### ISSUE TITLE
在文件中搜索不到字符串

### ISSUE THREAD

**Issue by whuper** [Microsoft/vscode#52148]
Issue Type: <b>Bug</b>

1 Mac 版，在文件中搜索字符串
2 只是搜索一个单词的部分连续字母
3 搜不到
4 但是，使用全局搜索，却可以搜到

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz (4 x 1400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|4.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.24.3
vetur|oct|0.12.5

</details>

**Comment by RMacfarlane** [comment]
Using google translate:

Searching for a string in a file

1 Mac version, searching for strings in a file
2 just search for a partial continuation of a word
3 not found
4 However, using a global search can be found

Can you check that none of the search options have been turned on?
<img width="253" alt="screen shot 2018-06-17 at 8 53 16 pm" src="https://user-images.githubusercontent.com/3672607/41517564-add906f0-7270-11e8-8b3a-27f1b8180b69.png">

Could you provide an example file and search string that has this problem?

**Comment by whuper** [comment]
![2018-06-18 10 58 16](https://user-images.githubusercontent.com/5762124/41544400-375cc652-734b-11e8-9bb8-2159cef81e6a.png)

确实是和全字匹配有关，我连续点击了‘全部匹配按钮’两次，就搜不到了

如果只点一次的话，是可以搜得到的

**Comment by RMacfarlane** [comment]
> It's really related to the whole word match. I clicked on the ‘all match button’ twice and I’m not able to find it.
>
> If you only have one point, it can be found

The behavior of search when you have whole word watch selected should be that it only finds complete word matches, and not matches where the text contains it. For example, if you search 'web' and have the text 'webview' in the file, 'webview' would not be found. Can you give a specific example of a search you tried, what options were checked, and what the actual and expected result were?

**Comment by whuper** [comment]
I found that it behaviors at the same way on windows 7 system.
Now I know how it works
Maybe it's not a bug, It's just  I'm using it in the wrong way!

You've solved my confusion,Thank you for your timely reply !

---------------------------
By the way
Here is the file and the string I'm searching for



[file.zip](https://github.com/Microsoft/vscode/files/2113525/file.zip)
