### ISSUE TITLE
[Flow] type can be used by only '.ts' files?

### ISSUE THREAD

**Issue by Beingbook** [Microsoft/vscode#5214]
- VSCode Version: 0.10.11
- OS Version: Mac 10.11.4

Steps to Reproduce:

1. I set type for return-type, argument-type and variable-type, etc.
2. Got this message
<img width="710" alt="2016-04-13 2 45 10" src="https://cloud.githubusercontent.com/assets/2682865/14483870/6c6a6612-0186-11e6-9b93-2a4fd5cb1065.png">

Type is not only for TypeScript. [Flow](http://flowtype.org/) can be used by other javascript

**Comment by egamma** [comment]
Code doesn't know about Flow by default. To teach it about flow you can:
- install the flow language extension https://marketplace.visualstudio.com/items?itemName=flowtype.flow-for-vscode
- associate .js files with the flow language (you need to upgrade to the insider build for that https://code.visualstudio.com/download?insiders=true). Here is how: https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/latest.md#file-to-language-association

Please let me know how this works for you.

**Comment by egamma** [comment]
@Beingbook could you try out what I suggested above?

**Comment by Beingbook** [comment]
@egamma sorry, I'm late.
I installed the flow extension and made the language type flow.
Result:
<img width="677" alt="2016-04-15 6 42 20" src="https://cloud.githubusercontent.com/assets/2682865/14557781/e3522e54-0339-11e6-8eae-a046d2899630.png">
I think it is still.

**Comment by Beingbook** [comment]
And [your last link](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/latest.md#file-to-language-association) looks broken

**Comment by Beingbook** [comment]
@egamma I retested the extension and it prevents `.ts` file only message but doesn't check type.

**Comment by egamma** [comment]
This is the broken link https://github.com/Microsoft/vscode-docs/blob/master/release-notes/latest.md#file-to-language-association sorry.

**Comment by egamma** [comment]
>@egamma I retested the extension and I saw it works correctly!

Did you retest it on Version 1.0?

**Comment by Beingbook** [comment]
@egamma yes my environment is 1.0

**Comment by egamma** [comment]
@Beingbook thanks for the confirmation - closing.

**Comment by ericwooley** [comment]
@egamma I know this is closed, but @egamma do you know of any way to run eslint as well? I can't seem to get it working with the flow language.

**Comment by egamma** [comment]
@ericwooley never done this, sorry. There is an eslint flow plugin that might help https://github.com/zertosh/eslint-plugin-flow-vars

**Comment by Beingbook** [comment]
@egamma vscode doesn't resolve eslint plugins in OSX El Cap latest. Hope you to check this.

**Comment by egamma** [comment]
@Beingbook this looks this issue https://github.com/Microsoft/vscode-eslint/issues/71

**Comment by laggingreflex** [comment]
This isn't working for me. I've installed the extension, associated the file extension, the project has flowconfig, `flow` CLI works, but VSCode still not recognizing flow. 

![image](https://cloud.githubusercontent.com/assets/2523987/24070359/dec9451e-0be1-11e7-9435-d9132bdc09d4.png)

**Comment by ChuksFestus** [comment]
set `"javascript.validate.enable": false` how? where pls am having same issues

**Comment by ChuksFestus** [comment]
oh..never mind, fixed

**Comment by Falconerd** [comment]
Doesn't setting `javascript.validate.enable` to `false` just disable ESLint?

Is ESLint not needed when using Flowtype?

My understanding is that they aren't mutually exclusive. Unless Flowtype lets you set rules for things like quotes, semicolons, spacing, etc?

**Comment by bhongy** [comment]
@Falconerd `javascript.validate.enable: false` works. I have ESLint and Flow Language Support extensions installed in Code. I followed the instruction from the [Flow Language Support extension repo](https://github.com/flowtype/flow-for-vscode#setup). Adding these two lines to my user settings.json

```
    "flow.useNPMPackagedFlow": true,
    "javascript.validate.enable": false,
```

I have ESLint setup in my repo using babel-eslint parser. Installed flow-bin and init it locally in my repo.

**Comment by laggingreflex** [comment]
It disables VSCode's inbuilt javascript validator which is still very important because you don't get errors like these highlighted anymore:

```
import _ from 'lodash';
import1 React from 'react'; <<< should cause "Cannot find name 'import1'" error
```
I haven't used flow much so I'm not sure if it completely takes care of errors like above, does it?

**Comment by bhongy** [comment]
@laggingreflex good to know!

For this particular instance, I use ESLint with babel-eslint parser, and it catches:

```javascript
import1 React from 'react'`  // [eslint] Parsing error: ...
```

**Comment by crucialfelix** [comment]
I have `flowtype.flow-for-vscode` installed. It does parse and display errors correctly. It is functioning. 

However the `only '.ts' files` error is still displayed everywhere there are type annotations.
I have followed the install directions exactly (several times to be sure).

There is no "flow" language that I can associate a file or all *.js files with. Just `JavaScript` and `JavaScript react`

**Comment by lautapercuspain** [comment]
This is a good eslint plugin that helps with this issue,
https://github.com/gajus/eslint-plugin-flowtype#eslint-plugin-flowtype-installation

**Comment by victorbenjamin** [comment]
Workspace Settings:

"javascript.validate.enable": false

**Comment by johnunclesam** [comment]
Any news on this?

**Comment by dijonkitchen** [comment]
The Flow plugin should really override just what's needed. Seem to be a lot of conflicts between JS checking, TS, and Flow.
