### ISSUE TITLE
Failed to install VS Code update

### ISSUE THREAD

**Issue by CisSasGot** [Microsoft/vscode#52159]
- VSCode Version: Insaider
- OS Version: Windows 10 Pro x64 ; build: 17134.112

# This is e attach of the following log file with error from update 
 
Jun 18 09:50:13.479 INFO Starting: C:\Program Files\Microsoft\VS Code Insiders\Code - Insiders.exe, false
Jun 18 09:50:13.487 INFO Checking for running Code - Insiders.exe processes... (attempt 1)
Jun 18 09:50:13.508 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:14.040 INFO Checking for running Code - Insiders.exe processes... (attempt 2)
Jun 18 09:50:14.116 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:14.627 INFO Checking for running Code - Insiders.exe processes... (attempt 3)
Jun 18 09:50:14.665 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:15.173 INFO Checking for running Code - Insiders.exe processes... (attempt 4)
Jun 18 09:50:15.207 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:15.708 INFO Checking for running Code - Insiders.exe processes... (attempt 5)
Jun 18 09:50:15.738 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:16.244 INFO Checking for running Code - Insiders.exe processes... (attempt 6)
Jun 18 09:50:16.279 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:16.781 INFO Checking for running Code - Insiders.exe processes... (attempt 7)
Jun 18 09:50:16.815 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:17.316 INFO Checking for running Code - Insiders.exe processes... (attempt 8)
Jun 18 09:50:17.346 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:17.848 INFO Checking for running Code - Insiders.exe processes... (attempt 9)
Jun 18 09:50:17.879 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:18.384 INFO Checking for running Code - Insiders.exe processes... (attempt 10)
Jun 18 09:50:18.418 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:18.919 INFO Checking for running Code - Insiders.exe processes... (attempt 11)
Jun 18 09:50:18.949 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:19.473 INFO Checking for running Code - Insiders.exe processes... (attempt 12)
Jun 18 09:50:19.513 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:20.095 INFO Checking for running Code - Insiders.exe processes... (attempt 13)
Jun 18 09:50:20.228 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:20.756 INFO Checking for running Code - Insiders.exe processes... (attempt 14)
Jun 18 09:50:20.843 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:21.383 INFO Checking for running Code - Insiders.exe processes... (attempt 15)
Jun 18 09:50:21.429 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:22.056 INFO Checking for running Code - Insiders.exe processes... (attempt 16)
Jun 18 09:50:22.190 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:22.719 INFO Checking for running Code - Insiders.exe processes... (attempt 17)
Jun 18 09:50:22.771 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:23.308 INFO Checking for running Code - Insiders.exe processes... (attempt 18)
Jun 18 09:50:23.357 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:23.863 INFO Checking for running Code - Insiders.exe processes... (attempt 19)
Jun 18 09:50:23.911 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:24.441 INFO Checking for running Code - Insiders.exe processes... (attempt 20)
Jun 18 09:50:24.511 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:25.014 INFO Checking for running Code - Insiders.exe processes... (attempt 21)
Jun 18 09:50:25.063 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:25.565 INFO Checking for running Code - Insiders.exe processes... (attempt 22)
Jun 18 09:50:25.603 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:26.104 INFO Checking for running Code - Insiders.exe processes... (attempt 23)
Jun 18 09:50:26.162 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:26.664 INFO Checking for running Code - Insiders.exe processes... (attempt 24)
Jun 18 09:50:26.710 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:27.213 INFO Checking for running Code - Insiders.exe processes... (attempt 25)
Jun 18 09:50:27.255 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:27.756 INFO Checking for running Code - Insiders.exe processes... (attempt 26)
Jun 18 09:50:27.794 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:28.296 INFO Checking for running Code - Insiders.exe processes... (attempt 27)
Jun 18 09:50:28.335 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:28.836 INFO Checking for running Code - Insiders.exe processes... (attempt 28)
Jun 18 09:50:28.872 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:29.374 INFO Checking for running Code - Insiders.exe processes... (attempt 29)
Jun 18 09:50:29.426 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:29.959 INFO Checking for running Code - Insiders.exe processes... (attempt 30)
Jun 18 09:50:29.990 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:30.493 INFO Checking for running Code - Insiders.exe processes... (attempt 31)
Jun 18 09:50:30.532 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:31.033 INFO Checking for running Code - Insiders.exe processes... (attempt 32)
Jun 18 09:50:31.077 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:31.578 INFO Checking for running Code - Insiders.exe processes... (attempt 33)
Jun 18 09:50:31.613 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:32.114 INFO Checking for running Code - Insiders.exe processes... (attempt 34)
Jun 18 09:50:32.156 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:32.672 INFO Checking for running Code - Insiders.exe processes... (attempt 35)
Jun 18 09:50:32.723 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:33.225 INFO Checking for running Code - Insiders.exe processes... (attempt 36)
Jun 18 09:50:33.294 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:33.803 INFO Checking for running Code - Insiders.exe processes... (attempt 37)
Jun 18 09:50:33.846 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:34.348 INFO Checking for running Code - Insiders.exe processes... (attempt 38)
Jun 18 09:50:34.403 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:34.904 INFO Checking for running Code - Insiders.exe processes... (attempt 39)
Jun 18 09:50:34.957 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:35.458 INFO Checking for running Code - Insiders.exe processes... (attempt 40)
Jun 18 09:50:35.493 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:35.997 INFO Checking for running Code - Insiders.exe processes... (attempt 41)
Jun 18 09:50:36.039 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:36.544 INFO Checking for running Code - Insiders.exe processes... (attempt 42)
Jun 18 09:50:36.590 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:37.092 INFO Checking for running Code - Insiders.exe processes... (attempt 43)
Jun 18 09:50:37.144 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:37.668 INFO Checking for running Code - Insiders.exe processes... (attempt 44)
Jun 18 09:50:37.703 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:38.239 INFO Checking for running Code - Insiders.exe processes... (attempt 45)
Jun 18 09:50:38.277 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:38.787 INFO Checking for running Code - Insiders.exe processes... (attempt 46)
Jun 18 09:50:38.846 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:39.349 INFO Checking for running Code - Insiders.exe processes... (attempt 47)
Jun 18 09:50:39.397 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:39.903 INFO Checking for running Code - Insiders.exe processes... (attempt 48)
Jun 18 09:50:39.953 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:40.458 INFO Checking for running Code - Insiders.exe processes... (attempt 49)
Jun 18 09:50:40.501 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:41.004 INFO Checking for running Code - Insiders.exe processes... (attempt 50)
Jun 18 09:50:41.058 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:41.559 INFO Checking for running Code - Insiders.exe processes... (attempt 51)
Jun 18 09:50:41.608 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:42.112 INFO Checking for running Code - Insiders.exe processes... (attempt 52)
Jun 18 09:50:42.158 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:42.661 INFO Checking for running Code - Insiders.exe processes... (attempt 53)
Jun 18 09:50:42.704 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:43.205 INFO Checking for running Code - Insiders.exe processes... (attempt 54)
Jun 18 09:50:43.248 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:43.749 INFO Checking for running Code - Insiders.exe processes... (attempt 55)
Jun 18 09:50:43.793 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:44.294 INFO Checking for running Code - Insiders.exe processes... (attempt 56)
Jun 18 09:50:44.336 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:44.838 INFO Checking for running Code - Insiders.exe processes... (attempt 57)
Jun 18 09:50:44.874 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:45.376 INFO Checking for running Code - Insiders.exe processes... (attempt 58)
Jun 18 09:50:45.424 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:45.927 INFO Checking for running Code - Insiders.exe processes... (attempt 59)
Jun 18 09:50:45.972 INFO Code - Insiders.exe is running, wait a bit
Jun 18 09:50:46.474 INFO Checking for running Code - Insiders.exe processes... (attempt 60)
Jun 18 09:50:46.514 INFO Gave up waiting for Code - Insiders.exe to exit
Jun 18 09:50:46.515 INFO Checking for possible conflicting running processes... (attempt 1)
Jun 18 09:50:46.554 INFO Kill process if found: 12244, Code - Insiders.exe
Jun 18 09:50:46.554 INFO Found Code - Insiders.exe running, pid 12244, attempting to kill...
Jun 18 09:50:46.554 INFO Kill process if found: 11328, Code - Insiders.exe
Jun 18 09:50:46.556 INFO Found Code - Insiders.exe running, pid 11328, attempting to kill...
Jun 18 09:50:46.556 INFO Kill process if found: 8012, Code - Insiders.exe
Jun 18 09:50:46.556 INFO Found Code - Insiders.exe running, pid 8012, attempting to kill...
Jun 18 09:50:46.556 INFO Kill process if found: 9624, Code - Insiders.exe
Jun 18 09:50:46.557 INFO Found Code - Insiders.exe running, pid 9624, attempting to kill...
Jun 18 09:50:46.557 INFO Kill process if found: 8748, Code - Insiders.exe
Jun 18 09:50:46.558 INFO Found Code - Insiders.exe running, pid 8748, attempting to kill...
Jun 18 09:50:46.558 INFO Successfully killed Code - Insiders.exe, pid 8748
Jun 18 09:50:46.559 INFO Kill process if found: 12924, Code - Insiders.exe
Jun 18 09:50:46.561 INFO Kill process if found: 9772, Code - Insiders.exe
Jun 18 09:50:46.561 INFO Found Code - Insiders.exe running, pid 9772, attempting to kill...
Jun 18 09:50:46.562 INFO Kill process if found: 12060, Code - Insiders.exe
Jun 18 09:50:46.562 INFO Found Code - Insiders.exe running, pid 12060, attempting to kill...
Jun 18 09:50:46.562 INFO Kill process if found: 28180, Code - Insiders.exe
Jun 18 09:50:46.562 INFO Found Code - Insiders.exe running, pid 28180, attempting to kill...
Jun 18 09:50:46.564 WARN Kill error Failed to kill process
Jun 18 09:50:46.564 WARN Kill error Failed to kill process
Jun 18 09:50:46.564 WARN Kill error Failed to kill process
Jun 18 09:50:46.564 WARN Kill error Failed to kill process
Jun 18 09:50:46.565 WARN Kill error Failed to get process file name: Odmowa dostępu.

Jun 18 09:50:46.565 WARN Kill error Failed to kill process
Jun 18 09:50:46.566 WARN Kill error Failed to kill process
Jun 18 09:50:46.566 WARN Kill error Failed to kill process
Jun 18 09:50:46.612 INFO Checking for possible conflicting running processes... (attempt 2)
Jun 18 09:50:46.652 INFO Kill process if found: 12244, Code - Insiders.exe
Jun 18 09:50:46.652 INFO Found Code - Insiders.exe running, pid 12244, attempting to kill...
Jun 18 09:50:46.653 INFO Kill process if found: 11328, Code - Insiders.exe
Jun 18 09:50:46.653 INFO Found Code - Insiders.exe running, pid 11328, attempting to kill...
Jun 18 09:50:46.654 INFO Kill process if found: 8012, Code - Insiders.exe
Jun 18 09:50:46.654 INFO Found Code - Insiders.exe running, pid 8012, attempting to kill...
Jun 18 09:50:46.655 INFO Kill process if found: 9624, Code - Insiders.exe
Jun 18 09:50:46.655 INFO Found Code - Insiders.exe running, pid 9624, attempting to kill...
Jun 18 09:50:46.656 INFO Kill process if found: 12924, Code - Insiders.exe
Jun 18 09:50:46.656 INFO Kill process if found: 9772, Code - Insiders.exe
Jun 18 09:50:46.657 INFO Found Code - Insiders.exe running, pid 9772, attempting to kill...
Jun 18 09:50:46.658 INFO Kill process if found: 12060, Code - Insiders.exe
Jun 18 09:50:46.658 INFO Found Code - Insiders.exe running, pid 12060, attempting to kill...
Jun 18 09:50:46.658 INFO Kill process if found: 28180, Code - Insiders.exe
Jun 18 09:50:46.659 INFO Found Code - Insiders.exe running, pid 28180, attempting to kill...
Jun 18 09:50:46.659 WARN Kill error Failed to kill process
Jun 18 09:50:46.660 WARN Kill error Failed to kill process
Jun 18 09:50:46.660 WARN Kill error Failed to kill process
Jun 18 09:50:46.661 WARN Kill error Failed to kill process
Jun 18 09:50:46.662 WARN Kill error Failed to get process file name: Odmowa dostępu.

Jun 18 09:50:46.662 WARN Kill error Failed to kill process
Jun 18 09:50:46.663 WARN Kill error Failed to kill process
Jun 18 09:50:46.663 WARN Kill error Failed to kill process
Jun 18 09:50:46.857 INFO Checking for possible conflicting running processes... (attempt 3)
Jun 18 09:50:46.899 INFO Kill process if found: 12244, Code - Insiders.exe
Jun 18 09:50:46.901 INFO Found Code - Insiders.exe running, pid 12244, attempting to kill...
Jun 18 09:50:46.902 INFO Kill process if found: 11328, Code - Insiders.exe
Jun 18 09:50:46.903 INFO Found Code - Insiders.exe running, pid 11328, attempting to kill...
Jun 18 09:50:46.904 INFO Kill process if found: 8012, Code - Insiders.exe
Jun 18 09:50:46.904 INFO Found Code - Insiders.exe running, pid 8012, attempting to kill...
Jun 18 09:50:46.905 INFO Kill process if found: 9624, Code - Insiders.exe
Jun 18 09:50:46.905 INFO Found Code - Insiders.exe running, pid 9624, attempting to kill...
Jun 18 09:50:46.906 INFO Kill process if found: 12924, Code - Insiders.exe
Jun 18 09:50:46.906 INFO Kill process if found: 9772, Code - Insiders.exe
Jun 18 09:50:46.907 INFO Found Code - Insiders.exe running, pid 9772, attempting to kill...
Jun 18 09:50:46.907 INFO Kill process if found: 12060, Code - Insiders.exe
Jun 18 09:50:46.908 INFO Found Code - Insiders.exe running, pid 12060, attempting to kill...
Jun 18 09:50:46.908 INFO Kill process if found: 28180, Code - Insiders.exe
Jun 18 09:50:46.909 INFO Found Code - Insiders.exe running, pid 28180, attempting to kill...
Jun 18 09:50:46.909 WARN Kill error Failed to kill process
Jun 18 09:50:46.910 WARN Kill error Failed to kill process
Jun 18 09:50:46.910 WARN Kill error Failed to kill process
Jun 18 09:50:46.911 WARN Kill error Failed to kill process
Jun 18 09:50:46.912 WARN Kill error Failed to get process file name: Odmowa dostępu.

Jun 18 09:50:46.912 WARN Kill error Failed to kill process
Jun 18 09:50:46.913 WARN Kill error Failed to kill process
Jun 18 09:50:46.913 WARN Kill error Failed to kill process
Jun 18 09:50:47.357 INFO Checking for possible conflicting running processes... (attempt 4)
Jun 18 09:50:47.396 INFO Kill process if found: 12244, Code - Insiders.exe
Jun 18 09:50:47.397 INFO Found Code - Insiders.exe running, pid 12244, attempting to kill...
Jun 18 09:50:47.397 INFO Kill process if found: 11328, Code - Insiders.exe
Jun 18 09:50:47.398 INFO Found Code - Insiders.exe running, pid 11328, attempting to kill...
Jun 18 09:50:47.398 INFO Kill process if found: 8012, Code - Insiders.exe
Jun 18 09:50:47.398 INFO Found Code - Insiders.exe running, pid 8012, attempting to kill...
Jun 18 09:50:47.399 INFO Kill process if found: 9624, Code - Insiders.exe
Jun 18 09:50:47.400 INFO Found Code - Insiders.exe running, pid 9624, attempting to kill...
Jun 18 09:50:47.400 INFO Kill process if found: 12924, Code - Insiders.exe
Jun 18 09:50:47.401 INFO Kill process if found: 9772, Code - Insiders.exe
Jun 18 09:50:47.401 INFO Found Code - Insiders.exe running, pid 9772, attempting to kill...
Jun 18 09:50:47.402 INFO Kill process if found: 12060, Code - Insiders.exe
Jun 18 09:50:47.403 INFO Found Code - Insiders.exe running, pid 12060, attempting to kill...
Jun 18 09:50:47.403 INFO Kill process if found: 28180, Code - Insiders.exe
Jun 18 09:50:47.404 INFO Found Code - Insiders.exe running, pid 28180, attempting to kill...
Jun 18 09:50:47.404 WARN Kill error Failed to kill process
Jun 18 09:50:47.405 WARN Kill error Failed to kill process
Jun 18 09:50:47.405 WARN Kill error Failed to kill process
Jun 18 09:50:47.406 WARN Kill error Failed to kill process
Jun 18 09:50:47.406 WARN Kill error Failed to get process file name: Odmowa dostępu.

Jun 18 09:50:47.407 WARN Kill error Failed to kill process
Jun 18 09:50:47.407 WARN Kill error Failed to kill process
Jun 18 09:50:47.408 WARN Kill error Failed to kill process
Jun 18 09:50:48.202 INFO Checking for possible conflicting running processes... (attempt 5)
Jun 18 09:50:48.242 INFO Kill process if found: 12244, Code - Insiders.exe
Jun 18 09:50:48.243 INFO Found Code - Insiders.exe running, pid 12244, attempting to kill...
Jun 18 09:50:48.243 INFO Kill process if found: 11328, Code - Insiders.exe
Jun 18 09:50:48.244 INFO Found Code - Insiders.exe running, pid 11328, attempting to kill...
Jun 18 09:50:48.244 INFO Kill process if found: 8012, Code - Insiders.exe
Jun 18 09:50:48.245 INFO Found Code - Insiders.exe running, pid 8012, attempting to kill...
Jun 18 09:50:48.245 INFO Kill process if found: 9624, Code - Insiders.exe
Jun 18 09:50:48.246 INFO Found Code - Insiders.exe running, pid 9624, attempting to kill...
Jun 18 09:50:48.246 INFO Kill process if found: 12924, Code - Insiders.exe
Jun 18 09:50:48.247 INFO Kill process if found: 9772, Code - Insiders.exe
Jun 18 09:50:48.247 INFO Found Code - Insiders.exe running, pid 9772, attempting to kill...
Jun 18 09:50:48.248 INFO Kill process if found: 12060, Code - Insiders.exe
Jun 18 09:50:48.248 INFO Found Code - Insiders.exe running, pid 12060, attempting to kill...
Jun 18 09:50:48.249 INFO Kill process if found: 28180, Code - Insiders.exe
Jun 18 09:50:48.250 INFO Found Code - Insiders.exe running, pid 28180, attempting to kill...
Jun 18 09:50:48.250 WARN Kill error Failed to kill process
Jun 18 09:50:48.251 WARN Kill error Failed to kill process
Jun 18 09:50:48.251 WARN Kill error Failed to kill process
Jun 18 09:50:48.252 WARN Kill error Failed to kill process
Jun 18 09:50:48.252 WARN Kill error Failed to get process file name: Odmowa dostępu.

Jun 18 09:50:48.253 WARN Kill error Failed to kill process
Jun 18 09:50:48.253 WARN Kill error Failed to kill process
Jun 18 09:50:48.254 WARN Kill error Failed to kill process
Jun 18 09:50:49.497 INFO Checking for possible conflicting running processes... (attempt 6)
Jun 18 09:50:49.545 INFO Kill process if found: 12244, Code - Insiders.exe
Jun 18 09:50:49.545 INFO Found Code - Insiders.exe running, pid 12244, attempting to kill...
Jun 18 09:50:49.546 INFO Kill process if found: 11328, Code - Insiders.exe
Jun 18 09:50:49.546 INFO Found Code - Insiders.exe running, pid 11328, attempting to kill...
Jun 18 09:50:49.547 INFO Kill process if found: 8012, Code - Insiders.exe
Jun 18 09:50:49.547 INFO Found Code - Insiders.exe running, pid 8012, attempting to kill...
Jun 18 09:50:49.548 INFO Kill process if found: 9624, Code - Insiders.exe
Jun 18 09:50:49.548 INFO Found Code - Insiders.exe running, pid 9624, attempting to kill...
Jun 18 09:50:49.548 INFO Kill process if found: 12924, Code - Insiders.exe
Jun 18 09:50:49.549 INFO Kill process if found: 9772, Code - Insiders.exe
Jun 18 09:50:49.549 INFO Found Code - Insiders.exe running, pid 9772, attempting to kill...
Jun 18 09:50:49.550 INFO Kill process if found: 12060, Code - Insiders.exe
Jun 18 09:50:49.550 INFO Found Code - Insiders.exe running, pid 12060, attempting to kill...
Jun 18 09:50:49.551 INFO Kill process if found: 28180, Code - Insiders.exe
Jun 18 09:50:49.551 INFO Found Code - Insiders.exe running, pid 28180, attempting to kill...
Jun 18 09:50:49.552 WARN Kill error Failed to kill process
Jun 18 09:50:49.552 WARN Kill error Failed to kill process
Jun 18 09:50:49.553 WARN Kill error Failed to kill process
Jun 18 09:50:49.553 WARN Kill error Failed to kill process
Jun 18 09:50:49.554 WARN Kill error Failed to get process file name: Odmowa dostępu.

Jun 18 09:50:49.554 WARN Kill error Failed to kill process
Jun 18 09:50:49.555 WARN Kill error Failed to kill process
Jun 18 09:50:49.555 WARN Kill error Failed to kill process
Jun 18 09:50:51.352 INFO Checking for possible conflicting running processes... (attempt 7)
Jun 18 09:50:51.392 INFO Kill process if found: 12244, Code - Insiders.exe
Jun 18 09:50:51.393 INFO Kill process if found: 11328, Code - Insiders.exe
Jun 18 09:50:51.394 INFO Found Code - Insiders.exe running, pid 11328, attempting to kill...
Jun 18 09:50:51.395 INFO Kill process if found: 8012, Code - Insiders.exe
Jun 18 09:50:51.395 INFO Found Code - Insiders.exe running, pid 8012, attempting to kill...
Jun 18 09:50:51.396 INFO Kill process if found: 9624, Code - Insiders.exe
Jun 18 09:50:51.396 INFO Found Code - Insiders.exe running, pid 9624, attempting to kill...
Jun 18 09:50:51.397 INFO Kill process if found: 12924, Code - Insiders.exe
Jun 18 09:50:51.397 INFO Kill process if found: 9772, Code - Insiders.exe
Jun 18 09:50:51.398 INFO Found Code - Insiders.exe running, pid 9772, attempting to kill...
Jun 18 09:50:51.399 INFO Kill process if found: 12060, Code - Insiders.exe
Jun 18 09:50:51.400 INFO Found Code - Insiders.exe running, pid 12060, attempting to kill...
Jun 18 09:50:51.400 INFO Kill process if found: 28180, Code - Insiders.exe
Jun 18 09:50:51.401 INFO Found Code - Insiders.exe running, pid 28180, attempting to kill...
Jun 18 09:50:51.401 WARN Kill error Failed to get process file name: Odmowa dostępu.

Jun 18 09:50:51.402 WARN Kill error Failed to kill process
Jun 18 09:50:51.402 WARN Kill error Failed to kill process
Jun 18 09:50:51.403 WARN Kill error Failed to kill process
Jun 18 09:50:51.403 WARN Kill error Failed to get process file name: Odmowa dostępu.

Jun 18 09:50:51.404 WARN Kill error Failed to kill process
Jun 18 09:50:51.404 WARN Kill error Failed to kill process
Jun 18 09:50:51.404 WARN Kill error Failed to kill process
Jun 18 09:50:53.852 INFO Checking for possible conflicting running processes... (attempt 8)
Jun 18 09:50:53.888 INFO Kill process if found: 12244, Code - Insiders.exe
Jun 18 09:50:53.895 INFO Kill process if found: 11328, Code - Insiders.exe
Jun 18 09:50:53.896 INFO Found Code - Insiders.exe running, pid 11328, attempting to kill...
Jun 18 09:50:53.897 INFO Kill process if found: 8012, Code - Insiders.exe
Jun 18 09:50:53.898 INFO Found Code - Insiders.exe running, pid 8012, attempting to kill...
Jun 18 09:50:53.899 INFO Kill process if found: 9624, Code - Insiders.exe
Jun 18 09:50:53.899 INFO Found Code - Insiders.exe running, pid 9624, attempting to kill...
Jun 18 09:50:53.900 INFO Kill process if found: 12924, Code - Insiders.exe
Jun 18 09:50:53.900 INFO Kill process if found: 9772, Code - Insiders.exe
Jun 18 09:50:53.901 INFO Found Code - Insiders.exe running, pid 9772, attempting to kill...
Jun 18 09:50:53.901 INFO Kill process if found: 12060, Code - Insiders.exe
Jun 18 09:50:53.902 INFO Found Code - Insiders.exe running, pid 12060, attempting to kill...
Jun 18 09:50:53.902 INFO Kill process if found: 28180, Code - Insiders.exe
Jun 18 09:50:53.903 INFO Found Code - Insiders.exe running, pid 28180, attempting to kill...
Jun 18 09:50:53.903 WARN Kill error Failed to get process file name: Odmowa dostępu.

Jun 18 09:50:53.903 WARN Kill error Failed to kill process
Jun 18 09:50:53.904 WARN Kill error Failed to kill process
Jun 18 09:50:53.904 WARN Kill error Failed to kill process
Jun 18 09:50:53.905 WARN Kill error Failed to get process file name: Odmowa dostępu.

Jun 18 09:50:53.905 WARN Kill error Failed to kill process
Jun 18 09:50:53.906 WARN Kill error Failed to kill process
Jun 18 09:50:53.906 WARN Kill error Failed to kill process
Jun 18 09:50:57.140 INFO Checking for possible conflicting running processes... (attempt 9)
Jun 18 09:50:57.222 INFO Kill process if found: 12244, Code - Insiders.exe
Jun 18 09:50:57.223 INFO Kill process if found: 11328, Code - Insiders.exe
Jun 18 09:50:57.224 INFO Found Code - Insiders.exe running, pid 11328, attempting to kill...
Jun 18 09:50:57.224 INFO Kill process if found: 8012, Code - Insiders.exe
Jun 18 09:50:57.225 INFO Found Code - Insiders.exe running, pid 8012, attempting to kill...
Jun 18 09:50:57.226 INFO Kill process if found: 9624, Code - Insiders.exe
Jun 18 09:50:57.226 INFO Found Code - Insiders.exe running, pid 9624, attempting to kill...
Jun 18 09:50:57.227 INFO Kill process if found: 12924, Code - Insiders.exe
Jun 18 09:50:57.227 INFO Kill process if found: 9772, Code - Insiders.exe
Jun 18 09:50:57.228 INFO Found Code - Insiders.exe running, pid 9772, attempting to kill...
Jun 18 09:50:57.228 INFO Kill process if found: 12060, Code - Insiders.exe
Jun 18 09:50:57.229 INFO Found Code - Insiders.exe running, pid 12060, attempting to kill...
Jun 18 09:50:57.229 INFO Kill process if found: 28180, Code - Insiders.exe
Jun 18 09:50:57.230 INFO Found Code - Insiders.exe running, pid 28180, attempting to kill...
Jun 18 09:50:57.230 WARN Kill error Failed to get process file name: Odmowa dostępu.

Jun 18 09:50:57.231 WARN Kill error Failed to kill process
Jun 18 09:50:57.231 WARN Kill error Failed to kill process
Jun 18 09:50:57.232 WARN Kill error Failed to kill process
Jun 18 09:50:57.232 WARN Kill error Failed to get process file name: Odmowa dostępu.

Jun 18 09:50:57.233 WARN Kill error Failed to kill process
Jun 18 09:50:57.233 WARN Kill error Failed to kill process
Jun 18 09:50:57.234 WARN Kill error Failed to kill process
Jun 18 09:51:01.279 INFO Checking for possible conflicting running processes... (attempt 10)
Jun 18 09:51:01.318 INFO Kill process if found: 12244, Code - Insiders.exe
Jun 18 09:51:01.322 INFO Kill process if found: 11328, Code - Insiders.exe
Jun 18 09:51:01.323 INFO Found Code - Insiders.exe running, pid 11328, attempting to kill...
Jun 18 09:51:01.324 INFO Kill process if found: 8012, Code - Insiders.exe
Jun 18 09:51:01.325 INFO Kill process if found: 9624, Code - Insiders.exe
Jun 18 09:51:01.326 INFO Found Code - Insiders.exe running, pid 9624, attempting to kill...
Jun 18 09:51:01.326 INFO Kill process if found: 12924, Code - Insiders.exe
Jun 18 09:51:01.326 INFO Kill process if found: 9772, Code - Insiders.exe
Jun 18 09:51:01.327 INFO Found Code - Insiders.exe running, pid 9772, attempting to kill...
Jun 18 09:51:01.327 INFO Kill process if found: 12060, Code - Insiders.exe
Jun 18 09:51:01.328 INFO Kill process if found: 28180, Code - Insiders.exe
Jun 18 09:51:01.328 INFO Found Code - Insiders.exe running, pid 28180, attempting to kill...
Jun 18 09:51:01.329 WARN Kill error Failed to get process file name: Odmowa dostępu.

Jun 18 09:51:01.330 WARN Kill error Failed to kill process
Jun 18 09:51:01.330 WARN Kill error Failed to get process file name: Odmowa dostępu.

Jun 18 09:51:01.331 WARN Kill error Failed to kill process
Jun 18 09:51:01.331 WARN Kill error Failed to get process file name: Odmowa dostępu.

Jun 18 09:51:01.332 WARN Kill error Failed to kill process
Jun 18 09:51:01.332 WARN Kill error Failed to get process file name: Odmowa dostępu.

Jun 18 09:51:01.333 WARN Kill error Failed to kill process
Jun 18 09:51:06.328 INFO Checking for possible conflicting running processes... (attempt 11)
Jun 18 09:51:06.372 INFO Kill process if found: 12244, Code - Insiders.exe
Jun 18 09:51:06.373 INFO Kill process if found: 11328, Code - Insiders.exe
Jun 18 09:51:06.373 INFO Found Code - Insiders.exe running, pid 11328, attempting to kill...
Jun 18 09:51:06.374 INFO Kill process if found: 8012, Code - Insiders.exe
Jun 18 09:51:06.374 INFO Kill process if found: 9624, Code - Insiders.exe
Jun 18 09:51:06.375 INFO Found Code - Insiders.exe running, pid 9624, attempting to kill...
Jun 18 09:51:06.375 INFO Kill process if found: 12924, Code - Insiders.exe
Jun 18 09:51:06.376 INFO Kill process if found: 9772, Code - Insiders.exe
Jun 18 09:51:06.376 INFO Found Code - Insiders.exe running, pid 9772, attempting to kill...
Jun 18 09:51:06.377 INFO Kill process if found: 12060, Code - Insiders.exe
Jun 18 09:51:06.377 INFO Kill process if found: 28180, Code - Insiders.exe
Jun 18 09:51:06.378 INFO Found Code - Insiders.exe running, pid 28180, attempting to kill...
Jun 18 09:51:06.378 WARN Kill error Failed to get process file name: Odmowa dostępu.

Jun 18 09:51:06.379 WARN Kill error Failed to kill process
Jun 18 09:51:06.379 WARN Kill error Failed to get process file name: Odmowa dostępu.

Jun 18 09:51:06.380 WARN Kill error Failed to kill process
Jun 18 09:51:06.380 WARN Kill error Failed to get process file name: Odmowa dostępu.

Jun 18 09:51:06.381 WARN Kill error Failed to kill process
Jun 18 09:51:06.381 WARN Kill error Failed to get process file name: Odmowa dostępu.

Jun 18 09:51:06.382 WARN Kill error Failed to kill process
Jun 18 09:51:06.383 ERRO Failed to kill process

**Comment by joaomoreno** [comment]
You seem to have #47841.

Please read this comment if you can provide more detail: https://github.com/Microsoft/vscode/issues/47841#issuecomment-393101777

Please read this one to disable background updates: https://github.com/Microsoft/vscode/issues/47841#issuecomment-395017687
