### ISSUE TITLE
Cannot resize Markdown preview tab

### ISSUE THREAD

**Issue by neilsustc** [Microsoft/vscode#52150]
Issue Type: <b>Bug</b>

- Open a Markdown file
- Toggle preview to the side
- Try to resize (horizontally) the preview tab

I guess it is related to the new grid layout feature.

VS Code version: Code - Insiders 1.25.0-insider (7dc9539a421c9c33e57e2ce0b718f183bb44c756, 2018-06-15T05:17:41.405Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (3.11GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by neilsustc** [comment]
The bot seems to have assigned a wrong label 😳

@joaomoreno since I find that there are some layout constraints added in the recent commits.

**Comment by bpasero** [comment]
I can reproduce.

**Comment by bpasero** [comment]
@joaomoreno thanks!

Reported to Electron as https://github.com/electron/electron/issues/13278
