### ISSUE TITLE
Uninstall VSCode from MacOS

### ISSUE THREAD

**Issue by budarin** [Microsoft/vscode#52151]
I can not uninstall VSCode from MacOS
I have deleted every Code, Microsoft Visual Code, com.microsoft.vs* and etc file from Library, Cache and other folder on my Mac, but cold not delete VSCode

I want a simple way to uninstall VSCode from Mac OS

**Comment by RMacfarlane** [comment]
@budarin Deleting the "Visual Studio Code" file from your `Applications` folder should remove it. Extension data is stored at `~/.vscode/extensions/`

**Comment by budarin** [comment]
thanks
