### ISSUE TITLE
Need browser (Chrome) like new window dimensions 

### ISSUE THREAD

**Issue by kzhui125** [Microsoft/vscode#52153]
OS: Windows

------
what Chrome does:

case 1:
1. first, open a window(`WINDOW1`), resize to `SIZE1` (not maximized).
2. open a new window(`WINDOW2`), ==> `WINDOW2` is `SIZE1` (**expected**).

case 2:
1. first, open a window(`WINDOW1`), resize to `SIZE1` (not maximized)
2. maximize `WINDOW1`
3. open a new window(`WINDOW2`), ==> `WINDOW2` is maximized (**expected**).
4. restore `WINDOW2`. ==> `WINDOW2` is `SIZE1` (**expected**).

case 3:
1. first, open a window(`WINDOW1`), resize to `SIZE1` (not maximized)
2. make `WINDOW1` full screen(F11)
3. open a new window(`WINDOW2`), ==> `WINDOW2` is SIZE1 (**good**).

------
what VSCode does:

## set "window.newWindowDimensions": "default"

a new window will open in the center of the screen with **very small** dimensions.

## set "window.newWindowDimensions": "inherit"

case 1:
1. first, open a window(`WINDOW1`), resize to `SIZE1` (not maximized).
2. open a new window(`WINDOW2`), ==> `WINDOW2` is `SIZE1` (**expected**).

case 2:
1. first, open a window(`WINDOW1`), resize to `SIZE1` (not maximized)
2. maximize `WINDOW1`
3. open a new window(`WINDOW2`), ==> `WINDOW2` is maximized (**expected**).
4. restore `WINDOW2`. ==> `WINDOW2` is not `SIZE1`, and it's **very small**. (**unexpected**).

case 3:
1. first, open a window(`WINDOW1`), resize to `SIZE1` (not maximized)
2. make `WINDOW1` full screen(F11)
3. open a new window(`WINDOW2`) ==> `WINDOW2` is  full screen.
4. F11 ==> `WINDOW2` is  maximized.
5. restore `WINDOW2`. ==> `WINDOW2` is not `SIZE1`, and it's **very small**. (**unexpected**).

------

**Comment by bpasero** [comment]
@kzhui125 so the issue you are talking about is that when you restore a window that opened maximized, it does not have the size the first window had when that one was not maximized?

**Comment by kzhui125** [comment]
yes @bpasero

**Comment by bpasero** [comment]
I think we can merge this into https://github.com/Microsoft/vscode/issues/422

**Comment by kzhui125** [comment]
@bpasero 

  // Controls the dimensions of opening a new window when at least one window is already opened. By default, a new window will open in the center of the screen with **small dimensions**. When set to 'inherit', the window will get the same dimensions as the last window that was active. When set to 'maximized', the window will open maximized and fullscreen if configured to 'fullscreen'. Note that this setting does not have an impact on the first window that is opened. The first window will always restore the size and location as you left it before closing.
  "window.newWindowDimensions": "default",

Why do you open with **small dimensions**?

Why not open with **normal dimensions** by default?!!

It's too small.
