### ISSUE TITLE
Paths start with slash in Open Editors pane

### ISSUE THREAD

**Issue by vvs** [Microsoft/vscode#52156]
Issue Type: <b>Bug</b>

This seems to be a recent change (or regression?)

The paths shown in the Open Editors pane now start with slash, which is quite visually distracting and ugly in my opinion.

If I am not mistaken, there were similar regressions in the past that were reverted to the default behavior (no slash).

VS Code version: Code - Insiders 1.25.0-insider (777c8e57e0eb1cbffb87a57ffd4f9c3d274f9429, 2018-06-18T05:15:57.671Z)
OS version: Windows_NT x64 10.0.17134

**Comment by vvs** [comment]
![vs-slash](https://user-images.githubusercontent.com/9781/41520975-963df63a-72d0-11e8-8e4d-1f4580e41617.jpg)
Here's the screenshot of the issue.

**Comment by isidorn** [comment]
@vvs that's a great catch, thanks a lot!
I have pushed a fix, so you should see the correct thing in vscode insiders from tomorrow. Let us know if that fixes the issue for you. Thanks!

**Comment by vvs** [comment]
Verified! :) Many thanks!

**Comment by isidorn** [comment]
Thanks, adding verified label
