### ISSUE TITLE
Shortcut keys `up` or `down` for markdown navigation

### ISSUE THREAD

**Issue by DingYuanfang** [Microsoft/vscode#5215]
- VSCode Version:0.10.11
- OS Version:windows 8.1

### Issues:
Although markdown preview window to get the focus, but must pass through the mouse to click can use shortcut keys to scroll through the `up` or `down`.

### I also hope:
Open two Windows ，a Markdown Edit window and a  Markdown  the preview window, preview window and edit window current view content binding, preview window response editor window scroll.

1. Open any project ,Open a .md file

2. Use shortcuts `ctrl+shift+v` ,Press the keyboard   `up` or 'down'

**Comment by bpasero** [comment]
These keys work for me.
