### ISSUE TITLE
[Accessibility]A11y_VSCode_KeyboardShortcuts_Screenreader: NVDA is reading "Sort by precedence" button as checkbox 

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#52155]
**Environment Details:**
VSCode Version : 1.24.0
OS Version : Win10

**Additional Details:**
Screenreader,NVDA[2018.2],JAWS[18.0.5038],MAS1.3.1

**Repro Steps:**
1. Launch VS Code while NVDA is ON.
2. Navigate to Settings icon in Activity Bar->Press Enter->Select "Keyboard Shortcuts" from dropdown.
3.Navigate to "Sort by precedence" button which is located inside the "Search keybindings" edit text field.
4.Observed that NVDA is reading "sort by precedence" button as check box. 

**Actual:**
NVDA is reading the "sort by precedence" button as check box. 

Same issue is observed in jaws

**Expected:**
NVDA should reads the "sort by precedence" button as push button instead of check box. 

**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
[https://microsoft.sharepoint.com/teams/msenable/mas/Pages/browse-fixes.aspx](url)

**User Impact:**
User will get confused what is the role and type of control.

**MAS Reference:**
MAS1.3.1: [https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}](url)

**Attachment For Reference:**
[[Accessibility]A11y_VSCode_KeyboardShortcuts_Screenreader.pptx](https://github.com/Microsoft/vscode/files/2110086/Accessibility.A11y_VSCode_KeyboardShortcuts_Screenreader.pptx)
Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
Its a check box to toggle sort by precedence on and off. So it is expected.
