### ISSUE TITLE
Search panel open in lower panel, shortcut missing in sidebar

### ISSUE THREAD

**Issue by roroland** [Microsoft/vscode#52168]
- VSCode Version: Version 1.24.1 (1.24.1)
- OS Version: Mac OS High Sierra

Steps to Reproduce:

1. Accidentally hide search icon in sidebar
2. Search panel shows in bottom panel
3. No way to restore search panel and search icon to the sidebar as usual
4. Right-click menu doesn't show search to restore normal state.

<img width="222" alt="screen shot 2018-06-18 at 05 40 02" src="https://user-images.githubusercontent.com/200220/41526397-8161be60-72ba-11e8-93ee-41529623143c.png">
<img width="857" alt="screen shot 2018-06-18 at 05 40 30" src="https://user-images.githubusercontent.com/200220/41526403-84be141e-72ba-11e8-8f49-03492c204f4b.png">

Does this issue occur when all extensions are disabled?: Yes

Besides this the search works fine, just want to restore normal UI behavior.

**Comment by isidorn** [comment]
Open settings, delete `search.location` setting
