### ISSUE TITLE
React JSX code block syntax highlight not working.

### ISSUE THREAD

**Issue by xinhuang327** [Microsoft/vscode#5216]
VSCode's support for React development is awesome except for JSX evaluated block's syntax highlight, code within curly braces can only show with only one color.

I have tried to tweak TypeScriptReact tmTheme and tmLanguage file, but I found tmTheme won't treat code inside curly braces as common JS expressions, and I cannot get consistent colors like code outside of markups. 

It would be nice to be able to distinguish tag name, attributes, keywords, quoted string,  constant by color, whether it's in or outside of JSX curly braces.

I think it shouldn't be too hard to fix this, how can it be done?

- VSCode Version: 0.10.11
- OS Version: OSX 10.11.4

![screen shot 2016-04-13 at 3 03 48 pm](https://cloud.githubusercontent.com/assets/6767625/14485339/01b5ec94-0189-11e6-8ca5-31c2a66f424a.png)

**Comment by aeschli** [comment]
related to #3008
