### ISSUE TITLE
Gear button has a border in search

### ISSUE THREAD

**Issue by oneslash** [microsoft/vscode#52161]
<img width="266" alt="screen shot 2018-06-18 at 10 03 10" src="https://user-images.githubusercontent.com/15870134/41524781-e10a3dfa-72de-11e8-9848-3ca2b36aa55e.png">

Issue Type: <b>Bug</b>

-  Search in Folder
- Click on the gear of "files to exclude"
- Focus on editor
- Border stays

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|16.00GB (0.86GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
gc-excelviewer|Gra|2.0.21
vscode-docker|Pet|0.0.27
gitignore|cod|0.5.0
systemd-unit-file|coo|1.0.0
vscode-eslint|dba|1.4.12
ansible-vault|dho|0.1.3
tslint|eg2|1.0.32
vscode-npm-script|eg2|0.3.4
terraform-autocomplete|erd|0.0.8
flow-for-vscode|flo|0.8.1
terraform|mau|1.1.2
dotenv|mik|1.0.1
python|ms-|2018.5.0
cpptools|ms-|0.17.4
Go|ms-|0.6.83
jenkinsfile-support|sec|0.1.0
vscode-nginx|sha|0.5.0
cmake|twx|0.0.17
vscode-react-native|vsm|0.6.11
jinja|who|0.0.8

(1 theme extensions excluded)

</details>

**Comment by chrmarti** [comment]
The border indicates that the option is 'on'.

**Comment by sardorocket** [comment]
@chrmarti that looks weird, I think would be nice if instead of a border the icon will have a different color

**Comment by bpasero** [comment]
-1, we consistently use this style to indicate something is checked also in the find widget for example.

**Comment by oneslash** [comment]
@bpasero for me it does not look obvious.

**Comment by misolori** [comment]
We should consider using an alternate style for showing when a state is "enabled" or "checked" as our focus border treatment already uses the border style so it can be confusing. Adding this to the backlog.

**Comment by oneslash** [comment]
Will close this in a favor of #36439
