### ISSUE TITLE
[Accessibility]A11y_VSCode_KeyboardShortcuts_Screenreader: JAWS is not reading "Keybindings.json" as link

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#52169]
**Environment Details:**
VSCode Version : 1.24.0
OS Version : Win10

**Additional Details:**
Screenreader,JAWS[18.0.5038],MAS1.3.1

**Repro Steps:**
1. Launch VS Code while JAWS is ON.
2. Navigate to Settings icon in Activity Bar->Press Enter->Select "Keyboard Shortcuts" from dropdown.
3.Navigate to "Keybindings.json" link.
4.Observed that JAWS is not reading it's type.

**Actual:**
JAWS is reading  simply "Keybindings.json" as "Keybindings.json"  but not reading it as link.

**Expected:**
JAWS should reads "Keybindings.json" with it's type such as  "Keybindings.json"link.

**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
[https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx](url)

**User Impact:**
User will get confused what is the role and type of control.

**MAS Reference:**
MAS1.3.1: [https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}](url)

**Attachment For Reference:**
[[Accessibility]A11y_VSCode_KeyboardShortcuts_Screenreader.pptx](https://github.com/Microsoft/vscode/files/2110664/Accessibility.A11y_VSCode_KeyboardShortcuts_Screenreader.pptx)
Does this issue occur when all extensions are disabled?: Yes

**Comment by auchenberg** [comment]
Closing this issue as it's only observed in JAWS, and this isn't strictly needed to meet MAS C compliance.
