### ISSUE TITLE
RPM builds are broken

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#52172]
Since they were also preventing the builds from publishing the ZIPs, I had to disable them:

https://github.com/Microsoft/vscode/commit/2afc0e92484a5a53af066a545c5fa7511515fa15
https://github.com/Microsoft/vscode/commit/36cab98dc03489882271770fd3bf813ed4548ce1

https://monacotools.visualstudio.com/Monaco/_build/index?buildId=39652&_a=summary

**Comment by Tyriar** [comment]
@joaomoreno I re-enabled them and did a run and it was fine? 
I undid your changes to get them building again 😕  https://monacotools.visualstudio.com/Monaco/_build/index?buildId=39668&_a=summary&tab=ms.vss-codecoverage-web.code-coverage-details

**Comment by joaomoreno** [comment]
KK, let's wait and see if it comes back. I've been seeing some slowness there. I will also change the order of things. We should maybe:

1. Build and publish ZIP
2. Build and publish DEB
3. Build and publish RPM

Right now we're doing the following:

1. Build ZIP, RPM, DEB
2. Publish ZIP
3. Publish DEB
4. Publish RPM
