### ISSUE TITLE
Upgrade to vscode 1.24.1 fails on Win 10 Enterprise Version 10.0.15063 Build 15063

### ISSUE THREAD

**Issue by CailleauThierry** [Microsoft/vscode#52170]
- VSCode Version: upgrade from 1.24.0 to 1.24.1
- OS Version: Win 10 Enterprise Version 10.0.15063 Build 15063

Steps to Reproduce:

1. Select "New Code update available" in bottom left corner of vscode 1.24.0
2. A "Visual Studio Code 1.24.1 is being installed" message appears
![visual studio code 1 24 1 is being installed](https://user-images.githubusercontent.com/19176129/41527473-924a27d0-72e7-11e8-967c-a59be442d8b7.png)
" appear
3. Then 2 messages, 1 "Restart Visual Studio Code" and the other "Visual Studio Code 1.24.1 is being installed in the background
![restart visual studio code_visual studio code 1 24 1 is being installed in the background](https://user-images.githubusercontent.com/19176129/41527497-a970c068-72e7-11e8-8bdc-7ec3ac6cb213.png)

4. This lead to this install log
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2110627/vscode-inno-updater.log)

Does this issue occur when all extensions are disabled?: Yes

[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2110689/vscode-inno-updater.log)

Note: Add/Remove already shows vscode at version 1.24.1
![appwiz cpl_already at vscode 1 24 1](https://user-images.githubusercontent.com/19176129/41528660-f8c366a4-72ea-11e8-828f-31b6cebea071.png)

While vscode > About shows correct version 1.24.0 :

Version 1.24.0
Commit 6a6e02cef0f2122ee1469765b704faf5d0e0d859
Date 2018-06-06T17:35:40.560Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by joaomoreno** [comment]
You seem to have #47841.

Please read this comment if you can provide more detail: https://github.com/Microsoft/vscode/issues/47841#issuecomment-393101777

Please read this one to disable background updates: https://github.com/Microsoft/vscode/issues/47841#issuecomment-395017687

**Comment by CailleauThierry** [comment]
Thanks it works! I am now upgraded to vscode 1.24.1

As in previews ticket I also have this installed ion my work laptop:
CrowdStrike Device Control
CrowdStrike Sensor Platform
CrowdStrike Windows Sensor
Managed Windows Defender

The steps to implement this workaround on vscode 1.24.0 are:

From vscode 1.24.0 > File > Preferences > Settings then:

add a comma after the last entry and before the "}", for me it was:
    "gitlens.historyExplorer.enabled": true
}

and add "update.enableWindowsBackgroundUpdates": false

now the end of the "USER SETTINGS" json file looks like:

    "gitlens.historyExplorer.enabled": true,
    "update.enableWindowsBackgroundUpdates": false
}
