### ISSUE TITLE
Warp lines only at whitespace

### ISSUE THREAD

**Issue by daiyam** [microsoft/vscode#52178]
Hello,

I would like to able to wrap lines only at whitespace. Why?
Due to:
- I will know there is only a whitespace between 2 wrapping lines (currently, there may be a whitespace of not)
- it won't break symbolic controls (currently, it breaks symbolic controls)
- it won't have a space at the start of a wrapping line

Currently:
![currently](https://user-images.githubusercontent.com/587742/41530960-22b09bec-72f2-11e8-90ea-d3a83a64849f.png)

Should be only like:
![between controls](https://user-images.githubusercontent.com/587742/41530959-2292fcae-72f2-11e8-9640-ae1d1d73eec8.png)
or
![inside controls](https://user-images.githubusercontent.com/587742/41531088-8a6a519c-72f2-11e8-9dba-98476adbb27c.png)

It could maybe configured by an `editor.wordWarpSeparators` option.

**Comment by alexdima** [comment]
Let's track in #39981
