### ISSUE TITLE
[Accessibility]A11y_VSCode_RestartRunningTask_ScreenReader:JAWS is not reading the placeholder text.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#52179]
**Environment Details:**
VSCode Version : 1.24.1
OS Version : Win10
**Additional Details:**
ScreenReader,,[JAWS18.0.5038],MAS1.3.1
**Repro Steps:**
Launch VS Code.
Navigate   to Tasks(Alt+T) menu option and select "Restart Running Task" from   dropdown.
Observe what jaws reads.
Actual:
JAWS is not reading the placeholder text.
Same issue observed in JAWS also.
Expected:
:JAWS is not reading the placeholder text.
Recommendations:
Refer below link which is repository of bug fixes code snippets:
https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx
User Impact:
The user will not be able to know the placeholder text.
MAS Reference:
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}
Does this issue occur when all extensions are disabled?: Yes
**Attachment for Reference**
[restartplaceholder.pptx](https://github.com/Microsoft/vscode/files/2110904/restartplaceholder.pptx)

**Comment by chrmarti** [comment]
@dbaeumer Should this be a message dialog?

**Comment by dbaeumer** [comment]
@chrmarti  No, this is actually using a normal quick pick which uses a place holder text. I will assign this to you assuming that this is something that needs to be addressed in the quick pick infrastructure.

**Comment by dbaeumer** [comment]
Please ping if you think otherwise.

**Comment by dbaeumer** [comment]
This is a little problematic then in terms of showing progress. I currently feed in a promise and the quick pick shows progress if it takes a while to compute the running tasks. If I would use a dialog the quick pick would show then close and a dialog would pop up. I found it the worse alternative. Will this be something that becomes easier with the multi step input?

**Comment by chrmarti** [comment]
No, not initially. We could later add a message area to the QuickPick to avoid having to use a list item to show messages like this one.

**Comment by dbaeumer** [comment]
Good idea.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/51824
Also we do not suport jaws
