### ISSUE TITLE
[Accessibility]A11y_VSCode_ShowRunningTasks_ScreenReader:JAWS is not reading the placeholder text

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#52182]
**Environment Details:**
VSCode Version : 1.24.1
OS Version : Win10
**Additional Details:**
ScreenReader,,[JAWS18.0.5038],MAS1.3.1
**Repro Steps:**
Launch VS Code.
Navigate   to Tasks(Alt+T) menu option and select "Show Running Tasks" from   dropdown.
Observe what jaws reads.
Actual:
JAWS is not reading the placeholder text
Expected:
JAWS should read the placeholder text
Recommendations:
Refer below link which is repository of bug fixes code snippets:
https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx
User Impact:
The user will not be able to know the placeholder text.
MAS Reference:
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}
Does this issue occur when all extensions are disabled?: Yes
Attachment for Reference
[show.pptx](https://github.com/Microsoft/vscode/files/2110955/show.pptx)

**Comment by auchenberg** [comment]
Closing this issue as it's only observed in JAWS, and this isn't strictly needed to meet MAS C compliance.
