### ISSUE TITLE
[Accessibility]A11y_VSCode_ShowOpenedEditors_Screenreader: JAWS is reading quick picker tree view twice. 

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#52187]
**Environment Details:**
VSCode Version : 1.24.1
OS Version : Win10
**Additional Details:**
 JAWS18.0.5038,MAS1.3.1
**Repro Steps:**
1)Launch VSCode.
2)Navigate   to welcome screen and beside opened editors pane at top(in middle   pane)->Select More(…)->Select "Show Opened Editors" from   dropdown.
3)Check with JAWS reading.
**Actual:**
JAWS is reading quick picker tree view twice. 
**Expected:**
JAWS should not read quick picker tree view twice. 
**Recommendations**:
Refer below link which is repository of bug fixes code snippets:
https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx
**User Impact:**
This will create confusion for the user .
**MAS Reference:**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={8492c4eb-c179-40ae-8777-cd044ed725a2}
Does this issue occur when all extensions are disabled?: Yes
**Attachment for Reference:**
[editor.pptx](https://github.com/Microsoft/vscode/files/2111019/editor.pptx)

**Comment by auchenberg** [comment]
Closing this issue as it's only observed in JAWS, and this isn't strictly needed to meet MAS C compliance.
