### ISSUE TITLE
Render kb(editor.action.marker.next) as F8

### ISSUE THREAD

**Issue by ma11hew28** [Microsoft/vscode#52186]
VSCode 1.25.0-insider
macOS 10.13.4 (17E199)

Open [Interactive Playground][1] in Visual Studio Code. Under the "Errors and Warnings" section, `kb(editor.action.marker.next)` appears as `unbound`. Instead, it should show up as `F8`.

  [1]: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/welcome/walkThrough/electron-browser/editor/vs_code_editor_walkthrough.md

**Comment by ma11hew28** [comment]
Also, I don't see "Go to Next Error or Warning" under the "Go" menu.

**Comment by chrmarti** [comment]
Could you open a separate issue for the Go menu entry?
