### ISSUE TITLE
[Accessibility]A11y_VSCode_KeyboardShortcuts_Screenreader: Voiceover is reading only the placeholder values

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#52180]
**Environment Details:**
VSCode Version : 1.24.0
OS Version : MAC OS HighSierra10.13.5

**Additional Details:**
Screenreader,voicover,MAS1.3.1

**Repro Steps:**
1. Launch VS Code while VOICEOVER is ON.
2. Navigate to Settings icon in Activity Bar->Press Enter->Select "Keyboard Shortcuts" from dropdown.
3.Using keyboard key navigate to "More" option expand it and select the "Show open editor"
4.Observed that VOICEOVER is not reading entered value.

**Actual:**
Voiceover is reading only "type '?' to get help on the actions you can  take from here" instead of entered values.

**Expected:**
Instead of reading only placeholder value voiceover should reads the entered data.

**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
[https://microsoft.sharepoint.com/teams/msenable/mas/Pages/browse-fixes.aspx](url)

**User Impact:**
User will not able to know what data is enter in editable text field.

**MAS Reference:**
MAS1.3.1: [https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}](url)

**Attachment For Refernce:**
[[Accessibility]A11y_VSCode_KeyboardShortcuts_Screenreader.pptx](https://github.com/Microsoft/vscode/files/2110939/Accessibility.A11y_VSCode_KeyboardShortcuts_Screenreader.pptx)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Duplicate
