### ISSUE TITLE
resolveDebugConfiguration is provided the wrong WorkspaceFolder

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#52192]
I have a workspace open with two (sibling) folders. Neither of them have a `launch.json`:

![screen shot 2018-06-18 at 12 54 22 pm](https://user-images.githubusercontent.com/1078012/41534562-e2f36836-72f6-11e8-806b-7a018bc75d28.png)

![screen shot 2018-06-18 at 12 53 57 pm](https://user-images.githubusercontent.com/1078012/41534566-e809ddfa-72f6-11e8-9a6a-6e7bf525c098.png)

If I open a file from the second workspace and press `F5`, my `resolve` method gets given the WorkspaceFolder that is not the one that contains the active file:

```ts
public async resolveDebugConfiguration(folder: WorkspaceFolder | undefined, debugConfig: DebugConfiguration, token?: CancellationToken): Promise<DebugConfiguration> {
    console.warn("Open workspaces:");
    workspace.workspaceFolders.forEach((wf) => console.log(wf.uri.toString()));
    console.warn("Active doc: " + window.activeTextEditor.document.uri.toString());
    console.warn("Provided workspace: " + folder.uri.toString());
```

```
Open workspaces:
    file:///Users/dantup/Dev/Google/flutter/examples/flutter_gallery
    file:///Users/dantup/Dev/Google/flutter/examples/stocks
Active doc: file:///Users/dantup/Dev/Google/flutter/examples/stocks/test/icon_color_test.dart
Provided workspace: file:///Users/dantup/Dev/Google/flutter/examples/flutter_gallery
```

The expectation is to run the "current file" so I think the `WorkspaceFolder` given should be the one containing that?

cc @weinand

**Comment by isidorn** [comment]
@DanTup good catch, thanks.
The fix will be available in insiders from next week. So if it works just let us know so we add a verified label (this is usualy nice to do for all isues). Thanks

**Comment by DanTup** [comment]
Fix looks good in Insiders, thanks!
