### ISSUE TITLE
Preview does not recognise .csv anymore

### ISSUE THREAD

**Issue by gennaro-tedesco** [Microsoft/vscode#52197]
As per title, all of a sudden the preview does not recognise .csv file as such, generating the exception `Active editor doesn't show a CSV or plain text document`. It does still work for plain text extentions. 

- VSCode Version: 1.24
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1. open any .csv file
2. try to preview it 

Does this issue occur when all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
I'm not aware of a built-in CSV previewer. Were you using an extension, like: https://marketplace.visualstudio.com/items?itemName=GrapeCity.gc-excelviewer

**Comment by gennaro-tedesco** [comment]
Sorry, I apologise, I forgot to include it. Yes, I am using the above mentioned extension: is the issue from their end, then?

**Comment by chrmarti** [comment]
Yes, looks like https://github.com/jjuback/gc-excelviewer/issues/68. Thanks.

**Comment by gennaro-tedesco** [comment]
Thank you for looking into it, cheers.
