### ISSUE TITLE
Debug session selector grows upwards when at top of screen making it difficult to use

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#52194]
When I go to select a debug session and there are several, this dropdown grows upwards but has limited space on the screen so sends up being quite difficult to use.

This is on macOS, stable channel.

![screen shot 2018-06-18 at 1 03 26 pm](https://user-images.githubusercontent.com/1078012/41534917-3d68229c-72f8-11e8-98d9-bebdb9bc7428.png)

**Comment by isidorn** [comment]
This is just native electron behavior. Pleae file it against electron. Thanks

**Comment by DanTup** [comment]
Ah, cool - I've opened it at https://github.com/electron/electron/issues/13279. Thanks!
