### ISSUE TITLE
subsequent items in array are displayed as undefined

### ISSUE THREAD

**Issue by dotbloup** [Microsoft/vscode#52191]
Issue Type: <b>Bug</b>

1.create a class with a array property
```js
class myClass{
  constructor(){
    this.bloup = [];
  }
}
```
2. create a method inside the class:
```js
jojo(){
  this.bloup=['ok','ok2','ok3'];
  console.log(this.bloup);
}
```
3. save, In the configuration, choose this file for debug
4. start debug
5. in terminal, when you click the down arrow you will see  and then the subsequent items under the first item will be "undefined". in our example,  it should display ok2 in position 1 and ok3 in position 2 
for sure, you can see them at the top on one line but if you have 100000 items you will not see them :)

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 3|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_15162997|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.3.2
vscode-docker|Pet|0.0.27
vscode-angular2-files|ale|1.5.1
jshint|dba|0.10.19
Angular2|joh|6.1.1
debugger-for-chrome|msj|4.6.0
vetur|oct|0.12.5
addDocComments|ste|0.0.8
vscode-angular-support|vis|0.1.4

</details>

**Comment by weinand** [comment]
Your steps are incomplete:
there is no code that uses your class.
