### ISSUE TITLE
[Accessibility]A11y_VSCode_ScreenReaderOptimized_ScreenReader:VoiceOver is not reading the content and control of the screen.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#52207]
Environment Details:
VSCode Version : 1.24.1
OS Version : Win10
Additional Details:
ScreenReader,VoiceOver,MACOS High Sierra 10.13.5 Beta (17F70a),MAS1.3.1
**Repro Steps:**
1. Launch VS Code.
2. Navigate to File->select New File->Navigate to Status Bar->Click on "Screen Reader Optimized" button.
3. Observe what Voiceover  reads.
**Actual:**
 VoiceOver is not reading the content and control of the screen.
**Expected:**
 VoiceOver should read the content and control of the screen.

Recommendations:
Refer below link which is repository of bug fixes code snippets:
[https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx](url)
**User Impact:**
The user will not be able to know the content.
**MAS Reference:**
[https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}](url)
Does this issue occur when all extensions are disabled?: Yes
**Attachment for Reference**

[[Accessibility]A11y_VSCode_ScreenReaderOptimized_ScreenReader.pptx](https://github.com/Microsoft/vscode/files/2111695/Accessibility.A11y_VSCode_ScreenReaderOptimized_ScreenReader.pptx)

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/52036
