### ISSUE TITLE
Support terminakl.integrated.env.* as a workspace setting.

### ISSUE THREAD

**Issue by pascencio** [microsoft/vscode#52216]
- VSCode Version: 1.24.1
- OS Version: Manjaro Linux 17.1.7

Steps to Reproduce:

1. Create a Workspace
2. Set in workspace setting **terminal.integrated.env.linux** the GOPATH env.
3. Print in a new terminal the GOPATH value.

![image](https://user-images.githubusercontent.com/9783678/41547621-b582ce9e-72ee-11e8-8ce2-623bf4e3ef6e.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
I think this is happening as we only support shell/shellArgs in workspace settings after an additional opt-in dialog. env is not supported atm.

**Comment by pascencio** [comment]
@Tyriar there are some workaround?
I need it! :nerd_face: 
Thanks in advance.

**Comment by Tyriar** [comment]
@pascencio no workaround for use in workspace settings, you would need to stick it in your *user* settings.json.

**Comment by pascencio** [comment]
@Tyriar have you plans of include this feature in a new release?

**Comment by Tyriar** [comment]
No it's not planned currently.

**Comment by Tyriar** [comment]
This was implemented a while ago, note that you'll get a warning for security reasons:

![image](https://user-images.githubusercontent.com/2193314/66419696-5ec98f00-e9b9-11e9-8ee8-996865b3c2d2.png)
