### ISSUE TITLE
resourceIsFile context seems to always be true for explorer context menus, even on folders

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#52217]
I was trying to make a context menu item only appear for folders and came across `resourceIsFile`. However, it seems to always be true, even when I right-click on folders:

```js
{
	"command": "flutter.openInAndroidStudio",
	"when": "resourceIsFile"
},
{
	"command": "flutter.openInXcode",
	"when": "!resourceIsFile"
}
```

The Android Studio one appears on everything, and the Xcode one appears on nothing.

**Comment by isidorn** [comment]
Use this instead (or the negation of that 
`explorerResourceIsFolder`

file means it uses the `file` uri, not that it is not a folder

**Comment by DanTup** [comment]
Ah, doh! Works great, thanks! :)
