### ISSUE TITLE
Extension marketplace should not pull images directly from master branch on GitHub

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode#52219]
Steps to Reproduce:

1. Publish an extension with a link to an image in the README
2. Remove that image from master branch of the extension's Github repo

Expected: The marketplace still shows that image
Actual: The marketplace fails to show that image

We didn't realize the marketplace was pulling images directly from our master branch on GitHub, leading to this bug in the Azure App Service extension: https://github.com/Microsoft/vscode-azureappservice/issues/459

This behavior effectively prevents us from deleting/editing images until the day we release an update to our extension. Can the marketplace host the images itself rather than pointing to our master branch?

**Comment by chrisdias** [comment]
assigning to @seanmcbreen

**Comment by egamma** [comment]
Closing this is a feature request against the market place, nothing VS Code can do to address it.
