### ISSUE TITLE
When I click on a link in the terminal, browser opens with a URL which seems to be the link, but run through decodeURIComponent

### ISSUE THREAD

**Issue by capaj** [Microsoft/vscode#52211]
- VSCode Version:  Version 1.24.1
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. paste `echo Browse to http://localhost:8448/#/repository?path=%2Fhome%2Fcapaj%2Fgit_projects%2Fartillery` in the terminal, hit enter
2. now click on the link while holding down ctrl

Your browser will open URL `http://localhost:8448/#/repository%3Fpath=/home/capaj/git_projects/artillery`
instead of the original one

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
Links that are being opened don't get encoded, browsers usually take care of this because users usually don't encode URIs either. The `?`-character in the fragment shouldn't be encoded and that has been fixed via #49628.

@capaj What is the problem here?
