### ISSUE TITLE
Typing punctuation goes to beginning of line

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#52222]
Issue Type: <b>Bug</b>

* Paste this into a file:
```ts
class C


```
* Click on line 2. (There should be at least one blank line after `class C`.)
* Hit the left arrow on your keyboard to now be at the end of `class C` on line 1.
* Type a punctuation character such as ` ` (space) or `{`. (NOTE: The bug will not reproduce if there is *already* a space after `C`.)
* The cursor will be taken back to the beginning of the line.
* Typing a non-punctuation character does not reproduce the bug, so you can type `Cow` without being taken to the start. The bug will not reproduce if you've typed non-puncutation after hitting the left arrow to move up from line 2.
* Does not reproduce in vscode non-insiders.

VS Code version: Code - Insiders 1.25.0-insider (777c8e57e0eb1cbffb87a57ffd4f9c3d274f9429, 2018-06-18T05:19:20.432Z)
OS version: Linux x64 4.13.0-43-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2109)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 2|
|Memory (System)|7.63GB (1.29GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
typescript-javascript-grammar|ms-|0.0.42

</details>

**Comment by chrmarti** [comment]
Could be #52080. Does this reproduce in the latest insiders?

**Comment by andy-ms** [comment]
Thanks, looks like a duplicate of #52080. I was experiencing the bug in JSON too but couldn't reproduce it as reliably as this.
