### ISSUE TITLE
Preserve --enable-proposed-api when opening a new folder/workspace

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#52229]
- VSCode Version: 1.25-insiders
- OS Version: Windows 10 x64

Currently if you pass `--enable-proposed-api <extension-name>`  to vscode on the command line it only seems to work for that workspace. If you open a new folder or workspace from within that window, `--enable-proposed-api` seems to be lost.

This makes testing/using extensions with proposed apis very difficult.

**Comment by eamodio** [comment]
This is not a duplicate of that

**Comment by jrieken** [comment]
@bpasero I was assuming that flags are inherited to the next window... Where and how do I need to enable this?

**Comment by bpasero** [comment]
I need to check, do not know on top of my head.

**Comment by eamodio** [comment]
@bpasero I can still reproduce this in the latest insiders. I will try later to run from sources and look for that log.
