### ISSUE TITLE
Option for sorting files by type in Explorer

### ISSUE THREAD

**Issue by gulshan** [Microsoft/vscode#5222]
It would be nice to have a "Sort/Order by type" option which will sort the files by types (and then by name) in the file explorer.

**Comment by whitecolor** [comment]
Yeah sorting by type/extension would very useful.

**Comment by drwasho** [comment]
Third

**Comment by brianweber13** [comment]
Yes. Please.

**Comment by bpasero** [comment]
Landed via https://github.com/Microsoft/vscode/pull/29509

Setting to use: `"explorer.sortOrder": "type"`

**Comment by whitecolor** [comment]
Very cool, but not in latest insiders yet. )

**Comment by brianweber13** [comment]
Woohoo! Thanks!
