### ISSUE TITLE
Disabling extension shows incorrect extension as dependency

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode#52220]
Issue Type: <b>Bug</b>

Copied from https://github.com/Microsoft/vscode-azureappservice/issues/463 by @jleach

Repro steps:
1. Install both the Azure Functions and Azure App Service extensions
1. Disable the App Service extension
1. Select 'Yes' when asked "Would you like to disable the dependencies of the extensions also?"

* Expected: An error with the message "Cannot disable extension 'Azure Account'. Extension 'Azure Functions' depends on this."
* Actual: Instead of 'Azure Account' listed in the error message (which both extensions depend on), 'Azure App Service' is listed as the dependency (which is not true). This can result in weird circular error messages for users:
![screen shot 2018-06-18 at 10 30 18 am](https://user-images.githubusercontent.com/11282622/41552089-9d56005e-72e2-11e8-8949-a645583e3064.png)

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (6.23GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.18.0
tslint|eg2|1.0.32
vscode-azureappservice|ms-|0.8.1
vscode-azurefunctions|ms-|0.9.1
azure-account|ms-|0.4.0
csharp|ms-|1.15.2
java|red|0.26.0
vscode-java-debug|vsc|0.9.0

</details>

**Comment by sandy081** [comment]
Looks like both extensions depends on Azure Account extension, so cannot disable both App Service and Azure Account extension because, Azure Function extension depends on Azure Account extension. 

I think the message is misleading here
