### ISSUE TITLE
Git insertion colour disappears when scrolling

### ISSUE THREAD

**Issue by zyskfhmuenster** [Microsoft/vscode#52227]
Issue Type: <b>Bug</b>

The coloured line next to the line numbers symbolising a Git insertion disappears when the line number of the insertion's last row disappears while scrolling down. The line break mode (Alt+Z) is enabled in my current configuration.

1. Create a Git observed text file.
2. Write two long paragraphs (each in one line).
3. Scroll down.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz (8 x 2392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (4.14GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Users\de23463\Documents\Unterlagen Fachhochschule\Praxisphase 2\Unit-Testing Prozessmodelle\LateX Projekt\bachelorthesis|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-de|MS-|1.24.3
team|ms-|1.136.0
java|red|0.26.0
vscode-java-debug|vsc|0.9.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.6.1
vscode-maven|vsc|0.9.0

</details>

**Comment by alexandrudima** [comment]
Here is a gif showing the problem:

![kapture 2018-09-12 at 9 55 00](https://user-images.githubusercontent.com/5047891/45410458-03bc5000-b672-11e8-9abb-08cccc0303c4.gif)
