### ISSUE TITLE
[sql] add support for mysql

### ISSUE THREAD

**Issue by llewelynrex** [Microsoft/vscode#5223]
- VSCode Version: 0.10.11
- OS Version: Windows 7 Professional

Steps to Reproduce:

I have a \ character defined as a string in an update query. The Syntax highlighting is incorrectly escaping the following ' and displaying the rest of the script as a string. I am using UTF-8 Encoding with SQL as the language. Below two screenshots:

![error](https://cloud.githubusercontent.com/assets/9720471/14493462/ded13ba0-0185-11e6-982e-6160b8edba5c.jpg)

This is the same piece of script in SSMS.
![ssms](https://cloud.githubusercontent.com/assets/9720471/14493535/33fcb442-0186-11e6-8598-e975e1f3074f.jpg)

**Comment by aharpervc** [comment]
Possibly related: https://github.com/atom/language-sql/issues/13 (probably using the same grammars?). Whoever fixes it first should send a patch to the other, if so.

**Comment by aeschli** [comment]
We're using https://github.com/textmate/sql.tmbundle. 
From the discussion in atom/language-sql#13 it looks like this is about different dialects of SQL. You seem to use the MySQL dialect, where '\' is not an escape character.
Just removing it wouldn't work, as it would break other users.
I guess we need to add separate language support for MySQL.

**Comment by aharpervc** [comment]
This isn't a MySQL thing, even though the OP described it that way, or otherwise stated, it is _also_ a SQL Server syntax issue. In any case, separate sql dialects probably need separate rules. There is also the question of what the default should be.

**Comment by aeschli** [comment]
This got fixed in the meantime, likely by the switch of the SQL grammar from https://github.com/Microsoft/vscode-mssql
