### ISSUE TITLE
Syntax highlighting is broken for JS parameters

### ISSUE THREAD

**Issue by tylerr514** [Microsoft/vscode#52231]
Issue Type: <b>Bug</b>

function(parm1, parm2) {
}
the colors of parm1, and parm2 are broken

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17692

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4785T CPU @ 2.20GHz (8 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (9.12GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
jshintrc-generator|ben|1.0.0
node-module-intellisense|lei|1.5.0
vscode-exec-node|mir|0.5.0
vscode-scss|mrm|0.6.2
python|ms-|2018.5.0
polacode|pnp|0.2.2
java|red|0.26.0
live-sass|rit|1.3.0
LiveServer|rit|5.0.0
vscode-java-debug|vsc|0.9.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.6.1
vscode-maven|vsc|0.9.0
JavaScriptSnippets|xab|1.6.0

</details>

**Comment by mjbvz** [comment]
Please share a screenshot of the issue

**Comment by tylerr514** [comment]
Oh I'm sorry for tossing this false tread up prematurely.
I failed to read the update notes, and missed that unused items are now gray.
