### ISSUE TITLE
Option to enable localStorage in WebView panels

### ISSUE THREAD

**Issue by jdgarcia** [Microsoft/vscode#52246]
I am currently using the `vscode.previewHtml` command to display a web app in VS Code (via iframe) which uses `localStorage` to store persisting state, and I am currently trying to convert it to use the new Webview API, in order to take advantage of the new `retainContextWhenHidden` option. I noticed however that while accessing `localStorage` works fine when using `vscode.previewHtml`, it is disabled in panels that use the Webview API.

I saw that a persistence API is currently being worked on (https://github.com/Microsoft/vscode/issues/49022), but in order to even use that, I would have to wrap all my `localStorage` gets/sets in async functions that check to see if `localStorage` is accessible, and if it isn't, use message passing between the iframe and the webview in order to use `getState`/`setState` inside the webview.

That would be doable but it's definitely not ideal.

[This comment](https://github.com/Microsoft/vscode/issues/48464#issuecomment-384105131) seems to imply that it is disabled intentionally but is something that can potentially be enabled.

**Comment by mjbvz** [comment]
It's disabled because we serve webview using data uris: https://stackoverflow.com/questions/37379254/how-to-save-data-to-the-browser-with-data-url/37541068

**Comment by formulahendry** [comment]
Do we have plan to enable this? I meet with the same issue on https://marketplace.visualstudio.com/items?itemName=formulahendry.vscode-node-red extension. Currently, we are using `vscode.previewHtml` but want to use `retainContextWhenHidden` in new WebView API. However, localStorage is not enabled..

**Comment by mjbvz** [comment]
@formulahendry You should not need local storage. See the new persistence APIs instead

**Comment by formulahendry** [comment]
Hi @mjbvz , in my extension, I embed https://www.npmjs.com/package/node-red (which is just a localhost website) into the webview. I have no control of node-red npm package to not to use local storage.. Any suggestion would be appreciated. Thanks!

**Comment by jrieken** [comment]
It a Web*View*, not a Web*Browser* ;-)  I don't think we can isolate local storage of web views with the local storage VS Code is using That would be cross pollution that's generally undesirable for us.

**Comment by formulahendry** [comment]
If we have no plan to support that in WebView, do we have plan to make `vscode.previewHtml` not re-render when switching? I really need the page to be retained. 😢

**Comment by mjbvz** [comment]
No. You should use a webview. The old html preview is deprecated and will not receive new features

**Comment by formulahendry** [comment]
OK, so seems like I need to wait for localStorage to be enabled in WebView.
