### ISSUE TITLE
JSDoc @property, first {object}, rest of properties become sub properties

### ISSUE THREAD

**Issue by austin-rausch** [Microsoft/vscode#52242]
- VSCode Version: 1.24.1 AND 1.25.0 (nightly build)
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Create a .js file
2. Post the following code into the file and save
```
/**
  * @typedef {object} typeTest
  * 
  * @property {string} second - second property
  * @property {object} first - first property
  * @property {string} first.one - first's one property
  * @property {object} third - third property
  */

/**
 * @type typeTest
 */
const test;

```
3.  `third` property becomes a property of `first` instead of a property of `typeTest`
Screen shot:
![image](https://user-images.githubusercontent.com/14016828/41568415-8965e0b8-7333-11e8-863e-cba85661b9d1.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by ssut** [comment]
Here I am suffering the same issue.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#25072
