### ISSUE TITLE
VSCode kill terminal shortcut stopped working

### ISSUE THREAD

**Issue by zenVentzi** [Microsoft/vscode#52241]
[Screenshot](https://i.stack.imgur.com/WWWeI.png).

It used to work, but it stopped after some of the updates. 1.24.0 is my current version, on Windows 10. Prolblem persists even with no extensions enabled. Ideas? Thanks!

P.S. The Cmd(Window key) Shift J command still works.

**Comment by zenVentzi** [comment]
Okay, changed only the last letter and it started working again. Strange, I see no other keybinding with the "w" letter. It's not a big deal just couldn't make sense what is causing it. Thank you, Tyriar!

**Comment by Tyriar** [comment]
I would guess that's being intercepted by Windows as the Windows key is often used for OS-level things.
