### ISSUE TITLE
Failed to update

### ISSUE THREAD

**Issue by HeapOfPackrats** [Microsoft/vscode#52248]
Contents of vscode-inno-updater.log below:

Jun 18 18:55:06.393 INFO Starting: C:\Program Files\Microsoft VS Code\Code.exe, false
Jun 18 18:55:06.393 INFO Checking for running Code.exe processes... (attempt 1)
Jun 18 18:55:06.396 INFO Code.exe is running, wait a bit
Jun 18 18:55:06.896 INFO Checking for running Code.exe processes... (attempt 2)
Jun 18 18:55:06.907 INFO Code.exe is running, wait a bit
Jun 18 18:55:07.407 INFO Checking for running Code.exe processes... (attempt 3)
Jun 18 18:55:07.412 INFO Code.exe is not running
Jun 18 18:55:07.412 INFO Checking for possible conflicting running processes... (attempt 1)
Jun 18 18:55:07.417 INFO Inno Updater v0.4.3
Jun 18 18:55:07.418 INFO Starting update, silent = false
Jun 18 18:55:07.471 INFO do_update: "C:\\Program Files\\Microsoft VS Code\\Code.exe", _
Jun 18 18:55:07.471 INFO move_update: "C:\\Program Files\\Microsoft VS Code\\unins000.dat", _
Jun 18 18:55:07.471 INFO Delete: "api-ms-win-core-console-l1-1-0.dll" (attempt 1)
Jun 18 18:55:07.471 INFO Delete: "api-ms-win-core-datetime-l1-1-0.dll" (attempt 1)
Jun 18 18:55:07.472 INFO Delete: "api-ms-win-core-debug-l1-1-0.dll" (attempt 1)
Jun 18 18:55:07.472 INFO Delete: "api-ms-win-core-errorhandling-l1-1-0.dll" (attempt 1)
Jun 18 18:55:07.472 INFO Delete: "api-ms-win-core-file-l1-1-0.dll" (attempt 1)
Jun 18 18:55:07.472 INFO Delete: "api-ms-win-core-file-l1-2-0.dll" (attempt 1)
Jun 18 18:55:07.473 INFO Delete: "api-ms-win-core-file-l2-1-0.dll" (attempt 1)
Jun 18 18:55:07.473 INFO Delete: "api-ms-win-core-handle-l1-1-0.dll" (attempt 1)
Jun 18 18:55:07.473 INFO Delete: "api-ms-win-core-heap-l1-1-0.dll" (attempt 1)
Jun 18 18:55:07.473 INFO Delete: "api-ms-win-core-interlocked-l1-1-0.dll" (attempt 1)
Jun 18 18:55:07.474 INFO Delete: "api-ms-win-core-libraryloader-l1-1-0.dll" (attempt 1)
Jun 18 18:55:07.474 INFO Delete: "api-ms-win-core-localization-l1-2-0.dll" (attempt 1)
Jun 18 18:55:07.474 INFO Delete: "api-ms-win-core-memory-l1-1-0.dll" (attempt 1)
Jun 18 18:55:07.474 INFO Delete: "api-ms-win-core-namedpipe-l1-1-0.dll" (attempt 1)
Jun 18 18:55:07.474 INFO Delete: "api-ms-win-core-processenvironment-l1-1-0.dll" (attempt 1)
Jun 18 18:55:07.475 INFO Delete: "api-ms-win-core-processthreads-l1-1-0.dll" (attempt 1)
Jun 18 18:55:07.475 INFO Delete: "api-ms-win-core-processthreads-l1-1-1.dll" (attempt 1)
Jun 18 18:55:07.475 INFO Delete: "api-ms-win-core-profile-l1-1-0.dll" (attempt 1)
Jun 18 18:55:07.475 INFO Delete: "api-ms-win-core-rtlsupport-l1-1-0.dll" (attempt 1)
Jun 18 18:55:07.476 INFO Delete: "api-ms-win-core-string-l1-1-0.dll" (attempt 1)
Jun 18 18:55:07.476 INFO Delete: "api-ms-win-core-synch-l1-1-0.dll" (attempt 1)
Jun 18 18:55:07.476 INFO Delete: "api-ms-win-core-synch-l1-2-0.dll" (attempt 1)
Jun 18 18:55:07.476 INFO Delete: "api-ms-win-core-sysinfo-l1-1-0.dll" (attempt 1)
Jun 18 18:55:07.476 INFO Delete: "api-ms-win-core-timezone-l1-1-0.dll" (attempt 1)
Jun 18 18:55:07.477 INFO Delete: "api-ms-win-core-util-l1-1-0.dll" (attempt 1)
Jun 18 18:55:07.477 INFO Delete: "api-ms-win-crt-conio-l1-1-0.dll" (attempt 1)
Jun 18 18:55:07.477 INFO Delete: "api-ms-win-crt-convert-l1-1-0.dll" (attempt 1)
Jun 18 18:55:07.477 INFO Delete: "api-ms-win-crt-environment-l1-1-0.dll" (attempt 1)
Jun 18 18:55:07.478 INFO Delete: "api-ms-win-crt-filesystem-l1-1-0.dll" (attempt 1)
Jun 18 18:55:07.478 INFO Delete: "api-ms-win-crt-heap-l1-1-0.dll" (attempt 1)
Jun 18 18:55:07.479 INFO Delete: "api-ms-win-crt-locale-l1-1-0.dll" (attempt 1)
Jun 18 18:55:07.479 INFO Delete: "api-ms-win-crt-math-l1-1-0.dll" (attempt 1)
Jun 18 18:55:07.479 INFO Delete: "api-ms-win-crt-multibyte-l1-1-0.dll" (attempt 1)
Jun 18 18:55:07.479 INFO Delete: "api-ms-win-crt-private-l1-1-0.dll" (attempt 1)
Jun 18 18:55:07.480 INFO Delete: "api-ms-win-crt-process-l1-1-0.dll" (attempt 1)
Jun 18 18:55:07.480 INFO Delete: "api-ms-win-crt-runtime-l1-1-0.dll" (attempt 1)
Jun 18 18:55:07.480 INFO Delete: "api-ms-win-crt-stdio-l1-1-0.dll" (attempt 1)
Jun 18 18:55:07.480 INFO Delete: "api-ms-win-crt-string-l1-1-0.dll" (attempt 1)
Jun 18 18:55:07.481 INFO Delete: "api-ms-win-crt-time-l1-1-0.dll" (attempt 1)
Jun 18 18:55:07.481 INFO Delete: "api-ms-win-crt-utility-l1-1-0.dll" (attempt 1)
Jun 18 18:55:07.481 INFO Delete: "bin" (attempt 1)
Jun 18 18:55:07.528 INFO Delete: "blink_image_resources_200_percent.pak" (attempt 1)
Jun 18 18:55:07.528 INFO Delete: "Code.exe" (attempt 1)
Jun 18 18:55:07.531 INFO Delete: "Code.VisualElementsManifest.xml" (attempt 1)
Jun 18 18:55:07.531 INFO Delete: "CodeSignSummary.md" (attempt 1)
Jun 18 18:55:07.532 INFO Delete: "content_resources_200_percent.pak" (attempt 1)
Jun 18 18:55:07.532 INFO Delete: "content_shell.pak" (attempt 1)
Jun 18 18:55:07.532 INFO Delete: "d3dcompiler_47.dll" (attempt 1)
Jun 18 18:55:07.533 INFO Delete: "ffmpeg.dll" (attempt 1)
Jun 18 18:55:07.533 INFO Delete: "icudtl.dat" (attempt 1)
Jun 18 18:55:07.533 INFO Delete: "libEGL.dll" (attempt 1)
Jun 18 18:55:07.534 INFO Delete: "libGLESv2.dll" (attempt 1)
Jun 18 18:55:07.534 INFO Delete: "locales" (attempt 1)
Jun 18 18:55:07.543 INFO Delete: "msvcp140.dll" (attempt 1)
Jun 18 18:55:07.544 INFO Delete: "natives_blob.bin" (attempt 1)
Jun 18 18:55:07.544 INFO Delete: "node.dll" (attempt 1)
Jun 18 18:55:07.546 INFO Delete: "pdf_viewer_resources.pak" (attempt 1)
Jun 18 18:55:07.547 INFO Delete: "resources" (attempt 1)
Jun 18 18:55:08.867 INFO Delete: "snapshot_blob.bin" (attempt 1)
Jun 18 18:55:08.867 INFO Delete: "ucrtbase.dll" (attempt 1)
Jun 18 18:55:08.867 INFO Delete: "ui_resources_200_percent.pak" (attempt 1)
Jun 18 18:55:08.868 INFO Delete: "vcruntime140.dll" (attempt 1)
Jun 18 18:55:08.868 INFO Delete: "views_resources_200_percent.pak" (attempt 1)
Jun 18 18:55:08.868 INFO Rename: "api-ms-win-core-console-l1-1-0.dll" (attempt 1)
Jun 18 18:55:08.869 INFO Rename: "api-ms-win-core-datetime-l1-1-0.dll" (attempt 1)
Jun 18 18:55:08.869 INFO Rename: "api-ms-win-core-debug-l1-1-0.dll" (attempt 1)
Jun 18 18:55:08.869 INFO Rename: "api-ms-win-core-errorhandling-l1-1-0.dll" (attempt 1)
Jun 18 18:55:08.870 INFO Rename: "api-ms-win-core-file-l1-1-0.dll" (attempt 1)
Jun 18 18:55:08.870 INFO Rename: "api-ms-win-core-file-l1-2-0.dll" (attempt 1)
Jun 18 18:55:08.871 INFO Rename: "api-ms-win-core-file-l2-1-0.dll" (attempt 1)
Jun 18 18:55:08.871 INFO Rename: "api-ms-win-core-handle-l1-1-0.dll" (attempt 1)
Jun 18 18:55:08.871 INFO Rename: "api-ms-win-core-heap-l1-1-0.dll" (attempt 1)
Jun 18 18:55:08.872 INFO Rename: "api-ms-win-core-interlocked-l1-1-0.dll" (attempt 1)
Jun 18 18:55:08.872 INFO Rename: "api-ms-win-core-libraryloader-l1-1-0.dll" (attempt 1)
Jun 18 18:55:08.873 INFO Rename: "api-ms-win-core-localization-l1-2-0.dll" (attempt 1)
Jun 18 18:55:08.873 INFO Rename: "api-ms-win-core-memory-l1-1-0.dll" (attempt 1)
Jun 18 18:55:08.873 INFO Rename: "api-ms-win-core-namedpipe-l1-1-0.dll" (attempt 1)
Jun 18 18:55:08.874 INFO Rename: "api-ms-win-core-processenvironment-l1-1-0.dll" (attempt 1)
Jun 18 18:55:08.874 INFO Rename: "api-ms-win-core-processthreads-l1-1-0.dll" (attempt 1)
Jun 18 18:55:08.875 INFO Rename: "api-ms-win-core-processthreads-l1-1-1.dll" (attempt 1)
Jun 18 18:55:08.875 INFO Rename: "api-ms-win-core-profile-l1-1-0.dll" (attempt 1)
Jun 18 18:55:08.875 INFO Rename: "api-ms-win-core-rtlsupport-l1-1-0.dll" (attempt 1)
Jun 18 18:55:08.876 INFO Rename: "api-ms-win-core-string-l1-1-0.dll" (attempt 1)
Jun 18 18:55:08.876 INFO Rename: "api-ms-win-core-synch-l1-1-0.dll" (attempt 1)
Jun 18 18:55:08.877 INFO Rename: "api-ms-win-core-synch-l1-2-0.dll" (attempt 1)
Jun 18 18:55:08.877 INFO Rename: "api-ms-win-core-sysinfo-l1-1-0.dll" (attempt 1)
Jun 18 18:55:08.877 INFO Rename: "api-ms-win-core-timezone-l1-1-0.dll" (attempt 1)
Jun 18 18:55:08.878 INFO Rename: "api-ms-win-core-util-l1-1-0.dll" (attempt 1)
Jun 18 18:55:08.878 INFO Rename: "api-ms-win-crt-conio-l1-1-0.dll" (attempt 1)
Jun 18 18:55:08.879 INFO Rename: "api-ms-win-crt-convert-l1-1-0.dll" (attempt 1)
Jun 18 18:55:08.879 INFO Rename: "api-ms-win-crt-environment-l1-1-0.dll" (attempt 1)
Jun 18 18:55:08.879 INFO Rename: "api-ms-win-crt-filesystem-l1-1-0.dll" (attempt 1)
Jun 18 18:55:08.880 INFO Rename: "api-ms-win-crt-heap-l1-1-0.dll" (attempt 1)
Jun 18 18:55:08.880 INFO Rename: "api-ms-win-crt-locale-l1-1-0.dll" (attempt 1)
Jun 18 18:55:08.881 INFO Rename: "api-ms-win-crt-math-l1-1-0.dll" (attempt 1)
Jun 18 18:55:08.881 INFO Rename: "api-ms-win-crt-multibyte-l1-1-0.dll" (attempt 1)
Jun 18 18:55:08.882 INFO Rename: "api-ms-win-crt-private-l1-1-0.dll" (attempt 1)
Jun 18 18:55:08.882 INFO Rename: "api-ms-win-crt-process-l1-1-0.dll" (attempt 1)
Jun 18 18:55:08.882 INFO Rename: "api-ms-win-crt-runtime-l1-1-0.dll" (attempt 1)
Jun 18 18:55:08.883 INFO Rename: "api-ms-win-crt-stdio-l1-1-0.dll" (attempt 1)
Jun 18 18:55:08.883 INFO Rename: "api-ms-win-crt-string-l1-1-0.dll" (attempt 1)
Jun 18 18:55:08.884 INFO Rename: "api-ms-win-crt-time-l1-1-0.dll" (attempt 1)
Jun 18 18:55:08.884 INFO Rename: "api-ms-win-crt-utility-l1-1-0.dll" (attempt 1)
Jun 18 18:55:08.885 INFO Rename: "bin" (attempt 1)
Jun 18 18:55:08.885 INFO Rename: "blink_image_resources_200_percent.pak" (attempt 1)
Jun 18 18:55:08.885 INFO Rename: "Code.exe" (attempt 1)
Jun 18 18:55:08.937 INFO Rename: "Code.exe" (attempt 2)
Jun 18 18:55:09.137 INFO Rename: "Code.exe" (attempt 3)
Jun 18 18:55:09.589 INFO Rename: "Code.exe" (attempt 4)
Jun 18 18:55:10.391 INFO Rename: "Code.exe" (attempt 5)
Jun 18 18:55:11.643 INFO Rename: "Code.exe" (attempt 6)
Jun 18 18:55:13.444 INFO Rename: "Code.exe" (attempt 7)
Jun 18 18:55:15.895 INFO Rename: "Code.exe" (attempt 8)
Jun 18 18:55:19.098 INFO Rename: "Code.exe" (attempt 9)
Jun 18 18:55:23.150 INFO Rename: "Code.exe" (attempt 10)
Jun 18 18:55:28.152 INFO Rename: "Code.exe" (attempt 11)
Jun 18 18:55:28.154 ERRO Access is denied. (os error 5)

**Comment by joaomoreno** [comment]
You seem to have #47841.

Please read this comment if you can provide more detail: https://github.com/Microsoft/vscode/issues/47841#issuecomment-393101777

Please read this one to disable background updates: https://github.com/Microsoft/vscode/issues/47841#issuecomment-395017687
