### ISSUE TITLE
running truffle framework or javascript apps on integrated terminal, vs code crashes

### ISSUE THREAD

**Issue by mato777** [Microsoft/vscode#52249]
I am solidity developer, in last version when I use truffle to run my test, my memory is consumed all and vs code crashes.
I tested also with a basic react app and I get the same error.

I even uninstalled everything tried again and I get the same error.

I am running windows 10 on a new laptop.

I don't know how to get log about this.

**Comment by mato777** [comment]
"terminal.integrated.rendererType": "dom"
found the cause, if I set this option in dom problems get away.  I have an nvidia 960 m in a lenovo y700.  Don't know why it is not rendering as it should.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/36913
