### ISSUE TITLE
Folders collpasing

### ISSUE THREAD

**Issue by freynolds** [Microsoft/vscode#52247]
Issue Type: <b>Bug</b>

Since last update I get bugs that when I try to open/close a folder, it will do that to another folder or completly mixup what folder goes where

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
fish|Ted|0.0.4
graphql|mqu|0.1.2
debugger-for-chrome|msj|4.6.0
change-case|wma|1.0.0

</details>

**Comment by chrmarti** [comment]
Could you provide step to reproduce, one step at a time, and before/after screenshots?

**Comment by isidorn** [comment]
Also try reproducing with latest vscode insiders https://code.visualstudio.com/insiders/

**Comment by freynolds** [comment]
Hi sorry for the delay, I wasn't able to reproduce this in a way I could share, it happened twice since posting the bug, but idk what steps I made to get to there, it happened after heavy load of working, some hours in using the software.
Next time it happens I will attach a video so you can at least have an idea of what i was talking about.
