### ISSUE TITLE
[Accessibility]A11y_VSCode_CommandPalette_Screenreader: Voiceover is not reading list of expanded values of "CommandPalette"

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#52257]
**Environment Details:**
VSCode Version : 1.24.0
OS Version : MAC OS HighSierra10.13.5

**Additional Details:**
Screenreader,Voiceover,MAS1.3.1

**Repro Steps:**
1.Launch VS Code while Voiceover is ON.
2.Navigate to Settings icon in Activity Bar->Press Enter->Select "Command Palette" from dropdown.
3.Enter ">" sign to reflect all list of expanded "Command Palette" option.
3.Observed that,Voiceover is not reading expanded list value of "Command Palette".

**Actual:**
While reading through the screenreader, voiceover is reading only the placeholder value such as "Type "?" to get help on the actions you can take from here" instead of reading the expanded value list of "Command Palette."
 
**Expected:**
Instead of reading only placeholder value such as " Type "?" to get help on the actions you can take from here" on each and every value of expanded "Command Palette".
Voiceover should reads the selected list name only.

**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
[https://microsoft.sharepoint.com/teams/msenable/mas/Pages/browse-fixes.aspx](url)

**User Impact:**
The user will not know which value is selected from expanded "Command Palette".

**MAS Reference:**
MAS1.3.1: [https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}](url)

**Attachment For Reference:**
[[Accessibility]A11y_VSCode_CommandPalette_Screenreader.pptx](https://github.com/Microsoft/vscode/files/2114005/Accessibility.A11y_VSCode_CommandPalette_Screenreader.pptx)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/52383
