### ISSUE TITLE
Outline view always follows the cursor

### ISSUE THREAD

**Issue by mattacosta** [Microsoft/vscode#52250]
Issue Type: <b>Bug</b>

Steps to reproduce:
1. Show the outline view for a typescript file (preferably with a class in it).
2. Disable 'Follow Cursor'.
3. Move the cursor position around.
4. Enable 'Follow Cursor'.
5. Move the cursor position around.

Actual:
Child symbols are selected in the outline view regardless of the setting.

Expected:
Moving the cursor with the setting disabled should not change the outline view selection or expand it if it has children.

VS Code version: Code - Insiders 1.25.0-insider (c51cf862a9604dffe2e3e8792a4b0a45213869a3, 2018-06-18T08:50:30.859Z)
OS version: Windows_NT x64 10.0.17134

Extensions: none

**Comment by jrieken** [comment]
yeah, we fixed that yesterday. please try with latest insiders
