### ISSUE TITLE
[Accessibility]A11y_VSCode_CommandPalette_keyboard: Provided shortcuts key in expanded "Command Palette" are not working.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#52266]
**Environment Details:**
VSCode Version : 1.24.0
OS Version : Win10

**Additional Details:**
Keyboard,MAS2.1.1,MAS2.4.3

**Repro Steps:**
1.Navigate to Settings icon in Activity Bar->Press Enter->Select "Command Palette" from dropdown.
2.Follow the list of actions/shortcuts provided in expanded "Command Palette". 
2.Observed that,the list of shortcuts are provided in expanded "Command Palette" option are not working.

**Actual:**
After opening the "Command Palette" list there are list of shortucts controls such as "clt+alt+downarrow","ctrl+f2" etc but it is not working.

**Expected:**
Provided keyboard shortcuts should be work properly.
Here, provided keyboard shortcuts should works.

**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
[https://microsoft.sharepoint.com/teams/msenable/mas/Pages/browse-fixes.aspx](url)

**User Impact:**
User will get confused on which key the proper action will performed

**MAS Reference:**
MAS2.1.1: [https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={8492c4eb-c179-40ae-8777-cd044ed725a2}](url)
MAS2.4.3: [https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={0de7fbe1-ad7e-48e5-bcbb-8d986691e2b9}](url)

**Attachment For Reference:**
[[Accessibility]A11y_VSCode_CommandPalette_Keyboard.pptx](https://github.com/Microsoft/vscode/files/2114127/Accessibility.A11y_VSCode_CommandPalette_Keyboard.pptx)

Does this issue occur when all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
"clt+alt+downarrow" (Add Cursor Below), "ctrl+f2" (Change All Occurrences) only work when editing a file, but not when the command palette is open. Were you editing a file and did that file have focus when you found it not working?

**Comment by alexandrudima** [comment]
The command palette shows actions and their keyboard shortcuts.

The keyboard shortcuts should be used outside of the command palette. 

i.e. the command palette shows an easier method to invoke an action, directly via shortcuts for the next time the user wants to invoke the action.
