### ISSUE TITLE
Failed to install VS Code update.

### ISSUE THREAD

**Issue by darth3pio** [Microsoft/vscode#52261]
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2114036/vscode-inno-updater.log)
 

- VSCode Version: 1.24 Insider
- OS Version: Windows 10, 17134.112

Steps to Reproduce:

1. Update through VS Code built-in updater
2. Restart VS Code to install the update, the update will progress to a certain point then error.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by anhallbe** [comment]
I'm getting this in Stable and Insiders since a couple of months back.

Have tried uninstall & reinstall several times

Windows 10.0.16299

**Comment by joaomoreno** [comment]
You seem to have #47841.

Please read this comment if you can provide more detail: https://github.com/Microsoft/vscode/issues/47841#issuecomment-393101777

Please read this one to disable background updates: https://github.com/Microsoft/vscode/issues/47841#issuecomment-395017687
