### ISSUE TITLE
Error while installing .NET Core Debugger (VSC 0.10.11)

### ISSUE THREAD

**Issue by maxonico** [Microsoft/vscode#5227]
- VSCode Version: 0.10.11
- OS Version: Windows 8.1 x64

Can't install the C# debugger.

Steps to Reproduce:

1. Install .NET Core SDK
- 1.1. dotnet --version =  **_1.0.0-rc2-002349_**
2. Create a new dummy project (dotnet new)
3. Restore (dotnet restore)
4. Check build is working, and works (dotnet build)
5. Install VS Code (**_0.10.11_**)
6. Install C# extensions for VSC (open VSC, press F1, type: **_ext install c#,_** press Enter and wait the installer to finish)
7. Restart VSC after C# extensions have been installed
8. In VSC, open a CS file, and check the output window
9. After installing dependencies, you eventually get to the debugger installation, and get a: 

> Error: Can not find runtime target for framework 'DNXCore,Version=v5.0' compatible with one of the target runtimes: 'win81-x64, win8-x64, win7-x64'. Possible causes:
1. The project has not been restored or restore failed - run `dotnet restore`
2. The project does not list one of 'win81-x64, win8-x64, win7-x64' in the 'runtimes' section.

This is my project.json file:

`{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-3002349"
    }
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "portable-net45+wp80+win8+win81-x64+win8-x64+wpa81+dnxcore50"
      ]
    }  
  }
}`

and NuGet.config file (root of the project):

`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
  </packageSources>
</configuration>`

And this is my NuGet.config file inside of "Users\%USER%\\.vscode\extensions\ms-vscode.csharp-0.3.7\coreclr-debug":

`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    
    <clear />
    <add key="dotnet-core" value="https://www.myget.org/F/dotnet-core/api/v3/index.json" />
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="coreclr-debug" value="https://www.myget.org/F/coreclr-debug/api/v3/index.json" />
  </packageSources>
</configuration>`

Thanks.

**Comment by egamma** [comment]
Moving to  omnisharp-vscode for investigation.

**Comment by egamma** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#183
