### ISSUE TITLE
With custom titlebar, window title is disappeared when launch without workspace

### ISSUE THREAD

**Issue by yume-chan** [Microsoft/vscode#52271]
Issue Type: <b>Bug</b>

Testing the new custom titlebar implementation (#51422)

![screenshot 10](https://user-images.githubusercontent.com/1330321/41582069-26706ed8-73d3-11e8-8771-47211e5a01a2.png)
`"window.titleBarStyle": "native"`

![screenshot 11](https://user-images.githubusercontent.com/1330321/41582078-2a58e660-73d3-11e8-8d92-9ded51db3a4c.png)
`"window.titleBarStyle": "custom"`

Close workspace and restart, so no folder is opened when startup, the old behavior will display program name in title bar, but the custom titlebar won't.

VS Code version: Code - Insiders 1.25.0-insider (2cb30794e7e0b4edd2907be895a0410fd601b736, 2018-06-19T05:18:30.374Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (2.92GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by sbatten** [comment]
fixed by 0977a4c3866a108dc93be6a643dabdee54bc2cf1
