### ISSUE TITLE
With custom titlebar, the `window.enableMenuBarMnemonics` setting is not complied

### ISSUE THREAD

**Issue by yume-chan** [Microsoft/vscode#52275]
Issue Type: <b>Bug</b>

Testing the new custom titlebar implementation (#51422)

1. Set `"window.titleBarStyle": "custom"`, `"window.enableMenuBarMnemonics": false`
2. Press <kbd>Alt</kbd>+<kbd>F</kbd>

The "File" menu still pops up.

VS Code version: Code - Insiders 1.25.0-insider (2cb30794e7e0b4edd2907be895a0410fd601b736, 2018-06-19T05:18:30.374Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (3.01GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by sbatten** [comment]
fixed by 88904d72696fd93e6b35864e0adb4434df3341dc
