### ISSUE TITLE
Elementary OS Freya VSCode icon issues.

### ISSUE THREAD

**Issue by hristokkanchev** [Microsoft/vscode#5228]
- VSCode Version: 0.10.11
- OS Version: Elementary OS Freya

Hello!

When running VSCode under Elementary OS Freya the VSCode icon is blurry and not focused compared to other icons it seems. Also I am not able to pin in to the Dock and open VSCode from there. It only gives me the option to close VSCode when it's opened. Other programs give me the option to keep them in the Dock.

Blurriness in icon issue:
![VSCode icon](https://sc-cdn.scaleengine.net/i/3b74977c06e3782866e8ec270a558e46.png)

Dock issue:
I am not able to take a screenshot of this issue but it basically gives me only one option and that is to close VSCode.

Steps to Reproduce:

1. Run Elementary OS Freya.
2. Open VSCode.

**Comment by Tyriar** [comment]
This is fixed when installed via .deb package. This is available in the current insiders but is coming to stable very soon too.

![image](https://cloud.githubusercontent.com/assets/2193314/14503484/26ad5f06-0165-11e6-98ea-6462af03cbc0.png)

**Comment by hristokkanchev** [comment]
Glad to hear and see that this is fixed. Are you able to pin the VSCode icon to the Dock and run it from there though?

**Comment by Tyriar** [comment]
Yeah, the package adds a [desktop entry](https://github.com/Microsoft/vscode/blob/master/resources/linux/code.desktop) which is what enables that :+1:
