### ISSUE TITLE
Cannot open the issue reporter form custom titlebar

### ISSUE THREAD

**Issue by EbXpJ6bp** [Microsoft/vscode#52284]
Issue Type: <b>Bug</b>

Testing #51422

Steps to Reproduce:
1. Click [Help]->[Report Issue]
2.  It's not responding to my clicks

VS Code version: Code - Insiders 1.25.0-insider (b4a18da6e78f95295ea6538f5ae8dd0c9f0869a9, 2018-06-19T07:49:07.900Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.95GB (1.22GB free)|
|Process Argv|D:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe --locale=en|
|Screen Reader|no|
|VM|67%|

</details>

**Comment by TomSputz** [comment]
This issue also applies to a few other menu items, e.g:

- Right clicking on a view in the activity bar, and trying to use the 'Hide' option
- Help > Documentation

**Comment by RMacfarlane** [comment]
@TomSputz  The issue with "hide" seems to be orthogonal to the original issue and still reproduces so I opened another bug for it: https://github.com/Microsoft/vscode/issues/53195

And the issue with the SCM menu is tracked here:  https://github.com/Microsoft/vscode/issues/52455
