### ISSUE TITLE
Intelligent prompt

### ISSUE THREAD

**Issue by q1183149917** [Microsoft/vscode#52289]
Issue Type: <b>Bug</b>

Intelligent prompts (code hints), the "intelligent prompt" in the encoding process is invalid, and you need to restart the vscode to change back to normal.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.95GB (3.19GB free)|
|Process Argv|F:\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.18.0
php-intellisense|fel|2.3.3
file-icons|fil|1.0.12
auto-rename-tag|for|0.0.15
vue-snippets|hol|0.1.7
ftp-sync|luk|0.3.3
vscode-language-pack-zh-hans|MS-|1.24.3
mssql|ms-|1.3.1
python|ms-|2018.5.0
JavaScriptSnippets|xab|1.6.0

</details>

**Comment by chrmarti** [comment]
Could you provide steps to reproduce and a screenshot?
