### ISSUE TITLE
Node debug processes hang

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#5229]
- VSCode Version: 1.0.0-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. clone vscode-eslint
2. cd eslint && npm install && code-alpha .
3. cd eslint-server && npm install && code-alpha .
4. press Ctrl+Shift+B in both instances
5. Install eslint npm package into a workspace folder (npm install eslint)
6. Switch to the one having eslint open
7. Press F5. In the dev instance open the workspace folder created in step 5
8. Switch to code having eslint-server open
9. Attach the debugger to the server by pressing F5
10. Go to the dev instance and reload the instance
11. Go back to code having eslint-server open
12. Try to reattach the debugger. It fails

 I am pretty sure that this worked in the past.

**Comment by bpasero** [comment]
@dbaeumer is this before or after the electron update?

**Comment by dbaeumer** [comment]
I saw this before the electron update.

**Comment by isidorn** [comment]
In the end, I could follow steps but I am running first into #5313

**Comment by isidorn** [comment]
With latest changes from Ben regarding #5313 I can no longer repro this on OS X.
@dbaeumer will also try on windows with latest
@egamma let me know if you still see it with latest

**Comment by isidorn** [comment]
Closing this. Please reopen @dbaeumer if you still see it

**Comment by dbaeumer** [comment]
Didn't see it again.
