### ISSUE TITLE
Replace may lead a crash

### ISSUE THREAD

**Issue by yueyang68** [Microsoft/vscode#523]
When use the replace function in a large file(more than 20MB), the vs code will crash.

**Comment by alexandrudima** [comment]
@yueyang68 Can you please help me out with a specific reproducible example (i.e. large file and what to search for, what to replace with).

Thank you!

**Comment by yueyang68** [comment]
Sorry, due to the data privacy, I can't just send the file to you. The size of the file is more than 20 MB and the word I want to replace appears many times in this file.When I click the "Replace All" button, this may lead a crash. I will try to get a file that will reproduce this crash and send to you.

**Comment by alexandrudima** [comment]
I have tried replace all in a 20MB+ file multiple times and VSCode did not crash for me. If you can share even a similar file or a generator program that generates a file of similar characteristics I can look into it in greater depth, but without a reproducible case I cannot investigate what goes wrong.
