### ISSUE TITLE
Add keybinding for resizing active pane in small increments

### ISSUE THREAD

**Issue by davidpmccormick** [Microsoft/vscode#5230]
Please consider adding a keybinding for resizing the current pane.

**Comment by Tyriar** [comment]
There is a minimize other editors command (`workbench.action.minimizeOtherEditors`), in addition to an even editors width command (`workbench.action.evenEditorWidths`). Adding keybindings for these in your keybinding.json will probably help accomplish what you want.

**Comment by davidpmccormick** [comment]
Resizing a pane horizontally (instead of dragging the gutter) – cf. https://atom.io/packages/resize-panes

**Comment by dodalovic** [comment]
👍

**Comment by bpasero** [comment]
We have `workbench.action.decreaseViewSize` and `workbench.action.increaseViewSize` for a while.
