### ISSUE TITLE
[Accessibility]A11y_VSCode_AddConfiguration_Screenreader: Jaws is not reading the value of expanded "AddConfiguration" option

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#52310]
**Environment Details:**
VSCode Version : 1.24.0
OS Version : Win10

**Additional Details:**
Screenreader,JAWS[18.0.5038],MAS1.3.1

**Repro Steps:**
1.Launch VS Code while JAWS is ON.
2.Navigate to Debug(Alt+D) menu option and select "Add Configuration" from dropdown.
3.Observed that,JAWS is not reading value of expanded "AddConfiguration" option.

**Actual:**
Instead of reading selected value of expanded "AddConfiguration" JAWS is reading launch.json and "Add configuration" button name.

**Expected:**
JAWS should reads the selected value of expanded "AddConfiguration" such as "{}Node.js:Attach".

**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
[https://microsoft.sharepoint.com/teams/msenable/mas/Pages/browse-fixes.aspx](url)

**User Impact:**
User will not able to understand the value of expanded "AddConfiguration" option.

**MAS Reference:**
[https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}](url)

**Attachment For Reference:**
[[Accessibility]A11y_VSCode_AddConfiguration_ScreenReader.pptx](https://github.com/Microsoft/vscode/files/2114791/Accessibility.A11y_VSCode_AddConfiguration_ScreenReader.pptx)

Does this issue occur when all extensions are disabled?: Yes

**Comment by auchenberg** [comment]
Closing this issue as it's only observed in JAWS, and this isn't strictly needed to meet MAS C compliance.
