### ISSUE TITLE
Update to 1.24 failed (access denied)

### ISSUE THREAD

**Issue by El-Loco-Pinguino** [Microsoft/vscode#52312]
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2114782/vscode-inno-updater.log)
- VSCode Version: 1.24
- OS Version: Windows 10 64-bit

I tried to update to 1.24 when asked by VSC. It downloads without any problem. When installing the new version, it crashes. (Looking by the .log file attached, it's because of the renaming of a file)
It already happened when I updated from 1.22 to 1.23.

**Comment by joaomoreno** [comment]
You seem to have #47841.

Please read this comment if you can provide more detail: https://github.com/Microsoft/vscode/issues/47841#issuecomment-393101777

Please read this one to disable background updates: https://github.com/Microsoft/vscode/issues/47841#issuecomment-395017687
