### ISSUE TITLE
when i check the source directory no html css file is visible

### ISSUE THREAD

**Issue by NikosEfthias** [Microsoft/vscode#5231]
this question is just out of curiosity when i build an app using electron all my files are visible whitin the resources folder but when i check vscode they are not there just module exports etc. how do you do that ?

**Comment by bpasero** [comment]
@NikosEfthias can you attach a screenshot?

**Comment by NikosEfthias** [comment]
![](http://i.imgur.com/rJleGnd.png) here as you can see (or cannot see :)) theres no actual source file like main.js or index.js just 3rd party modules and images

**Comment by bpasero** [comment]
@NikosEfthias I meant to show more information how you think in VS Code there is a bug. I am not sure I understand the issue you raise.

**Comment by NikosEfthias** [comment]
@bpasero as i mention above this isnt a bug i just ask because of curiosity i dont know whether you have a kinda user forum and simply i couldnt think somewhere else to ask my question rather then here

**Comment by bpasero** [comment]
@NikosEfthias ok I see, we do not have a forum, I really suggest you forward this question to the Electron forum: https://discuss.atom.io/c/electron

As for VS Code we have a step in our build process that bundles all our JS files into one large JS file. But still, we do have all our resources under the resources folder of Electron, I am not sure how this is different from other Electron applications.
