### ISSUE TITLE
Difficult to identify top scroll bar

### ISSUE THREAD

**Issue by itsamy003** [Microsoft/vscode#52323]
Issue Type: <b>Bug</b>

I felt, its difficult to identify top scroll bar & scroll   when files are more in a single VS code window. 

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:02.816Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz (4 x 2893)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (1.74GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
expand-region|let|0.1.2
material-icon-theme|PKi|3.5.0
sort-lines|Tyr|1.7.0

(1 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment]
@itsamy003 I am not sure what you mean, can you perhaps show a screenshot of what is difficult to identify ?

**Comment by itsamy003** [comment]
Scroll bar is difficult to identify in the background colour and it’s very
small.

**Comment by alexandrudima** [comment]
It is possible to install / change to themes which have different colors for the scrollbars.
