### ISSUE TITLE
Search all files from Console

### ISSUE THREAD

**Issue by KUGA2** [microsoft/vscode#52320]
In any sourcefile, i mark some text and press CTRL+SHIFT+F to open the "Search all files" menu with the selected text already filled in.
Can you implement this to work also in the Terminal panel?

This is handy when you get a message in the output and want to check where it comes from.

**Comment by roblourens** [comment]
This is what you mean, right?

- Select text in terminal
- Press cmd+shift+f
- Search with that text

How do I get the selected text in temrinal @Tyriar ?

**Comment by Tyriar** [comment]
We already support ctrl+f to find within a terminal (focus it and hit ctrl+f), I'd say searching _all_ terminals is out of scope.

<img width="724" alt="screen shot 2018-09-13 at 9 12 58 pm" src="https://user-images.githubusercontent.com/2193314/45529399-d23ea400-b799-11e8-93a0-00007bfb2dae.png">

**Comment by Tyriar** [comment]
@roblourens doh, you're right. Use `ITerminalService.getActiveInstance()`, null check that and then `ITerminalInstance.selection` (string | undefined)

**Comment by roblourens** [comment]
Can I tell whether focus is in the terminal? I see `onFocus` events but not `isFocused`.

**Comment by Tyriar** [comment]
@roblourens can you make a new command and bind it when `terminalFocus` context is true? Or use an arg to indicate terminal focus in the existing command?

**Comment by roblourens** [comment]
What do you mean by 

> Or use an arg to indicate terminal focus in the existing command?

Can I just query the context key?

**Comment by Tyriar** [comment]
@roblourens using `args` in a keybinding https://code.visualstudio.com/docs/getstarted/keybindings#_command-arguments

```
{
  "key": "ctrl+shift+f",
  "command": "workbench.action.findInFiles",
  "when": "terminalFocus",
  "args": { "context": "terminal" }
}
```

The command can then check for args

**Comment by roblourens** [comment]
It needs to work even when not invoked with a keybinding though, I found that people expect to be able to copy some text then click the 🔍 and search with that text.

**Comment by Tyriar** [comment]
Oh I didn't even know that was a thing, I'm not sure how you would check if the terminal was focused other than with `document.activeElement`.

**Comment by roblourens** [comment]
I think I can use IContextKeyService#getValue

**Comment by roblourens** [comment]
Note to self, the context key is no longer set when the search viewlet is revealed after clicking on the 🔍. We would need something tracking focus around the workbench so we know where it came from.
