### ISSUE TITLE
Keyboard shortcut for add cursor above/below not working

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5233]
- VSCode Version: 1.0.0-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Open a file
2. Put your cursor on a line and press Ctrl+Alt+UpArrow

Actual:
Nothing happens. No other cursors are made. If you press F1 and select it from the actions list it does work.

**Comment by alexandrudima** [comment]
@vsccarl Sometimes Ctrl+Alt+Up and Ctrl+Alt+Down are "eaten" by the video graphics driver at the OS level before they reach us. Please see https://superuser.com/questions/279756/how-to-disable-the-screen-orientation-hotkeys-in-windows-xp for example.
