### ISSUE TITLE
Grid: in a 2x2 grid, the settings editor does not prevent sizing when getting small

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#52333]
Steps to Reproduce:

1. enter 2x2 grid
2. open settings editor in second grid
3. make grid small

=> at one point I would have expected the settings editor to prevent getting smaller

![grid-tw](https://user-images.githubusercontent.com/900690/41601379-96a96c68-73d8-11e8-9db3-c6dc640f40af.gif)

Is this just a missing adoption of the editor size constraints for the settings editor?

**Comment by joaomoreno** [comment]
Hehe! Nah, it's just a 2x2 issue, I knew we'd find some!!

**Comment by bpasero** [comment]
🥂
