### ISSUE TITLE
Test: Grid Editor Layout smoke test

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#52334]
- [x] any os @stevencl   
- [x] any os @rebornix 

Complexity: 3

The grid editor layout feature was already tested last milestone extensively (see https://github.com/Microsoft/vscode/issues/50458) but there were still quite a bit of changes going in during this milestone. The idea is to do some **exploratory** testing to ensure we have not introduced new bugs by ensuring:

* you can create editor layouts and sizing works good and is preserved across reloads
* there are no exceptions in the console when working with the grid overall
* try with normal text editors, diff editors, settings editor and webview
  * side-by-side and settings editor have different size constraints, to try resizing them to their minimum sizes

**2x2**

The 2x2 grid is newly implemented:

* You can enable it via `View > Editor Layout > Grid (2x2)`
* Test that the sashes are connected
* Test that as soon as the grid structure changes, the 2x2 behaviour is dropped
* Test that everything is persisted on reload
* Test that editor minimum widths/heights are respected (eg. the settings editor has a larger minimum width/height than regular editors)

**Comment by rebornix** [comment]
It works as expected during my testing with markdown preview, zen mode, centered editors, diff view, etc. I really like it.
