### ISSUE TITLE
Add the ability to hide workspace titlebar

### ISSUE THREAD

**Issue by zaken** [Microsoft/vscode#52338]
Hi, I think it would be nice to be able to hide this thingie. Personally, I never ever use those buttons. The workspace name isn't *that* important and it's shown in the titlebar anyway.

![image](https://user-images.githubusercontent.com/21025134/41606465-6998406e-73ec-11e8-98cd-301aaf302773.png)

**VSCode**: 1.24.1
**OS**: Win 10

**Comment by TomSputz** [comment]
Alternatively, could it just be pushed up into the Explorer view title so long as you aren't in a multi root workspace?

Could look like this ( A very sketchy mockup) - https://i.imgur.com/RCGjMOm.png

I'm just kinda averted to removing them entirely as if you don't have any whitespace left in the box doe to a smaller window / lots of files, adding a new folder gets pretty tedious

**Comment by yume-chan** [comment]
@TomSputz if the folders view is the only view in the explorer, it will. Or it's a little difficult to arrange other views in the panel.

@zaken I think the title is here to tell you this is the explorer. Does it really take so much space?
