### ISSUE TITLE
Search results in tree structure

### ISSUE THREAD

**Issue by aaltaras** [Microsoft/vscode#52349]
Issue Type: <b>Feature Request</b>

Hello,

I start using VSCode and found it very fast and love it, but few features are missing compare to eclipse.
1. return search results in tree structure 
2. call hierarchy

It would be great to have both option

Thanks 

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
OS version: Darwin x64 16.7.0

**Comment by chrmarti** [comment]
The search results in a tree are tracked with https://github.com/Microsoft/vscode/issues/20224.
The call hierarchy is tracked with https://github.com/Microsoft/vscode/issues/16110.
