### ISSUE TITLE
Strange artifacts in new menu

### ISSUE THREAD

**Issue by JacksonKearl** [Microsoft/vscode#52342]
![image](https://user-images.githubusercontent.com/8586769/41612551-1dfb4ce4-73a8-11e8-8ca4-469529bed3be.png)

happens on OSS and latest insiders

**Comment by JacksonKearl** [comment]
Also is it by design that "Install from VSIX" is blue? Doesn't seem to have similar emphasis with normal menus

**Comment by JacksonKearl** [comment]
https://github.com/Microsoft/vscode/blob/e8008a7953ef7abdadd01341c98bb7d4a69b3078/src/vs/workbench/parts/extensions/electron-browser/extensionsActions.ts#L1150
https://github.com/Microsoft/vscode/blob/e8008a7953ef7abdadd01341c98bb7d4a69b3078/src/vs/workbench/parts/extensions/electron-browser/extensionsActions.ts#L1173
This is the root cause. I'm not sure why we pass the class as 'clear-extensions' here.

**Comment by JacksonKearl** [comment]
If I had to guess it would be overzealous copying long ago that didn't show up until now because native menus don't render icons?

**Comment by sbatten** [comment]
@JacksonKearl thanks for the investigation. 

@ramya-rao-a can It appears so, but just to check, can I remove these classes safely?

**Comment by sbatten** [comment]
fixed the first issue with dcffd79899fdc946b92fc05b4172c989fa49a565

**Comment by sandy081** [comment]
@sbatten How can I reproduce this? I do not see the blue colour action when I am running from dev. I am on Mac.

**Comment by sbatten** [comment]
@sandy081 repro is on windows/Linux with setting `window.titleBarStyle` set to `custom`

**Comment by sandy081** [comment]
Theme is applied to all actions with `extension-action` class. Those who does not want theme to be applied should not have this class. Cleaned up.

**Comment by sandy081** [comment]
Reverted the fix and made changes to theme participants to contribute specific themes as the actions being reused in extension editor.
