### ISSUE TITLE
Problems don't clear when closing an existing file

### ISSUE THREAD

**Issue by Cirieno** [Microsoft/vscode#52348]
Issue Type: <b>Bug</b>

I have to work with legacy javascript files that are thousands of lines long and have hundreds of errors listed in the Problems panel.  As there is no way to clear the Problems panel or hide specific files or problem categories, I have made a little test.

1) Open a new editor window (language = javascript)
2) Type ```a === b;```
3) Problems panel shows: ```[ts] Cannot find name 'a'. [ts] Cannot find name 'b'.```
4) Close the editor without saving and the Problems panel clears.

next: 

5) Externally save a javascript .js file that contains only the code ```a === b;```
6) Open it in VSCode.
7) You will see the same Problems listed as 3) above.
8) Close this file.  Problems panel does not clear.

The error also happens if you save your new document directly and then close it (skipping steps 4-7).

Reproduceable with ```--disable-extensions```: yes.

I have seen other threads that speak of Problems lists needing to be cleared by the owner extensions of the error, but this is the the javascript/Typescript parser built in to VSCode.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2540M CPU @ 2.60GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (3.11GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe --disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled

**Comment by mjbvz** [comment]
@dbaeumer This is a result of the change for #47386. Any way we can be smarter here or should we close this as by-design?

**Comment by Cirieno** [comment]
Reading that thread, it seems people running tasks or with workspaced projects wanted to see the errors for all files, not just the currently-open ones.

But for those people who aren't working in workspaces or projects or running tasks -- those who are simply editing standalone files -- it doesn't make sense for the errors to hang around when the files are closed.  And some of the errors reported can never be "fixed" or avoided (such as references in a script to variables defined in other scripts).

Addendum: I have just found "restart TS server" in the command palette that clears the old issues out and relists issues from the open files, but this feels like a heavy-handed fix.

I would propose a right-click option on the filename in the panel to "close this Problem list" or similar.

(Further, it would be nice to have a way of saying "ignore this error" for specific errors, but that's something for another Feature Request).

**Comment by dbaeumer** [comment]
The difference is indeed the way how that file got opened. I would for a language like typescript expect that if I open a project and have inter file dependencies that errors in the problems view go away if fixed even if not both files are open. However if I open a single file I see the desire that the errors should got away if the file is closed. 

In general we try to do the following in VS Code:

- for single file validation we remove them on close
- for project validation we should keep them around on close. Since the TS server is not there yet (I still have the feeling project validation might come) we `emulated` this with not removing the errors on close.

So I am a little reluctant to say that even if we fix all the issues around #47386 that cleaning the TS errors on file close is not what I would expect.

**Comment by deevincentday** [comment]
I edit json files containing data.  I am frustrated by the problems panel not getting cleared when I close an editor.  I end up with a huge list of problems when I only want to see the problems for the file I am viewing.  I also wish there was a way of telling VSCode that something it identifies as a problem is not actually a problem.  For example we use farmer all my farmer files are identified as a problem but they are not.  There is no support for farmer in VS Code.  I would like to tell vs code to ignore all farmer files.
![image](https://user-images.githubusercontent.com/30651204/42328014-2a8e2232-8065-11e8-9a72-0e777900dbe4.png)
