### ISSUE TITLE
lorem*2 only give one line of lorem

### ISSUE THREAD

**Issue by IronGhost63** [microsoft/vscode#52345]
- VSCode Version: 1.24.1
- OS Version:  macOS 10.13.5

Steps to Reproduce:

1. Create/Open an HTML file
2. type lorem*2 (also happen with lorem\<number\>*2) then tab

Result is expected to be 2 lines of lorem. but instead there is just one line with \<number\>*2 words.

Works fine with lorem*3

![untitled](https://user-images.githubusercontent.com/7050540/41613706-877e9aea-7420-11e8-82a8-61836d6650c9.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Cirieno** [comment]
I can recreate this.

lorem*<n> is fine, but lorem*2 gives one long, unbroken line.  In each test I have noted an element of punctuation, no break, and then the next word:

> hic voluptate!Ab, velit
> sint aperiam.Sequi animi
> accusamus excepturi?Ad veritatis

VSCode 1.24.1

**Comment by ramya-rao-a** [comment]
PRs are welcome to fix this bug.

The fix would be to the the upstream module called `vscode-emmet-helper`. There is a [test case]( https://github.com/Microsoft/vscode-emmet-helper/blob/master/src/test/emmetHelperTest.ts#L892) there for the case of `lorem*3` which passes. As observed in this issue, changing that to 2 fails the test case.

**Comment by TheDancingCode** [comment]
One way around this is setting this in your vscode user settings:
```json
"emmet.syntaxProfiles": {
    "html":{
        "inline_break": 1
    }
}
```

**Comment by dyong0** [comment]
@TheDancingCode Thanks, that gave me a hint to fix this issue!
https://github.com/Microsoft/vscode-emmet-helper/pull/26

**Comment by dyong0** [comment]
@ramya-rao-a, could you please review https://github.com/Microsoft/vscode-emmet-helper/pull/26?

**Comment by ramya-rao-a** [comment]
@dyong0 I wouldnt change the default for `inline_break` to 2 as it changes expectations for how inline elements are expanded.
For example, `span*2` is expected to expand to `<span></span><span></span>` where as `span*3` is expected to expand to 
```
<span></span>
<span></span>
<span></span>
```

@sergeche

When trying out lorem in https://docs.emmet.io/, I noticed that `lorem*n` always surrounded the text by a `div` tag when `n` > 1

But the new emmet modules dont do this and so end up becoming an inline element and forced to follow the `inline_break` configuration.

How do you suggest we tackle this?

**Comment by TheDancingCode** [comment]
Surrounding `lorem*n` with `div` tags for `n` > 1 makes sense. Lorem Ipsum is meant to serve as dummy text or data in html elements, so I don't see any use for `lorem*n` except a quick way to create more **elements** containing text. If you simply want a longer text, that's what `loremN` is for. If you want more paragraphs, there's `p*n>lorem`.

**Comment by ramya-rao-a** [comment]
I've logged https://github.com/emmetio/expand-abbreviation/issues/23 as an upstream issue with emmet and marking this issue as out of scope.

Once there is a solution from upstream, we can use the same in VS Code

**Comment by rzhao271** [comment]
\closedWith dc5a3da

**Comment by rzhao271** [comment]
Verifier: Ensure that running `Emmet: Expand Abbreviation` on `lorem*2` in an HTML file expands to give two lines of lorem ipsum instead of just one.
