### ISSUE TITLE
When dragging sidebar views to rearrange, individual items in the Open Editors view are highlighted

### ISSUE THREAD

**Issue by iansan5653** [Microsoft/vscode#52344]
- VSCode Version: 1.25.0-insider
- OS Version: Windows 10 Home - 1803

Steps to Reproduce:

1. Select the Explorer sidebar tab
2. Drag the Outline or File Hierarchy views as if to rearrange them
3. Move the cursor over an item in the Open Editors view
4. The individual editors will change color along with the entire view, making it seem as if you can drop a sidebar view into an open editor and something will happen. What should actually happen is that the view should highlight (since its location will be replaced; it does do this), but the individual items should not be affected.

Screenshot: 
![image](https://user-images.githubusercontent.com/2294248/41613352-55b83a32-73c3-11e8-831c-ef16a63e4d02.png)
I am holding the File Hierarchy view over the index.js file in that screenshot.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
I acknowledge the issue, the problem is that the OpenEditor view is not differentiating between drag events
https://github.com/Microsoft/vscode/blob/0a35cbfcf422054090971f78cf3a357cb42c3bae/src/vs/workbench/parts/files/electron-browser/views/openEditorsView.ts#L629

PR to fix this is welcome

**Comment by iansan5653** [comment]
I was able to add a check to prevent the hover styling unless the item being dragged is another open editor in the list (see https://github.com/iansan5653/vscode/commit/5add9ceeab367c4c9427f28709c6930971cd7d16), however this also means that when tabs are dragged over the Open Editors panel (ie, when there's multiple groups; you can drag a tab into a group and it will duplicate into that group), it doesn't have any styling anymore. I couldn't figure out a way to check if the dragged object is a tab.

**Comment by isidorn** [comment]
@iansan5653 yeah it is not so simple
You would need to check the dragged data. If there is an elegent solution to fix this please provide a PR. If too complex or computation intensive I would prefer to leave the issue open for now. Thanks

**Comment by iansan5653** [comment]
@isidorn So just to make sure, the only things that should trigger the `focused` class on open editors are the open tabs and the other open editors in the list, correct?

**Comment by isidorn** [comment]
@iansan5653 no. Dragging resources from the explorer, adn dragging things outside of vscode should also trigger it
