### ISSUE TITLE
C# file kills performance

### ISSUE THREAD

**Issue by bigonazzi** [Microsoft/vscode#52341]
I've got a machine generated cs file weighting at 99KBs that takes minutes to open on my laptop rendering vs code completely unresponsive in the process. I've tried disabling all extensions and I can still repro the issue. Please contact me privately I'll happily share the file.

CPUs | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwarerasterization: disabled_softwarevideo_decode: enabledvideo_encode: enabledvpx_decode: enabledwebgl: enabledwebgl2: enabled
Memory (System) | 15.85GB (4.84GB free)
Process Argv | C:\Program Files\Microsoft VS Code\Code.exe C:\Users\dariobig\Desktop\modules\...
Screen Reader | no
VM | 0%

Extensions: none

**Comment by alexandrudima** [comment]
@bigonazzi Can you please share the file or another one that reproduces the issue with us? My email address is viewable in my GitHub profile.

**Comment by alexandrudima** [comment]
I have reduced and anonymised the repro to the following code pattern:

```cs
double aaaaAaaaaa0=((A_AaaaAaaaaA1 > 0.1) ? ((A_AaaaaaaaAaAaaaaaaaa > 0.1) ? -0.111111111111111 : ((A_AaaaAaaaaa > 111.1) ? ((A_AaaaAaaaaa > 11.1) ? -0.111111111111111 : ((A_AaaaAaaaaA1 > 0.1111111) ? -0.111111111111111 : ((AaAaa_AaaaaaaAaaa > 0.1111111) ? 0.111111111111111 : 0.0111111111111111))) : -0.111111111111111)) : ((A_AaaaaaaAaaaaA1 > 0.111111) ? ((AaAaa_AaaaaaaAaaa > 0.1111111) ? ((A_AaaaAaaaaa > 111.1) ? 0.11111111111111 : -0.111111111111111) : ((AaaaAaaa_AaaaaaaAaaaa > 0.1111111) ? ((A_AaaaAaaaaa > 111.1) ? ((A_AaaaaaaAaaaaA1 > 0.1111111) ? -0.111111111111111 : ((AaaaAaaa_AaaaaaaAaaaaAaaaaaaaa > 0.1111111) ? -0.111111111111111 : ((A_AaaaaaaaAaaaa > 0.1) ? -0.111111111111111 : 0.111111111111111))) : -0.111111111111111) : -0.111111111111111)) : ((A_AaaaAaaaaA1 > 0.111) ? ((AaaaAaaa_AaaaaaaAaaaa > 0.1111111) ? ((A_AaaaAaaaaa > 111.1) ? -0.111111111111111 : -0.11111111111111) : -0.111111111111111) : ((AaaaAaaa_AaaaaaaAaaaa > 0.1111111) ? ((AaAaa_AaaaaaaAaaaaaa > 0.1111111) ? -0.111111111111111 : -0.111111111111111) : -0.111111111111111))));
```

**Comment by alexandrudima** [comment]
By logging from oniguruma, the following regular expression in the C# grammar causes the tokenization time to skyrocket:

```
(?x)
(?<return-type>
  (?<type-name>
    (?:
      (?:ref\s+(?:readonly\s+)?)?   # ref return
      (?:
        (?:(?<identifier>@?[_[:alpha:]][_[:alnum:]]*)\s*\:\:\s*)? # alias-qualification
        (?<name-and-type-args> # identifier + type arguments (if any)
          \g<identifier>\s*
          (?<type-args>\s*<(?:[^<>]|\g<type-args>)+>\s*)?
        )
        (?:\s*\.\s*\g<name-and-type-args>)* | # Are there any more names being dotted into?
        (?<tuple>\s*\((?:[^\(\)]|\g<tuple>)+\))
      )
      (?:\s*\?\s*)? # nullable suffix?
      (?:\s*\[(?:\s*,\s*)*\]\s*)* # array suffix?
    )
  )\s+
)
(?<interface-name>\g<type-name>\s*\.\s*)?
(\g<identifier>)\s*
(<([^<>]+)>)?\s*
(?=\()
```

**Comment by aeschli** [comment]
This issue was moved to atom/language-c#283

**Comment by aeschli** [comment]
This issue was moved to dotnet/csharp-tmLanguage#130
