### ISSUE TITLE
Code with syntax errors gets dimmed out too easily

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#52346]
Issue Type: <b>Bug</b>

See the following example. Situations like this can easily happen when editing code. Thus, the highlighting jumps back and forth between different levels of opacity.

VS Code version: Code - Insiders 1.25.0-insider (b4a18da6e78f95295ea6538f5ae8dd0c9f0869a9, 2018-06-19T07:38:09.923Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.53GB free)|
|Process Argv|/Users/kmaetzel/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_14822946|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
solargraph|cas|0.17.4
npm-intellisense|chr|1.3.0
regex|chr|0.2.0
githistory|don|0.4.1
gitlens|eam|8.4.1
tslint|eg2|1.0.32
vscode-npm-script|eg2|0.3.4
vsc-material-theme|Equ|2.1.0
git-project-manager|fel|1.6.1
crazy|kie|0.0.2
svgpreview|kis|0.2.0
vscode-azurestorage|ms-|0.3.1
mssql|ms-|1.3.1
python|ms-|2018.5.0
azure-account|ms-|0.4.0
azurecli|ms-|0.4.2
Go|ms-|0.6.83
vsliveshare|ms-|0.3.295
printcode|nob|2.3.0
vscode-docker|Pet|0.0.27
material-icon-theme|PKi|3.5.0
Ruby|reb|0.18.0
kustovscode|sea|0.0.1
php-syntax-visualizer|vsc|0.0.1
vscode-open-in-github|ziy|1.3.3

(3 theme extensions excluded)

</details>

![screen shot 2018-06-19 at 11 18 03 am](https://user-images.githubusercontent.com/4674940/41616525-0702a2f2-73b3-11e8-97a6-f3e5c85af3c1.png)

**Comment by mjbvz** [comment]
Example:

```js
({
    a: 1
}
b: 1
})
```

The syntax error squiggles also disappear and reappear as you edit the file, correct?

**Comment by kieferrm** [comment]
The squiggles are stable when I make changes to the file.  I'm guessing the issue is how the code is interpreted.

![screen shot 2018-07-09 at 3 26 31 pm](https://user-images.githubusercontent.com/4674940/42479232-b8d42b2a-838c-11e8-9ee1-c4f6ff60a2d7.png)

**Comment by mjbvz** [comment]
I've opened https://github.com/Microsoft/TypeScript/issues/25591 to track issues like this
