### ISSUE TITLE
Terminal window (CMD) does not wrap long lines

### ISSUE THREAD

**Issue by jsuddsjr** [Microsoft/vscode#52340]
Issue Type: <b>Bug</b>

Open Terminal Window (CMD). Begin typing. Long line does not wrap at the end of the window and end of line is not visible in window.  Expect that terminal window would adjust maximum number of characters according to the width of the viewport. Or, provide a horizontal scrollbar so the contents can be moved into view.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17698

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 0 @ 3.60GHz (8 x 3591)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (8.56GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
fontsize-shortcuts|fos|1.5.0
beautify|Hoo|1.3.2
vscode-filesize|mkx|2.1.0
python|ms-|2018.5.0
csharp|ms-|1.15.2
vsliveshare|ms-|0.3.295
debugger-for-chrome|msj|4.6.0
vscode-findinpage|sat|0.2.5

</details>

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
