### ISSUE TITLE
webkit appearance not working

### ISSUE THREAD

**Issue by nader54** [Microsoft/vscode#52356]
Issue Type: <b>Bug</b>

webkit appearance not working

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.16GB free)|
|Process Argv|/Users/NaderArvanaghi/Text Editors/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_962795|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|3.5.0
font-awesome-codes-html|med|0.0.7
vscode-clang|mit|0.2.2
css-grid-snippets|oha|0.0.5
md2pdf|qin|0.0.1
LiveServer|rit|5.0.0
vscode-icons|rob|7.23.0
java-snippets|tus|0.0.1

(19 theme extensions excluded)

</details>

**Comment by TomSputz** [comment]
Steps to repro?
