### ISSUE TITLE
Error message is chopping while working with multi screen.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#5235]
- VSCode Version: 1.0.0-alpha
- OS Version: Windows10

Steps to Reproduce:
1. Launch app and open root dir for NodeJSExpress project.
2. Open multi screen (3 screen) and try to add reference to the typing files.
3. Verify error message and hover over to get complete error message details.

Actual: When user is working with multi screen then error massage is chopping.
![image](https://cloud.githubusercontent.com/assets/17735796/14512656/db1da3b2-0195-11e6-851f-71c1c17583ed.png)

Expected: It should display complete message when hover over on highlighted error.
![image](https://cloud.githubusercontent.com/assets/17735796/14512699/2ff37272-0196-11e6-8240-a6a3cade44d2.png)

**Comment by jrieken** [comment]
@alexandrudima Isn't that a config options?

**Comment by jrieken** [comment]
@v-pavanp To clarify - you mean it not wrap, or? Because I don't see what is missing about the message, it looks complete to me.

**Comment by v-pavanp** [comment]
Yes, it is not wrap.
If you see the first screenshot, the path for the node.d.ts is not displaying completely.
https://cloud.githubusercontent.com/assets/17735796/14512656/db1da3b2-0195-11e6-851f-71c1c17583ed.png

**Comment by jrieken** [comment]
Ah, understood. Most likely the limits of browser wrapping cos the string is quotes is long and likely no proper break position can be found. We might consider overflowing them from the editor area

**Comment by alexandrudima** [comment]
I believe this has been fixed in the meantime.
