### ISSUE TITLE
make an action of editor.contrib.wordHighlighter

### ISSUE THREAD

**Issue by kascote** [microsoft/vscode#52354]
Currently there are 2 actions (assignable to hot keys) to move between highlighted tokens (```editor.action.wordHighlight.next``` and ```editor.action.wordHighlight.prev```), but there isn't a way to fire the highlighter action except using the mouse and clicking the token.

The action seems to be ```editor.contrib.wordHighlighter``` but can't map it to a hotkey like for example ```editor.action.showHover```.

I'm using VimKeybinding and could be great have support for it.

**Comment by chrmarti** [comment]
I get the highlights when moving the text cursor with the keyboard onto a symbol.

**Comment by kascote** [comment]
@chrmarti but when use the plugin http://aka.ms/vscodevim it don't work, and the action can't be fired from the plugin or I'm missing something ?

**Comment by chrmarti** [comment]
Not sure what the vim extension might do here. /cc @rebornix

**Comment by J-Fields** [comment]
This actually does exist, and VSCodeVim uses it: `editor.action.wordHighlight.trigger`
