### ISSUE TITLE
“files.defaultLanguage”: “powershell” fails to set default lanaguage to PowerShell

### ISSUE THREAD

**Issue by github-12341234** [Microsoft/vscode#52352]
Issue Type: <b>Bug</b>

I want to make #PowerShell the default language in Visual Studio Code on Mac 1.24.1 so that after I enter ⌘N I can immediately start typing PowerShell code and have all the parsing and completion and syntax highlighting work.

Under "User Settings" I did this:

{
    "files.defaultLanguage": "powershell"
}

I then exited and restarted Visual Studio Code.

I then tried ⌘N and typed $ps and pressed the tab key. I got a tab. No completion. No highlighting.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (3.01GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|25%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.5.0
PowerShell|ms-|1.7.0
elm|sbr|0.18.0

</details>

**Comment by chrmarti** [comment]
I get 'Powershell' in the statusbar for the new untitled file when I add that setting. Also syntax highlighting works.

![image](https://user-images.githubusercontent.com/9205389/41640347-ba1d2d72-7461-11e8-872f-f1be57a32689.png)

**Comment by github-12341234** [comment]
I believe you.

When I’m making a change like:




{

    "files.defaultLanguage": "powershell"

}

How do I save the change?


Thanks,

-Chris

**Comment by chrmarti** [comment]
There is File > Save in the main menu.

**Comment by Ayanmullick** [comment]
Saving the settings doesn't change the default Language of VSC to Powershell. It still remains plain text.

**Comment by chrmarti** [comment]
@Ayanmullick Could you open a new issue for this? Thanks.
