### ISSUE TITLE
[suggest] Colors tabs navigations

### ISSUE THREAD

**Issue by djmisterjon** [Microsoft/vscode#52357]
I would love to have a coloring feature for tabs.
To group them by color.
It is easier to navigate by color, especially if you have more than 20 children's and parents modules tabs groin in the navigation.

**What do you think about this feature ??**
This its just a fast example ...
![af4-tg4qgytq4gyhqa](https://user-images.githubusercontent.com/24865815/41622945-3610f112-73df-11e8-8914-27ff7d8f709f.png)
maybe a color bar, or circle, or full color tabs ?
And maybe assign color with left click on tabs ?

thank all for your awesome work.

**Comment by TomSputz** [comment]
What colour would tabs be set to when the are first created? Should it be determined by file type? Directory grouping?

(Also, due to clutter, this would have to be opt-in imo, probably better as an extension)

**Comment by djmisterjon** [comment]
The general idea is mainly to facilitate navigation grouped by modules and class.
I navigate a lot between different module connect in the navigation and I often lose precious seconds to scan with my eyes and read the titles.

It's just to enable a more efficient workflow, and save time to target a modules tabs.
![gameengine scene wefdeaforkflow](https://user-images.githubusercontent.com/24865815/41627398-2ba29406-73ee-11e8-8c1f-e7b46a0b2d48.png)

**Comment by djmisterjon** [comment]
@bpasero hi, can you give me the duplicated tread ? , thank
