### ISSUE TITLE
When searching for font, suggestFontSize is ranked lower than formatOnSave

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#52358]
Issue Type: <b>Settings Search Issue</b>

When searching for font in the settings search, suggestFontSize is ranked lower than formatOnSave

VS Code version: Code - Insiders 1.25.0-insider (b4a18da6e78f95295ea6538f5ae8dd0c9f0869a9, 2018-06-19T07:38:09.923Z)
OS version: Darwin x64 15.6.0

<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.18.0
vscode-eslint|dba|1.4.12
tslint|eg2|1.0.32
vscode-npm-script|eg2|0.3.4
mssql|ms-|1.3.1
vscode-icons|rob|7.23.0

</details><details><summary>Results</summary>

Setting|Extension|Score
---|---|---
workbench.fontAliasing|core|5.004
editor.fontLigatures|core|5.001
editor.fontFamily|core|4.459
editor.fontWeight|core|4.293
editor.fontSize|core|4.143
terminal.integrated.fontSize|core|4.050
editor.suggestFontSize|core|3.838
terminal.integrated.lineHeight|core|3.789
editor.lineHeight|core|3.685
terminal.integrated.fontFamily|core|3.670
markdown.preview.fontFamily|core|3.372
markdown.preview.fontSize|core|3.202
markdown.preview.lineHeight|core|2.733
scss.lint.fontFaceProperties|core|2.666
less.lint.fontFaceProperties|core|2.493
css.lint.fontFaceProperties|core|2.436
terminal.integrated.fontWeight|core|0.968
terminal.integrated.fontWeightBold|core|0.389
editor.tokenColorCustomizations|core|0.319
editor.mouseWheelZoom|core|0.307

</details>

Query: font
Literal matches: 19

**Comment by ramya-rao-a** [comment]
<img width="422" alt="screen shot 2018-06-19 at 2 06 51 pm" src="https://user-images.githubusercontent.com/16890566/41624287-0c0f964e-73ca-11e8-80c6-5b7d2cd2c8bf.png">

**Comment by roblourens** [comment]
These results come from the local filtering, not bing search which is ranked by relevance. We can rank local results by relevance too, there's an issue for it but local search isn't set up for that right now.
