### ISSUE TITLE
CSS Emmet shortcuts for pre-built font families dont work

### ISSUE THREAD

**Issue by aprofromindia** [Microsoft/vscode#52366]
Some useful Emmet CSS shortcuts as according to its [cheatsheet](https://docs.emmet.io/cheat-sheet/) doesn't work, e.g. :-

- `ff:a` -> expands into `font-family:auto;` instead of `font-family: Arial, "Helvetica Neue", Helvetica, sans-serif;`

- `ff:t` expands into `font-family:t;`instead of `font-family: "Times New Roman", Times, Baskerville, Georgia, serif;`

- `ff:v` expands into `font-family: v;` instead of `font-family: Verdana, Geneva, sans-serif;`

The above shortcuts work perfectly in sublime text :)

**Comment by ramya-rao-a** [comment]
VS Code uses [the newer modular Emmet libraries ](https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0) where these snippets are not supported.

The [snippet library](https://github.com/emmetio/snippets/blob/master/css.json) doesnt have entries for font families that can support the above.

@sergeche Your thoughts on this?

**Comment by sergeche** [comment]
These snippets are missing, you can PR them to [CSS snippets](https://github.com/emmetio/snippets/blob/master/css.json)

**Comment by ely-alamillo** [comment]
I can go ahead and give this a shot. I would only need to add the suggested snippets to [CSS snippets](https://github.com/emmetio/snippets/blob/master/css.json) file ?

**Comment by sergeche** [comment]
Yes. Note that `:` isn’t allowed in snippet names anymore, it’s used to explicitly separate property name and property value. Thus, you should either add pipe-separated values to `ff` snippet so they will be picked by automatic snippet resolved for passed property name (e.g. in `ff:a` abbreviation `a` is property value, which can be matched with `Arial, "Helvetica Neue", Helvetica, sans-serif` value). Or create new snippets without `:` in name.

**Comment by ely-alamillo** [comment]
Got it, just to make sure I understood correctly for a snippet like `ff:a` since the `:` are no longer allowed I can add `Arial, "Helvetica Neue", Helvetica, sans-serif` as value to the `ff` property.

**Comment by sergeche** [comment]
Exactly. It’s a good idea to add it as a custom snippet into VS Code and ensure everything works as expected

**Comment by sergeche** [comment]
Published as `@emmetio/snippets@0.2.10`

**Comment by ramya-rao-a** [comment]
Thanks @ely-alamillo and @sergeche 
I'll include the changes in VS Code in the next week or so.

**Comment by mjbvz** [comment]
I'm still seeing `ff:a` expand to `font-family: auto;` in c86cab2211d6dce686e5c89934d915b1e020ba9e

![screen shot 2018-08-02 at 5 41 47 pm](https://user-images.githubusercontent.com/12821956/43594824-7bdcf9c0-967b-11e8-8e22-e97ffa5bb1b8.png)

**Comment by skmcgowan** [comment]
Try 'ffa'

![image](https://user-images.githubusercontent.com/29570739/43595286-307eefee-9674-11e8-8a24-c8f2982e1715.png)

**Comment by ely-alamillo** [comment]
@mjbvz, @sergeche  mentioned that `:` are not allowed in snipped names anymore so `ff:a` does not work. To get that snippet to work you should use `ffa` instead.

**Comment by mjbvz** [comment]
Yep looks good without the `:`
