### ISSUE TITLE
Search for docker gives language packs in the result

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode#52362]
Search for "docker" in the extensions view search box
You will see language packs show up that have nothing to do with "docker"

![image](https://user-images.githubusercontent.com/16890566/41626607-abb96880-73d1-11e8-8d71-bb21b33aa7f0.png)

**Comment by kesane-msft** [comment]
@ramya-rao-a / @auchenberg this issue is now fixed. Could you verify and close the issue?
