### ISSUE TITLE
Multiple cursors do not insert generated snippet at all cursors

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5236]
- VSCode Version: 1.0.0-alpha
- OS Version: Windows 10

Steps to Reproduce:
1. Add a cursor above your current one
2. Add a code snippet (for, do, etc)

Actual:
Snippet will only be generated at the original cursor location.

![multiplecursorsnippet](https://cloud.githubusercontent.com/assets/12900364/14512729/7fdae1da-0196-11e6-84b9-76a43c9190c1.gif)

**Comment by shaneparsons** [comment]
Along the lines of this, when doing the same thing but choosing a reference (i.e. variable) rather than a snippet, everything in between the first and last cursor gets highlighted after completion, making the next thing you type overwrite all the lines in between.

**Comment by alexandrudima** [comment]
@jrieken I think you've implemented this

**Comment by jrieken** [comment]
Yeah, I have implemented this in #16037
