### ISSUE TITLE
showInputBox: value option is selecting text by default resulting in deleted content

### ISSUE THREAD

**Issue by jamarw** [Microsoft/vscode#52365]
- VSCode Version: 1.24.1, Insiders: 1.25.0-insider
- OS Version: Windows 10 1803

**Steps to Reproduce**:
Sample code
    let disposable = vscode.commands.registerCommand("extension.sayHello", () => {
        vscode.window.showInputBox({
            value: "https://",
        });
    });

1. Run the code above sample

**Result**
Input box opens and **https://** is selected automatically.  If a user begins to type it will delete the placeholder value.  This is similar to an old resolved [issue](https://github.com/Microsoft/vscode/issues/28213).

Does this issue occur when all extensions are disabled?: Yes

Thanks and please let me know if you need any additional information.

**Comment by chrmarti** [comment]
You could use the `valueSelection` option to set the cursor to the end of the initial value.

**Comment by jamarw** [comment]
@chrmarti , thanks for the suggestion.

**Comment by chrmarti** [comment]
Reverting to the old behavior. This wasn't an intentional change.

**Comment by chrmarti** [comment]
Actually, the documentation was always that `When `undefined` the whole word will be selected ...`. I'll revert this change back to what is documented with #52906.
