### ISSUE TITLE
When I stage a selected range, VSCode commits the entire file (staged AND unstaged parts)

### ISSUE THREAD

**Issue by ggregoire** [Microsoft/vscode#52367]
- VSCode Version: 1.24.1
- OS Version: macOS high sierra

Steps to Reproduce:

1. Go in Source Control
2. Select a file to display the diff
3. Select a line of diff
4. cmd+shift+P > Git: Stage Selected Ranges
5. Commit with the icon (or cmd+shift+P > Git: Commit Staged, same bug)

Then the entire file is commited.

Here a screenshot where we see a file with a staged line and the other part not staged:

<img width="218" alt="screen shot 2018-06-19 at 5 50 10 pm" src="https://user-images.githubusercontent.com/591804/41628354-c1cfb9ea-73e9-11e8-8d17-d10a130f8d40.png">

Then when I commit, VSCode commits both part, staged and unstaged.

**Comment by sarahwbs** [comment]
I am also having this problem. I'm happy to provide more details. How much of the git log do you want to see?

**Comment by joaomoreno** [comment]
If you have a reproducible case, make sure to send post the exact two files (old version and new version) and tell me which chunk you're trying to stage.
