### ISSUE TITLE
 integrated terminal flash back

### ISSUE THREAD

**Issue by luckhpy** [Microsoft/vscode#52379]
Issue Type: <b>Bug</b>

the integrated terminal quick flash back when i open it , and my computer is mac os

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 4|
|Memory (System)|8.00GB (1.47GB free)|
|Process Argv|/Users/pengxin/Downloads/Visual Studio Code 2.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
mithril-emmet|Fal|0.7.1
beautify|Hoo|1.3.2
vscode-language-pack-zh-hans|MS-|1.24.3
vetur|oct|0.12.5
sass-indented|rob|1.4.9
language-stylus|sys|1.9.2

</details>

**Comment by Tyriar** [comment]
Can you elaborate what you mean by "integrated terminal quick flash back"?
