### ISSUE TITLE
Insiders closed with crash. When opened - Untitled files are duplicated in separate window

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#52371]
- VSCode Version: 1.25.0-ins
- OS Version: win7x64

I've just got an update to version:

```
Version: 1.25.0-insider
Commit: b4a18da6e78f95295ea6538f5ae8dd0c9f0869a9
Date: 2018-06-19T07:49:07.900Z
Electron: 2.0.2
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

And at the same time, 10 minutes before update, I've set a setting "`files.hotExit`" to "`onExitAndWindowClose`" in the **_Settings_**

So, I don't know what exactly caused this crash, update or this setting.

And then the strange thing happened after launch - all my 8 Untitled files were duplicated to separate window with **_Plain text_** language mode in all of them. (I've had different: css, js, xml, etc.)
_Talking about workspace - it's been saved before all these actions._

img:
![image](https://user-images.githubusercontent.com/24613274/41631150-c009629e-743b-11e8-9ebd-80168568d527.png)

console message:
![image](https://user-images.githubusercontent.com/24613274/41631273-64bf6090-743c-11e8-8919-4d81f7948b11.png)
`INFO no standard startup: not just one window   ---   log.ts:159`

----------------------

`AppData\Roaming\Code - Insiders\logs`:

[logs.zip](https://github.com/Microsoft/vscode/files/2117362/logs.zip)

**Comment by Tyriar** [comment]
This is odd, I haven't seen it before. I notice you have the following:

- You're in a multi-root workspace
- You're on Windows 7
- You're running as admin

I tried to repro and failed using a multi-root workspace on macOS as I'm away from my Windows machine atm. @user3323 does this repro consistently when you crash the window via task manager? Also does running VS Code _not_ as admin fix it?

**Comment by user3323** [comment]
@Tyriar  hi there.

I'm not quite sure what do you mean by "multi-root" workspace.
Do I use files from different folders in my workspace? Yes.
Windows 7 x64

I don't know how to force launch app without Administrator mode. They all run with it. Do you have an advice?

And I've crashed VS Code on purpose via task manager.... and it really strange. First crash (after your comment) - it DID repro, then 4 more force crashes - and it did NOT repro. Really strange behavior.

**Comment by Tyriar** [comment]
> I'm not quite sure what do you mean by "multi-root" workspace.
> Do I use files from different folders in my workspace? Yes.

That's what I mean, by root I mean root folder.

> I don't know how to force launch app without Administrator mode. They all run with it. Do you have an advice?

Windows 7 shouldn't do that...? ctrl+shift+enter or right click is needed to force admin mode doesn't it 😕

**Comment by user3323** [comment]
@Tyriar 

> right click is needed to force admin mode

are we talking about forcing admin mode or forcing NON admin mode?

you asked me:

`Also does running VS Code not as admin fix it?`

so, **_not as admin_**, means NON admin mode right?
and I answered, that I don't know how to force launch VSCode with NON admin mode

**Comment by Tyriar** [comment]
Normally Windows will run nothing as administrator, you need to right click the application and select `Run as Administrator` in the context menu. That's what's confusing me.

**Comment by user3323** [comment]
@chrmarti  @Tyriar  hey, it's happened again. But now - behavior even MORE strange.

I had all my Untitled files in workspace, named "WSPACE 1".
I closed it.
Then, drag and drop'ed folder into VS Code, and saved this new workspace, as "WSPACE 2".
Closed VS Code.
Start VS Code..... and I'm getting my WSPACE 2 opened, with ..... those 8 Untitled files from WSPACE 1.

Console log error:
`INFO  no standard startup: not just one window   /C:/Program Files/VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1375`

Any thoughts?
