### ISSUE TITLE
double-clicking the title bar window is not adaptive

### ISSUE THREAD

**Issue by beroft** [Microsoft/vscode#52376]
Issue Type: <b>Bug</b>

Today, I turned on the editor and found this problem, which had not been a problem before.

VS Code version: Code - Insiders 1.25.0-insider (b4a18da6e78f95295ea6538f5ae8dd0c9f0869a9, 2018-06-19T07:38:09.923Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.56GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|29%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
code-settings-sync|Sha|2.9.2
project-manager|ale|0.25.2
bracket-pair-colorizer|Coe|1.0.58
vscode-eslint|dba|1.4.12
xml|Dot|2.3.1
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.32
php-debug|fel|1.12.3
php-intellisense|fel|2.3.3
php-pack|fel|1.0.1
auto-close-tag|for|0.5.6
vscode-phpfmt|kok|1.0.30
Angular-BeastCode|Mik|6.0.17
vscode-language-pack-zh-hans|MS-|1.24.3
sublime-keybindings|ms-|4.0.0
php-docblocker|nei|1.6.0
material-icon-theme|PKi|3.5.0
copy-copy-paste|roc|0.0.5
html-css-class-completion|Zig|1.17.1

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
@sbatten looks like a regression from the title work, double clicking on the title should maximize the window (macOS).
