### ISSUE TITLE
Outline can't recognize function with (char *interface) paramater.

### ISSUE THREAD

**Issue by BSCCO** [Microsoft/vscode#52377]
- VSCode Version: 1.24.1
- OS Version: Linux Mint 18.3 Cinnamon 64-bit, kernel 4.13.0-43-generic

Steps to Reproduce:

1.Define a function with  (char *interface) paramater, and the outline can't recognize it correctly.
![2018-06-20 10-56-43](https://user-images.githubusercontent.com/11715329/41635179-eb7a2a42-7479-11e8-88b9-7d5c80eabc8a.png)
2.If I change the variable name, it can recognize it.
![2018-06-20 10-57-11](https://user-images.githubusercontent.com/11715329/41635195-0b32a576-747a-11e8-9fa9-15f469d15554.png)

Does this issue occur when all extensions are disabled?: 
Can't open outline in this situation.

**Comment by chrmarti** [comment]
This issue was moved to Microsoft/vscode-cpptools#2159
