### ISSUE TITLE
calling stack not showing when Chinese characters in module file path name

### ISSUE THREAD

**Issue by farnking** [Microsoft/vscode#52374]
Issue Type: <b>Bug</b>

I have some users who save my python program in a folder with name in Chinese character.  
Then vscode started saying that she could not find the modules in the calling stack.  
The breakpoints still work.  
But then VSCode did not show the program lines at which the breakpoints stopped. 

If I removed the chinese characters from the module path, the problem disappeared. 

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (10.37GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-language-pack-zh-hant|MS-|1.24.3
python|ms-|2018.5.0
cpptools|ms-|0.17.4

</details>

因為必要資料太大，我們已為您將其寫入您的剪貼簿。請貼上。

**Comment by weinand** [comment]
Please file this issue against the Python extension.
