### ISSUE TITLE
自动补全（智能提示）打开软件后的一段时间就会失效的问题

### ISSUE THREAD

**Issue by felix9ia** [Microsoft/vscode#52380]
- VSCode Version:1.23.1
- OS Version: windows 10

我的vscode在插件全部禁用的状态下，自动补全（智能提示）在打开软件后一段时间就会失效。我的工作主要是使用Node开发。不知道该如何解决，想请教一下。如果没办法解决，我只能去用Atom了

Does this issue occur when all extensions are disabled?: Yes

**Comment by felix9ia** [comment]
@rebornix @chrmarti 是我提isssue使用了中文的原因吗？我的英语很烂，所以才觉得使用中文，然后你们可以通过翻译器来看我的issue。请问，这个智能提示丢失的问题不存在嘛？我现在依然存在这样的问题啊。

**Comment by felix9ia** [comment]
resolved!

**Comment by zhaocongdong** [comment]
@felix9ia 你是怎么搞定的,我的自动补全功能也总是失效,重启vscode就可以了.但是每天要重启好几次.

**Comment by felix9ia** [comment]
我是Vue和React交叉开发，
我尝试过把所有的插件都禁用了，但是不管用。
最后，
1.我把Vue和React容易冲突的插件卸载了，
2.把setting.json里面有关于Vue和React可能造成冲突的配置禁用了。

找一找可能冲突的地方吧，祝你好运。

**Comment by zhaocongdong** [comment]
@felix9ia 好的,多谢.
