### ISSUE TITLE
[Accessibility][Usability]A11y_VSCode_ActivityBar_Screenreader: Jaws is reading actionable control as readonly button.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#52388]
**Environment Details:**
VSCode Version : 1.24.0
OS Version : Win10

**Additional Details:**
Screenreader,JAWS[18.0.5038],Usability

**Repro Steps:**
1. Launch VS Code while JAWS is ON.
2.Navigate to "Activity Bar" at left side of the screen after login.
3.Navigate to "SettingsButton".
4.Observed that jaws is reading actionable control as read only button.

**Actual:**
Here, jaws is reading actionable control "Setting" as read only button.

**Expected:**
Readonly is come for the noneditable text/control here "Setting" is the actionable control so jaws should not read it as read only button.

**Recommendations:**
Refer below link which is repository of bug fixes code snippets.
https://microsoft.sharepoint.com/teams/msenable/mas/Pages/browse-fixes.aspx

**User Impact:**
If jaws read it as read only then user will not know that it is nothing but the actionable control.

**Attachment For Reference:**
[[Accessibility][Usability]A11y_VSCode_ActivityBar_Screenreader.pptx](https://github.com/Microsoft/vscode/files/2118011/Accessibility.Usability.A11y_VSCode_ActivityBar_Screenreader.pptx)

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
It reads properly on NVDA not sure if we support jaws

**Comment by auchenberg** [comment]
Closing this issue as it's only observed in JAWS, and this isn't strictly needed to meet MAS C compliance.

**Comment by AccessibilityTestingTeam-TCS** [comment]
We did execution on both NVDA and Jaws too so this issue is observed in jaws.If nvda is reading it correctly then jaws should read it correctly.
