### ISSUE TITLE
Preview for a markdown file doesn't follow the font setting

### ISSUE THREAD

**Issue by showerying** [Microsoft/vscode#52387]
- VSCode Version: 1.24.1
- OS Version: Windows 10 Home Edition

Steps to Reproduce:

1. Open a markdown file.
2. Click the preview button.

Does this issue occur when all extensions are disabled?: Yes

I've set a specific font with "editor.fontFamily": "等距更纱黑体 SC", but the preview shows in OS default font.

![image](https://user-images.githubusercontent.com/6418433/41639649-3eac48be-7491-11e8-8459-db2c4b3006fe.png)

**Comment by neilsustc** [comment]
`editor.fontFamily` only controls the "editor font".
You need to change the `markdown.preview.fontFamily` setting.

**Comment by showerying** [comment]
@neilsustc Thanks.
