### ISSUE TITLE
No shortcut to jump directly to the error message from the editor.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#52391]
Environment Details:
VSCode Version : 1.23.1
OS Version : Win10
MAC OS Version: HighSierra10.13.5 

Repro Steps:
1. Launch VS Code
2.Open any code in the editor which has errors.
3. Go to View menu and Select Problems.
4. Press enter on any error, focus will jump to the line where error is found.

Actual:
 No any shortcut provided to jump directly to the error message from the editor after resolving any error.
If we use ctrl+shift+m to jump to the problems tab, treeview gets closed. To open that treeview, we again have to use that ctrl+shift+m command.

Expected:
There should be any keyboard shortcut to jump directly to the next error message when user has resolved his previous error.

Recommendations:
Refer below link which is repository of bug fixes code snippets:
https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx

User Impact:
User will have to press two times ctrl+shift+m command to go back to problems pane and visually impaired people might not get the scenario that if the problems tab is open and he switches to the editor and again if he wants to switch to problems tab and if he press ctrl+shift+m , that problems tab will close.

Attachment for reference:

[A11y VSCode Problems NVDA No shortcut to directly switch to editor..pptx](https://github.com/Microsoft/vscode/files/2118036/A11y.VSCode.Problems.NVDA.No.shortcut.to.directly.switch.to.editor.pptx)

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
All our View panels and viewlets commands toggle the views. To go back to the problems view there is another command `View: Focus Problems` command.

Please let us know this is sufficient ?

**Comment by AccessibilityTestingTeam-TCS** [comment]
Yes, F8 is covering one of the issue. Through F8 user can move to the next error. Suppose, user wants to check the errors of another file while he is in Editor,keeping the problems tab open. So, once he will press the command to switch to the tab, it will close because it is already open(toggle functionality). So, at this time screenreader should announce some information that whether tab is open or close when user switches between Editor and tabs.

**Comment by isidorn** [comment]
I have no clue what the last comment means, leaving to @sandy081 to digest
