### ISSUE TITLE
Replace with selection problems

### ISSUE THREAD

**Issue by crushglass** [Microsoft/vscode#5239]
- VSCode Version: 0.10.11
- OS Version: Win7

Steps to Reproduce:
1. Could not replace with selection in a line.
2. replace with selection mode get wrong result, vs code would replace all match items in docment

![bug](https://cloud.githubusercontent.com/assets/10541127/14515513/63c7f180-022d-11e6-817e-7fa60e3c4049.png)

**Comment by alexandrudima** [comment]
The search in selection feature is indeed currently limited to a selection that contains at least one full line.

**Comment by BillDenton** [comment]
I've just found this problem when trying to do a replace in a selection of less than a line. After reading this I got around it by selecting multiple lines. To the user (i.e. me), this looks more like a bug than a feature request. Has this been placed on milestone?

**Comment by alexandrudima** [comment]
Fixed via #15566

**Comment by BillDenton** [comment]
Verified fixed in 1.10.1
