### ISSUE TITLE
Easier method to customise colours

### ISSUE THREAD

**Issue by hsdk123** [Microsoft/vscode#524]
It's currently very difficult for a newcomer to visual studio code to customise the colours of the editor (and explorer, etc.) It would be nice if Code could have a way manually helping users select their colours for various parts of the editor. 

For example, I'd like my explorer white, whereas my editor dark - this is very difficult to simply get.

**Comment by Tyriar** [comment]
Closing in favor of https://github.com/Microsoft/vscode/issues/76
