### ISSUE TITLE
[Accessibility][Usability]A11y_VSCode_StatusBar_Keyboard: The tool tip is not appeared on avtivity bar button list

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#52408]
**Environment Details:**
VSCode Version : 1.24.0
OS Version : Win10

**Additional Details:**
Keyboard,Usability

**Repro Steps:**
1.Navigate to "Status Bar" at bottom of the screen after login.
2.Try to navigate "Status Bar" through the keyboard key such as "TAB".
3.Observed that tooltip is not appeared. 

**Actual:**
Tooltip get appeared only on the mouseover.

**Expected:**
On keyboard focus tooltip should appeared.

**Recommendations:**
Refer below link which is repository of bug fixes code snippets.
[https://microsoft.sharepoint.com/teams/msenable/mas/Pages/browse-fixes.aspx](url)

**User Impact:**
Keyboard only user will not unserstand the extra information which is provided by the tooltip.

**Attachment For Reference:**
[[Accessibility][Usability]A11y_VSCode_StatusBar_Keyboard.pptx](https://github.com/Microsoft/vscode/files/2118280/Accessibility.Usability.A11y_VSCode_StatusBar_Keyboard.pptx)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
We decided to not make the status bar navigatable to not have too many "tabbable" locations for the users. All actions in the status bar are accessible via the global command palette.
