### ISSUE TITLE
[Accessibility][Usability]A11y_VSCode_ActivityBar_Keyboard: The tool tip is not appeared on avtivity bar button list

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#52406]
**Environment Details:**
VSCode Version : 1.24.0
OS Version : Win10

**Additional Details:**
Keyboard,Usability

**Repro Steps:**
1.Navigate to "Activity Bar" at left side of the screen after login.
2.Navigate to any item such as "Explorer,Search,SourceControl,Debug,Extensions,Setting" buttons.
3.Observed that keyboard focus is going on the button list but the tooltip is not appeared. 

**Actual:**
Keyboard focus goes on the button list but tooltip is not appeared on it.

**Expected:**
if the button have tooltip then after keyboard focus tooltip should appeared on it.

**Recommendations:**
Refer below link which is repository of bug fixes code snippets.
https://microsoft.sharepoint.com/teams/msenable/mas/Pages/browse-fixes.aspx

**User Impact:**
Keyboard only user will not unserstand the extra information which is provided by the tooltip.

**Attachment For Reference:**
[[Accessibility][Usability]A11y_VSCode_ActivityBar_Keyboard.pptx](https://github.com/Microsoft/vscode/files/2118264/Accessibility.Usability.A11y_VSCode_ActivityBar_Keyboard.pptx)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@AccessibilityTestingTeam-TCS to clarify you mean that the tooltip should visually appear on each button/action/toolitem that gets keyboard focus?

**Comment by AccessibilityTestingTeam-TCS** [comment]
Here,the issue is only by mouse over the tool tip get appeared.But if keyboard only user wants to see or know the extra information which is provided in tooltip then user will not get it.So without mouse over only by the keyboard focus tooltip should appeared.
