### ISSUE TITLE
Displays visible trailing whitespaces on sidebar's folder name

### ISSUE THREAD

**Issue by rwu823** [Microsoft/vscode#52417]
![image](https://user-images.githubusercontent.com/890063/41647757-b80e1f3a-74a9-11e8-9ae8-6b5a1eed5cc7.png)

Currently you can create a folder with any trailing whitespaces they are difficult to find and make confuse.

Could it be?

1. Displays visible trailing whitespaces
2. Avoid trailing whitespaces in vscode

Reproduce environment:
OS: macOS `10.13.3`
VSCode version: `1.24.1`

**Comment by TomSputz** [comment]
How to reproduce? Is this only an issue on linux/mac? Because afaik windows does now allow trailing whitespace on file names

**Comment by rwu823** [comment]
@TomSputz I'm in macOS environment

**Comment by isidorn** [comment]
In vscode insiders we show a warning to avoid adding trailing whitespace. Please try it out and if you are not happy with the solutino let us know and we can reopen
