### ISSUE TITLE
Indentation incorrect when moving blocks in HTML

### ISSUE THREAD

**Issue by taalas** [Microsoft/vscode#52415]
- VSCode Version: 1.24.1
- OS Version: Windows 10 Pro (1803)

Steps to Reproduce:

1. Select a block of HTML code
2. Move selected block using ALT-DownArrow and ALT-UpArrow

![2018-06-20_10-29-00](https://user-images.githubusercontent.com/6582821/41646864-2372a852-7475-11e8-9628-d9c9dd302a3a.gif)

This could be related to HTML not indenting correctly when pasting with `editor.autoIndent=on`

**Comment by rebornix** [comment]
Let's track this issue in https://github.com/Microsoft/vscode/issues/48993 and thanks for your feedback!
