### ISSUE TITLE
Failed updating to v1.24.1

### ISSUE THREAD

**Issue by matiusmonkey** [Microsoft/vscode#52416]
First issue I've had (loving vs code by the way - keep up the good work!)

Just had a popup mid update, asking to attach the following to a new issue on here:

[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2118478/vscode-inno-updater.log)

Cheers,

Mat

**Comment by block13** [comment]
same here...log attached...
Current Version:
Version 1.24.0
Commit 6a6e02cef0f2122ee1469765b704faf5d0e0d859
Date 2018-06-06T17:35:40.560Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2120828/vscode-inno-updater.log)

**Comment by joaomoreno** [comment]
You seem to have #47841.

Please read this comment if you can provide more detail: https://github.com/Microsoft/vscode/issues/47841#issuecomment-393101777

Please read this one to disable background updates: https://github.com/Microsoft/vscode/issues/47841#issuecomment-395017687
