### ISSUE TITLE
Python Highlighting is oddly off

### ISSUE THREAD

**Issue by Redoubts** [Microsoft/vscode#5241]
I tried to install a Twilight like theme from Sublime Text, and some of the colors aren't porting over properly. Here's an example showing how the Class name, inherited Class, and keys in a dict literal aren't matching how the theme looks in Sublime Text 3. VS Code on left, ST3 on right. These wrong colors aren't even part of the palette in the theme, so I don't know where they're coming from.

<img width="1400" alt="screen shot 2016-04-13 at 9 13 13 pm" src="https://cloud.githubusercontent.com/assets/2435101/14517024/f0a3da8a-01bd-11e6-8edd-e0f62ac2d97b.png">

- VSCode Version: 0.10.11
- OS Version: 10.11

Steps to Reproduce:

1.  Install Twilight theme https://gist.github.com/Redoubts/f37f3a267a3ee05b3b4599444806b81e
2. Observe odd coloration

**Comment by aeschli** [comment]
What you see is that colors of the default theme are shining through (in the case the turquise for the definition).
I fixed this for 1.0.
