### ISSUE TITLE
Mac non admin user does not have permission to change .vscode folder

### ISSUE THREAD

**Issue by Innovative-Ideas** [Microsoft/vscode#5242]
- VSCode Version: 0.10.11
- OS Version: OS X 10.11.4

Steps to Reproduce:

0. (May be necessary to Install Unity, Unity Sample Project, and Unity VS Code plugin)
1. (I first debugged Unity successfully in VS Code with a user that has admin privileges)
2. Log into OS X with a User that does not have admin privileges. 
3. Start VS Code. <br>
Following the steps for Unity Debugging Support listed here: https://marketplace.visualstudio.com/items?itemName=Unity.unity-debug
4. Delete .vscode/Launch.json file
5. Try to recreate Launch.json file from inside VS Code by selecting "Unity Debugger"

Result:
Unable to create 'launch.json' file inside the '.vscode' folder (Error: EACCES: permission denied, open '/Users/Shared/Unity/Standard Assets Example Project/.vscode/launch.json').

Desired Result:
File will be created successfully.

Reason:
The .vscode folder's permissions for a non admin user is "Read only".  The folder permissions need to be "Read & Write"

Current Workaround:
In OS X Finder, manually change the access permissions of the .vscode folder to "Read & Write"

**Comment by bpasero** [comment]
@Innovative-Ideas looks like you started VS Code as root once maybe and created the settings?
