### ISSUE TITLE
工作区扩展名 Work Space Extension Name

### ISSUE THREAD

**Issue by Ainto** [Microsoft/vscode#52425]
Issue Type: <b>Feature Request</b>

现在的工作区扩展名是code-workspace
这样并不美观,太长了,能否使用简短的扩展名

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 6.1.7601

**Comment by chrmarti** [comment]
"The current workspace extension is code-workspace
This is not beautiful, too long, can use a short extension"

**Comment by bpasero** [comment]
No plans to change that.
