### ISSUE TITLE
[Accessibility]A11y_VSCode_CommandPalette_Keyboard:Keyboard focus does not go to "Other Commands" and "Recently Viewed" controls.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#52426]
**Environment Details:**
VSCode Version : 1.24.0
OS Version : Win10
**Additional Details:**
Keyboard,MAS2.1.1,NVDA2018.2.1
Repro Steps:
1.Navigate to Settings icon in Activity Bar->Press Enter->Select "Command Palette" from dropdown.
2.Enter ">" sign to reflect all list of expanded "Command Palette" option.
3.Navigate to the  "Other Commands" or  "Recently Viewed" using keyboard.
**Actual:**
Keyboard focus does not go to "More Commands" and "Recently Viewed" controls.
NVDA is also not reading "More Commands" and "Recently Viewed" controls

**Expected:**
Keyboard focus should go to "More Commands" and "Recently Viewed" controls.
NVDA should read "More Commands" and "Recently Viewed" controls.
**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
https://microsoft.sharepoint.com/teams/msenable/mas/Pages/browse-fixes.aspx
User Impact:
User is not able to  use the contols.
MAS Reference:
MAS2.1.1: https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={8492c4eb-c179-40ae-8777-cd044ed725a2}
**Attachment For Reference:**
[CommandPallete.pptx](https://github.com/Microsoft/vscode/files/2118685/CommandPallete.pptx)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/51850
