### ISSUE TITLE
having a "debug.hideActionBar" settings hides the debug toolbar always

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#52438]
VS Code Insiders:

- add a "debug.hideActionBar": "false" to your settings
- F5

Observe: no floating debug toolbar

- comment out "debug.hideActionBar"
- F5

Observe: floating debug toolbar appears

**Comment by isidorn** [comment]
Since in the last milestone we have deprecated this settings (and announced that in the release notes)
I have decided for this milestone to fully stop supporting it
