### ISSUE TITLE
let and var highlights in a word

### ISSUE THREAD

**Issue by nfdevil** [Microsoft/vscode#5244]
- VSCode Version: 0.10.11
- OS Version: Windows 8.1 Enterprise

Steps to Reproduce:

1. Create a new file and set the syntax to Javascript or TypeScript
2. Type letters or variable

![image](https://cloud.githubusercontent.com/assets/7434048/14520959/5d71b70e-0227-11e6-9359-aa5bb77f740d.png)

**Comment by egamma** [comment]
Duplicate of #4620
