### ISSUE TITLE
[Accessibility]A11y_VSCode_StatusBar_ScreenReader:Jaws reads warning as 0Links. 

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#52446]
**Environment Details:**
VSCode Version : 1.24.0
OS Version : Win10
**Additional Details:**
ScreenReader,Jaws18.0.5038,MAS1.3.1
Repro Steps:
1.Navigate to "Status Bar" at bottom of the screen after login.
2.Navigate to the Warnings at bottom of page 
**Actual:**
 jaws reads warning as 0Links. 
**Expected:**
Jaws should not read warning as 0Links.
**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
https://microsoft.sharepoint.com/teams/msenable/mas/Pages/browse-fixes.aspx
**User Impact:**
User will get confused on which key the proper action will performed
**MAS Reference:**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}
**Attachment For Reference:**
[usabilitylink0.pptx](https://github.com/Microsoft/vscode/files/2123500/usabilitylink0.pptx)

Does this issue occur when all extensions are disabled?: Yes

**Comment by auchenberg** [comment]
Closing this issue as it's only observed in JAWS, and this isn't strictly needed to meet MAS C compliance.
