### ISSUE TITLE
VSCode opens my browser every time I launch it

### ISSUE THREAD

**Issue by bamarni** [Microsoft/vscode#52458]
![peek 2018-06-20 13-10](https://user-images.githubusercontent.com/1205386/41655064-df6b2942-748b-11e8-8444-8850161de84c.gif)

- VSCode Version: 1.24.0
- OS Version: Ubuntu 18.04 LTS

Steps to Reproduce:

1. Open VSCode

Does this issue occur when all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
This should only show on first startup. The fact that it was shown should be recorded in local storage which resides in the user's home folder. What are the timestamps of the files in your `~/.config/Code\ -\ Insiders/Local\ Storage/`?

**Comment by bamarni** [comment]
I don't see the `Insiders` folder, but assuming you're talking about this one :
```
la ~/.config/Code/Local\ Storage/                
total 256K
-rw-r--r-- 1 bamarni bamarni 256K Sep 11  2017 file__0.localstorage
-rw-r--r-- 1 bamarni bamarni    0 Sep 11  2017 file__0.localstorage-journal
```

**Comment by chrmarti** [comment]
Yes, are you running VS Code with the user `bamarni`? These timestamps should update when you use VS Code. What happens when you move that `Code` folder to `Code.bak`?

**Comment by bamarni** [comment]
Yes I'm running VSCode as bamarni, when I move `Code` to `Code.bak` it then only opens the browser on first boot, but I then loose all my settings. I've never messed with this directory manually and used the official Ubuntu deb installer so I think there were a bug at some point. Isn't there some logs I can look at?

**Comment by bamarni** [comment]
Thanks @Tyriar , I've deleted this folder and it doesn't happen again, not sure if / how it got corrupted. I have a backup of it so let me know if I should send it to you.

Otherwise I've opened #52783, which is also quite annoying :confused:

**Comment by Tyriar** [comment]
@bamarni I don't think we'll be able to do much with the folder, it's probably some obscure Chromium bug you hit.
