### ISSUE TITLE
Extensions: sort actions should read out what action it performed

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#52452]
**Environment Details:**
VSCode Version : 1.24.0
OS Version : Win10
**Additional Details:**
Screenreader,NVDA[2018.2],JAWS[18.0.5038],MAS1.3.1
**Repro Steps:**
Launch VS Code while NVDA is ON.
Navigate to Settings icon in Activity Bar->Press Enter->Select "Keyboard Shortcuts" from dropdown.
3.Navigate to "Sort by precedence" button which is located inside the "Search keybindings" edit text field.
**Actual:**
NVDA  is not reading any action performed by the "Sort by Precedence" button.
Same issue is observed in jaws
**Expected:**
NVDA should read actions performed on the page by the "Sort by Precedence" button.
**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
https://microsoft.sharepoint.com/teams/msenable/mas/Pages/browse-fixes.aspx
**User Impact:**
User will get confused about actions performed on the page.
**MAS Reference:**
MAS1.3.1: https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}
**Attachment For Reference:**
[KeyBoardShorcutsScreenReader.pptx](https://github.com/Microsoft/vscode/files/2118965/KeyBoardShorcutsScreenReader.pptx)
Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Once the sort action is exectued a simple aria alert should do the trick -> assigning to July

**Comment by RMacfarlane** [comment]
Reopening because there is a typo in the label

precendence -> precedence
