### ISSUE TITLE
'switch' not highlighted in JS file.

### ISSUE THREAD

**Issue by ThePenguin123** [Microsoft/vscode#5245]
- VSCode Version: 0.10.11
- OS Version: OS X 10.11

Steps to Reproduce:

1. 'switch' keyword is not highlighted by JavaScript syntax highlighter.

**Comment by aeschli** [comment]
I looks like this is fixed now in 1.0
![image](https://cloud.githubusercontent.com/assets/6461412/14690287/bbac73e4-074b-11e6-8a1b-29b516aac2ea.png)
