### ISSUE TITLE
Missing menu entries in SCM menu when using custom menus

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#52455]
This is the SCM menu using native menus
![image](https://user-images.githubusercontent.com/172399/41654538-0cd0d514-748a-11e8-991a-622f380a5f6c.png)

This is the SCM menu with custom menus
![image](https://user-images.githubusercontent.com/172399/41654603-3e69ff74-748a-11e8-9802-d44a7b14472f.png)

Notice that the menu group after 'Undo Last Commit' is empty

**Comment by bpasero** [comment]
Fixed via https://github.com/Microsoft/vscode/commit/b09094ea9e7946cdf236aa5fa4c0d6833e47de24
