### ISSUE TITLE
Custom fonts in integrated terminal window.

### ISSUE THREAD

**Issue by dylanvdmerwe** [Microsoft/vscode#52461]
- VSCode Version: 1.24.1
- OS Version: MacOS 10.13.5

Steps to Reproduce:

1. Setup and configure an iTerm terminal as described [here](https://gist.github.com/ZenLulz/c812f70fc86ebdbb189d9fb82f98197e).
2. Open the terminal in VSCode and you will see font-related issues:

![image](https://user-images.githubusercontent.com/2852839/41655923-b4a0417c-748e-11e8-9726-9e8022f3eaef.png)

3. Set iTerm to be the default shell.

The integrated terminal should in fact look like this as per iTerm:
![image](https://user-images.githubusercontent.com/2852839/41655978-d8e3bf50-748e-11e8-9640-42c0ea86bf06.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This should work, it uses a different name for the font though. You should be able to find the answer by searching for "vscode terminal powerline"
