### ISSUE TITLE
import path is shown on code completion

### ISSUE THREAD

**Issue by LiorRocks** [Microsoft/vscode#52466]
Hi,

I'm getting the following screen after updating vscode to latest version (see attached file).
The prediction dialog is showing the import paths.

This makes working with autocomplete harder.

Thanks,
Lior
![capture](https://user-images.githubusercontent.com/2188993/41657240-62d091d2-749b-11e8-9aa1-663d312c1719.PNG)

**Comment by mjbvz** [comment]
Did you test this in VS Code insiders?

**Comment by tuhinkarmakar** [comment]
I am facing the same issue. I think the issue surfaced after upgrading to 1.24.1.

![screenshot from 2018-06-24 22-23-00](https://user-images.githubusercontent.com/11135104/41821379-34b719a0-77fd-11e8-8582-daae9bc62957.png)

**Comment by LiorRocks** [comment]
Hi @mjbvz ,

It's working fine in insiders version.

Thanks,
Lior

![works on insiders](https://user-images.githubusercontent.com/2188993/41858630-0377b6dc-78a3-11e8-9e84-1dde1c8a4aef.PNG)
