### ISSUE TITLE
Mouse-over icon hides preview occasionally

### ISSUE THREAD

**Issue by daewin** [Microsoft/vscode#5247]
- VSCode Version: 0.10.11
- OS Version: Windows 10.0.10586

Steps to Reproduce:

1. Mouse-over vscode icon of multiple windows (not click)
2. Hover over any window to preview
3. Preview shows and hides almost immediately

**Comment by egamma** [comment]
This is on Windows?

**Comment by daewin** [comment]
Yes. Sorry, I did not mention that. Editing.

**Comment by bpasero** [comment]
@daewin hm I tried to reproduce on my Windows 10 and failed. I wonder if this is a windows issue with your version of Windows. Can you make a video to show?
