### ISSUE TITLE
Turkish characters in PS1 files shows incorrectly

### ISSUE THREAD

**Issue by serkanz** [Microsoft/vscode#52487]
- VSCode Version: 1.24.0
- OS Version: Windows Server 2012 R2

Steps to Reproduce:

1. Create a new .ps1 file in VSCode editor
2. Write the code below to the file and save
$department ="Yönetim"
write-host $department
3. run the ps1 file from powershell command prompt, it prints output 
YÃ¶netim

Does this issue occur when all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
You can save the file in a different encoding. Open the file in VS Code and click 'UTF-8' in the statusbar. Choose to save in a different encoding and pick 'UTF-8 with BOM'.
