### ISSUE TITLE
Feature request: Setting for Git commits message length

### ISSUE THREAD

**Issue by eugenevk** [Microsoft/vscode#52489]
Feature request: more available characters for commenting on Git commits

**Comment by joaomoreno** [comment]
@eugenevk What do you mean?

**Comment by eugenevk** [comment]
@joaomoreno See attached screenshot. I would like to have much more space for my commit comments, to describe in detail what I changed in my source code.
![commit comments](https://user-images.githubusercontent.com/19785727/41718312-df2b1920-755c-11e8-8183-b2fbbbdc5bab.jpg)
