### ISSUE TITLE
Settings editor layout issues

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#52486]
Issue Type: <b>Bug</b>

Pls see attached screenshot. There are several issues that make it hard to visually track the various settings. I use for this description the "Files: Auto Save Delay" setting.

- The distance between the value and the reset link is too large (the issue actually is that the input fields don't have borders and so the only visual indication I have is the actuall settings value.

- The distance between the value 500 and the description text is too large (same border issue).  The distance is visually the same as the one to "Editor: Font Size". So, it hard to tell where I should focus on.

Overall, I don't have the visual impression of 7 rows corresponding to the  settings on the page. I have the impression of  some text rows and some number rows.

![capture](https://user-images.githubusercontent.com/4674940/41666097-85fdc86a-745e-11e8-8d51-2d13f4d76f7f.PNG)

VS Code version: Code - Insiders 1.25.0-insider (e585e4bf008a50e5b1f4fde71cf6d255e25381bf, 2018-06-20T08:08:46.972Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (9.01GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.1.2
solargraph|cas|0.17.4
regex|chr|0.2.0
githistory|don|0.4.1
gitlens|eam|8.4.1
tslint|eg2|1.0.32
vscode-npm-script|eg2|0.3.4
vsc-material-theme|Equ|2.1.0
git-project-manager|fel|1.6.1
mdmath|goe|2.2.1
svgpreview|kis|0.2.0
vscode-azurestorage|ms-|0.3.1
mssql|ms-|1.3.1
python|ms-|2018.5.0
azure-account|ms-|0.4.0
azurecli|ms-|0.4.2
Go|ms-|0.6.83
printcode|nob|2.3.0
vscode-docker|Pet|0.0.27
material-icon-theme|PKi|3.5.0
Ruby|reb|0.18.0
code-settings-sync|Sha|2.9.2
vscode-open-in-github|ziy|1.3.3

(3 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
I added a hack to copy the border from the dropdown and apply it to the checkbox and input box which is a big improvement for many themes. The select box is usually themed better for this background since it appears on the panel.

But theming still needs to be solved for real. Do we add theme colors for every control type or just one set for all controls. Are the background and foreground themeable separately from the editor, if so then the outline also needs to be themeable, etc.

**Comment by roblourens** [comment]
I have #53908 for theming, I think other spacing issues are mitigated or will be by theming.
