### ISSUE TITLE
Source Control tab unusable for several minutes after clicking large untracked file

### ISSUE THREAD

**Issue by jreina** [Microsoft/vscode#52483]
Issue Type: <b>Bug</b>

After clicking a very large untracked JSON file in the source control tab, the source control tab becomes unresponsive. The JSON file shows up in the editor immediately and I am able to navigate around the project without issue, but clicking on other files in the source control tab in an attempt to see a diff or open the file does nothing. After several seconds I right clicked the JSON file and clicked "Discard Changes", which did nothing until several minutes later when the delete file dialog finally showed up as I was working in the project.

I am using git version 2.17.1.windows.2

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.94GB (23.64GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\development\test-record-service|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
vscode-node-readme|ben|3.0.2
bracket-pair-colorizer|Coe|1.0.58
vscode-eslint|dba|1.4.12
prettier-vscode|esb|1.5.0
flow-for-vscode|flo|0.8.1
vscode-mocha-sidebar|mat|0.20.8
dotenv|mik|1.0.1
mssql|ms-|1.3.1
cpptools|ms-|0.17.4
code-settings-sync|Sha|2.9.2
code-spell-checker|str|1.6.10

</details>

**Comment by chrmarti** [comment]
Does this occur with all extensions disabled? (`code --disable-extensions`)

**Comment by jreina** [comment]
My apologies for the delay. I have since been unable to reproduce the issue.

**Comment by chrmarti** [comment]
Thanks. Let us know if you see it again.
