### ISSUE TITLE
Selections in the editor are not treated as X Selection on Linux

### ISSUE THREAD

**Issue by abetkin** [Microsoft/vscode#5248]
- VSCode Version: 0.10.14-insider
- OS Version: Ubuntu x64 4.2.0-35-generic

Steps to Reproduce:

1. Select text in the editor
2. Try to paste in another window using middle mouse button

PS. X selections work normally in the atom editor.

**Comment by Tyriar** [comment]
This is currently disabled by default, you can turn it on by adding this to your `settings.json`:

```json
{
  "editor.selectionClipboard": true
}
```

I believe it is being turned on by default in the April release.

**Comment by abetkin** [comment]
thanks!
