### ISSUE TITLE
Refine debug toolbar

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#52490]
I've tried to compile issues and proposals from #2513 and #9093:

**Today** VS Code supports two locations:
- floating on top of editor tabs (default)
- pinned to debug viewlet header (new option) 

**"floating"** debug toolbar issues:
- floating debug toolbar can only be moved horizontally and its vertical position is not ideal
  - problem: floating debug toolbar hides tabs (but only in tab mode). 
  - workaround: move floating debug toolbar to the left and make debug viewlet wide enough so that toolbar doesn't overlap with tabs.

**"docked"** debug toolbar issues:
- debug actions only available in debug viewlet
  - problem: you cannot use debug buttons when debug viewlet is not active
  - workaround: use F1 or keyboard shortcuts
- no debug configuration drop-down visible while debug session active
  - problem: another concurrent session cannot be easily started while one is active
  - workaround: use F1 or set "debug.showInStatusBar" to "onFirstSessionStart" and start session via quickpick
- no session drop-down visible if debug viewlet is too narrow
  - problem: it is not really obvious that the CALLSTACK view could be used for switching sessions in this situation
  - workaround: make debug viewlet wider

**Proposed Debug Bar locations**:
- in activity bar (https://github.com/Microsoft/vscode/issues/2513#issuecomment-322394219)
- pinned to its own bar directly below the title bar (https://github.com/Microsoft/vscode/issues/2513#issuecomment-316092754)
- like an actual toolbar (not floating) like VS (https://github.com/Microsoft/vscode/issues/2513#issuecomment-331213396)
- in statusbar (https://github.com/Microsoft/vscode/issues/2513#issuecomment-315615609)
- snap it to any edge along the editor view (https://github.com/Microsoft/vscode/issues/2513#issuecomment-315931733)
- below the find box (https://github.com/Microsoft/vscode/issues/9093#issuecomment-289090807)
- under the debug viewlet header (https://github.com/Microsoft/vscode/issues/9093#issuecomment-311826699)
- float in the editor like the search widget (https://github.com/Microsoft/vscode/issues/9093#issuecomment-315570734)
- unanchored free floating (https://github.com/Microsoft/vscode/issues/9093#issuecomment-330707973)
- moves the debugger down into your code area (https://github.com/Microsoft/vscode/issues/2513#issuecomment-375884136)

**Important requirements**: 
  - toolbar always visible (independent from which viewlet is active)
    - "docked" toolbar violates this
  - toolbar should not hide anything
    - "floating" toolbar violates this

**My take**:

The two important requirements could be easily addressed by a global toolbar, but VS Code doesn't provide one. 
Since it is difficult to find a good solution that obeys both requirements, I propose a two-pronged approach:

- improve "floating" toolbar (which will continue to be the default):
  - make it more suitable for editor tabs mode, e.g. by allowing to move it below the tabs, and/or
  - allow for unanchored free floating

- improve "docked" toolbar (which is most likely covered by #49881):
  - don't overlap docked toolbar with viewlet header but create a new view "SESSIONS"
  - show debug actions in the SESSIONs header
  - move the session drop-down into the SESSIONs content
  - as long as there is only a single debug session there is no need to expand the SESSION view and all debug actions are available through in the header anyway

Let's start by improving the "floating" toolbar.

**Comment by weinand** [comment]
In June we have improved the positioning of the "floating" toolbar.

**Comment by pklapperich** [comment]
I'm running `1.24.1` which is currently the latest release. There's still no vertical position of the "floating" toolbar. It covers my filenames or other things I want to read/use. I can't put it anywhere that's out of my way. I'm constantly dragging the thing left and right. I hate it.

Every time I open VSCode I have modify the local style on the "debug-actions-widget" to change `style="top:0px; ..."` to `style="bottom:0px; ..." I feel like it wasn't that long ago that the debug buttons sat permanently above the "variables" list on the debug pane. I liked that. I swore at my computer less.

**Comment by weinand** [comment]
@pklapperich as always the new feature is available in the current Insiders release (1.25.0) and it will become available in the upcoming stable June release.

**Comment by WhatFreshHellIsThis** [comment]
Why in the world is it floating in the first place?  I never could understand that choice and now the fix is to make it even more "floaty"?!

**Comment by weinand** [comment]
@WhatFreshHellIsThis if you don't like the floating bar, you can dock it.

**Comment by WhatFreshHellIsThis** [comment]
Cool, thank you @weinand  I didn't know that, my work life just got a tiny bit more pleasant!  I still wonder at the mystifying choice to float it at all.  I've used VSCODE with many different languages and environments now and I still don't see a use-case for it other than to annoy people but maybe that's just me.
