### ISSUE TITLE
splitEditor not working for diff editor

### ISSUE THREAD

**Issue by vogler** [Microsoft/vscode#52491]
Issue Type: <b>Bug</b>

`workbench.action.splitEditor` (<kbd>cmd</kbd>+<kbd>\\</kbd>) works for normal editors but doesn't do anything for diff editors.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.18GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
latex-workshop|Jam|5.5.1
vscode-docker|Pet|0.0.27
haskero|Van|1.3.1
vscode-wakatime|Wak|1.2.2
Bookmarks|ale|0.19.1
npm-intellisense|chr|1.3.0
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.12
githistory|don|0.4.1
xml|Dot|2.3.1
vscode-npm-script|eg2|0.3.4
vscode-great-icons|emm|2.1.33
reasonml|fre|1.0.37
ocaml|hac|0.6.43
hoogle-vscode|jca|0.0.4
vscode-github|Kni|0.29.0
Lisp|mat|0.1.8
vscode-cosmosdb|ms-|0.7.2
python|ms-|2018.5.0
vscode-code-outline|pat|0.2.1
platformio-ide|pla|0.15.2
vscode-icons|rob|7.23.0
gi|rub|0.2.11
vscode-gtm|s3r|0.2.0
linter-xo|sam|2.2.1
vscoq|sie|0.2.7
stylish-haskell|vig|0.0.9
vim|vsc|0.13.0
better-align|wwm|1.1.6

(4 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
We explicitly disabled splitting of the diff editor for no specific reason, I think it is fine to allow for this.
