### ISSUE TITLE
cant install extension

### ISSUE THREAD

**Issue by vabka** [Microsoft/vscode#52498]
Issue Type: <b>Bug</b>

Just cant install extensions or updates from store. Only from vsix

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A6-6400K APU with Radeon(tm) HD Graphics    (2 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.97GB (4.14GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by chrmarti** [comment]
Are you behind a proxy?

**Comment by vabka** [comment]
Already Find problem: enviromental variable "Temp" 21.06.2018, 12:37, "Christof Marti" <notifications@github.com>:Are you behind a proxy?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.  ----С уважением,Банников Василий
