### ISSUE TITLE
Visual Studio Code Screen jumbles up in Fedora

### ISSUE THREAD

**Issue by tanekim77** [Microsoft/vscode#52492]
Symptom:
After about 5 hours of use of Visual Studio Code in Fedora, Fedora screen gets jumbled up, to a point I cannot see any legible things. I have tried with different machines, and they produce the same result.

How to reproduce:
Need to be constantly coding and navigating between files for 4~5 hours, in a big project.
Not being active in visual studio code would not reproduce the symptom.

If you are a fedora user, please share your experience here as well

**Comment by tanekim77** [comment]
I have tried copying same project to VS Codes in Ubuntu and OpenSuse, but they were running fine in those linux OS's. Only Fedora is having the issue.

**Comment by tanekim77** [comment]
The project I had was a big C++ project.

**Comment by chrmarti** [comment]
Could you attach a screenshot?

**Comment by tanekim77** [comment]
ok, I will attach it when I encounter that screen again.

**Comment by tanekim77** [comment]
![error](https://user-images.githubusercontent.com/20119808/41723800-042e440e-753a-11e8-9a2f-d1284905aa76.PNG)

**Comment by tanekim77** [comment]
To elaborate on it, the screen is not frozen. All menu buttons and functions still work if I make a right guess as to where they are behind the jumbled the screen. Also the screen gets more jumbled up as I move or click with mouse.

**Comment by Tyriar** [comment]
@tanekim77 what version of vscode are you using?

**Comment by chrmarti** [comment]
What is the output when you try upgrading?

**Comment by tanekim77** [comment]
It does not throw any errors, but it only upgrades up to 1.23.1.

**Comment by chrmarti** [comment]
Do you have the Code repository still listed? `dnf repolist`
If yes: Does `dnf check-update code` show the newer version?
If yes: What is the output of `dnf upgrade code`?

**Comment by tanekim77** [comment]
dnf upgrade code did the trick. I will test Today if the newest version that I just installed also has the symptom.

**Comment by tanekim77** [comment]
Today, the jumbled screen happened again with the newest version 1.24

**Comment by Tyriar** [comment]
Can you try close all windows and launching with `code --disable-gpu` to see if that helps?

**Comment by tanekim77** [comment]
I will try --disable-gpu from today and will let you know if I have the problem.

**Comment by tanekim77** [comment]
So far I have not gotten any jumbled screen after I set --disable-gpu. Is there any settings I can make --disable-gpu whenever I open vs code?

**Comment by Tyriar** [comment]
@tanekim77 the only way currently is to change the .desktop entry to include this arg. It should be located at: `/usr/share/applications/code.desktop`
