### ISSUE TITLE
Custom menu spacing errors

### ISSUE THREAD

**Issue by Studio384** [Microsoft/vscode#52494]
The new custom menu has a number of spacing issues:

1. The first item, "File", is to close to the Visual Studio Code logo.
2. The left and right padding of each item is to small, especially short items like "File" look weirdly tall (and they are thinner than the old menu had them).
3. Dividers in the menu's have more space above them than below them.

**Comment by sbatten** [comment]
@Studio384 @bpasero what do we think of this spacing. Should address all 3 issues
![spacing](https://user-images.githubusercontent.com/6561887/42251600-15322e16-7eed-11e8-9f25-bedf11dcadae.png)

**Comment by bpasero** [comment]
@sbatten yes I would revisit:
* spacing to application icon
* spacing between menu items in the menu bar
* spacing of menu items within a menu

This is probably also related to revisiting the font used for menus.

**Comment by sbatten** [comment]
@bpasero the image above has some spacing changes addressing the concerns of OP

**Comment by bpasero** [comment]
@sbatten yeah better. I still feel like the spacing to separators could be reduced:

![image](https://user-images.githubusercontent.com/900690/42263960-bee99b10-7f6f-11e8-9388-9a118d55fed7.png)

**Comment by sbatten** [comment]
@bpasero 

<img width="460" alt="spacing" src="https://user-images.githubusercontent.com/6561887/42301782-0c7bf7ea-7fcc-11e8-909c-6d52de7bb247.png">

**Comment by bpasero** [comment]
@sbatten looks good
