### ISSUE TITLE
extra space after pasting code.

### ISSUE THREAD

**Issue by DragonicDefson** [Microsoft/vscode#52496]
Issue Type: <b>Bug</b>

if you copy a piece of code. [for example. html].
and you paste it on another line of the file.
the code will have an extra indentation on each line.
it's pretty annoying.

i hope you guy's can fix this in the next update.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 6.1.7601

Extensions: none

**Comment by rebornix** [comment]
We tried to adjust the indentation when you paste the code, you can turn this feature off by setting `editor.autoIndent` to `false`.
