### ISSUE TITLE
Smooth scroll 

### ISSUE THREAD

**Issue by Kiran-Kannan** [Microsoft/vscode#52493]
**It would be nice to have a smoother scrolling effect to scroll between longer codes**

**Comment by chrmarti** [comment]
Are you using a mouse wheel, touchpad or something similar?

**Comment by alexandrudima** [comment]
@Kiran-Kannan Have you tried the option `"editor.smoothScrolling": true` ?

**Comment by Kiran-Kannan** [comment]
@alexandrudima oh thank you its much better now.
I think this should be added by default.

@chrmarti mousewheel
