### ISSUE TITLE
[json] schema specified in workspace settings not triggering Intellisense

### ISSUE THREAD

**Issue by masonicboom** [Microsoft/vscode#525]
My .vscode/settings.json has this section:

```json
	// ...
	"json.schemas": [
		{
			"fileMatch": [
				"/tslint.json"
			],
			"url": "http://json.schemastore.org/tslint"
		}
	]
```

When I make a tslint.json file in the root of my project, Intellisense does not activate to suggest properties, as I expect it to. The developer console does not show any errors.

Referencing that schema by putting a `"$schema": "http://json.schemastore.org/tslint",` property directly into tslint.json doesn't do the trick either.

I am running VS Code version 0.10.1 on OSX. My internet connection is working fine.

Am I doing something incorrectly?

(Side-question: Will specifying a single element in that "json.schemas" array within my project-local settings then clobber all the other elements of that array in the general settings (such as package.json)? Or does it just merge into the previously specified schemas?)

**Comment by aeschli** [comment]
![image](https://cloud.githubusercontent.com/assets/6461412/11401331/6311cb1c-9392-11e5-9707-ffbc22289065.png)

This seems to work from me. I get hovers and code assist. 
Can you open the dev tools (F1 > Toggle Developer Tools) and check the console?

Note: If you specify a single element in the "json.schemas" array, this will replace all other settings.
This is a known issue, that I want to fix.

**Comment by aeschli** [comment]
Closing, as works for me. Please reply to my @ tag if you more information
