### ISSUE TITLE
When switching conda environments in python editor, also switch environment in powershell

### ISSUE THREAD

**Issue by blaylockbk** [Microsoft/vscode#52504]
I followed the directions to switch python environments that exist in the `conda env list` from here, https://code.visualstudio.com/docs/python/environments, but when I try running the python script in PowerShell, the environment was not changed.  

Base environment: 

![image](https://user-images.githubusercontent.com/6249613/41681588-49b520ea-7492-11e8-964a-cea09597e8fe.png)  

Switch to custom environment:  

![image](https://user-images.githubusercontent.com/6249613/41681487-fb366ca8-7491-11e8-89b7-e84b4012d82a.png)

![image](https://user-images.githubusercontent.com/6249613/41681659-8040b67e-7492-11e8-8802-248e614544c9.png)  

Even after using the `activate` command, the conda environment still did not change. 

It would be nice if this change was made automatically when a new python environment was selected using the `Python: Select Interpreter`

**Comment by chrmarti** [comment]
The problem with `activate` not working appears to be discussed here: https://github.com/conda/conda/issues/7207#issuecomment-388537514

Moving the issue for the Python extension request. (Not sure if you can switch environments in an existing terminal.)

**Comment by chrmarti** [comment]
This issue was moved to Microsoft/vscode-python#2025
