### ISSUE TITLE
Failed to install VS Code update - 

### ISSUE THREAD

**Issue by apcspecialist** [Microsoft/vscode#52503]
- VSCode Version: 1.24.0
- OS Version: 1709
Steps to Reproduce:
1. Selected upgrade from the Visual Studio Code prompt
2. Error was produced after removing old version
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2120856/vscode-inno-updater.log)

Does this issue occur when all extensions are disabled?: Yes/No  Cannot test VSCode deleted

**Comment by Melvin-Abraham** [comment]
I also had a similar issue...

- VSCode Version: 1.24.1
- OS: Windows 10 Pro (version 1803) - Build 17134.112

Log File: 
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2122510/vscode-inno-updater.log)

**Comment by joaomoreno** [comment]
You seem to have #47841.

Please read this comment if you can provide more detail: https://github.com/Microsoft/vscode/issues/47841#issuecomment-393101777

Please read this one to disable background updates: https://github.com/Microsoft/vscode/issues/47841#issuecomment-395017687
