### ISSUE TITLE
Custom titlebar appears late compared to native titlebar

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#52507]
On Windows:

When launching VS Code with a native titlebar the titlebar (and menubar) are shown immediately when the window is created while the rest of the workbench appears later.

This is not the case when using the custom titlebar. The window initially is one empty flat rectangle and the titlebar appears at the same time as the rest of the workbench.

The time it takes to render the workbench varies on Windows more than on other platforms. During slow startups, the empty rectangle is the only thing the user sees.

**Comment by sbatten** [comment]
since @joaomoreno added the "splash screen" behavior, we discussed this issue may now be moot. Is this still the opinion?

**Comment by joaomoreno** [comment]
I think you mean @jrieken

**Comment by sbatten** [comment]
sorry @jrieken

**Comment by sbatten** [comment]
I don't see us doing anything major on this any time soon. the splash screen helps and this has sat for some time.
