### ISSUE TITLE
Unable to open 'Workspace Settings': Cannot read property 'defaultPreferencesRenderer' of undefined.

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode#52508]
Version 1.25.0-insider
Commit c51cf862a9604dffe2e3e8792a4b0a45213869a3
Datum 2018-06-18T08:50:30.859Z
Shell 2.0.2
Renderer 61.0.3163.100
Node 8.9.3
Architektur 6.1.534.41

- OS Version: win64

Steps to Reproduce:

I got this error while opening vscode and closing some existing windows.  Haven't been able to repro it, but figured I'd report it anyway for tracking.  Feel free to close if there's nothing you can do without a repro.

Unable to open 'Workspace Settings': Cannot read property 'defaultPreferencesRenderer' of undefined.

**Comment by roblourens** [comment]
Can you open the developer tools and see if there's a full stack trace?

**Comment by StephenWeatherford** [comment]
As mentioned I haven't been able to repro.

**Comment by roblourens** [comment]
Ok. I'm not sure how this would have happened, but please let me know if you see it agian.

**Comment by roblourens** [comment]
Thanks @mjbvz for the repro steps. I see it when I press cmd+, then immediately cmd+w. Has to be very fast.

**Comment by StephenWeatherford** [comment]
Thanks!
