### ISSUE TITLE
Improve zh-CN translation

### ISSUE THREAD

**Issue by 1dot75cm** [Microsoft/vscode#5250]
- VSCode Version: 0.10.15-insider (zh-CN)
- OS Version: Fedora 23

File | Current | Request(zh-CN)
------------ | ------------ | -------------
editorStatus.i18n.json | `"spacesSize": "空间: {0}",` | `"spacesSize": "空格: {0}",`
editorStatus.i18n.json | `"tabSize": "制表符大小: {0}",` | `"tabSize": "制表符: {0}",`
editorStatus.i18n.json | `"singleSelection": "Ln {0}，Col {1}",` | `"singleSelection": "行 {0}，列 {1}",`
editorStatus.i18n.json | `"singleSelectionRange": "Ln {0}，Col {1} (已选择{2})",` | `"singleSelectionRange": "行 {0}，列 {1} (已选择{2})",`
menus.i18n.json | `"aboutDetail": "\n版本 {0}\n提交 {1}\n日期 {2}\nShell {3}\n呈现器 {4}\nNode {5}",` | `"aboutDetail": "\n版本 {0}\n提交 {1}\n日期 {2}\nShell {3}\n渲染器 {4}\nNode {5}",`
gitActions.i18n.json | `"pull": "拉",` | `"pull": "拉取 (Pull)",`
gitActions.i18n.json | `"pullWithRebase": "拉取(变基)",` | `"pullWithRebase": "拉取 (Rebase)",`
gitActions.i18n.json | `"push": "推送",` | `"push": "推送 (Push)",`
indentation.i18n.json | `"indentationToSpaces": "将缩进转换为空白",` | `"indentationToSpaces": "将缩进转换为空格",`
indentation.i18n.json | `"indentUsingSpaces": "使用空格的缩进",` | `"indentUsingSpaces": "使用空格缩进",`
indentation.i18n.json | `"indentUsingTabs": "使用 \"Tab\" 的缩进",` | `"indentUsingTabs": "使用 \"Tab\" 缩进",`
indentation.i18n.json | `"toggleRenderWhitespace": "切换呈现空格"` | `"toggleRenderWhitespace": "切换显示空格"`

commonEditorConfig.i18n.json
Current: `"wrappingIndent": "控制换行的行的缩进。可以是“无”、“相同”或“缩进”。"`
Request: `"wrappingIndent": "控制换行时的缩进。可选项为 'none'、'same' 或 'indent'。"`

Current: `"cursorBlinking": "控制光标闪烁动画，接受的值为“闪烁”、“可见”和“隐藏”",`
Request: `"cursorBlinking": "控制光标闪烁动画，接受的值为 'blink'、'visible' 和 'hidden'",`

Current: `"cursorStyle": "控制光标样式，接受的值为“块”和“行”",`
Request: `"cursorStyle": "控制光标样式，接受的值为 'block' 和 'line'",`

**Comment by egamma** [comment]
@dbaeumer can you pls assign this one.

**Comment by johnliu2016** [comment]
@lukaschal please fix accordingly in the files.

editorStatus.nls.resx.lcl
menus.nls.resx.lcl
gitActions.nls.resx.lcl
indentation.nls.resx.lcl
commonEditorConfig.nls.resx.lcl

**Comment by lukaschal** [comment]
On review now.

**Comment by lukaschal** [comment]
Fixed as suggested.

**Comment by 1dot75cm** [comment]
Thanks @lukaschal

**Comment by 1dot75cm** [comment]
@johnliu2016  Where is these files? How to participate i18n?
