### ISSUE TITLE
Enabling custom titlebar causes a titlebar to appear before restarting

### ISSUE THREAD

**Issue by sylveon** [Microsoft/vscode#52502]
- VSCode Version: Latest master commit
- OS Version: Windows 10 build 17692

Steps to Reproduce:

1. Set `window.titlebarStyle` to `custom` without restarting
2. Observe a titlebar appear inside the view before having even restarted:
![image](https://user-images.githubusercontent.com/6440374/41680666-46656752-74a0-11e8-8c0e-4cd6fe13fbfa.png)

Expected result:
This only appears at restart, when the Windows titlebar has been hidden

Does this issue occur when all extensions are disabled?: Yes
@sbatten

**Comment by sbatten** [comment]
awesome, just verified this as well
