### ISSUE TITLE
Move selection horizontally

### ISSUE THREAD

**Issue by mquandalle** [Microsoft/vscode#5251]
Atom 1.8 will introduce two new commands to move text selections left and right. A description of the feature is available in https://github.com/atom/atom/pull/6631. It would be great to have these commands on VSCode.

![the atom feature](https://cloud.githubusercontent.com/assets/823545/7448891/7c64c1ea-f1f4-11e4-94bf-dfbaab1a5ee6.gif)

**Comment by egamma** [comment]
Thanks for bringing this feature to our attention @alexandrudima fyi

**Comment by alexandrudima** [comment]
That looks so cool

**Comment by mquandalle** [comment]
Could we use the <kbd>Alt</kbd>+<kbd>←</kbd> (respectively <kbd>Alt</kbd>+<kbd>→</kbd>) as the keyboard shortcut? That would match perfectly the actions to move lines up or down.

**Comment by yisibl** [comment]
https://github.com/colinta/SublimeMoveText

I think <kbd>control</kbd> + <kbd>cmd</kbd> + <kbd>←/→</kbd> is better. 

<kbd>Alt</kbd> + <kbd>←/→</kbd> is to move the cursor around the word.

**Comment by yisibl** [comment]
You can modify the shortcut key configuration, this is a temporary solution.

```json
	{
		"key": "alt+left",
		"command": "cursorWordStartLeft",
		"when": "!editorHasSelection && editorTextFocus"
	},
	{
		"key": "alt+right",
		"command": "cursorWordEndRight",
		"when": "!editorHasSelection && editorTextFocus"
	}
```
