### ISSUE TITLE
Unicode Characters in file path displayed incorrectly in debugger panel

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode#52512]
Issue Type: <b>Bug</b>

* Create a file named `汉语a2.js`
* Add some js code and add a breakpoint
* The breakpoints pane contains garbage (in Insiders)

**Note: This works in VS Code Stable**

<img width="562" alt="screen shot 2018-06-20 at 2 44 58 pm" src="https://user-images.githubusercontent.com/1948812/41686410-d4bcf8ce-7498-11e8-9b6b-103b3e8599da.png">

VS Code version: Code - Insiders 1.25.0-insider (e585e4bf008a50e5b1f4fde71cf6d255e25381bf, 2018-06-20T07:58:47.516Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 8, 8|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_1352010|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-generate-getter-setter|DSK|0.5.0
gc-virtualdocumentspy|Gra|1.0.1
application-insights|Vis|0.4.2
django-html|bib|1.2.0
django-snippets|bib|1.1.0
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.12
githistory|don|0.4.1
xml|Dot|2.3.1
gitlens|eam|8.4.1
tslint|eg2|1.0.33
vscode-npm-script|eg2|0.3.4
githd|hui|1.1.5
docthis|joe|0.7.1
MagicPython|mag|1.0.12
dotenv|mik|1.0.1
vscode-azureappservice|ms-|0.8.1
extension-manifest-editor|ms-|0.1.5
mssql|ms-|1.3.1
azure-account|ms-|0.4.0
cpptools|ms-|0.17.4
csharp|ms-|1.15.2
Go|ms-|0.6.83
debugger-for-chrome|msj|4.6.0
autodocstring|njp|0.2.1
vscode-docker|Pet|0.0.27
python|ms-|2018.7.0-beta
typescript-hero|rbb|2.3.2
vscode-yaml|red|0.0.13
vscode-icons|rob|7.23.0
yo|sam|0.9.3
cython|tcw|0.1.0
i18n-sample|vaz|0.1.0
jinja|who|0.0.8

</details>

**Comment by isidorn** [comment]
@DonJayamanne good catch and thanks for nice reproducable steps
