### ISSUE TITLE
Command to trigger fileRename on specific resource

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#52515]
**Problem**
As part of some code actions, we would like to be able to trigger a file rename operation. For example, #50685 requests triggering a file rename when you run the `mode to new file` refactoring

**Proposal**
Extend the `renameFile` command or introduce a new command that allows triggering a rename on a specific resource. The `editor.action.rename` command allows something similar.

I believe this may already be possible using `revealInExplorer` followed by `renameFile`. This issue requests a more standardize approach

**Comment by isidorn** [comment]
Currently the renameFile command is tightly coupled to the explorer and that file actually being rendered in the explorer.
Thus as you correctly assumed what you need can only be done by using two command `revealInExplorer` and `renameFile`. If I understand correctly there is currently only one extension needing this, so for now simplly execute those two commands.
When there are more use cases we can investigate into adding a command on the vscode side that would essential just call those two commands

**Comment by jrieken** [comment]
We have this covered with better workspace edits (which allow to create, delete, and rename resources)
