### ISSUE TITLE
cli command "code ." throw error on windows

### ISSUE THREAD

**Issue by AbstractFlame** [Microsoft/vscode#52510]
Hi,

- VSCode Version: 1.24.1
- OS Version: Windows 7

Steps to Reproduce:
1. Open command line
2. Get to the required directory
3. Type: code .

Does this issue occur when all extensions are disabled?: Yes

The error in the command line:
"D:\projects\html-css-basic-course>code --disable-extensions
A megadott nevet (VSCODE_CWD) a rendszer nem ismeri fel bels? vagy k?ls?
parancsk?nt, futtathat? programk?nt vagy k?tegf?jlk?nt.
{ Error: Command failed: VSCODE_CWD="D:\projects\html-css-basic-course" open -g
-n -b "com.microsoft.VSCode" --args --disable-extensions
A megadott nevet (VSCODE_CWD) a rendszer nem ismeri fel bels? vagy k?ls?
parancsk?nt, futtathat? programk?nt vagy k?tegf?jlk?nt.
    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'VSCODE_CWD="D:\\projects\\html-css-basic-course" open -g -n -b "com.micr
osoft.VSCode" --args --disable-extensions' }"

What I've tried already:
- Check environment variable path
- Run code without extensions

Please help

Best
Sami

**Comment by AbstractFlame** [comment]
Yes, you've translated the error message right I guess. As I wrote I type "code ." in the command line. This is where it comes from. Or I don't know what do you mean "come from". 

Or do you mean running "code ." without extension idea? This comes from you: "Does this issue occur when all extensions are disabled?: yes / no". But pls don't stuck with that. The main problem is that "code ." doesn't work at all. Do you have any idea what is the problem?

**Comment by chrmarti** [comment]
We will need @joaomoreno's insights on where that `VSCODE_CWD=...` line comes from.

**Comment by joaomoreno** [comment]
What looks odd to me is the launch command:

```
open -g -n -b "com.microsoft.VSCode" --args --disable-extensions
```

This is the pattern to launch apps on macOS (which we don't use BTW). And the platform seems to be Windows...

So I wonder what's up. What's your `PATH` variable?
