### ISSUE TITLE
Terminal doesn't work

### ISSUE THREAD

**Issue by themanigandan** [Microsoft/vscode#52513]
Issue Type: <b>Bug</b>

sometimes Terminal works fine but half en it is worst I can't find a path and nothing  works .. and displaying 1:bash.ex, => nothing works into the terminal

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.97GB (12.61GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
debugger-for-chrome|msj|4.6.0
sass-indented|rob|1.4.9

</details>

**Comment by Tyriar** [comment]
Can you share some screenshots of it not working as expected?
