### ISSUE TITLE
格式化代码有问题

### ISSUE THREAD

**Issue by superMonkey-T** [Microsoft/vscode#52529]
Issue Type: <b>Feature Request</b>

tab缩进从2改成4以后，偶尔会出现缩进还是2，格式化代码失败的问题。

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

**Comment by SunOfHomeBoy** [comment]
Better to use English！

**Comment by spitWind** [comment]
我们是汉人,说中文

**Comment by chrmarti** [comment]
```
Problems with formatting code

After the tab indent was changed from 2 to 4, there was occasionally indentation or 2 and the formatting code failed.
```

Please provide an example.
