### ISSUE TITLE
URL-encoded path fragment shown in UI

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#52524]
- Have a folder in the workspace with a space in the path name
- See that in quick open, the tab, and "open editors", the path fragment is displayed with a `%20` instead of a space

![image](https://user-images.githubusercontent.com/323878/41690220-540fc4ac-74a9-11e8-9dcc-4a95a64346d1.png)

**Comment by isidorn** [comment]
This should be fixed in latest. @roblourens please reopen if you still see this
Thanks
