### ISSUE TITLE
Allow "Declare property" quick fix for enums

### ISSUE THREAD

**Issue by gbbarroso** [Microsoft/vscode#52528]
The same way there's a "declare property" suggestion for classes when you use quick fix, there should be one for enums as well. Often you just want to create a new constant for an existing enum and you don't even care about the order / value, having this quick fix would save a trip back to the file containing the enum declaration.

To be clear, that's what I'm talking about:

![image](https://user-images.githubusercontent.com/11339504/41692866-f5318f6c-74d8-11e8-916e-b99742993ec7.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#25129
