### ISSUE TITLE
[json] problem with comment after literal

### ISSUE THREAD

**Issue by EduTel** [Microsoft/vscode#52523]
Issue Type: <b>Bug</b>

In my user settings i set  
*{
    "workbench.sideBar.location": "left"//note
}*  
when i change the value of something set from interface, the result values is that  
*{
    "workbench.sideBar.location": "left",
    "php.suggest.basic": false//note
}*  
and give me a error ("[jsonc] Value expected")  

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 6.1.7601

**Comment by mjbvz** [comment]
Verified that I no longer see the bug. The comment still ends up the second line which seems unexpected
