### ISSUE TITLE
using includes() on an Array is shown as an error. Kindly update the library

### ISSUE THREAD

**Issue by raviteja-avvari** [Microsoft/vscode#5252]
- VSCode Version:0.10.11
- OS Version: Ubuntu 14.04

Steps to Reproduce:

1. Just use includes() on an array
2.

**Comment by egamma** [comment]
@raviteja-avvari 
`includes()` is an ES7 feature and the JS language service currently support up to ES6. So you will not get Intellisense for `includes` but I cannot reproduce that you get an error:

![image](https://cloud.githubusercontent.com/assets/172399/14588513/95c3fe7c-04cb-11e6-8e75-e0017af708aa.png)

To disable the built-in JS syntax checking and only rely on a linter like ES6 use the `javascript.validate.enable: false` setting.
