### ISSUE TITLE
Can't update extension automatically or manually

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode#52526]
Issue Type: <b>Bug</b>

Failed to update 'ms-azuretools.vscode-cosmosdb'.

REPRO:

1) Says I should update Azure Cosmos DB:
![image](https://user-images.githubusercontent.com/6913354/41691778-57c30a5c-74b1-11e8-89de-a7c2524630ee.png)
2) I click on the update button.  After a few minutes it gives me:

Failed to update 'ms-azuretools.vscode-cosmosdb'.

3) I click  "Download Manually".
4) After downloaded, I click "Install from VSIX..." and choose the downloaded vsix
5) Progress bar in EXTENSIONS:
![image](https://user-images.githubusercontent.com/6913354/41691857-d2474676-74b1-11e8-9289-8a01881dfbba.png)
5) After several more minutes, the progress bar on the extension stops, I get no messages or errors whatsoever, and yet it still says the extension needs to be updated:
![image](https://user-images.githubusercontent.com/6913354/41691877-e42f0cc0-74b1-11e8-8e89-900f87257032.png)

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E31230 @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.96GB (6.28GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
mongogo|bag|0.1.2
regex|chr|0.2.0
vscode-markdownlint|Dav|0.18.0
githistory|don|0.4.1
jupyter|don|1.1.4
tslint|eg2|1.0.33
vscode-bump|fab|1.5.3
docthis|joe|0.7.1
vscode-antlr4|mik|2.0.3
vscode-azureappservice|ms-|0.8.1
vscode-azurefunctions|ms-|0.9.1
vscode-azurestorage|ms-|0.4.0
vscode-cosmosdb|ms-|0.6.0
python|ms-|2018.6.0
azure-account|ms-|0.4.0
csharp|ms-|1.15.2
azurerm-vscode-tools|msa|0.4.2
vscode-versionlens|pfl|0.21.1
yo|sam|0.9.3
extension-api|spy|0.3.1
python|tht|0.2.3
code-lens-roundup|wad|1.0.0

</details>

**Comment by sandy081** [comment]
@StephenWeatherford Can you please retry it by setting the log level to `trace` using the command `Set Log Level` and share us the logs (Shared Process) from Output Panel?

**Comment by StephenWeatherford** [comment]
https://gist.github.com/StephenWeatherford/7aaa81206cca12d429a00e34ddf18627

I've seen this error message before from vscode and was able to delete it manually and try again.  This time, though, I saw no error messages whatsoever.
I don't have any troubles manually renaming this folder, not sure why vscode would be an issue.

**Comment by sandy081** [comment]
@StephenWeatherford May I know if folder `ms-azuretools.vscode-cosmosdb-0.7.2` already exists and is that why the rename is failing?

**Comment by StephenWeatherford** [comment]
Yes, and when I deleted it, the install succeeded.

**Comment by sandy081** [comment]
#50385 looks related.

**Comment by sandy081** [comment]
@StephenWeatherford I want to know why the update was shown here. Did you change the version in the `package.json` file in `ms-azuretools.vscode-cosmosdb-0.7.2` folder?

**Comment by sandy081** [comment]
Related: #52946

**Comment by StephenWeatherford** [comment]
Don't really know why I got into this situation.  I did not manually modify the package, but I do author the extension.  I think what might have happened was that I installed 0.7.2 via VSIX to test it, then uninstalled and reinstalled the earlier version from marketplace. Then 0.7.2 shipped.

**Comment by sandy081** [comment]
Ah I see.. I think then this would got fixed by #52946. Please try with tomorrows insiders.
