### ISSUE TITLE
Add 'mixed' mode to workbench.list.openMode

### ISSUE THREAD

**Issue by yuval-gilboa** [microsoft/vscode#52535]
This is a feature request for adding a new '**mixed**' mode to **workbench.list.openMode** setting, that will apply 'doubleClick' behavior on parent nodes and 'singleClick' behavior on leaf nodes.

The setting workbench.list.openMode currently supports only two modes: '**singleClick**' and ' **doubleClick**'. Both of these modes work the same on any tree item, regardless of whether it is a parent node or a leaf mode. The 'mixed' behavior requested above is a desirable combination that cannot be achieved with any of the existing modes.

**Comment by yuval-gilboa** [comment]
Related to https://github.com/Microsoft/vscode/issues/47978

**Comment by isidorn** [comment]
This sounds like a fair feature request.
I would be open to accept a PR which fixes this if @bpasero agrees
