### ISSUE TITLE
Context menus do not overflow

### ISSUE THREAD

**Issue by JacksonKearl** [Microsoft/vscode#52533]
Custom context menus will clip at window edges instead of overflowing.
![cant overflow](https://user-images.githubusercontent.com/8586769/41694341-a82f09fc-74be-11e8-9c11-6b03b17358d2.gif)

VS Code version: Code - Insiders 1.25.0-insider (e585e4bf008a50e5b1f4fde71cf6d255e25381bf, 2018-06-20T08:08:46.972Z)
OS version: Windows_NT x64 10.0.16299

**Comment by SunOfHomeBoy** [comment]
Every update comes with a problem, But that's a good thing！That means VSCode is making progress！

**Comment by JacksonKearl** [comment]
@SunOfHomeBoy that seems like a different issue. This is related to the "custom" title bar option introduced in recent Insider's versions. You don't seem to have that enabled.

**Comment by SunOfHomeBoy** [comment]
@JacksonKearl Excuse me! How to activate?

**Comment by alkorsan** [comment]
a temporal solution can be:
https://github.com/Microsoft/vscode/issues/31278

open vscode with this flag --force-device-scale-factor=0.8
this will change the UI size and make it smaller, so menus will not be hidden at less.
I hope they will add the scroll to the menus soon , it s a basic thing.
