### ISSUE TITLE
Resizing a grid should not be allowed on custom menu

### ISSUE THREAD

**Issue by Joelism** [Microsoft/vscode#52539]
- VSCode Version: 1.25.0-insider (e585e4b, 2018-06-20T08:08:46.972Z)
- OS Version: Windows_NT x64 10.0.17692

![test](https://user-images.githubusercontent.com/14136385/41695365-577b7936-7541-11e8-8cba-4cacc024925f.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
The menu needs to use the highest z-index of them all I guess.

**Comment by bpasero** [comment]
Opened https://github.com/Microsoft/vscode/pull/53242
