### ISSUE TITLE
var in identifiers get highlighted incorrectly

### ISSUE THREAD

**Issue by martellaj** [Microsoft/vscode#5253]
- VSCode Version: **0.10.11**
- OS Version: **Windows 10**

Steps to Reproduce:

1. Create a JavaScript (or TypeScript) file.
2. Create a variable with the identifier of `variation` on `this` or an object's prototype.

Expected result: Highlighting is the same as any other variable.
Actual result: The `var` part of `variation` will be highlighted differently, even though it's part of an identifier name because (*I believe*) there's no preceding `var` on the same line. For example, `var variation = 0;` results in proper highlighting.
 
![image](https://cloud.githubusercontent.com/assets/1019478/14532242/3f917d62-0215-11e6-9ea6-f3e8d13da25b.png)

**Comment by OneOfOne** [comment]
I posted an issue about that 2 days ago https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/466

**Comment by egamma** [comment]
Fixed in 1.0, please upgrade to the lastest version.
