### ISSUE TITLE
Add ability to choose syntax highlighting on unsaved document

### ISSUE THREAD

**Issue by JackStromberg** [Microsoft/vscode#52536]
Issue Type: <b>Feature Request</b>

Can you please add the ability to choose what syntax highlighting to use on an unsaved document?  Many times I copy and paste small scripts to a new "Scratch document", where I'd like to see the syntax highlighting, but not necessarily save the document for it to show up.  You can easily do this in notepad++, where they have a menu item called Language and you simply select the language you want for syntax highlighting.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

**Comment by taalas** [comment]
@JackStromberg At least in recent versions of VS Code you should be able to do exactly what you describe using the language mode chooser in the footer (bottom right). Right beside your notification bell there should be an element to choose the language even if your document is unsaved.
