### ISSUE TITLE
Cant click on custom context menus when on top of title bar

### ISSUE THREAD

**Issue by JacksonKearl** [Microsoft/vscode#52531]
when the context menu overlaps with the title bar, the buttons become unclickable. It seems the clicks fall through to the title bar, as double clicking makes the window full screen. 
![cant click title bar](https://user-images.githubusercontent.com/8586769/41694176-de5d70dc-74bd-11e8-8767-ed7ca81d6d95.gif)

VS Code version: Code - Insiders 1.25.0-insider (e585e4bf008a50e5b1f4fde71cf6d255e25381bf, 2018-06-20T08:08:46.972Z)
OS version: Windows_NT x64 10.0.16299

**Comment by JacksonKearl** [comment]
![debugbutton](https://user-images.githubusercontent.com/8586769/41747927-8e096ae4-7564-11e8-9913-69119d8e65a4.gif)
related

**Comment by sbatten** [comment]
Less of an issue now that the context menu math has been updated
