### ISSUE TITLE
[cmd+click] go do define not stable

### ISSUE THREAD

**Issue by Fov6363** [Microsoft/vscode#52534]
- VSCode Version: 1.24.1
- OS Version: macAir 10.13.2

Steps to Reproduce:

1.if close screen mac, and open it on second day, it large probability [cmd+click] not working.and i restart vscode ,it work.

2.or sudden [cmd+click] not working,don't know reason.

3.resolve:  restart vscode.

4.can I do something when [cmd+click] not working?

**Comment by alexandrudima** [comment]
@Fov6363 Which programming language are you using where cmd+click is not working for you? When cmd+click is not working, are alternative means of invoking go to definition working correctly? (i.e. right click + go to definition or <kbd>F12</kbd> ?)

**Comment by Fov6363** [comment]
@alexandrudime
1.write js 
2.node -v = 6.10.3
3.the alternative I should to try.wait me~

**Comment by mjbvz** [comment]
Please provide a code example or small example project. Also test this on VS Code insiders with all extensions disabled

**Comment by Fov6363** [comment]
sorry,I can't provide code,but I find when code is too long,it will be happen,one file My code line about 2000 lines,I will try it close extensions disabled can [cmd+click]

**Comment by Fov6363** [comment]
when I [cmd+e] checkout project,it happend, and i [cmd+click] or [click+go] or F12 ,it alert "未找到**任何定义",i close one extension, and reload project,it work,I think the extension is not reason,can i debug something for support more info?

**Comment by Fov6363** [comment]
when [cmd+click] is not work,I create a new .js file in project,and write two line code:
```
let abc = 1;

console.log(abc);
```
[cmd+click] the 'abc' is not work, and F12 not work.

**Comment by alexandrudima** [comment]
未找到**任何定义 translates to "No definitions found**", so I believe this is a problem with the language service, not with the UI gesture handling.

**Comment by mjbvz** [comment]
@Fov6363 Does this reproduce in the [latest VS Code build](https://code.visualstudio.com/insiders/) with all extensions disabled? Do you see it in all projects or just specific ones?

**Comment by Fov6363** [comment]
1.It latest vscode version.
2.not disabled all extensions.because I not know to reproduce,I need extensions to write code...
3.just specific ones, the project more file has more line(> 2000), when I open the project, [cmd+click] a variable, it will not quickly go to define, the vscode file top show a move cursor,and the macAir cpu ,memory is growth fast,normal, it will 1~3 min ago, the [cmd+click] can work, and sometimes, [cmd+click] not work, I think it load project first need build self runtime something, this section can failed

**Comment by mjbvz** [comment]
Please try temporarily disabling extensions to see if one of them is causing this issue. If you are seeing performance issues, you can also follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information and hopefully track  down what may be going wrong

If you are able to, please also share an example file or small example project
