### ISSUE TITLE
Test: Output refactorings

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#5254]
- [x] win @jrieken 
- [x] mac @waderyan 
- [x] linux @joaomoreno 

We have fully refactored our output support. Verify the following works as before:
* Changing output between 'Tasks', 'Git', 'Extensions'
* Last selected output is preserved across VSCode sessoins
* You are able to create a new output channel and write to it from an extension

**Comment by vsccarl** [comment]
Verified all these scenarios work on Windows 10.

**Comment by isidorn** [comment]
@vsccarl these changes are quite fresh, on what vscode version did you verify it?

**Comment by vsccarl** [comment]
@isidorn I verified them on commit [8ca1f811dff7e2120b58c29463483b7f5a00b81a](https://github.com/Microsoft/vscode/commit/8ca1f811dff7e2120b58c29463483b7f5a00b81a) 
Should I run through them again today?

**Comment by isidorn** [comment]
No, we should not test them more now. When we create `testplan-item` our intentation is to test them in the endgame week so we are sure the feature works as expected once we shipe them to the user.
More details about our development process can be found [here](https://github.com/Microsoft/vscode/blob/master/wiki/project-management/development-process.md)

**Comment by waderyan** [comment]
Looks good. 

FYI @isidorn the link above gives a 404.
