### ISSUE TITLE
a simple way to run a command on the current file (without workspace)

### ISSUE THREAD

**Issue by santagada** [Microsoft/vscode#52548]
Right now it is very very complex to just bind a key press to execute a command on the current file without it being in a workspace (so no tasks.json in a parent directory). So a simple runCommand that can use ${file} and either show the results or ignore the output is needed. A simple example would be to do wc ${file} and show the result on the status bar or some other form that is not a modal box (so you can continue working).

my current work case is doing p4 edit on the current file (as all the perforce extensions need a workspace for some strange reason).

Someone tried to help me on stackoverflow but the resulting code is very messy: https://stackoverflow.com/questions/50838602/bind-a-keypress-to-a-shell-command-that-uses-the-current-file-in-visual-studio-c/50846586

**Comment by dbaeumer** [comment]
For now the easiest to achieve this is to write our own little extension that adds a new command that when executed runs the wc $file. 

There is already a feature request to support user level tasks.josn files which would then support that use case. Objection to close it as a dup. I am pretty sure that we will not implement a different command execution system.
