### ISSUE TITLE
[Accessibility]A11y_VSCode_LangMode_Screenreader: NVDA is not reading complete value of exapnded LangMode

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#52544]
**Environment Details:**
VSCode Version : 1.24.0
OS Version : Win10

**Additional Details:**
Screenreader,NVDA,MAS1.3.1

**Repro Steps:**
1.Navigate to Status Bar and select "Select Language Mode" button.
2.Navigate to expanded langmode combo values through arrow keys.
3.Select any value from list.
4.Observed that NVDA is not reading all the data which is written in selected value.

**Actual:**
If the value is selected by the arrow keys and if value is for eg:"symbol Batch(bat)" then NVDA is reading it only as "Batch" but not reading complete value.

**Expected:**
If the selected value of expanded langmode is "Symbol Batch(bat)" then NVDA should read it as "symbol's(name) Batch right parenthesis bat left parenthesis".

**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
[https://microsoft.sharepoint.com/teams/msenable/mas/Pages/browse-fixes.aspx](url)

**User Impact:**
User will not understand what is the exact value is selected.

**MAS Reference:**
MAS1.3.1: [https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}](url)

**Attachment For Reference:**
[[Accessibility]A11y_VSCode_LangMode_Screenreader.pptx](https://github.com/Microsoft/vscode/files/2122109/Accessibility.A11y_VSCode_LangMode_Screenreader.pptx)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/52383
