### ISSUE TITLE
Zoom Reset not respecting User Settings window.zoomLevel

### ISSUE THREAD

**Issue by dysol** [Microsoft/vscode#52543]
- VSCode Version: 1.24.1
- OS Version: 10.13.5

Steps to Reproduce:

1. Set your window.zoomLevel: -1 (can be any integer)
2. Use keyboard shortcut to reset zoom: (mine is mapped to cmd+0

What happened?
Zoom resets to 0 rather than -1

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by chrmarti** [comment]
`window.zoomLevel` is the current zoom level. It does not affect the what the reset zoom level is. That is always 0.
