### ISSUE TITLE
👋The Fastest Way to complete your code by one key and get more code efficiently👋

### ISSUE THREAD

**Issue by noberk** [Microsoft/vscode#52549]
I hope like this .

![1](https://user-images.githubusercontent.com/26300918/41699551-f7db00f8-7556-11e8-935a-69aec3af37c1.png)

![2](https://user-images.githubusercontent.com/26300918/41699582-151cc6b0-7557-11e8-914f-a00a2021052e.png)

I am programming engineer for 8 years , VSCode & VS  has good perception for auto complete our code when we type a variable name and next input  key "dot" that will hint you and recommended you remain words that's pritty good ...   a list of recommended words will be showing immediately, if you we want to select top 1 or 2 or 3 word  we can press upArrow or downArrow on keyboard to changed .. the problem is if you want to selected 4 or 5 or 6 or 7 or 8 variable name item . you have to press upArrow upArrow upArrow  or downArrow downArrow downArrow many times .

there is a good resolution for this common problem...

we can using upArrow or downArrow key  and also   press  1 ,2, 3, 4, 5, 6 number key for each match variable name item then fill the remaining automatically ...

**Comment by noberk** [comment]
@ramya-rao-a  dear expert, when we will get the new feature?

**Comment by ramya-rao-a** [comment]
We have fuzzy matching supported in the auto-complete feature. Which means you can type a few letters of the suggested words (the letters need not be contiguous, you can type first 2 letters and then then the 4th or 6th or any letter), and the auto-complete feature will filter down the list, so that you dont have to press the up/down arrow key a lot to choose the word.

cc @jrieken for the suggestion of using the number keys to select from the auto-completion list.

**Comment by noberk** [comment]
Yes，agreement you and your team opinions ..  I have been used visual studio series from 05，08，10 ，12，13，15  until now。。Intelligent-code-complete is very cool ，and why we need the new feature 。
1） using up and down keys， we need to lift our right hand or move to right direction then go back ，it will waste your energy if again and again
2） if you type some incorrect words on  （fuzzy matching supported in the auto-complete feature ）you have to enter backspace key to modification and then type words again to find out the remaining word.
3) another reason in China, Japan,  Korea and so many Country which they like to using number key on left top of the keyboard that to select vocabulary which when they input vocabulary ... it's a custom,
4) it's the shortest distance between point A to point B that is Line. if we want to select the item we just only moving our finger of the left hand, 1 2, 3 4 5 6 7 8 9 0 any key you want that's easy way achieve! O(∩_∩)O
5) this is  the very cool and new feature in the IDE's world which is you never seen before

**Comment by ramya-rao-a** [comment]
Thanks for the explanation @noberk

@jrieken I see that you have upvoted this request and so assume that you are on board.

**Comment by noberk** [comment]
Thank you for your team review . Perharps You have misconstrued my words . I mean that we holp the new feature on VsCode  which can improve all the developer code speed at least in others country which are often switch to input method between English and their own mother country languages on coding... 

We have numerous people who they love coding in VScode  if the smart feature may save a developer 1mins to 10mins one day on his work ,I think, even more that data... so assume we have hundred thousand people , one million people even more ,  we use the factor of people number mutils saved time than we got a huge number . which mean we Save developer's life . We are angels!!o(∩_∩)o

**Comment by noberk** [comment]
@ramya-rao-a Thank You.. ramya-rao-a ..What is RPs mean?   You thought which recommended me to implement this feature by my self? ?

**Comment by ramya-rao-a** [comment]
@noberk I meant pull requests to the code.

We agree that this a useful feature to have. So, we welcome pull requests from anyone who wants to implement this feature. VS Code is an open source project and welcomes contributions from all.

**Comment by noberk** [comment]
@ramya-rao-a  oh I got , I think VS code is very popular and perfessional Software , as a developer that we can implement the new funtion. But should we need a UI design to helper us what getting more visual effect on it?  I don't know the workflow of the open source project... how should I do


pull the code ...  then push to you .. ? how to design user interface?

**Comment by ramya-rao-a** [comment]
I dont think there is a need for any new UI. You can implement the feature such that pressing Ctrl+2 would select the second item from the currently selected item in the auto-complete list. You can do this for numbers from 1 to 11, as we dont show more than 12 items in the list.

Please read [How to Contribute](https://github.com/Microsoft/vscode/wiki/How-to-Contribute)

**Comment by noberk** [comment]
@ramya-rao-a  OK,  I have readed the source code about that related to the TS files which are
  (((suggestWidget.ts,suggestController.ts))) you pointed to me.., each file has a lot of import and reference objects which they are almost without comments....  a ton of interfaces & classes & functions are like Spider Web . would you give me some advise? how to get started?😭😭

**Comment by ryenus** [comment]
I kinda understand the need for this, but @ramya-rao-a is right that auto-completion with fuzzy matching is already supported, plus that:

Assuming the suggestions are numbered as requested:

1. what if the number for a suggestion also appears in another suggestion? At least it would be a little surprise.

2. Using a number means you'd remember the number, rather than the actual suggestion, what happens if the suggestions are smart enough that the order varies even though the contexts are similar? 

IMAO, if this is implemented, it's probably better to have a setting that conditionally turn it on.

**Comment by DJLad97** [comment]
Sorry for being completely off topic, but can I ask what theme you have @noberk

**Comment by ramya-rao-a** [comment]
@noberk Were you able to get a local set up running for VS Code?

**Comment by DJLad97** [comment]
@noberk Sorry, your VSCode theme you have applied in the image of your first comment

**Comment by noberk** [comment]
@DJLad97  the theme called  "Cobalt2 Theme official"

**Comment by TheSharpieOne** [comment]
Something like #49437 would also help achieve "The Fastest Way to complete your code by one key and get more code efficiently"
The combination of this additional hot-key and AI auto-complete suggestions would be amazing.

**Comment by noberk** [comment]
@ramya-rao-a   I tried to install the starter few day ago which follow the document guide. but finished 4 of 5 finally . it didn't work....~~    recently I have ton of work to do...  I am going to do this feature late...

**Comment by noberk** [comment]
@ramya-rao-a I readed some ts code which is related to this feature which you offered ... it's hard to comprehension.. because large size import variables inside it ...

**Comment by ramya-rao-a** [comment]
@noberk After you have a local instance of VS Code running from the source (using `./scripts/code.sh` or `scripts\code.bat`), 
- Set `sticky` to `true` at https://github.com/Microsoft/vscode/blob/ba795060a4c997331c2062017ea27cf7f7faf6a5/src/vs/editor/contrib/suggest/suggestWidget.ts#L38 and reload the dev instance of VS Code. This will let you debug easily and ensure that the widget doesnt disappear when your mouse is elsewhere.
- use the instructions in [Debugging VS Code](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#debugging) to debug the suggest widget. 
- Add a break point in the [showSuggestions](https://github.com/Microsoft/vscode/blob/ba795060a4c997331c2062017ea27cf7f7faf6a5/src/vs/editor/contrib/suggest/suggestWidget.ts#L681) method and its easy to follow from there

**Comment by noberk** [comment]
@ramya-rao-a  very nice and clear suggestion that pretty good for me thank you !

**Comment by noberk** [comment]
@ramya-rao-a  
![image](https://user-images.githubusercontent.com/26300918/43659140-a97650c6-978d-11e8-8f21-4a657b51509b.png)

electron-v2.0.5 is always loadding. speed like the snail

![image](https://user-images.githubusercontent.com/26300918/43659230-ef151f72-978d-11e8-8f3b-ec7f2a874dc7.png)

I got the .zip file from another Github link , where should I place it that can support the next procedure to running

**Comment by ramya-rao-a** [comment]
I dont understand why you would need to copy the zip file...

**Comment by noberk** [comment]
@ramya-rao-a because   [electron-v2.0.5.zip]  could not download successfully in my local region forever.. so I try to download the offline zip file .

**Comment by ramya-rao-a** [comment]
@rebornix Do you have any ideas on where the downloaded electron zip needs to be placed? Or what the alternative is for people from China to work on VS Code source code?

**Comment by ryenus** [comment]
This might help: 

https://github.com/electron-userland/electron-download/blob/master/lib/index.js#L64
