### ISSUE TITLE
Cannot exit zen mode after reload window in zen mode

### ISSUE THREAD

**Issue by biggray** [Microsoft/vscode#52550]
Issue Type: <b>Bug</b>

1. enter zen mode
2. reload window
3. try to exit zen mode -> not working

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.66GB (2.23GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe E:\work\code\git\FluentExcel|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.18.0
vscode-eslint|dba|1.4.12
docs-markdown|doc|0.1.1
xml|Dot|2.3.1
tslint|eg2|1.0.33
php-intellisense|fel|2.3.3
docomment|k--|0.1.0
mssql|ms-|1.3.1
python|ms-|2018.6.0
cpptools|ms-|0.17.4
csharp|ms-|1.15.2
Go|ms-|0.6.83
PowerShell|ms-|1.7.0
typescript-javascript-grammar|ms-|0.0.42
vs-keybindings|ms-|0.2.0
debugger-for-chrome|msj|4.6.0
vetur|oct|0.12.5
vscode-docker|Pet|0.0.27
java|red|0.27.0
vscode-java-debug|vsc|0.9.0
vscode-maven|vsc|0.9.0

</details>

**Comment by chrmarti** [comment]
It stays in fullscreen mode for me (on Mac).
