### ISSUE TITLE
[Accessibility]A11y_VSCode_GoToLine_Screenreader: NVDA is reading expanded values of "GotoLine" as blank.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#52556]
**Environment Details:**
VSCode Version : 1.24.1
OS Version : Win10

**Additional Details:**
Screenreader,NVDA[2018.2],MAS1.3.1

**Repro Steps:**
1.Navigate to Status Bar and select "Go To Line" button.
2.After opening the "GoToLine" the keyboard focus is on editable text field.
3.Navigate to expanded values of gotoline.
3.Observed that,NVDA reading the focused value as blank.

**Actual:**
The focused selected value nvda is reading it as blank.
such as "Untitled-2" reads as blank.

**Expected:**
NVDA should read "Untitled-2" as "Untitled-2" instead of blank.

**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
[https://microsoft.sharepoint.com/teams/msenable/mas/Pages/browse-fixes.aspx](url)

**User Impact:**
User will not understand what value is selected from expanded "GoToLine"

**MAS Reference:**
MAS1.3.1: [https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}](url)
**Attachment For Reference:**
[[Accessibility]A11y_VSCode_GoToLine_Screenreader.pptx](https://github.com/Microsoft/vscode/files/2122488/Accessibility.A11y_VSCode_GoToLine_Screenreader.pptx)

Does this issue occur when all extensions are disabled?: Yes
[[Accessibility]A11y_VSCode_GoToLine_Screenreader.pptx](https://github.com/Microsoft/vscode/files/2133158/Accessibility.A11y_VSCode_GoToLine_Screenreader.pptx)

**Comment by isidorn** [comment]
Dup of the other quick open items
https://github.com/Microsoft/vscode/issues/52383
and tab wrongly jumps
