### ISSUE TITLE
DNX Command does not work with spaces in path (still)

### ISSUE THREAD

**Issue by jtsom** [Microsoft/vscode#5255]
- VSCode Version: 0.10.15-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Open any .NET Core project
2. Hit F1, choose DNX Run Command, then dnx web

If there is a space in the path to the project, a command window opens with the error:
```
'C:\Users\John' is not recognized as an internal or external command,
operable program or batch file.
Press any key to continue . . .
```

in my case, the path to the project is:
c:\Users\John Tsombakos\Documents\Visual Studio 2015\projects\Testapp

This problem still occurs after the supposed downstream dependencies have been fixed (OmniSharp and the Microsoft run-in-terminal packages)

**Comment by jtsom** [comment]
Problem still exists in just released Version 1.0

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#189

**Comment by jtsom** [comment]
And yet in Omnisharp, they are saying the "fix" has been merged in, and yet it is still broken.
