### ISSUE TITLE
Refactor... action leaves some screen cheese behind when there are no refactorings available

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#52559]
1. Open a .ts file
2. Open the context menu on a location without any refactorings
3. Select Refactor...

-> the action leaves some screen cheese. It looks like this is the menu that would show up when there are refactorings.

![cheese](https://user-images.githubusercontent.com/172399/41703316-268cd968-7533-11e8-94ce-275dd6970cf1.gif)

**Comment by sbatten** [comment]
dupe of #52516
