### ISSUE TITLE
No collapse/expand sign for indent codes

### ISSUE THREAD

**Issue by nadinugraha** [Microsoft/vscode#52557]
Issue Type: <b>Bug</b>

This feature used to be working, but now it isn't since the last update. So, there is no collapse/expand sign for indent code, the sign only appears when there is a code with "{" at the end of the text code. 

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (3.81GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
beautify|Hoo|1.3.2
node-debug2|ms-|1.20.0
debugger-for-chrome|msj|4.6.0
vetur|oct|0.12.5
code-settings-sync|Sha|2.9.2
vscode-react-native|vsm|0.6.11
vscode-todo-highlight|way|0.5.12

(4 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
Depending on the language, there are different folding strategies.
- indentation based folding
- syntax aware folding

If a language has syntax aware folding, it is used by default. If you prefer indentation based folding you can configure this:
```
"[typescript]": {
	"editor.foldingStrategy": "indentation"
}
```
