### ISSUE TITLE
Find widget: Keyboard focus goes in an optimized order

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#52564]
**Environment Details:**
VSCode Version : 1.24.1
OS Version : Win10

**Additional Details:**
Keyboard,MAS2.4.3

**Repro Steps:**
1. Launch VS Code.
2. Navigate to Status Bar and select “Find And Replace " button.
3.Observed that keyboard focus goes in incorrect sequence.

**Actual:**
The first keyboard focus goes on the "Find" editable text field. instead of "ToggleReplaceMode".

**Expected:**
The first keyboard focus should goes on the "ToggleReplaceMode" instead of "Fine" editable text field.

**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
[https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx](url)

**User Impact:**
The user will not understand the sequence of the actionable controls.

**MAS Reference:**
MAS2.4.3: [https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={0de7fbe1-ad7e-48e5-bcbb-8d986691e2b9}](url)

**Attachment for Reference:**
[[Accessibility]A11y_VSCode_FindAndReplace_Keyboard.pptx](https://github.com/Microsoft/vscode/files/2122605/Accessibility.A11y_VSCode_FindAndReplace_Keyboard.pptx)
[[Accessibility]A11y_VSCode_FindAndReplace_Keyboard1.pptx](https://github.com/Microsoft/vscode/files/2133167/Accessibility.A11y_VSCode_FindAndReplace_Keyboard1.pptx)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
@rebornix do we plan to change the keyboard focus order. If yes than can we do this in september.
If no, then we should close this as invalid with a good reason.
Assigning to September and adding under-discussion

**Comment by rebornix** [comment]
I don't think we are going to change the order of focusing into the find widget. When the find widget is launched and focused, we want to allow users to directly type in query keywords. We have the same experience for Search Viewlet (when it's opened, the focus is in the input box, not the left side toggle button), Git viewlet (focus in the textarea, instead of the top-corner expand/collapse button).

If you think this makes sense, we can then close it.

**Comment by isidorn** [comment]
@rebornix agree with what you outlined. Closing as designed
