### ISSUE TITLE
On MacOS Typescript intellisense shows import file path instead of types

### ISSUE THREAD

**Issue by jnorkus** [Microsoft/vscode#52567]
Issue Type: <b>Bug</b>

On MacOS when typing a function, intellisense shows the full file path of the import for the function arguments, cluttering and making it difficult to read.

![image](https://user-images.githubusercontent.com/5137138/41707156-2aff8dde-7546-11e8-97dc-c177959e92a1.png)

Expected: see only the type name.

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:30:30.113Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.42GB free)|
|Process Argv|/private/var/folders/rn/bl7tnn794ml821qb25f161mc0000gn/T/AppTranslocation/5EC863BE-BEFE-4DD9-9626-499DB8BF5CB7/d/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|2.14.0
flutter|Dar|2.14.0
prettier-vscode|esb|1.5.0
Angular-BeastCode|Mik|6.0.17
prettify-json|moh|0.0.3
nativescript|Tel|0.7.4

</details>

**Comment by mjbvz** [comment]
Do you see this problem in VS Code insiders?

**Comment by jnorkus** [comment]
Seems to be fixed in insiders! Sorry for not checking first.
