### ISSUE TITLE
Attach to extension host: breakpoints ignored

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#5256]
- VSCode Version: insiders but can also repro on latest vscode alpha
- OS Version: OS X

Steps to Reproduce:

1. open vscode repo in built VSCode 
2. `scripts/code.sh`
3. in the built VSCode choose 'Attach to Extension Host' and attach -> all looks good
4. Put some breakpoints in extension host code -> notice these breakpoints never get hit. Also notice that VSCode will not break on any exceptions

##### Additional info
Putting breakpoint in .js files and setting `sourceMaps` to `false` does not help.
Regular extension development / debugging is working just fine.
This used to work couple of milestones ago.

##### Example for step 4 

Put breakpoint in `exHostOutputService.ts:53`. And from your extension try to show the output via the following snippet:
```
const outputChannel = vscode.window.createOutputChannel("Test");
outputChannel.show();
```

**Comment by else** [comment]
Having the same problem here with 1.0.0 fa6d0f0381. Can you give me a version where it worked?

**Comment by else** [comment]
I had a short look with Wireshark and I can see that the actual commands to set a breakpoint are being sent, but paths look wrong (target host is running Linux):

```
> {"command":"setbreakpoint","arguments":{"line":5,"column":0,"type":"scriptRegExp","target":"^(.*[\\/\\\\])?[cC]:\\\\Users\\\\simon\\\\git\\\\test\\\\js\\\\routes\\\\entity\\.js$"},"type":"request","seq":24}
< {"seq":69,"request_seq":24,"type":"response","command":"setbreakpoint","success":true,"body":{"type":"scriptRegExp","breakpoint":8,"script_regexp":"^(.*[\\/\\\\])?[cC]:\\\\Users\\\\simon\\\\git\\\\test\\\\js\\\\routes\\\\entity\\.js$","line":5,"column":0,"actual_locations":[]},"refs":[],"running":true}
```

**Comment by isidorn** [comment]
This has been fixed in latest and should be availbe next week in the insiders channel

**Comment by else** [comment]
Can you point me to the commit?

**Comment by isidorn** [comment]
https://github.com/Microsoft/vscode-node-debug/commit/c2c41f3647c653b780497cdccf7e85cafd43f546
