### ISSUE TITLE
.Vue files udnerlining

### ISSUE THREAD

**Issue by StefanTodorov988** [Microsoft/vscode#52563]
Issue Type: <b>Bug</b>

Hello 

The ide is underlining(red) :
`      <p v-for="customer in customers">{{customer.Name}} <button v-on:click="login(customer)">Login</button></p>
`
this line ,wich is working perfectly 

Best Regards

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (8.97GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.3.2
vetur|oct|0.12.5
vscode-icons|rob|7.23.0

(1 theme extensions excluded)

</details>

**Comment by octref** [comment]
https://github.com/vuejs/vetur/issues/261

It shows you the error. You should follow the link and fix your error.
