### ISSUE TITLE
VS code's “Go to definition” menu item goes to type definition

### ISSUE THREAD

**Issue by LAITONEN** [Microsoft/vscode#52565]
🚨 The issue tracker is not for questions, but there is no other place to get help from. 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/vscode.

I asked - no answer: https://stackoverflow.com/questions/50952350/vs-codes-go-to-definition-menu-item-goes-to-type-definition

**Comment by chrmarti** [comment]
Please add an example.

**Comment by mjbvz** [comment]
@LAITONEN Please share a code example, or even better a small example project
