### ISSUE TITLE
Editor in zen mode does not take the entire screen

### ISSUE THREAD

**Issue by rodrigoelp** [Microsoft/vscode#52566]
Issue Type: <b>Bug</b>

When I toggle zen mode, the app enters the mode but the editor seems to be constrained to a small portion of the screen instead of expanding to all of it. It seems to be a render issue... annoying issue.

VS Code version: Code - Insiders 1.25.0-insider (e585e4bf008a50e5b1f4fde71cf6d255e25381bf, 2018-06-20T07:58:47.516Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.16GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
json2ts|Gre|0.0.6
swift|Kas|0.0.3
solargraph|cas|0.17.4
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
tslint|eg2|1.0.33
vscode-npm-script|eg2|0.3.4
prettier-vscode|esb|1.5.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vscode-npm-dependency|how|1.2.0
ts-extension-pack|loi|0.0.1
prettify-json|moh|0.0.3
debugger-for-chrome|msj|4.6.0
color-highlight|nau|2.3.0
indent-rainbow|ode|7.2.2
vscode-ios-common-files|Ort|1.0.4
vscode-jest|Ort|2.8.0
tsimporter|pmn|1.2.14
typescript-hero|rbb|2.3.2
Ruby|reb|0.18.0
vscode-icons|rob|7.23.0
markdown-preview-enhanced|shd|0.3.5
gitconfig|sid|1.0.1
move-ts|str|1.11.3
vim|vsc|0.13.1
vscode-react-native|vsm|0.6.11
vscode-todo-highlight|way|0.5.12
markdown-all-in-one|yzh|1.4.0

</details>

**Comment by rodrigoelp** [comment]
I've also tested it on the latest available build of vscode: Code - Insiders 1.25.0-insider (c5c7d43b65bcbbb3851fbd972fad077631c707e3, 2018-06-21T05:05:09.106Z)

**Comment by chrmarti** [comment]
Could you attach a screenshot?

**Comment by rodrigoelp** [comment]
Yup, here it comes.

Now that the duplicate detector showed a few more items, might be similar to #46277

<img width="1680" alt="screen shot 2018-06-21 at 12 09 45 pm" src="https://user-images.githubusercontent.com/301434/41706171-25fc968c-754c-11e8-9b00-11e6d0679189.png">

**Comment by chrmarti** [comment]
You are in Centered Layout mode. Try View > Toggle Centered Layout while in Zen mode.

**Comment by rodrigoelp** [comment]
Ah, I see. My bad, I don't remember ever accessing that property.

Thank you, Closing this issue as it was a misconfiguration on my part.
