### ISSUE TITLE
git remote branch sync

### ISSUE THREAD

**Issue by baiyunchen** [Microsoft/vscode#52571]
- VSCode Version:1.22.2
- OS Version: windows 10

Steps to Reproduce:
When someone creates a new branch in the remote repository, using VSCode can not directly see the new branch. And still can't see the latest branch after clicking the pull button.
But when I manually execute command `git pull`, I see the new branch in the branch list.

I think that after clicking the pull button on any branch, the latest branch list should be synchronized from the remote repository.

Does this issue occur when all extensions are disabled?: No

**Comment by joaomoreno** [comment]
@baiyunchen When you click the pull button, we just pull the upstream branch. You should run the `Git: Fetch` command to sync with the remote.
