### ISSUE TITLE
Stabilize terminal access APIs

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#52574]
These ones seem like no brainers:

```ts
export namespace window {
	/**
	 * The currently opened terminals or an empty array.
	 */
	export const terminals: ReadonlyArray<Terminal>;

	/**
	 * An [event](#Event) which fires when a terminal has been created, either through the
	 * [createTerminal](#window.createTerminal) API or commands.
	 */
	export const onDidOpenTerminal: Event<Terminal>;
}
```

Both live share and python are using/want to use these.

**Comment by Maples7** [comment]
Great feature! 

And would it be better to `cd` to the directory of the open focus file after the terminal is launched? I am trying to write an extension to achieve this feature but do not find the activation event while a terminal is launched. So good to know this is planned.

**Comment by Tyriar** [comment]
FYI @jrieken

**Comment by Maples7** [comment]
I've published an extension to achieve the function above I mentioned.

[Terminal In Place](https://marketplace.visualstudio.com/items?itemName=Maples7.terminal-inplace)

**Comment by dziarkoaka1001** [comment]
Dzialaja należycie :)
