### ISSUE TITLE
Explore moving webcontents around when moving editors with webviews

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#5257]
I know you were waiting for it. Please don't reparent editors during slot assignment because some dom element don't survive such action. 

Related to #5039

**Comment by bpasero** [comment]
Idea is to maybe use absolute positioning (or flex layout?). Potential issues I see:
* accessibility with tab navigation will be broken if the order of elements in the DOM is different from the visual order
* layout might flicker more if the elements moved are not in order in the DOM as visually appearing (have seen this with the panel and editor area before)

**Comment by bpasero** [comment]
Electron adds support to move webcontents between webview instances (https://github.com/electron/electron/pull/7157). We should explore if this is a solution for the problem.

**Comment by mikes-gh** [comment]
In vscode 1.8 / electron 1.4.6 changing tabs back and forth still gives a new guestintance id for an open webview each time the web view is shown hidden.
AFAIK it should b e possible to keep the guestinstance id and prevent the reload now with electron update?

**Comment by bpasero** [comment]
@mjbvz fyi this might be interesting to you: https://github.com/electron/electron/pull/7157

When I played with it I could not really get it to work. Nevertheless I think https://github.com/Microsoft/vscode/issues/5257#issuecomment-210295335 applies to your solution that you picked now.

**Comment by mjbvz** [comment]
Yes we can explore using guestInstance. Accessibility seem to work using the existing absolute position approach but there are a few edge cases around positioning.

We also need to be able to keep webviews alive when their editor is no longer visible. We may be able to use a hidden webview element as a cache for this case

**Comment by mjbvz** [comment]
Blocked by https://github.com/electron/electron/issues/12251 . Out editors destroy their content before webview has a chance to transfer itself over to the new webview inside the new editor. Not sure if there is any workaround

**Comment by bpasero** [comment]
@mjbvz not sure if it makes your life easier, but with the introduction of grid layout, an editor will always stay fixed to its parent container, even if the view is moved around. Of course, in the end if the view is moved, the grid widget will still remove the element from the DOM and put it somewhere else. I am also not sure if you are still using the hack to position webviews absolutely, maybe you could test this in the grid branch (`ben/editor`).

**Comment by bpasero** [comment]
It looks like https://github.com/electron/electron/issues/12251 was closed and will not be supported with Electron 3.0.x onwards.
