### ISSUE TITLE
Files discarded via Git bash inside VS Code are still shown on Git Source Control

### ISSUE THREAD

**Issue by msaguindang** [Microsoft/vscode#52575]
VSCode Version: 1.24.1
OS Version: Windows 10

Steps to Reproduce:

1. Make changes to repo
2. Discard changes using git checkout -- <filename>
3. Run git status to check if changes were discarded

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
What is the issue?

**Comment by msaguindang** [comment]
Edited the title because it was too vague. The issue is that files are still shown on source control or when running git status.

**Comment by thismarcoantonio** [comment]
Try to run "git fetch --prune"

**Comment by msaguindang** [comment]
@thismarcoantonio I tried running git fetch --prune but it does nothing

**Comment by joaomoreno** [comment]
This seems like a lack of file events.

Did you open the root of the repository as a workspace?

**Comment by msaguindang** [comment]
Sorry for the late response. Yes, and I use the Project Manager extension to switch between projects.

**Comment by joaomoreno** [comment]
Does VS Code react to file events otherwise? If you delete a file in the Windows Explorer, does the VS Code explorer react?
