### ISSUE TITLE
DevTools broken most of the time

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#5258]
Since the electron update the dev tools almost never survive a reload. That's a major setback for development.

Steps to reproduce

* run `./scripts/code.sh`
* open dev tools, set a breakpoint, debug a little
* change the file you have just debugged in source
* refresh workbench
* breakpoints are still there but not hit anymore

**Comment by bpasero** [comment]
Seems to be https://github.com/electron/electron/issues/4842

Workaround: reload when focus is in the renderer and not dev tools

**Comment by bpasero** [comment]
Fixed with the update to Electron 0.37.6
