### ISSUE TITLE
[Accessibility]A11y_VSCode_ViewIntegratedTerminal_Keyboard: Tooltip of buttons(New Terminal,Split Terminal,Kill Terminal,Restore Panel Size)are not available on keyboard focus.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#52598]
**Environment Details:** 
VSCode Version : 1.24.0
OS Version : Win10

**Additional Details:**
Keyboard,MAS2.1.1,MAS1.1.1
**Repro Steps:**
1. Launch VS Code.
2. Go to View menu and Select Integrated Terminal.
3. Tab till the editor.

**Actual:**
Tooltip of buttons(New Terminal,Split Terminal,Kill Terminal,Restore Panel Size)are not available when navigating through keyboard.

**Expected:**
When keyboard focus goes on control and for that control if tooltip is present then on keyboard focus tooltip should appear.

**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
[https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx](url)

**User Impact:**
Keyboard only users wont get the information which are conveyed through tooltip.

**MAS Reference**:
[https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={8492c4eb-c179-40ae-8777-cd044ed725a2}](url)

**Attachment for Reference:** 

[[Accessibility]A11y_VSCode_ViewIntegratedTerminal_Keyboard.pptx](https://github.com/Microsoft/vscode/files/2123456/Accessibility.A11y_VSCode_ViewIntegratedTerminal_Keyboard.pptx)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/52016
