### ISSUE TITLE
Datei aus Outlook Email

### ISSUE THREAD

**Issue by commaender** [Microsoft/vscode#52594]
Issue Type: <b>Bug</b>

Ich bekomme regelmäßig JSON-Dateien per Email zugeschickt (Microsoft Outlook 2016, Desktop-Installation, kein Office-365). Die Dateien haben immer den identischen Dateinamen.

Wenn ich so eine JSON-Datei doppelklicke, dann öffnet sich Visual Studio Code und zeigt die Datei an. Dann verwende ich die Funktion "Dokument formatieren", um das JSON "lesbar" zu machen.
Wenn ich meine Infos rausgelesen habe, beende ich Visual Studio Code einfach mit dem "X" rechts oben, ohne die Datei explizit zu schließen.

Wenn ich nun eine ANDERE Email im Outlook öffne, und dort auch wieder die (identisch benannte) Datei im Anhang doppelklicke, dann öffnet sich wieder das Visual Studio Code, aber es wird NICHT die NEUE Datei geladen, sondern er zeigt wieder die alte, vorherige Datei an!

Visual Studio Code bekommt also scheinbar nicht mit, dass hier eine ANDERE Datei geladen werden soll, und zeigt einfach wieder irgendwas altes an...

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (8.55GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Users\Matthias Kahlert\AppData\Local\Microsoft\Windows\INetCache\Content.Outlook\GCANH2M3\ErrorData.json|
|Screen Reader|no|
|VM|33%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
xml|Dot|2.3.1
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.33
vs-code-xml-format|fab|0.1.5
csharpextensions|jch|1.3.0
vscode-nuget-package-manager|jmr|1.1.6
mssql|ms-|1.3.1
csharp|ms-|1.15.2
vscode-icons|rob|7.24.0
autoimport|ste|1.5.3

</details>

**Comment by chrmarti** [comment]
Sounds like hot-exit. You can close and reopen the file when you notice the problem. Or disable hot-exit in the settings: `"files.hotExit": "off"`

**Comment by Tyriar** [comment]
Yeah I think this is as designed, if you change the file and don't save it then it will backup and restore the changes when you next load it.

**Comment by commaender** [comment]
Sorry for writing the posting in German instead of English :-)

I still think, it is a bug...

For better understanding: I regularly receive emails with a JSON file attached. The JSON file always has the same filename, but different contents.
When I double click the attachment of mail (A) in Outlook 2016, the JSON file is opened in VS Code. Then I right-click in VS Code to format the JSON to a readable format. When I finished checking the file, I simply close the VS Code editor.

Then, in Outlook, I select the next email, with a _different_ JSON file, double-click that, VS Code starts, but it doesn't load the new and different file that I double-clicked, it shows the file that had been viewed before.

That's very mis-leading, I would expect to see the file that I double-clicked, and not the file that I viewed hours ago...

**Comment by Tyriar** [comment]
@commaender what are the file paths that show when you mouse over the tab of the first and the second files?

**Comment by commaender** [comment]
File path shown is:
C:\Users\Matthias\AppData\Local\Microsoft\Windows\INetCache\Content.Outlook\GCANH2M3\ErrorData.json (that's the filename of the attachment)

It seems, that Outlook always saves the attachment in the same directory with the same filename, overwriting the previously viewed attachment.

In my opinion: When VSCode keeps a file opened, it should be able to determine if it is still the same file, or if it has been modified since VSCode was last run. It notepad++ for example it asks the user if the file should be reloaded.

**Comment by Tyriar** [comment]
> It seems, that Outlook always saves the attachment in the same directory with the same filename, overwriting the previously viewed attachment.

This behavior is expected currently then. 

> In my opinion: When VSCode keeps a file opened, it should be able to determine if it is still the same file, or if it has been modified since VSCode was last run.

This is tracked in https://github.com/Microsoft/vscode/issues/15749
