### ISSUE TITLE
[Accessibility][Usability]A11y_VSCode_ViewSearch_ScreenReader: Keyboard focus order is inappropriate as it lands directly on "Search field" which may lead screenreader users to miss few controls.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#52609]
**Environment Details:**
VSCode Version : 1.24.0
OS Version : Win10

**Additional Details:**
Issue Type : Usability

**Repro Steps:**
1. Launch VS Code.
2. Navigate to Activity Bar and select "Search"(Cntrl+Shift+F) button.
3. Observe keyboard focus order for screenreader users.

**Actual:**
Keyboard focus directly lands on "Search" field and screenreader users will not come to know about few controls like "Toggle Replace" , "Clear", "Collapse All", "Refresh" buttons.

**Expected:**
Keyboard focus should directly land on first interactive element on screen.

**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx

**User Impact:**
Screenreader users will not be able to know that there are few controls present (accessed using Shift+ Tab) on the screen and may miss the functionality present.

**Attachment For Reference:**
[A11y_VSCode_ViewSearch_Usability_FocusOrderIssue.pptx](https://github.com/Microsoft/vscode/files/2123736/A11y_VSCode_ViewSearch_Usability_FocusOrderIssue.pptx)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
> Keyboard focus should directly land on first interactive element on screen.

I disagree. Those buttons are rarely used. 99% of the time when a user goes to the search viewlet, they need to type in the search field.
