### ISSUE TITLE
Characters missing automatically while writing C++ code

### ISSUE THREAD

**Issue by RMyang** [Microsoft/vscode#52612]
VS Code Version: 1.24.1
OS Version: Windows 10

I was confused when I tried to write C++ codes using VS Code. For example, after I wrote “int a=6;”, some characters missed automatically like below:
![1](https://user-images.githubusercontent.com/17923170/41719199-ec85277a-7591-11e8-8707-2bba525022a2.png)
Sometimes, the code line turned to "int = 6;", and sometime the codes didn't go wrong after enter ";".
Would someone please tell me why it happened, and how can I fix it? Thanks!

These are the extensions I installed:
![2](https://user-images.githubusercontent.com/17923170/41722408-0cd81bc8-759b-11e8-8d1d-5167b477ef95.png)
This is my settings:
![3](https://user-images.githubusercontent.com/17923170/41722417-1a389d42-759b-11e8-9fbd-f1fe7028f076.png)

**Comment by chrmarti** [comment]
This issue was moved to Microsoft/vscode-cpptools#2162
