### ISSUE TITLE
Allow triggering quick fixes from problems view

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#52627]
**Feature request**
Provide a way to trigger a quick fix from the problems view.

For example, for the javascript:

```js
//@ts-check
class Abc {}

new AbC()
```

A quick fix is available:

<img width="431" alt="screen shot 2018-06-21 at 10 27 07 am" src="https://user-images.githubusercontent.com/12821956/41735124-b1dbb084-753d-11e8-808c-0ac1a0842076.png">

But this is not shown or indicated in the problems view:

<img width="814" alt="screen shot 2018-06-21 at 10 27 58 am" src="https://user-images.githubusercontent.com/12821956/41735164-cd366cac-753d-11e8-9980-02852532db74.png">

Additionally, when you click on the problems entry, the editor is not focused so you cannot use a keyboard shortcut to trigger the quick fix

**Comment by sandy081** [comment]
Following are the quick fixes when shown in problems view.

![image](https://user-images.githubusercontent.com/10746682/42640781-55b57274-85f3-11e8-956f-6824d14ac165.png)

![image](https://user-images.githubusercontent.com/10746682/42640795-5daa35dc-85f3-11e8-9579-f41c471c5e72.png)

Let me know if it makes sense 

@jrieken FYI

**Comment by jrieken** [comment]
I like it. This is per error/warning, right? Per file we could offer source actions, like orga-imports et al.

**Comment by sandy081** [comment]
Yeah it is per marker. Sure, we can offer source actions and may be also fix all action on file.

**Comment by kieferrm** [comment]
@sandy081 do I see when quick fixes are available without opening the context menu?

**Comment by sandy081** [comment]
@kieferrm No, you don't. 
But is not it intuitive to find fixes from context menu in problems view.

Otherwise, we can show overlaid light bulb icon on top of error/warning icon?

**Comment by kieferrm** [comment]
@sandy081 that's something we should experiment with.

**Comment by jrieken** [comment]
> Otherwise, we can show overlaid light bulb icon on top of error/warning icon?

Maybe on select/hover?

**Comment by sandy081** [comment]
On select might inline with editor

**Comment by sandy081** [comment]
I think Source Actions are not a good fit as they are nothing to do with diagnostics.
