### ISSUE TITLE
Can't get lightbulb to show up when clicking on green squiggle.

### ISSUE THREAD

**Issue by jaynadeau** [Microsoft/vscode#52625]
Issue Type: <b>Bug</b>

When I click on a green squiggle to fix includes I do not get the lightbulb showing up.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1607 v4 @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (14.04GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
svn-scm|joh|1.29.5
cpptools|ms-|0.17.4
partial-diff|ryu|1.1.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Please share some example code and steps to reproduce the issue

**Comment by jaynadeau** [comment]
Steps:
1. open a C++ file
2. click on green squiggly line - no lightbulb

There is no real example code, im just clicking on an include file and was trying to add it to my include path but there is no lightbulb.
This happened to me on another machine and was intermittent. I do not know under which circumstances the lightbulb does not show up, but in this particular install I don't seem to be able to get the lightbulb at all, so not intermittent on this machine.

**Comment by mjbvz** [comment]
Please file this issue against the c++ extension. They provide the squigglies and the quick fixes
