### ISSUE TITLE
Explore update to Electron 3

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#52629]
**VSCode Exploration Builds with Electron 3.0.x:**
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/45498d93166483c2eff886e28f8dab915ae382fc/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/code-exploration_1.28.0-1538127308_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/VSCodeUserSetup-x64-1.28.0-exploration.exe)

**Comment by Tyriar** [comment]
Issues so far:

- node-pty needs `nan` updated
- vscode-nsfw needs `nan` updated

**Comment by Tyriar** [comment]
@bpasero you'll need to re-release https://github.com/bpasero/fsevents in order to pick up nan@2.10.0

**Comment by bpasero** [comment]
@Tyriar is that a change compatible with older Electron versions or do we need a specific release only for Electron 3.x?

**Comment by Tyriar** [comment]
@bpasero it's compatible, the latest insiders is using nan@2.10 for node-pty.

**Comment by bpasero** [comment]
@Tyriar we might have to fork NSFW, I do not think that project is active anymore...

**Comment by bpasero** [comment]
@Tyriar I published `vscode-chokidar@1.6.3` to try with

**Comment by Tyriar** [comment]
We already forked nsfw to vscode-nsfw to release https://github.com/Axosoft/nsfw/pull/47 (repo: https://github.com/Tyriar/nsfw/tree/vscode-release)

**Comment by bpasero** [comment]
@Tyriar I pushed https://github.com/Microsoft/vscode/tree/electron-3.0.x that compiles. There are some serious issues I have not looked into, e.g. I cannot save files for some reason.

**Comment by bpasero** [comment]
I believe that one could be due to https://github.com/nodejs/node/issues/2006

**Comment by Tyriar** [comment]
A lot of errors in the terminal running code.sh coming from devtools:

![image](https://user-images.githubusercontent.com/2193314/42888975-36248c32-8a5e-11e8-86b1-c08a6e63c58f.png)

**Comment by Tyriar** [comment]
Saving actually does work, the first time at least. It just doesn't lose the circle indicator and then after that lots of things seem to be broken, like I cannot close the window via custom menu bar and ctrl+r doesn't work to reload.

**Comment by bpasero** [comment]
@Tyriar can you make a branch on `vscode-nsfw` for the NAN update? I am not even sure which GitHub repo that would be?

Would be cool to get a build with Electron 3 running for next weeks Electron hackathon ⭐️

**Comment by bpasero** [comment]
@rebornix @alexandrudima is this V8 change something we need to change in our code? I remember we once did changes around this where we assume a certain max string length:

![image](https://user-images.githubusercontent.com/900690/43911392-a32309dc-9bff-11e8-94f4-b45668da99e4.png)

(via https://v8project.blogspot.com/2017/09/v8-release-62.html)

**Comment by Tyriar** [comment]
Looks like the xterm.js parser is firing layouts in the scroll bar code in Ch66 (not in 58 or 61):

<img width="636" alt="screen shot 2018-08-09 at 11 48 58 am" src="https://user-images.githubusercontent.com/2193314/43919300-5d123ef2-9bca-11e8-9b6b-4c7680ad3ffa.png">

**Comment by Tyriar** [comment]
Actually this is happening in 58 and 61, it's just way faster:

<img width="501" alt="screen shot 2018-08-09 at 11 50 50 am" src="https://user-images.githubusercontent.com/2193314/43919348-822eb918-9bca-11e8-9544-3978db4379a7.png">

Slow layouts is something we should look out for. I can look into fixing this in xterm.js as this should only be happening when a frame is rendered.

**Comment by bpasero** [comment]
Fyi I got NSFW working now, looks like another change for Node 10 compatibility is needed: https://github.com/bpasero/vscode-nsfw/commit/2c0ff39a2f5157fee04e407014026123e4bd3295

**Comment by bpasero** [comment]
We have our first VSCode exploration builds out (see description of the issue for download links).

**Comment by EbXpJ6bp** [comment]
Some function does not work in electron 3.0:
- Process explorer,  Runnning processes section (in issue reporter) and Workspace metadata section ( in issue reporter) are blank
- `code-exploration --status` dose not work with follwing error

```
(node:47356) UnhandledPromiseRejectionWarning: #<Object>
(node:47356) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:47356) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I am looking forward to vscode getting better by updating to electron 3.0!

**Comment by bpasero** [comment]
@EbXpJ6bp yeah good catches, I see that windows-process-tree somehow fails to load. Probably a build failure related to the node 10 update.

**Comment by bpasero** [comment]
@EbXpJ6bp should be fixed with [download](https://az764295.vo.msecnd.net/exploration/acdabe28fb63ed8b3bdd9ba685bfe595c2daf750/VSCodeUserSetup-x64-1.27.0-exploration.exe).

**Comment by EbXpJ6bp** [comment]
@bpasero thanks! With the latest build, it is working.

**Comment by Tyriar** [comment]
Electron 3 doesn't have the slow canvas render issues (workaround `--ignore-gpu-blacklist`) that i see in 2 on my Linux box :tada:

**Comment by mikaelsouza** [comment]
I've been experiencing some performance issues with scrolling on VS Code 1.26.1 (and earlier) and this version using electron 3 seems to be a lot better. 

I hope we get it to the main VS Code soon!

**Comment by nealot** [comment]
Electron 3.0 fixed https://github.com/Microsoft/vscode/issues/56189 for me. :tada: Hopefully it can be merged soon.

**Comment by shamiln** [comment]
@bpasero What beta build of Electron have you integrated in the current download links in the original post?

**Comment by bpasero** [comment]
@shamiln the links are probably a bit outdated, I can update them (though on macOS and Windows you will get auto-updated). The latest is: Electron `3.0.0-beta.10`

**Comment by pixieaka** [comment]
Every time i open setting as json file.

![capture](https://user-images.githubusercontent.com/17777237/45422447-818f5400-b690-11e8-9363-aff76e99828f.JPG)

**Comment by bpasero** [comment]
@pixieaka yeah I reported this, should be fixed soon (@dbaeumer @aeschli )

**Comment by xiaotan0305** [comment]
mac os All extensions failed to start
![image](https://user-images.githubusercontent.com/12965330/45462168-4301a400-b739-11e8-8e56-97759d4013ed.png)
![image](https://user-images.githubusercontent.com/12965330/45462282-b99ea180-b739-11e8-9048-bc802020a9a1.png)

**Comment by bpasero** [comment]
I am not seeing that, weird. There will be a new build in a moment. Let me know if that changes anything.

**Comment by rebornix** [comment]
Electron 3 uses Nodejs 10, which ships the new ABI stable API for native modules NAPI, so I played with node-spellchecker and ported it to NAPI https://github.com/rebornix/napi-spellchecker . Now when writing extensions using napi-spellchecker, it will never break or throw errors/warnings when the node version doesn't match.

I ran extensions with napi-spellchecker on current Insiders (which is using Node < 10) and the extension still works but throws warning about the usage of experimental API.

We may want to use NAPI if possible one day and then we don't need to worry about node version change any more like https://github.com/Microsoft/vscode/issues/52629#issuecomment-399194181 . It can help with our OSS experience as well. We can now recommend extension authors to use NAPI if they want to improve the performance by leveraging native modules.

**Comment by corbinu** [comment]
@rebornix If your going to recommend authors can now use use NAPI to improve performance. Would it be also reasonable to note that Node 10 as stable support for WASM so they can also use WASM to get similar benefits: https://github.com/rustwasm/wasm-pack

**Comment by rebornix** [comment]
@corbinu definitely, wasm is another good solution to improve the performance and it has its special benefits 

* broader language support
* OS independent

The second advantage above can be seen as disadvantage as it can't support talking to the system but it's up to extension authors which one to use. Thanks!

**Comment by pixieaka** [comment]
Electron 3.0.2 1.29.0 Exploration ( user setup )
Error 1
![capture](https://user-images.githubusercontent.com/17777237/46329921-c57ed480-c610-11e8-883b-5bb96e21c349.JPG)

Error 2
![capture2](https://user-images.githubusercontent.com/17777237/46329961-d29bc380-c610-11e8-8731-ab0512832e04.JPG)

**Comment by bpasero** [comment]
@pixieaka yeah, extra points if someone can find out which code is triggering Error1. The second error is expected because we have not released release notes for 1.29 yet.

**Comment by pixieaka** [comment]
Electron 3.0.2 1.29.0 Exploration ( user setup )
----------------------------------------------------------------
Error 1
------------------------------
![capture](https://user-images.githubusercontent.com/17777237/46330067-640b3580-c611-11e8-9161-e07c2e2e9635.JPG)

Error 2 [ Note: When I press Release Notes from about it open web page in my default browser ]
------------------------------
< https://go.microsoft.com/fwlink/?LinkId=724002 >

Then redirect to

< https://github.com/Microsoft/vscode/wiki/Insiders-Release-Notes >

![capture2](https://user-images.githubusercontent.com/17777237/46330074-6c637080-c611-11e8-8725-f10bd0bddf6a.JPG)

**Comment by pixieaka** [comment]
![capture](https://user-images.githubusercontent.com/17777237/46484207-95def080-c7f9-11e8-85ab-a65dd343a965.gif)

**Comment by Tyriar** [comment]
@pixieaka it's a regression in Windows that we can't do anything about unfortunately https://github.com/Microsoft/vscode/issues/57803

**Comment by jens1o** [comment]
@Tyriar so, it is impossible that a Microsoft team urges another Microsoft team to fix a bug?

ok.

**Comment by Tyriar** [comment]
@jens1o Windows is enormous and has a complex release process as a result, it was too late when it was discovered to do a fix.

**Comment by jens1o** [comment]
@Tyriar Please further delay the rollout of Electron 3, so then I'm already on Linux. Thank you.

There is no chance this will be handled in like the next sprint of Windows?

**Comment by pixieaka** [comment]
Some errors in 1.29.0 -- 2018-10-03 | Electron: 3.0.2
![annotation](https://user-images.githubusercontent.com/17777237/46560407-f18da480-c8f3-11e8-845d-e51324661ce1.png)

**Comment by graph** [comment]
on linux if you click on settings->update it links to the insiders build which doesn't use electron 3.

**Comment by graph** [comment]
I see. I like the package manager approach. PPA should be the main instructions on the website for linux. The update to insiders confused me I thought it was renamed.

using the exploration update it feels that the scrolling issue I had is fixed in electron 3. I've been using all versions stable, insiders, and exploration on windows & linux. I only had it happen on stable & insiders weird scroll jumps. In the latest version of stable on linux even though it's electron 2 it happens much less frequently now.

**Comment by Tyriar** [comment]
@graph when you install the deb from the website it should install the repo as well.

**Comment by aayushbisen** [comment]
Are these __exploration__ builds official ?

**Comment by bpasero** [comment]
@aayushbisen they are manually released but should be similar to our insider builds. not as stable as "stable", but I for example use them everyday since 2 months for development.

**Comment by pixieaka** [comment]
@bpasero Why this ??
![image](https://user-images.githubusercontent.com/17777237/47709721-953f4b80-dc39-11e8-8322-3bb2b30d62fd.png)

**Comment by bpasero** [comment]
@pixieaka we will have to hunt down node modules we depend on that use the deprecated buffer constructor and update.

**Comment by danilaml** [comment]
It's almost time to start exploring Electron 4 😄

**Comment by loligans** [comment]
Is there somewhere I can get the latest exploration build. I'd like to test out vscode in electron 3.0

**Comment by compilenix** [comment]
I don't think so, yet.

But you can build it from source [How-to-Contribute#build-and-run](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run).

**Comment by dalDevelo** [comment]
For real? There are 3 links in the original post with download links to the exploration build, depending on your OS 😳

**Comment by compilenix** [comment]
Sorry @dalDevelo , i assumed that @loligans already saw that and is not running on an OS using `dmg`, `exe` or `deb` packages. I.e. have Fedora which wants a `rpm` package.

**Comment by dalDevelo** [comment]
@compilenix. Thanks for clarifying, your response makes sense now. It's perhaps best if @loligans states his exact requirements in his post, to avoid assumptions and...in my case, confusion.

Ty

**Comment by bpasero** [comment]
> It's almost time to start exploring Electron 4 😄
Yes: https://github.com/Microsoft/vscode/issues/61787

**Comment by pvh** [comment]
Is Electron 3 expected to be ready for the November release or not until February? I'm trying to decide whether to backport a fix in a module I use (which I will do if Electron 3 is Feb+) or just wait for the next release.

**Comment by bpasero** [comment]
@phv Q1 2019

**Comment by pvh** [comment]
Thanks, I'll backport. Not a big deal.

(PS: Improved support for binary dependencies would be welcome and I know you're tracking that elsewhere.)

**Comment by bpasero** [comment]
Merged to master for our release early February 2019. Should be available in insiders end of week.

**Comment by akmittal** [comment]
Electron 4 is released, https://electronjs.org/releases#release-notes-for-v400

**Comment by bpasero** [comment]
Already builds available: https://github.com/Microsoft/vscode/issues/61787
