### ISSUE TITLE
Git settings missing

### ISSUE THREAD

**Issue by wwlorey** [Microsoft/vscode#52626]
Issue Type: <b>Bug</b>

Git settings are missing from User Settings. 

![image](https://user-images.githubusercontent.com/22795803/41733115-85a8ebac-7548-11e8-97e5-af88b4bd0de2.png)

Only gitlens settings are displayed and giving `getlens.advanced.git` a path to `git.exe` did not resolve the issue.

Also, the Source Control tab displays "There are no active source control providers."

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.16299

<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.19.1
gitlens|eam|8.4.1
vsc-material-theme|Equ|2.1.0
cpptools|ms-|0.17.4
vim|vsc|0.13.1

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
If you open <kbd>F1</kbd>, `Developer: Toggle Developer Tools`, is there any error in the console?

And does <kbd>F1</kbd>, `Developer: Show Running Extensions` show the Git extension there?

**Comment by wwlorey** [comment]
There aren't any errors in the console and the only Git related extension running is GetLens.

**Comment by joaomoreno** [comment]
Interesting. If you download our [ZIP release](https://vscode-update.azurewebsites.net/latest/win32-x64/stable) and run Code from there... does Git work?

**Comment by wwlorey** [comment]
Still no Git options after downloading that release.

**Comment by joaomoreno** [comment]
Doesn't make much sense 🤔 

How about if you run with a fresh new user app data? `code --user-data-dir SOMEFOLDER`

**Comment by wwlorey** [comment]
That did the trick! There are Git settings and the Source Control tab populates.

**Comment by joaomoreno** [comment]
Can you ZIP up your usual user data dir and send me that to jomo @ microsoft dot com?
