### ISSUE TITLE
Can’t disable typescript pop-up

### ISSUE THREAD

**Issue by kirkstrobeck** [Microsoft/vscode#52622]
- Related to https://github.com/Microsoft/vscode/issues/28380
- Here are my settings https://gist.github.com/kirkstrobeck/c6175de8e883c382623efaccbca98335
- Insiders @ c5c7d43b65bcbbb3851fbd972fad077631c707e3

<img width="1085" alt="screen shot 2018-06-21 at 08 10 35" src="https://user-images.githubusercontent.com/241963/41727999-9a205ce6-752a-11e8-853e-5b097a2f8667.png">

Create `.js` file with the following contents

```
module.exports = () => {}
```

**Comment by mjbvz** [comment]
Set `"javascript.suggestionActions.enabled": false` to disable these

**Comment by kirkstrobeck** [comment]
Still getting some, like `[ts] Expression expected` -- My settings gist is updated for reference.

**Comment by mjbvz** [comment]
To disable all hovers, set `"editor.hover": false`

To disable all javascript syntax validation, set `"javascript.validate.enable": false`

**Comment by kirkstrobeck** [comment]
Thank you!
