### ISSUE TITLE
Double curly braces on import statements

### ISSUE THREAD

**Issue by farlock85** [Microsoft/vscode#52624]
- VSCode Version: 1.25.0-insides
- OS Version:

Steps to Reproduce:

1. Paste this line in VS Code: import { something } from 'library-name'
2. It will show up like this:
![image](https://user-images.githubusercontent.com/1142915/41728606-6b71f850-7534-11e8-8439-0ff684d9e65e.png)

The actual file doesn't have the double curly braces.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Duplicate of #52196
