### ISSUE TITLE
"Adjust imports" feature needlessly adjusts non-relalative imports

### ISSUE THREAD

**Issue by arackaf** [Microsoft/vscode#52630]
- VSCode Version: 1.24.1
- OS Version: Windows 10

Steps to Reproduce:

1. Rename a file's extension (or probably just a file)
2. Click yes to adjust imports

EVERY import with a non-relative path, ie "app/util/foo" is now updated to be relative, ie "../../../aoo/util/foo" 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/Microsoft/TypeScript/issues/25132 to tack this upstream

Let me know if that issue doesn't capture the bug you were seeing

**Comment by arackaf** [comment]
That’s perfect - thanks!
