### ISSUE TITLE
VS Code debugger does not accurately return env variables that include '$' symbol 

### ISSUE THREAD

**Issue by koberlag** [Microsoft/vscode#52637]
Issue Type: <b>Bug</b>

I am using VSCode to run python 3.6 with Flask 1.0.2 and the dotenv extension. The issue occurs when using the Flask debugger. The flask debugger configuration is as below:

 {
            "name": "Python: Flask (0.11.x or later)",
            "type": "python",
            "request": "launch",
            "module": "flask",
            "env": {
                "FLASK_APP": "app.py"
            },
            "args": [
                "run",
                "--no-debugger",
                "--no-reload"
            ]
},

I am not certain that this is a VSCode issue, but it occurs when debugging in VSCode, but not when executing 'Flask run' in the terminal.

Using a .env file I have a variable such as:

MY_VARIABLE='Thi$isTheValue'

dotenv will set the variables from the .env file on startup.

The issue can be seen when trying to access the variable's value with os.getenv, such as in a configuration settings file.

import os
my_var_value = os.getenv("MY_VARIABLE")

When trying to access a variable that has a '$' symbol when running the debugger the value is not returned accurately. Sometimes the '$' symbol is removed, or sometimes it will remove everything after the '$' symbol.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (6.78GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.18.0
vscode-docker|Pet|0.0.27
html-css-class-completion|Zig|1.17.1
vscode-eslint|dba|1.4.12
dotenv|mik|1.0.1
python|ms-|2018.6.0
csharp|ms-|1.15.2
debugger-for-chrome|msj|4.6.0
heroku-command|pko|0.0.8
codebucket|pst|0.2.0

</details>

**Comment by weinand** [comment]
Please file this against the Python extension you are using.
