### ISSUE TITLE
Add cli option to run launch script

### ISSUE THREAD

**Issue by rsweetland** [Microsoft/vscode#52636]
It would be nice if the `code` cli could accept an argument to run a launch script.  For example... 

```code --launch "Launch Program"```

...where "Launch Program" is a pre-configured command in launch.json.

A one-line command like ```code --launch "Launch Server" ./api-server &&  code --launch "Launch Client" ./api-client"``` could then be used to orchestrate dev environments for microservice-based projects.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/10979
