### ISSUE TITLE
Custom select box should only fire onDidSelect when a change happens

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#52632]
From https://github.com/Microsoft/vscode/issues/50249#issuecomment-398734938

The custom select box fires its onDidSelect event anytime it blurs, but I want to know whether the user changed the selection, or dismissed it without selecting anything.

https://github.com/Microsoft/vscode/blob/3b798fd805b0ae31090dcac15063b8d49f4e3862/src/vs/base/browser/ui/selectBox/selectBoxCustom.ts#L564

The native select box only fires 'change' when an element was selected, even if it's the same element that was already selected.

**Comment by cleidigh** [comment]
@roblourens 
@bpasero 
For clarification:
Is the desired behavior for the select box widget to generate the onSelect event after any user movement
of the selected item? We made the decision to not fire the event until the select box is either closed
with an active selection or there is a blur based upon mouse moves.  If we generate an event on any intermediary selection change then we do not have a way to distinguish the selection from a blur.

I would think we would have to always change the selection even if we blur out of the select box without an active selection (pressing the Enter key or clicking the mouse)

FYI the control of the event handling has some differences where some things cannot be intercepted on the native select box.

**Comment by roblourens** [comment]
Yeah I agree that it shouldn't fire an event for intermediate changes while the control is open. It should fire at the same times it does now, but only when the selected value actually changes. If I open the dropdown, and click the element that's already selected, it should not fire.

**Comment by cleidigh** [comment]
@roblourens 
Cool.  I think that works, should be no problem.  
I will do the tweak.

**Comment by roblourens** [comment]
Thanks!

**Comment by cleidigh** [comment]
@roblourens 
HeadsUp:
  I found an odd selected option sync issue when changing event fire , have to address this
before changing the event handling.

**Comment by cleidigh** [comment]
Fixed With: #53627
