### ISSUE TITLE
Debugger window local variable this is undefined in arrow function 

### ISSUE THREAD

**Issue by dtoki** [Microsoft/vscode#52635]
An arrow function's `this` in the debugger window reports/displays `undefined`. However, a `console.log(this)` from inside the arrow function does not yield `undefined` in the console output.

### System Details

- VSCode Version: 1.24.1
- OS Version: macOS 10.13.5
- Node.js Version: 6.9.5

### Steps to Reproduce:

1. Simple [script][1] to reproduce issue
2. Set a breakpoint on line 8 and line 23.
3. Launch a Node.js debug instance on the script, and step through until the breakpoint reaches the body of the arrow function.
4. Expand local tab in debug window and you'll see `this: undefined`

### Expected behaviour
`this` in  the local variable debug tab should be `Automobile {type: "suv", year: 2012, mph: 200}`

Does this issue occur when all extensions are disabled?: Yes

[1]: https://gist.github.com/dtoki/0895111da239c8f28e7f0e8f5dc96940

### Pictures:
![screen shot 2018-06-21 at 11 34 57 am](https://user-images.githubusercontent.com/7953527/41738818-f4a4d1a2-7547-11e8-804f-cf2f03010b0a.png)
![screen shot 2018-06-21 at 11 35 30 am](https://user-images.githubusercontent.com/7953527/41738822-f6e550cc-7547-11e8-8dfb-f91630f2d46b.png)

**Comment by roblourens** [comment]
This is a limitation in Node, I see the same when debugging with Chrome devtools. It works in Node 10 though

![image](https://user-images.githubusercontent.com/323878/41747976-bdc81d66-7564-11e8-97bd-71141848bdf5.png)
