### ISSUE TITLE
Don't re-open editor when switching side-bar tabs

### ISSUE THREAD

**Issue by jacobweber** [Microsoft/vscode#52638]
Start with an open project but no open files. If I click a file in Explorer to open it, then close the editor, the file will remain selected in Explorer (that's fine).

Then if I switch to another tab, like Extensions, and switch back to Explorer, it will re-open the selected file.

This seems wrong; it should leave the editor closed.

**Comment by isidorn** [comment]
I can not reproduce this. Can you reproduce using vscode insiders?
https://code.visualstudio.com/insiders/
if yes, can you please attach a short video / gif demontrating this?

**Comment by yume-chan** [comment]
I can reproduce it with my insiders version:

````
VS Code version: Code - Insiders 1.25.0-insider (b7e6e04666ca8dde560b69081c43365dce77d12a, 2018-06-22T05:17:08.689Z)
OS version: Windows_NT x64 10.0.17134
````

When I saw the op says 

>then close the editor, the file will remain selected in Explorer

I realize they have `"explorer.autoReveal": false` in their settings.

Steps:

1. Close all files
1. Open a file from explorer
2. Close it
3. Hide sidebar
4. Click the explorer icon to open the sidebar

And the selected file is opened again.

![1](https://user-images.githubusercontent.com/1330321/41771537-13e21aba-7648-11e8-8906-042a0326804a.gif)

**Comment by isidorn** [comment]
@jacobweber thanks, I also see this behavior it was just not clear from your original comment.
However this behavior is designed and we do it explicitly [here](https://github.com/Microsoft/vscode/blob/2ae783aebe5a8c9bdddddbcb6dccbdedd166e348/src/vs/workbench/parts/files/electron-browser/views/explorerView.ts#L309)

I feel like this is user preference and we would add an option to disable this only if more users complained.
@bpasero can also share why he originaly did this.

**Comment by jacobweber** [comment]
Thanks @yume-chan — you're right that I do have `"explorer.autoReveal": false`. Maybe it would make sense to disable this behavior if that setting is false? It seems to only make sense when it's true.

**Comment by waynebloss** [comment]
More complaints:

- https://stackoverflow.com/questions/50181866/prevent-vscode-from-re-opening-selected-file-when-switching-back-to-explorer

- https://github.com/microsoft/vscode/issues/75181
