### ISSUE TITLE
Font Family Not Changing in Editor Text

### ISSUE THREAD

**Issue by MarkPhillips** [Microsoft/vscode#52631]
I am on Windows 10 and have changed font-family in User Settings as follows:    

"editor.fontFamily": "Verdana"

Unfortunately, this change does not effect existing .html, .ts, .js files.  The still appear in serif font and not Verdana. 

Thanks,
Mark

**Comment by chrmarti** [comment]
@MarkPhillips Which version of VS Code is this?

**Comment by alexandrudima** [comment]
@MarkPhillips Did you save the `settings.json` file? Does this reproduce for any font family?

**Comment by MarkPhillips** [comment]
Hi.  I am using Version 1.24.1 and yes I did save settings.json file.  I also tried Arial and got the same result.  I checked Windows 10 the laptop fonts and both Verdana and Arial are installed.

**Comment by alexandrudima** [comment]
@MarkPhillips Can you please follow precisely these steps and let me know if it works for you. Perhaps you have opened a folder or a workspace which overrides the font family with a different value?


* Open New Window
* Open User Settings
* Change "editor.fontFamily"
* Save

![kapture 2018-06-26 at 11 28 37](https://user-images.githubusercontent.com/5047891/41902603-29bd6774-7934-11e8-940a-caa9c6c7fd23.gif)

**Comment by MarkPhillips** [comment]
Hi Alexandru,

The changes began working yesterday, prior to receiving your email.  Not
sure why exactly.  I had disabled some extensions while trying to clear up
other issues.  Unfortunately, I do not remember which ones.

Thanks for your time,
Mark
