### ISSUE TITLE
Non-standard ascii character changed to unicode � in ANSI file

### ISSUE THREAD

**Issue by inarius** [Microsoft/vscode#52642]
Issue Type: <b>Bug</b>

This seems related to issue #34652. In my instance, rather than displaying a unicode character incorrectly, VS Code fails to display a regular ANSI character which is outside the basic ASCII set. The character I had trouble with was '¥' (0xA5).

As in the above issue, VS code saves the question mark character and overwrites the ANSI character. It saves the question mark character (�) in unicode, which is interpreted as three characters instead of one inside other applications that only read ANSI.

Here are some example text files:
- [before-vscode.txt](https://github.com/Microsoft/vscode/files/2125437/before-vscode.txt)
- [after-vscode.txt](https://github.com/Microsoft/vscode/files/2125438/after-vscode.txt)

VS Code version: Code - Insiders 1.25.0-insider (7dc9539a421c9c33e57e2ce0b718f183bb44c756, 2018-06-15T05:17:41.405Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|A8-7A8-7650K Radeon R7, 10 Compute Cores 4C+6G  (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|14.94GB (4.78GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
gc-excelviewer|Gra|2.1.23
rainbow-csv|mec|0.4.2
mssql|ms-|1.3.1
vscode-spotify|shy|2.4.0

</details>

**Comment by svenax** [comment]
The default setting for VS Code is to treat all files as UTF-8. If that's not what you want, you can change the default encoding by setting `files.encoding` to e.g. `windows1252`. Or, you can set `files.files.autoGuessEncoding` to `true`.

**Comment by alexandrudima** [comment]
@Tyriar opening/saving a file from disk and related encoding issues should be assigned to @bpasero

**Comment by bpasero** [comment]
VS Code supports a wide range of file encodings. You can see the full list when you click on the lower right status bar where the encoding is shown and then choose to either reopen the file with a specific encoding or save the file with a specific encoding:

![image](https://user-images.githubusercontent.com/900690/33760971-db202986-dc07-11e7-8ca0-f8d8938cef7f.png)

There are two options how to configure the encoding for files

**Configure the encoding as a setting for all files or files of specific type**
We provide a `files.encoding` setting that you can use to set an encoding for all files. You can also configure this encoding for specific file types, e.g. like this:

```json
"[markdown]": {
    "files.encoding": "utf8"
}
```

**Configure VS Code to automatically detect the encoding when opening files**
We provide a `files.autoGuessEncoding` setting that you can enable to let VS Code detect the encoding of every file automatically. Note that this approach is known to not be accurate in all cases. This guessing of encoding is rather a heuristic that can produce wrong results (that is also why this setting is not enabled by default).

Please also check out issues that are already reported with the `files-encoding` label: https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afile-encoding

**Comment by WorldofBay** [comment]
great idea to provide the issue as a solution to itself.

first not every file with the same filetype has the same encoding and there usually is no way to differ between them by filename regexes.

second the `files.autoGuessEncoding` guesses UTF-8 for a lot of ANSI files and if you aren't aware of that little encoding label in the bottom right all the time vs code will change your files (and maybe break code) without even telling you so.

i don't want to set all filetypes that could posssibly ever contain an ANSI file with non-ascii characters to ANSI. that would avoid the silent normalization but some test will be unreadable.

note that the big problem is the **silence**. without a diff tool it is impossible to recognize.
