### ISSUE TITLE
error updating 06212018

### ISSUE THREAD

**Issue by grhartt** [Microsoft/vscode#52644]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Update last release with recent release
2. Currently have powershell, t-sql and Power Query M extensions enabled

error stated to open new issue and attached log
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2125515/vscode-inno-updater.log)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
You seem to have #47841.

Please read this comment if you can provide more detail: https://github.com/Microsoft/vscode/issues/47841#issuecomment-393101777

Please read this one to disable background updates: https://github.com/Microsoft/vscode/issues/47841#issuecomment-395017687
