### ISSUE TITLE
Emmet > Wrap Individual Lines With Abbreviation erases $1

### ISSUE THREAD

**Issue by marc-learning** [Microsoft/vscode#52640]
Issue Type: <b>Bug</b>

#### Applying the *Emmet > Wrap Individual Lines With Abbreviation* to text that contains a ```$1``` or ```$2``` erases the $ character and first digit after it.

For instance, we would expect  *Emmet > Wrap Individual Lines With Abbreviation* with a *p**, when applied to this text:
```
more than $ billion in proceeds
more than $x billion in proceeds
more than $1 billion in proceeds
more than $2.1 billion in proceeds
```
to produce this result:
```
<p>more than $ billion in proceeds</p>
<p>more than $x billion in proceeds</p>
<p>more than $1 billion in proceeds</p>
<p>more than $2.1 billion in proceeds</p>
```
but actually it produces this unexpected result:
```
<p>more than $ billion in proceeds</p>
<p>more than $x billion in proceeds</p>
<p>more than  billion in proceeds</p>
<p>more than .1 billion in proceeds</p>
```
**The ```$1``` and ```$2``` characters are unexpectedly erased!**

The interim, preview state of the text, before committing the change, looks like this:
```
<p>more than \$ billion in proceeds</p>
<p>more than \$x billion in proceeds</p>
<p>more than | billion in proceeds</p>
<p>more than |.1 billion in proceeds</p>
```
![screen shot 2018-06-21 at 4 37 00 pm](https://user-images.githubusercontent.com/38844167/41746301-d27fc6a6-7577-11e8-8e60-55d30030cb75.png)

The ```$1``` and ```$2``` appear to be changed to the | (cursor) character.

Please help!
thanks,
*Marc*

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
OS version: Darwin x64 15.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.08GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by ramya-rao-a** [comment]
Thanks for reporting!
I have pushed a fix that will fix this.
One side effect is that during preview the $ will show a preceding \. But the final value will be the right one.

**Comment by marc-learning** [comment]
Thanks for your fast action! You guys are great!
