### ISSUE TITLE
Breakpoint is moving one step down and showing up "Unverified breakpoint" message while debugging.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#5264]
- VSCode Version: 1.0.0-alpha
- OS Version:Windows10

Steps to Reproduce:
1. Launch app and try to debug node.js (TS) project.
2. Configure task.json and Launch.json (sourceMaps = true and oudir:"path").
3. Delete any generated .js file, build project (CTRL+SHIFT+B) and set break point in .ts file.
4. Start debugging and verify whether debug points hit or not.

Actual: Debug point is hitting in .ts file but I observed that the breakpoint is moving one step down and due to that other breakpoints are affected and make them "Unverified breakpoint".

![breakpointissue](https://cloud.githubusercontent.com/assets/17735796/14536434/362c0514-0227-11e6-834f-ec9013b038fa.gif)

**Comment by weinand** [comment]
@v-pavanp could you please make your project available so that I can investigate. Ideally just attach a zipped up project folder.

**Comment by v-pavanp** [comment]
Uploaded project at https://github.com/v-pavanp/ForTestingCode/commit/551ea09f84ac6ce9af2770271d362d413faa34c0 

Setup instruction:
1. Follow instruction from http://expressjs.com/en/starter/installing.html
2. Open app.ts and add break point at LN 10, 13, 14 and start debugging.
3. Verify app behavior.

**Comment by weinand** [comment]
@v-pavanp the creation time stamps on the source maps clearly showed that the maps were stale. Your build setup does not produce any source maps. After adding the sourceMap option to your task.json breakpoints were hit correctly:
```json
"args": ["--sourceMap", "app.ts"],
```
