### ISSUE TITLE
inactive region color was wrong

### ISSUE THREAD

**Issue by 1XiaSheng** [Microsoft/vscode#52652]
Issue Type: <b>Bug</b>

in the premacro ,in all .c or .cpp file,
#if()
  Color recognition error
#elif()
  Color recognition error
#endif

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (3.80GB free)|
|Process Argv|D:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.18.0
vscode-eslint|dba|1.4.12
code-runner|for|0.9.3
vscode-lua|gcc|0.1.2
vscode-language-pack-zh-hans|MS-|1.24.3
python|ms-|2018.6.0
cpptools|ms-|0.17.4
Go|ms-|0.6.83
red|red|0.2.2
vscode-hexdump|sle|1.6.0
vscode-lua|tri|0.12.4
clang-format|xav|1.6.2

</details>

**Comment by 1XiaSheng** [comment]
![tim 20180622114317](https://user-images.githubusercontent.com/37097029/41756902-7ad4faa8-7611-11e8-9f8b-8f3c4eb7d1ec.png)

**Comment by 1XiaSheng** [comment]
![tim 20180622114810](https://user-images.githubusercontent.com/37097029/41757052-2db44778-7612-11e8-8a86-e78bd6bb30b0.png)

**Comment by 1XiaSheng** [comment]
![tim 20180622115332](https://user-images.githubusercontent.com/37097029/41757187-ff3454aa-7612-11e8-96d7-568b8457e840.png)

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-cpptools

**Comment by 1XiaSheng** [comment]
ok, i will do it.
