### ISSUE TITLE
gulp vscode-linux-x64 produces a binary that opens a blank window

### ISSUE THREAD

**Issue by OneOfOne** [Microsoft/vscode#5265]
- VSCode Version:
```
➜ git describe --always --abbrev=16
e3ac586869cc97e6
```
- OS Version:
Arch Linux 64bit (kernel 4.4.5)

Steps to Reproduce:

1.  `cd $PATH_TO_VSCODE_GIT && ./node_modules/.bin/gulp vscode-linux-x64`
2. `../VSCode-linux-x64/bin/code-oss`

It opens the vscode window with just the menubar, none of the menu options does anything and no sidebar or status bar, also no errors.

**Comment by OneOfOne** [comment]
Note that running `./scripts/code.sh` works as intended.

**Comment by Tyriar** [comment]
@OneOfOne interesting, has this happened before on other builds of vscode? I haven't tried on Arch Linux before.

@joaomoreno is there a way to view logging from Electron on master currently? `VSCode-linux-x64/code` seems to hit the CLI now.

**Comment by OneOfOne** [comment]
@Tyriar I haven't tried that before, I was using insiders, I just wanted to test the $go matcher.

**Comment by bpasero** [comment]
We recently updated Electron to a newer version, try to run scripts/npm install first

**Comment by OneOfOne** [comment]
this was a completely fresh git pull, like I said I've been using insiders, I just wanted to try the $go matcher.

**Comment by OneOfOne** [comment]
I deleted the vscode folder and cloned it again and reran npm.sh install and gulp electron, now it's downloading ffmpeg, have been for the last hour but that's new, it didn't do that the first time around.

**Comment by OneOfOne** [comment]
For the record, it is still downloading, github's CDN is horribly slow.

**Comment by OneOfOne** [comment]
That fixed it, not sure why `git clean -fxd` wasn't enough and I had to completely remove the repo and reclone it, sorry for the noise.

**Comment by Tyriar** [comment]
Good to hear :)
