### ISSUE TITLE
vscode freezes when building from source in ubuntu 17.10 VM since upgrade to electron 2.0.x

### ISSUE THREAD

**Issue by jeanp413** [Microsoft/vscode#52653]
- VSCode Version:code-oss-dev 1.25.0 (Commit unknown, Date unknown)
- OS Version:Linux x64 4.13.0-45-generic

Since the upgrade to electron 2.0.x every time I build and launch vscode in my ubuntu 17.10 or 18.04 VM it freezes after a few seconds. It doesn't freeze if I launch it using the `--disable-gpu` flag but that wasn't needed before.
Also the insiders build works fine without the `--disable-gpu` flag but when I run `code-insiders --status` I got this error, don't know if this is a separate issue.
```
ubuntu@ubuntu:~$ code-insiders -v
1.25.0-insider
c5c7d43b65bcbbb3851fbd972fad077631c707e3
x64
ubuntu@ubuntu:~/Desktop/vscode$ code-insiders --status
[main 10:33:12 PM] Error: Command failed: /usr/share/code-insiders/resources/app/out/vs/base/node/cpuUsage.sh 108847 108849 108887 108947 108906 108913 108933
/bin/sh: 1: /usr/share/code-insiders/resources/app/out/vs/base/node/cpuUsage.sh: not found

    at ChildProcess.exithandler (child_process.js:287:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)

```

Output of `--status` without `--disable-gpu` flag
```
ubuntu@ubuntu:~/Desktop/vscode$ ./scripts/code.sh --status
[22:22:25] Syncronizing built-in extensions...
[22:22:25] You can manage built-in extensions with the --builtin flag
[22:22:25] [marketplace] ms-vscode.node-debug@1.25.2 ✔︎
[22:22:25] [marketplace] ms-vscode.node-debug2@1.25.1 ✔︎

Version:          code-oss-dev 1.25.0 (Commit unknown, Date unknown)
OS Version:       Linux x64 4.13.0-45-generic
CPUs:             Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3801)
Memory (System):  5.31GB (0.11GB free)
Load (avg):       2, 1, 1
VM:               33%
Screen Reader:    no
Process Argv:     /home/ubuntu/Desktop/vscode/.build/electron/code-oss . -n
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    disabled_software
                  rasterization:                disabled_software
                  video_decode:                 unavailable_software
                  video_encode:                 unavailable_software
                  webgl:                        enabled
                  webgl2:                       enabled

CPU %	Mem MB	   PID	Process
    0	   125	 96230	code-oss main
    0	    43	 96263	   zygote
    0	   201	 96479	     window (Welcome - Code - OSS Dev)
    0	    92	 96708	       extensionHost
    0	    92	 96492	     shared-process
    0	    92	 96428	   gpu-process

```
Output of `--status` with `--disable-gpu` flag
```
ubuntu@ubuntu:~/Desktop/vscode$ ./scripts/code.sh --status
[22:24:32] Syncronizing built-in extensions...
[22:24:32] You can manage built-in extensions with the --builtin flag
[22:24:32] [marketplace] ms-vscode.node-debug@1.25.2 ✔︎
[22:24:32] [marketplace] ms-vscode.node-debug2@1.25.1 ✔︎

Version:          code-oss-dev 1.25.0 (Commit unknown, Date unknown)
OS Version:       Linux x64 4.13.0-45-generic
CPUs:             Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3801)
Memory (System):  5.31GB (0.11GB free)
Load (avg):       1, 1, 1
VM:               33%
Screen Reader:    no
Process Argv:     /home/ubuntu/Desktop/vscode/.build/electron/code-oss . -n --disable-gpu
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    disabled_software
                  rasterization:                disabled_software
                  video_decode:                 unavailable_software
                  video_encode:                 unavailable_software
                  webgl:                        enabled
                  webgl2:                       enabled

CPU %	Mem MB	   PID	Process
    0	   136	 98717	code-oss main
    0	    43	 98742	   zygote
    0	   196	 98780	     window (Welcome - Code - OSS Dev)
    0	    92	 98805	       extensionHost
    0	   103	 98816	     shared-process
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@jeanp413 do you still get the issue with `code-insiders --status` failing? That sounds like an issue that could be unrelated to the electron update. 

As for the freeze: 
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by jeanp413** [comment]
@bpasero sorry for the late reply
- With the latest insiders build `Version:          Code - Insiders 1.25.0-insider (499122702e462b458117122a6885e6aeb3cec0a4, 2018-06-29T05:19:31.733Z)
` I no longer get an error with `code-insiders --status`.
- I tried following the steps in the link provided but the file called `core` never gets generated.

Notice that after a few seconds the animations of the activity bar and the cursor blinking stop working, that's when the whole vscode app freezes but as I said this doesn't happen with the `--disable-gpu` flag
![peek 2018-07-03 23-59](https://user-images.githubusercontent.com/25115070/42257751-b9e53c8e-7f1d-11e8-9dde-003c4dedb0f5.gif)

**Comment by bpasero** [comment]
@jeanp413 that above video is running out of "master" or another branch? Because on master we have yet returned to Electron 1.7.x.

**Comment by jeanp413** [comment]
@bpasero yes in the video its running on the electron-2.0.x branch with electron 2.0.3 just to show the issue as was reported originally when that branch was merged into master.

**Comment by KamranMackey** [comment]
@bpasero but why? There aren't any visible issues on the Windows platform with Electron 2.x, and are you aware that 1.7.12 has a major security vulnerability that you guys still haven't updated VS Code to be protected against?

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by jeanp413** [comment]
Sorry I've been really busy at work. I followed the steps in the wiki page but the core file never gets generated. Is there another way to get more info about the freezing?

**Comment by bpasero** [comment]
@jeanp413 that is weird, I fear that makes it hard to understand what is going on. The [normal build](https://az764295.vo.msecnd.net/exploration/eda3157386fd24251128652e4630433b760cc297/code-exploration-1531823891.tar.gz) never shows this behaviour or does it?

**Comment by jeanp413** [comment]
No, it doesn't. It works just fine
