### ISSUE TITLE
Typescript region folding does not work when syntax-aware folding is enabled

### ISSUE THREAD

**Issue by yuval-gilboa** [Microsoft/vscode#52650]
@mjbvz , @bpasero 
issue reported in #44530 as closed still reproduces in vscode 1.24.1

- set `editor.foldingStrategy` to `auto`
- set `typescript.experimental.syntaxFolding` to `true`
- folding controls are no longer visible for `#region` / `#endregion` sections
- folding controls also not visible for `region` / `endregion` sections

![image](https://user-images.githubusercontent.com/4710322/41755012-d63b0f1a-75dd-11e8-9853-781b0294054a.png)

**Comment by mjbvz** [comment]
Please share the text of that example code. Also, does this also happen in VS Code insiders?
