### ISSUE TITLE
update always failed

### ISSUE THREAD

**Issue by leeseean** [Microsoft/vscode#52663]
when it tip me to update to  a new version,I clicked yes,then it failed always

**Comment by chrmarti** [comment]
Does it show any error?

**Comment by joaomoreno** [comment]
You seem to have #47841.

Please read this comment if you can provide more detail: https://github.com/Microsoft/vscode/issues/47841#issuecomment-393101777

Please read this one to disable background updates: https://github.com/Microsoft/vscode/issues/47841#issuecomment-395017687

Also read this one to provide feedback on our new user setup: https://github.com/Microsoft/vscode/issues/47841#issuecomment-399941682
