### ISSUE TITLE
JSX syntax broken in ternary operator & arrays.

### ISSUE THREAD

**Issue by jorgebucaran** [Microsoft/vscode#52662]
- VSCode Version: 1.24.1
- OS Version: macOS 10.13.5

Steps to Reproduce:

1. Create the following JSX declaration in a .jsx, .jsx or .tsx file.

```jsx
var obj = {
  someMethod: state =>
    state ? (
      <MyComponent someProp={false} />
    ) : (
      [
        <MyComponent someProp={false} />,
        <MyComponent someProp={false} />
      ]
    )
}
```

2. That's  it.

EDIT: The issue is present whether I'm in "JavaScript" or "Javascript React" language mode.

---

### Screenshots

<img width="604" alt="screen shot 2018-06-22 at 15 49 28" src="https://user-images.githubusercontent.com/56996/41762059-6f7d0b46-7634-11e8-833e-00c90946189c.png">
<img width="840" alt="screen shot 2018-06-22 at 15 49 11" src="https://user-images.githubusercontent.com/56996/41762060-6fb3bf9c-7634-11e8-89ac-71a887772f4e.png">

A few more screenshots.

<img width="526" alt="screen shot 2018-06-22 at 15 55 25" src="https://user-images.githubusercontent.com/56996/41762151-ce29f758-7634-11e8-9a8a-02185d6bebcb.png">

And finally, the only way to fix it is to wrap them both in an array.

<img width="845" alt="screen shot 2018-06-22 at 15 55 40" src="https://user-images.githubusercontent.com/56996/41762155-d0d937c0-7634-11e8-8f4b-2efed1191196.png">

**Comment by mjbvz** [comment]
Fixed in insiders:

![screen shot 2018-06-25 at 11 29 29 am](https://user-images.githubusercontent.com/12821956/41868480-0f96e2e0-786b-11e8-86b9-60b5f302bd3b.png)
