### ISSUE TITLE
Command tab 'problems' badge counter should count by filter too

### ISSUE THREAD

**Issue by muuvmuuv** [Microsoft/vscode#52661]
The command tab problems should just show problems within a filter. So if I select a filter and inside that path is no error, it should show no counter badge:

<img src="https://user-images.githubusercontent.com/11534760/41762272-8356ecca-75fa-11e8-922f-27e093a0e796.png">
<img src="https://user-images.githubusercontent.com/11534760/41762273-8375af84-75fa-11e8-85fc-e70501c9db2a.png">

**Comment by sandy081** [comment]
Badge is to show the total number of problems. Not showing the badge might mislead/confuse users when the problems are filtered out.

**Comment by muuvmuuv** [comment]
In confuse me in its current state, anyway it could be a option on the right sie of the filter input (anicon; count all/only filtered).
