### ISSUE TITLE
Enter more than one line and a vertical scroll bar will appear

### ISSUE THREAD

**Issue by zhangyongbo** [Microsoft/vscode#52666]
Issue Type: <b>Bug</b>

Enter more than one line and a vertical scroll bar will appear. After typing 20 lines, a 20-line blank area appears at the bottom.The vertical scroll bar should appear after exceeding the height of the editor.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|8.00GB (0.28GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by yume-chan** [comment]
`"editor.scrollBeyondLastLine": false`

**Comment by zhangyongbo** [comment]
Very good
