### ISSUE TITLE
Convert split terminal into new tab

### ISSUE THREAD

**Issue by mittalyashu** [Microsoft/vscode#52665]
Using split terminal with many terminals on the screen at once can be bit messy.

![capture](https://user-images.githubusercontent.com/29014463/41767544-7f4609ae-7627-11e8-9ed3-da2553058d81.PNG)

So, it's would be great if we can toggle the split terminal into a new tab.

**Comment by Tyriar** [comment]
@mittalyashu you want to convert an already existing split terminal into a new tab? I think I'll merge this issue into https://github.com/Microsoft/vscode/issues/10546 as the layout of terminals should be more flexible then (plus it needs some ux work first).

**Comment by mittalyashu** [comment]
@Tyriar, I didn't mean to convert a split terminal into new tab _(like `.eslintrc.js`, though it is a good feature request)_. What I meant is that we can convert the split terminal into a separate instance, instead of joined.

![image](https://user-images.githubusercontent.com/29014463/41889337-b4e40e78-7927-11e8-82f6-15ad7d4679cd.png)

**Comment by Tyriar** [comment]
@mittalyashu how instances are handled will be redesigned when #10546 is done so I'm deferring this request to that.

**Comment by mittalyashu** [comment]
Oh! I see.
