### ISSUE TITLE
Invalid autocompletion

### ISSUE THREAD

**Issue by pronebird** [Microsoft/vscode#52678]
- VSCode Version: Version 1.24.1 (1.24.1)
- OS Version: macOS

Simple Javascript scenario script: 

I have an object `a` with the properties `b` and `c`. 

```
// I am gonna leave it here for demo purposes
import React from 'react';

var a = {
  b: 1337,
  c: 0xdeadbeef
};
```

I type in `a.` and VSCode gives me the alphabetically ordered vocabulary that's a mashup of words that VSCode spotted in the document and useful suggestions based on context.

See:

<img width="400" alt="screenshot 2018-06-22 13 52 45" src="https://user-images.githubusercontent.com/704044/41775281-9ffadd2c-7623-11e8-9271-e74ad86bce74.png">

As you can see from the screenshot, `React` and `a` are part of the suggestions list and for whatever reason have "document" icons. 

Apparently this is a very minimal example but give it a spin on a 400 LOC React component.

Is it possible to clean up the list of suggestions or *disable* autocompletion feature somehow while keeping the 3rd party plugins still offering suggestions?

**Comment by mjbvz** [comment]
Set `"javascript.nameSuggestions": false` to disable this
