### ISSUE TITLE
[Accessibility]A11y_VSCode_KeyboardShortcuts_Keyboard:Shortcut for ShowSearchNextTerm(Alt+DownArrow) is not working. 

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#52674]
**Environment Details:** 
VSCode Version : 1.24.1
OS Version:WIN10
**Additional Details:**
MAS Violated: MAS2.1.1

**Repro Steps:**
1. Launch VS Code.
2. Open Keyboard Shortcuts.

**Actual:**
Shortcut for Show Search Next Term(Alt+DownArrow) is not working.

**Expected:**
The shortcut(Alt+DownArrow) should work to show the next term and should show the next search term.

**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
[https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx](url)

**User Impact:**
User will not be see the search next term.

**MAS Reference**
[https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={8492c4eb-c179-40ae-8777-cd044ed725a2}](url)

Does this issue occur when all extensions are disabled?: Yes
**Attachment For Refernce:**
[[Accessibility]A11y_VSCode_KeyboardShortcuts_Keyboard_Show.pptx](https://github.com/Microsoft/vscode/files/2127468/Accessibility.A11y_VSCode_KeyboardShortcuts_Keyboard_Show.pptx)

**Comment by roblourens** [comment]
This works for me. Are you trying it while the search input box is focused? It doesn't do anything on the Keyboard Shortcuts page

**Comment by AccessibilityTestingTeam-TCS** [comment]
This bug is not reproducing on 
Version 1.24.1
Commit 24f62626b222e9a8313213fb64b10d741a326288
Date 2018-06-13T17:51:32.889Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by roblourens** [comment]
Does that mean it can be closed?
