### ISSUE TITLE
Remove unused imports from folder

### ISSUE THREAD

**Issue by cedvdb** [Microsoft/vscode#52670]
It would be nice to be able to right click on a folder and be able to remove unused imports of `.js` & `.ts` in of the whole folder. IntelliJ has this for java and it helps keeping things clean.

**Comment by mjbvz** [comment]
Try this extension: https://marketplace.visualstudio.com/items?itemName=bierner.folder-source-actions

**Comment by cedvdb** [comment]
@mjbvz doesn't want to install unfortunately but I understand it's an extension responsability
