### ISSUE TITLE
Test: debug toolbar floating position

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#52686]
Refs: https://github.com/Microsoft/vscode/issues/52490

- [x] any os @jrieken 
- [x] any os @Tyriar 

Complexity: 1

Start debugging something, and try to drag the debug toolbar around. 

* Now it should be possible to also put it one "level" lower in the editor area. 
* Make sure this works fine and position is peristed across vscode session
* Verify double click on drag area returns it to its original position

**Comment by bpasero** [comment]
@isidorn @weinand I find this a bit weird to be honest:

![image](https://user-images.githubusercontent.com/900690/41926976-21f79da6-7971-11e8-9294-923ba4fe376c.png)

Would it make sense (or possible) to restrict the toolbar to the area that is reserved for editors if (and only then) the toolbar is one level below (and thus more part of the editor area then before)?

**Comment by isidorn** [comment]
@bpasero some poeple want to put it in the viewlet below the top actions. So optimally I would restrict it to the editor and viewlet area, and not allow over activity bar
