### ISSUE TITLE
Extension does not activate any longer and stopped working

### ISSUE THREAD

**Issue by JohannesHoppe** [Microsoft/vscode#52685]
Hello, my extension is very simple but somehow it stopped working.
I don't know what went wrong, because it is more or less still the same code from the `yo` generator. And it worked some time ago.

Here is the code:
https://github.com/angular-schule/vscode-angular-schule-extension-pack

I'm looking at "View > Output > (Log) Extension Host"
the extension is not in the list of extensions, that `ExtensionService` tries to activate.

Without any activation, the registration via `commands.registerCommand` seems to be never called. In the end the command fails with:
![image](https://user-images.githubusercontent.com/640639/41777583-1a1d75ee-762c-11e8-913e-3f41902373e9.png)

Is this a bug in VSCode? Or is the extensions is somehow outdated?
Many thanks!

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.15063

**Comment by chrmarti** [comment]
Do you have all the extensions this extension depends on installed? (There is a list of `extensionDependencies` in the `package.json`.)

Is there anything in the Debug Console of the window you started from?

**Comment by JohannesHoppe** [comment]
Hi. Thanks for stepping in!

This extension is mainly an extension pack. The listed extensions are installed during the installation of my extensions. This part works like a charm. After that the exension is supposed to change some user settings, to adjust the extensions of the pack. This worked fine in the past. 

And no, there is no output regarding my extension. Complete silence. I see the ExtensionService output from other extensions, but not mine. The funny part is the following:

1. The extension in the store installs the extensionDependencies flawlessly.
1. I can also debug this locally. But only if I remove the extensionDependencies before debugging. While debugging the commands do work.

**Comment by glennreag** [comment]
Hi just to add to this issue, i'm having a similar problem, when i installed the VSCode May Update my extension began to behave weirdly, i have some commands that when i do the keybinding call they fail, but if i manually execute the function by right clicking the file and selecting the function that i want to execute then the function executes correctly. My extension worked fine before the update.

I don't know if i have to create a new issue so i'm just adding to this conversation.

![image](https://user-images.githubusercontent.com/12106247/41881930-6087a986-78a3-11e8-9237-4531c5109e4b.png)

Here's an image with the error, i'm receiving.

**Comment by chrmarti** [comment]
@glennreag Your command is called without arguments when run from a keybinding, maybe that causes it to fail?

**Comment by chrmarti** [comment]
@JohannesHoppe I think when debugging the dependencies are not automatically installed. Make sure you have all (including recently added ones) dependencies already installed when you start debugging.

**Comment by glennreag** [comment]
@chrmarti Yeah somehow the May update changed the context, and when the function was called from keybinding, the context didn't receive arguments. Thanks for the help.

**Comment by JohannesHoppe** [comment]
I still think that my original issue is different! ;-)

**Comment by chrmarti** [comment]
@JohannesHoppe Can you confirm that all the dependencies are installed?

**Comment by JohannesHoppe** [comment]
The extension has the following
```
"extensionDependencies": [
        "eg2.tslint",
        "Angular.ng-template",
        "EditorConfig.EditorConfig",
        "msjsdiag.debugger-for-chrome",
        "christian-kohler.path-intellisense",
        "CoenraadS.bracket-pair-colorizer",
        "formulahendry.auto-rename-tag",
        "AngularDoc.angulardoc-vscode",
        "pkief.material-icon-theme",
        "aeschli.vscode-css-formatter"
    ],
```
after installation from the marketplace I have all of them installed:

- eg2.tslint ✅ 
- angular.ng-template ✅
- editorconfig.editorconfig ✅
- msjsdiag.debugger-for-chrome ✅
- christian-kohler.path-intellisense ✅
- coenraads.bracket-pair-colorizer ✅
- formulahendry.auto-rename-tag ✅
- angulardoc.angulardoc-vscode ✅
- pkief.material-icon-theme ✅
- aeschli.vscode-css-formatter ✅

So everything is fine here.
Still, I can't execute the commands:

![image](https://user-images.githubusercontent.com/640639/41777583-1a1d75ee-762c-11e8-913e-3f41902373e9.png)

**Comment by chrmarti** [comment]
The debug console shows: `Extension 'angular-schule.angular-schule-extension-pack' failed to activate. Reason: unknown dependency 'pkief.material-icon-theme'.`

Looks like themes no longer work as a dependency. In the latest insiders builds (and upcoming stable release) you can use `"extensionPack"` instead of `"extensionDependencies"` in the `package.json` as a workaround. (That also fits your usage better from what I see.)

**Comment by sandy081** [comment]
@JohannesHoppe Since it is an extension pack, I would suggest to use `extensionPack` property instead of `extensionDependencies` which will take off the run time dependency on these extensions.


But please note that you can only do it from 1.26 as this feature is available on then.

**Comment by JohannesHoppe** [comment]
@chrmarti @sandy081 Many thanks for figuring this out for me. 👍 

Indeed, the extension `pkief.material-icon-theme` (which is an icon theme) was causing the trouble. After removing the entry, my extension is again loaded.
