### ISSUE TITLE
Show a back/forward button prominently in a toolbar

### ISSUE THREAD

**Issue by brianjmurrell** [Microsoft/vscode#52687]
This is a re-request of #21890 since that issue was summarily closed.  It's really not helpful to close issues (and moreso, lock them down to just contributors) just because their implementation is not foreseeable in the immediate future.

How are you to gauge demand for a feature if it cannot be commented on, and when closed, how does a feature ever get implemented?

So, to ask again, it would be nice if there was a single click button for what is effectively _Go->Back_, which itself is two mouse clicks with a pointer navigation in between.  That seems like it's not significant but when you are doing it repeatedly to navigate back through a series of _Go to Definition_ jumps, it becomes significant.

**Comment by chrmarti** [comment]
An extension could contribute buttons to the editor: https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesmenus

**Comment by HaaLeo** [comment]
@brianjmurrell the [Code Navigation](https://marketplace.visualstudio.com/items?itemName=vikas.code-navigation) extension does exactly what you want.

**Comment by brianjmurrell** [comment]
@HaaLeo Seems so.  Nice.  Would be cool if it had a concept of seeing the stack of functions you have followed through.  But I guess that is an RFE for the extension.  :-)
