### ISSUE TITLE
Releasing the alt key with the menubar hidden and the new titlebar enabled causes the menubar to immediately hide

### ISSUE THREAD

**Issue by iansan5653** [Microsoft/vscode#52697]
- VSCode Version: 1.25.0-insider
- OS Version: Windows 10 Home 1803

Steps to Reproduce:

1. Hide the menu bar with **View** -> **Toggle Menu Bar**
2. Add the setting: `"window.titleBarStyle": "custom"`
3. Press the <kbd>Alt</kbd> key. The menu reappears, as expected.
4. Release the <kbd>Alt</kbd> key. The menu should stay visible until an option is selected or somewhere else is clicked. Instead, the menu immediately disappears.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
should be addressed with #51493
