### ISSUE TITLE
Missing icons in activity bar

### ISSUE THREAD

**Issue by AustinShalit** [Microsoft/vscode#52691]
- VSCode Version: 1.22.2
- OS Version: MacOS 10.13.5

Description:
I am experiencing the same issue as #40531.

Steps that do not work to resolve:
- Reload window
- Reboot computer

Steps that do resolve:
- Right click on activity bar and select all

![missing](https://user-images.githubusercontent.com/3799260/41779684-949a8a36-7600-11e8-9b4f-3adaa998612a.jpeg)

Reproduces without extensions: Yes

**Comment by sandy081** [comment]
Can you please update your VS Code and try to reproduce it?

**Comment by AustinShalit** [comment]
Will do

**Comment by AustinShalit** [comment]
Closing for now.  If I see this happen again I'll reopen.
