### ISSUE TITLE
Support ctrl+up/ctrl+down to scroll without moving the caret

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/vscode#527]
Like other editors, VS Code should support Control + Up / Down arrows to scroll the current viewport without moving the caret

**Comment by alisabzevari** [comment]
+1 for this feature.

**Comment by nielslbeck** [comment]
+1

**Comment by Ivan171** [comment]
+1. Use this lot on Sublime.

**Comment by jaygeek** [comment]
+1 :+1: ++1
for (i = 0; i < success; i++) { 
    vote.post();
}

**Comment by alexandrudima** [comment]
Thanks to @spellizzari this is now in! :+1:

**Comment by RyanCavanaugh** [comment]
Thank you @spellizzari ! :trophy: Can't wait to set up a local build and start using this.

**Comment by jaygeek** [comment]
Awsm! Can't wait. Thanks.

**Comment by alexandrudima** [comment]
@RyanCavanaugh fyi we plan to release on the insiders channel on Monday 14th

**Comment by ericsciple** [comment]
Really happy to see this feature made it in! Thanks!
