### ISSUE TITLE
Default keyboard shortcut (Cmd+Shift+S) for Save As does not work on Mac

### ISSUE THREAD

**Issue by krupenja** [Microsoft/vscode#52703]
- VSCode Version: 1.24.1
- OS Version: MacOS 10.13.5

Steps to Reproduce:

1. Open VSCode
2. Press Cmd+Shift+S.

Result:
Nothing happens, Save As dialog does not appear.  Save As works fine when opened from menu. Other keyboard shortcuts work OK. 

Also, default shortcut (Ctrl+Shift+S) works fine in Linux.

Does this issue occur when all extensions are disabled?: Yes.

**Comment by chrmarti** [comment]
This works for me. Do you have any applications installed that might capture this shortcut?

**Comment by krupenja** [comment]
Checked again today and it has no started working. No idea what was causing the issue originally but closing since it is no longer reproducible.
