### ISSUE TITLE
Add "Hide All Tools" action

### ISSUE THREAD

**Issue by funkyOne** [Microsoft/vscode#52708]
It would be good to create an action that would hide any open panel/sidebar leaving only editor groups. Essentially it would be a copy of the same action from WebStorm.

So technically it would do two things:
 - hide SideBar
 - hide Panel

As a bonus it could remember what tools it closed and tried to reopen when called again.

There is already "Maximize Editor Group and Hide SideBar" action with a bit similar behavior.
![old](https://user-images.githubusercontent.com/2235489/41798783-a43f680e-7677-11e8-9ae2-2e7b77aa1269.gif)
However there are 2 issues:
- It doesn't hide Panel
- Minimizes all other editor groups

This new action would fulfill the need to "Close whatever tools I have open and let me get to coding"
See example:
![new](https://user-images.githubusercontent.com/2235489/41798817-c68a681e-7677-11e8-84f3-7b99fc991183.gif)

I already have this action implemented, would be happy to create PR if the feature is worth adding.

Thanks!

**Comment by TomSputz** [comment]
This seems really handy :), I agree that often using zen mode / collapsing other editor groups can be overkill and being able to easily toggle unnecessary parts of the ui would be handy. Is there any reason this shouldn't just be an extension though?

On another note - do you mind making a repo to demo this? I'd love to have a look at the code to see if I could add that recover functionality. It would be a must for this to be useful

**Comment by isidorn** [comment]
Please use F1 > toggle zen mode
You can configure zenMode in the settings
