### ISSUE TITLE
Adding live logging for JavaScript

### ISSUE THREAD

**Issue by arthurbuhl** [Microsoft/vscode#52702]
Hi, thanks a ton for VS Code. I like it a lot.

I suggest adding a simple feature to show live `console.log` value next to it.

So something like if we have code:

```js
const array1 = [1, 4, 9, 16];
const map1 = array1.map(x => x * 2);
console.log(map1);
```
Then it would be nice to see the live result next to `console.log` only like
```js
const array1 = [1, 4, 9, 16];
const map1 = array1.map(x => x * 2);
console.log(map1);    [2, 8, 18, 32]
```
Something like we see in [import-cost](https://github.com/wix/import-cost). That `51.2k` value is calculated live and shown as hover text.

![image](https://user-images.githubusercontent.com/40258253/41791712-362f0534-7674-11e8-80ba-9d619a8925b8.png)

Some like this would be nice for live `console.log` also. I think this will be a really cool addition to VS Code.

:octocat:

**Comment by TomSputz** [comment]
This doesn't seem particularly important for the main application imo, Though alternatively you can use [this](https://marketplace.visualstudio.com/items?itemName=WallabyJs.quokka-vscode) extension for the functionality you want I think

**Comment by weinand** [comment]
@arthurbuhl 

If you add `"debug.inlineValues": true` to your settings, actual values are shown inline:

![2018-06-22_22-21-17](https://user-images.githubusercontent.com/1898161/41797533-a821abb0-766a-11e8-8c06-028e1b25e006.png)

Is this what you are suggesting?
