### ISSUE TITLE
Lag through scrolling

### ISSUE THREAD

**Issue by pawarsagar** [Microsoft/vscode#52701]
- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:34.867Z)
- OS Version: Windows_NT x64 10.0.17134
- Extensions: none
---

Steps to Reproduce:

1. Even my Vs Code has almost 100 lines of codes, it makes scrolling impossible through few seconds of Lag

**Comment by TomSputz** [comment]
Can you please update to the latest version of vscode and see if this issue still affects you?

**Comment by alexandrudima** [comment]
@pawarsagar  Can you please provide some kind of steps?

**Comment by Vahagn1993** [comment]
@TomSputz  @alexandrudima  Same here
Acer Aspire E5-771G-348S
VS Code About:
Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:43:53.668Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64
Windows: 10 (1803 build 17134.165)

**Comment by pawarsagar** [comment]
@alexandrudima  yes sure,
while iam scrolling in my workspace it takes few seconds to responds 
for eg if I scroll through my mouse  to top of the page , it consumes few seconds to response 
and then  it will react to my mouse activity

**Comment by alexandrudima** [comment]
@pawarsagar Can you please follow our guide at https://github.com/Microsoft/vscode/wiki/Performance-Issues to identify which process is consuming a lot of CPU for you?
