### ISSUE TITLE
Updating to 1.24.1 failed when using the built-in updater

### ISSUE THREAD

**Issue by zomgrolf** [Microsoft/vscode#52709]
- VSCode Version: 1.23 or 1.24 (not quite sure)
- OS Version: Windows 10 Home 64-bit 1803

Tried to update VSCode to the latest version (1.24.1) using the built-in updater. The update failed, asking me to download and install the new version manually and to open an issue a github with the inno log attached:

[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2129146/vscode-inno-updater.log)

Does this issue occur when all extensions are disabled?: No idea

**Comment by joaomoreno** [comment]
You seem to have #47841.

Please read this comment if you can provide more detail: https://github.com/Microsoft/vscode/issues/47841#issuecomment-393101777

Please read this one to disable background updates: https://github.com/Microsoft/vscode/issues/47841#issuecomment-395017687
