### ISSUE TITLE
Display function param type details instead of just type name.

### ISSUE THREAD

**Issue by iugo** [Microsoft/vscode#52718]
```
/**
 * @typedef Options
 * @property {number} number
 */

/**
 * @param {Options} options
 */
function getNum(options) {
  return options.number;
}
```

When I hover over `options`, I want to see `Options` has a property which named number and type number.

以前的版本, 当光标悬停在参数 `options` 上时, 会显示 `Options` 内具体的内容. 但是现在仅仅显示一个名字.

希望能该功能回退到以前的版本, 或者作为一个编辑器选项.

**Comment by mjbvz** [comment]
Related to https://github.com/Microsoft/TypeScript/issues/14662

Showing only the alias is by design here as often the full type signature can be overwhelming and is often not useful
