### ISSUE TITLE
files.trimTrailingWhitespace removes trailing whitespace inside Javascript multi-line string literals

### ISSUE THREAD

**Issue by andyburke** [Microsoft/vscode#52711]
- VSCode Version: 1.24.1 (1.24.1)
- OS Version: macOS High Sierra 10.13.4 (17E199)

Steps to Reproduce:

1. Create a multi-line Javascript string literal that has some trailing whitespace using backticks:

```js
`this is a
multi-line
string
     
with some trailing whitespace   
`
```

2. Save the file with the files.trimTrailingWhitespace option enabled
3. Observe that trailing whitespace inside the multi-line string literal has been removed

Does this issue occur when all extensions are disabled?: [x] Yes/No

**Comment by andyburke** [comment]
This is also happening inside multi-line comments, eg:

```js
/*
here is a multi-line comment
    
with some trailing white space   
*/
```

**Comment by alexandrudima** [comment]
Currently trimming trailing whitespace is implemented in a language agnostic way (meaning it works the same for plain text files and for javascript or other file types). It does not use any tokenization information to trim the file.

Perhaps such a syntactical aware trimmer is something a rich language formatter should provide? Did you look into using format on save or into using extensions that define JavaScript formatters ?

**Comment by andyburke** [comment]
I did not.

I think there probably should be a warning associated with this setting given that it's not context aware.
