### ISSUE TITLE
The extensions stops working

### ISSUE THREAD

**Issue by Isatol** [Microsoft/vscode#52719]
- VSCode Version: 1.21.1
- OS Version: Windos 10 Pro 1803 17134.112

Steps to Reproduce:

1. Nothing, i was working as always With Vue in VS Code, and the intellisense for Js, Vue, Vetur, Vuetify, AutoClose- Tag, Ato Rename tag, everything stops working, only themes are working, i uninstall, reinstall, update, clean uninstall with extensions and configs, and nothing happens.  
2.

Does this issue occur when all extensions are disabled?: No

**Comment by chrmarti** [comment]
Could you update to VS Code 1.24.1 and check if the problem is still there?
