### ISSUE TITLE
JSON coloring changes

### ISSUE THREAD

**Issue by golf1052** [Microsoft/vscode#5271]
- VSCode Version: 1.0.0
- OS Version: Mac OS X 10.10.5 and Windows 10 (stable build 10586)

Updated from 0.10.11 to 1.0.0, JSON coloring changed between versions for my theme [Base16 Ocean](https://marketplace.visualstudio.com/items?itemName=golf1052.theme-base16-ocean).

Before (Can't find a download link for 0.10.11 right now so i just edited the styling in dev tools to show what it looked like. The braces were grey.):
![](http://i.imgur.com/0mOioX4.png)

After:
![](http://i.imgur.com/uyuS0o3.png)

[Link to .tmTheme](https://github.com/golf1052/base16-ocean-vscode/blob/master/extension/themes/base16-ocean.dark.tmTheme)

Steps to Reproduce:
1. Install Base16 Ocean extension and set theme to Ocean Dark
2. Open a JSON file, notice coloring
3. Update to 1.0.0
4. Open a JSON file, notice coloring

Testing with built in themes it seems like the issue is more the theme than VSCode but I do wonder why the coloring changed between versions.

**Comment by aeschli** [comment]
There was a issue before that custom themes would inherit the colors of the default theme.
This led to problems when the color in the default theme matched with more scope segments and therefore overrules the color of the theme.
Now custom themes no longer inherit colors. Only the colors defined in the theme are used.
You have to update your theme to also contain a rule for the scope used by json properties
(The scope is `support.type.property-name`)
