### ISSUE TITLE
Text drag and drop broken by unused variable in object destructuring

### ISSUE THREAD

**Issue by mpearson** [Microsoft/vscode#52714]
Issue Type: <b>Bug</b>

I noticed this issue after the recent update which introduced special rendering for unused variables. It seems that you can no longer drag and drop text onto lines with this special formatting.

Repro steps:

1. open a Typescript file
2. assign one or more variables via object destructuring
3. ensure a variable is unused, and is rendered in grey due to the recent update
4. select text elsewhere and try to drag it onto the line with that variable
5. drag and drop doesn't work anywhere in the line
6. dragging a selection *from* that line to elsewhere in the file does work

![ezgif-5-48a38323cb](https://user-images.githubusercontent.com/926478/41802834-cc8c97e4-7638-11e8-8965-ef621830a64c.gif)

```
public myFunction() {
  const obj = {
    unusedVar: 50,
    usedVar: 100,
  };

  const {unusedVar} = obj;
  const {usedVar} = obj;

  const textIWantToDrag = "whatever";

  console.log(usedVar);
}
```

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:40.560Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (9.01GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.58
tslint|eg2|1.0.30
csharp|ms-|1.15.2
code-settings-sync|Sha|2.9.2

</details>

**Comment by rebornix** [comment]
It seems the hit test is doing incorrectly in this case.

**Comment by rebornix** [comment]
Tried to reproduce in latest version but failed, we no longer show the green squiggly line under unused variables, and that's probably why the issue no longer exists. Close it for now but if we have a good reproduce of this problem again, let's reopen it.
