### ISSUE TITLE
Terminal view for Laravel

### ISSUE THREAD

**Issue by 7heDuke** [Microsoft/vscode#52727]
Issue Type: <b>Bug</b>

I am new to Laravel. When I typed "php artisan route:help" in the terminal this showed up:

?[37;41m                                                                  ?[39;49m
?[37;41m  [Symfony\Component\Console\Exception\CommandNotFoundException]  ?[39;49m
?[37;41m  Command "route:help" is not defined.                            ?[39;49m
?[37;41m  Did you mean one of these?                                      ?[39;49m
?[37;41m      route:cache                                                 ?[39;49m
?[37;41m      route:clear                                                 ?[39;49m
?[37;41m      route:list                                                  ?[39;49m
?[37;41m                                                                  ?[39;49m

I think it's an ASCII for text color I guess, but now showed properly.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz (4 x 2395)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (3.05GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.58
vscode-eslint|dba|1.4.12
vscode-faker|dee|1.3.0
es7-react-js-snippets|dsz|1.8.3
EditorConfig|Edi|0.12.4
php-debug|fel|1.12.3
php-intellisense|fel|2.3.3
php-pack|fel|1.0.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.3
beautify|Hoo|1.3.2
vscode-filesize|mkx|2.1.0
vscode-apache|mrm|1.1.1
python|ms-|2018.6.0
debugger-for-chrome|msj|4.6.0
color-highlight|nau|2.3.0
laravel-blade|one|1.18.0
laravel-extension-pack|one|0.2.0
laravel5-snippets|one|1.4.0
material-icon-theme|PKi|3.5.0
laravel-helpers|raf|0.2.2
LiveServer|rit|5.1.1
vscode-paste-and-indent|Rub|0.0.8
laravel-artisan|rya|0.0.20
reactreduxcoursesnippets|TCL|0.7.0
vscode-react-native|vsm|0.6.11
change-case|wma|1.0.0
html-css-class-completion|Zig|1.17.1

</details>
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
