### ISSUE TITLE
HTML Tags

### ISSUE THREAD

**Issue by 7heDuke** [Microsoft/vscode#52729]
There is a feature in Sublime Text that I liked. Every time we select a `<div>`, we will be shown the closing `<div>` of the tag. Currently in VC, if I select a `<div>`, it will show every `<div>` on the page. That's not good since it's kind of difficult to find out which closing tag belongs to that `<div>`.

**Comment by MorganMarshall** [comment]
I'm not able to reproduce. Try clicking the letters within the <div>. It will then show you corresponding </div>, are you on the latest version? Whats your OS?

**Comment by aeschli** [comment]
@7heDuke What's editor language (lower right corner). It should work if it's HTML. For PHP you need to install an extension such as intelliphense.

**Comment by aeschli** [comment]
Closing as this works for me in HTML.
