### ISSUE TITLE
How to remove unwanted cloned project from VS code

### ISSUE THREAD

**Issue by Mathias02** [Microsoft/vscode#52725]
Good day,

Would you please help me to remove a project from my VS code that I might have cloned by mistake and can't find its link to move it to, it says on the fork icon 5000 pending changes and don't know how to get rid of them from my windows machine, 

Regards

**Comment by chrmarti** [comment]
Please check your Source Control view. When there are multiple repositories, select the one with 5000+ changes. You can hover over one of the listed files to see in which path it is and the clean that up from the command line or the file explorer.
