### ISSUE TITLE
Severe performance issues with the debug console

### ISSUE THREAD

**Issue by aleksijuvani** [Microsoft/vscode#52728]
Issue Type: <b>Bug</b>

When printing messages to the standard output at a sufficiently fast rate, extreme stuttering can be observed in both VS Code and the application being debugged. This will happen only if the "debug console" is visible in VS Code.

Additionally, if a lot of messages have been printed before switching to the "debug console" tab, VS Code will hang for several seconds upon switching tab.

I'm convinced that the problem is the debug console, because running the application outside VS Code shows no such problems. Hiding the VS Code debug console or removing the print statements from the program will also get rid of the stutter.

Reproduces both with and without `--disable-gpu`.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.95GB (19.43GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.17.5
PowerShell|ms-|1.7.0
sublime-keybindings|ms-|4.0.0
trailing-spaces|sha|0.2.11
shader|sle|1.1.3
rewrap|stk|1.9.1

(1 theme extensions excluded)

</details>

**Comment by weinand** [comment]
The debug console is meant as a REPL, not as a vehicle for outputting lots of data.
Please use the integrated terminal instead by adding a `"console": "integratedTerminal"` to your launch config.

**Comment by aleksijuvani** [comment]
This doesn't seem to be an option with the C++ debugger. Upon setting `"console": "integratedTerminal"`, output disappears from the debug console, but it doesn't appear in the integrated terminal. Should I file an issue against [Microsoft/vscode-cpptools](https://github.com/Microsoft/vscode-cpptools)?

In any case, it feels like an odd default behaviour to have the debug output go to the debug console if it's not capable of handling large amounts of text.

**Comment by isidorn** [comment]
Dup https://github.com/Microsoft/vscode/issues/11462
