### ISSUE TITLE
Untranslated update strings in Linux

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5272]
- VSCode Version: 1.0.0-alpha
- OS Version: Ubuntu 15.10

Steps to Reproduce:

1. Change language to Spanish
2. Install yesterdays version (84abe71111a...) and check for updates or wait for the pop-up.
3. Update pop-up message is untranslated for the message and download now buttons
![updatelocalized](https://cloud.githubusercontent.com/assets/12900364/14540080/2de15286-0238-11e6-978f-9cbf5239dcdc.jpg)

Also the "Download available update" option under the help menu is not translated.
![menu_005](https://cloud.githubusercontent.com/assets/12900364/14540131/5f3d9074-0238-11e6-8a1b-51b5b84b5d69.png)

**Comment by Tyriar** [comment]
cc @joaomoreno

**Comment by joaomoreno** [comment]
This is `alpha`. String will be translated soon enough...
