### ISSUE TITLE
Can't determine number of extensions

### ISSUE THREAD

**Issue by SkybuckFlying** [Microsoft/vscode#52720]
I am a first time user of Visual Studio Code, I am exploring and admiring the enormous ammount of extensions/plugins and such.

I have absolutely no idea how many there are. Mostly because there is no scrollbar, not counter, no nothing ?!? No indication, I could be spending the rest of my life scrolling through this downwards... as it loads more extensions... what is the point of all this ?

I also get fed up with having to scroll the mouse's scroll wheel... this is costing a little bit more finger strain/energy then dragging a scrollbar, also it makes annoying sound to have to turn the scroll wheel

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288,

**Comment by TomasHubelbauer** [comment]
You can also use the web UI for the VS Code extension gallery:

https://marketplace.visualstudio.com/

**Comment by chrmarti** [comment]
There should be a scrollbar. Which OS are you on?

There are indeed a lot of extensions written by the community. Using https://marketplace.visualstudio.com/ is a good hint to browse through these.

**Comment by SkybuckFlying** [comment]
Scrollbox/bar is not visible (or is dark gray like background also dark gray), scroll thumb is visible, just noticed it, I guess I completely missed it, didn't notice it before. I am used to classic GUI. I use Windows 7 in classic GUI mode. I am used to a light gray scrollbar with background showing up and arrows at top and bottom. 

This new behaviour is something totally different, the vertical bar is not visible, it remains dark, only the tiny little medium scroll thumb is visible.

In case this new visual style is desired I would recommend making the tiny little scroll thumb blink for a couple of seconds after the users scroll with mouse wheel... or perhaps make it bigger and then zoom in to it's tiny little position to bring it to the attention of the user.

**Comment by sandy081** [comment]
@SkybuckFlying All scroll bars in VS Code look similar. 

@alexandrudima Assigning to you for continuing discussion on scroll bars.

**Comment by alexandrudima** [comment]
I agree our scrollbars can feel foreign, especially on Windows 7, especially if you've never used other OSes. I think even Windows 10 uses scrollbars without arrows on touch devices, but that's something pretty well established and used by default on OSX or Ubuntu AFAIK.

Our hope is that you end up using a code editor and you see them there and figure out that the rectangles are scrollbar sliders:

![image](https://user-images.githubusercontent.com/5047891/41904247-2f452e62-7938-11e8-8857-7b89a27d9b12.png)

You can also install different themes, the scrollbars are themable and they are changed by themes. That being said, we don't have any plans to make them look like native Windows 7 scrollbars and add arrows and other such stuff. IMHO it takes maybe a few minutes, but then you get used to them... They're just sliders...

**Comment by SkybuckFlying** [comment]
This picture is a bit deceptive.

VSCode runs with dark mode by default, and in dark mode it's much harder to see.

**Comment by alexandrudima** [comment]
I agree the scrollbar is harder to see for me in the dark theme:

![image](https://user-images.githubusercontent.com/5047891/42078946-8ba5f324-7b7e-11e8-9da1-ed1e938a95d6.png)

That's why I use a light theme. By the way, we ship out of the box with a High Contrast Theme and there are hundreds of theme extensions on the marketplace. Also, it is possible to customize the color. e.g.

In `settings.json`:
```
	"workbench.colorCustomizations": {
		"scrollbarSlider.background": "#ffffff88",
		"scrollbarSlider.hoverBackground": "#ffffffaa",
		"scrollbarSlider.activeBackground": "#ffffffcc",
	}
```

![image](https://user-images.githubusercontent.com/5047891/42079045-ef90e10a-7b7e-11e8-864c-1e5e26ded0e4.png)

**Comment by SkybuckFlying** [comment]
These screenshots still put these weird scrollbars in a too positive light.

1. On a resolution of 1920x1200 the thumb is so small it's easy to miss.

2. Further more I took another look at it and the thumb and bar is actually not visible at all IT'S HIDDEN. Only when the user starts to scroll does it become somewhat visible.

3. I was expecting the thumb to be at the bottom of the scrollbar as usual, but it's not there ! Amazingly enough it's at the top of the bar and thus it's easily missed. Since the user will be  looking at the bottom cause that is where the list is actually growing. So this is totally weird behaviour.

4. It looks like the list is tiny, but this is deceptive it's actually a growing list of extensions and thus the usage in this fashion of a scrollbar makes no sense what's so ever and it's behaviour is simply flawed/misleading/etc.

**Comment by alexandrudima** [comment]
1. The slider has the length depending on the length of the content (`scrollHeight`) relative to the length of the viewport (`height`) with a minimum of 20px.

2. The slider appears when a scroll event occurs or when the mouse is over the scrollable surface
![kapture 2018-07-02 at 11 26 46](https://user-images.githubusercontent.com/5047891/42156239-d7ef01bc-7dea-11e8-98fc-4a01ead9599b.gif)

3. The slider is rendered at the location where the viewport is relative to the content length. This is a first principle of how scrollbar sliders work:
![kapture 2018-07-02 at 11 28 23](https://user-images.githubusercontent.com/5047891/42156323-10f0b58c-7deb-11e8-973b-a9ca57f0385c.gif)

4. ping @sandy081 

@SkybuckFlying I will not change anything on the scrollbar implementation. I believe the scrollbar (an UI component used throughout VS Code in many places) works correctly. @sandy081 Please go through this thread and see if you want to do something about the discoverability of scrolling in the extensions viewlet.

**Comment by sandy081** [comment]
Thanks @alexandrudima for responding to scrollbar questions. 

All views (including extensions viewlet) are consistent in how we show sliders and I do not want to introduce new behaviour here.
