### ISSUE TITLE
Problem with 'https://schemastore.azurewebsites.net/schemas/json/package.json' 

### ISSUE THREAD

**Issue by albertosantini** [Microsoft/vscode#52722]
- VSCode Version: 1.24.1
- OS Version: Windows 10 - Version 1803

Steps to Reproduce:

1. Sometimes I experiment the issue in the title loading a package.json.
2. No finite steps, because it doesn't happen always and restarting Code fixed the issue (until the next time)

Does this issue occur when all extensions are disabled?: Yes

I read https://github.com/Microsoft/vscode/issues/48298, but I have not any proxy.

No relevant info in output panels.

**Comment by albertosantini** [comment]
See also #51032 and #45792.

**Comment by aeschli** [comment]
@albertosantini Could this have been because of connectivity issues?

**Comment by albertosantini** [comment]
When I notice that problem, I am connected and it seems the network is working fine.

Generally speaking, I notice the issue, when I am publishing a package to npm and I double check if there is any "no-go". So I notice the icon, with the problem, in the status bar, just after a `npm test` or a `git push`. So the connectivity should be ok.

I am in Italy. Maybe any load balancing failure? A router misconfigured? 

Really no idea. 

I noticed the problem recently maybe with 1.23.x or 1.24.x. 
I didn't experimented the issue with 1.25.x .

**Comment by gangsthub** [comment]
Could this be related with network changes (i.e., switching from one wifi to another or disabling a proxy connection on the machine)?

**Comment by albertosantini** [comment]
No. 

I have not any proxy and I have only one wifi.

I would close the issue, because I cannot reproduce it and, lately, I didn't notice it.

In the meantime I changed the box. 
Maybe it was a race condition between random network latency and slow machine.
