### ISSUE TITLE
Git visualisation plugin not working properly.

### ISSUE THREAD

**Issue by vgvishesh** [Microsoft/vscode#52721]
[Issue](url
![image](https://user-images.githubusercontent.com/3880698/41807809-18e4c472-76f2-11e8-845c-bc1416db1f11.png)
) Type: <b>Bug</b>

Git status tracker for the files, like marking which files are modified or not, is not working properly. My workspace has been reset to the head, as a result there is no new modified files, can be verified from the terminal. But, still the git tracker is showing the some newly modified files.

VS Code version: Code - Insiders 1.25.0-insider (b7e6e04666ca8dde560b69081c43365dce77d12a, 2018-06-22T05:11:25.722Z)
OS version: Darwin x64 17.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.45GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_12458977|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
intellij-idea-keybindings|k--|0.2.24

</details>

**Comment by chrmarti** [comment]
You might need to add `node_modules` to your `.gitignore` file from what I see. The `5k` badge refers to both modified and new files and your `node_modules` folder is shown in green for addition in the Explorer.
