### ISSUE TITLE
intelisense won't work for require with template strings

### ISSUE THREAD

**Issue by NikosEfthias** [Microsoft/vscode#5273]
- VSCode Version:1.8.2
- OS Version:ubuntu 15.10

Steps to Reproduce:
 ```javascript
const a=require("something") //autocomplete works great
const b=require('something') //autocomplete works great
const c=require(`something`) //will not autocomplete
```

**Comment by egamma** [comment]
Moving to the TypeScript repository for investigation.

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#8135

**Comment by egamma** [comment]
@NikosEfthias FYI the issue got moved to the TypeScript repository, where it is open. It got closed in this repository.
