### ISSUE TITLE
Allow root user to run --list-extensions without specifying --user-data-dir

### ISSUE THREAD

**Issue by lonix1** [Microsoft/vscode#52732]
**ENVIRONMENT**

I'm using vscode on linux. My backups are done via a cron job that runs as root.

**PROBLEM**

I want to backup the configuration and the list of extensions being used, [so I do this](https://stackoverflow.com/a/49398449/9971404):

    code --list-extensions > list-of-vscode-extensions.txt

That produces a text file I can include in the backup.

However since the backup runs as root, I get this error: `You are trying to start vscode as a super user which is not recommended. If you really want to, you must specify an alternate user data directory using the --user-data-dir argument.`

If I set `--user-data-dir` then it works, but produces stuff in that directory that I must delete every time.

**SUGGESTION**

When specifying `--list-extensions` it should not care whether you are running as root, and thus not ask for `--user-data-dir`, and also not write anything to anywhere. This is safe as after it lists extensions it doesn't load vscode anyway, and returns immediately to the prompt.

**Comment by TomSputz** [comment]
What? But the extensions are set per-user, how could code know where to look for the extensions if it isn't specified?

**Comment by lonix1** [comment]
@TomSputz I know I was wonderring that myself. But when I run that command as root it works - i.e. it shows me all installed extensions for my non-root user.

**Comment by chrmarti** [comment]
Couldn't you run that as the user? Which OS are you on?

**Comment by joaomoreno** [comment]
Shouldn't you run `sudo -u YOURUSER code --list-extensions > list-of-vscode-extensions.txt` instead?

**Comment by lonix1** [comment]
The problem is still there, try this:

    mkdir /tmp/datadir
    sudo code --user-data-dir /tmp/datadir/ --list-extensions

That works.

So:
- it tells me the extensions for a non-sudo user, which seems to be a bug
- vscode only prints some stuff and exits, so I it shouldn't be necessary to specify `--user-data-dir /tmp/datadir/` (if this is fixed then automated backups would work as root)

**Comment by joaomoreno** [comment]
@lonix1 Shouldn't you run `sudo -u YOURUSER code --list-extensions > list-of-vscode-extensions.txt` instead, to run the command as your original user?

**Comment by lonix1** [comment]
@joaomoreno Yes thanks that would work. I've since found a way to avoid this problem.

But  my point is that this issue is still valid and should not be closed because there is a potential bug or design flaw (i.e. not connected to my original problem, which I solved).

**Comment by joaomoreno** [comment]
`You are trying to start vscode as a super user which is not recommended.` is there for a reason: it is insecure, regardless of which operation you do. I will leave this as is. Thanks for the suggestion though.
