### ISSUE TITLE
Request: Provide a simple keyboard shortcut to "Show/Hide Line Numbers"

### ISSUE THREAD

**Issue by drankinatty** [Microsoft/vscode#52735]
One simple thing that is missing from the VS Editor is a simple way to "Show/Hide Line Numbers". It is a feature present in just about every editor I've ever used (even rudimentary ones). I was surprised after searching through Tools->Options->Text Editor->C/C++->General, and Tools->Customize->Commands, that there was no simple way to create a keyboard shortcut that would allow showing/hiding the line numbers at will. 

On Laptops and smaller screens, screen real estate is at a premium, and the numbers themselves can be distracting. However I do want them when I'm working through a list of compiler warnings/errors, etc. So being able to "Show/Hide Line Numbers" with a simple keystroke (rather than navigating Tools->Options->Text Editor->C/C++->General each time) would be great. The general menu location for the command is under the "View" menu to which a configurable shortcut can be assigned.

**Comment by chrmarti** [comment]
We try to keep additional functionality in extensions where possible. Thanks @TomSputz for the detailed reply!
