### ISSUE TITLE
预览Markdown文档时（包括点击预览标签时），出现显示错误

### ISSUE THREAD

**Issue by xhstdpgt** [Microsoft/vscode#52731]
**问题：**
菜单栏和整体显示位置不变，但下面紫色状态栏到菜单栏的界面看起来上移了——只能看到第6行和以下。
![vscode_](https://user-images.githubusercontent.com/22113494/41811171-40699cca-773d-11e8-903c-e84a41409af1.PNG)

**可能的原因：**
 快速多次点击”打开侧边预览“。

**Comment by RC-Wei** [comment]
Human translate:
  Question: The menu bar and the others display are working well, but the purple status bar below it seems moving up -- Just only display editor rows 6 and below ( It can't display 1 to 5 rows).
  Probably Reason: Click "OPEN MARKDOWN VIEW" too much and rapid.
(我只能帮你到这儿了)

**Comment by bpasero** [comment]
@xhstdpgt can you provide more exact steps in english?
