### ISSUE TITLE
VS code would not debug c# project on mac

### ISSUE THREAD

**Issue by hungarianguy** [Microsoft/vscode#52733]
- VSCode Version: 1.24.1
- OS Version: Mac Os Sierra High Sierra, 10.13.5

Steps to Reproduce:

1.  Create a .net sample project: dotnet new console -o testcshar
2. open VS code
3. open folder VS code
4. try Debugging pressing green error with breakpoint
    nothing happens

Does this issue occur when all extensions are disabled?: Yes/No
did not try since I believe C# extension is needed

**Comment by weinand** [comment]
pleas file issue against C# extension.

**Comment by hungarianguy** [comment]
can you let me know how to get debug log lines from vscode...

**Comment by weinand** [comment]
that depends on the extension your are using.
Please ask here: https://github.com/OmniSharp/omnisharp-vscode/issues

**Comment by hungarianguy** [comment]
It was actually a vscode issue.... i have uninstalled (https://stackoverflow.com/questions/42603103/how-to-completely-uninstall-vscode-on-mac) and reinstalled vscode and now things work

**Comment by weinand** [comment]
Not necessarily a VS Code issue. If you've followed the stackoverflow link, then you have removed all installed extensions and their extension state.
Probably it would have been sufficient to just remove the C# extension and reinstall it again. 
But I'm glad that you could fix the problem.
