### ISSUE TITLE
ERR_CONTENT_LENGTH_MISMATCH 

### ISSUE THREAD

**Issue by vammex** [Microsoft/vscode#52746]
Issue Type: <b>Bug</b>
Failed to load resource: ERR_CONTENT_LENGTH_MISMATCH 
it is terrible that i cannot search on the website
i have such an error and i dont have an option to just seek ERR_CONTENT_LENGTH_MISMATCH  on the awesome offsite!
what should i do with the error?

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (8.55GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe D:\ONVEGO\GoOld\App\index.html|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by chrmarti** [comment]
Could you describe what you were doing at the time this error occurred?

**Comment by vammex** [comment]
hi
nothing remarkable.. just refresh a page, and some important awesome files (like fontawesome-all.min.css or fontawesome-all.min.js) are not getting downloaded. thus the page looks ugly, you can expect

**Comment by chrmarti** [comment]
@vammex Are you reporting an issue for the website or for the desktop app?

**Comment by vammex** [comment]
website

**Comment by chrmarti** [comment]
What browser are you using?

**Comment by vammex** [comment]
chrome Version 67.0.3396.87

**Comment by octref** [comment]
@vammex I'm on the same version. Can you show us a screenshot of what's happening? (With devtools open). Also what are the Chrome extensions you installed that might cause this (Adblockers, Tampermonkey, etc)?

**Comment by vammex** [comment]
it happened a week ago. i dont have a screen...
i didnt install addons

**Comment by octref** [comment]
So it doesn't happen anymore? If it does, feel free to reopen.
