### ISSUE TITLE
Floating debug toolbar not clickable with custom titlebar 

### ISSUE THREAD

**Issue by zurkoxxx** [Microsoft/vscode#52748]
- VSCode Version: 1.25.0-insider
- OS Version: Win 10 (10.0.17692)

Steps to Reproduce:

1. set `"window.titleBarStyle": "custom" `
and `"debug.toolBarLocation": "floating"`
2. start debugger
3. try to click on any debugger button

it just clicks on titlebar as if debug toolbar wasn't there

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/12783209/41818101-8c048a1e-77b0-11e8-81ec-ca9fe911418c.png)

**Comment by weinand** [comment]
No, this is not a duplicate of a test item but a real bug.

**Comment by isidorn** [comment]
I have pushed a fix for this and you can try see it in tomorrows insiders.
@zurkoxxx let us know if that fixes the issue tomorrow - thanks!

**Comment by zurkoxxx** [comment]
works like a charm :)

**Comment by isidorn** [comment]
Thanks, adding verified label
