### ISSUE TITLE
Embedded terminal degraded on Linux

### ISSUE THREAD

**Issue by alekseyt** [Microsoft/vscode#52749]
Issue Type: <b>Bug</b>

Steps to reproduce:

1. Open embedded terminal or start build in terminal
2. Select a portion of text with mouse
3. Try to paste this text into editor using ~~middle mouse button~~ Shift+Insert

On Linux selected text is usually already in clipboard when it is selected on screen and could be pasted using middle mouse button or Shift+Insert. This was working before just fine, but after update to newer vscode i have to right click on selected text, select "Copy" and then paste selected text with Ctrl+V.

I can't copy selected text with Ctrl+C because, obviously, Ctrl+C closes the terminal.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:47:35.732Z)
OS version: Linux x64 4.4.0-112-generic

<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.19.1
nightswitch-lite|gha|2.1.0
cpptools|ms-|0.17.5
Go|ms-|0.6.83
shader|sle|1.1.3
cmake|twx|0.0.17
code-navigation|vik|0.2.0
vscode-todo-highlight|way|0.5.12
lua-for-vscode|xxx|0.0.23

(1 theme extensions excluded)

</details>

**Comment by Strum355** [comment]
Ive never seen that selected text is in the clipboard on Linux. Either way, Ctrl+Shift+C for copying and Ctrl+Shift+V for pasting, same as in gnome terminal

**Comment by alekseyt** [comment]
It also would be nice to have this on Windows + vscode + git bash. It works if i open standalone git bash, but doesn't work with git bash as a shell for vscode:
```
"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
```

Usual use-case for this is the following:

1. `git log`
2. Double click commit hash to select it
3. `q` (to exit `less` spawned by git)
4. `git checkout <Shift+Insert>` or `git reset <Shift+Insert>` or whatever with Shift+Insert

**Comment by Strum355** [comment]
`On Linux selected text is usually already in clipboard when it is selected on screen` i have never seen this being the case before, I know its definitely not default setting on any of my Linux machines. The standard way to copy things from the terminal is with Ctrl+Shift+C

**Comment by Tyriar** [comment]
ctrl+shift+c/v is the default on Linux. You can configure how copy/paste works on all platforms: http://www.growingwiththeweb.com/2017/03/mastering-vscodes-terminal.html#copy-and-paste

**Comment by alekseyt** [comment]
@Tyriar i swear this was working before, but i reverted vscode version back to 1.16.1 and i can't make it work. Surprisingly middle mouse click works as expected: it pastes selection without pressing any hotkeys, just select text with left mouse button, then middle click and correct paste appears, but Shift+Insert pastes wrong clipboard. Is there a way to bind primary clipboard or whatever is on middle mouse click to Shift+Insert? Or does it make sense to file a feature request?

**Comment by Tyriar** [comment]
@alekseyt no there's no way to bind primary clipboard to shift+insert (and you never could). Here's the issue https://github.com/Microsoft/vscode/issues/36170

**Comment by alekseyt** [comment]
WTF, this is ... unexpected. Sorry for bothering you, i must have mistaken something. Terminal in vscode is just too convincing, i probably assumed that it just got broken but instead i should have reverted vscode to previous version before reporting bug. I'll +1 feature request, thank you.
