### ISSUE TITLE
Better update progress, when explicitly checking for updates

### ISSUE THREAD

**Issue by fuzenco** [microsoft/vscode#52744]
Issue Type: <b>Feature Request</b>

Checking for Updates feels too hidden in the bottom-left gear icon. Once clicked, you still have to scroll down for the update button. Plus, there's not visible progress bar (indicator) in the UI once you've clicked it.

VS Code version: Code - Insiders 1.25.0-insider (c5c7d43b65bcbbb3851fbd972fad077631c707e3, 2018-06-21T05:11:06.323Z)
OS version: Darwin x64 17.6.0

**Comment by MorganMarshall** [comment]
If you click the top help menu item, "check for updates" is there also.

**Comment by joaomoreno** [comment]
Actually, it is my impression that most people argue the opposite: they just don't care about update progress as long as the application eventually updates. Do you know when Chrome updates, and while it does what is its progress? What about Spotify?

Our goal here is to have seamless updates such that you don't even think about them any more.

**Comment by fuzenco** [comment]
At least on Mac which I’ve run for 20 years, if a person actively/manually chooses to update an app, 99% of apps I’ve used have always shown a progress indicator. If it’s updated silently in the background, then yes I agree with you.

**Comment by joaomoreno** [comment]
That's actually a good point!
