### ISSUE TITLE
Cursor disappears when using touchscreen

### ISSUE THREAD

**Issue by TheBrenny** [microsoft/vscode#52747]
Issue Type: <b>Bug</b>

So this was odd... I'm not sure if this is a Windows issue or a VSCode issue, but when using the touchscreen, it is expected that the cursor hides, but then when using the mouse again, it should reappear. This is not the case however, when you *tap* on File > Open Folder.../File...

The mouse stays hidden and shows when Alt+Tabbing out, but is purely hidden until you escape from the dialog box.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (2.08GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
jshint|dba|0.10.19
vscode-eslint|dba|1.4.12
EditorConfig|Edi|0.12.4
php-debug|fel|1.12.3
beautify|Hoo|1.3.2
vscode-JS-CSS-HTML-formatter|lon|0.2.3
ftp-sync|luk|0.3.3
vscode-apache|mrm|1.1.1
python|ms-|2018.5.0
cpptools|ms-|0.17.4
csharp|ms-|1.15.2
debugger-for-chrome|msj|4.6.0
vscode-docker|Pet|0.0.27
java|red|0.26.0
vscode-icons|rob|7.23.0
code-settings-sync|Sha|2.9.2
vscode-hexdump|sle|1.6.0
autoimport|ste|1.5.3
vscode-arduino|vsc|0.2.17
vscode-java-debug|vsc|0.9.0

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to the code. As such, I will go ahead and close it. If you can identify the component that is causing the issue, please report it upstream:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.
