### ISSUE TITLE
TypeScript extension ignores type guards on properties

### ISSUE THREAD

**Issue by Tomeamis** [Microsoft/vscode#52757]
Issue Type: <b>Bug</b>

In the following TypeScript snippet
```ts
let obj: any = {cpp: ["hello"]}
if(obj && typeof obj === "object" && (obj.cpp instanceof Array))
{
	let cpp = obj.cpp as Array<any>
	return cpp.every(val => typeof val === "string")
}
```
I would expect `obj.cpp` to be considered `any[]` inside the `if` block.

However, when I hover over `obj.cpp` in the `if` block, the hover still says the type is  `any`. This also affects code completion.

Note that when I only do 
```ts
if(obj instanceof Array)
{
	obj
}
```
the `obj` in the `if` block is correctly reported as `any[]`.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4712MQ CPU @ 2.30GHz (8 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (3.24GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Dev\youcompleteme-vscode|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|0.3.1
sftp|lix|1.2.2
youcompleteme-vscode|Tom|0.2.2

</details>

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#25198
