### ISSUE TITLE
regex replacement

### ISSUE THREAD

**Issue by bbsdkjdx** [Microsoft/vscode#52751]
Issue Type: <b>Bug</b>

It's no doubt that vscode is an awesome editor,but there is a little flaw in the replacement function.When do replace in the regex mode,if the target string set to "\1",it's just simply replace it to "\1",whitch in regex syntax,it should be the first caught group.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:52:25.282Z)
OS version: Windows_NT ia32 6.1.7601

**Comment by bbsdkjdx** [comment]
I was taught just now that the vscode regex syntex is like JavaScript regex,whitch use "$1" for the 1st caught group,not like the python regex syntax use "\1".
And I hope there is an setting or plugin can select the regex syntax to suilt all programmers.

**Comment by rebornix** [comment]
Right now we only support javascript regex in the editor. Close it for now as we don't have plans for supporting other syntax in the near term.
