### ISSUE TITLE
Visual Studio Code 1.0 no longer works with C#; C# not listed as a supported language

### ISSUE THREAD

**Issue by BeauBender** [Microsoft/vscode#5275]
- VSCode Version:1.0.0
- OS Version: Windows 10 Version 1511 (OS build 10586.164) 

Steps to Reproduce:

1. Upgrade to Visual Studio Code 1.0.0
2. Open a folder containing C# code
3. Note that auto-detection detects *.cs files as Plain Text
4. Try to change language to C# and find that C# is not listed

**Comment by BeauBender** [comment]
This just reproduced on a second Windows 10 machine with OS build 10586.218

**Comment by mattyork** [comment]
@BeauBender This is intentional. The C# plugin is now an additional install instead of bundled with the installer. https://code.visualstudio.com/updates/vFebruary#_languages-c35

**Comment by BeauBender** [comment]
Thanks, @mattyork ! 

It seems like there might still be a bug since this didn't work for me:
"...or if you already have a project with C# files, VS Code will prompt you to install the extension as soon as you open a C# file."

**Comment by egamma** [comment]
>"...or if you already have a project with C# files, VS Code will prompt you to install the extension as soon as you open a C# file."

The text is not accurate, sorry. We will only prompt when you had the C# extension installed previously. We do not prompt in a fresh install when the extension has never been installed. The C# extension will be recommended as an extension with 'Show Recommended Extensions'. Making the recommended extensions more popular is on the backlog.

**Comment by JohnGalt1717** [comment]
As of right now using current vs.net 2017 rc .csproj files neither the .sln nor the .csprojs are recognized. They don't show up in the selector down at the bottom left (there is no selector) and choosing a project manually from the pallet is hit or miss if it works at all.
