### ISSUE TITLE
Integrated Remote terminal or Putty terminal itself in VSCode

### ISSUE THREAD

**Issue by ashishmgofficial** [Microsoft/vscode#52754]
I believe 99 % working professionals connect to their client's system through Putty or any such remote provider and use that as their execution environment(at least in service based sector). So it becomes pretty cumbersome to code in our local system and then export it to that particular client system through WinSCP or any such systems to run it. 

I believe its high time VSCode should add maybe a terminal similar to putty integrated to vscode or may be an option to integrate putty terminal itself in vscode, like we have for other systems.

**Comment by Tyriar** [comment]
No plans to integrate putty, I think openssh in Windows 10 is the avenue we're going for here https://blogs.msdn.microsoft.com/commandline/2018/01/22/openssh-in-windows-10/
