### ISSUE TITLE
Reload with extensions enabled

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#52760]
There are two commands in the **Command Palette**:
- **Reload Window**
- **Reload Window With Extensions Disabled**

After one execute **Reload Window With Extensions Disabled**, how to reload again but with extensions enabled? I don't see such an option, so please add it. **Reload Window** reloads with extensions still disabled.

**Comment by RMacfarlane** [comment]
In the next release (1.25.0), `Reload Window` will reload the window with extensions enabled again (or whatever the previous state was). There will be a notification when `Reload Windows With Extensions Disabled` is run explaining how to exit:

![screen shot 2018-07-05 at 10 06 11 am](https://user-images.githubusercontent.com/3672607/42337301-3372fd98-803b-11e8-8259-7976f719d5f4.png)
