### ISSUE TITLE
Not able to move a folder to another directory

### ISSUE THREAD

**Issue by mittalyashu** [Microsoft/vscode#52761]
Issue Type: <b>Bug</b>

Error: EPERM: operation not permitted, rename 'starter-kit\index.js' -> 'starter-kit\components\index.js'

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:52:25.282Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.78GB (0.38GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe G:\gitlab\sass-starter-kit|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by chrmarti** [comment]
How are you moving the file? In the Explorer? Are you moving just `index.js`?

**Comment by mittalyashu** [comment]
I tried to drag the file using the explorer.

**Comment by isidorn** [comment]
Please file a new proper issue using this steps https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions
