### ISSUE TITLE
VSCode ignores editor.insertSpaces

### ISSUE THREAD

**Issue by MrVallentin** [Microsoft/vscode#5276]
- VSCode Version: 1.0.0
- OS Version: Windows 10

I was editing a `README.md` file, when VSCode prompted me to download the new VSCode update. Did so, but after when I continued editing then each time I hit <kbd>Tab</kbd> then the tab was promptly replaced with spaces.

My `User/settings.json` looks like this:

```json
{
	"editor.renderWhitespace": true,
	
	"editor.wrappingColumn": 10000000000000000000,
	
	"editor.tabSize": 4,
	"editor.insertSpaces": false
}
```

Tested out some different things, but it looks like `editor.insertSpaces` is ignored, and it simply uses spaces, if spaces previously have been used as any kind indention in the file. Though if both tabs and spaces have been used as indention, then it won't replace any following tabs with spaces.

**Comment by egamma** [comment]
// @isidorn and insights?

**Comment by isidorn** [comment]
Yes, we have changed this behavior in our latest release - more details can be found under 'Tab and Space indentation' [here](https://code.visualstudio.com/updates#_editor).

Here is the issues which motivated us to do the change https://github.com/Microsoft/vscode/issues/3259
Shortly use `editor.detectIndentation:false` if you want your old behavior back,

**Comment by MrVallentin** [comment]
@isidorn that's weird, I even checked [code.visualstudio.com](//code.visualstudio.com), but somehow I totally overlooked the "Tab and Space Indentation" section.
