### ISSUE TITLE
Unverified breakpoint, Breakpoints set but not bound

### ISSUE THREAD

**Issue by slipsnip** [Microsoft/vscode#52763]
- VSCode Version: 1.24.1
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Create index.html and script.js, add some javascript, link in source.js.  Create and save launch.json:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceFolder}"
        }
    ]

}
```
2) Set breakpoint on any line in javascript script.js
3) run google-chrome --remote-debugging-port=8080
3) Hover over the line you set breakpoint on (notice it is grey and tool-tip shows aforementioned error)

Does this issue occur when all extensions are disabled?: Yes

![vscode-breakpoint](https://user-images.githubusercontent.com/40281791/41822060-e9271d5e-77b7-11e8-9d89-c027a10b9547.png)

**Comment by roblourens** [comment]
You don't need to start chrome manually, the launch config will start Chrome for you.

Since you started Chrome on the same port as your webserver, 8080, please check that your page is actually running in Chrome correctly.

**Comment by Megabyteceer** [comment]
I had same problem. Reason was i deleted  "webRoot": "${workspaceRoot}"  entry from config. Breakpoints fixed after returning this line. Maybe its help.

**Comment by slipsnip** [comment]
I closed chrome prior to debuging.  Started a new project and created a repository with the problem code 
git@github.com:slipsnip/vscode-debug-breakpoints.git

**Comment by roblourens** [comment]
Your screenshot clearly shows that you started chrome in the terminal.

You need to start a webserver on port 8080 that serves your site.

**Comment by slipsnip** [comment]
OP Step 3 clearly states run google-chrome --remote-debugging-port=8080
The documentation on vscode is very unclear.

**Comment by slipsnip** [comment]
Thank you, my bad.
