### ISSUE TITLE
Error when updating

### ISSUE THREAD

**Issue by Yokaos** [Microsoft/vscode#52764]
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2131073/vscode-inno-updater.log)

**Comment by joaomoreno** [comment]
You seem to have #47841.

Please read this comment if you can provide more detail: https://github.com/Microsoft/vscode/issues/47841#issuecomment-393101777

Please read this one to disable background updates: https://github.com/Microsoft/vscode/issues/47841#issuecomment-395017687

Also read this one to provide feedback on our new user setup: https://github.com/Microsoft/vscode/issues/47841#issuecomment-399941682
