### ISSUE TITLE
Caret position wrong when typing Thai.

### ISSUE THREAD

**Issue by first087** [Microsoft/vscode#5277]
- VSCode Version: 1.0.0
- OS Version: OS X 10.11.4

Steps to Reproduce:

1. Typing English characters.
2. Typing Thai characters.

Click for see video.
[![Screenshot](https://gist.github.com/first087/4bf9f56cdc23c3dd5d671a54e2f61e5d/raw/c436a48b9fef7fa933da130810cd7a3997cefcdf/VSCode%2520v1.0.0%2520Bug%2520Report.png)](https://gist.github.com/first087/4bf9f56cdc23c3dd5d671a54e2f61e5d/raw/39cfc0cd655a664d55ce64a776b5346caf506627/VSCode%2520v1.0.0%2520Bug%2520Report.mp4)

**Comment by spywhere** [comment]
For workaround, you could set `editor.fontLigatures` to `true` this also solve the floating/sinking vowels in some cases.

**Comment by spywhere** [comment]
I think this also a dup of #747.

**Comment by alexandrudima** [comment]
Indeed, it is a dup of #747 which got resolved with our upgrade to Electron v0.37.6 which includes Chromium 49
