### ISSUE TITLE
Markdown Syntax Highlighting Bold & Italics Bug

### ISSUE THREAD

**Issue by McPrescott** [Microsoft/vscode#52771]
Issue Type: <b>Bug</b>

Syntax highlighting is broken for multiple lines (which I have seen has been reported and closed), and it also breaks when bold or italic content begins with a non-alphanumeric character (brackets, punctuation, etc.).

![screenshot from 2018-06-24 15-03-19](https://user-images.githubusercontent.com/20735042/41823650-c8516a7c-77c0-11e8-88ca-35770c7b1101.png)
 

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:47:35.732Z)
OS version: Linux x64 4.13.0-45-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 1771)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|7.67GB (0.23GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by mjbvz** [comment]
Yes this is not easy to fix because the grammar engine we use for syntax highlighting primarily works per lines. Closing as out of scope
