### ISSUE TITLE
Git conflict resolution when remote file is deleted

### ISSUE THREAD

**Issue by ThetaSinner** [Microsoft/vscode#52787]
I'm using Code for my merges these days and it's brilliant apart from deleted files.

When you've modified a file locally but it's been deleted remotely then there is no way to accept the remote change in Code.
You can copy changes into your local and commit if you wanted to keep the file.
If you want to accept the remote delete then you need to do a git remove locally.

It would be great to support git remove when you right click on the file (in the context menu with open file and stage changes)

**Comment by MaxMilton** [comment]
I tend to run into this a lot. In an active projects with a decent size team of devs it's a common occurrence.

Would be great to have some way to decide quickly in the UI. A note like "This file was removed in the remote repository, what would you like to do? [Keep] / [Remove]".

**Comment by joaomoreno** [comment]
Good news guys, just implemented handling `Deleted By Them` and `Deleted By Us` conflicts!
