### ISSUE TITLE
Custom menu bar: clicking a menu has no effect with menuBarVisibility = toggle

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#52788]
With the following settings:
```json
    "window.titleBarStyle": "custom",
    "window.menuBarVisibility": "toggle"
```
1. Maximize the window
1. Move the cursor so that it is located inside the title bar
2. Press the ´Alt´ key
3. Click a menu item -> the menu doesn´t pull up.

**Comment by sbatten** [comment]
dupe of #52522
