### ISSUE TITLE
Hindi & Chinese Unicode symbols & characters appear garbled inside integrated terminal 

### ISSUE THREAD

**Issue by laxmansahni** [Microsoft/vscode#52784]
Integrated terminal fails to display Hindi & Chinese symbols & characters.

VSCode Version: 1.24.1(24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:36:01.396Z)
OS Version: macOS High Sierra 10.13.4
<img width="435" alt="- -" src="https://user-images.githubusercontent.com/1550393/41837369-dde8b6d2-787a-11e8-9d3d-2d46909cde48.png">
<img width="259" alt="- -" src="https://user-images.githubusercontent.com/1550393/41837370-de30bc48-787a-11e8-942e-34df6c65acb7.png">

Steps to Reproduce:

1. create folder नमस्ते in Hindi & folder 你好 in Chinese with macOS's built-in terminal
2. Launch VS code and go to integrated terminal
3. type cd {parent folder} of newly created folders
4. type ls

Actual output:
garbage output ?? is displayed. 

Expected output:
It should display list of folders with actual names नमस्ते & 你好

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
I can't reproduce this, have you tried to use a different font?

**Comment by laxmansahni** [comment]
It's working now. Closing the issue. 
<img width="1209" alt="screen shot 2018-06-27 at 2 28 55 pm" src="https://user-images.githubusercontent.com/1550393/41964090-cae6d1de-7a16-11e8-993d-e590920ca2fe.png">
