### ISSUE TITLE
Emacs-like up-list (navigation command)

### ISSUE THREAD

**Issue by StoffePro** [microsoft/vscode#52790]
This is one of the emacs-isms that hurts the most to not have:

> (up-list &optional ARG ESCAPE-STRINGS NO-SYNTAX-CROSSING)
> 
> Move forward out of one level of parentheses.
> This command will also work on other parentheses-like expressions defined by the current language mode. 

(IOW jump to the character after the next enclosing close-paren).

Not sure how it should be named. Maybe cursorParenEndRight (and left)? Or would that exclude brackets etc?

**Comment by StoffePro** [comment]
Should have the feature request label, but it doesn't look like I can assign it myself? Either that or i've just gone blind.

**Comment by alexandrudima** [comment]
This could also be implemented from an extension.

**Comment by StoffePro** [comment]
Sure. Do you think that would be better? It seems like a core code-navigation feature to me, but I'm new here, so I'm not going to insist. :)

I'm sure I could implement it myself. Do you think that would be welcome?
