### ISSUE TITLE
Can not use the "Format Document" command with most file types

### ISSUE THREAD

**Issue by benm-eras** [Microsoft/vscode#52791]
Issue Type: <b>Bug</b>

I first noticed this with C# files, but I have been through the list of languages and I can only use the "Format Document" (Ctrl+Shift+F) in a few (JSON and HTML for example), but not in some that I am pretty sure should have formatters built into VS Cose (~~Javascript,~~ CSS), and others where an extension should take care of it (C#). When I use the command I get "There is no document formatter for 'csharp'-files installed" messages.

I have uninstalled all my extensions and wiped my user settings and I have even re-installed VS Code, but no luck.

It used to work, but I have been working mainly on projects using VS2017 for a while so I am afraid I cannot pin-point when it stopped working properly as I put off dealing with it assuming I'd be able to sort it out when I needed to.

**Edit:**
I initially stated that the format for Javascript wasn't working, but since explicitly enabling all the "built-in" formatters (pretty sure they were all left at default values before though) it has started to work.

![image](https://user-images.githubusercontent.com/30234297/41852040-dbe2568e-7881-11e8-8179-7ce88ba7210c.png)

**Another Edit**
Actually this might be a problem with the C# extension as it doesn't seem to be doing... well anything. As described [here](https://github.com/OmniSharp/omnisharp-vscode/issues/2391).

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3450 CPU @ 3.10GHz (4 x 3096)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.96GB (3.83GB free)|
|Process Argv|D:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.15.2

</details>

**Comment by chrmarti** [comment]
For JSON and HTML formatting make sure you did not disable the built-in extensions. For C# I can't get it to work either (tried 1.24.1 and 1.25 insiders).

**Comment by chrmarti** [comment]
For JSON and HTML formatting make sure you did not disable the built-in extensions. For C# I can't get it to work either (tried 1.24.1 and 1.25 insiders).

**Comment by chrmarti** [comment]
For JSON and HTML formatting make sure you did not disable the built-in extensions. For C# I can't get it to work either (tried 1.24.1 and 1.25 insiders).

**Comment by chrmarti** [comment]
For JSON and HTML formatting make sure you did not disable the built-in extensions. For C# I can't get it to work either (tried 1.24.1 and 1.25 insiders).

**Comment by roblourens** [comment]
If it's just C# that's not working, that would be an issue with the extension. Looks like you've found their repo, you can open an issue on them if there isn't one already.
