### ISSUE TITLE
Test API for preselected items

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#52798]
Refs: #35551

- [x] any @sandy081 
- [ ] any @ramya-rao-a 

Complexity: 1

A completion item can ~~not~~ now be marked as preselected. That means the UI is more likely to select that item. 'More likely' because such items can still be filtered out or ranked low and then they aren't selected. Also, suggest memories overwrite the preselect-property. Test that all of that works.

**Comment by jrieken** [comment]
FYI - to test against the latest API do the following:

* open your extensions `package.json` file
* change the `engine.vscode` property to `*`
* run `npm run postinstall` (assuming you have the `vscode` module as dev-dependency)
* undo the engine-version change from step 2

**Comment by jrieken** [comment]
assigning @ramya-rao-a because of emmet

**Comment by sandy081** [comment]
@jrieken Do you mean `can` here - `A completion item can not be marked as preselected.`?

**Comment by jrieken** [comment]
ops. thanks @sandy081. corrected.

**Comment by ramya-rao-a** [comment]
Verified that the pre-selected item is pre-selected when completion is triggered and there is no text before the cursor
