### ISSUE TITLE
Add terminal window(terminal service) in workbench

### ISSUE THREAD

**Issue by javagg** [Microsoft/vscode#528]
The workbench on visual studio online on Azure has a nice power-shell terminal to let user work with their workplace in cloud. Other mature IDE products also have term window in their workbench. That way, user can interactively exec some command without switch between desktop and vscode window.

**Comment by Tyriar** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/143, it's coming in the next stable release!
