### ISSUE TITLE
Hide reset link

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#52808]
Issue Type: <b>Bug</b>

We had discussed to remove the reset link and do the "right" thing and remove the actual entry in the `settings.json` when the actual value is the same as the default.

<img width="508" alt="screen shot 2018-06-25 at 3 55 43 pm" src="https://user-images.githubusercontent.com/4674940/41854434-888f27aa-7890-11e8-82ac-e2896f80877a.png">

VS Code version: Code - Insiders 1.25.0-insider (5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3, 2018-06-25T09:32:08.937Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.26GB free)|
|Process Argv|/Users/kmaetzel/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_17449123|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
solargraph|cas|0.17.4
npm-intellisense|chr|1.3.0
regex|chr|0.2.0
githistory|don|0.4.1
tslint|eg2|1.0.33
vscode-npm-script|eg2|0.3.4
vsc-material-theme|Equ|2.1.0
git-project-manager|fel|1.6.1
crazy|kie|0.0.2
svgpreview|kis|0.2.0
vscode-azurestorage|ms-|0.3.1
mssql|ms-|1.3.1
python|ms-|2018.6.0
azure-account|ms-|0.4.0
azurecli|ms-|0.4.2
Go|ms-|0.6.83
vsliveshare|ms-|0.3.319
printcode|nob|2.3.0
vscode-docker|Pet|0.0.27
material-icon-theme|PKi|3.5.0
Ruby|reb|0.18.0
kustovscode|sea|0.0.1
php-syntax-visualizer|vsc|0.0.1
vscode-open-in-github|ziy|1.3.3

(3 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
It will be impossible to set a workspace setting to a default to override a user setting. But we can call that an "advanced" feature that they can use the JSON editor for.

**Comment by roblourens** [comment]
And another option is to only 'reset' if the workspace setting's default value doesn't conflict with the current user setting's value, but I'd worry that would look inconsistent and confusing.

**Comment by roblourens** [comment]
It's also not great for text fields.

Could apply @misolori's suggestion of showing the default value in the placeholder text for those.
