### ISSUE TITLE
Test improved workspace edit api

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#52800]
Refs: #10659

- [x] win @isidorn
- [x] linux @joaomoreno 

Complexity: 2

We have enhanced the WorkspaceEdit-api to allow to create, delete, and rename files. Test that

* everything works as advertised
* things behave reasonable in corner cases, e.g. delete a file, then update it

**Comment by jrieken** [comment]
FYI - to test against the latest API do the following:

* open your extensions `package.json` file
* change the `engine.vscode` property to `*`
* run `npm run postinstall` (assuming you have the `vscode` module as dev-dependency)
* undo the engine-version change from step 2
* from the vscode-repo copy the `vscode.proposed.d.ts`-file into your project
* in your `package.json` file add `enableProposedApi: true`

**Comment by isidorn** [comment]
Here's an example to help with testing

```
'use strict';
// The module 'vscode' contains the VS Code extensibility API
// Import the module and reference it with the alias vscode in your code below
import * as vscode from 'vscode';

// this method is called when your extension is activated
// your extension is activated the very first time the command is executed
export function activate(context: vscode.ExtensionContext) {

    let disposable = vscode.commands.registerCommand('extension.sayHello', () => {
        const workspaceEdit = new vscode.WorkspaceEdit();
        workspaceEdit.deleteFile(vscode.Uri.file('/Users/isidor/development/w/june/one'));
        workspaceEdit.createFile(vscode.Uri.file('/Users/isidor/development/w/june/two'));
        workspaceEdit.renameFile(vscode.Uri.file('/Users/isidor/development/w/june/two'), vscode.Uri.file('/Users/isidor/development/w/june/two'));
        vscode.workspace.applyEdit(workspaceEdit);
    });

    context.subscriptions.push(disposable);
}

```
