### ISSUE TITLE
Emmet weird CSS expansion 

### ISSUE THREAD

**Issue by hmalaud** [Microsoft/vscode#52801]
- VSCode Version: 1.24.1
- OS Version: Mac OS Sierra

Sorry to dig that up, but I've been spending the whole morning trying to find a solution and only found users having the same problems I'm experiencing right now but no solution to it. 
While the suggestions used to work properly, they recently stopped, and when w10 was working correctly, it does not anymore, without any change on my behalf (tried to reinstall VS Code, didn't change anything). This problem has also been reported multiple times (#28933 is one among others), but the issues I stumbled upon are now closed.

Examples of unexpected behaviors:
- df now gives stroke-dashoffset: 
- db -> box-decoration-break: 
- posa -> padding-block-start: 
- w -> white-space: 
- p -> pad: 
...

Thanks a lot for any help.

Edit : this seems to happen in some .styl files but not in all of them

**Comment by ramya-rao-a** [comment]
Below is a .styl file that I tried your examples on. All work as expected.

![styl](https://user-images.githubusercontent.com/16890566/41867804-fc802e7a-7868-11e8-9055-af4564928e49.gif)

Please share a small code sample where you can consistently repro the issue.

Do you see this issue only in .styl files or even in css/scss/less files?

**Comment by hmalaud** [comment]
Thank you for your answer. After a night of the computer being turned off, it started working again in every file I've been testing this morning. Like I said, this only occurred in some of many .styl files yesterday.
Sorry for the trouble!

**Comment by ramya-rao-a** [comment]
No problem, Happy Coding!
