### ISSUE TITLE
context menu of tree view explorer shows and disappears immediately

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/vscode#52803]
- VSCode Version: 1.24
- OS Version: Windows

Steps to Reproduce:

1. Install [Azure IoT Toolkit](https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.azure-iot-toolkit)
2. Move the 'Azure IoT Hub Devices' explorer to some position near the bottom
3. Click the **...**

![explorer_bug](https://user-images.githubusercontent.com/1050213/41852368-7795c42c-78bd-11e8-9b2e-99aa4735ec20.gif)

Actual:
The context menu shows and disappears immediately

**Comment by formulahendry** [comment]
Not try it on other extension, but I guess it could also repro on other view since there is no special things in this extension, just use the tree view app to redenr the view.

**Comment by sandy081** [comment]
@formulahendry Can you please confirm if it also happens on other views like `Extensions Viewlet` ?

**Comment by formulahendry** [comment]
I could confirm it happens in 'Explorer Viewlet', but for 'Extensions Viewlet', is seems there is no '...' and I could not use extension api to contribute to the 'Extensions Viewlet'.

**Comment by formulahendry** [comment]
I guess this issue would happen when the context menu has several items and the explorer is near the bottom.

**Comment by sandy081** [comment]
There is `...` action in extension viewlet. Please see the attachment here.

![image](https://user-images.githubusercontent.com/10746682/41996184-69128956-7a54-11e8-8385-23d7959dce13.png)

I would like to know if it is happening everywhere or only at one place.

**Comment by formulahendry** [comment]
Got it. Thanks for the screenshot. This issue could not repro on 'Extensions Viewlet'

**Comment by sandy081** [comment]
@bpasero I could reproduce the issue with the outline view `...` menu on windows. As user mentioned, it only happens when the context menu is shown above `...`. When it is has to be shown below `...` it is good.

**Comment by bpasero** [comment]
I can reproduce, it looks like one entry is automatically selected if the menu opens to the top. This will improve when @sbatten custom menu lands as default.

**Comment by formulahendry** [comment]
Hi there, do we have any ETA for fixing this issue? Several our customers meet with this issue. Most of them have no idea to resolve this. 😢   Thanks a lot!

**Comment by formulahendry** [comment]
Ping @sbatten

**Comment by formulahendry** [comment]
Hi @sbatten , thanks a lot for the information! Could I know when this issue could be fixed or when the `window.titlebarStyle => custom` would be default? Several customers meet with this issues when using [Azure IoT Toolkit](https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.azure-iot-toolkit) and reported to us, and we see hundreds of event triggered to hit this issue in one day time frame. So it is really important issue for us. Thanks a lot!

**Comment by formulahendry** [comment]
Ping @sbatten

**Comment by sbatten** [comment]
@formulahendry In order to establish a high quality experience, we will keep the feature available but disabled by default until we are sure the quality is there and the users that have tried it are satisfied with the new experience.

**Comment by formulahendry** [comment]
Thanks @sbatten for the info. If the custom titlebarStyle would not be default in short term, could we have a fix for the current default titlebarStyle? Since ths issue really affect a lot of users.. Thanks a lot!

**Comment by bpasero** [comment]
We will change to custom menus on Windows. For now you can set `"window.titleBarStyle": "custom"`.

**Comment by formulahendry** [comment]
@bpasero Awesome! So the `custom menus` will be enabled as default for v1.27?
