### ISSUE TITLE
Regression: `revealIfOpen` does not work any more

### ISSUE THREAD

**Issue by ddotlic** [Microsoft/vscode#52807]
Issue Type: <b>Bug</b>

Some time in the time frame of the 1.25 (insider) release the option `revealIfOpen` stopped working.
1.24.1 works fine.
Disabling all extensions does not help.

VS Code version: Code - Insiders 1.25.0-insider (5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3, 2018-06-25T09:32:08.937Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|22%|

</details>

**Comment by bpasero** [comment]
Great catch 👍

**Comment by ddotlic** [comment]
@bpasero Well, I **do** use the feature 😉 Thanks for the lightning fast fix!
