### ISSUE TITLE
Test Custom View API improvements

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#52806]
Refs: #48198 #49311 #50662 

- [x] anyOS @isidorn
- [x] anyOS @weinand 

Complexity: 2

Write an extension that contributes a tree view to the Explorer. Refer to [documentation](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesviews) and [ftpExplorer](https://github.com/Microsoft/vscode-extension-samples/blob/master/tree-view-sample/src/ftpExplorer.textDocumentContentProvider.ts).

- Test listening to `onDidChangeSelection` event when the selection changes.
- Test `visible` property and the corresponding `onDidChangeVisibility` event are working as expected when the tree view contents are visible or not.  **NOTE:** `visible` is `false` when the tree view is collapsed.
- Test passing focus flag to `reveal` api and make sure that revealed element is focused - `reveal(element: T, options?: { select?: boolean, focus?: boolean }): Thenable<void>;`

**Comment by weinand** [comment]
@sandy081 Writing an extension can only have a complexity of 3 and more...

**Comment by isidorn** [comment]
@sandy081 please provide an extension that is creating a tree view, since the one you attached is not using the new api.
Writing a new extension that does all this seems like a much higher compleixty
Thanks

**Comment by weinand** [comment]
@isidorn I've updated https://github.com/weinand/vscode-processes to the new API. You can use this as a sample.

**Comment by isidorn** [comment]
@weinand thanks!

**Comment by sandy081** [comment]
@isidorn FTP Explorer uses the Tree view implementation. Updated the description to use that sample.
