### ISSUE TITLE
Tab titles in settings editor seem too small

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#52810]
Issue Type: <b>Bug</b>

See screen shot. The tab titles in the settings editor seem too small in comparision to the rest of the font sizes used. Also, it seems that the spacing between the text above the tabs and the tabs is too small. 

<img width="1074" alt="screen shot 2018-06-25 at 4 03 29 pm" src="https://user-images.githubusercontent.com/4674940/41854771-53661cfe-7891-11e8-953c-ea621035d0b5.png">

VS Code version: Code - Insiders 1.25.0-insider (5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3, 2018-06-25T09:32:08.937Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (1.30GB free)|
|Process Argv|/Users/kmaetzel/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_17449123|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by roblourens** [comment]
Tabs = user/workspace settings right?

**Comment by roblourens** [comment]
@misolori pointed out that the tabs match the tabs in the panel and we think the tabs fit in to the rest of the text on the page. How much bigger do you think they should be?

We did tweak the padding between the tabs and "For advanced customizations..." and the search box above.
