### ISSUE TITLE
Intellisense shows foreach loop snippet after typing 'fun'

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5281]
- VSCode Version: 1.0.0-alpha
- OS Version: Windows 10/Ubuntu 15.10

Steps to Reproduce:

1. Open a javascript file
2. Type "fun"
3. Scroll to the bottom of the intellisense suggestions to see snippets

Actual:
Shows the foreach snippet suggestion even though isn't relevant after typing 'fun'

![funintellisense](https://cloud.githubusercontent.com/assets/12900364/14545963/db14e224-0256-11e6-810b-3293ee8b5128.PNG)

**Comment by jrieken** [comment]
This is the actual design behaviour. 

1. You type `fun` and trigger intellisense (discard the suggest on type box) -> no 'foreach' shows
2. You type `f` and intellisense comes up cos of typing -> It shows all suggestions for `f` keeps selecting the best match as you continue typing
