### ISSUE TITLE
Test: showQuickPick, showInputBox API

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#52818]
- [x] anyOS @joaomoreno 
- [x] anyOS @rebornix 

Complexity: 3

Test the `showQuickPick` and `showInputBox` APIs. The implementation of these two APIs has changed quite a bit. Make sure nothing broke, including the various method overloads, options and callbacks.

**Comment by joaomoreno** [comment]
FYI - to test against the latest API do the following:

* open your extensions `package.json` file
* change the `engine.vscode` property to `*`
* run `npm run postinstall` (assuming you have the `vscode` module as dev-dependency)
* undo the engine-version change from step 2
* from the vscode-repo copy the `vscode.proposed.d.ts`-file into your project
* in your `package.json` file add `enableProposedApi: true`

**Comment by chrmarti** [comment]
@joaomoreno This is the existing API, copying your instructions over to #52820. Thanks!

**Comment by joaomoreno** [comment]
@chrmarti I just realised that while testing. 😄
