### ISSUE TITLE
Improve Linux product build

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#52819]
We should maybe:

1. Build and publish ZIP
2. Build and publish DEB
3. Build and publish RPM

Right now we're doing the following:

1. Build ZIP, RPM, DEB
2. Publish ZIP
3. Publish DEB
4. Publish RPM

**Comment by joaomoreno** [comment]
There's a current dependency between building the deb and the archive: the archive takes the version computed by the deb building for its public name...

@Tyriar Why do we have this version number in the archive again? Does it need to be (or should it be) the same as the deb?

**Comment by Tyriar** [comment]
@joaomoreno the "revision number" (epoch timestamp) is used in the file names primarily to differentiate code_1.26.0_amd64.deb/zip/rpm from the following build in your downloads folder. However, for the deb package it is also used as the revision number for the package which defines the upgrade path. You can only upgrade from 1.26.0 to another 1.26.0 if the revision number is higher.

In an ideal world it would be the same for all the packages as you can use that to check the exact version, but it doesn't really matter (rpm is different I see). Feel free to give the zip and deb packages different numbers to make this easier.

**Comment by Tyriar** [comment]
Thanks @joaomoreno!
