### ISSUE TITLE
Setting `zenMode.hideStatusBar` needs workbench reload

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#52814]
The `zenMode.hideStatusBar` setting (& similar) should work dinamically, without requiring a workbench reload.

**Comment by isidorn** [comment]
The setting does not require a workbench load, but a zen mode reload.
All those settings are what happens when you enter zen mode, not while you are in zen mode.

Though I understand that it would be better if they just worked.
Treating as a feature request and assigning to july to investigate

**Comment by isidorn** [comment]
None of the thousands of zen mode users complained about this -> closing as out of scope
