### ISSUE TITLE
TOC synchronisation is off when using keyboard to scroll

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#52817]
Issue Type: <b>Bug</b>

The synchronization between the list of settings and the TOC is working well when using the mouse to scroll through the list. However, when I use arrow keys to navigate the list of the settings, the synching is off (as it seem to be using the same algorithm as for mouse scrolling). The sync mechanism needs to consider the keyboard focus. Still needs to handle the case when I start scrolling using the mouse while an entry in the list of settings has the keyboard focus.

See the current behavior:
![swrg5zufji](https://user-images.githubusercontent.com/4674940/41856178-bf82cb6e-7894-11e8-869c-49b14d5df283.gif)

VS Code version: Code - Insiders 1.25.0-insider (5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3, 2018-06-25T09:32:08.937Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.06GB free)|
|Process Argv|/Users/kmaetzel/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_17449123|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by roblourens** [comment]
I guess it can use the selection if the selection is in the viewport, otherwise ignore it.
