### ISSUE TITLE
Test: Portable Mode

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#52823]
- [x] macOS @octref  
- [x] linux @mjbvz 
- [x] windows @alexandrudima 

Complexity: 3

- Go through the preview documentation: https://github.com/Microsoft/vscode-docs/blob/vnext/docs/editor/portable.md
- Give it a good smoke test
- Also provide issues for improving the documentation

**USB Drive**

It would be pretty cool to test this setup on a USB Drive. I suggest using something reasonably fast, at least USB 3.0. Give it a smaller perf test around that setup and provide feedback on it.

**Comment by mjbvz** [comment]
@joaomoreno I'm having trouble getting this working on macos or linux. After creating the `code-portable-data` folder, the downloaded insiders instance still picks up my global state/config

Do I need to uninstall my existing insiders build before trying to setup a portable instance? Any other steps required to get this working?

**Comment by octref** [comment]
@joaomoreno On macOS, when I run the App, nothing happens. No files created in `code-insiders-portable-data`. All my settings / keybindings are the ones in the installed Insiders.

Did I do something wrong?

@mjbvz Notice that you need to use `code-insiders-portable-data`.

**Comment by octref** [comment]
@joaomoreno I'm guessing that's because when macOS is running each app in another location? See the `AppTranslocation`:

![image](https://user-images.githubusercontent.com/4033249/41947528-e65f437e-796c-11e8-8717-e0bc40e8304f.png)

When I run it through cli like this, it works fine:

```
./Visual\ Studio\ Code\ -\ Insiders.app/Contents/MacOS/Electron
```

**Comment by joaomoreno** [comment]
> @joaomoreno I'm having trouble getting this working on macos or linux. After creating the code-portable-data folder, the downloaded insiders instance still picks up my global state/config
>
> Do I need to uninstall my existing insiders build before trying to setup a portable instance? Any other steps required to get this working?

Not at all... this should just work independently of what you have installed. Did you create the insiders folder? `code-insiders-portable-data`

**Comment by joaomoreno** [comment]
@octref Yeah that's pretty rough. I already have an issue for it: https://github.com/Microsoft/vscode/issues/52224

**Comment by mjbvz** [comment]
Thanks @joaomoreno. Working now on linux using `code-insiders-portable-data` instead of `code-portable-data`

**Comment by octref** [comment]
@joaomoreno By giving it smoketest, do you mean I should run the automated smoketest with this?

```
yarn smoketest --build ~/Desktop/test/Visual\ Studio\ Code\ -\ Insiders.app
```

When I run this, the Insider build is opened but no smoketest is performed.

Other than #52224, I was directly launching Electron with `./Visual\ Studio\ Code\ -\ Insiders.app/Contents/MacOS/Electron` and it has been working fine.

**Comment by octref** [comment]
I'm closing this, as #52224 is tracked in another issue.
