### ISSUE TITLE
Test: Windows user setup

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#52824]
- [x] windows 64bit @jrieken 
- [x] windows 32bit @roblourens 

Complexity: 3

Get the Windows **user setup** over here: https://vscode-builds.azurewebsites.net/builds/insider

- You should be able to install the user setup without any Administrator privileges (try it on a regular User account).
- All setup options should work correctly: file associations, desktop icon, start menu icon, context menu actions.
- You should get seamless background updates without lots of prompts and dialogs. The update experience should feel like macOS. In order to test an update, edit the installation's `product.json` and change the `commit` key to `outdated`.
- **64bit only:** You should not be able to install both the 32 and 64 bit release

**Note:** a user can have two installations of VS Code on his system: one globally and another locally. We're doing nothing to prevent that or distinguish those two. It doesn't seem to be a pressing issue and we'll wait for user reactions to that, if it happens.

**Comment by roblourens** [comment]
If I have global and user installs running at the same time, they will be sharing data folders but have their own main processes. That feels unsafe for some reason but I couldn't really find any specific problems with it.

**Comment by joaomoreno** [comment]
> If I have global and user installs running at the same time, they will be sharing data folders but have their own main processes. That feels unsafe for some reason but I couldn't really find any specific problems with it.

You won't be able to run both at the same time pointing to the same data. The second instance will just open a window on the first.

**Comment by roblourens** [comment]
I was able to do this, I verified that they had different main processes.

**Comment by joaomoreno** [comment]
Please check again. If they point to the same user data dir, the second instance should really simply make the first one open a window and kill itself. Can you confirm?

**Comment by joaomoreno** [comment]
Can you confirm that they use the same user data dir?

**Comment by roblourens** [comment]
Yes they are both in `AppData/Roaming/Code - Insiders/User/settings.json`. I'm just clicking the .exes of each one.


![jun-28-2018 09-06-28](https://user-images.githubusercontent.com/323878/42046351-917532c8-7ab2-11e8-82b4-e9b2816efa1a.gif)

**Comment by joaomoreno** [comment]
Are they the same version number?

**Comment by roblourens** [comment]
Cool, I can't repro this at all anymore. With the same steps I was using, now it opens two windows with the same main process. I'd reinstalled the user-level install at some point, I don't know which versions I was on last.

It's also possible to see which exe is actually running with Task Manager so I'll check that if I think I see it again.
