### ISSUE TITLE
Not able to uninstall GitLence extension

### ISSUE THREAD

**Issue by HarshalSolao** [Microsoft/vscode#52828]
Issue Type: <b>Bug</b>

Showing this popup "command 'gitlens.toggleFileBlame' not found"
And even not able to unistall.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz (4 x 2294)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (3.87GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|0.25.2
ng-template|Ang|0.1.9
npm-intellisense|chr|1.3.0
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.12
git-extension-pack|don|0.1.3
githistory|don|0.4.1
gitlens|eam|8.4.1
tslint|eg2|1.0.33
vscode-npm-script|eg2|0.3.4
git-project-manager|fel|1.6.1
githd|hui|1.1.5
notepadplusplus-keybindings|ms-|1.0.2
team|ms-|1.136.0
debugger-for-chrome|msj|4.7.0
typescript-hero|rbb|2.3.2
java|red|0.27.0
git-merger|sha|0.4.1
vscode-java-debug|vsc|0.9.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.5.0
vscode-maven|vsc|0.9.0
gitblame|wad|2.4.2
vscode-open-in-github|ziy|1.3.3

</details>

**Comment by roblourens** [comment]
Please file a bug on the Gitlens repo for that.

Have you tried uninstalling the extension through the extension viewlet?

![image](https://user-images.githubusercontent.com/323878/41876844-10c1ab96-7884-11e8-9a25-b63d3a756ecc.png)

**Comment by HarshalSolao** [comment]
I tried all the possible way but still its not working.

**Comment by roblourens** [comment]
What happens when you try? What do you mean exactly, "it's not working"
