### ISSUE TITLE
Parsing of NFS mounted drive is really slow (Ubuntu)

### ISSUE THREAD

**Issue by ashwinaj** [Microsoft/vscode#5282]
- VSCode Version: 1.0.0
- OS Version: Ubuntu 14.04 LTS

Steps to Reproduce:

1. Open an NFS mounted folder in VS Code with a mix of C++, js and python source code (1000's of files)
2. Let the parsing (indexing) begin i.e. creation of the symbols database for intelliSense 

It is really slow (it's been running for 4 hours). This isn't the case with a similar setup with Sublime Text 3 on the same NFS mounted folder.

**Comment by bpasero** [comment]
@ashwinaj what do you mean by "parsing" / "indexing"?

**Comment by ashwinaj** [comment]
@bapsero I mean creation of symbols for intellisense. The bar at the bottom always says "parsing" and never moves to done

**Comment by bpasero** [comment]
@ashwinaj is this from an extension? can you attach a screenshot?

**Comment by ashwinaj** [comment]
@bpasero I apologize, I should've mentioned, it's using the following extension from Microsoft: https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools

Attached is a screenshot of this, highlighted in red.

![vs_code](https://cloud.githubusercontent.com/assets/7064045/14576321/ea90d7b4-031c-11e6-8667-05aae5dc4f93.png)

**Comment by bpasero** [comment]
This issue was moved to Microsoft/vscppsamples#11
