### ISSUE TITLE
Test: createQuickPick, createInputBox API

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#52820]
- [x] anyOS @dbaeumer 
- [x] anyOS @misolori 

Complexity: 5

Test the `createQuickPick` and `createInputBox` proposed APIs. Including:
- Documentation in `vscode.proposed.d.ts`.
- Samples in [quickinput-sample](https://github.com/Microsoft/vscode-extension-samples/tree/master/quickinput-sample)
- Think of different scenarios where you would use this API and make sure you can and it works as expected.
- Go through the various methods/properties and check they work.

**Comment by chrmarti** [comment]
From @joaomoreno:

FYI - to test against the latest API do the following:

* open your extensions `package.json` file
* change the `engine.vscode` property to `*`
* run `npm run postinstall` (assuming you have the `vscode` module as dev-dependency)
* undo the engine-version change from step 2
* from the vscode-repo copy the `vscode.proposed.d.ts`-file into your project
* in your `package.json` file add `enableProposedApi: true`

**Comment by dbaeumer** [comment]
And you need to have ripgrep installed to make one of the examples work

**Comment by dbaeumer** [comment]
I wrote my own multi step input scenario and without the sample from @chrmarti I would have failed I guess. I am wondering if some of the code we have in the sample would be helpful for other as well. I know it is boiler plate code but without that if is for example even hard to find out from the vscode.proposed.d.ts that I have to dispose and show the dialogs to get a multi step behaviour.

**Comment by chrmarti** [comment]
@dbaeumer I agree it would. We decided against making a ready-made multi-step API available to avoid locking ourselves in to a specific API. Instead we now have the samples that document concrete use cases and avoid the lock-in.
