### ISSUE TITLE
Import suggestions and individual Lodash modules

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#52831]
Lodash provides individual modules for each of its functions, e.g.

``` ts
import maxBy from 'lodash/maxBy';
```

However, currently TypeScript/VSCode will not use these files for import suggestions:

![image](https://user-images.githubusercontent.com/921609/41870091-f0f1a634-78b2-11e8-8db7-b4f183b731d8.png)

… which creates

``` ts
import { maxBy } from "lodash";

maxBy
```

What would it take for TypeScript/VSCode to suggest these files?

I'm sure this pattern applies to other modules as well, not just Lodash.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#25236
