### ISSUE TITLE
[Test plan] DefinitionLink api

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#52839]
Test #10037

- [x] anyOS @bpasero 

Complexity: 3

**Summary**
The proposed definition link API allows a definition provider to add additional metadata to a definition. This includes the range of the defining symbol.

**Test**
Write a simple extension that uses the proposed definition link api.  Check

- The `origin` range is used for mouse go to  definition hovers
- Do the property names make sense?
- Does the documentation make sense?

**Comment by bpasero** [comment]
@mjbvz when is `range` used and when `selectionRange`? I think that might need a bit more clarification.

**Comment by bpasero** [comment]
I only verified `origin` to be the range that gets underlined, neither `range` nor `selectionRange` made a lot of sense to me but I also do not know if they changed.
