### ISSUE TITLE
Privacy statement links to English regardless of set language 

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5283]
- VSCode Version: 1.0.0 (release)
- OS Version: Windows 10 / Ubuntu 15.10

Steps to Reproduce:

1. Change language to Spanish (es)
2. Ayuda > Declaración de privacidad (Help > Privacy Statement)

Actual:
Links to the English privacy statement. Translated versions are [available ](https://www.visualstudio.com/es-es/dn948229)

**Comment by chrisdias** [comment]
nice catch!  I have to find the URLs for each language...

**Comment by chrisdias** [comment]
ES: https://www.visualstudio.com/es-es/dn948229
FR: https://www.visualstudio.com/fr-fr/dn948229
DE: https://www.visualstudio.com/de-de/dn948229
RU: https://www.visualstudio.com/ru-ru/dn948229
ZH-CN: https://www.visualstudio.com/zh-cn/dn948229
ZH-TW: https://www.visualstudio.com/zh-tw/dn948229
JP: https://www.visualstudio.com/ja-jp/dn948229
KO: ???
IT: https://www.visualstudio.com/it-it/dn948229

**Comment by dbaeumer** [comment]
@bpasero any hint where to tweak the privacyStatementUrl. In contrast to the license URL the language is not a param. So we need a kind of place holder in the license URL.

**Comment by bpasero** [comment]
@dbaeumer we should make it in a way that you can pass in the language as parameter

**Comment by dbaeumer** [comment]
OK. Makes sense to me. 

@chrisdias I assign this to you to adopt the privacy URL to the same schema we use for the license URL.

**Comment by chrisdias** [comment]
@dbaeumer @bpasero 

The privacy URLs are out of our control, they are on visualstudio.com. I am confident many products refer to them and their url schema is probably consistent across their site so changing it there is unlikely.

We could do a redirect from code.visualstudio.com, would that work for you guys?

**Comment by bpasero** [comment]
Sounds good to me.

**Comment by chrisdias** [comment]
eventually we will use:

http://go.microsoft.com/fwlink/?LinkId=786907?lang=XX

**Comment by chrisdias** [comment]
this is now in the website, we still need to update the product.

- need to update `privacyStatementUrl` in `product.json` to point to fwlink: http://go.microsoft.com/fwlink/?LinkId=786907
- need to append `?lang=XX` to the url
