### ISSUE TITLE
VsCode tasks events do not fire

### ISSUE THREAD

**Issue by DavidSchuldenfrei** [Microsoft/vscode#52830]
- VSCode Version: 1.24.1
- OS Version: Windows 10 

Steps to Reproduce:

1. I am writing an extension for VsCode. I am trying to get notifications on tasks start and end (specifically the "Build" task). I wrote the following in the startup code of my extension:
`tasks.onDidStartTask.apply(function(event: any) { 
    console.log(event);
});`
The code for hooking the apply is called, but the callback is never called. 

I tried with tasks.json version "0.1", and with version "2.0", to no avail

**Comment by dbaeumer** [comment]
This works for me using a simple example like this:

```typescript
'use strict';
// The module 'vscode' contains the VS Code extensibility API
// Import the module and reference it with the alias vscode in your code below
import * as vscode from 'vscode';

// this method is called when your extension is activated
// your extension is activated the very first time the command is executed
export function activate(context: vscode.ExtensionContext) {

    vscode.tasks.onDidStartTask((event) => {
        console.log(`Task started ${event.execution.task.name}`);
    })

}

// this method is called when your extension is deactivated
export function deactivate() {
}
```

and in the package.json having

```json
    "activationEvents": [
        "*"
    ]
```
