### ISSUE TITLE
Test: Active terminal extension API

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#52834]
https://github.com/Microsoft/vscode/issues/47615

- [x] macOS @jrieken  
- [x] Linux @chrmarti 
- [x] Windows @ramya-rao-a

Complexity: 2

Test these two new proposed APIs for the terminal that allow tracking of the active terminal:

https://github.com/Microsoft/vscode/blob/d88b3dd55be626154bf1d43c6d8570e02b4a32bb/src/vs/vscode.proposed.d.ts#L467-L480

**Comment by chrmarti** [comment]
From @ joaomoreno:

FYI - to test against the latest API do the following:

* open your extensions `package.json` file
* change the `engine.vscode` property to `*`
* run `npm run postinstall` (assuming you have the `vscode` module as dev-dependency)
* undo the engine-version change from step 2
* from the vscode-repo copy the `vscode.proposed.d.ts`-file into your project
* in your `package.json` file add `enableProposedApi: true`
