### ISSUE TITLE
IntelliSense: Drill in on callback?

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#5284]
![image](https://cloud.githubusercontent.com/assets/3254987/14546974/4f88973e-025e-11e6-8053-724cc8ecc51e.png)
I would be great if when `tape((<cursor>))` it would be able to drill in the `tape.TestCase` and show the signature of the callback. :tulip: 

This is probably on `tsc`, but let's start here. :smile:

**Comment by egamma** [comment]
Yes, hint is computed by Salsa/TypeScript. Moving to TypeScript.

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#8134
