### ISSUE TITLE
Dynamic intellisense for "editor.codeActionsOnSave"

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#52846]
For the `editor.codeActionsOnSave` setting, provide intellisense for all known source code actions.

As a initial step. the list of actions would come from the known `CodeActionProviderMetadata` currently registered by extensions. As these registrations are  dynamic, the completions would depend on an the code action providers having being activated so far.

**Comment by ParkourKarthik** [comment]
Hi @mjbvz . I'd like to pick this up. Could you provide me with an existing example for a setting with intellisense. So that I could use it for reference.
