### ISSUE TITLE
Test: Webview persistence api

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#52849]
Test for #49022 #48542

Complexity: 3

- [x] Any OS @JacksonKearl 
- [ ] Any OS  @RMacfarlane  
 
**Summary**
A new api for webview serialization has been added. This allows webviews to both save their state between becoming hidden and visible, as well as saving their state when VS Code restarts

**Test**
Try adding the two types of persistence to the new webview (you can use the [cat coding example](https://github.com/Microsoft/vscode-extension-samples/blob/master/webview-sample/) for this)

Visibility persistence is implemented using a `getState` and `setState` method inside the webview itself:

```ts
const vscode = acquireVsCodeApi();
const state = vscode.getState();
vscode.setState({ abc: 123 })
```

Serialization uses [`WebviewPanelSerializer`](https://github.com/Microsoft/vscode/blob/f5300ced7fbd0193babf05ee37860bb2d160beb7/src/vs/vscode.d.ts#L5423) and [`registerWebviewPanelSerializer`](https://github.com/Microsoft/vscode/blob/f5300ced7fbd0193babf05ee37860bb2d160beb7/src/vs/vscode.d.ts#L5942) to register a handler in the extension that can revive a webview from its state.

**Things to test:**

* Can you implement the two types of persistence?
* Does the API documentation make sense? (I'll be writing docs for it too but have not finished these yet)
* Are there cases where the new APIs may not work?

**Comment by JacksonKearl** [comment]
Visibility persistence seems to work well and is easy to implement, Serialization was more difficult to figure out but ended up getting it in the end, with some help. Updating one of the examples to use Serialization would definitely be helpful.

One thing I was expecting but didn't seem to get was persisting the state across closing the tab and reopening it with a command.
