### ISSUE TITLE
Expand unused detection (exports, properties, etc.)

### ISSUE THREAD

**Issue by jabacchetta** [Microsoft/vscode#52847]
[Unused variables and imports](https://code.visualstudio.com/updates/v1_24#_highlight-unused-variables-and-imports) are a good start.

Would love to see unused exports, classes, and properties added to this detection.

**Comment by mjbvz** [comment]
Please provide examples

**Comment by jabacchetta** [comment]
Here's one using WebStorm, where an unused export is detected.
<img width="1440" alt="screen shot 2018-06-25 at 5 43 01 pm" src="https://user-images.githubusercontent.com/12591890/41879448-4b4d4994-789f-11e8-8d15-b918c1c54ca3.png">

**Comment by mjbvz** [comment]
Please share small, minimal code examples as text (or better, small example projects). I need to understand why they are not being marked unused currently

**Comment by jabacchetta** [comment]
@mjbvz I might be confused. Should this actually be working in VS Code currently?

This issue was meant to be a feature request, not a bug. But if it's suppose to be working already, I'll do more digging.

**Comment by waratah** [comment]
@jabacchetta    Unused was only just released.   It is awesome.

**Comment by jabacchetta** [comment]
@waratah Yeah, I'm running 1.24.1 and can see it working. But from my understanding, it only works for variables and imports. Unused exports and properties do not show as unused.

**Comment by mjbvz** [comment]
Please share code examples

Properties should already be detected as unused. Exports aren't marked as unused because we don't know if they form part of the API surface for the library or not
