### ISSUE TITLE
HTML inline features are not displayed when editing PHP files.

### ISSUE THREAD

**Issue by Creeper9207** [Microsoft/vscode#52840]
I found myself falling in love with the HTML inline tips (especially the color swatches) and was saddened when I found out that such tools are not active when editing PHP files containing HTML code. A setting allowing HTML inline features in PHP files would be amazing, specifically for developers using wordpress.

**Comment by aeschli** [comment]
VSCode has only a very little built-in support for PHP. We recommend using a PHP extension from the marketplace such as 
https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense
or
https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client

Please file your feature request against one of these extensions.
@bmewburn @felixfbecker FYI
