### ISSUE TITLE
VSCode tsconfig, jsconfig & other (.json) files in SharePoint

### ISSUE THREAD

**Issue by MJNP** [Microsoft/vscode#52853]
We're using Visual Studio Code to edit (.js) files in SharePoint.
All is working as expected. However, it has come to our attention that our SharePoint logs grew big and we found out that there are bunch of  errors pointing to requesting for tsconfig.json, jsconfig.json & .vscode/extensions.json. As observed, it seems that VSCode is looking for these files whenever we save or keep a file open.

By default, SharePoint 2013 blocks (.json) files hence we removed (.json) from the list of blocked file types in central admin but we're still getting the same list of errors. 

We're wondering if we can disable something from the Preferences > User Settings. We tried to use the following to tell VSCode to stop looking for those (.json) files but results are just the same

1. files.exclude
2. files.watcherExclude
3. search.exclude

We've also tried to downgrade VSCode from 1.24 to 1.6.1
Because VSCode 1.6.1 does not look for these files in the background.
Although we're unhappy about it because we're missing a lot of great features.

Hope someone can enlighten us about this.

**Comment by roblourens** [comment]
I'm guessing you want to disable the builtin Typescript extension for the tsconfig and jsconfig files. Not sure about .vscode/extensions.json. I'm not exactly clear about the scenario though, do those files exist?

**Comment by MJNP** [comment]
Hi @roblourens no they don't. 

I forgot to mention above that the Folder I am trying to open in VS Code was not made using npm install. 
Just by simply right clicking on an empty space and New Folder/New Text. The files in it are simple (.html), (.js) and (.css) files only.

In addition to the information I've written above, I would like to mention 2 cases that I noticed while investigating it.

1) Leave a file open in the Editor (regardless whether I am actively editing it or not)
- **Result**: server constantly logs (.json) request

2) Close all files in the Editor but keep the Folder open in VS Code
- **Result**: server does not log any (.json) request

The behavior of searching the mentioned (.json) files seems to be recursive. It looks within each sub-folders.

Is there a guide on how I can do what you've mentioned about disabling Typescript extension?

Thanks!

**Comment by roblourens** [comment]
You can find it in the extensions viewlet: 

![image](https://user-images.githubusercontent.com/323878/41929288-742e6bb2-792c-11e8-8685-e82510a342ca.png)

then disable the "TypeScript and JavaScript Language Features" extension

**Comment by roblourens** [comment]
@sandy081 is there any way to keep vscode from looking for the .vscode/extensions.json file?

**Comment by MJNP** [comment]
@roblourens thanks a lot! It appears that the server is not logging any (tsconfig.json & jsconfig.json) requests anymore!

I'll wait for @sandy081 advise about /.vscode/extensions.json 

Again, Many thanks!

**Comment by sandy081** [comment]
`/.vscode/extensions.json` is a file that is used to recommend extensions. It is generated by VS Code while configuring recommendations. It is similar to `.vscode/settings.json` file. 

Not sure why you want VS Code not to look at these core files

**Comment by MJNP** [comment]
Hi @sandy081 I see. I did some observations again today and I noticed that server is logging requests for `/.vscode/extensions.json`  whenever I open up VSCode only so I guess we can work with that. 

Thanks a lot for your help guys!

Cheers!

PS: After I disabled the "TypeScript and JavaScript Language Features" the Format Document `Alt + Shift + F` option won't be available for (.js) files anymore

**Comment by roblourens** [comment]
Yeah, disabling the extension will disable all TS/JS language features. It's not the greatest workaround. But this is an unusual case.
