### ISSUE TITLE
Test: Custom Title/Menubar on Windows/Linux

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode#52854]
Test for #29024 

- [x] windows @bpasero
- [x] windows @octref 
- [x] linux @Tyriar 

Complexity: 4

**Summary**
On Windows and Linux, users can now opt in to use the custom titlebar that has been available on macOS for some time. With this change, we have implemented a new HTML-based menubar that is more accessible than the Electron version as well as just looks nicer. In order to match the new menubar, menus throughout the workbench are now using the same menu widget.

**Test**
1. First, set `window.titleBarStyle` to `custom` and restart Code.
2. Use the new titlebar and window controls.
3. Use the new menubar.
4. Try out menus throughout the workbench.

**Things to verify**
- Do the window controls work as expected?
- Can you navigate the menubar with a keyboard?
- Can you navigate the menubar with the mouse?
- Does the menubar honor settings like `window.enableMenuBarMnemonics` and `window.menuBarVisibility`?
- Accessibility with screen readers
- Do the actions in the menubar as well as menus throughout the workbench actually work?

See existing issues here for dupes [Menu](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+assignee%3Asbatten+label%3Aworkbench-menu) and [Accessibility](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+assignee%3Asbatten+label%3Aaccessibility)

**Comment by bpasero** [comment]
I did a lot of testing, but I ran out of time to test each action of each menu to be honest. Maybe someone else wants to focus on that task?

**Comment by beastdestroyer** [comment]
I'm not sure which issue to put this in, but I found that in each menu, there is a black box which surrounds part of the option, making it look weird, here is a screenshot, you can see the outline in the little box I made around it
![menubug](https://user-images.githubusercontent.com/30497573/41924145-27a9966a-7961-11e8-93bc-11b64ec36462.png)

**Comment by bpasero** [comment]
@beastdestroyer that sounds like https://github.com/Microsoft/vscode/issues/52911

**Comment by beastdestroyer** [comment]
@bpasero Yup, indeed it is, apologies for the trouble, if any!
