### ISSUE TITLE
unused variable - typescript edge case

### ISSUE THREAD

**Issue by waratah** [Microsoft/vscode#52856]
Issue Type: <b>Bug</b>

Typescript code:  

 ```
constructor(
        private $location: angular.ILocationService,
        private $interval: ng.IIntervalService,
        private $scope: angular.IScope,
        private $routeParams: angular.route.IRouteParamsService,
        private translationService: ITranslationService,
        private userService: IUserService,
    ) {
        this.ngOnInit();
        $scope.$on(
            "$destroy",
            () => $interval.cancel(this.intervalObj)
        );
    }
```

The $scope is highlighted as unused.   This is both correct and incorrect.   It is correct because this.$scope is never used however $scope is used within the constructor.   Removing private from the declaration stops highlighting the field.

I cannot figure out what the correct behaviour is for this...   just noting issue for consideration.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.26GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_61455|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
gitlens|eam|8.4.1
tslint|eg2|1.0.33
auto-rename-tag|for|0.0.15
beautify|Hoo|1.3.2
mssql|ms-|1.3.1
csharp|ms-|1.15.2
code-spell-checker|str|1.6.10

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
This is correct. The specific error is ` Property '$scope' is declared but its value is never read.` You are not using `this.$scope` anywhere. The fix is not not create a property using `private`

**Comment by waratah** [comment]
Would not call this correct.   Delete the line which it encourages and it does not compile.

**Comment by mjbvz** [comment]
You should just remove `private`, not the entire line. If you are not using `this.$scope` anywhere, you should not create a property for it
