### ISSUE TITLE
Test: LSP Inspector

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#52866]
- [x] windows: @sbatten  
- [x] macOS: @mjbvz 
- [x] linux: @isidorn

Complexity: 2

Repo: https://github.com/Microsoft/language-server-protocol-inspector
Hosted at: https://microsoft.github.io/language-server-protocol/inspector/

Description:

See [Usage](https://github.com/Microsoft/language-server-protocol-inspector#usage) of the LSP Inspector. Test:

- The visual display of the Inspector illustrates the communication effectively
- The filtering / searching works as expected
- Try generating logs from html/css/json Language Servers, or even https://github.com/Microsoft/vscode-tslint or https://github.com/vuejs/vetur. Verify the inspector can load them all.

**Comment by octref** [comment]
Additionally, verify that the Language Server guide make sense to you: https://github.com/Microsoft/vscode-docs/blob/vnext/docs/extensions/example-language-server.md#logging-support-for-language-server

**Comment by isidorn** [comment]
Language server guid is covered by this item, so we should not duplicate work https://github.com/Microsoft/vscode/issues/52873

**Comment by isidorn** [comment]
Cool work

**Comment by mjbvz** [comment]
Really cool work! I'm opened a few issues but none of them are serious so far. Mostly just ideas for small UI improvements or enhancements
