### ISSUE TITLE
After sudden power off, unsaved files lose data

### ISSUE THREAD

**Issue by swaps19** [Microsoft/vscode#52868]
Issue Type: <b>Bug</b>

1. Open a few files
2. Directly power off the system

- Following two things are unexpected reopening Code after Reboot
1. Previous opened files are gone
2. If some of the unsaved files open, those will loose data

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:47:35.732Z)
OS version: Linux x64 4.15.0-23-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3 CPU         530  @ 2.93GHz (4 x 2926)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|7.59GB (2.80GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
solargraph|cas|0.17.4
jsrefactor|cms|2.13.0
vscode-eslint|dba|1.4.12
githistory|don|0.4.1
vscode-JS-CSS-HTML-formatter|lon|0.2.3
ruby-rubocop|mis|0.7.0
sublime-keybindings|ms-|4.0.0
vscode-docker|Pet|0.0.27
Ruby|reb|0.18.0
gitblame|wad|2.4.2
html-css-class-completion|Zig|1.17.1

</details>

**Comment by Tyriar** [comment]
Can you share your settings.json file? Also did you have a folder open at the time?

**Comment by swaps19** [comment]
@Tyriar Yes I had opened a folder in the `VS Code`.

Following are my `User Settings`-

```json
{
    "editor.fontSize": 11,
    "editor.formatOnPaste": true,
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.snippetSuggestions": "top",
    "workbench.colorTheme": "Monokai",
    "editor.tabSize": 2,
    "editor.renderWhitespace": "boundary",
    "editor.wordWrap": "on",
    "diffEditor.ignoreTrimWhitespace": false,
    "workbench.sideBar.location": "left",
    "workbench.activityBar.visible": true,
    "editor.minimap.enabled": false,
    "ruby.lint": {
        "rubocop": {
            "lint": true,
            "rails": true
        },
        "ruby": {
            "unicode": true,
            "levels": [
                "error",
                "warning",
                "info"
            ],
            "classes": [
                "argument_amount",
                "loop_keywords",
                "pedantics",
                "shadowing_variables",
                "undefined_methods",
                "undefined_variables",
                "unused_variables",
                "useless_equality_checks"
            ]
        },
        "ruby-lint": true,
    },
    "window.zoomLevel": 0,
    "ruby.intellisense": "rubyLocate",
    "[javascript]": {
        "editor.tabSize": 4
    },
    "[html]": {
        "editor.tabSize": 4
    },
    "[css]": {
        "editor.tabSize": 4
    },
    "[scss]": {
        "editor.tabSize": 4
    }
}
```

**Comment by Tyriar** [comment]
I can sort of repro this, but things actually work fine. Here's what happened for me.

I changed a file, checked that the backup existed for the file:

```
cat ~/.config/Code\ -\ Insiders/Backups/20ef69747b14f3a788362e0578228d3f/file/9ab4b925a92d84bf420b2eae5098fc3b  | less
```

Hard shutdown the computer, then reopened VS Code. VS Code opened but didn't restore because a different folder I had opened earlier was opened. This is because opened folders in a workspace are only  persisted during a graceful shutdown. Opening the folder from above correctly restored the file (though it was in a background tab).

So I would expect the backup to exist, it's just the correct window may not have been restored.

**Comment by swaps19** [comment]
Yeah that might be the case.
Actually I'm used to `Sublime` and didn't face these kind of issues ever.
So thought to report a bug as I also lost some of the code in the `Hard Shutdown` process.

**Comment by Tyriar** [comment]
If this was the case you shouldn't have lost the files, you just need to reopen the folder. You can also check the files inside `~/.config/Code\ -\ Insiders/Backups` to see if you can recover the file(s).

**Comment by swaps19** [comment]
The folder gets reopened automatically with the restart of `Code`. So I didn't reopened the folder explicitly.
Also my `~/.config//Code/Backups/..*` folders are looking empty.
