### ISSUE TITLE
Increase tab styling options

### ISSUE THREAD

**Issue by mhkeller** [microsoft/vscode#52862]
Hello. I have a three suggestions for styling tabs that I feel would improve the UX of the editor and allow themes to be more internally consistent.

* `tab.hoverForeground` to style the foreground color of a tab. Currently `tab.hoverBackground` exists but not foreground. I think this would be useful because in my theme — spacegray — I want the hover style in the sidebar to match the hover style in the tabs. Currently, on sidebar hover, the foreground color lightens.
* `tab.closeForeground`, which would style the color of the close button. I don't currently see this anywhere but if I've missed it, please let me know
* `tab.closeHoverForeground`, which would style the color of the close button on hover Per [this comment](https://github.com/Microsoft/vscode/issues/30901#issuecomment-350197809) by @bpasero, hover states for the close button were not seen useful but I would argue a close button is an ideal use case for hover-state feedback. When switching tabs, a user could accidentally click on the close button instead of the tab hit area and accidentally close that tab. If the close button turns a different color on hover, it is very clear that a click will close the tab.

**Update:**
* Allow `tab.unfocusedActiveBackground` in `workbench.colorCustomizations` #54197
* Have separate colors for active and inactive tab hover #54713

**Comment by mhkeller** [comment]
@bpasero If you have a pointer on where this change would be needed in the code, I'd be happy to take a crack at it and PR.

**Comment by webia1** [comment]
As of February 2019 `tab.unfocusedActiveBackground` is still missing,..  :disappointed_relieved:

**Comment by jabacchetta** [comment]
Agreed, the hovering options are definitely needed to make the tab UI more intuitive. Would love to see `tab.hoverForeground` and `tab.inactiveHoverBackground`.

**Comment by mhkeller** [comment]
@bpasero Any thoughts on this?

**Comment by bpasero** [comment]
Added a few new colors:
* `tab.unfocusedInactiveBackground`
* `tab.hoverForeground`
* `tab.unfocusedHoverForeground`

Since we moved to icon fonts for our icons, foreground colors will also apply to e.g. the close button:

![image](https://user-images.githubusercontent.com/900690/79105118-48d5c600-7d70-11ea-80e5-ed04de214735.png)

I am reopening https://github.com/microsoft/vscode/issues/54713 because I did not add any more colors as asked in that issue.
