### ISSUE TITLE
manay  rg.exe cpu 100% usage

### ISSUE THREAD

**Issue by ufowiner** [Microsoft/vscode#52860]
Issue Type: <b>Bug</b>

when i open the vscode 
manay  rg.exe  cpu 100% usage

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17134

**Comment by roblourens** [comment]
These are probably from extensions. If you can get the command line arguments from Task Manager, you can probably figure out which one it is.

**Comment by yeluoqiuzhi** [comment]
It's from typescript 2.9 and above, not from extension

**Comment by roblourens** [comment]
@yeluoqiuzhi This issue can have many different causes, yours may not be the same.
