### ISSUE TITLE
Custom extension shows open uninstall [x] box in extensions menu

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5286]
- VSCode Version: 1.0.0 (release)
- OS Version: Ubuntu 15.10

Steps to Reproduce:

1. Create a custom extension
2. Add it to your $HOME/.vscode/extensions directory
3. launch Code and view installed extensions

![customextension](https://cloud.githubusercontent.com/assets/12900364/14547072/0f3ca8f4-025f-11e6-859a-cfae7dcd6da3.png)

**Comment by joaomoreno** [comment]
Rendering issue. Will go away with #637
