### ISSUE TITLE
Location is missing on document symbols in Insiders

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#52874]
I have an integration test that executes `vscode.executeDocumentSymbolProvider` for some files and inspects the results. In Insiders, they seem to be missing the `location` (it's undefined):

Value I'm returning (PartialSymbolInformation is a subclass of SymbolInformation that allows me to stash unresolved location data, since I share this method with Workspace symbols):

<img width="380" alt="screen shot 2018-06-26 at 8 33 22 am" src="https://user-images.githubusercontent.com/1078012/41896212-e593d7a8-791b-11e8-9bf5-a20b2c8c820c.png">

Here's what comes through in the test:

<img width="394" alt="screen shot 2018-06-26 at 8 33 39 am" src="https://user-images.githubusercontent.com/1078012/41896213-e5b18da2-791b-11e8-88ef-9faeefb588cd.png">

I wondered if it was related to #51695 but as far as I can tell, no code changes were made for that (only the comment fixed).

cc @jrieken

**Comment by jrieken** [comment]
Hm, likely some problem with the data conversion. Internally we already use the new `DocumentSymbol`-type and that's likely what we are returning from the api-command too. Not entirely sure what to do, usually we are a little more relaxed when it comes to api-commands and stability...

**Comment by DanTup** [comment]
I don't mind putting conditions in my test to check a different type if the data is available there - breaking the API isn't a big deal to me (it's just tests), but I'm not sure if there may be others using this within extensions.

**Comment by jrieken** [comment]
Looking at other extensions, I'll make this backwards compatible. For the future, we might add a flag to get the "modern data"
