### ISSUE TITLE
Installing extensions does not convert download icon to uninstall icon in install menu

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5287]
- VSCode Version: 1.0.0 alpha
- OS Version: Windows 10 / Ubuntu 15.10

Steps to Reproduce:

1. Install an extension
2. Restart
3. Open install menu again

Actual:
The extension will still show the download button after being installed but it will show correctly if opened in the installed extensions menu. This allows you to install the same extension multiple times

**Comment by joaomoreno** [comment]
Great catch.
