### ISSUE TITLE
On Large XML files Formatting/Syntax highlighting does not work

### ISSUE THREAD

**Issue by nirlavi** [Microsoft/vscode#52870]
Issue Type: <b>Bug</b>

Opening an xml north of ~25MB does not format the document, show syntax highlighting or enable navigation in the Xml Document pane.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.89GB (37.48GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe |Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.3.1
vscode-colorize|kam|0.6.21
python|ms-|2018.6.0
csharp|ms-|1.15.2
PowerShell|ms-|1.7.0
vscode-icons|rob|7.24.0
code-settings-sync|Sha|2.9.2
debug|web|0.22.0

(2 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
Right now we disable these features for large files to ensure acceptable performance and without crashing VSCode. Thanks for reporting this issue.
