### ISSUE TITLE
No Response When  Android Studio opened

### ISSUE THREAD

**Issue by limajia** [Microsoft/vscode#52877]
Issue Type: <b>Performance Issue</b>

step 1: open the vscode , it's ok!
step 2: but  when open the software "android studio", vscode can't click any more, only can removed.

then i must close the vscode by force.  this question occur 100%!

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:30:30.113Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (1.25GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by roblourens** [comment]
I can't think of any reason why these two programs would interact. Is Android Studio just using a lot of CPU and slowing everything down?

**Comment by roblourens** [comment]
Also please see these performance troubleshooting tips: https://github.com/Microsoft/vscode/wiki/Performance-Issues
