### ISSUE TITLE
Intellisense for instantiation of abstract classes

### ISSUE THREAD

**Issue by wehrstedt** [Microsoft/vscode#52878]
- VSCode Version: 1.24.1
- OS Version: Windows 10 1803

Steps to Reproduce:

1. Create an abstract class
```
abstract class abc {} 
```
2. Type in ```new <ctrl + space>``` => The abstract class will be suggested. If you accept the proposal, you will get an an error (abstract classes can't be instantiated)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#25234
