### ISSUE TITLE
Terminal#onData violates event naming conventions

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#52882]
re #52833

see https://github.com/Microsoft/vscode/wiki/Extension-API-guidelines#event-naming

**Comment by jrieken** [comment]
same for `TerminalRenderer#onInput`

**Comment by dbaeumer** [comment]
Same is true for `TerminalRenderer#onInput`

**Comment by Tyriar** [comment]
I'll change them to `TerminalRenderer.onDidAcceptInput`, `Terminal.onDidWriteData`
