### ISSUE TITLE
Custom menus follow up

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#52884]
Some follow up from code review that I consider more debt and not bugs which is fine to look at for July:

* [x]  ~~remove the [titlebarPart.css transition rule](https://github.com/Microsoft/vscode/blob/51e0ad1ac7f96466130c413dddf11a8934b3a007/src/vs/workbench/browser/parts/titlebar/media/titlebarpart.css#L85) unless there is a need for it~~
Looks like it is being used (https://github.com/Microsoft/vscode/pull/53211#issuecomment-401033547)
* [x] remove the old menu implementation
  * [x] verify everything works as before when menu is not custom and on macOS
* [x] remove the [`vscode.toggleAutoSave`](https://github.com/Microsoft/vscode/blob/51e0ad1ac7f96466130c413dddf11a8934b3a007/src/vs/workbench/electron-browser/window.ts#L187) which I think is no longer needed then
* [x] remove [`FILE_MENU_FAKE_OPEN_FILE_COMMAND_ID`](https://github.com/Microsoft/vscode/blob/51e0ad1ac7f96466130c413dddf11a8934b3a007/src/vs/workbench/browser/parts/menubar/menubarCommands.ts#L10) ?
* [x]  why are there two `AlternativeKeyEmitter` ([here](https://github.com/Microsoft/vscode/blob/51e0ad1ac7f96466130c413dddf11a8934b3a007/src/vs/workbench/browser/parts/menubar/menubarPart.ts#L687), [here](https://github.com/Microsoft/vscode/blob/51e0ad1ac7f96466130c413dddf11a8934b3a007/src/vs/platform/actions/browser/menuItemActionItem.ts#L23)), can they not be reused/shared?
* [x] what is the purpose of the `resizer` element in the title bar part?
* [x] why are the window buttons called `chrome-xy`? google chrome?
* [x] do not use a [`querySelect`](https://github.com/Microsoft/vscode/blob/51e0ad1ac7f96466130c413dddf11a8934b3a007/src/vs/workbench/browser/parts/titlebar/titlebarPart.ts#L335) to find the element, rather keep it as field
* [x] `menubarPart` is should use the `builder` pattern either fully or not, but partially is a bit weird, e.g. [`this.customMenus[menuIndex].titleElement.getHTMLElement().onmouseenter`](https://github.com/Microsoft/vscode/blob/071344114997cdc962dd6d454846535e801e0046/src/vs/workbench/browser/parts/menubar/menubarPart.ts#L501) vs. [`this.customMenus[menuIndex].titleElement.on(EventType.CLICK, (event) => {`](https://github.com/Microsoft/vscode/blob/071344114997cdc962dd6d454846535e801e0046/src/vs/workbench/browser/parts/menubar/menubarPart.ts#L492)
* [x] `menubarPart` is not properly cleaning up disposeables, for example this:

`this.configurationService.onDidChangeConfiguration(e => this.onConfigurationUpdated(e));`

should be

`this._register(this.configurationService.onDidChangeConfiguration(e => this.onConfigurationUpdated(e)));`

**Comment by sbatten** [comment]
@bpasero 
>why are there two AlternativeKeyEmitter (here, here), can they not be reused/shared
I originally created the second one because the original was used for the alternative actions throughout the workbench, but that behavior was still under discussion. Now, I've modified it by quite a bit to fit my needs and changed the name even.

>what is the purpose of the resizer element in the title bar part?
On windows, the window can't be resized from a draggable region, so the resizer let's you grab from the top.

>why are the window buttons called `chrome-xy`? google chrome?
UI jargon, that stuffs called window chrome.
