### ISSUE TITLE
The program freezes and falls off when using the plug-in "FreeMarker"

### ISSUE THREAD

**Issue by PavelHancharou** [Microsoft/vscode#52886]
The program freezes and falls off when using the plug-in "FreeMarker"

- VSCode Version: 1.24.1
- OS Version: Win 10 x64
- Plugin for FreeMarker: https://github.com/dcortes92/vs-freemarker
- Version of plugin: 0.0.9

Steps to Reproduce:

1. Open VSC
2. Select Language Mode - FreeMarker (.ftl)
3. Write next text:
${abcdefghijklmnopqrstuvwxyzabcdefj
4. VSCode stop to work

![vscodebug](https://user-images.githubusercontent.com/19645768/41901807-8b85c31a-793a-11e8-8078-de82249da8ea.JPG)

The problem is currectly **with FreeMarker Plugin**, and when there is  **NO closing quote "}"** in the text

**Comment by aeschli** [comment]
This issue was moved to dcortes92/vs-freemarker#18
