### ISSUE TITLE
Display the size of an image alongside its name

### ISSUE THREAD

**Issue by tsirolnik** [Microsoft/vscode#52883]
When viewing an image inside VSCode it'll be nice if we could've seen the image's size in pixels.

For example with the following image, the size will be displayed alongside its name - 

![2018-06-26-120815_118x53_scrot](https://user-images.githubusercontent.com/3106496/41901460-a10119de-7939-11e8-990e-d3b8a6d0129b.png)

logo.png (400x400)

![2018-06-26-120740_185x49_scrot](https://user-images.githubusercontent.com/3106496/41901427-8da6652e-7939-11e8-9fa7-17a88ae500b2.png)

Although being a minor addition I think that it'll be very useful

**Comment by trustedtomato** [comment]
It's already there at the right side of the status bar between the size and zoom level.
