### ISSUE TITLE
A vertical line is shown when panel is move to right

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#52892]
Testing #52287

Steps to Reproduce:

- Initial State: Activity bar is hidden, Side bar is hidden, Panel is hidden, No centered layout
- Go to centered layout
- Show Side bar
- Show panel
- Move panel to right

- 🐛 vertical line is shown in panel

![kapture 2018-06-26 at 15 28 04](https://user-images.githubusercontent.com/10746682/41915451-0a04606e-7956-11e8-8c16-a20e7a9bb0e1.gif)

![image](https://user-images.githubusercontent.com/10746682/41915415-ef758f7a-7955-11e8-8036-113ecc3aa6e7.png)

**Comment by isidorn** [comment]
Some repro steps would be great
You can also dom inspect the line and check is it a sash, does it belong to the centered editor layout? Does it go away if you resize the window (thus forcing a layout)?
Does it go away if you move panel / trigger centered

**Comment by sandy081** [comment]
Will try to repro and give you required info

**Comment by sandy081** [comment]
@isidorn Updated description with necessary steps and gif
