### ISSUE TITLE
Labels: on Windows a relative path should not begin with a backslash

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#52896]
This seems to be a regression from the label changes:

![image](https://user-images.githubusercontent.com/900690/41903725-fc8a7046-7936-11e8-8c79-6cd7714a0a63.png)

**Comment by isidorn** [comment]
I fixed this a couple of days ago.
I verified that it no longer happens with latest -> closing

Please reopen if you still see it - and let me know if you have some special setup
Thanks!

![screen shot 2018-06-27 at 16 28 54](https://user-images.githubusercontent.com/1926584/41980619-36b7e21c-7a27-11e8-89b9-652fb1aa2d4c.png)

**Comment by bpasero** [comment]
I was probably using an old build.
