### ISSUE TITLE
Terminal: emoji characters cut off

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#52891]
Refs: #52836

1. Open terminal, vscode repo
2. `yarn`

Notice some emoji characters being cutoff.  I can repro this for both `dynamic` and `static` `textureCachingStrategy`
Notice the magnyfing glass and the clipp

![screen shot 2018-06-26 at 11 29 37](https://user-images.githubusercontent.com/1926584/41902722-72cf4482-7934-11e8-9733-59b3948c00b1.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35901
