### ISSUE TITLE
Workspace folder name in paths is not updated when changed

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#52898]
Testing #52288

- Open a Multi-root workspace
- Open some files from one root folder and make sure they are shown in open editor
- Open Workspace Configuration file and update the name of the root folder

Expected: Root folder name should be updated to new name
Actual: Old folder name is shown

![image](https://user-images.githubusercontent.com/10746682/41904407-992861fa-7938-11e8-86ff-df2ed6fd26f7.png)

**Comment by isidorn** [comment]
This would mean that we would have to refresh all our trees when a root folder name changes.
I prefer for now to show the wrong name, and only update on refresh -> backlog

**Comment by alexandrudima** [comment]
I also noticed this with the following:
* Open a folder
* Add folder to workspace

The labels are not updated in the "Open Editors" section, perhaps in other places too.

**Comment by isidorn** [comment]
This works in latest
