### ISSUE TITLE
REPL for fsi

### ISSUE THREAD

**Issue by erasmas** [Microsoft/vscode#529]
Hi guys,
Great job, `vscode` looks promising! The only thing that I can't leave without is REPL for F#. Is there an extension that I need to install for it?

**Comment by isidorn** [comment]
Did you try [ionide-fsharp](https://app.market.visualstudio.com/items/Ionide.Ionide-fsharp)
Here is their repo for possible feature requests: https://github.com/ionide/ionide-vscode-fsharp
