### ISSUE TITLE
Menus: restore icon has different color compared to other icons

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#52900]
Refs: https://github.com/Microsoft/vscode/issues/52854

It looks like the restore icon has a white background and the other icons grey?

![image](https://user-images.githubusercontent.com/900690/41904554-ff6d92f0-7938-11e8-8ec2-b5b965692c79.png)

**Comment by sbatten** [comment]
@bpasero I think this was resolved when I updated to the mask trick you mentioned. can you verify?

**Comment by sbatten** [comment]
![controls](https://user-images.githubusercontent.com/6561887/43854395-99a6b8ee-9af7-11e8-88bf-3534ca005815.png)
@bpasero hmm, different machine, different results

**Comment by bpasero** [comment]
@sbatten yeah could be an artefact of me being inside a VM.
