### ISSUE TITLE
Menu: "Open Recent" stays empty

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#52909]
Refs: #52854

It looks like the **File > Open Recent** menu is staying empty, even though I am changing folders and would expect that menu to have entries after a while.

![image](https://user-images.githubusercontent.com/900690/41905109-7458d7d6-793a-11e8-9e36-62052855b4eb.png)

**Comment by Tyriar** [comment]
Verified, but I hit another bug https://github.com/Microsoft/vscode/issues/53272
