### ISSUE TITLE
Menu: title is not perfectly centered?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#52905]
Refs: #52854

It seems to me the window title is not in the perfect center:

![image](https://user-images.githubusercontent.com/900690/41904783-918fc914-7939-11e8-9a50-a0fb7b0b51dc.png)

**Comment by Tyriar** [comment]
Yea it should be centered in-between the buttons and the menu imo:

![image](https://user-images.githubusercontent.com/2193314/41935133-89539128-793d-11e8-82c7-6b5634c07cb5.png)

**Comment by sbatten** [comment]
fixed via #55100
