### ISSUE TITLE
cannot execute any command when Chinese UI is used

### ISSUE THREAD

**Issue by localvar** [Microsoft/vscode#5290]
- VSCode Version: 1.0
- OS Version: Windows 10

All commands are in Chinese when using Chinese UI, when I type something like "ext install", it says "没有匹配的命令(no matched command)" and don't allow me to run the command.

BTW: how to switch to English UI?

Steps to Reproduce:

1. 
2.

**Comment by Treri** [comment]
All commands should not be translated to locale specific commands.

## And they should only be **English**

**Comment by chanzig** [comment]
[language support and change](https://code.visualstudio.com/docs/customization/locales)
 
surely the commands should not be translated !  OK, why not translated the Keyboard ShortCurts desc..

**Comment by hax** [comment]
duplicate #4679 ?

**Comment by egamma** [comment]
Duplicate of #4679
