### ISSUE TITLE
Quick input validation doesn't run for preset value

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#52908]
Testing #52818

Have the following snippet:

```ts
await vscode.window.showInputBox({
   validateInput: value => /a/.test(value) ? 'uh oh' : null,
   value: 'hello warld'
}, tokenSource.token);
```

The validation doesn't run for that predefined value.

**Comment by chrmarti** [comment]
Changing it to run validation on the initial value. If there is a validation message on the initial value, it will not be shown until the user tries to accept it or changes the value and then return to the initial one. This avoids having the input box open with an error shown immediately which would be odd.
