### ISSUE TITLE
Menu: high contrast theme leaves weird separators around

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#52917]
Refs: #52854

Steps:
* enable high contrast theme
* expand the File menu
* see separators hanging out on the right hand side

![image](https://user-images.githubusercontent.com/900690/41905503-a38f43e0-793b-11e8-9be5-47a756e8d93c.png)

**Comment by sbatten** [comment]
@bpasero is this still happening? I cannot repro
