### ISSUE TITLE
Incorrect highlight in color theme "Dark+" and "Light+"

### ISSUE THREAD

**Issue by heroboy** [Microsoft/vscode#5291]
- VSCode Version: 1.0
- OS Version: windows 10

Paste code `var p = 1?2:(3<4?5:6)`, and everything after this will be in wrong color.

![12345](https://cloud.githubusercontent.com/assets/54468/14549153/ed6df98a-02ef-11e6-8ed7-47caaf7a262f.png)

**Comment by bgse** [comment]
Probably this one again:

https://github.com/Microsoft/TypeScript-TmLanguage/issues/11

**Comment by Tyriar** [comment]
Looks like it's actually https://github.com/Microsoft/TypeScript-TmLanguage/issues/81, just on a worse scale because of the brackets. Closing as duplicate.
