### ISSUE TITLE
Menu: first entry should not be selected by default

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#52913]
Refs: #52854

When opening a menu (either from menu bar or context menu), the first entry should not automatically be selected.

**Comment by bpasero** [comment]
It looks like the first entry should only be selected by default when the menu was opened through `Alt+xyz`

**Comment by bpasero** [comment]
Looks like this originates from https://github.com/Microsoft/vscode/blob/39f426232fda29b74ab9d77a5b8d4799252cd51e/src/vs/base/browser/ui/menu/menu.ts#L95 but changing it means I can no longer use arrow keys to move to an item.

**Comment by sbatten** [comment]
related #52933 and #52936

**Comment by sbatten** [comment]
after looking at the accessibility issues and with the unification of mouse and keyboard focus, I think this behavior is correct. though some native menus don't do this, it isn't harmful anymore and is more accessible. one example is the edge menus. Keyboard focus is given to the first element but that isn't displayed. down arrow actually focuses the second element. I think our approach is clearer.

**Comment by bpasero** [comment]
Be prepared for many bugs coming in from our users that just expect the native behaviour. But I am fine with waiting for some more feedback from users and their rationale why they would prefer the native behaviour.
