### ISSUE TITLE
Menu: window buttons should never be hidden

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#52918]
Refs: #52854

It looks like currently the menu pushes the window buttons out when the size is small. I think the buttons should always be visible:

![image](https://user-images.githubusercontent.com/900690/41905570-e7e76edc-793b-11e8-950b-9091fd31552e.png)

**Comment by bpasero** [comment]
It also looks like the application icon is moving when I resize the window just a bit.

**Comment by sbatten** [comment]
resolving as dupe of #52920
