### ISSUE TITLE
WorkspaceEdit: create file - overwrite and ignoreExists can conflict

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#52919]
Refs:  #52800

Have an extension with the following `WorkspaceEdit`
```
workspaceEdit.createFile(vscode.Uri.file('c:\\Development\\Test\\hello2.txt'), {
            overwrite: true,
            ignoreIfExists: true
        });
```

Notice that those two settings are conflicting and it is nowhere specified that ignoreIfExists has priority - which is what I see in practice.

**Comment by jrieken** [comment]
Yeah, "make illegal states un-representable" they said...

**Comment by jrieken** [comment]
needs inspiration, moving to July since this is proposed only. Maybe remove `ignoreIfExists`...

**Comment by jrieken** [comment]
Yeah, I think we will just document this and `overwrite` will win

**Comment by isidorn** [comment]
@jrieken in your comment you say that "overwrite wins" however I was seeing that `ignoreIfExists` wins. Did you change some other behavior that now results in different behavior here.
Reopening just so you see my comment and moving to august

**Comment by jrieken** [comment]
Yeah, this was really implemented, not just a doc change. See https://github.com/Microsoft/vscode/blob/7289c303db9c6437489b08e558a83a11ff063438/extensions/vscode-api-tests/src/singlefolder-tests/workspace.test.ts#L712

**Comment by isidorn** [comment]
Verified it works as documented now
