### ISSUE TITLE
Menu: should close easier

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#52912]
Refs: #52854

It looks like the menu currently stays open when you e.g. click on the title or even when you Alt+Tab away from the window. Other apps seem to close the menu in that case.

**Comment by bpasero** [comment]
Another case is this:
* open a context menu in the workbench in a viewlet
* click on another viewlet

=> the menu stays open

**Comment by sbatten** [comment]
I believe all of these cases are addressed except for clicking the titlebar. Separate issues have been created so closing as dupe. Re-open if I've missed one.
