### ISSUE TITLE
tree.onDidChangeSelection does not fire if selection is cleared

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#52910]
testing https://github.com/Microsoft/vscode/issues/52806:

- use https://github.com/weinand/vscode-processes
- add listener for `onDidChangeSelection` which outputs the `selection`
- F5
- run "Show Processes View" command
- in the new window open the integrated terminal
- in the integrated terminal run a "sleep 1000"
- in the process viewer select the "sleep 1000" node (which results in a onDidChangeSelection event)
- in the integrated terminal kill the "sleep" via Control-C

Observe: `onDidChangeSelection` does not fire

**Comment by sandy081** [comment]
Looks like tree is not triggering selection event in this case.

**Comment by joaomoreno** [comment]
I believe this is fixed by now.
