### ISSUE TITLE
onDidChangeActiveTerminal not fired on first terminal

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#52922]
Issue Type: <b>Bug</b>

Testing https://github.com/Microsoft/vscode/issues/52834.

- Open terminal with `Ctrl + \``.
- No `onDidChangeActiveTerminal` event is fired (unexpected).
- Set UI focus somewhere else in the workbench and then back to the terminal.
- `onDidChangeActiveTerminal` event is fired.

VS Code version: Code - Insiders 1.25.0-insider (368ab9c31b5c0930a40ab3f0e0d768ebbeeb9ef8, 2018-06-26T05:18:29.183Z)
OS version: Linux x64 4.15.0-22-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (2 x 2194)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|3.85GB (0.12GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders --user-data-dir=/home/parallels/devel/tmp/user --extensions-dir=/home/parallels/devel/tmp/exts|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.33

</details>

**Comment by chrmarti** [comment]
Similarly when restarting with a terminal open: `activeTerminal` is not set when starting early and `onDidChangeActiveTerminal` is not fired until I pass focus to it. That doesn't match the current API doc.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/53107
