### ISSUE TITLE
Menu: we need some kind of overflow behaviour when the menu is large

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#52924]
Refs: #52854

Steps:
* make the window small
* expand the "View" menu
* 🐛 it is not possible to reach most of the items

![image](https://user-images.githubusercontent.com/900690/41905961-f0c0f1ee-793c-11e8-867b-76d41583e804.png)

The native menu solves this a bit better by just going out of the window. I think we could also think about a scrollbar instead.

**Comment by sbatten** [comment]
dupe of #52533
