### ISSUE TITLE
Menu: make checked items more clear

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#52929]
Refs: #52854

I find the current indicator is too subtle and also should be to the left:

![image](https://user-images.githubusercontent.com/900690/41906470-376ff33c-793e-11e8-91be-63b248f2759d.png)

Compared to native:

![image](https://user-images.githubusercontent.com/900690/41906503-4beb92b2-793e-11e8-83b7-dc6e084392c5.png)

**Comment by sbatten** [comment]
@bpasero see experiment branch for use of svg. obviously it needs to pick up theme color, right now it is  just set up for a basic light theme. please comment on the look of the svg (sourced from @roblourens settings editor), placement, and margins of the menu to adjust.

**Comment by bpasero** [comment]
@sbatten yeah looks good in light theme:

![image](https://user-images.githubusercontent.com/900690/43880099-4377c39a-9ba7-11e8-9f72-2a107fbf8297.png)

But probably needs a matching icon for dark theme:

![image](https://user-images.githubusercontent.com/900690/43880114-5046b84c-9ba7-11e8-84a0-4a730a6e224e.png)
