### ISSUE TITLE
WorkspaceEdit for files isn't atomic/undoable

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#52927]
Refs: #52800

I could not find anywhere specified that if one workspace edit fails, all consective edits will not even be attempted.
If feel like this is good behavior but expect some explanation in our vscode.d.ts comments.

**Comment by joaomoreno** [comment]
I also wonder if we should specify the reason for returning false. How can an extension react correctly to a `false` result?

**Comment by jrieken** [comment]
Well, there is this: [`"the editor implements an 'all-or-nothing'-strategy,"`](https://github.com/Microsoft/vscode/blob/923e9ccb3fc44bfaaf4b4049015c84e42bc40f95/src/vs/vscode.d.ts#L6752) which is arguably written towards textual edits (for historical reasons) but the idea is the same. The problem is more the lack of composite undo and the lack of undoable file operations.

**Comment by joaomoreno** [comment]
@jrieken Wait, I don't think that's true. `all or nothing` means that either all run or none run. With these file system changes, you can have some run and others don't, since there's no rollback. The current strategy is more like `run until failure`.

**Comment by jrieken** [comment]
> The problem is more the lack of composite undo and the lack of undoable file operations.

Yeah, I think it's still a desirable goal ;-)

**Comment by joaomoreno** [comment]
It is... but aren't the docs wrong if they say it's `all or nothing`?

**Comment by jrieken** [comment]
yeah, I was hoping we can fix it once this goes to stable API... I'll reopen and see what I can do there

**Comment by jrieken** [comment]
@bpasero Is it in reach to undo a file operation? Anything like that supported or thought of in the file/textfile service?

**Comment by bpasero** [comment]
@jrieken the `IFileService` is probably not a good place for undo/redo, the `ITextFileService` is probably a good fit, but obviously needs some infrastructure to implement this. I think the challenge is to undo delete operations, whereas move and create (once added) are probably easier to get right.

**Comment by aeschli** [comment]
Slightly different topic, but also to be improved in the vscode.d.ts comment:

> Note that all changes are applied in the same order in which
> 	 * they have been added and that invalid sequences like 'delete file a' -> 'insert text in
> 	 * file a' causes failure of the operation.

For text edits applied at the same offset, the rule is:
If multiple inserts are made with the same position, these strings appear in the resulting text in the order the 'insert' was made.
