### ISSUE TITLE
WorkspaceEdit: deleteFile - no way to specify to ignore if does not exist

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#52923]
Refs: #52800

Have an extension with the following snippet code

```
 const workspaceEdit = new vscode.WorkspaceEdit();
        workspaceEdit.deleteFile(vscode.Uri.file('c:\\Development\\Test\\hello.txt'));
        workspaceEdit.createFile(vscode.Uri.file('c:\\Development\\Test\\hello2.txt'), {
            overwrite: true
        });
```
The first file should not exist.
Notice how the workspace edit will not get applied because the delete fails.
I would expect there is an `ignoreIfNotExists` the same way there is an ignoreIfExists for the `createFile` operation. This way they would be consistent
`renameFile` also does not have that option and I would expect it there for consistency

**Comment by joaomoreno** [comment]
Same for `renameFile`.

**Comment by jrieken** [comment]
Yeah, unsure if this is a need that exists because of testing or if language servers asking to delete files really don't know if those files exist... For create, TypeScript actually doesn't know...
