### ISSUE TITLE
Menus: submenus should not close when mouse moves out of them

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#52939]
Refs: #52854 

Steps:
* epxand a submenu
* move the mouse somewhere outside that menu
* the submenu closes

This makes it very hard to actually move the mouse into a submenu to select something

**Comment by octref** [comment]
Agreed. I think it makes more sense to hide the submenu when you move mouse on other items above/below `Editor Layout` in the main menu. 

![image](https://user-images.githubusercontent.com/4033249/41944283-f3d67a9c-795b-11e8-8ac9-24d025ae0950.png)

**Comment by sbatten** [comment]
I think the new behavior from https://github.com/Microsoft/vscode/commit/069a812bd723606d1bf4940ca9425dde6cd2a7bb and some extra polish that came later has addressed the spirit of this issue.
