### ISSUE TITLE
snippets variable not resolved in JSON proposal

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#52931]
Seen on Linux.

1. Open User Settings
2. Type `linux`, pick the `terminal.integrated.shell.linux` suggestion

You'll end up with 

```
"terminal.integrated.shell.linux": "${1:/usr/bin/zsh}",
```

You should've ended up with 

```
"terminal.integrated.shell.linux": "/usr/bin/zsh",
```

**Comment by aeschli** [comment]
The terminal sets the default for `terminal.integrated.shell.linux` to `process.env.SHELL`

**Comment by Tyriar** [comment]
I don't know what I could have done to change this, all I do is set the default value.

I'm guessing something changed in settings code as the default value is correct.

![image](https://user-images.githubusercontent.com/2193314/41939350-5caff3fc-794a-11e8-92e5-3db6d57e2229.png)

**Comment by roblourens** [comment]
@sandy081 where do these completions come from? These aren't from the configuration-editing extension. I didn't change anything related to this (as far as I can tell)

**Comment by sandy081** [comment]
These come from JSON language server.

**Comment by aeschli** [comment]
Problem is a change in the snippet engine:
The following user snippet reproduces the problem:
```json
{
	"test": {
		"prefix": "test",
		"body": [
			"\"terminal.integrated.shell.linux\": \"${1:/bin/bash}\"",
		]
	}
}
```

**Comment by jrieken** [comment]
@go2sh Sorry, but I don't wanna risk breaking more/other snippets and therefore I have un-done the custom snippet extensions. It now only supports `${«int»/«regexp»/«format»/«options»}` as spec'd here: http://manual.textmate.org/snippets.html#transformations. 

We will ship the next stable release soon and therefore little risk can be taken. Lets revisit early July and lets check for better solution to your problem.

**Comment by go2sh** [comment]
Ahh sorry, I didn't thought about that. :-/ I totally understand that you have to revert this. With backward compatibility in mind, there is no easy way to extend the current behavior. Maybe we could use some other special char like `?`, `#` to create some new extended behavior, which doesn't mess with the existing one.

**Comment by jrieken** [comment]
> Maybe we could use some other special char like ?, # to create some new extended behavior, which doesn't mess with the existing one.

Yeah, we should experiment with that. We can also take a look at existing, popular snippet extensions and see what kind of snippets they bring along
