### ISSUE TITLE
Would be great if the multi input had some information about the info I added before I finally execute them

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#52932]
Testing #52820

In the provided example it would be create to see the resource group I picked and the application name before I finally created them.

**Comment by chrmarti** [comment]
Should that be a separate confirmation step?

**Comment by dbaeumer** [comment]
Yes, that would satisfy me.

**Comment by misolori** [comment]
+1 to having a confirmation screen showing the summary of the selected items, which would then allow you to execute or go back and edit.
