### ISSUE TITLE
createQuickPick and createInputBox should document when to use them

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#52938]
Testing #52820 

Currently the doc says something like:

```
		 * Note that in many cases the more convenient [window.showQuickPick](#window.showQuickPick)
		 * is easier to use.

```

Would be cool to mention when to use them and not to mention `not` to use them.

**Comment by chrmarti** [comment]
I can add something saying that these should be used when the others are not sufficient. That seems like the most accurate way to put it.
