### ISSUE TITLE
Provide easier way to create workspace folder relative uris

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#52937]
Testing #52800

It would be much easier to create uris to give to `WorkspaceEdit` instances if we had utilities to create uris from relative paths inside folders.

Right now I have to do something like this:

```ts
vscode.Uri.file(path.join(folder.uri.fsPath, 'foo.js'))
```

Suggestions:

- `Uri.relative(path: string): Uri`
- `WorkspaceFolder.getRelativeUri(path: string): Uri`

I know our API isn't supposed to have utils... so I also see the counter argument.

**Comment by jrieken** [comment]
Unlikely to happen and I also think it's an artificial need that arises from toying around. I'd say that language brains creating workspace edits are already using absolute paths (maybe uris) so that this need doesn't exist.
