### ISSUE TITLE
Menu: Alt+F followed by Alt+S does not work properly

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#52935]
Refs: #52854

Steps:
* press `Alt+F` and keep `Alt` pressed
* press `S`

=> the Selection menu expands when I would expect the save action to trigger

**Comment by JackTrapper** [comment]
**Steps to Reproduce**

- Press `Alt`
- Press `F`
- Release `F`
- Press `S`
- Release `S` *(no save)*
- Release `Alt`
