### ISSUE TITLE
Menu: labels should not oveflow into keybindings

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#52940]
Refs: #52854

Steps:
* expand the Selection menu
* notice how one entry is long enough to enter the area of where keybindings are shown

![image](https://user-images.githubusercontent.com/900690/41907616-beb7acce-7941-11e8-9f25-5b2876625af5.png)

**Comment by sbatten** [comment]
I think that's normal enough.

<img width="329" alt="screen shot 2018-08-08 at 3 36 46 pm" src="https://user-images.githubusercontent.com/6561887/43868155-1228fe34-9b21-11e8-92d9-1513ab336f96.png">
