### ISSUE TITLE
`...` is not shown if diagnostics are overlapped

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#52943]
Testing #52218

```ts
collection.set(document.uri, [{
            code: '',
            message: 'Hello 1',
            range: new vscode.Range(new vscode.Position(8, 4), new vscode.Position(8, 10)),
            severity: vscode.DiagnosticSeverity.Hint,
            source: ''
        }, {
            code: '',
            message: 'Hello 2',
            range: new vscode.Range(new vscode.Position(8, 8), new vscode.Position(8, 20)),
            severity: vscode.DiagnosticSeverity.Hint,
            source: ''
        }]);
```

`...` is not shown for second diagnostic which starts from the middle of first

**Comment by jrieken** [comment]
@sandy081 I see the `...`

<img width="205" alt="screen shot 2018-06-26 at 14 06 41" src="https://user-images.githubusercontent.com/1794099/41910511-297b24f2-794a-11e8-8acb-2c0ec8d4a8d6.png">

**Comment by sandy081** [comment]
@jrieken Updated the description, I would expect to see two `...`s if the second one starts from the middle of first one

**Comment by jrieken** [comment]
Tricky... The three dots are a *no-repeat* background image and it seems that both decorations are the same element. Stretch for June

**Comment by jrieken** [comment]
Looks like both decorations are merged into one (the decoration starts at 8,4 and ends at 8,20). I am not sure why that and if that can be control...

<img width="336" alt="screen shot 2018-06-27 at 12 55 47" src="https://user-images.githubusercontent.com/1794099/41970043-a7cc58d4-7a09-11e8-9900-4b57482d5424.png">

**Comment by jrieken** [comment]
@alexandrudima can you advice?

**Comment by alexandrudima** [comment]
Yes, decorations get merged in order to paint squigglies as a continuous element. Oftentimes, extensions place many squiggles on top of each other or next to each other. This merging allows for these errors to be rendered using a single dom element and for the squiggle shape to look continuous.

**Comment by jrieken** [comment]
Idea is to have an decoration-option that controls the merge behaviour.
