### ISSUE TITLE
<Enter> broke in Settings.

### ISSUE THREAD

**Issue by sulkhanp** [Microsoft/vscode#52942]
- VSCode Version: 1.25 Insider
- OS Version: Win10

Steps to Reproduce:

1. In the latest insiders release go to settings.json
2. Try clicking enter to insert a newline in the editor.
3. Newline isn't inserted and nothing happens.

I believe this is related to this commit: 082918976ec2e8023ab21393f090ba0dd0b85fa7

Does this issue occur when all extensions are disabled?: Yes

**Comment by sulkhanp** [comment]
@roblourens is this the new intended behavior?

**Comment by roblourens** [comment]
Dupe of #52887
