### ISSUE TITLE
VS Code account 

### ISSUE THREAD

**Issue by walidovic05** [Microsoft/vscode#52947]
Hi VS Code team and fans,
During my internship , my superior asked me to work with the computer in the company not with mine. And so i had to install VS Code and all the extensions i use in my personnal computer(to feel like i'am using vs code on my computer) and that took me a lot of time to first search and then install them.

So i suggest a **VS code account**,
Whenever you need to use vs code in other computers and you miss your extensions so you need just to **login to your vs code account and you find your extension list** and then you feel free to install the ones you need or with one click you can install them all.

**Comment by roblourens** [comment]
This is tracked in https://github.com/Microsoft/vscode/issues/2743
