### ISSUE TITLE
Failed to manually update extension

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#52946]
Refs: #52811

1. Disable extension auto updates, Have some extension installed, open the `package.json` of that extension and modify its `version` to be lower
2. Reload vscode, notice vscode properly offering to update the extension, click yes ->
3. Failed to update error

If I try to uninstall the extension it no longer appears in the vscode ui, but it is left on disk. I would expect that VSCode is always able to remove the extension, even if a user manually modifies it

This happens for all extensions I have tried this process

**Comment by isidorn** [comment]
Hmm now if I change the package.json of an extension vscode complains that the extension has been modified on disk and that I should reload. IF I reload I no longer see the extension. I find this behavrior weird as the extension simply disapears beneth my feet -> reopening so we can discuss

**Comment by sandy081** [comment]
Looked at it with @isidorn and he has some previous state that uninstalled the particular version of the extension. Hence the extension disappeared when changed the version in the file.

With clean state everything looks ok. Hence closing.
