### ISSUE TITLE
use singular form of "breakpoints set but not yet bound" message 

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#52953]
testing https://github.com/Microsoft/vscode/issues/52296:

if a breakpoint is greyed out (unverified), the message uses the plural instead of singular form:
![2018-06-26_14-30-13](https://user-images.githubusercontent.com/1898161/41911782-e3c92f18-794d-11e8-83c3-43113471f87c.png)

**Comment by isidorn** [comment]
This message if coming from the debug adapter, thus I pushed a commit in the chrome debug core to fix this. fyi @roblourens
