### ISSUE TITLE
Backspace in terminal renderer deletes one character

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#52951]
Tests https://github.com/Microsoft/vscode/issues/52833

Have the following code (from the sample):

```
	let renderer;
	context.subscriptions.push(vscode.commands.registerCommand('terminalTest.terminalRendererCreate', () => {
		renderer = (<any>vscode.window).createTerminalRenderer('renderer');
		renderer.write(colorText('~~~ Hello world! ~~~'));
		renderer.onDidChangeMaximumDimensions(dim => {
			console.log(`Dimensions for renderer changed: cols=${dim.cols}, rows=${dim.rows}`);
		});
		renderer.onInput((input) => {
			renderer.write(input);
			console.log(`Input: ${input}`);
		})
	}));
```

- Create a terminal renderer
- type into the terminal which echos the charcters
- press backspace (observer one character is removed)
- type backspace again

Observe: nothing happens. Backspace should either always work or never.

**Comment by dbaeumer** [comment]
Actually the character is not deleted. It is only rendered back on back. If you move the cursor over it, it is still there.

**Comment by Tyriar** [comment]
I think this unexpected behavior is happening as 127 (DEL) is being passed directly to the terminal where normally that would be send to a shell for processing which wouild send back commands to move the cursor and remove the character before.
