### ISSUE TITLE
Update fails and leaves a wreck when update-folder is open in explorer

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#52958]
re #52824

* trigger an update via the product.json trick
* be curious how this works and open `C:\Users\jrieken\AppData\Local\Programs\Microsoft VS Code Insiders\_\resources\app` in the explorer
* apply the update
* 🐛 the update fails
* 💥 the installation is now broken

<img width="842" alt="screen shot 2018-06-26 at 14 43 09" src="https://user-images.githubusercontent.com/1794099/41913146-909d8426-7950-11e8-96a4-147a53c1ab87.png">
<img width="622" alt="screen shot 2018-06-26 at 14 43 18" src="https://user-images.githubusercontent.com/1794099/41913147-90bbb7f2-7950-11e8-8b3a-62b28fbb86c0.png">

**Comment by joaomoreno** [comment]
Can you show me the log file?

**Comment by jrieken** [comment]
Already nuked everything (reinstalled)... Where would that log-file be?

**Comment by joaomoreno** [comment]
`%TEMP%\vscode-inno-updater.log`

**Comment by joaomoreno** [comment]
#47841
