### ISSUE TITLE
Seeing both hovers while debugging

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#52950]
Seeing both hovers while debugging

![image](https://user-images.githubusercontent.com/5047891/41911496-17e86ada-794d-11e8-88dd-89e64b2b44e1.png)

(fyi @isidorn)

**Comment by isidorn** [comment]
So it seems like the debug does not properly disable it with your new options.
Do you want me to look into this?

**Comment by alexandrudima** [comment]
No, I will look into it, since I broke it. I just wanted to let you know in case you get duplicates.

**Comment by alexandrudima** [comment]
This must have been a dup of #53152
