### ISSUE TITLE
Menu: application logo overlaps menu in this case

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#52952]
Refs: #52854

Steps:
* configure VSCode to restore fullscreen ("window.restoreFullscreen": true)
* start in fullscreen
* leave fullscreen

=> 🐛 

![image](https://user-images.githubusercontent.com/900690/41911771-dba1c8ea-794d-11e8-9556-e276526f4de2.png)

**Comment by sbatten** [comment]
related to #53244
