### ISSUE TITLE
Menu: accessibility output is not the same as native menus

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#52955]
Refs: #52854

Comparing the output in NVDA between a native menu (Notepad) and the custom menu, I am seeing some differences:
* the keybinding seems to be read for a native menu (but not for the custom one)
* if the item has a mnemonic, its mnemonic is appended to the output (for native menu item)
* if you arrow over a top level item, its label and keybinding will also be read (for native menu)

**Comment by sbatten** [comment]
These should all be resolved due to a myriad of changes with focus behavior and aria labels
