### ISSUE TITLE
Undo stack inconsistent after placeholder transformation

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#52963]
Issue Type: <b>Bug</b>

Testing #52796

The snippet:
```json
"Something": {
	"prefix": "something",
	"body": [
		"// ${1/(..)(..)/${1:/upcase}${2:/capitalize}/g} $1 becomes: ${1/(.*)/${1:/upcase}/}",
		"// ${1/(sd)?/${1:?if:else}/}"
	]
}
```

Steps:
- Trigger the snippet
- Enter: `fdsa`
- Press Tab
- Undo several times
- `fdsa` is left

![undostack](https://user-images.githubusercontent.com/9205389/41914268-ceb98f00-7952-11e8-9ab2-bb4d7348f59e.gif)

VS Code version: Code - Insiders 1.25.0-insider (368ab9c31b5c0930a40ab3f0e0d768ebbeeb9ef8, 2018-06-26T05:11:12.670Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.14GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron --extensions-dir /Users/chrmarti/Development/repos/tmp/ext --user-data-dir /Users/chrmarti/Development/repos/tmp/user|
|Screen Reader|no|
|VM|20%|

</details>Extensions: none

**Comment by RMacfarlane** [comment]
Repro with a slightly simpler snippet:

```
"Snippet 1": {
		"prefix": "foo",
		"body": [
			"${1:placeholder1}",
			"${1/(.*)/good/}"
		]
	}
```

![undo](https://user-images.githubusercontent.com/3672607/41936914-a9d66f96-7943-11e8-8c75-f305a3b2b058.gif)
