### ISSUE TITLE
Dialog poped up while typing stealing focus

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#52967]
While I was typing a dialog popped up stealing focus:

![image](https://user-images.githubusercontent.com/900690/41914739-5acc6d36-7954-11e8-9672-84cc1a9a54d9.png)

I don't know what this is, I just created a new file test.ts in the vscode source tree.

At the very minimum I suggest to turn this into a non modal dialog.

**Comment by mjbvz** [comment]
Where you renaming or moving files? This is intentionally a modal dialog to prevent further edits to the files

**Comment by bpasero** [comment]
@mjbvz no I literally clicked "New File" in the explorer and created "test.ts".

**Comment by mjbvz** [comment]
Let me know if you hit this in the latest insiders build. I added a workaround on our side that should prevent this from happening

**Comment by bpasero** [comment]
I can still reproduce with Insiders `499122702e462b458117122a6885e6aeb3cec0a4`. Steps:
* open `openAnythingHandler.ts` wait until TS has loaded
* create a file `test.txt`
* type `console.log("foo")`
* from the explorer rename it to `test.ts`

=> 🐛 a dialog pops up asking if the imports should be updated too

I wonder if this is related to my change to use `ITextFileService.move()` when renaming (via https://github.com/Microsoft/vscode/blob/6ca99aca80e80224f1c0bd4370c6ec4941c3bc54/src/vs/workbench/services/textfile/common/textFileService.ts#L716)?

**Comment by mjbvz** [comment]
Seems fixed in TS 3.0 but broken in 2.9.x. I'm going to add a workaround that check if the renamed file contains any exported symbols before trying to update paths

**Comment by mjbvz** [comment]
Note that the workaround is not complete. If you create an export in the new file and then rename it, you still get false edits. This is fixed in TS 3.0 in my testing
