### ISSUE TITLE
Inconsistent propagation of transformed placeholder

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#52968]
Issue Type: <b>Bug</b>

Testing #52796

Snippet:
```json
	"Something": {
		"prefix": "something",
		"body": [
			"// ${1:another ${2:placeholder/(.*)/${1:/downcase}/}/(.*)/${1:/upcase}/}",
			"// $1",
			"// $2"
		]
	}
```

- Insert snippet
- 1st placeholder: `one`
- Tab
- 2nd placeholder: `TWO`
- Tab
- `TWO` was propagated once in lowercase and once in uppercase which seem inconsistent.

![nestedplaceholder](https://user-images.githubusercontent.com/9205389/41915644-7cc825ea-7956-11e8-84ad-6e8eda9aad50.gif)

VS Code version: Code - Insiders 1.25.0-insider (368ab9c31b5c0930a40ab3f0e0d768ebbeeb9ef8, 2018-06-26T05:11:12.670Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.15GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron --extensions-dir /Users/chrmarti/Development/repos/tmp/ext --user-data-dir /Users/chrmarti/Development/repos/tmp/user|
|Screen Reader|no|
|VM|20%|

</details>Extensions: none

**Comment by jrieken** [comment]
This seems to work differently in SublimeText but I won't say it works much better...

**Comment by jrieken** [comment]
Yeah, that's actually weird

**Comment by jrieken** [comment]
Closing as out of scope. A few things have change so that a statement like that isn't possible anymore, e.g you cannot use a transform in the first occurrence of a placeholder . Using snippet below works better but not yet perfect.

```
"Something": {
		"prefix": "something",
		"body": [
			"${1:one ${2:two}}",
			"${1/(.*)/${1:/upcase}/}",
			"${2/(.*)/${1:/downcase}/}"
		]
	},
```
