### ISSUE TITLE
Dragging a file onto editor space always grids

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#52962]
* open vscode, have an empty editors-area
* drag a file from the explorer
* 🐛 it's very easy to open that file aside or atop but it's quite hard to open the file taking all space, esp with small screens. IMO the grid'ing shouldn't happen when no editor is open

![jun-26-2018 15-05-13](https://user-images.githubusercontent.com/1794099/41914172-8797209c-7952-11e8-9437-2bdfba670374.gif)

**Comment by bpasero** [comment]
@jrieken we could special-case the empty case, but you might still hit this issue when a file is opened. Compared to before-grid, the hit-zone for initiating the split is larger (I think now we are at 20% around the center and previously it was 10%). Maybe we also need to reduce that hit zone.

**Comment by bpasero** [comment]
I ended up going with a solution that makes this conditional based on wether an editor is dragged or an editor group to get as close as possible to our stable behaviour:
* dragging an editor: only 10% margin around the editor to initiate a split
* dragging an editor: 30% margin to initiate a split (*)

(*): this depends also on the `workbench.editor.openSideBySideDirection` setting. if the user prefers to split to the right, it will be 30% for left/right but only 10% for top/bottom and vice versa

**Comment by jrieken** [comment]
![jun-28-2018 12-44-29](https://user-images.githubusercontent.com/1794099/42029815-12e70b4c-7ad1-11e8-8c32-0bfbec1e3bb8.gif)

**Comment by bpasero** [comment]
This is actually bug that the grid always had but now became more of an issue with the reduced size for splitting at the corners. This reproduces only when tabs are enabled and the issue was that the 35px of the title area was pushing down the drop-zone to a point where you could not split anymore to the bottom.

**Comment by bpasero** [comment]
@jrieken please see if that commit I pushed fixes your issue for you, I am not sure why you hit it so easily given that the window seems rather large in your case. I could reproduce only with a smaller window.
