### ISSUE TITLE
Test Core language pack support in VS Code

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#52960]
Ref: #50588

Complexity: 4

- [x] windows: @dbaeumer 
- [x] mac  @chrmarti  
- [x] linux  @joaomoreno

In this release, VS Code is bundled with only english language and other core languages are removed. Please test following scenarios and make sure users are guided properly to install required language packs so that they can have VS Code in the UI language they want.

**Core Languages:** ` ['de', 'en', 'en-US', 'es', 'fr', 'it', 'ja', 'ko', 'ru', 'zh-CN', 'zh-Hans', 'zh-TW', 'zh-Hant']`

**Note:** Make sure that prompts are shown in both OS language and English

**Note:** Latest stable build is [here](https://vscode-builds.azurewebsites.net/builds/stable)

## Fresh Installation

1. When VS Code is freshly installed on a machine with english language OS its UI is shown in english by default and no prompts to install language packs should be shown.

2. When VS Code is freshly installed on a machine with non-english language OS (for eg., Chinese) its UI is shown in english by default and user should see a prompt to install the language pack of OS language

3. When VS Code is freshly installed on a machine and user starts VS Code from CLI by passing locale option `code --locale=de` then its UI is shown in english by default and user should see a prompt to install the language pack of language passed in arguments (de).

## Update

1. When VS Code is updated from 1.23 or 1.24 to current stable on a machine with OS language is one of the core languages, its UI should be shown in OS language without any prompts if the corresponding language pack has been install on 1.23 or 1.24.

2. When VS Code is updated from 1.22 or lesser to current stable on a machine with OS language is one of the core languages, its UI should be shown in english language. If OS language is non-english, then user should see a prompt to install the language pack of OS language.

**Comment by joaomoreno** [comment]
@sandy081 All great!

**Comment by chrmarti** [comment]
@joaomoreno Checking your checkbox, maybe that was lost.
