### ISSUE TITLE
Grid: when opening a 2x2 grid existing editors are misplaced

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#52975]
Issue Type: <b>Bug</b>

Open two files side by side
View -> Editor Layout -> Grid 2x2
Note that the editor that was on the right hand side is now underneath the other editor.
Expected both editors to remain positioned side by side on the top row with two empty cells underneath each in the second row

This is made a little worse by the fact that when you then drag the editor from the bottom left to the top right, the group in the bottom left is closed.

VS Code version: Code - Insiders 1.25.0-insider (368ab9c31b5c0930a40ab3f0e0d768ebbeeb9ef8, 2018-06-26T05:18:23.085Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3687U CPU @ 2.10GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (1.08GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
jshint|dba|0.10.19
vscode-eslint|dba|1.4.12
tslint|eg2|1.0.33
vscode-great-icons|emm|2.1.35
vscode-gutter-preview|kis|0.12.2
vscode-azureappservice|ms-|0.8.1
vscode-cosmosdb|ms-|0.7.2
azure-account|ms-|0.4.1
csharp|ms-|1.15.2
vs-keybindings|ms-|0.2.0
team|ms-|1.136.0
debugger-for-chrome|msj|4.7.0
addDocComments|ste|0.0.8
cordova-tools|vsm|1.4.0

</details>

![twofilestogrid2](https://user-images.githubusercontent.com/1704059/41917801-04d02b76-7953-11e8-9496-28e75cef60ae.gif)

Found while testing: https://github.com/Microsoft/vscode/issues/52334

**Comment by bpasero** [comment]
This depends a little bit on the root orientation and might be hard to get right, but I am willing to look into this to see if there is something lowhanging we can do.

/cc @joaomoreno

**Comment by joaomoreno** [comment]
@bpasero Maybe we can preserve the original orientation?
