### ISSUE TITLE
DAP protocol visualisation

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#52974]
Refs: #52866

https://microsoft.github.io/language-server-protocol/inspector/app

As you now nicely visualize LSP protocols we might consider in the future to reuse this to visualize debug adapter protocol messages.
fyi @weinand @roblourens

**Comment by roblourens** [comment]
I would stick to my logs which include traffic between the adapter and runtime, and internal logs in the adapter. But others might find it useful!

**Comment by octref** [comment]
If there's need we can revisit, but some of the UI is tied to LSP and not that easily reusable in DAP visualization.

**Comment by hyangah** [comment]
@roblourens @weinand @isidorn I also think DAP visualization tool is useful as we add more debugging support through DAP. Reusing LSP inspector code is just one way to achieve this.

Is there anyone who's already working on this? Should I open this issue in the debug adaptor protocol repo so more DAP users can see the progress or lack thereof?

**Comment by hyangah** [comment]
From the slack channel, I learned about https://github.com/microsoft/language-server-protocol-inspector/issues/38 where the discussion continues.

**Comment by weinand** [comment]
I'll move the issue to the DAP repo.
