### ISSUE TITLE
LSP Inspector: App seems hidden

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#52978]
Refs: #52866

I feel like the App tab is the main thing and it is hidden away.
App also does not feel like a good name so I would try to get rid of it.
I would somehow try to emphasize it for example it could be the default view, and the usage could be folded on top. So the usage and app are not equal siblings

**Comment by sbatten** [comment]
I agree with this. The current representation looks less like 2 options and more like a title and subtitle where Usage is the title and App is the subtitle. App almost looks unclickable.
