### ISSUE TITLE
Group disappears when dragging duplicate file onto it from another group

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#52970]
Issue Type: <b>Bug</b>

Turn tabs off
Open a file
Split the editor so that there are two groups, each containing the same file
Now open another file in one of the groups.
You should have two groups. One group has two files (say fileA and fileB). The other group has one file (say fileA).
Select fileA in the group that contains two files.
Drag it over to the group that contains fileA only
Make sure that the selection rectangle covers the whole group before dropping.
When dropped, notice that the whole group disappears.

![draggingduplicatefileclosesgroup](https://user-images.githubusercontent.com/1704059/41915877-ac5dc100-794e-11e8-8f45-0c6872887a7b.gif)

Found while testing: https://github.com/Microsoft/vscode/issues/52334

VS Code version: Code - Insiders 1.25.0-insider (368ab9c31b5c0930a40ab3f0e0d768ebbeeb9ef8, 2018-06-26T05:18:23.085Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3687U CPU @ 2.10GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (0.35GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
jshint|dba|0.10.19
vscode-eslint|dba|1.4.12
tslint|eg2|1.0.33
vscode-great-icons|emm|2.1.35
vscode-gutter-preview|kis|0.12.2
vscode-azureappservice|ms-|0.8.1
vscode-cosmosdb|ms-|0.7.2
azure-account|ms-|0.4.1
csharp|ms-|1.15.2
vs-keybindings|ms-|0.2.0
team|ms-|1.136.0
debugger-for-chrome|msj|4.7.0
addDocComments|ste|0.0.8
cordova-tools|vsm|1.4.0

</details>

**Comment by bpasero** [comment]
@stevencl there is a setting to control this behaviour: `"workbench.editor.closeEmptyGroups": false` will change it to the behaviour you expected.

I thought this would be a good default because it matches exactly with how we behave today without grid. I would like to keep our UI as simple as possible and not add empty groups unless the user opted in. Would you agree?

**Comment by stevencl** [comment]
Oh, sorry, I got confused. I didn't notice fully what had happened. I think with tabs off it was a little more confusing for me. I just didn't look at the open editors list to confirm what had  happened. Sorry!

**Comment by bpasero** [comment]
@stevencl no problemo
