### ISSUE TITLE
Expose product name in API, as env.productName

### ISSUE THREAD

**Issue by alefragnani** [Microsoft/vscode#5297]
Is there a way (API) to detect the current release where the extension is running?

I would like to know this info, so I could differentiate my _user data_, which is stored on local disk instead of `context.workspaceState.update`. 

Thanks in advance.

**Comment by jrieken** [comment]
@alefragnani There no such thing as a _project name_ constant but you can use the `ExtensionContext` and the `extensionPath` constant. That's the location your extension which will contain the product specific install location, like `.vscode-insider/extensions` (https://code.visualstudio.com/docs/extensionAPI/vscode-api#ExtensionContext)

**Comment by alefragnani** [comment]
@jrieken Thanks for your suggestion

I will be using it, until the new API be available.

**Comment by jrieken** [comment]
> I would like to know this info, so I could differentiate my user data, which is stored on local disk instead of context.workspaceState.update.

We have now the `appName` in the API which is the product name. I still wonder why you need this and cannot use the `workspaceState` cos that already scopes by product etc

**Comment by alefragnani** [comment]
Hi @jrieken ,

The contents that I'm saving is a JSON file. I did't use `workspaceState` because I wanted to let the user to have easy access to this file. So, I decided to use the same approach as `keybindings.json` and `settings.json`.

Your suggestion (to use `ExtensionContext` and `extensionPath`) does the trick, so for me it would be enough. But since you decided to add an API, I pretend to move to that API, when available. 

What do you think about it?

**Comment by jrieken** [comment]
It makes sense to store things outside in a readable file. My concern with using the product name is that it's not a 'derive storage location path' api but just a string and its value might change. So, while it is _VS Code Alpha_ today it is not impossible that it becomes _Visual Studio Code Alpha_ in the future. 

I would recommend that you generate a storage file name, using the `appName`, but then store that filename using the `ExtensionContext` and retrieve it from there. That gives you speaking filenames but isn't prune to breaking like path-math is. 

Unsure where exactly you store those files, but we could talk about exposing the directory path in which VS Code store global-global settings, like `/Users/jrieken/Library/Application Support/Code - Alpha/User/settings.json`

**Comment by alefragnani** [comment]
Well, I'm embarassed... that's exactly what I was looking for :disappointed: I should have make it clear right in the first post. I didn't know that you would expose that folder, so I was using it just for convenience, thinking in better alternatives.

I'm sorry, I didn't mean to make you waste your time with this. I will be more careful next time.

**Comment by jrieken** [comment]
no worries. I have created a new request for that won't likely won't make it in April any more as we are in lock down since today...
