### ISSUE TITLE
vscode界面的中文改成英文

### ISSUE THREAD

**Issue by chwentao** [Microsoft/vscode#5298]
- VSCode Version:1.0.1
- OS Version:win7

今天更新到版本1.0.0之后 vscode界面成了中文，怎么改回到英文？

**Comment by love19862003** [comment]
ctrl+p 输入语言 修改语言版本。

**Comment by wk472150269** [comment]
F1 -> 语言设置 -> 修改为en-US -> 保存重启 VSCode

**Comment by Lonefy** [comment]
F1 输入 ‘配置语言’
![image](https://cloud.githubusercontent.com/assets/7921431/14553082/3ceaeb14-0316-11e6-9a29-620ed4c0197e.png)
改为
![image](https://cloud.githubusercontent.com/assets/7921431/14553094/57c89b2a-0316-11e6-9f22-bc7e44dd8b85.png)

保存后重启

**Comment by love19862003** [comment]
我知道啊。 我只是觉得这样太不友好了。中文输入很慢的。就是希望能兼容中文和英文的命令

2016-04-15 

love19862003 



发件人：Lonefy <notifications@github.com>
发送时间：2016-04-15 14:31
主题：Re: [Microsoft/vscode] vscode界面的中文改成英文 (#5298)
收件人："Microsoft/vscode"<vscode@noreply.github.com>
抄送："fanny.wu"<love19862003@163.com>

F1 输入 ‘配置语言’

改为

保存后重启

**Comment by chwentao** [comment]
已经解决 谢谢各位  上面方法都是有效的

**Comment by Lonefy** [comment]
@love19862003 是啊 insider 0.10.13的时候提过，貌似vscode team目前只是提供了修改配置的方法。。

**Comment by Tyriar** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/4679

**Comment by hiyangguo** [comment]
👍
