### ISSUE TITLE
Feature Request: Pinned Directories in File Explorer

### ISSUE THREAD

**Issue by SCJack25** [Microsoft/vscode#52986]
It would be nice, and extremely helpful to have a section for pinning folders in the file explorer.

1. Concept: Perhaps add a section between "Open Editors: and the "working directory" for quick access to sections/files we are working on.

2. Need: Currently having to scroll through numerous core files, files we don't wish to be working on at the time, and most importantly hundreds of node modules in order to view the one single module we want to see.

Thanks so much for listening and please let me know if I can provide any further assistance.

**Comment by isidorn** [comment]
Try using multi root workspaces instead.
Leaving this open as a feature request
