### ISSUE TITLE
Do not ship CodeSignSummary-*.md

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#52982]
Download a zip build of VSCode e.g. https://az764295.vo.msecnd.net/insider/923e9ccb3fc44bfaaf4b4049015c84e42bc40f95/VSCode-win32-x64-1.25.0-insider.zip 

Observe the CodeSignSummary file. We should not ship this file.

**Comment by joaomoreno** [comment]
Oh that's new...
