### ISSUE TITLE
Suggestion: always show recommendation status

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#52980]
Testing: https://github.com/Microsoft/vscode/issues/52850

After I choose to `Ignore Recommendation` I can't turn the recommendation back on, unless editing local storage I presume.  The only time I have the opportunity to `undo` a recommendation is when I choose to ignore it.

Suggestion: If I search for an extension that was recommended in the past, but I've chosen to ignore it, show the message that I've chosen to not receive recommendations and allow me to `undo`.

![image](https://user-images.githubusercontent.com/1487073/41920239-237c3f62-7915-11e8-83a4-051dd7ba50ca.png)

So, the flow would look like this:

- See a recommendation for the beautify extension
- Choose to ignore it
- Later on, search for the beautify extension
- The note `You have chose not to receive recommendations...` is shown with the `undo` option

**Comment by ramya-rao-a** [comment]
> Suggestion: If I search for an extension that was recommended in the past, but I've chosen to ignore it, show the message that I've chosen to not receive recommendations and allow me to undo.

Showing the msg in this case is an valid ask. It gives credibility to the extension that it was once recommended. 

But, the credibility may be misplaced. The recommendation may not be valid anymore. It may not be applicable to the user or could have gotten stale or removed from our white list or could have been an experimental recommendation.

As for the undo button in this case, it feels unnecessary. By this time, if you have chosen to search for a specific extension, clicked on it for the editor to open, read the message that it was once recommended, and then decide that this extension is indeed relevant to you, you might as well just install it right away, or search again in the future. 

Thoughts?

**Comment by chrisdias** [comment]
in the cases where it is no longer valid, simply don't show the option to restore the recommendation.

**Comment by ramya-rao-a** [comment]
Its not trivial to maintain list of valid but ignored list. Especially now that we have so many different kinds.

So unless we **really** want to do this, I'd rather not.

**Comment by ramya-rao-a** [comment]
Also, the fix for this is dependent on #52989.
So once #52989 is fixed, we can determine whether its trivial to maintain the valid but ignored list across sessions.

**Comment by JacksonKearl** [comment]
Closed with #53178

**Comment by ramya-rao-a** [comment]
You now can undo the ignore you did from the previous VS Code sessions.

**Comment by misolori** [comment]
Verified

![image](https://user-images.githubusercontent.com/35271042/42010883-a9ca406a-7a45-11e8-8ee5-2d46a8afce37.png)

**Comment by ramya-rao-a** [comment]
@misolori We just added this in today and the change is not in the latest Insiders. How did you test?
Did you test across sessions?

**Comment by misolori** [comment]
@ramya-rao-a I tested this from the latest on `master`. Should I be verifying these from insiders?

**Comment by ramya-rao-a** [comment]
Yes, we usually verify bug fixes using the Insiders.
Its ok, no harm done :)

**Comment by misolori** [comment]
🙈 I'll use Insiders next time
