### ISSUE TITLE
Undo ignore recommended extension does not place extension back in the recommended list

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#52989]
Issue Type: <b>Bug</b>

Open extension recommendations
Click on one
In the editor, click the ignore recommendation button
Note that the extension is removed from the recommended extension list as expected
Click on the undo button in the editor
Note that the recommended extension is not placed back in the list. 

VS Code version: Code - Insiders 1.25.0-insider (368ab9c31b5c0930a40ab3f0e0d768ebbeeb9ef8, 2018-06-26T05:18:23.085Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3687U CPU @ 2.10GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (1.07GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
jshint|dba|0.10.19
vscode-eslint|dba|1.4.12
tslint|eg2|1.0.33
vscode-great-icons|emm|2.1.35
vscode-gutter-preview|kis|0.12.2
vscode-azureappservice|ms-|0.8.1
vscode-cosmosdb|ms-|0.7.2
azure-account|ms-|0.4.1
csharp|ms-|1.15.2
vs-keybindings|ms-|0.2.0
team|ms-|1.136.0
debugger-for-chrome|msj|4.7.0
addDocComments|ste|0.0.8
cordova-tools|vsm|1.4.0

</details>

![undodoesntwork](https://user-images.githubusercontent.com/1704059/41921311-7d8d5118-795a-11e8-987f-9fe02437e520.gif)

Testing: https://github.com/Microsoft/vscode/issues/52850

**Comment by JacksonKearl** [comment]
Note: this only applies to non-workspace recommendations. Will look into

**Comment by ramya-rao-a** [comment]
Re-opening as we are considering never to put back the item on the list and just say that it will be added back in the future. This will simplify https://github.com/Microsoft/vscode/issues/52980

**Comment by JacksonKearl** [comment]
Closed with #53178
