### ISSUE TITLE
After ignoring extension recommendation, still get a notification about extensions that can help

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#52984]
Issue Type: <b>Bug</b>

No python or vue extensions installed
Open a python file and a vue file
Get recommendations for extensions associated with python and vue
Ignore each recommendation
Reload window
Get a notification about extensions in the marketplace that can help

VS Code version: Code - Insiders 1.25.0-insider (368ab9c31b5c0930a40ab3f0e0d768ebbeeb9ef8, 2018-06-26T05:18:23.085Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3687U CPU @ 2.10GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (1.20GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
jshint|dba|0.10.19
vscode-eslint|dba|1.4.12
tslint|eg2|1.0.33
vscode-great-icons|emm|2.1.35
vscode-gutter-preview|kis|0.12.2
vscode-azureappservice|ms-|0.8.1
vscode-cosmosdb|ms-|0.7.2
azure-account|ms-|0.4.1
csharp|ms-|1.15.2
vs-keybindings|ms-|0.2.0
team|ms-|1.136.0
debugger-for-chrome|msj|4.7.0
addDocComments|ste|0.0.8
cordova-tools|vsm|1.4.0

</details>

![extrec](https://user-images.githubusercontent.com/1704059/41920537-d9803046-7958-11e8-89df-2719b1615f87.png)

Testing: https://github.com/Microsoft/vscode/issues/52850

**Comment by ramya-rao-a** [comment]
This happens only for file types for which there is no out of the box support in VS Code.
For example, this wouldn't happen for C#, Go or python files.
But will happen for vue

vue is the only case where we show a recommendation for a specific extension (vetur) for a file type that is not supported out of the box.

Its not trivial to skip the second notification, so will revisit this if there is more user feedback in this area.
