### ISSUE TITLE
Debug toolbar should stick to right side of screen

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#52992]
Issue Type: <b>Bug</b>

#52686

Repro:

1. Make the window width small
2. Move the debug toolbar to the top-right corner of the editor:

   <img width="230" alt="screen shot 2018-06-26 at 8 09 11 am" src="https://user-images.githubusercontent.com/2193314/41921659-3a7f88d8-7918-11e8-9118-cc934b44c33c.png">

3. Increase the width of the window

   <img width="333" alt="screen shot 2018-06-26 at 8 09 36 am" src="https://user-images.githubusercontent.com/2193314/41921691-4946e14a-7918-11e8-8dea-8b87c3bed3cb.png">

I would expect it to stay in the top-right corner on top of the minimap.

VS Code version: Code - Insiders 1.25.0-insider (368ab9c31b5c0930a40ab3f0e0d768ebbeeb9ef8, 2018-06-26T05:11:12.670Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 3|
|Memory (System)|16.00GB (2.79GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_1118481|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|1.4.4
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.33
vscode-npm-script|eg2|0.3.4
git-project-manager|fel|1.6.1
debugger-for-chrome|msj|4.7.0
material-icon-theme|PKi|3.5.0
polacode|pnp|0.2.2
gitblame|wad|2.4.2
vscode-todo-highlight|way|0.5.12

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
This is a fair request. However the widget is currently not aware of the outside layout calls does it can not particape in this resizing.
I would consider changing this if more users ask for this. In the meantime, backlog
