### ISSUE TITLE
Unable to assign Function key for a shortcut

### ISSUE THREAD

**Issue by wzup** [Microsoft/vscode#52998]
Issue Type: <b>Bug</b>

**Bookmarks: Toggle** shortcut is `cmd+alt+k` by default.

I want to assign `F2` for **Bookmarks: Toggle**.

But Function keys are not accepted.

#### Reproduce

1. Open shortcuts: cmd+k, cmd+s
2. Find Bookmarks
3. Double click `Bookmarks: Toggle` to set keys
4. Try to click `F2` - nothing happens. Function keys are not working for shortcuts.

How to fix?

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.79GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
Bookmarks|ale|0.19.1
gitignore|cod|0.5.0
vscode-babel-coloring|dza|0.0.4
react-native-react-redux|EQu|1.9.0
auto-close-tag|for|0.5.6
beautify|Hoo|1.3.2
graphql-for-vscode|kum|1.12.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
smartsemicolon|seu|1.0.3
vscode-react-native|vsm|0.6.11
propertylist|zho|0.0.2

(3 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
This works for me. Not sure whether it's a keybindings editor issue or a keyboard layout issue.

Are you using a non-english keyboard layout?

**Comment by wzup** [comment]
@roblourens 
Indeed, non-english and and PC keyboard with Mac

**Comment by roblourens** [comment]
Is there anything in here that helps? https://github.com/Microsoft/vscode/wiki/Keybinding-Issues
