### ISSUE TITLE
Add Color Distinction Between Split Windows

### ISSUE THREAD

**Issue by MarkPhillips** [Microsoft/vscode#52994]
When Editors Are In Split Windows, their distinction could be amplified by applying a different shading to each window. (Like a html odd even).

Thanks for VS Code

**Comment by bpasero** [comment]
@MarkPhillips do you mean separate windows or separate editors showing up in the same window side by side?

**Comment by MarkPhillips** [comment]
Not sure of terminology. I'm referring to when Split is selected from the
menu

**Comment by bpasero** [comment]
Marking as duplicate of https://github.com/Microsoft/vscode/issues/35379
