### ISSUE TITLE
Heavy lag when typing

### ISSUE THREAD

**Issue by vijaysrao** [Microsoft/vscode#52993]
The previous versions worked well (subtle lag was tolerable), but this version started creating annoying amount of lag between typing and display on the screen. 
Version details:
Version 1.24.1
Commit 24f62626b222e9a8313213fb64b10d741a326288
Date 2018-06-13T17:47:35.732Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by roblourens** [comment]
Does it happen if you start with `--disable-extensions`?
