### ISSUE TITLE
[ts] 'privateFunction' is declared but its value is never read.

### ISSUE THREAD

**Issue by francofslab15** [Microsoft/vscode#52997]
Got here and found an issue similar to: https://github.com/Microsoft/vscode/issues/51814 which was marked as not reproducible.

Verified that the insiders build has the same issue as the current release. So I used it to test it without any external extensions.

- VSCode Version: 1.25.0-insider
- OS Version: Windows 10 Pro - Version 1803 - Build 17134.112

Steps to Reproduce:
Using latest TypeScript npm package, create the typescript class below:
```ts
export class Test {
    private _someVar: boolean = false; //[ts] '_someVar' is declared but its value is never read.

    public somePublicFunction = function() {
        var lib = new ExternalLibrary();
        this._somePrivateFunction();
    }

    private _somePrivateFunction = function() { //[ts] '_somePrivateFunction' is declared but its value is never read.
        if (this._someVar) { //_someVar is read here.
            console.log(':/');
        }
    }
}
```

Does this issue occur when all extensions are disabled?: Yes

This happens only when we declare class functions as anonymous. Although not a best coding practice, VSCode is still flagging those variables or functions incorrectly.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#25232
