### ISSUE TITLE
Killing a split terminal causes a visual bug in non-default themes

### ISSUE THREAD

**Issue by misolori** [Microsoft/vscode#52995]
Issue Type: <b>Bug</b>

Originally was testing #52835 but this repros on the insiders build so unsure if it's related.

Whenever you split a terminal and then proceed to kill it, there is a visual bug on the right side of the terminal that only appears in our non-default (dark/light) themes. This goes away when you move focus away.

![ezgif com-gif-maker 23](https://user-images.githubusercontent.com/35271042/41922088-300671b8-7919-11e8-8eca-6b095ed699b7.gif)

VS Code version: Code - Insiders 1.25.0-insider (368ab9c31b5c0930a40ab3f0e0d768ebbeeb9ef8, 2018-06-26T05:11:12.670Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.20GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_3789725|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
svgo|100|0.8.0
vscode-svgo|ajh|0.1.0
gitlens|eam|8.4.1
python|ms-|2018.6.0

(3 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/51094
