### ISSUE TITLE
Issue of  Sizing in different browser in html code 

### ISSUE THREAD

**Issue by drifter1007** [Microsoft/vscode#52990]
Hey,
While creating  the site  i having issue in sizing  .the fixed width i created of 1000px not working  in  FireFOx and chrome it showing wrong output  but its working in Internet explorer .One more thing while using same code in codepen.io  it working perfectly in any browser.  

Different scenario for same code :-

Code in Chrome
[https://www.dropbox.com/s/9k5argcovnz7y9c/chrome.png?dl=0](url)
Same code in InternetExplorer .THis code look like similiar to original code  in IE but in chrome n firefox
its not working.
[https://www.dropbox.com/s/yij1lga8qif61xv/iess.png?dl=0](url)
Clone i want to create .  
[https://www.dropbox.com/s/iomp7r1nftqi639/orignalsite.png?dl=0](url)

**Comment by roblourens** [comment]
This sounds like a problem with your code, not the vscode editor.

**Comment by drifter1007** [comment]
@roblourens then why the same code working fine in codepen.io or Internet explorer

**Comment by drifter1007** [comment]
As new bee its all going over the head..
I think i have to leave VS code n switch back to Atom.
