### ISSUE TITLE
It should be possible to include paths in search in Go to file dialog

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#53]
**Repro:**

1. `mkdir -p foo/bar`
2. `echo 'test' > foo/bar/test`
3. `Code .`
4. `Ctrl+P` to open Go to file
5. Type `foo/bar/test`

**Expected:**
The test file is the best match

**Actual:**
No matches found

**Comment by KingHenne** [comment]
:+1:

Furthermore, typing parts of the full path, e.g. `fobate`, should also be a match.
(See TextMate’s "Go to File" for comparison.)

**Comment by asaf** [comment]
+1 ! (Expecting same behavior as in Sublime)

**Comment by bpasero** [comment]
This is coming for december.
