### ISSUE TITLE
File/Folder picker

### ISSUE THREAD

**Issue by SamVerschueren** [Microsoft/vscode#530]
In my Yeoman plugin, I run the generator in the current workspace. Off course, if no workspace is opened, it fails (at the moment). That's why it would be nice if we had a file/folder picker that I could use to pick the current working directory (`cwd`).

More information at https://github.com/SamVerschueren/vscode-yo/issues/21#issuecomment-159148393

// @bpasero

**Comment by bpasero** [comment]
@SamVerschueren does #58 help you?

**Comment by SamVerschueren** [comment]
Somehow yes. I guess it would allow me to ask the user where he wants to run the generator and call `vscode.commands.executeCommand('vscode.openFolder', uri);` But that would still force the user to manually type the entire path into a normal input box right? There is no way to open the UI file picker and let the user navigate and select a directory via that way?

**Comment by bpasero** [comment]
@SamVerschueren I pushed a change so that the new `vscode.openFolder` command can be called without arguments which will bring up a native folder picker. The second optional argument `newWindow` can still be used to force the picked folder to open in a new window or not.

**Comment by SamVerschueren** [comment]
Thanks @bpasero! Appreciate the effort.
