### ISSUE TITLE
Can you make the VSC to support multi project debug?

### ISSUE THREAD

**Issue by SilentTiger** [Microsoft/vscode#5300]
Can you make the VSC to support multi project debug?
I mean, just like in VS, make user be able to open more than one project folder at the same time, and can debug them in the same time?

I think that would be a wonderful feature.
Thank you so much!

**Comment by egamma** [comment]
@weinand fyi

**Comment by weinand** [comment]
@SilentTiger VS Code already supports to open more than one project folder. And every project has its own window and supports its own debug session.
What is currently not supported is opening a **single** project in **multiple** windows. A consequence of this is that you cannot have more than one debug session for a single project.
A workaround exists: add a subfolder to your project and open that folder in another VS Code window.
This helps if your project consists of a client and a server: if you move the server into a server sub folder you can debug client and server at the same time.

**Comment by SilentTiger** [comment]
@weinand Thanks for your reply.
I'm afraid my description made you misunderstand.
I did not mean to open single project in multiple windows, I mean open **multiple** projects in **single** window.

For example, a project consists of a client and a server, if I can debug them in just one VSC window but not two VSC windows, such as what I did in VS, that would be great.

I opened this issue because I have a big project consists with 5 different NodeJS projects, and I need to run and debug them at the same time, so if I open them in separated windows, there will be 5 VSC windows full of my screen.

Thank you so much!

**Comment by weinand** [comment]
@SilentTiger how should multiple debug sessions in one window work?

**Comment by SilentTiger** [comment]
@weinand 
This is my screen on VS2015 with NTVS 1.1
I run two projects at same time, and I can set break point on both projects.

![shot](https://cloud.githubusercontent.com/assets/764862/14560026/83b63ef8-033f-11e6-9bfd-b0d8271549b2.png)

**Comment by weinand** [comment]
@SilentTiger what's about the stack trace and data views?

**Comment by SilentTiger** [comment]
@weinand  You can see that the app1.js is paused by the break point, and the app2.js is still running. The left bottom window of VS is local variables, and the right on it is stack trace.
![shot](https://cloud.githubusercontent.com/assets/764862/14592759/cbfac424-0554-11e6-86a9-7bf4b9824761.png)

**Comment by weinand** [comment]
@SilentTiger and if both are stopped in a breakpoint?

**Comment by SilentTiger** [comment]
@weinand It can not stop more than one project by break poins at sametime.
But I still think it's a great feature to run two or more projects in one VSC window. In fact, I can first set break point in project A to pause the process and then set a break point in project B to pause the process later without restart them.
Maybe you could have a try on VS2015 about this feature.

Of course, VS2015 has its own problem, it would be very slow when the project contains too many js files, while VSC did really great in this kind of situation.

**Comment by weinand** [comment]
@SilentTiger "It cannot stop more than one project by breakpoins at the same time." That's exactly one of the issues we want to avoid in VS Code. But that would require to be able to show multiple threads, stacktraces, variables, debug console etc. Doing this with multiple windows is much clearer and simpler than squeezing it into one window.

**Comment by weinand** [comment]
This feature made its first appearance in the October 2016 release. In the November release we are fine tuning the UI. See https://github.com/Microsoft/vscode/issues/14450.
