### ISSUE TITLE
Menu: Custom title menu should say Meta/Super instead of Windows on Linux

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#53002]
#52854

**Comment by bpasero** [comment]
I am actually surprised this bug exists, @sbatten aren't you using some keybinding helper to turn the keybinding into a human readable label?

**Comment by sbatten** [comment]
@bpasero yea I'm using the keybinding service, yes, I'm not doing anything special on my own I don't believe.

**Comment by Tyriar** [comment]
Related: https://github.com/Microsoft/vscode/issues/55060

**Comment by Tyriar** [comment]
PR out: https://github.com/Microsoft/vscode/pull/55061
