### ISSUE TITLE
Menu: Why is the custom title bar enabled on Linux?

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#53001]
#52854

It looks super weird having a Windows-style title bar with the Windows menu font. Also I don't think we get any real accessibility benefits out of it as alt shortcuts work fine using the native title bar and we don't support screen readers on Linux.

**Comment by bpasero** [comment]
@Tyriar a lot of people ask for a themable title area though, so I think there is still people that would want this. I agree though that the styling should be Linux specific and not Windows if possible.

**Comment by Tyriar** [comment]
> a lot of people ask for a themable title area though

I always saw those issues as better integrating with the native, like https://github.com/Microsoft/vscode/issues/49967 and https://github.com/Microsoft/vscode/issues/36667

> I agree though that the styling should be Linux specific and not Windows if possible.

I'm not sure this is possible though as it's so customizable and different on every distro, the best you could get is based on the default Ubuntu theme.

---

I'll close this off as I guess it can't hurt much to have it there. The only problem I can think of is if someone wants to share their settings file across platforms and have different values for each.
