### ISSUE TITLE
VSCode extensions folder searched

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#53000]
Issue Type: <b>Bug</b>

1. Install GitLens, or run the `Gitlens: Welcome` command
2. Search `setTimeout`

A result is included from `.vscode-insiders/extensions`, the `welcome.html` from the GitLens webview. Also repros if the welcome webview is closed before searching. I'm not sure if this is an issue with what GitLens itself is doing, but I wouldn't expect files within the vscode extensions folder to be indexed and searched. This also repros with stable.

![screen shot 2018-06-26 at 9 35 25 am](https://user-images.githubusercontent.com/3672607/41926654-d1461b4a-7924-11e8-82e5-977a4bba9b70.png)

VS Code version: Code - Insiders 1.25.0-insider (923e9ccb3fc44bfaaf4b4049015c84e42bc40f95, 2018-06-26T13:00:22.932Z)
OS version: Darwin x64 17.4.0

<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.12
gitlens|eam|8.4.1
vscode-rust|kal|0.4.2
vscode-pull-request-github|Mic|0.0.1
vscode-language-pack-hu|MS-|1.25.0
debugger-for-chrome|msj|4.7.0

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Fixed with another issue in 1.28
