### ISSUE TITLE
Menu: Keyboard focus border should not be visible when the menu was opened with the mouse

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#53003]
#52854

![image](https://user-images.githubusercontent.com/2193314/41927102-1241817e-7926-11e8-90e2-b3554d6b0d69.png)

Maybe it should show only after pretty up or down when it was opened with the mouse?

**Comment by sbatten** [comment]
related to #52933

**Comment by joaomoreno** [comment]
It's also pretty awkward that the border isn't around the whole row.

**Comment by sbatten** [comment]
as mouse focus === keyboard focus now with #54428, I'm going to close this issue. However, #52913 will stay open
