### ISSUE TITLE
Custom Title: right clicking on title bar should show standard menu

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#53011]
#52854

Right clicking should show something like this:

![image](https://user-images.githubusercontent.com/2193314/41927861-43be4154-7928-11e8-96a1-f57cd222f7d0.png)

**Comment by sbatten** [comment]
@Tyriar This should already be working. Can you provide repro steps?

**Comment by Tyriar** [comment]
@sbatten right click the title bar on Linux.

**Comment by Tyriar** [comment]
FYI this is the standard menu on Ubuntu 18/gnome.

![image](https://user-images.githubusercontent.com/2193314/41980076-74de9de4-79da-11e8-8405-0910a7bf7b00.png)

max/min and close should be included as a minimum.

**Comment by sbatten** [comment]
On windows, this works because the OS returns that menu on right-click of a draggable region. We can't listen for mouse events on a draggable region as I understand https://github.com/electron/electron/issues/1354

**Comment by sbatten** [comment]
@deepak1556 similar to the issue with shift clicking the taskbar in windows.

**Comment by deepak1556** [comment]
Closing as this is a `wontfix` in upstream
