### ISSUE TITLE
jsonc strings are wrong color

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#53010]
- Use Monokai
- In stable, strings in a jsonc file are white
- In Insiders, they are yellow
- The `string.quoted.double.json` rule is not matching

**Comment by Nxt3** [comment]
This fix seems to have ruined the coloring of all JSONC files. Before, I had the same colorings of JSON files in JSONC files. This is no longer the case--everything is the same color now in JSONC files.
