### ISSUE TITLE
帮助-切换开发人员工具

### ISSUE THREAD

**Issue by pk111and222** [Microsoft/vscode#5301]
- VSCode Version:1.0.0
- OS Version:window10 64

Steps to Reproduce:

1. 打开一个文件
2. 切换开发人员工具
3. 关闭开发人员工具
4. 崩溃

**Comment by Lonefy** [comment]
Steps:
*1 File -> new File
*2 Help -> Toggle Developer Tool
*3 Help -> Toggle Developer Tool
*4 Crash

**Comment by egamma** [comment]
@Lonefy thanks for the translation.

I cannot reproduce on win10 given these steps.

**Comment by Lonefy** [comment]
@egamma  I reproduce this problem by  `File -> new File`

**Comment by Lonefy** [comment]
@egamma I try these steps for several times, and I find that this will happen only with `Toggle Developer Tool` when I repeat the 2ed and 3rd steps.

**Comment by egamma** [comment]
I can reproduce it now. It doesn't happen all the times on the second time and you have to continue to execute the toggle developer tools action.

**Comment by alexlur** [comment]
I can reproduce this issue with Visual Studio Code 1.0 on OS X El Capitan.

**Comment by bpasero** [comment]
#4430
