### ISSUE TITLE
Custom Title: Icons differ from standard windows icons

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#53015]
#52854

- Minimize line is thicker
- Maximize box is smaller
- Close button is smaller
- Restore is smaller and blurry

Top: Notepad
Bottom: VS Code

![image](https://user-images.githubusercontent.com/2193314/41928200-3c647468-7929-11e8-90e3-4f39446877c4.png)

Notepad:

![image](https://user-images.githubusercontent.com/2193314/41928292-92b72bc6-7929-11e8-97d6-c6d85a37f7a7.png)

VS Code:

![image](https://user-images.githubusercontent.com/2193314/41928323-ae52b6a2-7929-11e8-8d2c-30a2bdda121f.png)

**Comment by misolori** [comment]
@sbatten is there any way to use the native icons? I'm trying to look for the originals in case we need to specify the svgs.

**Comment by sbatten** [comment]
@misolori not sure how they are drawn by the OS, but I think the icons are part of the Segoe MDL2 Assets font in Windows 10.

**Comment by Tyriar** [comment]
I think an SVG will always have the possibility of being blurry won't it, because SVGs don't have the features that fonts do to align to the pixel grid?

**Comment by neilsustc** [comment]
FYI, I think this will be fixed with #53211.

**Comment by sbatten** [comment]
seems resolved. please verify @Tyriar
