### ISSUE TITLE
Read only workspace: an error should be shown when dragging a file from another workspace

### ISSUE THREAD

**Issue by misolori** [Microsoft/vscode#53018]
Issue Type: <b>Bug</b>

Testing #52573

If I drag a file from another workspace into my read-only workspace nothing happens. I would expect an error to be shown.

![ezgif com-gif-maker 24](https://user-images.githubusercontent.com/35271042/41929212-38f3743e-792c-11e8-9c65-ddec05a71db2.gif)

VS Code version: Code - Insiders 1.25.0-insider (923e9ccb3fc44bfaaf4b4049015c84e42bc40f95, 2018-06-26T13:00:22.932Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.38GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_4183037|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
svgo|100|0.8.0
vscode-svgo|ajh|0.1.0
gitlens|eam|8.4.1
python|ms-|2018.6.0

(4 theme extensions excluded)

</details>

**Comment by misolori** [comment]
This also happens when dragging a file from within the read-only workspace to another folder in the same workspace. We should disable the hovering when dragging so it doesn't appear like you are able to do that, otherwise it looks very confusing.

![ezgif com-gif-maker 25](https://user-images.githubusercontent.com/35271042/41929509-1b673ef4-792d-11e8-8d91-0437ac752991.gif)

**Comment by isidorn** [comment]
@misolori good points. However I personally prefer not to throw errors like crazy.
For now I have decided to disable the drag feedback, so a noop is not so surprising.

If we get user feedback that errors are expected in these cases then I might reconsider
