### ISSUE TITLE
Suggestion: append a "Read-only" label in the editor tabs for files that are read only

### ISSUE THREAD

**Issue by misolori** [Microsoft/vscode#53022]
Issue Type: <b>Bug</b>

Testing #52573

When you have multiple workspaces (including a read-only one), it's hard to tell which files opened are the read-only ones. Wondering if it's worth appending a `Read-only` label so it's easier to see when you're in other tabs.

![image](https://user-images.githubusercontent.com/35271042/41930177-1e95c5a8-792f-11e8-971e-91efda708a5d.png)

VS Code version: Code - Insiders 1.25.0-insider (923e9ccb3fc44bfaaf4b4049015c84e42bc40f95, 2018-06-26T13:00:22.932Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.38GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_4183037|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
svgo|100|0.8.0
vscode-svgo|ajh|0.1.0
gitlens|eam|8.4.1
python|ms-|2018.6.0

(4 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
I like the idea of specially decorating the tab - not sure if add read-only is the best due to limitied horizontal space.
@bpasero thoughts?

**Comment by bpasero** [comment]
@isidorn @misolori we can do it, a similar thing exists when a file is deleted on disk:

![image](https://user-images.githubusercontent.com/900690/41965962-2a4649ca-79fe-11e8-9775-75d56f776e5a.png)

There might be a better way to indicate these things, so maybe worthwhile for a UX discussion.

**Comment by isidorn** [comment]
Yeah, I can bring it up in next weeks ux call

**Comment by isidorn** [comment]
I like being consistedf with deleted from disk, so I went with that approach.

**Comment by roblourens** [comment]
Hey @isidorn I'm seeing this show up at the wrong time

![image](https://user-images.githubusercontent.com/323878/43622968-bf23c340-9693-11e8-8010-036aff63f4cc.png)

**Comment by isidorn** [comment]
Thanks @roblourens for catching that, I did a n00b mistake, pushed a fix. Is it ok now?

**Comment by vvs** [comment]
In the latest insiders build, basically all my tabs are now with (read-only). :)

**Comment by isidorn** [comment]
@vvs yeah I was very stupid. There will be a new insiders release soon, you will survive for a couple of hours :)

**Comment by vvs** [comment]
Thank you, @isidorn, I barely survived, but the latest insiders build fixed the problem! :)

But seriously, many, many thanks for all the hard work you guys are putting in the amazingVS Code, which makes my life much, much easier! :)

**Comment by isidorn** [comment]
@vvs glad to hear, you are welcome. Enjoy :)
