### ISSUE TITLE
Menu: Provide theme keys for menu

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#53020]
#52854

I want to theme this:

![image](https://user-images.githubusercontent.com/2193314/41929963-8ffaafe8-792e-11e8-9e47-114e3e72997f.png)

Doesn't look like I can:

![image](https://user-images.githubusercontent.com/2193314/41929981-9c99683e-792e-11e8-88f5-6b65c36379d4.png)

**Comment by sbatten** [comment]
dupe of #52914
