### ISSUE TITLE
Redo Not Working

### ISSUE THREAD

**Issue by pertrai1** [Microsoft/vscode#53026]
- VSCode Version: Version 1.25.0-insider (1.25.0-insider)
- OS Version: High Sierra 10.13.5 (17F77)

Steps to Reproduce:

1. Add code to a file
2. Cut some of the code
3. Press `cmd+shift+z` to redo

Note that this does not redo what was just done.

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by JacksonKearl** [comment]
I'm not able to reproduce this on the latest Insiders. Could you be more specific about both what you mean by "cut some of the code", and when you are pressing `cmd-z` to perform the undo you'd like to revert?

In general though, it's expected that you wont be able to redo anything besides an undo; to revert the changes made by your cut operation (whether that's a `cmd-x` or a `del`), you should use `cmd-z`.

**Comment by pertrai1** [comment]
@JacksonKearl what is the expected result of Edit -> Redo? That command is `cmd+shift+z`.  If I undo some code and then I want it back, how would I go about doing that? I would expect redo to undo the previous action. Is that the wrong thinking?

**Comment by roblourens** [comment]
This sounds like correct unless I'm misunderstanding. You want to undo the cut operation with cmd+z.
