### ISSUE TITLE
Read only workspace: using commands from extensions that edit/format a file should trow an error

### ISSUE THREAD

**Issue by misolori** [Microsoft/vscode#53024]
Issue Type: <b>Bug</b>

Testing #52573

There should be an error shown when an extension tries to edit/modify a read-only file. Right now nothing happens. See "Prettify JSON" example below.

![ezgif com-gif-maker 26](https://user-images.githubusercontent.com/35271042/41931152-0ea940ae-7932-11e8-92f4-fa7130913f98.gif)

VS Code version: Code - Insiders 1.25.0-insider (923e9ccb3fc44bfaaf4b4049015c84e42bc40f95, 2018-06-26T13:00:22.932Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.38GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_4183037|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
svgo|100|0.8.0
vscode-svgo|ajh|0.1.0
gitlens|eam|8.4.1
python|ms-|2018.6.0

(4 theme extensions excluded)

</details>

**Comment by JacksonKearl** [comment]
Not just extensions, currently it seems only "type" commands show errors. Delete should show errors too, and builtin commands like transpose should as well.

**Comment by isidorn** [comment]
This is a known limitation of the readonly editor that extensions can still go crazy and execute their commands.
However if they use the file system provider which is readonly it will through an error - though they can alwasy go directly to node and there is nothing we can do.
So for now pushing this to the backlog as I have no immediate plans to fix
