### ISSUE TITLE
vscode 1.0 editor.fontSize not work for tip or autocomplete

### ISSUE THREAD

**Issue by sswangifly** [Microsoft/vscode#5302]
- VSCode Version:1.0
- OS Version:windows 10

Steps to Reproduce:

1. change the editor.fontSize in the settings.json
2. the editor font size has success changed,but not the tip and autocomplete

**Comment by joaomoreno** [comment]
Autocomplete: #2465

What do you mean by *tip*?

**Comment by sswangifly** [comment]
yes IntelliSense.

**Comment by joaomoreno** [comment]
Closing as duplicate of #2465
