### ISSUE TITLE
Terminal Menu: Include "Paste Active File Path"

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#53033]
Testing: #52835

This will be much more useful than "Run Active File" and "Run Selected Text".

**Comment by octref** [comment]
In addition, I think "Run Active File" should be removed.

- It actually runs the file instead of putting down the command to the terminal and give user a chance to Enter / Cancel.
- It does not handle anything other than sh files. For js files, at least it should be `node ${activeFilePath}`. For others -- I'm not sure. It's better to include "Paste Active File Path", so people can do
  - Enter `node`, paste file path, run it
  - Enter `ruby`, paste file path, run it

**Comment by Tyriar** [comment]
This is an established command that has existed and been used for I think over 12 months, we can't just remove it. 

As for pasting the path, you can do this easily by using the copy active file path command`ctrl+k p`

**Comment by octref** [comment]
@Tyriar I just meant "remove from menu", not "remove the command".

![image](https://user-images.githubusercontent.com/4033249/41935776-c01dc4c4-793f-11e8-9534-717063f38250.png)

I feel `Paste Active File Path` would be a better fit. As `Run Active File` only work for sh files, and only sh files which you have run `chmod +x` on, I don't think it can justify a place in the context menu.

But then just realized we have `workbench.action.files.copyPathOfActiveFile` but no command to paste active file path.
