### ISSUE TITLE
Ignore Recommended Extension only works on open readme/editor

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#53035]
`Extensions: Ignore Recommended Extension (workspace folder)` only works when an extension's readme is open as an editor.

I expected that the command worked off of selection in the Extension viewlet, not the open editor. I did a multi-select in the extension viewlet, then chose to Ignore them for the workspace, but only one was added to `extensions.json`.

**Comment by ramya-rao-a** [comment]
There is no context menu available for extensions in the extensions viewlet.
The one place where a menu is available, is shown under the gear icon and only for installed extensions to show actions like Enable/Disable/Uninstall.

The ignore action is usually for an uninstalled recommended extension. Adding a new gear and a context menu with a single entry seemed excessive. Therefore, we opted for a command that works on the opened extension editor.

For multi-select see the other issue you logged. https://github.com/Microsoft/vscode/issues/53043
