### ISSUE TITLE
Filter entries in Outline by type

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#53034]
Testing #52799

The outline view would be even more useful to me if I could filter it to just show classes, methods, and functions. I want to see a high-level view of the parts of a file, and I rarely want to see local variables. They add a lot of noise when browsing or searching.

**Comment by Mochnant** [comment]
Seems like very useful functionality!

**Comment by fiddleplum** [comment]
Is there any progress on this issue yet? It really makes the outline view near useless to me for JavaScript, since it enumerates every single local variable and even for-loop variable, and the whole point is to have an outline of the file, not an enumeration of every local variable. Ideally it would show everything except local variables.

**Comment by itssimon** [comment]
Same here. I'm using VSCode for Python and would love the outline to show a high-level outline of a file. With all the variables in there, the outline is almost as long as the code itself and as such useless as an outline. Can this please be prioritised? I assume it's a fairly easy feature to implement but would provide tremendous value.

**Comment by DaleCBrooks** [comment]
Would really like to see this option in the Python Outline:  1) Tree structure by type with collapsible nodes.  Otherwise, there's too much content in the outline, making it unusable.

**Comment by NorthboundTrain** [comment]
Outline view is nearly useless without this in both Perl and Bash. Thanks!

**Comment by flavius** [comment]
The outline is useless without this in rust as well.

**Comment by brain90** [comment]
+1 variable list should hidden by default. Very distracting.

**Comment by GerrGIT** [comment]
After years of working with all kind of editors, the VSCode is the most awesome tool I'm using so far. It doubles my workflow speed. It's close to perfect, except this issue. I'm working with PHP and MVC frameworks, the outline would be so helpful to hop between methods. But because of showing the variables it's to long and therefor useless now. A simple setting "Outline variables collapsed on default" yes/no would be awesome. Really looking forward to when this issue will be completed.

**Comment by hipoglucido** [comment]
I cannot agree more. Please let the user choose what to see in the code outline (variables filtered out by default seems reasonable to me).

**Comment by danlub** [comment]
Another user fustrated with this behaviour of the outline tool in Python. When I want to use the outline is when the file is long, so seeing the variables makes this unusuable.
Somehow this doesn't happen with Fortran

**Comment by mitchjam** [comment]
I'm in PHP Laravel and the inability to view a classes methods in a concise list is very, very frustrating. I'm about to turn green, put some purple shorts on, and throw this macbook at a barista.

**Comment by egabrum** [comment]
Guys, if you find that the outline view is useless, you might want to check CodeMap Explorer. It's pretty basic, but at least it can be used for something.

**Comment by arigit** [comment]
+1 ask - python user to be able to list just functions to help manage / remove the noise in the outline

**Comment by jrieken** [comment]
I have pushed a change that adds `outline.filteredTypes.variable` etc etc settings. That allows to turn on/off filtering for each type the outline can show.

<img width="570" alt="Screenshot 2019-10-10 at 10 43 57" src="https://user-images.githubusercontent.com/1794099/66553180-f01c3b00-eb4a-11e9-8f05-3dbb3b510b9b.png">

<img width="574" alt="Screenshot 2019-10-10 at 10 43 46" src="https://user-images.githubusercontent.com/1794099/66553201-fca09380-eb4a-11e9-88da-b13fa688dd08.png">

**Comment by fiddleplum** [comment]
@jrieken This is perfect! Thank you :)

**Comment by danlub** [comment]
This is great! Thanks!
When will it be included in the stable version, approximately?

**Comment by GerrGIT** [comment]
Looks awesome indeed! Hope it will be in the next update, thanks a lot.

**Comment by jrieken** [comment]
This is in todays [insiders](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=2ahUKEwi_7bL6rJvlAhVBaVAKHU2pCVAQFjAAegQICBAC&url=https%3A%2F%2Fcode.visualstudio.com%2Finsiders%2F&usg=AOvVaw0f8kL4zvRmKCp9_9q4hy9V) and will be in the next stable release.

**Comment by egabrum** [comment]
@jrieken Great! Thanks! 
Could this very-sensible feature be also applied to the breadcrumbs? 
It would also be great if we could access the outline directly from the Activity Bar.

**Comment by jrieken** [comment]
Yeah, breadcrumbs supports this as well, it's the same settings but prefixed with "breadcrumbs.filteredTypes"

**Comment by jrieken** [comment]
Verifier: make sure there is a `breadcrumbs.filteredTypes.xyz` setting

**Comment by roblourens** [comment]
It seems like this doesn't work for breadcrumbs?  I have this code:

```js
const a = 1;

function foo() {
}
```

and these settings:

```json
"breadcrumbs.filteredTypes.variable": false,
"outline.filteredTypes.variable": false,
```

Not hidden from breadcrumbs:

![image](https://user-images.githubusercontent.com/323878/67808452-f750ad80-fa53-11e9-9059-d9528ae12cf7.png)

Hidden from Outline:
![image](https://user-images.githubusercontent.com/323878/67808467-ff105200-fa53-11e9-9f57-4eb5416347b0.png)

**Comment by jrieken** [comment]
This is for breadcrumbs: https://github.com/microsoft/vscode/issues/69279#issuecomment-547681858

**Comment by joaomoreno** [comment]
Assigned to November!
