### ISSUE TITLE
extensions.json completions, warnings

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#53038]
Testing #52850

I seem to get IntelliSense/Completions for installed extensions in the `recommendations` section, but I don't get completions in the `unwanted Recommendations` section.  Maybe the show the current list of recommended extensions if we can't show the full list from the Marketplace.

Also, I don't get validation of the contents provided by completions. For example, if I choose the extension `chrisdias.vscode-opennewinstance` from the completion list, then modify the entry to something incorrect, no error/warning.

**Comment by ramya-rao-a** [comment]
The completions for the `recommendations` section are provided via an built-in extension. Extensions have access to installed extensions but not to recommended extensions or uninstalled extensions.
Which is kinda ok, as chances are you would be recommending an extension for a workspace that you already have installed and use in the workspace.

Regardless, #37225 tracks the feature request to provide completions for uninstalled extensions.

For the `unwantedRecommendations` section, providing completions for just installed extensions doesnt make sense. Chances are you dont want to ignore an installed extension. So I would use #37225 to track completions in general.

Regarding validation, the only thing we do is to make sure the format of the text provided is of the form `publisherid.extensionid`.
We dont validate the publisher id or the extension id itself. This would require accessing the gallery which the extension cant do at the moment.
