### ISSUE TITLE
ability to open extensions.json from prompt

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#53032]
testing #52850 

It would be nice to have a link on this prompt to open the workspace `extensions.json`.  that way i can see what was done.

![image](https://user-images.githubusercontent.com/1487073/41932163-181b9d0a-7935-11e8-9f8d-1c252e08f503.png)

**Comment by ramya-rao-a** [comment]
Link in the text mostly is not possible, as that works only for actual links.
We might have to add a button that says `View changes` which opens the file that was edited.
