### ISSUE TITLE
Show Recommended Extensions shows different list every time

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#53044]
Testing https://github.com/Microsoft/vscode/issues/52850

When I open the Extensions Viewlet and choose `Show Recommended Extensions` from the overflow menu, I get a new/different list every time I execute the command.

From a user's perspective, I don't understand why I keep getting a new list.  I expect that when I issue the command VS Code shows me all of the recommended extensions. Otherwise, I keep clicking the menu to see what else might be recommended.

**Comment by ramya-rao-a** [comment]
The ones that change are the tool based recommendations and the one we infer from telemetry. There is no ranking mechanism for these, and so are shuffled to give all a chance to be shown.

What we can do is do the shuffle only once for each VS Code session.

**Comment by chrisdias** [comment]
yes, for each session sounds good. i can imagine that if we have not yet done the more costly recommendations then the 2nd or 3rd time i invoke `show recommended extensions` that more are added to the list.

**Comment by ramya-rao-a** [comment]
> i can imagine that if we have not yet done the more costly recommendations then the 2nd or 3rd time i invoke show recommended extensions that more are added to the list.

I didnt follow that. Are you saying that we should keep adding to the list every time `Show Recommended Extensions` is invoked? Why?
