### ISSUE TITLE
flutter doctor doesn't dettect visual studio code

### ISSUE THREAD

**Issue by ndlive** [Microsoft/vscode#53047]
Issue Type: <b>Bug</b>

flutter doctor doesn't dettect visual studio code

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (4.33GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
flutter-snippets|ale|0.0.2
dart-code|Dar|2.14.0
flutter|Dar|2.14.0
anaconda-extension-pack|ms-|1.0.0
python|ms-|2018.6.0
team|ms-|1.136.0
vscode-yaml|red|0.0.13

</details>

**Comment by roblourens** [comment]
What is flutter doctor? Please give details of exactly what the issue is.
