### ISSUE TITLE
How to highlight a .tpl file as HTML

### ISSUE THREAD

**Issue by biij5698** [Microsoft/vscode#5304]
希望可以像sublime那样，原生支持.tpl扩展文件，依然高亮显示HTML代码

**Comment by bingzheyuan** [comment]
He means that he wants syntax hightlight in .tpl file the same as in HTML file, which sublime surpports.

**Comment by BillyONeal** [comment]
Something like:

```
"files.associations": {
"*.tpl": "html"
}
```

in your user preferences may work.

**Comment by biij5698** [comment]
yes,thank you @BillyONeal
