### ISSUE TITLE
Outline doesn't show 'container' type

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#53048]
Testing #52799

- The symbol quick pick shows the 'container' type from the symbol provider. Like from unit test navigate:
![image](https://user-images.githubusercontent.com/323878/41937107-48f9b416-7944-11e8-86ff-319fff133a76.png)
- But they aren't shown in the outline view:
![image](https://user-images.githubusercontent.com/323878/41937132-580f6aa4-7944-11e8-81bf-f96ff0246956.png)

Was that on purpose? It's useful for the unit-test-navigate extension. Not sure what other extensions might use it for.

**Comment by jrieken** [comment]
Yeah, that on purpose. The `containerName` exists in the old API only as a weak hint towards the containing/parent type. With the new API, there is that as parent-node and a symbol can have a `detail` property for extra information.
