### ISSUE TITLE
createQuickPick API: missing intellisense for property values

### ISSUE THREAD

**Issue by misolori** [Microsoft/vscode#53041]
Issue Type: <b>Bug</b>

Test #52820 

Unsure if this is related, but when I attempted to use `${state.name}` on a property there was no intellisense to help guide me towards the right value (after selecting `state` nothing was shown to proceed).

Expected
<img src="https://user-images.githubusercontent.com/35271042/41935289-fe1a1b12-793d-11e8-85b7-fdca9b5619a4.png" width="300"/>

Result
![ezgif com-gif-maker 27](https://user-images.githubusercontent.com/35271042/41935010-2bf33e34-793d-11e8-8770-359b54cd4b4d.gif)

VS Code version: Code - Insiders 1.25.0-insider (923e9ccb3fc44bfaaf4b4049015c84e42bc40f95, 2018-06-26T13:00:22.932Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
svgo|100|0.8.0
vscode-svgo|ajh|0.1.0
gitlens|eam|8.4.1
python|ms-|2018.6.0

(4 theme extensions excluded)

</details>

**Comment by chrmarti** [comment]
This works for me:
![image](https://user-images.githubusercontent.com/9205389/41957974-ee2142de-79e8-11e8-9233-2d17918b4a43.png)

Does it work after reloading the window?

**Comment by misolori** [comment]
@chrmarti this comes back after reloading the window. Is this a bug worth looking into or should we close it?

**Comment by mjbvz** [comment]
Does any intellisense work in that case?

**Comment by misolori** [comment]
@mjbvz it does work after reloading the window. In my original bug, I had the window open for an extended period of time (a few hours) and am wondering if something timed out.

**Comment by mjbvz** [comment]
OK. Let me know if you hit this again
