### ISSUE TITLE
 How to distinguish global/user installations when uninstalling

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#53058]
Testing #52824

I want to uninstall the user-level installation, how can a user tell which is which?

![image](https://user-images.githubusercontent.com/323878/41941618-66f6c9f6-7951-11e8-8650-3ad652a234e2.png)

**Comment by joaomoreno** [comment]
We can probably change the name over there.

**Comment by JacksonKearl** [comment]
Verified on the label, but when I tried to uninstall, I got a warning message about running the uninstaller, which is from an untrusted publisher. 

I was able to just click okay, but I'm not sure if that would be possible for someone without admin privileges on the system. This seems slightly off... you can install Code, but not uninstall.

**Comment by joaomoreno** [comment]
Yeah it's possible for someone without admin priviledges to uninstall, you just have to click next. #2416
