### ISSUE TITLE
Breaking change inside the API?

### ISSUE THREAD

**Issue by TheAifam5** [Microsoft/vscode#53052]
- VSCode Version: 
Version 1.24.1
Commit 24f62626b222e9a8313213fb64b10d741a326288
Date 2018-06-13T17:51:32.889Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

- OS Version: Windows 10

Steps to Reproduce:

I noticed the bug inside the VSCode, here is more information about the issue. The logs are just the same (except the extension-related source path and lines, but callstack is the same).
- https://github.com/christophschlosser/doxdocgen/issues/79
- https://github.com/kasecato/vscode-docomment/issues/67

Does this issue occur when all extensions are disabled?: No

**Comment by roblourens** [comment]
Can you give some steps on how to repro the issue, or details on what you think is wrong? Otherwise I'd assume it's an issue in the extension.
