### ISSUE TITLE
Should TerminalRenderer with cropped rows be top aligned?

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#53059]
#52833

Create a terminal renderer that sets `dimensions.rows` to a small value:

```ts
renderer.dimensions = {
	cols: renderer.maximumDimensions.cols,
	rows: 4
}
```

Notice that terminal content is positioned at the bottom of the panel instead of at the top. I expected it to be aligned to the top left corner instead

**Comment by Tyriar** [comment]
@IlyaBiryukov thoughts?

**Comment by IlyaBiryukov** [comment]
Sorry for noticing this one just now. As long as the whole terminal screen area is visible (e.g. `dimensions.rows <= maxDimensions.rows`) and user can scroll to see the history, I think it is fine either way. Positioning at the bottom has an advantage of displaying more of the previous history, while positioning at the top might look more natural for full screen experiences.
