### ISSUE TITLE
Vscode does not recognize my git remote repo

### ISSUE THREAD

**Issue by achawla5000** [Microsoft/vscode#53051]
Issue Type: <b>Bug</b>

Vscode has stopped tracking changes in my repo.  Branch name does not show any more in bottom left hand corner of screen.  Try "Pull" command from menu, and I get message "Your repository has no remotes configured to pull from."  On this system git integration with vscode had been working perfectly fine for the past 1.5 years; suddenly, it is not working.  Using the command line, I can successfully get the latest changes from the remote repo and also push changes to the remote repo.  Git version is 2.11.0.windows.1.  Executing the command git remote -v from the command line shows that I have a remote repo configured.  Apparently, vscode is not recognizing the repo; but why?

Update:  I added the following in the User Settings config, and this did not resolve the issue -
"git.path": "C:\\Program Files\\Git\\cmd\\git.exe"
Also, I added this to my Environment Variables (system variables) 
;C:\Program Files\Git\cmd
This did not resolve the issue.

Update:  Upgraded to git version 2.18.0.windows.1, and this seems to have had no effect on my issue.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:52:25.282Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.38GB (9.44GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe C:\Git\Issunc\i3bo-playground|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
file-templates|brp|1.2.0
vscode-great-icons|emm|2.1.35
json-tools|eri|1.0.2
beautify|Hoo|1.3.2
vscode-angular2-emmet|jak|2.0.3
Angular2|joh|6.1.1
mssql|ms-|1.3.1
debugger-for-chrome|msj|4.7.0
gitflow|vec|1.2.1

(2 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
If you see `Your repository has no remotes configured to pull from.` then the repository is recognized.

Can you show me a screenshot of the workbench?

**Comment by achawla5000** [comment]
![screenshot](https://user-images.githubusercontent.com/11709568/41973016-b1a80632-79e1-11e8-9ee7-3f665b645a84.png)

**Comment by joaomoreno** [comment]
Can you show me the full Git output?

**Comment by achawla5000** [comment]
This is the full Git output -
`Looking for git in: C:\Program Files\Git\bin\git.exe
Using git  from C:\Program Files\Git\bin\git.exe
> git rev-parse --show-toplevel
> git config --get commit.template
Open repository: \.
> git status -z -u
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
`
I'm sorry to have bothered you, as I realize this is not a vscode issue; I also have TortoiseGit installed, and it (as well as vscode) does not recognize my git.exe path.  Again, everything was working fine until yesterday.  Also, as I mentioned, from the command line, I can use git commands to pull and push to my remote repo. I really appreciate your helping me to resolve this.

**Comment by joaomoreno** [comment]
I'm interested in why wouldn't Git report the full path of the repository in this log line:

```
Open repository: .
```

**Comment by achawla5000** [comment]
I see that the full url of the Git repository does exist in the .git/config file - 

`
[remote "origin"]
	url = https://_removed_
	fetch = +refs/heads/*:refs/remotes/origin/*
`

**Comment by joaomoreno** [comment]
Did you install Git from https://git-scm.com/?

**Comment by achawla5000** [comment]
@joaomoreno Yes.
Some more information - About 20 hours ago (long after I first observed this problem), I completely uninstalled Git, and then re-installed it.  The problem behavior I described above for vscode and TortoiseGit is the same.  Also, I then downloaded GitKraken, and this tool is able to track the changes in my git repo out of the box; I didn't do any configuration for this tool.  Additionally, one thing I notice is that when I run git-bash and try to execute any git command (e.g., git --version), the response in git-bash is nothing -
![image](https://user-images.githubusercontent.com/11709568/42038506-1edf1c04-7ab9-11e8-913c-1e31fb287d0a.png)

**Comment by joaomoreno** [comment]
@achawla5000 You're on to something. What does `which git` return?

**Comment by achawla5000** [comment]
It returns `/mingw64/bin/git`

**Comment by achawla5000** [comment]
I found out this afternoon that the cause of this problem was an update which had been pushed out by our IT Dept.  The issue has now been resolved, and everything is working perfectly.  Thank you @joaomoreno  for all your help on this!
