### ISSUE TITLE
Uninstall during extension upgrade prompts with errors

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#53050]
Testing https://github.com/Microsoft/vscode/issues/52811

- Manually install a version of an extension that is earlier than what is in the marketplace. For example, I built a version of the `vscode-docker` extension that is version `0.0.25` and installed it with `code-insiders --install-extension ...`
- Open VS Code, open extension viewlet and see that there is a prompt to upgrade to `0.0.27`. Click on the update button in the editor (not in the extension viewlet)
- Notice how in the editor view the button changes to `Uninstall`. **Click on that while installing**
- Result is a `Failed to update: 'peterjausovec.vscode-docker'.` notification
- Now, in the editor view the button is back to `Update to 0.0.27`, click on it
- Result: Nothing happens
- Click again, get another error prompt.
- Reload window, the extension is no longer installed

**Comment by sandy081** [comment]
Editor should not show Uninstall action while the extension is being installed. It should show Installing Action
