### ISSUE TITLE
Should TerminalDimensions properties be readonly?

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#53054]
#52833

You can currently write code such as

```ts
let renderer: vscode.TerminalRenderer = vscode.window.createTerminalRenderer('renderer');
...
renderer.dimensions.columns = 1;
```

This does not seem to properly trigger an update to the dimensions. I suggest making the properties of `TerminalDimensions` be readonly to prevent this

**Comment by Tyriar** [comment]
Yeah I think so, you're meant to be able to set `TerminalRenderer.dimensions` but not `TerminalRenderer.maximumDimensions`
