### ISSUE TITLE
Opening and closing find dialog in diff editor will cause the left editor to jump sometimes

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#53061]
Repro:

1. Open a diff
2. Search for something
3. F3
4. Escape
5. Repeat 3

**Comment by jaqra** [comment]
@Tyriar does it still same?

**Comment by Tyriar** [comment]
I think I might have seen it but it was hard to reproduce and isn't really that bad. I think the main issue was probably fixed a while ago.
