### ISSUE TITLE
Need admin rights to uninstall the user-level installation?

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#53060]
Testing #52824

My guest user account is not an administrator. I could install and update the user-level install, but when I uninstall it, I get a UAC prompt.

![image](https://user-images.githubusercontent.com/323878/41941783-da0f050c-7951-11e8-9510-5cd2924b23ba.png)

**Comment by roblourens** [comment]
Maybe it doesn't do that if it's signed?

**Comment by joaomoreno** [comment]
Yeah this is the signing issue, which we simply cannot fix while we're using Inno Setup #2416
