### ISSUE TITLE
Command to jump to the next/previous difference in the diff editor

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#53062]
I don't use the diff editor much, one of the first things I tried to do when I was learning it better now was to find the command to jump to the next change. I found go to next difference (F7) which is almost what I want:

![image](https://user-images.githubusercontent.com/2193314/41942041-cd7d246c-7952-11e8-920e-1e43af36e268.png)

F7 goes to the diff chunk:

![image](https://user-images.githubusercontent.com/2193314/41941983-906880b2-7952-11e8-9e78-cf6456b650cc.png)

I was expecting it to move the cursor/viewport to center around the change in the right editor.

**Comment by alexandrudima** [comment]
`F7` and `Shift+F7` navigate through the diff hunks, but they do so in an accessible way. i.e. they are the mechanism through which the diff editor is accessible.

**Comment by Tyriar** [comment]
Thanks, this is it:

```
workbench.action.compareEditor.nextChange
workbench.action.compareEditor.previousChange
```

They don't have default keybindings.

**Comment by Tyriar** [comment]
These keybindings seem to work well for me:

```
{ "key": "alt+f3",           "command": "workbench.action.editor.nextChange", "when": "editorTextFocus" },
{ "key": "shift+alt+f3",     "command": "workbench.action.editor.previousChange", "when": "editorTextFocus" },
{ "key": "alt+f3",           "command": "workbench.action.compareEditor.nextChange", "when": "isInDiffEditor" },
{ "key": "shift+alt+f3",     "command": "workbench.action.compareEditor.previousChange", "when": "isInDiffEditor" }
```

Maybe they should default to alt+f5/shift+alt+f5, so it's the same default as `workbench.action.editor.*Change` when in the diff editor?

**Comment by GandalfSaxe** [comment]
^ I would support that. I made a separate issue here, don't know if that was overkill #55481

**Comment by GandalfSaxe** [comment]
Btw I'd think that it would be more logical to use modifiers+F7 (next diff change), instead of modifiers+F3 (next search match) 🙂

**Comment by GandalfSaxe** [comment]
Or.. it's actually more similar to
`{ "key": "alt+f5",                "command": "workbench.action.editor.nextChange",`

There are so many commands related to the concept of "next change",  I'm actually a little confused myself 😅

**Comment by GandalfSaxe** [comment]
Alright I have it figured out!

These two now have the default shortcuts:
```json
  {
    "key": "alt+f5",
    "command": "workbench.action.editor.nextChange",
    "when": "editorTextFocus"
  },
  {
    "key": "shift+alt+f5",
    "command": "workbench.action.editor.previousChange",
    "when": "editorTextFocus"
  }
```

The `compareEditor.nextChange` does the _exact_ same thing as `editor.nextChange`, just for diff editor instead of normal editor. So there's absolutely no reason not to overload the `alt+f3` and `shift+alt+f3` with the same functionality. So all we have to do is add:

```json
  {
    "key": "alt+f5",
    "command": "workbench.action.compareEditor.nextChange",
    "when": "isInDiffEditor"
  },
  {
    "key": "shift+alt+f5",
    "command": "workbench.action.compareEditor.previousChange",
    "when": "isInDiffEditor"
  }
```

**Comment by GandalfSaxe** [comment]
Actually the `"when": "isInDiffEditor"` might strictly be unnecessary, but it's good to have there for clarity.

**Comment by GandalfSaxe** [comment]
I'd contribute the above myself, but I have no idea where the default keybindings are in the source 😅
