### ISSUE TITLE
JSON with comments has different coloring than JSON

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#53068]
Issue Type: <b>Bug</b>

Paste the following into a file `foo.json`:
```ts
{
    "foo": true
}
```

![json_normal](https://user-images.githubusercontent.com/19274678/41944637-b60927d0-795d-11e8-9d31-58bbfccb5522.jpg)

Change the language to "JSON with Comments":

![json_with_comments](https://user-images.githubusercontent.com/19274678/41944682-edb78064-795d-11e8-81f2-5c21c5e1bee0.jpg)

Does not reproduce in vscode non-insiders.

VS Code version: Code - Insiders 1.25.0-insider (368ab9c31b5c0930a40ab3f0e0d768ebbeeb9ef8, 2018-06-26T05:18:29.183Z)
OS version: Linux x64 4.13.0-43-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 3050)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.63GB (1.87GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
prettify-json|moh|0.0.3
typescript-javascript-grammar|ms-|0.0.42

</details>

**Comment by roblourens** [comment]
#53010
