### ISSUE TITLE
Ignore spaces in file search

### ISSUE THREAD

**Issue by biij5698** [Microsoft/vscode#5306]
在sublime中，比如在admin/adscontroller.class.php这个文件 我可以ctrl + p然后 admin adscon然后admin/adscontroller.class.php这个文件就自动出来了，但vscode做不到

**Comment by hax** [comment]
你肯定是哪里姿势不对。vscode明明是可以的。

**Comment by Lonefy** [comment]
like this:
![image](https://cloud.githubusercontent.com/assets/7921431/14554277/7a9e1ed8-031e-11e6-8067-fffc88c4cbca.png)

![image](https://cloud.githubusercontent.com/assets/7921431/14554283/8e15f03a-031e-11e6-914d-0ff85975f0c2.png)

**Comment by hax** [comment]
不要加空格就可以了。

**Comment by hax** [comment]
So as my understanding, this issue is suggesting ignore SPACE in the fuzzy search.
