### ISSUE TITLE
Menus: Consistent display for dirty files

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#53065]
Refs: #52854 

The same indication (one dot to the right) should be used across Tab and Menu Bar.

![image](https://user-images.githubusercontent.com/4033249/41943057-d434081c-7956-11e8-801a-b87816a02f40.png)

**Comment by sbatten** [comment]
do you have a custom window title format set in your setting? I'm unable to repro the extra dots you are seeing

**Comment by octref** [comment]
@sbatten My apologies, copy-pasted some settings into the VS Code in Win VM and forgot about it totally.
