### ISSUE TITLE
[Feature Request] Add "Git: Stage/Unstage chages" to the file context menu

### ISSUE THREAD

**Issue by iamshital** [Microsoft/vscode#53067]
![image](https://user-images.githubusercontent.com/7985635/41944503-f3f42848-795c-11e8-9875-929a7b1a66a2.png)

* If file is not staged, the show - Git : Stage Changes
* If file is staged, then show - Git : Unstage Changes

I know that, I can do this by going to Source View. But the purpose of the context menus is to get things done quickly.. right there!

**Comment by rishab-pdx** [comment]
@joaomoreno I would like to contribute on this issue. 
After a little digging through the extension, I intend to add a new section in package.json
```
"editor/title/context": [
        {
          "command": "git.stage",
          "group": "z_commands",
          "when": "??"
        }
      ]
```
Considering we have to show  - Stage,Unstage or Stage/Unstage as a "z_command", how can we make the ```when``` depend on a function from [CommandCenter](https://github.com/Microsoft/vscode/blob/master/extensions/git/src/commands.ts#L156) - I tried adding a function there but it does not depend on it. AFAIK, we will have to make use of existing property from ```vscode``` which tells if the file is dirty,staged or dirty staged and unstaged. I tried to dig through the code to find such property but could not find a appropriate one ? Can you point me in right direction ?
