### ISSUE TITLE
Don't let contributed keybindings override ours for showing keybinding in Quick Pick & Menu

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#53066]
1.24

- Install GitLens

![image](https://user-images.githubusercontent.com/4033249/41943845-ffaf2866-7959-11e8-856d-eb172980ab5a.png)

![image](https://user-images.githubusercontent.com/4033249/41943867-1cd4824c-795a-11e8-880f-a62fe6384f2e.png)

![image](https://user-images.githubusercontent.com/4033249/41943891-3be8a186-795a-11e8-81ae-c026604cf498.png)

**Comment by alexandrudima** [comment]
@octref I don't understand what this issue is about from the screenshots. Can you please explain?

**Comment by octref** [comment]
GitLens is doing this keybinding contribution. I don't think it should be allowed.

```
            {
                "command": "workbench.view.scm",
                "key": "ctrl+shift+g g",
                "when": "gitlens:keymap == chorded && gitlens:enabled"
            }
```

**Comment by alexandrudima** [comment]
@octref That is the sole purpose of keybindings contributions: To allow for extensions to customize default keybindings. That is how keymap extensions can work. That is how vim can work.

You can remove this keybinding in your `keybindings.json` which can overrule both core keybindings and extensions keybindings. Alternatively, you can complain to the author of the extension or you can uninstall the extension.

**Comment by octref** [comment]
@alexandrudima OK, I think I misunderstood. I originally thought keybinding contributions are only for adding keybindings to newly registered commands, not overriding existing ones.
