### ISSUE TITLE
Readonly workspaces should show errors on edits other than types

### ISSUE THREAD

**Issue by JacksonKearl** [Microsoft/vscode#53075]
Mentioned this in another comment, but readonly workspaces should show errors on deletions and cut/paste at the least, and ideally all edit commands (transpose, insert line above, join lines, etc.)

**Comment by JacksonKearl** [comment]
#52573

**Comment by isidorn** [comment]
No. This is just how read only editors behave. We do not throw errors to the users face, but instead choose to disable those actions instead.
Closing as will not fix.

If there is a particular action that you feel shuold throw an error, please file an issue to me with that exact action in mind - thanks!
