### ISSUE TITLE
Readonly filesystems should not show move file confirmation

### ISSUE THREAD

**Issue by JacksonKearl** [Microsoft/vscode#53072]
![image](https://user-images.githubusercontent.com/8586769/41945079-2522d6e6-7960-11e8-8d2a-8486a0ff4b9a.png)

Instead we can just switch the cursor to the cirlce-slash cursor that flickers around when you try to move files normally?

**Comment by JacksonKearl** [comment]
#52573

**Comment by roblourens** [comment]
@JacksonKearl please assign new issues to the test item author
