### ISSUE TITLE
Menus: Consider using a stronger font-weight for UI

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#53076]
Refs: #52854 

@bpasero @Tyriar @misolori Wondering what's your opinion? During today's testing I was staring at the menu for a few hours and I found the font too thin and lightweight.

I find increasing the `font-weight` to 500 makes it much easier to read.

For the sake of consistency, this will impact both Menu bar and the Panel Bar.

### White

`font-weight: 400`

![image](https://user-images.githubusercontent.com/4033249/41945528-8b91bb48-7962-11e8-8973-fc397bbc4db1.png)

`font-weight: 500`

![image](https://user-images.githubusercontent.com/4033249/41945619-e95a54e2-7962-11e8-8289-e6dfcd570f56.png)

### Dark

`font-weight: 400`

![image](https://user-images.githubusercontent.com/4033249/41945681-342f5148-7963-11e8-9fc9-11c54bc0ef8b.png)

`font-weight: 500`

![image](https://user-images.githubusercontent.com/4033249/41945651-093e1aaa-7963-11e8-8318-292df4e8f99c.png)

**Comment by octref** [comment]
This is the effect of both fix #53007 (make label / shortcut both 12px, currently label is 11px and shortcut 12px) and applying the 500 font-weight:

![image](https://user-images.githubusercontent.com/4033249/41945941-b45a87ba-7964-11e8-8021-d960e7da418d.png)

**Comment by Tyriar** [comment]
I think we should try align with what Windows does by default

**Comment by bpasero** [comment]
Yeah I find the menu in light theme especially hard to read. Agree, we should try to use a similar font size and weight as the default menus.

**Comment by misolori** [comment]
I also agree that matching what Windows does by default. Is there a reason why we decided to not use the default font size/weight?

**Comment by Cirieno** [comment]
Agreed.  Having the items in a menu at a font smaller than the menu itself makes the menu items harder to read (thinking of anti-aliased / Cleartyped but not hi-def screens)

![vscode_issues](https://user-images.githubusercontent.com/37182505/42378212-662bcee8-811e-11e8-911d-ba8a099171b7.png)
.

**Comment by sbatten** [comment]
font sizing was changed via #54695, I think this solves the issue at heart here and font weight can remain the same. please re-open and provide feedback if you feel the weight is still an issue.
