### ISSUE TITLE
PHP Syntax Highlighting changed for Dark+ ?!

### ISSUE THREAD

**Issue by Morgy93** [Microsoft/vscode#5307]
- VSCode Version: 1.0
- OS Version: 10586.218

![code](https://cloud.githubusercontent.com/assets/7961978/14553493/32d164ca-02e7-11e6-97f5-0d6d074829c4.PNG)

These were red before - I didn't see the change in the changelog so far?!
Intentionally or unintentionally?
(Red was way better before btw., because now it doesn't differ from html tags)

**Comment by aeschli** [comment]
Yes, that was intended. It used to be red bold and was IMO not very pretty.
Now we use the default color for html tags.
