### ISSUE TITLE
Suggestion: Add label to readonly workspace folders

### ISSUE THREAD

**Issue by JacksonKearl** [Microsoft/vscode#53074]
![image](https://user-images.githubusercontent.com/8586769/41945629-f35e7da6-7962-11e8-93de-b10a8ff96962.png)
Something like the above could help make it clear where the readonly restriction is coming from.

**Comment by JacksonKearl** [comment]
#52573

**Comment by isidorn** [comment]
The notion of readonlies in the ux side is file based, not workspace based. So in theory you could have some readonly files in a workspace and some which are writable.
Due to that I prefer this solution https://github.com/Microsoft/vscode/issues/53022
