### ISSUE TITLE
Single quotation marks or double quotation marks error completion

### ISSUE THREAD

**Issue by beroft** [Microsoft/vscode#53081]
Issue Type: <b>Bug</b>
Hi, vscode teams.
When I enter Chinese in single or double quotation marks and delete them, the quotation marks will be completed automatically, This could be a BUG because I didn't find it in the stable version.
Here's my video.
https://photos.app.goo.gl/1LoXwb6VodB5Kh1y6

VS Code version: Code - Insiders 1.25.0-insider (923e9ccb3fc44bfaaf4b4049015c84e42bc40f95, 2018-06-26T13:00:22.932Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_614550|
|Screen Reader|no|
|VM|29%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
code-settings-sync|Sha|2.9.2
project-manager|ale|0.25.2
All-Autocomplete|Ati|0.0.16
bracket-pair-colorizer|Coe|1.0.58
vscode-eslint|dba|1.4.12
xml|Dot|2.3.1
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.33
php-debug|fel|1.12.3
php-intellisense|fel|2.3.3
php-pack|fel|1.0.1
auto-close-tag|for|0.5.6
vscode-phpfmt|kok|1.0.30
Angular-BeastCode|Mik|6.0.19
vscode-language-pack-zh-hans|MS-|1.25.0
sublime-keybindings|ms-|4.0.0
php-docblocker|nei|1.6.0
material-icon-theme|PKi|3.5.0
copy-copy-paste|roc|0.0.5
html-css-class-completion|Zig|1.17.1

(1 theme extensions excluded)

</details>

**Comment by zelljhos** [comment]
Hello, i solved this issue with this extension: https://marketplace.visualstudio.com/items?itemName=konstantin.wrapSelection

i hope this feature could be by default in coming versions.

Thanks.
