### ISSUE TITLE
outline for C++/C: the Follow Cursor fails

### ISSUE THREAD

**Issue by chongchai** [Microsoft/vscode#53085]
- VSCode Version: 1.24.1
- OS Version: windows 7
- Extension: C/C++ 0.17.4

Steps to Reproduce:

1.  open a c/c++ project and show the outline view
2.  select 'Follow Cursor'. But when I change the selection in the file, the outline selected symbol will not change.

ps: this feature is ok for typescript.

**Comment by jrieken** [comment]
The extension needs to adopt the new API first
