### ISSUE TITLE
Hide settings editor toc when editor is too narrow

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#53083]
Issue Type: <b>Bug</b>

At small widths, the settings editor can looks quite busy/cramped. 

 
![screen shot 2018-06-26 at 6 21 10 pm](https://user-images.githubusercontent.com/12821956/41947675-cd87c3e8-796d-11e8-853f-07637ee14041.png)

I think we should consider hiding the TOC when the editor is under a certain width

VS Code version: code-oss-dev 1.25.0 (Commit unknown, Date unknown)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.14GB free)|
|Process Argv|/Users/matb/projects/vscode/.build/electron/Code - OSS.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|17%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cat-coding|ms-|0.0.1

</details>

**Comment by roblourens** [comment]
Set a minimum width of 600px, feels about right.
