### ISSUE TITLE
Logpoint UI is not invoke after set a logpoint

### ISSUE THREAD

**Issue by yaohaizh** [Microsoft/vscode#53089]
- VSCode Version: 1.24.0
- OS Version: Windows/Linux

Steps to Reproduce:

1. Set a logpoint on the language support logpoint 
2. Add log message on the UI, close the UI
3.  The editor sidebar indicates this is a logpiont
4. Select the same logpoint, the UI is still pop up the "Expression" field not log point UI.

Expected: 
Should change the UI for logpoint

Does this issue occur when all extensions are disabled?: I tested in on Java debugger that plan to support logpoint, it should be UI side issue.

**Comment by isidorn** [comment]
@yaohaizh please try this out in tomorrow vscode insiders and let us know if the issue is fixed for you.
If not, please attach a picture clariyfing your problem

**Comment by isidorn** [comment]
@yaohaizh thanks, adding verified label
