### ISSUE TITLE
切换成中文版后，不支持英文命令了。

### ISSUE THREAD

**Issue by love19862003** [Microsoft/vscode#5308]
- VSCode Version:1.0
- OS Version:

Steps to Reproduce:

1. 中文版安装
2. 所有命令都变中文了。 不能使用英文命令。除非切换成英文版本。
希望能中英文命令都兼容

**Comment by egamma** [comment]
Hi, the development team doesn't speak Chinese, sorry. Can you please find someone that helps you translate the issue to English.

**Comment by Tyriar** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/4679

**Comment by love19862003** [comment]
I am used  visual studio code with  language  "zh-cn",   but i can not used command with english .   
input chinese is vary slowly . 
i want input command with english and chinese.


2016-04-15 

love19862003 



发件人：Erich Gamma <notifications@github.com>
发送时间：2016-04-15 14:57
主题：Re: [Microsoft/vscode] 切换成中文版后，不支持英文命令了。 (#5308)
收件人："Microsoft/vscode"<vscode@noreply.github.com>
抄送："fanny.wu"<love19862003@163.com>

Hi, the development team doesn't speak Chinese, sorry. Can you please find someone that helps you translate the issue to English.
