### ISSUE TITLE
progress bar for tasks

### ISSUE THREAD

**Issue by graph** [Microsoft/vscode#53086]
builders such as ninja & make can output progress information. It would be nice to have a progress bar in vs code.

**Comment by TomSputz** [comment]
It might make sense for this to be a percentage next to the build icon we already have in the status bar, though I fear there isn't really any place for an actual bar that wouldn't clutter the interface

**Comment by graph** [comment]
also OS's support progress bar for the OS panel that overlays the app. That's a good place to add an indicator too. Maybe the addition of a progressMatcher in tasks.json will be good too.

**Comment by connorshea** [comment]
I think this is the same as #17607?

**Comment by dbaeumer** [comment]
@connorshea agree. Thanks. Closing as dup of #17607
