### ISSUE TITLE
Documentation tweak for registerWebviewPanelSerializer

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#53082]
Testing #52849

Currently says 

```
Extensions that support reviving should have an `"onWebviewPanel:viewType"` activation method
```
I think it would be clearer if "method" was changed to "event" to align with the property name in `package.json`

**Comment by RMacfarlane** [comment]
One other documentation suggestion:
I was initially confused about what I actually needed to do in `deserializeWebviewPanel`/what properties of the panel object needed to be revived. It might be good to call out that setting `webview.html` is one of these responsibilities.

**Comment by JacksonKearl** [comment]
Agreed on more documentation about what these methods should do. I will post my implementation to show what my reading of the docs brought me to.
