### ISSUE TITLE
Completion in a defined List

### ISSUE THREAD

**Issue by zunlihu** [Microsoft/vscode#53097]
Hi,
I plan to design an extension, in which the completion items can display in a defined order. For  example, the original list is in alphabetic order {a;b;c;d}, and I want it displays in {d;a;b;c}.

The language I used is typescript, is there a way to achieve such a function?
Thanks!

**Comment by jrieken** [comment]
Yes, use `CompletionItem#sortText`

**Comment by zunlihu** [comment]
I just can know that sortText will compare with other items. But I am still confused about how sortText works in ordering the completionitems.  
Can you tell me how it works taking {a;b;c;d} for example?
