### ISSUE TITLE
Provide intelligence in JSDOC import statements

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#53093]
With TS 2.9 I now can write

```
/**
 * @typedef {import("./dir/file1").exportedType} typeAlias
 */
```

We should provide support for completing the file paths parameters for `import` the same way we do for `require`.

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/Microsoft/TypeScript/issues/25275 to track this upstream
