### ISSUE TITLE
VSCode switches between windows arbitrarily

### ISSUE THREAD

**Issue by bereal** [Microsoft/vscode#53092]
Issue Type: <b>Bug</b>

I am running VSCode in OSX, after latest update it began to switch between windows arbitrarily. To reproduce:
- open vscode full-screen
- open two windows, switch to the second one
- cmd-tab away from VSCode
- cmd-tab back

it will show the first workspace, I'll have to switch again.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
OS version: Darwin x64 15.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_5756285|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
postgresql|JPT|0.0.2
solidity|Jua|0.0.43
cql|Law|0.8.7
vscode-docker|Pet|0.0.27
vscode-database|baj|1.5.1
django-html|bib|1.2.0
django-snippets|bib|1.1.0
vscode-eslint|dba|1.4.12
jupyter|don|1.1.4
python-extension-pack|don|1.0.1
gitlens|eam|8.4.1
reasonml|fre|1.0.37
vscode-emacs|hir|0.1.1
vscode-emacs-friendly|lfs|0.8.2
MagicPython|mag|1.0.12
terraform|mau|1.2.0
python|ms-|2018.6.0
Go|ms-|0.6.83
appidocsnippets|mya|0.1.17
vscode-code-outline|pat|0.2.1
vscode-icons|rob|7.24.0
vscode-react-native|vsm|0.6.11
HCL|who|0.0.5
jinja|who|0.0.8
markdown-all-in-one|yzh|1.5.0

(1 theme extensions excluded)

</details>

**Comment by bereal** [comment]
Update: I discovered that it has to do with that only one of the windows was full-screen.

**Comment by roblourens** [comment]
So you have one fullscreen and one non-fullscreen window? What are the "first" and "second" in your steps. Is this just the way MacOS handles fullscreen windows and cmd+tab between apps? I think it typically just focuses the window on the current screen, when you cmd+tab to an app.
