### ISSUE TITLE
Can I change font-family only for comments?

### ISSUE THREAD

**Issue by DevotionGeo** [Microsoft/vscode#53095]
I'm asking it here, because this kind of questions are already disallowed at StackOverflow. 

There is the setting `editor.fontFamily`, but it changes font-family for the whole editor. I'm looking for something (setting/extension) which changes font-family only for comments in my code. I'd love to read comments in something like [Purisa](https://graphicdesign.stackexchange.com/posts/13471/revisions) or other handwritten fonts.
There are also now a days applications which can generate fonts handwritten by you yourself, and it makes a lot of sense to use that kind of font for comments.

**Comment by TomSputz** [comment]
As far as I can tell this is not yet possible - The feature is requested in issue #36512, and on the milestone, so it should hopefully not be too long :)

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/36512 is right, thanks @TomSputz
