### ISSUE TITLE
Remove the spaces after opening and before closing non empty curly brackets

### ISSUE THREAD

**Issue by scharinger** [Microsoft/vscode#53096]
I wish there was an added setting for formatting the JavaScript. Which _removes the spaces after opening and before closing non empty *curly* brackets_.
It is basically the same rule as `insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets` but for curly brackets instead of square brackets.

Thanks!

**Comment by mjbvz** [comment]
Try   `"javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": false`
