### ISSUE TITLE
code comment choose

### ISSUE THREAD

**Issue by yakiler** [Microsoft/vscode#53098]
How to modify the type of comment used by "Ctrl + /" ? Is it a block comment or a line comment?

I really need your help and thanks

supplement:
Sorry,In fact, I am concerned about how to specify the type of annotation used in different types of files? Is it /// or /** */ or \<\!-- \--\>

**Comment by TomSputz** [comment]
`Ctrl`+`/` will toggle a line comment at your cursor position, `Shift`+`Alt`+`A` will toggle a block comment, these can be remapped by putting
```js
[
    {
        "key": "shift+alt+a",
        "command": "editor.action.blockComment",
        "when": "editorTextFocus && !editorReadonly"
    },
    {
        "key": "ctrl+oem_2",
        "command": "editor.action.commentLine",
        "when": "editorTextFocus && !editorReadonly"
    },
]
```
in your keybindings.json (`F1` > Preferences: Open Keyboard Shortcuts File), and editing the 'key' field

**Comment by roblourens** [comment]
Are you using an extension for smarty? That will be up to the extension.
