### ISSUE TITLE
Hint on character only has two dots

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#53094]
Issue Type: <b>Bug</b>

Testing #52218

On first character in document on two dots are shown:
![image](https://user-images.githubusercontent.com/9205389/41959005-0d7747d4-79ec-11e8-8bec-6ea7884a340b.png)

VS Code version: Code - Insiders 1.25.0-insider (f2fa6bea46bde9856e6a593e4d4c5af2b303ac66, 2018-06-27T05:11:02.122Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (1.15GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron --extensions-dir /Users/chrmarti/Development/repos/tmp/ext --user-data-dir /Users/chrmarti/Development/repos/tmp/user|
|Screen Reader|no|
|VM|20%|

</details>Extensions: none

**Comment by chrmarti** [comment]
Not just on the first character:
![image](https://user-images.githubusercontent.com/9205389/41959240-ae17e6ee-79ec-11e8-9d1a-b9c83a857ea1.png)

**Comment by jrieken** [comment]
@chrmarti Where does that marker come from?

**Comment by chrmarti** [comment]
@jrieken I added it through a test extension.

**Comment by jrieken** [comment]
So, the diagnostic is just for that one character, right?

**Comment by chrmarti** [comment]
`Range(1, 1, 2, 1)` and `Range(1, 1, 1, 2)` both show two dots, `Range(1, 1, 1, 3)` shows three.
