### ISSUE TITLE
[sass] Hover Feature not work correctly in SCSS Rule with Parent Selectors '&'

### ISSUE THREAD

**Issue by kaiye** [Microsoft/vscode#531]
![sass-bug](https://cloud.githubusercontent.com/assets/344283/11360340/8c5b84b0-92be-11e5-922c-d5c0567a2733.png)

Remind the cursor pointer in the screenshot above, it should be `<element class="meizu-header-logo-img" ...` which displays  `<undefined-logo-img ...` now.

**Comment by aeschli** [comment]
![image](https://user-images.githubusercontent.com/6461412/33479477-8edac0e2-d68d-11e7-9c2e-01a16229a75b.png)

This git fixed in the meantime.
