### ISSUE TITLE
Tab completion (Insiders)

### ISSUE THREAD

**Issue by bsvipas** [Microsoft/vscode#53106]
- VSCode Version: 1.25.0 (Insiders)
- OS Version: macOS

Steps to Reproduce:

1. Go to the settings
2. Press `ctrl + space` to trigger IntelliSense
3. Use tab to complete properties for e.g. `"workbench.fontAliasing": PRESS HERE TO AUTOCOMPLETE,`
4. And you will see it will not complete, but instead it will add tab :smile:

This problem doesn't exist in Stable release :)

**Comment by bsvipas** [comment]
Seems it doesn't complete at the first time, but after clicking more than one time it will complete. Very strange...

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/52999
