### ISSUE TITLE
Not able to restart debugger

### ISSUE THREAD

**Issue by lior8813** [Microsoft/vscode#53102]
Issue Type: <b>Bug</b>

I work with rdebug, and if I start the debugger process (in my case "Listen for rdebug-ide" and receive a ECONNREFUSED error, I have to restart VSC before trying to run the debugger again.

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:32:53.389Z)

**Comment by weinand** [comment]
Please file this issue against the rdebug extension.
