### ISSUE TITLE
Portable mode: on Windows and Linux, move the data folder inside the application's folder

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#53108]
Testing #52823

It would make a lot more sense (also for the future), that the `data` folder is distribution name agnostic (simply called `data`) and that it is placed inside the folder, right next to the `.exe` and other folders.

**Comment by joaomoreno** [comment]
@alexandrudima Can you give these builds a quick smoke test?

- [Windows 64](https://az764295.vo.msecnd.net/insider/e087b31199659c22c58c0ced4641d1b167ca62e7/VSCode-win32-x64-1.25.0-insider.zip)
- [Linux 64](https://az764295.vo.msecnd.net/insider/e087b31199659c22c58c0ced4641d1b167ca62e7/code-insider-1.25.0-1530107296_amd64.tar.gz)
- [macOS](https://az764295.vo.msecnd.net/insider/e087b31199659c22c58c0ced4641d1b167ca62e7/VSCode-darwin-insider.zip)

**Comment by joaomoreno** [comment]
Updated docs:

https://github.com/Microsoft/vscode-docs/commit/21ea4c679a92f7dfd492ce0c21103035011f7b8e

**Comment by alexandrudima** [comment]
@joaomoreno 

:+1: all works nice!

I think it would help to document this command line in the `portable.md`:

```
xattr -d com.apple.quarantine Visual\ Studio\ Code\ -\ Insiders.app/
```

**Comment by joaomoreno** [comment]
Yup I will put that there. I also have this https://github.com/Microsoft/vscode/issues/52224
