### ISSUE TITLE
Recent ferw updates impacting common functionality

### ISSUE THREAD

**Issue by danieltaylor1** [Microsoft/vscode#53105]
- VSCode Version:
1.24.1 / Shell 1.7.12 x64

- OS Version:
Win10 / WIn10 insider, WinServer2012R2 x64

Steps to Reproduce:

1. Launch VSCode
2. Launch a new PS file (do not save it)
3.  Example: Type any code. Try to run any line of code - F1 (show all commands)-F5 or F8 accelerator options no longer work as before. Right Click to Run , is no longer available.

Only after you save the file in the editor, do these things return. Prior versions (x86/x64) do/did not suffer from this.

I regularly run code in the VSC editor that I do not save (throw away stuff), as I did in the ISE or console hosts. 

Even after saving the ps1, the F1(show all commands)-F5-F8 options are not working. Right click F8 does, 
I have a fully customize VSCode user settings, the auto starts PS console and integrated console.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

It's like all previous default keyboard are no longer working at all, though they show as mapped in the file, with nothing in the 'When' column.

I just manually review 10 different station with different versions of VSCode, and half of them are pristine installs. same issue, Stuff is no longer working, console will not accept input unless the inset key is pressed and the file is saved.

**Comment by roblourens** [comment]
Are these commands from the powershell extension? Can you file an issue on the powershell repo so they can investigate? https://github.com/PowerShell/vscode-powershell

**Comment by danieltaylor1** [comment]
Nope.

With or without extension enabled, or even installed at all,  this happens.

Will do.


Thank you in advance.

͡° ͜ʖ ͡°

v/r

Daniel L. Taylor , Capt (USA/USAR)
Secure Enterprise Deployment Lifecycle (SEDL) Principal Architect
SSCP, CISSP, CISA, CISM, CEH, NSA(IAM), MCSA:Security, MCSE:Security
Security+, CIW Security Analyst, TruSecure (ICSA), CCSPA, MCTS:Forefront, MCTS:ISA Server
MOUS/expert, MCP+I, MCP+Site Building, MCDST, MCTS:Vista:W2K8, MCITP:EST, MCT
MCAD, MCSD, MCSD.NET, MCDBA, MSF Practitioner, ITILv3 (ITSM)
MCSE+Internet, MCSA:Messaging, MCSE:Messaging, MCITP:SA, MCITP:EA
Linux+, CCSA/CCSE+ (NG AI \ NGX), CCMSE (NGX \ NGX+VSX)

**Comment by roblourens** [comment]
Ok can you explain what happens when you press F5 or F8, and what is supposed to happen? I'm pretty sure you're looking for the commands from the PS extension.

**Comment by danieltaylor1** [comment]
Follow-up.

I finally discover the root cause of the issue.

I have been running VSCode on Win 10 since its release and thus user the 32bit version until recently. I’ve also have PSCore on the system. These coexisted fine without issues.
VScode was using the PSWin environment using the editor, and either ‘PowerShell Integrated Console – Visual Studio Code Host’ and / or the Console host, which I often run side by side.

As of the last VSCode update, I switched and installed the x64 version and continued as normal, but had not did any recent coding on this client in VSCode until recently. I still spend most of my time in the ISE and Sapien’s PS Studio (all my GUI work/projects are here).

Upon switching back to VSCode for other reason, the items below occurred.

The root cause, is that the VSCode x64 auto-configured the ConsoleHost to default to the PSCore installation and not the default Windows ConsoleHost. This was unexpected.

So, all things stopped working because PSCore is a vanilla install and not customize and my PSWin ConsoleHost is and of course all that Is possible with PSWin (ISE / Console) is not possible with PSCore.

So, this was not the extensions, but the side by side install of PSCore with VSCode which now defaults to PSCore  (if installed) for ConsoleHost terminal and not PSWin. Which kind of flies in the face of PS side by side installation.

Uninstalling PSCore, fixed all the issues, thus allowing VSCode x64 to only use PSWin, fixed I’ve raised here.

The interesting part is, I never changed my default terminal (powershell.exe) in my user settings (which I’ve always understood that user settings would take precedence). So, I would not have thought, that setting was being ignored after switching to VSC x64.




From: Daniel Taylor
Sent: Wednesday, 27 June, 2018 14:40
To: Microsoft/vscode <reply@reply.github.com>; Microsoft/vscode <vscode@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [Microsoft/vscode] Recent ferw updates impacting common functionality (#53105)

Nope.

With or without extension enabled, or even installed at all,  this happens.

Will do.


Thank you in advance.

͡° ͜ʖ ͡°

v/r

Daniel L. Taylor , Capt (USA/USAR)
Secure Enterprise Deployment Lifecycle (SEDL) Principal Architect
SSCP, CISSP, CISA, CISM, CEH, NSA(IAM), MCSA:Security, MCSE:Security
Security+, CIW Security Analyst, TruSecure (ICSA), CCSPA, MCTS:Forefront, MCTS:ISA Server
MOUS/expert, MCP+I, MCP+Site Building, MCDST, MCTS:Vista:W2K8, MCITP:EST, MCT
MCAD, MCSD, MCSD.NET, MCDBA, MSF Practitioner, ITILv3 (ITSM)
MCSE+Internet, MCSA:Messaging, MCSE:Messaging, MCITP:SA, MCITP:EA
Linux+, CCSA/CCSE+ (NG AI \ NGX), CCMSE (NGX \ NGX+VSX)

**Comment by roblourens** [comment]
FYI @Tyriar ^

**Comment by Tyriar** [comment]
@danieltaylor1 can you please clarify some things?

- What's your default terminal path set to in your settings.json? (that you didn't change)
- What is PSCore and where is it located?
- What is PSWin and where is it located?

/cc @tylerl0706

**Comment by danieltaylor1** [comment]
CDIL...

**Comment by tylerl0706** [comment]
Hey @danieltaylor1, I work on the PowerShell extension for VSCode.

When you say that it's defaulting to PSCore, is it the PowerShell Integrated Console that's defaulting to PSCore?

When you open a PowerShell file in VSCode and the PowerShell extension starts (and you see the PowerShell Integrated Console pop up) what green number do you see at the bottom right of vscode:
![](https://user-images.githubusercontent.com/5177512/42726015-cdb17df6-874a-11e8-809b-d2b9b4d7e729.png)
