### ISSUE TITLE
"editorUnnecessaryCode.border" not working

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#53103]
Issue Type: <b>Bug</b>

Testing #52218 

It doesn't show as border:
![image](https://user-images.githubusercontent.com/9205389/41962667-e19462fa-79f5-11e8-9676-204ac6792d07.png)

In other cases it doesn't show at all:
![image](https://user-images.githubusercontent.com/9205389/41962844-5d2d9404-79f6-11e8-9526-6522d81ee541.png)

VS Code version: Code - Insiders 1.25.0-insider (f2fa6bea46bde9856e6a593e4d4c5af2b303ac66, 2018-06-27T05:11:02.122Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.73GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron --extensions-dir /Users/chrmarti/Development/repos/tmp/ext --user-data-dir /Users/chrmarti/Development/repos/tmp/user|
|Screen Reader|no|
|VM|20%|

</details>Extensions: none

**Comment by mjbvz** [comment]
In the first example, I believe it is showing as expected. The green dashes are the border

In the second example, we don't show the additional border because the squiggly already exists. We only show `editorUnnecessaryCode.border` if there no other marker
