### ISSUE TITLE
Settings editor looks cramped

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#53111]
Testing #52859

![image](https://user-images.githubusercontent.com/10746682/41965485-e9a77cf0-79fc-11e8-948e-8f37240e8c28.png)

Content should proportionally expand with the size of the editor, otherwise lot of space on the left and right seems unused

**Comment by roblourens** [comment]
On the other hand, people don't like to read a line of text that goes across a very wide screen. That's the main reason for the max-width

**Comment by sandy081** [comment]
@

**Comment by roblourens** [comment]
I think extremely long lines and text boxes don't look better than empty space. 

Thoughts @misolori?

**Comment by roblourens** [comment]
![image](https://user-images.githubusercontent.com/323878/42008499-b750d8b2-7a3a-11e8-82e9-e370fa9aab11.png)

**Comment by misolori** [comment]
I think that we can strike a balance of using the space adequately while still remaining readable. I would also argue that reading code is a very different task than reading description text for a setting, so I wouldn't remove the max-width.

I'd suggest that for larger screens we increase the max-width to `1100px` and increase the `margin-right` of the toc to `60px`:

![image](https://user-images.githubusercontent.com/35271042/42010540-ff8b6eea-7a43-11e8-8649-bbbaa363932a.png)

**Comment by sandy081** [comment]
Yes, we do not need to make lines and input boxes long, we can give space between TOC and Contents. Above screen shot from @misolori looks perfect to me.

**Comment by roblourens** [comment]
Lots of layout changes have happened, hope this is better now.
