### ISSUE TITLE
Edit in Settings.json link is shown in between results

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#53115]
Testing #52859

![image](https://user-images.githubusercontent.com/10746682/41965771-ab8356a0-79fd-11e8-8590-3be116b9e1dd.png)

**Comment by sandy081** [comment]
At first I thought that the link is global edit action but later I realised that it is an action for `Lcov:Path` setting. It looks disconnected to me due to the space between the setting and the action. May be it should be closer?

**Comment by eamodio** [comment]
I looks like this is now on a dropdown menu under the cog. Personally I liked the old style better -- it was more discoverable

**Comment by roblourens** [comment]
It is also still on each individual setting. But we moved the global action since we get a lot of feedback that the header looks too busy or crowded.

**Comment by eamodio** [comment]
Yeah, I agree with the too crowded, but imo that is much more do to spacing/padding and the preview text that will ultimately be removed.

**Comment by roblourens** [comment]
Hopefully this is ok now, there have been padding changes since this was filed.
