### ISSUE TITLE
--locale=zh-Hans does not prompt for language pack install

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#53126]
Testing #52960

- VSCode Version: 1.25 build for testing
- OS Version: High Sierra

Starting with `--locale=zh-Hans` does not prompt for the language pack install.

**Comment by chrmarti** [comment]
Same for `zh-Hant`.

**Comment by sandy081** [comment]
Only zh-cn and zh-tw are supported. Its an issue with the test case
