### ISSUE TITLE
Rename Features group to Views?

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#53129]
Testing #52859

I see that Features group is showing the Views entries. Why not call it Views to be in sync with how we show them already in the product? 

Also call File Explorer as Explorer?

![image](https://user-images.githubusercontent.com/10746682/41969261-1c1345fc-7a07-11e8-8c3e-a585442fcb87.png)

**Comment by roblourens** [comment]
I don't want to tie it to that menu because it's missing half of what's in that menu. I think those things make sense together in a menubar, "here's how to find parts of the UI or change the way it looks" but not in settings.
