### ISSUE TITLE
Enter on Group header entry in TOC should expand or collapse

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#53125]
Testing #52859

When you press Enter / Click on a group header entry, it should expand/collapse.
When you click on an entry in the group, it should highlight the entry in the main content by preserving focus.
When you press Enter on an entry in the group, it should highlight and focus the entry in the main content.

This is similar to how our file explorer works and is user friendly

**Comment by roblourens** [comment]
I think Enter should always send focus to the tree. Users can use arrow keys to expand/collapse. I think that's more typical because 'enter' doesn't work that way on Mac for any tree that I see.

**Comment by roblourens** [comment]
I implemented what I described, let me know what you think

**Comment by sandy081** [comment]
Liked it.
