### ISSUE TITLE
Bogus Modified in User label

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#53127]
Testing #52859

I see bogus Modified in User label on a setting, even though it is not

![image](https://user-images.githubusercontent.com/10746682/41968957-3ecd2924-7a06-11e8-867e-53f0ac45e28c.png)

**Comment by roblourens** [comment]
Are you sure? Is there nothing different about that setting?

**Comment by sandy081** [comment]
Yes, I do not see it in my user settings file

**Comment by sandy081** [comment]
I no longer see it now. May be I would have had it my user settings.
