### ISSUE TITLE
Sync navigation between TOC and contents

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#53122]
Testing #52859

While I navigate in TOC using up and down arrow, I would expect to see the contents synced.

**Comment by roblourens** [comment]
Tweaked this, try it tomorrow and let me know if it's what you expect.

**Comment by sandy081** [comment]
@roblourens Good that it is in Sync while navigating from tree. But why does up and down arrow is selecting the node now ? This is different from all our trees. 

Up and down arrow should focus the node and contents get synced would be nice and consistent

**Comment by sandy081** [comment]
Reopening it continue the discussion

**Comment by roblourens** [comment]
I'm not a fan of the focus+select paradigm in most trees, and I don't really know what it would mean here. Suppose I use arrow keys to focus some TOC node, and some other TOC node is selected. The focused TOC node is selected in the settings tree, but what does the selected TOC node mean? 

I think it makes sense in the explorer but not here. Search works similarly to the settings trees (focus and select are always the same)

**Comment by sandy081** [comment]
I see.. its a valid point.
