### ISSUE TITLE
Word completion should include words from other opened files

### ISSUE THREAD

**Issue by worldcoding** [microsoft/vscode#5312]
- VSCode Version:1.0.0
- OS Version:win7

For example, in a document has been entered in the string: helloworld, then enter the letter h for selection when you choose b helloworld file.

**Comment by egamma** [comment]
Hi, the development team doesn't speak Chinese, sorry. Can you please find someone that helps you translate the issue to English.

**Comment by egamma** [comment]
We call this word completion and it should be enabled by default. In which language do you not see word completion as expected. 

![image](https://cloud.githubusercontent.com/assets/172399/14556014/365cbd74-02f6-11e6-9109-900f72a55f96.png)

**Comment by chwentao** [comment]
my mean is in other file ,not in same file.

**Comment by chwentao** [comment]
![qq 20160415165035](https://cloud.githubusercontent.com/assets/13378254/14556323/3fd76654-032a-11e6-8549-c43c06c7e91e.png)

**Comment by egamma** [comment]
@chwentao thanks for the clarification.

**Comment by dannyZhou** [comment]
Sorry about that in PHP I have some problems. 

ENV:
- File Type: *.php
- OS: `ubuntu 14.04`  `3.13.0-32-generic`  `x86_64` 
- Code Version: 
 - Version 1.3.1
 - Commit e6b4afa53e9c0f54edef1673de9001e9f0f547ae
 - Date 2016-07-12T13:28:46.761Z
 - Shell 0.37.6
 - Renderer 49.0.2623.75
 - Node 5.10.0


> We call this word completion and it should be enabled by default. In which language do you not see word completion as expected.

**Comment by rnemec** [comment]
I am surprised why nobody else is "+1"-ing this issue. The word completion using words from any opened buffer is extremely useful and pretty common these days. I hope this would make it into one of the near future releases...

**Comment by jilustrisimo** [comment]
Will this ever be implemented? It's pretty standard for most editors.  It's my main gripe with VSCode which is upsetting because it's my preferred editor in any other aspect.

**Comment by hjbolide** [comment]
+1
The lacking of this feature is a big factor why i still hang up on emacs.

**Comment by atishay** [comment]
Can you all try this out: https://marketplace.visualstudio.com/items?itemName=Atishay-Jain.All-Autocomplete. Would  love to get some feedback.

**Comment by rnemec** [comment]
@atishay , failed to install, tried 3 times, no time on my side to investigate :-(

**Comment by jilustrisimo** [comment]
@atishay thanks for the plugin.  It seems to work for me.  It may be causing a problem with the Rubocop ext. I have (ruby-rubocop 0.3.5) but I haven't investigated to see if the problem may be from somewhere else.  Either way, thank you for making this!

**Comment by lalosh** [comment]
It'll be really appreciated if you embed this feature inside the editor.
I don't know why 'All Autocomplete' ext didn't work for me!

**Comment by cntech** [comment]
+1
Recently I switched from Atom to VSCode and it is one of 2 things I miss in VSCode.

**Comment by tomkra** [comment]
@jrieken Any progress on this feature? Thank you

**Comment by kanlukasz** [comment]
It's very important option and very useful
Plugin by @atishay unfortunately not working properly --> https://github.com/atishay/vscode-allautocomplete/issues/51

**Comment by chen3feng** [comment]
+1

**Comment by jrieken** [comment]
Tomorrows [VS Code Insiders](https://code.visualstudio.com/insiders/) will use all documents of the current language when computing word based completions, e.g when typing in a CPP file, words from all open CPP files will be suggested

**Comment by usernamehw** [comment]
@jrieken Is it possible to add a setting to include words from all opened documents regardless of language?

**Comment by jrieken** [comment]
Sure, sure. Accepting PRs: https://github.com/microsoft/vscode/blob/5facf746acd67947f35565ef9c012121047c4cf8/src/vs/editor/common/services/editorWorkerServiceImpl.ts#L163

**Comment by jrieken** [comment]
To verify

* make sure there a new setting `editor.wordBasedSuggestionsMode` 
* make sure the setting allow three modes: word based suggestion from the current document, from matching documents (e.g same language), and from all documents
* note that a document must be truly open for it to be included, e.g a tab that's restored after reload isn't considered

**Comment by danielo515** [comment]
Is this tied to the Javascript and typescript extension? Because I am not getting word based suggestions, not even for the current file.
