### ISSUE TITLE
Remove TOC search behavior modes besides 'filter'

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#53120]
Testing #52859

Settings main content jump to left while searching as the TOC are hidden. IMO the better experience would be show the TOC.

![image](https://user-images.githubusercontent.com/10746682/41966973-cf6738a4-7a00-11e8-9adc-201f7d2729c4.png)

In the beginning, I would not have a setting to configure TOC unless somebody wants.

I see that currently TOCs are not updated with the setting. Not having a setting also fixes it.

**Comment by sandy081** [comment]
@roblourens We should also provide a smart default. And I would rather do the other way around by providing one option and expand it. It is difficult to remove any functionality we add in future.

**Comment by roblourens** [comment]
I think we are trying to figure out which option is the smart default. I prefer hiding the TOC which is why that's currently the default. Also since this is still a "preview" feature, I don't mind arbitrarily adding or removing functionality. I wouldn't do that once it's stable.

**Comment by sandy081** [comment]
@roblourens If it is for experimenting how about use the setting by not registering it? 

Not sure how you are evaluating to finalise on default behaviour, my preference would be have the TOC always and filtered. With this, UI looks smooth and consistent.

**Comment by roblourens** [comment]
@kieferrm Any thoughts on whether the setting that controls TOC behavior should be hidden, and whether we should have a different default besides "hide"?

**Comment by roblourens** [comment]
'filter' is now the default, I'll use this issue to track removing other modes.

**Comment by roblourens** [comment]
Keeping 'hide' and 'filter'.
