### ISSUE TITLE
Settings Editor is not getting focused when I click on open space

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#53124]
Testing #52859

- Open Settings Editor in one editor group
- Open another file in another editor group
- Click in open space of settings editor

🐛 Its not getting focused as a result no title bar actions are enabled

**Comment by roblourens** [comment]
Huh, I don't really know how to fix this. The editor doesn't lose focus when I click on a non-focusable element, but it doesn't really make sense to make that background of the settings editor focusable. And the way it's set up right now, I actually don't control that element anyway.

**Comment by roblourens** [comment]
I gave the background `tabindex=-1`, hopefully that's legal
