### ISSUE TITLE
Prompt for language pack only in English

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#53130]
Testing #52960

- VSCode Version: 1.25 build for testing
- OS Version: High Sierra

The test item mentions it should also be in the OS language. That does not seem to be the case.

![image](https://user-images.githubusercontent.com/9205389/41969365-7a630098-7a07-11e8-8cac-26f51ef06e4a.png)

**Comment by ramya-rao-a** [comment]
This is because the language pack for French doesn't have the required strings.
For that matter, almost none of the core language packs have the required strings.

@danyeh, 
The required translations are in the built-in language support but not in the language pack extensions.

https://github.com/Microsoft/vscode/search?q=installAndRestartMessage&unscoped_q=installAndRestartMessage

https://github.com/Microsoft/vscode-loc/search?q=installAndRestartMessage&unscoped_q=installAndRestartMessage

Can you ensure that these strings get into the language packs?

**Comment by sandy081** [comment]
@danyeh Following language packs are not missing translations for those necessary strings which we show to user to install the language pack before installing it. 

- `de`
```
"vs/platform/node/minimalTranslations": {
	"searchMarketplace": "Marketplace durchsuchen",
	"installAndRestart": "Installieren und neu starten"
}
```

- `es`
```
"vs/platform/node/minimalTranslations": {
    "searchMarketplace": "Buscar en Marketplace ",
    "installAndRestart": "Instalar y Reiniciar"
}
```

- `fr`
```
"vs/platform/node/minimalTranslations": {
    "searchMarketplace": "Rechercher dans le Marketplace",
    "installAndRestart": "Installer et Redémarrer"
}
```

- `it`
```
"vs/platform/node/minimalTranslations": {
    "searchMarketplace": "Cerca nel Marketplace",
    "installAndRestart": "Installa e riavvia"
}
```

**Comment by ramya-rao-a** [comment]
>-zh-tw: No translations at all
Only zh-cn has translations for all strings.

@sandy081 When users choose zh-cn or zh-tw we fall back to zh-hans or zh-hant respectively. The pack for zh-hans has the required translations, zh-hant doesnt.

**Comment by danyeh** [comment]
According to loc schedule, we will cover all strings by end of day July 3rd. And publish language pack afterward.

**Comment by sandy081** [comment]
> When users choose zh-cn or zh-tw we fall back to zh-hans or zh-hant respectively. The pack for zh-hans has the required translations, zh-hant doesnt.

Fallback is only for extension name and locale id contributed by respective extensions still should be `zh-cn` and `zh-tw`.

**Comment by danyeh** [comment]
As of today, we have zh-cn, fr, it, ja, ko language pack loc completed and published in Marketplace.

**Comment by sandy081** [comment]
Thanks @danyeh for the update. 

- `zh-cn`: This needed fix from our side
![image](https://user-images.githubusercontent.com/10746682/42223168-6752f4a2-7ed7-11e8-9d71-7da3459a0f05.png)

- `fr`
![image](https://user-images.githubusercontent.com/10746682/42222274-f5a837a6-7ed4-11e8-948d-2f1ec6dc1421.png)

- `it`
![image](https://user-images.githubusercontent.com/10746682/42222297-08653434-7ed5-11e8-8c75-0f90b1cd30f8.png)

- `ja`
![image](https://user-images.githubusercontent.com/10746682/42222312-1fd5ef6e-7ed5-11e8-9b19-1bc8f79d3e3d.png)

- `ko`
![image](https://user-images.githubusercontent.com/10746682/42222334-2fe2c80a-7ed5-11e8-9f5e-5e8201839314.png)

**Comment by danyeh** [comment]
Remaining language pack loc completed and published in Marketplace - de, es, ru, zh-tw.

**Comment by sandy081** [comment]
Verified all core language packs showing recommendation prompt in their respective languages.
