### ISSUE TITLE
VS Code displays in English alfter update

### ISSUE THREAD

**Issue by byyxx128** [Microsoft/vscode#53139]
Issue Type: <b>Bug</b>

Sometimes VS Code displays in English, although I have installed language pack and set "locale":"zh-CN", especially when I just update and reopened VS Code.
Reinstalling the language pack will be useful, but it has happened more than once.

VS Code version: Code - Insiders 1.25.0-insider (923e9ccb3fc44bfaaf4b4049015c84e42bc40f95, 2018-06-26T13:11:31.133Z)
OS version: Windows_NT x64 10.0.17686

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.53GB (4.43GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe F:\Images\Adobe Prelude CC 2018.1 SP\packages\setup.xml|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
minibex-lang|ama|0.0.4
vscode-language-pack-zh-hans|MS-|1.25.1
cpptools|ms-|0.17.5

(1 theme extensions excluded)

</details>

**Comment by dbaeumer** [comment]
@byyxx128 do you have any additional information. If you don't reinstall the language pack and close and reopen VS Code will it start correctly?

**Comment by dbaeumer** [comment]
@sandy081 adding you as well. Could it be that the LP install is broken?

**Comment by Joelism** [comment]
I got this problem, too.
It seems `languageId` of the lp is `zh-hans` now, and once `"locale": "zh-hans"` is set in locale.json, VS Code is in Simplified Chinese again.

**Comment by dbaeumer** [comment]
@danyeh I thought we have fixed this? Looking at the contribution section of the LP in the market place it is indeed zh-hans.

<img width="883" alt="capture" src="https://user-images.githubusercontent.com/1931590/42024018-8f7bd47c-7ac1-11e8-9579-7d7b8180419b.png">

**Comment by dbaeumer** [comment]
@danyeh can you fix this?

**Comment by dbaeumer** [comment]
@byyxx128 

when this happens the next time can you please provide us with the following information:

- the content of the languagePacks.json file located at C:\Users\${your user}\AppData\Roaming\Code - Insiders where ${your user} is your user id
- the content of the clp directory located at the same location. You can zip the content.

Can the commit id of the VS Code insider version you are using. Can be found in the help about dialog.

**Comment by sandy081** [comment]
Filed a separate issue for zh-cn locale id - https://github.com/Microsoft/vscode/issues/53317

**Comment by byyxx128** [comment]
OK, I'll obverse if it would happen next time. Then I can give you more details.

**Comment by dbaeumer** [comment]
The problem with using `zh-hans` instead of `zh-cn` is tracked here #53317 and got fixed. I tested it this morning and both `zh-tw` and `zh-cn` work for me. 

@byyxx128 what infinite loop are you seeing?

**Comment by sandy081** [comment]
> @byyxx128 And this value has been changed automatically.

Its because the Simplified Chinese language extension has `zh-Hans` as locale id. Hence when you say `Install and Restart` the locale id is set to `zh-Hans` in the file.

**Comment by byyxx128** [comment]
@dbaeumer Well, if `zh-hans` is used instead of `zh-cn` (I'm not sure who change it... maybe the extension?), VS Code will displayed in English, and ![image](https://user-images.githubusercontent.com/20079289/42257944-395e71ca-7f27-11e8-849c-cfcd9beffa1a.png) always pops when VS Code start. And if I click ![image](https://user-images.githubusercontent.com/20079289/42257992-72ee7872-7f27-11e8-9ef1-26d2557331ec.png), Code will restart automatically, but it will still display in English.
If I change `zh-hans` to `zh-cn`, the restart VS Code, everything will be okey.

**Comment by dbaeumer** [comment]
@byyxx128 ok. Now I understand. The correct id is `zh-cn`. There was a bug with a published `zh-cn` Language pack that used `zh-hans` instead bringing you into this loop. This got fix for today. So everything should be fine again when using `zh-cn`.

**Comment by dbaeumer** [comment]
@byyxx128 any objection to close ?

**Comment by byyxx128** [comment]
@dbaeumer 🆗, everything seems fine now. You can close this issue. Thanks for your and your colleagues' job.

**Comment by sandy081** [comment]
Removed it from the schema/proposals.

**Comment by aeschli** [comment]
@dbaeumer @sandy081 I think #53317 isn't the correct fix and that we should start using the new language ids (`zh-hans`..) in our contribution points.

**Comment by sandy081** [comment]
Agreed fix looks ugly, but we want to continue support old ids as it is like an API I suppose.

**Comment by sandy081** [comment]
Yes, we should not restrict language pack writers to provide translations for zh_hans and zh_hant.

So, this fix will force all language packs to use zh_cn and zh_tw which is not correct IMO. 

I do not understand why is this fix needed? Core translations team should run the tool with zh_cn and zh_tw not with zh_hans and zh_hant.

@danyeh ?

**Comment by dbaeumer** [comment]
The problems are extensions not users of VS Code. We pass the locale and language information along to extensions using the `VSCODE_NLS_CONFIG` and in there we need to keep `zh-cn` and `zh-tw` since these we use since day one.

In addition `appLocale` (the electron function) returns `zh-cn` and `zh-tw` and we should stay consistent here.

**Comment by byyxx128** [comment]
@dbaeumer 
There's still an error: if I change the `"locale"` to `zh-hans` manually, it still reminds me to install LP switch to `zh-hans`, although ![image](https://user-images.githubusercontent.com/20079289/42738059-80da5906-884b-11e8-950e-dbd2e2de88a2.png).
![image](https://user-images.githubusercontent.com/20079289/42738063-9287f9f6-884b-11e8-8c9a-bbe787c4958b.png)
If I click ![image](https://user-images.githubusercontent.com/20079289/42738074-b04a86f2-884b-11e8-89be-e61ec03283e3.png), it will install Chinese LP. But as you know, it won't work, and it will remind again. So I think you should remove all support of `zh-hans`. Because if I change the value to ![image](https://user-images.githubusercontent.com/20079289/42738093-18a3e63a-884c-11e8-9c31-cdb0dce6edbc.png), it won't remind me.

**Comment by dbaeumer** [comment]
@byyxx128 in this scenario do you have the language pack installed before changing the locale to `zh-hans`?

**Comment by byyxx128** [comment]
@dbaeumer It will happen whether or not I installed a language pack. Maybe because `zh-hans` is still detected as an available locale although it has been removed from the proposals list. If I change the value to `123` `abc` or any other unavailable values, it won't happen.
Actually it won't affect users unless one changes the locale proactively.
But I think you need to fix it to make VS Code more perfect.

**Comment by dbaeumer** [comment]
@ramya-rao-a can you explain why this happens. Do we have code that if the user request 'zh-hans' we download the corresponding Chinese language pack. I can add code to the main.js to convert `zh-hans`and `zh-hant`back to the 2 digit format but since everything works correctly if the user put `xxx` in I would first like to understand if this is really necessary.

**Comment by byyxx128** [comment]
Well I think you guys can remove everything about `zh-hans` directly. If you still keep it, it will be very inconvenient to make it available.

**Comment by dbaeumer** [comment]
@ramya-rao-a if you type `zh-hans` into the locale.json file you get a warning saying that this locale is not supported. So I am fine if in this case the UI comes up in English (it does for all other unknown locales). IMO all the trouble started when we named the language pack with a prefix of `zh-hans` instead of `zh-cn`.

@ramya-rao-a I am actually not sure what you propose as a fix. Should we map `zh-hans` back to `zh-cn` and allow it as I proposed above or do you have a better fix.

**Comment by ramya-rao-a** [comment]
@dbaeumer I suggest #54696 as the fix.
