### ISSUE TITLE
Git: Support to bulk resolve merge changes

### ISSUE THREAD

**Issue by mnikn** [Microsoft/vscode#53133]
The git stash conflict handle doesn't has a option to apply all current changes or incoming changes, you must apply the changes one by one，What if we add two new menu item to support apply all current changes or incoming changes, like:

![demo](https://user-images.githubusercontent.com/12381740/41972016-0f57298c-7a43-11e8-9517-6f6ebf371de1.png)

**Comment by joaomoreno** [comment]
This is independent of stash.
