### ISSUE TITLE
Workbench entry under Workbench ?

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#53132]
Testing #52859 

![image](https://user-images.githubusercontent.com/10746682/41969821-fa7e6d66-7a08-11e8-9c0f-f4e0a62251bc.png)

Workbench section under Workbench group does not look correct to me. Also we do not have any explanation of that. 

Also Window under Window. May be a single section for Window would be good?

**Comment by roblourens** [comment]
Yes that's the "etc" section. It could also be called "general" or something
