### ISSUE TITLE
Open Editors shows beginnings of file paths instead of endings

### ISSUE THREAD

**Issue by cnlier** [Microsoft/vscode#53135]
Issue Type: <b>Bug</b>

When one has multiple equally named files open, those can normally be distinguished by looking at the ending of their file paths. The editor tabs show these endings, which is fine. However, the list in the "Open Editors" view shows the beginnings of the paths instead, which are usually identical for all of my files (something like "~/Documents/workspace..."). So I can't know which file is which.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
OS version: Darwin x64 17.6.0

**Comment by isidorn** [comment]
Thanks for your feedback, however this is designed behavior and we have no plans to change this at the moment.
We do not want to change this because we show paths like that in all of vscode and no other customer complained thus far. Thanks!
