### ISSUE TITLE
Menu: click does not close menu when opened in this case

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#53149]
Steps to Reproduce:

1. mouse into title area (not the menu)
2. press Alt once
3. click on "Terminal"
4. hit ESC
5. click on "Terminal"
6. click on "Terminal" until it does not disappear but simply opens again

A bit hard to reproduce.

**Comment by sbatten** [comment]
a lot of churn to focus behavior seems to have fixed this. please verify
