### ISSUE TITLE
Can't take a screenshot of a tooltip

### ISSUE THREAD

**Issue by LAITONEN** [Microsoft/vscode#53148]
- VSCode Version: 1.24.1
- OS Version: 10.12.6

**Steps to Reproduce:**
Issues was asserted only on macOS (Sierra and High Sierra)
1. Hover over any part of the code.
2. Try taking a snapshot using `CMD+SHIFT+4`.
3. The tooltip closes, the snapshot does not contain a tooltip.

**Does this issue occur when all extensions are disabled?: Yes/No**
Yes

**Comment by alexandrudima** [comment]
The hover is built to disappear when keypresses occur in order to allow for typing unobstructed. I think this is a good behaviour. Perhaps there are other macOS ways to take a delayed shortcut...

**Comment by alexandrudima** [comment]
But then the <kbd>4</kbd> would close it...

I will not do any changes here, as these keybindings can be customized and we have no idea what they could be bound to:
![image](https://user-images.githubusercontent.com/5047891/42080023-9a98b54e-7b81-11e8-88d7-1d9ee39aacd4.png)

Here are steps for how to take a timed screenshot: http://www.idownloadblog.com/2016/05/11/take-timed-screenshot-on-mac/

**Comment by LAITONEN** [comment]
@alexandrudima It does not. This is the reason why I did not mention `4` as an issue.
