### ISSUE TITLE
Screen blacking out

### ISSUE THREAD

**Issue by megaflop666** [Microsoft/vscode#53141]
I recently installed vscode on my pixelbook and it runs fine except for one little annoying issue.  Everytime I click on a menu, or right click to bring up a menu, the entire app goes black and then slowly starts to repopulate the screen in chunks.  Example, if I click on File everything inside the window goes blank and then comes back up, if I slide over to edit, selection, etc, it does the same thing.
I have been searching around this morning and found no one else reporting this issue.  It only effects my new install of vscode through the linux terminal on my pixelbook.  If I run it through my old crouton container there are no issues.

**Comment by roblourens** [comment]
Which OS?

**Comment by megaflop666** [comment]
Google Chrome OS Canary 69

**Comment by Tyriar** [comment]
We don't support chromeos currently, https://github.com/Microsoft/vscode/issues/1031
