### ISSUE TITLE
Menu: inactive window should show menu and buttons as inactive

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#53147]
Refs: #52854

It seems to me that a window that is not active shows the menu and window buttons slightly dimmed:

![image](https://user-images.githubusercontent.com/900690/41976475-8b4a1d2c-7a1d-11e8-904b-56468ffc8555.png)

I do not think we are doing this currently for anything but the title background and foreground.

**Comment by sbatten** [comment]
resolved via #54003
