### ISSUE TITLE
onDidExpand and onDidCollapse events for TreeView

### ISSUE THREAD

**Issue by ivankravets** [Microsoft/vscode#53156]
VSCode calls `TreeDataProvider.getChildren` even when a user does not expand a view. For example, "Debug View" can contain different TreeViews(Providers) and they are collapsed by default. It could be registers, peripherals, memory, and other views. There is no need to update all these views if a user will not see them.

I propose to `TreeDataProvider.getChildren` when a user expands a view or implement `onDidExpand` and `onDidCollapse` events for TreeView and we can update a state of TreeDataProvider depending on the current state of the view.

**Comment by sandy081** [comment]
@ivankravets VS Code is supposed to call getChildren only when needed

- When the view is shown, first level elements are asked
- When user expands a node, children for that node are asked
- If the node has collapsible property set to expanded, then the children of the node are asked

If you see getChildren is called when not in above cases, it should be a bug. Can you please provide your sample where you are seeing this behaviour?

Also, `TreeView` already has `onDidExpandElement` and `onDidCollapseElement` events.

**Comment by ivankravets** [comment]
> When the view is shown

Could you explain in details here? What do you mean by "shown"? We have different views for debugging, see the main screenshot here https://marketplace.visualstudio.com/items?itemName=platformio.platformio-ide

"Memory" or "Disassembly" views are collapsed. Should VSCode, in this case, call `getChildren` even if a user has not asked?

**Comment by sandy081** [comment]
There should not be a call to `getChildren` when the view is collapsed and user has not asked for.

**Comment by ivankravets** [comment]
It seems that a bug. It calls `getChildren` every time. Could you reproduce it?

**Comment by sandy081** [comment]
Its not happening to me. Do you have a sample to reproduce it?

**Comment by ivankravets** [comment]
I tried [this](https://github.com/Microsoft/vscode-extension-samples/tree/master/tree-view-sample) example and can't reproduce. So, I decided to dive into deeper. 

So, when I move `platformio-debug.disassembly` into `views->explorer`, VSCode does not call `getChildren`. Everything is OK. However, when I move it to `debug` and start a debug session it call `getChildren`. See configuration below.
```
    "views": {
      "explorer": [
        {
          "id": "platformio-debug.disassembly",
          "name": "Disassembly"
        }
      ],
      "debug": [
        {
          "id": "platformio-debug.peripherals",
          "name": "Peripherals",
          "when": "debugType == platformio-debug && peripheralsEnabled"
        },
        {
          "id": "platformio-debug.registers",
          "name": "Registers",
          "when": "debugType == platformio-debug"
        },
        {
          "id": "platformio-debug.memory",
          "name": "Memory",
          "when": "debugType == platformio-debug"
        }
      ]
    },
```

**Comment by sandy081** [comment]
@ivankravets May I know if the view is expanded during that time?

**Comment by ivankravets** [comment]
No, it is a part of Debug ActivityBar.

**Comment by sandy081** [comment]
Can you please provide a screenshot of VS Code when `getChildren` is called ?
