### ISSUE TITLE
Unknown at-rule causes placing cursor on CSS tokens to highlight entire document

### ISSUE THREAD

**Issue by JacksonKearl** [Microsoft/vscode#53159]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/8586769/41987308-9cc81ba6-79ed-11e8-881f-35daf05cb573.png)

this happens with all `"css.lint.unknownAtRules"` setting and does not happen in stable.
#52864
VS Code version: Code - Insiders 1.25.0-insider (f2fa6bea46bde9856e6a593e4d4c5af2b303ac66, 2018-06-27T05:18:12.763Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (6.32GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.4.1
tslint|eg2|1.0.33
debugger-for-chrome|msj|4.7.0
subtle-brackets|raf|2.1.1
vscode-multiclip|sle|0.1.4
code-spell-checker|str|1.6.10

</details>

**Comment by aeschli** [comment]
@JacksonKearl Can you paste the search code from the screenshot so we can validate if the fix works?
