### ISSUE TITLE
Don't trigger the shift+enter keyboard shortcut while searching

### ISSUE THREAD

**Issue by fiendish** [Microsoft/vscode#53151]
Issue Type: <b>Bug</b>

1. Open a Python file.
2. Select something in the file.
3. Press Cmd+F or Ctrl+F to start searching.
4. Press Shift+Enter to find the previous match.
5. Watch the Terminal pop up, probably with some garbage NameErrors about whatever you selected not being defined.

This is because Shift+Enter is the default keyboard shortcut for "Run Selection/Line in Python Terminal", but that shouldn't be firing during a search.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.34GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.58
markdown-preview-github-styles|bie|0.1.2
vscode-markdownlint|Dav|0.18.0
jupyter|don|1.1.4
gc-excelviewer|Gra|2.1.24
rainbow-csv|mec|0.4.2
python|ms-|2018.6.0
rewrap|stk|1.9.1
python-extended-snippets|tus|0.0.1
markdown-all-in-one|yzh|1.5.0

</details>

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-python/

**Comment by fiendish** [comment]
I understand that the extension adds that shortcut, but is the activation of keyboard shortcuts in general during search actually controlled by extensions?
