### ISSUE TITLE
 Cannot assign to read only property 'enabled' of object '#<Object>'

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#53152]
Issue Id: <b>579d7b1f-9f9c-2f59-c541-8b03166dc623</b><br /><br />*Versions* <br />- 1.25.0-insider (6/25/2018 9:37:32 AM)<br />*Stack* <br />TypeError: Cannot assign to read only property 'enabled' of object '#<Object>'<br />[/vs/base/common/objects.ts#107:25](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/base/common/objects.ts#L107:25)<br />    at Array.forEach (native)<br />[/vs/base/common/objects.ts#101:22 (mixin)](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/base/common/objects.ts#L101:22 (mixin))<br />[/vs/base/common/objects.ts#105:6](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/base/common/objects.ts#L105:6)<br />    at Array.forEach (native)<br />[/vs/base/common/objects.ts#101:22 (mixin)](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/base/common/objects.ts#L101:22 (mixin))<br />[/vs/editor/browser/widget/embeddedCodeEditorWidget.ts#57:10 (updateOptions)](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/editor/browser/widget/embeddedCodeEditorWidget.ts#L57:10 (updateOptions))<br />[/vs/workbench/parts/debug/electron-browser/debugEditorContribution.ts#295:15 (_applyHoverConfiguration)](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/workbench/parts/debug/electron-browser/debugEditorContribution.ts#L295:15 (_applyHoverConfiguration))<br />[/vs/workbench/parts/debug/electron-browser/debugEditorContribution.ts#265:8 (call)](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/workbench/parts/debug/electron-browser/debugEditorContribution.ts#L265:8 (call))<br />[/vs/base/common/event.ts#140:15 (fire)](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/base/common/event.ts#L140:15 (fire))<br />[/vs/editor/browser/widget/codeEditorWidget.ts#387:25 (setModel)](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/editor/browser/widget/codeEditorWidget.ts#L387:25 (setModel))<br />[/vs/editor/contrib/referenceSearch/referencesWidget.ts#810:18 (onComplete)](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/editor/contrib/referenceSearch/referencesWidget.ts#L810:18 (onComplete))<br />[/vs/base/common/winjs.base.js#1581:0 (then)](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/base/common/winjs.base.js#L1581:0 (then))<br />[/vs/editor/contrib/referenceSearch/referencesWidget.ts#794:64](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/editor/contrib/referenceSearch/referencesWidget.ts#L794:64)<br />[/vs/base/common/winjs.base.js#10:0](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/base/common/winjs.base.js#L10:0)<br />[/vs/base/common/winjs.base.js#10:0](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/base/common/winjs.base.js#L10:0)<br />

**Comment by vscodeerrors** [comment]
Here is another similar callstack 

TypeError: Cannot assign to read only property 'enabled' of object '#<Object>'<br />[/vs/base/common/objects.ts#107:25](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/base/common/objects.ts#L107:25)<br />    at Array.forEach (native)<br />[/vs/base/common/objects.ts#101:22 (mixin)](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/base/common/objects.ts#L101:22 (mixin))<br />[/vs/base/common/objects.ts#105:6](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/base/common/objects.ts#L105:6)<br />    at Array.forEach (native)<br />[/vs/base/common/objects.ts#101:22 (mixin)](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/base/common/objects.ts#L101:22 (mixin))<br />[/vs/editor/common/config/commonEditorConfig.ts#187:29 (updateOptions)](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/editor/common/config/commonEditorConfig.ts#L187:29 (updateOptions))<br />[/vs/editor/browser/widget/codeEditorWidget.ts#337:22 (call)](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/editor/browser/widget/codeEditorWidget.ts#L337:22 (call))<br />[/vs/editor/browser/widget/embeddedCodeEditorWidget.ts#52:21 (_onParentConfigurationChanged)](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/editor/browser/widget/embeddedCodeEditorWidget.ts#L52:21 (_onParentConfigurationChanged))<br />[/vs/editor/browser/widget/embeddedCodeEditorWidget.ts#44:95 (call)](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/editor/browser/widget/embeddedCodeEditorWidget.ts#L44:95 (call))<br />[/vs/base/common/event.ts#140:15 (fire)](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/base/common/event.ts#L140:15 (fire))<br />[/vs/editor/browser/widget/codeEditorWidget.ts#227:34 (call)](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/editor/browser/widget/codeEditorWidget.ts#L227:34 (call))<br />[/vs/base/common/event.ts#140:15 (fire)](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/base/common/event.ts#L140:15 (fire))<br />[/vs/editor/common/config/commonEditorConfig.ts#113:21 (_recomputeOptions)](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/editor/common/config/commonEditorConfig.ts#L113:21 (_recomputeOptions))<br />[/vs/editor/common/config/commonEditorConfig.ts#189:7 (updateOptions)](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/editor/common/config/commonEditorConfig.ts#L189:7 (updateOptions))<br />[/vs/editor/browser/widget/codeEditorWidget.ts#337:22](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/editor/browser/widget/codeEditorWidget.ts#L337:22)<br />

**Comment by vscodeerrors** [comment]
Here is another similar callstack 

TypeError: Cannot assign to read only property 'enabled' of object '#<Object>'<br />[/vs/base/common/objects.ts#107:25](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/base/common/objects.ts#L107:25)<br />    at Array.forEach (native)<br />[/vs/base/common/objects.ts#101:22 (mixin)](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/base/common/objects.ts#L101:22 (mixin))<br />[/vs/base/common/objects.ts#105:6](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/base/common/objects.ts#L105:6)<br />    at Array.forEach (native)<br />[/vs/base/common/objects.ts#101:22 (mixin)](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/base/common/objects.ts#L101:22 (mixin))<br />[/vs/editor/common/config/commonEditorConfig.ts#187:29 (updateOptions)](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/editor/common/config/commonEditorConfig.ts#L187:29 (updateOptions))<br />[/vs/editor/browser/widget/codeEditorWidget.ts#337:22 (call)](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/editor/browser/widget/codeEditorWidget.ts#L337:22 (call))<br />[/vs/editor/browser/widget/embeddedCodeEditorWidget.ts#52:21 (_onParentConfigurationChanged)](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/editor/browser/widget/embeddedCodeEditorWidget.ts#L52:21 (_onParentConfigurationChanged))<br />[/vs/editor/browser/widget/embeddedCodeEditorWidget.ts#44:95 (call)](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/editor/browser/widget/embeddedCodeEditorWidget.ts#L44:95 (call))<br />[/vs/base/common/event.ts#140:15 (fire)](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/base/common/event.ts#L140:15 (fire))<br />[/vs/editor/browser/widget/codeEditorWidget.ts#227:34 (call)](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/editor/browser/widget/codeEditorWidget.ts#L227:34 (call))<br />[/vs/base/common/event.ts#140:15 (fire)](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/base/common/event.ts#L140:15 (fire))<br />[/vs/editor/common/config/commonEditorConfig.ts#113:21 (_recomputeOptions)](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/editor/common/config/commonEditorConfig.ts#L113:21 (_recomputeOptions))<br />[/vs/editor/common/config/commonEditorConfig.ts#189:7 (updateOptions)](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/editor/common/config/commonEditorConfig.ts#L189:7 (updateOptions))<br />[/vs/editor/browser/widget/codeEditorWidget.ts#337:22](https://github.com/microsoft/vscode/blob/5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3/src/vs/editor/browser/widget/codeEditorWidget.ts#L337:22)<br />

**Comment by alexandrudima** [comment]
As this might be the cause of #52950, we should investigate for june

**Comment by alexandrudima** [comment]
Possible steps to reproduce. (There might be other steps):
* have side by side a `.js` file and the user `settings.json`
* in the user `settings.json` write `"editor.hover.enabled": false`
* **reload workbench**
* in the `.js` file begin debugging
* in the `.js` file stop debugging
* comment out the setting in the settings side editor

```
 ERR Cannot assign to read only property 'enabled' of object '#<Object>': TypeError: Cannot assign to read only property 'enabled' of object '#<Object>'
    at file:///Users/alex/src/vscode/out/vs/base/common/objects.js:101:46
    at Array.forEach (native)
    at mixin (file:///Users/alex/src/vscode/out/vs/base/common/objects.js:94:33)
    at file:///Users/alex/src/vscode/out/vs/base/common/objects.js:98:29
    at Array.forEach (native)
    at Object.mixin (file:///Users/alex/src/vscode/out/vs/base/common/objects.js:94:33)
    at Configuration.CommonEditorConfiguration.updateOptions (file:///Users/alex/src/vscode/out/vs/editor/common/config/commonEditorConfig.js:142:40)
    at CodeEditorWidget.updateOptions (file:///Users/alex/src/vscode/out/vs/editor/browser/widget/codeEditorWidget.js:185:33)
    at TextFileEditor.BaseTextEditor.updateEditorConfiguration (file:///Users/alex/src/vscode/out/vs/workbench/browser/parts/editor/textEditor.js:242:36)
    at TextFileEditor.BaseTextEditor.handleConfigurationChangeEvent (file:///Users/alex/src/vscode/out/vs/workbench/browser/parts/editor/textEditor.js:69:22)
    at file:///Users/alex/src/vscode/out/vs/workbench/browser/parts/editor/textEditor.js:43:109
    at Emitter.fire (file:///Users/alex/src/vscode/out/vs/base/common/event.js:148:38)
    at file:///Users/alex/src/vscode/out/vs/editor/common/services/resourceConfigurationImpl.js:36:135
    at Emitter.fire (file:///Users/alex/src/vscode/out/vs/base/common/event.js:148:38)
    at WorkspaceService.triggerConfigurationChange (file:///Users/alex/src/vscode/out/vs/workbench/services/configuration/node/configurationService.js:550:48)
    at WorkspaceService.onUserConfigurationChanged (file:///Users/alex/src/vscode/out/vs/workbench/services/configuration/node/configurationService.js:422:18)
    at file:///Users/alex/src/vscode/out/vs/workbench/services/configuration/node/configurationService.js:53:105
    at Emitter.fire (file:///Users/alex/src/vscode/out/vs/base/common/event.js:148:38)
    at file:///Users/alex/src/vscode/out/vs/platform/configuration/node/configuration.js:34:136
    at Emitter.fire (file:///Users/alex/src/vscode/out/vs/base/common/event.js:148:38)
    at file:///Users/alex/src/vscode/out/vs/base/node/config.js:151:53
    at file:///Users/alex/src/vscode/out/vs/base/node/config.js:78:24
    at /Users/alex/src/vscode/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (original-fs.js:439:3)
```

**Comment by isidorn** [comment]
Nice steps, can not repro with latest insiders -> verified
