### ISSUE TITLE
Unsafe RegExp.exec() usage?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#53153]
While fixing https://github.com/Microsoft/vscode/issues/52576 I made a quick pass of users of `RegExp.exec()` that do not check the returned result for being `null`. I found 3 possible locations:

@Tyriar 
https://github.com/Microsoft/vscode/blob/d90f82140439e38e1aafc9dc052691dd38f77901/src/vs/workbench/parts/terminal/electron-browser/terminalService.ts#L208
https://github.com/Microsoft/vscode/blob/d90f82140439e38e1aafc9dc052691dd38f77901/src/vs/workbench/parts/terminal/electron-browser/terminalLinkHandler.ts#L255

@jrieken 
https://github.com/Microsoft/vscode/blob/d90f82140439e38e1aafc9dc052691dd38f77901/src/vs/workbench/api/node/extHostDocumentData.ts#L151

Not sure if this ever caused any issue, but I wanted to bring it up nevertheless.

**Comment by jrieken** [comment]
Using it with an outer `*` is always safe.

**Comment by Tyriar** [comment]
The second one is checked for `null` earlier in `_handleLocalLink`.

**Comment by bpasero** [comment]
Thanks.
