### ISSUE TITLE
Start without debugging does not terminate a launched Rails process when clicking the stop button

### ISSUE THREAD

**Issue by camilo0365** [Microsoft/vscode#53150]
- VSCode Version: 1.24.1
- OS Version: OSX HighSierra 10.13.5

Steps to reproduce:

1. Create a Rails 5.2 app and open it in VS Code

2. Add this entry to `.vscode/launch.json`:
```
{
            "name": "Rails server",
            "type": "Ruby",
            "request": "launch",
            "cwd": "${workspaceRoot}",
            "program": "${workspaceRoot}/bin/rails",
            "args": [
                "server"
            ]
}
```

3. Launch a `Start without debugging` (Control+F5) session that uses the config entry above.

4. On a Bash shell run `ps -ef | grep  -E "UID|puma"`

```
  UID   PID  PPID   C STIME   TTY           TIME CMD
  501 49937 49936   0  4:16PM ??         0:06.58 puma 3.11.4 (tcp://localhost:3000) [app]
```

5. Stop the debugger (Shift+F5 or stop button) and re-run the command in step 4.

```
  UID   PID  PPID   C STIME   TTY           TIME CMD
  501 49937     1   0  4:16PM ??         0:06.60 puma 3.11.4 (tcp://localhost:3000) [app]
``` 

Analysis:

Judging by the PPIDs the Puma process isn't terminated when the debugger session stops. It is left orphaned and keeps running as child of the OS's init process (PID 1).

This issue does not exist when the same debug config is run in "normal" debug mode

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
Please file this issue against the Ruby extension.
