### ISSUE TITLE
Quick preview of files from Go to File dropdown 

### ISSUE THREAD

**Issue by cachvico** [Microsoft/vscode#53169]
To set up (exiting behaviour):

1. To press ctrl+p
2. To type in some parts of a set of filenames (e.g. type "foo" to see Foo.js and Foobar.php)
3. To press Up and Down keys to navigate the menu

Proposed change:

4. To see the file currently highlighted appear in the editor in Preview mode.
5. *If the mouse pointer is over the editor and not over the quick open dropdown*, the mouse wheel will scroll the editor window. (Conversely if the mouse pointer is over the file dropdown menu, it is the menu that the scroll wheel acts upon)

This will allow me to quickly scan the contents of a set of files without having to lose the context of the auto-complete Go To File dropdown. (It is one of the features of Sublime that I really like).

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/8939
