### ISSUE TITLE
Visual Studio Code not detecting #endif in .c file

### ISSUE THREAD

**Issue by PandaMakesCode** [Microsoft/vscode#53168]
- VSCode Version: 1.24.1
- OS Version: Windows 8.1

Steps to Reproduce:

1. This isn't the exact code i used, but typing this out claims that #ifndef does not have a #endif to close it
#ifndef FILE_H
#define FILE_H
#ifdef _WIN32
#pragma once
#endif
2. "the #endif for this directive is missing"

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Is this validation coming from the C++ extension? If so could you file an issue on their repo?

**Comment by PandaMakesCode** [comment]
I thought i closed this? I forgot to add another #endif
