### ISSUE TITLE
HTML snippets being suggested in attributes

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#53163]
Issue Type: <b>Bug</b>

If you have a string ending in `html` inside an html tag attribute, like this:

 ```
<app-code-block [html]="'assets/code-snippets/canvas-elements/ex.ce-appearance.html'"></app-code-block>
```

Emmet suggests and will complete an entire html document:

<img width="1183" alt="screen shot 2018-06-27 at 1 26 05 pm" src="https://user-images.githubusercontent.com/835148/41989715-36ea560c-7a0e-11e8-89cf-73e2385fbbe3.png">

VS Code version: Code - Insiders 1.25.0-insider (f2fa6bea46bde9856e6a593e4d4c5af2b303ac66, 2018-06-27T05:11:02.122Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.84GB free)|
|Process Argv|/Users/st016lo/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_9681211|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
code-settings-sync|Sha|2.9.2
better-comments|aar|1.2.6
Bookmarks|ale|0.19.1
project-manager|ale|0.25.2
bracket-pair-colorizer|Coe|1.0.58
vscode-eslint|dba|1.4.12
tslint|eg2|1.0.33
vscode-great-icons|emm|2.1.35
prettier-vscode|esb|1.5.0
auto-rename-tag|for|0.0.15
path-autocomplete|ion|1.10.0
svg|joc|0.1.1
Angular2|joh|6.1.1
ecdc|mit|0.12.0
HTMLHint|mka|0.5.0
theme-monokai-pro-vscode|mon|1.1.8
vscode-scss|mrm|0.6.2
vscode-stylefmt|mrm|2.5.0
angular2-inline|nat|0.0.17
incrementor|nms|0.1.0
vscode-versionlens|pfl|0.21.1
material-icon-theme|PKi|3.5.0
polacode|pnp|0.2.2
quicktype|qui|11.0.14
stylelint|shi|0.37.0
rewrap|stk|1.9.1
bootstrap4-vscode|the|4.1.1
sort-lines|Tyr|1.7.0
change-case|wma|1.0.0

(3 theme extensions excluded)

</details>

**Comment by ramya-rao-a** [comment]
That's actually coming from the html extension snippets

**Comment by aeschli** [comment]
That's the expected behavior, snippets are not context-aware and show up everywhere in the file.
