### ISSUE TITLE
How to build localized UI

### ISSUE THREAD

**Issue by jackqq** [Microsoft/vscode#5316]
- VSCode Version: master
- OS Version: Windows 10

I'm trying to test a few modifications to Chinese Simplified translation, but can't get the built Code app localized.

I followed the instructions from:

- [Contributing to Code](https://github.com/Microsoft/vscode/blob/master/wiki/contributing/how-to-contribute.md)

My build env is:

- Node JS v4.4.3
- Python 2.7.11
- Visual Studio Express 2013

Finally, I started Code successfully with:

    .\scripts\code.bat

However, the localized UI just wouldn't show. I discovered that the nls files,

    out\vs\workbench\workbench.main.nls.*.js

didn't get built.

How should I build them? Thanks!

I tried instruction from #2228, but couldn't clone the monacotools repository because I'm not authorized. And don't know if this is the right way to go.

**Comment by dbaeumer** [comment]
@jackqq you need to run a full build. You can do that using the following command from a command prompt in the vscode directory:

gulp vscode-win32

This builds a full vscode version in ..\VSCode-Win32. After it is done change to that directory and start 'Code - OSS.exe'.
