### ISSUE TITLE
Process explorer does not work on linux for portable install

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#53166]
Issue Type: <b>Bug</b>

1. Create a portable install at a folder path that has a space in the name (mine was under `/home/parallels/Downloads/porta code`)
1. Open vs code portable install
1. Open process explorer

**Bug**
No content.

```
ncaught (in promise) Error: Command failed: /home/parallels/Downloads/porta code/VSCode-linux-x64/resources/app/out/vs/base/node/cpuUsage.sh 4982 4985 5018 5030 5158 5258 5103 5104 5276 5148 5277 5180
/bin/sh: 1: /home/parallels/Downloads/porta: not found


    at ChildProcess.exithandler (child_process.js:217:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe.Socket._destroy.cb._handle.close [as _onclose] (net.js:510:12)
```

VS Code version: Code - Insiders 1.25.0-insider (923e9ccb3fc44bfaaf4b4049015c84e42bc40f95, 2018-06-26T13:07:17.299Z)
OS version: Linux x64 4.13.0-45-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (2 x 2194)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|3.85GB (0.68GB free)|
|Process Argv|/home/parallels/Downloads/porta code/VSCode-linux-x64/code-insiders|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
color-info|bie|0.5.0
markdown-preview-github-styles|bie|0.1.2

</details>

**Comment by mjbvz** [comment]
Actually even the normal insiders install doesn't seem to work:

```
Uncaught (in promise) Error: Command failed: /usr/share/code-insiders/resources/app/out/vs/base/node/cpuUsage.sh 7012 7018 7050 7062 7146 7204 7118 7119 7226 7227
/bin/sh: 1: /usr/share/code-insiders/resources/app/out/vs/base/node/cpuUsage.sh: not found


    at ChildProcess.exithandler (child_process.js:217)
    at emitTwo (events.js:106)
    at ChildProcess.emit (events.js:194)
    at maybeClose (internal/child_process.js:899)
    at Socket.<anonymous> (internal/child_process.js:342)
    at emitOne (events.js:96)
    at Socket.emit (events.js:191)
    at Pipe.Socket._destroy.cb._handle.close [as _onclose] (net.js:510)
```

@RMacfarlane Any idea why this file would be missing?

**Comment by RMacfarlane** [comment]
Ah, no, you're right, that's a separate issue. My change was just for making sure the script exists in the out folder, not for handling paths with space
