### ISSUE TITLE
Explorer - Indicate ignored files (say by symbol i)

### ISSUE THREAD

**Issue by Agarwal-Nikhil** [Microsoft/vscode#53171]
Like untracked files are indicated by U. Is it possible to indicate ignored files by i.

**Comment by isidorn** [comment]
Currently we indicate ignored files by greying them out.
Leaving this open as a feature request
@jrieken this is currently not possible to be done via an extension ,correct?

**Comment by jrieken** [comment]
No, that's currently not possible...
