### ISSUE TITLE
Pressing space should toggle checkbox value in new settings editor

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#53174]
Testing #52859
Issue Type: <b>Bug</b>

Pressing space should toggle checkbox value in new settings editor when using the keyboard to select an option.

In the screenshot here the option is selected, and pressing space should toggle the checkbox.

<img width="1552" alt="screen shot 2018-06-27 at 1 51 41 pm" src="https://user-images.githubusercontent.com/173559/41999104-6f8ac5ca-7a11-11e8-8ee5-91b80dbbc79a.png">

VS Code version: Code - Insiders 1.25.0-insider (923e9ccb3fc44bfaaf4b4049015c84e42bc40f95, 2018-06-26T13:00:22.932Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
jsx|Twe|0.0.1
chrome-vs-code|fab|0.0.1
vscode-azureappservice|ms-|0.8.1
azure-account|ms-|0.4.1
debugger-for-chrome|msj|4.7.0
vscode-icons|rob|7.24.0

</details>

**Comment by roblourens** [comment]
I think it should only do this when the checkbox is selected (via tab or enter) to avoid accidentally flipping booleans when navigating. For example I often use space for paging and might press it on this list out of muscle memory.

**Comment by auchenberg** [comment]
I don't. I find it confusing that you have to tab to the particular form control inside the settings item in order to change the setting. It's one level too deep.

Much like we try to put focus into <textareas> or <input> when you click or focus it's wrapper element we should do the same here.

**Comment by roblourens** [comment]
I think the settings editor will feel fragile if I can change settings with a single accidental keypress. Also why should boolean controls be special, when I can't change other types with a single keypress? At least this would be consistent, so users would know they always can press the same key to get into an editing state.

**Comment by auchenberg** [comment]
In general I'd say that we should try to make the settings actionable with as few clicks as possible. 

Ex: If I tab or select a settings option, it would be actionable by default, meaning that if I start typing and the setting is free text the <input> would be populated, etc.

If you try settings in Google Chrome or Atom, you see that pattern where the control for a given setting is getting focused by default. You don't have to "tab" into the setting.

**Comment by roblourens** [comment]
How are you manipulating settings in Atom with the keyboard? I can't get that to work.

In Chrome you can tab directly from control to control which is a different model than what we have here, since we also need to scroll and expand the setting, etc. Although it's a little simpler now that we've removed the 'reset' button.

**Comment by auchenberg** [comment]
Atom: If you select one option by clicking then you can tab between the settings (no clear active indicator) but you can toggle checkboxes with space,  and select dropdown values, etc.  Atom also puts focus into the first input when you change sections to the left.

**Comment by roblourens** [comment]
Ok I see, the focus is totally invisible at least in the default theme I'm using, that's no good.

**Comment by auchenberg** [comment]
Good question What if we tabbed between controls, and still had the active state around the whole option? That way you when using the keyboard you would have an actionable option, and if an option form control agains focus the whole option is marked as focused/active?

Kinda like the bottom list here https://material-components.github.io/material-components-web-catalog/#/component/text-field

**Comment by roblourens** [comment]
Continuing this in #54039
