### ISSUE TITLE
Settings editor: Shouldn't be possible to select setting groups with keyboard

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#53177]
Testing #52859 
Issue Type: <b>Bug</b>

Seems odd that I can use the keyboard to select an editor group, when it doesnt have any actions?

<img width="1552" alt="screen shot 2018-06-27 at 1 56 33 pm" src="https://user-images.githubusercontent.com/173559/41999342-20b880c6-7a12-11e8-93cf-0763c331f3cb.png">

VS Code version: Code - Insiders 1.25.0-insider (923e9ccb3fc44bfaaf4b4049015c84e42bc40f95, 2018-06-26T13:00:22.932Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
jsx|Twe|0.0.1
chrome-vs-code|fab|0.0.1
vscode-azureappservice|ms-|0.8.1
azure-account|ms-|0.4.1
debugger-for-chrome|msj|4.7.0
vscode-icons|rob|7.24.0

</details>

**Comment by roblourens** [comment]
#53118
