### ISSUE TITLE
Auto complete suggests words from comments

### ISSUE THREAD

**Issue by vladtz** [Microsoft/vscode#5317]
- VSCode Version: 1.0.0
- OS Version: Windows 10 1511

As a student, I write my comments in Romanian, but the functions and variables are mostly in English. So when I try to type something that starts similar in both languages, the suggestions are really confusing and counter-productive.

Steps to Reproduce:

1. Type a random word in comments 
2. Example in C:

![image](https://cloud.githubusercontent.com/assets/1708491/14555681/9438d03a-02fc-11e6-8aa2-028270810a6e.png)

At least it could be suggested below the function.

**Comment by jrieken** [comment]
This is on purpose. VS Code works with multiple suggestion providers and merges the results of all of them. There is a hierarchy of providers - more specific ones that return a result will make not make textual completion show. 
Take, for instance JavaScript for which we have 'smart' suggestions - if that provider yields a result we won't add textual completions, iff not we will. In your case both suggestion are textual (not smart) and therefore both show - that's the default unless there an extension that understands C like https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools
