### ISSUE TITLE
Search in new settings editor doesnt take me to the results

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#53173]
Testing #52859

When searching for a setting in the new settings editor it's not clear that the search has found anything, if the resulting item is in a group that isn't visible.

Suggestions:
- Scroll to the first item in the group list
- When clicking on a group that has a search result, don't show all the empty groups, but take me to the first item.

<img width="1552" alt="screen shot 2018-06-27 at 1 47 49 pm" src="https://user-images.githubusercontent.com/173559/41998988-02074bd6-7a11-11e8-9040-4ed107b0ea14.png">
<img width="1552" alt="screen shot 2018-06-27 at 1 47 54 pm" src="https://user-images.githubusercontent.com/173559/41998991-03d254f6-7a11-11e8-9a9e-6228ab4ce959.png">
<img width="1552" alt="screen shot 2018-06-27 at 1 47 57 pm" src="https://user-images.githubusercontent.com/173559/41998992-058e76f8-7a11-11e8-8ac4-0c6738f0234b.png">

VS Code version: Code - Insiders 1.25.0-insider (923e9ccb3fc44bfaaf4b4049015c84e42bc40f95, 2018-06-26T13:00:22.932Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
jsx|Twe|0.0.1
chrome-vs-code|fab|0.0.1
vscode-azureappservice|ms-|0.8.1
azure-account|ms-|0.4.1
debugger-for-chrome|msj|4.7.0
vscode-icons|rob|7.24.0

</details>

**Comment by roblourens** [comment]
@auchenberg you are using yesterday's build which had some issues with search, update to today's and try again.
