### ISSUE TITLE
Ctrl/Cmd+Down arrow from extension search box should focus extension list

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#53185]
We do the same for search, settings, keybindings, etc.

**Comment by JacksonKearl** [comment]
@roblourens Attempting to do `Ctrl+down` on settings (old and new) and keybindings in Insiders and not seeing anything happen. Just `down` works, but that conflicts with the normal use of `down` to reach the end of the input field. In Search however, `Ctrl-down` works and `down` takes you through history. Are we still in the process of moving to `Ctrl-down` everywhere or are we doing something else now?

**Comment by JacksonKearl** [comment]
Could we maybe rename `search.focus.nextInputBox` to just `editor.focus.nextInputBox` and use it everywhere?

**Comment by roblourens** [comment]
On input fields that don't have history like settings and keybindings, it's just down. We could add bindings for ctrl+down for those fields too to be consistent, although I like down a lot more anyway.

**Comment by roblourens** [comment]
I don't think it helps to have a common command for this because it's going to be different in every case.

**Comment by JacksonKearl** [comment]
Should extensions also be just down, given there's no history?

**Comment by roblourens** [comment]
I think so.

**Comment by sandy081** [comment]
Might be an issue if we want to show history in Extensions input box in future.

**Comment by ramya-rao-a** [comment]
Note to verifier: Down arrow from the extension search box is now expected to take you to the first result

**Comment by mjbvz** [comment]
Tested on MacOS, cmd down arrow goes to end of text box instead of focusing the list
