### ISSUE TITLE
unsaved changes lost on reload

### ISSUE THREAD

**Issue by msftrncs** [Microsoft/vscode#53181]
Issue Type: <b>Bug</b>

Upon downloading a new extension, offered the 'RELOAD' button, doing this lost changes to an changed (titled and previously saved) editor (which was not the focus of the extension) with no warnings.  An untitled editor remained as expected.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz (8 x 2794)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Memory (System)|15.91GB (9.98GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
mssql|ms-|1.3.1
csharp|ms-|1.15.2
PowerShell|ms-|1.7.0

</details>

**Comment by roblourens** [comment]
Could you try that scenario again to see if it happens every time?

**Comment by msftrncs** [comment]
Additional side note:  uninstalled the extension 1 last time, and hit reload, and my unsaved changes did not come back, even when switching focus back to the that editor.  I closed and reopened VS Code with that editor focused, and the unsaved changes returned, thankfully.   I think I will save them now.  :)

**Comment by Tyriar** [comment]
Can you share my settings.json file?

**Comment by msftrncs** [comment]
{
    "editor.renderControlCharacters": true,
    "editor.renderWhitespace": "all",
    "mssql.connections": [
        {
            "server": "...",
            "database": "WCT",
            "authenticationType": "Integrated",
            "profileName": "Work Completion Tracking",
            "password": ""
        },
        {
            "server": "...",
            "database": "ENG PARTS",
            "authenticationType": "Integrated",
            "profileName": "ENG PARTS",
            "password": ""
        }
    ],
    "mssql.format.keywordCasing": "uppercase",
    "window.zoomLevel": 0
}

**Comment by Tyriar** [comment]
Unfortunately I cannot reproduce this, I will keep an eye out for similar issues going forward.
