### ISSUE TITLE
Terminal follow link hover shows up while making a selection

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#53184]
Follow up on #37729

**Repo steps**
1. Open terminal
1. Run `echo http://example.com`
1. Start selection from left side of link. Keep cursor over link while slowly making selection 

**Expected behavior**
Click on link hover does not appear while making a selection

**Actual behavior**
If the cursor is over the link while making the selection, the hover message still will appear

**Comment by Tyriar** [comment]
Closing as out of scope as the only way to add this is to add selection events to xterm.js and they would be not very useful generally.
