### ISSUE TITLE
HTML attributes - only expand multiline when long

### ISSUE THREAD

**Issue by jabacchetta** [Microsoft/vscode#53187]
Currently there's a setting for `"html.format.wrapAttributes": "force-expand-multiline"`.

It'd be great if there was a similar setting: ` "html.format.wrapAttributes": "force-expand-multiline-long"`.

The idea being that it would only force expand if `html.format.wrapLineLength` was exceeded.

**Comment by aeschli** [comment]
Please file this against
We use [beautifyjs](http://jsbeautifier.org/) as the underlying HTML formatter. Would you mind filing this request directly against https://github.com/beautify-web/js-beautify ?
