### ISSUE TITLE
win10下触摸板滑动内容卡顿

### ISSUE THREAD

**Issue by zhl666** [Microsoft/vscode#53199]
Issue Type: <b>Bug</b>

win10下触摸板滑动内容卡顿，最大化或最小化操作后可暂时修复，过一段时间重新复现

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.63GB (2.91GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.3.2
vscode-language-pack-zh-hans|MS-|1.23.5

</details>

**Comment by roblourens** [comment]
> Win10 touchpad slide content carding, maximize or minimize the operation can be temporarily repaired, over a period of time to reproduce

Google translate is not helping here. Please give more details of exactly what your issue is.

**Comment by yunnysunny** [comment]
I met the same problem.
When scrolling the scrollbars in VS Code with touch pad of my windows 10 PC, it moves not smoothly.
But when I do the same operation with mouse's wheel, it moves smoothly.
And by the way, it also move smoothly , when I use touch pad to scroll in my chrome browser.
So , I guess something is wrong in VS Code for using touch pad.

**Comment by kzhui125** [comment]
I have the same problem on one of my computer(Win10).
On another PC it's normal.

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/13612
