### ISSUE TITLE
Clear `similar issues` when changing extensions in the issue reporter

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#53196]
**Steps to Reproduce:**

1. Open issue reporter
1. Select `an extension` as cause
1. Enter a generic title such as `a`
1. Select an extension with some issues
1. See `similar issues` get populated
1. Now select another extension with some issues

**Bug**
While the query is taking place, the old `similar issues` are still shown

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment]
I've just tried to reproduce this in the latest insider's and wasn't able to, so am going to go ahead and close this
