### ISSUE TITLE
Project Title

### ISSUE THREAD

**Issue by 1vipulp** [Microsoft/vscode#53198]
When some files are open in VC, then by hovering on visual code from windows bottom title bar, it is not showing the project title name full. If you can update this, then it will be great for user experience.

**Comment by roblourens** [comment]
Please give some more details, I don't understand.

**Comment by 1vipulp** [comment]
I will explain you with more details soon. I'm little bit buzy.

**Comment by roblourens** [comment]
Please update when you have time and I can reopen it.
