### ISSUE TITLE
Disable or enable an installed extension without relaunch vscode.

### ISSUE THREAD

**Issue by tangbc** [Microsoft/vscode#53197]
What about support this feature ?

**Comment by sandy081** [comment]
Verify that you can be able to disable an extension after installing it.

**Comment by roblourens** [comment]
@sbatten and I think that the actual request was not about disabling an extension right after installing it, but was probably a request to disable or enable an extension at any time and have that take effect immediately without reloading vscode. That probably won't happen any time soon.  

But I verified what you describe @sandy081 and it's still a good thing to have 👍

**Comment by sandy081** [comment]
@roblourens Yeah you are right... I misread the summary but agreed that the real feature is hard.
