### ISSUE TITLE
Settings editor input clipped on narrow editors

### ISSUE THREAD

**Issue by JacksonKearl** [Microsoft/vscode#53190]
![image](https://user-images.githubusercontent.com/8586769/42006173-321e406a-7a2d-11e8-9db5-c7fb918b8f22.png)

**Comment by roblourens** [comment]
Is this from resizing the window after selecting the setting row? Yes I have to remeasure the row when the window is resized...

**Comment by JacksonKearl** [comment]
Yes, resizing an active row after it has been selected. Clicking again triggers a resize and it will correct itself.
