### ISSUE TITLE
Identifying Camel Case Words in Keyboard Shortcut Word Skipping

### ISSUE THREAD

**Issue by tonyrusignuolo** [Microsoft/vscode#53191]
Issue Type: <b>Feature Request</b>

I frequently parse through code using Ctrl+arrow keys, but it skips straight over camel case words (i.e. "thingThing" or "camelCase"). I think it would be fairly helpful if VSCode could parse the individual words of a camel case word, so I don't skip over them when editing.

Thanks!

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 6.1.7601

**Comment by tonyrusignuolo** [comment]
I just found the Camel Case Navigation Extension. Sorry for wasting your time!

**Comment by roblourens** [comment]
No problem. I use that extension every day 😁
