### ISSUE TITLE
[php] backtick commands not colorized correctly

### ISSUE THREAD

**Issue by splatonov92** [Microsoft/vscode#532]
Hello.
It is not comment, it is selection all files from the directory
![screenshot from 2015-11-24 10 53 08](https://cloud.githubusercontent.com/assets/10979831/11360893/a9cc9f9a-9299-11e5-8b4d-6040c1b7b4a6.png)

**Comment by aeschli** [comment]
@splatonov92 Can you paste the problematic code here? Thanks a lot!

**Comment by splatonov92** [comment]
if (isset ( $_POST ['type'] ) && $_POST ["type"] == "shlam") {
		info ( "{$pref} remove mudlog index files" );
		$result = `$runTS rm -rf var/MudlogProxy/* && echo "OK"`;
		isError ( $result, "remove var/MudlogProxy", "attempt to delete var/MudlogProxy" );
		if ($plugin == "GeologProxy.jar") {
			$result = `$runTS rm -f var/GeologProxy/cuttings.dat var/GeologProxy/calcimetry.dat var/GeologProxy/descriptions.dat var/GeologProxy/lithology.dat && echo "OK"`;
			isError ( $result, "remove var/GeologProxy", "attempt to delete var/GeologProxy" );
		}
	}

**Comment by kurtcorbett** [comment]
This is also a problem with double forward slash in js. 

<img width="479" alt="screen shot 2015-11-30 at 7 50 03 pm" src="https://cloud.githubusercontent.com/assets/7966496/11491076/b0a4014e-979b-11e5-8101-e47677924cf4.png">

````
  const contentObj = {
    domain: uriObj.host,
    path: uriObj.path,
    longUrl: `${uriObj.protocol}://${uriObj.host}${uriObj.path}`,
    type: '',
  };
```

**Comment by mjbvz** [comment]
@splatonov92 Just checked in VSCode 1.9 and it looks like the original issue has been fixed:

<img width="819" alt="screen shot 2017-01-31 at 6 45 30 pm" src="https://cloud.githubusercontent.com/assets/12821956/22493520/843985d4-e7e5-11e6-9c69-c8c34257d434.png">


@kurtcorbett This also is now fixed:

<img width="593" alt="screen shot 2017-01-31 at 6 44 43 pm" src="https://cloud.githubusercontent.com/assets/12821956/22493501/5ca31832-e7e5-11e6-9207-6ed98c88b37c.png">
