### ISSUE TITLE
Improve sidebar optimal resizing

### ISSUE THREAD

**Issue by mquandalle** [Microsoft/vscode#5320]
I implemented sidebar optimal resizing in 65bdaf3. However some desirable characteristics of this feature were postponed due to some implementation challenges—namely, measuring not-yet-rendered DOM elements.  I’m opening this issue to keep track of these sub-features with the hope that they will be solved at some point.

---

(originate from https://github.com/Microsoft/vscode/pull/4702#issuecomment-205530593)
- [ ] `getOptimalWidth()` doesn’t work if the sidebar is closed, _ie_ you can’t double click on the closed sash to open the sidebar to its optimal width, which is expected;
- [ ] if the explorer list is too long, VSCode renderer will break the list into multiple “tiles” that won’t be displayed concurrently, thus `getOptimalWidth()` will only consider visible elements and not the entire list. For comparison, this is handled correctly by both Atom and SublimeText.

**Comment by bpasero** [comment]
:+1:

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
