### ISSUE TITLE
high GPU usage, and the VS Code stuck when I just press the key of up in terminal

### ISSUE THREAD

**Issue by yunnysunny** [Microsoft/vscode#53208]
- VSCode Version:1.24.1
- OS Version:win10

Steps to Reproduce:

1.I use the terminal in the vs code, and press the key of `up` to find the latest command I have input.
2. The VS Code stuck, and a alarm dialog show as follows:

![suck](https://user-images.githubusercontent.com/734818/42016776-5aa49216-7adf-11e8-8ec0-f60905b0e49b.png)

I also check the task manager, and found that VS Code use high GPU.

![high_gpu](https://user-images.githubusercontent.com/734818/42016815-80bc8ecc-7adf-11e8-850e-005adfe15626.png)

After been stuck many times, VS Code show a dialog to let change the way of the render of the terminal:

![render](https://user-images.githubusercontent.com/734818/42017270-ffb1b206-7ae0-11e8-8f0d-e5f74b260ec1.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/36913

Enabling the DOM renderer is the current way around this:

```
"terminal.integrated.rendererType": "dom"
```
