### ISSUE TITLE
Open picked definition in splitted screen

### ISSUE THREAD

**Issue by eastwing27** [Microsoft/vscode#53207]
Hey,

When you choose "peek definition" in popup menu you can open that in new tab (or same tab if it's in the same file). But from time to time you need to keep definition and file you just worked with opened at the same time. Sure it is possible to open splitted screen manually but it's an extra action and more extra actions if it is the same file. 

So it would be great if you add opportunity to split screen and open peeked code at the right hand by one click. 

Update
Same for "Find references" by the way

**Comment by eastwing27** [comment]
Is there some setting on it? If I ctrl+click on class name it just opens in new tab

**Comment by roblourens** [comment]
It works for me, what are you clicking on? The entry on the right side in the peek view?

**Comment by eastwing27** [comment]
Ooooh, didn't know that. Exactly what I need, thanks
