### ISSUE TITLE
Option to move the Problems Filter out of tab strip when docked as sidebar

### ISSUE THREAD

**Issue by zspitzer** [microsoft/vscode#53200]
The problems tab includes a filter text input, which when docked as a sidebar hides
all the other tabs (search etc) it even hides the Problems title. 

Could we have an option to move that filter input to a secondary row when displayed in a sidebar?

![image](https://user-images.githubusercontent.com/426404/42011294-263b205c-7ad6-11e8-83ed-e51357f95a86.png)

**Comment by sandy081** [comment]
![Kapture 2019-11-06 at 19 10 57](https://user-images.githubusercontent.com/10746682/68325330-6fa91580-00c9-11ea-84b9-fc63ed015aa3.gif)
