### ISSUE TITLE
Integrated with SVN

### ISSUE THREAD

**Issue by am54ful** [Microsoft/vscode#53202]
Need integrated with SVN. I've tried the extension but no luck. So why not just integrated with SVN fro VSCode? The only thing left is that and I would say VSCode is the best amongst editor

shortcut key to open file, jump line, with cmd or terminal, colour themed branded, easy to zoom with mouse scroll

**Comment by Tyriar** [comment]
We defer SCM support other than git to extensions. We want to keep the core slim and fast.
