### ISSUE TITLE
allow custom sort function depending on filetype

### ISSUE THREAD

**Issue by e110c0** [microsoft/vscode#53201]
currently,  "sort lines ascending" sorts alphabetically caseinsensitive.
While this makes sense most of the time, there are case where a more specific ordering would be preferable,

## Example: Sass/CSS ordering

when sorting in Sass/Css files, the current sorting order is a counter intuitive:
```
border: ...
border-radius: ...
```

will become
```
border-radius: ...
border: ...
```

because it orders '-' before ':' but in this specific case, it's preferable to go from generic to specific, i.e. ordering border before border-radius.

with a way to provide a custom sort function (or have some to choose from) would allow to get this way of sorting

**Comment by e110c0** [comment]
#48123 is similar (requesting ASCII compare instead of localeCompare) but this would not resolve this specific situation since - (45) comes before : (58)

**Comment by alexandrudima** [comment]
This could be implemented from an extension. Specifically, for CSS, a formatter could be written that always sorts properties in a certain order ...
