### ISSUE TITLE
Smaller update size of code & code-insiders

### ISSUE THREAD

**Issue by nascarsayan** [Microsoft/vscode#53203]
Presently, whenever the package needs to be updated, we need to fetch the *whole new version* , and install the new version over the existing version, and then the old package is deleted. <br><br>Is it possible to fetch just the changes, saving internet bandwidth?<br> Fetching almost daily updates for vscode-insiders expending **~50Mb** of data is really inconvenient.

**Comment by joaomoreno** [comment]
Unfortunately, while it's a good idea, it's not in our planning horizon.
