### ISSUE TITLE
Text selection in console

### ISSUE THREAD

**Issue by ayeressian** [Microsoft/vscode#5321]
- VSCode Version: 1.0.0
- OS Version: OSX 10.11.3

BUG 1
Steps to Reproduce:

1. console.log a huge text.
2. Try to select the text in console by using mouse.
3. Notice it will not scroll the console view.

BUG 2
Steps to Reproduce:

1. console.log some text.
2. Try to select the text in console by mouse drag.
3. Try to continue the text selection with keyboard. Holding shift and up arrow.
3. Notice when the selection reaches to the beginning of the console it will continue code selection in the code section from top to bottom.

**Comment by isidorn** [comment]
Thanks for the nice steps, however both bugs are dups of #2163
