### ISSUE TITLE
Outline doesn't show all items up

### ISSUE THREAD

**Issue by BankofFunny** [Microsoft/vscode#53210]
Issue Type: <b>Bug</b>
![gif2](https://user-images.githubusercontent.com/36688398/42017265-fb8a8dce-7ae0-11e8-9348-667db7623663.gif)

The last two items in outline was out of border when I clicked extension and clicked explorer back.
Change the size of outline window would make them show up again.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (11.07GB free)|
|Process Argv|D:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
include-autocomplete|ajs|0.0.4
arm|dan|0.2.0
vsc-material-theme|Equ|2.1.0
cpptools|ms-|0.17.5
material-icon-theme|PKi|3.5.0
vim|vsc|0.14.0

(2 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
This is fixed in latest [insiders](https://code.visualstudio.com/insiders/)
