### ISSUE TITLE
Incorrect Javascript function highlighting in HTML tag

### ISSUE THREAD

**Issue by aerchit** [Microsoft/vscode#53219]
- VSCode Version: 1.24.1
- OS Version: windows 10 64bits

![visual studio code](https://user-images.githubusercontent.com/17045080/42021507-65e969fe-7aed-11e8-9248-a1296315e0f5.png)

Steps to Reproduce:

1. insert this in html body
`<p onclick="add('p<br>');" >click me</p>`

2. use any color theme. **All of them cannot highlight correctly,** but Sublime Text can.

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
This issue was moved to textmate/html.tmbundle#86
