### ISSUE TITLE
"Find in folder" is only considering file contents

### ISSUE THREAD

**Issue by Kaedin** [Microsoft/vscode#53215]
Hi Developers,

I found out that a really useful feature today, "Find in folder" launched via context menu on selected folder in Explorer tab. However, seems that this search function is only able to search for contents of files.

For example, I have opened a folder "Forms" in Explorer tab and I would like to find files where term "language" is used. There are two files in the folder named as "language" and "languages". Both files are having almost the same contents but term "language" is only mentioned within the first file contents. As a result, "Find in Folder" is only displaying file "language" in the matches as the file itself has the corresponding term included.

Could this somehow be improved a little to include matches found in filenames as well? :)

Best regards,
Kaedin

**Comment by roblourens** [comment]
This is what quickopen (ctrl+p) is for. You can press ctrl+p, type 'language' and see all files with 'language' in the name or path.

I think that searching for filenames and contents are separate tasks and it makes sense to cover them with separate features.
