### ISSUE TITLE
Indentation settings not working

### ISSUE THREAD

**Issue by azrlucky** [Microsoft/vscode#53212]
Issue Type: <b>Bug</b>

After updating to VS Code v1.24.1 My indentaion settings stopped working. 

Steps to reproduce:
1. Change to below settings:
"editor.insertSpaces": false,
"editor.detectIndentation": false,
"editor.tabSize": 4,

still for every file, setting is space:2. Even when I click and change Indentaion to Tab:4 for a file, it switches back to space:2 when I go to other file and come back to the file.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:52:25.282Z)
OS version: Windows_NT ia32 10.0.10586

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz (4 x 3912)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Memory (System)|7.91GB (2.43GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.12
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.33
beautify|Hoo|1.3.2
angular2-switcher|inf|0.1.9
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-scss|mrm|0.6.2
debugger-for-chrome|msj|4.7.0
material-icon-theme|PKi|3.5.0
autoimport|ste|1.5.3

</details>

**Comment by kaiwood** [comment]
@azrlucky Try disabling the EditorConfig plugin and see if the settings now stick. It always comes last in the chain and sets the indentation settings to its default, even if VSCode is configured to something different.

**Comment by rebornix** [comment]
@azrlucky did you try @kaiwood 's suggestion and any luck with that? Did you also happen to open a workspace which have these settings?

**Comment by azrlucky** [comment]
@rebornix Yes it solved my issue. Kudos to @kaiwood
