### ISSUE TITLE
Change RegExp of mnemonic

### ISSUE THREAD

**Issue by EbXpJ6bp** [Microsoft/vscode#53217]
Issue Type: <b>Feature Request</b>

Related issue #52576

Can you change the RegExp of mnemonic in the custom menu? 
Because, some strings in transifex are not suitable for the custom menu (e.g. `(&T)`, not `(&&T)`).

Native menu supports both styles, also 41 strings adopt the single `&` style. So, I think it might be a good idea to support the (&T) style

![a](https://user-images.githubusercontent.com/8474118/42021369-63882ea4-7af5-11e8-905b-233d2d1ee5a0.png)

VS Code version: Code - Insiders 1.25.0-insider (07d89abf1522a67f0e8105770505077f454ab021, 2018-06-28T05:19:16.448Z)
OS version: Windows_NT x64 10.0.17134

**Comment by sbatten** [comment]
moving to august to decide if this is necessary as it looks like strings have been updated to support the more explicit && style
