### ISSUE TITLE
VS Live Share Global Search not woking

### ISSUE THREAD

**Issue by anik4e** [Microsoft/vscode#53228]
Issue Type: <b>Bug</b>

After sharing code via "VS Live Share" Search is not working. Please check this.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
OS version: Darwin x64 17.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5575R CPU @ 2.80GHz (4 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.14GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
jshint|dba|0.10.19
vscode-eslint|dba|1.4.12
php-debug|fel|1.12.3
node-debug2|ms-|1.21.1
vsliveshare|ms-|0.3.335
debugger-for-chrome|msj|4.7.0
vscode-icons|rob|7.24.0
wordpress-snippet|tun|1.1.2

</details>

**Comment by roblourens** [comment]
This isn't supported by Live Share yet. Please file other live share issues on their repo at https://github.com/MicrosoftDocs/live-share

**Comment by roblourens** [comment]
This isn't supported by Live Share yet. Please file other live share issues on their repo at https://github.com/MicrosoftDocs/live-share

**Comment by roblourens** [comment]
This isn't supported by Live Share yet. Please file other live share issues on their repo at https://github.com/MicrosoftDocs/live-share
