### ISSUE TITLE
Cannot scroll in menu bar dropdown list

### ISSUE THREAD

**Issue by davistran86** [Microsoft/vscode#53224]
Issue Type: <b>Bug</b>

Currently if I enable "window.titleBarStyle": "custom", there is no scrolling in menu dropdown list on my laptop, bottom of the list is hidding below windows taskbar. 

![image](https://user-images.githubusercontent.com/23651625/42024596-cbb1b9f4-7aec-11e8-9c91-1d25c60dc673.png)

VS Code version: Code - Insiders 1.25.0-insider (07d89abf1522a67f0e8105770505077f454ab021, 2018-06-28T05:19:16.448Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.85GB (0.70GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|2.1.0
terraform|mau|1.2.0

</details>

**Comment by sbatten** [comment]
same issue as #52533
