### ISSUE TITLE
Startup potentially spends a long time in statting the folder path

### ISSUE THREAD

**Issue by nntantidakis** [Microsoft/vscode#53221]
Issue Type: <b>Bug</b>

I use VSCode with mounted folders from Virtual machines(Samba share on Debian VMs). When i open VSCode and the previous opened folder cannot be mounted, VSCode takes 2 mins to open, and another 2mins to open the folder selection menu. Maybe add a setting that we can disable the auto-load of previous editing folder?

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz (12 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.91GB (25.82GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-intelephense-client|bme|0.8.8
php-intellisense|fel|2.3.3
vscode-phpfmt|kok|1.0.30
cpptools|ms-|0.17.5
savebackup|pur|0.0.3
vscode-arduino|vsc|0.2.17

</details>

**Comment by roblourens** [comment]
Please see this wiki page to help us figure out why vscode might be slow: https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by nntantidakis** [comment]
Let me remind you that this issue occurs when the folder is not mounted while i try to run VSCode, if it is mounted then its starts right away. To me it is a realtime problem as i work everytime with VPN and VMs(With samba share and i work as a mounted drive on Windows 10)

![2018-06-28_22-51-22](https://user-images.githubusercontent.com/37312505/42057383-d220a262-7b25-11e8-9327-090368ce0d47.jpg)

Whatever else you may need to resolve this issue please respond and i will gladly give the information you seek. 

- VSCode Version: <code>Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)</code>
- OS Version: <code>Windows_NT x64 10.0.17134</code>
- CPUs: <code>Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz (12 x 3400)</code>
- Memory (System): <code>31.91GB (27.35GB free)</code>
- Memory (Process): <code>165.30MB working set (208.35MB peak, 154.97MB private, 38.23MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>67%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|35|
|main|app.isReady => window.loadUrl()|63688|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|527|
|renderer|require(workbench.main.js)|1109|
|renderer|create extension host => extensions onReady()|537|
|renderer|restore viewlet|0|
|renderer|restore editor view state|2|
|renderer|overall workbench load|219|
|main + renderer|start => extensions ready|65941|
|main + renderer|start => workbench ready|65603|

---
[4c66-main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/2146754/4c66-main.cpuprofile.txt)
[4c66-renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/2146755/4c66-renderer.cpuprofile.txt)
[4c66-exthost.cpuprofile.txt](https://github.com/Microsoft/vscode/files/2146756/4c66-exthost.cpuprofile.txt)

**Comment by jrieken** [comment]
Yeah, looks like this is stuck on `statSync` for a minute...


<img width="732" alt="screen shot 2018-06-29 at 09 16 19" src="https://user-images.githubusercontent.com/1794099/42078522-1e974f04-7b7d-11e8-9fd1-ec3d59b5cf1d.png">

**Comment by bpasero** [comment]
Unhappy, but I also don't have a good idea how to fix this. When a window opens we try to restore the previous folder that was opened and we first check if it still exists. You cannot open VSCode on a folder that does not exist, so we prevent this from happening right from the beginning. We could in theory wait for e.g. 10s and then simply ignore the folder when we do not get a response in that time and open up empty.

**Comment by bpasero** [comment]
Somewhat related: once we allow to open remote folders from the command line we have to revisit this check probably too because we cannot stat a remote folder on startup.
