### ISSUE TITLE
extension development host: console log should also go in Extensions output and log

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#53229]
- Create a new extension with the following code:
```ts
'use strict';
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
    let disposable = vscode.commands.registerCommand('extension.sayHello', () => {
        console.log('Hello')
    });

    context.subscriptions.push(disposable);
}
```
- launch a extension development host
- run the 'Hello World' command
- open the Output view, `Extensions` tab: empty, `Log (Extension Host)`: empty
- The output is printed in debug console of the outer VSCode where the extension development host as launched, but I think it should also appear in the extension development host itself.

**Comment by roblourens** [comment]
I think the Extension Host output channel just shows logs from our EH code and it probably doesn't make sense to mix extension output in there, but we could add a new output channel for that. I think it would end up including logs from other extensions too (same as the debug console)

**Comment by roblourens** [comment]
I think this is out of scope, extensions can/will be able to explicitly log if they want a log. Ping @jrieken in case you disagree.
