### ISSUE TITLE
Debug: "Run" vs "Start" is very hard for me to understand

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#5323]
I find it very confusing that we have "Start" and "Run" commands in the palette and only one command exposed in the debug viewlet. For a user it is not clear at all which one connects the debugger and which one does not. 

I don't have good ideas how to solve this but some thoughts:
* expose both run and start in the viewlet (let the green arrow be a dropdown?)
* make it very clear (in the label?) that one connects the debugger and one does not
* use a different color in the status bar (not the orange)

@isidorn @weinand @stevencl @bgashler1 fyi

**Comment by bpasero** [comment]
Also bad: We show "Debug: Run" so I assume the debugger is connected. In fact, the debugger is not connected.

![image](https://cloud.githubusercontent.com/assets/900690/14558428/b7666224-0302-11e6-8818-32097566a630.png)

**Comment by bpasero** [comment]
I like what VS does:

![image](https://cloud.githubusercontent.com/assets/900690/14559360/78322826-0308-11e6-88e2-4d293d04612f.png)

Also, starting without debug does not change the status bar color.

**Comment by weinand** [comment]
@bpasero yes, I like the VS wording too.
@isidorn let's try this and do not change the status bar color.

**Comment by isidorn** [comment]
Very good points.
