### ISSUE TITLE
Integrated terminal's error on command "bundle exec jekyll serve" (doesn't occur and works as expected in external terminal)

### ISSUE THREAD

**Issue by akshaykhobragade** [Microsoft/vscode#53230]
- VSCode Version: 1.22.2
- OS Version: Arch Linux | Kernel: x86_64 Linux 4.16.13-1-ARCH

![error](https://user-images.githubusercontent.com/29286381/42029598-b7e4869e-7aed-11e8-8e2c-7b0db91ab01c.png)

Steps to Reproduce:

1. Run `bundle exec jekyll serve` (as normal user).

I'm filing the bug report because the error doesn't happen in gnome-terminal or xterm but only in the VSCode's integrated terminal. Plus, when the terminal is closed with `ctrl+d` this appears: `The terminal process terminated with exit code: 14`.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This is probably related to environment variables, can you try adding this setting?

```
"terminal.integrated.setLocaleVariables": true
```

**Comment by akshaykhobragade** [comment]
Yeah, it was a Locale issue. A reboot later `gnome-terminal` too stopped working but setting up the locale and regenerating it brought both one's back.

What does `"terminal.integrated.setLocaleVariables": true` actually do?

**Comment by Tyriar** [comment]
@akshaykhobragade glad it's fixed! `setLocaleVariables` tries to set a good `$LANG` environment variable value based on the app locale:

https://github.com/Microsoft/vscode/blob/ab21dfa0a9c56e05f3f4f380f16d4b1b673961a2/src/vs/workbench/parts/terminal/node/terminalEnvironment.ts#L91-L122
