### ISSUE TITLE
[loc][Query] Source text issue for "Lists contributions to VS Code by this extension"

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#53236]
For string below community member is asking if "by this extension" should not be "for this extension"? Can you please check? Thanks!

**Original comments**
FR ISSUE
by this extension => for this extension ?
by agriffard, a month ago

**Context**
src/vs/workbench/parts/extensions/electron-browser/extensionEditor:English (en):plaintext:contributionstooltip

**Resource**
vs_workbench_parts_extensions

**String text**
Lists contributions to VS Code by this extension

**Comment by sandy081** [comment]
No, its correct.

It is  view that shows all contributions by the extension to VS Code.
