### ISSUE TITLE
Feature: Enable static code analysis github integration (e.g. codefactor)

### ISSUE THREAD

**Issue by JonKohler** [Microsoft/vscode#53235]
Hey vscode team!

I was wondering if you would be open with enabling a static code analsyis engine integration with GitHub, like codefactor?

Looking around at other MS projects, it looks like the PowerShell team uses codefactor with good success, here: https://github.com/PowerShell/PowerShell

I forked vscode to my personal profile and enabled codefactor on it, and it looks like its getting really good results. You can check it out here: https://www.codefactor.io/repository/github/jonkohler/vscode

If codefactor is acceptable, Enabling this is crazy easy. Repo admin just needs to go to codefactor.io, signin and enable the repo (like other github integrated stuff)

**Comment by Tyriar** [comment]
We normally keep quality in check through the use of tslint rules/pre-commit hooks, I don't think adding this (or code climate) would add much value for us as we'd likely never look at the results.

**Comment by JonKohler** [comment]
@Tyriar - This isn't a tool that you have to go look at to see if it just so happened to find something, and then try to go fix it later.

It actually comes up right in the github checks API, and will tell you if there are issues found with the PR

See how the PowerShell team uses it, here: https://github.com/PowerShell/PowerShell/pull/7220

In that PR, it failed as the submitted sent in code that wasn't up to snuff, so now that PR is going to be held until it gets up to snuff.

This will help the case where someone doesn't apply the hooks correctly, or doesn't do the linting correctly, so all of that stuff will be cause pre-commit / pre-merge.

I agree that vscode quality is amazing, as I use it literally every single day for one thing or another, so I'm a huge fan.

I did enable codefactor on a fork @Tyriar ... https://www.codefactor.io/repository/github/jonkohler/vscode/issues

and it did find quite a few things, some of them low hanging, some others more nuanced, but good finds none the less.

**Comment by Tyriar** [comment]
But we already do these types of quality checks using linters which already run on our CI and tell us before merging, I think it would be simpler just to keep doing that and adding extra rules where it makes sense.

Also I've used Code Climate in the past and didn't find it that useful. It's mainly just a convenient way to get a bunch of linters running on your code, but if you're already running linters it doesn't add much imo.

**Comment by JonKohler** [comment]
ahha! ok, I misinterpreted your previous comment, this makes 100% now. Thanks for taking the time to respond, I really appreciate it, and keep up the good work! 

I've gotten to the point where I dont even use sublime or traditional visual studio anymore, just 100% vscode :)

**Comment by Tyriar** [comment]
@JonKohler nice, and thanks for taking the time to report an issue :smiley:
