### ISSUE TITLE
[ts] warnings are being shown in javascript files

### ISSUE THREAD

**Issue by brambow** [Microsoft/vscode#53247]
- VSCode Version: 1.24.1
- OS Version: MacOS 10.13.4

With the most recent update I am getting strange [ts] warnings in Javascript files. I do not use Typescript, so I'm not sure why I'm getting these messages.

Example.

![image](https://user-images.githubusercontent.com/6227786/42039705-002c7736-7abc-11e8-9b7d-3df36c0071d6.png)

Getting the [ts] warning is weird enough, but the error isn't even true. driveTimeLyr is referenced just a few lines below.

![image](https://user-images.githubusercontent.com/6227786/42039635-dac21ba4-7abb-11e8-936b-557fadc0efb3.png)

These warnings sometimes disappear if I close/reopen a file, but they eventually show back up. Any suggestions appreciated.

**Comment by mjbvz** [comment]
TypeScript powers js intellisense as well.

Does this the incorrect graying out issue reproduce in the [latest VS Code build](https://code.visualstudio.com/insiders/) with all extensions disabled? If it does, please share a complete example as text

**Comment by brambow** [comment]
Yes it occurs on the most recent Insiders build with extensions disabled. However, I'm having trouble reproducing it consistently.  Take the screenshot below. On the left is the original file, still showing the ts warnings, but the right side is the exact same file saved to a new name, no longer with the warnings.  I also noticed if I changed the file extension to .jsx the issue went away.  I'll keep testing to see if I can pinpoint the issue.

<img width="1280" alt="screen shot 2018-06-28 at 2 13 24 pm" src="https://user-images.githubusercontent.com/6227786/42052823-dc225d48-7add-11e8-985f-f42536d23db3.png">

**Comment by ehynds** [comment]
I'm seeing this as well. It typically happens after I've been using my editor for some arbitrary period of time (feels like an hour or so). Restarting usually fixes it.

**Comment by picanteverde** [comment]
it happens to me too, and yes restarting the window did it for me

**Comment by ddobson** [comment]
I'm also having this issue. Neither restarting nor disabling all extensions seems to fix it. I'm currently running 1.24.1 with a brand new project. 

<img width="1262" alt="screenshot 2018-07-03 10 51 18" src="https://user-images.githubusercontent.com/7988792/42236369-8d6203ae-7eaf-11e8-83de-e5ece7e7e338.png">

**Comment by mjbvz** [comment]
@brambow Have you been able to come up with reliable repo steps?
