### ISSUE TITLE
Markdown code blocks have two background colors

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#53246]
Looks kinda strange:

![image](https://user-images.githubusercontent.com/22350/42039554-f2d1751e-7aed-11e8-9d13-4b2feaa20e23.png)

**Comment by mjbvz** [comment]
Seems to be a regression. Will fix for June.

Repo:

1. Open markdown file:

~~~md
```js
const a = 1;
```
~~~

2. Open md preview
