### ISSUE TITLE
Menu: items jump when zoom-level is not 0

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#53248]
Steps to Reproduce:

1. configure the zoom level to be anything but 0
2. reload window and watch the menu bar
3. 🐛 it jumps a little bit after reload is done

![before](https://user-images.githubusercontent.com/900690/42039752-6991988c-7aee-11e8-8d7a-38bcb39c5752.gif)

**Comment by sbatten** [comment]
resolved since menubar now zooms with the rest of UI

**Comment by sbatten** [comment]
@wsmelton it is available in the latest insiders but you must enable the new custom menubar by setting `window.titleBarStyle` to `custom` in your `settings.json`

**Comment by wsmelton** [comment]
Ah, sweet...love that view and the emjois I add finally show up in color...that is what I was missing for that to work right as well. Much appreciated!
