### ISSUE TITLE
Menu: should we merge menubar and titlebar?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#53244]
I think one of the reason for keeping the two parts was to:
* separate concerns
* potentially allow to have the menu appear below the title (via setting?)

However the current solution makes it hard to get this right because you need to position the menu absolutely over the title bar (e.g. this triggers https://github.com/Microsoft/vscode/issues/52905).

I wonder if we should ditch the support for having the menu on a separate line and just merge the two parts into one again. I think all the code of the menu should still be in a separate file and just be instantiated from the title bar. 

The advantage of this approach is that a lot of layout complexity would go away, e.g. I would not expect that you need to layout the menubar using math at all, but you should be able to layout everything nicely with just one flex layout in the title bar area.

**Comment by TomSputz** [comment]
As I see it, the menubar being a separate element could be very useful, enabling better placement for usability if required, but I understand that this could be seen as non-essential.

Having them separate isn't causing issues with placement though, at least not directly. I checked the css for the custom titlebar when I noticed [this issue](https://i.imgur.com/dkGAJrQ.png) (Will add link to issue id when I make it), and it is very badly made, with the padding for the window name overcompensating massively, I'm happy to make a PR soon, once I'm sure my code isn't breaking any of the TypeScript as I don't know much about it

**Comment by bpasero** [comment]
Oh I would still keep it separate, but I would like to get rid of the absolute positioning and custom layout done in JS. Instead it should all just be one row of elements with a `flex` layout.

**Comment by sbatten** [comment]
@bpasero things would simplify in `layout.ts` but we still need the absolute positioning to center the title when possible. i.e. when the menubar doesn't touch the middle of the titlebar we can still center the title in the window, not the remaining space.

**Comment by bpasero** [comment]
@sbatten sorry, I do not follow that rationale, I would center the title between menubar and window controls and let the title shrink when size is little, then let the menubar shrink so that the window controls take over.

**Comment by sbatten** [comment]
@bpasero when the window is large enough to show all parts of the title bar and still center the title on the window width(not the space between the menubar and controls) we should

**Comment by bpasero** [comment]
@sbatten understood, here is an idea after talking with @joaomoreno about this:
* if the window is small, do not use any absolute positioning, just put the menu, title and controls in divs with a flex layout. the title should be centered between menu and controls and should be the first one to disappear when the size gets smaller. after that, the menu should disappear until only the window controls are visible
* if the window is large, put the title absolutely positioned in the center of the title area. leave the menu and the window controls using flex layout without absolute positioning

**Comment by joaomoreno** [comment]
I also suggest to never use `order` and simply rely on DOM order. Keeps things easier to maintain.

**Comment by sbatten** [comment]
@bpasero @joaomoreno There is also the case of full screen mode with the menubar set to visible. In this case the titlebar part is no longer present, but the menubar should be.
