### ISSUE TITLE
Queue ext host terminal onData events when terminal ID is not yet set

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#53251]
https://github.com/Microsoft/vscode/blob/7396416d7a35f1a4187c558dc050908d60a1f632/src/vs/workbench/api/node/extHostTerminalService.ts#L294

**Comment by mjbvz** [comment]
Verification steps?

**Comment by alexr00** [comment]
Verification Steps:
Create an extension with this command:

    context.subscriptions.push(vscode.commands.registerCommand('terminalTest.createAndSend', () => {
		const terminal = vscode.window.createTerminal(`Ext Terminal #${NEXT_TERM_ID++}`);
		if((<any>terminal).onDidWriteData) {
			(<any>terminal).onDidWriteData(data => {vscode.window.showInformationMessage('Hello World!');});
		}
		terminal.sendText("echo 'Sent text immediately after creating'");
	}));

When you execute the command, confirm that the 'Hello World!' info message shows. Do this five or so more times since this is a race condition.
