### ISSUE TITLE
New Settings Editor: "Modified in: Workspace" shows up erroneously

### ISSUE THREAD

**Issue by JacksonKearl** [Microsoft/vscode#53258]
Issue Type: <b>Bug</b>
Saw this happening with many different settings (Mouse Scroll Wheel Sensitivity, Font Family, Font Ligatures, Word Separators, Debug Tool Bar Location, File Explorer: Open Editors Visible, Git: Enable Smart Commit, etc.) , but a reliable repro seems to be:
```
{
	"files.autoSave": "onFocusChange",
	"editor.formatOnSave": true,
	"editor.minimap.enabled": false,
	"extensions.ignoreRecommendations": false,
	"editor.renderWhitespace": "boundary",
	"workbench.view.alwaysShowHeaderActions": true,
	"editor.fontFamily": "Hasklig",
	"editor.fontLigatures": true,
	"search.smartCase": true,
	"editor.fontSize": 14,
	"window.zoomLevel": 0,
	"editor.cursorStyle": "line",
	"editor.multiCursorModifier": "ctrlCmd",
	"tslint.autoFixOnSave": true,
	"tslint.jsEnable": true,
	"tslint.packageManager": "yarn",
	"editor.matchBrackets": false,
	"editor.overviewRulerBorder": false,
	"workbench.editor.showIcons": false,
	"explorer.openEditors.visible": 0,
	"editor.accessibilitySupport": "off",
	"debug.toolBarLocation": "docked",
	"editor.wordSeparators": "`~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?",
	"window.enableMenuBarMnemonics": false,
	"window.titleBarStyle": "custom",
	"git.enableSmartCommit": true,
	"editor.mouseWheelScrollSensitivity": 5,
	"editor.multiCursorMergeOverlapping": false,
	"css.lint.unknownAtRules": "ignore",
}
```
This with the vscode workspace settings gives:
- Title bar style
- Css lint: unknown at rules
- Word Separators
- Format on save
- Font Size
- Cursor Style

as being "Modified in: Workspace", when none of them are

VS Code version: Code - Insiders 1.25.0-insider (f2fa6bea46bde9856e6a593e4d4c5af2b303ac66, 2018-06-27T05:18:12.763Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (8.03GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.4.1
tslint|eg2|1.0.33
haxe-hl|Hax|0.3.0
debugger-for-chrome|msj|4.7.0
vshaxe|nad|2.0.1
subtle-brackets|raf|2.1.1
vscode-multiclip|sle|0.1.4
code-spell-checker|str|1.6.10
haxe-debug|vsh|1.2.0
haxe-extension-pack|vsh|1.1.0
codedox|wig|1.2.7

</details>

**Comment by JacksonKearl** [comment]
I notice when I switch form user settings to workspace settings and back, more showed up:
- Multi Cursor Modifier
- Font Family
- Minimap enabled
- Match brackets
- Editor Management: show icons
- Window: enable menu bar mneumonics


etc...

**Comment by roblourens** [comment]
I fixed something but I don't know whether it's exactly what you were seeing. Try again tomorrow
