### ISSUE TITLE
Editor buffers readonly status doesn't change after changing file system provider

### ISSUE THREAD

**Issue by IlyaBiryukov** [Microsoft/vscode#53256]
Issue Type: <b>Bug</b>

1. In extension, register a custom read-only `FileSystemProvider`.
2. In VSCode open a file from that work space. The file will open read only as expected.
3. In extension dispose of the file system provider and re-register another one for the same scheme, this time not read-only.
4. Run `workbench.files.action.refreshFilesExplorer` command.

Expected:
The editor changes and becomes read-write.

Actual:
The editor stays read-only, even if I close it and re-open it.

VS Code version: Code - Insiders 1.25.0-insider (5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3, 2018-06-25T09:40:10.343Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (12.25GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe C:\src\cascade\vscode\extension|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.17.5
csharp|ms-|1.15.2
vsliveshare|ms-|0.4.0-dev

</details>

**Comment by isidorn** [comment]
Thanks for creating these issues. I will look into this in July 
fyi @jrieken

**Comment by isidorn** [comment]
@jrieken thanks, on that event I need to clear my explorer model it seems

**Comment by jrieken** [comment]
yeah, maybe. tho I'd say you are mostly driven by the workspace config (which should probably listen to this event)

**Comment by isidorn** [comment]
@jrieken I found it weird that the workspace context service fires an `onDidChangeWorkspaceFolders` once a new file system provider is registered. For now I decided to listen on that event directly from explorer.
