### ISSUE TITLE
Settings Editor Scaling

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#53255]
Issue Type: <b>Bug</b>

When I zoom the settings UI I see some cropping of the new UI.  I also don;t see it laid out to the edge in most cases - here are a few images...

![image](https://user-images.githubusercontent.com/1051190/42047624-aa24925c-7ab5-11e8-9601-eb77d739e25a.png)

Zoom and then window reload...

![image](https://user-images.githubusercontent.com/1051190/42047661-c8b9a540-7ab5-11e8-81f3-a24c240d9aed.png)

VS Code version: Code - Insiders 1.25.0-insider (07d89abf1522a67f0e8105770505077f454ab021, 2018-06-28T05:19:16.448Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (7.18GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.4.1
rest-client|hum|0.19.0
markdown-table-formatter|jos|0.2.3
vscode-azurefunctions|ms-|0.9.1
mssql|ms-|1.3.1
python|ms-|2018.6.0
azure-account|ms-|0.4.1
cpptools|ms-|0.17.5
Go|ms-|0.6.83
java|red|0.27.0
todotasks|san|0.5.0
kustovscode|sea|0.0.4
vscode-java-debug|vsc|0.10.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.7.0
vscode-maven|vsc|0.9.0

</details>

**Comment by roblourens** [comment]
I remember seeing something like this in the past but it works fine for me now. Can you show me next time you're in the room?
