### ISSUE TITLE
Enable progressive selection (up/down) for multi-edit

### ISSUE THREAD

**Issue by Ettery** [microsoft/vscode#53266]
I absolutely love the ability to select a character sequence and see all matching sequences highlighted, then press `Ctrl-Shft-L` to edit them all at the same time - stand-out feature for me.  But quite often, I don't want to edit all matches in the file - I may only want to edit those in the current function or block.  It gets a bit painful to select these with the mouse.

I think a great (and easily implemented?) feature would be to be able to successively select matching sequences above or below my original selection with a key combination - say `Ctrl-Shft-Down` or `Ctrl-Shft-Up`.

For example, I have a function with 10 instances of the string `isValid` in it.  I want to edit them all, but not the other instances of `isValid` in the file.  With this feature implemented, I could:

1. Select the first instance of `isValid` in the function
1. Press `Ctrl-Shft-Down` nine times
1. Edit away around all 10 instances of `isValid`!

**Comment by idanpa** [comment]
I wrote an [extension for context aware multi-cursor](https://marketplace.visualstudio.com/items?itemName=idanp.smartmulticursor).
But the flow you describe can be done with just ctrl+d (Add Selection To Next Find Match).
