### ISSUE TITLE
Keyboar maping issue when run through ssh tunnel

### ISSUE THREAD

**Issue by lloydbpark** [Microsoft/vscode#53265]
I sometimes run VSCode 1.24.1 on an Ubuntu VM using ssh and XQuartz on my OS X laptop. When I do some keys do the wrong thing or don't work at all.  Disabling extensions doesn't fix the issue.   VSCode runs fine when used on the VM's local display. 

I found a Stack Exchange article that described a similar issue (#24107) in VSCode 1.11 that was fixed in 1.12.  The posted 1.11 workaround: "keyboard.dispatch": "keyCode" fixed it for me.

**Comment by roblourens** [comment]
So there are no problems when using `"keyboard.dispatch": "keyCode"`? Then I think that's the right solution. Also see https://github.com/Microsoft/vscode/wiki/Keybinding-Issues for troubleshooting tips.
