### ISSUE TITLE
Debug: consider to drop support to run extension without debugging

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#5326]
I find the distinction between "Run" and "Start" very confusing for a user (see https://github.com/Microsoft/vscode/issues/5323).

I suggest for extension development to do the same thing regardless of pressing "Run" or "Start" or indicate that the one is not supported.

What is the use case for running an extension without debugging from VS Code?

@isidorn @weinand fyi

**Comment by weinand** [comment]
@bpasero use case: I do not want to hit breakpoints and exceptions.
