### ISSUE TITLE
MAC installer "broken" when being verified and sent to Trash

### ISSUE THREAD

**Issue by Karrezza** [Microsoft/vscode#53261]
https://go.microsoft.com/fwlink/?LinkID=620882   I have downloaded from this location twice
both times when verifying package after unzipping, it is deemed damaged and sent to trash.

Where do I get a functioning .DMG file for my mac for VSCode?

**Comment by roblourens** [comment]
Works for me. It's a zipped .app, not a .dmg. MacOS/Finder says it's damaged?

**Comment by roblourens** [comment]
This is the official download link from code.visualstudio.com right?

**Comment by Karrezza** [comment]
Well it comes down as a .zip file, Mac extracts it, I assumed a .dmg file,
just the extension I am used to, but either way,
it extracts fine then double clicking app icon, it pops up saying that its
broken and to recommend sending to Trash.
I tried the Insider and stable default download link, and the direct link.

68.6 mg file size zipped.
I click to unzip.
Click on the App, Visual Studio Code. It does a "Verifying Visual Studio
Code"
It fails saying it is "broken".
I am a QA software tester so I usually do not report, until I reproed at
least 3 times, which I did.

So, just testing again to get accurate info for you,  the 4th time it has
now worked, but I didn't double click on it.  The only thing I did
differently, is I right clicked on the app icon and chose "Open".
I wonder if that runs it "as admin" like on Windows, though I am an admin,
on this Mac.

The app came up, took a bit, but I will now test to see it works as
expected.

Thank you for answering though.


_________________________________________________________

*Elizabeth A. Chubbuck  (built circa "67-"68)        *

*__________________________________________________*



*"MOTIVATION: If a pretty picture and a cute saying are all it takes to
motivate you, you probably have an easy job. One that robots will be doing
soon." ~Despair.com*

**Comment by Karrezza** [comment]
I used the go.microsoft.com links, but it seems to have worked as you will
see my other reply

Thanks again.


_________________________________________________________

*Elizabeth A. Chubbuck  (built circa "67-"68)        *

*__________________________________________________*



*"MOTIVATION: If a pretty picture and a cute saying are all it takes to
motivate you, you probably have an easy job. One that robots will be doing
soon." ~Despair.com*
