### ISSUE TITLE
Block labels in JS are faded out as "unused"

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#53269]
![image](https://user-images.githubusercontent.com/323878/42057321-db1a466a-7ad1-11e8-9ab2-f98ea2cd485b.png)

The block label is faded out as "unused", which doesn't seem right. Why would it be used or unused?

From #51264

**Comment by mjbvz** [comment]
We marked it as unused if the label is not referenced anywhere. Adding `break foo` somewhere in the program will cause it to become referenced. 

Is this what you see?

**Comment by roblourens** [comment]
Oh, that makes sense. Thanks
