### ISSUE TITLE
VSCode freezes after most recent update

### ISSUE THREAD

**Issue by ajkandy** [Microsoft/vscode#53274]
- VSCode Version: 1.24.1
- OS Version: Windows 7 Professional Build 7601, SP1 64-bit 

Steps to Reproduce:

1. Launch VSCode
2. Open any folder 
3. Open the Integrated Terminal
4. Attempt to type anything in Integrated Terminal
5. Nothing appears in Terminal at the cursor prompt
6. Within a second or two, entire computer seems to slow down; then a popup appears noting that VSCode has become unresponsive. Selecting Reopen does not change this issue.
7. Setup was working correctly recently, no major changes made to computer, no other software displays this issue

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
@ajkandy @wayspurrchen do you get this notification? I can only reproduce a big slowdown (on various operating systems) and then this notification will appear with the workaround to the problem.

One idea here is to be much more aggressive and automatically switch the user over as I've seen many reports of users ignoring the prompt.

**Comment by ajkandy** [comment]
I didn't see that notification regarding high GPU usage, but then again I wasn't looking for it. I will double-check when I'm back at the office on Monday.

**Comment by wayspurrchen** [comment]
I had to open Process Explorer to view the high GPU, so you didn't miss it; seems like a similar case to #36913.

**Comment by Tyriar** [comment]
@ajkandy you need to have rendered 11+ frames in the terminal before it will show, that's used to get a reasonably reliable number for how long rendering takes.

**Comment by ajkandy** [comment]
Thanks @Tyriar. I will see if the behaviour persists. Wondering if this is something due to Win7 and/or it not talking to my graphics card properly... Let me know if you need more info and what I'd need to do to get it to you.

**Comment by Tyriar** [comment]
@ajkandy thanks. On the weekend I pushed a change that allows the renderers to be swapped in and out without restarting the terminal, so pressing the notification should immediately fix the problem. The next step on my side is to automatically switch over to the fallback when it's detected as slow, this is deferred to next month though.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/56628
