### ISSUE TITLE
Surround with ( for Live Templates )

### ISSUE THREAD

**Issue by Shadowbrokerz** [Microsoft/vscode#53276]
In Jetbrains, you've got the ability to create live templates for most languages. What I found really useful as an example:

console.log($SELECTION$);

With this I had the chance of either, typing "cl" and that would complete the sentence for me and having the cursor inside the brackets, I think this is possible already, but what I also really like, is that by using $SELECTION$ I can also press CTRL+ALT+J having selected a line/word and I get a Surround with menu and console.log will show up so that would surround whatever I highlighter with that. I really love that feature and it saves some time. I'd love to have this in VSCode

**Comment by roblourens** [comment]
It sounds like you are describing "snippets" in vscode. It's possible to have a snippet that wraps the selection in whatever code you want. Check it out: https://code.visualstudio.com/docs/editor/userdefinedsnippets
