### ISSUE TITLE
Clicks pass through when refocussing a window that's lost focus on OS X

### ISSUE THREAD

**Issue by IsaiahJTurner** [Microsoft/vscode#53273]
Standard usability patterns on OS X dictate that clicking on a window which is not focussed will refocus the window without triggering any action on that window (except for the close/minimize/maximize Buttons). You can observe this pattern on Safari, App Store, Slack, Atom, Spotify, Mail, and almost all other Mac apps.

VS Code seems to have overlooked this usability pattern. I've attached a video to demonstrate how this creates a bad user experience.
[Disruptive.zip](https://github.com/Microsoft/vscode/files/2147076/Disruptive.zip)

 

- VSCode Version: 1.24.1
- OS Version: OS X 10.13.5

Steps to Reproduce:

1. Open VS Code
2. Open a new application (VS Code will lose focus)
3. Click a button/anywhere on VS Code (while it is not focussed)
4. Button click is received

Expected Behavior:

1. Open VS Code
2. Open a new application (VS Code will lose focus)
3. Click a button/anywhere on VS Code (while it is not focussed)
4. Button click is ignored, VS Code regains focus
5. Click again to trigger button click

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@IsaiahJTurner you will see that this pattern is not "standard" by any means if you e.g. run TextEdit and see that you can click on elements in the toolbar without making the Window focused first. The same is true with Xcode for example.

We decided that it makes sense for an editor to be usable without making the window focus first. And it seems other editor related applications behave the same from Apple. If you do not like that you can turn it off via `"window.clickThroughInactive": false`
