### ISSUE TITLE
Debugging golang barely works.

### ISSUE THREAD

**Issue by FrankSzendzielarz** [Microsoft/vscode#53271]
Steps to Reproduce:

1. Download geth source
2. Build and run
3. Debug.

Latest Delve, Golang, etc.

Symptoms: Stepping through code seems to skip back and forth as though threads were switching. Hardly any variables show the right values. Adding watches either crashes the IDE (ie nothing appears) or shows "unavailable". 

Totally unusable.

**Comment by weinand** [comment]
Please file this issue against the go extension.
