### ISSUE TITLE
Setting section "outline" should be capitalized as "Outline"

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#53283]
- VSCode Version: 1.25 Insiders
- OS Version: Windows 10

In the Default User Settings UI, other section begin with a capital letter. "outline" should do the same for consistency.

![image](https://user-images.githubusercontent.com/12818376/42067756-c61df966-7afc-11e8-8dba-d6ee5443ff75.png)

**Comment by gregvanl** [comment]
Looks like registerConfiguration in  src\vs\workbench\parts\outline\electron-browser\outline.contribution.ts is missing a title value and so the settings editor is showing the id.

**Comment by gregvanl** [comment]
Possible fix in https://github.com/Microsoft/vscode/pull/53285

**Comment by jrieken** [comment]
fixed via #53285
