### ISSUE TITLE
Linked snippets

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#53280]
**Feature request**
API to insert multiple snippets in a file so that the the placeholders of these snippets are connected together.

Example using this to reimplement rename:

1. Start with the js:

```js
const a = 1;
console.log(a)
```

1. Trigger rename on `a`

1. VS Code inserts linked snippets `${1:a}` at all locations effected by the rename:

```
const ${1:a} = 1;
console.log(${1:a})
```

As the user completes the placeholder value, both locations are updated in the file as they type. 

**usage cases**
Refactorings  that require user input, such as extract constant or extract function

**Comment by jrieken** [comment]
The new'ish `SnippetTextEdit` is exactly that
