### ISSUE TITLE
Custom titlebar should apply to all windows (Process Explorer, Report a bug, Dialogs...)

### ISSUE THREAD

**Issue by Astrantia** [microsoft/vscode#53282]
- VSCode Version: 1.25 Insiders
- OS Version: Win10

Steps to Reproduce:

1.Open `About`
2.Notice title bar isn't styled
![image](https://user-images.githubusercontent.com/32885386/42067243-3adca866-7b56-11e8-84a3-5a3135dbf299.png)

I don't if this is extra and not really needed, but the appearance is really inconsistent with custom title bar. I think if users choose custom title bar all pop-ups should inherit the new custom style.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
This would be nice to have, but nothing critical imho.

**Comment by bpasero** [comment]
@sbatten yes that is correct
