### ISSUE TITLE
Can’t uninstall user-level code installation without admin privileges 

### ISSUE THREAD

**Issue by JacksonKearl** [Microsoft/vscode#53284]
unins000.exe is from an unknown publisher

**Comment by JacksonKearl** [comment]
![image](https://user-images.githubusercontent.com/8586769/42067917-c45650c8-7afd-11e8-946a-e2259c0a59c2.png)

**Comment by joaomoreno** [comment]
Oh it really seems like you can't uninstall it... Not good.
