### ISSUE TITLE
Regarding the color transfer issue

### ISSUE THREAD

**Issue by kapnarola123** [Microsoft/vscode#53296]
Issue Type: <b>Feature Request</b>

Color transfering taking time to display original code color according to selected color theme. 

When i save the my long file there is at least 3000 lines and
It is displaying first whole page with white texts only and then after it will change color.

Would be really great fix some thing with this issue.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 6.3.9600

**Comment by rebornix** [comment]
Our tokenizer and highlighter is line based and it starts from the first line to the last. Improving the speed and syntax highlighting is always on our radar so we can close this issue.
