### ISSUE TITLE
前端项目，程序打开一段时间后，错误提示、代码提示等消失，重启程序又会正常。

### ISSUE THREAD

**Issue by hotinhot** [Microsoft/vscode#53291]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
> In the front-end project, after the program is opened for a period of time, error messages, code hints, etc. disappear, and the restart process will be normal.

Which language? JS/TS?
