### ISSUE TITLE
`workbench.action.terminal.rename` does not return focus to element that was focused when command was issued

### ISSUE THREAD

**Issue by pgrunwald** [Microsoft/vscode#53294]
- VSCode Version: Version 1.24.1 (1.24.1)
- OS Version: Mac OS 10.13.5

Current Behavior:
* After confirming or cancelling the "Enter terminal name" dialogue box, the focus is always returned to the "first editor", regardless of where the focus was when the `workbench.action.terminal.rename` command was issued.

Expected Behavior:
* After confirming or cancelling the "Enter terminal name" dialogue box, the focus should return to wherever the focus was when the `workbench.action.terminal.rename` command was issued.

Steps to Reproduce:
1. Focus on the terminal (terminalFocus == true)
2. Issue `workbench.action.terminal.rename` command
3. Input new name for terminal session and press "enter" to accept
4. Dialogue box closes, but focus is now on the first editor, rather than the terminal

or

1. Focus on the terminal (terminalFocus == true)
2. Issue `workbench.action.terminal.rename` command
3. Press "escape" to cancel
4. Dialogue box closes, but focus is now on the first editor, rather than the terminal

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
@bpasero I think we've spoken about returning focus after a command is canceled before, can't seem to find the issue though. Do you know which one it was?

**Comment by bpasero** [comment]
@Tyriar https://github.com/Microsoft/vscode/issues/44722
