### ISSUE TITLE
New autoReveal setting for explorer

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#5329]
- [x] any OS @isidorn - OS X
- [x] any OS @gregvanl - Windows

There is now a new setting `explorer.autoReveal` to prevent the explorer (not working files) from revealing the currently active file of the editor.
* verify changing this option prevents the explorer from automatically revealing the active file when you switch between files (e.g. from working files)
* verify you have a global action to reveal the active file and it does just that

**Comment by stephenmartindale** [comment]
This is listed in the release notes for v.1.0.1-insider but it isn't working for me, on that version.

**Comment by bpasero** [comment]
@stephenmartindale did you try `explorer.autoReveal: false` in settings?

**Comment by stephenmartindale** [comment]
This is what I have:
`
"explorer.autoReveal": false,`

**Comment by stephenmartindale** [comment]
Wait - I've worked out what is going on: The explorer is simply redrawing the selection rectangle which makes it look like it is revealing the file - it isn't actually scrolling.

To be perfectly honest, the fact that it is not scrolling is enough. Perhaps the documentation should simply be clearer - this setting disabled scrolling, not revealing of the file.
