### ISSUE TITLE
Can not sync files to VSTS anymore

### ISSUE THREAD

**Issue by viralnaik77** [Microsoft/vscode#53299]
Issue Type: <b>Bug</b>

Hi there, i am no longer be able to sync my changes to VSTS anymore.
I was able to save it and sync it 3 days ago.  I have recently updated the VSC to latest version. 

Once I click on sync icon its asks me to provide the username and password for Git:company.visualstudio.com (Press 'enter' to confirm or 'Escape to cancel').

This was never asked 3 days ago, and even if I enter the correct username and password, it throws error
Git: Logon failed, use Ctrl+c to cancel credential prompt.

``

I recently updated to below version, not sure if its related.
Version 1.24.1
Commit 24f62626b222e9a8313213fb64b10d741a326288
Date 2018-06-13T17:51:32.889Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Please help.
-Viral

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.14393

**Comment by joaomoreno** [comment]
You probably had it setup with a PAT, which has expired. Have you tried recreating a new PAT and using that as auth?

**Comment by viralnaik77** [comment]
Yes i get the same error
PS C:\Data\VSTS\SharePoint_Operations> git pull
Logon failed, use ctrl+c to cancel basic credential prompt.

username:
password:
fatal: Authentication failed for <URL>
