### ISSUE TITLE
Application menu does not display bottom line about last file

### ISSUE THREAD

**Issue by muyu66** [Microsoft/vscode#53293]
- VSCode Version: 1.24.1
- OS Version: Windows10 Home x64 1803

Steps to Reproduce:

1. click VSCODE menu "File"
2. click sub menu "open lastest File"
3. we can find that all Program name with "_" become to " "

such as ,  program name is "user_center",  but i see it's "user center"

maybe be  "Chinese (Simplified) Language Pack for Visual Studio Code" 's issue.

**Comment by roblourens** [comment]
Can you include a screenshot?

**Comment by roblourens** [comment]
Does it show up when the language mode is English?

**Comment by muyu66** [comment]
how to display English in VSCODE without change my SYSTEM? I don't find this option in Preference

**Comment by yume-chan** [comment]
<kbd>F1</kbd>, 配置显示语言 (Configure Display Language), change "zh-CN" to "en", restart code

**Comment by sbatten** [comment]
@muyu66 I am unable to repro this issue with a standard underscore character. Would you mind copying and pasting the problem path into the issue? It appears a bit lower than the standard underscore.

**Comment by muyu66** [comment]
@sbatten  Such as "D:\asdsad_dasd" , "C:\Web\hrm_api".   I just create a folder with _  all will be like this.

It may be my alone problem. 
[underline.zip](https://github.com/Microsoft/vscode/files/2161666/underline.zip)

**Comment by sbatten** [comment]
@muyu66 thanks for providing the zip. Unfortunately, I am still unable to repro this on my machine event with your provided folder. You mentioned that you do not repro this on a separate machine after copying the folders. Does the original machine still produce the issue consistently?

**Comment by muyu66** [comment]
@sbatten  Tragedy, I formatted the PC that had the problem before, now it is just Opensuse   T_T
So i describe this problem when i meet it again
