### ISSUE TITLE
Could not identify extension for 'vscode' require call from EditorConfig

### ISSUE THREAD

**Issue by mittalyashu** [Microsoft/vscode#53295]
Screenshot took from `code - insider`

When we get notifications, there is nowhere mentioned that the notifications came from which extension or it belongs to the core editor.

![code - insiders_2018-06-29_11-18-13](https://user-images.githubusercontent.com/29014463/42075427-8dbad64c-7b8e-11e8-9fa5-06a5603a8e33.png)

And when I try to click on the gear icon it didn't work.

![2018-06-29_11-18-51](https://user-images.githubusercontent.com/29014463/42075437-9cfaef8e-7b8e-11e8-8f5c-28d58a3dcc58.gif)

You should put some kind of reference in the notification.

**Comment by bpasero** [comment]
@mittalyashu that should not happen, what extensions do you have installed?

**Comment by mittalyashu** [comment]
Here's the list of extension installed:

![image](https://user-images.githubusercontent.com/29014463/42121489-a506b8b0-7c4d-11e8-840a-14283bedaa4c.png)

**Comment by bpasero** [comment]
@mittalyashu 
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by mittalyashu** [comment]
I got this log file.

[-1530370975728.log](https://github.com/Microsoft/vscode/files/2151854/-1530370975728.log)

**Comment by bpasero** [comment]
@mittalyashu thanks, the issue seems to originate from this:

`[Extension Host] Could not identify extension for 'vscode' require call from C:\Users\YASHU\.vscode\extensions\EditorConfig.editorconfig-0.12.4\out\src\editorConfigMain.js`

Can you try to:
* quit VSCode
* delete `C:\Users\YASHU\.vscode\extensions\EditorConfig.editorconfig-0.12.4`
* start VSCode
* install `EditorConfig` extension again from [here](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig)
* check if this still reproduces

**Comment by mittalyashu** [comment]
I don't think so about it.

Still getting the same notification.

**Comment by bpasero** [comment]
@mittalyashu can you try with "VS Code Stable" if you are using "VS Code Insiders" or vice versa otherwise? I just installed that extension and do not see that error about the extension not loading.

**Comment by mittalyashu** [comment]
Hmm...
I didn't get that notification in VS Code Stable.

Apart from that, as I have mentioned earlier.

> You should put some kind of reference in the notification.

Have you considered that.

**Comment by bpasero** [comment]
@alexandrudima @sandy081 can you help here, why would `[Extension Host] Could not identify extension for 'vscode' require call from C:\Users\YASHU\.vscode\extensions\EditorConfig.editorconfig-0.12.4\out\src\editorConfigMain.js` be reported in insiders only?

**Comment by alexandrudima** [comment]
ping @jrieken to investigate.

> I've added that warning as it was missing before to track cases like this down. Whenever an extension requires `vscode`, we will look at the call stack to determine which extension the file belongs to.

**Comment by jrieken** [comment]
> why would [Extension Host] Could not identify extension for 'vscode' require call from C:\Users\YASHU\.vscode\extensions\EditorConfig.editorconfig-0.12.4\out\src\editorConfigMain.js be reported in insiders only?

Hm, `\.vscode\extension` and Insiders... Shouldn't the path then be `.\vscode-insider\extension`? We build an [extension index](https://github.com/Microsoft/vscode/blob/91e82ed2fef68f9f0a8aea9276fdad35ff649e66/src/vs/workbench/api/node/extHostExtensionService.ts#L239) from the real paths and when a file requests the `vscode`-module we check from what extension that comes... The path mismatch could be a hint...

**Comment by bpasero** [comment]
@mittalyashu do you maybe run from the command line and configure the extensions home directory as command line flag?
