### ISSUE TITLE
Extremely slow saving/loading

### ISSUE THREAD

**Issue by monkeysuffrage** [Microsoft/vscode#53292]
- VSCode Version:
code --version
1.24.1
24f62626b222e9a8313213fb64b10d741a326288
x64
- OS Version:
Windows 10 Pro

Steps to Reproduce:

1. Open vscode
2. Create a new file in terminal
3. VSCode spins for 60+ seconds. It only seems to happen in some folders, possibly ones with lots of files or big files. This is on a fast PC with lots of RAM and a SSD.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

Can someone suggest any other ways to troubleshoot this?

**Comment by roblourens** [comment]
Please see the steps in this wiki and post the results here to help us understand what might be going on, thanks! https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by monkeysuffrage** [comment]
It's happening again after switching to Insiders. I noticed it first saving a PHP file so I tried "php.validate.enable": false - but this didn't help.

Here is output of code --status:

Version:          Code - Insiders 1.25.0-insider (368ab9c31b5c0930a40ab3f0e0d768ebbeeb9ef8, 2018-06-26T05:18:23.085Z)
OS Version:       Windows_NT x64 10.0.17134
CPUs:             Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz (8 x 2394)
Memory (System):  15.62GB (6.00GB free)
VM:               50%
Screen Reader:    no
Process Argv:     C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe
GPU Status:       2d_canvas:                    enabled
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    disabled_software
                  rasterization:                disabled_software
                  video_decode:                 enabled
                  video_encode:                 enabled
                  vpx_decode:                   enabled
                  webgl:                        enabled
                  webgl2:                       enabled
CPU %	Mem MB	   PID	Process
    0	   100	  7188	code-insiders main
    1	   205	  2172	   window (● mobile_friendly.php - mobile_friendly - Visual Studio Code - Insiders)
    0	    24	  1160	     terminal
    0	     6	  1364	       winpty-process
    0	     9	  8004	         C:\cygwin\bin\bash.exe -l
    0	     7	 17340	         console-window-host (Windows internal process)
    0	    13	  4628	     watcherService 
    0	     5	  6936	       console-window-host (Windows internal process)
    0	    54	 10212	     extensionHost
    0	    58	  1104	       electron_node jsonServerMain.js 
    0	   171	  2824	   window (anz.bot.rb - anz - Visual Studio Code - Insiders)
    0	    21	  3920	     terminal
    0	     5	 15944	       winpty-process
    0	     6	  3700	         console-window-host (Windows internal process)
    0	     6	 15020	         C:\cygwin\bin\bash.exe -l
    0	    33	  7404	     extensionHost
    0	    39	  2652	       electron_node htmlServerMain.js 
    0	    11	 11448	     watcherService 
    0	     5	  8840	       console-window-host (Windows internal process)
    0	    21	 12128	     terminal
    0	     6	 12284	       winpty-process
    0	     9	  7712	         console-window-host (Windows internal process)
    0	     7	  7808	         C:\cygwin\bin\bash.exe -l
    2	   214	  4276	   window (● xxx - henry_ebay - Visual Studio Code - Insiders)
    0	    63	 14112	     extensionHost
    0	    24	 16032	       electron_node jsonServerMain.js 
    0	    31	 15728	     terminal
    0	     8	   596	       winpty-process
    0	     7	 13552	         C:\cygwin\bin\bash.exe -l
    0	     8	 14880	         console-window-host (Windows internal process)
    0	    16	 15976	     watcherService 
    0	     5	  1156	       console-window-host (Windows internal process)
    0	    20	 16280	     terminal
    0	     5	 15680	       winpty-process
    0	     6	 17760	         console-window-host (Windows internal process)
    0	     6	 17908	         C:\cygwin\bin\bash.exe -l
    0	    68	  7608	   shared-process
    1	   125	  9632	   gpu-process
    0	    93	 11516	   window (routes.rb - people1.info - Visual Studio Code - Insiders)
    0	    21	  2136	     terminal
    0	     5	 15636	       winpty-process
    0	     6	  7976	         C:\cygwin\bin\bash.exe -l
    0	     6	 10236	         console-window-host (Windows internal process)
    0	    11	  3864	     watcherService 
    0	     5	   140	       console-window-host (Windows internal process)
    0	    21	  8928	     terminal
    0	     5	 14008	       winpty-process
    0	     6	  5228	         console-window-host (Windows internal process)
    0	     7	 15228	         C:\cygwin\bin\bash.exe -l
    0	    32	 13072	     extensionHost
    0	   153	 13676	   window (geocoder.js - geolocation - Visual Studio Code - Insiders)
    0	    19	  3608	     terminal
    0	     8	 10816	       winpty-process
    0	     6	  5684	         C:\cygwin\bin\bash.exe -l
    0	     9	  7912	         console-window-host (Windows internal process)
    0	    38	  7232	     extensionHost
    0	    24	  1660	       electron_node electronForkStart.js tsserver.js 
    0	    18	 13904	         electron_node typingsInstaller.js tsserver.js typesMap.js 
    0	    31	 10544	       electron_node jsonServerMain.js 
    0	    11	 13652	     watcherService 
    0	     5	  5500	       console-window-host (Windows internal process)
Workspace Stats:
|  Window (geocoder.js - geolocation - Visual Studio Code - Insiders)
|  Window (anz.bot.rb - anz - Visual Studio Code - Insiders)
|  Window (● xxx - henry_ebay - Visual Studio Code - Insiders)
|  Window (routes.rb - people1.info - Visual Studio Code - Insiders)
|  Window (● mobile_friendly.php - mobile_friendly - Visual Studio Code - Insiders)
|    Folder (anz): 4 files
|      File types: rb(2) ruby-version(1) html(1)
|      Conf files:
|    Folder (mobile_friendly): 11 files
|      File types: php(5) csv(2) ruby-version(1) icns(1) txt(1)
|      Conf files:
|    Folder (geolocation): 7513 files
|      File types: cache(7489) csv(9) js(5) json(2) ruby-version(1) zip(1)
|                  txt(1) xlsx(1)
|      Conf files: package.json(1)
|    Folder (henry_ebay): more than 166820 files
|      File types: cache(166792) txt(8) csv(3) gitignore(2) rb(2)
|                  ruby-version(1) json(1) yml(1) ico(1) dat(1)
|      Conf files:
|    Folder (people1.info): 1115 files
|      File types: cache(673) png(250) rb(83) erb(37) keep(8) yml(7) scss(6)
|                  js(6) coffee(5) txt(5)
|      Conf files:

**Comment by bpasero** [comment]
@monkeysuffrage how do you "Create a new file in terminal" and when does it wait for 60s?

**Comment by monkeysuffrage** [comment]
If I do "touch xxx" in terminal for example, vscode will spin in the left
side file area. Also when I save a buffer it sometimes takes 30 seconds or
so to save.

**Comment by bpasero** [comment]
@monkeysuffrage is there any remote file system involved or is the file local on disk?

**Comment by monkeysuffrage** [comment]
It's all local and on a fast SSD

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by monkeysuffrage** [comment]
I don't see nightly builds at that link. I'm using 1.25.0-insider which I
installed this week. Anyway I don't think this issue has been resolved.

**Comment by bpasero** [comment]
@monkeysuffrage does it happen with any file type you create?

**Comment by monkeysuffrage** [comment]
I think so. It seems to go away for awhile at least if I close out all the
vscode windows and restart.

**Comment by bpasero** [comment]
@monkeysuffrage can you also reproduce when you create a new file from the file explorer?

**Comment by monkeysuffrage** [comment]
Hi Benjamin,
Sorry I didn't follow that. Can you reword the question please?

**Comment by bpasero** [comment]
@monkeysuffrage you indicated that you create a file using the integrated terminal and I am wondering if you also see this when you use the file explorer to create a new file:

![grid-tw](https://user-images.githubusercontent.com/900690/42211322-9aecb6f0-7eb3-11e8-972a-2e9e5440b1d3.gif)

**Comment by monkeysuffrage** [comment]
You're wondering if I also have an issue when I create a new file from
vscode? In that case yes, I do.

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!
