### ISSUE TITLE
VS Code Classic: All Opt-in version of VS Code

### ISSUE THREAD

**Issue by mrange** [microsoft/vscode#53297]
I really like VS Code, however I liked it better when it had less smart features.

VS Code now has many enabled features that rubs me the wrong way and that I have to spend time to disable. This is my least favourite thing to do.

The latest thing that almost got too unbearable is the numerous notifications pointing out various problems it sees with my project. These are non-problems when I just open a folder to browse around in the project. The problem instead becomes all notifications I have to click away.

Instead, I would like a VS Code with a minimal set of features enabled that support text editing. Let me opt-in instead. Don't tell me with a notification that there is a plugin for this file, I know how to find it. 

Give me back my smart text editor experience, not the IDE experience.

I realize that others love the IDE experience but let me chose the text editor experience on install.

**Comment by aciccarello** [comment]
Could this mostly be accomplished via your own settings config? It would be messy to have have to override everything but it would be good if someone maintained a base version.

As a VS Code feature I could imagine a flag to use an alternate set of default settings. Either a boolean "minimalFeatures" flag or some way to compose multiple settings (plugin opportunity?).

**Comment by sana-ajani** [comment]
Hi there, you can turn off notifications by setting "extensions.ignoreRecommendations": true, or do this for select ones by clicking on the gear in the pop-up and choose "Don't Show Again".

**Comment by mrange** [comment]
Thanks. That address 50% of my issue though. I would like a VS Code experience that is minimal and let me opt-in. 

I don't, for example, want the GIT plugin in VS Code, it sometimes causes VS Code to perform slowly when having large repos.

I realize most people love the GIT plugin, I don't want to take that away from them. I just like an option to start from a plain text editor and carefully add what I want.

**Comment by chrisdias** [comment]
you can turn off the built-in features that are implemented as extensions, including git.  Open the Extensions View (`Ctrl+Shift+X`), and search for `@builtin`.  From there you can disable features, themes, and core language support (e.g. colorization).

![image](https://user-images.githubusercontent.com/1487073/99157685-19799580-2680-11eb-8cb9-86762646d4ef.png)
