### ISSUE TITLE
sftp配置文件post写的number却总是报错

### ISSUE THREAD

**Issue by JiaYand** [Microsoft/vscode#53290]
Issue Type: <b>Feature Request</b>

这是配置文件写的
"post":22,

config validation fail: prop "port" fails because ["port" must be a number]

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
OS version: Darwin x64 17.4.0

**Comment by JiaYand** [comment]
提交bug

**Comment by roblourens** [comment]
What config file? Are you using an extension?

**Comment by shaynem** [comment]
getting the same issue 

.vscode/sftp.json

```{
    "protocol": "sftp",
    "host": "xxxxx",
    "port": 1025,
    "username": "root",
    "remotePath": "/var/www/xxxx",
    "uploadOnSave": true,
    "privateKeyPath": "xxxx"

}

```
