### ISSUE TITLE
How to setting php.validate.executablePath?

### ISSUE THREAD

**Issue by karl20888** [Microsoft/vscode#533]
How to setting php.validate.executablePath?

**Comment by dbaeumer** [comment]
If the php executable is not on your path you can use the setting to point to the php executable. For example 
```json
php.validate.executablePath="C:\\apps\\php\\php.exe"
```

**Comment by karl20888** [comment]
@dbaeumer Thank you!

**Comment by only1shirish** [comment]
Not Working 
![untitled](https://cloud.githubusercontent.com/assets/4066994/11606822/e31774e6-9b54-11e5-89a3-6ddf14e8b3be.png)

**Comment by only1shirish** [comment]
I am sorry the file ext was wrong

**Comment by mattid89** [comment]
What another settings do I need to debug php code?

**Comment by dbaeumer** [comment]
There is currently no out of the box support to debug PHP. You might want to look if an extension is available.

**Comment by mattid89** [comment]
thanks!

**Comment by Hettar** [comment]
Try that:
php.validate.executablePath="C:/apps/php/php.exe"

**Comment by TRE8** [comment]
How would I achieve this on my Mac running Mamp?

I'm trying
 "php.validate.executablePath": "~/Applications/MAMP/bin/php/php7.0.12/bin"

**Comment by Exevium** [comment]
![code error](https://cloud.githubusercontent.com/assets/25924266/23959114/88052e94-09a4-11e7-9323-ec6af0c29aae.png)

It doesn't work for me.

**Comment by dastani** [comment]
hi,
open file setting.json
{
"php.validate.executablePath": "C:\xampp\php\php.exe",
"php.executablePath": "C:\php7.1\php.exe"
}
:)

**Comment by cp1001** [comment]
on mac,add setting to setton.json:
"php.validate.executablePath": "/usr/local/php5-7.1.4-20170506-100436/bin/php"

**Comment by muganwas** [comment]
@only1shirish super helpful, I couldn't make sense of anything anyone was saying.

**Comment by Nathan-Hanlon** [comment]
I have tried everything on here but it is still not debugging

**Comment by dbaeumer** [comment]
@Nathan-Hanlon which OS are you on?

**Comment by Nathan-Hanlon** [comment]
Windows 10

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by 8sam** [comment]
I went to my workspace settings and typed php.validate.executablePath: "c://Users/User01/data/php.exe" but its not working even then.

**Comment by knucklejames** [comment]
I've tried a few paths for PHP binaries on OS X, none of them seem to work. Visual Studio is finding PHP 5.6 somewhere on my computer and it's sticking to it, regardless of my settings.

The error I get is "The language server needs at least PHP 7 installed. Version found: 5.6.30".

Here are the different paths I've tried to give it:
```
"php.validate.executablePath": "/Applications/MAMP/bin/php/php7.1.1/bin/php",
"php.validate.executablePath": "/Applications/MAMP/bin/php/php7.1.1/bin/",
"php.validate.executablePath": "/usr/local/Cellar/php71/7.1.0_11/bin/",
"php.validate.executablePath": "/usr/local/Cellar/php71/7.1.0_11/bin/php",
```

Atom uses MAMP's php binary just fine. Visual Studio Code ain't having it.  ¯\_(ツ)_/¯

![screen shot 2017-08-04 at 2 53 21 pm](https://user-images.githubusercontent.com/20188919/28982865-45dbe256-7925-11e7-8efd-6076c48346d4.png)

**Comment by icwgiam** [comment]
is not working for me ... sorry !!!

**Comment by whatyoubendoing** [comment]
Also not working for me

**Comment by iamkingsleyf** [comment]
trying to set mine

**Comment by ejljustimbaste** [comment]
Guys, just find the directory of the file where you can find your _php.exe_

Mine was "C:\xampp\php\php.exe"

I just had to change "\" to "/"

Therefore "C:/xampp/php/php.exe"

**Comment by AteX01** [comment]
@ejljustimbaste It still doesn't work.

**Comment by iamkingsleyf** [comment]
you have to set for `php.executablePath` and `php.validate.executablePath`

**Comment by gerardactu** [comment]
![solve](https://user-images.githubusercontent.com/32501158/31155051-52cafb2a-a8a3-11e7-80c3-1d4d47342432.png)
Do this to solve 100% work

**Comment by arifavia** [comment]
"php.validate.executablePath": "C:/xampp/php/php.exe",
    "php.executablePath": "C:/xampp/php/php.exe",

I added these and it worked, finally!
