### ISSUE TITLE
import types error

### ISSUE THREAD

**Issue by WangPengJu** [Microsoft/vscode#53305]
typescript version: 2.9.1

1. create new project
2. npm install typeorm --save
3. write code
```typescript
    namespace Test {
        export let fs: typeof import("fs");
        export let typeorm: typeof import("typeorm");
    }
```
"fs" is ok, but "typeorm" is wrong.
error: can not find module "typeorm".

ps: "typeorm" has index.d.ts in root dir

**Comment by WangPengJu** [comment]
just IntelliSense,
don't need run code.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#25332
