### ISSUE TITLE
[Multi-target debuging] Switch between the multiple debug session automatically

### ISSUE THREAD

**Issue by adashen** [Microsoft/vscode#53303]
We have a client <-> server scenario. And there are break points set in both client and server. We could start the multi-target debugging for both client/server. But if the current session is client, the break point in server could not be hit. This cause problem when we would like to debug a e2e flow with both client and server break points in one session.

Requirement:
The break point in server should also be hit if the current debug session is client.

**Comment by weinand** [comment]
What debuggers/languages are you using?
How does your launch configuration look like?

**Comment by adashen** [comment]
@weinand 
Please refer to https://github.com/VSChina/iot-edge-abnormality-detection/blob/master/.vscode/launch.json for the json.

It is an iot edge scenario. And the debug targets are dotnet process running in docker container.  
VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17134

**Comment by weinand** [comment]
Please file this issue against the C#/.net repository https://github.com/OmniSharp/omnisharp-vscode/issues
