### ISSUE TITLE
Cursor does not keep indentation

### ISSUE THREAD

**Issue by venil7** [Microsoft/vscode#5330]
- VSCode Version: 1.0
- OS Version: macos 10.11.4

Steps to Reproduce:

1. open vscode
2. open .js file
3. start typing code

expeceted: indentation kept where applicable
actual: not at all....

please see screenshot:
![out](https://cloud.githubusercontent.com/assets/508022/14559625/089e97f2-0302-11e6-965f-ce98cdc4983b.gif)

**Comment by dbaeumer** [comment]
I can't reproduce this neither with format on type on nor off. @venil7 could you share the file our workspace. There must be more to it. Do you work with format on type off or on

![bug](https://cloud.githubusercontent.com/assets/1931590/14598112/0ce2b9e6-0551-11e6-919d-74211a65b392.gif)

**Comment by venil7** [comment]
I can only replicate it when  `"editor.formatOnType": true,`
if set to `false` - all works as expected 

could it be caused by plugins?

**Comment by dbaeumer** [comment]
@venil7 it could. Can you launch vscode from the command line using the switch --disable-extensions and check if it reproduces. If yes, could you provide the content of the JS file and the jsconfig.json

**Comment by venil7** [comment]
turning off extensions didn't help - I can still reproduce it.

here is my `jsconfig.json`

```{
	// See http://go.microsoft.com/fwlink/?LinkId=759670
	// for the documentation about the jsconfig.json format
	"compilerOptions": {
		"target": "es6"
	},
	"exclude": [
		"bower_components",
		"jspm_packages",
		"node_modules",
		"public",
		"temp",
		"tmp",
	]
}
```

**Comment by dbaeumer** [comment]
@venil7 could you share the content of the js file showing the behavior. Would ease tracking this down.

**Comment by venil7** [comment]
Sure, the js file in GIF above is here: `https://github.com/Financial-Times/email-manual-editor/blob/master/src/app/components/stats/stats.directive.js`

but for me bug manifests in _any_ file where indentation needs to be preserved

**Comment by dbaeumer** [comment]
This is really strange. I cloned the repository and tried to reproduce but failed. Here is what I see.

![bug](https://cloud.githubusercontent.com/assets/1931590/14676247/f6250c82-070c-11e6-9f88-ca6e993d8948.gif)

Can you think of any difference? We are aware that we loose indentation when you insert two empty lines in a row and there is a corresponding issue in the TS land for this.

**Comment by venil7** [comment]
I'm not sure that `code --disable-extensions .` disables extensions, because I can still see extensions if i type `Show Installed Extensions` into command line

So my previous experiment may not have been clean.

**Comment by venil7** [comment]
One other observation - I can see that when I hit `[Enter]` cursor goes to where it should be.. and then immediately goes to beginning of line.. :(

**Comment by dbaeumer** [comment]
The switch is correct. It disables extensions for that specific run.

**Comment by dbaeumer** [comment]
I tried this on Windows so far. Will try on Mac.

**Comment by dbaeumer** [comment]
@jrieken: can you please check if you can reproduce this on the Mac. I can't under Windows. Just to be sure.

**Comment by dbaeumer** [comment]
This comment has instruction where to find the repository: https://github.com/Microsoft/vscode/issues/5330#issuecomment-212319726

**Comment by jrieken** [comment]
I believe this is only happening on the second (!) line of trivia. It's a known issue with TypeScript/JavaScript format on type.

**Comment by jrieken** [comment]
I'd say it's related to https://github.com/Microsoft/vscode/issues/3797. Tho is reproduces for me only on the second line

**Comment by jrieken** [comment]
checked with the repo from above, doesn't happen with the first but the second Enter. I remember this behaviour being present in a previous version of TypeScript and their 'fix' made it work for the first enter. @venil7 might not be on 1.0

**Comment by dbaeumer** [comment]
Exactly. His steps are with one line. This is why I keep investigating. Would like to understand his issues.

**Comment by venil7** [comment]
Yes, happens on first [Enter], with `"editor.formatOnType": true,`

**Comment by dbaeumer** [comment]
@venil7 I added code to trace what we get back from the TS language server in your setup to better understand why this is happening. I will ping you as soon as this lands in a public available build with instructions how to produce a trace. I don't know how to track this down otherwise.

**Comment by dbaeumer** [comment]
@jrieken since I am out on vacation for the next two weeks can you please follow up. The idea to track that down further is to use the next insider build, enable tsserver logging (the new option) and see if this is the tsserver or VSCode. Then we know at least where to look at.

**Comment by dbaeumer** [comment]
@venil7 do you have a tsdk setting either globally or locally pointing to an older version of the tsserver ?

**Comment by venil7** [comment]
yes, turns out, I had `tsdk` setting pointing to some location, in `settings.json`, removing it solved the issue even with `formatOnType:true`. @dbaeumer thanks for pointing this out, I do not have salsa version showing in bottom right corder any more, is that how it should be?

**Comment by jrieken** [comment]
yeah - we don't show the salsa version anymore when things are set to default. the double enter issue is still tracked in #3797

**Comment by mlibre** [comment]
same here again.

Version 1.15.1
Commit 41abd21afdf7424c89319ee7cb0445cc6f376959
Date 2017-08-16T17:16:27.618Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
Architecture x64
OS: Linux

* running with `code --disable-extensions`.
* there is a `"typescript.tsdk": null` configuration in my default setting.
* `"editor.formatOnType": false` dose not help. still happening:

![a](https://user-images.githubusercontent.com/8473036/29705481-07ffdf96-8933-11e7-9425-cf373e9cc3ce.gif)
 
[default-setting.txt](https://github.com/Microsoft/vscode/files/1251271/default-setting.txt)
[user-setting.txt](https://github.com/Microsoft/vscode/files/1251266/user-setting.txt)
[workspace-setting.txt](https://github.com/Microsoft/vscode/files/1251267/workspace-setting.txt)
[js-user-snippets.txt](https://github.com/Microsoft/vscode/files/1251268/js-user-snippets.txt)
