### ISSUE TITLE
URL activation event for extensions

### ISSUE THREAD

**Issue by arjun27** [Microsoft/vscode#53301]
Can we have a way to activate the extension on `vscode://` URLs? Just as it is possible to [open a file/project](https://code.visualstudio.com/docs/editor/command-line#_opening-vs-code-with-urls), it would be useful to have this for extensions.

One use-case that is critical for my extension ([Slack Chat](https://github.com/karigari/vscode-chat)) is to enable OAuth, with a redirect URL. Other apps on Mac use URL scheme handlers to setup OAuth redirection, and it would be great if vscode could do so too.

**Comment by roblourens** [comment]
Is this what you are looking for? https://github.com/Microsoft/vscode/blob/049cb9dde0839c0602a8ebeec8e7c7fcebcee4b6/src/vs/vscode.proposed.d.ts#L505

**Comment by arjun27** [comment]
This looks exactly like what I need, thank you. I will remember to check the proposed APIs before creating an issue the next time. Is there any timeline on when this will be in stable?

**Comment by joaomoreno** [comment]
This API is coming out for stable only in July.
