### ISSUE TITLE
Create new instance from a tab

### ISSUE THREAD

**Issue by mittalyashu** [Microsoft/vscode#53300]
Grid view is really awesome, but in that structure, working in settings or any other file could be a bit hard.

![code - insiders_2018-06-29_11-50-37](https://user-images.githubusercontent.com/29014463/42076801-44fe6ae4-7b94-11e8-9851-e82c6ef75308.png)

Currently, to view the settings properly I have to close all the other tabs. 

![2018-06-29_11-53-40](https://user-images.githubusercontent.com/29014463/42076780-2e6c034a-7b94-11e8-8164-69b7df418396.gif)

What if we can drag the tab outside _(or as shown in the image below)_ and it creates a new instance of vs code with that tab.

![2018-06-29_11-55-03](https://user-images.githubusercontent.com/29014463/42076775-2a3b6342-7b94-11e8-84df-b5d2a9ae7d28.png)

**Comment by roblourens** [comment]
The new settings editor should be a little better in this regard but it will still be an issue.

**Comment by roblourens** [comment]
What you're suggesting is tracked in https://github.com/Microsoft/vscode/issues/10121
