### ISSUE TITLE
Menu: context menu on explorer does not show keybindings

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#53309]
Looks like a regression:

![image](https://user-images.githubusercontent.com/900690/42082019-38d234e2-7b87-11e8-9b62-1cc4ab1acafb.png)

Compared to stable:

![image](https://user-images.githubusercontent.com/900690/42082034-4213acfc-7b87-11e8-9af8-ded39be68481.png)

**Comment by bpasero** [comment]
Interestingly I do not see that in the editor context menu:

![image](https://user-images.githubusercontent.com/900690/42082072-548f5f34-7b87-11e8-8575-af8bc024a234.png)

**Comment by sbatten** [comment]
@bpasero see commit not in master

**Comment by bpasero** [comment]
@sbatten lgtm, we could merge this to June release
