### ISSUE TITLE
Sort encodings in settings by name to make picking easier

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#53304]
Issue Type: <b>Bug</b>

It is hard to find a specific encoding when they are not sorted alphabetically:
![image](https://user-images.githubusercontent.com/9205389/42078790-16728ce8-7b7e-11e8-942e-767568629020.png)

VS Code version: Code - Insiders 1.25.0-insider (499122702e462b458117122a6885e6aeb3cec0a4, 2018-06-29T05:11:09.904Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (1.01GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron --extensions-dir /Users/chrmarti/Development/repos/tmp/ext --user-data-dir /Users/chrmarti/Development/repos/tmp/user|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
debugger-for-chrome|msj|4.7.0
code-eol|soh|0.3.3

</details>

**Comment by bpasero** [comment]
I would like to wait for a user to complain about this because this list is sorted in the order of most common encodings and so it may be confusing to change it suddenly. To compare, this is how the list looks like in the picker:

![image](https://user-images.githubusercontent.com/900690/42095642-79a4607c-7bb3-11e8-95fe-cfe39d4679b3.png)

**Comment by chrmarti** [comment]
For the picker the ordering by popularity is easier to navigate because you can filter, in the context menu the lookup can only be sped up when the entries are sorted alphabetically. I'm fine with leaving it as-is.
