### ISSUE TITLE
Allow to cancel changes from git modifications view

### ISSUE THREAD

**Issue by pludov** [Microsoft/vscode#53308]
When reviewing changes (using GIT source control), I often miss the ability to cancel changes from this view.

In this regard, two new context actions would be handfull from the Modifications list:
 - Delete file (for new untracked file)
 - Cancel change (for modified files)

**Comment by joaomoreno** [comment]
The action you're looking for is `Discard Changes`.

**Comment by pludov** [comment]
Thank you for the feedback!

So there is a problem with the French translation: the action is labeled "ignorer les modifications" which would translate to "ignore change", understood as "add to gitignore...". That's why I didn't find it.

A more accurate translation would be:  "Annuler les modifications"

**Comment by joaomoreno** [comment]
@pludov Would you like to contribute to that translation? https://github.com/Microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project

**Comment by pludov** [comment]
done...
