### ISSUE TITLE
Unable to autodetect gulp tasks for pdf.js project

### ISSUE THREAD

**Issue by SirR4T** [Microsoft/vscode#53318]
Found two previous issues, which may or may not be related: #19743 and #34575.

Reproducible using insiders build too.

- VSCode Version: 1.24.1
- OS Version: macOS, Darwin kernel version 17.6.0

Steps to Reproduce:

1. Clone the [pdf.js](https://github.com/mozilla/pdf.js/) project
2. Open in a new VSCode window
3. Hit <kbd>⇧ Shift</kbd>+<kbd>⌘ Command</kbd>+<kbd>B</kbd> (opens up the tasks pane for me)

I expect this pane to be autofilled with all the gulp tasks defined in the pdf.js project.
Shows only `gulp: buildnumber`, for some reason, and `npm: build - examples/browserify` and `npm: build - examples/webpack` (pulled in from their respective `package.json` files in subfolders).

Does this issue occur when all extensions are disabled?: Yes

**Comment by dbaeumer** [comment]
Strange. I cloned the project, ran npm install and then opened code and it shows:

<img width="494" alt="capture" src="https://user-images.githubusercontent.com/1931590/42156552-a6342fac-7deb-11e8-8a14-8fd8b2d6a8e5.png">

Can you provide any additional info.

**Comment by SirR4T** [comment]
Pulled in latest changes from the project, ran npm install.
Deleted .vscode folder, and the .code-workspace file.

No luck, still seeing the above reported behaviour.

![screen shot 2018-07-02 at 7 10 41 pm](https://user-images.githubusercontent.com/2033712/42167491-d9ec9772-7e2b-11e8-86e1-ff471d5a0291.png)

What other information will be relevant here? I don't see anything in the Output tab.
How do i fetch further debug info?

**Comment by dbaeumer** [comment]
@SirR4T what you can do is the following

- open a terminal
- run `gulp --tasks-simple` in the workspace folder

What tasks will be listed. 

I am using gulp version 

```
[09:51:59] CLI version 2.0.1
[09:51:59] Local version 3.9.1
```

**Comment by SirR4T** [comment]
@dbaeumer `gulp --tasks-simple` does indeed list down all the 45 different tasks defined in gulpfile.js . This is true for the integrated terminal window in vscode, as well.

**Comment by dbaeumer** [comment]
@SirR4T this is really strange. One thing that could be different is that the auto detection first looks into node_modules for a gulp command and then globally. Does `.\node_modules\.bin\gulp.cmd --tasks-simple` work as expected as well. If so would you be willing to debug this ?

**Comment by dbaeumer** [comment]
@SirR4T create. I will provide you instructions how to do this.

**Comment by SirR4T** [comment]
I'm sorry, I didn't get you. create what?
