### ISSUE TITLE
Russian translation of toggle/hide menu is confusing

### ISSUE THREAD

**Issue by Heather** [Microsoft/vscode#5331]
I read it as "switch menu line" , it's something different and not very native/common

**Comment by egamma** [comment]
// FYi @dbaeumer

**Comment by johnliu2016** [comment]
@lukaschal Please send this feedback to Russian linguistic review, correct all "Toggle ..." / "Hide ..." menu translations accordingly.

**Comment by lukaschal** [comment]
On linguistic review now.

**Comment by lukaschal** [comment]
Please, is it possible to add some ENU/RUS screenshot or repro steps ?

**Comment by dbaeumer** [comment]
@Heather can you please provide a screen shot ?

**Comment by Heather** [comment]
@dbaeumer @lucaslra not currently it's complicated for me, maybe later, but it's just the button which hides menu bar in version 1.0 in Russian, shouldn't be hard to find thought

**Comment by Heather** [comment]
![default](https://cloud.githubusercontent.com/assets/2656965/14611739/d346f9be-05a4-11e6-9d7a-76d24dd567be.JPG)

**Comment by lukaschal** [comment]
Fixed.
