### ISSUE TITLE
Wrong path opened when using drive letter with relative path

### ISSUE THREAD

**Issue by Tiltowaite** [Microsoft/vscode#53312]
Issue Type: <b>Bug</b>

at command prompt:
C:\>md d:\Subfolder\Foo\bar
C:\>echo TEst>d:\Subfolder\Foo\bar\File.txt
C:\>cd d:\Subfolder
C:\>code d:Foo\bar\File.txt
Expected: opens the file with "TEst" in it.
Actual: opens a new file at D:\foo\bar\File.txt
(errant \ is added between drive and folder, path generation should attach relative path onto "current folder" of the target drive.).  replace "CODE" with "DIR" and you will see the proper path used.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17707

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (5.89GB free)|
|Process Argv|c:\Program Files\Microsoft VS Code\Code.exe GitBuildSpec.WPTEdgeHTMLMinCheckin.txt|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-csv|mec|0.4.2
csharp|ms-|1.15.2
PowerShell|ms-|1.7.0

</details>

**Comment by Tyriar** [comment]
> Expected: opens the file with "TEst" in it.

Why do you expect this when you add `d:` to the path in this step? `C:>code d:Foo\bar\File.txt`

**Comment by Tiltowaite** [comment]
I expect the full path to the file will be d:\TestFolder\foo\Bar\File.txt.   Each drive a "current working directory" so when you "dir d:" you are asking to view whatever the current directory on D: is, not the root.   In my case, I was working in D:\TestFolder, switched to C:, and then wanted to refer to the files on D: relative to where I was working before.  "Dir D:" would have showed the contents of D:\TestFolder, and I expect a path that does not include a leading \ (after the drive specifier) will also start relative to D:\TestFolder.

**Comment by Tyriar** [comment]
You need to do `C:>code d:\Subfolder\Foo\bar\File.txt`, we don't (and can't AFAIK) track working directories  across drives.

**Comment by Tiltowaite** [comment]
After parsing a name from the command line, you pass the name to this function and the relative paths will be resolved.

https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-getfullpathnamea

**Comment by Tyriar** [comment]
That's cmd's job, we just show what cmd tells us to. Your request belongs in https://github.com/Microsoft/console
