### ISSUE TITLE
Cannot reset keybinding after removing 1 of 3 keybindings for command

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#53311]
Issue Type: <b>Bug</b>

Verifying #51303

- Observe that there are 3 entries for keybindings of Zoom In
- Remove 1 keybinding for Zoom In
- Observe that there are now only 2 entries for Zoom In and none has the 'Reset' menu item enabled
- Only when I remove the remaining 2 keybindings does an entry without keys appear on which 'Reset' is enabled

Maybe the entry without keys should be shown as soon as the first keybinding is deleted?

VS Code version: Code - Insiders 1.25.0-insider (499122702e462b458117122a6885e6aeb3cec0a4, 2018-06-29T05:11:09.904Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron --extensions-dir /Users/chrmarti/Development/repos/tmp/ext --user-data-dir /Users/chrmarti/Development/repos/tmp/user|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
debugger-for-chrome|msj|4.7.0

</details>

**Comment by sandy081** [comment]
Yeah, its tricky the existing two entries are default keybindings and showing a reset button does not makes sense. One option is to show the user removed entry not sure how much it is helpful to the user. 

Also I do not think of the need to show reset button in this case
