### ISSUE TITLE
German translation mistake in debug variable scopes

### ISSUE THREAD

**Issue by martinbilles** [Microsoft/vscode#5332]
In the German localization, in the debug sidebar, the term "Blockieren" (to block) is a translation error. It should be "Block" (a block).

![vscode-blockieren](https://cloud.githubusercontent.com/assets/5391834/14560365/a562d76c-030f-11e6-8a5e-1f8f3e077ae5.png)

- VSCode Version: 1.0.0
- OS Version: Ubuntu 14.04

Steps to Reproduce:

1. Create block-scoped JavaScript file:
```javascript
"use strict";
{
    const c = 10;
    debugger;
}
```
2 . Debug with node >= v 4.0

3 . Reach the breakpoint and examine variables.

**Comment by egamma** [comment]
CC @dbaeumer

**Comment by johnliu2016** [comment]
@lukaschal wrong translation in nodeDebug.nls.resx.lcl

      <Item ItemId=";scope.block" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[Block]]></Val>
          <Tgt Cat="Text" Stat="Loc" Appr="PreApproved" Orig="Auto" Confidence="100">
            <Val><![CDATA[Blockieren]]></Val>
          </Tgt>
        </Str>
        <Disp

**Comment by lukaschal** [comment]
Waiting for linguistic input.

File: out\node\nodeDebug.nls.resx
ID: out\node\nodeDebug.nls.resx
SRC: Block
TGT: Blockieren

**Comment by lukaschal** [comment]
Fixed as suggested.
