### ISSUE TITLE
type checking and intellisense seems to be broken at the moment

### ISSUE THREAD

**Issue by pdp2** [Microsoft/vscode#53323]
Issue Type: <b>Bug</b>

type checking and intellisense seems to be broken at the moment

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:52:25.282Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.67GB (8.94GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe C:\apps\connect-ui|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-svgviewer|css|1.4.4
tslint|eg2|1.0.33
beautify|Hoo|1.3.2
minify|Hoo|0.3.0
autofilename|Jer|0.1.3
gitblame|wad|2.4.2

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by tudor33sud** [comment]
I have the same problem on a nodeJS project... Intellisense / Go To Definition are stuck. I'm not even using Typescript, just pure NodeJS and it happens to two of my projects with all the extensions uninstalled.

Is there any way to check intellisense logs so I could report the issue? I cannot share all the project code...

**Comment by mjbvz** [comment]
@tudor33sud Did you test in insiders? Please open a new issue

**Comment by tudor33sud** [comment]
@mjbvz  I can confirm that on insiders my intellisense it's working again. I'll use that until the update

**Comment by mjbvz** [comment]
Closing as we have not heard back from @pdp2 and do not have enough information to investigate this
