### ISSUE TITLE
Custom colors for specific comments

### ISSUE THREAD

**Issue by Coronon** [Microsoft/vscode#53328]
Hello,
I would really like to see a feature that allows to give specific comments special color's.
This would really help me to organise them with priority.
For example:

1. Write a comment
2. Select it and right click on it
3. Choose 'Colorise'
4. Select a color for the comment/A part of the comment
5. The comment has a new color

**Comment by TomSputz** [comment]
As the colour data isn't being written to the file, this feature couldn't work without vs code, and a file to provide metadata powering it. This functionality would be much better suited to an extension, as it isn't part of the text editor.

Alternatively, vscode could potentially support styling with Regex, allowing color information to be written at the start of a line, that vscode could then interpret and render on opening the file. This is a much better option as the information can be contained in the file, but I'd guess the overhead would make larger files very slow to open, causing this to affect the core goals of the project. Again, you would have to see if this could be done in an extension IMO
