### ISSUE TITLE
Not badge in vscode-doc

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#53325]
I am writing release notes and work in the vscode-doc repo with latest insiders and for some reason the scm-viewlet shows not badge. The one for the vscode repo does...

<img width="325" alt="screen shot 2018-06-29 at 12 27 07" src="https://user-images.githubusercontent.com/1794099/42087897-e74273ba-7b97-11e8-8774-cbcf3d0aa37a.png">

**Comment by joaomoreno** [comment]
Very strange. We were able to reproduce this easily until we added another repo and removed it. It doesn't repro any longer.

Will investigate.

**Comment by joaomoreno** [comment]
I really can't seem to reproduce... I've been through the code and also don't see anything wrong in there. I'll keep an eye out, please do the same.

cc @sandy081

**Comment by joaomoreno** [comment]
Not reproducing... Closing until we have steps.

**Comment by joaomoreno** [comment]
@jrieken Pushing possible fix which could explain the occurrence of this issue in very unlikely circumstances. Also pushed some `trace` logging, so if it happens again, you can set the log level to trace and see if the badge it being set at all.
