### ISSUE TITLE
Undo stack is lost on file name change

### ISSUE THREAD

**Issue by dmartensson** [Microsoft/vscode#53333]
- VSCode Version: 1.24.1
- OS Version: Windows 10

Steps to Reproduce:

1. Make changes to a file
2. Rename file
3. Cannot use Ctrl+Z to undo changes made any more

Does this issue occur when all extensions are disabled?: Yes

**Comment by dmartensson** [comment]
I see the proposed dups, but except the 50570 I would never have considered the others related.

**Comment by roblourens** [comment]
I believe this is covered by https://github.com/Microsoft/vscode/issues/50801
