### ISSUE TITLE
ECMAScript 'Private instance methods and accessors' proposal syntax support

### ISSUE THREAD

**Issue by trustgit** [Microsoft/vscode#53335]
This syntax below is recognized as an error:
- [Private instance methods and accessors](https://github.com/tc39/proposal-private-methods)  

e.g. when I write:
```js
class Test{
    #a = 1
}
```
VSCode says that `#` is an unavailable character.
I hope that this syntax will be supported. If it is, that would be awesome.
Thanks.

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/Microsoft/TypeScript/issues/9950
