### ISSUE TITLE
Frequent "Terminal with ID n does not exist" errors with new tasks API

### ISSUE THREAD

**Issue by Gama11** [Microsoft/vscode#53331]
[VSCode Version](https://i.imgur.com/rPr5h0T.png)

I've created [an extension](https://marketplace.visualstudio.com/items?itemName=vshaxe.terminator) to work around #6578. However, it's not as convenient as it should be because it frequently produces errors like this instead of running the tasks:

![](https://i.imgur.com/DVcvT2J.png)

I'm not aware of any way to work around this on the extension side / don't think I'm using the API incorrectly. Potentially related to #47707, which was closed because it couldn't be reproduced.

___________

To reproduce:

- create an extension with:

	```typescript
	'use strict';
	import * as vscode from 'vscode';
	
	export function activate(context: vscode.ExtensionContext) {
		var runningTasks:Array<vscode.TaskExecution> = [];
		vscode.tasks.onDidStartTask(startEvent => runningTasks.push(startEvent.execution));
	
		vscode.commands.registerCommand("foo", () => {
			runningTasks.forEach(execution => execution.terminate());
			runningTasks = [];
			vscode.tasks.fetchTasks().then(tasks => {
				vscode.tasks.executeTask(tasks[0]);
			});
		});
	}
	```

    ```json
    "contributes": {
        "commands": [
            {
                "command": "foo",
                "title": "foo"
            }
        ]
    }
    ```

- Open a workspace with some task that runs long enough to be able to execute the `foo` command twice, e.g.

	```json
	{
		"version": "2.0.0",
		"tasks": [
			{
				"label": "foo",
				"type": "shell",
				"command": "ping 8.8.8.8 /t",
				"problemMatcher": []
			}
		]
	}
	```

- Run the `foo` _command_ (not task) twice and observe the "Terminal with ID does not exist" error.

**Comment by Gama11** [comment]
Good question. Adding some log calls, it seems like it happens on the execute call:

![](https://i.imgur.com/FdkkrTf.png)

**Comment by isidorn** [comment]
Nothing critical, Dirk is on vacation, pushing out to August

**Comment by TaylorAnderson** [comment]
Do we know when this issue is going to get fixed @dbaeumer ? This is the only thing keeping me from using VSCode to work on my Haxe projects currently.

**Comment by dbaeumer** [comment]
@TaylorAnderson in which usage scenario are you seeing this error. The provided example in this issue is killing and restarting all tasks which is not a very common usages sceanrio. Might be your problem is independent from this.

**Comment by TaylorAnderson** [comment]
I’m using the extension @Gama11 is referring to in the first comment.

**Comment by dbaeumer** [comment]
Thanks. I looked into this this morning and it is very likely a dup of https://github.com/Microsoft/vscode/issues/60858 then.

**Comment by dbaeumer** [comment]
I am marking it as a dup since terminating the terminal programmatically or pressing the kill terminal button goes through the same code path.

Dups https://github.com/Microsoft/vscode/issues/60858
