### ISSUE TITLE
Official download at https://code.visualstudio.com/license has bogus, lengthy legalese additional license although project is easily available under MIT here

### ISSUE THREAD

**Issue by JonasT** [Microsoft/vscode#5333]
Official download at https://code.visualstudio.com/license has bogus, lengthy legalese additional license although project appears to be easily available under just the much shorter MIT licensing from here. This is shady behavior and encourages people to make unofficial packages which do exactly the same but risk incompatibilities just to escape the useless waste of additional legalese terms to agree to.

Why not just make the official version be exactly under the MIT license, and then just offer *optional* feedback features that don't require ten pages of additional terms to agree to?? That's just silly.

**Comment by bgse** [comment]
As far as I know the Microsoft-branded build (the one which has the Visual Studio logo and such) does have the extra terms, while the opensource vscode-oss build (the one you get when building from this repo, and has the vscode-oss logo) has MIT.

**Comment by JonasT** [comment]
I am making this ticket not because I don't understand the thing they have done with that separate build, but simply to remark that it seems like a bad idea to have such an extra build. As I said, it drives people to make their own unofficial build just to avoid that.

Personally I sure lost interest in the branded one once I saw that lengthy page of legal stuff *for an MIT open-source project* I was supposed to agree to. No thanks. Does Microsoft want people to make extra unofficial builds because theirs sucks/is overly corporate legalese for no good reason? That seems like a bad thing.

**Comment by Tyriar** [comment]
Yes @bgse you're correct, you can see https://github.com/Microsoft/vscode/issues/60#issuecomment-161792005 for a detailed write up on the issue.

**Comment by JonasT** [comment]
Well I guess that means it's not going to be changed. What a shame...

You should at least consider also putting pre-built packages here on github as downloads which don't have this annoying licensing on top that nobody needs.
