### ISSUE TITLE
[loc][Query] Localizability of documentSymbols

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#53336]
For strings below we are not sure about theirs localizability? Can you please confirm whether they should be translated or not, and if yes, where they will be used? Thanks!

**Context**
src/vs/workbench/common/theme:English (en):plaintext:deprecatedEditorGroupBackground

**Resource**
vs_workbench

**String texts**
array
boolean
class
constant
constructor
enumeration
enumeration member
event
field
file
function
interface
key
method
module
namespace
null
number
object
operator
package
property
string
struct
type parameter
variable

**Comment by jrieken** [comment]
Tricky, it's about programming constructs and I'd say lets not translate them for now

**Comment by josefhosek** [comment]
@jrieken thanks for confirmation! We will mark these strings as "notranslate" so only source text can be used as translation.
