### ISSUE TITLE
JSDoc @typedef not working as expected

### ISSUE THREAD

**Issue by ffxsam** [Microsoft/vscode#53348]
- VSCode Version: 1.24.1
- OS Version: macOS 10.13.5

`@typedef` support seems a bit buggy. There are a couple of things going on, but related.

First, typdefs with properties don't seem to work as expected. I have the following file, `funcs.js`:

```js
/**
 * API options.
 * @typedef {Object} ApiOptions
 * @property {number} artificialDelay Number of milliseconds for an artificial delay
 * @property {boolean} debug Debug mode
 */

/**
 *
 * @param {string} url URL to call
 * @param {ApiOptions} [options] API options
 */
export function apiCall(url, options = {}) {}
```

And in `index.js`, I import `apiCall` but the JSDoc hints don't show the properties of `ApiOptions`:

<img width="501" alt="screen_shot_2018-06-29_at_11_17_05_am__2_" src="https://user-images.githubusercontent.com/12532733/42103245-192acde6-7b8e-11e8-905f-ad03b69d1e56.png">

Also, typdefs should be able to be "exportable". I modified `funcs.js` to this:

```js
/** @module api */

/**
 * API options.
 * @typedef {Object} module:api.ApiOptions
 * @property {number} artificialDelay Number of milliseconds for an artificial delay
 * @property {boolean} debug Debug mode
 */

/**
 *
 * @param {string} url URL to call
 * @param {module:api.ApiOptions} [options] API options
 */
export function apiCall(url, options = {}) {}
```

I added a new file called `middle.js`:

```js
import { apiCall } from './funcs';

/**
 *
 * @param {module:api.ApiOptions} options
 */
export function test(options) {}
```

VSCode doesn't seem to understand this usage at all:

<img width="381" alt="screen_shot_2018-06-29_at_11_42_20_am__2_" src="https://user-images.githubusercontent.com/12532733/42104322-b7b5d85e-7b91-11e8-91b8-d4ec9ac7015b.png">

It would be great if VSCode fully supported this for projects that aren't using TypeScript.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Lenophie** [comment]
What's weird is Intellisense/VSCode already exports typedef across a project by default BUT it fails if the custom uses other custom types.
Here are some test cases.
*****
Declaration of ```CustomType``` in a file :
![image](https://user-images.githubusercontent.com/40424734/42129265-744a1226-7cc0-11e8-8bb5-70b5dff3d173.png)
Declaration of a variable of type ```CustomType```  in another file :
![image](https://user-images.githubusercontent.com/40424734/42129270-a3bf8734-7cc0-11e8-83b1-8058f0079f30.png)
*Quick info works.* 👍 
*Displayed type is correct.* 👍 
*Displayed type property is correct.* 👍 
*****
Declaration of ```CustomType``` using another custom type ```CustomType2``` in a file :
![image](https://user-images.githubusercontent.com/40424734/42129286-11b7a406-7cc1-11e8-8b43-df61d217a54c.png)
Declaration of a variable of type ```CustomType```  in another file :
![image](https://user-images.githubusercontent.com/40424734/42129289-389dd5b8-7cc1-11e8-83d2-94bfe7b2c20a.png)
*Quick info doesn't work.* 👎 
*****
Declaration of ```CustomType``` using another custom type ```CustomType2``` AND declaration of a variable of type ```CustomType``` in the same file :
![image](https://user-images.githubusercontent.com/40424734/42129293-735b244e-7cc1-11e8-9286-21a7ea72e32c.png)
*Quick info works.* 👍 
*Displayed type is correct.* 👍 
*Displayed type property is correct.* 👍 
*****
Declaration of ```CustomType``` AND declaration of a variable of type ```CustomType``` in the same file BUT declaration of ```CustomType2`` in another file :
![image](https://user-images.githubusercontent.com/40424734/42129303-a8638424-7cc1-11e8-8af0-e53b4708fa68.png)
*Quick info works.* 👍 
*Displayed type is correct.* 👍 
*Displayed type property is wrong.* 👎 
*****
I hope this breakdown of different cases help solve the issue !

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#25386
