### ISSUE TITLE
[json] swagger 2.0 json schema not working for intellisense in visual studio code

### ISSUE THREAD

**Issue by mfmayer** [Microsoft/vscode#5334]
- VSCode Version: 1.0
- OS Version: Windows 7

Steps to Reproduce:

1.  Create new directory with .vscode/settings.json
2. Add json schema for swagger 2.0 to the settings.json: 

   ```
// Place your settings in this file to overwrite default and user settings.
   {
     "json.schemas": [
       {
         "fileMatch": [
           "*.json"
         ],
         "url": "http://json.schemastore.org/swagger-2.0"
       }
     ]
   }
```
3. Create new json file and see that autocomplete according to the swagger 2.0 json schema isn't working.

**Comment by djabraham** [comment]
Swagger 2.0 defined a $ref as this, but the code at [jsonSchemaService.ts#L432](https://github.com/Microsoft/vscode/blob/master/extensions/json/server/src/jsonSchemaService.ts#L432) assumes its a string, instead of an object. It crashes on split.

    "jsonReference": {
      "type": "object",
        "required": [
          "$ref"
        ],
          "additionalProperties": false,
            "properties": {
        "$ref": {
          "type": "string"
        }
      }
    }

**Comment by djabraham** [comment]
:+1: Thanks for fixing this so fast!

**Comment by mfmayer** [comment]
Thank you also from my side 👍
