### ISSUE TITLE
About keybindings and Extension implement

### ISSUE THREAD

**Issue by TX-QAQ** [Microsoft/vscode#53344]
As is write in the document:
When a key is pressed:
the rules are evaluated from bottom to top.
the first rule that matches, both the key and in terms of when, is accepted.
**no more rules are processed**.
if a rule is found and has a command set, the command is executed.

So is it able to customize the value of  "when" in keybinding?
If not, how may I implement a partial keybinding overide with customized condition?
for example,
I would like to add a new command binding to key "enter"
but hope it only act when cursor at end of a line.
Else it shall excute the former "enter" 's binding command.

**Comment by alexandrudima** [comment]
Customizing <kbd>Enter</kbd> and <kbd>Escape</kbd> is one of the most tricky things to do, but here is what you should do.

#### Step 1. Collect all the usages of <kbd>Enter</kbd>
* go to the default keybindings and look for `"enter"`

```
{ "key": "enter", "command": "breakpointWidget.action.acceptInput",
                     "when": "breakpointWidgetVisible && inBreakpointWidget" },
{ "key": "enter", "command": "repl.action.acceptInput",
                     "when": "inDebugRepl && textInputFocus" },
{ "key": "enter", "command": "settings.action.focusNextSetting",
                     "when": "inSettingsSearch" },
{ "key": "enter", "command": "acceptSelectedSuggestionOnEnter",
                     "when": "acceptSuggestionOnEnter && suggestWidgetVisible && suggestionMakesTextEdit && textInputFocus" },
{ "key": "enter", "command": "acceptRenameInput",
                     "when": "editorFocus && renameInputVisible" },
{ "key": "enter", "command": "list.select",
                     "when": "listFocus && !inputFocus" },
{ "key": "enter", "command": "notification.toggle",
                     "when": "notificationFocus" },
{ "key": "enter", "command": "settings.action.editFocusedSetting",
                     "when": "inSettingsEditor && settingRowFocused" },
{ "key": "enter", "command": "settings.action.focusSettingsList",
                     "when": "inSettingsEditor && settingsTocRowFocus" },
{ "key": "enter", "command": "debug.renameWatchExpression",
                     "when": "watchExpressionsFocused" },
{ "key": "enter", "command": "debug.setVariable",
                     "when": "variablesFocused" },
{ "key": "enter", "command": "renameFile",
                     "when": "explorerViewletVisible && filesExplorerFocus && !explorerResourceIsRoot && !explorerResourceReadonly && !inputFocus" },
```

---

#### Step 2. Immediately drop out non-conflicting keybindings
* remove keybindings which are for UI pieces completely outside the editor:
```
{ "key": "enter", "command": "breakpointWidget.action.acceptInput",
                     "when": "breakpointWidgetVisible && inBreakpointWidget" },
{ "key": "enter", "command": "repl.action.acceptInput",
                     "when": "inDebugRepl && textInputFocus" },
{ "key": "enter", "command": "acceptSelectedSuggestionOnEnter",
                     "when": "acceptSuggestionOnEnter && suggestWidgetVisible && suggestionMakesTextEdit && textInputFocus" },
{ "key": "enter", "command": "acceptRenameInput",
                     "when": "editorFocus && renameInputVisible" },
```

---

### Step 3. Target non-conflicting cases:
* look at the `when` conditions and target a situation where they don't apply:
  * `inBreakpointWidget`
  * `inDebugRepl`
  * `suggestWidgetVisible`
  * `renameInputVisible`

---

So, use the following when clause:
```
  "when": "textInputFocus && !inBreakpointWidget && !inDebugRepl && !suggestWidgetVisible && !renameInputVisible"
```

**Comment by TX-QAQ** [comment]
What if the condition I need is more specific beyond the existing built-in "when condition"?
If I liberalize my condition and check the condition inside the command, there is no way to trigger the "when condition check" of next possible key.
Therefore, can I somehow implement my our "when" condition 
or throw any certain Exception in my command to return to the "when rule" matching part?

**Comment by alexandrudima** [comment]
Yes, it is possible to drive a context key from an extension. From an extension, you can invoke the command `setContext` to define a custom context key. 

Here is a working example which wraps that command in a class:
https://github.com/Microsoft/vscode-extension-samples/blob/f06607de44240b400ac275822babc707fa935911/vim-sample/src/extension.ts#L238-L253

**Comment by TX-QAQ** [comment]
This approach seems to register bool values of conditions as "environment variables". Even if not being used, it updates so frequently in every action. I'm worried about it's performance. 
Is it able to register a bool-return function as condition? Lazy evaluation seems more economical.
If not, please consider it as a feature request.
Anyway, your detailed answer helped me a lot, thanks.

**Comment by alexandrudima** [comment]
We won't allow for lazy-evaluated context keys defined by extensions because we don't want to block keyboard dispatching in the renderer process on the extension host process.

In other words, if there is an unresponsive extension that leads to an unresponsive extension host, ... and even if the extension host process is killed..., keyboard dispatching should work immediately.

**Comment by TX-QAQ** [comment]
You are right.Thanks for dispelling my doubts.
