### ISSUE TITLE
file path intellisense inside quotes, selection moves cursor outside quotes

### ISSUE THREAD

**Issue by msftrncs** [Microsoft/vscode#53353]
Issue Type: <b>Bug</b>

Enter the following where file path intellisense is permitted (I am working in a PowerShell file with the PowerShell extension, and could not determine if VS Code or PowerShell extension provide this functionality), on a new line:

$VARIABLE = 

Then start with a single or double quote (I tried both), which automatically includes the closing quote on the other side of the cursor, and then start typing a valid file path (in my case, a network path '\\server\share\folder'.  Intellisense starts offering completion suggestions.  Pressing TAB or ENTER to accept one of the suggestions cause the suggestion to be entered in to the document, and the cursor moves to the other side of the closing quote, preventing further traversal of the file hierarchy.

I could not find any documentation that suggested that file path intellisense worked differently (I couldn't find any documentation stating that VS Code had built in file path intellisense).   The same effect did not happen if I manually triggered intellisense with a variable name (pressing CTRL-SPACE after a $ while just inside the closing quote).  I would think that the behavior should be consistent, regardless of even which type of file system object I selected.  The cursor should remain in front of the closing quote after the selection.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz (8 x 2794)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Memory (System)|15.91GB (10.30GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
mssql|ms-|1.4.0
csharp|ms-|1.15.2
PowerShell|ms-|1.7.0

</details>

**Comment by roblourens** [comment]
I think that would be from the Powershell extension. Can you check whether it happens if you start with `--disable-extensions`?

**Comment by roblourens** [comment]
This issue was moved to PowerShell/vscode-powershell#1398
