### ISSUE TITLE
Integrated Terminal Font Size doesn't match editor's Font Size.

### ISSUE THREAD

**Issue by pradeepambati** [Microsoft/vscode#53356]
- VSCode Version: 1.24.1
- OS Version: macOS 10.13.5 

Steps to Reproduce:

1. 
<img width="1609" alt="vscode_terminal" src="https://user-images.githubusercontent.com/4181886/42111934-b25f27b0-7bab-11e8-8c3c-1623d08cf7ae.png">

2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
You can make them align approximately by using `editor.fontSize` and `terminal.integrated.fontSize`. It looks like you're scaling the editor portion only though, If you scale the whole workbench the terminal will scale as well (`window.zoomLevel`);
