### ISSUE TITLE
Define custom list (topics extraction) regex

### ISSUE THREAD

**Issue by IBIT-ZEE** [Microsoft/vscode#53358]
for the new Code Outline panel

Possibility to create extra JSON/Config definitions to extract topics from code
to be added to the existing hierarquic topic/symbols tree
or replace the existing tree
(very much like the function list of IDM/UltraEdit (http://ultraedit.com)

(the trigger to this option (to toggle add/substitute topics) 
should be a simple button in the [OUTLINE] title separator)

the funcionality and simplicity of the vscode extensions "CodeOutline" or "ShowFunction" 
should be an example and a great guidance example...

My suggestion for the definition is something like this:
(example for powershell files with comments like <#[ COMMENT1 ]###########>)
{
extensions :  [ "ps", ".ps1" ]
lookup       :  /<#\[\s(+.)+\s\]#+>/
show         :  /(\1)/
}

Of course it should be possible to define several (lookup, show) tuples
for more complex languages

the grabbed topics should be merged with the other topics/symbols already in the tree,
and if the user press the toggle button then the topics tree should only display
this extra items...

![1](https://user-images.githubusercontent.com/3254076/42113060-f483f98c-7be1-11e8-9d51-794ab8fe7df8.png)

**Comment by jrieken** [comment]
@IBIT-ZEE Is this a request for a generic outline view? We already do support outlines from multiple sources (extensions) and the tree would show them as siblings. Is there something else that's missing?
