### ISSUE TITLE
Feature request: Chrome coverage tool integration

### ISSUE THREAD

**Issue by walrus95** [Microsoft/vscode#53351]
I’d like an integration between the “coverage” tool in the Chrome developer tools and Visual Studio Code. I’m developing an Angular application, and I would like to see highlighted in Visual Studio Code the lines of code which have been executed by the running instance of Chrome. I would also like to see highlighted the files in the sidebar which contain lines that have been executed in Visual Studio Code, similar to how files are highlighted when using the Git integration.

Thank you.

**Comment by Tyriar** [comment]
This will come in naturally when Electron gets updated to 59+, look out for Electron updates in the release notes

**Comment by Tyriar** [comment]
Oh I misunderstood, I think you should report this against the Chrome Debugger extension https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome
