### ISSUE TITLE
Working directory doesn't appear in terminal prompt on startup or reload

### ISSUE THREAD

**Issue by Bravo555** [Microsoft/vscode#53355]
Issue Type: <b>Bug</b>

1. Open terminal
2. Use command "Reload window"
3. Terminal prompt doesn't show current working directory.
Expected result: terminal shows current working directory.

It's not that bad because you can always use `clear` in terminal to make the working dir reappear.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:47:35.732Z)
OS version: Linux x64 4.15.0-23-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 1705)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.71GB (0.52GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.4
material-icon-theme|PKi|3.5.1
vscode-wakatime|Wak|1.2.2
Bookmarks|ale|0.19.1
code-gnu-global|aus|0.2.2
better-toml|bun|0.3.2
file-icons|fil|1.0.12
python|ms-|2018.6.0
atom-keybindings|ms-|3.0.4
cpptools|ms-|0.17.5
rust|rus|0.4.5
cmake|twx|0.0.17
quokka-vscode|Wal|1.0.132

</details>

**Comment by Tyriar** [comment]
Can you show screenshots of before/after and what you expect to show?

**Comment by Bravo555** [comment]
Right now:
![image](https://user-images.githubusercontent.com/10912424/42114354-0e014272-7bef-11e8-904d-e18899674e5b.png)
Expected result:
![image](https://user-images.githubusercontent.com/10912424/42114361-1735aba8-7bef-11e8-88db-3eade3d6cb7a.png)

**Comment by Tyriar** [comment]
This is what I see:

![image](https://user-images.githubusercontent.com/2193314/42178760-651e6636-7de6-11e8-91a6-9d0a90bc6d0a.png)

I think the root cause of this is https://github.com/Microsoft/vscode/issues/48136
