### ISSUE TITLE
Allow language plugins to overrule built-in language modes only if the file extension *and* the first line match

### ISSUE THREAD

**Issue by mserajnik** [microsoft/vscode#53350]
For the purpose of easier differentiation between `file extension` and `extension` (in the sense of `extension for VS Code`), I am calling the latter `plugin`.

I am currently developing a language plugin for VS Code. The language I am developing it for usually comes with either its own file extension (let's call it `.myext`) or simply `.txt` (it's just a scripting language).

I have run into the issue that I am not sure how to tell VS Code to only use my plugin when the first line matches a specific string when opening `.txt` files. Afaik, this is currently not possible (hence the _feature request_). I have not found any information that tells me otherwise and the [contribution points](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributeslanguages) article does not go into details about how exactly VS Code chooses a language mode when applying the three mentioned rules.

From what I have read [here](https://github.com/Microsoft/vscode/issues/10915) and [here](https://github.com/PranayAgarwal/vscode-hack/issues/1), there have been some changes last year that allow language plugins that match the file extension __and__ the first line of a file to get precedence over a plugin that just matches one of the two. But this does not seem to work with any built-in language modes. As soon as I set a file extension match for `.txt` (or other file extensions I do not have specific plugins installed for) in my plugin, VS Code __always__ activates my plugin when opening such a file and disregards the _first line_ match I have also set up specifically to make sure VS Code does not activate my plugin for "any old" `.txt` file.

What I think should happen is that when my plugin is the only one that contributes to `.txt` files and I have a file extension match __and__ a _first line_ match set up, these two matches should behave like a logical `AND` (`&&`); only if both are `true`, VS Code should use my extension over the built-in language mode for _plain text_. The more sophisticated solution would probably be to let the plugin developer choose if he wants to apply a `AND` or an `OR` rule to these matches. Or a weight-based system as described in #10915.

I hope it is somewhat clear what the issue is. If not, let me know and I will provide an example extension that demonstrates what I am talking about.

**Comment by mserajnik** [comment]
As a side note: I thought there might exist a workaround for my specific issue by only setting up a _first line_ match. However, this does not work; in such a case (where I specifically omit the `.txt` extension match from my plugin), VS Code __never__ chooses my plugin when opening `.txt` files where the first line matches what I have specified.

**Comment by alexandrudima** [comment]
I will try to see if I can summarise the request... Today, the semantics of `contributes.languages.extensions` and `contributes.languages.firstLine` is OR. 

That is to say, take for example the registration for XML:

```
...
			"extensions": [
				".xml",
				".xsd",
				".ascx",
				".atom",
				".axml",
				".bpmn",
				".config",
				".cpt",
				".csl",
				".csproj",
				".csproj.user",
				".dita",
				".ditamap",
				".dtd",
				".dtml",
				".fsproj",
				".fxml",
				".iml",
				".isml",
				".jmx",
				".launch",
				".menu",
				".mxml",
				".nuspec",
				".opml",
				".owl",
				".proj",
				".props",
				".pt",
				".publishsettings",
				".pubxml",
				".pubxml.user",
				".rdf",
				".rng",
				".rss",
				".shproj",
				".storyboard",
				".svg",
				".targets",
				".tld",
				".tmx",
				".vbproj",
				".vbproj.user",
				".vcxproj",
				".vcxproj.filters",
				".wsdl",
				".wxi",
				".wxl",
				".wxs",
				".xaml",
				".xbl",
				".xib",
				".xlf",
				".xliff",
				".xpdl",
				".xul",
				".xoml"
			],
			"firstLine" : "(\\<\\?xml.*)|(\\<svg)|(\\<\\!doctype\\s+svg)",
...
```

Then an `.xml` file which begins with an empty first line (does not match `firstLine` regex) will still be opened as XML.

You would like for the semantics between these two to be AND. I don't think we will ever change the existing semantics, but perhaps we could add some sort of configuration option in the registration.

But IMHO this is pretty niche request, it seems to me that if you invent a new language, your new language deserves a new file extension.

**Comment by mserajnik** [comment]
@alexandrudima

Thank you for taking the time to have a look.

> But IMHO this is pretty niche request, it seems to me that if you invent a new language, your new language deserves a new file extension.

I do agree. The issue mainly came up because there is already a huge amount of code in the language the plugin is for out there that uses the `txt` extension.

I am not the inventor of the language, but I think this probably happened because of two reasons:

+ There has not been much in the terms of syntax highlighting or even IDE support for it (aside from a plugin for Sublime Text, one for Notepad++ and mine for VS Code, I do not know of any others), thus making a custom extension pretty "unnecessary".
+ The runtime natively only runs on Windows where `txt` is just a convenient default extension to use – files with custom extensions (or files with no extension) require at least a one-time manual setup to be able to open them by double-clicking. Given that the language is (intended to be) simple enough to pick up for people who have not touched anything else programming-related before, the developer might have thought that it is best to keep it as simple as possible for beginners, therefore just choosing `txt`.

Afaik, the custom extension that is now available came a while later, but people still tend to use `txt` – probably because they are used to it or older tutorials do not mention the custom extension.

> […] but perhaps we could add some sort of configuration option in the registration.

This would be neat. The simplest thing I can think of is a flag like `only override built-in language modes if extension AND firstLine match` – I am not sure how to word that more efficiently though. :D

As I have mentioned, this apparently works out of the box for plugins, where a plugin that matches both gets precedence over one that only matches either/or.

But after some consideration, I can also see how your current default for overriding built-ins makes sense, because it is generally safe to assume that a language plugin provides more/additional functionality than a built-in mode, so it should always get precedence.

In any case, it is certainly not a huge issue and the easier thing to do might probably be just educating developers to use the custom extension. Feel free to close the issue if you do not think such a flag/option is something you are going to add – and thank you for the great code editor! :)
