### ISSUE TITLE
search exclusion does not work with .folder/**/*.* pattern

### ISSUE THREAD

**Issue by zpdDG4gta8XKpMCd** [microsoft/vscode#53354]
Visual Studio Code - Insiders
Version: 1.25.0-insider
Commit: b7e6e04666ca8dde560b69081c43365dce77d12a
Date: 2018-06-22T05:17:08.689Z
Electron: 2.0.2
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Steps to Reproduce:

1. create a folder named `.folder`, to this folder add `test.txt` file with `test` in it
2. add `"search.exclude": { ".folder": true }` to `settings.json` or type `.folder/**/*.*` to `files to exclude` field in `Search` tab
3. search for `test`
4. observe results are still found in `test.txt` despite being instructed to omit 

Does this issue occur when all extensions are disabled?: Yes

**Comment by aleksey-bykov** [comment]
i followed the tips, and still have problem, please make it clear what more info you need

**Comment by roblourens** [comment]
- Is test.txt open?
- If not, please follow the steps at the bottom of the page to get the logs
