### ISSUE TITLE
Button to hide dotfiles/configs in Explorer

### ISSUE THREAD

**Issue by NavyAdmiral** [Microsoft/vscode#53369]
Add a button to hide common dotfiles/configs:
![example](https://i.imgur.com/Yy5Orj1.png)
Possibly here:
![location](https://i.imgur.com/PtiWpx7.png)

**Comment by roblourens** [comment]
You can hide them with the `"files.exclude"` setting. Is that like what you are thinking of?

**Comment by NavyAdmiral** [comment]
@roblourens yes, I want to achieve the same effect with a button if it makes sense.

**Comment by roblourens** [comment]
Ok so this would be a button to toggle `files.exclude`, similar to the button we have in search to toggle whether exclude patterns are applied.
