### ISSUE TITLE
command 'test' not found

### ISSUE THREAD

**Issue by Tech-49** [Microsoft/vscode#53367]
I posted this issue before as well, someone has closed this before I provide more details.

One more time -- My issue is when I tried to copy paste something it gives me an error at bottom right side called "command 'test' not found".

I uninstalled VSCODE 2-3 times no luck.

I also don't have anything under my user's extension folder -- C:\Users\Hardik-pc\.vscode\extensions.

Here is how you can reproduce this issue.

Step 1:
Create sample file called sample.php

Step 2:
Put this line -- echo "Sample file"

Step 3:
try to copy line by pressing CTRL+c

Step 4:
try to paste in next line -- under the notification window, It's saying "command 'test' not found.

FYI -- I am using Windows 8.

Hope I explained it very well.

**Comment by roblourens** [comment]
It sounds like you might have a keybinding set up for a command named 'test' that doesn't exist. Can you check your keybindings?

**Comment by Tech-49** [comment]
You are right!

It was keybinding, I don't how it gets there, I removed it and working just fine now.

Thank you, you can close this now.
