### ISSUE TITLE
Fail to disable an extension pack extension

### ISSUE THREAD

**Issue by x-strong** [Microsoft/vscode#53366]
- VSCode Version:1.25.0-insider
```
Version: 1.25.0-insider
Commit: 6ca99aca80e80224f1c0bd4370c6ec4941c3bc54
Date: 2018-06-29T09:03:04.490Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64
```
- OS Version: Windows 10 Enterprise 1803(17134.112)

Steps to Reproduce:

1.Install an extension pack, for example 'Java Extension Pack' and reload after installing the extension pack.
2.Try to disable the extension pack, and then a comfirm dialog appears with message 'Would like to disable the dependencies of the extension aolso?', you can't not disable the extension pack extension if you click the Yes button, with a popup error message 'Cannot disable extension 'XXX'. Extension 'YYY' depends on this', but the No can.

![confirm to disable extension and its dependencies](https://user-images.githubusercontent.com/3232261/42131316-3f1f932e-7d32-11e8-89ab-af40a3d33d08.png)
![disable extension failed](https://user-images.githubusercontent.com/3232261/42131319-45be4e14-7d32-11e8-931a-52b3ba6b2108.png)

So is that a bug of VSC? #27336

Does this issue occur when all extensions are disabled?: N/A

**Comment by roblourens** [comment]
>you can't not disable the extension pack extension if you click the Yes button

What happens if you click the Yes button?

**Comment by x-strong** [comment]
@roblourens See the updated version of the problem description, please : )

**Comment by sandy081** [comment]
@x-strong I cannot reproduce it. Can you please let me know what are the extensions you have installed and which extension pack you are trying to disable?

**Comment by svict4** [comment]
I am getting this too, unsure if it's intended or not. However, I'd expect `Disable all extensions` to ignore non-core dependency warnings.

![image](https://user-images.githubusercontent.com/1137112/42851144-6a6739e4-8a6e-11e8-9b00-391d525815c3.png)

**Comment by sandy081** [comment]
@svict4 Are you trying to disable all extensions or a specific extension with dependencies?

**Comment by svict4** [comment]
@sandy081 all extensions

**Comment by sandy081** [comment]
@svict4 Please let me know the list of extensions you have installed so that I can reproduce it.
