### ISSUE TITLE
Typings are not available with ES6 module system

### ISSUE THREAD

**Issue by xabikos** [Microsoft/vscode#5336]
- VSCode Version: 1.0.0
- OS Version: Windows 7 SP1

In a vary simple project that consists of two files 
```
-- apiService.js
-- index.js
```

The apiService code looks like: 
```
var axios = require('axios');
//import axios from 'axios';

const service = {
    /**
     * Triggers a get http request
     * @param {string} url - The url of the request
     */
    get(url) {
        return axios.get(url);
    }
};

export default service;
```
When requiring the axios library in this way there is intellisense provided by typings which I have install for axios libary as seen in the following picture
![valid](https://cloud.githubusercontent.com/assets/487416/14562123/3420ed80-031b-11e6-8e72-2fc64fd71463.png)

If we use the ES6 way of importing the library (swap the commenting if first two lines) then the intellisense is gone.

What I noticed though is that this import syntax works perfectly fine when importing my modules as indicating here
![index](https://cloud.githubusercontent.com/assets/487416/14562221/bbadaf72-031b-11e6-8018-f44f87cbdf98.png)

My jsconfig file looks like 
```
{
    "compilerOptions": {
        "module": "es6"
    },
    "exclude": [
        "node_modules"
    ]
}
```
And I tried the other available options for module.

**Comment by egamma** [comment]
The axios typings does not use ES6 default exports, therefore you cannot use ES6 imports. The recently added compiler option `allowSyntheticDefaultImports` allows you to still use the ES6 style import (see [compilerOptions](https://www.typescriptlang.org/docs/handbook/compiler-options.html).

Therefore changing the jsconfig.json as shown below fixes this.
```json
	"compilerOptions": {
		"target": "es6",
		"allowSyntheticDefaultImports": true
	},
```

**Comment by HugoMcPhee** [comment]
This issue still occurs for me even with allowSyntheticDefaultImports  set to true (inside my js projects jsconfig.json file).

The library in my case is "babylonjs"
as soon as `import BABYLON from "babylonjs"` is present, the intellisense stops working

Is it a requirement for the babylonjs library to be typescript compiled with the allowSyntheticDefaultImports option, or is there something users can do to have intellisense work (without needing the library to change)?
