### ISSUE TITLE
New VS Code Insiders 1.25.0 "deleted from disk" change breaks our C/C++ extension functionality

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#53368]
We call vscode.workspace.openTextDocument with a vscode.Uri that has scheme "untitled" in an attempt to open a new doc, but VS Code is blocking us from creating the document and instead causing some "deleted from disk" document to be opened.

This repros with the C/C++ extension (do C/Cpp: Edit Configurations... to create the c_cpp_properties.json, then delete it and repeat the command).

See function handleConfigurationEditCommand at https://github.com/Microsoft/vscode-cpptools/blob/master/Extension/src/LanguageServer/configurations.ts

**Comment by bpasero** [comment]
@sean-mcmanus can you please provide a reproducible case with a simple hello world extension to demonstrate what issue you are running in?

**Comment by bpasero** [comment]
I tried to reproduce with this sample and could not:

```typescript
'use strict';
// The module 'vscode' contains the VS Code extensibility API
// Import the module and reference it with the alias vscode in your code below
import * as vscode from 'vscode';

// this method is called when your extension is activated
// your extension is activated the very first time the command is executed
export function activate(context: vscode.ExtensionContext) {

    // Use the console to output diagnostic information (console.log) and errors (console.error)
    // This line of code will only be executed once when your extension is activated
    console.log('Congratulations, your extension "test-ts" is now active!');

    // The command has been defined in the package.json file
    // Now provide the implementation of the command with  registerCommand
    // The commandId parameter must match the command field in package.json
    let disposable = vscode.commands.registerCommand('extension.sayHello', () => {
        // The code you place here will be executed every time your command is executed

        // Display a message box to the user
        // vscode.window.showInformationMessage('Hello World!');

        vscode.workspace.openTextDocument(vscode.Uri.parse('untitled:/Users/bpasero/Desktop/end-ts/src/extension222.ts')).then(doc => {
            vscode.window.showTextDocument(doc);
        });
    });

    context.subscriptions.push(disposable);
}

// this method is called when your extension is deactivated
export function deactivate() {
}

```

**Comment by sean-mcmanus** [comment]
Why are you trying to reproduce it with a Hello World example when I have a repro with the C/C++ extension at https://github.com/Microsoft/vscode-cpptools/tree/release ? Our repro should be pretty simple to use. I would guess something with our more complicated code is the key to reproducing the bug. The same version of our C/C++ extension repros the issue on Insiders VS Code, but not the 1.24.1 VS Code (using identical settings), so it seems like the best explanation is that it's an Insiders regression.

**Comment by sean-mcmanus** [comment]
Oh...my co-worker wasn't able to reproduce the bug -- there must be something strange with my VS Code Insiders. I deleted all my settings (and disabled other extensions) so I don't understand how I could be getting different behavior from other machines or my VS Code non-Insiders. I'll try reinstalling VS Code Insiders.

**Comment by sean-mcmanus** [comment]
It looks like our call to document.save() is failing -- since the document fails to save, it doesn't exist when we later call open on it. Do you know of anything that could cause document.save() to fail with Insiders or how to get diagnostics on the failure reason?

**Comment by bpasero** [comment]
> Oh...my co-worker wasn't able to reproduce the bug -- there must be something strange with my VS Code Insiders. I deleted all my settings (and disabled other extensions) so I don't understand how I could be getting different behavior from other machines or my VS Code non-Insiders. I'll try reinstalling VS Code Insiders.

Maybe you have the setting `workbench.editor.closeOnFileDelete` enabled and others do not?

**Comment by sean-mcmanus** [comment]
@bpasero I have closeOnFileDelete set to true for VS Code Insiders and non-Insiders -- it's the default. The bug repros with no settings modifications at all (just defaults).

**Comment by bpasero** [comment]
@sean-mcmanus yes I meant to ask if you have `workbench.editor.closeOnFileDelete` configured to `false` (which would be non-default).

Again, please try to distill a reproducible case with a simple hello world extension. The fact that it does not even reproduce for someone else on your team makes me wonder if its related to a configuration you have. You could also try to run "`code --user-data-dir <some folder>`" to start code with a truly fresh data directory and settings to see if it reproduces.

**Comment by sean-mcmanus** [comment]
1. Using --user-data-dir doesn't fix the issue.
2. It repros with a simple hello world extension using the code below. The 1st time the code runs, it creates/shows the file, but after the delete of the file, the save is silently failing even though a success result is returned. I'm on Windows 10. Is there some more logging I could enable? I could try to debug the issue if you can point me to a relevant location.

`
    let disposable2: vscode.Disposable = vscode.commands.registerCommand("someCommandInPackageJson", () => {
        let fullPathToFile: string = "somePathThatExists\\c_cpp_properties.json"; // c_cpp_properties.json shouldn't exist
        let filePath: vscode.Uri = vscode.Uri.parse("untitled:" + fullPathToFile);
        vscode.workspace.openTextDocument(filePath).then((document: vscode.TextDocument) => {
            let edit: vscode.WorkspaceEdit = new vscode.WorkspaceEdit();
            edit.insert(document.uri, new vscode.Position(0, 0), "mod");
            vscode.workspace.applyEdit(edit).then((status) => {
                document.save().then((success: boolean) => {
                    if (!success) {
                        vscode.window.showErrorMessage("this doesn't occur but the file is never saved still, the 2nd time");
                    }
                    this.propertiesFile = vscode.Uri.file(fullPathToFile);
                    vscode.workspace.openTextDocument(this.propertiesFile).then((document: vscode.TextDocument) => {
                        vscode.window.showTextDocument(document);
                    });
                });
            });
        });
    });
`

**Comment by bpasero** [comment]
@sean-mcmanus with the help of @jrieken we found the issue is with the way the untitled resource is being created, it works fine if you change to:

```typescript
let fullPathToFile: string = "somePathThatExists\\c_cpp_properties.json"; // c_cpp_properties.json shouldn't exist
let filePath: vscode.Uri = vscode.Uri.file(fullPathToFile).with({ scheme: "untitled:"});
```

This will produce the correct `URI` for our system.

**Comment by sean-mcmanus** [comment]
Thanks a lot -- that fixed it (although "untitled" should not have a colon after it). Still seems like VS Code Insiders might have a bug, but I'm fine with the workaround. https://github.com/Microsoft/vscode-cpptools/pull/2235

**Comment by bpasero** [comment]
@sean-mcmanus 

> Still seems like VS Code Insiders might have a bug

Why do you say that?
