### ISSUE TITLE
Broken highlight with generic TSX component (TS 2.9) 

### ISSUE THREAD

**Issue by ColCh** [Microsoft/vscode#53362]
Issue Type: <b>Bug</b>

Code example

```tsx
<Bar>
  {({ name }) => (
    <HelloWorld<
      Foo>
      name={name}
      variants={['TEST']}
    />
  )}
</Bar>
```

Renders like this:

![image](https://user-images.githubusercontent.com/599439/42118348-0aaf8b94-7c0b-11e8-9256-08803ef8d07d.png)

Actions to make it look OK (would help debug may be):

```diff
<Bar>
  {({ name }) => (
    <HelloWorld<
      Foo>
      name={name}
-     variants={['TEST']}
    />
  )}
</Bar>
```

```diff
<Bar>
  {({ name }) => (
-   <HelloWorld<
-     Foo>
+   <HelloWorld<Foo>
      name={name}
      variants={['TEST']}
    />
  )}
</Bar>
```

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.40GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron --disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#632
