### ISSUE TITLE
Reinstalled the VsCODe and now one more Issue :terminal is not working

### ISSUE THREAD

**Issue by drifter1007** [Microsoft/vscode#53373]
Issue Type: <b>Bug</b>

I just reinstalled VSCODE and just opened the terminal and its not working
its just stuck at cursor blinking .

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 6.0.6001

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Memory (System)|3.94GB (1.13GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Program Files\Microsoft VS Code\bin\..\resources\app\out\cli.js|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.12
python|ms-|2018.6.0
cpptools|ms-|0.17.5

</details>

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/43169#issuecomment-401534695
