### ISSUE TITLE
Reinstalled the VsCODe and now 1+one more Issue :Unable to install some extensions 

### ISSUE THREAD

**Issue by drifter1007** [Microsoft/vscode#53377]
I just reinstalled the VsCode and i am facing one more issue here while installing some extension its giving EPERM error.I tried installing while vscode running as admin.I also tried installing through VSIX.but no chance .
Help me guyz.
[https://www.dropbox.com/s/f86lakm7c7w8vur/eperm%20error.jpg?dl=0](url)

**Comment by drifter1007** [comment]
@sandy081   any clue to  solve this eperm error .
@roblourens

**Comment by sandy081** [comment]
@drifter1007 On what platform are you on? Is it happening with all extensions or some extensions?

**Comment by beastdestroyer** [comment]
@sandy081 Tried that (Using win10 April 2018 update, inisders build 2018-06-29) and my update to Material Theme did complete successfully

**Comment by drifter1007** [comment]
@sandy081  Hey I  am using it on win7 .Its happening to only some extension.

**Comment by drifter1007** [comment]
@sandy081 Thanks bro it  worked :please go to extensions installation folder (Use command Open Extensions Folder) and delete the folder belongs to the extension and re-try.
