### ISSUE TITLE
Reg Color theme, light+, selected text not proper

### ISSUE THREAD

**Issue by hsmgitr** [Microsoft/vscode#53374]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.17134
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.16.1

---

Steps to Reproduce:

1. Select Preferences->Color Theme -> Light+ (default)
2. Search for some text across files. The selected text in the file cannot be read because of improper colors.

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
Version 1.18 is rather old, can you try in the latest version?

And can you share a screenshot to show exactly what the problem is?
