### ISSUE TITLE
workbench.settings.openDefaultKeybindings && workbench.action.openRawDefaultKeybindings

### ISSUE THREAD

**Issue by Enteleform** [Microsoft/vscode#53372]
**New Setting:** `workbench.settings.openDefaultKeybindings`
**New Action:** `workbench.action.openRawDefaultKeybindings`

-----

Currently, `{"workbench.settings.openDefaultSettings": false}` allows users to disable the side-by-side default/user settings view, instead allowing us to view our customized settings file in isolation when using the `workbench.action.openSettings` command.

A corresponding option does not yet exist for `workbench.action.openGlobalKeybindingsFile`, although it would be equally useful.

Additionally, something like @sandy081's `workbench.action.openRawDefaultSettings` contribution in https://github.com/Microsoft/vscode/commit/f8c9ed837ae3306abc55051c44fc32de6e77d6b9 should be implemented to allow access of the default keybindings if `workbench.settings.openDefaultKeybindings` is disabled.

**Comment by njkevlani** [comment]
I'd like to take solve this issue. @sandy081 any suggestions? What files will I have to work with for this?

This would be my first contribution to VSCode!

**Comment by sandy081** [comment]
References:

- https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/preferences/browser/preferencesService.ts#L170 for Opening raw default settings

- https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/preferences/browser/preferencesService.ts#L265 for not opening default settings

**Comment by njkevlani** [comment]
Hey guys, I got some work around for showing user settings in `keyboindingEditor` (GUI) (yet not pushed in my PR), but I had a question.

If we set `workbench.settings.openDefaultKeybindings`:`false` and open `kebindingEditor` (GUI), it should show only user keybinding settings. But then how should we handle `Show Default Keybindings` and `Show User Keybindings` in menu (3 dot at right corner)?
