### ISSUE TITLE
Mark latest release as latest

### ISSUE THREAD

**Issue by artagel** [Microsoft/vscode#53371]
When using the API https://api.github.com/repos/Microsoft/vscode/releases/latest it shows 1.11.2 as the latest release, but the latest is actually 1.24.1.  Please mark the actual latest release as latest, so i can easily script detection of new versions.
In the meantime I'm using https://api.github.com/repos/Microsoft/vscode/tags and parsing the tags, but there's no data in the github api data so it makes it difficult to find the latest, we can only rely on the version number.

**Comment by jrieken** [comment]
assigning to endgame master

**Comment by isidorn** [comment]
Could not find GitHub ui to change this currently our first release is marked as latest 
https://github.com/Microsoft/vscode/releases/tag/1.11.2

It seems like release should be created via GitHub ui in order for this latest release tag to be respected
https://github.community/t5/How-to-use-Git-and-GitHub/Why-last-release-is-not-marked-as-quot-latest-release-quot/td-p/1762

@joaomoreno do we want to do this?

**Comment by joaomoreno** [comment]
We do not use GitHub releases. We would disable that tab if we could.

**Comment by artagel** [comment]
Is there a public api that provides the latest version of vscode?

**Comment by joaomoreno** [comment]
Sure:

```
https://vscode-update.azurewebsites.net/api/update/PLATFORM/QUALITY/latest
```

Where `PLATFORM` can be:

- `win32`, `win32-x64`
- `linux-ia32`, `linux-x64`
- `darwin`

And `QUALITY` can be:

- `stable`
- `insider`

Example:

```
GET https://vscode-update.azurewebsites.net/api/update/linux-ia32/insider/latest
HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Length: 414
Content-Type: application/json; charset=utf-8
Date: Tue, 03 Jul 2018 07:21:29 GMT
ETag: W/"18f-HHLRbtAoGcgE2iPJj1jpa65KHCs"
Server: Microsoft-IIS/10.0
Set-Cookie: ARRAffinity=63c32fb386c206cc2985a7b1c61bb36d046bad7a343412f64893133bcd81a1d8;Path=/;HttpOnly;Domain=vscode-update.azurewebsites.net
Vary: Accept-Encoding
X-Commit: 8651236bc22654032f4215e347c01b61d9f2aec0
X-Powered-By: Express
X-Powered-By: ASP.NET

{
    "hash": "beb4d21a64af6c346d8ca0f48c7b500f9aab11e7",
    "name": "1.25.0-insider",
    "productVersion": "1.25.0-insider",
    "sha256hash": "2b989f0aea2a014d808344044e60212e789a9ba7d7135c3e29b06964d85d54bd",
    "timestamp": 1530534938780,
    "url": "https://az764295.vo.msecnd.net/insider/26eb2a9af5827d71e1f65096c0ce712c5ad2740d/code-insider-1.25.0-1530535384_i386.tar.gz",
    "version": "26eb2a9af5827d71e1f65096c0ce712c5ad2740d"
}
```
