### ISSUE TITLE
VSCode Freezes when deleting assets

### ISSUE THREAD

**Issue by mfour-merickson** [Microsoft/vscode#53384]
- VSCode Version:

1.24

- OS Version:

OSX 10.12.6

Steps to Reproduce:

1. Launch code with extensions disabled

`code --disable-extensions`

Note: I have also tried this with latest code insiders and the crash occurs there as well

2. Open any project, in this case it was a brand new project 

3. When attempting to delete any file (in this case, package-lock.json)

4. As you can see by the screenshot, code eventually times out and displays the familiar dialog

Does this issue occur when all extensions are disabled?: Yes/No

Yes

![image](https://user-images.githubusercontent.com/31225533/42128326-8f5407ce-7c5d-11e8-96e3-11f333b31f31.png)

**Comment by mfour-merickson** [comment]
Screenshot from same issue with latest Code Insiders

![image](https://user-images.githubusercontent.com/31225533/42128350-346bc486-7c5e-11e8-8a2a-85d83e0b191e.png)

**Comment by roblourens** [comment]
Does it happen if you set `files.useExperimentalFileWatcher: true`?

Sounds similar to #53053

**Comment by mfour-merickson** [comment]
@roblourens Thanks for the suggestion, it seems to be working at the moment with this change.  I will continue to monitor, hopefully this is the permanent solution

**Comment by bpasero** [comment]
@mfour-merickson are you just deleting a singe file or a large folder? does this happen for any folder you open?
