### ISSUE TITLE
Providing an option to copy the hover text to the clipboard

### ISSUE THREAD

**Issue by gertcuykens** [microsoft/vscode#53386]
ref: https://github.com/Microsoft/vscode-go/issues/1742

https://user-images.githubusercontent.com/16890566/42074807-d904ff04-7b22-11e8-9e47-6809b6a0625f.gif

**Comment by gr2m** [comment]
The suggestion of copying the text from the hover only works for simple types. Types with too many keys are abbreviated and cannot be copied in full

<img width="541" alt="image" src="https://user-images.githubusercontent.com/39992/129783997-ae874562-fb27-4926-a7ce-dce2680be62e.png">
