### ISSUE TITLE
New command to open a folder for extension writers

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#5338]
- [x] win @jrieken 
- [x] mac @isidorn 
- [x] linux @waderyan 

We introduced a new command that is exposed to extensions to open a folder in the same or new window
* the command identifier is `vscode.openFolder` and it accepts two optional arguments `uri` and `newWindow`
* if you ommit the `uri` to open, it is also possible to bring up the native file dialog to let the user make the decision

**Comment by waderyan** [comment]
Command works on Linux, but I'm not sure how to pass in arguments. I've looked through the docs, but can't find help. Can someone point out how to do this? 

I'm typing the following into the command palette. 

![image](https://cloud.githubusercontent.com/assets/2449568/14833660/42cc602e-0bb5-11e6-8f9c-9cbf3f5b12ce.png)

**Comment by bpasero** [comment]
@waderyan this command is about writing an extension and executing the command through our command API, not about using the command palette :)

**Comment by waderyan** [comment]
@bpasero ha ok got it now.

**Comment by waderyan** [comment]
Works!

**Comment by bpasero** [comment]
Thanks
