### ISSUE TITLE
No intellisense for Node.JS even if we use jsconfig.json

### ISSUE THREAD

**Issue by tbhaxor** [Microsoft/vscode#53387]
- VSCode Version: `1.231`
- OS Version: `Linux h3ll 4.17.2-1-ARCH #1 SMP PREEMPT Sat Jun 16 11:08:59 UTC 2018 x86_64 GNU/Linux`

This solution was recommended on one of the [stackoverflow post](https://stackoverflow.com/questions/36235242/visual-studio-code-intellisense-not-working-for-javascript)

**my jsconfig.json**
```json
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs"
    },
    "exclude": [
        "node_modules"
    ]
}
```
Steps to Reproduce:

**for node variables**
_for some node variables like process_

1. create a `js` file and edit with `code [FILENAME].js`
2. type any `nodejs` variable `process`
3. you wont see any intellisense
![image](https://user-images.githubusercontent.com/28386721/42129928-d3326eac-7cf0-11e8-8ee0-2bfbc6353cae.png)

**for node module with ( . )**
_for some node modules like module_
1. create a `js` file and edit with `code [FILENAME].js`
2. type any `nodejs` variable `module.`
3. you wont see any intellisense
![image](https://user-images.githubusercontent.com/28386721/42129881-2e414f3a-7cf0-11e8-9ac4-d69f2300865f.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by tbhaxor** [comment]
well done microsoft support team :angry:

**Comment by mjbvz** [comment]
You are on an old version of VS Code (1.23).  Does this reproduce in the [latest VS Code build](https://code.visualstudio.com/insiders/) with all extensions disabled?

Other things to try:

- Add  `require` call anywhere in the file. This will tell VS Code that you are working with node code rather than plain browser code.

- You can also tell VS Code that you are using node by installing the node typings manually: 

```ts
$ npm install --save-dev @types/node
```

**Comment by tbhaxor** [comment]
@mjbvz i am using arch linux and vscode is not officially supported by arch linux but downloaded from its AUR repository. And on aur its the latest version :smile:

**Comment by tbhaxor** [comment]
thnkx @mjbvz  problem is solved
