### ISSUE TITLE
Select to Bracket for HTML tags

### ISSUE THREAD

**Issue by Janjuks** [Microsoft/vscode#53382]
- VSCode Version: 1.24.1

In Visual Studio this same feature works nice for HTML tags as well. That is - it selects text from opening tag to closing tag. Can we have the same in VS Code? Right now it selects either opening or closing tag, depending where the cursor is.

Steps to Reproduce:

1. Put cursor inside HTML opening or closing tag
2. Execute `Select to Bracket` command
3. Only opening or closing tag will be selected

**Comment by ramya-rao-a** [comment]
Use the `Emmet: Balance(outward)` command.
