### ISSUE TITLE
duplicate entries @ vscode://defaultsettings/keybindings.json

### ISSUE THREAD

**Issue by Enteleform** [Microsoft/vscode#53398]
Just disabled all of the default keybindings to organize & remap the ones I'm going to use & noticed that there are some duplicates:

```typescript
import equals from "fast-deep-equal"

const keyBindings = [
  // keybindings.json entries goes here
]

const checked    = []
const duplicates = []

keyBindings.forEach(a => {
  if( checked.some(b => equals(a, b)) )
    {duplicates.push(a)}
  checked.push(a)
})

console.log(duplicates)

// RESULT:
// [
//   {"key":"alt+1",         "command":"workbench.action.openEditorAtIndex1"                                                                  },
//   {"key":"alt+2",         "command":"workbench.action.openEditorAtIndex2"                                                                  },
//   {"key":"alt+3",         "command":"workbench.action.openEditorAtIndex3"                                                                  },
//   {"key":"alt+4",         "command":"workbench.action.openEditorAtIndex4"                                                                  },
//   {"key":"alt+5",         "command":"workbench.action.openEditorAtIndex5"                                                                  },
//   {"key":"alt+6",         "command":"workbench.action.openEditorAtIndex6"                                                                  },
//   {"key":"alt+7",         "command":"workbench.action.openEditorAtIndex7"                                                                  },
//   {"key":"alt+8",         "command":"workbench.action.openEditorAtIndex8"                                                                  },
//   {"key":"alt+9",         "command":"workbench.action.openEditorAtIndex9"                                                                  },
//   {"key":"ctrl+h",        "command":"editor.action.startFindReplaceAction"                                                                 },
//   {"key":"ctrl+p",        "command":"workbench.action.quickOpen"                                                                           },
//   {"key":"ctrl+pagedown", "command":"workbench.action.nextEditor"                                                                          },
//   {"key":"ctrl+pageup",   "command":"workbench.action.previousEditor"                                                                      },
//   {"key":"ctrl+w",        "command":"workbench.action.closeActiveEditor"                                                                   },
//   {"key":"ctrl+d",        "command":"editor.action.addSelectionToNextFindMatch",      when:"editorFocus"                                   },
//   {"key":"up",            "command":"workbench.action.interactivePlayground.arrowUp", when:"interactivePlaygroundFocus && !editorTextFocus"},
// ]
```

-----

Also noticed a good amount of duplicates in the default settings, but they might be trickier to pick out due to the `when` property.

-----

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|61.59GB (50.97GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
alignment|ann|0.3.0
converter|bey|0.0.3
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
codealignment-vscode|cpm|2.0.19
jupyter|don|1.1.4
gitlens|eam|8.4.1
permute-lines|ear|0.0.9
sort-lines-by-selection|ear|0.0.3
vscode-npm-script|eg2|0.3.4
vscode-eval|exp|1.2.1
vscode-terminals|fab|1.11.7
code-runner|for|0.9.3
terminal|for|0.0.10
vscode-yarn|gam|1.6.0
macros|ged|1.2.1
vscode-settings-cycler|hoo|1.0.1
code-file-nav|jak|0.7.2
code-select-until|jak|0.6.0
vscode-text-pastry|jkj|1.2.0
node-module-intellisense|lei|1.5.0
vscode-json5|mrm|1.0.0
python|ms-|2018.6.0
sublime-keybindings|ms-|4.0.0
vscode-subword-navigation|ow|1.2.0
tsimporter|pmn|1.2.14
markdown-preview-theme-one-dark|rae|0.0.1
exchange-selection-start-end|san|2.0.0
guides|spy|0.9.2
whiteviz|spy|0.5.1
selectline-statusbar|tom|0.0.2
terminal-tabs|Tyr|0.2.0
change-case|wma|1.0.0
cursor-align|yo1|1.0.4
markdown-all-in-one|yzh|1.5.1
editor-functions|ent|0.0.1

(4 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
@Enteleform What is the source of `keyBindings`? Are they defaults from VS Code or also coming from other extensions?

I suppose, out of the product, we should do not have any duplicates

**Comment by Enteleform** [comment]
@sandy081 

Sorry about that, it seems that all of those were added by extensions. Just tested by disabling all extensions & re-running the script above.

On a related note - is there any way to disable keybindings/settings/command-palette-entries/etc. from being added automatically by extensions? Or to at least disable the vs-code default setting files from being active, using only values defined in the user setting files?

I'm hoping to attain a setup where every keybinding/setting/menu-item/etc. is explicitly defined by me.

Also - I'm currently aware of the user settings & keybindings files. Is there a user file for command-palette/context-menu/etc. entries? Or a way to override contributions/extension-files that persists through updates, as with `%APPDATA%\Sublime Text 3\Packages` in SublimeText? (*see: [**Package Control > Customizing Packages**](https://packagecontrol.io/docs/customizing_packages)*)

**Comment by sandy081** [comment]
@Enteleform You can disable the complete extension but not each contribution from it. 

Settings are always inherited from Default settings and are overridden by user settings.

There is no explicit file for commands and context menus. They all come from extension's `package.json` file.
