### ISSUE TITLE
Add TextMate Scopes for eval/package

### ISSUE THREAD

**Issue by jabacchetta** [Microsoft/vscode#53399]
As [documented on StackOverfow](https://stackoverflow.com/questions/51110201/italicize-javascripts-reserved-keywords-in-vs-code), I was able to target all of JavaScript's reserved keywords via TextMate with the exception of two:

1. `eval` (disallowed in strict)
2. `package` (unused future keyword)

It's not clear to me whether this is something that needs to be updated in the TextMate grammar or if support just needs to be added in VS Code.

For `eval`, a `support.function.eval.js` scope appears to make sense. With `package` not actually being used yet, I'm not sure what scope that would go under.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#634
