### ISSUE TITLE
No icon shown in the activity bar after VSCode update

### ISSUE THREAD

**Issue by ElSousou** [Microsoft/vscode#53392]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.17134
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.4.0
node-debug2|ms-|1.20.0
vscode-react-native|vsm|0.6.11

---

Steps to Reproduce:

1. Just launch VStudio Code: no icon other than parameters shows in the activity bar.

I tried to hide/show it, right click and select/unselect the different items (like shown on the attached screenshot). 

Reproduces without extensions: Yes
<img width="960" alt="screenshot" src="https://user-images.githubusercontent.com/13822404/42134692-33222078-7d41-11e8-937d-b6b141da0a0a.png">

**Comment by ElSousou** [comment]
- The 1.18.1 was automatically installed yesterday, so I thought it was the last version - my bad, I did not check.
- No other version was shown available when I used the "Search for updates button".
I downloaded the last 1.24.1 version and reinstalled it, problem fixed.
Problem fixed, sorry for time loss.

**Comment by roblourens** [comment]
No problem thanks for checking
