### ISSUE TITLE
node inspector discovery only looks at /json/list

### ISSUE THREAD

**Issue by pmlopes** [Microsoft/vscode#53391]
Some projects that expose a node inspector API might only implement the `/json` API, so the debugger could try to look up that resource in case the current one fails to load.

For more info see https://github.com/oracle/graal/issues/505

**Comment by roblourens** [comment]
Sure, we can check both.

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode-chrome-debug-core/commit/387267cf67cc204dd21dc811b5c5199af6c93d97

**Comment by octref** [comment]
@roblourens How to verify?

**Comment by roblourens** [comment]
There isn't an easy way to verify this, but code review should show that we now check the `/json` endpoint if checking the `/json/list` endpoint fails.

**Comment by octref** [comment]
OK, reviewed and verified.
