### ISSUE TITLE
vscode-insiders can't display chinese traditional

### ISSUE THREAD

**Issue by jerryc127** [Microsoft/vscode#53397]
- VSCode Version:1.25.0-insider
- OS Version: windows10 1803

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

I am already setting in the locale.json to "locale":"zh-tw",
I also install the Chinese traditional language pack.
It still shows the English rather than Chinese.

**Comment by dbaeumer** [comment]
@jerryc127 see my comments in the other issue :-). If you still see this can you please provide me with the following information:

- the content of the languagePacks.json file located at C:\Users\${your user}\AppData\Roaming\Code - Insiders where ${your user} is your user id
- the content of the clp directory located at the same location. You can zip the content.

And the commit id of the VS Code insider version you are using. Can be found in the help about dialog.

**Comment by jerryc127** [comment]
it was solved, thanks.
I try to reinstall the Chinese traditional language pack,
And it shows the error "Unable to write into the file because the file is dirty. Please save the file and try again."
According to #19161, I solved the problem.
