### ISSUE TITLE
develop php and python code advanced autocompletion speed so slowly

### ISSUE THREAD

**Issue by SFLAQiu** [Microsoft/vscode#53396]
Issue Type: <b>Feature Request</b>

Does anyone else have this problem?I asked a few of my friends, and so it was

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17134

**Comment by roblourens** [comment]
This sounds like an issue with extensions you're using for php/python intellisense. Please file specific issues with more details on those extensions.
