### ISSUE TITLE
Sash double clicks

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#5339]
- [x] win @alexandrudima 
- [x] mac @chrisdias 
- [x] linux @aeschli

You can now double click on the sash to resize it
* for the explorer sash, verify that the sidebar gets large enough to show you the file names without trimming
* for other viewlets the behaviour is to size the sidebar to its minimum allowed size
* for the panel as well
* for the diff editor it will size it equally (50, 50)
* when you have multiple editors open, it will size the two editors around a sash with half of the available width

**Comment by chrisdias** [comment]
looks nice.
