### ISSUE TITLE
VS Code status hang on "Scanning"

### ISSUE THREAD

**Issue by asalhani** [Microsoft/vscode#53402]
- VSCode Version:
![vs code version](https://user-images.githubusercontent.com/5410830/42137546-cee0d34e-7d76-11e8-8920-e1ec850672ce.JPG)

- OS Version:
![windows version](https://user-images.githubusercontent.com/5410830/42137553-e7a59dce-7d76-11e8-8efd-2defce145dc6.JPG)

Steps to Reproduce:

1. Open any midum to large size project.
2. Open a new VS code window and load diffrent project
2. On any of two loaded projects, navigate on some source files
3. Toggle code expantion by clicking (+) sign beside any function.
4. After short time, the VS code status in the bottom of 2nd project will hang on "Scanning" and the toggle (+, -) singns dissaper. 

Does this issue occur when all extensions are disabled?:  i did not try

**Comment by roblourens** [comment]
> After short time, the VS code status in the bottom of 2nd project will hang on "Scanning" and the toggle (+, -) singns dissaper.

It sounds like this is a feature from an extension. Is that right? Please file an issue on the repo for the extension you are using.
