### ISSUE TITLE
Match Entire Word doesnt work for $

### ISSUE THREAD

**Issue by wysisoft** [Microsoft/vscode#53401]
try to do a replacement of $ (match entire word) in text such as ...

	sort   = (!search.query && options.sort_empty) || options.sort;

		/**
		 * Fetches the specified sort field value
		 * from a search result item.
		 *
		 * @param  {string} name
		 * @param  {object} result
		 * @return {mixed}
		 */
		get_field = function(name, result) {
			if (name === '$score') return result.score;
			return getattr(self.items[result.id], name, options.nesting);
		};

		// parse options
		fields = [];
		if (sort) {
			for (i = 0, n = sort.length; i < n; i++) {
				if (search.query || sort[i].field !== '$score') {
					fields.push(sort[i]);
				}
			}
		}

		// the "$score" field is implied to be the primary
		// sort field, unless it's manually specified

**Comment by roblourens** [comment]
Can you give some more details about exactly what you are searching and replacing, what happens, and what you expect to happen?

**Comment by wysisoft** [comment]
how is this not clear? Open VSCODE. file->New File.
Type $asd123 into the editor
do a replace all and choose "Match Whole Word".
try to replace "a" with "x" and it wont, because you chose "Match Whole Word"
try to replace "$" with "x" and it will.

VSCODE 1.24.1

**Comment by roblourens** [comment]
This works for me. Which OS are you using?

Are you using the editor find, or search (ctrl+shift+f)?

**Comment by wysisoft** [comment]
![image](https://user-images.githubusercontent.com/15177964/42139293-548e7610-7d48-11e8-8cfa-a560d4b3d416.png)

windows 10, Ctrl+H

**Comment by roblourens** [comment]
Ok, I see the same. Your title says "doesnt work for $" so I thought you weren't expecting it to match.

I think this is by design because it matches the regex `\b\$\b`

**Comment by wysisoft** [comment]
Note that I wasnt selecting to use regular expressions. It replaces the $ character no matter where in the string it occurs. Are you saying VSCODE is incapable of replacing the $ character when matching that character only?

**Comment by roblourens** [comment]
> replacing the $ character when matching that character only?

I don't understand exactly what you expect to happen, please spell it out step by step.

**Comment by wysisoft** [comment]
I'm very suprised that VSCODE, Sublime, VS2017, Notepad++ all behave the same. I guess we can close this issue.
