### ISSUE TITLE
"There are no updates currently available" 

### ISSUE THREAD

**Issue by hickford** [Microsoft/vscode#5340]
Hi. I'm using Visual Studio Code 0.10.8 on Windows 7. I just read [version 1.0.0 has been released](https://code.visualstudio.com/Updates#_100-march-2016) but when I try Help / Check for updates nothing happens. Eventually I get a message "There are no updates currently available" 

I'm in an office network behind a proxy. Perhaps Code can't access the internet. If so, it would be better to give a more accurate message "could not connect to check for updates, here's a link to check for updates yourself"

**Comment by mlaffargue** [comment]
Same problem here, I've the 0.10.6 version and it says "no update available" (though 1.2.0 is out).
Proxy is ok I can install extension without problem.
I tried using Administrator rights too but nothing work. I'll install by hand, but I would have prefer the update checking system to work.

**Comment by joaomoreno** [comment]
This has since been fixed with the proxy setting. Both 0.10.6 and 0.10.8 are way too old, and obviously don't have this fix. Simply download the latest from the web site.
