### ISSUE TITLE
Debugger connects to wrong port when specifying an IP to bind to

### ISSUE THREAD

**Issue by EgoAleSum** [Microsoft/vscode#53409]
- VSCode Version: 1.24.1
- OS Version: macOS 10.13.5

Steps to Reproduce:

1. Configure `package.json` so there's an explicit IP to bind to in the `--inspect` parameter. For example: `"debug": "./node_modules/.bin/nodemon --inspect=127.0.0.1:9230 index.js`
2. Start the debugger, trying to attach to the running process.
3. The debugger thinks the port is `127`, from the first octet of the IP address, rather than `9230`.

**Comment by weinand** [comment]
@EgoAleSum how do you start the debugger?

**Comment by EgoAleSum** [comment]
@weinand this is the launch.json:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "attach",
            "name": "Node: Nodemon",
            "processId": "${command:PickProcess}",
            "restart": true,
            "protocol": "inspector",
        }
    ]
}
```

**Comment by weinand** [comment]
Thanks!
yes, the failure of parsing `127.0.0.1:9230` is a bug.

BTW, if you know the port already from the package.json, why do you go through the trouble of picking a process first?

This configuration directly connects the debugger to the port:
```
        {
            "type": "node",
            "request": "attach",
            "name": "Node: Nodemon",
			"port": 9230,
            "restart": true
        }
```

Or you could even tell VS Code to launch your program via nodemon:
```
		{
			"type": "node",
			"request": "launch",
			"name": "nodemon",
			"runtimeExecutable": "${workspaceRoot}/node_modules/.bin/nodemon",
			"program": "${workspaceRoot}/index.js",
			"restart": true,
			"console": "integratedTerminal"
		},
```

**Comment by weinand** [comment]
duplicate of #52238

**Comment by EgoAleSum** [comment]
Thanks for the update.

To answer your points above, not because relevant for this bug, but because it might give you some input on how I'm using the product and the challenges I have:

1. I have a monorepo which has multiple packages. I don't explicitly set the port so when I start the debugger I can choose which instance of node (+ nodemon) to attach to, and debug multiple packages.
2. I had explored the "launch" request, but that won't work for me because I need to pipe all output through the "pino" CLI to format the logs that are coming out (which are JSON-formatted). The actual command that I run for `npm run debug` is `"debug": "./node_modules/.bin/nodemon --inspect=127.0.0.1:9230 index.js | ./node_modules/.bin/pino -l"`
