### ISSUE TITLE
Cannot Start Debugging

### ISSUE THREAD

**Issue by Ritzpak** [Microsoft/vscode#53411]
What version of Delve are you using (dlv version)?
    5cd86b1
    What version of Go are you using? (go version)?
    go1.10.3.windows-amd64
    What operating system and processor architecture are you using?
    Windows Server 2016 Datacenter x64
    Visual Studio Code v1.24.1 x64
    What did you do?
    Followed the install instructions.
    What did you expect to see?
    Hitting a breakpoint.
    What did you see instead?
    Error message: Can not debug non-main package.

I can Start Without Debugging and get my Println message so I know it compiles, but when I try Start Debugging, I get an error. I'm just getting started in Go and have only installed what is recommended so far. Not sure if there are conflicts or what. This should be extremely simple, but for some reason it won't run.

![image](https://user-images.githubusercontent.com/1278990/42141258-0e3289da-7d76-11e8-8c38-b84696073659.png)

![image](https://user-images.githubusercontent.com/1278990/42141268-1d1ee4c0-7d76-11e8-9d2d-f1a8c5b06e44.png)

I posted this in the delve issues and I was able to run through the terminal, so was told it was a vscode issue.  Hopefully there is something to fix this or they will make be switch to Eclipse.

**Comment by weinand** [comment]
Please file against go extension.
