### ISSUE TITLE
Git: commit box grabs focus after reload

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#53419]
Steps to Reproduce:

1. open SCM viewlet
2. focus into the editor
3. reload window

=> focus ends up in the git commit box

Any other view does not steal focus from the editor, so it must be something in the SCM viewlet that passes DOM focus to the commit field.

**Comment by itamark** [comment]
@joaomoreno okay if I take this one as well?

**Comment by joaomoreno** [comment]
@itamark Be my guest!

**Comment by itamark** [comment]
@bpasero Interesting. I was able to reproduce in my regular Insiders build but not in my vscode dev build. Have you seen cases where this doesn't happen?

**Comment by joaomoreno** [comment]
Maybe you have multiple repositories in your insiders, but not in dev?

**Comment by itamark** [comment]
Ah I was just about to commit and see it's already dealt with. I'll grab something else.
