### ISSUE TITLE
find - regular expression

### ISSUE THREAD

**Issue by amgalan81mn** [Microsoft/vscode#53415]
Issue Type: <b>Bug</b>

\d{6}-\W this criteria not working on this text editor, in other text editor works

text
  180702-
  180703-180704

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.87GB (9.56GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
mssql|ms-|1.4.0

</details>

**Comment by roblourens** [comment]
I guess the difference is whether `\W` matches `\n`, which it seems like it should because they match in the JS regex engine, and replacing it with a `\n` matches

**Comment by rebornix** [comment]
we should have a wiki page for both find widget and search widget about the special cases of regex handling.
