### ISSUE TITLE
No syntax highlighting for in-product release notes code blocks. 

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#53413]
- VSCode Version: 1.25 Insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Help > Release Notes
2. Look for json or TypeScript code blocks

![image](https://user-images.githubusercontent.com/12818376/42144120-3fb92a2a-7d6e-11e8-93e9-e91ee6e11fc6.png)

Code blocks are simply white on black (default dark theme) with no syntax highlighting.

Seems to only happen on the first time. If you close the release notes and try again, the code blocks are correctly highlighted.

**Comment by gregvanl** [comment]
DevTools console output:
 INFO no standard startup: not just one text editor
/C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1375  INFO No grammar found for scope source.applescript
/C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1375  INFO No grammar found for scope text.html.textile
/C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1375  INFO No grammar found for scope source.c++
/C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1375  INFO No grammar found for scope source.js.jquery
/C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1375  INFO No grammar found for scope source.smarty
/C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1375  INFO No grammar found for scope source.dosbatch
/C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1375  INFO No grammar found for scope source.scala
/C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1375  INFO No grammar found for scope source.dart
/C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1375  INFO No grammar found for scope text.html.javadoc
/C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1375  INFO No grammar found for scope source.postscript
/C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1375  INFO No grammar found for scope source.sass
/C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1375  INFO No grammar found for scope source.less
/C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1375  INFO No grammar found for scope source.stylus
2/C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3543 [Embedded Page] Blocked script execution in 'data:text/html;charset=utf-8,%3C%21DOCTYPE%20html%3E%0D%0A%3Chtml%20lang%3D…100%25%3B%20height%3A%20100%25%22%3E%0D%0A%3C%2Fbody%3E%0D%0A%3C%2Fhtml%3E' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.

**Comment by gregvanl** [comment]
No such console output on second try when there is syntax highlighting.

**Comment by gregvanl** [comment]
I wonder if this could be due to change to delay load TextMate grammars https://github.com/Microsoft/vscode/commit/54ff9a1974b784df1d84b5b6f12664c145707b94#diff-7d43e3fab25f026e232da23df0f2139c @aeschli

**Comment by aeschli** [comment]
The output `No grammar found for scope source.applescript` is caused by changes by my change and is just for info. We should track this in a separate issue. I created #53860

**Comment by mjbvz** [comment]
@aeschli Do you think we will have a chance to look into this early next week?

**Comment by gregvanl** [comment]
This seems to be fixed in 1.26.0
