### ISSUE TITLE
Does not warn when creating more specific key binding than existing key binding

### ISSUE THREAD

**Issue by alexreg** [Microsoft/vscode#53412]
- VSCode Version: 1.24.1
- OS Version: macOS 10.13.5

Steps to Reproduce:

1. Create key binding like `Cmd + S, Cmd + X`.
2. Observe that existing key binding for save (`Cmd + S`) does not work.
3. No warning/conflict is displayed in *Keyboard Shortcuts* editor, when it should be.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
@alexreg We show the similar keybindings while you are assigning the keybinding

![image](https://user-images.githubusercontent.com/10746682/42157664-9b226784-7dee-11e8-80c5-bbf159ac4c23.png)

If you have assigned it by ignoring the link in above screenshot, you can also find similar keybindings using the following action

![image](https://user-images.githubusercontent.com/10746682/42157750-e49e9608-7dee-11e8-9b1c-17d38b7d2479.png)

**Comment by alexreg** [comment]
@sandy081 Right, although when I enter the following chord, that disappears, which I think is not good. Also, the message "1 existing command" can apply to the same command, if you set the key binding to the same thing, which is rather confusing.
