### ISSUE TITLE
vscode-tscancellation-* files flood /tmp directory

### ISSUE THREAD

**Issue by SkeLLLa** [Microsoft/vscode#53423]
- Version 1.24.1
- Commit 24f62626b222e9a8313213fb64b10d741a326288
- Date 2018-06-13T17:47:35.732Z
- Shell 1.7.12
- Renderer 58.0.3029.110
- Node 7.9.0
- Architecture x64
- OS Version: Linux x64

There are lot's of similar issues, but they are all closed without any working solution.

Steps to Reproduce:

1. Start VSCode
2. Do some coding
3. After some time  `vscode-tscancellation-*` files will appear in `/tmp`
4. When there will be lots of such files VSCode become laggy and CPU usage will increase up to 100% when typing. 

Does this issue occur when all extensions are disabled?: Yes

```
srwxr-xr-x  1 user user        0 Jul  2 01:17  vscode-155df17b74231c662cb870f57e04b2f36586dc7b.sock
srwxr-xr-x  1 user user        0 Jul  2 01:17  vscode-162f6495a1f18c896aa8bc1e93cc00b9a60fae50.sock
srwxr-xr-x  1 user user        0 Jul  2 09:10  vscode-370ba774ebe76d2ac41fc0d8536da9bc87737119.sock
srwxr-xr-x  1 user user        0 Jul  2 09:10  vscode-47a5a3513b354fb7526fa851d874c8671a731626.sock
srwxr-xr-x  1 user user        0 Jul  2 01:17  vscode-6f1869560d13c35229e077539e4833005ab5af6b.sock
srwxr-xr-x  1 user user        0 Jul  2 01:17  vscode-826486d16ec6669d81de916078b1c7d8b865de86.sock
srwxr-xr-x  1 user user        0 Jul  2 01:37  vscode-b481610d6339db46e7933a68e41bbe577ee569da.sock
srwxr-xr-x  1 user user        0 Jul  2 01:37  vscode-f8b28ece9bc1228293ddff1f0b834c9764bd66dc.sock
srwxr-xr-x  1 user user        0 Jul  2 09:10  vscode-lang-9ddae7a14c671632056644b696c32802ba7a21e6.sock
srwxr-xr-x  1 user user        0 Jul  2 09:10  vscode-lang-dfc4ead4dabe352086ca31d00951c9707d4dae80.sock
-rw-r--r--  1 user user        0 Jul  2 01:25  vscode-tscancellation-31a76b28ad990f5475e5.sock145
-rw-r--r--  1 user user        0 Jul  2 01:25  vscode-tscancellation-31a76b28ad990f5475e5.sock164
-rw-r--r--  1 user user        0 Jul  2 01:25  vscode-tscancellation-31a76b28ad990f5475e5.sock203
-rw-r--r--  1 user user        0 Jul  2 01:25  vscode-tscancellation-31a76b28ad990f5475e5.sock238
-rw-r--r--  1 user user        0 Jul  2 01:25  vscode-tscancellation-31a76b28ad990f5475e5.sock273
-rw-r--r--  1 user user        0 Jul  2 01:26  vscode-tscancellation-31a76b28ad990f5475e5.sock328
-rw-r--r--  1 user user        0 Jul  2 01:28  vscode-tscancellation-31a76b28ad990f5475e5.sock385
-rw-r--r--  1 user user        0 Jul  2 01:28  vscode-tscancellation-31a76b28ad990f5475e5.sock413
-rw-r--r--  1 user user        0 Jul  2 01:28  vscode-tscancellation-31a76b28ad990f5475e5.sock423
-rw-r--r--  1 user user        0 Jul  2 01:28  vscode-tscancellation-31a76b28ad990f5475e5.sock469
-rw-r--r--  1 user user        0 Jul  2 01:28  vscode-tscancellation-31a76b28ad990f5475e5.sock481
-rw-r--r--  1 user user        0 Jul  2 01:28  vscode-tscancellation-31a76b28ad990f5475e5.sock496
-rw-r--r--  1 user user        0 Jul  2 01:28  vscode-tscancellation-31a76b28ad990f5475e5.sock519
-rw-r--r--  1 user user        0 Jul  2 01:28  vscode-tscancellation-31a76b28ad990f5475e5.sock525
-rw-r--r--  1 user user        0 Jul  2 01:28  vscode-tscancellation-31a76b28ad990f5475e5.sock529
-rw-r--r--  1 user user        0 Jul  2 01:28  vscode-tscancellation-31a76b28ad990f5475e5.sock536
-rw-r--r--  1 user user        0 Jul  2 01:29  vscode-tscancellation-31a76b28ad990f5475e5.sock562
-rw-r--r--  1 user user        0 Jul  2 01:29  vscode-tscancellation-31a76b28ad990f5475e5.sock567
-rw-r--r--  1 user user        0 Jul  2 01:29  vscode-tscancellation-31a76b28ad990f5475e5.sock581
-rw-r--r--  1 user user        0 Jul  2 01:24  vscode-tscancellation-31a76b28ad990f5475e5.sock62
-rw-r--r--  1 user user        0 Jul  2 01:29  vscode-tscancellation-31a76b28ad990f5475e5.sock639
-rw-r--r--  1 user user        0 Jul  2 01:24  vscode-tscancellation-31a76b28ad990f5475e5.sock76
```

Tsserver verbose log attached as well, but seems it has noting special there.
[tsserver.log](https://github.com/Microsoft/vscode/files/2153993/tsserver.log)

**Comment by mjbvz** [comment]
This is by design. These files are used internally and are not responsible for the cpu usage you are seeing

Do you see the high cpu usage in the [latest VS Code build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by SkeLLLa** [comment]
@mjbvz I'll try 1.25.

Regarding those files - could they be safely deleted? Or, probably, vscode should delete them after it's being closed?

**Comment by SkeLLLa** [comment]
@mjbvz In my case it may take a lot of time, because `tmp` is cleared on reboot/shutdown. However usually I just hibernate my laptop. So sometimes amount of those files reaches more than 1000.
And just an IMHO it's a good practice to make clean-up before shutdown or after file is no longer needed.

**Comment by mjbvz** [comment]
@SkeLLLa 1000 empty files is not going to cause problems. Are you still seeing cpu usage issues on 1.25?

**Comment by SkeLLLa** [comment]
1000 empty files don't create problem for filysystem. However they could and they will create problems for users. E.g. it will be harder to find something in /tmp folder besides vscode tmp files.
So anyway it will be better if vscode will delete it's files on shutdown or whenever they became no longer needed. Or at least putting all those stuff to some subdirectory `/tmp/.vscode-stuff-<randomid>` will look better and probably it will be easier to clean up afterwards by deleting that directory.

In 1.25 version it seems more stable. At least the amount of such files reduced. To make sure I'll need some time to investigate the behaviour of vscode with more "uptime" and on larger projects.

**Comment by SkeLLLa** [comment]
The problem is still present in latest 1.25 version.

**Comment by mjbvz** [comment]
The CPU usage problem? Please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to track down which process/extension is causing this. If it is typescript, try collecting the TSserver log again so we can investigate why it is causing the high cpu usage

Also, try testing on [VS Code insiders](https://code.visualstudio.com/insiders/) which includes  new typescript version

**Comment by kaiwa** [comment]
Yeah, please put that stuff in a subdirectory at least. My nautilus just crashed while trying to access my /tmp folder...

**Comment by SkeLLLa** [comment]
@mjbvz Let's stay stick to main topic of the issue - the number of files that vscode generate and doesn't clean after. As for performance and cpu usage - when I get clear reproduction steps, I'll create a new issue.

**Comment by mjbvz** [comment]
I've moved the files into directories. Again, the number of files being created is not a real issue and these will get cleaned up automatically by the system. I've been running for ~15 days with probably a hundred VS Code instances and have 200 cancellation files total

**Comment by SkeLLLa** [comment]
@mjbvz I've get around 300-400 in 1-2 days. So probably it depends on project size.

**Comment by nbsdx** [comment]
@mjbvz These files still need to be cleaned up - just dumping them into another folder isn't a real solution. There has to be a better method to signal to the typescript server that a request was cancelled (as per your comment in #54671). On top of this, these files are created even when not using typescript. Either the server itself needs to clean them up once it acknowledges the cancellation, or vscode should verify that there even is a server running to process requests.

Not to mention that despite your claims that "the OS will just clean them up", it can still cause significant burden on filesystems that aren't well optimized for small files (such as XFS).

**Comment by SkeLLLa** [comment]
I totally agree with @nbsdx. So that bug is just partially fixed. Usually it's a good practice to make clean-up. IMHO there's only one excuse for app leaving such files for system cleanup - some fatal crash. In other cases it should clean up all the stuff either when it becomes not needed or after shutdown.

**Comment by spazmodius** [comment]
Please clarify the assertion that "these will get cleaned up automatically by the system".  When is that supposed to happen?  Is there a configuration in Windows that I've never in all my life known about?
