### ISSUE TITLE
can't show _

### ISSUE THREAD

**Issue by JeanPwal** [Microsoft/vscode#53420]
Issue Type: <b>Bug</b>

Ubuntu vscode terminal can't show the _ when filename include _

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:47:35.732Z)
OS version: Linux x64 4.4.0-128-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1225 v6 @ 3.30GHz (3 x 3312)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|1.94GB (0.07GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
php-debug|fel|1.12.3
php-intellisense|fel|2.3.3
php-pack|fel|1.0.1
vscode-clang|mit|0.2.2
vscode-language-pack-zh-hans|MS-|1.24.3
cpptools|ms-|0.17.5
Go|ms-|0.6.84
vscode-code-outline|pat|0.2.1
clang-format|xav|1.6.2
vscode-proto3|zxh|0.2.1

</details>

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35901
