### ISSUE TITLE
Updated extension fails to show Reload button

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#53426]
1. Start Code with an outdated extension, auto update enabled
2. Show the Extensions viewlet

The extension will appear to be updating... but then it returns back to this:

![image](https://user-images.githubusercontent.com/22350/42149850-20df1adc-7dd8-11e8-984a-9a24339a5631.png)

**Comment by joaomoreno** [comment]
@sandy081 I still don't see a `Reload` action. Also, when I run `Show Outdated Extensions` and then back to `Show Installed Extensions`, the extension appears disabled:

![image](https://user-images.githubusercontent.com/22350/42222929-cdede7f4-7ed6-11e8-93a4-24342cf4c278.png)

**Comment by sandy081** [comment]
@joaomoreno Good catch.
