### ISSUE TITLE
git more click

### ISSUE THREAD

**Issue by kongchenglc** [Microsoft/vscode#53436]
Issue Type: <b>Bug</b>

the more button click look like double click

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.63GB (1.71GB free)|
|Process Argv|D:\software\vscode\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-babel-coloring|dza|0.0.4
nornj|joe|0.3.1
vscode-language-pack-zh-hans|MS-|1.24.3
open-in-browser|tec|1.1.0

</details>

**Comment by jrieken** [comment]
Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by kongchenglc** [comment]
my English is so poor , so i use gif to speak.
![vscode](https://user-images.githubusercontent.com/20537203/42220222-eda20844-7f00-11e8-9882-dec66065c90d.gif)

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/46833
