### ISSUE TITLE
How to quick open file always in new tap?

### ISSUE THREAD

**Issue by ldhios** [Microsoft/vscode#53433]
I use  "command+p" seach file then press "enter" to open the result file. It will replace current tab file.
How to setting keep it always new tap?

**Comment by ldhios** [comment]
![image](https://user-images.githubusercontent.com/9722423/42154281-e44d5774-7e17-11e8-9a53-5aba0f0b1d6b.png)
When hold down command and click mouse, it will jump to function implementation. bu it will display two result preview. like above picture. How to disable the feature. I don't like it.

**Comment by bpasero** [comment]
Follow our docs to resolve this: https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode

**Comment by ldhios** [comment]
Hi, @bpasero 
   Thanks for your reply.
I set    "workbench.editor.enablePreview":false,
    "workbench.editor.enablePreviewFromQuickOpen":false,  The first issues is solve. 
But the second issues not solve.  not found relevant setting , when my search the 'User Settings' with use 'preview' keywords. Can you help me? I am troubled by this issues recently.
