### ISSUE TITLE
Highlight the breakpoint when stopping on a breakpoint with custom debugger 

### ISSUE THREAD

**Issue by bvicinay** [Microsoft/vscode#53437]
How can this be done, the debugging api does not seem to allow this. This is a very important feature of creating a debugger. 

For example, when a StoppedEvent is emitted a line and file could be passed in to be highlighted by the UI. 

An issue like this was closed in the past: [36094](https://github.com/Microsoft/vscode/issues/36094)

**Comment by weinand** [comment]
@bvicinay with "Highlight the breakpoint" you mean select "the breakpoint in the BREAKPOINTS view"?

**Comment by bvicinay** [comment]
Yes, a breakpoint that was set by a user. When the debugger stops at the breakpoint.

**Comment by weinand** [comment]
Why is it important to select the breakpoint? 
Isn't it sufficient to highlight the breakpoint in source?

**Comment by bvicinay** [comment]
I need to highlight the breakpoint in the source, in the editor. When the breakpoint is reached, the editor window of the file with the breakpoint should show and hightlight the line with the breakpoint that was reached. Nothing to do with the breakpoints view. This seems to not happen automatically when a StoppedEvent is sent. Sorry for the misunderstanding.

**Comment by weinand** [comment]
VS Code automatically reveals and highlights the source under these two conditions:
- the target is running and
- a stopped event is received.

It does **not** highlight the source if the target is **not** running.

So when you are emitting (artificial) stopped events, make sure that the VS Code is the running state by emitting a "continue" event first. See https://github.com/Microsoft/vscode-debugadapter-node/blob/7b97e42f1ed19777044850c5f18bfce8e21fc598/protocol/src/debugProtocol.ts#L107-L120

**Comment by bvicinay** [comment]
After emitting a ContinuedEvent, vscode does not highlight the source when a StoppedEvent is emitted. Are there other conditions necessary? Like breakPointId's, _currentLine, etc.. How does vscode know where to highlight the source?
