### ISSUE TITLE
Updating import paths causes third party modules to use the types folder

### ISSUE THREAD

**Issue by RonanQuigley** [Microsoft/vscode#53439]
- VSCode Version: 1.25.0-insiders Commit: 6ca99aca80e80224f1c0bd4370c6ec4941c3bc54
- OS Version: Windows 10 

Steps to Reproduce:

If this is better in the typescript repo feel free to move it over there.

![ts-bug-one](https://user-images.githubusercontent.com/33596237/42159859-281784be-7ded-11e8-96e2-977350433227.gif)

[Note that this happens with any third party module, not just React.]

Currently in insiders if I update an import path it also updates third party modules by referencing their types instead of using the node modules folder. I've tried including the node_modules folder via a jsconfig but that doesn't work. It also happens if I change the update import paths option from prompt to always. Here's the ts log if it helps:

[tsserver-log-b9pXtq.zip](https://github.com/Microsoft/vscode/files/2154881/tsserver-log-b9pXtq.zip)

I'm guessing this is a bug by the looks of it, but is there a way to tell vscode to selectively ignore paths to update for third party modules like React? 

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Please try upgrading your workspace to use `typescript@next` by following [these instructions](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions). Do you still see this issue on typescript@next?

**Comment by RonanQuigley** [comment]
Yup that fixes it, but it creates a new problem. It leaves files in the workspace that say deleted from disk after the move has taken place.

![gif](https://user-images.githubusercontent.com/33596237/42178100-fe48cd34-7e26-11e8-885a-a81df82343ef.gif)

Might be worth adding: none of these issues happen with 1.24 and typescript 2.9.1 that it ships with.

**Comment by screaney** [comment]
Just to throw in my 2 cents, this also happens with my project.  Usually when it happens, I end up with about 400 3rd party .ts files open.

**Comment by RonanQuigley** [comment]
So the second problem I mentioned in my last post now goes away with ts 3.0.0-dev.20180706, however the path completion is really slow and prone to breaking at present. If anyone else is having this issue, until this is fixed (has it been confirmed yet?), for the new vscode 1.25 release, I'd suggest downgrading ts from 2.9.2 to 2.9.1. Much more stable. 

Currently the new renaming folders feature for updating paths doesn't work either. I can make a sep issue for that if I get a chance.

**Comment by mjbvz** [comment]
Let me know if you see this issue on the next VS Code insiders build when using typescript 3.0
