### ISSUE TITLE
Add to Path & Context Menu Integration no longer work in current insiders

### ISSUE THREAD

**Issue by MeikTranel** [Microsoft/vscode#53438]
Issue Type: <b>Bug</b>

When installing insiders fresh, while enabling Add To Path and context menu integration, none of those features work.
Doing the same on the current regular release of code works perfectly fine.

I tried using different kinds of accounts (admin, local admin, domain admin) but none of them worked. The entries are just not registered to registry.

VS Code version: Code - Insiders 1.25.0-insider (07d89abf1522a67f0e8105770505077f454ab021, 2018-06-28T05:19:16.448Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3504)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (9.78GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.18.0
docs-article-templates|doc|0.1.2
docs-authoring-pack|doc|0.1.1
docs-markdown|doc|0.1.1
docs-preview|doc|0.3.12
gitlens|eam|8.4.1
beautify|Hoo|1.3.2
csharp|ms-|1.15.2
vscode-docker|Pet|0.0.27
vscode-yaml|red|0.0.13
vscode-icons|rob|7.24.0
code-spell-checker|str|1.6.10
msbuild-project-tools|tin|0.2.39

</details>

**Comment by MeikTranel** [comment]
the recommended duplicate does not cover my issue. also hi @Tyriar 😄 
You might wanna flag this "update-install" ;)

**Comment by MeikTranel** [comment]
```Powershell
$env:Path
--> "C:\Program Files (x86)\Embarcadero\Studio\17.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\17.0\Bpl;
C:\Program Files (x86)\Embarcadero\Studio\17.0\bin64;
C:\Users\Public\Documents\Embarcadero\Studio\17.0\Bpl\Win64;
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;
C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;
C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;
C:\Windows\System32\WindowsPowerShell\v1.0\;
C:\Windows\System32\OpenSSH\;
C:\Program Files\Intel\WiFi\bin\;
C:\Program Files\Common Files\Intel\WirelessCommon\;
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;
C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;
C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;
C:\ProgramData\chocolatey\bin;
C:\Program Files\Git\cmd;
C:\Program Files\Git LFS;
C:\Program Files\dotnet\;
C:\Program Files (x86)\GitExtensions\;
C:\Program Files\Java\jdk1.8.0_172\bin;
C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;
C:\Program Files\OpenSSH-Win64;
C:\Users\mtr\scoop\shims;
C:\Users\mtr\AppData\Local\Microsoft\WindowsApps;C:\Users\mtr\Desktop\Software\CMDTools;C:\tools\cmdermini;;C:\Program Files\Microsoft VS Code\bin
```

**Comment by joaomoreno** [comment]
Just confirmed the issue, great catch, thanks for filling!

**Comment by MeikTranel** [comment]
Just to confirm that this is one of my installers weirding out 😄 
the bug is that current VSCode-Insiders write an empty string into path right? (thus the double semicolon) ?

**Comment by joaomoreno** [comment]
No, I believe the double semicolon comes from something else in your system. We were writing on a completely wrong registry key.

**Comment by MeikTranel** [comment]
Well.. damn. need to check that then 😄 

I just reinstall to get this, right?

**Comment by joaomoreno** [comment]
The latest insider should already have the fix: https://az764295.vo.msecnd.net/insider/fb0b8f12036bfb69a47a1b3354126794a093e749/VSCodeSetup-x64-1.25.0-insider.exe

**Comment by MeikTranel** [comment]
Used your installer, still didnt work? Where is the Entry for Open With Code Insiders supposed to be in registry`?

**Comment by MeikTranel** [comment]
@joaomoreno i just checked the commit hash. Your commit is the head of the installer you linked. The fix still didnt work for me.

**Comment by joaomoreno** [comment]
@MeikTranel I think you are right. The PATH is fixed, but not the context menu stuff.

**Comment by joaomoreno** [comment]
I'll send you a new build to try out

**Comment by MeikTranel** [comment]
Yeah i just checked the path is cool (thank god for ``code-insiders .``)

**Comment by MeikTranel** [comment]
Does the Insider-Preview Download link on the VS/MS page always link the latest build after CI is done with it?

**Comment by joaomoreno** [comment]
@MeikTranel Yes, except in stabilisation week (right now).

**Comment by MeikTranel** [comment]
Well, nice :smile:

**Comment by joaomoreno** [comment]
Yes, exactly.

Wanna give the build a try? https://az764295.vo.msecnd.net/insider/0f080e5267e829de46638128001aeb7ca2d6d50e/VSCodeSetup-x64-1.25.0-insider.exe

**Comment by MeikTranel** [comment]
![image](https://user-images.githubusercontent.com/6466560/42285968-7c0dced2-7fb1-11e8-9d38-ddd84515cfca.png)
Well this is better 🥂
