### ISSUE TITLE
Avoid aync and winjs-promise

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#53442]
A [while back](https://github.com/Microsoft/vscode/pull/47144) we have made an effort to compile the vscode-sources down to es6 but had to stop that because TypeScript doesn't allow async-functions that don't return native promises, see https://github.com/Microsoft/vscode/pull/47144#issuecomment-380910256. Back then we didn't trust native promises because thy don't interact nicely with winjs-promises and therefore we didn't continue the es6 path. 

Good news is that the native/winjs-promise is now understood and fixed, indeed it was an winjs-promise issue, and we can now continue the es6 path. To continue we should now adopt async-functions that return winjs-promises. Searching for `async .+TPromise<.+>` (as regex) yield ~110 results and often the adoption is as easy as changing the return type.

**Comment by jrieken** [comment]
Assigning people based on rough code-ownership...

**Comment by isidorn** [comment]
Assigning to @weinand for this reference https://github.com/Microsoft/vscode/blob/91e82ed2fef68f9f0a8aea9276fdad35ff649e66/src/vs/workbench/api/node/extHostDebugService.ts#L126

@sandy081 let me know if you want me to convert the panel viewlet `create` method which spreads everywhere

**Comment by sandy081** [comment]
@isidorn I will take care of all viewlets. Just for FYI, I moved away from `async-await` in all viewlets `create` method. If we have to retain that, we have to change the base `create` method which will have a big ripple affect.

**Comment by sandy081** [comment]
Looks like @joaomoreno did the changes for viewlets.

**Comment by joaomoreno** [comment]
Down to 13.

**Comment by jrieken** [comment]
done

**Comment by jrieken** [comment]
👏 Thanks everyone!

**Comment by joaomoreno** [comment]
Nice!
