### ISSUE TITLE
Allow to use macOS services via keybindings

### ISSUE THREAD

**Issue by janosh** [microsoft/vscode#53440]
I have the exact same problem as unnamedcrewman reported [here](https://github.com/Microsoft/vscode/issues/1628#issue-123759576). I'm trying to use a keyboard shortcut that calls a system service which in turn invokes a productivity tool called PopClip on mac OS. As unnamedcrewman mentioned, the shortcut and service work in every application I tried except for VS Code. Unfortunately, the linked issue was closed even though the problem persists.

Could someone perhaps look into this again?

![show popclip system service](https://user-images.githubusercontent.com/30958850/42160520-d8ab73a8-7df7-11e8-91f4-a1bb329e4671.png)
![popclip in vs code](https://user-images.githubusercontent.com/30958850/42160521-d8cceb96-7df7-11e8-974e-a490de232b7b.png)

**Comment by bpasero** [comment]
If someone has ideas how to make this happen, feel free to chime in.

**Comment by bpasero** [comment]
This actually seems to work fine when I select text in a native input field in VSCode, but not when selecting text in the editor, so I suspect this is due to the way how we have a virtual selection with a hidden text area

//cc @rebornix
