### ISSUE TITLE
"Are you missing a using or assembly reference"  error occured while code changed

### ISSUE THREAD

**Issue by venkatsgitaccount** [Microsoft/vscode#53441]
Issue Type: <b>Bug</b>

After changing any code or editing the reference error occured.But build get successful.The errors are cleared after restarting the application.

Also Go to definition is not working.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (10.17GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe D:\JMS\AngularCLI|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
angular2-snippets|dan|1.0.19
vscode-npm-script|eg2|0.3.4
dotnet|for|0.0.4
csharp|ms-|1.15.2
Go|ms-|0.6.84
debugger-for-chrome|msj|4.7.0

</details>

**Comment by jrieken** [comment]
Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
