### ISSUE TITLE
Korean translation of Markdown is wrong.

### ISSUE THREAD

**Issue by azyu** [Microsoft/vscode#5345]
- VSCode Version: 1.0

Current Korean translation of 'Markdown' is '가격 인하'. But, It means 'discount'.

Correct translation is '마크다운'.

![markdown](https://cloud.githubusercontent.com/assets/1789839/14564179/5b0ac818-0360-11e6-87ac-75233a26a00c.jpeg)

**Comment by Tyriar** [comment]
Related https://github.com/Microsoft/vscode/issues/4679

**Comment by johnliu2016** [comment]
Location of the menu string: [markdown.contribution.nls.resx.lcl](https://monacotools.visualstudio.com/DefaultCollection/Monaco/_git/MonacoLocalization#path=%2FLocalize%2Fkor%2Fvscode%2Fsrc%2Fvs%2Flanguages%2Fmarkdown%2Fcommon%2Fmarkdown.contribution.nls.resx.lcl&version=GBmaster&_a=contents)

      <Item ItemId=";markdownConfigurationTitle" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[Markdown preview configuration]]></Val>
          <Tgt Cat="Text" Stat="Loc" Appr="PreApproved" Orig="New" AutoAppr="N/A">
            <Val><![CDATA[가격 인하 미리 보기 구성]]></Val>
          </Tgt>
        </Str>

**Comment by johnliu2016** [comment]
@lukaschal please ask term review of "Markdown" 
Here's another case in [markdown.contribution.nls.resx.lcl](https://monacotools.visualstudio.com/DefaultCollection/Monaco/_git/MonacoLocalization#path=%2FLocalize%2Fkor%2Fvscode%2Fsrc%2Fvs%2Flanguages%2Fmarkdown%2Fcommon%2Fmarkdown.contribution.nls.resx.lcl&version=GBmaster&_a=contents)
      <Item ItemId=";styles" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[A list of URLs or local paths to CSS style sheets to use from the markdown preview.]]></Val>
          <Tgt Cat="Text" Stat="Loc" Appr="PreApproved" Orig="New" AutoAppr="N/A">
            <Val><![CDATA[가격 인하 미리 보기에서 사용할 CSS 스타일시트의 로컬 경로 또는 URL 목록입니다.]]></Val>
          </Tgt>
        </Str>

**Comment by johnliu2016** [comment]
also [markdownActions.contribution.nls.resx.lcl](https://monacotools.visualstudio.com/DefaultCollection/Monaco/_git/MonacoLocalization#path=%2FLocalize%2Fkor%2Fvscode%2Fsrc%2Fvs%2Fworkbench%2Fparts%2Fmarkdown%2Fbrowser%2FmarkdownActions.contribution.nls.resx.lcl&version=GBmaster&_a=contents)
      <Item ItemId=";markdown" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[Markdown]]></Val>
          <Tgt Cat="Text" Stat="Loc" Appr="PreApproved" Orig="New">
            <Val><![CDATA[가격 인하]]></Val>
          </Tgt>
        </Str>

**Comment by lukaschal** [comment]
Waiting for linguistic input.

**Comment by lukaschal** [comment]
Strings fixed.

Linguistic answer:

Instead of the original or suggested translation is used "markdown" to keep consistency with TS: there is one occurrence of the term “markdown” in TermStudio for ko-KR (markdown file, src ID 2355577) and “markdown” is kept in English.
