### ISSUE TITLE
Support built in Windows 10 ssh-agent

### ISSUE THREAD

**Issue by tomeaton17** [Microsoft/vscode#53450]
- VSCode Version: 1.24.1
- OS Version: Windows 10 Build 17134

Steps to Reproduce:

1. Add ssh key to `ssh-agent` with `ssh-add`
2. Try to push/pull from repository

Does this issue occur when all extensions are disabled?: Yes

I can work around this issue with the following steps:

- Open powershell
- `start-ssh-agent`
- `code`

This becomes irritating and time consuming as it has to be done every time when opening VS Code. Please fix this issue.

**Comment by tomeaton17** [comment]
When you try to push/pull from the repository it errors `Permission denied (public key)`. 

I can't find the `ssh-agent` version, but it is part of the OpenSSH tools included in Windows. Found at `C:\Windows\System32\OpenSSH\`.

**Comment by joaomoreno** [comment]
Is this an insider version of Windows?

**Comment by tomeaton17** [comment]
No I am using Windows 10 Pro Build 17134. There seems to be some inconsistencies on my system on which OpenSSH version I am using, for example `where ssh-add` points to `C:\Windows\System32\OpenSSH\ssh-add.exe` but `where start-ssh-agent` points to a git repository. This a problem on my end. Sorry for the confusion.
