### ISSUE TITLE
Terminal cannot escape from `yes` command using Ctrl+C.

### ISSUE THREAD

**Issue by kbumsik** [Microsoft/vscode#53452]
- VSCode Version: 1.24.1
- OS Version: Manjaro Linux

Terminal cannot escape from `yes` command using Ctrl+C. It is also applies to the others like Ctrl+Z.

In other terminals, `yes` command immediately exists when pressing Ctrl+C.  

Steps to Reproduce:

1. Run `yes` command in the Integrated Terminal.
2. Try Ctrl+C
3. Terminal ignores Ctrl+C and keeps printing. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/42234
