### ISSUE TITLE
Allow refactoring tools in the outline view

### ISSUE THREAD

**Issue by yanckst** [Microsoft/vscode#53451]
Hi,

I'm not sure if some people could see this future useful but, it would be very nice to allow users having refactoring tools inside the outline view. Right now, the only features we have are a filter and a sort for finding/sorting elements in the code.

What if we can add more feature in this view? I don't know if it was designed for that, but it can help a lot for refactoring the code.

Here's a GIF demonstrating the current features : 
![vscode-outline](https://user-images.githubusercontent.com/30554401/42170332-3cc38bdc-7de4-11e8-99b1-4f504241b100.gif)

**What we can add :** 
- Contextual Menu
- Rename
- Delete
- Drag/Drop

### For the Rename refactoring : 
When the user right-click on the mouse, a contextual menu should appear and a "Rename" choice should be there. When the user, click on rename, it should rename the entity (constructor, property, method, etc) in the code and update all references. The user could also user the the keyboard shortcut like F2 for renaming, like we do in the application too.

### For the Delete refactoring : 
When the user right-click on the mouse, a contextual menu should appear and a "Delete" choice should be there. When the user, click on delete, it should delete the entity (constructor, property, method, etc) in the code and update all references. The user could also user the the keyboard shortcut like del for deleting, like we do in the application too.

### For the Drag/Drop refactoring : 
The user should be able to move the entity and it should update in the code too, not only in the outline view. The cursor should be changed by the "move" cursor. 

### Nice to have if it's possible : 
When displaying the entities (constructors, properties, methods, etc). It would be very nice to have something visual to distinguish public vs protected vs private. Right now, all entities are displayed. When you have a huge class, sometimes you want to spot the private methods region. If you have something visual in this view, it would help a lot finding what you are looking for. Like changing the icon or the font. If a entity is private, the font could be darker than the public ones. 

If it's possible, we can also add a sorting in the sorting choices. We can add something like "Sort by: Member access" below the "Sort by: Type"

If anyone has any refactoring ideas that I didn't mention, please feel free to add a comment. 😊😊

Let me know if it's possible the add this feature.

Thanks! 😇😇

**Comment by jrieken** [comment]
Please complete #49925 with things mentioned here but not there
