### ISSUE TITLE
it should be able to set "fontWeight" for suggestion widget

### ISSUE THREAD

**Issue by komagic** [Microsoft/vscode#53469]
<img width="485" alt="2018-07-03 10 21 52" src="https://user-images.githubusercontent.com/13415767/42195328-ef6a5cea-7eaa-11e8-8d98-1d3be6795526.png">

it should be able to set "fontweight"  in suggestion widget, like "editor.suggestFontSize",

create a fontWeight variable in suggest.ts
<img width="870" alt="2018-07-03 10 36 01" src="https://user-images.githubusercontent.com/13415767/42195779-406e8916-7ead-11e8-83f5-0a283a59fe77.png">

**Comment by ramya-rao-a** [comment]
@joaomoreno @jrieken Thoughts on re-using the `editor.fontWeight` in the suggest widget instead of introducing `editor.suggestFontWeight`?

**Comment by komagic** [comment]
Separately，pls.

**Comment by joaomoreno** [comment]
My intuition tells me aligning it with the `editor.fontWeight` should be done any way. Having a `suggestFontWeight` is an additional feature. :+1:

**Comment by komagic** [comment]
it looks like 
<img width="216" alt="2018-08-17 6 05 47" src="https://user-images.githubusercontent.com/13415767/44260872-63c4ff80-a248-11e8-8fab-14bacb8d68d2.png">
^ ^

**Comment by komagic** [comment]
ok, agree~

**Comment by komagic** [comment]
Up to now, I think vs code is the best tool for FE, however,  the Atom's suggestion widget looks more.....you know that~

**Comment by ramya-rao-a** [comment]
> I think vs code is the best tool for FE,

What does "FE" mean?

> however, the Atom's suggestion widget looks more.....you know that~

looks more like what? Sorry, I dont understand what you are trying to say. Perhaps, you can share some screenshots?

I have pushed a change such that the suggest widget uses the font weight set in the `editor.fontWeight` setting. You can see this in our [Insiders build](https://code.visualstudio.com/insiders] tomorrow. Please let us know if this serves your need.

**Comment by ramya-rao-a** [comment]
Closing this feature request as `editor.fontWeight` is now respected by the suggest widget
