### ISSUE TITLE
Completions: prefer slight misspelling over distant substring match

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#53468]
Issue Type: <b>Bug</b>

Type:
```ts
const supercaliFragilisticExpialidocious = 0;
const frajile = 1;
```
* Type `fragile()`.

Expected: Corrects to `frajile`.
Actual: Corrects to `supercaliFragilisticExpialidocious`.

VS Code version: Code - Insiders 1.25.0-insider (499122702e462b458117122a6885e6aeb3cec0a4, 2018-06-29T05:19:31.733Z)
OS version: Linux x64 4.13.0-43-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 1536)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.63GB (1.38GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders tests/cases/fourslash/|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by jrieken** [comment]
Unsure... We only swap neighbouring characters but we don't skip or replace characters in the search word. Even that can confuse people and I don't know if more graceful matching is wanted. Tho, we now do have a setting in which this can be captured.

**Comment by andy-ms** [comment]
`supercaliFragilisticExpialidocious` doesn't contain `fragile` as a substring though, only `fragil` -- so it must be skipping to the `E`. There's no autocorrect if I use `Oxpialidocious` instead.

**Comment by jrieken** [comment]
> supercaliFragilisticExpialidocious doesn't contain fragile as a substring though, only fragil -- so it must be skipping to the E.

I don't call that correction but matching. The logic is that every character of the search string must appear (in order) in the word and that the first match must be strong (those are matches on upper-case letters or after separators like - and _)
