### ISSUE TITLE
Deleting all files in a folder should result with the empty folder being selected

### ISSUE THREAD

**Issue by johnpapa** [Microsoft/vscode#53464]
Version 1.25.0-insider (1.25.0-insider)
macOS 10.13.4 (17E202)

Steps to Reproduce:

0. Start with a project with multiple folders, each with multiple files in them
1. Select all of the files in a folder
2. Delete the files (not the folder) so the folder is empty
3. Notice that the selected folder is no longer selected

**Comment by wistcc** [comment]
After trying to fix this I got to [this line](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/fileActions.ts#L666) which is working as expected.

Then I noticed that the only way to reproduce this is by removing a file that is opened. Even removing just one file (that is opened) the parent folder won't be selected as you can see in [this video](https://youtu.be/zPrQk6Z1rms).

So, seems that after closing the just removed file, the focus is lost from its parent folder. I think we should focus the parent folder after we close the editor [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/editors/fileEditorTracker.ts#L180). I haven't been able to find a way to focus the parent folder from `fileEditorTracker.handleDeletes`, can anyone give me some guidance?

**Comment by isidorn** [comment]
`explorer.autoReveal: false`
should customize that behavior, let me know if that does not fix the issue and I can reopen. Thanks

**Comment by wistcc** [comment]
Yes, that fixes it. Thanks!
