### ISSUE TITLE
Developing Themes on Extension Development Host. Have to change Theme everytime you switch files with 1.0.0 release

### ISSUE THREAD

**Issue by EWhite613** [Microsoft/vscode#5346]
- VSCode Version: 1.0.0
- OS Version: Mac OS X

Steps to Reproduce: 

1. Develop a theme
2. Ctrl + F5
3. Switch to dev Theme
4. Change Files
5. Have to switch to dev Theme again

Example Repo: https://github.com/EWhite613/vscode-ember-colorizer

**Comment by aeschli** [comment]
@EWhite613 Can you explain more? In step 4, do you make changes to the theme?
Why do you have to switch to the dev Theme again? To refresh it?
I recommend to keep the Extension Host window open and press `Ctrl + r` to refresh.
Does that help?

**Comment by EWhite613** [comment]
Step 4 I'm in the Extension Host window on a file like `config.js`. I switch files to `default.js` (Still in the same window), theme switches to back to my non-dev theme (Ex. `Dark+`). So now I have to open up Theme preferences again and switch back to my dev theme

**Comment by aeschli** [comment]
Hm, strange, I can't reproduce this. It's not that you just look at the new theme in the preview mode (with the theme picker window open, but don't press enter)?
How do switch between the file? Clicking in the explorer?

**Comment by EWhite613** [comment]
@aeschli I press enter on the theme. Ya just clicking in the explorer

**Comment by aeschli** [comment]
Can you, in the Extension Host window, open the dev tools (F1 > Toggle Developer Tools)?
In the dev tools, go to Console and see if there is anything interesting there?

**Comment by EWhite613** [comment]
@aeschli 
I get this:
<img width="754" alt="screen shot 2016-04-22 at 1 17 36 pm" src="https://cloud.githubusercontent.com/assets/9057680/14749288/a700343e-088c-11e6-865f-8cbac29502cd.png">

**Comment by aeschli** [comment]
Sorry, I still have no clue what could cause the theme switch.
Can you try again with the 1.0.1 release?
http://code.visualstudio.com/download?insiders=true

**Comment by EWhite613** [comment]
@aeschli Works fine with 1.0.1
