### ISSUE TITLE
[TextMate / Typescript / Theme] Detecting Type of exported Class

### ISSUE THREAD

**Issue by Ritorna** [Microsoft/vscode#53476]
When importing a Typescript class, within the project it is defined in, textmate would match the class to `variable.other.object`: 
![image](https://user-images.githubusercontent.com/10747768/42205000-83ae1426-7ea3-11e8-9da7-7b3ba636f5b6.png)
Normal class export: 
![image](https://user-images.githubusercontent.com/10747768/42204956-65252094-7ea3-11e8-91be-b11ce61937ed.png)

I'd rather have it matched as class or something like that. To be able to define a Theme to create an improved reading ability when working with classes. Somewhat like this: 
![image](https://user-images.githubusercontent.com/10747768/42205242-2b7821e2-7ea4-11e8-9c43-90a88322e183.png)

Currently when setting the `variable.other.object` Theme property it would also cause other objects to be highlighted with the specified options: 
![image](https://user-images.githubusercontent.com/10747768/42205171-fb0dc08e-7ea3-11e8-8eef-4f5e960f5286.png)
 
Is there currently any chance to give hints that the imported value is an class? If not I suppose it would make Typescript development easier.

**Comment by mjbvz** [comment]
This requires semantic highlighting #585

Closing as out of scope for textmate grammars.
