### ISSUE TITLE
Integrated terminal ctrl+' not working

### ISSUE THREAD

**Issue by Narenvaran** [Microsoft/vscode#53473]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1. ctrl + ' not working
2. i am going manually to select integrated terminal

**Comment by Tyriar** [comment]
You're on v1.7 from October 2016, you should update to the latest before reporting an issue.
