### ISSUE TITLE
Xbox Live: Achievement Get: Git commit

### ISSUE THREAD

**Issue by willhackett** [Microsoft/vscode#53471]
Why not increment my Xbox Live Gamerscore for tap, tap, tapping away in my IDE. Add achievements for committing, merging, resolving conflicts, rebasing — pit players against each-other to create unnecessary office competition. 

![image](https://user-images.githubusercontent.com/12025460/42197814-f91af034-7ec7-11e8-970c-ef9df31e28bd.png)
Image credit: Slide 35 of this -> https://www.slideshare.net/tmacwilliam/git-magic-versioning-files-like-a-boss

**Comment by jxom** [comment]
+1
