### ISSUE TITLE
Clicking into menu  / title bar area doesn't close custom menu 

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#53479]
- custom menu bar
- open a menu
- click to the right of the Help menu into the title bar

I expect the menu to close

**Comment by sbatten** [comment]
I looked into this and don't think we can make this happen as the titlebar is a draggable region and as far as I understand, that area absorbs the click event meaning we can't tell this is happening. Moving to August to see if @bpasero has any ideas.

**Comment by bpasero** [comment]
I don't, without further investigation...

**Comment by sbatten** [comment]
I'm trying a workaround that has its own drawbacks which is to remove the drag region while the menu is open. While it fixes this issue, it brings up another which is breaking drag on the first click of the title bar if the menu is open. I don't think these actions come in pairs so it probably won't be an issue, but we well see the feedback.

**Comment by dbaeumer** [comment]
I still find it pretty annoying that this doesn't close the menu. I am somehow use to close it that way since this works with all other programs. No way to make this happen ?

**Comment by sbatten** [comment]
@dbaeumer this was resolved via https://github.com/Microsoft/vscode/commit/9849693bb1f5e77c7d1b4fc37019f6420f2e9c05. Are you still seeing the issue in the latest? Please see https://github.com/Microsoft/vscode/issues/53479#issuecomment-420443295 for explanation of fix.

**Comment by dbaeumer** [comment]
It is fixed in today's insider. Thanks. I am pretty sure it wasn't yesterday.
