### ISSUE TITLE
file tracking by git

### ISSUE THREAD

**Issue by samael205** [Microsoft/vscode#53477]
Versión: 1.24.1
Confirmación: 24f62626b222e9a8313213fb64b10d741a326288
Fecha: 2018-06-13T17:51:32.889Z
Shell: 1.7.12
Representador: 58.0.3029.110
Nodo 7.9.0
Arquitectura x64

Steps to Reproduce:

1. Create a json file in .vscode folder
2. Modify it
3. The file if you have a repository git, is tracked by git.
4. Add the json file on .gitignore file
5. Modify de json file
6. The file continues being tracked by git even having add it to .gitignore file.

Why does git keep watching the file?

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Did you `git add` the file at any point?

**Comment by joaomoreno** [comment]
Yes. You must remove the file from Git, if you have added it once.
