### ISSUE TITLE
Got git stuck on "please clean your repository before pulling"

### ISSUE THREAD

**Issue by mikkotikkanen** [Microsoft/vscode#53475]
Issue Type: <b>Bug</b>

Working from the train, the internet is not always most reliable. I committed and tried to sync changes to remote repo. Immediately after pressing sync I realized that there was still changes to be committed, quickly committed the remaining files as Code was still trying to connect to remote. Eventually it managed to connect only to greet me with "please clean your repository.." error even though I had nothing to commit anymore. Refresh button in Git view didn't help either. Only way I got it back to working order was to restart Code.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.41GB (3.32GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
Handlebars|and|0.4.1
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.12
gitlens|eam|8.4.1
vscode-npm-script|eg2|0.3.4
auto-rename-tag|for|0.0.15
autofilename|Jer|0.1.3
debugger-for-chrome|msj|4.7.0
vscode-docker|Pet|0.0.27
stylelint|shi|0.37.0
bootstrap4-vscode|the|4.1.1
bootstrap-3-snippets|wcw|0.1.0

</details>

**Comment by joaomoreno** [comment]
This is strange, because Code gets that message from `git.exe`. Let me know if you can repro, I'll reopen if you do so.
