### ISSUE TITLE
cannot format cpp files

### ISSUE THREAD

**Issue by justin-romano** [Microsoft/vscode#53480]
Issue Type: <b>Bug</b>

when attempting for format with alt-shift-f i get the error 
"There is no document formattor for 'cpp'-files installed."
I have attempted to install clang-format as suggested by MS c++tools
but still get this message. Not sure if there is supposed to be a simple cpp formattor as there seems to be with javascript and typescript
```json
{
    "workbench.startupEditor": "welcomePage",
    "git.ignoreMissingGitWarning": true,
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "editor.tabSize": 2,
    "terminal.integrated.rendererType": "dom",
    "editor.fontSize": 16,
    "C_Cpp.clang_format_path": "C:\\Program Files\\LLVM\\bin\\clang-format.exe",
    "C_Cpp.formatting": "Default"
}
```

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2367M CPU @ 1.40GHz (4 x 1396)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.84GB (1.34GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.17.6
PowerShell|ms-|1.7.0
platformio-ide|pla|0.17.0
clang-format|xav|1.6.2

</details>

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-cpptools
