### ISSUE TITLE
[Accessibility]A11y_VSCode_KeyboardShortcuts_Keyboard: Refactor(Ctrl+Shift+R) shortcut command is not working.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#53486]
Environment Details:
VSCode Version : 1.24.1

Additional Details:
MAS Violated: MAS2.1.1

Repro Steps:
1)Launch VS Code.
2)Open Keyboard Shortcuts.

Actual:
Refactor(Ctrl+Shift+R) shortcut command is not working. 

Expected:
After using Ctrl+Shift+R command, refactor function should work.

Recommendations:
Refer below link which is repository of bug fixes code snippets:
https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx

MAS Reference
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={8492c4eb-c179-40ae-8777-cd044ed725a2}

Attachment for reference: 
[A11y VSCode Refactor command.pptx](https://github.com/Microsoft/vscode/files/2159036/A11y.VSCode.Refactor.command.pptx)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Where were you trying to trigger refactoring? This command only works in languages that support refactorings, such as javascript and typescript

**Comment by isidorn** [comment]
In the attached video you can see that the tester tryed to trigger refactoring in an HTML file. This funtionality is not enabled for HTML files. Thus closing as designed
