### ISSUE TITLE
Extension debugging: Debugger stops but doesn't show call stack

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#5348]
- VSCode Version: alpha from 15-04
- OS Version: Linux

Steps to Reproduce:

1. In the vscode repo open /vscode/extensions/php as folder
2. set a breakpoint on /src/features/hoverProvider.ts, line 13 (in provideHover)
3. F5 to run the extension
4. in the dev target open a PHP file and hover over a word
5. Debugger stops, but call stack stays empty

**Comment by aeschli** [comment]
This works in 1.0.0

**Comment by isidorn** [comment]
VSCode is getting an empty callstack from node debug, forwarding to @weinand  
I can also debug our nodeDebug next week to drill deeper.

**Comment by isidorn** [comment]
Asigning to me to investigate

**Comment by isidorn** [comment]
The error that the node adapter gets from node is 

```
message:"Internal error: illegal access"
request_seq:25
seq:155
success:false
type:"response"
__proto__:Object
```
It happens [here](https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/nodeDebug.ts#L1527)
Not sure if related https://github.com/node-inspector/node-inspector/issues/413
So it seems that the adapter has no access to the new node running as part of the extension host.

Will continue investigating, pasting info here maybe @weinand, @bpasero  have a suggestion

**Comment by bpasero** [comment]
I did not hear about this issue before. Unrelated: You should really find a way to return these errors back to the adapter and display them somehow, the error in https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/nodeDebug.ts#L1527 seems totally not being used?

**Comment by isidorn** [comment]
Can not reproduce this with a small node 5.10 attach sample. So somehow trying to attach to node inside extension host makes the difference here.
I do not believe this is important since this will not get surfaced to the users. Removing that tag, @aeschli let me know if you disagree.

**Comment by isidorn** [comment]
Fixed this morning by Ben and me
