### ISSUE TITLE
After update, "ng serve" service terminal not reloading/refreshing after saving the typescript file

### ISSUE THREAD

**Issue by deepak-ranolia** [Microsoft/vscode#53488]
Issue Type: <b>Bug</b>

Hi,
I was using visual studio version 1.24.1 earlier
And one day i updated it to version 1.24.1 and on the same day when i was working, the pc crashed....So i have to restart the pc
After restart, when i opened VISUAL STUDIO CODE(Version:1.24.1) : - 
1. The auto format for the code automatically enabled(or may be it was in the software update). My whole code formatted to a f****d up state, i dont like the formatting at all.
2. Whenever i try to save the file and try to change the formatting of code...it is not working at all.
3. In the formatting, end of line/function code.....";(semicolon)" added automatically , i always removes them in order to write less code...
4. Whenever i save my file, terminal window not automatically reloading/refreshing due to which browser does not refreshes...And i cant see the real time changes i have made in my code......
5. Wherever i declared some variables and imports which is no longer assigned/used in the below file....editor shows them in light gray and [hints] that i have not used them/not assigned below.....

What to do ???
How to rollback the version if it is version issue ??
Solutions ASAP ???????????????

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:47:35.732Z)
OS version: Linux x64 4.13.0-45-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3384)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|7.70GB (0.79GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.19.1
copy-relative-path|ale|0.0.2
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.58
prettier-vscode|esb|1.5.0
beautify|Hoo|1.3.2
Angular2|joh|6.1.1
debugger-for-chrome|msj|4.7.0
vetur|oct|0.12.5
vue-vscode-extensionpack|sdr|0.1.2
vue-vscode-snippets|sdr|1.3.0
vscode-status-bar-format-toggle|tom|1.4.0
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.7.0

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
> The auto format for the code automatically enabled(or may be it was in the software update). My whole code formatted to a f****d up state, i dont like the formatting at all.
> Whenever i try to save the file and try to change the formatting of code...it is not working at all.
> In the formatting, end of line/function code.....";(semicolon)" added automatically , i always removes them in order to write less code...

These are all because of extensions, try disabling some. prettier and beautify are prime candidates.

> Whenever i save my file, terminal window not automatically reloading/refreshing due to which browser does not refreshes...And i cant see the real time changes i have made in my code......

I don't understand what you mean here, why would the terminal "reload" when you save a file?

> Wherever i declared some variables and imports which is no longer assigned/used in the below file....editor shows them in light gray and [hints] that i have not used them/not assigned below.....

This is a new feature, see https://code.visualstudio.com/updates/v1_24#_highlight-unused-variables-and-imports for how to disable.

**Comment by deepak-ranolia** [comment]
### I don't understand what you mean here, why would the terminal "reload" when you save a file?
 @Tyriar : In visual studio code [ terminal window ] I have an angular application in development mode. So whenever i start coding the application i run command "ng serve" from terminal so that i can see the application in browser[http://localhost:4200]...So if i will save the file after some changes in the code, terminal window re-compile/build the process so that i can see my corresponding changes[after 100% compile/build] in the browser...
But now it is not happening at all when i save a file.

What more info you will need to solve the issue ???

**Comment by Tyriar** [comment]
@deepak-ranolia that's 100% a problem with the application you're running within the terminal, file watching and reacting to it is up to `ng serve` to do and act upon.

**Comment by deepak-ranolia** [comment]
![screenshot from 2018-07-04 12-37-47](https://user-images.githubusercontent.com/33685167/42261861-20eca6ce-7f87-11e8-99ef-c9586922ee02.png)
 @Tyriar I have attached the screenshot, Here i can run all the cmds related to angular and all. All are working fine and my application has no bug[May be there is other configuration for the reload problem] and i can easily see my app on browser[Ip changed here in screenshot]. Now if i will save the file after editing, the terminal should automatically re-compile itself. Right ?

But it is not happening at all.

**Comment by Tyriar** [comment]
@deepak-ranolia it's a problem with the watch compile program you're using, not the vscode terminal. The terminal just hosts some process which does things, it doesn't provide a file watch service to the processes or anything.

**Comment by deepak-ranolia** [comment]
@Tyriar Thanks man !
Yeah its not the VSCODE issue at all and appreciate for the new version release
Right now i have to run everytime i restart my vscode

## echo 65536 | sudo tee -a /proc/sys/fs/inotify/max user watches

Still looking for answers but not here :-)

**Comment by Tyriar** [comment]
You can do it permanently by adding to `/etc/sysctl.conf`, we have instructions to up the limit in our docs too https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc
