### ISSUE TITLE
Repeated characters inserted in editor

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#53483]
Create the following `file.py`:

```py
name = f"joao {dsaname}"
ddd
modifieddsadsadsa a long long long modifieddsadsadsa a long long long modifieddsadsadsa a long long long 
dsanamedass
dsasdaadss

dsaa
```

Close the file, open the file again, move the cursor to the end of line 2 and type `d`.

![issue](https://user-images.githubusercontent.com/22350/42213559-690bccce-7eb9-11e8-99b9-09c766bf6d19.gif)

**Comment by alexandrudima** [comment]
Duplicate of #49480
