### ISSUE TITLE
Update Extension does not show reload anymore [Insiders build]

### ISSUE THREAD

**Issue by wsmelton** [Microsoft/vscode#53493]
Issue Type: <b>Bug</b>

1. You get the notification in the Extensions panel that you have an update for an extension (e.g. shows "update to x.x.x").
2. Click the Update button for that extension.
3. Button changes to installing.
4. Button changes to "update to x.x.x" showing the same version.
5. Reload window
6. Check extension and it was updated to the "x.x.x" version.

The previous behavior showed a "reload" on that button after the installation was completed.

VS Code version: Code - Insiders 1.25.0-insider (499122702e462b458117122a6885e6aeb3cec0a4, 2018-06-29T05:18:12.665Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Memory (System)|15.92GB (11.03GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
cform|aws|0.0.10
bracket-pair-colorizer|Coe|1.0.58
vscode-markdownlint|Dav|0.18.0
docs-article-templates|doc|0.1.2
docs-authoring-pack|doc|0.1.1
docs-markdown|doc|0.1.1
xml|Dot|2.3.1
gitlens|eam|8.4.1
vscode-great-icons|emm|2.1.35
vscode-azurestorage|ms-|0.4.0
azure-account|ms-|0.4.1
PowerShell|ms-|1.7.0
wordcount|ms-|0.1.0
azurerm-vscode-tools|msa|0.4.2
vscode-docker|Pet|0.0.27
arm-snippets|sam|1.2.0
vscode-sql-beautify|sen|0.0.4
code-settings-sync|Sha|2.9.2
code-spell-checker|str|1.6.10
gitblame|wad|2.4.2

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
Fixed in latest insiders.
