### ISSUE TITLE
Access modifiers in constructor are not highlighted when using decorators with parameters

### ISSUE THREAD

**Issue by olostan** [Microsoft/vscode#5349]
- VSCode Version: 1.0.0

Language: TypeScript

Steps to Reproduce:

1. Add a decorator/annotation that accept parameter(s)
2. Put this annotation on constructor's parameters with "private"/"public" modifiers

![image](https://cloud.githubusercontent.com/assets/459897/14565474/f3bf3a9e-0333-11e6-9469-1cfd42c9db0c.png)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#148
