### ISSUE TITLE
Wrong cursor position in a tsv (tab separated values) file

### ISSUE THREAD

**Issue by ricobautsch** [Microsoft/vscode#53490]
Issue Type: <b>Bug</b>

I have a file with tab separated values.
The cursor for editing is not placed correctly in the document, especially if i want to edit columns nearly the end of the document.
Following i paste the content of my file - for example try to edit the char "u" near the end of the document.
My file contains the following content (a single line with tab separated values):

12	b	06	Test	Heini	19721020		104512074	111222333444				177777700	123456701	20180522	R60.0      G, L97 Z R, F09 G,	f		180101	180331		1	7										1		i	2	1		0111	0122								l	1		2	7											1	3	6				1	4	5										Sonst	Anlei	u	1	1	1									

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700T CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Memory (System)|31.92GB (19.75GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe D:\temp\Spezifikation\Barcode\Verordnungen\codes\test.tsv|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|0.11.1
pascal|ale|0.11.0
better-toml|bun|0.3.2
sftp|lix|1.2.3
rainbow-csv|mec|0.4.2
mssql|ms-|1.4.0
csharp|ms-|1.15.2
PowerShell|ms-|1.7.0
debugger-for-chrome|msj|4.7.0
vscode-docker|Pet|0.0.27
vscode-autohotkey|sle|0.2.2

</details>

**Comment by alexandrudima** [comment]
I cannot reproduce on my machine, but I've heard others reporting it. It might happen for certain fonts and on certain machines, that the monospace font rendering is not 100% monospace. i.e. we measure the width of one character (`w`) and then assume that N characters have the width `N*w`... but this does not always hold true .. unclear why.

Does this issue go away when using the internal setting `"editor.disableMonospaceOptimizations": true` ?

**Comment by ricobautsch** [comment]
Yes, the issue is going away when using your suggestion and setting "editor.disableMonospaceOptimizations": true.

I found another thing.
The issue is only present, if i enabled Whitespace rendering with the setting "editor.renderWhitespace": "all".
I enabled this, because i have to see the number of tabs between two visible values.
Maybe the issue is not with rendering the visible chars, but with rendering the whitespaces (in my case the arrow for a tabulator).

**Comment by alexandrudima** [comment]
@ricobautsch Thank you for the additional screenshot. I believe this was sharing the same root cause as #54146. So I think 22c1af5a3e5867da647d2484c4406aea35d6e392 fixed it too. It has to do with the character we use to render tabs that end up occupying 1 space on screen, `￫` vs `→`... In some cases that would lead to a breakage of monospace.
