### ISSUE TITLE
Subword navigation : Confusing keybinding name

### ISSUE THREAD

**Issue by V-ed** [Microsoft/vscode#53497]
Issue type : Modification Request

After the PR #48023 has been merged, a feature I really like has been added to VSCode and is currently in Insiders. Thing is, there is two commands that confused me when I first read them :

![vscode cursorWordPartStartLeft](https://user-images.githubusercontent.com/16652915/42236216-455932b2-7ec8-11e8-93ce-83f09909c746.png)

`cursorWordPartStartLeft` and `cursorWordPartStartLeftSelect`

I propose a very slight modification to them : the word `Start` is rather confusing and should be removed. These two commands does the exact same behavior as `cursorWordPartRight` (_but goes to the left_), so I feel like they should be named the same way : `cursorWordPartLeft` and `cursorWordPartLeftSelect`.

<details><summary>VSCode Insiders Info</summary>
<p>

```
  Version: 1.25.0-insider
  Commit: 33ba00346fd1bc889d5adc2f386c64fdb3657e61
  Date: 2018-07-03T14:40:32.630Z
  Electron: 1.7.12
  Chrome: 58.0.3029.110
  Node.js: 7.9.0
  V8: 5.8.283.38
  Architecture: x64
```

</p>
</details>

**Comment by slinstj** [comment]
Same feeling. The names should keep the coherence.
