### ISSUE TITLE
plan to support babel-cli debugging?

### ISSUE THREAD

**Issue by Beingbook** [Microsoft/vscode#535]
Hello.
VS Code supports only 'node' type. But it's not enough to test my project. I need to exec command directly such as `babel` and `eslint`. So I'm asking to you where options for aforementioned?

Thank you!

**Comment by isidorn** [comment]
Hello,

Did you try using the `preLaunchTask` in `launch.json`.
More details about debugging and `preLaunchTask` can be found [here](https://code.visualstudio.com/docs/editor/debugging)

**Comment by Beingbook** [comment]
I saw about `preLaunchTask`. It looks need `gulp` tasks.
I just want to build purely as `babel-node ./tools/run.js` (https://babeljs.io/docs/usage/cli/)
`babel` actually can be executed in script side but I prefer command than gulp.

**Comment by isidorn** [comment]
This should be possible by introducing a task that does just that.
Please read our [tasks doc](https://code.visualstudio.com/docs/editor/tasks) on how to do that.
Then you can reference this task from the `preLaunchTask`
