### ISSUE TITLE
Icons are missing in the SCM view

### ISSUE THREAD

**Issue by geoffrey-vl** [Microsoft/vscode#53500]
Issue Type: <b>Bug</b>

The source control panel is not showing the "open file", "discar changes", "stage" icons at the right side of changes files (git).

Also Visual Studio Icons extension not rendering icons, while the Great Icons extension does.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:47:35.732Z)
OS version: Linux x64 4.4.0-130-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz (4 x 2771)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 1|
|Memory (System)|7.69GB (3.44GB free)|
|Process Argv|/usr/share/code/code|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icons|rob|7.24.0

</details>

**Comment by Pato91** [comment]
The search input for the branches appears to be a password input instead of a plain text input. It masks the branch text you are typing into the text field/text input.
![vscode](https://user-images.githubusercontent.com/29727441/42273872-30c915c6-7f93-11e8-9a3e-dcac70209e36.png)


Version 1.24.1
Commit 24f62626b222e9a8313213fb64b10d741a326288
Date 2018-06-13T17:47:35.732Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by joaomoreno** [comment]
@geoffrey-vl Can you share a screenshot?

@Pato91 Please file a separate issue.

**Comment by geoffrey-vl** [comment]
Sure, I hadn't noticed Github's drag and drop support until now :-)

![schermafdruk van 2018-07-03 21-32-10](https://user-images.githubusercontent.com/4291362/42290208-1caca0b8-7fc4-11e8-8f2d-f9d2739de8c7.png)
![schermafdruk van 2018-07-04 19-55-39](https://user-images.githubusercontent.com/4291362/42290276-898d73ec-7fc4-11e8-9a2a-804cec8358bf.png)

**Comment by joaomoreno** [comment]
What icon theme do you have selected?

**Comment by geoffrey-vl** [comment]
vscode-icons.

**Comment by joaomoreno** [comment]
If you choose another theme, do the icons appear?

**Comment by geoffrey-vl** [comment]
With VSCode Great Icons, yes.

**Comment by joaomoreno** [comment]
Please reinstall the vscode-icons extension. If it still doesn't work, file an issue to https://github.com/vscode-icons/vscode-icons

**Comment by geoffrey-vl** [comment]
I think you misunderstood. The visual bugs with the icon theme is _just another visual bug_. There is also a problem with visualizing the icons in the SCM/git view. As I said in the beginning: 

> The source control panel is not showing the "open file", "discar changes", "stage" icons at the right side of changes files (git).

You only get these icons when you hover a changed file, that's why its not in the printscreen. 
But what you _can see_ in the printscreen is that there is also the "commit" and "refresh" icons missing.
It is not icon theme related since I've tried running VSCode without any icon theme installed and it is still having this issue. Also these icons should be there on a default freshly installed vscode, here is how that looks like on another pc (I've marked in red the icons that are missing):
![image](https://user-images.githubusercontent.com/4291362/42310253-3b9015ce-803b-11e8-95a1-9eb88d4eeac0.png)

**Comment by joaomoreno** [comment]
Oh I see, sorry for that!

**Comment by bpasero** [comment]
@geoffrey-vl are you saying the icons show up as soon as you hover over them?

**Comment by geoffrey-vl** [comment]
No, they're not shown at all. The helper texts do popup, so hovering works.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by geoffrey-vl** [comment]
I can confirm it's having the same issue. No icon theme installed this time.

![schermafdruk van 2018-07-05 19-48-59](https://user-images.githubusercontent.com/4291362/42339185-8cd4ba10-808c-11e8-9ba1-202ab2428a06.png)

**Comment by bpasero** [comment]
@geoffrey-vl are there any other places where the icons are missing?

**Comment by geoffrey-vl** [comment]
well, not that I've been aware of

**Comment by bpasero** [comment]
@geoffrey-vl does a full reinstall help?

**Comment by geoffrey-vl** [comment]
I've used the tarball for nightly builds, so I guess that counts as a yes

**Comment by bpasero** [comment]
@geoffrey-vl are you familar with chrome devtools and could check if the element of the action has the correct CSS rule applied that points to the image?

**Comment by geoffrey-vl** [comment]
> @geoffrey-vl are there any other places where the icons are missing?

As of today I've noticed the split view icon is also MIA

**Comment by bpasero** [comment]
Sorry, I do not know why this happens for you and it does not seem like any other user is hitting this so far so I can only speculate it must be very specific for your configuration.

**Comment by geoffrey-vl** [comment]
My Ubuntu VM at works handles everything OK so as it seems it might be a OS/driver/rendering issue.
