### ISSUE TITLE
Inconsistent completion for re-export

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#53502]
- VSCode Version: 1.24.1
- OS Version: Windows Server 2016

Steps to Reproduce:

```ts
// a.ts
export interface Foo { ... }

// b.ts
export * from './a'
export function do() { ... {

// c.ts
import { do } from './b'

const a: Foo // autocomplete while typing suggests "import { Foo } from './a'"

const b: Foo = { ... }
// Show Fix (Ctrl+.) suggests adding "Add 'Foo' to existing import declaration from './b'
```

It would be great if autocomplete also allows (and prefers) importing from './b'

**Comment by mjbvz** [comment]
Please try upgrading your workspace to use `typescript@next` by following [these instructions](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions). Do you still see this issue when using `typescript@next`?

**Comment by unional** [comment]
Still exist in 1.25.0
