### ISSUE TITLE
Split Editor's [Contextual Menu Options]

### ISSUE THREAD

**Issue by soulshined** [Microsoft/vscode#53504]
This might be circumstantial to me, but I just find splitting windows is not as intuitive as other editors I've used. 

I personally think the best and easiest fix would just add 2 contextual menu options (split horizontally, split vertically). 

When splitting, the split button (next to the more button) is great, but it keeps the same file on each pane it's in, which I understand is a need, but I would like to split it, while moving the file to the new split view. I know this can be done with keybinds, but memorizing 3-4 different keybinds depending on the scenario doesn't feel right in my opinion for something that should be easy. 

Not to mention, it took me a good while to figure out how to switch horizontal to vertical using keybinds. (it's just in a weird place in my opinion, why is it with the file tree when it doesn't affect it? 
Might be a reason beyond me that is valid)

In most cases, I am pro-keybindings, anything to keep my hands on the keyboard, but this circumstance would be nice just to have a right click option for those that want it, or simple addition to the 'Split Editor' button.

If contextual menu's aren't an option, might I suggest something simple like moving the vertical editor group layout button outside of the explorer pane so I don't have to open it every time to toggle it? Or at minimum, can you give us a user/workspace setting parameter to toggle if it splits moving the file with it, or splitting a copy of the file? That would work just fine.

----

Also, I am aware there is a right click option in the explorer pane, but again, this is not optimal because when you are working with large projects navigating to the file you need just to right click and select "Open to the side" can prove to be arduous as the number of files grow.  I am meaning more of right click of the file that's being edited (it's name). 

Thanks for your time.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_25.md#grid-editor-layout
