### ISSUE TITLE
Markdown preview doesn't show headers

### ISSUE THREAD

**Issue by DieLaughing** [Microsoft/vscode#53501]
When I open a regular markdown file using hashtags to set the heading level, it simply doesn't change anything in the preview and just displays the hashtags without marking anything up or down
UNLESS I ADD A SPACE.

I don't know if I'm losing my mind, or just got really old when nobody was looking, but I could have SWORE that

##Header##

was a legit header in Markdown. But apparently, the rules changed and there must be a space now like

\## Header

Sorry if this isn't a bug. I'm still trying to figure out where and when I missed the info that a space is required after the hashtags. All of my "old" Markdown looks like &*#$ garbage now on VSCode.

**Comment by mjbvz** [comment]
CommonMark requires a space after the `#` for headers. Our built-in preview targets commonmark markdown but this can be extended by extensions
