### ISSUE TITLE
[python] syntax highlighting breaks on function annotations

### ISSUE THREAD

**Issue by doug-numetric** [Microsoft/vscode#53509]
- VSCode Version: 1.24.1
- OS Version: macOS 10.13.5

Steps to Reproduce:

1. Create a new file: `test.py`
2. Paste in the following text:
```python3
def test() -> None:
    # Broken comment highlighting
    if True:
        print('The if statement above isn't highlighting either.  Same goes for this string')

```

Does this issue occur when all extensions are disabled?: Yes

Appears to be a regression of: https://github.com/Microsoft/vscode/issues/1467

**Comment by aeschli** [comment]
This issue was moved to MagicStack/MagicPython#138
