### ISSUE TITLE
Browse.VC.db file being created out of nowhere

### ISSUE THREAD

**Issue by yoazmenda** [Microsoft/vscode#5350]
- VSCode Version: 1.0
- OS Version: Windows 10 x64

Every time I open a project (Java project) a 4mb "browse.VC.db" file is being created in my repository that can't be deleted.

Steps to Reproduce:
started happening after I tried editing C,C++ files.

**Comment by yoazmenda** [comment]
disapeared ater uninstalling c/c++ extensions

**Comment by BillyONeal** [comment]
Recent versions of the C++ extensions put this file into the .vscode folder.

**Comment by egamma** [comment]
This issue was moved to Microsoft/vscppsamples#14
