### ISSUE TITLE
auto region folding for DSC Configuration

### ISSUE THREAD

**Issue by fatherjack** [Microsoft/vscode#53506]
Issue Type: <b>Feature Request</b>

currently VSCode does not offer to fold lines within a DSC Configuration such as

    Configuration ConfigName {
        param()

        xVHD {
        ...
        }
    }

should fold to 

    Configuration ConfigName {...}
        

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.16299

**Comment by aeschli** [comment]
By default we offer indentation based folding. You example looks nicely indented, so it should work.
![image](https://user-images.githubusercontent.com/6461412/42444866-8fb4f9e2-8371-11e8-8be9-67dff03ba876.png)

If you want language aware folding, this needs to be implemented by an extension.
