### ISSUE TITLE
Incorrect indent when moving code down

### ISSUE THREAD

**Issue by mattacosta** [Microsoft/vscode#53511]
Issue Type: <b>Bug</b>

Steps to reproduce:
1. Select lines 1-3.
2. Press Alt+Down a few times.

Sample code (typescript):
```ts
if (false) {
  //
}
if (true) {
  //
}
if (true) {
  //
}
```

Expected:
The code should be indented and then de-indented as appropriate.

Actual:
The code is always indented.

Notes:
Moving code up works correctly.

VS Code version: Code - Insiders 1.25.0-insider (33ba00346fd1bc889d5adc2f386c64fdb3657e61, 2018-07-03T14:40:32.630Z)
OS version: Windows_NT x64 10.0.17134

**Comment by rebornix** [comment]
Same issue as https://github.com/Microsoft/vscode/issues/54829#issuecomment-422501144, where I left some initial investigations. Let's track this bug there.
