### ISSUE TITLE
extension can not install

### ISSUE THREAD

**Issue by jingr1** [Microsoft/vscode#53516]
The extension market show "No extension found" and when I want to search some extension, it report “An unknown error occurred. Please consult the log for more details.” 
![image](https://user-images.githubusercontent.com/7448804/42254467-5aa6ef4a-7f79-11e8-8a50-c132dbf6fa93.png)

**Comment by sandy081** [comment]
@jingr1 Can you please open your dev tools using command `Developer: Toggle Developer Tools` and provide us the logs?

Can you please check if your internet connection is good.

**Comment by sandy081** [comment]
@jingr1 Click on the console tab in dev tools and you can see errors there.

**Comment by jingr1** [comment]
This is the error logs:
![image](https://user-images.githubusercontent.com/7448804/42266590-72d273a2-7fa9-11e8-940e-9e5676440b2e.png)

**Comment by sandy081** [comment]
@jingr1 Could be a proxy issue - Please check this https://code.visualstudio.com/docs/setup/network

**Comment by jingr1** [comment]
@sandy081 it seems a proxy issue. but why the insider version can works well at the same PC.

**Comment by andremacola** [comment]
Ticket #53549 is the same problem

**Comment by tzaiyang** [comment]
I had the same problem on windows 10 1803 version.

**Comment by sandy081** [comment]
@jingr1 

No idea!!

Can you please try with new stable release (1.25)?
