### ISSUE TITLE
SyntexHighlighting error

### ISSUE THREAD

**Issue by Retrospection** [Microsoft/vscode#53518]
Issue Type: <b>Bug</b>

### Environment
- OS: windows 7 x64
- VS Code Version: 1.24.1

### Content

when explore the Source code of Vue (0948d999 of master branch), in create-element.js from line 55, the editor can't render the code color correctly.

### ScreenShot

![Image](http://wx1.sinaimg.cn/large/70976d6cgy1fsxo4y2tczj20ku0p5abl.jpg)

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.54GB (2.76GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by pronebird** [comment]
Same here, but related to back ticks. It used to work before.

![capture](https://user-images.githubusercontent.com/704044/42273048-4f04b71c-7f88-11e8-851c-2cfd886b048e.PNG)

**Comment by mjbvz** [comment]
Please share the text of the code along with screenshots. Also, 
does this reproduce in the [latest VS Code build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by mjbvz** [comment]
We don't provide built-in support for flow. You should install the flow extension
