### ISSUE TITLE
x11forwarding not woking

### ISSUE THREAD

**Issue by lidm1989** [Microsoft/vscode#53517]
- VSCode Version:1.24.1
- OS Version:centos7

I use vscode via x11forwarding. I'm sure that my environment is ok, because I test by xterm. Vscode can't lanuch, the error:

`.....
[main 11:14:25 AM] Resolving machine identifier...
[main 11:14:25 AM] Resolved machine identifier: ef82848e38b0b2a5622203fa032a1531839642715badf2c32f47de2aa103f2e3
[main 11:14:25 AM] update#setState idle
[26794:0704/111425.448216:ERROR:browser_main_parts.cc(122)] X IO error received (X server probably went away)`

**Comment by bpasero** [comment]
I am closing this as we do not officially support x11forwarding
