### ISSUE TITLE
Fix or delete checkFilePatternRelativeMatch

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#53510]
We have code in fileSearch.ts which checks whether `folder+pattern` is an absolute path match for a file that exists. If so, it's supposed to not apply excludes to that file. But it doesn't work if you type out the query because it will be searching in the cache anyway. It's been broken for quite a while.

If we fix this feature we should move it to openFileHandler.ts like we did for the absolute path check. I would rather remove it to simplify and reduce the amount of work we have to do to use quickopen. I don't think anyone complained when it broke. Is that ok?

@chrmarti 
@bpasero 
?

**Comment by bpasero** [comment]
@roblourens isn't that code obsolete now that we moved the logic of opening an absolute path to the `openFileHandler` anyways?

**Comment by roblourens** [comment]
It covers a different case, absolute paths vs paths relative to a workspace folder.

**Comment by roblourens** [comment]
The absolute path code that we moved already is for when I type `/Users/roblou/code/vscode/package.json`. This relative path code is for when I type `out/vs/css.js`. Normally it would be excluded by an exclude pattern but this code tried to skip the excludes for that file if it's an exact match relative to the workspace folder.

**Comment by bpasero** [comment]
@roblourens interesting, I did not know we have this logic. Yeah we can move this into the openFileHandler too provided we can make it smart enough to not fire too often (e.g. only do it when it contains a slash or backslash). I think we should not do it for top level files because that would mean we do a file check on each keystroke.

**Comment by roblourens** [comment]
Given that nobody knew it existed, and that we would need that restriction on top level files which might seem arbitrary to a user, is it worth keeping? I would rather remove it. @chrmarti and I have discussed a button to disable exclude patterns for quickopen, but I don't remember many people asking for that sort of thing.

**Comment by bpasero** [comment]
I would remove it given that we have the support to open an absolute path, which I would argue is the bigger use case to bypass the exclude pattern.

**Comment by chrmarti** [comment]
`git status` shows relative paths that could be used as input to this 'feature'. Not sure how often this is used (it still seems to work), so maybe remove it early in the milestone and see if there is any feedback on it.

**Comment by roblourens** [comment]
What are you using to test it @chrmarti? It doesn't work for me. 

In any case I'll remove it and see if it affects anyone.

**Comment by chrmarti** [comment]
Just some relative path on OSX, that seemed to work. 🤔
