### ISSUE TITLE
show @deprecated in editor

### ISSUE THREAD

**Issue by WangPengJu** [microsoft/vscode#53514]
![fe8f45fd-60ed-476a-95eb-0cf3f096e633](https://user-images.githubusercontent.com/9954852/42253736-c5a2293a-7f75-11e8-8e93-10309d7eb989.png)
show line

**Comment by mjbvz** [comment]
Api support for this was added with https://github.com/microsoft/vscode/issues/56694

For surfacing `@deprecated` in js/ts specifically, see this upstream issue: https://github.com/microsoft/TypeScript/issues/390
