### ISSUE TITLE
Disable automatic highlighting of current token/word?

### ISSUE THREAD

**Issue by leeoniya** [Microsoft/vscode#5351]
Sorry if this has been asked before (I couldn't find it in any issues containing "highlight").

Is it possible to disable automatic highlighting of the current token/word without also disabling match-highlight for explicit selections via `"editor.selectionHighlight": false`?

Thanks!
- VSCode Version: 1.0.0-insider
- OS Version: Win10

![auto-highlight](https://cloud.githubusercontent.com/assets/43234/14566665/15bae898-02f6-11e6-8d81-d7b287fbd085.png)

**Comment by alexandrudima** [comment]
I think `editor.selectionHighlight` does not stop semantic highlighting, so I don't think we have any option to disable semantic highlighting (from https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/wordHighlighter/common/wordHighlighter.ts#L120)

**Comment by leeoniya** [comment]
> I think `editor.selectionHighlight` does not stop semantic highlighting

Right, it shouldn't. But an additional option to disable this would be very welcome.

**Comment by leeoniya** [comment]
@alexandrudima any updates?

Seems like an easy feature to add, let me know if there's any interest or if you'd like a pull request for this.

**Comment by alexandrudima** [comment]
:+1: on a PR. You can add a new editor option and use it in https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/wordHighlighter/common/wordHighlighter.ts#L120 -- that is where we do the call to do semantic word highlighting to language servers.

**Comment by Bill-Stewart** [comment]
+1 - I like selected matches to be highlighted, but I would like to be able to disable automatic keyword highlighting.

**Comment by PierBover** [comment]
This is really annoying visually.

Also in most themes there's barely a visual difference between a highlighted word and a selected one.

**Comment by Bill-Stewart** [comment]
I agree @PierBover. Please react ![ ](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png) on the top post to raise its profile.

**Comment by leeoniya** [comment]
@aeschli plz put this on your radar in case you'll be working on `WordHighlighter` for #12973

**Comment by jitendravyas** [comment]
any solution to this ?

**Comment by realuser** [comment]
+1

**Comment by alexandrudima** [comment]
Added `editor.occurrencesHighlight` that can be set to false to turn this off. Will be available in tomorrow's insiders build and in the March stable release (i.e. not the one going out in the next few days)

**Comment by Bill-Stewart** [comment]
Thank you @alexandrudima !

**Comment by leikind** [comment]
Having read this discussion a few times I assumed that setting `editor.selectionHighlight` to `true` and `editor.occurrencesHighlight` to `false` will result in the behavior I need: no automatic selection of a word where the cursor is, and a working selection once I select the whole word. But no, in fact, I don't see how `editor.occurrencesHighlight` changes anything at all, and `editor.selectionHighlight` turns highlighting off/on completely.

Still highlighting words automatically when the cursor is:

![screen shot 2017-04-06 at 11 51 59](https://cloud.githubusercontent.com/assets/99266/24748307/90db7bd2-1abf-11e7-8455-e6ae03819c40.png)

- VSCode Version: 1.11.0
- OS Version: MacOS 10.12.4

**Comment by nevcook** [comment]
Same for me.
I also gather from the discussion above, the same conclusion that leikind came to, but I've just installed the latest update (1.11.1) and setting "editor.occurrencesHighlight": false seems to have no effect at all.

**Comment by realuser** [comment]
I also am experiencing that setting `"editor.occurrencesHighlight": false` in user settings appears to have no effect on word highlighting in VSCode:  1.11.1. 

If the cursor is on a word, all occurrences of that word are still highlighted.

**Comment by leikind** [comment]
@alexandrudima Since `"editor.occurrencesHighlight": false` does not have any effect for at least 3 users, shouldn't this ticket be re-opened?

**Comment by leikind** [comment]
@sullerandras 
I installed the Ruby extension and found out that  no matter how I set `editor.occurrencesHighlight`, words in a Ruby file are never highlighted when the cursor is on a word. Contrary to, say, a plain text file when words are always highlighted no matter how I set `editor.occurrencesHighlight`.

**Comment by alexandrudima** [comment]
Thank you for the feedback. For cases where no extension registers a document highlight provider, the selection highlighter compensates and highlights whole words. This can happen for any language where we don't ship with such a document highlight provider (e.g. ruby, sql, pythong).

I've extracted this to #24426

**Comment by dheerajwebkul** [comment]
Updated my vscode to V1.11.2, 
and still
"editor.occurrencesHighlight": false,

is not working to stop highlight semantic symbol occurrence. :(

**Comment by nevcook** [comment]
Was this fix released in VS Code v1.11.2, or is the release of this change still pending?
I ask because for me also, it is still not working.

Language: Go
VSCode: 1.11.2
OS: Windows 10

**Comment by leikind** [comment]
Nothing has changed in 1.11.2.

`"editor.occurrencesHighlight": false` has no effect.

Language: plain text
VSCode: 1.11.2
OS: MacOS

**Comment by maddox** [comment]
Same issue, `"editor.occurrencesHighlight": false` has no effect.

Language: ruby
VSCode: 1.11.2
OS: macOS

**Comment by nbourguig** [comment]
Same issue, "editor.occurrencesHighlight": false has no effect.

Language: javascript
VSCode: 1.11.2
OS: macOS

**Comment by realuser** [comment]
My understanding is that this issue was moved to this issue: #24426 and that issue was fixed but will not appear until the April 2017 milestone which closes April 30, 2017.
