### ISSUE TITLE
debugging a process which creates a daemon child process, the deamon is killed when stop debugging

### ISSUE THREAD

**Issue by royalrover** [Microsoft/vscode#53521]
Debugging a App with a daemon child process，but when I stop debug，the daemon is killed。 So I guess vscode find child processes and send SIGKILL to child. How can I do sth to prevent kill the daemon?

code:
```
    process.title = "main-process"
    if (fs.existsSync(sockPath)) {
        client = new Client({sockPath: sockPath});
        handleClientEvent(client);
    } else {
        let sp = exec.spawn('node', [path.join(__dirname, './child.js')], {
            detached: true,
            execArgv: []
        });
        sp.unref();
        detectionServer()
    }
```

**Comment by weinand** [comment]
VS Code kills the debuggee (and child processes) only if it has started it.
I suggest to use an "attach" debug configuration.
Here VS Code attaches to an already running process and at the end of the debug session it detaches without killing anything.

**Comment by royalrover** [comment]
But the daemon is created by the master process, if use "attach" configuration, I should start the daemo manually, is that so?

**Comment by weinand** [comment]
Just add an argument "--debug=12345" to the spawn call where you launch your demon.

How did you start debugging in your original setup?

**Comment by royalrover** [comment]
Can I listen a signal in daemon to prevent killing the daemon process? I do not want the daemon dead.
