### ISSUE TITLE
Unable to synchronize with GIT VSTS since last VSC update

### ISSUE THREAD

**Issue by DDB19** [Microsoft/vscode#53522]
Issue Type: <b>Bug</b>

Hello, since the last update/upgrade of VSC on my workstation, I am unable to synchronise my local GIT repository with our online VSTS instance.
I have tried to change my PAT on VSTS, with the same result.
I have an error message "Git : fatal: unable to access
'https://xxxxxx.visualstudio.com/xxxxxx/_git/xxxxx/': Failed to connect to xxxxxx.visualstudio.com port 443: Timed out
I am able to acces to my VSTS instance from my browser successfully.
In VSTS i am using Visual Studio Team Services extension and the team: signin feature works.

All was working fine before the last uprade of VSC last week.
Could you please help me to solve this issue ?

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:52:25.282Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.43GB (2.33GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
azureautomation|Awe|0.6.7
azuretoolsforvscode|bra|2.0.2
json-tools|eri|1.0.2
azure-functions-tools|joh|0.3.3
vscode-github|Kni|0.30.0
vscode-azureappservice|ms-|0.8.1
vscode-azurefunctions|ms-|0.9.1
vscode-azurestorage|ms-|0.4.0
vscode-language-pack-fr|MS-|1.24.3
azure-account|ms-|0.4.1
azurecli|ms-|0.4.2
PowerShell|ms-|1.7.0
team|ms-|1.136.0
azurerm-vscode-tools|msa|0.4.2

</details>
.

**Comment by joaomoreno** [comment]
Are you using SSH or HTTPS? Can you show me a screenshot of the error?

**Comment by DDB19** [comment]
I've solved the issue by deleting my local repositories and setting up new configuration of git and team services extension.
It seems to work fine now.
I don't understand what has happened after the VSC upgrade.
Thank you.
