### ISSUE TITLE
All "Find in Folder" results open in the same tab when clicked, unless the content is modified

### ISSUE THREAD

**Issue by ghuser** [Microsoft/vscode#53528]
When performing a find in folder, and see the search results, whichever result is clicked it replaces the same tab.  This happens even if I perform multiple searches.
So I cannot perform 3 consequent searches and open 3 tabs out of them.

It seems like the tab that has been opened from the search result, is treated specially, because even if I select another active tab, and click on a search result, it will replace the last tab that was opened from a search result click.

Only if the tab has been modified the clicked result opens in a new tab.

To my opinion, tabs that open from search result should not be treated specially. If the corresponding file is open it should focus on that tab, otherwise it should open a new tab.

**Comment by roblourens** [comment]
The file should be opened in the 'active group' unless it's already open in a group, in which case it will reveal the file that's already open.

Are you sure the same file isn't already open in that group?

You can also use ctrl/cmd click to open the result 'to the side'.

**Comment by ghuser** [comment]
I think the issue is invalid. I was ignoring the concept of `preview mode` in vscode. Double-click (instead of single-click) on a file entry is the way to keep the tab open. Ref: https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode
