### ISSUE TITLE
Expose diff editor border color

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#53523]
We need a theme color for the diff editor border between the two editors. Currently, the separation happens due to the shadow only... which a theme can define to be really nuanced...

![image](https://user-images.githubusercontent.com/22350/42266089-b0047c5e-7f75-11e8-86ae-a824ebba6b07.png)

**Comment by itamark** [comment]
@joaomoreno So do you think the border for diffs specifically should override any editor border configuration in the theme?

**Comment by joaomoreno** [comment]
No, I think it should be an independent theme color.

**Comment by itamark** [comment]
@joaomoreno Ah - got it. That makes sense. I'll take this today if that's okay.

**Comment by sa-adebayo** [comment]
@itamark are you currently working on this? You are not listed as an assignee.

**Comment by itamark** [comment]
@sa-adebayo I was going to work on it tonight. Only Microsoft/vscode team can add/edit assignees I believe.
Do you want to take this instead of me?

**Comment by joaomoreno** [comment]
We can't add collaborators as assignees. @itamark Looking forward for the PR!

**Comment by itamark** [comment]
Great thanks @joaomoreno

**Comment by itamark** [comment]
Okay @joaomoreno - check out #53931 
I used the same exact colors as the regular editor border for consistency.

**Comment by sa-adebayo** [comment]
@itamark great, I can see that you have submitted a PR. Dropped a comment there.

**Comment by itamark** [comment]
Thanks @sa-adebayo - I pushed the wording corrections and changed the PR description. Your suggestion was so much clearer than my initial text! :-)

**Comment by bpasero** [comment]
@joaomoreno close, this seems to be in via `diffEditor.border` ?
