### ISSUE TITLE
Switch between different window issues with Microsoft Pinyin

### ISSUE THREAD

**Issue by liyuhang1997** [microsoft/vscode#53527]
Force return to the last switched window when I turn on `floating IME mode icon`

- VSCode Version: `1.24.1`
- OS Version: `Microsoft Windows [Version 10.0.17134.112]`

Steps to Reproduce:

1. Press `Windows Key`, Search `IME` and press `Enter Key`
2. Found `中文(中华人民共和国)` and click `Options`, Found `Microsoft Pinyin`（微软拼音） and click `Options`
3. Click `Appearance`
4. Found `Choose how long to show the floating IME mode icon`（选择显示浮动输入法模式图标的时长）
5. Select `1 second` or `3 second` Option
6. Open two differnet vscode window
7. Switch to first window
8. Just Open a file, and click input area, usually, you will see an IME mode icon
9. Switch to next window
10. Repeat step 8
11. Try switching between the two windows, you will find that switching back, the window will switch back soon (When I return to the `Never show` option, everything works fine)

Does this issue occur when all extensions are disabled?: `Yes`

**Comment by liyuhang1997** [comment]
**Additional problems**

When I switch from other windows to VS Code and quickly press the keyboard to input Chinese characters, VS Code will lose the first letter I pressed. The following is an example.

**Example:**

`w ei'run`

![example](https://i.loli.net/2018/07/24/5b56ea52043b8.png)

**Expect:**

`wei'run`

![expect](https://i.loli.net/2018/07/24/5b56ea52045ac.png)

**Comment by upupming** [comment]
I found this issue too when I write markdown. But it doesn't exist when I write code.

**Comment by DeviesVi** [comment]
I can reproduce this bug by chance in all kinds of document.

**Comment by liyuhang1997** [comment]
I haven’t encountered the two problems mentioned above for a long time and it seems to have been fixed.
