### ISSUE TITLE
process.env.PATH not set on load

### ISSUE THREAD

**Issue by leonormes** [Microsoft/vscode#53529]
Issue Type: <b>Bug</b>

I use i3wm on Ubuntu 18:04, and have now made a Clean install. 

When I open VSCode using the i3 launcher, code doesn't load the `PATH` properly. It has a minimal setting and none of the custom ones.

In code developer tools console I get with `process.env.PATH`;

`"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"`

In the terminal outside of VSCode I get;

`/home/leonormes/.nvm/versions/node/v6.14.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`

This means that when I try to start the node debugger code can't find node executable.

If I start code from the command line with `code .` it loads the process.env.PATH variable correctly and I get the same output as the external terminal.

On searching for a solution I have found past issues on here, but they just suggest starting code from the commandline, which is a work-around not a solution. I would like to be able to launch code how I choose and not how the system chooses! 

Why does this happen? I like to have my apps start on startup but currently this doesn't work for code. 

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:47:35.732Z)
OS version: Linux x64 4.15.0-24-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7560U CPU @ 2.40GHz (4 x 3699)|
|Load (avg)|0, 0, 0|
|Memory (System)|15.40GB (9.80GB free)|
|Process Argv|/snap/vscode/38/usr/share/code/code|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vim|vsc|0.14.1

</details>

**Comment by Tyriar** [comment]
Where do you initialize nvm?

**Comment by leonormes** [comment]
I have the suggested addition to my `.bashrc` and `.zshrc`

```
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
```
I have both these rc files but the user is set to use zsh

**Comment by Tyriar** [comment]
On Linux I would recommend you add nvm's init to your profile file instead of rc. The reason being you want access to nvm and its version of node/npm even when you're not in a terminal (or launching from a terminal). This is what I believe you're seeing:

1. Login to Ubuntu (.bash_profile runs)
2. Launch i3 (inherits env)
3. Launch vscode (inherits env)

Compare this to running it within a terminal:

1. Login to Ubuntu (.bash profile runs)
2. Launch terminal (inherits env, runs .bashrc)
3. Launch vscode (inherits env)
