### ISSUE TITLE
Terminal menu still shows up when custom menu is used

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#53524]
We should also take out the "Terminal" menu when using the custom menu:

![image](https://user-images.githubusercontent.com/900690/42268779-b069f4f6-7f7c-11e8-92cf-6f439db0a302.png)

//cc @egamma

**Comment by isidorn** [comment]
@Tyriar @sbatten pushed a fix for this only to the release branch.
What we do for master is up for discussion.
@bpasero please verify once the build is out in 30 mins. Thanks

**Comment by Tyriar** [comment]
Thanks @isidorn, I didn't know about this code.
