### ISSUE TITLE
Provide code action invokation has no diagnostics and range set if context.only === source

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#53525]
It was my understanding that for code actions the call contains the diagnostics relevant for the call so that they can be used to compute the necessary edits.

If `context.only === 'source'` I would have expected that:

- all diagnostics of the file are provided
- the range of the call is the whole file

Is there any reason why this is not the case?

For ESLint I have for example optimizations that if the file has no eslint errors I don't go bother the server.

**Comment by dbaeumer** [comment]
@jrieken FYI.

**Comment by mjbvz** [comment]
I don't understand the problem. How are you trying to get the code actions? Using the command?

**Comment by dbaeumer** [comment]
From the UI execute `Source Actions` from the context menu in the editor. This calls the registered code action provider, but no diagnostics are passed in the context. To my understanding a code action provider should in this case provide code actions applicable to the file (not cursor position). Hence I would expect to get all diagnostics of the file in the context.

**Comment by dbaeumer** [comment]
@mjbvz any comments? Is there anything else you need.

**Comment by mjbvz** [comment]
Not sure about this. The current design treats source actions just like normal code actions,  so they are passed the editor selection and diagnostics in that selection. We leave it up to the extension's source action provider to determine they care about the entire document or just the selection

Could eslint use the new diagnostic reading apis to check the diagnostics in the file?

Any thoughts @jrieken?

**Comment by jrieken** [comment]
Hm, my initially feel would have been that source actions are requested for the entire source file

**Comment by dbaeumer** [comment]
I can workaround this but at a minimum we need to specify what we do. I had the same feeling as @jrieken that if a source action is for the whole file I get the diagnostics for the whole file.

**Comment by mjbvz** [comment]
@jrieken Any concerns about the number of diagnostics we will end up sending for large files?

If we start treating source actions differently, we must document that they are intended to apply to the entire file. When we originally designed source actions, we said that something like `format selection` could become a source action. With this change, you could have a `format` source action but not a `format selection` action

**Comment by jrieken** [comment]
>  number of diagnostics we will end up sending for large files?

We actually not sending them but we re-collecting them on the extension host side: https://github.com/Microsoft/vscode/blob/5c21818cfb3128f9512acc012eed7fb03564806e/src/vs/workbench/api/node/extHostLanguageFeatures.ts#L312-L318

> If we start treating source actions differently, we must document that they are intended to apply to the entire file. 

How about this: An empty selection becomes the whole document and the non-empty selection remains what it is?
