### ISSUE TITLE
CRLF switch is broken on Windows

### ISSUE THREAD

**Issue by pronebird** [Microsoft/vscode#53530]
- VSCode Version: 1.24.1
- OS Version: Win 10

Steps to Reproduce:

1. Open any file saved in LF. VSCode shows it's in CRLF
1. Switch to LF from the statusbar
1. The file is changed in Git
1. Run `git diff` and see:
```
warning: LF will be replaced by CRLF in app/index.js.
```

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
> Open any file saved in LF. VSCode shows it's in CRLF

Can you show me the file? If I open an LF file, VS Code says it is LF.

**Comment by MarekLew** [comment]
This is git problem. You git configured convert `LF->CRLF`, read this: https://stackoverflow.com/questions/5834014/lf-will-be-replaced-by-crlf-in-git-what-is-that-and-is-it-important
