### ISSUE TITLE
tasks.json: "Ctrl+click to follow link" not working if presentation panel is "shared".

### ISSUE THREAD

**Issue by dsanz006** [Microsoft/vscode#53537]
I am using VS Code on Linux to build my C/C++ project, which uses gmake. If I have compiler errors, I get them very nicely displayed in the terminal window. If I have `"panel": "new"` or `"panel": "dedicated"` under the `"presentation"` field in my tasks.json file, I get a very nice feature on the terminal: if I Ctrl+Click on a compile error, it takes me to the file and line of the error directly.

However, if I set `"panel":"shared"` I don't get this feature any longer. Is this a bug, or is there a reason for this?

**Comment by dbaeumer** [comment]
No this sounds like a bug. Can you provide us with a GitHub repository to clone which demos this. Does it work on the first task execution?

@Tyriar could it be that the ternminal doesn't register a link provider if the terminal is reused.

**Comment by Tyriar** [comment]
@dbaeumer I don't think they do `TerminalInstance._onProcessExit` runs when `waitOnExit` is true, then `reuseTerminal` is called if it's shared. Only `TerminalInstance.dispose` disposes the link handler. Could this be related to the `deregisterLinkMatcher` calls in terminalTaskSystem.ts?

**Comment by dbaeumer** [comment]
@Tyriar since I pass in the handle I always thought it only deregisters that one. And at the end I don't register any (`registerLinkMatchers` is commented out due to another issue) so registering shouldn't do anything.

The link matcher used is the standard file link matcher the terminal is using.

**Comment by dsanz006** [comment]
I just created  a new repository to replicate this error. It is a dummy project based on my real one. The link is the following: [https://github.com/dsanz006/test_vscode_terminal_link.git](url)

Basically it is a C++ project with only one source file, and it is compiled using gmake. The gmake files are generated with premake.

If on tasks.json I make the terminal "dedicated" or "new", then the links work, but with "shared", they don't work. I have also discovered that if I remove the "dependsOn" option, the links work fine too. It is the combination of "shared" and "dependsOn" that make it fail. 

I also have another question: is there a way to force the terminal to close once a task finishes executing? I don't want to "press any key" always.

**Comment by dbaeumer** [comment]
@dsanz006 thanks for the test case. Since it requires quite some dependencies I tried to reproduce this with a smaller case but fails. Do this work for you:

```
{
	// See https://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "2.0.0",
	"tasks": [
		{
			"label": "echo",
			"type": "shell",
			"command": "echo 'an error in ./main.ts'",
			"presentation": {
				"echo": true,
				"reveal": "always",
				"focus": false,
				"panel": "shared"
			},
			"problemMatcher": []
		}
	]
}
```

and having a `main.ts` having in the workspace as well.

**Comment by dsanz006** [comment]
I don't really understand what you want me to test. I added this task to tasks.json, executed it, and obviously I just get the following output: `an error in ./main.ts`. Everything seems fine to me, as this task just echoes what it should.

I tried it without a `main.ts` file (it wouldn't change anything if I had it). What is this file?

**Comment by dbaeumer** [comment]
@dsanz006 I tried to create a minimal test case since the repro you provided requires installing a lot of additional dependencies which I try to avoid.

As you said in the initial description this only happens when using a shared panel. I however can run the above task twice and it works as expected. The link is detected and control clicking on it opens the file. Can you think of any difference between your output and mine that would explain why it fails.

**Comment by dsanz006** [comment]
I have tried it creating an empty `main.ts` file in the root of my repository, and it works correctly: When I run the `echo` task, I ctrl+click the link on the terminal and the `main.ts` file opens correctly.

**Comment by dbaeumer** [comment]
@dsanz006 ok. that confirms that the support works in general. Any idea what is different in your case. When you run it a second time does the terminal underline the link when hovering over it?

**Comment by dsanz006** [comment]
I have no idea what is different in my case, except the obvious differences, that it's a gmake command which compiles a C++ project.

In the task you created, the terminal underlines the link and opens it correctly. In my task which fails, the terminal doesn't even underline the link.

**Comment by dbaeumer** [comment]
OK. Can you provide me with the output of the task in textual form. May be I see something.

**Comment by dsanz006** [comment]
This is what the terminal output looks like:

`> Executing task in folder test_vscode_terminal_link: make config=debug64 <

==== Building dummy (debug64) ====
Creating output
Creating output/debug/x64
main.cpp
../../src/main.cpp: In function ‘int main()’:
../../src/main.cpp:8:11: error: ‘error’ was not declared in this scope
     error();
           ^
dummy.make:106: recipe for target 'output/debug/x64/main.o' failed
make[1]: *** [output/debug/x64/main.o] Error 1
Makefile:16: recipe for target 'dummy' failed
make: *** [dummy] Error 2
The terminal process terminated with exit code: 2

Terminal will be reused by tasks, press any key to close it.`

**Comment by dsanz006** [comment]
Not fixed though

**Comment by dbaeumer** [comment]
Reopening. @dsanz006 what happens if you execute the task directly in the terminal. Will you be able to click the links?

**Comment by dsanz006** [comment]
No, I can't click the links, but I could never do that: I could only click the links when executing from VS Code, if panel was "new" or "dedicated".

**Comment by dbaeumer** [comment]
@Tyriar any idea. This seems to be task unrelated since the links aren't clickable even when executed directly in the terminal.
