### ISSUE TITLE
Remove Seti icon theme and/or replace it

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#53538]
Seti last update was 2 years ago (https://github.com/hellopao/vscode-seti-icons). It even contains several issues from your team and they are not fixed. My suggestion is to remove it from VS Code and replace it with https://marketplace.visualstudio.com/items?itemName=robertohuertasm.vscode-icons which is updated regularly. Or if you don't want to replace it then it makes sense to fork it and update it or remove it completely.

**Comment by svipben** [comment]
Also, this will improve autocompletion for paths to show icons depending on the file extension instead of a blank untitled file like it's right now.

![image](https://user-images.githubusercontent.com/10441177/42413410-d7f471ec-8227-11e8-8092-debed222c5f7.png)

**Comment by aeschli** [comment]
The built-in seti theme is generated from https://github.com/jesseweed/seti-ui which has gotten regular updates.
https://github.com/hellopao/vscode-seti-icons is an unrelated extension on the marketplace.

The screenshot is interesting. I wasn't aware that we use file icons in the code completion suggestion window. @octref Have you worked on this, or is this a vscode-icons innovation?

I can't see this in 1.26.0-insider with the vscode-icons theme:
![image](https://user-images.githubusercontent.com/6461412/42446473-ac6c68d6-8376-11e8-9e18-e4812937bf86.png)

**Comment by svipben** [comment]
@aeschli I created that with Sketch to show how it can look like 😄

Also, I didn't know that about Seti, good to know, but I guess it makes sense to consider to use `vscode-icons` since it's for VS Code, not like Seti for Atom and it doesn't have workspaces, etc. I don't know how hard integration is to replace Seti, but I will definitely consider it to win in both sides. First is to have icon theme especially for VS Code which is maintained, very beautiful and contains all the needed icons. Second is to have file/folder icons for code completion like in my screenshot which was created to show the example of how it will improve it.

**Comment by octref** [comment]
@aeschli @svipben https://github.com/Microsoft/vscode/issues/44860

@jrieken Just an +1 for that one. I think this would be something really nice to have.

**Comment by aeschli** [comment]
@svipben Seti and vscode-icons look quite different and replacing one with the other would not please everyone.
Also, we don't want really to bundle more extensions with VSCode:
- `vscode-icons` is an independent, highly successful extension, that have their own way of working and can release updates any time.
- we want to keep the VSCode installation lean
