### ISSUE TITLE
Mocaco styles overriding color theme

### ISSUE THREAD

**Issue by MaximeDesRoches** [Microsoft/vscode#53540]
- VSCode Version: Version 1.24.1 (1.24.1)
- OS Version: macOS High Sierra 10.13.3

Steps to Reproduce:

1. Open a JS file and import another js but don't use it. (eg: `import * from TweenMax`)
2. Monaco adds the `squiggly-overlay-unnecessary` class which overrides the theme color set for that line. (previously it put a squiggly green line under)

![image](https://user-images.githubusercontent.com/5558036/42281244-f15e24f2-7f70-11e8-86b8-3165be95c52d.png)
![image](https://user-images.githubusercontent.com/5558036/42280880-f61c023a-7f6f-11e8-9606-6a2ca1fbee4c.png)
![image](https://user-images.githubusercontent.com/5558036/42281218-dcaa2d6c-7f70-11e8-858b-dc0c0a76f3a4.png)

**Comment by mjbvz** [comment]
This is by design. It indicates that the code is unused. In VS code 1.25, we fade out the code instead of changing it to grey
