### ISSUE TITLE
Wrong name for shared.sock

### ISSUE THREAD

**Issue by andremacola** [Microsoft/vscode#53549]
- VSCode Version: 1.25.0-insider (1.25.0-insider)
- OS Version: High Sierra 10.3.4

Steps to Reproduce:

0. Your home folder need to be like `/Volumes/customdrive/users/username`
1. Install VSCode and launch.
2. Close VSCode and relaunch.
3. Extensions tab is buggy and forever loading.
4. Developer tools showing: `Uncaught Error: Error deleting the shared ipc hook.`
5. Go to `~/Library/Application Support/Code - Insiders` folder and see wrong naming for .socks
6. Rename/delete .soc/.socks files and relaunch VSCode for a temp fix.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Unfortunately, you seem to be hitting https://github.com/Microsoft/vscode/issues/51048 for which we only have one suggestion: use a shorter `user-data-dir` path.

**Comment by andremacola** [comment]
@joaomoreno interesting but why VSCode Stable is fine? The problem is only with Insider
