### ISSUE TITLE
[html] update to jsbeautify 1.8.0-rc2.

### ISSUE THREAD

**Issue by Mlocik97-issues** [Microsoft/vscode#53546]
Issue Type: <b>Bug</b>

[HTML, Format Doc / js-beautify] comment behind tag is formated as comment above next tag:

for example:

```
<script src="/lib/jquery.js"></script> <!-- jquery library -->
<script src="sw.js"><script>
```
is formated as
```
<script src="/lib/jquery.js"></script>
<!-- jquery library -->
<script src="sw.js"><script>
```

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (12.39GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by jrieken** [comment]
@Mlocik97-issues What extension are you using to format html?

**Comment by Mlocik97-issues** [comment]
> Extensions: none

**Comment by bitwiseman** [comment]
@Mlocik97-issues  
https://github.com/beautify-web/js-beautify/issues/1337

**Comment by Mlocik97-issues** [comment]
@bitwiseman can I ask, when it will be aplicated in vs code? can it be in "June" Recovery patch?

**Comment by aeschli** [comment]
1.8.0-rc2 is now in 1.26.0.
However, I still have to surface the `wrap_attributes_indent_size` and `aligned-multiple` options.

**Comment by bitwiseman** [comment]
@aeschli 
Please consider taking https://github.com/Microsoft/vscode-html-languageservice/pull/31 - update to 1.8.0-rc4. It has significantly better performance and fixes a few sev1 bugs.
