### ISSUE TITLE
No 24/7 inteli-sense in css comments

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#5354]
- VSCode Version: alpha
- OS Version: os x

Steps to Reproduce:

1. open a css file, start writing a comment
2. notice that the 24/7 intelli-sense is always in your face, it is quite frustrating

I know that for .js we do not show 24/7 intelli-sense inside comments, I would like the same for other premium languages we have, e.g css.

**Comment by jrieken** [comment]
> I know that for .js we do not show 24/7 intelli-sense inside comments,

That's not true. We always show textual completions on type. The rule is that as long as the higher ranked provider returns a result, the lower ranked (textual completions) won't get a shot.  What is different between textual and other completion is the _commit on special character_ rule.

Once CSS becomes an extension the behaviour is the same. Nothing to do here
