### ISSUE TITLE
Apply HTML formatter to a custom file / language?

### ISSUE THREAD

**Issue by atif089** [Microsoft/vscode#53543]
`VS Code Version: 1.24.1`

We use a specific non-standard file extension and format for templating which looks similar to HTML. Is it possible to enable only HTML formatter in that document? And if yes, can this be done through the workplace configuration or do I need to write a plugin to handle this?

I do not want to share all the features, I need just the formatter.

My workflow at the moment is to switch the document language to HTML, format, and then switch it back to the templates.

**Comment by aeschli** [comment]
> enable only HTML formatter in that document
Sorry, you would need to write an extension.
