### ISSUE TITLE
Git hooks using Shell script timeout in VSC but work in VS2017

### ISSUE THREAD

**Issue by jimmyheaddon** [Microsoft/vscode#53553]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Create a `pre-commit` file in the `.git/hooks/` folder alongside a Git repository
2. Paste this simple Shell script in to this newly created file, and save

```
#!/bin/sh
# Stops accidental commits to master and develop. https://gist.github.com/stefansundin/9059706
# Install:
# cd path/to/git/repo
# curl -fL -o .git/hooks/pre-commit https://gist.githubusercontent.com/stefansundin/9059706/raw/pre-commit
# chmod +x .git/hooks/pre-commit

BRANCH=`git rev-parse --abbrev-ref HEAD`

if [[ "$BRANCH" == "master" || "$BRANCH" == "develop" ]]; then
  echo "You are on branch $BRANCH. Are you sure you want to commit to this branch?"
  echo "If so, commit with -n to bypass this pre-commit hook."
  echo "Otherwise, create a feature branch and commit to that."
  exit 1
fi

# This block allows for chaining pre-commit hooks if this hook is a global hook (via core.hooksPath) and there also exists a repo-specific pre-commit hook
if [[ -f ".git/hooks/pre-commit" ]]; then
  type realpath >/dev/null 2>&1 || { echo >&2 "NOTE: the realpath binary is required to chain to the repo-specific pre-commit hook. Ignoring."; exit 0; }
  if [[ "${BASH_SOURCE[0]}" != "$(realpath ".git/hooks/pre-commit")" ]]; then
    .git/hooks/pre-commit
    exit $?
  fi
fi

exit 0
```
3. Open the repository as a folder in Visual Studio Code
4. Make changes to the project
5. Attempt to commit to any branch (it should prevent you from committing to the `master` branch)

On all machines I've tried (including multiple versions of VSC), this causes the Git commit operation to hang, with `index.lock` remaining.  The very same folder opened in Visual Studio 2017 works perfectly, with no modifications to the script.

I hope this hasn't; been raised before, isn't expected behaviour, and isn't just the Shell script.  Apologies if that's the case!  If not, it's a real pain to jump between VSC and VS2017, when VSC consistently falls over, and I have to open VS2017 to commit or push!

Does this issue occur when all extensions are disabled?: Yes

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600 Six-Core Processor             (12 x 3200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (8.80GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.12
tslint|eg2|1.0.33
vscode-npm-script|eg2|0.3.4
debugger-for-chrome|msj|4.7.0
vscode-versionlens|pfl|0.21.1
vscode-icons|rob|7.24.0
trailing-spaces|sha|0.2.11
autoimport|ste|1.5.3
vscode-todo-highlight|way|0.5.12
vscode-import-cost|wix|2.7.2
html-css-class-completion|Zig|1.17.1

</details>

**Comment by joaomoreno** [comment]
This is what I see when I try to commit on Windows, with that hook:

![image](https://user-images.githubusercontent.com/22350/42309104-f48a1d3a-8037-11e8-99ce-945b29f8da14.png)

What Git do you have installed?

**Comment by jimmyheaddon** [comment]
Interesting, I get this on different versions of Git, from 2.17.1.windows.2 to the very latest, 32 and 64bit.  I've tried Windows 10 v1608, v1709 and again the latest public release.  It's happened for me for well over a year, so all the versions of VSC since then, on multiple machines.  I just can't get my head around it!

**Comment by joaomoreno** [comment]
Are you saving the file as LF?
