### ISSUE TITLE
Why is my workspaceStorage so big and how to clean it?

### ISSUE THREAD

**Issue by souljacker** [Microsoft/vscode#53552]
My workspaceStorage is 7 GB big right now. Why is that so huge?

Is there a way to safely clean it?

**Comment by dbaeumer** [comment]
@souljacker what kind of development do you usually do so we understand which extension causes this. Is there one folder sticking out?

At the end it is a dup of https://github.com/Microsoft/vscode/issues/32461 were we try to find was to auto clean the workspace storage folder. Problem is that it is not so easy to determine if the storage is no longer needed.

**Comment by souljacker** [comment]
@dbaeumer Fullstack with PHP, JS (React, Vue) and Node

I do have a BUNCH of extensions (68 lol). Is that what loads the workspaceStorage?

I guess I don't really know what goes in there and how to manage it

**Comment by dbaeumer** [comment]
@souljacker no, the number of extensions is not problematic. It is what extensions write into it. We know that C++ produces a big workspace storage footprint but all other extensions usually behave normal. Which OS are you on. Then I can provide instructions to find out who is causing this.

**Comment by Yannnnnnnnnnnn** [comment]
I just sudo rm them~~ everything seems okay
