### ISSUE TITLE
Wrong monitor being used if window is fullscreen

### ISSUE THREAD

**Issue by monkeygroover** [Microsoft/vscode#53555]
OSX HighSierra (10.13.6 Beta)   VSCode - Version 1.24.1 (1.24.1)

Recently quite frequently vs code has got into a state where it is opening things in the "wrong" window. For example I have two windows open, click on a recent link in the Welcome tab in one window and it opens in the other.. Another symptom when it is in this state is that launching via new window from the dock doesn't create a new window but reuses one already open. When this happens I have to close all windows to recover normal behaviour. I cannot remember ever seeing this happen before the last update. I also haven't seen it happen on ubuntu, only OSX. Has anyone else had window strangeness recently?

**Comment by monkeygroover** [comment]
Update, so I think i found reproducible steps.

Open first window, drag it to second monitor and full screen it.

then go back to first monitor and try to open a second window. (it will reuse the first fullscreen window)

If i don't fullscreen the window all works ok.

**Comment by bpasero** [comment]
@monkeygroover so all of this only reproduces if one window is fullscreen, is that right?

**Comment by monkeygroover** [comment]
Yes I think that appears to be the case. I can't get it to happen if no windows are in fullscreen mode. Not sure if it being on a second monitor is relevant or not, i'll test that when i get a moment.

**Comment by monkeygroover** [comment]
Yes It does require multiple displays. If i have a window fullscreen on a single display I see no issues. As soon as i drag that fullscreen window onto a second display then the problem occurs.

**Comment by bpasero** [comment]
Open for help if someone wants to look into this. It could be an upstream issue too.

**Comment by bpasero** [comment]
@monkeygroover your steps:

> Open first window, drag it to second monitor and full screen it.
> 
> then go back to first monitor and try to open a second window. (it will reuse the first fullscreen window)

This is expected, VSCode does not really know on which monitor you are, so it will open a new window on the monitor of the last active VSCode window. If you have a window opened in the first monitor which is most recently used and try this, the window should open correctly on that monitor.

**Comment by monkeygroover** [comment]
Yes in full-screen that matches what I see. However in windowed mode the new window always opens on the desktop of the dock that I launched new window from no matter what order I do it in or what has focus.

**Comment by bpasero** [comment]
@monkeygroover are you maybe using sierra native window tabs?

**Comment by monkeygroover** [comment]
It appears I am (didn't even know about the option!) however with that off + whatever changed a month or so back this is now working as I would expect.

Thanks!
