### ISSUE TITLE
Snippets: Translate all tab characters (not just leading) to spaces

### ISSUE THREAD

**Issue by coe-jeubanks** [Microsoft/vscode#5355]
- VSCode Version: 1.0.0
- OS Version: Windows 10

With VS Code option: "editor.insertSpaces": set to true, snippets only translate \t characters to spaces when they are at the beginning of the string.

Following snippet correctly translates \t character to spaces:

   "If statement": {
      "prefix": "if",
      "body": [
         "if ${true}",
         "\t$0",
         "end-if"
      ]
   }

Following snippet incorrectly leaves \t as a tab character:

   "If statement": {
      "prefix": "if",
      "body": [
         "if ${true}",
         "_\t$0",
         "end-if"
      ]
   }

**Comment by isidorn** [comment]
We have changed our indentation behavior in the latest release, closing as dup of #5276 and you can see the explanation and workaround there

**Comment by coe-jeubanks** [comment]
Respectfully, I believe this is still an issue that should be looked at, specifically in the portion of code that processes snippets. I checked my settings for "editor.detectIndentation", and here's what I found:

if "editor.detectIndentation" is set to true, and the document uses tabs for indentation:
All "\t" characters in a snippet are translated to tab characters in the document. (correct)

if "editor.detectIndentation" is set to true, and the document uses spaces for indentation:
"\t" that precedes other alpha characters in a snippet is translated to spaces (correct)
"\t" after other alpha characters in a snippet is left as a tab character. (incorrect)

if "editor.detectIndentation" is set to false, and "editor.insertSpaces" is set to false:
All "\t" characters in a snippet are translated to tab characters in the document. (correct)

if "editor.detectIndentation" is set to false, and "editor.insertSpaces" is set to true:
"\t" that precedes other alpha characters in a snippet is translated to spaces (correct)
"\t" after other alpha characters in a snippet is left as a tab character. (incorrect)

I'm not sure of the protocol on closed issues (can they be reopened)? If I should open a new one, please let me know.

**Comment by isidorn** [comment]
Issues can always be reopened, no need to create a new one.
Thanks for the detailed analysis

**Comment by alexandrudima** [comment]
@coe-jeubanks is correct.

We only substitute leading tabs when inserting snippets.

**Comment by alexandrudima** [comment]
fyi @jrieken
