### ISSUE TITLE
Unable to Debug/Run individual Python unites after first run.

### ISSUE THREAD

**Issue by MandarJKulkarni** [Microsoft/vscode#53550]
I use VS code for my Python projects and we have unit tests written using Python's unittest module.
 

- VSCode Version: May 2018 (1.24)
- OS Version: Windows 10

Steps to Reproduce:
Let's say I have 20 unit tests in a particular project.
1. Setup the unit test run by specifying the unittest framework and unit tests folder.
2. Run the tests by right clicking on a unit test file and click 'Run all unit tests'
3. After the run is complete, the results bar displays how many tests are passed and how many are failed. (e.g. 15 passed, 5 failed).
And I can run/debug individual test because there is a small link on every unit test function for that.
4. If I re-run the tests from same file, then the results bar displays the twice number of tests. (e.g. 30 passed, 10 failed)
And now the links against individual test functions are gone. So I cannot run individual tests.

The only way to be able to run/debug individual tests after this is by re-launching the VS code.

**Comment by weinand** [comment]
Please file against Python extension.
