### ISSUE TITLE
Outline view sort alphabetically

### ISSUE THREAD

**Issue by ghiscoding** [Microsoft/vscode#53560]
I searched issues with label of Outline and couldn't find any open request about a possible way to sort the list alphabetically. I don't always put my functions in alphabetical order in my classes but I really wish there would be a way to show them alphabetically in the Outline view. They seem to be always sorted in VS (by symbol, then alphabetically), so it would be nice to also have this option in VSCode.

**Comment by jrieken** [comment]
Check the overflow menu. There is sort by name.

<img width="336" alt="screen shot 2018-07-05 at 09 15 08" src="https://user-images.githubusercontent.com/1794099/42307797-eea4d670-8033-11e8-85ef-7e9e3e82c473.png">

**Comment by ghiscoding** [comment]
@jrieken 
Thanks I did not even know there was a menu for Outline. 
However, I see that there's only 1 sort possible at a time, so I cannot sort by type **then** by name. 
Could that be a feature request to add in the future?

**Comment by jrieken** [comment]
> so I cannot sort by type then by name. Could that be a feature request to add in the future?

It should be stable, e.g having sorted by name then by kind, then we shouldn't mixup items of equal kind. That's a known bug with the tree.
