### ISSUE TITLE
User-level installed vscode failed to update

### ISSUE THREAD

**Issue by neilsustc** [Microsoft/vscode#53569]
I installed the user-level version of vscode from the v1.25 changelog. It does do not ask for admin permission when installing updates. But if I click "restart to update" from the left bottom gear. It says

```
Failed to install VS Code update. Please download and reinstall VS Code.

Please attach the following log file to a new issue on GitHub:

C:\Users\zhang\AppData\Local\Temp\vscode-inno-updater.log
```

But `C:\Users\zhang\AppData\Local\Temp\vscode-inno-updater.log` doesn't exist.

---

And my vscode information

Version: 1.25.0-insider
Commit: 33ba00346fd1bc889d5adc2f386c64fdb3657e61
Date: 2018-07-03T14:40:32.630Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

**Comment by joaomoreno** [comment]
Can you please double check? That file should definitely be here. I see it in my machine.

**Comment by neilsustc** [comment]
Ok, I find it now... (I thought it was a folder).

<details>
<summary>Log file</summary>
<pre>Jul 05 14:48:47.706 INFO Starting: C:\Users\zhang\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe, false
Jul 05 14:48:47.707 INFO Checking for running Code - Insiders.exe processes... (attempt 1)
Jul 05 14:48:47.710 INFO Code - Insiders.exe is running, wait a bit
Jul 05 14:48:48.210 INFO Checking for running Code - Insiders.exe processes... (attempt 2)
Jul 05 14:48:48.216 INFO Code - Insiders.exe is running, wait a bit
Jul 05 14:48:48.717 INFO Checking for running Code - Insiders.exe processes... (attempt 3)
Jul 05 14:48:48.726 INFO Code - Insiders.exe is not running
Jul 05 14:48:48.726 INFO Checking for possible conflicting running processes... (attempt 1)
Jul 05 14:48:48.734 INFO Inno Updater v0.4.4
Jul 05 14:48:48.734 INFO Starting update, silent = false
Jul 05 14:48:48.761 INFO do_update: "C:\\Users\\zhang\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\Code - Insiders.exe", _
Jul 05 14:48:48.762 INFO move_update: "C:\\Users\\zhang\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\unins000.dat", _
Jul 05 14:48:48.762 INFO Delete: "api-ms-win-core-console-l1-1-0.dll" (attempt 1)
Jul 05 14:48:48.762 INFO Delete: "api-ms-win-core-datetime-l1-1-0.dll" (attempt 1)
Jul 05 14:48:48.762 INFO Delete: "api-ms-win-core-debug-l1-1-0.dll" (attempt 1)
Jul 05 14:48:48.763 INFO Delete: "api-ms-win-core-errorhandling-l1-1-0.dll" (attempt 1)
Jul 05 14:48:48.763 INFO Delete: "api-ms-win-core-file-l1-1-0.dll" (attempt 1)
Jul 05 14:48:48.763 INFO Delete: "api-ms-win-core-file-l1-2-0.dll" (attempt 1)
Jul 05 14:48:48.763 INFO Delete: "api-ms-win-core-file-l2-1-0.dll" (attempt 1)
Jul 05 14:48:48.763 INFO Delete: "api-ms-win-core-handle-l1-1-0.dll" (attempt 1)
Jul 05 14:48:48.763 INFO Delete: "api-ms-win-core-heap-l1-1-0.dll" (attempt 1)
Jul 05 14:48:48.764 INFO Delete: "api-ms-win-core-interlocked-l1-1-0.dll" (attempt 1)
Jul 05 14:48:48.764 INFO Delete: "api-ms-win-core-libraryloader-l1-1-0.dll" (attempt 1)
Jul 05 14:48:48.764 INFO Delete: "api-ms-win-core-localization-l1-2-0.dll" (attempt 1)
Jul 05 14:48:48.764 INFO Delete: "api-ms-win-core-memory-l1-1-0.dll" (attempt 1)
Jul 05 14:48:48.764 INFO Delete: "api-ms-win-core-namedpipe-l1-1-0.dll" (attempt 1)
Jul 05 14:48:48.765 INFO Delete: "api-ms-win-core-processenvironment-l1-1-0.dll" (attempt 1)
Jul 05 14:48:48.765 INFO Delete: "api-ms-win-core-processthreads-l1-1-0.dll" (attempt 1)
Jul 05 14:48:48.765 INFO Delete: "api-ms-win-core-processthreads-l1-1-1.dll" (attempt 1)
Jul 05 14:48:48.765 INFO Delete: "api-ms-win-core-profile-l1-1-0.dll" (attempt 1)
Jul 05 14:48:48.765 INFO Delete: "api-ms-win-core-rtlsupport-l1-1-0.dll" (attempt 1)
Jul 05 14:48:48.765 INFO Delete: "api-ms-win-core-string-l1-1-0.dll" (attempt 1)
Jul 05 14:48:48.766 INFO Delete: "api-ms-win-core-synch-l1-1-0.dll" (attempt 1)
Jul 05 14:48:48.766 INFO Delete: "api-ms-win-core-synch-l1-2-0.dll" (attempt 1)
Jul 05 14:48:48.766 INFO Delete: "api-ms-win-core-sysinfo-l1-1-0.dll" (attempt 1)
Jul 05 14:48:48.766 INFO Delete: "api-ms-win-core-timezone-l1-1-0.dll" (attempt 1)
Jul 05 14:48:48.766 INFO Delete: "api-ms-win-core-util-l1-1-0.dll" (attempt 1)
Jul 05 14:48:48.766 INFO Delete: "api-ms-win-crt-conio-l1-1-0.dll" (attempt 1)
Jul 05 14:48:48.766 INFO Delete: "api-ms-win-crt-convert-l1-1-0.dll" (attempt 1)
Jul 05 14:48:48.767 INFO Delete: "api-ms-win-crt-environment-l1-1-0.dll" (attempt 1)
Jul 05 14:48:48.767 INFO Delete: "api-ms-win-crt-filesystem-l1-1-0.dll" (attempt 1)
Jul 05 14:48:48.767 INFO Delete: "api-ms-win-crt-heap-l1-1-0.dll" (attempt 1)
Jul 05 14:48:48.767 INFO Delete: "api-ms-win-crt-locale-l1-1-0.dll" (attempt 1)
Jul 05 14:48:48.767 INFO Delete: "api-ms-win-crt-math-l1-1-0.dll" (attempt 1)
Jul 05 14:48:48.767 INFO Delete: "api-ms-win-crt-multibyte-l1-1-0.dll" (attempt 1)
Jul 05 14:48:48.767 INFO Delete: "api-ms-win-crt-private-l1-1-0.dll" (attempt 1)
Jul 05 14:48:48.768 INFO Delete: "api-ms-win-crt-process-l1-1-0.dll" (attempt 1)
Jul 05 14:48:48.768 INFO Delete: "api-ms-win-crt-runtime-l1-1-0.dll" (attempt 1)
Jul 05 14:48:48.768 INFO Delete: "api-ms-win-crt-stdio-l1-1-0.dll" (attempt 1)
Jul 05 14:48:48.768 INFO Delete: "api-ms-win-crt-string-l1-1-0.dll" (attempt 1)
Jul 05 14:48:48.768 INFO Delete: "api-ms-win-crt-time-l1-1-0.dll" (attempt 1)
Jul 05 14:48:48.768 INFO Delete: "api-ms-win-crt-utility-l1-1-0.dll" (attempt 1)
Jul 05 14:48:48.769 INFO Delete: "bin" (attempt 1)
Jul 05 14:48:48.769 INFO Delete: "blink_image_resources_200_percent.pak" (attempt 1)
Jul 05 14:48:48.769 INFO Delete: "Code - Insiders.exe" (attempt 1)
Jul 05 14:48:48.820 INFO Delete: "Code - Insiders.exe" (attempt 2)
Jul 05 14:48:49.020 INFO Delete: "Code - Insiders.exe" (attempt 3)
Jul 05 14:48:49.471 INFO Delete: "Code - Insiders.exe" (attempt 4)
Jul 05 14:48:50.271 INFO Delete: "Code - Insiders.exe" (attempt 5)
Jul 05 14:48:51.522 INFO Delete: "Code - Insiders.exe" (attempt 6)
Jul 05 14:48:53.323 INFO Delete: "Code - Insiders.exe" (attempt 7)
Jul 05 14:48:55.773 INFO Delete: "Code - Insiders.exe" (attempt 8)
Jul 05 14:48:58.974 INFO Delete: "Code - Insiders.exe" (attempt 9)
Jul 05 14:49:03.025 INFO Delete: "Code - Insiders.exe" (attempt 10)
Jul 05 14:49:08.025 INFO Delete: "Code - Insiders.exe" (attempt 11)
Jul 05 14:49:08.027 ERRO 另一个程序正在使用此文件，进程无法访问。 (os error 32)</pre>
</details>

The last line says "another program is using this file, cannot access"

**Comment by neilsustc** [comment]
After restarting my computer, it installs now.

But I don't know what program will occupy vscode while installing. This is not the first time I had this issue. I tried user-level version as early as you announced it on twitter. But I had to go back to the normal version because of this issue. I gave it another try recently and again had this issue.

So please feel free to close this since I don't have more useful information. But if you would like to investigate more to address this "vscode occupied" issue, it would be nice. (Maybe tell the user which program is using vscode?)

**Comment by joaomoreno** [comment]
Did you find the log file after all?

**Comment by neilsustc** [comment]
Yes, I wrapped it inside a `<details>` block to save space 😂

![image](https://user-images.githubusercontent.com/7588612/42313314-01fe0a02-8075-11e8-8c0f-f395bf7f73b7.png)

**Comment by joaomoreno** [comment]
Interesting. If it ever happens again, try to find out which program is using the file.
