### ISSUE TITLE
Cannot read property 'identifier' of undefined

### ISSUE THREAD

**Issue by jbsulli** [Microsoft/vscode#5356]
- VSCode Version: 1.0.0
- OS Version: Windows 10 (version 1511, build 10586.218)

Steps to Reproduce:

1. Use Node.js (I'm using 4.4.0 right now)
2. Type "typeof" in a JavaScript file. 

Seems to always pop up when while I'm typing an if statement and haven't added the variable I'm trying to get the typeof. Not a huge issue but results in a VSCode error popping up that I then have to close.

Developer tools shows: 
```
    Cannot read property 'identifier' of undefined
    e.doShow @ workbench.main.js:90
```
Great work on VSCode though! Really enjoying it. :+1:

**Comment by bpasero** [comment]
Debug hover?

**Comment by isidorn** [comment]
@jbsulli are you trying to debug a file? Or you are just editing a file when you get the error?
Can you post the example of the file for which you get this error?

**Comment by jbsulli** [comment]
Just editing the file. I created a new project and it seems to not be happening. I have a pretty large Node.js project that it happens consistently. I'm going to see if I can track down any files or settings that trigger it and get back to you guys.

**Comment by isidorn** [comment]
@jbsulli great, a small reproducable sample would be great

Unassigning myself since it is not debug, but editing.

**Comment by jbsulli** [comment]
Doh... after poking around it looks like I must have originally mistyped the "--disable-extensions" flag as doing it this time fixed the issue. Launched Code again and uninstalled the "jshint" extension and that fixed the issue. So it looks like the issue is with their extension. Sorry for wasting your time.

**Comment by isidorn** [comment]
Np, glad we got to the bottom of the issue.

**Comment by bpasero** [comment]
Cool
