### ISSUE TITLE
Intellisense popups should be much wider

### ISSUE THREAD

**Issue by lonix1** [Microsoft/vscode#53565]
I'm using the latest versions of vscode and the C# extension.

The IntelliSense popups are very narrow, and wrap text. So for many method signatures, that means  the text is broken onto multiple lines, which makes it VERY hard to read, and basically that makes IntelliSense useless.

Please add one or more of the following:
- Add a setting for "wider IntelliSense popups"
- Don't wrap
- Or the best option: allow me to resize the popup horizontally, and automatically remember the width

**Comment by lonix1** [comment]
Sorry unsure how to take screenshots. But it's easy to understand:

The popup shown when I type **the dot**: e.g. `foo.bar.` and I expect to see stuff within `bar`

Also the popup shown when I'm supposed to get IntelliSense for arguments, e.g. when I type **the parenthesis** in `foo.bar.doSomething(` and I expect to see args for `doSomething`

All IntelliSense popups are narrow. During debugging too.

**Comment by ramya-rao-a** [comment]
So you want to be able to have wider widgets for both?

**Comment by lonix1** [comment]
When function signatures are long (often are) then it's hard to see what's going on, because the text wraps. So wider popups, or no wrapping.

Put it this way, because of the wrapping, and narrow popups, it's hard to understand what's going on, so the Intellisense is useless. So I often have to hit `f12` to go to the definition and read it there.

It should be more like Visual Studio proper, where this is done really well.

**Comment by joaomoreno** [comment]
@ramya-rao-a Parameter hints needs a good refresh... It also suffer from the same space constraints.

**Comment by ramya-rao-a** [comment]
In that case, lets use https://github.com/Microsoft/vscode/issues/29126 for the similar discussion for the parameter hints
