### ISSUE TITLE
Moving a file triggers changes in a bunch of unrelated files.

### ISSUE THREAD

**Issue by Glinkis** [Microsoft/vscode#53567]
Whenever I move a single file in my project folder, vscode opens up and triggers a change in a bunch of files under node_modules.
This is super annoying, as I have to revert changes for every single one of those files every time I move one of my own.

<img width="374" alt="screen shot 2018-07-05 at 08 47 44" src="https://user-images.githubusercontent.com/8037927/42306644-20abaecc-8030-11e8-9f17-703466fc08ad.png">

None of the affected files have any relation to the moved file.
I have all of the `update import on move`-settings on `prompt`.

**Comment by mjbvz** [comment]
Please try upgrading your workspace to use `typescript@next` by following [these instructions](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions). Do you still see this issue when using typescript@next?

**Comment by Glinkis** [comment]
The issue seem to be resolved when using `typescript@next`.

**Comment by mjbvz** [comment]
Closing this as fixed in typescript@3.0 (which has been adopted in the current VS Code insiders build and will ship in the july release)
