### ISSUE TITLE
Updated license term dialog should not happen on dev or oss builds

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#5357]
https://github.com/Microsoft/vscode/blob/5b9ec15ce526decc5dd0488339e798f6bcb4ec46/src/vs/workbench/parts/update/electron-browser/update.contribution.ts#L63

Maybe check that env.licenseUrl does not point to https://github.com/Microsoft/vscode/blob/master/LICENSE.txt also?

**Comment by joaomoreno** [comment]
Since this is a one off, from prior to 1.0 to post 1.0, I won't do anything now.
