### ISSUE TITLE
Traduction à revoir

### ISSUE THREAD

**Issue by albu77** [Microsoft/vscode#53575]
Issue Type: <b>Bug</b>

La nouvelle  fonctionalité "Outline" est traduite en "contour"  ce devrait plutôt être  "Explorateur d'objet"  . Je n'ai pas mieux pour le moment ......

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:52:25.282Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz (4 x 2294)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|5.98GB (1.16GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-snippet-pack|aka|0.1.5
project-manager|ale|8.0.0
vscode-custom-css|be5|2.7.1
css-compressor|bes|0.0.2
path-intellisense|chr|1.4.2
open-html-in-browser|cod|0.1.21
vscode-instant-markdown|dba|1.4.1
vscode-great-icons|emm|2.1.36
json-tools|eri|1.0.2
vscode-todo-plus|fab|2.1.4
beautify|Hoo|1.3.2
ftp-simple|hum|0.6.7
typings-autoinstaller|jvi|1.2.0
gitignore|mic|1.0.1
vscode-language-pack-fr|MS-|1.24.3
debugger-for-chrome|msj|4.7.0
live-server-preview|neg|0.1.2
flowmaker|spe|1.2.0

(2 theme extensions excluded)

</details>

**Comment by johnliu2016** [comment]
Sent to linguistic review

**Comment by janbaltus** [comment]
Implemented into Transifex.
Please check directly in xlf or under

https://www.transifex.com/microsoft-oss/vscode-editor/translate/#fr/$/111043208?q=text%3Aoutline

https://www.transifex.com/microsoft-oss/vscode-workbench/translat/#fr/$/142825224?q=text%3Aoutline

**Comment by johnliu2016** [comment]
Thanks @janbaltus
