### ISSUE TITLE
Single/double click for "Open in editor" button in GIT view

### ISSUE THREAD

**Issue by danielrentz** [Microsoft/vscode#53576]
When clicking the "Open in editor" button in the "Changes" file list in GIT view, the file opens in shallow mode (italic file name in tab).

When double clicking the "Open in editor" button, the file should be opened in sticky mode (opening another file should not replace the former in the editor).

**Comment by joaomoreno** [comment]
Actually we changed the default to always open sticky, since it is an explicit action.
