### ISSUE TITLE
Regarding look and feel

### ISSUE THREAD

**Issue by nikinfinity2** [Microsoft/vscode#53572]
Issue Type: <b>Feature Request</b>

As we see other editors with nice look and feel. we want same in visual code with excellent look and feel.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:47:35.732Z)
OS version: Linux x64 4.13.0-43-generic

**Comment by m3alamin** [comment]
Yes, Like atom. Please bring the design of atom editor.

**Comment by TomSputz** [comment]
This needs more info - What's wrong with the look of VS Code? Imo it's very clean and the theming API does a pretty good job of allowing custom colours while staying in a simple design spec

**Comment by misolori** [comment]
@nikinfinity2 can you be more specific and provide a few examples of what you'd like to see?
