### ISSUE TITLE
Explorer doesn't show new files when using NSFW in multi workspace

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#53574]
Seen on macOS

1. Open a two-folder workspace
2. Show the Explorer
3. Create a file

It doesn't appear in the explorer. File deletions appear.

It doesn't repro with single folder and `files.useExperimentalFileWatcher: true`.

**Comment by bpasero** [comment]
Does not repro for me:

![before](https://user-images.githubusercontent.com/900690/42313097-304125b2-8042-11e8-9acc-843c5270bf06.gif)

**Comment by isidorn** [comment]
Does not repro for me.
@joaomoreno are you sure you have the folder open using the correct casing?

**Comment by joaomoreno** [comment]
Yes, I reprod it in dev and Insiders... and many times... tho it doesn't repro now... 🤔

**Comment by isidorn** [comment]
Another issue solved by Pasero - Nikolic team

**Comment by joaomoreno** [comment]
@isidorn When I reproduced it, I was logging file events and they were coming. So this was the explorer not refreshing correctly.

**Comment by isidorn** [comment]
@joaomoreno here's a good place to put a breakpoint in case it happens again
https://github.com/Microsoft/vscode/blob/11c5b9381b8d1db012055201d48cc4d37299afce/src/vs/workbench/parts/files/electron-browser/views/explorerView.ts#L475
