### ISSUE TITLE
Screen reader optimized in top left corner

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#53571]
OS X, insiders

1. Turn on voice over
2. Start vscode insiders -> notice screen reader optimized popup in the top left corner (instead of the bottom right)

I feel like I already filed this issue in the past

![screen shot 2018-07-05 at 09 34 33](https://user-images.githubusercontent.com/1926584/42308726-b1feca8e-8036-11e8-90ae-a61e053dd476.png)

**Comment by alexandrudima** [comment]
Fixed by using a notification instead of custom UI in https://github.com/Microsoft/vscode/commit/1433e180d1ca25fa2a33b900a17b633123120631
