### ISSUE TITLE
Visual Studio Flickers in Windows 10

### ISSUE THREAD

**Issue by adityajk** [Microsoft/vscode#53585]
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
angular-material|1to|0.13.0
html-snippets|abu|0.2.1
ng-template|Ang|0.1.9
path-intellisense|chr|1.4.2
EditorConfig|Edi|0.11.1
tslint|eg2|1.0.32
prettier-vscode|esb|1.3.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
json2ts|Gre|0.0.6
angular2-switcher|inf|0.1.9
Angular2|joh|6.0.0
angular-extension-pack|loi|0.5.3
Angular2Tests|Mar|0.7.3
debugger-for-chrome|msj|4.7.0
ng-fortytwo-vscode-extension|NG-|0.0.9
typescript-hero|rbb|2.3.2
simontest|Sim|0.18.1
autoimport|ste|1.5.3
move-ts|str|1.11.3
Angular2|UVB|0.4.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by TomasHubelbauer** [comment]
Could you attach a video of the flickering? Also the name of the application is Visual Studio Code or VS Code.
