### ISSUE TITLE
I cannot find the search button at left, where is it???

### ISSUE THREAD

**Issue by stevenlii** [Microsoft/vscode#53583]
Issue Type: <b>Bug</b>

I cannot find the search button at left, where is it???

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (2.17GB free)|
|Process Argv|D:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vue-peek|dar|1.0.2
vscode-markdownlint|Dav|0.18.0
vscode-eslint|dba|1.4.12
vscode-npm-script|eg2|0.3.4
prettier-vscode|esb|1.5.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vuejs-extension-pack|mub|1.1.2
vetur|oct|0.12.5
vscode-status-bar-format-toggle|tom|1.4.0
JavaScriptSnippets|xab|1.7.0

</details>

**Comment by jrieken** [comment]
search where? in the editor? in the terminal? in web views? in the extension widget? in the search viewlet?

**Comment by obayit** [comment]
do you mean this?
![vscode issue 53583](https://user-images.githubusercontent.com/20386024/42328517-be587c7a-806e-11e8-8534-96a5c962200b.png)
