### ISSUE TITLE
Terminal error The terminal process terminated with exit code: 4294967295

### ISSUE THREAD

**Issue by CodingArcher** [Microsoft/vscode#53588]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by Tyriar** [comment]
What do you did to produce this error?

**Comment by CodingArcher** [comment]
Hi @Tyriar 
All i did is open up the terminal and it then states to press a key, which i did and then it closes it self and shows me that error

**Comment by Tyriar** [comment]
The error message seems to tell it all. You're probably pointing to bash.exe in your settings file but you don't have it installed. Open the command palette (F1) and run the select default shell command and use cmd or powershell (or install a WSL distro).

**Comment by Tyriar** [comment]
@CodingArcher the message is saying that you haven't installed it inside Windows. Follow the instructions in the message you saw:

Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore

**Comment by Jovani17** [comment]
Modify User Settings in VS Code (File -> Preferences -> User Settings) and add the following within the settings.json pane:

"terminal.integrated.shell.windows": "C:\\WINDOWS\\sysnative\\bash.exe",
 "terminal.integrated.shell.windows": "bash.exe",
