### ISSUE TITLE
VS Code will modify my data in Python script when i debug with it

### ISSUE THREAD

**Issue by sherlockchou86** [Microsoft/vscode#53581]
- VSCode Version: 1.19.3
- OS Version: Windows 10

Steps to Reproduce:
the VS Code IDE will modify my property in Python script when i debug with it. my test code as below
'''
bytesIO = io.BytesIO(...)
bytesIO.seek(0)
print(bytesIO.realine())   # will output the first line
'''

1. Suppose i have a stream-like object in my Python script(such as BytesIO object called 'bytesIO'), call 'byteIO.seek(0)' to set offset to start position.
2.  set breakpoint at the code line 'byteIO.readline()'
3.  use the 'variable monitor' to watch the data inside bytesIO object
4.  press F10 to continue run the code.

result:    print(bytesIO.readline()) output nothing.
expect:  print(bytesIO.readline()) will output the first line.

if i add 'bytesIO.seek(0)' after i watch the variable by vs code ide, the output is right.  I wander if the ide has modified the data inside the bytesIO object, such as it called its iterator and changed the position flag inside the object.

hope it helps!

Does this issue occur when all extensions are disabled?: Yes/No  (i cannot debug with it if i disable the Python extensions, right?)

**Comment by weinand** [comment]
Please file this against the Python extension.
