### ISSUE TITLE
"Toggle Panel" Doesn't Preserve Focus on Line # in Editor

### ISSUE THREAD

**Issue by ahmadawais** [Microsoft/vscode#53580]
- VSCode Version:1.24.1
- OS Version: macOS 10.12.6

## Steps to Reproduce:

1. <kbd>⌘</kbd> + <kbd>J</kbd> to toggle the panel will jump the file open in the editor to the top instead of the line number that was previously in focus.

Does this issue occur when all extensions are disabled?: No

## Screen recording

Look there's a problem with Gulp line # 119 I `ALT` clicked and jumped to that line but when I pressed <kbd>⌘</kbd> + <kbd>J</kbd> to toggle the panel the editor jumped at the top of the file.

→ [Check this screen recording](https://on.ahmda.ws/sjL7)

**Comment by isidorn** [comment]
Can not repro
@ahmadawais do you see this wiht latest vscode insiders https://code.visualstudio.com/insiders/
If yes can you please proivde exact repro steps

**Comment by ahmadawais** [comment]
@isidorn can you check the video link at the end? To see how to reproduce it.

I added a mistake in my `gulpfile.js` below the fold on line 119 — when I <kbd>⌥</kbd> + <kbd>CLICKED</kbd> the link to go to the line and then pressed <kbd>⌘</kbd> + <kbd>J</kbd> to toggle the panel — the Editor jumped at the top of the file (though if I start typing it will start typing from line 119 as the cursor is still there but the view is at the top of the file)

**Comment by isidorn** [comment]
Please try with extensions disbled.
Also I watched the video, and a video is not steps unfortunetly
