### ISSUE TITLE
Align Format behavior across languages

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5358]
- VSCode Version: 1.0.0 alpha
- OS Version: Windows 10 / Ubuntu 15.10

Using format code in Javascript does not remove extra blank lines at the bottom of the file. In other languages format code removes these extra lines.

Steps to Reproduce:
1. Open a Javascript file
2. Add new lines to the end of the file
3. Format code

Try the same with a JSON or HTML file.

What is the expected behavior of using format code with blank lines at the end of the file?

**Comment by jrieken** [comment]
Each and every language decided on formatting rules and how formatting is "done right". While there are some extensions that massage final new lines, formatters are still free to do what they want and it's not the rule of vscode to decided on this.
