### ISSUE TITLE
Node debug: auto attach mode is not remembered

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#53586]
- enable auto attach using the Toggle Auto Attach command
- reload the window

-> the auto attach statusbar item is gone.

I was wondering whether the auto attach mode would not better be a setting, then I can define per workspace when I want to have the feature enabled.

**Comment by weinand** [comment]
The reason why we don't remember this as a setting is because that would require to activate 
the node-debug extensions early.

**Comment by egamma** [comment]
closing as a duplicate of #53640

**Comment by weinand** [comment]
I've reopened this issue to track the fixes for the following problems:
- the auto-attach state is now a setting with 3 values: 'disabled', 'on', 'off'. The value 'disabled' hides it from the status bar.
- if the setting is created via the "Toggle Auto Attach", it will be stored in workspace settings
- restarting remembers the setting's value

**Comment by weinand** [comment]
I've created https://github.com/Microsoft/vscode/issues/54183 to address the issue with the settings API.

**Comment by weinand** [comment]
Verification:

- the auto-attach state is now a setting with 3 values: 'disabled', 'on', 'off'. The value 'disabled' hides it from the status bar.
- if the setting is created via the "Toggle Auto Attach", it will be stored in workspace settings.
- restarting remembers the setting's value.

Verify that
- the auto-attach setting works as described,
- auto-attach setting can be used in user and workspace settings,
- and is persisted across debug sessions.

**Comment by JacksonKearl** [comment]
I'm not able to get auto-attach to work on win10 with node v8.11.2 on latest insiders.

I have index.js:
```
let a = () => setTimeout(() => {
    console.log('ping')
    a();
}, 500);
a();
```

And when I run `node --inspect index.js` in either bash or powershell, the program executes but code does not attach

**Comment by weinand** [comment]
auto-attach failing on Windows issue is unrelated to this issue.
I've created issue #55672 for this.
