### ISSUE TITLE
how do i import other powershell modules and snapins- exchange, scom, lync etc.

### ISSUE THREAD

**Issue by lkowitz** [Microsoft/vscode#5359]
- VSCode Version: 1.0
- OS Version: 2012 R2

Steps to Reproduce:

1. Not sure how to import other snapins like the powershell exchange cmdlets.  i'd like to have intelli sense and the ability to debug these commands.

**Comment by egamma** [comment]
This issue was moved to PowerShell/vscode-powershell#147
