### ISSUE TITLE
can't  not disable Files Exclude Fliter

### ISSUE THREAD

**Issue by ShayCormac1963** [Microsoft/vscode#53599]
![image](https://user-images.githubusercontent.com/19632359/42382650-91f0ab40-8167-11e8-8725-2c930e6edbfe.png)
![image](https://user-images.githubusercontent.com/19632359/42370436-53322870-813f-11e8-8cc6-85b6cd5c9334.png)
Issue Type: <b>Bug</b>

"markers.panel.no.problems.file.exclusions": "由于启用了文件排除筛选器，所有问题均已隐藏。",
"disableFilesExclude": "禁用排除的文件筛选器。",

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17686

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (6.75GB free)|
|Process Argv|E:\Program Files\VSCode-x64-1.23.1\Code.exe|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
read-only-indicator|ale|0.7.0
custom-window-zoom|cra|1.1.4
xml|Dot|2.3.1
gc-excelviewer|Gra|2.1.24
code-eol|jef|0.3.7
vscode-language-pack-zh-hans|MS-|1.24.3
anaconda-extension-pack|ms-|1.0.0
python|ms-|2018.6.0
vscode-yaml|red|0.0.13

(1 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by ShayCormac1963** [comment]
![image](https://user-images.githubusercontent.com/19632359/42370488-740f7d4a-813f-11e8-801d-05e4d042fe7e.png)

**Comment by jrieken** [comment]
@ShayCormac1963 Please file issues in English. Thanks

**Comment by ShayCormac1963** [comment]
![image](https://user-images.githubusercontent.com/19632359/42382670-99d4d700-8167-11e8-97e1-c55d0510632e.png)

**Comment by sandy081** [comment]
Steps to Reproduce:

- Open Problems View
- Toggle Files exclude option in the filter box
- Toggle Problems view

Expected: Files exclude option state is retained
Actual: Files exclude option state is reset.

**Comment by ShayCormac1963** [comment]
![image](https://user-images.githubusercontent.com/19632359/42410622-1b630cbc-821f-11e8-81b8-2d708de76a80.png)
i have never toggle flies exclude fliter and it will randomly Display the above prompts that i can find what happen to my code

**Comment by sandy081** [comment]
@ShayCormac1963 State of the filters are remembered and are retained when the window is reloaded. You will get into above state only if the filter was enabled before. 

If not, can you please provide the steps to reproduce to get into this situation?

**Comment by ShayCormac1963** [comment]
![20180712130042](https://user-images.githubusercontent.com/19632359/42622174-5a887acc-85f2-11e8-8332-93a82910b9ba.png)
maybe its Git extension cause this problem,because its will show an icon when can't not disable Files Exclude Fliter(illustrated above),the icon like "search" Next to the split screen button in the upper right corner The red box I drew out

**Comment by sandy081** [comment]
@ShayCormac1963 Really sorry to say that its hard to understand what is the issue and how is it happening. 

Can you please update to latest insiders and see if you can reproduce it?

**Comment by ShayCormac1963** [comment]
![20180723185240](https://user-images.githubusercontent.com/19632359/43072842-14241832-8eaa-11e8-8775-562e10702cca.png)
what is the meaning about this icon, i found that when the icon appear then the problem appear

**Comment by sandy081** [comment]
@ShayCormac1963 This action opens the diff view if your file has changes.
