### ISSUE TITLE
Add event onBeforeOpenTextDocument

### ISSUE THREAD

**Issue by xmxstudio** [Microsoft/vscode#53595]
I'd like the ability to run some code AFTER a file has been selected to be opened but BEFORE a new tab/active editor is created and the document is rendered.  I want to have the ability to abort the fileopen process determined by my script.

**Comment by jrieken** [comment]
> I want to have the ability to abort the fileopen process determined by my script.

Can you explain your use-case in more detail please? We are very careful with running this *before* user-gesture happens because that enables other to make us appear as slow. So far we only do that with `onWillSaveTextDocument` and with little patience (time budget is 1.5 seconds)

**Comment by xmxstudio** [comment]
I want to be able to get the filename of the user selected file. If it matches a predetermined filename or pattern, simply abort the file loading process. 

Currently I have an extension that I've called StreamSafe. Which basically fires on 
onDidOpenTextDocument.   On my extension load I read in the filenames/patterns from  the $rootfolder/.streamsafe file.   If the filename of the just opened file is in the .streamsafe file, I immediately call   vscode.commands.executeCommand('workbench.action.closeActiveEditor');

This effectively prevents my file from being able to be edited while my plugin is loaded/active.

The problem is that the file gets opened/rendered to view and then closed as soon as its done rendering the editor view.  This delay is unacceptable as you can clearly see the contents of the file. I want to simply disallow the file from ever being presented visually.

**Comment by xmxstudio** [comment]
So if there's an event i can hook into to abort the fileload process after a user has selected a file to open that would be ideal.

**Comment by jrieken** [comment]
> I want to simply disallow the file from ever being presented visually.

But why is that? Why should a user not open nor see a text file?

**Comment by xmxstudio** [comment]
it would be for developers who stream their work. Often there are files you wish to NEVER display on stream. stuff like credentials.js.  dbconfig.json  mydirtysecrets.txt.   I wrote an extension that when OBS is found running on my system it enables STREAMSAFE mode. which blocks access to files found in .streamsafe .. effectively preventing me from OPPS i just opened my clientsecret and smtp password  files on stream! damn gotta change them again!   

thats exactly why a user should be able to not open or see a text file (depending on circumstance)  I'm just asking for an event that fires before a tab/editor gets generated for a file so that I can abort. It makes perfect sense now right?

**Comment by jrieken** [comment]
> It makes perfect sense now right?

Yeah, I understand the use-case but I wonder if that's really good protection. I means a user can always open/read files in other ways and I wonder if something like OS-level-fileaccess-rights are more appropriate. 

The thing is that allowing extensions to prevent us from showing files is a very sharp knife and not everyone might know how to handle it...

**Comment by xmxstudio** [comment]
Yea. Anything can be a sharp knife. I'm just asking for the blunt
onBeforeOpenTextDocument event lol.  Having to change file permissions
could also work... just change file permissions on extension load.. but
that requires maintaining a list of old permissions in order to revert back.
