### ISSUE TITLE
Selecting text and pressing CTRL+SHIFT+F/H should switch OFF regex mode

### ISSUE THREAD

**Issue by Kroc** [Microsoft/vscode#53592]
If you select a piece of text and then do a global search or replace, the regex mode should be switched off (if on). That is, if selecting text in a document, it is *very* unlikely to be a regex that you want to use for searching, rather you want to search for the literal string.

**Comment by roblourens** [comment]
I disagree, I don't think we should make assumptions and flip flags for the user. And I often select a piece of text and use it to build a regex.
