### ISSUE TITLE
Add "sort lines" option

### ISSUE THREAD

**Issue by felixzapata** [Microsoft/vscode#536]
I think it would be very helpful the option to sort alphabetically (desc / asc) the lines you have selected. For example, a `bower.json` file and its packages.

**Comment by eliashdezr** [comment]
I find this very useful too.

**Comment by kasiriveni** [comment]
its is great idea

**Comment by bpasero** [comment]
This can (and should) easily be done via extension.

**Comment by MattiasPernhult** [comment]
I would like to give this a go, I will comment here when I have finished the extension

**Comment by Tyriar** [comment]
I created an extension that does when vscode was open sourced https://marketplace.visualstudio.com/items/Tyriar.sort-lines

The repo is here for issues/PRs https://github.com/Tyriar/vscode-sort-lines

**Comment by felixzapata** [comment]
thanks @Tyriar

**Comment by Tyriar** [comment]
Basic version of this is now in the editor, more sorting options are available in my extension https://marketplace.visualstudio.com/items/Tyriar.sort-lines
