### ISSUE TITLE
Rename 'Open in Command Prompt' to 'Open in Terminal'

### ISSUE THREAD

**Issue by isiah-lloyd** [Microsoft/vscode#53604]
On Windows 10, when you right click a folder/file there is an option to open in command prompt, this may may be confusing for users as it actually opens in the Terminal in VS Code, the expected behavior may be that an actual Command Prompt window would open. It can also be misleading if the user set up WSL as their Terminal.

**Comment by jlbeard84** [comment]
Opened PR #53636 to make this more consistent.
