### ISSUE TITLE
Program fails to update

### ISSUE THREAD

**Issue by aroberge** [Microsoft/vscode#53607]
- VSCode Version:  1.24?  Trying to update to 1.25
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. I simply tried to update and got an error message that it failed, suggesting to open an issue and attach a file (which is hopefully the right one).
2. Sorry, there is no step 2 ... I have to install the new version as the old one is no longer installed.

This is the second time it happens when I try to update VS code.  I believe that a similar issue also happened when I tried to update another program lately. It might be caused by some Windows settings - or perhaps by Malwarebytes and/or CCleaner who are running in the background, doing some monitoring.  Sorry that I cannot be more helpful.  See the file attached.

Does this issue occur when all extensions are disabled?: Yes/No
N/A 

[operation_log.txt](https://github.com/Microsoft/vscode/files/2167888/operation_log.txt)

**Comment by aroberge** [comment]
Sorry, I believe that I might have attached the incorrect file in my report.
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2168156/vscode-inno-updater.log)

**Comment by yezige** [comment]
I have encountered a problem with the update today. There is a folder called '-' under the path.
I modified the extensionAllowedProposedApi of Microsoft VS Code\resources\app\product.json.
This is the update log
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2168778/vscode-inno-updater.log)

**Comment by joaomoreno** [comment]
You seem to have #47841.

Please read this comment if you can provide more detail: https://github.com/Microsoft/vscode/issues/47841#issuecomment-393101777

Please read this one to disable background updates: https://github.com/Microsoft/vscode/issues/47841#issuecomment-395017687

Also read this one to provide feedback on our new user setup: https://github.com/Microsoft/vscode/issues/47841#issuecomment-399941682
