### ISSUE TITLE
Minimap not refreshed on resume after suspend 

### ISSUE THREAD

**Issue by thupalo** [Microsoft/vscode#53601]
- VSCode Version:  1.24.1
- OS Version: Ubuntu 16.04
Minimap of editor content is not refreshed after returning from machine suspend

Steps to Reproduce:

1. Suspend machine
2. Wake-up from suspend

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexandrudima** [comment]
Duplicate of #30292
