### ISSUE TITLE
Provide a configuration property to configure quickOpen sort order

### ISSUE THREAD

**Issue by oleblaesing** [Microsoft/vscode#53608]
When I open the quickOpen menu, the file in my workspace that I'm currently working on is selected by default. To quickly jump between two files, it would be more convenient, if I could have the opportunity to configure the sort order, so I can select the previous focused file by default.

It should then be easy to jump between two files with a fast "CTRL+P and Return".

The configuration property could be some integer describing an offset for the default results.

**Comment by chrmarti** [comment]
You can do this by hitting P a second time without releasing Ctrl in-between.
