### ISSUE TITLE
Returning a object literal CompletionList stalls intellisense

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#5360]
- VSCode Version: 1.0.0
- OS Version: Linux

Steps to Reproduce:
1.  write an extension that implements a CompletionItemProvider
2. In the provider return a CompletionList, but instead of creating it with
`new CompletionList(items)` create a literal that has the same form:
```typescript
		let result: CompletionList = {
			items: items,
			isIncomplete: false
		};
```

All compiles fine, but when invoking, the suggest widget gets stuck on 'Pending'.
No errors in the console.

-> Either allow that object literals that have the shape of a CompletionList can also be passed, or create an error in the extension host when the returned result is neither a CompletionItem[] and not instance of a CompletionList.
Given that the compiler doesn't enforce you to create a CompletionList with the constructor I'm for the first one (The language server also does that).

**Comment by jrieken** [comment]
Well, TypeScript should really give you can compile error cos `CompletionItem` is spec as a class...

**Comment by jrieken** [comment]
In your case it will return [`undefined`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostLanguageFeatures.ts#L515) which we should handle along the way...

**Comment by jrieken** [comment]
@aeschli I don't see how it stalls. I see that in case of the object literal textual completions kick in (or in case of an empty document 'no suggestions' shows). My provider is this

```
    provideCompletionItems(document: TextDocument, position: Position, token: CancellationToken) {
        let items = [
            new CompletionItem('stall?-one'),
            new CompletionItem('stall?-two'),
            new CompletionItem('stall?-three'),
            new CompletionItem('stall?-four'),
        ];
        let result: vscode.CompletionList = {
            items,
            isIncomplete: false
        };
        return result;
    }
}
```

**Comment by jrieken** [comment]
I have files https://github.com/Microsoft/TypeScript/issues/8168 to clarify the TypeScript part of this
