### ISSUE TITLE
No coloring for new CSS properties

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#53606]
- VSCode Version: 1.25.0
- OS Version: macOS

How it looks with new properties added in 1.25.0:

![image](https://user-images.githubusercontent.com/10441177/42341678-8c2e69d4-809c-11e8-8178-744bf0759309.png)

How it looks like with other properties:

![image](https://user-images.githubusercontent.com/10441177/42341720-adae2ee6-809c-11e8-98c5-8fbb1c0ced5d.png)

**Comment by aeschli** [comment]
@octref if this is not related to your fixes we can move this to the css grammar repo.

**Comment by octref** [comment]
https://github.com/atom/language-css/issues/131

I can fix it in my fork first. Seems Atom folks don't have time to review the PRs yet.

**Comment by octref** [comment]
This is fixed now thanks to @goodmind's PR: https://github.com/octref/language-css/pull/1

**Comment by svipben** [comment]
Nice work @octref!
