### ISSUE TITLE
slow intellisense/type checking

### ISSUE THREAD

**Issue by seansfkelley** [Microsoft/vscode#53618]
Issue Type: <b>Bug</b>

Possibly related issues: https://github.com/Microsoft/vscode/issues/51819, https://github.com/Microsoft/vscode/issues/53541

1.24.x appears to have introduced a performance regression for performance in Typescript projects. The type checking process frequently hovers at 100% for several seconds at a time, with a corresponding lack of updates in the UI (red underlines where they don't make sense, out of date type information, Intellisense stating that it's "Loading...").

I switched to the insiders build and disabled all extensions and the issue persists.

This is especially bad when there's a lot of churn, such as changing branches or even when making a quick sequence of edits. Anecdotally, the longer said sequence of edits is the longer the type checker hangs, up to a limit where it appears to catch up (5-10 seconds or so? I haven't timed it). Changes made in one open file are often slow to be reflected in another open file (such as when I change the type of a value).

Is there a way to downgrade to 1.23.x? Both so it works better for me and so I can help verify that it was indeed 1.23 -> 1.24 that caused the problem. What other debugging information would help?

VS Code version: Code - Insiders 1.25.0-insider (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-04T14:06:34.850Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

<details>
<summary><code>code-insiders --status</code></summary>

```
Version:          Code - Insiders 1.25.0-insider (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-04T14:06:34.850Z)
OS Version:       Darwin x64 17.4.0
CPUs:             Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)
Memory (System):  16.00GB (0.18GB free)
Load (avg):       3, 3, 3
VM:               0%
Screen Reader:    no
Process Argv:     /Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron
GPU Status:       2d_canvas:                    enabled
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    enabled
                  rasterization:                enabled
                  video_decode:                 enabled
                  video_encode:                 enabled
                  vpx_decode:                   enabled
                  webgl:                        enabled
                  webgl2:                       enabled

CPU %   Mem MB     PID  Process
    3      131   52530  code-insiders main
    3       98   52531     gpu-process
    7      328   52532     window (SiteService.ts — clues-frontend)
    0       98   52538       extensionHost
   99      344   52542         electron_node electronForkStart.js tsserver.js
    0       49   52554           electron_node typingsInstaller.js tsserver.js typesMap.js
    0       66   52560         electron_node jsonServerMain.js
    0       49   52539       watcherService
    0       49   52571       searchService
    0       82   52540     shared-process
    2       82   52577     window (Process Explorer)

Workspace Stats:
|  Window (SiteService.ts — clues-frontend)
|    Folder (clues-frontend): 268 files
|      File types: js(80) tsx(77) ts(37) scss(33) json(6) yml(3) md(3)
|                  woff2(2) png(2) ico(2)
|      Conf files: tslint.json(2) makefile(1) package.json(1) tsconfig.json(1)
|                  settings.json(1)
```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by matpag** [comment]
@mjbvz I had the same problem, when i disabled all the extensions the problem disappeared on VS Code 1.25.0. 
Btw i didn't installed new extensions from when i was on version 1.23.1 and there were no problems with all the extensions enabled.

**Comment by maritz** [comment]
I am experiencing this with 1.25.0 as well, the problem with finding a cause or validating a fix is that it dosen't instantly happen on starting vscode. It builds up over time where after a couple of hours the typechecker becomes unusably slow and even just typing becomes very unresponsive (takes up to a second sometimes after a few hours of work).

The rest of my system is running completely fine in the meantime. One of 8 virtual cores (4 real cores with HT) is often used 100% by the vscode tsserver for a few seconds after saving a file. But everything else is below 10% usage and RAM is also still available, SWAP completely untouched.

External tsc watchers and webpack builders are continuing to run fine without needing restarts even after days of running.

I have however definitely experienced it with all extensions disabled in the stable 1.25.0. 

Testing the insider builds right now.

**Comment by seansfkelley** [comment]
FWIW I downgraded to 1.23.x and the problem went away. I'll try to reproduce in the next couple days on the latest insiders build but as @maritz has noted it takes a bit to get there as it's not a binary working/broken reproduction but more of a slow climb to sadness.

**Comment by maritz** [comment]
So far so good.

Some unrelated problems, but the slowdowns did not appear for me with the following extensions installed:

- Bracket Pair Colorizer
- Docker
- Document This
- EditorConfig for VS Code
- Gitlens
- markdownlint
- Prettier
- TSLint

I had a much shorter list on 1.25 at one point, so this list should have definitely triggered it imo.

**Comment by seansfkelley** [comment]
Mine was mostly better for a few days until yesterday when the same issues seem to have returned noticeably.

I noticed some more patterns in the behavior: the delay is easiest to trigger when using go-to-definition to go to a file I haven't visited yet (or in some time) and is accompanied by a large jump in memory usage of the `tsserver.js` extension process noted in the original report (sometimes up to ~200mb in a single shot). Memory usage of that process tends to hover at around 1.1gb; unsure if that's normal or not.

I still see other instances of the problem, such as very long wait times for Intellisense to come up with a list of suggestions, but the pattern for those is harder to identify. When that does happen, it tends to stick around for a while, which is to say that a file/workplace in a bad state doesn't seem to get better over time like it might with a simple empty-cache issue.

**Comment by maritz** [comment]
@seansfkelley Did you try insiders or still on 1.25?

**Comment by seansfkelley** [comment]
Oops, sorry; this is 1.26.0-insider `7e992cab07f6d3faf5a137e8ca0d094f8dffeee6`.

**Comment by seansfkelley** [comment]
Here's an example of the types of issues that crop up routinely. I was editing code higher up in the file, which was of course breaking syntax further down in the file. The message is obviously erroneous
but this file never refreshed itself even once the file was again syntactically valid and should have type-checked.

I had time to take both of these screen shots, write this comment and then edit it, before I gave up and ran "Reload window",\* at which point the file (without further edits) was considered valid, as it should be.

Extensions are still disabled; insiders version `d1272ff8edbaa54c81382f82fa2091f63ed3daea`.

\* "Reload project" doesn't ever seem to help.

![image](https://user-images.githubusercontent.com/2101409/42898003-b26eaddc-8a76-11e8-8c88-fc8503e025f1.png)

![image](https://user-images.githubusercontent.com/2101409/42898016-c6ee4e70-8a76-11e8-8dff-b8a0d63d89ab.png)

**Comment by mjbvz** [comment]
Please try collecting the TS Server log:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a folder with a `tsserver.log` file in it

Look through that log file for errors or stack traces. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by seansfkelley** [comment]
FWIW, these performance issues have been slowly tapering off, so I haven't seen cases as egregious as originally cited. I still have no idea what caused the issue in the first place (bad combination of libraries? over-aggressive cache clearing? slow filesystem?) but I've been staying on the insiders build and it's been improving back to the point where it used to be.

If the issue returns, I'll try to collect some useful logs before reopening.
