### ISSUE TITLE
sass autocomplete do not work in vue file

### ISSUE THREAD

**Issue by git-antonyuk** [Microsoft/vscode#53614]
Issue Type: <b>Bug</b>

sass autocomplete do not work in vue file

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (10.51GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.19.1
copy-relative-path|ale|0.0.2
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.59
vscode-eslint|dba|1.4.12
vscode-html-css|ecm|0.2.0
prettier-vscode|esb|1.5.0
beautify|Hoo|1.3.2
vscode-styled-components|jpo|0.0.19
vetur|oct|0.12.5
vscode-icons|rob|7.24.0
sass-indented|rob|1.4.9
vue-vscode-extensionpack|sdr|0.1.2
vue-vscode-snippets|sdr|1.3.0
vscode-status-bar-format-toggle|tom|1.4.0
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.7.0
markdown-all-in-one|yzh|1.5.1

(1 theme extensions excluded)

</details>

**Comment by octref** [comment]
There is no sass Language Server that provides completions.
