### ISSUE TITLE
ALT key doesn't toggle menu bar visibility in fullscreen mode when titleBarStyle is 'custom'

### ISSUE THREAD

**Issue by alisterlf** [Microsoft/vscode#53611]
- VSCode Version: 1.25.0
- OS Version: Microsoft Windows [Version 10.0.16299.431]

Steps to Reproduce:

1. Set `"window.titleBarStyle": "custom"`
2. Restart vscode
3. Press `F11` to enter fullscreen mode
4. Press `ALT` to show menu bar
5. Press `ALT + F` to open the file menu

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
same cause as #52954
