### ISSUE TITLE
Outline view doesn't follow JS code in .vue files

### ISSUE THREAD

**Issue by ffxsam** [Microsoft/vscode#53615]
- VSCode Version: 1.25.0
- OS Version: macOS 10.13.5

Steps to Reproduce:

1. Open a .vue file (single-file component)
2. Move the cursor through methods, etc

The odd thing is, if I click on a method in the outline view, it skips to the appropriate line in the code. But it can't detect where I am if I move the cursor around. The HTML/template portion of the .vue file works as expected.

Does this issue occur when all extensions are disabled?: Yes

![screencap](https://user-images.githubusercontent.com/12532733/42345707-d37d10d8-8065-11e8-8e5c-e811388b0f67.gif)

**Comment by mjbvz** [comment]
Please file this issue against the vue extension
