### ISSUE TITLE
Saving file does not trigger watches in WSL

### ISSUE THREAD

**Issue by brennancheung** [Microsoft/vscode#53621]
Issue Type: <b>Bug</b>

1. Use `create-react-app` to create a new React app within /home/USER/my-project within the Ubuntu WSL on Windows 10.
2. `npm start` to start the dev server in watch mode.
3. Open the folder in VS Code.
4. Change some text in `src/App.js`.
5. Save the file

Actual result:

The file is changed but no watch is trigger.  The browser does not update with the new changes.

Expect result:

The page should change in the browser with the recent changes.

Note:

If I use `vim` inside any WSL shell and edit the file, the changes are picked up instantly.

VS Code does successfully change the file but it seems like whatever event needs to be generated on file changes does not happen.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.74GB (14.14GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.59
vscode-eslint|dba|1.4.12
es7-react-js-snippets|dsz|1.8.3
gitlens|eam|8.4.1
vimL|fal|0.0.3
kubernetes-snippets|ipe|0.1.9
graphql-for-vscode|kum|1.12.0
vscode-language-babel|mgm|0.0.18
python|ms-|2018.6.0
cpptools|ms-|0.17.6
multi-command|ryu|1.2.0
prettier-vscode-space-parenthesis|sch|0.17.101
code-settings-sync|Sha|2.9.2
vim|vsc|0.14.1

(8 theme extensions excluded)

</details>

**Comment by brennancheung** [comment]
This seems like a related issue but apparently it has already been fixed and I'm on a much later version of Windows.  https://github.com/Microsoft/WSL/issues/216

**Comment by brennancheung** [comment]
I'm able to work around this issue using the following steps:

1. `npm run eject`
2. Edit `config/webpackDevServer.config.js`
3. Add `poll: 1000` to `watchOptions`.  (`poll: true` did not seem to work)

Obviously this is not ideal because I need to `eject` and it is polling.

**Comment by bpasero** [comment]
I don't think we can do anything about it, it sounds like an upstream issue with WSL.
