### ISSUE TITLE
Incorrect TextEditor passed by onDidChangeTextEditorSelection

### ISSUE THREAD

**Issue by shardulm94** [Microsoft/vscode#5362]
- VSCode Version: 1.0.0
- OS Version: Windows

Steps to Reproduce:
1. Two files open inside vscode. 
    -  `index.js` (30 lines: cursor on line 30)
    -  `package.json` (23 lines: cursor on line 10)
2. `package.json` is currently open.
3. Now switch to `index.js` and observe the `onDidChangeTextEditorSelection` event which is fired.

Issue:
In the `TextEditorSelectionChangeEvent` argument, the property `selections` refers to selections in the new document (here `index.js`), while the property `textEditor` points to the old document (here `package.json`).
I guess the `textEditor` should also point to the new file. Also note that, even though `textEditor` points to the old document, `textEditor.selections` has selections of the new doc.

![image](https://cloud.githubusercontent.com/assets/6961317/14574471/8299d9e6-0379-11e6-8689-13b6f1421e9f.png)

**Comment by jrieken** [comment]
I trust your screen shot but I have failed to reproduce this. Also the code looks pretty straight forward... @shardulm94 anythings else that would allow me to reproduce this?

**Comment by shardulm94** [comment]
@jrieken 

I created a sample vscode extension to demonstrate the same. I have just added two listeners: `onDidChangeActiveTextEditor` and `onDidChangeTextEditorSelection`.

Steps to reproduce:
1.Have the `30linefile.ts` open with cursor on line 30
2.Have the `10linefile.ts` open with cursor on line 10 (Please ignore all output until this point)
3.Switch from `10linefile.ts` to `30linefile.ts`. Here is the output
```
onDidChangeTextEditorSelection called =>
file: c:\Users\Shardul\Desktop\sample-vscode-extension\test\10linefile.ts
line count: 10 selection: Ln 30, Col 1

onDidChangeTextEditorSelection called =>
file: c:\Users\Shardul\Desktop\sample-vscode-extension\test\30linefile.ts
line count: 30 selection: Ln 30, Col 1

onDidChangeActiveTextEditor called =>
new editor file: c:\Users\Shardul\Desktop\sample-vscode-extension\test\30linefile.ts
```
4.Switch from `30linefile.ts` to `10linefile.ts`. Here is the output
```
onDidChangeTextEditorSelection called =>
file: c:\Users\Shardul\Desktop\sample-vscode-extension\test\30linefile.ts
line count: 30 selection: Ln 10, Col 1

onDidChangeTextEditorSelection called =>
file: c:\Users\Shardul\Desktop\sample-vscode-extension\test\10linefile.ts
line count: 10 selection: Ln 10, Col 1

onDidChangeActiveTextEditor called =>
new editor file: c:\Users\Shardul\Desktop\sample-vscode-extension\test\10linefile.ts
```

As you can see in both the instances, there were **two** `onDidChangeTextEditorSelection` events.
The second one has the correct file and selection, but in the first event the file and selection do not match.

I have uploaded my sample extension to [this repo](https://github.com/shardulm94/sample-vscode-extension). The sample files used above are also included in the `test` folder. Hope this makes sense.

**Comment by alexandrudima** [comment]
@shardulm94 Thank you for the great repro!
