### ISSUE TITLE
Window specific properties for tasks ?

### ISSUE THREAD

**Issue by SheepDomination** [Microsoft/vscode#53625]
What are window specific properties I can use in `tasks.json` ? I can't find much info in the documentation for tasks.

**Comment by SheepDomination** [comment]
Also where are script naturally read for VSCode ?

**Comment by dbaeumer** [comment]
@SheepDomination can you explain what you mean by window specific properties. If you refer to variables you can use in tasks, they are documented here: https://code.visualstudio.com/docs/editor/variables-reference
