### ISSUE TITLE
Custom window titlebar display problem

### ISSUE THREAD

**Issue by Yurunsoft** [Microsoft/vscode#53628]
Issue Type: <b>Bug</b>

my setting:

```json
"workbench.colorTheme": "Solarized Light",
"window.titleBarStyle":"custom",
```

pic:
![default](https://user-images.githubusercontent.com/20104656/42354532-0a6d60a4-80fa-11e8-8e16-1061dc59f3a4.png)

problem:
1. The first item of the menu has a box
2. The Chinese font is abnormal and cannot be seen clearly.

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (3.66GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
vscode-intelephense-client|bme|0.8.8
template-generator-vscode|Den|0.4.1
php-debug|fel|1.12.3
vscode-sshfs|Kel|1.9.2
markdown-shortcuts|mdi|0.8.1
php-namespace-resolver|Meh|1.1.0
vscode-language-pack-zh-hans|MS-|1.25.3
python|ms-|2018.6.0
cpptools|ms-|0.17.6
php-docblocker|nei|1.6.0
vetur|oct|0.12.5
vscode-php-getters-setters|php|1.2.3
view-in-browser|qin|0.0.5
vscode-lowercase|rui|1.0.1
vscode-uppercase|rui|1.0.1
vscode-preview-server|yui|1.0.1
markdown-all-in-one|yzh|1.5.1
html-css-class-completion|Zig|1.17.1

</details>

**Comment by printempw** [comment]
+1

![screenshot](https://i.imgur.com/c5UPYy4.png)

**Comment by Unixeno** [comment]
It also happened in English.
![image](https://user-images.githubusercontent.com/10361897/42417953-219e64a6-82c8-11e8-8f03-50441c1a00f9.png)

This issue seems like a bug in Dark+ Theme, beacause it disappeared after changing to other themes.

**Comment by sbatten** [comment]
This issue has several issues mentioned that already exist elsewhere. I will close as duplicate. See #53672 for issue with font clarity. See #52911 for the focus indicator issue.
