### ISSUE TITLE
Terminal Window Overlapping Explorer

### ISSUE THREAD

**Issue by BondiGeek** [Microsoft/vscode#53629]
Issue Type: <b>Bug</b>

Open up a project with Explorer expanded and enough items to extend all the way to the bottom of the window.

Make sure terminal window is open

It will overlap explorer by about an inch

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (6.23GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
tslint|eg2|1.0.33
vscode-npm-script|eg2|0.3.4
json2ts|Gre|0.0.6
json-to-ts|Mar|1.5.5
mssql|ms-|1.4.0
csharp|ms-|1.15.2
vsliveshare|ms-|0.3.379
debugger-for-chrome|msj|4.7.0

(2 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/51479
