### ISSUE TITLE
Gear icon menu and popup controls dont work

### ISSUE THREAD

**Issue by usmannajib** [microsoft/vscode#53624]
Issue Type: <b>Bug</b>

1. Move sidebar to right
2. Maximize the window
3. Try clicking on the gear icon on bottom right
4. Try clicking on some button on a popu-up at bottom right

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1603 v3 @ 2.80GHz (4 x 2794)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (8.59GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.15.2
debugger-for-chrome|msj|4.7.0
vscode-docker|Pet|0.0.27

</details>

**Comment by RMacfarlane** [comment]
Sorry for the delay in looking at this issue, it's only shown up in our search query just now.

@usmannajib Can you confirm that you still see this issue in the most recent version of VS Code, 1.33? I'm unable to reproduce it
