### ISSUE TITLE
new opened file is in same tab so that old file disappear

### ISSUE THREAD

**Issue by worldwalk** [Microsoft/vscode#53631]
- VSCode Version: 1.24.1
- OS Version: WIN7

Steps to Reproduce:

1.  open fileA
2. then open fileB,  fileB occupy the only tab, so fileA disappear.

is  there way to make new opened file in new tab?  thanks!

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Goe23** [comment]
you can just select more than one file or a hole folder

**Comment by bpasero** [comment]
Follow our docs to resolve this: https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode
