### ISSUE TITLE
无法根据环境变量的path配置, 自动找到python解释器

### ISSUE THREAD

**Issue by chang-shuai** [Microsoft/vscode#53632]
Issue Type: <b>Bug</b>

第一次出现这个问题的情况是我先安装了vscode, 然后配置了python的环境变量. 结果python插件就提示我在path中没有找到python的解释器. 
第二次出现这个问题是我更新了vscode之后, 又出现了这个提示.

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (2.91GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.25.3
python|ms-|2018.6.0
vscode-docker|Pet|0.0.27

</details>

**Comment by jrieken** [comment]
Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
