### ISSUE TITLE
how to add context and reference window like sourceinsight?

### ISSUE THREAD

**Issue by lanmanck** [Microsoft/vscode#53638]
The reason i like sourceinsight is that it has realtime context preview and reference map tree window. If vscode has, i will very happy and change to vscode.

**Comment by jrieken** [comment]
Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
