### ISSUE TITLE
Subword Navigation not work properly for uppercase like HTML_DOCUMENT or HTMLDocument

### ISSUE THREAD

**Issue by johnnytemp** [Microsoft/vscode#53645]
- VSCode Version: 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e)
- OS Version: macOS 10.13.5

Steps to Reproduce:

1. type HTML_DOCUMENT in editor, position cursor to word start
2. do cursorWordPartRight twice will move to H^T^ML_DOCUMENT (which is wrong) instead of HTML^_DOCUMENT^ (expected)
^ <=> cursor stop positions

Note: I also expect ^HTMLDocument to move right-ward to HTML^Document^

**Comment by alexandrudima** [comment]
Fixed by #53470
