### ISSUE TITLE
hide editor scrollbar -- version: 1.25

### ISSUE THREAD

**Issue by janskey** [Microsoft/vscode#53647]
- VSCode Version: 1.25
- OS Version: MacOs

how to hide the editor scrollbar? there is no settings available. i tried the following settings but doesnt work:

    "editor.scrollbar.vertical": "hidden",
    "editor.scrollbar.verticalScrollbarSize": 1,
    "editor.scrollbar.horizontal": "hidden",
    "editor.scrollbar.horizontalScrollbarSize": 1,

**Comment by alexandrudima** [comment]
You can use the following hacky, not supported options:
```
"editor.scrollbar.vertical": "hidden",
"editor.scrollbar.horizontal": "hidden",
```

You must restart VS Code for these hacky, not supported options to work.
