### ISSUE TITLE
Bug in syntax highlighting

### ISSUE THREAD

**Issue by PaVolDev** [Microsoft/vscode#53648]
Issue Type: <b>Bug</b>

Enter code:
asd = "_string";

A string that contains the symbol underscore is highlighted as a number (Pink).
Then, after this the semicolon is highlighted as a code error (Red) and all the code is incorrectly highlighted.

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.15063

![48645648](https://user-images.githubusercontent.com/40880620/42361304-40ccf670-8107-11e8-8a22-9a0c5653fd7e.png)
![48645646](https://user-images.githubusercontent.com/40880620/42361306-45fa5c1e-8107-11e8-91c8-dfccd529aeb1.png)
![48645650](https://user-images.githubusercontent.com/40880620/42361309-4938548a-8107-11e8-98fb-69fdebfc6ac2.png)

The sample code (C#):
```
using System.Collections;
public class GameSettings : MonoBehaviour {
	public string gameMode = "_none";
	public static int scores = 4568;
	public static int kills = 123456;
	public static int allMoney = 123456;
}
```
![5464845](https://user-images.githubusercontent.com/40880620/42515074-57f53f9a-8474-11e8-8083-77f6310acc3c.png)

<details><summary>Extensions (5)</summary>
Extension|Author (truncated)|Version
---|---|---
vs-color-picker|lih|0.7.0
identical-sublime-monokai-csharp-theme-colorizer|max|0.10.0
vscode-language-pack-ru|MS-|1.25.2
csharp|ms-|1.15.2
color-highlight|nau|2.3.0
</details>

**Comment by jrieken** [comment]
In what language does that happen?

**Comment by PaVolDev** [comment]
The programming language is C#

**Comment by ivanvoznyakovsky** [comment]
I got an issue w/ highlighting variable type in typescript

only first typed var is highlighted. the following two are not
<img width="402" alt="screenshot 2018-07-06 14 32 38" src="https://user-images.githubusercontent.com/6418145/42376907-95a90d9c-8129-11e8-9cc9-1c70a6bf0a50.png">

breaking it apart highlights the first two but if you add types to the following vars it's not highlighted
<img width="409" alt="screenshot 2018-07-06 14 36 35" src="https://user-images.githubusercontent.com/6418145/42376992-01c7d346-812a-11e8-97ff-fe06dd5949bb.png">

**Comment by aeschli** [comment]
@PaVolDev Can you paste the sample code?

**Comment by PaVolDev** [comment]
@aeschli,
The sample code (C#):
```
using System.Collections;
public class GameSettings : MonoBehaviour {
	public string gameMode = "_none";
	public static int scores = 4568;
	public static int kills = 123456;
	public static int allMoney = 123456;
}
```
![5464845](https://user-images.githubusercontent.com/40880620/42515074-57f53f9a-8474-11e8-8083-77f6310acc3c.png)

The semicolon is highlighted as a code error (Red) and all the code is incorrectly highlighted

**Comment by PaVolDev** [comment]
It seems I found the problem. 
I have the installed extension "identical-sublime-monokai-csharp-theme-colorizer" v0.10.0.
I disabled this extension and the problem disappeared. 
![5464846](https://user-images.githubusercontent.com/40880620/42516125-cc620e4c-8476-11e8-94c7-2fb452a328ec.png)

**Comment by aeschli** [comment]
Thanks for finding the issue. Looks like this already reported here: https://github.com/Maximetinu/Sublime-Text-Monokai-theme-for-Visual-Studio-Code/issues/1
