### ISSUE TITLE
Markdown: Javascript fenced code block have incorrect highlighting after inline comment

### ISSUE THREAD

**Issue by vinzlee97** [Microsoft/vscode#53641]
Issue Type: <b>Bug</b>

I created a javascript sample code with some comments inside a fenced code block, place it after an ordered / unordered list item and then indent it. Whenever I indent the code block, everything below the comment is highlighted with the comments color. The bug is in the markdown editor; the preview is fine. The GIF below shows the difference before and after indenting.

Steps to Reproduce:
1. create new markdown file
2. create a list (either ordered / unordered)
3. create a js/ts fenced code block with an inline comment and some code right after the comment line
4. place the code block after a list item
5. indent the code block

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.17134

Extensions: none (all disabled)

![record_2018_07_06_10_09_15_95](https://user-images.githubusercontent.com/28251913/42358364-70e74c94-8106-11e8-8494-ec7be8ac68ab.gif)

**Comment by mjbvz** [comment]
Please share the text of the code along with screenshots

**Comment by vinzlee97** [comment]
This is code from the GIF:

```markdown
- Code explanation

    ```javascript
    // these are circle parameters
    let radius = 10 // in metres
    const PI = 3.14

    // these are circle functions
    function circleArea() {
        return PI * Math.pow(radius, 2)
    }

    console.log(circleArea());
    ```
- Another code explanation

    ```python
    # This is an input line
    a = int(input())

    # This is a print line
    print(a)
    ```
```

Javascript code block:

Before indenting:
![before1](https://user-images.githubusercontent.com/28251913/42406836-10fcea30-81da-11e8-9005-100c8795bbaa.JPG)

After indenting:
![after1](https://user-images.githubusercontent.com/28251913/42406838-2267eea0-81da-11e8-808c-582f74531278.JPG)

Python code block:

Before indenting:
![before2](https://user-images.githubusercontent.com/28251913/42406848-3a542e8e-81da-11e8-8f0d-3ac7d4551102.JPG)

After indenting:
![after2](https://user-images.githubusercontent.com/28251913/42406851-438b4c80-81da-11e8-91f9-79ba6822b000.JPG)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/vscode-markdown-tm-grammar#23

**Comment by roblourens** [comment]
![image](https://user-images.githubusercontent.com/323878/44875483-2d797e00-ac53-11e8-8a3a-ebe0551e5f3d.png)

I repro it with the `ms-vscode.typescript-javascript-grammar` extension installed, that seems weird, but it works with extensions disabled.
