### ISSUE TITLE
command 'search.action.focusActiveEditor' not found

### ISSUE THREAD

**Issue by imoby** [Microsoft/vscode#53644]
- VSCode Version: 1.25
- OS Version: MacOs

Steps to Reproduce:

1. Go to a file and attempt to do search that has multiple of same words on page
2. After searching for word, in the hover toolbox hit enter to go to the next iteration
3. Error is thrown that "command 'search.action.focusActiveEditor' not found"

![image](https://user-images.githubusercontent.com/6380855/42360464-9709fcd0-80ae-11e8-863c-d97b21ab3129.png)

Does this issue occur when all extensions are disabled?: No

**Comment by roblourens** [comment]
You probably have a keybinding that references that command.

I removed that command in 1.25 but I should have left the command and only removed the keybinding.

**Comment by roblourens** [comment]
Well, I didn't restore the command right away, and it's been a couple months with no other complaints, so I'll close this.
