### ISSUE TITLE
[Feature Request] Make Syntax and UI Themes Combinable

### ISSUE THREAD

**Issue by NavyAdmiral** [Microsoft/vscode#53651]
Not sure if I titled this correctly, but I often like UI colors offered by theme A and Syntax colors offered by theme B. It's possible to create theme C by manually merging A and B by spending some time in .vscode folder, but it's not the best approach as it will not respect A's and B's updates. In any case, here's how Atom does this:
![image](https://user-images.githubusercontent.com/40662484/42361843-659c1e8c-8101-11e8-9c28-ae523adb9ca2.png)

**Comment by aeschli** [comment]
This was under discussion (see #22443) but we decided for a single theme story for simplicity reasons.
