### ISSUE TITLE
Missing chars in terminal

### ISSUE THREAD

**Issue by lucblom** [Microsoft/vscode#53657]
Issue Type: <b>Bug</b>

1) Open a terminal (ctrl+`). 
2) Type a lot of chars without giving a line-feed (enter).
3) See that chars are missing...

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (8.06GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-github|Kni|0.30.0
python|ms-|2018.6.0
vscode-icons|rob|7.24.0

(3 theme extensions excluded)

</details>

**Comment by lucblom** [comment]
@jrieken 

![tmp](https://user-images.githubusercontent.com/9318177/42364101-4e945f94-80fa-11e8-8ab7-aeeb277c1a08.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/51479
