### ISSUE TITLE
regression: commands invoked from a keybinding get undefined

### ISSUE THREAD

**Issue by liximomo** [Microsoft/vscode#53659]
[This behaviour](https://code.visualstudio.com/updates/v1_24#_default-argument-for-keybinding-command-invocation) in 1.24 gets broken.

It now received undefined.

**Comment by liximomo** [comment]
It receives `null` in 1.24, but now get `undefined`. This makes it no way to distinguish command executed by shortcut from by command palate.

**Comment by liximomo** [comment]
@alexandrudima Can you give me some feedback? This really important for my extension.

**Comment by MarekLew** [comment]
> It receives null in 1.24, but now get undefined. This makes it no way to distinguish commands executed by shortcut from those by command palate.

Keybilding have parameter args. Use  '"args":[null]' to fixed current behavior

**Comment by alexandrudima** [comment]
See #42851 and associated changes. It was not intentional that the keybindings service invokes commands with an empty object, nor with null or whatever. The keybindings service invokes commands with the args argument or without anything.

**Comment by alexandrudima** [comment]
@liximomo What is your use-case that you need to have a command behave differently if invoked from a keybinding or from somewhere else? Do you perhaps have two distinct commands using the same identifier?

**Comment by MarekLew** [comment]
@alexandrudima he have 4 distintct commands using the same identifier. null,undefined, param and params for active file, all files, one file and selected files.

**Comment by liximomo** [comment]
@alexandrudima Why change this behavior without a changelog?

**Comment by alexandrudima** [comment]
I'm sorry about that. I will try to document in our release notes when I change unspecified behaviour in the future.
