### ISSUE TITLE
Document: Port to portable mode

### ISSUE THREAD

**Issue by schlamar** [Microsoft/vscode#53653]
To port from zipped 1.24 to real portable mode 1.25 I

- moved `C:\Users\<username>\AppData\Roaming\Code` to `<VSCode>\data\user-data`
- moved `C:\Users\<username>\.vscode\extensions` to `<VSCode>\data\extensions `

For now, everything seems to be working fine. 

Is this the recommended way to port an existing setup to real portable mode? If yes, you should consider adding this to the [docs](https://code.visualstudio.com/docs/editor/portable).

**Comment by joaomoreno** [comment]
Yes that should do it. Not sure this warrants a docs section. If we get more questions/requests, I'll put it in the docs.

**Comment by eromoe** [comment]
@schlamar 
I can't open vscode after doing that.

**Comment by joaomoreno** [comment]
Reopening for documentation.

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode-docs/pull/1722

**Comment by eromoe** [comment]
@joaomoreno 
I do construct folder like that.  My home PC did work,  but my work PC didn't .  Vscode even don't show up , and there is no error msg .  

They are both win10 x64,  the only different is vscode install in Driver C in my work PC . Which need admin right to copy files into, may be by this ?

**Comment by joaomoreno** [comment]
Portable mode is not supported if you install VS Code. It is only supported if you get the ZIP download.

**Comment by jpresley** [comment]
I have all of that working but I still can't run dotnet commands like dotnet new console without installing the CLI on the host machine. I have downloaded the CLI zip and have it on my drive but when I try to run the commands through the integrated terminal it errors stating that dotnet is not a cmdlet function etc. How do I get the integrated terminal or VS code or OmniSharp or whatever to look at the CLI on the portable drive and not just look for it in the default location on the C: drive?
