### ISSUE TITLE
Shortcut to peek behind parameter hint

### ISSUE THREAD

**Issue by JordanBelford** [Microsoft/vscode#5365]
I find parameter hints useful, but it is frustrating when the hint box obscures the previous lines. 

It would be great to be able to show/hide the hint with a keyboard shortcut, allowing the user to quickly peek behind the box. 

Currently I have to press escape to close the hint, then fumble around with trigger keys to get the hint to show up again.

![tdfqs5ix5n](https://cloud.githubusercontent.com/assets/1946538/14575111/98441db6-0314-11e6-980f-0376ea7ccdb0.gif)

**Comment by csholmq** [comment]
Perhaps partial transparency as long as you don't hover the box? Or simply that the box pops up below the marker, just like the auto complete does.

**Comment by JordanBelford** [comment]
Putting the parameter hint under the marker would solve my problem. It
would have to deal with potentially overlapping the auto complete box.
Maybe it could go to the right of the auto complete box, or auto complete
could go below the parameter hint.

**Comment by egamma** [comment]
There is the `Trigger Parameter Hints` (cmd+shift+space) command you can use to trigger the parameter hint. 
@JordanBelford does this cover your needs?

**Comment by JordanBelford** [comment]
@egamma The trigger parameter hints command is perfect, I must have misspelled it when I searched through the available commands. Thank you.

I added this as a custom keyboard shortcut to allow toggling. I think it would be good to add as an official binding.
```
{
    "key": "shift+cmd+space",
    "command": "closeParameterHints",
    "when": "editorTextFocus && parameterHintsVisible"
} 
```

**Comment by egamma** [comment]
@JordanBelford great 

Closing the issue.
