### ISSUE TITLE
Shortcut problem with the new custom titleBarStyle

### ISSUE THREAD

**Issue by mrahhal** [Microsoft/vscode#53654]
- VSCode Version: 1.25.0
- OS Version: Windows 10

I have very valuable shortcuts assigned to Alt+D (and Alt+A and the likes). When I enable the new custom titleBarStyle, pressing Alt+D now makes the "Debug" menu active without executing the shortcut. This used to work in the native title. Interestingly, Alt+Shift+D still works.

I'm in love with the new custom title, but there's no way I can enable it with this shortcut not working.

**Comment by zurkoxxx** [comment]
try setting:
`"window.enableMenuBarMnemonics": false`

**Comment by mrahhal** [comment]
Thanks! That worked. I myself don't care about the menu's mnemonics so I'll just disable it. But the issue can be resolved in a more appropriate way.

**Comment by monk-time** [comment]
I agree that it would be great to have the ability to re-use menubar shortcuts without disabling `enableMenuBarMnemonics` completely. That's how it works in the current legacy menu: redefined shortcuts execute their actions without opening the menu. But it seems that both actions happens at once with the new menu.

For example:
1. Enable `"window.titleBarStyle": "custom"`.
2. Add `{ "key": "alt+f", "command": "editor.action.selectAll", "when": "textInputFocus" }` to `keybinding.json`.
3. Press `Alt+F`.

What happens: the text gets selected, but the "File" menu also opens and grabs the focus to itself.

Sometimes though it works differently: I use the GitLens extension that assigns a number of very common actions to `Alt+*` shortcuts in its non-default "alt-based" shortcut scheme. When I press `Alt+H` ("Show File History"), the menu opens and closes very briefly before the extension takes over and shows its UI for this action.
