### ISSUE TITLE
"window.titleBarStyle": "custom" on windows cause registered command get "{"isTrusted":true}"

### ISSUE THREAD

**Issue by liximomo** [Microsoft/vscode#53665]
- VSCode Version: 1.25

With `"window.titleBarStyle": "custom"` setting on Windows. The callback pass to registerCommand get called with "{ isTrusted":true }"  as params when select a file in explorer.  It should be an Uri object.

**Comment by sbatten** [comment]
@liximomo this has since been resolved 

see related https://github.com/Microsoft/vscode/issues/56225
