### ISSUE TITLE
Ruby Language detects Puppet manifest as Ruby

### ISSUE THREAD

**Issue by dhollinger** [Microsoft/vscode#5366]
- VSCode Version: 1.0.0
- OS Version: Fedora 23 x86_64

Steps to Reproduce:
1. Install VSCode
2. Install Puppet Extension
3. Open puppet manifest (.pp file)
4. VSCode detects it as a Ruby file type
##### package.json snippet of offending extension:

``` json
            "id": "ruby",
            "extensions": [ ".rb", ".rbx", ".rjs", ".gemspec", ".pp", ".rake" ],

```

The included Ruby language extension has the puppet extension (.pp) in its extensions list and overrides any installed Puppet extension causing Puppet manifest files to always be detected as Ruby files unless a manual override is put into the User Configuration.

**Comment by egamma** [comment]
// CC @alexandrudima

**Comment by shamil** [comment]
Any progress with this?

**Comment by dhollinger** [comment]
@shamil This was fixed back in the July/August release. I should have closed it then, sorry.

See https://github.com/Microsoft/vscode/pull/8637
