### ISSUE TITLE
When use `file -> open new window`, the languang will change to English partly.

### ISSUE THREAD

**Issue by imhuay** [Microsoft/vscode#53663]
Such as "Welcome page" and broadside toll bar are change to English from Chinese.
But the task bar still are Chinese.

The BUG only appear when open a new window using `file -> open new window`. 

It's OK when open a new window with  shortcut

**Comment by dbaeumer** [comment]
@imhuay I tried to reproduce this using VS Code 1.25 with Simplified and Traditional Chinese language packs and I am not seeing the problem.

Can you provide screen cast that demos what you are seeing. Which version of Code are you using?

**Comment by imhuay** [comment]
I have tested on another PC, there's no this problem. I re-install to solve it
