### ISSUE TITLE
Memory consumption issue

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#53661]
Issue originally reported by @amolnw2778 

![image](https://user-images.githubusercontent.com/172399/42365047-aa3ae4aa-80fd-11e8-8426-d05d34ea3895.png)

![image](https://user-images.githubusercontent.com/172399/42365058-b2d15c20-80fd-11e8-8561-d21f87a35728.png)

![image](https://user-images.githubusercontent.com/172399/42365073-bb885698-80fd-11e8-84df-a9ac6f40d3c6.png)

![image](https://user-images.githubusercontent.com/172399/42365086-c6418938-80fd-11e8-8f04-5c1f572b146e.png)

![image](https://user-images.githubusercontent.com/172399/42365101-cffe7cb0-80fd-11e8-9091-dfbd32c76b43.png)

**Comment by jrieken** [comment]
One of the language servers `electron_node server.js` seems to be greedy (554MB)... Its generic name doesn't reveal much and I wonder what kind of files are open

**Comment by egamma** [comment]
From the workspace info this looks like a TS project. The author has the ng-template (angular language service installed) so this would be a possible culprit. There is a memory consumption issue reported against this extension: https://github.com/angular/vscode-ng-language-service/issues/174.
