### ISSUE TITLE
preserve scroll position is broken again

### ISSUE THREAD

**Issue by SailorMax** [Microsoft/vscode#53662]
- VSCode Version: 1.25.0
- OS Version: Windows 10 1803

Looks like preserve scroll position is broken again ( #22995 )

Steps to Reproduce:

1. Help / Release Notes
2. Scroll to the middle of document
3. File / Preferences / Settings
4. switch back to "Release Notes" tab

Expected: middle of document
Actual: begin of document

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Duplicate of #45571
