### ISSUE TITLE
Keybinding for cursorWordPart* collides with moveEditorTo*Group

### ISSUE THREAD

**Issue by JohnArcher** [Microsoft/vscode#53671]
We have written the needed data
Issue Type: <b>Bug</b>

With the introduction of sub word navigation (thanks a lot) after upgrading from 1.24.x to 1.25.0 there is a conflict with the following keybindings:

- `"ctrl+alt+right"` is mapped to `"cursorWordPartRight"` and `"workbench.action.moveEditorToNextGroup"`
- `"ctrl+alt+left"` is mapped to `"cursorWordPartStartLeft"` and `"workbench.action.moveEditorToPreviousGroup"`

I know that the sub word nav commands are also bound to` "when": "textInputFocus"`, but that does not work. While in editor has focus and cursor blinks, if I press `"ctrl+alt+right"` the editor is moved to next group, which is wrong.

Other commands like `"ctrl+right"` (`"cursorWordEndRight"`) works like indented.

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz (8 x 1995)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.95GB (2.66GB free)|
|Process Argv|D:\Programme\Microsoft VS Code\Code.exe H:\miju\Documents\Projekte\Webtool\_dashboard\1.0\qtDashboard.code-workspace|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-caniuse|aga|0.5.0
vscode-icontheme-nomo-dark|be5|1.3.5
vscode-log-viewer|ber|0.5.1
vscode-eslint|dba|1.4.12
tslint|eg2|1.0.33
LogFileHighlighter|emi|2.4.0
vscode-todo-plus|fab|2.1.4
php-debug|fel|1.12.3
php-intellisense|fel|2.3.3
php-pack|fel|1.0.1
JSDocTagComplete|Hoo|0.0.2
phpcs|ika|1.0.5
docthis|joe|0.7.1
svn-scm|joh|1.29.6
format-indent|Kas|1.3.0
csstriggers|kis|0.6.0
php-symbols|lin|2.1.0
rainbow-csv|mec|0.4.2
vscode-todo-parser|min|1.9.1
typescript-javascript-grammar|ms-|0.0.42
debugger-for-chrome|msj|4.7.0
php-docblocker|nei|1.6.0
vscode-paste-and-indent|Rub|0.0.8
todotasks|san|0.5.0
comment-snippets|Tob|0.2.0
vscode-todo-highlight|way|0.5.12
html-css-class-completion|Zig|1.17.1

(2 theme extensions excluded)

</details>

**Comment by dan-blanchard** [comment]
I've actually tried to fix the keybinding conflict and still find that sub-word navigation shortcuts still don't work.

**Comment by sonicdivx** [comment]
I figured out the issue.  Seems the keybindings are applied in order.  I recreated the sub-nav keybindings in the User file and they superseded the Global bindings.  That said, if you want both functions I think you either need to create different mappings or change the global items' "when" condition.  

Unfortunately the VS docs are a bit cryptic, IMHO, on the different focuses. I mean editorFocus,textInputFocus read almost the same

**Comment by alexandrudima** [comment]
I will remove the conflicting keybindings. If you wish to use sub-word navigation, you can define the following in the keybindings.json:

```
{ "key": "ctrl+alt+right",          "command": "cursorWordPartRight",
                                       "when": "textInputFocus" },
{ "key": "ctrl+shift+alt+right",    "command": "cursorWordPartRightSelect",
                                       "when": "textInputFocus" },
{ "key": "ctrl+alt+left",           "command": "cursorWordPartStartLeft",
                                       "when": "textInputFocus" },
{ "key": "ctrl+shift+alt+left",      "command": "cursorWordPartStartLeftSelect",
                                       "when": "textInputFocus" },
{ "key": "ctrl+alt+backspace",       "command": "deleteWordPartLeft",
                                       "when": "textInputFocus && !editorReadonly" },
{ "key": "ctrl+shift+alt+backspace", "command": "deleteWordPartRight",
                                       "when": "textInputFocus && !editorReadonly" },
```

This is also documented in the [release notes](https://code.visualstudio.com/updates/v1_25#_subword-support)

**Comment by iOiurson** [comment]
Default key bindings for `cursorWordStartLeft` (and similar `cursorWordEndRight`, `cursorWordEndRightSelect`, `cursorWordStartLeftSelect`) actually conflict with default for `cursorWordPartLeft` and similar.

`cursorWordStartLeft` and similar should not have `editorTextFocus` default `when` IMHO.

I actually had to change the `keybindings.json` as follows to make it work properly:
```
    {
        "key": "ctrl+alt+left",
        "command": "-cursorWordStartLeft",
        "when": "editorTextFocus"
    },
    {
        "key": "ctrl+alt+right",
        "command": "-cursorWordEndRight",
        "when": "editorTextFocus"
    },
    {
        "key": "ctrl+shift+alt+right",
        "command": "-cursorWordEndRightSelect",
        "when": "editorTextFocus"
    },
    {
        "key": "ctrl+shift+alt+left",
        "command": "-cursorWordStartLeftSelect",
        "when": "editorTextFocus"
    }
```
