### ISSUE TITLE
Autocomplete issue with python

### ISSUE THREAD

**Issue by parkhyosinfan** [Microsoft/vscode#53676]
Problem : My auto-complete function offers partially. Like second picture, it offers words which is what i used. But it doesn't show up all functions like first picture. As you can see in the first picture, i want purple color font and other functions, definitions.
In addition to, my pycharm is showing like first picture. It offers auto-complete perfectly. Is there any relation  with other editors?? 
Also, i installed exetensions python for vs.code, py_dev, python exetension pack, magic_python.

Version : 
-python : 3.52
- VSCode Version: 1.24.1
- OS Version: windows 10

Expected Behavior:  This is not my vs.code. It is my friends screen. 
![1](https://user-images.githubusercontent.com/40885151/42368701-b363b8c8-8142-11e8-9a8a-282b55d6aa27.png)

Actual Behavior: It is my real screen. It just only shows words which is used to or basic functions. 
<img width="386" alt="default" src="https://user-images.githubusercontent.com/40885151/42368613-766d3a52-8142-11e8-880d-c838cc67c4a7.png">

Steps to Reproduce:
n/a

**Comment by jrieken** [comment]
Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
