### ISSUE TITLE
Group source and header in open editor tabs

### ISSUE THREAD

**Issue by JMasak** [Microsoft/vscode#53687]
Issue Type: <b>Feature Request</b>

Hello,

when editing C++ projects most times i have the implementation and header file for the classes (i am currently editing) open at the same time. I like to have the editor tabs grouped so that the header is next to the implementation file (xx.cpp | xx.h | xy.cpp | xy.h ...).

Is it possible if a new tab is openend that it is moved automatically right beside the one with the same name (except for the file extension)? And e.g. if i Ctrl+Click on a Symbol in xy.cpp the file where the symbol is declared will be opened to the right, could this be changed so that the new editor tab would be opened at the right edge of all opened editors or to the right of the "Group" of implementation and header?

Best regards,
Jan Masak

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 6.1.7601

**Comment by isidorn** [comment]
This should be done by the C++ extension, please file it there as a feature request. Thanks
