### ISSUE TITLE
Update import paths on folder rename feature doesn't work

### ISSUE THREAD

**Issue by RonanQuigley** [Microsoft/vscode#53682]
- VSCode Version: 1.25.0
- OS Version: Windows 10
- Typescript: 2.9.2 - Also reproduced with latest typescript@next

Steps to Reproduce:

Your release notes shows folder renaming for path updates as a feature, but it doesn't seem to be working

You can see that file movements work, but folder renames don't in the following gif:

![gif](https://user-images.githubusercontent.com/33596237/42370764-868f5178-8105-11e8-88b2-ce101e6c4e00.gif)

The same example works fine in insiders.

Does this issue occur when all extensions are disabled?: Yes

Logs:
[tsserver-log-igQSBz.zip](https://github.com/Microsoft/vscode/files/2169830/tsserver-log-igQSBz.zip)

This was brought up in and may be related to #53439

**Comment by mjbvz** [comment]
Please test this in tomorrow's VS Code insiders build. I believe this has been fixed
