### ISSUE TITLE
Auto Show/Hide Activity Bar by hovering over the Activity bar area.

### ISSUE THREAD

**Issue by iyashpal** [Microsoft/vscode#53689]
I already know that there is an option to set a shortcut key to show/hide the **Activity Bar**. But it would be great if there is the option to auto show and hide the **Activity Bar** by just hovering over the **Activity Bar** area instead of pressing the shortcut key. I always dream to see the **VS Code** better than the **Atom Editor**. That's why I always wait for the next update to get the better **VS Code Editor**. The last update is very impressive. I loved it.

Thank you for giving us such a great editor ever.

**Comment by isidorn** [comment]
And a bit of a duplicate of auto hide sidebar

**Comment by martin-braun** [comment]
> And a bit of a duplicate of auto hide sidebar

@isidorn I get what you mean. Although, I managed to [auto hide using an extension](https://marketplace.visualstudio.com/items?itemName=sirmspencer.vscode-autohide), but this will force me to click the icon or use the hotkey to show it, again.

**Comment by AmelianceSkyMusic** [comment]
Any updates in 2023?

**Comment by HugoSbl** [comment]
any update in 2024..... ?

**Comment by pookdeveloper** [comment]
I need the same feature here! :)

**Comment by anchan42** [comment]
Any update on 2026?

**Comment by marcospgp** [comment]
can't believe we don't have this option yet, and there's not even a third party solution :(
