### ISSUE TITLE
[themes] `keywords` token customization should not include arrow (=>)

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#53688]
- VSCode Version: 1.25.0
- OS Version: macOS

```
  "editor.tokenColorCustomizations": {
    "keywords": {
      "fontStyle": "italic",
    }
  },
```

It shouldn't `italic` arrow (`=>`).

![arrw](https://user-images.githubusercontent.com/10441177/42373210-ee5d6b5c-811c-11e8-9a44-8c4153f3e893.png)

**Comment by mjbvz** [comment]
@aeschli Looks like `tokenGroupToScopesMap` includes `'storage.type'`.

**Comment by svipben** [comment]
@mjbvz Maybe it's possible to exclude `storage.type.function.arrow` like `keyword - keyword.operator` here https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/themes/electron-browser/colorThemeData.ts#L30?

`storage.type` is necessary for keywords like `const`, `let`, etc. so better is to keep it.

**Comment by aeschli** [comment]
If you want to give the arrow a different look, use this:
```
    "editor.tokenColorCustomizations": {
        "keywords": {
            "foreground": "#ff00ff",
            "fontStyle": "italic"
        },
        "textMateRules": [
            {
                "scope": "storage.type.function.arrow",
                "settings": {
                    "foreground": "#ff0000",
                    "fontStyle": ""
                }
            }
        ]
    }
```

![image](https://user-images.githubusercontent.com/6461412/45589936-ad2f6a00-b92e-11e8-8458-b331c87a1121.png)

`storage.type.fuction` is used for the `function` keyword. By using`storage.type.fuction.arrow` the textmate grammar puts the arrow in the same category as `function`. 

I see this as a decition of the grammar and I don't think we should override that by having a special rule saying the arrow is an 'operator'. Also in our default themes the arrow is rendered as a keyword, and I'm not aware of any compaints. So I'd rather keep things as they are, especially as it customizable in the settings (and in themes)
