### ISSUE TITLE
Long strings in Debug Console not wrapping

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5368]
- VSCode Version: 1.0.0 alpha
- OS Version: Windows 10 / Ubuntu 15.10

Steps to Reproduce:

1. Create a long output string to the console
2. Debug

Actual:
![selection_008](https://cloud.githubusercontent.com/assets/12900364/14576811/96aa13ea-0321-11e6-846e-7b7f88edcbc9.png)

![selection_009](https://cloud.githubusercontent.com/assets/12900364/14576813/9c9061ba-0321-11e6-8979-01ccf6c7acc3.png)

They are wrapping correctly in release 1.0.0.

**Comment by isidorn** [comment]
Nice catch, this has happened because we updated to a new chrome version which handled white-space css property differently in this case.

**Comment by isidorn** [comment]
I will now assign this bug back to you, the vscode version from tuesday will have the fix and then you can verify it by adding the `verified` tag if it looks good.
More about our verification process can be found [here](https://github.com/Microsoft/vscode/blob/master/wiki/project-management/issue-tracking.md#verification)
