### ISSUE TITLE
"Open active file in new window" halts everything on Linux.

### ISSUE THREAD

**Issue by dsanz006** [Microsoft/vscode#53684]
Whenever I am working on a file and I want to open it on a new window, I press Ctrl+K O, which triggers the "open active file in new window". Before this was working perfectly, but now it halts my computer completely. It seems that the RAM fills up completely: before doing Ctrl+K O, I had many programs open: google chrome, thunderbird, spotify, xterm and VSCode. My RAM was over 2 GB out of 8 GB. After doing Ctrl+K O, the RAM went up to 8 GB, so everything halted.

This is a strange bug because it was not happening before (not sure since when it's happening). Moreover, it doesn't happen if I open a new window doing Ctrl+Shft+N, for example: that works perfectly fine (the RAM went up just around 500 MB, I guess that's normal).

 

- VSCode Version: Version: 1.25.0
- OS Version: Ubuntu 16.04.4 LTS.

Steps to Reproduce:

1.Open a workspace and press Ctrl+K O.

Does this issue occur when all extensions are disabled?: No

Update: the bug could be caused by the C/C++ extension. I reinstalled it and did not get problems for some time, but now it is happening again.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by dsanz006** [comment]
Thank you, the bug has disappeared with the insiders build. Everything works as expected, even with the C/C++ Extension.
