### ISSUE TITLE
"update path on file move" refactoring not working for JavaScript

### ISSUE THREAD

**Issue by g3offrey** [Microsoft/vscode#53681]
Hi folks 👋 

First of all thank you for your hard work. Each month I'm amazed how Code is becoming an unique awesome piece of software 😄 

I'm opening a ticket because I encounter an issue with "_update path on file move_" refactoring.

Here's are information about it : 

- VSCode Version: 1.25.0
- OS Version: MacOS 10.13.4

Steps to Reproduce:

1. clone https://github.com/g3offrey/example-node-repository
2. try to move file from folder1 to another folder or to the root
3. check if the require path in index.js is updated

Does this issue occur when all extensions are disabled?: Yes

If I can do something to help, don't hesitate to ask me.
Thank you 👍

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#25493
