### ISSUE TITLE
Hover glitch

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#53690]
- VSCode Version: 1.25.0
- OS Version: macOS

![glitch](https://user-images.githubusercontent.com/10441177/42373523-cc5022c4-811d-11e8-8568-b78b8ba350ad.gif)

**Comment by jrieken** [comment]
Doesn't reproduce for me. Please try to distill what could cause this. E.g. try a different theme, a different symbol etc

**Comment by svipben** [comment]
@jrieken restarted VS Code and everything is fine. Weird, but seems it's good now 😄
