### ISSUE TITLE
Vertical Split tabs: squeeze tab by click in editor not expanding

### ISSUE THREAD

**Issue by safoorsafdar** [Microsoft/vscode#53693]
I have no idea how to explain this issue, but this were working before 1.25.0, but I will try.

have open the two tabs in single window and both are vertical splitted. 
Second tab are expanded to 
left to get full view, and first tab display almost 10 % of the two tabs. 
When click on first tab editor its automatically expand and squeeze to the right side. 
So in other words, any tab currently squeeze in by clicking in editor expand not working.

![not-expanding](https://user-images.githubusercontent.com/5680768/42375263-74fbfa04-8134-11e8-90de-75966c645e03.PNG)

**Comment by bpasero** [comment]
You likely miss https://github.com/Microsoft/vscode/issues/51614
