### ISSUE TITLE
Failed to load icon resource from disk

### ISSUE THREAD

**Issue by zhaoyi0113** [Microsoft/vscode#53698]
I am building a vscode extention and try to load icon file from project. My source code structure is:
```
    PROJECT_ROOT/src/index.js
    PROJECT_ROOT/resources/file.svg
```
I want to load the `file.svg` as a resource to show on a tree item. In the `index.js` I use below code to load the resource:
```
    const resource = Uri.parse('file:../resources/database.png')
    // return the tree item
    return {resourceUri: resource}
```
the tree item will render the file name rather than the actual icon file. How can I load the resource from a relative path?

**Comment by jrieken** [comment]
Use [`ExtensionContext#asAbsolutePath`](https://github.com/Microsoft/vscode/blob/b0ef947992f10643e5d8f3e854adaaa3c6865681/src/vs/vscode.d.ts#L4428)

**Comment by zhaoyi0113** [comment]
@jrieken  I have tried below code but doesn't seem to work:

```
Uri.parse(context.asAbsolutePath('../resources/database.png'))
```

**Comment by zhaoyi0113** [comment]
I tried this code but it doesn't show icon instead it shows file name.

```
resourceUri: Uri.file(context.asAbsolutePath('../resources/database.png'))
```

**Comment by zhaoyi0113** [comment]
@jrieken  Could you let me know whether I did anything wrong with the Uri.file? I still couldn't get the right icon shown on my tree view item. Thanks.

**Comment by jrieken** [comment]
cc @sandy081

**Comment by sandy081** [comment]
@zhaoyi0113 Please check our [sample](https://github.com/Microsoft/vscode-extension-samples/blob/master/tree-view-sample/src/nodeDependencies.ts)
