### ISSUE TITLE
Open folder in new vs code instance by right clicking on the folder

### ISSUE THREAD

**Issue by mittalyashu** [Microsoft/vscode#53692]
I have open two folders inside a VS Code instance.

For example (folder name): A and B

I want to open the folder B in a new instance of VS Code, but there is no option to open by right-clicking on the folder.

![image](https://user-images.githubusercontent.com/29014463/42374975-a356edf2-8137-11e8-8ffd-0f740b63e27e.png)

Even Atom has the option to open the folder in a new instance.

![image](https://user-images.githubusercontent.com/29014463/42374990-bea5dece-8137-11e8-8f7d-b73c8aa3f42f.png)

**Source:** [Stackoverflow](https://stackoverflow.com/questions/51151953/how-to-open-folder-in-new-vs-code-instance-by-right-clicking-on-the-folder)

**Comment by jrieken** [comment]
You can this extension for that: https://marketplace.visualstudio.com/items?itemName=chrisdias.vscode-opennewinstance

**Comment by mittalyashu** [comment]
Instead of installing an extension for a small thing, can you add directly inside VS Code?

**Comment by mittalyashu** [comment]
I have installed the plugin and this is not what I want expecting or trying to saw.

What I want the option to be added inside this menu.

![image](https://user-images.githubusercontent.com/29014463/42777005-6d6063b4-8956-11e8-8dc8-11b5c4ed299d.png)
