### ISSUE TITLE
How to format the document after call `vscode.window.showTextDocument`

### ISSUE THREAD

**Issue by zhaoyi0113** [Microsoft/vscode#53697]
I am building a vs code extension. Below is my code to open an untitled file with a JSON text.
```
        .then(stats => {
            return vscode.workspace.openTextDocument({ content: JSON.stringify(stats), language: 'json' });
        })
        .then((document) => {
            return vscode.window.showTextDocument(document, 1, false);
        })
```
The text shown in the editor is very ugly. I wonder how I can format the opened document on the editor? I know that vscode support formatting json data by default so I am looking for an API to do format automatically.

**Comment by jrieken** [comment]
You can run `executeCommand('editor.action.formatDocument')` which is the same as selecting "Format Document" from the UI. It will then format the active editor.

**Comment by zhaoyi0113** [comment]
@jrieken  Thanks for your response. I tried this command and it shows the unformatted text first then format it after 2 or 3 seconds. Is there a way to show the formated result when open it?
