### ISSUE TITLE
[Zen Mode] tabs bar regression

### ISSUE THREAD

**Issue by Ky6uk** [Microsoft/vscode#53694]
Issue Type: <b>Bug</b>

After upgrading VSCode from `v1.24` to `v1.25` tabs bar is looking as short as the editing place does in zen mode.

![screen shot 2018-07-06 at 13 48 59](https://user-images.githubusercontent.com/46930/42375439-3617d200-8124-11e8-977c-baf156a96f83.png)

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:02:28.333Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz (4 x 1300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_6407708|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.4
Bookmarks|ale|0.19.1
project-manager|ale|8.0.0
vscode-color|ans|0.4.5
snapshot-tools|asv|0.0.7
vscode-eslint|dba|1.4.12
gitlens|eam|8.4.1
tslint|eg2|1.0.33
beautify|Hoo|1.3.2
vscode-styled-components|jpo|0.0.19
typescript-duck-snippet|Ky6|1.0.0
atom-keybindings|ms-|3.0.4
vscode-icons|rob|7.24.0
code-settings-sync|Sha|2.9.2
stylelint|shi|0.37.0
language-stylus|sys|1.9.2

(1 theme extensions excluded)

</details>

**Comment by AlexEne** [comment]
Is there an workaround for this issue?

**Comment by AlexEne** [comment]
Just in case anyone needs a workaround, setting this _fixes_ the issue: ```"zenMode.centerLayout": false,```

**Comment by isidorn** [comment]
This is as designed. Workaround is as already specified `"zenMode.centerLayout": false`

**Comment by Ky6uk** [comment]
@isidorn that workaround doesn't help me. I have toggle that option to `false` and just nothing happens afterwards. Do we have a way to do only the editing place on the center and tab bars on the full width (as it was before)?

**Comment by isidorn** [comment]
F1 > toggle centered editor layout

**Comment by Ky6uk** [comment]
@isidorn that also doesn't help.

`"zenMode.hideTabs": false` + `Toggle Centered Layout`:

![screen shot 2018-07-16 at 17 55 14](https://user-images.githubusercontent.com/46930/42765785-717c9df8-8921-11e8-886d-41413b42ce15.png)

`Toggle Centered Layout` again:

![screen shot 2018-07-16 at 17 55 44](https://user-images.githubusercontent.com/46930/42765823-87ba15f0-8921-11e8-9de1-6b0252074a28.png)

So It just toggles both top bar and the editing place in the same time.

**Comment by AlexEne** [comment]
I don't understand how this is by design. Centered layout would take advantage of the full width as you opened more tabs. 

Now it doesn't and leaves big gaps on both sides of the screen.

**Comment by Ky6uk** [comment]
@AlexEne Is that workaround above help you? I'm using VSCode  for a long time and only in Zen-mode and `v1.25` just breaks that behaviour. Workaround doesn't help me.

**Comment by isidorn** [comment]
@Ky6uk having the editor area centered and the tab bar not centered is no longer supported. And we will not support this due to the grid work which we did last milestone. Sorry for not being more clear in my previous comment.

**Comment by AlexEne** [comment]
Yes it is working in the sense that i can use the full screen width, but of course if I have only one tab I see it centered on the left and occupying the full screen width in zen mode.

**Comment by isidorn** [comment]
Here's an issue where you can vote up / express your concerns 
https://github.com/Microsoft/vscode/issues/53989
