### ISSUE TITLE
Debugging the same project in multiple instances of Code produces unhandled error

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5369]
- VSCode Version: 1.0.0-alpha and 1.0.0
- OS Version: Windows 10 / Ubuntu 15.10

In most cases users will not hit this issue since it is not possible to open the same folder in multiple instances. But it is reproducible if you open the parent folder in Code and create another launch config.

Steps to Reproduce:

1. Open 2 instances of Code (either alpha and release or insiders and release) with the same folder
It is also possible to open the parent of the project folder and point the launch to the same program.
2. Start debugging in one instance.
3. Start debugging the other.

Actual:
Code will hit an unhandled error event
![selection_010](https://cloud.githubusercontent.com/assets/12900364/14576990/21fd6acc-0323-11e6-90fb-9e76e3b71e4c.png)

**Comment by weinand** [comment]
@vsccarl this setup should work just fine. It is our recommended setup for debugging both sides of client and server type programs. So something must be broken in your setup.

What are the details of the error?
What is the exact setup? If possible include zipped project including launch configs.

**Comment by vsccarl** [comment]
Here's the error that it produces: ![multipledebugerror](https://cloud.githubusercontent.com/assets/12900364/14684522/323dda6e-06e5-11e6-844f-7a7aaadaa299.PNG)

The project is [node-js-sample](https://github.com/heroku/node-js-sample)

**Comment by weinand** [comment]
@vsccarl the `EADDRINUSE` is an indication that your code tries to serve the same port '5000' more than once. Please use a different port for the second program.
This is not a VS Code problem.
