### ISSUE TITLE
resolveTask() never gets called (also not for tasks.json tasks)

### ISSUE THREAD

**Issue by WebFreak001** [Microsoft/vscode#53691]
- VSCode Version: 1.24.1
- OS Version: `Linux archlinux 4.17.3-1-ARCH #1 SMP PREEMPT Tue Jun 26 04:42:36 UTC 2018 x86_64 GNU/Linux`

Steps to Reproduce:

1. Create new extension (engine: 1.24.0), code:

```ts
'use strict';
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
	context.subscriptions.push(vscode.tasks.registerTaskProvider("test1", new DubProvider()));
}

class DubProvider implements vscode.TaskProvider {
	provideTasks(token?: vscode.CancellationToken): vscode.ProviderResult<vscode.Task[]> {
		return undefined;
	}

	resolveTask(task: vscode.Task, token?: vscode.CancellationToken): vscode.ProviderResult<vscode.Task> {
		console.log(task);
		task.execution = new vscode.ProcessExecution("echo", [task.definition.arch]);
		return task;
	}
}

// this method is called when your extension is deactivated
export function deactivate() {
}
```

Add this to the contributes block in package.json:
```json
        "taskDefinitions": [
            {
                "type": "test1",
                "properties": {
                    "arch": {
                        "type": "string",
                        "description": "Arch type to run"
                    }
                }
            }
        ]
```

2. Launch extension

3. Create tasks.json with this content:
```js
{
	// See https://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "2.0.0",
	"tasks": [
		{
			"type": "test1",
			"arch": "test"
		}
	]
}
```

4. Do ctrl-shift-B to trigger the Run Task dialog, see that Tasks opens and writes this error:
```
Error: The test1 task detection didn't contribute a task for the following configuration:
{
    "type": "test1",
    "arch": "test"
}
The task will be ignored.
```

5. Try placing a breakpoint inside the `resolveTask` method and observe that it is never called.

Does this issue occur when all extensions are disabled?: n/a

This bug is similar to #33523, but not the same, as that bug describes that it isn't called for the tasks provided with provideTasks, but this bug describes that the valid task configs inside tasks.json are never passed to the extension.

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/33523
