### ISSUE TITLE
1.26 Insider: Terminal selection scrolls up and down with the terminal itself

### ISSUE THREAD

**Issue by MeikTranel** [Microsoft/vscode#53705]
Issue Type: <b>Bug</b>

When scrolling up and down the terminal any selection made before is lost, because the selection seems to registered around the buffer of the rendered terminal and not the actual terminal buffer.

![2018-07-06_14-07-50](https://user-images.githubusercontent.com/6466560/42378274-09325f8c-8127-11e8-9751-c8ec083067db.gif)

This issue is only reproducible in the current Insider version. For reference, this is what behavior the user expects:

![2018-07-06_14-20-44](https://user-images.githubusercontent.com/6466560/42378604-20c09faa-8128-11e8-8fbc-6febc7141d2e.gif)

This is a freshly downloaded VSCode downloaded via chocolatey install vscode.

VS Code version: Code - Insiders 1.26.0-insider (bd953248ad6a8e2f8896bfb78b3ae40e0fd47426, 2018-07-06T05:17:37.386Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3504)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (6.26GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.18.0
docs-article-templates|doc|0.1.2
docs-authoring-pack|doc|0.1.1
docs-markdown|doc|0.1.1
docs-preview|doc|0.3.12
xml|Dot|2.3.1
gitlens|eam|8.4.1
beautify|Hoo|1.3.2
csharp|ms-|1.15.2
PowerShell|ms-|1.7.0
vscode-docker|Pet|0.0.27
vscode-yaml|red|0.0.13
vscode-icons|rob|7.24.0
code-spell-checker|str|1.6.10
msbuild-project-tools|tin|0.2.39

</details>

**Comment by Tyriar** [comment]
Whoa, that's bad o.0 It was probably related to column selection which just got pulled in (alt+click). Looking into it now.

**Comment by MeikTranel** [comment]
Will verify asap ;)

**Comment by MeikTranel** [comment]
Is deployment currently disabled?

**Comment by Tyriar** [comment]
@MeikTranel it's a "nightly" build which builds Monday-Friday Zurich morning. This time was chosen so we can react if there is a major issue with the build.

**Comment by MeikTranel** [comment]
oh. huh so the checkmarks are just merge check builds that deploy nothing?

**Comment by Tyriar** [comment]
Yeah. Deploying on every commit wouldn't be feasible; people would have to update constantly and release builds also take 30-60 minutes to build.

**Comment by MeikTranel** [comment]
but... but... why am i getting all these 💄 refactoring commit updates ? 😺

**Comment by Tyriar** [comment]
Exactly 😛 

We actually had complaints in the past about *too many* updates on Windows. Since then we've made it less annoying to update on Windows 😃

**Comment by MeikTranel** [comment]
i can verify this is fixed now.
