### ISSUE TITLE
Visual Studio Code spawns thousands of processes and makes the system shutdown

### ISSUE THREAD

**Issue by albjerto** [Microsoft/vscode#53700]
VSCode starts spawning thousands of processes making the system freeze. Here's a screenshot with the number of processes opened after a minute or so of non-stop spawning. The forkbomb goes on until the system eventually shuts itself down.

VERSION: 1.25.0
OS Version: 1709 (OS Build 16299.492)

Steps to reproduce:
1. Open VSCode
2. The issue seems to be presenting itself after around 5-10 minutes of Visual Studio Code being opened

Note: I updated VSCode to the version written above just today. The issue started appearing after said update.

![image](https://user-images.githubusercontent.com/21308294/42376952-665fc5c4-8121-11e8-90fc-54c47f5156b2.png)

**Comment by jrieken** [comment]
That should not happen... Can you follow this guide https://github.com/Microsoft/vscode/wiki/Performance-Issues#visual-studio-code-is-consuming-a-lot-of-cpu esp ` Help>Open Process Explorer`. That will tell us what process this is

**Comment by albjerto** [comment]
@jrieken here's the Process Explorer output with Extensions Enabled. I am currently running a test with the Extensions Disabled.

![vscode_processeswithextensions](https://user-images.githubusercontent.com/21308294/42379227-548e1888-812a-11e8-929f-ea75137b565f.png)

**Comment by jrieken** [comment]
@dbaeumer Those seem to be launched from the eslint-server. @albjerto does that match your usage pattern? do you work on JS files or have them in your project?

**Comment by dbaeumer** [comment]
@albjerto to avoid this for now you can disable the eslint extension.

@jrieken can you please try to reproduce this on your Mac. Thanks! Simple steps to get an eslint setup

- fresh directory
- npm init (answer the questions)
- npm install eslint --save
- /node_modules/.bin/eslint --init
  Answer the questions. Require semicolon and double quotes when asked
- open code
- create a couple of JS files
- look how many of these processes exist. There should actually none since this is a one time setup thing.

**Comment by jrieken** [comment]
yeah, I don't see leaking/any processes that are from eslint with those steps

**Comment by dbaeumer** [comment]
@jrieken thanks! I have no idea yet why these leak and the code around this has not changed since month. 

@albjerto is eslint actually functional when this happens (e.g. you see error produced by eslint).

**Comment by dbaeumer** [comment]
@albjerto do you see this with every workspace or only on specific once. If it only happens on specific once can you provide me with the source code?

**Comment by albjerto** [comment]
@jrieken I am indeed working on JS right now. @dbaeumer it was. I don't have my PC with me right now, so I'll make further investigations monday, but I remember seeing a eslint error on my output. The freeze occurs after a while so I'm not really sure they're related. Also I can't see any further output message because VSCode freezes. @dbaeumer I'll make further testings and check if it is a workspace-related issue monday. Thank to both of you for the quick answers.

**Comment by albjerto** [comment]
@dbaeumer @jrieken the exact same issue presented itself on the computer of a colleague who just updated VSCode, on the same workspace I was working on. I cannot reproduce it anymore though. As soon as I have time I will try and recreate the very same environment (same extensions installed and enabled, same steps) and see if it reappears.

**Comment by albjerto** [comment]
@dbaeumer @jrieken looks like the extension causing the forkbomb is not ESLint, but actually one called "Task Master". I will make its creator know.

**Comment by dbaeumer** [comment]
@albjerto thanks a lot for finding this out. 

He must have copied code from use since the command line is exactly what got spawned from the ESLint server. Ping if it turns out to be us :-)
