### ISSUE TITLE
The new title bar has a problem on maximize the window

### ISSUE THREAD

**Issue by MariusVatasoiu** [Microsoft/vscode#53707]
- VSCode Version: 1.25.0
- OS Version: Windows 10 1803

Steps to Reproduce:

1. Set `"window.titleBarStyle": "custom"`
2. Press maximize button to make the window full screen (Image 1)
3. Press again the maximize button to make the window smaller
4. Press once again the maximize button to make the window full screen (Image 2). Now the title bar has a blue border on top and an extra space.

Does this issue occur when all extensions are disabled?: Yes

Image 1:
![image1](https://user-images.githubusercontent.com/18071013/42378943-cf7b9082-8131-11e8-967a-86ad5c8dd05d.PNG)

Image 2:
![imag2](https://user-images.githubusercontent.com/18071013/42378950-d6ca6340-8131-11e8-956b-4ea1caf7d258.PNG)

**Comment by MarekLew** [comment]
Yes this problem exist on windows 10. Fragment from oryginal title bar show alter 2 maximalize.

**Comment by NearAutomata** [comment]
This is actually an issue with Electron (and presumably with the latest Windows 10 update) across various Electron-powered applications.

Related issues:

* electron/electron#12971
* electron/electron#12996
