### ISSUE TITLE
Portable Mode creates cache files in %APPDATA%

### ISSUE THREAD

**Issue by jmlntw** [Microsoft/vscode#53706]
- VSCode Version: 1.25.0
- OS Version: Windows 10 Home 1803

Steps to Reproduce:

1. Download and extra VS Code 1.25 in any folder.
2. Create `data` folder in VS Code's folder to enable Portable Mode.
3. Launch VS Code (`code.exe`) and then close it.
4. Some cache files are created in `%APPDATA%\Code\CachedData`.

Does this issue occur when all extensions are disabled?: Yes

---

Is there any possible to keep all cache files in VS Code's folder? Thanks.

**Comment by joaomoreno** [comment]
@jrieken Can you review and verify? https://github.com/Microsoft/vscode/commit/14d8d7cd7491dd80b4841529b4d1c1def9ef4d89

**Comment by jrieken** [comment]
Yeah, looks good. Adding verified based on code review
