### ISSUE TITLE
markdown preview image cannot find relative path (parent folder)

### ISSUE THREAD

**Issue by Creta5164** [Microsoft/vscode#53711]
![image](https://user-images.githubusercontent.com/13521406/42380390-b66c1378-8168-11e8-8d31-5f2606ddd7d1.png)

version : 1.24.1
if targeted with relative path, preview didn't parse that.
but with `<img>` tag is fine.

**Comment by Creta5164** [comment]
I've found the problem clearly.
It seems that parsing does not work if the path contains spaces.

 * ` ` : can't parse.
 * `&nbsp;` : can't parse.
 * `%20` : detect space and it's trying parse.

![image](https://user-images.githubusercontent.com/13521406/42392838-345428f4-818f-11e8-88bc-9869b053401f.png)

**Comment by mjbvz** [comment]
Markdown links must be valid uri components, so you must precent encode space and other special characters. We follow the common mark spec for this
