### ISSUE TITLE
suggestion score - allow first character to be a weak match

### ISSUE THREAD

**Issue by kiuuik** [microsoft/vscode#53715]
(This idea was originally posted in the repo for the python extension as issue [2097](https://github.com/Microsoft/vscode-python/issues/2097), reposted here on advice of [MikhailArkhipov](https://github.com/MikhailArkhipov). This is reworded and extended with screenshots)

Intellisense completions in VSCode are only shown after typing the first letter of a method. But I don't always remember this - I often only remember some other parts of a name.

Example: If I type 
 
    import os 
    os.dir

I would like to get "mkdir" or "makedirs" as a suggestion. This works as expected in VS Community2017 (or other IDEs like pycharm):

![intellisense_vs_community2017](https://user-images.githubusercontent.com/19992955/42380505-74e7b554-812e-11e8-83bc-ece31654ee40.png)
 
In VSCode 1.25.0 (with python extension 2018.06) I only get this:

![intellisense_vscode1 25](https://user-images.githubusercontent.com/19992955/42380531-84cd182e-812e-11e8-887f-c752623cd53d.png)

Only if I enter "os.m" I get suggestions for "mkdir" or "makedirs". It's nice that after the initial letter I can enter any string so that "os.md" shows the suggestions I want but I don't always remember the first letter of a method. I think I'm not the only one with this problem. 

This not only affects the module os but is a general problem.

I don't know how this behavior is called. maybe fuzzy completion? Please adjust the title of this thread.

**Comment by jrieken** [comment]
Understood. Today the rule is that the first matching character (e.g. `d`) must be a *strong* match. That are matches at the word-start, after a separator like `_` and `-`, and upper-case characters. We can think of relaxing that rule

**Comment by StephenWeatherford** [comment]
@jrieken How is this considered a feature request?  It is clearly a bug to filter out a valid completion that is being returned.  Can't imagine any user who would not consider it a bug.

**Comment by StephenWeatherford** [comment]
THanks!

**Comment by jrieken** [comment]
To verify

* ensure `editor.suggest.matchOnWordStartOnly` exists as setting and that it is on by default
* use the TS sample below and verify that `contextm` has no suggestion when the setting is on and that it has `oncontextmenu` when the setting is off
* try with similar cases

```ts
const root = document.createElement('div');
root.contextm
```

**Comment by joyceerhl** [comment]
The setting appears to be off by default: 
![image](https://user-images.githubusercontent.com/30305945/186484058-2de208c8-46e1-400f-bada-257f3ea8151d.png)

https://github.com/microsoft/vscode/blob/e1d50b06a522e9765b9d498e05a06af52e3a6503/src/vs/editor/common/config/editorOptions.ts#L4163-L4167

**Comment by etriebe** [comment]
I think off by default is expected. People can try this out for now, gather feedback and then see if it should be the new default.

**Comment by jrieken** [comment]
Great find @joyceerhl! This was an oversight when we semantically flipped the meaning of this setting

**Comment by etriebe** [comment]
Ah, right! Good find!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
