### ISSUE TITLE
Code snippet for function call not available for aliased functions. 

### ISSUE THREAD

**Issue by chemzqm** [microsoft/vscode#53716]
- VSCode Version:  1.25.0
- OS Version: MacOS

Steps to Reproduce:

1. Add `"typescript.useCodeSnippetsOnMethodSuggest": true,` to settings file to enable code snippet for method suggest.
2.  Create `a.ts` with
    ``` typescript
    export function func(str:string):void {
        // noop
    }
    ```
3. Create `b.ts` with
    ``` typescript
    import {func} from './a'
    
    ``` 
    and then type `func` and select `func` item, the completion is done, but no code snipet would b used.

The reason is because `typescript` server would return `alias` for the import variable but not function, so `typescript-language-features` extension would not consider it as function and no code snippet is generated.
<img width="729" alt="screen shot 2018-07-06 at 9 42 53 pm" src="https://user-images.githubusercontent.com/251450/42382360-a1ef1f96-8166-11e8-87a5-84c99af82f5f.png">
 

Does this issue occur when all extensions are disabled?: Yes

**Comment by yogeshmangaj** [comment]
@mjbvz I'd like to help, is there any more information that I could use to debug and fix this?

**Comment by chemzqm** [comment]
@yogeshmangaj here is the check for use code snippet
https://github.com/Microsoft/vscode/blob/74880d68369e10577bb3fc0786ab211d7aa372e7/extensions/typescript-language-features/src/features/completions.ts#L56
and here is the function to generate the snippet.
https://github.com/Microsoft/vscode/blob/74880d68369e10577bb3fc0786ab211d7aa372e7/extensions/typescript-language-features/src/features/completions.ts#L543

**Comment by yogeshmangaj** [comment]
@chemzqm I am not sure if I'm missing something, and this may be unrelated to the issue you have mentioned, but code snippet for a function does not show from within the same file either.

1. Create `a.ts` with
```
export function func(str:string):string {
    return "hello world";
}
```
2. On the next line in `a.ts` type `func`, the code snippet is same as what it shows for the alias function visible in your screenshot.

![image](https://user-images.githubusercontent.com/2225257/43025788-b94dc78e-8c90-11e8-8b70-f1e19887a6a0.png)

**Comment by chemzqm** [comment]
@yogeshmangaj I'm able to complete that, you should enable code snippet in your VSCode settings
```
    "typescript.useCodeSnippetsOnMethodSuggest": true,
```

**Comment by yogeshmangaj** [comment]
@chemzqm I have that setting enabled, and I still get the same thing, is there any other setting that has to be enabled? Could you please post a screenshot of the snippet that you're seeing (hope this is not bothersome)?
![image](https://user-images.githubusercontent.com/2225257/43037625-bbf1a2fc-8d2c-11e8-84df-19461cb86179.png)
Thanks!

**Comment by chemzqm** [comment]
@yogeshmangaj other setting should be unrelated.
I think you don't have snippet is because your tsserver is old, it should be 2.9.2 or later.

**Comment by yogeshmangaj** [comment]
@chemzqm that does not seem to be the case either, tsserver is 2.9.2

**Comment by chemzqm** [comment]
> On the next line in a.ts type func, the code snippet is same as what it shows for the alias function visible in your screenshot.

It's not the same, there not `alias`, you should be able to get the snippet by confirm the selection.

**Comment by mjbvz** [comment]
Closing this in favor of https://github.com/microsoft/TypeScript/issues/25207

We are limited in what we can do generating snippets on the VS Code side and really need TS support for more advanced support like this
