### ISSUE TITLE
VSCode Marketplace link does not connect or is  v   e   r    y     S   l   o    w . . .

### ISSUE THREAD

**Issue by txquestor** [Microsoft/vscode#5371]
- VSCode Version: 1.0
- OS Version: WIndows 8.1 Pro ver. 6.3.9600
Marketplace links:
https://marketplace.visualstudio.com/VSCode
https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp

Steps to Reproduce:

1. Go to the above links
2. No connection

**Comment by egamma** [comment]
Works for me currently. 
// CC @waderyan
