### ISSUE TITLE
Maximize/zoom for text editor 

### ISSUE THREAD

**Issue by costincaraivan** [Microsoft/vscode#53712]
The new grid editor is awesome! Thanks for adding it!

I'm not sure if this hasn't been suggested already, I couldn't find it.

But, basically what I'd want is: the possibility to maximize a single text editor pane, temporarily.

You work with a grid layout and then for some reason you want to see more of a specific file, but you don't want to throw away all the other files. So you'd just maximize temporarily the pane you want and minimize it back when you're done.

If you're not sure what I mean, just grad the nearest Tmux user and ask him to create a few panes and then maximize/revert one.

Very, very useful.

**Comment by isidorn** [comment]
I like this idea.
Maybe we could solve it by entering into Zen, add adding some zen setting of changing the grid layout.
Let's leave it open for now.

**Comment by costincaraivan** [comment]
This is dumb. Which issue is this duplicating?
