### ISSUE TITLE
VS Code won't launch in portable mode

### ISSUE THREAD

**Issue by webmasterMeyers** [Microsoft/vscode#53720]
- VSCode Version: 1.25.0
- OS Version: Window 10 Pro 1803 build 17134.112

Steps to Reproduce:

1. create data folder in C:\Program Files\Microsoft VS Code
2. try and start VS Code

VS Code will not launch.  Editing data folder permissions to allow "full access" OR launch VS Code as Administrator works.

When switching to portable mode, all extensions disappeared.  deleting the data folder restores original settings and extensions.

**Comment by joaomoreno** [comment]
Portable mode isn't to be used with the Windows Setup.

> Portable Mode is supported on the ZIP download for Windows and Linux, as well as the regular Application download for macOS.

https://code.visualstudio.com/docs/editor/portable
