### ISSUE TITLE
Can't get onDidChangeVisibility to fire

### ISSUE THREAD

**Issue by Gruntfuggly** [Microsoft/vscode#53721]
My extension contains:

```
    var todoTreeViewExplorer = vscode.window.createTreeView( "todo-tree-explorer", { treeDataProvider: provider } );

    todoTreeViewExplorer.onDidChangeVisibility( e =>
    {
        console.log( "Yeah baby!" );
    } );
```

but it never fires.

I've tried collapsing/expanding the tree, collapsing/expanding the viewlet, hiding/showing the viewlet, hiding/showing the container with the viewlet...

`todoTreeViewExplorer.visible` is always `false`

Am I missing something?

**Comment by sandy081** [comment]
@Gruntfuggly It works for me.. See the attached video. Which version of VS Code are you running on?

![kapture 2018-07-06 at 18 02 19](https://user-images.githubusercontent.com/10746682/42388760-df996e52-8146-11e8-86c5-8559847cff9e.gif)

**Comment by Gruntfuggly** [comment]
For anybody who find this with the same problem, it was because I originally implemented the tree using `vscode.window.registerTreeDataProvider` to create the view. When I added the view explicitly using `vscode.window.createTreeView` I forgot to remove the register command and it seems this is what was preventing the `visible` flag from being updated - probably because there was another view being created...
