### ISSUE TITLE
1.25 thrashing and then crashing under Windows 10

### ISSUE THREAD

**Issue by claudeduguay** [Microsoft/vscode#53729]
I was not able to find anyone else reporting similar problems but I had to revert to 1.24.1 after repeated experiments with 1.25. I don't have a trace or much of use but I will describe my experience and hope that additional information can be added by others if I'm not the only one who experienced this.

Last night I did the update and read through the release notes excited by the new windowing layout and other features. From the outset, however, performance was laggy and I suspected the animated images in the release notes, but the problem persisted.

I saw a thin progress bars in the top area of the editor panel on occasion and wondered if, like Eclipse, the language services were trying to slurp up relevant data in some of the larger projects but even smaller projects appeared to have the same problem. The interface becomes unresponsive, taking the CPU to the point of not allowing the mouse to move. 

Typically, this would eventually lead to a dialog about restarting without much additional information other than reporting a crash.

I started the process of narrowing things down.

1) Uninstalled, reinstalled.
2) Renamed user folder (removing all custom configuration and extensions).
3) Tried to find root causes, repeatable actions, doesn't seem tied to specific activities.

I cannot afford to spend more time on this at the moment but uninstalling and installing 1.24.1 works fine. I even repeated this, uninstalling 1.24.1 and installing 1.25 again, to no avail. I have removed it and am currently working with 1.24.1 to stay productive.

Any advice on find the root cause would be useful. I will try to find time this weekend to try anything that makes sense. If anyone else is having similar issues, I presume they can be added to this ticket if the symptoms are the same.

- VSCode Version:
1.25.0
- OS Version:
Windows 10

Steps to Reproduce:

1. Install 1.25.0 on Windows 10
2. Open projects and do normal actions like loading a file into the editor or navigating the file system or menus.

Does this issue occur when all extensions are disabled?: YES

**Comment by jrieken** [comment]
When this happens - can you follow this guide: https://github.com/Microsoft/vscode/wiki/Performance-Issues#visual-studio-code-is-consuming-a-lot-of-cpu. Also, does this happen when justing open files or when reading release note.

**Comment by claudeduguay** [comment]
I was able to resolve this using the prescribed tooling and disabling extensions that appeared to operate poorly. thanks for the assistance.

**Comment by an5rag** [comment]
@claudeduguay I'm facing the exact same issue and disabling all extensions worked. I'm now trying to selectively enable some extensions to find the culprit. Which extension was the culprit in your case?
