### ISSUE TITLE
The terminal process exited with code 5 

### ISSUE THREAD

**Issue by mijunk** [Microsoft/vscode#53726]
This was reported and closed with issue #43980.

This is not a duplicate of any issue I can see by searching the issues.  This is still happening with the latest build so it's not closed.  Your VSCodeBot is closing things improperly which frankly should be another bug.

Windows 10.
VS Code:
Version: 1.25.0
Commit: 0f080e5267e829de46638128001aeb7ca2d6d50e
Date: 2018-07-05T13:11:58.697Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

Steps to Reproduce:

1. Launch the integrated terminal

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
What's in your settings.json file?
