### ISSUE TITLE
Editor Layout->Toggle Verticle/Horizontal Layout - icon doesn't change reflecting new setting

### ISSUE THREAD

**Issue by Zephilim** [Microsoft/vscode#53728]
- VSCode Version: 1.25.0
- OS Version: macOS 10.13.5

Steps to Reproduce:

1. Open a source code file in the text editor
2. Select Toggle Verticle/Horizontal Layout from View->Editor Layout
3. Perform a view split, by right clicking on the editor source file tab and selecting "Split Down". I don't know if an up/down split corresponds to horizontal or vertical split mode (this is ambiguous and could mean either depending on your perspective!)
4. The icon indicating the horizontal/vertical layout should change to reflect the layout setting. However, the icon never changes and so you don't know what state the feature is in. (This used to work properly in previous version)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
This feature works differently now, it will just flip the orientation of the grid but not have any other impact. To change the split direction you can configure `"workbench.editor.openSideBySideDirection"`.
