### ISSUE TITLE
Cursor position bug for text with Mongonlian/Manchu letters

### ISSUE THREAD

**Issue by smreg** [Microsoft/vscode#5372]
- VSCode Version:  1.0.0 (1.0.0)
- OS Version: OS X Yosemite 10.10.5

Steps to Reproduce:

1. Installing fonts for Mongolian/Manchu texts

   You can download free font from here: [Daicing White](https://raw.githubusercontent.com/smreg/smreg.github.io/master/css/font/DC_White.ttf)

2. Setting up font config `editor.fontFamily`

3. Input text in Mongolian/Manchu letters, for example:
   `ᠮᠠᠨᠵᡠ ᠊ᡳ ᡥᡝᡵᡝᡤᡝᠨ `
    , the text can be displayed as okay, but the position of the cursor is buggy.

   When you input the text naturally from line start, your cursor is at the line end, but it does show at the line head.

  Weird when you navigate left forward, and then navigate right forward by the same steps as the left forward part, the cursor would be positioned at the line end and it is okay now. But then you are at the line end again, you press the right arrow key in the keyboard, the cursor would be positioned at the line head again.

===
Thank the intelligent and hardworking people in Microsoft and the community for bringing out such a "God saw that it was good" text editor, I wish this excellent work could benefit more people.
Thank you. Have a nice day.
(❁´◡`❁)*✲ﾟ*

**Comment by alexandrudima** [comment]
This was caused by [Chromium issue 487028](https://code.google.com/p/chromium/issues/detail?id=487028). We got the Chromium fix with our upgrade to Electron v0.37.6 which includes Chromium 49.
