### ISSUE TITLE
IPython autoreload does not work in integrated-terminal

### ISSUE THREAD

**Issue by Tembocs** [Microsoft/vscode#53738]
- VSCode Version: 1.25.0 stable
- OS Version: Windows 10, 64 bit, Insider build 17704.1000

Steps to Reproduce:
1. Start a terminal session with PowerShell as the shell
2. In the integrated-terminal call ipython
3. Once ipython starts call '%load_ext autoreload' then call '%autoreload 2'
4. Import any Python module you are working on in the editor.
5. Modify the module in the editor
6. Call some code from the module --> It does not work.

Repeating the above using standalone PowerShell --> It works.

**Comment by Tyriar** [comment]
Can you explain what's meant to happen for someone with no experience with ipython?

**Comment by Tembocs** [comment]
What is meant to happen is;
In ipython calling '%load_ext autoreload' followed by '%autoreload 2' is used to ensure that ipython reload your script before executing anything from it every time you call code from it. That way one does not need to start a new instance of ipython every time changes are made in their script.

**Comment by Tyriar** [comment]
Ah I see, given this is something that is entirely handled by ipython I don't see how it could be a problem with the VS Code terminal. It might be worth reaching out to the ipython team and see if they know what's going on with your setup.
