### ISSUE TITLE
Create a theme key for terminal command options

### ISSUE THREAD

**Issue by tweakimp** [Microsoft/vscode#53735]
Currently, if you type something like `python -m` in the terminal, "-m" is colored in `terminal.ansiBrightBlack`. The problem is that with dark themes that have a dark `terminal.background` color you can not see the command option very well unless you redefine what black is,
![imgofwhatimean](https://i.imgur.com/DsWTLqZ.png)
Please add a specific key for these options.

**Comment by Tyriar** [comment]
I don't understand the request, these two colors are `terminal. ansiBrightBlack` and `terminal.background` as you suggest. You just need to increase the contrast between the 2 colors.

**Comment by tweakimp** [comment]
I can just change the `terminal. ansiBrightBlack` so that the readability is good enough, sure, but then black is not black any more. if any program wants to output something in `BrightBlack`, it prints the light color i set to have a contrast to the background.If I change it to yellow and the output should be a character with a yellow background and a bright black foreground color, you would just see a yellow block. 
I hope you understand what i mean :)
(btw how can i find out that colors have other use than what the dscription is saying? I had to find this with trial and error, is there a better way?)

**Comment by Tyriar** [comment]
@tweakimp most terminals would tweak ansiBlack and ansiBrightBlack to be a grey that you can make out. The inverse is also an issue with white text on white background. It's just a flaw in the way that terminals were designed, there isn't really a fix to it other than that.

The description is the only way to find out what it does, for these keys specifically they're only used for what you're seeing.

**Comment by tweakimp** [comment]
Ok, thank you for your time.
Keep up the good work!
