### ISSUE TITLE
Automatically Open any folder in VS code

### ISSUE THREAD

**Issue by saileshkush95** [Microsoft/vscode#53734]
Today, Frist time I tried vs code in the linux environment, and I'm facing a big problem.
When i try to open any folder on desktop by double clicking, it automatcally open in vs code.
But after uninstalling vscode I didn't face any types of problem like this with other editor like atom
Please help me out, I love vs code

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/41037
