### ISSUE TITLE
"vscode.executeCompletionItemProvider" doesnot return a preselect field

### ISSUE THREAD

**Issue by akshita31** [Microsoft/vscode#53749]
Issue Type: <b>Bug</b>

I have been trying to add test for the `preselect` field for the completion item. However the object returned by the `executeCompletionItemProvider` doesnot return a preselect field. Here is the link to the [test](https://github.com/OmniSharp/omnisharp-vscode/pull/2388/files#diff-6f79647db32d51596484e4165e8c678aR34)  and the failing [build](https://travis-ci.org/OmniSharp/omnisharp-vscode/builds/401014505?utm_source=github_status&utm_medium=notification).

I suspect this is because the field is not being copied [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostTypeConverters.ts#L508).

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.90GB (16.40GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
cake-vscode|cak|0.11.2
gitlens|eam|8.4.1
tslint|eg2|1.0.33
csharp|ms-|1.15.2
sonarlint-vscode|Son|1.4.0
code-spell-checker|str|1.6.10
wallaby-vscode|Wal|1.0.91
licenser|ymo|1.1.2

</details>

**Comment by jrieken** [comment]
<img width="296" alt="screen shot 2018-07-10 at 09 33 39" src="https://user-images.githubusercontent.com/1794099/42495773-57606f28-8424-11e8-86b6-b5dd0888ef99.png">
 
and daily insiders

**Comment by jrieken** [comment]
@akshita31 Is this blocking you on something?

**Comment by akshita31** [comment]
@jrieken We have a PR that is blocked on this, because the test wont pass.

**Comment by jrieken** [comment]
I think that doesn't mean the bar for adding this to the recovery candidate. For the PR, I'd recommend to disable the test or, if that's possible, to run tests against insiders
