### ISSUE TITLE
Node Debugger not working

### ISSUE THREAD

**Issue by spicydonuts** [Microsoft/vscode#53745]
Issue Type: <b>Bug</b>

The built in Node.js debug extension says it's enabled and I don't see any errors in the output window related to it, but `"type": "node"` is not recognized in my `.vscode/launch.json` files and the menu which helps create new `launch.json` files does not list "Node.js" as an option. I've tried searching existing issues and googling but there's too much vscode debugging or general nodejs debugging noise .

OS: Arch Linux, installed VSCode and Node using the main AUR packages.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:47:35.732Z)
OS version: Linux x64 4.14.52-1-lts

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.39GB (2.95GB free)|
|Process Argv|/opt/visual-studio-code/code|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.18.0
EditorConfig|Edi|0.12.4
html-css-class-completion|Zig|1.17.1
project-manager|ale|8.0.0
npm-intellisense|chr|1.3.0
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.5.0
file-icons|fil|1.0.12
vscode-firefox-debug|hbe|1.4.1
language-haskell|jus|2.5.0
vsliveshare|ms-|0.3.379
debugger-for-chrome|msj|4.7.0
ide-purescript|nwo|0.19.0
language-purescript|nwo|0.1.2
vim|vsc|0.14.2

(1 theme extensions excluded)

</details>

**Comment by weinand** [comment]
Please make sure that the built-in node-debug extensions are enabled:

![2018-07-06_21-36-29](https://user-images.githubusercontent.com/1898161/42397060-af4457da-8164-11e8-98ec-88df6cea5da9.png)

**Comment by spicydonuts** [comment]
Ah, legacy was disabled. It seems to work now.. wasn't expecting them to be connected like that (also not sure how the legacy one got disabled in the first place)
