### ISSUE TITLE
Alt F followed by O without releasing ALT does not bring up the Open File dialog

### ISSUE THREAD

**Issue by Ams627** [Microsoft/vscode#53740]
- VSCode Version: 1.24.1
- Commit 24f62626b222e9a8313213fb64b10d741a326288
- OS Version: Window 8.1

Steps to Reproduce:

1. Press Alt F then without releasing Alt press O. I expect to see the open file dialog.

This is something I have been doing since Windows 3.1! Notepad has always supported Alt F O without releasing Alt. I just can't recondition my muscle memory after almost 30 years and it would be great if this is fixed.

Does this issue occur when all extensions are disabled?: Yes

**Comment by yarrgh** [comment]
Upgrade VSCode to 1.25.0 and change "window.titleBarStyle" to "custom"

**Comment by sbatten** [comment]
As @yarrgh mentions, this is resolved with the new menubar enabled via the setting above
