### ISSUE TITLE
Sometimes the Debug Console is double spaced

### ISSUE THREAD

**Issue by akbyrd** [Microsoft/vscode#53747]
Issue Type: <b>Bug</b>

Depending on the width of the side bar in the first fraction of a second after being shown the Debug Console sometimes injects extra blank lines between every actual line. Gif attached.

![debug console](https://user-images.githubusercontent.com/484784/42397143-597c5102-812a-11e8-9fe0-f7abd9434b26.gif)

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (10.51GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-npm-script|eg2|0.3.5
tortoise-svn|fan|0.1.1
vsc-space-block-jumper|jmf|1.2.2
Lua|key|0.0.9
theme-monokai-pro-vscode|mon|1.1.8
python|ms-|2018.6.0
cpptools|ms-|0.17.6
csharp|ms-|1.15.2
Go|ms-|0.6.84
PowerShell|ms-|1.7.0
code-settings-sync|Sha|2.9.2
shader|sle|1.1.3
Align|ste|0.2.0
unity-debug|Uni|1.3.0
vscode-todo-highlight|way|0.5.12

(1 theme extensions excluded)

</details>

**Comment by akbyrd** [comment]
Text in the editor doesn't have this problem. Why's it only broken in some places?

At least 75% of the time I'm looking that the console output after an application has closed. Either it's printing profiling information on exit or dumping a stack trace in the case of an error. So 'it will re-wrap later' doesn't help my use case. It's an unpleasant workflow to open the window, see that it's messed up, and have to drag it around awkwardly to get properly formatted text.

If this is unsolvable, I'd much rather have no wrapping at all and a scroll bar.

**Comment by hfhchan** [comment]
Issue #57656 doesn't seen to resolve with new entries added into the console.
