### ISSUE TITLE
Feature Request: Outline Settings

### ISSUE THREAD

**Issue by hparadiz** [Microsoft/vscode#53746]
Please allow hiding or showing of different outline elements depending on the language.

For example in PHP it is useful to see:
- Includes/Requires
- Namespace declarations
- Class definition
- Trait declarations
- Method defines

But I want to turn off listing method parameters as it is cluttering the outline view without providing much value.

Here's a screenshot to show how cluttered it can get.
![image](https://user-images.githubusercontent.com/195216/42396996-2631a434-8132-11e8-9c88-197cc22bb49b.png)
---------------

We should also be able to move outline view. It is currently extremely annoying that it is using up space from the file tree view.

Please allow moving Outline view to to the right.

It should also potentially be possible to replace minimap with outline view (or show both).

---------------

Thank You!

**Comment by Outpox** [comment]
I would also really love to be able to filter the elements by type and (then) by name.

**Comment by murraycollingwood** [comment]
SOLVED: I was using the Extension "PHP Intellephense", I disabled this and installed "PHP IntelliSense" and all of those properties disappeared, now I see a list of functions!

The automatic code completion is also less invasive, another benefit.
