### ISSUE TITLE
Integrated terminal: selected text doesn't stay selected (v1.24.1 on Ubuntu 18.04)

### ISSUE THREAD

**Issue by lcscs12345** [Microsoft/vscode#53759]
Hi,

VSCode is awesome. However, the integrated terminal doesn't follow a default behaviour of linux terminal. Selected text in the terminal doesn't stay selected when typing a new command. To reproduce this, select a text in the integrated terminal and type something, the text is no longer selected. Thank you!

**Comment by Tyriar** [comment]
This is a design decision in [xterm.js](https://github.com/xtermjs/xterm.js) so the issue belongs over there. I would be interested to hear in why you want this though as it seems like such a minor thing to me that I'm not sure it's worth the added complexity in the API.

**Comment by lcscs12345** [comment]
Thank you for your reply. This is the muscle memory that I developed over the years using linux terminal. I always select text on linux terminal, type something, then ctrl+shift+c to copy the selected text and ctrl+shift+v to paste in order to complete the command. I've added right click to copy option to vscode terminal. But shifting between vscode and linux terminal will be a pain.

**Comment by Tyriar** [comment]
Just did a little check on what other terminals do, here are the results:

- gnome-terminal (VTE): retains selection, no selection
- xterm: clears selection, no setting
- Terminal.app: clears selection, no setting
- iTerm: clears selection, no setting

Given this and the fact that there's only be a single request for this in the ~2 years we've had the terminal I'm going to close this as out of scope. I don't think there's enough need for exposing an API in xterm.js and a setting in VS Code when so few people are going to use it. I'll keep looking out for these requests though.
