### ISSUE TITLE
Label split-windows in source control working tree

### ISSUE THREAD

**Issue by denDAY04** [microsoft/vscode#53753]
When inspecting changes made in source control (I have only tried in git) the split-windows showing the working tree changes are unlabeled. It would be nice if we were able to tell which window was the local changes and which window was the tracking HEAD, instead of having to make assumptions based on other IDEs.

**Comment by joaomoreno** [comment]
Can you explain this better with a screenshot?

**Comment by denDAY04** [comment]
Yes of course. I've taken a screenshot of a workting tree view which can be seen [here](https://imgur.com/a/5uwmnd3), displaying the changes made to a file. What I'm missing is an indication of which of the two split-windows is my hanges, and which one is the file such as it looks in the currently tracking HEAD. 

In the current representation I'm left to guess which window is which; whether the changes I've made is displayed on the left window or the right window.
