### ISSUE TITLE
Change default keybindings for subword navigation

### ISSUE THREAD

**Issue by cauebs** [Microsoft/vscode#53750]
The current defaults conflict with common bindings for operating systems and window managers (the worst being `ctrl+alt+delete`), so I proppose we remove `ctrl` from all of them. This would match what Atom and Sublime Text do by default and, as far as I can tell, doesn't conflict with any other VSCode defaults.

**Comment by garu57** [comment]
As a matter of fact with 1.25.1 subword navigation keybindings conflicts with other core default bindings (all extensions disabled) that that are taking precedence or are predated. 
Here they are in order of precedence (bottom highest):

```
{ "key": "ctrl+alt+right", "command": "cursorWordPartRight", "when": "textInputFocus" },
{ "key": "ctrl+alt+right", "command": "workbench.action.moveEditorToNextGroup" },

{ "key": "ctrl+shift+alt+right", "command": "cursorColumnSelectRight", "when": "textInputFocus" },
{ "key": "ctrl+shift+alt+right", "command": "cursorWordPartRightSelect", "when": "textInputFocus" },

{ "key": "ctrl+alt+left", "command": "cursorWordPartStartLeft", "when": "textInputFocus" },
{ "key": "ctrl+alt+left", "command": "workbench.action.moveEditorToPreviousGroup" },

{ "key": "ctrl+shift+alt+left", "command": "cursorColumnSelectLeft", "when": "textInputFocus" },
{ "key": "ctrl+shift+alt+left", "command": "cursorWordPartStartLeftSelect", "when": "textInputFocus" },
```

**Comment by alexandrudima** [comment]
Let's discuss in #53671
