### ISSUE TITLE
My extension doesn't run when I run it in debugger. It says "Extension did not start in 10 seconds".

### ISSUE THREAD

**Issue by KalitaAlexey** [Microsoft/vscode#5375]
- VSCode Version: 1.0
- OS Version: Ubuntu 14.04.3 x64

Steps to Reproduce:

1. Install VSCode for insiders. Uninstall VSCode for insiders. Install VSCode 1.0
2. Try run extension

Extension: https://github.com/saviorisdead/RustyCode

**Comment by egamma** [comment]
This issue was moved to saviorisdead/RustyCode#96

**Comment by KalitaAlexey** [comment]
Why did you close it?
