### ISSUE TITLE
executeTask Cannot read property _key of undefined

### ISSUE THREAD

**Issue by ThadHouse** [Microsoft/vscode#53752]
Issue Type: <b>Bug</b>

After updating to VS  Code 1.25,  calling executeTask is throwing `Cannot read property '_key' of undefined`. Below is the task structure that is getting passed to the function.

```
"{
    "_definition": {
        "type": "wpilibgradle"
    },
    "_scope": {
        "uri": {
            "$mid": 1,
            "fsPath": "c:\\Users\\thadh\\Documents\\VscodeTests",
            "external": "file:///c%3A/Users/thadh/Documents/VscodeTests",
            "path": "/c:/Users/thadh/Documents/VscodeTests",
            "scheme": "file"
        },
        "name": "VscodeTests",
        "index": 0
    },
    "_name": "C++ Build",
    "_source": "wpilib",
    "_execution": {
        "_commandLine": "gradlew assemble",
        "_options": {
            "cwd": "c:\\Users\\thadh\\Documents\\VscodeTests",
            "executable": "cmd.exe",
            "shellArgs": [
                "/d",
                "/c"
            ]
        }
    },
    "_problemMatchers": [],
    "_hasDefinedMatchers": false,
    "_isBackground": false
}"
```

Below is the full error.
```
"{
    "name": "TypeError",
    "message": "Cannot read property '_key' of undefined"
}"
```

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (1.20GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
vscode-express|Com|0.0.5
tslint|eg2|1.0.33
arduino-gmr-vscode|Gre|0.0.4
python|ms-|2018.6.0
cpptools|ms-|0.17.6
csharp|ms-|1.15.2
PowerShell|ms-|1.7.0
java|red|0.28.0
vscode-icons|rob|7.24.0
gitconfig|sid|1.0.1
vscode-hexdump|sle|1.6.0
vscode-ev3cpp|tha|0.0.4
vscode-wpiformat|tha|0.0.4
vscode-arduino|vsc|0.2.17
vscode-java-debug|vsc|0.10.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.7.0
vscode-maven|vsc|0.9.0
vscode-cil-complete|wk-|0.0.5
vscode-wpilib|wpi|0.1.0-20180703171836-40-g2382b2d

</details>

**Comment by ThadHouse** [comment]
My extension was using VS Code engine v1.24.0. Upgrading to 1.25.0 Does not change or fix the issue. This is a major blocker and regression to my extension.

**Comment by dbaeumer** [comment]
@ThadHouse Thanks for the repro. I will have a look right away.

**Comment by dbaeumer** [comment]
@ThadHouse I looked at your repro and the problem is that your introduce a new task type `wpilibgradle` but din't declared it as a contribution in the package.json. There was a code pass where I forgot to check this and I fixed it for 1.25.0 because not declaring the type correctly resulted in issue where the systrem executed the wrong task. A good example of how to declare a task definition can be found here: https://github.com/Microsoft/vscode/blob/master/extensions/gulp/package.json#L46

If you point me to the source code of your extension I am happy to help fixing this.

**Comment by dbaeumer** [comment]
In the example you provided you need to add the following to the package.json
```
        "taskDefinitions": [
            {
                "type": "wpilibgradle"
            }
        ]
```

which makes the example work. I apologize for the breakage that I have caused.

**Comment by dbaeumer** [comment]
Just for clarification: a task definition was always mandatory however I wasn't good at enforcing it. I added code to make tasks fail earlier if the task definition is missing. I should have been more carefully with the change though.

**Comment by ThadHouse** [comment]
Ah ok. Here is my actual extension, and I will look to ensure that adding that fixes my issue later today when I'm near my computer again.

https://github.com/wpilibsuite/vscode-wpilib

However, I think this could be better documented. It's not on the package.json documentation page at all, and in the extension API the only place this is documented is on the parameter docs for vscode.TaskDefinition, which means 2 nodes have to be expanded in order to see it. I think adding to the package.json page, or a specific page dealing with tasks (like the webview one) might help solve issues like this in the future.

**Comment by dbaeumer** [comment]
Actually, now that I think about it I should relax that for `executeTask` and maker is recommended (for consistency reasons) and only mandatory fort `provideTasks`.

**Comment by dbaeumer** [comment]
I agree, that this needs documentation in the package.json documentation page. I made myself an item for it :-). I still recommend that you add the `taskDefinition` in your package.json even if I relax that for executeTask.

**Comment by dbaeumer** [comment]
Adding to recovery milestone to relax this for execute Task.

**Comment by dbaeumer** [comment]
To verify for the recovery build clone the repository from this comment https://github.com/Microsoft/vscode/issues/53752#issuecomment-403156005

- open the workspace
- run the extension
- open a folder workspace
- Execute the command `Hello World`

Ensure that a task is executed in the terminal that prints `hello`
