### ISSUE TITLE
scm

### ISSUE THREAD

**Issue by jewels98** [Microsoft/vscode#53761]
Issue Type: <b>Bug</b>

I dont have access to my scm and I have loaded extensions for git. I would like to stop using the terminal, however I dont have any options with the scm. I can only use the control panel instead of drop down menu for my extensions.

VS Code version: Code - Insiders 1.26.0-insider (bd953248ad6a8e2f8896bfb78b3ae40e0fd47426, 2018-07-06T05:11:13.829Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.30GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|0.11.1
git-easy|bib|1.9.1
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.59
vscode-markdownlint|Dav|0.18.0
vscode-eslint|dba|1.4.12
jquerysnippets|don|0.0.1
gitlens|eam|8.4.1
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.5.0
git-project-manager|fel|1.6.1
beautify|Hoo|1.3.2
jquery-snippets|Hri|1.0.0
ftp-simple|hum|0.6.7
icon-fonts|idl|2.1.0
node-module-intellisense|lei|1.5.0
vs-color-picker|lih|0.7.0
code-beautifier|mic|2.1.0
Angular-BeastCode|Mik|6.0.20
easy-less|mrc|1.4.5
vscode-less|mrm|0.6.3
vscode-scss|mrm|0.6.2
atom-keybindings|ms-|3.0.4
debugger-for-chrome|msj|4.7.0
material-icon-theme|PKi|3.5.1
Ruby|reb|0.18.0
live-sass|rit|2.2.1
LiveServer|rit|5.1.1
vscode-icons|rob|7.24.0
sass-indented|rob|1.4.9
javascript-typescript|sou|0.0.7
open-in-browser|tec|1.1.0
vscode-terminal-here|Tyr|0.1.1
html-css-class-completion|Zig|1.17.1
vscode-open-in-github|ziy|1.3.3

(4 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
I have a very hard time understanding what you mean. Maybe show me a couple screenshots?

**Comment by jewels98** [comment]
I am having a tough time with source control provider connecting with team
services. I have signed up to team services but when I turn on team
services extension I get a pop-up to sign up window. Is there an easy way
to set up this app on Macs. I have tried to follow the videos on you tube,
but some videos seem dated.

**Comment by joaomoreno** [comment]
Is this about TFS?

**Comment by jewels98** [comment]
Thanks I'll figure it out
