### ISSUE TITLE
editor.renderWhitespace: true doesn't render intra-line whitespace

### ISSUE THREAD

**Issue by BillyONeal** [Microsoft/vscode#5376]
- VSCode Version: 1.0
- OS Version: Windows 10, rs1_lkg selfhost

Steps to Reproduce:

1. Turn editor.renderWhitespace on.
2. Open a file with significant whitespace not at the start of a line.

Compare Visual Studio Code vs. Sublime Text with the same file:

<img width="1280" alt="2016-04-15_23-25-44" src="https://cloud.githubusercontent.com/assets/1544943/14579527/2ed24e04-0362-11e6-8ea7-a877ebc01a3a.png">

<img width="1280" alt="2016-04-15_23-26-56" src="https://cloud.githubusercontent.com/assets/1544943/14579529/3f5287f8-0362-11e6-8d11-68b3238317ed.png">

**Comment by BillyONeal** [comment]
Looks like the offending code is here: https://github.com/Microsoft/vscode/blob/c82ac047c4f43f738d212c3d6e600180475543d0/src/vs/editor/common/viewLayout/viewLineParts.ts#L162 but I'm not super sure how to modify it. Giving it a shot.

**Comment by glen-84** [comment]
Duplicate of #3828 (?)

**Comment by BillyONeal** [comment]
Yup, looks like a dupe to me. Thanks!
