### ISSUE TITLE
Fold / Unfold buttons not showing up on some parts of the file

### ISSUE THREAD

**Issue by andrewloable** [Microsoft/vscode#53766]
Issue Type: <b>Bug</b>

Hi,

For some reason, only codes below a certain line number only gets the fold / unfold option.
All codes above it does not show the fold/unfold button besides the line numbers at all.

For example in the screenshot below, after doing a fold all command, all code below line 211 gets folded while the catch block at line 198 does not. the fold/unfold button is also not visible on the code above line 211.

![image](https://user-images.githubusercontent.com/10375300/42404898-57cf2d5c-81c0-11e8-8ad1-f2023e467b5a.png)

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz (4 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (10.18GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|29%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
dart-code|Dar|2.15.0
vscode-clang|mit|0.2.2
python|ms-|2018.6.0
cpptools|ms-|0.17.6
Go|ms-|0.6.84
vetur|oct|0.12.5
java|red|0.28.0
html-preview-vscode|tht|0.1.1
vscode-java-debug|vsc|0.10.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.7.0
vscode-maven|vsc|0.9.0

</details>

**Comment by aeschli** [comment]
@andrewloable Can you attach the file to reproduce the behaviour?

**Comment by andrewloable** [comment]
@aeschli Sorry I can't due to NDA.

**Comment by andrewloable** [comment]
@aeschli attached test.js

I just repeated the structure multiple times and the bug shows up after about 1178 lines. (tested in 1.25.1)


[test.zip](https://github.com/Microsoft/vscode/files/2194553/test.zip)

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/25782 to track this upstream
