### ISSUE TITLE
Ability for extensions to extend language Intellisense

### ISSUE THREAD

**Issue by fusepilot** [Microsoft/vscode#53765]
A project my team is working on involves working with Javascript files that are loaded inside an application during its runtime. The application injects global functions in the Javascript's scope at runtime dynamically. I'd like to write an extension that provides Intellisense about the dynamically injected functions.

A workaround is to put `/// <reference path="path/to/types.d.ts" />` at the top of the Javascript file. This isn't ideal since we aren't using a package.json that could install those definitions in the project easily. So instead, we need to ensure everyone has them installed at a pre-determined location on the development machine.

Being able to wrap up this functionality, plus a few other project specific editor features inside of an extension would be a great productivity boost for us.

**Comment by mjbvz** [comment]
This is a good use case for a TypeScript server plugin: https://github.com/Microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin

These plugins can augment JS and TS language support. They can also be contributed by VS Code extensions through the `typescriptServerPlugins` contribution point
