### ISSUE TITLE
Drag array items to reorder

### ISSUE THREAD

**Issue by dylanmcgowan** [Microsoft/vscode#53771]
It would be neat if you could drag an array item to reorganize because copy pasting back spacing is like so 2010. And the select drag doesn't play nice with auto spacing.

**initial array**
```
[ 'One', 'Two', 'Three' ]
```

**drag feature**
```
[
'One', 👈 click and drag
'Two',
'Three',
👈 put right here
]
```
***new array*** 
```
[ 'Two', 'Three', 'One' ]
```

Maybe you hold alt or ctrl to toggle the grabbie drag fist 🤔

**Comment by zurkoxxx** [comment]
seems kind of unnecessary to me.
if your array is formated like this:
``` 
[  
    'One',
    'Two',
    'Three', 
]
```
you can just use alt+up/down arrow to move elements up/down
