### ISSUE TITLE
Support for scrolling on touch-enabled devices

### ISSUE THREAD

**Issue by WhatFor** [microsoft/vscode#53775]
Issue Type: <b>Feature Request</b>

As a user of a touch screen laptop, it would be really useful to be able to scrub through the minimap using touch. With touch enabled devices becoming more common, it would be great! 😊🚀

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

**Comment by fredski02** [comment]
@DoctorChip 

How is your touch screen experience with vscode in general?

**Comment by p0kR** [comment]
Same for me, can't scroll with my touchscreen device.
I can "click"/touch on the minimap to use it, but I cannot drag the current view.
I also cannot scroll in opened files or the file/extension/... sidebar.
I am using Ubuntu with (vanilla) Gnome 3.30

**Comment by Ciantic** [comment]
I think this should be reopened, this is *not* a duplicate of #47771 because that bug is about minmap.

Bigger problem is that you can't scroll the actual editor with a touch input.

**Comment by alexandrudima** [comment]
@Ciantic This issue is about the minimap.

> As a user of a touch screen laptop, it would be really useful to be able to scrub **through the minimap** using touch

Please create a separate issue for your issue.
