### ISSUE TITLE
HTML outline error

### ISSUE THREAD

**Issue by roshad** [Microsoft/vscode#53770]
- VSCode Version: 1.25.0
- OS Version: Win 7

5 sections in main. But it displays 4 outside.
![qq 20180707135443](https://user-images.githubusercontent.com/30169506/42407363-3d4fd7f6-81ed-11e8-88e4-ec04376b1e9a.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
@roshad I was not able to reproduce with
```
<main>
    <section></section>
    <section></section>
    <section></section>
    <section></section>
    <section></section>
</main>
```

Maybe something wrong in the folded code?
Can you attach a full example?

**Comment by roshad** [comment]
[Codepen](https://codepen.io/roshad/pen/wXLPeP)

**Comment by roshad** [comment]
`<main id="main-doc">
  <section class="main-section" id="Introduction">
    <header>Introduction</header>
    <article>  
      <p>JavaScript is a cross-platform, object-oriented scripting language. It is a small and lightweight language. Inside a host environment (for example, a web browser), JavaScript can be connected to the objects of its environment to provide programmatic control over them.</p>

      <p>
        JavaScript contains a standard library of objects, such as Array, Date, and Math, and a core set of language elements such as operators, control structures, and statements. Core JavaScript can be extended for a variety of purposes by supplementing it with additional objects; for example:

        <li>Client-side JavaScript extends the core language by supplying objects to control a browser and its Document Object Model (DOM). For example, client-side extensions allow an application to place elements on an HTML form and respond to user events such as mouse clicks, form input, and page navigation.</li>
        <li>Server-side JavaScript extends the core language by supplying objects relevant to running JavaScript on a server. For example, server-side extensions allow an application to communicate with a database, provide continuity of information from one invocation to another of the application, or perform file manipulations on a server.</li>
      </p>
    </artice>
  </section>
  
  <section class="main-section" id="What_you_should_already_know">
    <header>What you should already know</header>
    <article>
      <p>This guide assumes you have the following basic background:</p>

      <li>A general understanding of the Internet and the World Wide Web (WWW).</li>
      <li>Good working knowledge of HyperText Markup Language (HTML).</li>
      <li>Some programming experience. If you are new to programming, try one of the tutorials linked on the main page about JavaScript.</li>
    </artice>
  </section>
  
  
</main>`
Code before fixing.
