### ISSUE TITLE
how to reopen the issue#53599

### ISSUE THREAD

**Issue by ShayCormac1963** [Microsoft/vscode#53779]
Issue Type: <b>Bug</b>
![image](https://user-images.githubusercontent.com/19632359/42382650-91f0ab40-8167-11e8-8725-2c930e6edbfe.png)
i have never toggle flies exclude fliter and it will randomly Display the above prompts that i can't find what happen to my code

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.17686

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (8.41GB free)|
|Process Argv|E:\Program Files\VSCode-x64-1.23.1\Code.exe|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
read-only-indicator|ale|0.7.0
custom-window-zoom|cra|1.1.4
xml|Dot|2.3.1
gc-excelviewer|Gra|2.1.24
code-eol|jef|0.3.7
vscode-language-pack-zh-hans|MS-|1.25.3
anaconda-extension-pack|ms-|1.0.0
python|ms-|2018.6.0
vscode-yaml|red|0.0.13

(1 theme extensions excluded)

</details>

**Comment by ShayCormac1963** [comment]
there is no use to solve this problem
> Steps to Reproduce:

Open Problems View
Toggle Files exclude option in the filter box
Toggle Problems view
Expected: Files exclude option state is retained
Actual: Files exclude option state is reset.

**Comment by sandy081** [comment]
@ShayCormac1963 I replied to your comment in #53599. Please continue the discussion there.
