### ISSUE TITLE
希望vscode可以想sublime一样有subl快捷命令

### ISSUE THREAD

**Issue by biij5698** [Microsoft/vscode#5377]
Linux下，可以在命令行下输入subl打开sublime，这有特殊作用，比如sudo subl，那么此时的vscode就具有高级权限，希望vscode也可以

**Comment by biij5698** [comment]
通过code命令是可以的，很好

**Comment by hungys** [comment]
There exists a command for your need: `Shell Command: Install 'code' command in PATH`

Check [https://code.visualstudio.com/docs/editor/setup](https://code.visualstudio.com/docs/editor/setup) for the tips.

**Comment by Tyriar** [comment]
Run `code` on the command line for this, if you're on OS X you may need to install it via the command that @hungys mentions.

For `sudo code`, that is captured in this issue: https://github.com/Microsoft/vscode/issues/3068
