### ISSUE TITLE
Can't click titlebar menu after focusing titlebar

### ISSUE THREAD

**Issue by Albert221** [Microsoft/vscode#53788]
- VSCode Version: 1.26.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Have `"window.menuBarVisibility": "toggle"`
2. Click on the title bar
3. Press `alt`
4. Click on any menu option - you can't. You have to click on editor area first to set it focused or something

It doesn't occur always, but pretty much the majority of times I try to reproduce.

**Comment by sbatten** [comment]
I believe this is the same as #52522
