### ISSUE TITLE
Cannot attach debugger to VS Code using process._debugProcess

### ISSUE THREAD

**Issue by TomasHubelbauer** [Microsoft/vscode#53789]
VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.17134

I cannot seem to be able to attach a debugger to an existing instance of Code by executing `process._debugProcess(<code-pid>)` (which is a Windows version of `kill -s SIGUSR1 <node-pid>`) in a separate instance of Node.

The call succeeds (doesn't throw an error), but doesn't print out information like this:
```
Debugger listening on ws://127.0.0.1:9229/cf49bcfe-d922-4f89-b438-57755d254198
For help see https://nodejs.org/en/docs/inspector
```

The above lines are printed out upon successful attachment to other running Node processes.

Because this is not printed out, I cannot know what port and UUID to use to connect to the debugger using CDP.

When I run the above and then scan all open ports of `127.0.0.1` and issue `http://127.0.0.1:<port>/json/list` against all of them, I do not find any open port where this URL (which is the same as `chrome://inspect`) returns a list of targets containing a VS Code instance.

Is it possible to attach a debugger to an existing VS Code instance and connect to it using CDP?

**Comment by auchenberg** [comment]
@TomasHubelbauer Are you trying to debug an instance of VS Code itself or a Node process?

**Comment by auchenberg** [comment]
@TomasHubelbauer I'm still not sure whether you are trying to debug VS Code itself or another Electron app. We have a debugging recipe for how you can debug both the main and renderer process of Electron apps here: https://github.com/Microsoft/vscode-recipes/tree/master/Electron

In general for all Electron apps (including VS Code itself) it's not possible to put the process into debug mode via SIGUSR1. This is tracked here https://github.com/electron/electron/issues/11287

**Comment by TomasHubelbauer** [comment]
I am trying to debug VS Code itself, not any other Electron app. I then switched to using a barebones Electron app first to make sure I have basic working repro, but I was not succeeding either which leads me to believe I should open this with Electron so I did: electron/electron#13580.

`process._debugProcess` is a Windows version of `SIGUSR1` as mentioned in my first comment.
