### ISSUE TITLE
workbench.main.css overwrites custom theme

### ISSUE THREAD

**Issue by tweakimp** [Microsoft/vscode#53787]
With `"window.titleBarStyle": "custom"` the right click menu is themed after `workbench.main.css`, overwriting the custom colors I chose in the `theme.json`.

Screen from the computed styles of the `<div>` of a right click menu:
![screen](https://i.imgur.com/13XkMzA.png)

How can I theme the right click menu?

VSCode Insider 1.26.0

**Comment by sbatten** [comment]
tracking here #52914
