### ISSUE TITLE
New settings editor: SelectBox cannot expand if near bottom of window

### ISSUE THREAD

**Issue by mrg0lden** [Microsoft/vscode#53780]
VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.17134

Steps to Reproduce:
(precisely)

1. type "menu bar" in the search field
2. go to the last one
3. you won't be able to select any choice because selections are hidden 

Does this issue occur when all extensions are disabled?: Yes
 A GIF demonstrates the issue:
![vscode](https://user-images.githubusercontent.com/8347078/42410892-61c6720e-81fa-11e8-9531-18f06ee8d28c.gif)

**Comment by cleidigh** [comment]
@roblourens 

This is the result of the select box constraint for a bottom margin.  I have an option to set this different from the default , I just have to see if this is the best way to fix it or if I have to add a little more intelligence.

The select box  could open to the top but I have to see if the context view can be forced.

Auto scrolling up might be a possibility not sure what you think?

**Comment by roblourens** [comment]
I don't know what the history is, but I would assume that if there isn't room at the bottom, it would open upwards.

@bpasero

**Comment by cleidigh** [comment]
@roblourens 
Yes, the drop-down should flip up.  I just have to figure out the best way to handle the margins.

**Comment by cleidigh** [comment]
@mrg0lden 
Thanks for the catch!

**Comment by mrg0lden** [comment]
@cleidigh The least I can do to improve my favorite editor!
