### ISSUE TITLE
VSC on Centos keeps asking me to install extentions that I already have

### ISSUE THREAD

**Issue by grimmjow-sms** [Microsoft/vscode#53784]
- VSCode Version: 1.25.0
- OS Version: Centos 7

Steps to Reproduce:

1.Install VSC and then install the Go extension: Go Rich  go language support.... 
2.Try to code something with Golang code and try to save.

When trying to save a go file, a popup window appears and says that I need to install something else
![imagen](https://user-images.githubusercontent.com/35404896/42412585-b0c30280-81d4-11e8-8ebf-848eb7357a67.png)

Then I hit install all, and the installation process starts and says it successfully installed 10 tools 
![imagen](https://user-images.githubusercontent.com/35404896/42412604-07fb9bd4-81d5-11e8-8b8f-27e4357587af.png)

Then I go back to a code window, and the popup keeps showing up
![imagen](https://user-images.githubusercontent.com/35404896/42412612-2fa4ff90-81d5-11e8-8014-7cba103e41e2.png)

I must add, that even when I have the Go extension Installed and Enabled, I have barely seen the auto filling when I am coding. I have to type every single word

Regards

Does this issue occur when all extensions are disabled?: No

**Comment by jluisgarcia** [comment]
I just detected this issue.

**Comment by ramya-rao-a** [comment]
This issue was moved to Microsoft/vscode-go#1781
