### ISSUE TITLE
Change VS Play button behavior  

### ISSUE THREAD

**Issue by DeanKamali** [Microsoft/vscode#53786]
Wondering if it is possible to change play button behaviour, in which I can program it to run my node server with user-defined parameters. 

![screen shot 2018-07-07 at 1 35 12 pm](https://user-images.githubusercontent.com/1252959/42413253-9ab3196a-81ea-11e8-86fb-baea096f5d2b.png)

Would be nice to change play to stop when the server is running.

**Comment by weinand** [comment]
@DeanKamali What play button is this?

**Comment by DeanKamali** [comment]
In my VS code, I'm seeing a play button top right corner of the screen, when pressed it runs whatever code is open in active tab. 

Now I'm wondering if it came with VS code, or one of the plugins I installed. 

![screen shot 2018-07-07 at 7 00 49 pm](https://user-images.githubusercontent.com/1252959/42415318-36697250-8218-11e8-8339-1f4f08dfc6f0.png)

**Comment by arafatamim** [comment]
I think that play button comes with the Code Runner extension.

**Comment by weinand** [comment]
@DeanKamali yes, most likely this is the 'Code Runner' extension.
That proves that you create your own extension that adds a run button for starting your node server.
