### ISSUE TITLE
Visual Code does not show TS errors in Problem panel if I stopped a tsc build in watch mode and restart it

### ISSUE THREAD

**Issue by ajayindfw** [Microsoft/vscode#53783]
Here's the scenario:

I open a Visual Studio code project and start up the build task using "Run Build Task" menu in Visual Code.  I havae a tasks.json file in the root of my TS project which looks like:
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "type": "typescript",
            "tsconfig": "app/tsconfig.json",
            "option": "watch",
            "problemMatcher": [
                "$tsc-watch"
            ]
        }
    ]
}
```

the project also has a base tsconfig.base.json that tsconfig.json in apps/ refers to:

```
{
  "compilerOptions": {
    "target": "es5",                         
   "sourceMap": true,
  "noImplicitAny": true,
    "watch": true ,
    "outDir": "js",
    "strictNullChecks": true
  }
}
```

The build runs just fine in watch mode when I run the build after opening the IDE.  Any TS errors show up both in the Terminal Window and are also reported in the Problems panel.   However, if say I make a change to a compiler option in base tsconfig.base.json and restart the build, any errors are not reported in the problems panel.

**Comment by dbaeumer** [comment]
This works for me if I terminate the watch task and restart it. 

However I noticed that the interal compiler (TypeScript extension) doesn't reflect the changes.

**Comment by dbaeumer** [comment]
@mattbierner assigning to you. Not sure if this needs to be forwarded to TS.

**Comment by mjbvz** [comment]
Looks like the original issue was resolved.

https://github.com/Microsoft/TypeScript/issues/17753 tracks the issue where you have to save the child `tsconfig` for changes to the base to be picked up
