### ISSUE TITLE
Anti-breakpoints, to ignore certain exceptions when "all exceptions" is checked in the debugger

### ISSUE THREAD

**Issue by AmeliaBR** [Microsoft/vscode#53795]
Issue Type: <b>Feature Request</b>

When working with build chains that catch and re-throw exceptions from my scripts, I often need to check the "Break on all exceptions" (instead of only on uncaught exceptions) option in order for the debugger to break at the point of the original exception, with the correct call stacks and scopes. But then the script breaks on all sorts of well-handled exceptions elsewhere in the build, too.

It would be useful if I could mark these well-handled exceptions to be excluded from the "All exceptions" option.

I am picturing something similar to breakpoints, that you would assign to a line of code, but which would indicate "don't break here, even if there is an exception".  There could also be conditional anti-breakpoints, but the condition would only be evaluated if an exception would cause a break on that line, and would determine whether or not to actually break.

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.17134

**Comment by weinand** [comment]
You can try to use the "skipFiles"  option for this 
(see https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_skipping-uninteresting-code-node-chrome)

Under skipping rules you find this:
> If you have set the option to break on thrown exceptions, then you won't break on exceptions thrown from skipped files.
