### ISSUE TITLE
Multiple Lines(Non-html) of flask-templates Combining to a single line

### ISSUE THREAD

**Issue by srk1195** [Microsoft/vscode#53799]
Issue Type: <b>Bug</b>

What I need to see is below after saving also.
```
{{ render_field(form.email, placeholder=form.email.label.text) }}
{{ render_field(form.password, placeholder=form.password.label.text) }}
{{ render_field(form.textarea) }} 
{{ render_radio_fields(form.radios) }}
```

But what i always get all of them into a single line and it's very annoying and disturbing.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:52:25.282Z)
OS version: Windows_NT ia32 10.0.17134

<details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
Happy-Flasker|ape|0.0.6
django|big|1.0.0
flask-snippets|cst|0.1.0
vscode-mysql|for|0.3.0
beautify|Hoo|1.3.2
vscode-JS-CSS-HTML-formatter|lon|0.2.3
python|ms-|2018.6.0
java|red|0.28.0
bootstrap4-vscode|the|4.1.1
vscode-java-debug|vsc|0.10.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.7.0
vscode-maven|vsc|0.9.0
jinja|who|0.0.8
html-css-class-completion|Zig|1.17.1

</details>

**Comment by aeschli** [comment]
I assume you use the HTML formatter to format your template language.

The HTML formatter isn't aware of the syntax of your language. You can:
- look in the market place if there is a better formatter, maybe even a formatter specifically for your language
- configure the HTML formatter not to format the content to certain elements. Check out the `"html.format.contentUnformatted"` setting.
