### ISSUE TITLE
I hope to open vscode by vocode in console like sublime

### ISSUE THREAD

**Issue by biij5698** [Microsoft/vscode#5379]
we can open subime like this:sudo subl in sonsole,but vsocde can not,I hope vscode can be opened in console like: sudo vscode

**Comment by BillyONeal** [comment]
Did you try the command "code"? (That's how it registers itself on Windows at least)

**Comment by biij5698** [comment]
yes it can,very good! thank you!

**Comment by biij5698** [comment]
It can be opened by wrtie code in console in linux,very good!

**Comment by bachstatter** [comment]
Is there any way to open insiders build through the terminal?

**Comment by Tyriar** [comment]
@bachstatter `code` for stable and `code-insiders` for insiders. You can create an alias if you want something shorter if insiders is your daily driver:

```bash
alias c='code-insiders'
```

**Comment by biij5698** [comment]
@bachstatter No,there is no way to open insiders buid through the terminal

**Comment by biij5698** [comment]
But on windows it can

**Comment by Tyriar** [comment]
@biij5698 you should be able to launch from the terminal on all platforms:

- On Windows you need to check add code to PATH in the installer
- On Linux you need to install via a .deb or .rpm package (or setup a symlink manually)
- On Mac you need to install the command to PATH via the command palette (<kbd>F1</kbd>) from within the editor.

**Comment by biij5698** [comment]
@Tyriar what is via and how to get it?

**Comment by Tyriar** [comment]
Via means "with" in this case. You can download deb and rpm files from the homepage
