### ISSUE TITLE
Typescript suggestions on js files by default

### ISSUE THREAD

**Issue by marcus13345** [Microsoft/vscode#53794]
The file pictured is in a workspace with no typescript files. I have typescript installed and enabled, but it seems absurd that vscode would run the linter on files so clearly not meant to be typescript.

![image](https://user-images.githubusercontent.com/6365746/42414744-281d6534-820a-11e8-89d9-a42fb40ea90e.png)

I should point out how this is different from the similar issue, #47299 which refers to specifically the pictured linting suggestions, whereas I am referring to the typescript linter running on the file in the first place.

**Comment by mjbvz** [comment]
TypeScript powers js intellisense as well. You can disable these hints by setting `"javascript.suggestionActions.enabled": false`
