### ISSUE TITLE
clear running terminal

### ISSUE THREAD

**Issue by BenDietze** [Microsoft/vscode#53790]
![image](https://user-images.githubusercontent.com/39699022/42413693-d1d01804-8225-11e8-8709-ad7b4657e1a1.png)

I am mostly logging some console output to terminal / splitted terminals (for reading raw HTML output instead of reloading a browser every time for example - and many other strings), but while this i cannot clear the terminal buffer. I must always scroll line for line and search for beginning of my last output when doing an new output. So it would be very very nice if i could clear / reset the terminal simply without killing it :)

Were great if it can be added as per click 💯 

Would be useful for splitted terminals in separate manner.

Thank you

**Comment by Tyriar** [comment]
You can clear the terminal with cmd+k on mac and ctrl+k on Windows. Also on mac there are default keybindings for jumping to the last command run (cmd+up). You can set this up on other platforms with a keybinding like this:

```json
{ "key": "ctrl+up",               "command": "workbench.action.terminal.scrollToPreviousCommand",
                                     "when": "terminalFocus" },
```

**Comment by BenDietze** [comment]
Thank you very much for your unbelievable fast response 👍 

but keybindings as only way are a little bit limited.

They will often be used by extensions and one must permanently check for all needed bindings :/
For me, in this case, an extension with bindings for `CTRL+` `K`, `H` blocked it but itself doesn't react on `CTRL+` `K` ? Is it a bug? While thinking about - i have had this every time installing this extension the last 1 - 2 years. (tht13.html-preview-vscode)

_Clearing_ is one of most needed options and there is nothing similar at terminal tab.

I understand its a little bit tricky because the split-mode.

**Comment by Tyriar** [comment]
@BenDietze ctrl+k is a special keybinding because of the chord keybindings, if this broke you can ready why and how to fix it on the FAQ https://code.visualstudio.com/docs/editor/integrated-terminal#_common-questions
