### ISSUE TITLE
F4 to find next search result works once only 

### ISSUE THREAD

**Issue by flowt-au** [Microsoft/vscode#53792]
Issue Type: <b>Bug</b>

1. Search in files for something ==> list of results in side bar
2. Press F4 ==> first result is highlighted in the editor pane
3. Press F4 for next result and instead of jumping to that match it opens the find panel in the editor pane (the one we use to search within a file)

If I click in the Search box in the side panel before each F4 press it does take me to the next match. ie I need to keep shifting the focus back to the search box. I might as well click the search result! :-)

I also notice that I can press down arrow to go through the items. That does the job.

Thanks.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
OS version: Darwin x64 14.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|20%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
minify|Hoo|0.3.0
Bookmarks|ale|0.19.1
cucumberautocomplete|ale|2.11.0
vscode-sublime-importer|auc|1.0.1
vscode-eslint|dba|1.4.12
rest-client|hum|0.19.0
coldfusion|ili|1.0.1
sublime-keybindings|ms-|4.0.0
vetur|oct|0.12.5

</details>

**Comment by roblourens** [comment]
Most likely you have a custom keybinding that's conflicting with F4, can you doublecheck?

**Comment by flowt-au** [comment]
OK, I understand. I will dig into that. I am using the Sublime Text Keymap so maybe that has introduced a conflict. I will uninstall it and compare values. I will report back.

**Comment by roblourens** [comment]
It looks like the Sublime keymap does overwrite F4 for editor find.
