### ISSUE TITLE
Not recognize the @tailwind directive in CSS (Taildwindcss Framework)

### ISSUE THREAD

**Issue by nencode** [Microsoft/vscode#53797]
Hi!
In the new version of VSCode (1.25.0) does not recognize the @ tailwind directive. This prevents you from recognizing some CSS properties and the html page is displayed incorrectly. With version 1.24 that does not happen.
![tailwindcss](https://user-images.githubusercontent.com/40928091/42416559-faf2d806-823f-11e8-92d6-2301d58501ab.JPG)
![grabacion_2018_07_07_23_06_57_512](https://user-images.githubusercontent.com/40928091/42416561-ffe7e63a-823f-11e8-8dc5-0abc58f315b0.gif)

**Comment by nencode** [comment]
After many tests: POSTCSS and STYLUS syntax highlighter, removes warnings but CSS Intellisence is incomplete, does not show the first-utitilies classes Tailwind
![css](https://user-images.githubusercontent.com/40928091/42539242-878f2218-8468-11e8-9520-cc360c254ff5.jpg)

**Comment by octref** [comment]
PostCSS and Stylus are supported via extensions and you should file issues for them.

**Comment by nencode** [comment]
Cool!
Thanks!
