### ISSUE TITLE
Debug Launch Cfgs/selectBox:  Duplicate option names allowed-cause issues

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#53791]
OS - Platform independent
VSC 1.25 \ exists in prior versions also

Related:  #46011

The Debug Configuration editor for launch.json allows entries
with the same name.  I'm not sure this was originally intentional
but it is not prevented.  The Debug Launch Configurations DropDown/selectBox
(and all selectBox instances) also allow for options with the same name.

The problem arises when selecting an option in the selectBox that has
another duplicate named option.  The debugActionItems.ts UpdateOptions() walks the named options
list and sets the selected index to the last option with the same name,
not necessarily what the user selected.

https://github.com/Microsoft/vscode/blob/cd1969b4eae58c02ed7a48c212a6f278a10599fc/src/vs/workbench/parts/debug/browser/debugActionItems.ts#L155-L168

The terminal code that handles the terminal selectBox adds the index
as a prefix to the name so the user can duplicate names that can still be
distinguished both within the select box as well as the code.

I'm not sure if it's intended to support duplicate options, but right now
they cause some issues.  The selectBox is capable if necessary.

Does this issue occur when all extensions are disabled?: Yes

Steps to reproduce:

1. SetUp launch configurations with a duplicate name similar to screenshot
2. Open Debug configurations DropDown , select "Launch Cfg 2"
3. Reopen Debug configurations DropDown , "Launch Cfg 2" should be correctly selected
4. Select the first "Launch Cfg 1"
5. Open Debug configurations DropDown , Note: last "Launch Cfg 1" is selected, 
   not the first that was previously selected.

@weinand : feel free to task me on this with direction

![image](https://user-images.githubusercontent.com/25272315/42414811-00e694fc-820c-11e8-9c3a-4789d3197a0c.png)

**Comment by isidorn** [comment]
@cleidigh yes we currently allow duplicate names to be in the debug launch dropdown.
Only once the debug session is started we report an error to the user.
I currently do not mind the behavior - and the issue that the wrong one is selected (user will be notified soon about the need to de-dup and he will take some action).
Due to the above I prefer not to do anything here. Though I am open for suggestions if you have an elegant solution

**Comment by cleidigh** [comment]
@isidorn 
I did not realize that you do catch the duplicates on debug launch.  I agree that should be enough
after all it is the user 's fault :-)

I will go ahead and close.
