### ISSUE TITLE
The IntelliSense gets triggered even in comments

### ISSUE THREAD

**Issue by hashhar** [Microsoft/vscode#538]
This is both useful and bad depending on situations. But mostly undesirable. Maybe add a config value to control this as well?

**Comment by bpasero** [comment]
Also really don't like it, @jrieken ping.

**Comment by jrieken** [comment]
We currently don't know what a comment is. As soon as we know, we can make this change happen.

**Comment by hashhar** [comment]
I think it could be done, as easy as checking if the current line has a comment opening character. And i believe you do know the comment characters because the `ctrl +/` command inserts and removes it.

Or maybe not. Things sound very easy but writing it into code is difficult.

**Comment by jrieken** [comment]
```
/*
sorry but will not work |<ctrl+space>
*/
```

We need to expose the scopes the tm-bundles define, it's on our plan but we are not there yet.

**Comment by hashhar** [comment]
Great. Thanks for looking into it.
I believed the facilities for the languages supported out of the box was inbuilt.

**Comment by jrieken** [comment]
We have made the default intellisense provider less aggressive. There is currently no plan to extract that in it's own plugin but when that happens user can decided to install or not. Not planning further work on this.

**Comment by hashhar** [comment]
I saw it. Works a lot better now and is more helpful. Thanks for looking into this.

**Comment by pspi** [comment]
Reopen since it's not fixed?
