### ISSUE TITLE
Menus are not dismissed when clicking elsewhere on custom titlebar

### ISSUE THREAD

**Issue by myandrienko** [Microsoft/vscode#53809]
Issue Type: <b>Bug</b>

With `window.titleBarStyle` set to `custom` and having a menu open, clicking elsewhere on a titlebar doesn't dismiss the currently opened menu.

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.17134

**Comment by sbatten** [comment]
duplicate of #52912
