### ISSUE TITLE
Image not displaying in extension details

### ISSUE THREAD

**Issue by chinchiheather** [Microsoft/vscode#53804]
Issue Type: <b>Bug</b>

I have an image in my extension's readme, a status badge for my project's latest CircleCI build. This displays correctly when I view the readme on github (and in incognito), but in VS Code it shows as a broken image.

My extension is vscode-margin-colours, reproduce by finding in the Extensions tab within VS Code and see the broken image right at the top of the details page. View my project on github https://github.com/chinchiheather/vscode-margin-colours to see the image loads.

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:02:28.333Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.74GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-margin-colours|chi|1.2.1
vscode-eslint|dba|1.4.12
githistory|don|0.4.1
gitlens|eam|8.4.1
tslint|eg2|1.0.33
auto-close-tag|for|0.5.6
vscode-styled-components|jpo|0.0.20
PowerShell|ms-|1.7.0
quokka-vscode|Wal|1.0.132
vscode-todo-highlight|way|0.5.12

</details>

**Comment by chinchiheather** [comment]
I have another image in there though that is coming from another domain https://chinchiheather.github.io/vscode-margin-colours/img/demo-low-rate.gif and this loads fine?

**Comment by joaomoreno** [comment]
Interesting... let me check.

**Comment by joaomoreno** [comment]
@mjbvz I verified that we are indeed blocking the request, but I can't find the code point where that happens...

**Comment by mjbvz** [comment]
We only allow svgs from certain trusted domains. We can add circleci to that list

**Comment by mjbvz** [comment]
Should be fixed in the next VS Code insiders build

**Comment by chinchiheather** [comment]
Awesome, thank you! :)
