### ISSUE TITLE
Crashes gnome

### ISSUE THREAD

**Issue by paperbenni** [Microsoft/vscode#53802]
Issue Type: <b>Bug</b>

Problem: I stopped using vscode for a while and my pc stopped crashing randomly. I'm not implying that it crashes gnome, but it's a really strange coincidence...

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:10:37.273Z)
OS version: Linux x64 4.15.0-24-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700 Eight-Core Processor (16 x 1428)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 0|
|Memory (System)|15.68GB (9.07GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.18.0
beautify|Hoo|1.3.2
vscode-docker|Pet|0.0.27
cform|aws|0.0.10
vscode-eslint|dba|1.4.12
vscode-gist|dba|1.0.0
gitlens|eam|8.4.1
vscode-language-pack-de|MS-|1.25.2
vsliveshare|ms-|0.3.379
java|red|0.28.0
bash-debug|rog|0.2.0
bash-beautify|sha|0.1.1
shellcheck|tim|0.5.1
vim|vsc|0.14.2
markdown-all-in-one|yzh|1.5.1

(2 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
Please check with the vscode process explorer if any process is going crazy (see https://github.com/Microsoft/vscode/wiki/Performance-Issues#visual-studio-code-is-consuming-a-lot-of-cpu)

**Comment by paperbenni** [comment]
I haven't had crashes in a while now, seems to be fixed. :)
