### ISSUE TITLE
Menus shouldn't have fade-in animation

### ISSUE THREAD

**Issue by myandrienko** [Microsoft/vscode#53808]
Issue Type: <b>Bug</b>

When `window.titleBarStyle` is set to `custom`, menus get fade-in animation on appearence. This animation should either be optional, or much faster, or disabled. Fade-in animation makes menus fill laggy and unresponsive.

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.17134

**Comment by sbatten** [comment]
Thanks for your feedback. I will update the behavior in the menubar as native context menus in windows do have a fade-in animation, but the native menubar does not.
