### ISSUE TITLE
How do I select visible (uncollapsed) code in Visual Studio Code?

### ISSUE THREAD

**Issue by virtualgithub** [microsoft/vscode#53800]
Once I collapse a piece of code I need to select the uncollapsed part of the file. I tried CTRL + A and also using the mouse manually selecting what is visible, but both methods copy the whole file, even the code that is hidden. Is this impossible to achieve?

**Comment by aeschli** [comment]
We don't have that functionality...

**Comment by navdotnetreqs** [comment]
Still no?
