### ISSUE TITLE
Can VS Code be used for commercial purpose ?

### ISSUE THREAD

**Issue by user-mk** [Microsoft/vscode#53807]
Can VS Code ( downloaded from https://code.visualstudio.com/ ) be used for commercial purpose ?

I am not talking about the github source code. The source code on github is MIT licensed but what about the commercial usage of the VS Code Editor i install on my machine ( whether mac or pc ) that's downloaded from https://code.visualstudio.com/ ? 

Regards,
MMK.

**Comment by lhb94** [comment]
Yes. But this isn't the place to be posting this question.
