### ISSUE TITLE
Integrated Terminal with Zsh on macOS displays every command before it is run

### ISSUE THREAD

**Issue by consen** [Microsoft/vscode#53805]
Issue Type: <b>Bug</b>

My vscode integrated terminal shell is Zsh(with Oh-My-Zsh), every command in the integrated terminal is displayed to the screen before it is run. 

![image](https://user-images.githubusercontent.com/2787272/42418968-1ad18cbe-82de-11e8-9692-e03090537a1b.png)

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:02:28.333Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.30GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.25.3
python|ms-|2018.6.0
cpptools|ms-|0.17.6
java|red|0.28.0
vscode-icons|rob|7.24.0
vscode-java-debug|vsc|0.10.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.7.0
vscode-maven|vsc|0.9.0

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Does it repro if you switch to bash?

**Comment by consen** [comment]
No, it works well with bash.

**Comment by Tyriar** [comment]
@consen could you try setup the xterm.js demo and see if it reproduces over there? https://github.com/xtermjs/xterm.js/wiki/Contributing#linux-or-macos

After you get it setup you can enable debug move and view exactly what is being sent to the terminal by the pty. This will help identify at which point the problem is occurring. https://github.com/xtermjs/xterm.js/wiki/Contributing#enabling-debug-mode
