### ISSUE TITLE
opening file via URL handler always opens file in new window #4883

### ISSUE THREAD

**Issue by sarim** [Microsoft/vscode#53818]
Issue Type: <b>Bug</b>

1.  Opening a url like `vscode://file/c:/myProject/package.json:5:10`
2.  While the file is open in vscode, open the same url again.
3.  Another vscode window opens with the same file.

Frameworks like symfony can generate a url when showing an error/exception, clicking the url takes you to the offending file and line in your editor. Opening the file in a new window again and again defeats the purpose of this feature as i want it to open it inside already opened project window.

Please notice third party solution using `-g` and `-r` flag to `code.exe` does not have the same problem.
Ex: https://github.com/shengyou/vscode-handler/blob/master/VS%20Code%20Protocol/run_editor.js#L8

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.89GB (5.66GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
reg|ion|0.0.2
dotenv|mik|1.0.1
remote-vscode|raf|1.1.0
vscode-nginx|sha|0.5.0
twig|wha|1.0.2

</details>

**Comment by joaomoreno** [comment]
I cannot reproduce this. Both when the file is open or otherwise, it never creates a new window in my setup. Can you show me your full settings?

**Comment by sarim** [comment]
@joaomoreno check this https://streamable.com/c7yij

Here you can see composer.json is open already. But it opens new window again and again when opening via url handler.

@bpasero What configuration? Searching the default configuration i found these ones. I haven't edited any of these as you can see in the screen capture above. Still its opening in new window.
```js
  "window.openFilesInNewWindow": "off",
  "window.openFoldersInNewWindow": "default",
  "window.openWithoutArgumentsInNewWindow": "on",
```

**Comment by sarim** [comment]
Just adding another info, running 
```sh
code --open-url -- "vscode://file/C:/Users/Sarim Khan/Documents/hoboard/composer.json:50:0"
```
from powershell does  the same. Opens a new window every time.

**Comment by joaomoreno** [comment]
Still can't repro with that command line, thought it's good to know it does for you.

Can you show me your full user settings?

**Comment by sarim** [comment]
Sorry, my bad. Problem solved.

```js
"window.openFilesInNewWindow": "default"
```

This was the offending config. It was set to `"default"`. Setting it to `"off"` solves this issue. [setting it to `"off"` raises another ux issue with vscode-remote extension, but thats outside of this topic]
