### ISSUE TITLE
Now, Jade has been renamed to Pug

### ISSUE THREAD

**Issue by mizunashi-mana** [Microsoft/vscode#5381]
- VSCode Version: 1.0.0
 - OS Version: Windows 10

Steps to Reproduce:
 - Open any pug file without syntax highlighting

**Unfortunately**, Jade has been renamed to Pug (ref: https://github.com/pugjs/pug/issues/2184).
We should change `jade` to `pug` on all documents, extensions and supports...

Do you have any plans?

**Comment by mizunashi-mana** [comment]
P.S. I left a solution regarding syntax highlighting on this issue for all vscode and pug user.

Add your User settings (`Command Palette` -> `Preferences: Open User Settings` -> edit settings.json) such as:

```json
"files.associations": {
  "*.pug": "jade"
}
```

**Comment by egamma** [comment]
@gregvanl can you update the doc accordingly.
@aeschli I suggest we support both the `.pug` and `.jade` file associations.

**Comment by bgse** [comment]
Definitely keep supporting the now-legacy .jade associations, there is a lot of code floating around still including the old jade.

**Comment by aeschli** [comment]
- added the '.pug' file association
- once the new name is established and e.g. the pug-lang.com website is up and ready, we can also rename the extension, the label and the language id.

**Comment by Jack-Works** [comment]
Um, so what about do the same here?
https://github.com/Microsoft/vscode/blob/2f76c44632b0d47ba97f66fbc158c763628e30b3/extensions/jade/syntaxes/Jade.json#L5
Change it to "name": "Pug" or something

**Comment by aeschli** [comment]
Also renamed extension and label. Kept languageID for backward compatibility. See #18219
