### ISSUE TITLE
VSCode locks internet connection on ubuntu

### ISSUE THREAD

**Issue by fssrepository** [Microsoft/vscode#53814]
When i'm closing down VSCode on latest ubuntu (16.4 - not the 17.10) there are many process remains in the background, especially the Microsoft one blocks my internet connection. (after killing the process, i'm able to browse the net again on chrome)

I have a wifi connection, which not that stable. Ubuntu has problems with connection handling, but i think VSCode hasn't implemented some sort of "pending" state feature.

**Comment by jrieken** [comment]
Please use the process explorer (as described here https://github.com/Microsoft/vscode/wiki/Performance-Issues#visual-studio-code-is-consuming-a-lot-of-cpu) to know what processes are leaking

**Comment by fssrepository** [comment]
It would take some time to recreate, but i will do, if it happens.

**Comment by jrieken** [comment]
Ok, it'll be helpful for us.
