### ISSUE TITLE
Request: Light/Dark theme switching based on ambient light sensor

### ISSUE THREAD

**Issue by AdamBrodzinski** [Microsoft/vscode#53817]
It would be amazing if VS Code could switch to a light or dark theme based on my ambient light sensor for those times when a dark theme is not usable on full brightness. This would save a lot of time switching between themes if you spend time outside vs inside for example.

I'm not sure how much data the sensor provides and if it's able to detect massive shifts in brightness (an extreme example, inside a basement vs on a beach).

**Comment by aeschli** [comment]
Interesting idea, why not implement this idea as an extension? The current theme is a setting that can be changed through the extensions API.

https://www.npmjs.com/package/ambient-light-sensor seems to provide a way to access the sensor.
