### ISSUE TITLE
History of searches/replacements in search/replace dialog

### ISSUE THREAD

**Issue by spacepille** [Microsoft/vscode#53810]
![image](https://user-images.githubusercontent.com/11977563/42421759-3ef270d4-82db-11e8-9e2d-7b8d5664a82d.png)

A history of last n searches in the search dialog and additionally of last n replacments in the replace dialog would be very helpful. Thank you.

**Comment by roblourens** [comment]
You can navigate through search/replace history with the arrow keys (or alt+arrow keys in 1.24 and before).
