### ISSUE TITLE
Allow terminal/debug pane to be moved around as flexibly as a regular document window

### ISSUE THREAD

**Issue by ogrotten** [Microsoft/vscode#53819]
Currently

```
+--------+--------+
|        |        |
|  doc1  |  doc2  |
|        |        |
|        |        |
+--------+--------+
| Term            |
+-----------------+
```
With most of the space on the right half of the terminal being wasted.
With the flexibility of a regular document window, people could put it wherever was best for their particular style/needs.

Even without the added flexibility, I'd most like to see the option for it to go to 

```
+--------+--------+
|        |        |
|  doc1  |  doc2  |
|        |        |
|        |        |
|        +--------+
|        |  Term  |
+--------+--------+
```

PS: I'm probably breaking protocol of some sort. . . my boxes were unreadable without http://asciiflow.com/, which I discovered specifically because of this post.

**Comment by Tyriar** [comment]
Terminal specifically is tracked in https://github.com/Microsoft/vscode/issues/10546. @isidorn not sure if you have an issue tracking for the panel?
