### ISSUE TITLE
The npm task detection didn't contribute a task for the following configuration

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#53822]
- Clone https://github.com/microsoft/vscode-chrome-debug-core
- Press cmd+shift+b
- Tasks output channel appears with the following error

```
Error: The npm task detection didn't contribute a task for the following configuration:
{
    "type": "npm",
    "script": "watch",
    "isBackground": true,
    "problemMatcher": "$gulp-tsc",
    "group": {
        "kind": "build",
        "isDefault": true
    }
}
```

- This has worked fine until I just updated Insiders

**Comment by dbaeumer** [comment]
This works for me

![capture](https://user-images.githubusercontent.com/1931590/42530277-a145f444-8435-11e8-8e42-a5c3cf472358.png)

Did you miss to run npm install or something so that the task can't be auto detected.

**Comment by roblourens** [comment]
Today it works 🤷‍♂️
