### ISSUE TITLE
Error normalizing log message to internal format Can't convert string from native encoding to 'UTF-8'

### ISSUE THREAD

**Issue by hulkhub** [Microsoft/vscode#53826]
Commit the code is fail, commit message has Chinese, how to resolve it?

**Comment by joaomoreno** [comment]
Can you elaborate on what the issue is? What platform, Code version? What steps do you do? What is the expected result? What is the actual behavior?

Please read our guide about [Submitting Bugs and Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).

**Comment by hulkhub** [comment]
I have solved it. : )

**Comment by joaomoreno** [comment]
How did you solve it?
