### ISSUE TITLE
Python使用TensorfFlow框架时。语法提示不合理

### ISSUE THREAD

**Issue by OneiroXL** [Microsoft/vscode#53825]
Issue Type: <b>Feature Request</b>

使用tensorflow框架里面的函数时，编译器报
{
	"resource": "/G:/Study/Python/TensorFlow/Demo/TensorFlow.py",
	"owner": "python",
	"code": "E1101",
	"severity": 8,
	"message": "E1101:Module 'tensorflow' has no 'matmul' member",
	"source": "pylint",
	"startLineNumber": 11,
	"startColumn": 5,
	"endLineNumber": 11,
	"endColumn": 5
}
错误。
![image](https://user-images.githubusercontent.com/18098263/42426554-58e67b90-835b-11e8-9c5d-0114b033d62d.png)

但实际是该函数是存在的，语法格式也是正确的，而且程序可以正常运行
![image](https://user-images.githubusercontent.com/18098263/42426573-7b426e10-835b-11e8-86e4-a2827a883513.png)

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

 # #

**Comment by mnikn** [comment]
@OneiroXL have you installed any extensions? btw, please use English and I don't think the Issue type is "Feature Request".

**Comment by OneiroXL** [comment]
First of all, thank you,I didn't use English because my English was poor.
The extension should be installed,Grammar tips are yes.
![image](https://user-images.githubusercontent.com/18098263/42434798-015b63aa-8387-11e8-9457-0e09d873b9d5.png)

After use
![image](https://user-images.githubusercontent.com/18098263/42434903-5f85431a-8387-11e8-8876-62422689c403.png)
