### ISSUE TITLE
Copying text with LF endings stores text with CRLF endings in clipboard

### ISSUE THREAD

**Issue by CephHunter** [Microsoft/vscode#53820]
Copying text with LF line-endings to clipboard gives text with CRLF endings stored in clipboard. For example if i make a new file and set the line ending to LF and type:
```
a
b
```
Then copy this text and paste it in notepad.exe i see
```
a
b
```
However if i save the file and then open the saved file with notepad.exe i see 
```
ab
```
as expected. This still happens with all extensions disabled and is also present in the insiders version.

Environment details:

- VSCode Version: 1.25.0
- OS Version:  Windows 10 Home 1709

Steps to Reproduce:

1. Create or open a file
2. Set the line ending to LF
3. Copy multi line content to clipboard
4. Paste clipboard in notepad.exe

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
I think we did this by purpose https://github.com/microsoft/vscode/issues/22688

**Comment by alexandrudima** [comment]
On Windows, **we always write text with CRLF to the clipboard**, even when selecting from a file with LF end-of-line sequence.

This is slightly incorrect, but causes far less problems than being correct. See #22688
