### ISSUE TITLE
Opening a Ruby file containing Inspec causes Code to freeze in editor pane

### ISSUE THREAD

**Issue by grdnrio** [Microsoft/vscode#5383]
- VSCode Version: 1.0
- OS Version: Windows 10 1511 Build 10586.218

Steps to Reproduce:

1. From powershell run code. in repo directory containing inspec ruby files
2. Click cursor into editor pane

Error pop up: 'This Windows Is No Longer Responding'

**Comment by egamma** [comment]
Can you attach a ruby file that is causing this problem? Can you reproduce the error with other ruby files?

**Comment by dbaeumer** [comment]
Closing.

@grdnrio please ping when the additional information is available.
