### ISSUE TITLE
windows7 专业版vscode 占用cpu过高

### ISSUE THREAD

**Issue by gjfme** [Microsoft/vscode#53846]
新装了windows7 系统，打开vscode时，Code.exe 进程cpu占用率98% 以上，卡死。

**Comment by gjfme** [comment]
My Windows 7 system is newly installed. When the vscode is opened, the Code.exe process has a CPU usage of 98% or more and is stuck.（by  Google Translate）

**Comment by jrieken** [comment]
Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

**Comment by gjfme** [comment]
thank you
