### ISSUE TITLE
Staged changes not showing the correct diff

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#53849]
Issue Type: <b>Bug</b>

Stage a change to a file, and open the diff -- it the change isn't staged it will work, but if it is staged the diff is the same on both sides.

This started in today's insiders build.

VS Code version: Code - Insiders 1.26.0-insider (bbafa06a3d3db60bbd06d4d4cd582586f7126d93, 2018-07-09T05:49:15.364Z)
OS version: Windows_NT x64 10.0.17711

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (16.06GB free)|
|Process Argv|C:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by joaomoreno** [comment]
Will re-release today's build.
