### ISSUE TITLE
Outline view (files.associations)

### ISSUE THREAD

**Issue by coder911x** [Microsoft/vscode#53847]
Issue Type: <b>Bug</b>

Don't work option "files.associations" with Outline View.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 6.1.7601

**Comment by jrieken** [comment]
Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
