### ISSUE TITLE
 Folding icons next to the line numbers are not shown in the nested block

### ISSUE THREAD

**Issue by ryaa** [Microsoft/vscode#53842]
- VSCode Version: Version 1.25.0 (1.25.0)
- OS Version: MacOS High Sierra 10.13.5

Steps to Reproduce:

1. Create .ts file and add multiple enclosed blocks of code
2. Note that starting some level (> 7?) the folding icon is not displayed and folding/unfolding does not work - see attached (note that + icon is not displayed)
Please note that //#region seems to be working

<img width="1366" alt="screen shot 2018-07-09 at 08 31 53" src="https://user-images.githubusercontent.com/3608222/42432482-6af91b9c-8353-11e8-946f-72e87746095f.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Please share the text of the code along with screenshots

**Comment by ryaa** [comment]
Here is the file (just remove .txt extension and open the file in VS Code) and the screenshot.
Note that that there are collapsing icons at the line 1380, 1390, 1411 and no collapsing icon for the line 1400, 1422, 1433 etc.)

[add-multiple-photos-using-preview.spec.ts.txt](https://github.com/Microsoft/vscode/files/2182922/add-multiple-photos-using-preview.spec.ts.txt)

<img width="1062" alt="screen shot 2018-07-11 at 07 13 55" src="https://user-images.githubusercontent.com/3608222/42550375-0ee23b1c-84da-11e8-84e3-389839f6833f.png">

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#25596
