### ISSUE TITLE
vscode stucked frequently

### ISSUE THREAD

**Issue by IIInsomnia** [Microsoft/vscode#53844]
- VSCode Version: 1.25.0
- OS Version: macOS 10.13.5

Steps to Reproduce:

1. open terminal

**Comment by jrieken** [comment]
Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

**Comment by IIInsomnia** [comment]
when open terminal, the vscode stucked will happen

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/53782
