### ISSUE TITLE
Show proper message when there are proxy issues connecting to Market place

### ISSUE THREAD

**Issue by rohel01** [microsoft/vscode#53856]
- VSCode Version: 1.24.1
- OS Version: Ubuntu 16.04 LTS amd64

Steps to Reproduce:

1. Configure proxy and disable strict SSL checking
2. Open the "Extensions" view
3. Start typing in the search bar

Does this issue occur when all extensions are disabled?: Yes

I have configured my vscode to use my employer proxy and I deactivated strict SSL checking. Yet, my extension view is broken. When searching for new extensions, I get the following error

![erreurproxy](https://user-images.githubusercontent.com/9367595/42439798-1f880ffe-8364-11e8-9de7-94f6df8ac553.png)

In the output log windows, no additional information is provided. From the command line, extension installations work perfecltly. 

Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3697)
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwarerasterization: disabled_softwarevideo_decode: unavailable_softwarevideo_encode: enabledvpx_decode: unavailable_softwarewebgl: enabledwebgl2: enabled
Load (avg) | 0, 0, 0
Memory (System) | 15.55GB (11.55GB free)
Process Argv | /usr/share/code/code --unity-launch
Screen Reader | no
VM | 0%

Extension	Author (truncated)	Version
vscode-pandoc	Dou	0.0.8
plantuml	jeb	2.8.2
python	ms-	2018.6.0
markdown-all-in-one	yzh	1.5.1

**Comment by joaomoreno** [comment]
Can you run <kbd>F1</kbd>, `Developer: Toggle Shared Process` and check the network tab in that window while you open the extensions view?

**Comment by rohel01** [comment]
Yes, no network activity is recorded while I search for extensions in the "Extensions" view.

**Comment by rohel01** [comment]
I found an other way to trigger the error:

 1. Open "Quick Open" (Ctrl + P)
 1. Try to install an extension (for example, ``ext install vscodevim.vim``)
 1. Hit Enter

As with the previous procedure, no network activity was recorded during these steps

**Comment by rohel01** [comment]
Ok, sorry for all the noise but there IS network activity. Since a (big) timeout is inolved, I just had to wait long enough. I get both a warnings and an errors. I have attached the logs

[-1531147729880.log](https://github.com/Microsoft/vscode/files/2176685/-1531147729880.log)

**Comment by joaomoreno** [comment]
https://stackoverflow.com/questions/37355890/neterr-insecure-response-in-chrome

Can you try spawning Code with `--ignore-certificate-errors`?

**Comment by rohel01** [comment]
Yes, the error disappears when Code is spawned with `--ignore-certificate-errors`.
Maybe the error message could be improved ?

**Comment by robinhood23rus** [comment]
Same problem on VSCode Version: 1.25.1 OS Version: Ubuntu 18.04 LTS amd64.
--ignore-certificate-errors hides error but extensions list not loading. 

Message from console:
`Failed to load resource: net::ERR_FAILED
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:167 WARNING: Promise with no error callback:53
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:167

"Error↵    at XMLHttpRequest.t.xhrRequest.i.TPromise.t.onerror (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:5320:354
`

**Comment by djbrown** [comment]
I fixed the problem in my Ubuntu 18.04 VM with Code 1.25.1 running in coorporate network behind a proxy.

:x: Previously I had proxy settings configured via `/etc/environment`, User/Workspace Settings and/or program arguments (i.e. `--proxy-server`). But no combination worked.
When trying via GUI from within Code, it seemd to search forever but eventually showed `POST https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery net::ERR_CONNECTION_TIMED_OUT` in the Developer Tools Console.

:ok: I was only able to install extensions via terminal: `code --install-extension <ext>`.

:heavy_check_mark: I had to set the Proxy via the OS GUI settings tool: Settings > Network > Network Proxy. You may restart Code afterwards.

:thinking: Seems like when installing extensions via GUI, Code does not regard any proxy settings other than set by the OS GUI settings tool.
:man_facepalming: Until today I didn't even think of that being an alternative to `/etc/environment`.

**Comment by ramya-rao-a** [comment]
@sandy081 In the last release we added a generic message when we are not able connect to the marketplace. The actual error is printed out to the console as well. This is of course different from when we do connect to the marketplace and zero results are found. I don't believe we can single out the proxy issue from other network issue to provide a dedicated message.

**Comment by sandy081** [comment]
How about seeing Connection time out response and informing the user that there could be proxy issues?

**Comment by sandy081** [comment]
Closing this as there is no action planned to be taken.
