### ISSUE TITLE
Typing has gotten very slow, probably due to large files

### ISSUE THREAD

**Issue by crucialfelix** [Microsoft/vscode#53859]
Issue Type: <b>Performance Issue</b>

There is a folder with many mp3 audio files. This is probably what is causing the slow down.  But the files are not being changed, not loaded into any editor. They are just sitting there. I can't think why 

It's normal (fast) when disabling extensions. It is definitely some extension, but we need some way to quickly identify which one it is. Some performance analysis mode like Atom timecop but for runtime analysis.

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:02:28.333Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.71GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron ./|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   27	   131	  3255	code main
    5	   197	  3260	   gpu-process
    0	   229	  3261	   window (48.csv — textin)
    0	   147	  3262	     extensionHost
    0	    82	  3274	       electron_node htmlServerMain.js 
    0	    49	  3278	       electron_node jsonServerMain.js 
    0	    49	  3265	     watcherService
    0	    49	  3270	     searchService
    4	    98	  3266	   shared-process
   12	   639	  3419	   window (sites/crucial-systems/templates/Artist.js — matterminds)
    0	   262	  3420	     extensionHost
    0	   131	  3435	       electron_node jsonServerMain.js 
    0	    82	  3475	       electron_node eslintServer.js 
    0	   246	  3479	       electron_node electronForkStart.js tsserver.js 
    0	    66	  3489	         electron_node typingsInstaller.js tsserver.js typesMap.js 
    0	    49	  3480	       electron_node tslintServer.js 
    0	    49	  3421	     watcherService
    0	    49	  3425	     searchService
    0	    33	  3705	     terminal
    0	     0	  3706	       /bin/zsh -l
   79	    98	  4436	   window (Issue Reporter)
    0	     0	  4437	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (sites/crucial-systems/templates/Artist.js — matterminds)
|  Window (48.csv — textin)
|    Folder (textin): 1 files
|      File types: csv(1)
|      Conf files:
|    Folder (matterminds): 5698 files
|      File types: md(1585) yaml(1268) mp3(642) json(597) jpg(587) js(374)
|                  JPG(222) scss(168) DS_Store(140) png(43)
|      Conf files: package.json(1) tsconfig.json(1) settings.json(1);
```

</details>
<details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
clipboard-history|Anj|1.0.7
template-generator-vscode|Den|0.4.1
EditorConfig|Edi|0.12.4
vscode-docker|Pet|0.0.27
lorem-ipsum|Tyr|1.2.0
project-manager|ale|8.0.0
vscode-color|ans|0.4.5
django-html|bib|1.2.0
django-snippets|bib|1.1.0
vscode-opennewinstance|chr|0.0.4
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.59
transformer|dak|1.6.0
vscode-eslint|dba|1.4.12
jupyter|don|1.1.4
python-extension-pack|don|1.0.1
xml|Dot|2.3.1
gitlens|eam|8.4.1
tslint|eg2|1.0.33
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.5.0
vscode-open-in-npm|fab|1.0.1
simple-new-file|fay|0.1.0
gc-excelviewer|Gra|2.1.24
vscode-react-typescript|inf|1.0.17
hungry-delete|jas|1.5.0
nbpreviewer|jit|1.0.0
auto-comment-blocks|kev|1.0.1
graphql-for-vscode|kum|1.12.0
node-module-intellisense|lei|1.5.0
restructuredtext|lex|65.0.0
MagicPython|mag|1.0.12
markdown-shortcuts|mdi|0.8.1
rainbow-csv|mec|0.4.2
dotenv|mik|1.0.1
vscode-todo-parser|min|1.9.1
python|ms-|2018.6.0
autodocstring|njp|0.2.1
typescript-hero|rbb|2.3.2
vscode-yaml|red|0.0.13
preview-vscode|sea|1.4.2
git-merger|sha|0.4.1
bash-beautify|sha|0.1.1
vscode-fileutils|sle|2.10.3
vs-code-node-require|tgr|1.2.7
vim|vsc|0.14.2
jinja|who|0.0.8
markdown-pdf|yza|1.2.0
markdown-all-in-one|yzh|1.5.1

(7 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

**Comment by crucialfelix** [comment]
Thanks that was exactly the type of profiling I was looking for. Will use that the next time.

I did use developer tools for a bit and I did isolate it:

```
  "vim.statusBarColorControl": false,
```

Closing, see https://github.com/VSCodeVim/Vim/issues/2166 and https://github.com/VSCodeVim/Vim/issues/2124
