### ISSUE TITLE
no module backtrader

### ISSUE THREAD

**Issue by Quinn-zeng** [Microsoft/vscode#53854]
Issue Type: <b>Bug</b>

I uploaded backtrader successfully. However, when I run my codes, it just shows that no module : backtrader. AND I tried all windows and mac system, I just cannot get graph in visual studio code, I really don't know why. Could you help me to fix this problem? It would be appreciated if you could reply me as soon as you are convenient.

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:02:28.333Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz (4 x 1400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|4.00GB (0.05GB free)|
|Process Argv|/Users/apple/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
django-html|bib|1.2.0
django-snippets|bib|1.1.0
git-easy|bib|1.9.1
jupyter|don|1.1.4
python-extension-pack|don|1.0.1
gitlens|eam|8.4.1
gc-excelviewer|Gra|2.1.24
MagicPython|mag|1.0.12
anaconda-extension-pack|ms-|1.0.0
python|ms-|2018.6.0
debugger-for-chrome|msj|4.7.0
vscode-yaml|red|0.0.13
vscode-icons|rob|7.24.0
python|tht|0.2.3
jinja|who|0.0.8

</details>

**Comment by jrieken** [comment]
Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
