### ISSUE TITLE
IntelliSense should auto-close at the end of the only-suggested-phrase

### ISSUE THREAD

**Issue by ghost** [Microsoft/vscode#5386]
# \- VSCode Version: 0.10.11
- OS Version: Fedora 23, 64bit

Steps to Reproduce:
1. For example I'm typing `method`, and IntelliSense suggests that only one phrase.
2. At the end of `method|` (pipe is the caret), IntelliSense doesn't auto-close. If I need to make new line, I have to type <kbd>Enter</kbd> _twice_: one to close IntelliSense, one to make new line.

I think it should auto close in such scenario.

Thanks, and have a nice weekend  `:-)`

**Comment by csholmq** [comment]
I agree, that is annoying! An auto-close when there is only one matching string sounds like a good idea. Once you've typed out the complete suggestion, it should go away.

**Comment by dbaeumer** [comment]
@jrieken not sure if this is you or @joao. I think @haibison is asking for auto accept if only one element is proposed and fully typed. I was able to reproduce this

**Comment by jrieken** [comment]
To @joaomoreno for reference but I believe the box just closes when you continue typing one more character.

**Comment by haibison** [comment]
@jrieken I understand. But in my case, to make new line, I need to double <kbd>Enter</kbd>. I think it will help if the IntelliSense auto closes in such scenario.

P.S: I filed the issue while working with v0.10.11, but I just reproduced it in 1.0.0.

**Comment by joaomoreno** [comment]
Fixed.
