### ISSUE TITLE
Debug is not working properly

### ISSUE THREAD

**Issue by BalajiSrgm** [Microsoft/vscode#53864]
Issue Type: <b>Bug</b>

I am develop node js app in es6 and try to debug in es5.  when i click before the line number the debug red icon randomly select another line

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:10:37.273Z)
OS version: Linux x64 4.4.0-130-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.71GB (0.89GB free)|
|Process Argv|/usr/share/code/code .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.12
gitlens|eam|8.4.1
graphql-for-vscode|kum|1.12.0
dotenv|mik|1.0.1
vscode-json-transform|oct|0.1.2
json-organizer|rin|0.0.3
vscode-icons|rob|7.24.0
json-to-js-object|sal|0.0.4

</details>

**Comment by weinand** [comment]
What's your debug launch config?
