### ISSUE TITLE
createTerminalRenderer does not exist on type 'typeof window'

### ISSUE THREAD

**Issue by Gamadril** [Microsoft/vscode#53861]
- VSCode Version: 1.25.0
- OS Version: macOS 10.13.5

Seems that the corresponding vscode.d.ts file of v1.25.0 is not reflecting the state of the v1.25 API.

Steps to Reproduce:
1. create a simple extension with `yo code` (Typescript).
2. Add in activate: `const shell = vscode.window.createTerminalRenderer('My Extension REPL');`
3. `npm run compile` shows an error: `error TS2339: Property 'createTerminalRenderer' does not exist on type 'typeof window'.`

However generated JS code works fine.

> Detected VS Code engine version: ^1.25.0
> Found minimal version that qualifies engine range: 1.25.0
> Fetching vscode.d.ts from: https://raw.githubusercontent.com/Microsoft/vscode/0f080e5267e829de46638128001aeb7ca2d6d50e/src/vs/vscode.d.ts
> vscode.d.ts successfully installed!

**Comment by jrieken** [comment]
That's proposed API and only available to your extension when setting the `enabledProposedApi`-setting to `true`. See https://code.visualstudio.com/updates/v1_25#_proposed-extension-apis
