### ISSUE TITLE
Click event on "open dialog" is propagated to VS Code main window 

### ISSUE THREAD

**Issue by JeehoYoo** [Microsoft/vscode#53867]
- VSCode Version: 1.25
- OS Version: Windows7 -> Ubuntu 16.04

Steps to Reproduce:

1. Connect to Linux PC and launch the VS Code remotely, from Windows PC.(I'm using MobaXTerm to do this.)
2. Make a VS Code extension template.(I refered [this page](https://code.visualstudio.com/docs/extensions/example-hello-world))
3. Add below codes in "activate()" function:
`vscode.window.showOpenDialog({}).then((uri) => { vscode.window.showQuickPick(['item0', 'item1', 'item2']); });`
4. Press F5 to launch the extension.
5. Execute the command "Hello World" on the Extension Development Host.
6. Open dialog is shown, then select some files or folders.
7. Check that quickpick is closed immediately without any user input.
8. We can avoid this bug if the VS Code main window is not covered with open dialog. That is why I guess it is caused by wrong click event propagation.

Does this issue occur when all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
@JeehoYoo Does this also occur when logging in to the Linux box directly or only with the remote UI session?

**Comment by JeehoYoo** [comment]
@chrmarti As I check, it occur only with the remote UI session.
