### ISSUE TITLE
Node modules import suggestions with relative path

### ISSUE THREAD

**Issue by Ridlsan** [Microsoft/vscode#53869]
- VSCode Version: June 2018 (version 1.25.0) and Insiders version
- OS Version: Windows 10

Steps to Reproduce:
1. Add smth from node_modules in code.
2. Try to get suggestion for import. it adds like this (relative path): 

![image](https://user-images.githubusercontent.com/13232749/42451417-def340f4-838f-11e8-98fa-72d6d8b46594.png)

Does this issue occur when all extensions are disabled?: Yes

1.24 version does not have this bug

**Comment by mjbvz** [comment]
Duplicate of #53597
