### ISSUE TITLE
Wrong code color when i use `.css` key to get Object value

### ISSUE THREAD

**Issue by MrKou47** [Microsoft/vscode#53866]
- VSCode Version:  
- OS Version: OSX 10.12.4

Steps to Reproduce:

```js
var obj = {};
if(obj[`${name}.css`]) { // vs code render wrong color on this line
  // some code
}
```

![wrong code style](https://image.ibb.co/dUf12T/WX20180709_203120_2x.png)

Does this issue occur when all extensions are disabled?: No

**Comment by mjbvz** [comment]
This is caused by one of your extensions that contributes to the js grammar. Please file the issue against them

**Comment by MrKou47** [comment]
It's `vscode-styled-jsx` bug. When i remove this extension it work fine.
