### ISSUE TITLE
debug.startDebugging() thenable doesn't resolve on failure

### ISSUE THREAD

**Issue by Gama11** [Microsoft/vscode#53874]
- VSCode Version: 1.25.0
- OS Version: Windows 10

To reproduce, create an extension with the following:

```ts
'use strict';
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
	vscode.commands.registerCommand("foo", () => {
		vscode.debug.startDebugging(vscode.workspace.workspaceFolders[0], "bar")
			.then(success => console.log(success));
	});
}

```

```json
"contributes": {
    "commands": [
        {
            "command": "foo",
            "title": "foo"
        }
    ]
}
```

**Scenario 1:** A launch config named `bar` actually exists, and running the `foo` command leads to `true` being printed in the dev console. So far so good.

**Scenario 2:** There is _no_ launch config with that name, so starting a debugging session fails. My expectation was that `false` would be printed in that case, but instead I get this:

![](https://i.imgur.com/z4uUFPO.png)

I'm actually not 100% sure that's unexpected, since the `@return` docs for `startDebugging()` state:

>A thenable that resolves when debugging could be successfully started.

Which kind of sounds like "it resolves _only_ when debugging could successfully be started". However, what would be the point of the `boolean` parameter that's passed to the `Thenable` then, if it's only ever `true`?

**Comment by weinand** [comment]
Errors are now properly propagated:

![2018-09-17_00-48-41](https://user-images.githubusercontent.com/1898161/45601826-72ebc880-ba13-11e8-8c17-a5161fc6271c.png)
 
Yes, the boolean parameter passed to the thenable will never be false. But now it's too late to change the return type to the correct `Thenable<void>`
