### ISSUE TITLE
Risky dependency from DebugService to TaskService

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#5387]
I have pushed https://github.com/Microsoft/vscode/commit/13c79c8c875d3328f0fa6a1431317b42d8a2c99c cos no one knew why there was such _non-standard_ code around. Turns out @outcoldman  is now struck by this. My only reasonable explaining is that `enableTasks` is sometimes [not true](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/index.html#L172)

I see those options

* We always register an instance of an `ITaskService`, the real-one or a dummy
* We check if debug is prepared for not having a task service
* We don't let the instantiation service explode anymore when a dependency is missing

fyi @isidorn @dbaeumer

**Comment by outcoldman** [comment]
@jrieken seems like that is happens to early, so I cannot attach debugger to it :( 

see https://www.dropbox.com/s/sozuwkjmvzb81ve/vscode-error.mov?dl=0

Any other ideas how I can help to debug this problem?

**Comment by jrieken** [comment]
I think I understood the issue.  I have pushed this as workaround: https://github.com/Microsoft/vscode/commit/fe5ea709b1345f418cde4e775444dea67d0ffc8e

**Comment by isidorn** [comment]
@jrieken we do not have a task service when we have a no folder workspace. However in that case debug is also disabled, though debug service gets registered.
So debug is not prepared for not having a task service, but in practice that never happens becuase they both get disabled for those cases.
Let me know if there is something I should improve here.

**Comment by bpasero** [comment]
The fact that we still use a global flag `enableTasks` is bad debt from old times that we need to get rid of.

**Comment by jrieken** [comment]
> but in practice that never happens becuase they both get disabled for those cases.

I does happen because one service gets registered and the other doesn't

**Comment by dbaeumer** [comment]
Agree that the flag should disappear. I already did that for the configure action which shows a message when invoked on a single file. We can do the same for the clean, build and test actions. Then we can always register a task server. I can look into this.

**Comment by jrieken** [comment]
Assigning to @dbaeumer then. I have changed the instantiation service such that it won't explode in that case more. That is in line with other cases of missing dependencies.
