### ISSUE TITLE
command 'vsforce.retrieveCommand' not found

### ISSUE THREAD

**Issue by rohkapPersonal** [Microsoft/vscode#53876]
Issue Type: <b>Bug</b>

I have installed each and every extension for Salesforce. And use this https://www.youtube.com/watch?v=XD1BqLErWUQ to setup my project. Step to reproduce
- In local create demo project folder
- create package.xml in the folder
- create .vscode (in the same folder) -> settings to provide your login details
- Ctrl + Shift+ P -> vsforce: Retrieve Package
Now at end I am getting the error -command 'vsforce.retrieveCommand' not found.
How to resolve that.

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (0.49GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
apex-autocomplete|chu|0.2.13
vsforce|cov|0.2.0
vscode-eslint|dba|1.4.12
xml|Dot|2.3.1
apex|Joh|0.0.2
ForceCode|Joh|0.5.35
visualforce|Joh|1.0.2
python|ms-|2018.6.0
notepadplusplus-keybindings|ms-|1.0.2
salesforcedx-vscode|sal|43.6.0
salesforcedx-vscode-apex|sal|43.6.0
salesforcedx-vscode-apex-debugger|sal|43.6.0
salesforcedx-vscode-apex-replay-debugger|sal|43.6.0
salesforcedx-vscode-core|sal|43.6.0
salesforcedx-vscode-lightning|sal|43.6.0
salesforcedx-vscode-visualforce|sal|43.6.0

</details>

**Comment by alex-a-ncino** [comment]
Re-downloaded v1.24 and everything is working now

**Comment by patrickhellosign** [comment]
Still an issue.
