### ISSUE TITLE
[folding] Don't expand when clicking on space after collapsed line

### ISSUE THREAD

**Issue by tommai78101** [microsoft/vscode#53886]
- VSCode Version: 1.24.1
- OS Version: Windows 7 LTS

Steps to Reproduce:

1. Do either one of these steps:
    - Copy the following code in a blank document that VS Code supports code folding in.
    - Create a JavaScript document, and save it as "foo.js" anywhere.
2. Copy the following code in (or create whatever code you can be syntactically correct in, and it has to have at least 5 lines of codes):
```javascript
function foo() {
	var create1 = document.querySelector("div");
	var create2 = document.querySelector("div");
	var create3 = document.querySelector("div");
	var create4 = document.querySelector("div");
	var create5 = document.querySelector("div");
	var create6 = document.querySelector("div");
	var create7 = document.querySelector("div");
	var create8 = document.querySelector("div");
	var create9 = document.querySelector("div");
	var create10 = document.querySelector("div");
	var create11 = document.querySelector("div");
	var create12 = document.querySelector("div");
	var create13 = document.querySelector("div");
	var create14 = document.querySelector("div");
	var create15 = document.querySelector("div");
	var create16 = document.querySelector("div");
	var create17 = document.querySelector("div");
	var create18 = document.querySelector("div");
	//... 
}
```
3. Fold the code function, `foo`, so it is folded like so:
![image](https://user-images.githubusercontent.com/6444116/42462134-574c1bd6-8370-11e8-9aaa-78889db18bff.png)
4. Click outside of Visual Studio Code, so Visual Studio Code is inactive (out-of-focus).
5. Click on the right side of the left bracket on the line, `foo() {`, in Visual Studio Code. (Basically, clicking on the empty space, so the line indicator is highlighting the beginning of the code-folded line and the text cursor is at the end of the line).
6. Observe that `foo` gets expanded upon first click, when the correct behavior should be the operating system switching context to Visual Studio Code, and consume the mouse click event without doing anything else.

Here's a GIF in action:

![gif](https://user-images.githubusercontent.com/6444116/42462427-3d528bce-8371-11e8-9849-65f0fc352848.gif)

If we have a list of code-folded functions, and all the user wanted to do was to go back to Visual Studio Code and scroll the document up/down, the user may inadvertently unfold the code, and it would annoy the user to re-fold the code back before continuing to scroll.

Does this issue occur when all extensions are disabled?: Yes

**Comment by nehtechnine** [comment]
loadatomelectronprotonneutronfilestodo

**Comment by tommai78101** [comment]
What?

**Comment by aeschli** [comment]
The current implemented behavior is that when you click after collapsed line, it's range is expanded (regardless whether the VSCode window was inactive or active).

Keeping the issue open to see if others have the same request. If not I'd rather stick with the current behavior. When you activate a window, yo always have to check where you click, as the action below is executed.

**Comment by tommai78101** [comment]
@aeschli I see, so it's an intended design choice. I thought it was a bug, because I didn't see this occurring in Visual Studio 2017, and I am pretty used to the behavior where collapsed codes aren't expanding as is in Visual Studio 2017.

Just curious. Was there ever the intention for Visual Studio Code to stay consistent with Visual Studio 2017 in some/most of the places?

**Comment by aeschli** [comment]
> Just curious. Was there ever the intention for Visual Studio Code to stay consistent with Visual Studio 2017 in some/most of the places?

VSCode is free to evolve and innovate and also takes inspiration from other editors. In the end, we listen to the user feedback. If more users feel as you do (by adding 👍 to the description), we're happy to change to current behavior.

**Comment by tommai78101** [comment]
@aeschli Would it be possible to keep the behavior of this feature, but don't let VS Code take in the mouse click event when inactive?

**Comment by aeschli** [comment]
@tommai78101 I look into that but it's not so easy to detect and I believe it would be the only place where we have such a special treatment.

**Comment by tommai78101** [comment]
Ah ok. The way you edited the title of the issue, made me want to ask if not doing the behavior while VS Code is inactive is possible. But I guess it's a lot harder.

Thanks.

**Comment by filipgoc** [comment]
This also bothers me. I would definitely prefer a toggle to disable this behavior!

**Comment by Lovecircle** [comment]
Please change this or give an option to "unfold code on double-click" for example. I cannot say how many times I accidentally unfolded blocks of code by simply clicking on what appeared to be just an empty space in the editor - very annoying.

**Comment by aeschli** [comment]
@Footurist Cursor move is not related to clicking.
Please file a issue and explain what command exactly you are using.

**Comment by Pierce913** [comment]
This also frustrates me. I would prefer to explicitly unfold or click the little +/- button. I don't want it to unfold when I click at the end of a folded line.

**Comment by Rawalanche** [comment]
Hi, another vote from me. This behavior is extremely frustrating. When you fold any function in MSVS, then everything still feels solid and comfortable. But when you fold anything in VSCode, you immediately start to feel like a EOD unit member, having to be very, VERY careful where you click. It's never a good thing to introduce any behavior that requires user to feel uneasy and careful.

**Comment by simonvomeyser** [comment]
It's also a reason for me to not use folding that much because i mostly move my cursor up and down with the keyboard... moving it over a folded region expands that region

An option flag for that would be awesome! Keep up the good work tough 👍

**Comment by 4ekki** [comment]
Another vote from me for keeping the block folded when clicking on the empty space in the end of the line and unfold only on explicitly clicking 'plus' or '...' icons. When you have something like this and you want to focus the window, big chances that you occasionally expand something folded. 
![image](https://user-images.githubusercontent.com/38757986/56791596-1d309780-6810-11e9-91b5-42df0bc20d30.png)

**Comment by HanggiAnggono** [comment]
Another vote from me, also the folded region will open if text search found a match inside the folded region

**Comment by robomalo** [comment]
+1 Auto expanding drives me nutty.

**Comment by JOJ0** [comment]
> It's also a reason for me to not use folding that much because i mostly move my cursor up and down with the keyboard... moving it over a folded region expands that region
> 
> An option flag for that would be awesome! Keep up the good work tough 👍

Exactely my problem. Why unfold when I just want to move my cursor up in the code. I had the thing collapsed for a reason ;-) Making this configurable would be perfect.

Thanks for a great editor though!!!

**Comment by aeschli** [comment]
Due to many requests I've change the behaviour that clicking in the empty space no longer expands.

**Comment by gkarapeev** [comment]
> Due to many requests I've change the behaviour that clicking in the empty space no longer expands.

NOOOOO.

**Comment by gkarapeev** [comment]
Is there a way to opt out of that change? I find it frustrating having to click such a small target with my mouse. It's a well explained situation in UX (Fitt's Law)!

**Comment by tommai78101** [comment]
@gkarapeev In VSCode 1.42.1, there's a feature where you're able to auto-fold / auto-expand code blocks using `Shift` + `Mouse Click`. You can click on the highlighted code line with this mouse shortcut, and the code blocks will fold / unfold. Not sure if left mouse button or right mouse button. 

This new feature supersedes the "empty space code folding".

**Comment by aeschli** [comment]
I will make it configurable: #88522
