### ISSUE TITLE
Double click on an icon in the window header causes window close (titleBarStyle custom)

### ISSUE THREAD

**Issue by Yanpas** [Microsoft/vscode#53881]
- VSCode Version: 1.25
- OS Version: kubuntu 18.04

Steps to Reproduce:

1. Enable new windowing mode with menu rendered in the window title
2. double click on vscode blue icon in the left
3. VS code closes with exit-code 0 and empty log.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
This is apparently default behavior on Windows I discovered when testing this, @sbatten I would suggest toggling maximize is the right behavior for Linux.
