### ISSUE TITLE
The option to undo auto-format output

### ISSUE THREAD

**Issue by RaananW** [microsoft/vscode#53884]
There are certain auto-format edits that don't make sense for certain types.
Instead of disabling it globally (or per project), it will be great if I could undo the last auto-formatting output and still save the file. 

Something along the lines of:

Ctrl+S -> bad formatting -> Ctrl+Z -> Ctrl+S -> Saved without auto formatting

**Comment by jrieken** [comment]
This now exists as "Save without formatting"
