### ISSUE TITLE
Source provider

### ISSUE THREAD

**Issue by jewels98** [Microsoft/vscode#53880]
<img width="712" alt="screen shot 2018-07-09 at 10 37 04 am" src="https://user-images.githubusercontent.com/40129390/42457970-dbcf9a0e-8366-11e8-8bd0-8cf8c4e5e3cf.png">
Issue Type: <b>Bug</b>

I am unable to use source control. I attached a screen shot of the tools I don't have access to unless I use the command line.

VS Code version: Code - Insiders 1.26.0-insider (bbafa06a3d3db60bbd06d4d4cd582586f7126d93, 2018-07-09T05:42:46.615Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|16.00GB (2.34GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_3670912|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|0.11.1
git-easy|bib|1.9.1
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.59
vscode-markdownlint|Dav|0.18.0
vscode-eslint|dba|1.4.12
jquerysnippets|don|0.0.1
gitlens|eam|8.4.1
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.5.0
git-project-manager|fel|1.6.1
beautify|Hoo|1.3.2
jquery-snippets|Hri|1.0.0
ftp-simple|hum|0.6.7
icon-fonts|idl|2.1.0
node-module-intellisense|lei|1.5.0
vs-color-picker|lih|0.7.0
code-beautifier|mic|2.1.0
Angular-BeastCode|Mik|6.0.21
easy-less|mrc|1.4.5
vscode-less|mrm|0.6.3
vscode-scss|mrm|0.6.2
atom-keybindings|ms-|3.0.4
team|ms-|1.136.0
debugger-for-chrome|msj|4.7.0
material-icon-theme|PKi|3.5.1
Ruby|reb|0.18.0
live-sass|rit|2.2.1
LiveServer|rit|5.1.1
vscode-icons|rob|7.24.0
sass-indented|rob|1.4.9
javascript-typescript|sou|0.0.7
open-in-browser|tec|1.1.0
vscode-terminal-here|Tyr|0.1.1
html-css-class-completion|Zig|1.17.1
vscode-open-in-github|ziy|1.3.3

(4 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
> I am unable to use source control. I attached a screen shot of the tools I don't have access to unless I use the command line.

From the screenshot it seems everything is working OK.

What is the problem?
