### ISSUE TITLE
Release notes 1.25.0 is not fully working

### ISSUE THREAD

**Issue by luizhds** [Microsoft/vscode#53883]
Issue Type: <b>Bug</b>

Release notes for the version 1.25.0 is not working. I can only see a kinda html page with some references to javascript code and css

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600M CPU @ 2.90GHz (4 x 2893)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Memory (System)|7.91GB (1.75GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
mssql|ms-|1.4.0
python|ms-|2018.6.0
csharp|ms-|1.15.2

</details>

**Comment by Tyriar** [comment]
Can you provide a screenshot?

**Comment by luizhds** [comment]
![image](https://user-images.githubusercontent.com/3083235/42473654-d7b2f492-838a-11e8-9da4-a7c4e503da13.png)

**Comment by mjbvz** [comment]
Are you on a proxy? Our release notes should not have jquery in them.
