### ISSUE TITLE
Can't move the panel position to the bottom after move to right.

### ISSUE THREAD

**Issue by naishiro** [Microsoft/vscode#53889]
Issue Type: <b>Bug</b>

I've just moved the position of the panel (terminal,output...) to the right, but the button is missing..  include move to bottom, I don't know how to restore it.
<img src="https://image.ibb.co/d1WLe8/Screen_Shot_2018_07_10_at_12_36_46_AM.png">
VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:02:28.333Z)
OS version: Darwin x64 17.6.0

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/46017
