### ISSUE TITLE
Please provide support for developing/debugging Google AppEngine applications

### ISSUE THREAD

**Issue by MandarJKulkarni** [Microsoft/vscode#53888]
I (like many others) use VS code to debug a flask application.
This application is deployed as a service on Google cloud using appengine.

I somehow managed to debug the application on Windows with manual changes in appengine_config file or by modifying PYTHONPATH.
However, setting up VS code on Ubuntu image has been giving a really hard time.
Please consider adding support for developing/debugging Google AppEngine services as a feature.

**Comment by weinand** [comment]
This feature could be easily supported as an extension.
