### ISSUE TITLE
Access visible source control providers

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#53892]
From the discussion in https://github.com/Microsoft/vscode/pull/51734, we want to introduce a `visibleSourceControls` api that allows extensions to get a list of currently selected providers and be notified of changes.

**Comment by RMacfarlane** [comment]
The plan now is to expose an API for this through the git extension by having an event on the git Source Control object that fires when it is selected.

I assume there would also be a corresponding "blur" event. This means that a change in selection wouldn't be an atomic event, but a blur of one control and focus of another. Alternately, instead of separate blur and focus events, there's one change event that fires with a boolean indicating which it is, but selection change is still not atomic. @joaomoreno what did you have in mind for this? And a list of source controls would be exposed through the git extension, correct?

// cc @jrieken

**Comment by joaomoreno** [comment]
Do we really need a blur event? Isn't a selection change event enough?

**Comment by RMacfarlane** [comment]
Perhaps I just misunderstood the explanation of the proposal - if it's just to move `visibleSourceControls` and `onDidChangeVisibleSourceControls` to the git extension API, then there's no need for the blur event. But I thought it was something like an `onDidSelect` event on a source control object itself

**Comment by joaomoreno** [comment]
Oh I see what you mean. Yeah that's true. Unless the git extension does some debouncing, users of the API would get two separate events.
