### ISSUE TITLE
Typescript types are not highlighted

### ISSUE THREAD

**Issue by ivanvoznyakovsky** [Microsoft/vscode#53896]
- VSCode Version: 1.25.0
- OS Version: macOS 10.13.5

Steps to Reproduce:

1. declare more than 2 variables with a single `let/const/var` each on a new line
2. type each variable
3. observe that starting from 3rd var it's type is not highlighted
<img width="230" alt="screenshot 2018-07-09 20 33 54" src="https://user-images.githubusercontent.com/6418145/42466379-6d0f8cea-83b7-11e8-96c7-d4186ff78a35.png">
4. putting all vars in one line highlights type of every var
<img width="531" alt="screenshot 2018-07-09 20 34 22" src="https://user-images.githubusercontent.com/6418145/42466397-7b9d314a-83b7-11e8-8af7-a7c0b9110c5b.png">

Does this issue occur when all extensions are disabled?: Yes
<img width="237" alt="screenshot 2018-07-09 20 22 35" src="https://user-images.githubusercontent.com/6418145/42465857-da9e19e0-83b5-11e8-8e1b-4eb48982d93b.png">

Does this issue occur in latest insiders build?: Yes
<img width="181" alt="screenshot 2018-07-09 20 28 35" src="https://user-images.githubusercontent.com/6418145/42466121-ae71aa70-83b6-11e8-8a94-a8a6393de5d3.png">

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript-TmLanguage/issues/635 to track this upstream
