### ISSUE TITLE
 Cannot read property 'row' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#53893]
Issue Id: <b>783c1aa8-11bd-b612-810d-6ae01b32b008</b><br /><br />*Versions* <br />- 1.26.0-insider (7/6/2018 5:15:15 AM)<br />*Stack* <br />TypeError: Cannot read property 'row' of undefined<br />[/vs/base/browser/ui/list/listView.ts#285:12 (insertItemInDOM)](https://github.com/microsoft/vscode/blob/bd953248ad6a8e2f8896bfb78b3ae40e0fd47426/src/vs/base/browser/ui/list/listView.ts#L285:12 (insertItemInDOM))<br />[/vs/base/browser/ui/list/listView.ts#258:9 (render)](https://github.com/microsoft/vscode/blob/bd953248ad6a8e2f8896bfb78b3ae40e0fd47426/src/vs/base/browser/ui/list/listView.ts#L258:9 (render))<br />[/vs/base/browser/ui/list/listView.ts#374:7 (call)](https://github.com/microsoft/vscode/blob/bd953248ad6a8e2f8896bfb78b3ae40e0fd47426/src/vs/base/browser/ui/list/listView.ts#L374:7 (call))<br />[/vs/base/common/event.ts#142:18 (fire)](https://github.com/microsoft/vscode/blob/bd953248ad6a8e2f8896bfb78b3ae40e0fd47426/src/vs/base/common/event.ts#L142:18 (fire))<br />[/vs/base/browser/ui/scrollbar/scrollableElement.ts#177:18 (call)](https://github.com/microsoft/vscode/blob/bd953248ad6a8e2f8896bfb78b3ae40e0fd47426/src/vs/base/browser/ui/scrollbar/scrollableElement.ts#L177:18 (call))<br />[/vs/base/common/event.ts#140:15 (fire)](https://github.com/microsoft/vscode/blob/bd953248ad6a8e2f8896bfb78b3ae40e0fd47426/src/vs/base/common/event.ts#L140:15 (fire))<br />[/vs/base/common/scrollable.ts#332:17 (_setState)](https://github.com/microsoft/vscode/blob/bd953248ad6a8e2f8896bfb78b3ae40e0fd47426/src/vs/base/common/scrollable.ts#L332:17 (_setState))<br />[/vs/base/common/scrollable.ts#222:7 (setScrollDimensions)](https://github.com/microsoft/vscode/blob/bd953248ad6a8e2f8896bfb78b3ae40e0fd47426/src/vs/base/common/scrollable.ts#L222:7 (setScrollDimensions))<br />[/vs/base/browser/ui/scrollbar/scrollableElement.ts#258:19 (setScrollDimensions)](https://github.com/microsoft/vscode/blob/bd953248ad6a8e2f8896bfb78b3ae40e0fd47426/src/vs/base/browser/ui/scrollbar/scrollableElement.ts#L258:19 (setScrollDimensions))<br />[/vs/base/browser/ui/list/listView.ts#201:25 (_splice)](https://github.com/microsoft/vscode/blob/bd953248ad6a8e2f8896bfb78b3ae40e0fd47426/src/vs/base/browser/ui/list/listView.ts#L201:25 (_splice))<br />[/vs/base/browser/ui/list/listView.ts#137:15 (splice)](https://github.com/microsoft/vscode/blob/bd953248ad6a8e2f8896bfb78b3ae40e0fd47426/src/vs/base/browser/ui/list/listView.ts#L137:15 (splice))<br />[/vs/base/browser/ui/list/splice.ts#21:34](https://github.com/microsoft/vscode/blob/bd953248ad6a8e2f8896bfb78b3ae40e0fd47426/src/vs/base/browser/ui/list/splice.ts#L21:34)<br />    at Array.forEach (native)<br />[/vs/base/browser/ui/list/splice.ts#21:19 (splice)](https://github.com/microsoft/vscode/blob/bd953248ad6a8e2f8896bfb78b3ae40e0fd47426/src/vs/base/browser/ui/list/splice.ts#L21:19 (splice))<br />[/vs/base/browser/ui/list/listWidget.ts#936:56 (fn)](https://github.com/microsoft/vscode/blob/bd953248ad6a8e2f8896bfb78b3ae40e0fd47426/src/vs/base/browser/ui/list/listWidget.ts#L936:56 (fn))<br />[/vs/base/common/event.ts#403:2](https://github.com/microsoft/vscode/blob/bd953248ad6a8e2f8896bfb78b3ae40e0fd47426/src/vs/base/common/event.ts#L403:2)<br />    at e.splice (out/vs/<br />

**Comment by ramya-rao-a** [comment]
@joaomoreno Seems to occur only in the Insiders of 1.26
