### ISSUE TITLE
Subword with multiple space

### ISSUE THREAD

**Issue by MaxenceG2M** [Microsoft/vscode#53899]
- VSCode Version: 1.25.0 (0f080e5)
- OS version: Windows_NT x64 10.0.17134

Hi,
The new feature subword navigation has a weird behavior with multiple space and could be improved (in my opinion).

With multiple space, this is the actual behavior:
![default_behavior](https://user-images.githubusercontent.com/4601728/42469395-d9da5486-83b7-11e8-8677-83185f80e583.gif)

If you use [Subword Navigation](https://marketplace.visualstudio.com/items?itemName=ow.vscode-subword-navigation) extension, this is the behavior (and expected behavior for me):
![expected_behavior](https://user-images.githubusercontent.com/4601728/42469407-e5164ef4-83b7-11e8-9121-6bd9dc60962f.gif)

I think this improvment could be very nice :)

Thanks a lot for this wonderful IDE :)

**Comment by johnnytemp** [comment]
E.g. I would like to use the purposed behavior to manual re-align the following code: do column selection for multiple lines at column 1, select spaces (or tabs), delete them and tab-key to indent:

     -- 1
            -- 2
        #3
       #4

**Comment by johnnytemp** [comment]
Tested the insiders version a3f9f2e7240106aeec2f1d4bc03d7876bd42e2e4 2018-09-07T05:05:38.205Z just now.

The fix doesn't work perfectly.

On line 1 of:

    ; -- 1
    ;        -- 2
    ;    #3
    ;   #4

" --" is selected wrongly, instead of just one space.

And for the input:

     -- 1
            -- 2
        #3
       #4

4 columns at line starts, wordPartRightSelect, then wordPartLeftSelect, all lines remain one space selected at the start of the lines.

See the gif
![subword-space-select-bug](https://user-images.githubusercontent.com/2296583/45275073-283aef80-b4ed-11e8-8042-5abacafc44e8.gif)

**Comment by johnnytemp** [comment]
There is also problem when begin from line start and do wordPartRightSelect for lines with only spaces.  On many lines the last space is not selected.

    ....
    .
    ...
    ........

The periods meant spaces above.

**Comment by alexandrudima** [comment]
Thanks @johnnytemp for the testing.

I have pushed additional fixes via a4a5b590ec996f64eb0675dedd80adf941333777

**Comment by johnnytemp** [comment]
Thanks @alexandrudima   Will test it later when the Insider released.

**Comment by johnnytemp** [comment]
Oh, seems it works perfectly now.  Thanks a lot!

**Comment by MaxenceG2M** [comment]
Thank you very much! Work perfectly in Insider :)

Another essential function directly in VSCode, this IDE become the best of the best!
