### ISSUE TITLE
How to get file go-to and intellisense working for aliased imports?

### ISSUE THREAD

**Issue by ffxsam** [Microsoft/vscode#53903]
The following is not recognized by VS Code:

```js
import { login, logout } from '@/adonis-api';
```

If I use a relative path, e.g. `'../../../adonis-api'`, it's fine. Is there some way to configure VS Code so it knows what folder the `@` alias points to?

**Comment by dotproto** [comment]
Is your alias defined in `webpack.config.js`, `.tsconfig`, or somewhere else? I ask because I'm currently looking at a TS project with an alias defined in `.tsconfig` and I'm not seeing this issue.

**Comment by mjbvz** [comment]
Closing as we need more information to investigate this. @ffxsam Please share how you are trying to define the alias. This should be done in a `jsconfig.json` or `tsconfig.json` file using the `paths` section

**Comment by ffxsam** [comment]
Solved with the following `jsconfig.json` file. Thanks!

```json
{
  "compilerOptions": {
    "baseUrl": "./",
    "paths": {
      "@/*": ["src/*"]
    }
  }
}
```

**Comment by AO17** [comment]
@ffxsam how would that look with [this](https://stackoverflow.com/questions/48686203/webpack-resolve-alias-does-not-work-with-vs-code-intellisense) `jsconfig.json` ?
