### ISSUE TITLE
Menu breaks workbench if window is too short

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#53905]
![image](https://user-images.githubusercontent.com/2193314/42474136-783c4b9e-837b-11e8-9dcc-9267b7633d2e.png)

This can corrupt the workbench position after the menu is closed:

![image](https://user-images.githubusercontent.com/2193314/42474160-86edef76-837b-11e8-806a-1c92009b7943.png)

**Comment by sbatten** [comment]
tracked in #52533
