### ISSUE TITLE
Setting the zoom level independently for each editor

### ISSUE THREAD

**Issue by axefrog** [microsoft/vscode#53901]
I have a very large monitor and am using the grid layout a lot (thanks! :)) ... and what I'm finding is that I'd like to zoom out some of the editor panes so that they're visible to glance at, but reduced in size seeing as they're not the main focus, and then be able to zoom in on certain panes as well. For instance I write a tonne of notes across different markdown files, and I'll have 2-3 previous markdown files open to the right in a vertical stack of grid panels for reference/review while I'm writing today's notes, which take up a full column to their left. Then to the left of that, I have the current code file I'm working on. The main markdown file would ideally be zoomed in a bit, and the code file would be at the normal zoom level. The reference notes on the right would be at about half zoom so I can see enough to make the vertical stacking not lose value.

**Comment by SpaceHexagon** [comment]
Once people begin to flee IntelliJ, they will want this feature.
It's going to happen!
Remain vigilant, my independently zooming warriors!

**Comment by elliotchaim** [comment]
Yes please!

**Comment by detj** [comment]
Will this feature also allow one to zoom the Markdown preview font independently of the editor zoom settings?

**Context**
I often write large amount of markdown text in zen mode with markdown preview on. I also zoom in the editor font while writing. Very comfortable when the monitor is farther from my eyes. While editor font zooming works perfectly, the markdown preview font does not change though, making it harder to preview.

I understand that the markdown preview font size is controlled by the markdown stylesheet settings, but it would be really useful if the end user could either independently control the markdown preview font size or if changing the editor font zoom setting could also proportionally zoom in/out the markdown editor font size.
