### ISSUE TITLE
Roots expanded on startup if all were collapsed on close

### ISSUE THREAD

**Issue by haugerbr** [microsoft/vscode#53904]
Whenever I open up my multi-root project every folder is expanded by default in the explorer which makes it harder to drill down into what I want to work on since it is a huge file tree. I can't find any setting or documentation on how to change this behavior. I put this as a bug instead of a feature request because it feels more like a usability issue than a feature to me.

**Comment by isidorn** [comment]
Try this:
`"explorer.autoReveal": false`

We only expand all root folders if all of them are collapsed (due to some corner case situation which we an not distuingish from this). If this is your exact issue let me know but we do not plan to fix this at the time being.

**Comment by tumido** [comment]
@isidorn, I'm not the original complainer here, but the expanded root folders is exactly the problem which brought me here. II'm sorry to hear that the team decided this won't get fixed any time soon.

However for @haugerbr and others interested, I have a workaround:
1. Install [Auto Run Command](https://marketplace.visualstudio.com/items?itemName=gabrielgrinberg.auto-run-command) extension
2. Add this rule to your `settings.json`:
```
"auto-run-command.rules": [
    {
        "condition": always,
        "command": "workbench.files.action.collapseExplorerFolders"
    }
],
```

**Comment by haugerbr** [comment]
@isidorn What additional information do you need? `"explorer.autoReveal": false` did not fix it.

**Comment by haugerbr** [comment]
Used workaround provided by @tumido for now.

**Comment by isidorn** [comment]
This works fine for me in latest. Closing
