### ISSUE TITLE
Opening Typescript references (via references code lens) never finishes loading in the peek view

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#53902]
Issue Type: <b>Bug</b>

Started in today's insiders build. Click on a references code lens in a Typescript file and the peek view opens, but it just always says "Loading..." and never loads. Using the command (via the menu, or command palette) works fine. While using the shortcut key, (Shift+F12) doesn't do anything at all (although that is reproducible for me in 1.25 too).

VS Code version: Code - Insiders 1.26.0-insider (19df280c7f7cf73d9bafcde82a9e93b14026cfc2, 2018-07-09T08:59:57.017Z)
OS version: Windows_NT x64 10.0.17711

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (14.71GB free)|
|Process Argv|C:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by mattacosta** [comment]
Odd, Shift+F12 works for me in 1.25 and today's insider build. It's just the code lens link that does nothing (in the insiders build).

**Comment by mjbvz** [comment]
I don't think this is language specific. F12 seems to work for me in general

**Comment by mjbvz** [comment]
@jrieken I think this may be related to the winjs promise work but am not sure. We at least make it to `showReferencesCommand` after you click on the code lens

**Comment by eamodio** [comment]
I figured out my F12 problem -- had nothing to do with vscode, sorry for the noise.
