### ISSUE TITLE
tsserver.js running with 100% CPU after adding sources to excluded folder 

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#53912]
Issue Type: <b>Bug</b>

1. Create  a js project with a `jsconfig.json` file that contains the following snippet
```json
{
    "exclude": [
        "ignored-sources"
    ]
}
```
2. Add a `.js` file to your project and open it
3. `cd` into `ignored-sources` and clone the vscode repo

-> `tsserver.js` runs at 100% for 30s or more before it calms down. Ignoring file events should be that resource intensive.

VS Code version: Code - Insiders 1.26.0-insider (19df280c7f7cf73d9bafcde82a9e93b14026cfc2, 2018-07-09T08:50:28.927Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.28GB free)|
|Process Argv|/Users/kmaetzel/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_757945|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by mjbvz** [comment]
I don't see this in the latest VS Code insiders. The vscode watcher service still goes a bit crazy but not tsserver.

Still seeing this after the latest TS-insiders update?
