### ISSUE TITLE
npm `.bin` handling is disabled: `.bin` directory is not created, `.cmd` wrappers missing...

### ISSUE THREAD

**Issue by busticated** [Microsoft/vscode#53916]
hi there :wave:

i'm not sure if this is a known-issue or what (i tried digging thru the docs to see if it was called out but wasn't able to find anything - apologies in advance if i just missed it). 

i have an extension under development which attempts to pull in a node-based CLI via its `dependencies` in `package.json`. i noticed that the expected `.bin` directory (and related `.cmd` wrappers) are not created after installing my extension `.vsix`. 

i see this in the extension's `node_modules` directory:

```
    Directory: C:\Users\Me\.vscode\extensions\test.test-vscode-core-0.0.1\node_modules


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         7/9/2018  11:07 AM                align-text
d-----         7/9/2018  11:07 AM                amdefine
...
```

but when i install using npm v5, i see:

```
    Directory: C:\Users\Me\test-npm-i\node_modules


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         7/9/2018   5:25 PM                .bin
d-----         7/9/2018   5:25 PM                align-text
d-----         7/9/2018   5:25 PM                amdefine
...
```

within `.bin` i see:

```
    Directory: C:\Users\Me\test-npm-i\node_modules\.bin


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         7/9/2018   5:25 PM            331 my-cli
-a----         7/9/2018   5:25 PM            208 my-cli.cmd
...
```

the key being the `.cmd` helper(s)

my debug info:
- VSCode Version: v1.25.0
- OS Version: Windows 10 "Pro"

Steps to Reproduce:

1. install an extension with `dependencies` that expose a cli command via the `bin` field in its `package.json` file
2. inspect the resulting `node_modules` directory

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
VS Code doesn't run `npm install` after installing an extension. Instead, the VSIX contains the `node_modules` folder within. It only contains the actual runtime dependencies, so it will exclude `.bin`. Since scripts in `.bin` are nothing more than links to sources in dependencies, I suggest writing them yourself and shipping them within the VSIX.

**Comment by busticated** [comment]
thanks @joaomoreno 🙏 

do you have any guidance and / or docs on the packaging step?

specifically, what files / directories are included by default? is it basically a whitelist of files (readme, changlog, etc) in the root of the extension plus the contents of `./src`?

i know there are restrictions around images 👇 
https://code.visualstudio.com/docs/extensions/publish-extension#_publishing-extensions

i also tried reading thru 👉  https://github.com/Microsoft/vscode-vsce/blob/master/src/test/package.test.ts but may have missed it

**Comment by joaomoreno** [comment]
This is what gets ignored by default: https://github.com/Microsoft/vscode-vsce/blob/53d41d44c895d3ed6ffa9b07a222996d09126e39/src/package.ts#L680

**Comment by busticated** [comment]
ah, ok. i thought some sub-directories were being excluded but looking more closely at what actually gets installed i see now they are not. thanks! 🙏 👍
