### ISSUE TITLE
Editor.parameterHints Failed

### ISSUE THREAD

**Issue by vicchoutw** [Microsoft/vscode#53925]
Hello All，I have set the 'editor.parameterHints' to 'true' in user.setting json but my html file still showed the pop out tips in few minutes later (Success at first)。I try restart VScode application but it still do the same, so weird lol.

User's Setting
<img width="406" alt="error" src="https://user-images.githubusercontent.com/21326779/42488991-0e3f50d6-843b-11e8-8308-b8bbe7ff642e.png">

But VScode still show the tips
<img width="813" alt="error2" src="https://user-images.githubusercontent.com/21326779/42488992-0e6b8318-843b-11e8-8321-5f1349d1e835.png">

**Comment by Coalescent** [comment]
I am having the same issue (I assume the poster above meant to type `false`)... just started in the past several days or so. I had not changed my User Settings for some months and then suddenly I'm getting hints (like the screen above) popping up as if `parameterHints` was set to `true`. I have checked my User Settings and they look correct (and remain unchanged from how I've had them for many, many weeks at least):

```
"editor.parameterHints": false,
"html.suggest.html5": false
```

I am running Version 1.25.1 (1.25.1) on Mac OS X 10..12.6.

This seems like a bug. I have restarted VS Code and that makes no difference. I have tried changing my user settings above and that doesn't help.

**Comment by palbergstrom** [comment]
Same problem
1.26.1
Ubuntu 18.04

**Comment by alexandrudima** [comment]
That screenshot is not of parameter hints. The screenshot is of the hover. The hover can be disabled via `editor.hover.enabled`.

**Comment by vicchoutw** [comment]
Hello Alexandru, but it still not working...
I am running Mac OSX 10.13.6 & VScode version 1.26

<img width="390" alt="2018-08-24 10 51 15" src="https://user-images.githubusercontent.com/21326779/44562319-ac6e4280-a78b-11e8-8855-cfcf07cbaffb.png">
<img width="566" alt="2018-08-24 10 52 07" src="https://user-images.githubusercontent.com/21326779/44562350-c90a7a80-a78b-11e8-9678-4786ef9a67a1.png">

**Comment by alexandrudima** [comment]
@vicchoutw I cannot reproduce.

In a VSCode installation with a single setting `"editor.hover.enabled": false`, the hover does not show:

![kapture 2018-08-27 at 11 38 56](https://user-images.githubusercontent.com/5047891/44653010-d2931d00-a9ed-11e8-9a25-c145d297ff1e.gif)

**Comment by vicchoutw** [comment]
Hi Alexandrudima,

 I found that i got this in user setting `"editor.hover": false`,
which cause "editor.hover.enabled" failed

After delete then everything work perfectly
