### ISSUE TITLE
Allow to right click on split icon to change split direction

### ISSUE THREAD

**Issue by FFengIll** [Microsoft/vscode#53929]
if it is possible to allow 
`right click` to change the `vertical/horizontal view`?
so we can easily make the grid view than cmd or menu.

**Comment by bpasero** [comment]
@FFengIll please explain with more text what you want

**Comment by FFengIll** [comment]
As we know , we have this to split view  now 
![temp](https://user-images.githubusercontent.com/7359555/42498718-873c25da-845f-11e8-9548-7cecafa23f7b.png)

but the single button is not convenient while grid view, like bellow, （great thanks for grid view)
<img width="714" alt="temp2" src="https://user-images.githubusercontent.com/7359555/42498999-43991b52-8460-11e8-89a3-66fb9adc7c15.png">

Now we can only `split to right` with the button (in GUI), 
so if we can `right click` the button and change it into `split to down`, like this,
![image](https://user-images.githubusercontent.com/7359555/42499111-87fd478c-8460-11e8-9aba-5b9c31deaba0.png)


it may be great.

**Comment by FFengIll** [comment]
@bpasero if it is allowed, I will try to pull request.
