### ISSUE TITLE
Changing "editor.fontSize" and "editor.fontFamily" in  user settings will not take effect

### ISSUE THREAD

**Issue by CallMeR** [Microsoft/vscode#53926]
- VSCode Version:1.25.0
- OS Version: Windows 10，Ubuntu 18.04
- "window.titleBarStyle": "custom" OR "window.titleBarStyle": "native",

Steps to Reproduce:

1. open settings.jason 
2.change font size or family，ctrl+s
3.window on the left will take effect immediately，but window on the right will keep the old look。

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
I cannot reproduce with the given steps, the font family changes in both opened files for me:

![fontfamily](https://user-images.githubusercontent.com/5047891/43307323-2a4eb88e-917e-11e8-9139-376216b9b59c.gif)
