### ISSUE TITLE
Support links execute vscode commands in output panels

### ISSUE THREAD

**Issue by Lamoreauxaj** [microsoft/vscode#53922]
## Feature
Currently, I'm using the output panel and can use file paths in order to create links to files on my system. At the moment, this includes input and output files from the extension running. I want to also be able to diff compare the output to the correct output on just a click from the terminal.
In order to use vscode's awesome diff editor, I have to launch it programmatically. So that's where this feature idea came from. If I was able to create links in the output panel that run a vscode command, I could then launch the diff editor on the appropriate files.
I can also see why you wouldn't want someone to launch commands from the output panel as a fear of unknown code execution.
### Background
I'm working on an extension for personal use designed as a test runner for competitive programming. The gist of it is that I create test cases from input and output files and can run on multiple languages with the output to the output panel. There are other features specific for the extension that aren't relevant here.

Any input on whether this is already supported, any good alternatives, or whether this is a bad idea?

Note: that just selecting files and doing a diff isn't an applicable solution, because the files are runtime generated and stored in temporary locations.

**Comment by Tyriar** [comment]
> Currently, I'm using the output panel and can use file paths in order to create links to files on my system. At the moment, this includes input and output files from the extension running. I want to also be able to diff compare the output to the correct output on just a click from the terminal.

You say both Output Panel and Terminal, which thing are you talking about?

Do you have a proposal for how this would work?

**Comment by Lamoreauxaj** [comment]
I was specifically talking about the Output Panel, sorry for the confusion.

Currently the output panel deals with link rendering, so maybe a specific syntax that when parsed by the code that manages output panel rendering. The idea is to create hyperlinks that really just execute vscode commands.
