### ISSUE TITLE
Terminal cannot display correctly

### ISSUE THREAD

**Issue by honghui-qiao** [Microsoft/vscode#53920]
- VSCode Version: 1.25
- OS Version: macOS 10.13.5

Here's the screenshot, move side bar right will have this issue:
![20180710102006](https://user-images.githubusercontent.com/16600963/42485649-2431909e-842b-11e8-86c7-e02e88fc574c.png)

**Comment by honghui-qiao** [comment]
Any update?

**Comment by saborrie** [comment]
This is happening to me too

**Comment by saborrie** [comment]
For now you can add this to the end of `C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\workbench.main.css`

```
.xterm-screen{overflow-x:hidden}
```

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by saborrie** [comment]
hey @Tyriar, yes this looks like it is working in the latest insiders build, thanks
could you link to the issue you've tagged this as a duplicate of? so that I can follow it and get updated for when it makes it into usual release

**Comment by Tyriar** [comment]
@saborrie there were 2 issues that caused this in various cases https://github.com/Microsoft/vscode/issues/51479 & https://github.com/Microsoft/vscode/issues/54230
