### ISSUE TITLE
更新失败

### ISSUE THREAD

**Issue by wangFty** [Microsoft/vscode#53927]
Issue Type: <b>Performance Issue</b>

更新失败

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (2.64GB free)|
|Process Argv|G:\Visual Studio\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   100	  3468	code main
    3	    76	  1280	   shared-process
    9	   302	  6220	   window (HelloWorld.vue - 无标题 (工作区) - Visual Studio Code)
    0	    10	  7504	     electron-crash-reporter
    0	    98	 13400	     extensionHost
    0	    29	  2164	       electron_node tslintServer.js 
    0	    58	  7520	       electron_node htmlServerMain.js 
    0	   136	  9004	       electron_node vueServerMain.js 
    0	    67	 11992	       electron_node jsonServerMain.js 
    0	    28	 16608	     searchService
    0	    35	 16944	     watcherService
    0	    66	 12488	   shared-process
    1	    95	 13808	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (HelloWorld.vue - 无标题 (工作区) - Visual Studio Code)
|    Folder (脚手架axios): 25 files
|      File types: js(13) json(2) png(2) vue(2) babelrc(1) editorconfig(1)
|                  gitignore(1) md(1) html(1) gitkeep(1)
|      Conf files: package.json(1)
|    Folder (Vue项目): 87 files
|      File types: js(27) jpg(17) png(15) vue(10) map(4) css(3) html(2)
|                  gitignore(1) babelrc(1) eslintignore(1)
|      Conf files: package.json(1)
|    Folder (vue复习): 184 files
|      File types: js(61) html(38) jpg(20) DS_Store(12) png(12) map(8) css(6)
|                  vue(6) json(5) docx(3)
|      Conf files: package.json(2);
```

</details>
<details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
npm-intellisense|chr|1.3.0
vscode-express|Com|0.0.5
vscode-markdownlint|Dav|0.18.0
vscode-eslint|dba|1.4.12
es7-react-js-snippets|dsz|1.8.3
vscode-babel-coloring|dza|0.0.4
vscode-html-css|ecm|0.2.0
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.33
vscode-npm-script|eg2|0.3.5
vue-snippets|hol|0.1.8
autofilename|Jer|0.1.3
vscode-scss|mrm|0.6.2
vscode-language-pack-zh-hans|MS-|1.24.3
node-debug2|ms-|1.20.0
sublime-keybindings|ms-|4.0.0
team|ms-|1.136.0
debugger-for-chrome|msj|4.7.0
vetur|oct|0.12.5
px-to-rem|sai|1.2.3
vue-vscode-snippets|sdr|1.3.0
open-in-browser|tec|1.1.0
vscode-react-native|vsm|0.6.12
heyui-snippets|vvp|0.1.1
quokka-vscode|Wal|1.0.132
iis-express|war|1.1.2
JavaScriptSnippets|xab|1.7.0
html-css-class-completion|Zig|1.17.1

(3 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
> Update failed

**Comment by zhangenming** [comment]
me,too
window 7's err
can't run updata.exe

**Comment by zhangenming** [comment]
![_15317494802601](https://user-images.githubusercontent.com/21235555/42762637-61daaddc-8943-11e8-95d9-a78d54332a7b.png)

**Comment by joaomoreno** [comment]
This issue was closed because it doesn't meet our standards of a properly filled issue. Please read our guide about [Submitting Bugs and Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).
