### ISSUE TITLE
Request for new Tab - File Explorer

### ISSUE THREAD

**Issue by vijaypushkin** [Microsoft/vscode#53933]
I feel the present Explorer tab is crowds with

- Open Editors
-  Project Tree
- (File) Outline
- and GitLens

It would be nice if File Outline and other plugins that related to files were moved to new tab - **File Explorer** or some other relevant name.

**Comment by isidorn** [comment]
GitLens fixed this in latest release.
Outline will probably move somewhere fyi @jrieken
