### ISSUE TITLE
Support a goto file action in the explorer

### ISSUE THREAD

**Issue by sahas-** [Microsoft/vscode#5393]
- VSCode Version: 1.0.0
- OS Version: Mac

Please ignore if its suggested already. Ask is, would it be nice to have "search and filter" capability in project explorer. This will become handy especially for Node development, when we bring in some external module, that'll bring in boat load of its own dependencies as well and the list is so huge. If we have to verify something inside the node_modules folder, its a lot of scroll up and down. So capability something similar to "Visual studio solution explorer" search and filter will be nice.

**Comment by egamma** [comment]
There is the `files.exclude` setting, pls see  https://code.visualstudio.com/docs/editor/codebasics#_explorer. Does this cover your needs?

**Comment by egamma** [comment]
Seach is covered by `Goto>File`. Closing the issue both search and filter is supported.

**Comment by sahas-** [comment]
@egamma, I understand its possible to get to the file I want without using any of these, just scrolling up and down inside node_modules. What I experienced was, I had problems with my own npm module not installing its own dependencies. Unfortunately it starts with "g" and Its right in the middle of 100s of other node_modules. Whenever I wanted to verify whether my module has its dependencies installed, it made more sense to stay within the folder explorer instead of using shift+cmd+f (search) or Goto-->File ..at some point, I started using console, it was very easy to write "tree" function in my profile to filter and show me the tree view of node_modules and modules that start with "g". So, my point is these capabilities might exist but not just useful for this context. IMO,  may be one of those many but console wins vscode over on something the editor could easily do.

**Comment by eamodio** [comment]
@egamma It would also be great to on-demand filter the explorer pane to reduce the "noise" when working on a subset of files. For example, I usually work with VSCode open to the root of our repo (with many projects in it) and I am lately finding myself needing to update common things across the projects (say in `package.json`, `project.json`, etc), so right now I have to either scroll around in the explorer pane or use Goto->File -- which forces me to have to type the file name in over an over. If I could just filter the explorer pane to show all `project.json` files it would be quick and painless.

**Comment by egamma** [comment]
I've updated the title to capture the original feature request. 

@eamodio your comment is a valid feature request, please file a separate issue for it.

**Comment by eamodio** [comment]
@egamma Thanks! Added https://github.com/Microsoft/vscode/issues/9373

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
