### ISSUE TITLE
[Feature request]Support search in git changes panel

### ISSUE THREAD

**Issue by mnikn** [Microsoft/vscode#53936]
Is it possible to support the vscode search when in the git changes panel?

![search support](https://user-images.githubusercontent.com/12381740/42495980-43438114-8457-11e8-92de-575e2908043d.png)

**Comment by roblourens** [comment]
You want to search inside files that are changed in git? Or what? Please explain some more.

**Comment by mnikn** [comment]
@roblourens Exactly I think it just like a search bar in the vscode, when you enter the change file content or file name  the unmatched file will be filtered, so that we can select and commit special changes easily when a lot of changes in the git.
