### ISSUE TITLE
编辑器经常卡死，无法编辑文件

### ISSUE THREAD

**Issue by boylufeng20141007** [Microsoft/vscode#53934]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by boylufeng20141007** [comment]
已经是最新的版本

**Comment by Tyriar** [comment]
Translation:

> The editor is often stuck and cannot edit the file
>
> Already the latest version

**Comment by Tyriar** [comment]
@boylufeng20141007 what does "stuck" mean? Can you post a screenshot or more info about why you can't edit?
