### ISSUE TITLE
No colors in debug console in 1.25

### ISSUE THREAD

**Issue by nvomedia** [Microsoft/vscode#53930]
- VSCode Version: 1.25
- OS Version: Windows 10 

Steps to Reproduce:

1. Run an program, like Node.JS with the package chalk to write some coloured lines, or run an gulp command
2. In the previous versions the colours (not all, but the most) are shown up in the debug console, in this version all text is white.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
@nvomedia can you please provide an example javascript program for which the colors are nicely rendered in the previous version and are not rendered in the new version?
Thanks

fyi @danielfrankcom

**Comment by nvomedia** [comment]
I had installed 'cmder' as Terminal with these lines in my settings:

```    "terminal.integrated.shellArgs.windows": [
        "/k C:\\cmder\\vendor\\init.bat"
    ],
    "terminal.integrated.shell.windows": "C:\\Windows\\SysWOW64\\cmd.exe"
```

But after disabling this (and a restart of VS Code) it's still not working.

**Comment by andrewdbond** [comment]
@nvomedia colors in chalk still don't work, but different colors do appear in https://github.com/winstonjs/winston for different levels.

Also, possibly related: https://github.com/chalk/supports-color/issues/79

(I know this issue is closed.)
