### ISSUE TITLE
Provide a shortcut function that will reload all extensions

### ISSUE THREAD

**Issue by elron** [microsoft/vscode#53947]
Sometimes my extensions just stops working suddenly. Later on (about 2 minutes later) I recieve a popup message that tells me that the exensions has stopped working, and there is a reload button. When I press it, it reloads all extensions without reloading the whole window. (which is great)
But sometimes I don't want to wait that 2 minutes until that popup message appears, I want to reload it instantly.
Therefore, I would like a built-in function just like ">Reload Window", but only for ">Reload Extensions".

Is that possible?
Thank you

**Comment by sandy081** [comment]
It looks like this is a request for `Restart Extension Host` command.

**Comment by elron** [comment]
Yeah, seems like you are right. Is the command available?
Because I can't see the `Restart Extension Host` command:
![image](https://user-images.githubusercontent.com/395792/42657696-b8b6fa90-862b-11e8-8073-ec626e16ac3d.png)

**Comment by sandy081** [comment]
@elron No
