### ISSUE TITLE
Dash in snippets prefix broken

### ISSUE THREAD

**Issue by Yago** [Microsoft/vscode#53945]
Since the May or the June release, the snippets containing a dash (`-`) inside cannot be used when fully typed.

 

- VSCode Version: 1.25.0
- OS Version: MacOS 10.13.5

Steps to Reproduce:

1. Create a user snippet with a prefix containing a dash (`-`) inside
2. Try to use it
3. (Define `"editor.snippetSuggestions": "top"` in your settings to show it on top)

![snippets](https://user-images.githubusercontent.com/2025924/42501553-3dad041e-8434-11e8-9690-dc0744a77daf.gif)

**Comment by jrieken** [comment]
Nice find @Yago. This is a regression from #37166 - we now re-compute snippets when a trigger character is hit and in css, dash (`-`) seems to be such a character. The issue is that in the presence of a trigger character selecting snippets is more strict.

**Comment by Yago** [comment]
Ok nice to know. Happy to help 😄

**Comment by jrieken** [comment]
Ok, I have pushed a bigger change is how snippets are computed. That change fixes this issue and should make snippet suggestions be more stable in general. Tho, there might be some oversights and I would *really* appreciate more feedback. You can try my fix and change with next insiders (in ~24hr from now): https://code.visualstudio.com/insiders/
