### ISSUE TITLE
ts reports error on opened file even it is in the tsconfig.json exclude list

### ISSUE THREAD

**Issue by hkjeffchan** [Microsoft/vscode#53944]
- VSCode Version: 1.25.0
- OS Version: Mac 10.13.5

Steps to Reproduce:
1. add "node_modules" in tsconfig.json exclude list
2. add a file in node_modules and make some syntax error and it will be reported in "PROBLEMS" panel
3. error will persist after closing the file or even deleting the file. It will disappear after reloading vscode.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
`exclude` only excludes the file from that project. If you open the file, we still provide intellisense and type checking on it

See #52348 for more details about the problem. We are looking into a better experience for this
