### ISSUE TITLE
SCM: Add option to always show inline actions

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/vscode#53942]
Currently I always need to hover with the mouse across all changed files to see their commit status:

![don t auto hide](https://user-images.githubusercontent.com/9283914/42274964-d940af66-7f8e-11e8-89c0-7c06dcee7644.gif)

Can we please get an option to stop status icons/buttons from auto-hiding?

**Comment by bpasero** [comment]
> Currently I always need to hover with the mouse across all changed files to see their commit status

Why is that? How do the icons express any commit status?

**Comment by SetTrend** [comment]
They either show a "+" or a "-" sign.

**Comment by joaomoreno** [comment]
They are in the `Aederungen` section. If you stage them, they will appear in another section, right?

**Comment by joaomoreno** [comment]
Well, who else was I addressing?

> They are in the `Aederungen` section. If you stage them, they will appear in another section, right?

So... what's the answer?

**Comment by joaomoreno** [comment]
Here's how it works:

- In git, when you modify a file, it becomes **modified**, we show it in the **Changes** view.
- You can then **stage** it. That's what the **plus** does. And when you do, we show it in another section: the **Staged Changes** view.

The `+` doesn't transform to a `-`, the file actually goes into another group. Can you confirm?

**Comment by SetTrend** [comment]
Yes, I can confirm.

Yet, it's utterly hard to quickly distinguish between this:

![1](https://user-images.githubusercontent.com/9283914/43035123-425178a6-8cea-11e8-99bf-70d6085b9c0c.png)
<br/>

... and that:

![2](https://user-images.githubusercontent.com/9283914/43035125-471e8e64-8cea-11e8-916a-bee814ac0145.png)

**Comment by SetTrend** [comment]
I don't know which size of screen you're working with, so here's the same screenshots scaled down for UX tests, to simulate a quick grasp while still having all the time to examine here:

![1s](https://user-images.githubusercontent.com/9283914/43035220-39ef555a-8cec-11e8-873b-54a137690e12.png)

![2s](https://user-images.githubusercontent.com/9283914/43035221-3c867898-8cec-11e8-94b1-c599f0c2589f.png)

**Comment by SetTrend** [comment]
Hi @joaomoreno : The `needs more info` flag is still set. Do you want me to provide more info?

**Comment by joaomoreno** [comment]
I don't understand why it is hard to distinguish. The section names are very different.

**Comment by SetTrend** [comment]
Let's not argue about users being required to read and interpret subsidiary texts, particularly when they are hidden due to, say 50 files about to be pushed. Let's not argue about usability and mens' inability to quickly grasp static texts compared to the simplicity of recognizing a simple iconic sign.

I gave a visual example by providing the thumbnails above. In these examples it's not easy at all to tell one text from the other. Yet even with the thumbnails above one could simply tell "`-`" from "`+`".

You argue from a standpoint of someone with nothing else in mind than these two texts. I'm talking about feasibility, usability in contrast to information hiding.

So, for a moment, let's not argue about usability. Let's just restrain to argue about why VS Code hides functional information at all. What is the advantage in showing a useless black surface, hiding workflow relevant information? Why has deliberate functionality been added to VS Code to hide/reveal information instead of just showing necessary information statically? Why is hiding information an advantage to the VS Code team, worth implementing an animation?
