### ISSUE TITLE
Terminal text goes offscreen & is occasionally offset

### ISSUE THREAD

**Issue by zebslc** [Microsoft/vscode#53946]
Issue Type: <b>Bug</b>

After installing the latest version I notice that the terminal text now goes offscreen instead of wrapping on my 14" laptop screen.  Some text also appears to start at offset positions instead of to the left.

Expected - long text wraps correctly and all new lines start on the left
Actual - text goes offscreen with no scroll option to view it and text at varying positions

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (6.21GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
angular-material|1to|0.13.0
angular-material-snippets|4tr|0.3.1
html-snippets|abu|0.2.1
jest-snippets|and|1.4.0
ng-template|Ang|0.1.9
angulardoc-vscode|Ang|6.0.6
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitlens|eam|8.4.1
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.33
vscode-npm-script|eg2|0.3.5
vscode-great-icons|emm|2.1.36
prettier-vscode|esb|1.5.0
vs-code-xml-format|fab|0.1.5
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
gc-excelviewer|Gra|2.1.24
json2ts|Gre|0.0.6
angular-bootstrap|her|4.0.9
angular2-switcher|inf|0.1.9
angular-essentials|joh|0.3.2
Angular2|joh|6.1.1
angular-extension-pack|loi|0.5.3
Angular2Tests|Mar|0.7.3
vscode-apache|mrm|1.1.1
vscode-azureappservice|ms-|0.8.1
azure-account|ms-|0.4.1
vs-keybindings|ms-|0.2.0
team|ms-|1.136.0
debugger-for-chrome|msj|4.7.0
angular2-inline|nat|0.0.17
ng-fortytwo-vscode-extension|NG-|0.0.9
vscode-jest|Ort|2.8.0
material-icon-theme|PKi|3.5.1
typescript-hero|rbb|2.3.2
git-merger|sha|0.4.1
simontest|Sim|0.18.4
autoimport|ste|1.5.3
move-ts|str|1.11.3
bootstrap4-vscode|the|4.1.1
Angular2|UVB|0.4.1
html-css-class-completion|Zig|1.17.1
ab-html-formatter|zov|0.0.2

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/51479
