### ISSUE TITLE
New installer breaks Windows env:PATH

### ISSUE THREAD

**Issue by jimcroft** [Microsoft/vscode#53941]
Issue Type: <b>Bug</b>

I'm using the new insider user (rather than system wide) installer. It seems to be adding an extra `;` char into the my users path. The Python extension complains about this on @code startup.

The path looks like this
`....;C:\Users\jim\AppData\Roaming\npm;;C:\Users\jim\AppData\Local\Programs\Microsoft VS Code Insiders\bin;`

VS Code version: Code - Insiders 1.26.0-insider (adfa9ce9778a6e79197477fcc60cb5420a31979a, 2018-07-10T05:19:09.185Z)
OS version: Windows_NT x64 10.0.17711

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (8.04GB free)|
|Process Argv|C:\Users\jim\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
Gradle|caz|1.1.2
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.18.0
vscode-eslint|dba|1.4.12
githistory|don|0.4.1
gitlens|eam|8.4.1
tslint|eg2|1.0.33
vsc-material-theme|Equ|2.3.0
git-project-manager|fel|1.6.1
code-runner|for|0.9.3
docker-explorer|for|0.1.6
terminal|for|0.0.10
gc-excelviewer|Gra|2.1.24
docker-linter|hen|0.5.0
beautify|Hoo|1.3.2
rest-client|hum|0.19.0
Ionide-fsharp|Ion|3.22.3
Ionide-Paket|Ion|1.12.0
puppet-vscode|jpo|0.10.0
language-haskell|jus|2.5.0
vscode-github|Kni|0.30.0
terraform|mau|1.2.3
theme-monokai-pro-vscode|mon|1.1.8
python|ms-|2018.6.0
csharp|ms-|1.15.2
Go|ms-|0.6.84
PowerShell|ms-|1.7.0
vsliveshare|ms-|0.3.379
debugger-for-edge|msj|1.0.2
gradle-language|nac|0.2.3
vscode-docker|Pet|0.0.27
seti-icons|qin|0.1.3
Ruby|reb|0.18.0
java|red|0.28.0
datetime|rid|1.0.5
vscode-icons|rob|7.24.0
partial-diff|ryu|1.2.0
jenkinsfile-support|sec|0.1.0
code-settings-sync|Sha|2.9.2
haskelly|UCL|0.5.4
vscode-java-debug|vsc|0.10.0
vscode-java-test|vsc|0.7.0

(4 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
I believe the code to add to the PATH didn't change... so it can only be that your user's PATH variable was already ending in `;` prior to installing VS Code Insiders. Is that possible?

**Comment by jimcroft** [comment]
I'll double check and comment here shortly. Certainly I only noticed the Python extension complaining about it after I switched to the new installer.

**Comment by jimcroft** [comment]
False alarm. Looks like it was nodejs or chocolatey messing with the path.

**Comment by joaomoreno** [comment]
Thanks for the update.
