### ISSUE TITLE
vsCode freezes when an external .bat file update files in the opened folder in vsCode

### ISSUE THREAD

**Issue by keserwan** [Microsoft/vscode#53943]
Issue Type: <b>Bug</b>

vsCode freezes when an external .bat file update files in the opened folder in vsCode.
I have a .bat file that copies an external folder to the vsCode project.
This external folder has more than 300 files.
After execution, vsCode freezes, except the main menu, but I can't do anything, even I cant close vsCode.
After like 30 seconds, vsCode shows a dialog with the buttons (re-open, close)

I hope this got fixed, I use this .bat a lot.
everytime I have to re-open vsCode.

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (6.89GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Development\Pro-Leagues\Proleague_BO_Angular|
|Screen Reader|no|
|VM|80%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
php-debug|fel|1.12.3
php-intellisense|fel|2.3.3
debugger-for-chrome|msj|4.7.0
vscode-docker|Pet|0.0.27
java|red|0.28.0
autoimport|ste|1.5.3
vscode-java-debug|vsc|0.10.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.7.0
vscode-maven|vsc|0.9.0

</details>

**Comment by Tyriar** [comment]
What does the batch file do?
