### ISSUE TITLE
[css] warn about using 0px in outline

### ISSUE THREAD

**Issue by David-Else** [Microsoft/vscode#53948]
- VSCode Version: 1.25.0
- OS Version: fedora 28

Steps to Reproduce:

add "css.lint.zeroUnits": "warning", to your prefs:

1. add this to a CSS file `outline: black 0px solid;` or `outline: black 0em solid;`
2. see there is no warning from the linter

it works for  `margin: 0px;`

Does this issue occur when all extensions are disabled?: Yes

**Comment by octref** [comment]
https://stylelint.io/user-guide/rules/length-zero-no-unit/

You can use this extension.

**Comment by David-Else** [comment]
Please re-read the issue. It is a bug in vs code, no extension is needed.

"css.lint.zeroUnits" is built into vs code, **but it has a bug**. It WORKS for margin, but not outline. This is not correct behavior by anyone's definition.

**Comment by octref** [comment]
Oh I see, sorry.
