### ISSUE TITLE
Emmet ignore css.intUnit setting when provide value with fraction

### ISSUE THREAD

**Issue by PixelT** [Microsoft/vscode#53957]
- VSCode Version: 1.25.0
- OS Version: macOS 10.13.5

Steps to Reproduce:

1. I have in settings:
```
"emmet.preferences": {
    "css.intUnit": "rem"
}
```
2. In scss file I write:
```
.test {
    m5
}
```
and hide tab after `m5`

I expected to get: `margin: 5rem;`
I get: `margin: 5rem;`
This is OK.

3. I write in scss file:
```
.test {
    m1.5
}
```
and hide tab after `m1.5`

I expected to get: `margin: 1.5rem;`
I get: `margin: 1.5em;`
This is NOT OK. I got `em` instead of `rem`

Does this issue occur when all extensions are disabled?: Yes

**Comment by ramya-rao-a** [comment]
Add `"css.floatUnit": "rem"` under your emmet preferences in the settings.

**Comment by PixelT** [comment]
It works, thanks @ramya-rao-a
