### ISSUE TITLE
End of line override doesn't work in Windows10

### ISSUE THREAD

**Issue by darulbaby** [Microsoft/vscode#53958]
Issue Type: <b>Bug</b>
</br>
</br>
This problem looks like with git operation, when we do git pull it'll fetch updated file from remote repository to local. At the time file mode always set with CRLF mode, this mode not override by VSC application as per users settings.
</br>
</br>
Steps to reproduce:</br>
1. Work with any Git repository at Windows environment</br>
2. Set "files.eol" from "\r\n" to "\n" in user settings json file. basically we trying to set CRLF to LF for Linux support</br>
3. Close Visual Studio code application and then re-open</br>
4. Do git pull form the remote repository</br>
5. Open any file that'll shows with CRLF mode, not with LF mode which is we override this setting with users setting not working as expected.</br></br>

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.17134

**Comment by bpasero** [comment]
This setting only applies when you create new files. To convert the line ending, toggle it from the status bar.
