### ISSUE TITLE
"insertSpaceAfterFunctionKeywordForAnonymousFunctions" settings are not reflected

### ISSUE THREAD

**Issue by fahimmahmoodmir** [Microsoft/vscode#53967]
I have been trying to disable spaces after anonymous functions with following format settings:

`"javascript.format.insertSpaceAfterFunctionKeywordForAnonymousFunctions": false`

After setting this property (and restarting also several times vs code) its showing following behavior:

![image](https://user-images.githubusercontent.com/2732245/42516663-8da62a48-845e-11e8-819a-16909eb22e49.png)

Expected behavior after above property:
![image](https://user-images.githubusercontent.com/2732245/42516801-b5b47896-845e-11e8-811c-ae2739984bea.png)

Visual Studio Code version: 

![image](https://user-images.githubusercontent.com/2732245/42516902-de799f68-845e-11e8-8b9c-6d08cadba76c.png)

Operating System: Ubuntu 18.04

is there any other property we need to change?

**Comment by mjbvz** [comment]
Does this still happen if you disable all extensions?
