### ISSUE TITLE
i hope there can be option for choosing language

### ISSUE THREAD

**Issue by YuSuu** [Microsoft/vscode#5396]
- VSCode Version:1.0.0
- OS Version:win 7

im a china user,
and im already used to type english commands in vs code
when everything became chinese i feel not that much familiar.
and its indeed much more easy to type sevaral char instead type PinYin
anyway ,i hope there can be language optiona

Steps to Reproduce:

1. 
2.

**Comment by egamma** [comment]
There already is the `Configure Language` command available in the command palette, pls see
https://code.visualstudio.com/docs/customization/locales
