### ISSUE TITLE
Autocomplete messed up after dot in strings

### ISSUE THREAD

**Issue by henrikra** [Microsoft/vscode#53962]
I have type file for my translation function like this
```typescript
declare namespace typed_i18n {
  interface TFunction {
    (_: 'login.title', __?: {}): string;
    (_: 'login.description', __?: {}): string;
    (_: 'login.sendEmailAgree', __?: {}): string;
    (_: 'login.termsOfUse', __?: {}): string;
    (_: 'login.privacyPolicy', __?: {}): string;
    (_: 'login.sendEmailButton', __?: {}): string;
    (_: 'login.emailInputPlaceholder', __?: {}): string;
    (_: 'login.errorWrongEmailTitle', __?: {}): string;
    (_: 'login.errorWrongEmailDescription', __?: {}): string;
    (_: 'login.errorGeneralEmailTitle', __?: {}): string;
    (_: 'login.errorGeneralEmailDescription', __?: {}): string;
    (_: 'login.loginErrorTitle', __?: {}): string;
    (_: 'login.loginErrorDescription', __?: {}): string;
    (_: 'login.openEmailAppErrorTitle', __?: {}): string;
    (_: 'login.openEmailAppErrorDescription', __?: {}): string;
    (_: 'login.openEmailAppErrorConfirm', __?: {}): string;
  }
}
export = typed_i18n;
```

And when I start typing the autocomplete works fine like this:
![image](https://user-images.githubusercontent.com/12229968/42512755-1d07a5e6-845e-11e8-812f-ed2ea0734e8c.png)

But when I add the dot it loses match to the `login` part (notice that `login` does not have blue color anymore)
![image](https://user-images.githubusercontent.com/12229968/42512874-52d997f6-845e-11e8-9651-3323f8ecbc9c.png)

Then I start to type `email` but the autocomplete is messed up at this point:
![image](https://user-images.githubusercontent.com/12229968/42512927-7096b27e-845e-11e8-84b1-66a9e30b5184.png)

So looks like it is bug in VsCode 🐛 

- VSCode Version: 1.25.0
- OS Version: macOS High Sierra 10.13.5

Does this issue occur when all extensions are disabled?: Yes

**Comment by henrikra** [comment]
@jrieken So it is bug in vscode or bug in my types?

**Comment by jrieken** [comment]
Your types are fine, it's a bug in the TypeScript extension (which is part of vscode).
