### ISSUE TITLE
Cannot edit break point in side by side code panels

### ISSUE THREAD

**Issue by sfjadi2010** [Microsoft/vscode#53978]
- VSCode Version: 1.25.0
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Open code file in one panel and add a break point and edit break point for expression. Please don't close the expression model by hitting enter key.
2. Open other code file in side panel and add break point and try to edit it. It will not open.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sfjadi2010** [comment]
Did you follow the reproduce steps? I'm getting following error in Developer Tools

![image](https://user-images.githubusercontent.com/1775622/42590301-7497d4da-8511-11e8-805c-87fb9772d6d6.png)

Thanks for checking.

**Comment by isidorn** [comment]
@sfjadi2010 thanks for nice steps. I can reproduce this

**Comment by sfjadi2010** [comment]
Thanks for checking it and sorry for my poor English.
