### ISSUE TITLE
tabbed formatting not working on only JavaScript files

### ISSUE THREAD

**Issue by southwestking** [Microsoft/vscode#5397]
- VSCode Version: 1.0.0
- OS Version: windows 10

Steps to Reproduce:

1. add to user settings:
{
	"editor.formatOnType": true,
    "editor.tabSize": 3
}
2. create a javasctipt file:
if(true)
console.log(true);
3. verify tab spacing (there should be 3 however there is 5 the default)

**Comment by dbaeumer** [comment]
I can't reproduce this. @southwestking any additional info. Could you attach a animated gif ?

![bug](https://cloud.githubusercontent.com/assets/1931590/14598556/0a4e7fce-0553-11e6-992c-bbf0772075c8.gif)

**Comment by southwestking** [comment]
Closing this issue, the problem must have been have occurred during the update to 1.0.0. I solve it by coping my code to a new file and then formatting seemed to work just fine.
