### ISSUE TITLE
Enter key not working on macOS

### ISSUE THREAD

**Issue by katbow** [Microsoft/vscode#53972]
Issue Type: **Bug**

VS Code version: Code 1.25.0
OS version: Darwin x64 17.6.0

**Steps to Reproduce:**
Unclear. I've had it happen with only 1 file open, many files open, extensions disabled, etc. Enter will stop working seemingly at random.

**Does this issue occur when all extensions are disabled?:** Yes

This issue was reported previously [here](https://github.com/Microsoft/vscode/issues/13170) and [here](https://github.com/Microsoft/vscode/issues/12929), however I cannot see a resolution for mac. There is a comment in the linked issue to use `fn + enter`, but that doesn't work either. 

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
erb|Cra|0.0.1
rails|bun|0.8.0
vscode-gemfile|bun|0.0.2
gitlens|eam|8.4.1
code-runner|for|0.9.3
referenceshelper|gay|0.2.2
ruby|gro|0.0.6
endwise|kai|1.2.2
haml|kar|1.1.0
vscode-elixir|mjm|1.1.0
vsliveshare|ms-|0.3.379
rails-run-spec-vscode|nok|0.1.2
vscode-ruby-ctags|oto|1.4.1
Ruby|reb|0.18.0
rails-go-to-spec|spo|0.0.1

</details>

**Comment by alexandrudima** [comment]
@katbow Does this reproduce when running with all extensions disabled? `code --disable-extensions`

**Comment by katbow** [comment]
@alexandrudima yes it does.

**Comment by alexandrudima** [comment]
@katbow can you search to see which keybindings you have for "Enter" in the keybindings editor?:

Do you have the same ones as defined here:

![image](https://user-images.githubusercontent.com/5047891/43706530-e0a00c02-9965-11e8-940c-8944be2cbd6f.png)

**Comment by katbow** [comment]
![image](https://user-images.githubusercontent.com/1287388/43709318-60f009cc-9964-11e8-8fc1-8ba49b1e0416.png)

Looks like I am missing `breadcrumbs.selectFocus...` and have `endwise.enter` & endwise.checkForAccept...` as extra from that list.

**Comment by alexandrudima** [comment]
@katbow Ok, it looks like an extension has added two commands on Enter: `endwise.*`. Are you familiar with what these commands do, do you use them, do you know which extension defines them?

You can:
- disable/uninstall the extension
- (or) right click on the commands and remove them

I would also suggest that you reach out to the extension that defines these commands to point out that something is broken with them.
