### ISSUE TITLE
gcc problemMatcher does not work with absolute paths

### ISSUE THREAD

**Issue by jonatangoebel** [Microsoft/vscode#53971]
Steps to Reproduce:

1. Create a simple 'Hello World' app.
2. Create a task to compile it with gcc passing the absolute path to the source file as argument.
3. Force a build error.
4. Try to open the file by clicking the Problem Report

Problem Example:
![image](https://user-images.githubusercontent.com/41071594/42521697-da02e71a-843f-11e8-90f4-cfd352555807.png)

- VSCode Version:
Version: 1.26.0-insider
Commit: adfa9ce9778a6e79197477fcc60cb5420a31979a
Date: 2018-07-10T05:18:58.178Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

- VSCode Extensions:
C/C++ IntelliSense: 0.17.6

- OS Version: Ubuntu 16.04 LTS

Code for easy copy-paste:

**example.c**
```
#include <stdio.h>
#include <stdlib.h>

#ifdef FORCE_BUILD_ERROR
#error "build error"
#endif

int main(int argc, char const *argv[])
{
    /* code */
    printf("Hello World\n");
    return 0;
}
```
**task.json**
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "type": "shell",
            "command": "gcc",
            "args": [
                "`pwd`/example.c",
                "-DFORCE_BUILD_ERROR"
            ],
            "group": "build",
            "problemMatcher":"$gcc"
        }
    ]
}
```

**Comment by Gama11** [comment]
Problem matchers only work with either relative or absolute paths: #449

Related issue on the vscode-cpptools repo: https://github.com/Microsoft/vscode-cpptools/issues/1915

**Comment by jonatangoebel** [comment]
Hum, so it is working as intended? It does not support absolute paths.

How can I vote for the feature request?

Should I close this ticket?

**Comment by jonatangoebel** [comment]
Can I set this property separately for each task or tasks.json file? If yes, how do I do that? I added it to my tasks.json file but had no effect.

I do work with both relative and absolute path, but being able to configure it for different tasks/folder/workspace would be helpful.

**Comment by dbaeumer** [comment]
@jonatangoebel this can be configured per task. Simply use the above for the `"problemMatcher":"$gcc"` in the task you showed.

If you can't get it to work can you provide me with a GitHub repository that demos what you want to achieve and then I can have a look.

**Comment by jonatangoebel** [comment]
@dbaeumer I tried it again and it worked just fine, don't remember what I did wrong last week.

Thanks, for the support.
