### ISSUE TITLE
Clicking on references codelens shows Loading... forever

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#53979]
Issue Type: <b>Bug</b>

- Enable the references codelens for typescript
- For any symbol, run `Find All References`. Notice that you see the results in the peek window
- Escape
- For the same symbol, click on the references codelens above it. Notices that you see "Loading..." forever.

This happens only in Insiders and not in Stable (1.25) 

I notice the same for Go, so this might not be a language specific issue

VS Code version: Code - Insiders 1.26.0-insider (adfa9ce9778a6e79197477fcc60cb5420a31979a, 2018-07-10T05:19:09.185Z)
OS version: Windows_NT x64 10.0.17134

Installed Extension: Go

**Comment by mjbvz** [comment]
Duplicate of #53902
