### ISSUE TITLE
Trailing bracket always one space off on paste from DevTools

### ISSUE THREAD

**Issue by ch4ppy** [Microsoft/vscode#53975]
Title pretty much says it all. When I paste code from Chrome DevTools the closing bracket is ALWAYS one space to the left of being properly indented. Like so: 
<img width="320" alt="screen shot 2018-07-10 at 9 34 41 am" src="https://user-images.githubusercontent.com/26723545/42524217-b6035a9a-8424-11e8-898f-497b8dfba6f8.png">
Is there a setting somewhere that will fix this? I already tried "indent on paste" addon from marketplace but it made it worse honestly.

**Comment by rebornix** [comment]
Sorry for reaching out late, can you share more about the details? Like what does the file you pasting into look like? What's the content you copy from Chrome Dev Tools look like? I can't reproduce this issue.
