### ISSUE TITLE
Remove filename from top bar of VSCode or make it optional

### ISSUE THREAD

**Issue by danielcasler** [Microsoft/vscode#53982]
When you have many windows open and you have long filenames, it becomes very difficult to quickly jump between projects when mousing over all your open windows preview. All you see is the filename and if you have multiple index.js files open, how do you quickly know which one is which?

Perhaps this could be a feature where you can display file name and project name or just project name.

Just project name would make it much easier to quickly jump between projects from the preview navigation.

Thanks

**Comment by bpasero** [comment]
Can be done using `window.title` setting.

![image](https://user-images.githubusercontent.com/900690/42551939-2b25fc28-84da-11e8-8faa-d9ed6a00ebcb.png)
