### ISSUE TITLE
Started to consume a lot of battery

### ISSUE THREAD

**Issue by romariolopezc** [Microsoft/vscode#53985]
Issue Type: <b>Performance Issue</b>

Don't know how to reproduce

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:02:28.333Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|8.00GB (0.09GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   12	    90	 39470	code main
    0	    66	 39471	   gpu-process
    0	    25	 39893	   shared-process
    0	   188	 56586	   window (lib/roque/caller/extra_details_request.rb — roque)
    0	    66	 56588	     extensionHost
    0	   262	 56592	       ruby /Users/romario/.rvm/gems/ruby-2.5.1/bin/solargraph socket --port 0
    0	    57	 62919	       electron_node jsonServerMain.js 
    0	    25	 56589	     watcherService
    0	    16	 57232	     searchService
    0	    25	 63454	     terminal
    0	     0	 63455	       /bin/zsh -l
    0	    90	 65136	   window (Issue Reporter)
    0	     0	 65140	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (lib/roque/caller/extra_details_request.rb — roque)
|    Folder (roque): 671 files
|      File types: rb(584) yml(58) json(9) txt(7) md(2) lock(1) gitignore(1)
|                  gemspec(1) ruby-version(1) js(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.27
project-manager|ale|8.0.0
rails|bun|0.8.0
vscode-gemfile|bun|0.0.2
solargraph|cas|0.17.5
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
erb|Cra|0.0.1
smali|cra|1.0.1
vscode-markdownlint|Dav|0.18.0
mustache|daw|1.1.1
githistory|don|0.4.1
vscode-babel-coloring|dza|0.0.4
vscode-html-css|ecm|0.2.0
vscode-npm-script|eg2|0.3.5
vscode-great-icons|emm|2.1.36
prettier-vscode|esb|1.5.0
file-icons|fil|1.0.12
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
beautify|Hoo|1.3.2
node-module-intellisense|lei|1.5.0
ruby-rubocop|mis|0.7.0
vscode-elixir|mjm|1.1.0
python|ms-|2018.6.0
csharp|ms-|1.15.2
Go|ms-|0.6.84
elmmet|nec|1.0.0
rpa-eslint-snippets|rav|0.0.2
Ruby|reb|0.18.0
java|red|0.28.0
sass-indented|rob|1.4.9
final-newline|sam|0.3.2
elm|sbr|0.18.0
code-settings-sync|Sha|2.9.2
shader|sle|1.1.3
ayu|tea|0.14.0
vscode-java-debug|vsc|0.10.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.7.0
vscode-maven|vsc|0.9.0
vim|vsc|0.14.2
vscode-wakatime|Wak|1.2.3

(10 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Power consumption is typically linked to CPU usage and I notice that there isn't much happening in the process information you posted. Could you run `code --status` when you see a slow down occur? That will tell us which process is to blame.

I suspect it's related to one of your extensions as you have 44 of them (and that's normally what these types of issues are).

**Comment by romariolopezc** [comment]
VSCode warn you about some extensions using excessive amount of CPU??
