### ISSUE TITLE
existing tabs in vertical/horizontal splits should be reused

### ISSUE THREAD

**Issue by nkoroste** [Microsoft/vscode#53981]
Issue Type: <b>Bug</b>

I usually have 3 vertical splits with multiple open file tabs in each. 

When clicking on a class reference in vertical split 1, if that class is already opened in split 2 I expect it to gain focus in that split rather than open a new tab in a current split (1). 

This is true not only when clicking on a class reference, but for all other actions like:
1. open command platter, type class name, if I already have it open in a split it should gain focus in that split (or come to focus). 
2. when using "Find all references" and clicking on the overlay 
3. clicking on the file in the explorer
4. I'm sure there are more entry points that I'm missing. 

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:10:37.273Z)
OS version: Linux x64 4.9.0-6-amd64

<details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
ActiveFileInStatusBar|Ros|1.0.3
terminal-tabs|Tyr|0.2.0
path-intellisense|chr|1.4.2
dart-code|Dar|2.15.0
fileheadercomment|doi|0.0.3
githistory|don|0.4.1
vscode-great-icons|emm|2.1.36
vsc-material-theme|Equ|2.3.0
language-fidl|fuc|0.0.2
python|ms-|2018.6.0
cpptools|ms-|0.17.6
vscode-gn|npc|1.0.0
vscode-yaml|red|0.0.13
code-spell-checker|str|1.6.10
gitblame|wad|2.4.2
vscode-proto3|zxh|0.2.1

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
Configure `"workbench.editor.revealIfOpen": true`
