### ISSUE TITLE
Cannot disable format on save

### ISSUE THREAD

**Issue by philsher93** [Microsoft/vscode#53988]
Version: 1.25.0

Steps:

1. Open User Settings
2. add `"editor.formatOnSave": false` to user settings
3. restart code, try to save an html file without it formatting, still formats.

**Comment by philsher93** [comment]
CPUs | Intel(R) Xeon(R) CPU W3520 @ 2.67GHz (8 x 2666)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwarerasterization: disabled_softwarevideo_decode: enabledvideo_encode: enabledvpx_decode: unavailable_softwarewebgl: enabledwebgl2: enabled
Memory (System) | 13.98GB (9.52GB free)
Process Argv | C:\Program Files\Microsoft VS Code\Code.exe
Screen Reader | no
VM | 0%

jslint	ajh	1.2.1
jshint	dba	0.10.19
vscode-eslint	dba	1.4.12
xml	Dot	2.3.1
tslint	eg2	1.0.33
auto-close-tag	for	0.5.6
beautify	Hoo	1.3.2
vscode-JS-CSS-HTML-formatter	lon	0.2.3
prettify-json	moh	0.0.3
team	ms-	1.136.0
debugger-for-chrome	msj	4.7.0
vetur	oct	0.12.5
vscode-react-native	vsm	0.6.12

**Comment by aeschli** [comment]
I can not reproduce. Please check
- that this is not caused by an extension, e.g `vscode-JS-CSS-HTML-formatter`
- that the setting `"editor.formatOnSave": false` is not also set in the workspace settings
- that there's no override for html in your settings
```
"[html]": {
    "editor.formatOnSave": true
}
```
