### ISSUE TITLE
Process explorer not showing renderer processes

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#53999]
Not sure if this is easy to repro or not, but this happened when I wanted to check the processes

<img width="606" alt="screen shot 2018-07-10 at 5 21 35 pm" src="https://user-images.githubusercontent.com/2193314/42544317-cc3634a4-8465-11e8-97f5-fc0ebe8187fb.png">

The same also shows when I run `code-insiders --status`

**Comment by RMacfarlane** [comment]
Hmm, I don't have a repro yet on my machine. What were you doing prior to opening the process explorer? If this is still happening, could you take a look at Activity Monitor with the view set to hierarchical and see what's under insiders there?

**Comment by Tyriar** [comment]
Oh cool, I had no idea I could do hierarchical.

<img width="626" alt="screen shot 2018-07-10 at 5 42 00 pm" src="https://user-images.githubusercontent.com/2193314/42544773-9b11fa90-8468-11e8-93d4-a50e6d6310f7.png">

**Comment by Tyriar** [comment]
Probably a better screenshot:

<img width="706" alt="screen shot 2018-07-10 at 5 43 52 pm" src="https://user-images.githubusercontent.com/2193314/42544819-d98aff42-8468-11e8-9132-c80b62e96ef4.png">
