### ISSUE TITLE
Markdown preview doesn't support checkboxes

### ISSUE THREAD

**Issue by dilijev** [Microsoft/vscode#53993]
Issue Type: <b>Bug</b>

Sample checklist (GitHub style):

* [ ] unchecked box
* [x] checked box

Notice that GitHub renders the above with checkboxes, and VS Code does not.

Repros with all extensions disabled.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1245 v3 @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.69GB (16.61GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe E:\work|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
indentation-level-movement|kai|1.1.1
csharp|ms-|1.15.2
PowerShell|ms-|1.7.0
1es-oss-assistant|mso|0.0.18

</details>

**Comment by mjbvz** [comment]
Use this extension: https://marketplace.visualstudio.com/items?itemName=bierner.markdown-checkbox

**Comment by dilijev** [comment]
I'm surprised that the markdown viewer is included with VS Code but this small but popular feature of markdown is not supported and a plugin is necessary?
