### ISSUE TITLE
list.focusForeground should override gitDecoration.ignoredResourceForeground

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#53998]
I have a contrast issue when using `gitDecoration.ignoredResourceForeground`, I have `node_modules` focused in the following screenshot:

<img width="335" alt="screen shot 2018-07-10 at 5 14 37 pm" src="https://user-images.githubusercontent.com/2193314/42544190-c3e84996-8464-11e8-9cf7-292776c29bd9.png">

To give a more obvious example of what's going on, with these theme keys:

```json
"workbench.colorCustomizations": {
    "list.focusForeground": "#ff0000",
    "gitDecoration.ignoredResourceForeground": "#0000ff"
}
```

I see this (node_modules is focus, .bin is active):

<img width="290" alt="screen shot 2018-07-10 at 5 12 32 pm" src="https://user-images.githubusercontent.com/2193314/42544145-79c7ca62-8464-11e8-83be-7ed9006f5595.png">

I think node_modules should be `#ff0000` in this case in order to fix my issue.

Theme used: https://marketplace.visualstudio.com/items?itemName=Tyriar.theme-sapphire

**Comment by joaomoreno** [comment]
@Tyriar I'm not too sure... `gitDecoration.ignoredResourceForeground` seems to be way more specific than `list.focusForeground`, so I'm not sure I would alter their priority.

**Comment by joaomoreno** [comment]
At first I wasn't convinced about it, but since it is about when the element is focused, I believe that makes sense.

**Comment by jrieken** [comment]
Letting decoration colours win over selection/focus colours was a conscious decision. cc @bpasero

**Comment by bpasero** [comment]
> Letting decoration colours win over selection/focus colours was a conscious decision.

Yeah I cannot remember why we went one or the other direction. Anyway it looks like we are not consistent though:

![image](https://user-images.githubusercontent.com/900690/42569371-9d6dcc94-8510-11e8-8404-1cf6e7a164d3.png)

The selection color wins of the tree but the focus color does not?

**Comment by Tyriar** [comment]
It is weird that active works but not focus, also if this is/was as designed then it basically prevents using a subtle color for the ignored state if I want to see it when it's focused.

Material theme (no 2 in marketplace) also sees this problem:

<img width="322" alt="screen shot 2018-07-11 at 7 45 50 am" src="https://user-images.githubusercontent.com/2193314/42580137-bb42aaaa-84de-11e8-9828-e649993faaf1.png">
