### ISSUE TITLE
Insider wont update in win10 if path/name install is changed

### ISSUE THREAD

**Issue by slinstj** [Microsoft/vscode#53991]
Log:

```
Jul 10 17:16:58.441 INFO Starting: C:\Users\myUser\Programas\vscode\msvscodeinsider\Code - Insiders.exe, false
Jul 10 17:16:58.445 ERRO Bad arguments: Code path doesn't seem to exist: C:\Users\myUser\Programas\vscode\msvscodeinsider\Code - Insiders.exe
```
Current path here is `C:\Users\myUser\Programas\vscode\bin\code-insiders`

Version: 1.26.0-insider
Commit: bd953248ad6a8e2f8896bfb78b3ae40e0fd47426
Date: 2018-07-06T05:17:37.386Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

**Comment by joaomoreno** [comment]
Did you manually change the path name after installing?

**Comment by slinstj** [comment]
Yeah. it was changed.

**Comment by joaomoreno** [comment]
Please don't do that, since it breaks things.
