### ISSUE TITLE
Folders appear deleted but are not deleted

### ISSUE THREAD

**Issue by meibenny** [Microsoft/vscode#54002]
In Windows 7, it's possible for folders to appear deleted in VS Code's explorer even though they were never deleted in the first place.

- VSCode Version: 1.25.0
- OS Version: Windows 7

Steps to Reproduce:

1. Open a folder, `folderA`, with VS Code
2. Create a new folder, `test`, in `folderA`
3. Navigate into `test` via the VS Code Integrated Terminal
4. Use the explorer to delete `test`
5. Notice `test` is no longer visible via the VS Code explorer
6. Open a command prompt, and navigate to `folderA`
7. Try to create the `test` folder via the command prompt, `mkdir test`
8. Notice the command prompt responds with `A subdirectory or file test already exists.`
9. Go back to VS Code's explorer and notice `test` is not visible
10. Press "refresh" and notice `test` was never actually deleted

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/43819
