### ISSUE TITLE
Changing log level doesnt affect the logs from the main process and issue reporter processes

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#54006]
- Change the log level to trace
- Notice that traces are now being printed to the output channel for shared and renderer process
- Open a new folder (this should have triggered some traces in the main process)
- The output channel for main process continues to use the default log level which is "info"

**Comment by ramya-rao-a** [comment]
@sandy081 This is because the main and issue reporter processes don't use the `LogLevelSetterChannelClient`.

**Comment by joaomoreno** [comment]
@sandy081 I believe you had an issue to handle this?

**Comment by ramya-rao-a** [comment]
Adding this to the current milestone as we need this fixed for the feature #54001 to be complete.

**Comment by sandy081** [comment]
Yeah, this should get propagate to all processes. Will check.
