### ISSUE TITLE
Unable to perform most of Source Control actions.

### ISSUE THREAD

**Issue by adithyaharun** [Microsoft/vscode#54009]
Issue Type: <b>Bug</b>

After several minutes or hours working, I was unable to perform most (or maybe all) of the Source Control actions, such as: commit, push, pull, sync, etc. Clicking files on the Changes list didn't show the diffs too. I tried to commit via Terminal, Source Control pane won't updated too.

![untitled 1](https://user-images.githubusercontent.com/7106825/42548533-15cebbce-84fa-11e8-83db-fe978bc02aa6.gif)

For now, I just close and reopen the window to fix this issue.

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:02:28.333Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz (4 x 1300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 3|
|Memory (System)|4.00GB (0.03GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
riot-tag|cri|0.1.7
dart-code|Dar|2.15.0
flutter|Dar|2.15.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vscode-simple-icons|Lau|1.8.3
MagicPython|mag|1.0.12
vscode-apache|mrm|1.1.1
sublime-keybindings|ms-|4.0.0
vetur|oct|0.12.5
vscode-react-native|vsm|0.6.12

(2 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Can you check the log files, maybe there's still something there? <kbd>F1</kbd>, `Developer: Open Logs Folder`.

Let me know if this happens again. When it does, open <kbd>F1</kbd> `Developer: Toggle Developer Tools` and check for errors in the console.

**Comment by adithyaharun** [comment]
When it happens, I checked the errors from the Developer Tools, I found no errors.
I will give more information about this if happens again.

The log files are attached below.

[main.log](https://github.com/Microsoft/vscode/files/2184488/main.log)
[sharedprocess.log](https://github.com/Microsoft/vscode/files/2184490/sharedprocess.log)

**Comment by joaomoreno** [comment]
Can you easily reproduce? Does it reproduce with `--disable-extensions`?

**Comment by adithyaharun** [comment]
Hi. It happened again. Below is the logs from the Developer Tools.
I will try using `--disable-extensions` now.

![screen shot 2018-07-17 at 06 43 21](https://user-images.githubusercontent.com/7106825/42787375-cc8a0026-898c-11e8-9148-0db701655e27.png)

**Comment by adithyaharun** [comment]
Hi, sorry for the late information. It seems one of the extensions I've installed causing this problem.

I will close this issue since this is an extension-related issue.

**Comment by joaomoreno** [comment]
@adithyaharun Any chance you can tell me which extension it was?
