### ISSUE TITLE
"Select All Occurences of Find Match" does not select all if find uses regex

### ISSUE THREAD

**Issue by espresso3389** [Microsoft/vscode#5400]
- VSCode Version: Version 1.0.0-insider
- OS Version: Windows 10 Pro 1511 (10586.218)

Steps to Reproduce:
1. Search with regex to match multiple occurrence
2. Invoke "Select All Occurences of Find Match" (Oooops! Typo in the sentence)

It does not select all of them but only one.

![vscode-1 0 0-insider](https://cloud.githubusercontent.com/assets/1311400/14582938/f043ca9a-044d-11e6-81b0-93a3615cb595.gif)

**Comment by espresso3389** [comment]
Do you have any fix estimation and/or workaround on it?

**Comment by alexandrudima** [comment]
@espresso3389 workaround: press `alt+enter`

**Comment by espresso3389** [comment]
@alexandrudima Wow, I didn't realize that key combination. Thanks!

**Comment by QuietWind** [comment]
@alexandrudima  
thx your skill, thank you very much。

**Comment by caffeineaddiction** [comment]
`Alt + Enter` works +1 Thank You

It would be nice to have a [Find All] button on the actual find-widget like exists in sublime

**Comment by dakaraphi** [comment]
Looks like the text that appears in the list of commands is incorrect.
The 'select all occurrences of find' maps to command select all highlights.  So it should say instead 'select all highlights'
The Alt+Enter combination; however, does not appear in the quick command list.
