### ISSUE TITLE
Please Support Customizing Font of the TitleBar

### ISSUE THREAD

**Issue by DevinSusen** [Microsoft/vscode#54004]
Issue Type: <b>Feature Request</b>

The font of the titlebar is ugly when use the window.titleBarStyle setting value custom.

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.17134

**Comment by bpasero** [comment]
@DevinSusen you are talking about the font that is used for the menu or for the title text?
