### ISSUE TITLE
Огромное потребление пямяти и ЦП

### ISSUE THREAD

**Issue by daromnik** [Microsoft/vscode#54016]
Issue Type: <b>Performance Issue</b>

Во время работы vs code идет огромное потребление памяти и ЦП.
Компьютер просто еле работает.
Процесс extensionHost может сжирать 40% ЦП и 3 гига оперативки.
При его отключении все становится нормально, но выскакивает сообщение: Хост-процесс для расширений неожиданно завершил работу.

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.10586

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4370 CPU @ 3.80GHz (4 x 3791)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (1.29GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    86	  9460	code main
    0	    62	   760	   window (Обозреватель процессов)
    0	    71	  4252	   window (Средство создания отчетов о неполадках)
    0	    67	  4268	   shared-process
    0	    84	 10972	   gpu-process
    0	   174	 11016	   window (Visual Studio Code)
   25	  2154	 10100	     extensionHost
    0	    58	  5016	       electron_node jsonServerMain.js 
    0	    11	 11340	     electron-crash-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.59
php-intellisense|fel|2.3.3
smarty|imp|0.3.0
vscode-apache|mrm|1.1.1
vscode-language-pack-ru|MS-|1.25.2
omnipascal|Wos|0.15.0

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
One of your 6 extensions is very likely causing the issue, try closing all windows and running `code --disable-extensions` to disable them and verify.

**Comment by daromnik** [comment]
Yes, it was PHP IntelliSense felixfbecker.php-intellisense.
Thanks you.
