### ISSUE TITLE
All language code highlights are missing when "files.encoding": "utf16le"

### ISSUE THREAD

**Issue by chuanjiao10** [Microsoft/vscode#54017]
- VSCode Version: 1.25.0

The meaning of this parameter is:
New document, default charset set to BOM+utf16le

bug begin from 1.25.0,old version normal.
"files.encoding": "utf16le"  is no longer support?

Steps to Reproduce:
I have an a.ps1, and an a.yaml, all charset set to BOM+utf16le
When i put "files.encoding": "utf16le" to setting ,highlights are missing.
Delete it and restart vscode highlights normal .
A.ps1, a.yaml No changes are required.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@chuanjiao10 this encoding is still supported, there was no change. what is the issue you are seeing?

**Comment by chuanjiao10** [comment]
This is a trap created by the utf-8 charset paranoia on the unicode charset paranoia. They want to occupy the world! ^_^

**Comment by chuanjiao10** [comment]
?
why you close this issue  ???
if no longer support ,      then remove "utf16le" from **"files.encoding":** 
if still support,   fix highlights when  **"files.encoding":**  set to  "utf16le" 

Now ,let can open BOM+unicode ,but create trap  save BOM+unicode, it's tooooooo mean
