### ISSUE TITLE
When `result` in `EvaluateResponse` is a 0-length string, the vscode GUI will display the wrong result.

### ISSUE THREAD

**Issue by actboy168** [Microsoft/vscode#54011]
Issue Type: <b>Bug</b>

e.g. watch 

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:11.248Z)
OS version: Windows_NT ia32 10.0.17134

**Comment by Tyriar** [comment]
Can you be a little more specific? It's not clear what EvaluateResponse is, are you talking about debugging? Can you provide a screenshot pointing out the problem?

**Comment by actboy168** [comment]
`EvaluateResponse` is

https://github.com/Microsoft/vscode-debugadapter-node/blob/master/debugProtocol.json#L1821-L1859

Sorry, I can't provide screenshots right now. But I think it should be easy to reproduce. I guess its error is the same as #49355.

**Comment by Tyriar** [comment]
@actboy168 thanks that's all I need to send to the right person, looks very similar to #49355.

**Comment by isidorn** [comment]
@actboy168 as mentioned in https://github.com/Microsoft/vscode/issues/49355 this is now fixed and works fine for me in latest vscode inisders. On that issue you mentioned that it works for you - when has this changed? When has it stopped working?
Can you reproduce with latest vscode insiders https://code.visualstudio.com/insiders/

**Comment by actboy168** [comment]
#49355 is also works fine for me.  #49355 is `VariablesResponse`, but now it is `EvaluateResponse`.

**Comment by isidorn** [comment]
@actboy168 thanks, I have pushed a fix. You can try it out in tomorrow's vscode insiders. Let us know if it fixes the issue you were facing. Thank you

**Comment by actboy168** [comment]
Yes.It's fixed.But it missing a colon.
![default](https://user-images.githubusercontent.com/1836844/42956638-1b825e26-8bb3-11e8-966e-ef64d08351e0.PNG)

**Comment by isidorn** [comment]
@actboy168 thanks for checking it out, adding verified label.
I have pushed a fix for the missing colon
