### ISSUE TITLE
Extension crashes in production, never in [Extension Development Host]

### ISSUE THREAD

**Issue by Janne252** [Microsoft/vscode#5401]
I'm having rather confusing issues with my extension. It is the only installed extension and seems to always crash when run in production (the extension is built & installed). The result:
![](http://i.imgur.com/GU8rrd6.png)

The question is, where can I look for more information regarding the crash? 
The extension never does this when ran in development mode from vscode (Extension Development Host), which makes it even harder to understand.

**Comment by Janne252** [comment]
I have managed to narrow down the probable cause:
[extension.ts, line 34](https://github.com/Janne252/relic-scar/blob/master/src/extension.ts#L34) **→** [scarFunctionFileCollection.ts](https://github.com/Janne252/relic-scar/blob/master/src/scarFunctionCollection/scarFunctionFileCollection.ts)

scarFunctionFileCollection.ts scans all the files in the current workspace by doing the following:

- Get the list of all files (including sub-directories)
- Iterate over the filelist, scan each file for user functions (open file, get the text, rip the stuff we want with regex)
- Prepare completionIItem and SignatureHelp data from the found functions

What ever goes wrong in that procedure, it never seems to happen in [Extension Development Host]. Disabling the call in [extension.ts, line 34](https://github.com/Janne252/relic-scar/blob/master/src/extension.ts#L34) "fixes" the issue.

**Comment by alexandrudima** [comment]
@Janne252 Given your extension does something workspace specific, perhaps it doesn't crash in the extension development case because you are opening different folders?

@bpasero When the extension host crashes, do we have any additional information printed somewhere?

**Comment by bpasero** [comment]
@alexandrudima only the exit code of the process. on Mac there is a chance to get at the crash dump using the "Console" application:

![image](https://cloud.githubusercontent.com/assets/900690/14878612/e9f5c910-0d24-11e6-9489-3a3d898eed0d.png)

**Comment by bpasero** [comment]
@Janne252 can you monitor the memory consumption of the extension host process to see if maybe the scanning of the workspace consumes lots of memory?

**Comment by Janne252** [comment]
I have recently re-coded the problematic part of the extension and it now seems to behave correctly. There were multiple occasions of logical errors. 
Thanks for the replies. Unfortunately I don't have access to OSX machine. However it would be useful if the crash dump seen above could be made available on other platforms as well.

**Comment by bpasero** [comment]
We use the Electron crash reporter to collect crashes on all OS though I am unsure if this service also collects the crashes from forked processes.

**Comment by alexandrudima** [comment]
@Janne252 Given it is always possible to write extension code that leads to crashing the extension host, and most likely the extension host crashes with OOM, and that you've refactored your code and it no longer crashes, I don't know what we could do more on our side. I'm opting to close this issue for now.
