### ISSUE TITLE
Fails to open image diff when staged

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#54014]
Issue Type: <b>Bug</b>

When attempting to show a diff of a staged image change the following error message pops up
```
Unable to open 'foo.png (Index)': Cannot set property onDidSizeConstraintsChange of #<t> which has only a getter.
```

VS Code version: Code - Insiders 1.26.0-insider (adfa9ce9778a6e79197477fcc60cb5420a31979a, 2018-07-10T05:19:09.185Z)
OS version: Windows_NT x64 10.0.17711

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (14.70GB free)|
|Process Argv|C:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe C:\Users\Eric\code\vscode-gitlens|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by eamodio** [comment]
I don't think this is a dupe

**Comment by joshunger** [comment]
VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
![image](https://user-images.githubusercontent.com/2301847/42571480-84215c4c-84d4-11e8-81a2-9645bdc5ac0b.png)

**Comment by joaomoreno** [comment]
Broken by https://github.com/Microsoft/vscode/commit/4d0b3d025e935ebca55eee235e22504d2b6bb2f6#r29684945
