### ISSUE TITLE
Search: remember string when accidentally invoking history navigation (up/down arrow)

### ISSUE THREAD

**Issue by borekb** [Microsoft/vscode#54018]
Version 1.25 (June 2018) [changed defaults for history navigation](https://code.visualstudio.com/updates/v1_25#_history-navigation) to plain up/down arrows where this previously moved between fields (implemented in #12645). I like the change itself but often press up/down arrow accidentally as my muscle memory is used to navigating between fields with that.

The problem is that up/down arrows now navigate history, losing what I just typed. Imagine I carefully write some regular expression in the search box, want to limit it to *.md files so I press the down arrow.. ooops, my regex is gone.

The proposed change here is to remember what I just typed into the field. For example, I write my regex, press down, realize that this is a history navigation command (which itself is debatable; shouldn't history navigation be triggered by Up only, like in terminal?) so I press the opposite arrow and my regex is back.

Thanks for considering this.

**Comment by roblourens** [comment]
> The proposed change here is to remember what I just typed into the field.

This is supposed to work and it does work for me. Where are you testing this?

**Comment by sandy081** [comment]
I see.. I think I got the issue. I think it happens when you have the history when you navigate to next.

**Comment by borekb** [comment]
Correct, I already have some history so pressing down arrow replaces my search string with an item from the history, with no way to get my manually typed text back (all this is before I pressed Enter for search so my search string has not been added to the history yet). @sandy081, thanks for looking into it!

**Comment by sandy081** [comment]
To Verify

- Search for value `1`
- Search for value `2`
- Search for value `3`
- Type Up Arrow to reach `2`
- Clear the input and type `4`
- Type Down Arrow 
- Verify that value is not changed
- Type Up Arrow
- Verify that value is changed to `3`
- Type Down Arrow
- Verify that value is changed to `4`
