### ISSUE TITLE
search not work for file if file is not opened.

### ISSUE THREAD

**Issue by FFengIll** [Microsoft/vscode#54020]
- VSCode Version: 1.25
- OS Version: MacOS

Steps to Reproduce:

1. search not work for file if file is not opened. (if I open the file, the search is successful, aka pic.3)
2. see the snapshot. 
( may ref to  #48958)

file closed:
![image](https://user-images.githubusercontent.com/7359555/42555161-eb64004a-8519-11e8-84e9-3b7fd5382056.png)

file closed:
![image](https://user-images.githubusercontent.com/7359555/42555164-ee548acc-8519-11e8-81c6-e8e0f320a807.png)

file opened:
![image](https://user-images.githubusercontent.com/7359555/42555491-07c35bae-851b-11e8-8928-d7693094e830.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Is it open in screenshot 3 and closed in shots 1 and 2?

**Comment by roblourens** [comment]
Please see these troubleshooting tips: https://github.com/Microsoft/vscode/wiki/Search-Issues#missing-search-results

And attach the logs (instructions at the bottom of that page) if they don't help.

**Comment by FFengIll** [comment]
@roblourens I will follow `Please see these troubleshooting tips` and attach things later.

Before that, I have done a debug and find that:
search not work for a single file ( I found related things and reasons but no solution now), ref #48958 (as you say)

But why it works for the opened file (screenshot 3)?
I found it may come from the default action -- always search in opened files.
The file just feat the glob, so the results of the opened show in the GUI.

Wish to share these info to help for a solution.

**Comment by roblourens** [comment]
Searching in open files does work differently from searching in other files, so that's expected.
