### ISSUE TITLE
Dark+ color theme is more colorful on Linux than on Windows

### ISSUE THREAD

**Issue by milesxu** [Microsoft/vscode#54028]
vscode version: 1.25
system: Manjaro x86_64, Windows 10 x86_64

I found that Dark+ theme is more colorful on Linux than on Windows.

The theme on **Linux**:
![vscode-manjaro](https://user-images.githubusercontent.com/2003731/42560559-81190a72-8529-11e8-8754-a8b51acadc32.png)

And the theme on **Windows 10**:
![vscode-win10](https://user-images.githubusercontent.com/2003731/42560680-cf0e134e-8529-11e8-975d-ac6f45a5d2f6.PNG)

Why there are differences? It would be nice to make Dark+ look same on both systems.

**Comment by mjbvz** [comment]
Looks like you have a brackets colorized extension installed on your linux system but not on windows

**Comment by milesxu** [comment]
@mjbvz I see, thank you very much!
