### ISSUE TITLE
Debugging Issue

### ISSUE THREAD

**Issue by Harshita18** [Microsoft/vscode#54022]
Issue Type: <b>Bug</b>

I am not able to debug the code as everytime it is throwing error with the Debug log levels.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.10586

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4310U CPU @ 2.00GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (1.64GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
apex-debug|chu|1.0.3
apex|Joh|0.0.2
ForceCode|Joh|0.5.35
visualforce|Joh|1.0.2
salesforcedx-vscode|sal|43.6.0
salesforcedx-vscode-apex|sal|43.6.0
salesforcedx-vscode-apex-debugger|sal|43.6.0
salesforcedx-vscode-apex-replay-debugger|sal|43.6.0
salesforcedx-vscode-core|sal|43.6.0
salesforcedx-vscode-lightning|sal|43.6.0
salesforcedx-vscode-visualforce|sal|43.6.0

</details>

**Comment by Tyriar** [comment]
Can you provide more information about the error?

**Comment by cythomli** [comment]
@Tyriar I have the same issue. On typing .scripts I see the following:

.scripts 
› VM201
› VM202
› VM209
› VM214
› VM219
› VM224
› VM229
› VM230
› VM231
› VM232
› VM253
› VM280
› VM281
› VM68
› chrome-extension://ppnbnpeolgkicgegkbkbjmhlideopiji/content.js
› https://az416426.vo.msecnd.net/scripts/a/ai.0.js
    - ../JavaScript/JavaScriptSDK.Interfaces/IConfig.ts (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\scripts\JavaScript\JavaScriptSDK.Interfaces\IConfig.ts)
    - ../JavaScript/JavaScriptSDK.Interfaces/Contracts/Generated/Base.ts (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\scripts\JavaScript\JavaScriptSDK.Interfaces\Contracts\Generated\Base.ts)
    - ../JavaScript/JavaScriptSDK.Interfaces/Contracts/Generated/Envelope.ts (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\scripts\JavaScript\JavaScriptSDK.Interfaces\Contracts\Generated\Envelope.ts)
    - ../JavaScript/JavaScriptSDK.Interfaces/Context/IApplication.ts (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\scripts\JavaScript\JavaScriptSDK.Interfaces\Context\IApplication.ts)
    - webpack:///../external "@microsoft/sp-webpart-base" (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\dist\external "@microsoft\sp-webpart-base")
    - webpack:///../../../../../../src/webparts/publishApps/Components/PublishApps/PublishAppsComponent.tsx (c:\Users\src\webparts\publishApps\Components\PublishApps\PublishAppsComponent.tsx)
    - webpack:///.././node_modules/react-redux/es/components/Provider.js (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\dist\node_modules\react-redux\es\components\Provider.js)
    - webpack:///.././node_modules/prop-types/factoryWithTypeCheckers.js (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\dist\node_modules\prop-types\factoryWithTypeCheckers.js)
    - webpack:///.././node_modules/prop-types/checkPropTypes.js (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\dist\node_modules\prop-types\checkPropTypes.js)
    - webpack:///.././node_modules/hoist-non-react-statics/index.js (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\dist\node_modules\hoist-non-react-statics\index.js)
    - webpack:///.././node_modules/invariant/browser.js (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\dist\node_modules\invariant\browser.js)
    - webpack:///.././node_modules/react-redux/es/utils/Subscription.js (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\dist\node_modules\react-redux\es\utils\Subscription.js)
    - webpack:///.././node_modules/react-redux/es/connect/connect.js (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\dist\node_modules\react-redux\es\connect\connect.js)
    - webpack:///.././node_modules/react-redux/es/utils/shallowEqual.js (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\dist\node_modules\react-redux\es\utils\shallowEqual.js)
    - webpack:///.././node_modules/react-redux/es/connect/mapDispatchToProps.js (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\dist\node_modules\react-redux\es\connect\mapDispatchToProps.js)
    - webpack:///.././node_modules/lodash-es/_baseGetTag.js (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\dist\node_modules\lodash-es\_baseGetTag.js)
    - webpack:///.././node_modules/lodash-es/_root.js (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\dist\node_modules\lodash-es\_root.js)
    - webpack:///.././node_modules/lodash-es/_freeGlobal.js (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\dist\node_modules\lodash-es\_freeGlobal.js)
    - webpack:///.././node_modules/lodash-es/_getRawTag.js (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\dist\node_modules\lodash-es\_getRawTag.js)
    - webpack:///.././node_modules/lodash-es/_objectToString.js (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\dist\node_modules\lodash-es\_objectToString.js)
    - webpack:///.././node_modules/lodash-es/_getPrototype.js (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\dist\node_modules\lodash-es\_getPrototype.js)
    - webpack:///.././node_modules/lodash-es/_overArg.js (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\dist\node_modules\lodash-es\_overArg.js)
    - webpack:///.././node_modules/lodash-es/isObjectLike.js (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\dist\node_modules\lodash-es\isObjectLike.js)
    - webpack:///.././node_modules/symbol-observable/index.js (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\dist\node_modules\symbol-observable\index.js)
    - webpack:///.././node_modules/symbol-observable/lib/index.js (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\dist\node_modules\symbol-observable\lib\index.js)
    - webpack:///../(webpack)/buildin/module.js (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\dist\(webpack)\buildin\module.js)
    - webpack:///.././node_modules/symbol-observable/lib/ponyfill.js (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\dist\node_modules\symbol-observable\lib\ponyfill.js)
    - webpack:///.././node_modules/redux/es/combineReducers.js (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\dist\node_modules\redux\es\combineReducers.js)
    - webpack:///.././node_modules/redux/es/bindActionCreators.js (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\dist\node_modules\redux\es\bindActionCreators.js)
    - webpack:///../../../../../../../src/webparts/publishApps/Components/PublishApps/actions/Actions.ts (c:\src\webparts\publishApps\Components\PublishApps\actions\Actions.ts)
    - webpack:///../../../../../src/webparts/publishApps/store/Store.ts (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\src\webparts\publishApps\store\Store.ts)
    - webpack:///.././node_modules/redux-thunk/lib/index.js (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\dist\node_modules\redux-thunk\lib\index.js)
    - webpack:///.././node_modules/redux-logger/dist/redux-logger.js (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\dist\node_modules\redux-logger\dist\redux-logger.js)
    - webpack:///../../../../src/webparts/publishApps/RootReducer.ts (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\src\webparts\publishApps\RootReducer.ts)
    - webpack:///../../../../../../../src/webparts/publishApps/Components/ListApps/reducers/Communication.ts (c:\src\webparts\publishApps\Components\ListApps\reducers\Communication.ts)
    - webpack:///../../../../../../../src/webparts/publishApps/Components/ListApps/reducers/CommunicationState.ts (c:\src\webparts\publishApps\Components\ListApps\reducers\CommunicationState.ts)
    - webpack:///../../../../../../../src/webparts/publishApps/Components/ListApps/reducers/Control.ts (c:\src\webparts\publishApps\Components\ListApps\reducers\Control.ts)
    - webpack:///../../../../../../../src/webparts/publishApps/Components/ListApps/reducers/ControlState.ts (c:\src\webparts\publishApps\Components\ListApps\reducers\ControlState.ts)
    - webpack:///../../../../../../../src/webparts/publishApps/Components/ListApps/reducers/Data.ts (c:\src\webparts\publishApps\Components\ListApps\reducers\Data.ts)
    - webpack:///../../../../../../../src/webparts/publishApps/Components/ListApps/reducers/DataState.ts (c:\src\webparts\publishApps\Components\ListApps\reducers\DataState.ts)
    - webpack:///../../../../../../../src/webparts/publishApps/Components/ListApps/reducers/Session.ts (c:\src\webparts\publishApps\Components\ListApps\reducers\Session.ts)
    - webpack:///../../../../../../../src/webparts/publishApps/Components/ListApps/reducers/SessionState.ts (c:\src\webparts\publishApps\Components\ListApps\reducers\SessionState.ts)
    - webpack:///../../../../../../../src/webparts/publishApps/Components/PublishApps/reducers/Communication.ts (c:\src\webparts\publishApps\Components\PublishApps\reducers\Communication.ts)
    - webpack:///../../../../../../../src/webparts/publishApps/Components/PublishApps/reducers/CommunicationState.ts (c:\src\webparts\publishApps\Components\PublishApps\reducers\CommunicationState.ts)
    - webpack:///../../../../../../../src/webparts/publishApps/Components/PublishApps/reducers/Session.ts (c:\src\webparts\publishApps\Components\PublishApps\reducers\Session.ts)
    - webpack:///../../../../../../../src/webparts/publishApps/Components/PublishApps/reducers/SessionState.ts (c:\src\webparts\publishApps\Components\PublishApps\reducers\SessionState.ts)
    - webpack:///../../../../../../../src/webparts/publishApps/Components/SubmitAppForm/reducers/Communication.ts (c:\src\webparts\publishApps\Components\SubmitAppForm\reducers\Communication.ts)
    - webpack:///../../../../../../../src/webparts/publishApps/Components/SubmitAppForm/reducers/CommunicationState.ts (c:\src\webparts\publishApps\Components\SubmitAppForm\reducers\CommunicationState.ts)
    - webpack:///../../../../../../../src/webparts/publishApps/Components/SubmitAppForm/reducers/Control.ts (c:\src\webparts\publishApps\Components\SubmitAppForm\reducers\Control.ts)
    - webpack:///../../../../../../../src/webparts/publishApps/Components/SubmitAppForm/reducers/ControlState.ts (c:\src\webparts\publishApps\Components\SubmitAppForm\reducers\ControlState.ts)
    - webpack:///../../../../../../../src/webparts/publishApps/Components/SubmitAppForm/reducers/Data.ts (c:\src\webparts\publishApps\Components\SubmitAppForm\reducers\Data.ts)
    - webpack:///../../../../../../../src/webparts/publishApps/Components/SubmitAppForm/reducers/DataState.ts (c:\src\webparts\publishApps\Components\SubmitAppForm\reducers\DataState.ts)
    - webpack:///../../../../../../../src/webparts/publishApps/Components/SubmitAppForm/reducers/Session.ts (c:\src\webparts\publishApps\Components\SubmitAppForm\reducers\Session.ts)
    - webpack:///../../../../../../../src/webparts/publishApps/Components/SubmitAppForm/reducers/SessionState.ts (c:\src\webparts\publishApps\Components\SubmitAppForm\reducers\SessionState.ts)
› https://localhost:4321/lib/webparts/publishApps/loc/en-us.js (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\lib\webparts\publishApps\loc\en-us.js)

    - webpack:///../external "@microsoft/decorators" (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\sp-webpart-base\dist\external "@microsoft\decorators")
    - webpack:///../external "@microsoft/sp-http" (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\sp-webpart-base\dist\external "@microsoft\sp-http")
    - webpack:///../external "@microsoft/sp-component-base" (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\sp-webpart-base\dist\external "@microsoft\sp-component-base")
    - webpack:///../external "@microsoft/sp-loader" (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\sp-webpart-base\dist\external "@microsoft\sp-loader")
    - webpack:///../external "@microsoft/sp-page-context" (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\sp-webpart-base\dist\external "@microsoft\sp-page-context")
    - webpack:///../external "@microsoft/office-ui-fabric-react-bundle" (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\sp-webpart-base\dist\external "@microsoft\office-ui-fabric-react-bundle")
› https://localhost:4321/node_modules/@microsoft/sp-webpart-workbench/dist/sp-webpart-workbench_en-us.js (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\sp-webpart-workbench\dist\sp-webpart-workbench_en-us.js)
    - webpack:///../webpack/bootstrap 7a2bed6694b0cf6ddfe7 (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\sp-webpart-workbench\dist\webpack\bootstrap 7a2bed6694b0cf6ddfe7)
    - webpack:///.././sp-webpart-workbench.js (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\sp-webpart-workbench\dist\sp-webpart-workbench.js)
    - webpack:///../external "react-dom" (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\sp-webpart-workbench\dist\external "react-dom")
    - webpack:///../external "react" (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\sp-webpart-workbench\dist\external "react")
    - webpack:///../external "@microsoft/sp-core-library" (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\sp-webpart-workbench\dist\external "@microsoft\sp-core-library")
    - webpack:///../external "@ms/sp-telemetry" (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\sp-webpart-workbench\dist\external "@ms\sp-telemetry")
    - webpack:///../external "@microsoft/sp-lodash-subset" (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\sp-webpart-workbench\dist\external "@microsoft\sp-lodash-subset")
    - webpack:///../../lib/resx-strings/en-us.js (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\sp-webpart-workbench\lib\resx-strings\en-us.js)
    - webpack:///../external "@microsoft/sp-webpart-base" (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\sp-webpart-workbench\dist\external "@microsoft\sp-webpart-base")
    - webpack:///../external "office-ui-fabric-react" (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\sp-webpart-workbench\dist\external "office-ui-fabric-react")
    - webpack:///../external "@microsoft/office-ui-fabric-react-bundle" (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\sp-webpart-workbench\dist\external "@microsoft\office-ui-fabric-react-bundle")
    - webpack:///../external "@microsoft/sp-page-context" (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\sp-webpart-workbench\dist\external "@microsoft\sp-page-context")
    - webpack:///../external "@microsoft/sp-http" (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\sp-webpart-workbench\dist\external "@microsoft\sp-http")
    - webpack:///../external "@microsoft/sp-application-base" (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\sp-webpart-workbench\dist\external "@microsoft\sp-application-base")
    - webpack:///../external "@microsoft/sp-loader" (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\sp-webpart-workbench\dist\external "@microsoft\sp-loader")
› https://localhost:4321/node_modules/@microsoft/sp-webpart-workbench/lib/api/workbenchInit.js (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\@microsoft\sp-webpart-workbench\lib\api\workbenchInit.js)
› https://localhost:4321/node_modules/react-dom/dist/react-dom.js (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\react-dom\dist\react-dom.js)
› https://localhost:4321/node_modules/react/dist/react.js (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\node_modules\react\dist\react.js)
› https://localhost:4321/temp/manifests.js (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\temp\manifests.js)
› https://localhost:4321/temp/workbench.html (c:\Users\lipalath\_\EUS-Col-ColPub-PublishApps\PublishApps\temp\workbench.html)

Please let me know what this means.

**Comment by isidorn** [comment]
Will reopen if more data is provided
