### ISSUE TITLE
Suggest: text and icons stacked together

### ISSUE THREAD

**Issue by TheChoconut** [Microsoft/vscode#54036]
Issue Type: <b>Bug</b>

#### Steps to reproduce:
Using Ctrl+Space shortcut to trigger suggestions.

#### Expected behaviour:
Suggestion list items can be scrollable, lines aren't stacked and are readable.

#### Actual behaviour:
Suggestion list items are stacked together, resulting in unreadable lines of solutions.

### Screenshot:
![image](https://user-images.githubusercontent.com/16463535/42569241-27b76212-8510-11e8-9a1d-c4708d3cf283.png)

VS Code version: Code - Insiders 1.26.0-insider (adfa9ce9778a6e79197477fcc60cb5420a31979a, 2018-07-10T05:19:09.185Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     E8400  @ 3.00GHz (2 x 2999)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|6.00GB (1.70GB free)|
|Process Argv|D:\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
materialcolorsnippets|bru|1.0.0
tslint|eg2|1.0.33
minify|Hoo|0.3.0
vscode-apache|mrm|1.1.1
sublime-keybindings|ms-|4.0.0
debugger-for-chrome|msj|4.7.0
tsimporter|pmn|1.2.14
vscode-icons|rob|7.24.0
bootstrap4-vscode|the|4.1.1
vscode-react-native|vsm|0.6.12

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Should be fixed in next build
