### ISSUE TITLE
Reference group variable still not working

### ISSUE THREAD

**Issue by wzup** [Microsoft/vscode#54032]
https://github.com/Microsoft/vscode/issues/9586
https://github.com/Microsoft/vscode/issues/9010

Still not working
```javascript
// regexp
(abc)
foo=$1

// I get
foo=1

// should be
foo=abc
```

**Comment by sandy081** [comment]
It works for me

![image](https://user-images.githubusercontent.com/10746682/42627089-4c94367a-85cc-11e8-9d72-8df0cdc312f5.png)

Do you have a specific example and steps to reproduce?
