### ISSUE TITLE
No C# file type and C# files not recognised for syntax highlighting

### ISSUE THREAD

**Issue by THuffam** [Microsoft/vscode#5403]
- VSCode Version: 1.0.0
- OS Version: Ubuntu Mate 15.10

Steps to Reproduce:

1. Install VS Code Stable 1.0
2. Open a folder created by: yo aspnet --grunt
3. Open a .cs file eg Controllers/HomeController.cs
The text loads white (no syntax highlighting)
In the status bar at the bottom of the window is says "Plain text" which I'm assuming is the file type. When I click on this to change file type, the list does not include C#- but it does include many others eg C, C++, F#, CSS, etc.

**Comment by kataras** [comment]
I think that C# is not bundled with the vs code now, you have to install it via the extension manager... take a look [here](https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp). 

>Note that I'm not 100% sure for that, but give it a try.

**Comment by egamma** [comment]
@katares is correct you need to install the C# extension.
