### ISSUE TITLE
unable to run electron in bash shell

### ISSUE THREAD

**Issue by digitalrinaldo** [Microsoft/vscode#54037]
Issue Type: <b>Bug</b>

Install nodejs and npm 
# uname -aLinux emery-blagdon 4.4.0-17134-Microsoft #112-Microsoft Thu Jun 07 22:57:00 PST2018 x86_64 x86_64 x86_64 GNU/Linux# nodejs -vv10.6.0# npm -v
6.1.0
#

try to install electron

/mnt/c/Users/digitalrinaldo/Documents/assisted-reading-opengaze/javascript/node_modules/electron/dist/electron: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-9590 Eight-Core Processor            (8 x 4722)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.96GB (20.25GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by Tyriar** [comment]
This is the vscode repo, not the electron repo?

**Comment by digitalrinaldo** [comment]
Do not reopen but you did not read the bug report carefully..

**Comment by Tyriar** [comment]
> unable to run electron in bash shell

> Install nodejs and npm

> try to install electron

> /mnt/c/Users/digitalrinaldo/Documents/assisted-reading-opengaze/javascript/node_modules/electron/dist/electron: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory

Where does VS Code come in here?
