### ISSUE TITLE
nodejs requires not resolved

### ISSUE THREAD

**Issue by foobar8675** [Microsoft/vscode#5404]
- VSCode Version:

1.0.0 

- OS Version:
10.11.4 El cap
Steps to Reproduce:

1. nothing to really reproduce. i'm just confused as to why the require statements in this node project have errors. 
2. i have a jsconfig.json file, which from the docs say the paths should be set, such vscode should be able to resolve the paths in the requires?

<img width="602" alt="screen shot 2016-04-16 at 5 13 35 pm" src="https://cloud.githubusercontent.com/assets/1685700/14584332/959a3658-03f6-11e6-9b52-cd769079976d.png">

<img width="1152" alt="screen shot 2016-04-16 at 4 57 53 pm" src="https://cloud.githubusercontent.com/assets/1685700/14584292/77f37346-03f4-11e6-87bf-3a2c82a927f8.png">

**Comment by egamma** [comment]
The file is treated as a Typescript file due to this bug: Microsoft/TypeScript#7291. 

Closing as a duplicate.
