### ISSUE TITLE
Custom Titlebar: Can't drag top border to resize window

### ISSUE THREAD

**Issue by jtlowe** [Microsoft/vscode#54045]
Issue Type: <b>Bug</b>

While the custom title bar is enabled, hovering over the very top of the titlebar does not give the option to drag and resize the window.

Steps to Reproduce:

1. Enable the custom 
2. Hover over the very top of the window. There is no option to drag and resize the window

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.16299

<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
classic-asp|ili|0.0.4
vscode-icon-theme|jtl|1.6.2
csharp|ms-|1.15.2
PowerShell|ms-|1.8.0

</details>

**Comment by sbatten** [comment]
@jtlowe I believe this issue is resolved in insiders. Would you be able to verify?

**Comment by jtlowe** [comment]
@sbatten Yes, it is working correctly for me in Insiders. Thanks for resolving this!

**Comment by sbatten** [comment]
@jtlowe thanks for verifying
