### ISSUE TITLE
Alt Tab invokes menu

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#54047]
On Linux:

1. <kbd>Alt Tab</kbd> to another app
2. <kbd>Alt Tab</kbd> back to Code
3. <kbd>Enter</kbd> once, notice the top menu gets focused
4. <kbd>Enter</kbd> again, notice the top `File` menu opens

**Comment by joaomoreno** [comment]
Thanks for this! It's probably what hits me the most.

**Comment by joaomoreno** [comment]
Works great! I wonder if you should also put a timeout in the time it takes for <kbd>Alt</kbd> to be released, in order to focus the menu. It should focus the menu on a single, short press, but not in a continuous hold & release. What do you think?

**Comment by sbatten** [comment]
@joaomoreno I don't disagree that a continuous hold & release is probably not the intended action but I'm not sure its worth changing. For accessibility reasons, I don't think we want to enforce a speed requirement on this action. Is there another action that you would want to happen on a purely altKey press, hold, and release?

**Comment by joaomoreno** [comment]
Not another action, but often happens that I hold <kbd>Alt</kbd> because I want to Alt-Tab but I regret it half-way and just end up releasing Alt after a second or so. My suggestion was to put that timeout really high, like 750ms.

**Comment by iansan5653** [comment]
@joaomoreno @sbatten In my opinion, the timeout is way too high right now; I often start typing only to realize that the menu bar was focused. I didn't see this conversation here until after I posted #54723 or I would have just replied here, so if you want to close that bug and just discuss here then feel free.
