### ISSUE TITLE
nested quotation mark strings in configurations stopped working

### ISSUE THREAD

**Issue by salda** [Microsoft/vscode#54042]
see https://stackoverflow.com/questions/51283841/vscode-nested-quotation-mark-strings-in-configurations-stopped-working

**Comment by salda** [comment]
It's not covered. Reading the first link I checked encoding and it's UTF-8 anyway.

**Comment by weinand** [comment]
@salda what debug extension are you using?
Showing the full debug configuration would help.

**Comment by salda** [comment]
@weinand C/C++ extension
        {
            "name": "Debug something wallet rpc wallet",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/build/debug/bin/something-wallet-rpc",
            "args": [
                "--rpc-bind-port", "19835",
                "--wallet-file", "wallet",
                "--password", "\"\"",
                "--log-level", "2"
            ],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]//,
            //"preLaunchTask": "wait some time"
        }
