### ISSUE TITLE
Menu separator has strange width

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#54049]
Seen on Linux.

This menu now looks strange:

![screenshot from 2018-07-11 15-28-54](https://user-images.githubusercontent.com/22350/42575399-a681ea12-8520-11e8-800a-6fcbff03f62c.png)

- The horizontal separator should span the whole menu width.
- ~~There should be no padding between the menu item's background color and the separator itself.~~

**Comment by joaomoreno** [comment]
Actually I take back the part about the padding... other menus seem to work the same way... it's really the padding which doesn't make much sense.

**Comment by sbatten** [comment]
@joaomoreno on windows 10, menus in the desktop environment have this spacing. we don't have to do that because every context menu in windows looks different, but that's the reasoning for not changing it

**Comment by joaomoreno** [comment]
I see... we can perhaps make it platform specific then? It looks quite alien in Linux.
