### ISSUE TITLE
UI freeze after checking for updates of extensions

### ISSUE THREAD

**Issue by Yanpas** [Microsoft/vscode#54041]
- VSCode Version: 1.25
- OS Version: kubuntu 18.04

Steps to Reproduce:

1. Open extensions view
2. Click check for updates

After a few seconds whole UI becomes unresponsive for 2-3 seconds. Event-thread was blocked by some network call. It would be useful to log everything that blocks main thread for more than 20 milliseconds (>16 ms feels lagging).

It seems to be a regression, appeared after 1.25

**Comment by sandy081** [comment]
@Yanpas  Can you please get the logs (window and shared) and show me? May be enable log level to trace to get more info.

**Comment by sandy081** [comment]
@roblourens Can you please try with 1.24v and see if you can reproduce it?

**Comment by sandy081** [comment]
@roblourens May I also know which platform are you on?

**Comment by Yanpas** [comment]
started code with `--log trace`. Logs:
https://gist.github.com/Yanpas/bb04d9f7430c80767277743c2ed1ceaf
https://gist.github.com/Yanpas/ff84ffdaecb5bd0bd830521812c3da53

> May I also know which platform are you on?

Kubuntu linux 18.04. Kernel 4.17.3

> Do you also see the issue when you search in Market place?

Yes

> When are you checking for the updates

I check manually using menu. I don't face it if I just open new window.

Here is a screencast:
![peek 2018-07-12 14-40](https://user-images.githubusercontent.com/7345761/42630995-873981f8-85e1-11e8-90fe-79c9e48563ab.gif)

**Comment by sandy081** [comment]
@Yanpas Can you please try with out opening anything in the editor?

**Comment by roblourens** [comment]
- mac
- No problem when I search
- The window has been open for a while
- In 1.25 I am seeing the same symptom for a very brief amount of time. The UI doesn't respond but just for less than 1s, instead of several seconds.

The trace logs after I run "check for updates":

Window:
```
[2018-07-12 09:43:23.522] [renderer33] [trace] RequestService#request https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery
[2018-07-12 09:43:23.523] [renderer33] [trace] RequestService#request https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery
[2018-07-12 09:43:23.591] [renderer33] [trace] RequestService#request https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery
[2018-07-12 09:43:23.685] [renderer33] [trace] RequestService#request https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery
[2018-07-12 09:43:35.242] [renderer33] [trace] CommandService#executeCommand setContext
[2018-07-12 09:43:35.244] [renderer33] [trace] CommandService#executeCommand setContext
[2018-07-12 09:43:35.244] [renderer33] [trace] CommandService#executeCommand setContext
[2018-07-12 09:43:35.244] [renderer33] [trace] CommandService#executeCommand setContext
[2018-07-12 09:43:35.244] [renderer33] [trace] CommandService#executeCommand setContext
[2018-07-12 09:43:36.979] [renderer33] [trace] CommandService#executeCommand setContext
```


Shared:

```
[2018-07-12 09:43:23.383] [sharedprocess] [trace] Started scanning user extensions
[2018-07-12 09:43:23.446] [sharedprocess] [info] Scanned user extensions: 94
```

**Comment by roblourens** [comment]
Oh you asked about 1.24, I don't see it in 1.24.

**Comment by sandy081** [comment]
@roblourens Since you are able to reproduce it, can you try it running out of dev 

- pointing to 1.25 extension dir
- pointing to 1.25 user data dir (if possible as I am not sure this can be done)

And profile it and send me the profile?

**Comment by roblourens** [comment]
The pause in the middle is when the UI was unresponsive. It was short this time but seems to correspond to when the network request to the gallery was happening.

[Profile-20180713T090447.json.txt](https://github.com/Microsoft/vscode/files/2193392/Profile-20180713T090447.json.txt)

**Comment by hastebrot** [comment]
Also freezes on my macos machine. vscode 1.25.1. using the reproduction steps in the initial description.

**Comment by sandy081** [comment]
Thanks @roblourens for the profile.

Looks like extension change listeners are consuming this 1s.

**Comment by Yanpas** [comment]
This bug affects windows too

**Comment by roblourens** [comment]
I also see this, or something similar, when I 

- Open the extension viewlet
- Reload the window

It's really bad sometimes, here's a profile from an instance where it was blocked for 25 seconds.

[Profile-20180731T141009.json.txt.zip](https://github.com/Microsoft/vscode/files/2247112/Profile-20180731T141009.json.txt.zip)

**Comment by roblourens** [comment]
Other people seeing this, how many extensions do you have installed?

**Comment by Yanpas** [comment]
I have 44 (36 enabled, 8 disabled)

**Comment by sandy081** [comment]
Looks like some of the actions are listening to changes from every extension and updating their enablement state.

Provided a fix that will let actions to listen changes from their extensions only.
