### ISSUE TITLE
Git: Add some git variables in snippets

### ISSUE THREAD

**Issue by dimensi** [Microsoft/vscode#54040]
It seems to me useful to have access to some variables from the git for snippets for git commit snippets
Like
```
"Refactoring": {
	"prefix": "gm ref",
	"body": "🔥 ${GIT_BRANCH} $2"
},
```
result of this
```
🔥 branch-name text
```

**Comment by joaomoreno** [comment]
cc @jrieken

**Comment by joaomoreno** [comment]
If #10561 gets resolved, you can write an extension which does this.

**Comment by joaomoreno** [comment]
Can you show an example?

**Comment by jrieken** [comment]
There you go: https://github.com/Microsoft/vscode-extension-samples/blob/master/completions-sample/src/extension.ts

**Comment by joaomoreno** [comment]
Excellent, great example!
