### ISSUE TITLE
Background updated failed (error 32)

### ISSUE THREAD

**Issue by profiler-bg** [Microsoft/vscode#54051]
- VSCode Version: 1.26.0-insider
- OS Version: Windows 17134.165

Steps to Reproduce:
1. Wait for it to try autoupdate

[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2184686/vscode-inno-updater.log)

**Comment by joaomoreno** [comment]
Interesting... can you show me what's inside `C:\\Users\\Hristo\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\bin`?

**Comment by profiler-bg** [comment]
![image](https://user-images.githubusercontent.com/1459709/42623194-287a2234-85ba-11e8-96f7-9221292f6ab8.png)
Seems empty to me. It just failed again several more times. Resource Monitor doesn't show any file in Local\Programs being open too.

**Comment by joaomoreno** [comment]
That's not cool... Maybe disable background Windows updates in that machine: 

```
"update.enableWindowsBackgroundUpdates": false
```

Do updates work then?

**Comment by profiler-bg** [comment]
![image](https://user-images.githubusercontent.com/1459709/42638370-5c423586-85e5-11e8-9973-1a0db2386d92.png)

I'm starting to think there is something wrong with my machine. RM still doesn't show any access happening in Local\Programs.

**Comment by profiler-bg** [comment]
![image](https://user-images.githubusercontent.com/1459709/42638370-5c423586-85e5-11e8-9973-1a0db2386d92.png)

I'm starting to think there is something wrong with my machine. RM still doesn't show any access happening in Local\Programs.

**Comment by profiler-bg** [comment]
I'll need to reinstall it, as after restarting the computer to test updating in fressh boot, broke it completely.

![image](https://user-images.githubusercontent.com/1459709/42639396-ce3fc782-85e7-11e8-869d-adf35aebdf25.png)

Thanks for looking into it.

**Comment by joaomoreno** [comment]
> I'm starting to think there is something wrong with my machine. 

Me too. :wink: 

Let's uninstall completely, delete all those files and reinstall. When you get an update, let me know what happens.

**Comment by profiler-bg** [comment]
So I did uninstall all version from the machine. Manually deleted whatever was left in app data and used the VSCodeUserSetup-x64, which installed the latest version yesterday. Also reset the background update yesterday. Today after running it, checking for updates and selecting "Restart to update", it still failed.

While Code was running I had several instances of code and the 2 versions of the installer. Restart to update closed all the code instances and popped up the install progress dialog. After some time it gave up and popped the error with the two installer processes still running.

![image](https://user-images.githubusercontent.com/1459709/42684864-43cf9e72-8689-11e8-9143-818f28ee87f8.png)

[vscode-inno-updater.txt](https://github.com/Microsoft/vscode/files/2192140/vscode-inno-updater.txt)

I've changed the extension of the log file as GitHub says it doesn't support it today....

**Comment by joaomoreno** [comment]
That's some impeccable detailing, many thanks! Do you mind giving it another full retry, but this time disable background updates:

```
"update.enableWindowsBackgroundUpdates": false
```

You will go through the old style of updating... does that fail too?

**Comment by profiler-bg** [comment]
It feels to be slightly longer. I haven't timed it, but I've reenabled background update, so I should be able to confirm with the next update.

**Comment by joaomoreno** [comment]
You can force one:

1. Open the `Microsoft VS Code\resources\app\product.json` and change the `commit` field to `outdated`.
2. Restart Code, an update should happen

**Comment by profiler-bg** [comment]
1. Set commit to oudated
2. Restart Code
3. Check for Update
4. Almost immediate change to Installing update which lasts ~30s
5. Restart to Update which closes Code, 5s pass and it reopens, no update progress dialog was shown
6. No error makes it look like a success
7. The commit value is still set to outdated, so you can loop from step 3 (is this normal)?
---
- Checked installer log in temp: log file modified few minutes ago, but message inside claim to be from the 11. Jul (2 days ago)
- Force temp folder cleanup with Code closed
- Start Code & check for update
- Messages now go in order "Downloading update", "Installing update", "Restart to update".
- Restart closes Code and this time shows the backgroud updater progress dialog (viva fresh installer)
- Both installer processes in Task Manager show up as running
- Around 20s after I ahd started the update also started a stopwatch which clocked 4 mins before the installer gave up with the same old message to check the log, which is the same as before but at least the messages timestamp is from now.
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2192487/vscode-inno-updater.log)
- commit is still set to outdated which is something I expected with failed update

looking into the directory tree
%APPDATA%\Local\Programs\Microsoft VS Code Insiders\bin is empty but
%APPDATA%\Local\Programs\Microsoft VS Code Insiders\_\bin is not
![image](https://user-images.githubusercontent.com/1459709/42690156-2b83cd9a-869b-11e8-993e-aa5fce825c20.png)

This bug is voodoo magic level.

**Comment by joaomoreno** [comment]
Truly... Thanks for all the details, very insightful!

**Comment by MikeR-Surewise** [comment]
Has there been any update to this? my VS code still wont update, same problem as was raised in ticket #58342

**Comment by MikeR-Surewise** [comment]
I Did a little checking, and I managed to get it to update... I isolated the updater somewhere, and when it ran, I tried to manually delete the problem files highlighted in the logs... even with no system process of the sort running, code.exe was "still in use by the system."

I closed everything down, and shut off my PC, then turned it back on without even starting VScode, just running the installer on its own. Then it didn't have a problem updating at all. Something is keeping code.exe open even when any and all processes are killed, I'm on the latest version now. Will update here if I keep having update troubles on the later versions

**Comment by profiler-bg** [comment]
Hi, @joaomoreno,

I've tested it again with the 1.30 builds and everything seems to be working as intended now. As I wasn't using it for some time, I'm unable to pinpoint when it was fixed or if it was something that the OS update (current Win 17763.134) helped with.

Thank you for looking into it.
