### ISSUE TITLE
French translation errors

### ISSUE THREAD

**Issue by menardany** [Microsoft/vscode#5405]
- VSCode Version:1.0.0
- OS Version: Win 7

Steps to Reproduce: Configuration title in settings.json

1. `"Update configuration"` line 174 became `"Mettre à jour la configuration"`; must be `"Configuration des mises à jour"`
2. `"problem severities"` line 200, 308 and 370 became `"les problèmes de gravité"`; must be `"la gravité des problèmes"`
3. `"JSON configuration"` line 294 did not translated; must be `"Configuration JSON"`

**Comment by johnliu2016** [comment]
@lukaschal strings location info as following, please fix in files
1. main.contribution.nls.resx.lcl
      <Item ItemId=";updateConfigurationTitle" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[Update configuration]]></Val>
          <Tgt Cat="Text" Stat="Loc" Appr="PreApproved" Orig="New">
            <Val><![CDATA[Mettre à jour la configuration]]></Val>
          </Tgt>
        </Str>
        <Disp Icon="Str" />
        <Modified By="ICizkova" DateTime="2016-03-10T16:02:43Z" />
      </Item>

2. Found 3 instances 
(1) css.contribution.nls.resx.lcl
      <Item ItemId=";lint" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[Controls CSS validation and problem severities.]]></Val>
          <Tgt Cat="Text" Stat="Loc" Appr="PreApproved" Orig="New">
            <Val><![CDATA[Contrôle la validation CSS et les problèmes de gravité.]]></Val>
            <Props>
              <Str Name="TranslationModifiedBy" Val="Locit" />
              <Date Name="TranslationModifiedDate" Val="2014-10-03T13:08:25.1154415Z" />
            </Props>
          </Tgt>
          <Prev Cat="Text">
            <Val><![CDATA[Controls problem severities used in the lint validation.]]></Val>
          </Prev>
        </Str>

(2) less.contribution.nls.resx.lcl
      <Item ItemId=";lessLint" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[Controls LESS validation and problem severities.]]></Val>
          <Tgt Cat="Text" Stat="Loc" Appr="PreApproved" Orig="New">
            <Val><![CDATA[Contrôle la validation LESS et les problèmes de gravité.]]></Val>
            <Props>
              <Str Name="TranslationModifiedBy" Val="MM" />
              <Date Name="TranslationModifiedDate" Val="2015-11-19T10:24:22.650276Z" />
            </Props>
          </Tgt>
          <Prev Cat="Text">
            <Val><![CDATA[Controls problem severities used in the LESS lint validation.]]></Val>
          </Prev>
        </Str>

(3) sass.contribution.nls.resx.lcl
      <Item ItemId=";sassLint" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[Controls Sass validation and problem severities.]]></Val>
          <Tgt Cat="Text" Stat="Loc" Appr="PreApproved" Orig="New">
            <Val><![CDATA[Contrôle la validation Sass et les problèmes de gravité.]]></Val>
            <Props>
              <Str Name="TranslationModifiedBy" Val="Locit" />
              <Date Name="TranslationModifiedDate" Val="2014-10-03T13:35:19.5747833Z" />
            </Props>
          </Tgt>

3 json.contribution.nls.resx.lcl
      <Item ItemId=";jsonConfigurationTitle" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[JSON configuration]]></Val>
          <Tgt Cat="Text" Stat="Loc" Appr="PreApproved" Orig="New" AutoAppr="N/A">
            <Val><![CDATA[Configuration de JSON]]></Val>
          </Tgt>
        </Str>

**Comment by lukaschal** [comment]
Waiting for linguistic input.

**Comment by lukaschal** [comment]
Fixed.

File: src\vs\languages\less\common\less.contribution.nls.resx
ID: ".resx", 0; "lessLint"
SRC: Controls LESS validation and problem severities.
TGT: Contrôle la validation LESS et la gravité des problèmes.

File: src\vs\languages\sass\common\sass.contribution.nls.resx
ID: src\vs\languages\sass\common\sass.contribution.nls.resx
SRC: Controls Sass validation and problem severities.
TGT: Contrôle la validation Sass et la gravité des problèmes.

File: src\vs\languages\css\common\css.contribution.nls.resx
ID: src\vs\languages\css\common\css.contribution.nls.resx
SRC: Controls CSS validation and problem severities.
TGT: Contrôle la validation CSS et la gravité des problèmes.

File: src\vs\workbench\electron-browser\main.contribution.nls.resx
ID: src\vs\workbench\electron-browser\main.contribution.nls.resx
SRC: Update configuration
TGT: Configuration des mises à jour

**Comment by aravantv** [comment]
Another one: "Définition de l'apercu" should be "Apercu de la définition".

Steps to reproduce:

- open a file (typescript in my case)
- right-click on a class or function *usage*

Observed: second entry of the context menu is "Définition de l'apercu (Ctrl+Shift+F10)"

Expected: same entry should be "Apercu de la définition"

**Comment by johnliu2016** [comment]
@lukaschal string location is [goToDeclaration.nls.resx.lcl](https://monacotools.visualstudio.com/Monaco/_git/MonacoLocalization#path=%2FLocalize%2Ffra%2Fvscode%2Fsrc%2Fvs%2Feditor%2Fcontrib%2FgoToDeclaration%2Fbrowser%2FgoToDeclaration.nls.resx.lcl&version=GBmaster&_a=contents)

      <Item ItemId=";actions.previewDecl.label" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[Peek Definition]]></Val>
          <Tgt Cat="Text" Stat="Loc" Appr="PreApproved" Orig="New">
            <Val><![CDATA[Définition de l'aperçu]]></Val>
          </Tgt>
          <Prev Cat="Text">
            <Val><![CDATA[Peek definition]]></Val>
          </Prev>
        </Str>

**Comment by lukaschal** [comment]
Waiting for linguistic input.

**Comment by lukaschal** [comment]
Fixed as suggested.

SRC: Peek Definition
TGT: Apercu de définition
