### ISSUE TITLE
Reload Without Reloading the Terminal

### ISSUE THREAD

**Issue by ahmadawais** [Microsoft/vscode#54054]
I've slowly started moving away from iTerm2 in the favor of xTerm in VSCode. The only problem is my workflow breaks every time I have to reload VSCode after installing a new extension. 

There should be a way to set a setting where reload doesn't affect the running terminals. Otherwise, after every reload I have to start 4 terminal windows with different workflow-watchers in them.

Peace! ✌️

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/20013
