### ISSUE TITLE
Typescript SVGElement is not defined

### ISSUE THREAD

**Issue by superheri** [Microsoft/vscode#54056]
- VSCode Version: Insiders 5a4eab8
- OS Version: Win 10 1803

Works in VSCode 1.25

Steps to Reproduce:

1. Create an element and make it of the type "SVGElement" in a TypeScript File
2. Saying SVGElement is not defined

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
In the status bar, do you see `Typescript 3.0.0-dev ...`? What does your `tsconfig.json` look like?

**Comment by superheri** [comment]
I see Typescript 3.0.0-Insider... and my tsconfig.json I have something like this : 
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "sourceMap": true,
    "allowSyntheticDefaultImports": true,
    "allowJs": false,
    "alwaysStrict": true,
    "module": "es2015",
    "moduleResolution": "node",
    "strict": true,
    "strictNullChecks": false,
    "target": "es5",
    "baseUrl": "/",
    "lib": [ "es6", "dom.iterable" ],
    "experimentalDecorators": true,
    "skipLibCheck": true,
    "typeRoots": [ "node_modules/@types", "typings" ],
    "paths": {
    }
  },
  "include": [
    "*.ts",
  ]

}
```

**Comment by mjbvz** [comment]
Try adding `"dom"` to `"lib"`:

```
    "lib": [ "es6", "dom.iterable", "dom"]
```

If you think this is not correct, please open an issue against typescript
