### ISSUE TITLE
Choice Snippet shows no suggestions

### ISSUE THREAD

**Issue by jkavanagh58** [Microsoft/vscode#54057]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

Code in Snippet ${1|one,two,three|}
When calling snippet, No Suggestions is shown in the drop down value/choice list.

VS Code version: Code - Insiders 1.26.0-insider (5a4eab812bd485942061f71af39f3eabc52a1035, 2018-07-11T09:33:23.382Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz (2 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|4.00GB (1.13GB free)|
|Process Argv|C:\Users\vndTekJXK\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|1.2.6
html-snippets|abu|0.2.1
vscode-css-formatter|aes|1.0.1
spaces-inside-braces|Air|0.4.0
vscode-custom-css|be5|2.7.1
django-html|bib|1.2.0
django-snippets|bib|1.1.0
markdown-preview-github-styles|bie|0.1.2
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.59
excel-to-markdown-table|csh|0.3.1
kixtart|cya|0.0.1
vscode-markdownlint|Dav|0.18.0
bettergitcommits|dav|0.5.0
hunspell-spellchecker|den|1.0.1
docs-markdown|doc|0.1.1
vscode-github-gist|dog|1.0.2
jupyter|don|1.1.4
python-extension-pack|don|1.0.1
xml|Dot|2.3.1
gitlens|eam|8.4.1
vscode-projects-plus|fab|1.18.0
vscode-projects-plus-todo-plus|fab|1.6.3
vscode-todo-plus|fab|2.2.0
azure-storage-explorer|for|0.1.2
macros|ged|1.2.1
css-inline|gio|0.0.1
gc-excelviewer|Gra|2.1.24
beautify|Hoo|1.3.2
vstsservicestatus|jep|1.3.0
vscode-gist|ken|1.2.1
vscode-commitizen|Kni|0.5.0
zeal-theme|kqa|1.1.0
MagicPython|mag|1.0.12
code-beautifier|mic|2.1.0
python|ms-|2018.6.0
azure-account|ms-|0.4.1
csharp|ms-|1.15.2
PowerShell|ms-|1.8.0
vsliveshare|ms-|0.3.395
team|ms-|1.136.0
highlight-dodgy-characters|nac|1.0.0
printcode|nob|2.3.0
vscode-code-outline|pat|0.2.1
markdown-checkbox|PKi|1.3.0
sharecode|Rol|0.4.1
copy-text|sal|0.4.1
html5-boilerplate|sid|1.0.3
vscode-microsoftteams|ste|1.0.6
python|tht|0.2.3
bracket-padder|via|0.0.1
vscode-wakatime|Wak|1.2.3
vscode-todo-highlight|way|0.5.12
jinja|who|0.0.8

(15 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
@jkavanagh58 Thanks, good find!
