### ISSUE TITLE
Setting checkbox label should be clickable

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#54053]
![screenshot from 2018-07-11 15-43-12](https://user-images.githubusercontent.com/22350/42575637-53179cea-8521-11e8-88bd-feda025fee24.png)

Like this codepen: https://codepen.io/anon/pen/QBwOGj

**Comment by cleidigh** [comment]
@roblourens 

I can pick this up since is directly related to the labeling I'm already doing..

**Comment by cleidigh** [comment]
@roblourens 
@joaomoreno 
started to work on this.
unless I'm really off-base, I don't think the simple <label> as suggested will work as the checkbox widget
implements the control as a custom element, not an HTML checkbox.

I think we have to make the entire text a clickable element that toggles the checkbox.  I guess the other nested links can continue to activate the round targets.

Do you guys agree with the above?

**Comment by roblourens** [comment]
Yes I think so
