### ISSUE TITLE
Breadcrumbs need hover feedback

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#54050]
We need to figure out a better hover feedback for the breadcrumbs widget.

**Comment by jrieken** [comment]
I now have this

![jul-11-2018 17-24-04](https://user-images.githubusercontent.com/1794099/42582388-3de6a470-852f-11e8-8651-af6496a8981d.gif)

**Comment by joaomoreno** [comment]
Getting better! :+1: 

Though it's a new hover feedback to our workbench, this actually feels cool to me:

![peek 2018-07-12 10-58](https://user-images.githubusercontent.com/22350/42623219-9bada016-85c2-11e8-9459-54fbc6a7924c.gif)

Give it a try!
