### ISSUE TITLE
The Red Text

### ISSUE THREAD

**Issue by nekolite** [Microsoft/vscode#54066]
![screenshot from 2018-07-11 22-02-10](https://user-images.githubusercontent.com/35808376/42581071-23037634-8556-11e8-8ee5-fb51ff6c84ae.png)

Why i got this red text? the program runs correctly, but why these texts turn to be red?

**Comment by mjbvz** [comment]
Does this still happen with all extensions disabled?

**Comment by mjbvz** [comment]
Closing as not actionable without additional information
