### ISSUE TITLE
When I open a Markdown file,it will open localhost:8090 auto.Can it be close?

### ISSUE THREAD

**Issue by TingYa** [Microsoft/vscode#5406]
- VSCode Version: 1.0 
- OS Version: OS X 10.11.4

Steps to Reproduce:

1. When I open a Markdown file My Chrome will open localhost:8090 auto and when I open such as 20 markdown files,my chrome will open as same as number link.It's so bad

**Comment by bpasero** [comment]
@TingYa very likely an extension you have installed? VS Code by default would not open such a port.

**Comment by TingYa** [comment]
@bpasero Yeah 
I am so sorry about it,my issue I listed is the extension *Markdown*'s feature
Thank you for your answers

**Comment by bpasero** [comment]
Ok I suggest to talk to them then
