### ISSUE TITLE
"Auto-importing" a namespace duplicates preceding comments

### ISSUE THREAD

**Issue by Gama11** [Microsoft/vscode#54063]
VS Code version: Code - Insiders 1.26.0-insider (5a4eab812bd485942061f71af39f3eabc52a1035, 2018-07-11T09:33:23.382Z)
OS version: Windows_NT x64 10.0.17134

Steps to Reproduce:

![](https://i.imgur.com/8DVzkne.gif)

```ts
'use strict';
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
    // some commented out code
}
```

TS version:

![](https://i.imgur.com/xsaWbH5.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/Microsoft/TypeScript/issues/25707 to track this upstream
