### ISSUE TITLE
Undo sometimes undos more than it should

### ISSUE THREAD

**Issue by F4Tornado** [Microsoft/vscode#54068]
Issue Type: <b>Bug</b>

I don't know how to reproduce it, but what it is, is that when I press undo, it very rarely continues undoing after it was pressed, deleting a lot of work. EDIT: I found that it's only a visual thing, the code comes back when it's done.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (7.89GB free)|
|Process Argv|D:\all items\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
p5js-snippets|aci|0.0.6
beautify|Hoo|1.3.2
vsliveshare|ms-|0.3.379

(1 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment]
@F4Tornado Do you have any reproducible steps?

**Comment by F4Tornado** [comment]
No, I don't know what causes it, just that is sometimes happens. I also noticed that it's only visible, when it's done, the code comes back. It just gave me a REALLY big scare.

**Comment by alexandrudima** [comment]
@F4Tornado :+1: Please keep an eye out and if you see this happening again try to figure out some steps so we can reproduce.
