### ISSUE TITLE
Zen mode broke content width

### ISSUE THREAD

**Issue by luchillo17** [Microsoft/vscode#54073]
Issue Type: <b>Bug</b>

Just entered zen mode & now the main content panel doesn't use the full width of the screen, exiting from zen mode after that didn't fixed the issue.

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:10:37.273Z)
OS version: Linux x64 4.15.0-24-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 3368)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 9, 12|
|Memory (System)|15.57GB (0.45GB free)|
|Process Argv|/usr/share/code/code --disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled

![image](https://user-images.githubusercontent.com/9698639/42583212-211f66f8-84f6-11e8-83f6-e452a56ed342.png)

![image](https://user-images.githubusercontent.com/9698639/42583256-360a16e4-84f6-11e8-9eb5-3b754e5f118b.png)

**Comment by luchillo17** [comment]
Yep, duplicated of https://github.com/Microsoft/vscode/issues/52566, i never got into that `Centered Layout Mode`, is it a default? if so i think it's wrong, should be off by default.

**Comment by isidorn** [comment]
`"zenMode.centerLayout": "false"`

**Comment by luchillo17** [comment]
I know of that setting, searched after finding the duplicated, i'm saying the centered layout mode should be separated for zen & normal mode, so one can be in centered mode while the other doesn't.
