### ISSUE TITLE
Scroll Behaviour Tottally Messed up

### ISSUE THREAD

**Issue by nikksan** [Microsoft/vscode#54072]
**Configation**
- VS Code version: 1.25.0
- OS Version: Ubuntu 18.04 LTS

**Steps to Reproduce:**
1. Start scrolling down/up on the desktop or any other place
2. Switch over to Visual Code
3. The moment you try to scroll on the opened file the scroll will scroll instantly in the direction that you have been scrolling in step 1

_There is an existing workaround which requires the installation of `imwheel` but this ultimately disables by back/forth buttons._

**Comment by alexandrudima** [comment]
This sounds like an issue with the OS, with the driver, or with the way the installation is configured.

I am not able to reproduce with a steelseries mouse.
