### ISSUE TITLE
Window of the code too long for closing all files.

### ISSUE THREAD

**Issue by nowapoca** [Microsoft/vscode#54076]
Hi, it is a small thing but It is very important to me. When I want to close all the files in Visual Code, I have to move the mouse for finding and closing all the different windows, and it depends of the size of the name. It is a small thing but it could be a nice change.

![visualstudiorequest](https://user-images.githubusercontent.com/34867334/42584213-0d10d198-8509-11e8-84e6-4d134edaf855.png)
I have to move the mouse for closing them all!

Thank for reading!

**Comment by Tyriar** [comment]
There are many options for closing tabs in the context menu, there are also keybindings you can look up in preferences.

<img width="279" alt="screen shot 2018-07-11 at 9 13 21 pm" src="https://user-images.githubusercontent.com/2193314/42612270-4fd46ada-854f-11e8-8e1f-eba2a1be3845.png">
