### ISSUE TITLE
Context view doesn't layout content

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#54075]
See attached screen shot. My expectation is that the context view checks the size of its children and positions them so that they fit into the screen, e.g moves them left a little in this case.

<img width="338" alt="screen shot 2018-07-11 at 17 49 50" src="https://user-images.githubusercontent.com/1794099/42584171-df0101ea-8532-11e8-8d2f-ae5b90e57275.png">

**Comment by joaomoreno** [comment]
The breadcrumb picker was positioned absolute, so it wasn't in the layout tree. Check the fix and whether it breaks any other assumptions you had because of `position: absolute`.

**Comment by jrieken** [comment]
Yeah, that was oversight to still have them. I have added to because when the context view wasn't in the workbench subtree, adding the the `monaco-workbench` style would conflict with the context view styles...
