### ISSUE TITLE
Breadcrumbs title aligned to top, when icon theme is not `null`.

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#54086]
Issue Type: <b>Bug</b>

![top_aligned](https://user-images.githubusercontent.com/9638156/42588904-d62296dc-8547-11e8-828f-de07f2bae725.png)

VS Code version: Code - Insiders 1.26.0-insider (5a4eab812bd485942061f71af39f3eabc52a1035, 2018-07-11T09:33:23.382Z)
OS version: Windows_NT x64 10.0.17134

**Comment by jrieken** [comment]
fixed in latest
