### ISSUE TITLE
Wrong path is pasted into integrated terminal while using drag and drop from opened folder

### ISSUE THREAD

**Issue by FIFOFridge** [Microsoft/vscode#54089]
- VSCode Version: 1.25.0
- OS Version: Windows 10

Steps to Reproduce:

1.  Open Menu "File"
2.  Select "Open folder" and open some folder
3.  Drag and drop some file into integrated terminal

Result path is always prefixed by slash ("/").
example:
"/c:/Users/FIFOFridge/TR/src/main/index.js"

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/29926
