### ISSUE TITLE
Integrated terminal going blank after network disconnect

### ISSUE THREAD

**Issue by MandarJKulkarni** [Microsoft/vscode#54080]
I am facing a variant of issue #18415
Integrated Terminal Going Blank #18415 (https://github.com/Microsoft/vscode/issues/18415)

- VSCode Version: 1.25.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open VS code and run some commands in the integrated terminal 
2. If I close the lid, then the laptop goes into sleep mode.
3. After I re-open the laptop, the integrated terminal mostly goes blank.
4. Sometimes, the terminal is not blank and if I run the previous command (e.g. git branch), I get response something like this.
 _0 [main] less 12440 C:\Cygwin\bin\less.exe: *** fatal error - add_item ("\??\C:\Cygwin", "/", ...) failed, errno 1
Stack trace:
Frame     Function  Args
End of stack trace_

Does this issue occur when all extensions are disabled?: 
No. The commands worked fine after disabling the extensions.
Extensions installed are Python, flask, VSTS, Docker and Code coverage.

**Comment by MandarJKulkarni** [comment]
The issue #43619 cannot be resolved after VS code is restarted.
However this issue disappears after I restart the VS code.

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
