### ISSUE TITLE
Open Folder From Windows Explorer

### ISSUE THREAD

**Issue by ericnyc646** [Microsoft/vscode#54082]
When in windows explorer, it would be nice if I could open the folder with Visual Studio code.  For large projects, we focus on one area at a time which means that we have to copy the folder location and then ask VS Code to open it.

I noticed this option is available for Visual Studio.

This would be a huge productivity bump.

**Comment by ManNguyen** [comment]
You can do that by right click in the folder -> [Open with Code]
https://gyazo.com/e57daf40a8f3752323aeb7840c5e1542

Make sure to check all of the boxes when you install VSCode.

**Comment by ManNguyen** [comment]
You can do that by right click on the folder then [Open with VS Code]
https://gyazo.com/e57daf40a8f3752323aeb7840c5e1542

Make sure to check all of the boxes when you install VSCode. You can reinstall to get that feature.

**Comment by ericnyc646** [comment]
Fantastic, this open should be on by default.

Thank you!
