### ISSUE TITLE
vscode (insiders) hangs when opening large powershell script

### ISSUE THREAD

**Issue by rfoust** [Microsoft/vscode#54099]
- VSCode Version: 1.26.0-insider
- OS Version: MacOS 10.13.5

Steps to Reproduce:

1. Open large powershell script
2. VSCode hangs

Does this issue occur when all extensions are disabled?: Yes

I can't reproduce the problem on the latest stable vscode release. Just insiders.

I captured a javascript profile thing with extensions enabled, but the same problem occurs with extensions disabled.  The file is 28mb so I've placed it elsewhere for download:

https://duke.box.com/s/0cwoa5wk61v21qetq6tk44ejuo28ps6v

**Comment by Tyriar** [comment]
@rfoust how big is the file? Do you have the powershell extension and have you tried launching and checking with `code-insiders --disable-extensions`?

**Comment by rfoust** [comment]
@Tyriar Yes it happens with --disable-extensions.  The file is just under 91k in size and 2377 lines long.  A little more info... Even though vscode seems mostly unresponsive, eventually it pops up a window and says "The window is no longer responding." I can keep clicking "Keep Waiting" and eventually after a few minutes the syntax highlighting finishes doing it's thing and it starts responding again.  It seems to be just on the initial load/processing of the file.  I can provide the file privately if needed.

**Comment by rfoust** [comment]
Any updates? This is still an issue on the insiders build.

**Comment by rfoust** [comment]
I reformatted the code a bit and cleaned it up some, and now I no longer have the problem.  So not sure what about it was causing vscode to break.  I'll leave it up to you guys if you want to look into the cause of the problem or not.  Otherwise feel free to close this issue.

**Comment by manigandan-jegannathan-developer** [comment]
I am also facing this issue with large PS code. Any workaround ?

**Comment by rebornix** [comment]
@rfoust sorry for responding late. Do you think it's possible that you can provide a ps file for me to troubleshoot?
