### ISSUE TITLE
Terminal.onDidWriteData sends duplicate data

### ISSUE THREAD

**Issue by alpaix** [Microsoft/vscode#54096]
Version: 1.25.0-insider
Commit: fb0b8f12036bfb69a47a1b3354126794a093e749
Date: 2018-07-03T09:09:37.369Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

#### The problem

The terminal will fire the same event multiple times when extension code is written like the following
```ts
if (terminal.onDidWriteData) {
    terminal.onDidWriteData(data => { console.log(data); });
} 
```

The reason for that is the `onDidWriteData` getter has a side effect as it [registers](https://github.com/Microsoft/vscode/blob/7396416d7a35f1a4187c558dc050908d60a1f632/src/vs/workbench/api/node/extHostTerminalService.ts#L80) a data listener on every call.

**Comment by Tyriar** [comment]
Moving to August as I believe this is as it was before. Testing this works for me when attaching the listener in a separate command (not immediately after). Tracking @octref's problem in https://github.com/Microsoft/vscode/issues/55777
