### ISSUE TITLE
Breadcrumbs are not visible in new (untitled) files after the language mode is set

### ISSUE THREAD

**Issue by qcz** [Microsoft/vscode#54094]
Issue Type: <b>Bug</b>

Breadcrumbs are not visible when no workspace or folder is opened. However, outline information is still available in these files, so I would expect that it is displayed. Visual Studio displays the breadcrumb when no solution is opened.

VS Code version: Code - Insiders 1.26.0-insider (5a4eab812bd485942061f71af39f3eabc52a1035, 2018-07-11T09:33:23.382Z)
OS version: Windows_NT x64 10.0.17134

**Comment by jrieken** [comment]
@qcz Can you still reproduce? All of this is pretty fresh and it might be working with my recent changes

<img width="940" alt="screen shot 2018-07-12 at 12 08 54" src="https://user-images.githubusercontent.com/1794099/42627115-5f0ed850-85cc-11e8-9ce2-e32f35ebf3f8.png">

**Comment by jrieken** [comment]
Ok, understood. For `untitled` document we currently bail out early but that isn't the smart thing to do...
