### ISSUE TITLE
Can not play video in webview

### ISSUE THREAD

**Issue by wk-j** [Microsoft/vscode#54097]
Both YouTube and Vimeo video are not playable in webview

<img width="685" alt="youtube" src="https://user-images.githubusercontent.com/860704/42596017-5f60043a-857e-11e8-99b7-29623ee0ebc4.png">

- VSCode Version: 1.25.0
- OS Version: macOS

```html
<!DOCTYPE html>
<html lang="en">

<head> </head>

<body>
    <iframe src="https://player.vimeo.com/video/277584430" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen
        allowfullscreen></iframe>

    <iframe class="frame" width="560" height="315" src="https://www.youtube.com/embed/BHQfBbQBRWM?rel=0&amp;showinfo=0" frameborder="0"
        allow="autoplay; encrypted-media" allowfullscreen>
    </iframe>
</body>

</html>
```

Steps to Reproduce:

1. Debug extension project
2. Open webview

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
We don't ship ffmpeg in our electron build. Many audio and video formats are therefore not supported inside webviews. No plans to change this
