### ISSUE TITLE
Improve presentation of the built in extensions view in the details section

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#54098]
- [x] Better icon for basic programming languages cc @misolori 
- [x] How to contribute goes to a separate md file and linked from readme
- [x] Standardize the readmes. 
       - h1 for name
       - Notice about this being a built-in extension and so can disabled but not uninstalled
       - h2 for Features 
           - This can be linked to our docs
           - or to hand written features
           - or for extensions without readme file, this will be extension description
       - h2 for Settings (optional)
- [x] `npm` and `Configuration Editing` extensions should be under features and and not under "Programming Languages"
- [x] Bug: Settings for Css langauge features extension doesnt show up in the "Contributions" section #54116 
- [x] Changelog -> Link to release notes either in product or website

**Comment by misolori** [comment]
@ramya-rao-a would this icon work for the basic programming languages?

![image](https://user-images.githubusercontent.com/35271042/42599854-68c66230-8515-11e8-8601-40262c8e7f8e.png)

Dark theme
![image](https://user-images.githubusercontent.com/35271042/42600012-d168f17c-8515-11e8-8399-6d50db0ba253.png)

Light theme
![image](https://user-images.githubusercontent.com/35271042/42600073-f9f174fc-8515-11e8-811c-d63eb03724ae.png)

**Comment by ramya-rao-a** [comment]
@JacksonKearl Not all of the builtin extensions have the `How to contribute` sections. Only the complex ones. See css, html, emmet
