### ISSUE TITLE
Typescript+JSX Syntax Highlighting in generator functions

### ISSUE THREAD

**Issue by nmain** [Microsoft/vscode#54091]
- VSCode Version: 1.25.0 (ia32)
- OS Version: Windows 10

Steps to Reproduce:

1. Create a `.tsx` file with the following content:
```
class Baz { }

class F {
	public *foo() {
		yield <Baz />;
	}
	
	public fuu() {
		return <Baz />;
	}
}
```
2. Look at the syntax highlighting.  The first `<Baz />` won't have the correct syntax highlighting.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#636
