### ISSUE TITLE
Support diagnostics references from TypeScript 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#54102]
Tracks the VS Code side support for https://github.com/Microsoft/TypeScript/issues/25257

This feature adds related information on some diagnostics

**Comment by JacksonKearl** [comment]
I was only able to get this to trigger on use before declaration, I think there should be more trigger, based on the related issue on the TS side. @mjbvz  this was my file:

```
import * as express from 'express'

let a: unknown = {}

let ob = {
    'aaa': 1,
    'bbb': 2
}

let b: number = a // nothing for incompatible assignment

let c = express(); // nothing for calling CommonJS import (this was the big screenshot in the linked issue)

ob.aab = 4 // nothing for "did you mean"

r = 4; // does trigger:  "r is declared here: ..."
let r: number;
```

**Comment by mjbvz** [comment]
I confirmed that feature does the right thing on our side. Here are the followups from your example:

1. Opened https://github.com/Microsoft/TypeScript/issues/26145 for this
1. Not sure why this would is error since the `@types` typings do indicate that the exported namespace is a function. Will follow up to see if this is expected or not
1. Does show up if you make the name slightly longer: `aaab`. TS is a bit conservative with 'did you mean' checks. Will open another issue for this
