### ISSUE TITLE
Bash terminal in live-share prints color codes

### ISSUE THREAD

**Issue by tsraza** [Microsoft/vscode#54106]
The formatting codes for bash are printed instead of formatting the text.

- VSCode Version: 1.22.2
- OS Version: Windows 7

Steps to Reproduce:

1. Use a live-share bash terminal
2. Type anything

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by Tyriar** [comment]
https://github.com/MicrosoftDocs/live-share
