### ISSUE TITLE
Tooltips disappear too fast to take a screenshot in MacOS

### ISSUE THREAD

**Issue by lukepighetti** [Microsoft/vscode#54108]
If you are trying to take a screenshot in MacOS of something including tooltips, they disappear too fast to be able to snap them. Which is interesting, because usually MacOS manages to keep things like tooltips up in most other applications when taking a screenshot.

Happens with Command-Shift-3 and Command-Shift-4

It appears to be connected with pressing Shift.

**Comment by sean256** [comment]
This has been driving me mad lately, I'm glad I'm not the only one. I've been wanting to send screenshots to my junior devs.

**Comment by lukepighetti** [comment]
It's impossible to send any meaningful screenshots with VSC on macOS.

**Comment by alexandrudima** [comment]
You can use the grab app that is shipped with macOS and is authored by Apple to create a timed screenshot. https://support.apple.com/en-gb/guide/grab/welcome/mac

I don't think taking screenshots should be taken into account to influence the UX of a product.

**Comment by lukepighetti** [comment]
@alexandrudima Is there a good reason for the tooltips to disappear only when you press shift? If not, perhaps you will reconsider your position.

**Comment by sean256** [comment]
> I don't think taking screenshots should be taken into account to influence the UX of a product.

As an engineer taking screenshots is absolutely part of my user experience.

**Comment by alexandrudima** [comment]
@lukepighetti @sean256 

The idea is the following: If you move the mouse over some symbol and the hover shows up, the hover gets immediately dismissed when you begin typing. Say, for example you forget the type name of some variable, you would hover it and then learn the type name, and then proceed to type it. As soon as you begin to type, the hover gets out of the way so you can see the code you are editing.

**Comment by lukepighetti** [comment]
I wonder if it would work if you just make it so shift didn't hide tooltips. Shift doesn't send any text to the window so it would seem like a reasonable compromise

**Comment by lukepighetti** [comment]
@alexandrudima Thank you!

**Comment by lukepighetti** [comment]
<img width="1073" alt="screen shot 2018-09-11 at 8 34 18 am" src="https://user-images.githubusercontent.com/666539/45360974-fb471500-b59e-11e8-886e-0edfca409458.png">

Yeeeeaaaaahhh!!! 😄
