### ISSUE TITLE
Toggling working files shows error

### ISSUE THREAD

**Issue by pratyushsharma** [Microsoft/vscode#5410]
- VSCode Version:1.0.0
- OS Version: OS X 10.11.3

Steps to Reproduce:

1. Press ⌘K ↑	for toggling working file

Error
![screen shot 2016-04-17 at 3 57 00 pm](https://cloud.githubusercontent.com/assets/4585580/14586416/1254061a-04b5-11e6-9df6-a285c1a52b72.png)

**Comment by egamma** [comment]
This works as expected, but you have to press ⌘K  (then release ⌘) ↑
