### ISSUE TITLE
vscode.executeCodeActionProvider returns inconsistent types

### ISSUE THREAD

**Issue by daytonellwanger** [Microsoft/vscode#54100]
The `vscode.executeCodeActionProvider` command should return an array of `CodeAction`:
```
{
    title: string;
    command?: Command;
    edit?: WorkspaceEdit;
    diagnostics?: IMarkerData[];
    kind?: string;
}
```
However, when running this command, some of the code actions returned by extensions are of a different type.

An example returned by the "Code Spell Checker" extension:
```
{
    command: "cSpell.addWordToUserDictionarySilent",
    title: "Add word to dictionary",
    arguments: [...]
}
```

Even for code actions that seem to be of type `CodeAction`, their `command` properties don't follow the `Command` type definition.

"Organize imports":
```
{
    title: "Organize Imports",
    command: {
        command: "_typescript.organizeImports",
        title: "",
        arguments: [...]
    },
    kind: {
        value: "source.organizeImports"
    }
}
```

"Delete all unused declarations" also returns an object with the same properties. It looks like the `command` property on the `Command` object should be called `id` (the `Command` interface has no property `command`). 

Is this a problem of the extensions providing code actions? Or is this a VS Code issue with how the code actions are collected?

**Comment by jrieken** [comment]
Returned a mixed type (CodeAction or Command) reflects what providers can return and looking at the code it seems to be on purpose.


> It looks like the command property on the Command object should be called id (the Command interface has no property command).

Not sure why you say that. See https://github.com/Microsoft/vscode/blob/0247a861a30d60ab0e895dd65494a3399bd4a2d8/src/vs/vscode.d.ts#L19

**Comment by daytonellwanger** [comment]
As to providers returning a `CodeAction` or `Command`, I was looking at [getCodeActions in codeAction.ts](https://github.com/Microsoft/vscode/blob/0247a861a30d60ab0e895dd65494a3399bd4a2d8/src/vs/editor/contrib/codeAction/codeAction.ts#L19), which returns `Promise<CodeAction[]>` (not `Promise<(CodeAction | Command)[]>`).

That [`Command`](https://github.com/Microsoft/vscode/blob/0247a861a30d60ab0e895dd65494a3399bd4a2d8/src/vs/editor/common/modes.ts#L934) referenced from that[ `CodeAction` type](https://github.com/Microsoft/vscode/blob/0247a861a30d60ab0e895dd65494a3399bd4a2d8/src/vs/editor/common/modes.ts#L344) has a property `id` instead of `title`.

Looking at the `CodeActionProvider` interface in `vscode.d.ts`, it does return `(Command | CodeAction)[]`, and that `Command` is the one you reference with property `title` instead of `id`.

Looks like I got confused by looking at the internal types instead of the API.

**Comment by jrieken** [comment]
Yeah, our internal api is slightly different here and there
