### ISSUE TITLE
SCM viewlet missing style

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#54105]
- Open multiroot workspace, see SCM viewlet
- There's no space between the name and type of a repo:

![image](https://user-images.githubusercontent.com/323878/42598506-45b9e266-8511-11e8-8913-e249156e1b57.png)

**Comment by joaomoreno** [comment]
Broken by https://github.com/Microsoft/vscode/commit/0e68a1a14acf64352d93a23007442f212864727e#diff-da29f645d60a46d84c5ce858aeda68a6L54 cc @JacksonKearl will revert the change... any idea why this came in, in the first place?
