### ISSUE TITLE
No import suggestions when using rootDirs and inherited tsconfig.json

### ISSUE THREAD

**Issue by gremo** [microsoft/vscode#54107]
#### System information

- OS: Windows 10 x64
- VSCode version: 10.25.0

#### Description

No import suggestions when using `rootDirs` and inherited `tsconfig.json`.

##### Steps to reproduce

Simple directory structure:

```
.
├── common              # import a .ts file living here (customer.ts)
├── server
│   └── tsconfig.json   # custom TypeScript config file (inherits from main)
├── tsconfig.json       # main TypeScript config file
```
Contents of `customer.ts`:

```typescript
export class Customer { }
```

Contents of `tsconfig.json`:

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
```

Contents of `server/tsconfig.json`:

```json
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../dist",
    "module": "commonjs",
    "rootDir": "../",
    "rootDirs": [
      "./",
      "../common"
    ]
  }
}
```

As you can see I added `common` folder to `rootDirs` in order to import a class exported by `common/customer.ts`.

When I try to import `Customer` class from `server/repository/customer.repository.ts` there are no suggestions at all.

![cattura](https://user-images.githubusercontent.com/1532616/42728644-3532d190-87bf-11e8-9514-ed85fb7a3130.gif)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code build](https://code.visualstudio.com/insiders/) with all extensions disabled? The latest insiders includes typescript 3.0

**Comment by gremo** [comment]
@mjbvz Yes, the same. Even switching to a different (local) TypeScript version lead to the same result, no suggestions.

**Comment by mjbvz** [comment]
@gremo Can you please provide a more complete example? I can't repo this using the basic setup the issues describes

**Comment by gremo** [comment]
`git clone https://github.com/gremo/angular-fullstack`, then `yarn install`, open VS code 1.27.1 and create a new file `common/entities/customer.ts` with:

```typescript
export class Customer { }
```

The edit `server/app.ts` and paste `const c = new Customer();` just after the `import` statements.

As you can see, no suggestions at all. Using latest VS code 1.27.1 with Typescript 3.0.3.

**Comment by mjbvz** [comment]
Sorry for the long delay getting back on this one. I just tested this again and confirmed everything seems to be working using VS Code's version of TS:

![Screen Shot 2019-05-29 at 3 53 13 PM](https://user-images.githubusercontent.com/12821956/58596704-f0fea100-8229-11e9-8329-ba63aeda341e.png)
