### ISSUE TITLE
Alt keyboard shortcuts focus menu

### ISSUE THREAD

**Issue by JacksonKearl** [Microsoft/vscode#54109]
Issue Type: <b>Bug</b>

Using an alt keyboard shortcut (`alt_t` for instance) will cause the menu to be focused after the action has occured.

VS Code version: Code - Insiders 1.26.0-insider (5a4eab812bd485942061f71af39f3eabc52a1035, 2018-07-11T09:33:23.382Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (5.98GB free)|
|Process Argv|C:\Users\t-jakea\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.19.1
gitlens|eam|8.4.1
tslint|eg2|1.0.33
debugger-for-chrome|msj|4.7.0
subtle-brackets|raf|2.1.1
vscode-multiclip|sle|0.1.4
code-spell-checker|str|1.6.10

(1 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
same root cause as #54047
