### ISSUE TITLE
Selection lost on rename

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#54117]
Have this code:

```ts
let asdf  = 1;

asdf++;
```

- Cursor on the second asdf, after f
- f2 rename
- Rename to `asd`.
- Cursor sometimes goes to the first `asdf` when it should stay on the second

![jul-11-2018 16-55-18](https://user-images.githubusercontent.com/323878/42605155-3918eef2-852b-11e8-8adc-1e36fafcc060.gif)

**Comment by jrieken** [comment]
Yeah, I was waiting for that ;-)
