### ISSUE TITLE
Some forms change to fuzzy pixels

### ISSUE THREAD

**Issue by owtotwo** [Microsoft/vscode#5411]
`bug`

- VSCode Version: 1.0
- OS Version: Microsoft Windows 10

Issue : Some forms change to fuzzy pixels.

Steps to Reproduce:

1.  Launch the VScode
2.  Ctrl + '=' (zoom in)
3.  OUTPUT something (i.e. build project)
4.  Words are covered some mist..

Like this...
![image](https://cloud.githubusercontent.com/assets/13444035/14603615/643993d6-05a1-11e6-9c3d-030cff6723dc.png)
(PS: maybe you should zoom in the graph above to the high definition. The words in the middle form are fuzzier than the right form obviously... *Sometimes*  I select almost all the text by dragging the mouse then It will be fuzzy!)

**Comment by owtotwo** [comment]
It dizzied me...but I do not want to give up the vscode... it is a nice application for developers...

**Comment by bpasero** [comment]
We pushed a major update to the UI framework to our insiders release and would appreciate feedback if this issue got resolved. You can give it a try from our insiders release today: http://code.visualstudio.com/Download#insiders

Happy for feedback!

**Comment by owtotwo** [comment]
@bpasero 
It seems not to be improved... Maybe it is my computer problem....?
![image](https://cloud.githubusercontent.com/assets/13444035/14706917/294b9292-07f4-11e6-92f2-2b8617bbf88d.png)

**Comment by owtotwo** [comment]
@bpasero 
It seems not to be improved... Maybe it is my computer's problem....?
![image](https://cloud.githubusercontent.com/assets/13444035/14707002/9e81a042-07f4-11e6-8d26-17d335653db2.png)

**Comment by owtotwo** [comment]
But it is no problem in win7 installed in the same computer...
![image](https://cloud.githubusercontent.com/assets/13444035/14707421/562b54c0-07f7-11e6-8950-4200ca996efc.png)

**Comment by owtotwo** [comment]
well ... Is there any progress...?

**Comment by alexandrudima** [comment]
@owtotwo Yes, I'm working on a change that disables our usage of `translate3d` when the `zoomLevel` is not 0. Since it was filed before, let's track progress in #959

**Comment by owtotwo** [comment]
thanks a lot!
