### ISSUE TITLE
Window stops responding on "check for updates" in extension viewlet

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#54115]
- Just run "Check for updates"
- Window stops responding for a minute

I can repro it consistently but @ramya-rao-a can't. Let me know how I can help debug it...

**Comment by sandy081** [comment]
@roblourens Can you get the logs (window and shared) and show me? May be enabled log level to trace to get more info.

**Comment by sandy081** [comment]
Duplicate #54041
