### ISSUE TITLE
Git multi select and stage is broken

### ISSUE THREAD

**Issue by nikonso** [Microsoft/vscode#54112]
Issue Type: <b>Bug</b>

Refer to #43787

This is happening again in stable and on the latest insiders,

Edit: It only happens when using 

` "window.titleBarStyle": "custom"`

VS Code version: Code - Insiders 1.26.0-insider (5a4eab812bd485942061f71af39f3eabc52a1035, 2018-07-11T09:38:12.464Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.94GB (3.72GB free)|
|Process Argv|C:\Users\bmf.ribeiro\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.19.1
vagrant|bbe|0.5.0
solargraph|cas|0.17.5
vscode-eslint|dba|1.4.12
githistory|don|0.4.1
gitlens|eam|8.4.1
tslint|eg2|1.0.33
vscode-npm-script|eg2|0.3.5
ruby-linter|hoo|1.0.0
Ionide-fsharp|Ion|3.22.3
docthis|joe|0.7.1
VS-code-vagrantfile|mar|0.0.7
prettify-json|moh|0.0.3
csharp|ms-|1.15.2
PowerShell|ms-|1.8.1
vscode-docker|Pet|0.0.27
material-icon-theme|PKi|3.5.1
Ruby|reb|0.18.0
vscode-icons|rob|7.24.0
gitblame|wad|2.4.2

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Can you show me the full steps of what you do to reproduce this issue? Can you reconfirm that it only happens with `"window.titleBarStyle": "custom"`?

**Comment by nikonso** [comment]
Yes, it only happens  with "window.titleBarStyle": "custom"..

>
I believe I misunderstood the other issue, mine is slightly different, they
are both selected but when I press stage, only one of the files is staged.

**Comment by joaomoreno** [comment]
Can you show me the full steps of what you do to reproduce this issue?

**Comment by nikonso** [comment]
https://gfycat.com/SlipperyGloomyDartfrog

Screen capture of the bug

João Moreno <notifications@github.com> escreveu no dia quinta, 12/07/2018
à(s) 14:52:

**Comment by nikonso** [comment]
Screen capture of the bug

![slipperygloomydartfrog](https://user-images.githubusercontent.com/16099035/42655193-309f530e-8613-11e8-8ebd-0c62392ba532.gif)

**Comment by joaomoreno** [comment]
So... broken doesn't mean that it doesn't work... just that it works partially. And you use the context menu to stage. A current workaround for you is to use the inline `+` actions... they also work when you have multiple selection.

---

@sbatten Those actions use special contexts to support multiple selection. Can you double check?

**Comment by joaomoreno** [comment]
This wasn't due to your changes @sbatten... the _fake_ menu, which predates you, wasn't ready for getting passed an `actionRunner`. I went ahead and fixed that up.

**Comment by nikonso** [comment]
Yeah, the title could have been clearer...

Thank you for the quick fix!
