### ISSUE TITLE
Theme syntax error

### ISSUE THREAD

**Issue by ltt2801** [Microsoft/vscode#54126]
Issue Type: <b>Bug</b>
```php
$sql = "INSERT INTO `table_1` (`name`) SELECT REPLACE(`name`, '\' ', '') as `name` FROM `table_2`";

mysql_query($sql);
```
Structures are correct but highlight theme error

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.14393

**Comment by aeschli** [comment]
I assume your editor is in PHP mode:

That's what I see in the latest:

![image](https://user-images.githubusercontent.com/6461412/45544279-2c317f00-b817-11e8-8b1a-6b5838b3ee89.png)

That looks fine to me. Please reopen if you disagree. Please describe what you see and expect.
