### ISSUE TITLE
clicking inside function body wont highlight the outline entry

### ISSUE THREAD

**Issue by linuxjh** [Microsoft/vscode#54121]
clicking on function name from the title highlights the outline entry. this is good. thanks!

it doesn't work if i click somewhere inside function body or click else where from the title (eg. return type, parameter list).

version: 1.25.0
ext: ms-vscode.cpptools

**Comment by jrieken** [comment]
/duplicate of https://github.com/Microsoft/vscode-cpptools/issues/2230
