### ISSUE TITLE
Freezes when opening xml files having 3000+ lines

### ISSUE THREAD

**Issue by julian-bieringer** [Microsoft/vscode#54128]
Issue Type: <b>Bug</b>

*Open an xml file with more than 3000 lines
*Hit search and search for a sequence
*You can type something but cannot delete anything

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:10:37.273Z)
OS version: Linux x64 4.15.0-24-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1396)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|15.43GB (6.11GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by rebornix** [comment]
@julian-bieringer is it possible that you can share the xml or you can create a sample xml that leads to the same error? It can help me better troubleshoot.
