### ISSUE TITLE
Latest VS Code update doesn't resolve typescript module paths correctly

### ISSUE THREAD

**Issue by waelkdouh** [Microsoft/vscode#54120]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by burtek** [comment]
![image](https://user-images.githubusercontent.com/2940958/42623115-513485f4-85c2-11e8-8c7d-9a1615a8d9a9.png)
All typescript modules are suggested to be imported relatively from `node_modules/@types/...` rather then directly from corresponding package.

**Comment by matulkum** [comment]
+1 (with version 1.24 it definitely still works for me)

**Comment by burtek** [comment]
Might be duplicate of #53894 ?

**Comment by waelkdouh** [comment]
@matulkum  I am on version 1.25. It was still working for me on 1.24. 
@burtek when I create a project with the angular cli and I try to import some class from the @angular/core is used to suggest the following which is clean: 
import {Component} from '@angular/core'. 
Now it suggests the following which is messy: 
import { Component } from "../../node_modules/@angular/core";
What am I missing here? And why is the behavior changing from one version to the other?

**Comment by waelkdouh** [comment]
@burtek you are correct it does seem to be a duplicate of #53894. I will continue the discussion there.
