### ISSUE TITLE
Ability to hide functions in variables window when debugging typescript/javascript

### ISSUE THREAD

**Issue by harleybl** [microsoft/vscode#54125]
Often when I am debugging my Typescript application the variables window is cluttered with all sorts of things that normally I don't care about. Most of them are functions. For instance if I have an object with 2 attributes, in order to see the values of those attributes I have to scroll past all the member function definitions that I defined on the object (and it's ancestor's function definitions to get to see the values of the attributes. 

I think most developers don't need to see functions like __defineGetter__, __defineSetter__, etc in the variables window. It would be nice if there were toggles at the top of the variables window to turn on and off viewing different types of variables.

Perhaps this would be better as a plugin since it is Typescript/Javascript specific.

**Comment by weinand** [comment]
This would be a feature of the node-debuggers...

**Comment by roblourens** [comment]
You can try the new tree filtering feature to help with this. Just type when the variables view has focus and click the button on the orange decoration to switch to "filter" mode. I don't think we plan to do any other improvements here in the near future.
