### ISSUE TITLE
js files are not excluded from explorer view in Mac OS X 10.9

### ISSUE THREAD

**Issue by tarurar** [Microsoft/vscode#5413]
- VSCode Version: 1.0.0
- OS Version: Mac OS X 10.9

Steps to Reproduce:

1. open settings.json
2. add following settings 
```json
{
    "files.exclude": {       
        "**/*.js": {"when": "$(basename).ts"}
    }
}
```
*.js files still apears in Explorer.

**Comment by bpasero** [comment]
@tarurar this will only hide *.js files if there are *.ts files with the same name. Otherwise just say "true" instead of using the when condition.

**Comment by tarurar** [comment]
Ok, @bpasero, please have a look at the screenshot attached. *.js and *.map files didn't dissapear from the explorer.
<img width="1440" alt="screen shot 2016-04-17 at 20 06 14" src="https://cloud.githubusercontent.com/assets/142044/14588334/18d928f8-04d8-11e6-8ff3-10c22d0b01b5.png">

**Comment by bpasero** [comment]
@tarurar you missed the "*" in "*.js"?

**Comment by tarurar** [comment]
Haven't got it. What is the questions, actually?

**Comment by bpasero** [comment]
@tarurar somehow github escaped my comment in a weird way. I said, you seem to have missed the `*` in `*.js` in your settings. I only see `.js`

**Comment by tarurar** [comment]
Yes, you are right. Sorry. You can close the issue.
