### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'buffer' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#54132]
Issue Id: <b>be92cae4-edb3-36ca-143c-a9de2d6ce072</b><br /><br />*Versions* <br />- 1.25.0<br />-  33ba00346fd1bc889d5adc2f386c64fdb3657e61<br />-  6ca99aca80e80224f1c0bd4370c6ec4941c3bc54<br />-  923e9ccb3fc44bfaaf4b4049015c84e42bc40f95<br />-  26eb2a9af5827d71e1f65096c0ce712c5ad2740d<br />-  f2fa6bea46bde9856e6a593e4d4c5af2b303ac66<br />-  368ab9c31b5c0930a40ab3f0e0d768ebbeeb9ef8<br />-  5d6156a0f8b68fe7e9429facbcfaa7c061a8b3e3<br />-  499122702e462b458117122a6885e6aeb3cec0a4<br />-  f6a1888a2c87febeb8b03af0179bd46b63efb4e7<br />*Stack* <br />TypeError: Cannot read property 'buffer' of null<br />    at InputHandler.parse (\node_modules.asar\vscode-xterm\lib\InputHandler.js:183:36)<br />    at Terminal._innerWrite (\node_modules.asar\vscode-xterm\lib\Terminal.js:822:32)<br />    at \node_modules.asar\vscode-xterm\lib\Terminal.js:807:23<br />

**Comment by Tyriar** [comment]
This is easily reproducible by running `yes` and killing the terminal.

**Comment by octref** [comment]
@Tyriar I can't repro it in either Code 1.25.1 or Insiders, so maybe my method of reproducing is wrong.

What I'm doing is:

- Run `yes` in one terminal
- Kill that terminal
- No error is thrown

**Comment by Tyriar** [comment]
I verified it again just now
