### ISSUE TITLE
Allow debug config providers to resolve variables (like ${workspaceFolder})

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#54136]
This is a re-request of #49515 which I can't comment on now because it's locked.

I'd like to be able to resolve these tokens in my `resolveDebugConfiguration` method so that I can do some inspection of the application being launched (to launch the correct debug adapter). The [previous conclusion](https://github.com/Microsoft/vscode/issues/49515#issuecomment-387704670) was:

> I suggest that you work around that limitation on your side for now. The only variable that makes sense for `cwd` is `${workspaceFolder}` and you have access to its value.

So, that's what I did; but it turns out to be more complicated because I just got a bug from someone that has `${workspaceFolder:Example}` in their `program`.

To handle this, my simple replacement of `${file}` and `${workspaceFolder}` is going to turn into something much more complicated as I'm going to have to start duplicating (and maintaining) logic that's in Code.

(cc @weinand @isidorn)

**Comment by weinand** [comment]
We've introduced a new hook resolveDebugConfigurationWithSubstitutedVariables that receives the debug configuration with all variables resolved. See #87450.
