### ISSUE TITLE
Tasks: Emit a warning when a taskProvider is registered without a task definition

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#54138]
(verifying #53960)

When an extension registers a TaskProvider and there is no corresponding TaskDefinition in the package.json then I suggest to emit a warning in the console.

**Comment by dbaeumer** [comment]
This is already in (only on insiders since it was a bigger change). Code is here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostTask.ts#L875

Closing
