### ISSUE TITLE
Show a line where max-line-length ends

### ISSUE THREAD

**Issue by muuvmuuv** [Microsoft/vscode#54137]
In Atom editor, there was a function to enable a 30% transparent line at the max-line-length of the editor. I think that would be very useful when typing markdown or scripts too, to prevent beautifiers automated line wrap.

**Comment by 6A** [comment]
You can use `editor.rulers` for this purpose. See [this StackOverflow](https://stackoverflow.com/questions/29968499/) question for more informations.

## TL;DR
Add a vertical line at the 80th character with this code:
```json
    "editor.rulers": [ 80 ]
```

**Comment by muuvmuuv** [comment]
Awesome, thanks!
