### ISSUE TITLE
Extension section is empty after reload

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#54133]
Open the new settings editor. Notice that the Extension section has children:
![image](https://user-images.githubusercontent.com/172399/42618050-1a4fb030-85b4-11e8-854d-1d211725b16f.png)

Reload the window. Notice that the Extension section is empty
![image](https://user-images.githubusercontent.com/172399/42617976-e6909c46-85b3-11e8-9af5-3fa3bbfe1965.png)

When closing and reopening the settings editor then the Extension section appears correctly again.

**Comment by roblourens** [comment]
This actually happens in the old settings editor sometimes too.
