### ISSUE TITLE
New Settings Editor: links are difficult to see

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#54130]
Links are difficult to see when using a dark theme

![image](https://user-images.githubusercontent.com/172399/42617003-7efd0fc2-85b0-11e8-9b4b-8be507a50013.png)

**Comment by roblourens** [comment]
This is fixed in today's build, you might have had yesterday's. Should now be the same link color as elsewhere.

![image](https://user-images.githubusercontent.com/323878/42649015-548a9c34-85bd-11e8-9908-d03f0270fd00.png)
