### ISSUE TITLE
Doesn't load files correctly

### ISSUE THREAD

**Issue by AMetnik** [Microsoft/vscode#54144]
Issue Type: <b>Bug</b>

It's not a bug that will be easy to recreate since it does not appear systematically.

But sometimes, we have an issue, when reloading/loading a folder, that it doesn't read the files as files. But reads them as a folder.

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.63GB (7.33GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-lombok|Gab|0.9.4
Angular2|joh|6.1.1
mssql|ms-|1.4.0
RPG|Nie|0.1.1
java|red|0.28.0
vscode-java-debug|vsc|0.10.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.7.1
vscode-maven|vsc|0.9.2

</details>

**Comment by Tyriar** [comment]
@AMetnik what does it mean that a file is read as a folder? Can you provide any better repro steps?

**Comment by bpasero** [comment]
Weird, when this happens again, can you try to install node.js and just run a fs.statSync at such a path to see if node tells this is a folder?

**Comment by AMetnik** [comment]
![skaermbillede 2018-08-03 09 34 54](https://user-images.githubusercontent.com/2640098/43630441-a33b999c-9700-11e8-876b-f06090e258dd.png)
![skaermbillede 2018-08-03 09 35 00](https://user-images.githubusercontent.com/2640098/43630442-a35bfed0-9700-11e8-9598-f8fcf8d69e85.png)
So here is pictures, when i've opened folder, and the picture which is showing them as files is after I've pressed the reload button.

Which command do you wish me to run in node, please be specific, since I'm not good at it.
