### ISSUE TITLE
Cursor position wrong when rendering whitespaces

### ISSUE THREAD

**Issue by idleherb** [Microsoft/vscode#54146]
Issue Type: <b>Bug</b>

When using the 

`"editor.renderWhitespace": "all"`

option, the cursor position is slightly wrong. It's just a few pixels, but sometimes it blinks directly over a character making it hard to work. 

VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:30:30.113Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-table-formatter|jos|0.2.3
markdown-all-in-one|yzh|1.5.1

</details>

**Comment by Tyriar** [comment]
Can you post a screenshot of the bad positioning?

**Comment by idleherb** [comment]
@Tyriar sure, here: 
![cursor_problem](https://user-images.githubusercontent.com/3649482/42637668-10a9838e-85ec-11e8-9a69-0b6d00f1da33.png)

I meanwhile figured that for my case it happens when I use certain characters, like `*` with a tab between them. The problem is shown in the screenshot, I didn't investigate it with other combinations.

**Comment by dbaeumer** [comment]
@alexandrudima verified on Windows. Please `unverify` if this was OS dependent.

**Comment by alexandrudima** [comment]
Thank you!

I would also like to get this checked on macOS (with the default font we ship with)

**Comment by misolori** [comment]
Verified on macOS with our default font

![image](https://user-images.githubusercontent.com/35271042/44878625-31f66480-ac5c-11e8-8317-ab9defff14ed.png)
