### ISSUE TITLE
Settings editor: provide context menu actions

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#54140]
It would be great to have a few context menu actions on the settings editor:

- Copy setting to clipboard (including key and value)
- Set to default

**Comment by roblourens** [comment]
Here is Miguel's mockup for where a context menu action might go:

![gif](https://user-images.githubusercontent.com/35271042/43794148-47b648d0-9a32-11e8-8c04-bd9e850e9701.gif)

**Comment by roblourens** [comment]
I like this, but I'm also kind of inclined to put it in a consistent spot for every setting (regardless of how wide the control is). Other options I can think of are

- Below the control - but then it looks like the old expansion indicator
- Next to the label - but there's already a lot going on, in that row
- Right justified - but nothing in the setting is right-justified
- Left of the control - but a '...' looks wrong to the left of something, it should to the right. ("There is more...")

The right-justified option makes me think of Slack

![image](https://user-images.githubusercontent.com/323878/44061827-cc40499e-9f0e-11e8-9b3a-4d5ba167b7da.png)

They also have it on the right, when nothing else is right-justified. They also show that subtle hover color to tie it together.

**Comment by misolori** [comment]
Yea, I agree with your points.

One idea (not sure how I feel about it) is to move it to the left as it's the only consistent place it can go, and maybe use an alternative icon (unsure of what that could be).

![image](https://user-images.githubusercontent.com/35271042/44062599-e1930d88-9f11-11e8-847d-a63b923745d6.png)

![image](https://user-images.githubusercontent.com/35271042/44062605-e7bff130-9f11-11e8-81da-36c4b3302724.png)

**Comment by roblourens** [comment]
I like that but I think that we should stick with `...` for a dropdown. It might not be that bad on the left though.

**Comment by roblourens** [comment]
Had to use shift+f9 for the keyboard shortcut because shift+f10 still needs to show the context menu for input elements.
