### ISSUE TITLE
UI overlay bug

### ISSUE THREAD

**Issue by FernandoMiguel** [Microsoft/vscode#54142]
Issue Type: <b>Bug</b>

the side bar icons overlay the window control icons

![screenshot 2018-07-12 09 33 42](https://user-images.githubusercontent.com/168366/42621856-d59f7c42-85b6-11e8-82c6-869889ae75f2.png)

VS Code version: Code - Insiders 1.26.0-insider (a56ec40e8abf5579674894fb12b526956f048dc7, 2018-07-12T05:11:18.814Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
spellright|ban|2.5.16
better-toml|bun|0.3.2
githistory|don|0.4.1
github-pr|jas|1.0.0
mdhelper|jos|0.0.11
vscode-github|Kni|0.30.0
pasteurl|kuk|0.4.0
terraform|mau|1.2.3
prettify-json|moh|0.0.3
python|ms-|2018.6.0
docker-compose|p1c|0.2.3
vscode-docker|Pet|0.0.27
vscode-nginx|sha|0.5.0

</details>

**Comment by bpasero** [comment]
@FernandoMiguel any steps how to reproduce that?

**Comment by FernandoMiguel** [comment]
@bpasero i restarted Code to update to the latest version and when it open, i saw that.
if i switch to full desktop and back to Desktop mode, i can see it moving down .
but when it 1st started , it showed as in the screenshot

**Comment by bpasero** [comment]
Looks like https://github.com/Microsoft/vscode/issues/41691

I could never find out what the cause is though :-(
