### ISSUE TITLE
cannot push code to github with lint error

### ISSUE THREAD

**Issue by wdajun** [Microsoft/vscode#54143]
After update vscode version to 1.25.0, I cannot push my local Angular 6 code changes on to github. There is an popup window shows "Cannot push refs to remote. Trying running 'Pull' first to integrate your changes". I've also checked the git output console, and following is the log message:

> git push origin master:master
Lint errors found in the listed files.
error: failed to push some refs to 'xxxx@xxxxx'

I've not installed any extension except Angular 6 Snippets, and there is also no TS/ES lint configuration on Settings.

- VSCode Version: 1.25.0
- OS Version: Windows 10

Could anybody provided with some solutions? Thanks in advance~

**Comment by joaomoreno** [comment]
You seem to have a `pre-push` git hook set up. Can you push using the command line?

**Comment by wdajun** [comment]
Thanks for your quick response~
The project code has just new cloned,  I just tried with your suggestion with cmd: git push origin master:master. The console shows may lint error with TS files, following log is some some part of them:

.......
ERROR: C:/admin/src/app/pages/scheduler/scheduler.module.ts[4, 25]: 'ToasterService' is declared but its value is never read.
ERROR: C:/admin/src/app/pages/scheduler/scheduler.module.ts[4, 25]: 'ToasterService' is declared but its value is never read.
ERROR: C:/admin/src/app/pages/scheduler/scheduler.module.ts[4, 25]: 'ToasterService' is declared but its value is never read.
......

Lint errors found in the listed files.

All files pass linting.

> husky - pre-push hook failed (add --no-verify to bypass)
> husky - to debug, use 'npm run prepush'
error: failed to push some refs to 'xxxxx@xxxxxxx'

Any idea please let me know. Thanks~

**Comment by joaomoreno** [comment]
Can you push from the command line?

**Comment by wdajun** [comment]
I used command line (git push origin master:master) inside terminal of VSCode, it seems it still execute lint checking before push.
Now I've fixed the issues of TS lint checklist, and still, there are some sass lint not passed.

Is there some way that I can close the lint checking action for both TS & SASS when I use git in VSCode?

**Comment by wdajun** [comment]
I find there is 1 package named 'husky' in package.json, it is the root cause of  the 'pre-push' and make the lint worked in progress of pushing. After I npm unistall it from my project, I can push my code to github now. Thanks for your support~
