### ISSUE TITLE
File rename or move not done through source control provider

### ISSUE THREAD

**Issue by pbricout** [Microsoft/vscode#54153]
**Versions:**
- VSCode Version:
  Version: 1.25.0
  Commit: 0f080e5267e829de46638128001aeb7ca2d6d50e
  Date: 2018-07-05T13:11:58.697Z
  Electron: 1.7.12
  Chrome: 58.0.3029.110
  Node.js: 7.9.0
  V8: 5.8.283.38
  Architecture: x64
- OS Version: Windows 7 - 64 bit

**Steps to Reproduce:**

1. Open a project having a source control like git
2. Ensure this project have at least one file commited in the history
3. Open the file explorer side panel
4. Rename the file
5. Open the source control side panel

**Result:**

The file appears as deleted + added, instead of being renamed.
Any file under source control should be renamed or moved through the source control provider.
For example doing a `git mv oldname newname` shows the file has been correctly renamed under the source control side panel. This allows the source control provider can to track the file changes correctly instead of breaking the history.

Similarly, when renaming a file in the integrated shell through a source control provider, for example `git mv oldname newname`, the editor does not track the change correctly and if the file was opened, it shows as the file as `deleted from disk`, rather than using the new name.
Let me know you prefer a separate issue for this one.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/53449
