### ISSUE TITLE
No Definition found error for version 1.25.0

### ISSUE THREAD

**Issue by dineshguntha** [Microsoft/vscode#54150]
![image](https://user-images.githubusercontent.com/30077888/42625885-7dff933e-85e6-11e8-9775-e26090b8b5f5.png)

On Refernce class click on method or F12 then No Definition found is displying. I was working on old version. I is not working in new version update

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code build](https://code.visualstudio.com/insiders/) with all extensions disabled?

If you still see the issue on insiders, please share a small, complete code example
