### ISSUE TITLE
Menu should expose hover background/foreground colors

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#54157]
Currently there is only `menubar.selectionBackground` which is used for both hover and selection states. There should be independent colors for the hover state.

**Comment by bpasero** [comment]
We had this discussion already and think that hover/selection should be the same for the menu, since that is what native menus seem to do.

**Comment by joaomoreno** [comment]
Again... maybe on Windows, but definitely not on Linux.

**Comment by bpasero** [comment]
@joaomoreno maybe with a theme, my Ubuntu 18 out of the box does not distinguish between an item that is hovered vs. active vs. selected.

**Comment by sbatten** [comment]
We won't be distinguishing hover and selected so I am closing this issue. However the mouse down state is still open in #54170
