### ISSUE TITLE
Editor is not responding to clicks after it has been snapped to the corner, and then expanded to full window height.

### ISSUE THREAD

**Issue by constact** [Microsoft/vscode#5415]
- VSCode Version: 1.0.0
- OS Version: Windows 10

Steps to Reproduce:

1. Snap editor to the top-left corner.
2. Drag bottom border of the editor, so it snaps to the taskbar.
3. Try entering text to the editor or navigating through files.

**Comment by CubicsRube** [comment]
My bad! It happens with Chrome as well, not just VSC. Probably something to do with the rendering engine.

**Comment by bpasero** [comment]
I am closing this because I believe this is fixed, otherwise please report back. If you can reproduce I would appreciate if you could try to reproduce with our insiders build: 
You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders
