### ISSUE TITLE
If VS Code window size is reduced, keyword definitions pop up and obscure code

### ISSUE THREAD

**Issue by j-a-lewis** [Microsoft/vscode#54154]
Issue Type: <b>Bug</b>

I'm typing along line of Python code in VS Code, my mouse cursor probably rests on a keyword like "range" or "pd.DataFrame," and a big ol' definition, along with arguments, explanations, etc., pops up.  This could be very helpful BUT because I have the size of the window to reduced to look at other stuff on my screen, like a Juypter Notebook with code I'm trying to imitate de novo by programming on my own, the "HELP" screen for the keyword is very annoying and doesn't easily go away.  Please stop throwing up unwanted instructions.  Just like the autocapitalize "hint" in Office or same for autocomplete where you can tell the damn bot to stop doing what it's doing, make it easy to turn on/turn off HELP when you actually want it or conversely don't need it, rather than cramming it down your users throats.

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5 CPU       M 430  @ 2.27GHz (4 x 2261)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.68GB (3.96GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.33
anaconda-extension-pack|ms-|1.0.0
python|ms-|2018.6.0
vscode-yaml|red|0.0.13

</details>

**Comment by Tyriar** [comment]
@ramya-rao-a might know how to disable this?

**Comment by ramya-rao-a** [comment]
@j-a-lewis Can you please share a screenshot where you can show us the problem? Its not clear if we are talking about the suggest widget or the parameter hint widget. The screenshot will also help in seeing what editor width you are working with.

**Comment by j-a-lewis** [comment]
Thanks for your help.  Below is a screenshot of the sort of pop-up that blocks the view.  Today the pop-up is behaving better (after July Patch Tuesday??).  When I move the mouse cursor, it promptly goes away.  In the past, once the pop-up occurred, it was hard to make it go away.


Basically, I would like to have more control over when and where this pop-up occurs, rather than having it happen automatically, whether I want it or not.  And perhaps it is already controllable if one digs into Settings.  OTH, as I mentioned, for autocapitalization, autocorrect/autocomplete, MS Office offers little controls that appear near the involved area of the screen that offer the user an immediate and direct choice to control the behavior of these Office features.  I realize if such "AI" were included in VS Code, it might bloat the IDE and it would no longer be the spritely programming interface it is.  Just saying the pop-up at times is more of an annoyance than a help.  I would rather have a separate "help" window that I could float somewhere else on the overall screen away from the coding window and other stuff that I want to see.  Sorry if my basic problem is ignorance of VS Code, which I am just starting to use to learn Python.


[cid:01155eed-28a5-4cb0-b43d-ebd95c7e4db7]


Jim Lewis




________________________________

**Comment by ramya-rao-a** [comment]
@j-a-lewis I dont see your screenshot, and am still not sure if you are referring to the parameter hint widget or the suggest widget....

**Comment by j-a-lewis** [comment]
I guess we can credit Microsoft software for the lack of an included image on your end.  I added the image an INLINE photo in Outlook.com.  The image shows up in the SENT copy of my reply to you both in Outlook.com in MS Edge in Windows 10 and in the Microsoft Outlook app for Android.  So I am resending the image as an attachment, rather than an inline HTML image.


Apparently, the pop-up windows is the parameter hint window as I had the cursor resent on matplotlib and the pop-up window is a discussion of matplotlib that fills the window space, obscuring code.  I did not include the only computer screen (it's a 27-inch monitor), only the reduced VS Code window in which the pop-up obscures all the code.  If you want the entire screen image, let me know.


Jim Lewis


________________________________

**Comment by j-a-lewis** [comment]
Should be "I added the image AS an inline photo in Outlook.com...."


and "I did not include the WHOLE computer screen (it's a 27-inch monitor), only the reduced VS Code window ….."


________________________________

**Comment by j-a-lewis** [comment]
I just got the Visual Studio Code v1.25.1 update and that has HOVER display options for the editor.  Haven't experimented with hover delay but just the two following settings installed into my User settings work nicely for me:


    "editor.hover.enabled": true,
    "editor.hover.sticky": false,


So if I leave the cursor on the keyword, I quickly get help.  If I move the cursor anywhere, even over the pop-up, the help, which was blocking my view of the code, quickly goes away.  Perhaps my problem initially was the pop-up was so large relatively to the reduced size of the overall VS Code window that I never moved my mouse cursor outside of the pop-up window.  Hence, I thought the HELP wouldn't go away.

Thanks for the editor.hover options.

Jim Lewis

________________________________

**Comment by ramya-rao-a** [comment]
Am glad this got resolved for you in the latest version of VS Code.

Regarding the image problems, I have been viewing this issue in github in the browser. So the issue must be the way github reads your email replies.

Regardless, Happy Coding!
