### ISSUE TITLE
 Random invisible code

### ISSUE THREAD

**Issue by Maartenb111** [Microsoft/vscode#54160]
Issue Type: <b>Bug</b>

1 Create a new html file
2 Use boilerplate html (or start plain)
3 Begin adding html elements and code
4 View your file in a browser and keep on editing within VCS until you see random bits of code appearing on random places in your website
The random placed code seems to be parts of code written in your html file (use browser inspector).
5 Check the code in VCS and compare with browser inspector code. You will see differences.

Note: changing the filename within VCS makes the random code visable. Deleting it however doesn't solve the issue.

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:02:28.333Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.23GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by Tyriar** [comment]
Can you provide a screenshot of what you're seeing and point out the bad parts?

**Comment by Maartenb111** [comment]
Thanks for your reply. I've added sceenshots. You can see that after the closing html tag there is something added (l>/html>) which is not visable within VSC (and not added by me).

![schermafbeelding 2018-07-13 om 23 34 49](https://user-images.githubusercontent.com/18197337/42715052-8584c31c-86f5-11e8-9004-6189ea22f734.png)
![schermafbeelding 2018-07-13 om 23 34 36](https://user-images.githubusercontent.com/18197337/42715054-85a59b82-86f5-11e8-9481-02b30866aba5.png)
![schermafbeelding 2018-07-13 om 23 34 28](https://user-images.githubusercontent.com/18197337/42715055-85c3fd70-86f5-11e8-9486-f77beebbb5d6.png)

**Comment by aeschli** [comment]
If you still have that resource, can you zip it and attach it here?
