### ISSUE TITLE
TSLint Language Server is broken starting from 1.25.0

### ISSUE THREAD

**Issue by lingz** [Microsoft/vscode#54164]
- VSCode Version: 1.25.0
- OS Version: Mac OS Sierra 10.12.6

Steps to Reproduce:

1. Install tslint-language-service
2. Open a file with linting errors
3. Notice the linting errors show up for a split second, and then dissapear
4. Reproduce in 1.24.0 and notice it works

Issue also noticed here:
https://github.com/angelozerr/tslint-language-service/issues/76

**Comment by vilic** [comment]
@mjbvz Hi, please revisit this issue. `tslint-language-service` is not an extension but a plugin of typescript.
