### ISSUE TITLE
The integrated terminal scrollbar is hidden off screen

### ISSUE THREAD

**Issue by aveniri** [Microsoft/vscode#54178]
Issue Type: <b>Bug</b>

The terminal scrollbar and about 20px of text are hidden off screen. That is also the case when there are multiple terninals opened side by side.

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3667U CPU @ 2.00GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.70GB (1.10GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\airfind_repos\airfind-base|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.12
githistory|don|0.4.1
es7-react-js-snippets|dsz|1.8.3
gitlens|eam|8.4.1
vscode-npm-script|eg2|0.3.5
relativepathrefactor|jak|0.9.0
run-in-terminal|kor|0.0.1
contextualduplicate|laf|0.2.0
vscode-jade-snippets|mrm|1.0.1
sublime-keybindings|ms-|4.0.0
change-case|wma|1.0.0
html-css-class-completion|Zig|1.17.1

</details>
paste.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/51479
