### ISSUE TITLE
red lines in the first header file

### ISSUE THREAD

**Issue by SPK-RPI** [Microsoft/vscode#54172]
We have written the n
Issue Type: <b>Bug</b>

in c  as well as in c++ i am getting a red line at the bottom of the first header file thoe there are no errors...

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz (8 x 1995)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|5.95GB (2.72GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
flutter-snippets|ale|0.0.2
npm-intellisense|chr|1.3.0
ionic3-vs-ionView-snippets|dan|1.0.2
dart-code|Dar|2.15.0
flutter|Dar|2.15.0
vscode-eslint|dba|1.4.12
xml|Dot|2.3.1
tslint|eg2|1.0.33
vscode-npm-script|eg2|0.3.5
file-icons|fil|1.0.12
beautify|Hoo|1.3.2
trimspaces|igo|0.0.24
vsclassic-icon-theme|jez|1.1.0
vscode-clang|mit|0.2.2
python|ms-|2018.6.0
cpptools|ms-|0.17.6
debugger-for-chrome|msj|4.8.0
material-icon-theme|PKi|3.5.1
java|red|0.28.0
ionic3-snippets|sit|1.0.1
vscode-java-debug|vsc|0.10.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.7.1
vscode-maven|vsc|0.9.2

(3 theme extensions excluded)

</details>
eeded data into your clipboard because it was too large to send. Please paste.

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-cpptools
