### ISSUE TITLE
Menu: allow to theme active background/foreground when clicking menu item

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#54170]
Status bar items have three different states:

- Idle (`statusBar.background`)
- Hover (`statusBarItem.hoverBackground`)
- Active (`statusBarItem.activeBackground`, when mouse is pressing down)

It would be great to have the same for menu items.

**Comment by bpasero** [comment]
I think to begin with we should try to emulate what native windows menus do in terms of colors. We can add more styles later if we think that is needed.

**Comment by joaomoreno** [comment]
This is native emulation, at least on Linux: there's always an idle, hover and active distinct background colors.

**Comment by bpasero** [comment]
@joaomoreno maybe with a theme, my Ubuntu 18 out of the box does not distinguish between an item that is hovered vs. active vs. selected.

**Comment by joaomoreno** [comment]
Still, this issue is about themeing isn't it? Regardless, it is just good UX to provide the user a distinction between hover and active states.

We should aim to be good, not to clone bad.

**Comment by sbatten** [comment]
@joaomoreno this point will be moot when I change the mouse to alter keyboard focus as you mention in #54242 i.e. Hover === Active

**Comment by joaomoreno** [comment]
Active in this context means `mouse is being pressed over the item right now`:

1. Menu opens (idle state)
2. Mouse moves over item (hover state)
3. Mouse button is pressed & hold over the item (active state)

Much like this:

![peek 2018-07-17 10-36](https://user-images.githubusercontent.com/22350/42805882-4673ea8a-89ad-11e8-8f09-34388faac7c0.gif)

Again, (some) native menus might not provide this style, but it's just good UX.
