### ISSUE TITLE
I hope vscode can provide better auto-complete like eclipse

### ISSUE THREAD

**Issue by YuSuu** [Microsoft/vscode#5417]
- VSCode Version:1.0.0
- OS Version:Win 7 

im now writting some PHP code through a framework called Phalcon,
and VS-code cant have a good auto-complete on this,but on the other hand
with Eclipse , i can add the Phalcon source code to the "Included Path",
then Eclipse can provide a good auto-complete for it..

![qq 20160418013058](https://cloud.githubusercontent.com/assets/16498050/14588805/33b81e9a-0505-11e6-9280-0e93bd70373a.png)
![qq 20160418013103](https://cloud.githubusercontent.com/assets/16498050/14588806/33bb6e60-0505-11e6-8f8d-d62ed904bc9f.png)

Steps to Reproduce:
1. 
2.

**Comment by roblourens** [comment]
There are some extensions that provide this.
