### ISSUE TITLE
Cursor is lost when entering Zen mode

### ISSUE THREAD

**Issue by lane-s** [Microsoft/vscode#54175]
- VSCode Version: 1.25
- OS Version: OSX 10.12.5

Steps to Reproduce:

1. Open a file with VSCode
2. Navigate to a line
3. Enter Zen Mode

**Expected behavior**
The cursor should remain in place and be usable in Zen Mode without clicking the screen.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
I can not reproduce this, do you see this with latest vscode insiders?
Can you reproduce this issue if you simply go into full screen mode View > Toggle Full Screen?

**Comment by lane-s** [comment]
I'll test with the latest insiders. The issue does not occur when toggling full screen, only Zen mode.

**Comment by david-jares** [comment]
Have the same issue. Hotkey to Zenmode - Cool . But no cursor anywhere in my script. Have to grab  Mouse and click into the Script. its a pitty.

**Comment by longdeqidao** [comment]
- VSCode Version: 1.27.2
- OS Version: macOS High Sierra 10.13.6 

The same situation reproduced here. It's great if we fix it.

**Comment by itsmysterybox** [comment]
This was not the problem with Zen mode. It was the [Centered Layout](https://github.com/Microsoft/vscode/issues/61673). You can disable Center Layout in Zen mode in settings.

![zen](https://user-images.githubusercontent.com/43930682/47545614-d9191480-d90a-11e8-9701-4ad599c0c3d3.png)

Or add `"zenMode.centerLayout": false,` in User Settings.

Hopefully, cursor should be visible now in Zen mode. This [Centered Layout](https://github.com/Microsoft/vscode/issues/61673) bug is removed in latest VSCode Insiders.

- OS Version: Windows_NT x64 10.0.17134

**Comment by isidorn** [comment]
Appologies for people seeing the issue, I misunderstood the problem originally.
The point is -> this will be fixed in the next vscode stable release, and if you want it right now you can use vscode insiders

@itsmysterybox thanks for jumping in

**Comment by OrdinaryAspect** [comment]
Press F11. you'll exit the mode
