### ISSUE TITLE
${file} launch.json variable reference uses windows path in WSL

### ISSUE THREAD

**Issue by matt-best-elateral** [Microsoft/vscode#54179]
- VSCode Version:
1.26.0-insider
1.25.0
- OS Version:
Windows 10 v.1803

Steps to Reproduce:

1. Install node in WSL (Ubuntu)
2. Add a launch configuration to launch.json that includes a ${file} argument and useWSL:true:
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Tests",
      "program": "${workspaceFolder}\\node_modules\\ava\\profile.js",
      "args": [
          "${file}"
        ],
        "useWSL": true
    },
3.  This will launch the following command:
node --inspect-brk=46446 node_modules/ava/profile.js d:\git\my-service\test\unit\db.test.js
4.  The following error is reported:
Error: ENOENT: no such file or directory, open '/mnt/d/git/my-service/d:gitmy-servicetestunitdb.test.js'

The problem is that even with useWSL, the ${file} variable uses a windows path, whose '\' are then removed when attempting to create a file path.  In this the concatenated file path suffix becomes d:gitmy-servicetestunitdb.test.js.  If a the configuration contains an actual relative linux file path in place of the ${file} variable then the command has the correct file path and succeeds:

config:
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Tests 2",
      "program": "${workspaceRoot}/node_modules/ava/profile.js",
      "args": [
          "test/unit/db.test.js"
        ],
        "useWSL": true
    }, 

command:
     node --inspect-brk=27764 node_modules/ava/profile.js test/unit/db.test.js

P.S.  I think WSL + VS Code are great!  Thank you!

**Comment by Ciantic** [comment]
Same problem in tasks.json, if you use `"terminal.integrated.shell.windows": "C:\\Windows\\System32\\bash.exe"` or e.g.

```
        {
            "label": "My Task",
            "type": "shell",
            "command": "_runbuildtest.sh",
            "options": {
                "cwd": "${fileDirname}",
                "shell": {
                    "executable": "C:\\Windows\\System32\\bash.exe"
                }
            },
            "args": [
                "${file}"
            ],
            "problemMatcher": []
        }
```

**Comment by michaelharbour** [comment]
Hi there,  I'm just a programing hobbiest, but trying to use the WSL bash shell as my integrated terminal.  The only problem that I am having is that the paths that get passed to this terminal are starting with the drive (e.g. c:/) as opposed to /mnt/c/, which is what the terminal needs.  I'm trying to follow what you are reporting above to see if it is the same issue, and wondering if you know of anyway to configure VSC so that it begins paths with /mnt/c instead of c:

Thanks for your help

**Comment by n0v1** [comment]
@matt-best-elateral see https://github.com/Microsoft/vscode/issues/54593#issuecomment-431820312 (mocha example) for a possible workaround. I think you would have to use `${command:extension.vscode-wsl-workspaceFolder}/${relativeFile}` instead of `${file}` as your argument.

**Comment by matt-best-elateral** [comment]
Thank you n0v1.  I haven't had immediate success with this but will continue to try variations.

**Comment by Tyriar** [comment]
We just announced remote development with VS Code, check out the blog post for details https://code.visualstudio.com/blogs/2019/05/02/remote-development

**Comment by matt-best-elateral** [comment]
Thank you @Tyriar !
