### ISSUE TITLE
Suggest npm module name in commonjs require

### ISSUE THREAD

**Issue by AlexZeitler** [Microsoft/vscode#5418]
- VSCode Version: 1.0.0
- OS Version: Linux 3.19.0-58-generic #64~14.04.1-Ubuntu SMP Fri Mar 18 19:05:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1. Create a new Node.js project
2. `npm install express`
3. Create an `index.js`
4. Type `let e = require('` and hit `<ctrl><space>`

It would be nice if VS Code would now suggest `express` and any other npm module being installed but VS Code first only shows `Loading...` and after a few moments it shows `no suggestions`.

It also doesn't suggest the default Node modules like `path` or `fs` even if the `node` typings are installed.

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/TypeScript/issues/188
