### ISSUE TITLE
TypeScript types created from Pick<T> lose refactoring capabilities

### ISSUE THREAD

**Issue by jpattersonz** [Microsoft/vscode#54185]
Issue Type: <b>Bug</b>

The below example compiles correctly and results in a Properties type with just a `value: string` property, which Code recognizes just fine.

```typescript
class Base {
  name: string;
}

class Implementation extends Base {
  value: string;
}

type Properties = Pick<Implementation, Exclude<keyof Implementation, keyof Base>>;

const x: Properties = null;

x.value;
```

Attempting to 'Go to Definiton' on `x.value` will fail.

Using 'Rename Symbol' to rename Implementation.value to Implementation.value1 will rename the class property, but fail to rename `x.value` to `x.value1`.

To provide some context, I am using a library that forces me to inherit from a generic base class in order to use it's functionality.  I'd like to be able to work with the implementation classes specific properties without having to reason about the significant amount of extra methods and properties on the base class.  While I could define an interface and have my class both implement the interface and extend the base class, it would require duplication of code in order to define the properties both on the interface and on the class. Using `Pick<Implementation, Exclude<keyof Implementation, keyof Base>>` allows for me to define the properties just once.

I'm not sure if this is a VS code bug, a limitation in the TypeScript Language Service, or a mix of the two.  In my specific example, it's easy to reason about how the tooling should be able to support this.

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:02:28.333Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.89GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron --disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled

**Comment by andy-ms** [comment]
Created a TypeScript issue for this: Microsoft/TypeScript#25607

**Comment by PinkyJie** [comment]
I had a similar issue with `Pick<>`, I think it might be related to this one: Go to Definition feature is not working with a type after calling `Pick<>`.

``` typescript
type Actions = Pick<ActionCreators, 'a' | 'b' | 'c'>;
const actions:Actions;
```

Then if I try to use "Go to Definition" on `actions.a`, it can't navigate to the implementation of `ActionCreators` type.

**Comment by mjbvz** [comment]
Closing as upstream
