### ISSUE TITLE
C/C++ intellisense not working with FileSystemProvider filesystem

### ISSUE THREAD

**Issue by jdwieber** [Microsoft/vscode#54189]
- VSCode Version: 1.25.0
- OS Version: Windows 7 Enterprise

Steps to Reproduce:

1. install vscode-cpptools
2. install vscode-sshfs
3. configure c_cpp_properties.js includePath to use the ssh FileSystemProvider

vscode-sshfs works well for mounting remote directories, and editing files. However, intellisense fails to parse the files in these "mounted" directories. When I connect a remote directory as a workspace folder, I get an entry in my code-workspace setting that looks like this:

```
{
	"uri": "ssh://path_to_search/",
	"name": "SSH FS - itickers"
}

```
I added the folder to my c_cpp_properties.js like this:
```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}",
                "ssh://path_to_search/"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "intelliSenseMode": "clang-x64"
             "cStandard": "c11",
            "cppStandard": "c++17"
        }
    ],
    "version": 4
}
```

**Comment by jdwieber** [comment]
Thanks. I'll followup with the extension engineer.

Cheers!

**Comment by jinjiren** [comment]
It seems that the author of the extension thinks that this is an issue should be fixed in VS Code... https://github.com/SchoofsKelvin/vscode-sshfs/issues/27

**Comment by jrieken** [comment]
It's not an issue with the sshfs-extension but with the cpp-extension

**Comment by jdwieber** [comment]
A feature request is open to add support.
https://github.com/Microsoft/vscode-cpptools/issues/2268
