### ISSUE TITLE
Simplify API for updating settings

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#54183]
Today the API for modifying settings supports to target the different settings stores (user, workspace, folder). This is powerful but a bit laborious to use.

If you need to update a value in the store where it came from, you need to write code to figure out where it came from and then select the appropriate target value for passing it to `WorkspaceConfiguration.update`.

This results in something like this:
```
	const conf = vscode.workspace.getConfiguration('debug.node');
	const info = conf.inspect('autoAttach');
        const value = conf.get('autoAttach');
	let target: vscode.ConfigurationTarget = vscode.ConfigurationTarget.Global;
	if (info) {
		if (info.workspaceFolderValue) {
			target = vscode.ConfigurationTarget.WorkspaceFolder;
		} else if (info.workspaceValue) {
			target = vscode.ConfigurationTarget.Workspace;
		} else if (info.globalValue) {
			target = vscode.ConfigurationTarget.Global;
		} else if (info.defaultValue) {
			// setting not yet used: store setting in workspace
			if (vscode.workspace.workspaceFolders) {
				target = vscode.ConfigurationTarget.Workspace;
			}
		}
	}
	conf.update('autoAttach', !value, target);
```

I suggest that we simplify the API a bit.

Currently I see two approaches:

1. Add a new enum value `originalTarget` to the `ConfigurationTarget` type. With this a setting value can be toggled like this: 
```
    const conf = vscode.workspace.getConfiguration('debug.node');
    const value = conf.get('autoAttach');
    conf.update('autoAttach', !value, vscode.ConfigurationTarget.originalTarget);
```

2. Add a new attribute `effectiveTarget` to the structure returned from `WorkspaceConfiguration.inspect`. `effectiveTarget` would contain the target where the value came from. With this a setting value can be toggled like this: 
```
    const conf = vscode.workspace.getConfiguration('debug.node');
    const info = conf.inspect('autoAttach');
    const value = conf.get('autoAttach');
    conf.update('autoAttach', !value, info.effectiveTarget);
```

**Comment by sandy081** [comment]
I like the first approach of giving a different target value to update to specify an effective target. Getting from inspect might not be correct as if a setting is not defined only in default settings then it does not makes sense to return user target as effective target.
