### ISSUE TITLE
Integrated terminal workspace hard disk letter is lowercase

### ISSUE THREAD

**Issue by sharh** [Microsoft/vscode#54181]
Issue Type: <b>Bug</b>

When use `Open in Commander Prompt` on a directory, the hard dist letter is lowercase:

`d:\Node\vue-ssr>`

And install a nodejs package like:

```
d:\Node\vue-ssr\vue-hackernews-2.0>cnpm i axios --save
```
When import axios in the project
```javascript
import Vue from 'vue'
import axios from 'axios'
Vue.prototype.$axios = axios.create({})
```
This will cause some WARNING like:

```
WARNING in ./node_modules/_process@0.11.10@process/browser.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* D:\Node\vue-ssr\vue-hackernews-2.0\node_modules\_process@0.11.10@process\browser.js
    Used by 3 module(s), i. e.
    D:\Node\vue-ssr\vue-hackernews-2.0\node_modules\_setimmediate@1.0.5@setimmediate\setImmediate.js
* d:\Node\vue-ssr\vue-hackernews-2.0\node_modules\_process@0.11.10@process\browser.js
    Used by 1 module(s), i. e.
    d:\Node\vue-ssr\vue-hackernews-2.0\node_modules\_axios@0.18.0@axios\lib\defaults.js
 @ ./node_modules/_process@0.11.10@process/browser.js
 @ ./src/api/index.js
 @ ./src/store/actions.js
 @ ./src/store/index.js
 @ ./src/app.js
 @ ./src/entry-client.js
 @ multi webpack-hot-middleware/client ./src/entry-client.js
```

And when I install the package in `cmd` or `powershell`, this WARNING will disappear:

```
PS D:\Node\vue-ssr\vue-hackernews-2.0> cnpm i
/ [29/37] Installing uniq@^1.0.1platform unsupported chokidar@1.7.0 › fsevents@^1.0.0 Package require os(darwin) not compatible with your platform(win32)
[fsevents@^1.0.0] optional install error: Package require os(darwin) not compatible with your platform(win32)
√ Installed 37 packages
√ Linked 634 latest versions
√ Run 1 scripts
Recently updated (since 2018-07-05): 11 packages (detail see file D:\Node\vue-ssr\vue-hackernews-2.0\node_modules\.recently_updates.txt)
  Today:
    → css-loader@0.28.11 › postcss@5.2.18 › js-base64@^2.1.9(2.4.6) (12:41:56)
√ All packages installed (764 packages installed from npm registry, used 38s, speed 196.09kB/s, json 671(7.18MB), tarball 49.43kB)
PS D:\Node\vue-ssr\vue-hackernews-2.0> cnpm i axios
√ Installed 1 packages
√ Linked 0 latest versions
√ Run 0 scripts
√ All packages installed (used 220ms, speed 171.86kB/s, json 1(37.81kB), tarball 0B)
PS D:\Node\vue-ssr\vue-hackernews-2.0> npm run dev

> vue-hackernews-2.0@ dev D:\Node\vue-ssr\vue-hackernews-2.0
> node server

server started at localhost:8080


 DONE  Compiled successfully in 2452ms                                                                          22:39:21



 DONE  Compiled successfully in 3166ms                                                                          22:39:22

webpack built 408948bd003220a37cd6 in 3166ms


```

How can I change the `d:` to `D:` in vscode's terminal?

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (10.52GB free)|
|Process Argv|D:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (65)</summary>

Extension|Author (truncated)|Version
---|---|---
svgo|100|0.8.0
vscode-file-peek|abi|1.0.1
html-snippets|abu|0.2.1
aessoft-class-autocomplete|AES|0.1.0
color-info|bie|0.5.0
file-properties-viewer|bru|0.2.0
jsonviewer|cci|1.0.3
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
regex|chr|0.2.0
bracket-pair-colorizer|Coe|1.0.58
yaml-key-viewer|cyb|0.1.0
dart-code|Dar|2.15.0
app-migrator|deb|0.0.3
vscode-faker|dee|1.3.0
css-minify|Die|0.1.10
vscode-html-css|ecm|0.2.0
vscode-npm-script|eg2|0.3.4
we-app-vscode|eme|0.8.0
prettier-vscode|esb|1.5.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.3
terminal|for|0.0.10
gc-excelviewer|Gra|2.1.24
vscode-gitbuild|grz|1.0.1
vue-snippets|hol|0.1.8
beautify|Hoo|1.3.2
minify|Hoo|0.3.0
output-colorizer|IBM|0.1.2
path-autocomplete|ion|1.10.0
copy-filename|jac|1.0.2
docthis|joe|0.7.1
typings-autoinstaller|jvi|1.2.0
robotframework|kei|0.2.8
vscode-gutter-preview|kis|0.12.2
node-module-intellisense|lei|1.5.0
font-awesome-codes-html|med|0.0.7
HTMLHint|mka|0.5.0
vscode-filesize|mkx|2.1.0
binary-viewer|mom|0.0.1
sublime-keybindings|ms-|4.0.0
debugger-for-chrome|msj|4.7.0
vetur|oct|0.12.5
material-icon-theme|PKi|3.5.1
vscode-css-peek|pra|2.1.0
filenamecomplete|qin|0.0.3
minapp-vscode|qiu|1.6.1
Ruby|reb|0.18.0
vue-vscode-snippets|sdr|1.3.0
markdown-preview-enhanced|shd|0.3.5
html5-boilerplate|sid|1.0.3
indenticator|Sir|0.6.0
autoimport|ste|1.5.3
code-spell-checker|str|1.6.10
language-stylus|sys|1.9.2
open-in-browser|tec|1.1.0
nativescript|Tel|0.7.4
highlight-matching-tag|vin|0.4.4
vscode-java-pack|vsc|0.3.0
vscode-maven|vsc|0.9.0
quokka-vscode|Wal|1.0.132
vscode-todo-highlight|way|0.5.12
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.7.0

(2 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
I believe we set it to lower because of other issues that occur with node packages that have issues with the inverse problem. Maybe you could go to `C:` then `D:` to switch it?
