### ISSUE TITLE
Tabbar Feature Requests

### ISSUE THREAD

**Issue by XeonG** [Microsoft/vscode#54182]
Tabbar Feature Requests in order of importance...

1. Mousewheel support on the tabbar to quickly cycle back/forth between open tabs. Like to quickly compare multiple documents and cycle through open ones faster.. (*)
2. Allow tabs to go onto multiple tabbars and not off screen on a single tabbar.
3. More control over the tab styling sizes, layout, this might be possible but currenty the amount of wasted space with individual tab padding reduces the amount of visible filename text. (**)
4. Add an icon on the far right side of the tabbar to show a drop down of all tabbed documents (***) 
5. Put in the option to remove the tab close button (including the invisible  area it takes up on tabs that are not in view), this will free up more space for the filename text per tab.
6. Tab preivew showing a thumbnail of the opened document zoomed out, like the scrollmap with color, would be nice, or even better something like vivaldi's browser tabbar preview thumbnails.

*. Currently mousewheel support is for scrolling the tabbar, it is not very good and generally awful workflow. This mousewheel support should also work with a single tabbar, where the tabs go offscreen, instead of the tabs being shifted and mousewheel scrolling the tabbar only while not switching the active document... tabs that are selected by mousewheel that are offscreen should come into view.. add this functionality to a combo key [shift+mwheel+up/down]

**. Being able to adjust the min tab size and maximum size of the tab would really allow end users to squeeze as many tabbed documents on the tabbar with the amount of readable filename text that they want. With better styling and less pixel space wastage on padding sizes this could be improved even more.

***. This functionality is in a lot of webbrowser and also visual studio, is very useful for when the vscode sidebar is not showing the opened documents because it is closed or showing a different sidebar like extensions/search etc.. currently very annoying.

Here is a picture comparison of a few tabbars from various programs..... 

![Tabbars](https://i.imgur.com/Qbfd01Z.jpg)

1.Firefox (tweaked custom theme, pre-firefox quantun version garbage, was highly customizable and great before)

2.Notepad++ - screenshot of earlier version when the tabbar wasn't so messed up, showing a total of 39 documents!!..  this s is bare minimum vscode should support, why vscode has an awful user experience for the tabbar? While long established code editors like notepad++ have been out for a long time with far better support in this area.

3.Jetbrains Rider - Awful tab styling and waste of space styling, but at least supports multiple tabbars.

4.Vscode with it's fat padding bloated tabbar that barely shows around 9 open documents compared to notepad++ on the tabbar before going off the screen.. really rubbish design... and practically forces you to have the explorer sidebar bar opened losing even more screenspace in the code editor to have any sort usable workflow in hopping between documents..

**Comment by superheri** [comment]
One thing that could be nice too is to be able to pin tabs we always want to stay in the view like in Visual Studio 2017.

**Comment by bpasero** [comment]
Closing as per https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#writing-good-bug-reports-and-feature-requests

Also quite some feature requests have been asked for when you look at https://github.com/Microsoft/vscode/labels/workbench-tabs
