### ISSUE TITLE
Autoimport always imports relative paths

### ISSUE THREAD

**Issue by sharpcoder28** [Microsoft/vscode#54187]
With the June 1.25 version, imports now are full relative paths.

```
import { Observable } from '../../../../node_modules/rxjs';
```

I tried adding

`"typescript.preferences.importModuleSpecifier": "non-relative"`

which did not work.

**Comment by mjbvz** [comment]
Duplicate of #53597 

Fixed in VS Code insiders and if you upgrade to to use TypeScript 3.0 in your workspace (or downgrade to use TS 2.9.1)
