### ISSUE TITLE
Finding word

### ISSUE THREAD

**Issue by joshu111** [Microsoft/vscode#54199]
Issue Type: <b>Bug</b>

I was trying to find keyword "asset" in file first occurunce is highlighted with no problem. But, when try to go to next occurance it higlights the line but not column. It should scroll horizontaly when word is not in window.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (7.50GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
StarboundJson|Kyl|0.1.3

</details>

**Comment by rebornix** [comment]
![wordwrap-search](https://user-images.githubusercontent.com/876920/45063980-fac1f200-b065-11e8-971a-1d10652310bf.gif)

I can't reproduce this issue in latest version. Close for now and we can reopen it if you can still reproduce it.
