### ISSUE TITLE
Allow `tab.unfocusedActiveBackground` in `workbench.colorCustomizations`

### ISSUE THREAD

**Issue by kankaristo** [Microsoft/vscode#54197]
`workbench.colorCustomizations` allows you to define different colors for focused and unfocused active tabs, e.g. `tab.activeForeground` and `tab.unfocusedActiveForeground`.

Oddly, there's no unfocused variant of `tab.activeBackground` (i.e. `tab.unfocusedActiveBackground`).

I'd like to keep the "regular" background color for unfocused active tabs, but have a brighter color for the currently focused active tab background.

**Comment by bpasero** [comment]
Merging into https://github.com/Microsoft/vscode/issues/52862
