### ISSUE TITLE
System slowdown after screen turns off while in full-screen mode

### ISSUE THREAD

**Issue by pulzed** [Microsoft/vscode#54198]
Issue Type: <b>Performance Issue</b>

VSCode, when ran in full-screen, will make the whole system slow after Windows wakes up from screen sleep.

I am not sure if this is an issue isolated to my own machine or not, but I can reproduce this with 100% repeatability. I'm also not sure if it's an Electron issue, a VSCode issue, or something else going on with my system configuration. This is not a critical issue, just glitchy behavior that doesn't make much sense to me.

Steps to reproduce (I've only tested this on my own machine, but it happens every single time):

1. Run VSCode on my second monitor in full-screen mode (this only happens when in full-screen, I'm not sure if the 2nd monitor plays a role)
2. Let Windows turn off my monitors after a given delay (as configured under Power & sleep -> Screen in Windows Settings) - NOT sleep mode, just monitors turning off
3. After waking up the system (immediately after or after a long while, it doesn't matter), everything on my first monitor starts lagging severely (not VSCode but the entire system) - all context menus open with a delay, windows are frozen or repaint with a delay when moved, selecting text is laggy, etc. This whole time the second monitor remains black (not in sleep as the screen itself does wake up, it looks like VSCode is just rendering a black screen).
4. This behavior stops when the mouse enters the second monitor which contains VSCode or when VSCode gets focus via alt-tab. At this point VSCode shows up again, the entire system stops lagging and everything returns to normal.

Again it should be noted that this only happens when VSCode is left to run in full-screen.

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600X Six-Core Processor            (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (11.05GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
(14 theme extensions excluded)

**Comment by Tyriar** [comment]
While the lagginess is happening could you run `code --status` and paste in the process details here?

**Comment by pulzed** [comment]
Here's a screenshot after running code --status while the system is slowed down:

![codestatusdetails](https://user-images.githubusercontent.com/2159248/42782730-0b490476-894a-11e8-943d-78dee4e6de49.png)

Here's a screenshot after running the command immediately after VSCode wakes up and the system stops lagging (as mouse enters the blank screen) - almost exactly the same output:

![codestatusdetails2](https://user-images.githubusercontent.com/2159248/42783059-0e21a65c-894b-11e8-9b4f-8cf516de7261.png)

**Comment by pulzed** [comment]
It seems like it doesn't really matter which processes are running, the behavior is still there even if I have only VSCode running. This is a screenshot of the task manager while the system is slowed down (the CPU is pretty much idling this whole time):

![taskmanager_slowdown](https://user-images.githubusercontent.com/2159248/42910786-0fd33a52-8ae9-11e8-8e88-b8939ab5c43b.png)

**Comment by Tyriar** [comment]
Considering little CPU is being used that makes me believe this is an issue with Windows 😕 

@bpasero have you seen issues like this where Windows slows down after sleep and speeds up again when the mouse enters the monitor containing VS Code?

**Comment by bpasero** [comment]
The fact that VSCode renders as a black screen sounds like it was reported already before, but I am not so sure about the slowdown after wakeup.

@pulzed does it reproduce if only VSCode is running and no other app?

**Comment by pulzed** [comment]
@bpasero @Tyriar seems like the behavior changed for me for some reason. I can't reproduce the slow-down behavior anymore. I've been doing some quick tests and I've found that running VSCode in fullscreen on my 1st screen and waking from screen-sleep works as expected (nothing unusual to report), while running VSCode in fullscreen on my 2nd screen and waking from screen-sleep produces all-black 2nd screen until the mouse enters the area, but it doesn't slow-down the rest of the system anymore like it did before.

Is it possible this behavior is caused by my graphics driver?

**Comment by bpasero** [comment]
Yes possibly. Closing as it seems you resolved the issue.
