### ISSUE TITLE
Integrated terminal not rendering lines. 

### ISSUE THREAD

**Issue by kevgliss** [Microsoft/vscode#54195]
Issue Type: <b>Bug</b>

Update to v1.25 caused the integrated terminal to stop rendering lines correctly. Note this works as expected on 1.24.1 and iterm2. 

I have also disable all extensions. 

Expected (v1.24.1): 
![screen shot 2018-07-12 at 11 50 59 am](https://user-images.githubusercontent.com/2262214/42653552-a064ea58-85ca-11e8-8624-e219f664615a.png)

Actual (v1.25.0):
![screen shot 2018-07-12 at 11 57 34 am](https://user-images.githubusercontent.com/2262214/42653641-d31f409c-85ca-11e8-9e6e-40722fea4500.png)

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:02:28.333Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6287U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.66GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by Tyriar** [comment]
This is fixed in the latest insiders https://github.com/Microsoft/vscode/issues/53769, the fix will come in 1.26. In the meantime I recommend working around the problem with this setting:

```
"terminal.integrated.experimentalTextureCachingStrategy": "dynamic"
```
