### ISSUE TITLE
window.titleBarStyle: custom

### ISSUE THREAD

**Issue by mostafaabobakr7** [Microsoft/vscode#54209]
- VSCode Version: 1.25.1
- OS Version: win10 x64

### "window.titleBarStyle": "custom"
**The _first item_ in all menus are always _highlighted_**
![2018-07-12_232736](https://user-images.githubusercontent.com/27288406/42660890-bfc207b6-862c-11e8-922c-25bd909d29b5.png)
![2018-07-12_232749](https://user-images.githubusercontent.com/27288406/42660891-bfe7672c-862c-11e8-857c-664afec699a2.png)

**Comment by sbatten** [comment]
tracking in #52933
