### ISSUE TITLE
Custom Browser to open editor links

### ISSUE THREAD

**Issue by wellington1993** [Microsoft/vscode#54201]
Hi,

I need to change the path off browser binary.

Change the primary browser used to open editor links, 
like change change log, update, help, extension links or other interface links.

I'm being using a custom compiled locally version of Firefox Nightly and
when I try to open links the editor call to open the system default browser.

I want to change the default response of editor to open links in my customized 
browser path and parameter.

Should be useful to Web Developers too.

Thanks.

**Comment by TomasHubelbauer** [comment]
Could you instead do this on system level by setting your build of FF nightly as your OS's default? I don't feel like this should be a VS Code settings personally, but maybe there is a case to be made for it.

**Comment by wellington1993** [comment]
@TomasHubelbauer maybe system config help, but in this case two items still missing: the custom parameters to the browser and the use of not installed software.

An alternative it's allow to copy and paste links from add-ons dialogs and interface links, like changelog and others. Because these link don't have copy option.

Having the link I can open anywhere. 

In this case I have two suggestion instead the original:
- Config to set custom browser and parameters to open all interface links and
- Config to copy links from the IDE interface with mouse right click.

I think can't make a PR for this in this moment because I'm not familiarized with vscode source enough.
 
Thanks!

**Comment by wellington1993** [comment]
@TomasHubelbauer maybe system config help, but in this case two items still missing: the custom parameters to the browser and the use of not installed software.

An alternative it's allow to copy and paste links from add-ons dialogs and interface links, like changelog and others. Because these link don't have copy option.

Having the link I can open anywhere. 

In this case I have two suggestion instead the original:
- Config to set custom browser and parameters to open all interface links and
- Config to copy links from the IDE interface with mouse right click.

I think can't make a PR for this in this moment because I'm not familiarized with vscode source enough.
 
Thanks!

**Comment by TomasHubelbauer** [comment]
Your point about copying links by mouse clicking should be a separate issue and there may already be some for this behavior, so please use search in case there really are, before creating a new one.

As far as sending custom parameters goes, there is another option you could try and that is to set system browser to a BAT/SH script and have that script run the browser for you with the extra arguments you require. This being a system setting would affect all software and not just VS Code, but then again I don't think VS Code is likely to gain support for on top of opening a separate non-system browser to send arguments to it.

Should the arguments be based on the links context or just a general set of extra arguments which do not depend on the link?

**Comment by wellington1993** [comment]
@TomasHubelbauer Thanks for the fast response.

I don't opened copy and paste issue because I had think the new config of browser path and parameters can be useful to other users, but If anyone like the idea I can survive with copy and paste alternative, I will find this issue to follow...

In my case independently of the link, just general set of extra arguments like you said.

Regards.

**Comment by TomasHubelbauer** [comment]
If that't the case please consider settings your system's default browser to a script which will start the browser with those arguments, instead of having VS Code invoke it that way. Maybe that will work for your use case if you are not bothered by the fact that other applications will also start the browser with those arguments.

**Comment by wellington1993** [comment]
@TomasHubelbauer Thanks. In this case I will close this issue.
If anyone find same motivations can be found this issue and re-open.

Regards.
