### ISSUE TITLE
Emmet settings and other features

### ISSUE THREAD

**Issue by nicothin** [Microsoft/vscode#5420]
- VSCode Version: 1.0.0
- OS Version: Win10 64

Emmet has many hot [keys](http://docs.emmet.io/actions/), [filters](http://docs.emmet.io/filters/), [settings](http://docs.emmet.io/customization/preferences/)
I want to customize this tool. But now there is only the abbreviation :(

**Comment by alphashuro** [comment]
Wrap with abbreviation is missing as well :broken_heart:

**Comment by Spinarooni** [comment]
I agree.  Perhaps this should have been integrated as an extension like most of the other editors that can use Emmet.

**Comment by egamma** [comment]
Support for wrapping an abbreviation is now tracked in #7800 

@Spinarooni fully agreed that emmet should be a full extension, we have added emmet support before we had the extension model in place. This is a debt item we have on our backlog.

**Comment by egamma** [comment]
Added support for settings thanks to PR #7926.
