### ISSUE TITLE
Git Stash Apply

### ISSUE THREAD

**Issue by lvl99** [Microsoft/vscode#54204]
I've attempted to find any other requests for this but didn't seem to see any.

At the moment the CVS context menu shows:
![image](https://user-images.githubusercontent.com/238480/42658519-dd031a4c-8625-11e8-9eaf-1815fed537b6.png)

Only "Pop latest stash" and "Pop stash..." are visible.

Is it possible to change the default stash behaviour to "apply" rather than "pop"? Additionally, is it possible to add two lines under "Pop stash..." for the same actions, just using apply:
 * Apply latest stash
 * Apply stash...

I just lost a few hours and considerable amount of hair when a popped stash was deleted. I then had to sift through `git fsck --lost-found` doing `git show <shahash>` on each `dangling commit <shahash>`. Having "Apply stash..." easily accessible might be nicer.

**Comment by joaomoreno** [comment]
I suggest to simply add `Apply Latest Stash` and `Apply Stash...` commands.

**Comment by lvl99** [comment]
@sa-adebayo looks like it might already be done in #54300

**Comment by sa-adebayo** [comment]
@lvl99 yeah, just confirmed, Thanks. If I may ask, is there any rule around tagging an issue that is being worked on as it would be multiple efforts if I happen to have started it without anyone's knowledge.
I've been scouting for an issue with no assignee to work on :-(
Thanks for the catch tho!

**Comment by joaomoreno** [comment]
Closed by #54300
