### ISSUE TITLE
Prevent GettingStarted part from triggering during firstime workstation startups.

### ISSUE THREAD

**Issue by beeblebrox** [Microsoft/vscode#54205]
My use case is that I do not want first time ran workspaces to pop up the web browser with the docs website and I don't want the telemetry prompt.  This is so we can use visual code in docker containers or other quick workstation deployments for developers without the popups every time the container is recreated.

I think the simplest way to do this would be to make the 'workbench.hide.welcome' GettingStarted part localstorage property to become a settable settings.json property. It is pretty easy to deploy the settings.json file before first time startup.  Another option would be to allow for a command line argument to prevent it.

There is currently not a satisfactory workaround that I have found. Suggestions are welcome.

**Comment by joaomoreno** [comment]
The command line is `--skip-getting-started`.
