### ISSUE TITLE
Powershell command-line parameters very difficult to read in dark themes

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode#54207]
Issue Type: <b>Bug</b>

Powershell command-line parameters very difficult to read in dark themes

E.g. I'm using "Tomorrow Night Blue", but it repros in the other dark themes I tried.  Here's an example:

![image](https://user-images.githubusercontent.com/6913354/42660233-6165d32a-85df-11e8-96cc-87b1073a8517.png)
![image](https://user-images.githubusercontent.com/6913354/42660269-7fd30e18-85df-11e8-80c1-16e77c26f838.png)

The "-f", "-t" and "-" strings are extremely difficult to see.

Thx.

VS Code version: Code - Insiders 1.26.0-insider (bd953248ad6a8e2f8896bfb78b3ae40e0fd47426, 2018-07-06T05:17:37.386Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E31230 @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.96GB (5.79GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe C:\Repos\vscode-docker|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.18.0
vscode-eslint|dba|1.4.12
tslint|eg2|1.0.33
rest-client|hum|0.19.0
csharpfixformat|Leo|0.0.72
vscode-mocha-sidebar|mat|0.20.12
vscode-antlr4|mik|2.0.3
vscode-azureappservice|ms-|0.8.1
vscode-azurefunctions|ms-|0.9.1
vscode-azurestorage|ms-|0.4.0
vscode-azureterraform|ms-|0.2.0
vscode-cosmosdb|ms-|0.8.0
vscode-language-pack-de|MS-|1.25.2
vscode-kubernetes-tools|ms-|0.1.11
mssql|ms-|1.4.0
vscode-ai|ms-|0.1.9
azure-account|ms-|0.4.1
azurecli|ms-|0.4.2
azurerm-vscode-tools|msa|0.4.2
azure-hdinsight|msh|0.0.16
vscode-docker|Pet|0.0.27
vscode-yaml|red|0.0.13
usql-vscode-ext|usq|0.2.14
azure-iot-edge|vsc|1.0.0
azure-iot-toolkit|vsc|1.0.0

</details>

**Comment by Tyriar** [comment]
@tylerl0706 it looks like the characters are being drawn as black or inverse, any idea how to get around this?

**Comment by tylerl0706** [comment]
This is due to [PSReadLine](https://github.com/lzybkr/PSReadLine) which ships in PowerShell. To work around this you can set that dark gray to another color.

What version of PSReadLine do you have?
```powershell
gmo PSReadLine
# or
Get-Module PSReadLine
```

##### if you're on 2.0.0, you can set the color by running:
```powershell
Set-PSReadLineOption -Colors @{
    # Use a ConsoleColor enum
    "Error" = [ConsoleColor]::DarkRed

    # 24 bit color escape sequence
    "String" = "$([char]0x1b)[38;5;100m"

    # RGB value
    "Command" = "#8181f7"
}
```
In your case, you're going to want to update `Parameter` so:

```powershell
Set-PSReadLineOption -Colors @{
    "Parameter" = [ConsoleColor]::DarkRed
}
```

If you're on an older version... I think the call is:

```powershell
Set-PSReadLineOption -ParameterColor [ConsoleColor]::DarkRed
```

You might need to add this to your profile to get it to persist.
