### ISSUE TITLE
Syntax highlighting for YAML literal scalars shows errors for otherwise invalid strings

### ISSUE THREAD

**Issue by heaths** [Microsoft/vscode#54219]
Issue Type: <b>Bug</b>

When editing YAML - such as .vsts-ci.yml files, it's not uncommon to use a literal scalar like so:

```yaml
testAssemblyVer2: |
  **\$(BuildConfiguration)\*mocks*.dll
  **\$(BuildConfiguration)\*test*.dll
  **\$(BuildConfiguration)\Win32\*test*.dll
  !**\obj\**
```

According to http://yaml.org/spec/1.2/spec.html#id2795688, any string therein should be literal and cannot be escaped; however, VSCode shows all strings having errors or otherwise incorrect. These cannot be quoted, or the quotes will - as spec'd - end up in the VSTS tasks (see screenshot).

![image](https://user-images.githubusercontent.com/1532486/42667426-58e42a78-8600-11e8-859f-457289c747d2.png)

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (24.08GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sidebar|Acr|1.0.0
xml|Dot|2.3.1
vscode-guid|hea|1.3.1
vscode-azurefunctions|ms-|0.9.1
vscode-azurestorage|ms-|0.4.0
vscode-cosmosdb|ms-|0.8.0
python|ms-|2018.6.0
azure-account|ms-|0.4.1
cpptools|ms-|0.17.6
csharp|ms-|1.15.2
Go|ms-|0.6.84
PowerShell|ms-|1.8.1
team|ms-|1.136.0
debugger-for-chrome|msj|4.8.0
vscode-docker|Pet|0.0.27

</details>

**Comment by heaths** [comment]
Folded blocks have a similar problem:

```yaml
packagesToPush: >
  $(Build.SourcesDirectory)\**\*.nupkg;
  !**\*.symbols.nupkg;
  !**\packages\**\*.nupkg;
```

...yields:

![image](https://user-images.githubusercontent.com/1532486/42667821-78742120-8602-11e8-91d3-b9de4369ec56.png)

**Comment by aeschli** [comment]
marking as dup https://github.com/textmate/yaml.tmbundle/issues/26

**Comment by heaths** [comment]
@aeschli, how do you track insertion of syntax changes, or are any available in textmate's repos automatically transformed and inserted during VSCode build?

**Comment by aeschli** [comment]
It's done manually. I update all grammars at least once every release. We have a script that reads the grammars from the original. The copy has additional properties to document what original commit the copy is from.
Just ping me anytime if you want me to update a particular grammar.
