### ISSUE TITLE
Editor cannot be dragged to full size

### ISSUE THREAD

**Issue by linfan68** [Microsoft/vscode#54218]
After the 1.25.0 update I found the editor window cannot be resized to full horizontal space. See screen shot below:
 
![image](https://user-images.githubusercontent.com/4918344/42665312-f1119cb6-85f3-11e8-87d8-dbbdb622497d.png)
With other views open:

![image](https://user-images.githubusercontent.com/4918344/42665366-2c3ce994-85f4-11e8-89c9-c8651a61e5cd.png)

**Comment by linfan68** [comment]
Update: problem fixed after removing the ..\AppData\Roaming\Code\Local Storage\

**Comment by bpasero** [comment]
@linfan68 looks like you were in "Centered Editor Mode", something you can turn off from the "View" menu.
