### ISSUE TITLE
Terminal startup render issue on long paths

### ISSUE THREAD

**Issue by abartho** [Microsoft/vscode#54217]
If VS Code opens a directory with a long path, the integrated terminal will initially render the path incorrectly. Selecting the terminal and pressing enter fixes the issue.

Terminal after opening
![startup_broken](https://user-images.githubusercontent.com/1980015/42664813-b1a27460-8634-11e8-99ff-6387a251c4d3.png)

Terminal after pressing enter
![pressed_enter](https://user-images.githubusercontent.com/1980015/42664820-b718147c-8634-11e8-9cb6-4d171f701d88.png)

Version: 1.25.1 and earlier
OS: Linux Mint 18 Cinnamon 64-bit
Issue occurs with extensions disabled: yes

How to reproduce:
1. Create a directory with a really long path (see screenshot)
2. Make sure terminal is closed
3. Open long directory in VS Code via File -> Open Folder
4. Open terminal

OR

1. Create a directory with a really long path (see screenshot)
2. Open terminal
3. Open long directory in VS Code via File -> Open Folder
4. Restart VS Code

What I expect to see: The path of the currently opened directory rendered correctly in the integrated terminal
What I actually see: The path of the currently opened directory split and overriding the start of the line (see screenshot)

Note: the same behavior occurs with shorter directories, if the prompt is set up to show extra information (such as the current branch in a git-versioned directory)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/48136
