### ISSUE TITLE
VS Code CLI throws errors when using "code" command

### ISSUE THREAD

**Issue by nbystrom** [Microsoft/vscode#54216]
Issue Type: <b>Bug</b>

When I type "code" into the command line to run vs code, I get "node.dll not found", and "ffmpeg not found" errors. When I type the same command using "code.cmd" instead of just "code" it works fine. This happens across cmd, git bash for windows, and powershell.

To reproduce:   
* Just type "code" into the command line

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.16299

**Comment by joaomoreno** [comment]
What is your `%PATH%` variable?

**Comment by nbystrom** [comment]
"%SystemRoot%\system32\python; %SystemRoot%\system32\python\python37; %SystemRoot%\system32\; %SytemRoot%; %SystemRoot%\system32\Wbem; %SYSTEMROOT%\system32\WindowsPowerShell\v1.0\; C:\WINDOWS\CCM; %NVM_HOME%; %NVM_SYMLINK%; C:\Program Files\Git\cmd; C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn; C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn; C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn; C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\MangaementStudio\; C:\Program Files\Microsoft VS Code\bin\code.cmd; C:\Program Files\Microsoft VS Code\bin\"

**Comment by joaomoreno** [comment]
Can you remove the `C:\Program Files\Microsoft VS Code\bin\code.cmd` part and try agian?

**Comment by nbystrom** [comment]
It still has not worked. Additionally, I tried moving it to the beginning, in case the issue was a semicolon in the path (that was an issue with python for some time), but it was not that either.

**Comment by joaomoreno** [comment]
Does it get fixed if you reinstall VS Code?

**Comment by nbystrom** [comment]
It still has the same error when I reinstalled VS Code.  However, while working on two different machines, I was unable to reproduce the bug, so I think I can chalk it up to this machine being weird.
