### ISSUE TITLE
Microsoft.VSCode.CPP.Extension.darwin consuming 100GB of RAM

### ISSUE THREAD

**Issue by shacron** [Microsoft/vscode#54211]
I found that my machine was slowing down. Microsoft.VSCode.CPP.Extension.darwin was spinning, consuming 50% of a core with the kernel task consuming 100% of another on its behalf. It has allocated up to 110GB before I killed it, and was rapidly growing.

Version 1.25.1 (1.25.1)
1dfc5e557209371715f655691b1235b6b26a06be
2018-07-11T15:27:07.646Z

[Sample of Microsoft.VSCode.CPP.Extension.darwin.txt](https://github.com/Microsoft/vscode/files/2190498/Sample.of.Microsoft.VSCode.CPP.Extension.darwin.txt)

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-cpptools
