### ISSUE TITLE
Add setting to not treat indented empty lines as trailing whitespace

### ISSUE THREAD

**Issue by kankaristo** [Microsoft/vscode#54210]
VSCode currently treats any whitespace at the end of a line as "trailing" whitespace.

However, I would consider the below 2 lines to be different:
![screenshot from 2018-07-13 00-18-29](https://user-images.githubusercontent.com/3522333/42659937-6edd9d64-8632-11e8-836c-786c1873ef38.png)

The first line unambiguously has trailing whitespace, and I'd like to automatically trim that (with `files.trimTrailingWhitespace` set to true).

But I'd consider the second line to be an *empty line with indentation* (the line contains only whitespace, or more specifically: indentation == trailing whitespace).

I'm moving to VSCode from Atom, which has a "Remove Trailing Whitespace" config option, but also has "Ignore Whitespace Only Lines", enabling this kind of functionality.

-----

"Ignore Whitespace Only Lines" **would be good enough** (I'd be very happy if this was added), but "Keep Indentation on Empty Lines" would be perfect. If the second line in the above example had 6 spaces, I'd like it to be trimmed to 4 spaces (the indentation in the current block).

I'm not sure how VSCode tracks indentation internally, but the way I do this in a custom lint script, is to look at the next non-whitespace line (backwards loop over all lines), and copy the indentation on that line to the empty lines before it. So, the end result (in Python) is:
![screenshot from 2018-07-13 00-49-06](https://user-images.githubusercontent.com/3522333/42661371-ab868e20-8636-11e8-98b4-8c82ad4a4264.png)

(line 132 has 4, not 8, spaces)

I realize that this may be way too specific (I'll look into writing an extension, if you feel this doesn't apply to very many users), and "Ignore Whitespace Only Lines" would be much simpler to implement, and based on Atom's config options, lots of users would probably like to see this.

**Comment by kankaristo** [comment]
Ah, I didn't find https://github.com/Microsoft/vscode/issues/49661, but I'll leave this open for now, since this has a slightly wider scope ("keep indentation" vs. "ignore whitespace-only lines").

But feel free to close this, if "keep indentation" isn't something you would implement (I'd be happy with the "ignore" option).

**Comment by mixingyu** [comment]
yep
we need
Keep Indentation on Empty Lines

**Comment by alexandrudima** [comment]
:+1: Let's track in #49661
