### ISSUE TITLE
Allow to associate a workspace folder to untitled documents

### ISSUE THREAD

**Issue by ArtemGovorov** [microsoft/vscode#54227]
Currently VS Code workspace API doesn't allow to specify the workspace of the document being created with:
```js
openTextDocument(options?: {content: string, language: string}): Thenable<TextDocument>
```

In our [Quokka extension](https://marketplace.visualstudio.com/items?itemName=WallabyJs.quokka-vscode) we allow users to select an active workspace (with `window.showWorkspaceFolderPick`). The active workspace is used as a working directory to run their code.

However, when we create new (scratch) documents with the `openTextDocument` method call, we can't pass the selected workspace, and it causes users to see intellisense (and other services) for the first workspace (rather than for the one selected by the extension).

Would it be possible to extend the API and add workspace URI property to the `options` parameter?

**Comment by bpasero** [comment]
@dbaeumer @aeschli since this would have to drag through all the layers of LSP etc. does this request even make sense for you? My understanding is that currently untitled buffers are not associated with any workspace at all?

**Comment by ArtemGovorov** [comment]
> My understanding is that currently untitled buffers are not associated with any workspace at all?

An untitled document still gets TypeScript intellisense from one of the opened workspaces, would be good to select which one if multiple workspaces are opened.

**Comment by bpasero** [comment]
@ArtemGovorov I see, let's wait for folks (including maybe @mjbvz) to hear back how that association is made.

**Comment by dbaeumer** [comment]
@bpasero the request does make sense to me. From a LSP perspective that there is no openTextDocument request. Only a notification that signals that a document did get opened. So I think this has no ripple effects on LSP.

**Comment by bpasero** [comment]
@dbaeumer but how would a language server be able to know for which workspace the untitled document belongs to without having some new property on it that identifies the workspace? We cannot use the resource path because the untitled document does not have one.

**Comment by jrieken** [comment]
> We cannot use the resource path because the untitled document does not have one.

Using some authority tricks? Like `untitled://workspace-id/Untitled-1` etc... Still, it would require that the language brains know about that convention.

**Comment by dbaeumer** [comment]
@bpasero that would be something the vscode lsp library had to implement. The LSP protocol would not know about this since the client would map the untitled document to the server that handles the workspace folder. So you are right there is a ripple in the library but not in the protocol itself.

**Comment by mjbvz** [comment]
TS puts untitled files into an inferred project. For untitled resources, this inferred project is always in the first root folder because we do not have a concept of an "active root" when first creating the untitled filed. 

This has been the behavior since we introduced multiroot support and is the first time I have heard about it causing problems
