### ISSUE TITLE
Shortcut: CTRL + P 

### ISSUE THREAD

**Issue by yuluotuxi** [Microsoft/vscode#54225]
After entering a file name,can not find the file which already existed in the project，besides，the speed slower than before at the latest version.

**Comment by TomasHubelbauer** [comment]
Are you sure the file is not in `.gitignore` or some `excludes` field in settings?

**Comment by yuluotuxi** [comment]
@TomasHubelbauer yes, I`m sure. I hava several project, all the project Work normally expect this project （https://github.com/mattermost/mattermost-webapp）。

**Comment by TomasHubelbauer** [comment]
I'll try to repro, what file are you searching using Ctrl+P, specifically what precise substring so that I can do a precise repro?

**Comment by yuluotuxi** [comment]
@TomasHubelbauer

**Comment by yuluotuxi** [comment]
I can not find the file when using  Ctrl+P if I didn't opent the file.

**Comment by TomasHubelbauer** [comment]
I was able to find any file I tried without opening it first. Is this broken for all files for you or only some files?

**Comment by TomasHubelbauer** [comment]
I think this is caused by your local setup. Try to use VS Code without extensions and see if this reproduces and if it persists, try to backup your VS Code preferences and restore them to defaults to see if that will help.

**Comment by yuluotuxi** [comment]
I remember I had enabled the  flow extensions and disabled the typescript extensions.Is it  cause  the  result?

**Comment by TomasHubelbauer** [comment]
I don't know, you can try and see for yourself by running VS Code without extensions: 

https://code.visualstudio.com/docs/editor/command-line#_working-with-extensions

`--disable-extensions`

**Comment by yuluotuxi** [comment]
Thanks  very  much，I will  try  it 。

**Comment by chrmarti** [comment]
Does `Ctrl + Shift + F` find any text in that file? Try with and without the exclusion settings by toggling: 
![image](https://user-images.githubusercontent.com/9205389/42767292-d89cf1fe-891c-11e8-8b71-1275923672c9.png)
