### ISSUE TITLE
[folding] JSX cant collapse blog of code in 1.25.1

### ISSUE THREAD

**Issue by bossnarathip** [Microsoft/vscode#54223]
blog of code in JSX can collapse before v 1.24 but in the present can't, give it back to our

<img width="677" alt="screen shot 2561-07-13 at 10 07 25" src="https://user-images.githubusercontent.com/18586257/42670425-fb87aef6-8684-11e8-9cc9-f34c6c8ee9c3.png">

**Comment by mjbvz** [comment]
Duplicate of #53939
