### ISSUE TITLE
Suddenly close VScode

### ISSUE THREAD

**Issue by kokheng1025** [Microsoft/vscode#54222]
- VSCode Version: 1.25.0
- OS Version: Window 10.0.16299 build 16299

Steps to Reproduce:

1. Open VScode and leave it a while
2. VScode app will automatically close, without any notice

Does this issue occur when all extensions are disabled?: Yes/No
Not sure how to disable all extension, havent't try it out

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
