### ISSUE TITLE
clang-msvc- Cannot find or open the PDB file

### ISSUE THREAD

**Issue by yl3d** [Microsoft/vscode#54221]
0>I do have installed VS2015
vscode:
1>clang++ --target=x86_64-pc-windows-msvc
2>debug-->(windows) launch
3>Loaded 'C:\..........\VsCode_clang_win_test\bin\hello.exe'. Symbols loaded.
Loaded 'C:\Windows\System32\ntdll.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\System32\kernel32.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\System32\KernelBase.dll'. Cannot find or open the PDB file.

**Comment by weinand** [comment]
Please provide repeatable steps and file this against the C++ extension.
