### ISSUE TITLE
Multiple rename variables

### ISSUE THREAD

**Issue by julsburgs** [Microsoft/vscode#54235]
To be able select two or more variables and rename with f2

**Comment by alexrohleder** [comment]
I guess you could have a similar effect pressing `CTRL + SHIFT + L` (or even spamming `CTRL + D`)  with the cursor on the variable you want to rename.

see https://code.visualstudio.com/docs/getstarted/keybindings

**Comment by Curdflappers** [comment]
Do you want to rename multiple variables to the same name? If so, why? If not, I think it is simpler to just rename one variable at a time.

**Comment by julsburgs** [comment]
I mean rename variables in inline declaretion and tab between variables

**Comment by jrieken** [comment]
> I mean rename variables in inline declaretion and tab between variables

Sorry, I don't understand. Can you use more words and a sample?
