### ISSUE TITLE
The width of the terminal can overflow out of the panel for proportional fonts

### ISSUE THREAD

**Issue by pvakharia9033** [Microsoft/vscode#54230]
Issue Type: <b>Bug</b>

Open side by side integrated terminal the boundry of terminals are not properly allign it goes over side bar (my side bar is on right hand). The inner wall of terminals ae also overlaping fonts.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (3.32GB free)|
|Process Argv|D:\Program Files (x86)\Microsoft VS Code\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-cosmosdb|ms-|0.8.0
azure-account|ms-|0.4.1
node-debug2|ms-|1.26.2

</details>

**Comment by wgwine** [comment]
![screen shot 2018-07-13 at 11 09 58 am](https://user-images.githubusercontent.com/2429681/42698939-548bf7c0-868d-11e8-9b9b-6d417f5371ee.png)

I see the same on Mac.

**Comment by yume-chan** [comment]
Relates to #51945

Regression?

**Comment by Tyriar** [comment]
This is fixed in insiders https://github.com/Microsoft/vscode/issues/51479

**Comment by yume-chan** [comment]
@Tyriar Someone has confirmed it's fixed in a 7-day-ago version, but I think this guy is using... eh... a not-7-day-ago version.

And I can still reproduce it using my "invalid terminal font" repro.

![image](https://user-images.githubusercontent.com/1330321/42766569-67e41060-894d-11e8-8a9b-f829621751b4.png)

**Comment by Tyriar** [comment]
@yume-chan hmm, I can't repro that on Linux using dom renderer+Arial. What font are you using?

**Comment by yume-chan** [comment]
@Tyriar I'm using canvas renderer.

Steps to reproduce:

1. Set `terminal.integrated.fontFamily` to invalid value.
2. Close terminal panel and sidebar
3. Restart Code
4. Open sidebar
5. Open terminal panel

**Comment by Tyriar** [comment]
@yume-chan I can repro with those steps 👍

**Comment by Tyriar** [comment]
I don't think it's the issue the OP was seeing but let's track it here. https://github.com/Microsoft/vscode/issues/51945 was about monospace fonts

**Comment by Tyriar** [comment]
This would be fixed with the proposal in https://github.com/xtermjs/xterm.js/issues/702#issuecomment-403133603
