### ISSUE TITLE
Smooth scrolling fix failed after enabled custome title bar

### ISSUE THREAD

**Issue by StormBR1120** [Microsoft/vscode#54234]
Issue Type: <b>Bug</b>

Update to 1.25.1 and set `"window.titleBarStyle": "custom"`,
smooth scrolling do not work, even `"editor.smoothScrolling"` and `"window.smoothScrollingWorkaround"` are set `true`.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.86GB (3.20GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe d:\multimedia\Documents\_My\Stormworks^PL\学习笔记\05 SpringMVC.txt|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
reg|ion|0.0.2
vscode-language-pack-zh-hans|MS-|1.25.3

</details>

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/53793
