### ISSUE TITLE
Toolbar menu not responding after closing windowed project

### ISSUE THREAD

**Issue by guiroco** [Microsoft/vscode#54231]
Issue Type: <b>Bug</b>

Using the new feature 'custom toolbar menu' I open a project in another VSC window an then close the just created window before it loads properly makes the toolbar menu not responding.

Steps to reproduce

1. File => Ctrl + Open recent project (open any project).
2. When another window pops up close quickly.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (1.65GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|40%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
jshint|dba|0.10.19
vscode-eslint|dba|1.4.12
githistory|don|0.4.1
tslint|eg2|1.0.33
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.3.0
beautify|Hoo|1.3.2
docthis|joe|0.7.1
Angular1|joh|0.2.0
Angular2|joh|6.1.1
json-to-ts|Mar|1.5.5
vscode-todo-parser|min|1.9.1
vscode-autoprefixer|mrm|2.1.2
debugger-for-chrome|msj|4.8.0
vscode-docker|Pet|0.0.27
material-icon-theme|PKi|3.5.1
vscode-icons|rob|7.24.0
sass-indented|rob|1.4.9
lorem-ipsum|Tyr|1.2.0
vscode-todo-highlight|way|0.5.12
JavaScriptSnippets|xab|1.7.0
markdown-pdf|yza|1.2.0

(1 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
I am unable to repro this issue, can you still repro on the latest builds? @guiroco
