### ISSUE TITLE
open multiple files with the same filename

### ISSUE THREAD

**Issue by fleeto** [Microsoft/vscode#54246]
Issue Type: <b>Bug</b>

The files are in different paths like this. When I clicked on different file, Code will open the file in the same editor tab.
.
├── codea
│   └── 1.txt
├── codeb
│   └── 1.txt
└── codec
    └── 1.txt

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|29%|

</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.18.0
vscode-docker|Pet|0.0.27
code-settings-sync|Sha|2.9.2
yaml|ada|0.0.9
hugofy|akm|0.1.0
vscode-python-docstring|aza|0.0.5
toml|be5|0.0.3
better-toml|bun|0.3.2
gitignore|cod|0.5.0
systemd-unit-file|coo|1.0.0
vscode-dash|dee|1.10.0
tslint|eg2|1.0.33
code-runner|for|0.9.3
gc-excelviewer|Gra|2.1.24
beautify|Hoo|1.3.2
kubernetes-snippets|ipe|0.1.9
prettify-json|moh|0.0.3
vscode-language-pack-zh-hans|MS-|1.25.3
vscode-kubernetes-tools|ms-|0.1.11
python|ms-|2018.6.0
Go|ms-|0.6.84
vscode-yaml|red|0.0.13
jinja|who|0.0.8
markdown-pdf|yza|1.2.0

</details>

**Comment by bpasero** [comment]
Follow our docs to resolve this: https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode
