### ISSUE TITLE
Open Terminal As New Tabs

### ISSUE THREAD

**Issue by ShibaSalmon** [Microsoft/vscode#54240]
Hello everyone.
I think that it would be useful to open terminals as code editing tab
Default you only open terminal on lower part.
But sometimes you will using terminal for connecting VM, etc, and you may use external terminals.
It is so convenient to open terminal as new tabs for that.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/10546
