### ISSUE TITLE
VS Code won't highlight C# files

### ISSUE THREAD

**Issue by Someguy123** [Microsoft/vscode#5424]
- VSCode Version: 1.0.0
- OS Version: OSX 10.10.5 (Yosemite)

Steps to Reproduce:

1. Open a .cs file
2. The file is not highlighted
3. There is also no option when trying to manually set it to C# by clicking "plain text" at the bottom

![](https://i.imgur.com/2aWoMuZ.png)

**Comment by Stanzilla** [comment]
I think you need https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp

**Comment by Someguy123** [comment]
@stanzilla seems a little odd that C# (including highlighting) was pulled from the core, when Visual Basic and F# are both there still...

Was this supposed to happen? 

I was using vs code alone with C# just a few months back without needing to download anything extra.

**Comment by egamma** [comment]
@Someguy123 yes this was intentional. For C# there is much more support than just coloring and you really want to use the full extension.

We will provide more guidance to install recommended extensions in the future.

**Comment by Someguy123** [comment]
@egamma I see, the C# extension does work like the old built-in support.

How about a nice alert like the "Visual Studio Code has been updated", which says something like 

>Click *View Online* to view the EXTENSION_LANGUAGE extension, which may include features such as better syntax highlighting, debugging support etc. for LANGUGE [View Online] [Later] [Never]

**Comment by egamma** [comment]
@Someguy123 yes this is consistent with what we are planning to provide, thanks.

**Comment by aliozgur** [comment]
How about code just analyses the opened file and suggest to install the language extension if one exists on the marketplace?
