### ISSUE TITLE
Cannot touch new-styled submenus

### ISSUE THREAD

**Issue by the1812** [Microsoft/vscode#54249]
Issue Type: <b>Bug</b>

**How to reproduce:**
(When `window.titleBarStyle = "native"`)
Open a menu, touch a submenu item, then my touch will be ignored and submenu remain closed.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

**Comment by sbatten** [comment]
closed via 7c14a15a5a8197962685e8ebfa59fdcfd09dd9cd

**Comment by bpasero** [comment]
@the1812 are you sure you had native title style enabled and not custom?

**Comment by the1812** [comment]
@bpasero I'm sorry, it should be `custom` and I updated my description.

**Comment by the1812** [comment]
Completely fixed in version 1.27.1, thank you.
