### ISSUE TITLE
suggestions open only on first caret even when it out of view

### ISSUE THREAD

**Issue by andrey6498** [Microsoft/vscode#54245]
VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

Steps to Reproduce:

1.Select multiple lines in file(more than screen can show, or just scroll down)
2.And now try to open suggestions popup

Isn't it needs to open on _**first visible**_ caret?

**Comment by Tyriar** [comment]
It's not clear what you mean, can you post a screenshot?

**Comment by andrey6498** [comment]
![1](https://user-images.githubusercontent.com/8511369/42939381-1d77fa24-8b5e-11e8-8f4f-758cf215e0d9.jpg)
![2](https://user-images.githubusercontent.com/8511369/42939383-1d98858c-8b5e-11e8-92dc-dc2656059cfb.jpg)

**Comment by andrey6498** [comment]
So vscode needs to show suggestions on first _visible_ line or _jump to first selected line_ when you try to open them

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/6995
