### ISSUE TITLE
breakpoint not hit in extension development.

### ISSUE THREAD

**Issue by Jostar1024** [Microsoft/vscode#54247]
- VSCode Version: 1.25.1
- OS Version: Ubuntu 16.04 LTS

Information from Help -> About

> Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:40:20.190Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

Steps to Reproduce:

1. follow the [tutorial](https://code.visualstudio.com/docs/extensions/example-hello-world) of developping an extension from official site.
2. Set a breakpoint and it's not hit. No information is presented on the sidebar, `debugger` doesn't work as well. It seems that source map here is not working.

Does this issue occur when all extensions are disabled?: **Yes**
![image](https://user-images.githubusercontent.com/13313192/42684810-cd4fd380-86c3-11e8-9f93-4c48552ffe2d.png)

**Comment by isidorn** [comment]
This works fine for me
@Jostar1024 can you reproduce using latest vscode insiders https://code.visualstudio.com/insiders/

**Comment by roblourens** [comment]
Did you run the command? Did the Hello World message appear?

**Comment by Jostar1024** [comment]
I've tried insider version. It's the same behavior.

**Comment by roblourens** [comment]
If you run the command a second time, do you hit the breakpoint?

Can you post your launch config her?

Can you set `"trace": true` in your launch config, run it again, and upload the log here?

**Comment by Jostar1024** [comment]
```json
{
	"version": "0.2.0",
    "configurations": [
        {
            "name": "Extension",
            "type": "extensionHost",
            "request": "launch",
            "runtimeExecutable": "${execPath}",
            "args": [
                "--extensionDevelopmentPath=${workspaceFolder}"
            ],
            "outFiles": [
                "${workspaceFolder}/out/**/*.js"
            ],
            "preLaunchTask": "npm: watch",
            "trace": true
        },
        {
            "name": "Extension Tests",
            "type": "extensionHost",
            "request": "launch",
            "runtimeExecutable": "${execPath}",
            "args": [
                "--extensionDevelopmentPath=${workspaceFolder}",
                "--extensionTestsPath=${workspaceFolder}/out/test"
            ],
            "outFiles": [
                "${workspaceFolder}/out/test/**/*.js"
            ],
            "preLaunchTask": "npm: watch"
        }
    ]
}
```
Here is the log file
[vscode-node-debug2.txt](https://github.com/Microsoft/vscode/files/2235007/vscode-node-debug2.txt)

**Comment by roblourens** [comment]
The log shows setting a breakpoint on line 8, hitting that breakpoint, then continuing. It doesn't show a breakpoint on line 21.

**Comment by Jostar1024** [comment]
Yeah sorry I've messed up the line. Here is the log files with the breakpoint on line 21.
[vscode-node-debug2.txt](https://github.com/Microsoft/vscode/files/2240608/vscode-node-debug2.txt)

Although the breakpoint seems to be hit, It did stop at the unknowing line and I have to click Continue to run the rest of the program. But neither the highlight of the breakpoint's line, nor the debug context on the side bar is shown. The situation on the image shown on top of this issue is that this program stops at the unknowing line...

**Comment by roblourens** [comment]
Oh, now I see that the debug adapter never responds to the 'stackTrace' request, which is very weird. Everything else looks normal. Do you see the same if you set a breakpoint somewhere else in the file? At the top level or in the activate function? I think that's what the first log is showing?

Can you try disabling all other extensions by starting with `--disable-extensions`, in case one of them is interfering somehow?

**Comment by Jostar1024** [comment]
I did see the same (nothing is shown) if I set breakpoint somewhere else in `extension.ts`. Debugger statement doesn't work either. Starting vscode with `--disable-extensions` doesn't change the behavior.

The "stopOnEntry" of launch.json did stop and give me back the right infos on `bootstrap_node.js`. However, when the program enters into `extension.ts`, nothing works....

**Comment by roblourens** [comment]
Ok, honestly I don't know what might be going on... I've never seen this issue even on the same version of Ubuntu.

Have you debugged any other node programs on this computer?

**Comment by roblourens** [comment]
I am stumped, and if you are up for setting up the debug adapter so you can debug it, I would sure appreciate that and can tell you where to set breakpoints: https://github.com/Microsoft/vscode-node-debug2

Alternately, you can open up the extension source in the app and add some more logs.
