### ISSUE TITLE
Improve menu selection behaviour

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#54242]
In the following screencast, I am clicking and holding on `Stage Changes` and then moving the mouse around:

![peek 2018-07-13 10-37](https://user-images.githubusercontent.com/22350/42681749-daec8d20-8688-11e8-95b4-41a6e2078aab.gif)

There are a couple things that appear to be weird:

- If I click-hold and drag, I still should get hover feedback on the elements I drag over (though I'd argue I should get active feedback, instead of hover feedback, but that's another issue #54170)
- If I click-hold, drag to another item and release, then that other item's action should run. This makes me wonder if you should simply listen on mouse up and ignore mouse down altogether.
- There shouldn't be two difference states on these menu items, just one. Currently I can change selection with the keyboard and focus with the mouse (apparently), which is very strange for a menu. Either pressing navigation keys or moving the mouse should alter the focused item.

**Comment by joaomoreno** [comment]
Ignore the last point, it's #54237

**Comment by sbatten** [comment]
The issues outlined here exist separately as #52907 and #54237 as mentioned above
