### ISSUE TITLE
Extension tips service should only listen on `file` schema URIs

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#54255]
It seems that file extensions recommendations listen to any text model document and look for file extensions. Virtual documents coming from the git extension end with `.git` in their path. The tips service detects that as a file with a `git` extension and pings the marketplace for it:

![screenshot from 2018-07-13 14-32-02](https://user-images.githubusercontent.com/22350/42691770-a98d7412-86a9-11e8-97ca-df8baa8dc59c.png)

The tips service should filter out all documents which are not `file` scheme.

This is very likely a candidate for re-release since it's causing lots of traffic in the Marketplace servers.

**Comment by sandy081** [comment]
My bad. This is caused by my Changes 

Candidate for recovery.

**Comment by sardorocket** [comment]
is it still for the June recovery?

**Comment by sandy081** [comment]
No release were planned last week as there was no response from Marketplace team. So this will go in July milestone
