### ISSUE TITLE
VS Code update fail

### ISSUE THREAD

**Issue by Dan503** [Microsoft/vscode#54253]
VS Code told me to make a new GitHub issue so I'm making a new GitHub issue

![error-message](https://user-images.githubusercontent.com/10610368/42688992-e4ecb18e-86e1-11e8-820f-da5a58fdf28e.png)

- VSCode Version: ? (can't check)
- OS Version:

![os-details](https://user-images.githubusercontent.com/10610368/42689037-14f71b44-86e2-11e8-9730-2ded5a3875bf.png)

Steps to Reproduce:

1. Pop up asked me to upgrade
2. I clicked update now
3. crash

Here is the log file: [vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2192406/vscode-inno-updater.log)

**Comment by Dan503** [comment]
![error-message-2](https://user-images.githubusercontent.com/10610368/42689211-befe5ada-86e2-11e8-83bf-fc617e7d9bf9.png)

**Comment by HarryAdney** [comment]
Same here. windows 10 insider, 17692.rs_prerelease_flt.180625-1624
Log file attached
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2192576/vscode-inno-updater.log)

**Comment by joaomoreno** [comment]
You seem to have #47841.

Please read this comment if you can provide more detail: https://github.com/Microsoft/vscode/issues/47841#issuecomment-393101777

Please read this one to disable background updates: https://github.com/Microsoft/vscode/issues/47841#issuecomment-395017687

Also read this one to provide feedback on our new user setup: https://github.com/Microsoft/vscode/issues/47841#issuecomment-399941682

**Comment by HarryAdney** [comment]
Thanks, I see from #47841 that MalwareBytes seems to be involved. I have it installed on my system, so this looks like the likeliest culprit.

Thanks for your help and guidance.

**Comment by Dan503** [comment]
> MalwareBytes seems to be involved. I have it installed on my system, so this looks like the likeliest culprit.

Just letting you know that I have MalwareBytes installed on my computer as well.
