### ISSUE TITLE
Chinese translation error.中文翻译错误

### ISSUE THREAD

**Issue by scriptkitz** [Microsoft/vscode#5425]
- VSCode Version: 1.0.0
- OS Version: win7

Steps to Reproduce:

1.  default config, 27 line num.
```
	// 一个选项卡等于的空格数。    <---- "选项卡" should be "制表符" or just call "Tab"
	"editor.tabSize": 4,
```
2. line num:36
```
	// 控制选项是否有圆角         <------"控制选项" should be "选区" or "选择区域"
	"editor.roundedSelection": true,
```

**Comment by medifle** [comment]
+1

**Comment by Nullizer** [comment]
+1

**Comment by javagg** [comment]
+1

**Comment by johnliu2016** [comment]
@lukaschal string location:
[commonEditorConfig.nls.resx.lcl](https://monacotools.visualstudio.com/DefaultCollection/Monaco/_git/MonacoLocalization#path=%2FLocalize%2Fchs%2Fvscode%2Fsrc%2Fvs%2Feditor%2Fcommon%2Fconfig%2FcommonEditorConfig.nls.resx.lcl&version=GBmaster&_a=contents)

      <Item ItemId=";tabSize" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[The number of spaces a tab is equal to.]]></Val>
          <Tgt Cat="Text" Stat="Loc" Appr="PreApproved" Orig="New">
            <Val><![CDATA[一个选项卡等于的空格数。]]></Val>
          </Tgt>

      <Item ItemId=";roundedSelection" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[Controls if selections have rounded corners]]></Val>
          <Tgt Cat="Text" Stat="Loc" Appr="PreApproved" Orig="Auto" Confidence="100">
            <Val><![CDATA[控制选项是否有圆角]]></Val>
          </Tgt>
        </Str>

**Comment by lukaschal** [comment]
These issue are on review in this bug:

https://github.com/Microsoft/vscode/pull/5395

**Comment by lukaschal** [comment]
Fixed as suggested.
