### ISSUE TITLE
Add user VSCode to save custom configurations

### ISSUE THREAD

**Issue by JoelCL** [Microsoft/vscode#54259]
A very necessary function would be to be able to save my custom configurations and my extensions already installed, so when I migrate from one PC / laptop to another, I can not lose all my configurations. In web browsers have that functionality, just by logging into the software, those configurations and extensions are automatically imported. Then, it would be good to add users to Visual Studio Code, so that they can save their unique profile.

**Comment by Tyriar** [comment]
https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync
