### ISSUE TITLE
custom titlebar broke stage selected files

### ISSUE THREAD

**Issue by t7yang** [Microsoft/vscode#54265]
- VSCode Version: both stable 1.25.1 and 1.26.0-insider
Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Version: 1.26.0-insider
Commit: 023b51bcc6204cc9bb9ca7752f764a3396401ec7

- OS Version: Windows

Steps to Reproduce:

1. set `window.titleBarStyle` to `custom` and restart.
2. try to use context menu to stage selected files, expecting stage all selected files, but stage only one.
![2018-07-13_23-43-23](https://user-images.githubusercontent.com/4502661/42701102-3e1f48b4-86f8-11e8-8ee0-9260257bbc63.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Fixed in master: #54112
