### ISSUE TITLE
@memberOf or @memberof

### ISSUE THREAD

**Issue by maschmid-MSFT** [Microsoft/vscode#54268]
Issue Type: <b>Bug</b>

When writing code documentation I noticed an anomaly. If I start typing @member then autosuggest gives me the option of @memberOf (notice the capital O). However, if I type with a lowercase O as in "@memberof" then syntax highlighting highlights similar to how @param or other documentation fields are highlighted. "@memberOf" is not highlighted leading me to believe it is incorrect but that it is what autosuggest is suggesting.

-maschmid

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.90GB (18.35GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.3.1
gitlens|eam|8.4.1
tslint|eg2|1.0.33
beautify|Hoo|1.3.2
csharp|ms-|1.15.2
PowerShell|ms-|1.8.1
debugger-for-chrome|msj|4.8.0
material-icon-theme|PKi|3.5.1
vscode-icons|rob|7.24.0

(1 theme extensions excluded)

</details>

**Comment by maschmid-MSFT** [comment]
somehow the memberOf directives were changed to lowercase in the bug report.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#25653

**Comment by JacksonKearl** [comment]
Edited to use backtick code blocks rather than username pings (resolves casing issue). Also verified (`@memberof` is now the suggestion)
