### ISSUE TITLE
Import IntelliSense (path and module suggestions) completely gone in Typescript and Javascript

### ISSUE THREAD

**Issue by FadeZhanger** [Microsoft/vscode#54267]
- VSCode Version: 1.26.0-insider (updated July 13, 2018)
- OS Version: Windows 10 (build 17134)
- Typescript version: 3.0.0-insiders.20180706

Steps to Reproduce:
1. Open any typescript file (.ts or .tsx)
2. Type out an ES6 import statement (e.g. `import {} from './` ... or `import DefaultImport from './` ... or `import React from 're` ...)

Expected:
IntelliSense gives suggestions for a module or a local relative file path

Actual:
Intellisense displays string keywords from current file with no module or file path suggestions (e.g. ['import', 'from'] are given as suggestions when the file contains `import {} from './`)
This bug also occurs for JS files (.js/.jsx) in the same fashion.

Video: http://recordit.co/bCV36K4KTC

tsconfig.json:
```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "allowJs": true,
    "jsx": "react",
    "module": "commonjs",
    "moduleResolution": "node",
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "sourceMap": true,
    "strictNullChecks": true,
    "target": "es5"
  }
}
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by reneruiz** [comment]
I have this same issue. Path Intellisense & Path Autocomplete extensions also do not work for me.

**Comment by FadeZhanger** [comment]
@reneruiz are you still having this issue? It should be fixed in the latest build, but if you haven't updated, then using TS 2.9.2 instead of 3.0-insiders is a workaround.
