### ISSUE TITLE
Terminal doesn't launch independently from "terminal.integrated.shell.windows" setting

### ISSUE THREAD

**Issue by AbstractFlame** [Microsoft/vscode#54269]
- VSCode Version: 1.25.0
- OS Version: Win7
- Does this issue occur when all extensions are disabled?: Yes

Steps to Reproduce:

1. Open VS Code

Details:

If I activate the terminal window then a cursor shows up but can't type any character.
I've been searching four ours for the solution and I try every suggested values for "terminal.integrated.shell.windows" setting and I restarted VS Code a ton of times and nothing helped.

![vs code no terminal](https://user-images.githubusercontent.com/16545103/42704873-cb9639c2-86d1-11e8-8885-e8135bcbe2ee.png)

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/43169
