### ISSUE TITLE
When 'Beautifying', the collapsed code expands again

### ISSUE THREAD

**Issue by animanoir** [Microsoft/vscode#54266]
- VSCode Version: 1.25.2
- OS Version: W10

Steps to Reproduce:

1. Use Beautify extension
2. Collapse code
3. Beautify code
4. See expanded, previously collapsed code.

Does this issue occur when all extensions are disabled?: Yes.

**Comment by aeschli** [comment]
I can't reproduce this with the following example and the build-in html formatter (no extension):
```html
<html>
<body>
	<div>
		<div class = "adasad">
			   hello
			hello
			hello
		</div>
	</div>
</body>

</html>
```
![unfolding-while-formatting](https://user-images.githubusercontent.com/6461412/45544052-8e3db480-b816-11e8-9983-d04f86fffdee.gif)

No folded ranges are unfolded when formatting is applied. 

Please reopen with a example that shows the problem.
