### ISSUE TITLE
Cannot save new file without file extension

### ISSUE THREAD

**Issue by AnthonyMastrean** [Microsoft/vscode#54263]
Cannot save new file without file extension

> [Window Title]
> Save As
> 
> [Content]
> Vagrantfile
> The file name is not valid.
> 
> [OK]

![image](https://user-images.githubusercontent.com/217842/42699457-ce24aaea-868e-11e8-8f19-a15f0aae141d.png)

# System

- VSCode Version: latest
- OS Version: Windows 10 Pro 1803

# Steps to Reproduce:

1. Open code
2. Add a new file
3. Save file
4. Choose a file name without an extension
5. Switch "Save as type" to "any file" to avoid an automatic extension being added
6. Error!

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
It should work fine if you pick "No File Extension":

![image](https://user-images.githubusercontent.com/900690/42701137-0ab7fd9a-86c6-11e8-922b-6df902422362.png)
