### ISSUE TITLE
Before decoration results in wrong border size

### ISSUE THREAD

**Issue by BoykoAlex** [Microsoft/vscode#54279]
- VSCode Version: 1.25.1
- OS Version: Mac OSX 10.13.5

Steps to Reproduce:
```
const DECORATION = VSCode.window.createTextEditorDecorationType({
            before: {
                contentIconPath: path.resolve(__dirname, "../icons/boot-12.png"),
                margin: '0px 2px 0px 0px'
            },
            backgroundColor: 'rgba(109,179,63,0.25)',
            borderColor: 'rgba(109,179,63,0.25)',
            borderSpacing: '4px',
            borderRadius: '4px',
            borderWidth: '4px'
        });
// Code calculates ranges which are correct ranges
// ...
// Logic to calculate ranges
// ...
editor.setDecorations(this.DECORATION, decorations)
```
The above creates a decoration that looks like:

![image](https://user-images.githubusercontent.com/6433390/42713991-6dd927fc-86bf-11e8-8bff-1a833ceb433b.png)

Looks like background is coloured first then the before decoration appears but background is not redrawn. If I collpase/expand something in the editor the background color is is placed correctly within the specified range accounting for the before decoration.

Also a question: why is the image in before decoration a few pixels over the bottom? The bounds seem to be correct, but the image is shifted... Mystery... Any chance the icon in before decoration grows as text font grows?

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
> Looks like background is coloured first then the before decoration appears but background is not redrawn.

I believe the background is correctly drawn. But perhaps the image is not finished loading. Since this is a CSS pseudo element we don't have a lot of options here on our side. i.e. I don't think we can listen to pseudo element's background images finishing loading. Have you tried giving an explicit `width` and `height` ?

> why is the image in before decoration a few pixels over the bottom?

Perhaps giving an explicit `width` and `height` might help in this case too.

> Any chance the icon in before decoration grows as text font grows?

You could read the editor's settings and adjust the `width` and `height` on your side. e.g.:

```js
function readEditorLineHeight() {
	const MINIMUM_LINE_HEIGHT = 8;
	const MAXIMUM_LINE_HEIGHT = 150;
	const GOLDEN_LINE_HEIGHT_RATIO = (process.platform === 'darwin') ? 1.5 : 1.35;

	const editorConfig = vscode.workspace.getConfiguration('editor');
	const fontSize = editorConfig.get('fontSize');
	let configuredLineHeight = editorConfig.get('lineHeight');

	function clamp(n, min, max) {
		if (n < min) {
			return min;
		}
		if (n > max) {
			return max;
		}
		return n;
	}

	function safeParseInt(n, defaultValue) {
		if (typeof n === 'number') {
			return Math.round(n);
		}
		let r = parseInt(n);
		if (isNaN(r)) {
			return defaultValue;
		}
		return r;
	}

	let lineHeight = safeParseInt(configuredLineHeight, 0);
	lineHeight = clamp(lineHeight, 0, MAXIMUM_LINE_HEIGHT);
	if (lineHeight === 0) {
		lineHeight = Math.round(GOLDEN_LINE_HEIGHT_RATIO * fontSize);
	} else if (lineHeight < MINIMUM_LINE_HEIGHT) {
		lineHeight = MINIMUM_LINE_HEIGHT;
	}
	return [fontSize, lineHeight];
}
```
