### ISSUE TITLE
Tabbing through snippet placeholders is circular, the cycle breaks on ENTER or ESC. Need better user experience

### ISSUE THREAD

**Issue by medifle** [Microsoft/vscode#5427]
- VSCode Version: 1.0.0-stable
- OS Version: 10.11.4

Steps to Reproduce:
1. Open VS  Code using `--disable-extensions` flag
2. `Cmd-N` to open an empty file
3. `Cmd-K M` to choose `Language Mode` to `HTML`
4. Enter `!` or `html:5` and hit `TAB` to expand
5. Use `TAB` to jump to inside the `body` tag
6. Enter any legal emmet syntax like `.container>.row` and hit `TAB`

Here is an animated GIF:

![vscode-emmet-html5](https://cloud.githubusercontent.com/assets/13296643/14592836/b255cc5c-0555-11e6-8294-df7285542c47.gif)

What I expect to happen:

As the last step above has been executed, normally the emmet in other editors should perform its expand action and the result is:

``` html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>
  <div class="conainer">
    <div class="row"></div>
  </div>
</body>
</html>
```

However, VS Code does not do that, just jumping back to inside the `title` tag.

**Comment by traktraktrugui** [comment]
You need to press [ENTER] when focus is on <body>.

**Comment by yisibl** [comment]
@traktraktrugui This experience is not very good.

**Comment by atwright147** [comment]
If it helps with debugging, pressing `[Esc]` after the first expansion, means that the next expansion will work.

**Comment by Sapunov** [comment]
This is totally unexpected behavior:( While @mrmlnc don't ask me to press Enter or Esc I can't write my emmet expressions.

**Comment by ramya-rao-a** [comment]
This is due to the way we treat snippets with placeholders. Tabs always circle among the placeholder. Hitting ENTER or ESC breaks the cycle.

@jrieken You have any thoughts here on how we could make the experience better?

**Comment by jrieken** [comment]
Yeah, that how snippets are currently implemented. I personally also like the tab-tab-done mode better. I am planning a bigger redo of the snippet controller in Spring and could tackle this than

**Comment by jrieken** [comment]
This got implemented via https://github.com/Microsoft/vscode/pull/26042. Snippet insertion now follows the tab-tab-done model, meaning snippet mode exists as soon as the the final tab stop is reached. Also Enter doesn't exist snippet anymore by default.
