### ISSUE TITLE
Show editor peek for related diagnostics

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#54271]
**Feature request**
In the related diagnostics view, add a way to show a peek editor  for the related location. Currently, related diagnostics jump to related location when clicked. Often you just want to see the code without losing context

**Comment by sandy081** [comment]
@mjbvz Where do you want this peek widget to be shown?

**Comment by mjbvz** [comment]
This came out of the FB meeting. I do not know if they had an exact idea of where it should be shown, but showing a code peak somewhere is something they were very interested in

**Comment by sandy081** [comment]
But this has to be shown somewhere in Editor right and not in Problems view?

**Comment by jrieken** [comment]
> In the related diagnostics view

Is that the problem view or peek in peek?

**Comment by mjbvz** [comment]
"peek" may be an overloaded term here. What the FB guys specifically requested was a way to show the code that a related diagnostic refers to. I believe this would be shown both in the editor when hovering over a diagnostic, as well as in the problems panel when the diagnostic is expanded. We could use a peek view for this, or some other way to present code inline

**Comment by jrieken** [comment]
Yeah, we had an initial version of this in which the F8-error view wouldn't show the filename and line number but an actual preview of the code in question. We can revive that.
