### ISSUE TITLE
Treat any file in a "log" folder as a log file

### ISSUE THREAD

**Issue by kankaristo** [Microsoft/vscode#54278]
This may be more of a question than a feature request, sorry about that in advance.

I was pleasantly surprised to find that the following works as intended:
```json
"files.associations": {
    "**/log/**": "log",
    "**/logs/**": "log"
}
```

But I started wondering why it isn't enabled by default? Does using `**` have performance implications? Are you worried that this would override file associations for a log class in a directory called "log"?

Or *should* this be enabled by default? (the "feature request" part of this issue)

I would argue that at least `/var/log/**` should be enabled by default (assuming it works, I didn't try absolute paths), if not a catch all `**/log/**`.

**Comment by superamadeus** [comment]
Because it’s a massive assumption. 

If I had a class `UserLog` in `src/log/user.ts`, I want it to be a typescript file and not a log file.

**Comment by mjbvz** [comment]
I think this behavior could be a confusing default. Since it sounds like you can already configure this, I'm closing this issue as a potential user setting / extension candidate

**Comment by kankaristo** [comment]
Okay, fair enough.

Is there some option that would assume the file is a log file only if no other language/syntax was detected (and it matched `**/log/**` or `**/logs/**`). Something like this (although it looks a bit weird):
```json
"[plaintext]": {
    "files.associations": {
        "**/log/**": "log",
        "**/logs/**": "log"
    }
}
```
