### ISSUE TITLE
[folding] Allow markdown code blocks to be foldable

### ISSUE THREAD

**Issue by masters3d** [Microsoft/vscode#54282]
I searched for this feature but could not find  it. Please close if it is already being tracked. 

When I am inside a markdown file, I'd like to be able to fold code blocks

\```C#
namespace Rextester
{
    public class Program
    {
        public static void Main(string[] args)
        {
            //Your code goes here
        } 
}
\```

into this:

\```C#
\>...
\```

**Comment by mjbvz** [comment]
duplicate of #36169
