### ISSUE TITLE
Toggling sidebar switches away from settings editor

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#54280]
Issue Type: <b>Bug</b>

**Repo**
1. Open a file.
1. Open new settings editor
1. Toggle the side bar to hide it and then again to show it 

**Bug**
Editor switches from settings editor back to opened file

VS Code version: Code - Insiders 1.26.0-insider (023b51bcc6204cc9bb9ca7752f764a3396401ec7, 2018-07-13T05:11:27.582Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_10898020|
|Screen Reader|no|
|VM|15%|

</details>

**Comment by roblourens** [comment]
Fixed
