### ISSUE TITLE
Implicit rename operations

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#54283]
**Feature request**
Allow a rename to be implicitly when editing an identifier. Example:

```js
const abc = 123;
console.log(abc)
```

User edits `abc` in `const abc` to `def`. At this point, we ask the user if they wanted to they wanted to trigger a rename for all reference to `abc` to `def`.

(From the FB meeting)

**Comment by mjbvz** [comment]
Tricky since we presumably need to either:

- Get all potential rename operations before the user edits the identifier, and remember these locations so that we an perform a rename later

- Keep around multiple versions of the document

**Comment by jrieken** [comment]
Yeah, tricky... We would need to know those rename-targets upfront and post-edit (whenever that actually is) we would need to prompt and perform the rename...
