### ISSUE TITLE
Background task presentation option to hide terminal output

### ISSUE THREAD

**Issue by alpaix** [microsoft/vscode#54288]
In a Live Share scenario, we create a shadow task in a remote VSCode instance to let a participant control task execution (list, start, terminate). 
In parallel, we synchronize existing task terminals currently open on the host side.
This flow leads to an experience of showing two terminals per actual host task.
A possible solution would be adding a task presentation option allowing a shadow task's execution running without a terminal.

**Comment by dbaeumer** [comment]
@alpaix not sure I understand you correctly. Why do you need a task for this in the remote. Would it be not enough to query the API?

**Comment by alpaix** [comment]
When a participant interacts with the VSCode tasks menu they get a list of tasks produced by the Live Share task provider. These tasks are proxy tasks executed by a remote host. Whenever a guest user runs a task we start our broker process associated with the selected task; this process monitors a corresponding task execution on the host.

**Comment by alpaix** [comment]
@dbaeumer Perhaps there's a better solution for this. We'd simply wanted to not surface a proxy task execution.

**Comment by dbaeumer** [comment]
@alpaix now I understand what is happening. I think what would be a better solution is add a predefined task type that has no command and is handed to the extension for execution. In this way the task system would not start something in the terminal. For example a task type "$proxy". Such a task would not be customizable in the tasks.json either.

**Comment by alpaix** [comment]
yes, that'd be ideal!

**Comment by alpaix** [comment]
@dbaeumer How probable is it that this issue would get resolved in November milestone?

**Comment by dbaeumer** [comment]
@alpaix we published the November plan yesterday and we didn't add this. So I would say very unlikely. If this is urgent we need to talk to @kieferrm to see if we can re-schuffle things?

**Comment by dbaeumer** [comment]
@kieferrm this is not minor work: needs new API and a new concept we currently don't have.

**Comment by alpaix** [comment]
This is not very urgent. Still, it'd be helpful to understand if and when this issue could be resolved so we'd plan some integration work on our end. Thanks!

**Comment by dbaeumer** [comment]
OK. Understood. @kieferrm can you add this to the next plan that we at least investiagte what it would mean to implement.

**Comment by alexr00** [comment]
@alpaix does the proposed (soon to be finalized) CustomExecution solve your use case?
