### ISSUE TITLE
Rapid progress.report({increment}) values are lost

### ISSUE THREAD

**Issue by vector-of-bool** [Microsoft/vscode#54295]
I talked shortly with @bpasero on [this commit](https://github.com/Microsoft/vscode/commit/098cf01a2e35d00206ec29c4e95cfc7d308afdc6). (A few hours have turned into a few days. Oops.)

- VSCode Version: 1.25.1
- OS Version: elementaryOS Loki (Ubuntu 16.04 Xenial)

Steps to Reproduce:

1. An extension calls `withProgress(...)` to get a progress handle.
2. Call `progress.report({increment: value})` quickly in a short time frame
3. The progress increments are lost.

Does this issue occur when all extensions are disabled?: Yes

As far as I can tell, the trouble is the debouncer for progress RPC. It "merges" repeated progress calls into a single progress RPM, but a faulty conditional prevents repeated `increment` values from being added together to sum up to the final value. See the linked commit.

**Comment by bpasero** [comment]
@vector-of-bool can you provide a small sample on top of a generated extension (via "yo code" generator - [link](https://github.com/Microsoft/vscode-generator-code)).

**Comment by vector-of-bool** [comment]
Sure. Should I attach the ext as an archive? Upload a repo? I could also just attach a VSIX.

Here's the entirety of `extension.ts`, if that suffices:

```ts
'use strict';
import * as vscode from 'vscode';

function pause(time: number): Thenable<void> {
  return new Promise(resolve => { setTimeout(() => { resolve(); }, time); });
}

export function activate() {
  vscode.commands.registerCommand('bad-progress.showProgress', () => {
    return vscode.window.withProgress(
        {location: vscode.ProgressLocation.Notification, title: 'Dummy Progress'},
        async (pr) => {
          let value = 0;
          while (value < 100) {
            // Wait for a random amount of time. Pauses less than the debounce time (100ms)
            // will cause the progress notification to lose increments.
            // With 200ms as the max pause, 1/2 increments will be lost. The
            // resulting progress bar will show about 1/2 progress.
            await pause(Math.random() * 200);
            value++;
            // Increment. Show the actual percentage for reference.
            pr.report({increment: 1, message: `Progress is at ${value}%`});
          }
          await pause(2000);
        },
    );
  });
}

export function deactivate() {}
```

**Comment by bpasero** [comment]
Thanks, I can have a look.
