### ISSUE TITLE
Toggle Word Wrap doesn't work with the custom title bar style on Windows

### ISSUE THREAD

**Issue by grahammcculloch** [Microsoft/vscode#54291]
Issue Type: <b>Bug</b>

(Using Windows 10, default is `"editor.wordWrap": "off"`)
1. Switch to the custom title bar style and restart VS Code:
```"window.titleBarStyle": "custom"```
2. Open a new file and enter a long sentence of text that causes horizontal scrolling.
3. Select View -> Toggle Word Wrap
4. The text is (incorrectly) _not_ wrapped.
5. Switch to the native title bar style and restart VS Code:
```"window.titleBarStyle": "native"```
6. Select View -> Toggle Word Wrap
7. Verify that the text is now correctly wrapped.

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (7.97GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\cshcV3\cshc-web|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
django-html|bib|1.2.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.12
vscode-babel-coloring|dza|0.0.4
permute-lines|ear|0.0.9
prettier-vscode|esb|1.5.0
gc-excelviewer|Gra|2.1.24
restructuredtext|lex|65.0.0
python|ms-|2018.6.0
azure-account|ms-|0.4.1
vscode-docker|Pet|0.0.27
vscode-remote-editor|see|0.0.1
vscode-sql-beautify|sen|0.0.4

</details>

**Comment by grahammcculloch** [comment]
Yes - I can reproduce without extensions. See this [video recording](http://recordit.co/VJ9hQ0wUJh).

**Comment by sbatten** [comment]
This should now be fixed in insiders. Please give it a try @grahammcculloch
