### ISSUE TITLE
Debug adapter process has terminated unexpectedly with PowerShell

### ISSUE THREAD

**Issue by selfvoid** [Microsoft/vscode#5429]
- VSCode Version: 1.0.0
- OS Version: Windows 10 x64
- PowerShell extension: 0.5.0

Steps to Reproduce:

1. Toggle break point with F9 key (step can be skipped, but it recommended by "PowerShell extension" manual.)
2. Start debugging with F5.

Message appear: Debug adapter process has terminated unexpectedly

txt file is absent in C:\Users\[user]\.vscode\extensions\ms-vscode.PowerShell-0.5.0\bin

**Comment by dbaeumer** [comment]
This has to go to the PowerShell repository. I pinged their devs.

**Comment by daviwil** [comment]
Just received another report of this, will track it there:

https://github.com/PowerShell/vscode-powershell/issues/149
