### ISSUE TITLE
When VS Code and Fortnite are open at the same time, the system crashes because "SYSTEM THREAD EXCEPTION NOT HANDLED"

### ISSUE THREAD

**Issue by Floffah** [Microsoft/vscode#54297]
- VSCode Version: 1.25.1
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Download, install, and launch Visual Studio Code and leave running for an hour or so (what i did)
2. Download, install, and launch fortnite 

Does this issue occur when all extensions are disabled?: Yes/No yes

Other information:
i was able to reproduce this bug with the steps above. oh an by the way, it occurs when the computer has been turned on for atleast an hour with VS Code open most of the time.

**Comment by J0shhT** [comment]
I believe this is a fortnite related issue, nothing to do with VS Code itself.
