### ISSUE TITLE
Switching system agents crash the VSCode

### ISSUE THREAD

**Issue by cx3386** [Microsoft/vscode#54298]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Open vscode and download/update some packages
2. When downloading, switch the system agents (using Shadowsocks by "Enable system agents")
3. Vscode breaks down without any prompt

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
What OS? What's a system agent?
