### ISSUE TITLE
[html] Please provide a built-in HTML.tmLanguage file

### ISSUE THREAD

**Issue by sodatea** [Microsoft/vscode#543]
Lots of template languages extend html syntax.

Since popular text editors such as sublime text and atom usually have built-in `HTML.tmLanguage` file, most online syntax definition files just simply add an `include: text.html.basic` field in them.

However, Visual Studio Code does not have that built-in syntax definition file, thus forcing language extension authors to manually include an `HTML.tmLanguage` file. This feels awkward. I don't want to redefine HTML syntax in every single language extension I wrote.

So, please provide a built-in HTML syntax definition file for language extension authors!

**Comment by aeschli** [comment]
Makes sense, will add.

**Comment by aeschli** [comment]
Fix delivered

**Comment by Spown** [comment]
>Fix delivered

So what exactly have happened here? How to use it? I can't see anything in the update log and/ordocumentation.

**Comment by aeschli** [comment]
The built in HTML extension now contains the html text mate grammar and declares the scope name `text.html.basic`.
The HTML editor mode in VSCode doesn't the text mate grammar yet, but other language extensions that depend on the html text mate grammar to be present profit from this. The issues description is a good summary.

**Comment by abdelouahabb** [comment]
this feature will be usefull to develop extensions like Django/Jinja/Tornado templates support for example

**Comment by abdelouahabb** [comment]
@aeschli Emmet are not fired on langagues that use HTML (Jinja, Tornado, Django...etc), how to activate it?

In Atom, I added this ` atom-text-editor[data-grammar="text html tornado"]:not([mini])` in the `keymaps`, I checked the `emmet docs` and dident found the value to put in preferences?

**Comment by mrmlnc** [comment]
@abdelouahabb, well, that's a work in progress. See #9500

**Comment by abdelouahabb** [comment]
@mrmlnc ah, thank you, excited to see it coming ^_^
