### ISSUE TITLE
Make "Restart TS Server" available in multiroot workspaces

### ISSUE THREAD

**Issue by hbenl** [Microsoft/vscode#54306]
When installing/updating npm packages, the Typescript server (and hence the Intellisense feature) often fails to pick up the changes and needs to be restarted. Unfortunately, the "Restart TS server" command is not available in multiroot workspaces. Please make it available there as well.

**Comment by mjbvz** [comment]
It is enabled in multi-root workspace, but you have to be in a js/ts file

**Comment by mjbvz** [comment]
Why are you running this command by the way? You should never need to unless you re-install the workspace version of typescript itself. Please open a new issue if you find yourself having to restart the TS server manually

**Comment by hbenl** [comment]
> you have to be in a js/ts file

You're right, I diagnosed this wrong.

> Why are you running this command by the way? You should never need to unless you re-install the workspace version of typescript itself.

Hmm, I was under the impression that when I `npm install` an additional dependency, the TS Server (sometimes?) fails to pick it up. But maybe I mis-diagnosed this as well.

> Please open a new issue if you find yourself having to restart the TS server manually

Will do. Thanks for the explanation.
