### ISSUE TITLE
Extension's view/title menu entry contributions are sometimes grouped incorrectly

### ISSUE THREAD

**Issue by hbenl** [Microsoft/vscode#54308]
- VSCode Version: 1.25.1 (also tested with the lates insiders release)
- OS Version: Arch Linux x64

I have some `view/title` menu item contributions in my `package.json`:
```
        {
          "command": "test-explorer.enable-autorun",
          "group": "1_autorun@1",
          "when": "view == test-explorer"
        },
        {
          "command": "test-explorer.disable-autorun",
          "group": "1_autorun@2",
          "when": "view == test-explorer"
        },
        {
          "command": "test-explorer.retire",
          "group": "2_state@1",
          "when": "view == test-explorer"
        },
        {
          "command": "test-explorer.reset",
          "group": "2_state@2",
          "when": "view == test-explorer"
        }
```
This results in the menu items being grouped incorrectly:
![screenshot_2018-07-14_15-38-15](https://user-images.githubusercontent.com/16060807/42724953-30670926-877c-11e8-9b7f-11b24146da9d.png)

There is a workaround: if I change the `group` properties from `2_state@1` to `2_state@3` and from `2_state@2` to `2_state@4`, it works as expected:
![screenshot_2018-07-14_15-42-32](https://user-images.githubusercontent.com/16060807/42724977-aeb71f96-877c-11e8-94e5-f6398312742c.png)

So it looks like this only occurs when there are menu items in different groups that have the same item sorting index.
Note also that I have only seen this bug in `view/title` contributions whereas `view/item/context` contributions work flawlessly.

**Comment by hbenl** [comment]
That's not a duplicate of this issue.

**Comment by sandy081** [comment]
Forwarding to @jrieken as it is related to menu

**Comment by jrieken** [comment]
I cannot reproduce. Please provide more information so that I can reproduce this locally.

<img width="268" alt="screen shot 2018-08-29 at 16 38 49" src="https://user-images.githubusercontent.com/1794099/44795028-061aa680-abaa-11e8-9343-7eca97ff7db1.png">

**Comment by hbenl** [comment]
It looks like you tried this with a `view/item/context` contribution, which doesn't have this bug. Try it with a `view/title` contribution.

**Comment by jrieken** [comment]
That's true. I can reproduce there.

**Comment by jrieken** [comment]
By part here work correctly, the `fillInAction...`-function works proper (see screenshot). This must get scrambled downlevel, e.g when merging with legacy actions or so.

<img width="827" alt="screen shot 2018-08-29 at 17 48 48" src="https://user-images.githubusercontent.com/1794099/44799332-f1dba700-abb3-11e8-8244-4709a74089a9.png">

**Comment by jrieken** [comment]
The ViewletPanel#setActions method seems to be called with the wrong data. Someone on the way it gets broken, my suspect is `prepareAction` which is always doing some funky resort.

<img width="607" alt="screen shot 2018-08-29 at 17 51 51" src="https://user-images.githubusercontent.com/1794099/44799453-3cf5ba00-abb4-11e8-8e83-45cdc5131009.png">

**Comment by sandy081** [comment]
@bpasero `prepareActions` is messing up the order.

**Comment by bpasero** [comment]
@hbenl can you share the full package.json with the view contribution and the commands etc. so that I can reproduce?

**Comment by jrieken** [comment]
There you go @bpasero 

```
{
	"name": "virtual",
	"displayName": "Virtually Testing",
	"description": "Balbababababab",
	"version": "0.0.2",
	"publisher": "jrieken",
	"engines": {
		"vscode": "^1.23.0"
	},
	"categories": [
		"Other"
	],
	"activationEvents": [
		"onFileSystemAccess:foo",
		"onFileSystemAccess:mem",
		"onView:fooTree",
		"*"
	],
	"main": "./out/extension",
	"enableProposedApi": true,
	"contributes": {
		"views": {
			"explorer": [
				{
					"id": "fooTree",
					"name": "Foo Tree"
				}
			]
		},
		"snippets": [
			{
				"language": "abc",
				"path": "./snippets/abc.json"
			},
			{
				"path": "./snippets/super.code-snippets"
			}
		],
		"languages": [
			{
				"id": "json2",
				"aliases": [
					"JSON2"
				],
				"extensions": [
					".json2"
				]
			},
			{
				"id": "foo",
				"aliases": [
					"foolang"
				],
				"extensions": [
					".foo"
				]
			},
			{
				"id": "foobar",
				"aliases": [
					"Foobar"
				],
				"extensions": [
					".foobar"
				]
			},
			{
				"id": "barfoo",
				"aliases": [
					"Barfoo"
				],
				"extensions": [
					".barfoo"
				]
			},
			{
				"id": "abc",
				"extensions": [
					".abc"
				],
				"configuration": "./abc.language-configuration.json"
			}
		],
		"commands": [
			{
				"command": "extension.sayHello",
				"title": "Hello World & Welt"
			},
			{
				"command": "extension.sayHello1",
				"title": "test-1"
			},
			{
				"command": "extension.sayHello2",
				"title": "test-2"
			},
			{
				"command": "extension.sayHello3",
				"title": "test-3"
			},
			{
				"command": "extension.sayHello4",
				"title": "test-4"
			}
		],
		"menus": {
			"commandPalette": [
				{
					"command": "extension.sayHello"
				}
			],
			"view/title": [
				{
					"command": "extension.sayHello1",
					"group": "1_autorun@1",
					"when": "view == fooTree"
				},
				{
					"command": "extension.sayHello2",
					"group": "1_autorun@2",
					"when": "view == fooTree"
				},
				{
					"command": "extension.sayHello3",
					"group": "2_state@1",
					"when": "view == fooTree"
				},
				{
					"command": "extension.sayHello4",
					"group": "2_state@2",
					"when": "view == fooTree"
				}
			]
		},
		"keybindings": [
			{
				"key": "cmd+j",
				"command": "extension.sayHello"
			}
		],
		"configuration": {
			"properties": {
				"foo.bar": {
					"type": "string"
				},
				"extension.setting": {
					"type": "string",
					"default": "Grüezi"
				},
				"properties": {
					"testExtension.object": {
						"default": null,
						"type": "object",
						"properties": {
							"field": {
								"default": "hello",
								"type": "string"
							}
						}
					}
				}
			}
		},
		"configurationDefaults": {
			"[python]": {
				"editor.suggestSelection": "first"
			}
		},
		"problemMatchers": [
			{
				"pattern": [
					{
						"regexp": "^([^\\\\s].*)\\\\((\\\\d+,\\\\d+)\\\\):\\\\s*(.*)$",
						"file": 1,
						"location": 2,
						"message": 3
					}
				]
			}
		]
	},
	"scripts": {},
	"devDependencies": {
		"typescript": "2.5.3",
		"vscode": "1.1.5",
		"@types/node": "8.0.31"
	}
}

```

**Comment by jrieken** [comment]
And I'd put my money on this being the [order-patching](https://github.com/Microsoft/vscode/blob/5c9d1c4cd13607758dcc757f78b1686bf886ccb1/src/vs/workbench/browser/actions.ts#L166-L179)
