### ISSUE TITLE
Error in path localization

### ISSUE THREAD

**Issue by regme** [Microsoft/vscode#5430]
- VSCode Version: 1.0.0-insider (0.35.6)
- OS Version: Windows 10 Pro (Russian)

Steps to Reproduce:

1. Create Windows user with russian chars in name
2. Install .Net Command Lite Tools (1.0.0-beta-001598)
3. Open some .sln in VS Code
4. Wait until installation of .Net Debugger finish
5. Open Error Log

**Андрей** --> **РђРЅРґСЂРµР№**

Error: Response file 'C:\Users\РђРЅРґСЂРµР№\.vscode-insiders\extensions\ms-vscode.csharp-1.0.3-rc2\coreclr-debug\obj\Debug\netstandardapp1.5\dotnet-compile.rsp' doesn't exist.

> log  : Restoring packages for C:\Users\Андрей\.vscode-insiders\extensions\ms-vscode.csharp-1.0.3-rc2\coreclr-debug\project.json...
info : Committing restore...
log  : Restore completed in 5170ms.

> NuGet Config files used:
    C:\Users\Андрей\.vscode-insiders\extensions\ms-vscode.csharp-1.0.3-rc2\coreclr-debug\NuGet.config

> Feeds used:
    https://www.myget.org/F/dotnet-core/api/v3/index.json
    https://api.nuget.org/v3/index.json
    https://www.myget.org/F/coreclr-debug/api/v3/index.json
Publishing dummy for .NETStandardApp,Version=v1.5/win7-x64
Project dummy (.NETStandardApp,Version=v1.5) will be compiled because expected outputs are missing.
 C:\Users\Андрей\.vscode-insiders\extensions\ms-vscode.csharp-1.0.3-rc2\coreclr-debug\bin\Debug\netstandardapp1.5\dummy.dll
 C:\Users\Андрей\.vscode-insiders\extensions\ms-vscode.csharp-1.0.3-rc2\coreclr-debug\bin\Debug\netstandardapp1.5\dummy.pdb
 C:\Users\Андрей\.vscode-insiders\extensions\ms-vscode.csharp-1.0.3-rc2\coreclr-debug\bin\Debug\netstandardapp1.5\win7-x64\dummy.dll
 C:\Users\Андрей\.vscode-insiders\extensions\ms-vscode.csharp-1.0.3-rc2\coreclr-debug\bin\Debug\netstandardapp1.5\win7-x64\dummy.pdb

> Compiling dummy for .NETStandardApp,Version=v1.5
Running C:\Program Files\dotnet\bin\dotnet.exe compile-csc @C:\Users\Андрей\.vscode-insiders\extensions\ms-vscode.csharp-1.0.3-rc2\coreclr-debug\obj\Debug\netstandardapp1.5\dotnet-compile.rsp
Process ID: 9248
Error: Response file 'C:\Users\РђРЅРґСЂРµР№\.vscode-insiders\extensions\ms-vscode.csharp-1.0.3-rc2\coreclr-debug\obj\Debug\netstandardapp1.5\dotnet-compile.rsp' doesn't exist.

> Error: C:\Program Files\dotnet\bin\dotnet.exe compile-csc @C:\Users\Андрей\.vscode-insiders\extensions\ms-vscode.csharp-1.0.3-rc2\coreclr-debug\obj\Debug\netstandardapp1.5\dotnet-compile.rsp returned Exit Code 1

> Compilation failed.
    0 Warning(s)
    0 Error(s)

> Time elapsed 00:00:00.6875176

> Published 0/1 projects successfully
dotnet exited with error code 1

**Comment by dbaeumer** [comment]
@jrieken do you know where to move this? Looks like OmniSharp.

**Comment by regme** [comment]
### temporary solution for this case

`C:\Users>mklink /D РђРЅРґСЂРµР№ c:\Users\Андрей`

`symbolic link created for РђРЅРґСЂРµР№ <<===>> c:\Users\Андрей`

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#210
