### ISSUE TITLE
NPM scripts explorer doesn't show all scripts in multiroot workspace

### ISSUE THREAD

**Issue by hbenl** [Microsoft/vscode#54307]
- VSCode Version: 1.25.1
- OS Version: Arch Linux x64

Steps to Reproduce:

1. create a multiroot workspace with 2 folders
2. add package.json to each folder containing npm scripts, some of them having the same name in both folders

Expected results: all npm scripts for both folders are shown
Actual results: all npm scripts for the first folder are shown; for the second folder, only npm scripts that have a name not occurring in the first folder are shown

Does this issue occur when all extensions are disabled?: Yes

**Comment by hbenl** [comment]
I checked the listed issues and none of them seems to be a duplicate of this one.

**Comment by egamma** [comment]
This looks like a duplicate of #54085.

This is the interesting information
>Actual results: all npm scripts for the first folder are shown; for the second folder, only npm scripts that have a name not occurring in the first folder are shown

**Comment by egamma** [comment]
Closing as duplicate of #54085
