### ISSUE TITLE
Auto double trigger webpack compile with watch file when save file on smb share folder VMWare

### ISSUE THREAD

**Issue by KytoSai** [Microsoft/vscode#54303]
- VSCode Version: 1.125.1
- OS Version: MacOS 10.13.6

I'm using VMWare with CentOS 7, I've shared the Project folder with MacOS.

- Then I ran the Webpack Watch file on CentOS.

- I modified the file inside the project in shared folder, then Webpack on CentOS automatically trigger compile bundles 2 times. I do not know how to handle this problem?

- I tried textEdit so this does not happen.
- I tried fixing it directly on Filezilla so this does not happen

Please show me how to fix this. Here is my video:

https://www.youtube.com/watch?v=-h99GqND69U&feature=youtu.be

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
I suggest to report this to them.
