### ISSUE TITLE
installed on ubuntu but it doesn't run

### ISSUE THREAD

**Issue by Albert819** [Microsoft/vscode#54301]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
Can you try run `code --verbose`?

How did you install VS Code?

**Comment by Albert819** [comment]
I have solved it. It's permission problem.
cd ～/config
Sudo rm - rf ./Code/
