### ISSUE TITLE
'Spread Operator'-like support for settings.json?

### ISSUE THREAD

**Issue by NavyAdmiral** [Microsoft/vscode#54305]
Hi. With settings like this, you have to copy the whole array to append a new setting:
![image](https://user-images.githubusercontent.com/40662484/42724404-a414756a-8782-11e8-9cd1-88c0931a26c5.png)
This clutters settings.json unnecessarily.
Instead, I'd want to just append a new option like this:
![image](https://user-images.githubusercontent.com/40662484/42724431-13b92ed8-8783-11e8-83bf-6d19e31e61e6.png)

Is this feasible?

**Comment by lloydjatkinson** [comment]
I'm sure it's feasible, but then it's no longer JSON.

**Comment by NavyAdmiral** [comment]
@lloydjatkinson Yea file needs to be .js if this is to be supported. Maybe there's other way to make this work though?
