### ISSUE TITLE
Go To Definition: "config/index.js"  is conflict with "~/Library/Caches/typescript/2.9/node_modules/@types/config/index.d.ts"

### ISSUE THREAD

**Issue by texzhichen** [Microsoft/vscode#54311]
- VSCode Version: 1.25.1
- OS Version: macOS 10.13.5

Steps to Reproduce:

For a Node project, I create a `config/index.js` under the root of the project. Somewhere at another folder, I use `const config = require('config')` for the absolute path import. I have set `NODE_PATH=.` and `jsconfig.json` such that it works well with other folders, e.g., `middleware/index.js` or even `configs/index.js`, but not the `config` folder.

If I delete the `config` folder at `~/Library/Caches/typescript/2.9/node_modules/@types`, "Go To Definition" works as expected (it leads me to the `config/index.js`). However, once vscode restarts, the `config` folder at `~/Library/Caches/typescript/2.9/node_modules/@types` is automatically generated.

My `jsconfig.json` is as follows.
```json
{
  "compilerOptions": {
    "target": "ES6",
    "module": "es2015",
    "moduleResolution": "node",
    "baseUrl": "."
  }
}
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#25692
