### ISSUE TITLE
syntax highlight error

### ISSUE THREAD

**Issue by ustccjw** [Microsoft/vscode#5431]
- VSCode Version: 1.0.0
- OS Version: OSX 10.11.3

```
const timeRange = isAll ? '所有时间' : `${startTime} - ${endTime}`
...
````
![927f0b00-9866-458f-a2f2-228f039621ff](https://cloud.githubusercontent.com/assets/4114358/14596063/7120a2cc-0576-11e6-872b-c017dbaa8a7b.png)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#147
