### ISSUE TITLE
Scroll randomly lags when the window is maximized

### ISSUE THREAD

**Issue by ahmedhamdy90** [Microsoft/vscode#54313]
Issue Type: <b>Performance Issue</b>

Scroll lags when the window is maximized, and the only way to solve it is by un-maximizing the window then maximizing it again. I am using the touchpad.

Steps to reproduce:
1. Open VSCode 
2. Open a large code file (like 100~200 line of code)
3. While working, after a while, and randomly, the scroll will lag
4. The only way to regain scroll smoothest is by un-maximizing the window then maximizing it again

System Information:
1. Windows 10 Pro x64 version 1803
2. VSCode version 1.25.1
3. Laptop: Dell Inspiron 7559

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

**Comment by krupenja** [comment]
I think you might be experiencing #13612. Have you tried the workaround from that issue?

**Comment by ahmedhamdy90** [comment]
@krupenja I edited it in the setting, but should I enable the smooth scrolling too?
