### ISSUE TITLE
Selecting text in Mardown Preview leads to weird visual errors

### ISSUE THREAD

**Issue by deadcoder0904** [Microsoft/vscode#54319]
- VSCode Version: 1.25.1
- OS Version: Mac OS High Sierra 10.13.6

Steps to Reproduce:

1. Open `.md` file in Markdown Preview
2. Select Text in Markdown Preview

Checkout the GIF below & check the top right panel move 👇

![visual error](https://user-images.githubusercontent.com/16436270/42727519-2bd394f2-87c6-11e8-9b4d-ac75ff9ce1f6.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by deadcoder0904** [comment]
This is related to #53918 but not similar as I'm talking about the top right panel & the linked issue is talking about Copy+Paste Bug

**Comment by mjbvz** [comment]
Double clicking on an element in the preview switches the editor by default. Set `"markdown.preview.doubleClickToSwitchToEditor": false` to disable this

**Comment by deadcoder0904** [comment]
@mjbvz Can I ask why it isn't default as from my perspective it should be default🤔
