### ISSUE TITLE
titleBarStyle: custom Chinese menu font is too small

### ISSUE THREAD

**Issue by lhjok** [Microsoft/vscode#54314]
Issue Type: <b>Bug</b>

The Chinese menu is too small to increase the number one

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:40:20.190Z)
OS version: Linux x64 4.15.12-gentoo

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz (4 x 3796)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Load (avg)|0, 0, 0|
|Memory (System)|15.63GB (12.50GB free)|
|Process Argv|/opt/code/code --new-window-if-not-first|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
code-runner|for|0.9.3
vscode-rust|kal|0.4.2
vscode-language-pack-zh-hans|MS-|1.25.3
Go|ms-|0.6.84
RustyCode|sav|0.19.1

</details>

**Comment by sbatten** [comment]
I believe this has been addressed elsewhere
