### ISSUE TITLE
Intellisense Pick: don't double text to the right

### ISSUE THREAD

**Issue by sirgru** [Microsoft/vscode#54310]
If we have part of an identifier and call Intellisense in the middle of that identifier, when we pick the option the part to the right of the cursor will be ignored. This leads to situations where the part of the identifier that was right of the cursor is doubled. VS Code should take the duplicated part into account and remove it, just like full Visual Studio.

**Comment by Tyriar** [comment]
Can you show an example of what you mean preferably with screenshots?

**Comment by yume-chan** [comment]
For example, you now have `my|Value` where `|` denotes the cursor.

Invoke IntelliSense, choose `myValue` (same value as you already have), it will only move your cursor to the end (`myValue|`), not appending an extra value results `myValue|Value`.
