### ISSUE TITLE
snippet and intellisense management IS TERRIBLE 

### ISSUE THREAD

**Issue by axe-z** [Microsoft/vscode#54318]
in Js ..
typing for instance:  a

I get stuff i've got no clue where it's from or why.. 

![capture d ecran 2018-07-14 a 14 53 16](https://user-images.githubusercontent.com/27289270/42727502-1d7de272-8776-11e8-8669-15241cc37b5e.png)

so :( ... I do not use twiter where you guys are asking for feedback, so here's what I think.. so much great stuff, but falling at the basics and most important ones, I'm back on atom

**Comment by mjbvz** [comment]
Those are auto import suggestions. They come from all public exports in your project. Accepting one will add the correct import

You can find more information about them and how to disable them here: https://code.visualstudio.com/Docs/languages/javascript#_auto-imports
