### ISSUE TITLE
Windows update failed: Access is denied (resources)

### ISSUE THREAD

**Issue by DylanPerez1** [Microsoft/vscode#54328]
Jul 14 17:24:09.411 INFO Starting: C:\Program Files\Microsoft VS Code\Code.exe, false
Jul 14 17:24:09.453 INFO Checking for running Code.exe processes... (attempt 1)
Jul 14 17:24:09.461 INFO Code.exe is running, wait a bit
Jul 14 17:24:09.963 INFO Checking for running Code.exe processes... (attempt 2)
Jul 14 17:24:09.968 INFO Code.exe is running, wait a bit
Jul 14 17:24:10.470 INFO Checking for running Code.exe processes... (attempt 3)
Jul 14 17:24:10.475 INFO Code.exe is running, wait a bit
Jul 14 17:24:10.976 INFO Checking for running Code.exe processes... (attempt 4)
Jul 14 17:24:10.982 INFO Code.exe is running, wait a bit
Jul 14 17:24:11.483 INFO Checking for running Code.exe processes... (attempt 5)
Jul 14 17:24:11.488 INFO Code.exe is not running
Jul 14 17:24:11.488 INFO Checking for possible conflicting running processes... (attempt 1)
Jul 14 17:24:11.494 INFO Inno Updater v0.4.4
Jul 14 17:24:11.494 INFO Starting update, silent = false
Jul 14 17:24:11.564 INFO do_update: "C:\\Program Files\\Microsoft VS Code\\Code.exe", _
Jul 14 17:24:11.564 INFO move_update: "C:\\Program Files\\Microsoft VS Code\\unins000.dat", _
Jul 14 17:24:11.565 INFO Delete: "api-ms-win-core-console-l1-1-0.dll" (attempt 1)
Jul 14 17:24:11.584 INFO Delete: "api-ms-win-core-datetime-l1-1-0.dll" (attempt 1)
Jul 14 17:24:11.622 INFO Delete: "api-ms-win-core-debug-l1-1-0.dll" (attempt 1)
Jul 14 17:24:11.623 INFO Delete: "api-ms-win-core-errorhandling-l1-1-0.dll" (attempt 1)
Jul 14 17:24:11.624 INFO Delete: "api-ms-win-core-file-l1-1-0.dll" (attempt 1)
Jul 14 17:24:11.634 INFO Delete: "api-ms-win-core-file-l1-2-0.dll" (attempt 1)
Jul 14 17:24:11.635 INFO Delete: "api-ms-win-core-file-l2-1-0.dll" (attempt 1)
Jul 14 17:24:11.636 INFO Delete: "api-ms-win-core-handle-l1-1-0.dll" (attempt 1)
Jul 14 17:24:11.637 INFO Delete: "api-ms-win-core-heap-l1-1-0.dll" (attempt 1)
Jul 14 17:24:11.638 INFO Delete: "api-ms-win-core-interlocked-l1-1-0.dll" (attempt 1)
Jul 14 17:24:11.639 INFO Delete: "api-ms-win-core-libraryloader-l1-1-0.dll" (attempt 1)
Jul 14 17:24:11.640 INFO Delete: "api-ms-win-core-localization-l1-2-0.dll" (attempt 1)
Jul 14 17:24:11.671 INFO Delete: "api-ms-win-core-memory-l1-1-0.dll" (attempt 1)
Jul 14 17:24:11.673 INFO Delete: "api-ms-win-core-namedpipe-l1-1-0.dll" (attempt 1)
Jul 14 17:24:11.674 INFO Delete: "api-ms-win-core-processenvironment-l1-1-0.dll" (attempt 1)
Jul 14 17:24:11.689 INFO Delete: "api-ms-win-core-processthreads-l1-1-0.dll" (attempt 1)
Jul 14 17:24:11.690 INFO Delete: "api-ms-win-core-processthreads-l1-1-1.dll" (attempt 1)
Jul 14 17:24:11.691 INFO Delete: "api-ms-win-core-profile-l1-1-0.dll" (attempt 1)
Jul 14 17:24:11.693 INFO Delete: "api-ms-win-core-rtlsupport-l1-1-0.dll" (attempt 1)
Jul 14 17:24:11.694 INFO Delete: "api-ms-win-core-string-l1-1-0.dll" (attempt 1)
Jul 14 17:24:11.695 INFO Delete: "api-ms-win-core-synch-l1-1-0.dll" (attempt 1)
Jul 14 17:24:11.696 INFO Delete: "api-ms-win-core-synch-l1-2-0.dll" (attempt 1)
Jul 14 17:24:11.697 INFO Delete: "api-ms-win-core-sysinfo-l1-1-0.dll" (attempt 1)
Jul 14 17:24:11.699 INFO Delete: "api-ms-win-core-timezone-l1-1-0.dll" (attempt 1)
Jul 14 17:24:11.700 INFO Delete: "api-ms-win-core-util-l1-1-0.dll" (attempt 1)
Jul 14 17:24:11.702 INFO Delete: "api-ms-win-crt-conio-l1-1-0.dll" (attempt 1)
Jul 14 17:24:11.715 INFO Delete: "api-ms-win-crt-convert-l1-1-0.dll" (attempt 1)
Jul 14 17:24:11.717 INFO Delete: "api-ms-win-crt-environment-l1-1-0.dll" (attempt 1)
Jul 14 17:24:11.719 INFO Delete: "api-ms-win-crt-filesystem-l1-1-0.dll" (attempt 1)
Jul 14 17:24:11.720 INFO Delete: "api-ms-win-crt-heap-l1-1-0.dll" (attempt 1)
Jul 14 17:24:11.721 INFO Delete: "api-ms-win-crt-locale-l1-1-0.dll" (attempt 1)
Jul 14 17:24:11.722 INFO Delete: "api-ms-win-crt-math-l1-1-0.dll" (attempt 1)
Jul 14 17:24:11.724 INFO Delete: "api-ms-win-crt-multibyte-l1-1-0.dll" (attempt 1)
Jul 14 17:24:11.725 INFO Delete: "api-ms-win-crt-private-l1-1-0.dll" (attempt 1)
Jul 14 17:24:11.726 INFO Delete: "api-ms-win-crt-process-l1-1-0.dll" (attempt 1)
Jul 14 17:24:11.727 INFO Delete: "api-ms-win-crt-runtime-l1-1-0.dll" (attempt 1)
Jul 14 17:24:11.727 INFO Delete: "api-ms-win-crt-stdio-l1-1-0.dll" (attempt 1)
Jul 14 17:24:11.729 INFO Delete: "api-ms-win-crt-string-l1-1-0.dll" (attempt 1)
Jul 14 17:24:11.729 INFO Delete: "api-ms-win-crt-time-l1-1-0.dll" (attempt 1)
Jul 14 17:24:11.730 INFO Delete: "api-ms-win-crt-utility-l1-1-0.dll" (attempt 1)
Jul 14 17:24:11.731 INFO Delete: "bin" (attempt 1)
Jul 14 17:24:11.745 INFO Delete: "blink_image_resources_200_percent.pak" (attempt 1)
Jul 14 17:24:11.746 INFO Delete: "Code.exe" (attempt 1)
Jul 14 17:24:11.764 INFO Delete: "Code.VisualElementsManifest.xml" (attempt 1)
Jul 14 17:24:11.766 INFO Delete: "CodeSignSummary-3e1b90b5-324e-4737-ad8b-0aa13f09a490.md" (attempt 1)
Jul 14 17:24:11.767 INFO Delete: "content_resources_200_percent.pak" (attempt 1)
Jul 14 17:24:11.768 INFO Delete: "content_shell.pak" (attempt 1)
Jul 14 17:24:11.772 INFO Delete: "d3dcompiler_47.dll" (attempt 1)
Jul 14 17:24:11.773 INFO Delete: "ffmpeg.dll" (attempt 1)
Jul 14 17:24:11.774 INFO Delete: "icudtl.dat" (attempt 1)
Jul 14 17:24:11.777 INFO Delete: "libEGL.dll" (attempt 1)
Jul 14 17:24:11.784 INFO Delete: "libGLESv2.dll" (attempt 1)
Jul 14 17:24:11.786 INFO Delete: "locales" (attempt 1)
Jul 14 17:24:11.937 INFO Delete: "msvcp140.dll" (attempt 1)
Jul 14 17:24:11.972 INFO Delete: "natives_blob.bin" (attempt 1)
Jul 14 17:24:11.973 INFO Delete: "node.dll" (attempt 1)
Jul 14 17:24:11.975 INFO Delete: "pdf_viewer_resources.pak" (attempt 1)
Jul 14 17:24:11.976 INFO Delete: "resources" (attempt 1)
Jul 14 17:24:29.160 INFO Delete: "resources" (attempt 2)
Jul 14 17:24:29.361 INFO Delete: "resources" (attempt 3)
Jul 14 17:24:29.813 INFO Delete: "resources" (attempt 4)
Jul 14 17:24:30.614 INFO Delete: "resources" (attempt 5)
Jul 14 17:24:31.864 INFO Delete: "resources" (attempt 6)
Jul 14 17:24:33.666 INFO Delete: "resources" (attempt 7)
Jul 14 17:24:36.116 INFO Delete: "resources" (attempt 8)
Jul 14 17:24:39.317 INFO Delete: "resources" (attempt 9)
Jul 14 17:24:43.368 INFO Delete: "resources" (attempt 10)
Jul 14 17:24:48.369 INFO Delete: "resources" (attempt 11)
Jul 14 17:24:54.420 INFO Delete: "resources" (attempt 12)
Jul 14 17:25:01.621 INFO Delete: "resources" (attempt 13)
Jul 14 17:25:10.072 INFO Delete: "resources" (attempt 14)
Jul 14 17:25:19.873 INFO Delete: "resources" (attempt 15)
Jul 14 17:25:31.124 INFO Delete: "resources" (attempt 16)
Jul 14 17:25:43.924 INFO Delete: "resources" (attempt 17)
Jul 14 17:25:58.375 INFO Delete: "resources" (attempt 18)
Jul 14 17:26:14.576 INFO Delete: "resources" (attempt 19)
Jul 14 17:26:32.626 INFO Delete: "resources" (attempt 20)
Jul 14 17:26:52.627 INFO Delete: "resources" (attempt 21)
Jul 14 17:27:14.678 INFO Delete: "resources" (attempt 22)
Jul 14 17:27:38.879 INFO Delete: "resources" (attempt 23)
Jul 14 17:28:05.331 INFO Delete: "resources" (attempt 24)
Jul 14 17:28:34.131 INFO Delete: "resources" (attempt 25)
Jul 14 17:29:05.382 INFO Delete: "resources" (attempt 26)
Jul 14 17:29:39.183 INFO Delete: "resources" (attempt 27)
Jul 14 17:29:39.184 ERRO Access is denied. (os error 5)

**Comment by mepco-tecture** [comment]
Here you go!

[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2302770/vscode-inno-updater.log)

**Comment by joaomoreno** [comment]
You seem to have #47841.

Please read this comment if you can provide more detail: https://github.com/Microsoft/vscode/issues/47841#issuecomment-393101777

Please read this one to disable background updates: https://github.com/Microsoft/vscode/issues/47841#issuecomment-395017687

Also read this one to provide feedback on our new user setup: https://github.com/Microsoft/vscode/issues/47841#issuecomment-399941682
