### ISSUE TITLE
Unable to toggle wordwrap and minimap when using `"window.titleBarStyle": "custom"`

### ISSUE THREAD

**Issue by AlbertEmil** [Microsoft/vscode#54324]
Running VS Code on Fedora 28:

> Version: 1.25.1
> Commit: 1dfc5e557209371715f655691b1235b6b26a06be
> Date: 2018-07-11T15:40:20.190Z
> Electron: 1.7.12
> Chrome: 58.0.3029.110
> Node.js: 7.9.0
> V8: 5.8.283.38
> Architecture: x64

When adding `"window.titleBarStyle": "custom"` to the User Settings in order to apply theme not only to the application window itself but also to the menu bar and menu entries, toggling the minimap and word wrap does not work (clicking the menu items does not do hide/show minimap or en-/disable word wrap).

This issue might be Electron related. However, toggling e.g. the sidebar still works as expected.

**Comment by yume-chan** [comment]
> **Unable to toggle wordwrap and minimap when using `"window.titleBarStyle": "custom"`**

It's a bad title, the problem actually is **The menu items to toggle word warp and minimap doesn't work when using custom titlebar**

>This issue might be Electron related.

No, it's just the new menu didn't register these actions properly.

**Comment by yume-chan** [comment]
Relates to #54291
