### ISSUE TITLE
Install extension with complete code path dont work

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#54322]
Tried this command in command prompt in windows 10.
> "C:\Program Files\Microsoft VS Code\Code.exe" --install-extension ms-vscode.cpptools

Code although opens but extension never installs.

**Comment by Tyriar** [comment]
You need to run code (code.cmd or code.sh on PATH), running the executable will not run the CLI.

**Comment by shanalikhan** [comment]
If on PATH not available, is there any way to get from API
i have tried to get `process.arg0`

**Comment by Tyriar** [comment]
@shanalikhan I'd say try the `$PATH` and fallback to searching the default install locations for the various packages. There's no API for getting this AFAIK.
