### ISSUE TITLE
Application keeps crashing after opening files

### ISSUE THREAD

**Issue by Redfearn-Justin** [Microsoft/vscode#54329]
Today has been the first day I've had crashing issues with VSC. At first, it crashed when I had about 8 tabs open at the same time ( this I kind of expected). However, about 10+ times after that, after about the second time I "dragged-and-dropped" my files into VSC, in the "Open Files" explorer window, it would crash. This persisted even when I restarted my laptop.

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!
