### ISSUE TITLE
Published extension fails to register where local debugging succeeds

### ISSUE THREAD

**Issue by k2snowman69** [Microsoft/vscode#54332]
- VSCode Version:
Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:43:53.668Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64
- OS Version: Windows 10

Steps to Reproduce:
Part 1 - Published version fails
1. Install [Sortier](https://marketplace.visualstudio.com/items?itemName=Snowcoders.sortier-vscode) extension
2. Open a typescript file and run the `Sortier: Run` action
Expect error message `command 'sortier.run' not found`

Part 2 - Local version works
1. Pull the Sortier-vscode extension from GitHub - https://github.com/snowcoders/sortier-vscode
2. Run npm install
3. Open repo in vscode
4. Run the extension
5. Open a typescript file and run the `Sortier: Run` action
Expect: Same error message as in published package
Actual: Extension runs perfectly fine

My main goal of this issue is to determine what my next steps are to determine why this is failing only from the marketplace. I've tried the following
1. Debugging locally (see part 2 instructions)
2. Publishing the package to a vsix file and then installing that locally (still succeeds)

So is there another option that is closer to the actual marketplace or a way to debug the activation of an extension installed from marketplace locally?

Does this issue occur when all extensions are disabled?: No

**Comment by sandy081** [comment]
@k2snowman69 Does the extension published in the market place and that one you run from sources are of same version?

**Comment by k2snowman69** [comment]
The published extension is the same as the sources. I've also attempted republishing just in case something went wrong in the process. Both are now currently sitting at 1.0.3

**Comment by k2snowman69** [comment]
I also just enabled renovate.js and all dependencies are now up to date.

**Comment by sandy081** [comment]
Do you see the issue even after updating?

**Comment by k2snowman69** [comment]
Yep, still occurs; published 1.0.4 after updating last night.

**Comment by sandy081** [comment]
@k2snowman69 It works for me when I install from Marketplace.

Can you please set the log level to trace and try again and check your window logs?

**Comment by k2snowman69** [comment]
Log level in Visual Studio Code? My extension (which doesn't have logging currently)? And when you say "window logs", did you mean VS code's logs or Window's logs (e.g. event viewer)?

I guess what I am requesting are reproducible instructions so that I can be sure I'm providing the information you are requesting.

**Comment by sandy081** [comment]
@k2snowman69 I mean current window logs in VS Code. You can see it in the output panel. Looks like your extension is not getting activated. After triggering the command, open `Developer: Running Extensions` and see if the extension is running or not.

**Comment by k2snowman69** [comment]
It does seem that the extension is not running for me as it's not listed in the `Developer: Show running extensions` window. I also just installed a clean version of VS Code on a separate machine and installed Sortier from the marketplace, still repros.

**Comment by sandy081** [comment]
@k2snowman69 After the extension is activated in the fresh install.. do you see the extension is shown in Running extensions view?

**Comment by k2snowman69** [comment]
Nope, it does not show up

**Comment by sandy081** [comment]
You have the activation event registered for your command in `package.json` like below:

```json
"activationEvents": [
    "onCommand:commandId"
  ]
```

**Comment by k2snowman69** [comment]
Right now it just activates on everything
```
"activationEvents": [
        "*"
    ],
```

**Comment by sandy081** [comment]
@jrieken Everything looks correct with the extension user using. Still the command invocation says `command not found`.

Any more insights?

**Comment by jrieken** [comment]
Try not using `*` activation, but the `onCommand:myCommandId` - when running the command, we wait for the command-specific activation event but we don't wait for the `*` activation to be finished. /cc @alexandrudima to check if this is intentional or not.

**Comment by alexandrudima** [comment]
@k2snowman69 There is nothing immediately wrong about your extension.

I was able to write one just like yours where the command is ok.

Do you perhaps throw an error from the `activate` function or from code loading? That would lead to the system considering your extension to be not activated.

Otherwise, the following works fine for me:
* your `package.json`
```js
const vscode = require('vscode');

exports.activate = function() {
    vscode.commands.registerCommand('sortier.run', function() {
        console.log(`command running!`);
    });
}
```

The command runs correctly. Can you please create a minimal reproducible extension?

**Comment by k2snowman69** [comment]
Okay so this is actually pretty weird (at least by my understanding) and it came down to `typescript` being in dev-dependencies.

`sortier-vscode` depends on `sortier` which depends on `cosmiconfig` and `typescript` because it's a file formatter. `sortier-vscode` only depends on `cosmiconfig` but to build it needs typescript so I had it in the dev-dependencies.

For some reason when the extension is being packaged it was losing the `typescript` dependency for `sortier` which means when `sortier` was imported it would throw an exception because `typescript` could not be found.

Moving `typescript` from devDependences to dependencies in sortier-vscode did fix the problem however again, this isn't sortier-vscode's dependency, it's sortier's dependency which means this should never have been needed in the first place.

Looking at the extension contents of 1.0.7 (before I added typescript as a direct dependency of sortier-vscode)

.vscode\extensions\snowcoders.sortier-vscode-1.0.7\node_modules

- @snowcoders
  - sortier
    - node_modules
       - cosmiconfig
       - typescript

So the typescript library is there but for some reason it's not actually looking inside of the sortier library to grab it.

Also for a sanity check, I searched `typescript` in the `out` folder of sortier-vscode just to make sure the extension isn't using it directly and I got 0 results.

So yea, there is some sort of bug here but I'm not sure what exactly.

**Comment by alexandrudima** [comment]
I would summarise the problem: the extension, if downloaded from the marketplace, fails to load code **because the `typescript` node module is missing**.

I suspect this might be a problem with `vsce` which looks at which node modules to package when creating the zip and it is possible you are hitting some edge case by having `typescript` be both a top level dev dependency and an inner level dependency.

**Comment by k2snowman69** [comment]
Of all the output generated, this is the only line worth mentioning:
```
D:\Projects\sortier-vscode\node_modules\@snowcoders\sortier\node_modules\typescript
```

Which is correct, `sortier` depends on typescript directly but `sortier-vscode` only needs it for the build

**Comment by joaomoreno** [comment]
I've cloned your repository, ran `npm install` and then:

```
➜  sortier-vscode git:(master) ✗ npm list --production --parseable --depth=9999 | grep typescript
/home/joao/Desktop/sortier-vscode/node_modules/@snowcoders/sortier/node_modules/typescript
/home/joao/Desktop/sortier-vscode/node_modules/typescript-eslint-parser
/home/joao/Desktop/sortier-vscode/node_modules/typescript-eslint-parser/node_modules/semver
/home/joao/Desktop/sortier-vscode/node_modules/typescript
```

I get many more references to typescript, especially that top level one. Are you sure you ran `npm install`?

**Comment by k2snowman69** [comment]
The checked in code has a workaround (mentioned in https://github.com/Microsoft/vscode/issues/54332#issuecomment-408793970) which moved `typescript` from a `dev-dependency` to a `dependency` to get the code working. The reproduction steps you are looking for are:

1. Pull down the repository
2. Move `typescript` from dependencies to dev-dependencies
3. npm install

**Comment by joaomoreno** [comment]
Got it.

> So yea, there is some sort of bug here but I'm not sure what exactly, maybe something specifically to typescript being a sub-dependency but also listed as a dev-dependency? But that wouldn't explain why when loading the sortier library it wouldn't look in it's own node-modules folder.

You are on to something here.

When I move `typescript` to `devDependencies`, I still see it properly included in the VSIX in `node_modules/@snowcoders/sortier/node_modules/typescript`... Don't you see that?

---

I'm confused by your comment:

> For some reason when the extension is being packaged it was losing the typescript dependency for sortier which means when sortier was imported it would throw an exception because typescript could not be found.

On one hand it sounds like you see that the typescript folder is missing. On the other, it sounds like you are intrigued about why sortier can't find the typescript module... So... When you run `vsce ls | grep typescript`, does the `node_modules/@snowcoders/sortier/node_modules/typescript` folder appear in the output?

Finally, I'm pretty sure some code is doing `require('typescript')` from a place where it shouldn't. What is the actual exception which occurs?

**Comment by k2snowman69** [comment]
I also see it properly included in the VSIX in `node_modules/@snowcoders/sortier/node_modules/typescript`, sorry for any confusion.

There are no `require('typescript')` code pieces in my src directory but there are some in my dist output files. Maybe it has to do with my `tsconfig.json`? The fields that would affect this would be
```
        "module": "commonjs",
        "target": "es2015",
        "moduleResolution": "node",
```
But node module resolution is what you would want in this situation... And there is no webpack in this build, just pure `tsc`.

As for getting the actual error, is there a way to install a previous version of an Extension. Now that I've published 1.0.8 with the work around, the only way to reproduce the issue is to install 1.0.7 and run VS Code.

**Comment by joaomoreno** [comment]
OK found the issue: the extension [depends on `typescript-eslint-parser`](https://github.com/snowcoders/sortier/blob/master/package.json#L73), which has a [`peerDependency` to `typescript`](https://github.com/eslint/typescript-eslint-parser/blob/master/package.json#L62). So yeah, `typescript` needs to be a runtime dependency of your module, it can't just be a devtime dependency.

**Comment by k2snowman69** [comment]
`typescript-eslint-parser` is imported by sortier which also has `typescript` in it's dependencies list (see [sortier's package.json](https://github.com/snowcoders/sortier/blob/master/package.json#L73)) so that peer-dependency should be resolved in sortier itself.

**Comment by joaomoreno** [comment]
> `typescript-eslint-parser` [...] also has `typescript` in it's dependencies list

This is incorrect, it only depends on it as a dev and peer dependency. Because of the peer dependency, your extension needs to depend on `typescript` as a regular dependency.

**Comment by k2snowman69** [comment]
I just copied this from Sortier's package.json
```
 "dependencies": {
    "cosmiconfig": "^5.0.5",
    "flow-parser": "^0.78.0",
    "fs": "0.0.2",
    "globby": "^8.0.1",
    "rimraf": "^2.6.2",
    "typescript": "^3.0.0",
    "typescript-eslint-parser": "^18.0.0"
  }
```

I'm fairly sure this means it's a dependency of sortier, not a dev-dependency.

Do you mean adding Typescript as a dev-dependency of `sortier-vscode` overrides `sortier`?

**Comment by joaomoreno** [comment]
10 days ago you did this:

> Moving typescript from devDependences to dependencies in sortier-vscode did fix the problem however again, this isn't sortier-vscode's dependency, it's sortier's dependency which means this should never have been needed in the first place.

This **is** the right fix. Because `sortier-vscode` depends on `typescript-eslint-parser` and `typescript-eslint-parser` has a peer dependency to `typescript`, then `sortier-vscode` **needs** to depend on `typescript`.

**Comment by k2snowman69** [comment]
Sorry, I'm not saying that this isn't the right fix, I'm just trying to understand why it is the right fix. So if I understand your explanation: sortier has both `typescript` and `typescript-eslint-parser` as dependencies as seen in it's [package.json](https://github.com/snowcoders/sortier/blob/master/package.json). But since `typescript-eslint-parser` claims `typescript` as a peer-dependency, it's not sortier who has to resolve this peer dependency but the leaf consumer which in this case is sortier-vscode.

I again want to reiterate `sortier-vscode` does not depend on `typescript-eslint-parser` *directly* (see [package.json](https://github.com/snowcoders/sortier-vscode/blob/master/package.json)). `sortier-vscode` depends on `sortier` which depends on both `typescript-eslint-parser` and `typescript`.

If my summary is true, then the issue is actually with npm as performing an npm install of sortier itself should result in a peer-dependency warning due to typescript-eslint-parser not being resolved. Right now it does not:
```
C:\Temporary>mkdir whee && cd whee
C:\Temporary\whee>npm init
C:\Temporary\whee>npm install @snowcoders/sortier
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN whee@1.0.0 No description
npm WARN whee@1.0.0 No repository field.

+ @snowcoders/sortier@2.1.8
added 159 packages from 126 contributors in 13.544s
[+] no known vulnerabilities found [968 packages audited]


C:\Temporary\whee>
```

If this is your understanding as well I can open an issue with the npm project instead stating that this process should have presented a peer-dependency warning.

**Comment by joaomoreno** [comment]
> I again want to reiterate `sortier-vscode` does not depend on `typescript-eslint-parser` *directly* (see [package.json](https://github.com/snowcoders/sortier-vscode/blob/master/package.json)). `sortier-vscode` depends on `sortier` which depends on both `typescript-eslint-parser` and `typescript`.

Oh, I failed to understand that `vscode-sortier !== sortier`. Sorry!

---

Yeah this sounds like an NPM issue. I moved `typescript` back to `sortier-vscode`'s dev dependencies and deleted `package-lock.json`. After `npm install`, this is the outcome:

```
...
sortier-vscode/node_modules/@snowcoders/sortier/node_modules/typescript
sortier-vscode/node_modules/typescript-eslint-parser
...
```

And no top level `typescript` module. So, `typescript-eslint-parser` can't use `typescript`.

I would file it as an issue to NPM.
