### ISSUE TITLE
Add a command to enter a workspace without window reload

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#54335]
This will help extensions like LiveShare that create ad-hoc workspaces to perform the switch from empty window to workspace without a window reload much faster.

**Verify:**
* write an extension (hello world is fine)
* craft any workspace file on disk
* add code like this: `vscode.commands.executeCommand('_workbench.enterWorkspace', vscode.Uri.file('<path to workspace file'));`
* you should enter this workspace without a window reload

**Comment by isidorn** [comment]
The new workspace seems to be opened fine, however the extension host is not started properly.
Follow your steps from above and wait 10 seconds and get an error -> reopening and assigning to August

![screen shot 2018-07-31 at 15 47 31](https://user-images.githubusercontent.com/1926584/43463548-1ef485a0-94d9-11e8-86cf-dea0aea42acc.png)

**Comment by bpasero** [comment]
I now this used to work when I tested, so I speculate @sandy081 your changes might have caused this maybe?

**Comment by bpasero** [comment]
Very likely same symptoms as https://github.com/Microsoft/vscode/issues/55899, I see the extension host restarts but it is stopped in debug break.

**Comment by weinand** [comment]
Verified on macOS, Windows, and linux.
