### ISSUE TITLE
用处模板上下滚动文本时卡顿

### ISSUE THREAD

**Issue by AetheWu** [Microsoft/vscode#54331]
Issue Type: <b>Bug</b>

用vscode打开源代码，在触摸板上双指上下滑动时，文本滚动卡顿，必然重现；滑动操作在其他应用中无此bug。

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (2.81GB free)|
|Process Argv|D:\app\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vsc-material-theme|Equ|2.3.0
vscode-language-pack-zh-hans|MS-|1.25.3
python|ms-|2018.6.0
cpptools|ms-|0.17.6
material-icon-theme|PKi|3.5.1
python|tht|0.2.3

(1 theme extensions excluded)

</details>

**Comment by yume-chan** [comment]
Please try if `"window.smoothScrollingWorkaround": true` config makes things better.

**Comment by Tyriar** [comment]
The machine translation isn't very good for this so we need some more details.

**Comment by yume-chan** [comment]
> It's not smooth when scrolling with two-finger scrolling on touchpad

@Tyriar there is a typo in the title so I understand why machine translation doesn't work.

**Comment by AetheWu** [comment]
i have tried that as you suggest,but it doesn't work. 吴衡 邮箱：wzh942633545@gmail.com 签名由 网易邮箱大师 定制 在2018年07月16日 14:14，Simon Chan 写道： Please try if "window.smoothScrollingWorkaround": true config makes things better. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by gpenghe** [comment]
Let me try to translate it:

Original:

>>用vscode打开源代码，在触摸板上双指上下滑动时，文本滚动卡顿，必然重现；滑动操作在其他应用中无此bug。


My Translation:

>>When opening source code with VS Code and scroll it with the Trackpad, the scrolling is jerky/laggy. This is repeatable. Other applications don't have this issue.
