### ISSUE TITLE
VS Code won't fill screen on re-maximize with custom title bar and menus

### ISSUE THREAD

**Issue by ieu** [Microsoft/vscode#54333]
- VSCode Version: 1.24, 1.24.1, 1.26.0-insider
- OS Version: Windows 10 1803

Steps to Reproduce:

1. Set window.titleBarStyle to "custom"
2. Maximize VS Code
3. Restore VS Code
4. Maximize VS Code

![Imgur](https://i.imgur.com/jxnpjBq.gif)

**Comment by TomSputz** [comment]
Duplicate of #52265 - this is an issue with electron that has been explored in https://github.com/electron/electron/issues/12971 , and does have a workaround, though it would need some testing to implement is case it created issues with any other code (based on event listeners)

**Comment by ieu** [comment]
Duplicate
