### ISSUE TITLE
files.exclude使用正则表达式匹配字符时出现问题

### ISSUE THREAD

**Issue by xiaozhigithub** [Microsoft/vscode#54337]
Issue Type: <b>Bug</b>

首先我写了如下的配置文件，用于排除对我没用的BSP(板级支持包)(frist i wrote a setting.json like below, to remove useless BSP(board sport package) for me):
```` json
"files.exclude": {
        "**/bsp/l*":true,
        "**/bsp/m*":true,
        "**/bsp/n*":true,
        "**/bsp/c*":true,
        "**/bsp/i*":true,
        "**/bsp/a*":true,
        "**/bsp/b*":true,
        "**/bsp/C*":true,
        "**/bsp/d*":true,
        "**/bsp/f*":true,
        "**/bsp/g*":true,
        "**/bsp/h*":true,
        "**/bsp/p*":true,
        "**/bsp/r*":true,
        "**/bsp/q*":true,
        "**/bsp/t*":true,
        "**/bsp/x*":true,
        "**/bsp/e*":true,
        "**/bsp/u*":true,
        "**/bsp/w*":true,
        "**/bsp/z*":true,
        "**/bsp/sa*":true,
        "**/bsp/se*":true,
        "**/bsp/si*":true,
        "**/bsp/stm32l*":true,
        "**/bsp/stm32h*":true,
        "**/bsp/stm32f0*":true,
        "**/bsp/stm32f1*":true,
        "**/bsp/stm32f2*":true,
        "**/bsp/stm32f4*":false,
        "**/bsp/stm32f7*":true,
        "**/bsp/stm32f107":true,
        "**/bsp/stm32f10x-*":true,
        "**/bsp/stm32f40*":true,
        "**/bsp/stm32f41*":true,
        "**/bsp/stm32f42*":true,
    },
````
然后这么长看起来就很麻烦，于是简化了一下(then i want make it simple)
```` json
"files.exclude": {
        "**/bsp/[^s]*": true,
        "**/bsp/s[^t]*": true,
        "**/bsp/stm32[^f]*": true,
        "**/bsp/stm32f[^1]*": true,
        "**/bsp/stm32f1*L": true,
        "**/bsp/stm32f1*7": true,
    },
````
简化完发现这样写的表达式虽然简单了一些但是有一些问题出现了，intellisence貌似无法确定我的头文件到底是在哪一个BSP里面，当我按下F12，文件追踪自动打开了一个在上面的配置里面应该已经忽略了的文件(After doing this, I found that all the matched options disappeared in the left resource manager. But some problems happened, it seems the intellisence don't know whereis my headers in.When I pressing F12, the vscode may open a file located on the directions that should been ignore.)
实际代码在这个[Github仓库](https://github.com/RT-Thread/rt-thread) (the code I'm browsing now is located in this [github repo](https://github.com/RT-Thread/rt-thread))
I hope it's useful for fix this bug.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.92GB (0.87GB free)|
|Process Argv|D:\ProgramFiles(green)\VSCode-win32-x64-1.24.1\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
easy-cpp-projects|ACh|1.4.2
path-intellisense|chr|1.4.2
python|cod|0.9.0
arm|dan|0.2.0
code-runner|for|0.9.3
8051|jun|0.1.0
cortex-debug|mar|0.1.21
python|ms-|2018.6.0
cpptools|ms-|0.17.6

</details>

**Comment by xiaozhigithub** [comment]
。。。算了反正都忘了翻标题，，发个中文版的好了，第一次提交issue，机翻还有排版什么的请见谅，本来有个这样的配置文件setting.json

> "files.exclude":  {
> "/bsp/l*":true,
> "/bsp/m*":true,
> "/bsp/n*":true,
> "/bsp/c*":true,
> "/bsp/i*":true,
> "/bsp/a*":true,
> "/bsp/b*":true,
> "/bsp/C*":true,
> "/bsp/d*":true,
> "/bsp/f*":true,
> "/bsp/g*":true,
> "/bsp/h*":true,
> "/bsp/p*":true,
> "/bsp/r*":true,
> "/bsp/q*":true,
> "/bsp/t*":true,
> "/bsp/x*":true,
> "/bsp/e*":true,
> "/bsp/u*":true,
> "/bsp/w*":true,
> "/bsp/z*":true,
> "/bsp/sa*":true,
> "/bsp/se*":true,
> "/bsp/si*":true,
> "/bsp/stm32l*":true,
> "/bsp/stm32h*":true,
> "/bsp/stm32f0*":true,
> "/bsp/stm32f1*":true,
> "/bsp/stm32f2*":true,
> "/bsp/stm32f4*":false,
> "/bsp/stm32f7*":true,
> "/bsp/stm32f107":true,
> "/bsp/stm32f10x-*":true,
> "/bsp/stm32f40*":true,
> "/bsp/stm32f41*":true,
> "/bsp/stm32f42*":true,
>  },

 觉得麻烦然后改造了一下

> "/bsp/[^s]*": true,
> "/bsp/s[^t]": true,
> "**/bsp/stm32[^f]": true,
> "/bsp/stm32f[^1]*": true,
> "/bsp/stm32f1L": true,
> "**/bsp/stm32f17": true,

看起来没有问题，重启之后追踪变量就出问题了，能追到左边资源管理器没有的文件里面去，也就是说这样匹配只在资源管理器里面生效了，intellisence根本没有理会这种形式的表达式

**Comment by yume-chan** [comment]
1. issue 标题是可以修改的 (issue title can be edited)
2. issue 内容是可以修改的 (issue content can be edited)
3. 在代码块上下加上四个反点号可以避免格式化，还可以代码高亮 (use four backticks to provide code formatting and highlighting)

比如输入这样：(e.g. if you type)
<pre>
```` json
{
    "files.exclude": {
        "/bsp/[^s]": true
    }
}
````
</pre>

得到的是 (and you get)

```` json
{
    "files.exclude": {
        "/bsp/[^s]": true
    }
}
````

反正我还是看不出你的配置长成什么样 (anyway I still don't understand your settings)

4. 我看你的描述似乎 IntelliSense 是 cpptools 扩展提供的，麻烦你参阅 [扩展文档](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/Getting%20started%20with%20IntelliSense%20configuration.md) 查看如何配置 IntelliSense (from your description I guess you are working on a C project and the IntelliSense is provided by the cpptools extension, please refer to their documentation to configure IntelliSense)

5. 关于 cpptools 扩展没有读取 `files.exclude` 设置的问题，你可以在 cpptools 的 repo 发一个 feature request (If you are complaining about the cpptools doesn't conform your `files.exclude` setting, you can send a feature request to there)

**Comment by xiaozhigithub** [comment]
十分感谢大佬，我还以为会沉了没人理的。。。issue内容格式已改，标题暂时没想好，我发现确实是我不会用造成的，具体在[这里](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/IntelliSense%20engine.md)有介绍，根据intellisence engine的介绍，我应该设置两个变量includePath和browse path，然而只设置了一个includePath，browse path处于默认状态所以直接递归把所有文件都纳入了intellisence感知范围，第一个配置能正确跳转到指定的BSP目录应该是intellsence简单的判断了一下file.exclude里面的内容，在内容解析上面没有做完全，所以才会出现我这个问题，所以好像我确实需要往cpptools的repo里面发一个issue。。。

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-cpptools
