### ISSUE TITLE
feat: tab completion for everything

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#54343]
Hi, my suggestion is to improve or add another configuration for `"editor.tabCompletion": true,` to complete everything not only snippets.

As an example:
1. I disable quick suggestions with `"editor.quickSuggestions": false,`
2. I enable tab completion with `"editor.tabCompletion": true,`
3. I open a JS file and write `const comp = 'my component';`
4. I write `if (co` and when I press tab it will complete to `comp` automatically

Why?
I feel quick suggestions are too noisy and if you want to disable them in some situations you still are triggering it with `CTRL + SPACE`, but it can be avoided if I have the ability to complete by pressing TAB.

I don't know if I formed it correctly, but my suggestion is to just simply pick first suggestion which matches with TAB instead of triggering quick suggestion and doing the same thing.

**Comment by svipben** [comment]
Also, about configuration instead of creating new one or by letting the user decide what they want it can be changed to a string like this:

For snippets: `snippets` | `onlySnippets`
For words: `code` | `words` | `onlyCode` | `onlyWords`
For everything: `all` | `true`
For disable: `none` | `off` | `false`

My opinion best would be: `editor.tabCompletion: ['snippets', 'words', 'all', 'off']`
And to keep default as it was it can be default to `snippets`

**Comment by svipben** [comment]
I hidded quick suggestions widget in Developer Tools to show you how it looks like to complete code with TAB.

![ezgif-2-79604c48cc](https://user-images.githubusercontent.com/10441177/42734660-823050b2-8850-11e8-86a5-6a10bda9e4ad.gif)

**Comment by svipben** [comment]
- If there's no such suggestion it simply uses TAB as default (space defined in User Settings).
- If it's already completed it uses TAB as default (space defined in User Settings).
- If it wasn't completed but it matches the same word for e.g. `IS_DEVELOPMENT` it uses TAB as default (space defined in User Settings).

**Comment by svipben** [comment]
@jrieken I tried to create this feature as a extension, but I couldn’t get suggestions list by string. I didn’t find any API in ‘vscode.languages’, maybe I was doing something wrong? Or it’s impossible to create such thing as a extension? Maybe it should go as a extension instead of in vscode core?

Thanks!

**Comment by jrieken** [comment]
It is tricky... There are [API commands](https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands) which allows you trigger other completion providers.

**Comment by nealot** [comment]
This could also be useful for providing auto-completion for some spelling extensions.

**Comment by jrieken** [comment]
If you wanna make a PR, please go ahead. It's not trivial but should be manageable. You should start by adding a command that triggers and accept a completions. For that add a new method like, similar to [`SuggestController#trigger`](https://github.com/Microsoft/vscode/blob/ef24ce4431f13c63e0ce09634acd266f5f977e28/src/vs/editor/contrib/suggest/suggestController.ts#L270). 

Basically what you want is

1. [trigger suggest](https://github.com/Microsoft/vscode/blob/ef24ce4431f13c63e0ce09634acd266f5f977e28/src/vs/editor/contrib/suggest/suggestModel.ts#L352) from the controller (new function like `trigger`) in a way that prevents the widget [from showing](https://github.com/Microsoft/vscode/blob/ef24ce4431f13c63e0ce09634acd266f5f977e28/src/vs/editor/contrib/suggest/suggestController.ts#L110) (add some kind of flag to trigger and the "did suggest"-event)
2. locally (in that function) wait for the "did suggest"-even, check for the best [completion item](https://github.com/Microsoft/vscode/blob/ef24ce4431f13c63e0ce09634acd266f5f977e28/src/vs/editor/contrib/suggest/suggestModel.ts#L31-L32), and if there is one invoke the [`_onDidSelectItem`](https://github.com/Microsoft/vscode/blob/ef24ce4431f13c63e0ce09634acd266f5f977e28/src/vs/editor/contrib/suggest/suggestController.ts#L198) method

I might have missed some critical details but in essence that's all it takes and how the data flows.

**Comment by svipben** [comment]
@jrieken thank you very much, I will try to do it.

P.S. Your links are broken 😢

**Comment by jrieken** [comment]
fixed the links above

**Comment by jrieken** [comment]
@svipben Just fyi that #28215 might actually happen this month. I took another look and I have hacked something together and works reasonable well...

**Comment by svipben** [comment]
@jrieken Very good, I'm really happy, so then we can close this issue. Maybe you can show gif how it looks, I'm really curious 😄

**Comment by jrieken** [comment]
@svipben see https://github.com/Microsoft/vscode/issues/28215#issuecomment-422310232
