### ISSUE TITLE
Do not add file extension to new file if specified filename contains one already

### ISSUE THREAD

**Issue by lukas-lang** [Microsoft/vscode#54347]
Consider the following workflow:

* Create a new file (`CTRL+N`)
* Open save dialog (`CTRL+S`)
* Type a name with an extension specified (e.g. `test.cpp`)
* Choose a non-matching file type (e.g. the default, "Plain Text") which is not associated to the file extension from the previous step
* Save the file (`ENTER`)

Now, the current behavior is: The created file gets the extension associated to the file type appended. In the example above, the file is saved as `test.cpp.txt`

Suggested behavior: Do not add the extension if one is specified, i.e. the file should be saved as `test.cpp`

Other possibility: Change the default file type to "All files". In this case, the behavior with no specified extension would need to be changed such that `.txt` is appended (currently, an error is generated)

**Comment by isidorn** [comment]
This is native OS behavior and there is nothing we can do about it.
For me this works fine in win10, os x. Not sure which OS you are using but file na issue against that OS please.

**Comment by lukas-lang** [comment]
I'm not sure I get what you mean - this happens for me on Windows 10, exactly as described in the issue.

As for the "this is OS behavior": I can't judge this, but whatever it is, Notepad++ has no issues with the same scenario: In Notepad++, the default extension is also `.txt`, but if another extension is specified, `.txt` is not appended

**Comment by isidorn** [comment]
If this does not happen for other apps then this is an Electron issue, can you please file it in their repository. Thanks
https://github.com/electron/electron
