### ISSUE TITLE
Show custom title when moving mouse to the top even in fullscreen mode

### ISSUE THREAD

**Issue by MDKi** [Microsoft/vscode#54340]
- VSCode Version: 1.26.0-insider
- OS Version: macOS Mojave 10.14 Beta (18A326h)

Steps to Reproduce:

1. Click the green button to get into fullscreen mode.
2. Slide your cursor over to the top to show the menu bar.

<img width="1680" alt="screen shot 2018-07-15 at 05 45 35" src="https://user-images.githubusercontent.com/32469869/42732200-53e42cf4-87f3-11e8-9f59-9e7503bd0bd2.png">

Notice that, while not in fullscreen mode, it is always dark regardless of system settings as well, but that's expected as it changes if you change the color theme.

<img width="1680" alt="screen shot 2018-07-15 at 05 45 23" src="https://user-images.githubusercontent.com/32469869/42732201-541599ce-87f3-11e8-8d14-28324c39c7af.png">

Does this issue occur when all extensions are disabled?: Yes/No
Yes.

**Comment by MDKi** [comment]
Can confirm this also affects VSCode Version 1.24.0-exploration

**Comment by Tyriar** [comment]
Only the fullscreen title bar is a light color? I would have expected this to be handled my macOS :confused:

**Comment by MDKi** [comment]
This has been fixed on PR #59742, closing.
