### ISSUE TITLE
Folding (Collapse/Expand) blocks code, better visual ?

### ISSUE THREAD

**Issue by BlinkSun** [Microsoft/vscode#54351]
![image](https://user-images.githubusercontent.com/7069760/42737394-813cbe08-8840-11e8-961b-4921bc02317a.png)

**_Collapse_**, when a language uses brackets to delimit blocks code, ... 
well you know, there are **two** types of coders :wink:

_Type 1:_
```c#
void Method() {­
   for(;;) {
      break;
   }
}
```

_Type 2:_
```c#
void Method()
{
   for(;;)
   {
      break;
   }
}
```
:sweat_smile:

No matter how we write them, when we collapse, we would like them to be visually on one line, as on my screenshot, we can see the ending bracket on a new line.

Would it be possible to make, when we collapse a block, that the end of the only line look like this, whenever the way we write block's brackets:
```c#
void Method() {...}
```
And the collapse/expand marks `[-]` `[+]` should be always at the same line of the method, not at the same line of the first opening brackets !

**_NB:_**
I never saw in my life a block like this :sweat: :
```c#
void Method() {
   for(;;) {
      break;}}
```
... unfortunately, it's the only way to get the visual collapse that I'm looking for !

**Comment by BlinkSun** [comment]
Hey @aeschli , any comment ? :smile: ...
What kind of _bracketer_ are you when you code ? :thinking:

**Comment by aeschli** [comment]
The request to place the end bracket on the first line is #3352.
Your request adds the suggestion to then also show an opening bracket.

**Comment by aeschli** [comment]
Closing as dup of #3352.
