### ISSUE TITLE
A new feature which I really dislike: cursor position updates when clicking to focus the VSCode window

### ISSUE THREAD

**Issue by liranh85** [Microsoft/vscode#54358]
Issue Type: <b>Bug</b>

I'll start by saying that this is in my opinion hands down the best IDE for Front End Development. Keep up the amazing work!

Now to the problem. You've recently changed the behaviour for when clicking on the VSCode window to focus it. It used to simply focus, with the cursor position remaining where it previously was. Since around two months ago (maybe less), it now not only focuses the window, but also changes the cursor position to exactly where I clicked in the window. This is really annoying, as it makes me forget where I was in my code prior to switching to a different app.

Please either reverse this to the previous behaviour, or at least add make this behaviour configurable.

Thanks!

Liran

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU           W3565  @ 3.20GHz (8 x 3200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
insertnumbers|Asu|0.9.1
indent4to2|Com|0.1.2
vscode-eslint|dba|1.4.12
vscode-quick-select|dba|0.2.5
beautify|Hoo|1.3.2
velocity|luq|0.7.1
rainbow-csv|mec|0.4.2
convert-css-in-js|pau|1.1.3
code-settings-sync|Sha|3.0.0
vscode-react-native|vsm|0.6.12
vscode-import-cost|wix|2.7.2
change-case|wma|1.0.0

</details>

**Comment by Tyriar** [comment]
Adding this setting will go back to the old behavior `"window.clickThroughInactive": false`
