### ISSUE TITLE
Incorrect Indentation

### ISSUE THREAD

**Issue by jeffsaremi** [microsoft/vscode#54352]
- VSCode Version: 1.25.0
- OS Version: Windows 10

The following are a few of the instances i noticed incorrect indentation. I hope i don't have to debate why they're incorrect:

1. case xxxx:
The next line starts immediately under 'c' and not indented.

2. object.function(param1,
The next line starts with no indentation

3.   this.function(param1, 
    param2 );
Pressing enter after the semicolon starts the next line right under 'p' which is incorrect. Indentation is not reset here.

4. if(some condition)
Next line is not indented if I don't use paranthesis. With paranthesis the indentation is correct.

5. for(...)
Same as for "if". If I don't use paranthesis the indentation is not happening otherwise it's ok

**Comment by mjbvz** [comment]
When does the incorrect indention occur? After format or just when typing?

**Comment by touho** [comment]
To explain step 4:

With parenthesis automatic indentation works:
```
if (hello === 'world') {
    helloWorld();
}
```

Without parenthesis automatic indentation doesn't work:
```
if (hello === 'world')
helloWorld();
```

Fixing of this bug would possibly be the lowest hanging fruit to improve coding experience in VS Code.

**Comment by mjbvz** [comment]
Closing due to lack of further user interest expressed in this issue over the past two plus years

(also please open separate issues for problems like this in the future to make them more discoverable)
