### ISSUE TITLE
vscode can't format python file

### ISSUE THREAD

**Issue by ladyrick** [Microsoft/vscode#54356]
Issue Type: <b>Bug</b>

I have installed the python ext, and `pip install autopep8`.
Then when I format the code with `Alt + Shift +F` or right click and select "format file", vscode just shows **Formatting with autopep** but doing nothing to my code.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (10.60GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.25.3
python|ms-|2018.6.0

</details>

**Comment by yume-chan** [comment]
Since it's caused by the Python extension, please report your issue to [Microsoft/vscode-python](https://github.com/Microsoft/vscode-python/issues) so they can better help you.

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-python/
