### ISSUE TITLE
checkForUpdates for extension should be controlled concurrency

### ISSUE THREAD

**Issue by axetroy** [Microsoft/vscode#54350]
I found that once I check the extension updates.

VSCode will be stuck for a few seconds.

And I did not found the `checkForUPdates` logic in here

https://github.com/Microsoft/vscode/blob/fec5cf6f43406264a131fc8ee5e05b7918c5dee0/src/vs/workbench/parts/extensions/common/extensions.ts#L93

But I think It should be concurrent.

If I got many extension (20+), trigger the action to check update. It will send 20+ times request.

I think It's why VSCode will be stuck at that moment.

If as I say. **I think we should control the number of concurrencies to improve performance.**

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_1466726|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.27
vscode-auto-schema|axe|0.1.0
vscode-gpm|axe|0.23.0
thrift|cdu|0.0.1
vsc-material-theme|Equ|2.3.0
prettier-vscode|esb|1.5.0
php-intellisense|fel|2.3.3
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
terminal|for|0.0.10
local-history|gay|0.0.3
vscode-nginx-conf-hint|han|0.1.0
vue-snippets|hol|0.1.8
intellij-idea-keybindings|k--|0.2.24
vscode-language-pack-ja|MS-|1.25.2
vscode-language-pack-zh-hans|MS-|1.25.3
python|ms-|2018.6.0
Go|ms-|0.6.84
vetur|oct|0.12.5
material-icon-theme|PKi|3.5.1
nginx-formatter|ray|0.0.2
code-settings-sync|Sha|3.0.0
vscode-nginx|sha|0.5.0
gitconfig|sid|1.0.1
code-spell-checker|str|1.6.10
open-in-browser|tec|1.1.0
vscode-todo-highlight|way|0.5.12
json-helper|zho|1.3.2

</details>

**Comment by ramya-rao-a** [comment]
@sandy081 Related to #54041?

**Comment by sandy081** [comment]
Yes.
