### ISSUE TITLE
Terminal: Text does not wrap properly in DOM mode

### ISSUE THREAD

**Issue by jtanx** [Microsoft/vscode#54368]
- VSCode Version: 1.25.1
- OS Version: Windows 10 1703

Steps to Reproduce:

1. Open a file in `less` that has a line long enough that it will wrap, e.g.:

   ```
   ABCDEFGHIJKLMNOPQRTSUVWXYZ ABCDEFGHIJKLMNOPQRTSUVWXYZ ABCDEFGHIJKLMNOPQRTSUVWXYZ ABCDEFGHIJKLMNOPQRTSUVWXYZ ABCDEFGHIJKLMNOPQRTSUVWXYZ ABCDEFGHIJKLMNOPQRTSUVWXYZ ABCDEFGHIJKLMNOPQRTSUVWXYZ ABCDEFGHIJKLMNOPQRTSUVWXYZ ABCDEFGHIJKLMNOPQRTSUVWXYZ ABCDEFGHIJKLMNOPQRTSUVWXYZ ABCDEFGHIJKLMNOPQRTSUVWXYZ ABCDEFGHIJKLMNOPQRTSUVWXYZ ABCDEFGHIJKLMNOPQRTSUVWXYZ
   ```

2. Observe that in canvas mode, it wraps properly. But in DOM mode, it does not wrap properly - the start of the continuation is as if it were still in canvas mode, but because of a differing text width in dom mode, the first line gets cut off too soon, and the wrapped part doesn't show this.

Canvas mode:
![image](https://user-images.githubusercontent.com/5137410/42748530-dcbfed48-8923-11e8-99e0-14da36aa1591.png)

DOM mode:
![image](https://user-images.githubusercontent.com/5137410/42748556-f5f4f56a-8923-11e8-943e-b4a129d16937.png)

   

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/51479
