### ISSUE TITLE
Javascript Object Outline Tree View

### ISSUE THREAD

**Issue by tianenchong** [Microsoft/vscode#54364]
Issue Type: <b>Feature Request</b>

Outline is working well relatively for a flat structure.

However, in the case of javascript object, this need to be expanded to a tree view. E.g. In a Javascript object that contains property 'A' and property 'B', both properties contain function 'C', the current outline feature only lists 1 of the 2 function 'C's in the properties. The outline also fail to list property 'A' and property 'B'.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.16299

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/25694 to track this upstream
