### ISSUE TITLE
Crashes when managing extensions

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#54375]
Issue Type: <b>Bug</b>

Code seems to get stuck in a loop and ultimately crashes. I tried breaking the in debugger during the loop and it looks like it was constantly trying to update the new breakcrumbs UI

VS Code version: Code - Insiders 1.26.0-insider (6babef94104b27b252929324aa3c2d69cd38e9f2, 2018-07-16T05:18:37.865Z)
OS version: Windows_NT x64 10.0.17713

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (13.02GB free)|
|Process Argv|C:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by jrieken** [comment]
do you still have a stack trace or screen shot from the debugger?

**Comment by jrieken** [comment]
never mind, I can reproduce
