### ISSUE TITLE
bind command(workbench.action.files.openFile) failed

### ISSUE THREAD

**Issue by monadbobo** [Microsoft/vscode#5437]
- VSCode Version: 1.0.0
- OS Version: 10.11.4

I bind "ctrl+c ctrl+f" bind workbench.action.files.openFile, but after i set this command, using ctrl+c ctrl+f , vscode show me this message "No handler found for the command: 'workbench.action.files.openFile'. An extension might be missing an activation event."

**Comment by dbaeumer** [comment]
@bpasero starting with you. Not sure if the is @alexandrudima.

**Comment by bpasero** [comment]
Please use `workbench.action.files.openFileFolder` on Mac !

**Comment by martynchamberlin** [comment]
I was about to be seriously bummed about this until I realized that what I [was looking for](https://code.visualstudio.com/docs/customization/keybindings#_navigation) was `workbench.action.quickOpen`.

**Comment by mmathys** [comment]
It's ⇧⌘P on Mac.
