### ISSUE TITLE
No "Static Website (preview)"  (VS Code docs refer here)

### ISSUE THREAD

**Issue by SeaDude** [Microsoft/vscode#54376]
Please search existing issues to avoid creating duplicates.
I did. No results

Also please test using the latest insiders build to make sure your issue has not already been fixed: https://code.visualstudio.com/insiders/
Just updated today. 

Use Help > Report Issue to prefill these.
- VSCode Version: 1.25.1
- OS Version: Ubuntu 17.04 LTS

**Steps to Reproduce:**

1. Follow VS Code "Static Website" docs here: https://code.visualstudio.com/tutorials/static-website/getting-started
2. Step 3 "Create Storage Account" https://code.visualstudio.com/tutorials/static-website/create-storage#_create-your-storage says to select "Static Website (preview)" under the Azure Portal/Azure Storage/Settings area. 
3. This option does not exist in Azure Portal/Azure Settings area. Nor any area in Azure Storage.

**Desired Results:**

Please update docs and advise how to deploy a Static Website using VS Code + Azure Storage. 

Thank you.

**Comment by fiveisprime** [comment]
Hi and thanks for reporting this.

Make sure that you choose general purpose v2 (GPv2) when creating the account. I'll update the tutorial to clarify this.

**Comment by gregvanl** [comment]
![image](https://user-images.githubusercontent.com/12818376/42773084-153ffd04-88e1-11e8-98fe-e1b01052402e.png)

**Comment by gregvanl** [comment]
Documentation updated with https://github.com/Microsoft/vscode-docs/commit/da73b25ddc69d8cd2ea63a9f2c96b2c90e772318

**Comment by SeaDude** [comment]
Aha. Thanks for the prompt response. I'll revisit these instructions tonight and give them a try. 

Take care

**Comment by SeaDude** [comment]
Worked like a charm. Thank you.
