### ISSUE TITLE
Intellisense for node.js api is not working

### ISSUE THREAD

**Issue by arslan0tahir** [Microsoft/vscode#54371]
Issue Type: <b>Bug</b>

Intellisense for node.js api is not working e.g. 

const os = require('os');
os.           is not resolving relevant functions available in its documentation

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Quad  CPU   Q9450  @ 2.66GHz (4 x 2660)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Memory (System)|3.99GB (1.24GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
JavaScriptSnippets|xab|1.7.0

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by mjbvz** [comment]
Node intellisense is powered by typings files automatically downloaded by npm. It looks like that is failing for you.

Please try collecting the log for typings installation :

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a folder with a `ti-xxxx.log` file in it

That log file contains typing install information. It should indicate why the typings for node were not properly downloaded. Please share the `ti` file

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by ayyash** [comment]
@mjbvz if Typescript in the command panel doesn't come up, what do u think went wrong? (I updated typescript, after which all intellisense went broken, I know I'm cha nging the subject, but i'm holding to any glimpse of hope)

**Comment by mjbvz** [comment]
@ayyash Make sure that either a javascript or typescript file is active. The command will only show up when you are in one of those files
