### ISSUE TITLE
Settings only partialy rendered on inital open

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#54377]
OS X, latest insiders

Preferences > settings > notice how the new settings UX is only partialy rendered. Additional parts of the ux get rendered as I scroll through them

![screen shot 2018-07-16 at 09 36 06](https://user-images.githubusercontent.com/1926584/42747237-e449eaca-88db-11e8-89d2-ea92fea063f5.png)

**Comment by misolori** [comment]
Also happening on search. This makes the entire Settings page unusable.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/35271042/42768962-b7b5ac34-88d5-11e8-9e45-f03b09be7673.gif)

**Comment by roblourens** [comment]
Fixed in https://github.com/Microsoft/vscode/pull/54435
