### ISSUE TITLE
 [Loc] Request to add Belarusian (Tarask) (be@tarask) language to Transifex VS Code project 

### ISSUE THREAD

**Issue by janbaltus** [microsoft/vscode#54388]
See guidance at https://github.com/Microsoft/Localization/wiki/How-to-request-a-new-UI-language-for-VS-Code-project.
We need 3 contributors vote here before enable the language in Transifex.
Please vote here by pasting you Transifex account here. For example, https://www.transifex.com/user/profile/12345

**Comment by Slauta** [comment]
https://www.transifex.com/user/profile/Slauta/

**Comment by danyeh** [comment]
We don't have plan to enable additional language for VSCode in MLCP in near term. Hence close the request here.
New request should be logged in [Localization Community Repo](https://aka.ms/vscodeloc)
