### ISSUE TITLE
$SSH_AUTH_SOCK not respected

### ISSUE THREAD

**Issue by Yajo** [Microsoft/vscode#54380]
Issue Type: <b>Bug</b>

I'm on GNOME, Linux. Automatically it starts an SSH agent when I start my session, but that's not being respected in vscode since the last version.

Prior to this version, I opened the integrated terminal and this worked fine:

    git pull

With current version, it asks for the `id_rsa` key passphrase.

A workaround is to open settings and add this:

```json
    "terminal.integrated.env.linux": {
        "SSH_AUTH_SOCK": "/run/user/1000/keyring/ssh"
    },
```

It does the trick, but I don't understand why this stopped working 😕

Worst of all, using integrated version control panel doesn't work now due to this same problem:

![captura de pantalla de 2018-07-16 09-11-07](https://user-images.githubusercontent.com/973709/42748488-4879faf2-88d8-11e8-9dec-00ab21aea8f7.png)

Thanks!

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:40:20.190Z)
OS version: Linux x64 4.17.3-200.fc28.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX-7500 Radeon R7, 10 Compute Cores 4C+6G (4 x 2095)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Load (avg)|5, 4, 3|
|Memory (System)|14.63GB (1.39GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by joaomoreno** [comment]
So whats the value of `process.env['SSH_AUTH_SOCK']` if you type that in the Devtools Console? <kbd>F1</kbd>, `Developer: Toggle Developer Tools`

**Comment by joaomoreno** [comment]
> Automatically it starts an SSH agent when I start my session

Where is that configured? `.bashrc`?

**Comment by Yajo** [comment]
It's defined somehow in the whole GNOME session, since it is not present when logging in through tty.

Not sure what's happening, but as of today, vscode is getting that env variable correctly :confused: :question: 

I'm gonna close, and I will reopen if it happens again, thanks!
