### ISSUE TITLE
双击标签页最大化

### ISSUE THREAD

**Issue by hurrilycong** [Microsoft/vscode#54381]
双击标签页时，能够将侧边栏隐藏，或显示出来

**Comment by chemzqm** [comment]
你可以自己写插件实现

**Comment by V0idk** [comment]
双击标签页是固定标签的功能. 这样打开文件不会覆盖原来标签

**Comment by hurrilycong** [comment]
是的，是我考虑不周，只是左侧边栏必须手动点击才能隐藏，或者左侧边栏打开文件后自动隐藏，鼠标左滑再显示出来。



发自我的小米手机
在 V0idk <notifications@github.com>，2018年7月19日 下午5:10写道：

双击标签页是固定标签的功能. 这样打开文件不会覆盖原来标签

**Comment by alexandrudima** [comment]
I am sorry, I'm going to have to ask that you recreate the issue in English.
