### ISSUE TITLE
Failure to update "Unable to Execute file"

### ISSUE THREAD

**Issue by HarryAdney** [Microsoft/vscode#54389]
Version 1.26.0 Insiders version
upgrade notice from within VScode "Restart to Update..."

Error message:

C:\Users\*********\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe

Create Process Failed; code 2
The system cannot find the file specified

The weird thing is, the file existed, but the icon for it was plain white. After writing this post halfway through I checked the file and it was gone! Apparently it was in the process of being deleted!?

Anywho, it's definitely not there now, and the taskbar icon has also disappeared.  Apparently it has now uninstalled itself!

**Comment by HarryAdney** [comment]
Just reinstalled; the "Restart to Update..." notice is there again. I ain't touching it 'til this is sorted out.

**Comment by joaomoreno** [comment]
Can you show me a screenshot of the error?
