### ISSUE TITLE
Quick Suggestions must not autocomplete with commas

### ISSUE THREAD

**Issue by u3u** [Microsoft/vscode#54386]
- VSCode Version: 1.25.1
- OS Version: macOS High Sierra 10.13.5

Steps to Reproduce:

<img src="https://i.loli.net/2018/07/16/5b4c72e708ac1.gif" width="409">

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
use `"editor.acceptSuggestionOnCommitCharacter": false`, to turn that feature off

**Comment by distinctdan** [comment]
Are there any plans to completely remove "comma" as an autocomplete character? Seems non-standard to me. I never want the editor to autocomplete anything unless I press tab.
