### ISSUE TITLE
Release notes opening as source code an not as HTML page as in previous version

### ISSUE THREAD

**Issue by jotamorais** [Microsoft/vscode#54399]
Issue Type: <b>Bug</b>

**Expected**:
After updating VS Code to latest version and restarting VS Code, one would expect the Release Notes to open as an HTML page (preview mode). 

**Actual**:
After updating and restarting VS Code, Release Notes opens as HTML source code.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.10586

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.68GB (5.38GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
vagrant|bbe|0.5.0
marko-beautify|bus|1.0.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
angular2-snippets|dan|1.0.19
vscode-eslint|dba|1.4.12
vscode-npm-source|dku|1.0.0
xml|Dot|2.3.1
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.5.0
dotnet|for|0.0.4
ruby|gro|0.0.6
search-node-modules|jas|1.3.0
csharpextensions|jch|1.3.0
Angular2|joh|6.1.1
efcore-snippets|jul|0.0.5
dotnet-core-essentials|Kis|0.0.5
node-module-intellisense|lei|1.5.0
csharpfixformat|Leo|0.0.72
VS-code-vagrantfile|mar|0.0.7
dotnet-core-commands|mat|1.0.6
mssql|ms-|1.4.0
python|ms-|2018.6.0
csharp|ms-|1.15.2
PowerShell|ms-|1.8.1
vs-keybindings|ms-|0.2.0
debugger-for-chrome|msj|4.8.0
node-modules-resolve|nau|1.0.2
marko|pca|0.3.0
vscode-docker|Pet|0.0.27
tns-cli|pko|0.0.3
sonarlint-vscode|Son|1.4.0
vscode-helm|tec|0.3.0
nativescript|Tel|0.7.4
nativescript-xml-snippets|tsv|1.0.6
vscode-maven|vsc|0.9.2
nodejs-extension-pack|wad|0.1.9
nativescript-ng2-snippets|www|2.0.1
JavaScriptSnippets|xab|1.7.0
format-all-files|xyk|0.2.0

</details>
ard because it was too large to send. Please paste.

**Comment by joaomoreno** [comment]
What opens if you run <kbd>F1</kbd>, `Show Release Notes`?

**Comment by jotamorais** [comment]
@joaomoreno Pressing <kbd>F1</kbd> actually showed an excerpt of our corporate proxy cover page. So, yeah, that helped to understand that our corp proxy is getting in our way. 

This is similar to #53883

Appreciate your guidance here.

**Comment by joaomoreno** [comment]
Yeah this is definitely related to proxy issues.

The only way to fix this is to check for the content returned by the release notes Markdown URL, example: https://code.visualstudio.com/raw/v1_26.md

@gregvanl Is it safe to assume that the release notes always start with the following?

```
# MONTH YEAR (VERSION)
```

**Comment by eflamm** [comment]
FWIW, I do not have a proxy connection, and while the release notes appear to be rendered as HTML, the links in the first section (Welcome to the June 2018 release...) are all prefixed with `https://code.visualstudio.com/raw/...` whereas if I open the release notes online, the links are `https://code.visualstudio.com/updates/...`. As a result, the links in the release notes don't open a browser window as expected.

![image](https://user-images.githubusercontent.com/1466921/43037577-8e75a31e-8cdc-11e8-9215-da6522d62388.png)
