### ISSUE TITLE
curl: (6) Could not resolve host: packages.microsoft.com gpg: no valid OpenPGP data found. while trying curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg

### ISSUE THREAD

**Issue by GeethanjaliSriram** [Microsoft/vscode#54391]
I'm trying to install VSCode manually and following the steps from https://code.visualstudio.com/docs/setup/linux
I'm getting below error at curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg -

 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: packages.microsoft.com
gpg: no valid OpenPGP data found.

**Comment by Tyriar** [comment]
> curl: (6) Could not resolve host: packages.microsoft.com

This looks like a network issue as it's definitely there https://packages.microsoft.com/, I recommend trying again and speaking to your sys admin if it doesn't work.
