### ISSUE TITLE
Organize Imports doesnt order underscores the same as tslint

### ISSUE THREAD

**Issue by Slessi** [Microsoft/vscode#54393]
- VSCode Version: 1.25.1
- OS Version: macOS High Sierra 10.13.5

Steps to Reproduce:

Organizing generates the below:

```ts
import {
  EmployeeLeave,
  EmployeeLeave as EmployeeLeaveResponse,
  EmployeeLeaveResponses,
  EmployeeLeaveVariables,
  EmployeeLeave_employeeLeave,
  EmployeeLeave_pendingEmployeeLeave,
} from '../GraphQL/types';
```

However, tslint expects the following order:

> *Note*: Don't understand why, but if you have `as` underscores are ordered last, but if you do not have `as`, underscores are ordered first?

```ts
import {
  EmployeeLeave,
  EmployeeLeave as EmployeeLeaveResponse,
  EmployeeLeave_employeeLeave,
  EmployeeLeave_pendingEmployeeLeave,
  EmployeeLeaveResponses,
  EmployeeLeaveVariables,
} from '../GraphQL/types';
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#25690
