### ISSUE TITLE
Explorer context menu: Git raw path

### ISSUE THREAD

**Issue by richeney** [Microsoft/vscode#54390]
Add an option in the right click context menu in the menu (for files) for the Raw Git URI.  This would be very useful when automating around ARM templates, Terraform modules etc.

**Comment by joaomoreno** [comment]
Can you give me an example of a _Raw Git URI_?

**Comment by richeney** [comment]
Sure.  My repo is linked to the GitHub repo:
```
vdc-networking-lab$ git remote -v
origin  https://github.com/azurecitadel/vdc-networking-lab (fetch)
origin  https://github.com/azurecitadel/vdc-networking-lab (push
```

The usual path to the file is:
`https://github.com/azurecitadel/vdc-networking-lab/blob/master/DeployVDCwithNVA.json`
(Maybe a Open in GitHub would be good for a browser URL....)

And the corresponding raw path (navigable via the raw button) is:
`https://raw.githubusercontent.com/azurecitadel/vdc-networking-lab/master/DeployVDCwithNVA.json`

**Comment by joaomoreno** [comment]
This seems GitHub specific, not a general Git concept.

I suggest looking for an [extension which supports it already](https://marketplace.visualstudio.com/search?term=github&target=VSCode&category=Other&sortBy=Relevance), contributing this functionality to an extension, or write a new extension which introduces this.
