### ISSUE TITLE
German commit message placeholder is too long and gets cropped.

### ISSUE THREAD

**Issue by GoBijan** [Microsoft/vscode#5439]
- VSCode Version: 1.0
- OS Version: OS X 10.11.4

Steps to Reproduce:

1. Open Git View
2. Commit message placeholder box is cropped because german translation is way longer than english version.

Suggestion: Replace the following:

> Nachricht (drücken Sie Cmd + Enter, um den Commit auszuführen)

with 

> Nachricht (Cmd + Enter, für Commit)

**Comment by dbaeumer** [comment]
@johnliu2016 can you please pipe this back  to the translation team.

@joaomoreno please have a look as well since we should not clipped text. We should show ... and may be a hover in this case.

**Comment by joaomoreno** [comment]
Can't show `...` since this is a placeholder text. Tooltip can work though.

**Comment by johnliu2016** [comment]
@lukaschal please pass on the suggestion to linguistic review 

[changesView.nls.resx.lcl](https://monacotools.visualstudio.com/DefaultCollection/Monaco/_git/MonacoLocalization#path=%2FLocalize%2Fdeu%2Fvscode%2Fsrc%2Fvs%2Fworkbench%2Fparts%2Fgit%2Fbrowser%2Fviews%2Fchanges%2FchangesView.nls.resx.lcl&version=GBmaster&_a=contents)

      <Item ItemId=";commitMessage" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[Message (press {0} to commit)]]></Val>
          <Tgt Cat="Text" Stat="Loc" Appr="PreApproved" Orig="New">
            <Val><![CDATA[Nachricht (drücken Sie {0}, um den Commit auszuführen)]]></Val>
          </Tgt>
          <Prev Cat="Text">
            <Val><![CDATA[Commit message]]></Val>
          </Prev>
        </Str>
      </Item>

**Comment by johnliu2016** [comment]
@GoBijan can you attach the screenshot showing the clipping so we can understand the context to handle a possible string shortening?

**Comment by GoBijan** [comment]
@johnliu2016  sure :)
<img width="392" alt="bildschirmfoto 2016-04-18 um 15 04 57" src="https://cloud.githubusercontent.com/assets/49339/14605051/11929f30-0577-11e6-83b3-54b775aa08a0.png">

**Comment by johnliu2016** [comment]
Thanks for the s/s, @GoBijan is this Git panel resizable by user?

**Comment by joaomoreno** [comment]
It is. I've also added a `title` attribute, so the user will get the full information on hover.

**Comment by GoBijan** [comment]
Thx guys! You're doing an awesome job with VSCode :) 👍
