### ISSUE TITLE
Copy IDE links with mouse right click

### ISSUE THREAD

**Issue by wellington1993** [Microsoft/vscode#54396]
Hi,

I'm suggesting an way to copy interface links, like changelog links or link of pages rendered inside de editor.

The motivation is way to open the link with another browser or just to share or other copy and paste uses.

I'm not found this suggestion, sorry if duplicate.

Thanks!

**Comment by bpasero** [comment]
I think this asks about being able to "Copy" a link in a webview, e.g. from a context menu.

**Comment by bpasero** [comment]
@wellington1993 maybe show a screenshot of what link you mean

**Comment by mjbvz** [comment]
Many of these are not normal `<a href="...">` links, they trigger editor actions that perform an operation. Copying the href like a browser would make no sense as implemented

For links in the terminal and editor, you can already copy the text of the link itself. Adding @Tyriar and @bpasero to see if we want to do anything else here

The welcome page and tweet ones probably shouldn't be copyable as they are internal. 

For webviews, we could make the links copyable but will have to do a lot of work to make sure we copy the real href and not the pseudo href we actually use the open the link.

**Comment by Tyriar** [comment]
For the terminal I'd need to expose extra API in xterm.js, I'd only want to do that if we make a decision to do this across the workbench. I'm 👎 to this in general right now as there are workarounds and this seems like a lot of work for little pay off when we have plenty of other stuff to do.

**Comment by mjbvz** [comment]
I don't think this is worth the effort. For webviews maybe we can revisit this in the future if more people are interested in it. It only really makes sense though for document style webviews, such as the markdown preview
