### ISSUE TITLE
When openning a folder, i can only open one tab, if i click another file, the file opened before will be covered.

### ISSUE THREAD

**Issue by kylinhao** [Microsoft/vscode#5440]
- VSCode Version:1.0.0
- OS Version:windows

Steps to Reproduce:

1. open a folder
2. click one file in the left nav and a tab will appear in the right and show its content
3. if i click another file in the left nav and it will shut down the tab opened before( i do not do this operation) , as a result, there is only one tab existed.

**Comment by dbaeumer** [comment]
@bpasero :-)

**Comment by bpasero** [comment]
#tabs

**Comment by wahyd4** [comment]
Seems vscode 1.5.2 still have this issue, and in very rare occasion one more tab will be opened.

**Comment by bpasero** [comment]
@wahyd4 try `"workbench.editor.enablePreview": false` in settings

**Comment by wahyd4** [comment]
It works, thank you @bpasero.
