### ISSUE TITLE
Performance Terrible - Unusable experience

### ISSUE THREAD

**Issue by prumbles** [Microsoft/vscode#54409]
Issue Type: <b>Performance Issue</b>

Performance is really bad today.  I don't know what happened.  Scrolling is really bad, and moving the caret position with the keyboard has a slight delay.  Very annoying - even unusable.  Tried multiple projects and they all have the same issue.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17692

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (10.81GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    4	   131	 15308	code main
    4	   150	 11888	   gpu-process
    3	    82	 14440	   window (Issue Reporter)
    0	   223	 14744	   window (my-view1.html - PlaybookFiddle - Visual Studio Code)
    0	    11	 14556	     watcherService 
    0	    12	 14108	       console-window-host (Windows internal process)
    0	    63	 16120	     extensionHost
    0	    86	  4516	       electron_node htmlServerMain.js 
    0	    74	 14752	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (my-view1.html - PlaybookFiddle - Visual Studio Code)
|    Folder (PlaybookFiddle): 22 files
|      File types: html(12) json(3) js(2) png(2) gitignore(1) md(1) svg(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-vscode|raf|1.1.0

</details>

**Comment by ChrisDrostUSE** [comment]
Does it go away if you completely close out of VS Code and then restart it? If you are looking at the Task Manager is VS Code at something like 100% utilization of one core (so on a 4-core machine it sits at 25%)?

(I am having a performance issue which may be similar: performance seems to slowly degrade over time, but "snaps back" when reloading VS code. During this the delay is definitely CPU-bound.)

**Comment by randyleighton** [comment]
I have been having a ton of performance issues. I noticed that there are a ton of Issues are being found with styling stuff in the problem tab. I removed the linting extensions but it still kept finding css and scss stuff wrong.  If I close and reload it seems like its very busy and super slow finding problems.

**Comment by randyleighton** [comment]
this seems to have helped in the settings, though im not sure if its a long term solution
    "scss.validate": false,
    "css.validate": false

**Comment by prumbles** [comment]
@ChrisDrostUSE No, I've restarted VS Code a few times and even restarted my computer, and it still has performance issues.

**Comment by prumbles** [comment]
The issue magically went away today.  I have no idea why this was happening.  I haven't used my computer since last seeing the issue, so I'm not sure how it just stopped occurring.  I am going to close this issue.
