### ISSUE TITLE
Strange character in update dialog

### ISSUE THREAD

**Issue by AmjadKh** [Microsoft/vscode#54408]
- VSCode Version: 1.25
- OS Version: Windows 10 x64

Steps to Reproduce:
1. click update in vs code update notification
2. a dialog shown with the following message: "Update VS Code...X(strange character here)" 
![vscode update bug](https://user-images.githubusercontent.com/8796366/42776611-337aae68-8940-11e8-9265-08b6f496caca.png)

**Comment by joaomoreno** [comment]
Fixed in https://github.com/Microsoft/inno-updater/commit/0625109f5afd09163297f78991d38d4c756f1f2f#diff-e3f00db462e987008147fb59690c1ca6

**Comment by AmjadKh** [comment]
@joaomoreno  What you did exactly? just to know :)

**Comment by joaomoreno** [comment]
We changed to resources in https://github.com/Microsoft/inno-updater/pull/1
