### ISSUE TITLE
Do NOT re-sort QuickPickItem when typing

### ISSUE THREAD

**Issue by ThisIsManta** [microsoft/vscode#54400]
Originally, the quick pick comprises `index`, `actionType`, `reducer`, and `selector` respectively. I intentionally place `index` at the top of the list because, you know, it is `index.js`. However, when start typing, VSCode **re-sorts** my items so `actionType` comes before `index` which **I do NOT want that**.

I believe auto sorting QuickPickItem is a feature (https://github.com/Microsoft/vscode/issues/15659), hence I'm creating a feature request ticket so that `QuickPickOptions` has a new field called `keepOrder` or `doNotResort` or whatever.

Cheers!

![2018-07-16_21-32-48](https://user-images.githubusercontent.com/5592654/42764439-d208e0dc-893f-11e8-8469-6f0c1142e648.gif)

**Comment by Tyriar** [comment]
I guess what's being asked for here is to make sure the entries stay stable if they have the same weight after going through the fuzzy sort.

**Comment by ThisIsManta** [comment]
Thanks Daniel for your swift response.

Unfortunately, I would like have my order untouched whether the search term matches `label` or `description`.

My extension populat

**Comment by Tyriar** [comment]
@ThisIsManta the order must be changed as it's fuzzy sorting and filtering the list. Without sorting, if you had something that matched the label exactly and the description partially the best match may not be at the top. In the example above I would expect the match weights to be the same as they're both matching on the description.
