### ISSUE TITLE
Can an extension receive a notification each time a LanguageServer 'completion' event has taken place?

### ISSUE THREAD

**Issue by d3r3kk** [Microsoft/vscode#54404]
We have a request to count the number of 'completion' events that have occurred from our  LanguageServer in the vscode-python extension. *(After a number of these completion events, we want to raise a popup and ask the user for some feedback).*

I've not found a way to do this without asking for a change from the LanguageServer itself (have it raise an event that I can hook into). I am wondering if there is such a facility already available though, within VSCode itself?

I have found the `BaseLanguageClient.onNotification` from within the vscode-languageclient library. I am not entirely sure what `method` to hook into with this though, or even if there is an event relevant to my need.

Anyone have any tips for this?

**Comment by d3r3kk** [comment]
[I duplicated question here, will update both as information arrives...](https://stackoverflow.com/questions/51366649/how-to-count-languageserver-completion-requests-that-have-occurred-from-within-a)

**Comment by ramya-rao-a** [comment]
@d3r3kk You can add a middleware. For example: https://github.com/Microsoft/vscode-go/blob/0.6.84/src/goMain.ts#L113

**Comment by d3r3kk** [comment]
Wonderful, thank you!
