### ISSUE TITLE
Git: Improve local changes overwriting error message

### ISSUE THREAD

**Issue by JacksonKearl** [Microsoft/vscode#54407]
![image](https://user-images.githubusercontent.com/8586769/42772641-e91e6f36-88df-11e8-9f1e-5cd676d89acd.png)
Maybe we should be checking for this text and changing the message? Either that or allow lists in the error modal. 

- VSCode Version:  Insiders 1.26.0-insider (6babef94104b27b252929324aa3c2d69cd38e9f2, 2018-07-16T05:18:37.865Z)
- OS Version: Win10

**Comment by joaomoreno** [comment]
Let's improve this specific message.

**Comment by joaomoreno** [comment]
Actually we had done this. Git just changed the message in some version.
