### ISSUE TITLE
User Install: application doesn't stay pinned

### ISSUE THREAD

**Issue by eeevans** [Microsoft/vscode#54419]
Issue Type: <b>Bug</b>

So, I kept getting prompted to switch to user install of VS Code with the promise of better update experience.  Now every time VS Code updates it removed my pinned taskbar icon and I have to move it back to where I had it and re-pin it.

VS Code version: Code - Insiders 1.26.0-insider (6babef94104b27b252929324aa3c2d69cd38e9f2, 2018-07-16T05:18:37.865Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz (16 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (8.25GB free)|
|Process Argv|C:\Users\ed.evans\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
aurelia|Aur|1.0.3
solargraph|cas|0.17.5
vscode-markdownlint|Dav|0.18.0
gitlens|eam|8.5.0
vscode-npm-script|eg2|0.3.5
platformio|for|0.2.5
rest-client|hum|0.19.0
VS-code-vagrantfile|mar|0.0.7
terraform|mau|1.2.3
rainbow-csv|mec|0.4.2
mssql|ms-|1.4.0
python|ms-|2018.6.0
azure-account|ms-|0.4.1
azurecli|ms-|0.4.2
cpptools|ms-|0.17.6
csharp|ms-|1.15.2
Go|ms-|0.6.84
PowerShell|ms-|1.8.1
vs-keybindings|ms-|0.2.0
team|ms-|1.136.0
debugger-for-chrome|msj|4.8.0
vscode-docker|Pet|0.0.27
Ruby|reb|0.18.0
vscode-icons|rob|7.24.0
vscode-hexdump|sle|1.6.0
python|tht|0.2.3
azure-iot-toolkit|vsc|1.0.0
vscode-arduino|vsc|0.2.17
vscode-react-native|vsm|0.6.12

</details>

**Comment by joaomoreno** [comment]
But the update is smoother, right? :fireworks: 

> Now every time VS Code updates it removed my pinned taskbar icon and I have to move it back to where I had it and re-pin it.

That is interesting... What happens to that pin after an update? Can you show me?

**Comment by dfinton** [comment]
I can confirm this has happened to me on my Windows 7 computer. After the user update, all my shortcuts, including the pinned one in the taskbar, become invalid (Windows prompts you to remove them if the target no longer exists). I have to manually hunt down the vscode executable in the Program Files directory to relaunch it. I get no errors during the update, and when I manually relaunch it everything works.

**Comment by eeevans** [comment]
When I went to record the latest update, the pin was left alone this time and all worked correctly.  I think the original pin was from the system install that got modified to launch the user installed VS Code.  Not sure.

**Comment by joaomoreno** [comment]
@eeevans That makes more sense. Closing it then. :+1: Thanks for the update.
