### ISSUE TITLE
Moving a file causes entire system to freeze

### ISSUE THREAD

**Issue by kaitlynbrown** [Microsoft/vscode#54413]
- VSCode Version: 1.24.1
- OS Version: Elementary OS Loki 0.4.1
Note: Not sure if this is relevant, but the hard drive which my OS, VS Code, and everything is running from is a SSD connected via USB

Steps to Reproduce:

1. Move a file to another folder by dragging and dropping in the explorer
2. A popup will open asking if you would like to update all imports pointing to the moved file. 
3. The popup is frozen. VS Code is frozen. Everything else is frozen! Only solution is to hard reboot

This has happened to me 2 out of the last 3 times I have tried to move a file in this way

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?
