### ISSUE TITLE
Allow to open editor as pinned and preserve current preview editor

### ISSUE THREAD

**Issue by stefvhuynh** [microsoft/vscode#54418]
Currently, I have the editor configured to use preview mode which is useful for browsing files. However, I would like to be able to open a file NOT in preview mode and in a new tab in the current editor while still having preview mode enabled.

**Comment by mjbvz** [comment]
If you option click on the file, it will open in the next editor group over. Does that do what you want?

If not, please provide a more detailed writeup of the expected behavior

**Comment by stefvhuynh** [comment]
No, I don't a new editor. I want to be able to open that file in the current editor as a new tab. I will add this to the initial description.
