### ISSUE TITLE
Auto-expansion and other default behaviors

### ISSUE THREAD

**Issue by uzhcwells** [Microsoft/vscode#54415]
Hi Team,

I've been an avid MS user and fan for a very long time, starting with Visual Studio 6 (in high school). I'm an Architect and often based applications on MS stack.

VSCode and VS2017 have good language support and features, but I've run into extremely frustrating issues with the 'default' actions of the IDEs now. The auto expansion of code (i.e. javascript) when entering multiline comments, searching, etc. is, RIDICULOUS as a default. For us with very limited schedules, with a focus on using IDE as TOOLS (we are not making VS products), make ALL (EVERY, EACH, SET, AND) of these things O P T I O N A L.

Productivity, focus on achieving valuable goals, etc. are some aspects that architects look at when working with our development teams. The need to constantly fiddle with settings make it super hard to want to download updates (i.e. our #regions stopped functioning last week) that don't need to be set (aka, they are prescriptive FIRST, not SECOND).

Please add an "I just want to type my code like I am in Notepad + keep things open/closed until I CLICK THEM" mode (or better, an installation option with no other DI components in there)? 

Seriously, Notepad++ HAS A BETTER USER EXPERIENCE that VSCode or VSS2017 (sorry to be direct, but time is lost when editing code and the text editor is trying to figure out what we want, but does not seem to know what we want.......................insert puppy dog eyes here.........)

Also, please bring you tools back to being simple to use; you'd agree we all have more complicated and challenging things to think about and maintain that the IDE; I like point-and-click Preference setting, not JSON....you get my drift? Please become the leader, again, of simple to use tools (when your users often are trying to manage, learn or utilize increasingly complex systems, etc.). 

If I buy a hammer, I don't expect the box to have a 50-set instruction manual; the same is for setting background colors.

Simplicity == Valuable
Silence == Golden
Unpredictable == Headache
Love == God

Cheers,
A guy from East Mt. Airy in Zurich

**Comment by alexandrudima** [comment]
@uzhcwells 

By removing unnecessary text, I was able to extract the following three specific pieces of feedback from your issue:

1. auto-expansion when entering multiline comments in JavaScript
2. #regions stopped functioning last week
3. point-and-click preference settings, not JSON

---

1. Do you perhaps mean JSDoc comments? `/**` <- note the two stars. Such comments are considered to be JSDoc comments and there are widely accepted industry conventions around JSDoc comments, namely that they look somewhat like below: e.g.
```ts
	/**
	 * Add a new edit operation (a replace operation).
	 * @param range The range to replace (delete). May be empty to represent a simple insert.
	 * @param text The text to replace with. May be null to represent a simple delete.
	 */
	addEditOperation(range: Range, text: string): void;
```

---

2. Can you provide a reproducible case of a JavaScript? file where #regions are not identified?

---

3. We are actively working on this and it is available as a preview. Did you get a chance to look at the release notes -- https://code.visualstudio.com/updates/v1_25#_new-settings-editor

**Comment by isidorn** [comment]
I agree with Love is equal to God statement 🙏
