### ISSUE TITLE
Don't offer autocomplete it the only option is what the user has already typed

### ISSUE THREAD

**Issue by Timmmm** [Microsoft/vscode#5441]
- VSCode Version: 1.0.0
- OS Version: Windows 7

Steps to Reproduce:

1. Install the Python extension
2. Type `pass`

After typing `pass` you will be offered the autocomplete option `pass`. You then have to press enter or escape to dismiss autocomplete before you can press enter again for a newline (pretty much what you always want after a `pass`).

![capture](https://cloud.githubusercontent.com/assets/376842/14601549/8b406a28-055a-11e6-80be-6089fca47213.PNG)

The result is that you have to mash enter to get newlines sometimes. It's a bit annoying. Autocomplete should hide itself if the only option is what the user has already typed (i.e. if pressing enter would just dismiss it).

**Comment by joaomoreno** [comment]
@jrieken @alexandrudima Any idea why this is back?

**Comment by jrieken** [comment]
> Any idea why this is back?

Unsure what this means?

**Comment by joaomoreno** [comment]
We used to not recommend the `currentWord` in textual completion.

**Comment by spywhere** [comment]
I think this issue is related to #5386 ?

**Comment by Timmmm** [comment]
Ah yeah that is the same issue.
