### ISSUE TITLE
SelectBox: Add shadow option for custom select box

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#54417]
Add widget shadow option to ISelectBoxOptions

@roblourens 
@bpasero 
@misolori 
@sbatten 

While there is already a border, when there are several select boxes on top of each other
such as the new settings editor, the select boxes really blend into each other.

Current example where boxes just flow into each other:

![image](https://user-images.githubusercontent.com/25272315/42782725-bcc77a12-8917-11e8-8915-6556900cd648.png)

Using suggested parameters from Related: #53073
Note: current quick open uses a larger shadow

![image](https://user-images.githubusercontent.com/25272315/42783014-9c6bd32a-8918-11e8-9854-5488fa99c794.png)

I will have the option, assuming no objections, as for values it sounds like this is still in flux.
I can change to whatever.  The new settings is different enough from the quake open menu
it might want slightly different values.

**Comment by roblourens** [comment]
I'm not totally convinced it's necessary, and the shadow looks strange and artificial. Maybe if it was an extremely subtle shadow.

**Comment by bpasero** [comment]
Would it help if there was a stronger border around the dropdown? I would try to stay close to the native look and feel if possible. 

E.g. the difference from dropdown to background is already very subtle in the light theme:

![image](https://user-images.githubusercontent.com/900690/42798411-f97f4602-8993-11e8-9eed-af8ec25ed6e4.png)

**Comment by cleidigh** [comment]
I will post a PR with a couple examples and pictures
for some very subtle shadows.  The recent background color changes
really improve things.  we can compare with some small shadows, but regardless it should be small
if anything.

**Comment by cleidigh** [comment]
@roblourens 
Your new colors and I think some small layout tweaks make the layout much better.
I would say now a shadow would be redundant unless others think differently

show we close this?

**Comment by roblourens** [comment]
Sure, @misolori and I also plan some other dropdown changes for the future :)
