### ISSUE TITLE
No intellisense when exporting es3 style class 

### ISSUE THREAD

**Issue by DenysYefimenko** [Microsoft/vscode#5442]
- VSCode Version: 1.0.0
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. Create two js files.

**moduleA.js**
```javascript
var constructorFunction = function () {};
constructorFunction.prototype.prototypeMethod = function () {};
module.exports = constructorFunction;
```
**moduleB.js**
```javascript
var moduleA = require('./moduleA');
var constructedObject = new moduleA();
constructedObject.
```
2. Try get intellisense suggestion after dot in **moduleB**. 
3. No intellisense provided.

4. If I change code in **moduleA** as following:
```javascript
function constructorFunction () {}
constructorFunction.prototype.prototypeMethod = function () {};
module.exports = constructorFunction;
```
intellisense in **moduleB** starts working.

Expected result: intellisense works no matter how exported function is defined.

**Comment by dbaeumer** [comment]
@DenysYefimenko the change part reads exactly the same as in steps. e.g 
```js
function constructorFunction () {} 
 constructorFunction.prototype.prototypeMethod = function () {}; 
 module.exports = constructorFunction; 
```

Are we missing something ?

**Comment by DenysYefimenko** [comment]
Yes, you do :) In changed part I declared constructorFunction without using `var variable = function() {...}` construction.

**Comment by dbaeumer** [comment]
Thanks. Missed that.

Moving to TS.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#8144
