### ISSUE TITLE
Typescript project: debugging javascript in node_modules stopped working in 1.25

### ISSUE THREAD

**Issue by swilliams-a3digital** [Microsoft/vscode#54425]
Issue Type: <b>Bug</b>

We have our typescript in a folder ~/.  Our typescript compiles to javascript in a folder ~/dist.  Our node modules are in ~/node_modules.  When I attach a debugger to something in node_modules I get an error when the break point hits:
Unable to open 'log-client.js': File not found (file:///Users/swilliams/dist/node_modules/@a3-digital/log-client/log-client.js).

Same project, same code run on vs code 1.24 and earlier works fine.  It is looking for the file in the wrong place.  In incorrectly things node_modules is under dist.

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:02:28.333Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_94231|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.27
xml|Dot|2.3.1
gitlens|eam|8.5.0
tslint|eg2|1.0.33
json-tools|eri|1.0.2
terraform|mau|1.2.3
csharp|ms-|1.15.2
vscode-icons|rob|7.24.0
yo|sam|0.9.3
gitblame|wad|2.4.2
vscode-proto3|zxh|0.2.1

</details>

**Comment by swilliams-a3digital** [comment]
I don't think it is related to those two tickets above. Also, I just reinstalled vs code 1.24.1 and everything works fine in that version.

**Comment by roblourens** [comment]
Can you try with 1.25.1?

Are you using localRoot/remoteRoot in your attach config?

**Comment by swilliams-a3digital** [comment]
my attach config looks like this:

{
            "name": "KUBE",
            "type": "node",
            "request": "attach",
            "port": 8081,
            "address": "localhost",
            "restart": true,
            "sourceMaps": true,
            "outFiles": [ "${workspaceRoot}/dist/**/*.js" ],
            "localRoot": "${workspaceRoot}/dist",
            "remoteRoot": "/app"
        },

**Comment by swilliams-a3digital** [comment]
It does not work in 1.25.1
It does work in 1.24.1

**Comment by roblourens** [comment]
Can you set `"trace": true`, try again, and attach the log here?

**Comment by swilliams-a3digital** [comment]
In the trace file I see these map remoteToLocal, which appear to be mapping the wrong thing on the local side:

Mapped remoteToLocal: /app/node_modules/performance-now/lib/performance-now.js -> /Users/swilliams/projects/banking/bill-pay-fis/dist/node_modules/performance-now/lib/performance-now.js

Mapped remoteToLocal: /app/node_modules/@a3-digital/log-client/http-response.js -> /Users/swilliams/projects/banking/bill-pay-fis/dist/node_modules/@a3-digital/log-client/http-response.js

Mapped remoteToLocal: /app/node_modules/@a3-digital/log-client/log-client.js -> /Users/swilliams/projects/banking/bill-pay-fis/dist/node_modules/@a3-digital/log-client/log-client.js

**Comment by swilliams-a3digital** [comment]
[debugadapter.txt](https://github.com/Microsoft/vscode/files/2203570/debugadapter.txt)

**Comment by roblourens** [comment]
This looks like a correct application of remoteRoot and localRoot. Can you give the same log for 1.24?

remote: `/app/node_modules/performance-now/lib/performance-now.js`
replaces `/app` with `"${workspaceRoot}/dist"`
to get `/Users/swilliams/projects/banking/bill-pay-fis/dist/node_modules/performance-now/lib/performance-now.js`

What is it supposed to be?

**Comment by swilliams-a3digital** [comment]
I'm attached the 1.24 version.  I think the difference between 1.25 and 1.24 is that in 1.24 node_modules is not under ${workspaceRoot}/dist so doesn't seem to apply the remote mapping to node_modules ? Just a guess.
[debugadapter.txt](https://github.com/Microsoft/vscode/files/2203602/debugadapter.txt)

**Comment by roblourens** [comment]
In the 1.24 log I see `Mapped remoteToLocal: /app/node_modules/performance-now/lib/performance-now.js -> /Users/swilliams/projects/banking/bill-pay-fis/dist/node_modules/performance-now/lib/performance-now.js` isn't that exactly the same?

`/app/node_modules replaced with ${workspaceRoot}/dist/node_modules`

Your config says to replace `/app` with `${workspaceRoot}/dist` so the above sounds correct.

**Comment by swilliams-a3digital** [comment]
You are right, it is the same in both.  Maybe it works in 1.24 because node_module is a special folder?  It it searched up to parent node_modules ?

**Comment by roblourens** [comment]
I just think your localRoot/remoteRoot is wrong and I can't find in your 1.24 log where node_modules files show up in the stackTrace.

It's simply replacing localRoot with remoteRoot and vice versa.
