### ISSUE TITLE
White flash / reload a few seconds after opening project

### ISSUE THREAD

**Issue by swilliams-a3digital** [Microsoft/vscode#54422]
Issue Type: <b>Bug</b>

When I open a project in vs code I see my files.  A few seconds later there is a white flash and the screen reloads.  After that vs code works fine. I work on a macbook.  The problem happens to everyone on my dev team.  We primarily are working with typescript projects.

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:02:28.333Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_94231|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.27
xml|Dot|2.3.1
gitlens|eam|8.5.0
tslint|eg2|1.0.33
json-tools|eri|1.0.2
terraform|mau|1.2.3
csharp|ms-|1.15.2
vscode-icons|rob|7.24.0
yo|sam|0.9.3
gitblame|wad|2.4.2
vscode-proto3|zxh|0.2.1

</details>

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by swilliams-a3digital** [comment]
It is caused by one of my extensions.  You can close this ticket.  I'll find out which extension and report it to the maker of that extension

**Comment by swilliams-a3digital** [comment]
FYI: is looks like vscode-icons 7.24 was the culprit.
