### ISSUE TITLE
Heavy CPU usage when code has syntax error

### ISSUE THREAD

**Issue by svenax** [Microsoft/vscode#54427]
Issue Type: <b>Performance Issue</b>

- Edit some code and deliberately create a syntax error. I have tried `php` and `go`, other languages are probably the same.
- Occasionally the CPU usage maxes out, not every time but often.
- The CPU usage goes back to normal if I open the Process Explorer window.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.49GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   43	   131	 46259	code main
   11	    33	 46260	   gpu-process
   25	   328	 46261	   window (runscripts.go — archive-tool)
    0	    33	 46380	     terminal
    0	     0	 46381	       /bin/zsh -l
    0	    98	 46403	     extensionHost
    0	    33	 46406	     watcherService
    0	    16	 48396	     searchService
    5	    82	 46436	   shared-process
    0	   279	 52463	   window (generate_runscripts.php — archive-import-tools)
    0	    98	 52465	     extensionHost
    0	   131	 52483	       php /Users/sven/.vscode/extensions/felixfbecker.php-intellisense-2.3.3/vendor/felixfbecker/language-server/bin/php-language-server.php --tcp=127.0.0.1:59328 --memory-limit=4095M
    0	    49	 52466	     watcherService
   72	    82	 52561	   window (Issue Reporter)
    0	     0	 52565	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (runscripts.go — archive-tool)
|    Folder (archive-tool): 18 files
|      File types: go(9) yaml(3) tsv(2) md(1) json(1) txt(1)
|      Conf files: launch.json(1)
```

</details>
<details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
swagger-viewer|Arj|1.7.0
vscode-toggle-quotes|Bri|0.3.2
vscode-generate-getter-setter|DSK|0.5.0
vscode-markdownlint|Dav|0.18.0
vscode-pandoc|Dou|0.0.8
EditorConfig|Edi|0.12.4
latex-preview|ajs|0.5.1
vscode-eslint|dba|1.4.12
githistory|don|0.4.1
xml|Dot|2.3.1
gitlens|eam|8.5.0
tslint|eg2|1.0.33
git-project-manager|fel|1.6.1
php-debug|fel|1.12.3
php-intellisense|fel|2.3.3
php-pack|fel|1.0.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.3
ruby|gro|0.0.6
jsx|hen|1.0.1
rest-client|hum|0.19.0
latex-workshop|Jam|5.6.1
Lisp|mat|0.1.8
rainbow-csv|mec|0.4.2
ruby-symbols|mig|0.1.7
dotenv|mik|1.0.1
vscode-clang|mit|0.2.2
find-jump|mks|1.2.4
python|ms-|2018.6.0
azure-account|ms-|0.4.1
cpptools|ms-|0.17.6
Go|ms-|0.6.84
makefiles-support-for-vscode|nae|0.0.3
php-docblocker|nei|1.6.0
printcode|nob|2.3.0
advanced-new-file|pat|1.2.0
material-icon-theme|PKi|3.5.1
vscode-table-formatter|shu|1.2.1
gitconfig|sid|1.0.1
vscode-scheme|sjh|0.3.2
vscode-hexdump|sle|1.6.0
rewrap|stk|1.9.1
html-preview-vscode|tht|0.1.1
vscode-lua|tri|0.12.4
lilypond|tru|0.0.1
vscode-todo-highlight|way|0.5.12
better-align|wwm|1.1.6

</details>

**Comment by roblourens** [comment]
This is most likely from an extension. Does it happen if you start with `--disable-extensions`?

**Comment by svenax** [comment]
I will check without extension soon. What I find curious is that the CPU usage immediately drops to normal whenever I open the Process Explorer window.

**Comment by roblourens** [comment]
Hm, that's got to be a coincidence. You can also use the activity monitor or `ps`
