### ISSUE TITLE
Format on save timeout doesn't cancel format request

### ISSUE THREAD

**Issue by JacksonKearl** [Microsoft/vscode#54431]
It looks like a token is created here, but it never gets called. https://github.com/Microsoft/vscode/blob/9bd319bf1e9fbe3dd56f469d37047533915e37b5/src/vs/editor/contrib/format/format.ts#L52 

It should probably be called whenever the timeout is reaced

**Comment by jrieken** [comment]
Do you have more  information or steps? The `asWinJSPromise`-function returns a winjs-promise which has a `cancel` method which is wired up to the cancellation token source. I what scenario did you expect cancellation to happen?

**Comment by JacksonKearl** [comment]
Formatting gets aborted at the vscode level if it takes more than (a default of) 750ms. https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/electron-browser/mainThreadSaveParticipant.ts#L218

However, we don't trigger the token on this timeout. This means the extension's format process never gets killed, but its result is discarded

**Comment by jrieken** [comment]
Ok, now it makes sense. The `mainThreadSaveParticipant` is to blame
