### ISSUE TITLE
Multiline Numbering

### ISSUE THREAD

**Issue by shadykdc** [microsoft/vscode#54430]
I didn't see this so I hope it's not a duplicate.

When doing multi-line editing I frequently want to do something with incrementing numbers.

For example

Some code that is all the same except at the end I'm going to say line 1
Some code that is all the same except at the end I'm going to say line 2
Some code that is all the same except at the end I'm going to say line 3
Some code that is all the same except at the end I'm going to say line 4

This would be especially useful when I'm doing variable names that end in numbers like.

VariableName1 = 0;
VariableName2 = 0;
VariableName3 = 0;
VariableName4 = 0;

I hope that makes sense.

**Comment by TomSputz** [comment]
How could this be implemented? I don't see how the user would use this feature without it being more tedious than just typing it out manually

**Comment by ZombieProtectionAgency** [comment]
@TomSputz It isnt quite the same and I dont know that it would be worth it but it probably wouldnt be too hard to use the system that snippets use to tab between cursor positions along with a command that makes multi-cursor behave like that. 

E.g. Block select the end of the lines then execute some command and the cursor goes to the first cursor position. Then just  "1" tab "2" tab "3" tab etc

**Comment by szepeu** [comment]
You can use [Increment Selection Extension](https://marketplace.visualstudio.com/items?itemName=albymor.increment-selection), which does just what You want.
