### ISSUE TITLE
Current symbol in breadcrumb dropdown is covered by find input box after reveal.

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#54444]
Issue Type: <b>Bug</b>

* Click on a symbol in the editor
* Click on the last item in the breadcrumb
* The symbol item in the treeview/dropdown is revealed and focused but seems it's covered by the input box.

![breadcrumb-reveal](https://user-images.githubusercontent.com/876920/42795639-f5b35198-89b7-11e8-95c2-369515897aa6.gif)

VS Code version: Code - Insiders 1.26.0-insider (6babef94104b27b252929324aa3c2d69cd38e9f2, 2018-07-16T05:11:22.192Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.46GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_14798364|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|2.5.16
markdown-emoji|bie|0.0.7
solargraph|cas|0.17.6
npm-intellisense|chr|1.3.0
vscode-svgviewer|css|1.4.4
vscode-markdownlint|Dav|0.18.0
vscode-eslint|dba|1.4.12
gitlens|eam|8.5.0
remotehub|eam|0.2.0
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.33
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.3.0
ocaml|hac|0.6.43
beautify|Hoo|1.3.2
references-plusplus|jri|0.0.5
vscode-pull-request-github|Mic|0.0.3
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.8
vscode-language-pack-zh-hans|MS-|1.25.3
python|ms-|2018.6.0
azure-account|ms-|0.4.1
csharp|ms-|1.15.2
Go|ms-|0.6.84
PowerShell|ms-|1.8.1
wordcount|ms-|0.1.0
vsliveshare|ms-|0.3.395
debugger-for-chrome|msj|4.8.0
debugger-for-ios-web|msj|0.1.2
color-highlight|nau|2.3.0
vetur|oct|0.12.5
vscode-versionlens|pfl|0.21.1
material-icon-theme|PKi|3.5.1
seti-icons|qin|0.1.3
project-snippets|reb|0.5.0
Ruby|reb|0.18.0
smartpaste|reb|0.0.3
toggle|reb|0.0.1
sass-indented|rob|1.4.9
rust|rus|0.4.7
vscode-graphql|stp|0.2.3
vscode-lldb|vad|0.8.9

(7 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
@joaomoreno I call `reveal`, `select`, and `focus` but it doesn't seem to be properly revealed. See https://github.com/Microsoft/vscode/blob/379f5570229020c213ff11758c1b8dc629ee9e0a/src/vs/workbench/browser/parts/editor/breadcrumbsPicker.ts#L70. Ideas?

**Comment by joaomoreno** [comment]
You seem to be calling reveal before the tree was ever given a layout call.
