### ISSUE TITLE
outline view is always slow and loading, code cannot be folded.

### ISSUE THREAD

**Issue by qdechochen** [Microsoft/vscode#54449]
Issue Type: <b>Bug</b>

- VSCode Version: 1.25.1
- OS Version: Mac OS 10.13.5

Steps to Reproduce:

1. open a js file.
2. change something, and save
3. outline is loading..... and code cannot be folded until outline view is ready (nothing happends when  click -/+. Sometimes, the fold symbols( -, +) disappear, and when outline view is ready, they will be back.
<img width="503" alt="wx20180717-130338 2x" src="https://user-images.githubusercontent.com/1181011/42797623-a13b02ea-89c2-11e8-9f46-a37ca1ed8030.png">

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (1.65GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron --disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled

**Comment by bestv2** [comment]
same to me.
set  files.autoSave to "off" for temporary

**Comment by bestv2** [comment]
It seems to be ok after disable the local-history plugin

**Comment by qdechochen** [comment]
@bestv2 Yes, the problem comes out when you save a file. But, I save file very frequently :(

**Comment by jrieken** [comment]
> It seems to be ok after disable the local-history plugin

Please file this issue against that extension. Once the extension host process is busy, there is nothing we can do.
