### ISSUE TITLE
Feature Request: Add separate Panels  for Updated Files(Newly Added, Modified and Deleted) and Unstaged Files

### ISSUE THREAD

**Issue by quophyie** [Microsoft/vscode#5444]
Hi, I have  been using VS Code recently and I  think that It will be really really amazing if the Git Feature had a staging area / panel which contains modified, newly added and deleted files that was separated from unstaged files instead of the Current **`CHANGES`** panel which contains all modified, unstaged, newly added and deleted file. This current setup makes it too easy to miss files if you only want stage a subset of unstaged files. The current **`CHANGES`** area area also feells untidy and makes it unfriendly if you want to organise modified, newly added added and deleted files separately from the unstaged files. The current setup also makes it too difficult if you want to revert a subset of the modified files.

Finally, if a staging area is to be added, it will nice to be prompted to add new files to new staging area/panel or have a setting that automatically adds new files to the staging area

**Comment by joaomoreno** [comment]
I don't understand what you mean by *unstaged files*. Git doesn't talk about files, but changes. There are three types of changes: modification, addition and deletion. Then, each change can either be staged or unstaged. Here are the combinations:

- unstaged modification
- unstaged addition (untracked)
- unstaged deletion
- staged modification
- staged addition
- staged deletion

We currently display the **unstaged** separate from the **staged** changes. Note that the **staged** group will only show up once you actually stage something. Try clicking the **plus** sign on the right of a change. This will stage it.

What would you prefer having instead?

By the way, you can multi-select changes and use the context actions or the context menu to perform the same action on a group of changes.

**Comment by quophyie** [comment]
@joaomoreno. Thanks for getting back so quickly. When I talked of changed files what I meant was changes :-) . In any case what I mean is that,  if for example, I make a modification to a file that file was previously staged (i.e. an **`unstaged modification`**), I want that unstaged modification to be automatically added the to the **`STAGED CHANGES`** because chances are that I want those modifications staged. In the rare cases when I dont want those changes staged, I can move the changes to the the **`CHANGES`** section before I commit. Without this it becomes too easy to forget / overlook to stage modifications  This also goes for **`unstaged deletions`** 

Also, whenever I add a new file (**`unstaged addition`**), I want to be prompted as to whether I want to stage that file or have a setting where I can always set the editor to stage new `unstaged addition`

I hope this makes it clearer but if not, then let me know and I will provide more info

**Comment by joaomoreno** [comment]
I don't think automatically staging anything is the correct behaviour for a tool such as Code. You might be correct that those are the *chances* but in the cases that they are not, Code would be doing the wrong thing unsolicited. This clashes especially with advanced git users that have expectations as to when and how their changes might be staged or otherwise.

I do see you have an specific workflow, which can be interesting to explore. My suggestion is to write an extension that would automatically stage changes as you make them. I believe we do have API to do so. Calling out to the git executable would let you manage the staging area.
