### ISSUE TITLE
Get a debug exception when i start debug a c program.

### ISSUE THREAD

**Issue by phypy** [Microsoft/vscode#54448]
Issue Type: <b>Bug</b>

Hi, i start an  easy test program(C lauguage), then i start debug by F5,then i get an exception at debug console :
gdb: unknown target exception 0x4000001f at 0x40163e
Thread 1 received signal ?, Unknown signal.
0x0009df88 in ?? ().

other info:
GNU:x86_64-8.1.0-release-posix-seh-rt_v6-rev0,  
debugger:gdb.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (2.00GB free)|
|Process Argv|D:\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.25.3
cpptools|ms-|0.17.6

</details>

**Comment by weinand** [comment]
please file this issue against the C extension you are using.
