### ISSUE TITLE
Custom titlebar misaligned on windows, when maximised.

### ISSUE THREAD

**Issue by kazeshini178** [Microsoft/vscode#54455]
Repo Steps:
Enable `"window.titleBarStyle": "custom"`
Maximise VSCode, using windows snap or 
Pull out of snapped
Maximise VSCode, using windows snap again

Expected results:
Window to maximise properly both times.
Actual results:
Second maximisation is offset from the top of the screen
![image](https://user-images.githubusercontent.com/17514276/42803536-816894b2-89a6-11e8-92f1-d1487e83fb23.png)

**Comment by TomSputz** [comment]
Duplicate - Documented thoroughly upstream at https://github.com/electron/electron/issues/12971 , and the devs have said that they plan to wait for the libchromium fix
