### ISSUE TITLE
Spawn unknown after auto update

### ISSUE THREAD

**Issue by armal** [Microsoft/vscode#54456]
Version 1.22.2
Commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
Date 2018-04-12T16:38:45.278Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- OS Version: Windows 10 Pro PL

Steps to Reproduce:
1. Help/Check for updates
2. popup in the right lower corner show "There's an update available: Visual Studio Code 1.25.1"
3. click button "Install Update"
4. two popups appears:
- error "spawn UNKNOWN"
- second (below error) "Visual Studio Code 1.25.1 is being installed in the background, we'll let you know when it's done."

Nothing happens. There is no installation process. 

Does this issue occur when all extensions are disabled?: Yes
command line shows:
c:\Program Files\Microsoft VS Code>
[main 09:47:25] update#setState idle
[main 09:47:30] update#setState checking for updates
[main 09:47:31] update#setState downloading
[main 09:47:31] update#setState downloaded
[main 09:47:32] update#setState updating

**Comment by joaomoreno** [comment]
What is your Windows user name?

**Comment by armal** [comment]
What for do you need that?

**Comment by joaomoreno** [comment]
Does it have non-ASCII characters?

**Comment by armal** [comment]
no it's just alpha chars.

Anyway, I updated VSS manually, simply installed new version. There is 
no updated versions now, so I don't know if the problem still exists. 
I'll let you know if a new version is released.



W dniu 2018-07-18 o 10:12, João Moreno pisze:

**Comment by joaomoreno** [comment]
In order to get a "fake" update, close Code, open the `C:\Program Files\Microsoft VS Code\resources\app\product.json` and change the `commit` field to `outdated`. Start Code, you should get an update.
