### ISSUE TITLE
Integrated Terminal non-GPU mode

### ISSUE THREAD

**Issue by Xadren** [Microsoft/vscode#54450]
Issue Type: <b>Bug</b>

Had a message pop up saying that using the standard integrated terminal seemed to be running slow, and that I could switch to a DOM based version of  it if I wanted to. I figured why not, switched over and loaded up a new terminal to see the difference.

Now I have an issue with the text running off the edge slightly before breaking on to a new line. The characters that run off the edge are non-visible. Eventually once the line has grown long enough, content starts to appear on the next line.

I've tried reloading the window with all extensions disabled. It didn't change anything. Resizing the terminal window doesn't fix the issue because as soon as the line becomes long enough again, the issue appears.

Resizing the whole application window doesn't fix this either. 

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5 CPU         750  @ 2.67GHz (4 x 2660)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.96GB (0.45GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by czeise** [comment]
This appears to be an issue on macOS 10.13.5 as well.

Screenshot of the overlap I'm seeing when splitting the terminal area:
![image](https://user-images.githubusercontent.com/1188932/42819750-1224210e-899a-11e8-96ed-6b1b31200f0e.png)

As described by @Xadren, this is also an issue when using a single terminal.

**Comment by Tyriar** [comment]
This is fixed already, need to wait for 1.26 though https://github.com/Microsoft/vscode/issues/51479
