### ISSUE TITLE
Feature Request: Add the ability to create and manage Git pull requests from VS Code

### ISSUE THREAD

**Issue by quophyie** [Microsoft/vscode#5445]
Hi, I have been using VS Code lately and the one thing that really frustrates me  about the Git integrations is  not being able to manage git Pull Requests from VS Code. I wanted to kindly ask whether you could add the ability to create and manage git pull requests from VS Code. This will greatly simply workflows that require pull requests without having to leave VS Code

**Comment by jitendravyas** [comment]
+1 I also need this

**Comment by joaomoreno** [comment]
_Pull requests_ are a GitHub concept, not git. This would make a fine extension, would you like to try it?

**Comment by KnisterPeter** [comment]
You could use this one [vscode-github](https://marketplace.visualstudio.com/items?itemName=KnisterPeter.vscode-github)
