### ISSUE TITLE
Make possibility to customize new menubar menu item font size

### ISSUE THREAD

**Issue by Xarkam** [Microsoft/vscode#54469]
Actually the font size for menubar-menu-items -> action-item -> action-label is 11px with a line-height of 1.1em
On my Kubuntu 18.04, this is very small:
![image](https://user-images.githubusercontent.com/331816/42813556-b69bfe92-89c1-11e8-9ee7-efb3f02f289f.png)

With a font size of 12px and line-height at 1.0em the render is bettrer:
![image](https://user-images.githubusercontent.com/331816/42813613-e3b4bc98-89c1-11e8-8f1b-0870140150ac.png)
Can you consider make font customizable ?

Thanks.

**Comment by damieng** [comment]
12px also looks much better on Windows too (regular 96 dpi);

![image](https://user-images.githubusercontent.com/118951/42957834-a6f9ad9a-8b38-11e8-90e4-0c58c8bc125c.png)

vs the default 11px 

![image](https://user-images.githubusercontent.com/118951/42957920-d5321a94-8b38-11e8-9e18-91b8a93ffba0.png)

Notepad for size comparison:

![image](https://user-images.githubusercontent.com/118951/42957945-e9a843d6-8b38-11e8-9f1b-f2fda95959c5.png)

**Comment by damieng** [comment]
The line in question is https://github.com/Microsoft/vscode/blob/65c3b9e9b83ae05a400f9b7291ac0c040dc3d2fa/src/vs/base/browser/ui/actionbar/actionbar.css#L57

This style is used in a variety of contexts.  

The best solution would be to remove the 11px from there and decide which specific contexts 11px is desirable is.

**Comment by sbatten** [comment]
There is a separate feature request for the font size of the entire workbench which the menu now inherits. I believe the spirit of this issue has been addressed, but if you still seek customization, you can upvote #519
