### ISSUE TITLE
error parsing glob

### ISSUE THREAD

**Issue by cloudsyk** [Microsoft/vscode#54463]
- VSCode Version:1.25.1
- OS Version:win 7

Steps to Reproduce:

1.search something
2.
![_20180717173033](https://user-images.githubusercontent.com/1833119/42809037-24c045f2-89e7-11e8-8870-9242a121496e.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
What is in your includes/excludes

**Comment by cloudsyk** [comment]
"search.exclude": {
    "**/node_modules": true,
    "**/bower_components": true
  },
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/**.meta": true
    },

I could not solve it even I delete vs code folder.

**Comment by roblourens** [comment]
It was in the error but I didn't read closely

`"**/**.meta": true`

should be

`"**/*.meta": true`
