### ISSUE TITLE
多行搜索替换

### ISSUE THREAD

**Issue by helibin** [Microsoft/vscode#54467]
搜索框会把多行内容强制转成了单行，这样在做替换时非常不方便

比如有代码如下：
// a.js
/** 模块a */
/** 模块b */
/** 模块c */
现需要在所有/** 模块a */上面叫注释：
/**
 * 基础模块a
 * /
现在vscode会添加为：
/**  * 基础模块a  * //** 模块a */
/** 模块b */
/** 模块c */

希望vscode能有多行搜索替换的功能。

**Comment by mjbvz** [comment]
Seems like a duplicate of #15727

Let me know if I misunderstood the problem
