### ISSUE TITLE
Wierd display in Integrated Terminal with webpack-dashboard in latest version

### ISSUE THREAD

**Issue by ChuckJonas** [Microsoft/vscode#54460]
- VSCode Version: Version 1.25.0 (1.25.0)
- OS Version: 10.12.6

I've been using `webpack-dashboard` in the integrated terminal for a while now without issues (well, without much issue; but that's another... "issue").  However, since the latest release, the lines are no longer displaying nice.  Instead I'm seeing characters show up in their place.

<img width="751" alt="settings_json_ _contract-summary_and_realself--staging___salesforce_-_unlimited_edition" src="https://user-images.githubusercontent.com/5217568/42805948-6b19080e-896a-11e8-92e5-685519568481.png">

Searching the issues for `webpack-dashboard`, it [seems like this might be an encoding issue](https://github.com/FormidableLabs/webpack-dashboard/issues/85).  I've tried setting env vars in the user settings like so `"terminal.integrated.env.osx": {"LC_ALL":"en_US.UTF-8", "LANG":"en_US.UTF-8"},` to try and force it to utf-8, but it doesn't seem to work.  

Steps to Reproduce:

1. open a project with webpack-dashboard configured
2. open integrated termina
3. run webpack dashboard

Does this issue occur when all extensions are disabled?: Yes/No
yes

**Comment by darotar** [comment]
Hello

I made experiment with it

When i am trying to work with 'blessed' npm module and doing something like:

![image](https://user-images.githubusercontent.com/15818529/42807218-41820930-89c1-11e8-9401-6b9266c81cc0.png)
All is normal

But, when I want to declare border.fg like "green" - all is bad

In "webpack-dashboard", "green" is default value for border.fg, so, I guess , this is a problem

**Comment by darotar** [comment]
In development version that's not reproducing

**Comment by Tyriar** [comment]
This is fixed in master https://github.com/Microsoft/vscode/issues/53769

Add this to settings for workaround:

```
"terminal.integrated.experimentalTextureCachingStrategy": "dynamic"
```
