### ISSUE TITLE
Add "File: delete" to Command Palette like Sublime Text

### ISSUE THREAD

**Issue by eduardseifert** [Microsoft/vscode#54476]
Feature Request: Add a command to Command Palette like Sublime Text "File: Delete".

Sublime Text:

![grafik](https://user-images.githubusercontent.com/1193638/42820012-67d4cd98-89d5-11e8-97b8-08f2c101d0c8.png)

VS Code 1.25.1:

![grafik](https://user-images.githubusercontent.com/1193638/42820070-82b1d9b2-89d5-11e8-9318-7fd269fc9bcc.png)

**Comment by bpasero** [comment]
See: https://marketplace.visualstudio.com/items?itemName=sleistner.vscode-fileutils
