### ISSUE TITLE
variable++ appears as unused var

### ISSUE THREAD

**Issue by EylonSu** [Microsoft/vscode#54478]
Issue Type: <b>Bug</b>

Steps to reproduce:
1. declare a variable (let a;)
2. a++;

Expected: a should be colored as used var

Actual: a is highlighted as unused var

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.12
githistory|don|0.4.1
gitlens|eam|8.5.0
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.33
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.5.0
angular2-switcher|inf|0.1.9
search-node-modules|jas|1.3.0
angular-essentials|joh|0.3.2
Angular2|joh|6.1.1
node-module-intellisense|lei|1.5.0
code-bitbucket-pipelines|luk|0.4.2
debugger-for-chrome|msj|4.8.0
angular2-inline|nat|0.0.17
title|nil|0.1.0
code-spell-checker|str|1.6.10
vscode-status-bar-format-toggle|tom|1.4.0
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.7.0

(1 theme extensions excluded)

</details>

**Comment by andy-ms** [comment]
`a` is considered unused because it could be removed without changing the program's behavior -- its value is never read.
