### ISSUE TITLE
Is there any way to select all the text matched by a regex search in column selection mode?

### ISSUE THREAD

**Issue by Inori** [Microsoft/vscode#5447]
- VSCode Version:1.0.0
- OS Version:Win7x64

Here is what I want in sublime:
![a00272d8-0570-11e6-99c9-3fde4a17a97d](https://cloud.githubusercontent.com/assets/6732524/14603561/05c63340-05a1-11e6-8f38-d068f066193b.gif)
Just input the regex text and then press Alt+Enter, It can select all the matched text in multiline mode, then I can edit, copy and paste them at anywhere I want.

How can I reproduce this in vscode or does vscode support for this?

**Comment by alexandrudima** [comment]
PR #5715 closes this.
