### ISSUE TITLE
Rename Visual Studio Code to Visual Code

### ISSUE THREAD

**Issue by hjoab** [Microsoft/vscode#54471]
There was a petition to rename it to Code alone.
https://github.com/Microsoft/vscode/issues/36511
I think VC or Visual Code can help with developers when searching for info in the web.
I used both Visual Studio and Visual Studio Code and when I search for specific issue of Visual Studio I receive pages about Visual Studio Code too. It is a nightmare cos as mentioned in the last petition both are very different products.
Visual Code retains is binding to Visual products as Visual Basic, Visual Studio, etc.

**Comment by welkie** [comment]
When searching for results specific to Visual Studio Code, you can use search terms like "visual studio code" or "vs code" (note the quotes). This should exclude results that pertain to Visual Studio, since the code keyword would be missing.

**Comment by mjbvz** [comment]
Interesting proposal but we do not have plans to make this rename
