### ISSUE TITLE
Custom menu bar shows top item highlighted

### ISSUE THREAD

**Issue by lsieben97** [Microsoft/vscode#54473]
Issue Type: <b>Bug</b>

How to reproduce:
change window.titleBarStyle in the properies editor and restart.

VS Code version: Code - Insiders 1.26.0-insider (d1272ff8edbaa54c81382f82fa2091f63ed3daea, 2018-07-17T08:39:50.444Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU G3900 @ 2.80GHz (2 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (0.89GB free)|
|Process Argv|C:\Users\IT Service Desk\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.33
vscode-icons|rob|7.24.0
linecount|yyc|0.1.7

</details>

![title bar](https://user-images.githubusercontent.com/10631441/42818670-cfe75e7c-89d1-11e8-80b5-fdfbca8acd85.PNG)

**Comment by sbatten** [comment]
addressing in #52933
