### ISSUE TITLE
No longer hitting breakpoints VSCode / Chrome debugging 1.25

### ISSUE THREAD

**Issue by olivieralvespro** [Microsoft/vscode#54477]
Hi, 

Type: BUG

I was using 1.23.1 and upgraded to 1.25 and the issue still persists.
I have the famous: Breakpoint set but not yet bound.
Solutions I have found (or better saying tricks) online do not work.

**Comment by roblourens** [comment]
Then please tell me what you have tried and see the readme for using the `.scripts` command to see what scripts are present and what info they have: https://github.com/Microsoft/vscode-chrome-debug#the-scripts-command

**Comment by desmondddd** [comment]
Same issue here. Breakpoints works in vscode v1.24. But after upgrading to v1.25, all breakpoints are set but not yet bound in my vuejs project. Here is the .scripts out put:
`    - webpack:///./src/components/Header.vue?7961 (/Users/desmond/Repos/quatek_web_app_project/frontend/scr/src/components/webpack:/src/components/Header.vue)
› webpack-internal:///./src/components/Index.vue
    - webpack:///./src/components/Index.vue?24bf (/Users/desmond/Repos/quatek_web_app_project/frontend/scr/src/components/webpack:/src/components/Index.vue)
› webpack-internal:///./src/components/Index.vue?vue&type=script&lang=js
    - webpack:///./src/components/Index.vue?ccf6 (/Users/desmond/Repos/quatek_web_app_project/frontend/scr/src/components/webpack:/src/components/Index.vue)
› webpack-internal:///./src/components/Index.vue?vue&type=style&index=0&id=82b7485c&scoped=true&lang=css
    - webpack:///./src/components/Index.vue?53e2 (/Users/desmond/Repos/quatek_web_app_project/frontend/scr/src/components/webpack:/src/components/Index.vue)
› webpack-internal:///./src/components/Index.vue?vue&type=template&id=82b7485c&scoped=true
    - webpack:///./src/components/Index.vue?9fdd (/Users/desmond/Repos/quatek_web_app_project/frontend/scr/src/components/webpack:/src/components/Index.vue)
› webpack-internal:///./src/main.js
    - webpack:///src/main.js?2ee2 (/Users/desmond/Repos/quatek_web_app_project/frontend/scr/main.js)
› webpack-internal:///./src/registerServiceWorker.js
    - webpack:///src/registerServiceWorker.js?083e (/Users/desmond/Repos/quatek_web_app_project/frontend/scr/registerServiceWorker.js)
› webpack-internal:///./src/router.js
    - webpack:///src/router.js?6a39 (/Users/desmond/Repos/quatek_web_app_project/frontend/scr/router.js)
› webpack-internal:///./src/store.js
    - webpack:///src/store.js?23a6 (/Users/desmond/Repos/quatek_web_app_project/frontend/scr/store.js)`

**Comment by roblourens** [comment]
@desmondddd Please open your own issue and in the future, attach a file instead of leaving a comment almost 1000 lines long.

It would be helpful if you provide your launch config and set `"trace": true` in your launch config and attach the log file too.

**Comment by ivan-pelly** [comment]
Issue closed for lack of info? The initial post says it all. Just create a new project with all the default settings and try and set a breakpoint. You can’t.

**Comment by weinand** [comment]
The requested launch config and trace was not provided and the initial post does not provide enough information to start investigation.

**Comment by statler** [comment]
This seems to be a recurring issue. Refer https://stackoverflow.com/questions/46821519/visual-studio-code-node-debugger-breakpoints-not-being-hit

When people are downgrading to resolve it, then fair chance there is a problem
