### ISSUE TITLE
flask jinja

### ISSUE THREAD

**Issue by krishnachouhan** [Microsoft/vscode#54480]
Issue Type: <b>Bug</b>

{{ some_code_here }}

get converted into:
{ 
    {
        some_code_here
    }
}

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:38.209Z)
OS version: Windows_NT ia32 10.0.15063

**Comment by alexandrudima** [comment]
@krishnachouhan Can you please create the issue against the Python extension at https://github.com/Microsoft/vscode-python/issues
