### ISSUE TITLE
Extension host API should support custom close action in show*Message calls

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#5448]
- VSCode Version: 1.0.0
- OS Version:

The API currently always adds a close message. I want to use my own wording.

**Comment by jrieken** [comment]
streck for April

**Comment by jrieken** [comment]
We should have `MessageOptions` similar to how we have `QuickPickOptions` which allows to control this. Like

```
interface MessageOptions {
   excludeDefaultClose:boolean
}
```

**Comment by jrieken** [comment]
@dbaeumer What would you prefer, explicit `MessageOptions` or alternatively a property on the `MessageItem` signalling it replaces _Close_?

Historically, I added the close action by default such that there is always an affordance to close when no message items are present. So with the `MessageOptions` someone could say don't show close but also provide no alternative which isn't valid. Moving the _replaces close_ information into the `MessageItem` avoids that problem but someone could set that on all items which is a little bogus. What do you think?

**Comment by jrieken** [comment]
spelled out

```
export interface MessageOptions {
 noClose: boolean;
}

export function showWarningMessage<T extends MessageItem>(message: string, options: MessageOptions, ...items: T[]): Thenable<T>;

// repeat for Info and Error...
```

or letting the MessageItem signal

```
export interface MessageItem {		
    title: string;
    isCloseAffordance?: boolean;
}
```

**Comment by dbaeumer** [comment]
I like the second better.

**Comment by jrieken** [comment]
deal
