### ISSUE TITLE
Highlight Unused Imports

### ISSUE THREAD

**Issue by jakedohm** [Microsoft/vscode#54482]
This feature would behave similarly to the recent addition of highlighting unused variables, but with imports. There's not _much_ to explain really, but if any more information is needed, I'd be glad to add more info.

Thanks for the amazing work on VS Code, it makes my life easier every day!

**Comment by andy-ms** [comment]
We should already be doing this. An unused import statement should be faded.

**Comment by jakedohm** [comment]
Gotcha. It probably has to do with the fact that I'm within a `.vue` file (Vue SFC). It's also not highlighting unused vars so I'm sure that's it. Would that be an issue with Vetur, then?

**Comment by mjbvz** [comment]
Yes please file this issue against Vetur
