### ISSUE TITLE
Remove usages of common/diagnostics

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#54486]
There is [`base/common/diagnostics.ts`](https://github.com/Microsoft/vscode/blob/b52ff893c80e9d124fce92234c64f6f09ecf75e7/src/vs/base/common/diagnostics.ts) which isn't used much anymore and also off by default (requires code change to be enabled). This util shouldn't be used anymore as we now have a solid logging story. Please stop using it and delete it then.

**Comment by isidorn** [comment]
@bpasero I have removed the `diagnostics.ts` and am now instead using `logService.info`
The only actual change will be in `textFileEditorModel` so check that out once you have a chance

**Comment by bpasero** [comment]
@isidorn thanks LGTM
