### ISSUE TITLE
When a user hides an activity bar item, should it re-show based on conditional view contributions?

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#54495]
- VSCode Version: 1.25.1
- OS Version: Windows 10 x64

Originally opened here: https://github.com/eamodio/vscode-gitlens/issues/447

Steps to Reproduce:

1. Right-click on the GitLens activity bar icon and choose *Hide*
2. Restart vscode
3. The GitLens activity bar icon will re-appear

Does this issue occur when all extensions are disabled?: No

**Comment by eamodio** [comment]
@sandy081 Related with this -- each time I restart vscode, the GitLens activity bar icon always gets its position reset to the bottom of the bar. I'm not exactly sure why this is the case, other than the fact that my views are conditionally attached to the view container.

**Comment by sandy081** [comment]
Could be related to conditional enablement.
