### ISSUE TITLE
No jsDoc intellisense when function is declared as part of prototype.

### ISSUE THREAD

**Issue by DenysYefimenko** [Microsoft/vscode#5449]
- VSCode Version: 1.0.0
- OS Version: Windows 10

Steps to Reproduce:

1. Create js file with following code:
```javascript
function constructorFunction () {}

/**
 * The prototype method.
 * @param {String} a Parameter definition.
 */
function prototypeMember(a) {}

constructorFunction.prototype.method = prototypeMember;

var x = new constructorFunction();
x.method();
```
2. Check that intellisense shows parameter description for `x.method()`.
3. Replace method definition with shorter syntax:
```javascript
/**
 * The prototype method.
 * @param {String} a Parameter definition.
 */
constructorFunction.prototype.method = function (a) {};
```
Intellisense for `x.method()` is not working now both for function and param descriptions.

**Comment by dbaeumer** [comment]
Moving to TS.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#8147

**Comment by sandersn** [comment]
This works for me on master.

@DenysYefimenko, can you test this by installing typescript@next in a test package and in Code's settings.json temporarily setting "typescript.tsdk": ".../node_modules/typescript/bin", where ... is the path of your test npm package? (You'll have to restart Code or Reload Window to get the changes.)
