### ISSUE TITLE
Typing "/**/" should work

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#54499]
Issue Type: <b>Bug</b>

When I type `"`, `[`, `(`, or `{` it is automatically matched with `"`, `]`, `)`, or `}`. But typing `""` or `()` will work by consuming the automatic match, so I don't end up with `())`.
When I type `/**/` I would expect that to be exactly the text I get, but instead I get `/**/ */`.

**Comment by mjbvz** [comment]
@rebornix @alexandrudima This is because we expand `/*|` to `/**| */`. Is there any way to tell VS Code to eat the next `/` that the user types, like we for for `)` when completing `()`?

**Comment by alexandrudima** [comment]
@mjbvz I don't believe it is the same case as a single character expansion.

We expand `/**|` to `/**| */`, i.e. we append ` */` after the cursor.

![kapture 2018-07-30 at 15 06 04](https://user-images.githubusercontent.com/5047891/43399061-1e3f6a78-940a-11e8-8383-5773c31300ad.gif)

It is not clear to me how to possibly recover if the user meant to type literally and empty comment: `/**/`. 

Perhaps we should not expand `/**|` to `/**| */` as it is not 100% clear a JSDoc will follow. Perhaps we should do the smart things when pressing Enter, as that more clearly indicates a JSDoc comment.

**Comment by alexandrudima** [comment]
Let's track in #1966
