### ISSUE TITLE
UI freeze on moving to trash on linux

### ISSUE THREAD

**Issue by Yanpas** [microsoft/vscode#54493]
- VSCode Version: 1.25
- OS Version: kubuntu 18.04

Steps to Reproduce:

1. start fresh system/session (I use KDE)
2. delete any file on HDD, ui freezes for 2 seconds

Moving to trash is synchronous action, but should be done asynchronously or in another thread. I assume that it is implemeted via DBus on Linux :thinking:

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by bclinthall** [comment]
I'm getting the same issue on windows. I just reproduced it on today's insider build. I made a bunch of files like this:
```js
var fs = require('fs');
for (let i=0; i<1000; i++){
    var wstream = fs.createWriteStream(i + '.txt');
    for (let j=0; j<1000; j++){
        wstream.write('Hello world!\n')
    }
    wstream.end();
}
```

I selected all the files in the vscode explorer and pressed the delete button. 
![image](https://user-images.githubusercontent.com/25251768/53424008-60a58b80-39b0-11e9-9b4f-49301ef17b18.png)

[Here](https://github.com/electron/electron/issues/11555) is a related electron issue.

It looks like the upstream aspect of the problem is that electron does not handle io asynchronously by default. If you want asynchronous io in an electron application, you have to do it yourself. The fact that vscode has not chosen to make io from its explorer asynchronous is a vscode issue, not an electron issue.

**Comment by Toxicable** [comment]
I get the prompt that VS Code is no longer responding + UI lock up when deleting anything, big or small files, even if the file is empty.

```
$ node --version
v10.15.3
$ code --version
1.33.1
51b0b28134d51361cf996d2f0a1c698247aeabd8
x64
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
$ plasmashell --version
plasmashell 5.12.7
$ kf5-config --version
Qt: 5.9.5
KDE Frameworks: 5.44.0
kf5-config: 1.0
```

**Comment by Ishidres** [comment]
It's been almost a year since this issue has been opened and it still occurs to me.
Why hasn't it been fixed, yet?

**Comment by drerichards** [comment]
> It's been almost a year since this issue has been opened and it still occurs to me.
> Why hasn't it been fixed, yet?

Same issue

**Comment by diegoheusser94** [comment]
Same issue

`$ node --version
v10.15.2
$ code --version
1.38.1
b37e54c98e1a74ba89e03073e5a3761284e3ffb0
x64
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 19.04
Release:        19.04
Codename:       disco
$ plasmashell --version
plasmashell 5.15.4
$ kf5-config --version
Qt: 5.12.2
KDE Frameworks: 5.56.0
kf5-config: 1.0`

**Comment by pikacic** [comment]
I have the same issue (code 1.39.1 88f15d17 installed via snap on Kubuntu 19.04), and I just tried the deb package you suggested.

From a simple test (open a folder + try to delete a file) it looks like it works.

I'm looking forward to get the version based on the new Electron via snap.

**Comment by killruana** [comment]
I use (K|X)ubuntu 19.04 and VSCode 1.39.1.
I trigger the bug when I use vscode on KDE but not when I use XFCE.

**Comment by diegoheusser94** [comment]
> We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
> 
> * macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
> * Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
> * Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
> * Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)

I tested the deb package and it worked

**Comment by killruana** [comment]
The bug is fixed for me using the provided .deb package (v1.39.0-exploration)
