### ISSUE TITLE
React Native slow debugging

### ISSUE THREAD

**Issue by danielDevelops** [Microsoft/vscode#54497]
When debugging react native code using the iOS Simulator the performance is very slow.  

Running the application normally is fine, but when the debugger is attached the application performs very slow

- VSCode Version: MacOS
- OS Version: High Sierra latest version

Steps to Reproduce:

1. Create react native application
2. add SQLIte save something to the db 
3. see slow performance

Does this issue occur when all extensions are disabled?: N/a since they are needed to debug react-native

**Comment by weinand** [comment]
what debug extension are you using?

**Comment by danielDevelops** [comment]
React Native Tools

**Comment by weinand** [comment]
please file the issue against their repository.
