### ISSUE TITLE
Breadcrumbs: clicking the scrollbar clears selection

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#54496]
![peek 2018-07-17 19-00](https://user-images.githubusercontent.com/22350/42833162-aff42588-89f3-11e8-84d8-4be4f4692c9d.gif)

**Comment by jrieken** [comment]
it seems to focus the container... not doing anything special tho

**Comment by jrieken** [comment]
my outline view has the same problem. seems to be me. @joaomoreno do I need to set something on the tree or its container?

**Comment by joaomoreno** [comment]
:man_shrugging:

**Comment by jrieken** [comment]
Thanks
