### ISSUE TITLE
Breadcrumbs: Should list ever be collapsed?

### ISSUE THREAD

**Issue by JacksonKearl** [Microsoft/vscode#54491]
I'm not sure that it ever makes sense for the breadcrumbs to be focused but collapsed, gven `Shift+Left/Right` can navigate between layers even when the list is open. It seems that it just adds an additional step of `Ctrl+Shift+.` followed by `Enter` always. Am I missing something here?

**Comment by jrieken** [comment]
> I'm not sure that it ever makes sense for the breadcrumbs to be focused but collapsed, gven Shift+Left/Right can navigate between layers even when the list is open.

Not sure what you mean collapsed? You mean not showing the picker?

**Comment by mihailik** [comment]
Breadcrumbs help making sense where you are in a large file.

**Comment by JacksonKearl** [comment]
What about if we allowed filtering by name while the list is not expanded, where any typing would epxand the list and start the filtering?

**Comment by JacksonKearl** [comment]
Typing when the breadcrubs bar has focus is currently a noop. It would be nice if it could start filtering as you type without needing to press `Enter` first

**Comment by jrieken** [comment]
Pushed a change that makes <kbd>Cmd+Shift+.</kdb> focus *and* select the last breadcrumb. Also added another command <kbd>Cmd+Shift+;</kdb> that only focuses (as before)
