### ISSUE TITLE
Problems view doesn't report TypeScript unreachable code

### ISSUE THREAD

**Issue by jonchardy** [Microsoft/vscode#54494]
Issue Type: <b>Bug</b>

1) Set `"typescript.reportStyleChecksAsWarnings": false` so that unreachable code is an error.
2) Create a simple file:
```ts
function test(): boolean {
  return true;
  return false;
}

test();
```

The `return false` line is greyed out and upon hover shows the TS error, but the problems view doesn't report it. It also causes an error during compilation.

![image](https://user-images.githubusercontent.com/1202288/42832477-55a9ee0c-89bf-11e8-84c6-2a1d7a94c48b.png)

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.84GB (23.18GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by mjbvz** [comment]
This matches the behavior of `tsc`. Unreachable code is not reported as an error (hence shown in problems) unless you set `allowUnreachableCode": false` or `"strict": true` in your `tsconfig.json`

**Comment by jonchardy** [comment]
Ok, figured out the problem. Our tsconfig is nested in a config folder, so `allowUnreachableCode` wasn't being accounted for properly. Looks like another use case for https://github.com/Microsoft/vscode/issues/12463, since we have different files named tsconfig in different folders.
