### ISSUE TITLE
randomly buggy lines appear in terminal

### ISSUE THREAD

**Issue by abdurrahmanarikan** [Microsoft/vscode#54506]
- VSCode Version: 1.25.1
- OS Version: 

Steps to Reproduce:
IDK, it appears randomly

1. macOS High Sierra
2. 10.13.6

![screen shot 2018-07-17 at 11 27 05 pm](https://user-images.githubusercontent.com/24858031/42843658-79e2aeb2-8a19-11e8-9ffb-12095b55cf4a.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Also do you have `window.zoomLevel` set?

**Comment by abdurrahmanarikan** [comment]
Hi @Tyriar,
I have ```window.zoomLevel": 0``` settings on my user settings file. I'll add 
```"terminal.integrated.experimentalTextureCachingStrategy": "dynamic"``` settings and pull the result here.
Thanks

**Comment by abdurrahmanarikan** [comment]
![screen shot 2018-07-25 at 11 28 55 am](https://user-images.githubusercontent.com/24858031/43188896-f4c0b55e-8ffd-11e8-8a06-e5af951ea58c.png)
it appeared again @Tyriar

**Comment by Tyriar** [comment]
I saw this today, it appeared as an horizontal line similar to an underscore for me.

**Comment by Tyriar** [comment]
I suspect this is related to Electron as when a character changes, the entire row is cleared and redrawn.
