### ISSUE TITLE
Split the background of the quickpick menu from `sideBar.background`

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#54509]
Currently  `sideBar.background` provides the background color for both the side bar as well as the quickpick menus. I would like to be able to specify a quick pick background color separate from the side bar.

**Comment by bpasero** [comment]
@eamodio if you want to take a stab at this, otherwise I would close as "out of scope".

**Comment by eamodio** [comment]
It looks like this is already implemented - https://github.com/microsoft/vscode/issues/65153
