### ISSUE TITLE
Terminal Opens Unexpectedly and captures input

### ISSUE THREAD

**Issue by TadMC** [Microsoft/vscode#54505]
Issue Type: <b>Bug</b>

While writing python, when rapidly typing "#" and a newline, like making a large comment block, something happens were the "#\n"s are piped to the terminal inside of VS Code.  Ive repeated this several times. I looked up the hotkey combo's to check if this is expected behavior and it doesnt seem so. 

EDIT: I should include my keyboard just incase thats the problem: It is a Microsoft Natural Ergonomic Keyboard 4000 v1.0

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (2 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.86GB (20.74GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
fortran|Gim|0.2.0
gc-excelviewer|Gra|2.1.24
language-julia|jul|0.10.2
fortran|krv|0.4.5
linter-gfortran|krv|1.3.1
rainbow-csv|mec|0.4.2
python|ms-|2018.6.0
csharp|ms-|1.15.2
PowerShell|ms-|1.8.1
vba|spe|1.2.0

</details>

**Comment by Tyriar** [comment]
This is likely an issue with the python extension https://github.com/Microsoft/vscode-python/
