### ISSUE TITLE
Add support for themable window border

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#54507]
On Windows 10 at least with the new custom titlebar (`"window.titleBarStyle": "custom"`) vscode loses its window border. It would be great for a theme to be able to specify a border color in this case (if desired). Because with some themes (particularly mine) it can be hard to tell where 1 window ends and another one starts.

I tried setting `titleBar.border` but it wasn't what I was looking for:
![image](https://user-images.githubusercontent.com/641685/42843782-129a8ef8-89df-11e8-9f00-3b23d151af1a.png)

//cc @sbatten

**Comment by mihailik** [comment]
That problem exists in default theme too: no border fuses overlapping windows.

Suggestion: slap a DIV with `box-shadow: inset...` on top of all of existing content. By using very faint inset shadow the border is non-intrusive and subtle, but the window edge is perceptible and makes a big difference when multiple VSCode instances opened.

I tried this one in DevTools, looks sensible (add as the last element inside #workbench.main.container div):

```html
<div style="
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 100;
    box-shadow: inset 0px 0px 13px rgba(0, 0, 0, 0.23);
    box-sizing: border-box;
"></div>
```

**Comment by smcpeak** [comment]
Note that for those who just want VSCode to have a window with a border (despite it possibly clashing with the theme), change the "Window: Title Bar Style" setting to "native".  That causes the entire window (not just the title bar) to have the usual OS decorations.
