### ISSUE TITLE
Completion in JSDoc is too eager to fix spelling error

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#54502]
Issue Type: <b>Bug</b>

Create a new JS file, type `/** @template T` and hit enter.
Expected:
```js
/**
 * @template T
 */
```

Actual:
```js
/** @template template */
```

Note that tsserver returns no completions in this case, so vscode must be coming up with them itself.

VS Code version: Code - Insiders 1.26.0-insider (b48367a8652bd0aa862638bbc24555a70823d3bd, 2018-07-17T05:18:49.004Z)
OS version: Linux x64 4.13.0-43-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2418)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|7.63GB (2.37GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders .|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by mjbvz** [comment]
Yes those are our word based suggestions. We show them in comments and strings and other locations where no normal suggestions are returned.

Disable them by setting:

```json
"editor.wordBasedSuggestions": false
```
