### ISSUE TITLE
Translation : Some translations are confusing

### ISSUE THREAD

**Issue by npirotte** [Microsoft/vscode#5450]
- VSCode Version: 1.0.0
- OS Version: window 10

The translation of some technical terms and command is confusing. 

For example I can no more type "git: commit" in the command palette, now I have to type "git: publier". The git original command is commit, I don't want to learn a new cli api for every translated feature...

Terms could be translated, but I would like to have access to commands by typing the original name.

Steps to Reproduce:

1. Run VSCode in french
2. Try to run a command like git: commit

**Comment by dbaeumer** [comment]
Dups #4679
