### ISSUE TITLE
Create tiny cli for running launch configuration definitions

### ISSUE THREAD

**Issue by ianwremmel** [Microsoft/vscode#54508]
I tend not to commit my launch.json because my CI tools rely on npm scripts defined in package.json and it's inconvenient to keep them in sync. It would be great to run definitions from launch.json via npm scripts so that CI tools can use them.

For example, let's say I have unit and integration tests defined in my `launch.json`. I'd like to put something in `package.json` like

```json
{
  "scripts": {
    "test": "npm-run-all test:*",
    "test:unit": "vscli --launch 'Unit Tests'",
    "test:integration": "vscli --launch 'Integration Tests'"
  }
}
```

Ideally, this would be a small, discrete package installable from npm that could be quickly download in CI environments rather than something that's only bundled with vscode and would require the whole app to be installed.

**Comment by weinand** [comment]
Launch configurations are not interpreted by VS Code but rely on debug extensions.
So a "vscli" tool would need access to all extensions in some kind of "headless" VS Code.

This is not something we are planning to do.

But you could use a reverse approach: keep all your launches as npm scripts and call them from launch configurations.

**Comment by ianwremmel** [comment]
> But you could use a reverse approach: keep all your launches as npm scripts and call them from launch configurations.

I considered that, but I've had limited success getting the debugger to work with things specified in npm scripts.

**Comment by weinand** [comment]
I'm not aware of any problems in that area. Do you have any examples?
I can help investigating...

**Comment by ianwremmel** [comment]
Nothing specific, I'm afraid. I always chalked it up to too many layers of binaries calling binaries. I haven't tried this recently, but I would expect the following to not be debuggable:

```json
{
  "scripts": {
    "test": "nyc mocha 'src/**/*.spec.js'"
  } 
}
```

**Comment by orenmizr** [comment]
@ianwremmel having the same issue running 
```
debug: wdio file.spec.js
```
did you find a workaround ?

**Comment by weinand** [comment]
@ianwremmel I don't know what "nyc" does, but in order to be debuggable, you will have to add a debug flag somewhere in the npm debug script, right? 

E.g. `"debug": "nyc mocha --inspect-brk=8888 'src/**/*.spec.js'"`

And then let VS Code know what the debug port is by adding a `"port": 8888` attribute to the launch config.

**Comment by ianwremmel** [comment]
hmm, ok. that might work, but i think that means it'll wait for the debugger before it runs tests, right? The problem, as i see it, is that the way vscode deals with run/debug configurations means most projects end up with two sources of truth that need to manually kept in sync:

- the `npm run` script that gets use by developers on the command line or in CI tools
- the `.vscode/lanuch.json` config that gets used by the vscode debugger. 

It seems to me that there are too many possible ways for run scripts to be implemented, so, in general,  vscode won't be able to figure out what to debug, but at the same time, a reasonable generic runner should be able to interpret the launch config and then call its entries from the CLI. The cli wouldn't need to put it in debug mode, necessarily, it would just need to invoke the same command with the same arguments in order to prevent multiple sources of truth.

I guess I'm specifically looking for a cli that could handle launch configs matching `{"type":"node", "request": "launch"}` since this feels like it could be an issue specific to how node programs get debugged and tested. 

Are launch configuration interpreters and debugging extensions one and the same? In other words, is https://code.visualstudio.com/docs/extensions/example-debuggers the only way to add new `"type"` options to the create new launch configuration list? I think I could write this myself fairly easily, but not necessarily in a way that survives vscode changes or works for runtimes other than node. I'd like to understand launch configurations better before going down that path :)

([nyc](https://github.com/istanbuljs/nyc) is a cli around istanbul that magically instruments code for coverage reporting, but it's just one example of where the vscode debugger gets separated from the process running the code under test)
