### ISSUE TITLE
Style @-ms-viewport issue

### ISSUE THREAD

**Issue by GrzegorzCupial** [Microsoft/vscode#54515]
Issue Type: <b>Bug</b>

Hi,
I have noticed something weird after last 1-2 patches

While coding email the whole code starts to be wrongly coloured below "@-ms-viewport"

![capture](https://user-images.githubusercontent.com/20965336/42848345-7b8c517c-8a1f-11e8-8872-93c5bdb179a5.PNG)

Deleting -ms- fixes issue
![capture_2](https://user-images.githubusercontent.com/20965336/42848393-9d970942-8a1f-11e8-94be-b52da4f58ddd.PNG)

**Comment by octref** [comment]
I added correct syntax highlight for `-ms-viewport` and `-o-viewport`.
