### ISSUE TITLE
Keyboard Shortcuts Reference that incorporates User Key Bindings

### ISSUE THREAD

**Issue by johndugan** [microsoft/vscode#54517]
It would be a nice little improvement if the [keyboard shortcuts reference](https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf) accessed from the help menu incorporated users' key bindings. Currently, it's a static document that only contains the defaults.

**Comment by cbuchart** [comment]
I think it worth mentioning that it should also update existing keybindings when user has modified them.
