### ISSUE TITLE
Please add implement interface functionality

### ISSUE THREAD

**Issue by jeffsaremi** [Microsoft/vscode#54519]
Just like VisualStudio I'd like to be able type "`class A implements B`" and then an Action to appear suggesting to implement the interface.

As of 1.25.0 on Windows such functionality does not exit.

**Comment by mjbvz** [comment]
What language? Please provide a code example if you don't see it showing up

**Comment by jeffsaremi** [comment]
This is in typescript.

file: Operators.ts
```
export interface Operators {
  doSomething(): Result;
}
```

file Backend.ts:
```
export class Backend implements Operators {
// nothing happens here ; no suggestions or actions
}
```
