### ISSUE TITLE
tasks.json update error when working from mapped network drive

### ISSUE THREAD

**Issue by adamzerok** [Microsoft/vscode#5451]
- VSCode Version: 1.0.0
- OS Version: WIn7 x64

**Summary:**
Changes to tasks.json are not recognized by ctrl-shft-B if the file is on a mapped network drive unless I first restart of VSCode.

**Steps to Reproduce:**

1. Select a working folder on a mounted network drive.
2. create tasks.json. ctrl-shift-B and verify operation.
3. change tasks.json so it has an error, save it (close, reopen in another editor if desired to verify it was saved)
4. hit ctrl-shift-B. note that the new, saved version is not used.

**Comment by dbaeumer** [comment]
The task service uses the config service to react to changes to the tasks.json file. The config service relies on file events.

@bpasero are you aware of any problem with FS events and mapped network drive. I had the experience that this worked

**Comment by bpasero** [comment]
@adamzerok can you check if any file event occurs from the mapped drive? I would assume this does not apply just for tasks.json but any other file as well.

Otherwise I am merging this into https://github.com/Microsoft/vscode/issues/3132

**Comment by adamzerok** [comment]
Events are seen when the tasks.json or any other file are changed.  There is no problem with file creation, editing or saving.

Changes to the script are applied when it is run with ctrl-shft-B

However, the updated tasks.json just isn't being used. It uses the copy present when VS Code launches.  If i make a change to tasks.json it isn't used unless i restart VS Code.

**Comment by bpasero** [comment]
@adamzerok ok this will be covered when we work on #3132
