### ISSUE TITLE
Migrate menubar action registrations out of menubar.contribution.ts

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode#54510]
With the new menubar implementation, all menubar actions can be contributed via the `MenuRegistry`. Currently, all actions for the menubar are registered in a single file `menubar.contribution.ts`; however, it would be nice to have these registered and owned by the area owners from which they originate.

When moving your command registration to the appropriate location, you may also opt to add a `precondition` to the command so that it is enabled dynamically. I have chosen the debug actions as an example https://github.com/Microsoft/vscode/commit/a08526a457c0adeb3efd7af04ad02ae708e23b1f. @isidorn I have not moved the registrations, only used them to demonstrate the use of `precondition` for the menu entries.

Here is an inline example:

```
MenuRegistry.appendMenuItem(MenuId.MenubarDebugMenu, {
	group: '3_step',
	command: {
		id: 'workbench.action.debug.continue',
		title: nls.localize({ key: 'miContinue', comment: ['&& denotes a mnemonic'] }, "&&Continue"),
		precondition: ContextKeyExpr.has('inDebugMode')
	},
	order: 4
});
```

There is also a `when` clause on the menu entry that hides the entry if the condition is not met; however, we are not currently recommending this approach for the menubar unless you are swapping two entries that are mutually exclusive.

@Microsoft/vscode please review the menubar entries for ones that you can own and move the corresponding registration into a more appropriate location. You can then add a `precondition` if it applies. Please ping me if you have any questions.

- [x] file @isidorn
- [x] edit @alexandrudima @rebornix 
- [x] selection @alexandrudima @rebornix 
- [x] view @isidorn
- [x] go @jrieken @bpasero 
- [x] terminal @Tyriar 
- [x] debug @isidorn
- [x] tasks @dbaeumer
- [x] window @bpasero @isidorn
- [x] help Volunterees welcome

**Comment by bpasero** [comment]
Linking https://github.com/Microsoft/vscode/issues/991 which is the original issue. One thing to mention is that we should try to set a `precondition` on most menu items to make sure the enablement is proper. If a context key does not exist yet for a particular menu item, it should be added 👍

**Comment by isidorn** [comment]
@sbatten nice work. 
I have moved the Debug menu contribution via 0738ae2f7f
@bpasero I can also move the View menu but not sure where to put it. How about it `main.contribution`? I can also create a new file `view.contribution`

@sbatten the ugly part now is that we have double the registration both in `menu.contribution.ts` and in `menus.ts`. When will we be able to drop `menus.ts` and really solely on the new way of registering menu items?

**Comment by isidorn** [comment]
I have updated the checkboxes in the original comment such that we have some owners per menu item.
@bpasero I will move the file, view and window menus in appropriate places. Just do a code review once you are back
@sbatten please tryout my changes on windows

**Comment by dbaeumer** [comment]
Done for tasks. @isidorn thanks for your help.

**Comment by alexandrudima** [comment]
@sbatten I tried to use `precondition` to control the enablement of Undo and Redo. One of the problems that came up is that the menubar menu entries are evaluated in the global context.

But in the workbench you can have multiple editors opened, some of which can undo and some of which cannot.

I have noticed that the menubar will refocus on the previously focused element when invoking the action, so if focus is in editor1, and then the Edit menu is opened, and Undo picked, focus is correctly brought back to editor1 before the command is invoked.

I think we could support high fidelity disablement/enablement of these commands if the menu items `precondition` would be evaluated in the context of the previous focused element. You can find the context associated with a particular element via `IContextKeyService.getContext(previousFocusedElement)`.

**Comment by sandy081** [comment]
Thanks @isidorn for adopting `Open View...` action.
