### ISSUE TITLE
51323 clarification

### ISSUE THREAD

**Issue by Gubith** [Microsoft/vscode#54511]
Existing issue https://github.com/Microsoft/vscode/issues/51323 closed.

> @ShayCormac1963 You can change keybindings and settings by changing your user keybindings.json and settings.json files. The defaults only exist in memory.

I think this means "Disregard the error.   Override the specific key binding in user settings, if needed."

**Comment by yume-chan** [comment]
#51323 was closed by a fix, the little text after the close mark read:

> @sandy081 closed this in 37a59a282aa66ac91c77daa8358d8241d3791709 2 days ago

**Comment by sandy081** [comment]
@Gubith Not sure what you mean and how it is related to #51323. Can you please elaborate?

**Comment by Gubith** [comment]
Thread 51323 shows closed still but I was able to post, maybe it was reopened.
