### ISSUE TITLE
Menu: align sub menus visually

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#54527]
A small nit, see native submenu:

![image](https://user-images.githubusercontent.com/900690/42860503-307f1484-8a57-11e8-9a08-ee886ca22382.png)

vs our submenu:

![image](https://user-images.githubusercontent.com/900690/42860510-396a9488-8a57-11e8-8f0a-3b45b7876312.png)

I think most native menus try to put the menu item on the same vertical position.

**Comment by neilsustc** [comment]
Still not aligned in today's insider build 😳

![image](https://user-images.githubusercontent.com/7588612/50094201-83762f80-020a-11e9-95bf-1ad6283c3f02.png)

**Comment by sbatten** [comment]
@neilsustc another fix broke this fix, now re-fixed :P
