### ISSUE TITLE
Trim the file name in the search menu

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/vscode#54529]
trim file name search

Suppose you're looking for `MyFile.ts` or `MyFile.ts:1:23`. If you search them exactly, you'll get the file result. If you prepend and/or append whitepace, e.g. ` MyFile.ts `, you won't.

It's common to accidentally include spaces when copy & pasting file names from, say, test reports. I'd love to fix this issue if you don't mind!

**Comment by roblourens** [comment]
Assuming leading and trailing whitespace is never relevant to any filePattern in a search, I think the correct spot would be here: https://github.com/Microsoft/vscode/blob/9c2084b9ee8c3a7ac0320772bd201cd341d08e5f/src/vs/workbench/parts/search/common/queryBuilder.ts#L83

A PR would be great!
