### ISSUE TITLE
No intellisense when object definition and declaration is splitted

### ISSUE THREAD

**Issue by DenysYefimenko** [Microsoft/vscode#5452]
- VSCode Version: 1.0.0
- OS Version: Windows 10

Steps to Reproduce:

1 Having following code: 
```javascript
function constructorFunction () {
	this.otherFunction = function () {}
}

constructorFunction.prototype.method = function () {};

var x;
x = new constructorFunction();
x.method();
```
2 Try to get intellisense suggestions on `x.method()`. No suggestions provided (apart from generic ones).
3 Do the following change:
replace 
```javascript
var x;
x = new constructorFunction();
```
with
```javascript
var x = new constructorFunction();
```

4 Intellisense starts working on `x`. It suggests both `method `and `otherFunction`.

**Comment by dbaeumer** [comment]
This is TS related. Moving...

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#8146
