### ISSUE TITLE
Visual Studio Code won't auto update

### ISSUE THREAD

**Issue by carnun** [Microsoft/vscode#54531]
Issue Type: <b>Bug</b>

Every time I start up Visual Studio Code it prompts me to restart to update. When I click on the restart button it shuts down VSCode and it doesn't restart VSCode. When I do open VSCode again I get the same restart to update prompt and VSCode is still on the old version.
Steps
1. Click on Restart to update
2. ...VSCode shuts down
3. Open up VSCode again
4. ...VSCode is still on version 1.24.1

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz (4 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 6, 6|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.27
vscode-raml|blz|3.0.1
vscode-eslint|dba|1.4.12
githistory|don|0.4.2
tslint|eg2|1.0.34
vscode-auto-open-markdown-preview|hnw|0.0.4
MagicPython|mag|1.0.12
python|ms-|2018.6.0
debugger-for-chrome|msj|4.8.0
code-spell-checker|str|1.6.10
python|tht|0.2.3

</details>

**Comment by joaomoreno** [comment]
Please check https://github.com/Microsoft/vscode/issues/7426#issuecomment-277737150
