### ISSUE TITLE
Suggestion: Nightly builds or way to produce own build

### ISSUE THREAD

**Issue by outcoldman** [Microsoft/vscode#5453]
To help contributing - we, contributors, need to have a way to get the latest builds. Will be good to have an option, something like `"update.channel": "nightly"`.
If this is not possible - at least have a way to build own VSCode package, which we can use for development.

**Comment by bgse** [comment]
You can build vscode yourself, just clone the repo and follow the instructions here:

https://github.com/Microsoft/vscode/blob/master/wiki/contributing/how-to-contribute.md#build-and-run-from-source

**Comment by outcoldman** [comment]
@bgse sorry, by "building" I meant "packaging". I want to be able to produce a package which I can use to replace `Visual Studio Code.app`.

**Comment by dbaeumer** [comment]
You can only build the OSS version of code using gulp vscode-win32 (or other platforms). There is no public command to build the identical MS VS Code version due to product specific settings.

@chrisdias can you provide more details?

**Comment by outcoldman** [comment]
What about publicly available Nightly builds?

**Comment by outcoldman** [comment]
Also does `gulp vscode-win32` produces actually a package, like "OSS Version Code.app" or just set of files which I need to package inside Electron on my own?

@dbaeumer why have you closed this issue? My question has not been answered yet.

**Comment by outcoldman** [comment]
Ok, I have found that `gulp vscode-darwin` outputs `VSCode-darwin/` outside of the source folder (which is not great), but understandable. Please document these steps.

**Comment by dbaeumer** [comment]
I thought my explanation was good enough on how to build VSCode yourself. Obviously not :-(. We also discussed making nightly builds available but haven't reached a conclusion yet.

**Comment by outcoldman** [comment]
Yes, it was a little bit confusing how to produce own build. I believe that `gulp vscode-darwin` is not documented anywhere. But this gave me some idea where to look, so I finally made my own build (using it for my unmerged PR).

@dbaeumer Could you please keep this feature request open to track "nightly builds" status?

Honestly I do not see a reason why I (or anybody else) cannot setup "nightly builds" on their own, but in that case you (Microsoft) will loose telemetry and statistics, which you probably want to have.

**Comment by dbaeumer** [comment]
Reopening. 

@chrisdias I assign to you because of the request of public nightly builds and the request of being able to run their own full VSCode builds

**Comment by chrisdias** [comment]
Nightly builds are on their way, please see: http://code.visualstudio.com/blogs/2016/05/23/evolution-of-insiders

**Comment by PeteOliveira** [comment]
@outcoldman This is a memory test :)

I am trying to create a vscode package using gulp vscode-darwin which from what I can tell needs modifications to the build script.
You mentioned "I finally made my own build (using it for my unmerged PR)" which I was hoping to find and learn from, but no luck.

Any chance you can point me in the right direction so I can gulp vscode-darwin successfully?

Thanks

**Comment by outcoldman** [comment]
@PeteOliveira sorry, I do not remember what required to do that. I only remember that I took some json file from official package and used it as an example.

**Comment by PeteOliveira** [comment]
@outcoldman thanks for the response and hopefully pointing me in the right direction.
Stay warm
