### ISSUE TITLE
Crash on every launch

### ISSUE THREAD

**Issue by CanastraRF** [Microsoft/vscode#54533]
Issue Type: <b>Bug</b>

Everytime I launch the app I get a crash but the App works fine after that

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3410)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.70GB (5.24GB free)|
|Process Argv|F:\Programme\VSCode-win32-x64-1.25.1\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-de|MS-|1.25.2

</details>

Name der fehlerhaften Anwendung: Code.exe, Version: 1.25.1.0, Zeitstempel: 0x5aa27854
Name des fehlerhaften Moduls: ntdll.dll, Version: 6.3.9600.18969, Zeitstempel: 0x5aa29ff0
Ausnahmecode: 0xc0000361 (STATUS_ACCESS_DISABLED_BY_POLICY_DEFAULT)
Fehleroffset: 0x00000000000ecf30
ID des fehlerhaften Prozesses: 0xd8
Startzeit der fehlerhaften Anwendung: 0x01d41e617507443f
Pfad der fehlerhaften Anwendung: F:\Programme\VSCode-win32-x64-1.25.1\Code.exe
Pfad des fehlerhaften Moduls: C:\Windows\SYSTEM32\ntdll.dll
Berichtskennung: b2c0d700-8a54-11e8-87b4-08606ec61c83
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by CanastraRF** [comment]
I can reproduce it with your nightly insider builds

**Comment by bpasero** [comment]
@CanastraRF can you try with our latest insider builds to see if something changed?

**Comment by bpasero** [comment]
@CanastraRF how is the crash surfacing?

**Comment by CanastraRF** [comment]
I start Code - Insiders.exe
After 1-2 secounds I get Screen Step1.png
![step1](https://user-images.githubusercontent.com/3735857/44037233-5c0fc6dc-9f03-11e8-82f3-e07835e61df3.png)

After additional 1-2 secounds I get Screen Step2.png
![step2](https://user-images.githubusercontent.com/3735857/44037251-643a25fa-9f03-11e8-84ed-44afc5a3a148.png)

HTH

**Comment by bpasero** [comment]
@CanastraRF weird indeed, I do not think VSCode is triggering this but maybe something in your windows installation triggers it. To validate that, I have builds of VSCode available that use a much newer UI framework, can you maybe give that one a try: Windows: [Download](https://az764295.vo.msecnd.net/exploration/acdabe28fb63ed8b3bdd9ba685bfe595c2daf750/VSCodeUserSetup-x64-1.27.0-exploration.exe)

**Comment by CanastraRF** [comment]
@bpasero 
I test with 1.27.0-exploration and it is the same behaivior.
![step3](https://user-images.githubusercontent.com/3735857/44146892-343028c6-a081-11e8-98b0-5724ba595c32.png)
This is also on all Computer in out Domain.

Does the program try to execute any code in the user Profile or temp Folder.
All of out Client are protected with Software restriction policies and no code can be executed from the Profile or temp Folder.

**Comment by bpasero** [comment]
@CanastraRF did you install VSCode global or for your user? We recently switched to supporting user installation which installs to %APPDATA%. 

A simple way to check this is if you could try to run from a ZIP file: https://az764295.vo.msecnd.net/stable/4e9361845dc28659923a300945f84731393e210d/VSCode-win32-x64-1.26.0.zip

**Comment by bpasero** [comment]
@CanastraRF that is Windows 8.1 you are using right?

**Comment by CanastraRF** [comment]
Yes Win 8.1 German x64

**Comment by bpasero** [comment]
If this results in a native crash (not sure), maybe this is possible:
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by CanastraRF** [comment]
@bpasero 
I install DebugDiag.
Attached are the logs.

[Code__PID__4972__Date__08_16_2018__Time_09_04_58AM__293__Log.zip](https://github.com/Microsoft/vscode/files/2292712/Code__PID__4972__Date__08_16_2018__Time_09_04_58AM__293__Log.zip)

Hope I've done it right

**Comment by bpasero** [comment]
@CanastraRF thanks, I was hoping for some stacktrace in those logs but it seems there are none. Does it make any difference if you run VSCode in that compatibility mode (http://pearsonsupport.helpserve.com/Knowledgebase/Article/View/210/2/how-to-install-or-run-a-program-in-compatibility-mode-in-windows-7)?

**Comment by CanastraRF** [comment]
@bpasero 
The Problem was, I can't select the process code.exe before the Crash. 
So I selected the process after it crashs.

Now I create a link to code.exe and set compatibility mode
All available Version (Vista to Win8) crashs

I test on a W10 Client in our domain with similar policies without any Crash.

**Comment by CanastraRF** [comment]
@bpasero 
Attached is a additional DebugDump where I run DebugDiag with active rule for code.exe
HTH
[Code__PID__176__Date__08_16_2018__Time_09_59_11AM__959__Log.zip](https://github.com/Microsoft/vscode/files/2292869/Code__PID__176__Date__08_16_2018__Time_09_59_11AM__959__Log.zip)

**Comment by bpasero** [comment]
@CanastraRF thanks, there is more info now.

@Tyriar a little bit suspicious is this one:

```
DetailID = 2
	Count:    1
	Exception #:  0XE06D7363
	Stack:        
		KERNELBASE!RaiseException+0x6c
		winpty!winpty_free+0x8421
		winpty!winpty_config_set_agent_timeout+0xd18
		winpty!winpty_config_set_agent_timeout+0x10ea
		winpty!winpty_open+0x68d
		pty+0x3182
		pty+0x1f46
		node!v8::internal::compiler::CommonOperatorBuilder::CreateFrameStateFunctionInfo+0x3650
		node!icu_59::Collator::safeClone+0x1763
		node!icu_59::Collator::safeClone+0x593
		node!icu_59::Collator::safeClone+0x47b
		0x11d`388847a1
		0x55`9e62b7c1
		0xa3
		0x5a`7f6dc080
		0x5a`03264540
		0x16
		0x5a`7f6dc080
		0x11d`3893fa33
		0x11d`388846e1
		0x5a`7f6dbfc0
		0x6
		0x5a`7f6dc0b0
		0x11d`389740e8
		0x22c`e9702311
		0x19c`45286949
		0xb`00000000
		0x22c`e9702421
		0x18`00000000
		0x50`00000000
		0xcd`30dc63d1
		0xcd`30dc3a51
		0xcd`30dc6829
		0x33`d3d61959
		0x3bd`7f53d121
		0x9`00000000
		0x14e`31e07e21
		0xcd`30dc6221
		0x19c`45286949
		0x5a`7f6dc0f8
		0x7
		0x16
		0x5a`7f6dc148
		0x11d`3893fa33
		0x22c`e9702421
		0x18`00000000
		0x50`00000000
		0xcd`30dc63d1
		0xcd`30dc3a51
		0xcd`30dc6829
		0x33`d3d61959
		0x3bd`7f53d121
		0x19c`45286949
		0x55`9e62b7c1
		0x22c`e9702311
		0xcd`30dc6829
		0x7f`00000000
		0x19c`45283ee9
		0x3bd`7f5585d1
		0x3bd`7f5585d1
		0xcd`30dc6221
		0x5a`7f6dc1c0
		0x11d`38885903
		0x22c`e9702421
		0x18`00000000
		0x50`00000000
		0xcd`30dc63d1
		0xcd`30dc3a51
		0x33`d3d619e9
		0x33`d3d61959
		0xcd`30dc6191
		0xcd`30dc6191
		0x3bd`7f5585d1
		0x7`00000000
		0xcd`30dbfa99
		0x1e
		0x5a`7f6dc250
		0x11d`38975e27
		0x22c`e9702421
		0x18`00000000
		0x50`00000000
		0xcd`30db3919
		0xcd`30dc3a51
		0x33`d3d619e9
		0x33`d3d61959
```

**Comment by bpasero** [comment]
@CanastraRF is it possible that you see this crash only when opening our integrated terminal?

**Comment by CanastraRF** [comment]
@bpasero 
Sorry I'm not familar with code now.
I'm looking for a replacemant of my current Editor.
So I download code and run it.
I've only configure the german Interface.
When the  integrated terminal open in the default configuration it opens.
Can I disable  integrated terminal?

**Comment by bpasero** [comment]
@CanastraRF the terminal is this:

![image](https://user-images.githubusercontent.com/900690/44199102-7bff2680-a143-11e8-96c2-8377785fdd5d.png)

**Comment by CanastraRF** [comment]
@bpasero 
I've not opend any terminal or any other Thing manualy
I've no termial menu at all now
![step4](https://user-images.githubusercontent.com/3735857/44201992-3db13980-a13a-11e8-84b0-5e3c70dded30.png)
Thanks for any Support.

**Comment by bpasero** [comment]
@CanastraRF ok thanks, unfortunately I am at the end of ideas...
