### ISSUE TITLE
External debugger

### ISSUE THREAD

**Issue by antonio-petricca** [Microsoft/vscode#54532]
- VSCode Version: 

> Version: 1.26.0-insider
> Commit: d1272ff8edbaa54c81382f82fa2091f63ed3daea
> Date: 2018-07-17T08:37:44.704Z
> Electron: 1.7.12
> Chrome: 58.0.3029.110
> Node.js: 7.9.0
> V8: 5.8.283.38
> Architecture: x64

- OS Version:

> Distributor ID: LinuxMint
> Description:    Linux Mint 19 Tara
> Release:        19
> Codename:       tara

Steps to Reproduce:

1. Install [VS Code Bash Debugger](https://github.com/rogalmic/vscode-bash-debug).
2. Add to **launch.json**:

```json
            "console": "externalTerminal",
            "env": {
                "TERM": "mate-terminal"
            },
```

3. Run debugger

4. Output: 

> TERM environment variable not set.

**Comment by weinand** [comment]
Please file this issue against the Bash debugger.

**Comment by antonio-petricca** [comment]
Could you explaing why you assess this? 
Could you point me to a guide to configure the external terminal for the current insiders release?

Thank you again!

**Comment by weinand** [comment]
@antonio-petricca how a terminal is configured for debugging depends on the debug extension. Passing environment variables specified in a debug config to the debugger or debuggee is the responsibility of the debug extension. VS Code does neither control nor prescribe how this is done.

**Comment by antonio-petricca** [comment]
Thank you for you kindly answer!
