### ISSUE TITLE
Menu: don't use padding to center text vertically

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#54539]
Menu fonts are blurred because their text elements are set with `padding-top` and `padding-bottom` at fractional pixel values (`5.5px`).

![screenshot from 2018-07-18 09-24-49](https://user-images.githubusercontent.com/22350/42866570-2c41e6d8-8a6d-11e8-9ebf-4189af85bda6.png)

Please simply use flex for laying out menu items. Layout would be much easier to understand and reason about, as well.

**Comment by joaomoreno** [comment]
Another issue is the misalignment of different labels:

![screenshot from 2018-07-18 09-38-19](https://user-images.githubusercontent.com/22350/42866955-65563e78-8a6e-11e8-9a62-fb54c4dac02c.png)

**Comment by sbatten** [comment]
fixed via https://github.com/Microsoft/vscode/pull/54695
