### ISSUE TITLE
Copy/paste HTML kills indentation

### ISSUE THREAD

**Issue by bischofb** [Microsoft/vscode#54534]
When I copy paste Html into my code it throws off the indentation of the code I'm copy/pasting as well as the next line below it. Why it shifts over the line below it doesn't make any sense. Anyway, auto-indentation is great when I'm typing, but when I do copy/paste I always have to go back and reformat all my indentation.

**Comment by rebornix** [comment]
We tried to adjust the indentation based on language indentation rules but that might not be perfect. You can turn off this feature by setting `editor.autoIndent` to `false`.
