### ISSUE TITLE
showing system files in git  

### ISSUE THREAD

**Issue by emmyhayer** [Microsoft/vscode#54536]
in  git tab vs code showing system  files on ubuntu 18.04
![screenshot from 2018-07-18 12-28-03](https://user-images.githubusercontent.com/12946963/42865079-1e1c1402-8a86-11e8-8444-6248be92d8e5.png)

**Comment by joaomoreno** [comment]
Run `git rev-parse --show-toplevel` to find out where your git repository root is. If that should not be a git repository, then delete the `.git` folder contained within it.
