### ISSUE TITLE
'Unused class' notification missing in VSCode

### ISSUE THREAD

**Issue by theapache64** [Microsoft/vscode#54530]
In `WebStorm`, if a class not used anywhere, we'll get a notification like this

![image](https://user-images.githubusercontent.com/9678279/42862952-1607922a-8a7f-11e8-9906-9fda12976198.png)

Is this available in VSCode?

**Comment by jpike88** [comment]
needs a bit more info...

**Comment by mjbvz** [comment]
We don't detect unused, exported variables as we do not know if they form part of a public api
