### ISSUE TITLE
Menu: Menu items still show border on built product

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#54538]
This is super annoying and almost makes me jump back to native menus. Possibly Linux only.

Built product, with Dark+:

![screenshot from 2018-07-18 09-24-49](https://user-images.githubusercontent.com/22350/42866364-a208ec32-8a6c-11e8-953a-f904e21c438b.png)

Dev, with Dark+:

![screenshot from 2018-07-18 09-25-08](https://user-images.githubusercontent.com/22350/42866363-a1f1276e-8a6c-11e8-8fe3-80795a7f747a.png)

We change some CSS order in the built product, which might override styles set in dev.

**Comment by joaomoreno** [comment]
I'm not even able to debug this in the built product. As soon as I focus the devtools, that border is gone. @bpasero might know exactly where that style is.

**Comment by joaomoreno** [comment]
I was only able to suppress it with:

```
.menubar-menu-items-holder .action-menu-item {
    outline-color: transparent !important;
}
```

Which is definitely not the fix. We should understand why this is different in the build vs dev and override the style properly.

**Comment by sbatten** [comment]
this was addressed via https://github.com/Microsoft/vscode/commit/01fb34dc00c36566afc7ac55e09be4c17f2f1bb4
