### ISSUE TITLE
Message service should show a little more

### ISSUE THREAD

**Issue by alefragnani** [Microsoft/vscode#5454]
When you use `vscode.window.showErrorMessage` (_Information_ and _Warning_ too), the message that is displayed is _limited_ to one line with a certain length. 

It would be good to have a way to _expand_ the message (maybe like the _Read more_ available in Intellisense), showing the entire content.

Thanks in advance

**Comment by dbaeumer** [comment]
@jrieken +1. I have a use case for this as well.

**Comment by jrieken** [comment]
The API should be fit for it but it's a limitation of our underlying message service.

**Comment by bpasero** [comment]
@stevencl @bgashler1 this should be one input to our notifications discussion.

**Comment by joelbarker2011** [comment]
At the very least, there should be some documentation stating that the portion of the message string after the first new line will be silently ignored!

**Comment by bpasero** [comment]
Hovering should always reveal the full message so there is a workaround.

**Comment by joelbarker2011** [comment]
Thanks, @bpasero.

I note that hovering collapses all white space (newlines/tabs) into single spaces (it renders as a string, not HTML, so there seems to be no way to render lines of output in a readable manner).

I also note that the hovering behavior, while better than nothing, is both non-obvious and undocumented.

**Comment by bgashler1** [comment]
Related to #1135

**Comment by philocafe** [comment]
> Hovering should always reveal the full message so there is a workaround.

Have you ever tried writing down an error message that is displayed in a tooltip?
Doesn't work all that well. ;)

**Comment by s-h-a-d-o-w** [comment]
> Hovering should always reveal the full message so there is a workaround.

Have you ever tried writing down an error message that is displayed in a tooltip?
Doesn't work all that well. ;)

**Comment by bpasero** [comment]
This landed via https://github.com/Microsoft/vscode/pull/43770 and can be tried out in our preview release: https://code.visualstudio.com/insiders/
