### ISSUE TITLE
wrong editor cursor position when enter new line in split editor. 

### ISSUE THREAD

**Issue by Zuolon** [Microsoft/vscode#54545]
- VSCode Version:1.25.1
- OS Version:win10

Steps to Reproduce:
![vs code bug](https://user-images.githubusercontent.com/35440694/42866917-9354f666-8aa0-11e8-9262-6e4bf5b84ce5.gif)
1.Split a editor.
2.Enter any content and show intelligent code completion dialog, and then don't click anywhere and don't close the suggest dialog.
3.Now enter new line in another editor. The cursor will jump back to old editor.

Does this issue occur when all extensions are disabled?: Yes

**Comment by braindev** [comment]
FWIW, I'm seeing the same thing on MacOS with the same version of VSCode.

**Comment by alexandrudima** [comment]
I would expect the suggest list to close itself on focus loss.

@Zuolon Can you reproduce this when disabling all extensions?
