### ISSUE TITLE
Can't open integrated terminal

### ISSUE THREAD

**Issue by SmallLuma** [Microsoft/vscode#54549]
Issue Type: <b>Bug</b>

1.Open the floder.
2.View -> integrated terminal -> I can not type anything in it.It shows nothing.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.80GB (2.42GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|0.3.6
Lua|key|0.0.9
vscode-language-pack-zh-hans|MS-|1.25.3
rust|rus|0.4.7

</details>

**Comment by SmallLuma** [comment]
@Tyriar 
[settings.json.zip](https://github.com/Microsoft/vscode/files/2208628/settings.json.zip)
![screenshot](https://user-images.githubusercontent.com/11296891/42926193-3aae4602-8b63-11e8-81c3-3014089d4792.png)

**Comment by SmallLuma** [comment]
More than PowerShell is not available, Cmd and GitBash are not available.

**Comment by SmallLuma** [comment]
The terminal of Inside Edition is not available too.

**Comment by Tyriar** [comment]
Can you close all VS Code windows and then launch in a terminal with `code --log trace`. This will expose some terminal logs that you can get to from the command "Developer: Open Log File..." (F1 opened command palette). Can you get the logs when the issue happens and paste it in here?

**Comment by SmallLuma** [comment]
I had launched the code with --log trace,but I could not open the log.
![tim 20180720004340](https://user-images.githubusercontent.com/11296891/42957756-253915ce-8bb6-11e8-8173-7b28212d0b0f.png)

But I got some log in console.

![0](https://user-images.githubusercontent.com/11296891/42957800-461d3be4-8bb6-11e8-98ff-c5a3ed2e9c67.png)
![1](https://user-images.githubusercontent.com/11296891/42957803-486a42f2-8bb6-11e8-9c72-cdd30bb27962.png)

**Comment by SmallLuma** [comment]
My user name is chinese.
May code has some problem with Chinese character?

**Comment by Tyriar** [comment]
Are you running VS Code in compatibility mode? See https://code.visualstudio.com/docs/editor/integrated-terminal#_common-questions

**Comment by SmallLuma** [comment]
Yes,I had try it in Windows 8/7/Vista compatibility mode,but it  not work.
Administrator mode is not work too.

**Comment by SmallLuma** [comment]
If I uncheck the compatibility mode,it not work too.

**Comment by jadchaar** [comment]
I am unable to open the integrated terminal as well. Just started on 1.25.1 (at least as far as I can tell). Completely clean installed VSCode and the issue remains. When I try and open an integrated terminal my fans spin up and my CPU Temp ramps up to 70C, and nothing opens when the button is clicked. I look at the activity monitor and have multiple Code Helper processes at 100%+ CPU usage. After this, the terminal icon in the bottom bar just disappears on window reload. I had to disable the "Terminal" extension for now.

**Comment by Tyriar** [comment]
It's probably related to the user name then.

**Comment by SmallLuma** [comment]
I had created new user "VSCodeTest" to test VSC.
![default](https://user-images.githubusercontent.com/11296891/43254472-093563c0-90fa-11e8-99ba-76532bbd9b20.png)

Log:
[20180726T173451.zip](https://github.com/Microsoft/vscode/files/2231333/20180726T173451.zip)

**Comment by Tyriar** [comment]
@SmallLuma maybe try see if it still happens in the Insiders build? https://code.visualstudio.com/insiders/

**Comment by SmallLuma** [comment]
@Tyriar Console in the Insiders build is not worked.
