### ISSUE TITLE
Menu: can't click devtools Continue button anymore

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#54544]
The `Continue` button is now unclickable:

![screenshot from 2018-07-18 10-03-10](https://user-images.githubusercontent.com/22350/42868170-ec0a3fc0-8a71-11e8-9381-80222aefc8fe.png)

**Comment by joaomoreno** [comment]
How do we actually set that the titlebar is the draggable window element?

**Comment by sbatten** [comment]
It's css  `-webkit-app-region: drag`

**Comment by joaomoreno** [comment]
https://github.com/electron/electron/issues/1354#issuecomment-404348957

Not sure how nice this would work...

**Comment by sbatten** [comment]
I won't try to reimplement the drag behavior ourselves so this is on electron/chromium to fix. fyi @deepak1556
