### ISSUE TITLE
Add 'Save as Copy' to File menu options

### ISSUE THREAD

**Issue by greggo10** [Microsoft/vscode#54543]
I often find myself wanting to save a copy of a file, as backup, and continue working on the on the original open file.
Currently I have to do a 'Save As', close the renamed file and re open the original file. 
A 'Save as Copy' option would simplify this.

**Comment by bpasero** [comment]
You can get this by installing this extension: https://marketplace.visualstudio.com/items?itemName=sleistner.vscode-fileutils
