### ISSUE TITLE
Title bar custom: Min/Max/Close Icons get lost when window is too small

### ISSUE THREAD

**Issue by theFlyingCat04** [Microsoft/vscode#54556]
When the window of code is too small, then the icons for closing minimizing and maximizing the window disappear. I expect those (essential) icons to be visible all the time.

- VSCode Version: 1.25.1
- OS Version: Linux Mint 18.1 Serena

Steps to Reproduce:
1. in the settings choose "window.titleBarStyle": "custom" and reload the window
2. grab the left or right border of the window and shrink it to a minimum, then the above mentioned icons will disappear

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
@theFlyingCat04 Thanks for reporting. This issue has been resolved in the latest insiders.
