### ISSUE TITLE
Bad Syntax Highlighting for Valid Javascript

### ISSUE THREAD

**Issue by qdirks** [Microsoft/vscode#54553]
Issue Type: <b>Bug</b>

Please copy and paste the following javascript statements into vscode:

```js
var g = function() {console.log(1);};
var x = (function(){}/0); // bad highlighting
var y = (function(){}/0/g);
var z = (function(){}/0/g)/g(function(){}/0/g);
```

The code runs okay, but vscode fails to highlight it correctly. I believe the issue is due to the division slash being interpreted as the beginning of a regex literal.

The reason I would like this fixed is because it could help with code obfuscation/deobfuscation and debugging. Thanks for your time.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (8 x 3411)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (8.43GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#639
