### ISSUE TITLE
Rename "Change Language Mode" to "Change Syntax Highlighting"

### ISSUE THREAD

**Issue by SimonSomlai** [Microsoft/vscode#54555]
I was looking for a way to change the highlighting of my code and found it confusing that it was named "Change Language Mode". Most other editors I've used in the past at least included the word 'Syntax'.

I don't seem to be the only person that couldn't easily find this feature; https://stackoverflow.com/questions/30775551/how-to-manually-set-language-for-syntax-highlighting-in-visual-studio-code

 Is this something that could be re-named? It would definitely make it easier to transition between editors!

**Comment by Gama11** [comment]
It's not just about syntax highlighting, it also affects all language-specific features like IntelliSense, Navigation, Refactoring...

**Comment by alexandrudima** [comment]
The language mode picker gets one of the most proeminent spots in our UI in the status bar and that is the primary way to change the language:

![image](https://user-images.githubusercontent.com/5047891/43327582-16131a8e-91bc-11e8-8f6e-022adc2c6753.png)

I would not rename it to "Change Language Syntax" as syntax highlighting is only part of it. VS Code offers intellisense, hover, refactorings, etc. so the scope of changing the language is more than just the syntax highlighting.
