### ISSUE TITLE
я не могу форматировать код

### ISSUE THREAD

**Issue by kirya355** [Microsoft/vscode#54558]
я нажимаю shift + alt + f , ничего не работает и появляется уведомление , 
Модуль форматирования документов для файлов 'csharp' не установлен.
Как установить модуль ?
![screen](https://user-images.githubusercontent.com/41366638/42874015-c0303136-8a88-11e8-93d6-017556191c31.png)

**Comment by alexandrudima** [comment]
Duplicate of #54557
