### ISSUE TITLE
`code --help` from git bash terminal on windows now failing

### ISSUE THREAD

**Issue by dumbledad** [Microsoft/vscode#54561]
(N.B. There's a possibly related old issue [here](https://github.com/Microsoft/vscode/issues/1704))

Using VS Code as my commit message editor for git on Windows was working fine, but recently it fails. If I try `code --help` I get the same error message:

> /f/Program Files/Microsoft VS Code/bin/code: line 28: /Code.exe: No such file or directory  

I am using an odd version of Windows (18200.rs_prerelease.180716-1422), I do not know if that's a contributing factor in the error.

**Comment by joaomoreno** [comment]
Does `code --help` work from the Command Prompt?

**Comment by joaomoreno** [comment]
Seems to work fine over here.

What does `cat "$(which code)"` return?

**Comment by dumbledad** [comment]
>which code  
>/f/Program Files/Microsoft VS Code/bin/code

**Comment by joaomoreno** [comment]
The odd Windows version can explain it. You can try to figure out where it goes wrong by editing that script. For example, what is the value of `VSCODE_PATH` after computing it?

**Comment by dumbledad** [comment]
Sounds daft, but I don't know how to do that! I'll come back when I've worked out how to debug bash scripts on Windows!

**Comment by joaomoreno** [comment]
Yeah the interesting part is:

```
VSCODE_PATH="$(dirname "$(dirname "$(realpath "$0")")")"
```

This seems to result in an empty string. Does `dirname` and `realpath` work in your Bash?

**Comment by dumbledad** [comment]
Both are present. What is $0 when the call is made? I can try to reconstruct how 

> "$(dirname "$(dirname "$(realpath "$0")")")"

 ends up empty
