### ISSUE TITLE
font is not showing properly in ubuntu 18.04

### ISSUE THREAD

**Issue by emmyhayer** [Microsoft/vscode#54564]
- VSCode Version: 1.25
- OS Version: ubuntu 18.04

Steps to Reproduce:

1. font is not showing properly 

Does this issue occur when all extensions are disabled?: Yes/No yes
BTW i haven't installed any extensions yet

![screenshot from 2018-07-18 16-28-21](https://user-images.githubusercontent.com/12946963/42877565-be70781e-8aa7-11e8-9cdc-f2ddd4403bae.png)

**Comment by wondar-go** [comment]
my source folder in the folder where vscode is installed is missing after updating.....i don't konw what happend

**Comment by Tyriar** [comment]
@emmyhayer is the problem the lack of sub-pixel anti-aliasing? Can you share your settings.json file? Have you tried any other fonts?

**Comment by emmyhayer** [comment]
these are my settings, i am using default fonts

{
	"files.exclude": {
		".vscode": true
	},
	"window.zoomLevel": 0,
	"git.ignoreLegacyWarning": true,
	"editor.wordWrap": "on",
	"editor.minimap.enabled": false,
	"editor.rulers": [
		120
	],
	"editor.tabSize": 2,
	"editor.fontSize": 13,
	"workbench.colorTheme": "Solarized Light"
}

**Comment by emmyhayer** [comment]
i removed vscode and all data and released latest 1.25 version again and issue resolved
