### ISSUE TITLE
proper C and C++ syntax highlighting?

### ISSUE THREAD

**Issue by Castlespring** [Microsoft/vscode#54567]
I've installed VSCode and I am a really big fan of it, it's a nice and lightweight editor which would be perfect for working in C and C++ when you do not need the heavier Visual Studio version. I've added the C/C++ extension for debugging support, etc. I've also changed the theme to Dark.

One problem though... The syntax highlighting for C and C++ is totally off. My #define and #ifdef/#ifndef coloring is wrong and the definition name is colored differently to the #define, #ifdef and #ifndef which is not nice.

The real bugger is that when I have Windows.h included (or any header file containing its own type-definitions), type-definitions like NTSTATUS, BOOLEAN, ULONG, SIZE_T, etc. and structures will not be highlighted in a color. Only standard ones like "int", "bool" will be highlighted.

When using typedef struct _STRUCTURE_NAME, only that STRUCTURE_NAME will be highlighted, as well. If you did:

typedef struct _STRUCTURE_NAME {
...
} STRUCTURE_NAME, *PSTRUCTURE_NAME;

The STRUCTURE_NAME and PSTRUCTURE_NAME will not be highlighted in a color.

Could you please add an option to match syntax highlighting to the original Visual Studio versions (e.g. 2017 Professional) for C and C++, and fix the issue regarding syntax highlighting with type-definitions and structures?

Thx!

**Comment by aeschli** [comment]
This issue was moved to atom/language-c#281
