### ISSUE TITLE
Intellisense, add option to ignore lines

### ISSUE THREAD

**Issue by idlelimey** [Microsoft/vscode#54569]
At present I work with a system that uses custom template tags to output in to the page.  This breaks intellisense and disrupts the code colouring.  With JSHint, I can have it ignore certain lines using something like:

// ignore:[start|end]

It would be nice to be able to have an option to do something similar.  At present, I have to multiline comment a section of code for the syntax highlighting and intellisense to work properly.  I find these great features so I do not want to turn them off.

I've searched for similar feature requests but couldn't find anything.  If there's already an option for this please disregard and comment with a pointer.

Many thanks.

**Comment by alexandrudima** [comment]
You can create an extension that contributes a different grammar for `.js`. You can start from the current `.js` grammar and then modify it to match your new programming language (which is like `.js` but uses custom template tags).
