### ISSUE TITLE
Any reason why the header size is not 5

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#54570]
https://github.com/Microsoft/vscode/blob/5c5f93cdbcc763b94ed996d73ed4e5329e60d7a8/src/vs/base/parts/ipc/node/ipc.net.ts#L28

From my looking at the format, it appears one byte is spent to mark either isJson or not and another 4 bytes on the 32 bit length integer, giving a total of 5 bytes.

I wonder why don't we just save the extra 12 bytes per message and reduce the header length to 5 ?

**Comment by jrieken** [comment]
good question. might be some leftover from other work...
