### ISSUE TITLE
Issue with HTML comments & text hightlight

### ISSUE THREAD

**Issue by MrSantaCloud** [Microsoft/vscode#54576]
- VSCode Version: 1.25.1
- OS Version: Windows 10 x64 v.1803

This issue appears when using HTML comments to visually separate code regions.
Text appears as green, like it's commented, even if it's not, if it's wrapped between two lines of HTML comments made like: `<!---->`.
Please, see "steps to reproduce" for more details

Steps to Reproduce:

1. Write a comment using a syntax similar to the following: `<!--------->`, or having at least a dash `-` between the two comment tags `<!--` &` -->` without any space.
2. Duplicate the line. Write some uncommented HTML code between the two "lines".
3. All the text between the lines appears as green, but it's not commented.
4. If you add a space, text returns "normal" (EG: `<!-- ----- -->`)

EXAMPLE CODE:

```
<!----------------------------------------------------------------------------->
<div class="container">
    <div class="container"> bug </div>
</div>
<!----------------------------------------------------------------------------->
<!-- ------------------------------------------------------------------------ -->
<div class="container">
    <div class="container"> no bug </div>
</div>
<!-- ------------------------------------------------------------------------ -->
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by myfairsyer** [comment]
IIUC that's correct HTML: https://www.w3.org/TR/html5/syntax.html#syntax-comments

**Comment by myfairsyer** [comment]
IIUC that's as-designed for HTML 5.1: https://www.w3.org/TR/html51/syntax.html#comment
> the text must not [...] contain two consecutive U+002D HYPHEN-MINUS characters (--)

In HTML 5.2 it seems only to be prohibited to contain `-->`: https://www.w3.org/TR/html5/syntax.html#syntax-comments
> the text must not [...] contain the strings "", or "--!>"

"The text" refers to the part of the comment between opening and closing fragments
