### ISSUE TITLE
Console Windows Host high CPU usage

### ISSUE THREAD

**Issue by jimcroft** [Microsoft/vscode#54579]
Issue Type: <b>Bug</b>

Looking at Task Manager I can see that the Console Window Host subprocess of vscode regularly sits at around 30% CPU utilisation. This is the case even when I'm not actively using the integrated console and it's just sitting there at the prompt. 

VS Code version: Code - Insiders 1.26.0-insider (a7689a0eb1369afbb3d912cb38876a93e601ff06, 2018-07-18T05:19:07.488Z)
OS version: Windows_NT x64 10.0.17713

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (5.90GB free)|
|Process Argv|C:\Users\jim\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.18.0
githistory|don|0.4.2
gitlens|eam|8.5.1
git-project-manager|fel|1.6.1
gc-excelviewer|Gra|2.1.24
beautify|Hoo|1.3.2
rest-client|hum|0.19.0
puppet-vscode|jpo|0.11.0
vscode-github|Kni|0.30.0
python|ms-|2018.6.0
PowerShell|ms-|1.8.1
vsliveshare|ms-|0.3.395
seti-icons|qin|0.1.3
Ruby|reb|0.18.0
partial-diff|ryu|1.2.0
jenkinsfile-support|sec|0.1.0
code-settings-sync|Sha|3.0.0

</details>

**Comment by jimcroft** [comment]
[code-status.txt](https://github.com/Microsoft/vscode/files/2210320/code-status.txt)

**Comment by Tyriar** [comment]
@bitcrazed any ideas why the outer conhost would be using a lot of CPU?

**Comment by bitcrazed** [comment]
If VSCode is dormant, and nothing's being typed or running in the shell, ConHost shouldn't be doing much.

If it's eating 30% when dormant, I wonder whether an extension is thrashing in the background, looking for work to do.

Could you try running Task Manager, and disabling add-ons one after the other with 5-10s between each, to see if your ConHost's CPU utilization suddenly drops?

**Comment by jimcroft** [comment]
Thanks for that. 

Looks like it was being caused by a PowerShell module being loaded as part of my profile. Haven't confirmed which yet, but after disabling `AdvancedHistory`, `DirColors`, and `VSSetup` VSCode resting CPU usage back to normal.
