### ISSUE TITLE
Red files and Folders in Explorer

### ISSUE THREAD

**Issue by tunedin76** [Microsoft/vscode#54574]
Issue Type: <b>Bug</b>

I did a commit in GIT and revert (externally from VSCODE) all of the sudden I have myu .env file and node modules in red - like there is an error. There is none. 
The env file has not been changed, also in the ENV file, it turns all non quoted numbers and null to red - with no underline or tip
In node modules EVERY file is highlighted red, even text files in the directory.
NPM run dev compiles fine.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2630 0 @ 2.30GHz (24 x 2294)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.95GB (18.91GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|0.8.8
laravel-goto-view|cod|1.2.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vscode-mysql|for|0.3.0
mysql-syntax|jak|1.3.1
vscode-gist|ken|1.2.1
php-namespace-resolver|Meh|1.1.0
dotenv|mik|1.0.1
mysql-inline-decorator|odu|0.0.5
laravel-blade|one|1.18.0
material-icon-theme|PKi|3.5.1
laravel-artisan|rya|0.0.20
bootstrap4-vscode|the|4.3.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by tunedin76** [comment]
Yes

James

________________________________

**Comment by mjbvz** [comment]
We won't provide errors for a `.env` file out of the box. Are you sure all extensions are disabled and you have restarted vscode? Did you chance the language mode for that file?

**Comment by tunedin76** [comment]
Every single file In vendors is also red. And yes. Everything disabled still results in red

James

________________________________

**Comment by mjbvz** [comment]
What about language mode? Please provide a screenshot of this as well

**Comment by tunedin76** [comment]
I have to wait until Tuesday when I go back to work, I have VSCODE at my home, but it is not doing this. Seems something broke during a GIT transaction (from GIT BASH). I’ll get you a screeshot Tues.

**Comment by tunedin76** [comment]
![2](https://user-images.githubusercontent.com/16789318/43138606-6bfab87c-8f1d-11e8-8a4d-09827238f254.PNG)
![3](https://user-images.githubusercontent.com/16789318/43138607-6c0cd2e6-8f1d-11e8-9da3-84148f7ee190.PNG)
![4](https://user-images.githubusercontent.com/16789318/43138608-6c1ea7f0-8f1d-11e8-8652-e4b04e316d98.PNG)
![5](https://user-images.githubusercontent.com/16789318/43138609-6c2e3760-8f1d-11e8-9088-594c5cc870ad.PNG)
![1](https://user-images.githubusercontent.com/16789318/43138610-6c50ddec-8f1d-11e8-8fe8-e1546e44029c.PNG)

**Comment by tunedin76** [comment]
I wouldn't know, but EVERY file is marked in node modules and vendor folder (both of which have never been edited) could it possibly be an EOF or EOLN error... and is there a way I could check that?

**Comment by mjbvz** [comment]
This unrelated to intellisense. It is caused by cobalt2 theme which—from what I can tell at least—decided to color .gitignored files as red. You can disable explorer colorization this by setting `"explorer.decorations.colors": false`

Please file an issue against Cobalt2
