### ISSUE TITLE
Custom Title Bar behaves strangely when scaling up/down

### ISSUE THREAD

**Issue by TheTeapot418** [Microsoft/vscode#54575]
Issue Type: <b>Bug</b>

When scaling up the interface using Ctrl++, the custom title bar scales down. When scaling down using Ctrl+-, the custom title bar scales up. This bug only occurs when the scaling value is very high or very low.

![image](https://user-images.githubusercontent.com/11538064/42883802-ea71c356-8a9c-11e8-8c91-f34bb05569a0.png)

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500T CPU @ 2.70GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.89GB (0.84GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
cisco|jam|1.1.0
vscode-language-pack-fr|MS-|1.25.2

</details>

**Comment by sbatten** [comment]
related to #17180
