### ISSUE TITLE
False warning in an extension´s package.json on the icon attribute

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#54578]
On Windows.

Open the bundle VS Code npm extension.
Notice that the warning on the icon

![image](https://user-images.githubusercontent.com/172399/42886055-ea7a6802-8aa2-11e8-86a3-9fc139f9635d.png)

**Comment by chrmarti** [comment]
The warning is correct for extensions on the marketplace, it is only incorrect for our built-in extensions. We could add the `"repository"` to the package.json or let the linter ignore built-in extensions (not sure what a good check would though).

**Comment by egamma** [comment]
Seeing the warning for bundled extension is tolerable, closing the issue.
