### ISSUE TITLE
Auto-update hangs on installation, renders shortcuts invalid

### ISSUE THREAD

**Issue by dfinton** [Microsoft/vscode#54585]
- VSCode Version: 1.25.1
- OS Version: Windows 7

Steps to Reproduce:

1. When VS Code prompts you for an update, click on "Install update"
2. Update occurs, but when it's time to restart, the IDE hangs
3. Trying to relaunch via any of the shortcuts causes Windows to prompt the user to delete them because the targets no longer exist
4. I *am* able to relaunch VS Code by manually going into the Program Files subdirectory and clicking on the EXE file manually. From there I can re-pin the application and and create new shortcuts.

Does this issue occur when all extensions are disabled?: Not sure. It's difficult to test, but the extension updates do not cause any errors. Just the core product updates.

**Comment by joaomoreno** [comment]
What do you mean by _IDE hangs_? Is there a crash?

Does this happen all the time, or was it a one time thing?
