### ISSUE TITLE
globalState not updated?

### ISSUE THREAD

**Issue by Gruntfuggly** [Microsoft/vscode#54584]
My extension writes to the extensionContext.globalState object. However, if I read the object in another window, the state is not up todate?

**Comment by jrieken** [comment]
@Gruntfuggly The `update` function returns a promise. Does that resolve or reject?

**Comment by jrieken** [comment]
>However, if I read the object in another window, the state is not up todate?

And is it up to date in the current window?

**Comment by Gruntfuggly** [comment]
Yes - it's fine in the current window. I'll check the promise, although I think it resolves because if I reload the window it picks up the globalState change correctly...

**Comment by bpasero** [comment]
@Gruntfuggly can you attach a simple reproducible case for us to try out?

**Comment by bpasero** [comment]
This sounds a lot like https://github.com/Microsoft/vscode/issues/55834

**Comment by Gruntfuggly** [comment]
Yes, I think it's the same.
