### ISSUE TITLE
Closing last editor with Ctrl+W closes VS Code (regression)

### ISSUE THREAD

**Issue by rlipscombe** [Microsoft/vscode#54583]
(v1.25.1 appears to have reverted #1764.)

- VSCode Version: 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be)
- OS Version: Linux Mint 18.3

Steps to Reproduce:

1. Configure VS Code, per #1764 to ignore Ctrl+W if there are no editors open. See below.
2. Press Ctrl+W with no editors open.
3. Observe that VS Code closes. It shouldn't.

Does this issue occur when all extensions are disabled?: Yes

`~/.config/Code/User/keybindings.json` contains...

```
// Place your key bindings in this file to overwrite the defaults
[
    // Prevent Ctrl+W from closing the whole IDE
    {
        "key": "ctrl+w",
        "command": "-workbench.action.closeWindow",
        "when": "!editorIsOpen"
    }
]
```

Per the documentation at https://code.visualstudio.com/docs/getstarted/keybindings, this should work.

**Comment by rlipscombe** [comment]
It appears that #53730 has the correct, changed, incantation:

```
{
  "key": "ctrl+w",
  "command": "-workbench.action.closeWindow",
  "when": "!editorIsOpen && !multipleEditorGroups"
}
```

**Comment by bpasero** [comment]
Yes, https://github.com/Microsoft/vscode/issues/54583#issuecomment-405961434 is the correct solution. 

@rlipscombe did you see this documented somewhere in our docs?

**Comment by rlipscombe** [comment]
> did you see this documented somewhere in our docs?

No, I did not. I found the original solution in https://github.com/Microsoft/vscode/issues/1764#issuecomment-230674122, but filed this issue when it stopped working. The dupe robot pointed me at #53730, which has the solution. It could be better documented.

**Comment by bpasero** [comment]
@rlipscombe yes, we accept PRs for our documentation, if you want to give it a shot: https://github.com/Microsoft/vscode-docs/tree/vnext
