### ISSUE TITLE
Toggle Minimap won't work

### ISSUE THREAD

**Issue by frvo** [Microsoft/vscode#54589]
Issue Type: <b>Bug</b>

Menu/View/Toggle Minimap doesn't make any difference. Minimap won't go away.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4310U CPU @ 2.00GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.68GB (8.70GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Users\fvogliotti\Desktop\bluewater.sh|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.3.1
gitlens|eam|8.5.1
java|red|0.28.0
vscode-java-debug|vsc|0.10.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.7.1
vscode-maven|vsc|0.9.2

</details>

**Comment by alexandrudima** [comment]
@frvo Can you please check your User Settings, Workspace Settings and Folder Settings for `editor.minimap` ?

**Comment by frvo** [comment]
I'm sorry I omited one thing: this happens when I switched to the new interface custom in Window settings:
File/Preferences/Settings/Window/Title Bar Style -> switched to "custom"
When in "Native" mode, no problems whatsoever.
![captura de pantalla de 2018-07-20 01-18-29](https://user-images.githubusercontent.com/13700892/42983051-d6047692-8bba-11e8-8322-92bc15098a95.png)

**Comment by sbatten** [comment]
@frvo sorry for the bad experience. This issue should be resolved in the latest insiders. Would you be able to verify?

**Comment by frvo** [comment]
In fact I tested Insider version and yes, it works perfectly. Thank you!!

**Comment by sbatten** [comment]
@frvo thanks for verifying
