### ISSUE TITLE
Not able to debug Node program using WSL

### ISSUE THREAD

**Issue by isiah-lloyd** [Microsoft/vscode#54593]
- VSCode Version: 1.25.1
- OS Version: Windows 10 Home 1803

I'm trying to debug a Node application using Windows Subsytem for Linux but I don't think the paths are translating. 

This is my launch.json
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch NestJS",
      "useWSL": true,
      "console": "integratedTerminal",
      "runtimeExecutable": "npm",
      "runtimeArgs": [
        "run-script",
        "start:dev"
      ],
      "port": 5000,
    }
  ]
}
```
and this is what appears in my console after attempting to debug:
```
isiah@isiah-acer:/mnt/c/Users/Isiah/Documents/Programming_Projects/etc/podcast_db/new-api$ cd "c:\Users\Isiah\Documents\Programming_Projects\etc\podcast_db\new-api" ; "C:\WINDOWS\System32\bash.exe" -ic "npm run-script start:dev"
-bash: cd: c:\Users\Isiah\Documents\Programming_Projects\etc\podcast_db\new-api: No such file or directory
C:\WINDOWS\System32\bash.exe: command not found
```

And for further information `npm run-script start:dev` runs `nodemon` and here is my nodemon.json:
```
{
  "watch": [
    "src"
  ],
  "ext": "ts",
  "ignore": [
    "src/**/*.spec.ts"
  ],
  "exec": "node -r tsconfig-paths/register --inspect=5000 --require ts-node/register src/main.ts"
}
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
This is a complex setup which is not yet supported.

**Comment by n0v1** [comment]
I think this should work when removing `"console": "integratedTerminal"` from your launch configuration. `"useWSL": true` should be enough.

**Comment by offero** [comment]
@n0v1 Worked for me. Thank you!

**Comment by Tyriar** [comment]
We just announced remote development with VS Code, check out the blog post for details https://code.visualstudio.com/blogs/2019/05/02/remote-development
