### ISSUE TITLE
option to open folder in vs code in right click menu of mouse

### ISSUE THREAD

**Issue by jagdishjadeja** [Microsoft/vscode#54590]
when i want to open a project new(means never opened in vscode) i have to open vs code then go to open menu and open particular folder.
if project is old ( means already once opened in vscode) i can open that project from vs codes **open recent**  menu.
so what i was thinking is like can vs code add a feature or menu in my right click context menu like git has added, so that can vs code put an option in context menu of right click to open a folder directly in vs code  with few clicks ?
like here i have option to open git same for vs code.
![image](https://user-images.githubusercontent.com/17143515/42893754-d9ef1782-8ad2-11e8-937e-25ff546a7fdb.png)

**Comment by joaomoreno** [comment]
This is supported in the installer, there's a checkbox to enable that.
