### ISSUE TITLE
Menu: Custom context menus sometimes disappear right after opening

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#54594]
Issue Type: <b>Bug</b>

I haven't been able to reliably reproduce this, but it happens decently often.

To repo:
1. Right-click on a line in an editor (seems to happen more often if it is not the active line)
2. Most of the time the context menu will open, but sometimes it just flashes in and disappears

My guess is that it feels like some sort of conflict between showing a hover vs the context menu. And I'm not sure if GitLens plays a roll here or not (though it never happens with the native menus).

Another observation, it seems to be more likely to happen right after you've switched to a editor as well (either that or just becomes less likely after the menu has been shown already or something).

VS Code version: Code - Insiders 1.26.0-insider (a7689a0eb1369afbb3d912cb38876a93e601ff06, 2018-07-18T05:19:07.488Z)
OS version: Windows_NT x64 10.0.17713

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (18.27GB free)|
|Process Argv|C:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe C:\Users\Eric\code\vscode-gitlens|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by Tyriar** [comment]
@eamodio it just loves to classify things as terminal :sob:

**Comment by sbatten** [comment]
Looks like this happens when the contributor codelens info gets added to the editor which may trigger scroll which dismisses context menus.

/cc @bpasero

**Comment by sbatten** [comment]
possibly related #55309

**Comment by sandy081** [comment]
I saw this issue while testing https://github.com/Microsoft/vscode/issues/64282 today.

**Comment by sbatten** [comment]
@sandy081 was the behavior unique to the latest insiders or could you reproduce with stable

**Comment by sandy081** [comment]
I tested only on latest insiders did not try on stable

**Comment by formulahendry** [comment]
/confirm  
still repro on 1.30.0 stable version

**Comment by jrieken** [comment]
Sorry, I still this one and then. Not fixed, but also no steps. @sbatten can we add logging when programmatically(?) closing a menu, esp. withing 1sec of opening

**Comment by jrieken** [comment]
> or that it is actually dismissed?

That ⬆️ - unless the command is a no op. I think this happens when I open the context menu but not immediately interact with it. Can it be that while the menu is open and context-key events comes in, causing the menu (native. macOS) to hide?

**Comment by sbatten** [comment]
@jrieken oh, native case, alright, i'll dig into it

**Comment by sbatten** [comment]
This is now reproducing with the custom context menus as well. The scrollTop change does not appear to work anymore(fully?). Something to note is that in VS Code, with the custom titlebar enabled or using a mac, it is not possible to scroll the editor with the conext menu open. Thus, dismissing due to a scroll event is now wrong (I think). Dismissal due to scrolling seems like it was added for the benefit of monaco more than vs code. See https://github.com/microsoft/monaco-editor/issues/147

@alexandrudima @rebornix  Do you think we could switch to `wheel` event? This way, I believe, monaco's behavior should be preserved and vs code would not have this event triggered because of the blocking div when a context menu is open.

**Comment by alexandrudima** [comment]
@sbatten :+1: That could work well.
