### ISSUE TITLE
[themes] Add a "Recently Used" section at the top of the color themes menu

### ISSUE THREAD

**Issue by kjleitz** [microsoft/vscode#54597]
I often switch between a dark theme and a light theme, depending on where I am and how much light there is. If I'm outside or next to a bright window, I switch over to a light theme, because it's far easier to read text despite the glare. On the other hand, if I'm in a darker area or in the office, I much prefer a dark theme because the contrast is better and it's easier on the eyes. My usual method of switching themes involves opening the command palette (`⌘` `shift` `P`), selecting "Preferences: Color Theme" (you can also get here with `⌘` `K`, `⌘` `T`... _but muscle memory),_ and then having to scroll down/up to select my usual ones (specifically "Quiet Light" and "Tomorrow Night", not that it matters). I have a bunch of themes installed, so it tends to be faster to use the mouse to scroll up/down and select the right one, as opposed to navigating with the arrow keys. It's a bit of an interruption and minor pain.

So, my feature suggestion is to add a "Recently Used" section to the top of the menu to enable quick switching and easier navigation with the keyboard, much like the "Recently Used" section at the top of the root command palette menu. Right now, the three named sections in the menu are "Light Themes", "Dark Themes", and "High Contrast Themes", so the "Recently Used" section would be right at the top, above the "Light Themes" section.

**Current "Preferences: Color Theme" menu:**

![screen shot 2018-07-18 at 1 18 11 pm](https://user-images.githubusercontent.com/18669659/42897903-83991146-8a8f-11e8-8b1a-ddfa7ab84044.png)

**Current Command Palette menu (with "Recently Used" section at the top) as an example to model this feature after:**

![screen shot 2018-07-18 at 1 36 55 pm](https://user-images.githubusercontent.com/18669659/42897956-b55443c2-8a8f-11e8-8332-2d61454a1d06.png)

(I'm on version 1.25.1, if it matters to those reading!)

**Comment by aeschli** [comment]
You could, alternatively, directly modify the settings:
```
"workbench.colorTheme": "Default Dark+",
//"workbench.colorTheme": "Default Light+",

**Comment by kjleitz** [comment]
@aeschli I don't believe that solves the problem 😅The desire to have a "recently used" section is a result of _frequently_ switching between themes; changing the settings for the default isn't really useful in this context.

**Comment by kjleitz** [comment]
For the sake of posterity: this issue was actually resolved (for my use case, at least) by the recently-released "Toggle between Light and Dark themes" feature 🎉
