### ISSUE TITLE
C++: Single open brace in #define

### ISSUE THREAD

**Issue by CChelak** [Microsoft/vscode#54599]
In our company's code, we define namespaces as macros. An example is below:

    #define BEGIN_NAMESPACE_MYCODE namespace mycode {
    #define END_NAMESPACE_MYCODE }

I've notice however, that the syntax highlighter doesn't know how to handle the open bracket at the end of the define and the rest of the code becomes highlighted as if it were part of the macro. Oddly enough, the word `namespace` seems to be an equal culprit in this problem because defining something as follows doesn't mess up syntax highlighting:

    #define BEGIN_DONUT_TIME fried dough {

Any thoughts?

**Comment by aeschli** [comment]
This issue was moved to atom/language-c#280
