### ISSUE TITLE
Support goto symbol for markdown files

### ISSUE THREAD

**Issue by d4rkb1ue** [Microsoft/vscode#5459]
- VSCode Version: 1.0.0
- OS Version: os x 10.11.4

Steps to Reproduce:

1.open a markdown file like this:

``` md
#aaa

###ddd
```

2.press "shift+cmd+o" to open Goto Symbol feature "@"

always says: "we have no symbol information for this file."

**Comment by jcramirez** [comment]
Is this also not working for Python??

**Comment by tinganho** [comment]
I really need this feature!

**Comment by mjbvz** [comment]
I believe this was fixed by #16979 

Please give it a try in the next insiders build.

Thanks
