### ISSUE TITLE
Broken ${workspaceFolder} for multi-root workspaces.

### ISSUE THREAD

**Issue by paroxayte** [microsoft/vscode#54596]
When operating under a multi-root workspaces, files not created within vscode receive incorrect path from ${workspaceFolder}. Instead of receiving the top-most folder relative to the file's hierarchy, it always gets the top project's root path. The correct path is returned on files created by vscode.

- VSCode Version: 1.25.1
- OS Version: Debian 9.5 Stretch

Steps to Reproduce:

1. Open multi-root workspace
2. Define task with following command: `echo ${workspaceFolder}`
3. Navigate to source directory of folder not in topmost root folder -> `vi ./test` -> :wq 
4. Open the test file and run the command defined in step 2. Note that the topmost root-directory is returned instead of the file's root directory. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by dbaeumer** [comment]
@paroxayte I think there is a misunderstanding what ${workspaceFolder} returns. It doesn't return the workspace folder the currently active file is in. It returns the workspace folder in which the task is defined.

@isidorn does debug do something different. If we want to have the workspace folder of the active file we need a new variable IMO `fileWorkspaceFolder`

**Comment by isidorn** [comment]
@dbaeumer debug does not do something different. Note that it is possible to specify a specific workpsace folder using the following syntax
`${workspaceFolder:Server}` where Server is the name of my folder. If the name is not specified it resolves like @dbaeumer explained - based on the location of your tasks.json or launch.json

More details here https://code.visualstudio.com/docs/editor/multi-root-workspaces#_debugging

Yes a new variable could do this, but it sounds confusing and no other users asked for this so I would wait before adding something here.

**Comment by dbaeumer** [comment]
@isidorn thanks. Marking as a feature request then.

**Comment by alexr00** [comment]
@paroxayte can you give a real-world example of when you would use this?
