### ISSUE TITLE
[debug] launch.json validation shows warnings for extension debug adapters

### ISSUE THREAD

**Issue by daviwil** [Microsoft/vscode#546]
A user reported this on the vscode-powershell repo:

https://github.com/PowerShell/vscode-powershell/issues/20

When a user opens their launch.json to debug PowerShell scripts using my extension's debug adapter, they get a warning stating that the type is not an accepted value:

![image](https://cloud.githubusercontent.com/assets/79405/11368654/dc3a3aac-926f-11e5-8885-a0fb8af3202f.png)

There's also a warning which states that a property named "request" is missing.  These warnings cause the user to think that their launch.json file is configured incorrectly even though the debugger launches successfully.

I suppose the validation just hasn't been updated yet to account for non-node debug adapters?

**Comment by isidorn** [comment]
In the future we will make the `"request"` field required so that warning is correct. Using `"request"` we distinguish if we should launch or attach.

As for the type not being an accepted value I made a PR in your repo to fix that.

**Comment by daviwil** [comment]
Thanks for looking into this Isidor!  Next time I'll check the docs to make sure I didn't do things wrong :)
