### ISSUE TITLE
Editor panes are not auto resized when focused

### ISSUE THREAD

**Issue by oujiafan** [Microsoft/vscode#54608]
- VSCode Version: 1.25.1
- OS Version: macOS 10.13.4

Steps to Reproduce:

1. Drag a file from main editor pane to right side.
2. Click the right pane to focus.
3. In previous version of VSCode, the right editor pane should automatically resize and become major editor pane. But in current version it doesn't.

Does this issue occur when all extensions are disabled?: Yes

**Comment by V-ed** [comment]
Duplicate of #51614

**Comment by oujiafan** [comment]
Confirmed dup.
