### ISSUE TITLE
Change file import suggestion fail

### ISSUE THREAD

**Issue by ue** [Microsoft/vscode#54600]
When I change import or file name whatever from search bar. The suggestion appear woud you like to change file import etc. 
and its turn the fallow line

`import React, { Component } from '../../../../../../../Library/Caches/typescript/2.9/node_modules/@types/react';`

normal form as fallow
`import React, { Component } from 'react';`

**Comment by mjbvz** [comment]
Duplicate of #53597 

Fixed in VS Code insiders and if you upgrade to to use TypeScript 3.0 in your workspace (or downgrade to use TS 2.9.1)
