### ISSUE TITLE
remote debug for node process does not work any more with both version 1.25.0 and 1.25.1

### ISSUE THREAD

**Issue by jxhou** [Microsoft/vscode#54607]
- VSCode Version: vscode 1.25.0 and 1.25.1
- OS Version: windows 10

When remote debug a nodejs process running in local container, and hitting a breakpoint set in a  xxxx.js file, vscode display error message window with message: unable to open 'xxxx.js': File not found (the path to the file).

This nodejs container is running in virtualbox.

It works again, if reinstall 1.24.1.

I've got the following launch.json:
 "version": "0.2.0",
    "configurations": [
        
        {
            "type": "node",
            "request": "attach",
            "name": "Attach to Remote",
            "address": "localhost",
            "port": 9229,
            "localRoot": "${workspaceFolder}",
            "remoteRoot": "usr/src/app/"
        },

**Comment by weinand** [comment]
Could you please try the Insiders release?

**Comment by jxhou** [comment]
Have just tried the Insiders release. Show same error as 1.25.0 and 1.25.1.

**Comment by RoyHP** [comment]
We're still getting unverified breakpoint on 1.25.1 - supposedly this issue was fixed by #53785, but is not for us while remote debugging.
<img width="864" alt="screen shot 2018-07-19 at 5 06 51 pm" src="https://user-images.githubusercontent.com/1066439/42970104-6995ba32-8b76-11e8-8e59-e00326279edc.png">
<img width="831" alt="screen shot 2018-07-19 at 5 04 53 pm" src="https://user-images.githubusercontent.com/1066439/42970105-69a68222-8b76-11e8-9cb1-34980a08bd16.png">

**Comment by Yonatanper** [comment]
same issue for me on version 1.25.1

**Comment by roblourens** [comment]
@jxhou you have `"remoteRoot": "usr/src/app/"` shouldn't that be `/usr/src/app`? It must be an absolute path.

**Comment by roblourens** [comment]
@RoyHP you are describing different symptoms from @jxhou, please open a new issue. Please set `"trace": true`, try it again, and upload the log.

**Comment by roblourens** [comment]
Ok, I'm not sure why it worked before, but it shouldn't have :)

**Comment by ILNILEY** [comment]
It's weird, I have two computer, one for private, the other for work. The versions of VSCode in my computers are both v1.25.1. When I debugged in the one for work,there is no such problem.When I debugged in the other, break point is a gray hollow circle and tip that "Unverified breakpoint". 
![image](https://user-images.githubusercontent.com/23351345/43559056-e0358fdc-963e-11e8-92f6-dfc0ce5e8023.png)
