### ISSUE TITLE
`Edit in settings.json` link not visible in light themes

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#54603]
Issue Type: <b>Bug</b>

The link color matches the background on light themes:

![screen shot 2018-07-18 at 11 05 57 am](https://user-images.githubusercontent.com/3672607/42899365-acd244ca-8a7a-11e8-8523-5da8a1da4eef.png)
![screen shot 2018-07-18 at 11 06 14 am](https://user-images.githubusercontent.com/3672607/42899374-b0a96ba0-8a7a-11e8-93f0-f778c487e00e.png)

VS Code version: Code - Insiders 1.26.0-insider (a7689a0eb1369afbb3d912cb38876a93e601ff06, 2018-07-18T05:11:51.838Z)
OS version: Darwin x64 17.4.0

**Comment by roblourens** [comment]
`Colors.imagination`
