### ISSUE TITLE
Bring back typedef property expansion

### ISSUE THREAD

**Issue by zavr-1** [Microsoft/vscode#54609]
In the newer version, I can only see the type of an argument which is an object, compared to how it was expanded in the previous versions.

![test3](https://user-images.githubusercontent.com/21156791/42904849-3f94249c-8ace-11e8-91bb-8a09063e9d30.png)

It was actually very useful to see all properties on hover which served as a documentation. 

![test4](https://user-images.githubusercontent.com/21156791/42905747-d387673e-8ad0-11e8-92c8-ddf31e9d7f92.png)

I think if you hide the details of the type, you should also provide means to expand its properties via a UI, or provide a setting for it.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#25784
