### ISSUE TITLE
Receive message "Failed to install VS Code update ..." for 1.25.0 to 1.25.1

### ISSUE THREAD

**Issue by KentonHensley** [Microsoft/vscode#54604]
Steps to reproduce:

1. Click "Install Update" prompt from VS Code
2. Get prompted for elevated permissions. 
3. Log in using my administrative account. => VS Code reports it is installing update in the background.
4. VS Code prompts with message to restart to install update. => Immediately after this, the display becomes unresponsive (mouse, keyboard don't work).
5. Press Ctrl-Alt-Del then Esc. => Display is freed up
6. Click VS Code Install Update to restart VSC and install update. => VS Code restarts and then displays error message "Failed to install  VS Code update." Note that on restart, there is no opportunity to log in with elevated permissions. So, I also tried closing VS Code and restarting it with administrator permissions. Result is the same for both.

I tried three separate times.
_______
Version: 1.25.0
Commit: 0f080e5267e829de46638128001aeb7ca2d6d50e
Date: 2018-07-05T13:11:58.697Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2206828/vscode-inno-updater.log)
![image](https://user-images.githubusercontent.com/26150265/42899063-f01adc8e-8a92-11e8-9eb2-5be0739a9681.png)

**Comment by joaomoreno** [comment]
You seem to have #47841.

Please read this comment if you can provide more detail: https://github.com/Microsoft/vscode/issues/47841#issuecomment-393101777

Please read this one to disable background updates: https://github.com/Microsoft/vscode/issues/47841#issuecomment-395017687

Also read this one to provide feedback on our new user setup: https://github.com/Microsoft/vscode/issues/47841#issuecomment-399941682
