### ISSUE TITLE
export default breaks typedef in JSDoc

### ISSUE THREAD

**Issue by zavr-1** [Microsoft/vscode#54606]
- VSCode Version: 1.25.1
- OS Version: 10.13.1

![test1](https://user-images.githubusercontent.com/21156791/42900049-c9434092-8abf-11e8-8c54-2ba46f28bff6.png)

Exporting a function as default will result in breaking of a type annotation. 

![test2](https://user-images.githubusercontent.com/21156791/42900050-c9657c66-8abf-11e8-94d1-ee6a1925c53d.png)

The solution is to place `export default fn` after the `typdef`.

Does this issue occur when all extensions are disabled?: Yes

**Comment by zavr-1** [comment]
@andy-ms but I don't use Typescript, and it's true it was a typo for `the` but also doesn't work when fixed.

**Comment by andy-ms** [comment]
Vscode uses TypeScript when editing js files. Updating the TypeScript version used by the editor should fix the issue.

**Comment by zavr-1** [comment]
@andy-ms yeah but I'm also thinking of my users who will want the JSDoc to work.

**Comment by andy-ms** [comment]
They'll just have to wait for TS to be updated in vscode then -- we're not doing any more 2.9 releases.

**Comment by zavr-1** [comment]
@andy-ms yep I understand that. Thank you for checking if it works in the newer versions. I think this can be closed now unless it needs to be open until the bug is actually fixed in a released version.
