### ISSUE TITLE
Peek window still opens when executing "Go to definition"

### ISSUE THREAD

**Issue by craxal** [Microsoft/vscode#54611]
# Repro Steps
1. Open a Typescript file that imports and uses a type or function from another Typescript file.
2. Position cursor over type/function defined in other Typescript file and press F12.

# Expected
I expect the other Typescript file to open at the location of the type/function definition.

# Actual
The other Typescript file opens at the correct location, but the Peek window also opens, which is redundant and distracting.

![image](https://user-images.githubusercontent.com/3473026/42906210-4ed68074-8a8f-11e8-8c49-63b93e651f15.png)

**Comment by mjbvz** [comment]
Are you running VS Code insiders?

**Comment by craxal** [comment]
No.

**Comment by mjbvz** [comment]
This should be fixed on insiders. Please try using that
