### ISSUE TITLE
Test: "Open in Terminal" not working on Fedora

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#5461]
Test plan for #4478

- [x] Fedora @aeschli

### Basic test case

1. Open a folder
2. Right click a folder in the explorer
3. Select open in terminal

**Comment by aeschli** [comment]
On my freshly installed Fedora 23 install I get the following error when invoking 'open in terminal':

`shell.ts:415spawn x-terminal-emulator ENOENT: Error: spawn x-terminal-emulator ENOENT`

I reopen #4478
