### ISSUE TITLE
Allow to specify files to ignore for HTML and other formatters

### ISSUE THREAD

**Issue by garyking** [microsoft/vscode#54617]
I use the HTML formatter in VSC by enabling `editor.formatOnSave`. However, there are some files, including HTML ones, that I want to NOT format on save. Therefore, please allow us to specify an ignore file, using a format similar to `.gitignore`, to not format on save, when this file exists in a project's root dir. 

Thanks!

**Comment by aeschli** [comment]
In the settings you can already specify this:
```
"[html]: {
  "editor.formatOnSave": false
}

**Comment by garyking** [comment]
I specifically have the following setting, in order to enable formatting on save for HTML files:

```json
"[html]: {
  "editor.formatOnSave": true
}
```

But I want to be able to specify that *specific* files don't get auto-formatted, just like I can in a `.gitignore` file. So I don't want `dist/index.html` to be auto-formatted, for instance.

**Comment by shaneknysh** [comment]
I'd like this feature for targeting specific files as well.

Particularly package.json for contributing to open source. If you change something as small as the version number on a dependency it will reformat the entire file triggering from a few to hundreds of changes.

I can create a second ticket and relate it to this one if required.

**Comment by jrieken** [comment]
Closing as this didn't get much upvotes - Having said that some of the scenarios here can be tackled via "save without formatting"

**Comment by shaneknysh** [comment]
I understand that this is not a popular request but the "save without formatting" comment is not a solution. In a project with 50 files turning off formatting on 47 of those files - which I want to have formatting on - so that 3 of them don't get formatted is undesirable.
