### ISSUE TITLE
VSCode window is out of view when 2nd monitor is disconnected

### ISSUE THREAD

**Issue by fatherjack** [microsoft/vscode#54610]
Issue Type: <b>Bug</b>

Steps to reproduce
Run VSCode on a laptop with an external monitor and displaying VSCode on the 2nd monitor.
Set the laptop to sleep / hibernate by closing the lid.
Disconnect the external monitor.
Start the laptop.
VSCode doesnt open on the laptop screen  and it cannot be brought to the screen by Win + left arrow or Win + Right arrow.

The only solution is to close VSCode from the taskbar and then reopen it.
When reopened it starts correctly on the laptop screen.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.88GB (41.03GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|0.11.1
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.59
vscode-markdownlint|Dav|0.18.0
docs-article-templates|doc|0.1.2
docs-authoring-pack|doc|0.1.1
docs-markdown|doc|0.1.2
docs-preview|doc|0.3.12
xml|Dot|2.3.1
gitlens|eam|8.5.1
tslint|eg2|1.0.34
json-tools|eri|1.0.2
DocFX|ms-|0.1.3
mssql|ms-|1.4.0
PowerShell|ms-|1.8.1
vsliveshare|ms-|0.3.395
team|ms-|1.136.0
vscode-docker|Pet|0.0.27
material-icon-theme|PKi|3.5.1
code-settings-sync|Sha|3.0.0
vscode-spotify|shy|2.5.0
code-spell-checker|str|1.6.10
vscode-wakatime|Wak|1.2.3

(1 theme extensions excluded)

</details>

**Comment by fatherjack** [comment]
from left to right, 23"monitor, 23"monitor, HP laptop screen, windows has labelled these as 3,2,1 when I click Identify. The middle monitor is the one considered my main display.

So, running VSCode on far left (the screen that identifies as #3 ) and closing the laptop (hibernate) and then opening the laptop with no external monitors connected results in VSCode still running but not being visible on the laptop screen.

**Comment by MrGlenThomas** [comment]
I have the same problem, the window remains off-screen after disconnecting a monitor that it was being displayed on. You can bring the window to the main screen by 'maximizing' it from the taskbar.

**Comment by fatherjack** [comment]
"an upstream component" ??? Other apps dont suffer with this problem. Its something within VSCode in my opinion.
