### ISSUE TITLE
Terminal: Run Active File doesn't POSIX-ify filepaths for bash

### ISSUE THREAD

**Issue by JacksonKearl** [Microsoft/vscode#54613]
Issue Type: <b>Bug</b>

When I run "Terminal: Run Active File" with bash as my terminal, it puts something along the lines of:
```bash
$ c:\Users\t-jakea\Developer\vscode\src\vs\workbench\browser\parts\menubar\menubarPart.ts
bash: c:Userst-jakeaDevelopervscodesrcvsworkbenchbrowserpartsmenubarmenubarPart.ts: command not found
```

It should convert the filepath to be POSIX-ish:
```
$ c:/Users/t-jakea/Developer/vscode/src/vs/workbench/browser/parts/menubar/menubarPart.ts
```

VS Code version: Code - Insiders 1.26.0-insider (a7689a0eb1369afbb3d912cb38876a93e601ff06, 2018-07-18T05:19:07.488Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (7.46GB free)|
|Process Argv|C:\Users\t-jakea\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.0.0
vscode-svgviewer|css|1.4.4
gitlens|eam|8.5.1
tslint|eg2|1.0.34
Go|ms-|0.6.84
debugger-for-chrome|msj|4.8.0
vetur|oct|0.12.5
subtle-brackets|raf|2.1.1
vscode-multiclip|sle|0.1.4
code-spell-checker|str|1.6.10

(1 theme extensions excluded)

</details>

**Comment by JacksonKearl** [comment]
```javascript
if (platform === Platform.Windows && instance.shellLaunchConfig.executable.indexOf('bash') !== -1) {
    instance.sendText(uri.fsPath.replace(/\\/g, '/'), true);
} else {
    instance.sendText(uri.fsPath, true);
}
```
at https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/terminal/electron-browser/terminalActions.ts#L642 seems to fix this, but specific to bash on windows. Not sure if theres another case where this would happen.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/36897
