### ISSUE TITLE
can not pass environment variable values to debugger

### ISSUE THREAD

**Issue by syendev** [Microsoft/vscode#54615]
Issue Type: <b>Bug</b>

similar to https://github.com/Microsoft/vscode/issues/45423

node v10.6.0
npm 6.1.0
launch.json contents:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "useWSL": true,
            "runtimeArgs": [
                "--experimental-modules"
            ],
            "env": {
                "SQLITEFILE": "chap07.sqlite3",
                "NOTESMODEL": "sqlite3"
            },
            "program": "${workspaceFolder}\\bin\\www.mjs"
        }
    ]
}
```
cannot access NOTESMODEL via process.env.NOTESMODEL

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) m3-7Y30 CPU @ 1.00GHz (4 x 1608)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (3.72GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
Handlebars|and|0.4.1
vscode-eslint|dba|1.4.12
mssql|ms-|1.4.0
cpptools|ms-|0.17.6
debugger-for-chrome|msj|4.8.0
html-css-class-completion|Zig|1.17.1

</details>

**Comment by Tyriar** [comment]
We just announced remote development with VS Code, check out the blog post for details https://code.visualstudio.com/blogs/2019/05/02/remote-development
