### ISSUE TITLE
jsdoc on functions within object does not seem to work

### ISSUE THREAD

**Issue by flowt-au** [Microsoft/vscode#54619]
I am wanting to auto-generate the jsdoc for functions within objects using the `/**` autocomplete.

I searched SO to no avail. It seems unsupported?

ie This works:

    /**
     * 
     * @param {*} a 
     * @param {*} b 
     */
    function calc(a,b){

    }

But this does not:

    var obj = {
        /**
         * 
         */
        calc: function(a,b){

        }
    }

Is this missing functionality or am I doing something wrong?

Thanks.

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/vscode/issues/54619 to track this upstream
