### ISSUE TITLE
Azure Extensions have a circular dependency so they can't be disabled

### ISSUE THREAD

**Issue by pcannons** [Microsoft/vscode#54621]
Issue Type: <b>Bug</b>

Trying to disable all extensions temporarily and noticed the Azure extensions are dependent on each other so it's impossible to disable them. 

![image](https://user-images.githubusercontent.com/1009566/42914292-767529d6-8aae-11e8-8453-bd439183f784.png)

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz (4 x 3300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (2.05GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
azure-event-hub-explorer|Sum|0.1.2
azuretoolsforvscode|bra|2.0.2
azure-storage-explorer|for|0.1.2
vscode-azureappservice|ms-|0.9.0
vscode-azurefunctions|ms-|0.9.1
vscode-azurestorage|ms-|0.4.0
azure-account|ms-|0.4.2
azurerm-vscode-tools|msa|0.4.2
usql-vscode-ext|usq|0.2.14

</details>

**Comment by sandy081** [comment]
@pcannons How are you trying to disable all extensions? Is it through the command `Disable All Installed Extensions` or one by one?

**Comment by pcannons** [comment]
I was going through one by one. 

Sent via Superhuman ( https://sprh.mn/?vip=philipp.cannons@gmail.com )

**Comment by sandy081** [comment]
@pcannons If you are going one by one then you have to disable the extension that depends on another extension before disabling it.

**Comment by pcannons** [comment]
Right, but the Azure plugins all depend on each other.

I went through the whole list and tried to disable each one, one by one, and it wouldn’t let me. So if there’s a circular dependency you can’t uninstall, which is frustrating.

**Comment by sandy081** [comment]
@pcannons Can you please list out the azure extensions which has circular dependencies. I would like to go through them and reproduce it.

**Comment by pcannons** [comment]
Sure, here is the list that causes it:
![image](https://user-images.githubusercontent.com/1009566/43233608-a1bc9c28-902b-11e8-9ccf-ddb294dbdc92.png)

Here's a video of my reproducing it:
https://www.dropbox.com/s/pajce090vbg8qqh/CantDisableAzureExtensionsVS.mov?dl=0

**Comment by sandy081** [comment]
I see the issue. You can disable extension by extension. I mean when you get a prompt to disable with or without dependencies, select disabling without dependencies. This will work.

But, I have a feature request to not show the prompt if there is another extension depending on the dependency of the current extension. #55118

So, I will mark this as dup of it.
