### ISSUE TITLE
VSCode have process "Code Helper" always run over 100% CPU

### ISSUE THREAD

**Issue by KytoSai** [Microsoft/vscode#54627]
- VSCode Version: 1.25.1
- OS Version: 10.13.6

VSCode have process "Code Helper" always run over 100% CPU
Demo: http://prntscr.com/k89vav

Does this issue occur when all extensions are disabled?: Yes

I have attempt to reboot laptop multiple times. But It still happen run over 100% CPU

**Comment by alexandrudima** [comment]
@KytoSai In order for us to try to understand what is going on, can you please follow the guide at https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by alexandrudima** [comment]
@jadchaar Filing a separate issue is good, as you might be running into a different issue which just happens to have the same symptoms (high cpu usage). 

@KytoSai Did you get a chance to look at https://github.com/Microsoft/vscode/wiki/Performance-Issues and give us some steps?
