### ISSUE TITLE
Auto-complete won't work for a few seconds, after running `yarn install`

### ISSUE THREAD

**Issue by garyking** [Microsoft/vscode#54624]
- VSCode Version: Version 1.25.1 (1.25.1)
- OS Version: macOS 10.13.5 (17F77)

Steps to Reproduce:

1. Create a Node project.
2. Run `yarn install moment`
3. Auto-complete won't work in any VSC JS file, until I think the "Fetching better TypeScript Intellisense" message appears and disappears from the status bar.

Does this issue occur when all extensions are disabled?: Yes

I can see that Code Helper uses 100% while the auto-complete is inactive, so clearly VSC is trying to do something, and therefore it's blocking all other features from working, for that moment. Sometimes, it even lasts indefinitely. It might have something to do with VSC trying to read the `yarn.lock` file?

**Comment by jesseyang0626** [comment]
i have the same problem

**Comment by mjbvz** [comment]
Using the latest VS code release (1.27) please try collecting the TS Server log:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a folder with a `tsserver.log` file in it

 If you can share the log, someone on the TS team or I can take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this
