### ISSUE TITLE
vs code not  reading multiple git repos in one folder but on windows it is (GIT)

### ISSUE THREAD

**Issue by emmyhayer** [Microsoft/vscode#54629]
- VSCode Version: 1.25
- OS Version: ubuntu 18.04

Does this issue occur when all extensions are disabled?: Yes/No
YES

on windows => 
![vscode_windows_git png](https://user-images.githubusercontent.com/12946963/42925657-807c4ab0-8b4c-11e8-939b-e8df89f17498.png)
on ubunu =>
![vscode_ubuntu_git](https://user-images.githubusercontent.com/12946963/42925681-90ea25de-8b4c-11e8-9c5d-59b0ae976858.png)

**Comment by joaomoreno** [comment]
Do you open the same folder on both systems? Can you show me the folder hierarchy?

**Comment by emmyhayer** [comment]
yes it is working

**Comment by joaomoreno** [comment]
And do both repositories show up if you open a file within each?

**Comment by emmyhayer** [comment]
yes if i open individually repo in editor it shows git changes
you can see here 

![screenshot from 2018-07-19 16-24-29](https://user-images.githubusercontent.com/12946963/42938581-611e7750-8b70-11e8-927f-e5671dca3fcc.png)

**Comment by joaomoreno** [comment]
Got it. The only setting which can configure this is `git.autoRepositoryDetection`. Are you sure you haven't configured it in Linux?

**Comment by emmyhayer** [comment]
i dont know about it, can u tell me how i can configure it or check it ?

**Comment by emmyhayer** [comment]
i removed vscode and all data and released latest 1.25 version again and issue resolved
