### ISSUE TITLE
Settings editor shifts up and down with row selection

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#54626]
I've decided to file this separate of #54039, since that one is becoming a greater discussion.

If we decide the keep row focus, there are two issues:

- Rows below the selected one get shifted down even when there's no additional text to render
- Clearing the row selection takes 2x <kbd>Escape</kbd> presses

![peek 2018-07-19 08-06](https://user-images.githubusercontent.com/22350/42924511-d48e3e28-8b2a-11e8-914e-e902546d294b.gif)

**Comment by roblourens** [comment]
I can't repro the first, although that has broken before. Are you zoomed in or something?

The second, since I hide focus vs selection I think this is going from row selected -> row focused -> tree focused. It can be better.

**Comment by joaomoreno** [comment]
> Rows below the selected one get shifted down even when there's no additional text to render

This is on Linux.

**Comment by roblourens** [comment]
Do you still see this? Lots of css has changed. I tested on Linux today and it looks ok.
