### ISSUE TITLE
Add HTML & CSS propertyor tag in  PHP intellisence

### ISSUE THREAD

**Issue by gaurav9643** [Microsoft/vscode#54633]
Issue Type: <b>Feature Request</b>

Add HTML & CSS propertyor tag in  PHP intellisence

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:11.471Z)
OS version: Windows_NT ia32 10.0.16299

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/670
