### ISSUE TITLE
User Settings, updateImportsOnFileMove.enabled is not work as image

### ISSUE THREAD

**Issue by onpaik** [Microsoft/vscode#54634]
when I set **javascript.updateImportsOnFileMove.enabled": "prompt"**, 

![three](https://user-images.githubusercontent.com/34502769/42978003-f7628b98-8bfc-11e8-846f-046f376001ee.png)

1: step one , the original code 
```
import React from 'react';
import { fromJS } from 'immutable';
import {
  required,
  mobileNumber,
  email,
} from 'shared/utils/validate';
import { bankList } from 'shared/consts/bankList';
import { bankList1 } from 'shared/consts/bankList1';
import { addressList } from 'shared/consts/addressList';
import { addressNoArea } from 'shared/consts/addressNoArea';
```
2: step two: change the file bankList  name as other name,
3: vscode will prompt a modal some, like this 

![one](https://user-images.githubusercontent.com/34502769/42977931-9ac97978-8bfc-11e8-83d6-11223dfc0580.png)

3: so,  the import path changed to relative, change  like below in all file all import
![two](https://user-images.githubusercontent.com/34502769/42977939-a896d78a-8bfc-11e8-8396-c778ca1f560b.png)

```
import React from '../../../../../../../../../../Library/Caches/typescript/2.9/node_modules/@types/react/index';
import { fromJS } from '../../../../../../../../../../Library/Caches/typescript/2.9/node_modules/immutable/dist/immutable-nonambient';
import {
  required,
  mobileNumber,
  email,
} from '../../../../../../shared/utils/validate';
import { bankList } from '../../../../../../shared/consts/bankList';
import { bankList1 } from '../../../../../../shared/consts/bankList1';
import { addressList } from '../../../../../../shared/consts/addressList';
import { addressNoArea } from '../../../../../../shared/consts/addressNoArea';

```

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by onpaik** [comment]
@mjbvz pease ckeck

**Comment by TSiege** [comment]
This is really annoying and is happening to me as well on vscode 1.25.1 (as of posting the latest version). It frustratingly doesn't seem to happen to me every time I move a file, but maybe %50 of the time. It's happening only with importing 3rd party libraries, and I have the following in my User Settings `"javascript.updateImportsOnFileMove.enabled": "always"`.

Here is an example output after moving files:
```
import bluebird from '../../../../../../Library/Caches/typescript/2.9/node_modules/@types/bluebird'
```

**Comment by mjbvz** [comment]
@onpaik Did you try in insiders?

**Comment by tomergev** [comment]
This is a horrible bug and very frustrating!

**Comment by thienedits** [comment]
I am on Windows 10, vscode 1.26.1 and typescript 3.0.1 and the prompt never appears for me after moving a folder location.
