### ISSUE TITLE
As a user, clicking a extension identifier, when reviewing the extension, should copy it to the clipboard

### ISSUE THREAD

**Issue by Amaranthos** [Microsoft/vscode#54639]
As a nice quality of life improvement, it would be nice to be able to copy an extension's identifier with a single click. This would make it easier for including the extension as a recommendation, etc.

Thanks everyone for a great tool.

**Comment by ramya-rao-a** [comment]
From VS Code 1.25 onwards, there is a command to add current extension to workspace recommendations.
See [Manage Workspace Recommendations](https://code.visualstudio.com/updates/v1_25#_manage-workspace-recommendations)

Is there any other scenario where the single-click => copy to clipboard feature would be useful?

**Comment by Amaranthos** [comment]
That covers my use case nicely. I'm not sure of other scenarios where this request may be useful, so can probably close this one.

Thanks

**Comment by ramya-rao-a** [comment]
In that case, I'll close this issue @Amaranthos 
Happy Coding!
