### ISSUE TITLE
Why is there no declearation of the method named 'createDataChannel' in 'RTCPeerConnection' ?

### ISSUE THREAD

**Issue by gyc1299339354** [Microsoft/vscode#54632]
![wx20180719-152509](https://user-images.githubusercontent.com/8892634/42927747-fb1ea73e-8b67-11e8-93e3-972a3de09c3f.png)
<img width="1182" alt="wx20180719-152449 2x" src="https://user-images.githubusercontent.com/8892634/42927774-0944f2be-8b68-11e8-9bbe-0860ecc35528.png">

**Comment by alexandrudima** [comment]
@gyc1299339354 Did you mean to open this issue against another project? What is the VS Code issue here ?

**Comment by gyc1299339354** [comment]
emm...yes...I mean that if we open an issue for this question and I have found no issues like this~☺

**Comment by stringparts** [comment]
This is a Typescript issue, not VS Code. Open an issue on [Microsoft/TypeScript](https://github.com/Microsoft/TypeScript)

(Typescript's WebRTC typings seem a bit old, install `@types/webrtc` to get better types.)

**Comment by gyc1299339354** [comment]
oh ~ thanks guys ~
