### ISSUE TITLE
Import referenceSearch in standaloneReferenceSearch.ts

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#54635]
‘vs/editor/contrib/referenceSearch/referenceSearch’ is only imported in editor.all. When using the webpack plugin only standaloneReferenceSearch is loaded, but not referenceSearch. One effect is that 'Find All References' is missing from the context menu.

**Comment by alexandrudima** [comment]
Let's track in https://github.com/Microsoft/monaco-editor-webpack-plugin/issues/26
