### ISSUE TITLE
Context menu is rendered outside the window, when there's still space for it

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#54630]
Some math seems to be off when calculating the necessary space for that menu. Are you using the context view? If so, just leave this for me.

![peek 2018-07-19 08-56](https://user-images.githubusercontent.com/22350/42926426-a6f26974-8b31-11e8-93f3-cbb907ca0608.gif)

**Comment by sbatten** [comment]
yes for context menus (not menubar menus) context view is being used.

**Comment by joaomoreno** [comment]
Verifier: make sure that context menus (using custom UI on Windows or Linux) are always contained within the workbench.
