### ISSUE TITLE
Text selection performance is poor on 1.0 alpha

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#5464]
- VSCode Version: 1.0.0-alpha
- OS Version:Windows 10

Steps to Reproduce:
1. Open vscode-docs vnext branch in VS Code and open the vMarch.md file.
2. Go to the Downloads: section which has 8 links for the various VS Code platform flavors.
3. Select some text with the mouse from the first line.  - seems fine
4. Select some text with the mouse from the last line (ex. 32 bit .rpm link) - really slow.
   Note: default word wrap of 300 characters is set.
   Does not repro on 1.0.0-stable

**Comment by OneOfOne** [comment]
Why are you reporting a bug on an alpha release that you said doesn't happen on the stable release?

**Comment by gregvanl** [comment]
Hi @OneOfOne, I can see how that name would be confusing.  "Alpha" is the name of the Microsoft internal latest builds of VS Code.  It has the very latest changes before we release to the Insiders build (weekly) and stable (monthly).  We test alpha internally to find issues early.

**Comment by alexandrudima** [comment]
@gregvanl Are you still seeing this? 

I've made quite a number of changes in selection perf (especially the writing to the native textarea part that was causing slowness when selecting)

**Comment by alexandrudima** [comment]
@gregvanl ping -- Do you have a laptop with a touchscreen?

**Comment by alexandrudima** [comment]
Closing after a number of days without a response

**Comment by gregvanl** [comment]
Sorry, @alexandrudima, I missed your earlier comments. This issue no longer repro's on 1.12.2. Likely fixed long ago.
