### ISSUE TITLE
Hover tooltip shows eternal "Loading..." even though LS send the response

### ISSUE THREAD

**Issue by philcolol** [Microsoft/vscode#54640]
Hi,

The issue seem to have a very peculiar set of conditions to reproduce:
1. It only reproduces when returned Hover object has empty list in "contents" field. Issue does not reproduce if contents isn't present at all:
![image](https://user-images.githubusercontent.com/11789456/42936490-e1ce14ee-8b54-11e8-8b02-5dad41559be7.png)
2. It only reproduces if hover calculation took some time (experimentaly it seems to be 750-800+ ms, but it might be machine dependant):
![image](https://user-images.githubusercontent.com/11789456/42936506-eade3190-8b54-11e8-9f1e-7656b472e194.png)
![image](https://user-images.githubusercontent.com/11789456/42936521-fac42344-8b54-11e8-8fed-d9ef0dd92451.png)
3. Our Language Server is based on java and uses [lsp4j](https://github.com/eclipse/lsp4j) (version 0.4.0.M6) library. I couldn't reproduce the issue on JS language servers. 

- VSCode Version: 1.25.1
- OS Version: Win10

**Comment by alexandrudima** [comment]
I have tried to reproduce with the following extension:

* `package.json`:
```json
{
    "name": "54640",
    "publisher": "alex",
    "version": "0.0.0",
    "engines": {
        "vscode": "^1.22.0"
    },
    "activationEvents": [
        "*"
    ],
    "main": "./index.js"
}
```

* `index.js`:
```js
const vscode = require('vscode');
const fs = require('fs');

exports.activate = function() {

	vscode.languages.registerHoverProvider('plaintext', {
		provideHover: (document, position) => {
			return new vscode.Hover([]);
//			return new vscode.Hover([`hello`]);
		}
	});

};
```

and I cannot reproduce. I suspect this might be affecting the LSP VSCode client.

**Comment by dbaeumer** [comment]
I am not able to reproduce this either in an LSP setup using the following code to return a hover.

```
	return new Promise((resolve, reject) => {
		setTimeout(() => {
			resolve({ contents: []});
		}, 920);
	});
```

The Hover response is like this:
```
[Trace - 12:05:14 PM] Received response 'textDocument/hover - (20)' in 922ms.
```

and the 'Loading' disappears correctly.

You could debug the LSP client code and see if there is something going wrong when converting the Hover result. The code is here: [Trace - 12:05:14 PM] Received response 'textDocument/hover - (20)' in 922ms.
