### ISSUE TITLE
Feature request: Disable color swatches but keep color picker enabled.

### ISSUE THREAD

**Issue by justablob** [Microsoft/vscode#54648]
I'm looking for a way to disable the little color swatches next to color strings in CSS because I'm using the Color Highlight extension, however I want to keep the color picker enabled as it's simply the best color picker for VS Code and it's also a built-in feature.

**Comment by niderhoff** [comment]
Duplicate of #34341, #59696?

**Comment by justablob** [comment]
Yup, dupe :(
