### ISSUE TITLE
Inconsistent behavior of opening a file under a symlink folder.

### ISSUE THREAD

**Issue by tinysnake** [Microsoft/vscode#54643]
Issue Type: <b>Bug</b>

It's hard to explain, so I write down my test step, hope you can understand.

I have my code project in **D:\my-proj**
I have a folder I want to demonstrate in **D:\origin-folder**
Then I run this command in CMD: `mklink /j D:\my-proj\junction-folder D:\origin-folder`(please note: if I change the parameter /j to /d will do the same)
Now I open the **D:\my-proj** folder with vscode, and then open the **junction-folder\test.txt** file using the **vscode explorer tab**. if I hover my mouse to that tab header of the opened file, I will display the absolute path as: 

> **D:\my-proj\junction-folder\test.txt**

And I open the file throgh command line: `D:\my-proj> code .\junction-folder\test.txt`, then vscode will open it as a different file, and the path is: 

> **D:\origin-folder\test.txt**, the origin path but not the symlinked path

It should be **D:\my-proj\junction-folder\test.txt**, but somehow vscode resolve the origin path of that symlinked file.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz (8 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (1.93GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
shaderlabvscodefree|aml|1.1.0
vscode-csharp-snippets|jor|0.3.1
vscode-language-pack-zh-hans|MS-|1.25.3
python|ms-|2018.6.0
csharp|ms-|1.15.2
material-icon-theme|PKi|3.5.1
unity-debug|Uni|1.3.0

(1 theme extensions excluded)

</details>

**Comment by tinysnake** [comment]
Oh, if I create a hard link of a single file like `mklink /h b.txt a.txt`, and this bug won't happen. just FYI.

**Comment by tinysnake** [comment]
According to my colleague's words, vscode in Mac OSX has the same problem.

**Comment by bpasero** [comment]
The duplicate is: https://github.com/Microsoft/vscode/issues/18837
