### ISSUE TITLE
Opening multiple files at once should add all of them to the MRU list

### ISSUE THREAD

**Issue by sudhirdhumal289** [microsoft/vscode#54644]
Issue Type: <b>Bug</b>

I had 5 files open in VS Code then clicked on last tab and opened 20 more files (selected 20 files and opened them at once). When I tried to close them VS Code always falling back (opening) the tab of 4 th files. I thought it is opening the tab previous to the current file so I swithched to last tab pressed ctrl+w and it again opened the 4th tab I want to keep pressing ctrl+w to close all 20 files at once, which is difficult in this case.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:40:20.190Z)
OS version: Linux x64 4.15.0-23-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 3263)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.55GB (10.50GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|2.16.0
flutter|Dar|2.16.0
vscode-markdownlint|Dav|0.18.0
vscode-eslint|dba|1.4.12
githistory|don|0.4.2
gitlens|eam|8.5.1
tslint|eg2|1.0.34
beautify|Hoo|1.3.2
cpptools|ms-|0.17.6
debugger-for-chrome|msj|4.8.0
java|red|0.28.0
vscode-java-debug|vsc|0.10.0

</details>

**Comment by bpasero** [comment]
@sudhirdhumal289 we maintain a most-recently-used order in the tabs and opening 20 files at once will put the last of those 20 on that stack. If you close one file, it will jump to the one you had opened before. 

I can see how this behavior can be undesired in your case, but I would treat that as a feature request.
