### ISSUE TITLE
colorize const not right

### ISSUE THREAD

**Issue by natqe** [Microsoft/vscode#54653]
- VSCode Version: latest
- windows Version: 10

[screenshot to demonstration the issue](https://i.imgur.com/C6cLSan.png)

**Comment by mjbvz** [comment]
Please share the text of the code along with screenshots

**Comment by natqe** [comment]
@mjbvz this is the text:
`            const
              dialog = this.$mdDialog.prompt().title('Enter a name').cancel('Cancel').ok('Ok'),
              name: string = await this.$mdDialog.show(dialog)`

**Comment by mjbvz** [comment]
Fixed upstream by https://github.com/Microsoft/TypeScript-TmLanguage/issues/638
