### ISSUE TITLE
I can't use git in my vscode

### ISSUE THREAD

**Issue by wandouni** [Microsoft/vscode#54654]
- VSCode Version: v1.25.1
- OS Version: win10

My version control in VS Code doesn't have the button of init and more, and the settings doesn't contain the option——git.
You can see the picture below of my vscode to know what happend.
thanks for your help~

[image](https://wx2.sinaimg.cn/mw690/77a03329gy1ftfdnlqelpj209y06nmwy.jpg)
[image](https://wx2.sinaimg.cn/mw690/77a03329gy1ftfdnlseocj20lb09bdfw.jpg)

**Comment by joaomoreno** [comment]
Do you have Git installed? https://git-scm.com/

**Comment by wandouni** [comment]
sure, i ve installed git
I can use git to push code to remote in my webstrom

**Comment by wandouni** [comment]
The path my of git is:
`D:\installDir\Git`

And the path to git executable in my webstrom is:
`D:\installDir\Git\cmd\git.exe`

And my %PATH% has added:
`D:\installDir\Git\cmd`

All above can be seen in the piictures below, I hope it can help.
[git directory](https://wx3.sinaimg.cn/mw690/77a03329gy1ftg24e3ixwj20m50abt9b.jpg)
[webstrom git path](https://wx3.sinaimg.cn/mw690/77a03329gy1ftg24dyoeej20b10220sj.jpg)
[%PATH%](https://wx3.sinaimg.cn/mw690/77a03329gy1ftg24e1pshj20eq0fpaal.jpg)

@joaomoreno @myfairsyer

**Comment by wandouni** [comment]
I put all my plugins available disabled ,and then reenabled them, the problem was fixed.
I think maybe some plugin has confused the function of the git-scm in my vscode.
I truly show my appreation for your help.
@joaomoreno @myfairsyer
