### ISSUE TITLE
Weird empty bars occupying space in the editor

### ISSUE THREAD

**Issue by Zerokk** [Microsoft/vscode#54658]
- VSCode Version: 1.25.1
- OS Version: W10

Hi there, quick question for the developers and users: do you have an empty, unremovable bar, like this?:

https://i.imgur.com/bD1uXsw.png

It happens me since the latest patch, and I can't remove it no matter what I do. It's quite annoying because it gives me less space for seeing the code. Do you know any way of removing it?

**Comment by alexandrudima** [comment]
It might be the centred layout ...

**Comment by isidorn** [comment]
`F1 > toggle centered editor layout`
