### ISSUE TITLE
Snippets/alias for integrated terminal

### ISSUE THREAD

**Issue by pikilon** [Microsoft/vscode#54652]
Allow create Snippets for the terminal so you can define them in VSC and trigger them in any bash.

The integrated terminal is awesome in VSC for creating the `.bash__alias` cross shells could be a PITA.

As a good side effect I also use `Sync` extension and this will be stored automatically on the cloud, so all my devices with VSC will share this aliases

**Comment by Tyriar** [comment]
Something like this will be possible after the `activeTerminal` API is stabilized by using that and `Terminal.sendText` to send different chunks of text to the terminal (perhaps using the quick pick API to present the various snippets?). It's possible that we could add something like this in the future but experimentation within extensions in the meantime would be best.
