### ISSUE TITLE
ES6 generator syntax highlighting (generator name and `yield` keyword)

### ISSUE THREAD

**Issue by anyong** [Microsoft/vscode#5465]
- VSCode Version: 1.0.0-insider
- OS Version: Win 10

Steps to Reproduce:

1. Write a generator function
2. The name and yield keywords don't get highlighted

VS Code:

![image](https://cloud.githubusercontent.com/assets/6260469/14625630/42e25bca-0617-11e6-82f2-0ab08f8aa2b5.png)

Expected result (from Sublime Text):

![image](https://cloud.githubusercontent.com/assets/6260469/14625642/6aa68744-0617-11e6-94a3-17cefe9806a6.png)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#146
