### ISSUE TITLE
Request: only save file if it has changed

### ISSUE THREAD

**Issue by lonix1** [Microsoft/vscode#54651]
vscode 1.25.1, ubuntu 18.04

If I save a file, even if it hasn't changed, then vscode actually saves the file. Since I'm using some node watching modules to check for changes, it triggers a reload/rebuild and so on, which is undesirable.

Surely vscode should not save in these cases:
- file hasn't changed
- undo buffer is empty (i.e. file was changed but the change was reverted, so file is in fact unchanged)

**Comment by bpasero** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/41812
