### ISSUE TITLE
Suggest send telemetry as you type

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#54667]
* set log level to 'trace' so that you can see telemetry events
* open a typescript file, globally trigger suggestions, type 'console'
* 🐛 per keystroke an event is send `telemetry/suggestWidget`

I don't think that much telemetry is useful and it surely has an impact on performance (since filtering/ranking suggestions is already expensive) and my plan is to remove it unless @ramya-rao-a has objections or usages of this event

**Comment by ramya-rao-a** [comment]
Is your plan to remove the event altogether or to tweak the code to only log the event for the first time the suggest widget opens and not for subsequent filtering?
