### ISSUE TITLE
Cannot debug because the dll cannot be found

### ISSUE THREAD

**Issue by rhires** [Microsoft/vscode#54668]
Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:43:53.668Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

Steps to Reproduce:

1. dotnet new console
2. run in debug mode, get error

Narrative: the issue is that when I run "dotnet new console" it's creating an extra layer of hierarchy that the debug part is not aware of somehow. The screen shot below should illustrate this issue: the paths to the dll are different. 

![image](https://user-images.githubusercontent.com/12577765/42950565-5490f6a8-8b42-11e8-877f-6dab37295e56.png)

**Comment by weinand** [comment]
Please file this issue against the C#/.net extension
