### ISSUE TITLE
Python flask crashes on startup

### ISSUE THREAD

**Issue by stevej2608** [Microsoft/vscode#54669]
Python Flask crashes on startup when launched with a VSCODE python launch 
configuration that contains "console": "none", eg :

...
            "debugOptions": [
                "RedirectOutput",
            ],

            "console": "none"
...

The offending line is in Flash app.py/run(). Line 938 in flask-v1.02:

        cli.show_server_banner(self.env, self.debug, self.name, False)

Commenting out this line fixes the problem and the Flash server runs ok.

cli.show_server_banner() calls:

     click._winconsole.py\write() line 512

This method throws the following exception

    OSError: Windows error 1

Looks like something to do with buffered writes to stdout not being happy with a null terminal.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.84GB (8.73GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.12
jupyter|don|1.1.4
tslint|eg2|1.0.34
php-debug|fel|1.12.3
nbpreviewer|jit|1.0.0
code-beautifier|mic|2.1.0
perl-debug|mor|0.4.1
python|ms-|2018.6.0
debugger-for-chrome|msj|4.8.0
LiveServer|rit|5.1.1
code-spell-checker|str|1.6.10
bootstrap4-vscode|the|4.3.0
twig|wha|1.0.2
markdown-all-in-one|yzh|1.5.1

(1 theme extensions excluded)

</details>

**Comment by weinand** [comment]
Please file against Python extension
