### ISSUE TITLE
[Request] Add user setting property to allow users to customize unused variables text colors and highlight colors

### ISSUE THREAD

**Issue by tommai78101** [Microsoft/vscode#54665]
I have having a really troubling time trying to change the current Default Dark+ VS Code theme for unused variables.

Currently, there is no method that exposes the functionality to allow users to set their own colors for unused variables in the User Settings.

I would like to request a feature to expose this in User Settings, so it is easier to change unused variables text colors. 

If this isn't viable, how do I change unused variables text colors (and highlight colors)?

**Comment by mjbvz** [comment]
This is discussed in #53519. We removed the old solid color for unused behavior as it made the editor look broken. In JS/TS you can configure unused to be treated as an error which adds squiggles, or you can use the `border` setting for unused variables

**Comment by tommai78101** [comment]
@mjbvz So how do I increase the intensity of the fading you mentioned in #53519 with the official API?
