### ISSUE TITLE
Replace doesn't work well with navigation arrows

### ISSUE THREAD

**Issue by lemano** [Microsoft/vscode#54660]
Hi.

I got a weird behaviour, on find&replace. The reproducible steps are:
1. Make a simple replace(Ctrl-H)
2. You regret it, so Undo the edition made by replace
3. Now go to the replace input, and up arrow until some other string
4. Code replaces by the last replaced string, not by the chosen one.

Details of my installation:
Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:40:20.190Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

Thanks

**Comment by pekkast** [comment]
Jep, as reported above
![vscode replace bug](https://user-images.githubusercontent.com/1282829/43943677-0cb94fa2-9c85-11e8-9dd5-5dd189a4e96f.gif)

**Comment by rebornix** [comment]
Thanks for reporting, this is terrible. Will fix it this month.
