### ISSUE TITLE
[TS] Cannot find module

### ISSUE THREAD

**Issue by NavyAdmiral** [Microsoft/vscode#54663]
- VSCode Version: 1.26 Insiders
- OS Version: Win10
-----------------------
Steps to Reproduce:

1.Create a dir with this struct:

- src/components
- src/containers

2.Change dir to src/containers and import component like this:
`import SomeComponent from 'components/SomeComponent'`

-----------------------

Project builds successfully but vscode says module was not found.

`'./components/SomeComponent'` does work, but shouldn't the former work too?

-----------------------
Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Take a look at this answer I just posted: https://stackoverflow.com/a/51427531/306149

**Comment by NavyAdmiral** [comment]
@mjbvz if the struct is:
```
./gui/src/utils/something.js
otherfolders/
```
and you use
```
{
    "compilerOptions": {
        "target": "ES6",
        "baseUrl": "./gui/src"
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```
vscode will suggest the utils/ folder but it won't suggest something.js
