### ISSUE TITLE
Themes colors do not work in first accented letters

### ISSUE THREAD

**Issue by rodrigojcmello** [Microsoft/vscode#54666]
- VSCode Version: 1.25.1
- OS Version: Mac
- Theme: One Dark Pro 2.15.1 (The problem happens on any theme)

Steps to Reproduce:

1. Create a variable that begins with an accent

<img width="271" alt="captura de tela 2018-07-19 as 11 18 35" src="https://user-images.githubusercontent.com/5174526/42948930-f49a7206-8b46-11e8-929e-827de81ebde9.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
JavaScript?

**Comment by rodrigojcmello** [comment]
Yes, javascript.

I'm sorry, the bug is the extension "Sublime Babel"
