### ISSUE TITLE
Terminal does not clear screen after detaching from `screen`

### ISSUE THREAD

**Issue by rjbruin** [microsoft/vscode#54664]
Issue Type: <b>Bug</b>

1. Open integrated terminal and switch it to the right hand side of the window
2. Install package `screen`
3. Enter a couple of commands to fill the terminal buffer
4. `screen` to open a new screen
5. Press Ctrl+A then D to detach from the screen. The previous commands in the terminal buffer are now displayed, though the terminal "cursor" is at the top of the terminal.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:40:20.190Z)
OS version: Linux x64 4.4.0-130-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3703)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|7.51GB (0.65GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-clock|Com|0.0.1
latex-workshop|Jam|5.6.1
rainbow-csv|mec|0.4.2
python|ms-|2018.6.0
material-icon-theme|PKi|3.5.1
vscode-icons|rob|7.24.0

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Expected:

![image](https://user-images.githubusercontent.com/2193314/43144496-22540346-8f12-11e8-8d7e-a9ce2202ad1b.png)

Actual:

![image](https://user-images.githubusercontent.com/2193314/43144516-2d06393a-8f12-11e8-8549-766ede699053.png)

**Comment by sleighsoft** [comment]
I observe a similar issue with `tmux`.
When detaching some cursor highlights are not cleared.

See the vertical yellow dots.
![grafik](https://user-images.githubusercontent.com/9438971/59667337-d9766080-91b6-11e9-9ea8-e40ba50a55d9.png)

**Comment by Tyriar** [comment]
Seems to be fixed now
