### ISSUE TITLE
Opening new files open in Preview pane

### ISSUE THREAD

**Issue by paulelong** [Microsoft/vscode#54675]
Issue Type: <b>Bug</b>

Open .MD file
Open preview window
Single click another MD file
File opens in the preview pane

I expect it to open the pane holding the .MD file.  That way I can see the preview for any MD file I click on.  But the way it works now I have open another preview pane, which means I have 3.  Or I have to drag the MD file to the pane where the first MD file is.

In the end I want my preview to take place in the same pane, but it doesn't work that way by default today.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (1.84GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
gc-excelviewer|Gra|2.1.24
r|Iku|0.6.0
r-lsp|Iku|0.0.7
cpptools|ms-|0.17.6
csharp|ms-|1.15.2
mono-debug|ms-|0.15.8
PowerShell|ms-|1.8.1
vscode-arduino|vsc|0.2.18

</details>

**Comment by mjbvz** [comment]
See the markdown preview documentation: https://code.visualstudio.com/Docs/languages/markdown#_dynamic-previews-and-preview-locking

The preview shows the active file by default, but can be locked to a single file
