### ISSUE TITLE
Quick Switch Command is not working

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#54673]
Issue Type: <b>Bug</b>

VS Code version: Code - Insiders 1.26.0-insider (afc3d77e7cfc6534ba05c52f5e1289cbecd58b3d, 2018-07-19T05:12:41.315Z)
OS version: Darwin x64 17.3.0

Quick Switch Command is not working

![kapture 2018-07-19 at 17 55 32](https://user-images.githubusercontent.com/10746682/42954443-fffbca6a-8b7c-11e8-9ca0-7cecbf1faa0f.gif)

**Comment by bpasero** [comment]
Yes, this one can only be triggered via keybinding.
