### ISSUE TITLE
Fifteen thousand vscode-tscancellation* temp files created

### ISSUE THREAD

**Issue by flotwig** [Microsoft/vscode#54671]
Issue Type: <b>Bug</b>

This is a bit of a weird bug. I noticed that in my Windows %Temp% directory, I have 15,612 separate empty files named `vscode-tscancellation-([0-9a-f]+).sock([0-9]{2})`:

```
$ ls -al ~/AppData/Local/Temp/vscode-tscancellation-*.sock* | wc -l
15612
```

![A small selection.](https://user-images.githubusercontent.com/1151760/42953625-d903c3c4-8b48-11e8-81a7-470d61bde479.png)

They date back to when I installed VS Code on my computer, and appear to be created during the hours I actively use VS Code. Sometimes over 20 will be created in the course of a minute. I write Python, JavaScript, JSX, and other things in VS Code.

I'm assuming that some process is failing to cleanup old temp files. It looks like the `sock([0-9]+)` values are sequential, so something is probably creating them, incorrectly thinking the creation failed, trying to recreate it, finding the file already exists, then incrementing the end number so it can be created - and repeating infinitely.

Anyone have an idea what could be causing this?

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (0.55GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.6.0

</details>

**Comment by flotwig** [comment]
Maybe related to this?

https://github.com/Microsoft/vscode/blob/533c6deb7901fba48df4db8c7adfbd42a6d2fe7a/extensions/typescript-language-features/src/typescriptServiceClient.ts#L977

**Comment by flotwig** [comment]
Looks like it comes from here:

https://github.com/Microsoft/vscode/blob/533c6deb7901fba48df4db8c7adfbd42a6d2fe7a/extensions/typescript-language-features/src/typescriptServiceClient.ts#L798

The `seq` number just keeps incrementing and so new files are touched over and over again at this LOC.

Not sure what this `tscancellation` file does, I'm assuming some other process checks if it exists and if so terminates?

**Comment by mjbvz** [comment]
This is by-design. It's just a empty file we use to signal out of process the typescript server that a request as been canceled

533c6deb7901fba48df4db8c7adfbd42a6d2fe7a moved them to their own directory

**Comment by flotwig** [comment]
That helps somewhat, but won't there still be thousands and thousands of orphaned files? I read #53423, it sounds like the assumption is that the OS will clean up these files, but Windows so far has not done that.

**Comment by JacksonKearl** [comment]
@mjbvz It looks like Windows doesn't clean out this temp directory on restart. 
`ls -al ~/AppData/Local/Temp/vscode-* | wc -l` gave me 1,600 files before and after restart. However the files only go back a week. It might be a time based thing?
