### ISSUE TITLE
Synchronizing Extensions across computers

### ISSUE THREAD

**Issue by aydeisen** [Microsoft/vscode#54677]
Is it possible to synchronize extensions across computers, even if it means relocating the extensions directory to OneDrive?

If not, is there a way to allow extensions to be synchronized across instances?

**Comment by superheri** [comment]
Why not the global user settings too

**Comment by sandy081** [comment]
There is not such support but there is a sync extension marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync that does it.
