### ISSUE TITLE
Resize find widget

### ISSUE THREAD

**Issue by chwentao** [Microsoft/vscode#5467]
- VSCode Version:1.0.0
- OS Version:win7

as the title said, when find message long,we need change the search form bigger,
but vscode can't as so far.

**Comment by chwentao** [comment]
fox example the picture.
![qq 20160419111710](https://cloud.githubusercontent.com/assets/13378254/14626882/02210f9a-0622-11e6-948d-027168bd9ca4.png)

**Comment by rebornix** [comment]
Let's track this issue in https://github.com/Microsoft/vscode/issues/2657 and work on it in May. Thanks for your input!
