### ISSUE TITLE
command 'o.pickProjectAndStart' not found

### ISSUE THREAD

**Issue by afernandes** [Microsoft/vscode#54684]
Issue Type: <b>Bug</b>

[ERROR]
>OmniSharp: Select Project
command 'o.pickProjectAndStart' not found

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.96GB (1.58GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Users\AndersonN\source\repos\aspnetboilerplate|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
supersharp|cra|0.1.4
netcore-snippets|dog|0.0.17
githistory|don|0.4.2
bowerwatcher|eal|0.0.1
gitlens|eam|8.5.1
php-debug|fel|1.12.3
php-intellisense|fel|2.3.3
auto-rename-tag|for|0.0.15
code-runner|for|0.9.3
dotnet|for|0.0.4
gc-excelviewer|Gra|2.1.24
githd|hui|1.2.0
csharpextensions|jch|1.3.0
docomment|k--|0.1.2
rainbow-csv|mec|0.4.2
vscode-language-pack-pt-BR|MS-|1.25.2
mssql|ms-|1.4.0
csharp|ms-|1.15.2
mono-debug|ms-|0.15.8
PowerShell|ms-|1.8.1
debugger-for-chrome|msj|4.8.0
gulptasks|nic|1.2.0
Csharp-ASPNETCore|rah|1.0.5
classlens|rex|0.7.1
aspnet-helper|sch|0.6.4
asp-net-core-vs-code-extension-pack|tem|1.0.2
msbuild-project-tools|tin|0.2.39
code-lens-roundup|wad|1.0.0

</details>

**Comment by alexandrudima** [comment]
@afernandes This looks like an OmniSharp issue. Can you please create the issue against the OmniSharp extension at https://github.com/OmniSharp/omnisharp-vscode/issues
