### ISSUE TITLE
Cannot read property 'getValue' of null when changing themes

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#54683]
Issue Type: <b>Bug</b>

In the latest Insiders change the theme using the `Preferences: Color Theme` command. For each change, you will see the below error in the console

![image](https://user-images.githubusercontent.com/16890566/42961998-6065d07c-8b45-11e8-9b20-34ef476089c0.png)

VS Code version: Code - Insiders 1.26.0-insider (afc3d77e7cfc6534ba05c52f5e1289cbecd58b3d, 2018-07-19T05:18:41.292Z)
OS version: Windows_NT x64 10.0.17134

**Comment by aeschli** [comment]
@ramya-rao-a I'm not able to reproduce in 26e5a55cd8452477bfb7a472ea9475761600adf0
Date: 2018-07-20T05:18:52.551Z.
Can you get more information from the dev tools as where this is happening? There haven't been any changes in the theme service lately.

**Comment by ramya-rao-a** [comment]
I dont see it the latest Insiders from last night either.
Closing.
