### ISSUE TITLE
Rendering issues when ssh'd to a Windows git bash shell.

### ISSUE THREAD

**Issue by javon27** [Microsoft/vscode#54682]
- VSCode Version: 1.25.1
- OS Version: Windows 10 1803. Build 17134.165

Steps to Reproduce:

1. Set git bash as default shell
2. ssh to remote windows server running git bash as the shell
3. Run a few commands (git pull, cd directory, etc)
4. Input gets displayed one character per line followed by 20 rows. The next character is displayed in the correct column, however. See attached screenshot

Does this issue occur when all extensions are disabled?: Yes

<img width="646" alt="vscode ssh bash bug" src="https://user-images.githubusercontent.com/6467320/42961475-7787f67c-8b54-11e8-818d-7eac6b8f1634.png">

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
