### ISSUE TITLE
simpleWidget editors do not support Ctrl+a

### ISSUE THREAD

**Issue by JacksonKearl** [Microsoft/vscode#54686]
In any `simpleWidget` editor (extensions search box, debug repl, logpoint editor), `Ctrl+a` does not select all text.

**Comment by DieLaughing** [comment]
The Keyboard shortcuts for Linux PDF do NOT list `Ctrl+a` as a shortcut key. In fact, they don't have SELECT ALL listed as a feature you can use a shortcut key with. It's either incompetence or malice, but I haven't discovered which yet.

**Comment by alexandrudima** [comment]
@JacksonKearl If you want to tackle this one, it is as simple as relaxing the precondition here https://github.com/Microsoft/vscode/blob/5b8a81742a562811acd2e0603eced8fafdb8e5d7/src/vs/editor/browser/controller/coreCommands.ts#L1707

to use `EditorContextKeys.textInputFocus`

**Comment by JacksonKearl** [comment]
Closed with #55078
