### ISSUE TITLE
Performance Issue version 1.25.1

### ISSUE THREAD

**Issue by antnativo** [Microsoft/vscode#54685]
- VSC version 1.25.1:
- Mac OS X 10.13.5:

Steps to Reproduce:

1. Opening VSC
2. VSC opens existing project
3. VSC runs "scanning tasks"
4. VSC becomes unresponsive 1 min after opening
5. Mac OS throws unresponsive program warning with options to wait or kill operation

Does this issue occur when all extensions are disabled?: Yes

**Comment by dbaeumer** [comment]
@antnativo what exactly do you mean by 'scanning tasks'. Do you execute 'Tasks > Run Tasks`?

**Comment by dbaeumer** [comment]
VS Code will not eagerly scan for tasks. Only if you do `Tasks > Run Tasks` and all the scanning happens in the extension host. So this shouldn't block the UI in any ways.
