### ISSUE TITLE
git.path is automatically set to wrong path pointing to the executable and not the folder

### ISSUE THREAD

**Issue by herrgutt** [Microsoft/vscode#54681]
Hello,

After I was thinkering with the source control providers settings since they were not working i noticed that the git.path value is wrong.

It should point to the **folder** containing git-cmd.exe and **not** the file itself.
This is occured after fresh install with Git & VSC.

- VSCode Version: 1.25.1
- OS Version: Windows 10 Home

Steps to Reproduce:

1. Install Git
2. Install VS Code
3. See that there is no Source control providers since the git.path value is wrong.

Does this issue occur when all extensions are disabled?: Yes

Soulution:
- Make VSC only point to the folder containing the git-cmd.exe file and not the file itself.

**Comment by joaomoreno** [comment]
No, it should definitely point to the executable. What makes you say that?

**Comment by herrgutt** [comment]
Hi, thanks for getting back to me.

After changing my git.path to the folder for Git it works correctly for me. When i changed it back to the exec again it would not work.

**Comment by joaomoreno** [comment]
Interesting. Btw, why is it called `git-cmd.exe` in your system? How did you install Git?

**Comment by herrgutt** [comment]
I installed Git from https://git-scm.com/download/win, newest version at the time. As far as I know, git-cmd.exe is the default name from the installer.

**Comment by joaomoreno** [comment]
What Code expects to find is `git.exe`, it must be somewhere in the installation folder.
