### ISSUE TITLE
Problems window is reloading every second.

### ISSUE THREAD

**Issue by chaluvadis** [Microsoft/vscode#54698]
I noticed an issue in Problems window. 

![screen](https://user-images.githubusercontent.com/738511/42977533-4d72a8d0-8b8d-11e8-8f4d-62efff3ce468.gif)

**Comment by sandy081** [comment]
@chaluvadis Can you please check if an extension providing problems is causing this.. it might be creating and removing the problems which is leading to this? 

Disable the extension and try.

**Comment by chaluvadis** [comment]
Test Explorer extension is causing that problem. I removed all my extensions and installed one at a time  . Finally I figured out the Test Explorer extension window causing that problem. Its good now. thanks you for your help.
