### ISSUE TITLE
Text is not selectable in the new Settings Editor

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#54694]
Issue Type: <b>Bug</b>

Text is not selectable in the new Settings Editor

VS Code version: Code - Insiders 1.26.0-insider (afc3d77e7cfc6534ba05c52f5e1289cbecd58b3d, 2018-07-19T05:18:41.292Z)
OS version: Windows_NT x64 10.0.17134

**Comment by roblourens** [comment]
Do you need to select names/descriptions? What if there was a "copy" context menu option that copied the JSON form of the setting? e.g. copy or cmd+c with the row selected would copy something like `"editor.fontSize": 10`?

**Comment by roblourens** [comment]
Ping @ramya-rao-a , I can't decide whether this is covered by https://github.com/Microsoft/vscode/issues/54140 (context menu actions) or whether the text itself should be selectable.

**Comment by ramya-rao-a** [comment]
No, I meant to select the setting name. #54140 covers most of what I want, I'll close this.
