### ISSUE TITLE
VSCode continues to display TypeScript errors when all TypeScript settings are disabled.

### ISSUE THREAD

**Issue by politician** [Microsoft/vscode#54691]
We do not use TypeScript in several of our projects, so we have attempted to disable TypeScript validation in our JavaScript files.  However, VSCode displays TypeScript-related messages despite the settings instructing it not to do so.

Apparently this is a regression in the latest build because there was another long bug closed by @sandy081 about a similar issue back in March 2018 where the team appeared to have communicated that *the ability to disable TypeScript* was a feature that VScode supported.

- VSCode Version: 1.25.1
- OS Version: macOS 10.13.6

Steps to Reproduce:

1. Launch with `code --disable-extensions`
2. Open User Settings and configure it as per below.
2. Create a new file
3. Type `import test from "path"`
4. Change the Language Mode to "JavaScript"
5. Hover over the word `test` and observe the message `[ts] 'test' is declared but its value is never read' appears inside the tooltip.
6. The expected behavior is that VSCode does not attempt to communicate TypeScript-related error messages when TypeScript validation is disabled.

### User Settings for Step 2

```
    # Surely one of these will turn off all [ts] messages in tooltips!
    "typescript.validate.enable": false,
    "typescript.autoImportSuggestions.enabled": false,
    "typescript.check.npmIsInstalled": false,
    "typescript.format.enable": false,
    "typescript.format.insertSpaceAfterCommaDelimiter": false,
    "typescript.format.insertSpaceAfterFunctionKeywordForAnonymousFunctions": false,
    "typescript.format.insertSpaceAfterKeywordsInControlFlowStatements": false,
    "typescript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": false,
    "typescript.format.insertSpaceAfterSemicolonInForStatements": false,
    "typescript.format.insertSpaceBeforeAndAfterBinaryOperators": false,
    "typescript.quickSuggestionsForPaths": false,
    "typescript.reportStyleChecksAsWarnings": false,
    "typescript.showUnused": false,
    "typescript.suggestionActions.enabled": false,
    "typescript.tsc.autoDetect": "off",
    "typescript.updateImportsOnFileMove.enabled": "never",
    "tslint.enable": false
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Set the javascript version of this setting instead:

```js
    "javascript.showUnused": false,
```

If you are in js files, use the `javascript` versions of those settings if they exist

**Comment by politician** [comment]
No, that's not the fix.

**Comment by mjbvz** [comment]
Yes. The TypeScript extension powers our javascript intellisense which is why you see `[TS]` in your js file. That only indicates what extension is providing that error

**Comment by politician** [comment]
How does VSCode disambiguate TypeScript validations from JavaScript validations?

**Comment by mjbvz** [comment]
That's where the two versions of the settings come in: the `typescript.*` setting apply to typescript files specifically, while the `javascript.*` settings apply to javascript files. Behind the scenes both are powered by the typescript extension

**Comment by politician** [comment]
Thank you, that's an explanation that I can bring back to the team and not have folks scratching their heads.

**Comment by ajelcocks** [comment]
I have spent several days trying to stop a tooltip prefixed with [ts] and now I find it is not a TypeScript error? I have been pulling my hair out scouring the web, setting every possible setting to false, rebuilding projects and workspaces.

Two days of frustration and wasted effort...because the IDE tells me a JavaScript message using a TypeScript prefix/indicator.

That is just awesome!  Thank you so much.

Perhaps you could look into maybe making it a little less confusing and putting a different [prefix] there, like oh I don't know ..[js] or something similar?
