### ISSUE TITLE
After opening the software for a period of time, the code prompt disappeared

### ISSUE THREAD

**Issue by jesseyang0626** [Microsoft/vscode#54699]
VSCode Version:1.25.1
OS Version:Windows 10
Steps to Reproduce:

After opening the software for a period of time, the code prompt disappeared

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
@jesseyang0626 I don't understand what you mean by "code prompt". Can you please show a screenshot or some steps to explain what you mean.

**Comment by jesseyang0626** [comment]
thank u 
It seems that the translation software didn't make my meaning clear,what i mean is code auto complete.Strangely enough, it was normal again
