### ISSUE TITLE
Promise.reject() triggers uncaught exception break, even when caught

### ISSUE THREAD

**Issue by andrewwalters** [Microsoft/vscode#54693]
Issue Type: <b>Bug</b>

Using built-in Node.js debugger and VS code version 1.25.1, calling `Promise.reject()` from inside a `setTimeout()` handler triggers an uncaught exception breakpoint, even if the rejected promise is caught and handled.

To repro:

- Make sure 'Uncaught Exceptions' is checked.

- Run the following code in Node.js debugger:

```
setTimeout(() => {
  return Promise.reject().catch(() => console.log("caught!"));
}, 100);
```

Expected: Outputs `caught!`

Actual: Debugger stops with "Exception has occurred: undefined". Call stack shows "Paused on uncaught exception". Can continue from breakpoint to get expected output.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|10, 6, 3|
|Memory (System)|16.00GB (2.16GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_3134205|
|Screen Reader|no|
|VM|40%|

</details>

**Comment by andrewwalters** [comment]
The following code also triggers the uncaught exception breakpoint:

```
setTimeout(() => {
  return new Promise((resolve, reject) => reject()).catch(
    () => console.log('caught! 2')
  );
}, 100);
```

And the following does not:

```
setTimeout(() => {
  return new Promise((resolve, reject) => setImmediate(() => reject())).catch(
    () => console.log('caught! 3')
  );
}, 100);
```

**Comment by weinand** [comment]
Yes, the `setImmediate()` is basically the explanation for this behaviour.
For more details see #1746.
