### ISSUE TITLE
Debugger opens incorrect file

### ISSUE THREAD

**Issue by zavr-1** [Microsoft/vscode#54697]
- VSCode Version: 1.25.1
- OS Version: 10.13.1

Steps to Reproduce:

1. Clone the repository.

```sh
git clone https://github.com/artdecocode/debugger-report.git
code debugger-report
```

2. Open `test/spec/index.js` and set a breakpoint and line 15.

3. Hit `F5` and wait for the debugger to start. It will pause in the `src/index.js` file at line 15 rather than in `test/spec/index.js`.

When the test file is renamed to `index1.js` instead of `index.js` then it's fine. Therefore, VS Code must be picking up the wrong file by its basename somehow, despite the fact that source maps are `inline`. 

![replay of the bug](https://github.com/artdecocode/debugger-report/raw/master/appshot-debugger1.gif)

## read-only sourcemaps

ALSO, what's up with opening source maps in the read-only? It didn't used to do that, is that by design? I loose the visibility of breakpoints because they all have to be set in the source files, but are not displaying the read-only view, and I have to keep switching between the two. I guess it's better in terms of control when changes are made to a source but the debugger source has not changed just yet, but was it that big of an issue? 

Does this issue occur when all extensions are disabled?: Yes

**Comment by chriscordova** [comment]
@zavr-1 The 'read-only source maps' issue has been driving me crazy with this new version, I'm hoping that it can be addressed soon. Thanks for bringing this up. Have downloaded VSCode 1.24 for the time being.

**Comment by roblourens** [comment]
This looks like #54026, and your project works for me in Insiders. Please try it there.
