### ISSUE TITLE
Unable to open existing scripts having filename like "1543/test.xml"

### ISSUE THREAD

**Issue by ss-is-master-chief** [Microsoft/vscode#54705]
- VSCode Version: 1.25.1
- OS Version: macOS High Sierra 10.13.6

My project has a few `XML` scripts which have filenames such as `1543/test.xml`, `1541/test.xml`. They show up on the Explorer as just `test.xml`. While trying to open them, VSCode notifies me with the following message `Unable to open 'test.xml': File not found`.

Upon creating a new script with a similar name, VSCode identifies it correctly by putting them under a directory. For example, `1543/test.xml` is listed under directory `1543`.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Having a `/` in a file name is invalid on mac. Thus it can not be opened.
Closing as desgined behavior

**Comment by ss-is-master-chief** [comment]
@isidorn Thank you
