### ISSUE TITLE
Toggle hidden file include in "files.exclude" setting

### ISSUE THREAD

**Issue by tolawho** [Microsoft/vscode#54704]

**Comment by roblourens** [comment]
Please include more details

**Comment by tolawho** [comment]
Sorry for my english.

When I use vscode, some folder I want hide it, and I added it to "files.exclude" setting. Example ".vscode" folder. But some extension also add the setting file into ".vscode" folder. 
Now I want to change the setting of the extension, I must open the user setting to comment the ".vscode" folder in "files.exclude" to show it.
I request this feature hope vscode provide one method to show/hide all the folder in "files.exclude" quickly(maybe shortcut).
![image](https://user-images.githubusercontent.com/12527881/42987799-a39b4ad6-8c24-11e8-98f8-610fb83b8ad5.png)
