### ISSUE TITLE
Split blank window with hot key when only one file is opened.

### ISSUE THREAD

**Issue by Alnlll** [Microsoft/vscode#54700]
When only one file is opened, I can't split window with hot-key "Alt+Shift+2". So if I want to do that,  opening another file from "Workspace" with mouse then do splitting is the only choice by my opinion. Please add a feature to allow to split a new blank window under these circumstances。

**Comment by bpasero** [comment]
"Split Editor" should work. Make sure your keybindings are configured properly.

Does it work if you click this:
![image](https://user-images.githubusercontent.com/900690/43712220-d0db55e6-9975-11e8-8319-adc1f98c35a0.png)
?

**Comment by Alnlll** [comment]
I used the hotkey which move files between editor splited to split editor, so It's a misunderstanding.
