### ISSUE TITLE
插件配置文件到每个项目里面都要配置,有点麻烦

### ISSUE THREAD

**Issue by qq471754603** [Microsoft/vscode#54703]
Issue Type: <b>Bug</b>

插件配置文件到每个项目里面都要配置,有点麻烦

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 15.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|8.00GB (0.24GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
project-manager|ale|8.0.0
color-info|bie|0.5.0
vscode-intelephense-client|bme|0.8.8
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.59
vscode-eslint|dba|1.4.12
php-debug|fel|1.12.3
php-intellisense|fel|2.3.3
terminal|for|0.0.10
vscode-mysql|for|0.3.0
beautify|Hoo|1.3.2
docthis|joe|0.7.1
sftp|lix|1.2.5
vscode-language-pack-zh-hans|MS-|1.25.3
sublime-keybindings|ms-|4.0.0
open-html-in-browser|pea|0.0.3
vscode-css-peek|pra|2.1.0
vscode-format|rya|0.0.6
code-settings-sync|Sha|3.0.0
xmake-vscode|tbo|1.1.2
bootstrap4-vscode|the|4.3.0
quokka-vscode|Wal|1.0.133
bootstrap-v4-snippets|Zac|0.1.2
html-css-class-completion|Zig|1.17.1

</details>

**Comment by alexandrudima** [comment]
Sorry, please create issues in English.
