### ISSUE TITLE
Make debugger reveal existing tab for source instead of opening a new one in the active pane

### ISSUE THREAD

**Issue by l0k1verloren** [Microsoft/vscode#54715]
Sorry if this is a duplicate, but I couldn't find any issue resembling this.

When the debugger jumps to a new source file, it always opens a new instance of the file in the active (last clicked in) editor pane.

What I would much prefer it did is that if the source is already open in *another* pane, to switch to this pane instead. Especially now there is proper source editor panes, on a 4K display with 4 or more panes as I debug the number of duplicated open source files starts to get ridiculous.

**Comment by l0k1verloren** [comment]
I just poked at it a little more and actually this feature would be also useful to extend to when you click in the explorer file list on a source that is already open. This alone might be all that is required to get this feature.

**Comment by weinand** [comment]
VS Code only opens a new file, if (and only if) it cannot find (or map) a given source location coming from the debugger to an existing file in the workspace. 

If this happens, this is typically an indication of a configuration error: the debugger returns source paths in a different way than VS Code sees the file, or in case of transpilation, the debugger sees a generated file that is not part of the VS Code workspace and no source map exists that would map the generated file back to its source.

So if you have this problem, then please provide the details of your setup. In most cases we are able to help you fixing the configuration problem.

@isidorn am I missing something here?

**Comment by l0k1verloren** [comment]
I'm uncertain exactly what you mean. To clarify what I'm talking about a bit more, whatever pane is currently selected, if the file is not already opened in it, it opens it again, regardless of whether other editor panes already have the file open. They should be identical by their file path. But I think the issue is that the debugger is not aware of any other editor pane other than the currently active one.

I haven't made any special configurations for the debugger, aside from enabling verbose output (ie, printing output to stdout/stderr) it's completely standard, as automated. You wouldn't even know that it does this unless you open multiple panes and then start running a debugger (in this case Go's Delve) and have files already open that the execution path hits. If you have only one pane, yes, it opens the existing opened file. It just pays no attention to the fact the file might already be open in the unfocused panes.

**Comment by weinand** [comment]
Please clarify what you mean by "pane"?
This is not a term we use in the context of VS Code.

**Comment by l0k1verloren** [comment]
'pane' is a canvas that is locked within fixed or proportionally adjusted delimiters splitting two or more parts of a window. Like a literal window pane... Not that many people are making physical windows in this form anymore (generally one frame one pane now), as glass is a lot cheaper and flatter and available in larger sections than it used to be.

I mean, as in, the frame that bounds the tabs and the topmost tab visible, as in the editor that has the active cursor. Used to be only possible to have at most 3 side by side but they have added a splitting function to the tab menu now which is nice but without the debugger knowing to activate and bring to the top of the stack of tabs an existing file, all these panes just end up having shorter sections for the tabs and more things in them and require constant manual closing to keep it sane.

Possibly in some circumstances other than debugging with Delve the debugger *does* actually activate and elevate the editor view that contains the current position of execution, but it does not with Delve and Golang, and I sorta doubt that it does with others. Maybe I should record a screencap.

**Comment by weinand** [comment]
Thanks for your explanation of the term "pane". With that I'm now pretty sure that you are experiencing either a problem with the Go debugger or a configuration problem.

I'll try again to explain in simple sentences the intent of VS Code:
- using debugging in VS Code should never open the same file in two tabs!
- if it does, then this is not a bug in VS Code but it is a problem with the debugger (which VS Code neither owns nor controls): the debugger returns a file path to VS Code that VS Code cannot find in any of it tabs and therefore opens it again.

You said "They should be identical by their file path". That's the theory. And if the theory would be always true, then VS Code would never open a file more than once.

But in practice the debugger sometimes returns a path that is not identical (even if you know that it should reference the same file).

I suggest to file this issue against the Go debugger (Delve).

**Comment by l0k1verloren** [comment]
Ok, just did a little more testing and what is happening is that it *does* switch to another, inactive editor view *if* the topmost (visible) tab is the one it's looking for. Otherwise it opens the file in the same view, adding a new tab.

The file explorer correctly identifies already open files when they are clicked on. But as you point out, of course the paths will be consistent there.

I don't see how differently prefixed paths could be appearing within a Go workspace, unless the editor component is not expanding variables and abbreviations (eg ~) into their full absolute pathname *before* comparing them during the walk through the editor's open file tree.

Since I have not changed any configurations relating to the debugger, from default and automatic, I am quite convinced that the issue is the code that searches currently open windows is not expanding the pathspec being given by the debugger, before making comparisons. You even basically say as much 'it only opens a new view of the same file if the path is different'. How can it be the *same file* if the path is not the same? Obviously path expansion is not being done somewhere. I think you are jumping to conclusions that it is the debugger and not the editor, especially because Go is pretty fussy and rigid about paths and the only way I could see such a thing happening is if I was using relative paths: eg:

`/home/loki/Downloads/../Pictures/image.jpg' is exactly the same real path as `/home/loki/Downloads/Pictures/image.jpg' and would be superficially identified as being a different path. However, the path specification should be walked like a tree. `The Downloads/..` would be deleted if the path was being constructed properly before comparison.

**Comment by l0k1verloren** [comment]
I don't know why this issue is closed. I am sure you can replicate it easily by loading a golang repository and running the debugger. Note that it's not just the debugger that is opening unnecessary new views, it is also the control-click in the terminal. Furthermore, myself and my colleague have been experiencing odd problems with updated edits disappearing randomly while tabs are inactive.

**Comment by weinand** [comment]
I've closed this issue because the issue you are seeing cannot be solved by VS Code but must be solved by the debug extension you are using.

VS Code never opens a file in a new tab if that file is already open and has an identical URL.
But if the debugger sends a different URL (for the supposedly same file), VS Code cannot know that this file is already open and it will open the file in another tab.

So the fix is to make sure that the debugger sends URLs that correspond to the URLs VS Code uses for files in a workspace.

**Comment by weinand** [comment]
Please file new issues for the problem with "control-click in the terminal" and "edits disappearing randomly while tabs are inactive." Do not assume that after mentioning those issues here will automatically start an investigation on our side.

**Comment by l0k1verloren** [comment]
I haven't seen the edits disappearing thing happen many times so I will report it if I can get more details.

The thing is, quite clearly both the terminal and the debugger plugin are behaving the same. And not only that, so does the explorer sidepanel. Here is a screen record of what I am talking about. I don't think I really need to also show the terminal control click or the debugger URL jump if the error is in the editor modules and not caused by malformed URLs, as this will amply demonstrate:

https://drive.google.com/open?id=1vaGywo8PXoEBR8L9VSsM9QEfe18bj3Nt

I suspect this is simply a problem that not many people encounter because as you can see my display is 3840x2160. But you don't need to see it in full resolution to see that the very same file is being loaded in separate editor panels.
