### ISSUE TITLE
Have separate colors for active and inactive tab hover

### ISSUE THREAD

**Issue by lllopo** [microsoft/vscode#54713]
Currently we have "tab.hoverBackground", but this is bit inconsistent with the rest of the tab properties and also sometimes lead to not-so-nice results visually when the backgrounds of the active and inactive tabs are too contrasting. In this case finding a hover color that looks fine on both active and inactive tab is not an easy task.
I'd rather suggest to split this in two as the rest of tab properties, so we get : "tab.activeHoverBackground" and "tab.inactiveHoverBackground".

**Comment by bpasero** [comment]
Merging into https://github.com/Microsoft/vscode/issues/52862
