### ISSUE TITLE
Moving up/down effect on grayed out unused variables

### ISSUE THREAD

**Issue by HRK44** [Microsoft/vscode#54716]
- VSCode Version: 1.25
- OS Version: Ubuntu 18.04 LTS

Steps to Reproduce:

It's kinda hard to reproduce but you can try :

1. Have a function with 3 parameters, the middle one not used (should be grayed out)
2. Focus some lines inside the function
3. Make some scroll up/down
4. The unused param should move up/down

Does this issue occur when all extensions are disabled?: Yes and No

Without extensions, I can't manage to reproduce the auto-blink, but the grayed out param still moves up and down when I manually click a line inside the function after scrolling.

**Comment by alexandrudima** [comment]
@HRK44 Can you capture your screen to show what you mean? I cannot reproduce:

![kapture 2018-07-20 at 11 47 14](https://user-images.githubusercontent.com/5047891/42996054-b567e286-8c12-11e8-8b9d-e229a086838b.gif)

**Comment by HRK44** [comment]
@alexandrudima I'm using mouse scrolling, maybe that plays into account. Just a little up/down scroll then click on a line inside the function (to change the focus).

![peek 2018-07-20 11-56](https://user-images.githubusercontent.com/7391040/42996530-1cce4446-8c14-11e8-82e8-5bd9b53f643b.gif)

**Comment by HRK44** [comment]
Another one with no extensions :

![peek 2018-07-20 12-12](https://user-images.githubusercontent.com/7391040/42997240-4c4bb738-8c16-11e8-9253-b4bd3dfed773.gif)

**Comment by alexandrudima** [comment]
It looks like the usage of `opacity` for the unused decorations is causing grief with Chromium under Linux...

**Comment by bpasero** [comment]
@HRK44 would you be willing to give some feedback if you can still reproduce this issue with a newer build that uses a newer Chrome version? You can [download it from here](https://az764295.vo.msecnd.net/exploration/198d785facf747b1f26234807376c6b3da09ef7a/code-exploration-1533906522.tar.gz). You will notice a new "VS Code Exploration" application with an orange icon.

Thanks!

**Comment by HRK44** [comment]
@bpasero I didn't manage to reproduce the issue, looks clean
