### ISSUE TITLE
File association for bash_profile not working

### ISSUE THREAD

**Issue by juol** [Microsoft/vscode#5471]
- VSCode Version: 1.0
- OS Version: OS X Yosemite

Steps to Reproduce:

`files.associations {
    "*bash_profile": "sh"
}`

**Comment by bpasero** [comment]
@juol I cannot reproduce. does it not work after a restart even?

**Comment by juol** [comment]
Ok, works on opening code from command line in a directory:
`code .`

But not from command line when opening file directly:

`code .bash_profile`

**Comment by bpasero** [comment]
Also works for me. Are you sure you are not mixing insiders release with stable release maybe and the setting only applies to the insiders?

**Comment by juol** [comment]
Using 1.0.0,

`"Vagrantfile": "ruby"`

works fine, so the new setting is there.

I don't have a shebang at the top of my `.bash_profile` as it is sourced and not executable. That's why I'm trying to do this. Still not working on my box.

**Comment by bpasero** [comment]
@juol actually it seems that any .bash_profile is associated to shell. When you look at the language indicator in the bottom right corner, what language is shown for .bash_profile?

See my video how it shows the language to be shell:

![untitled](https://cloud.githubusercontent.com/assets/900690/14633979/edea8cfe-0617-11e6-846d-e4f94cfc0320.gif)

**Comment by juol** [comment]
I have a repo for my dot files. In this repo I have renamed `.bash_profile` to `bash_profile` so it is not hidden. I symlink to this from my home directory.

So I hoped that `"*bash_profile": "sh"` would pick up both these files. It doesn't seem to on my machine.

The simplest way to reproduce this seems to be:

```
mkdir issue5471
cd issue5471
cp ~/projects/dotfiles/bash_profile .
cp bash_profile .bash_profile
```

Now `code .bash_profile` works but `code bash_profile` doesn't, It reports as Plain Text.

**Comment by bpasero** [comment]
The fix is to use the following setting:

files.associations { "*bash_profile": "shellscript" }
