### ISSUE TITLE
Coverage decreased (-97.7%) to 0.0%

### ISSUE THREAD

**Issue by arthurbuhl** [Microsoft/vscode#54718]
- VSCode Version: 1.25
- OS Version:

It seems there is some issue with code coverage for this repo, as coverage decreased (-97.7%) to 0.0%. If this is intended behavior, then please remove the coverage badge from readme.
 
Steps to Reproduce:

1. Please visit: https://coveralls.io/builds/18036959

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
I have deleted the Coveralls build, since we don't really use it.

Created https://github.com/Microsoft/vscode/issues/55647
