### ISSUE TITLE
Code Folding In Integrated Terminal

### ISSUE THREAD

**Issue by anuraghazra** [Microsoft/vscode#54720]
# Code Folding In Integrated Terminal
If vscode have code folding in the Integrated Terminal like google chrome's debugger have then the terminal will be much more easy to use.
> so the arrays and objects will show like this 

![chrome debugger](http://i1188.photobucket.com/albums/z413/headshot9x9/Untitled.png)

**Comment by Tyriar** [comment]
We already do this in the debug console, the problem with doing it in the terminal is it's just unstructured text; we don't know what it's going to be (or even what's running in the terminal) so it cannot be formatted like this.

**Comment by anuraghazra** [comment]
OK, I understand. Thanks for the response. But it will really help use debug our nodejs code..
