### ISSUE TITLE
Pressing up when on the first of multiple suggestions for the same function closes the dialog

### ISSUE THREAD

**Issue by glek** [Microsoft/vscode#54726]
- VSCode Version: 1.26.0-insider (commit 26e5a55cd8452477bfb7a472ea9475761600adf0)
- OS Version: Arch Linux (rolling release, kernel 4.17.6-1-ARCH)

Steps to Reproduce:

1. With the following minimal code sample:

```ts
class FooBar {
    public baz(str: string);
    public baz(v: number);
    public baz(v: any) {

    }

}

const f = new FooBar();
f.baz
```

2. Trigger autocomplete by placing the cursor after the `f.baz` and type `(`.
3. Attempt to navigate to the next override definition by pressing the up arrow on the keyboard.

Expected Results:

* Autocomplete dialog cycles to the last override definition.

Actual Results:

* Autocomplete window disappears.

Does this issue occur when all extensions are disabled?: Yes

Example:

![vscode_bug](https://user-images.githubusercontent.com/1039449/43005385-b2ea2e22-8c00-11e8-9867-d4028d4ee311.gif)

**Comment by jrieken** [comment]
That's on purpose because there have been complains about signature help stealing the arrow keys - see https://github.com/Microsoft/vscode/issues/51191. A way out of this would be adding an option.

**Comment by ozyx** [comment]
I'm working on adding an option for this which would default to `false`. Should have a PR up soon.

**Comment by roblourens** [comment]
Hey @jrieken, this PR removes the `'editor.parameterHints'` setting entirely, was that intended?

**Comment by jrieken** [comment]
Yeah, there is now `"editor.parameterHints.enabled"` and `"editor.parameterHints.cycle"`

**Comment by roblourens** [comment]
Yes but typically wouldn't we deprecate the setting instead of removing it in a single release? 

I need a better way to handle this in the new UI because right now it will just break those settings silently https://github.com/Microsoft/vscode/issues/56768
