### ISSUE TITLE
Using 'alt' to create multiple cursors and then rapidly relasing it causes the menu bar to focus, making the multiple cursors disappear

### ISSUE THREAD

**Issue by iansan5653** [Microsoft/vscode#54723]
- VS Code Version: 1.26.0-insider
- VS Code Commit: 023b51bcc6204cc9bb9ca7752f764a3396401ec7
- OS Version: Windows 10 Home 1803

Steps to Reproduce:

1. Enable the new menu bar
2. While an editor is active, press and hold alt
3. Rapidly click in another place to create a second cursor
4. Rapidly release alt (within less than a second)
5. If it was fast enough, all cursors will disappear and you'll be unable to type until you refocus the editor.

This is a pretty serious issue as it's very common to be typing and quickly want to create a second cursor and continue typing; I run into this every couple of minutes.

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by iansan5653** [comment]
This is definitely related to #54065 and #53924, however it's a different bug in that it doesn't happen every time, only when performed rapidly.

**Comment by sbatten** [comment]
@iansan5653 Sorry about that. I will fix this shortly. Fyi, until this is fixed, if you single press alt again after you focus the menu, the editor will regain focus and your multicursor selection will return.
