### ISSUE TITLE
Search stop button needs ux love

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#54727]
Start a long running search, notice the ugly stop icon
I feel like somebody took the debug stop and stripped it of its color. Notice how it is too bright compared to the other icons. Also it feels a bit too large / too strong

![screen shot 2018-07-20 at 15 53 14](https://user-images.githubusercontent.com/1926584/43006076-1529fe58-8c35-11e8-9a49-1aa47eea1d07.png)

**Comment by bpasero** [comment]
Should we use the exact same icon as the "Debug" stop icon maybe?

**Comment by isidorn** [comment]
It goes with the redish clear. But still looks too strong and distracting for me.
Why do we need a button for that in the end, why doesn't esc simply cancel the search?

**Comment by bpasero** [comment]
I think ESC is not really discoverable and the button only shows up when search is taking a long time (as far as I remember). I don't mind the button there, but I am also not a big fan of the icon we have at the moment.

**Comment by misolori** [comment]
Typically you see an `X` to cancel/stop progress, but we use that icon for closing items so it feels a bit out of place. Here's a few variations:

![image](https://user-images.githubusercontent.com/35271042/44415115-7bd89f80-a524-11e8-887c-6771673c9f5e.png)

I think an interesting idea is using the loading spinner and placing the stop icon on hover. Though we already have the viewlet progress indicator so it might be a duplication but the icon and interaction feels a little more natural:
![image](https://user-images.githubusercontent.com/35271042/44415285-e4278100-a524-11e8-927d-921d8d2223dc.png)

**Comment by roblourens** [comment]
> I think ESC is not really discoverable and the button only shows up when search is taking a long time (as far as I remember)

This is right, we used to get a lot of complaints about not being able to cancel a search.

**Comment by bpasero** [comment]
@misolori I am not sure I would agree that X is used to stop a running operation, it feels to me the stop button makes more sense. I associate X more with closing something then stopping something.

**Comment by misolori** [comment]
@bpasero here's a few examples where X is used to stop a running operation:

<img width="50%" src="https://user-images.githubusercontent.com/35271042/44475285-74c79500-a5e9-11e8-889b-44c3989ed1d2.png">

<img width="50%" src="https://user-images.githubusercontent.com/35271042/44475214-4d70c800-a5e9-11e8-8967-79707e044d1a.png">

<img width="50%" src="https://user-images.githubusercontent.com/35271042/44473627-8e66dd80-a5e5-11e8-9a65-b170c6e1afff.png">


If we want to keep using the "Stop" icon, we can either make the current one smaller and match the correct color or use an alternate stop icon:

![image](https://user-images.githubusercontent.com/35271042/44475094-0682d280-a5e9-11e8-895d-25b1e85c5dd0.png)

**Comment by bpasero** [comment]
@misolori that icon might work in other apps, but in VSCode every usage of the "X" is for closing something, not stopping something.

**Comment by misolori** [comment]
@bpasero agreed, I was just pointing out that other apps also use the X in other ways.

What are your thoughts on either stop button?

**Comment by bpasero** [comment]
@misolori how did the stop button change in the first screenshot?

**Comment by misolori** [comment]
It's subtle, I made it smaller by 2px, removed the white border, and used the same gray color as the other icons.

**Comment by bpasero** [comment]
@misolori yeah let's try it out in insiders

**Comment by isidorn** [comment]
Yeah without the border it at least looks better. We shuold try it out
