### ISSUE TITLE
Searching Large folder freezes entire machine

### ISSUE THREAD

**Issue by jovere** [Microsoft/vscode#54730]
Issue Type: <b>Bug</b>

If I try to search in all files for "QT_QPA_EGLFS_INTEGRATION" with the Qt source tree as the root, after a few "hits" the entire system locks up.

I'm searching `/Qt/5.9.6/Src` which has the following directory contents:
```
coin             qtcharts            qtmultimedia      qtserialbus        qtwebsockets
configure        qtconnectivity      qtnetworkauth     qtserialport       qtwebview
configure.bat    qtdatavis3d         qt.pro            qtspeech           qtwinextras
configure.json   qtdeclarative       qtpurchasing      qtsvg              qtx11extras
gnuwin32         qtdoc               qtquickcontrols   qttools            qtxmlpatterns
qt3d             qtgamepad           qtquickcontrols2  qttranslations     README
qtactiveqt       qtgraphicaleffects  qtremoteobjects   qtvirtualkeyboard
qtandroidextras  qtimageformats      qtscript          qtwayland
qtbase           qtlocation          qtscxml           qtwebchannel
qtcanvas3d       qtmacextras         qtsensors         qtwebengine
```

I completely disabled all extensions and I'm still getting this issue.  I've previously had this issue with the Perforce extension just installed, but as shown below, I have Zero extensions.

I remember something about having to increase "nodes?" when running VSCode for the first time otherwise it would crash when opening large directories, like it wants to index everything.  Perhaps this is the issue?

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:40:20.190Z)
OS version: Linux x64 4.10.0-20-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1800X Eight-Core Processor (16 x 3600)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Load (avg)|0, 0, 0|
|Memory (System)|31.35GB (29.31GB free)|
|Process Argv|/usr/share/code/code Qt/5.9.6/Src/|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by roblourens** [comment]
I tried the same repo with no issues. Can you use the vscode process explorer (Help > Toggle Process Explorer) to see which process is busy?

**Comment by jovere** [comment]
I tried, but the entire machine becomes unresponsive in a couple seconds.  If I have the window open before I start the search, it does a single update (the only changes are zygote at 1%, watcher service at 995MB of memory) and then freezes.  The clock in the system tray also freezes.  If I open it after the search has started, it never even fills in the window.  I can't even switch to the Linux console (using Ctrl-Alt-F1).  The only way for the system to become responsive again is a hard reset.

**Comment by roblourens** [comment]
Is this a lower power or single core machine, or a VM?

**Comment by jovere** [comment]
Nope, as shown in the system info, it's a Ryzen 7 1800X with 32GB of RAM.

**Comment by jovere** [comment]
Some things I've noticed...

Usually, I'm using this with Synergy as a "remote" system.  A couple seconds after the search starts, I no longer have network connectivity and the Synergy network interface dies.  So, I disabled Synergy and used a directly connected keyboard/mouse to take that out of the equation.  The directly connected mouse "works" in that I can move the cursor, but *nothing* else responds.  If I try to plug in any USB devices, (such as another mouse), nothing happens.  The mouse never turns on any lights, so that is telling me it's never getting enumerated on the USB bus.

Also, I've had the lockup issue in the past just opening a directory with many files.  I learned that this was  due to the Perforce plugin, which I have since stopped using.  However, in this case I am not using any extensions, with just the base search mechanism. Reference here: https://github.com/Microsoft/vscode/issues/43838#issuecomment-369600314

**Comment by roblourens** [comment]
Can you try setting `"search.useRipgrep": false` to see if that's any different?

Also, can you try a search that won't produce any results?

**Comment by jovere** [comment]
> Can you try setting "search.useRipgrep": false to see if that's any different?

Adding the above setting worked without issue.  I compared it to the following command line call, and they both returned the same results:
`grep -rnw Qt/5.9.6/Src/ -e 'QT_QPA_EGLFS_INTEGRATION'`

One thing I noticed... When using the standard settings, there is a short line above the search bar that moves left and right forever, like it doesn't know when the search will end.  When using the `"search.useRipgrep": false` option, the bar fills like a regular progress indicator.

**Comment by roblourens** [comment]
> When using the "search.useRipgrep": false option, the bar fills like a regular progress indicator.

Yeah that's just an expected difference between the two.

With the default settings, we just invoke ripgrep on the folder. Can you try running ripgrep manually from a terminal to see if that alone causes this to happen?

It should be at `/path to vscode installation/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg`

And you can just invoke it like `/pathToRg searchString /pathToWorkspace`

**Comment by jovere** [comment]
Yup, that results in instant death.  The mouse moves and nothing else works.  I've noticed that `rg` is also run in the #43838 issue I mentioned earlier from the Perforce plugin.  I never noticed the issues until I updated to VSCode 1.20.

**Comment by roblourens** [comment]
Ok, that's probably the issue over there too. Extensions have some different ways to start a search.

Could you open an issue in https://github.com/BurntSushi/ripgrep to see what the maintainer needs to troubleshoot the issue? Also does it work ok in a smaller folder? I noticed that repo has a lot of submodules, what if you pass `--no-ignore` so it isn't looking for .gitignore files everywhere?

**Comment by roblourens** [comment]
And thanks for the investigation help, I'm sure killing your computer on every iteration is getting annoying but we appreciate it 😁

**Comment by jovere** [comment]
For future reference, there was a kernel bug in 4.10.0-20 that was causing the freezing issue with ripgrep.  All the ripgrep processes were at 100% kernel time and couldn't be recovered.
