### ISSUE TITLE
`cursorHomeSelect` stops working after launch

### ISSUE THREAD

**Issue by pwilver12** [Microsoft/vscode#54737]
Issue Type: <b>Bug</b>

I am having trouble with the default `cursorHomeSelect` and `cursorEndSelect` keyboard shortcuts in my instance of VS Code. These bindings seem to work when VS Code is first opened, however they stop working once another keyboard shortcut is executed (e.g. `cursorUpSelect` with `shift+up`).

For Mac, there are two shortcuts that trigger each of these actions. The ones that are giving me trouble are `shift+cmd+left` and `shift-cmd-right`. I've tried to test whether other applications on my machine are intercepting the bindings (I thought it may have been SizeUp), but I can't seem to get them to work reliably even when running VS Code as my only open application.

I have colleagues that are also using VC Code on similar machine setups, and this command works flawlessly for them (same OS version, same VS Code version).

I really want to use VS Code, but I use this command 1,000+ times a day. I'm lost without it!

VS Code version: Code - Insiders 1.26.0-insider (26e5a55cd8452477bfb7a472ea9475761600adf0, 2018-07-20T05:11:33.977Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.22GB free)|
|Process Argv|/private/var/folders/cz/l01tdfy52rj2yr2sw5c547tdlyc079/T/AppTranslocation/B9E2814A-E6F7-4042-B61A-11522CAB8E3A/d/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_344148|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by alexandrudima** [comment]
@pwilver12 Can you check by opening the keybindings editor (cmd+k cmd+s) which keybindings are bound to `shift+cmd+left` and `shift+cmd+right` ?

These are the default ones we ship with:
![image](https://user-images.githubusercontent.com/5047891/43063114-4a2f71a0-8e5b-11e8-826d-24bc8fa20f7c.png)

**Comment by pwilver12** [comment]
@alexandrudima I'm seeing the same thing as you. See below.

![screen shot 2018-07-23 at 7 38 09 am](https://user-images.githubusercontent.com/10912966/43074496-7a6cbf4a-8e4b-11e8-8f9b-93aca0d15e54.png)

The interesting thing is that if I try to edit that mapping, or even create my own, it refuses to accept that combination. E.g. I hold `shift+cmd` and attempt to hit my left arrow key, and it won't register:

![screen shot 2018-07-23 at 7 40 24 am](https://user-images.githubusercontent.com/10912966/43074548-b0148736-8e4b-11e8-88e7-672d9d94dcb9.png)

**Comment by alexandrudima** [comment]
@pwilver12 This means that the keybinding does not reach VS Code, so we cannot dispatch it to `cursorHomeSelect`. IMHO I think you have some piece of software on the machine that is eating up that key combination.

Can you try with a guest account or something...
