### ISSUE TITLE
Give the option to fix centered layout width.

### ISSUE THREAD

**Issue by jonnyso** [microsoft/vscode#54731]
Previously the centered layout in zen mode had a fixed width, meaning that if you resize the window the centered section will remain the same as long as it still fits in the resized window. The behaviour now is for the centered section width to be proportional to the size of the window. See below:

![image](https://user-images.githubusercontent.com/30509290/43009531-57ddd10a-8c14-11e8-9ee0-597c2a9e8466.png)

On resize, old behaviour/new behaviour:

![image](https://user-images.githubusercontent.com/30509290/43009812-1187e6e0-8c15-11e8-980f-b3251e081dc4.png)

**Comment by isidorn** [comment]
This is a fair feature request. I know @joaomoreno wanted something like this.

**Comment by FancyBanana** [comment]
I agree, having the editor window resized every time you toggle sidebar is quite annoying for me. It would also be nice to bring back switching back to full-size layout when having more than 1 editor open side by side.

**Comment by FancyBanana** [comment]
@isidorn I think this issue is closely related to #53989

**Comment by zhiayang** [comment]
So does this mean that you're not going to address this issue any time in the near future? "Issue grooming" seems to simply be a euphemism for getting rid of issues that nobody wants to fix.

**Comment by Gameghostify** [comment]
Can this be reopened? I feel this would be a great change

**Comment by isidorn** [comment]
Yes I can reopen.

**Comment by Gameghostify** [comment]
@isidorn Thanks a lot!

**Comment by jan-scorl** [comment]
Any plans on implementing this?

**Comment by akbyrd** [comment]
I love the centered layout feature and I _really_ want to be able to use it. Unfortunately it's unusable as is and I've avoided it for the last couple of years waiting for it to be addressed.

First and foremost, the size *must* be absolute, not relative. The current behavior is honestly just broken. I can't think of a sane reason why it would be relative. Look at the results:

Sane:
![image](https://user-images.githubusercontent.com/484784/79012105-598cfe80-7b1a-11ea-8971-cfa64d262921.png)

Not sane:
![image](https://user-images.githubusercontent.com/484784/79012273-cb654800-7b1a-11ea-815d-2e1c61707d28.png)

This is also being asked for here: https://github.com/microsoft/vscode/issues/71361#issuecomment-491854562

Second, we need settings for whether to use centered layout and to set the default size. I put in a [request for this](https://github.com/microsoft/vscode/issues/45242) years ago and it was inexplicably renamed to a completely different request and closed as a duplicate.

P.S. I'm now noticing it's even not centered properly? That's weird...

**Comment by isidorn** [comment]
This is a fair feature request and we are open for a lean and good PR that fixes this
Code pointer https://github.com/microsoft/vscode/blob/b7a9bfa7f9e8d34414b1319ff214eb8a2f55c524/src/vs/base/browser/ui/centered/centeredViewLayout.ts#L65

**Comment by edgarfroes** [comment]
Any plans on implementing this?

**Comment by zhiayang** [comment]
Looks like somebody already implemented a PR for it (#104942), but the vscode people decided to close it for petty reasons.

**Comment by fareloz** [comment]
I miss this feature for almost a year. Any news on when it will be implemented?

**Comment by victorvianna** [comment]
Rather than have it be fixed size, I'd rather have the editor adjust to the rulers you define for each file extension. I work in a project where .cc files can have 80 chars, .java can have 100 and my debug logs are unbounded. So whenever I switch I have to adjust the width manually.

**Comment by arsdever** [comment]
Does anyone know any workaround until someone finds time to implement it in vscode natively? Any extension that solves this problem?

**Comment by ma-sadeghi** [comment]
Any updates?

**Comment by fareloz** [comment]
I wrote my comment here back in 2018... now is 2022 and this annoying issue is still here, sadly. Ok, the dev team doesn't want to add such a change to the main code base. But at least five an API to create an extension for those you needs this.

**Comment by ma-sadeghi** [comment]
My main issue is the terminal pane. I used to put the terminal pane side by side the editor, and pop it on and off when I needed it. The problem was that in the occasions where I needed both, the editor width was shrunk down to an unusable width due to the centering issue. So, everytime I had to manually switch back and forth between normal and center modes. 

Until yesterday, which I gave up and put the terminal at the bottom, so I no longer need to frequently switch to normal mode. It's a pain though, since I lose half the screen height when I need both the editor and the terminal 😟

Please make this an option. There's already an option that automatically turns off the center mode when you open another "window", but it doesn't apply to the terminal pane.

**Comment by thernstig** [comment]
@FancyBanana I am going to go out in a limb here and ask if https://github.com/microsoft/vscode/issues/60900 can be fixed as I find it even more relevant than a fixed width, but subjective of course.
