### ISSUE TITLE
Submenu arrows too large

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#54738]
Opening the view menu I only see them screaming at me due to their size. Can we somehow decrease their size.

The native mac arrows are slightly smaller. While visual studio on windows uses a much smaller version

![screen shot 2018-07-20 at 17 33 40](https://user-images.githubusercontent.com/1926584/43011252-2d3ef0e4-8c43-11e8-84a8-46dee445bdec.png)

![screen shot 2018-07-20 at 17 35 22](https://user-images.githubusercontent.com/1926584/43011295-4b7be792-8c43-11e8-9a7d-7d2ecdb7ad1f.png)

**Comment by isidorn** [comment]
This is the custom toolbar on the windows we are currently working on. So we could customize it here imho

**Comment by bpasero** [comment]
+1 I think the arrow could be reduced a bit
