### ISSUE TITLE
Pressing alt should underline all accelerator menu keys

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#54736]
Press alt, focus nicely moves to the file menu, however I would expect all the menu entries to underline their acceselaror keys. Example

![screen shot 2018-07-20 at 17 20 15](https://user-images.githubusercontent.com/1926584/43010612-330b8458-8c41-11e8-9e55-6fb194994045.png)

**Comment by sbatten** [comment]
this issue has been fixed and verified elsewhere
