### ISSUE TITLE
vscode 1.0 can't auto detect charset 

### ISSUE THREAD

**Issue by sswangifly** [Microsoft/vscode#5473]
- VSCode Version:1.0
- OS Version:windows 10

Steps to Reproduce:

1. open GB2312 /ASCI charset file with vscode
2. vscode open file with utf8 charsset and chinese characters are not displayed properly

**Comment by bpasero** [comment]
@sswangifly you need to set the encoding in your settings either globally or per workspace.

#5388 is the duplicate.
