### ISSUE TITLE
Breadcrumbs: focus needs love

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#54745]
I feel like the focus moving needs more work in the breadcrumbs. Here are my suggestion:

1. When focus on first tree element UP will move focus to the actual breadcrumb which is the parent of the tree
2. It is possible to use Tab to focus the whole breadcrumb thing (once the focus is there use arrow keys to move focus). They would optimaly get focus after the tab area
3. Tab inside the tree should move focus out of the breadcrumbs (and not navigate to that item like now, enter is for that)
4. Focused element in the breadcrumb has a stronger visual feedback (especially hard to spot for the `...`)
5. Once we have that all figured out I would expect that we announce what keys we use for navigation once breadcrumbs is focused

Shift + left / right is nice but people will not discover it imho. Also why did you use shift, and not alt since that is the alternative modifier which we use across the workbench.

**Comment by jrieken** [comment]
> When focus on first tree element UP will move focus to the actual breadcrumb which is the parent of the tree

That is: https://github.com/Microsoft/vscode/issues/53950

**Comment by jrieken** [comment]
> Tab inside the tree should move focus out of the breadcrumbs (and not navigate to that item like now, enter is for that)

Not sure about that. I added tab on request of @Tyriar. It's like the tab behaviour in IntelliSense

**Comment by Tyriar** [comment]
@jrieken here's my expectation vs current:

- Breadcrumb titles are focused
  - tab
    - Expectation: Moves to the next breadcrumb, if the last breadcrumb is focused then focus the editor
    - Current: Same
  - shift+tab: 
    - Expectation: Moves focus to the previous breadcrumb, if the first breadcrumb is focused then focus the last editor group action
    - Current: Focuses the last editor group action
- Breadcrumb menus are focused
  - tab
    - Expectation: Focus the next breadcrumb's menu (shift+right), if the last breadcrumb is focused then focus the editor
    - Current: Nothing :warning: 
  - shift+tab
    - Expectation: Focus the previous breadcrumb's menu (shift+left), if the first breadcrumb is focused then focus the last editor group action
    - Current: Focuses the end of the workbench :warning:

**Comment by jrieken** [comment]
@Tyriar So, you are suggesting to use tab/shift+tab (instead of arrows) for the in-widget navigation, right?

**Comment by Tyriar** [comment]
@isidorn in the *tree* we do use arrows, I want tab to navigate the top-level breadcrumbs while the menu is focused, or at the very least focus the editor/editor group actions.

**Comment by jrieken** [comment]
>I want tab to navigate the top-level breadcrumbs while the menu is focused,

Does "menu" mean the breadcrumb picker? So, you want tab to move the picker or to close the picker and to focus the breadcrumbs?

**Comment by Tyriar** [comment]
@jrieken by menu I mean the thing that pops up when you click a breadcrumb.

**Comment by JacksonKearl** [comment]
Verified for 
- Better emphasis (underline)
- Ctrl instead of shift
- Tab leaves menu
- Tab focuses menu, then arrows move in menu

Not verified
- We don't "announce the keys".
- Up from top element doesn't close dropdown

Not mentioned here, but related: `space` opens the  menu for the right of the hilighted item, not the item itself

**Comment by isidorn** [comment]
Thanks for verifiying, the remaining issue can be looked in august

**Comment by JacksonKearl** [comment]
@jrieken I’m not sure, that’s just the wording from the original issue.

**Comment by JacksonKearl** [comment]
I added verification-found and reopened because part of the original issue was unaddressed. Is that not correct?

**Comment by jrieken** [comment]
Yeah, I think it is not correct. According to [your comment](
https://github.com/Microsoft/vscode/issues/54745#issuecomment-409718859) (that's my understanding) you reopened this because of two things: *'We don't "announce the keys".'* and *'Up from top element doesn't close dropdown'*. Is that correct? Iff so, the latter is a dupe and with the former you are not sure what it means.

**Comment by JacksonKearl** [comment]
@isidorn could you clarify what you meant about announcing the keys?

**Comment by jrieken** [comment]
> Once we have that all figured out I would expect that we announce what keys we use for navigation once breadcrumbs is focused

This means that we decide, after everything else is done, on the key*bindings* we use for navigating breadcrumbs.
