### ISSUE TITLE
Garbage collector end point  missing under Windows

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#5474]
- VSCode Version: 1.0.0 - alpha
- OS Version: Windows 10

Steps to Reproduce:

1.  From time to time when I start Code Alpha I see the following dialog. Started after Electron upgrade

![capture](https://cloud.githubusercontent.com/assets/1931590/14630681/77ca594e-060f-11e6-890b-d5305b288806.png)

**Comment by bpasero** [comment]
@dbaeumer I cannot reproduce though, do you maybe have a broken installation?

**Comment by bpasero** [comment]
This is scar but not reproducible and seems to indicate a half broken installation. 

@joaomoreno fyi if you ever saw this before. happened after the nightly update.

**Comment by dbaeumer** [comment]
Uninstalling and reinstalling fixed the issue. However A simple reinstall didn't.
