### ISSUE TITLE
TypeScript debugging breakpoints broke on VSCode 1.25.1

### ISSUE THREAD

**Issue by rilut** [Microsoft/vscode#54740]
- VSCode Version: 1.25.1
- OS Version: macOS 10.13.4 (17E199)

Steps to Reproduce:

1. Debug a Typescript project on VSCode 1.25.1. (Details: my project is not a frontend/webpack project)
2. Breakpoints would be unverified despite enabled sourcemap and correct`launch.json` and 
 `tsconfig.json`

My `launch.json` after I tried different configurations on 1.25.1:
```
        {
            "name": "LAUNCH",
            "type": "node",
            "request": "launch",
            "runtimeArgs": [
                "--nolazy"
            ],
            "envFile": "${workspaceFolder}/.env",
            "sourceMaps": true,
            "cwd": "${workspaceFolder}",
            "program": "${workspaceFolder}/start.js",
            "outFiles": [
                "${workspaceFolder}/lib/**/*.js"
            ],
            "protocol": "inspector",
            "trace": "all"
        },
```

on launch.json I've tried to enable normal sourcemap or inlined sourcemap, no success.

3. Sometimes this error pops on 1.25.1 when I hit the debug launch button:

!["root folders property missing"](https://i.imgur.com/WmPqjxQ.png)

Found no exact match on Google, seems like it's a new bug

4. If I grep the log/trace it would show the sourcemap is found/loaded/created. But breakpoints are still unverified

```
SourceMap: creating for /Users/rilut/myproject/lib/components/repos/my_repo.js
SourceMaps.scriptParsed: /Users/rilut/myproject/lib/components/repos/my_repo.js was just loaded and has mapped sources: ["/components/repos/my_repo.ts"]
```

5. After reading @chriscordova comment on https://github.com/Microsoft/vscode/issues/54697#issuecomment-406485751 that everything are okay in 1.24.1, I decided to downgrade to VSCode 1.24.1. (Details: I open the 1.24.1 without closing the 1.25.1)

6. Breakpoints are working  in 1.24.1 even without any configurations, I still use the exact launch.json from no 2

7. Can't re-reproduce the error on 1.25.1 because when I press debug:

```
Debug adapter executable '/Users/rilut/.vscode/extensions/ms-vsliveshare.vsliveshare-0.3.395/dotnet_modules/Microsoft.Cascade.VSCodeHostAdapter' does not exist.
```

![Debug adapter executable '/Users/rilut/.vscode/extensions/ms-vsliveshare.vsliveshare-0.3.395/dotnet_modules/Microsoft.Cascade.VSCodeHostAdapter' does not exist.](https://i.imgur.com/P5uCeVr.png)

**Comment by weinand** [comment]
Can you still reproduce if you disable the Liveshare extension?

**Comment by rilut** [comment]
Yes, I can launch debug again in 1.25.1, and the Unverified Breakpoints still exist.

Which logs should I provide?

**Comment by roblourens** [comment]
Can you try this in insiders?

**Comment by rilut** [comment]
I can confirm breakpoints works again in Insider.

- rm -rf lib && tsc
- debug in 1.25.1, debugging doesn't work
- debug in Insider, debugging works

**Comment by roblourens** [comment]
Great, thanks for trying that.
