### ISSUE TITLE
Alt + click in breadcrumbs should open file to the side

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#54743]
Everywhere else in workbench alt + click opens the file on the side. It would be good if the breadcrumbs tree also respected this.

**Comment by jrieken** [comment]
@isidorn Do you mean from the picker or the breadcrumb items or both?

**Comment by isidorn** [comment]
From the breadcrumb picker tree.

**Comment by jrieken** [comment]
Made Alt+Click open element to the side, also when alt+clicking an breadcrumb item. Also make Ctrl/Cmd+Enter open the element to the side (as in quick open)

**Comment by isidorn** [comment]
Great.
