### ISSUE TITLE
VS Code in portable mode cannot load loc UI first time after the move

### ISSUE THREAD

**Issue by danyeh** [microsoft/vscode#54746]
- VSCode Version: 1.25
- OS Version: Windows 10

**Customer feedback:**
[Feedback from Yuchen Deng in Marketplace](https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-zh-hans&tracking_data=eyJTb3VyY2UiOiJFbWFpbCIsIlR5cGUiOiJOb3RpZmljYXRpb24iLCJTSUQiOiJtcy5HYWxsZXJ5Tm90aWZpY2F0aW9ucy5yZXZpZXctdXBkYXRlZC1zdWJzY3JpcHRpb24iLCJTVHlwZSI6IkNPTiIsIlJlY2lwIjozLCJFbGVtZW50IjoiaGVyby9jdGEifQ%3D%3D#review-details)

**Translation of the feedback:**
If VS Code uses Portable mode (the directory has the data sub-directory), and has installed the language pack, if moved to another path, it shows English UI the first time to VS Code. I assume it is because the language pack is based on absolute path to find translations, Rather than a relative path.

**Comment by sandy081** [comment]
@dbaeumer The cache which I populate has absolute paths to extensions directory. The cache while Daniel mentioning is this or the one you populate?

**Comment by dbaeumer** [comment]
The cache file I produce has absolute paths to the extension directory as well. Something like

```
"c:\\Users\\dirkb\\.vscode-oss\\extensions\\ms-ceintl.vscode-language-pack-de-1.25.2/translations/extensions/css.i18n.json"
```

@sandy081 in portable mode where do we install extensions. In the home directory as well?

**Comment by dbaeumer** [comment]
@joaomoreno any insights on where the extensions are installed in portable mode. If they are alongside the installation how can I in main.js find out where that location is?

**Comment by loaden** [comment]
@dbaeumer the extensions are installed in 'data' sub-directory. e.g. %VSCODE%\data\extensions\ms-ceintl.vscode-language-pack-zh-hans-1.26.3

**Comment by joaomoreno** [comment]
@dbaeumer I'll add the extensionPath computation and you can then pick that up.

**Comment by loaden** [comment]
Does anyone still focus this issue? The issue exist for a while, if you guys have some move then please let me know. thx.

**Comment by dbaeumer** [comment]
Given our current priorities this is out of scope for the next months. But IMO still something we should tackle.

**Comment by dbaeumer** [comment]
@sandy081 I think we should close this as out of scope for now.
