### ISSUE TITLE
HELP: Terminal shows nothing

### ISSUE THREAD

**Issue by Fherlaban** [Microsoft/vscode#54753]
Issue Type: <b>Bug</b>

There is nothing to interact with just a white block.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 6.1.7600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5020U CPU @ 2.20GHz (4 x 2197)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.44GB (0.78GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe --log trace|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
beautify|Hoo|1.3.2
team|ms-|1.136.0
material-icon-theme|PKi|3.5.1

</details>

**Comment by Tyriar** [comment]
You should check i you have compatibility mode on, and turn off if so.

Duplicate https://github.com/Microsoft/vscode/issues/43169
