### ISSUE TITLE
 Uncaught Error: Pty seems to have been killed already

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#54754]
Issue Id: <b>ff4d91a4-d71d-8fc0-ac95-52f56d1f61f0</b><br /><br />*Versions* <br />- 1.26.0-insider (7/19/2018 5:16:52 AM)<br />*Stack* <br />Error: Pty seems to have been killed already<br />    at WindowsPtyAgent.kill (\node_modules.asar\node-pty\lib\windowsPtyAgent.js:83:13)<br />    at WindowsTerminal.<anonymous> (\node_modules.asar\node-pty\lib\windowsTerminal.js:144:26)<br />    at WindowsTerminal._defer (\node_modules.asar\node-pty\lib\windowsTerminal.js:155:24)<br />    at WindowsTerminal.kill (\node_modules.asar\node-pty\lib\windowsTerminal.js:139:14)<br />[/vs/workbench/parts/terminal/node/terminalProcess.ts#97:20](https://github.com/microsoft/vscode/blob/afc3d77e7cfc6534ba05c52f5e1289cbecd58b3d/src/vs/workbench/parts/terminal/node/terminalProcess.ts#L97:20)<br />

**Comment by ramya-rao-a** [comment]
I can repro it by killing terminals on Windows when using 64 bit system setup (not user set up)

![image](https://user-images.githubusercontent.com/16890566/44051519-ef8171c8-9eee-11e8-9047-da75d7c47530.png)
