### ISSUE TITLE
File Converted Into Either Binary Or Unsupported Text Encoding

### ISSUE THREAD

**Issue by Vishal-Isharani** [Microsoft/vscode#5475]
- VSCode Version:1.0.0
- OS Version:Windows 10

Steps to Reproduce:

1.Current Unsaved File
2. Either System Restart Or Crash Or Electricity Problem The File Converted To Binary Or Unsupported Text Encodding
![vscode issue](https://cloud.githubusercontent.com/assets/10386581/14630746/2e515e3e-062d-11e6-9f75-462ee7b42fc7.jpg)

**Comment by bpasero** [comment]
For this we need https://github.com/Microsoft/vscode/issues/1161

Marking as duplicate.
