### ISSUE TITLE
Haiku OS Port of VSCode

### ISSUE THREAD

**Issue by roired** [Microsoft/vscode#54765]
I would like to see the Port of Visual Studio Code to Haiku OS 64bit.

Not sure how much work would it be, but I presume it would not be that hard as there are already ports for OSX and Linux. If I had the skills I would try to do it myself, with prior consent from the developers, of course.

Thank you very much for taking your time in reading this "Feature request".
Regards,
Roired

**Comment by dotnetCarpenter** [comment]
@roired You need to champion for a port of [Electron](https://electronjs.org) to Haiku OS before it is possible.

**Comment by roired** [comment]
@dotnetCarpenter Thanks. I had no idea on what Electron was before. That proves that my skills are close to none... XD
I will look into that Electron thing. Step by step.
Regards,
Roired

**Comment by Tyriar** [comment]
Feel free to follow this up in [electron](https://github.com/electron/electron)
