### ISSUE TITLE
 Unable to write to Workspace Settings because no workspace is opened. Please open a workspace first and try again.

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#54761]
Issue Id: <b>8b0fd4cc-8837-fc8b-d3bf-66f7461ca432</b><br /><br />*Versions* <br />- 1.25.1<br />*Stack* <br />Error: Unable to write to Workspace Settings because no workspace is opened. Please open a workspace first and try again.<br />[/vs/workbench/parts/search/browser/replaceService.ts#73:49](https://github.com/microsoft/vscode/blob/1dfc5e557209371715f655691b1235b6b26a06be/src/vs/workbench/parts/search/browser/replaceService.ts#L73:49)<br />[/vs/workbench/parts/surveys/electron-browser/languageSurveys.contribution.ts#62:2](https://github.com/microsoft/vscode/blob/1dfc5e557209371715f655691b1235b6b26a06be/src/vs/workbench/parts/surveys/electron-browser/languageSurveys.contribution.ts#L62:2)<br />[/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#147:58 (this)](https://github.com/microsoft/vscode/blob/1dfc5e557209371715f655691b1235b6b26a06be/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L147:58 (this))<br />[/vs/workbench/parts/search/browser/replaceService.ts#96:26 (replaceService)](https://github.com/microsoft/vscode/blob/1dfc5e557209371715f655691b1235b6b26a06be/src/vs/workbench/parts/search/browser/replaceService.ts#L96:26 (replaceService))<br />[/vs/workbench/parts/search/browser/replaceService.ts#85:8 (_completePromise)](https://github.com/microsoft/vscode/blob/1dfc5e557209371715f655691b1235b6b26a06be/src/vs/workbench/parts/search/browser/replaceService.ts#L85:8 (_completePromise))<br />[/vs/base/common/async.ts#356:8 (_super)](https://github.com/microsoft/vscode/blob/1dfc5e557209371715f655691b1235b6b26a06be/src/vs/base/common/async.ts#L356:8 (_super))<br />[/vs/base/common/async.ts#340:9 (value)](https://github.com/microsoft/vscode/blob/1dfc5e557209371715f655691b1235b6b26a06be/src/vs/base/common/async.ts#L340:9 (value))<br />[/vs/base/common/winjs.base.js#1415:0 (_this)](https://github.com/microsoft/vscode/blob/1dfc5e557209371715f655691b1235b6b26a06be/src/vs/base/common/winjs.base.js#L1415:0 (_this))<br />[/vs/base/common/async.ts#336:2 (isDisposed)](https://github.com/microsoft/vscode/blob/1dfc5e557209371715f655691b1235b6b26a06be/src/vs/base/common/async.ts#L336:2 (isDisposed))<br />[/vs/workbench/parts/search/browser/replaceService.ts#84:56 (_taskSystem)](https://github.com/microsoft/vscode/blob/1dfc5e557209371715f655691b1235b6b26a06be/src/vs/workbench/parts/search/browser/replaceService.ts#L84:56 (_taskSystem))<br />[/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#1246:7 (executionEngine)](https://github.com/microsoft/vscode/blob/1dfc5e557209371715f655691b1235b6b26a06be/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L1246:7 (executionEngine))<br />[/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#709:20 (Build)](https://github.com/microsoft/vscode/blob/1dfc5e557209371715f655691b1235b6b26a06be/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L709:20 (Build))<br />[/vs/workbench/parts/tasks/node/taskConfiguration.ts#1348:36](https://github.com/microsoft/vscode/blob/1dfc5e557209371715f655691b1235b6b26a06be/src/vs/workbench/parts/tasks/node/taskConfiguration.ts#L1348:36)<br />

**Comment by sandy081** [comment]
Yes, you cannot write a workspace setting if no workspace is opened.
