### ISSUE TITLE
Region Tags in PS files broken

### ISSUE THREAD

**Issue by travis-sobeck** [Microsoft/vscode#54763]
No longer able to collapse/fold on region tags after latest upgrade.
 
- VSCode Version:1.25.1
- OS Version:Windows 10

Steps to Reproduce:

1. open powershell file with vscode
2.

**Comment by MayPLaY** [comment]
The problem doesn't seem to be VSCode, but it's the PowerShell Extention. Just disabled the extention, reload, and try again, it should work like a charm.

Sending a bug report on their repo.

**Comment by travis-sobeck** [comment]
Yes, to be more specific it has been fixed and awaiting next release https://github.com/PowerShell/vscode-powershell/issues/1428
I found this after I posted this issue.
