### ISSUE TITLE
Error icon is out of order

### ISSUE THREAD

**Issue by ngurney** [Microsoft/vscode#54769]
Issue Type: <b>Bug</b>

See screenshot: https://cl.ly/3v1S2n3R0j3G

Shouldn't it be "9+"? 

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (1.15GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_103039550|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|2.3.0
material-icon-theme|PKi|3.5.1
sublime-babel-vscode|jos|0.2.10
open-in-browser|tec|1.1.0

(6 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
Yeah, true story
