### ISSUE TITLE
I fond that I begin to love vscode,But I not found the mutiple window function in vscode

### ISSUE THREAD

**Issue by biij5698** [Microsoft/vscode#5476]
The sublime text have a function:mutiple window to open more files,But I not foud this function in vscode

**Comment by dbaeumer** [comment]
We don't have multiple window support tight now. But you can open more then one file in the editor. To switch between the files use Ctrl+Tab or the working file list in the explorer.

![capture](https://cloud.githubusercontent.com/assets/1931590/14632765/b765c7a4-061a-11e6-83c9-01d73b2398b2.png)

@bpasero moving to you for the multi window request.

**Comment by biij5698** [comment]
I hope vscode can open files by multiple windows like sublime text.thanks

**Comment by bgse** [comment]
@biij5698 In case you didn't already know, you can open two (or three) files side-by-side in the same window.

For example, if you left-click a file in the file explorer it will open. If you left-click another file while pressing 'ctrl'-key, it will open in a second editor area. This way you can see both files at the same time.

You can load another file in the left-side editor by simple left-click, and another file in the right-side editor by doing left-click while pressing 'ctrl'-key.

**Comment by bpasero** [comment]
@biij5698 can you explain to me in more words what exactly you are missing to do in VS Code?

**Comment by biij5698** [comment]
@bpasero  I want to open multiple files by the way of multi-window, such as sublime text

**Comment by bpasero** [comment]
@biij5698 you can do File > New Window and open files in there? Can you explain your scenario better?
