### ISSUE TITLE
Auto-tabbing doesn't work correctly when moving lines with shortcuts

### ISSUE THREAD

**Issue by freddyouellette** [Microsoft/vscode#54778]
- VSCode Version: 1.25.1
- OS Version: Windows 10 

Steps to Reproduce:

1. Select one or more lines in HTML
2. Move them down with a shortcut (for me, Alt-Down)

Does this issue occur when all extensions are disabled?: Yes, it still occurs.

![vscode-line-move-tab-issue](https://user-images.githubusercontent.com/25867102/43030964-18cc1586-8c5e-11e8-8b87-a30f267b5887.gif)

**Comment by rebornix** [comment]
Let's track this issue in https://github.com/Microsoft/vscode/issues/48993 , thanks for your feedback!
