### ISSUE TITLE
Can't import from package, relative path has ./ (dot slash) removed when moving files

### ISSUE THREAD

**Issue by ps2goat** [Microsoft/vscode#54770]
- VSCode Version: 1.25.1
- OS Version: Windows 10 1709, build 16299.492
- TypeScript Version: 2.8-2.9.2

Steps to Reproduce:

1. Create an npm package project
2. Put source code in a `/src` folder
3. Export your public classes in `/src/index.ts`
4. Have a root index file at `/index.ts`, and make this use `export * from './src';`

5. Create a client app that uses this npm package.
6. Have the client app's source code in `/src` folder.
7. Install your npm package from above.

Things work.  Now, the problem:

8. In the npm package, move a file that is imported by other files to a new folder.  When asked if you want to update references, choose 'Yes'.
9. Choosing 'Yes' causes the moved references to be updated.  All of my `./` in those paths are gone, including the package's root index.ts file.  When I rebuild/publish the package, it now has `export * from 'src';` in `/index.ts`. This is the bug.
10. Install the latest version of your npm package into your client app. You should now not have any importable members in the npm package.

### 1. STOP REMOVING `./` from import paths.
It's nice to leave our explicitness alone, and in the case of bug 2, the relative path is a workaround.
### 2. The TypeScript (?) package import Intellisense could not find any exported members.
It took a while to figure out why.  I thought a co-workers deployment updates, made while I was on vacation, were to blame.  Within my client app, which installed my npm package, I F12-ed on my imported package name, and it took me to the main index.d.ts file (root file).  I then saw the line of `export * from 'src';`.  I F12-ed on 'src', and it took me to my client app's `/src/index.ts` instead of the package's!

I suggest that when importing from a package, the paths be treated as relative to the package and not the root of the application.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by ps2goat** [comment]
Using VS Code version 1.26.0-insider, all extensions disabled:

It looks like the specific problem with number 1 no longer happens.  I did find additional bugs with import path updates not working when moving a file more than one directory up or down the hierarchy, though. I can't pinpoint it enough to document exactly what is happening, but it is easily reproducible in my project.

Bug number 2 is still present-- the index file of the npm package with `export * from 'src';` still navigates to the client application's `src` folder.

**Comment by mjbvz** [comment]
For 2, VS Code targets a commonjs style module system by default. You likely have configured `baseUrl` in the `tsconfig.json` so that absolute imports are resolved relative to the root of the project. Try targeting a different module system if you don't want this behavior:

```
{
    "compilerOptions": {
        "module": "es6",
        "target": "es2016",
        "jsx": "preserve",
        "baseUrl": "."
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```
