### ISSUE TITLE
File explorer doesn't show changed files

### ISSUE THREAD

**Issue by delmyers** [Microsoft/vscode#54774]
Issue Type: <b>Bug</b>

Start with a folder that looks something like this, pulled from a Git repo:
```
Root
  FolderA
    File.txt
```
Create a new folder, FolderB, and copy File.txt into it:
```
Root
  FolderA
    File.txt
  FolderB
    File.txt
```
make a change to FolderB/File.txt

Expected result:
  File.txt is italisized to mark that it has changes in it

Actual result:
  File.txt is not italisized.

This has caused me to miss checking in a few changes to my repo today because I thought that I had saved all of the files in my folder, but they were not saved.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.69GB (5.58GB free)|
|Process Argv|D:\Program Files\Microsoft VS Code\Code.exe .|
|Screen Reader|yes|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.17.7
code-eol|soh|0.3.3

(1 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
> File.txt is italisized to mark 

Not sure what you mean. We don't italisize items, we add a little letter to the end like U or M and change the color. The italic style is used in editor titles and the open editors view to indicate if an editor is open in preview mode or not.
