### ISSUE TITLE
Debug pointer should not highlight blank line while debugging (with F10).

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#5477]
- VSCode Version: 1.0.0-alpha
- OS Version: Windows10

Steps to Reproduce:

1. Launch VSCode and open a folder which contains .ts project.
2. Set configuration for launch.json (sourceMaps : 'true') and tasks.json.
3. Perform build with CTRL+SHIFT+B and verify app.js is generated.
3. Now set break point to app.ts and start debugging.
4. Keep debugging with F10 and verify debug pointer.

Actual: Looks like debug pointer is not referring latest code and highlighting the blank line while debugging.
Expected: Debugger should not highlight the blank line.

You can refer the sample project from : v-pavanp/ForTestingCode@ 551ea09 

![debugpointer issue](https://cloud.githubusercontent.com/assets/17735796/14631231/4acce49a-05c7-11e6-9e2d-29c58b25043e.gif)

**Comment by isidorn** [comment]
We are highlighting the blank line because the adapter sends the stop event on that line.
I believe this is desired behavior, what do you get when you use node-inspector in the same setup?

Forwarding to @weinand so he can decide if this is as designed

**Comment by weinand** [comment]
@v-pavanp this looks like a source map problem. Could you please verify with this tool http://sokra.github.io/source-map-visualization/#typescript that the source map is correct (or zip up the three files and attach them here so that I can investigate).

**Comment by v-pavanp** [comment]
I tried with the provided tool and after loading all the required files, I am getting error "Unable to get property 'substr' of undefined or null reference"
Find the attached zip file which contains all the three files.
[app.zip](https://github.com/Microsoft/vscode/files/226723/app.zip)

**Comment by weinand** [comment]
@v-pavanp since in similar issue #5264 your source maps weren't up-to-date, could you please make sure that your source maps have the same time stamps as the generated JavaScript files.

If this is not the issue, please let me know and I will reopen this issue.
