### ISSUE TITLE
workspace.applyEdit allows 'concurrent' calls to succeed

### ISSUE THREAD

**Issue by grork** [Microsoft/vscode#54773]
In Stable, when calling `applyEdit `multiple times before the first one is complete, subsequent calls are rejected, until the first edit is completes. This allows you to make the assertion that if an `applyEdit `succeeds, there should be one, and only one, `onDidChangeTextDocument `change event containing the edits that were applied.

This is not true in Insiders -- both `applyEdit `calls will succeed, and there will be multiple `onDidChangeTextDocument `events raised.

Attached is an example extension that has one command -- `minibash.concurrentBash` that will show the repro.

Expected Debug console output w/ Stable:
````
1: Applying Edit: 0,0, text: 'O'
2: Applying Edit: 0,0, text: 'DRENG'
Doc changed with 1 changes
1: Applied Edits
2: Applied Edits
2: Failed to apply edits
Failed
````
Output w/ Insiders:
````
1: Applying Edit: 0,0, text: 'M'
2: Applying Edit: 0,0, text: 'RRGAOCOQ'
Doc changed with 1 changes
Doc changed with 1 changes
1: Applied Edits
2: Applied Edits
saw multiple edits
saw multiple edits
Failed
````

To run this:
1. open the extension sources, and F5
2. create a new empty document (or open existing one)
3. Run `Minibash: Concurrently Bash`
[Minibash.zip](https://github.com/Microsoft/vscode/files/2215702/Minibash.zip)

Note, that if you remove the `return false;` on line 69 in `doEditsUntilBad`, you'll see that Insiders will happly apply 1000 edits. Stable does not; it immediately fails on the second edit (As expected)

**Comment by alexandrudima** [comment]
@grork Thank you for the repro. 

I can reproduce. This issue was introduced with https://github.com/Microsoft/vscode/commit/54a6ec8f588c766349e5d36891d0bd13b8673462#diff-ffd7342f51e8e5d64bad8622e6f5a48e

The gist of it is that the version id is checked and then asynchronously the edits are applied. We should check the version id right before applying the edits...

**Comment by jrieken** [comment]
Thanks @alexandrudima
