### ISSUE TITLE
Option to automatically open markdown in preview 

### ISSUE THREAD

**Issue by abdhx** [microsoft/vscode#54776]
Add a setting `markdown.defaultView` to automatically open .md files in preview mode instead of editing mode.
This is so useful, because the most of time, I just want to read the .md files.

**Comment by jcgerhard** [comment]
This would be a perfect solution! I am using vscode for nearly everything day in day out. And I built a private wiki/knowledgebase based on markdown files. An option like `markdown.defaultView` would be a perfect solution! Most of the times I want to read-only my documents in fullsize view without the need to see the source code! As a reference you can check typora.io and/or notable app where this feature is amazingly implemented.

**Comment by evanharmon1** [comment]
I definitely agree. This seems like a clear win to have an option for this.

**Comment by JudyLipinski** [comment]
We use VSCode to teach Web Dev and Python and love to use markdown files for instructions. It would be incredibly helpful to have an option like markdown.defaultView to help those who are a bit less technical be distracted by the edit mode.

**Comment by jcgerhard** [comment]
Any news on this? Seems like this request is completely ignored. I am very afflicted because this simple tiny feature would make all other note-taking tools obsolete! Hey Devs...pull yourself together...pleeeaaase...and add this feature! I think it wouldn‘t be very hard to implement.

**Comment by mjbvz** [comment]
Locking as none of the comments are anything but fancy +1s

If you are actually interested in working on this feature and have ideas on how to implement it, please let me know (just open a separate issue and reference this one)

**Comment by mjbvz** [comment]
I have checked in prototype that allows you to set the markdown preview as the default editor: #84520 We are looking for the community to drive the testing and polishing of this feature so that it can ship, so please follow up on #84520 if you wish to contribute

**Comment by mjbvz** [comment]
This has actually be possible for a while. To change this, you can configure the default editor for `.md` files (or whatever other markdown file extension  you wish). Here's an example setting:

```
"workbench.editorAssociations": {
	"*.md": "vscode.markdown.preview.editor"
}
```

Use the `reopen with` command to switch back to the standard text editor
