### ISSUE TITLE
Another wrong german translation in the "report issue" dialog

### ISSUE THREAD

**Issue by AlCalzone** [Microsoft/vscode#54789]
Issue Type: <b>Bug</b>

1. Open "report issue" dialog
2. See this.
![issue3](https://user-images.githubusercontent.com/17641229/43034805-ac9168b8-8ce3-11e8-8c8a-6844a27c584e.PNG)

The highlighted link is labeled with an entire sentence which makes sense on its own, but not in the spot where it currently is. The link should probably read something along the lines of
*"Versuchen Sie, das Problem nach __erneutem Laden des Fensters mit deaktivierten Erweiterungen__ zu reproduzieren"*

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3403)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.96GB (7.56GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.12
gitlens|eam|8.5.2
tslint|eg2|1.0.34
RunOnSave|eme|0.0.16
vscode-language-pack-de|MS-|1.25.2
vscode-docker|Pet|0.0.27
project-snippets|reb|0.5.0
java|red|0.28.0
vscode-coverage-gutters|rya|2.0.1
vscode-java-debug|vsc|0.10.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.7.1
vscode-maven|vsc|0.9.2

</details>

**Comment by danyeh** [comment]
@AlCalzone, thank you very much for your feedback!
Translation is opened to community in Transifex. It will be great if you can help to fix there.
See https://aka.ms/vscodeloc for localization project background. Sign up Transifex free.
Here is the string: https://www.transifex.com/microsoft-oss/vscode-workbench/translate/#de/$/132525384?q=text%3A'disabling+all+extensions+and+reloading+the+window'

**Comment by danyeh** [comment]
Thank you @AlCalzone for your help! The translation you suggested is being used now. It will be reflected in German language pack v1.26.
