### ISSUE TITLE
ECMAScript 2018, regular expression, lookbehind in search bar

### ISSUE THREAD

**Issue by PawelekS** [Microsoft/vscode#54785]
Chrome (so chromium and propably electron too) have that feature. When i wanted use it in VSC search bar, I getted an error ;/

VSC:
![image](https://user-images.githubusercontent.com/28712303/43034292-54048d14-8cda-11e8-8544-264361f1839f.png)

Chrome console:
![image](https://user-images.githubusercontent.com/28712303/43034406-fe2b7c98-8cdb-11e8-8865-fcaa05f05e7e.png)

Well - this is both feature suggestion and error report

That's may be helpful:
https://github.com/tc39/proposal-regexp-lookbehind

**Comment by roblourens** [comment]
Some regex features are not supported. See the bottom of this paragraph: https://code.visualstudio.com/docs/editor/codebasics#_advanced-search-options
