### ISSUE TITLE
Search like in Visual Studio

### ISSUE THREAD

**Issue by TheEagle82** [Microsoft/vscode#54784]
I love Visual Code and Visual Studio. However, in Visual Code, the search for files is not as easy as in Visual Studio. I suggest to have it same as in Visual Studio on top of the Explorer

**Comment by roblourens** [comment]
Can you be more specific about what you want to see in vscode?

**Comment by TheEagle82** [comment]
This is what I see in Visual Studio, the “Search Solution Explorer” which lets you search directly the files in your solution:

[cid:image001.png@01D4290D.3FB77B90]

**Comment by roblourens** [comment]
You can use cmd+p for a similar feature, or we have this feature request for searching directly in the explorer:

https://github.com/Microsoft/vscode/issues/10026
