### ISSUE TITLE
No scroll bar in the vscode integrated terminal

### ISSUE THREAD

**Issue by KnoxKnot** [Microsoft/vscode#54783]
- VSCode Version: 1.25.1
- OS Version: Windows 10

Steps to Reproduce:

1. Just updated the vscode and installed anaconda 5.2 with the integrated vscode

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
