### ISSUE TITLE
teminal width

### ISSUE THREAD

**Issue by hosseinse1919** [Microsoft/vscode#54782]
i set my bar on right (explorer and ...)
and teminal is come over it and  cover my explorer

**Comment by hosseinse1919** [comment]
![image](https://user-images.githubusercontent.com/39802485/43032213-07e2d372-8cc7-11e8-88f8-127587ad1ef1.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/54230
