### ISSUE TITLE
Automatic comment-block ending

### ISSUE THREAD

**Issue by ImmortaleVBR** [microsoft/vscode#54793]
Visual Studio Code lacks support for automatic comment-block ending in C and C++.

If you were to start a comment-block with `/*`, an automatic `*/` will not be added as it would be in the traditional Visual Studio. When I type `/*`, it should automatically be turned into `/**/` and the text cursor should be between the two `*`.

It isn't that big of a deal but it would be really nice to have this feature in Visual Studio Code.

**Comment by andrew-r-king** [comment]
Workaround:
https://github.com/microsoft/vscode/issues/77008#issuecomment-509765216

**Comment by hpg-mheck** [comment]
Ugh.  I currently have the exact OPPOSITE problem: I want to DISABLE this feature.  This is happening for me and I can't figure out how to turn it OFF.

**Comment by alexandrudima** [comment]
Let's track in #38352
