### ISSUE TITLE
tsconfig.json path aliases are not included in auto import paths

### ISSUE THREAD

**Issue by eodrap** [Microsoft/vscode#54798]
VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.6.0
TypeScript version: 2.9.2
Does this issue occur when all extensions are disabled?: Yes

Steps to reproduce -

1. Define path alias in `tsconfig.json` -
```
    "baseUrl": "./",
    "paths": {
      "@root/*": ["*"]
    },
```
2. Restart VS Code
3. Trigger auto import by typing a module name and selecting the, 'Auto import from ...' menu entry
4. The auto import path offered does *not* include the alias, a relative path is inserted -
Module path `x/y/z/module.ts`
Expected path `@root/x/y/z/module.ts`
Inserted path `x/y/z/module.ts`

Omitting the alias is causing module not found errors.

#39459 suggests this has been resolved but I cannot find a way to include the alias path prefix in auto import suggestions. I've tried setting `typescript.preferences.importModuleSpecifier = 'non-relative'`. Apologies if I'm missing a required preference or doing something silly.

**Comment by eodrap** [comment]
Not a duplicate of #54513.

**Comment by eodrap** [comment]
Thanks for replying, yes it does. Clean installation & profile of VS Code Insiders, no installed extensions, and auto import paths do not include the configured alias. The alias is understood if added manually to import paths.

VS Code version: Code - Insiders 1.26.0-insider (26e5a55cd8452477bfb7a472ea9475761600adf0, 2018-07-20T05:11:33.977Z)
OS version: Darwin x64 17.6.0

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#25876
