### ISSUE TITLE
Character keys not captured in shortcut combination "Ctrl+K,*"

### ISSUE THREAD

**Issue by H1MSK** [microsoft/vscode#54794]
Issue Type: <b>Bug</b>

1. open a file(I just tested .md files)
2. press Ctrl+K
3. then you can input alphabets into your file although the shortcut is still waiting for next key :(

It seems that the priority of directly-inputed keys are messed, though other keys like backspaces are still captured.

This system was installed not long before and doesn't have many softwares installed, and all the softwares (and a lot more) were also installed when I was using 16.04, so it might not be a software-wide conflict.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:40:20.190Z)
OS version: Linux x64 4.15.0-23-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|7.70GB (0.27GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by alexdima** [comment]
This works as designed. `Ctrl+K, a` is not a keybinding, so the `a` after `Ctrl+K` gets typed in the editor. If you were to bind a keybinding to `Ctrl+K, a`, then `a` would not be typed in the editor.

(the majority of our default keybindings use `Ctrl+K, Ctrl+A`, so the Ctrl modifier is expected to be pressed for the second part of the chord as well).
