### ISSUE TITLE
inpossible to use Code because of very high cpu usage.

### ISSUE THREAD

**Issue by jens1o** [Microsoft/vscode#54795]
It's even worse. One process will continue doing nothing but causing high cpu even after closing the window.

- VSCode Version: <code>Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)</code>
- OS Version: <code>Windows_NT x64 10.0.17134</code>
- CPUs: <code>Intel(R) Pentium(R) CPU B960 @ 2.20GHz (2 x 2195)</code>
- Memory (System): <code>7.88GB (4.71GB free)</code>
- Memory (Process): <code>231.85MB working set (284.09MB peak, 217.14MB private, 37.65MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|156|
|main|app.isReady => window.loadUrl()|2625|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|2795|
|renderer|require(workbench.main.js)|17292|
|renderer|create extension host => extensions onReady()|10557|
|renderer|restore viewlet|341|
|renderer|restore editor view state|4077|
|renderer|overall workbench load|7191|
|main + renderer|start => extensions ready|35783|
|main + renderer|start => workbench ready|32187|

---
[933b-main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/2216283/933b-main.cpuprofile.txt)
[933b-renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/2216284/933b-renderer.cpuprofile.txt)
[933b-exthost.cpuprofile.txt](https://github.com/Microsoft/vscode/files/2216285/933b-exthost.cpuprofile.txt)

**Comment by donacellos** [comment]
I have the same problem on macOS.

**Comment by jens1o** [comment]
It turns out to be this extension: https://github.com/wayou/vscode-todo-highlight/blob/b1d790463199b07a3ddd7094f6feebe579cc12cd/src/HighlightExtension.ts#L120-L123

**Comment by giulianozor** [comment]
Same issue here. VSC simply keeps hanging for 5 minutes, then works fine for 1 minute :(

**Comment by Leedehai** [comment]
Correct @jens1o Disabling that [todo hight extension](https://github.com/wayou/vscode-todo-highlight/blob/b1d790463199b07a3ddd7094f6feebe579cc12cd/src/HighlightExtension.ts#L120-L123) fixed my problem. Otherwise all the extensions and IntelliSense don't work for any files (HTML, C++, markdown), and the fan is high.

**Comment by jens1o** [comment]
cc @wayou

**Comment by alexandrudima** [comment]
:+1: @jens1o for figuring it out!

There is not a lot we can do on our side, extensions are free to write any type of code (including code that causes a lot of CPU consumption).

Please contact the author of the extension and point out the problem with the extension.
