### ISSUE TITLE
F-String Method is not working

### ISSUE THREAD

**Issue by rohanbhandari94** [Microsoft/vscode#54791]
Issue Type: <b>Bug</b>

F-string method is producing an invalid syntax output.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-django|bat|0.15.0
vscode-eslint|dba|1.4.12
jupyter|don|1.1.4
python-extension-pack|don|1.2.0
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.34
code-runner|for|0.9.3
beautify|Hoo|1.3.2
MagicPython|mag|1.0.12
mssql|ms-|1.4.0
python|ms-|2018.7.0
vsliveshare|ms-|0.3.423
jinja|who|0.0.8

(2 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment]
@rohanbhandari94 Can you please explain in greater detail what the issue is? It would be preferable if you could include steps so we attempt to reproduce.

**Comment by JacobCallahan** [comment]
This is likely due to the version of python their pylint is aligned to.
@rohanbhandari94 can you paste the output of ```pylint --version```

**Comment by alexandrudima** [comment]
Closing for lack of feedback.
