### ISSUE TITLE
Git changes in explorer window, and cmd +d for diffs, just like webstorm

### ISSUE THREAD

**Issue by QuantumInformation** [Microsoft/vscode#54805]
This is a feature I use in webstorm more than anything, I really miss it in VScode. I find the inline working tree tabs for changes and switching to the source control tab inconvenient.

<img width="1136" alt="screen shot 2018-07-21 at 22 26 14" src="https://user-images.githubusercontent.com/216566/43040178-27478a3c-8d35-11e8-9047-237130ef32db.png">

**Comment by joaomoreno** [comment]
The explorer already supports change decorations. We also already have side-by-side diffing. Can you elaborate better, and in detail, what it is that you're missing?
