### ISSUE TITLE
Extra session - will not go away

### ISSUE THREAD

**Issue by jschank** [Microsoft/vscode#54807]
- VSCode Version: 1.25
- OS Version: MacOSX  10.13.6

Steps to Reproduce:

1. Open visual studio code. For example $ code --disable-extensions <somefile>
2. I get two vscode windows. The expected one, and an extra one with two files that are empty and have the name --waitMarkerFilePath.

I cannot make vscode launch without this extra session - even if I close those files with or without saving them

I even tried deleting vscode and reinstalling it.

Does this issue occur when all extensions are disabled?: Yes

![waitmarker](https://user-images.githubusercontent.com/30314/43040675-fafca1d2-8d17-11e8-8a6e-62b74795408f.png)

**Comment by jschank** [comment]
This *may* be related to lots of Code Helper processes being launched which eat up CPU. Hard to tell, since I can no longer launch without this extra session

**Comment by jschank** [comment]
I think this started when I ran visudo. And I my shell editor was set to use code

I use fish shell - so that is the syntax for setting an environment variable

```
set -gx EDITOR "/usr/local/bin/code -w -n"
set -gx VISUAL "/usr/local/bin/code -w -n"
```

**Comment by jschank** [comment]
I can't even imagine how this is possible.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
