### ISSUE TITLE
visual studio code giving me error?

### ISSUE THREAD

**Issue by cairotx** [Microsoft/vscode#54802]
![screen shot 2018-07-21 at 1 24 44 pm copy](https://user-images.githubusercontent.com/30858063/43039043-3b1ed254-8cea-11e8-9ee0-26195c922e04.png

I keep getting error message and dont understand why, even i save the file.

**Comment by mikecann** [comment]
I suspect that isnt to do with Code as is more to do with your node setup. Have you tried running from a Terminal external to Code?

What happens if you run `node app.js` ?
