### ISSUE TITLE
Drag folder to VS Code doesn't work when Running as Administrator

### ISSUE THREAD

**Issue by RJSeven** [Microsoft/vscode#54808]
Drag folder to VS Code doesn't work when Running as Administrator.
This happens in VS Code v1.25 and VS Code Insiders v1.26.

**Comment by ImmortaleVBR** [comment]
I can confirm that the report from @RJSeven is applicable for me as well.

I am running the latest official non-insider build (v1.25.1) and was able to reproduce the bug first-try; the bug does not exist whilst VS Code is running as standard rights, but will dismiss *any* folder drag-and-drop attempts if it is running elevated.
