### ISSUE TITLE
Replace call to process.getProcessMemoryInfo

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#54801]
`process.getProcessMemoryInfo` is being deprecated in Electron 3 and removed in 4, we're using it here only:

https://github.com/Microsoft/vscode/blob/04594c864be35281ff7eca15a6db2a5a735bb320/src/vs/workbench/services/timer/node/timerService.ts#L61

See https://github.com/electron/electron/projects/11#card-11509601

**Comment by bpasero** [comment]
This will not hit us until Electron 4, so I suggest we revisit this when Electron 4 is out with an alternative method to use.

**Comment by bpasero** [comment]
I will keep track of this when it happens.

**Comment by bpasero** [comment]
Related: https://github.com/electron/electron/issues/13447

**Comment by bpasero** [comment]
The API got replaced but is not as complete: https://github.com/electron/electron/issues/16712

**Comment by bpasero** [comment]
This is adopted.
