### ISSUE TITLE
 Cannot read property 'document' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#5480]
Issue Id: <b>b69492db-3cc4-2c53-d056-ead1327be4a4</b><br /><br />*Versions* <br />- 1.0.0-insider<br />-  fa6d0f03813dfb9df4589c30121e9fcffa8a8ec8<br />*Stack* <br />TypeError: Cannot read property 'document' of null<br />    at e.Object.defineProperty.get [as document] (\out\vs\workbench\node\pluginHostProcess.js:19:10563) <no sourcemaps><br />    at QuickInfo__handle_$ (\Ionide.Ionide-fsharp-1.6.0\fsharp.js:3185:34) <no sourcemaps><br />    at null._onTimeout (\Ionide.Ionide-fsharp-1.6.0\fsharp.js:3180:14) <no sourcemaps><br />    at Timer.listOnTimeout (timers.js:89:15)<br />

**Comment by dbaeumer** [comment]
This is a problem with the ionide fsharp extension.
