### ISSUE TITLE
Added tree items (expanded with children) aren't visible in the tree until children are enumerated

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#54806]
Issue Type: <b>Bug</b>

I am trying to add a new item to a tree that has children and should be expanded by default. If the tree item's `getChildren()` call returns a promise, it seems that the tree won't show the item until the promise resolves. I would expect the tree item to be added to the tree, with a spinner, and once the promise resolves the children will be shown. Basically identical to the behavior if the item was added collapsed and the user clicks the expand triangle.

I also tried first adding the item as collapsed and then after a short delay (`setImmediate`) setting `item.collapsibleState = TreeItemCollapsibleState.Expanded` which also doesn't seem to work.

//cc @sandy081 

VS Code version: Code - Insiders 1.26.0-insider (26e5a55cd8452477bfb7a472ea9475761600adf0, 2018-07-20T05:18:39.569Z)
OS version: Windows_NT x64 10.0.17713

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (14.64GB free)|
|Process Argv|C:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe C:\Users\Eric\code\vscode-gitlens|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by sandy081** [comment]
Will investigate in August

**Comment by sandy081** [comment]
@eamodio What is the difference when you set the collapsible state of the item to expanded in the beginning. This will expand the element right?

**Comment by eamodio** [comment]
If I set it to `TreeItemCollapsibleState.Expanded` it will expand the element, but the element won't show up at all until the promise for `getChildren` resolves. So if you are adding an item with lots of children or children that will take a while to load, a user can't even see that item until all the children are ready.

In my case I was trying to add commit search results to GitLens' Results explorer, and I would like the search item to show up immediately and show a loading spinner while the children are loading, and then expand when the children are complete. Which is the same behavior that is seen by a user, if I add the item collapsed, and the user clicks to expand the item.

**Comment by sandy081** [comment]
Sorry, this is a limitation from our internal Tree implementation. Will be considered for our new internal Tree from @joaomoreno
