### ISSUE TITLE
Set up to all computers synchronously according to the account number！

### ISSUE THREAD

**Issue by SciRui** [Microsoft/vscode#54817]
Issue Type: <b>Feature Request</b>

I want to be able, like the edge browser, based on the accounts that are landed in the VS Code, and then synchronize the settings (including the installed plug-ins, some configurations, such as fonts, topics, etc.) to the VS Code on all computers!

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

**Comment by shanalikhan** [comment]
Try settings sync extension
