### ISSUE TITLE
over 100% CPU, even after quitting (Code Helper)

### ISSUE THREAD

**Issue by huafu** [Microsoft/vscode#54814]
Issue Type: <b>Performance Issue</b>

Badly this is random, and while for the same project(s) open it could be working fine, another start VSCode suddenly uses over 100% CPU even before I start using it.

Tho one thing that remains the same is, when that issue happen and **I close VSCode**, 4 or more `Code Helper` processes keep running forever at +100% in the background and I have to kill them.

I know some other issues have been opened like this one, but the only one still open was asking to report the bug using the `Help` `Report Issue` so here it is.

Also here are the processes that keep running after I close VSCode when my issue hapen:
```
❯ ps aux | grep -i 'Visual Studio Code.app'
huafu             2222  93.9  2.1  5133144 176060   ??  R     7:38AM   3:10.22 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=extensionHost
huafu             1776  92.8  0.8  5189252  66200   ??  R     7:09AM  24:33.56 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=extensionHost
huafu             1819  92.4  0.7  5132796  59688   ??  R     7:09AM  24:09.17 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=extensionHost
huafu             1780   0.0  0.3  5011088  23992   ??  S     7:09AM   0:00.29 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=searchService
huafu             1775   0.0  0.1  4307360   8320   ??  S     7:09AM   0:00.04 /Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Resources/crashpad_handler --no-rate-limit --no-upload-gzip --database=/var/folders/dr/dyg3_v313zjfpq82wd_4b0lr0000gn/T/VSCode Crashes --metrics-dir=/var/folders/dr/dyg3_v313zjfpq82wd_4b0lr0000gn/T/VSCode Crashes --url=https://rink.hockeyapp.net/api/2/apps/21a48a66799e47fea4f52c0ff81e803d/crashes/upload --handshake-fd=60
```

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 5, 5|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   22	   115	  2325	code main
    4	   139	  2326	   gpu-process
    0	   451	  2327	   window (get-typescript-config.ts — ts-jest)
    0	    33	  2349	     terminal
    0	     0	  2350	       /usr/local/bin/fish -l
   82	   172	  2373	     extensionHost
    0	     0	  2377	       (git)
    0	     0	  2378	       (git)
    0	     0	  2380	       (which)
    0	     0	  2381	       (which)
    0	    33	  2382	       electron_node electronForkStart.js tsserver.js 
    0	    49	  2374	     watcherService
    0	    98	  2370	   shared-process
   11	    98	  2379	   window (Issue Reporter)
    7	     0	  2383	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (get-typescript-config.ts — ts-jest)
|    Folder (ts-jest): 232 files
|      File types: ts(112) json(75) js(13) gitignore(10) babelrc(4) snap(4)
|                  md(3) tsx(2) yml(2) DS_Store(1)
|      Conf files: package.json(30) tsconfig.json(30) tslint.json(1)
|                  launch.json(1) settings.json(1)
|      Launch Configs: node;
```

</details>
<details><summary>Extensions (58)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
EditorConfig|Edi|0.12.4
json-to-ts|Mar|1.5.5
vscode-jest|Ort|2.8.0
vscode-docker|Pet|0.0.27
ejs-language-support|Qas|0.0.1
html-css-class-completion|Zig|1.17.1
Bookmarks|ale|9.0.0
vscode-color|ans|0.4.5
markdown-preview-github-styles|bie|0.1.2
vscode-yarn-script|car|0.0.1
gitignore|cod|0.5.0
snippetier|daf|0.1.0
vue-peek|dar|1.0.2
vscode-quick-select|dba|0.2.5
vscode-dash|dee|1.10.0
Vue2|duc|0.1.3
gitlens|eam|8.5.2
ts-tslint|eg2|0.0.7
LogFileHighlighter|emi|2.4.0
vsc-material-theme|Equ|2.3.0
prettier-vscode|esb|1.5.0
gitlab-workflow|fat|0.6.0
code-runner|for|0.9.3
shell-format|fox|1.1.3
vscode-yarn|gam|1.6.0
icon-fonts|idl|2.1.0
path-autocomplete|ion|1.12.0
plantuml|jeb|2.8.3
theme-karyfoundation-themes|kar|18.0.1
vscode-gist|ken|1.2.1
Lua|key|0.0.9
vscode-gutter-preview|kis|0.12.2
vscode-commitizen|Kni|0.5.0
vscode-github|Kni|0.30.0
javascript-test-runner|leg|0.2.0
vue|liu|0.1.5
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
debugger-for-chrome|msj|4.8.0
vscode-gitignore-generator|pio|1.0.1
material-icon-theme|PKi|3.5.2
typescript-mono-repo-import-helper|q|0.0.6
seti-icons|qin|0.1.3
vscode-coverage-gutters|rya|2.0.1
partial-diff|ryu|1.2.0
code-settings-sync|Sha|3.0.0
language-stylus|sys|1.9.2
json-schema-validator|tbe|0.1.0
ayu|tea|0.14.0
vscode-gitmoji-snippets|thi|3.2.0
stylus-supremacy|thi|2.12.0
json2yaml|tux|0.2.0
gitflow|vec|1.2.1
stylint|vtf|0.0.2
vscode-todo-highlight|way|1.0.3
markdown-all-in-one|yzh|1.6.0
tslint-snippets|zuo|1.1.0

(4 theme extensions excluded)

</details>

**Comment by huafu** [comment]
...now it's stuck all the time when I open one project. I can type code, but most of my extensions are not loaded, and when I go to the SCM pane it shows "There are no active source control provider" 😧

**Comment by ayyash** [comment]
I would like to add my note, my vscode stops typescript intellesense and takes 100% CPU, unless I disable ALL extensions, I tried to enable just one to test: TODO Highlight, and it went crazy again.

**Comment by ayyash** [comment]
yes, I don't what the odds are, but I happened to disable the one extension that was causing the trouble! This one and scss-scan caused the trouble, my guess is they do some sort of "file scanning" and it takes forever (node_modules is excluded but it doesn't seem to honer that)

**Comment by superheri** [comment]
I have the same problem on my side and Git is not working as it should be...

**Comment by qdechochen** [comment]
same here, and I disabled all extensions, still > 90%, and always > 90%.

**Comment by aa7955** [comment]
Same issue running Python. I had 99.8%.

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
