### ISSUE TITLE
Very high CPU usage Code Helper processes (100%+) suddenly showing up on startup

### ISSUE THREAD

**Issue by jadchaar** [Microsoft/vscode#54813]
Issue Type: <b>Performance Issue</b>

Occurs on startup or window reload. Causes my CPU temp to reach 70C+ and the fans to ramp up big time.

I have found that going to activity monitor and forcing the Code Helper processes to quit then results in a single 100% CPU usage process (**_still an issue_**), but at least my fans don't blow like crazy (but the temps are still in mid to high 60C).

Complete clean install (removing VSCode from Applications folder and removing the directories here listed in [this article](https://stackoverflow.com/questions/42603103/how-to-completely-uninstall-vscode-on-mac)) did not fix this issue. 

Note: I am working with a Go project and it seems that Go auto-formatting and Go intellisense are gone after force quitting the high CPU Code Helpers. So that makes me think I ended the Go extensions process. This seems to be super relevant: https://github.com/Microsoft/vscode-go/issues/1775.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|8.00GB (0.71GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   26	   115	  2099	code main
    4	    90	  2100	   gpu-process
    1	    98	  2127	   shared-process
    7	   254	  2151	   window (ItunesLookup.go — itunes-icons)
   92	   123	  2152	     extensionHost
    0	     0	  2173	       (go)
    0	     0	  2174	       (git)
    0	     0	  2175	       (git)
    0	     0	  2176	       (git)
    0	    49	  2153	     watcherService
    0	    41	  2155	     searchService
   85	    90	  2182	   window (Issue Reporter)
    0	     0	  2183	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (ItunesLookup.go — itunes-icons)
|    Folder (itunes-icons): 6 files
|      File types: DS_Store(3) go(2) gitignore(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-javascript-snippet-pack|aka|0.1.5
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.18.0
vscode-eslint|dba|1.4.12
githistory|don|0.4.2
gitlens|eam|8.5.2
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.34
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.3.0
auto-close-tag|for|0.5.6
code-runner|for|0.9.3
beautify|Hoo|1.3.2
vscode-scss|mrm|0.6.2
python|ms-|2018.7.0
cpptools|ms-|0.17.7
Go|ms-|0.6.84
vscode-docker|Pet|0.0.27
tsimporter|pmn|1.2.14
typescript-hero|rbb|2.3.2
sass-indented|rob|1.4.9
gitblame|wad|2.4.2
vscode-todo-highlight|way|1.0.3
JavaScriptSnippets|xab|1.7.0
markdown-all-in-one|yzh|1.6.0

</details>

**Comment by ramya-rao-a** [comment]
@jadchaar The linked issue from the Go extension is specifically about linters being the cause of the perf issue. If you believe that indeed is the cause, then please follow the solution in that same issue and let us know if that solves your problem.

Since you have a whole lot of other extensions, also follow https://github.com/Microsoft/vscode/wiki/Performance-Issues#visual-studio-code-is-consuming-a-lot-of-cpu to see if they give you any more ideas on what might be causing this.

**Comment by jadchaar** [comment]
Hi @ramya-rao-a, thanks for the follow up.

I am unable to consistently reproduce this 100% CPU usage after clearing my NVRAM a day ago (to try and fix another issue I was having with my system). I was able to get the issue to reproduce on every startup and reload (even with extensions disabled), and even after restarting my computer. But it is gone as of today. So I guess I will report back if it occurs again. Man that is odd, it suddenly goes away right when we start to dig deeper haha

**Comment by ramya-rao-a** [comment]
:) No problem. Feel free to log an issue if this occurs again.
Happy Coding!
