### ISSUE TITLE
Pin group: make editor always opened in the specific group.

### ISSUE THREAD

**Issue by V0idk** [Microsoft/vscode#54815]

**Comment by bpasero** [comment]
@V0idk can you explain with more text what you want?

**Comment by V0idk** [comment]
![image](https://user-images.githubusercontent.com/17514799/43755124-0f88aa5c-9a41-11e8-808d-f234c98b0796.png)
@bpasero

**Comment by V0idk** [comment]
![peek 2018-08-07 12-54](https://user-images.githubusercontent.com/17514799/43755147-2a6ceb12-9a41-11e8-9016-f2519a491519.gif)
@bpasero
