### ISSUE TITLE
checked 'Keep Open'

### ISSUE THREAD

**Issue by SchoolforDesign** [Microsoft/vscode#54811]
Issue Type: <b>Feature Request</b>

Could you please, add a check mark to 'Keep Open' at the opened tab, please. because we don't know which tab keep or not. thanks.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/46807
