### ISSUE TITLE
Support English locales like en-gb, en-au

### ISSUE THREAD

**Issue by MemeBeast** [Microsoft/vscode#54819]
Since US english is different from AUS please add a native language pack for this.
Like i. Color is spelled wrong in AUS.

**Comment by mjcheetham** [comment]
@MemeBeast I've started an en-GB language pack (#35690 - the language is now available on VSCode's Transifex project accepting translations) which although not 100% Australian, I believe we use the same spellings for colour/flavour/centre etc?

There however seems to be a problem (as referenced: Microsoft/vscode-loc#34) in that VSCode is ignoring any `en-*` language packs and just falling back to `en-US` :cry:

**Comment by ramya-rao-a** [comment]
From https://github.com/Microsoft/vscode-loc/issues/34#issuecomment-412046890 by @mjcheetham 

@ramya-rao-a, as linked on my original request (Microsoft/vscode#35690) and the new request for an en-AU language pack (Microsoft/vscode#54819), there are a number of differences in spelling and grammar between en-US (the Code default/fallback language) and en-GB/AU.

Many English speakers in Europe are also familiar with the 'British' spellings (and I believe British English is used for official translations in the EU too).

Given the large population of speakers who are familiar with this English variant I would expect en-* languages to be supported in Code. Both the "traditional" and "simplied" variants of Chinese are supported, and I believe (based on the lack of special treatment of `pr-*` languages in Code) that a European Portugese (pr-PT) language pack would work fine alongside the already existing Brazillian Portuguese (pr-BR) language pack.

I don't think it'd be fair to arbitrarily restrict language pack availablity to only one variant of each language.

**Comment by MemeBeast** [comment]
Thanks a ton!

**Comment by dbaeumer** [comment]
Fixed. This was only a short cut to not scan for language files if en was requested. Now only omitting the scanning for en or en-US. en-gb,... will now scan for available translations.

**Comment by danyeh** [comment]
@mjcheetham @MemeBeast , en-GB language pack published. Could you please give a try? Thanks!
https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-en-GB
