### ISSUE TITLE
New Workbench Menu does not respect Alt+<Key> hotkeys on Windows.

### ISSUE THREAD

**Issue by JeffHanna** [Microsoft/vscode#54822]
- VSCode Version: 1.26.0-Insider
- OS Version: Windows 10 Pro (Insider) - 17713.rs5_release.180706-1551

This bug only occurs with the setting window.titleBarStyle: custom. When using the original style menus, in VS Code and VS Code (Insiders), the Alt hotkeys work as expected.

Steps to Reproduce:
1. Enable the new menu bar
2. Press Alt+F to open the File menu
3 Press S to save
3. While the File menu does appear and the various menu entries show underscores under their Alt hotkey activators, the save never occurs and the menu does not close. This happens for every Alt hotkey I've tried.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
@JeffHanna currently, you must still hold alt for the second action. i.e. Alt+F, Alt+S. However, specifically for that key combination, there is a conflict that needs resolution #52935
