### ISSUE TITLE
after renaming a file changing only the case, both appear in search

### ISSUE THREAD

**Issue by lepistone** [Microsoft/vscode#54820]
Issue Type: <b>Bug</b>

I renamed a filename to change the case, from `SimpleJson.hs` to `SimpleJSON.hs`. I checked in the terminal and the old `SimpleJson.hs` file is gone as expected. Then I hit ⌘P for fuzzy search.

**Actual result**: both `SimpleJson.hs` and `SimpleJSON.hs` show up, both can be edited and changes are saved in the only file that exists: `SimpleJSON.hs`.

**Expected result**: only the new file shows up in the search.

Thank you!

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) M-5Y31 CPU @ 0.90GHz (4 x 1100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (0.99GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-hie-server|ala|0.0.20
language-haskell|jus|2.5.0
vim|vsc|0.15.3

</details>

**Comment by lepistone** [comment]
No bot, this is not about the integrated terminal.

**Comment by roblourens** [comment]
How did you rename it, in vscode or externally?

Is the file open in a tab when you do the search?

**Comment by lepistone** [comment]
Thanks @roblourens! I can reproduce both renaming with `mv` in the terminal or in vscode. I can reproduce the search both with tab open and closed.
<img width="739" alt="screen shot 2018-07-26 at 22 34 47" src="https://user-images.githubusercontent.com/1314778/43287060-27e8285a-9124-11e8-9e25-0db60dbf5656.png">

**Comment by roblourens** [comment]
Oh right, that falls under https://github.com/Microsoft/vscode/issues/12448. There are a bunch of issues with path case-sensitivity.
