### ISSUE TITLE
How to know either Code is running as portable mode via code api or env. variable

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#54824]
I know to get the code exe path via api
I need to know the following things:
1. Any flag or identifier that shows code is running as portable Mode
2. The data files folder and extensions folder either by process variable or API

**Comment by jrieken** [comment]
> The data files folder and extensions folder either by process variable or API

that is #2741

> Any flag or identifier that shows code is running as portable Mode

Why would an extension need to know? I wouldn't like extensions doing thing different just because VS Code comes as portable mode

**Comment by shanalikhan** [comment]
Settings Sync needs to know either the code is running as portable mode. If its running as portable mode extension needs to look for the user specified folders ( #2741 )

**Comment by joaomoreno** [comment]
Actually, you need the user data and extensions directory paths, not the notion of whether Code is portable or otherwise. Similar to https://github.com/Microsoft/vscode/issues/54345#issuecomment-405302919

Closing it given that #2741 is the right way to go.
