### ISSUE TITLE
Settings is null in configuration change event

### ISSUE THREAD

**Issue by tempit** [Microsoft/vscode#54821]
I registered a configuration setting from my extension, but when receiving a call to connection.onDidChangeConfiguration the notification comes with null settings. 

If I run connection.workspace.getConfiguration for my language, I see the new config. 
Shouldn't the new configuration (or the delta) be in the settings? It seems to imply so in the documentation. Or do I need to re-read the config after every changeConfiguration event?

VSCode Version: 1.25.1
OS Version: Ubuntu 16.04
Reproduces w/o extensions: N/A

**Comment by sandy081** [comment]
@tempit the event should have `ConfigurationChangeEvent` object from which you can check if your configuration has changed or not.

Are you sure you are getting `null` ? If so, please provide steps to reproduce?

**Comment by tempit** [comment]
@sandy081 I'm using connection.onDidChangeConfiguration, which expects a DidChangeConfigurationParams, which should have a 'settings' field. The event arrives, but the settings field is null (pic below).
As to reproduction, I'm not clear on what to provide, other than a link to the repo ([here](https://github.com/wix/stylable-intelligence)). What I do is launch the extension, open the settings file, and change a setting. 
![image](https://user-images.githubusercontent.com/1898725/43147080-da54f61e-8f6a-11e8-9ad2-de2380ac9394.png)

**Comment by sandy081** [comment]
@tempit Do you mean the `change` object does not has `settings` field?

**Comment by tempit** [comment]
@sandy081 Yup. Or rather, the value of the field is null.

**Comment by sandy081** [comment]
@tempit Change object is of type

```ts
export interface ConfigurationChangeEvent {

	/**
	 * Returns `true` if the given section for the given resource (if provided) is affected.
	 *
	 * @param section Configuration name, supports _dotted_ names.
	 * @param resource A resource Uri.
	 * @return `true` if the given section for the given resource (if provided) is affected.
	 */
	affectsConfiguration(section: string, resource?: Uri): boolean;
}
```

If you want the configuration value, you can get the configuration again using

`vscode.workspace.getConfiguration()`

I understand getting the value from the change event is easy and quick. But letting you know you can also get it like above.

Fine to make it a feature request or close it if you are ok with above.

**Comment by tempit** [comment]
@sandy081 , again, I'm not sure we're talking about the same thing. This is what I'm using:
```js
//From main.d.ts in vscode-languageserver
     * Installs a handler for the `DidChangeConfiguration` notification.
     *
     * @param handler The corresponding handler.
     */
    onDidChangeConfiguration(handler: NotificationHandler<DidChangeConfigurationParams>): void;
```
```js
//From protocol.d.ts in vscode-languageserver-protocol
export interface DidChangeConfigurationParams {
    /**
     * The actual changed settings
     */
    settings: any;
}
```
I searched the entire project for ConfigurationChangeEvent and couldn't find it. Am I using an outdated version? 
In any case, I've already got it working by re-reading the config after each event, it's just that the jsdocs seem to imply I should be able to just get the settings from the event.

**Comment by sandy081** [comment]
Ah I see it now. This `main.d.ts` is from `vscode-languageserver` and I got confused with the official extension api `vscode.d.ts`.

`vscode-languageserver` is a separate project which language extensions can use.

Here we only track issues of VS Code core which includes vscode extension api.

So, I am forwarding your issue https://github.com/Microsoft/vscode-languageserver-node/issues/380
