### ISSUE TITLE
Allow to launch VSCode from the debug view when running in portable mode

### ISSUE THREAD

**Issue by segevfiner** [microsoft/vscode#54828]
- VSCode Version: 1.25.1
- OS Version: Windows 10.0.17134.165 x64

Steps to Reproduce:
1. Run a [Portable VS Code](https://code.visualstudio.com/docs/editor/portable) instance.
2. Launch a development VS Code from a VS Code Git clone using the "Launch VS Code" launch configuration.
3. The newly launched instance uses the same paths as the running one for data and extensions.

This is probably the `VSCODE_PORTABLE` environment variable leaking to the launched VS Code. Maybe it should be wiped when launching a task? or maybe somewhere else in the launch process of an in-development VS Code...

Does this issue occur when all extensions are disabled?: Yes

**EDIT:** I think this also applies to `VSCODE_LOGS`.

**Comment by segevfiner** [comment]
https://github.com/Microsoft/vscode/blob/4986a04100c90188a367d92eaacfa0b9a2748a62/src/vs/workbench/parts/terminal/node/terminalEnvironment.ts#L54-L83

Maybe this should be extracted and reused for running tasks, debug processes and what not...?

**Comment by bpasero** [comment]
@segevfiner to clarify you are not working on an extension but actually on VSCode itself?

**Comment by segevfiner** [comment]
> @segevfiner to clarify you are not working on an extension but actually on VSCode itself?
Yes. This was while I tried to work on VS Code itself.

But unless there is a dedicated workaround somewhere in the code. I think you might get similar behavior while developing an extension in the extension development host. Since it is launched similarly from a launch configuration.

**Comment by bpasero** [comment]
@segevfiner for an extension this is actually desired, the window that opens is literally the same instance and not a new instance.

**Comment by segevfiner** [comment]
You're right. But those environment variables probably don't matter for
extension development, since VS Code is going to start the extension
development host window via IPC to the main process anyhow. At least that's
what I think is happening...

בתאריך יום ד׳, 8 באוג׳ 2018, 9:10, מאת Benjamin Pasero ‏<
notifications@github.com>:
