### ISSUE TITLE
Searching in empty workspace never completes

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#54835]
- Open empty window
- Ensure `"searchRipgrep.enable": false`
- Do a text search
- See progress bar forever

This comes from switching PPromise to an Event in search IPC. In this case, the search promise resolves immediately, so we should use `onFirstListenerDidAdd` instead of `onFirstListenerAdd`. FYI @joaomoreno

**Comment by joaomoreno** [comment]
Great catch and awesome fix! :+1:
