### ISSUE TITLE
打开多文件，头部提示问题

### ISSUE THREAD

**Issue by daibin91** [Microsoft/vscode#54848]
Issue Type: <b>Feature Request</b>

在打开多文件的时候，编辑区域头部只有一个文件显示，且没有关闭按钮
![image](https://user-images.githubusercontent.com/18304670/43065058-3e56c6de-8e93-11e8-9244-fd9a32bd9135.png)

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.7.0

**Comment by alexandrudima** [comment]
Please open the issue again and use English.

I think you should review your user settings `"workbench.editor.showTabs"`.

**Comment by daibin91** [comment]
is ok, thanks!
