### ISSUE TITLE
Python AutoComplete is very very slow with tensorflow

### ISSUE THREAD

**Issue by coder3101** [Microsoft/vscode#54842]
- VSCode Version: 1.25.1
- OS Version: Ubuntu 18.04 LTS

Steps to Reproduce:

1. Install Python Extensions and Enable PyLint
2. Import tensorflow and watch the autocomplete delay

Does this issue occur when all extensions are disabled?: No

1. import tensorflow as tf
2. tf.<CTRL + SPACE>

Line 2 Above takes over 3-5 seconds to show the modules under tf. Same is true for any other module like numpy (relatively less time in this case). Also, I found that there is no caching if in the very 10th line i again do tf.<CTRL + SPACE>, it takes the same amount of time.

**Comment by alexandrudima** [comment]
Can you please open an issue directly against the Python extension, at https://github.com/Microsoft/vscode-python/issues
