### ISSUE TITLE
search is not working properly

### ISSUE THREAD

**Issue by sojan-spark** [Microsoft/vscode#54843]
Issue Type: <b>Bug</b>

search is not looking up all files, results are pretty broken after the last couple of updates

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:40:20.190Z)
OS version: Linux x64 4.15.0-24-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Athlon(tm) II X2 260 Processor (2 x 1900)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Load (avg)|1, 1, 1|
|Memory (System)|5.57GB (0.13GB free)|
|Process Argv|/usr/share/code/code .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.15.0
django-html|bib|1.2.0
django-snippets|bib|1.1.0
django|big|1.0.0
vscode-intelephense-client|bme|0.8.8
vscode-importmagic|bra|0.0.6
angular2-snippets|dan|1.0.19
dart-code|Dar|2.16.0
flutter|Dar|2.16.0
jupyter|don|1.1.4
python-extension-pack|don|1.2.0
php-debug|fel|1.12.3
MagicPython|mag|1.0.12
php-namespace-resolver|Meh|1.1.0
mssql|ms-|1.4.0
python|ms-|2018.7.0
vsliveshare|ms-|0.3.423
jinja|who|0.0.8

</details>

**Comment by roblourens** [comment]
Please see the troubleshooting tips here: https://github.com/Microsoft/vscode/wiki/Search-Issues#missing-search-results
