### ISSUE TITLE
Git confirm box looks strange.

### ISSUE THREAD

**Issue by zhaolc90** [Microsoft/vscode#54847]
- VSCode Version: 1.25.1 win64
- OS Version: win 7 Enterprise SP1

Steps to Reproduce:

1.git 2.14.1.windows.1
![image](https://user-images.githubusercontent.com/28498664/43064411-67483e76-8e91-11e8-9e71-5e683063a950.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by oriash93** [comment]
code pointer:

https://github.com/Microsoft/vscode/blob/11567e39f5bd9a56685bd72703043b511bc546f4/extensions/git/src/commands.ts#L987-L991

**Comment by joaomoreno** [comment]
@zhaolc90 What is your exact VS Code version (commit id)?

**Comment by joaomoreno** [comment]
@zhaolc90 How do you update your Code?

**Comment by zhaolc90** [comment]
Download from vscode site zip, and unzip to old directory. 

Maybe old config files are the problem.
