### ISSUE TITLE
Writing a file on my split editor could not respond.

### ISSUE THREAD

**Issue by czfadmin** [Microsoft/vscode#54846]
Issue Type: <b>Bug</b>

Writing a file on my split editor could not respond.

In the following GIF image, the right side is opened first, and the content can be edited normally, but the right (post-opened) editor, I can't input it normally (can't input anything). 
And this problem I encountered in the previous version. I have been there a few times.
This problem was discovered by chance, but usually when I reopen the VSCode or reload this window, the problem will disappear.

![html](https://user-images.githubusercontent.com/13393959/43064279-0aac7b50-8e91-11e8-9e47-6f7f6161433e.gif)

VS Code version: Code - Insiders 1.26.0-insider (26e5a55cd8452477bfb7a472ea9475761600adf0, 2018-07-20T05:18:39.569Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.88GB (1.00GB free)|
|Process Argv|D:\Program Files\Microsoft VS Code Insiders\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|2.16.0
flutter|Dar|2.16.0
code-runner|for|0.9.3
vue-snippets|hol|0.1.8
Kotlin|mat|1.6.0
Angular-BeastCode|Mik|6.1.6
vscode-cosmosdb|ms-|0.8.0
vscode-language-pack-zh-hans|MS-|1.25.3
python|ms-|2018.7.0
vscode-ai|ms-|0.1.9
azure-account|ms-|0.4.2
cpptools|ms-|0.17.7
csharp|ms-|1.15.2
Go|ms-|0.6.84
js-atom-grammar|ms-|0.1.14
jscs|ms-|0.1.9
mono-debug|ms-|0.15.8
typescript-javascript-grammar|ms-|0.0.42
vetur|oct|0.12.5
java|red|0.28.0
vscode-yaml|red|0.0.13
rust|rus|0.4.9
vscode-arduino|vsc|0.2.18
vscode-java-debug|vsc|0.10.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.7.1
vscode-maven|vsc|0.9.2
JavaScriptSnippets|xab|1.7.0
html-css-class-completion|Zig|1.17.1

(1 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment]
Does this ever reproduce when running with `--disable-extensions`? Can you type in other places (like in a third side-by-side editor) when this happens? What are some steps which could help me try to reproduce?

**Comment by czfadmin** [comment]
This problem was discovered by chance. So I don't know if this problem will happen in the case of 
<code>-disable-extensions</code>. 
At the same time, I don't know how to reproduce the problem. I don't know if the problem is in the third side-by-side split editor.This problem sometimes happens on a single open editor.
In short, if I encounter this problem next time, I will notify you immediately.

**Comment by czfadmin** [comment]
@alexandrudima 
I have encountered this problem again today. In the third open editor, I can't edit the content either, but the first one can be edited normally. I tried it in the second (or the third editor). ) Open other files, and you can't edit the content normally.

See the screenshot below for details.

In the first GIF file, the leftmost editor can be used and ok can be entered normally, but nothing can be entered in the next few open ones.

![issues2](https://user-images.githubusercontent.com/13393959/43296032-723ad658-917b-11e8-869e-21c59852d5ad.gif)

After the overload window:

![issues3](https://user-images.githubusercontent.com/13393959/43296082-b40ea83e-917b-11e8-9c2b-0a92e5f317e9.gif)

**Comment by alexandrudima** [comment]
One possible explanation would be that one of your installed extensions is registering the `type` command (basically takes over typing in editors). The extension then passes back the text when the active text editor is the first one but not in other cases. I would review the extension list. From my glance over it, I am not aware of any of those extensions having known issues around typing.

I am sorry I don't know what could be wrong and the only way to figure this out is to have reproducible steps. Please keep an eye out and give us some steps. Next time this happens, you can also run F1 > Developer: Show running extensions to see which extensions are activated at the time. This might narrow down the list of the 29 extensions you have installed...

**Comment by czfadmin** [comment]
@alexandrudima 

Thank you. In the future, if this problem reappears, I will follow the requirements of you to check the problem.I will pay more attention and give you some more effective steps.

**Comment by alexandrudima** [comment]
@czfadmin If you find clear steps to reproduce please reopen or create a new issue.
