### ISSUE TITLE
'node' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by gL1TcHeD0uT** [Microsoft/vscode#54849]
version: 1.25

i was just trying to run a program and i got this error message
'node' is not recognized as an internal or external command,
operable program or batch file.
which is weird because the file 'node.dll' is present in the folder
help me pls

**Comment by gL1TcHeD0uT** [comment]
no it does not

**Comment by weinand** [comment]
having "node.dll" in a folder does not sound like a correctly installed Node.js.
Please install node.js correctly and verify that you can run it from a command prompt or form VS Code's integrated terminal.
