### ISSUE TITLE
Breadcrumbs not showing namespace

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#54855]
Issue Type: <b>Bug</b>

The cursor is in `window`, but that isn't shown in the breadcrumbs:
![image](https://user-images.githubusercontent.com/9205389/43067620-25c6943a-8e68-11e8-8dc1-08b17d538c85.png)

VS Code version: Code - Insiders 1.26.0-insider (26e5a55cd8452477bfb7a472ea9475761600adf0, 2018-07-20T05:11:33.977Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_65552|
|Screen Reader|no|
|VM|33%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
autofilename|Jer|0.1.3
regex|chr|0.2.0
ssh|chr|0.0.4
vscode-eslint|dba|1.4.12
Spot|der|0.4.0
ghlink|dt|1.0.2
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.34
rest-client|hum|0.19.0
vscode-azureappservice|ms-|0.9.0
vscode-azurefunctions|ms-|0.9.1
vscode-cosmosdb|ms-|0.8.0
azure-account|ms-|0.4.2
azurecli|ms-|0.4.2
github-issues-prs|ms-|0.9.0
PowerShell|ms-|1.8.1
debugger-for-chrome|msj|4.8.0
vscode-docker|Pet|0.0.27
vscode-versionlens|pfl|0.21.1
vscode-open-in-github|sys|1.7.0

</details>

**Comment by chrmarti** [comment]
Yes, on the second and later `namespace window` declarations in the proposed API. I hadn't noticed that was a necessary step before.

**Comment by jrieken** [comment]
Yeah, now I see it...

**Comment by jrieken** [comment]
This is actually an issue with TypeScript. The returned data contains window only once.

**Comment by mjbvz** [comment]
@jrieken Can TS provide multiple spans for a definition using `DocumentSymbol`? The hierarchy that TS hands is a logical one, not one based on the text structure of the file. That means there's one `window` result with all `window.*`  elements under it. Is that the expected design or should the outline we return match the structure of the text more closely?

**Comment by jrieken** [comment]
> should the outline we return match the structure of the text more closely?

That. One symbol has one location in our model
