### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#54852]
Electron update broke the build, this commit https://github.com/Microsoft/vscode/commit/a7095d7b6f18ae3e5fceae2a93f3729a391df96a 

Erros can be found here https://monacotools.visualstudio.com/Monaco/_build/results?buildId=40314 
Seems like for some reason he fails to download the node-debug / node debug-2 extension, even though there is nothing wrong with them.
Please note that building locally works for me, error only happens in the build agent.

fyi @weinand

**Comment by sandy081** [comment]
@Tyriar I have reverted the PR related to electron update so that we can have builds. - https://github.com/Microsoft/vscode/pull/54854

**Comment by sandy081** [comment]
Also just be aware to handle distro commit correctly. I see that the PR merged an old distro commit.

**Comment by sandy081** [comment]
After bit more investigation, it looks like the build is failing while downloading the Electron v2.0.5 from the repo. Looks like the repo does not has it hosted.

**Comment by Tyriar** [comment]
Thanks for reverting, closing this in favor of https://github.com/Microsoft/vscode/issues/45542 and https://github.com/Microsoft/vscode/pull/54873
