### ISSUE TITLE
DocumentSymbol.selectionRange doesn't seem to work

### ISSUE THREAD

**Issue by Gama11** [Microsoft/vscode#54857]
- VSCode Version: 1.25.1
- OS Version: Windows 10

The docs for `DocumentSymbol.selectionRange` state:

>The range that should be selected and reveal when this symbol is being picked, e.g the name of a function.

To me, this implies that picking a symbol from <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>O</kbd> selects this range (not sure what else it would be for, selecting something in the Outline view doesn't set a cursor selection / only navigates to the line).

Instead, the cursor is positioned at the start of `range` (in this example, the `selectionRange` covers `name`).

```ts
import * as vscode from "vscode";

export function activate(context: vscode.ExtensionContext) {
	vscode.languages.registerDocumentSymbolProvider('plaintext', {
		provideDocumentSymbols: (): vscode.DocumentSymbol[] => {
			return [new vscode.DocumentSymbol("name", "", vscode.SymbolKind.Variable,
                               new vscode.Range(0, 0, 1, 0), new vscode.Range(0, 4, 0, 8))];
		}
	});
}
```

![](https://i.imgur.com/ZZYONkA.gif)

I would expect the cursor to be positioned before `name`, and perhaps also select it. Originally brought this up in https://github.com/Microsoft/vscode-languageserver-node/issues/373#issuecomment-405749820.

**Comment by jrieken** [comment]
Yeah, we didn't adopt that for quick outline (yet) but only for the outline tree and the breadcrumbs

**Comment by jrieken** [comment]
Pushed a fix to use the `selectionRange` property. @Gama11 Tho be aware that the highlighting is always full lines, not columns, so that in your sample no change can be observed.

**Comment by jrieken** [comment]
Nevermind - pushed another change so that the `range` will be use for the (yellow) highlight and the `selectionRange` will be used for the revealing

**Comment by Gama11** [comment]
Thanks! I'll check it out in the next Insider's build that includes the changes.

**Comment by Gama11** [comment]
Thanks, now it's working as I'd expect. 👍 

One question: should doc comments before fields / types be included in `range`? Intuitively I'd say yes, since it makes sense that selecting e.g. a field's doc comment would highlight the corresponding symbol in the Outline view. However, TypeScript doesn't seem to do that (I often treat TS support as a sort of "reference implementation" for various language features and check how things are done there).

**Comment by jrieken** [comment]
> One question: should doc comments before fields / types be included in range? Intuitively I'd say yes, since it makes sense that selecting e.g. a field's doc comment would highlight the corresponding symbol in the Outline view.

Yeah, I'd also say yes.

**Comment by JacksonKearl** [comment]
@jrieken What is the desired behavior here? Not seeing any difference between range and selection range. In particular, not seeing the "yellow highlight".

**Comment by jrieken** [comment]
To verify

* have the extension snippet above
* open quick outline
* select the element and make sure the cursor is at line 1 column 5, not at 1,1
