### ISSUE TITLE
OutlineView to InheritationView javascript: Show class members from parents

### ISSUE THREAD

**Issue by dermoench42** [Microsoft/vscode#54850]
I'm working with classes in Javascript, precisely the class and extends keywords.
For me it seems to be very useful if the outline view would display, maybe configurable, all inherited members from parent classes. And also I'd like to see a hint on the 'overwrite' order of the inheritation tree.

e.g. given classes:

```
class plant {
  construktor(){}
  waterNeed(avgTemperature, avgHumidity){}
  sunshineNeed()
  liveOneDay(){}
}
class flower extends plant {
  constructor(){}
  sunshineNeed()
  liveOneDay(){}
}

class rose extends flower{
  constructor(){}
  attentionNeed(){}
  liveOneDay(){}
}
```
It would be nice if the outline of rose would show something like:

```
...
plant
  constructor flower:,plant:
  attentionNeed
  liveOneDay flower:, plant:
  from flower:
    sunshineNeed plant:
    from plant:
      waterNeed
...
```
... perfect with to possibility to navigate to the parentclass(function) by click.
maybe the nested depth should be configurable set to something like 3 or 5.

is that a good idea?

Happy coding!

ervin

**Comment by mjbvz** [comment]
Interesting proposal. The current outline view shows the hierarchy of the text document itself so showing more of a "logical" outline would be a change

**Comment by mjbvz** [comment]
@jrieken Interested to hear your thoughts about this. Should languages  return links to parent classes or other outside references in their document symbols?

**Comment by jrieken** [comment]
Unsure, it sounds like something special and like nothing other editors are doing or other users have asked for. You can always achieve this by implementing your own document symbol provider but making us do it (via options or something) is stretching it

**Comment by mjbvz** [comment]
Thanks @jrieken Closing this as our outline is currently designed to show the document structure and the parent class does not fit this
