### ISSUE TITLE
Import suggestion suggesting import from @types folder

### ISSUE THREAD

**Issue by flipchart** [Microsoft/vscode#54860]
- VSCode Version: 1.25.1
- OS Version: Windows 10 1803
- Typescript Version: 2.9.2

VSCode incorrectly suggests the location of the typescript definition file, rather than the actual module. Not limited to React module. React is installed (this is an existing project working fine). The file is a .tsx (typescript react) file. 

![image](https://user-images.githubusercontent.com/1951912/43075700-d3236f18-8e81-11e8-9d74-ca8ec430ab5b.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by flipchart** [comment]
No it doesn't.
