### ISSUE TITLE
 source: property 'sourceReference' is missing

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#5486]
Issue Id: <b>d5dcdace-c7a4-00bf-a1be-26363e63eb51</b><br /><br />*Versions* <br />- 1.0.0-insider<br />-  fa6d0f03813dfb9df4589c30121e9fcffa8a8ec8<br />-  67567498285c2081312077cc24370d97676fc20a<br />*Stack* <br />Error: source: property 'sourceReference' is missing<br />[/vs/workbench/parts/debug/node/rawDebugSession.ts#L79:29](https://github.com/microsoft/vscode/blob/c1d66b6e47c9da4c768ce7f216da14e7e4ac06ff/src/vs/workbench/parts/debug/node/rawDebugSession.ts#L79:29)<br />[/vs/base/common/winjs.base.raw.js#L1470:0 (onError)](https://github.com/microsoft/vscode/blob/c1d66b6e47c9da4c768ce7f216da14e7e4ac06ff/src/vs/base/common/winjs.base.raw.js#L1470:0 (onError))<br />[/vs/base/common/winjs.base.raw.js#L1176:0 (_notify)](https://github.com/microsoft/vscode/blob/c1d66b6e47c9da4c768ce7f216da14e7e4ac06ff/src/vs/base/common/winjs.base.raw.js#L1176:0 (_notify))<br />[/vs/base/common/winjs.base.raw.js#L1343:0 (enter)](https://github.com/microsoft/vscode/blob/c1d66b6e47c9da4c768ce7f216da14e7e4ac06ff/src/vs/base/common/winjs.base.raw.js#L1343:0 (enter))<br />[/vs/base/common/winjs.base.raw.js#L1316:0 (_run)](https://github.com/microsoft/vscode/blob/c1d66b6e47c9da4c768ce7f216da14e7e4ac06ff/src/vs/base/common/winjs.base.raw.js#L1316:0 (_run))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L79:5 (errorDispatch)](https://github.com/microsoft/vscode/blob/c1d66b6e47c9da4c768ce7f216da14e7e4ac06ff/src/vs/workbench/parts/debug/node/v8Protocol.ts#L79:5 (errorDispatch))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L147:5 (clb)](https://github.com/microsoft/vscode/blob/c1d66b6e47c9da4c768ce7f216da14e7e4ac06ff/src/vs/workbench/parts/debug/node/v8Protocol.ts#L147:5 (clb))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L114:11 (dispatch)](https://github.com/microsoft/vscode/blob/c1d66b6e47c9da4c768ce7f216da14e7e4ac06ff/src/vs/workbench/parts/debug/node/v8Protocol.ts#L114:11 (dispatch))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L69:8 (handleData)](https://github.com/microsoft/vscode/blob/c1d66b6e47c9da4c768ce7f216da14e7e4ac06ff/src/vs/workbench/parts/debug/node/v8Protocol.ts#L69:8 (handleData))<br />    at emitOne (events.js:77:13)<br />

**Comment by isidorn** [comment]
This should be fixed on latest alpha, @weinand filled a bug regarding this 2 weeks ago but I can not find it right now
