### ISSUE TITLE
definition javascript Object prompt error: [ts]  “;”

### ISSUE THREAD

**Issue by ganxunzou** [Microsoft/vscode#54868]
![2018-07-23_214556](https://user-images.githubusercontent.com/5092728/43080342-214230fe-8ec2-11e8-8412-51681bf37825.jpg)

![2018-07-23_215005](https://user-images.githubusercontent.com/5092728/43080487-6b86a064-8ec2-11e8-8e8f-7269eb7c6a63.jpg)

**Comment by ganxunzou** [comment]
![2018-07-23_215210](https://user-images.githubusercontent.com/5092728/43080629-aec10400-8ec2-11e8-85e7-4e38f56d06a1.jpg)

**Comment by ganxunzou** [comment]
set `"typescript.validate.enable": false` is Ok

**Comment by mjbvz** [comment]
Please share the text of the code along with all screenshots

**Comment by ehynds** [comment]
This is a duplicate of #54261

**Comment by mjbvz** [comment]
It is not

**Comment by ganxunzou** [comment]
sorry `"typescript.validate.enable": false` is not ok. 

this is ok:
```
const config = {
  "": ""
}
```

**Comment by mjbvz** [comment]
@ganxunzou Your first example is not a valid JavaScript file. The braces are interpreted as a block, not an object literal
