### ISSUE TITLE
Folder with Chinese path cannot import into workspace

### ISSUE THREAD

**Issue by shihehe73** [Microsoft/vscode#54870]
Issue Type: <b>Bug</b>

Path include Chinese such as "Google 雲端硬碟"、"學業", will cause error to import folder into workspace

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600 Six-Core Processor             (12 x 3194)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (8.62GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hant|MS-|1.25.5
cpptools|ms-|0.17.7
java|red|0.28.0
vscode-java-debug|vsc|0.10.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.7.1
vscode-maven|vsc|0.9.2

</details>

**Comment by Tyriar** [comment]
@shihehe73 do you mean you cannot open such a folder without it causing errors?

**Comment by shihehe73** [comment]
When I import the folder, it put the folder title into workspace with a exclamation mark beside it.
However, I try it on my laptop today, I can import the same folder...
I'll try again when I come home today. This is a bit weird.

**Comment by Tyriar** [comment]
Strange, let us know if you see it again.

**Comment by shihehe73** [comment]
![default](https://user-images.githubusercontent.com/15064645/43143720-070d7b86-8f8e-11e8-8710-21827e8291bd.png)
Error occurred like this.

After some trial and error, I found that if I import the folder(contains Chinese characters) alone, it appeared to be fine. But if I imported more than one folder to the workspace, than dragged the same folder in, the error occurred.

**Comment by isidorn** [comment]
@shihehe73 this works fine for me. Please let me know if you are doing something different than me.
If you can still reproduce please try it with latest vscode insiders https://code.visualstudio.com/insiders/

![chinese](https://user-images.githubusercontent.com/1926584/44408951-b3b20800-a561-11e8-9983-906fbd953c0d.gif)
