### ISSUE TITLE
Mac OS X "Invalid key shortcut terminal" on ⌃`

### ISSUE THREAD

**Issue by fanyinghao** [Microsoft/vscode#54872]
I want to open a terminal tab using the shortcut ⌃`, but it does not work correctly. Actually, it works sometime with tips on the [view] menu.

- VSCode Version: 1.25.1 
- OS Version: macos 10.13.6 

Steps to Reproduce:

1. select a folder
2. ⌃`
3. nothing happens

**Comment by Tyriar** [comment]
@fanyinghao does the shortcut say ^` in the View menu? What keyboard layout are you using?

**Comment by fanyinghao** [comment]
@Tyriar yes! can seeing **View** -> **Integrated Terminal[^`]** .
I am using Simplified Chinese. And you reminded me that I switch it to ABC then it works correctly. So I know how it happens but can we make it better?

**Comment by Tyriar** [comment]
@fanyinghao ah ok, this is as designed as I don't think we can intercept that keystroke from the IME handling it.
