### ISSUE TITLE
VS Code opens files from previous settings regardless of the restoreWindows setting

### ISSUE THREAD

**Issue by Dyoung0606** [Microsoft/vscode#54879]
- VSCode Version: 1.25.1
- OS Version :Microsoft Windows [Version 10.0.14393]

Steps to Reproduce:

1) From a command prompt, type "code (some folder)"
   (without the quotes)
2) Update user settings to include:
  "window.restoreWindows": "none"
3) Close VS Code
4) From a command prompt, type "code (that same folder)"
   (without the quotes)

Expected Result:
   VS Code launches with no files open in the editor tab

Actual Result:
  VS Code launches with all files opened that were opened in the previous session.

Does this issue occur when all extensions are disabled?: Yes

**Comment by kieferrm** [comment]
@Dyoung0606, you launch with `code <someFolder>`. In this case you explicitly tell code to open that folder and therefore it restores its state.  You ask for a new behavior: starting a new **blank** session of a given workspace.

**Comment by Dyoung0606** [comment]
I swear I did a search but that one did not come up.  Thanks for the pointer.
