### ISSUE TITLE
ES & TS autoimport features enhance

### ISSUE THREAD

**Issue by chebotiuk** [Microsoft/vscode#54871]
No useful ways to import es & ts modules without of intalling packages.
Want to have `importAll` and `import word under cursor` options out of box.

Let me know when you'll implement it.
Best regards Pavlo, chebotuk@gmail.com

**Comment by mjbvz** [comment]
An `import all` quick fix is already available in VS Code insiders. It will also be in VSCode 1.26

**Comment by chebotiuk** [comment]
@mjbvz great! Thank you
