### ISSUE TITLE
React 'Props' raise error "'type arguments' can only be used in a .ts file"

### ISSUE THREAD

**Issue by DiegoNovati** [Microsoft/vscode#54882]
- VSCode Version:
Version 1.25.1 (1.25.1)
- OS Version:
macOS Sierra - 10.12.6

Steps to Reproduce:

1. Create a react project using create-react-app

2. Add flow to the project:
    npm install flow-bin --save-dev
    npm run flow init

3. Open the project with VS Code

4. Open the file 'App.js' and add the following as first line

    // @flow

5. In the same file 'App.js'modify the line 

    class App extends Component {

with the following lines:

    type Props = {};

    class App extends Component<Props> {

Now both 'Props' will display the error

     [ts] 'type aliases' can only be used in a .ts file.

Does this issue occur when all extensions are disabled?: Yes/No

Yes

**Comment by mjbvz** [comment]
VS Code does ship with built-in Flow support. To use Flow, install the [flow extension](https://marketplace.visualstudio.com/items?itemName=flowtype.flow-for-vscode) and [follow these instructions](https://github.com/flowtype/flow-for-vscode#setup)
