### ISSUE TITLE
css font-face unicode-range

### ISSUE THREAD

**Issue by heidarv** [Microsoft/vscode#54889]
Issue Type: <b>Bug</b>

css parser get error on code:
unicode-range: U+6??;

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

**Comment by kieferrm** [comment]
@heidarv Please provide a concrete `css` snipped together with the steps you take to open it. Thanks!
