### ISSUE TITLE
Changing window.zoomLevel makes the opposite effect on the custom title bar menus

### ISSUE THREAD

**Issue by qcz** [Microsoft/vscode#54885]
Issue Type: <b>Bug</b>

When changing window.zoomLevel, the menu bar shrinks instead of growing, and vice versa. See:
![2018-07-23_15-42-16](https://user-images.githubusercontent.com/304384/43092602-005b2d14-8eae-11e8-83e4-0fcbbeea17ec.gif)

VS Code version: Code - Insiders 1.26.0-insider (90fc7e66e2e10f643871b42f9c0f1f989d0ed221, 2018-07-23T10:03:03.289Z)
OS version: Windows_NT x64 10.0.16299

**Comment by qcz** [comment]
@sbatten: This is maybe related to #54575, but not exactly.

**Comment by sbatten** [comment]
resolved by  #55100
