### ISSUE TITLE
Typescript reference is formatted to comment

### ISSUE THREAD

**Issue by lucavallin** [Microsoft/vscode#54893]
When I do this

```
/// <reference path="circleMath.ts"/>
/// <reference path="RectangleMath.ts" />
```

It is automatically formatted to

```
/// <reference path="circleMath.ts"/> / <reference path="RectangleMath.ts" />
```

and in general every comment. I am using TSLint with Prettier. Any idea?
Thanks!

**Comment by mjbvz** [comment]
Does this reproduce with all extensions disabled?

**Comment by lucavallin** [comment]
All linters at least, yes. Do you want my to try with ALL extensions?

**Comment by mjbvz** [comment]
Yes, try disabling Prettier and tslint too to see which one causes this

**Comment by lucavallin** [comment]
I'm happy to say I am a true idiot, I didn't disable "taichi.react-beautify" which I totally forgot I had installed.
However, I had to find an error in the console to be able to point to that. Is there a way to track what extensions are doing what? That would be handy!

**Comment by mjbvz** [comment]
Ok, closing as caused by extension. Please try filing this issue against that extension

I think helping users debug what extension contributes what falls under #53146
