### ISSUE TITLE
Can't debug unit tests

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#54899]
When I run the Unit Tests launch config I get

```
Loading "vs/css!vs/workbench/browser/parts/editor/media/notabstitlecontrol" failed
Detail:  Could not find /Users/roblou/code/vscode/src/../out/vs/workbench/browser/parts/editor/media/notabstitlecontrol.css or it was empty
Here are the modules that depend on it:
[ 'vs/workbench/browser/parts/editor/noTabsTitleControl' ]
```

The css file does exist, I think the ts file needs to not be loaded in by unit tests, or the css file should be loaded somewhere else.

**Comment by alexandrudima** [comment]
I think the most obvious change is in v8/node/Electron versions. It looks like that debug configuration is launching mocha using electron with `ELECTRON_RUN_AS_NODE`. That is different than running the tests via `scripts/test.sh`, in the former Electron is ran as node, while in the latter tests are executed in an Electron Renderer process. 

![image](https://user-images.githubusercontent.com/5047891/43838821-b892b5b2-9b1c-11e8-9114-067442ffe12e.png)

**Comment by bpasero** [comment]
@alexandrudima I can run the tests from `1.25` against a Electron `2.0.5`, so it must be something else.

**Comment by alexandrudima** [comment]
I cannot understand how this ever worked. I pushed a change where we do not attempt to load CSS using the real CSS loader.

**Comment by roblourens** [comment]
Thanks!

**Comment by bpasero** [comment]
@alexandrudima great, thanks ❤️
