### ISSUE TITLE
Able to change color of text of all editors that belong to editor group on de-activation of  

### ISSUE THREAD

**Issue by ilteris** [Microsoft/vscode#54891]
It would be great to be able to effect the color of the text of the editor group when cycling between editor groups. All I am looking for is to make unfocused editor group look like "unfocused" Currently both editor groups next to each other looks similar. 

It would be great to have something like editorGroup.unfocusedTextColor

which overrides editor text for unfocused EditorGroup maybe?

**Comment by bpasero** [comment]
This should be possible with the colors we provide (see inactive / unfocused colors for the editor).
