### ISSUE TITLE
Zen Mode causes slowdown, then hang, in Insiders edition on Debian Gnome

### ISSUE THREAD

**Issue by komali2** [Microsoft/vscode#54895]
- VSCode Version: 

```
Version: 1.26.0-insider
Commit: 90fc7e66e2e10f643871b42f9c0f1f989d0ed221
Date: 2018-07-23T09:57:57.891Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64
```

- OS Version:

```
OS Version: Debian GNU/Linux 9.5 (stretch) 64-bit
Gnome V 3.22.2
10.8GiB RAM
Intel Core i7-8650U @ 1.9GHz x 4
Graphics: Chromium

```
Steps to Reproduce:

1. Launch vscode
2. Enter zen mode via clicking view-> zen mode, or pressing ctrl + k, z

Zen mode will enter, vscode and computer will be usable for several seconds, then slowdown and hang. This differs from non-insiders-edition, in that it does not instantly hang. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
@komali2 does this also happen if you go into full screen and not zen?
Can you reproduce if you disable all extensions?

**Comment by komali2** [comment]
I can reproduce on a fresh debian install, on a fresh vscode install. (I can reproduce if i disable all extensions)

This is mostly likely a Debian issue, as it does not happen on previous versions of debian, and happens on many versions of vscode, not just insiders. I will try fullscreen mode soon.

**Comment by komali2** [comment]
This issue occurs in the same manner when entering fullscreen mode. 

The hang is caused by massive CPU usage by `gnome-shell`. The CPU usage remains even if vscode is exited from zen or fullscreen mode, and even if VScode is closed. The CPU usage does not go down until the system is fully restarted.

**Comment by komali2** [comment]
This issue happens on, at the very least, the preview version as well as the last 3 versions of VScode (that I have tested)

**Comment by komali2** [comment]
This issue happens when Chrome is entered into fullscreen mode via f11 as well. Will test other apps shortly. 

This is likely a Debian issue. https://unix.stackexchange.com/questions/458034/fullscreen-mode-in-apps-causes-gnome-shell-to-hit-80-100-cpu-even-after-closin

**Comment by isidorn** [comment]
Yeah, nothing we can do here. Please file an issue against chrome / debian.
Thanks
