### ISSUE TITLE
Atom packages compatibility

### ISSUE THREAD

**Issue by anaibol** [Microsoft/vscode#549]
Hi, I really like the new features of vscode. I think it would be really interesting the IDE to be compatible with Atom packages (apm).

**Comment by egamma** [comment]
While VS Code also builds on electron the layer on top is different and we use a fundamentally different approach to extensibliity see https://code.visualstudio.com/docs/extensions/our-approach.
Making a ship of the Atom API on top of the VS Code one is therefore no realistic.
