### ISSUE TITLE
Fullscreen on windows 10 not working properly

### ISSUE THREAD

**Issue by VIMGAS** [Microsoft/vscode#54902]
- VSCode Version: 1.26.0-insider
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Turn on custom titlebar.
2. Set up the screen in a way that it is not full screen.
3. Either double click the titlebar or drag the window by the titlebar to the top of the screen (windows will show a animation indicating it will occupy the whole screen after you drop it).
4. Notice the small gap on the top of vscode's window.

Screenshots: 
![image](https://user-images.githubusercontent.com/20145874/43102538-d1e2644a-8ea1-11e8-904f-12c97e94be5e.png)

![image](https://user-images.githubusercontent.com/20145874/43102670-1a996d78-8ea2-11e8-891f-e0ef2178bc21.png)

Does this issue occur when all extensions are disabled?: Yes

## P.S.: It does not happen 100% of times, try the steps 3 or 4 times to see the bug.

**Comment by Guema** [comment]
duplicate #52265
