### ISSUE TITLE
Quick open support for opening a folder in the explorer

### ISSUE THREAD

**Issue by sebastian-nowak** [microsoft/vscode#54904]
WebStorm's quick open equivalent allows not only opening files, but also folders. In order to open a folder instead of a file, you either have to prefix the name with '/' or add it as a suffix.

For example you could use quick open (cmd + p) to enter something like:
* /node_modules/mocha
* test/

Once you open a folder, explorer panel is opened, it's scrolled to the selected folder and the folder is expanded.

It's super useful when working with huge projects and it's something I *really* miss in VSCode.

**Comment by sebastian-nowak** [comment]
I do believe this feature request is crucial and should be looked into.

**Comment by ZYinMD** [comment]
+1.
A lot of times I don't remember the name of the file I want to open, but I remember the name of the folder it's in, so I just want to search and open the folder, and look for the file with my eyes.

**Comment by ZYinMD** [comment]
Hi @sebastian-nowak, maybe you should rename the issue title to include the keyword "search folder" - I think that's the term people would use when they search existing issues.
