### ISSUE TITLE
How to index functions in vscode?

### ISSUE THREAD

**Issue by biij5698** [Microsoft/vscode#5490]
We can index functions by Ctrl + R in sublime text,But I'm not found this function in vscode

**Comment by dbaeumer** [comment]
Actually VSCode supports that for language that provide symbol index features. To get the symbols for a single document use Ctrl+Shift+O. To get the symbols for a whole workspace use Crl+T and type the symbol name you are searching for.
 
![capture](https://cloud.githubusercontent.com/assets/1931590/14632654/33f491b6-061a-11e6-9337-ce24260e9da6.png)

![capture](https://cloud.githubusercontent.com/assets/1931590/14632692/60cf405a-061a-11e6-9186-6768dd41a747.png)

**Comment by biij5698** [comment]
But it doesn't work in PHP by Ctrl + T and Ctrl + Shift + O.

**Comment by biij5698** [comment]
@dbaeumer

**Comment by dbaeumer** [comment]
@biij5698 agree and we have a feature request for this.

**Comment by hehg** [comment]
we need this feature ,such as sublime

**Comment by dougpuob** [comment]
I need it too.

**Comment by sundyloveme** [comment]
But! Symbol list is dynamic. If click on space, the symbol list can be clear. I need symbol list hold on!!when I click wherever.

**Comment by fangxing204** [comment]
Not work for ruby?

**Comment by dheerajwebkul** [comment]
I am leaving vscode and switching to sublime just because of this feature is missing :(

**Comment by fernandovega** [comment]
You can install for php https://marketplace.visualstudio.com/items?itemName=linyang95.php-symbols
