### ISSUE TITLE
JS comment folding

### ISSUE THREAD

**Issue by rfossella** [Microsoft/vscode#54903]
Since upgrading to VSCODE 1.25 comment folding has stopped working.  I see other issues touching on this but is there any resolution?  
- VSCode Version: 1.25.1
Date: 2018-07-11
- OS Version: Windows 7 

Steps to Reproduce:

1.Open code
2. Hover over comment of the form
```
/**
 * xxxxx
 * xxxxx
 * xxxxxx
 */
```
3.  No folding option is shown
The issue occurs with/without extensions loaded

**Comment by mjbvz** [comment]
Likely duplicate of https://github.com/Microsoft/TypeScript/issues/22732

Is the comment attached to a function or variable or anything?

**Comment by rfossella** [comment]
Not attached to anything.  Just stand-alone comment blocks. I saw 22732 but it doesn't seem to offer a solution?

**Comment by mjbvz** [comment]
Yes this is a duplicate of Microsoft/TypeScript#22732. Needs to be fixed upstream

**Comment by matrixapps** [comment]
Has this problem yet been resolved?  V1.26 still has lingering issue.  Config option to change?

**Comment by mjbvz** [comment]
No, look at the upstream issues
