### ISSUE TITLE
Visual Studio Light Theme - Activity Bar is dark instead of light

### ISSUE THREAD

**Issue by Qedinux** [Microsoft/vscode#54900]
Issue Type: **Bug**

The Activity Bar for Visual Studio Light theme is dark instead of light.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (4 x 3600)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Memory (System)|4.00GB (2.70GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-fr|MS-|1.25.2
PowerShell|ms-|1.8.1

</details>

**Comment by mjbvz** [comment]
Can you please provide a screenshot of this

**Comment by kieferrm** [comment]
@Qedinux the out-of-the-box Visual Studio themes do have dark activity bars by design.

**Comment by pedrogarcia** [comment]
> @kieferrm: "@Qedinux the out-of-the-box Visual Studio themes do have dark activity bars by design."

Why? 
Why would I want a black activity bar if I set the theme to light?

**Comment by dan-modsi-io** [comment]
Ditto @pedrogarcia 

If I choose a Light theme I most definitely want a lighter colored Activity Bar.

I understand these are themes and there's some room for artistic expression.  But the default themes.. the ones that ship with VS Code should "make sense" and not leave the user scratching there heads wondering what's broke.
