### ISSUE TITLE
Display installed dependencies

### ISSUE THREAD

**Issue by Bernd-L** [microsoft/vscode#54917]
The dependencies tab of an Add-on should display which ones I have installed already/give me a button to install a dependency individually.

**Comment by sandy081** [comment]
Yeah, makes sense.

**Comment by ramya-rao-a** [comment]
@sandy081 What do you think of re-using the renderer used in the extensions viewlet for the dependencies and extension pack contents?

Because the minute we have an "Install" button next to the dependencies, the next logical request would be for a uninstall/enable/disable button.

**Comment by sandy081** [comment]
👍

**Comment by Bernd-L** [comment]
👍

**Comment by sandy081** [comment]
Now that we show extension packs separately from dependencies and provide options to install them separately, I do not see big reason to support this feature for extension dependencies. Hence closing this as out of scope.
