### ISSUE TITLE
The default keyboard shortcuts for debugging conflict with default OS keyboard shortcuts on macOS

### ISSUE THREAD

**Issue by dkorbar** [Microsoft/vscode#54914]
F11 is the default for step into in VSCode.
Shift + F11 is the default for step out in VSCode

F11 however is also the default for show Desktop on macOS and if that default isn't changed F11 (and neither shift + F11) will get to VSCode and will always show the Desktop instead.

One solution would be to use the same keys that XCode uses by default:
F6: step over
F7: step into
F8: step out

**Comment by weinand** [comment]
On macOS the "fn" is used to flip the meaning of a function key between the macOS commands and application specific commands.

And the OS provides means to always flip the functions keys:
![2018-09-07_12-59-17](https://user-images.githubusercontent.com/1898161/45215497-e1a38600-b29d-11e8-90f9-77d616cd6b71.png)

There is no way to find keyboard shortcuts that avoid collisions.

**Comment by dkorbar** [comment]
What you are describing is not a Mac-specific feature and it's also not automatically the case on all Mac computers.
Yes, some Mac keyboards and laptops use fn to switch between F1, F2, F3, etc. and function keys like screen brightness. So do some keyboards on Windows (especially on laptops).
I also don't see how this is relevant for this request. When using such a keyboard once can still use the F keys by pressing the FN key (or by pressing the F keys when said option is disabled).
The point is that when using F keys the default keys that Visual Studio Code is using are in conflict with OS default keys. There is a set of buttons that can be used for debugging that are not in conflict with default OS keys. The same keys that XCode is using and that macOS developers are familiar with.
