### ISSUE TITLE
file group index error 

### ISSUE THREAD

**Issue by ljporljp** [Microsoft/vscode#54916]
Issue Type: <b>Bug</b>

I have 2 group, file 1 is in group 1, file 2 is in group 2 , but Ctrl  + 1 change to group 1,but focus on file 2, and Ctrl + 2 change to group 2 but foucs on file 1

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.94GB (1.61GB free)|
|Process Argv|D:\Pro\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|1.2.6
lua-debug|act|0.3.6
Bookmarks|ale|9.0.1
code-gnu-global|aus|0.2.2
vscode-database|baj|1.5.2
path-intellisense|chr|1.4.2
vscode-svgviewer|css|1.4.4
vscode-markdownlint|Dav|0.18.0
vscode-eslint|dba|1.4.12
vscode-hasher|dee|1.0.1
jupyter|don|1.1.4
xml|Dot|2.3.1
gitlens|eam|8.5.2
tslint|eg2|1.0.34
file-icons|fil|1.0.12
code-runner|for|0.9.3
gc-excelviewer|Gra|2.1.24
beautify|Hoo|1.3.2
nsis|idl|3.13.2
latex-workshop|Jam|5.6.1
Lua|key|0.0.9
cmake-tools-helper|mad|0.2.1
vscode-clang|mit|0.2.2
ecdc|mit|0.12.0
vscode-language-pack-zh-hans|MS-|1.25.3
mssql|ms-|1.4.0
python|ms-|2018.7.1
vscode-ai|ms-|0.1.9
cpptools|ms-|0.17.7
csharp|ms-|1.15.2
Go|ms-|0.6.84
PowerShell|ms-|1.8.1
debugger-for-chrome|msj|4.8.0
color-highlight|nau|2.3.0
qub-xml-vscode|qub|1.2.8
java|red|0.28.0
vscode-icons|rob|7.24.0
code-settings-sync|Sha|3.0.0
shader|sle|1.1.3
vscode-lua|tri|0.12.4
cmake|twx|0.0.17
unity-debug|Uni|1.3.0
cmake-tools|vec|1.1.0
vscode-redis|vit|1.2.0
vscode-java-debug|vsc|0.10.0
markdown-all-in-one|yzh|1.6.0

(1 theme extensions excluded)

</details>

**Comment by kieferrm** [comment]
@ljporljp I can't reproduce on 1.25.1 on Win10. Works for me as expected.

**Comment by ljporljp** [comment]
I have found this bug how to reproduce!  Follow me:
1、Open one workspace (can empty dir).
2、Create 3 or more files.
3、Move any of these files separately to 3 or more groups.

**Comment by ljporljp** [comment]
These groups should be drag to created

**Comment by kieferrm** [comment]
@ljporljp thanks!

When you create a 2x2 grid and fill it from the top left, top right, bottom left, to the bottom right you get different results on macOS and Windows.

On mac:
| <kbd>Cmd+1</kbd> | <kbd>Cmd+2</kbd> |
| <kbd>Cmd+3</kbd> | <kbd>Cmd+4</kbd> |

On windows:
| <kbd>Ctrl+1</kbd> | <kbd>Ctrl+3</kbd> |
| <kbd>Ctrl+2</kbd> | <kbd>Ctrl+4</kbd> |

I'd expect VS Code on Windows to behave the same as on the mac.

**Comment by bpasero** [comment]
@kieferrm I do not think what you describe is related to the issue, what you see very much depends on the initial orientation of the grid. Cmd+1, Cmd+2, etc. works in grid order, not in visual order, so if the root orientation is vertical vs horizontal, it can well be that Cmd+2 brings you to the bottom left corner. @joaomoreno and me figured out this might be unexpected, but we did not want to push this further and wait for users to complain.

@ljporljp I am trying to understand your issue or reproduce, are you saying that you have 2 files open side by side and Ctrl+1 correctly activates the left editor, but the blinking cursor stays in the right editor? Can you attach a video?

**Comment by ljporljp** [comment]
@bpasero No, sorry for my poor present leading you misunderstand and can not reproduce.
Clearly: 
this can reproduce without the workbench-grid layout.
i just drag to add the third horizontal group, then ctrl+N(1,2,3) just mismatch the opened eidtor's(in the left panel) index.

**Comment by bpasero** [comment]
@ljporljp Ctrl+Number is for switching editor groups, not editors. You can change keybindings to alter that behaviour. I am going to close this issue now that I understand your issue.

**Comment by ljporljp** [comment]
@bpasero no, you don't understand me. And I know Ctrl + N is for switching editor groups , I do mean that Ctrl + N mismatch the showing group index in the open editors index by my way.
![20180809090816](https://user-images.githubusercontent.com/5728237/43872342-dfc88994-9bb3-11e8-9f3b-225cd0beded9.png)
Above is Ctrl + 2, but focus on group 3.

**Comment by ljporljp** [comment]
@bpasero test3.lua is in third group ! You should see it at the left opened editors .it's in "第 3 组", and i really  pressed Ctrl + 2 !

**Comment by bpasero** [comment]
@ljporljp interesting, yeah it looks like the "open editors" view is out of sync with what is showing on the right hand side. 

Can you give me any more detailed steps how to reproduce this issue, ideally from scratch from an empty state where no editor is opened? Thanks!

**Comment by ljporljp** [comment]
@bpasero Ok, I have to post some screenshots to you.
![1](https://user-images.githubusercontent.com/5728237/43889607-3db7d878-9bf7-11e8-9529-797c444aac31.jpg)

![2](https://user-images.githubusercontent.com/5728237/43889620-4c4a600e-9bf7-11e8-8979-4d9e4d5a39a8.jpg)

![3](https://user-images.githubusercontent.com/5728237/43889631-518d4716-9bf7-11e8-987a-3f29e9f03775.jpg)

![4](https://user-images.githubusercontent.com/5728237/43889641-57ad1a04-9bf7-11e8-9c4f-e39464545114.jpg)

![5](https://user-images.githubusercontent.com/5728237/43889652-5d8bb2aa-9bf7-11e8-99c8-a195988f4336.jpg)

![6](https://user-images.githubusercontent.com/5728237/43889656-6297f6fa-9bf7-11e8-8de6-54f67bd04607.jpg)

![7](https://user-images.githubusercontent.com/5728237/43889663-66a61588-9bf7-11e8-883e-f5aa2a2ff89f.jpg)

![8](https://user-images.githubusercontent.com/5728237/43889672-6b128656-9bf7-11e8-916e-32cdb45343d1.jpg)

![9](https://user-images.githubusercontent.com/5728237/43889688-6f16dce8-9bf7-11e8-93ad-ebfd054ab026.jpg)

**Comment by bpasero** [comment]
@ljporljp thanks for the explanation! this actually works as designed now that I see how you got there. The order in the "open editors" view is by creation time of the group, not in visual order. Otherwise the open editors view would update quite frequently when you change layouts. We decided to go with this to reduce noise in the view.

**Comment by ljporljp** [comment]
@bpasero But this made inconsistent and confused. So i think it's just not implemented well.
