### ISSUE TITLE
Freeze up after leaving running overnight

### ISSUE THREAD

**Issue by OMGtechy** [Microsoft/vscode#5491]
Version 0.10.11
Commit f291f4ad600767626b24a4b15816b04bee9a3049
Date 2016-03-11T16:19:03.130Z
Shell 0.35.6
Renderer 45.0.2454.85
Node 4.1.1
Using the C++ extensions

Ubuntu 14.04 LTS

Steps to Reproduce:

1. Leave VS Code running overnight with laptop lid shut
2. When I return the next morning, it's unresponsive and eventually prompts me to close it

It's not the only program that has this issue when I come back in the mornings (Toggl and Slack sometimes do too, but that requires a kill -9 to fix!). Other apps, such as Thunderbird and Firefox, do not have this problem.

I've also noticed that over time the editor gets slower and slower, eventually grinding to a halt. Perhaps this is just the manifestation of that overnight? Perhaps some kind of leak, be it tasks or memory?

**Comment by dbaeumer** [comment]
@bpasero assigning to you since I remember you looked into a similar issue. Interesting is that @OMGtechy points out Slack (which is an electron app) has similar behavior.

**Comment by bpasero** [comment]
Likely #508. I have a change pushed to test something out in insiders.
