### ISSUE TITLE
[Feature request] Add the ability to open the User folder like "%appdata%\Code" in the file manager from Vscode

### ISSUE THREAD

**Issue by maclam** [Microsoft/vscode#54918]
Hi Team,

I often use this feature in Sublime Text on Windows, Linux and Mac because it's more comfortable than manually opening this folder in the file manager.
![sublime](https://user-images.githubusercontent.com/22882318/43124530-bb698c12-8f27-11e8-95b2-2a25bc19e5d0.png)

Please add "Browse Global .vscode" and "Browse Global Settings" to the File menu.

Thank you very much

**Comment by kieferrm** [comment]
@maclam, can you give more detail of what you think "Browse Global .vscode" and "Browse Global Settings" will do when being selected by the user?

**Comment by maclam** [comment]
Sorry for my terrible english ...
I mean, for example on Windows, if we select "Browse Settings" from the File menu, it calls the File Explorer to open "C:\User\username\AppData\Roaming\Code" folder, and "Browse .vscode" => C:\Users\username\.vscode.
