### ISSUE TITLE
[Portable] Extensions not loading on second window

### ISSUE THREAD

**Issue by jlanza** [Microsoft/vscode#54922]
- VSCode Version: 1.25.1 Portable
- OS Version: Windows 10 Build 17134

Steps to Reproduce:

1. Open one folder with VS Code from File Explorer
2. Open second folder with VS Code from File Explorer

The 1st window has all the extensions enabled, while the second doesn't. When switching on the developer console I got the following message when reloading the window:
no standard startup: not a new window

Does this issue occur when all extensions are disabled?: Yes/No
The problem is with extensions so I'm not disabling them ;)

**Comment by kieferrm** [comment]
@jlanza how do you get steps 1 and 2 to work? You have a portable install, i.e. one that installs with `unzip` but you use context menu actions in Window's File Explorer to open folders in VS Code. How did you setup the context menu actions?

**Comment by jlanza** [comment]
I have the system configured manually. I have used this configuration when there wasn't an official VSCode version and I've been using `--user-data-dir "userdata" --extensions-dir "extensions"`. At that moment VSCode was not my main IDE but now it is so I am properly configuring it ;)
```
@echo off
SET vscodePath=VSCODE_EXE_PATH
 
rem add it for all file types
@reg add "HKEY_CLASSES_ROOT\*\shell\Open with VS Code"         /t REG_SZ /v "" /d "Open with VS Code"   /f
@reg add "HKEY_CLASSES_ROOT\*\shell\Open with VS Code"         /t REG_EXPAND_SZ /v "Icon" /d "%vscodePath%,0" /f
@reg add "HKEY_CLASSES_ROOT\*\shell\Open with VS Code\command" /t REG_SZ /v "" /d "%vscodePath% \"%%1\"" /f
 
rem add it for folders
@reg add "HKEY_CLASSES_ROOT\Folder\shell\Open with VS Code"         /t REG_SZ /v "" /d "Open with VS Code"   /f
@reg add "HKEY_CLASSES_ROOT\Folder\shell\Open with VS Code"         /t REG_EXPAND_SZ /v "Icon" /d "%vscodePath%,0" /f
@reg add "HKEY_CLASSES_ROOT\Folder\shell\Open with VS Code\command" /t REG_SZ /v "" /d "%vscodePath% \"%%1\"" /f

rem add it for inside a folder (background)
@reg add "HKEY_CLASSES_ROOT\Directory\Background\shell\Open with VS Code"         /t REG_SZ /v "" /d "Open with VS Code"   /f
@reg add "HKEY_CLASSES_ROOT\Directory\Background\shell\Open with VS Code"         /t REG_EXPAND_SZ /v "Icon" /d "%vscodePath%,0" /f
@reg add "HKEY_CLASSES_ROOT\Directory\Background\shell\Open with VS Code\command" /t REG_SZ /v "" /d "%vscodePath% \"%%V\"" /f
```
I have noticed that if I open a VSCode window and then `File->New Window` the extensions are properly loaded. Is there anyway I can set the registry entries to open a new window instead of a new instance of VSCode.

**Comment by jlanza** [comment]
I think I found the error.... it was my fault :( I still have the --extension and --user-data arguments on the command line I defined in the registry.

Sorry for the inconveniences. I'm closing and will reopen in case I found something strange.
