### ISSUE TITLE
Shell Script Language Mode: "endif" not highlighted correctly on tcsh scripts

### ISSUE THREAD

**Issue by dsanz006** [Microsoft/vscode#54926]
I am writing a very simple tcsh script on VS code and I can see that the shellscript language mode doesn't highlight the syntax correctly in all cases. For example, on an if/else instruction like this one:

`if (${ERRORCODE} != 0) then`
    `echo "Error"`
`else`
    `echo "Success"`
`endif`

Here, `if`, `then` and `else` are highlighted correctly, but `endif` is not. It should be highlighted as the rest.

I don't know if this happens with more keywords, because I have used VS code for tcsh scripts in a very limited way.

- VSCode Version: 1.25.1
- OS Version: Ubuntu 16.04.4 LTS

**Comment by aeschli** [comment]
This issue was moved to atom/language-shellscript#123
