### ISSUE TITLE
menu bar item select animation is disturbing (windows, 32bit)

### ISSUE THREAD

**Issue by AdmiralSnyder** [Microsoft/vscode#54927]
Issue Type: <b>Feature Request</b>

there is a whoosh - animation when you change through the items in the  menu bar (somehow like a filled circle expanding).
this makes the eye focus toward the thing that just has been selected and is displayed in a different color. but when you click a menu, you want the eyes to focus as quickly as possible to the menu content. please disable this.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:11.471Z)
OS version: Windows_NT ia32 10.0.17134

**Comment by sbatten** [comment]
@AdmiralSnyder Thanks for your feedback. The animation you are referring to is part of the Electron menu. We have been working on a new custom menubar that can be enabled via the setting `window.titleBarStyle` => `custom`. Please try it out and let us know what you think :)

**Comment by AdmiralSnyder** [comment]
looks good. i think i like the decision to integrate menu and title bar. the system icon (with the vs code logo should contain all the usual system context menu items, though (resize, move, close, …)) but at least double-clicking it to close the window works. should i create an issue for that?

**Comment by sbatten** [comment]
There is a separate issue for this currently here #52904 resolved with details in the comments.
