### ISSUE TITLE
Top Left Logo closes Window

### ISSUE THREAD

**Issue by Venrir** [Microsoft/vscode#54929]
Issue Type: <b>Bug</b>

1.26.0-Insiders:
Click on Logo twice or once.
*poof* its gone

VS Code version: Code - Insiders 1.26.0-insider (26e5a55cd8452477bfb7a472ea9475761600adf0, 2018-07-20T05:18:39.569Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (6.27GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|29%|

</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
vscode-custom-css|be5|2.7.1
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.59
jshint|dba|0.10.19
vscode-eslint|dba|1.4.12
make-hidden|dev|2.3.1
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.34
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.3.0
sass-lint|gle|1.0.2
path-autocomplete|ion|1.12.0
Angular2|joh|6.1.1
vscode-codemetrics|kis|1.17.1
Angular-BeastCode|Mik|6.2.1
vscode-scss|mrm|0.6.2
debugger-for-chrome|msj|4.8.0
material-icon-theme|PKi|3.5.2
LiveServer|rit|5.1.1
sass-indented|rob|1.4.9
vsc-material-theme-italicize|Ser|0.0.14
JavaScriptSnippets|xab|1.7.0
html-css-class-completion|Zig|1.17.1

(4 theme extensions excluded)

</details>

**Comment by kieferrm** [comment]
Although this is the default behavior on Windows (see explorer window and notepad), we should move away from it. Neither Edge, office, or Chrome are behaving this way.

**Comment by beastdestroyer** [comment]
#55656
