### ISSUE TITLE
Test Breadcrumbs

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#54935]
- [x] any os @alexandrudima 
- [x] any os @sandy081 

Complexity: 3

re #9418 - This is about breadcrumbs. Please test that

* you can enable/disable breadcrumbs via a setting
* you can enable/disable breadcrumbs via the global menu (View > Toggle Breadcrumbs)
* breadcrumbs show when using tabs or when not using tabs and in both cases an appropriate style is used
* breadcrumbs show for text files and binary files
* breadcrumbs show outline symbols when a corresponding extension exists (e.g. JSON, TypeScript etc)
* breadcrumbs update as you open/close files and, when having outline symbols, as the cursor moves 
* breadcrumbs can be focused via the command palette and via <kbd>Cmd/Ctrl+Shift+.</kbd>
* breadcrumb items can be navigated with <kbd>Shift+ArrowLeft/Right</kbd>
* breadcrumb items can be selected via <kbd>Shift+Enter</kbd> or Ctrl/Cmd+Click and the item will be reveal in the editor
* a picker can shows on <kbd>Enter</kbd> or Click
* the picker moves when pressing <kbd>Shift+ArrowLeft/Right</kbd>
* the picker reveals the current element
* the picker filters, reveals, and highlights items as you start typing
* the picker hides when selecting an element, when clicking somewhere else, or when hitting <kbd>Esc</kbd> (often enough - that's a known issue)
* breadcrumbs can be configured how to show the file path and symbol path
* breadcrumbs can be configured to use quick pick instead of individual pickers

**Comment by sandy081** [comment]
@jrieken Good work. It works pretty smooth and nice.

**Comment by alexandrudima** [comment]
Nice job!!!

But I don't understand this row:

* breadcrumb items can be selected via Shift+Enter or Ctrl/Cmd+Click and the item will be reveal in the editor

Shift+Enter behaves like Escape for me and Cmd+Click behaves like click for me.
