### ISSUE TITLE
Please add editor.acceptSuggestionOnTab or equal setting

### ISSUE THREAD

**Issue by lillem4n** [Microsoft/vscode#54936]
It should work exactly like editor.acceptSuggestionOnEnter , except, obviously it should affect tab and not enter.

The result I'm after, for example, is to ONLY allow enter to accept suggestions.

Now, an even better option would be:

editor.acceptSuggestionKeys: ["tab", "enter", "esc"...]
editor.acceptSuggestionBehaviour: "smart" / "on" / "off"

**Comment by jrieken** [comment]
To unbind <kbd>Tab</kbd> just add this to your keybindings.json-file

```json
{
	"key": "tab",
	"command": "-acceptSelectedSuggestion"
},
```

**Comment by lillem4n** [comment]
I already hacked the keybindings.json file a bit so I could work without getting crazy. :) But it would be more straight forward in the settings imo. Especially since editor.acceptSuggestionOnEnter already exists.

**Comment by jrieken** [comment]
No plans to make this a setting as this can be configured via keybindings.json and because there is little demand for this
