### ISSUE TITLE
Python tutorial: wrong link to flask tutorial (.md extension should be removed)

### ISSUE THREAD

**Issue by r03** [Microsoft/vscode#54931]
This page contains a wrong link: https://code.visualstudio.com/docs/python/environments

> The next section describes how to select an environment, include virtual environments. For an example of using a virtual environment in a project, see the Flask tutorial.

The link to Flask tutorial is this: https://code.visualstudio.com/docs/python/tutorial-flask.md

But the .md extension should be removed.

**Comment by r03** [comment]
I'm not sure if this is the correct repo, but the error page suggests to create an issue here:
https://code.visualstudio.com/docs/python/tutorial-flask.md

**Comment by kieferrm** [comment]
@gregvanl one for the vscode-docs repo.

**Comment by gregvanl** [comment]
Fixed https://github.com/Microsoft/vscode-docs/commit/9207fa64f863cb39b0090102d1f7c3c55f704744
