### ISSUE TITLE
Refresh Problems List

### ISSUE THREAD

**Issue by PeterLaComb-Availity** [Microsoft/vscode#54934]
Issue Type: <b>Feature Request</b>

The Problems list provides no refresh mechanism, so after changing branches I'm left with reports of errors for files that don't exist on disk.

Clearly something triggers VSCode and extensions to update this list - that should be something users can trigger, and it should start by clearing the list and having everything report out again.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 16.7.0

**Comment by kieferrm** [comment]
The problems are generated by extensions and pushed to the core or they come through problem matchers on tasks the user runs. I assume that in your case the problems are generated by a build process either run as a task or triggered by an extension. The build needs to re-run after the branch switch. For us, there is no generic way to trigger that build. If the extension ran the build, the extension should listen to file changes and re-run the build or let you know that the build is stale.
