### ISSUE TITLE
Test decorations in custom views

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#54939]
Ref: #47502

- [x] anyOS @weinand 
- [x] anyOS @alexandrudima 

Complexity: 2

## Set up
- Clone https://github.com/Microsoft/vscode-extension-samples/tree/master/tree-view-sample
- `npm install`
- `npm run watch`
- `F5` to start debugging
- Open a folder in that window
- Custom File explorer view replicating the file explorer should be shown in the Explorer

## Testing

* Check that you see GIT colors and badges for modified, untracked, and ignored files.
* Check that you see colors and badges for errors and warnings.
* Test that you can turn on/off colors and badges via `explorer.decorations.colors` and `explorer.decorations.badges`. 
* Check that decorations are in sync with those in file explorer and open editors views.
* Check that decorations are **not** shown in other custom views like `FTP Explorer`.

**Comment by weinand** [comment]
@sandy081 I hope this item does not involve writing code. If it does, then I don't accept a Complexity below 4!

**Comment by rebornix** [comment]
@sandy081 may I ask that whether this only works for `file` scheme? I tried this with a custom scheme but file decoration provider is not triggered?

**Comment by sandy081** [comment]
@rebornix This only works for `file` scheme as the decorations are supported only for file URIs. There is an issue #54938 to support decorations for all schemes.
