### ISSUE TITLE
intelliSense doesn't see hasOwnProperty 

### ISSUE THREAD

**Issue by Sergged** [Microsoft/vscode#54944]
Issue Type: <b>Bug</b>

When type object.hasOwnProperty - VS Code haven't any suggestions for helping. But if will add () to object.hasOwnProperty, intelliSense will find function description in its data base

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.0.1
path-intellisense|chr|1.4.2
auto-rename-tag|for|0.0.15
sublime-keybindings|ms-|4.0.0
vscode-docker|Pet|0.0.27
live-sass|rit|3.0.0
LiveServer|rit|5.1.1

</details>

**Comment by mjbvz** [comment]
This is by design since that property—and other ones common to all js objects—would be shown in almost every intellisense suggestion. It's just noise most of the time
