### ISSUE TITLE
On Outline is it possible to get Expand All and Retract All

### ISSUE THREAD

**Issue by albu77** [microsoft/vscode#54941]
Issue Type: <b>Feature Request</b>

It would be practical to be able with one click to modify the outline to everything expanded or everything retracted

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:11.471Z)
OS version: Windows_NT ia32 6.1.7601

**Comment by kieferrm** [comment]
**Collapse All** is in the section header. 

![screen shot 2018-07-24 at 4 13 22 pm](https://user-images.githubusercontent.com/4674940/43170934-868dd5ea-8f5c-11e8-8fe3-9951c5319b42.png)


**Expand All** to bring the outline back into the state it was in when the editor got focus is missing.

**Comment by albu77** [comment]
Yes, My question was really to have a toggle effect on the button. I took note Expand All is missing.

**Comment by JVimes** [comment]
It would be great if that button were a toggle to "collapse/expand all" in the outline. I think a lot of us click it a second time, expecting toggle behavior.

**Comment by jrieken** [comment]
Thanks to the new tree this is now possible
