### ISSUE TITLE
 Illegal value 82 for `line`

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#5494]
Issue Id: <b>552da819-3bfd-3cb0-7b94-8ab0a0d035c4</b><br /><br />*Versions* <br />- 1.0.0-insider<br />-  c1d66b6e47c9da4c768ce7f216da14e7e4ac06ff<br />*Stack* <br />Error: Illegal value 82 for `line`<br />    at t.lineAt (\out\vs\workbench\node\pluginHostProcess.js:18:29390)<br />    at Object.t.lineAt (\out\vs\workbench\node\pluginHostProcess.js:18:28204)<br />    at Guides.getRangesForLine (\spywhere.guides-0.2.2\out\src\extension.js:217:57)<br />    at Guides.updateEditor (\spywhere.guides-0.2.2\out\src\extension.js:142:34)<br />    at null._onTimeout (\spywhere.guides-0.2.2\out\src\extension.js:121:19)<br />    at Timer.listOnTimeout (timers.js:89:15)<br />

**Comment by aeschli** [comment]
Lets rename the exception to 'Illegal line number' without mentioning the line.
