### ISSUE TITLE
Allow terminal escape sequence logging

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#54949]
xterm.js has a "debug mode" which prints escape sequences to the console, this will be helpful in diagnosing issues and prevent the need for users to check bugs in the xterm.js demo.

**Comment by Tyriar** [comment]
Verifier please check the command "Toggle Escape Sequence Logging" logs data to the console when you run command sin the terminal.

**Comment by isidorn** [comment]
F1 > toggle escape sequence logging has no effect on my terminal
zshell, osx
Am I missing something or what should the actuall effect be?

**Comment by Tyriar** [comment]
@isidorn when it's on there should be a bunch of logs in the devtools console when anything happens in the terminal.

**Comment by isidorn** [comment]
I do not really get anything
![logs](https://user-images.githubusercontent.com/1926584/43478181-7ba4b15c-94fd-11e8-8e4c-0253555be26b.gif)

**Comment by JacksonKearl** [comment]
I was able to verify on Win10
