### ISSUE TITLE
[Python] pytest only executing a subset of tests. 

### ISSUE THREAD

**Issue by zopyx** [Microsoft/vscode#54940]
- VSCode Version: 1.25.1
- OS Version: Latest Open-Suse

I am using VSCode with the Python plugin, enabled pytest support.

I have one test_XX.py file with five `test_somethingXXX()` methods which are recognized by pytest on the console as five test. The five tests also have in VSCode the "Run Test, Debug Test" annotation.

Clicking on "Run Test" executes only 2 tests out of five. I don't see the "pytest.." commandline.

Any pointer?

**Comment by weinand** [comment]
Pease file against Python extension.
