### ISSUE TITLE
No difference between "editor.action.selectHighlights" and "editor.action.changeAll"?

### ISSUE THREAD

**Issue by GandalfSaxe** [Microsoft/vscode#54954]
We have these two commands:

| Shortcut (Mac) | Command description  | Command |
| ------------- | ------------- | ------------- |
| ⇧⌘L | Select all occurrences of current selection | editor.action.selectHighlights |
| ⌘F2 | Select all occurrences of current word | editor.action.changeAll |

I've been testing them out, and they seem to do the exact same thing. The description could suggest that only ⌘F2 only works for a single word rather than an arbitrary selection, but they worked the same in my testing.

If they are indeed the same, shouldn't they just be rolled into one single command. Unless I'm mistaken and they're different somehow?

- VSCode Version: 1.26 Insiders
- OS Version: macOS 10.14 Beta (18A336e)

**Comment by kieferrm** [comment]
The only difference I'm aware of is that the first one still works when the editor does not have focus, for example when the find widget is open, and when the file is read-only. @alexandrudima?

**Comment by alexandrudima** [comment]
They have the same implementation.

Change All is left for compatibility reasons (i.e. people might have created keybindings for it and people might be used to it in the context mneu)

https://github.com/Microsoft/vscode/blob/15411fdcb2dcc625a364e28d15f0f193d10897b5/src/vs/editor/contrib/multicursor/multicursor.ts#L642:L663

https://github.com/Microsoft/vscode/blob/15411fdcb2dcc625a364e28d15f0f193d10897b5/src/vs/editor/contrib/multicursor/multicursor.ts#L617:L640

**Comment by GandalfSaxe** [comment]
Just wanted to say that as a new user, it was confusing to me trying to learn the ins and outs of VSCode in depth, having duplicate functionality that actually just have two different names. Especially because there is no documentation on commands (that I could find?) as there is with settings with the comments above them. So I had to do a bunch of experimentation to determine that they actually were doing the exact same thing :)

If it's just a question of compatibility, you could remove one of the functions and map the keyboard shortcut of it to the other identical command. That is, both ⇧⌘L  and ⌘F2 continues to do the same, but both now invokes the one and same command. Auto update everybody's user keymap and tell them it happened in the change log.

Anyway keep up the good work 👍

**Comment by GandalfSaxe** [comment]
@alexandrudima If it's only left for compatibility purposes, should they both be mentioned in the keyboard shortcuts reference? Being a document for a subset of the most important keyboard shortcut, it seems odd that two entries are dedicated to a duplicate of functionality.

<img width="411" alt="screenshot 2018-08-12 at 14 30 51" src="https://user-images.githubusercontent.com/12127864/44002042-a8cc1920-9e3c-11e8-81d4-b479d8a3c8f1.png">
