### ISSUE TITLE
Search: Focus Next Search Result should keep track of removed search results

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#54950]
I tried to do a project wide search to remove the search term manually. Specifically I was removing `{type}` jsdoc annotation as it's redundant in TS so I searched the regex `\*.*\{`, removed the type and hit F4 to go to the next, unfortunately this doesn't work though as the search focus goes back to the top.

1. Search the folder for something
2. Press F4 several times to go to a result in the middle of the list
3. Delete the line
4. Press F4, I want to go to the next result, not the first result

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/20467 - I've tried to fix this before but it's turned out to be a pain
