### ISSUE TITLE
Join All Editor Groups should preserve which editor is active

### ISSUE THREAD

**Issue by kibiz0r** [Microsoft/vscode#54955]
Currently, if you have two groups open, with tabs like this:

```
|[ File1.cs ][ <MySelectedFile.cs> ][ File3.cs ]||[ File4.cs ][ File5.cs ][ File6.cs ]|
|                                               ||                                    |
|                                               ||                                    |
```

~And you run "Join All Editor Groups", then `File6.cs` will become the active editor.~ Looking at it closer, I actually have no idea how it determines the new active editor. Sometimes it seems to be simply the last editor, but other times I can't come up with any reason why it picks the editor that it does.

This is very jarring, since I'm using that command in order to focus on my current file, but if it's not ~my furthest-right editor~ the new active editor, then I completely lose context.

I was originally going to post this as a feature request, but after seeing [this commit message](https://github.com/Microsoft/vscode/pull/22389/commits/791341b31b4579287c98eaf054240b93a37f1976), I think that what I'm seeing is actually unexpected behavior.

**Comment by bpasero** [comment]
When merging editor groups, we just simply always changed the active editor of the group to merge into to become the active editor of the group that gets merged in. The fix is to only do that if the group that gets merged into another group is active.
