### ISSUE TITLE
[PowerShell] Foldable regions not working #region #endregion

### ISSUE THREAD

**Issue by AlexHimself** [Microsoft/vscode#54952]
Issue Type: <b>Bug</b>

Foldable regions are not working for Powershell. Here are screenshots of Powershell ISE vs VS Code:

**PowerShell ISE:**
![image](https://user-images.githubusercontent.com/10466466/43151770-9162d30c-8f21-11e8-8d60-f970de270276.png)

**VS Code:**
![image](https://user-images.githubusercontent.com/10466466/43151807-a33ecd06-8f21-11e8-92ab-6afcd1861b7f.png)

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz (8 x 3096)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.84GB (8.05GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.5.2
vscode-gist|ken|1.2.1
PowerShell|ms-|1.8.1

</details>

**Comment by Tyriar** [comment]
@tylerl0706 I think you can accomplish this via the API now, eg:

https://github.com/Microsoft/vscode/blob/e918835b38b756fbbaa8e1ede949472309d085cb/extensions/typescript-basics/language-configuration.json#L28-L33

**Comment by Tyriar** [comment]
Also this appears to be built in?

https://github.com/Microsoft/vscode/blob/e918835b38b756fbbaa8e1ede949472309d085cb/extensions/powershell/language-configuration.json#L26-L31

**Comment by AlexHimself** [comment]
@Tyriar so it's built in but not working? I have the latest VSCode & PowerShell extension.

I created a new issue under the PS Extension https://github.com/PowerShell/vscode-powershell/issues/1449
