### ISSUE TITLE
Notepad inside the VSCode

### ISSUE THREAD

**Issue by cadupedroni** [Microsoft/vscode#54957]
I have the need to make several specific annotations for each project, be it for structure construction, business conditions, information for authentication, among others.

Today I make these notes in OneNote, which helps me a lot but it would not be possible to have notepad something very simple even just for notes of the projects, but that are not saved within the projects, could be a folder of documents inside the folder Vscode.

To open the Notes option could be an icon on the side like the extensions, and the notes open as a new tab inside the Vscode.

If you think it's a good idea or don't leave your comments, I don't know if anyone has the same need.

**Comment by V-ed** [comment]
This would be perfect for an extension.

_Let's see... \*quick google search for `vscode notes`\*_

Hey, there's the [VSNotes extension](https://marketplace.visualstudio.com/items?itemName=patricklee.vsnotes) that does pretty much exactly what you ask about!

Hopefully this extension will be enough for you.

Oh and sorry for the passive aggressive comment / solution. I don't mean any harm, I guess I'm just having a bad day. :)

**Comment by cadupedroni** [comment]
Yes, perfect. Thank you
