### ISSUE TITLE
Type constructor have to press r twice

### ISSUE THREAD

**Issue by wcauchois** [Microsoft/vscode#54959]
Issue Type: <b>Bug</b>

When I type "constructor" in an editor text field, it stops before the last "r" and I have to press the "r" key twice. I was noticing this while editing TypeScript, but it also repros in a blank text editor. I have the Vim extension installed, so not sure whether that affects things either.

It also doesn't seem to happen for other "r"s. Just the "r" at the end of the word "constructor". Attached is a GIF of this in action, even though it doesn't include my keyboard input you can see the pause where I have to type r twice. This repro's 100% of the time.

![jul-24-2018 14-02-39](https://user-images.githubusercontent.com/300544/43157274-93a4005e-8f4a-11e8-8343-8ecedb019981.gif)

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.32GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_57358|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.27
sort-typescript-imports|mic|1.4.1
graphql|mqu|0.1.2
debugger-for-chrome|msj|4.8.0
vim|vsc|0.15.3

</details>

**Comment by kieferrm** [comment]
I could reproduce it when installing the `vim` extension. Its a timing issue. The 'r' is not eaten all the time. When you briefly pause after the 'o' the 'r' is inserted correctly.

Created https://github.com/VSCodeVim/Vim/issues/2888.
