### ISSUE TITLE
Visual studio code rename symbol in angular project is not updating the classes mentioned in app.module.ts file

### ISSUE THREAD

**Issue by rkramakrishna17** [Microsoft/vscode#54956]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. After you have created a component in angular 6 project.
2. Double click and select a class (component or service or directive).
3. From the options show select 'Rename Symbol'. 
4. When you get the text box, change to the required name and press Return (Enter) key.
5. This changes will be reflected in all places where this class was used except app.module.ts file.

Does this issue occur when all extensions are disabled?: Yes

checked in visual studio code version :

Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:40:20.190Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

**Comment by rkramakrishna17** [comment]
My OS is ubuntu 16.04

**Comment by mjbvz** [comment]
I can't repo this using the latest VS Code insiders build. The `declarations` and `bootstrap` sections in `app.module.ts` both seem to be updated properly.

Can you please test this using the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled.

**Comment by rkramakrishna17** [comment]
Yes verified this issue in latest insiders buid. Its working fine now.

Version: 1.26.0-insider
Commit: 5fae91d61f12726e149fe5baed342eac2fbf8f88
Date: 2018-07-25T05:18:52.916Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
