### ISSUE TITLE
 Internal module service_remote.js not found.

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#5495]
Issue Id: <b>b31506ae-f51c-5973-11b1-cddf1965e801</b><br /><br />_Versions_ <br />\- 1.0.0-insider<br />_Stack_ <br />Error: Internal module service_remote.js not found.<br />[/vs/workbench/parts/debug/node/rawDebugSession.ts#L79:29](https://github.com/microsoft/vscode/blob/c1d66b6e47c9da4c768ce7f216da14e7e4ac06ff/src/vs/workbench/parts/debug/node/rawDebugSession.ts#L79:29)<br />[/vs/base/common/winjs.base.raw.js#L1470:0 (onError)](https://github.com/microsoft/vscode/blob/c1d66b6e47c9da4c768ce7f216da14e7e4ac06ff/src/vs/base/common/winjs.base.raw.js#L1470:0 %28onError%29)<br />[/vs/base/common/winjs.base.raw.js#L1176:0 (_notify)](https://github.com/microsoft/vscode/blob/c1d66b6e47c9da4c768ce7f216da14e7e4ac06ff/src/vs/base/common/winjs.base.raw.js#L1176:0 %28_notify%29)<br />[/vs/base/common/winjs.base.raw.js#L1343:0 (enter)](https://github.com/microsoft/vscode/blob/c1d66b6e47c9da4c768ce7f216da14e7e4ac06ff/src/vs/base/common/winjs.base.raw.js#L1343:0 %28enter%29)<br />[/vs/base/common/winjs.base.raw.js#L1316:0 (_run)](https://github.com/microsoft/vscode/blob/c1d66b6e47c9da4c768ce7f216da14e7e4ac06ff/src/vs/base/common/winjs.base.raw.js#L1316:0 %28_run%29)<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L79:5 (errorDispatch)](https://github.com/microsoft/vscode/blob/c1d66b6e47c9da4c768ce7f216da14e7e4ac06ff/src/vs/workbench/parts/debug/node/v8Protocol.ts#L79:5 %28errorDispatch%29)<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L147:5 (clb)](https://github.com/microsoft/vscode/blob/c1d66b6e47c9da4c768ce7f216da14e7e4ac06ff/src/vs/workbench/parts/debug/node/v8Protocol.ts#L147:5 %28clb%29)<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L114:11 (dispatch)](https://github.com/microsoft/vscode/blob/c1d66b6e47c9da4c768ce7f216da14e7e4ac06ff/src/vs/workbench/parts/debug/node/v8Protocol.ts#L114:11 %28dispatch%29)<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L69:8 (handleData)](https://github.com/microsoft/vscode/blob/c1d66b6e47c9da4c768ce7f216da14e7e4ac06ff/src/vs/workbench/parts/debug/node/v8Protocol.ts#L69:8 %28handleData%29)<br />    at emitOne (events.js:77:13)<br />

**Comment by aeschli** [comment]
Also:
/vs/workbench/parts/debug/node/rawDebugSession.ts#79:29 
 /vs/base/common/winjs.base.raw.js#1470:0 (onError) 
 /vs/base/common/winjs.base.raw.js#1176:0 (_notify) 
 /vs/base/common/winjs.base.raw.js#1343:0 (enter) 
 /vs/base/common/winjs.base.raw.js#1316:0 (_run) 
 /vs/workbench/parts/debug/node/v8Protocol.ts#79:5 (errorDispatch) 
 /vs/workbench/parts/debug/node/v8Protocol.ts#147:5 (clb) 
 /vs/workbench/parts/debug/node/v8Protocol.ts#114:11 (dispatch) 
 /vs/workbench/parts/debug/node/v8Protocol.ts#69:8 (handleData)

**Comment by isidorn** [comment]
This is coming from the node adapter, forwarding to @weinand

**Comment by isidorn** [comment]
1 year old -> closing
If it was still happneing we would get freshed error telemetry
