### ISSUE TITLE
Auto-expansion of `from` path for ES6 imports

### ISSUE THREAD

**Issue by brianmhunt** [Microsoft/vscode#54963]
- VSCode Version: Insiders
- OS Version: Mac OS X latest

Steps to Reproduce:

1. See https://github.com/Microsoft/vscode/issues/53894

Does this issue occur when all extensions are disabled?: Yes

This issue is just confirmation that the above-noted (and similar) issue continues to occur in VSCode insiders. @mjbvz 

The original issue continues, namely

```js
import { has } from 'lodash-es'
```

automatically becomes

```js
import {
  has
} from '../../../../Library/Caches/typescript/2.9/node_modules/@types/lodash-es'
```

Auto-updating of imports seems dangerously broken in insiders, as the editor exhibits not only this issue, but it does not seem to hesitate to needlessly open hundreds of files in `node_modules` that are unrelated to any imports of any interest and modify them similarly.  Closing the files takes an exceedingly long time because you have to click "don't save" for each.

**Comment by mjbvz** [comment]
Are you TS 3.0+ in your workspace? That path suggests that 2.9 is still active

**Comment by brianmhunt** [comment]
Thanks @mjbvz — That looks like it was indeed the issue.

For folks who happen across this, here's a wrap-up of the solution:

1. Use [Visual Studio Code Insiders](https://code.visualstudio.com/insiders/)
2. Install Typescript 3 with e.g. `yarn add typescript@3.0.0-rc` in the workspace root
3. Run "Select Typescript Version" and select the "Use Workspace Version" (which should be `3.0.0-rc` in `node_modules/typescript/lib`)
