### ISSUE TITLE
Keyboard shortcut for Switch to Inline View

### ISSUE THREAD

**Issue by GandalfSaxe** [Microsoft/vscode#54967]
I know you can toggle it permanently with `"diffEditor.renderSideBySide": false`

It would also be great with a keyboard shortcut to toggle between side-by-side and inline view in git diff.

**Comment by kieferrm** [comment]
@GandalfSaxe, you can assign a keybinding to `toggle.diff.editorMode`. You can also use the editor menu:

![re8cj6r5te](https://user-images.githubusercontent.com/4674940/43173270-e0c15cb0-8f68-11e8-9ea3-d43085d37288.gif)

**Comment by GandalfSaxe** [comment]
Ah perfect. Thanks @kieferrm! I got confused by the three different names used for this same feature:

1. GUI toggle: `Toggle Inline View`
2. Setting switch:  `renderSidebySide`
3. Keyboard toggle: `editorMode`.

You might consider to make the three names more uniform. It's hard to search for, both in settings and especially in keyboard shortcuts, since you just tend to search for whatever it's called in the GUI 🙂
