### ISSUE TITLE
 number is not a function

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#5496]
Issue Id: <b>ff51dcb3-b140-604a-a550-5e79e2b239c5</b><br /><br />*Versions* <br />- 1.0.0-insider<br />-  c1d66b6e47c9da4c768ce7f216da14e7e4ac06ff<br />*Stack* <br />TypeError: number is not a function<br />[/vs/editor/browser/config/elementSizeObserver.ts#L75:9 (changeCallback)](https://github.com/microsoft/vscode/blob/fa6d0f03813dfb9df4589c30121e9fcffa8a8ec8/src/vs/editor/browser/config/elementSizeObserver.ts#L75:9 (changeCallback))<br />[/vs/editor/browser/config/elementSizeObserver.ts#L56:7 (measureReferenceDomElement)](https://github.com/microsoft/vscode/blob/fa6d0f03813dfb9df4589c30121e9fcffa8a8ec8/src/vs/editor/browser/config/elementSizeObserver.ts#L56:7 (measureReferenceDomElement))<br />[/vs/editor/browser/config/configuration.ts#L291:28 (observe)](https://github.com/microsoft/vscode/blob/fa6d0f03813dfb9df4589c30121e9fcffa8a8ec8/src/vs/editor/browser/config/configuration.ts#L291:28 (observe))<br />[/vs/editor/browser/widget/codeEditorWidget.ts#L225:22 (observeReferenceElement)](https://github.com/microsoft/vscode/blob/fa6d0f03813dfb9df4589c30121e9fcffa8a8ec8/src/vs/editor/browser/widget/codeEditorWidget.ts#L225:22 (observeReferenceElement))<br />[/vs/workbench/browser/parts/editor/textEditor.ts#L206:21 (layout)](https://github.com/microsoft/vscode/blob/fa6d0f03813dfb9df4589c30121e9fcffa8a8ec8/src/vs/workbench/browser/parts/editor/textEditor.ts#L206:21 (layout))<br />[/vs/workbench/browser/parts/editor/sideBySideEditorControl.ts#L1503:33 (layout)](https://github.com/microsoft/vscode/blob/fa6d0f03813dfb9df4589c30121e9fcffa8a8ec8/src/vs/workbench/browser/parts/editor/sideBySideEditorControl.ts#L1503:33 (layout))<br />[/vs/workbench/browser/parts/editor/sideBySideEditorControl.ts#L1383:8 (layoutEditor)](https://github.com/microsoft/vscode/blob/fa6d0f03813dfb9df4589c30121e9fcffa8a8ec8/src/vs/workbench/browser/parts/editor/sideBySideEditorControl.ts#L1383:8 (layoutEditor))<br />[/vs/workbench/browser/parts/editor/editorPart.ts#L424:29 (layout)](https://github.com/microsoft/vscode/blob/fa6d0f03813dfb9df4589c30121e9fcffa8a8ec8/src/vs/workbench/browser/parts/editor/editorPart.ts#L424:29 (layout))<br />[/vs/base/common/winjs.base.raw.js#L1826:0 (onComplete)](https://github.com/microsoft/vscode/blob/fa6d0f03813dfb9df4589c30121e9fcffa8a8ec8/src/vs/base/common/winjs.base.raw.js#L1826:0 (onComplete))<br />[/vs/workbench/browser/parts/editor/editorPart.ts#L421:46 (then)](https://github.com/microsoft/vscode/blob/fa6d0f03813dfb9df4589c30121e9fcffa8a8ec8/src/vs/workbench/browser/parts/editor/editorPart.ts#L421:46 (then))<br />

**Comment by alexandrudima** [comment]
I cannot understand how this can happen. This code executes all the time (any time you resize an editor) and `changeCallback` is never written to except in the ctor and the `ElementSizeObserver` is constructed from a single place with a valid callback.

**Comment by alexandrudima** [comment]
@aeschli I do not understand how this stack trace is possible, so there is no attached change.
