### ISSUE TITLE
ESLint Extension not working

### ISSUE THREAD

**Issue by MariahAdams** [Microsoft/vscode#54964]
- VSCode Version: 1.25.1
- OS Version: macOS High Sierra 10.13.6

Steps to Reproduce:

1. Create a simple test file from terminal
2. Add .eslintrc file
3. >npm init --yes
Add the following script to package.json:
"lint": "eslint ."
4. Add test.js
5. Test for semi-colons with `console.log()`
6. >npm run lint

Currently, eslint works from the terminal, but will not automatically detect semi problems in VSCode. I know of another mac user who is having the same problem with eslint semi issues. Also, mysteriously my Bracket Pair Colorizer extension is not working either. 

I have attempted the following:
- restarting VSCode
- uninstalling and reinstalling extensions
- checking my VSCode user settings. I have eslint.options and validate customized for .js and .vue
- I have this line in my .eslintrc under rules: "semi": ["error", "always"]
- checking if eslint was installed globally (it is not); it is locally installed in the project
- trying a .eslintignore file inside a project (nothing happened as far as I can tell)
- checked Google -- was not successful with any of the comments I found on past problems that sounded like this one
- checked if eslint existed in my node_modules (it does); Also tried removing them and running npm i

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Please try filing this issue against the [eslint extension](https://github.com/Microsoft/vscode-eslint/issues) or asking on stackoverflow
