### ISSUE TITLE
entering a string for a switch parameter causes powershell to crash

### ISSUE THREAD

**Issue by andy2002a** [Microsoft/vscode#54962]
- VSCode Version: 1.25.1
- OS Version: Server 2016 1607

Steps to Reproduce:

1.Run the command block below
2.Enter random text when prompted in the console
3.You get an error saying that powershell crashed

If you launch the same code in the ISE you will get an error in the console saying that the switch param will not accept a string. However, the shell will not crash.

```
[cmdletbinding()]
param(
    [Parameter(Mandatory = $true, HelpMessage = 'test')]
    [Switch]$ServerName,

    [Parameter(Mandatory = $true, HelpMessage = 'test')]
    [Switch]$Server2Name

)#End cmdletbinding
```

Does this issue occur when all extensions are disabled?: Yes/No
No, but only because the powershell extension does not load

**Comment by weinand** [comment]
Please file this against the PowerShell extension.
