### ISSUE TITLE
"Workspace Recommendations" view text cut off

### ISSUE THREAD

**Issue by JacksonKearl** [Microsoft/vscode#54973]
on insiders
![image](https://user-images.githubusercontent.com/8586769/43171375-a238942c-8f5e-11e8-9cee-3451539cb14d.png)

**Comment by JacksonKearl** [comment]
@ramya-rao-a @sandy081 Do you know of any recent changes to relevant CSS? If not I'll take a look

**Comment by JacksonKearl** [comment]
Good chance it was this (47e4319871cafd9bc25b641e855672d899233226) commit.

**Comment by sandy081** [comment]
@JacksonKearl I suppose this https://github.com/Microsoft/vscode/issues/54943 is a duplicate.

**Comment by JacksonKearl** [comment]
@sandy081 Yes that was part of it
