### ISSUE TITLE
vscode can not index functions in PHP files

### ISSUE THREAD

**Issue by biij5698** [Microsoft/vscode#5497]
vscode can index functions like javascript But In PHP files it not work("Ctrl + Shift + O" and "Ctrl + T")

**Comment by herbertpimentel** [comment]
this will be awesome. let us know if we can help anyway.

**Comment by zagreusinoz** [comment]
Agreed, would be good.

**Comment by roblourens** [comment]
VS Code doesn't have complete PHP support out of the box, but you can try one of the extensions that now offer this.
