### ISSUE TITLE
Add context information to SignatureHelpProvider

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#54972]
**Problem**
Signature help providers sometimes need more information to determine which signature to return. https://github.com/Microsoft/TypeScript/issues/1150 for example discusses how typing a comma inside of a string could mistakenly triggering TypeScript signature help. Using the current VS Code api, a signature help provider cannot easily distinguish the cases:

- User just typed a comma in a string, triggering signature help.
- Cursor is after a comma in a string and the user manually requested signature help.

**Proposal**
Add a `context` when requesting signature help. This context should supply at least the following:

- The character that triggered signature help (optional)
- Why signature help was triggered (manual, typing, retrigger, ...)

This proposal is based on what typescript [has implemented](https://github.com/Microsoft/TypeScript/pull/24915/) which in turn is based on [rosyln](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/SignatureHelp/SignatureHelpTriggerInfo.cs,2e9e71d9d0082b2d)

`retriggger` presents one additional complication. This is needed for nested function calls and would be invoked when you type a closing brace with signature help already showing, such as:

```js
console.log(1, Math.max(1, 2)|   )
```

when the user has just typed `)`. See Daniel's comment for more context: https://github.com/Microsoft/TypeScript/issues/1150#issuecomment-401158832

**Comment by Gama11** [comment]
Same as https://github.com/Microsoft/vscode/issues/34737 / maybe one should be closed?

**Comment by mjbvz** [comment]
Prototype PR up at #58135

I'd like feedback [on the proposed api](https://github.com/Microsoft/vscode/pull/58135/files#diff-4878e8b25d41f2ab7c2715852b1b97aaR816) from a few other language authors to make sure we design an api that will work well for a variety of languages. /cc @DonJayamanne @DustinCampbell @DanTup @ramya-rao-a @aeschli @fbricon @DanielRosenwasser

Some starting questions:

- Does your extension / language server have a need for this extra context when computing signature help? 
- Are there other pieces of context beyond what is currently proposed that would be helpful?
- Any concerns about the trigger reasons?

Also @dbaeumer heads-up for language server protocol

**Comment by DanTup** [comment]
Whoops - I hadn't noticed this was missing (and require it to implement [automatic triggering](https://github.com/dart-lang/sdk/issues/34241) in a way that doesn't annoy users).

The proposal looks good for me, though we'd planned on not requiring the specific character in the API to the server but rather just whether it was automatically triggered (and if not, only return data of the offset is in a position that is the start of an argument).

**Comment by mjbvz** [comment]
Reopening :)

API is still in-design but I've merged in the current proposal so that we can get some real world testing of how the current design works for javascript and typescript. Please continue to share feedback here

**Comment by KamasamaK** [comment]
> Are there other pieces of context beyond what is currently proposed that would be helpful?

Yes, the client value of `activeSignature`. See #33413

**Comment by DanTup** [comment]
Is this being considered for LSP too?

**Comment by dbaeumer** [comment]
Yes, this will very likely make its way into LSP as well.
