### ISSUE TITLE
Why region commentin can't collapse

### ISSUE THREAD

**Issue by qdljc** [Microsoft/vscode#54978]
Issue Type: <b>Bug</b>

region commenting feature/ Collapse code by region function not available。

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.92GB (2.95GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|57%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
gc-excelviewer|Gra|2.1.24
vscode-language-pack-zh-hans|MS-|1.25.3
PowerShell|ms-|1.8.1

</details>

**Comment by tommymaynard** [comment]
I can attest that from 1.25 to 1.25.1 that regions broke when using PowerShell.

**Comment by kieferrm** [comment]
Same for TypeScript. When you enable indentation based folding (`editor.foldingStrategy`) in settings, region folding works.

**Comment by aeschli** [comment]
@kieferrm Please file a separate bug against typescript (the implementation now comes from languages folding provider), ideally with a sample, as I see it working for typescript.

**Comment by aeschli** [comment]
@qdljc I assume you use the powershell extension. The issue is https://github.com/PowerShell/vscode-powershell/issues/1447

**Comment by kieferrm** [comment]
@aeschli given that we saw the same issue across different languages made me assume there is a language independent issue.
