### ISSUE TITLE
random scroll down and random paste of codes

### ISSUE THREAD

**Issue by acebesmonte** [Microsoft/vscode#54985]
- VSCode Version:1.25.1
- OS Version: ubuntu 18

Steps to Reproduce:

1. random times, upon alt tab to other app then going back, the monitor is scrolled down upto at least 6inches down.
2. random times that its pasting code from what i (ctrl+C). im sure i didnt pressed (ctrl+V)

Does this issue occur when all extensions are disabled?: Yes/No
NO. i didnt disable it. I'll try again while extensions are disabled.

**Comment by kieferrm** [comment]
@acebesmonte same as #54072?
