### ISSUE TITLE
Vscode running low perf

### ISSUE THREAD

**Issue by Rokuo** [Microsoft/vscode#54984]
Issue Type: <b>Performance Issue</b>

It happen since i've installed cinamon, i'm on fedora 27 and now my vscode have a low perf like ram, freezing sometimes when i'm typing.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:40:20.190Z)
OS version: Linux x64 4.16.11-100.fc26.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 1056)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|7.69GB (0.63GB free)|
|Process Argv|/usr/share/code/code .|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    4	   118	 20699	code main
    0	    31	 20702	   zygote
    0	   252	 20740	     window (settings.json - intranet - Visual Studio Code)
    0	    47	 20774	       terminal
    0	     0	 20781	         /usr/bin/fish
    0	    87	 20794	       extensionHost
    0	   150	 20896	         electron_node electronForkStart.js tsserver.js 
    6	    63	 20929	           electron_node typingsInstaller.js tsserver.js typesMap.js 
    0	   102	 20898	         electron_node htmlServerMain.js 
    0	    71	 21045	         electron_node jsonServerMain.js 
    0	    55	 20798	       watcherService
    0	    47	 20894	       searchService
    0	    87	 20826	     shared-process
    4	    94	 21270	     window (Issue Reporter)
    0	   118	 20727	   gpu-process
    0	     0	 21292	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (settings.json - intranet - Visual Studio Code)
|    Folder (intranet): 1137 files
|      File types: png(293) js(280) pdf(149) scss(77) css(65) jpg(55) html(40)
|                  json(32) gif(29) hbs(18)
|      Conf files: package.json(1) settings.json(1);
```

</details>
<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
solargraph|cas|0.17.6
path-intellisense|chr|1.4.2
docker-explorer|for|0.1.6
node-module-intellisense|lei|1.5.0
cpptools|ms-|0.17.7
epitech-c-cpp-headers|nic|1.9.5
vscode-docker|Pet|0.0.27
Ruby|reb|0.18.0
selectline-statusbar|tom|0.0.2
JavaScriptSnippets|xab|1.7.0

</details>

**Comment by Tyriar** [comment]
Try closing all windows and launching via a terminal with the following:

- `code --disable-extensions`
- `code --disable-extensions --disable-gpu`
- `code --disable-extensions --ignore-gpu-blacklist`

Let me know if any of those improve the experience.

---

On RAM, it doesn't look like VS code is taking up *that* much, a lot of it is caused from built-in extensions providing the language services which is expected.

**Comment by Rokuo** [comment]
Well, i had cinnamon installed on my pc, and it seems that the cinnamon and vscode had a conflict, because before installing cinnamon i had a clear vs code.
I've removed cinnamon and re-installed it, and vs code's back to normal ! 
sorry for the disturbance !
