### ISSUE TITLE
Hover hides when start of anchoring range is scrolled outside viewport

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#54989]
* have a long link
* hover over the link and notice the popup
* horizontally scroll so that link start isn't in the viewport anymore
* hover over the link
* :bug: the popup shortly shows and then hides

![jul-25-2018 09-45-14](https://user-images.githubusercontent.com/1794099/43186668-a93f21be-8fef-11e8-9463-7c9d9458e085.gif)

**Comment by eamodio** [comment]
Wow, didn't realize this one was so old, been running into this a lot lately (as it affects all hovers)

**Comment by alexandrudima** [comment]
Duplicate of #51794
