### ISSUE TITLE
Normalize uri-paths before attempting to open them?

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#54990]
re #54863

* run this: `code --folder-uri remotehub://github.com/OmniSharp/omnisharp-roslyn/src/../src/OmniSharp.Roslyn/ --folder-uri remotehub://github.com/OmniSharp/omnisharp-roslyn/src/OmniSharp.Roslyn/`
* the first folder (which the same as the latter) won't load

We should consider calling `path.posix.normalize` on the path-component of user-provided URIs (our URI implementation doesn't normalise paths) before treating them as good.

**Comment by jrieken** [comment]
Same is true for trailing slashes (won't be covered by normalise) 

```
jrieken:~/Code/vscode$ code --folder-uri remotehub://github.com/OmniSharp/omnisharp-roslyn/ --new-window
jrieken:~/Code/vscode$ code --folder-uri remotehub://github.com/OmniSharp/omnisharp-roslyn --new-window
```

**Comment by jrieken** [comment]
verified in code

**Comment by dineshmaity** [comment]
Please,  Stop sending mestate at this email.  As  I do not want to engage in your project.
