### ISSUE TITLE
Showing loading indication in explorer

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#54991]
re #54863

* run `code --folder-uri remotehub://github.com/OmniSharp/omnisharp-roslyn/src/`
* the workbench and explorer show quickly
* the explorer is empty for a while and doesn't show that it is fetching data

**Comment by isidorn** [comment]
I see some loading, though it does not start asap, there is a slight delay. Do you see the same?
This seems to be coming from a manually delay set [here](https://github.com/Microsoft/vscode/blob/e4b7417e7118df59f715c40d55bf026c1f257a31/src/vs/workbench/parts/files/electron-browser/views/explorerView.ts#L793)
Looking at the comments that is done for the most common use case where we do not want to show we are slow. Correct? @bpasero 

![startup](https://user-images.githubusercontent.com/1926584/43607908-012545c8-96a0-11e8-8769-5c7db845e3b8.gif)

**Comment by bpasero** [comment]
@isidorn yeah maybe we can relax that condition if we now it is a remote file system that is slow?

**Comment by isidorn** [comment]
I have cut down the delay to show progress from 3200ms to 1200ms. This works nicely on my machine as for local files it does not show progress and still shows it for remote files.
I did not want to cut down the delay more as it might cause that we show progress too much for local file systems.

**Comment by jrieken** [comment]
Verified in code - time will tell how this feels in the real world
