### ISSUE TITLE
[feature request] New workspace command with a full finder navigation.

### ISSUE THREAD

**Issue by QuantumInformation** [Microsoft/vscode#54998]
It would nice to have a New workspace command with a full finder navigation.

Currently, I have to use `save the workspace as`, and the only folders I see are favourites so have to manually move it after.

<img width="308" alt="screen shot 2018-07-25 at 09 27 22" src="https://user-images.githubusercontent.com/216566/43188855-1d7e4026-8fed-11e8-8bab-3337f46dd049.png">

**Comment by kieferrm** [comment]
This the macOS default Save dialog. You get the same when you, for example, use `Save As...` in Preview. You can navigate to any accessible folder on any mount using this dialog. No need to move the file afterwards.

**Comment by QuantumInformation** [comment]
What about new workspace?
