### ISSUE TITLE
Dock context menu broken?

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#54992]
#54863

After playing with `--folder-uri` parameter my Dock context menu look weird: E.g. it has mixed 'New Window' with a file entry and it has an empty bucket atop.

<img width="314" alt="screen shot 2018-07-25 at 09 47 36" src="https://user-images.githubusercontent.com/1794099/43187412-99f2d280-8ff1-11e8-910f-a469f06242e6.png">
<img width="373" alt="screen shot 2018-07-25 at 09 59 11" src="https://user-images.githubusercontent.com/1794099/43187413-9a0d6e38-8ff1-11e8-8871-b59f265b69db.png">

**Comment by sandy081** [comment]
I know the empty section is caused because of the non file schema folder uri, but I have no clue why it happens and why `New Window` entry got messed up.


I would need insights from @bpasero as he knows well about this. Until then I will not add non file schema folder uris to Mac dock recent list.

**Comment by bpasero** [comment]
https://github.com/electron/electron/issues/11159

**Comment by sandy081** [comment]
@bpasero Can I revert the temp fix now?

**Comment by bpasero** [comment]
@sandy081 yeah I was wondering what your change is actually trying to achieve?

**Comment by sandy081** [comment]
Temporary fix I added was not to add non-file schema URIs to the Dock recent list so that these empty sections are not shown. Given that this issue is fixed, I can revert that.

**Comment by bpasero** [comment]
@sandy081 I do not think that the macOS dock menu supports entries that are not file paths, so I think we should filter them. In other words, do not add URIs to native areas (Windows JumpList, macOS dock) etc.

**Comment by sandy081** [comment]
I see. 

I have a question, I see non file entries in the macOS dock menu in other electron applications like slack. Do not know what kind of entries are they

![image](https://user-images.githubusercontent.com/10746682/44081093-372dc62e-9fae-11e8-9756-079689962e1c.png)

Also, while testing Windows JumpList, non file paths were working.

**Comment by bpasero** [comment]
@sandy081 yeah good point, we do that too: https://github.com/Microsoft/vscode/blob/920defc6a68980cbe55ba06b9e609f716d606a84/src/vs/code/electron-main/menus.ts#L302

I was more referring to the [`app.addRecentDocument`](https://github.com/electron/electron/blob/master/docs/api/app.md#appaddrecentdocumentpath-macos-windows) API that only supports file paths as far as I know. We use the same on Windows, so I think we should filter there too.

**Comment by jrieken** [comment]
Hm, it's now broken in different ways...
