### ISSUE TITLE
Go to Definition doesn't work in Diff View

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#5499]
- VSCode Version: 1.0.0
- OS Version: Mac OSX

Steps to Reproduce:

1. Open any git repository
2. Make changes to a file
3. Navigate to Git pane and pick the changed file
4. On the left side pane, right click on any function as below
![image](https://cloud.githubusercontent.com/assets/876920/14636789/1de4cbde-0660-11e6-8c5f-e7d4aa8a4364.png)
5. `Go to Definition` doesn't work, nothing happens. While if you do the same thing on the right side pane, it works as charm.

We know that the code is already changed and Intellisense won't work for original version (the left side one), should we hide the context menu instead of confusing users with the not-working `Got to Definition` or `Peek Definition`?

**Comment by dbaeumer** [comment]
IMO we should disable language feature for the left hand side of a diff viewer? @jrieken what is your take.

**Comment by jrieken** [comment]
The actions should be disabled when there no providers for that file. To my knowledge we register the left hand side with some `git-index`-scheme, so TypeScript and no one else is offering a provider - @dbaeumer given TypeScript registers like so `{ scheme: file, language: typescript}`. I'll investigate...

**Comment by jrieken** [comment]
@dbaeumer The issue is the TypeScript extension registers for typescript models not only for those it can reason about - files on disk. Instead of the simple document selector it should use one that selects files that are associated to _typescript_ AND that sit on disk. The context menu of the left hand side editor will then honour that.

**Comment by jrieken** [comment]
This is how it looks for C#/Omnisharp which registers like this: https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/omnisharpMain.ts#L39

![screen shot 2016-04-19 at 16 21 03](https://cloud.githubusercontent.com/assets/1794099/14642437/bbab8968-064a-11e6-8069-3a069e896d64.png)

**Comment by dbaeumer** [comment]
@jrieken makes sense.

**Comment by dbaeumer** [comment]
Disabled the language features for the left hand side of a diff.
