### ISSUE TITLE
Add option to disable multi-select  support in tree

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#55000]
Testing #54935

- In breadcrumb tree, I am able to do multi select. If there is no special treatment for multi-select it should be disabled

**Comment by jrieken** [comment]
@isidorn Do you happen to know if the tree can be configured to not support multi-select?

**Comment by isidorn** [comment]
Seems similar to https://github.com/Microsoft/vscode/issues/44508

Currently list has multi select support [here](https://github.com/Microsoft/vscode/blob/d63937a452f5dd4291625bfd5e8b189206a0feb3/src/vs/base/browser/ui/list/listWidget.ts#L674)
However the old tree does not.
The new tree which is built on top of the list has support for it.

If you are really passionate about it you could override it in your tree controller.

**Comment by jrieken** [comment]
This works now
