### ISSUE TITLE
JSON completion extensibility

### ISSUE THREAD

**Issue by nadako** [Microsoft/vscode#5500]
I love how VS Code completes e.g. npm library names when editing `package.json`, that's really great!
However could this be more pluggable, so a vscode extension could provide own `IJSONWorkerContribution`? I'd be interested in implementing one similar to NPM handler.

**Comment by aeschli** [comment]
If you look at the latest in head, the PackageJSONContribution is now part of the JavaScript extension.
It is used by the `JSONCompletionItemProvider` in `javascript/src/features/jsonContributions.ts` and is a regular completion item processor. All the JSON parsing logic is in a new node_module `jsonc-parser`.

The idea is that you do it the same way. You can basically copy jsonContributions.ts to your extension and feed it with your handler. Of course you can simplify this also and just have single CompletionItemProvider doing it all together.

**Comment by nadako** [comment]
Nice, thanks!
