### ISSUE TITLE
Support find and filter in breadcrumbs picker

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#55004]
Testing #54935

- Open `extensionManagement.ts` file
- Open its symbols outline tree from breadcrumbs
- Type `version`

Expected to see only the sub tree that has matches. But it shows sibling that does not have matches. For example siblings of `IExtensionManifest` symbol.

![image](https://user-images.githubusercontent.com/10746682/43190311-05435af8-8ff9-11e8-86e6-6af7e55550ab.png)

Outline view filters them correctly

![image](https://user-images.githubusercontent.com/10746682/43190360-27d1b1b4-8ff9-11e8-9271-b2f7dde8297b.png)

**Comment by jrieken** [comment]
It's 'Find' not 'Filter' - in the outline view the default is also 'Find' but you might have this set to 'Filter'

**Comment by sandy081** [comment]
Right, Its Filter in Outline

**Comment by ris58h** [comment]
From my point of view it would be useful to have a toggle button (find/filter) right in the picker's input field. Of course there should be a shortcut for it.

Example:
![breadcrumbs-find-toggled](https://user-images.githubusercontent.com/511242/44272582-f57f3d80-a245-11e8-96f3-4c01fd84587d.png)
![breadcrumbs-filter-toggled](https://user-images.githubusercontent.com/511242/44272589-f7e19780-a245-11e8-8f0d-79050ba15773.png)
 
There are such (toggle) buttons in the Search View: Match Case, Match Whole Word, Use Regular Expression.

**Comment by jrieken** [comment]
This is implemented but impacted by https://github.com/Microsoft/vscode/issues/57089

**Comment by jrieken** [comment]
The implementation and tree behaviours aren't good. Removed the option for now and moving this to September.

**Comment by jrieken** [comment]
this is now like all other trees
