### ISSUE TITLE
Splash: gentle ux to notify user splash screen is not broken rendering

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#55003]
Refs: #54937

Currently our splash screen is very minimalistic and it can easily be confused by rendering being broken. I personally really like how Slack just adds a gentle ux so it is immediatly clear to the user that the whole thing is acutally loading.
Can we be inspired by them and add a similar notion in the sidebar and in the editor area. The goal is that the user does not get puzled if rendering is broken but gets the clear indication that vscode is starting up

![screen shot 2018-07-25 at 10 50 31](https://user-images.githubusercontent.com/1926584/43190201-cb2206a8-8ff8-11e8-882c-038ec5827960.png)

**Comment by jrieken** [comment]
Not a fan - the goal should be to be able to render the UI as fast as possible and we should move more into the pre-start phase, e.g. (disabled) buttons and titles

**Comment by isidorn** [comment]
Sure rendering the UI as fast as possible makes sense. But not sure how adding some ux will slow things down and affect this.
The only downside of this approach that I see is that there can be a "mini flash" when content changes, but due to that we should use light colors.

**Comment by jrieken** [comment]
no action planed
