### ISSUE TITLE
Custom styled menu/title unavailable in zen mode

### ISSUE THREAD

**Issue by DeeHants** [Microsoft/vscode#55002]
Issue Type: <b>Bug</b>

When zen mode is enabled, the menu bar is hidden.
Pressing alt will then show it again, allowing access to options, including "exit zen mode".
When the custom menu styling is enabled, this behaviour no longer works, and there is no other apparent way of bringing up the menu.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:11.471Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2294)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (1.02GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.0.2
vscode-eslint|dba|1.4.12
vscode-npm-script|eg2|0.3.5
format-php|Kas|1.1.2
vscode-sshfs|Kel|1.9.2
eml|lei|0.2.2
php-docblocker|nei|1.6.0
vscode-format|rya|0.0.6
dot|Ste|0.0.1
code-spell-checker|str|1.6.10
php-docblock-generator|vin|0.0.1
vscode-todo-highlight|way|1.0.4
highlight-trailing-white-spaces|yba|0.0.2

</details>

**Comment by DeeHants** [comment]
Can someone add the workbench-menu label please?

**Comment by kieferrm** [comment]
As a workaround you can go through the command pallet <kbd>Ctrl+Shift+P</kbd> or use the keyboard shortcut.

**Comment by sbatten** [comment]
related to #52954

**Comment by sbatten** [comment]
resolved by  #55100
