### ISSUE TITLE
Should --disable-extension imply --new-window?

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#55013]
Testing #54865

Using `--disable-extension` when there already is a window open currently just focuses that other window. It would make sense to always open a new window.

**Comment by sandy081** [comment]
Default is to open in the existing window. There are options to open a new window 

`'-n, --new-window': localize('newWindow', "Force to open a new window."),`

**Comment by chrmarti** [comment]
The default is clearly not what I want when I specify `--disable-extension`. 🤔

**Comment by sandy081** [comment]
But why do you want to open in a new window as default?

**Comment by chrmarti** [comment]
I'd expect `--disable-extension` to have some effect. Currently it just focuses the last window and does not disable the extension. Reloading the last window might be too intrusive, so I thought opening a new window with the extension disabled would make sense.

**Comment by sandy081** [comment]
@chrmarti So you do this `code-insiders --disable-extension a.b` without giving anything to open?

**Comment by chrmarti** [comment]
Correct.

**Comment by sandy081** [comment]
@chrmarti Is not this same behaviour when you do `--disable-extensions` ?

**Comment by chrmarti** [comment]
That could be improved too. Anyway not a big deal. Feel free to close.

**Comment by sandy081** [comment]
I will close it and see if more users ask for the same
