### ISSUE TITLE
Startup now feels slower?

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#55010]
Refs: #54937

Not sure if related but creating this issue out of concern that the percieved startup with the new splash screen became worse. 
Comparing built vscode the difference is not noticable but I think I notice the difference when running vscode out of source. Also I have a fast machine, we should compare built versions on some dog-slow machine.

Could we do some measuring just that we are sure that we are not slowing things down by going to storage / adding html elements on startup?

**Comment by jrieken** [comment]
During development I have measure between 15 and 20ms, mostly due to loading the vscode-uri node module. I'll add perf marks so that everyone can check - accessing local storage might be the bottleneck for heavily used installations.

**Comment by jrieken** [comment]
@isidorn I have pushed a change that adds perf marks. Out of dev or when built run `Dev: Startup Performance` and see at the bottom of the console something like this 'willShowPartsSplash' and 'didShowPartsSplash'

**Comment by isidorn** [comment]
It is 23 ms on my mac.
It is 12 ms on my windows
And 10ms on linux. For some reason it is slowest on mac.

**Comment by jrieken** [comment]
Closing as this wasn't reported anywhere else
