### ISSUE TITLE
No gesture to reveal an item without closing the picker

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#55014]
Testing #54935

I can open the breadcrumb view and show the outline. I can navigate through the outline with arrow keys and I can press Enter to close the outline and jump to a location.

It would be helpful if another key is offered, like spacebar where the outline will maintain focus and the editor is scrolled (without moving cursor) to the symbol.

**Comment by jrieken** [comment]
It could also work like quick outline where the focused element in highlighted and scrolled into the view port

**Comment by jrieken** [comment]
I have actually implemented that as #56983 today. Closing as dupe
