### ISSUE TITLE
Side bar size should not jump in splash screen when it is changed in a different window

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#55017]
Testing #54937

- Open two windows A and B
- Change the side bar width in window B
- Reload window A

Splash screen is loaded with previous side bar size and gets adjusted to new size. Splash screen can be smart to show the new side bar size ?

**Comment by jrieken** [comment]
this is fixed via #55033

**Comment by jrieken** [comment]
Actually needed one more... Now the parts splash data is saved when the layout changes. That should make it work much better when using two windows.
