### ISSUE TITLE
Installed extension that is still being verified

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#55028]
Issue Type: <b>Bug</b>

Testing #54862 

I was able to install while verification was still running:
![image](https://user-images.githubusercontent.com/9205389/43195639-f636434c-9005-11e8-8e4b-d793646c78e9.png)

VS Code version: Code - Insiders 1.26.0-insider (5fae91d61f12726e149fe5baed342eac2fbf8f88, 2018-07-25T01:56:56.548Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.14GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|22%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
999-pack1|chr|0.12.0
regex|chr|0.2.0
ssh|chr|0.0.4
vscode-eslint|dba|1.4.12
Spot|der|0.4.0
ghlink|dt|1.0.2
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.34
rest-client|hum|0.19.0
vscode-azureappservice|ms-|0.9.0
vscode-azurefunctions|ms-|0.10.0
vscode-cosmosdb|ms-|0.8.0
azure-account|ms-|0.4.2
azurecli|ms-|0.4.2
github-issues-prs|ms-|0.9.0
PowerShell|ms-|1.8.1
debugger-for-chrome|msj|4.8.2
vscode-docker|Pet|0.0.27
vscode-versionlens|pfl|0.21.1
vscode-open-in-github|sys|1.7.0
azure-iot-toolkit|vsc|1.1.0

</details>

**Comment by sandy081** [comment]
Ah you are publishing from a web page ?

@viradhamMS @pkuma-msft

Looks like new extension version is available in Marketplace to install while it is still being verified. Is it a bug in Marketplace?

**Comment by chrmarti** [comment]
I published using vsce 1.44.0.

**Comment by pkuma-msft** [comment]
Hi @chrmarti .. thanks for reporting this. It is possible that even though the extension was validated the UX wasn't updated to reflect the status. Are you able to repro this always? 
I will look into it and get back with more details.

**Comment by pkuma-msft** [comment]
Ok, I looked at our telemetry and that confirms that it is a UX bug. Here are the details:
Extension was validated at: 2018-07-25 10:23:18.6768851 (all times in UTC)
VS Code installation at: 2018-07-25 10:25:12.8932334

So when you installed the extension, it was successfully validated but the UX wasn't showing that for some reason. 

Did it stay like that for a long time? I see that you pushed more updates to the extension, I'm assuming you didn't see this issue during those updates?
