### ISSUE TITLE
Typing in breadcrumbs jumps around even if the same element is selected.

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#55020]
Testing #54935

* open `editorCommon`
* type `deco`..
* then *confirm* by typing `r` (note the selection jumped??)
* then type `a` (note we are back to the IContentDecoration)... why did we jump in the previous step?

![kapture 2018-07-25 at 11 36 18](https://user-images.githubusercontent.com/5047891/43192920-ffa3b254-8ffe-11e8-93c1-bf7c97054fdb.gif)

**Comment by jrieken** [comment]
The idea is that the best match is being revealed/selected but it doesn't seem to work well ;-)
