### ISSUE TITLE
Problems: light bulb and error should be two icons

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#55021]
Refs: #54861

The current light bulb next to the red error is practicaly invisible.
I suggest to increase the size of the light bulb such that it can actualy be seen.
I like that the red error is the main thing in this icon, but the light bulb should be more distunigishable, either by size or by some border lines or contrast.
An alternative is to render two icons next to one another.

![screen shot 2018-07-25 at 11 41 47](https://user-images.githubusercontent.com/1926584/43193303-f75f4d3c-8fff-11e8-8a0f-3ab1c72b5be4.png)

**Comment by isidorn** [comment]
Actually I like rendering two icons because then we could also trigger context menu on light bulb icon click - would be consistent with editor light bulb experience and would be more discoverable.

**Comment by sandy081** [comment]
@isidorn I am discussing this with @misolori and we agreed upon showing two icons. Light bulb icon will be shown at the end just like an action.

**Comment by isidorn** [comment]
That makes sense. The only downside of that is that the lightbulb will be disconnected due to the large horizontal size of the problem panel.
However I prefer that to the current solution.

**Comment by sandy081** [comment]
Yeah position is far away, I can also try placing it at the very end of the message.

**Comment by isidorn** [comment]
Experiment with both and whatever seems better for you works for me.
I would also consider putting it next to the error icon.

**Comment by sandy081** [comment]
Putting it next to the error icon might need to accommodate some space for it. If an entry does not have quick fixes then it will be empty if not, it will be misaligned.

**Comment by isidorn** [comment]
I would expect that space to be empty if entry does not have quick fixes. Would have to see it to decide if this is any good.
Though leaving up to you to decide

**Comment by sandy081** [comment]
Check out this

![kapture 2018-07-26 at 0 30 29](https://user-images.githubusercontent.com/10746682/43231123-4dd9cc58-906b-11e8-8e8e-64f95aeb480c.gif)

**Comment by isidorn** [comment]
Much better. I guess it also shows on mouse hover.

**Comment by sandy081** [comment]
Yes
