### ISSUE TITLE
[feature request] Add a new channel for update.channel

### ISSUE THREAD

**Issue by HRK44** [Microsoft/vscode#55027]
I always install vscode through ``apt install``, but I keep receiving the message that a new update is available when it's not yet on the apt repo.

Is it possible to add a new option for ``update.channel`` which would be ``apt`` so that it would notify the user when the new update is available on the public ubuntu repo instead of the website?

I've posted a question on stackoverflow as well : https://stackoverflow.com/questions/51205831/how-do-i-tie-vscode-update-notification-to-apt-update

Thanks

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/21651
