### ISSUE TITLE
Allow to continue debug when extension host restarts

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#55025]
Issue Type: <b>Bug</b>

Testing #54865

Using `_workbench.enterWorkspace` with extensions that are already disabled (or non-existing ones), such that it does not reload the window, shows the `Extension host did not start in 10  seconds` message.

VS Code version: Code - Insiders 1.26.0-insider (5fae91d61f12726e149fe5baed342eac2fbf8f88, 2018-07-25T01:56:56.548Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (0.46GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|22%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
regex|chr|0.2.0
ssh|chr|0.0.4
vscode-eslint|dba|1.4.12
Spot|der|0.4.0
ghlink|dt|1.0.2
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.34
rest-client|hum|0.19.0
vscode-azureappservice|ms-|0.9.0
vscode-azurefunctions|ms-|0.10.0
vscode-cosmosdb|ms-|0.8.0
azure-account|ms-|0.4.2
azurecli|ms-|0.4.2
github-issues-prs|ms-|0.9.0
PowerShell|ms-|1.8.1
debugger-for-chrome|msj|4.8.2
vscode-docker|Pet|0.0.27
vscode-versionlens|pfl|0.21.1
vscode-open-in-github|sys|1.7.0
azure-iot-toolkit|vsc|1.1.0

</details>

**Comment by sandy081** [comment]
@chrmarti Can you please provide me your set up of extensions (installed, disabled) and the code you used to run this command?

**Comment by chrmarti** [comment]
It reproduces without any extensions installed and also with just '' installed but disabled:
```ts
export function activate(context: vscode.ExtensionContext) {

    let disposable = vscode.commands.registerCommand('extension.sayHello123', async () => {
        const sampleWorkspace = '/Users/chrmarti/Development/repos/test.code-workspace';
        vscode.commands.executeCommand('_workbench.enterWorkspace', vscode.Uri.file(`${sampleWorkspace}`), ['jerryhong.autofilename']);
    });

    context.subscriptions.push(disposable);
}
```

(Even when that workspace is already open, maybe that should be a noop.)

**Comment by sandy081** [comment]
@chrmarti I guess you are doing this by launching extension host. When the extension host is being debugged, restarting the extension host by calling the method looks to me problematic. @alexandrudima @weinand Any insights on this?

@chrmarti Can you please try this by installing the extension that has this command and running the command?

**Comment by alexandrudima** [comment]
I'm sorry, I don't know about the `_workbench.enterWorkspace` command. The 10s message might be shown if the extension host is launched with `--inspect-brk` i.e. if it breaks on the first statement and if the debugger does not connect to it.

**Comment by sandy081** [comment]
I think you can ignore `_workbench.enterWorkspace` command. 

This happens when Extension host is launched by our Debugger (Extension development) and extension host is requested to restart during this session using above command.

**Comment by alexandrudima** [comment]
I don't know, perhaps the command `_workbench.enterWorkspace` should let the debugger know that it is about to relaunch the extension host.

How else should the debugger know that it needs to connect to a new extension host process...

**Comment by bpasero** [comment]
This should work fine now.

**Comment by weinand** [comment]
@isidorn this worked fine in stable but is now broken in the latest Insider (which contains your Session refactoring)

**Comment by weinand** [comment]
I can easily reproduce this with a the Hello World extension and this activate function:
```
function activate(context) {
    let disposable = vscode.commands.registerCommand('extension.sayHello', function () {
        vscode.commands.executeCommand('_workbench.enterWorkspace', vscode.Uri.file('/Users/weinand/MS/Projects/Scenarios/test.code-workspace')).then(_ => {
            console.log("ok");
        }, e => {
            console.log("error: " + e);
        });
     });
    context.subscriptions.push(disposable);
}
```
