### ISSUE TITLE
Meta settings icon

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#55030]
As already mentioned in the UX call I do not like the new settings icon inside settings.
I feel like this should be elipses instead and this would align better with other places in vscode where we use elipses and this settings wrench.

fyi @roblourens 

![screen shot 2018-07-25 at 12 33 02](https://user-images.githubusercontent.com/1926584/43195988-e311aa08-9006-11e8-9c2b-3b5a3de9e6e7.png)

**Comment by misolori** [comment]
So the reasoning we decided to go with the gear was that the ellipsis icon isn't well suited for a notification badge (it would be dot dot dot and a notification dot). We also use the gear in other places like the debug viewlet, extensions, files/filter exclude. Here's a comparison of the two:

![image](https://user-images.githubusercontent.com/35271042/43211310-164beae4-8fe6-11e8-9f55-ee172653add4.png)

Curious to hear your thoughts between the two. Personally, I'm fine using either but thought the gear icon played better with the notifcation.

**Comment by isidorn** [comment]
Yes the gear icon plays better with the dot.
4 dots do not make much sense.

I guess it is fine in the end.
My concernt was that we are overloading the gear icon with too manu dfferent meaning in different places which do not always mean "configure". Let's close for now, and see if anybody else has conernse
