### ISSUE TITLE
Settings UI: create some mark near settings which has been override

### ISSUE THREAD

**Issue by myxo** [Microsoft/vscode#55037]
When you scroll "default user settings" page it is hard to tell if some partucular setting is already override by "user settings" page. 
It would be nice to see some mark which tell us that this settings has been override. Ideally when user points to this mark there should be some pop up window with value of setting from "user settings" page.

It might look something like this. Here red dot means that this setting has been override (don't insist on red dot, this is just an example).

![38](https://user-images.githubusercontent.com/2719353/43195803-c825b10a-900e-11e8-831b-0f9573b370fa.png)

In this case pen icon may have same color on this king of settings.
![39](https://user-images.githubusercontent.com/2719353/43196097-8e15d778-900f-11e8-8df4-ac39687b3d72.png)

**Comment by kieferrm** [comment]
We address this issue in the new settings editor. Pls see #50249.
