### ISSUE TITLE
Splash data should be stored globally

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#55033]
Refs #54937

As already mentioned in the PR

You keep all these dimensions per Workspace, however most of them we keep globaly and thus a glitch can happen.
Example:

Have a sidebar very small in workspace A
Open workspace B and have a sidebar very large
Open workspace A again, the splash thinks the sidebar is small, even though it is large since we keep it globaly

IMHO: for the most common use case it would work better if we keep the splash globaly. If we take this approach we would take the workspace UX configuraitons as a corner case which I believe they are.

**Comment by isidorn** [comment]
Other examples where this is very noticable:

Zooming, hiding parts...

**Comment by jrieken** [comment]
> If we take this approach we would take the workspace UX configuraitons as a corner case which I believe they are.

Not so sure about that... We should consult configuration telemetry first

**Comment by isidorn** [comment]
My reasoning for the above statement is that all our commands, ux visible actions / menus write to user settings.
But yeah telemetry could verify my hipothesis

**Comment by jrieken** [comment]
Things are now stored globally!

**Comment by isidorn** [comment]
Yeeey 🎉
