### ISSUE TITLE
Add support to configure the UI Language through menu entries

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#5503]
- VSCode Version: 1.0.0
- OS Version: all

Currently users have to edit a json file. We should provide menu entries for this.

**Comment by gregvanl** [comment]
A first step would be to at least have a Configure Language item under the File > Preferences menu.

**Comment by dbaeumer** [comment]
@chrisdias & @egamma Is this something we should still investigate / work on. I haven't received an external request to have this in menu entries.

**Comment by gregvanl** [comment]
Here's a smile Doc Feedback verbatim from 4/15/2016:
"You have to implement an interface menu item to change the locale settings, like this: File -> Preferences -> Display Settings as it done for "User Settings"."

**Comment by dbaeumer** [comment]
Didn't get to it because of the builder explorartion.

**Comment by dbaeumer** [comment]
Moving to the backlog based on our planning discussion.

**Comment by bpasero** [comment]
@dbaeumer I suggest to close.

**Comment by dbaeumer** [comment]
Agree. Closing.
