### ISSUE TITLE
Open settings.json for advanced customisation too long

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#55032]
I would jsut call this `Open settings.json`
Our users are already aware that we use .json files underneath (tasks.json launch.json)
The current title is too long and unnedeed imho
fyi @misolori 

![screen shot 2018-07-25 at 12 33 54](https://user-images.githubusercontent.com/1926584/43196107-36b4e45e-9007-11e8-8cb8-04c7485497f8.png)
r

**Comment by roblourens** [comment]
I don't know what to call "old settings editor" for the user

**Comment by roblourens** [comment]
I didn't notice the issue already had the answer 👍
