### ISSUE TITLE
Should installing a pack enable the included extensions?

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#55034]
Issue Type: <b>Bug</b>

Testing #54862

Installing an extension pack with some included extensions already installed but disabled, currently does not enable these extensions. It seems to make sense to enable these similarly to installing any missing ones.

VS Code version: Code - Insiders 1.26.0-insider (5fae91d61f12726e149fe5baed342eac2fbf8f88, 2018-07-25T01:56:56.548Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (0.52GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|22%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
autofilename|Jer|0.1.3
999-pack1|chr|0.12.0

</details>

**Comment by sandy081** [comment]
I would not agree for this. Pack is just a bundle of independent extensions to install together. Enabling the extensions user disabled just a pack is installed might not be expected for the user.
