### ISSUE TITLE
spawn ENAMETOOLONG in WSL workspace from Windows

### ISSUE THREAD

**Issue by sleutho** [microsoft/vscode#55045]
Issue Type: <b>Bug</b>

I'm trying to use Windows to work in a workspace located in the WSL.
E.g.: C:\Users\<user>\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\home\<user>\<foldername>\<workspacename>

The search is broken, showing a "spawn ENAMETOOLONG" toast.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.85GB (21.36GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Users\leuthold\OneDrive - Altair Engineering, Inc\Weekly recap.txt|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.7.1
cpptools|ms-|0.17.7
vscode-icons|rob|7.24.0
hyperworks|sle|0.1.0
optistruct|sle|0.1.0
radioss|sle|0.1.0
tcl|sle|0.2.0
templex|sle|0.1.1

</details>

**Comment by sleutho** [comment]
![screenshot](https://imgur.com/a/cMMhmCH)

**Comment by kieferrm** [comment]
@sleutho search in the workspace I guess?

**Comment by sleutho** [comment]
Yes, full search in the workspace, not in a single file.

**Comment by roblourens** [comment]
Does it work if you set `"searchRipgrep.enable": true`? That might be a good workaround for now.

**Comment by sleutho** [comment]
It works with "searchRipgrep.enable": true.

**Comment by roblourens** [comment]
That is a new implementation of search which will eventually become the default. This is too hard to fix in the current version of search.

**Comment by roblourens** [comment]
Should be fixed now. Also check out the Remote WSL extension if you are developing in WSL.
