### ISSUE TITLE
Export Keybindings.json to pdf/word document

### ISSUE THREAD

**Issue by jdcrux** [Microsoft/vscode#55049]
A button or feature that prints the key shortcuts (_keybindings.json_) to a pdf format or word documents (most preferably .pdf)

**Comment by jdcrux** [comment]
or maybe include the other way around (import) ... maybe?

**Comment by kieferrm** [comment]
The built-in version is accessible through the command palette (<kbd>Cmd+Shift+P</kbd>) or the `Help` menu: `Keyboard Shortcuts Reference`.
