### ISSUE TITLE
Run code region

### ISSUE THREAD

**Issue by GandalfSaxe** [Microsoft/vscode#55048]
Code regions can be made with [special syntax](https://code.visualstudio.com/docs/editor/codebasics#_folding) for each language, for the purposes of code folding.

As far as I can see it's not possible to run a code region. This would a great future.

**Comment by kieferrm** [comment]
We have a generic `Run Selected Text in Active Terminal` command. Anything that is more specific needs to come from language extensions as only extensions can know if the selection / region is runnable and if so how.

**Comment by GandalfSaxe** [comment]
Are you sure about this? Because logically if you can support code folding universally, you should be able to support “Run code in region” universally if a code region is detected? Those two functionalities seem equivalent to me.

**Comment by kieferrm** [comment]
Even if we have the region we wouldn't know how to run it. We'd need some help from the extension.

**Comment by GandalfSaxe** [comment]
I see. I’ll take it up with the python extension then. Thanks!
