### ISSUE TITLE
Disabling Azure App Service fails

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#55043]
Issue Type: <b>Bug</b>

Testing #54862

Disabling Azure App Service fails. The pack includes Azure Account and Azure App Service depends on Azure Account. Maybe that made it fail.

![image](https://user-images.githubusercontent.com/9205389/43197796-981259b6-900c-11e8-9106-79e84595d925.png)

VS Code version: Code - Insiders 1.26.0-insider (5fae91d61f12726e149fe5baed342eac2fbf8f88, 2018-07-25T01:56:56.548Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 4|
|Memory (System)|16.00GB (0.17GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|22%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
autofilename|Jer|0.1.3
999-pack1|chr|0.12.2
regex|chr|0.2.0
ssh|chr|0.0.4
vscode-eslint|dba|1.4.12
Spot|der|0.4.0
ghlink|dt|1.0.2
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.34
rest-client|hum|0.19.0
javascript-unit-test-snippet|iZD|1.0.0
vscode-kitchen|jir|0.5.0
vscode-azureappservice|ms-|0.9.0
vscode-azurefunctions|ms-|0.10.0
vscode-cosmosdb|ms-|0.8.0
azure-account|ms-|0.4.2
azurecli|ms-|0.4.2
github-issues-prs|ms-|0.9.0
PowerShell|ms-|1.8.1
debugger-for-chrome|msj|4.8.2
vscode-docker|Pet|0.0.27
vscode-versionlens|pfl|0.21.1
999-extension-pack1|san|0.0.2
todotasks|san|0.5.0
vscode-open-in-github|sys|1.7.0
azure-iot-toolkit|vsc|1.1.0

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
Yes as the message says.

**Comment by chrmarti** [comment]
Azure App Service is in the pack together with Azure Account. I'd expect all to be disabled, instead that fails.

**Comment by sandy081** [comment]
@chrmarti Please try it again. With fix from #55055 you will see a prompt to disable extension only or its dependencies also. If you choose to disable its dependencies also you will see above message, otherwise it should work.
