### ISSUE TITLE
[handlebars] validation issue in Handlebars file (exactly the same as #18777)

### ISSUE THREAD

**Issue by ecarlotti** [Microsoft/vscode#55046]
This is the exact same error reported on issue #18777 closed by Microsoft on Nov, 18 2017 with a fix on commit 9b47ab5, but it seems the issue is back (if it ever got fixed, anyway - I can't really tell).

The insiders build I downloaded today has the same issue

- VSCode Version: 1.25.1
- OS Version: CentOS 7

Steps to Reproduce:

1. start VScode without any extensions (code --disable-extensions)
2. load html file that has any tag including a style element that uses a handlebars extension, e.g.:
<template name="mytemplate">
    <div class="detail-widget style1" style="background-color:{{getBGColor}}; color:#ffffff;">
    </div>
</template>

VSCode will show 5 errors for the code above:

1. [css] property value expected (2, 63)
2. [css] at-rule or selector expected (2, 76)
3. [css] identifier expected (2, 85)
4. [css] { expected (2, 92)
5. [css] at-rule or selector expected (2, 93)

![screen shot 2018-07-25 at 08 34 54](https://user-images.githubusercontent.com/28097312/43198618-afbd05ba-8fe5-11e8-850b-12b4c2decbd7.PNG)

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
This is a HTML file (test.html) and the editor is in `HTML` mode. Using `{{getBGColor}}` is not valid in HTML.
If this is handlebars, you have to give your file the `hb` extension so the editor is in the handlebars mode.

Alternatively, configure
`"html.validate.styles": false`
