### ISSUE TITLE
Disabling/uninstalling extension with dependency prompts about 'pack'

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#55052]
Issue Type: <b>Bug</b>

Testing #54862

Since extension dependencies are now about functional dependencies (and not a bundling mechanism anymore), the prompts should indicate that.

![image](https://user-images.githubusercontent.com/9205389/43202075-b1589986-901a-11e8-87a3-497ca1c7d528.png)

Maybe: "Would you like to uninstall 'foobar' only or include its dependencies?"

VS Code version: Code - Insiders 1.26.0-insider (5fae91d61f12726e149fe5baed342eac2fbf8f88, 2018-07-25T01:56:56.548Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.40GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|22%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
azure-account|ms-|0.4.2
azure-iot-toolkit|vsc|1.1.0

</details>

**Comment by sandy081** [comment]
I think while uninstalling extension with functional dependencies, I would think its better not to show any prompt and uninstall/disable the extension only.

**Comment by chrmarti** [comment]
Sounds good, these prompts are confusing. One downside is maybe that installing and then uninstalling an extension with dependencies does not leave you in the same state as you started from.

**Comment by chrmarti** [comment]
An advantage is that it solves the following issue (a bug):
- Install Azure App Service and Azure Cosmos DB.
- Uninstall Azure App Service and choose to uninstall the 'pack'.
- Observe: Only the Azure App Service is uninstalled, presumably because Azure Cosmos DB still needs Azure Account.
- Expected: Don't prompt to uninstall the 'pack'.

**Comment by sandy081** [comment]
Fixed by #55055

**Comment by chrmarti** [comment]
Typo when disabling an extension (should be "extension" not "extensions"):
![image](https://user-images.githubusercontent.com/9205389/43249589-60be3610-90bb-11e8-8409-b8034f574102.png)

Move "also" around and shorten: "Also disable the dependencies of the extension?"

**Comment by chrmarti** [comment]
Align the two:
![image](https://user-images.githubusercontent.com/9205389/43249855-21aaac28-90bc-11e8-8a91-45731c0db6e9.png)

Maybe: "Also uninstall the dependencies of the 'Azure Functions' extension?"

**Comment by sandy081** [comment]
Good suggestion

![image](https://user-images.githubusercontent.com/10746682/43255263-a77ddb6a-90c9-11e8-8e6e-bbef2184b3da.png)


![image](https://user-images.githubusercontent.com/10746682/43255312-cb6edb1e-90c9-11e8-9a9d-cacd81765187.png)

**Comment by sandy081** [comment]
There have been lot of improvements in this area. So please revalidate this issue with latest changes and file a separate issue or reopen this with updated requirements.
