### ISSUE TITLE
let's avoid cycling service dependencies

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#5505]
We have a couple of cycling dependencies between services, like `KeybindingService` depends on `MessageService` and vice versa. Such dependencies are undesirable and we should strive to remove them/not have them in the first place. Let's collection cycling dependencies first and then come up with a plan on how to get rid of them.

**Comment by jrieken** [comment]
fyi @bpasero @alexandrudima

**Comment by bpasero** [comment]
👍

**Comment by dbaeumer** [comment]
@jrieken @bpasero @alexandrudima any volunteer. Want to get it out of the inbox :-)

**Comment by Tyriar** [comment]
After this is cleaned up could the `InstantiationService` or service registry be modified to prevent this from being introduced again? Keeping a service->dependency map would make it easy to detect cycles at service registration/creation.

**Comment by bpasero** [comment]
I pushed a change to get rid of the keybindingservice <-> messageservice cycle.

**Comment by dbaeumer** [comment]
@bpasero thanks. OK to close ?

**Comment by bpasero** [comment]
@dbaeumer maybe assign this back to @jrieken in case he found more cycles.

**Comment by jrieken** [comment]
yeah, I will keep looking for more cycles

**Comment by bpasero** [comment]
There is a very ugly setWorkbenchServices() call in MessageService that I would tackle as part of https://github.com/Microsoft/vscode/issues/5504

**Comment by jrieken** [comment]
@Tyriar We already do that and `createInstance` will explode when a cycle in [detected](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/instantiation/common/instantiationService.ts#L163). The problem is that we create the instantiation service from a service collection that we in parts populate manually. That manual setup (shell.ts/workbench.ts) is the issue...
