### ISSUE TITLE
Modify system time, causing CPU to rise

### ISSUE THREAD

**Issue by BlackHole1** [microsoft/vscode#55053]
- VSCode Version: 1.25.1
- OS Version: win10 Pro

Steps to Reproduce:

1. open Vscode

2. Modify system time

3. Wait for a few seconds

4. The CPU occupancy began to rise

Does this issue occur when all extensions are disabled?: Yes

**Comment by BlackHole1** [comment]
Not repeating

**Comment by kieferrm** [comment]
What process is consuming the CPU? You can open the Process Explorer through the Command Palette to see which one it is.

**Comment by BlackHole1** [comment]
![image](https://user-images.githubusercontent.com/8198408/43357066-8c9142c4-92ae-11e8-8f4d-3a3f972e7e6d.png)

**Comment by kieferrm** [comment]
@BlackHole1 thanks for the screenshot. Can you please also add one using the VS Code Process Explorer. <kbd>F1</kbd> > `Developer: Open Process Explorer`.

**Comment by BlackHole1** [comment]
@SpectralKH Is it normal after restart?

**Comment by SpectralKH** [comment]
@BlackHole1 I didn't restart, I just updated to VSC 1.16.1

**Comment by BlackHole1** [comment]
I already use webstorm, thank you very much for your reply, I will close this question
