### ISSUE TITLE
Improve disabling or uninstalling an extension pack vs an extension with dependencies behaviour

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#55055]
By separating extension packs with extension dependencies, we now know what are functional dependencies and what are bundle dependencies. With this we can improve the management of these extensions

Based on the feedback received during testing, following is recommended

## Extension Packs

- Install & Uninstall, Enablement & Disablement is done as a pack

## Extension Dependencies

- Install / Enable **also** installs / enables the dependencies
- Uninstall / Disable shows a prompt to uninstall/disable single extension or with dependencies (like before).

@chrmarti What do you think?

**Comment by chrmarti** [comment]
Sounds great! One caveat maybe: This will work well only when existing 'bundles' adopt the new `"extensionPack"`.

**Comment by sandy081** [comment]
Yes, but the change in behaviour is only during uninstall/disable which is tolerable I suppose.

It means, an extension pack which is using dependencies cannot be disabled/uninstalled completely.

**Comment by sandy081** [comment]
Gave a second thought and want to give some time for the existing extension packs to adopt to new property. Until then extensions with dependencies will have the same behaviour. But extension packs (using new property) will have new behaviour as mentioned in the description.

Created a followup item for updating the uninstall/disable behaviour of extensions with dependencies  - #55072

**Comment by sandy081** [comment]
@chrmarti Please verify this in tomorrow's build. Thanks.
