### ISSUE TITLE
Attributes starting with accent in React Components (.jsx / JavaScript React)

### ISSUE THREAD

**Issue by rodrigojcmello** [Microsoft/vscode#55056]
- VSCode Version: 1.25.1
- OS Version: Mac 10.13.6
- Theme: Monokai (issue occurs with any theme)

Steps to Reproduce:

1. Create a react component with jsx
2. Pass attributes starting with accents like ícone, ônibus, àrea
<img width="339" alt="captura de tela 2018-07-25 as 10 14 07" src="https://user-images.githubusercontent.com/5174526/43203658-34112198-8ff5-11e8-9035-acbf33a042aa.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#640
