### ISSUE TITLE
Show folder name on the file being edited (Multiple Folders in workspace)

### ISSUE THREAD

**Issue by jasonbronson** [Microsoft/vscode#55066]
When editing a file which has the same name as other folders in a workspace example header.php it can be difficult to tell which file is from which folder. 
If you could add in the ability to show the folder name maybe in the title of the editor or something instead of just showing

Before:
filename --- WorkspaceName (Workspace)

After
filename --- FOLDERNAME --- WorkspaceName (Workspace)

Keep in mind the editor does this already when two files of the same name are opened but not if only one is opened. When you start opening many files from different workspace folders you easily get lost in which file belongs to where.

**Comment by kieferrm** [comment]
@jasonbronson  check out the `window.title` setting in the settings editor. You can configure what  your window title should be.
