### ISSUE TITLE
cmd keybindings map to super on Linux

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#55060]
I expect cmd keybindings to be mac specific, this keybinding translates to super+k on Linux though:

```
{ "key": "cmd+k",            "command": "workbench.action.terminal.clear", "when": "terminalFocus" }
```

**Comment by alexandrudima** [comment]
Yes, `cmd` and `meta` are parsed as `meta`. What is the exact problem?

**Comment by Tyriar** [comment]
I expected it to only work on macOS as it's called "cmd", much like "windows+k" should not apply mac keybinding as mac does not have a windows key. I know they're both "meta" underneath in the web API but that's an implementation detail.

**Comment by alexandrudima** [comment]
I think I considered the VM case and decided at the time to make the parsing more liberal.

For example, if I am running a Linux VM in a macOS host, then I can copy-paste my user keybindings from macOS and paste them in the VSCode running on Linux and most of the keybindings will work like on macOS.

I would not change this behaviour.

**Comment by Tyriar** [comment]
Ok, as long as it was considered 😃. https://github.com/Microsoft/vscode/pull/54894 would also help solve this problem for me of Windows+K being bound on Linux/Windows.
