### ISSUE TITLE
Why is the version 1.0 in German?

### ISSUE THREAD

**Issue by aureole82** [Microsoft/vscode#5506]
- VSCode Version: 1.0.0
- OS Version: Windows 10 Pro

The new version is in German???

**Comment by dbaeumer** [comment]
VSCode 1.0.0 ships in 9 language now. You can control the language by editing the locale.json file. Press 
![capture](https://cloud.githubusercontent.com/assets/1931590/14643914/7d3533ea-0650-11e6-9309-67175d3656cc.png)
F1 and type Spracke konfigurieren. Enter "en" as the locale value.

**Comment by aureole82** [comment]
**F1 and "Sprache konfigurieren" did it!** It created the `%APPDATA%\Code\User\locale.json` which doesn't exists before.

But how should I know that?

**Comment by dbaeumer** [comment]
Agree. We are working on a more discoverable solution.
