### ISSUE TITLE
vscode.window.terminals always gives empty array

### ISSUE THREAD

**Issue by stefandevo** [Microsoft/vscode#55079]
Trying to make an extension that executes some stuff in a dedicated terminal.
But querying vscode.window.terminals always gives 0 elements while there are terminals available.

**Comment by Tyriar** [comment]
What version of VS Code are you on?

**Comment by stefandevo** [comment]
Running 1.25.1
and in my package.json I have the vscode: "^1.1.18"
I am using javascript (not typescript)

**Comment by Tyriar** [comment]
Will try look into this soon.

**Comment by Tyriar** [comment]
The API still works for me just fine, my guess is that you didn't have proposed APIs enabled as you were testing on 1.25.1 and it only became stable in 1.26. Give it another try on latest and let me know how it goes.
