### ISSUE TITLE
Support filter text expansion and '/' notation for folders in the breadcrumb

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#55077]
Issue Type: <b>Feature Request</b>

This is a complement to #55076 but still independent.

The breadcrumb is not yet optimized for switching to a file in a different folder. When searching for a folder and I have a prefix match <kbd>RightArrow</kbd> should expand my filter text with the first highlighted match. Appending '/' should then allow me to continue searching inside that folder. The folder should autoexpand and the matches be highlighted.

VS Code version: Code - Insiders 1.26.0-insider (5fae91d61f12726e149fe5baed342eac2fbf8f88, 2018-07-25T01:56:56.548Z)
OS version: Darwin x64 16.7.0

**Comment by jrieken** [comment]
I like, but tricky...

**Comment by jrieken** [comment]
The problem with searching is that we don't know (yet) the child items (for files). It would require integrating file search for that (as we do in quick open)...
