### ISSUE TITLE
How to make Visual Studio Code look for dependencies in a mounted partition (A Singularity container)?

### ISSUE THREAD

**Issue by Amir-Arsalan** [Microsoft/vscode#55071]
I want to compile a large code base using Visual Studio Code but I don't want to install the dependencies (that I obtain them through `apt-get` or `pip`) of that code base on my laptop. Instead, I have installed those dependencies in another partition (basically, a Singularity container as mentioned [here](https://github.com/Microsoft/vscode/issues/55062)) and have mounted the partition where the dependencies.

Since it looks like I cannot run VS Code's GUI in the Singularity container, as of now, my goal is to use the CMake extension in VS Code to generate the CMake files for that code base and compile it. However, CMake gives errors as it cannot find the dependencies on my machine. So I wonder, how can I make Visual Studio Code to only look for dependencies in a specific location (say the mounted partition) instead of my machine?

**Comment by kieferrm** [comment]
@Amir-Arsalan pls ask this question in the CMake extension repo. Thanks!

**Comment by Amir-Arsalan** [comment]
@kiefermm sorry I'm a bit mad but I feel you didn't really read my question. I understand that VS Code gets a lot of issues every day but it shouldn't mean that they should be closed by the end of the business day. My question is noy about the CMake Extension but is about VS Code. I just gave an example of my eventual goal. I would appreciate if you can rread my question again. I would also appreciate if you can do the same for the other issue I posted before (which I pointed to in this issue) as it seems it is a problem that some other people have pointed to (different issues for each error I mentioned there) in other issues since 2 years ago
