### ISSUE TITLE
Consider to change development process

### ISSUE THREAD

**Issue by outcoldman** [Microsoft/vscode#5507]
Follow up discussion on:
- PR https://github.com/Microsoft/vscode/pull/5443#issuecomment-211401340
- Nightly builds https://github.com/Microsoft/vscode/issues/5453

Current development process:

- developers commit directly into `master`
- you cannot be 100% sure that you can build `master`.
- there are no way to setup Nightly Builds, because there are huge chance that build can be broken in master.
- it happened to me two times already (for my 2 days experience with VSCode). When I pulled master and could not use it, because in first time there were some issues with runtime (which could be found with integration test) and second time a build issue.
- It is just my assumption that because of this workflow you can lose interest of some contributors, don't think that most folks will deal with it.

My suggestion:

- Personally I believe all changes needs to be made with Code Reviews. But my ask to at least work through PR and only merge when build is green.

Microsoft now has plenty Open Source projects, I believe most of them (if not all) are using Pull Request model with Code Reviews. Please talk to @shanselman, ASP.NET team or dotnet core team to learn from their experience.

/cc @jrieken

**Comment by egamma** [comment]
@outcoldman thanks for your input. I fully agree that @shanselman and the ASP.net team do a great job.

An difference between the ASP.net project and ours is that we aggressively dogfood and this 'luxury' allows us to also use a more aggressive development process that gives us more velocity. We use the PR model in end games and for contributions inside the time to areas which are mostly owned by someone else. We currently have no plan to go with a full PR model. 

We have decided to make our alpha channel available and will update the web site etc, which will happen soon. This will give you nightly builds and this was a great suggestion.

**Comment by outcoldman** [comment]
@egamma thank you for answer
