### ISSUE TITLE
comment bug for different file types

### ISSUE THREAD

**Issue by DK013** [Microsoft/vscode#55085]
Issue Type: <b>Bug</b>

Comments are written differently in different languages.
For Example:
In HTML : `<!--<div> whatever</div>-->`
iIn CSS, JS, PHP etc : `// whatever code`

Previously VSCode used to respect those rules for different languages and the keyboard shortcut for comment used to put the right syntax depending on language. now "//" seems to be universal. This needs to be fixed.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17704

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-6300 Six-Core Processor              (6 x 3516)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|8.00GB (3.94GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|8.0.0
laravel-blade|cjh|1.1.2
xml|Dot|2.3.1
vscode-html-css|ecm|0.2.0
vscode-npm-script|eg2|0.3.5
php-debug|fel|1.12.3
crane|Hvy|0.3.8
smarty|imp|0.3.0
solidity|Jua|0.0.45
vscode-language-babel|mgm|0.0.20
dotenv|mik|1.0.1
node-debug2|ms-|1.26.6
PowerShell|ms-|1.8.1
team|ms-|1.136.0
debugger-for-chrome|msj|4.8.2
color-highlight|nau|2.3.0
laravel-blade|one|1.18.0
material-icon-theme|PKi|3.5.2
heroku-command|pko|0.0.8
java|red|0.28.0
ftp-kr|rua|1.3.16
vscode-java-debug|vsc|0.10.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.7.1
vscode-maven|vsc|0.9.2
vscode-react-native|vsm|0.6.13

(1 theme extensions excluded)

</details>

**Comment by kieferrm** [comment]
Tested on 1.25.1 on Window 10 for the language modes `html`, `js`, `css` on a vanilla VS Code.  Works as expected.
