### ISSUE TITLE
There is no search history

### ISSUE THREAD

**Issue by brunolemos** [Microsoft/vscode#5508]
Can't easily redo previous search, which is very annoying and decreases productivity.

- VSCode Version: 1.0.0
- OS Version: OS X 10.11.4

Steps to Reproduce:

1. Press Shift+Cmd+F
2. Search for something
3. Search for another thing
4. Press UP key (or Cmd+Z or whatever)

Expected: Show previous search term, like all other editors
Result: Nothing happens

VS Code:
![VS Code Search Example]
(https://s31.postimg.org/6th4ds8hn/search-code.gif)

Atom:
![Atom Search Example]
(https://s31.postimg.org/4q6p648or/search-atom.gif)

**Comment by dbaeumer** [comment]
@kieferrm heard you are taking over search :-)

**Comment by JimmyBurdette** [comment]
I really liked this feature in Atom and would use it regularly.

**Comment by Urik** [comment]
I would love to give this feature a shot. Any chance you'd accept a contribution on this one?

**Comment by sandy081** [comment]
@Urik I have already started on this and planning to push it today.. Sorry for that.

**Comment by Urik** [comment]
That's so great to hear Sandy, I've been lusting over that feature since I started working with VSCode!  
I'd love to see these possible features, thanks.

**Comment by sandy081** [comment]
Implemented following support:

Search input in Search view
Find input in Find widget

- <kbd>alt</kbd>+<kbd>up</kbd> : Shows the previous term in history
- <kbd>alt</kbd>+<kbd>down</kbd> : Shows the next term in history

Customize key board short cuts
- `search.history.showPrevious` : <kbd>alt</kbd>+<kbd>up</kbd>
- `search.history.showNext` : <kbd>alt</kbd>+<kbd>down</kbd>
- `find.history.showPrevious` : <kbd>alt</kbd>+<kbd>up</kbd>
- `find.history.showNext` : <kbd>alt</kbd>+<kbd>down</kbd>

**Comment by hipstersmoothie** [comment]
this work well but i feel its kinda hidden behind the alt+. is there any way to have it just be up/down on the search fields?

**Comment by sandy081** [comment]
@hipstersmoothie You can customize the key board short cuts overriding the commands and keys mentioned in [comment](https://github.com/Microsoft/vscode/issues/5508#issuecomment-246646872)

**Comment by gandhis1** [comment]
Thats great, still, the defaults should be intuitive and natural. Not sure that the use of ALT satisfies that. Is there any downside to not using ALT? These are single line queries (absent the use of \n), anyway, so I would think up and down do not have a meaning in these contexts.

**Comment by sandy081** [comment]
@gandhis1 Up and Down are already used to navigate between the input boxes (Search, Replace, Files include, Files exclude). Using Alt goes with other key board short cuts for actions - Toggle match case, reg ex, whole word. 

I am open for the suggestions to change the default one to more better ones.

Thanks for the feedback

**Comment by z-ax** [comment]
@sandy081 navigation between fields is actually expected by `tab`, `shift+tab`. So I don't see any reason to not just use arrows for search/replace history in those fields.

**Comment by sandy081** [comment]
Thanks for the feedback. Filed the following issue to change it

https://github.com/Microsoft/vscode/issues/12645
