### ISSUE TITLE
Not possible to checkout a specific commit?

### ISSUE THREAD

**Issue by GandalfSaxe** [Microsoft/vscode#55086]
Issue Type: <b>Bug</b>

I almost can't believe this, but is it truly not possible to checkout an arbitrary commit by hash? Nothing happens if I paste a commit hash/id into the checkout quick command. Do I really have to use a 3rd party client to roll back time? :)

Same problem as Microsoft/vscode/issues/30280

VS Code version: Code - Insiders 1.26.0-insider (5fae91d61f12726e149fe5baed342eac2fbf8f88, 2018-07-25T01:56:56.548Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.22GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.0.2
path-intellisense|chr|1.4.2
vscode-svgviewer|css|1.4.4
vscode-markdownlint|Dav|0.18.0
githistory|don|0.4.2
jupyter|don|1.1.4
vscode-pandoc|Dou|0.0.8
gitlens|eam|8.5.3
vsc-material-theme|Equ|2.3.0
prettier-vscode|esb|1.5.0
vscode-diff|fab|1.3.2
latex-workshop|Jam|5.7.0
python|ms-|2018.7.1
PowerShell|ms-|1.8.1
wordcount|ms-|0.1.0
vsliveshare|ms-|0.3.472
gremlins|nho|0.7.0
vscode-docker|Pet|0.0.27
quicktype|qui|12.0.5
vscode-icons|rob|7.24.0
partial-diff|ryu|1.2.0
markdown-preview-enhanced|shd|0.3.5
vscode-spotify|shy|2.5.1
vscode-fileutils|sle|2.10.3
slack|soz|0.0.14
code-spell-checker|str|1.6.10
vscode-terminal-here|Tyr|0.1.1
vscodeintellicode|Vis|1.0.1
vscode-todo-highlight|way|1.0.4
markdown-all-in-one|yzh|1.6.0

(2 theme extensions excluded)

</details>
<!-- generated by issue reporter —>

**Comment by kieferrm** [comment]
`git checkout <commit id>` in the integrated terminal. No real need for an extension.

**Comment by GandalfSaxe** [comment]
Fair enough 🙂

**Comment by GandalfSaxe** [comment]
On the other hand I don't see why the "Git: Checkout to..." command shouldn't be able to take a branch name _as well as_ a commit id. Should be trivial.
