### ISSUE TITLE
Allow to open file names containing backslash

### ISSUE THREAD

**Issue by fiendish** [Microsoft/vscode#55084]
Issue Type: <b>Bug</b>

macOS supports backslashes in file names, but this breaks vscode. The file shows broken in the explorer pane (all characters before the backslash are missing), and the file cannot be opened and gives a file not found error where the backslash has been converted into a forward slash which masquerades as a directory split.

<img width="373" alt="screen shot 2018-07-25 at 2 48 23 pm" src="https://user-images.githubusercontent.com/201996/43221118-e6c2ab9e-9019-11e8-8a79-375e7c8c244a.png">
<img width="288" alt="screen shot 2018-07-25 at 2 48 36 pm" src="https://user-images.githubusercontent.com/201996/43221130-eeb51b7a-9019-11e8-9021-5548003609c9.png">
<img width="531" alt="screen shot 2018-07-25 at 2 50 54 pm" src="https://user-images.githubusercontent.com/201996/43221203-2e56e1e6-901a-11e8-961c-9d1b2a1325df.png">

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.36GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.1.2
vscode-markdownlint|Dav|0.18.0
jupyter|don|1.1.4
gc-excelviewer|Gra|2.1.25
rainbow-csv|mec|0.4.2
python|ms-|2018.7.1
rewrap|stk|1.9.1
vscode-lua|tri|0.12.4
python-extended-snippets|tus|0.0.1
markdown-all-in-one|yzh|1.6.0

</details>

**Comment by tonyzheng1990** [comment]
when can fix this bug?
