### ISSUE TITLE
Long descriptions in new settings editor need ellipsis when being cut off

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#55089]
Issue Type: <b>Bug</b>

In the below case, the description for `emmet.includeLanguages` setting is longer than 1 line. But at a glance, this is not obvious. Having an ellipsis in the end would help

![image](https://user-images.githubusercontent.com/16890566/43223812-1c05894a-9009-11e8-8b83-4a997417daae.png)

**Comment by ubikusss** [comment]
I can actually see them:

![image](https://user-images.githubusercontent.com/10058111/43261162-756f4b5c-90e4-11e8-9084-96195e1f4ba2.png)

VS Code Version: 
Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:43:11.471Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: ia32

**Comment by roblourens** [comment]
They were present in 1.25.1 but lost in 1.26 (insiders)

**Comment by roblourens** [comment]
This is now N/A
