### ISSUE TITLE
Don't auto-add closing quotes in HTML outside tags

### ISSUE THREAD

**Issue by davidpmccormick** [Microsoft/vscode#5509]
When entering characters in HTML, VS Code will auto-close all quotes.

This seems like sensible behaviour within a tag, but outside tags (i.e. in copy) a single-quote could easily be being used as an apostrophe.

**Comment by Foxandxss** [comment]
I get this but only in Windows, not in Mac.

When I do say `<div>Hello I don'</div>` that apostrophe gets outputted twice.

**Comment by rebornix** [comment]
This can be disabled by setting `editor.autoClosingQuotes` to `beforeWhitespace`.
