### ISSUE TITLE
CMD+S Randomly Stops Working

### ISSUE THREAD

**Issue by macintacos** [microsoft/vscode#55093]
Issue Type: <b>Bug</b>

I don't know how to reproduce this because it happens randomly. I'll just be going about my day, using CMD+S to save my files. Randomly, I'll notice that there are still grey dots next to file names, because the file hasn't been saved in a while. CMD+S stopped working. Running it through the command palette is fine.

I remove the mapping for the save action to CMD+S and restart VSCode, and go to remap the action again to CMD+S. VSCode refuses to type the letter "S" into the keybindings window. I have no idea why, but it happens.

![Gif](https://cl.ly/tEdE/Screen%20Recording%202018-07-25%20at%2005.00%20PM.gif)

Here's the kicker; other keyboard shortcuts (like Save As) that include CMD+S+<another modifier> work _fine_. It's driving me insane.

A full restart of my machine resolves it. This happened today with the two options specified via the command line (for monitor flicker issues), but it happens with normal starts of VSCode too.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: unavailable_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Load (avg)|4, 4, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron --disable-gpu --ignore-gpu-blacklist|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (82)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.18.0
EditorConfig|Edi|0.12.4
terminal-tabs|Tyr|0.2.0
better-comments|aar|1.2.6
html-snippets|abu|0.2.1
vscode-caniuse|aga|0.5.0
vscode-javascript-snippet-pack|aka|0.1.5
Bookmarks|ale|9.0.2
project-manager|ale|8.0.0
spellright|ban|2.5.22
color-info|bie|0.5.0
htmltagwrap|bra|0.0.7
solargraph|cas|0.17.6
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
regex|chr|0.2.0
open-html-in-browser|cod|0.1.21
gitignore|cod|0.5.0
bracket-pair-colorizer|Coe|1.0.59
compulim-vscode-closetag|Com|1.2.0
vscode-svgviewer|css|1.4.4
scala|dal|0.0.5
jshint|dba|0.10.19
vscode-eslint|dba|1.4.12
vscode-dash|dee|1.10.0
jquerysnippets|don|0.0.1
scala-lsp|dra|0.2.3
gitlens|eam|8.5.3
vscode-html-css|ecm|0.2.0
vscode-npm-script|eg2|0.3.5
LogFileHighlighter|emi|2.4.0
vsc-material-theme|Equ|2.3.0
json-tools|eri|1.0.2
prettier-vscode|esb|1.5.0
git-project-manager|fel|1.6.1
php-intellisense|fel|2.3.3
file-icons|fil|1.0.12
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.3
terminal|for|0.0.10
gc-excelviewer|Gra|2.1.25
beautify|Hoo|1.3.2
applescript|idl|0.10.0
hungry-delete|jas|1.5.0
golang-tdd|joa|0.0.9
intellij-idea-keybindings|k--|0.2.24
vscode-gutter-preview|kis|0.13.0
expand-region|let|0.1.2
scratchpad|mac|0.0.3
MagicPython|mag|1.0.12
HTMLHint|mka|0.5.0
vscode-filesize|mkx|2.1.1
vscode-scss|mrm|0.6.2
python|ms-|2018.7.1
cpptools|ms-|0.17.7
csharp|ms-|1.15.2
Go|ms-|0.6.84
node-debug2|ms-|1.26.6
PowerShell|ms-|1.8.1
debugger-for-chrome|msj|4.8.2
advanced-new-file|pat|1.2.0
vscode-code-outline|pat|0.2.1
material-icon-theme|PKi|3.5.2
vscode-css-peek|pra|2.1.0
itunes-vscode|Psy|0.8.3
vscode-icons|rob|7.24.0
partial-diff|ryu|1.2.0
code-settings-sync|Sha|3.0.0
markdown-preview-enhanced|shd|0.3.5
vscode-fileutils|sle|2.10.3
guides|spy|0.9.2
autoimport|ste|1.5.3
Align|ste|0.2.0
rewrap|stk|1.9.1
ayu|tea|0.14.0
vscode-react-native|vsm|0.6.13
quokka-vscode|Wal|1.0.135
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.8.0
JavaScriptSnippets|xab|1.7.0
markdown-all-in-one|yzh|1.6.0

(7 theme extensions excluded)

</details>

**Comment by kieferrm** [comment]
@macintacos bummer. Just in case, anything in the Developer tools log? (`Toggle Developer Tools` in through the command palette). Do you happen to know if you had the same issue on 1.25 before you installed the latest High Sierra update?

**Comment by macintacos** [comment]
@kieferrm Next time this happens I'll take a peek at the developer logs; keep forgetting that this is an Electron app and I can do that 😅 It typically happens about once a week, so I'll open that up next time it happens and take a peek.

> Do you happen to know if you had the same issue on 1.25 before you installed the latest High Sierra update?

It's been happening occasionally for a few months, so definitely before VSCode 1.25; typically when it was the least convenient and when I didn't really have time to write a decent bug report. The only OS this machine has known has been High Sierra, so I can't speak to whether or not this occurs in versions before High Sierra.

**Comment by macintacos** [comment]
Nope, hasn't been a problem for a good long while. I'll re-open if it happens again.
