### ISSUE TITLE
How to change mouse hover tooltip pop-up delay time?

### ISSUE THREAD

**Issue by skyvondave** [Microsoft/vscode#55098]
When I hover over unfamiliar icons in the editor, it takes 3-5 seconds for its name or description to appear... I'd like to change this to 1 or 2 seconds, but I'm seeing no option for this anywhere.

I found this - `"editor.hover.delay": 300` - but it doesn't specify what numerical unit `300` is so I'm assuming it means milliseconds which means that doesn't appear to be the correct settings. There's no 'tooltip' in settings and 'delay' doesn't seem to show relevant settings.

I'm on a Mac.

**Comment by kieferrm** [comment]
@skyvondave you use the correct setting. The delay describes how long VS Code waits until it requests the hover. If it is as slow as you see it, its an issue with the language extension you use. See the gif for a demonstration on our own TypeScript code base.

![vks9rlghhn](https://user-images.githubusercontent.com/4674940/43236269-f833fcec-9038-11e8-9d7a-56fb86b917e8.gif)

**Comment by kieferrm** [comment]
@skyvondave I missed the "unfamiliar icons" part. There is no setting that you can use to control that delay.
