### ISSUE TITLE
[SCSS] Syntax highlighting is broken when using ::ng-deep followed by a class

### ISSUE THREAD

**Issue by Nxt3** [Microsoft/vscode#55099]
- VSCode Version: 1.26.0-insiders

Syntax highlighting seems to get funky around things like `::ng-deep`, which is used in Angular2+.

<img width="430" alt="screen shot 2018-07-25 at 7 44 36 pm" src="https://user-images.githubusercontent.com/2940826/43233310-42540344-9043-11e8-987a-e6d65691a1f2.png">

<img width="614" alt="screen shot 2018-07-25 at 7 44 45 pm" src="https://user-images.githubusercontent.com/2940826/43233302-3c4e83c0-9043-11e8-813e-8d378edf66a7.png">

It only seems to happen when you place it in a block:

<img width="324" alt="screen shot 2018-07-25 at 7 41 43 pm" src="https://user-images.githubusercontent.com/2940826/43233350-73ac7f7a-9043-11e8-8bb0-3cc54cddcedb.png">

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by octref** [comment]
Can you list all the things that Angular CSS deviate from the standard CSS? `my-tile` is not a HTML 5 tag name, is it for your custom components? Also `::ng-deep` is not a standard pseudo element.

**Comment by Nxt3** [comment]
It's really just `::ng-deep`. `my-tile` is the name of a custom component in Angular and could be whatever I named the component.

**Comment by aeschli** [comment]
This issue was moved to atom/language-sass#254
