### ISSUE TITLE
Support macOS "smart zoom"

### ISSUE THREAD

**Issue by JonJamesDesign** [Microsoft/vscode#55096]
In macOS, you can double-tap the trackpad with two fingers to zoom-in on the area of the screen where the cursor is positioned. This is called 'smart zoom'.

Following some rudimentary tests, 'Smart zoom' is supported in applications such as Google Chrome, Spotify and other macOS applications.  However, it does not work with VSCode.

**When I want to zone-out on a bug/issue with a few lines of code, I'd love to be able to just double-tap the trackpad and use 'smart zoom' to focus on that small portion of the screen.**

**Comment by costis** [comment]
Works for me. MacOS Sierra 10.12.6, VSCode 1.25.1

**Comment by bpasero** [comment]
We decided to disable this feature because it would zoom not just the code but everything. We do not intent to change this behavior.
