### ISSUE TITLE
.vscode folder for empty text document?

### ISSUE THREAD

**Issue by rakkarage** [Microsoft/vscode#5510]
- VSCode Version: 1.0.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. create new text document on desktop and open with vscode
2. now i have a hidden .vscode folder with a database on my desktop?

is there anyway to not create this file and folder unless there is a project? or at least some parse-able data?
is there a way to centralize or disable this cache?

thanks

**Comment by dbaeumer** [comment]
@rakkarage actually we should only create the .vscode folder if you edit workspace settings, create a task runner or debug. 

@bpasero in case there is something happening which creates an unwanted .vscode folder

**Comment by bpasero** [comment]
I would be surprised. If you use workspace settings, debug or tasks, you will need the .vscode folder.

**Comment by rakkarage** [comment]
the folder is created when i open an empty text file
no debug, tasks, or workbench settings, just open new text file
you are claiming this should not happen? or does not happen?
thanks

**Comment by bpasero** [comment]
We do not create a .vscode folder unless you open a folder with VS Code and use one of these features: settings, tasks or debug.

**Comment by rakkarage** [comment]
![folder](https://cloud.githubusercontent.com/assets/962340/14678647/9963bc14-06e4-11e6-8d9a-708813fa9703.gif)

**Comment by bpasero** [comment]
@rakkarage yeah maybe, what is inside the folder? 
Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions`

**Comment by rakkarage** [comment]
https://marketplace.visualstudio.com/items/ms-vscode.cpptools
this causes it :)
thanks

**Comment by bpasero** [comment]
@rakkarage so what kind of file does it put in there?

**Comment by outcoldman** [comment]
Is the ms cpptools extension open sourced? 

@bpasero `.browse.VC.db`

**Comment by bpasero** [comment]
Yes, please file this at https://github.com/Microsoft/vscppsamples/issues

**Comment by outcoldman** [comment]
I guess it is documented in https://github.com/Microsoft/vscppsamples/issues/14
