### ISSUE TITLE
粘贴代码自动缩进更改设置不生效

### ISSUE THREAD

**Issue by honefly** [Microsoft/vscode#55102]
Issue Type: <b>Feature Request</b>

写代码最常用的就是Ctrl + V 可是我粘贴代码后他自动给我缩进了，简直不要太烦人，格式能不能对齐啊。

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

**Comment by zhuqinggang** [comment]
Select the code and press "shift+tab" or "tab".Have a try.
github通用语言是英语啊朋友

**Comment by rebornix** [comment]
You can turn it off by setting `editor.autoIndent` to `false`.
