### ISSUE TITLE
Cannot debug npm script using Yarn

### ISSUE THREAD

**Issue by texastoland** [Microsoft/vscode#55103]
- VSCode Version: 1.26.0
- OS Version: macOS 10.13.6

Steps to Reproduce:

1. Use Yarn.
2. Create a npm script with `--inspect`.
3. Click run in script explorer.
4. It runs as expected.
5. Click debug in script explorer.
6. Debug console says `error Command "run-script" not found.`.

https://github.com/Microsoft/vscode/blob/e8b1ee0b4d016bc38bbc1cf06d6d1868760d5fe8/extensions/npm/src/tasks.ts#L322-L326

The Yarn command is `run` which is also an alias using npm. I recommend simply deleting `-script`. I'd PR if I knew how to write the test.

**Comment by weinand** [comment]
Please file this against the npm extension.

**Comment by texastoland** [comment]
@weinand how do I do that? The bug is in this repo (as shown in the description).

**Comment by weinand** [comment]
@texastoland sorry, I forgot that this is a built-in extension.

**Comment by texastoland** [comment]
I put a fix in the description. I just don't know where to write a test for it.

**Comment by egamma** [comment]
@texastoland good catch, thanks for the fix.
