### ISSUE TITLE
Errors generated that do not exist

### ISSUE THREAD

**Issue by rdavi10471a2** [Microsoft/vscode#55105]
project directory zipped and attached

[FinanceSeerV2.zip](https://github.com/Microsoft/vscode/files/2230321/FinanceSeerV2.zip)
Issue Type: <b>Bug</b>
![image](https://user-images.githubusercontent.com/6091414/43239606-846e1052-9058-11e8-9393-9783526aafd5.png)

tsconfig file
```json
{
    "compileOnSave": true,
    "compilerOptions": {
      
        "target": "es5",
        "module": "commonjs",
        "sourceMap": true,
        "outDir": "./JS",
        "allowJs": true
    }
}
```
project directory structure
```
financeseerv2
   .vscode
   CSS
   JS
     NodeModules
     Source
        divtextelement.js
        divtexelement.js.map
       financeseer.js
       financeseer.js.map
node_modules (standard node stuff here)
Source
   divTextElement.ts
   financeseer.ts
financeseer.html
package-lock.json
tsconfig.json
```

starting from opening this folder I can edit financeseer.ts by modifying anything and errors start appearing randomly in the file that are completely bogus in the problem pane
if i save/close he widows the  problem pane is cleared. this can be repeated over and over again.

also note that files are output to js/source 
when i specified only ../js 

---------------example financeseer.ts
```js
///<reference path="../node_modules/hyperhtml/index.js" />
class FinanceSeerApp {
    test :divTextElement;
    ElementId :string ="";
    $Element :JQuery
    Text:string ="";
  private myVar:number=80;
  constructor(pelementId:string,ptext :string){
        this.ElementId=pelementId
        this.Text=ptext;
        this.$Element=$("#"+this.ElementId)
        this.$Element.click((e) => this.onClick(e));
        this.$Element.text(this.Text)
        this.test=new divTextElement("test1","text")
        var data = {message: 'completly new string! add characters here inside quotes to cause errors'};
        hyperHTML.bind(document.querySelector('#root'))`<div style='background-color:cyan'> ${data.message} </span>`
      
  };
  onClick = (e):void =>{
      let  $elementid =$(e.currentTarget).attr("Id");
      alert($elementid)
      this.$Element.css('width',300+this.myVar);
      this.$Element.text("changed 2 a"+this.myVar++)

  };
  
}

window.onload = () => {
  let app = new FinanceSeerApp("testdiv","fwer")
  let app2 = new FinanceSeerApp("testdiv2","dsfa")
  console.log(app)
  console.log(app2)
};
```

  

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     P8700  @ 2.53GHz (2 x 2527)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.97GB (4.19GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-file-templates|bam|1.1.0
path-intellisense|chr|1.4.2
jsrefactor|cms|2.13.0
open-html-in-browser|cod|0.1.21
vscode-eslint|dba|1.4.12
vscode-generate-getter-setter|DSK|0.5.0
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.34
prettier-vscode|esb|1.5.0
json2ts|Gre|0.0.6
vue-snippets|hol|0.1.8
rest-client|hum|0.19.0
ts-extension-pack|loi|0.0.1
vscode-JS-CSS-HTML-formatter|lon|0.2.3
mssql|ms-|1.4.0
csharp|ms-|1.15.2
Go|ms-|0.6.84
debugger-for-chrome|msj|4.8.2
vetur|oct|0.12.5
tsimporter|pmn|1.2.14
vscode-css-peek|pra|2.1.0
typescript-hero|rbb|2.3.2
html5-boilerplate|sid|1.0.3
javascript-typescript|sou|0.0.7
move-ts|str|1.11.3
bootstrap4-vscode|the|4.3.0

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by mjbvz** [comment]
@rdavi10471a2 So it's working now? I don't see what you changed in the tsconfig

**Comment by rdavi10471a2** [comment]
it was working and now it has stopped again after I added more things from
NPM.
will try to send more details tonight.. how do I get to the site to attache
more items.

**Comment by mjbvz** [comment]
Please make sure to test on vscode insiders

**Comment by rdavi10471a2** [comment]
will do, i am starting from scratch and if it happens again i will put in
another ticket.
It is just so flaky any changes to files in bulk and it seems to lose its
mind and start reporting error all over the place.

**Comment by mjbvz** [comment]
Closing since we have not heard back on this issue
