### ISSUE TITLE
Intellisense and Go to Symbol not working with JavaScript

### ISSUE THREAD

**Issue by israelnyc** [Microsoft/vscode#55104]
Issue Type: <b>Bug</b>

I've been experiencing this issue starting with release 1.24 where intellisense and Go to Symbol (CTRL+SHIFT+O) don't work at all, with certain JavaScript files. All I see is the Loading... message or the animated progress bar. 

At first I thought it may have been related to large JavaScript files and the amount of symbols they contain since I am working with files some of which have thousands of lines of code. However, after trying with different projects, that wasn't the case. 

I think I have narrowed it down though to a simplified reproduction, at least based on the code I'm experiencing the issue with. I've been able to consistently reproduce it with the sample code below on two separate Windows 10 systems as well as on macOS 10.13.3, all with the latest insiders build with extensions disabled or no extensions installed at all. 

It seems that when updating an array by doing `arr[arr.length] = 'value'` vs. `arr.push('value')` multiple times, it causes intellisense to slow down drastically or not work at all. With the code below it is either really slow and eventually works or just doesn't work at all. Performance seems to get worse with each added line. 

When it fails to work, the process CPU usage also stays between 10% and 15% when those lines are in the file. Whereas if they are commented out or when in version 1.23.1, the process stays below 1%. 

![vscode-cpu-compare](https://user-images.githubusercontent.com/10267/43237464-ecc70146-9057-11e8-81c2-6a9d76d01dc9.JPG)

With the actual code I'm working with, there are many more such lines updating arrays and I think that is what causes it to never work at all. The only time I have seen it work is if I try it quickly after first opening the editor and before the Outline for the file is loaded. But that is inconsistent and it won't work on subsequent attempts.

Something else I noticed with the code below is that the issue will randomly not occur - seemingly when the editor has been left open a while and hasn't been touched - but only for a short while or until the file is modified. 

It works perfectly fine and with zero delay on version 1.23.1, but every release since then on both the stable and insiders versions have the same issue. 

``` javascript
function build() {
    var arr = [];

    arr[arr.length] = 'value'; 
    arr[arr.length] = 'value'; 
    arr[arr.length] = 'value';
    arr[arr.length] = 'value';
    arr[arr.length] = 'value';
    arr[arr.length] = 'value';
    arr[arr.length] = 'value'; 
    arr[arr.length] = 'value'; 
    arr[arr.length] = 'value';
    arr[arr.length] = 'value';
    arr[arr.length] = 'value';
    arr[arr.length] = 'value';
    arr[arr.length] = 'value';
    arr[arr.length] = 'value';
    arr[arr.length] = 'value';
    arr[arr.length] = 'value'; 
    arr[arr.length] = 'value';
    arr[arr.length] = 'value';
    arr[arr.length] = 'value';
    arr[arr.length] = 'value';
    arr[arr.length] = 'value';
    arr[arr.length] = 'value';
    arr[arr.length] = 'value';
    arr[arr.length] = 'value';
    arr[arr.length] = 'value'; 

    // arr.push('value');
    // arr.push('value');
    // arr.push('value');
    // arr.push('value');
    // arr.push('value');
    // arr.push('value');
    // arr.push('value');
    // arr.push('value');
    // arr.push('value');
    // arr.push('value');
    // arr.push('value');
    // arr.push('value');
    // arr.push('value');
    // arr.push('value');
    // arr.push('value');
    // arr.push('value');
    // arr.push('value');
    // arr.push('value');
    // arr.push('value');
    // arr.push('value');
    // arr.push('value');
    // arr.push('value');
    // arr.push('value');
    // arr.push('value');
    // arr.push('value');
}
```

VS Code version: Code - Insiders 1.26.0-insider (5fae91d61f12726e149fe5baed342eac2fbf8f88, 2018-07-25T02:04:01.629Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (20.87GB free)|
|Process Argv|C:\Users\Israel\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#26031
