### ISSUE TITLE
Missing keybinding for navigation in Quick Fix contextual menu

### ISSUE THREAD

**Issue by gibbok** [microsoft/vscode#55111]
The problem:

It is not possible to define custom shortcuts for Quick Fix contextual menu.

- Use latest stable build of VS code  and open a TypeScript project.
- Open the Quick Fix by intentionally making a mistake in the code.
- Press `CTRL + .` to open the Quick Fix contextual menu suggestions.
- It is possible to select an item from the menu by using UP/DOWN arrow key.
- ISSUE: it is no possible to define custom shortcuts in order to select the prev/next Quick Fix suggestion in the contextual menu.
Would be great to have customize selection of the prev/next suggestion, similarly to IntelliSense (example below): 
```
    {
      "key": "ctrl+k",
      "command": "selectPrevSuggestion",
      "when": "suggestWidgetMultipleSuggestions && suggestWidgetVisible && textInputFocus"
    },
    {
      "key": "ctrl+j",
      "command": "selectNextSuggestion",
      "when": "suggestWidgetMultipleSuggestions && suggestWidgetVisible && textInputFocus"
    },
```

**Comment by jrieken** [comment]
To my knowledge that isn't possible because we are using a native menu.

**Comment by refeiner** [comment]
so sad, i am trying to bind the up/down to 'j', 'k', and blocked here. is there any workaround?

**Comment by monkeylmj** [comment]
So sad, can't use shortcut to move in Quick Fix contextual menu break my coding experience. can you fix this bug quickly?

**Comment by Akuseru1** [comment]
please fix this quickly

**Comment by chuanqisun** [comment]
Please prioritize. The lack of custom binding is a productivity killer for vim-like users. The workflow is interrupted each time you have to reach for the arrow keys. And some linux-centric keyboards don't even have the arrow keys. They would have to press combo keys to get the arrow keypress event.

**Comment by PascalSenn** [comment]
is there any internal API do get the code actions? having them displayed in menu at the top like Quick Open would already solve this issue

**Comment by PascalSenn** [comment]
I created a extension as a workaround:
https://marketplace.visualstudio.com/items?itemName=pascalsenn.keyboard-quickfix

It uses the quick open picker to display codeactions. 
It is possible to navigate through these with the keyboard

**Comment by SeeminglyScience** [comment]
@PascalSenn did you figure out a good way to display "No code actions available"? That's the road block I ran into (though not really a big deal, just curious).

**Comment by PascalSenn** [comment]
@SeeminglyScience  i did not think about that. Added it in 0.0.4. 
Might take a few minutes to show up on the market place 
![image](https://user-images.githubusercontent.com/14233220/86533312-9d509380-bed0-11ea-98df-cb7cd7fbb195.png)

**Comment by Tizoner** [comment]
@PascalSenn could you please add a command like keyboard-quickfix.toggleQuickFix to open/close quickFix using the same command?

**Comment by PascalSenn** [comment]
Have a lot to do currently, but you can open an issue here:
https://github.com/PascalSenn/keyboard-quickfix/issues

**Comment by gibbok** [comment]
Currently as a work around I use the following [key biding](https://github.com/gibbok/settings/blob/master/vscode/keybindings.json) in `keybindings.json`, I hope you find it useful.

```json
[
  {
    "key": "ctrl+k",
    "command": "selectPrevSuggestion",
    "when": "suggestWidgetMultipleSuggestions && suggestWidgetVisible && textInputFocus"
  },
  {
    "key": "ctrl+j",
    "command": "selectNextSuggestion",
    "when": "suggestWidgetMultipleSuggestions && suggestWidgetVisible && textInputFocus"
  }
]
```

**Comment by desprit** [comment]
@gibbok 

It doesn't work for me. I added these mappings and navigation inside the popup window with suggestions isn't working. I don't have any other commands bound to these combinations.

**Comment by ckwong90** [comment]
I am also trying to use vim keyboard shortcuts for the quickfix menu. Seems there is no solution yet...

**Comment by diegonogueira** [comment]
My workaround is using the Hotkeys app

```
#IfWinActive, Visual Studio Code
^j::
Send, {Down}
return

#IfWinActive, Visual Studio Code
^k::
Send, {Up}
return

#IfWinActive, Visual Studio Code
^[::
Send, {Esc}
return
```

**Comment by finnmerlett** [comment]
> Currently as a work around I use the following [key biding](https://github.com/gibbok/settings/blob/master/vscode/keybindings.json) in `keybindings.json`, I hope you find it useful.
> 
> ```json
> [
>   {
>     "key": "ctrl+k",
>     "command": "selectPrevSuggestion",
>     "when": "suggestWidgetMultipleSuggestions && suggestWidgetVisible && textInputFocus"
>   },
>   {
>     "key": "ctrl+j",
>     "command": "selectNextSuggestion",
>     "when": "suggestWidgetMultipleSuggestions && suggestWidgetVisible && textInputFocus"
>   }
> ]
> ```

This works for the autocomplete menu very well (I use alt-j/k, but works great), however it doesn't work with the quick fix menu. For that you need the keyboard quickfix extension

**Comment by alanmrochadeveloper** [comment]
> My workaround is using the Hotkeys app
> 
> ```
> #IfWinActive, Visual Studio Code
> ^j::
> Send, {Down}
> return
> 
> #IfWinActive, Visual Studio Code
> ^k::
> Send, {Up}
> return
> 
> #IfWinActive, Visual Studio Code
> ^[::
> Send, {Esc}
> return
> ```
Is that for Linux? If so could you explain how do I apply that in my Linux(PopOS)! Linux noob user here. I really want that shortcuts workaround. Thanks in advance.

**Comment by alanmrochadeveloper** [comment]
BTW  a shallow workaround: Press "alt+enter" when the quick fix pops up on the screen, but you can't switch among options, but if there is only one option its will be enough.

**Comment by alanmrochadeveloper** [comment]
Well, I just figured out a solution for this issue, download AutoKey app for Linux and set this shortcut keyboard as you like. An example below with my preferences!
![image](https://user-images.githubusercontent.com/54696320/112708899-c4eaf000-8e93-11eb-9a97-e2931bc60872.png)

**Comment by MejanH** [comment]
still no default keybindings for navigating through the quick-fix list?

**Comment by iamWing** [comment]
I also want a default keybinding for this. Since I switch back and forth between Mac & Windows a lot I often use `ctrl + n` and `ctrl+ p` to navigate the menu a lot. I've basically mapped most of the keybindings to match my experience on mac but this one really caught me out as I can't navigate the menu with the same shortcuts.

**Comment by hasanmn** [comment]
Does anyone have any workaround for this issue?
I really like the idea of customizing keybinding for navigating in the context menu.

**Comment by ohechtl** [comment]
First, read the whole discussion before asking which is already been answered, second, use this extension, like it was said before: https://github.com/PascalSenn/keyboard-quickfix
This replaces the quickfix context menu with the quick open window, which keybindings can be customized

**Comment by hasanmn** [comment]
Thanks, @ohechtl. I read the discussion, but I missed the solution from @PascalSenn.
Thanks, @PascalSenn for the extension. Really helpful.

**Comment by justschen** [comment]
With the new Code Action Widget (which applies to the refactoring and source controls from the context menu, the lightbulb widget, and **quickfixes**), custom keybindings for navigation, selection, and previews have been added.

Currently the widget is under an experimental setting `"editor.experimental.useCustomCodeActionMenu": true`. Can also be found by going to Editor › Experimental: Use Custom Code Action Menu!

Take a look at this snippet for `keybindings.json`

`[
{ "key": "ctrl+k", "when": "CodeActionMenuVisible", "command": "focusPreviousCodeAction" },`
`{ "key": "ctrl+j", "when": "CodeActionMenuVisible", "command": "focusNextCodeAction" },
]`

**Comment by MejanH** [comment]
> With the new Code Action Widget (which applies to the refactoring and source controls from the context menu, the lightbulb widget, and **quickfixes**), custom keybindings for navigation, selection, and previews have been added.
> 
> Currently the widget is under an experimental setting `"editor.experimental.useCustomCodeActionMenu": true`. Can also be found by going to Editor › Experimental: Use Custom Code Action Menu!
> 
> Take a look at this snippet for `keybindings.json`
> 
> > ```json
> > [
> >   {
> >     "key": "ctrl+k",
> >     "when": "CodeActionMenuVisible",
> >     "command": "focusPreviousCodeAction"
> >   },
> >   {
> >     "key": "ctrl+j",
> >     "when": "CodeActionMenuVisible",
> >     "command": "focusNextCodeAction"
> >   }
> > ]
> > ```

The commands changed into `selectNextCodeAction` and `selectPrevCodeAction` in the new update.

**Comment by d-khomenko** [comment]
in the new action menu is no longer working hotkey selection on the first letter of the phrase, now only works with the arrows ...
 Is it just me who has this problem?

**Comment by justschen** [comment]
Couple modifications in the latest update! As @MejanH mentioned, the commands are changed into `selectNextCodeAction` and `selectPrevCodeAction` in the new update.

A problem that @d-khomenko brought up is resolved with changing `CodeActionMenuVisible` to camel-case - `codeActionMenuVisible`

```json
[
  {
    "key": "ctrl+k",
    "when": "codeActionMenuVisible",
    "command": "selectPrevCodeAction"
  },
  {
    "key": "ctrl+j",
    "when": "codeActionMenuVisible",
    "command": "selectNextCodeAction"
  }
]
````
