### ISSUE TITLE
Adopt FileSystemProvider for Git

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#55110]
I'm trying to fix https://github.com/eamodio/vscode-gitlens/issues/430 and I think my best option it to stop creating temp files and instead leverage the built-in git content provider (`git:` scheme). I have this solution pretty much working (though will require a bunch of burn in), but the biggest issue I'm having is when I'm showing a diff of a file that has been renamed or moved the open file command will fail because the path of the file doesn't match the working tree.

To fix this can we add an optional `workingPath` to `GitUriParams` and use it if it exists when executing the open file command?

The other challenge is that using the git content provider doesn't handle images, but I can probably just replicate the logic here:

https://github.com/Microsoft/vscode/blob/master/extensions/git/src/commands.ts#L255-L272

/cc @joaomoreno

**Comment by joaomoreno** [comment]
I see. We have the notion of the rename path in our Git model, but not in the URI. How could a Git extension API help you, instead of having additional fields on git uris?

**Comment by eamodio** [comment]
Doh -- got closed. I guess fixing the open file command, to detect the case where the file on disk doesn't exist and walk back from that commit to the working file -- which is what I do in GitLens in this case (and then store that working filename in the Uri)

**Comment by joaomoreno** [comment]
@eamodio Let's push for this. Would exposing [this `getURI` call](https://github.com/Microsoft/vscode/blob/f8092f7573e25b0e97ed0f161809daf0f644790c/extensions/git/src/commands.ts#L256) be enough?

**Comment by eamodio** [comment]
I think that will help some, but I've recently abandoned the usage of a `TextContentProvider` in favor of implementing a `FileSystemProvider` for git (see https://github.com/eamodio/vscode-gitlens/blob/develop/src/git/fsProvider.ts). Using that structure, it solves the encoding issues and image issues since it leverages all the existing work in vscode to handle those things. I also added it for more features than just to replace the `TextContentProvider` but so far it seems to be working out quite well.

**Comment by joaomoreno** [comment]
> I think that will help some, but I've recently abandoned the usage of a TextContentProvider in favor of implementing a FileSystemProvider for git

This is probably something that should also be done by git itself. Would possibly fix these issues: #36219, #48038, #48038

Maybe we can join forces as well and bring that over to the git extension and you could leverage it?

> somehow provide the Uri (or something) to the Open File command that is added in a diff view -- to handle renames, etc.

Hm... not sure I understand this one.

> And the other I would love, is a way to provide a title for an editor (like you can for a diff view), because right now formatting non-file Uri's in a way that is friendly in the editor tab is a pain.

Just talked to @bpasero about this yesterday. Guess what? https://github.com/Microsoft/vscode/commit/4e3f58f2f4e81fd6ebe5a5a7da7587c9247ce9ad#diff-81002b6983f6ca938fb1efc58cd9da2f

**Comment by joaomoreno** [comment]
> I'm also planning on implementing a search provider (as soon as that API is stable) so that you can search a git repo at a specific revision -- is that something else that could go in core?

It is definitely interesting!

> I mean that if I open a diff of `abc.txt` @ revision `xyz`, but in the working tree `abc.txt` is now named `abc.md` -- the Open File command will try to open `abc.txt` and fail. So for GitLens revisions, I have my own `Open File Revision` and `Open Working File` and `Open Working File` handles the renames and finds the correct working file.

I see... The current git extension doesn't really worry itself with anything other than `HEAD`, so this was never really addressed. Hmm. Let's leave this for GitLens for now.

Let's leave this issue open for the FileSystemProvider adoption.

**Comment by gjsjohnmurray** [comment]
Might [**isomorphic-git**](https://isomorphic-git.org/en) be a path to getting VSCode's built-in git support to a place where it can play nice with `FileSystemProvider`? Apparently isomorphic-git is [BYOFS](https://isomorphic-git.org/docs/en/fs) (Bring Your Own File System).

**Comment by TomasHubelbauer** [comment]
@wmhilton FYI the above suggestion. You can probably speak to this. :-)

**Comment by joaomoreno** [comment]
@eamodio The git extension now uses the file system provider and a barebones utility has appeared in its API:

https://github.com/microsoft/vscode/blob/master/extensions/git/src/api/git.d.ts#L189

Needs more work in there, depending on on the requirements from extensions, but it's a starting step.

**Comment by eamodio** [comment]
@joaomoreno Will we be supporting the directory traversal with the fs provider? That would enable breadcrumbs and workspace folder support.

**Comment by joaomoreno** [comment]
@eamodio You mean creating a fs view in which modified files would exist? It's a cool idea, but it would require me to go away from encoding extra information in the uri query params and rely solely on path. There were a few issues wrt using path only, very early on, but those might've been ironed over the years. Maybe it's worthwhile looking into once again. Something like:

- `gitfs://workingtree/...`
- `gitfs://index/...`
- `gitfs://merge/...`
