### ISSUE TITLE
Multiple selection doesn't work with custom titleBarStyle

### ISSUE THREAD

**Issue by Yanpas** [Microsoft/vscode#55112]
- VSCode Version: 1.25.1
- OS Version: kubuntu 18.04

Original bug report: https://github.com/JohnstonCode/svn-scm/issues/298

I've discovered this bug in svn VCS extension. When you select several items in the list-view and do some action (commit or patch) - you see only last one selected

**Comment by edgardmessias** [comment]
Steps:
* Change `window.titleBarStyle` to `custom`
* Open a GIT repository
* Change two or more files
* In SCM, stage selected files with context menu
* Only last selected file are staged

**Comment by kieferrm** [comment]
Reproduced on Win10.

**Comment by sbatten** [comment]
I believe this is a duplicate of #54112 which has been resolved in the latest insiders. Details can be found there. If you find that I have made a mistake, please re-open.
