### ISSUE TITLE
Inconsistency between disabling and uninstalling with dependencies

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#55118]
Issue Type: <b>Bug</b>

Small nit: When I have Azure App Service, Azure Functions and Azure Account installed and I uninstall Azure Functions, no prompt shows up because Azure Account cannot be uninstalled. When I disable Azure Functions I'm asked if I want to disable dependencies too and when I choose yes, the operation fails. Disabling is missing the smarts uninstalling has.

VS Code version: Code - Insiders 1.26.0-insider (e8b1ee0b4d016bc38bbc1cf06d6d1868760d5fe8, 2018-07-26T05:12:05.252Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (1.83GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_3367734|
|Screen Reader|no|
|VM|33%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
999-pack1|chr|0.12.3
regex|chr|0.2.0
ssh|chr|0.0.4
vscode-eslint|dba|1.4.12
Spot|der|0.4.0
ghlink|dt|1.0.2
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.34
rest-client|hum|0.19.0
autofilename|Jer|0.1.3
vscode-azureappservice|ms-|0.9.0
vscode-azurefunctions|ms-|0.10.0
vscode-cosmosdb|ms-|0.8.0
azure-account|ms-|0.4.2
azurecli|ms-|0.4.2
github-issues-prs|ms-|0.9.0
PowerShell|ms-|1.8.1
debugger-for-chrome|msj|4.8.2
vscode-docker|Pet|0.0.27
vscode-versionlens|pfl|0.21.1
vscode-open-in-github|sys|1.7.0
azure-iot-toolkit|vsc|1.1.0

</details>

**Comment by sandy081** [comment]
Yes, you are right. I can add this feature for disablement also

**Comment by sandy081** [comment]
With #55072 Uninstalling or Disabling an extension with dependencies will uninstall or disable the extension only. So this is no longer necessary to implement.
