### ISSUE TITLE
Can not load extensions market and extension can not install

### ISSUE THREAD

**Issue by forestriveral** [Microsoft/vscode#55113]
Issue Type: <b>Bug</b>

Installed vs code_1.25.1 in Ubuntu 16.04 but it failed to load the extensions market. Then error occurred, showing "an unknown error occurred. Please consult the log for more details".

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:47:35.732Z)
OS version: Linux x64 4.15.0-29-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3700)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Load (avg)|2, 2, 2|
|Memory (System)|15.61GB (6.06GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kieferrm** [comment]
@forestriveral Can you please open your dev tools from the command palette choosing `Developer: Toggle Developer Tools` or from the Help menu and provide us the logs? 

Pls also have a look at #53516 for a similar case. Thanks!
