### ISSUE TITLE
Ctrl + X hangs VS Code

### ISSUE THREAD

**Issue by yerzhant** [Microsoft/vscode#55126]
Issue Type: <b>Bug</b>

Pressing Ctrl + X  hangs VS Code

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:40:20.190Z)
OS version: Linux x64 4.15.0-29-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2866)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|15.10GB (5.30GB free)|
|Process Argv|/usr/share/code/code .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
clipboard-history|Anj|1.0.7
html-snippets|abu|0.2.1
npm-intellisense|chr|1.3.0
vue-peek|dar|1.0.2
vscode-eslint|dba|1.4.12
githistory|don|0.4.2
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.34
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.5.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
beautify|Hoo|1.3.2
path-autocomplete|ion|1.12.0
vscode-attrs-sorter|mrm|2.1.0
vscode-scss|mrm|0.6.2
vuejs-extension-pack|mub|1.1.2
vetur|oct|0.12.5
sass-indented|rob|1.4.9
partial-diff|ryu|1.2.0
vscode-multiclip|sle|0.1.4
vscode-status-bar-format-toggle|tom|1.4.0
JavaScriptSnippets|xab|1.7.0

</details>

**Comment by kieferrm** [comment]
Pls disable all extensions and try again. If it still happens, please provide concrete steps to reproduce. Thanks!
