### ISSUE TITLE
Improve refactoring

### ISSUE THREAD

**Issue by BeliliFahem** [Microsoft/vscode#55125]
I give an example on an Angular2 + project with a component ("my-component.html", "my-component.ts"). In the .ts file I have an "onFinishClicked ()" method.

#### Current Behavior
If I refactore (onFinishClicked), I have to manually rename it in the HTML file.

#### Desired Behavior 
If I refactore (onFinishClicked) the method, then all references to this method are renamed.

**Comment by mjbvz** [comment]
Please file this issue / feature request against the angular extension.
