### ISSUE TITLE
Problems ordering

### ISSUE THREAD

**Issue by ncannasse** [Microsoft/vscode#55120]
Haxe compiler - and many others that I know of - sometimes outputs several error messages for the same error, in order to give more complete information.

For instance:

````
A.hx:5 : incorrect type for parameter x
B.hx:66 : declared here
````

Or sometimes within the same file:

````
A.hx:100 : type X is missing field Y
A.hx:3 : declared here
````

However, because VS Code sorts problems on its own, it will give a file ordering and within-file ordering that can revert these statements, making it order to pinpoint the original error location.

I suggest adding the possibility to force the order of Problems to be kept the same as the compiler outputs. 

Another way would be for the task to be able to provide an "index" for sorting purposes, that would ensure that all messages with index N appear in order before messages with index N+1

**Comment by kieferrm** [comment]
The language extensions should adopt related diagnostics. We introduced that for that exact purpose. Here's is the API: https://github.com/Microsoft/vscode/blob/00821eaa6ab49876aefeaed891fd73630f756a09/src/vs/vscode.d.ts#L4032

**Comment by Gama11** [comment]
This is mostly about problems from tasks / problem matchers, not diagnostics, but I see you already created an issue to track that. 👍
