### ISSUE TITLE
Using absolute paths shows component but also shows infinite loading bar

### ISSUE THREAD

**Issue by piotr-kwiatek** [Microsoft/vscode#55121]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by piotr-kwiatek** [comment]
1. Set in settings:
{
    "javascript.preferences.importModuleSpecifier": "non-relative",
}

2. Create in main directory jsconfig.json file. Add there:
{
    "include": ["src/**/*"],
    "compilerOptions": { "baseUrl": "./src" }
}

Restart vsCode. From now you are able to use absolute paths - when you click on component link with ctrl - you will go there. 

Sometimes when I use this shows loading short bar (which is going from left to right) - and it's doing all the time, even after component is found and loaded.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?
