### ISSUE TITLE
code snippets for matching type

### ISSUE THREAD

**Issue by ackvf** [Microsoft/vscode#55129]
When invoking code completion on a finished keyword (so that it doesn't interfere with keyword completion), I would like to be able to insert an associated code snippet.

Instead of `prefix` use the `type` of a method.

```
// user snippets file
"snapshot.forEach": {
	"type": "firebase.database.DataSnapshot.forEach",
	"body": [
		"forEach(item => {",
		"  $1",
		"  return false // true breaks further enumeration",
		"})",
	],
	"description": "snapshot forEach"
}
```
Use case:

![image](https://user-images.githubusercontent.com/2313018/43252463-d7e01cf2-90c2-11e8-9b87-02b1c29c5f05.png)

![image](https://user-images.githubusercontent.com/2313018/43252767-9bd29504-90c3-11e8-9f47-5724ce43e215.png)

In this case, the `forEach` of a _firebase snapshot_ is specific in such a way that returning a truthy value at the end of an iteration cancels any further enumeration. This subtle feature can bite silently when used with arrows - this code snippet would remind me every time.

This code can lead to all sorts of funny behaviours.
```snapshot.forEach(item => myArray.push(item.val()))```

<hr/>
PS: Right now I am using this exact code snippet, but it is listed in hints for any `forEach` without context. 

```
"snapshot.forEach": {
  "prefix": "forEach",
  "body": [
    "forEach(item => {${1:",
    "  $2",
    "  return true // breaks further enumeration",
    "}})"
  ],
  "description": "snapshot forEach"
},
```

**Comment by jrieken** [comment]
Snippets aren't contextual and event the editor doesn't know anything about type et al. Snippets that require dynamic context (like types) are usually a good candidate for an extension (completion item providers can also return snippets).

**Comment by ackvf** [comment]
Can you please add a label to allow the community to pick it up?
