### ISSUE TITLE
Adding paren after losing focus adds too many parens

### ISSUE THREAD

**Issue by MarkKahn** [Microsoft/vscode#55133]
Issue Type: <b>Bug</b>

Keystrokes: `(<lose app focus, regain app focus>(`
Result: `((()))`

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7Y75 CPU @ 1.30GHz (4 x 1400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|16.00GB (2.66GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron VoiceNGO|
|Screen Reader|no|
|VM|38%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.27
sort-lines|Tyr|1.7.0
vscode-terminal-here|Tyr|0.1.1
vscode-custom-css|be5|2.7.1
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.12
prettier-vscode|esb|1.5.0
flow-for-vscode|flo|0.8.2
VS-code-vagrantfile|mar|0.0.7
theme-monokai-pro-vscode|mon|1.1.8
atom-keybindings|ms-|3.0.4
debugger-for-chrome|msj|4.8.2
remote-vscode|raf|1.1.0
gitconfig|sid|1.0.1
language-stylus|sys|1.9.2
quokka-vscode|Wal|1.0.135
wallaby-vscode|Wal|1.0.92
markdown-all-in-one|yzh|1.6.0
vscode-proto3|zxh|0.2.1

(2 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
![paren-focus](https://user-images.githubusercontent.com/876920/45112190-d3b5ff80-b0fb-11e8-91ef-dae652fea3d5.gif)

I can't reproduce this issue, please see gif above. Could you please try and let me know if you can still see the problem or provide a gif to help troubleshoot?

**Comment by MarkKahn** [comment]
I can no longer repro.  Was probably fixed in one of the last two monthly updates
