### ISSUE TITLE
Windows attach debugger results in "stdout maxBuffer exceeded" error (with launch.json - processId settings)

### ISSUE THREAD

**Issue by Vukasin92** [Microsoft/vscode#55134]
- VSCode Version: 1.25.1
- OS Version: Windows Server 2016 Datacenter v1607

Steps to Reproduce:

1.The issue is basically the same as in https://github.com/Microsoft/vscode/issues/15940, except it occurs for windows attach debugging configuration, while the original issue was fixed for nodejs.

**Comment by Vukasin92** [comment]
It looks like this:
       {
            "name": "(Windows) Attach",
            "type": "cppvsdbg",
            "request": "attach",
            "processId": "${command:pickProcess}"
        }

But I just checked again and the issue has resolved itself somehow. I'll close this issue for now unless it happens again. Thanks.

**Comment by weinand** [comment]
Thanks for closing.
And please file issues always against the correct extension (in the above case it would have been  https://github.com/Microsoft/vscode-cpptools/issues).
