### ISSUE TITLE
Python 2.7 occasionally raises exceptions in integrated terminal when using logger methods

### ISSUE THREAD

**Issue by KornephorosDk** [Microsoft/vscode#55131]
Using the logger method from the logging module with an empty string as message (e.g. `logger.error('')`) in the integrated terminal raises the following exception occasionally (with no apparent pattern):
```
Traceback (most recent call last):
  File "C:\Python27\Lib\logging\__init__.py", line 880, in emit
    stream.write(fs % msg)
IOError: [Errno 0] Error
```
This happens when using Python 2.7.10. Also tested on Python 3.6.5 with no problems. Additionally, the problem does not occur using Windows Powershell.
The problem seems to have debuted after recent Windows upgrade.

- VSCode Version: Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:43:53.668Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64
- OS Version: Windows 10 Enterprise Version 10.0.16299 Build 16299

- Extensions: Python

Steps to Reproduce (Code):

```
import logging

logger = logging.getLogger(__name__)
logger.addHandler(logging.StreamHandler())

for i in range(0, 100):
    logger.error('')
```

Replacing `logger.error('')`  with `print('')` occasionally produces the following error message instead:
```
close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr
```

Does this issue occur when all extensions are disabled?: Yes

**EDIT:** Just got the exception using a non-empty string as message (e.g. `logger.error('message')`)

**Comment by Tyriar** [comment]
This was a bug in Windows 10, you'll need to update.

**Comment by Tyriar** [comment]
See https://github.com/Microsoft/vscode/issues/36630
