### ISSUE TITLE
Extension API: code-structure as object

### ISSUE THREAD

**Issue by MarcelZOI** [Microsoft/vscode#55138]
Hey, it would be nice if there a possibility that i get the code of the active Editor as json or as another object? So for example i what the line of the closing bracket of a function, or of a while loop or something else.

so if the active editor contains this code:
```js
function hello (name) {
  if (name !== "") {
    for (var i = 0; i < 5; i++) {
      console.log("Hello, " + name);
    }
  }
}
```

i get back something like this:

```json
{
  "content": [
    {
      "type": "function",
      "name": "hello",
      "starting": "0",
      "end": "6",
      "content": [
        {
          "type": "if",
          //[...],
          "starting": "1",
          "end": "5",
          "content": [
            //{[...]}
          ]
        }
      ]
      //...more such as parameters....and so one,
    }
  ]
}
```

What do you think?

**Comment by jrieken** [comment]
That is out of the scope of just being an editor. Something like a generic syntax tree is something an extension good and should do because it requires language specific knowledge.

**Comment by MarcelZOI** [comment]
Hey @jrieken, thanks for answering, but i meant that not a frontend thing in the ui. I want this feature for making extension. I guess that makes it easier to write extension that find the closing bracket. For example i wrote an extension that shows me the starting line of a function, when hovering over a closing curled bracket. with that kind of api it is just one line to get the closing bracket. otherwise you have to do a lot of regex and checking.
