### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by KievJunta** [Microsoft/vscode#5513]
private char GetChar()//Метод возвращающий 
Comment isn't become green

**Comment by dbaeumer** [comment]
@KievJunta Is this C#?

**Comment by KievJunta** [comment]
@dbaeumer  yes, C#. If there is no space between class declaration and comment, comment isn't become green.

**Comment by dbaeumer** [comment]
@jrieken assigning to you. Not sure were we get the TextMate grammar from

**Comment by aeschli** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#225

**Comment by dbaeumer** [comment]
This issue was moved to OmniSharp/omnisharp-server#212
