### ISSUE TITLE
editor.codeActionsOnSave organizeImports and editor.formatOnSave with search & replace doesn't respect formatOnSave

### ISSUE THREAD

**Issue by vincentbriglia** [Microsoft/vscode#55132]
- VSCode Version: Version 1.25.1 (1.25.1)
- OS Version: MacOS 10.13.4 (17E199)

Steps to Reproduce:

1. set user settings 
```
"editor.formatOnSave": true, 
"editor.codeActionsOnSave": {
  "source.organizeImports": true
}
``` 
2. create a handful of files with long import statements like 

```
import {
  IComponentInterface1,
  IComponentInterface2,
  IComponentInterface3,
  IComponentInterface4,
  IComponentInterface5,
  IComponentInterface6,
  IComponentInterface7,
  IComponentInterface8,
  IComponentInterface9,
  IComponentInterface10,
  IComponentInterface11,
  IComponentInterface12,
} from '../component';
```

3. leave some files open and close some others

3. do a search and replace for `IComponentInterface1` and replace it with `IDummy` 

note that all files, regardless of whether they're open in the editor or not, have imports that have reverted to a one-liner 

```
import { IDummy, IComponentInterface2, IComponentInterface3, IComponentInterface4, IComponentInterface5, IComponentInterface6, IComponentInterface7, IComponentInterface8, IComponentInterface9, IComponentInterface10, IComponentInterface11, IComponentInterface12 } from '../component';
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
> note that all files, regardless of whether they're open in the editor or not, have imports that have reverted to a one-liner

That's the undesired case, right? Does this reproduce without extension being enabled? Does this reproduce when doing a simple edit and save operation?

**Comment by vincentbriglia** [comment]
i'd expect that it respects the user settings, and no, this only happens when doing a search/replace in a workspace

**Comment by jrieken** [comment]
> i'd expect that it respects the user settings,

What user setting? The fact that everything goes to one line looks like some formatter is involved...

**Comment by vincentbriglia** [comment]
Hi, 

i used the user settings 

```
"editor.formatOnSave": true, 
"editor.codeActionsOnSave": {
  "source.organizeImports": true
}
```

and disabled all extensions in my editor in order to reproduce the behavior. 

the behavior described in [the first comment](https://github.com/Microsoft/vscode/issues/55132#issue-344767090) only happen when trying to search and replace in a project, it doesn't happen when saving a single file. 

the expected behavior is that a search and replace respects the same formatting as if opening, editing and saving a single file.

**Comment by jrieken** [comment]
I can still not reproduce. Please update with more step/context or share the project with. Thanks
