### ISSUE TITLE
Problem with VSCODE

### ISSUE THREAD

**Issue by FernandoGaranito** [Microsoft/vscode#55141]
Hello everyone
I was trying to use vscode but an error insists on it happening.
Initially I was finding it strange that I could not edit the vscode console, then I understood that it is in the read-only version

So I discovered that just open the "file" tab and go in the settings to enable editing, but whenever I try to open the file tab the vscode simply closes without any error warning, it just closes. I've already tried uninstalling and installing again and the problem continues.

Another problem is in the code that appears on the console when I command to run. The result of the code does not appear, even if it is right, and it only appears that the code has run and nothing else.

Can someone please help me?

**Comment by kieferrm** [comment]
@FernandoGaranito I have a hard time understanding your problem. Can you record a video and share? Thanks!
