### ISSUE TITLE
import is typed and triggers an error even with all typings disabled

### ISSUE THREAD

**Issue by Janne252** [Microsoft/vscode#55142]
- VSCode Version: 1.25.1
- OS Version: Windows 10 Pro 64-bit

Steps to Reproduce:

1. Create an empty directory and open it in VS Code
2. Create `tsconfig.json` with the following content:
```js
{
    "compilerOptions": {
        "noLib": true,
        "types": [],
        "typeRoots": []
    },
    "include": [
        "./**/*.ts"
    ],
}
```
3. Create a new TypeScript file with the following content:
```typescript
import();
```
4. Note how the `import();` statement refers to dynamic import (unexpected behavior).  Type in `require();` and see how it results in "Cannot find name 'require'" (expected behavior)
![image](https://user-images.githubusercontent.com/4705573/43262092-9e401766-90e7-11e8-86aa-50d48403315b.png)

If you use `//@ts-ignore`, an error will be reported about the missing Promise type:
![image](https://user-images.githubusercontent.com/4705573/43262337-7355fbdc-90e8-11e8-9225-06563f6a6e24.png)

### Workaround
If you use `//@ts-ignore` AND declare a type for the Promise, the error disappears (VS Code forces Promise to have at least one type parameter, which sounds like import & Promise typing requirements are hardcoded)
![image](https://user-images.githubusercontent.com/4705573/43262428-c140ed48-90e8-11e8-8a56-a1f8a7505dfe.png)

Even with the declared type for Promise `//@ts-ignore` is still required, otherwise VS Code checks if the module exists:
![image](https://user-images.githubusercontent.com/4705573/43262501-fc19cae8-90e8-11e8-8b42-0d759824390c.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#25986
