### ISSUE TITLE
Remove references to specific menu entries from menubar.ts

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#55149]
As discussed in https://github.com/Microsoft/vscode/pull/54826
I believe all references to specific menu entries should be removed from menubar.ts
These menu entries should somehow be registered from their respective areas. 'debug' from `debug.contribution.ts` and so on.

**Comment by bpasero** [comment]
I think this can probably be closed by now, at least I cannot find specific debug entries anymore.

**Comment by isidorn** [comment]
Yes this looks better now, closing
