### ISSUE TITLE
Jump to declaration multiple workspaces

### ISSUE THREAD

**Issue by jasonbronson** [Microsoft/vscode#55153]
Jump to declaration goes to incorrect files in another folder in workspace when using multiple files with same file and method names.

- VSCode Version: 1.25.1
- OS Version: 10.13.6 OSX

Steps to Reproduce:

1. create multiple workspaces and add multiple folders with identical library files / classes
2. open one of the workspace folders and do a jump to declaration and it will jump to a declaration in another folder in the workspace not the currently working in.

Does this issue occur when all extensions are disabled?: Yes

**Comment by kieferrm** [comment]
@jasonbronson pls provide an example workspace. Easiest would be if you have a GitHub repo that contains the workspace. Thanks!

**Comment by jasonbronson** [comment]
@kieferrm  

While setting this up for you I realized you don't even need a workspace for this issue. Just two folders does the trick.

Step 1  create a folder vscodebug
Step 2 open in vscode the folder with my github repo in it 
https://github.com/jasonbronson/BugVSCode
Step 3 open up posts.php under this folder in editor
/pcentral/wp-content/themes/theme1/libraries/posts.php
Step 4 close the posts.php file
Step 5 open up pressreleases.php file under
/pmasters/wp-content/themes/theme2/libraries/pressreleases.php
Step 6 Highlight "Posts" under Pressrelease extends Posts
Step 7 hit go to declaration
Step 8 notice it jumps to the top folder with that file.

I believe if you're in a folder the top level would be all that it should be searching for not going to other folders.
Example I open up top folder 1 to copy some code into the library file I'm building into folder2 now this bug occurs.

**Comment by kieferrm** [comment]
@jasonbronson I assume you have the PHP extension installed. VS Code does not have any deep PHP understanding out of the box and the PHP extension is responsible for telling VS Code where to find the declarations for a given symbol.

Please file the issue against the one you use. Thanks a ton!
