### ISSUE TITLE
Recent menu in menubar.ts feels like a hack

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#55150]
How we currently [add](https://github.com/Microsoft/vscode/blob/742767ef9c249b3102fe59b7023221e21eb16afd/src/vs/code/electron-main/menubar.ts#L478) the recent menu in the `menubar.ts` feels as a total hack. 
The open recent should be a submenut, all those entries shuold be added to that submenu

**Comment by bpasero** [comment]
Is this good now?

**Comment by isidorn** [comment]
Well there is still an if check.
I thought we could add this menu entry through our contribution mechanism.
Though if there are no plans to do this or if it is not feasable it is fine for @sbatten to close this issue
