### ISSUE TITLE
Word under cursor wrong highlight the same words

### ISSUE THREAD

**Issue by pixmaster** [Microsoft/vscode#55158]
Issue Type: <b>Bug</b>

Sometimes when I click on some word all found words was highlighted with offset. And if I wanted to rename this variable it replaced only selected part of words.
![image](https://user-images.githubusercontent.com/3305295/43271249-b56e670e-90ff-11e8-9d0f-e381c4963655.png)

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:11.471Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (2.35GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.12
githistory|don|0.4.2
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vscode-styled-components|jpo|0.0.21
PowerShell|ms-|1.8.1
indent-rainbow|ode|7.2.2
guides|spy|0.9.2
gitblame|wad|2.4.2
vscode-todo-highlight|way|1.0.4

</details>

**Comment by alexandrudima** [comment]
This looks like the TS service is using out-of-sync files.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by pixmaster** [comment]
In the latest (1.26.1) and with all extensions **enabled** it doesn't reproduce.
