### ISSUE TITLE
Workplace Settings Not Persisting in Visual Studio Code

### ISSUE THREAD

**Issue by darrenbrett** [Microsoft/vscode#55155]
We are using VSC and the prettier extension in our Node project to keep our formatting consistent. I am noticing that when I set some workplace settings, that those settings work -- for a while. However, when I close out the project and re-open later, even though those same workplace settings are still showing, they don't seem to be taking effect. Specifically I'm referring to auto-formatting happening upon the saving of a file -- `"editor.formatOnSave": true`. 

Here are my workplace settings:

```
    {
      "jshint.enable": true,
      "jshint.options": {
        "esversion": 6,
        "moz": true
      },
      "git.ignoreLimitWarning": true,
      "editor.tabSize": 2,
      "editor.detectIndentation": false,
      "editor.formatOnSave": true,
      "prettier.printWidth": 300,
      "javascript.suggestionActions.enabled": false
    }
```

Supposedly these workplace settings are supposed to override my user settings. But this doesn't seem to be happening consistently.

**Comment by sandy081** [comment]
@darrenbrett To make the problem simpler to understand are you reporting following?

- Open a node project in VS Code
- Have `"editor.formatOnSave": true` in workspace settings
- Reload the VS Code window

Format on save is not working?
