### ISSUE TITLE
Prompt before removing recent items when path not found

### ISSUE THREAD

**Issue by eidylon** [microsoft/vscode#55160]
Issue Type: <b>Bug</b>

Right now when clicking a folder from the "recent" list, if it "doesn't exist", it is automatically removed. 
This is VERY annoying. Proper behaviour would be to notifiy that it is not accessible, and then PROMPT if we want to remove it or not.

Very often I work on projects that are on network locations. Sometimes network locations get dropped, or not not reconnected on login. 
So I go to open the project, and then it tells me it doesn't exist. When in reality, I just need to reconnect the network drive and then try again. 

But now I can't because VS automatically removed it, and I wind up having to renavigate to it again and open it new.
Horrible UX.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.96GB (7.60GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe \\xweb2\wwwroot\net35.test.xiacon.com\nycdoh|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icontheme-nomo-dark|be5|1.3.6
xml|Dot|2.3.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.3
beautify|Hoo|1.3.2
minify|Hoo|0.3.0
classic-asp-html|jtj|0.1.0
prettify-json|moh|0.0.3
mssql|ms-|1.4.0
python|ms-|2018.7.1
csharp|ms-|1.15.2
PowerShell|ms-|1.8.1
qub-xml|qub|1.2.1
vscode-sql-beautify|sen|0.0.4
html-preview-vscode|tht|0.1.1

</details>

**Comment by zspitzer** [comment]
this is really annoying bug with Win10 in general about refreshing network drives, it would be great if in addition to not removing the drives, if VS Code could attempt to automatically refresh the network mapping too

**Comment by eidylon** [comment]
> 
> 
> this is really annoying bug with Win10 in general about refreshing network drives after rebooting, it would be great if in addition to not removing the drives, if VS Code could attempt to automatically refresh the network mapping too

True... attempt an automatic refresh first. If it _still_ can't be found, then prompt the user about whether to remove it or not. To give them a chance to go reconnect the network location first. Maybe the prompt should actually have three options... 

`[ Retry ]   [ Remove ]   [ Cancel ]`

**Comment by zspitzer** [comment]
the refreshing of network drives has actually been fixed in Windows 10 build 17763.168
https://support.microsoft.com/en-us/help/4469342/november292018kb4469342osbuild17763167

**Comment by eidylon** [comment]
> 
> 
> the refreshing of network drives has actually been fixed in Windows 10 build 17763.168
> https://support.microsoft.com/en-us/help/4469342/november292018kb4469342osbuild17763167

That's good. 👍🏼 Though this issue in VSCode still needs to be addressed for other issues. In my case, what happens is occasionally my account will get locked out over night. I of course don't know this until I try to access the network. So I open VSCode, try to open a network folder from `Recents`, and it says it doesn't exist and removes it. In reality I just needed to get my account unlocked, and then the folder would've existed. So the VSCode issue still has a detrimental impact.
