### ISSUE TITLE
Remember state of collapsible menu in Variables when debugging

### ISSUE THREAD

**Issue by alete89** [Microsoft/vscode#55162]
When debugging at a breakpoint, every time you do "step over" or "step into", variables are reloaded and the state of the tree is lost. It would be great to keep track of that state in order to ease the debugging.

I made an awful gif to illustrate
![debug](https://user-images.githubusercontent.com/4999277/43272472-68990986-90d0-11e8-9ebc-c53069c328ca.gif)

**Comment by weinand** [comment]
please file this issue against the debug extension your are using.

**Comment by alete89** [comment]
sorry, I thought it was built in vscode. Thanks.
