### ISSUE TITLE
Bad arguments: Code path doesn't seem to exist: C:\Program Files\Microsoft VS Code\Code.exe

### ISSUE THREAD

**Issue by surfarri** [Microsoft/vscode#55165]
Subject says it all.  My VS Code is installed on the D:\, if that matters.

**Comment by kieferrm** [comment]
Pls provide more detailed steps. Thanks!

**Comment by surfarri** [comment]
VSCode was previously installed on C:, then I performed a "Reset" on my PC.  After the reset, I re-installed VSCode on the D: drive.  Once I received notification for an update, I tried to update.  I referred to steps in one of the issues above, and did find that the registry references to VSCode were still pointing at C:.  I think the issue might come from not having uninstalled (removing those registry items), or installing to a new drive and the installer steps not overwriting the previous registry entries if the destination changed from what was previously there.

**Comment by joaomoreno** [comment]
Yep, please uninstall and remove all registry keys related to VS Code. Then, reinstall.
