### ISSUE TITLE
Unusable and laggy when used with NVIDIA G-SYNC monitor

### ISSUE THREAD

**Issue by bording** [Microsoft/vscode#5516]
I recently upgraded to a new monitor that supports NVIDIA's G-SYNC refresh rate syncing technology, and ever since then, Visual Studio Code is completely unusable if I have G-SYNC enabled.

Whenever the window has focus, graphical updates for the entire screen slow to a crawl, because something in VS Code is triggering G-SYNC's ability to adjust the refresh rate of the monitor to match some internal frame rate of the application. Using a built-in feature of the monitor, I can see that the refresh rate is altering based on my interactions with the window, and in some cases dropping to single digit values!

I've seen this behavior in other applications, and the thing they all have in common is that they are all using Electron. I suspect the problem is actually in something Electron is doing with its version of the Chromium code, but I don't know enough about the changes they've made to track down the exact cause. Chrome itself does not exhibit this behavior.

I have found and commented on the following upstream issues:

https://github.com/electron/electron/issues/2767
https://github.com/electron/electron/issues/3026

While I know this is actually an Electron problem, I'm posting this here to help raise awareness of the issue, and perhaps get some more traction to actually get this fixed for everyone using Electron.

- VSCode Version: 1.0.0
- OS Version: Windows 10 Pro 10586.218

Steps to Reproduce:

1. Get a monitor that supports G-SYNC and attach it to a system with an NVIDIA graphics card

2.  Enable G-SYNC for windowed and full screen mode in the NVIDIA control panel:
![gsync](https://cloud.githubusercontent.com/assets/753669/14659305/a940e610-0668-11e6-9bea-224a0abf3b26.png)

3. Open up Visual Studio Code and try to use it

**Comment by dbaeumer** [comment]
@bpasero I move this to you since this seems to be an underlying electron issue and can only be fixed there.

**Comment by bpasero** [comment]
@bording we have an internal version of VS Code running with the latest Electron that includes Chrome 49. Can you give [1] a try to see if it changes anything?

[1] https://az764295.vo.msecnd.net/alpha/c83fa467d071a784a3cdeacc69c29fdfdbc91fce/VSCode-win32-alpha.zip

**Comment by bording** [comment]
@bpasero I just tried the version you linked, and there is no change in behavior. It's doing the same thing as 1.0.0.

Looks like it still hasn't been fixed in Electron yet.

**Comment by bpasero** [comment]
Ok thanks.

**Comment by bording** [comment]
I do have a laptop that has a touchscreen, but that is a different machine than the one that has the G-SYNC monitors.

**Comment by alexandrudima** [comment]
Ok, I was just doing a pass to check if you're hitting #12036. I guess not.

**Comment by bording** [comment]
That electron issue does give me some ideas for investigating the problem I'm seeing a bit more, so thanks for bringing it up.

**Comment by bpasero** [comment]
@bording also note that our insiders release got a major Chrome/Electron update. Maybe you give it a try: 
You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by bpasero** [comment]
Please reopen if this still happens with our 1.6.0 release.

**Comment by bording** [comment]
@bpasero Just had a chance to try the latest insiders release, and it looks like the problem has been fixed! Do you happen to know what might have fixed it? If so, have a link to the issue?

**Comment by bpasero** [comment]
@bording no unfortunately not. We updated Electron which brought major Chrome updates (from 49 to 52) so I think it got fixed meanwhile in Chrome.

**Comment by bording** [comment]
> @bording no unfortunately not. We updated Electron which brought major Chrome updates (from 49 to 52) so I think it got fixed meanwhile in Chrome.

If it was something in Chrome, that would be interesting since Chrome itself has never exhibited the problem.

I took a look at the Electron release notes and didn't see anything obvious there either.

Always fun when a problem mysteriously gets fixed, because if it wasn't intentional who knows if it will mysteriously break again in the future. 😟
