### ISSUE TITLE
Links in settings descriptions don't work for search results

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#55179]
From https://github.com/Microsoft/vscode/issues/54690#issuecomment-408164843

- Do a search in the settings editor
- Click a link
- Nothing happens

If the setting is in the search results, we should reveal it. If it isn't, we should clear the search and reveal it.

**Comment by roblourens** [comment]
6f010b081e1fc4a99e5edd007f6c6ce8bdba0e84

**Comment by sandy081** [comment]
Nothing happens when clicking on a setting link that is filtered out

- Search for `detect inde`
- Click on the links in the description of indentation setting.

Nothing happens

**Comment by roblourens** [comment]
I'm not sure what should happen in that case. Clear the search query? That might be unexpected.

**Comment by sandy081** [comment]
I thought you are already doing it as said in the description

**Comment by roblourens** [comment]
Now it clears the search and focuses that setting. I'm not sure how I like that, it seems unexpected, but I'll try it out. I did fix the input box so that "undo" will work in this case and you can get your search query back.

Another option would be to replace the search value with the key of the clicked setting, but that seems inconsistent from the normal way.
