### ISSUE TITLE
New "weekly" Option for "Update: Channel" Setting

### ISSUE THREAD

**Issue by Chiramisu** [Microsoft/vscode#55174]
I have searched existing issues and not found this request.

While I appreciate the nightly "default" builds, I would much prefer a **"weekly" channel** as the perfect balance. If anything ever broke, I could simply change back to the nightlies for a cycle.

Even [this vscode blog post](https://code.visualstudio.com/blogs/2016/05/23/evolution-of-insiders) notes that the "benefits and the difference between weekly and nightly builds was actually low."

**Comment by kieferrm** [comment]
@Chiramisu we also said
> We decided that the overhead of releasing three different builds outweighed the benefits

and that statement still applies. We won't go back to three builds.

**Comment by Chiramisu** [comment]
Pardon my ignorance, but would you kindly explain why adding an option to selectively update only one out of the seven builds that you're already doing anyway, adds additional overhead? In my mind, the "channel" is just a simple filter than selectively ignores certain builds based on the preferred frequency.

**Comment by kieferrm** [comment]
The overhead is not creating the build. The overhead is in managing GH issues related to the nightly, weekly, and monthly builds. And in dealing with questions like "When we break do we rebuild it?" etc. If we do it, we would do it "right" and thus we would rebuild broken weeklies. We would have to maintain then a weekly branch and would have to retest... We spend our time better when we push master forward.
