### ISSUE TITLE
code causes desktops to switch undesirably

### ISSUE THREAD

**Issue by stevenbrix** [Microsoft/vscode#55172]
Issue Type: <b>Bug</b>

i'm trying to open the current directory using vs code by doing "code ." which is opening the folder in an existing instance of vs code on a separate virtual desktop which is incredibly annoying.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:11.471Z)
OS version: Windows_NT ia32 10.0.17723

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.79GB (16.50GB free)|
|Process Argv|c:\Program Files (x86)\Microsoft VS Code\Code.exe .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.17.7
csharp|ms-|1.15.2
node-debug2|ms-|1.26.6
createGUID|nwa|0.0.2
vscode-react-native|vsm|0.6.13
t4-support|zbe|0.4.2

</details>

**Comment by kieferrm** [comment]
@stevenbrix this only happens when the folder is already open on the other desktop. If the workspace is not open we open the new window on the current desktop.
