### ISSUE TITLE
Is vsocde can support tpl files?

### ISSUE THREAD

**Issue by biij5698** [Microsoft/vscode#5517]
It seems that vscode can not support tpl files like html

**Comment by dbaeumer** [comment]
@biij5698 what kind of template files are you referring to? Can you give me an example?

**Comment by biij5698** [comment]
Oh,Your staff have told me the answer:
Something like:
"files.associations": {
	"*.tpl": "html"
}
in your user preferences may work.
And  I have tried this way,This can be!
Thanks!

**Comment by biij5698** [comment]
@dbaeumer

**Comment by biij5698** [comment]
you can close this issues,Thanks vscode,I have already fallen in love with vscode.It was wonderful!
