### ISSUE TITLE
New project dialog  

### ISSUE THREAD

**Issue by rypz79** [Microsoft/vscode#55178]
Issue Type: <b>Feature Request</b>

Hello,

Create new project dialog (Project->New project) to select the:
1) Language C,C++,PHP,JAVA,PYTHON...(whatever is installed)
2) Templates
3) Linking & Compiling flags and libraries 
4) Debugging

Create new file dialog (File->New File) within the project  to select the:
1) Type of the file source, header, script, object, class...
2) Templates

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:40:20.190Z)
OS version: Linux x64 4.15.0-29-generic

**Comment by nealot** [comment]
Try out https://github.com/visualzoran/vz-file-templates.
