### ISSUE TITLE
C# syntax coloring is broken inside of multiline interpolated strings when a line starts with a placeholder

### ISSUE THREAD

**Issue by klick-barakgall** [Microsoft/vscode#55185]
Issue Type: <b>Bug</b>

I apologize if this should actually be in the csharp extension issues, but I feel like syntax coloring is done in conjuction between the extension and vscode so I'm not really certain where the issue really lies.

Place the following code in a *.cs file:

```
string strParam = "Some string";
string syntaxColoringMessed = $@"
I am a multiline interpolated string with a parameter: {strParam}
Everything is fine except when a line STARTS with a parameter:
{strParam} <-- Not colored even though it compiles fine! grabbing
the strParam value.

However it's even worse when an interpolation includes another string:
{"some string..."}

";
```

Please see the following image:
![vscode-syntax-coloring-smell](https://user-images.githubusercontent.com/8572438/43285123-fcf9b4d4-90eb-11e8-8e54-bb773655d7af.png)

Note that despite the syntax coloring this compiles fine.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.63GB (19.90GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\_projs\OverKlock\CM|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.15.2

</details>

**Comment by klick-barakgall** [comment]
I have looked for duplicate issues prior to posting but didn't find anything that I feel is relevant.

Also I think this issue has been around for a really long time but I've been too lazy to post an issue. Apologies for that :S.

**Comment by aeschli** [comment]
This issue was moved to dotnet/csharp-tmLanguage#131
