### ISSUE TITLE
Load extension based on project or file types in workspace 

### ISSUE THREAD

**Issue by akankshagaur** [Microsoft/vscode#55183]
Hi,

Can we add a feature to enable or disable extensions based on file types or language type in work space? 
Like: enable Angular extensions if angular.json is present in the folder, maven extensions if pom.xml is present etc

Right now, user needs to enable and disable extensions for each workspace which is a tedius task. 

Thanks

**Comment by ramya-rao-a** [comment]
These extensions get activated based on file types in the first place. Any reason you feel the need to disable them when not working on the corresponding file types
