### ISSUE TITLE
Unexpected cursor behavior with subword navigation

### ISSUE THREAD

**Issue by kleber-swf** [Microsoft/vscode#55184]
It's just me or the subword navigation is kinda not the way it should be?

For example, inside this piece of code:
```typescript
GameObject.configure(this, config);
```
I would expect the cursor to stop at:
```
|Game|Object|.|configure|(|this|, |config|)|;|
```

But actually it stops at
```
|Game|Object|.configure|(this|,| |config|);|
```
when going forward, and
```
|Game|Object.|configure(|this,| |config|);|
```
when going backward.

The overall issues are the cursor is not stopping at all word separators and it is not behaving the same way when going forward and backward.

Beside that, I loved the feature :smiley:

Tested with VSCode Insiders version with all extensions disabled too.

<details><summary>VSCode Info</summary>
Version: 1.25.1<br>
Commit: 1dfc5e557209371715f655691b1235b6b26a06be<br>
Date: 2018-07-11T15:43:53.668Z<br>
Electron: 1.7.12<br>
Chrome: 58.0.3029.110<br>
Node.js: 7.9.0<br>
V8: 5.8.283.38<br>
Architecture: x64
</details>

**Comment by alexandrudima** [comment]
This has been fixed in the meantime via a4a5b590ec996f64eb0675dedd80adf941333777
