### ISSUE TITLE
Failed to install VS Code update

### ISSUE THREAD

**Issue by arebee** [Microsoft/vscode#55181]
- VSCode Version: 
Visual Studio Code - Insiders
Version: 1.26.0-insider
Commit: 90fc7e66e2e10f643871b42f9c0f1f989d0ed221
Date: 2018-07-23T10:03:03.289Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

- OS Version: Windows 1803 - 10.0.17134 

- Steps to Reproduce:

1. Attempted to updated. Got dialog prompting to create an issue.
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2233204/vscode-inno-updater.log)

Does this issue occur when all extensions are disabled?: Yes

**Comment by kieferrm** [comment]
@arebee looking at your log I'd suspect that there is a second running instance that runs for example in admin mode.

**Comment by arebee** [comment]
There was a second instance I found with Process Explorer. It wasn't admin, and had no visible windows.
