### ISSUE TITLE
Set language mode from the contents of file

### ISSUE THREAD

**Issue by sveinse** [Microsoft/vscode#55187]
I know this topic has been discussed on numerous occasions previously, but I couldn't find an exact match for it. As I'm working a lot with Makefile, this is a pain-point for me, so please excuse me if this is already been discussed.

As a Linux user I am dealing with a lot of filenames that are not named by suffix. I'd like VSCode to correctly interpret the appropriate language mode to avoid the manual work of setting it when opening new files. Specifically, this most often applies to the ecosystem around `Makefile`, where make include files exists in a plethora of naming conventions, such as `rules.make`, `build.inc`, `Makefile.rules`, `buildenv`, etc. More often than not, I need to set the language mode every time I open these files.

Other editors have meta-data that can be added to the file itself to identify the file types. Emacs use `; -*- mode: Lisp;-*-` (see https://www.gnu.org/software/emacs/manual/html_node/emacs/Choosing-Modes.html), vim use `/* vim: setlocal ft=cpp: */` (see http://vimdoc.sourceforge.net/htmldoc/options.html#modeline)

Ideally I would like a mechanism for setting language directives within the text of the file. -- And it cannot only be limited to the first or last line of the file. The first line is commonly reserved for shebang, while the last line is error-prone.

My second option would be the ability to setup my own custom regexp rules, where I can define a pattern and the corresponding language rule.

**Comment by kieferrm** [comment]
@sveinse you can't use `file.associations` in workspace settings?

**Comment by alexandrudima** [comment]
> Ideally I would like a mechanism for setting language directives within the text of the file.

The only thing we have here is the ability of extensions to define a regex for the first line. e.g. xml:

```
		{
			"id": "xml",
			"extensions": [
				".xml",
				....
				".xoml"
			],
			"firstLine" : "(\\<\\?xml.*)|(\\<svg)|(\\<\\!doctype\\s+svg)",
			"aliases": [ "XML", "xml" ],
			"configuration": "./xml.language-configuration.json"
		}
```

So, using a VSCode extension you could target the first line.

> My second option would be the ability to setup my own custom regexp rules, where I can define a pattern and the corresponding language rule.

You could do what @kieferrm suggests in your user `settings.json`. Even better, if you can place this in the workspace/folder settings, then you can check this into source control and others will also get the setting. e.g.:

```
"files.associations": {
	"buildenv": "makefile"
}
```
