### ISSUE TITLE
Search not showing 'no results' properly

### ISSUE THREAD

**Issue by agzuniverse** [Microsoft/vscode#55180]
- VSCode Version: 1.25.1
- OS Version: Windows 10 build 1803

This issue is likely to be a simple fix.

### Steps to Reproduce:

Search for anything:
![screenshot 17](https://user-images.githubusercontent.com/22353313/43281946-90e785e0-9132-11e8-9cf2-66bb18690ab7.png)

Delete/change the matching term from the file in which it matched.
![screenshot 18](https://user-images.githubusercontent.com/22353313/43281963-9ab993b0-9132-11e8-89fc-89fa12ef4c2e.png)

As you can see the search results become empty, but it does not show the "no results found..." text.

### Expected behavior:

Show the "no results found..." text:
![screenshot 19](https://user-images.githubusercontent.com/22353313/43282020-ba5df3fa-9132-11e8-9fa4-2b10d78b5036.png)

Issue not related to any extensions.

**Comment by roblourens** [comment]
I'm not sure that it should. It doesn't feel like the right message for what just happened. There __was__ a result found... And telling the user to check their exclusions feels like missing the point.
