### ISSUE TITLE
Changes committed even when pre-commit hook fails. 

### ISSUE THREAD

**Issue by karimboucher** [Microsoft/vscode#55192]
- VSCode Version: 1.25.1
- OS Version: Ubuntu 16.04 LTS

Steps to Reproduce:

1. Run `install-hooks.sh` to create symlink of `pre-commit.sh`
2. Make change 
3. Force fail unit tests, exit code 1
4. Commit code

```
install-hooks.sh

#!/bin/sh

GIT_DIR=$(git rev-parse --git-dir)

echo "Installing hooks..."
# this command creates symlink to our pre-commit script
ln -s ../../tests/hooks/pre-commit.sh $GIT_DIR/hooks/pre-commit
echo "Done."
```
```
pre-commit.sh

#!/bin/sh

cd ../../tests/

`python3 -m unittest discover -p "test_*.py"`

if [ $? = 0 ]
then
    echo "> Tests PASSED"
    echo ".. Ready to commit."
else
    echo "> Tests FAILED"
    echo ".. Tests must pass before commit."
    exit 1
fi

exit 0
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Are you sure this only happens when you commit using VS Code, but not when using `git commit` in the command line?
