### ISSUE TITLE
Declare Uri.external in vscode.d.ts (extension development)

### ISSUE THREAD

**Issue by olback** [Microsoft/vscode#55195]
![screenshot from 2018-07-27 00 03 09](https://user-images.githubusercontent.com/8039145/43291081-77920c34-9130-11e8-96c5-e956f6a08b56.png)

When hovering over `external` it says `Property 'external' does not exist on type 'Uri'`. But logging `active.document.uri` will give you:

```json
{
    "$mid": 1,
    "fsPath": "/home/olback/Desktop/es6-css-minify/src/test/workspace/js/aaa.main.js",
    "external": "file:///home/olback/Desktop/es6-css-minify/src/test/workspace/js/aaa.main.js",
    "path": "/home/olback/Desktop/es6-css-minify/src/test/workspace/js/aaa.main.js",
    "scheme": "file"
}
```

It would be nice if `external` were added to the Uri class in `vscode.d.ts`.

**Comment by mjbvz** [comment]
That's internal state.  URI already provides `toString` to get this value
