### ISSUE TITLE
Can't see installed extensions when offline

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#55193]
- Go offline
- Open extension viewlet
- Type `@builtin`
- Get an error popup

**Comment by JacksonKearl** [comment]
@ramya-rao-a is this expected because we need to load the details from the gallery? Or should that be local?

**Comment by roblourens** [comment]
It works in 1.25

**Comment by JacksonKearl** [comment]
Ah, literally offline, not just "offline mode"

**Comment by roblourens** [comment]
Oh right not related to the new settings

**Comment by JacksonKearl** [comment]
Closed with #55273
