### ISSUE TITLE
VS Code can't trash items on Ubuntu

### ISSUE THREAD

**Issue by ffxsam** [Microsoft/vscode#55196]
- VSCode Version: 1.25.1
- OS Version: Ubuntu 18.04

Same issue as: https://github.com/Microsoft/vscode/issues/49675 (please reopen that issue if possible)

**Comment by Tyriar** [comment]
@ffxsam the end of that issue indicates that it's probably fixed in Electron 2? Could you try the insiders build to see if it's fixed? https://code.visualstudio.com/insiders/
