### ISSUE TITLE
Copy File in explorer should stop once something else was copied in the editor

### ISSUE THREAD

**Issue by 17twenty** [Microsoft/vscode#5519]
- VSCode Version: 1.0.0
- OS Version: Ubuntu 14.04.4 LTS

Steps to Reproduce:
1. Have a number of open files
2. Right-click and copy one of these files and paste it somewhere else in the tree.
3. Copy text from an open file
4. Move to another open file where you can paste the text 
5. CTRL+V to paste and watch as it pastes another copy of the file instead of pasting the text.

**Comment by dbaeumer** [comment]
@bpasero marking as important since it sounds a little scary.

**Comment by bpasero** [comment]
Now after you have pasted I am clearing out the pasted target so that subsequent pastes are not causing the same file to be pasted again.

**Comment by 17twenty** [comment]
Is that a good fix? What if someone wants to paste the same file multiple
times?

I would've thought clearing the chosen file in a text copy would've been
better?

**Comment by bpasero** [comment]
Actually the copy file feature is such a hack (it bypasses the clipboard) that I would argue to rather try to implement it using the clipboard APIs of Electron.

**Comment by 17twenty** [comment]
Could we leave this as open until remedied?

**Comment by bpasero** [comment]
Hehe sorry, I reverted my commit and GH closed this issue again. I really think reverting should have left this issue open...

**Comment by bpasero** [comment]
@alexandrudima is there an event emitted when a command is executed like "Copy" in the editor?

**Comment by alexandrudima** [comment]
@bpasero Why not implement file copying natively now that we use electron (`require('electron').clipboard`). That would allow copying/pasting integration with the Explorer / Finder.

**Comment by bpasero** [comment]
@alexandrudima I thought about that but we need the "file" clipboard transfer for this (afaik) and not the text one.

**Comment by bpasero** [comment]
Fixed via https://github.com/Microsoft/vscode/pull/43029
