### ISSUE TITLE
Disable scrolling past Peek Definition editor

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#55199]
Currently, if you open a Peek Definition box and scroll down to the end, the parent editor begins scrolling too. This is kind of disorienting because I always have to scroll back up and fix my position. It would be much more comfortable if the scroll was locked to the child editor when the mouse is inside the Peek Definition area so that I can't scroll past the end or beginning.

**Comment by nealot** [comment]
Just wanted to add that this also happens with the Git peek and the hover widget.
