### ISSUE TITLE
TextMate-derived themes should be able to affect colors of VS Code UI outside of the editor control

### ISSUE THREAD

**Issue by daviwil** [Microsoft/vscode#552]
It's cool how the in-box themes are able to change the colors of the UI surrounding the editor control.  It would be really nice if there was a way for TextMate themes to affect the colors of this UI also.  

One way to accomplish this would be to provide some new fields to the "theme" contribution in package.json which maps VS Code UI colors to specific keys in the TextMate definition.  It would be up to the author of the theme package to choose which keys/colors to use for the UI element colors.  This would allow the theme author to be able to write the color codes in the theme file without having to update their package.json.

**Comment by satya164** [comment]
+1

**Comment by rojorojo** [comment]
+1

**Comment by bpasero** [comment]
#3112
