### ISSUE TITLE
VS Code Insider upate failure

### ISSUE THREAD

**Issue by phil0074** [Microsoft/vscode#55206]
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2234250/vscode-inno-updater.log)

Update failed and requested attaching the following log, uninstall, and then reinstall VS Code Insider Edition.

**Comment by joaomoreno** [comment]
Can you reproduce this consistently? Or did an update work afterwards?

**Comment by phil0074** [comment]
A re-install of VS Code Insider update seems to resolve the issue.
