### ISSUE TITLE
Provide a openEditorAtIndex command that allows to pass in the index

### ISSUE THREAD

**Issue by xconverge** [Microsoft/vscode#55205]
I am forming an openEditorAtIndex command using the following syntax:

'workbench.action.openEditorAtIndex' + index

1-9 work correctly (and are default keybindings already). Would it be possible to add support for any index?

I currently need to use this command if <= 9 and if > 9, I have to go to index 9 and then next count - 9 times to get to the desired pane with a risk of wrapping around

**Comment by bpasero** [comment]
@xconverge trying to understand the scenario here, I do not think it makes sense for VSCode to introduce commands for more indices because this number is pretty much unlimited. Can we have another command that just goes to the next index, from the current one and you could use that instead?  E.g. does it work if you use `workbench.action.nextEditorInGroup`?

**Comment by xconverge** [comment]
https://github.com/VSCodeVim/Vim/blob/182b9d5a2f93eda9d6421f8670f9df595ee7f61d/src/cmd_line/commands/tab.ts#L55

Lines 55 - 89 are what I use to be able to go to any tab

My ```default:``` case here is what I am trying to avoid

Ideally I could do ```await vscode.commands.executeCommand('workbench.action.openEditorAtIndex' + index);``` and never think twice about it

The problem with using nextEditorInGroup is that I have no way of knowing the max editor number index, so if I say go to tab 10 and there are only 8 tabs, the current logic will try to go to tab 9 with the absolute exposed command, then use a nextEditorInGroup command.

**Comment by bpasero** [comment]
@xconverge that switch-case statement looks quite horrible, an alternative would be for the workbench to expose a command `workbench.action.openEditorAtIndex` where you just pass the index as argument into. We already have that for other commands, e.g. see the "move editor command" ([here](https://github.com/Microsoft/vscode/blob/b7677de2a04f5fd547b597e9a0a917b816524a73/src/vs/workbench/browser/parts/editor/editorCommands.ts#L78))

Would that be better?

**Comment by xconverge** [comment]
That would work for me too! It is not very urgent since I don't think people navigate to tabs they can't see very often but for completeness it would be nice! Thanks!

**Comment by bpasero** [comment]
Great. I would accept a reasonable small PR on this feature request.

**Comment by hhu94** [comment]
I'll try to write a reasonable small PR for this :)

**Comment by bpasero** [comment]
@xconverge landed, thanks to @hhu94

**Comment by isidorn** [comment]
Some steps so I do not have to read the whole discussion?
What command with what arguments should do what now?

**Comment by bpasero** [comment]
Ah yeah good point, but I think that is fine.
