### ISSUE TITLE
打开一个文件数量很多的工程，卡死，没响应

### ISSUE THREAD

**Issue by astariochuck** [Microsoft/vscode#55208]
打开一个文件数量很多的工程，卡死，没响应

**Comment by zhuqinggang** [comment]
这是所有编辑器的通病，请耐心等等。
提issue请用英文，不然没有人答哦。
赶紧把issue关掉吧

**Comment by rebornix** [comment]
Close it for now as it lacks enough information to help troubleshoot. Please provide detailed reproduce steps and then we can look into it.
