### ISSUE TITLE
High gpu-process usage in 1.26.0-insider

### ISSUE THREAD

**Issue by wayspurrchen** [Microsoft/vscode#55207]
VSCode Insiders uses a significant amount of RAM for gpu-process on a fresh install. The screenshot shows 336 but I've seen it as high as 450 on a fresh start. If continuing development, will freeze after a short amount of time with the Windows 10 Reopen/Wait for process/Close prompt. Waiting long enough will unfreeze but performance is still poor.

![image](https://user-images.githubusercontent.com/1059075/43299385-9e6d5fae-911f-11e8-8161-6e86a9268f2a.png)

This appears to be related to #36913 but wanted to highlight here that the latest version of insider (1.26.0-insider) does not appear to have fixed this issue for a fresh copy of Windows 10 Pro. I was able to avoid the issue in 1.25.0 by passing the `--disable-gpu` flag.

- VSCode Version: 1.26.0-insider
- OS Version: Windows 10 Pro

CPUs | Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz (8 x 3096)
-- | --
GPU Status | 2d_canvas: enabledchecker_imaging: disabled_offflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwarerasterization: enabledvideo_decode: enabledvideo_encode: enabledwebgl: enabledwebgl2: unavailable_off
Memory (System) | 15.85GB (6.95GB free)
Process Argv | C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe
Screen Reader | no
VM | 0%

Steps to Reproduce:

1. Launch VSCode Insiders
2. View Process Explorer

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/53274
