### ISSUE TITLE
one click vscode start from specific folder

### ISSUE THREAD

**Issue by saswat3115** [Microsoft/vscode#55210]
Please include following features : 

Create a solution file like batch file to start vs code from a specific folder. Currently we are creating batch file and writing "code ." to start. It is like .sln file in .net project in visual studio.

Thanks

**Comment by flotwig** [comment]
You can enable a feature to right click inside a folder in Explorer and "Open with Code":

http://thisdavej.com/right-click-on-windows-folder-and-open-with-visual-studio-code/
