### ISSUE TITLE
 command 'pr.refreshList' not found

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#55215]
Issue Id: <b>25efb273-306b-abd0-a3cc-82ff8b2c7818</b><br /><br />*Versions* <br />- 1.26.0-insider (7/24/2018 5:15:52 AM)<br />*Stack* <br />Error: command 'pr.refreshList' not found<br />[/vs/workbench/services/commands/common/commandService.ts#57:29 (_tryExecuteCommand)](https://github.com/microsoft/vscode/blob/befea2253626b1918352df04477cae83eee618ac/src/vs/workbench/services/commands/common/commandService.ts#L57:29 (_tryExecuteCommand))<br />[/vs/workbench/services/commands/common/commandService.ts#50:33 (onComplete)](https://github.com/microsoft/vscode/blob/befea2253626b1918352df04477cae83eee618ac/src/vs/workbench/services/commands/common/commandService.ts#L50:33 (onComplete))<br />[/vs/base/common/winjs.base.js#1587:0 (then)](https://github.com/microsoft/vscode/blob/befea2253626b1918352df04477cae83eee618ac/src/vs/base/common/winjs.base.js#L1587:0 (then))<br />[/vs/workbench/services/commands/common/commandService.ts#50:18 (apply)](https://github.com/microsoft/vscode/blob/befea2253626b1918352df04477cae83eee618ac/src/vs/workbench/services/commands/common/commandService.ts#L50:18 (apply))<br />[/vs/workbench/api/electron-browser/mainThreadCommands.ts#79:44 (apply)](https://github.com/microsoft/vscode/blob/befea2253626b1918352df04477cae83eee618ac/src/vs/workbench/api/electron-browser/mainThreadCommands.ts#L79:44 (apply))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#261:16 (_doInvokeHandler)](https://github.com/microsoft/vscode/blob/befea2253626b1918352df04477cae83eee618ac/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L261:16 (_doInvokeHandler))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#246:27 (_invokeHandler)](https://github.com/microsoft/vscode/blob/befea2253626b1918352df04477cae83eee618ac/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L246:27 (_invokeHandler))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#192:39 (_receiveRequest)](https://github.com/microsoft/vscode/blob/befea2253626b1918352df04477cae83eee618ac/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L192:39 (_receiveRequest))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#174:9 (_receiveOneMessage)](https://github.com/microsoft/vscode/blob/befea2253626b1918352df04477cae83eee618ac/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L174:9 (_receiveOneMessage))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#107:65 (onMessage)](https://github.com/microsoft/vscode/blob/befea2253626b1918352df04477cae83eee618ac/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L107:65 (onMessage))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#303:4 (call)](https://github.com/microsoft/vscode/blob/befea2253626b1918352df04477cae83eee618ac/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L303:4 (call))<br />[/vs/base/common/event.ts#140:15 (fire)](https://github.com/microsoft/vscode/blob/befea2253626b1918352df04477cae83eee618ac/src/vs/base/common/event.ts#L140:15 (fire))<br />[/vs/base/parts/ipc/node/ipc.net.ts#104:22 (acceptChunk)](https://github.com/microsoft/vscode/blob/befea2253626b1918352df04477cae83eee618ac/src/vs/base/parts/ipc/node/ipc.net.ts#L104:22 (acceptChunk))<br />[/vs/base/parts/ipc/node/ipc.net.ts#133:3](https://github.com/microsoft/vscode/blob/befea2253626b1918352df04477cae83eee618ac/src/vs/base/parts/ipc/node/ipc.net.ts#L133:3)<br />    at emitOne (events.js:96:13)<br />    at Socket.emit (<br />

**Comment by vscodeerrors** [comment]
Here is another similar callstack 

Error: command 'pr.refreshList' not found<br />[/vs/workbench/services/commands/common/commandService.ts#57:29 (_tryExecuteCommand)](https://github.com/microsoft/vscode/blob/befea2253626b1918352df04477cae83eee618ac/src/vs/workbench/services/commands/common/commandService.ts#L57:29 (_tryExecuteCommand))<br />[/vs/workbench/services/commands/common/commandService.ts#50:33 (onComplete)](https://github.com/microsoft/vscode/blob/befea2253626b1918352df04477cae83eee618ac/src/vs/workbench/services/commands/common/commandService.ts#L50:33 (onComplete))<br />[/vs/base/common/winjs.base.js#1587:0 (then)](https://github.com/microsoft/vscode/blob/befea2253626b1918352df04477cae83eee618ac/src/vs/base/common/winjs.base.js#L1587:0 (then))<br />[/vs/workbench/services/commands/common/commandService.ts#50:18 (apply)](https://github.com/microsoft/vscode/blob/befea2253626b1918352df04477cae83eee618ac/src/vs/workbench/services/commands/common/commandService.ts#L50:18 (apply))<br />[/vs/workbench/api/electron-browser/mainThreadCommands.ts#79:44 (apply)](https://github.com/microsoft/vscode/blob/befea2253626b1918352df04477cae83eee618ac/src/vs/workbench/api/electron-browser/mainThreadCommands.ts#L79:44 (apply))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#261:16 (_doInvokeHandler)](https://github.com/microsoft/vscode/blob/befea2253626b1918352df04477cae83eee618ac/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L261:16 (_doInvokeHandler))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#246:27 (_invokeHandler)](https://github.com/microsoft/vscode/blob/befea2253626b1918352df04477cae83eee618ac/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L246:27 (_invokeHandler))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#192:39 (_receiveRequest)](https://github.com/microsoft/vscode/blob/befea2253626b1918352df04477cae83eee618ac/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L192:39 (_receiveRequest))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#174:9 (_receiveOneMessage)](https://github.com/microsoft/vscode/blob/befea2253626b1918352df04477cae83eee618ac/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L174:9 (_receiveOneMessage))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#107:65 (onMessage)](https://github.com/microsoft/vscode/blob/befea2253626b1918352df04477cae83eee618ac/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L107:65 (onMessage))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#303:4 (call)](https://github.com/microsoft/vscode/blob/befea2253626b1918352df04477cae83eee618ac/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L303:4 (call))<br />[/vs/base/common/event.ts#140:15 (fire)](https://github.com/microsoft/vscode/blob/befea2253626b1918352df04477cae83eee618ac/src/vs/base/common/event.ts#L140:15 (fire))<br />[/vs/base/parts/ipc/node/ipc.net.ts#104:22 (acceptChunk)](https://github.com/microsoft/vscode/blob/befea2253626b1918352df04477cae83eee618ac/src/vs/base/parts/ipc/node/ipc.net.ts#L104:22 (acceptChunk))<br />[/vs/base/parts/ipc/node/ipc.net.ts#133:3](https://github.com/microsoft/vscode/blob/befea2253626b1918352df04477cae83eee618ac/src/vs/base/parts/ipc/node/ipc.net.ts#L133:3)<br />    at emitOne (events.js:96:13)<br />    at Socket.emit (<br />

**Comment by kieferrm** [comment]
This is the Pull Request extension.
