### ISSUE TITLE
Weird behaviour on renaming folder opened in Windows Explorer

### ISSUE THREAD

**Issue by WorldofBay** [Microsoft/vscode#55214]
[Windows]
There are several weird behaviours on rename folder in VS Code.
Steps 1, 2 and 3 stay the same for all cases:
1. Open a folder with subfolders with subsubfolders in VS Code
2. Navigate a Windows Explorer instance into a subsubfolder
3. Rename subfolder in VS Code
-> nothing happens (no failure, no rename, no debug output)

Then there are different strange followups:
4a. Move up from subsubfolder to subfolder in Windows Explorer
-> subfolder is renamed

4b. Rename subfolder in VS Code to a different name from (3)
-> nothing happens
5b. Move up from subsubfolder to subfolder in Windows Explorer
-> subfolder is renamed to the name of (3); VS Code is showing an error of the rename in (4b)
![grafik](https://user-images.githubusercontent.com/16127164/43306667-30b69fe0-917c-11e8-8a5b-d79b3161d860.png)

4c. Rename subfolder in VS Code to a different name from (3)
-> nothing happens
5c. Create new subfolder in VS Code with the name from (3)
-> VS Code is showing an error of the rename in (3), new subfolder is created but not shown in VS Code
![grafik](https://user-images.githubusercontent.com/16127164/43306502-b3f6a7ca-917b-11e8-92e1-a1e1ef367868.png)
6c. Move up from subsubfolder to subfolder in Windows Explorer
-> subfolder is renamed to the name of (4c)

4d. Rename subfolder in VS Code to a different name from (3)
-> nothing happens
5d. Refresh subfolder in Windows Explorer
-> VS Code shows errors for both renames from (3) and (4d)
![grafik](https://user-images.githubusercontent.com/16127164/43306843-d698c50a-917c-11e8-8e2e-0771a1dc8012.png)

Happens without extensions.
Happens the same on VS Code Insiders.

VS Code should not keep a pending rename and try to apply it later when the user may already have forgotten about it.

Not tested how it behaves with other concurring applications.

**Comment by rslemos** [comment]
Is this solved?
