### ISSUE TITLE
Task: support that a task can have an auxiliary description/tooltip

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#55218]
The NPM script explorer shows the tasks and if a task had a tool tip then I would show the actual script that is executed when hovering over a script in the explorer. The screenshot below illustrates what I would like to show:

![image](https://user-images.githubusercontent.com/172399/43308954-9525803e-9183-11e8-9d6f-899b0fbbd878.png)

**Comment by dbaeumer** [comment]
@alexr00 can you please add steps to verify this.
