### ISSUE TITLE
'Tokenization is skipped for lines longer than 20k characters for performance reasons ' showing when auto-suggest box shows

### ISSUE THREAD

**Issue by jpike88** [Microsoft/vscode#55212]
- VSCode Version: Latest
- OS Version: macOS High Sierra

Steps to Reproduce:

1. Import a JSON with loads of keys (the JSON is not minified and is beautified), and have a method require a parameter that uses `keyof typeof` on that imported JSON object. Effectively, it becomes a large amount of string values all joined by the OR operator.

2. Hold CMD over a call on that method, which brings up the more info tooltip.

'Tokenization is skipped for lines longer than 20k characters for performance reasons' shows in a warning tooltip.

I shouldn't have to see that.

![screen shot 2018-07-27 at 1 21 36 pm](https://user-images.githubusercontent.com/9585787/43304898-04b8bd6e-91a0-11e8-8a94-bf56576cc483.png)

**SOLUTION:** truncate the grey information text to an amount of characters below 20k.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jpike88** [comment]
@alexandrudima any luck on this one? Seems like a quick fix doesn't it?

**Comment by mjbvz** [comment]
Falls under https://github.com/Microsoft/TypeScript/issues/14662. We shouldn't return the complete list of values large union cases like this

Closing as upstream
