### ISSUE TITLE
Duplicate file results in QuickPick

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#55224]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/9205389/43313459-6acb3d1c-9190-11e8-83c5-d090307d3686.png)

VS Code version: Code - Insiders 1.26.0-insider (dae69dbf00357ff8a3fe740a1f211d66b0b4681c, 2018-07-27T05:12:46.620Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_4596834|
|Screen Reader|no|
|VM|33%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
999-pack1|chr|0.12.3
regex|chr|0.2.0
ssh|chr|0.0.4
vscode-eslint|dba|1.4.12
Spot|der|0.4.0
ghlink|dt|1.0.2
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.34
rest-client|hum|0.19.0
vscode-azureappservice|ms-|0.9.0
vscode-azurefunctions|ms-|0.10.0
vscode-cosmosdb|ms-|0.8.0
azure-account|ms-|0.4.2
azurecli|ms-|0.4.2
github-issues-prs|ms-|0.9.0
PowerShell|ms-|1.8.1
debugger-for-chrome|msj|4.8.2
vscode-docker|Pet|0.1.0
vscode-versionlens|pfl|0.21.1
vscode-open-in-github|sys|1.7.0
ayu|tea|0.14.0
azure-iot-toolkit|vsc|1.1.0

</details>

**Comment by chrmarti** [comment]
Some additional data: The number of entries per file is the same as the number of workspace folders. :)

**Comment by roblourens** [comment]
I assume you have `searchRipgrep.enable` set. I broke the cacheKey.

**Comment by chrmarti** [comment]
I see this again in:
VS Code version: Code - Insiders 1.26.0-insider (0707dd4940b3fdbea8339595de478f354f6dda83, 2018-07-31T05:12:08.688Z)
OS version: Darwin x64 17.7.0

![image](https://user-images.githubusercontent.com/9205389/43451108-7d2ca780-94b4-11e8-9cb9-4725443aa6dc.png)
