### ISSUE TITLE
VSCode have process "Code Helper" always run over 100% CPU

### ISSUE THREAD

**Issue by KytoSai** [Microsoft/vscode#55225]
Issue Type: <b>Performance Issue</b>

VSCode Version: 1.25.1
OS Version: 10.13.6

VSCode have process "Code Helper" always run over 100% CPU
Demo: http://prntscr.com/kbo0wt

"Code Helper" stays running even after I quit the VSCode app

**Does this issue occur when all extensions are disabled?: Yes**

I have attempt to reboot laptop multiple times. But It still happen run over 100% CPU

old report: https://github.com/Microsoft/vscode/issues/54627#issuecomment-406183620 

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|29%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   11	   131	 10515	code main
    0	    66	 10516	   gpu-process
    0	    82	 10525	   shared-process
    0	   229	 13712	   window (html)
    0	   115	 13713	     extensionHost
    0	    33	 13731	       electron_node server.js 
    0	    33	 13735	       electron_node server.js 
    0	    33	 13738	       electron_node htmlServerMain.js 
    0	    66	 13776	       electron_node eslintServer.js 
  107	   164	 13777	       electron_node electronForkStart.js tsserver.js 
    0	    33	 13781	         electron_node typingsInstaller.js tsserver.js typesMap.js 
    0	    33	 13783	       electron_node jsonServerMain.js 
    0	   164	 14780	       extensionHost
    0	    66	 13714	     watcherService
    0	    16	 13718	     searchService
    0	    98	 14953	   window (Issue Reporter)
    0	     0	 14954	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (html)
|    Folder (html): 1094 files
|      File types: jpg(530) scss(150) DS_Store(62) png(52) svg(48) js(35)
|                  ttf(30) woff(25) woff2(23) php(22)
|      Conf files: jsconfig.json(2) package.json(2) settings.json(1);
```

</details>
<details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.4
lorem-ipsum|Tyr|1.2.0
html-css-class-completion|Zig|1.17.1
better-comments|aar|1.2.6
html-snippets|abu|0.2.1
vscode-javascript-snippet-pack|aka|0.1.5
lit-html|bie|1.6.2
vscode-intelephense-client|bme|0.8.8
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.19.0
vscode-eslint|dba|1.4.12
vscode-faker|dee|1.3.0
githistory|don|0.4.2
simple-alignment|ear|0.0.5
prettier-vscode|esb|1.5.0
auto-close-tag|for|0.5.6
HTMLHint|mka|0.5.0
vscode-scss|mrm|0.6.2
vetur|oct|0.12.5
indent-rainbow|ode|7.2.2
material-icon-theme|PKi|3.5.2
vscode-template-literal-editor|pli|0.9.0
code-settings-sync|Sha|3.0.0
markdown-preview-enhanced|shd|0.3.5
open-in-browser|tec|1.1.0
vscode-import-cost|wix|2.8.0

(1 theme extensions excluded)

</details>

**Comment by KytoSai** [comment]
Report today:


Issue Type: <b>Performance Issue</b>

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.14GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|29%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   13	    98	   754	code main
    0	    66	   755	   gpu-process
    0	   311	   756	   window (web.config.js — html)
    0	   180	   762	     extensionHost
    0	   131	   767	       electron_node electronForkStart.js tsserver.js 
    0	    49	   786	         electron_node typingsInstaller.js tsserver.js typesMap.js 
    0	    66	   768	       electron_node eslintServer.js 
    0	    49	   784	       electron_node server.js 
    0	    33	   794	       electron_node jsonServerMain.js 
    0	   197	  1698	       extensionHost
    0	    33	  1961	       electron_node vueServerMain.js 
    0	    16	  2830	       electron_node server.js 
    0	    82	  2831	       electron_node htmlServerMain.js 
    0	   164	  3273	       extensionHost
    0	   705	  3274	       extensionHost
    0	   786	  3275	       extensionHost
    0	   180	  3276	       extensionHost
    0	   197	  3277	       extensionHost
    0	    49	  3349	       electron_node server.js 
    0	    66	  3350	       electron_node cssServerMain.js 
  100	  2310	  3383	       extensionHost
    0	    33	   763	     watcherService
    0	    16	   773	     searchService
    0	    66	   764	   shared-process
    0	    82	  3743	   window (Issue Reporter)
    0	     0	  3744	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (web.config.js — html)
|    Folder (html): 1139 files
|      File types: jpg(547) scss(152) DS_Store(65) png(52) svg(48) js(37)
|                  ttf(30) woff(25) php(24) md(23)
|      Conf files: jsconfig.json(2) package.json(2) settings.json(1);
```

</details>
<details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.4
lorem-ipsum|Tyr|1.2.0
html-css-class-completion|Zig|1.17.1
better-comments|aar|1.2.6
html-snippets|abu|0.2.1
vscode-javascript-snippet-pack|aka|0.1.5
lit-html|bie|1.6.2
vscode-intelephense-client|bme|0.8.8
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.12
vscode-faker|dee|1.3.0
githistory|don|0.4.2
simple-alignment|ear|0.0.5
prettier-vscode|esb|1.5.0
php-debug|fel|1.12.3
auto-close-tag|for|0.5.6
HTMLHint|mka|0.5.0
vscode-scss|mrm|0.6.2
vetur|oct|0.12.5
indent-rainbow|ode|7.2.2
material-icon-theme|PKi|3.5.2
vscode-template-literal-editor|pli|0.9.0
code-settings-sync|Sha|3.0.0
markdown-preview-enhanced|shd|0.3.5
open-in-browser|tec|1.1.0
vscode-import-cost|wix|2.8.0

(1 theme extensions excluded)

</details>

**Comment by sambecker** [comment]
Same issue.

Using `Code 1.25.1` and `TypeScript 2.9.2` on `macOS 10.13.5`.

Code Helper stays at 100% after Code quits.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?
