### ISSUE TITLE
ActionBar focus broken

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#55221]
`ActionBar` can now be focussed whole which breaks how we have designed `ActionBar` focus
I think this commit has broken it with introducing tabIndex=0 to actionBar
79acca172a735336d990fb3e135f9d16fb613012

As mentioned in a seperate PR I do not understand why do we need to introduce changes to actionBar for menus. Let's try to keep the menu work independent in the menu land, and only fix issues in `ActionBar`.
Also note that `ActionBars` are used eveyrwhere in our workbench and change like this should be thourougly tested.

fyi @aeschli 
![image 6](https://user-images.githubusercontent.com/1926584/43312219-e466cb22-918c-11e8-9219-49960fb290df.png)

**Comment by sbatten** [comment]
Opened a separate issue regarding the menu/actionbar code structure #55258
