### ISSUE TITLE
Can not commit any changes

### ISSUE THREAD

**Issue by JustUsername1** [Microsoft/vscode#55228]
Issue Type: <b>Bug</b>

1. I cloned repo from GitHub.
2. I added new file to it and wrote something into it.
3. I pressed "+" to make the change staged.
4. I pressed the "tick" button to commit staged changes.
PROBLEM: it says "Git: Failed to execute Git". I have no idea why it does not work. I have installed Git and it looks like the extension has been made.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz (8 x 2394)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Memory (System)|3.91GB (1.42GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by joaomoreno** [comment]
Can you try to execute from the command line? What result do you get?

**Comment by JustUsername1** [comment]
I tried it and got the same result.

**Comment by joaomoreno** [comment]
So, it isn't an issue related to VS Code.

What is the full output you get from the command line?

**Comment by JustUsername1** [comment]
Looking for git in: C:\Program Files\Git\cmd\git.exe
Using git 2.18.0.windows.1 from C:\Program Files\Git\cmd\git.exe
> git rev-parse --show-toplevel
> git config --get commit.template
Open repository: c:\Users\lenovo\Desktop\HelloWorld\Hello-World
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git check-ignore -z --stdin
> git commit --quiet --allow-empty-message --file -

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'lenovo@DESKTOP-0B5Q4U5.(none)')
> git config --get-all user.name

**Comment by joaomoreno** [comment]
You need to run:

```
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
```

Replace the values with your personal details.
