### ISSUE TITLE
Expand/Collapse on Code

### ISSUE THREAD

**Issue by Memphis335** [microsoft/vscode#55226]
Issue Type: <b>Bug</b>

Create a javascript file. 

Add several function to the file, of about 1000 lines. 
Now try to collapse some of the functions. Close the file, open it up and try to expand the functions again. On certain occasions, this is not possible. 

It won't show the options. I have to open/close the file several times before this is working again. 

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:11.471Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.87GB (8.30GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
angular-material-snippets|4tr|0.3.1
jslint|ajh|1.2.1
vscode-javascript-snippet-pack|aka|0.1.5
angular1-code-snippets|ale|0.0.3
ng-template|Ang|0.1.9
npm-intellisense|chr|1.3.0
gitignore|cod|0.5.0
dart-code|Dar|2.16.0
flutter|Dar|2.16.0
javadebugger|don|0.1.5
tslint|eg2|1.0.34
php-debug|fel|1.12.3
beautify|Hoo|1.3.2
minify|Hoo|0.3.0
ftp-simple|hum|0.6.7
Angular2|joh|6.1.1
ajax-snippets|Mem|1.9.0
mssql|ms-|1.4.0
csharp|ms-|1.15.2
PowerShell|ms-|1.8.1
team|ms-|1.136.0
debugger-for-chrome|msj|4.8.2
sass-indented|rob|1.4.9
html5-boilerplate|sid|1.0.3
nativescript|Tel|0.7.4
cordova-tools|vsm|1.4.0

(1 theme extensions excluded)

</details>

**Comment by kieferrm** [comment]
- Can you pls try without any of your installed extensions?
- If it still happens, the folding indicators are coming from the language server. If the `js` file is the only `js` file you have open, the language server might need a new seconds to get ready. So, even when you wait, you don't see any folding indicators?

**Comment by Memphis335** [comment]
I tried that, Issue persists. 
I also tried to wait to no avail.

**Comment by kieferrm** [comment]
@Memphis335 
- Can you share the file with which that happens?
- Do you open a folder, i.e. does the file explorer show a directory, or do you only open the file?

**Comment by YegorTrembovetsky** [comment]
@kieferrm 
Hi, I have the same issue in huge files. Tried with all extensions disabled, issue persists. You can find the file on which folding fails:
[yt_page_header.html.txt](https://github.com/Microsoft/vscode/files/2266707/yt_page_header.html.txt)

**Comment by BarryYan** [comment]
I have the same issue.
When I update the lastest version, I can't collapse the element or `()` exclude `{}`  in jsx file.
![image](https://user-images.githubusercontent.com/8463435/43820944-43ef6c2a-9b1a-11e8-9e58-a0b6e07b00cb.png)

**Comment by Memphis335** [comment]
@kieferrm I open a UNC directory from my Windows server. 

[homepage.txt](https://github.com/Microsoft/vscode/files/2269347/homepage.txt)

**Comment by simongcc** [comment]
I have the same issue with the version 1.3.1 Mac OS X which I firstly used.
The Code Collapse Icon does not work but shortcut is working well such as
 <kbd>⌘ Command</kbd> <kbd>⌥ Option</kbd> <kbd>[</kbd> to collapse or <kbd>⌘ Command</kbd> <kbd>⌥ Option</kbd> <kbd>]</kbd> to expand.
