### ISSUE TITLE
User needs to manually restart VSCode to unplug tslint extension.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#5522]
- VSCode Version: 1.0.0-alpha
- OS Version: Windows10

Steps to Reproduce:
1. Launch VScode and install tslint extension.
2. Open folder which contains .ts file.
3. Verify it should highlight linter related issues.
4. Now uninstall the extension and verify app behavior.

Actual: After uninstallation user is not getting any message pop-up to restart app.
Expected: User should get restart pop-up message once uninstall is finished.

![tslintissue](https://cloud.githubusercontent.com/assets/17735796/14661359/c371b35e-0661-11e6-8517-7839095a2565.gif)

**Comment by joaomoreno** [comment]
Fixed since.
