### ISSUE TITLE
 Unable to write to Workspace Settings because angulardoc.lastSync is not a registered configuration.

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#55220]
Issue Id: <b>209a4063-8c5e-098c-8265-aa0ffd1652f4</b><br /><br />*Versions* <br />- 1.25.1<br />*Stack* <br />Error: Unable to write to Workspace Settings because angulardoc.lastSync is not a registered configuration.<br />[/vs/workbench/services/configuration/node/configurationEditingService.ts#85:2](https://github.com/microsoft/vscode/blob/1dfc5e557209371715f655691b1235b6b26a06be/src/vs/workbench/services/configuration/node/configurationEditingService.ts#L85:2)<br />[/vs/workbench/services/configuration/node/configurationEditingService.ts#274:31 (wrapError)](https://github.com/microsoft/vscode/blob/1dfc5e557209371715f655691b1235b6b26a06be/src/vs/workbench/services/configuration/node/configurationEditingService.ts#L274:31 (wrapError))<br />[/vs/workbench/services/configuration/node/configurationEditingService.ts#384:16 (resolveAndValidate)](https://github.com/microsoft/vscode/blob/1dfc5e557209371715f655691b1235b6b26a06be/src/vs/workbench/services/configuration/node/configurationEditingService.ts#L384:16 (resolveAndValidate))<br />[/vs/workbench/services/configuration/node/configurationEditingService.ts#156:14 (doWriteConfiguration)](https://github.com/microsoft/vscode/blob/1dfc5e557209371715f655691b1235b6b26a06be/src/vs/workbench/services/configuration/node/configurationEditingService.ts#L156:14 (doWriteConfiguration))<br />[/vs/workbench/services/configuration/node/configurationEditingService.ts#143:37 (factory)](https://github.com/microsoft/vscode/blob/1dfc5e557209371715f655691b1235b6b26a06be/src/vs/workbench/services/configuration/node/configurationEditingService.ts#L143:37 (factory))<br />[/vs/base/common/async.ts#524:32 (consume)](https://github.com/microsoft/vscode/blob/1dfc5e557209371715f655691b1235b6b26a06be/src/vs/base/common/async.ts#L524:32 (consume))<br />[/vs/base/common/async.ts#515:8 (init)](https://github.com/microsoft/vscode/blob/1dfc5e557209371715f655691b1235b6b26a06be/src/vs/base/common/async.ts#L515:8 (init))<br />[/vs/base/common/winjs.base.js#1656:0](https://github.com/microsoft/vscode/blob/1dfc5e557209371715f655691b1235b6b26a06be/src/vs/base/common/winjs.base.js#L1656:0)<br />[/vs/base/common/async.ts#507:9 (queue)](https://github.com/microsoft/vscode/blob/1dfc5e557209371715f655691b1235b6b26a06be/src/vs/base/common/async.ts#L507:9 (queue))<br />[/vs/workbench/services/configuration/node/configurationEditingService.ts#143:20 (writeConfiguration)](https://github.com/microsoft/vscode/blob/1dfc5e557209371715f655691b1235b6b26a06be/src/vs/workbench/services/configuration/node/configurationEditingService.ts#L143:20 (writeConfiguration))<br />[/vs/workbench/services/configuration/node/configurationService.ts#608:42 (writeConfigurationValue)](https://github.com/microsoft/vscode/blob/1dfc5e557209371715f655691b1235b6b26a06be/src/vs/workbench/services/configuration/node/configurationService.ts#L608:42 (writeConfigurationValue))<br />[/vs/workbench/services/configuration/node/configurationService.ts#265:23 (updateValue)](https://github.com/microsoft/vscode/blob/1dfc5e557209371715f655691b1235b6b26a06be/src/vs/workbench/services/configuration/node/configurationService.ts#L265:23 (updateValue))<br />[/vs/workbench/api/electron-browser/mainThreadConfiguration.ts#51:35](https://github.com/microsoft/vscode/blob/1dfc5e557209371715f655691b1235b6b26a06be/src/vs/workbench/api/electron-browser/mainThreadConfiguration.ts#L51:35)<br />    at e.$re<br />

**Comment by sandy081** [comment]
This is expected.
