### ISSUE TITLE
Menu items not properly centered on LInux

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#55223]
The menu entries on linux are not properly verticaly centered. This is especialy visible when the item is selected. Notice in the picture how there is more "blue" space beneath the item than above the iteam.
fyi @misolori to verify if my eyes are correct

![screen shot 2018-07-27 at 11 19 13](https://user-images.githubusercontent.com/1926584/43312984-1413ac58-918f-11e8-8dd6-512c48438feb.png)

**Comment by sbatten** [comment]
@isidorn are you seeing this in insiders? I cannot repro on insiders on my Ubuntu machine, but this was an issue that was fixed for all platforms earlier this milestone.

**Comment by isidorn** [comment]
@sbatten I see this when running out of source - so with latest. This should not depend on if it is a packaged product or out of source. I am using ubuntu 18.04

**Comment by isidorn** [comment]
I still get this with latest vscode insiders

**Comment by sbatten** [comment]
font used was not same as the rest of the UI and this surfaced issues only on 18.04
