### ISSUE TITLE
macOS: Search with Google keyboard service doesn't work in VS Code

### ISSUE THREAD

**Issue by nikitavoloboev** [Microsoft/vscode#55245]
I am using `Search with Google` keyboard service found in `System Preferences -> Keyboard`: 

![2018-07-27 at 16 00](https://user-images.githubusercontent.com/6391776/43325127-2e31375a-91b6-11e8-9dc2-b05ca5de2109.png)

And the issue is that it doesn't seem to work in VS Code at all. I tried changing hotkeys assigned too but that doesn't help.

**Comment by alexandrudima** [comment]
@nikitavoloboev I also cannot get Search with Google to do anything meaningful on my machine, regardless of the software that has the focus. For example, I open `TextEdit` and then press `shift+cmd+L` (the default) and nothing happens.

**Comment by nikitavoloboev** [comment]
> I open TextEdit and then press shift+cmd+L (the default) and nothing happens.

It might be that cmd+shift+l is already in use by TextEdit for something. I have this service working flawlessly in all the apps I use. Only VS Code has issues with this service.

**Comment by alexandrudima** [comment]
I think this is a Chromium issue. I also cannot get this to run with Chrome. In the meantime, it would be pretty easy to create a VSCode extension that opens a browser with a google search of the selected text.
