### ISSUE TITLE
OS specific paths in settings.json

### ISSUE THREAD

**Issue by DexterMagnific** [Microsoft/vscode#55244]
Hello All,

I'd like to customize some paths that are OS dependant. Here is my example:
```
 "cmake.configureEnvironment": {
        "HEXAGON_SDK_ROOT" : "C:/Hexagon3.2/Hexagon_SDK/3.2"
    }
```

Unfortunately, when compiling the same code on Linux this will fail. I would appreciate some trick to set OS dependant paths, like:

```
 "cmake.configureEnvironment": {
        "HEXAGON_SDK_ROOT" : "C:/Hexagon3.2/Hexagon_SDK/3.2",
        when : "Windows"
    },
```

Thanks a lot

**Comment by kieferrm** [comment]
The extension that's reading this setting needs to define OS specific scopes. For example, we do this for the terminal executables.
