### ISSUE TITLE
Cmd + Click to go to defintion is flaky

### ISSUE THREAD

**Issue by jrmileham** [Microsoft/vscode#55241]
Issue Type: <b>Bug</b>

This one is hard to preproduce as it doesn't seem to happen during a particluar pattern of working. 

When I cmd + click on a function or variable I expect to be taken to the defintion. However sometimes it nothing happens. My work around is to quit VS Code and reopen it.

I'm using a Mac and I've noticed this issue on multiple macs.
I program mostly in javascript and typscript using react and express.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|9, 5, 4|
|Memory (System)|16.00GB (2.36GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
html-css-class-completion|Zig|1.17.1
html-snippets|abu|0.2.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.59
vscode-eslint|dba|1.4.12
githistory|don|0.4.2
xml|Dot|2.3.1
vscode-babel-coloring|dza|0.0.4
gitlens|eam|8.5.3
vscode-html-css|ecm|0.2.0
vscode-npm-script|eg2|0.3.5
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.3
beautify|Hoo|1.3.2
svg|joc|0.1.1
docthis|joe|0.7.1
Lua|key|0.0.9
terraform|mau|1.2.3
dotenv|mik|1.0.1
vscode-todo-parser|min|1.9.1
python|ms-|2018.7.1
cpptools|ms-|0.17.7
debugger-for-chrome|msj|4.8.2
material-icon-theme|PKi|3.5.2
code-spell-checker|str|1.6.10
open-in-browser|tec|1.1.0
vscode-jss-snippets|vis|0.2.2
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.8.0
JavaScriptSnippets|xab|1.7.0
ReactSnippets|xab|2.2.0
markdown-all-in-one|yzh|1.6.0

(1 theme extensions excluded)

</details>

**Comment by flotwig** [comment]
IntelliSense crashes frequently for me too while doing JavaScript, both on Windows and on OS X. I have to restart at least once daily to get it back to working properly.

**Comment by jrmileham** [comment]
I haven't tried it in the insiders build. But I have noticed it's been a problem for quite a few versions now. Maybe for the last 3 versions?? - Sorry for not being very specific.

When it next happens I'll capture more info to put here.

**Comment by mjbvz** [comment]
Closing as not actionable without more information.

Try with VS code 1.28 insiders and all extensions disabled. If you still see the problem, please share some example code or small example project that demonstrates this problem
