### ISSUE TITLE
Word matching is not working as supposed

### ISSUE THREAD

**Issue by feardarkness** [Microsoft/vscode#55242]
Issue Type: <b>Bug</b>

VsCode is highlighting the wrong words. It affects F2 (rename symbol) too. vscode is renaming randomly.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:40:20.190Z)
OS version: Linux x64 3.16.0-6-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590T CPU @ 2.00GHz (4 x 2331)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|7.74GB (0.15GB free)|
|Process Argv|/usr/share/code/code .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.3.1
beautify|Hoo|1.3.2
html-snippets|abu|0.2.1
compulim-vscode-closetag|Com|1.2.0
mustache|daw|1.1.1
vscode-eslint|dba|1.4.12
code-runner|for|0.9.3
node-module-intellisense|lei|1.5.0
vue|liu|0.1.5
vscode-todo-parser|min|1.9.1
prettify-json|moh|0.0.3
vscode-language-pack-es|MS-|1.25.2
cpptools|ms-|0.17.7
appidocsnippets|mya|0.1.17
trailing-spaces|sha|0.2.11
html5-boilerplate|sid|1.0.3
addDocComments|ste|0.0.8
bootstrap4-vscode|the|4.3.0
vscode-npm-scripts|tra|0.2.1
highlight-matching-tag|vin|0.4.4
gitblame|wad|2.4.2
bootstrap-3-snippets|wcw|0.1.0
local-history|xyz|1.7.0

</details>

![seleccion_112](https://user-images.githubusercontent.com/860571/43324304-ca485ed2-9181-11e8-97d6-86ed44217e15.png)

**Comment by kieferrm** [comment]
@feardarkness Do you have a concrete file or workspace that shows that behavior?

**Comment by feardarkness** [comment]
Btw, i just reinstalled everything from zero. The problem seems fized now. Thank you and sorry for not answering before.
