### ISSUE TITLE
Extension search bar breaks its border

### ISSUE THREAD

**Issue by nealot** [Microsoft/vscode#55251]
Issue Type: <b>Bug</b>

![screenshot_20180727_112233](https://user-images.githubusercontent.com/36805289/43329949-cfc38ea0-918f-11e8-906c-32b3b218d37f.png)
![screenshot_20180727_112959](https://user-images.githubusercontent.com/36805289/43330182-6f3e067c-9190-11e8-81fb-93910062a73c.png)

As seen in the image above, the right side of the border has a portion cut off for an unknown reason. This doesn't happen with any of the official themes but does happen with themes installed from the marketplace.

VS Code version: Code - Insiders 1.26.0-insider (dae69dbf00357ff8a3fe740a1f211d66b0b4681c, 2018-07-27T05:18:38.441Z)
OS version: Linux x64 4.17.8-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 1922)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.55GB (4.61GB free)|
|Process Argv|/opt/visual-studio-code-insiders/code-insiders|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
flutter-snippets|ale|0.0.2
gitignore|cod|0.5.0
transformer|dak|1.6.0
dart-code|Dar|2.16.0
flutter|Dar|2.16.0
gitlens|eam|8.5.3
vsc-material-theme|Equ|2.3.0
vscode-commands|fab|1.2.2
vscode-todo-plus|fab|2.2.1
toggler|hid|0.0.3
output-colorizer|IBM|0.1.2
vscode-insertdatestring|jsy|2.2.2
vscode-commitizen|Kni|0.5.0
Go|ms-|0.6.85
vscode-quick-open-create|noc|0.6.0
vsnotes|pat|0.5.1
vscode-docker|Pet|0.1.0
java|red|0.28.0
vscode-yaml|red|0.0.14
code-settings-sync|Sha|3.0.0
gitconfig|sid|1.0.1
code-spell-checker|str|1.6.10
vsfire|tob|1.3.2
vz-file-templates|vis|0.0.3
vscode-java-debug|vsc|0.10.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.7.1
vscode-maven|vsc|0.10.0

(1 theme extensions excluded)

</details>

**Comment by nealot** [comment]
This only seems to happen with some themes so I'm guessing it isn't the fault of the editor.

**Comment by JacksonKearl** [comment]
Could you specify which theme causes this? In your installed extensions one theme has been redacted, I assume that't the one, as vsc-material-theme doesn't seem to have this issue for me.

**Comment by JacksonKearl** [comment]
Got a repro with dracula

**Comment by JacksonKearl** [comment]
Put up a PR that fixes this in the cases I saw. Thanks for the report!

**Comment by nealot** [comment]
Thanks for the fix! I originally thought it was just one or two themes using a deprecated api or something but I realized that most marketplace themes were broken.
