### ISSUE TITLE
Search bar hide match word at first line

### ISSUE THREAD

**Issue by qiuyi21** [Microsoft/vscode#5525]
- VSCode Version: 1.0.0
- OS Version: OS X 10.11.4

Steps to Reproduce:
1.  Long text at one line
2.  Ctrl + F (Command + F) search the keyword
   <img width="1165" alt="2016-04-20 10 56 40" src="https://cloud.githubusercontent.com/assets/3156921/14662294/640976be-06e7-11e6-953f-355c7ac9abf1.png">
   <img width="1168" alt="2016-04-20 10 56 12" src="https://cloud.githubusercontent.com/assets/3156921/14662295/64755424-06e7-11e6-83b6-e1a8643aa3dd.png">

**Comment by cparker4486** [comment]
Forgive me for abusing the comments here but kudos to the team for cleaning up and organizing all the open issues. You all are doing a fantastic job.

**Comment by DeeHants** [comment]
I've just opened #30503 as the find window still overlaps lines that wrap.
