### ISSUE TITLE
Consider alternative code structure for Menu and ActionBar

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode#55258]
Currently, many changes to the custom menus depend on changing actionbar because the menu has no clean way of interacting with its own dom nodes. We get around this by using the `isMenu` option on actionbar but this is becoming cumbersome and leading to issues. It has been brought up by both @joaomoreno and @isidorn, so we should discuss cleaning up the approach.

**Comment by joaomoreno** [comment]
Why not forking ActionBar and just taking the stuff you really need into Menu? That code is also very old and probably could use a good cleanup anyway.

**Comment by sbatten** [comment]
@joaomoreno I thought about your suggestion, but first wanted to attempt the extension strategy as an evaluation of how related a `Menu` and `ActionBar` _really_ are. Given the code re-use we gain seen in the above PR, I am in favor of extension, but seeking opinions.
