### ISSUE TITLE
Better autocomplete

### ISSUE THREAD

**Issue by This-Cat-Is-On-Drugs** [Microsoft/vscode#55250]
The autocomplete in visual studio code is a bit weird because let's say that I make an application and I made a method called "ILoveMicrosoft", so when I try to call this function and right ILov and it will show me ILoveMicrosoft so I click Enter so it will complete it to ILoveMicrosoft but it won't put the brackets... it really annoys me cause I am used to using the normal visual studio...

**Comment by mjbvz** [comment]
What language?

**Comment by user3323** [comment]
@This-Cat-Is-On-Drugs  I'm sure it is because you choose the default snippet in the snippets list, instead of choosing your own. 
And I'm pretty sure, that you don't even see your own made method snippet in the list, because of this issue - https://github.com/Microsoft/vscode/issues/32201

**Comment by kieferrm** [comment]
Closing since we didn't receive the additional info.
