### ISSUE TITLE
TypeScript extension uses inconsistent path case when talking to tsserver

### ISSUE THREAD

**Issue by hmil** [Microsoft/vscode#55266]
- VSCode Version: 1.25.0
- OS Version: macOS

Steps to Reproduce:

1. Open an empty directory
2. Create a file named 'TestClass.ts' with just an empty class declaration
3. Reload the window _(this step is not necessary, it just helps to get a cleaner log)_
4. Open the tsserver log

**expected**: All occurences of `TestClass.ts` in the log have the same case.
**actual**: There are mixed occurences with lowercase and uppercase.

<details>
<summary>sample log output</summary>

Info 61   [22:10:52.30] Host configuration update for file /Users/hmil/workspace/vscode-case-test/TestClass.ts
Info 62   [22:10:52.30] response:
    {"seq":0,"type":"response","command":"configure","request_seq":5,"success":true}
Perf 63   [22:10:52.30] 5::configure: async elapsed time (in milliseconds) 0.6735
Info 64   [22:10:52.30] request:
    {"seq":6,"type":"request","command":"getApplicableRefactors","arguments":{"file":"/Users/hmil/workspace/vscode-case-test/TestClass.ts","startLine":2,"startOffset":7,"endLine":2,"endOffset":7}}
Info 65   [22:10:52.31] Starting updateGraphWorker: Project: /dev/null/inferredProject1*
Info 66   [22:10:52.31] Finishing updateGraphWorker: Project: /dev/null/inferredProject1* Version: 1 structureChanged: false Elapsed: 0ms
Perf 67   [22:10:52.79] 6::getApplicableRefactors: elapsed time (in milliseconds) 48.8006
Info 68   [22:10:52.85] response:
    {"seq":0,"type":"response","command":"getApplicableRefactors","request_seq":6,"success":true,"body":[]}
Info 69   [22:10:52.85] request:
    {"seq":7,"type":"request","command":"getOutliningSpans","arguments":{"file":"/Users/hmil/workspace/vscode-case-test/TestClass.ts"}}
Perf 70   [22:10:52.87] 7::getOutliningSpans: elapsed time (in milliseconds) 1.6605
Info 71   [22:10:52.87] response:
    {"seq":0,"type":"response","command":"getOutliningSpans","request_seq":7,"success":true,"body":[{"textSpan":{"start":{"line":2,"offset":23},"end":{"line":6,"offset":2}},"hintSpan":{"start":{"line":2,"offset":1},"end":{"line":6,"offset":2}},"bannerText":"...","autoCollapse":false,"kind":"code"},{"textSpan":{"start":{"line":3,"offset":25},"end":{"line":5,"offset":6}},"hintSpan":{"start":{"line":3,"offset":5},"end":{"line":5,"offset":6}},"bannerText":"...","autoCollapse":true,"kind":"code"}]}
Info 72   [22:10:52.87] request:
    {"seq":8,"type":"request","command":"geterr","arguments":{"delay":0,"files":["/users/hmil/workspace/vscode-case-test/testclass.ts"]}}
Perf 73   [22:10:52.88] 8::geterr: async elapsed time (in milliseconds) 0.7149
Info 74   [22:10:52.88] request:
    {"seq":9,"type":"request","command":"getApplicableRefactors","arguments":{"file":"/Users/hmil/workspace/vscode-case-test/TestClass.ts","startLine":2,"startOffset":7,"endLine":2,"endOffset":7}}
Info 75   [22:10:52.88] Starting updateGraphWorker: Project: /dev/null/inferredProject1*
Info 76   [22:10:52.88] Finishing updateGraphWorker: Project: /dev/null/inferredProject1* Version: 1 structureChanged: false Elapsed: 0ms
Perf 77   [22:10:52.89] 9::getApplicableRefactors: elapsed time (in milliseconds) 0.4481
Info 78   [22:10:52.89] response:
    {"seq":0,"type":"response","command":"getApplicableRefactors","request_seq":9,"success":true,"body":[]}
Info 79   [22:10:52.89] Starting updateGraphWorker: Project: /dev/null/inferredProject1*
Info 80   [22:10:52.89] Finishing updateGraphWorker: Project: /dev/null/inferredProject1* Version: 1 structureChanged: false Elapsed: 0ms
Info 81   [22:10:52.89] Starting updateGraphWorker: Project: /dev/null/inferredProject1*
Info 82   [22:10:52.89] Finishing updateGraphWorker: Project: /dev/null/inferredProject1* Version: 1 structureChanged: false Elapsed: 0ms
Info 83   [22:10:52.89] event:
    {"seq":0,"type":"event","event":"syntaxDiag","body":{"file":"/users/hmil/workspace/vscode-case-test/testclass.ts","diagnostics":[]}}
Info 84   [22:10:52.90] Starting updateGraphWorker: Project: /dev/null/inferredProject1*
Info 85   [22:10:52.90] Finishing updateGraphWorker: Project: /dev/null/inferredProject1* Version: 1 structureChanged: false Elapsed: 0ms
Info 86   [22:10:52.90] Starting updateGraphWorker: Project: /dev/null/inferredProject1*
Info 87   [22:10:52.90] Finishing updateGraphWorker: Project: /dev/null/inferredProject1* Version: 1 structureChanged: false Elapsed: 0ms
Info 88   [22:10:52.115] event:
    {"seq":0,"type":"event","event":"semanticDiag","body":{"file":"/users/hmil/workspace/vscode-case-test/testclass.ts","diagnostics":[{"start":{"line":4,"offset":9},"end":{"line":4,"offset":25},"text":"Type '\"string\"' is not assignable to type 'number'.","code":2322,"category":"error"}]}}
Info 89   [22:10:52.115] Starting updateGraphWorker: Project: /dev/null/inferredProject1*
Info 90   [22:10:52.116] Finishing updateGraphWorker: Project: /dev/null/inferredProject1* Version: 1 structureChanged: false Elapsed: 1ms
Info 91   [22:10:52.117] event:
    {"seq":0,"type":"event","event":"suggestionDiag","body":{"file":"/users/hmil/workspace/vscode-case-test/testclass.ts","diagnostics":[]}}
Info 92   [22:10:52.117] event:
    {"seq":0,"type":"event","event":"requestCompleted","body":{"request_seq":8}}
Info 93   [22:10:52.232] request:
    {"seq":10,"type":"request","command":"geterr","arguments":{"delay":0,"files":["/users/hmil/workspace/vscode-case-test/testclass.ts"]}}
Perf 94   [22:10:52.232] 10::geterr: async elapsed time (in milliseconds) 0.3088
Info 95   [22:10:52.233] Starting updateGraphWorker: Project: /dev/null/inferredProject1*
Info 96   [22:10:52.234] Finishing updateGraphWorker: Project: /dev/null/inferredProject1* Version: 1 structureChanged: false Elapsed: 0ms
Info 97   [22:10:52.234] Starting updateGraphWorker: Project: /dev/null/inferredProject1*
Info 98   [22:10:52.234] Finishing updateGraphWorker: Project: /dev/null/inferredProject1* Version: 1 structureChanged: false Elapsed: 0ms
Info 99   [22:10:52.234] event:
    {"seq":0,"type":"event","event":"syntaxDiag","body":{"file":"/users/hmil/workspace/vscode-case-test/testclass.ts","diagnostics":[]}}
Info 100  [22:10:52.234] Starting updateGraphWorker: Project: /dev/null/inferredProject1*
Info 101  [22:10:52.234] Finishing updateGraphWorker: Project: /dev/null/inferredProject1* Version: 1 structureChanged: false Elapsed: 0ms
Info 102  [22:10:52.234] Starting updateGraphWorker: Project: /dev/null/inferredProject1*
Info 103  [22:10:52.234] Finishing updateGraphWorker: Project: /dev/null/inferredProject1* Version: 1 structureChanged: false Elapsed: 0ms
Info 104  [22:10:52.234] event:
    {"seq":0,"type":"event","event":"semanticDiag","body":{"file":"/users/hmil/workspace/vscode-case-test/testclass.ts","diagnostics":[{"start":{"line":4,"offset":9},"end":{"line":4,"offset":25},"text":"Type '\"string\"' is not assignable to type 'number'.","code":2322,"category":"error"}]}}
Info 105  [22:10:52.234] Starting updateGraphWorker: Project: /dev/null/inferredProject1*
Info 106  [22:10:52.235] Finishing updateGraphWorker: Project: /dev/null/inferredProject1* Version: 1 structureChanged: false Elapsed: 0ms
Info 107  [22:10:52.235] event:
    {"seq":0,"type":"event","event":"suggestionDiag","body":{"file":"/users/hmil/workspace/vscode-case-test/testclass.ts","diagnostics":[]}}
Info 108  [22:10:52.235] event:
    {"seq":0,"type":"event","event":"requestCompleted","body":{"request_seq":10}}
Info 109  [22:10:52.420] request:
    {"seq":11,"type":"request","command":"getApplicableRefactors","arguments":{"file":"/Users/hmil/workspace/vscode-case-test/TestClass.ts","startLine":2,"startOffset":7,"endLine":2,"endOffset":7}}
Info 110  [22:10:52.420] Starting updateGraphWorker: Project: /dev/null/inferredProject1*
Info 111  [22:10:52.420] Finishing updateGraphWorker: Project: /dev/null/inferredProject1* Version: 1 structureChanged: false Elapsed: 0ms
Perf 112  [22:10:52.420] 11::getApplicableRefactors: elapsed time (in milliseconds) 0.4713
Info 113  [22:10:52.420] response:
    {"seq":0,"type":"response","command":"getApplicableRefactors","request_seq":11,"success":true,"body":[]}

</details>

---

This inconsistency confuses language services such as `tslint-language-service`. See https://github.com/angelozerr/tslint-language-service/issues/76

**Comment by mjbvz** [comment]
Fixed by 6ffbde1
