### ISSUE TITLE
VSCODE consumes more RAM and random spike in Disk usage and CPU

### ISSUE THREAD

**Issue by syedirfan7** [Microsoft/vscode#55260]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
Angular-BeastCode|Mik|6.2.2
git-merger|sha|0.4.1

---

Steps to Reproduce:

1.normal opening of angular code
2.running server to develop code 

Reproduces without extensions: Yes

**Comment by kieferrm** [comment]
Please follow https://github.com/Microsoft/vscode/wiki/Performance-Issues to file a performance issue.
