### ISSUE TITLE
TypeScript debugger fails to start with preLaunchTask of type other than "typescript"

### ISSUE THREAD

**Issue by jadchaar** [Microsoft/vscode#55262]
Issue Type: <b>Bug</b>

Using a regular Typescript task configuration works great:
```json
         {
            "label": "compile",
            "type": "typescript",
            "tsconfig": "PATH_TO_tsconfig.json",
            "problemMatcher": [
                "$tsc",
                "$tslint5"
            ],
            "presentation": {
                "reveal": "always"
            }
        }
```

But when I do something like a task of type `npm` or type `shell` to try and add command line arguments to `tsc` (as I want my compile configuration to have different compiler options than the regular configuration), the compiling works great (I see the contents in my `dist` folder just fine), but the debugger sits on the "loading" state (the animation underneath the start button. I go to the terminal and close the "node watcher" process and boom the debugger begins. Any ideas? I feel like this has something to do with the "custom" tsc task not sending a proper exit code.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.12GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-javascript-snippet-pack|aka|0.1.5
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.19.0
vscode-eslint|dba|1.4.12
vscode-quick-select|dba|0.2.6
githistory|don|0.4.2
gitlens|eam|8.5.3
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.34
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.3.0
auto-close-tag|for|0.5.6
code-runner|for|0.9.3
terminal|for|0.0.10
beautify|Hoo|1.3.2
vscode-scss|mrm|0.6.2
python|ms-|2018.7.1
cpptools|ms-|0.17.7
Go|ms-|0.6.85
vscode-docker|Pet|0.1.0
tsimporter|pmn|1.2.14
typescript-hero|rbb|2.3.2
sass-indented|rob|1.4.9
gitblame|wad|2.4.2
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.7.0
markdown-all-in-one|yzh|1.6.0

</details>

**Comment by roblourens** [comment]
Can you show the task that doesn't work? Debugging won't start until the task has terminated. Are you running a tsc watch task?

**Comment by jadchaar** [comment]
So when I run a regular type "typescript" task, compile and watch, they both work great.

But if I try and use something like:
```
        {
            "label": "watch",
            "type": "shell",
            "command": "node",
            "args": [
                "PATH_TO_PARTICULAR_TSC_IN_NODE_MODULES",
                "-w",
                "-p",
                "scripts/bvt/tsconfig.json",
                "--inlineSourceMap",
                "true"
            ],
            "problemMatcher": [
                "$tsc-watch",
                "$tslint5"
            ],
            "presentation": {
                "reveal": "always"
            }
        },
```
The debugger just doesn't run. I deleted my `dist` folder and confirmed that everything went through with this command perfectly on the tsc compile side. But for some reason vscode is not detecting that this event has completed while loading the debug session.

I worked around this by just creating a separate tsconfig just for debugging purposes (`tsconfig_debug.json`), but that solution is not ideal.

**Comment by isidorn** [comment]
Please add this to your tasks.json 			
```json
"isBackground": true,
```

fyi @dbaeumer

**Comment by jadchaar** [comment]
@isidorn thanks for letting me know, I will give it a try. Any idea why this must be added for the task to work properly? Should any preLaunchTask be background?
