### ISSUE TITLE
Command extension runs indefinitely

### ISSUE THREAD

**Issue by rkhat** [Microsoft/vscode#5526]
- VSCode Version: 1.0.0
- OS Version: Windows 10

Steps to Reproduce:

1. Add following code to main.ts

   ```typescript
   import { window, commands, OutputChannel, Disposable, ExtensionContext} from 'vscode';
	 
   let channel: OutputChannel;
	 
   export function activate(context: ExtensionContext): void {
   	registerCommands(context);
   	channel = window.createOutputChannel('Compile');
   	context.subscriptions.push(channel);
   }
   
   export function deactivate(context: ExtensionContext): void {
   	console.log('deactivated');
   }
   
   function registerCommands(context: ExtensionContext): void {
   	let c1: Disposable = commands.registerCommand('test1', () => {
   		var test: number = 0;
   		(function testFunc() {
   			channel.appendLine(`test: ${test++}`);
   			setTimeout(function(){
   				testFunc();
   			},2000);
   		})();
   	});
   	context.subscriptions.push(c1);
   }
   ```

2. Add this to package.json (remember to change main value to compiled js)
  
   ```json
   {
   	"main": "<path-to-js>",
   	"activationEvents": [
   		"onCommand:gcc-compile"
   	],
   	"contributes": {
   		"commands": [
   			{
   				"command": "test1",
   				"title": "MY TEST 1"
   			}
   		]
   	}
   }
   ```

3. When you run the command multiple times, the previous instances don't shutdown. This will create an issue especially if a continuous command (such as watcher) is running. The only way to stop commands is to close Visual Studio Code.

Suggesions:

1. Function to stop one of the currently running commands.

2. Force single instance of an extension command.

3. A function similar to `export function deactivate(context: ExtensionContext)` that runs before every command call. One of the parameters should be an array of currently running commands with the ability to deactivate them.

**Comment by jrieken** [comment]
The code of your command is basically an endless loop and there is no way we can stop that from the outside. You should store the handle `setTimeout` returns and invoke [`clearTimeout`](https://developer.mozilla.org/en-US/docs/Web/API/WindowTimers/clearTimeout) before proceeding with another run. 

```
    (function testFunc() {
        channel.appendLine(`test: ${test++}`);
        setTimeout(function(){
            testFunc();
        },2000);
    })();
```

**Comment by rkhat** [comment]
The issue is how can I know whether another task is invoked. You can't access or check other tasks from within a running task unless I missed something in the API.

You can change the example to invoking a child process:
```
tsc -w
```

This task runs indefinitely. If the user wants to change a setting (extension supports extra settings) or accidentally invoked the same task again, you get multiple instances of typescript watcher modifying the same files.
