### ISSUE TITLE
Programmable buttons

### ISSUE THREAD

**Issue by graph** [Microsoft/vscode#55264]
in the tasks field json I want to add button configurations. I don't know where the buttons will go,  maybe on the left side with the rest of the buttons. It feels more satisfying hitting a build button than typing a shortcut. 99% of the time I run the same task over & over again.

I'm not very experienced with vs code so Iam probably wrong, but current extensions don't seem to let you execute a task. But they do let your run arbitrary commands but it means recreating the tasks essentially.

edit: I found issue #10709 I guess it's not going to happen :(

**Comment by alexr00** [comment]
You can execute a task via the API: https://code.visualstudio.com/api/references/vscode-api#tasks
Using that, you could write an extension that adds buttons that run tasks to the status bar.
