### ISSUE TITLE
Code coloring issue 

### ISSUE THREAD

**Issue by kirubiel** [Microsoft/vscode#55279]
Anything you write after list: will assume a color and keep that color outside of the script as well. It will bleed into the rest of the HTML below it.

<script>
    var x;
    var y;
    
    list: 
      .
      .
      .
      .
     document.getElementById("bla").innerHTML = x;

</script>

**Comment by kieferrm** [comment]
@kirubiel This is what I see. Pls provide more details.

![screen shot 2018-07-27 at 6 04 58 pm](https://user-images.githubusercontent.com/4674940/43351491-9f21eef8-91c7-11e8-8a19-0ac23c855711.png)

**Comment by kirubiel** [comment]
I actually wrote the code vertically. Not horizontally. So if you could write it downwards you could see what I was trying to say. Also put some code in place of the dots(they were for demonstration). In the dark+ (default dark) theme I'm on, the "list" label changes to a lighter shade of blue than the one for the HTML tags. Sorry I couldn't provide a screenshot due to network problems. Also I noticed that I was using a later version (1.23.1) of VS Code for 32 bit. Maybe it's fixed there idk. But just in case.

**Comment by kirubiel** [comment]
I think I got the exact code that is causing the issue. 

https://www.w3schools.com/js/tryit.asp?filename=tryjs_break_list 

Type all of the code in the page above into VS Code.

**Comment by kirubiel** [comment]
Sorry I am having network issues. I will reply tomorrow with a screenshot.

**Comment by kieferrm** [comment]
@kirubiel this is what I get with the example you reference:

![screen shot 2018-07-30 at 11 24 33 am](https://user-images.githubusercontent.com/4674940/43415742-3f15d83c-93eb-11e8-8ef1-e6b8e4b7e41c.png)

**Comment by kirubiel** [comment]
[
![Uploading 20180731_132553.jpg…]()
](url)
