### ISSUE TITLE
Unclicking breakpoint removes icon but does not send another setBreakpoints command

### ISSUE THREAD

**Issue by pieandcakes** [Microsoft/vscode#55274]
Issue Type: <b>Bug</b>

Set a breakpoint and remove it before the response comes back.

Protocol: Expect a set Breakpoint for setting it and then another for removing it.

Actual: get a setbreakpoint for setting the breakpoint but not one for removing it BUT the UI doesn't show the breakpoint anymore. 

This happens with a slower connection while using the C/C++ extension.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:11.471Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.96GB (5.53GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.17.7

</details>

**Comment by isidorn** [comment]
How do you set and remove the breakpoint? By clicking in the glyph margin?
Is that the only breakpoint that you have?

**Comment by pieandcakes** [comment]
Yes, that is correct. Click to set and then click to unset. It gets unset but isn't sending the SetBreakpoints message if the original SetBreakpoints message response hasn't been received.

**Comment by pieandcakes** [comment]
@isidorn this has caused reports of our breakpoints not being correct in certain scenarios. I feel like this should be something that gets fixed.
