### ISSUE TITLE
Auto import is dangerous. Should be off by default.

### ISSUE THREAD

**Issue by wardbell** [Microsoft/vscode#55276]
Maybe you have other stories like this one.

## Hours of Woe

Visual Studio Code  added an `environment` file TS import statement for me … without asking … and just happened to pick a _production version of that file_ instead of the development version I'm requesting with my build system.

>this is an Angular app, using the CLI to build with `ng build`

Naturally the production file had vastly different settings including URLs to remote services.

VS Code did this was to just one source file!  Which meant I got a mix of dev and production environment settings from the two different files, causing the app to behave one way running one part and another way running another part.:sob:

Who even LOOKS for that kind of error? I’m still not sure how I figured it out.

## Workaround

Friends tell me to turn this feature off in User Setting.

```
 "typescript.autoImportSuggestions.enabled": false,
```
That's what I'll do. But woe to all the users who don't know about this.

**Maybe it should be off by default and marked experimental**. 
Folks should learn just how unreliable this feature is.

**Comment by mjbvz** [comment]
Sorry for the troubles. No plans to change the default though as the feature generally is quite helpful and has been enabled for almost a year at this point.

Auto imports are indicated in the completion details:

<img width="970" alt="screen shot 2018-07-27 at 4 14 12 pm" src="https://user-images.githubusercontent.com/12821956/43349908-1fdfa612-91b8-11e8-997e-cd275990a716.png">

and you can use that setting to disable it for individual projects or at a user level.
