### ISSUE TITLE
Settings "search.include"

### ISSUE THREAD

**Issue by domske** [Microsoft/vscode#55271]
There is a setting "search.exclude", but not "search.include". 
I want to exclude ALL (`**`) BUT not `/src`. Only search in `/src`.
I expected that I can set the `include` which is evaluated after `exclude` to set:

```json
{
  "search.exclude": {
    "**": true
  },
  "search.include": {
    "/src": true
  }
}
```
(include > exclude)

Is there already way to only search in the src-folder? Without setting it every time in the vs code editor earch input? Is there already a setting / config file to enable this?

I do not want to exclude every folder in my project. It's easier to just include the few folders. 

Current VS Code Version: 1.25.1

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/869
