### ISSUE TITLE
Keep editor tab open after a file was deleted or ask before closing the editor tab

### ISSUE THREAD

**Issue by LordHog** [Microsoft/vscode#55284]
Having a brain cramp every now and then I have accidentally deleted a file from the system.  When that even occurs VSC closes that editor tab straight away.  I would like for VSC to keep the editor tab open when this event occurs.  The icon can change to the circle indicating the file hasn't been saved.

**Comment by kieferrm** [comment]
@LordHog set  `workbench.editor.closeOnFileDelete` to false in your user settings and you're on the safe side.

**Comment by LordHog** [comment]
@kieferrm Thanks.  I looked for a setting, but the keywords I used didn't show this option.  I even posted a question in gitter/vscode before making this request.  Glad to known it already exist.  Thanks.!

**Comment by LordHog** [comment]
Still, I don't know why this is enabled by default. Good way for a user to lose their data by accident quickly.  Most other editors have this feature disabled by default.  Perhaps the vscode team might consider having this option set to false by default.

**Comment by kieferrm** [comment]
@LordHog thanks for the recommendation.
