### ISSUE TITLE
Custom theme problems

### ISSUE THREAD

**Issue by yi-huan** [Microsoft/vscode#5528]
- VSCode Version: 1.0.0-insider
- OS Version:win8.1

**Following from the automatic translation:**
I think the built-in theme colored parts too small, so my own custom themes, problems encountered in this process are as follows:

- All:
  I hope I can define background color with RGBA, now only defines the color and font style. 

- In CSS part（Dark Visual Studio）:
  1.
![2016-04-20_114035](https://cloud.githubusercontent.com/assets/5660790/14662870/10417a12-06ed-11e6-88e1-bbfa4fc3b1c7.png)
![2016-04-20_114253](https://cloud.githubusercontent.com/assets/5660790/14662878/23bd76d6-06ed-11e6-9fb1-cdc3fde8ca62.png)
[Hidden], the symbol [] echo hidden separately.

2.
![2016-04-20_114712](https://cloud.githubusercontent.com/assets/5660790/14662972/1aaa417c-06ee-11e6-8435-152eb7ec57a5.png)
![2016-04-20_114951](https://cloud.githubusercontent.com/assets/5660790/14662975/2eb42b88-06ee-11e6-900a-a14de825da25.png)
@Keyframes should be in a tag and zoomIn in another tab

- SCSS part (description with a custom theme)
1. 
That's sort of the plan:
![2016-04-20_120058](https://cloud.githubusercontent.com/assets/5660790/14663118/9ceef316-06ef-11e6-9529-834e048a9e83.png)

But in fact it is:
![2016-04-20_115856](https://cloud.githubusercontent.com/assets/5660790/14663134/ba86e5dc-06ef-11e6-98c7-22194dd2795f.png)
The $before-content variable in the argument, should be like variables, but VSCode developer tools, see the label class and property name for the style class is the same.
@Mixin sameCont () is incorrect.

![2016-04-20_120901](https://cloud.githubusercontent.com/assets/5660790/14663211/b736568c-06f0-11e6-9cf6-45210ac53444.png)
The symbol names in the style, such as: (a) these symbols were not independence and CSS within a tag.

2.SCSS auto-complete is not accurate.
CSS AutoComplete and coloring:
![css](https://cloud.githubusercontent.com/assets/5660790/14665245/4c04e8a6-0704-11e6-8293-d8a251e24d34.gif)
Smart tips and tips for CSS rules (there are some errors in the value that corresponds to the tip). Corresponds to value judgments are correct, look at the picture:
![2016-04-20_143748](https://cloud.githubusercontent.com/assets/5660790/14665399/85c42b1e-0705-11e6-8d4b-485a12773e04.png)
![2016-04-20_143923](https://cloud.githubusercontent.com/assets/5660790/14665469/09ac030c-0706-11e6-9592-5dd629005255.png)

In the automatic completion of SCSS and coloring
![scss](https://cloud.githubusercontent.com/assets/5660790/14665338/f3488974-0704-11e6-87e3-cffef5777bf2.gif)
Although IntelliSense, but hints of other rules (such as a DIV) that correspond to the property values there are other superfluous. Corresponding values to determine correct.
![2016-04-20_144117](https://cloud.githubusercontent.com/assets/5660790/14665534/721c6d32-0706-11e6-812c-8e11a66598bf.png)

- Javascript
Only keyword coloring, (developer tools) the content does not contain special class cannot be modified.
![2016-04-20_144638](https://cloud.githubusercontent.com/assets/5660790/14665600/d4827106-0706-11e6-8ce7-f3b02414401f.png)

![2016-04-20_144905](https://cloud.githubusercontent.com/assets/5660790/14665637/134a8702-0707-11e6-97de-16236c4711d3.png)
Method names, parameters, local variables, global variables, such as separate independent label, easy coloring.
Should do well in the following figure:
![2016-04-20_145205](https://cloud.githubusercontent.com/assets/5660790/14665693/7d901c30-0707-11e6-94e7-ba47f2fc7aa2.png)

# Above and below the content line. Skip.

**原文： **
建议：我希望能用rgba定义背景色，现在只能定义显示颜色及字体样式。

我觉得自带主题着色部分过少，所以我自己自定义主题，在此过程中遇到的问题如下：

- CSS 部分（用 Dark Visual Studio 主题说明）
1、
![2016-04-20_114035](https://cloud.githubusercontent.com/assets/5660790/14662870/10417a12-06ed-11e6-88e1-bbfa4fc3b1c7.png)
![2016-04-20_114253](https://cloud.githubusercontent.com/assets/5660790/14662878/23bd76d6-06ed-11e6-9fb1-cdc3fde8ca62.png)
[hidden] 中，符号[]应和 hidden 分开。
2、
![2016-04-20_114712](https://cloud.githubusercontent.com/assets/5660790/14662972/1aaa417c-06ee-11e6-8435-152eb7ec57a5.png)
![2016-04-20_114951](https://cloud.githubusercontent.com/assets/5660790/14662975/2eb42b88-06ee-11e6-900a-a14de825da25.png)
@keyframes 应该在一个标签内，zoomIn在另外一个标签

- SCSS 部分（用自定义主题说明）
1、
应该是这样：
![2016-04-20_120058](https://cloud.githubusercontent.com/assets/5660790/14663118/9ceef316-06ef-11e6-9529-834e048a9e83.png)

但实际上是：
![2016-04-20_115856](https://cloud.githubusercontent.com/assets/5660790/14663134/ba86e5dc-06ef-11e6-98c7-22194dd2795f.png)
参数中的  $before-content 是变量，应该和变量一样，但是在VSCode开发者工具中，看到的标签 class 和样式的属性名称的 class 是一样的。
@mixin sameCont() 也是有误。

![2016-04-20_120901](https://cloud.githubusercontent.com/assets/5660790/14663211/b736568c-06f0-11e6-9cf6-45210ac53444.png)
样式中的名称的符号，如  : () 这些符号未和 css 那样 独立出来在一个标签内。

2、SCSS自动完成不准确。
在 css 的自动完成及着色：
![css](https://cloud.githubusercontent.com/assets/5660790/14665245/4c04e8a6-0704-11e6-8293-d8a251e24d34.gif)
有智能提示，且提示的内容均为 css 的规则（在对应的值提示中也有一些错误）。对应的值能判断是否正确，看图：
![2016-04-20_143748](https://cloud.githubusercontent.com/assets/5660790/14665399/85c42b1e-0705-11e6-8d4b-485a12773e04.png)
![2016-04-20_143923](https://cloud.githubusercontent.com/assets/5660790/14665469/09ac030c-0706-11e6-9592-5dd629005255.png)

在 scss 的自动完成及着色
![scss](https://cloud.githubusercontent.com/assets/5660790/14665338/f3488974-0704-11e6-87e3-cffef5777bf2.gif)
虽有智能提示，但提示的内容有其他规则（如 div），对应的属性值也有其他多余的。对应的值不能判断是否正确。
![2016-04-20_144117](https://cloud.githubusercontent.com/assets/5660790/14665534/721c6d32-0706-11e6-812c-8e11a66598bf.png)

- Javascript
仅有关键字才能着色，（在开发者工具中）其他的内容不含特殊class不能修改
![2016-04-20_144638](https://cloud.githubusercontent.com/assets/5660790/14665600/d4827106-0706-11e6-8ce7-f3b02414401f.png)

![2016-04-20_144905](https://cloud.githubusercontent.com/assets/5660790/14665637/134a8702-0707-11e6-97de-16236c4711d3.png)

应该将 方法名，参数，局部变量，全局变量等 分开独立标签，才方便着色。
应做到如下图比较好：
![2016-04-20_145205](https://cloud.githubusercontent.com/assets/5660790/14665693/7d901c30-0707-11e6-94e7-ba47f2fc7aa2.png)

**Comment by aeschli** [comment]
Hi @yi-huan, first, thanks for taking the time to submit and translate the issue.
Please, next time create one issue per item. Not all issues are handled by the same developer. It also make the discussion very difficult if there are multiple issues.

CSS 1: Is `[hidden]` valid css?
CSS 2: that's #3481
SCSS 1: parameter name highlighting: I delivered a fix that will change it to the same color as variables
SCSS: @mixin inside @if: I delivered a fix
SCSS 2: Not sure what you mean. Please file a separate issue containing the values that you think are not valid. What you see there are also snippets. Issue for that is #2343
SCSS2: Coloring of invalid values. Please file a separate feature request. We currently have no plans to do the same as for CSS.
JavaScript: Coloring of function and variable references: That's issue #3886.

**Comment by yi-huan** [comment]
@aeschli Thank you for your answer。
I am doing a vscode theme.
As far as I know, heme colors are generated based on the `file.tmTheme` file control display inline styles.
CSS 1 : `[hidden]`  Just for coloring,
JavaScript:  For vscode method names, properties, variables   are not separated, so I can't all coloring.They do not have unique class name.
