### ISSUE TITLE
Test: webview icons

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#55282]
Test for #48864

- [x] Mac @ramya-rao-a 
- [x] Linux @roblourens 
- [x] Windows @JacksonKearl 

Complexity: 2

**Summary**
Webviews can now set icons using `WebviewPanel.iconPath`. This URI points to an icon file on disk

**Testing**
Try updating [the webview sample](https://github.com/Microsoft/vscode-extension-samples/tree/master/webview-sample) to set a webview icon. Verify:

- The icon can be set
- The icon can be changed dynamically 
- The right icon is used for light and dark themes
- The icon is persisted for serialized webviews

**Comment by roblourens** [comment]
I think you mentioned this in sitdown once, but why isn't `ThemeIcon` supported?
