### ISSUE TITLE
Auto-revival of default keybindings

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#55288]
- VSCode Version: 1.26.0-ins
- OS Version: win7x64

I have my snippet for key combination `Ctrl+K Ctrl+K`

Some Insiders builds earlier we've got an update, where the default keybinding ...

```
{
  "key": "ctrl+k ctrl+k",
  "command": "-editor.action.defineKeybinding",
  "when": "editorTextFocus && !editorReadonly && editorLangId == 'jsonc'"
},
```
... totally ignoring User key binding for `Ctrl+K Ctrl+K` , became being an interceptor.

1. Question is... what the hell? How can Default key binding has higher priority than User's one?
2. Why the Default key binding **does not see** User's one?
3. If the Default one sees the User's one - Default's one should be inactive (grey color). Why it's not?

Even more... if you will set another key combination for    - it will move to your file with key bindings, but then if you want just comment it - it will auto revive in global keybindings file!

And more ........ if you just want to delete these annoying interceptors - they will revive over and over again, by jumping to your keybindings file.... when you delete them in your file - they will jump back to global file.

And again... what the hell ?

GIF:

![auto-revival of default keyb](https://user-images.githubusercontent.com/24613274/43352137-9b10ac18-9227-11e8-8037-19d75e11db7b.gif)

Make attention about moment, when you change the key binding for **_"command": "-editor.action.defineKeybinding"_** - it will move this command to your file with your new key binding, and the same moment auto add it's own CTRL+K CTRL+K after it.

It acts absolutely like malware code.

**Comment by kieferrm** [comment]
1. You define 'Ctrl+K Cltr+K' to insert a snippet when a text editor has focus. Your definition exists in addition to the two default bindings for 'Ctrl+K Ctrl+K' that have different `when` clauses.
2. When you delete the default keybindings you see the 'unbinding' instructions in your `json` file on the right. This is when the command string is prefixed with `-`.  When you remove the unbinding instructions in your `json` file the default bindings are back.
3. You then bind `keybindings.editor.definekeybinding` to 'Ctrl+k Ctrl+i`. This also unbinds 'Ctrl+K Ctrl+K' for this command. These two instructions how up in your `json` file on the right. When you delete those two instructions, the default keybindings are back.

All three points are working as expected. Under which circumstances is your 'insert snippet' command ignored.

**Comment by user3323** [comment]
@kieferrm  hello ...

1. Well, it turns out, it's not about `Ctrl+K Ctrl+K`, but about any keybinding for command **_editor.action.insertSnippet_**
It doesn't work at all. And it happened in 
I have nothing on Ctrl+K Ctrl+V, so I've bound this combination to insert snippet.
And nothing happens. Neither in JS file, nor in Plain Text.

```
{
  "key": "ctrl+k ctrl+v",
  "command": "editor.action.insertSnippet",
  "when": "editorTextFocus",
  "args": {
    "snippet": "console.log($1);$0"
  }
}
```

Try it yourself.

2. ...
> When you delete the default keybindings you see the 'unbinding' instructions in your json file on the right. This is when the command string is prefixed with -. When you remove the unbinding instructions in your json file the default bindings are back.

If you need to collect removed default keybindings in somewhere - just make another "trash" file for all removed keybindings. It would be great. I know, it's so much work to do, and change a lot of code, and we all are lazy guys, but that's how it **_SHOULD_** work in perfect way.
For now, all these **_-instructions_** are making a huge mess, and really confusing the user.

**Comment by kieferrm** [comment]
Thanks @user3323. This helped to reproduce the issue. We're failing in https://github.com/Microsoft/vscode/blob/b9b78028d58e8c89b94843ff2a17f6c3b6f46f8e/src/vs/workbench/parts/snippets/electron-browser/snippetsFile.ts#L36

as `prefix` in your case (you define the snippet in place) is `undefined`.
