### ISSUE TITLE
Consider using left aligned checkboxes for activity bar context menu

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#55296]
Before:
![before](https://user-images.githubusercontent.com/9638156/43356572-b04c9ea8-927b-11e8-96ed-d44838c38703.png)

Now:
![after](https://user-images.githubusercontent.com/9638156/43356575-c4fe24c0-927b-11e8-82f9-c44a55d1f55a.png)

**Comment by usernamehw** [comment]
Is the removal of keybinding tips intentional?

**Comment by sbatten** [comment]
duplicate of #52929
