### ISSUE TITLE
 My problem is about code folding when i am coding in vue 

### ISSUE THREAD

**Issue by waihoyu** [Microsoft/vscode#55295]
- VSCode Version:1.25.1
- OS Version: win7

My code is here
![1](https://user-images.githubusercontent.com/38418753/43355764-cc447090-9294-11e8-8d07-afe782031aca.png)
![2](https://user-images.githubusercontent.com/38418753/43355765-ce18e770-9294-11e8-936d-463a69e83b9b.png)
![3](https://user-images.githubusercontent.com/38418753/43355767-d102e760-9294-11e8-854b-c9c901f3949e.png)
![4](https://user-images.githubusercontent.com/38418753/43355768-d3347d6e-9294-11e8-9211-b0d7b9eb798f.png)

Steps to Reproduce:

1.As shown in Figure 1,  folding the code 
2.At the end of the 46 line，then enter
3.As shown in Figure 4, the result I expect.
4.But as shown in Figure 3, the final result.

**How can I achieve the results I am looking forward to?(Figure 4)**

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kieferrm** [comment]
Please file against the vue extension.
