### ISSUE TITLE
Can't set sidebar width to 0

### ISSUE THREAD

**Issue by lyyiangang** [Microsoft/vscode#55292]
see following picture
![image](https://user-images.githubusercontent.com/1982228/43354586-8627e4d8-9281-11e8-94b9-dfd26f356e4a.png)
I can't make the width A and B to be zero by dragging side bar. 
vscode version: 1.25.1

**Comment by kieferrm** [comment]
It seems to me that you are in centered layout mode.  Use `View: Toggle Centered Layout` from the command palette <kbd>F1</kbd> or from the `View` menu, submenu `Appearance`.
