### ISSUE TITLE
Launch.json fails to debug an npm script when running other CLI (wdio, webpack)

### ISSUE THREAD

**Issue by orenmizr** [microsoft/vscode#55293]
- VSCode Version: 1.25
- OS Version: window 10 

Steps to Reproduce:

1. add to package.json an npm script: 'debug: "wdio test.js"'
2. cofigure launch with npm script in lauch json

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
- How does your debug configuration looks like?
- the comma in "wdio test,js" seems to be a typo?

**Comment by orenmizr** [comment]
that was just my type here. my config works with the debugger runner but not npm: 

launch.json
```{
  "version": "0.2.0",
  "configurations": [{
      "type": "node",
      "request": "launch",
      "name": "WebdriverIO Debug",
      "runtimeExecutable": "npm",
      "protocol": "legacy",
      "program": "wdio",
      "windows": {
        "runtimeExecutable": "npm.cmd"
      },
      "runtimeArgs": [
        "run-script",
        "debug"
      ],
      "port": 5859,
      "cwd": "${workspaceRoot}",
      "console": "integratedTerminal",
      "address": "localhost"
    },
    {
      "type": "node",
      "request": "launch",
      "protocol": "legacy",
      "address": "localhost",
      "port": 5859,
      "timeout": 20000,
      "name": "WebdriverIO",
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/wdio",
      "windows": {
        "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/wdio.cmd"
      },
      "cwd": "${workspaceRoot}",
      "console": "integratedTerminal",
      // This args config runs only the file that's open and displayed
      // (e.g., a file in test/spec/):
      "args": [
        "--spec", "${relativeFile}"
        // To run a specific file, you can use:
        //"--spec", "test/specs/foo.spec.js"
      ]
    }
  ]
}

``` 

i use that port number because webdriver.io config has a setting field for debug port and that was is defined there. 

basically debug via npm script fails because of the extra step launch> npm -> wdio - > node

**Comment by orenmizr** [comment]
the programe attempt was a bad one :) what you've wrote is the original code from the template vscode... it after it fails to connect it on timoute, it says... "make sure you are running in legacy mode" so i replace the debug-brk to inspect trying the second protocol... then it throws a timeout error

**Comment by weinand** [comment]
Please reopen issue if you still see the problem.

**Comment by weinand** [comment]
Please reopen issue if you still see the problem.
