### ISSUE TITLE
Tall menus are not scrollable in the preview title bar.

### ISSUE THREAD

**Issue by utkumaden** [Microsoft/vscode#55290]
Issue Type: <b>Bug</b>

Get a device with a small resolution (like 1366x768) and set "window.titleBarStyle": "custom" in the settings. Menus such as the view menu will be too tall to fit in the window, with no scrolling. You can however use the arrow keys to select items not visible, which will temporarily shift the "viewport" down.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|5.91GB (1.74GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|0.3.6
latex-preview|ajs|0.5.1
code-gnu-global|aus|0.2.2
vscode-icontheme-nomo-dark|be5|1.3.6
vscode-glsllint|CAD|0.0.3
glsl-canvas|cir|0.1.91
xml|Dot|2.3.1
vscode-html-css|ecm|0.2.0
php-debug|fel|1.12.3
php-intellisense|fel|2.3.3
vscode-lua|gcc|0.1.2
gc-excelviewer|Gra|2.1.25
vscode-firefox-debug|hbe|1.4.3
latex-workshop|Jam|5.7.0
Lua|key|0.0.9
vscode-apache|mrm|1.1.1
cpptools|ms-|0.17.7
csharp|ms-|1.15.2
PowerShell|ms-|1.8.2
vs-keybindings|ms-|0.2.0
team|ms-|1.136.0
java|red|0.28.0
shader|sle|1.1.3
latex-support|tor|2.0.2
vscode-lua|tri|0.12.4
vscode-java-debug|vsc|0.10.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.7.1
vscode-maven|vsc|0.10.0

(1 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
@utkumaden We have made changes to the length of the view menu in insiders which helps with this issue.

Tracking in #52533
