### ISSUE TITLE
Poping stash without removing it

### ISSUE THREAD

**Issue by yarimiz** [Microsoft/vscode#55294]
Currently, when using the command Pop Stash (or recent stash), vscode applies the stash but immediately removes it without prompting or providing any flag to leave the stash file untouched.
This is unclear to the user and in some cases removing stashes you want to re-use.

I would like to see an option to apply a stash without removing it.

**Comment by joaomoreno** [comment]
That's what `git stash pop` does. You want `git stash apply`: #54204
