### ISSUE TITLE
Responsive Toolbar layout in Panel

### ISSUE THREAD

**Issue by SMotaal** [Microsoft/vscode#55300]
Moving the panel to the right has been very useful, especially after introducing the split terminal feature. One big drawback which is likely already considered by the team and was likely put off till after the initial implementation is having the toolbar redesigned so that the panels and tools could responsively span out into two rows if the width is too small.

The simplicity of the UI severely drops from this very simple feat.

Thanks.

**Comment by isidorn** [comment]
We already have some overflow behavior of the panel title area. I understand this currently does not work perfectly but a responsive toolbar layout only in the panel does not make sense. We would have to do it across the whole vscode and this is currently out of scope
