### ISSUE TITLE
Pylint errors

### ISSUE THREAD

**Issue by rizovictor** [Microsoft/vscode#55308]
Issue Type: <b>Bug</b>

Hello Everyone.
I am having some error messages everytime I open a file with VSC.
Messages like E0401, C0303 are shown even when eveything is woking good and I can run the project.

This gets anoying because I see all the time RED warnings of errors.

E0401:Unable to import 'django.db'",
C0303:Trailing whitespace

Like this messages I can have more and more.
I would like to have some guidance about how to fix this.

Thank you in advance.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     T6500  @ 2.10GHz (2 x 2095)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.91GB (1.43GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.7.1
atom-keybindings|ms-|3.0.4
team|ms-|1.136.0
python|tht|0.2.3

</details>

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-python/
