### ISSUE TITLE
visual studio code crashed and after restart now has large fonts for menu, window titles etc.

### ISSUE THREAD

**Issue by petegor** [Microsoft/vscode#55305]
I'm running RHEL 7.4 (Maipo) KDE Platform Version 4.14.8 and VSCode 1.25.1.
I had 2 instances of code running.
I clicked on File - Exit to close one of the instances and both windows collapsed. I'm thinking it crashed but don't know that for certain.
After launching vscode again, now my main menus are all using a really large font, as are all the file tab menus (see screenshot below).
Through Linux Application - System Settings - Application Appearance i'm able to affect the font size of vscode main window title (see screenshot), but it still has no effect on the menus.
How can i restore the smaller menu sizes?
Thank you.

Screenshots...

![image](https://user-images.githubusercontent.com/39388458/43358754-79aeda12-924b-11e8-94d6-260b779a5f19.png)

![image](https://user-images.githubusercontent.com/39388458/43358762-9b1d3824-924b-11e8-842b-1cc6b056f3fe.png)

**Comment by sbatten** [comment]
@petegor can you verify if this issue has been resolved for you?

**Comment by petegor** [comment]
I will endeavor to find out.

**Comment by sbatten** [comment]
@petegor thanks for the info, since all is resolved for you currently with regards to the fonts issue and this is on an outdated version of VS Code, I'd like to mark this as resolved for now. If you have the issue again on an updated version, please feel free to re-open.
