### ISSUE TITLE
Bug: A folded method also hides empty lines after it

### ISSUE THREAD

**Issue by lonix1** [Microsoft/vscode#55304]
- VSCode Version: 1.25.1
- OS Version: Ubuntu 18.04.1 LTS

Steps to Reproduce:

1. In a c# file
2. Fold a method
3. It will be folded, along with empty lines after it

Example before folding:

````csharp
public void foo() {
  // some code...
}
                               // this empty line will be hidden when folding "foo()"
                               // this empty line will be hidden when folding "foo()"
                               // this empty line will be hidden when folding "foo()"
                               // this empty line will be hidden when folding "foo()"
public string Bar { get; set; }
````

Example after folding:

````csharp
public void foo() { ...
public string Bar { get; set; }
````

I've marked this as a bug, rather than a request, because this is not how folding works with Visual Studio - which only folds code, not whitespace after it. And I assume you're aiming for parity with the IDEs, at least for c# anyway.

This is a really annoying problem, because when code is folded everything is buched up together and you can't visually separate between them - which is why you'd use empty lines between them.

**Comment by kieferrm** [comment]
I'm guessing you have the C# extension installed.

**Comment by lonix1** [comment]
@kieferrm I use c# yes. I don't understand - isn't this a problem with the IDE?

**Comment by kieferrm** [comment]
@lonix1 VS Code out of the box does not have any deep C# knowledge. If you have the C# extension installed, the C# extension provides VS Code with the knowledge about which ranges are folding ranges. Thus, the issue you describe is with the extension, not with VS Code proper.

**Comment by lonix1** [comment]
@kieferrm Thanks I get it now
