### ISSUE TITLE
Show project init errors

### ISSUE THREAD

**Issue by nrkn** [Microsoft/vscode#5530]
- VSCode Version: 1.0.0
- OS Version: Windows 10 Pro

I have no extensions installed. node.js v5.10.1

Error highlighting has stopped working in our node.js app - I was able to reduce it to a very minimal test case:

A single index.js containing an erroneous line so you can see if error highlighting is on
A single subfolder containing a package.json with grunt and grunt-browserify packages and a node_modules folder created by running npm install against the package.json
Standard vscode files - .vscode/launch.json and jsconfig.json

Steps to Reproduce:
1. [Clone this repo](https://github.com/nrkn/vscode-error-min/) or [recreate structure above from this gist](https://gist.github.com/nrkn/da6bde225b114d9b8d9f7cf66772c0c9)
2. Navigate to ./sub and run `npm install`
3. Open main folder in VSCode
4. View ./index.js - there is no error highlighting

I have reproduced this on 3 machines

Almost any change to this minimum case, like removing the node_modules folder, removing `use strict` from the index.js etc., removing the vscode files etc. prevents the bug from being triggered, and error highlighting starts working again, however our app is not a minimal test case so knowing that isn't much help to us!

**Comment by nrkn** [comment]
BTW, there are a ton of ways to fix the min case so that it works, like adding node_modules to the exclude in jsconfig.json - but none of these fixes helps in our full app. Am at quite the loss as to how to proceed. Please let me know if I can provide any more info.

**Comment by dbaeumer** [comment]
@nrkn thanks a lot for this nice test case. I was able to reproduce this immediately. First analysis shows that the tsserver which is powering JavaScript language smartness throws on reading the project info. We need to do two things here:

- let the user know that reading the project info failed.
- make a issue for the TS team.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#8212

**Comment by dbaeumer** [comment]
Reopening and moving to @jrieken: can you add code that informs the user that reading the project info for JS validation failed and why. This would allow users to report easier bugs. I also created https://github.com/Microsoft/vscode/issues/5532 to send telemetry events for failed requests.

**Comment by jrieken** [comment]
this became obsolete, the tsserver now sends events for this
