### ISSUE TITLE
Create ability to navigate to a referenced file by clicking the reference in a .ts or .html file

### ISSUE THREAD

**Issue by MarkPhillips** [Microsoft/vscode#55301]
WebStorm has ability to navigate to a file when clicking its reference in an .html or,ts file.  This feature is  a huge time saver and would be much appreciated.

**Comment by aeschli** [comment]
Can you paste a sample code that shows the kind of reference you mention?
We have `Goto declaration' in typescript and in HTML we have links for URL references.
