### ISSUE TITLE
菜单乱码

### ISSUE THREAD

**Issue by lantongxue** [Microsoft/vscode#55302]
- VSCode Version: 1.25.1
- OS Version: Deeping Linux 15.6  （4.15.0-21deepin-generic）

Steps to Reproduce:
1. "window.titleBarStyle": "custom",

![avatar](http://jindashen-1251139224.cosgz.myqcloud.com/%E6%B7%B1%E5%BA%A6%E6%88%AA%E5%9B%BE_code_20180728221610.png)

仅仅启用了中文语言包扩展

**Comment by rebornix** [comment]
The menu items are not rendered properly.

**Comment by sbatten** [comment]
This was an issue in 1.25.1 but has since been fixed.
