### ISSUE TITLE
Do not auto-close when ending with open autoClosingPair

### ISSUE THREAD

**Issue by MattHardcastle** [Microsoft/vscode#55314]
- VSCode Version: 1.25.1
- OS Version: Mac OS X 10.13.6 (17G65)

Steps to Reproduce:

1. Open new file
2. Set language mode to Python
3. type "marry had a little lamb" (w/o quote)
4. insert cursor anywhere in the string and type " (quote character)

Expected results:
* A quote character will be added

Actual result:
* Two quote characters are added

Does this issue occur when all extensions are disabled?: Yes

--- 

This bug happens with any line that ends in a character that starts an open autoClosingPair. It's especially prevalent in the Python language mode because Python has so many open autoClosingPairs that begin with a letter, but the bug will present itself in any language mode that has open autoClosingPairs similar to Python's.

**Comment by kieferrm** [comment]
Can't reproduce with a vanilla VS Code installation.

**Comment by MattHardcastle** [comment]
I'm happy to provide a gif of the issue:

![double-quote-issue](https://user-images.githubusercontent.com/10106755/43403854-0b1abd2e-93cb-11e8-827b-07a60125c879.gif)

I used version 1.26.0-insider in the gif:

<img width="283" alt="version-info" src="https://user-images.githubusercontent.com/10106755/43404039-6810d41e-93cb-11e8-878f-8776e23db5c4.png">

**Comment by kieferrm** [comment]
@MattHardcastle this is what I get in today's insider without any Python related extension.

![lcb8nydt8h](https://user-images.githubusercontent.com/4674940/43424383-1ce26532-9404-11e8-8a11-57b5802e7eb3.gif)

Based on your `gif` I assume you have a python extension installed. Please file the issue against the extension you use. Thanks a ton!

**Comment by MattHardcastle** [comment]
@kieferrm I'm reproducing the insider version of VSCode w/o any extensions installed. I believe you're failing to replicate the issue because you're not ending the string in the correct character. The bug will only present itself when a line ends in in r, u, f, or b.

The issue is caused by a bug in the way electricCharacters are recognized. It presents itself in the native Python extension because python has multi-character opening autoClosingPairs. For example `r"` opens a raw string in Python. VSCode is configured to recognize that and closes raw strings with a matching quote. The bug is that the opening character match is checking the end of a string instead of checking the cursor character backward for the open autoClosingPair.

I investigated this over the weekend and got a working fix in PR #55315.

**Comment by kieferrm** [comment]
@MattHardcastle got it now. Thanks for explaining.

**Comment by MattHardcastle** [comment]
No problem, @kieferrm. Thanks for reconsidering the issue.
