### ISSUE TITLE
Python syntax highlighting no longer works

### ISSUE THREAD

**Issue by JacobCallahan** [Microsoft/vscode#55318]
Issue Type: <b>Bug</b>

Syntax highlighting no longer works for python files. 
This has happened before and was resolved after disabling the python extension. However, this time disabling the extension did not bring back highlighting.
This could a conflict with python versions, as I just upgraded to python 3.7.

As I'm unsure of the cause, I cannot provide reproducer steps. This is on Fedora 28, with python 3.7 set as the system python version.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:40:20.190Z)
OS version: Linux x64 4.17.9-200.fc28.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|30.80GB (24.09GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
solargraph|cas|0.17.6
tslint|eg2|1.0.34
MagicPython|mag|1.0.12
python|ms-|2018.7.1
azure-account|ms-|0.4.2
vscode-docker|Pet|0.1.0
Ruby|reb|0.18.0
preview-vscode|sea|1.4.2
vscodeintellicode|Vis|1.0.1

(1 theme extensions excluded)

</details>

**Comment by JacobCallahan** [comment]
This is not a duplicate of those three issues, but thanks bot :)
Here is a screenshot of the issue.
![screenshot from 2018-07-28 21-38-49](https://user-images.githubusercontent.com/6618303/43362121-06e04d6c-92b0-11e8-8536-2c59c7624659.png)

**Comment by JacobCallahan** [comment]
@isidorn what extension? If you're going to close an issue, it would be helpful to explain why. In this case, what extension is causing the loss of highlighting?
Thanks

**Comment by isidorn** [comment]
Pyhton

**Comment by JacobCallahan** [comment]
@isidorn I'll assume you are referring to the MS Python extension and file the same issue against https://github.com/Microsoft/vscode-python

**Comment by isidorn** [comment]
Good asumption
