### ISSUE TITLE
Emmet fieldset only offers disabled options

### ISSUE THREAD

**Issue by itamark** [Microsoft/vscode#55317]
I know this was supposed to be solved from the previous ticket on this #48068 where @ramya-rao-a mentioned it had been fixed - however, it seems it's still happening.
Also, I know `fst` works in the meantime - just `fieldset` should, also.
Additionally - in the [Emmet cheat-cheet](https://docs.emmet.io/cheat-sheet/) it looks as if there's no regular fieldset option. However, it also looks like that for `button` for instance, and that works fine in vscode.

 

- VSCode Version: 1.26.0-insider
- OS Version: MacOS 10.12.6

Steps to Reproduce:

1. open HTML (in my case it was `template` tag in a `.vue` file)
2. begin typing `fieldset` - see options for `fieldset:d` and `fieldset:disabled`

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by ramya-rao-a** [comment]
It works as expected in an html file

![image](https://user-images.githubusercontent.com/16890566/43412739-01627caa-93e3-11e8-81e6-3913693f1143.png)


Emmet for vue files comes from the vetur extension (which I am guessing is what you are using). If so, then please log an issue for the vetur extension. It might be using an old version of the `vscode-emmet-helper` module.
