### ISSUE TITLE
Autoimport labels should differ between named and default imports.

### ISSUE THREAD

**Issue by ravshansbox** [Microsoft/vscode#55310]
![image](https://user-images.githubusercontent.com/1499188/43359792-84c360b8-92c2-11e8-8032-a6a05ac3957e.png)

**Comment by ravshansbox** [comment]
I propose following label from named imports:
`Import '{ Dashboard }' from module "./Dashboard"`

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#26089
