### ISSUE TITLE
Preserve editor group widths when moving groups left/right

### ISSUE THREAD

**Issue by axefrog** [Microsoft/vscode#55313]
- VSCode Version: 1.25.1, 1.26.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Open a bunch of tabs
2. Split a tab to make a group to the left or right
3. Resize the divider between the two groups
4. Move the active group to the left or right
5. Group widths are not maintained (group size should move with group)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
/cc @joaomoreno this may require some additional API on the grid widget for me to call. Currently I am doing this:
* `removeView` ([here](https://github.com/Microsoft/vscode/blob/5ddf33c7d3da6ccc2eb2ae3f6523f9efd376a41a/src/vs/workbench/browser/parts/editor/editorPart.ts#L672))
* `addView` ([here](https://github.com/Microsoft/vscode/blob/5ddf33c7d3da6ccc2eb2ae3f6523f9efd376a41a/src/vs/workbench/browser/parts/editor/editorPart.ts#L673))

If I had a method to move a view to a new location the widget could maybe preserve its sizes?
