### ISSUE TITLE
Improve tab order for search trough entire project

### ISSUE THREAD

**Issue by jasperkennis** [Microsoft/vscode#55312]
In atom, when you open the file search (cmd + shift + f) to search all files in the project, and press the tab button once to go to the field below it (which is the field that you use to say what type of files you want to search trough). In VSC you need to press tab several times to get to this field.

I get that this probably seems like a small thing, but as part of my flow I personally greatly appreciate it.

So my suggestion; after pressing cmd + shift + f, make the "search these files" field only a single press on tab away.

**Comment by roblourens** [comment]
I recommend using cmd+down/up for this, as we can't leave the buttons out of the tab order

**Comment by jasperkennis** [comment]
I was not aware of that shortcut, once my brain rewires I guess that will be just as effective, thanks!
