### ISSUE TITLE
'inDebugMode' context not working all the time?

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#55325]
I've had this keybinding forever,

```
{ "key": "f8", "command": "workbench.action.debug.continue",
        "when": "inDebugMode" },
```

but recently f8 always triggers 'go to next problem' even in debug mode, unless the editor isn't focused. I'm not sure how precedence is supposed to work when two keybindings both apply, maybe the keybindings are registered in a different order now. But I also noticed that 'debugState' and if I use `"when": "debugState != 'inactive'"` instead, it seems to work all the time?

**Comment by isidorn** [comment]
@roblourens good catch. I did some bad refactoring. Thanks
