### ISSUE TITLE
termial confict with conEmu, it load conEmu's starup script

### ISSUE THREAD

**Issue by deepkolos** [Microsoft/vscode#55321]
Issue Type: <b>Bug</b>

it is strange that the terimal in vsc will load conEmu's starpup script

and actually i hope vsc's termial can  display like below

![vscode termial conflict with conemu 4](https://user-images.githubusercontent.com/12824616/43362407-df3e1df4-931b-11e8-8c07-5fc3752a40a4.png)

![vscode termial conflict with conemu](https://user-images.githubusercontent.com/12824616/43362367-e60204b2-931a-11e8-87fa-c7092fab7408.png)

![vscode termial conflict with conemu 1](https://user-images.githubusercontent.com/12824616/43362368-e6441cee-931a-11e8-81bf-084db736fceb.png)

![vscode termial conflict with conemu 2](https://user-images.githubusercontent.com/12824616/43362369-e68a676c-931a-11e8-82c0-668b93b9a03e.png)

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (2.54GB free)|
|Process Argv|d:\Program files\Microsoft VS Code\Code.exe .|
|Screen Reader|no|
|VM|40%|

</details><details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
include-autocomplete|ajs|0.0.4
Bookmarks|ale|9.0.2
copy-relative-path|ale|0.0.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.59
vscode-svgviewer|css|1.4.4
vbscript|Dar|1.0.4
vue-peek|dar|1.0.2
vscode-eslint|dba|1.4.12
githistory|don|0.4.2
gitlens|eam|8.5.3
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.5.0
javac-linter|fau|1.3.1
php-debug|fel|1.12.3
php-intellisense|fel|2.3.3
php-pack|fel|1.0.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
matlab|Gim|0.9.0
npm-dependency-links|her|1.0.0
search-node-modules|jas|1.3.0
webpack|jer|2.1.0
node-module-intellisense|lei|1.5.0
VBScript|lug|0.0.2
vscode-clang|mit|0.2.2
vscode-attrs-sorter|mrm|2.1.0
vscode-language-pack-zh-hans|MS-|1.25.3
mssql|ms-|1.4.0
python|ms-|2018.7.1
cpptools|ms-|0.17.7
debugger-for-chrome|msj|4.8.2
vuejs-extension-pack|mub|1.1.2
makefiles-support-for-vscode|nae|0.0.3
vetur|oct|0.12.5
material-icon-theme|PKi|3.5.2
scheme|reb|0.0.2
npmsmartimporter|ref|3.0.0
vue-vscode-extensionpack|sdr|0.1.3
vue-vscode-snippets|sdr|1.3.0
code-settings-sync|Sha|3.0.0
vscode-nginx|sha|0.5.0
vscode-status-bar-format-toggle|tom|1.4.0
vscode-arduino|vsc|0.2.18
vscode-react-native|vsm|0.6.13
nodejs-extension-pack|wad|0.1.9
vscode-todo-highlight|way|1.0.4
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.7.0
map-replace-js|Yuk|0.1.0

(2 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
I'm not sure how to configure conemu's shell with the integrated terminal, There are instructions for cmder and cygwin on the website, let us know if you get it working and we might be able to add it to the website https://code.visualstudio.com/docs/editor/integrated-terminal#_can-i-use-cmders-shell-with-the-terminal-on-windows

**Comment by deepkolos** [comment]
@Tyriar that is what i need, thx~

**Comment by deepkolos** [comment]
@Tyriar it doesn't work in the ConEmu but i compare cmder' init.bat and conEmu's CmdInit.cmd

cmder use clink to decode `$E[1;32;40m$E[92m$P$E[90m`, so i do the same thing

```bat
@echo off

rem Followed by colored `Path`
set ConEmuPrompt1=$E[1;32;40m$E[92m$P$E[90m

rem Carriage return and `$` or `#`
if /I "%ConEmuPromptNL%" == "NO" (set ConEmuPrompt2=) else (set ConEmuPrompt2=$_)
rem Spare `$E[90m` was specially added because of GitShowBranch.cmd
if "%ConEmuIsAdmin%" == "ADMIN" (
  set ConEmuPrompt2=%ConEmuPrompt2%$E[90m#
) else (
  set ConEmuPrompt2=%ConEmuPrompt2%$E[90m$$
)

rem Finally reset color and add notify ConEmu about prompt input start coords
set ConEmuPrompt3=$E[m$S$E]9;12$E\

rem Set new prompt
PROMPT %ConEmuPrompt1%%ConEmuPrompt2%%ConEmuPrompt3%

:: Pick right version of clink
@if "%PROCESSOR_ARCHITECTURE%"=="x86" (
    set architecture=86
) else (
    set architecture=64
)
:: Run clink
@"%CMDER_ROOT%\ConEmu\clink\clink_x%architecture%.exe" inject --quiet --profile "%CMDER_ROOT%\ConEmu\clink\profile"

:clean
set ConEmuPrompt1=
set ConEmuPrompt2=
set ConEmuPrompt3=
```

cmder use lua script to decode the placehoder `{name}`, ConEmu use Cmd's way, but now is fine with me , thx again~

![vscode termial conflict with conemu 5](https://user-images.githubusercontent.com/12824616/43430747-18e74fda-949d-11e8-8b3e-1c659adcad88.png)
