### ISSUE TITLE
VSCode can use the wrong package manager

### ISSUE THREAD

**Issue by mikeymop** [Microsoft/vscode#55328]
I could not find references to how VSCode handles OS package management

- VSCode Version: 1.25.1
- OS Version: Fedora 28

Steps to Reproduce:
![screenshot from 2018-07-29 03-29-27](https://user-images.githubusercontent.com/4002969/43364137-7af25cae-92e2-11e8-9fed-c4d484678d6b.png)

1. Observe a request to install a support package
2. Click Yes/Install
3. Notice that VSCode wrongly assumes my distribution is using `apt` package manager.

Does this issue occur when all extensions are disabled?:
I dont think this is affected by the presence of extensions as the issue with the process is the *installation* of extensions.

I currently have no extensions installed, I have only modified editor fonts.

**Comment by kieferrm** [comment]
The notification in the screen shot comes from the Python extension. So, I'd assume you installed the Python extension at some point. The Python extension is also handling when you click the `Yes` button.
