### ISSUE TITLE
color black is missing in vscode terminal

### ISSUE THREAD

**Issue by gertcuykens** [Microsoft/vscode#55320]
try the following https://github.com/dvorka/hstr hh command in terminal

vscode 1.25.1 osx
![image](https://user-images.githubusercontent.com/863731/43362326-cc7df588-92e7-11e8-9544-79289c3bb4bb.png)

terminal osx
![image](https://user-images.githubusercontent.com/863731/43362329-df68aeea-92e7-11e8-94cc-a401bf138f43.png)

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/xtermjs/xterm.js/issues/1591
