### ISSUE TITLE
macOS: Can not paste into "issue reporter" input field.

### ISSUE THREAD

**Issue by satokaz** [Microsoft/vscode#55332]
Can not be pasted (⌘V) into Issue Reporter's Title and 'Steps to Reproduce' input field.
does not reproduce with vscode 1.25.1.

Issue Type: <b>Bug</b>

VS Code version: Code - Insiders 1.26.0-insider (dae69dbf00357ff8a3fe740a1f211d66b0b4681c, 2018-07-27T05:12:46.620Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (5.97GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron --disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled

**Comment by RMacfarlane** [comment]
I'm unable to repro this in the latest insiders (64c433bf2bd43c85d1bfe5753bb6fb90ff4be14a, 2018-07-30T05:11:25.700Z), can you check if you still see the problem in the latest version?

**Comment by satokaz** [comment]
Updated to the latest insiders.
I confirmed the expected behavior.

Thanks.

**Comment by RMacfarlane** [comment]
Great, thanks for verifying!
