### ISSUE TITLE
[Language extension] wordPattern does not support unicode character classes

### ISSUE THREAD

**Issue by lukas-lang** [Microsoft/vscode#55339]
- VSCode Version: 1.25.1
- OS Version: Windows 10, Spring Creators Update

Steps to Reproduce:

1. Create a language extension
2. Add a `wordPattern` entry to the language configuration file
3. Use POSIX brackets in the regex, such as `"[[:alpha:]$][[:alnum:]$]*"`

Note: The regex works fine in the side panel search, but not in the search widget.
According to #5708, at least some part of the regexes are parsed using the Oniguruma regex syntax, which [supports POSIX brackets](https://github.com/kkos/oniguruma/blob/ea86c22bfb9cb63c5b948e15b61e62389f292ace/doc/RE#L177).

If this is intended behavior, then I have two questions:

* Is there a way to find out which regex engine is used where? VSCode seems to use several different ones, with no clear indication as to which one is used where. [This page](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributeslanguages) for example only specifies "Regex".
* Is there a way to achieve something equivalent to the above regex for `wordPattern`?

**Comment by alexandrudima** [comment]
The word pattern is interpreted using JavaScript's regular expressions. This is a good page describing it - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp

The editor's find widget uses the same JavaScript regular expressions as the word pattern.

**Comment by lukas-lang** [comment]
@alexandrudima Thanks for the info! That's quite unfortunate, as it means there's no easy way to match classes like "all letters".
