### ISSUE TITLE
IPC could behave incorrectly for some message types

### ISSUE THREAD

**Issue by attilah** [Microsoft/vscode#55335]
While I reading through the source code I found this possible problem:

https://github.com/Microsoft/vscode/blob/master/src/vs/base/parts/ipc/common/ipc.ts#L27

And this function used in the ```onMessage``` method and can cause an immediate return for  ```RequestEventListen``, ```RequestEventDispose``` messages based on the ```MessageType``` enum at the top.

I found no use case in the code where it should fail, but IMHO the ```isResponse``` method implementation is not correct and can cause future hard to catch problems.

**Comment by joaomoreno** [comment]
Oh man that's BAD. Great eye!

**Comment by joaomoreno** [comment]
Verifier: please code review.
