### ISSUE TITLE
Adding indentation in SASS file

### ISSUE THREAD

**Issue by mittalyashu** [Microsoft/vscode#55330]
Issue Type: <b>Bug</b>

Not able to indent after collapsing the content in SASS file.
https://youtu.be/Vb2QvgUAIzA

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:11.471Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.78GB (0.65GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-languagetool|ada|3.8.0
vscode-languagetool-en|ada|3.8.0
Bookmarks|ale|9.0.2
vscode-open-file-folder|auc|0.0.4
emojisense|bie|0.4.1
rails|bun|0.8.0
vscode-gemfile|bun|0.0.2
gitlens|eam|8.5.3
EditorConfig|Edi|0.12.4
carbon-now-sh|eri|1.1.1
prettier-vscode|esb|1.5.0
code-runner|for|0.9.3
HTMLHint|mka|0.5.0
vscode-duplicate|mrm|1.2.1
atom-keybindings|ms-|3.0.4
vetur|oct|0.12.5
material-icon-theme|PKi|3.5.2
Ruby|reb|0.18.0
vscode-icons|rob|7.24.0
sass-indented|rob|1.4.9
guides|spy|0.9.2
code-spell-checker|str|1.6.10
vscode-import-cost|wix|2.8.0

(8 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
The folding strategy for SASS is based purely on the indentation of lines. A folding region starts when a line has a smaller indent than one or more following lines and ends when there is a line with the same or smaller indent.

To be smarter and to, for example, have folding regions for SASS rule, this would have to be done by a SASS extension that understands the SASS syntax.
Please file this request against your favorite SASS extension (We don't intend to work on SASS support ourselves)
