### ISSUE TITLE
Respect tsconfig files' include/exclude options

### ISSUE THREAD

**Issue by jack-bliss** [Microsoft/vscode#55333]
This is a duplicate of the closed, but unresolved, https://github.com/Microsoft/vscode/issues/3772.

I have a project which includes both front- and back-end typescript. I want to run my server code using ts-node, and bundle my client react code using webpack and awesome-typescript-loader. This is all works how I want it to, and I have set include and exclude to make sure that the correct parts of my projects are being covered. I have a tsconfig.client.json and a tsconfig.server.json, each with their own needs and concerns. What doesn't work, however, is intellisense. It would be nice to be able to mark files as using a specific tsconfig file, so that I can keep my config files in the root directory and have intellisense know what's going on. Even better would be if it would automatically detect which tsconfig to use, throwing an error only if a file is covered by multiple tsconfigs which are incompatible. At the moment, I've used the solution of having a 'dummy' tsconfig.json file which is configured purely for intellisense but I don't really like doing that. 

I appreciate that this isn't exactly a minor feature request. Is there any word on how prioritised this is by the team?

**Comment by mjbvz** [comment]
Please provide a small example project that demonstrates the problem.

Currently a file can only be part of a single tsconfig.json. Do you need some files to be part of multiple tsconfigs? Would [TypeScript 3 project references](https://www.typescriptlang.org/docs/handbook/project-references.html) help?
