### ISSUE TITLE
July Endgame

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode#55349]
- July 30th: Code freeze for the endgame
- August 3rd: Endgame done

> **Note:** The `Insiders` build needs to be in the wild for 24 hours before we can enter the last phase of the endgame.

> **Note:** Wednesday is a holiday for Zurich team and much of Zurich will be OOF throughout endgame.

##### Monday
- [x] Code freeze at 5pm PT
- [x] Ensure we have a green build on all platforms at 5pm PT
- [x] All test items contain sufficiently comprehensive test descriptions by 6pm PT
- Update your availability for testing here - https://vscode-tools.azurewebsites.net/

##### Tuesday
- [x] [Test Plan Items Assigned](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+label%3Atestplan-item+milestone%3A%22July+2018%22)
- [x] All closed feature-requests either have a verification-needed or on-testplan tag
- [x] Test build starts at 7am CET / 10pm PT on Monday
- [x] Test plan ready by 8am CET / 11pm PT on Monday
- [x] Testing
- [x] [Verification needed](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+-label%3Averified+is%3Aclosed+label%3Averification-needed)
- [x] Run [OSS tool](https://github.com/Microsoft/vscode-distro/blob/master/distro-tools/README.md) **endgame master**
  - *The LCA review of the ThirdPartyNotices.txt files is not needed anymore*

##### Wednesday
> **Note:** Holiday for Zurich
- [x] Testing
- [x] Remind team members to assign issues that they intend to fix to the current milestone
- [x] Fixing (self-assigned, milestone assigned)
- [x] [Verification](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+label%3Abug+-label%3Averified+-label%3Aon-testplan+is%3Aclosed+-label%3Aerror-telemetry+-label%3Aduplicate+-label%3A*duplicate+-label%3Ainvalid+-label%3Aas-designed+milestone%3A%22July+2018%22)

##### Thursday
- [x] Fixing (scrutiny sets in - major bugs only - to be discussed in stand-up meeting, labeled as `candidate`)
- [x] [Verification](https://github.com/Microsoft/vscode/wiki/Issue-Tracking#verification)
- [x] Check new OSS usage is entered into the [OSS registry](https://ossmsft.visualstudio.com/_apps/hub/ms.vss-oss-web.hub-oss) Product: Visual Studio Code  **@sbatten** **@isidorn**

##### Friday
- [x] Pause scheduled `insider` builds **endgame master**
- Satellite modules/npm packages ready, version updated, smoke tested
  - [ ] vscode **@bpasero**
  - [x] yo generator **@aeschli**
  - [x] vsce **@joaomoreno**
  - [x] node debug **@weinand**
  - [x] node debug2 **@roblourens**
  - [x] node debugadapter node **@weinand**
- [x] All issues [verified](https://github.com/Microsoft/vscode/wiki/Issue-Tracking#verification)
- [x] Fixing (only critical bugs - no string changes)
- [Smoketest](https://github.com/Microsoft/vscode/wiki/Smoke-Test)
  - [x] Windows - @ramya-rao-a 
  - [x] macOS - @roblourens 
  - [x] Linux - @RMacfarlane 
- All release notes updated - release notes are collected in a file named [*`v1_26.md`*](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_26.md) in this [repo directory](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/). This includes new features and notable fixes.
  - [x] @aeschli
  - [x] @alexandrudima
  - [x] @bpasero
  - [x] @chrmarti
  - [x] @dbaeumer
  - [ ] @egamma
  - [x] @isidorn
  - [x] @joaomoreno
  - [x] @jrieken
  - [x] @kieferrm
  - [ ] @mjbvz
  - [ ] @octref
  - [ ] @ramya-rao-a
  - [ ] @rebornix 
  - [x] @rmacfarlane
  - [x] @roblourens
  - [ ] @sandy081
  - [x] @sbatten
  - [ ] @tyriar
  - [x] @weinand
- [ ] Acknowledge pull requests in release notes. We acknowledge PRs from outside the team. Use the [thankyou](https://vscode-tools.azurewebsites.net/#acknowledgePRs) tool to generate the initial contents of the section. **endgame master**
  - [x] vscode **endgame master**
  - [x] vscode-node-debug **@weinand**
  - [x] vscode-node-debug2 **@roblourens**
  - [x] vscode-debugadapter-node **@weinand**
  - [x] vscode-languageserver-node **@aeschli**
  - [x] language-server-protocol **@aeschli**
  - [x] vscode-textmate **@alexandrudima**
  - [x] vscode-loader **@alexandrudima**
  - [x] vscode-generator-code **@aeschli**
  - [x] vscode-vsce **@joaomoreno**
  - [ ] vscode-docs **@gregvanl**
  - [x] vscode-css-languageservice **@aeschli**
  - [x] vscode-json-languageservice **@aeschli**
  - [x] vscode-html-languageservice **@aeschli**
  - [x] jsonc-parser **@aeschli**
  - [x] vscode-jscs **@chrisdias**
  - [ ] vscode-tslint **@egamma**
  - [x] vscode-eslint **@dbaeumer**
  - [x] vscode-jshint **@rmacfarlane**
  - [x] vscode-recipes **@auchenberg**
  - [x] localization **@danyeh**
  - [x] vscode-github-issues-prs **@chrmarti**
- [x] Add notable fixes to the release notes **@all**
- When done fixing/verifying and there are changes since last build at the end of day PT
  - [x] Trigger new insider build and publish it manually **endgame master**

##### Friday/Monday
- [x] Branch code to `release/<x.y> **endgame master**
- [x] Bump up the version in package.json - **endgame master**
- [x] Announce master is open for business **endgame master**
- [x] Let Daniel Ye know that the release branch `release/<x.y>` got created and that translation should be pulled from there and that the pull request has to be created against that branch **endgame master**
- [x] Polish release notes **@redmond**

##### Monday - Wednesday
- [x] Polish release notes **@redmond**
- [x] Cherry-pick hand-picked and reviewed changes to `release/<x.y>` **@endgame master**
- [x] Build `Insider` from `release/<x.y>` **@endgame master**
- [x] Manually release `Insider` **@endgame master**
- [ ] Documentation updated
  - [x] @aeschli
  - [x] @alexandrudima
  - [x] @bpasero
  - [x] @chrmarti
  - [x] @dbaeumer
  - [ ] @egamma
  - [x] @isidorn
  - [x] @joaomoreno
  - [x] @jrieken
  - [x] @kieferrm
  - [ ] @mjbvz
  - [ ] @octref
  - [ ] @ramya-rao-a
  - [ ] @rebornix 
  - [x] @rmacfarlane
  - [ ] @roblourens
  - [ ] @sandy081
  - [ ] @tyriar
  - [x] @weinand

> **Note:** The `Insiders` build needs to be in the wild for 24 hours before we can enter the last phase of the endgame.

##### Wednesday/Thursday
- [ ] Check translations (check `i18n` folder git history for latest translations, then build locally and see the amount of untranslated strings) **@zurich**
- [x] Build stable for all platforms **endgame master**
- [x] Add a git tag to `HEAD` of `release/<x.y>` in format `x.y.z` (for vscode.d.ts download)  **endgame master**
- [ ] Make sure that the [vsda module](https://github.com/Microsoft/vscode-distro/tree/master/quality/stable/node_modules/vsda) version in stable is the same as in insiders (which matches the latest electron)
- [x] Make [rpm signing request](https://github.com/Microsoft/vscode-distro/blob/master/linux-repo/README.md) **@Tyriar**
- [x] Sanity check of installable bits
  - [x] Windows
    - [x] signed installer 32-bit @ramya-rao-a
    - [x] signed installer 64-bit @ramya-rao-a
    - [x] signed user installer 32-bit @kieferrm
    - [x] signed user installer 64-bit @kieferrm
    - [x] zip 32-bit @kieferrm
    - [x] zip 64-bit @kieferrm
  - [x] macOS - @octref
  - [x] Linux
    - [x] deb package 32-bit @sbatten
    - [x] deb package 64-bit @sbatten
    - [x] rpm package 64-bit @RMacfarlane
    - [x] rpm package 32-bit @RMacfarlane
    - [x] archives @sbatten
- [x] Publish website **@gregvanl**
- [x] Publish to stable **endgame master**
- [x] Publish deb and rpms to repositories manually **@Tyriar**
- [ ] Add version with symbols to HockeyApp **@Tyriar**
- [x] Enable scheduled `insider` builds **endgame master**
- [x] Twitter announcement **@seanmcbreen**

**Comment by endgame** [comment]
Ha, github has subscribed me to your endgame plan. Awkward...

**Comment by ex1st** [comment]
> All release notes updated - release notes are collected in a file named [v1_26.md](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_25.md)

Seems link is wrong.

**Comment by paterasMSFT** [comment]
Any updates here? Excited for 1.26!

**Comment by Tyriar** [comment]
@paterasMSFT we're aiming to go out early next week

**Comment by jens1o** [comment]
Why this release is delayed?

**Comment by Tyriar** [comment]
@jens1o to allow more time for stabilization.
