### ISSUE TITLE
 Process is terminated due to StackOverflowException.

### ISSUE THREAD

**Issue by Firmbyte** [Microsoft/vscode#55341]
Issue Type: <b>Bug</b>

Everytime I open Visual Studio Code, the Powershell teminal crashes with the error: 
PS C:\CODE>
Process is terminated due to StackOverflowException.

In WinOS App log is this:
Faulting application name: powershell.exe, version: 10.0.16299.15, time stamp: 0xfdd02487
Faulting module name: System.Management.Automation.ni.dll, version: 10.0.16299.547, time stamp: 0xb298aca5
Exception code: 0xc00000fd
Fault offset: 0x000000000122e4bc
Faulting process id: 0x40f4
Faulting application start time: 0x01d42766a7b445e1
Faulting application path: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
Faulting module path: C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System.Manaa57fc8cc#\25f2d9efd1913f09bb16dbadd307b8e8\System.Management.Automation.ni.dll
Report Id: 12c738e9-893a-48b1-9593-b388c8a46e41
Faulting package full name: 
Faulting package-relative application ID: 

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Memory (System)|23.41GB (10.89GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|33%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
mssql|ms-|1.4.0
PowerShell|ms-|1.8.2
team|ms-|1.136.0

</details>

**Comment by Tyriar** [comment]
https://github.com/PowerShell/vscode-powershell
