### ISSUE TITLE
"Could not identify extension for 'vscode' require call" false positive

### ISSUE THREAD

**Issue by Gama11** [Microsoft/vscode#55340]
Issue Type: <b>Bug</b>

VS Code version: Code - Insiders 1.26.0-insider (dae69dbf00357ff8a3fe740a1f211d66b0b4681c, 2018-07-27T05:17:55.890Z)
OS version: Windows_NT x64 10.0.17134

In current Insider's builds, I'm seeing this output in the dev console. I'm not getting that output with 1.25.1.

![](https://i.imgur.com/zWzhdeH.png)

#53295, in particular this comment by @jrieken seems relevant: https://github.com/Microsoft/vscode/issues/53295#issuecomment-401741351

From the description there, it sounds like VSCode assumes that the extension path must be within `.vscode-insiders\extensions`. In my case, that is actually a symlink to `.vscode\extensions` to allow me to easily switch between Insider's and release builds, so the warning seems like a false positive.

**Comment by jrieken** [comment]
That's really weird... Both ends, the file that requires `vscode` and the index use the same paths, e.g. `...\.vscode\extensions\...` so it should really be found. @Gama11 This is windows, right? How did you create sym link?

**Comment by Gama11** [comment]
Using the [`mklink /D` command](https://superuser.com/a/1020825/365386).

**Comment by jrieken** [comment]
@Gama11 Trying to reproduce this but wasn't successful - neither on windows nor on macOS. Do you still see this issue with latest insider?

**Comment by Gama11** [comment]
Yes, I do (with the build from 42ffc0e)... Did you also have the Project Manager extension installed when trying to reproduce?

**Comment by jrieken** [comment]
Yeah, tried on windows with the mklink command and that extension...

**Comment by Gama11** [comment]
Just double-checked, there are no other custom extensions required to reproduce. So with only Project Manager installed, the error looks like this:

![](https://i.imgur.com/Uk2vxCY.png)

My symlinked `.vscode-insiders/extensions` folder looks like this:

![](https://i.imgur.com/m9S5wqX.png)

**Comment by jrieken** [comment]
I can finally reproduce 👯‍♂️
