### ISSUE TITLE
List of Errors Are Not Cleared When I close SQL File

### ISSUE THREAD

**Issue by lyndonjohn** [Microsoft/vscode#55345]
Issue Type: <b>Bug</b>

1. I have an sql file generated from sequelpro. 
2. Saved that file in my workspace.
3. Open file from my workspace.
4. Errors appear in status bar and integrated terminal.
5. I closed the file, but the errors are still there.

![screen shot 2018-07-30 at 8 30 39 am](https://user-images.githubusercontent.com/29518229/43372385-e6bd74d2-93d2-11e8-89cf-fa8d6c2bc242.png)

VS Code version: Code - Insiders 1.26.0-insider (dae69dbf00357ff8a3fe740a1f211d66b0b4681c, 2018-07-27T05:12:46.620Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.0.2
gitlens|eam|8.5.3
vsc-material-theme|Equ|2.3.0
php-intellisense|fel|2.3.3
beautify|Hoo|1.3.2
path-autocomplete|ion|1.12.0
vscode-insertdatestring|jsy|2.2.2
vscode-phpfmt|kok|1.0.30
mssql|ms-|1.4.0
es6-css-minify|olb|2.0.3
selectline-statusbar|tom|0.0.2
html-css-class-completion|Zig|1.17.1

</details>

**Comment by sandy081** [comment]
This could be because, the extension (mssql I assume) is not clearing the diagnostics when file is closed. Please file an issue against the corresponding extension.

**Comment by lyndonjohn** [comment]
@sandy081 Yes, you are right. It's mssql extension not clearing the errors. Thanks.
