### ISSUE TITLE
Auto Complete Does Not Recognioze Object Properties

### ISSUE THREAD

**Issue by idstef** [Microsoft/vscode#5534]
- VSCode Version: 1.0.0
- OS Version: Ubuntu 14.04

Steps to Reproduce:
1. Define object with full namespace and meta-tags
   ![screenshot from 2016-04-20 10 08 04](https://cloud.githubusercontent.com/assets/10683550/14667654/91a5fed2-06e0-11e6-8e8f-fdc7fa09c9ac.png)
2. Press ctrl+space and there are no suggestions for object properties / methods. Also, auto-complete did not give any suggestion on namespaces.

**Comment by dbaeumer** [comment]
@roblourens assigning to you as the new PHP owner. Feel free to close if this is not handle by the PHP extension.

**Comment by roblourens** [comment]
VS Code doesn't have complete support for this out of the box, but you can try one of the PHP extensions that now offer this.
