### ISSUE TITLE
Breakpoint/StepIn/StepOver doesn't work properly in VS Code for Typescript

### ISSUE THREAD

**Issue by bhawnablogs** [Microsoft/vscode#55351]
I am writing protractor tests for one application. To enable debugging, I have created a launch.json file and added various parameters. Now while running tests breakpoints are getting hit but breakpoints are not working properly.

Say that I have kept Breakpoint on line 27 and 32. When I press F5, I expect it go to 27 but either it goes to line no 32 or somewhere else sometimes out of code brackets also.
If press F10 : sometimes goes to next line sometimes goes anywhere else
If I press F11 : never goes inside the function
If I hover over variable : No information. Even in watch it shows undefined.
I have checked target in config file, it is pointing to es6 itself. Please suggest.

VS Code version : 1.22.2
Node Version : 8.10
Language : Typescript
System  Info: Windows 10

**Comment by isidorn** [comment]
VSCode 1.22 is an old version, please try with latest vscode.
If you can still repro please write here reproducable steps so we can investigate the issue on our end.
Repro steps means a program for which you see this invalid behavior
