### ISSUE TITLE
VS Code does not ask for passphrase

### ISSUE THREAD

**Issue by Mourdraug** [Microsoft/vscode#55352]
Issue Type: <b>Bug</b>

I have my encrypted ssh key in `~/.ssh/id_rsa`, pretty much default setup. When I try to push/pull instead of some passphrase dialog I get `Permission denied (public key)`. Code is the only app that has problems with this. It works without problem in Eclipse and Atom. Git from terminal also just prompts `Enter passphrase for key`. The only way to make it work is obviously starting both ssh-agent manually and code from terminal which is just inconvinient to do every time I start it, or just use git from terminal (which is my workaround so far).

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (2.55GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.34
python|ms-|2018.7.1
csharp|ms-|1.15.2
Go|ms-|0.6.85

</details>

**Comment by Mourdraug** [comment]
Atom:
https://puu.sh/B7qHY/57f3c89f47.png

Eclipse(Oxygen 3A):
https://puu.sh/B7qOt/a6b3848be0.png

**Comment by joaomoreno** [comment]
Got it.

/duplicate 13680
