### ISSUE TITLE
Language Code Detection

### ISSUE THREAD

**Issue by Souren09** [Microsoft/vscode#5535]
- VSCode Version:1.0.0
- OS Version: windows10.0.10586

Steps to Reproduce:

1. Open file with language code GB2312
2. Detected code is UTF-8.

**Comment by bpasero** [comment]
Duplicate of #5388

**Comment by Hyperdingo** [comment]
This setting has been added: **files.autoGuessEncoding**

Will hopefully be true as default soon; https://github.com/Microsoft/vscode/issues/23417
