### ISSUE TITLE
VS wil stop responding after adding  "\" in long string.

### ISSUE THREAD

**Issue by ChayMartis** [Microsoft/vscode#55356]
Adding a backslash inside a long string will crash Visual studio code

Example: 
        $pdf->Cell(24, 0, $pdf->Write(0,
        'huhrgtadfgggggggffffffffffffff 'Add backslash here' ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        huhrgtadfgggggggffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        huhrgtadfgggggggffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
        huhrgtadfgggggggffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff'
        ), 0, 0);

**Comment by isidorn** [comment]
What file type is that? Can you repro with vscode insiders https://code.visualstudio.com/insiders/

**Comment by ChayMartis** [comment]
Hi Isidorn, 

I'm sorry for the late reply, I don't check my spam emails that often.

- File type = PHP

I'm also having the same issue in the insider build and it happens only when the string is indent. (Check recorded steps). 


Recorded steps:
[VS Crash when adding backslash.zip](https://github.com/Microsoft/vscode/files/2269583/VS.Crash.when.adding.backslash.zip)
