### ISSUE TITLE
The Typescript language service died 5 times

### ISSUE THREAD

**Issue by pronebird** [Microsoft/vscode#55361]
- VSCode Version: 1.25.1
- OS Version: macOS 10.13.6

Dupe of https://github.com/Microsoft/vscode/issues/43103

TS Just keeps dying. God knows why.

<img width="458" alt="screenshot 2018-07-30 13 07 56" src="https://user-images.githubusercontent.com/704044/43394142-fb8e6142-93f9-11e8-88e4-c6c69ea054fe.png">

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Please try collecting the TS Server log:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a folder with a `tsserver.log` file in it

Look through that log file for errors or stack traces. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this
