### ISSUE TITLE
Search ripgrep settings confusion

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#55369]
While going throug my settings sweep I noticed that:

1. We have `searchRipgrep.enable` and `search.useRipgrep`. Why do we have two settings which seem to do the same thing?
2. searchRipgrep.enable from a naming standpoint does not make sense, it should be search.ripgrepEnable
3. Nowhere is it explained what is ripgrep and what effect does turning this on have

**Comment by roblourens** [comment]
`searchRipgrep.enable` is a temporary setting which enables the `search-rg` extension. Otherwise, the old search service is used (still with ripgrep).

**Comment by isidorn** [comment]
My point 3. still holds, so I suggest to keep this issue open.

**Comment by roblourens** [comment]
I think the real solution will be deleting the non-ripgrep search.

**Comment by isidorn** [comment]
@roblourens agree, that would be the best.

**Comment by nmsmith22389** [comment]
I'm still kind of confused if anyone could help clarify...

What's the difference between the search-rg extension and the regular ripgrep functionality?
<sup>*(or old vs new ripgrep?)*</sup>

I'm also partially against deleting the non-ripgrep searching for the following reasons:
- The *"in file"* search doesn't use ripgrep.
- Rip-grep doesn't support advanced RegEx features. <sup>*(at least not in the implemented form)*</sup>
- I prefer added functionality over a second or two difference in speed. <sup>*(and I doubt I'm the only one)*</sup>

**Comment by roblourens** [comment]
`search.useRipgrep` is deprecated, replace by `search.useLegacySearch`
