### ISSUE TITLE
Emmet doesn't work with pasted data

### ISSUE THREAD

**Issue by web2033** [Microsoft/vscode#55362]
- VSCode Version: 1.25.1
- OS Version: Win10

Steps to Reproduce:

1. Type a#
2. Paste snippet that contains future id (example - "future-link")
3. Hit "tab"
4. Emmet doesn't work in this case.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by ramya-rao-a** [comment]
Please see [Using tab for emmet expansions](https://code.visualstudio.com/docs/editor/emmet#_using-tab-for-emmet-expansions)
