### ISSUE TITLE
Allow user to remove individual items from recent projects list

### ISSUE THREAD

**Issue by ravshansbox** [Microsoft/vscode#55367]

**Comment by sbatten** [comment]
Hi @ravshansbox, could you please provide a description for this issue? Thanks for your feedback.

**Comment by ravshansbox** [comment]
Sometimes there are too much items in "recent project list" and one may need to clean up a bit unused/unnecessary ones. It seems possible to remove from recent, but that requires project folder be deleted from filesystem. I think we should provide `remove` button for each project in recent.

**Comment by bpasero** [comment]
That is possible from the "Recently opened" picker (File > Open Recent > More...):

![image](https://user-images.githubusercontent.com/900690/43726003-490f233a-999e-11e8-8678-04564b1f8df4.png)

**Comment by ravshansbox** [comment]
Ough, great. Thanks a lot!
