### ISSUE TITLE
Emmet attribute expansion not working as expected for HAML

### ISSUE THREAD

**Issue by asaadmahmood** [Microsoft/vscode#55366]
- VSCode Version: Version 1.25.1 (1.25.1)
- OS Version: 10.13.3 (Mac)

Steps to Reproduce:
1. Type `body[data="class"]`.
2. Expand it. 
3. It exapnds to: `%body(data="class")` instead of `%body{data => "class"}

Any way to fix this? Emmet works fine for basic expansion in haml such as `ul>li*5` but not for multiple attributes.

**Comment by ramya-rao-a** [comment]
Please share the below information:
- What extension are you using for haml? By default haml files are treated as plain text (See the bottom right corner). For them to get identified as haml, you must have had some extension.
- What are your emmet related settings

**Comment by asaadmahmood** [comment]
Using Better haml.
https://marketplace.visualstudio.com/items?itemName=karunamurti.haml
Do let me know if you prefer any other extension.
Also, how do I check my emmet related settings?

**Comment by ramya-rao-a** [comment]
Thanks @asaadmahmood 

This is an upstream issue with emmet itself. You can see the [tests](https://github.com/emmetio/markup-formatters/blob/186f60929bef76b90329648d45df1dd60fdaada3/test/haml.js) for haml abbreviations using () instead of {}

I have logged https://github.com/emmetio/html-transform/issues/18 to track this.

**Comment by asaadmahmood** [comment]
Okay cool, thanks a lot 👍

**Comment by sergeche** [comment]
According to [HAML docs](http://haml.info/docs/yardoc/file.REFERENCE.html#html-style-attributes-), `%body(data="class")` is a valid HAML instruction.

**Comment by asaadmahmood** [comment]
Oh cool, I didn't know that, though as pointed out, more complicated expressions aren't allowed in that syntax, so it would be better if we can switch towards a more lucrative one.

**Comment by asaadmahmood** [comment]
Cool, atleast we know that the basics work.
