### ISSUE TITLE
How to enable / disable extension from CLI

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#55363]
Can we get feature like 
1. Disable some extension via CLI
2. Get all the disabled / enabled extension list via CLI

I have opened similar issue via API ( https://github.com/Microsoft/vscode/issues/15466 )
As extension installing / uninstalling via API not supported yet ( https://github.com/Microsoft/vscode/issues/14444 ) and CLI is supported for now, so it would be great if you can support those things and **complete the extension management via CLI**

**In Settings Sync** , currently im using custom requests for download and install extension as API doesnt provide ways to perform functions, i'm looking forward to change to CLI based extension installation / uninstall.

**Comment by ramya-rao-a** [comment]
This is covered in #37620. Please update/upvote that issue
