### ISSUE TITLE
Javascript Suggestions include TypeScript Lint, even though they are disabled

### ISSUE THREAD

**Issue by IonCaza** [Microsoft/vscode#55371]
- VSCode Version: 1.25.1
- OS Version: macOS High Sierra 10.13.6

Steps to Reproduce:

1. ESLint is configured, TSLint is not installed
![image](https://user-images.githubusercontent.com/1081534/43404259-09b16748-93e5-11e8-819d-bcb9af6dba83.png)

2. Workspace settings are the following:
```
{
    "tslint.jsEnable": false,
    "tslint.exclude": ["**/*.js"],
    "typescript.validate.enable": false
}
```

3. Here are the plugins installed
![image](https://user-images.githubusercontent.com/1081534/43404406-6c1a5e3a-93e5-11e8-8962-6e38f857834c.png)

Does this issue occur when all extensions are disabled?: Yes, the problem still occurs.

Can someone please help me understand why I can't disable [ts] recommendations? I still need ESLint ones so disabling all javascript recommendations isn't an option.

**Comment by mjbvz** [comment]
Set `"javascript.validate.enable": false`

**Comment by tarol** [comment]
why not typescript.validate.enable
