### ISSUE TITLE
Unable to open two windows to the same folder

### ISSUE THREAD

**Issue by MashaMSFT** [Microsoft/vscode#55378]
I just updated my VS Code and now I am no longer able to open two windows to the same folder. When I already have a folder open in on VS Code window, I go to New window > Open Folder > Select same folder as other window >> nothing happens. Additionally, I can no longer use "code ." in git bash to open a new vs code window to the same folder. This is a pretty annoying issue and completely disrupts my workflow.

**Comment by isidorn** [comment]
@MashaMSFT I was not aware this was ever possible due to that we have F1 > duplicate workspace command.
Assigning to @aeschli and @sandy081 to check if something broke here

**Comment by MashaMSFT** [comment]
@isidorn, i didn't know this was an option :) i tried it and it works.. and now you have me questioning myself if this has ever worked this way. I'm fairly positive it has but now have no way to verify! :)

**Comment by isidorn** [comment]
@MashaMSFT we have, just download an older version of vscode 
Modify this uri as what suits your use case
https://vscode-update.azurewebsites.net/1.25.1/win32/stable

**Comment by MashaMSFT** [comment]
@isidorn, does this mean my only recourse from now on is to use an older version, or is this something that may change back in a future release?

**Comment by weinand** [comment]
VS Code did not support to open a folder in two windows.
Please follow the discussion in https://github.com/Microsoft/vscode/issues/2686
