### ISSUE TITLE
fontFamily not always working (at least with one specific font)

### ISSUE THREAD

**Issue by rbanffy** [Microsoft/vscode#5537]
- VSCode Version: 1.0.0
- OS Version: OSX 10.11.4

Steps to Reproduce:

1. Download and install IBM 3270 font (https://github.com/rbanffy/3270font/, installing from ZIP file is fine)
2. Edit your settings file to have "editor.fontFamily" set to "IBM 3270"
3. Save the file
4. Font setting does not quite catch: to see the weirdness, change it to "Monaco", then to "IBM 3270", then to "Arial Narrow" (wanted to check if spaces in the name could be related), then back to "IBM 3270" and you get something without serifs and monospaced that's not quite the default font. Set it to an empty string to bring sanity back (with a less cool font, that is 😉 ). Change it to an arbitrary name that's not an installed font and it'll change to a serif proportional spaced thing that looks like Times and is probably the default system font for body text.

**Comment by vvekic** [comment]
I've tried to reproduce, and detected additional weirdness:

In step 4, when switching back to 'IBM 3270", I didn't get the serif-monospaced thing, instead, the font remained the same (Arial Narrow), only the entire editor shifted right by a few pixels. The font then doesn't change no matter what you put as the font family, as long as it has at least 2 words, the first being "IBM", e.g. "IBM 3270xzy", "IBM xzy", "IBM one two three". If you put in "IBM" (or any other non existing font). Great weirdness indeed.

This is in no way related to Arial Narrow - it behaves the same whatever the previous font was.

**Comment by rbanffy** [comment]
- VSCode Version: 1.0.0
- OS Version: Ubuntu 15.10

Unsurprisingly (it was very unlikely to be platform-specific), the problem exists on Ubuntu too.

**Comment by rbanffy** [comment]
Tested on 1.5.1 on OSX and it still presents the same issue (not quite as bad as before - it reverts to a less ugly font).

**Comment by alexandrudima** [comment]
@rbanffy @vvekic What works for me is to set it to:

`"editor.fontFamily": "'IBM 3270'"`

The reason we don't auto-wrap the font family in quotes on our side is because you can actually specify a list in there (in case symbols are missing). e.g.:

`"editor.fontFamily": "'IBM 3270', Arial"`

![image](https://cloud.githubusercontent.com/assets/5047891/18436523/1afc151a-78f9-11e6-92e6-965fe9aa081c.png)

**Comment by rbanffy** [comment]
Worked perfectly.

**Comment by wilrnh** [comment]
This issue should've been resolved with updating the comment above that line
