### ISSUE TITLE
sidebar option to always show `staged changes` label

### ISSUE THREAD

**Issue by flpwgr** [Microsoft/vscode#55376]
Whenever you are working with the side bar, after you stage the first file the whole list jumps down, causing some confusion with the line positioning of the files.

Sample:
![problem](https://thumbs.gfycat.com/FlamboyantBothJuliabutterfly-size_restricted.gif)

If we always display the staged changes (or a option to do so) would be great :)

**Comment by VighneshKSP** [comment]
@joaomoreno I would like to help on this item

**Comment by isidorn** [comment]
I actually like the behavior with the new settings and will keep that.
Works nice -> verified
