### ISSUE TITLE
Quick open file "search" not finding files

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#55377]
Issue Type: <b>Bug</b>

I think it might be multi-root workspace related, but lately I've been finding that the quick open file search isn't finding matching files (even exact matches including case). It seems like it can't find files in certain workspace folders (but not all of them), but if I open a file from that workspace, it can then find that file, but still not others.

Another thing I've noticed (and may or may not be related) is moved/renamed/deleted files still show up in the quick pick open too

I also believe this is new in 1.26

VS Code version: Code - Insiders 1.26.0-insider (64c433bf2bd43c85d1bfe5753bb6fb90ff4be14a, 2018-07-30T05:19:32.584Z)
OS version: Windows_NT x64 10.0.17723

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (17.14GB free)|
|Process Argv|C:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by roblourens** [comment]
Is it a consistent set of files that get missed, or a random set at different times? You don't have `"searchRipgrep.enable"` set to true, right?

> Another thing I've noticed (and may or may not be related) is moved/renamed/deleted files still show up in the quick pick open too

Assuming these were previously open and show up under "Recently opened", this is a longstanding issue.

**Comment by eamodio** [comment]
Nope don't have `"searchRipgrep.enable"` (or any other specific search related settings). It seems consistent -- in the workspace I have open, I have 3 folders, and it is always the 3rd on that doesn't show up. I am also sometimes seeing results in triplicate too. 

For example, I was searching for `models.ts` (by typing exactly that) and I know that exists in the 1st and 2nd workspace folders I have open. But the search shows 3 matches for it, and all of them are for the 1st workspace folder. And if I open 1.25 and do the same everything works as expected.

Ah that must be it for the 2nd issue.

**Comment by roblourens** [comment]
Hey I think I fixed this in https://github.com/Microsoft/vscode/issues/55224, can you try again in the latest Insiders?

**Comment by eamodio** [comment]
@roblourens so far so good!
