### ISSUE TITLE
breadcrumb dropdown filter can't start with numbers

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#55387]
- VSCode Version: 1.26 Insiders
- OS Version: Windows

Steps to Reproduce:

1. Open vscode-docs v1_25.md
2. Click the breadcrumb file entry to see a dropdown showing sibling release notes files.
3. Try to filter on "1" or any number.

Nothing happens.

4. Type a letter

You now see the filter text box and can type any character, including numbers.

**Comment by jrieken** [comment]
Yeah, that's a problem with us having to guess what key event will produce what character...

**Comment by gregvanl** [comment]
This is still repro'ing for me on the most recent build 18d0027c33402b275bceb9b34d125d330dd78804

**Comment by jrieken** [comment]
The recent builds are produced from the release-branch, not the master-branch in which this is fixed
