### ISSUE TITLE
Autocomplete window truncated

### ISSUE THREAD

**Issue by rchande** [Microsoft/vscode#55380]
- VSCode Version: 1.25.1
- OS Version: Windows 10.0.17134

Steps to Reproduce:

1. Use an extension that provides autocomplete for long words
2. Words are truncated because the popup does not expand enough

![image](https://user-images.githubusercontent.com/3751401/43413478-03001de0-93e5-11e8-80e8-dd836200d851.png)

Copied from https://github.com/OmniSharp/omnisharp-vscode/issues/2434

Does this issue occur when all extensions are disabled?: N/A

**Comment by ramya-rao-a** [comment]
Covered in #29126 and #29757
