### ISSUE TITLE
edit keyboard shortcut directly from command palette 

### ISSUE THREAD

**Issue by tnrich** [Microsoft/vscode#55383]
I think a great feature would be if, when the user brings up a command via the Command Palette, hovering the right side of each suggested command would show a little edit icon. Clicking the edit icon would bring the user to the keyboard shortcut edit view for that command. 

For example, in the image below: 
![image](https://user-images.githubusercontent.com/2730609/43415860-88d0d17a-93eb-11e8-8f90-1dd39dcb6004.png)

If you hovered the "Search: Collapse All" line a little edit pencil would appear for you to click and edit the keyboard shortcut for that command. 

Hope that makes sense for y'all. I just think that would probably be the most natural way for the keybinding interaction to occur. 

Cheers!

PS: If this existed instead as an optional plugin I would also be fine with that but I do think it would be a purely helpful core functionality.

**Comment by isidorn** [comment]
fyi @sandy081

**Comment by sandy081** [comment]
@isidorn I see this is tagged as extension candidate. Would like to know how an extension can add such an entry to the command pallette?

**Comment by isidorn** [comment]
An extension can create a custom quick pick experience using our quick pick api.
Feel free to reopen

**Comment by sandy081** [comment]
I think user is asking to provide an edit button in the command pallette.

Duplicate of #27716

**Comment by tnrich** [comment]
@sandy081 is correct. I would like an edit button within the command palette itself :)
