### ISSUE TITLE
Test: Theming custom menus

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode#55384]
- [x] Linux @roblourens 
- [x] Windows @JacksonKearl 

Complexity: 2

This milestone, we added the following theme keys to theme the menus when `window.titleBarStyle` is set to `custom`.

```
"menu.background"
"menu.foreground"
"menu.selectionBackground"
"menu.selectionForeground"
"menu.selectionBorder"
"menubar.selectionBackground"
"menubar.selectionForeground"
"menubar.selectionBorder"
```

Verify:

* The theme keys make sense and you understand what they should do.
* All keys work as expected. You can set them manually with the `workbench.colorCustomizations` object setting.
* Ensure menus look good with our default themes.

**Comment by JacksonKearl** [comment]
I don't have a Linux box

**Comment by roblourens** [comment]
We can trade platforms @JacksonKearl

**Comment by JacksonKearl** [comment]
Okay
