### ISSUE TITLE
Add support to confirm messages shown at the top with the keyboard

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#5538]
- VSCode Version: 1.0.0
- OS Version:

Steps to Reproduce:
1. Do something that shows a message box at the top of the windows
2. Try to confirm that message with the keyboard.

This is very hard. You have to tab a lot and at some point to get focus there. If you then confirm your last focus position is lost. It would be nice if we can confirm with some special characters (shift+Enter) without loosing focus.

**Comment by bpasero** [comment]
Good idea.

**Comment by ChuckJonas** [comment]
this would be nice. some of us don't like to take our hands off the keyboard

**Comment by nickyhajal** [comment]
I would really appreciate this. Lots of linters add error messages in these popups and it's time consuming to go to the mouse every time to close them.

**Comment by douglaswaugh** [comment]
I would like complete control over which notifications display and when (i.e., I'd like to turn them all off, or have them collected somewhere less invasive.  Failing that, I'd like to at least have a keyboard shortcut where I could Accept/Close them.

Thanks!

**Comment by bpasero** [comment]
This landed via https://github.com/Microsoft/vscode/pull/43770 and can be tried out in our preview release: https://code.visualstudio.com/insiders/

There are commands to focus notifications and with a single Tab key you get to the actions.
