### ISSUE TITLE
Node auto-attach: Attach to child processes automaticlly

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#55394]
In order to reach parity with https://github.com/GoogleChromeLabs/ndb we should consider enabling [auto attach to child processes](https://github.com/Microsoft/vscode/issues/40123), when using the new Node auto attach feature.

**Comment by weinand** [comment]
This works already:
![2018-09-11_12-13-24](https://user-images.githubusercontent.com/1898161/45353821-40c60b00-b5bc-11e8-919c-fcdfa03b056f.gif)

**Comment by auchenberg** [comment]
Very cool @weinand :)
