### ISSUE TITLE
[Typescript 3.0.1] Ignores relative import refactor and always uses absolute

### ISSUE THREAD

**Issue by natew** [Microsoft/vscode#55392]
- VSCode Version: 1.25.1
- OS Version: High Sierra

Steps to Reproduce:

1. Move a file
2. Imports changed in other files are absolute

Does this issue occur when all extensions are disabled?: Yes

Just as it says. It seems to open and change the right files, but it makes the imports absolute. I tried setting every combination of (including not having any for either):

```
"typescript.preferences.importModuleSpecifier": "relative",
"javascript.preferences.importModuleSpecifier": "relative"
```

**Comment by natew** [comment]
Extra information:

Renaming the file in place works fine and keeps relative import.

Moving the file to a different folder (from $ROOT/some/sub/folder/file.ts to $ROOT/stores/file.ts) makes them absolute.

**Comment by JacksonKearl** [comment]
Related: Microsoft/TypeScript#25739. This was going the other way, but should fix this issue as well. Have you tried the latest Insiders?

**Comment by natew** [comment]
Is it in `3.0.1-insiders.20180726`?

**Comment by JacksonKearl** [comment]
Its a VS Code-side fix

**Comment by natew** [comment]
Yep, that fixes, thank you.
