### ISSUE TITLE
Start-up and switching folder(s) or files is supper slow

### ISSUE THREAD

**Issue by gpboutwell** [Microsoft/vscode#55391]
Issue Type: <b>Performance Issue</b>

Open VS Code
After initial load is slow editing appears to work 'normal', switching between folders or projects is slow like initial open.  Extensions enabled/disabled appears to be the same.

Debug Performance Status
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1375  INFO no standard startup: not just one text editor
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4459 Startup Performance Measurement
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4459 OS: win32 (6.1.7601)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4459 CPUs: Intel(R) Core(TM) i5-6440HQ CPU @ 2.60GHz (4 x 2592)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4459 Memory (System): 7.82GB (3.41GB free)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4460 Memory (Process): 214.89MB working set (284.82MB peak, 192.21MB private, 40.21MB shared)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4460 VM (likelyhood): 0%
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4460 Initial Startup: true
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4460 Screen Reader Active: false
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4460 Empty Workspace: true
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4460 
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4460 Extension Activation Stats
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4460 
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4461 Raw Startup Timers (CSV)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4461 Name	Start
main:started	1532981428246
main:appReady	1532981428339
main:loadWindow	1532981432021
renderer/started	1532981477300
willLoadWorkbenchMain	1532981477323
didLoadWorkbenchMain	1532981479523
main/startup	1532981479523
willAccessLocalStorage	1532981479538
didAccessLocalStorage	1532981479538
willStartWorkbench	1532981479538
willLoadExtensions	1532981479554
LifecyclePhase/Restoring	1532981479577
willRestoreEditors	1532981481466
didRestoreEditors	1532981481466
willRestoreViewlet	1532981481466
didRestoreViewlet	1532981481481
LifecyclePhase/Running	1532981481482
didStartWorkbench	1532981481489
LifecyclePhase/Eventually	1532981487984
extensionHostReady	1532981488109
didLoadExtensions	1532981488109

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6440HQ CPU @ 2.60GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.82GB (3.35GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe --prof-startup|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    64	 12524	code main
    0	    22	  5848	   shared-process
    0	   111	  9808	   window (Welcome - Visual Studio Code)
    0	     9	  8980	     extensionHost
    0	     1	 11940	     electron-crash-reporter
    0	     4	 11596	   shared-process
    0	    71	 11788	   window (Issue Reporter)
    0	    32	 12460	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
team|ms-|1.136.0

</details>

**Comment by gpboutwell** [comment]
This maybe related to Windows 7.  VSCode on basically the same laptop (a co-workers), in the same business environment but Windows 10 appears to run normally...

**Comment by jrieken** [comment]
When having started with `--prof-startup` some profile-files have been created. Please attach them to this issue. 

> This maybe related to Windows 7.

That's very likely

**Comment by gpboutwell** [comment]
@jrieken K, I attached all the output I knew to attach.  Sorry, I'm no sure what files are generated and were to grab them from to send.  But will be glad to do so...

**Comment by gpboutwell** [comment]
@jrieken I looked in my user profile for 2 files with the latest date-time and didn't find any.  There are lots of files that get touched, but no that seem to be named or related to profile...

**Comment by gpboutwell** [comment]
Not there...  In fact, search is not finding anything named *.cpuprofile* at all anywhere on my computer.


    Directory: C:\Users\gboutwel


Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
d-----        7/27/2018  11:29 AM                .dnx                                                                  
d-----         8/6/2018  10:41 AM                .eclipse                                                              
d-----         8/3/2018  11:28 AM                .puppetlabs                                                           
d-----        7/26/2018   1:20 PM                .vscode                                                               
d-----         8/6/2018  12:28 PM                .vscode-insiders                                                      
d-r---        7/26/2018   8:15 AM                Contacts                                                              
d-r---         8/7/2018  11:09 AM                Desktop                                                               
d-r---         8/1/2018  12:22 PM                Documents                                                             
d-r---         8/6/2018  12:20 PM                Downloads                                                             
d-----        5/17/2018  12:57 PM                Eclipse_Workspace                                                     
d-r---        7/26/2018   8:15 AM                Favorites                                                             
d-r---        7/26/2018   8:15 AM                Links                                                                 
d-r---        7/26/2018   8:15 AM                Music                                                                 
d-r---        7/26/2018   8:15 AM                Pictures                                                              
d-----        11/2/2017  11:03 AM                Roaming                                                               
d-r---        7/26/2018   8:15 AM                Saved Games                                                           
d-r---        7/26/2018   8:15 AM                Searches                                                              
d-----        7/26/2018   2:46 PM                Src                                                                   
d-r---        7/26/2018   8:15 AM                Videos                                                                
-a----         8/3/2018  12:50 PM            410 .gitconfig                                                            
-a----         5/2/2018  11:02 AM            284 .gitconfig.backup                                                     
-a----        7/12/2018   1:30 PM           2255 .kdiff3rc                                                             
-a----         8/6/2018  12:31 PM            139 894d                                                                  


    Directory: C:\Users\gboutwel\AppData\Roaming\Code


Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
d-----         8/3/2018   2:26 PM                Backups                                                               
d-----        7/30/2018   3:03 PM                Cache                                                                 
d-----        7/26/2018   1:20 PM                CachedData                                                            
d-----        7/27/2018  11:52 AM                CachedExtensions                                                      
d-----         8/6/2018  11:55 AM                databases                                                             
d-----        7/26/2018   1:21 PM                GPUCache                                                              
d-----         8/6/2018  11:55 AM                IndexedDB                                                             
d-----        7/30/2018   3:02 PM                Local Storage                                                         
d-----         8/6/2018   1:57 PM                logs                                                                  
d-----        7/26/2018   2:49 PM                User                                                                  
-a----         8/6/2018   2:03 PM           7168 Cookies                                                               
-a----         8/6/2018   2:03 PM              0 Cookies-journal                                                       
-a----         8/6/2018   2:02 PM              2 languagepacks.json                                                    
-a----        7/26/2018   1:20 PM             36 machineid                                                             
-a----         8/6/2018   1:57 PM           1389 Preferences                                                           
-a----         8/6/2018  11:55 AM          15360 QuotaManager                                                          
-a----         8/6/2018  11:55 AM              0 QuotaManager-journal                                                  
-a----         8/6/2018   2:51 PM          17198 storage.json                                                          

    Directory: C:\Users\gboutwel\AppData\Roaming\Code\User


Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
d-----        7/26/2018   1:21 PM                snippets                                                              
d-----         8/6/2018  11:40 AM                workspaceStorage                                                      
-a----         8/3/2018  11:27 AM            258 settings.json

**Comment by jrieken** [comment]
Then just re-run with `--prof-startup` and follow the instruction, they will point you the files

**Comment by gpboutwell** [comment]
Umm.. Ok.  I've re-ran with --prof-startup --disable-extensions a dozen times. I'm trying now with ONLY --prof-startup.  We'll see how it goes.

**Comment by jrieken** [comment]
It should be easy. You are following this guide, right: https://github.com/Microsoft/vscode/wiki/Performance-Issues#visual-studio-code-starts-up-slowly

**Comment by gpboutwell** [comment]
@jrieken Right.  That's what I have been doing.  The files are not created.  The Startup Performance Measurement Table that is displayed below that is available and I included it up above, but the two files that you seek are not there.
