### ISSUE TITLE
Streamline terminology for switching a diff editor into inline mode

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#55397]
From 
https://github.com/Microsoft/vscode/issues/54967#issuecomment-407653722:

1. GUI toggle: `Toggle Inline View`
2. Setting switch:  `renderSidebySide`
3. Keyboard toggle: `editorMode`.

**Comment by alexandrudima** [comment]
1. ✅ I've changed the GUI toggle: `Toggle Side By Side View`
2. ✅ I've left unchanged in Settings (avoid migration): `diffEditor.renderSideBySide`
3. I suggest we add a new command and leave the old one doing the same thing for keybinding compatibility purposes. @bpasero You introduced `toggle.diff.editorMode`, what id would you suggest to better align with the other two names?

**Comment by bpasero** [comment]
I added `toggle.diff.renderSideBySide` and deprecated the old one.
