### ISSUE TITLE
JavaScript IntelliSense Should Recognize DefineProperty

### ISSUE THREAD

**Issue by johnnykahalawai** [Microsoft/vscode#55390]
Issue Type: <b>Feature Request</b>

Hi -

Often when working with JavaScript an object i.e. class is extended with Object.defineProperty

Reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty

Unfortunately, Visual Studio's IntelliSense cannot make this connection so the GoTo Definition feature does not work.

FWIW, JetBrain's products e.g. WebStorm and IntelliJ does support this feature.

Thanks in advance,

Johnny

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.7.0

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#26082
