### ISSUE TITLE
Test feasibility of entering offline mode

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#55408]
Testing #54354

- [x] any OS @chrmarti 

Complexity: 2

- Go through https://github.com/Microsoft/vscode/issues/54354#issuecomment-407580259 and see if we missed any documenting any feature of VS Code that would make a network request.
- Test the new settings `extensions.autoCheckUpdates`, `npm.fetchOnlinePackageInfo`. 
- Ensure the `Show settings for Online Services` in the new settings editor displays all the settings related to features that make network requests.

Also see #55374 for ongoing discussion around the `Show settings for Online Services` view for more info

**Comment by chrmarti** [comment]
@ramya-rao-a A few more:
- Icon and badges in the extension editor are loaded from remote IIRC.
- Similarly the markdown previewer can load images from remote.
- The Experiments service.

**Comment by chrmarti** [comment]
Also: Issue reporter does a duplicate search.

**Comment by ramya-rao-a** [comment]
Thanks @chrmarti, I've updated #54354 accordingly and will include the above in the documentation.
Will add a setting for experiments. Rest are followups from a user invoked action, so they dont need a setting.
