### ISSUE TITLE
blank terminal LINUX BASH

### ISSUE THREAD

**Issue by Axeltherabbit** [Microsoft/vscode#55400]
When I start vscode the first terminal shell (Bash) is blank (screenshot: https://imgur.com/y5vsc95),
to fix it I need to open another terminal win and close the first one
  
`
$> code -v
1.25.1
1dfc5e557209371715f655691b1235b6b26a06be
x64
[ therabbit@xxx ] ~
$> uname -a
Linux xxx 4.17.10-1-ARCH #1 SMP PREEMPT Wed Jul 25 11:23:00 UTC 2018 x86_64 GNU/Linux
`

**Comment by Axeltherabbit** [comment]
my bad, was the ms-python.python extension the cause of the bug

**Comment by Tyriar** [comment]
How did you install VS Code?

What is $SHELL set to?

**Comment by Axeltherabbit** [comment]
`$> echo $SHELL
/bin/bash
`

vscode source: https://aur.archlinux.org/packages/visual-studio-code-bin/

**Comment by gabrielbiga** [comment]
The same problem here persists on visual-studio-code-bin and code aur packages.

**Comment by Tyriar** [comment]
Likely a problem with the unofficial AUR package.
