### ISSUE TITLE
instantiation services fails to caches services in cases

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#5540]
It might happen that a service dependency is cached not properly and therefore created again on subsequent calls.

**Comment by jrieken** [comment]
pls review the change

**Comment by alexandrudima** [comment]
@jrieken Maybe it is obvious, but maybe you need to present/frame the change...

**Comment by jrieken** [comment]
@alexandrudima look the the whole method. there was parameter `id` which was used to cache. That's the `id` of the service to create and not the `id` of dependencies that needed to be created first
