### ISSUE TITLE
Test SearchProvider API

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#55405]
Test https://github.com/Microsoft/vscode/issues/47058

- [x] AnyOS @RMacfarlane 
- [x] AnyOS @rebornix 

Complexity: 4

- There are 3 search provider APIs - `FileIndexProvider`, `FileSearchProvider`, and `TextSearchProvider`. Read the .d.ts docs, try to figure out what they do. Can you understand the difference between the two File* providers? Implement a basic extension that returns some dummy results. https://github.com/Microsoft/vscode/blob/f35b6ce8d8a24f2dcf756d8bd6e2069dd4f25cc9/src/vs/vscode.proposed.d.ts#L167

**Comment by misolori** [comment]
@roblourens is there a sample extension that uses the proposed apis? Having a hard time getting this to work.

**Comment by rebornix** [comment]
@misolori I created a sample extension using FileIndexProvider with proposed api enabled https://github.com/rebornix/vscode-extension-samples/tree/master/search-provider-sample . A `npm install` and `npm run compile` can work.

**Comment by rebornix** [comment]
@roblourens The return type of `FileSearchProvider` and `TextSearchProvider` is `void`, should it be `Uri[]`?

```
provideFileSearchResults(query: FileSearchQuery, options: FileSearchOptions, progress: Progress<Uri>, token: CancellationToken): Thenable<void>;

```

**Comment by roblourens** [comment]
@misolori yeah I can help you tomorrow or someone else can take this one since it's not an easy one.

**Comment by roblourens** [comment]
@rebornix Good catch, FileSearchProvider is not supposed to be using Progress anymore. But TextSearchProvider does return all its results through Progress.

**Comment by rebornix** [comment]
@roblourens I find myself have confusion with how the file* providers work with quick open. Like what's mentioned in #55551, the index provider kicks in before users open Quick Open but it won't affect how the results are being shown the first time.

The next one is `FileSearchProvider`, my suspicion is the results returned from `FileSearchProvider` will be shown when users search in quick open but it seems the results will be filtered again by the query internally.

For example, say we register a file search provider which always returns `index.js` under current folder.

```
	vscode.workspace.registerFileSearchProvider('file', {
		provideFileSearchResults: async (query: vscode.FileSearchQuery, options: vscode.FileSearchOptions, token: vscode.CancellationToken): Promise<vscode.Uri[]> => {
			return [vscode.Uri.file(path.resolve(options.folder.fsPath, 'index.js'))];
		}
	});
```

When I open quick open and type `a`, I got 0 result. Does it mean that vscode will do another round of filtering after getting the results from extensions?

**Comment by roblourens** [comment]
It should highlight but not filter, I still get it - 
![image](https://user-images.githubusercontent.com/323878/43561691-012b7624-95cd-11e8-8a7f-5afccef5ce51.png)

**Comment by roblourens** [comment]
That's not exactly what you said but I do get it for `a` as well.
