### ISSUE TITLE
when installing programs have the commands automatically loaded into terminal

### ISSUE THREAD

**Issue by zwhitchcox** [Microsoft/vscode#55409]
So, whenever I install something, e.g. yarn`, `node`, etc., I have to reload the whole program in vs code in order to get the command to work in the integrated editor. I have no idea why this is the way it is, but I would like it if I install `yarn` outside of the integrated terminal (because I have to run as admin), the command work in vs code without me having to restart the whole program.

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/47816
