### ISSUE TITLE
ApplicationInsights timeout throws error message

### ISSUE THREAD

**Issue by rjmholt** [Microsoft/vscode#55417]
Carried over from https://github.com/PowerShell/vscode-powershell/issues/1455, as filed by @Outek.

- VSCode Version: 1.25.1
- OS Version: Windows Server 2016

Steps to Reproduce:

1. Create a situation where VSCode is unable to connect to ApplicationInsights.
2. `code --list-extensions --show-versions`

Output:
```
PS C:\> code --list-extensions --show-versions
DotJoshJohnson.xml@1.9.2
lukehoban.Go@0.6.77
mauve.terraform@1.1.2
redhat.vscode-yaml@0.0.12
vscoss.vscode-ansible@0.1.3
ApplicationInsights:Sender [ { Error: connect ETIMEDOUT 40.77.226.250:443
      at Object.exports._errnoException (util.js:1050:11)
      at exports._exceptionWithHostPort (util.js:1073:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
    code: 'ETIMEDOUT',
    errno: 'ETIMEDOUT',
    syscall: 'connect',
    address: '40.77.226.250',
    port: 443 } ]
```

This initially occurred with the command:
```
PS D:\vscode_powershell> code --uninstall-extension ms-vscode.powershell
```

Which output:
```
Uninstalling ms-vscode.powershell...
Extension 'ms-vscode.powershell' was successfully uninstalled!
code : ApplicationInsights:Sender [ { Error: connect ETIMEDOUT 65.55.44.109:443
At line:1 char:1
+ code --uninstall-extension ms-vscode.powershell
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ApplicationInsi...5.55.44.109:443:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
      at Object.exports._errnoException (util.js:1050:11)
      at exports._exceptionWithHostPort (util.js:1073:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
    code: 'ETIMEDOUT',
    errno: 'ETIMEDOUT',
    syscall: 'connect',
    address: '65.55.44.109',
    port: 443 } ]
```

It looks like the actions are succeeding and then the error is thrown afterward... If that's the case and the error message is intended to be seen, then perhaps this is by design.

**Comment by ramya-rao-a** [comment]
How did you get to the situation where you couldnt connect to App Insights? Just went offline?

**Comment by keithbentrup** [comment]
I'm having the same problem except I never installed ApplicationInsights (AFAIK).
```
code --list-extensions
bierner.lit-html
bmewburn.vscode-intelephense-client
christian-kohler.npm-intellisense
christian-kohler.path-intellisense
cssho.vscode-svgviewer
dbaeumer.vscode-eslint
donjayamanne.githistory
eg2.vscode-npm-script
esbenp.prettier-vscode
felixfbecker.php-debug
felixfbecker.php-intellisense
ikappas.phpcs
jakebathman.mysql-syntax
jasonnutter.search-node-modules
ms-python.python
msjsdiag.debugger-for-chrome
oderwat.indent-rainbow
PeterJausovec.vscode-docker
stkb.rewrap
vincaslt.highlight-matching-tag
vsmobile.vscode-react-native
waderyan.nodejs-extension-pack
xabikos.JavaScriptSnippets
ApplicationInsights:Sender [ { Error: connect ECONNREFUSED 192.168.4.4:443
      at Object.exports._errnoException (util.js:1050:11)
      at exports._exceptionWithHostPort (util.js:1073:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
    code: 'ECONNREFUSED',
    errno: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.4.4',
    port: 443 } ]
```

**Comment by keithbentrup** [comment]
No, but it looks like the insights domain has made it to a dns blacklist. (I'm using pi-hole.) Also I found that it's the eslint extension that has telemetry enabled and is initiating the request.

**Comment by ramya-rao-a** [comment]
Thanks everyone. This week is endgame for the current iteration, we will get to this next week.

**Comment by ramya-rao-a** [comment]
I see the below when wifi is switched off:
<img width="870" alt="screen shot 2018-08-10 at 4 04 22 pm" src="https://user-images.githubusercontent.com/16890566/43984712-171c9a08-9cb7-11e8-9241-25325bbd2149.png">

**Comment by ramya-rao-a** [comment]
@keithbentrup 

> I'm having the same problem except I never installed ApplicationInsights (AFAIK).

This is coming from the app insights module used by VS Code.

**Comment by ramya-rao-a** [comment]
Verification Steps:
- Turn off wifi and/or wired network
- Run `code-insiders --list-extensions`
- Ensure you get the actual results without the error msgs as in https://github.com/Microsoft/vscode/issues/55417#issuecomment-412228135
