### ISSUE TITLE
intellisense in vue files are very slow,About 10 seconds or more

### ISSUE THREAD

**Issue by wbbhacker** [Microsoft/vscode#55418]
- VSCode Version:1.25
- OS Version:win7 

Steps to Reproduce:

1.Install vscode
2.Uninstall all extensions
3.intellisense in js or css files are very fast
4.but intellisense in vue files are very slow,About 10 seconds or more
5.I tried several lower versions of vscode and it didn't work

Does this issue occur when all extensions are disabled?: Yes

**Comment by wbbhacker** [comment]
yes，I didn't use Vetur extension,Have you read my description of the problem above?

**Comment by octref** [comment]
@wbbhacker I read it, but most people were using Vetur extension so I presume you were using it too.

Are you saying when you do `code --disable-extensions`, IntelliSense in Vue files are slow? But if there's no extension, there's no IntelliSense for Vue files by default.

**Comment by wbbhacker** [comment]
@octref ok,I'm try,If not, I'll reinstall the system,thx
