### ISSUE TITLE
Menu Items and Hovers Rendering as Symbols

### ISSUE THREAD

**Issue by fny** [Microsoft/vscode#55416]
- VSCode Version: 1.25
- OS Version: Red Hat Enterprise Linux Server release 7.4 (Maipo)

Steps to Reproduce:

1. Open VSCode

Does this issue occur when all extensions are disabled?: Yes

<img width="970" alt="screen shot 2018-07-31 at 12 54 26 am" src="https://user-images.githubusercontent.com/346068/43438561-d2bd99e6-945c-11e8-9f78-1e751bb330b3.png">

**Comment by isidorn** [comment]
What is exactly the issue here? What is unexpected and what behavior would you expect?
Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/

**Comment by fny** [comment]
The unexpected behavior is that I'm seeing "Wingdigs" instead of English characters in the menu dropdowns. Yes, I can reproduce this with the insider version.

**Comment by isidorn** [comment]
@fny you only see those weird characters in the menu, nowhere else in the UI?

**Comment by fny** [comment]
Also tooltips/popovers.

**Comment by isidorn** [comment]
Let's start with the localisation crew

**Comment by weinand** [comment]
Does this reproduce if you disable all extensions?

**Comment by fny** [comment]
This is already a bare installation without any extensions running.

For some more context, this the untarred running on a fairly bare bones box
that has no internet access for security reasons (patient data.)

**Comment by sandy081** [comment]
Not sure if it is a localisation issue as this occurs only in context menus, anything to do with electron?

**Comment by dbaeumer** [comment]
Agree with @sandy081 that this is very likely not a localization issues since it only appears in menus. I guess that this is a font setup issue. 

@bpasero what do we do to control the font of these menus. Is this something electron does automatically? Seems to affect native Electron controls.

**Comment by fny** [comment]
That didn't fix anything. Also, it looks like text in an editing pane has the same issue.

<img width="807" alt="screen shot 2018-08-14 at 4 25 46 pm" src="https://user-images.githubusercontent.com/346068/44116523-c2dcfe6c-9fde-11e8-90b5-4a98e6ed70ea.png">

**Comment by bpasero** [comment]
@fny can you update to our latest stable release (1.26) and try again?
