### ISSUE TITLE
Emmet not working in JSX statement when condition contains less than

### ISSUE THREAD

**Issue by mathdeziel** [Microsoft/vscode#55411]
- VSCode Version: `1.25.1` (also tried w/ `1.26.0-insider`)
- OS Version: `Windows_NT ia32 10.0.17134`

I was going through an intro course to React and stumbled on some issues with Emmet.  After reading the [documentation](https://code.visualstudio.com/docs/editor/emmet), I got it to work for the most part, but I couldn't find anything regarding to my issue.

There seems to be a bug with emmet in `else if` blocks with JSX in .JS and .JSX files.

---

_**Edit**: A member of the community [pointed out](https://github.com/Microsoft/vscode/issues/55411#issuecomment-409768888) that the issue was related to the less than sign (`<`) and not to the `else if` and so the issue was renamed.  Pleased read through the other comments for more information._

---

In short, the tab completion will work in a `return` if it is located in an `if` or an `else`, but will not work if it is located in an `else if` block (_please refer to the GIF below_). 

Steps to Reproduce:

1. Create a temp folder for the project
2. Add the emmet config provided below to the User Settings or Workspace Settings
3. Add a new file named List.js and populate it with the content provided below
4. Locate the method `renderChangePercent` around line 19 of the file, the comments will show where emmet works and where is located the bug.

Here is a GIF of the issue :
![vscode_emmet_jsx_elseif](https://user-images.githubusercontent.com/719796/43431823-e388e5c4-943d-11e8-82d5-195154108a98.gif)

Here is my emmet config :
```javascript
{
    "emmet.includeLanguages": {
        "javascript": "javascriptreact"
    },
    "emmet.triggerExpansionOnTab": true
}
```

And here is the file for testing :
```javascript
import React from 'react';

class List extends React.Component {
    constructor() {
        super();

        this.state = {
            loading: false,
            currencies: [],
            error: null,
        };
    }

    componentDidMount() {
        this.setState({loading: true});
    }
    

    renderChangePercent(percent) {
        if (percent > 0) {
            return <span className="percent-raised">{percent}% &uarr;</span>
        } 
        // Emmet does not work (tabs)
        else if (percent < 0) {
            return <div></div> 
        }
        // Emmet works
        else {
            return <span className="itWorks"></span>
        }
    }

    render() {
        if (this.state.loading) {
            return <div>Loading...</div>
        }
    }
}

export default List;
```

**Comment by ramya-rao-a** [comment]
Thanks for reporting @mathdeziel 

@JacksonKearl Can you take a look at this next week? https://github.com/Microsoft/vscode/blob/master/extensions/emmet/src/defaultCompletionProvider.ts would be the place to start.

**Comment by JacksonKearl** [comment]
Looks like the real culprit is the `<`. 
```
0 < 1;
sp // wont trigger
1 > 0;
sp // will trigger
```

**Comment by mathdeziel** [comment]
Good catch @JacksonKearl, you're right!  I should've tested that...

Here is a GIF attesting this hypothesis (_PS: don't look at the typo in the comment..._)
![vscode_emmet_jsx_lessthan](https://user-images.githubusercontent.com/719796/43556377-7d5148d2-95cd-11e8-92a6-af9c3fc228e9.gif)

I also retitled the issue to better reflect the real problem.

Thanks!

**Comment by JacksonKearl** [comment]
This was likely caused by #35128, where we wanted to disable emmet inside tags:
```
<img sr| // emmet shouldnt trigger here
```

I'll have to think about what the best solution here is. An obvious one would be to disable backtracking to look for opening brackets once you reach some set of characters (maybe semicolon, end paren, or newline?). But I'm not convinced that's the right fix.

**Comment by ramya-rao-a** [comment]
When backtracking, if we reach `<` but the character right after that cannot be part of a valid tag name, then we can ignore it. So the change can go here: https://github.com/Microsoft/vscode/blob/c3ad9789820afc6f9cab985bfa6e48175e414499/extensions/emmet/src/abbreviationActions.ts#L497 which already ignores the case of `<?`

**Comment by JacksonKearl** [comment]
But in this case, the character after is a space, which is valid as a tag name too

**Comment by ramya-rao-a** [comment]
space is not valid in a tag name as far as I know...

**Comment by mathdeziel** [comment]
Based on [the W3C recommendation](https://www.w3.org/TR/html5/syntax.html#start-tags), spaces _are_ valid in a tag name but only after the tag name itself, even if there are no attributes.

From my understanding,

```
<tag>            // valid
<tag >           // valid
<tag src="">     // valid
<  tag>          // invalid
```

So I would guess @ramya-rao-a's solution would work.

**Comment by mathdeziel** [comment]
I took the liberty to create a [PR](https://github.com/Microsoft/vscode/pull/55762) since it seemed to be an easy fix for a first OSS contribution with the help of @ramya-rao-a's recommendations -- which were spot on 😉 .

**Comment by mathdeziel** [comment]
PR as been merged, closing the issue.
