### ISSUE TITLE
VSCode Intellisense is not showing correct info

### ISSUE THREAD

**Issue by khaled4vokalz** [Microsoft/vscode#55414]
While using **private** constructor arguments in a typescript file and passing it to the **super()** constructor the intellisense shows that the value is declared but it is never used. But I am passing it to the **super()** constructor. Isn't it a use of my argument? but if the argument is declared as **Public** then the warning is not shown. Here is the image:

![image](https://user-images.githubusercontent.com/14083655/43435683-dc4b7f0a-94a2-11e8-8ded-6b193ca6d450.png)

- VSCode Version: 1.25.1
- OS Version: Windows 10

Steps to Reproduce:
1. Initialize a private constructor argument e.g. **constructor(private a: number)**
2. pass it to **super(a)** constructor

**Comment by mjbvz** [comment]
The error is correct. You are creating a member property but then only using the argument (instead of accessing `this.metadataPanelService`)

**Comment by khaled4vokalz** [comment]
@mjbvz isn't passing a value of a property as an argument to a method a usage? please correct me if I am wrong
