### ISSUE TITLE
How to use vscode on website?

### ISSUE THREAD

**Issue by DGideas** [Microsoft/vscode#5541]
I saw some website like http://try.buildwinjs.com/ use code editor like vscode. And I want to know how to use vscode on my website? I haven't see any topic on vscode wiki.
Thanks

**Comment by tw1nk** [comment]
There is already a feature request open for this here: 
#446

**Comment by dbaeumer** [comment]
Yes, this is a dup of #446

**Comment by DGideas** [comment]
@tw1nk @dbaeumer  Thanks
