### ISSUE TITLE
NLS uses old translation files

### ISSUE THREAD

**Issue by phil294** [Microsoft/vscode#55420]
![image](https://user-images.githubusercontent.com/14108705/43443262-a8dc8b0c-94a0-11e8-9f30-0e775577ba39.png)

What's going on? :D

---

Since latest update.

- VSCode Version: 1.25.1
- OS Version: Arch Linux

Steps to Reproduce:

1. Change some files, do not stage them
2. Try to commit

Does this issue occur when all extensions are disabled?: -> Yes

**Comment by joaomoreno** [comment]
This is very strange. Related to https://github.com/Microsoft/vscode/issues/54649 ?

**Comment by joaomoreno** [comment]
Can you reliably reproduce?

**Comment by phil294** [comment]
yes. the left  button seems to normally be something like "yes, always", becuase it sets git.enableSmartCommit to true. in other words, git.enableSmartCommit needs to be not true in order for this popup to show up in the first place. but that is intended behaviour, I guess.  The dialog has just become a little weird.

**Comment by joaomoreno** [comment]
@phil294  What is your exact VS Code version (commit id)?

Similar to #54847

**Comment by phil294** [comment]
@joaomoreno Latest official download I think, 1.25.1, 1dfc5e55

**Comment by joaomoreno** [comment]
And it reproduces 100% of the time?

Can you zip up the installation of VS Code and send me the bits?

**Comment by phil294** [comment]
Ah, not necessary, because I found the guilty files: I upgrade VS Code manually using something like

    curl -L 'https://vscode-update.azurewebsites.net/latest/linux-x64/stable' | tar xzf - -C ~/codeworkdir -

This does not erase files from a previous version that are not included in a new one. This *should* not make any difference though, should it?

And from the previous stable release, I still have the following files which are absent in the new version:

    VSCode-linux-x64/resources/app/extensions/git/out/nls.bundle.{de,es,fr,it,ja,,ko,ru,zh-cn,zh-tw}

`nls.metadata[.header].json` is still there in the latest version. When I delete the language bundles so it complies with the latest version, the prompt is fine. Note that the issue is valid for extensions-disabled mode too (I guess "git" is considered an always-active extension that cannot be disabled?).

I'm curious what you think about this. Is it expected behaviour that certain parts of VS Code break when you don't delete previous files before upgrading?

#54847 probably also came by due to a manual upgrading process.

**Comment by joaomoreno** [comment]
Excellent insights. cc @dbaeumer

**Comment by dbaeumer** [comment]
@joaomoreno i thought under Windows we install into a new directory and then swap them. So there shouldn't be any old files. Right? (unless the unzip the archive over the same location)

**Comment by joaomoreno** [comment]
@dbaeumer That's true! But one can still hit it by disabling background updates.

**Comment by dbaeumer** [comment]
I fixed it however it requries vscode-nls version 3.2.5

**Comment by joaomoreno** [comment]
@dbaeumer Did you do that adoption in our extensions? If not, can you create items to track that?

**Comment by dbaeumer** [comment]
I thought it will happen automatically but it doesn't because of the lock file. Will create myself and item and do it for everyone.

**Comment by dbaeumer** [comment]
See https://github.com/Microsoft/vscode/issues/57343

**Comment by octref** [comment]
I can repro this bug & it'll take #57343 to fix. So nothing to verify really.
