### ISSUE TITLE
HTML auto formatting using spaces instead of tabs

### ISSUE THREAD

**Issue by alan-agius4** [Microsoft/vscode#55423]
- VSCode Version: 1.25.1
- OS Version: Windows 10

Steps to Reproduce:

1. Set `"html.format.wrapAttributes": "force-aligned"` or `"html.format.wrapAttributes": force-expand-multiline` in the workspace settings
2. Set `indent_style` to tabs in `.editorconfig` for html
````js
[*.{cshtml,html}]
charset = utf-8
indent_style = tab
````
3. Format an html file.

![image](https://user-images.githubusercontent.com/17563226/43444812-03903e96-94a5-11e8-8eaf-c103647c1235.png)

![image](https://user-images.githubusercontent.com/17563226/43444880-24b8513a-94a5-11e8-9740-74b42f8a10d5.png)

I would expect that tabs are using instead of spaced.

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
What is the tab/spaces setting for your editor? Check out the lower right corner.

To sync settings in `.editorconfig` with the vscode settings, check out https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig

**Comment by alan-agius4** [comment]
Hi @aeschli my setting is `Tab Size: 4`
![image](https://user-images.githubusercontent.com/17563226/43455471-3fb47606-94c0-11e8-8f36-1f714c10f81a.png)

**Comment by aeschli** [comment]
reproduced on the https://beautifier.io/ playground:
- use tab as indent character
- set line length to 40
- custom settings:
```
{
  "wrap_attributes":   "force-aligned"
}
```
format the folloing code
```
<html>
<body>
    <div a=asdsd b=addasdas c=adadasda d=ASasS>
    </div>
</body>
</html>
```

Spaces are used to indent the attributes
![image](https://user-images.githubusercontent.com/6461412/45537617-fdaaa880-b804-11e8-9aeb-3868a977d74f.png)

**Comment by aeschli** [comment]
This issue was moved to beautify-web/js-beautify#1551
