### ISSUE TITLE
Disable some menu items when issue reporter is focused

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#55425]
Testing #55389

Steps to Reproduce:

1. Open issue reporter and focus that window
2. Open title bar menu.
3. Try clicking on an action such as `file -> New File`

**Bug**
These menu items have no effect but are still enabled

**Comment by mjbvz** [comment]
Also applies to process explorer

**Comment by sbatten** [comment]
this is no longer blocked by dynamic menus

**Comment by sbatten** [comment]
Issue reporter has possible work or not, either way, unlikely to fix this specific issue since it doesn't provide much value.
