### ISSUE TITLE
Double click title bar to expand window not working on MacOS

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#55421]
Issue Type: <b>Bug</b>

1. In macOS, double click on the title bar of the application

**Expected**
This should expand the window.

**Actual**
Nothing happens

VS Code version: Code - Insiders 1.26.0-insider (64c433bf2bd43c85d1bfe5753bb6fb90ff4be14a, 2018-07-30T05:11:25.700Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 18, 12|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_9320675|
|Screen Reader|no|
|VM|17%|

</details>

**Comment by RMacfarlane** [comment]
For me this only happens when the titlebar style is set to `custom`

**Comment by joaomoreno** [comment]
@sbatten Added `bug` label.
