### ISSUE TITLE
Extension search box shows "@category:" after typing "@tag:"

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#55422]
Testing #55386

Issue Type: <b>Bug</b>

1. In extension search box, type  `@tag:a`

**Bug**
`@category:` start showing up instead

![screen shot 2018-07-31 at 9 30 48 am](https://user-images.githubusercontent.com/12821956/43444767-e52e116c-94a4-11e8-8914-e68269f1860e.png)

VS Code version: Code - Insiders 1.26.0-insider (64c433bf2bd43c85d1bfe5753bb6fb90ff4be14a, 2018-07-30T05:11:25.700Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 18, 12|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_9320675|
|Screen Reader|no|
|VM|17%|

</details>

**Comment by JacksonKearl** [comment]
@ramya-rao-a what should we do in this case? We aren't able to change how these match. We could disable fuzzy finding entirely
