### ISSUE TITLE
Submenu closes with noticable delay

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#55437]
Refs: #55385

Ubuntu 18.04, insiders

Open some submenu in our menu bar.
Now hover over some menu item which does not have a submenu - notice 1 second delay in closing the submenu. I would expect the submenu to close instantaiously once its item is no longer focuesed

**Comment by sbatten** [comment]
This behavior helps us maintain a pleasant mouse experience such as addressing #55439 without making submenus or menus overly aware of each other. It is also close to the native experience on windows.
