### ISSUE TITLE
SmokeTest: vscode offers to create jsconfig.json although it exists

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#5543]
- VSCode Version: 1.0.1-Insider
- OS Version: Windows 10

Steps to Reproduce:

1. Express smoke test
2. Observe: green light bulp shows up although jsonfig.json file exists. Clicking on it prompts to create one.

![capture](https://cloud.githubusercontent.com/assets/1931590/14674555/ecd8f966-0704-11e6-96c5-e0cd5116a94a.png)

**Comment by jrieken** [comment]
Problem is a bad `jsconfig.json` files. It read

```
	"files": [
		"bin/wwww"
	]
```

Note the 4 w's, not 3. I have updated the test

**Comment by egamma** [comment]
I do no longer see a milestone, but the set-up in https://github.com/Microsoft/vscode-smoketest-express.git still doesn't make sense to me? 
- Why do have a files section on the `jsconfig.json`? 
- Why isn't `app.js` in the `files` section?

**Comment by jrieken** [comment]
No clue why that is. I closed cos the previous setup was even more broken using `wwww`

**Comment by egamma** [comment]
@jrieken fyi I've changed the sample so that it uses the default one that we generate from the light bulb.
