### ISSUE TITLE
Emmet not working in interactive playground

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#55432]
Issue Type: <b>Bug</b>

1. Open interactive playground
1. In the emmet section, try expanding the emmet snippet

**Bug**
Expansion doesn't work. No emmet entries show up in the comand palette

VS Code version: Code - Insiders 1.26.0-insider (0707dd4940b3fdbea8339595de478f354f6dda83, 2018-07-31T05:12:08.688Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 3|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|17%|

</details>

**Comment by chrmarti** [comment]
`Edit > Expand Abbreviation` works, `TAB` and content assist don't.

**Comment by ramya-rao-a** [comment]
See https://github.com/Microsoft/vscode/issues/44975#issuecomment-371970397
