### ISSUE TITLE
Menu layout broken when not enough vertical space for menu

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#55441]
Refs: #55385
Ubuntu 18.04, insiders

1. Resize your window such that there is not enough vertical space for a menu
2. Open a menu -> notice broken layout (menu bar gets hidden, blank space below status bar) 🐛

![screen shot 2018-07-31 at 11 27 31](https://user-images.githubusercontent.com/1926584/43451275-df4d836c-94b4-11e8-8cae-f8ac5237b757.png)

**Comment by sbatten** [comment]
same as #52533

**Comment by isidorn** [comment]
The cause might be the same, but the sympoms are different. In this case the whole window is badly rendered. But fine to close as dup for me

**Comment by sbatten** [comment]
@isidorn understood
