### ISSUE TITLE
Loaded scripts view needs to implement aria labels

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#55447]
Refs: #54921

Loaded scripts view should implement aria-labels for each of it's elements.
Now if you use a screen reader to navigate through the loaded scripts tree you will hear many "implement me" being announced

![arialabels](https://user-images.githubusercontent.com/1926584/43452918-ec04cf3a-94b8-11e8-8292-7d47516b0a71.gif)

**Comment by weinand** [comment]
There are now different aria labels for:
- Sessions
- Workspace Folders
- Folders
- Leafs
