### ISSUE TITLE
Restart frame does not clear loaded scripts view

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#55446]
Refs: #54921

1. Step over some code and notice how the loaded scripts view gets populated
2. Callstack view > right click > restart frame
3. Notice how the laoded scripts view is the same state as before the restart frame

I would expect the loaded scripts view to have a clean state after the restart frame aciton.

**Comment by weinand** [comment]
Why should "Restart Frame" affect loaded scripts?
"Restart Frame" just means start the current function from the beginning.

**Comment by isidorn** [comment]
I expected that the restart frame affects loaded scripts, but it seems I was wrong.
