### ISSUE TITLE
Breadcrumbs exclude rules

### ISSUE THREAD

**Issue by bm-stschneider** [Microsoft/vscode#55449]
Issue Type: <b>Bug</b>

It seems that the exclude rules for the side bar are not used for the breadcrumbs so all the folders are shown.

VS Code version: Code - Insiders 1.26.0-insider (0707dd4940b3fdbea8339595de478f354f6dda83, 2018-07-31T05:12:08.688Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_3293988|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.4
vscode-intelephense-client|bme|0.8.8
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.59
vscode-svgviewer|css|1.4.4
vscode-eslint|dba|1.4.12
gitlens|eam|8.5.3
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.34
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.3.0
prettier-vscode|esb|1.5.0
comment-anchors|Exo|1.1.1
php-debug|fel|1.12.3
php-intellisense|fel|2.3.3
beautify|Hoo|1.3.2
smarty|imp|0.3.0
docthis|joe|0.7.1
php-cs-fixer|jun|0.1.84
vscode-codemetrics|kis|1.17.1
php-symbols|lin|2.1.0
twig-language-2|mbl|0.3.1
php-namespace-resolver|Meh|1.1.0
vscode-scss|mrm|0.6.2
vsliveshare|ms-|0.3.472
debugger-for-chrome|msj|4.8.2
color-highlight|nau|2.3.0
vetur|oct|0.12.5
vscode-jest|Ort|2.9.0
vscode-docker|Pet|0.1.0
vscode-versionlens|pfl|0.21.1
material-icon-theme|PKi|3.5.2
vscode-yaml|red|0.0.14
code-settings-sync|Sha|3.0.0
sonarlint-vscode|Son|1.4.0
autoimport|ste|1.5.3
highlight-matching-tag|vin|0.4.4
Snippet|vsc|0.2.3
vim|vsc|0.15.7
vscode-import-cost|wix|2.8.0

(1 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
You mean for the picker, right?

**Comment by patrys** [comment]
Can confirm. Breadcrumbs show all files I've explicitly added to the ignore list in `files.exclude`.

**Comment by jrieken** [comment]
@isidorn Where is the filter implementation for the explorer and how reusable is that?

**Comment by atefBB** [comment]
Any news about this?
