### ISSUE TITLE
Loaded scripts identation broken once second program starts

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#55448]
Refs: #54921

1. Start debugging a first program, loaded scripts shows up and all is good
2. Start debugging a second program, loaded scripts has broken identation (too much to the left) 🐛
3. Notice that if I expand / collapse some nodes the indentation gets fixed

![screen shot 2018-07-31 at 12 00 13](https://user-images.githubusercontent.com/1926584/43453113-78cd2a52-94b9-11e8-8a7d-6a30af48a2bb.png)

**Comment by weinand** [comment]
that's a tree layout issue.

**Comment by isidorn** [comment]
@weinand None of the other trees are exibithing this behavior - and some do a very similar rendering to you, example Call Stack.
I suggest you look into this and check what is differnet between CallStack and Loaded Scripts before forwarding to Joao who does not fix tree bugs to my understanding.

**Comment by weinand** [comment]
The loaded scripts view is no longer extension code, so this is native tree issue.
I'll investigate whether I work around this.

**Comment by joaomoreno** [comment]
@weinand Interesting!

**Comment by joaomoreno** [comment]
:thinking: 

It could very well be an unintended constraint... I'm glad you found a way around it!

**Comment by weinand** [comment]
It would be helpful if you could add this constraint as a comment to the DataProvider interface.
