### ISSUE TITLE
savePartsSplash:  Cannot read property 'toString' of null 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#55455]
Issue Type: <b>Bug</b>

1. Enable high contrast mode
1. Restart VS Code

**Bug**
In the dev tools console, see the following errors:

```
  ERR Cannot read property 'toString' of null: TypeError: Cannot read property 'toString' of null
    at e._savePartsSplash (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3582:190)
    at e.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:172:552)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:175:613
```

VS Code version: Code - Insiders 1.26.0-insider (0707dd4940b3fdbea8339595de478f354f6dda83, 2018-07-31T05:12:08.688Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|12, 7, 6|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|17%|

</details>

**Comment by alexandrudima** [comment]
This affects the restoring of a workbench in high contrast:

![kapture 2018-08-03 at 10 43 41](https://user-images.githubusercontent.com/5047891/43633665-2e592cfc-970a-11e8-97f5-018cfed0648d.gif)
