### ISSUE TITLE
Remove "Accessibility Options" from help title bar

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#55451]
Testing #55389 

Issue Type: <b>Bug</b>

1. Enable custom title bar
2. Click on help

**Bug**
Notice entry for `Accessibility Options`. My understanding is that this is a command for internal use and should generally not be used by users

@alexandrudima Says we can remove the entire `Accessibility Options` command so that it no longer shows up in the command palette either

VS Code version: Code - Insiders 1.26.0-insider (0707dd4940b3fdbea8339595de478f354f6dda83, 2018-07-31T05:18:06.861Z)
OS version: Windows_NT x64 10.0.17686

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.98GB (1.25GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|57%|

</details>

**Comment by joaomoreno** [comment]
@sbatten Added `bug` label.
