### ISSUE TITLE
Loaded scripts view: hover not very useful

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#55459]
Refs: #54921

1. Start debugging
2. Hover over some item in the loaded scripts view shows "node" / "source" 
3. We usualy do not show the type in hover - the type should be clear looking at the tree. We usualy try to show additional data, so in this case I would expect to see the path when applicable.

**Comment by weinand** [comment]
What you are seeing is the default behaviour of your initial template. I didn't write any code for this...

**Comment by weinand** [comment]
I'm now returning the path for source and folder items, and the type "Session" for sessions.
The latter is in line with what you do for session objects in the callstack view.
