### ISSUE TITLE
Chrome debug: no loaded scripts view

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#55462]
Refs #54921

1. Start debugging using the chrome extension
2. No loaded scripts view

In my particular example I debugged 'launch vscode' configuration in our vscode repo.
I believe the issue here is that the chrome debug available on the marketplace still does not support loaded scripts.

**Comment by weinand** [comment]
@roblourens does the "Debugger for Chrome" already set the "supportsLoadedScriptRequest"?

**Comment by isidorn** [comment]
Looking here it seems like no
https://github.com/Microsoft/vscode-chrome-debug-core/blob/9afbe957503364d8d7b8225b1e890d59a65b4276/src/chrome/chromeDebugAdapter.ts#L277

**Comment by roblourens** [comment]
Yeah I guess that should go in -core not node2

**Comment by isidorn** [comment]
I still see this with latest vscode insiders:
1. vscode repo
2. "launch vscode" configuration (uses chrome)
3. Notice no loaded scripts view -> reopening

**Comment by roblourens** [comment]
Sorry, publishing it now.

**Comment by roblourens** [comment]
This is published with the flag to enable it but needs https://github.com/Microsoft/vscode/issues/57401 to be fixed.
