### ISSUE TITLE
Initial lodaded scripts view size is too large

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#55463]
Refs: #54921

1. Start vscode with a new user data dir
2. Start debugging, notice that the size of the loaded scripts view is really large
3. I suggest to use a smaller size, something which would be more alligned with the other debug views or even smaller

![screen shot 2018-07-31 at 14 22 09](https://user-images.githubusercontent.com/1926584/43459258-37b95c34-94cd-11e8-9de5-27ae0f7fe0cc.png)

**Comment by weinand** [comment]
Moved loaded scripts view to bottom, made it smaller and it is now initially collapsed.
