### ISSUE TITLE
Cannot type in issue reporter after moving it to a new window

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#55464]
Issue Type: <b>Bug</b>

1. On macos with multiple monitors
1. Launch issue reporter in primary window. 
1. Do not interact with the issue reporter but keep it focused.
1. Drag the issue reporter to a new window
1. Now try typing in it

**Bug**
Can't input any text

VS Code version: Code - Insiders 1.26.0-insider (0707dd4940b3fdbea8339595de478f354f6dda83, 2018-07-31T05:12:08.688Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|17%|

</details>

**Comment by RMacfarlane** [comment]
@mjbvz Does this reliably reproduce for you? I'm not seeing this on my machine

**Comment by mjbvz** [comment]
Yes, ~everytime. Make sure you are on MacOS and drag the issue reporter by the titlebar

**Comment by RMacfarlane** [comment]
@mjbvz Let me know if you do see this again, but I'm still not not able to get into this state and haven't seen other reports of this
