### ISSUE TITLE
Welcome page links are dragable

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#55466]
Steps to Reproduce:

1. Launch welcome page
2. Click and drag on the `New File` link

**Bug**
This starts a drag operation. VS Code shows this like you are dragging a file about

Possible fix: https://stackoverflow.com/questions/16283017/stop-chromes-click-and-hold-drag-image-default-behavior

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by chrmarti** [comment]
The suggested fix did not work. The behavior is the same as in, e.g., hovers.
