### ISSUE TITLE
Regular expression in Find dialog can't cope with backticks

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/vscode#5546]
![vscode regexerror](https://cloud.githubusercontent.com/assets/9283914/14674939/bf991772-0706-11e6-8f59-5010c4d29edd.png)
<br/>
I can't replace text containing backticks. Visual Studio Code doesn't correctly deal with those:
<br/>
![vscode regex error](https://cloud.githubusercontent.com/assets/9283914/14675320/bc4b680c-0708-11e6-8222-0613fefa850e.gif)

**Comment by alexandrudima** [comment]
This works fine for me:

File text:
```
| Default: `true`
| Default: `false`
```

Search string:
```
\| Default: `[^`]+`
```

![5546](https://cloud.githubusercontent.com/assets/5047891/23470676/5616a5dc-fea7-11e6-8bd2-2e119172473f.gif)
