### ISSUE TITLE
UriLabelService sohuld have an event OnDidUriLabelsUpdate

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#55473]
Issue Type: <b>Bug</b>

Testing #55358

1. Open a folder
1. Open a few files in this folder
1. Drag another folder into vs code to create a workspace

**Bug**
Notice that the open editor labels for previously opened files are not updated to include the project name. If you reload the window, the labels are updated properly

VS Code version: Code - Insiders 1.26.0-insider (0707dd4940b3fdbea8339595de478f354f6dda83, 2018-07-31T05:18:06.861Z)
OS version: Windows_NT x64 10.0.17723

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.98GB (1.61GB free)|
|Process Argv|C:\Users\matb\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|57%|

</details>

**Comment by mjbvz** [comment]
Not a regression from 1.25

**Comment by isidorn** [comment]
The UriLabelService should have an event `onDidUriLabelsUpdate` on which most trees should listen to and refresh when such an event is sent out.
Such an event would be sent out when going into workspace mode, a new uri display formatter is registered.

**Comment by isidorn** [comment]
This should be handled via https://github.com/Microsoft/vscode/pull/57690

**Comment by sandy081** [comment]
![kapture 2018-09-25 at 15 45 01](https://user-images.githubusercontent.com/10746682/46018380-05f2c580-c0da-11e8-8c85-e5b406daaf6a.gif)

**Comment by isidorn** [comment]
This is fixed now
