### ISSUE TITLE
Add a global action to add a new file in the explorer

### ISSUE THREAD

**Issue by SamVerschueren** [Microsoft/vscode#5547]
- VSCode Version: 1.0.0
- OS Version: OSX 10.11.3

I noticed that we can set `workbench.action.files.newFolder` to a keybinding. Which creates a nice input field in the sidebar to create the directory at the current selected position.

![screen shot 2016-04-20 at 15 06 05](https://cloud.githubusercontent.com/assets/1913805/14675479/7f52a86a-0709-11e6-9f55-4253728f5cb5.png)

But there is no possibility to do this for a file. Yes you can bind `workbench.action.files.newUntitledFile` but it does not do the same thing. It just creates a new `untitled file` and when pressing <kbd>cmd</kbd> + <kbd>s</kbd> you have to choose the destination in a picker. 

So, is it possible to add something for a new file as well? It would really improve my speed because I don't have to touch my mouse anymore to create a new named file in a specific directory.

**Comment by bpasero** [comment]
@SamVerschueren sounds like a good example for a PR?

**Comment by SamVerschueren** [comment]
Yes I looked into it but to be honest, I have to clue where to start :). So if you can point me in the right direction, I would be very happy to do one :).

**Comment by bpasero** [comment]
@SamVerschueren I would start by fulltext search for the action id (workbench.action.files.newFolder) and that brings you here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/fileActions.ts#L590

From there you can get a feeling how this global action works and maybe add the new one. You will also see the one on top for creating an untitled file (which is not what you want). 

When you find the references of that action you will see where it is being registered to the system: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/fileActions.contribution.ts#L169

**Comment by SamVerschueren** [comment]
Alright, awesome. Thank you very much @bpasero. Will see what I can do :).

**Comment by bpasero** [comment]
👍
