### ISSUE TITLE
Block "Synchronize Changes" button when there's an unsaved file

### ISSUE THREAD

**Issue by NatoBoram** [Microsoft/vscode#55477]
It would be a nice idiot-proofing feature to have if the "Synchronize Changes" button was blocked (or behind a confirmation dialog) while there's an unsaved file open in the editor that is located in the git repo. This way, it would be harder to `git pull` then `CTRL` + `S`, losing coworkers' code.

**Comment by joaomoreno** [comment]
Are you sure you would lose coworker's code? Code will correctly detect that there were changes to that file and show you a diff of them:

![peek 2018-08-02 15-48](https://user-images.githubusercontent.com/22350/43587873-7eb15df4-966b-11e8-8311-6ca7d3d1ff5b.gif)

**Comment by NatoBoram** [comment]
Hm. I think there were a bunch of shenanigans in the setup that made loss of code possible, including a too low limit of watchers in Linux (which was resolved afterwards) and *probable* human lack of attention.

In any case, it was just an idea I got after this happened between my coworkers. If it's not useful, feel free to close it!
