### ISSUE TITLE
Respect markdownDescription vs description in settings editor

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#55478]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Open the old settings editor
2. Hover over a settings such as `"window.title"` on the right hand side

**Bug**
Markdown is not rendered in the hover

![screen shot 2018-07-31 at 5 02 56 pm](https://user-images.githubusercontent.com/12821956/43468374-10c7d5bc-94e4-11e8-8aff-6ddbba8569c3.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
How do I make it do that like it does for other hovers? @jrieken ?

**Comment by mjbvz** [comment]
Looks like those hovers come from our json support? You can render the hover content as markdown by returning it as a `MarkdownString`

**Comment by roblourens** [comment]
We have to change all the setting registrations to use `markdownDescription` and `markdownEnumDescriptions`...
