### ISSUE TITLE
Hung, unkillable VS Code after dragging Macintosh HD into editor

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#55472]
Issue Type: <b>Bug</b>

1. In MacOS
1. Drag "Macintosh HD" onto vscode 
1. Wait a moment for code to relaunch

**Bug**
Code hangs and enters into an unkillable state. Even force quitting using `Activity monitor` didn't seem to work. The watcher and rg processes also go cpu crazy.

I don't think supporting opening `Macintosh HD` is needed, I'm just opening this bug because the failure mode here was ugly. Maybe we should warn if a user is trying to open a massive workspace (can we even detect that?)

VS Code version: Code - Insiders 1.26.0-insider (0707dd4940b3fdbea8339595de478f354f6dda83, 2018-07-31T05:12:08.688Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 7, 7|
|Memory (System)|16.00GB (1.56GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_10779207|
|Screen Reader|no|
|VM|17%|

</details>

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!
