### ISSUE TITLE
request

### ISSUE THREAD

**Issue by Dangtrungphu** [Microsoft/vscode#55487]
I feel very uncomfortable when the cursor continuously blinks when I saving html files

**Comment by aleksey-bykov** [comment]
did you try looking away?

**Comment by Dangtrungphu** [comment]
it looks like this

https://youtu.be/hpQjL0atR0M

**Comment by Dangtrungphu** [comment]
![capture-1](https://user-images.githubusercontent.com/40323522/43475244-572b8824-951f-11e8-99ab-92af0b56b1c7.gif)

**Comment by isidorn** [comment]
Can you reproduce this with all extensions disabled? How about with vscode insiders https://code.visualstudio.com/insiders/

**Comment by Dangtrungphu** [comment]
nguyên nhân của vấn đề này là do extebtion " Blank Line at the End of File
" cảm ơn đã hổ trợ tôi
