### ISSUE TITLE
Select all doesn't work from the menubar for webviews and terminal

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#55486]
Testing #54892 

With the new or old menubar the select all command doesn't work in webviews. Is it a separate command?

**Comment by mjbvz** [comment]
yes, and the terminal has its own select all command too. Should we dynamically register these commands to replace the normal select all command or is there a better way to do this?

**Comment by sbatten** [comment]
maybe the normal select all command could understand that it needs to call a different command. context keys would allow for you to dynamically register and replace the existing select all but it seems cumbersome to maintain as you would need to make sure the select all command didn't show up

**Comment by mjbvz** [comment]
@Tyriar Adding you for terminal

@sandy081 Would an approach like you took for unifying the find commands work  for you? #50583

**Comment by Tyriar** [comment]
Also keep in mind that the Edit and Selection menus contain editor only actions. I'm not sure making select all work where the focus was is a good thing. Focusing the terminal and running Edit > Find should open find in the editor, not the terminal imo.

I notice Copy works in the terminal but this is probably because it's working off the current selection in the webcontents rather than running the command to copy. That's the bug here imo.

**Comment by sandy081** [comment]
Currently Edit -> Find or Selection -> Select All are focus specific. They work only if editor is focused. If you have output panel focused and Edit -> Find opens find in Output panel. So why not opening terminal find when terminal is in focus?

**Comment by Tyriar** [comment]
@sandy081 I didn't know it did that, if that's the way we want the commands to work, sure.

**Comment by bpasero** [comment]
This will be challenging to get right because the custom menu is taking focus away and we have no notion of a "last active thing you can select all". 

The `Selection > Select All` was never working I think, not even in the native menu.

**Comment by sbatten** [comment]
@bpasero  We do return focus properly however, so it might be possible to have a single action that can redirect, right?

**Comment by bpasero** [comment]
@sbatten yes we would need the concept of a command that targets the thing that has focus, but we cannot have N different select all commands based on a context (which would be nice). 

We could fix this for webviews though by using the `activeEditor` context which I added this month. Requires the custom menu or the dynamic native menu (not yet enabled) to be working.
