### ISSUE TITLE
insider build complains about my language settings

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#5548]
I had this configure from the previous test run. Should be proper according to [this](https://code.visualstudio.com/docs/customization/locales)

![screen shot 2016-04-20 at 15 27 47](https://cloud.githubusercontent.com/assets/1794099/14676249/f788fdae-070c-11e6-9d24-7a495fe593a4.png)

**Comment by dbaeumer** [comment]
Good catch. Actually the proper value is en. I will add both to make json happy.

**Comment by dbaeumer** [comment]
This got fixed a long time ago.
