### ISSUE TITLE
display local images linked in the markdown of jsdocs

### ISSUE THREAD

**Issue by zpdDG4gta8XKpMCd** [microsoft/vscode#55484]
came from here: https://github.com/Microsoft/TypeScript/issues/26092

## Suggestion

display **local** images if they are linked in markdown inside jsdoc comments

## Use Cases

viewing images in inline documentation

## Examples

global images work

```ts
/** this is how it works ![Image of Yaktocat](https://octodex.github.com/images/yaktocat.png)
 */
class MyClass {
}
```
![image](https://user-images.githubusercontent.com/937933/43473941-7310ae12-94bf-11e8-90f7-e3aee4b503e7.png)

local images **DO NOT** work

```ts
/** this is how it works ![Hey](../../my-image.png)
 */
class MyClass {
}

```

**Comment by zewa666** [comment]
@zpdDG4gta8XKpMCd  you can actually display an absolute path which would be something along this lines:

```typescript
/** this is how it works ![Hey](/Users/Absolute/Path/To/Image/my-image.png)
 */
class MyClass {
}
```

One nice sideffect is that you can also resize the image using this pattern by adding heights and widths

```typescript
/** this is how it works ![Hey](/Users/Absolute/Path/To/Image/my-image.png|height=100|width=200)
 */
class MyClass {
}
```

**Comment by chipbite** [comment]
Hey @zewa666, I cannot get any local images to be displayed currently. I tried absolute path, same directory... nothing seems to work except non-local images. Does this still work for you?

**Comment by zewa666** [comment]
hmm can't really say as I'm no longer on Mac. On Windows it didn't work but what did is:

```
/** this is how it works ![Hey](file:///c:/temp/foo/test.png)
 */
```

**Comment by chipbite** [comment]
Thanks @zewa666, yeah, it is too bad it does not work so well. I can't even get that to work, oddly enough (also on win10).

**Comment by starball5** [comment]
Is this still an issue? Or did this feature get implemented already? It seems to work for me with relative paths like `![](foo.jpg)` and `![](./foo.jpg)`.

**Comment by cimak** [comment]
> Is this still an issue? Or did this feature get implemented already? It seems to work for me with relative paths like `![](foo.jpg)` and `![](./foo.jpg)`.

Seems to work but only in the same file: vscode is resolving image path relative to the file in which youre hovering/displaying jsdoc.
