### ISSUE TITLE
Terminal text column selection unstable when scrolling

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#55488]
Testing https://github.com/Microsoft/vscode/issues/55082

Issue Type: <b>Bug</b>

1. Use alt+click and drag to make a selection in the middle of the terminal
2. Scroll so that the top line of the selection goes off screen

![scrolling_selection](https://user-images.githubusercontent.com/3672607/43474929-12930906-94a9-11e8-99bc-79a964ee67cf.gif)

Result:
Selection visually changes to extend to the beginning of the line. Only the display seems to be incorrect, copy/pasting the selection in this state still produces the original selection.

VS Code version: Code - Insiders 1.26.0-insider (0707dd4940b3fdbea8339595de478f354f6dda83, 2018-07-31T05:18:06.861Z)
OS version: Windows_NT x64 10.0.17134

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/xtermjs/xterm.js/issues/1593
PR: https://github.com/xtermjs/xterm.js/pull/1594
