### ISSUE TITLE
Add syntax highlighting for Java 10 `var` keyword

### ISSUE THREAD

**Issue by domcorvasce** [Microsoft/vscode#55483]
Java 10 introduced the `var` keyword which is common to other programming languages and it's used to declare variables without specify a type for it.

```java
var name = "Bill";
```

I'm using **VSCode 1.25.1** and the highlighting for the keyword is missing and the variable declaration is not recognized by the editor.

**Comment by isidorn** [comment]
Please file against java extension. Thank you

**Comment by isidorn** [comment]
Yeah. Or whatever java extension you are using
