### ISSUE TITLE
References right side file path not normalized

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#55482]
Testing #55358

Issue Type: <b>Bug</b>

1. On Windows
1. In a js file.
1. Run `Find all references` on a variable that is referenced across multiple files
1. In the peek view, hover over the file path of the reference on the right hand side

**Bug**
The driver letter is not normalized (I'm hovering over the directory name here)

![screen shot 2018-07-31 at 5 45 27 pm](https://user-images.githubusercontent.com/12821956/43470952-263fc8e0-94ea-11e8-9d47-fbe574aef2f8.png)

VS Code version: Code - Insiders 1.26.0-insider (0707dd4940b3fdbea8339595de478f354f6dda83, 2018-07-31T05:18:06.861Z)
OS version: Windows_NT x64 10.0.17723

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.98GB (1.61GB free)|
|Process Argv|C:\Users\matb\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|57%|

</details>

**Comment by isidorn** [comment]
The references widget seems to be not going through the uri display service, since the paths are also not tildified.
I can also repro this in vscode stable.
Forwarding to @jrieken since he knows better where the references widget sets the title

**Comment by jrieken** [comment]
Hm, it should do that...

**Comment by jrieken** [comment]
Only usage of the  [FileLabel](https://github.com/Microsoft/vscode/blob/c51d1fc49cd707d0aa899313dee5e43f8a5f547b/src/vs/base/browser/ui/iconLabel/iconLabel.ts#L170)...
