### ISSUE TITLE
F7 is kind of broken and the better compareEditor.nextChange is not discoverable

### ISSUE THREAD

**Issue by GandalfSaxe** [Microsoft/vscode#55481]
I have an issue to the `Go To Next Difference` (F7), i.e.
```
editor.action.diffReview.next
editor.action.diffReview.prev
```
It seems inferior and I always avoid it in practice due to one simple fact: it doesn't highlight change _within_ the lines, only highlight whole lines added or removed. Otherwise I'd like the concept of cycling through the changed blocks and seeing nothing else.

Is this something that could be looked at? I found these much more useful:
```
workbench.action.compareEditor.nextChange
workbench.action.compareEditor.previousChange
```

which I only found thanks by accident thanks to #53062. These don't have any default keyboard shortcuts, and worse, they are not even discoverable in the Command Palette (Cmd+Shift+P). Yet these two commands are much more useful for reasons outlined above.

Compare this: (`workbench.action.compareEditor.nextChange`, hidden)

![image](https://user-images.githubusercontent.com/12127864/43470156-38fc14a4-94e8-11e8-9f41-f70c8a426880.png)

With this: (`editor.action.diffReview.next`, F7 and discoverable in command palette)

![image](https://user-images.githubusercontent.com/12127864/43470543-1a073712-94e9-11e8-963f-4f55f38d5b1b.png)

**Comment by GandalfSaxe** [comment]
The preferred solution would be to also highlight changes within line on the F7 command 👍

**Comment by GandalfSaxe** [comment]
Solution found in #53062.

**Comment by alexandrudima** [comment]
Let's close since we have merged https://github.com/Microsoft/vscode/pull/55493
