### ISSUE TITLE
javascript doc comments don't work for a parameter named `type`

### ISSUE THREAD

**Issue by epicgirl1998** [Microsoft/vscode#5549]
- VSCode Version: 1.0.0
- OS Version: Windows 8.1

Steps to Reproduce:

1. create a .js file containing the snippet below
2. hover over the function's name

```javascript
/**
 * @param {string} type
 */
function test(type) {
	return true;
}
```

the type hint for `type` should be `string`, but instead it is `any`

other parameter names do not suffer from the issue

i made a screenshot for your viewing pleasure:

![type](https://cloud.githubusercontent.com/assets/18557590/14675729/1b36c49c-0713-11e6-996a-305a3ff64b14.png)

the dev tools console is empty and i don't have any extensions installed

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#8222
