### ISSUE TITLE
Links aren't recognized when adding new config files

### ISSUE THREAD

**Issue by misolori** [Microsoft/vscode#55496]
Testing #55263

When adding new `tsconfig` files to an empty project, the references don't auto-update after you add the ref and there's no link (though it still recognizes that it's a path). I am forced to re-load in order for the link to be picked up.

I would expect that after I type the path that it becomes clickable without a reload.

After done typing:
![image](https://user-images.githubusercontent.com/35271042/43479072-62ea3248-94b4-11e8-929a-5ed9f64d4562.png)

After reload:
![image](https://user-images.githubusercontent.com/35271042/43479084-6771420c-94b4-11e8-9fcb-b9255a419779.png)

**Comment by mjbvz** [comment]
Weird. The links should always be clickable even if the referenced file doesn't exist

I think the issue that creating a new file called `tsconfig.json` does not actually activate the typescript extension (we normally rely on a workspace contains activation event here). I'll open a new bug to track that

**Comment by mjbvz** [comment]
Actually this is already tracked by #28122
