### ISSUE TITLE
Absolute URIs are not shown on hover

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode#55490]
Testing #55358 

If I understand the expectation correctly from the test plan, hovering the explorer or open editor tabs should reveal absolute URIs, but I am seeing relative paths.

> Absolute URI display is same as before (example: explorer hover, open editors hover, no tabs title area hover)

**Comment by isidorn** [comment]
@sbatten good catch

**Comment by bpasero** [comment]
I can still reproduce this for when tabs are disabled:

![before](https://user-images.githubusercontent.com/900690/43699577-9e16a87a-994f-11e8-969b-c9f01ff65390.gif)

**Comment by isidorn** [comment]
I can not reproduce this with latest vscode inisders
@bpasero do you still see this? If yes let me know and I will reopen
