### ISSUE TITLE
Keybindings editor shifts up on row select

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#55503]
- Open keybindings editor
- Select a row
- The page shifts up a few pixels

**Comment by sandy081** [comment]
@roblourens I do not see it.. can you please help me in finding it?

**Comment by roblourens** [comment]
I'm not seeing it now, but I do remember seeing it recently. I'll try to see what's going on next time I see it.

**Comment by sandy081** [comment]
Thanks, Please reopen it when you see it again
