### ISSUE TITLE
Shortcuts not working

### ISSUE THREAD

**Issue by tayyab80** [Microsoft/vscode#55501]
Issue Type: <b>Bug</b>

ctrl+c and etc shortcuts not working

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.88GB (0.32GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Users\Tayyab\Desktop\Angular\conFusion|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.12
vim|vsc|0.15.7

</details>

**Comment by Tyriar** [comment]
You need to give more information; where are they not working, what did you try, etc.
