### ISSUE TITLE
Prevent Split Editor button from defaulting to vertical

### ISSUE THREAD

**Issue by sundriftproductions** [Microsoft/vscode#55505]
When I need to split the editor in Visual Studio Code, 90% of the time I want to split the editor horizontally. Unfortunately, Visual Studio Code always sets the default value for the Split Editor button to vertical every time I launch the application. 

Although I can manually change the split so that it's horizontal via View -> Toggle Editor Group Layout and then split the editor, this seems like an unnecessary hassle. How can I ensure that Visual Studio Code's Split Editor default is always horizontal? I couldn't find the appropriate setting in the preferences.

Thanks!

**Comment by isidorn** [comment]
`	"workbench.editor.openSideBySideDirection": "down"`

**Comment by sundriftproductions** [comment]
Thank you!
