### ISSUE TITLE
Menubar: flicker on switch to full screen mode

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#55511]
- VSCode Version: 1.26 Insiders
- OS Version: Windows 10

During testing https://github.com/Microsoft/vscode/issues/55385

Steps to Reproduce:

1. Switch to Title Bar Style custom
2. F11 to go to full screen mode.

Notice a flicker and white line at the top of the menu bar.

**Comment by gregvanl** [comment]
Not surprisingly, also when going into Zen Mode.

**Comment by isidorn** [comment]
@gregvanl please try to assign issues to owners when you create them. Since that test plan item was created by Steven I will assign this to him.

**Comment by sbatten** [comment]
@gregvanl does this still repro for you? I was never able to see it on my machine.

**Comment by gregvanl** [comment]
@sbatten Yep, I still see it.
