### ISSUE TITLE
Need cursorWordPartDelete right/left

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#55512]
I've used this extension https://marketplace.visualstudio.com/items?itemName=ow.vscode-subword-navigation for subword navigation, and I can't switch to vscode's native version because it doesn't support deleting. I'd like to be able to use `ctrl+backspace` or `ctrl+delete` to delete a subword backwards or forwards.

**Comment by V-ed** [comment]
Isn't there `deleteWordPartLeft` and `deleteWordPartRight` that does exactly that?

**Comment by roblourens** [comment]
Oh yes, I didn't find those...
