### ISSUE TITLE
Add <node_internals>/** intellisense to `skipFiles` for Node

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#55517]
While testing #55403, I learned about `<node_internals>` in this comment: https://github.com/nodejs/node/issues/15464#issuecomment-332724821

Although I did find it in our doc https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_skipping-uninteresting-code-node-chrome, I think adding this as an auto-completed pattern would increase its discoverability.

**Comment by weinand** [comment]
Currently we do not support any auto-complete functionality for schema provided launch attributes.

**Comment by roblourens** [comment]
September? Is this easy?

**Comment by weinand** [comment]
@roblourens I commented on this item before targeting it for September, but this comment is now lost...
I said: we won't be able to support intellisense contributions for schema provided attributes but we should mention "<node_internals>" in the hover help for the "skipFiles" attribute.

**Comment by weinand** [comment]
Today the hover reads:
> An array of glob patterns for files to skip when debugging.

my proposal:
> An array of glob patterns for files to skip when debugging. Patterns starting with "<node_internals>" match internal Node.js modules, e.g. "<node_internals>/**/*.js" matches all.

@roblourens do you have something better and shorter?

**Comment by roblourens** [comment]
I think not all node files end with .js, so we should recommend `<node_internals>/**`. I think that text is fine, maybe we could shorten it like "The pattern `<node_internals>/**` matches all internal Node.js modules".

**Comment by weinand** [comment]
Yes, I like that.
Then let's go with:

> An array of glob patterns for files to skip when debugging. The pattern '<node_internals>/**' matches all internal Node.js modules.

**Comment by bpasero** [comment]
@roblourens verification needed?

**Comment by octref** [comment]
@roblourens Do you mind updating https://github.com/Microsoft/vscode-chrome-debug/blob/master/package.nls.json#L24 too?

**Comment by roblourens** [comment]
node_internals isn't used for chrome-debug
