### ISSUE TITLE
Telemetry: Add the ability to track usage of debug actions from editor gutter

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#55514]
When going over our telemetry for debug actions we have the ability to track usage counts of debug actions triggered from keyboard shortcuts and commands, as they execute commands which we emit telemetry for, but we don't seem to have telemetry in place for breakpoints set in the gutter (click or context menu). This is unfortunate as my hypothesis is that the majority of breakpoints are set this way.

https://github.com/Microsoft/vscode/blob/f82b14800cc0ed6f21a450b684518a4db05fc260/src/vs/workbench/parts/debug/browser/debugEditorActions.ts#L21

**Ask**
- Add ability to track breakpoint toggles (add/remove/change) from Gutter click
https://github.com/Microsoft/vscode/blob/bfc49dc41bcdbcaf0b64fe173415f6b9ce1ecd11/src/vs/workbench/parts/debug/electron-browser/debugEditorContribution.ts#L222
- Add ability to track breakpoint toggles from gutter context menu 
https://github.com/Microsoft/vscode/blob/bfc49dc41bcdbcaf0b64fe173415f6b9ce1ecd11/src/vs/workbench/parts/debug/electron-browser/debugEditorContribution.ts#L152

**Comment by isidorn** [comment]
@auchenberg would you like to contribute a PR for this? It shuold be fairly simple and you already have the nice code pointers.

**Comment by auchenberg** [comment]
@isidorn I'd be happy too, but we should land on an agreement on how to implement it. 

What's the best approach?
1) Add telemetry directly to the gutter actions
2) Re-wire the gutter actions to execute a command instead?

**Comment by isidorn** [comment]
@auchenberg for the best approach let's first see what you want to get exactly?
1. The total amount of all breakpoints set (including the gutter)
2. Fine grained events for breakpoint setting based on the way the user initated that aciton

In case of 1 we should just add a telemetry ping in the [`addBreakpoints`](https://github.com/Microsoft/vscode/blob/f35b6ce8d8a24f2dcf756d8bd6e2069dd4f25cc9/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L617) since everyone should go through there

In case of 2 depends on how fine grained you want it, if for every place then we should add an argument `source` or something like that in the addBreakpoints method and then also report that to telemetry.

**Comment by auchenberg** [comment]
I'd like us to be able to contribute a source/initiator to given breakpoint, so we can get an UI usage distributions, etc. @isidorn

**Comment by isidorn** [comment]
@auchenberg I suggest the following
Add a third argument `context: string` [here](https://github.com/Microsoft/vscode/blob/3a5b1263a5161bc4fec8606ac743c30d051c69bf/src/vs/workbench/parts/debug/common/debug.ts#L616)
In the implementation of that method use the telemetry service to report the appropriate event with the context.
And you should nicely get all the errors of all the callers of add breakpoints, simply pass different string context for each caller and you shuold be good to go.
Let me know if you have any questions

**Comment by auchenberg** [comment]
@isidorn Cool, I'l see what I can get cooking!

**Comment by isidorn** [comment]
Removing my assignment for this.
@auchenberg feel free to assign me back if you do not have time to tackle this and if we need this for August

**Comment by isidorn** [comment]
@auchenberg hey, would you still like this? If yes I can also look into it in October

**Comment by auchenberg** [comment]
@isidorn I'd still like to do this to get my hands dirty.

**Comment by isidorn** [comment]
@auchenberg cool, unasigning myself and let's leave it for October

**Comment by isidorn** [comment]
Verified by code review, adding verified label
