### ISSUE TITLE
debug - merge Watch and Variables section

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#5551]
When debugging I feel often distracted by the _Watch_ section and I would propose to merge its information with the _Variables_ section. It should be shown as a subgroup similar to scope variables. 

For me, and I believe I am not alone with that, the Variables and the Callstack sections are the most important. Now, my problem is that I actually use the Watch-section and therefore cannot just collapse it. That brings me the problem of managing it's size which effectively means I usually waste a lot of space at the bottom of the Variables and Watches section. I think the experience would be much better if it becomes an auto-sized node the Variables section.

![screen shot 2016-04-20 at 15 44 31](https://cloud.githubusercontent.com/assets/1794099/14676745/1f3d843a-070f-11e6-9f98-1d496e75395f.png)

**Comment by jrieken** [comment]
@isidorn  We talked about this. fyi @stevencl @bgashler1

**Comment by stevencl** [comment]
I understand the space problem. But I am not convinced that combining these sections is the best solution. Perhaps the viewlet needs to support an experience where section headers can be 'docked' to the bottom of the section above them such that they expand and contract with the space available. Similar to how the working files/open editors section works in the explorer but with the addition that there is an interaction the user can take to dock and undock sections. For example, if you drag the section header up to the bottom of the previous section it could dock. Then you could drag it off the bottom of the section to give it a fixed height.
