### ISSUE TITLE
ignoring [once again] exclude settings and downloading entire directories it was told to ignore

### ISSUE THREAD

**Issue by bobmagicii** [microsoft/vscode#55510]
![image](https://user-images.githubusercontent.com/881944/43484598-63909000-94d4-11e8-955b-fc7d531e1264.png)

i know its vs code, because it stops when quit it, and starts again when i open it back up. its downloading the entire bloody cdn lol, no matter what crazy patterns of * and ** i use in the exclude settings. this happens immediately on application launch. first i can see it hitting the workspace settings file, then it goes nuts.

it used to do this a long time ago... and it was fixed. but now it is unfixed.

its also got search.useIgnoreFiles true, and .gitignore git is successfully ignoring the data directory. but not vscode.

via files.exclude it does succeed at not putting it in the directory view on the left sidebar. but it still scans it.

![image](https://user-images.githubusercontent.com/881944/43484510-26e4623a-94d4-11e8-864b-3b7fb2e7709f.png)

**Comment by bobmagicii** [comment]
the currently running process according to file explorer

0	10	4460	             "c:\Program Files\Microsoft VS Code Insiders\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe" --files --hidden --case-sensitive -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store -g !**/data -g !**/vendor -g !**/node_modules -g !**/bower_components --no-ignore-parent --follow -- .

**Comment by roblourens** [comment]
I assume that rg process starts either when you press cmd+p, or when an extension tries to search.

The patterns look correctly applied to rg like `-g !**/data`. Are you sure that's the process causing the problem? It's possible for extensions to start searches that ignore the exclude patterns. You could start with `--disable-extensions` to check whether an extension is involved.

And I wonder what prompts the files to be downloaded, like even if ripgrep doesn't search inside the folder, if it just stats data/ could that trigger this?

**Comment by bobmagicii** [comment]
i am extremely sure its the process causing the problem. it is happening the moment vscode starts and opens the last used workspace.

yes, statting things is enough. its got to query the remote filesystem to do it. it may not be downloading all the bytes of the files, but its still statting 300,000+ remote files on the cdn even though they should have been ignored via the exclude settings.

i will test the --disable-extensions in the morning.

**Comment by roblourens** [comment]
Sorry for the trouble! I can't think of anything that would have recently caused a change. Those extensions probably aren't doing anything crazy, but the little badge says (4), are there a couple more extensions scrolled out of view?

What sort of remote filesystem is this, is there anyway I can test a similar setup?

You said it happens whether ripgrep is enabled or disabled - I'm pretty sure under both versions, search won't actually be looking inside `data/`, it sounds like maybe just statting data/ without going inside is enough to trigger this?

**Comment by bobmagicii** [comment]
in this case its a dev cloud server mounted via webdrive (sshfs), and that data directory is an nfs mount to the cdn. so we are crossing stats two remote file systems deep. thats why it really really needs to *genuinely* ignore things it is told to ignore. its still hitting the git dir and all that too but thats not as much a problem. idealy not files.exclude because i value being able to drill in at will. but the search.exclude needs to be super serious.

**Comment by roblourens** [comment]
Could you try a test to make sure it's what we think it is?

Run the command by itself in a command prompt from the folder you opened, `"c:\Program Files\Microsoft VS Code Insiders\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe" --files --hidden --case-sensitive -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store -g !**/data -g !**/vendor -g !**/node_modules -g !**/bower_components --no-ignore-parent --follow -- .` and make sure you see the same thing.

And if so, then add the `--debug` flag and paste the output here. If you could remove the other folders in that workspace to make the output cleaner that would help a lot.

No worries if you don't have time for that, I can try to set up webdrive to test it but it would have to wait til next week.

**Comment by bobmagicii** [comment]
indeed. same behaviour. its not printing that it found anything in those directories, but it is hitting them. and it stops when i ctrl+c kill it.

![image](https://user-images.githubusercontent.com/881944/43609733-6a7cbad2-966a-11e8-96af-e096458b8711.png)

**Comment by bobmagicii** [comment]
adding --debug to rg.

```
DEBUG/globset/globset\src\lib.rs:401: built glob set; 0 literals, 9 basenames, 0 extensions, 0 prefixes, 0 suffixes, 0 required extensions, 0 regexes

DEBUG/grep::search/grep\src\search.rs:195: regex ast:
Repeat {
    e: Literal {
        chars: [
            'z'
        ],
        casei: false
    },
    r: Range {
        min: 0,
        max: Some(
            0
        )
    },
    greedy: true
}

DEBUG/globset/globset\src\lib.rs:401: built glob set; 6 literals, 0 basenames, 0 extensions, 0 prefixes, 0 suffixes, 0 required extensions, 0 regexes

DEBUG/ignore::walk/ignore\src\walk.rs:1428: ignoring .\vendor: Ignore(IgnoreMatch(Override(Glob(Matched(Glob { from: None, original: "!**/vendor", actual: "**/vendor", is_whitelist: true, is_only_dir: false })))))

DEBUG/ignore::walk/ignore\src\walk.rs:1428: ignoring .\data: Ignore(IgnoreMatch(Override(phinx.php
Glob(Matched(Glob { from: None, original: "!**/data", actual: "**/data", is_whitelist: true, is_only_dir: false })))))

DEBUG/ignore::walk/ignore\src\walk.rs:1428: ignoring .\log: Ignore(IgnoreMatch(Gitignore(Glob { from: Some(".\\.gitignore"), original: "/log", actual: "log", is_whitelist: false, is_only_dir: false })))

DEBUG/ignore::walk/ignore\src\walk.rs:1428: ignoring .\backups: Ignore(IgnoreMatch(Gitignore(Glob { from: Some(".\\.gitignore"), original: "/backups", actual: "backups", is_whitelist: false, is_only_dir: false })))

DEBUG/ignore::walk/ignore\src\walk.rs:1428: ignoring .\.git: Ignore(IgnoreMatch(Override(Glob(Matched(Glob { from: None, original: "!**/.git", actual: "**/.git", is_whitelist: true, is_only_dir: false })))))
```

is_whitelist sounds like an oddity.

**Comment by roblourens** [comment]
Thanks. My guess is still that webdrive just downloads the folder even if search isn't stepping inside of it. I will experiment with it when I get a chance but I'm not sure what I'll be able to do.

I assume that using patterns like `**/data/` or `**/data/**` or `data` don't make a difference?

Only workaround I can think of, create a new folder, symlink to the folders you want to work with, exclude `data`.

**Comment by bobmagicii** [comment]
yeah i've tried every pattern under the sun. also extra info, its not specific web webdrive. its also happening when using expandrive (also sshfs).

**Comment by roblourens** [comment]
Are there 2 every time you open vscode? Can you get the command line of the second one?

Also can you try disabling the builtin Typescript extension? (Extension viewlet > search `@builtin` > find it under "Language Feature")

**Comment by bobmagicii** [comment]
my only two ideas would be

1) since it has an option "ripgrep" or what i guess would be "vscode's native way" - if the native way could be taught to properly ignore.

2) option to completely disable the search service. we're only ever searching open files, and anything else gets grepped from the command line. we had to adopt this method because the intellesense stuff never worked well on remote filesystems for the same reason - slow af due to remote.

**Comment by roblourens** [comment]
You're not the only one, we've looked at Nuclide and want to make that style of development better in vscode.

**Comment by devuxer** [comment]
@roblourens,

This may or may not be the same problem, but with the latest update to VS Code (1.28.1), when I do a search with "User Exclude Settings and Ignore Files" turned on, it's picking up results from my build folder, even though my .gitignore file contains `build/` (and git successfully ignores all the files in my build folder).

I  tried disabling all extensions and reloading--made no difference.

Should I file this as a separate bug or would you consider that the same thing?

**Comment by bobmagicii** [comment]
the .gitignore method did not work for me either back when we were first discussing this.

**Comment by roblourens** [comment]
I would recommend using the Remote - SSH extension, which is designed for exactly this sort of workflow. I won't be able to investigate this more, sorry.
