### ISSUE TITLE
Update mdn/browser-compat-data to latest version on VSCode load (or alert) 

### ISSUE THREAD

**Issue by richardjortega** [Microsoft/vscode#55523]
**Feature Request:**

The released VSCode version (1.25.1) introduced [Improved accuracy of Browser Compatibility Data](https://code.visualstudio.com/updates/v1_25#_improved-accuracy-of-browser-compatibility-data) which uses the [mdn/browser-compat-data](https://github.com/mdn/browser-compat-data) as its source of truth. However, the mdn package may be updated between VSCode releases. For instance, the Stable (1.25.1) and Nightly (1.26.0-Insider) builds both use a reference to the package that's out of date. As MDN updates that repo every 4-14 days, users may not have the latest version.

 

- VSCode Version:
  - Stable: (1.25.1 - 1dfc5e557209371715f655691b1235b6b26a06be)
  - Nightly: (1.26.0-Insider - 0707dd4940b3fdbea8339595de478f354f6dda83)

- OS Version: macOS High Sierra, Version 10.13.5

**Steps to Reproduce:**

Example using `justify-items` on VSCode 1.26.0-Insider

<img width="774" alt="screenshot 2018-07-31 14 35 00" src="https://user-images.githubusercontent.com/1143885/43488525-efd37e7a-94ce-11e8-9337-f64483047cc7.png">

vs the updated MDN compatibility list:

![screenshot 2018-07-31 13 59 59](https://user-images.githubusercontent.com/1143885/43488581-0e860630-94cf-11e8-886b-65082bbcbe0e.jpeg)

This change was reflected in: https://github.com/mdn/browser-compat-data/commit/306e87e95f643984114f4b53378125ca777831ff

Does this issue occur when all extensions are disabled?: Yes

**Suggested Implementations:**
- Check mdn/broswer-compat-data lib on VSCode editor load and prompt user to "Update" or not

Edit: Credit for the original find: @jo5hs

**Comment by jgardner04** [comment]
@octref IMHO we should always go with the automated option.

**Comment by MicrosoftEurope** [comment]
Yes, Microsoft knows best...

пт, 3 авг. 2018 г., 18:31 Jonathan Gardner (MSFT) <notifications@github.com

**Comment by octref** [comment]
The problem is not that we are not using the latest mdn data.

We are reading the `__compat` property of `justify-items`, but it doesn't have one. What it has is of this structure:

```
justify-items: {
  flex_context: {
    __compat: ...
  },
  grid_context: {
    __compat: ...
  }
}
```

This is not documented in BCD's schema and I've opened https://github.com/mdn/browser-compat-data/issues/2568 to track it.

**Comment by connorshea** [comment]
Keep in mind that the BCD schema isn't guaranteed to be stable since it's still v0.x, so it may not be the best idea to update it automatically for the user.

**Comment by octref** [comment]
- Re pulling latest Browser Compat Data: I'll do this manually until BCD reaches 1.0. This also gives us a chance to review changes. 
- Re reading multiple contexts in BCD: I pushed a temp fix. Currently let's say a property is supported in Chrome 30 in flex context and Chrome 40 in grid context, I show Chrome 40. This isn't optimal, which leads to:
- Display complex CSS compatibility layout: https://github.com/Microsoft/vscode/issues/57300.
