### ISSUE TITLE
Exclude Control: Clicking on option doesn't focus on setting item

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#55526]
Testing #55402 

I would expect that clicking an option would focus on the setting item:

![exclude](https://user-images.githubusercontent.com/4033249/43489010-66436920-94d0-11e8-9a95-250ca7bd2a27.gif)

Otherwise, the description doesn't get expanded and look weird.

**Comment by roblourens** [comment]
Other settings are the same, the control focus is independent of the setting itself.

I'll leave it for now since I may still try to get rid of focusing rows anyway.
