### ISSUE TITLE
Settings Editor: Weird logic in up/down

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#55527]
Why when I'm going down, it does not expand on "Application", and when I'm going up, it does not expand on "Features"? I would expect them to work consistently.

![setting-keyboard](https://user-images.githubusercontent.com/4033249/43489311-7a117fc2-94d1-11e8-850f-a5f78194833f.gif)

Also when going up, I feel it would be more natural to go to the last sub-section of the prev section. Namely, when pressing "Up" on B.1, it should go to A.2, not A.1

- A
  - A.1
  - A.2
- B
  - B.1

**Comment by roblourens** [comment]
Fixed with #54039
