### ISSUE TITLE
Settings Editor: Clicking on anchor doesn't work in search view

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#55529]
Testing #55401:

- Input "Search"
- In "Search: Exclude", click the anchor for `files.exclude`
- Nothing happens
- Clicking the anchor without search query works

![search](https://user-images.githubusercontent.com/4033249/43489690-b6ec8b0c-94d2-11e8-9507-99102fc0ef51.gif)

**Comment by roblourens** [comment]
#55179
