### ISSUE TITLE
Dark Theme JSX attributes grayed out 

### ISSUE THREAD

**Issue by alexanderby** [Microsoft/vscode#5553]
- VSCode Version: 1.0.0
- OS Version: Windows 7, 10

See the screenshot, Dark theme compared to Monokai theme. Only strings are colored inside JSX attributes.

![vscode-jsx-dark-theme-bug](https://cloud.githubusercontent.com/assets/9638588/14678634/3207fc3e-071f-11e6-8a4f-b74d16d457c4.png)

**Comment by aeschli** [comment]
caused by #3008
