### ISSUE TITLE
Built-in git extension disabled

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#55536]
Issue Type: <b>Bug</b>

1. Bring up code-insiders
2. In the extension viewlet, choose 'Disable All Installed Extensions' from the drop down menu.
3. Reload the window

-> The built-in git extension is disabled. It's the only built-in extension that's disabled. It only happens on mac. I could not reproduce it on Windows.

-> It only happens through the context menu. When I launch with `code-insiders --disable-extensions` the git extension remains enabled.

VS Code version: Code - Insiders 1.26.0-insider (0707dd4940b3fdbea8339595de478f354f6dda83, 2018-07-31T05:12:08.688Z)
OS version: Darwin x64 16.7.0

**Comment by sandy081** [comment]
This is a regression.

**Comment by joaomoreno** [comment]
@isidorn Verify this

**Comment by isidorn** [comment]
This works fine now following Kai's steps on mac.
