### ISSUE TITLE
Extensions panel - filter by contribution points

### ISSUE THREAD

**Issue by axefrog** [Microsoft/vscode#55534]
Note: I think there is another issue that speaks to this issue but only with respect to themes.

I believe the extensions panel needs better filtering options overall. Currently there's nothing much you can filter on with respect to the extension characteristics themselves, other than free text search, which is kind of a fuzzy "hope for the best" kind of thing, with no apparent exact matching or otherwise.

Below is a screenshot of the on-screen portion of my current installed extensions panel (with probably another 50% requiring scrolling to see.) I've highlighted the themes, but what about other contribution points? How can I specifically search for themes (either among what I have installed, or from what is in the marketplace) which provide grammars, views, panels, etc.? What about exclusions? So often I want to search for an extension that provides some kind of functionality I want, but have to sift through loads of irrelevant themes in the process. Sometimes I want _all_ my search terms to be included, whereas other times I want _any_ of them to be matched.

![image](https://user-images.githubusercontent.com/298883/43491086-7f8349fa-9566-11e8-9edd-aefa40841c32.png)

How can this be improved?

**Comment by JacksonKearl** [comment]
We actually already have a contribution point based querying language for extensions, but it isn't very well known. In the current Insiders we have added IntelliSense to the extensions search to help with discoverability. See here:
![image](https://user-images.githubusercontent.com/8586769/43602984-73b65bea-9646-11e8-945e-e52d2b46c80b.png)

We will be continuing to work on this querying system in August, to better support composing these filters (`@installed @category:themes`, for example). I've created an issue to track that at #55697.

**Comment by ramya-rao-a** [comment]
We rely on the search features from the [marketplace](https://marketplace.visualstudio.com/vscode) which does not support exclusions and the "or" condition.

@auchenberg correct me if I am wrong above.

But like @JacksonKearl mentioned above, we will look into the "and" condition of the filters and the search terms in the next iteration.
