### ISSUE TITLE
Intellisense for generic parameterized string literal function arguments not working

### ISSUE THREAD

**Issue by njgraf512** [Microsoft/vscode#55530]
- VSCode Version: 1.26.0-insider
- OS Version: MacOS 10.12.6

Steps to Reproduce:

1. Enter the following into a TS file:
```ts
const myObj =  {
  foo: 'Foo',
  bar: 'Bar',
}

function myFunc<T>(obj: T, key: keyof T) {
  return obj[key];
}

myFunc(myObj, 'f')
```
2. Observe that once you begin typing the `f` of string literal `foo` for the function's second argument, the tooltip switches from suggesting `"foo" | "bar"` to `never`:

**Good:**

![screen shot 2018-07-31 at 2 52 01 pm](https://user-images.githubusercontent.com/22208823/43489606-69b31acc-94d2-11e8-987c-98fe2ae25e46.png)

**Bad:**

![screen shot 2018-07-31 at 2 52 48 pm](https://user-images.githubusercontent.com/22208823/43489563-45f27470-94d2-11e8-932b-54736575d944.png)

3. Also, triggering intellisense with <kbd>control</kbd>+<kbd>space</kbd> does not suggest `foo` or `bar`:

![screen shot 2018-07-31 at 2 52 26 pm](https://user-images.githubusercontent.com/22208823/43489977-ac3d31ce-94d3-11e8-90e5-21c5e1c96aa2.png)

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#26662
