### ISSUE TITLE
Arrow down on menubar should expand menu and select first item

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#55539]
Issue Type: <b>Bug</b>

1. Set `window.menuBarVisibility` to `toggle`
2. <kbd>Alt</kbd>
3. <kbd>ArrowDown</kbd>
-> menu expands with no menu item selected
3. <kbd>ArrowRight</kbd>
-> `Undo` is selected

I'd expect `New File` to be selected after step 3.

VS Code version: Code - Insiders 1.26.0-insider (0707dd4940b3fdbea8339595de478f354f6dda83, 2018-07-31T05:18:06.861Z)
OS version: Windows_NT x64 10.0.17134

**Comment by joaomoreno** [comment]
@sbatten Added `bug` label.
