### ISSUE TITLE
Show line of opening bracket or tag in an editor overlay

### ISSUE THREAD

**Issue by hassanbinsafdar** [microsoft/vscode#55537]
Hello I want when i write a complete page of html sometimes page or div tags are too long so i want when i click on closing html tag and its parent not in view so parent class name with tag appear in bar like this. I am attaching the image for better understanding its actually available in phpstorm.

![feature](https://user-images.githubusercontent.com/13061479/43492960-ef651a2c-9544-11e8-8fb4-1a2ae5f1aa04.jpg)

**Comment by aeschli** [comment]
You want to see the location of the start of the actual block in an overlay at the top of the editor.
It's not something we currently have. If we add support for that, it should be implemented as an editor feature and work for all languages.

**Comment by alexandrudima** [comment]
This feature request is very similar to #52734

I wonder if you've tried our new breadcrumbs, they should help for in-file navigation.

**Comment by hassanbinsafdar** [comment]
@alexandrudima  thanks for advice but will you give me little bit concrete explanation of how i can try breadcrumbs because in editor i can't find options for this.
Thanks

**Comment by alexandrudima** [comment]
@hassanbinsafdar 
1. install [VSCode insiders](https://code.visualstudio.com/insiders/)
2. configure `"breadcrumbs.enabled": true`

**Comment by hassanbinsafdar** [comment]
@alexandrudima thanks I got it and yes its working perfectly 👍

**Comment by alexandrudima** [comment]
Let's track in #55075 (it has more upvotes at this time).
