### ISSUE TITLE
Settings Editor: Give more contrast to backtick code blocks

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#55532]
Testing #55401

Interactive Playground:

![image](https://user-images.githubusercontent.com/4033249/43489975-a9a8a4e8-94d3-11e8-8fc7-a70ef5ac21d7.png)

GitHub:

![image](https://user-images.githubusercontent.com/4033249/43489982-af4235d6-94d3-11e8-9beb-b3725779dd9c.png)

Settings Editor:

![image](https://user-images.githubusercontent.com/4033249/43490005-b9265974-94d3-11e8-96ba-65794178c896.png)

It's much harder to scan through the setting description to find which word is code.

**Comment by roblourens** [comment]
Good point! I thought that text was missing something. Hover has a background color for `code` segments, I wonder why we use one or the other. Thoughts @misolori?

![image](https://user-images.githubusercontent.com/323878/43491231-8e613c2c-94d8-11e8-96ce-d64e46e39ca9.png)

**Comment by misolori** [comment]
I think I prefer for them to be consistent, but then that adds more confusion with our links. What if we kept the same styling as we do with the playground (has both links and code blocks) and made the links use our regular font and also match the naming structure?

![image](https://user-images.githubusercontent.com/35271042/43491955-8222f268-94db-11e8-86b9-666b4f7c9289.png)

**Comment by roblourens** [comment]
I like that! I hadn't even thought about the names.

**Comment by roblourens** [comment]
Opened https://github.com/Microsoft/vscode/issues/55695 for the link names.
