### ISSUE TITLE
重启调试

### ISSUE THREAD

**Issue by aixiaoxianggithub** [Microsoft/vscode#55546]
Issue Type: <b>Bug</b>

最近的vscode版本遇到重启调试无法正常结束老程序，刷新为新程序的问题。有时候必须手动kill 老程序

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.55GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
rest-client|hum|0.19.0
vscode-language-pack-zh-hans|MS-|1.25.3
mssql|ms-|1.4.0
Go|ms-|0.6.85
debugger-for-chrome|msj|4.8.2
vetur|oct|0.12.5
view-in-browser|qin|0.0.5
java|red|0.29.0
vscode-java-debug|vsc|0.10.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.7.1
vscode-maven|vsc|0.10.0
markdown-all-in-one|yzh|1.6.0

</details>

**Comment by isidorn** [comment]
Please file this issue in english with nice reproducable steps and I will reopen

**Comment by aixiaoxianggithub** [comment]
@isidorn

**Comment by isidorn** [comment]
Please file this issue against the go extension - thank you
