### ISSUE TITLE
Disable Selection/Go/Edit menus when there is no visible/active editor

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#55545]
Testing #55389

We can probably disable selection actions when `editorFocus` is `false`.

<img width="795" alt="image" src="https://user-images.githubusercontent.com/876920/43498418-729fd20e-9579-11e8-9016-25961d9d08e3.png">

**Comment by alexandrudima** [comment]
This is blocked by #55453, currently the global context is evaluated when computing the enablement/disablement of extensions.
