### ISSUE TITLE
VSCode TS Autocomplete prepends a double "this." reference

### ISSUE THREAD

**Issue by yuval-gilboa** [Microsoft/vscode#55544]
Issue Type: <b>Bug</b>

When selecting a member method/property after typing "this.", a second "this." reference is prepended by the TS auto-complete  in VSCode. This behavior started since VSCode version 1.25. See video below

![vscode](https://user-images.githubusercontent.com/4710322/43497953-639e1a30-954d-11e8-897d-7752e1320439.gif)

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 6.1.7601

**Comment by mjbvz** [comment]
Does this still reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled? Are you using any typescript plugins?
