### ISSUE TITLE
Show All menu is greyed out only after clicking

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#55548]
Testing #55389

The screencasting tool I use can't capture the menu bar but the reproduce steps are simple

* Close the last vscode window
* Menubar only shows Code-Insiders, File, Window and Help
* Click Code-Insiders -> Show All

Show All is not greyed out and the last step does nothing (this is as expected). However after clicking it, Show All is greyed out. 

The last step does nothing.

**Comment by sbatten** [comment]
@rebornix these actions are provided by the os and enablement is determined by them. I could get the same behavior using iTerm2
