### ISSUE TITLE
dotnet run works, but vs code shows lots of errors

### ISSUE THREAD

**Issue by VanCoding** [Microsoft/vscode#5555]
Hi guys!

I use VS Code to develop my ASPNetCore application. It highlights over 50% of my code as errorous from the beginnging, even if `dotnet run` works just fine. I first thought that it's just a bug that you are aware of and are going to fix in a coming version. But when you guys released V1.0, I began to doubt that.

Also, VS Code constantly tells me that I need to restore, even if I have manually restored using `dotnet restore`. And if I let VS Code do its own restore, I cannot start my application using `dotnet run` anymore until I do `dotnet reload` manually again.

So, is this a bug or am I doing something wrong?

Thanks for your help! :)

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#228
