### ISSUE TITLE
Unable to code block end in Ruby

### ISSUE THREAD

**Issue by nwoow** [Microsoft/vscode#55558]
I am using 

VS code - Version 1.25.1 (1.25.1)

My OS - Sierra 10.13.3 (17D47)

I am using vs code for my rails application for that I am using VS Code Ruby Extension everything work fine except one thing. I am unable to see the end of the code block.

But when I change anything for example I go to bottom left of my file and change type LF to CRLF or CRLF to LF  it start working but when I go to other file and return it stops working. 

I posted this query in VS Code Ruby Extension  but no answer there. I don't know what is causing this problem. 

What is the logic behind  code block ending is there anything wrong with visual code

**Comment by isidorn** [comment]
I think vscode can do nothing here and this has to be solved by the ruby extensions, so please try to create more issues there. If you believe this is a vscode issue then please paste nice reproducable steps, like for what code what is not happening etc...
