### ISSUE TITLE
{{ } 添加问题，只能在 “}” 后面添加第二个 “}”，不能再其前面添加

### ISSUE THREAD

**Issue by IBUMBLEBEE** [Microsoft/vscode#55550]
Issue Type: <b>Feature Request</b>

{{ } markdown文件下编辑只能在 “}” 后面添加第二个 “}”。

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.7.0

**Comment by isidorn** [comment]
Please file this issue in english with nice reproducable steps and I will reopene
