### ISSUE TITLE
Allow to open new native window tab when dropping folder into window

### ISSUE THREAD

**Issue by mrleblanc101** [microsoft/vscode#55552]
- VSCode Version: 1.25.1
- OS Version: macOS 10.14 beta 5

Steps to Reproduce:

1. Start dragging a folder from the Finder
2. Drop it in a VS Code "workspace" (right side of the editor)

Expected behavior:

VS Code should open a new native tab if the option ```"window.nativeTabs": true``` is enabled.
It only work if the folder is dragged into the Dock icon.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@mrleblanc101 this should work if you configure your mac dock settings to prefer opening new windows as tabs instead of windows. Can you try that?

**Comment by bpasero** [comment]
@mrleblanc101 you can try with setting `window.openFoldersInNewWindow:on` to force open a new window everytime for folders.

**Comment by mrleblanc101** [comment]
Was already set to "on" and it does not work.

**Comment by mrleblanc101** [comment]
Fixed #90767
