### ISSUE TITLE
Built in updater for both stable and insider

### ISSUE THREAD

**Issue by theapache64** [Microsoft/vscode#55553]
It'd better if we've built in updater within the vscode, so that we don't have to download the package and install it again.

**Comment by joaomoreno** [comment]
What platform are you on?

**Comment by theapache64** [comment]
Linux/Ubuntu

**Comment by joaomoreno** [comment]
Got it. We do not support auto updates on the Linux archive distribution.

The official recommended way is to use the Deb release: https://code.visualstudio.com/docs/?dv=linux64_deb

Another (personally recommended) alternative is this: https://twitter.com/joaomoreno/status/1006810768283701251

**Comment by theapache64** [comment]
Wow, that's wonderful. 

I've read the script you wrote, found the API, and created my own version. It downloads the  `deb` package instead `.tar.gz` . Bonus, zero configuration. 

Just execute below command

```
wget -O - https://raw.githubusercontent.com/theapache64/sh/master/vscode_insiders_updater.sh -q --show-progress | bash
```

and It'll do the REST

![](https://raw.githubusercontent.com/theapache64/sh/master/vscode_insiders_updater_demo.gif)


 [full source available here](https://github.com/theapache64/sh)

**Comment by theapache64** [comment]
Bonus Alert! .  I've shortened the command to `code-insiders-update`. :stuck_out_tongue_winking_eye:
