### ISSUE TITLE
$tsc-watch matcher causes 'Building..' status to appear forever when used with the new tsc --build command

### ISSUE THREAD

**Issue by rotemdan** [Microsoft/vscode#55560]
- VSCode Version: `Latest x64 1.26.0-insider`
- TypeScript Version: `3.0.1`
- OS Version: `Win10 x64 build 17134.165`

Steps to Reproduce:

`tasks.json`:
```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "TypeScript Watch",
			"type": "shell",
			"command": "tsc",
			"args": [
				"--build",
				".",
				"--watch"
			],
			"isBackground": true,
			"problemMatcher": [
				"$tsc-watch"
			],
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"presentation": {
				"reveal": "silent",
				"panel": "dedicated"
			}
		}
	]
}
```

Does this issue occur when all extensions are disabled?: **Yes**/No

(The [`--build` command is new in TS 3.0](https://blogs.msdn.microsoft.com/typescript/2018/07/30/announcing-typescript-3-0/#project-references) and allows to use references between projects.)

Trying to use the `$tsc` matcher instead causes no `Building..` status to appear at all, though it does seem to work otherwise.

**Comment by dbaeumer** [comment]
@mjbvz thanks for looking into this.

**Comment by mjbvz** [comment]
Fixed upstream. Unfortunately not back-ported to 3.0.3 but will be in 3.1.0
