### ISSUE TITLE
Prefer workspace typescript

### ISSUE THREAD

**Issue by ravshansbox** [Microsoft/vscode#55567]
Issue Type: <b>Bug</b>

When two version of typescript is available (workspace version and editor version) editor should prefer workspace version.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (1.24GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.12
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.34

</details>

**Comment by mjbvz** [comment]
See this discussion of why we cannot do this by default: https://github.com/Microsoft/vscode/issues/26046

**Comment by ravshansbox** [comment]
If we don't trust the workspace version, then how do we protect from workspace including `.vscode/settings.json` and still forcing vscode to use workspace version?

**Comment by mjbvz** [comment]
Switching to the workspace version requires a user action the first time, even if you specify it in the `.vscode/settings.json`

**Comment by ravshansbox** [comment]
Ough, thanks for the info, now I got it.
