### ISSUE TITLE
relative sourceMap not found

### ISSUE THREAD

**Issue by dmail** [Microsoft/vscode#55566]
- VSCode Version: 1.26.0-insider
- OS Version: mac 10.13.6

Steps to Reproduce:

1. Create `file.js`
```javascript
const value = "ok"

debugger

console.log(value)
```

2. Create `file.es5.js`
```javascript
var value = "ok"

debugger

console.log(value)
//# sourceURL=./file.js
//# sourceMappingURL=./file.es5.js.map
```

3. Create `file.es5.js.map`
```json
{
  "version": 3,
  "sources": ["./file.js"],
  "names": ["value", "console", "log"],
  "mappings": "AAAA,IAAMA,QAAQ,IAAd;;AAEA;;AAEAC,QAAQC,GAAR,CAAYF,KAAZ",
  "file": "./file.js"
}
```

4. Create `.vscode/launch.json`
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch with node",
      "program": "${file}",
      "sourceMaps": true,
      "trace": "verbose",
    },
  ]
}
```

5. Open `file.es5.js` in vscode

6. Launch it using `Launch with node` configuration

**Expected behaviour**

- vscode stops at debugger
- vscode shows `file.js` content instead of `file.es5.js`

**Actual behaviour**

- vscode does not stops at debugger

**Additional information**

debug console output contains two explicit logs:

`Paths.scriptParsed: could not resolve ./file.js to a file with pathMapping/webRoot: undefined. It may be external or served directly from the server's memory (and that's OK).`

`SourceMaps.loadSourceMapContents: Could not read sourcemap file - ENOENT: no such file or directory, open './file.es5.js.map'`

vscode will work as expected when I
replaces occurences to `./file.js` by `/Users/dmail/project/file.js` in `file.es5.js` and `file.es5.js.map`;
replaces occurences to `./file.es5.js.map` by `/Users/dmail/project/file.es5.js.map` in `file.es5.js`

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
It seems that combination of sourceURL + sourceMappingURL doesn't work with chrome devtools either, but I think it should work with vscode.

**Comment by roblourens** [comment]
Actually no that's not valid. You are saying that the script should be called `./file.js`, then that the sourcemap is `./file.es5.js.map` relative to the script. But the script does not have an absolute path because you just renamed it to `./file.js`. sourceURL is taken literally, it isn't resolved as a relative path.

**Comment by dmail** [comment]
Indeed, during my tests I remember sourceURL + sourceMappingURL was preventing chrome devtools from working normally. However I cannot reproduce with the following steps:

1. Create an `index.html`.

```html
<html>

<head>
	<script src="./file.es5.js"></script>
</head>

<body></body>

</html>
```

2. Open it inside chrome using a server or directly from filesystem

3. Open chrome devtools

4. Reload the page

Chrome dev tools stopped at debugger on the source file as shown in screenshot below:
![image](https://user-images.githubusercontent.com/443639/43532512-910c0d1e-95b2-11e8-81b4-841b8b5dd3d5.png)

**Comment by dmail** [comment]
@roblourens, how can I make my example work with vscode then ?
I have already tried to replace `./file.js` into `file.js` without success and I feel like I tried every possible way to declare a relative sourcemap.

Chrome devtools works with relative paths like `./file.js`, `file.js` but vscode doesn't 😿

**Comment by roblourens** [comment]
Can I ask why you want to use sourceURL? If you are using sourcemaps anyway, sourceURL doesn't seem useful

**Comment by roblourens** [comment]
You said you were using the Node debugger. This does work with Chrome in vscode.

In vscode it's different because if nothing else works, we can resolve files relative to the root of the webserver ("webRoot" in the launch config).

**Comment by dmail** [comment]
No special reason behind using sourceURL.
Yes I'm using the Node debugger, just wanted to point out it works with chrome.
I have removed sourceURL comment and it works \o/.

The real issue is that having a relative source url comment in the file breaks source map resolution.

But I'm just going to remove this sourceURL comment because it's useless.
