### ISSUE TITLE
settings git.path should have better documentation

### ISSUE THREAD

**Issue by pashute** [Microsoft/vscode#55563]
Issue Type: <b>Bug</b>

git.path means path of git.  e.g. "C:\Program Files (x86)\Git\cmd"

but you expect it with the git executable: 
"C:\\Program Files (x86)\\Git\\cmd\\git.exe"

1. In the default user settings you should give an example in the documentation, so that people see the extra git.exe and that they must use a double backslash. 

2. In any case use a different name, or change it so that the ending "git.exe" is not necessary, and if its missing, use the default "git.exe". 

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

**Comment by joaomoreno** [comment]
Indeed, but it's too late to change it now as we do not have a setting migration story. The setting description actually says `Path to the git executable`.

**Comment by pashute** [comment]
Yes but still you can correct the description. It is NOT just the path to the executable. It is the path AND FULL NAME to the executable. 
And you can give an example or a default
