### ISSUE TITLE
{{ } . You can only add a second "}" after "}", you can't add it in front of it

### ISSUE THREAD

**Issue by IBUMBLEBEE** [Microsoft/vscode#55565]
Issue Type: <b>Bug</b>

The {{ } symbol can only be added after the "}" after editing under the markdown file.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.23GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_57358|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
vsc-rustfmt|Con|0.1.0
vscode-markdownlint|Dav|0.19.0
code-runner|for|0.9.3
shell-format|fox|1.1.3
beautify|Hoo|1.3.2
plantuml|jeb|2.8.4
AWK|lug|0.0.2
vscode-language-pack-zh-hans|MS-|1.25.3
mssql|ms-|1.4.0
python|ms-|2018.7.1
cpptools|ms-|0.17.7
Go|ms-|0.6.85
vscode-docker|Pet|0.1.0
material-icon-theme|PKi|3.5.2
startanyshell|rem|0.3.1
vscode-icons|rob|7.24.0
rust|rus|0.4.9
preview-vscode|sea|1.4.2
code-settings-sync|Sha|3.0.0
markdown-preview-enhanced|shd|0.3.5
vscode-mermaid-preview|vst|0.10.1
markdown-pdf|yza|1.2.0
markdown-all-in-one|yzh|1.6.0
propertylist|zho|0.0.2

(1 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment]
@IBUMBLEBEE this is a feature that is enabled by default. The feature comprises of automatically inserting a closing } when { is typed. If you don't like the feature, you can configure `"editor.autoClosingBrackets": false`

**Comment by IBUMBLEBEE** [comment]
Thank you!
