### ISSUE TITLE
HTML formatter not working

### ISSUE THREAD

**Issue by MykhailoIskiv** [Microsoft/vscode#55573]
Issue Type: <b>Bug</b>

document formatter stopped working for html files, though it's enabled
it shows
there is no document formatter for 'html'- files installed

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 5, 4|
|Memory (System)|16.00GB (0.32GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
vscode-clock|Com|0.0.1
EditorConfig|Edi|0.12.4
sort-lines|Tyr|1.7.0
html-snippets|abu|0.2.1
npm-intellisense|chr|1.3.0
vscode-svgviewer|css|1.4.4
angular2-snippets|dan|1.0.19
githistory|don|0.4.2
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.34
vscode-npm-script|eg2|0.3.5
auto-rename-tag|for|0.0.15
beautify|Hoo|1.3.2
svg|joc|0.1.1
Angular2|joh|6.1.1
import-sorter|mik|2.0.4
vscode-postcss-sorting|mrm|3.0.1
azure-account|ms-|0.4.2
sublime-keybindings|ms-|4.0.0
debugger-for-chrome|msj|4.8.2
vscode-docker|Pet|0.1.0
view-in-browser|qin|0.0.5
postcss|ric|2.0.0
vscode-icons|rob|7.24.0
final-newline|sam|0.3.2
jenkinsfile-support|sec|0.1.0
ngx-translate-zombies|sev|0.0.1
bash-beautify|sha|0.1.1
code-settings-sync|Sha|3.0.0
vscode-spotify|shy|2.5.1
vscode-fileutils|sle|2.10.3
autoimport|ste|1.5.3
code-spell-checker|str|1.6.10
change-case|wma|1.0.0

</details>

**Comment by MykhailoIskiv** [comment]
@aeschli I saw that comment, and checked it and it was enabled. I didn't do any changes in my config but for some reason document formatter stoped working. At first it was just html, then similar issues occurred for javascript, typescript and might happened with other formats, just don't remember exactly. Also it looked like some other extensions stopped working, as it didn't highlight errors in code, like using things that weren't imported to typescript document. I tried to reboot my mac (as sometimes it fixes things :) ) with open currently opened apps after reboot windows option but it did'n help. Then I rebooted it without saving opened apps, and looks like it helped (although not sure wether it was related to not opening running apps), as it started working again.

**Comment by aeschli** [comment]
Hmm, that's bad. The next time you see this, maybe check out if the logs contain any hints on what went wrong. You can look ate the logs in the output view.

**Comment by MykhailoIskiv** [comment]
@aeschli It happened again, and I've checked logs, in Output tab, checked all from dropdown and didn't see anything related. Only mac restart helped. And I've noticed weird thing, after rebooting, when everything works, it has more items in Output dropdown, when  document formatter stopped working, there were only Tasks and Extensions options (and the ones that are after separator Log...)

**Comment by aeschli** [comment]
@MykhailoIskiv Thanks for reporting back. Some of the entries in the dropdown are only created once that component is activated (e.g. Git or TypeScript). So maybe not a problem.

In the Log (Extension Host) you should see `ExtensionService#_doActivateExtension vscode.html-language-features`

Can you set `"html.trace.server": "verbose" `. Once you see the problem again, go to the `HTML Language Server` tab in the output view and look if there's any mentioning of `client/registerCapability` and `"textDocument/rangeFormatting"`?
