### ISSUE TITLE
custom titleBarStyle : titleBar should be loaded prior than the rest of the app.

### ISSUE THREAD

**Issue by Guema** [microsoft/vscode#55571]
I think that in an effort of coherence and reliability with os-driven-titlebar version,
the custom title bar should be loaded in a prior and faster loading phase.
Allowing to instant maximise or close, for exemple.
Menu bar could be fake loaded as a placeholder if data is not available already.
Layout should be loaded after.
But OS-window-related features (like close/windowing/reduce) should be available asap.

![loading](https://user-images.githubusercontent.com/8943532/43519705-cbe4f850-9590-11e8-8e11-12f69e96cd1f.gif)

Thanks,
Guema

**Comment by sbatten** [comment]
related #52507

**Comment by sbatten** [comment]
will keep tracking in related
