### ISSUE TITLE
Bad Translation of "Let's Go!" menu in VS Code

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/vscode#55578]
The German translation of the VS Code "`Go`" menu is inappropriate:

![vs code go menu](https://user-images.githubusercontent.com/9283914/43525789-0d6e168c-95a3-11e8-9324-718c02504cb9.png)

"`Los`" is German for "`Let's Go!`", an interjection to run a horse or a military unit. Or, alternatively, it's the noun "`Lottery ticket`". I feel both interpretations not to be rather fitting here.

"`Navigation`" may be a more appropriate translation.

**Comment by nealot** [comment]
Maybe the English version could use "Navigation" too? It gets pretty confusing when working with the go language and "navigate to" sounds a lot more professional.

**Comment by SetTrend** [comment]
... same for "`View`" which is commonly translated to German as "`Ansicht`", not "`Anzeigen`" (see screenshot above).

**Comment by danyeh** [comment]
Thank you @SetTrend for your feedback.
We host translation in Transifex and accept contribution from community. General guidance is here: https://aka.ms/vscodeloc.
It will be great if you can fix in Transifex and get enough vote from native speaker contributors so your fix get used in product.
The string must be in this query. https://www.transifex.com/microsoft-oss/vscode-workbench/translate/#de/$/150692246?q=text%3AGo

**Comment by SetTrend** [comment]
@danyeh 

Thanks for pointing me!

I've now added my German suggestions to Transifex for "&&Go" and "&&View". Please vote.

By the way: Wading through a plethora of "View" entries, I didn't have the slightest clue where these expressions were supposed to be used. Is there a way to tell where the corresponding items will be use within VS Code?

**Comment by danyeh** [comment]
I voted. Now new translation suggestion is being used. Thank you!
It is hard to link the string in string table to run time instance w/o check the code logic. I assume can guess from the resource ID and filename (all can be found in Transifex editor UI) as first step.
