### ISSUE TITLE
Syntax Highlighting optional class variable in type definition file.

### ISSUE THREAD

**Issue by zelein** [Microsoft/vscode#55575]
Issue Type: <b>Bug</b>

VSCode syntax highlighting breaks when it encounters an optional class level variable in a type definition (.d.ts) file.

The example below is a simplified version of what I was seeing in one of my emitted type definition files. 

When pasting this block into a .d.ts file, you should see the variables "private readonly" below where `test2?;` is declared in the TestClient turn from the expected dark blue to a light blue, or the same color as the variable name.  This has reaching affects throughout the file and causes other things below it to be improperly rendered. I've provided the `TestClient2` definition to show a simple case of it.
```
// test.d.ts
export declare class TestClient {
    private readonly test1;
    private readonly test2?;
    private readonly test3;
    private readonly test4;
}

export declare class TestClient2 {
    private readonly test1;
    private readonly test2;
    private readonly test3;
    private readonly test4;
    private readonly test5;
}
```

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (8.78GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.34
vsliveshare|ms-|0.3.504
vscode-icons|rob|7.24.0

</details>

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript-TmLanguage/issues/642 and https://github.com/Microsoft/TypeScript-TmLanguage/issues/643 to track this upstream
