### ISSUE TITLE
Why remove "Check for updates"?

### ISSUE THREAD

**Issue by cg31** [Microsoft/vscode#55576]
Issue Type: <b>Feature Request</b>

In old version (insider release), there is a "Check for update" under Help. 

I like it and uses from time to time.

Why remove it? 

VS Code version: Code - Insiders 1.26.0-insider (573d53815e74f8e4a52c2b6665f5ba9a92dbd341, 2018-08-01T05:17:54.216Z)
OS version: Windows_NT x64 10.0.17134

**Comment by isidorn** [comment]
@sbatten Did you maybe remove this with the new menu?
fyi @joaomoreno

**Comment by joaomoreno** [comment]
@sbatten Added `bug` label, please add repro steps.
