### ISSUE TITLE
Indent Patterns are not defined/work for Python

### ISSUE THREAD

**Issue by outcoldman** [Microsoft/vscode#5557]
- VSCode Version: 1.0.0
- OS Version: OSX 10.11.4

Steps to Reproduce:

1. Create new `.py` file
2. Start typing `def test():`
3. Press enter

Expected:
Code editor should indent function body.

Actual:
Editor keeps old indention

![python-indent](https://cloud.githubusercontent.com/assets/597158/14682544/e8699d60-06da-11e6-9bf3-5bd179cc73dd.gif)

**Comment by aeschli** [comment]
duplicate of #3754
