### ISSUE TITLE
Default solarized dark theme has wrong foreground color

### ISSUE THREAD

**Issue by purpleP** [Microsoft/vscode#55579]
Seems like it's white, while it should be #839496. Also I can't find any way of changing that.

**Comment by aeschli** [comment]
We took solarized dark from here:
https://colorsublime.github.io/themes/Solarized%20dark/
where the foreground color is `#93A1A1`.

There are other solarized dark themes in the marketplace. I suggest trying these as well. Given that it's easy to use or even create a new theme, we'd rather stick with the current color for the default solarized theme.

You can customize the color with
```
    "workbench.colorCustomizations": {
        "editor.foreground": "#839496",
    }
```
