### ISSUE TITLE
Provide both `pug` and `jade` language

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#55587]
https://github.com/Microsoft/vscode/issues/50086 and https://github.com/Microsoft/vscode/issues/50268 changed the languageId for `jade` and `pug` back and forth, and has caused issues for Vetur for both change:

- https://github.com/vuejs/vetur/issues/812
- https://github.com/vuejs/vetur/issues/840

I suggest keeping two extensions, `pug` and `jade`, like we do for `javascript` and `typescript` grammars.

@aeschli @ramya-rao-a

**Comment by aeschli** [comment]
The change of the language id was in master 2 hours, before I reverted it (see https://github.com/Microsoft/vscode/commits/master/extensions/pug/package.json). How did this cause trouble?
What has changes is the textmate scope. It is now `text.pug`

Two language ids just make things worse for the user experience. There are plenty of extensions that make contributions (e.g. snippets, formatters, previews) for 'jade'. There are also user snippets and language-specific user settings that use the language id.

To do this properly, we could introduce a new `languageIdAlias` property on our language contribution point. The jade language extension would define "languageIdAlias": "pug".
All contribution point handlers that deal with language ids and all language feature registries would have to be updated to merge contributions to the two languages. But we would still break all code that looks for `jade`, (e.g the Vue extension).

That's a lot of swirls and also work that don't think we can justify just for 'pug'.

**Comment by octref** [comment]
> There are plenty of extensions that make contributions (e.g. snippets, formatters, previews) for 'jade'.

There aren't that much. We can ask them to update the extensions and deprecate the usage of languageId `jade` within 2~3 months. The change from `text.jade` to `text.pug` is already breaking, so it doesn't make sense to say the textmate scope could have breaking change but the `languageId` can't — in the end we have inconsistencies.

The renaming happened so there needs to be breaking changes. For example the npm package itself: https://www.npmjs.com/package/jade

> There are plenty of extensions that make contributions (e.g. snippets, formatters, previews) for 'jade'.

On the other hand, if they never get updated, we would have extensions scattered through the marketplace that contributes to the language `jade`, when new users might not even realize `pug` has an old name. And the textmate grammar would refer to `text.pug`.

**Comment by aeschli** [comment]
> The change from text.jade to text.pug is already breaking,
I don't think that's breaking... We don't give out textmate scopes anywhere.

**Comment by aeschli** [comment]
> We can ask them to update the extensions and deprecate the usage of languageId jade within 2~3 months.
We should start that indeed. Extensions should always contribute to both 'jade' and 'pug'.

User snippets and user configurations (language specific settings) will be lost but IMO that's acceptable.

**Comment by octref** [comment]
> I don't think that's breaking... We don't give out textmate scopes anywhere.

This is part of the ext manifest: https://github.com/vuejs/vetur/blob/master/package.json#L98-L115

OK, let's do it.

- [ ] Duplicate current `extensions/pug` extension to `extensions/jade`
  - [ ] Make the scope `text.jade`
  - [ ] Make it contribute a language `jade`
  - [ ] Add a deprecation notice to `extensions/jade/README.md`
- [ ] Update website documentation for jade / pug
- [ ] Update release notes for the deprecation notice

**Comment by aeschli** [comment]
> This is part of the ext manifest: https://github.com/vuejs/vetur/blob/master/package.json#L98-L115
This is a mapping for scopes used _in your grammar_ to a language id. Only if you change the scope (or an include)  in your grammar, you have to change that extension point.
Of course what can happen is that `"include": "source.jade"` can no longer be resolved. But that's to be expected with every import (e.g. `"include": "source.haml"` also doesn't resolve).

I don't think we should bring back the `source.jade` grammar.
We should rather focus on usages of the `jade` language id:
[ ] search all extensions of the marketplace for usages (we have a tool for that)
[ ] file issues against them with the recommendation to always make 2 contributions. One for 'jade' and one for 'pug'.
[ ] we can already create the pug language but that's not really necessary
[ ] once we see enough adoption, we can rename the language id from 'jade' to 'pug'
