### ISSUE TITLE
Lost exception breakpoints

### ISSUE THREAD

**Issue by guycnicholas** [Microsoft/vscode#55589]
Issue Type: <b>Bug</b>

I use the built in NodeJS debugger, and I don't know how I got here, but I have lost the pair of exception breakpoints, "All Exceptions" and "Uncaught Exceptions".  I have searched settings and cannot find anything in reference to breakpoints or exceptions.  Is there a way to restore the breakpoints?

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|/Applications/VS_Code/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
duk-debug|Har|0.4.1
logcat|abh|0.0.7
android-dev-ext|ade|0.5.0
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.59
vscode-eslint|dba|1.4.12
vscode-npm-script|eg2|0.3.5
flow-for-vscode|flo|0.8.2
rest-client|hum|0.19.0
mdhelper|jos|0.0.11
sublime-babel-vscode|jos|0.2.10
azure-account|ms-|0.4.2
cpptools|ms-|0.17.7
csharp|ms-|1.15.2
vsliveshare|ms-|0.3.504
debugger-for-chrome|msj|4.8.2
vscode-code-outline|pat|0.2.1
java|red|0.29.0
vscode-icons|rob|7.24.0
vscode-java-debug|vsc|0.10.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.7.1
vscode-maven|vsc|0.10.0

</details>

**Comment by isidorn** [comment]
They should just reapear once you start debugging some language which supports exception breakpoints.
So for example start debugging node and they should appear. If they do not please let me know and I will reopen this issue

**Comment by guycnicholas** [comment]
I found the actual bug, and perhaps you would rather I update the description above.  I click the debug button and I have the exception bp's. Then in the middle of debugging, I find an issue, edit code and hit the "Restart" button at which point the bp's disappear.  That seems like a bug.

**Comment by guycnicholas** [comment]
Here is a video of it happening
[VSBreakpointVanish.zip](https://github.com/Microsoft/vscode/files/2255484/VSBreakpointVanish.zip)

**Comment by isidorn** [comment]
Thanks for the video, the issue seems to be that the node adapter returns an empty array for the `raw.capabilities.exceptionBreakpointFilters`
Though on the vscode side I could fix it by not removing exception breakpoints so aggresively
Reopening and assingin to august

fyi @roblourens for the node adapter returning empty expcetion breakpoint filters on restart

**Comment by roblourens** [comment]
This was very confusing because the debug adapter is definitely returning the correct thing, according to its log file. Then I realized it doesn't repro when I disable Live Share. Who do we ping for that?

**Comment by isidorn** [comment]
@roblourens the live share team that is wrapping your adapter
File an issue in their repository and close this one imho

**Comment by joelday** [comment]
@isidorn That repo link is 404'ing for me.

**Comment by roblourens** [comment]
It's a private repo, but I filed an issue upstream.
