### ISSUE TITLE
Persistent Markdown Webview

### ISSUE THREAD

**Issue by nealot** [Microsoft/vscode#55582]
With the relatively recent introduction of persistent webviews, would it be possible to allow markdown previews to retain their context when hidden?

**Comment by mjbvz** [comment]
What are you trying to do?

**Comment by mjbvz** [comment]
As the developer of the webview api, I can say pretty clearly that is not a good fit for persistence. Persisting the webview context increases memory overhead and is only meant to be used when a webview absolutely cannot quickly save off and restore its state
