### ISSUE TITLE
Allow to ignore extensions

### ISSUE THREAD

**Issue by outcoldman** [Microsoft/vscode#5558]
## Proposal:

Allow to specify the list of extensions you want to ignore / include in the runtime, when you are opening the folder.

For example, at current moment Microsoft CPP extension always creates `.vscode/.browse.VS.db` in every folder you open. With the allowing to be able to ignore / include extensions I could use something like
### user settings

```
{
    "extensions.extendedConfigurations": {
        "Microsoft:CPP": { "ignore": true }
    }
}
```
### In few projects / folders where I need this extension I may include it by

```
{
    "extensions.extendedConfigurations": {
        "Microsoft:CPP": { "ignore": false }
    }
}
```

This will allow me to have extensions installed, but at the same time load them only in specific folders/projects.

**Comment by alexandrudima** [comment]
I think we have this functionality under the extensions viewlet (via Disable extensions), but it is not in a file.

**Comment by sandy081** [comment]
Yes, you can disable an extension for a workspace or completely from Extensions viewlet.
