### ISSUE TITLE
Find and replace with regular expressions extremely buggy

### ISSUE THREAD

**Issue by ksathya** [Microsoft/vscode#55584]
Issue Type: <b>Bug</b>

I really love VS Code. But for this one buggy feature. I'm not sure it's just me or others too, find and replace with regular expressions is extremely buggy. It is the only bad thing for me with VS Code. The options just don't work according to the documentation. Like for example, you select a block of text and want it to find and replace within the selection, but it replaces in the entire document. This sometimes just keeps happening frustrating me. Can you please check and fix? 

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (0.98GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tomcat|ada|0.10.0
vscode-database|baj|1.5.2
pgformatter|bra|1.3.0
sql-formatter|cym|1.0.2
java-decompiler|dgi|0.0.2
xml|Dot|2.3.1
vscode-install-vsix|fab|1.1.2
gc-excelviewer|Gra|2.1.25
java-properties|ith|0.0.2
vscode-github|Kni|0.30.0
rainbow-csv|mec|0.4.2
anaconda-extension-pack|ms-|1.0.0
python|ms-|2018.7.1
vscode-docker|Pet|0.1.0
vscode-spring-boot|Piv|0.4.0
java|red|0.29.0
vscode-yaml|red|0.0.14
vscode-icons|rob|7.24.0
vscode-java-debug|vsc|0.10.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.7.1
vscode-maven|vsc|0.10.0
vscode-spring-initializr|vsc|0.3.0
vim|vsc|0.15.7
markdown-pdf|yza|1.2.0
markdown-all-in-one|yzh|1.6.0

(2 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
Let's track this issue in https://github.com/Microsoft/vscode/issues/44702
