### ISSUE TITLE
when enter comma or '.', cause wrong code completion.

### ISSUE THREAD

**Issue by liangpure** [Microsoft/vscode#55581]
- VSCode Version:1.25.1
- OS Version: win7/win10

Steps to Reproduce:

1.  coding  `arr.reduce((a,))`  
2.  when I tap ',' cause code completion,editor show 
    `arr.reduce((addEventListener,))`.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by alexandrudima** [comment]
This is pretty weird, why would TypeScript propose `addEventListener` at a parameter name position...

**Comment by akukolu** [comment]
Seems to be the same issue as https://github.com/Microsoft/vscode/issues/47696

Setting `editor.acceptSuggestionOnCommitCharacter` to false worked for me.

**Comment by mjbvz** [comment]
Duplicate of #54386
