### ISSUE TITLE
Find File: File Results have trailiing \ that prevents opening

### ISSUE THREAD

**Issue by derekwallace** [Microsoft/vscode#55593]
- VSCode Version: latest Insiders
- OS Version: Windows 10

This has started to happen.
Ctrl - P
The files names as presented have a trailin `\`.
therefore they dont open .

![image](https://user-images.githubusercontent.com/5574230/43539028-9490f9f0-95bb-11e8-8e45-342abcede205.png)

**Comment by isidorn** [comment]
I do not see what is the issue here. Can you please expain?
Can you reproduce with latest vscode insiders https://code.visualstudio.com/insiders/

**Comment by derekwallace** [comment]
The issue is that the files dont open becuase something is wrong with the stored path .

![image](https://user-images.githubusercontent.com/5574230/43584652-e6265310-965a-11e8-8da7-ecbdbd694bd9.png)

The file doesnt open. this used to work fine upto about 3 days ago.

![image](https://user-images.githubusercontent.com/5574230/43584671-f3c4eefa-965a-11e8-8806-8d0c6841ae83.png)

**Comment by isidorn** [comment]
Can you reproduce with latest vscode insiders?

**Comment by derekwallace** [comment]
yes. using it now. same issue.
very frustrating.

**Comment by isidorn** [comment]
Might this be connected with the workspace refactoring you did @aeschli @sandy081 
My uri display work only affect what we display, not how we open
fyi @bpasero

**Comment by aeschli** [comment]
@derekwallace Is there anything special about the P: drive? How did you open code and that folder?

**Comment by derekwallace** [comment]
Nothing special. It's a network disk. Have been using it for the same vscode workspace for about 7 months. Vscode installed on c: on local machine. 
Open insiders and it auto opens the last workspace.

**Comment by derekwallace** [comment]
the title is possible slightly misleading.  In the image above the cbs.tcl file in the file results seciton, has the path set to \ 
This is not correct as its windows. normally they are relative paths fromt the root of the workspace.
But this may just be a rendering issue.
In the 2nd image the path looks correct, but it says the file does not exist. but it does and the "file results" is form Code finding the file....

**Comment by aeschli** [comment]
You're mentioning that it's a workspace. Can you paste the .code-workspace file here?
If you opened vscode on a single folder, can you attach the `%AppData%\Roaming\Code - Insiders\storage.json` file?

What's really strange is the URI in the error dialog `file://\P:\perforce_playground\`. I wonder how the backspaces got in there. When we create an URI out of a path all `\` are turned into `/`.

**Comment by derekwallace** [comment]
its a workspace. pasting here.

```
`{
   "folders": [
      {
         "path": "P:\\perforce_Playground\\derekw_de02-1777_rce_dev"
      },
   ],

   "settings": {
      // trying to exclude some folders
      // ** means any path under tree
      "files.useExperimentalFileWatcher": true,
      "files.exclude" : {
         ".archive/**" : true,
         ".logarchive/**": true,
         "docs/**": true,
         "**/third_party/**": false,
         "**/thirdparty/**": true,
         "**/venv/**": true,
         "**/__pycache__/**": true,
         "tools/pals/test/src/**": true,
         "training/**": true,
         "**/palsref/**": true
      },

      "python.linting.enabled": false,
      "python.linting.pylintEnabled": true,
      "python.linting.ignorePatterns": [
         ".vscode/*.py",
         "**/site-packages/**/*.py",
         "**/third_party/**/*.py"
      ],
      "python.envFile": "${workspaceFolder}/.env",
      // "python.pythonPath": "C:\\Users\\derekw\\AppData\\Local\\Programs\\Python\\Python36\\python.exe",
      "python.workspaceSymbols.enabled": false,

      // this seems to work it means intellisense is aware of modules in these locations
      // and you can go to defintion etc.
      "python.autoComplete.extraPaths": [
         "P:\\perforce_Playground\\derekw_de02-1777_rce_dev\\tools\\python_lib",
         "P:\\perforce_Playground\\derekw_de02-1777_rce_dev\\tools\\iccr\\bin\\",
         "P:\\perforce_Playground\\derekw_de02-1777_rce_dev\\tools\\iipregr\\bin\\",
         "P:\\perforce_Playground\\derekw_de02-1777_rce_dev\\tools\\vividc\\bin\\",
         "P:\\perforce_Playground\\derekw_de02-1777_rce_dev\\tools\\python_lib\\venv\\lib\\python3.5\\site-packages\\",
      ],

      "python.workspaceSymbols.exclusionPatterns": [
         "**/site-packages/**",
         "**/third_party/**",
         "**/venv/**",
         "**/thirdparty/**",
         "**/.archive/**",
         "**/__pycache__/**",
         "**/auxiliary_scripts/**",
         "docs/**",
         "training/**",
         "**/palsref/**"
      ],

      // Try and get Ctrl-P to find any files in workspace
      "search.useRipgrep": true,
      "search.useIgnoreFiles": false,
      "search.exclude": {
         "**/__pycache__/**": true,
         "**/third_party/**": true,
         "**/venv/**": true,
         "**/thirdparty/**": true,
         "tools/pals/test/src/**": true,
         "auxiliary_scripts/**" :true,
         "docs/**" :true,
         "training/**": true,
         "**/palsref/**": true
      },
      "searchRipgrep.enable": true,




      // Indexing to find files. Ive confirmed
      "folder-indexing.exclude": [
         "*\\bin\\*",
         "*\\obj\\*",
         "*\\.svn\\*",
         "*\\.git\\*",
         "*\\__pycache__\\*",
         "*\\.archive\\*",
         "*\\.log_archive\\*",
         "*\\third_party\\*",
         "*\\venv\\*",
         "*\\thirdparty\\*",
         "*\\common\\*",
         "*\\docs\\*",
         "*.dll",
         "*.exe",
         "*\\auxiliary_scripts\\*",
         "*\\training\\*",
         "*\\palsref\\*"
      ],

   }

}
`
```

**Comment by derekwallace** [comment]
opening the same workspace in 1.25.1  VSCode does not have the issue.

![image](https://user-images.githubusercontent.com/5574230/43738520-d5da9dc6-99bc-11e8-9440-1ceee4c566d5.png)

**Comment by aeschli** [comment]
@derekwallace The problem is in the experimental search ripgrep extension. You have to remove ` "searchRipgrep.enable": true` from the settings in the .code-workspace file.

**Comment by aeschli** [comment]
Adding the candidate flag as the fix is simple. It's an experimental feature, but it seems it used to work.

**Comment by derekwallace** [comment]
confirming that setting` searchRipgrep.enable : false` fixes issue in insiders.
note that the same setting in the production version works fine.

**Comment by roblourens** [comment]
What's wrong with `URI.with`? What's the actual fix? I can repro but I'm still setting up to debug it.

Also, this was filed a week ago, please assign or at least mention me in search issues!

**Comment by roblourens** [comment]
Oh, it's not `URI.with`, it's `path.join` vs `paths.join` where this came from in resources.ts

**Comment by roblourens** [comment]
Since this code is just working with file paths and file folders, it's safe to use fsPath and `Uri.file`

**Comment by aeschli** [comment]
@roblourens Sorry Rob for the late notice, I thought this was related to the changes that I and @sandy081 made on using URI's for workspace folders. I wasn't able to reproduce until today with @bpasero's help.
