### ISSUE TITLE
No error when registering multiple FileIndexProviders with same scheme

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#55597]
Testing https://github.com/Microsoft/vscode/issues/55405

Issue Type: <b>Bug</b>

Expected: An error is thrown when trying to activate the extension, like when registering two `TextDocumentContentProvider`s with the same scheme

Actual: No error, the file provider registered later is used

```ts
    vscode.workspace.registerFileIndexProvider('file', {
        provideFileIndex: async (options: vscode.FileSearchOptions, token: vscode.CancellationToken): Promise<vscode.Uri[]> => {
            return [vscode.Uri.file('Users/ramacfar/dev/vscode-pull-request-github/package.json')];
        }
    });

    vscode.workspace.registerFileIndexProvider('file', {
        provideFileIndex: async (options: vscode.FileSearchOptions, token: vscode.CancellationToken): Promise<vscode.Uri[]> => {
            return [vscode.Uri.file('Users/ramacfar/dev/vscode-pull-request-github/gulpfile.js')];
        }
    });
```

VS Code version: Code - Insiders 1.26.0-insider (573d53815e74f8e4a52c2b6665f5ba9a92dbd341, 2018-08-01T05:23:16.805Z)
OS version: Darwin x64 17.7.0

**Comment by roblourens** [comment]
I don't see an error for

```
    vscode.workspace.registerTextDocumentContentProvider('foo', {});
    vscode.workspace.registerTextDocumentContentProvider('foo', {});
```
?

**Comment by RMacfarlane** [comment]
Yeah, you're right, I also don't seen an error in that case. But I do see it when trying to register one for `'file'` scheme:

![screen shot 2018-08-01 at 11 53 40 am](https://user-images.githubusercontent.com/3672607/43542377-a60f6dcc-9581-11e8-885f-4f7717b989de.png)

**Comment by roblourens** [comment]
It looks like there's a special check for 'file' and 'untitled' to prevent you from trying to overwrite builtin providers but for other schemes, the last one wins. I think other providers like FileSystemProvider are similar.
