### ISSUE TITLE
should `useIgnoreFiles` and `followSymlinks` search options be required?

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#55598]
Issue Type: <b>Bug</b>

Testing https://github.com/Microsoft/vscode/issues/55405

The `useIgnoreFiles` and `followSymlinks` search options seem to always be sent for every type of search provider. Should these be marked as required on the `SearchOptions` interface?

VS Code version: Code - Insiders 1.26.0-insider (573d53815e74f8e4a52c2b6665f5ba9a92dbd341, 2018-08-01T05:23:16.805Z)
OS version: Darwin x64 17.7.0

**Comment by RMacfarlane** [comment]
@roblourens `maxResults` seems to be actually optional, it's not returned for `provideFileIndex`

**Comment by roblourens** [comment]
That actually shouldn't be on the common query options, good catch
