### ISSUE TITLE
Single numbers entered will double after losing and regaining vs code focus

### ISSUE THREAD

**Issue by freddyouellette** [Microsoft/vscode#55590]
- VSCode Version: 1.25.1
- OS Version: MacOS X El Capitan 10.11.6

Steps to Reproduce:

1. Have a single number in code. Like just a single '1'.
2. Put your cursor directly after the 1.
3. Move focus away from VSCode (e.g. via Alt-Tabbing)
4. Move focus back to VSCode (Alt-Tab back)
5. Type the same number ( 1 ). 2 number 1s are placed instead of only 1 - it will now read '111'. 
6. If you do this again and again, the number of repeats will get bigger by a factor of `n*2+1` => 1, 111, 1111111, 111111111111111, 1111111111111111111111111111111, 111111111111111111111111111111111111111111111111111111111111111, [...]

This is if you alt-tab away & back, and just type the same number that was before.
This will work for symbols and single numbers.

Does this issue occur when all extensions are disabled?: Yes/No
Yes.

p.s. the least you could do was make it a fibonacci sequence or something instead of n*2+1

**Comment by isidorn** [comment]
I can not reproduce this behavior with latest vscode insiders.
Can you reproduce with latest vscode insiders https://code.visualstudio.com/insiders/
Can you reproduce with no extensions?
