### ISSUE TITLE
"Ignore Recommendation" makes all workspace recommendations go away

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#55596]
- Open a workspace with recommended extensions e.g. vscode
- See the 3 recommended extensions in the viewlet
- Click Debugger For Chrome, click "Ignore Recommendation"
- All 3 workspace recommendations disappear :bug:
- Refresh the viewlet, now just 2 recommendations appear ✔️

**Comment by ramya-rao-a** [comment]
@roblourens I am guessing this only happens when you are in the recommended view (i.e extensions viewlet has 2 sections, 1 for workspace recommendations and other for well.. other recomemndations) ?

**Comment by JacksonKearl** [comment]
This is related to the changes made to reduce errors while offline.. changing https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/extensions/electron-browser/extensionsViews.ts#L804 back to how it was before seems to fix this.

**Comment by ramya-rao-a** [comment]
This is a regression.
