### ISSUE TITLE
On windows, the terminal with powershell starts in wrong directory

### ISSUE THREAD

**Issue by graph** [Microsoft/vscode#55592]
Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:43:53.668Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

Steps to Reproduce:

1. Open folder
2. Goto terminal tab

expected behavior:

To be already cd'd into directory I opened.

Actual Results:

It's in the top level directory `\`.

This happens with powershell on windows. On mac/linux it seams to work fine across the various shells I have used.

**Comment by Tyriar** [comment]
Are you using the powershell extension?

**Comment by graph** [comment]
no I'm not using power shell or any terminal related extensions. The default value in vscode for shell is

```
// The path of the shell that the terminal uses on Windows. When using shells shipped with Windows (cmd, PowerShell or Bash on Ubuntu).
  "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
```

I changed it to 

```
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",
```

and regular cmd works fine.

**Comment by Tyriar** [comment]
@graph does `C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe` exist? @tylerl0706 might know more

**Comment by tylerl0706** [comment]
Yeah that's where Windows PowerShell lives - the one that ships in Windows. It's been there forever AFAIK.

**Comment by graph** [comment]
This issue still exists on latest vs code 

Version: 1.27.1 (system setup)
Commit: 5944e81f3c46a3938a82c701f96d7a59b074cfdc
Date: 2018-09-06T09:21:18.328Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64


I see it's labeled as more info.  tyler0706 is correct that path exists. I really would like to use powershell instead of cmd.exe.

**Comment by tylerl0706** [comment]
Oh this issue is not about starting PowerShell, it's about making sure PowerShell is cd'd into the correct directory.

@Tyriar do you know how you guys are passing the path of the opened workspace down to PowerShell?

**Comment by Tyriar** [comment]
@tylerl0706 oh, opps 😅 

We're setting the cwd of the process to do that:

https://github.com/Microsoft/vscode/blob/6c733bab057ec3c76e015fabcf85a9fa27ab64a7/src/vs/workbench/parts/terminal/node/terminalProcess.ts#L46-L54

https://github.com/Microsoft/node-pty/blob/e03567473cb1da907fc88ac116cd599707e66ef5/src/windowsPtyAgent.ts#L46-L52

Also this has always worked for me for powershell, I don't use the PS ext though, not sure if the OP does.

**Comment by tylerl0706** [comment]
Yeah that works for me too... As does the PS ext.

I wonder if there's anything special about OPs path that they're trying to open.

**Comment by graph** [comment]
When I start powershell manually by typing it into the command line it always starts in the top level "\" directory. Maybe my powershell is buggy.

**Comment by graph** [comment]
I don't know what the issue was I deleted my powershell settings and everything is working just fine now.
