### ISSUE TITLE
wiki changes: how to fork wiki and submit a PR against it

### ISSUE THREAD

**Issue by mackenza** [Microsoft/vscode#556]
I cannot seem to figure out how you can fork the wiki and submit a PR with my changes. I can clone the wiki and can manually create a remote on GH but I don't see how GH lets me submit a PR against a non-code branch (the wiki).

Idea? Process?

**Comment by Tyriar** [comment]
I also hit this and gave up because it wasn't worth the effort for the change.

**Comment by chrisdias** [comment]
removed the footer.
