### ISSUE TITLE
"Focus on Outline" doesn't focus outline when another viewlet is active

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#55607]
- Set 

```
{
  "key": "shift+cmd+o",
  "command": "outline.focus"
}
```

- Focus search viewlet
- Press cmd+shift+o
- Explorer is focused
- Press cmd+shift+o again
- Now the outline is focused

**Comment by sandy081** [comment]
@jrieken OutlinePanel.focus is called from outside but you are setting focus on tree. Don't know if the tree is visible or not at that time. 

![image](https://user-images.githubusercontent.com/10746682/44737096-52ee7680-aaf1-11e8-926e-dad7e72ec4de.png)
