### ISSUE TITLE
Light themes (and some others) do not recognize all python keywords

### ISSUE THREAD

**Issue by outcoldman** [Microsoft/vscode#5560]
- VSCode Version: 1.0.0
- OS Version: OSX 10.11.4

Steps to Reproduce:

1. Sample code

```
a = {}
if "a" not in a:
    pass
```

Expected `not` and `in` should be recognized as keywords in all themes, but looks like only imported from Textmate (like monokai) are recognize them as keywords.

![python-themes](https://cloud.githubusercontent.com/assets/597158/14683226/7573cf7a-06de-11e6-8821-f0655cdc4c22.gif)

**Comment by aeschli** [comment]
The python tokenizer uses the scope `keyword.operator` for `not` and `in` as well as for other operators such as `+` and `=`
In the VS default themes (light and dark) we chose to color these with the background color. 
I'd recommend you to use e.g. Monokai or Solorize Light if you prefer the coloring of the operators.

**Comment by johncruise** [comment]
I'm new at this and so... is there any way to manually modify the other themes to add those keywords and other operators?

**Comment by johncruise** [comment]
Looks like editing <codefolder>/resources/app/extensions/theme-defaults/themes/* ... and adding "keyword.operator.logical.python" to one of the scope would do the trick.  However, the next update would squash this so backup or put it somewhere else (??).
