### ISSUE TITLE
How i can disabled Outline view? This function very slowly job with live editing big file postcss (scss,css) 6000+ rows.

### ISSUE THREAD

**Issue by tony-show** [Microsoft/vscode#55608]
Hello thare!

I have trable very, very slow editing, when i get started editing my big postcss (scss nested, css style) file (6000+ rows, meny nested { { {} } }). This trable have, when outline wiev tab load new symbols when live editing.

I don't need outline view, how i can disabled this function in vs code (version 1.26)?

**Comment by isidorn** [comment]
Just hide the outline view. Right click -> hide
