### ISSUE TITLE
Performance enhancer for WSL terminal in VSC

### ISSUE THREAD

**Issue by n0l0cale** [Microsoft/vscode#55610]
Hi all,

I'm using the Windows Subsystem for Linux and the only useable terminal to this system is the VSC integrated terminal interface....

Shame on the developers of the bash.exe application.
Hooray on VSC Developers.

However since I've been using it more and more I have some performance issues and sometimes even VSC itself seems to find the application unresponsive, as it suggests me to close / reopen the window. Working is still possible....

Do you have any cheat-sheet what exactly to tweak to get the best performance out of that VSC-part?
Cheers,
S.

**Comment by Tyriar** [comment]
@n0l0cale you might be having issues with the terminal rendering, you could try tweaking settings:

```
"terminal.integrated.rendererType": "dom"
```

Or try launching with `code --disable-gpu`, I'd be interested to hear if either of these work for you.

**Comment by n0l0cale** [comment]
hi Tyriar,

THANKS for your quick reply!
actually with the rendererType dom the output is even much more slower
--disable-gpu seems to make no difference at all...

Cheers,
S.

**Comment by Tyriar** [comment]
I think you're probably seeing https://github.com/Microsoft/vscode/issues/53782
