### ISSUE TITLE
Remote fish shell rendering wrongly.

### ISSUE THREAD

**Issue by 9d77v** [Microsoft/vscode#55614]
Issue Type: <b>Bug</b>

When using remote fish shell terminal,the rendering can not work normaly.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

![qq 20180802080243_meitu_1](https://user-images.githubusercontent.com/8814495/43555081-b8be4cb4-962a-11e8-8418-ce13e1709b30.jpg)

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
