### ISSUE TITLE
findTextInFiles sometimes doesn't return when cancelled

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#55612]
Promises are not passed around correctly, and cancelling findTextInFiles can sometimes cause it to never resolve.

**Comment by roblourens** [comment]
Verification, just try something like 

```
const cancellation = new vscode.CancellationTokenSource();
cancellation.cancel();

await vscode.workspace.findTextInFiles({ pattern: 'foo' }, result => {
    results.push(result);
}, cancellation.token);
console.log('done')
```

run it a few times, make sure it always gets to 'done'.

**Comment by JacksonKearl** [comment]
How do I get the proposed api?

**Comment by JacksonKearl** [comment]
Okay I just ignored the compilation error and it seemed to work.

**Comment by roblourens** [comment]
👍 Alternately, copy vscode.proposed.d.ts into your extension manually.
