### ISSUE TITLE
Settings editor should show "no results" when searching

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#55615]
- Do a search that returns no results
- Weird empty screen

**Comment by deadcoder0904** [comment]
Glad that VSCode Bot works & provides relevant results otherwise I was opening same issue 😂

**Comment by misolori** [comment]
@roblourens that's exactly what I had in mind, keep it simple/consistent

**Comment by roblourens** [comment]
![image](https://user-images.githubusercontent.com/323878/44426586-e0efbd80-a543-11e8-89db-99b3b0cf93f7.png)

👍
