### ISSUE TITLE
Strange flashing in explorer names during file rename

### ISSUE THREAD

**Issue by JacksonKearl** [Microsoft/vscode#55613]
Issue Type: <b>Bug</b>
![weirdfalshing](https://user-images.githubusercontent.com/8586769/43554955-5510da5c-95ac-11e8-8f59-b65f027af644.gif)

VS Code version: Code - Insiders 1.26.0-insider (573d53815e74f8e4a52c2b6665f5ba9a92dbd341, 2018-08-01T05:17:54.216Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (5.81GB free)|
|Process Argv|C:\Users\t-jakea\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.0.3
vscode-svgviewer|css|1.4.4
gitlens|eam|8.5.4
tslint|eg2|1.0.34
debugger-for-chrome|msj|4.8.2
subtle-brackets|raf|2.1.1
vscode-multiclip|sle|0.1.4
code-spell-checker|str|1.6.10
sublime-commands|Zar|0.1.0

</details>

**Comment by isidorn** [comment]
What a strange bug. I can repro

**Comment by isidorn** [comment]
Closing as out of scope
@joaomoreno feel free to reopen if you are interested from a tree persepctive
