### ISSUE TITLE
The code is hidden

### ISSUE THREAD

**Issue by hankaibo** [Microsoft/vscode#55618]
- VSCode Version:1.25.1
- OS Version:Windows 10 Pro N 1803

Steps to Reproduce:

1.Sometimes the code is hidden and can't be seen,as follow:
2.
![capture](https://user-images.githubusercontent.com/5361465/43558992-93896000-963e-11e8-84b8-f26f8517092a.PNG)
3.some of the line numbers are lost and I don't collapse them.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by hankaibo** [comment]
These are my plugins:
![capture](https://user-images.githubusercontent.com/5361465/43559349-55513176-9640-11e8-8703-3742ea76512e.PNG)

**Comment by aeschli** [comment]
That looks very strange.
When you hover over the line numbers, you don't see any collapse items?

**Comment by hankaibo** [comment]
Yes,I can't see any collapse items when my mouse hover over the line numbers.
