### ISSUE TITLE
"html.format.contentUnformatted" doesn't apply when paste <pre> HTML

### ISSUE THREAD

**Issue by doggy8088** [Microsoft/vscode#55626]
- VSCode Version: 1.25.1
- OS Version: Windows 10 1803 (OS Build: 17134.165)

Steps to Reproduce:

1. Copy the following HTML snippet:

```
          <pre>f.valid = {{f.valid|json}}
f.invalid = {{f.invalid|json}}
f.touched = {{f.touched|json}}
f.untouched = {{f.untouched|json}}
f.dirty = {{f.dirty|json}}
f.pristine = {{f.pristine|json}}
f.enabled = {{f.enabled|json}}
f.disabled = {{f.disabled|json}}
f.errors = {{f.errors|json}}
f.value = {{f.value|json}}</pre>
```

2. Paste it to any HTML document

Does this issue occur when all extensions are disabled?: Yes

Expected result:

```
<pre>f.valid = {{f.valid|json}}
f.invalid = {{f.invalid|json}}
f.touched = {{f.touched|json}}
f.untouched = {{f.untouched|json}}
f.dirty = {{f.dirty|json}}
f.pristine = {{f.pristine|json}}
f.enabled = {{f.enabled|json}}
f.disabled = {{f.disabled|json}}
f.errors = {{f.errors|json}}
f.value = {{f.value|json}}</pre>
```

Actual result:

```
<pre>f.valid = {{f.valid|json}}
        f.invalid = {{f.invalid|json}}
        f.touched = {{f.touched|json}}
        f.untouched = {{f.untouched|json}}
        f.dirty = {{f.dirty|json}}
        f.pristine = {{f.pristine|json}}
        f.enabled = {{f.enabled|json}}
        f.disabled = {{f.disabled|json}}
        f.errors = {{f.errors|json}}
        f.value = {{f.value|json}}</pre>
```

Additional Notes:

* I confirmed my `"html.format.contentUnformatted": "pre,code,textarea"` is using default setting.  The `pre` tag should leave formating AS-IS even paste clipboard into any HTML document.

**Comment by aeschli** [comment]
That's caused by the `"editor.autoIndent": true` setting. The indent on paste is not using the formatter (and thus not the settings), but just the HTML indentation rules.

You can turn that off, also just for HTML, with
```json
"[html]": {
    "editor.autoIndent": false
  }
```

**Comment by doggy8088** [comment]
@aeschli Thanks! 👍

**Comment by doggy8088** [comment]
@aeschli By the way, is this possibly an issue to be fixed?  When dealing with `<pre>`, `<code>` or `<textarea>` tag in the HTML, the Auto Indent feature should/may consider under this circumstance?
