### ISSUE TITLE
Bug when formatting html elements

### ISSUE THREAD

**Issue by TianxinTse** [Microsoft/vscode#55621]
Here is an example:
```
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
</head>
```
If the last child element has no closing tag, formatting the document above will produce:
```
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge"></head>
```

---
```
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>document</title></head>
```
If the last child element does have a closing tag, formatting the document above will produce:
```
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>document</title>
</head>
```
---

- VSCode Version: 1.25.1
- OS Version: Windows 10 Version 1803
- Installed Related Extensions: Beautify

Steps to Reproduce:

1. Open any html files.
2. Use shortcut to format the document.

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
We use [beautifyjs](http://jsbeautifier.org/) as the underlying HTML formatter. Would you mind filing this request directly against https://github.com/beautify-web/js-beautify ?
Thanks a lot!
