### ISSUE TITLE
Menu items missing

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#55624]
c86cab2211d6dce686e5c89934d915b1e020ba9e
refs/heads/master 1.26.0-insider 1.26.0-1533187298

Elementary OS (Ubuntu 16.04)

File and About menus are missing.

![image](https://user-images.githubusercontent.com/6461412/43566805-f333ca2c-962f-11e8-9650-1f47768e295b.png)

**Comment by bplasmeijer** [comment]
same here

**Comment by borgdylan** [comment]
Same thing for the zip file build on Ubuntu 18.04.

**Comment by peterfsymdist** [comment]
Same issue here on Linux Mint 18 with latest built via repo

**Comment by neryuuk** [comment]
Same here...
![image](https://user-images.githubusercontent.com/966712/43594758-68804a8c-9651-11e8-8180-9d6e2e3c908c.png)

VS Code version: Code - Insiders 1.26.0-insider (c86cab2211d6dce686e5c89934d915b1e020ba9e, 2018-08-02T05:18:18.450Z)
OS version: Ubuntu 18.04.1 LTS (Linux x64 4.15.0-29-generic)

**Comment by sbatten** [comment]
fixed via https://github.com/Microsoft/vscode/commit/02822bf5c356612dc41ddbb3daf9e32ac7440f31

**Comment by wsmelton** [comment]
Interesting tidbit that I'm not sure if it was tested but changing my menu title bar to custom brings both menus back..

![image](https://user-images.githubusercontent.com/11204251/43619424-5d1e07e6-9693-11e8-9fa9-5b5d4c547e07.png)

**Comment by Raydir** [comment]
@wsmelton thanx, that seem to work for me too as a workaround.

**Comment by aeschli** [comment]
Verified in 1.26.0-insider
Commit: 0c2d71e2bb9a020995729ab7d5d5f8e4e897e657
Date: 2018-08-03T05:18:02.899Z
