### ISSUE TITLE
C# does not autocomplete closing quotation 

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5562]
- VSCode Version: 1.0.1-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Open a c# file and start typing a method that accepts a string.
2. Console.WriteLine( Type a " here

Actual:
Does not autocomplete the ending ". This is not the behavior of Visual Studio 2015.

**Comment by jrieken** [comment]
@vsccarl Stop filing C# issues in this repository. The correct repository is https://github.com/OmniSharp/omnisharp-vscode
