### ISSUE TITLE
QTabBar with Reveal in Explorer Causes VS Code to Lag Seriously

### ISSUE THREAD

**Issue by JohnTravolski** [Microsoft/vscode#55628]
- VSCode Version: 1.25.1
- OS Version: Windows 10 17134

Steps to Reproduce:

1. Have File Explorer open already at any arbitrary directory
2. Open up any file in Visual Studio Code (even the settings file for the matter)
3. Click "Reveal In Explorer" on that file's tab.
4. The file will open up in explorer immediately, but Visual Studio code will be completely unresponsive for approximately 15 seconds
5. After this time has elapsed, another file explorer window will open at the corresponding directory, and then VS code will be accessible again.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
I can not reprodcue this. Can you reproduce with latest vscode insiders https://code.visualstudio.com/insiders/

**Comment by isidorn** [comment]
Thanks for the investigation. However we have no immediate plans to look into this. Let's see if more users hit this issue

**Comment by JohnTravolski** [comment]
Okay, well it's definitely something to do with QTTabBar's "Capture Window" feature; with that disabled, it also goes away.  Since there doesn't seem to be much I can do about it, I'll just use an AutoHotKey script in the meantime.  For anybody interested, here it is:

```
#!7::
ClipSaved := ClipboardAll   ; Save the entire clipboard to a variable of your choice.

Send +!c ; make sure you set your VS code preference so that this shortcut always works instead of just whenever the editor isn't active (the default)
Sleep, 50 ; gotta give VS code some time to respond you know!
VScodefilepath = %Clipboard%
SplitPath, VScodefilepath,, dir

Run, "%dir%"

Clipboard := ClipSaved
ClipSaved =   ; Free the memory in case the clipboard was very large.
Return
```

This is a good workaround for me until either QTTabBar or VSCode fixes whatever needs to be fixed.  I'm not sure if either will ever happen, but this script is fine with me.

**Comment by guillaume86** [comment]
I have the same issue. I doubt is going to be enough to reopen the issue, and open to change solution for tabbed explorer if anyone got an better alternative?

**Comment by yyb1995** [comment]
Disable Capture Window feature in QTTabBar really works. Thanks!

**Comment by guillaume86** [comment]
Here's the upstream issue I created: https://github.com/electron/electron/issues/15321
