### ISSUE TITLE
Snippet variable transformation doesn't work if regex is complicated and snippet body contains '$$'

### ISSUE THREAD

**Issue by yvesyao** [Microsoft/vscode#55627]
Issue Type: <b>Bug</b>

1. Add custom snippet in javascript.json.

```json
"with dollar": {
	"prefix": "withdollar",
	"body": [
		"const fileName = '${TM_FILENAME/(.*)\\..+$/$1/}';",
		"let $$wrapper;",
	]
},
"without dollar": {
	"prefix": "withoutdollar",
	"body": [
		"const fileName = '${TM_FILENAME/(.*)\\..+$/$1/}';",
		"let wrapper;",
	]
},
```
2. Use snippet in a js file, the result is as follow.

```js
//with dollar
const fileName = 'abc.js';
let $wrapper;

// without dollar
const fileName = 'abc';
let wrapper;
```

3. But simple regex still works:

```json
"with dollar": {
	"prefix": "withdollar",
	"body": [
		"const fileName = '${TM_FILENAME/(.*)/${1:/upcase}/}';",
		"let $$wrapper;",
	]
},
```

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:03:31.083Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.34GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.59
javascript-ejs-support|Dig|0.3.2
vsc-material-theme|Equ|2.3.0
autofilename|Jer|0.1.3
vscode-language-pack-zh-hans|MS-|1.23.5
material-icon-theme|PKi|3.5.2
code-settings-sync|Sha|3.0.0
sonarlint-vscode|Son|1.4.0
jsx|Twe|0.0.1
sort-lines|Tyr|1.7.0
sublime-commands|Zar|0.1.0
better-comments|aar|1.2.6
html-snippets|abu|0.2.1
project-manager|ale|8.0.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
regex|chr|0.2.0
vscode-svgviewer|css|1.4.4
vscode-eslint|dba|1.4.12
es7-react-js-snippets|dsz|1.8.5
gitlens|eam|8.4.1
vscode-npm-script|eg2|0.3.5
vscode-mocha-test-adapter|hbe|1.0.2
vscode-test-explorer|hbe|1.1.0
useful-react-snippets|igo|1.4.4
search-node-modules|jas|1.3.0
NodeAssertionSnippets|jay|0.1.0
graphql-for-vscode|kum|1.12.1
markdown-shortcuts|mdi|0.8.1
vscode-stylefmt|mrm|2.5.0
sublime-keybindings|ms-|4.0.0
vscode-code-outline|pat|0.2.1
polacode|pnp|0.2.2
nunjucks|ron|0.2.3
vscode-coverage-gutters|rya|2.1.0
stylelint|shi|0.38.1
vscode-table-formatter|shu|1.2.1
css-auto-prefix|spo|0.1.4
rewrap|stk|1.9.1
code-spell-checker|str|1.6.10
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.7.0

(1 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
This happens because the snippets get rewritten because of the `$$wrapper` part. @yvesyao The `$wrapper` part is actually a variable reference in Textmate. Because that variable doesn't exist it is being rewritten to a placeholder. Use `\$wrapper` instead.
