### ISSUE TITLE
after window OS update，the toggle terminal shortcut doesn't work.

### ISSUE THREAD

**Issue by cddsgtc** [Microsoft/vscode#55638]
## my os version
![update](https://user-images.githubusercontent.com/16315661/43574503-f1b241b4-9676-11e8-82c9-6fcedac86474.png)

## this is my vscode keyboard shortcut doc line
![_20180802170829](https://user-images.githubusercontent.com/16315661/43574543-0b839656-9677-11e8-9525-875ec5f3a064.png)

This has been the case in the past, but it was quickly repaired in the next upgrade of the system.
But this time it happened again.
I don't know if I'm alone. I didn't change any of the editor's settings, but I upgraded the system last weekend, and that's it.

**Comment by isidorn** [comment]
This is as desgined. Use a different shortcut, the hover should nicely explain that key is no longer avilable on your system for some reason (non vscode related)

**Comment by cddsgtc** [comment]
@isidorn 
thank you for your words.
I decided to change my own first.
