### ISSUE TITLE
Insiders 'File' and 'Help' is missing in nightly build

### ISSUE THREAD

**Issue by jsacapdev** [Microsoft/vscode#55633]
- VSCode Version: Cant tell you because the help option is missing (see below)
- OS Version: Cant tell you because the help option is missing (see below)

Steps to Reproduce:

1. Open VSCode

![image](https://user-images.githubusercontent.com/10151920/43571236-5bd7296c-9634-11e8-900b-8663022e73cd.png)

One that works

![image](https://user-images.githubusercontent.com/10151920/43571269-73281f2c-9634-11e8-968a-7c7aede481fd.png)

**Comment by mjbvz** [comment]
Duplicate of #55624
