### ISSUE TITLE
Handlebars syntax highlighting missing from Markdown files

### ISSUE THREAD

**Issue by ChrisBAshton** [Microsoft/vscode#55635]
- VSCode Version: 1.25.1
- OS Version: OSX 10.12.3

Steps to Reproduce:

1. Create a Markdown file
2. Use the `hbs` extension in a code snippet - it is missing syntax highlighting

\```hbs
{{> test foo='bar' }}
\```

Example:

<img width="335" alt="screen shot 2018-08-02 at 10 05 12" src="https://user-images.githubusercontent.com/5111927/43574248-96b160f0-963b-11e8-8ca6-21d86430dadd.png">

I'm currently working around the issue by specifying jsx instead:

<img width="360" alt="screen shot 2018-08-02 at 10 05 19" src="https://user-images.githubusercontent.com/5111927/43574296-b4447cb0-963b-11e8-925b-19c4c95d90f9.png">

Viewing `.hbs` files directly works ok:

<img width="219" alt="screen shot 2018-08-02 at 10 06 37" src="https://user-images.githubusercontent.com/5111927/43574319-c7ab0062-963b-11e8-9de8-4e18c6949238.png">

Thanks for an otherwise really awesome IDE!

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/vscode-markdown-tm-grammar#24
