### ISSUE TITLE
VS Code resets keyboard layout

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [Microsoft/vscode#5563]
- VSCode Version: 1.0.0
- OS Version: Ubuntu 15.10, 16.04 (Cinnamon DE)

Steps to Reproduce:
1. Open Visual Studio Code

VS Code resets keyboard layout to "es"

I also recorded video: https://youtu.be/aZX5QGP-t0g

**Comment by dbaeumer** [comment]
@alexandrudima don't know where to start :-). Since the editor has a native keyboard module I start with you. But could be an electron bug as well. @bpasero does this ring any bell to you?

**Comment by bpasero** [comment]
No ringing.

**Comment by alexandrudima** [comment]
@DaFri-Nochiterov I could not reproduce this.

I have set up the English (US) and Russian kb layouts on Ubuntu 16.04 LTS:

![ubuntu-kb](https://cloud.githubusercontent.com/assets/5047891/23470300/5460d614-fea6-11e6-81e1-c41046996714.gif)

**Comment by DaFri-Nochiterov** [comment]
I don't use Linux anymore, sorry. So I can't say it fixed or not. It could be an Elector bug as said before. You can freely close this issue if you need.
