### ISSUE TITLE
Make pasted data match indentation of destination

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/vscode#55642]
I have a file that happens to be using tabs:

![image](https://user-images.githubusercontent.com/172594/43577603-2da2e148-9644-11e8-8eab-e3f2f3183b52.png)

When I paste something that's indented with spaces, VScode leaves the space indentation in then marks it as incorrect. 

![image](https://user-images.githubusercontent.com/172594/43577589-256bbd92-9644-11e8-87dd-0203c99c59bf.png)

I then have to fix the space indenation in the otherwise tab indented file by converting everything to tabs again.

I'd consider it a UX bug, but hey, I know someone will move it to feature request so let's not argue. 😀

**Comment by rebornix** [comment]
Thanks for reporting, I may want to call it `under-discussion` instead of `feature-request` 😃  Thanks for your code sample, I'll do some investigation into it.

**Comment by mikemaccana** [comment]
Thanks @rebornix!

**Comment by rebornix** [comment]
Looking into this again, VS Code editor doesn't convert spaces in the pasted content when pasting into a file using tabs, it's arguable if the auto indentation should change that aggressively. Considering the limitation of regex based auto indentation, we are not going to make any change right now.

For the error squiggle, it's contributed by an extension so it's out of VS Code's control.
