### ISSUE TITLE
RG 700% CPU usage 

### ISSUE THREAD

**Issue by reggiew2** [Microsoft/vscode#55649]
Issue Type: <b>Bug</b>

I found an issue where RG 700% CPU usage when I have my home dir open and expanded. I did this so I can easly access files. When I open to a different folder like desktop the issue goes away. I have repoed with all extensions disabled. 

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 7|
|Memory (System)|16.00GB (3.79GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.12
xml|Dot|2.3.1
gitlens|eam|8.5.4
json-tools|eri|1.0.2
code-runner|for|0.9.3
python|ms-|2018.7.1
PowerShell|ms-|1.8.2
vscode-icons|rob|7.25.0
propertylist|zho|0.0.2

</details>

**Comment by reggiew2** [comment]
This bug is repo without any extensions enabled.

**Comment by isidorn** [comment]
Can you please give us reproducable steps so we can try to look into this?
What does RG stand for?

**Comment by reggiew2** [comment]
The repo steps is open the home folder on a mac then expand it on the UI. RG is what shows up on Activity Monitor. I had no other files open in the main window.

**Comment by isidorn** [comment]
Sounds like rip grep.
I can not repro

**Comment by reggiew2** [comment]
ok, I was wrong before, sorry about that. The RG issue is caused by vscode-icons. However I also found an issue with Code by itself. The CPU goes to 100%+ when the home folder is open. I have a video of the issue and going through the RG issue with Activity Monitor on screen. https://citrix.sharefile.com/d/s09e54c7c59d4833a

**Comment by garthk** [comment]
I'm seeing this also. At each reload, I get another copy of VS Code's ripgrep running away with as much `%CPU` as it can get and slowly gaining `%MEM`. `ps auxww` shows the `COMMAND`:

    /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --files --hidden --case-sensitive -g **/tsconfig.json -g **/jsconfig.json -g **/tsconfig.*.json -g **/jsconfig.*.json --no-ignore --follow --quiet -- .

VS Code does not kill the process as it quits.

**Comment by garthk** [comment]
* Reproduced 29 times while disabling extensions one at a time to see if any of them were the culprit
* Happens even if no editors are open
* **Workspace specific:** 
  - doesn't happen if I close that workspace and open another
  - does happen if I close the other workspace and re-open the first
  - still happens if I empty out that workspace's `.vscode`
  - still happens if I ⌘⇧P `Clear Editor History`
  - still happens if I ⌘⇧P `Clear Command History`
  - still happens if I ⌘⇧P `File: Clear Recently Opened`
* VS Code 1.26.0
* macOS 10.13.6

Any other diagnostic steps I can try?

**Comment by garthk** [comment]
Is this #55649?

**Comment by garthk** [comment]
Is this #34711? This workspace has 521756 files after `npm install`. Long story.

**Comment by reggiew2** [comment]
@garthk The RG issue is caused by vscode-icons. Once I removed it all is good.

**Comment by garthk** [comment]
@reggiew2 I'm getting matching symptoms without `vscode-icons`.

**Comment by zzarcon** [comment]
I can confirm I'm having the same issue since the 1.26.0 update. I disabled all my extensions and CPU still goes above 600%

**Comment by roblourens** [comment]
Please try this

- Search `@builtin` in the extension viewlet
- Under the "Features" section find the "Typescript and JavaScript Language Features" extension
- Disable it

**Comment by zzarcon** [comment]
Thanks @roblourens. Disabling the **TypeScript and JavaScript Language Features** extension does the trick.

Is there any other workaround we can use currently in order to override the **workspaceContains** prop of the extension?

Disabling the **TypeScript and JavaScript Language Features** extension removes a lot of value from VScode 💔.

Thanks for the solution in the meantime!

**Comment by chrmarti** [comment]
Merging @roblourens 's fix for 1.26.1.

**Comment by DanTup** [comment]
@roblourens 

> Is the workspaceContains activation event necessary? Can you activate on onLanguage:json instead?

I'm using workspaceContains in Dart to activate when opening a Dart project (pubspec.yaml or .dart file):

```js
"activationEvents": [
		"onLanguage:dart",
		"onView:dartPackages",
		"workspaceContains:**/pubspec.yaml",
		"workspaceContains:**/*.dart",
		"onCommand:flutter.createProject",
		"onCommand:flutter.doctor"
],
```

Is this bad, should I avoid it?

**Comment by roblourens** [comment]
No, you don't need to avoid it - we are improving it in https://github.com/Microsoft/vscode/issues/34711.
