### ISSUE TITLE
customized `ctrl+k` in terminal not work

### ISSUE THREAD

**Issue by XadillaX** [Microsoft/vscode#55643]
- VSCode Version: 1.25.1
- OS Version: macOS 10.13.6

Steps to Reproduce:

1. configuration of **keybindings.json**:

```json
[{
  "key": "ctrl+l",
  "when": "explorerViewletFocus && explorerViewletVisible",
  "command": "workbench.action.focusFirstEditorGroup"
}, {
  "key": "- ctrl+l",
  "command": "docthis.documentThis",
  "when": "editorTextFocus && vim.mode != 'Insert'"
}, {
  "key": "ctrl+k",
  "command": "workbench.action.focusAboveGroup"
}, {
  "key": "ctrl+k",
  "command": "workbench.action.focusAboveGroup",
  "when": "terminalFocus"
}]
```

2. When I in terminal, `ctrl+k` didn't work. It will work if I changed the `key` to `cmd+k` and I pressed `cmd+k`.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
You need to configure the setting `terminal.integrated.commandsToSkipShell` to bind ctrl+k.
