### ISSUE TITLE
Regression: Code fails to tokenize files

### ISSUE THREAD

**Issue by borgdylan** [Microsoft/vscode#5564]
- VSCode Version: 1.0.1-insider
- OS Version: Ubuntu 15.10 on Linux 4.2

Steps to Reproduce:

1. Open code and load a folder.
2. Observe 'The mode has failed while tokenizing the input.' in a message on opening a file.
![code1 0 1-regression](https://cloud.githubusercontent.com/assets/7761010/14686212/fe2ea35e-0737-11e6-8008-5e9ba7abcba3.png)

**Comment by borgdylan** [comment]
To clear stuff up: this happens on any file I tried to open.

**Comment by borgdylan** [comment]
It was a mix up: updating by just overwriting yields a broken install, deleting teh isntall and unzipping afresh in the emptied folder fixes the issue.

**Comment by luisantoniojr** [comment]
I had the same issue, thanks borgdylan! Works on arch linux.
