### ISSUE TITLE
settings UI: show deprecated settings when set

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#55646]
- In the user settings add `"scss.colorDecorators.enable": false,`
- The `"scss.colorDecorators.enable"` setting does not show the new settings editor.

`scss.colorDecorators.enable` is marked as deprecated. It is therefore hidden in code completion in settings.json, but gets a hover and a warning when used.

IMO the new settings editor should only show it when set and also show the deprecation warning.

**Comment by JacksonKearl** [comment]
Closed in #55977
