### ISSUE TITLE
not be able to input in terminal

### ISSUE THREAD

**Issue by yhui2000** [Microsoft/vscode#55653]
Issue Type: <b>Bug</b>

dont know how to

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (10.57GB free)|
|Process Argv|C:\AmyInstall\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
PowerShell|ms-|1.8.2
debugger-for-chrome|msj|4.8.2

</details>

**Comment by Tyriar** [comment]
Can you take a screenshot of the terminal when this happens? Including the panel title/dropdown.
