### ISSUE TITLE
Links in high contrast mode have lover constrast than in default dark mode

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#55651]
Issue Type: <b>Bug</b>

1. In high contrast mode
1. Open welcome page

**Bug**
Notice that links are dim and have fairly low contrast. They have lower contrast than links in the default dark theme.

High contrast:

![screen shot 2018-08-02 at 12 52 43 pm](https://user-images.githubusercontent.com/12821956/43579714-4c63d024-9653-11e8-96e4-eaada2672d18.png)

Dark+:

![screen shot 2018-08-02 at 12 55 19 pm](https://user-images.githubusercontent.com/12821956/43579727-588c7afe-9653-11e8-9d42-381491e71fb9.png)

VS Code version: Code - Insiders 1.26.0-insider (c86cab2211d6dce686e5c89934d915b1e020ba9e, 2018-08-02T05:12:16.245Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.25GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|17%|

</details>

**Comment by misolori** [comment]
Updated the text link to use the same link color as Dark+

![image](https://user-images.githubusercontent.com/35271042/43594337-d4ab7330-962e-11e8-8e82-a00e07dc77d0.png)
