### ISSUE TITLE
AutoSave when app looses focus

### ISSUE THREAD

**Issue by ThomasWeiser** [Microsoft/vscode#5565]
When working with automatic rebuild/refresh tools (e.g. in web development) it would be handy if vscode would save all modified files as soon as its window looses the focus when switching to another application.

There is an option `files.autoSave: onFocusChange`. There should be another option `onWindowDeactivation` or something like that.

JetBrains' line of IDEs has this option. IMHO it's very handy.

**Comment by pribilinskiy** [comment]
Btw, `"files.autoSave": "onFocusChange"` and `"afterDelay"` are mutually exclusive currently and that is bad. You can't have both enabled.

I would like to suggest following changes:

- value of `"files.autoSave"` to `"on"` / `"off"`
- add `"files.autoSaveOnFocusChange"`: `"currentFile" / "allFiles"`

**Comment by bpasero** [comment]
Added a new `onWindowChange` option for auto save 👍
