### ISSUE TITLE
New pane inside the Explorer listing the git Modified files

### ISSUE THREAD

**Issue by varemenos** [Microsoft/vscode#55657]
We currently have 3 panes in the Explorer Open Editors, Folders, Outline. I'd like to recommend a 4th one which is called "Modified files" and it will list files that were changed (based on the output of `git status`).

It should reside inside the Explorer, be closed/hidden by default and it's content should be similar to what you'd find listed in the Source Control's changes list but when clicking on any of the items, it'd open a new Editor with the file instead of a git diff view.

Please let me know if the explanation is too vague.

**Comment by joaomoreno** [comment]
It's not too vague... but the feature sounds very redundant to me. It's also something you can achieve as an extension, so if you really like it, feel free to author one which contributes that.
