### ISSUE TITLE
Missing menus in menu bar on Elementary (Loki)

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#55652]
In the latest Insiders "File" and "Windows" and "Help" menu are missing from menubar:

![2018-08-02_13-16-55](https://user-images.githubusercontent.com/1898161/43580662-88a1ce58-9656-11e8-8d17-5860c1cbe892.png)

**Comment by alex-pex** [comment]
Same issue : https://github.com/Microsoft/vscode/issues/55624

**Comment by Raydir** [comment]
same problem here on a win 10 with german language Pack.

**Comment by neymanushka** [comment]
same. Missing File,Windows,Help menu in latest vscode build. (windows 10)

**Comment by mjbvz** [comment]
Duplicate of #55624
