### ISSUE TITLE
Double click on vscode icon closes the application.

### ISSUE THREAD

**Issue by yanckst** [Microsoft/vscode#55656]
Hi,

I don't know if it's an expecting behavior, but when you double-click on the Visual Studio icon, it closes the application. Let me know. 

Thanks!

I'm using : 
- VSCode Version: 1.25.1
- OS Version: Windows 10 17134.167

Steps to Reproduce:
1. Open Visual Studio Code
2. Double-click on the Visual Studio icon in the left top corner.
3. Visual Studio code closes.

![bug vscode double click](https://user-images.githubusercontent.com/30554401/43584513-8fb50d8e-9630-11e8-811c-0f3552a658f3.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by beastdestroyer** [comment]
I'm pretty sure I've seen this exact same issue somewhere (unless this is the same one but reopened or smth?), one of the developers replied that for now it is the intended behaviour, but they are working on changing it soon? Might want to dig through the issues...
