### ISSUE TITLE
Display more metadata for binary files

### ISSUE THREAD

**Issue by ograndebe** [Microsoft/vscode#55654]
In the current version if you select some binary file VSC only shows a generic message.
You could show more info about the binary file, for example, update date, size, extension, mime type, this plain things that helps a lot.

**Comment by bpasero** [comment]
@ograndebe did you check the status bar (bottom right)? It should show the size at least.

**Comment by ograndebe** [comment]
@bpasero I didt't notice that.
It helps a little bit, but i'm dealing with some docker projects and sometimes i want to check if some binary files were updated.
Sometimes would be helpful to copy the absolute/relative path only with one click.
Even if you are dealing with some assets (using any language).
I'm not complaining, just trying to help.
