### ISSUE TITLE
cant install extensions on line

### ISSUE THREAD

**Issue by MKingWang** [Microsoft/vscode#55663]
![11](https://user-images.githubusercontent.com/32352403/43588164-79aa3848-969e-11e8-9546-c6494adfadab.png)
![12](https://user-images.githubusercontent.com/32352403/43588171-7d24ebda-969e-11e8-9c86-36adda3783c4.png)
![13](https://user-images.githubusercontent.com/32352403/43588176-7ec1ef24-969e-11e8-9142-2b8b3f020b93.png)

os:Fedora 27
user:root

i stoped the vpn, but cant install also

**Comment by MKingWang** [comment]
i have tried a lot  such as clean settings  before reinstall, stop proxy, and reboot system, but it did not work yet.

There is an error log , but it seems useless .
![15](https://user-images.githubusercontent.com/32352403/43591047-066a73aa-96a5-11e8-92ce-7bc49ba13c94.png)

**Comment by ramya-rao-a** [comment]
Can you share any errors from the console? Help -> Toggle Developer Tools -> Console.
