### ISSUE TITLE
Go To Implementation in a Java project does not do anything 

### ISSUE THREAD

**Issue by aabuniaj** [Microsoft/vscode#55661]
I opened a Java project in VSCode that contains Interfaces with implementation classes implementing them. The Go To Implementation option (Command + F12), it does not do anything. I'm able to go to the method definition in the interface with Go To Definition option, but the Go To Implementation option does not go to the class that has the implementation. Is that a bug? Does it need configuration in order to get it to work in a Java project?

Thank you,

**Comment by mjbvz** [comment]
Please file this issue against the java extension
