### ISSUE TITLE
Issue with search and change, autoreplacing the additional symbol not in range

### ISSUE THREAD

**Issue by FlamingQuasar** [Microsoft/vscode#55664]
Hello! 

- VSCode Version: 1.25.1
- OS Version: Windows 10

Steps to Reproduce:
If I search a word with a dot on start, it mark searched words with symbol " left out of the range:

1. typing a word of css class name used in JavaScript object in .js file, for example word: .base-
2. seeng the rusult, that contain class ".base-"  with such area of marking: ".base- , so there is a difference between .base- and ".base-
3. ... any replaces word with dot on the start position replaces both word and " symbol, so my code crushes with class names with no name start " symbol.
![issue](https://user-images.githubusercontent.com/5690317/43588956-b22735b0-967e-11e8-9acb-79e6da15358a.png)

(If it not running like on a screen or description, try to find a class name text cfirst closing and clear searchline)

**Comment by rebornix** [comment]
@FlamingQuasar this is because regex mode is turned on 

<img width="27" alt="image" src="https://user-images.githubusercontent.com/876920/45184798-e6543580-b1dc-11e8-8caf-080a6a4d0acb.png">

If you turn this off, it should work as expected. Thanks!
