### ISSUE TITLE
NVDA announces wrong count in language mode quick selector

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#55666]
Testing #52542

1. Using NVDA
1. Open the language mode quick picker from the status bar
1. Type `s`

**Bug**
NVDA announces `s, 2` when there are more than 2 results

It also reads: `picker 1 of 58, level 1` which I think is the total number languages (not the filtered down count)

**Comment by chrmarti** [comment]
This appears to be an older solution to the problem that broke at some point. Needs more investigation. (See: quickOpenViewer.ts AccessibilityProvider and Filter.)
