### ISSUE TITLE
Disable weird automatic formating in keybindings.json

### ISSUE THREAD

**Issue by ackvf** [Microsoft/vscode#55662]
Whenever I
a) modify _Keyboard Shortcuts_
b) paste a binding from _Default Keybindings_ to _keybindings.json_
c) modify text in _keybindings.json_ by hand (e.g. _Move Line Down_, _Tab_)
the file _keybindings.json_ becomes a mess.

![image](https://user-images.githubusercontent.com/2313018/43587450-8d783f8e-966a-11e8-897b-00c17577594d.png)

Compare left: `Default Keybindings` _(nice)_ vs right: `keybindings.json` _(ugly)_

![image](https://user-images.githubusercontent.com/2313018/43587741-30adb0b2-966b-11e8-9c09-0a853392690d.png)

_(dream feature):_ Having each rule on a single line in some kind of a table layout would be even better...
![image](https://user-images.githubusercontent.com/2313018/43588005-d374b994-966b-11e8-8092-8b5a23e36f00.png)

I don't mind creating this kind of layout by hand myself, but at least, please, don't ruin my creations whenever any of aforementioned edits are made.

**Comment by aeschli** [comment]
This is caused by the `editor.indent` feature

**Comment by ackvf** [comment]
Yes, thank you for the hint, I guess I will disable it for json files. Anyway it still only relates to point _c)_

When I modify keyboard shortcut from the _Kyeboard Shortcuts_ settings panel, the newly inserted rule
1. changes previous record in _keybindings.json_ (because of the ending `} ,`)
2. is inserted on 5 separated lines instead of just one

**Comment by rebornix** [comment]
@ackvf this feature can be disabled by 

```
    "[json]": {
        "editor.autoIndent": false
    }
```

Our indentation adjustment is based on indentation rules and might not be perfect. Thanks for your feedback.
