### ISSUE TITLE
VSCode opens 54 terminals

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#55669]
Elementary Loki (Ubuntu 16.04)

Version: 1.26.0-insider
Commit: c86cab2211d6dce686e5c89934d915b1e020ba9e
Date: 2018-08-02T05:18:18.450Z

- start vscode-insiders from the console
- over 50 bash instances are started

![image](https://user-images.githubusercontent.com/6461412/43591488-c0cd4588-9673-11e8-8778-a7aca46c71c6.png)

**Comment by aeschli** [comment]
On the next start, one more added, now 55 instances.

**Comment by aeschli** [comment]
Marking as important. Others in the office don't see this, but I still suffer from it. Every VSCode restart gets slower, and it's also hitting the OS's resources (I see my native terminals crash often, not sure if its related)

**Comment by isidorn** [comment]
Let's assign it to July for now to raise awarness

**Comment by aeschli** [comment]
This is caused by the `"terminal.integrated.experimentalRestore"` setting which I set to true at some point. 

Removing the July milestone as regular users don't have this set.

**Comment by Tyriar** [comment]
It's acting as expected, that's one of the reasons `terminal.integrated.experimentalRestore` is marked experimental. https://github.com/Microsoft/vscode/issues/44302
