### ISSUE TITLE
Use multiple language syntax highlight in one file

### ISSUE THREAD

**Issue by XadillaX** [Microsoft/vscode#55660]
I'm working on a nunjucks-templated SQL file, it's something like:

```sql
SELECT
  `foo`, COUNT(0) AS `count`
FROM `bar`
WHERE
  {% if a and b %}
  `biu` BETWEEN {{a}} AND {{b}} AND
  {% elif a %}
  `biu` >= {{a}} AND
  {% elif b %}
  `biu` <= {{b}} AND
  {% endif %}
  {{c}}
GROUP BY `status`
```

I want to both highlight SQL syntax and nunjucks syntax.

**Here's some similar issues about HTML + PHP. But that is not the really two languages and the plugin can resolve that.** So I don't think they are the same issue.

**Comment by aeschli** [comment]
You need to write a specific syntax highlight grammar for that syntax...
