### ISSUE TITLE
TypeScript syntax highlighting: improve function expressions

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#5566]
- VSCode Version: 1.0.0
- OS Version: Mac OS X latest

Steps to Reproduce:

1. Add the following to a TS file: `const foo = (): Model => ({ 'bar': 'baz' })`

Result: the function body expression has no detail.

![image](https://cloud.githubusercontent.com/assets/921609/14686724/02f506c2-0732-11e6-8d97-5432dbec081c.png)

This is true for larger expressions too:

![image](https://cloud.githubusercontent.com/assets/921609/14686734/0bd94320-0732-11e6-92ab-6efdc226942f.png)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#150

**Comment by OliverJAsh** [comment]
This issue is actually not specific to TypeScript, it also effects JavaScript. Can we reopen the issue here, or elsewhere if there's a better place?

Notice the language mode in the bottom right:

![image](https://cloud.githubusercontent.com/assets/921609/18122098/a8aa8192-6f5f-11e6-970d-3081ffb442a4.png)
