### ISSUE TITLE
Auto-attach fails on Windows

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#55672]
VS Code Insiders:

- turn on auto-attach
- on integrated terminal run `node --inspect test.js`

Observe: debugger does not automatically attach

Problem: VS Code has changed how the terminal is launched:
previously a node.js process with an identifying argument `--type=terminal` was used; now a executable `winpty-agent.exe` is used.

Since the auto-attach feature needs to identify this process, it was broken by the VS Code change.

**Comment by sbatten** [comment]
verified in sources but wasn't in latest build yet
