### ISSUE TITLE
HG terminal border not changing

### ISSUE THREAD

**Issue by commit-master** [Microsoft/vscode#55674]
I'm currently trying to change the terminal border on focus on High Contrast default theme. Here is the settings I'm running:

```
"workbench.colorCustomizations": {
        "editorRuler.foreground": "#ffffff57",
        "[Default High Contrast]": {
            "terminal.ansiRed": "#ff6e67",
            "terminal.ansiBrightRed": "#ff6e67",
            "terminal.ansiBlue": "#caa9fa",
            "terminal.ansiBrightBlue": "#caa9fa",
            "terminal.border": "#ff0000"
        },
    },
```

While the text colors are getting updated to the right hex, the border of the terminal is still orange (like the default theme) instead of red. I believe `terminal.border` should be the right setting to play with.

Am I missing something or is it a bug ?
If it's not a bug, then it would be great to export a setting that allow users to modify this.

**Comment by alexr00** [comment]
@commit-master  I think what you're looking for here is `focusBorder`. The terminal doesn't have it's own focus border color and instead uses the same color as the rest of the application. Does `focusBorder` give you what you're looking for?

**Comment by Tyriar** [comment]
Yes `focusBorder` is right, and it works under the HC theme:

<img width="289" alt="screen shot 2018-09-13 at 9 07 04 pm" src="https://user-images.githubusercontent.com/2193314/45529236-01084a80-b799-11e8-97e4-f588e0393081.png">
