### ISSUE TITLE
file menu item disappeared

### ISSUE THREAD

**Issue by andersbc** [Microsoft/vscode#55679]
Issue Type: <b>Bug</b>

The 'file' menu item in the title bar has gone. I don't know what caused it. A restart of vs code didnt fix it. Neither disabling all extensions and reloading. 

Found a way to get it back through settings

Opne settings (ctrl+shift+p  'Preferences: Open  Settings (preview)' :

In the settings page:
'Window' -> Title Bar Style -> select 'custom' 
...restart vs code 

Then the file menu item reappears. 
Setting it back to 'native' causes it to disappear again. 

VS Code version: Code - Insiders 1.26.0-insider (c86cab2211d6dce686e5c89934d915b1e020ba9e, 2018-08-02T05:17:02.675Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (8 x 3503)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.97GB (2.70GB free)|
|Process Argv|C:\Users\xxx\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe C:\Users\xxx\Desktop\validate.js|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by st0le** [comment]
FYI, Even Help has disappeared
