### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#55673]
Issue Type: <b>Bug</b>

1. Enable nvda 
1. Enable screen reader mode in vscode
1. Open terminal
1. Resize VS Code window

**Bug**
In developer tools console, see:

```
Uncaught TypeError: Cannot read property 'style' of undefined
    at AccessibilityManager._refreshRowDimensions (C:\Users\matb\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\vscode-xterm\lib\AccessibilityManager.js:197:17)
    at AccessibilityManager._refreshRowsDimensions (C:\Users\matb\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\vscode-xterm\lib\AccessibilityManager.js:193:18)
    at C:\Users\matb\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\vscode-xterm\lib\AccessibilityManager.js:59:106
```

VS Code version: Code - Insiders 1.26.0-insider (c86cab2211d6dce686e5c89934d915b1e020ba9e, 2018-08-02T05:17:02.675Z)
OS version: Windows_NT x64 10.0.17728

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.98GB (0.90GB free)|
|Process Argv|C:\Users\matb\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|yes|
|VM|57%|

</details>

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/55744
