### ISSUE TITLE
Lost File and Help menu

### ISSUE THREAD

**Issue by wsmelton** [Microsoft/vscode#55676]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

I've lost file and help menu after an update on one machine. It repeats doing a fresh installation on a different machine.

VS Code version: Code - Insiders 1.26.0-insider (c86cab2211d6dce686e5c89934d915b1e020ba9e, 2018-08-02T05:17:02.675Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.90GB (0.42GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
azureautomation|Awe|0.7.0
cform|aws|0.0.10
emojisense|bie|0.4.1
bracket-pair-colorizer|Coe|1.0.59
xml|Dot|2.3.1
vscode-pandoc|Dou|0.0.8
gitlens|eam|8.5.4
vscode-great-icons|emm|2.1.39
vscode-azurestorage|ms-|0.4.1
mssql|ms-|1.4.0
azure-account|ms-|0.4.2
PowerShell|ms-|1.8.2
wordcount|ms-|0.1.0
vsliveshare|ms-|0.3.504
vsliveshare-audio|ms-|0.1.28
azurerm-vscode-tools|msa|0.4.2
vscode-docker|Pet|0.1.0
arm-snippets|sam|1.2.0
vscode-sql-beautify|sen|0.0.4
code-settings-sync|Sha|3.0.0
code-spell-checker|str|1.6.10
gitblame|wad|2.4.4

(3 theme extensions excluded)

</details>

**Comment by corbob** [comment]
Unscientific reproduction:
---
Currently have File and help:
---
Version: 1.26.0-insider
Commit: 573d53815e74f8e4a52c2b6665f5ba9a92dbd341
Date: 2018-08-01T05:17:54.216Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Updated insiders:
---
Version: 1.26.0-insider
Commit: c86cab2211d6dce686e5c89934d915b1e020ba9e
Date: 2018-08-02T05:17:02.675Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

File and Help menu disappeared.

**Comment by corbob** [comment]
@isidorn any idea which issue this is a duplicate of? I would love to follow that issue, but cannot find an open one that appears to be related. (note all the ones that the bot linked include the text about copying to the clipboard...)

**Comment by wsmelton** [comment]
Not sure who controls that bot but it needs to consider the version information added to the issue. The commit of Insiders is from the release this morning (Aug 02, 2018). So even if the text part matches up to other issues it cannot be considered relevant when it is a newer release (at least my opinion).

**Comment by isidorn** [comment]
https://github.com/Microsoft/vscode/issues/55624

**Comment by wsmelton** [comment]
Ha, one that is not even listed by the bot...
