### ISSUE TITLE
FoldingRangeKind that isn't Region or Comment (to support syntactic folds)

### ISSUE THREAD

**Issue by rjmholt** [Microsoft/vscode#55686]
From https://github.com/PowerShell/vscode-powershell/issues/1458#issuecomment-409794074.

We've implemented syntax/AST-based folding in the PowerShell extension, but the folding ranges it designates must be labelled with a `FoldingRangeKind`.

`Region` was chosen for syntax folds, since (for example) an `if`-block is not a `Comment` or an `Import`. But this means using "(Un)fold All Regions" toggles syntax-based folding as well, when a user might only want to fold explicit `#region`s.

Our current prospective solution is to assign a `FoldingRangeKind` of `-1` or similar (which seems to work). But naturally that's not an ideal solution.

Is there currently a supported way of distinguishing `#region` folding ranges from custom syntactic folding ranges?'

(Also, I imagine that adding new enum values into `FoldingRangeKind` to cater to increasingly granular folding ranges would be infeasible -- just more an illustration of our current workaround.)

**Comment by rjmholt** [comment]
VSCodeBot is so impressive!

**Comment by aeschli** [comment]
`Region` is only to be used for ranges originating from folding range marked by `#region` and `#endregion`

For syntax ranges, don't set `kind`. `kind` is optional.

**Comment by aeschli** [comment]
I will improve vscode.d.ts spec comment.

**Comment by rjmholt** [comment]
Thanks @aeschli!
