### ISSUE TITLE
After install multi format extensions, "editor.formatOnSave" base on which one?

### ISSUE THREAD

**Issue by TomIsion** [Microsoft/vscode#55680]
- VSCode Version: 1.25.1
- OS Version: macOS 10.13.6

Steps to Reproduce:

1. install extensions: "Beautify" and "Prettier - Code formatter"
2. then change settings "[javascript]": { "editor.formatOnSave": true }

Does this issue occur when all extensions are disabled?: No

So when I save `.js` file, the auto format sometime is "Beautify" sometime is "Prettier"

I wanna assign one to format my file, but I cannot find the setting.

Thanks.

**Comment by jrieken** [comment]
Yeah, that's a know problem and it depends on the order in which the extensions are activated. We have blogged about this https://code.visualstudio.com/blogs/2016/11/15/formatters-best-practices and the question is why do you need two formatters for one language? Allowing multiple formatters is tracked here: #41882
