### ISSUE TITLE
Mnemonics in the custom menus are using a different font

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#55681]
Elementary Loki (Ubuntu 16.04)

Version: 1.26.0-insider
Commit: c86cab2
Date: 2018-08-02T05:18:18.450Z

![image](https://user-images.githubusercontent.com/6461412/43596177-d1ed0f3c-967e-11e8-948d-72f16ab19720.png)

- the right arrow for the sub menus is too prominent. A little smaller would be more elegant
- the checkmark (see `Auto Save`) is barely visible
- the characters with mnemonice seem to use a different font (e.g. see the`l` in Save All)
- the submenus upper left corner seems to be round, while other corners are not
- the black menu on the back background is hard to see. On ElementaryOS the menu background color is normally white, which works quite well. Maybe it would make sense to read out the OS colors?

**Comment by sbatten** [comment]
Most of these have their own issues. I will rename as I think one does not. 

The roundedness of the top left is an illusion. This is much more obvious in a light theme. As for the color, the menus are themable so this is user choice.

**Comment by be5invis** [comment]
Also repros on Windows
![image](https://user-images.githubusercontent.com/240091/44081090-80690bc8-9fe0-11e8-9fb5-5778c965b1fe.png)
