### ISSUE TITLE
Debug not working

### ISSUE THREAD

**Issue by moisesrodriguez** [Microsoft/vscode#55685]
Issue Type: <b>Bug</b>

Since 1.25.1 the debugger stopped working. I can't even open the settings Add Configuration from the drop down. It just won't open it. Even if I try Debug: Open launch.json it will not open it.

When I click the green play button to Attach, it just stays as if is trying to attach, but it will stay there forever without sending any error.

This is how my config looks like. Which I haven't touched in months.
```
{
            "name": "Attach",
            "type": "node",
            "request": "attach",
            "port": 5858,
            "address": "localhost",
            "restart": true,
            "sourceMaps": false,
            "localRoot": "${workspaceRoot}",
            "remoteRoot": "/app",
            "timeout": 60000
}
```

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 5, 4|
|Memory (System)|8.00GB (0.12GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.4
npm-intellisense|chr|1.3.0
xml|Dot|2.3.1
gitlens|eam|8.5.4
vscode-github|Kni|0.30.0
dotenv|mik|1.0.1
HTMLHint|mka|0.5.0
vscode-apache|mrm|1.1.1
language-gettext|mro|0.1.1
azure-account|ms-|0.4.2
debugger-for-chrome|msj|4.8.2
vscode-docker|Pet|0.1.0
code-settings-sync|Sha|3.0.0
vscode-spotify|shy|2.5.1

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Can you reproduce this with vscode insiders
https://code.visualstudio.com/insiders/

**Comment by moisesrodriguez** [comment]
Maybe it was my computer, restarted it and it's now working.
