### ISSUE TITLE
IME Composition font is different from the font specified by editor.fontFamily

### ISSUE THREAD

**Issue by espresso3389** [Microsoft/vscode#5568]
- VSCode Version: 1.0.1-insider
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Turn IME on and type some characters.
2. You can see the font during IME composition is different from the font specified by editor.fontFamily.

![animation](https://cloud.githubusercontent.com/assets/1311400/14688163/349df892-077c-11e6-9372-a877d4cd197d.gif)

**Comment by espresso3389** [comment]
On 1.2.0-insider (7ccb21d7e7256a7d42f3dda8b2d3721b8e59724f), the issue seems fixed.

**Comment by alexandrudima** [comment]
Most likely due to PR #5615
