### ISSUE TITLE
[C#] Deeply nested parens causes editor hang.

### ISSUE THREAD

**Issue by staticvoidmain** [Microsoft/vscode#55687]
Issue Type: <b>Bug</b>

# Problem
Too many nested parens on a single line cause C# file to hang.

# Additional Info
- I recently reversed some VB to C# and pasted it into code, resulting in a complete hang of the vscode process.
- It's fine if these are separated into multiple lines as in the example, however if it's all on a *single* line you'll get a hang.
- It's definitely the syntax highlighter, and seems to be specific to C#.
- Tested against insiders, and with no extensions on the current build.
- Tested the same line with other c-like language file extensions (js, ts, cpp, java) and they handle it without a crash.
- Oh, also, if you drop the (object) casts off it's fine as well.

# Steps To Reproduce
1. New file > evil_line.cs
2. Paste these contents
```csharp
// don't try to join these lines...
var message = Conversions.ToString(
	Operators.ConcatenateObject(
		Operators.ConcatenateObject(
			Operators.ConcatenateObject(
				Operators.ConcatenateObject(
					Operators.ConcatenateObject(
						Operators.ConcatenateObject(
							Operators.ConcatenateObject(
								Operators.ConcatenateObject(
									Operators.ConcatenateObject(
										Operators.ConcatenateObject(
											Operators.ConcatenateObject(
												Operators.ConcatenateObject(
													Operators.ConcatenateObject(
														Operators.ConcatenateObject(
															Operators.ConcatenateObject(
																Operators.ConcatenateObject(
																	Operators.ConcatenateObject(
																		Operators.ConcatenateObject(
																			Operators.ConcatenateObject(
																				Operators.ConcatenateObject(
																					Operators.ConcatenateObject(
																						(object) strMsg,
																						Interaction.IIf(
																							Strings.Len(strMsg) > 0, 
																							(object) "\r\n", 
																							(object) null)), 
																					(object) "\r\n"),
																				(object) "name '"), 
																			(object) name), 
																		(object) "'"), 
																	(object) "\r\n"), 
																(object) "age '"), 
															(object) age), 
														(object) "'"),
													(object) "\r\n"),
												(object) "dob '"),
											(object) dob), 
										(object) "'"), 
									(object) "\r\n"), 
								(object) "favoriteColor '"), 
							(object) favoriteColor), 
						(object) "'"), 
					(object) "\r\n"), 
				(object) "favoriteFilm '"), 
			(object) favoriteFilm), 
		(object) "'")
	);
```

3. Join Lines

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2695 v2 @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|12.00GB (7.34GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.3.1
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.34
vscode-great-icons|emm|2.1.39
code-beautifier|mic|2.1.0
mssql|ms-|1.4.0
python|ms-|2018.7.1
cpptools|ms-|0.17.7
PowerShell|ms-|1.8.2
team|ms-|1.136.0
debugger-for-chrome|msj|4.8.2
vscode-javascript-booster|sbu|0.10.1

</details>

**Comment by alexandrudima** [comment]
Repro steps:

* create `file.txt` with the contents:
```
var message = Conversions.ToString( Operators.ConcatenateObject( Operators.ConcatenateObject( Operators.ConcatenateObject( Operators.ConcatenateObject( Operators.ConcatenateObject( Operators.ConcatenateObject( Operators.ConcatenateObject( Operators.ConcatenateObject( Operators.ConcatenateObject( Operators.ConcatenateObject( Operators.ConcatenateObject( Operators.ConcatenateObject( Operators.ConcatenateObject( Operators.ConcatenateObject( Operators.ConcatenateObject( Operators.ConcatenateObject( Operators.ConcatenateObject( Operators.ConcatenateObject( Operators.ConcatenateObject( Operators.ConcatenateObject( Operators.ConcatenateObject( (object) strMsg, Interaction.IIf( Strings.Len(strMsg) > 0, (object) "\r\n", (object) null)), (object) "\r\n"), (object) "name '"), (object) name), (object) "'"), (object) "\r\n"), (object) "age '"), (object) age), (object) "'"), (object) "\r\n"), (object) "dob '"), (object) dob), (object) "'"), (object) "\r\n"), (object) "favoriteColor '"), (object) favoriteColor), (object) "'"), (object) "\r\n"), (object) "favoriteFilm '"), (object) favoriteFilm), (object) "'") );
```

* change the language to C#

**Comment by alexandrudima** [comment]
Using the steps described in https://github.com/Microsoft/vscode/issues/57593#issuecomment-417276769

The bad regex is:
```
(?x)
(?<return-type>
  (?<type-name>
    (?:
      (?:ref\s+(?:readonly\s+)?)?   # ref return
      (?:
        (?:(?<identifier>@?[_[:alpha:]][_[:alnum:]]*)\s*\:\:\s*)? # alias-qualification
        (?<name-and-type-args> # identifier + type arguments (if any)
          \g<identifier>\s*
          (?<type-args>\s*<(?:[^<>]|\g<type-args>)+>\s*)?
        )
        (?:\s*\.\s*\g<name-and-type-args>)* | # Are there any more names being dotted into?
        (?<tuple>\s*\((?:[^\(\)]|\g<tuple>)+\))
      )
      (?:\s*\?\s*)? # nullable suffix?
      (?:\s*\[(?:\s*,\s*)*\]\s*)* # array suffix?
    )
  )\s+
)
(?<interface-name>\g<type-name>\s*\.\s*)?
(\g<identifier>)\s*
(<([^<>]+)>)?\s*
(?=\()
```

That is coming from this rule -- https://github.com/Microsoft/vscode/blob/667e4c2a1a85946344cd1194348d4f2e65fa53cc/extensions/csharp/syntaxes/csharp.tmLanguage.json#L1220

That line was changed last via https://github.com/Microsoft/vscode/commit/076c08493034201ab4e7c56b6258246def7afa5e

**Comment by aeschli** [comment]
This issue was moved to dotnet/csharp-tmLanguage#135
