### ISSUE TITLE
Incorrect presentation of Item in the Extensions list

### ISSUE THREAD

**Issue by fzzr-** [microsoft/vscode#55692]
Wrong presentation of Item in the Extensions list - missed upd btn and some info.

Ext id: `dbaeumer.jshint`

![screen shot 2018-08-02 at 20 42 25](https://user-images.githubusercontent.com/888526/43601099-1fc575e4-9695-11e8-9e1a-c17fc09f0fd6.png)

**Comment by hhu94** [comment]
I'm fairly sure that it's just that the width of your extensions panel went below the minimum width required for the `Update to 0.18.19` button + _Disabled_ to show up.

If you make your extensions panel just a bit wider it should show up as normal. You'll also notice that if you make your panel even narrower, the buttons for the other outdated extensions will start disappearing as well.

See below for a demonstration.

![bug-repro](https://user-images.githubusercontent.com/7145349/44131675-815c0dd6-a009-11e8-92e7-1dabfdb6170c.gif)

**Comment by fzzr-** [comment]
@hhu94 I agree. But it looks very laggy & glitchy :)
![43601099-1fc575e4-9695-11e8-9e1a-c17fc09f0fd6](https://user-images.githubusercontent.com/888526/44152012-e498b9a0-a0ac-11e8-97bc-a834615c3a4e.png)

**Comment by ramya-rao-a** [comment]
@fzzr- Thanks for reporting.

#22461 covers the issue of not showing the outdated information for disabled extensions in the first place. Once that is fixed, this current ux issue will not show up. So will close this one in favor of #22461

**Comment by ramya-rao-a** [comment]
Re-opening this as #22461 only covers excluding disabled extension in the badge and doesn't change anything around the `Update to` button

**Comment by misolori** [comment]
This now always shows the update buttons in narrow views:

<img width="75%" src="https://user-images.githubusercontent.com/35271042/60485073-8984a880-9c50-11e9-89d3-1add77dec342.gif" />
