### ISSUE TITLE
Error starting OmniSharp

### ISSUE THREAD

**Issue by wind39** [Microsoft/vscode#5569]
- VSCode Version: 1.0.0
- OS Version: Kubuntu 16.04

Steps to Reproduce:

1. Install C# extension.
2. Try to edit an existing C# project, already containing a .csproj file in the folder.

[INFO] Starting OmniSharp at '/home/william/Documents/Projects/SQL/SQL.sln'...
[INFO] Started OmniSharp from '/home/william/.vscode/extensions/ms-vscode.csharp-0.3.7/bin/omnisharp' with process id 13156...
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Framework.Runtime.Loader, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'Microsoft.Framework.Runtime.Loader, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
  at dnx.host.RuntimeBootstrapper.ExecuteAsync (System.String[] args) <0x40d53690 + 0x00857> in <filename unknown>:0 
  at dnx.host.RuntimeBootstrapper.Execute (System.String[] args) <0x40d53460 + 0x00063> in <filename unknown>:0 
[ERROR] Error: Failed to start OmniSharp

**Comment by dbaeumer** [comment]
This issue was moved to OmniSharp/omnisharp-server#213
