### ISSUE TITLE
Updating extension from CLI should accept Y/N response

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#55690]
From https://github.com/Microsoft/vscode/issues/45072#issuecomment-409661077

- Install old version of extension from vsix
- Run `code-insiders --install-extension msjsdiag.debugger-for-chrome`
- `Extension 'msjsdiag.debugger-for-chrome' v4.8.1 is already installed, but a newer version 4.8.2 is available in the marketplace. Would you like to update? Yes(0) | No(1)`
- If I respond `y`, it cancels the install. I have to respond with `0` which is unusual

Side note, in the message above, one version number has `v`, the other doesn't, they should be the same.

**Comment by ramya-rao-a** [comment]
Code pointer to anyone who wants to pick this one up: https://github.com/Microsoft/vscode/blob/19f25e4801b26850e959c928878edd511c944e4d/src/vs/code/node/cliProcessMain.ts#L143

**Comment by lolerwaffles** [comment]
I can do this
