### ISSUE TITLE
Improve git.autoRepositoryDetection

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#55696]
From #53668

This is all the info we have to understand this setting

![image](https://user-images.githubusercontent.com/323878/43602632-5d2cf056-9645-11e8-8b8c-843eaceb63e4.png)

I can guess that `true` includes both openEditors and subfolders, the string options just enable one, and `false` is nothing, but I had to think about it for a second. A couple enumDescriptions might help.

re: the setting in general, would there ever be a third option? What happens if someone wants to enable 2 of the 3?

**Comment by joaomoreno** [comment]
Yeah... I didn't want to break existing `true` and `false` users. We can improve docs here.

**Comment by roblourens** [comment]
I think those comments in the description should actually be enumDescriptions

**Comment by roblourens** [comment]
And I found #55895 while thinking about this

**Comment by joaomoreno** [comment]
@robertohuertasm Oh didn't even know about enumDescriptions until now!
