### ISSUE TITLE
Tool bar options are no longer there

### ISSUE THREAD

**Issue by tmknight** [Microsoft/vscode#55693]
Issue Type: <b>Bug</b>

Update from 2 Aug no longer shows 'File' and 'Help'

VS Code version: Code - Insiders 1.26.0-insider (c86cab2211d6dce686e5c89934d915b1e020ba9e, 2018-08-02T05:17:02.675Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (17.25GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.59
compulim-vscode-closetag|Com|1.2.0
vbscript|Dar|1.0.4
xml|Dot|2.3.1
auto-close-tag|for|0.5.6
code-runner|for|0.9.3
vscode-apache|mrm|1.1.1
mssql|ms-|1.4.0
python|ms-|2018.7.1
cpptools|ms-|0.17.7
csharp|ms-|1.15.2
PowerShell|ms-|1.8.2
team|ms-|1.136.0
htmlescape-vscode-extension|ray|0.0.4
vscode-yaml|red|0.0.14
code-settings-sync|Sha|3.0.0

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
@sbatten I think the whole planet filled this issue
