### ISSUE TITLE
Different size (height) of left panel after doubleclick on edge by resize arrow cursor in different panels

### ISSUE THREAD

**Issue by Mlocik97-issues** [Microsoft/vscode#55691]
Issue Type: <b>Bug</b>

Different size (height) of left panel after doubleclick on edge by resize arrow cursor in different panels (Explorer, Search and Debugger have one size of panel, and Git and Extensions have another size of panel)

![different sizes](https://user-images.githubusercontent.com/31345346/43600471-ef8b980e-968a-11e8-8bf4-8a2d5ab4d114.png)

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (9.48GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by isidorn** [comment]
As desizned, each viewlet decides what is its optimal width
