### ISSUE TITLE
Problems view: do not show blue focus outline please

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#55699]
Regression: now we display the blue focus outline in the problems view
Assigning also to myself since @sandy081 is on vacation

![screen shot 2018-08-02 at 20 48 03](https://user-images.githubusercontent.com/1926584/43604306-bb74bb1c-9695-11e8-8755-5b65c680f496.png)

**Comment by isidorn** [comment]
Not important for relase, moving out to August

**Comment by isidorn** [comment]
The issue is that it looks bad and I do not see the benefit of allowing this sentence to be focues.
@bpasero filed the same issue

**Comment by sandy081** [comment]
I see, not showing any focused element is also weird when problems view is focused. Changed this to: when there are no problems shown, the complete problems view will be focused.

![image](https://user-images.githubusercontent.com/10746682/44043105-4889c26a-9f22-11e8-954d-4da65a439a0c.png)

**Comment by bpasero** [comment]
@sandy081 I think the behaviour is now inconsistent with other "empty" views. Take the SCM for example:

![image](https://user-images.githubusercontent.com/900690/44043756-eb24ea1c-9f23-11e8-81fa-e93fcba2ad70.png)


I would also not expect a focus indicator around the text here because this element is nothing I can interact with.

For me focus only makes sense if I can interact with the element using the keyboard. It should not be used to fix screen reader issues imho.

**Comment by sandy081** [comment]
@bpasero There is a clear filter link to be interacted with all problems are filtered. 

![image](https://user-images.githubusercontent.com/10746682/44044555-368a69da-9f26-11e8-9560-9ac4f7f28911.png)

To be consistent, I focussed the container always.

**Comment by isidorn** [comment]
This is now not consistent with empty SCM which does not show focus even on the container.
Why don't you simply pass focus to the input box (similar as how debug console passes to the input)

**Comment by bpasero** [comment]
I like that 👍

**Comment by sandy081** [comment]
I can do that. Reopening to consider @isidorn's suggestion

**Comment by sandy081** [comment]
@isidorn If I focus the filter input box then the status about Problems view (like No Problems) will not be read to the user. Filer input box will have its own status or information.

**Comment by isidorn** [comment]
Than instead of doing some fancy aria-tricks I am fine with leaving the focus in the container - so the proper thing is read out.

**Comment by bpasero** [comment]
Could the input field read out some ARIA context to help here? E.g. how many things you can filter on? Maybe that is something useful to have anyway even when there are markers to filter?

**Comment by sandy081** [comment]
I think input field should read about what it is about. In this case it reads the placeholder that tells you about filtering. It also reads the text when you type. Overloading this with general information is not a good idea.

**Comment by bpasero** [comment]
@sandy081 could the empty case just be a tree with one element that reads this info? that would have the added value that - once problems are coming in - focus would already be in the tree and you can start to navigate.

**Comment by sandy081** [comment]
@bpasero This is the case now except that empty case is with an element other than tree. When the problems come in first problem will be selected.

**Comment by sandy081** [comment]
Closing this as the current solution is acceptable.

**Comment by octref** [comment]
@joaomoreno did a change in #61534 so this is now inconsistent.

If you do "Previous Panel View" and the Panel View ends on an empty Problems View, the next "Previous Panel View" won't run.
