### ISSUE TITLE
Underscore not visible

### ISSUE THREAD

**Issue by Ctrl-Code** [Microsoft/vscode#55706]
Issue Type: <b>Bug</b>

Underscore is not visible

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:40:20.190Z)
OS version: Linux x64 4.15.0-20-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 1694)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|7.72GB (3.04GB free)|
|Process Argv|/snap/vscode/44/usr/share/code/code pointer.cpp|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.17.7

</details>

**Comment by isidorn** [comment]
Please file repro steps so we could see the same issue you are seeing.
Also a picture would be useful

**Comment by ramya-rao-a** [comment]
/duplicate #35901
cc @Tyriar
