### ISSUE TITLE
Feature request: combining files in Explorer onto a single line

### ISSUE THREAD

**Issue by walrus95** [Microsoft/vscode#55704]
I'm working on an Angular project in Visual Studio Code. I would like Visual Studio Code to be able to combine related files into a single line in the Explorer side bar. For example, in a project which has the following files:

![image](https://user-images.githubusercontent.com/32824014/43607854-7c99c0d6-966d-11e8-8305-c5160b828ddf.png)

I would like them to be displayed as:

![image](https://user-images.githubusercontent.com/32824014/43607873-87a81ed2-966d-11e8-901e-a35ae10bb3b7.png)

The user would click the various icons to open the files corresponding to particular file types (html, css, ts, spec.ts, etc.) Clicking on the words (such as foo.component or bar.component) would default to opening the TypeScript file.

This may be a good extension candidate, if this functionality will not be implemented in the main project. If best as an extension, please link to resources which show how an extension could modify the Explorer sidebar to this extent. Thank you!

**Comment by walrus95** [comment]
Greetings @isidorn -- Would you be so kind as to provide a link to the feature request which is being duplicated? Thank you.

**Comment by isidorn** [comment]
@walrus95 can you please search through the issues with label "file-explorer" and "feature-request". You will then find it the same way I would. Thanks

**Comment by walrus95** [comment]
Than you, @isidorn 

I found the main one.
[#6328](https://github.com/Microsoft/vscode/issues/6328)

My suggestion is a bit different, in that I recommend multiple icons on the same line, but the solution in the main thread will better scale to large numbers of files.

We need need this feature implemented. The nerds are getting restless.

**Comment by isidorn** [comment]
Yeah the nerds will soon have my head :|
