### ISSUE TITLE
Failed to install VS Code update

### ISSUE THREAD

**Issue by ljtill** [Microsoft/vscode#55709]
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2255266/vscode-inno-updater.log)

- VSCode Version: 1.26.0-insider
- OS Version: Microsoft Windows 10 Pro Insider Preview - 10.0.18204 Build 18204

Steps to Reproduce:

1. Update VS Code Insider via Built-in Updater

![image](https://user-images.githubusercontent.com/158992/43613271-7492b710-9674-11e8-99a7-577c94769146.png)

**Comment by joaomoreno** [comment]
Can you check if you have any running Code processes?

**Comment by ljtill** [comment]
Attempted it again this morning and the issue has cleared. Upgrade went through without any issues.
