### ISSUE TITLE
Open parenthesis commits completion when typing `[...()]`

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#55700]
Issue Type: <b>Bug</b>

* First, type `a` somewhere and accept as a completion.
* Type:
```ts
const a = 0;
const arr = [];
```
* Put cursor inside `[]`.
* Type `...(`.
* Expected: See `[...()]` and I can start typing an expression in parentheses.
* Actual: `[...a()]`.

VS Code version: Code - Insiders 1.26.0-insider (573d53815e74f8e4a52c2b6665f5ba9a92dbd341, 2018-08-01T05:18:02.119Z)
OS version: Linux x64 4.13.0-43-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 899)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|7.63GB (0.75GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders tests/cases/fourslash/|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by alexandrudima** [comment]
Looks like `(` is a completion accepting character.
