### ISSUE TITLE
Slight text blur on integrated console resize

### ISSUE THREAD

**Issue by gfvandehei** [microsoft/vscode#55701]
- VSCode Version: 1.25.1
- OS Version: Windows 10 pro 10.0.17134 build 17134

Steps to Reproduce:

1. Open VSCode and snap window to left side of screen .
2. Create/open integrated terminal instance, tested with WSL bash, Powershell, cp.
3. Resize shell to around 5% of screen height.
4. Should see slight blur in text toward center of shell instance.

Note: problem does not appear on certain window sizes.
-Tested to appear at 1920*1080 snap to left or right half of screen, and snap to corner (1/4 screen).
-Tested to NOT appear when vscode is a free floating window.

Expected: text in console clear and sharp.
Result: text in console blurry.

Animation of issue included, 
![2018-08-02_15-12-12](https://user-images.githubusercontent.com/26315292/43606262-d5ff3476-9668-11e8-8893-086a7ff2ce1e.gif)

The slight blur can be very uncomfortable to look at for long periods of time.
 
Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
I think you're hitting https://github.com/xtermjs/xterm.js/issues/985

**Comment by Ebuall** [comment]
![blurry](https://user-images.githubusercontent.com/10381141/43783852-63777524-9a6b-11e8-8e1d-47a9ac267ce9.gif)
I think here you can see more clearly how font-height jumps, depending on a terminal height. 
It depends only on terminal height and width, and completely unrelated to main window.

**Comment by pedrogarcia** [comment]
I'm having this issue as well, even without resizing the terminal window.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

My settings.json has:
```
"window.zoomLevel": -0.75,
    "editor.fontSize": 16,
```
