### ISSUE TITLE
String literal

### ISSUE THREAD

**Issue by jpablopachar** [Microsoft/vscode#55715]
Fuera bueno que implementen la funcion de que al trabajar con strings literals en javascript pueda insertar codigo inteligente de html donde me sugiera clases, autocompletado de etiquetas etc etc...
Me gusta mucho Javascript y sobretodo trabajar en VS CODE !!! :1st_place_medal:

**Comment by mjbvz** [comment]
Sorry, I don't understand the issue. Can you please provide an example that shows the expected behavior
