### ISSUE TITLE
The feedback popup should disappear after choosing to submit a bug

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#55713]
Issue Type: <b>Bug</b>

- Click on the smiley face in the bottom right corner
- Click on the "Submit a bug" link in the pop up

The issue reporter shows up. At this point, there is no need for the pop up to remain... well, popped up.

VS Code version: Code - Insiders 1.26.0-insider (c86cab2211d6dce686e5c89934d915b1e020ba9e, 2018-08-02T05:17:02.675Z)
OS version: Windows_NT x64 10.0.17134

**Comment by itamark** [comment]
Hey @ramya-rao-a - is there a way to open the OSS version as an Insiders build so I can see that feedback smiley?

**Comment by itamark** [comment]
@ramya-rao-a Great - I'll create a PR for this. Also, in the insiders build - the request a feature link goes directly to a [feature-request filtered version of the issues in github.](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request+sort%3Areactions-%2B1-desc)

**Comment by itamark** [comment]
@ramya-rao-a @RMacfarlane do you want the feedback to close also on clicking `Request a missing feature`?

**Comment by RMacfarlane** [comment]
@itamark Yes, I think it would make sense for the popup to close in both cases. Thanks for looking at this!

**Comment by itamark** [comment]
@RMacfarlane no probs! I'll add that to the same PR.

**Comment by itamark** [comment]
@RMacfarlane okay I added it to the PR. #55938 I put the popup directly in the click event handler instead of using an external action is that okay?
