### ISSUE TITLE
Progress: allow to report progress on the taskbar

### ISSUE THREAD

**Issue by howiempt** [microsoft/vscode#55719]
Please add a Taskbar option to ProgressLocation to allow progress of tasks to be displayed in the Windows taskbar (or wherever appropriate in other OS/push to electron API to handle).

eg. https://docs.microsoft.com/en-us/windows/desktop/shell/taskbar-extensions#progress-bars

**Comment by isidorn** [comment]
fyi @bpasero @tyriar

**Comment by Tyriar** [comment]
Looks like it's already supported by Electron https://electronjs.org/docs/tutorial/progress-bar
