### ISSUE TITLE
nodejs debug not working - sometimes...

### ISSUE THREAD

**Issue by a8775** [Microsoft/vscode#5571]
- VSCode Version: 1.0.0
- OS Version: Windows 10
- NodeJS: 4.1.1

Steps to Reproduce:
It happen on one computer sometimes on other never.... I'm not able to reproduce 100% on this one that it happen.

The effect of starting debugging is:
- on top debug panel that disappear after 2-3 seconds, 
- in debug console typical 2 lines:
```
node --debug-brk=36163 --nolazy server.js 
Debugger listening on port 36163
```

I would like to make some more research on this issue. Please give more details how to proceed - may be some docs?

**Comment by isidorn** [comment]
Please check out these docs https://code.visualstudio.com/docs/editor/debugging
If you still see the issue let us know and please find a small reproducable sample repository where the issue happens.
Closing for now, will reopen if more data is provided
