### ISSUE TITLE
Paused on exception text not translated

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5572]
- VSCode Version: 1.0.1-alpha
- OS Version:

Steps to Reproduce:

1. Set a breakpoint and start debugging

![pausedonexception](https://cloud.githubusercontent.com/assets/12900364/14688979/0b3129f2-06fa-11e6-8bda-fe3cd5fb0316.PNG)

"PAUSED ON .." is not being translated. It is translated correctly in 1.0 release.

**Comment by dbaeumer** [comment]
@isidorn ignore if there is a nls.localize. We haven't received any new translation input yet.

**Comment by isidorn** [comment]
There is a [localize call](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/browser/debugViews.ts#L289)
