### ISSUE TITLE
API to retrieve the entire terminal buffer

### ISSUE THREAD

**Issue by alpaix** [microsoft/vscode#55720]
VS Live Share extension needs to retrieve a terminal buffer to share it with collaboration session participants. Currently, the proposed API provides `Terminal.onDidWriteData` method allowing intercepting raw data written to the terminal instance. The problem is a lack of a method of capturing the data written prior to subscribing to `onDidWriteData` event.

Would it be possible to introduce a method of retrieving the entire accumulated terminal buffer?

**Comment by Tyriar** [comment]
I don't see a use case for this type of API outside of live share.

Can you just playback the data you've read out via `onDidWriteData`? If there is too much you could try limit it to the last x characters, that would probably work for the majority of cases, the main thing you would need to worry about is knowing whether you're in application mode or not.

**Comment by alpaix** [comment]
The problem is we attach our data listener upon user clicking on the share button. Typically it happens after a user opened a workspace and performed some actions in a terminal so that we don't get "historical" data written to the terminal from the moment it's been created.

**Comment by Tyriar** [comment]
@alpaix sure, but you could do it when you launch the terminal (provided https://github.com/Microsoft/vscode/issues/55777 is addressed). Also since there is a separate command for sharing you only need to do it for those, we don't have to worry about the extra overhead of gathering the buffer for all terminals, only for the few that are shared.

**Comment by alpaix** [comment]
This feature request benefits ongoing work over shared terminal improvements as we're leaning towards unconditionally sharing all of the terminals in read-only mode without requiring additional UI gesture. To achieve that we're going to attach data listeners to all open terminals at the moment share button is clicked by a user.

Another alternative would be to start listening immediately after the Live Share extension got activated (before a user decides to share a workspace). This approach would likely cause some performance penalty we'll have to address. Apart from the potential perf issue, we'll still miss initial data written to a terminal open at workspace load time prior to the extension activation event. Typically it's a shell header message.

**Comment by alpaix** [comment]
@Tyriar Would it be possible to fetch just the latest written shell prompt?

**Comment by Tyriar** [comment]
@alpaix VS Code doesn't even know where that is reliably. The data to send could be cut down more as you suggest, but whether that would result in an API that's generally useful and is the right API to expose (and commit to) is a different story.

**Comment by Tyriar** [comment]
Closing as out of scope since the workaround is to play back everything, an API to simply get the buffer would not be enough as it would miss out on various terminal modes, which buffer is active, etc.
