### ISSUE TITLE
Show appropriate error message when extension gallery service is not accessible

### ISSUE THREAD

**Issue by smujohnson** [Microsoft/vscode#55723]
Issue Type: <b>Bug</b>

Clicking the "Extensions" sidebar button shows nothing.  Searching for anything yields no results either.  (And the interface to show you that is pretty shoddy, doesn't really give you any text or indication that anything happened other than some small blue underline moving thing that is pretty ambiguous.)

https://i.imgur.com/9zyrk2s.png

I watched a YouTube video of someone's fresh install and it shows a giant list of Extensions so... not sure what is going on.

Thanks.

PS:  You get an error 500 from Github if you don't login first to submit this.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5 CPU         750  @ 2.67GHz (4 x 2664)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.99GB (11.83GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by smujohnson** [comment]
Solved.  This occurs if your LAN / proxy settings aren't working (a simple way to test is to try to load the web with IE or Chrome).

But I think VS Code should give you an indication that something is wrong, since it just says nothing.  No error messages or squat.

**Comment by ramya-rao-a** [comment]
The below was meant to log a warning to the console, but unfortunately this line of code is never reached as `query` method handled the errors internally and always returned a valid paged model.

https://github.com/Microsoft/vscode/blob/1cb059c76e7c43fb264f192312cc73864f5ab2f7/src/vs/workbench/parts/extensions/electron-browser/extensionsViews.ts#L113-L120

Fortunately, the fix is straight-forward. We can update the `query` method to return the error thrown by the `this.extensionsWorkbenchService.queryGallery` call. PRs are welcome.

**Comment by octref** [comment]
Now extension view shows this with no internet, which I assume is the behavior.

![image](https://user-images.githubusercontent.com/4033249/44882268-79362280-ac67-11e8-9c60-39fd58aab7c2.png)

**Comment by ramya-rao-a** [comment]
@octref And the console should have a detailed error
