### ISSUE TITLE
Inconsistent focus indicators with titleBarStyle: custom

### ISSUE THREAD

**Issue by DavidArchibald** [Microsoft/vscode#55721]
Issue Type: <b>Bug</b>

In context menus, when `"window.titleBarStyle": "custom"` is enabled, the "focus indicators" for a menu item (selected, hovered, and tabbed), are inconsistent. Multiple selections can be seen when selecting with the mouse, arrow keys, and tabbing.

This can be reproduced by hovering over an item in the explorer pane or anywhere else. When you hover over any item there is a light grey hovered effect along the dark grey "selected" effect placed by default on the first item. Simply put, the selected effect doesn't shift to the hovered item. Additionally using the arrow keys you can seperate a third "tabbed" effect displayed as a blue border.

Using the arrow keys will combine the selected effect and the tabbed effect, but not the hovered effect. The expected result is that all of these would be combined into one effect whenever one "dominant" effect changes.

Here is a screenshot of the issue, though the focus indicators can be in any order:

![capture](https://user-images.githubusercontent.com/19630496/43619269-bcbe2f9e-9681-11e8-9e50-768658df4667.PNG)

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:11.471Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.97GB (2.79GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by sbatten** [comment]
@DavidArchibald thanks for the feedback. this issue has been resolved in the latest insiders.
