### ISSUE TITLE
vs code be freese

### ISSUE THREAD

**Issue by hex-Puck** [Microsoft/vscode#55722]
Issue Type: <b>Bug</b>

sometimes vs code will be freeze on my work computer(no network), and can't do anything except move my cursor, even when I kill -9 this process and vs code can't been kill too! so I always need reboot my computer. that's too terrible

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:40:20.190Z)
OS version: Linux x64 4.15.0-29-generic

<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
QML|bbe|1.0.0
gitlens|eam|8.5.4
mdmath|goe|2.2.1
linter-gfortran|krv|1.3.1
vscode-language-pack-zh-hans|MS-|1.25.3
cpptools|ms-|0.17.7

</details>

**Comment by isidorn** [comment]
Please try to follow these steps to file a meanigful bug which we can do something about. Thanks a lot 

https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by ramya-rao-a** [comment]
Please follow the [wiki for Performance Issues](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to log the issue using the issue reporter. That will give us more information to work with. Also, read that wiki completely which can help in figuring out which part of VS Code is actually causing this issue.
