### ISSUE TITLE
Git: Support to create local branch from specific remote branch

### ISSUE THREAD

**Issue by Meir017** [Microsoft/vscode#55732]
Similar to the visual-studio feature:

Right now the way to do this would be to checkout the remote branch and then create a branch from there

![git-branch](https://user-images.githubusercontent.com/9786571/43630114-fdbc7222-9707-11e8-86f2-2993a7ddced3.gif)

**Comment by joaomoreno** [comment]
The `Git: Checkout to...` command will show you a list of branches. If you pick a remote branch, it will create a local branch and set it to track the remote one.

**Comment by Meir017** [comment]
this would require me to first checkout the remote branch

**Comment by joaomoreno** [comment]
Please try <kbd>F1</kbd>, `Git: Checkout to...`, pick a remote branch and let me know if that doesn't create a local branch.

**Comment by Meir017** [comment]
it does create a local branch.
I think I didn't explain the feature request correctly 😢 

for example:
When working on a new feature you create a branch from the remote master into your own local branch `my-feature` you have no need to actually create a local version of the `master` branch.
I never create a local branch tracking the remote `master` branch

**Comment by joaomoreno** [comment]
So, you want to create a branch based off a **specific** remote branch?

**Comment by roblourens** [comment]
I don't see a "Create Branch From" command, what happened to it?

**Comment by hemlok** [comment]
hey @joaomoreno, is there a way to set this branch to be the current branch by default? 🤔

**Comment by joaomoreno** [comment]
> hey @joaomoreno, is there a way to set this branch to be the current branch by default?

What does that mean? When running the `Create Branch...` command, that branch will be checked out.

**Comment by hemlok** [comment]
Sorry @joaomoreno for not being very clear! 

Right now when I run this command I'm prompted to choose which branch to branch off every time. I quite liked it when the command would use the current branch as the branch to branch, without me having to specify it. I can see how the new behaviour is useful, but is there a way to set the old behaviour as the default behaviour, so that I don't have to confirm that I want to branch off the current branch when making a new branch?

**Comment by joaomoreno** [comment]
> I quite liked it when the command would use the current branch as the branch to branch off of, without me having to specify it.

The current experience auto selects `HEAD`... so all you have to do is press <kbd>Enter</kbd> when asked which ref the branch should be created from.
