### ISSUE TITLE
Teminal Window

### ISSUE THREAD

**Issue by flashim** [Microsoft/vscode#55734]
Issue Type: <b>Bug</b>

The terminal window extends beyond it's size and covers part of the side bar if the side bar is kept on right.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4030U CPU @ 1.90GHz (4 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.93GB (0.96GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Projects\TPG\swimlaneDemo|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-nupkg|eri|0.0.8
nuget4code|ffo|0.0.2
beautify|Hoo|1.3.2
nuget-reverse-package-search|jes|0.1.68
docthis|joe|0.7.1
python|ms-|2018.7.1
team|ms-|1.136.0
debugger-for-chrome|msj|4.8.2
react-beautify|tai|0.3.0
nativescript|Tel|0.8.0

</details>

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
