### ISSUE TITLE
"filename (read-only) (read-only)" in title bar

### ISSUE THREAD

**Issue by alvise1988** [Microsoft/vscode#55730]
Version: 1.26.0-insider
Commit: 0c2d71e2bb9a020995729ab7d5d5f8e4e897e657
Date: 2018-08-03T05:18:49.586Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

---

After opening **any** file, in the title bar next to the file name the string "(read-only) (read-only)" is shown. Nonetheless, this does not prevent editing and saving the file correctly.

Windows 10
![image](https://user-images.githubusercontent.com/42038976/43628721-138eb6b0-96f3-11e8-8852-6f75206e776f.png)

Windows 7
![image](https://user-images.githubusercontent.com/42038976/43628793-3c96c64c-96f3-11e8-9428-18e070056862.png)

---

A (possibly) related issue: after opening any file, if you:
- go in the VSCode Explorer and click on the name of the same file

OR
- click on the file name on the tag

the string "(read-only)" appear next to the file name on the **tag** of the open file.

Windows 10
![image](https://user-images.githubusercontent.com/42038976/43629135-4fef1978-96f4-11e8-9ccb-c4d39d297a4f.png)

Windows 7
![image](https://user-images.githubusercontent.com/42038976/43629131-47e8d4b2-96f4-11e8-8694-3b1025c13e28.png)

**Comment by joaomoreno** [comment]
@isidorn A few duplicates already, wanna look into this?

**Comment by joaomoreno** [comment]
Repro steps:

1. Open file A
2. Open file B
3. Open file A

It shows `A (read-only)`.

**Comment by weinand** [comment]
For me the "(read-only)" shows already when launching VS Code and a file was open in an editor
(and this happens on macOS too).

**Comment by massimonewsuk** [comment]
I'm experiencing this too

**Comment by andela-oadeniran** [comment]
I can confirm the same issue on vscode-insiders

**Comment by isidorn** [comment]
Fixed in latest out of source

**Comment by adrianpacala** [comment]
Can confirm, same issue on `Version 1.26.0-insider (1.26.0-insider)`, `0c2d71e2bb9a020995729ab7d5d5f8e4e897e657`.

**Comment by fchiumeo** [comment]
not issue on 
```
Versión: 1.26.0-insider
Confirmación: 4fa62b246c4305b4ca00507551f77c58135ce928
Fecha: 2018-08-03T12:32:37.823Z
```

**Comment by MeikTranel** [comment]
Yeah confirmed fixed on 

Version: 1.26.0-insider
Commit: 4fa62b246c4305b4ca00507551f77c58135ce928
Date: 2018-08-03T12:32:37.823Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by isidorn** [comment]
Thanks, adding verified label
