### ISSUE TITLE
VS Code is showing (read-only) in tab when it isn't

### ISSUE THREAD

**Issue by jmoeyersons** [Microsoft/vscode#55731]
Issue Type: <b>Bug</b>

Since the update of today (Fri 3 Aug 2018), the tabs in my projects are showing (read-only) with every file that I open. I can adapt the files as normal, but thus the (read-only) tag is not displayed correctly

VS Code version: Code - Insiders 1.26.0-insider (0c2d71e2bb9a020995729ab7d5d5f8e4e897e657, 2018-08-03T05:18:02.899Z)
OS version: Linux x64 4.15.0-29-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7440HQ CPU @ 2.80GHz (4 x 3433)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|15.29GB (3.37GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders --unity-launch|
|Screen Reader|no|
|VM|29%|

</details>Extensions: none

![screenshot from 2018-08-03 09-13-51](https://user-images.githubusercontent.com/15744141/43630259-133598ca-9700-11e8-85d1-2e04695f4c9e.png)

**Comment by dlong500** [comment]
appears to also be related to #55730.  Definitely a bug.
