### ISSUE TITLE
Middle click in explorer to open file pinned

### ISSUE THREAD

**Issue by jamesray1** [Microsoft/vscode#55733]
Issue Type: <b>Feature Request</b>

If I right click on a file in the sidebar, there is no option to open it it in a new tab. The next best option that I can use is to open it to the side (CTRL + ENTER) then drag it to the previous side so that I only have one side again. Additionally CTRL + T should also work to open it in a new tab, as well as scroll click.

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:10:37.273Z)
OS version: Linux x64 4.14.57-1-MANJARO

**Comment by isidorn** [comment]
If you just click on the file it shoulid open in the new tab. What is missing with that approach?
Maybe also try this 	
`"workbench.editor.enablePreview": false`

**Comment by jamesray1** [comment]
That doesn't consistently open a file in a *new* tab. If I open the program for the first time it will. But then after changing that setting it does consistently open the file in a new tab. But this is more of a patch fix, IMO. What new user is going to know that they can adjust this setting in order to do this?

**Comment by ramya-rao-a** [comment]
> But then after changing that setting it does consistently open the file in a new tab. But this is more of a patch fix

This feature is as-designed as it is helpful when browsing through different files.

> They have to read all the settings, and even then it isn't clear from "controls if opened editors show as preview..."

We can definitely improve the setting description such that searching for "open new tab", "open new editor" includes the setting in the search result. Feel free to send a PR for the same.

**Comment by jamesray1** [comment]
OK, you can do that, but I still think it would be good to enable scroll click to open in a new tab, as is done with web browsers, and removes the guesswork of looking in settings to see if there is a feature to enable to open a new tab.

**Comment by jamesray1** [comment]
Thanks @isidorn!

**Comment by bpasero** [comment]
@isidorn works nicely in the explorer but I wonder if other lists/trees should also support this. E.g. currently from a search result you cannot pin via middle click (whereas double-click consistently works across all places).

**Comment by isidorn** [comment]
@bpasero yeah this could be something to go for all "Open File" trees. Where do we keep that code which is shared for opening?

**Comment by bpasero** [comment]
@isidorn unfortunately there is no sharing of that code. We often talked about it (e.g. have some kind of `IListOpenListener` that would fire with the right set of instructions) but we never did it for mouse clicks at least.

**Comment by isidorn** [comment]
@bpasero should I create a debt item for that?
So we can start sharing since sharing is caring

**Comment by bpasero** [comment]
@isidorn yeah sounds good, we should at least get the consistent behaviour for middle click
