### ISSUE TITLE
Debug strings stay localized in old locale

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#55748]
I just noticed some of my debug world strings are localized. I might've experimented with the `de` locale some time ago... but my UI is now all in English except Debug:

![image](https://user-images.githubusercontent.com/22350/43636980-e4242150-9713-11e8-9925-8e3c7b490f0c.png)

**Comment by roblourens** [comment]
@joaomoreno have you seen this again? Was working with localization awhile ago and never saw this.
