### ISSUE TITLE
Open tabs and sidebar from where I left off

### ISSUE THREAD

**Issue by jamesray1** [Microsoft/vscode#55741]
Issue Type: <b>Feature Request</b>

Like in web browsers, it would be good to have an option in settings to open tabs, windows and the sidebar from where I left off when opening the program.

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:10:37.273Z)
OS version: Linux x64 4.14.57-1-MANJARO

**Comment by isidorn** [comment]
fyi @bpasero

**Comment by bpasero** [comment]
@jamesray1 that should already be the case, what are you missing?

**Comment by jamesray1** [comment]
Hmm that's weird, it opened the tabs from where I left off after closing and reopening and after restarting just now, but previously that wasn't happening... Will comment if it happens again.
