### ISSUE TITLE
Accessibility help widget has overflow

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#55747]
Issue Type: <b>Bug</b>

1. In a narrow width editor
1. Run the `Show accessibilty help` command

**Bug**
Notice that the widget is clipped

![screen shot 2018-08-03 at 11 46 16 am](https://user-images.githubusercontent.com/12821956/43636662-02dc988a-9713-11e8-825e-4d390e30e034.png)

VS Code version: Code - Insiders 1.26.0-insider (0c2d71e2bb9a020995729ab7d5d5f8e4e897e657, 2018-08-03T05:18:49.586Z)
OS version: Windows_NT x64 10.0.17728

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.98GB (1.65GB free)|
|Process Argv|C:\Users\matb\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|57%|

</details>

**Comment by alexandrudima** [comment]
FYI that widget is meant for Screen Readers (i.e. layout does not matter). Perhaps I could make the text transparent to avoid such issues.
