### ISSUE TITLE
Files are shown as "read-only" (twice)

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#55746]
Issue Type: <b>Bug</b>

After updating VS Code Insiders (user install), all files show up as read-only:

![2018-08-03_11-39-18](https://user-images.githubusercontent.com/1898161/43636485-7e72a9cc-9712-11e8-8002-3605c2e85952.png)

VS Code version: Code - Insiders 1.26.0-insider (0c2d71e2bb9a020995729ab7d5d5f8e4e897e657, 2018-08-03T05:18:49.586Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|5.88GB (3.19GB free)|
|Process Argv|C:\Users\weinand\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|33%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
mock-debug|and|0.27.0

</details>

**Comment by joaomoreno** [comment]
I also saw this...
