### ISSUE TITLE
Menu bar flashing on startup

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#55740]
VS Code Insiders:

- launch VS Code

Observe:
the VS Code menu bar briefly shows three menus, then it turns empty, and then it shows all menus:

![2018-08-03_11-01-10](https://user-images.githubusercontent.com/1898161/43634591-d427e978-970c-11e8-8b9a-a8289da3b890.gif)

**Comment by sbatten** [comment]
resolved via https://github.com/Microsoft/vscode/commit/1a1b92fbd020353051b51d2efa2dd88a63416a26
