### ISSUE TITLE
Add code action for unknown debug types

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#55742]
Issue Type: <b>Feature Request</b>

That could open the extension viewlet with a query for that type.

VS Code version: Code - Insiders 1.26.0-insider (0c2d71e2bb9a020995729ab7d5d5f8e4e897e657, 2018-08-03T05:12:27.609Z)
OS version: Darwin x64 17.7.0

**Comment by isidorn** [comment]
Would you expect a quick fix in the launch.json or an action in the dialog once you get the "unkown debut type" error? Or maybe both?

**Comment by chrmarti** [comment]
I had a QuickFix in mind. Both might make sense.

**Comment by isidorn** [comment]
That makes sense and I like the idea, let's assign it to august

**Comment by isidorn** [comment]
Will not have time to tackle, moving to on-deck
