### ISSUE TITLE
[html] Add `wrap_attributes_indent_size` and `aligned-multiple options`

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#55743]
jsbeautify has new options `wrap_attributes_indent_size` and `aligned-multiple` options.

There's also a new proposal https://github.com/beautify-web/js-beautify/issues/1404 to reorganize all these settings.

**Comment by sandy081** [comment]
@aeschli What are the steps to verify this?

**Comment by aeschli** [comment]
To verify:
- create a html snippet with an element that has many attributes
- change the wrap line length to something small
- format and observe how the attributes are differently aligned with the various settings for 'html.format.wrapAttributes`

`aligned-multiple` adds as many attributes on the same line as possible, and aligns nicely after breaking the line.

I'll remove 'wrap_attributes_indent_size'. I don't know really what it does.
