### ISSUE TITLE
VS Code is showing suggestion even if they are not related to words and apparently also applying them after entering shift + 9?

### ISSUE THREAD

**Issue by jatin11gidwani** [Microsoft/vscode#55756]
I am trying to learn gulp and so I am using rename() method but VS Code is showing those unrelated suggestion as shown in the image and as I am typing shift + 9 to make brackets for the method but instead of brackets its replacing what I am writing with the first suggestion and so it is changing rename to requestAnimationFrame. Why this behavior is happening and how can I fix this ?

![capture](https://user-images.githubusercontent.com/22614199/43642480-5519a9b2-9745-11e8-9113-d9041a14ba1a.JPG)

**Comment by mjbvz** [comment]
`(` is treated as commit character for method suggestion. Typing it will accept the current suggestion

Press escape to cancel out of the current suggestion before pressing `(` or disable commit characters entirely by setting `"editor.acceptSuggestionOnCommitCharacter": false`

**Comment by jatin11gidwani** [comment]
thanks a lot, it works :D
