### ISSUE TITLE
"Device not configured" when debugging with "debugServer"

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#55764]
I've been seeing this a lot lately, I don't know why. Not all the time but when it starts happening, it's very consistent.

- Set 'debugServer' and start a DA in server mode
- Start debugging
- It fails to start with the message "Device not configured"
- If I try to start again, it says "There is already a debug configuration 'Run' running." and I have to reload the window.

Often, debugging works the first time in a vscode instance, then fails the second time.

Let me know how I can help debug it

![image](https://user-images.githubusercontent.com/323878/43649539-43e3006a-96f2-11e8-8933-f05d8967d886.png)

![image](https://user-images.githubusercontent.com/323878/43649560-5093b368-96f2-11e8-908d-2f8663b7cd70.png)

**Comment by roblourens** [comment]
Oh this also stopped reproing when I disabled Live Share.

**Comment by isidorn** [comment]
Please file here, thanks https://github.com/microsoft/vscode-cascade
