### ISSUE TITLE
Refocusing visual studio code is sluggish - 1-5 seconds lagg

### ISSUE THREAD

**Issue by steinhaug** [Microsoft/vscode#55760]
Issue Type: <b>Bug</b>

I just started noticing that whenever I switch window forcus from VSC til something else and back it takes several seconds for the VSC to "recover".

Say I switch back to VSC and start by selecting any text or click anywhere to place the carret/cursor, this takes 1-5 seconds before it completes every time. I am on a pretty fast PS with 64GB ram so I am not sure what made this change. It started today - I remember I did upgrade just now aswell.

Hopefully this is helpful for someone.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3970X CPU @ 3.50GHz (12 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.91GB (56.29GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.1.2
bracket-pair-colorizer|Coe|1.0.59
githistory|don|0.4.2
gitlens|eam|8.5.4
php-debug|fel|1.12.3
vscode-auto-open-markdown-preview|hnw|0.0.4
smarty|imp|0.3.0
vscode-apache|mrm|1.1.1
vscode-docker|Pet|0.1.0
markdown-checkbox|PKi|1.3.0
material-icon-theme|PKi|3.5.2
sass-indented|rob|1.4.9
html-preview-vscode|tht|0.1.1

(2 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Can you also reproduce this behavior with vscode insiders https://code.visualstudio.com/insiders/
If yes here are some more steps on how to file a good performance issue https://github.com/Microsoft/vscode/wiki/Performance-Issues
Thanks!

**Comment by steinhaug** [comment]
Thank you for that tip on vscode insiders, I downloaded it and installed all the plugins that I have currently on the other vscode. At the moment I am not able to reproduce theese problems, the vscode insiders seems to work as I would expect when changing windows.

I will try to go through the steps on the performance link you posted, it should be a good lesson aswell into debugging stuff something I havnt been very up to date with. Great tip, thanks!

**Comment by isidorn** [comment]
Cool. Let us know if you find something.

**Comment by ramya-rao-a** [comment]
@steinhaug Since its been a week and we havent heard back from you, we are assuming that things are going well, and closing this issue.

The current Insiders will be released as stable early next week.

Happy Coding!
