### ISSUE TITLE
Searching takes a lot of time after update

### ISSUE THREAD

**Issue by faiz121** [Microsoft/vscode#55769]
Issue Type: <b>Bug</b>

Searches with in project directory using VS Code is taking too long

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 5, 5|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_77843|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-custom-css|be5|2.7.1
simple-react-snippets|bur|1.2.2
solargraph|cas|0.17.6
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.12
gitlens|eam|8.5.4
prettier-vscode|esb|1.5.0
auto-rename-tag|for|0.0.15
ruby-rubocop|mis|0.7.0
Ruby|reb|0.19.0
sass-indented|rob|1.4.9
haml|vay|1.0.1

(3 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Text search, or quickopen?

Can you give more details? Is this a large folder? Also see this wiki page: https://github.com/Microsoft/vscode/wiki/Search-Issues#slow-search-rg-running-for-a-long-time-or-consuming-lots-of-cpumemory
