### ISSUE TITLE
after opening user settings, all Vim keybindings are disabled

### ISSUE THREAD

**Issue by mvolkmann** [Microsoft/vscode#55768]
Issue Type: <b>Bug</b>

The Vim keybindings were working fine. Then I opening User Settings. From that point all all Vim keybindings stopped working.

VS Code version: Code - Insiders 1.26.0-insider (4fa62b246c4305b4ca00507551f77c58135ce928, 2018-08-03T12:25:19.888Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.21GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_1532278|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.59
vscode-markdownlint|Dav|0.19.0
vscode-eslint|dba|1.4.12
gitlens|eam|8.5.4
tslint|eg2|1.0.34
prettier-vscode|esb|1.5.0
flow-for-vscode|flo|0.8.2
auto-rename-tag|for|0.0.15
fish|gio|0.0.4
vscode-settings-cycler|hoo|1.0.1
vscode-go-to-file|jac|0.0.1
vscode-duplicate|mrm|1.2.1
Go|ms-|0.6.85
printcode|nob|2.3.0
vscode-versionlens|pfl|0.21.1
java|red|0.29.0
vscode-icons|rob|7.25.0
code-spell-checker|str|1.6.10
sort-lines|Tyr|1.7.0
vscode-java-debug|vsc|0.11.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.7.1
vscode-maven|vsc|0.10.0
vim|vsc|0.15.7
quokka-vscode|Wal|1.0.135
vscode-todo-highlight|way|1.0.4

</details>

**Comment by rebornix** [comment]
This issue was moved to VSCodeVim/Vim#3029
