### ISSUE TITLE
Controls are not visible when user try to perform uninstall action on the selected item from the installed extension list.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#5576]
- VSCode Version: 1.0.0.1-alpha
- OS Version: Windows10

Steps to Reproduce:
1. Launch app and press F1 to launch command palette.
2. Enter extension keyword and select installed extension option.
3. It will display the list of the installed extensions .
4. Select any item from the extension list and verify controls for "Readme", "License" or "Uninstall extension".

Actual: Controls are not visible.
![image](https://cloud.githubusercontent.com/assets/17735796/14690612/b7cb128e-0701-11e6-84e6-2d299af1cde7.png)

Expected: Controls should be visible for user to perform action on the selected item.
![image](https://cloud.githubusercontent.com/assets/17735796/14690520/53d0d764-0701-11e6-9039-d8155ae20a1f.png)

**Comment by joaomoreno** [comment]
I cannot reproduce. Any more details...?

**Comment by v-pavanp** [comment]
You can easily find the difference between kimbie Dark and light(Visual studio) theme when you launch the installed extension window from command palette and select any item from the list.
Find the below gif screenshot to get exact repro steps.
![extinstalledissue](https://cloud.githubusercontent.com/assets/17735796/14718481/c8195326-07ab-11e6-94e8-7eea6da62a42.gif)

**Comment by joaomoreno** [comment]
Got it! Thanks!
