### ISSUE TITLE
vscode update failed when a different user is using their own version

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#55775]
- Log in as user xyz, install user-level install, start code-insiders
- Log in as user rob, install global vscode, start it
- User rob gets an update
- Install fails, log says that code-insiders couldn't be killed. I assume it's trying to kill user xyz's instance

I don't know if that can be detected to be handled more gracefully or not, but in theory there shouldn't be a conflict right?

[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2258392/vscode-inno-updater.log)

**Comment by joaomoreno** [comment]
In theory, yes!

**Comment by Latupho** [comment]
Same issue as I've got. Solved by letting the user who installed the software, update it.
