### ISSUE TITLE
Custom Menus - Focus Rectangle Glitch

### ISSUE THREAD

**Issue by pushqrdx** [Microsoft/vscode#55773]
- VSCode Version: 1.26.0-insider
- OS Version: Windows 10 build 17134

Steps to Reproduce:

1. Open any context menu.

![image](https://user-images.githubusercontent.com/25884937/43657737-f2d198b6-9756-11e8-9d09-608fd4cfef74.png)

Notice the focus rectangle is glitching at the top and bottom of the context menu until you hover

![image](https://user-images.githubusercontent.com/25884937/43657793-1f3f47cc-9757-11e8-8e71-9d1e54f0c6d5.png)

**Comment by sbatten** [comment]
@pushqrdx Can you please verify that you are on the latest insiders? If you are and the issue is not resolved, can you specify your theme?

**Comment by pushqrdx** [comment]
@sbatten for some reason i wasn't on the latest insider version hence the issue. updating solved it so please feel free to close the issue.

**Comment by sbatten** [comment]
@pushqrdx thanks for letting me know
