### ISSUE TITLE
Bad Japanese (ja) translation for "Select All Occurences of Find Match"

### ISSUE THREAD

**Issue by espresso3389** [Microsoft/vscode#5577]
- VSCode Version: 1.0.1-insider

"Select All Occurences of Find Match" is currently translated as "一致項目のすべてのオカレンスを選択".
But it should be "すべての出現箇所を選択". At least, "オカレンス" is not a Japanese word.

![image](https://cloud.githubusercontent.com/assets/1311400/14692076/ccad8040-078f-11e6-8da8-096ddf98f9d2.png)

**Comment by johnliu2016** [comment]
@lukaschal Improper JPN translation in following locations

[find.nls.resx.lcl](https://monacotools.visualstudio.com/DefaultCollection/Monaco/_git/MonacoLocalization#path=%2FLocalize%2Fjpn%2Fvscode%2Fsrc%2Fvs%2Feditor%2Fcontrib%2Ffind%2Fbrowser%2Ffind.nls.resx.lcl&version=GBmaster&_a=contents)

      <Item ItemId=";selectAllOccurencesOfFindMatch" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[Select All Occurences of Find Match]]></Val>
          <Tgt Cat="Text" Stat="Loc" Orig="New" Appr="PreApproved">
            <Val><![CDATA[一致項目のすべてのオカレンスを選択]]></Val>
          </Tgt>
        </Str>
        <Disp Icon="Str" />
        <Modified By="snakamura" DateTime="2015-05-27T05:29:42Z" />
      </Item>

[findController.nls.resx.lcl](https://monacotools.visualstudio.com/DefaultCollection/Monaco/_git/MonacoLocalization#path=%2FLocalize%2Fjpn%2Fvscode%2Fsrc%2Fvs%2Feditor%2Fcontrib%2Ffind%2Fcommon%2FfindController.nls.resx.lcl&version=GBmaster&_a=contents)

      <Item ItemId=";selectAllOccurencesOfFindMatch" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[Select All Occurences of Find Match]]></Val>
          <Tgt Cat="Text" Stat="Loc" Appr="PreApproved" Orig="New">
            <Val><![CDATA[一致項目のすべてのオカレンスを選択]]></Val>
          </Tgt>
        </Str>
        <Disp Icon="Str" />
        <Modified By="ICizkova" DateTime="2016-03-10T16:02:42Z" />
      </Item>

**Comment by lukaschal** [comment]
Waiting for linguistic input.

**Comment by lukaschal** [comment]
Linguist confirmed new translation. Fixed now.

SRC: Select All Occurences of Find Match
NEW TGT: 一致項目のすべての出現個所を選択

**Comment by 5003** [comment]
consistency error: https://github.com/5003/vscode/commit/c5adff591e36ef4b4116a02ee674df9a9b455d53
