### ISSUE TITLE
Double click + shift click should select all words in range

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#55771]
On 1.25.1, with no extensions.

If I have text `Hello World`, and I do:

- Double click on `H`, so `Hello` is selected
- Shift-Click on `o`

In Word, Notepad, TextEdit, Chrome and many other apps: This would select over `Hello World`.

In Code, this selects `Hello Wo`.

**Comment by V-ed** [comment]
I personally prefer Code to select `Hello Wo` in your example rather than the suggested behavior of selecting the words in range.

If this functionality were to be implemented, I'd like to see it as an option rather than the only available behavior of `shift+click`.
