### ISSUE TITLE
New folder window search in files does not search in new folder opened

### ISSUE THREAD

**Issue by rojagit** [Microsoft/vscode#55783]
Ctrl+Shift+F - Search in all files in second opened folder still keeps looking at original folder to find matches 

- VSCode Version: Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:43:53.668Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64
- OS Version:
Win 8.1

Steps to Reproduce:

1. have one instance of VSCode running
2. open another folder and search for a file existing only in that folder - it doesnt find

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
I can't reproduce this, can you give more detailed steps?

**Comment by rojagit** [comment]
Hmm..you are right, I too couldn't repro now (in same 1.25) - I tried 2-3 times yesterday and it just wouldn't show up in the new window. Works fine now.

Although oddly, when simulating the same, Insiders seems to re-use the same Window without a warning that the other one would close. It is not even listed under workspace. Is this a bug ? (In 1.25 we have two separate instances of Code.)

Would be nice to have it listed as separate Windows in one instance of VSCode (as in IntelliJ)

**Comment by roblourens** [comment]
You might have set the `window.openFoldersInNewWindow` setting in stable
