### ISSUE TITLE
Peek editor pointlessly navigates to destination as well as presenting preview

### ISSUE THREAD

**Issue by tullo-x86** [Microsoft/vscode#55781]
Issue Type: <b>Bug</b>

## Reproduction
On a fresh install of VS Code:
- Open a JS/JSX file which references an identifier with more than one potential definition (I chose React's `Fragment` component as that identifier, as it was the first external example that worked in an arbitrary file in my project)
- Hold CTRL (on Windows) and hover — note the "Click to show 2 definitions" tooltip:
![image](https://user-images.githubusercontent.com/2888110/43664412-80254430-9732-11e8-9de0-67b688c427c9.png)

- Click the underlined identifier

## Expected behaviour
**Either:**
- The window navigates to the sole definition of the clicked identifier

**Or:**
- The peek editor appears, allowing the user to select which definition to navigate to

## Actual behaviour
- The window navigates away from the current context, **and** the peek editor appears, duplicating the view inline like so:

![image](https://user-images.githubusercontent.com/2888110/43664342-3eae461e-9732-11e8-9cf2-5b8e2fdddec1.png)

**This is pointless, because the view sacrifices the code's visual flow, without the benefit of keeping your position in the file you are currently viewing.**

I believe this is the source of frustration that led to issues like https://github.com/Microsoft/vscode/issues/34755 and https://github.com/Microsoft/vscode/issues/53164 being opened.

_Edit: s/symbol/identifier/_

___

VS Code version: Code - Insiders 1.26.0-insider (4fa62b246c4305b4ca00507551f77c58135ce928, 2018-08-03T12:32:37.823Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.88GB (15.88GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by chillitom** [comment]
I see a similar issue when using Typescript functions declared in the following fashion:

```typescript
export const observeChangesAll = (collectionPath: string): Observable<firebase.firestore.DocumentSnapshot[]> => ... 
```
This results in two definitions being found on the same line, see below.  The editor jumps to the definition but insists on displaying the peek window as well.

![image](https://user-images.githubusercontent.com/74433/43674773-797ffa96-97d0-11e8-81b2-050738ca9d6b.png)

This is rather frustrating as it simply gets in the way and reduces the utility of _Find All References_

**Comment by mjbvz** [comment]
@tullo-x86 Sounds like #53341. Are you using an older version of TypeScript in your workspace?

**Comment by tullo-x86** [comment]
@mjbvz: The dual definition for that identifier is not the problem; it is merely an easy way I found to reproduce the issue. The problem is that the IDE both navigates and opens the peek editor, in the same operation.

**Comment by tullo-x86** [comment]
@chillitom: While that specific circumstance makes this issue present itself, fixing the dual reference in the codebase will only mask the real problem, which is that **the IDE takes two actions where either alone would be an appropriate choice**.

**Comment by Adondriel** [comment]
Mine is doing this too, on version 1.26.0.
I press f12 on the function in one file, a nodejs app (using .js files, of course), export style is to do a module.exports = {list of exported functions};
![image](https://user-images.githubusercontent.com/1113496/44236377-c780f700-a17a-11e8-8517-8d207ad3adce.png)

It goes to the method, then inserts the peek definition on the same line that i'm going to! Super annoying!

**Comment by tullo-x86** [comment]
@mjbvz: What information can I offer for you to rescind the "needs more info" label on this issue? It seems pretty cut-and-dry:

```
if (definitions.length == 1)
  navigateTo(defintions[0]);
else
  showPeek(definitions);
```

**Comment by mjbvz** [comment]
Please share a complete code / project example
