### ISSUE TITLE
change the icon to look more different than visual studio

### ISSUE THREAD

**Issue by graph** [Microsoft/vscode#55788]
The icon just looks identical to visual studio but a different color. It's been more than a month and I'm still hitting the wrong icon.

**Comment by MicrosoftEurope** [comment]
Hello Ben,

    Could you please include a printscreen with the icon you see?

сб, 4 авг. 2018 г., 1:32 vscodebot[bot] <notifications@github.com>:

**Comment by graph** [comment]
It's the long weekend in Canada, I'll do so Tuesday. The icons do look different but they are also very similar and have a very similar feel. Both are based on the infinite symbol or a fish depending how you look at it.

Happy long weekend :)

**Comment by MicrosoftEurope** [comment]
Looking forward to your message...

Peaceful weekend !

сб, 4 авг. 2018 г., 1:42 Ben Manashirov <notifications@github.com>:

**Comment by graph** [comment]
![vscode vs](https://user-images.githubusercontent.com/1088059/43780553-db544286-9a28-11e8-8ed4-ad95f13f92ee.png)

VS Code and VS look nearly identical, the only difference is different color and an extra line in VS.

**Comment by auchenberg** [comment]
Hi @graph 👋 

Our VS Code logo is a part of the "Visual Studio Family", and is designed to look similar. You can read more about our logo here, https://code.visualstudio.com/blogs/2017/10/24/theicon

Closing, as this is intended.
