### ISSUE TITLE
Search in all files to find matches immediately

### ISSUE THREAD

**Issue by rojagit** [Microsoft/vscode#55782]
Ctrl+Shift+F - Search in all files in opened folder to find matches immediately instead of waiting for us to hit enter - as in IntelliJ

**Comment by roblourens** [comment]
We have looked at this in the past but our search is not fast enough and the tree view on the frontend is also not fast enough to support it.

**Comment by rojagit** [comment]
I guess there is a trade-off between IJ indexing for long in the foreground vs editor being available for use huh...maybe someone needs to come up with a way to do this (indexing) in lo-prio in the bkgrnd
