### ISSUE TITLE
Show setting enumDescriptions inside new dropdown control

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#55796]
![image](https://user-images.githubusercontent.com/323878/43669986-366f763a-973c-11e8-80ac-171b3a2aed69.png)

- The doc part is shown on hover, if that value has an enumDescription. Not all do, so maybe we show an (i) indicator on ones that do

Can we use the suggest widget, or is it easier to build on top of the menu control?

Accessibility.

**Comment by cleidigh** [comment]
@roblourens 
would you expect a key to pop up the detailed description for keyboard users/vision impaired?

**Comment by cleidigh** [comment]
@roblourens 
just thought of another thing, I may be wrong but I think I noticed your screenshot is the Linux platform,
that brings up the important aspect that the select box (custom) is not used on OS X.  Adding
pop-up descriptions to the native select box options probably won't work or at best will be noticeably different.  

I added myself to the assignment to help on this if you want to modify the select box with help

**Comment by roblourens** [comment]
@cleidigh, we are investigating something like this this month - it would probably use a form of the suggest widget or custom select box widget. Do you know why we don't use the custom select box widget on MacOS?

**Comment by cleidigh** [comment]
@roblourens 
Early on when I started the new dropdown the team felt that retaining the native feel on OS X
was preferred.  I think at this point I would like to do what I thought of in the beginning,
adding a user setting to let the user decide which to use.  No current limitation , I have always tested
new additions on OS X just in case.

If you want to vote for this in the team agrees , I will implement it.

**Comment by roblourens** [comment]
Got it. We might want to keep the current behavior for other dropdowns. I know that people still prefer native controls where possible. But maybe this will put us over the edge. I'll keep thinking about it.

**Comment by JacksonKearl** [comment]
Notes from sitdown:
- Perf: Making a Monaco for each input could be costly. 
- Styling: the dropdown should be the same length as the input, and look at whether the details should be at bottom.
- General approach: Hidden monacos cause potentially strange artifacts, and aren't a particularly clean solution. Being able to type, but not seeing what you're typing, could be unexpected.

Comments:
- Perf: I timed the load of w/ monacos vs without, and there was no difference.
- Styling: I think putting the details at bottom always makes sense, and it makes the flow of the page with resizing a lot simpler. @roblourens what makes you prefer side?
- Approach: I see three ways forward: keep this; keep the suggest widget but separate it out from requiring a monaco; make a bespoke dropdown widget. Of these I think first and third make the most sense, as separating the suggest widget seems like a big change and it would be a lot of code change to a pretty critical feature. Keeping this as is doesn't have downsides to me right now, as I cant measure a performance impact and as of yet there haven't been any big changes to the general suggest framework needed for this dropdown. Making a bespoke markdown-details-enabled SelectBox widget is probably the "cleanest: solution, but it would require a not-insignificant amount of engineering work, and much of that work would be in re-implementing behavior already present in the existing Suggest widget.

**Comment by roblourens** [comment]
Links in enumDescriptions:

- `files.autoSave`
- `editor.wordWrap`

Options
- Don't linkify setting names in enumDescriptions
- Advise against using links in enumDescriptions
- Come up with a different design that makes it easier to click these links
- Detect links in enumDescriptions and render them in the description, instead of in the dropdown
