### ISSUE TITLE
Settings editor scrollbar should be along far right edge

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#55795]
It used to be like that but the layout got more complicated.

**Comment by itamark** [comment]
I think I figured out a decent solution. It'll be ready likely today.

**Comment by roblourens** [comment]
Awesome :)

**Comment by roblourens** [comment]
Well having that space scrollable is a big part of my motivation for doing this. Sorry that the original issue didn't spell that out, but I want to change the layout so that the scrollable area includes that whole margin.

**Comment by itamark** [comment]
I mean, if the 1000px max-width isn't a must - removing that would solve this.

**Comment by itamark** [comment]
@roblourens There - I added another commit that seems to solve this completely.
