### ISSUE TITLE
[razor] inconsistent syntax highlighting 

### ISSUE THREAD

**Issue by btskyy** [Microsoft/vscode#558]
`<h2>@ViewData["Title"]</h2>` causes incorrect tag highlighting. Fixed by any html text string following it such as `<vsfix>&nbsp;</vsfix>` Reproducible in multiple and default themes. 

![screen shot 2015-11-24 at 10 47 06 am](https://cloud.githubusercontent.com/assets/175955/11377021/ca6dbf32-9298-11e5-8e4c-ecae784ce201.png)
![screen shot 2015-11-24 at 10 47 32 am](https://cloud.githubusercontent.com/assets/175955/11377022/ca6f6242-9298-11e5-9811-812311552104.png)

**Comment by aeschli** [comment]
The grammar now recovers after `<h2>@ViewData["Title"]</h2>`. But `</h2>` is colorized strangely. I created https://github.com/demyte/language-cshtml/issues/12
