### ISSUE TITLE
Explore how setting categories are formatted

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#55800]
This came up in https://github.com/Microsoft/vscode/issues/54690#issuecomment-408962237 and https://github.com/Microsoft/vscode/issues/55616#issuecomment-410313495

tl;dr, we show settings with some category context that's dynamically computed based on the sections its in. In the flat search mode, we show the full category from the setting key but not the TOC category.

- Should we show the TOC category somewhere in the flat search mode?
- ~~Should the category with multiple components be formatted differently? e.g. instead of `Editor.Hover: Delay`, `Editor > Hover: Delay` or something like that? Not a fan of the dot here especially when a component contains spaces. `Workbench.Command Palette: History` looks wrong~~
- ~~Since we updated the category opacity to meet color contrast guidelines, the categories are harder to skim/parse out visually. Anything we can do about that?~~
- Acronyms like IE and CSS should be formatted in all caps, where they are extracted from the setting key.

**Comment by beastdestroyer** [comment]
Hi @roblourens, I prefer the arrow, I think it'd be a better choice since it'll show a hierarchy of the settings better and it won't get weird like you mentioned.

Also for the colour contrast, what about when you click on a setting, the background of that box transitions to something else? 

Maybe add some hr tags to denote ends/beginnings of sections too?

**Comment by roblourens** [comment]
@misolori we lost some of the color contrast in the category, to fit the color contrast accessibility guidelines. I thought the setting names got harder to scan when we made that change. Do you think it would be ok to use the brighter "highlight" white color from the section titles and TOC selected item for the setting label?

Would look like this:

![image](https://user-images.githubusercontent.com/323878/44064323-44e7fbb2-9f19-11e8-9ab2-573590db6594.png)

**Comment by roblourens** [comment]
> Should we show the TOC category somewhere in the flat search mode?

Feels too noisy, redundant in some cases.
