### ISSUE TITLE
VS Code freezes when using integrated Powershell terminal

### ISSUE THREAD

**Issue by keesvanbochove** [Microsoft/vscode#55813]
Issue Type: <b>Bug</b>

- Open an interactive Powershell console
- Run a few commands
After a few minutes, VS Code freezes and gives a dialog box with "The window is no longer responding", and the only option is to force exit and restart VS Code completely.
I tried this also with all extensions disables, and got the same behaviour.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (0.91GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
json-tools|eri|1.0.2
kubernetes-snippets|ipe|0.1.9
vscode-kubernetes-tools|ms-|0.1.11
Go|ms-|0.6.85
vscode-docker|Pet|0.1.0
vscode-yaml|red|0.0.14
jinja|who|0.0.8

</details>

**Comment by keesvanbochove** [comment]
This happened after upgrading to 1.25.1 and was not an issue before, but I'm not sure what my previous version was.

**Comment by keesvanbochove** [comment]
![afbeelding](https://user-images.githubusercontent.com/373418/43675088-802eecea-97de-11e8-8d83-ba8db62a8ddc.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/53782
