### ISSUE TITLE
Hover on a file name in explorer should display file name

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5581]
- VSCode Version: 1.0.1-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Shrink the explorer window to where some file names are cut off and show an ellipsis.
2. Hover over a file.

Hover should show a message with the file name like this:
![hoverfilename](https://cloud.githubusercontent.com/assets/12900364/14693220/d295786a-0711-11e6-81bc-ee252fd791c8.PNG)

**Comment by Tyriar** [comment]
Verified, @bpasero it shows the full path instead of the filename though, not sure if this was intentional.

**Comment by bpasero** [comment]
Yes it was, fixes other issues 👍
