### ISSUE TITLE
Custom titlebar setting not respected

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#55819]
- VSCode Version: 1.25.1
- OS Version: 10.13.5

I have `"window.titleBarStyle": "custom"` in my settings, but this setting is not respected in the window that gets opened when debugging extensions:

<img width="962" alt="screen shot 2018-08-04 at 18 22 42" src="https://user-images.githubusercontent.com/1812093/43678433-90dfc7d2-9813-11e8-8d79-0a92b7531885.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
@bpasero there are several blocks for using the custom titlebar on macOS. I don't think I introduced a new one so maybe you can explain the reasoning for this one.

**Comment by bpasero** [comment]
You cannot move the window when devtools is opened and you have a custom title. This is a known bug in Electron that forces us to behave like this.
