### ISSUE TITLE
Support folding multi-line brace-less arrow functions

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#55817]
- VSCode Version: 1.25.1
- OS Version: 10.13.5

Especially when working with React I often tend to write multi-line arrow functions without curly braces, but they can't be folded:

<img width="210" alt="screen shot 2018-08-04 at 18 09 29" src="https://user-images.githubusercontent.com/1812093/43678311-8e8c3c4c-9811-11e8-9046-2f199a4f6a69.png">

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#26661
