### ISSUE TITLE
The Dollar sign does not have its own color scope

### ISSUE THREAD

**Issue by amiganno** [Microsoft/vscode#55829]
VS Code 1.25.1
Windows 10

Hello there, I just moved from sublime text and trying to make my own Monokai theme and realized that the Dollar sign `$` doesn't have a color scope. In sublime text, usually it scoped under `variable.other.dollar.only` or `punctuation.dollar`

![dollarsign](https://user-images.githubusercontent.com/42104746/43682241-032a2822-986f-11e8-8fab-d9ce07a8d88e.png)

Thank you

**Comment by mjbvz** [comment]
`$` is just an identifier. An extension / injection grammar could add this if you really `$` to have a unique scope in js files
