### ISSUE TITLE
Platform-specific settings

### ISSUE THREAD

**Issue by ladyrick** [Microsoft/vscode#55820]
Setting item "window.menuBarVisibility" should be "window.menuBarVisibility.windows", and exists on all platforms(windows, linux, osx).

When I copy the setting file (contains "window.mentBarVisibility") from windows to mac, vscode would give a warning: "Unknown configure setting". This almost drive me crazy.
I hope this configure setting would exists on all platforms, including windows, linux and osx, so that the warning would not exist.
However, this setting is only valid on windows. So I think it would be change to "window.menuBarVisibility.windows".

**Comment by sbatten** [comment]
@roblourens since this applies to many settings

**Comment by roblourens** [comment]
Dupe of https://github.com/Microsoft/vscode/issues/5595
