### ISSUE TITLE
Open Editors: Files labled read-only but they are not.

### ISSUE THREAD

**Issue by derekwallace** [Microsoft/vscode#55822]
Insiders latest release.

this has started in the last few days.
The Open Editors files are being marked as read-only.
they are not. i can save the file to disk.

![image](https://user-images.githubusercontent.com/5574230/43678994-40a09bbe-9815-11e8-8a9b-e9bc63d52ea9.png)

**Comment by derekwallace** [comment]
note. the files are from a source control repository.
the files are normally read-only. i make the writeable outside Code. but it doesnt notice.

**Comment by isidorn** [comment]
Fixed in latest
