### ISSUE TITLE
Format On Save moves the cursor to the bottom when editing SCSS file.

### ISSUE THREAD

**Issue by nchanged** [Microsoft/vscode#55823]
Issue Type: <b>Bug</b>
![formatonsave](https://user-images.githubusercontent.com/1629088/43679403-b81d56be-9824-11e8-857b-69f992316014.gif)

When hitting `save` with `formatOnSave` option the cursor jumps to the bottom when editing SCSS file. It cannot be reproduced with JSX for example. Calling the `format` action manually on the same file doesn't seem to trigger this behaviour.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
indent4to2|Com|0.1.2
pegjs-language|Sir|0.1.0
php-formatter|Sop|0.2.4
unity-tools|Tob|1.0.4
terminal-tabs|Tyr|0.2.0
unity-debug|Uni|1.3.0
unity-snippets|Ycl|0.1.2
vscode-languagetool|ada|3.8.0
vscode-languagetool-en|ada|3.8.0
project-manager|ale|8.0.0
shaderlabvscodefree|aml|1.1.0
Handlebars|and|0.4.1
vscode-color|ans|0.4.5
vscode-icontheme-nomo-dark|be5|1.3.6
php-debug|fel|1.12.3
php-pack|fel|1.0.1
live-html-previewer|hdg|0.3.0
github-pr|jas|1.0.0
docthis|joe|0.7.1
docomment|k--|0.1.2
vs-color-picker|lih|0.7.0
vue|liu|0.1.5
vscode-JS-CSS-HTML-formatter|lon|0.2.3
share|lyu|0.4.4
scratchpad|mac|0.0.3
python|ms-|2018.7.1
debugger-for-chrome|msj|4.8.2
vscode-code-outline|pat|0.2.1
vscode-icons|rob|7.25.0
code-settings-sync|Sha|3.0.0
trailing-spaces|sha|0.2.11
shader|sle|1.1.3
addDocComments|ste|0.0.8
launchterminal|tes|0.4.0
pegs|the|0.0.4
gitblame|wad|2.4.4

(2 theme extensions excluded)

</details>

**Comment by octref** [comment]
This is caused by extensions. If you run `code --disable-extensions`, this would not happen.

I suggest that you switch to another formatter than `vscode-JS-CSS-HTML-formatter`, for example, prettier: https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode
