### ISSUE TITLE
Scrolling up or down, causes a crash

### ISSUE THREAD

**Issue by pitos007** [Microsoft/vscode#55821]
Issue Type: <b>Bug</b>

Reaching top or bottom of the window when scrolling, causes a window crash.
Version: 1.25.1
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz (8 x 3506)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.94GB (24.37GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|2.17.1
flutter|Dar|2.17.1
anaconda-extension-pack|ms-|1.0.0
python|ms-|2018.7.1
java|red|0.29.0
vscode-yaml|red|0.0.14
vscode-java-debug|vsc|0.11.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.7.1
vscode-maven|vsc|0.10.0

</details>

**Comment by isidorn** [comment]
Please file this issue with reproducable steps. Like for what file are you seeing this.
Can you also reprodcue with vscode insiders?
https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions

**Comment by pitos007** [comment]
No luck with reproducing. I'll try to gather more info if it happens again.

**Comment by ramya-rao-a** [comment]
@pitos007 In that case, we'll go ahead and close this issue. Happy Coding!
