### ISSUE TITLE
Unrecognizable 'go' 

### ISSUE THREAD

**Issue by J-H-Developer** [Microsoft/vscode#55824]
Issue Type: <b>Bug</b>

1. Right-click on a file
2. Select ''Open in command prompt''
3. Enter ''Go run'' + name of file
4. Press enter

I get the following message:

'go' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.88GB (1.03GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
Go|ms-|0.6.85

</details>

**Comment by Tyriar** [comment]
What is go run meant to do?
