### ISSUE TITLE
Type 'classname' is not an array type or a string type. Use compiler option '--downlevelIteration' to allow iterating of iterators.

### ISSUE THREAD

**Issue by jeffsaremi** [Microsoft/vscode#55825]
- Typescript: 3.0.1 insiders
- VSCode Version: 1.26.0 insiders
- OS Version: Windows 10

I get the above message in the Problems window when I use an Iterator<> that I have added to my class
Tsc does not report anything on the command line and the all tests run fine. So I don't know if this is a vscode issue or I should take that up with the Typescript guys.

```
   for (const v of t) {
     result.push(v);
   }
```

I have added this option to my tsconfig file in my workspace:

   ```
"target": "es5",
    ...
    "lib": [
       "es2015", "dom", "es6"
    ],
   ...
   "downlevelIteration": true,

```

**Comment by jeffsaremi** [comment]
The issue exists in vscode 1.25.1 with tsc 2.9.2 as well.

**Comment by mjbvz** [comment]
Do you see this problem reported when running tsc 3.0.1 from the command line against that tsconfig?

**Comment by jeffsaremi** [comment]
Not able to reproduce in 3.0.1. I'll close this
