### ISSUE TITLE
Typescript 3 Project References: Go to Definition in a referenced project opens the file with path and file lower cased

### ISSUE THREAD

**Issue by tmueller** [Microsoft/vscode#55827]
Issue Type: <b>Bug</b>

### Typescript Version
3.0.1

### Problem
When using typescript 3s new feature of project references, going to the definiton of a symbol imported from a referenced project results in opening the file with its path and filename all lowercase. Sourcemaps look good, the filenames casing is preserved there.

### Steps to Repoduce
1. Create a Typescript project with project references 
2. import a symbol from a referenced project
3. F12 to Go to Definition

### Expected Behaviour
- opens the source file, where the symbol was imported from
- vscode treats the file as workspace file
  - highlighted in Explorer view
  - no path prefix in tab title

### Actual Behaviour
- opens the source file, where the symbol was imported from with the path and the filename all lower case
- vscode does not treat the file as workspace file
  - not highlighted in Explorer view
  - path prefix in tab title

### References
The problem was described also in https://github.com/Microsoft/TypeScript/issues/25508 and closed, but with no apparent result. @RyanCavanaugh suggested VS Code should be handling this.

### System
VS Code version: Code - Insiders 1.26.0-insider (4fa62b246c4305b4ca00507551f77c58135ce928, 2018-08-03T12:32:37.823Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (1.40GB free)|
|Process Argv|C:\Users\Thomas Müller\Downloads\VSCode-win32-x64-1.26.0-insider\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by AlexLandau** [comment]
We have a monorepo that is not using project references and is on TypeScript 2.9.2, but does use the `declarationMap` and `sourceMap` options, and "go to definition" gives the same behavior.

Another symptom is that no builds will happen when editing the file, which is quite annoying. The file can be edited and saved, however.

**Comment by JonWallsten** [comment]
I have the same issue. I'm someone in the VSCode team points me in the right direction I can try to create a PR.

**Comment by JonWallsten** [comment]
@mjbvz Any time in starting me up on this?

**Comment by cschleiden** [comment]
Looks like the lowercase path comes from the ts language service?

**Comment by tmueller** [comment]
Project references were supposed to be one of the bigger features of Typescript version 3.0, but this bug cripples this feature completely. Yet this bug seems to be ignored.

Even help was offered, so please @mjbvz can you help @JonWallsten getting started?

**Comment by mjbvz** [comment]
I'm pretty sure this was actually a TS server issue. With VS Code insiders, I tested go to definition using the same project without rebuilding on the following TS versions: 

- Broken in TS 3.0.x, 3.1.x, 3.2.x
- Works in TS 3.3-rc

Please test this using TS 3.3+. If you still see the problem, share an example project and I'll take a look

**Comment by JonWallsten** [comment]
@mjbvz Just tested. Can confirm it works now! So awesome!

**Comment by tmueller** [comment]
Awesome! @mjbvz This definitely works with TS 3.3.0-rc. It would have been interesting to know what caused the fix. Otherwise it could be only a conincidence. I skimmed thtorugh the latest commits of typescript, but was not able to find what fixed this issue.

**Comment by JonWallsten** [comment]
@tmueller I was also looking for it. Couldn't find what PR fixed it. Also unfortunately noticed that noticed that I still have the same issue, but caused by symlinks instead of these paths. What a bummer.

**Comment by dbaeumer** [comment]
Marking as verified based on https://github.com/Microsoft/vscode/issues/55827#issuecomment-458417514
