### ISSUE TITLE
Javascript Number.prototype.toLocaleString() method giving incorrectly formatted result when run in integrated terminal

### ISSUE THREAD

**Issue by rohan-paul** [Microsoft/vscode#55831]
- VSCode Version:  1.25.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

The below code gives me "123,456.789" where as the correct ouput should be "1,23,456.789" 

```
var number = 123456.789;

// India uses thousands/lakh/crore separators
console.log(number.toLocaleString('en-IN'));  // => 12,345,678.896
```
#### While, in Chrome-Developer console the same code is producing correct (expected) result

Per below documentation 
[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString)

here's the correct ouput : 

![image](https://user-images.githubusercontent.com/12703975/43683978-a9a95b1a-98b4-11e8-9549-11014b8693c1.png)

**Comment by roblourens** [comment]
> The below code gives me 

How are you running this code? In what runtime? Please give more detailed steps
