### ISSUE TITLE
i cannot find the solution

### ISSUE THREAD

**Issue by bedirhankose123** [Microsoft/vscode#55835]
Issue Type: <b>Bug</b>

Error = {"code":"ENOTFOUND","errno":"ENOTFOUND","syscall":"getaddrinfo","hostname":"localhost"}

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (2.06GB free)|
|Process Argv|/Users/bedirhankose/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-tr|MS-|1.25.2
anaconda-extension-pack|ms-|1.0.0
python|ms-|2018.7.1
vscode-yaml|red|0.0.14

</details>

**Comment by isidorn** [comment]
Please file this issue with reproducable steps
https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions

**Comment by ramya-rao-a** [comment]
This issue is being closed because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
