### ISSUE TITLE
Does it exist variable for expand emmet.extensionsPath?

### ISSUE THREAD

**Issue by baxebu** [Microsoft/vscode#55837]
Hello all! Does it exist variable for expand emmet.extensionsPath? I do not like the full way to write. There must be some sensible way.

instead
`"emmet.extensionsPath": "~/.config/Code/User/snippets/emmet",`
this:
`"emmet.extensionsPath": "${someUserSnippetsFolder}/emmet",`

**Comment by ramya-rao-a** [comment]
There is no variable called `someUserSnippetsFolder`. Are there any other variables you have tried?
