### ISSUE TITLE
Make the error message in the output window clickable to navigate to the error position.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#5583]
- VSCode Version:1.0.1-alpha
- OS Version: Windows10

Steps to Reproduce:
1. Launch app and open folder which contains node.js TS express project (or any other proj)
2. Configure tasks.json, tsconfig.json and launch.json to build and debug.
3. Build project with CTRL+SHIFT+B 
4. Verify output window.

Actual: Error message in the output window is not clickable to reach to the error position (Line number).
Expected: If output window is showing error message then make it clickable so that user can reach to the exact line number to fix the error.
![image](https://cloud.githubusercontent.com/assets/17735796/14693663/c2cac3e6-0715-11e6-8ee4-06c410bfea0a.png)

**Comment by dbaeumer** [comment]
@isidorn I give this to you since you worked on the output view. IMO we need to allow output channel clients to register link matchers. I know that @bpasero tried to solve the generically but that will either miss stuff or produce too many false positives.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/586
