### ISSUE TITLE
Weird unicode characters may get misrendered

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#55842]
- VSCode Version: 1.25.1
- OS Version: 10.13.5

Steps to Reproduce:

1. Open a new file
2. Set the language to `JavaScript`
3. Have `     ̷̸⁄∕／` in a line
4. Type `//` at the beginning of the line
5. 2 out of those 5 slashes kind of collapse into a single character

![Bug](https://user-images.githubusercontent.com/1812093/43688737-ef81bb66-98ee-11e8-84ec-ca54a6023a5e.gif)

It's definitely not really an issue, but you might want to look into that anyway.

**Comment by alexandrudima** [comment]
By copy-pasting and looking at their character codes, the 5 characters are:
* 'COMBINING SHORT SOLIDUS OVERLAY' (U+0337)
* 'COMBINING LONG SOLIDUS OVERLAY' (U+0338)
* 'FRACTION SLASH' (U+2044)
* 'DIVISION SLASH' (U+2215)
* 'FULLWIDTH SOLIDUS' (U+FF0F)

Typically fonts have two different implementations for Italic and Regular and I guess in this case (when adding a comment and converting the font to be Italic) the interpretation of the font rules ends up combining one or both of the first two characters.

For us, this is handled by the font rendering of Chromium. If you think this is a real bug, please open an issue against Chromium, but most likely it's one of those things...
