### ISSUE TITLE
"We recommend switching to our new User Setup ..." always pops up regardless of the fact whether it new setup was already installed or not

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/vscode#55840]
Version: 1.26.0-insider
Commit: 4fa62b246c4305b4ca00507551f77c58135ce928
Date: 2018-08-03T12:32:37.823Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

![image](https://user-images.githubusercontent.com/937933/43688082-5004c6f2-98b0-11e8-89cd-abb6f4153cf5.png)

**Comment by wsmelton** [comment]
I recall clicking on the sprocket/wheel and select the option to never show that again. I have not seen it show up after upgrades since the first release it was added.

**Comment by aleksey-bykov** [comment]
thats one way of doing it

**Comment by wsmelton** [comment]
What way are you expecting?

**Comment by aleksey-bykov** [comment]
installing what is suggested and never be bothered?

**Comment by joaomoreno** [comment]
Does the popup show up in the user-installed Code instance?

**Comment by aleksey-bykov** [comment]
@joaomoreno  that's exactly what happens

**Comment by joaomoreno** [comment]
Can you show me the full contents of `app\resources\app\product.json` located in your user installed Code?

Did the setup package ask for Administrator priviledges when you started it?

**Comment by joaomoreno** [comment]
What is the name of the setup .exe you downloaded?

**Comment by aleksey-bykov** [comment]
VSCodeUserSetup-x64-1.26.0-insider.exe

**Comment by aleksey-bykov** [comment]
```
D:\Downloads>D:\laptop\fciv.exe -md5 -sha1 D:\Downloads\VSCodeUserSetup-x64-1.26.0-insider.exe
//
// File Checksum Integrity Verifier version 2.05.
//
                MD5                             SHA-1
-------------------------------------------------------------------------
6d2924bff9647a62466696dba76774b0 c16397d5d8dfc6aa3e2932f3ee5d9f69e1a38b62 d:\downloads\vscodeusersetup-x64-1.26.0-insider.exe
```

**Comment by joaomoreno** [comment]
Interesting... those hashes do not match the hash of the user setup for our version `4fa62b2`, which you indicated in the first post. Can you reconfirm your VS Code version?

**Comment by aleksey-bykov** [comment]
man, no wonder versions don't match, i did reinstall so many times already and every time i get the same popup, hence this issue:
 
Version: 1.26.0-insider
Commit: 5fae91d61f12726e149fe5baed342eac2fbf8f88
Date: 2018-07-25T02:04:01.629Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by joaomoreno** [comment]
Interesting... version `5fae91d` also has different hashes for the setup file. Any chance you can upload that file somewhere I can download it from? (I am aware it is a large file).

**Comment by aleksey-bykov** [comment]
here are 3 different install packages that i used before i opened this issue:

https://drive.google.com/open?id=15MyfXy8CLKHaR_Aw2es48K_TDYSCRUeJ

**Comment by joaomoreno** [comment]
And when you tried the next, did you fully uninstall the previous? What was the last you used?

**Comment by aleksey-bykov** [comment]
here is the last one that i used on my **very clean just reinstalled desktop**:

- files: https://drive.google.com/open?id=1GmvkqmlXXEpPcru0_ULJtalEYyqdK9oQ

- version

Version: 1.26.0-insider
Commit: 4fa62b246c4305b4ca00507551f77c58135ce928
Date: 2018-08-03T12:32:37.823Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

showing the same problem every time i open it:

![image](https://user-images.githubusercontent.com/937933/43726569-81442844-996d-11e8-828c-3ecc356790a5.png)

**Comment by joaomoreno** [comment]
I still can't reproduce...

On that clean desktop, did you ever installed the system-wide setup? How did you eventually ended up getting a user-installable setup?

**Comment by aleksey-bykov** [comment]
1. i reinstalled the desktop anew
2. i downloaded and installed `VSCodeSetup-x64-1.26.0-insider.exe`: https://drive.google.com/open?id=17Eqe8Tgpv1S5mCvy8eGr0vZS41gnprbX

3. upon opening `code-insiders ./` i saw this:
![image](https://user-images.githubusercontent.com/937933/43727321-9aa5fec8-996f-11e8-9683-e7be53d3203a.png)

4. i followed the link and got `VSCodeUserSetup-x64-1.26.0-insider.exe`: https://drive.google.com/open?id=1QqjJWMhgtsw8lz3-M3NVi2yQbXtuWTJN

5. i closed my code insiders and i installed the packaged downloaded at step 4

6. i opened my code insiders again and i saw the same invitation to download and install `VSCodeUserSetup-x64-1.26.0-insider.exe` again

![image](https://user-images.githubusercontent.com/937933/43727467-10b73e38-9970-11e8-8f89-e060e08a0922.png)


7. i cam here and i opened the issue

**Comment by joaomoreno** [comment]
Yeah, I see... you now have both versions installed and the system-wide one wins the race in the `%PATH%` variable.

**Comment by joaomoreno** [comment]
I'll disable the popup if I detect that both are installed.

I suggest for you to uninstall the system-wide setup, and you'll be alright.

**Comment by joaomoreno** [comment]
Verification steps:

1. When installing the user setup after having the system setup installed, there should be a descriptive message informing the user of potential problems if both versions are installed.
2. When having both versions installed, the system version should warn that there's a user installed version as well.

**Comment by zouhair** [comment]
Just updated to the 1.26 version and started getting the same message.

**Comment by szukai** [comment]
Getting this either randomly whenever VS code decides to update OR whenever I decide to manually check for updates.

It does get horribly confusing.

----

Version: 1.26.0
Commit: 4e9361845dc28659923a300945f84731393e210d
Date: 2018-08-13T16:29:31.933Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by joaomoreno** [comment]
@zouhair @szukai You can click the gear icon ⚙ in the notification and choose `Never Show Again`.

**Comment by szukai** [comment]
So.. it's working as intended?

**Comment by joaomoreno** [comment]
@szukai I did not understand whether you have installed the user setup. Did you?

**Comment by szukai** [comment]
@joaomoreno I apologize, I don't quite follow. I used the VSCodeUserSetup-x64-1.26.0.exe to install VSCode and it's the only copy on my machine, if that's what you're referring to.

**Comment by joaomoreno** [comment]
Got it. You keep having this popup and it's **definitely** the only VS Code copy you have in your machine? Can you show me the contents of the `resources\app\product.json` file inside the installation folder?

**Comment by szukai** [comment]
@joaomoreno uploaded it here: https://ufile.io/wzu6n

Well I'm the only user of this machine, so the only way it could've "not been the only copy" is if I had a previous version and there wasn't a clean uninstall I guess? I haven't tried installing VSCode via any other methods besides the installer off the site (the laziest way).

**Comment by joaomoreno** [comment]
Are you absolutely sure you used `VSCodeUserSetup-x64-1.26.0.exe` to install the version which gave you this file? Can you send me that `VSCodeUserSetup-x64-1.26.0.exe` setup?

**Comment by szukai** [comment]
https://ufile.io/u6pp1

**Comment by joaomoreno** [comment]
If you open the Control Panel and go to Uninstall Programs, how many Microsoft VS Code rows do you see there?

**Comment by joaomoreno** [comment]
That installation is not the User one, since it would have `(User)` in the name. Thanks for the screenshot.

Uninstall that one and install the one you sent me.
