### ISSUE TITLE
Settings editor details takes two Escapes to close

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#55843]
- VSCode Version: 1.26 Insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Open New Settings editor and scroll done a description that has '...'
2. Click on the description to expand and show full description text.
3. Press Esc to close description

TOC selection moves to previous item in the TOC. Description is still expanded.

4. Press Esc again.

Now description panel is closed.

**Comment by roblourens** [comment]
Now N/A since settings can't be selected anymore.
