### ISSUE TITLE
Javascript symbol search / outline is truncated

### ISSUE THREAD

**Issue by m-brt** [Microsoft/vscode#5584]
- VSCode Version: 1.0.0
- OS Version: Windows 8

Steps to Reproduce:

Use this simple JS and press Ctrl-Shift-O

function myNewClass() {}
myNewClass.prototype.firstFunction = function() {};
myNewClass.theSecondFunction = function() {};

I tried different files in our project but it seems all found symbols/functions are truncated with ellipsis after 17 characers...

![outline](https://cloud.githubusercontent.com/assets/18584269/14694082/563cd624-0765-11e6-93bc-2041679f7472.png)

**Comment by dbaeumer** [comment]
The text comes back truncated from the TSServer. Moving to TS team.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#8238
