### ISSUE TITLE
Please Provide Full Integrated Git/GitHub Support

### ISSUE THREAD

**Issue by mqmashwani** [Microsoft/vscode#55845]
VSCode does not have full integrated support for  GitHub and Git. The full Git/GitHub experience can only be achieved by installing a variety of third party extensions. Please provide full built-in support including Github flavored markdown.

**Comment by ino76** [comment]
ctrl + `  -> opens nice terminal panel inside VSCode. From here I could use Git ...

**Comment by joaomoreno** [comment]
Closing this as it is a too loos item. Code, as an editor, aims to be helpful by providing core functionality. But because that's never enough, it has a comprehensive extension API to augment functionality. Not every user uses Git, much less GitHub.
