### ISSUE TITLE
Cannot read property when using markdown view and zen view

### ISSUE THREAD

**Issue by kinsuord** [Microsoft/vscode#55854]
Issue Type: <b>Bug</b>

Step
1. open .md file.
2. click the preview markdown buttom on the top-right and the markdown preview will be shown in the right part of the screen.
3. using ctrl + p to switch to preview on the left part of screen and now the right part will be empty
![image](https://user-images.githubusercontent.com/28496450/43702995-1189a8be-998e-11e8-8ce7-d6ca5c997cb0.png)
![image](https://user-images.githubusercontent.com/28496450/43703015-1f74dd22-998e-11e8-80fd-97c6f6c9e1a7.png)
4. use ctrl + p to switch another file and Toogle Zen mode
![image](https://user-images.githubusercontent.com/28496450/43703102-5f7f35d4-998e-11e8-9d22-a98cd7f44f5e.png)

and it will show the error
Cannot read property 'getWebContents' of undefined
if you want to switch back to normal mode , You will get more error

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (2.72GB free)|
|Process Argv|D:\VScode\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.0.3
vscode-markdownlint|Dav|0.19.0
vscode-eslint|dba|1.4.12
githistory|don|0.4.2
jquerysnippets|don|0.0.1
eppz-code|epp|1.2.41
json-tools|eri|1.0.2
matlab|Gim|0.9.0
gc-excelviewer|Gra|2.1.25
vscode-language-pack-zh-hant|MS-|1.25.5
python|ms-|2018.7.1
cpptools|ms-|0.17.7
veriloghdl|msh|0.3.3
debugger-for-chrome|msj|4.8.2
vetur|oct|0.12.5

</details>

**Comment by mjbvz** [comment]
Does this still reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?
