### ISSUE TITLE
vsCode performance issue when using protracor

### ISSUE THREAD

**Issue by x7Michi10x** [Microsoft/vscode#55855]
It seems to be an endless loop. The protractor-process is eating the whole memory which is available. It appears after starting protractor for the first time.

![screenshot](https://user-images.githubusercontent.com/17406687/43703722-00e4e968-995e-11e8-8b09-b6c0bb8530eb.PNG)

![screenshot2](https://user-images.githubusercontent.com/17406687/43703812-3bc5c6f6-995e-11e8-80ff-91e6768ab8a4.PNG)

Protractor is not running at the moment!

**Comment by isidorn** [comment]
Please file this issue in english with reproducable steps

**Comment by x7Michi10x** [comment]
Done.
