### ISSUE TITLE
Allow completion details to be selected

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#55853]
Issue Type: <b>Feature Request</b>

Currently when clicking or dragging on the completion details, it'll go away, making it impossible to select text inside it.

VS Code version: Code - Insiders 1.26.0-insider (4fa62b246c4305b4ca00507551f77c58135ce928, 2018-08-03T12:25:19.888Z)
OS version: Darwin x64 17.7.0

![un](https://user-images.githubusercontent.com/4033249/43702978-439568da-9910-11e8-9585-cc71381956d3.png)

**Comment by ozyx** [comment]
I also noticed this while investigating. Can confirm that the parameter hint widget text is not selectable. Right now I have a commit which is making the suggest completion details selectable. Just working on tidying it up as currently selecting the text causes keyboard shortcuts to no longer function (arrow keys for selecting a suggestion, esc key for exiting the popup).

**Comment by ramya-rao-a** [comment]
@luiszun @ozyx Below shows selection and copy possible in the parameter hint widget

![hover-select](https://user-images.githubusercontent.com/16890566/43871254-9b45c17a-9b30-11e8-8a3f-b7c56a9eb3d8.gif)

**Comment by luiszun** [comment]
@ramya-rao-a  It seems like that the widget you're showing there is the hover widget.
That one shows on src\vs\editor\contrib\hover\hoverWidgets.ts at showAt()

The one referred in the issue happens on suggestWidgets.ts, and the parameter hint on parameterHintsWidget.ts
Am I terribly lost?

I apologize for the text-only description, I need to find how to make those nifty gifs :)

**Comment by luiszun** [comment]
Good to know! I was worried that I was just adding confusion to this issue :)

**Comment by wistcc** [comment]
Actually, I wasn't able to mimic the hover widget behavior but [here](https://github.com/Microsoft/vscode/pull/56052) is another way to fix it.

**Comment by fbaligand** [comment]
I’m very interested by this feature!
