### ISSUE TITLE
Debug task runner: check for powershell.exe _and_ pwsh.exe to determine if "&&" can be used to chain commands

### ISSUE THREAD

**Issue by madig** [Microsoft/vscode#55852]
(Originally reported at https://github.com/Microsoft/vscode-python/issues/2329)

## Environment data

- VS Code version: 1.25.1
- Extension version (available under the Extensions sidebar): 2018.7.1
- OS and version: Windows 10 1803, x64
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.5 x64
- Type of virtual environment used: N/A
- Relevant/affected Python packages and their versions: N/A

## Actual behavior

Launching debug task uses "&&" to chain commands when shell set to "pwsh.exe". (Not sure if this happens with extensions disabled because I couldn't find another task I could readily use).

## Expected  behavior

Powershell only likes ";" to chain commands.

## Steps to reproduce:
1. In some Python project, configure this task:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Test script",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/test.py",
        },
    ]
}
```
2. Install Powershell 6.0.x
3. Set `"terminal.integrated.shell.windows": "pwsh.exe"` in configuration (PowerShell 6.0.x uses it to differentiate itself from the Windows Powershell)
4. "Start Debugging" with that task
5. Set shell to "powershell.exe" and repeat.

## Logs

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`)

```
> cd c:\[...]\fontParts && cmd /C "set "PYTHONIOENCODING=UTF-8" && set "PYTHONUNBUFFERED=1" && python c:\[...]\.vscode\extensions\ms-python.python-2018.7.1\pythonFiles\PythonTools\visualstudio_py_launcher.py c:\[...]\fontParts
61019 34806ad9-833a-4524-8cd6-18ca4aa74f14 RedirectOutput,RedirectOutput C:\[...]\fontParts/Lib/fontParts/fontShell/test.py "
At line:1 char:59
+ cd c:\[...]\fontParts && cmd /C " ...
+                                                           ~~
The token '&&' is not a valid statement separator in this version.
+ CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : InvalidEndOfLine
```

**Comment by octref** [comment]
Verified through code-review, that both powershell and pwsh are allowed.
