### ISSUE TITLE
Highlighted section on the navigation section of the settings(preview) does not match the current section that is actually being displayed

### ISSUE THREAD

**Issue by juancruzlepore** [Microsoft/vscode#55856]
Issue Type: <b>Bug</b>

-Open Setting(Preview)
-Scroll down until the "Applicacion" section
-Check that the highlighted section is not Application, it is Terminal, that is 2 sections above

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (11.10GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.4
plantuml|jeb|2.8.4
cpptools|ms-|0.17.7
PowerShell|ms-|1.8.2
vscode-icons|rob|7.25.0
cmake|twx|0.0.17

</details>

**Comment by juancruzlepore** [comment]
The auto assigned label is wrong, but I don't know if I can/ how to remove it.

**Comment by roblourens** [comment]
It highlights the first section that has a setting on the page. It might be at the very top of the page, and if you scroll a little further, it should highlight the next section.
