### ISSUE TITLE
font-family bug on custom UI zh-cn

### ISSUE THREAD

**Issue by ddrrqq** [Microsoft/vscode#55868]
Issue Type: <b>Bug</b>

I found a font bug,
If used this custom titleBarStyle,
the css class [monaco-menu-container] in workbench.main.css
[font-family] made Chinese Language Ugly.
Maybe I tried UNCHECKED css class in Dev tool,
or set Inherit, It is Good.

Maybe my OS Segoe UI bug,
but orther Application is normal,

I think this css class: [monaco-menu-container] -> [font-family] can be inherit.

Sorry for my English.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.10586

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.94GB (29.67GB free)|
|Process Argv|C:\Program Files\Visual Studio Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-caniuse|aka|0.5.3
vscode-javascript-snippet-pack|aka|0.1.5
vscode-language-pack-zh-hans|MS-|1.25.3
Go|ms-|0.6.85
material-icon-theme|PKi|3.5.2
vscode-todo-highlight|way|1.0.4
html-css-class-completion|Zig|1.17.1

(2 theme extensions excluded)

</details>

**Comment by ddrrqq** [comment]
![image](https://user-images.githubusercontent.com/20416681/43713150-25eacb54-99ab-11e8-96e0-c8b9d35ef68c.png)

That is default.

![default](https://user-images.githubusercontent.com/20416681/43713347-e34de60e-99ab-11e8-8de8-9ddf6480ac74.PNG)

It is OK!

And I just set 'Tahoma', it is unchanged, is liked default.

I don't what happend~~

**Comment by sbatten** [comment]
fixed via https://github.com/Microsoft/vscode/commit/9d3d20c3cd9ac1cdc6ea8df7a02a6f1303f3be5e

**Comment by ddrrqq** [comment]
Oh,
I see the 1.26.0 changed.
But it is not my point,
Chinese symbol use the default font: MSYH or named '微软雅黑'.

This is 1.26.0 style:
![image](https://user-images.githubusercontent.com/20416681/44215049-2444d780-a1a4-11e8-9948-858509699230.png)

but, not a TTF font style, this is Song or named '宋体'.
It is a Dot font like Consola~~

So now, this version maybe need refix~

Thanks your work!

**Comment by ddrrqq** [comment]
![image](https://user-images.githubusercontent.com/20416681/44217094-3d9c5280-a1a9-11e8-853a-b91fa6fee832.png)

**Comment by sbatten** [comment]
@ddrrqq the fix made 9 days ago is only in the latest insiders, not 1.26.0. Would you be able to verify that your issue is resolved in insiders? By the way, your graphic is very nice!

**Comment by ddrrqq** [comment]
Oh, Sooooooooooooooooooooooo Sorry for my focus on the stable version.

That is Good! It is work! 1.27.0 Insiders!
just the small translate bug.

![1 27 0](https://user-images.githubusercontent.com/20416681/44232863-ed3aea00-a1d4-11e8-8a2f-032da623df5a.png)

OK, Thank you very much!
I‘m looking forward next stable release!
Thank you, man!
nice your CSS

Thanks!!!
