### ISSUE TITLE
Focus not auto switched in order when multi-target debugging

### ISSUE THREAD

**Issue by LazarusX** [Microsoft/vscode#55862]
Issue Type: <b>Bug</b>

Steps to reproduce:
1. Create a simple client-server project with the following code:
```javascript
// client.js
http = require('http');

function sendRequest() {
    http.get('http://localhost:10086', (res) => {
        res.on('data', () => {
            console.log('hello');
        })
    });
    setTimeout(sendRequest, 1000)
}

setTimeout(() => {
    sendRequest();
}, 1000);
```
```javascript
// server.js
var express = require('express');

var app = express();

app.get('/', (req, res)=> {
    res.send('');
    console.log(req);
});

app.listen(10086)
```
```json
// launch.json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Client",
            "program": "${workspaceFolder}/client.js"
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Server",
            "program": "${workspaceFolder}/server.js"
        }
    ]
}
```
2. Add a breakpoint on the `console.log(req);` line of server.js, and start the "Launch Server" debugging profile.
3. Add a breakpoint on the `res.on('data', () => {` line of client.js, and start the "Launch Client" debugging profile.
4. The breakpoint in client.js should be hit now after 1 second.
5. Press F5 to continue. The breakpoint in server.js should be hit now.
7. Press F5 to continue. The breakpoint in client.js should be hit now.
8. Wait for about 5 seconds, and press F5 again.
9. The focus will stick in client.js but never switch to client.js. (under some cases, when the breakpoint is hit in server.js, the focus may be force preempted by client.js without hitting F5). You might need to try several times to get it reproduced.

The expected behavior:
The breakpoint should auto switch between client.js and server.js back and forth in order.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (0.54GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
gitignore|cod|0.5.0
vscode-eslint|dba|1.4.12
gitlens|eam|8.5.4
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.34
python|ms-|2018.7.1
azure-account|ms-|0.4.3
csharp|ms-|1.15.2
vscode-docker|Pet|0.1.0
vscode-icons|rob|7.25.0
code-spell-checker|str|1.6.10
usql-vscode-ext|usq|0.2.14
vscodeintellicode|Vis|1.0.1
azure-iot-edge|vsc|1.2.0-rc2
azure-iot-toolkit|vsc|1.1.1

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/57253

**Comment by LazarusX** [comment]
![vscode debug](https://user-images.githubusercontent.com/716650/44762764-bffa1e80-ab7a-11e8-8ac0-7b4728d5cbdb.gif)

With the 2018-08-28 Insider, when server.js and client.js are both paused on breakpoint, and the focus is in server.js, if I press continue (F5), the focus is not auto switched to client.js.

**Comment by isidorn** [comment]
@LazarusX got it, it is bascially the same issue as #57253 so let's continue the discussion there.
