### ISSUE TITLE
Tweak color names for breadcrumbs

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#55865]
Following up on the discussion here: 
https://github.com/Microsoft/vscode/commit/c588525c1c8b2e44d437aca6d24d888d1075849e#r29968874

**Comment by jrieken** [comment]
Should it be `breadcrumb.pickerBackground` or `breadcrumbPicker.background`?

**Comment by bpasero** [comment]
+1 for `breadcrumbPicker.background`

**Comment by joaomoreno** [comment]
LGTM by code review
