### ISSUE TITLE
Move the Integrated Terminal to a separate project

### ISSUE THREAD

**Issue by hgouveia** [Microsoft/vscode#55861]
The Integrated terminal of Visual Studio Code works really great, and pack with a lot of feature

- Open Multiple Terminal in "tab/dropdown"
- Open Different Terminal
- Split functionality
- Custom terminal from settings (terminal, arguments, font, fontsize), just to name a few
- Fast!

![image](https://user-images.githubusercontent.com/668866/43708941-e217731c-996b-11e8-978c-031623823c98.png)

Request: Move the Integrated Terminal to a separate project, basically remove monaco-editor and all things and just keep the Terminal functionality, and user settings , to be able to use it as standalone app 

i've used Another terminal solutions base on Electron and also using node-pty like Hyper.js and Terminus , but i think  VSCode terminal is better 

Or could be very helpful if some give me some guidence how to do it myself  :)

**Comment by Tyriar** [comment]
This has been suggested before, be sure to give https://github.com/Microsoft/vscode/issues/34442 a 👍 😃
