### ISSUE TITLE
Allow to change left margin

### ISSUE THREAD

**Issue by yaagma** [Microsoft/vscode#55869]
I'd like to remove the left margin when editing source code.
When using the following settings, there is still some space left. THAT is the margin I'd like to remove/reduce.

``` js
"editor.folding": false,
"editor.glyphMargin": false
"editor.lineNumbers": "off",
 ``` 

That space is always added, and I'd like to remove it and let, for example, glyphMargin to be the ONLY margin.

Thanks
Ps: In https://stackoverflow.com/questions/44912058/is-there-a-way-to-make-vscode-line-number-field-smaller-width seems to confirm that the margin I'm talking about can't be removed.

**Comment by alexandrudima** [comment]
Duplicate of #30795
