### ISSUE TITLE
win10打开vscode后频繁死机

### ISSUE THREAD

**Issue by zchrissirhcz** [Microsoft/vscode#55867]
- VSCode Version: 1.25.1
- OS Version: Windows 10

Steps to Reproduce:

1. Boot Windows 10 System, and open Chrome, and open VSCode
2. Wait. Just wait. Maybe go for a meal about 30 minutes, then come back to sit in front of my Computer, found the screen is locked (this is normal), after typing password to log in, only mouse can move, other stuff (the GUIs, the Ctrl+Alt+Del) don't response.

我是来自中国的，英语不是很好，就先用中文说一下情况吧：

我用的是一台台式机电脑，8G内存，Win10操作系统，我打开VSCode经常出现系统假死的情况，也就是突然间只有鼠标能动，其他窗口程序都没有反应，快捷键Ctrl+Alt+Del，或者Ctrl+Shift+Esc，都不起作用。开Chrome和VSCode加起来应该也不至于把内存用光。VSCode打开的工程里，打开的文件都是只有几十行几百行的代码文件。今天我打开VSCode两次，死机两次。怎样重现这个问题，我也觉得不太可能，就是想发上来，看看有没有人有类似的情况，反映一下，或者vscode官方提供点建议。毕竟我的系统连续运行3天，一直开着chrome，xshell，网易云音乐，microsoft word，outlook，QQ等软件，都没有死机，一开VSCode就很容易死机。

**Comment by SummerSun** [comment]
Let me help to translate and summarize this issue:  system just hang there when opening VS Code with even projects just hundreds of lines of code. Not stable repro, just want to track an issue here in case others may encounter the same problem.

**Comment by ramya-rao-a** [comment]
Thanks @SummerSun for the translation.

@zchrissirhcz Please follow the [wiki for Performance Issues](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to log the issue using the issue reporter. That will give us more information to work with. Also, read that wiki completely which can help in figuring out which part of VS Code is actually causing this issue.
