### ISSUE TITLE
Menu on OSX disappears/closes from under mouse or refuses to open

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#55876]
Issue Type: <b>Bug</b>

Attempt to open a new folder in a new window:
* File > New Window
* File > Open Recent
* Observe the menu disappears from under the mouse or the recent list does not show up

![kapture 2018-08-06 at 15 56 14](https://user-images.githubusercontent.com/5047891/43720786-5ab2833c-9991-11e8-8502-c9be29a1f489.gif)

Attempt to open the File menu:
* Quit VS Code
* Launch VS Code
* Attempt to operate the File menu, it will disappear after a couple seconds

![kapture 2018-08-06 at 16 00 32](https://user-images.githubusercontent.com/5047891/43720989-e287ced4-9991-11e8-84e7-fcb5a87c3105.gif)

VS Code version: Code - Insiders 1.26.0-insider (21ddb4843b2f40e3cd82500794dc9a1b9404717d, 2018-08-06T08:51:57.522Z)
OS version: Darwin x64 17.7.0

**Comment by sbatten** [comment]
revert to old menu https://github.com/Microsoft/vscode/pull/55913
