### ISSUE TITLE
Sudo in sh terminal

### ISSUE THREAD

**Issue by ridwanfirdaus96** [Microsoft/vscode#55875]
Issue Type: <b>Bug</b>

Hi, my name is Ridwan. Im from Indonesia. In vscode linux I have problem when I can't sudo etc and got message "sh: sudo: command not found" I hope you fix this bug. Thanks you

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:40:20.190Z)
OS version: Linux x64 4.15.0-29-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|7.67GB (1.92GB free)|
|Process Argv|/app/extra/vscode/code --extensions-dir=/home/ridwanfirdaus96/.var/app/com.visualstudio.code/data/vscode/extensions --reuse-window|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by ijash** [comment]
i found the bug was happened on flatpak in linux mint 19 repository.
for the solution i was installing the official .deb app. 
the bug fixed.
