### ISSUE TITLE
Auto Import with Absolute Path Error

### ISSUE THREAD

**Issue by estrellajm** [Microsoft/vscode#55873]
When using Auto Import I am getting the absolute path suggested in the imports. 

How do I switch back to having Auto Import use Relative Path?

- VSCode Version: 1.25.1
- OS Version: MacOS High Sierra 10.13.6
- Angular CLI 6.1.2
- Node 8.11.2

Steps to Reproduce:

1. Try importing a module in the constructor. You should receive suggestions. Please see the images below:

**Suggested import:**
![image](https://user-images.githubusercontent.com/7454322/43716780-9bbe58fa-9942-11e8-947c-cab544cc3453.png)

**Current Result:**
![image](https://user-images.githubusercontent.com/7454322/43716783-9e599944-9942-11e8-9837-070f776a9e59.png)

**Expected Result:**
![image](https://user-images.githubusercontent.com/7454322/43716785-a0fa5940-9942-11e8-81d3-ba484167ea32.png)

Does this issue occur when all extensions are disabled?: Yes/No **(was not able to run this command)**
![image](https://user-images.githubusercontent.com/7454322/43717001-54c9f76e-9943-11e8-8bd8-6b05d22dcc26.png)

**Development Environment:**
I am developing with Angular 6.1.2. I was able to reproduce this issue on a brand new project, by running the command:

`ng new example_project`

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?
