### ISSUE TITLE
Menu instability on macOS

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#55871]
Issue Type: <b>Bug</b>

- Quite frequently there is no "Open Recent..." submenu after opening a new VS Code window. Trying it again makes it appear.
- selecting an item from the "Open Recent..." submenu sometimes has no effect on first try.
- sometimes the menubar menus are missing too on first try.

VS Code version: Code - Insiders 1.26.0-insider (21ddb4843b2f40e3cd82500794dc9a1b9404717d, 2018-08-06T08:51:57.522Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.38GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_7907210|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by joaomoreno** [comment]
Yup, see it too

1. Open VS Code
2. Quickly click the `File` menu as soon as it opens
3. Move mouse to `Open Recent...`, nothing comes up on that submenu]
4. Move mouse to `Edit` top level menu, nothing comes up

**Comment by weinand** [comment]
@joaomoreno are you seeing this on macOS?

**Comment by joaomoreno** [comment]
Yeah.

**Comment by sbatten** [comment]
revert to old menu https://github.com/Microsoft/vscode/pull/55913
