### ISSUE TITLE
Poor terminal performance on Debian w/ GTX 1060

### ISSUE THREAD

**Issue by moof2k** [Microsoft/vscode#55889]
Issue Type: <b>Bug</b>

VSCode terminal runs very poorly unless I run vscode w/ --ignore-gpu-blacklist

lspci:
05:00.0 VGA compatible controller: NVIDIA Corporation GP106 [GeForce GTX 1060 3GB] (rev a1)

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:40:20.190Z)
OS version: Linux x64 4.9.0-4-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz (32 x 1351)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|94.35GB (85.25GB free)|
|Process Argv|/usr/share/code/code --ignore-gpu-blacklist|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.1.0
flatbuffers|gab|0.1.0
cpptools|ms-|0.17.7
clang-format|xav|1.6.2

</details>

**Comment by Tyriar** [comment]
This is a known issue caused by Chromium's GPU blacklist which disables GPU acceleration on certain OS/hardware combinations. 1.26 is having Electron/Chromium updated which may improve the situation.

**Comment by moof2k** [comment]
@Tyriar Even with --ignore-gpu-blacklist the 1.25.1 terminal appears to be a significant performance regression compared to the previous version I was running, 1.23.1. I've gone back to running the previous version.

**Comment by Tyriar** [comment]
@moof2k I recommend checking in 1.26 which will be released within the week as it's a pretty significant jump from Ch58 to Ch61.

**Comment by jleclanche** [comment]
@Tyriar Here, when jumping from 1.25 to 1.26, the terminal performance has become absolutely atrocious on Arch Linux. `VGA compatible controller: NVIDIA Corporation GK110B [GeForce GTX 780 Ti] (rev a1)` with nouveau driver.

**Comment by GLundh** [comment]
Same here. Went from 1.25 to 1.26 (Debian, GeForce GTX 1050) and the Terminal is now so slow it is practically unusable.

**Comment by GLundh** [comment]
When switching to renderType: "dom", the performance increases, but still much worse than canvas on 1.25.

**Comment by Tyriar** [comment]
This was caused by https://github.com/Microsoft/vscode/issues/56628, it's fixed in latest Insiders and will come to 1.27. Sorry about the hassle
