### ISSUE TITLE
Tree#reveal shouldn't cut off first entry

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#55887]
Steps to Reproduce:

1. open a large breadcrumb picker
2. notice how an item is selected but the top one is cut off

I feel for a picker to look nice, the top element should show fully if possible.

![image](https://user-images.githubusercontent.com/900690/43727417-33f67a80-99a2-11e8-81bd-a4c9f60b4771.png)

**Comment by joaomoreno** [comment]
@jrieken There's something you can do: get the view's max size to fit an odd number of elements, instead of an even one. Since you use `reveal` with 0.5, that would fix it.

**Comment by jrieken** [comment]
Yeah, that trick actually works

**Comment by joaomoreno** [comment]
Closing it for now.
