### ISSUE TITLE
Switching terminals without changing user settings

### ISSUE THREAD

**Issue by outish6** [Microsoft/vscode#55880]
This is my first time using vs code.
as you know vs code has an integrated terminal, I am trying to switch between Git Bash, PowerShell, and CMD, all without changing the user settings or messing with the program's files. 
I was able to do so by mistake, I remember that I was able to get drop down menu wanting me to choose between of the three terminals mentioned above but I don't remember how I was able to get it.
Please Help!

**Comment by outish6** [comment]
So my problem was solved by the Reddit community [Here](https://www.reddit.com/r/vscode/comments/951rjw/switching_terminals_without_changing_user_settings/). So to switch terminals you need to open the command palette (or use the shortcut Ctrl + Shift + P), and choose >Terminal: Select Default Shell, then choose the one you want, Press the + button in the terminal and you will get the terminal you just choose hope that helped everyone.

**Comment by Tyriar** [comment]
There's also this extension which makes it a little more convenient if you do this a lot https://marketplace.visualstudio.com/items?itemName=Tyriar.shell-launcher
