### ISSUE TITLE
a new idea

### ISSUE THREAD

**Issue by wayne17** [Microsoft/vscode#55884]
#### suggest to add a new edit mode that can typeset vertical  chinese, like this:
[https://img-blog.csdn.net/20180806233340131?watermark/2/text/aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dheW5lMTc=/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70](url)

**Comment by ramya-rao-a** [comment]
@wayne17 We are not able to open the link you have shared. Can you share the link again and provide more details?
