### ISSUE TITLE
Consider to rename IURIDisplayService 

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#55886]
I find the `IURIDisplayService` hard to understand. I think we generally talk about resource labels, so why not go with `IResourceLabelService`?

**Comment by isidorn** [comment]
Thanks for feedback, however we use URI eveywhere in our API in favor of resource.
So why not `IUriLabelService`

fyi @jrieken

**Comment by bpasero** [comment]
Works for me too.
