### ISSUE TITLE
VSCode Intellisense very slow because of a specific npm package

### ISSUE THREAD

**Issue by amnrzv** [Microsoft/vscode#55890]
Issue Type: <b>Performance Issue</b>

Whenever I try to use "wink-pos-tagger", the vscode intellisense goes very very slow. Not sure what exactly is causing it. I also see a spike in CPU usage as well.

VS Code version: Code - Insiders 1.26.0-insider (c2ddece6536330f4b4ceef33de5eea6e406fb30a, 2018-08-06T10:34:04.876Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-6600K APU with Radeon(tm) HD Graphics    (4 x 3893)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|14.93GB (7.74GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    3	   115	  2972	code-insiders main
    3	    66	   224	   gpu-process
    0	    69	  4900	   window (Issue Reporter)
    0	    70	 10844	   shared-process
    3	   185	 14236	   window (● index.js - language-analysis-backend - Visual Studio Code - Insiders)
    0	    14	   628	     watcherService 
    0	    10	  4704	       console-window-host (Windows internal process)
    0	    57	 13200	     extensionHost
    0	    35	  2152	       searchService
   25	   259	 14172	       electron_node electronForkStart.js tsserver.js 
    0	    59	  7080	         electron_node typingsInstaller.js tsserver.js typesMap.js 
    0	     6	 13460	     winpty-process
    0	     3	  1776	       C:\Windows\System32\cmd.exe
    0	    10	 14044	       console-window-host (Windows internal process)
    0	    35	 14268	     searchService
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● index.js - language-analysis-backend - Visual Studio Code - Insiders)
|    Folder (language-analysis-backend): 3 files
|      File types: json(2) js(1)
|      Conf files: package.json(1);
```

</details>
Extensions: none

**Comment by ramya-rao-a** [comment]
Do you see the same when using the stable version of 1.25.1? Please go through our [wiki on Perfromance Issues](https://github.com/Microsoft/vscode/wiki/Performance-Issues) and share any other information if possible.

**Comment by amnrzv** [comment]
![without-package](https://user-images.githubusercontent.com/3538909/43765817-c1025436-9a28-11e8-9797-169dd867a6f7.PNG)
![with-package](https://user-images.githubusercontent.com/3538909/43765822-c3c121ca-9a28-11e8-97e6-ee85ed13e4d4.PNG)

Please find process explorer screenshots for without the package and with the package CPU consumption.

Performance wise, in the second case intellisense takes around 30 secs to 1 min, whereas in the first one it's instantaneous.

**Comment by amnrzv** [comment]
I can confirm that the same is happening in the stable release v1.25.1 as well.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?
