### ISSUE TITLE
Issue Opening Folder Using vscode.openFolder

### ISSUE THREAD

**Issue by allileong** [Microsoft/vscode#55891]
- VSCode Version: 1.26.0-Insider (This issue is happening in Insiders only)
- OS Version: macOS 10.13.6

While running a custom extension, I execute: 
```javascript
vscode.commands.executeCommand(
     'vscode.openFolder',
     vscode.Uri.parse(
        <some-local-path>
     )
);
```
I get a 'Path does not exist error', even though the path exists. 
![screen shot 2018-08-06 at 9 42 14 am](https://user-images.githubusercontent.com/1639375/43730923-342f9eba-996a-11e8-96a5-54b01b450061.png)

Steps to Reproduce:

1. Run a custom extension
2. Execute the code snippet above

**Comment by ramya-rao-a** [comment]
cc @bpasero

**Comment by ramya-rao-a** [comment]
@allileong It works if you prefix the local path with `file:/` for me. For example: `file://Users/me/hello`. Can you try that?

@jrieken In the stable bits of 1.25.1, this would work even without the prefix of the scheme. I am not sure if the api for `Uri` changed or the one for `vscode.openFolder` command. Regardless, this would be a breaking changes for extension authors.

**Comment by bpasero** [comment]
@aeschli maybe due to the changes for supporting URIs on the main side?

**Comment by allileong** [comment]
Hi @ramya-rao-a , prefixing the local path with `file:/` gets me past the issue.

**Comment by aeschli** [comment]
@allileong Please use `vscode.Uri.file`. Thats the proper way to create a URI from a file path that works on all platforms.

**Comment by kieferrm** [comment]
@aeschli what you're saying is that our implementation of `vscode.URI.parse` behaves incorrectly.  It's documented as:
```js
		/**
		 * Create an URI from a string. Will throw if the given value is not
		 * valid.
		 *
		 * @param value The string value of an Uri.
		 * @return A new Uri instance.
		 */
		static parse(value: string): Uri;
```
but for local file path inputs it creates URIs without a mandatory scheme component, i.e. invalid URIs.

**Comment by jrieken** [comment]
> you're saying is that our implementation of vscode.URI.parse behaves incorrectly

I don't think he is saying that. The issue is this: `Uri.parse('c:\foo\bar')` is different from `Uri.file('c:\foo\bar')`. The sample code is `vscode.Uri.parse(<some-local-path>)` which is incorrect, when you have path you must use `Uri.file`

**Comment by jrieken** [comment]
> but for local file path inputs it creates URIs without a mandatory scheme component, i.e. invalid URIs.

We don't throw when uri components are missing, we only do little validation e.g. checking authority and path constraints [etc](https://github.com/Microsoft/vscode/blob/35f7ed7b7bdac5ea92d419ed3a32d8f031d20dad/src/vs/base/common/uri.ts#L14)

**Comment by jrieken** [comment]
I have experimented with enforcing that URIs must have a scheme... Un-commenting [this code](https://github.com/Microsoft/vscode/blob/e9ed5e19f69b4d2807f0d5850a86cec9acc1eb2d/src/vs/base/common/uri.ts#L16-L19) yields in many, many test failures and while the product starts we will likely see failure here and there. So, iff we want to support scheme-enforcement a coordinated effort is needed.

**Comment by aeschli** [comment]
We now throw an exception when invoking `vscode.openFolder` with an invalid (schema-less) URI.

**Comment by aeschli** [comment]
I change the fix to treat the missing schema gracefully. The URI without scheme is converted to a `file://` URI. That change only applies to `vscode.openFolder`.

Extensions are advised to not rely on the workaround but change `vscode.Uri.parse` to `vscode.Uri.file`. Note that `vscode.Uri.parse(<filename>)` doesn't (and hasn't) work on Windows as drive letters (`c:/`) are treated as URI schemes and will not be part anymore of `uri.fsPath`.

**Comment by chrmarti** [comment]
@aeschli The warning message doesn't expand `${uri}` because it is not in a template string. Verified otherwise.

**Comment by aeschli** [comment]
@chrmarti Good catch, I added a fix. I also improved the fix to use URI.file(uri.toString()) as alternative URL (then it also works on windows).

**Comment by aeschli** [comment]
@chrmarti If you can verify again that would be great

**Comment by sandy081** [comment]
Thanks @aeschli for the fix
