### ISSUE TITLE
Debugger doesnt stop when running extension from source and a new folder is opened

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#55899]
- VSCode Version: 1.26 insiders
- OS Version: Mac 

Steps to Reproduce:

1. Have an extension that opens a folder on command
```
vscode.commands.registerCommand('extension.sayHello', () => {
        vscode.commands.executeCommand('vscode.openFolder', vscode.Uri.parse('file://Users/some-local-path'));
    })
```
2. Debug the extension, run the above command
3. Observe the folder we want to open is indeed opened. Close the VS Code window
4. Back in the folder for the extension source itself, the debug session doesnt stop. The debug tool bar is still there. Clicking on the stop button does nothing.

In stable bits of 1.25.1, the debug session closes automatically.

**Comment by roblourens** [comment]
I can't repro this

**Comment by roblourens** [comment]
I do see the problem on Ramya's mac. After the new window opens, the debugger attaches correctly, and the DA sends `initialized`, but vscode never sends the requests that should happen at this point.

**Comment by ramya-rao-a** [comment]
[vscode-node-debug2.txt](https://github.com/Microsoft/vscode/files/2264162/vscode-node-debug2.txt)

**Comment by weinand** [comment]
@roblourens please see my comment https://github.com/Microsoft/vscode/issues/55911#issuecomment-410854957

**Comment by roblourens** [comment]
Is terminate involved here?

**Comment by weinand** [comment]
Yes, Ramyas initial comment says: "Clicking on the stop button does nothing"

**Comment by roblourens** [comment]
It's broken before that point

**Comment by weinand** [comment]
Most likely this is the same as https://github.com/Microsoft/vscode/issues/55025

**Comment by roblourens** [comment]
Oh ok, that sounds right. I guess I'm not sure why it works most of the time.
