### ISSUE TITLE
feature request: add additional launch.json variable to refer to the compiled version of a file

### ISSUE THREAD

**Issue by cdaringe** [Microsoft/vscode#55896]
# problem

to begin a debugging session where a `typescript` file is not my entrypoint, but is instead an argument to my entrypoint, i must find a way to get the `/path/to/the/compiled/JS` file into my launch config.  this could be reduced in complexity if such a pseudo-variable were simply exposed.

it may sound a little meta--see the example below

# desired state

- add a new [launch variable](https://code.visualstudio.com/docs/editor/variables-reference) to point to the _built_ version of the file

# example

i like to use `ava` test runner.  to debug ava against a file in javascript, one uses a configuration as such:

```json5
    {
      ...
      "program": "${workspaceRoot}/node_modules/ava/profile.js",
      "args": [
        "${file}"
      ],
    }
```

this works fine when `${file}` is JS.  in my case, it's TS.  thus, i need `${file}` to point to my built TS file.

# proposal

- add a var `${file:out}`/`${file:built}`/`${file:compiled}`
    - if an output file cannot be found, the current file is perhaps at least tried

```json5
    {
      ...
      "program": "${workspaceRoot}/node_modules/ava/profile.js",
      "args": [
        "${file:out}"
      ],
    }
```

now, the ava entrypoint will find my built src file, and sourcemaps will all work and i'll have a more natural debug workflow.

**Comment by weinand** [comment]
VS Code does not no anything about "building" or "build results". So we cannot introduce a new variable for that. 
I suggest that you create an extension that just implements "commands" with the specific behaviour you are looking for. You can then use these commands from within a launch configuration via the `${command:my_cool_command}`syntax.
