### ISSUE TITLE
Code blocks in hovers / tooltips wrap 

### ISSUE THREAD

**Issue by s-arash** [Microsoft/vscode#55902]
- VSCode Version: 1.25.1
- OS Version: Windows 10 version 1803

Code inside hovers (tooltips / intellisense) provided by language servers wraps, while normal text does not.
![screenshot 19](https://user-images.githubusercontent.com/4473311/43735530-d079582e-9988-11e8-9a5f-049afd7d5a0b.png)

Here, the hover content is something like this:
┌─────────────────────────────────┬────────────────┬───────────────┬
\`\`\`
┌─────────────────────────────────┬────────────────┬───────────────┬
\`\`\`
One would expect the text inside the code block not to wrap, and the text outside it to wrap; but it's the opposite! It completely destroys the formatting of some hovers:

![screenshot 21](https://user-images.githubusercontent.com/4473311/43735913-eb3e7530-9989-11e8-8ee5-b5826f99bfb9.png)

**Comment by ramya-rao-a** [comment]
@s-arash The screenshots above don't show the actual text in the hover widget. Please share some screenshots that do show the text

**Comment by s-arash** [comment]
@ramya-rao-a Do you mean they don't show alphabetic characters? For my use case, I need it not to wrap on those long, table-building strings. Like this one:
```
┌─────────────────────────────────┬────────────────┬───────────────┬────────────────────────────────┬
```
The second screenshot shows a mixture of text and alphabetic characters. If the hover content in the second screenshot were not inside a code block, it wouldn't wrap, but it would still look jumbled because the font wouldn't be mono spaced.

**Comment by ramya-rao-a** [comment]
If it doesnt wrap then am guessing you expect the widget to have a scrollbar?

**Comment by joaomoreno** [comment]
You should not attempt to render a table in this widget, it's just not meant for it. Try to distill the message you want the user to see and return a simple Markdown string explaining it. If you still want to render a table, you should use another UI abstraction for it, like a webview.
