### ISSUE TITLE
JavaScript import path Intellisense suggestions still pretty bad

### ISSUE THREAD

**Issue by Floriferous** [Microsoft/vscode#55909]
I'm following up on https://github.com/Microsoft/vscode/issues/17796, as I believe that intellisense is still giving very bad suggestions most of the time:

1. `core` is an autocompleted folder in my workspace, yet when I want to autocomplete the path, it suggest completely random things:
<img width="625" alt="screen shot 2018-08-06 at 22 10 09" src="https://user-images.githubusercontent.com/10428082/43738626-990d8512-99c5-11e8-8cf8-77be032df949.png">

2. When I edit some SCSS files I get hundreds of duplicated suggestions, and after probably a couple hundred suggestions for SASS variables, I finally see what I actually want:
<img width="453" alt="screen shot 2018-08-06 at 22 12 46" src="https://user-images.githubusercontent.com/10428082/43738737-f88e83ce-99c5-11e8-8d03-eb515ed5b15d.png">
<img width="449" alt="screen shot 2018-08-06 at 22 12 59" src="https://user-images.githubusercontent.com/10428082/43738738-f8a71e5c-99c5-11e8-817e-cc775d7aa259.png">

This is caused by the `SCSS intelliSense` extension, which finds the variables across the repo, and suggests them all. It'd be great if there was a way to tell VSCode what I want to see first if it can't figure it out on its own.

3. Here I get some random react autocompletions on a pure javascript class:
<img width="385" alt="screen shot 2018-08-06 at 22 19 34" src="https://user-images.githubusercontent.com/10428082/43739011-ddc78364-99c6-11e8-9213-f5ea977bed65.png">

**Comment by mjbvz** [comment]
@Floriferous  One issue per problem please. Let's use this one to track 1. 

What does your project jsconfig / tsconfig look like?

**Comment by Floriferous** [comment]
Yeah, I guess this might be closer to a feature request in that case. More control over suggestions by defining some manual priority order would be interesting.

Okay, for 1., here's the jsconfig:

```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "es6",
    "baseUrl": ".",
    "paths": {
      "core/*": ["../../core/*"]
    }
  },
  "exclude": ["node_modules"]
}
```

**Comment by Floriferous** [comment]
On latest version, I still see the exact same suggestions, not fixed for me.

Here's another issue I opened concerning another topic, where I explain the project's structure: https://github.com/Microsoft/vscode/issues/55905

**Comment by mjbvz** [comment]
I believe this was fixed by https://github.com/Microsoft/TypeScript/issues/24278 a few iterations back

I can't repo it anymore in test workspace. If you still see this issue on more recent versions of Ts/VS Code, please share a small example project and we can investigate
