### ISSUE TITLE
Find/Replace in Selection Clears Selection

### ISSUE THREAD

**Issue by jeffsaremi** [Microsoft/vscode#55901]
Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:43:53.668Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

Steps to Reproduce:

1. Select one ore more lines within which you would like to do a find/replace or just find.
2. Press CTRL+F or CTRL+H
3. Within the find/replace window start typing in either fields.
The selection goes away and if you're not careful you'd be replacing in the entire file.

Does this issue occur when all extensions are disabled?: Yes

**Comment by ramya-rao-a** [comment]
Add `"editor.find.autoFindInSelection": true` to your settings for find/replace to work on just the selection.
