### ISSUE TITLE
jsconfig not detected in multi-root workspace

### ISSUE THREAD

**Issue by Floriferous** [Microsoft/vscode#55905]
I have a project with mutliple roots configured in a workspace:

* _root_ -> One of the multi-roots
  * `jsconfig.json`
  * `shared/` -> One of the multi-roots
  * `subfolder/`
    * `app1/` -> One of the multi-roots
    * `app2/` -> One of the multi-roots

* `jsconfig.json` at the root of the workspace:
```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "es6",
    "baseUrl": ".",
    "paths": {
      "shared/*": ["./shared/*"]
    }
  },
  "exclude": [
    "node_modules",
    "subfolder/*/node_modules"
  ]
}
```
* When I go to one of the roots in my workspace and do `Javascript: Go to Project Configuration`, it says "File is not part of a Javascript project Click here to learn more."
  * When I click on the Call-to-Action "Configure jsconfig.json", it creates a new `jsconfig.json` in the root that I'm currently in

I expect the `jsconfig.json` to be detected across the entire workspace as it seems to be the normal behavior according to the docs: https://code.visualstudio.com/docs/languages/jsconfig

The autocompletion from the `paths` is also not working.

**Comment by pferreir** [comment]
Same here.

**Comment by LissetteIbnz** [comment]
This would be very useful...

**Comment by mjbvz** [comment]
@Floriferous Sorry, this fell off my radar. 

I can't repo this however. Here's the example workspace I used: https://github.com/mjbvz/vscode-55905

Can you please share an example git repo to make sure I have the correct workspace structure

**Comment by Floriferous** [comment]
I changed your repro a little bit to be more precise. But I'm unable to reproduce it as well, could you give some pointers as to how VSCode determines if a project is part of a javascript project?  I don't know what could interfere.

I should also note that when I try to run "Javascript: Go to Project Configuration", it takes roughly 3-5 seconds before it first signals me about the issue, maybe it's trying to search in the wrong places?
