### ISSUE TITLE
fix the exntension host

### ISSUE THREAD

**Issue by lefx** [Microsoft/vscode#55908]
Issue Type: <b>Bug</b>

all the time extension host stopped working ... unistalled all extensions and nothing ,,, fix the damn thing or disable it completely and embed the extensions into the main code 

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (2.72GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by ramya-rao-a** [comment]
@lefx Did this start happening recently only in the current version of VS Code that you are using? Can you try the latest [Insiders](https://code.visualstudio.com/insiders) and see if you get the same issue there?

**Comment by lefx** [comment]
@ramya-rao-a  thank you … its working ok for the time being with me adding some extensions … hope its ok because although I love vs code I will have to change to another editor if the problem arises again because it was driving me crazy

thank you again

**Comment by ramya-rao-a** [comment]
Please do log an issue if you see this again.
