### ISSUE TITLE
Always getting "Couldn't start client Language Server" in Insiders under F5

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode#55907]
Issue Type: <b>Bug</b>

See https://github.com/Microsoft/vscode-docker/issues/357.
This is recent behavior and doesn't seem to be related to any changes made on our side. Seems to only happen in Insiders and only when running the extension under F5.  And seems to happen 100%.

REPRO:
1) git clone https://github.com/Microsoft/vscode-docker.git
2) npm install
3) open folder in vscode
4) F5
5) In extension host, click on Docker icon:
![image](https://user-images.githubusercontent.com/6913354/43738116-6b763d62-9978-11e8-8c4c-807a41b1cf9a.png)
!) Error: Couldn't start client Dockerfile Language Server

VS Code version: Code - Insiders 1.26.0-insider (4fa62b246c4305b4ca00507551f77c58135ce928, 2018-08-03T12:32:37.823Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E31230 @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.96GB (3.34GB free)|
|Process Argv|C:\Users\stephwe\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe c:\Repos\vscode-docker|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.19.0
vscode-eslint|dba|1.4.12
tslint|eg2|1.0.34
rest-client|hum|0.19.0
csharpfixformat|Leo|0.0.73
vscode-mocha-sidebar|mat|0.20.17
vscode-antlr4|mik|2.0.4
vscode-language-pack-de|MS-|1.26.1
azure-account|ms-|0.4.3
vscode-docker|Pet|0.1.0

</details>

**Comment by ramya-rao-a** [comment]
@dbaeumer @aeschli I could trace this down to electron.fork failing at https://github.com/Microsoft/vscode-languageserver-node/blob/7700442d2580957ce5c8b40de7f2f50f837ef755/client/src/main.ts#L353 with code 9.

**Comment by ramya-rao-a** [comment]
cc @bpasero and @Tyriar as this might be related to electron

**Comment by ramya-rao-a** [comment]
@roblourens looked into this further and we found that changing the `debug` to `inspect` at https://github.com/Microsoft/vscode-docker/blob/069ed857323f4ceadfcee33130815c9d3fd56584/dockerExtension.ts#L213 fixes the issue.

This is due to the electron update we did for VS Code 1.26

@roblourens @weinand We can either update the documentation and release notes or maintain backward compatibility. Leaving this up to you.

**Comment by weinand** [comment]
In the release notes we need to add in the Electron update section that the new node version no longer supports the legacy debug protocol and the „—debug“ argument.

**Comment by joaomoreno** [comment]
As discussed, @Tyriar let's release note this, due to the Electron update.

**Comment by StephenWeatherford** [comment]
Great, thanks!

**Comment by Tyriar** [comment]
Added, I also called out the `natives` module https://github.com/Microsoft/vscode-docs/commit/47f7f375b88a7a2cf3d42f59aeb584bdc34d9e62
