### ISSUE TITLE
(Mac / Linux) `node --inspect-brk` with auto attach doesn't work

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#55918]
I'm on c2ddece6536330f4b4ceef33de5eea6e406fb30a with all extension disabled.
This does not happen on Windows.

- Create `index.js` with the following content
  ```js
  console.log('foo')
  console.log('bar')
  ```
- Put a breakpoint on first line
- `Debug: Toggle Auto Attach` to turn auto attach on
- Run `node --inspect-brk index.js`
- Editor do not enter debug mode and no breakpoint gets hit

Node Version: v8.9.2
macOS: High Sierra 10.13.6

**Comment by octref** [comment]
I was using Code 1.25 on Linux. Turned out this happens on both Mac and Linux.

**Comment by roblourens** [comment]
I think this is from the terminal process changes. Auto attach looks for `--type=terminal` which doesn’t exist anymore so it’s completely broken on linux and mac. cc @Tyriar

**Comment by Tyriar** [comment]
@roblourens that makes sense, processes are now spawned directly under the renderer process.

<img width="549" alt="screen shot 2018-08-06 at 4 03 44 pm" src="https://user-images.githubusercontent.com/2193314/43745188-5a96427a-9992-11e8-9479-52c6265bfedf.png">

@weinand let me know your thoughts, I don't think we should backtrack on the process layout. Perhaps looking for terminal processes by searching for the configured shell (terminal.integrated.shell.*) as a child of the renderer process?

**Comment by roblourens** [comment]
Or just start looking under `window.terminals`, you can get the processId of a `Terminal`.

**Comment by weinand** [comment]
When has this changed? In the test pass last week we found that the process topology had changed for Windows and we fixed that. But macOS and was working fine.

**Comment by Tyriar** [comment]
@weinand merged 25 days ago https://github.com/Microsoft/vscode/pull/54090

@roblourens oh yeah, that's stable now :smile:

**Comment by weinand** [comment]
Verification:

- turn on auto-attach via the "Toggle Auto Attach" action
- use a long-running node.js program "hello.js":
  ```
  var i = 0;
  setInterval(() => {
  	console.log('hello world ' + i++);
  }, 1000);
```
- set a breakpoint in line 3
- open integrated terminal
- enter `node --inspect hello.js`

Debugger should hit breakpoint
