### ISSUE TITLE
Add functionality to make VS Code a browser IDE

### ISSUE THREAD

**Issue by jgbradley1** [Microsoft/vscode#55917]
Others have started modifying VS Code to run within a browser (think running remote workspaces in a container). StackBlitz and Theia are great examples. Can those contributions be brought  into the VS Code project to make VS a proper cloud IDE?

**Comment by paulyoung** [comment]
I found this issue after seeing the recent efforts by @Compulves:

https://twitter.com/CompuIves/status/1031930891122049024

https://twitter.com/CompuIves/status/1031930894909562883

**Comment by wpitallo** [comment]
I am really surprised that Microsoft has not jumped onto this. I have been using visual studio for years but recently discovered https://aws.amazon.com/cloud9/?origin=c9io and so far I am loving it and dumping visual studio code in favor of cloud 9, Its a pity would love to have a browser based version of visual studio code at least running in the browser as an azure service.

**Comment by svenefftinge** [comment]
There is:
- [Theia](https://github.com/theia-ide/theia) is a VS Code-based open-source IDE
- [Gitpod.io](https://gitpod.io) is a hosted version of Theia
- [code-server](https://github.com/codercom/code-server) is a patched version of VS Code

All three provide the great VS Code developer experience in a browser. 
(disclaimer: I'm affiliated with theia and gitpod)

**Comment by wpitallo** [comment]
Awesome thanks going to check them out now :)

**Comment by paulyoung** [comment]
CodeSandbox runs VSCode in the browser and supports extensions: https://hackernoon.com/announcing-codesandbox-v3-4febbaba1963
