### ISSUE TITLE
Debuggin extension doesnt launch window, closing errors with Error processing "terminate": Error: kill ESRCH

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#55911]
- VSCode Version: Insiders 1.26 dated 6th August, 2018
- OS Version: Windows 10

Steps to Reproduce:

1. Have an extension that opens a folder on command
```
vscode.commands.registerCommand('extension.sayHello', () => {
        vscode.commands.executeCommand('vscode.openFolder', vscode.Uri.parse('C:/some-local-path'));
    })
```
2. Debug the extension, run the above command.
3. Close the debugging session, start again

At this point, a new window for extension host is not launched. Clicking the stop button doesnt stop the process either and throws the below error in the debug console

![image](https://user-images.githubusercontent.com/16890566/43739897-75b9723e-997e-11e8-9a52-67d400e684d3.png)

**Comment by roblourens** [comment]
Is vscode supposed to be sending `terminate` here? Should the DA be handling the case differently when `terminate` is called on windows?

**Comment by weinand** [comment]
On Windows or for extension host debugging the DA should return false for the supportTerminateRequest.

**Comment by roblourens** [comment]
Ok, I don't do that.

On windows, why is the DA not normally getting terminate requests? If I debug a normal node app and press stop, the DA doesn't send `terminate` like on Mac. If it did, we would see this breaking all the time.

**Comment by roblourens** [comment]
Apparently I didn't read your issue carefully, apologies. This is probably a candidate right?

**Comment by roblourens** [comment]
That test item should have had a tester assigned for windows...

**Comment by weinand** [comment]
Yes.

**Comment by roblourens** [comment]
I've opened a separate issue for the fact that EH debugging is broken.

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode-node-debug2/commit/82b08304dd5e36343468efd814361faba6664c62

**Comment by roblourens** [comment]
To answer my question from above, the reason I didn't get `terminate` on windows is because Live Share causes that capability to be lost. Like https://github.com/Microsoft/vscode-cascade/issues/69 I think.

This means that this change just causes vscode to officially act the way I've been using it for the past couple weeks.

**Comment by kieferrm** [comment]
Verified using @roblourens' instructions:
> Just do this - debug a node app on windows with `"trace": true`. Click the stop button. Open the log and verify that `From client: terminate(` doesn’t show up
