### ISSUE TITLE
Keybinding issue for Close All Editors command on Windows

### ISSUE THREAD

**Issue by skolmer** [Microsoft/vscode#55912]
- VSCode Version: 1.26.0-insider
- OS Version: Windows 10 Enterprise 1803

Steps to Reproduce:

1. Use Ctrl+W to close all open editor windows, only the active window is closed
2. Use Ctrl+K to close all open editor windows, nothing happens

Does this issue occur when all extensions are disabled?: Yes

I cannot use the default vscode keyboard shortcuts to close all open editor windows. Both Ctrl+K and Ctrl+W are not working to close all editor windows. Ctrl+W is closing only the current active editor window.
I discovered that Ctrl+W is assigned to multiple commands `workbench.action.closeActiveEditor` and `workbench.action.closeAllEditors`. Overriding the default keybinding in keybindings.json for `workbench.action.closeAllEditors` to only Ctrl+K fixes this issue.

**Comment by ramya-rao-a** [comment]
Can you share the changes you made to the keybindings?

**Comment by skolmer** [comment]
I can confirm the exact same behavior for vscode 1.25.1 (clean install without extensions).
I added this to my keybindings.json

```json
[
  {
    "key": "Ctrl+K",
    "command": "workbench.action.closeAllEditors",
    "when": ""
  }
]
```

**Comment by ramya-rao-a** [comment]
The default keybinding to close all editor windows is `Ctrl+K Ctrl+W`. This works as expected. Have you tried this?

**Comment by skolmer** [comment]
Maybe some misunderstanding on my side? I tried Ctrl+K+W and it is working. My Impression of the "Ctrl+K Ctrl+W" was that I could either use Ctrl+K or Ctrl+W to close all windows. Thanks for clarification! Could this be made more clear in the UI?

**Comment by ramya-rao-a** [comment]
I dont know the history behind the decision to show it as `Ctrl+K Ctrl+W` instead of `Ctrl+K,W`. @bpasero, @alexandrudima can shed more light there.

Visual Studio for instance uses the latter method

![image](https://user-images.githubusercontent.com/16890566/43748220-3e1228ce-99a3-11e8-83c4-46c227c2390f.png)

**Comment by skolmer** [comment]
yeah, that might be the reason behind my confusion, I'm a long time visual studio user. 
anyways, thanks for your help!

**Comment by ramya-rao-a** [comment]
Actually, if you look at the keybindings for Team Explorer and SQL Server Object Explorer in Visual Studio, the use the same pattern. We dont show the comma in between.

![image](https://user-images.githubusercontent.com/16890566/43749413-de687f30-99a8-11e8-9e8e-482918daff07.png)

**Comment by bpasero** [comment]
> I dont know the history behind the decision to show it as Ctrl+K Ctrl+W instead of Ctrl+K,W. @bpasero, @alexandrudima can shed more light there.

@ramya-rao-a as far as I know, we support both `Ctrl+K, W` and `Ctrl+K, Ctrl+W` as 2 individual keybindings, so we should display the keybinding always the way you have to press it.

**Comment by alexandrudima** [comment]
I'm not sure what we could have done better here. 

The keybinding to close all editors is a chord: `ctrl+k ctrl+w`. This is different than `ctrl+k w`. `ctrl+k ctrl+w` means <kbd>Control</kbd> must still be pressed when <kbd>W</kbd> is pressed.

I don't think there is anything actionable here.
