### ISSUE TITLE
Git: reverting changes for deleted file shows unclear error

### ISSUE THREAD

**Issue by JacksonKearl** [Microsoft/vscode#55915]
Delete a file. Attempt to undo the deletion. See error message:
![image](https://user-images.githubusercontent.com/8586769/43743168-9fef64e0-9989-11e8-9f93-e844440291d6.png)

This could stand to be more clear. It makes sense on the technical side, but some git novices might be confused. I personally had to double check I was reverting the right change.

**Comment by William-Python-King** [comment]
I think changing the message to `Are you sure you want to restore the deleted file {0}` is ok when discarding the changes in a deleted file.
