### ISSUE TITLE
Python debuggers - no breakpoints in "classic", same dir only in experimental

### ISSUE THREAD

**Issue by thelazydogsback** [Microsoft/vscode#55925]
I'm in-place converting a Python project from VS2017 to VSCode which contains a main.py that depends on two modules I define in directories below the main entry file.
Execution is as expected  - problems with breakpoints during debugging.

For the "classic" (non-experimental) debugger ("Python: Current File"):
- Breakpoints don't seem to work at all, and there are no warnings. 

For the "Python Experimental: Current File" (Integrated or External terminal) config:
- I get the following warnings for all breakpoints set in the sub-modules:
  `pydev debugger: warning: trying to add breakpoint to file that does not exist: <...path...>`
  However, all the noted files do exist at the specified locations
- Breakpoints work for the main.py and other files in the same directory, but (as expected from the warnings) the module breakpoints are not hit.
- I am also not able to step into the files in other directories -- Step Into always acts like Step Over

================
Python interpreter: Shared Anaconda 5.1.0
Python Extension: 2018.7.1

Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:43:53.668Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

**Comment by thelazydogsback** [comment]
The issue turned out to be a old version of the code that was still installed in site-packages.

The error message should probably be fixed if possible, as "file does not exist" is incorrect.
This is a common problem in general -- if it could be detected/linted either statically or during debugging that would be great.

**Comment by weinand** [comment]
Please file this issue against the Python extension.
