### ISSUE TITLE
Indendation for Python is incorrect

### ISSUE THREAD

**Issue by lravindr** [Microsoft/vscode#5592]
- VSCode Version: Version 1.0.0 (1.0.0)
- OS Version: Mac Yosemite

Steps to Reproduce:
1. Wrote a Python script with multiple static methods. When I try to run python, it couldn't detect all of the methods. Attached are the screenshots of Emacs and VSCode editors of the same script. VSCode has the incorrect indentations.
![screen shot 2016-04-21 at 11 36 35 am](https://cloud.githubusercontent.com/assets/4595924/14699505/f53e30b0-07b5-11e6-95e0-91f8c8c01ca0.png)
![screen shot 2016-04-21 at 11 36 14 am](https://cloud.githubusercontent.com/assets/4595924/14699507/fae15fc4-07b5-11e6-8e36-140076f38094.png)

**Comment by aeschli** [comment]
@lravindr Can you paste your code here? Or make a screenshot with 'render whitespaces' turned on? What are the tab/spaces settings (you can see this in the status bar)

**Comment by aeschli** [comment]
@lravindr Can you help?

**Comment by lravindr** [comment]
Sorry, will try to put a smaller repro code in the afternoon.

Sent from Windows phone

-----Original Message-----

**Comment by lravindr** [comment]
Unable to repro this behavior. The Python code has changed since then, and I can't see this behavior.

**Comment by aeschli** [comment]
Closing then. Feel free to reopen if you see this again.
