### ISSUE TITLE
Issue Reporter reports wrong version of macOS

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#55920]
Issue Type: <b>Bug</b>

The meta image :p

![image](https://user-images.githubusercontent.com/4033249/43744739-5a2f583c-9990-11e8-874e-6fc9d1ac9981.png)

VS Code version: Code - Insiders 1.26.0-insider (c2ddece6536330f4b4ceef33de5eea6e406fb30a, 2018-08-06T10:26:45.088Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (6.94GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|25%|

</details>

**Comment by RMacfarlane** [comment]
Ah, it's using https://nodejs.org/api/os.html#os_os_release, which reports the kernel release version
