### ISSUE TITLE
Rename symbol with no references fails with "No result."

### ISSUE THREAD

**Issue by alongafni** [Microsoft/vscode#55922]
Issue Type: <b>Bug</b>

I've added a class that was not yet used anywhere. When I tried to rename it (with F2) it failed and showed a tool tip with "No result."

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.92GB (37.88GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.19.0
vscode-eslint|dba|1.4.12
tslint|eg2|1.0.34
vscode-npm-script|eg2|0.3.5
json-tools|eri|1.0.2
beautify|Hoo|1.3.2
rest-client|hum|0.19.0
PowerShell|ms-|1.8.2
debugger-for-chrome|msj|4.8.2
vscode-docker|Pet|0.1.0
vscode-todo-highlight|way|1.0.4

</details>

**Comment by ramya-rao-a** [comment]
What kind of a file were you trying this on?

**Comment by alongafni** [comment]
So apparently my VSCode went into a weird state and had to be restarted... After restarting it the "rename" issue went away too. So I'm closing this issue
