### ISSUE TITLE
IDE thinks the debugging process is already running when isn't

### ISSUE THREAD

**Issue by remster** [Microsoft/vscode#55935]
Issue Type: <b>Bug</b>

Just a simple go program - when I i hit debug and it fails to compile - i cannot hit debug again as IDE thinks the process is already running. 

![alreadyrunning](https://user-images.githubusercontent.com/8327961/43762854-60c19c5c-9a29-11e8-81dc-86321bd15249.png)

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:40:20.190Z)
OS version: Linux x64 4.15.0-29-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 2, 2|
|Memory (System)|15.39GB (2.07GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.7.1
cpptools|ms-|0.17.7
Go|ms-|0.6.85

</details>

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/56136
