### ISSUE TITLE
Display of monospaced font has shifted

### ISSUE THREAD

**Issue by sinaku-developer** [Microsoft/vscode#5593]
- VSCode Version:1.0.0
- OS Version:OS X EI Capitan 10.11.4

Steps to Reproduce:

1.Enter the double-byte and single-byte characters.

2.character is off the correct position.

あああああ
aaaaaaaaaa

**Comment by alexandrudima** [comment]
@sinaku-developer We do not layout the individual characters, we leave it up to Chromium, which layouts them based on the font. May I suggest that you use the "editor.fontFamily" setting to change the font to one that does monospaced CJK characters

**Comment by alexandrudima** [comment]
Closing because there is no code change we can do on our side to force wide characters to be rendered at the width of 2 latin characters. There are fonts, such as Inconsolata which render this as desired.
