### ISSUE TITLE
VSCode lags tremendously when a background update for VSCode is triggered

### ISSUE THREAD

**Issue by sakettawde** [Microsoft/vscode#55933]
Issue Type: <b>Bug</b>

At a random time, VSCode will begin to start lagging heavily. This is for the Insiders (no admin privileges version) of VSCode.

At this point in time, it takes about a minute to register a keystroke. After about 5 minutes, I decided maybe I need to close VSCode and open it again. As soon as I close, a dialog box pops open which says VSCode is updating. Then it goes away in a couple of moments and I reopen VSCode and it runs fine.

This has happened 3 times now. And the only common factor in all 3 cases was the update dialog box that popped up after I closed VSCode. This is only happening now after I have shifted to the 'no admin privileges' version.

VS Code version: Code - Insiders 1.26.0-insider (c2ddece6536330f4b4ceef33de5eea6e406fb30a, 2018-08-06T10:34:04.876Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (1.90GB free)|
|Process Argv|C:\Users\Saket\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.12
githistory|don|0.4.2
react-native-react-redux|EQu|1.9.1
prettier-vscode|esb|1.5.0
vscode-styled-components|jpo|0.0.21
vsliveshare|ms-|0.3.504
java|red|0.29.0
vscode-java-debug|vsc|0.11.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.7.1
vscode-maven|vsc|0.10.0
vscode-react-native|vsm|0.6.13

</details>

**Comment by kataweina** [comment]
I think the issue im experiencing may be related to this.
at times, my VScode-Insiders runs a java process that eats CPU a lot, and if force quit, the process restarts in a few minutes, but not always.
Process details from Activity Monitor:
![image](https://user-images.githubusercontent.com/20850780/43859723-780395f4-9b1f-11e8-8cf0-6c4adea16cdb.png)

Sample of the process:
[Sample of java.txt](https://github.com/Microsoft/vscode/files/2271680/Sample.of.java.txt)

System info:
![image](https://user-images.githubusercontent.com/20850780/43859804-bf09031c-9b1f-11e8-8a77-8ba2cedb15a2.png)

I want to say i had the same issue in the non-insider version of VScode which is what prompted me to switch to insider.

**Comment by joaomoreno** [comment]
Can you reproduce with `--disable-extensions`? This could come from any of the Java extensions... can you double check with them?

**Comment by kataweina** [comment]
#facepalm, didn't even think to check the extensions.
Running Insiders today with only Beautify 1.3.2 and ESLint 1.4.12 enabled (uninstalled all the other ones, which were mostly Salesforce integration ones and some themes). Will let you know if I see more issues.

**Comment by joaomoreno** [comment]
Cool, let us know.

**Comment by kataweina** [comment]
Works like a charm, i'm gonna go ahead and blame Salesforce extensions. #thanksSalesforce
