### ISSUE TITLE
Editor crashing on Select all in medium big files

### ISSUE THREAD

**Issue by ddeath** [Microsoft/vscode#55939]
Issue Type: <b>Bug</b>

When I open my log file which is 176MB big it opens it all right. But when I want to select all content with Ctrl + A then it crash.

This not happen on small files or bigger files. For example when I open my second log file 694MB then it opens it without any problem and when I press Ctrl + A whole content of file is selected without crash.

I tried multiple "medium" sized files and it crashed on them too.

This is maybe another bug but on that bigest file I am able to select the text but not to delete it. When I press delete button, nothing happens...

VS Code version: Code - Insiders 1.26.0-insider (21ddb4843b2f40e3cd82500794dc9a1b9404717d, 2018-08-06T08:57:47.809Z)
OS version: Linux x64 4.15.0-24-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 3084)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.21GB (2.43GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.12
tslint|eg2|1.0.34
flow-for-vscode|flo|0.8.2
reasonml|fre|1.0.38
docthis|joe|0.7.1
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
python|ms-|2018.7.1
cpptools|ms-|0.17.7
js-atom-grammar|ms-|0.1.14
vsliveshare|ms-|0.3.504
vsliveshare-audio|ms-|0.1.32
debugger-for-chrome|msj|4.8.2
vscode-code-outline|pat|0.2.1
autoimport|ste|1.5.3
vscode-proto3|zxh|0.2.1

</details>

**Comment by alexandrudima** [comment]
@ddeath I think this might be due to the selection clipboard. Does this reproduce when using `editor.selectionClipboard: false` ?

**Comment by ddeath** [comment]
@alexandrudima when I set `editor.selectionClipboard: false` then the the editor does not crash anymore.

But the issue with deleting content of large files persist. So if I select content of the large file with `ctrl + a` and then press delete, it will do nothing.

**Comment by alexandrudima** [comment]
Thank you for confirming. Yes, the delete issue is tracked in #42473. We should better protect ourselves and not write to the selection clipboard large text.
