### ISSUE TITLE
Find in Files not working

### ISSUE THREAD

**Issue by master-kenobi** [Microsoft/vscode#55936]
Issue Type: <b>Bug</b>

CTRL+SHIFT+F and search for any terms. Doesn't return any result except from files in Open Editors. Previously it return the result from all files in opened folder (CTRL + K CTRL + O).

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.96GB (6.43GB free)|
|Process Argv|D:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.7.1
cpptools|ms-|0.17.7
change-case|wma|1.0.0

</details>

**Comment by roblourens** [comment]
Can you try in Insiders? Also please see the troubleshooting tips here: https://github.com/Microsoft/vscode/wiki/Search-Issues
