### ISSUE TITLE
Machine get stuck when switching between multiple VSCode windows(切换多个VSCode窗口时死机)

### ISSUE THREAD

**Issue by zchrissirhcz** [Microsoft/vscode#55932]
- VSCode Version: 1.25.1 
(版本: 1.25.1
提交: 1dfc5e557209371715f655691b1235b6b26a06be
日期: 2018-07-11T15:43:53.668Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
架构: x64)
- OS Version: Windows 10

Steps to Reproduce:

1. Boot my Windows 10 System
2. Open VSCode, and disable all possible plugins (The Chinese language plugin cannot be disabled)
3. Re-open VSCode, so only Chinese language plugin is loaded.
4. Open another two VSCode window.
5. Go to other applications for a while. e.g. View webpages on Google Chrome, and Xshell connection to remote server to edit some files.
6. Switch back to one VSCode windows
7. (May just for very few seconds) Switch to another VSCode window.**At this moment, the mouse icon turns into a circle ring, and only mouse can move. Any other GUI cannot move, Ctrl+Alt+Del does not response**. 

Note, this phenomenon occurs 3 times today, which is a stable phenomenon on my machine.

Does this issue occur when all extensions are disabled?: Only the Chinese language extension is enabled, but I cannot disable it.

========= The following is the Chinese description, ignore it if you don't need ===========
问题描述是这样的：首先禁用所有可以禁用的VSCode插件，发现中文插件没法禁用；然后重启VSCode，并且一共开了3个VSCode窗口；然后开浏览器或别的应用，一段时间之后，切回到VSCode，并且很快的再切到另一个VSCode窗口，这时候就崩了，鼠标变成转圈状态，并且只有鼠标能动，其他窗口动不了。这个现象今天出现了3次，非常稳定。

**Comment by ramya-rao-a** [comment]
Please follow our [wiki on Performance Issues](https://github.com/Microsoft/vscode/wiki/Performance-Issues). It may help in narrowing down the issue.
Do you see any high cpu or memory usage at this time?
Can you try our [latest Insiders](https://code.visualstudio.com/insiders) and let us know if you see the same issue there?

**Comment by zchrissirhcz** [comment]
@ramya-rao-a Thanks for your advice. I've uninstalled VSCode and installed [your latest Insiders](https://code.visualstudio.com/insiders) version. However, this time it even get worse: After I installed this version, it popup small window on the bottom-right corner of VSCode main window, asking me that if I would like to install the Chinese Language Plugin, and I choose yes, and right after that, this VSCode window restart, and within no more than 10 seconds, it get stuck that again only my mouse can move and any other application's GUI window cannot move, the machine died again. I'm very confusing but frustrated that I even have not ready to open the process monitor of VSCode, it crashes.

**Comment by ramya-rao-a** [comment]
@zchrissirhcz Sorry about that. Can you run `code --status` in a terminal after opening it again? That can give us some clue on what process is creating the problem.

**Comment by zchrissirhcz** [comment]
@ramya-rao-a  I need to change `code --status` to `code-insider --status`

When opening two VSCode windows, and run that command, it gives the status of a that second:
```
C:\Users\zz9555>code-insiders --status


Version:          Code - Insiders 1.26.0-insider (c827480be25bd63065e7ee2e106c24a707c08004, 2018-08-08T18:51:13.457Z)
OS Version:       Windows_NT x64 10.0.17134
CPUs:             Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)
Memory (System):  7.86GB (3.05GB free)
VM:               0%
Screen Reader:    no
Process Argv:     C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    disabled_software
                  rasterization:                enabled
                  video_decode:                 enabled
                  video_encode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled
CPU %   Mem MB     PID  Process
    0      109   12772  code-insiders main
    0      230   11544     window (CMakeLists.txt - caffe-ssd - Visual Studio Code - Insiders)
    0       68    9256       extensionHost
    0       36    3780         searchService
    0       36    8824         electron_node jsonServerMain.js
    0       35   13608       searchService
    0       11   14880       watcherService
    0       10   14792         console-window-host (Windows internal process)
    0      128   13128     gpu-process
    0       77   13340     shared-process
    0      152   13364     window (ssd_train (3).prototxt - Desktop - Visual Studio Code - Insiders)
    0       35   13592       searchService
    0       13   13636       electron-crash-reporter
    0       11   13716       watcherService
    0       10   13724         console-window-host (Windows internal process)
    0       52   13796       extensionHost
    0       36   13944         searchService
    0      138   14944     window (娆㈣繋浣跨敤 - Visual Studio Code - Insiders)
    0       35   14456       searchService
    0       51   15192       extensionHost

Workspace Stats:
|  Window (ssd_train (3).prototxt - Desktop - Visual Studio Code - Insiders)
|  Window (CMakeLists.txt - caffe-ssd - Visual Studio Code - Insiders)
|    Folder (Desktop): 14 files
|      File types: prototxt(12) ini(1) lnk(1)
|      Conf files:
|    Folder (caffe-ssd): 720 files
|      File types: cpp(214) hpp(116) cu(65) prototxt(58) py(53) sh(44) md(40)
|                  cmake(23) m(22) txt(16)
|      Conf files: cmake(23) makefile(2) settings.json(1)
```

It seems OK. Do you know any command that consistently watch VSCode's running status?

**Comment by ramya-rao-a** [comment]
Try Help -> Process Explorer. For other ways you can monitor, see [Performance Issues](https://github.com/Microsoft/vscode/wiki/Performance-Issues)

**Comment by zchrissirhcz** [comment]
I've updated my windows10 system and using the latest (1.27.1) vscode insider version, and it seems it won't hang like before.
