### ISSUE TITLE
Go to definition or Cmd + Click not working

### ISSUE THREAD

**Issue by vajrakumar** [Microsoft/vscode#55942]
Issue Type: <b>Bug</b>

I have function defined and used in javascript right click and click on go to definition states "No Definition found for 'testFn'"

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (4.32GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_98328|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by ramya-rao-a** [comment]
Please share a small sample code that we can use to see this issue?
Do you see this issue with all extensions disabled?

**Comment by ramya-rao-a** [comment]
@tnakaicode Please share a sample code and the type of file where you are trying this. Do you see this in the [latest Insiders](https://code.visualstudio.com/insiders) as well?
