### ISSUE TITLE
Marketplace: Download Extension link not visible with Linux useragent

### ISSUE THREAD

**Issue by SimonBoorer** [Microsoft/vscode#55948]
When I open https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint using the following user agent the Download Extension link is not visible:

`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36`

![screenshot at 2018-08-07 15 44 20](https://user-images.githubusercontent.com/814110/43783112-cdf2a33c-9a58-11e8-9339-31776f4a7dc6.png)

When I change my user agent to the following it becomes visible after refreshing the page and works as expected:

`Mozilla/5.0 (MSIE 10.0; Windows NT 6.1; Trident/5.0)`

![screenshot at 2018-08-07 15 45 57](https://user-images.githubusercontent.com/814110/43783183-010d6220-9a59-11e8-9b26-14f92891191f.png)

This is frustrating as it is the documented way for downloading extensions for installing offline:
https://code.visualstudio.com/docs/editor/extension-gallery#_can-i-download-an-extension-directly-from-the-marketplace

**Comment by ramya-rao-a** [comment]
@auchenberg Can you assign this to our friends at the marketplace?

**Comment by auchenberg** [comment]
@ramya-rao-a Done.

**Comment by harishkragarwal** [comment]
@SimonBoorer : thanks for reporting this. This has been fixed and will be deployed in coming weeks.
