### ISSUE TITLE
openOnSessionStart not working with internalConsole

### ISSUE THREAD

**Issue by CoenraadS** [Microsoft/vscode#55940]
Issue Type: <b>Bug</b>

I made a new project with `dotnet new console`

When I press f5 to debug, or use the green arrow, the intergrated console has focus with the build info, instead of the debug console.

lauch.json:

```
{
    // Use IntelliSense to find out which attributes exist for C# debugging
    // Use hover for the description of the existing attributes
    // For further information visit https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            // If you have changed target frameworks, make sure to update the program path.
            "program": "${workspaceFolder}/bin/Debug/netcoreapp2.0/DockerLogTest.dll",
            "args": [],
            "cwd": "${workspaceFolder}",
            // For more information about the 'console' field, see https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md#console-terminal-window
            "console": "internalConsole",
            "stopAtEntry": false,
            "internalConsoleOptions": "openOnSessionStart",
            "logging": {
                "moduleLoad": false,
            }
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command:pickProcess}"
        },
    ]
}
```

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Memory (System)|16.00GB (5.82GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|2.5.24
markdown-mermaid|bie|1.0.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
bracket-pair-colorizer|Coe|1.0.59
githistory|don|0.4.2
tslint|eg2|1.0.34
auto-rename-tag|for|0.0.15
python|ms-|2018.7.1
azurecli|ms-|0.4.2
csharp|ms-|1.15.2
PowerShell|ms-|1.8.2
vsliveshare|ms-|0.3.504
team|ms-|1.136.0
debugger-for-chrome|msj|4.8.2
code-settings-sync|Sha|3.0.0
vscode-wakatime|Wak|1.2.3
markdown-all-in-one|yzh|1.6.0

</details>

**Comment by weinand** [comment]
Please file this issues against the extension you are using.

**Comment by gregg-miskelly** [comment]
@weinand this doesn't sound like a C# extension issue. I am not sure if you have an idea for whatever other extension should be investigated. But to me it sounds like some sort of mysterious VS Code issue.

From what @CoenraadS said, the issue is that VS Code isn't deciding to bring the 'Debug Console' tab to the foreground and instead leaving the 'Terminal' tab up even though his configuration has `"internalConsoleOptions": "openOnSessionStart"`. I am not able to reproduce this problem myself.
