### ISSUE TITLE
skipFiles Option in Auto Attach Debugger

### ISSUE THREAD

**Issue by jason-wihardja** [microsoft/vscode#55947]
How to define the default skipFiles option for use in debugger auto attach scenario?

**Comment by weinand** [comment]
this is not yet possible (but planned).

**Comment by blitzmann** [comment]
Is this still not a thing?

**Comment by weinand** [comment]
not yet, 2 upvotes is not a lot..

But please suggest how we should tackle this (or even submit a PR)

**Comment by Bnaya** [comment]
@weinand can you provide a general direction where to look?

Thanks!

**Comment by weinand** [comment]
The auto attach feature lives in the node-debug extension. 
And the debug configuration is created here: https://github.com/microsoft/vscode-node-debug/blob/56e6390daac11a50022482a0de7c430a1d4c45e4/src/node/extension/autoAttach.ts#L93-L98

**Comment by adanilev** [comment]
Could you add an attribute to the attach configuration (`"autoAttach": true`)? Then auto-attach uses the first node config where that flag is set to true?

Or a settings config that you point to an attach config by name (`"debug.node.defaultAttachConfig": "myConfigName"`) 

I love the auto-attach feature but not being able to skip node internal files means I need to stop using it.

**Comment by weinand** [comment]
@connor4312 since auto-attach is now implemented in js-debug, you might want to decide what to do here.

**Comment by connor4312** [comment]
This is now possible via the `debug.javascript.terminalOptions` setting, which allows you to specify options as in `node` type launch configs.

**Comment by weinand** [comment]
aha, but "terminalOptions" sounds strange...

**Comment by connor4312** [comment]
We use those settings (originally) for the JavaScript Debug Terminal as well as auto attach. Pending eventual coalescence of those into one thing, which I think will happen at some point, they're still very similar flows and options are probably relevant for both.
