### ISSUE TITLE
Rename hover doesn't show underscores when using certain fonts

### ISSUE THREAD

**Issue by segevfiner** [Microsoft/vscode#55953]
- VSCode Version: 1.25.1 x64
- OS Version: Ubuntu 16.04.5 x64

Steps to Reproduce:
1. Use "DejaVu Sans Mono" or "[DejaVu Sans Mono for Powerline](https://github.com/powerline/fonts/tree/master/DejaVuSansMono)" at the default 14px.
2. Try to rename something on a supported language using F2.

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/24731903/43787958-e986b220-9a74-11e8-8710-18d0a3e9ba89.png)

Similar to https://github.com/Microsoft/vscode/issues/35901, but likely rendered using a completely different code path and possibly just a CSS issue.

**Comment by jrieken** [comment]
@segevfiner You have typed `print_hello_world`, right that correct?

**Comment by segevfiner** [comment]
> @segevfiner You have typed print_hello_world, right that correct?

Yes.

**Comment by fdg-org** [comment]
FWIW, the workaround to set `"window.zoomLevel": -0.001,` in `settings.xml` as mentioned in #35901 does **not** work here.

**Comment by fdg-org** [comment]
Another part where underscores are invisible is the auto-complete suggestions box:
![screenshot from 2018-08-15 11-48-46](https://user-images.githubusercontent.com/11015449/44142790-a0119778-a081-11e8-9cfa-78b4b2d826bf.png)

Interestingly the underscore is visible in the blue highlighted part.
