### ISSUE TITLE
"Java Server Pages" in "Language selection" option not available

### ISSUE THREAD

**Issue by the1derer** [Microsoft/vscode#55957]
Issue Type: <b>Feature Request</b>

"Java Server Pages" in "Language selection" option not available.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

**Comment by V-ed** [comment]
The [Java Server Pages (JSP) extension](https://marketplace.visualstudio.com/items?itemName=pthorsson.vscode-jsp#overview) might fix your problem.

**Comment by ramya-rao-a** [comment]
@the1derer I am assuming you mean you cant change the language mode to `Java Server Pages`. If so, then @V-ed  is right.

We dont support all languages out of the box, instead rely on extensions.
