### ISSUE TITLE
VSCode extensions stop working, requires reboot

### ISSUE THREAD

**Issue by Grehgous** [Microsoft/vscode#55963]
I have been experiencing an issue where extensions stop working. Currently I am using only the GO extension. The issue usually occurs after an hour or so of using VSCode, and makes it so that none of the GO features work, such as intellisense, testing packages, etc.. The dev console has a bunch of errors like:

```
[Extension Host] Activating extension 'ms-vscode.Go' failed: ENOENT: no such file or directory, lstat 'C:\SnapVolumesTemp\MountPoints\{8e491ec5-0000-0000-0000-100000000000}\SVROOT\Users\me'.
t.log @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:270
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:270 
```

I am on a VDI and I believe the issue has to do with how it looks for the file paths are set. If I uninstall the GO extension, restart the computer, then install the GO package it usually starts working again.

**VSCode:**
VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.14393

**System info:**
|CPUs|Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz (4 x 2694)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|8.00GB (4.31GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|100%|

**Go env:**
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\me\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=\\<website>.com\Users$\me\go
set GORACE=
set GOROOT=\\<website>.com\users$\me\GoRoot\Go
set GOTMPDIR=
set GOTOOLDIR=\\<website>.com\users$\me\GoRoot\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\me\AppData\Local\Temp\go-build090429926=/tmp/go-build
-gno-record-gcc-switches

**Comment by Grehgous** [comment]
Go is the only extension that I am using now. Can't remember if all extensions behaved that way. I will test it.

**Comment by sandy081** [comment]
@ramya-rao-a 

>  Activating extension 'ms-vscode.Go' failed: ENOENT: no such file or directory, lstat 'C:\SnapVolumesTemp\MountPoints\{8e491ec5-0000-0000-0000-100000000000}\SVROOT\Users\me'.

Does the GO extension is getting this error in its activation?

**Comment by Grehgous** [comment]
Yes, the Go extension gets the error at startup. It seems to be an issue with all extensions.

Our cloud engineer says that there's an IO filter driver installed by VMware App Volumes that redirects any requests written from where it's normally written to a different locatoin. For instance, writing to C:\Users\(username)\.vscode\extensions is redirected by the IO filter driver to C:\Snapvolumestemp\Mountpoints\(UUID string)\SVROOT\Users\(username)\.vscode\extensions, and etc.

**Comment by sandy081** [comment]
I see.

Does it work if the redirection does not happen? 
And where does the extensions are located, is it in first path or redirected path?

**Comment by Grehgous** [comment]
Redirection always happens behind the scenes, and as a VDI user I have no way to stop it. The extensions show in both paths, but are actually stored in the (hidden) redirected path.

**Comment by sandy081** [comment]
You mean extensions do exist under the path

`C:\Snapvolumestemp\Mountpoints\(UUID string)\SVROOT\Users\(username)\.vscode\extensions`

If so, is there any restrictions from the VM to write into this folder?

**Comment by Grehgous** [comment]
They do exist under that path. I can view files in that path but can't open them or write to that path, I can only write to `C:\Users\(username)\.vscode\extensions` which then redirects to that path.

**Comment by sandy081** [comment]
Not sure how can we help here as you have some filters installed on your VM which is redirecting the path to a non existing location.
