### ISSUE TITLE
Import auto replace spolied all the codebase

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#55962]
Just wanted to express my annoyance 👿 

**I moved a single file**, and VS code proposed to "replace imports automatically" or what does it say. What happend after: it replaced ALL relative imports `../some/path/...`  to something like `~/app/some/path` such paths is valid only for front-end app.

Also, it replaced `import {styles} from 'typestyle'` to `import {styles} from 'typestyle/lib'`, and like that, what? I even noticed some time minutes later.

Though this probably should go to Typescript.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?
