### ISSUE TITLE
Custom problem matcher not clearing problems correctly

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#55964]
Issue Type: <b>Bug</b>

I have the following problem matchers associated with an npm task which is a webpack watcher using ts-loader and tslint-loader. It seems to capture and populate the Problems view, but when errors are cleared it leaves behind problems in other (not opened) files. It seems like a clean run from the watch should clear all the problems.

/cc @dbaeumer 

```json
{
	"type": "npm",
	"script": "watch",
	"group": "build",
	"isBackground": true,
	"problemMatcher": [
		{
			"fileLocation": "absolute",
			"owner": "typescript",
			"pattern": [
				{
					"regexp": "\\[tsl\\] ERROR in (.*)?\\((\\d+),(\\d+)\\)",
					"file": 1,
					"line": 2,
					"column": 3
				},
				{
					"regexp": "\\s*TS\\d+:\\s*(.*)",
					"message": 1
				}
			],
			"severity": "error",
			"source": "ts",
			"background": {
				"activeOnStart": true,
				"beginsPattern": {
					"regexp": "webpack is watching the files..."
				},
				"endsPattern": {
					"regexp": "Built at\\:(.*)"
				}
			}
		},
		{
			"fileLocation": "relative",
			"owner": "typescript",
			"pattern": [
				{
					"regexp": "WARNING in (.*)",
					"file": 1
				},
				{
					"regexp": "Module Warning (.*)"
				},
				{
					"regexp": "\\[(\\d+), (\\d+)\\]: (.*)",
					"line": 1,
					"column": 2,
					"message": 3
				}
			],
			"severity": "warning",
			"source": "tslint",
			"background": {
				"activeOnStart": true,
				"beginsPattern": {
					"regexp": "webpack is watching the files..."
				},
				"endsPattern": {
					"regexp": "Built at\\:(.*)"
				}
			}
		}
	]
},
```

VS Code version: Code - Insiders 1.26.0-insider (aceb8771b1c0e116f684091986ad25769bdc0537, 2018-08-07T07:55:29.593Z)
OS version: Windows_NT x64 10.0.17730

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (15.71GB free)|
|Process Argv|C:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by dbaeumer** [comment]
@eamodio if I understand this correctly these problems aren't TypeScript problem. So they shouldn't use `typescript` as the owner.

Can you provide me with a GitHub repository I can clone that demos this?

**Comment by eamodio** [comment]
@dbaeumer They are coming from the webpack `ts-loader` which would be the equivalent of `typescript` owner no?

If you try the `develop` branch of the [GitLens repo](https://github.com/eamodio/vscode-gitlens/) it has it all setup with webpack and the problem matchers

**Comment by dbaeumer** [comment]
I cloned the repository. Can you provide steps I have to do to see the problem?

**Comment by dbaeumer** [comment]
OK. I was able to reproduce and the problem is that `webpack is watching the files…` is only issued once.

A background problem matcher for a watching task always needs a start / end expression to function correctly. When the start is detected the matcher scans the output and when the end is detected it stops scanning and clears all old problems. Since there is no new start it never clears.

Any objection to close ?

**Comment by eamodio** [comment]
Damn, ok -- thank you for the help!

**Comment by dbaeumer** [comment]
No problem.
