### ISSUE TITLE
searching for symbols/method names via ctrl-p sublime keymap extension is slow

### ISSUE THREAD

**Issue by aarumug** [Microsoft/vscode#55966]
Issue Type: <b>Bug</b>

When you try to search for a symbol or method in a c++ file using the sublime keymap extension, the search is way slower compared to sublime text. I am guessing that the performance of search is not related to the sublime keymap extension. But I must say I haven't tried it without the extension. This perf issue has been the main reason I switch back to sublime text after trying vscode for a while.

VS Code version: Code - Insiders 1.26.0-insider (aceb8771b1c0e116f684091986ad25769bdc0537, 2018-08-07T07:55:29.593Z)
OS version: Windows_NT x64 10.0.17728

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.79GB (11.52GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.12
vscode-nmake-tools|Mic|1.1.180726013
python|ms-|2018.7.1
cpptools|ms-|0.17.7
github-issues-prs|ms-|0.9.0
sublime-keybindings|ms-|4.0.0
vscode-gn|npc|1.0.0

(2 theme extensions excluded)

</details>

**Comment by ramya-rao-a** [comment]
This is related to the C++ extension and not the keymap. Please log an issue on the C++ extension
