### ISSUE TITLE
Show split view for multiple parallel tasks

### ISSUE THREAD

**Issue by jpike88** [microsoft/vscode#55979]
I run two tasks side by side when developing. Both have TS watch for two seperate TS projects.

I'd like a way to be able to have their terminals show in a split view, so I can see TS errors for each.

Instead I have to keep switching dropdown menus and it's really frustrating.

**Comment by alexr00** [comment]
We support this now! Checkout the presentation group here: https://code.visualstudio.com/docs/editor/tasks#_output-behavior
