### ISSUE TITLE
How do disable git extension?

### ISSUE THREAD

**Issue by zhaotongxue** [Microsoft/vscode#55978]
- Extension Name: git
- Extension Version: 1.0.0
- OS Version: Windows_NT x64 10.0.15063
- VSCode version: 1.25.1

 We have written the needed data into your clipboard. Please paste:

How do disable git extension?

it costs me 900ms to setup up.To slow.

**Comment by joaomoreno** [comment]
Set `git.enabled: false` in your settings.
