### ISSUE TITLE
Problema con selección

### ISSUE THREAD

**Issue by jahirvidrio** [Microsoft/vscode#55973]
Issue Type: <b>Bug</b>

Por alguna razón si selecciono texto y después (sin anular aún la selección) si quiero colocar el puntero sobre alguno de los caracteres seleccionados no puedo, debo anular la selección y después ya puedo colocar el puntero donde quiero.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A9-9410 RADEON R5, 5 COMPUTE CORES 2C+3G    (2 x 2895)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.45GB (6.45GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|80%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
lualinter|dcr|1.0.3
path-autocomplete|ion|1.12.0
Lua|key|0.0.9
vscode-language-pack-es|MS-|1.25.2
sublime-keybindings|ms-|4.0.0
java|red|0.29.0
ayu|tea|0.14.0
vscode-java-debug|vsc|0.11.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.7.1
vscode-maven|vsc|0.10.0

</details>

**Comment by ramya-rao-a** [comment]
Translation: 
> For some reason if I select text and then (without canceling the selection yet) if I want to place the pointer over one of the selected characters I can not, I must deselect it and then I can place the pointer where I want.

**Comment by ramya-rao-a** [comment]
@jahirvidrio What is the scenario where you want to click inside a selection and do not want the selection to change?
