### ISSUE TITLE
Image files of *.tiff format do not display properly

### ISSUE THREAD

**Issue by deadcoder0904** [Microsoft/vscode#55987]
Issue Type: <b>Feature Request</b>

Just like it opens up `png` files, support `tiff` as well :)

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.7.0

**Comment by bpasero** [comment]
@mjbvz I can open a tiff file but it does not show properly. Could this be related to the inlining we seem to do?

**Comment by mjbvz** [comment]
Chrome—and therefore electron—does not support displaying tiffs. We should treat this as a binary file instead of trying to open it as image

**Comment by deadcoder0904** [comment]
Cool. Bdw you peeps are doing a wonderful job. Probably the best team for me ❤️
