### ISSUE TITLE
search is not being done recursively if some results are found in the top level directory...it searches recursively if nothing is found on top level deirectory

### ISSUE THREAD

**Issue by sahilmehla** [Microsoft/vscode#55986]
I tried to go through the existing issue but didn't helped.

Thanks
Sahil

**Comment by sahilmehla** [comment]
If i enable the "match case" property...search seems to be recursive by seeing the number of results, but ignore case property is surely have some issue.

Thanks

**Comment by roblourens** [comment]
Can you check out this troubleshooting wiki to see if anything helps? https://github.com/Microsoft/vscode/wiki/Search-Issues

Also, can you give some more details about exactly what you are trying and what you see?
