### ISSUE TITLE
Feature-request: Project level extensions

### ISSUE THREAD

**Issue by OysteinAmundsen** [Microsoft/vscode#55985]
Hi.

As a consultant, I work on a lot of different projects all the time. I would really like to use VsCode for all of them, but that would mean I would have to install a lot of extensions, and only use a different fraction of them per project.

It would be really nice if I could install extensions "globally" (for all projects and all instances of VsCode), or on a project level (only installed and taking up memory space and CPU power within the given project). 

Perhaps we could also have an `autoinstall_extensions.json` in the .vscode folder, similar to the recommended `extensions.json`, which would download and install extensions locally for this project (in a .gitignore'd folder inside `./.vscode` perhaps?), first time a developer opens the project in vscode. That would make setting up a development environment for new developers a breeze. Just clone a git repo, open in vscode and wait for vscode to set up all extensions based on repo's configuration.

**Comment by OysteinAmundsen** [comment]
This is mislabeled by the vscodebot. This is a feature-request.

**Comment by ramya-rao-a** [comment]
> or on a project level (only installed and taking up memory space and CPU power within the given project).

An extension only takes up memory/cpu when its activated. So if you are on C# project but also have the python extension installed, then the latter doesnt get activated at all. And so doesnt use up any resources. This is controlled in the activation events of the extension which is declared by the extension author. (Python extension would activate on .py files and not .cs files)

But of course, there may be extensions that have declared themselves to be activated on all file types.

Have you tried to [disable/enable extensions](https://code.visualstudio.com/docs/editor/extension-gallery#_disable-an-extension) by workspace?

> That would make setting up a development environment for new developers a breeze. Just clone a git repo, open in vscode and wait for vscode to set up all extensions based on repo's configuration.

Yes that would make things easy indeed, but we want avoid installing anything on the user's machine without their explicit approval/request. The recommendation system followed by the user choosing "Install All" on the prompt does what you need.

> which would download and install extensions locally for this project

We manage extensions centrally and there is a lot of code around this assumption. Having extensions installed in different locations for each project would complicate things. This can also end up with some extensions repeated across workspaces. The enable/disable extensions by workspace feature was implemented to ease such pain points.

**Comment by OysteinAmundsen** [comment]
In this request, I have a nodejs mindset about dependencies/extensions, which are installed either globally or locally to a project. I admit it might not be the best approach and it definitely takes a lot of diskspace. 

But it mildly annoys me when I have an editor which is so configurable and so lightweight by nature, and I'm able to really streamline it for development on a particular tech-stack - that I have to take the same extensions with me to a totally different tech-stack on the next project. 

I want to look at extensions like what you've done with settings. Where we can have global settings, user settings or workspace settings. Yes, I can disable extensions per workspace, but it seems cumbersome. 

What if extensions were installed centrally, but with an additional config stating if the extension should be available for all projects by default (globally) or only available for an array of projects?

**Comment by ramya-rao-a** [comment]
I understand. Most of your concerns are covered in the below issues
#51658
#49826
#18386
#40239

I'll be closing this issue in favor of the existing ones.
Please feel free to comment/upvote/update the other issues.

**Comment by OysteinAmundsen** [comment]
Brilliant. Good to see that I'm not the only one having these thoughts.
