### ISSUE TITLE
Peek Definition is missing

### ISSUE THREAD

**Issue by tnakaicode** [Microsoft/vscode#55980]
"Peek Definition" window right-click on some symbol - now is missing.

I checked that "Peek definition" existed in Version 1.25.0 and don't exist in Version 1.25.1.

**Comment by ramya-rao-a** [comment]
On what file type were you trying this?
Do you see the `Go to definition` option in the menu?
Can you try our [latest Insiders](https://code.visualstudio.com/insiders)

**Comment by ramya-rao-a** [comment]
> I tried "Peek Definition" and "Go to Definition".
Both were same result.

It is not clear if you mean that both were missing from the menu or that both resulted in error. Please clarify.

Also, on what file type were you trying this?

**Comment by tnakaicode** [comment]
Sorry.
Both resulted in error. I got "No command matching".

I typed this command on Python code.

**Comment by tnakaicode** [comment]
For example following code.

But, this error occurred any Python code. I guess this is caused in setting of VSCode.

```
import numpy as np
import matplotlib.pyplot as plt

if __name__ == "__main__":
    lx, ly = 1, 1
    nx, ny = 100, 100
    px, py = np.linspace (-1, 1, nx)*lx/2, np.linspace (-1, 1, ny)*ly/2 
    mesh = np.meshgrid (px, py)
    func = mesh[0]**2 + mesh[1]**2

    plt.figure()
    plt.contourf (*mesh, func)
    plt.colorbar()
    plt.show()
```

**Comment by ramya-rao-a** [comment]
Sorry my mistake. I meant to ask if you have any python extension installed
