### ISSUE TITLE
Some characters appear cut off in terminal

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#55981]
I've seen characters that appear trimmed in the terminal from time to time. Examples:

![image](https://user-images.githubusercontent.com/323878/43817027-55ccd4c0-9a8c-11e8-9fdc-213c72fb4718.png)

![image](https://user-images.githubusercontent.com/323878/43817034-5a6db44a-9a8c-11e8-9226-ec7297e32d9c.png)

Same instance as the above:
![image](https://user-images.githubusercontent.com/323878/43817113-bcc7851c-9a8c-11e8-84c8-95caabfece79.png)

Happens in just one window for a particular character or set of characters. Fixed by a reload. Maybe I've seen it in windows that were used across different DPI displays?

**Comment by roblourens** [comment]
Saw it in Hyper too: 

![image](https://user-images.githubusercontent.com/323878/44045746-5e0a054e-9ede-11e8-8945-afa5240d4dd6.png)

**Comment by Tyriar** [comment]
Can not repro, note that the horizontal cut off is tracked in  https://github.com/Microsoft/vscode/issues/35901
