### ISSUE TITLE
怎么切换账号

### ISSUE THREAD

**Issue by zhuguoshou** [Microsoft/vscode#55998]
Issue Type: <b>Bug</b>

怎么切换账号

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.95GB (1.65GB free)|
|Process Argv|d:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
luaide|kan|0.7.1
vscode-language-pack-zh-hans|MS-|1.25.3

</details>

**Comment by ramya-rao-a** [comment]
Translation:

> How to switch accounts

**Comment by ramya-rao-a** [comment]
@zhuguoshou VS Code has no concept of accounts. Can you share more details on what you are trying to do?

**Comment by zhuguoshou** [comment]
I want to switch account of luaide? but, I donot know how to do

**Comment by zhuguoshou** [comment]
I find it . Thanks
