### ISSUE TITLE
Hidden search mode tab

### ISSUE THREAD

**Issue by coldner** [Microsoft/vscode#55990]
- VSCode Version: 1.25.1

Steps to Reproduce:

1. Run **FRESH** copy of VSC.
2. Double-click on any word (another word occurrences will highlight)
3. Hit i.e. Alt+C to Case-sensitive search. Matching words will highlight but there should be search mode info tab in right upper corner.

-------

4. **To fix it** hit Ctrl+F and then Escape to disable search tab. Now, when you hit Alt+C search mode info tab in right upper corner will appear. It will work fine until VSC close.
![serach mode](https://user-images.githubusercontent.com/35400886/43827673-b63d47cc-9afa-11e8-9a39-c9192c4cee4a.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
Nice catch. We should show the options dialog on the right corner.
