### ISSUE TITLE
Terminal over laps explorer 

### ISSUE THREAD

**Issue by McDoyen** [Microsoft/vscode#55996]
Issue Type: <b>Bug</b>

When the explore is set to appear on the right `("workbench.sideBar.location": "right")`, the terminal over laps the explorer

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
