### ISSUE TITLE
对于多个<template> 标签  格式化后页面错乱

### ISSUE THREAD

**Issue by Christine-qing** [Microsoft/vscode#55991]
Issue Type: <b>Bug</b>

<template>

<div>
<template>

</template>
</div>
</template>

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|8.00GB (0.24GB free)|
|Process Argv|/Users/lixiaoqing/Desktop/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify-quick-app|Ato|1.0.0
quickapp-for-highlighter|Ato|1.0.3
Angular2|UVB|0.4.1
html-snippets|abu|0.2.1
git-easy|bib|1.9.1
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.59
app-migrator|deb|0.0.6
wpy-beautify|doi|2.0.10
vscode-html-css|ecm|0.2.0
auto-close-tag|for|0.5.6
Hap|hap|0.0.8
vscode-fileheader|mik|0.0.2
HTMLHint|mka|0.5.0
vscode-language-pack-zh-hans|MS-|1.25.3
debugger-for-chrome|msj|4.8.2
vscode-fuse-syntax|nau|1.1.1
vetur|oct|0.12.6
view-in-browser|qin|0.0.5

</details>

**Comment by muuvmuuv** [comment]
Please translate your title into English and provide more information about your bug.

**Comment by ramya-rao-a** [comment]
Translation from Google: 
> For multiple <template> tags formatted page confusing

@Christine-qing Please share sample code and screenshots so that we can understand the issue better

**Comment by ramya-rao-a** [comment]
@Christine-qing Please share sample code and screenshots so that we can understand the issue better
