### ISSUE TITLE
Switch to last tab with cmd/ctrl 9 is no longer working

### ISSUE THREAD

**Issue by johnbillion** [Microsoft/vscode#55994]
Issue Type: <b>Bug</b>

#36567 introduced the ability to switch to the last tab using <kbd>⌘ 9</kbd>/<kbd>ctrl 9</kbd>. This appears to no longer work.

Tested with Code 1.25.1 on macOS 10.12.6.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz (4 x 3300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (2.55GB free)|
|Process Argv|/Applications/Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
erb|Cra|0.0.1
sort-lines|Tyr|1.7.0
Bookmarks|ale|9.0.3
project-manager|ale|8.0.0
scope-bar|amo|0.1.0
alignment|ann|0.3.0
vscode-puppet|bit|0.4.5
vscode-intelephense-client|bme|0.8.8
vscode-svgviewer|css|1.4.4
transformer|dak|1.6.0
jshint|dba|0.10.19
vscode-eslint|dba|1.4.12
vscode-dash|dee|1.10.0
gitlens|eam|8.5.4
tslint|eg2|1.0.34
vs-code-xml-format|fab|0.1.5
php-debug|fel|1.12.3
url-encode|fle|1.1.0
vscode-zoneinfo|gil|2.1.1
beautify|Hoo|1.3.2
phpcs|ika|1.0.5
svn-scm|joh|1.31.0
vscode-map-preview|jum|0.4.2
restructuredtext|lex|65.0.0
VS-code-vagrantfile|mar|0.0.7
rainbow-csv|mec|0.4.2
vscode-scss|mrm|0.6.2
language-gettext|mro|0.1.1
python|ms-|2018.7.1
sublime-keybindings|ms-|4.0.0
debugger-for-chrome|msj|4.8.2
php-docblocker|nei|1.6.0
incrementor|nms|0.1.0
vscode-phpcbf|per|0.0.8
polacode|pnp|0.2.2
vscode-sort-json|ric|1.13.0
vscode-nginx|sha|0.5.0
trailing-spaces|sha|0.2.11
stylelint|shi|0.38.1
gitconfig|sid|1.0.1
vscode-hexdump|sle|1.6.0
cucumber|ste|0.11.5
twig|wha|1.0.2
change-case|wma|1.0.0
html-css-class-completion|Zig|1.17.1

</details>

**Comment by bpasero** [comment]
@johnbillion I cannot reproduce, but it is possible that some other extension you have installed stole this keybinding.

I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by johnbillion** [comment]
Thanks, it looks like this is caused by a custom key mapping.
