### ISSUE TITLE
Launch extension debugger failed

### ISSUE THREAD

**Issue by liwangqian** [Microsoft/vscode#55993]
When launch extension debugger, it fails with the following message:
```
Error: Cannot find module 'c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\spdlog\build\Debug\spdlog.node'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Function.t._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:814:682)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\bindings\bindings.js:81:44)
    at Object.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\spdlog\index.js:3:35)
    at Object.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\spdlog\index.js:21:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
```

**Comment by joaomoreno** [comment]
@liwangqian Does the file `c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\spdlog\build\Debug\spdlog.node` exist?

**Comment by alexandrudima** [comment]
@joaomoreno The path on disk should be `c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node` (note `node_modules.asar.unpacked` and `Release`)

**Comment by liwangqian** [comment]
@joaomoreno That's it. So, do you known how to solve the problem ?

**Comment by joaomoreno** [comment]
@alexandrudima What does that mean? 🤔

**Comment by alexandrudima** [comment]
@joaomoreno You posed a question asking @liwangqian to look for a file that does not exist on any machine. 

> @liwangqian Does the file `c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\spdlog\build\Debug\spdlog.node` exist?

* `node_modules.asar` is a file on disk, it is not a folder that can contain a subfolder called `spdlog`.
* when shipping VS Code we build `spdlog` for `Release` and not for `Debug`.

I was trying to help out but it looks like I've just confused everybody.

**Comment by liwangqian** [comment]
![image](https://user-images.githubusercontent.com/19996314/43934801-9d86c552-9c83-11e8-8614-a4920dfc3f20.png)
@alexandrudima This is the folder snapshot, How can i solve this problem?

**Comment by joaomoreno** [comment]
@alexandrudima Got it!

@liwangqian Does the following file exist? `c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node`

**Comment by joaomoreno** [comment]
Can you show us a screen recording of the error?

**Comment by GzhiYi** [comment]
Same issue in launch a helloworld extension.
How to solve this problem?
![code](https://user-images.githubusercontent.com/21136420/44212621-6834de00-a19e-11e8-97c9-d3a3fd5d0607.png)
I am sure that the spdlog.node file exist.
![path](https://user-images.githubusercontent.com/21136420/44212628-6cf99200-a19e-11e8-9b1f-6e788739b4b8.png)

**Comment by joaomoreno** [comment]
@alexandrudima I am completely clueless with this, maybe this rings any bells to you? It appears this other user does have that file in disk.

**Comment by joaomoreno** [comment]
cc @alexandrudima

**Comment by alexandrudima** [comment]
@joaomoreno I don't understand this issue either.

Here is all you need to know about `.asar.unpacked` in two sentences. When creating an `.asar`, it is possible to leave some files unpacked. In this case, the `.asar` only contains the file name and the file stats, but the contents are left on disk in a sibling folder `.asar.unpacked`.

For example, if somebody wants to open `bla.asar/foo/bar.txt` and the file was left unpacked, then the contents are read from `bla.asar.unpacked/foo/bar.txt`. But please note that everything after the asar name must be the same!

---

The error message in https://github.com/Microsoft/vscode/issues/55993#issuecomment-413552939 complains about a certain path: 

`c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\spdlog\build\spdlog.node`

and the Windows Explorer screenshot shows a different path:

`C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node`

Please look carefully at the paths and observe that:
`\spdlog\build\spdlog.node` is not equal to 
`\spdlog\build\Release\spdlog.node`.

So the error message is valid, `c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\spdlog\build\spdlog.node` can not be found.

Why is `spdlog` looking for its native node module at the wrong path? We ship other native node modules which look for their respective `.node` file at the correct location. Take a look [here for example](https://github.com/Microsoft/node-native-keymap/blob/37c21529b2684d01c7a7527dbbde5382de9c698d/index.js#L15). I think it is possible to look for one's dll at the right location.

**Comment by joaomoreno** [comment]
Since node-spdlog uses `bindings`, it searches for the `.node` module in multiple paths. This message could just be a warning and not an error.

@liwangqian @GzhiYi Does extension debugging really fail? Or it just shows that message? Can you share a screen recording of what happens?

**Comment by liwangqian** [comment]
yes, the debugging really fail. 
sorry to say that, this problem is raised in my working environment, and recording is not allowed.

**Comment by sandy081** [comment]
@joaomoreno Sorry, No idea why the debugging fails.

**Comment by joaomoreno** [comment]
@liwangqian @GzhiYi Can you try our latest insider release?
