### ISSUE TITLE
Middle clicking a working file in the working file list should close it and remove it from working files

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#56]
Ubuntu 12.04, vscode 0.10.1

Seems like an easier/intuitive shortcut instead of trying to hit the tiny `x` button's hitbox.

**Repro:**

1. Open vscode
2. Open a folder
3. Open and edit a file
4. Middle click the file in working files

**Expected:**
The file should be closed and removed from working files (with are you sure/save dialog)

**Actual:**
Nothing

**Comment by bpasero** [comment]
:+1:

**Comment by Tyriar** [comment]
Nice :)
