### ISSUE TITLE
Running `code .` in a terminal does not get env vars from the terminal if there is any Code window already open

### ISSUE THREAD

**Issue by lukehoban** [Microsoft/vscode#560]
It seems that currently users can't rely on running `code .` from a terminal providing that terminals env vars in the new Code window.  

If Code was not running before hand, they will see the expected env vars.

But if Code was running before hand, the new window will see the same env vars as the previous Code windows.

For the `vscode-go` plugin this causes issues because Go relies heavily on env vars to establish the working environment, and different development sessions in different terminals are likely to use different GOPATH vars even during concurrent development sessions.

**Comment by joaomoreno** [comment]
@bpasero the fix here is to propagate the `process.env` over to the browser window, along with the cli arguments that we already do

**Comment by bpasero** [comment]
:+1:
