### ISSUE TITLE
Order of paths in Environmental Variables Matters for Python Interpreter Discovery

### ISSUE THREAD

**Issue by pjkottke** [Microsoft/vscode#56000]
Issue Type: <b>Bug</b>

When discovering Python interpreters, the order of the paths in the PATH Environmental Variable Matters. See attached for two screen shots, when the Plaxis Python install is above the miniconda root directory, the Plaxis Python interpreter is correctly identified; by shifting it down one slot it is no longer discovered.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Memory (System)|15.88GB (8.74GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-dash|dee|1.10.0
vsc-material-theme|Equ|2.3.0
gc-excelviewer|Gra|2.1.25
theme-monokai-pro-vscode|mon|1.1.8
python|ms-|2018.7.1
color-highlight|nau|2.3.0
vscode-code-outline|pat|0.2.1
code-settings-sync|Sha|3.0.0

(1 theme extensions excluded)

</details>

![path_works](https://user-images.githubusercontent.com/2700057/43845152-3e078802-9b23-11e8-82bc-986b1768f9cc.PNG)
![path_doesnt_work](https://user-images.githubusercontent.com/2700057/43845153-3e1ddd14-9b23-11e8-9e39-0f0f4e586c91.PNG)

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-python/
