### ISSUE TITLE
No revuelve el zoom

### ISSUE THREAD

**Issue by AgenteMM** [Microsoft/vscode#56002]
Issue Type: <b>Bug</b>

Estaba poniendo el zoom mas cerca i de repente me pase y ahora cuando intento revolver no funciona ni con teclas ni con las configuraciones ni saliendo i entrando ni desinstalano y volver a instalar y el zoom me ha puesto en la esquina inferior izquierda y me es inaccesible escribir codigo en estas condiciones.
Espero vuestra respuesta inpacientemente

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:11.471Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Genuine Intel(R) CPU             575  @ 2.00GHz (1 x 1995)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|1.93GB (0.43GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.12
vscode-javac|geo|0.1.1
vscode-language-pack-es|MS-|1.25.2
java|red|0.29.0
vscode-java-debug|vsc|0.11.0
vscode-java-pack|vsc|0.3.0
vscode-maven|vsc|0.10.0

</details>

**Comment by ramya-rao-a** [comment]
I am assuming that the window has gone offscreen. Does https://www.howtogeek.com/howto/windows/bring-misplaced-off-screen-windows-back-to-your-desktop-keyboard-trick/ help? If this is not the case, can you share some screenshots of your desktop so that we can understand the issue better
