### ISSUE TITLE
Source control key combination not working

### ISSUE THREAD

**Issue by sauzy34** [Microsoft/vscode#56001]
Using default key combination (Ctrl + Shift + G) to open source control is not working.

**Comment by ramya-rao-a** [comment]
- What version of VS Code are you using? Do you see this in the [latest Insiders](https://code.visualstudio.com/insiders)?
- What OS are you on?
- Do you see this even with all extensions disabled?
- Have changed any keybindings lately?
- Did it work as expected before and recently stopped?

**Comment by sauzy34** [comment]
- Version: 1.25.1
- Checked on Ubuntu and Windows
- Yes, i tried disabling all the extensions.
- I checked in the Default keybindings. `{ "key": "ctrl+shift+g",          "command": "workbench.view.scm" }`
- Yes it was working fine before.

**Comment by ramya-rao-a** [comment]
Can you share other keybindings that you might have changed?
Run `Preferences: Open Keyboard Shortcuts File` and share the contents of the right side of the editor that will have your customization
Do you see this in the latest [insiders](https://code.visualstudio.com/insiders) as well?

**Comment by sauzy34** [comment]
`[
    {
        "key": "ctrl+shift+i",
        "command": "editor.action.formatDocument",
        "when": "editorTextFocus && !editorReadonly"
    },
    {
        "key": "shift+alt+f",
        "command": "-editor.action.formatDocument",
        "when": "editorTextFocus && !editorReadonly"
    },
    {
        "key": "ctrl+shift+a",
        "command": "editor.action.blockComment",
        "when": "editorTextFocus && !editorReadonly"
    },
    {
        "key": "shift+alt+a",
        "command": "-editor.action.blockComment",
        "when": "editorTextFocus && !editorReadonly"
    },
    {
        "key": "alt+l",
        "command": "bookmarks.jumpToNext",
        "when": "editorTextFocus"
    },
    {
        "key": "ctrl+alt+l",
        "command": "-bookmarks.jumpToNext",
        "when": "editorTextFocus"
    },
    {
        "key": "ctrl+alt+k",
        "command": "bookmarks.jumpToPrevious",
        "when": "editorTextFocus"
    },
    {
        "key": "ctrl+alt+j",
        "command": "-bookmarks.jumpToPrevious",
        "when": "editorTextFocus"
    },
    {
        "key": "alt+k",
        "command": "bookmarks.toggle",
        "when": "editorTextFocus"
    },
    {
        "key": "ctrl+alt+k",
        "command": "-bookmarks.toggle",
        "when": "editorTextFocus"
    }
]`

I've not tried VS Code Insiders for a long time

**Comment by alexandrudima** [comment]
@sauzy34 Does the key combination reach VS Code?

What does VS Code detect when you press the desired key combination? Is ctrl+shift+g reaching VS Code?
![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

**Comment by sauzy34** [comment]
![screenshot from 2018-08-11 12-45-44](https://user-images.githubusercontent.com/19049022/43989267-7dd1736a-9d64-11e8-908d-c4b4429b88b4.png)

**Comment by sauzy34** [comment]
![screenshot from 2018-08-13 15-26-03](https://user-images.githubusercontent.com/19049022/44025243-3b9f0462-9f0d-11e8-8db3-8e1058731d05.png)

**Comment by alexandrudima** [comment]
@sauzy34 It looks like the git lens extension is overwriting the builtin keybinding for `ctrl+shift+g`. You can remove all of those keybindings by right clicking and choosing to remove or you can uninstall the git lens extension.
