### ISSUE TITLE
Cmd+Click (Go to Definition) not working when using `require.context`

### ISSUE THREAD

**Issue by akaralar** [Microsoft/vscode#56006]
- VSCode Version: 1.25.1
- OS Version: macOS 10.13.6

I'm using `require.context` API to export everything within a directory automatically. It works nicely, but 'Go to definition' is broken when I import those exports from other files. To give an example about my use case, consider that I have the following directory structure:
```
.
├── store
│   ├── actions.js
│   ├── app
│   │   ├── actions.js
│   │   ├── reducer.js
│   │   ├── sagas.js
│   │   └── selectors.js
│   ├── reducer.js
│   ├── sagas.js
│   ├── selectors.js
└── tools
    ├── lib
    │   └── fs.js
    ├── messages.js
    └── run.js
```

I have this piece of code in the `store/actions.js` file:
```
const req = require.context('.', true, /\.\/.+\/actions\.js$/)

req.keys().forEach((key) => {
  const actions = req(key)

  Object.keys(actions).forEach((name) => {
    module.exports[name] = actions[name]
  })
})
```

This code goes through all directories under `store`, finds all `action.js` files, get all their exports and re-exports them in a specific format. The use case is that when I want to import an action `store/app/actions.js`, I just use 
```'import { fetchAllAppConstants } from 'store/actions'```

So in a way, it makes me agnostic as to the directory structure under `store` and treats that directory as an API boundary. But cmd+clicking that `fetchAllAppConstants` doesn't work in VSCode. Is there a way to make it work?

Steps to Reproduce:

1. Prepare the above directory structure
2. Write the code above into the specified files
3. See that cmd+clicking doesn't work

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
IntelliSense for dynamic requires statements is a limitation of our intellisense, see: https://github.com/Microsoft/TypeScript/issues/26139 and https://github.com/Microsoft/TypeScript/issues/18656 and
