### ISSUE TITLE
中文

### ISSUE THREAD

**Issue by 5920dsaf** [Microsoft/vscode#56004]
中文语言在VSCodeSetup-x64-1.26.0-insider中工具栏无法显示为中文
我安装完之后打开的时候自动安装了中文语言但是重新加载之后工具栏无法正确显示中文

**Comment by ramya-rao-a** [comment]
Translation: Chinese language cannot be displayed as Chinese in VSCodeSetup-x64-1.26.0-insider
I installed the Chinese language automatically when I opened it after the installation, but the toolbar does not display Chinese correctly after reloading.

**Comment by ramya-rao-a** [comment]
@5920dsaf Can you share a screenshot? Also share the extensions you have installed

**Comment by ramya-rao-a** [comment]
- You dont see this issue in the stable version?
- Can you share the settings you have modified in the Insiders?

@sbatten This might be related to the menu work you are doing.

**Comment by xiaotan0305** [comment]
The following is my setup. The stable version doesn't have this problem, but the version number of the stable version, Chinese (Simplified) Language Pack for Visual Studio Code, is 1.25.3。
{
    "workbench.iconTheme": "vscode-icons",
    "editor.fontSize": 16,
    "files.exclude": {
        "**/.git": false,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/.DS_Store": true,
        "**/._*": true,
        "**/.idea": true,
        "**/node_modules": true,
        "**/node-dmp/public/static": true
    },
    "window.newWindowDimensions": "inherit",
    "files.trimTrailingWhitespace": true,
    "editor.wordWrap": "on",
    "emmet.triggerExpansionOnTab": true,
    "editor.find.autoFindInSelection": true,
    "eslint.options": {
        "configFile": "/Users/tankunpeng/WebSite/rules/eslintrc.json"
    },
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
    "editor.snippetSuggestions": "top",
    "editor.tabCompletion": true,
    "editor.detectIndentation": false,
    "files.associations": {
        "*.mix": "html",
        "*.html": "html",
        "*.wxml": "vue-html",
        "*.njk": "nunjucks",
        "*.js": "javascript"
    },
    "liveServer.settings.donotShowInfoMsg": true,
    "workbench.startupEditor": "newUntitledFile",
    "eslint.autoFixOnSave": true,
    "eslint.validate": [
        "javascript",
        "javascriptreact",
        "html",
        {
            "language": "vue",
            "autoFix": true
        }
    ],
    "liveServer.settings.donotVerifyTags": true,
    "explorer.confirmDelete": false,
    "git.enableSmartCommit": true,
    "git.confirmSync": false,
    "diffEditor.ignoreTrimWhitespace": false,
    "editor.minimap.enabled": true,
    "window.zoomLevel": 0,
    "editor.multiCursorModifier": "alt",
    "sync.gist": "1ce7f73bfe98eb8eaf42c576cf5ad5c6",
    "sync.host": "",
    "sync.pathPrefix": "",
    "sync.quietSync": false,
    "sync.askGistName": false,
    "sync.removeExtensions": true,
    "sync.syncExtensions": true,
    "sync.autoDownload": false,
    "sync.autoUpload": false,
    "sync.lastUpload": "2018-08-09T09:40:50.220Z",
    "sync.lastDownload": "",
    "sync.forceDownload": false,
    "fileheader.Author": "tankunpeng@fang.com",
    "fileheader.tpl": "/*\r\n * @Author: {author}\r\n * @Date: {createTime}\r\n * @Description: Description\r\n */\r\n",
    "git.checkoutType": "remote",
    "liveServer.settings.host": "10.2.101.200",
    "terminal.integrated.rendererType": "dom",
    "gitlens.advanced.messages": {
        "suppressShowKeyBindingsNotice": true
    },
    "javascript.updateImportsOnFileMove.enabled": "never",
    "debug.inlineValues": true,
    "debug.enableAllHovers": true,
    "debug.node.autoAttach": "on",
    "debug.allowBreakpointsEverywhere": true,
    "fileheader.LastModifiedBy": "",
    "breadcrumbs.enabled": false,
    "editor.quickSuggestions": {
        "other": true,
        "comments": true,
        "strings": true
    },
    "vetur.format.defaultFormatter.html": "js-beautify-html",
    "workbench.colorTheme": "One Dark Pro",
    "gitlens.codeLens.authors.enabled": false,
    "gitlens.codeLens.recentChange.enabled": false
}

**Comment by xiaotan0305** [comment]
Chinese (Simplified) Language Pack for Visual Studio Code  upgraded to 1.26.3, the problem has been solved, thank you very much.It's a beautiful day

**Comment by ramya-rao-a** [comment]
Thanks for reporting this issue @xiaotan0305  and Happy Coding!
