### ISSUE TITLE
Mac OS X Shortcut key: cmd + F1 (Move Focus to Next Window) not usable

### ISSUE THREAD

**Issue by satokaz** [Microsoft/vscode#5601]
OSX Shortcut key: `command + F1` (Move Focus to Next Window) was no longer work.
Can not be switched vscode window.

`command + F1` Key assignments have been added in the vscode side?
At least until the vscode 1.0.0 was functioning.

- VSCode Version: 1.0.1-insider
- OS Version: Mac OS X 10.11.4 (15E65) - Japanese locale

Steps to Reproduce:

1. Open multiple vscode window
2. Check the `command + F1` key operation

<img width="780" alt="2016-04-21 21 17 12" src="https://cloud.githubusercontent.com/assets/13635244/14708522/83f0081a-0806-11e6-85e7-53a845437edb.png">

**Comment by dbaeumer** [comment]
I checked and we don't Cmd+F1 out of the box. But could be it is on your version. Can you open the Keybindings (File > Preferences > Keybindings) and check if there is a binding for Cmd+F1. You can search in the file.

**Comment by satokaz** [comment]
@dbaeumer 

Thank you for your reply.
I do not define the `command + F1`.

![2016-04-21 22 42 51](https://cloud.githubusercontent.com/assets/13635244/14711205/6e49f5a4-0813-11e6-8df2-ff31dddefa7f.png)

Use the [Display keystroke utility: KeyCast](https://github.com/cho45/KeyCast) was recorded operation.
Is displayed on the left side is a key stroke character is actually the input of the ⌘[F1] (command + F1).
Does this difference would be of environmental issues?

## vscode 1.0 stable Release - **It is expected behavior**
![keycast_licecap](https://cloud.githubusercontent.com/assets/13635244/14712388/e0f36b36-0817-11e6-872b-c04aabec8c18.gif)

## vscode 1.0.1 insider build - **switch is not working**
![keycast_insider_licecap](https://cloud.githubusercontent.com/assets/13635244/14712463/32874a58-0818-11e6-9ac0-b94edad56776.gif)

**Comment by dbaeumer** [comment]
@bpasero could this be a consequence of the electron update. It works in 1.0 and doesn't in 1.0.1-Insider.

**Comment by bpasero** [comment]
Filed https://github.com/electron/electron/issues/5246

**Comment by bpasero** [comment]
@satokaz can you use Cmd+~ instead?

**Comment by satokaz** [comment]
@bpasero Thank you for investigation.

ok, `⌘ + ~ (tilde) ` gave us meet the operation as desired.

![keycast_insider_workaround_licecap](https://cloud.githubusercontent.com/assets/13635244/14736771/98c78148-08b3-11e6-804a-a497fa092d48.gif)

It is global setting does not work for OS X. 
Leave the guide just in case.

**Summary:**
- This problem is Electron bug.
- ` ⌘ + F1`(Move Focus to Next Window) does not work in vscode insider 1.0.1 or later (or Electron version: 0.37.6, At the moment)

**Workaround:** 
- Switching of only vscode windows is possible in `⌘ + ~ (tilde) `. Other window switches in ` ⌘ + F1`.
- If you want to change the global settings,  Please change the shortcut key  ` ⌘ + F1` to `⌘ + ~ (tilde) ` .

<img width="780" alt="2016-04-22 17 57 32" src="https://cloud.githubusercontent.com/assets/13635244/14736811/cc9dc194-08b3-11e6-8abb-a527ba7238b5.png">

**Comment by bpasero** [comment]
Given the workaround, removing the important label.

**Comment by sercanov** [comment]
Workaround is not valid for non-english keyboard users.

**Comment by bpasero** [comment]
@satokaz  we just released a new insiders build with a newer Electron. maybe you could give that build a try to see if it fixes this issue.

You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by satokaz** [comment]
@bpasero Yay!
For a little while ago, I was surprised to verify that it works vscode 1.6.0-insider 6fa85!

Thanks a lot!

**Comment by ramya-rao-a** [comment]
Marking as verified as per @satokaz comment https://github.com/Microsoft/vscode/issues/5601#issuecomment-246967503
