### ISSUE TITLE
Tslint Error

### ISSUE THREAD

**Issue by marcoadaza** [Microsoft/vscode#56016]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:16:27.618Z)
- OS Version: Linux x64 4.8.0-53-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|0.17.0
prettier-vscode|esb|0.24.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
Closing this issue as there are no details.
Please re-open it with more details. The wiki [Submitting Bugs](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions) can help.

**Comment by ISuckGood** [comment]
wow :)
