### ISSUE TITLE
Can't restore panel (e.g. debug panel) position back to default( it doesn't respect its setting )

### ISSUE THREAD

**Issue by pakbaz** [Microsoft/vscode#56010]
- VSCode Version: 1.25.1
- OS Version: Windows 10 (1607)

Steps to Reproduce:

1. Change Panel default location to right by: "workbench.panel.defaultLocation": "right"
2. after opening terminal then split terminal (perhaps delete them after split.)
3. now set the panel back to default which is bottom by "workbench.panel.defaultLocation": "bottom"
4. panels (such as terminal) now opens only in right and doesn't respect new setting. (ctrl + ` )

Does this issue occur when all extensions are disabled?: Yes

**Comment by ramya-rao-a** [comment]
Do you see the same in the latest [Insiders](https://code.visualstudio.com/insiders)?

**Comment by pakbaz** [comment]
I have not checked that

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by ramya-rao-a** [comment]
Please do check the latest Insiders and let us know if you see the same there.
