### ISSUE TITLE
files.hotExit breaks window.restoreWindows:none

### ISSUE THREAD

**Issue by petera703** [Microsoft/vscode#56011]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

1. Open some files in vscode. 
2. In Settings, set 
  "window.restoreWindows": "none"
  "files.hotExit": "onExit" 
3. Save settings.
4. Close and restart vscode.
5. Observe vscode reopens no previous files (correct).
6. Open the same files again, and edit one file without saving.
7. Close and restart vscode.
8. Observe vscode didn't prompt for save on close (correct).
9. Observe vscode reopens the file you edited without saving (correct).
10. Observe vscode reopens all the other files too (incorrect).

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A4-6210 APU with AMD Radeon R3 Graphics     (4 x 1797)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.68GB (3.83GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe W:\Dev\tic-tac-toe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-commandbar|gsp|0.2.24

</details>

**Comment by Tyriar** [comment]
This is behaving as designed as `files.hotExit` `onExit` overrides `window.restoreWindows`, the point of `onExit` is to always shows you the backups when you open VS Code. I think you're after `"files.hotExit": "onExitAndWindowClose"` which does not have that requirement.
