### ISSUE TITLE
New Settings: extension settings initially don't appear in @modified

### ISSUE THREAD

**Issue by JacksonKearl** [Microsoft/vscode#56017]
Issue Type: <b>Bug</b>

- Have some modified extension setting (`"scss.lint.boxModel": "error"`). 
- Go to new settings, search `@modified`
- Setting wont show up (if setting does shows up, try switching back and forth between user and work-space)
- Navigate to some other editor, then back to the settings. Setting now appears.

VS Code version: Code - Insiders 1.26.0-insider (a8033aaf216d684d775e058489d25186702d28e3, 2018-08-07T23:17:55.610Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (7.12GB free)|
|Process Argv|C:\Users\t-jakea\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.0.3
vscode-svgviewer|css|1.4.4
gitlens|eam|8.5.4
tslint|eg2|1.0.34
debugger-for-chrome|msj|4.8.2
subtle-brackets|raf|2.1.1
vscode-multiclip|sle|0.1.4
code-spell-checker|str|1.6.10
sublime-commands|Zar|0.1.0

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
I can't repro, do you still see it?

**Comment by JacksonKearl** [comment]
Looks like it was resolved elsewhere
