### ISSUE TITLE
Request to change jade/pug line comment to //-

### ISSUE THREAD

**Issue by JamesHenry** [Microsoft/vscode#5602]
- VSCode Version: 1.0.0
- OS Version: OSX 10.11.4

Steps to Reproduce:

1. Open a jade file
2. Press `cmd+/`

In the language config, a jade line comment is currently defined as `//`:
https://github.com/Microsoft/vscode/blob/master/src/vs/editor/standalone-languages/jade.ts#L17

This is certainly valid jade, but it gets compiled to an HTML comment, e.g.

**index.jade**
```
// my comment
```

...becomes

**index.html**
```
<!-- my comment -->
```

I think it would be preferable to choose the true jade comment syntax `//-` as **these are not included in the compiled markup**

I cannot speak for all editors, but Sublime Text uses `//-` when you use `cmd+/`, for example.

If you are happy to allow this change, I will gladly submit a PR for it

**Comment by aeschli** [comment]
I can make the change, thanks for the suggestion, I think you are correct.

**Comment by JamesHenry** [comment]
Great, thanks!
