### ISSUE TITLE
Fenced code blocks (only backticks) in tooltip render asterisk symbols

### ISSUE THREAD

**Issue by kleinfreund** [Microsoft/vscode#56025]
Issue Type: <b>Bug</b>

Using fenced code blocks in a JavaScript docstring will render the leading asterisk characters of the docstring **if the code block is formatted using backticks**. This does not happen with tilde code blocks.

**Example using backticks**:

```js
/**
 * ```js
 * function test1() {}
 * ```
 */
function test1() {}
```

![screenshot from 2018-08-08 20-23-15](https://user-images.githubusercontent.com/5774638/43856557-233bae06-9b49-11e8-8119-1e3c175e0aad.png)

**Example using tildes**:

```js
/**
 * ~~~js
 * function test2() {}
 * ~~~
 */
function test2() {}
```

![screenshot from 2018-08-08 20-24-27](https://user-images.githubusercontent.com/5774638/43856570-290724b4-9b49-11e8-9335-dc9d8857e57a.png)

**Expected Behavior**:

Both examples should render like example 2.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:40:20.190Z)
OS version: Linux x64 4.15.0-30-generic

**Comment by mjbvz** [comment]
Thanks. This is already tracked by https://github.com/Microsoft/TypeScript/issues/23517 upstream
