### ISSUE TITLE
Better indicator for long extension installations

### ISSUE THREAD

**Issue by miguelsolorio** [microsoft/vscode#56023]
If you are either on a slow connection or are installing a large extension, it's hard to identify if the installation is still proceeding or if it's stuck. There is the viewlet progress indicator, but that's not easy to identify with a specific extension as it's over the entire viewlet container.

### Current
<img src="https://user-images.githubusercontent.com/35271042/43853319-a93dd858-9af4-11e8-8b25-3c4a87e585e7.png" width="70%">

### Suggestion
Animate a `...` on the `Installing` text so that the progress is implicit.
![gif](https://user-images.githubusercontent.com/35271042/43855395-4c6677d8-9afa-11e8-91d6-466b83cd0d7a.gif)

**Comment by beastdestroyer** [comment]
@misolori Hi, not sure if I should be commenting here, but what about an actual mini progress bar alongside that? Like a thin line that shows at the bottom the progress, similar to an app installer for example. It would also be a pretty cool easy to see visual indicator for any UI size too.

ALso the little blue indicator that appears under "Extensions" is near pointless in this case wouldn't it?

**Comment by beastdestroyer** [comment]
Ah right, I didn't know that, coolio!
