### ISSUE TITLE
Support keybindings for sending custom sequences to the terminal 

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#56024]
Example send ctrl+c, up, enter to re-run a command.

**Comment by njkevlani** [comment]
I'd like to work on this.

Need some more information.

1. How user will add new keybindings for "custom sequences to the terminal". 
2. Currently,(as of my knowledge) we can assign keybindings to predefined `Actions`. How do we emulate terminal key presses with actions?

**Comment by Tyriar** [comment]
@njkevlani cool! Keybindings/commands can have arguments pass to them, we would want to leverage this https://code.visualstudio.com/docs/getstarted/keybindings#_command-arguments, basically we want expose a command similar to `MoveToLineEndTerminalAction` and its super class `BaseSendTextTerminalAction` (inside terminalActions.ts)

**Comment by njkevlani** [comment]
Didn't know this till now, good to know :) I'll look into it, put my suggestion/questions and will open PR soon!

**Comment by njkevlani** [comment]
Hey @Tyriar, I've coded a class `SendSequenceTerminalCommand` that extends `Command`. It takes user defined arguments from `keybindings.json`. I have some questions.

1. What custom sequences are we going to support? Like `ctrl+c up enter`, `ctrl+r ls enter` (To `ls` last `ls`ed directory). What I mean to say is that can you provide more cases like `ctrl+c up enter`?

2. Currently, I'm using `terminalInstance.sendText` multiple time to send a sequence. That is for example `ctrl+c up enter` goes as 
   1. `ctrl+c` using `sendText(String.fromCharCode('C'.charCodeAt(0)) - 64, false)`
    2. `up + enter` using `sendText(String.fromCharCode(KeyCode.UpArrow), true)`
 
Is there any better way?

**Comment by njkevlani** [comment]
Reminder @Tyriar

**Comment by Tyriar** [comment]
@njkevlani I would expect hex to be accepted, for example `\x1b` is the escape character, as well as the slash key codes like `\n`, `\a`, `\t`, etc. (see https://github.com/xtermjs/xterm.js/blob/0e45909c7e79c83452493d2cd46d99c0a0bb585f/src/common/data/EscapeSequences.ts#L31), the args can contain a string with a bunch of data in it which is sent. So you could for example send "ctrl+c, up, enter", or "hello world" just by tweaking the args on the keybinding.

**Comment by Tyriar** [comment]
Verifier: Please test on Linux or macOS that you can send text and sequences using a keybinding like this:

```
{ "key": "ctrl+shift+a",           "command": "workbench.action.terminal.sendSequence", "args": { "text": "abc" } },
```

**Comment by njkevlani** [comment]
Working on linux. Verified
