### ISSUE TITLE
VS Code auto-complete can overwrite if typing too fast

### ISSUE THREAD

**Issue by robertorfischer** [Microsoft/vscode#56026]
Issue Type: <b>Bug</b>

VS Code suggestion box can be slower than typing and it can cause new typed code after the suggestion to be overwritten when it finds a separator token, like (.

This is happening very frequently when I type a call to "console.log", because the "log" statement is very short. What I observe is this:

1. Start typing "console".
2. When the auto-complete suggestions pop up, "console" is in there
3. I ignore the suggestions and just keep typing the dot character folllowed by "log"
4. Many times, the suggestion box is slow and doesn't catch up, so it still shows "console", even though I'm already past the dot and typing "log".
5. When I type the open parenthesis character, it accepts the first suggestion on the box and overwrites everything I've written after it, including the dot.

This is what the text content looks like:
`console`  // keep typing
`console.log`  // keep typing
`console(`  // after hitting the ( key, it overwrites everything after the suggestion

This started happening a few weeks ago.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:40:20.190Z)
OS version: Linux x64 4.9.0-7-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|62.90GB (34.27GB free)|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
bazel-code|Dev|0.1.9
tslint|eg2|1.0.34
hg|mrc|1.2.3
python|ms-|2018.7.1
java|red|0.29.0
vscode-java-debug|vsc|0.11.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.7.1
vscode-maven|vsc|0.10.0
clang-format|xav|1.6.2

</details>

**Comment by ramya-rao-a** [comment]
Can you try setting `editor.acceptSuggestionOnCommitCharacter` to false and see if you still have this issue?

**Comment by robertorfischer** [comment]
Setting `"editor.acceptSuggestionOnCommitCharacter": false` makes the suggestion no longer overwrite what I wrote.

There's a noticeable delay after typing the dot until the suggestions for console's members appear. I had enough time to capture the following screenshot. Note how "log" has already been typed, but "console" is still being suggested. Eventually, the suggestion box catches up with text, but the fact that it's not being reset after I type a separator like the dot seems to be what causes this.

![console log](https://user-images.githubusercontent.com/251012/44125823-88a2b916-9fe9-11e8-9a39-7d4bf7a371d8.png)

(BTW, I actually like this setting turned off)

**Comment by andy-viv** [comment]
This only started occurring in the last several weeks so it was introduced in recent release.

**Comment by geordiemhall** [comment]
+1 Also running into this pretty frequently

**Comment by franky47** [comment]
Do you guys have the `vscode-styled-components` extension installed and active ? I've found it to be the source of many intellisense/autocomplete issues recently. Everything goes haywire with it, and normal without.

**Comment by robertorfischer** [comment]
I don't have it. Since I turned off that setting, I haven't had this issue, so I haven't bothered thinking much about it anyway.

**Comment by mjbvz** [comment]
@robertorfischer Did you have any typescript plugins installed in your project? Also, can you still reproduce this issue in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by robertorfischer** [comment]
@mjbvz I'm not going to be able to try out the insiders build, sorry. Re-enabling `editor.acceptSuggestionOnCommitCharacter` makes the issue come back. After disabling all installing extensions and reloading, issue persists.
I'm now on version 1.27.1, commit starting with 5944e81.

**Comment by mjbvz** [comment]
Let me know if you still setting this on the current VS Code insiders 9e62a05bc7c5dbb74d165e06f7c3a5f3c7549096 with extensions (and TS plugins) disabled. We've made several fixes around intellisense suggestions and I can't repo this issue anymore
