### ISSUE TITLE
Change the default for "openDebug" to open on session start

### ISSUE THREAD

**Issue by misolori** [Microsoft/vscode#56032]
For new users, it can be confusing/difficult when you start a debug session and the debug viewlet does not open automatically every time (by default it's set to `openOnFirstSessionStart` so it only opens on your first session). If you're not yet familiar with the UI, you don't know what keywords to look for if you want to change this. 

We should change the default of `debug.openDebug` to be `openOnSessionStart` so it's easier for new users to get started with debugging.

**Comment by isidorn** [comment]
Sure, I have pushed the change of default so we get some feedback from insiders.
This is also something to keep in mind to mention in the release notes.

**Comment by misolori** [comment]
@isidorn 🙌
