### ISSUE TITLE
Improve messaging when running a task with no workspace

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#56034]
When running the `Run Task` command from the menu, you are prompted with the following notification:

![image](https://user-images.githubusercontent.com/35271042/43861850-eef2f65e-9b0c-11e8-8e7a-b61a31cc386c.png)

For new users, they might not have a concept of a "workspace" or what a "task" is in the context of VS Code. We should add a link that points to our [Tasks docs](https://code.visualstudio.com/docs/editor/tasks) for more information. 

Additionally, our docs should have an explanation of how tasks work with workspaces.

**Comment by alexr00** [comment]
Fix 6 months ago by https://github.com/microsoft/vscode/pull/71476

**Comment by misolori** [comment]
Verified this works now, would've expected an inline text link instead but this works:

<img width="466" alt="image" src="https://user-images.githubusercontent.com/35271042/67811397-e440dc00-fa59-11e9-8234-ad75f2870cb2.png">
