### ISSUE TITLE
"Cannot read property 'toString' of null' when trying to save

### ISSUE THREAD

**Issue by JacksonKearl** [Microsoft/vscode#56030]
Issue Type: <b>Bug</b>

Steps:
- open workspace
- create a new file, add text (do not save)
- open either **new** settings editor or keybindings editor
- `ctrl+s` to save
- "Cannot read property 'toString' of null"

VS Code version: Code - Insiders 1.26.0-insider (a8033aaf216d684d775e058489d25186702d28e3, 2018-08-07T23:17:55.610Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (5.50GB free)|
|Process Argv|C:\Users\t-jakea\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.0.3
vscode-svgviewer|css|1.4.4
gitlens|eam|8.5.4
tslint|eg2|1.0.34
debugger-for-chrome|msj|4.8.2
subtle-brackets|raf|2.1.1
vscode-multiclip|sle|0.1.4
code-spell-checker|str|1.6.10
sublime-commands|Zar|0.1.0

(1 theme extensions excluded)

</details>

**Comment by ramya-rao-a** [comment]
after opening the settings editor, do you go back to the new file to save?

**Comment by JacksonKearl** [comment]
No, this happens if you trigger save in the settings or keybindings editor.

**Comment by ramya-rao-a** [comment]
Happens in stable as well.

**Comment by JacksonKearl** [comment]
I am no longer able to repro this, a fix may have come in from somewhere else.

**Comment by RMacfarlane** [comment]
I'm still able to repro this with the steps above, but only with the keybindings editor open. 

Code - Insiders 1.27.0-insider (47d0584301d16d4efd6618f6f33ef14099c92561, 2018-08-29T05:12:15.247Z)

**Comment by sandy081** [comment]
@isidorn Error is thrown at the following location 

https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/fileCommands.ts#L187

Please take a look
