### ISSUE TITLE
Allow `Delete` keyboard shortcut to remove file from explorer

### ISSUE THREAD

**Issue by SamVerschueren** [Microsoft/vscode#5603]
- VSCode Version: 1.0.0
- OS Version: 10.11.3

It's not possible to bind a key to the `Delete File` action from the explorer. I think it would be a nice addition.

// @bpasero yes I will look into doing a PR this evening ;)

**Comment by bpasero** [comment]
@SamVerschueren it should be bound to Cmd+Backspace though? See https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/views/explorerViewer.ts#L387

Making all explorer actions keybinding friendly is on the backlog but honestly not a straight forward thing to do :-/

**Comment by SamVerschueren** [comment]
Oh you're absolutely right. That makes total sense off course because it's the same as in the finder window... Maybe it should be added to the popup menu when left-clicking a file?

<img width="184" alt="screen shot 2016-04-21 at 19 00 14" src="https://cloud.githubusercontent.com/assets/1913805/14717778/51e8cfb8-07f3-11e6-94b2-a6b72573e9ff.png">

Would've saved me some mouse time in the past :)
