### ISSUE TITLE
Include Extensions in the Preferences menu

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#56042]
As requested by @chrisdias and discussed with @kieferrm:

Since extensions are a way of customizing VS Code, it needs a place in the preferences menu,.This issue tracks the below
- [x] Include `Extensions` in the Preferences Menu, right below `Settings`. Choosing this will open the Extensions view
- [x] Rename `Keymap Extensions` to `Keymaps` in the Preferences Menu
- [x] Rename `Manage Extensions` to just `Extensions` in the gear menu in the activity bar
- [x] Update the default Extensions view when no extensions are installed to show Popular + Recommended extensions instead of showing just the popular extensions. But only if there are recommended extensions to show.

**Comment by isidorn** [comment]
Adding verified. However I still see:
"Keymap extensions" not "Keymaps". Should I create a follow up isse for this? @ramya-rao-a

**Comment by ramya-rao-a** [comment]
@isidorn I've pushed the label update. Can you verify it in tomorrow's build and leave a note here?

**Comment by isidorn** [comment]
@ramya-rao-a the label is good now, thanks
