### ISSUE TITLE
Unexpected resizing of split windows

### ISSUE THREAD

**Issue by sidnt** [Microsoft/vscode#56044]
Issue Type: <b>Bug</b>

When the file explorer is closed, pressing cmd+shift+e slides it to the right. Clicking on the explorer icon, slides it back to the left. No big deal. But when this hide explorer action is invoked via a shortcut, like cmd+shift+a in my case, if my editor window is split into 2 files open side by side, this shortcut invocation unexpectedly resizes my splitting. Particularly, it collapses the left frame to a smaller size and expands the right frame.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 16.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.31GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
scala-lsp|dra|0.2.3
vscode-sbt-scala|lig|0.2.2
Lisp|mat|0.1.8
org-mode|too|0.5.0

</details>

**Comment by bpasero** [comment]
@sidnt can you record a video and add it here?

**Comment by sidnt** [comment]
![out](https://user-images.githubusercontent.com/11618157/43880437-0d05a222-9bc6-11e8-902b-1afafa0446a9.gif)

**Comment by bpasero** [comment]
@sidnt can you share your keybindings configuration file

**Comment by sidnt** [comment]
// Place your key bindings in this file to overwrite the defaults
[
    {
        "key": "cmd+,",
        "command": "workbench.action.terminal.focus"
    },
    {
        "key": "shift+cmd+a",
        "command": "workbench.action.maximizeEditor"
    }
]

**Comment by bpasero** [comment]
@sidnt `shift+cmd+a` is configured to maximize the current editor, so what you see is expected. there is another command to hide the side bar that you should use instead: `workbench.action.toggleSidebarVisibility`
