### ISSUE TITLE
When I use tig in inner command line, it is messy code.

### ISSUE THREAD

**Issue by rx123rx** [Microsoft/vscode#56049]
Issue Type: <b>Bug</b>

Just as i said above.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 3|
|Memory (System)|16.00GB (4.11GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|1.2.6
wechat-snippet|Cha|0.3.5
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
regex|chr|0.2.0
vscode-wxml|cod|0.1.9
bracket-pair-colorizer|Coe|1.0.59
dart-code|Dar|2.17.1
flutter|Dar|2.17.1
githistory|don|0.4.2
vscode-babel-coloring|dza|0.0.4
EditorConfig|Edi|0.12.4
vscode-npm-script|eg2|0.3.5
file-icons|fil|1.0.12
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.4
vue-snippets|hol|0.1.8
backbone-js-snippets|ioa|0.0.1
vscode-filesize|mkx|2.1.1
prettify-json|moh|0.0.3
vscode-language-pack-zh-hans|MS-|1.25.3
python|ms-|2018.7.1
vsliveshare|ms-|0.3.514
editorconfiggenerator|nep|0.2.1
vetur|oct|0.12.6
polacode|pnp|0.2.2
sass-indented|rob|1.4.9
gitblame|wad|2.4.4

(1 theme extensions excluded)

</details>

**Comment by ramya-rao-a** [comment]
> When I use tig in inner command line, it is messy code.

By "tig", do you mean "git"?
By "inner command line", do you mean the integrated terminal?

We need more details, please share a screenshot which can be very helpful.
Also read our wiki on [Submitting Bugs](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions)
