### ISSUE TITLE
Settings editor: tree loses entries

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#56043]
Issue Type: <b>Bug</b>

Pls see attached screencast.

1. Use @modified in the search box of the settings editor
2. Append ' git' to the search box
3. Click on Extension>GitLens in the tree

-> all nodes but GitLens are lost

![6gatg4jzl1](https://user-images.githubusercontent.com/4674940/43870836-77cc8618-9b2e-11e8-9009-70060aea8fda.gif)

VS Code version: Code - Insiders 1.26.0-insider (c827480be25bd63065e7ee2e106c24a707c08004, 2018-08-08T18:46:20.998Z)
OS version: Darwin x64 16.7.0

**Comment by roblourens** [comment]
Seems fixed now
