### ISSUE TITLE
Multi selection for breakpoints

### ISSUE THREAD

**Issue by luiszun** [Microsoft/vscode#56054]
I think this should've been reported before, but I couldn't find it. Sorry if it's a duplicate.

Other debuggers have the ability of selecting all (Code can select all) or a subset (Code can't select a subset) of breakpoints, and click a checkbox to have that group enabled/disabled.

Right now I have a bunch of breakpoints and it'd be handy to be able to toggle them all on and off easily.

**Comment by ris58h** [comment]
@luiszun You can actually enable/disable or activate/deactivate (it doesn't change enable/disable states) all breakpoints at once.
Use context menu (right click) items `Enable All Breakpoints` and `Disable All Breakpoints` to enable/disable them. Use `Deactivate Breakpoints` and `Activate Breakpoints` actions in the Breakpoints View header to deactivate/activate them.
If you problem is only about subset of breakpoints, there is no way to do that at this moment.

**Comment by luiszun** [comment]
Ah thanks @ris58h, didn't try to right click those. I still think it should be doable with a click on a selected set of breakpoints, like other debuggers do :)
