### ISSUE TITLE
New VSCode windows take several seconds to become "ready"

### ISSUE THREAD

**Issue by macintacos** [Microsoft/vscode#56050]
VSCode takes several seconds to load everything; is this expected behavior? I'm trying to narrow it down to maybe an extension or two that is using resources poorly, so was hoping that this could help identify the issue. Any insight would be appreciated.

Running `code --prof-startup` produced the following:

- VSCode Version: <code>Code 1.25.1 **[Unsupported]** (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)</code>
- OS Version: <code>Darwin x64 17.7.0</code>
- CPUs: <code>Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)</code>
- Memory (System): <code>16.00GB (1.54GB free)</code>
- Memory (Process): <code>319.64MB working set (0.00MB peak, 202.52MB private, 122.86MB shared)</code>
- Load (avg): <code>2, 2, 2</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|95|
|main|app.isReady => window.loadUrl()|364|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|364|
|renderer|require(workbench.main.js)|1206|
|renderer|create extension host => extensions onReady()|869|
|renderer|restore viewlet|0|
|renderer|restore editor view state|306|
|renderer|overall workbench load|706|
|main + renderer|start => extensions ready|3013|
|main + renderer|start => workbench ready|2760|

---

:warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`47d8-exthost.cpuprofile.txt`
-`47d8-main.cpuprofile.txt`
-`47d8-renderer.cpuprofile.txt`

[47d8-exthost.cpuprofile.txt](https://github.com/Microsoft/vscode/files/2272609/47d8-exthost.cpuprofile.txt)
[47d8-main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/2272610/47d8-main.cpuprofile.txt)
[47d8-renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/2272611/47d8-renderer.cpuprofile.txt)

**Comment by jrieken** [comment]
> VSCode Version: Code 1.25.1 [Unsupported] (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)

Your version of VS Code is unsupported, likely because an extension has patched the main sources. Please re-install and try again

**Comment by macintacos** [comment]
@jrieken I have a package that allows me to modify the CSS; is that the problem? It was slow before I ever downloaded that extension, and I just used that extension to hide some statusbar items...is there no insight to glean from the profile I've attached?

**Comment by jrieken** [comment]
Well, `[Unsupported]` means unsupported. Looking at those numbers, what stands out is the time it takes to load the sources (`require(workbench.main.js) | 1206`) which should take around 500ms.
