### ISSUE TITLE
Doesn't show output properly 

### ISSUE THREAD

**Issue by aalwattar1** [Microsoft/vscode#56056]
Hey there,
vscode
For some reason I have a problem by running couple code written in Python, doesn't show me the output in the terminal 
I will send you one of the codes that doesn't run (however I tried same code in another text editor it works fine)

def animal_crack(text):
    wordlist=text.lower().split()
    first=wordlist[0]
    second=wordlist[1]
    if first[0] == second[0]:
        return True
    else: return False

#check

animal_crack('camberjack light')

**Comment by luiszun** [comment]
Your script doesn't have any output. I'm surprised that other editors output something. Can you show other editors to clarify what was expected?

**Comment by aalwattar1** [comment]
![screenshot 2018-08-09 03 02 35](https://user-images.githubusercontent.com/40479353/43886240-bd250b20-9b80-11e8-9d3c-47fe15403816.png)

I tried it on Jupyter, and Atom.

Also this is another code, same problem doesn't give any output on VScode
![test](https://user-images.githubusercontent.com/40479353/43886413-410bcbfe-9b81-11e8-8166-d148125c02fa.JPG)
