### ISSUE TITLE
Changing color theme no longer updates minimap live

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#56055]
Steps to Reproduce:

1. jump over themes
2. notice how the minimap does not change until you pick a theme

![before](https://user-images.githubusercontent.com/900690/43879820-0d38e382-9ba6-11e8-91cb-7ace78e906df.gif)

**Comment by alexandrudima** [comment]
I cannot reproduce this in Insiders

**Comment by bpasero** [comment]
I should have mentioned: This was on Windows 10, running out of sources.

**Comment by alexandrudima** [comment]
I cannot reproduce running out of sources from the `release/1.26` branch, so this might be a very recent regression.

**Comment by aeschli** [comment]
I'm also not able to reproduce when running out of sources (master).

**Comment by bpasero** [comment]
I am not seeing this anymore, not sure what happened.
