### ISSUE TITLE
Broken explorer and strange scroll behaviour

### ISSUE THREAD

**Issue by Kelin2025** [Microsoft/vscode#56051]
- VSCode Version: 1.25.1
- OS Version: MacOS 10.13.4

Steps to Reproduce:

__Random__

Does this issue occur when all extensions are disabled?: Yes

Sometimes explorer gets crazy and all folder structure becomes a random mess of files and folders that "float" on scroll

Here files from "chain" folder are inside "auth" folder 
[Click to see](https://user-images.githubusercontent.com/4208480/43875952-833f568e-9b9b-11e8-8b44-5efe48c72914.png)

Here "chain" folder starts at the bottom of explorer and ends at the top:
[Click to see](https://user-images.githubusercontent.com/4208480/43875961-8aff31fa-9b9b-11e8-91fa-8c2a4b1bcd77.png)

Sometimes click on "Refresh" helps, sometimes only full restart helps. It happens randomly (without extensions too)

**Comment by isidorn** [comment]
Dup of a tree issue @joaomoreno is aware of
