### ISSUE TITLE
Ubuntu dock: clicking on VSCode icon while it is starting opens a second instance

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#56067]
I notice this ever since I selfhost on Linux (Ubuntu 18): when I start the app and it takes a while and I click the icon again, I see a second window opening. 

Am I the only one seeing this?

**Comment by Tyriar** [comment]
Simpler repro: `code && code`

**Comment by Tyriar** [comment]
Also repro's in Windows by opening code twice in quick succession, I'm not so sure this is even a bug?
