### ISSUE TITLE
Still Slow

### ISSUE THREAD

**Issue by zhaotongxue** [Microsoft/vscode#56065]
- Extension Name: include-autocomplete
- Extension Version: 0.0.4
- OS Version: Windows_NT x64 10.0.15063
- VSCode version: 1.25.1

 We have written the needed data into your clipboard. Please paste:
![image](https://user-images.githubusercontent.com/6638644/43887273-da5d47d2-9bf0-11e8-8a70-56581c17e15f.png)
The second time. It's still very slow.

**Comment by ramya-rao-a** [comment]
I am assuming you mean to say that the `include-autocomplete` extension is slow. Please log an issue in the repo of that extension.
