### ISSUE TITLE
Diff editor: horizontal scrollbar height is smaller

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#56062]
I am not sure if this was an explicit decision, but the height of the horizontal scrollbar in the diff editor is no longer the same height as it was in stable and also not the same as a normal editor. I feel it much harder now to use the scrollbar in the diff editor.

**Comment by alexandrudima** [comment]
@bpasero it always appears to be 10px for me.

Stable:
![image](https://user-images.githubusercontent.com/5047891/43893485-7172457c-9bcf-11e8-837a-f3dd07805890.png)

Insiders:
![image](https://user-images.githubusercontent.com/5047891/43893518-89eae9b0-9bcf-11e8-8325-89c01671428a.png)

**Comment by bpasero** [comment]
This looks like it only reproduces when tabs are disabled. I can see that toggling between tabs and no tabs pushes down the editor.

@alexandrudima can you reproduce that?

**Comment by alexandrudima** [comment]
The sliders are still 10px in height. 
![image](https://user-images.githubusercontent.com/5047891/43894439-52798466-9bd2-11e8-8ade-b4b921926083.png)

This looks like a layouting bug, it appears the entire editor is pushed under the status bar:

![image](https://user-images.githubusercontent.com/5047891/43894475-68b0cb36-9bd2-11e8-9f0e-f0951f91af48.png)

**Comment by alexandrudima** [comment]
@bpasero Should this be a candidate ?

**Comment by bpasero** [comment]
This is a regression in 1.26, but I cannot correlate this back to a specific CSS change. 

I cannot really explain why, but only if the diff editor is opened, the editor actions area on the right hand side grows to `39px` (possibly because of the "..." dropdown). Since the editor title area has an assumed (hardcoded) height of `35px`, this makes the editor flow out of the editor area because the title area pushes.

I pushed a fix to set the height of the div that contains the editor actions to `35px`. We already did that when tabs are enabled, so it seems OK to use this also when tabs are disabled.

**Comment by bpasero** [comment]
@jrieken yeah possibly, but I am seeing the action bar area having a size of > 35px also in stable, so I think this has been already around longer. Maybe something changed that the action area manages to push down the title bar, when it did not in stable.

**Comment by bpasero** [comment]
@alexandrudima could you verify this please?
