### ISSUE TITLE
typescript validate prompt is "Duplicate function implementation."

### ISSUE THREAD

**Issue by blusoul** [Microsoft/vscode#56068]
- VSCode Version: 1.26.0-insider/1.25.1
- OS Version: windows 10

Steps to Reproduce:

1. I compiled the .ts file, then generated a matching .js file.
2. when I open those two files, the code has a wrong tips "Duplicate function implementation."
3. The insider version has no extension and the setttings has no configuration

![image](https://user-images.githubusercontent.com/8167270/43890443-5bff9a62-9bf9-11e8-9205-40ac90d499d5.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by ramya-rao-a** [comment]
Adding a tsconfig file to that folder fixes the issue. Run `tsc -init`.
@mjbvz might know more about this.

**Comment by blusoul** [comment]
@ramya-rao-a  Thank you , the issue is fixed .

**Comment by mjbvz** [comment]
Yes you need a basic tsconfig in this case. The tsconfig file tells VS Code that you are working in a typescript project. Otherwise it puts all js and ts in a single project, which means that that two global variables `getName` will be in conflict
