### ISSUE TITLE
Integrated Terminal Loading .profile But Not .bashrc or .bash_profile When Not Launched From Command Line

### ISSUE THREAD

**Issue by Undistraction** [Microsoft/vscode#56061]
- VSCode Version: Version 1.25.1 (1.25.1)
- OS Version: 10.13.6 (17G65)

When I open VSCode from the command line, using `code`, and open an integrated Terminal, my `.bashrc` is loaded correctly. However when I open VSCode using the application Icon, or an app launcher, any instances of the integrated Terminal load only `.profile`.

Steps to Reproduce:

1. Open VSCode 
2. Open New Integrated Terminal

Does this issue occur when all extensions are disabled?: No, because it isn't a problem when VSCode is launched from the command line using `code`, regardless of whether extensions are disabled.

**Comment by Tyriar** [comment]
Can you open devtools (Help > Toggle Developer Tools) and run process.env in the console to see if that's the environment you expect?

**Comment by Undistraction** [comment]
It's working fine now after another restart. Thanks for your help.

**Comment by Undistraction** [comment]
As of Version 1.26.1 (1.26.1) this is now true no matter how VSCode is launched.  

Running `process.env` in devtools as suggested by @Tyriar shows that the expected env isn't loaded.

The only way to lauch vscode and have the correct env loaded is to use `open` for a filetype associated with VSCode. In that instance, `.bashrc` is correctly loaded, but in all other instances `.profile` is loaded.

**Comment by Tyriar** [comment]
Try setting this in your settings.json:

```
"terminal.integrated.shellArgs.osx": []
```

By default we launch shells as login shells which run the profile not the rc scripts.
