### ISSUE TITLE
ctrl   + 鼠标左键, 没法跳转

### ISSUE THREAD

**Issue by z1125** [Microsoft/vscode#56060]
Issue Type: <b>Feature Request</b>

ctrl   + 鼠标左键, 没法跳转

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

**Comment by linonetwo** [comment]
Please use English and be more specific.

**Comment by ramya-rao-a** [comment]
There isnt much details here to work with. Please provide actual steps, expected result and actual result.

**Comment by sandy081** [comment]
Please provide steps and reopen

**Comment by xuhongv** [comment]
@z1125 请问您解决了么  我这边也是跳转不了
