### ISSUE TITLE
cannot add more than one task and documentation does not help at all 

### ISSUE THREAD

**Issue by NikosEfthias** [Microsoft/vscode#5606]
- VSCode Version:![](http://i.imgur.com/0pD5Bbv.png)
- OS Version:ubuntu 15.10
i have following task file ![](http://i.imgur.com/OVbB3nd.png) i tried to make an array containing objects or just adding more objects to the file both wont work .
In documentation there are examples whic are already in example tasks.json file with a normal human being with an average iq can read from the example json file and understand everything from comments . Why documentation does not tell anything about how to do actually something is this because this is opensource and microsoft wants just money of people and microsoft created this editor in order to look prettier like saying 'look we suck your money but we also create open source software' ?

**Comment by dbaeumer** [comment]
Tasks are designed as light weight wrappers around an existing task runner like grunt or gulp. VSCode's task system does is starting such a gulp or grunt task and parses its output to produce errors. The limitation with this right now is that there can only be one command executed at any given time and that tasks must be used with the same command. So for example
```json
{
	// See http://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "0.1.0",
	"command": "gulp",
	"isShellCommand": true,
	"args": [
		"--no-color"
	],
	"tasks": [
		{
			"taskName": "build",
			"args": [],
			"isBuildCommand": true,
			"isWatching": false,
			"problemMatcher": [
				"$lessCompile",
				"$tsc",
				"$jshint"
			]
		}
	]
}
```
uses gulp ti run tasks. When the build task is executed (e.g. gulp build) its output is checked for less, tsc and jshint errors. The output of other gulp tasks like for example gulp deploy would not be checked for errors.

@NikosEfthias what exactly do you want to achieve?

**Comment by NikosEfthias** [comment]
how can i use multiple tasks not at the same time for example in some part of my project i need to run that particular js file not the entire file so as in the example i created a task for this and on a less file i wanna compile it so i wanna create another task definition to do so but i can only have one task per project with this design @dbaeumer

**Comment by dbaeumer** [comment]
We have a feature request #981 to be able to define more than one command and to run more than one task. Any objection to close as dup?

**Comment by NikosEfthias** [comment]
@dbaeumer where can i follow new features ?

**Comment by dbaeumer** [comment]
For every iteration we run we create a plan that describes what we want to achieve during that iteration. The one for April is here: https://github.com/Microsoft/vscode/issues/4888. 

We already started discussions on how to best solve the multi command / multi tasks problem but haven't landed on a final solution yet. One idea was to provide a better terminal integration because that gives more freedom.

**Comment by NikosEfthias** [comment]
thank you for answer @dbaeumer

**Comment by NikosEfthias** [comment]
i found a way to add multiple tasks 
under linux i just use /usr/bin/env as commant then configuring tasks:[] section but it could be just cool if the tasks.json file accepted and array rather than a single object
