### ISSUE TITLE
Typescript/HTML Autocomplete doesn't work for Attributes/Properties with an underscore

### ISSUE THREAD

**Issue by olivermuc** [Microsoft/vscode#56077]
- VSCode Version: **Version 1.25.1 (1.25.1)**
- OS Version: **Mac 10.13.5**

Steps to Reproduce:

**Typescript:** 

1. Add a key with an "_", eg. `data._custom_field` to any data structure
2. Then reference that data structure in the html template: `{{ data._cus... }}`

It will show all other data.* fields, but none of the ones with an underscore, no matter where the underscore is placed.

Even if the underscore might be seen as a declarator for a 'private field', this should at least be configurable.

Thanks,
Oliver

**Comment by ramya-rao-a** [comment]
- In what file type are you seeing this issue?
- Can you share some sample code where we can try this?

**Comment by olivermuc** [comment]
I gave an example above, the context is Typescript.

Let‘s say you have a data structure defined:
`let data = { a:1, b:2, _c:3 };` with the corresponding interface def.

In (or within) the TS file you can easily reference `data._c` and the autocompletion works fine.
It doesn‘t work with intellisense when working in the html template file refereced by the TS file (or component therein).
It just doesn‘t show any attributes with an underscore.
Removing the underscore from the interface declaration will immediately show the attribute.

**Comment by olivermuc** [comment]
It looks like this belongs here: https://github.com/angular/vscode-ng-language-service/issues/258

**Comment by olivermuc** [comment]
hey @mjbvz, let me know if you need any more input on this.
'glad this is being looked at - as it's really taking away a key feature and reason our team switched to vs code.

**Comment by mjbvz** [comment]
Yes, we don't provide built-in support for angular templates. That all comes from the angular extension. Please open the issue against them
