### ISSUE TITLE
Settings GUI Polish

### ISSUE THREAD

**Issue by beastdestroyer** [Microsoft/vscode#56074]
Issue Type: Polish

In terms of maybe polishing the GUI a bit:
- Make font sizes more consistent:
  - Looking at developer tools, I can see titles such as "Commonly Used" at 24px, then subtitles such as "Cursor" at 20px, but the normal text is only 13px, this could probably be at font size 16px.
  - This would also let people distinguish between setting name and setting description better, rather than having to rely on the slight change on font-weight and the structure.
  - Small text such as "Modified" can remain as is, since it isn't really part of the title, it's just a mini info textbox really.
  - Description text could probably remain as is, maybe increase it to 14px since brackets sometimes looks a bit squished
- Layout
  - First of all, the way settings are separated are by large padding spaces. Whilst personally, I would prefer it how Atom does it (rendering certain settings based on the active tab), I can't really argue with that, so here are my propositions:
    - How about just a ```<hr>``` to denote changes in categories, say from Text Editor to Workbench.
    - Titles should definitely have underlines
    - Instead of constant ```padding-top``` or bottom, just halve the current figure, and split that between top and bottom. It makes it look much nicer, especially when a setting is elected and that box comes about, it looks really off.
- Some other stuff
  - That box that appears when selecting something in the GUI, perhaps make it themable, and make it respond to whether its a dark or light theme. The box could just be the opposite, so a dark theme would have a light box etc. If unfocused, just make it change again
  - Allow showing of the equivalent ```json``` setting. Whilst present in some areas for explanation, you might as well make it show throughout. Be consistent, and can still help people too (though from what I've heard, most people will stick to JSON)
- From what I've seen, when the GUI edits the ```settings.json```, it just tacks it onto the end. I've seen this when I edit the file. I use both the GUI and JSON, you can guess for which reason. Anyways, since the GUI organises it, could it not organise the settings.json? I have my one split into different blocks relating to what section it belongs to.
- If you click a dropdown (maybe textbox too?) of an uncollapsed setting, it should collapse too in my opinion. It would be helpful to newer people (since that's what I've heard this GUI is for, right?)

Feel free to disagree, add your ideas whatever. These are just suggestions for polish. Thanks!

**Comment by roblourens** [comment]
Thanks for the feedback! I am in the process of getting rid of the row selection and expand/collapse behavior right now which will definitely change some things. Will keep this in mind as I continue working on the UI. FYI @misolori

**Comment by beastdestroyer** [comment]
@roblourens One more thing, if the viewport of the editor is small enough and the GUI is opened, the ToC disappears completely, and there seems to be no dropdown for it. Was this intended or just wasn't implemented?

**Comment by roblourens** [comment]
That's by design. There's not enough room for it and users can still scroll or search. Maybe collapsing it into a dropdown would be a good thing to do in the future

**Comment by beastdestroyer** [comment]
Would it be possible, since it's a GUI and all, to have a sidebar that is toggleable. It'd be hidden by default of course, but perhaps a button that you can click which slides it out over the main settings, then close it? It might defeat the purpose of scrolling and all, but as the ToC essentially is the way to go around navigation, I still feel it could provide benefits. As reference, atom has a popup arrow to the right of the screen which opens outline view, perhaps something similar but for ToC?

**Comment by roblourens** [comment]
I'm not planning on any other UX changes like toggling the table of contents. It does get hidden when the settings editor is narrow, but it's useful and I don't want to complicate things by making it toggleable.
