### ISSUE TITLE
HTML Wrap selection with tags and adding class adds it to both tags

### ISSUE THREAD

**Issue by mizujin** [Microsoft/vscode#5607]
- VSCode Version: 0.10.11
- OS Version: Windows 8

Steps to Reproduce:

1. In an HTML document, make a text selection to wrap and using Alt + W to wrap them with tags
2. Define the tags and immediately continue with a class statement.
3. class="" is added to both starting/ending tags.

**Comment by aeschli** [comment]
This issue was moved to Microsoft/vscode-htmltagwrap#3
