### ISSUE TITLE
[json] `json.format.enable = false` doesn't work

### ISSUE THREAD

**Issue by chrisdothtml** [microsoft/vscode#56079]
If there were a way to at least change it to only validate upon save, I wouldn't have such a problem with it, but the real-time validation as I type is very distracting. It seems that out-of-the-box linting in general is inconsistent across languages with regards to how they're configured

### Steps to Reproduce

1. set `"json.format.enable": false` in settings
2. json files are still validated

### Does this issue occur when all extensions are disabled?

Yes

### Versions

v1.26.0-insider
macOS High Sierra v10.13.6

**Comment by chrisdothtml** [comment]
No, this setting exists in the insiders build

<img width="802" alt="screen shot 2018-08-10 at 1 16 09 am" src="https://user-images.githubusercontent.com/4969439/43941795-23ac0906-9c3b-11e8-9207-90407a59ad5e.png">

**Comment by chrisdothtml** [comment]
What does `format` do then?

**Comment by aeschli** [comment]
@chrisdothtml Sorry for only now getting back to this.
Formatting (done by 'Format Document') and validation (the warnings/errors you see in the editor or problems) are two different features.
We have already a setting that let's you control id the built-in json formatter is registered (you might ant to use a different formatter for JSON).
Is your request to disable valiadation?

**Comment by chrisdothtml** [comment]
> Is your request to disable valiadation?

Sorry, yeah this is what I'm looking for
