### ISSUE TITLE
Editor keeps invalidly auto-correcting my code or replacing my code with completely irrelevant stuff

### ISSUE THREAD

**Issue by rclai** [Microsoft/vscode#56089]
- VSCode Version: 1.25.1 (1.25.1)
- OS Version: OSX 10.13.6 (17G65)

Steps to Reproduce:

1. Type `console.log`
2. Editor decides to kill `.log`, leaving me with just `console`.

Does this issue occur when all extensions are disabled?: No

**Comment by ramya-rao-a** [comment]
You mention that this issue doesnt occur when all extensions are disabled, which means that one of your installed extensions is causing the issue. Please disable the extensions one by one to see which one is causing the issue and then log an issue in the repo for that extension
