### ISSUE TITLE
Explore to use webpack for extensions

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#56081]
The idea is to use [webpack](https://webpack.js.org) for extensions with the goal of faster extension loading/activation and reduce installation size/time. We attempt to do this for `emmet` and `git` are because both are owned by us, reasonable complex, and activate on startup (`*`).

**Comment by jrieken** [comment]
Numbers

| Extension | Before | After| Delta |
|-----------|-------|------|----|
| css | 1759 | 34 | -1725 |
| emmet | 201 | 61 | -140 |
| html | 2094 | 292 | -1802 |
| json | 696 | 297 | -400 |
| typescript | 404 | 278 |  -126 |

Total saving is **4193** files 👏

**Comment by octref** [comment]
@jrieken Looks great! I think a lot of the savings might come from not including `devDependencies` in `node_modules`. Now when I'm publishing extensions I always do `yarn --prod`, but of course I could use webpack too.

It would be great if we can put this to the documentation.

**Comment by jrieken** [comment]
> I think a lot of the savings might come from not including devDependencies in node_modules. 

The `vsce` tool does that by default. I run `yarn list --prod --json` to know when runtime dependencies you have and bundles only those. Next step is to not bundle dependencies of excluded/bundled depenencies

**Comment by octref** [comment]
@jrieken I don't think it does for `devDependencies` in subfolders, which are quite common in Language Server extensions.

**Comment by jrieken** [comment]
> it does for devDependencies in subfolders, which are quite common in Language Server extensions.

Yeah, that's something I have learnt over the weekend...
