### ISSUE TITLE
[BUG, CSS, Emmet] suggestion color if said "#" like "id"....

### ISSUE THREAD

**Issue by Mlocik97-issues** [Microsoft/vscode#56082]
Issue Type: <b>Bug</b>
if I don't write selector in root scope but for example in media query, it suggest colors and attributes.

#42245

![bez nazvu](https://user-images.githubusercontent.com/31345346/43901198-2b8358ea-9be7-11e8-92c8-096fcb2a19b7.png)

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (10.83GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by ramya-rao-a** [comment]
That position is a valid position for both css property/value as well as a css rule.
So, I cannot prevent emmet altogether in that position.

But `#` followed by anything that is not a hexadecimal is an invalid abbreviation, so I've pushed a fix for that.

So, `ul#123abc` is valid but `ul#something` is not
