### ISSUE TITLE
JS syntax highlighting with conditionals

### ISSUE THREAD

**Issue by ralfstx** [Microsoft/vscode#5608]
- VSCode Version: 0.10.11
- OS Version: Ubuntu 15.10

In JavaScript, the value that follows the colon in a conditional statement is not highlighted. For example, in the following statement, the `null` won't be highlighted.

```
var foo = bar ? true : null;
```

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#151
