### ISSUE TITLE
[HTML] Can we have an extra newline inserted after tags?

### ISSUE THREAD

**Issue by tommai78101** [Microsoft/vscode#56088]
Currently, VS Code supports `html.format.extraLiners`, which would insert newlines before specified HTML tags.

By default, this is what it shows in the User Settings:

```
"html.format.extraLiners": "head, body, /html",
```

Can we have the same feature, but instead of inserting newlines **before** the specified tags, it will insert newlines **after** the specified tags?

The option can be labeled as:

```
"html.format.extraLinersAfter": "/span, br, /div",
```

So it will insert newlines after the tags when formatting HTML documents.

What's the motivation behind this? 

The current HTML formatter in VS Code is not wholly supportive of adding newlines **after** certain tags during formatting. Especially when it would concatenate `<br>` with text like so:

**Before**:

```
<br> 
Hello world
<br/>
Goodbye
``` 

**After**:

```
<br> Hello world
<br/> Goodbye
```

And we wanted it to be like this after formatting:

```
<br>
Hello world <br/>
Goodbye
```

Where `<br>` tags are placed at the end of text content nodes.

If we are to allow options to change formatting behavior, so certain nodes are always put at the end of the line, then we could make it more flexible by allowing users to specify what HTML tags the formatter should insert newlines at.

Hence the motivation.

-----

Additional request: 
https://github.com/Microsoft/vscode-html-languageservice/issues/32

**Comment by aeschli** [comment]
We use [beautifyjs](http://jsbeautifier.org/) as the underlying HTML formatter. Would you mind filing this request directly against https://github.com/beautify-web/js-beautify ?

**Comment by tommai78101** [comment]
Ok, I didn't know HTML is also using js-beautify.
