### ISSUE TITLE
Open Editors: revisit order of groups to be based on visual order

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#56084]
Extracted from: https://github.com/Microsoft/vscode/issues/54916

Instead of ordering groups by creation time, order them by visual appearance.

**Comment by bpasero** [comment]
@isidorn actually I wonder if we should revisit this decision. Every other command (Cmd+1, 2, 3) and also the Go > Switch Group > Group 1, 2, 3 works in visual grid order and not history order. We could just do the same for the "open editors" view and it would probably be OK for most cases.

The thing that makes me want to revisit this is that a simple flow like the following one produces a very confusing result:

![before](https://user-images.githubusercontent.com/900690/43910219-801e20f0-9bfc-11e8-8dde-56707cb8e53e.gif)

I just dropped the group to the left of the empty one and it becomes Group 2.

**Comment by isidorn** [comment]
Yeah I also find this use case confusing.
We can change it in insiders and try it out for a couple of weeks to see how it feels when we follow the visual order.

**Comment by bpasero** [comment]
Opened https://github.com/Microsoft/vscode/pull/56264

**Comment by bpasero** [comment]
**Verify:**
* open a group
* open a group to the side
* open some editors in each group
* open a third group between the 2 groups

=> the formerly called group 2 should now be called group 3 and the new group 2 should be in between group 1 and 3 (same as the visual order).
