### ISSUE TITLE
Vs code is not launching at ubantu 18.04

### ISSUE THREAD

**Issue by rjptechsolutions** [Microsoft/vscode#56087]

**Comment by mfocko** [comment]
Try running from Terminal... If you've installed from tarball you might be missing libraries.

In case you can't figure out what to install, install apt-file, update it (like you would apt or apt-get) and use `apt-file find <filename>`

**Comment by Tyriar** [comment]
@mfocko great advice!

@rjptechsolutions also how did you install VS Code?
