### ISSUE TITLE
Open file with (using current OS context menu)

### ISSUE THREAD

**Issue by x3r10n** [Microsoft/vscode#56083]
It would ber nice if we could right-click a file in the file explorer and have the "Open with" menu.

Example : 
![image](https://user-images.githubusercontent.com/4524121/43901180-cf7356ea-9bb4-11e8-81e1-76eae159c5d5.png)

I"m mostly looking to be able to open .jpg and .png file with photoshop if I have modification to do.

If it's not feasible to grab OS Open With menu, we could have a setting binding the file extension to the file path of the application we want to open it with.

**Comment by joaomoreno** [comment]
Code already associates with certain file types, mostly textual ones. If you want the same for images, then you must choose `Other`, then pick VS Code.

**Comment by x3r10n** [comment]
No, maybe I wasn't clear. I want this menu to be inside on vs code and when I right click an Image in my file explorer I can chose photoshop to edit the file.

<img width="521" alt="image" src="https://user-images.githubusercontent.com/4524121/43955586-dc247a26-9c6e-11e8-848a-74d419f07daa.png">

**Comment by joaomoreno** [comment]
Oh wow. I don't think it's possible to have the native menu in there. But, as an extension, you can contribute menu actions to explorer items. I recommend writing an extension for it.
