### ISSUE TITLE
Add setting for default path for new terminals?

### ISSUE THREAD

**Issue by GandalfSaxe** [Microsoft/vscode#56085]
Sometimes it's practical to have a project folder open at the top level to be able to access all files with `Go To File...` (Cmd+P), but sometimes the root of the main code directory is further down the project tree.

This means that each time you open a terminal, you have to `cd` down to the code directory before running main scripts.

Could you consider making a setting to set the path of the default directory that new terminals open in This way you would be able to have one folder open, but new terminals open in a subfolder for convenience.

**Comment by ArturoDent** [comment]
Maybe the extension Termianl Here https://marketplace.visualstudio.com/items?itemName=Tyriar.vscode-terminal-here helps?

**Comment by GandalfSaxe** [comment]
Thanks, I already have that extension. It provides a comment to make a new Terminal in the current folder of the open file, which is not what I want. I want all new terminals (Ctlr+`) to open not in the open folder, but in a specified folder within the root folder.

**Comment by Tyriar** [comment]
`terminal.integrated.cwd` does this

**Comment by GandalfSaxe** [comment]
@Tyriar thanks a ton! Exactly what I was looking for.

I looked everywhere in the docs, and couldn't find this mentioned. I think it's worth a mention [here](https://code.visualstudio.com/docs/editor/command-line) or [here](https://code.visualstudio.com/docs/editor/integrated-terminal). I guess I could've found it by fuzzy search in the settings, but it just didn't happen this time.

Anyway thanks and keep up the good work 👍

**Comment by Tyriar** [comment]
@GandalfSaxe good call 👍, I added it to the integrated terminal page rather than the CLI page: https://github.com/Microsoft/vscode-docs/commit/ac5fef24c88f6306015bf1e3a23df19f10a46a8d

**Comment by GandalfSaxe** [comment]
@Tyriar Any chance we could get `terminal.integrated.cwd` to work with relative paths from workspace root? Unfortunately the [VSCode variables](https://code.visualstudio.com/docs/editor/variables-reference) are not available for use in settings.json. Just to make sure, I tried:
`"terminal.integrated.cwd": "${workspaceFolder}/code"`
which didn't work.

As a result, `terminal.integrated.cwd` is in practice pretty useless in any workspace involving multiple people and even just multiple devices.

Or perhaps I missed something and relative paths are supported? I really hope I missed something 🙂

**Comment by Tyriar** [comment]
Hmm, relative is supposed to work:

https://github.com/Microsoft/vscode/blob/a220dfe9f2e609fa7872b5aaea1f5c52ac2e05da/src/vs/workbench/parts/terminal/node/terminalEnvironment.ts#L143-L150

If it doesn't we should create a bug on it with some repro steps. On `${workspaceFolder}` support, I think this should work as well but it's not there yet, another issue would be good 😄

**Comment by GandalfSaxe** [comment]
Sorry my mistake. I only tried with the environment variable, not simply plain relative path. It works!  Hurray, I did miss something. Lack of sleep I suppose 😅

Thanks, this is all cleared up now! Keep up the good work, I enjoy VSCode every day.

**Comment by Tyriar** [comment]
Thanks again for the feedback
