### ISSUE TITLE
Don't use English font family for Chinese UI

### ISSUE THREAD

**Issue by ArianeLu** [Microsoft/vscode#5609]
- VSCode Version: 1.00
- OS Version: Windows 10 Version 1511

Steps to Reproduce:

1. Change system language to Chinese (Simplified)
2. Install Visual Studio Code
3. Open 'File Panel', take a look at Chinese char.
3. They are blue , and not clear, very hard to read

We should use Microsoft YaHei for Chinese char, like toolbar and window title

**ScreenSnap:**
![bad](https://cloud.githubusercontent.com/assets/4962408/14711561/4e232d2e-080c-11e6-90ed-2e5c68229469.png)
_Bad ↑_
![good](https://cloud.githubusercontent.com/assets/4962408/14711562/4e76a0f8-080c-11e6-9d3d-8e8a68374137.png)
_Good ↑_

**Comment by medifle** [comment]
+1

**Comment by bpasero** [comment]
@ArianeLu @medifle this should be much better with our new insiders release. 
You can give it a try from our insiders release today: http://code.visualstudio.com/Download#insiders

Closing in favor of https://github.com/Microsoft/vscode/issues/5260
