### ISSUE TITLE
cannot get emmet to work

### ISSUE THREAD

**Issue by elcy-b** [Microsoft/vscode#56093]
I have tried setting, reinstalling and have not been able to get emmet to work with either the enter or tab.  Any help is very appreciated. Thanks

**Comment by elcy-b** [comment]
I have looked at the documentation and it appears that emmet should be automatically working.  But I type a ! and don't get the html generated whether I try the enter or tab keys.  Nothing happens. Please help. what am I missing?

**Comment by ragar005** [comment]
please provide more details on your emmet configs in settings. Did you change the default settings?
Also make sure "emmet.showAbbreviationSuggestions": true, in your settings

**Comment by ramya-rao-a** [comment]
- In what file type are you trying this?
- Please share sample code and the location in the sample code where you are trying to expand abbreviations.
- Have you disabled quick suggestions in your settings?
- Do read [Emmet in VS Code](https://code.visualstudio.com/docs/editor/emmet)
- To have the abbreviation expand on tab, you need to add `"emmet.triggerExpansionOnTab": true` in your settings

**Comment by elcy-b** [comment]
Thanks so much Ramya.  Working now!

**Comment by ramya-rao-a** [comment]
Great, Happy Coding!
