### ISSUE TITLE
Go to defination not working 

### ISSUE THREAD

**Issue by shalin51** [Microsoft/vscode#56098]
Issue Type: <b>Bug</b>

 When I press ctrl enter it loading and not gpoing to defination

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU           W3690  @ 3.47GHz (12 x 3466)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|24.00GB (16.32GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|1.6.1
python|ms-|2018.7.1
chrome-tools|msh|0.0.3
debugger-for-chrome|msj|4.8.2
watch-in-chrome|sne|0.0.2

(2 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
f12 goes to definition, ctrl+f12 goes to implementation
