### ISSUE TITLE
Markdown footnotes support

### ISSUE THREAD

**Issue by szepeu** [Microsoft/vscode#56090]
Currently Markdown preview doesn't support rendering footnotes. [Gitlab example here](https://docs.gitlab.com/ee/user/markdown.html#footnotes) and how it looks in the VS Code:

![image](https://user-images.githubusercontent.com/24934271/43905640-c128923e-9bf1-11e8-9d00-eca4dc023eec.png)

VSCode 1.25.1
Windows 7 SP1 64bit

**Comment by mjbvz** [comment]
Provided by this extension: https://marketplace.visualstudio.com/items?itemName=bierner.markdown-footnotes
