### ISSUE TITLE
WebviewPanel.viewColumn can return symbolic columns even after it is visible

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#56097]
Issue Type: <b>Bug</b>

1. Create a `WebviewPanel` and set its `viewColumn` to `ViewColumn.Beside`
1. Show the Webview
1. Query the `viewColumn` property -- it will still return `ViewColumn.Beside` rather the its actual view column

Also I noticed that in the docs `WebviewPanel.viewColumn` is marked as deprecated -- what is the new way to access this?

My use-case for needing `WebviewPanel.viewColumn` is that I want to open editor tabs in response to actions (clicks) in my webview and I want to ideally open them to the left of the webview. So without `WebviewPanel.viewColumn` my only option would be to use `ViewColumn.Beside` but that only opens editors to the right-ish of the current editor.

//cc @mjbvz 

VS Code version: Code - Insiders 1.26.0-insider (bda8a4de93278004d6d7c3628b92664f93f7e811, 2018-08-09T11:35:31.607Z)
OS version: Windows_NT x64 10.0.17730

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (13.49GB free)|
|Process Argv|C:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by mjbvz** [comment]
Note that when first creating a webview with a symbolic view column, the view column will now be marked as `undefined` until we can resolve the non-symbolic column. The `onDidChangeViewState` is also fired when this happens
