### ISSUE TITLE
File Explorer Improvements + Bug Report

### ISSUE THREAD

**Issue by beastdestroyer** [Microsoft/vscode#56099]
Issue Type: Feature Request + Bug Report (at the bottom)
No relevant issues found

The file explorer is pretty cool. Add folders to workspace/ Open them up etc. One great benefit of adding a workspace is that the folders are sorted based on when you added them, but order seems to only be changeable in the settings.json/workspace settings. That's just one thing I want to touch on;

- Be able to move folders in workspaces (root ones that show up in settings.json bear in mind) using mouse and not having to open up editor and change up order when I need to. This behaviour is essentially what Photoshop incorporates into its Layers tab. You can drag a folder, move it between 2 others and in Photoshop, a little thin blue line shows up to denote it will be placed there, this behaviour should be incorporated too, and also for above/below files.
- Custom grouping of folders
  - Essentially being able to create a "folder group" and drag folders in and out of them. These wouldn't have their own tabs, but rather a divider which also acts as a dropdown, a mini example to demonstrate:
Say your workspace was like this:
```
project1
folder1
folder2
project-x
```
You could be able to have the ability to sort it into something like this:
```
one ^
| - project1
| - folder1

two ^
| - folder2
| - project-x
```
> The ^ represents a dropdown arrow, the one that VSCode would normally use to indicate a dropdown, personally I feel it should be an arrow to denote whether you can collapse it or un collapse it.

That idea is essentially equivalent to Photoshop's Groups. Again, the ability to drag around these dropdowns to place them where you want should be available.

Just some ideas, thanks for reading!

> Note, I'm not sure if this was on purpose, doesn't seem to be, but since I've used VSCode, under settings.json/workspace settings, the folder array of objects is unhighlighted, yet the ```settings``` object that appears straight after is highlighted just fine.

**Comment by isidorn** [comment]
The feature request is a combination of out of scope / duplicate. Please search for other issue with tag file-explorer and feature-request and you might find similar things
As for the bug report, please file a new issue with concise, nice reproducable steps
