### ISSUE TITLE
Coding-completion takes longer than usual to complete

### ISSUE THREAD

**Issue by mrwadepro** [Microsoft/vscode#56091]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by ramya-rao-a** [comment]
It looks like you submitted this issue from the issue reporter, but you missed pasting the information from the clipboard
- In what file type are you seeing this?
- What version of VS Code are you using?
- Please share sample code.

**Comment by sandy081** [comment]
Please provide proper description with steps to reproduce and reopen.
