### ISSUE TITLE
Expose methods to alter cursor appearance via extensions API

### ISSUE THREAD

**Issue by bgourlie** [Microsoft/vscode#561]
I would like to be able to change the cursor appearance via the extensions API.  My particular use-case is to implement vim-like modal text editing, and would like to be able to style a block cursor for normal mode.

**Comment by jrieken** [comment]
There is `editor.selection` which you can assign an empty selection to.

**Comment by jrieken** [comment]
Oh, appearance..

**Comment by colbyrussell** [comment]
Update: vscode now has an `editor.cursorStyle` setting that allows a `block` value.  (Implemented in PR #1586.) The issue as written is still valid, since (AFAICS) there's no way to control it from the extensions API.

**Comment by alexandrudima** [comment]
@bgourlie @ghost
This is now done on master, three styles (line, block and underline) can be set via `TextEditor.options`. Please also see https://github.com/alexandrudima/vscode-vim if you are authoring a vim emulation for VS Code
