### ISSUE TITLE
URIs with custom labels

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#56106]
I've made this view:

![activity_bar_views](https://user-images.githubusercontent.com/1812093/43934179-41334526-9c4e-11e8-85b0-bc77b19761e5.png)

Which works like this:

- Todos are grouped by file
- A file should display its filetype icon
- A file should have its relative path as the label, instead of just the name (in order to avoid confusion when having multiple files named `index.ts`, for example)

This is impossible to implement without workarounds because URIs don't really support custom labels, they "always" show just the file name.

In order to make this work I had to write something like this:

```typescript
  getURI ({ filePath, relativePath }) {
    const uri = vscode.Uri.file ( filePath ) as any;
    uri.fsPath; // Accessing it before replacing `.path`, so that its value will be preserved
    uri.path = _.trimStart ( relativePath, '/' ).replace ( /\//g, '⧸' ); // Regular slashes get removed
    return uri;
  }
```

Another way of solving this issue, other than adding support for custom URIs labels, would be to add an API for retrieving those filetype icons given an arbitrary extension.

**Comment by fabiospampinato** [comment]
Turns out there's no forward slash alternative character that's properly rendered on all OSs, so until this gets fixed I have to remove the filetype icons from my view.

**Comment by nealot** [comment]
Aren't custom labels already supported within VSCode? The Quick Open widget seems to be displaying something similar to your design which leads me to believe that the foundation already exists. Hopefully this can be implemented in the next iteration.

**Comment by jrieken** [comment]
@fabiospampinato How do you use the [`TreeItem#resourceUri`](https://github.com/Microsoft/vscode/blob/74de533cacc5d3f7981a20c2a7ba51a2045b1bcd/src/vs/vscode.d.ts#L6502) API? That should take an uri and render it with the uri rendering we use everywhere, e.g. using the proper path separator, making it relative to the workspace etc etc

**Comment by fabiospampinato** [comment]
@jrieken Thank you! I didn't realize one could set both `TreeItem#label` and `TreeItem#resourceUri`.
