### ISSUE TITLE
API to query/control intellisense filter

### ISSUE THREAD

**Issue by Tomeamis** [Microsoft/vscode#56102]
When a CompletionItemProvider provides completion items, vscode sorts and filters them. But it is currently not possible to find out how this happens (I din't find anything in the docs and there seems to be no API for this).

I am writing an extension that uses another software to get completions for C++, and it has 2 modes: identifier-based, which is fast but inaccurate, and semantic, which is somewhat slower, but very accurate.
I wanted to add a feature where if the identifier completer failed, the semantic completer would be tried, but at present I have no way of knowing what is actually a failure, since even if I get some suggestions, they may all be filtered and no completion box would pop up.

If there was some way to figure out which completions will be filtered out, I could deal with these cases, but as it stands, I have no way to do that.

An API which would allow me to find out if an item will be shown would enable me to do this.

Example of filtered strings:
I type 'r' on its own line. Extension suggests vector, string, assert, ... but no completion box shows up.

**Comment by jrieken** [comment]
> If there was some way to figure out which completions will be filtered out, I could deal with these cases, but as it stands, I have no way to do that.

For filtering the rule is that all characters of the *current prefix* must occur in order in a suggestion and that the first character must be a *strong match* - that is matches on upper-case characters, the word-start, or after a separator. The *current prefix* is defined by the `range` property of your completion items. Samples (`foo|` is the current prefix and cursor)

```
r|   vector -> no match, first character doesn't match strong
vr| vector -> match, all character occur in order and first match is strong
```

More samples can be found here: https://github.com/Microsoft/vscode/blob/74de533cacc5d3f7981a20c2a7ba51a2045b1bcd/src/vs/base/test/common/filters.test.ts#L259. Last, when the current prefix is empty, no filtering happens and sorting purely bases on the `sortText`-property of your completion items.
