### ISSUE TITLE
macOS: dock menu showing unopened files as open

### ISSUE THREAD

**Issue by hparadiz** [Microsoft/vscode#56100]
- VSCode Version: Version 1.26.0-insider (1.26.0-insider)
- OS Version: 10.12.6 (16G1408)

Steps to Reproduce:
1. Not sure, see #54992

Does this issue occur when all extensions are disabled?: Yes

### Here is a screenshot of the dock menu with one window open:
![image](https://user-images.githubusercontent.com/195216/43915895-144a1f54-9bda-11e8-9606-5b1dfff1577c.png)

### Here is a screenshot of the dock menu while VS Code is completely turned off:
![image](https://user-images.githubusercontent.com/195216/43915928-29a8ba86-9bda-11e8-9630-37f9b1e0a9d9.png)

I've had these two menu items for `db.php` in my dock menu for months and I'm at my whits end trying to figure out a way to get rid of them.

#54992 @jrieken 
https://github.com/electron/electron/issues/11159

Maybe an issue with macOS?

**Comment by bpasero** [comment]
Yeah, it is nothing we can do. A while ago I pushed a change to try to make this better: instead of just adding to the dock, I remove all entries and write them all down again based on the history VSCode knows.

@hparadiz can you see if the list in the dock matches with what you see under File > Open Recent?

**Comment by hparadiz** [comment]
@bpasero 

It does not match.

![image](https://user-images.githubusercontent.com/195216/43965705-f6b2bc30-9c8d-11e8-9b78-f48bc234c408.png)
![image](https://user-images.githubusercontent.com/195216/43965741-0f10e04a-9c8e-11e8-99ad-e21b32063d20.png)


Is there any way to flush it empty or redraw the entire menu from scratch?

**Comment by bpasero** [comment]
@hparadiz that is exactly what I am doing in code, but I know this is an area of bugs, hence I filed https://github.com/electron/electron/issues/11159. There is nothing VSCode can do about it I think. I suggest you add your vote to that issue.

**Comment by hparadiz** [comment]
I was able to get rid of the bad entries!

`killall Dock` forced a reset of the Dock process which cleared out the fake "open" files from my dock menu.

https://www.quora.com/What-is-the-best-way-to-delete-a-recently-opened-file-history-on-a-Mac
