### ISSUE TITLE
Run active file [with spaces in name] in active terminal

### ISSUE THREAD

**Issue by luiszun** [Microsoft/vscode#56109]
Issue Type: <b>Bug</b>

I checked the issue reproes in the latest code version.

1 - Open a file that contains whitespaces in name. (In this example "AA Generator.py")
2 - Execute "Run Active File In Active Terminal"

Expected result: The file is executed, either quoted :
- PS C:\Users\luiszun\git\vscode> "c:\Users\luiszun\Desktop\AA Generator.py"

Actual result: The incomplete-filename is executed with the rest interpreted as a parameter.

PS C:\Users\luiszun\git\vscode> c:\Users\luiszun\Desktop\AA Generator.py
c:\Users\luiszun\Desktop\AA : The term 'c:\Users\luiszun\Desktop\AA' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included,
verify that the path is correct and try again.
At line:1 char:1

VS Code version: code-oss-dev 1.27.0 (Commit unknown, Date unknown)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.79GB (3.75GB free)|
|Process Argv|C:\Users\luiszun\git\vscode\.build\electron\Code - OSS.exe . --remote-debugging-port=9222 --no-first-run --no-default-browser-check --inspect=5875|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by luiszun** [comment]
Would you accept PR?

**Comment by Tyriar** [comment]
@luiszun yes, here's a code pointer for this: https://github.com/Microsoft/vscode/blob/af9d9ac56087a7b2ec7024cd44c824654a34bc96/src/vs/workbench/parts/terminal/electron-browser/terminalActions.ts#L641

**Comment by jats22** [comment]
Hi @luiszun , @tyriar I would like to take it up if not already worked on. Thanks.

**Comment by luiszun** [comment]
Thanks @jats22, but I'm already on it.

**Comment by alexr00** [comment]
This works now!
