### ISSUE TITLE
MAC OS: Visual Studio is not allowing to save a file into a subfolder

### ISSUE THREAD

**Issue by Sriharsha-hatwar** [Microsoft/vscode#56101]
VSCode Version:  Version 1.25.0 (1.25.0)
OS Version: Mac OS X version: 10.12.6

Steps to Reproduce:

1. Open visual studio code using the spotlight search 
2. Create a new file and try to save it using save as, there are only three places where it allows to save, one is device- external storage, another place is favorites- Application, Desktop, Downloads and another place is recently used.
I am not able to navigate into a subfloder inside the Desktop for saving the file.

Does this issue occur when all extensions are disabled?: Yes.

**Comment by ramya-rao-a** [comment]
Do you see this using the latest [Insiders](https://code.visualstudio.com/insiders) too?

**Comment by Sriharsha-hatwar** [comment]
OK sorry for the wrong information, so there is a button that when pressed would open the different locations that I can save into, though It is not straightforward. Can be made better if there is a text that  provides an option to browse into the folders.

The button at the right side of the save as region is not at all straightforward.

<img width="518" alt="screenshot" src="https://user-images.githubusercontent.com/14826535/43938767-3a543406-9c83-11e8-8829-224fd6a2a1d3.png">

**Comment by bpasero** [comment]
Welcome to to macOS file dialogs. I suggest you report this against Apple.
