### ISSUE TITLE
Ubuntu Visual Studio dnx Run Command

### ISSUE THREAD

**Issue by avikenjale** [Microsoft/vscode#5610]
- VSCode Version: 1.0.0
- OS Version: Ubuntu 14.04

I have created a simple WEB API application using Visual Studio Code on Ubuntu(on my VMWare). I completed all prior steps to install & configure .NET core, VS Code & mono libraries and packages. my `package.json` file contains following parameter as:
 
`"commands": {
    "web": "Microsoft.AspNet.Server.Kestrel"
}`

when I use 'ctrl+shift+p' to get command pallet, I can get `dnx:Run Command`, however after selecting this, I am not getting `dnx web - (MyApplication)`. When I tried to run same application from terminal using `dnx web`. I am getting proper results of saying :

`Hosting environment: Production
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.`

Same application, I moved to my windows 7 environment, I am getting everything expected from VS Code. I don't have to run explicitly from command prompt.

Is it the behavior of VS Code on **Ubuntu** Vs **Windows** environment or something is wrong.

**Comment by dbaeumer** [comment]
This issue was moved to OmniSharp/omnisharp-server#214
