### ISSUE TITLE
Sort Lines according to Template

### ISSUE THREAD

**Issue by walthuriks** [Microsoft/vscode#56113]
Hello i have multiple files with the same lines but different values. I did a template where i wrote all the lines in with empty values, how can i transfer the arrangement of my template to the other files? Thanks for help

**Comment by ramya-rao-a** [comment]
I dont understand what you mean by templates here.. Are you talking about snippets? See https://code.visualstudio.com/docs/editor/userdefinedsnippets

**Comment by walthuriks** [comment]
No no..  im sorry for not having it explained enough. I give an example: i have multiple files for multiple objects but they all have the same stats, lets say in one file there is on line 26 "weight = 0.6" but in another file for another object there is the same parameter but its on line 160 and says "weight = 1.2". How could i preserve the values but make a uniform position for all the lines? For example like in a template where the "weight = xyz" line is on position 16. How could i sort the other ones to be also on line 16?

**Comment by ramya-rao-a** [comment]
So you want to sort lines in a file based on file contents that is defined in another file?

**Comment by walthuriks** [comment]
Yes exactly. I saw that there is an alphabetical sorting algorithm but when it can do that then there has to be an option to create an algorithm that searches for lines that have the same words

**Comment by ramya-rao-a** [comment]
That would need a great deal of customization to support out of the box in VS Code.

Instead, you can create an extension for that. 
- Follow https://code.visualstudio.com/docs/extensions/yocode to get a sample extension generated.
- You can register a command to sort the way you want and add your algorithm there.
