### ISSUE TITLE
Keybindings are not loaded properly in the native menu

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode#56116]
Repro Steps: 
1. Clean install 
2. Open VS Code
3. Observe native menubar has no keyboard shortcuts

Alternative Repro Steps:
1. Change a keybinding
2. Observe the menubar does not reflect the change.

**Comment by kieferrm** [comment]
Must fix.

**Comment by Tyriar** [comment]
Reviewed, tested, merged and cherry picked to `release/1.26`. See https://github.com/Microsoft/vscode/pull/56121

**Comment by isidorn** [comment]
@Tyriar since you tested this can you please add a verified label
