### ISSUE TITLE
Mac: dual screen, right-click -> new file, focus/cursor doesn't move to Code

### ISSUE THREAD

**Issue by leskemp** [Microsoft/vscode#56111]
Did that, but could be my search foo failed.

Checked, it is an issue in the insiders build

- VSCode Version: Version 1.25.1 (1.25.1)
- OS Version: macOS 10.13.6

Steps to Reproduce:

1. 2 screens
2. open Code on one screen, another app on the other screen
3. open a project with folders in VSCode
4. Place focus on other app
5. Have focus in a text box of some sort in that other app (not necessary, but helps see the focus)
5. Right-click on a folder in VSCode and select New File and type
6. the focus remains in the other app

 code will not launch via command line "command not found: code"
Does this issue occur when all extensions are disabled?: Yes/No

![screen shot 2018-08-10 at 9 25 14 am](https://user-images.githubusercontent.com/38677898/43927538-00265742-9c82-11e8-8848-3d5913e94f4c.png)
<img width="418" alt="screen shot 2018-08-10 at 9 25 47 am" src="https://user-images.githubusercontent.com/38677898/43927584-1a38499c-9c82-11e8-8f70-7f174f558925.png">

**Comment by isidorn** [comment]
This is an electron issue that the context menu does not focus the applicatino. There is already an issue in this repository about this, you can search and find it.
And also make sure to file an issue against electron if it is not already filled. Thanks
