### ISSUE TITLE
lagging when changing workplace in zen mode (macOS)

### ISSUE THREAD

**Issue by MichaelMW** [microsoft/vscode#56128]
Issue Type: <b>Bug</b>

In zen mode if I want to switch app, say, search something on the internet, I usually do the 4 finger swipe to switch to another workplace. However, somehow this is very laggy. This disrupts the workflow. 

Otherwise, no complaint. Vscode ftw. 

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 4, 10|
|Memory (System)|8.00GB (0.29GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.17.0
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.19.0
vscode-dash|dee|1.10.0
jupyter|don|1.1.4
python-extension-pack|don|1.4.0
gitlens|eam|8.5.4
gc-excelviewer|Gra|2.1.25
nbpreviewer|jit|1.0.0
MagicPython|mag|1.0.12
rainbow-csv|mec|0.4.2
python|ms-|2018.7.1
snippet-creator|nik|0.0.4
biosyntax|rea|0.0.9
vscode-icons|rob|7.25.0
markdown-preview-enhanced|shd|0.3.5
code-spell-checker|str|1.6.10
python|tht|0.2.3
pdf|tom|0.3.0
vscodeintellicode|Vis|1.0.3
jinja|who|0.0.8
markdown-all-in-one|yzh|1.6.0

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to the code. As such, I will go ahead and close it. If you can identify the component that is causing the issue, please report it upstream:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.
