### ISSUE TITLE
Custom titlebar should be hidden when fullscreen in Windows 10

### ISSUE THREAD

**Issue by PowerSnail** [Microsoft/vscode#56127]
When using native titlebar, fullscreen vscode hides the titlebar. However, using custom titlebar, there is no way to hide it. 

The title bar serves very little purpose when I am in full screen mode. I can imagine others may find it useful when they have multiple instances. However, probably some are like me, who only open one instance of vscode. 

Hiding the titlebar provides a nice feature: tabs are at the very top of the screen, which makes it very easy to move the mouse onto tabs. 

(I looked at some other issues about titlebar and fullscreen, but did not see a same issue as mine. If I missed any, my apology in advance)

**Comment by bpasero** [comment]
@PowerSnail I cannot reproduce that on Linux at least where I use the custom title bar too. Do you maybe have a setting configured to show the custom title in full scren?

**Comment by PowerSnail** [comment]
I am using Windows 10. 

I just fiddled with the setting a bit, and found that this is the culprit:

```
    "window.menuBarVisibility": "toggle"
```

If it is set to "default", then the titlebar hides as expected.

However, this is confusing, since in FullScreen mode, I don't see a menu showing with either setting. Only when I press alt with visibility set to "toggle" does the menu show up. 

Here is a little table if my description is unclear:

| Setting | Press `alt` | Title bar Visibility | Menu bar Visibility |
|---|---|---|---|
|"default" | 0 time | Hidden | Hidden |
|"default" | 1 time | Hidden | Hidden |
| "toggle" | 0 time | Showing | Hidden |
| "toggle" | 1 time | Showing | Showing |

My point is in the third row ("toggle" + not press alt) should hide the titlebar as well.

PS: Thanks for the quick reply.

**Comment by bpasero** [comment]
@sbatten I don't think the custom title should show when in fullscreen in any of the setting of menu bar visibility.

**Comment by sbatten** [comment]
@bpasero what is happening is the menubar is showing and since the space is reserved I kept the title around. the window controls are hidden and there is no app icon. this was to prevent the annoying ui shift effect that occurred with the old menu.

**Comment by bpasero** [comment]
@sbatten was that a problem tough? I think what people like is the ability to toggle in the menu in fullscreen mode when needed. Why would we change this behaviour? Maybe we could have a third option to always show the title and menu in fullscreen, would that help?

**Comment by bpasero** [comment]
I think users agree with me: https://github.com/Microsoft/vscode/issues/56291, https://github.com/Microsoft/vscode/issues/56293

**Comment by PowerSnail** [comment]
@sbatten 

I understand your point about avoiding UI shift. However, I still believe the title bar should be hidden with the menu anyway.

When menu visibility is set to toggle, it probably means that the user (at least me) wants to hide the menu for the most of the time, and occasionally use it. If the user desires to see the menu often, he/she will probably just leave the menu visible. I cannot really think of a situation where the user frequently toggles the menu. Of course, I don't have any data to support that, so that is just my conjecture. 

If you agree with my conjecture, then saving the space (hiding title bar) is more important than avoiding UI shift, since the latter will occur scarcely. 

Furthermore, UI shift is conventional in the situation. At least from all software I have used, if the menu is toggle-able, it hides completely without leaving a placeholder. I would argue that following conventions is preferable, when the alternatives bring little benefit.  

Finally, consider the intention of toggle-able menu. Isn't the purpose to save the space? If only the texts of the menu bar would be hidden, it brings no real gain to toggle the menu.

**Comment by akbyrd** [comment]
I think the behavior of the native menu is exactly correct and should not be changed. There are two separate concerns there though:

1) The native menu and custom menu should behave exactly the same way, whatever that happens to be. Currently the custom menu is completely unreachable in fullscreen with `window.menuBarVisibility` set to default. That's just broken. And inconsistent with the native menu. Toggle leaves the window title always visible and hidden leaves the title visible when not fullscreen. These made sense with the native menu, but don't with the custom menu.

2) Changing the behavior to permanently reserve the space is clearly contentious and should therefore be introduced as a new enum value for the setting. Personally, I don't want this reserved behavior at all, as it is completely incongruous with the reason `window.menuBarVisibility` exists: to save space.

**Comment by sbatten** [comment]
Thank you @PowerSnail @akbyrd for your feedback. I definitely understand your points and have created the above PR to address the issue.

Another idea floating around was to bring back the old behavior, but instead of the UI shift, draw the menubar (while it is visible) on top of the rest of the UI. This would block the editor tabs and part of the sidebar for the short duration of using the menu, but you are indeed intending to just the menu. Any thoughts there? or am I trying to solve a non-issue? @bpasero

**Comment by akbyrd** [comment]
I think drawing as an overlay is an acceptable middle ground. When using the menu I've never had any need to see the editor tabs, and the individual menus already obscure window content. However, that looks like a workaround for a different underlying issue.

I agree that the layout shift is annoying, but I find it annoying because it's so janky, not simply because it's happening. The extra frame of jitter on the bottom bar and bottom panel are what make it look so bad. Something strange happens like the editor taking an extra frame to update its size and it's pushing/pulling everything below it.

If that extra frame of jitter wasn't there it wouldn't look nearly as bad and I wouldn't care at all. Bonus points if it animates in smoothly.

**Comment by sbatten** [comment]
that jankiness doesn't reproduce with the custom titlebar, so I'll consider the issue resolved. if you still see the issue with the custom titlebar, let me know in a new issue. thanks for the feedback @akbyrd

**Comment by akbyrd** [comment]
Thanks for taking a look at this @sbatten. I'm guessing I should look for this in 1.27?

**Comment by sbatten** [comment]
@akbyrd yes 1.27, also currently in insiders, thanks

**Comment by akbyrd** [comment]
@sbatten The new menu is quite sexy. Thanks!

It removes most of the layout jitter that existed with the previous menu. However, I did find one place where there's still a bit of jitter: markdown files. If I open the Release Notes and toggle the menu bar, the small 'scroll to top' button in the bottom right and the scroll bar jitter. The scroll bar only jitters when scrolled the bottom of the window.

Also, It would be great to see the previous title bar patched up to fix the jittering and keybinding issues if it's going to be kept around.
https://github.com/Microsoft/vscode/issues/35010#issuecomment-419665485

**Comment by akbyrd** [comment]
Done.

https://github.com/Microsoft/vscode/issues/58375
https://github.com/Microsoft/vscode/issues/58376
https://github.com/Microsoft/vscode/issues/58377
