### ISSUE TITLE
emoji tip

### ISSUE THREAD

**Issue by jiyewushen** [Microsoft/vscode#56124]

**Comment by jiyewushen** [comment]
like this: ![image](https://user-images.githubusercontent.com/16441451/43936251-5a605ebc-9c8a-11e8-8f20-339f11533494.png)

**Comment by joaomoreno** [comment]
VS Code does support emojis. Just not github's syntax.

![image](https://user-images.githubusercontent.com/22350/43949021-b4f1d96c-9c8c-11e8-91e1-8cb8fa3b9b61.png)

**Comment by joaomoreno** [comment]
Closing as out of scope, emojis are supported, just not the `:` syntax.
