### ISSUE TITLE
Intellisense is very slow.

### ISSUE THREAD

**Issue by muralinit** [Microsoft/vscode#56120]
Issue Type: <b>Performance Issue</b>

It is almost taking 30 secs to load the intellisense.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (10.27GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    98	  8268	code main
    0	    68	  3884	   shared-process
    0	   242	  4596	   window (● tabular-mapper.component.ts - gpoWorkflow-angular-polarisApp - Visual Studio Code)
    0	    11	  4884	     watcherService 
    0	    10	  9592	       console-window-host (Windows internal process)
    0	    89	 11232	     extensionHost
    0	   876	   232	       electron_node language-server-stdio.js 
    0	    38	  1992	       electron_node jsonServerMain.js 
    0	   191	  6060	       electron_node electronForkStart.js tsserver.js 
    0	    35	  9636	         electron_node typingsInstaller.js tsserver.js typesMap.js 
    0	    67	 10048	       electron_node tslintServer.js 
    0	   100	  9736	   gpu-process
    1	    77	 12160	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● tabular-mapper.component.ts - gpoWorkflow-angular-polarisApp - Visual Studio Code)
|    Folder (gpoWorkflow-angular-polarisApp): 512 files
|      File types: ts(219) html(202) scss(38) json(10) jpg(8) js(5) yaml(4)
|                  build(2) md(2) xml(2)
|      Conf files: makefile(1) package.json(1) tsconfig.json(1) tslint.json(1)
|                  launch.json(1)
|      Launch Configs: chrome(3);
```

</details>
<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
jshint|dba|0.10.19
vscode-eslint|dba|1.4.12
gitlens|eam|8.5.4
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.34
beautify|Hoo|1.3.2
debugger-for-chrome|msj|4.8.2
javascript-typescript|sou|0.0.7

</details>

**Comment by ramya-rao-a** [comment]
What filetype were you working on when this happened?

**Comment by armoucar** [comment]
very, very slow in here also... it started suddenly yesterday. Can't remember if there was an update before the issue started.

![image](https://user-images.githubusercontent.com/1134016/43957680-1722bbdc-9c7f-11e8-9672-22baeedb167c.png)

**Comment by hegelstad** [comment]
This will likely be solved when vscode upgrades typescript version 3.

Try to roll your own typescript version in vscode.

1. npm install typescript@next
2. go to vscode settings
3. add this line: `"typescript.tsdk": "<absolutepath/to/project/node_modules/typescript/lib/>"`
4. >Reload window

**Comment by ramya-rao-a** [comment]
Also try our latest [Insiders](https://code.visualstudio.com/insiders)
