### ISSUE TITLE
failed to build and package from v1.25.1 in windows

### ISSUE THREAD

**Issue by chongchai** [Microsoft/vscode#56122]
- VSCode Version: 1.25.1
- OS Version: windows 7

I download the vscode 1.25.1 source code and try to build from source as [Build and Run](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run).
But it seems failed in the package step. My network is behind proxy.

Steps to Reproduce:

1. download v1.25.1 source code
2. install node modules: `yarn`
3. compile: `yarn run compile`
4.  package: `npm run gulp -- vscode-win32-x64`

The 4th step package got error like this:
```
[18:40:27] Finished 'optimize-vscode' after 55 s
[18:40:27] Starting 'vscode-win32-x64'...
Error: tunneling socket could not be established, cause=socket hang up
    at ClientRequest.onError (D:\github\vscode-new\vscode\node_modules\gulp-remote-src\node_modules\tunnel-agent\index.js:180:17)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at Socket.socketOnEnd (_http_client.js:437:9)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**The error seems to be related with my proxy. 
But I can download node modules in the step 2. Also I can build and package from the v1.23.1 source code.**

Can someone help me to figure it out?

**Comment by joaomoreno** [comment]
Just try again later.

**Comment by chongchai** [comment]
@joaomoreno   I have tried several times. But each time fails with that same error. My proxy should be ok to download, That' weird.


I changed a dependency in package.json, then I can run package successfully.

My modification:
change `"keytar": "4.2.1"` to `"keytar": "4.0.5"`  
update the yarn.lock file

But is anything will be incorrect since I use an old version keytar?

**Comment by joaomoreno** [comment]
Probably not. Can you figure out why changing the version actually fixes it?

**Comment by chongchai** [comment]
@joaomoreno I find v4.2.1 keytar has more prebuild-install dependency in yarn.lock compared with v4.0.5 keytar. I guess the tunnel-agent package in deps cause the weird proxy error.

VScode 1.25.1 yarn.lock is here 
```
keytar@4.2.1:
  version "4.2.1"
  resolved "https://registry.yarnpkg.com/keytar/-/keytar-4.2.1.tgz#8a06a6577fdf6373e0aa6b112277e63dec77fd12"
  dependencies:
    nan "2.8.0"
    prebuild-install "^2.4.1"

prebuild-install@^2.4.1:
  version "2.5.3"
  resolved "https://registry.yarnpkg.com/prebuild-install/-/prebuild-install-2.5.3.tgz#9f65f242782d370296353710e9bc843490c19f69"
  dependencies:
    detect-libc "^1.0.3"
    expand-template "^1.0.2"
    github-from-package "0.0.0"
    minimist "^1.2.0"
    mkdirp "^0.5.1"
    node-abi "^2.2.0"
    noop-logger "^0.1.1"
    npmlog "^4.0.1"
    os-homedir "^1.0.1"
    pump "^2.0.1"
    rc "^1.1.6"
    simple-get "^2.7.0"
    tar-fs "^1.13.0"
    tunnel-agent "^0.6.0"
    which-pm-runs "^1.0.0"
```
