### ISSUE TITLE
File-Exporer isn't showing all files, if they have the same name

### ISSUE THREAD

**Issue by Maqsyo** [Microsoft/vscode#56129]
- VSCode Version: 1.25.1
- OS Version: Windows 10.0.17134

Steps to Reproduce:

1. And files to on directory with the same name, but different letter-casing
2. Only one file is shown in VS-File-explorer

![image](https://user-images.githubusercontent.com/19644698/43940083-4fc256d4-9c6e-11e8-961b-7abe9ea8116a.png)

![image](https://user-images.githubusercontent.com/19644698/43940093-569ae142-9c6e-11e8-8c04-ae388b906594.png)

The Main.js was created accidently, but isn't shown anywhere in vs-code

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@Maqsyo how do you manage to have different file casing on Windows, is this a specially formatted drive?

**Comment by Maqsyo** [comment]
It was just luck :D
i've created a main.js on my own, but the phaser-editor created the Main.js in the same folder. I think it's the fault of java

**Comment by bpasero** [comment]
@Maqsyo a normal windows filesystem (NTFS) does imho not allow to create the same file with different casing on disk, that is why I was wondering. At least it is very uncommon to have this on Windows where most tools assume this does not happen.

VSCode is not supporting same-file-different-case on any OS but Linux where this is standard.

**Comment by ramya-rao-a** [comment]
Closing this issue as there is nothing to be done from our side as per @bpasero's comment above.
