### ISSUE TITLE
Add the go to definition feature for extensions within vs code

### ISSUE THREAD

**Issue by basicdevomar** [Microsoft/vscode#56130]
A go to definition option for the C++ extension

**Comment by ramya-rao-a** [comment]
Only a handful of built-in extensions (js, ts, css, html, json) have language features more than the basic syntax highlighting. C++ is not one of them. Please install the [C++ extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools) from the marketplace
