### ISSUE TITLE
Once start debugging failed, it cannot start again

### ISSUE THREAD

**Issue by coderdreamworld** [Microsoft/vscode#56136]
Issue Type: <b>Bug</b>

Sometimes i write some wrong code, when start debugging it shows "Process exiting with code: 1". After that, i cant start debugging again, it always says "there is already a debug configuration running".  Even if i click stop, it does not really stop.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.96GB (3.42GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.25.3
Go|ms-|0.6.85

(1 theme extensions excluded)

</details>

**Comment by weinand** [comment]
I've seen this too.

**Comment by isidorn** [comment]
@coderdreamworld @weinand @bwilcutt can you please give me some precise reproducable steps so I start investigating what is the issue here.

Since this is already present in stable there is no need to fix this for the recovery, so August milestone is good.

**Comment by spiskula** [comment]
I seem to be hitting the same error, but when trying to debug GO language. Dont have much experience with VS Code so I followed https://rominirani.com/setup-go-development-environment-with-visual-studio-code-7ea5d643a51a.

I can run my script only one with the debugger. Upon second click on the green DEBUG arrow i get:
![image](https://user-images.githubusercontent.com/6223455/44032836-4b3db0ba-9f00-11e8-8124-aee1c7854888.png)

'There is already a debug configuration "Launch" running.'

**Comment by isidorn** [comment]
There was a large refactoring in debug how we handle sessions.
I tried reproducing the issue described with the following code sample and I could not

```javascript
process.exit(1);
console.log('hello there');
```

@coderdreamworld @weinand @bwilcutt So please try the latest insiders and let me know if you still see the original issue so I can reopen this. Thanks a lot

**Comment by isidorn** [comment]
Also might be a duplicate of https://github.com/Microsoft/vscode/issues/57255

**Comment by isidorn** [comment]
@juristr thanks a lot, I was not bobbling up the error properly, this should be fixed in latest out of source and you can verify in tomorrow's vscode insiders - thanks a lot!

**Comment by juristr** [comment]
@isidorn You guys rock 😄, didn't expect such a fast response

**Comment by isidorn** [comment]
Thanks, if the issue is good we tend to fix fast. Just let me know once you get the update if it is good for you so I can verify it.

**Comment by isidorn** [comment]
@juristr just a friednly reminder if you can verify this is good now, thanks a lot

**Comment by alexr00** [comment]
@isidorn For verification: Is there a good way to force the state that causes this to happen so I can make sure it doesn't happen?

**Comment by juristr** [comment]
@isidorn Just wanted to check whether the bug is fixed, but I'm getting a strange error now when running the exact same `launch.json` configuration I posted above 🤔 

![image](https://user-images.githubusercontent.com/542458/46272941-ae2de180-c553-11e8-8969-d3d324ab2d32.png)

**Comment by isidorn** [comment]
@juristr that sounds like an unrelated issue which has something to do with source maps.  fyi @roblourens 
@alexr00 no need to verify this one, since Sandeep verified the issue which this is a duplicate off https://github.com/Microsoft/vscode/issues/59331
Removing bug label, sorry for not doing that earlier
