### ISSUE TITLE
Viewlet badges glitches

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#56133]
Saw this while installing an extension from a VSIX:

<img width="147" alt="screen shot 2018-08-10 at 09 35 59" src="https://user-images.githubusercontent.com/22350/43944930-f095962c-9c80-11e8-9b9e-7b90f2869017.png">

cc @bpasero @sbatten

**Comment by bpasero** [comment]
This is another UI glitch that I tried to fix but failed. I am quite sure Electron 3.0.x will fix this.

**Comment by bpasero** [comment]
Closing this issue given that we plan to release VSCode stable early February with Electron 3.x. If you want to benefit from the fix already, consider to use our insiders version that already contains the fix: https://code.visualstudio.com/insiders/

**Comment by joaomoreno** [comment]
@bpasero Wow thanks, will definitely give Insiders a try!

**Comment by bpasero** [comment]
@joaomoreno yeah, that makes a huge difference!

Me:
![image](https://user-images.githubusercontent.com/900690/51759152-e4293f80-20c7-11e9-8886-d5b1605af053.png)

You:
![image](https://user-images.githubusercontent.com/900690/51759163-e8edf380-20c7-11e9-84e0-2fc9f6de55e2.png)

**Comment by isidorn** [comment]
Purple looks good on you maybe you should wear it more in public.

**Comment by bpasero** [comment]
@isidorn yeah I feel a lot like an empty workspace sometimes

**Comment by joaomoreno** [comment]
You must've missed something :thinking: 

![51759152-e4293f80-20c7-11e9-8886-d5b1605af053 1](https://user-images.githubusercontent.com/22350/51759527-b42e6c00-20c8-11e9-8304-939d213b4328.png)

**Comment by bpasero** [comment]
@joaomoreno nah, it is because you switched to insiders!
