### ISSUE TITLE
Line Numbers in Gutter off-centered

### ISSUE THREAD

**Issue by beastdestroyer** [Microsoft/vscode#56145]
Issue Type: Polish

- VSCode Version: 1.26.0-insider
- OS Version: Windows 10 1803 v17134.191

Steps to Reproduce:

1. (Preferably) make your font size large, but you can see it without doing this
2. Put the cursor at the beginning of any line (preferably single digit so you can see it better)
3. Notice how off-centred the numbers are

From dev tools, I found that VSCode was really using lots of ```position: absolute; ```, left, top etc. But after putting one line of CSS, it worked. In order to see what I mean, open dev tools and inspect element, go over to the line number (not the row of the number, the text itself) and click it. You'll see in element.style, it says left: blah blah and  with: blah blah. Adding a ```text-align: center;``` basically corrects the issue. Perhaps add this into the global ```.monaco-editor .margin-view-overlays .line-numbers``` to correct forever.

If it was intended, then I rest my case, it just bothered me after I noticed it :>

Does this issue occur when all extensions are disabled?: Yes (Not relevant to them however)

**Comment by beastdestroyer** [comment]
> (Experimental duplicate detection)
Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> - Allow folding block comment that starts in the middle of the line (#42287)

Irrelevant.

**Comment by ramya-rao-a** [comment]
I dont see the line numbers being off center. Can you share a screenshot?
