### ISSUE TITLE
Seti file icon theme: support more "todo" files

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#56143]
_Should I have opened this issue on https://github.com/jesseweed/seti-ui instead?_

There's already a custom file icon for files named `TODO`, I think the same icon should be used for these other files, which are supported by [Todo+](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-todo-plus) and other extensions, as well:

- `todolist.txt`
- `*.todo`
- `*.todos`
- `*.task`
- `*.tasks`
- `*.taskpaper`

**Comment by aeschli** [comment]
Yes, this needs to be filed against https://github.com/jesseweed/seti-ui (we generate the vscode seti theme from there)

**Comment by aeschli** [comment]
Oh, I see you define a `todo` language. I can assign the seti `todo` icon to the `todo` language.

**Comment by fabiospampinato** [comment]
That would be great, thank you.

**Comment by jrieken** [comment]
Using Seti and the Todo+ extension I still get the default icon

<img width="586" alt="screen shot 2018-08-28 at 16 47 03" src="https://user-images.githubusercontent.com/1794099/44730754-f20b7200-aae1-11e8-9479-ad47fa3dfef7.png">

**Comment by fabiospampinato** [comment]
It's working for me on v1.27.0 👍 

<img width="294" alt="screen shot 2018-09-06 at 22 09 38" src="https://user-images.githubusercontent.com/1812093/45182462-9186de00-b221-11e8-8536-0b856566a6c9.png">

**Comment by aeschli** [comment]
Thanks, marking as verified.
