### ISSUE TITLE
Travando

### ISSUE THREAD

**Issue by simonLuis** [Microsoft/vscode#56147]
Issue Type: <b>Bug</b>

Olá o meu vs code está travando, quando vou digitar um código ele trava.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.15063

**Comment by ramya-rao-a** [comment]
Google translation:

> Hello my vs code is crashing, when I go to type a code it crashes.

**Comment by ramya-rao-a** [comment]
Do you see the same when extensions are disabled? Close all VS Code windows. Run `code --disable-extensions` from the terminal
