### ISSUE TITLE
Autocomplete stop working with accents

### ISSUE THREAD

**Issue by rodrigojcmello** [Microsoft/vscode#56150]
- VSCode Version: 1.25.1
- OS Version: macOS High Sierra 10.13.6

Steps to Reproduce:

1. In a js / jsx file, write some method with accent
`const teste = {
    testéste: 1
}`
2. Try autocomplete this
`teste.test`
3. Accents stop the autocomplete

Starting autcomplete
<img width="535" alt="captura de tela 2018-08-10 as 09 51 10" src="https://user-images.githubusercontent.com/5174526/43959135-2e2ee954-9c84-11e8-8ef6-10223aadf6ae.png">

After accent
<img width="567" alt="captura de tela 2018-08-10 as 09 51 23" src="https://user-images.githubusercontent.com/5174526/43959162-42ac1fa0-9c84-11e8-8354-2b555abe5126.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by ramya-rao-a** [comment]
@jrieken This is related to filtering the suggestions.

**Comment by jrieken** [comment]
@rodrigojcmello How do you enter the `é`?

**Comment by rodrigojcmello** [comment]
@jrieken ' + e (our macbook keyboard in Brazil is equal US keyboard)

**Comment by jrieken** [comment]
Ok, thanks. It's like pressing Alt+e and then e on the US mac keyboard. This happens because the suggestions are filtered again `test´` already. We should wait for the composition to be completed first.

**Comment by rodrigojcmello** [comment]
@jrieken The issue has been resolved, but because of some more recent update the problem has returned.

**Comment by ramya-rao-a** [comment]
@rodrigojcmello I don't see the issue in either the latest stable (1.27.2) or the latest insiders. What version are you using?

**Comment by rodrigojcmello** [comment]
@ramya-rao-a I am on 1.27.2, I deactivated all extensions and the problem persisted, I uninstalled, rebooted the MacBook and reinstalled without any extension and the problem persisted. I tested Windows 10 also build 1.27.2 and there autocompletion works normally. The problem is apparently to wait for the accent on OSX. I remember testing it as soon as the build came out with this fix (1.27.1?) And everything was fine, but by upgrading to the latest build I realized that the problem had returned.
![autocomplete-accent-osx](https://user-images.githubusercontent.com/5174526/45923108-30af0500-beb3-11e8-80c8-0cfe2dedc899.png)

**Comment by ramya-rao-a** [comment]
> The problem is apparently to wait for the accent on OSX.

Can you elaborate on this?

Also, you can get the older 1.26.1 version from https://code.visualstudio.com/updates/v1_26. Can you try that to confirm that the problem was indeed fixed in 1.26.1 for you?
