### ISSUE TITLE
'Other files' search results node should not have an empty uri

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#56154]
https://github.com/Microsoft/vscode/blob/c8ac8ec30096bdabf1041fd0bdf271d02e3ed4ab/src/vs/workbench/parts/search/common/searchModel.ts#L542

Either give it at least a scheme, like `URI.from({scheme: 'empty'})`

Or try to refactor so that it doesn't need a URI at all.

**Comment by isidorn** [comment]
Verified that uri.parse('') got removed by code review
