### ISSUE TITLE
Context menu looks huge in standalone editor

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#56151]
* before (former editor release from April):
![image](https://user-images.githubusercontent.com/5047891/43960743-3eb61700-9cb3-11e8-8b99-8736fb22aa0c.png)

* now:
![image](https://user-images.githubusercontent.com/5047891/43960787-686f3e00-9cb3-11e8-950d-a67577f50808.png)

**Comment by alexandrudima** [comment]
Also, the context menu is no longer accessible. Focus does not appear to be set on the context menu and there is no highlight to make it keyboard accessible.

See https://github.com/Microsoft/monaco-editor/issues/439 and https://github.com/Microsoft/monaco-editor/issues/428

**Comment by rebornix** [comment]
Comparing 0.13.1 and 0.14.x, there are several things we need to change to make it consistent. 

* The first item in the context menu is not pre-selected/focused when being opened. (but there is a bug https://github.com/Microsoft/monaco-editor/issues/997)
* Font size
* Text color when focus/selected
* Line height

0.13.1

<img width="261" alt="image" src="https://user-images.githubusercontent.com/876920/43972537-8ea687d8-9c89-11e8-968b-d445a8378a63.png">

0.14.4 (from standalone/0.14.x) 

<img width="346" alt="image" src="https://user-images.githubusercontent.com/876920/43972636-e5b82a2c-9c89-11e8-8469-0640c9a3c447.png">

**Comment by sbatten** [comment]
Updated the css to correct sizing and colorization. The menus were changed a bit this milestone to act more like system menus uniform across OS. One behavior that is consistent is showing the menus without selecting the first item. Using the arrow keys will show focus correctly with color now.
