### ISSUE TITLE
C# Folding using directives

### ISSUE THREAD

**Issue by E4N** [Microsoft/vscode#56161]
On Visual Studio you are able to collapse using directives but it's not the case on Code for some reasons. Could this be addressed please?

![sans titre](https://user-images.githubusercontent.com/28897199/43970786-fa3d027a-9cce-11e8-8659-461f9ef1611a.png)

**Comment by aeschli** [comment]
This needs to be provided by a c# language service, e.g. omnisharp-vscode: Covered by https://github.com/OmniSharp/omnisharp-vscode/issues/2335
