### ISSUE TITLE
console.log items are not showing up in Output channel

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#56169]
- Clone https://github.com/octref/vscode-language-server-template
- Run `yarn` in `/` and `/server` in terminal
- Run `yarn compile` in terminal
- Run `client` to debug the instance
- Open markdown file, make changes

Problems:

- With 1.25, Output channel shows `console.log` output in this file https://github.com/octref/vscode-language-server-template/blob/master/server/serverMain.ts
- With 1.26 Insider, Output channel doesn't show any `console.log` from Language Server

**Comment by dbaeumer** [comment]
I have the feeling this is related to the Electron update. If I use a normal node runtime for running the server everything works as expected.

**Comment by dbaeumer** [comment]
@bpasero the item we discussed shortly.

**Comment by bpasero** [comment]
@octref @dbaeumer can you see if this changed again with Electron 3.0.x, find builds to download (Exploration) here: https://github.com/Microsoft/vscode/pull/56149#issue-207603624

**Comment by octref** [comment]
@bpasero Still nothing. I'm using IPC as the release notes instructued.

**Comment by bpasero** [comment]
Yeah we figured that our workaround for former broken behaviour should be removed.

**Comment by dbaeumer** [comment]
I fixed this by publishing new version of the LSP libraries (5.0.0) which work again with Electron 2.x
