### ISSUE TITLE
Closing unsaved file from provided file system does not trigger a save prompt

### ISSUE THREAD

**Issue by bolinfest** [Microsoft/vscode#56162]
- VSCode Version: Insiders 2018-08-07T07:40:50.417Z
- OS Version: macOS

Steps to Reproduce:

1. Register a custom file system via `vscode.workspace.registerFileSystemProvider()`.
2. Open a file from that file system and edit it (but do not save). Not the icon in the tab changes to show there is unsaved content.
3. Close the tab. There is no prompt to check if you want to save the file before closing the tab. This is expected since that's what happens with local files.

Does this issue occur when all extensions are disabled?: Yes/No

You need to create an extension to have a provided file system.

**Comment by bpasero** [comment]
@bolinfest are you reproducing this when running the extension out of VSCode in the debugger? We have some special setup when doing so where we allow to close a dirty editor without prompt for various reasons (e.g. allow us to run tests without dialogs popping up).

**Comment by bolinfest** [comment]
@bpasero This is when launching Insiders from the command line with the `--extensionDevelopmentPath` flag, pointing to my extension that registers the custom file system provider.

**Comment by bpasero** [comment]
Yes, this is as designed to prevent dialogs blocking our tests. It will not happen in production.
