### ISSUE TITLE
Support bundling custom fonts with Themes

### ISSUE THREAD

**Issue by beriberikix** [Microsoft/vscode#56172]
As a Theme creator, it would be nice to bundle a specific font with a Theme. I do not want to assume that the user already has the font installed on their machine or require them to manually install it.

I can imagine it working like [Font Definitions](https://code.visualstudio.com/docs/extensions/themes-snippets-colorizers#_font-definitions) or [`@font-face`](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face).

As far as I can tell, this is not currently possible. Would supporting bundling custom fonts with Themes be considered?

**Comment by octref** [comment]
Once you have #26128 you can do it.
