### ISSUE TITLE
Doc Bug: Progress.report() Parameter missing definition

### ISSUE THREAD

**Issue by beriberikix** [Microsoft/vscode#56178]
https://code.visualstudio.com/docs/extensionAPI/vscode-api#Progress

The Extension API docs mentions Progress.report but doesn't provide details on what parameters should be passed. It just says, "value: T | A progress item, like a message and/or an report on how much work finished."

Can you provide more details about what a Progress Item can be?

**Comment by jrieken** [comment]
It's a generic type and is defined by the usages of `Progress` not by the interface itself. It might be `Progress<string>` or `Progress<{total: number, worked:number}>` etc. Refer to the usages, not the definition.

**Comment by beriberikix** [comment]
Thanks @jrieken! Is the Slack community new? Heading over there now.

**Comment by jrieken** [comment]
see here: https://github.com/Microsoft/vscode/wiki/Feedback-Channels
