### ISSUE TITLE
--install-extension CLI doesn't work under Electron 3

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#56171]
#52629

```
❯ code-exploration --install-extension cssho.vscode-svgviewer
(node:67029) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Found 'cssho.vscode-svgviewer' in the marketplace.
Installing...
```

It just sits on Installing...

**Comment by bpasero** [comment]
Good catch, this could be a regression from my stream change.

**Comment by bpasero** [comment]
@Tyriar seems to work for me can you try again with a later build? Are you on macOS?

![image](https://user-images.githubusercontent.com/900690/43992022-51ea334a-9d78-11e8-863e-d0a9dd9c85b4.png)

**Comment by Tyriar** [comment]
@bpasero yes macOS, will try again

**Comment by Tyriar** [comment]
Seems to be working on latest :+1:
