### ISSUE TITLE
"Small perf tweaks" commit 79eda2ea breaks float preference values

### ISSUE THREAD

**Issue by rob3c** [Microsoft/vscode#5618]
Hi all,

I prefer the mouse wheel to scroll single lines in VS Code, and happily, there's a separate configuration setting to control this without disturbing my global system settings. When `editor.mouseWheelScrollSensitivity` is set to its default value of `1`, the mouse wheel on my system scrolls 3 lines, but by setting it to `0.33` - at least, in previous versions of VS Code - I got the desired behavior of single line scrolling.

Unfortunately, the seemingly innocuous "small perf tweaks" commit https://github.com/Microsoft/vscode/pull/4752/commits/79eda2eaefa014dc2d79c73fa66bf44c59213e0c from a few weeks ago introduced some regressions, one of which is to truncate float values due to the adding of `|0` after every numerical preference value assignment, including `editor.mouseWheelScrollSensitivity`.

Please consider fixing this and restoring the previous behavior. Thanks!

- VSCode Version: 1.0.1-insider
- OS Version: Windows 8

Steps to Reproduce:

1. Set, for example, `"editor.mouseWheelScrollSensitivity": 0.33` in user or workspace preferences.
2. Watch your mouse scroll wheel have no effect due to its value being changed to `0`.

**Comment by alexandrudima** [comment]
Thank you for the heads up!

**Comment by alexandrudima** [comment]
Please verify by reviewing the change
