### ISSUE TITLE
Automatically show and hide explorer, search, etc. pane on mouseover

### ISSUE THREAD

**Issue by rben01** [Microsoft/vscode#56187]
It would be nice if the left pane could be hidden but be revealed on mouseover, and then hide again when the mouse left the left pane. So instead of having the pane always visible or always hidden as it is now, moving your mouse over one of the icons would reveal the corresponding pane (e.g., mouseover the explorer icon would reveal the explorer pane), which would remain visible until your mouse was no longer over the pane. This way, the pane would be immediately visible when desired and would immediately hide when no longer desired, which would be superior to the current method of clicking to toggle.

**Comment by rben01** [comment]
Come on bot, at least give me the link to the issue that this is a duplicate of...

**Comment by misolori** [comment]
Duplicate of #53689
