### ISSUE TITLE
The file is reopened after the hyperlink is clicked

### ISSUE THREAD

**Issue by tiansin** [Microsoft/vscode#56184]
- VSCode Version: 1.25.1
- OS Version: Win10

Steps to Reproduce:

![ac](https://user-images.githubusercontent.com/4232281/43987380-62ddd6fa-9d52-11e8-9af0-6c5b4414f971.gif)

Does this issue occur when all extensions are disabled?: Yes

@ramya-rao-a 
Why does the same path file open two tabs, and the hyperlink in the second document switches back to the first one?

**Comment by ramya-rao-a** [comment]
There is a difference is casing in the path of the file opened in the 2 editors.
The link must be using the path with lower case which corresponds to the first editor, and so the jump.

@bpasero In the file quick open, the top 2 files are the same with the difference in casing.
How does one end up in such a case?

**Comment by tiansin** [comment]
@ramya-rao-a 
I may know what is the reason for this.
Only valid under Windows, because the path is not case sensitive.

tsconfig.json
`    "baseUrl": "./", 
    "paths": {
        "*": [
            "src/app/Services/*",
        ]
    },`

I found that there is such a piece of code. The first character uses lowercase letters, the actual path is uppercase letters.
`import { xxx } from "public/xxx";`
It may be that I accidentally used a hyperlink to enter the path at the beginning of this lowercase letter, so that vscode remembers the path.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/12448
