### ISSUE TITLE
Markdown link formatting override

### ISSUE THREAD

**Issue by sujan-s** [Microsoft/vscode#56188]
- VSCode Version: 1.25.1
- OS Version: MacOS High Sierra 10.13.6

<img width="284" alt="screen shot 2018-08-11 at 8 46 39 am" src="https://user-images.githubusercontent.com/19920532/43988326-f79c4a12-9d50-11e8-9f62-6304275cb830.png">

Markdown link formatting is lost when parentheses URL is added. It’d be great to keep the inline formatting within a link text. Is there any way to do this?

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/vscode-markdown-tm-grammar#25
