### ISSUE TITLE
Add "suspend work space" - Saving memory when opening lot's of work space.

### ISSUE THREAD

**Issue by MichelDiz** [Microsoft/vscode#56180]
The idea is very simple to suspend and summarize. Just as many extensions do in Chrome. Having options such as timer or "fixed" (not suspend) and etc.

arg:
 
Using HTOP, I noticed that there are many instances from Electron running. Consuming significant memory. My intention is to keep the workspaces, however it is not at all times that I am coding. Then consumption becomes unnecessary. And I would not like to close the Visual Code and then reopen it and rearrange the Spaces (Darwin).

**Comment by MichelDiz** [comment]
Hey bot, it's not duplicated. U.U

**Comment by bpasero** [comment]
I think this is https://github.com/Microsoft/vscode/issues/43115

**Comment by MichelDiz** [comment]
@bpasero No it's, not. Did you at least read and interpret my post?
The proposal is similar but the approach and concept is completely different.

 It's most like theses extensions:

https://chrome.google.com/webstore/detail/tab-suspender/fiabciakcmgepblmdkmemdbbkilneeeh
and
https://chrome.google.com/webstore/detail/the-great-discarder/jlipbpadkjcklpeiajndiijbeieicbdh
