### ISSUE TITLE
Quick open doesn't prioritize exact matches

### ISSUE THREAD

**Issue by TheDutchCoder** [Microsoft/vscode#56182]
Issue Type: <b>Bug</b>

When using Command+P and pasting in a file name, VScode doesn't always prioritize the exact match, but will sometimes list the last opened file as the first option.

Example:
Pasting "NewOrderTest" will first match "NewOrdersTest.php" and second "NewOrderTest.php".

I don't think this is correct and it's quite anooying at times.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (2.64GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|8.0.0
vscode-eslint|dba|1.4.12
vsc-material-theme|Equ|2.3.0
docthis|joe|0.7.1
node-debug2|ms-|1.26.8
vetur|oct|0.12.6
gitpatch|par|0.2.1
vscode-docker|Pet|0.1.0
material-icon-theme|PKi|3.5.2
vscode-coverage-gutters|rya|2.1.1
vscode-react-native|vsm|0.6.13
vscode-import-cost|wix|2.8.0

(4 theme extensions excluded)

</details>

**Comment by ramya-rao-a** [comment]
This is because we prioritize recently used text. Try setting `workbench.commandPalette.history` to 0 in your settings if you don't want this feature
