### ISSUE TITLE
Latin chars

### ISSUE THREAD

**Issue by jssmttgit** [Microsoft/vscode#5619]
The VS Code do not respect latin chars.

- VSCode Version: Last
- OS Version: Win 10 x64

Steps to Reproduce:

1. Open and type ç, ã, á

**Comment by dbaeumer** [comment]
@jssmttgit can you please provide more details. May be a screen cast about what you see. I have no problems entering latin characters like èüéöäà

**Comment by jssmttgit** [comment]
Hi,
when I do open the file it do not goes to ISO-8859-1.

![utf-8](https://cloud.githubusercontent.com/assets/18600109/14745638/953c15ce-0882-11e6-8e69-e3e897bf962d.PNG)

**Comment by jssmttgit** [comment]
Would be greate to set a default char codification.

**Comment by dbaeumer** [comment]
You can: the setting is "files.encoding" and it defaults to utf8. What does the status line say about the encoding of the file
![capture](https://cloud.githubusercontent.com/assets/1931590/14745914/971d3c3a-08ad-11e6-90cf-fb28419e15c2.png)

**Comment by jssmttgit** [comment]
Thanks for your reply.

Yes, I do change, but it does not save this option for the next time, I look out for change settings but do not found where do I set default encoding.

**Comment by bpasero** [comment]
You can change this globally or per workspace in settings (F1 > open global settings, F1 > open workspace settings). there are other issues opened to allow to persist this setting per file.
