### ISSUE TITLE
Highly CPU Usage

### ISSUE THREAD

**Issue by MarcwL22** [Microsoft/vscode#56197]
Hi, since the last update the vscode become unusable. The moment I open the editor, the cpu goes to 100%, and the intellisense does not work anymore.
I'm starting with code --disable-extensions
Here is the output of the code --status

Version:          Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS Version:       Darwin x64 17.7.0
CPUs:             Intel(R) Core(TM) i5-2435M CPU @ 2.40GHz (4 x 2400)
Memory (System):  16.00GB (0.95GB free)
Load (avg):       9, 7, 5
VM:               0%
Screen Reader:    no
Process Argv:     /Applications/Visual Studio Code.app/Contents/MacOS/Electron --disable-extensions
GPU Status:       2d_canvas:                    unavailable_software
                  flash_3d:                     unavailable_software
                  flash_stage3d:                unavailable_software
                  flash_stage3d_baseline:       unavailable_software
                  gpu_compositing:              unavailable_software
                  multiple_raster_threads:      unavailable_off
                  native_gpu_memory_buffers:    unavailable_software
                  rasterization:                unavailable_software
                  video_decode:                 unavailable_software
                  video_encode:                 unavailable_software
                  vpx_decode:                   unavailable_software
                  webgl:                        unavailable_off
                  webgl2:                       unavailable_off

CPU %	Mem MB	   PID	Process
    1	   131	 52649	code main
    0	   262	 52658	   window (MapPage.js — talherApp)
    0	    66	 52662	     extensionHost
   91	   180	 52666	       electron_node electronForkStart.js tsserver.js
    0	    66	 52679	         electron_node typingsInstaller.js tsserver.js typesMap.js
    0	    49	 52663	     watcherService
    0	    66	 52664	   shared-process
    3	    66	 52694	   window (Process Explorer)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?
