### ISSUE TITLE
Parse error on line 1: Expecting 'STRING'

### ISSUE THREAD

**Issue by joshpeng** [Microsoft/vscode#56193]
- VSCode Version: 1.25.1
- OS Version: Win10 also MacOS

Steps to Reproduce:

1. Seemingly randomly on file open, I run into this error on both Windows and Mac when there is nothing wrong with the code. I've ran into it on at least both Python and HTML files.
![image](https://user-images.githubusercontent.com/22549127/43990466-e0cf92a2-9d10-11e8-828d-2e8ff3c92520.png)

**Comment by aeschli** [comment]
The built-in HTML support does not validate. The error must be generated by an extension. Please file the issue there.
But if you ask me, the validator is likely right as this is not proper HTML syntax, try https://validator.w3.org/check.

**Comment by joshpeng** [comment]
@aeschli Thanks. I get these kinds of errors on all kinds of files, not even just HTML. Is there some way to tell which extension is causing that error? If I restart VSC, the error will usually disappear and seemingly reappear in another file on another random line for unknown reasons.
