### ISSUE TITLE
no syntax highlighting for custom user defined types/classes

### ISSUE THREAD

**Issue by Blaze23** [Microsoft/vscode#56198]
Issue Type: <b>Bug</b>

in c++ i can create classes and structs but when i make objects out of those classes, the user defined class types are not highlighted like they are in visual studio. please fix

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
gnuplot|mam|1.0.4
cpptools|ms-|0.17.7

</details>

**Comment by ramya-rao-a** [comment]
Isnt this already covered in your other issue #56199?

**Comment by sandy081** [comment]
Duplicate of #56199
