### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by tsangint** [Microsoft/vscode#56194]
- VSCode Version: code at git master(commitid:03cfde3d68b9c4a3139c7e3725755d35b4527437)
- OS Version:OSX

Steps to Reproduce:

1.git clone https://github.com/Microsoft/vscode.git
2.cd vscode
3.yarn
4.yarn run watch

[19:01:47] Starting 'watch-extension:html-language-features-server'...
[19:01:52] Finished 'clean-client' after 12 s
[19:01:52] Starting 'watch-client'...

<--- Last few GCs --->

[79760:0x103000600]   109585 ms: Scavenge 1361.2 (1422.8) -> 1360.3 (1423.3) MB, 4.3 / 0.0 ms  (average mu = 0.343, current mu = 0.330) allocation failure
[79760:0x103000600]   109609 ms: Scavenge 1361.3 (1423.3) -> 1360.4 (1423.8) MB, 7.8 / 0.0 ms  (average mu = 0.343, current mu = 0.330) allocation failure
[79760:0x103000600]   109637 ms: Scavenge 1361.5 (1423.8) -> 1361.1 (1424.3) MB, 5.7 / 0.0 ms  (average mu = 0.343, current mu = 0.330) allocation failure

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x57bff6041bd]
    1: StubFrame [pc: 0x57bff607c1a]
Security context: 0xca5c51e6c9 <JSObject>
    2: encodeLastRecordedSourceMapSpan(aka encodeLastRecordedSourceMapSpan) [0xca46b94291] [/Users/alfredtsang/Documents/git/vscode/node_modules/typescript/lib/typescript.js:~73796] [pc=0x57c017788d3](this=0xcae57022e1 <undefined>)
    3: emitPos(aka emitPos) [0xca46bb9a91] [/Users/alfredtsang/Documents/git/vscode/node_modul...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x100033c31 node::Abort() [/usr/local/bin/node]
 2: 0x1000353ea node::FatalTryCatch::~FatalTryCatch() [/usr/local/bin/node]
 3: 0x10019bc9a v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x10056a072 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 5: 0x100569029 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 6: 0x100566cb8 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 7: 0x1005731fc v8::internal::Heap::AllocateRawWithRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 8: 0x100541b94 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/usr/local/bin/node]
 9: 0x1007cb394 v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
10: 0x57bff6041bd
error Command failed with signal "SIGABRT".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by velechva** [comment]
+1

Getting the same error recently on an 8GB 2013 MBP. Activity monitor shows plenty of free memory while the build is running. If I understand correctly, the V8 engine is running out of memory.

I tried increasing the value of the --max_old_space_size=8190 flag everywhere in package.json but that didn't work either.

**Comment by tsangint** [comment]
@velechva I found the reason now,It's because my NodeJS version(10.5) not match the required versions(>= 8.9.1, < 9.0.0).You can install a NodeJS which version is  >= 8.9.1, < 9.0.0 and try again.

**Comment by joaomoreno** [comment]
Thanks for the update @tsangint.

It's already documented in the wiki: https://github.com/Microsoft/vscode/wiki/How-to-Contribute#prerequisites
