### ISSUE TITLE
Search stops if focus goes away from the app

### ISSUE THREAD

**Issue by pcherkasova** [Microsoft/vscode#56196]
When I press Ctrl + P and enter name of file, if my folder is very large, search can take a while. I'd like to do something else while search is going on. But, if I move focus away from VS Code, it stops searching.

 

- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
You can set `"workbench.quickOpen.closeOnFocusLost": false`
