### ISSUE TITLE
Outline Window with optional states and buttons for plugin devs

### ISSUE THREAD

**Issue by rand99** [Microsoft/vscode#56202]
The outline window could be used as an UI for the tests.
It would be great if the Outline-window could get buttons next to the functions (run/debug).
The states (FAIL/PASS) of the tests would also be great!

Example for Golang:
![Image of Outline as a test ui](https://user-images.githubusercontent.com/460223/43460360-ae02f1c2-94d0-11e8-99ec-0f20e1e54ed6.png)

**Comment by rand99** [comment]
@jrieken: I'm not sure what you mean.
As an inspiration here is a quite elegant solution.
https://mindart.de/ide_tests.mp4

So outline tree items would need the provide methods for plugin developers like ramya-rao to change the icon and maybe add a drop down that could be filled with commands like test, debug test, test with coverage.  or the possibility to add buttons next to the items. 
when working on a test it would be pretty convenient to be able to re-debug it via the outline window and quickly see and navigate to failed tests.

The possibility of buttons next to a function with drop down as in the video is also pretty cool.
Currently when working with go there are page jumps because text links are added above the function (run test, debug test).

**Comment by jrieken** [comment]
> The outline window could be used as an UI for the tests.

Seeing this only now. The outline view shouldn't be used for a test runner UI. We have API that allows extension authors to manage a tree and to react to commands on tree items.
