### ISSUE TITLE
Incorrect regex for windowsSdkVersion in c_cpp_properties.json

### ISSUE THREAD

**Issue by david-waterworth** [Microsoft/vscode#56208]
I'm not 100% sure if this is a vscode issue, or an extension

I've configured c_cpp_properties.json with the following

"windowsSdkVersion": "10.0.17134.12"

And the SDK version gets underlined - the regex it's applying seems to assume the last token (12) should be 1 character.

**Comment by ramya-rao-a** [comment]
That's coming from the C++ extension
