### ISSUE TITLE
For giving intuitive way of managing shortcut conflicts

### ISSUE THREAD

**Issue by akshat296** [Microsoft/vscode#56204]
Changing the way to manage shortcuts in vs code

**Comment by ramya-rao-a** [comment]
We do show the warning about conflicts if you use the keyboard shortcuts editor

![image](https://user-images.githubusercontent.com/16890566/43996042-3310a4da-9d6f-11e8-8697-7b7a18642b66.png)


But we dont show any warnings if you are editing the json file directly.

Are you referring to the keyboard shortcuts editor or the keyboard shortcuts json file?
