### ISSUE TITLE
Live Server bug

### ISSUE THREAD

**Issue by llama5476** [Microsoft/vscode#56206]
Issue Type: <b>Bug</b>

Half the time, live server works and half the time it doesn't. I tried shutting down VS code, reopening it and that didn't work. I uninstalled Live Server and re-installed it and that didn't work. I uninstalled VS code and re-installed it and that didn't work. Sometimes the "go live" icon appears, sometimes it doesn't.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3591)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (11.47GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.59
LiveServer|rit|5.1.1

</details>

**Comment by V-ed** [comment]
Please file an issue in the [extension's repository](https://github.com/ritwickdey/vscode-live-server) instead.

**Comment by ramya-rao-a** [comment]
Thanks @V-ed
