### ISSUE TITLE
Improvements to Keyboard Shortcut Reference

### ISSUE THREAD

**Issue by GandalfSaxe** [Microsoft/vscode#56218]
### Add missing shortcuts to macOS reference

To make the Keyboard Shortcut Reference PDF uniform across Windows / macOS, in heading "Search and replace", add `⌥⌘+C/R/W   Toggle case-sensitive / regex / whole word`.

### Place shortcut section in same order.

All the shortcut sections are ordered very differently across platforms. There is no reason for this, and would be easier to refer to if they're the same, especially when working on both platforms.

### Remove Change all / Select highlights
These two commands supposedly have almost the exact same functionality and implementation:
```
⌘F2 - Select all occurrences of current selection
⇧⌘L - Select all occurrences of current word
```
I propose `⌘F2 - Select all occurrences of current selection` should be removed from the reference. See https://github.com/Microsoft/vscode/issues/54954#issuecomment-408411740.

### Many commands could be combined on fewer lines
For example in the macOS reference in "Basic editing":
```
⌥⇧[  /  ⌥⇧]   Fold/unfold region
```
In Windows it's:
```
Ctrl+Shift+[  Fold (collapse) region
Ctrl+Shift+]  Unfold (uncollapse) region
```

If this was homogenized across platform references, it would be much easier to look up things, and especially when working regularly on multiple platforms.

**Comment by gregvanl** [comment]
This issue was moved to Microsoft/vscode-docs#1784
