### ISSUE TITLE
Intellisense: Importing a dependency from node_modules should not be prefixed by ../../node_modules

### ISSUE THREAD

**Issue by whizkidwwe1217** [Microsoft/vscode#56212]
Issue Type: <b>Bug</b>

Example: Create a typescript class and implement an interface from a third-party library. You will get a squiggly. Hit Ctrl + . to open up the intellisense and select the correct dependency to import it automatically. Issue: ../../node_modules should not be included in the import declaration.
Ex.: `import { Observable } from 'rxjs'` instead of `import { Observable } from '../../node_modules/rxjs'`

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.73GB (1.12GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Users\whizk\Documents\Projects\Web\Frameworks\Multitenancy\Final\ResearchAndDev\BlackFish|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.2.3
gitlens|eam|8.5.4
vscode-great-icons|emm|2.1.39
prettier-vscode|esb|1.6.1
vscode-todo-plus|fab|4.0.6
rest-client|hum|0.19.1
easy-icons|jam|0.3.1
mssql|ms-|1.4.0
sqlops-debug|ms-|1.1.0
csharp|ms-|1.15.2
debugger-for-chrome|msj|4.8.2
vscode-docker|Pet|0.1.0
material-icon-theme|PKi|3.5.2
LiveServer|rit|5.1.1

(4 theme extensions excluded)

</details>

**Comment by StevenLiekens** [comment]
I can confirm that absolute imports for node_modules have disappeared from the quickfix menu.

![image](https://user-images.githubusercontent.com/1583241/44029308-2119ee28-9efd-11e8-9f7f-6755d59e5326.png)

**Comment by blopez2010** [comment]
The auto import is not working as expected, for example, working on a project built in Angular 6, if I type `EventEmitter` and hit Enter, the dependency being imported is `selenium-webdriver` instead of `@angular/core` (Added or imported action)

**Comment by mjbvz** [comment]
This was fixed by TS 3.0.1 which is included in VSCode 1.26

**Comment by StevenLiekens** [comment]
Nice
