### ISSUE TITLE
Can't use mocha's dot reporter for extension tests

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#56211]
- `yo code`
- Change test runner so it uses mocha's `dot` reporter
- Observe no dot is shown after test completion

**Comment by bpasero** [comment]
@octref do you get any output? did it work with 1.25? what output do you get?

**Comment by octref** [comment]
1.25 has same behavior.

Default reporter output:

```
 test-dot > yarn test
yarn run v1.9.4
warning package.json: No license field
$ npm run compile && node ./node_modules/vscode/bin/test

> test-dot@0.0.1 compile /Users/octref/Code/test-dot
> tsc -p ./

### VS Code Extension Test Run ###
Current working directory: /Users/octref/Code/test-dot
Running extension tests: /Users/octref/Code/test-dot/.vscode-test/stable/Visual Studio Code.app/Contents/MacOS/Electron /Users/octref/Code/test-dot/out/test --extensionDevelopmentPath=/Users/octref/Code/test-dot --extensionTestsPath=/Users/octref/Code/test-dot/out/test
[main 8:07:02 AM] update#setState idle
stty: stdin isn't a terminal





  Extension Tests

    ✓ Something 1





  1 passing (5ms)



Tests exited with code: 0
✨  Done in 9.74s.
```

When I add `reporter: 'dot'`.

![image](https://user-images.githubusercontent.com/4033249/44217299-fc199200-a12b-11e8-9574-be035fbdc7bb.png)

```
 test-dot > yarn test
yarn run v1.9.4
warning package.json: No license field
$ npm run compile && node ./node_modules/vscode/bin/test

> test-dot@0.0.1 compile /Users/octref/Code/test-dot
> tsc -p ./

### VS Code Extension Test Run ###
Current working directory: /Users/octref/Code/test-dot
Running extension tests: /Users/octref/Code/test-dot/.vscode-test/stable/Visual Studio Code.app/Contents/MacOS/Electron /Users/octref/Code/test-dot/out/test --extensionDevelopmentPath=/Users/octref/Code/test-dot --extensionTestsPath=/Users/octref/Code/test-dot/out/test
[main 8:03:25 AM] update#setState idle

stty: stdin isn't a terminal





  1 passing (3ms)



Tests exited with code: 0
✨  Done in 10.61s.
```

When using mocha's `dot` reporter, it should show dot for each test:

```
 mocha-test > ./node_modules/.bin/mocha -R dot


  ․․․․․․․․․․․․․․․․․․․․

  20 passing (7ms)
```

**Comment by bpasero** [comment]
If someone has energy to look into this, PR welcome.

**Comment by bpasero** [comment]
Seems to be unrelated to our debug console, I can reproduce the same when running "npm run test" from the console. Probably an issue with the old mocha version we are using.

**Comment by octref** [comment]
Oh well, Mocha has inconsistent reporters.

- `spec` use `console.log`
- `dot`, `list` etc uses `process.stdout.write`
- When launching the test runner in the ext host, `process.stdout` is not available

Not sure if I should ask Mocha to fix on their side, do some change in the way to run test runner, or ask users to spawn mocha process with custom stdout/stderr.

**Comment by octref** [comment]
Actually this would be fixed by https://github.com/microsoft/vscode-extension-samples/pull/186, although its current approach has unresolved problem.
