### ISSUE TITLE
Error in Updating 

### ISSUE THREAD

**Issue by rahuls321** [Microsoft/vscode#56219]
I have been using VSCode since the previous month and I am continuously facing the same problem in updating the content through terminal whenever I try to run the reactJs app through `npm start`.
After updating the content, it is not able to recognize the updated content. So, if you are thinking that's a bug, then please fix it ...

**Comment by sandy081** [comment]
@rahuls321 May I know What content do you mean?

**Comment by rahuls321** [comment]
Content means whenever I add components in my react app it doesn't update in localhost @sandy081

**Comment by sandy081** [comment]
@rahuls321 May I know if you are using any react extensions? If so, can you please file an issue against that extension.
