### ISSUE TITLE
Unfold keyboard shortcut doesn't work

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#56215]
Issue Type: <b>Bug</b>

1. Clone https://github.com/deilan-htmlacademy-projects/js-2-pixel-hunter
2. Open `index.html`
3. Press <kbd>Ctrl+K Ctrl+0</kbd> (`Fold All`)
4. Set cursor on line 2 (`<html lang="en">`)
5. Press <kbd>Ctrl+Shift+J</kbd> (`Unfold`)

VS Code version:
- Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
- Code - Insiders 1.26.0-insider (207ace21dfec3dccab52f1296a3880ac7644c978, 2018-08-10T06:49:26.279Z)

OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.88GB (16.17GB free)|
|Process Argv|C:\Users\Deilan\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
debugger-for-chrome|msj|4.8.2
vscode-icons|rob|7.25.0

</details>

**Comment by aeschli** [comment]
This works for me: (1.28.0-insider). Maybe the wrong shortcut?
![folding-html](https://user-images.githubusercontent.com/6461412/45535064-80c80080-b7fd-11e8-8095-5a4c2a5b990a.gif)

Unfold just unfolds one level. To unfold all, use the respective action.

Please reopen if I misunderstood. Please write (or better: add a screenshot/gif) what you see and what you expect.
