### ISSUE TITLE
Typescript syntax highlighting bug on optional interface properties

### ISSUE THREAD

**Issue by softwareCobbler** [Microsoft/vscode#56229]
```ts
interface DagEdge {
  id?,
  from,
  to,
  qty?
}
/* the following interface is not syntax-colored properly, apparently due to the optional interface members above.
removing the optional members in DagEdge (above) results in the expected syntax coloring behavior*/
interface StateTree {
  dag : AbstractDag,
  mutationHistory,      
  contextMenu,
  hover,
  selection
}
```

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:11.471Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz (8 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.95GB (20.72GB free)|
|Process Argv|E:\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.7.1
java|red|0.29.0
vscode-java-debug|vsc|0.11.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.8.0
vscode-maven|vsc|0.10.0

</details>
 data into your clipboard because it was too large to send. Please paste.

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/Microsoft/TypeScript-TmLanguage/issues/651 to track this upstream
