### ISSUE TITLE
Interactions lag

### ISSUE THREAD

**Issue by iddan** [Microsoft/vscode#56221]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by iddan** [comment]
Why doesn't the issue reporter include the data in the GitHub preview?

**Comment by sandy081** [comment]
@RMacfarlane Can you please answer to the above question?

@iddan What is the real issue you are trying to report?

**Comment by RMacfarlane** [comment]
Normally, the data from the issue reporter is put into the url to pre-fill the issue title and description. However, there are limits on how long the url can be. When the data from the issue reporter exceeds this limit, it instead copies the data to the clipboard and asks the user to paste.

**Comment by sandy081** [comment]
@iddan Please update the description with required details
