### ISSUE TITLE
Can't add Keybinding with 5 key

### ISSUE THREAD

**Issue by Valetudox** [Microsoft/vscode#56222]
- VSCode Version: Version 1.26.0-insider (1.26.0-insider)
- OS Version: macOS High Sierra 10.13.5

Steps to Reproduce:

1. Go to `keyboard shortcuts` 
2. Setup a shourtcut
3. Try to use `cmd+alt+shift+ctrl+q`
4. The last character will be ignored
5. Manually edit `keybindings.json`
6. Try `alt+cmd+ctrl+shift+q` as `key`
7. It won't work

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
@Valetudox Does this keybinding reach VS Code ?

What does VS Code detect when you press the desired key combination?
![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

**Comment by Valetudox** [comment]
![hotkeys](https://user-images.githubusercontent.com/229279/44020745-266a3046-9ee3-11e8-879f-a5039c180ac1.gif)

The hotkey editor doesn't get the 'q' key, only the first 4

**Comment by Valetudox** [comment]
sorry, i didn't want to close

**Comment by alexandrudima** [comment]
@Valetudox This means that VS Code is not receiving the keybinding. You might have something at your OS level that is eating up that keypress. Were you successful in using this keybinding in any other software on the same machine ?

**Comment by Valetudox** [comment]
@alexandrudima It doesn't work in other editor too. Sorry for the interruption.
