### ISSUE TITLE
Agonizingly slow IntelliSense in .vue files

### ISSUE THREAD

**Issue by ffxsam** [Microsoft/vscode#56236]
- VSCode Version: 1.25.1
- OS Version: macOS 10.13.6

Bear with me, I'm not sure if this is a VS Code issue or a Vetur issue. IntelliSense is terribly slow in many cases. I'm using TypeScript in my codebase, if that matters. See screencap below.

![screencap](https://user-images.githubusercontent.com/12532733/44008496-04f511de-9e6a-11e8-8b49-88ba68c944a5.gif)

Does this issue occur when all extensions are disabled?: N/A, needs Vetur extension to work at all

**Comment by ramya-rao-a** [comment]
Please log this vetur first, it can be brought back to this repo if the issue is determined to be with VS Code
