### ISSUE TITLE
Cannot disable quick suggestions in intellisense

### ISSUE THREAD

**Issue by w0298i** [Microsoft/vscode#56230]
- VSCode Version: 1.25.1
- OS Version: Fedora 4.17.12-200.fc28.x86_64

Steps to Reproduce:

1. Open a js file with lots of methods and variables.
2. Use intellisense.

Does this issue occur when all extensions are disabled?: Yes

When in a file with lots of variables, intellisense will try to
suggest words that are in the document. From what I have
tried, it cannot be disabled.

**Comment by mjbvz** [comment]
Try setting `"javascript.nameSuggestions": false` to disable these

**Comment by w0298i** [comment]
ur a legend, ill test tmrw
