### ISSUE TITLE
Extend the YAML extension to support three periods at the end of a file

### ISSUE THREAD

**Issue by NeilLamka** [Microsoft/vscode#56232]
Issue Type: <b>Feature Request</b>

The current YAML extension flags the last line of a YAML file that contains three periods as an error.
{
	"resource": "/Users/nlamka/Documents/Intuit/Data Fabric/GitHub/oidm/oidm/MultimodelExample/Entitlement/actsOnEntitlement-rel.yaml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "undefined",
	"severity": 8,
	"message": "yaml: can not read an implicit mapping pair; a colon is missed at line 10, column 1",
	"startLineNumber": 11,
	"startColumn": 1,
	"endLineNumber": 12,
	"endColumn": 1
}

The placement of the three periods appears to be legal and valid so it would be helpful if it was not flagged as an error.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.7.0

**Comment by aeschli** [comment]
Can you file this against the yaml extension that you are using? Thanks a lot!
