### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by longmuir1** [Microsoft/vscode#56237]
import datetime
today = datetime.date.today()

str(today)
This piece of code will not work on vscode

**Comment by ramya-rao-a** [comment]
What programming language is this?

**Comment by sandy081** [comment]
Please reopen the issue with proper summary, description and steps to reproduce

**Comment by longmuir1** [comment]
import datetime
today = datetime.date.today()

str(today)
This piece of code will not work on vscode
This piece of code does not run in vs code but does run in the python interpreter

**Comment by longmuir1** [comment]
import datetime
today = datetime.date.today()

str(today)
This piece of code will not work on vscode
but does run in python interpreter

**Comment by ramya-rao-a** [comment]
Features for python code are provided by the python extension. So please log the issue in the repository of the python extension you are using

**Comment by longmuir1** [comment]
this is all to hard for little piece of code I'll just change my editor

**Comment by ramya-rao-a** [comment]
@longmuir1 VS Code is a light weight editor and as such uses extensions to provide language specific features. Please see https://code.visualstudio.com/docs/setup/additional-components

If the python code you have is in a python file, then of course you can use the integrated terminal to run it using `python`. But if you are trying to run the file directly somehow, we would suggest you to try out our [python extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python) and explore its features
