### ISSUE TITLE
Peek definition shows 2 definitions when there is actually only one on javascript

### ISSUE THREAD

**Issue by nelson687** [Microsoft/vscode#56231]
- VSCode Version: 1.25.1
- OS Version: Mac OS High Sierra

Seems that VScode gets confused with the definition of the function. I've seen similar requests but the issues are closed with no apparent fix.

See the screenshots:

1. I have a single .js file with the next function:

<img width="279" alt="screen shot 2018-08-12 at 20 52 13" src="https://user-images.githubusercontent.com/2769300/44005876-49e65ade-9e72-11e8-92b6-5ac3315ce001.png">

2. When I command + click in the caller:
<img width="1019" alt="screen shot 2018-08-12 at 20 52 21" src="https://user-images.githubusercontent.com/2769300/44005882-6f05f75c-9e72-11e8-9ddc-314d7b5ff27e.png">

It shows 2 definitions, but there is clearly only one.

thanks!

**Comment by mjbvz** [comment]
Fixed in VSCode 1.26
