### ISSUE TITLE
TreeItem is too slow

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/vscode#56234]
- VSCode Version: 1.25.1
- OS Version: 10.13.5

I've added the following view to [Todo+](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-todo-plus):

<img width="923" alt="screen shot 2018-08-13 at 00 58 43" src="https://user-images.githubusercontent.com/1812093/44007371-56619374-9e94-11e8-8828-89a160e7fe63.png">

I've been benchmarking it against [magento2](https://github.com/magento/magento2), which contains about 30k files and 2M lines of code. If the user has [ag](https://github.com/ggreer/the_silver_searcher) installed in his system the process of finding those todos is quite fast, its takes about 4s to do that on my laptop.

Quite surprisingly though the bulk of the time is spent on [these](https://github.com/fabiospampinato/vscode-todo-plus/blob/master/src/views/items/todo.ts/#L16-L26) lines, which are executed about 1k times, since the extension creates about 1k `TreeItem`s under these circumstances:

<img width="517" alt="screen shot 2018-08-13 at 01 05 42" src="https://user-images.githubusercontent.com/1812093/44007407-06b22716-9e95-11e8-9064-b84bfe5122d2.png">

- Adding the tooltips requires about 500 extra milliseconds, I would expect that number to be near 0ms, I see basically nothing going on here that can justify that number.

- Adding the commands requires about 4 extra **seconds**. 4 seconds for doing what? Creating those objects should be almost free, and until those `TreeItem`s get clicked they don't even change anything as far as the user is concerned, I think.

- Adding the icons requires about 14 extra **seconds**.  There are less than 10 different images loaded, but for some reason loading them a few hundred times is that slow.

**Comment by sandy081** [comment]
@fabiospampinato Is it possible to share the performance profile you created to come up with above numbers?

**Comment by fabiospampinato** [comment]
I don't know what you mean exactly by "performance profile", but I got the numbers this way:

- Have Todo+ installed, I think it was v4.0.5, but any more recent release should have basically identical performance.
- Download [magento2](https://github.com/magento/magento2) and open it in the VSC window that gets created for debugging extensions.
- Wrap [this](https://github.com/fabiospampinato/vscode-todo-plus/blob/master/src/utils/embedded_provider_ag.ts/#L35-L35) line in `console.time('foo')` and `console.timeEnd('foo')`, this is where the 4s figure for searching the files comes from
- Put a `if ( !item ) debugger;` [here](https://github.com/fabiospampinato/vscode-todo-plus/blob/master/src/views/embedded.ts/#L47), this gets hit right before creating any `TreeItem` object.
- Start a stopwatch and continue debugging at the same time.
- Stop the stopwatch when you see the view populated.

Now:

- If [these](https://github.com/fabiospampinato/vscode-todo-plus/blob/master/src/views/items/todo.ts/#L16-L26) lines are commented out the whole thing takes an amount of time that I don't remember, let's call it `X`, to render the view.
- If only [this](https://github.com/fabiospampinato/vscode-todo-plus/blob/4e2cba09983d479bf8c0eb5973aed35836c42424/src/views/items/todo.ts#L16) line is not commented out it takes about `X + 500ms` to do the work.
- If only [these](https://github.com/fabiospampinato/vscode-todo-plus/blob/master/src/views/items/todo.ts/#L18-L22) lines are not commented out it takes about `X + 4s` to do the work.
- If only [these](https://github.com/fabiospampinato/vscode-todo-plus/blob/master/src/views/items/todo.ts/#L24-L26) lines are not commented out it takes about `X + 14s` to do the work.
  - You might think that the problem here is actually the code that runs inside `Item#setTypeIcon`, but that's actually optimized enough to not really matter, and while benchmarking this thing I've replaced the body of the function with something like `return '/path/to/my/icon.svg'`, so that's not the problem.

I've taken these measurements multiple times just to be sure. All those numbers aren't super precise of course. I've run the code on an early-2015 MBP.

I hope this answers your question, let me know if you need anything else.

**Comment by sandy081** [comment]
Thanks for detailed explanation. I got it now.

Will investigate.

**Comment by alexr00** [comment]
I can see a small slowdown when a command and tooltip are included, but it's 10s of milliseconds, and I don't see an obvious way to bring this down. Since this issue was filed, we've swapped out the internal tree that the extension tree is built on top of. I expect this new tree is faster.
