### ISSUE TITLE
Expose hidesExplorerArrows as user setting

### ISSUE THREAD

**Issue by equinusocio** [Microsoft/vscode#56248]
Hi, the top level icons-theme configuration `hidesExplorerArrows`is not exposed as user setting. My theme extension set it to `true` to hide arrows but users can't change it through vscode settings.

Is there a way to override it?

**Comment by nealot** [comment]
Could this apply globally? i.e. enabling the option adds them to the outline, breadcrumbs, other extensions using the tree api, etc...

**Comment by aeschli** [comment]
duplicate of #45400
