### ISSUE TITLE
Vim 0.16.0プラグインを利用し、:e にて既存のファイルを開こうとすると、空ファイルになる

### ISSUE THREAD

**Issue by 0bara** [Microsoft/vscode#56242]
Issue Type: <b>Bug</b>

エクスプローラーから開くと問題なく動作するが、:eコマンドを介してファイルを開くと、空ファイルが開かれ、既存のファイルが空になる。

- 手順）
+ シェルからなんでも良いのでファイルをコピーする
 $ cp ../ex.py .
+ エディタ画面から、:e ex.py とタイプ
+ 空のファイルが表示される。
+ シェルでex.pyを確認すると空になっている
 $ ls -la ./ex.py

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) M-5Y51 CPU @ 1.10GHz (4 x 1200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 6, 5|
|Memory (System)|8.00GB (0.05GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
format-indent|Kas|1.3.0
html-css-class-completion|Zig|1.17.1
html-snippets|abu|0.2.1
code-gnu-global|aus|0.2.2
path-intellisense|chr|1.4.2
algorithm-mnemonics-vscode|dav|1.0.2
vscode-eslint|dba|1.4.12
githistory|don|0.4.2
tslint|eg2|1.0.34
php-debug|fel|1.12.3
php-intellisense|fel|2.3.3
auto-rename-tag|for|0.0.15
code-runner|for|0.9.4
terminal|for|0.0.10
gc-excelviewer|Gra|2.1.25
CppSnippets|har|0.0.13
beautify|Hoo|1.3.2
Runner|mat|0.1.14
rainbow-csv|mec|0.4.2
vscode-clang|mit|0.2.2
vscode-language-pack-ja|MS-|1.25.2
python|ms-|2018.7.1
cpptools|ms-|0.17.7
csharp|ms-|1.15.2
Go|ms-|0.6.85
docker-compose|p1c|0.2.3
vscode-docker|Pet|0.1.0
cmake-tools|vec|1.1.1
vim|vsc|0.16.0
JavaScriptSnippets|xab|1.7.0

</details>

**Comment by sandy081** [comment]
Can you please provide summary and description of the issue in English?

**Comment by octref** [comment]
Just helping out as I see it :) He was saying the `:e` command is not working as expected in Vim mode.

@0bara Please open this issue at https://github.com/VSCodeVim/Vim and use English. Vimプラグインに関するバグなので VSCodeVim に issue を提出してください。
