### ISSUE TITLE
Allow the debugger itself to persist the DebugConfiguration in launch.json

### ISSUE THREAD

**Issue by testforstephen** [Microsoft/vscode#56244]
In Java Debugger, there are two important configs `mainClass` and `projectName` which are error-prone when configuring them manually. So we add the validation in `DebugConfigurationProvider#resolveDebugConfiguration` and prompt user about the possible correct configs with QuickPick UI. But we don't find the API to persist the new change back to the launch.json. Could the VS Code provide a public API for the third-party debugger to persist the launch.json?

**Comment by weinand** [comment]
Debug configurations are a part of workspace configurations and can be persisted via the `WorkspaceConfiguration.update`API.
