### ISSUE TITLE
Glitch when quitting in fullscreen and starting again

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#56245]
OS: macOS

Steps to Reproduce:

1. enter fullscreen
2. quit
3. start again

=> 🐛 the title area shows no background and then gets it

We only restore the fullscreen window when `window.restoreFullscreen` is set to `true` so maybe that could be used as a hint to find out if the title should be stored for the splash or not.

**Comment by jrieken** [comment]
This is now more conservative and being in fullscreen (any window) will prevent rapid render.
