### ISSUE TITLE
wrong nesting object by @property in JSDoc

### ISSUE THREAD

**Issue by Tidyzq** [Microsoft/vscode#56247]
- VSCode Version: 1.25.1
- OS Version: Windows 10, Mac OSX

Steps to Reproduce:

1. Open a javascript file, put the following JSDoc code:
``` javascript
/**
 * @typedef {object} test
 * @prop {object} foo - foo
 * @prop {object} bar - bar
 */
```
2. Move the mouse on top of the `test` object, check the type info of `test`, it will give the structure like:
![image](https://user-images.githubusercontent.com/10173739/44019042-3cdbec34-9f10-11e8-915a-cacf62913a88.png)
The structure of type `test` should be:
``` typescript
{
  foo: any;
  bar: any;
}
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This seems fixed in VSCode 1.26:

![screen shot 2018-08-20 at 3 28 28 pm](https://user-images.githubusercontent.com/12821956/44343259-bcd1a500-a48d-11e8-920f-bbeb0528da57.png)
