### ISSUE TITLE
Advanced Process Monitoring

### ISSUE THREAD

**Issue by Kyngo** [Microsoft/vscode#56258]
When you develop applications, performance can be crucial, and monitoring CPU and RAM usage for the process you're debugging can be really helpful.

So, this is my feature request: a process monitor built into the debugger.

**Comment by isidorn** [comment]
fyi @weinand

**Comment by Kyngo** [comment]
I don't think this should be closed, as this feature can be very helpful to any dev out there.

**Comment by weinand** [comment]
You can already use the Chrome Dev Tools which are built into VS Code.
