### ISSUE TITLE
Getting updates on windows 8 is slow. 

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#5625]
- VSCode Version:1.0.1-alpha
- OS Version: Windows10 and Win8

I installed the latest alpha build from https://vscode-builds.azurewebsites.net/alpha on my windows10 and win8 machine. I observed whenever I install the latest build on windows10 I may get a update pop-up instantly if there is any build updates. 
But on win8 machine I didn't get any update pop-up instantly. Its trigger very late, almost after an hr.

![image](https://cloud.githubusercontent.com/assets/17735796/14724071/fd1376c0-07c8-11e6-90d1-1a1a3e9cc20f.png)

Win8 (before update):
![image](https://cloud.githubusercontent.com/assets/17735796/14724520/909e7654-07cb-11e6-9707-7fdf47639210.png)

Win10 (after update):
![image](https://cloud.githubusercontent.com/assets/17735796/14724532/b565884c-07cb-11e6-8048-b8f2ceaef22d.png)

**Comment by joaomoreno** [comment]
This is OK.
