### ISSUE TITLE
[loc][Query] Context for "hover" 

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#56257]
For string below community member is asking for more context to provide better translation. Can you please check it? Thanks!

**Original comment**
ES ISSUE
We need to understand better the context of this string (src/vs/editor/common/config/commonEditorConfig:English (en):plaintext:hover.enabled ) to provide a better Spanish translation for the "hover" word (Spanish: "flotar/flotante") as it refers in a implicit way to hover text for some elements on the editor when the mouse pointer is placed, I guess.
by AleksSyntek, 12 days ago

**Context**
src/vs/editor/common/config/commonEditorConfig:English (en):plaintext:hover.enabled

**Resource**
vs_editor

**String text**
Controls whether the hover is shown.

**Comment by ramya-rao-a** [comment]
> as it refers in a implicit way to hover text for some elements on the editor when the mouse pointer is placed, I guess.

Yes, it refers to the hover text shown on some elements in the editor when the mouse pointer is placed on them

cc @alexandrudima

**Comment by AleksSyntek** [comment]
Thanks @josefhosek and @ramya-rao-a for the clarify on this question.
Kind regards.
