### ISSUE TITLE
The resource manager displays a structural disorder.

### ISSUE THREAD

**Issue by LiZhiHao97** [Microsoft/vscode#56259]
- VSCode Version: 1.25.1
- OS Version: mac os 10.13.2

When I'm writing a project, the resource manager on the right sometimes displays folder structure errors (for example, files under one folder appear in another folder, fold up and expand again, and then return to normal)

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
Can you please provide a screenshot of what you mean?

**Comment by bpasero** [comment]
Sounds like explorer and/or tree issue.

**Comment by isidorn** [comment]
Sounds like the usual tree issue that Joao knows which one -> forwarding so he can close as duplicate

**Comment by isidorn** [comment]
@joaomoreno that is the only tree issue I whish we could somehow fix - since every milestone a couple of people hit it. Do you know the root cause?

**Comment by joaomoreno** [comment]
Wanna fix it together?
