### ISSUE TITLE
Git issue in WSL

### ISSUE THREAD

**Issue by NileshParkhe83** [Microsoft/vscode#56250]
Issue Type: <b>Bug</b>

* Similar Existing Open issue found : None

* Issue exists in Insider build.

Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:43:53.668Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 10.7.0
V8: 5.8.283.38
Architecture: x64
OS Version: 1803 (build 17134.165)
WSL Version: Ubuntu 18.04.1 LTS

Steps to Reproduce:
1. Set terminal to WSL bash
2. Verified in integrated WSL Bash terminal that global git config exists
    git config --get-all user.name  ==> Nilesh
    git config --get-all user.email ==> <valid email address>
3. Add new files to project. Git stages new files successfully. However, commit is rejected :- 
Please tell me who you are. unable to auto-detect email address. 

Does this issue occur when all extensions are disabled?: Yes

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (9.03GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe --disable-extensions .|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled

**Comment by yume-chan** [comment]
I met the same problem before, seems there is no way to set `git.path` to `wsl git`.

In the end, I have to configure git twice.
