### ISSUE TITLE
Can't open VSCode from command line with --extensions-dir flag

### ISSUE THREAD

**Issue by Grehgous** [Microsoft/vscode#56265]
- VSCode Version: 1.25.1
- OS Version: Windows 10

In command prompt when I enter `code` it opens VSCode, but if I add the `--extensions-dir` flag it does not open VSCode. I experience the same behavior when I add the property to the VSCode stortcut.

I am attempting to change the extensions folder location.

Steps to Reproduce:
1.  Open command prompt
2. Enter code `--extensions-dir C:\My\Path\.vscode\extensions`

**Comment by sandy081** [comment]
@Grehgous Do you see any errors when you use `extension-dir` flag?
