### ISSUE TITLE
Integrated terminal lines overflows monitor border limits

### ISSUE THREAD

**Issue by Rynaro** [Microsoft/vscode#56266]
- VSCode Version: 1.25.1
- OS Version: openSUSE Tumbleweed

Steps to Reproduce:

1.Open VSCode integrated terminal;
2. Run a command that returns a huge one line output, forcing terminal break into multiple lines.

Does this issue occur when all extensions are disabled?: Yes

I've made a screenshot to make the bug more visual:
![image](https://user-images.githubusercontent.com/5271543/44046154-017492a4-9f01-11e8-8aeb-2946743c0508.png)

**Comment by Tyriar** [comment]
Update to latest should fix this.
