### ISSUE TITLE
on Linux middle-click paste wont work.

### ISSUE THREAD

**Issue by NikosEfthias** [Microsoft/vscode#5626]
- VSCode Version:1.8.2
- OS Version:ubuntu 15.10

Steps to Reproduce:

1. highlight some text by mouse
2. middle click some other position to paste

**Comment by bgse** [comment]
Do you have the setting enabled in your config?

```
{
    "editor.selectionClipboard": true
}
```

**Comment by NikosEfthias** [comment]
@bgse does not work when i middle click editor just looses focus nothing is pasted

**Comment by Tyriar** [comment]
@NikosEfthias I've been using the feature for a month or so with no issues on Ubuntu 15.10 and most recently 16.04. Did you try restarting after the setting was modified?

Also what version of VSCode are you on? We're only up to v1.0.1 so far.

**Comment by NikosEfthias** [comment]
the version says 1.8.2 ![](http://i.imgur.com/WeKISZU.png)

**Comment by NikosEfthias** [comment]
i installed through deb package now it works

**Comment by NikosEfthias** [comment]
will i get updates automatically on ubuntu now through package manager

**Comment by Tyriar** [comment]
@NikosEfthias good to hear!

No updates won't happen until probably the May release now, we're blocked on another team for signing unfortunately. See https://github.com/Microsoft/vscode/issues/2973 for updates.
