### ISSUE TITLE
'/' on the numeric pad acts like PgUp in code editor

### ISSUE THREAD

**Issue by Serge1985** [Microsoft/vscode#56269]
Issue Type: <b>Bug</b>

I am using portable vscode install on my linux machine. I have configured some shortcuts, but even completely wiping out my keybinding.json doesn't fix the isue:
when I am in any other window than code editor and I press / on the numeric pad, it is interpreted as '/', however, when I am in the code editor, it acts as PgUp instead. The adjacent keys (numLock and *) work fine. / on the main key pad works too.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:40:20.190Z)
OS version: Linux x64 3.10.0-693.11.6.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz (16 x 3192)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Load (avg)|2, 2, 2|
|Memory (System)|31.26GB (11.07GB free)|
|Process Argv|/users/schernet/bin/VSCode-linux-x64/code training/training.code-workspace|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.17.7
debug|web|0.22.0

</details>

**Comment by alexandrudima** [comment]
@Serge1985 
What does VS Code detect when you press the desired key combination? Please hover over the input box and take a screenshot:
![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

**Comment by Serge1985** [comment]
This is something really weird - I even shot a video that shows my finger
typing on the keyboard: https://photos.app.goo.gl/mNHYqAeYsZ6JV5LZ6
When I type in search window, the same numpad / key is interpreted as '/',
however when I type it as keypress, it is taken as PgUp. I know it doesn't
sound sane, but that's what I see :)
------
Yours sincerely, Serge

**Comment by alexandrudima** [comment]
Am I seeing things correctly? You are actually on a Windows machine and use remote desktoping software to control a linux machine?

Did you take a look at https://github.com/Microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-linux-keybindings

**Comment by Serge1985** [comment]
Yes, you are quite right and thank you, it fixed the issue!
------
Yours sincerely, Serge
