### ISSUE TITLE
Integrated Terminal - Column Selection - freaks out when using alt click without moving the mouse to select anything

### ISSUE THREAD

**Issue by DustinX** [Microsoft/vscode#56278]
Issue Type: <b>Bug</b>

- open integrated terminal
- enter a command that would produce some output, such as "git log"
- hold the ALT key
- click somewhere in the terminal, don't move the mouse, and release the click

result:
terminal fills up with many empty and garbage lines

expected result:
nothing is copied to the clipboard

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.79GB (7.63GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe Plan.txt PROVs.txt json.json Scratchpad.txt Meeting Notes.txt Debug tips.txt PH Misc info.txt Plan Archive.txt Shortcuts.txt VSCode changes.txt -n|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.0.3
bracket-pair-colorizer|Coe|1.0.59
code-runner|for|0.9.4
PowerShell|ms-|1.8.2
vscode-icons|rob|7.25.0
vscode-paste-and-indent|Rub|0.0.8
partial-diff|ryu|1.3.0
code-settings-sync|Sha|3.0.0
gitblame|wad|2.4.4

</details>

**Comment by Tyriar** [comment]
Seems to work fine for me, could you put together a gif showing the issue?

**Comment by DustinX** [comment]
I haven't learned how to make a gif yet, so let me see if more info is enough for you to reproduce it:

Seems like it only happens when the terminal is paused on some scroll-able output, i.e. when you do a "git log" and it shows a few lines and then has a colon ":", at which point you can press Enter or Down Arrow to show more of the output, or press 'q' to quit. (see image)
![image](https://user-images.githubusercontent.com/786989/44182317-54fd1200-a0bb-11e8-8c2b-1d62d6e49fa6.png)

**Comment by Tyriar** [comment]
It looks like this is behaving as designed and will also happen in other terminals. The reason is because a click (not a drag) has alt+click sent to the program running in the terminal and that's just how `git log` handles it for some reason.

**Comment by DustinX** [comment]
Really?  I couldn't reproduce the behavior in native Powershell or a git bash window.  Even when explicitly holding alt while clicking.

**Comment by Tyriar** [comment]
@DustinX that's because the VS Code terminal is emulating a unix-based terminal whereas conhost is using the Windows Console API and has different capabilities. Since this always happened in the default mac terminal I'd say this is as designed.

**Comment by DustinX** [comment]
Thanks for the explanation
