### ISSUE TITLE
Syntax highlighting for inline css in html

### ISSUE THREAD

**Issue by steen3d** [Microsoft/vscode#56272]
Version 1.25.1

Syntax highlighting for inline styles in html documents. Currently the entire style attribute gets assigned one color. Separate colors for properties and values would make this much more readable.

**Comment by aeschli** [comment]
duplicate of https://github.com/textmate/html.tmbundle/issues/88

**Comment by steen3d** [comment]
Sorry for the duplication, and thanks for your work on the issue.

-Chris
