### ISSUE TITLE
spelling error: The termnial is now using the fallback renderer.

### ISSUE THREAD

**Issue by haarabi** [Microsoft/vscode#56276]
Issue Type: <b>Bug</b>

spelling error: The termnial is now using the fallback renderer.

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|15.88GB (4.78GB free)|
|Process Argv|C:\Users\hossein.aarabi\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.3.1
gitlens|eam|8.5.4
mssql|ms-|1.4.0
PowerShell|ms-|1.8.2
chef|Pen|0.7.0
jenkinsfile-support|sec|0.1.0
code-spell-checker|str|1.6.10

</details>

**Comment by Tyriar** [comment]
Fixed in latest insiders 👍
