### ISSUE TITLE
[Custom title bar] Window title not centered

### ISSUE THREAD

**Issue by Stanzilla** [Microsoft/vscode#56273]
Any chance the title bar text can be centered in this mode? Currently it looks like it tries to center itself based on the whole width-widthOfTheMenuBar instead of the whole window width.

**Comment by Stanzilla** [comment]
Hrm, https://github.com/Microsoft/vscode/issues/52905 comes close but @Tyriar said he prefers the way it was changed to now, so not sure.

**Comment by Tyriar** [comment]
I'm fine with keeping it centered, but this must not be truncated: 
![image](https://user-images.githubusercontent.com/2193314/44111952-a6869a1e-9fb8-11e8-8778-c8142991acd6.png)

**Comment by Splike** [comment]
It's easy to see here, that it's not centered properly:

![image](https://user-images.githubusercontent.com/7159527/45191391-467dc280-b243-11e8-8cce-7e55fce9ceec.png)

**Comment by cra0zy** [comment]
You could say that this is really... offsetting to see :P
