### ISSUE TITLE
Describe is not defined when testing extensions

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5627]
- VSCode Version: 1.0.1-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Create your own extension.
2. Open test/extension.test.js
3. Add a describe function as outlined in the Mocha testing docs

```javascript
    describe('Connection', function () {
        var db = new Connection,
            tobi = new User('tobi'),
            loki = new User('loki'),
            jane = new User('jane');

        beforeEach(function (done) {
            db.clear(function (err) {
                if (err) return done(err);
                db.save([tobi, loki, jane], done);
            });
        });
```

4. Launch tests.

Displays error saying "describe is not defined"
![testextensionerror](https://cloud.githubusercontent.com/assets/12900364/14724644/581c0840-07cc-11e6-9155-d20c963156f7.PNG)

**Comment by bpasero** [comment]
Configure the test runners in the index.js file. By default we use "tdd" and that allows you to use suite() and test().

**Comment by reduckted** [comment]
Just in case anyone else ends up here (like me), and doesn't quite understand what you're supposed to change, it's the `ui` property in the options to the `testRunner.configure` method:

```typescript
testRunner.configure({ ui: 'tdd' });
```

This is the default and it allows you to use `suite` and `test` (but _not_ `describe` and `it`).

If you want to use `describe` and `it`, change it to:

```typescript
testRunner.configure({ ui: 'bdd' });
```
