### ISSUE TITLE
Wrong results in Settings search

### ISSUE THREAD

**Issue by cnshenj** [Microsoft/vscode#56282]
Issue Type: <b>Bug</b>

1. Open Settings (<kbd>Ctrl</kbd>+<kbd>,</kbd>)
2. In search box, type "step"

Expected:
Shows all settings that contains "step".

Actual:
Shows many matching settings, but none of them contains "step".

Note:
Searching for "ste" or "tep" works fine. 

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz (8 x 3096)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|15.85GB (5.97GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.5.4
vscode-azurefunctions|ms-|0.10.0
mssql|ms-|1.4.0
azure-account|ms-|0.4.3
csharp|ms-|1.15.2
PowerShell|ms-|1.8.2
debugger-for-chrome|msj|4.8.2
vscode-docker|Pet|0.1.0
vscode-icons|rob|7.25.0
code-spell-checker|str|1.6.10

</details>

**Comment by roblourens** [comment]
Which settings are you expecting to see that include "step"? I don't see any.

**Comment by cnshenj** [comment]
I am not expecting any specific setting. I am expecting search to tell me what settings contain "step". Instead of showing me an empty list, it shows some random settings, like this:
![vscode settings search](https://user-images.githubusercontent.com/8441956/44105020-4754d730-9fa5-11e8-8b27-8ef9dbc6028c.PNG)

**Comment by roblourens** [comment]
We have fuzzy search that tries to anticipate typos, alternate words, etc. Not sure what it's matching on in this particular case, but that's what's going on.
