### ISSUE TITLE
Crash when using dev tools from VS Code

### ISSUE THREAD

**Issue by yasirs** [Microsoft/vscode#5628]
- VSCode Version:1
- OS Version:10.9.5

Steps to Reproduce:
I am not sure, but I am attaching the crash report.
[vscode.crashreport.txt](https://github.com/Microsoft/vscode/files/230760/vscode.crashreport.txt)

**Comment by bpasero** [comment]
@yasirs looks like you opened developer tools in VS Code, could that be true?

**Comment by yasirs** [comment]
Yes. I'd just installed it and was exploring the interface.

**Comment by bpasero** [comment]
This is https://github.com/electron/electron/issues/4261

**Comment by bpasero** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/4430
