### ISSUE TITLE
Terminal Pane Has No Current Path

### ISSUE THREAD

**Issue by jellyfishgh** [Microsoft/vscode#56287]
- VSCode Version:1.26.0
- OS Version:Windows 10

Steps to Reproduce:

1.Open Terminal View then No Current Path in the panel

![image](https://user-images.githubusercontent.com/3036042/44067708-5df9b2d6-9fa9-11e8-8864-fe48854a7ba5.png)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
