### ISSUE TITLE
Performance of "workbench.action.goToSymbol" is slow for network mapped drives

### ISSUE THREAD

**Issue by twig** [Microsoft/vscode#56281]
Issue Type: <b>Performance Issue</b>

I'm not sure whether its due to the size of the project or if I'm using VSCode over a mapped network drive.

Whenever I try to jump to a symbol within the same file, the autocomplete just doesn't work.

If I try it on a local file, it works quite well.

![image](https://user-images.githubusercontent.com/59689/44063951-259b5848-9fa6-11e8-943b-b23c91610e79.png)

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.86GB (3.23GB free)|
|Process Argv|D:\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    4	    91	 10396	code main
    0	    65	  2188	   shared-process
    2	   146	  7648	   gpu-process
    4	    72	 12360	   window (Issue Reporter)
    0	   207	 12888	   window (Untitled-1 - Visual Studio Code)
    0	    64	 11176	     extensionHost
    0	    32	  5448	       C:\Users\twig\.vscode\extensions\ms-vsliveshare.vsliveshare-0.3.535\dotnet_modules\vsls-agent.exe --autoexit --pipe bebb86de87384751b93353a9fb31b667 --service https://insiders.liveshare.vsengsaas.visualstudio.com/
    0	    10	  8136	         console-window-host (Windows internal process)
    0	    36	 12444	     searchService
    0	    14	 13076	     electron-crash-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
reasonml|fre|1.0.38
python|ms-|2018.7.1
vsliveshare|ms-|0.3.535
vscode-code-outline|pat|0.2.1

</details>

**Comment by twig** [comment]
I had a hunch that [disabling node_modules](https://stackoverflow.com/questions/33258543/how-can-i-exclude-a-directory-from-visual-studio-code-explore-tab) would improve performance and it seems to have worked

maybe switch the algorithm a little so it favours current file?

**Comment by mjbvz** [comment]
Please provide a complete set of repo steps and some example code that demonstrates the problem
