### ISSUE TITLE
window.titleBarStyle: custom display error

### ISSUE THREAD

**Issue by wanghaolu** [Microsoft/vscode#56288]
- VSCode Version:1.26.0
- OS Version:windows 10 1803

Steps to Reproduce:

1.Repeatedly maximize the vscode

![tim 20180814101302](https://user-images.githubusercontent.com/9586655/44068037-c1c95932-9faa-11e8-8c18-f9ae43cdcc9f.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by yume-chan** [comment]
Duplicate of #52265

**Comment by sbatten** [comment]
@yume-chan thanks for linking
