### ISSUE TITLE
Ability to hide breadcrumb icons

### ISSUE THREAD

**Issue by yuval-gilboa** [microsoft/vscode#56286]
Please add `breadcrumbs.icons` setting to enable hiding the breadcrumbs icons.
Similar to how its already done for outline icons using the `outline.icons` setting.

**Comment by chrismay** [comment]
I have created a draft PR that (I think) addresses this. 

However, changes don't immediately re-render the breadcrumb view - for example, if you split the editor and have a source file open in one pane and the settings in another, changing the "breadcrumbs.icons" setting won't change the editor's breadcrumb display until you switch editors, or move to a new section in the source file.

Should that work? And if so, how do I trigger a re-render as soon as the configuration setting changes?

**Comment by chrismay** [comment]
Updated the PR; 

I've made the breadcrumbs update immediately on toggling the option by modifying the `equals` method on `Item` to also include the icon-display option on `FileElement`s. I'm not sure whether that's the right approach or not, though.

**Comment by jrieken** [comment]
👏 to @chrismay
