### ISSUE TITLE
Stopping debugging an extension doesn't close dev host after opening a folder

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5629]
- VSCode Version: 1.0.1-alpha
- OS Version: Windows 10

Steps to Reproduce:
1. Create a Code extension
2. Debug launch extension
3. If debug opens a new window with a folder already open, close the folder in the host and restart debugging
4. Open a folder in the host
5. Stop debugging in the main window

Actual:
Dev host Code window does not close after pressing stop.

**Comment by weinand** [comment]
Can no longer reproduce.
