### ISSUE TITLE
Setting for dark themes: colorActiveIndentGuide, complementing highlightActiveIndentGuide

### ISSUE THREAD

**Issue by fungilation** [Microsoft/vscode#56297]
Currently in settings, there's toggle for editor.highlightActiveIndentGuide (default on). This is great, but looks "highlighted" only on light background themes, with the indent color being darker/black. In dark themes, the darker active indent actually becomes de-emphasized in reverse.

I propose a new setting: `editor.colorActiveIndentGuide`, with default being current black (?). On dark themes, users can then customize colorActiveIndentGuide to be a lighter color hex code so it actually appears highlighted instead of the other way around.

Bonus points: Have colorActiveIndentGuide add a 3rd [auto] setting, where it would automatically switch between black on light themes and lighter gray on dark themes.

**Comment by fungilation** [comment]
No bot, I searched. Nothing on this have been discussed in this repo, this has nothing to do with menu or activity bars.

**Comment by alexandrudima** [comment]
There already are two distinct colors: `editorIndentGuide.activeBackground` and `editorIndentGuide.background`

Why are these not sufficient?
