### ISSUE TITLE
add GenerateFullPaths to tasks.json by default

### ISSUE THREAD

**Issue by david-waterworth** [Microsoft/vscode#56295]
Each time I create a new solution, and vscode automatically adds a tasks.json template I find I have to add GenerateFullPaths=true manually or I get a lot of issues such as not being able to jump to the line of code where there's an error as vscode cannot resolve the location of the source file.

i.e.

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "command": "dotnet",
            "type": "process",
            "args": [
                "build",
                "${workspaceFolder}/XXX/XXX.csproj",
                "/property:GenerateFullPaths=true"
            ],
            "problemMatcher": "$msCompile"
        }
    ]
}
```

**Comment by dbaeumer** [comment]
How do you create the solution file? Do you run `Task > Configure Task`. I am actually pretty sure that this is caused by the C# extension but want to be sure.

**Comment by david-waterworth** [comment]
No I don't run Task > Configure Task, I just hit F5 and the first time it generates tasks.json

**Comment by dbaeumer** [comment]
Then this is generated by the C# extension. Can you please file the issue there.

**Comment by david-waterworth** [comment]
Will do, thanks!
