### ISSUE TITLE
Use Ctrl+Shift+. to turn on Breadcrumbs if off

### ISSUE THREAD

**Issue by tomByrer** [Microsoft/vscode#56302]
If the Breadcrumbs are off, I'd like to use `[Ctrl+Shift+.]` to turn on.

Breadcrumbs are a neat feature; cheers.

**Comment by jrieken** [comment]
@sandy081 I have tried this but it seems that updating a configuration value doesn't fire a change event synchronously but with a detail. That makes my code much more complicated and I wonder why we do that?

**Comment by jrieken** [comment]
Oh, didn't see it turn a promise...
