### ISSUE TITLE
vscode shutdwon

### ISSUE THREAD

**Issue by proudlily** [Microsoft/vscode#56306]
hi,after my pc audate .the vscode shutdown 
and here is the wrong message:

```javascript
./code: row35:  3998 date wrong               (core is transfor)ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"

```
#### pc:
```
Linux archlinux 4.17.14-arch1-1-ARCH #1 SMP PREEMPT Thu Aug 9 11:56:50 UTC 2018 x86_64 GNU/Linux
```

**Comment by sandy081** [comment]
@proudlily Do you mean VS Code got crashed after your PC got updated and restarted?

**Comment by proudlily** [comment]
yes.i dont know why.and i dont know how to offer the need info.so i dont add the info.if you need.please tell me .@sandy081

**Comment by proudlily** [comment]
what the info do u need.thanks very much !

**Comment by bpasero** [comment]
@proudlily do I understand it correctly that you start VSCode from the command line and it just crashes?

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

This smells a bit like https://github.com/Microsoft/vscode/issues/51917

**Comment by proudlily** [comment]
@bpasero thanks. i am doing the project now.so may have  no time to deal it .but when i have time ,i will do it .actually,it will takes me some time.:-)

**Comment by bpasero** [comment]
@proudlily let's move this into https://github.com/Microsoft/vscode/issues/55934 I am sure its the same underlying issue.
