### ISSUE TITLE
Extension Host terminated unexpectedly

### ISSUE THREAD

**Issue by javafuns** [Microsoft/vscode#56301]
Issue Type: <b>Bug</b>

told me extension host terminated unexpectedly. There is only one simple go file open

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:20:44.170Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 5, 4|
|Memory (System)|16.00GB (0.26GB free)|
|Process Argv|/Users/gavin/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|8.0.0
vscode-markdownlint|Dav|0.19.0
vscode-simpler-icons|dav|1.5.2
vscode-eslint|dba|1.4.12
vscode-npm-script|eg2|0.3.5
auto-close-tag|for|0.5.6
live-html-previewer|hdg|0.3.0
beautify|Hoo|1.3.2
sublime-babel-vscode|jos|0.2.10
theme-karyfoundation-themes|kar|18.0.1
prettify-json|moh|0.0.3
python|ms-|2018.7.1
Go|ms-|0.6.86
node-debug2|ms-|1.27.0
typescript-javascript-grammar|ms-|0.0.43
color-highlight|nau|2.3.0
vscode-extension-auto-import|Nuc|1.4.3
material-icon-theme|PKi|3.5.2
vscode-icons|rob|7.25.0
vscode-todo-highlight|way|1.0.4
markdown-all-in-one|yzh|1.6.0

(10 theme extensions excluded)

</details>

**Comment by gerrywastaken** [comment]
Same issue

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:20:44.170Z)
OS version: Darwin x64 16.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6287U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.87GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.3.1
yaml-key-viewer|cyb|0.1.0
rails-test-runner|dav|0.0.4
vscode-eslint|dba|1.4.12
copywithline|dii|0.0.2
gitlens|eam|8.5.4
tslint|eg2|1.0.34
json-tools|eri|1.0.2
prettier-vscode|esb|1.6.1
vs-code-xml-format|fab|0.1.5
flow-for-vscode|flo|0.8.2
vscode-auto-open-markdown-preview|hnw|0.0.4
hjson|lak|0.3.0
rails-rspec-file-toggle|mal|0.0.2
terraform|mau|1.3.4
rainbow-csv|mec|0.4.2
vscode-elixir|mjm|1.1.0
azure-account|ms-|0.4.3
vsliveshare|ms-|0.3.535
debugger-for-chrome|msj|4.8.2
rails-run-spec-vscode|nok|0.1.2
subtitles-editor|pep|0.0.1
vscode-docker|Pet|0.1.0
view-in-browser|qin|0.0.5
ruby|reb|0.20.0
elastic|ria|0.13.3
vscode-sql-beautify|sen|0.0.4
haml|vay|1.0.1
vim|vsc|0.16.0
vscode-open-in-github|ziy|1.3.5

(2 theme extensions excluded)

**Comment by sandy081** [comment]
Can you please give us following data

- Open output panel and get the logs from Extension, Window channels
- Open Development Tools (`Developer: Toggle Developer Tools`) and get the logs from the console.

**Comment by gerrywastaken** [comment]
@sandy081 Developer Tools console:

Output panel had nothing in the Extension channel but the following was in the `Log (Window)` channel:

```
[2018-08-14 20:05:25.300] [renderer7] [info] No grammar found for scope source.graphql
[2018-08-14 20:05:25.366] [renderer7] [info] No grammar found for scope source.js.jquery
[2018-08-14 20:05:25.395] [renderer7] [info] No grammar found for scope source.applescript
[2018-08-14 20:05:25.398] [renderer7] [info] No grammar found for scope text.html.textile
[2018-08-14 20:05:25.398] [renderer7] [info] No grammar found for scope text.html.javadoc
[2018-08-14 20:05:25.489] [renderer7] [info] No grammar found for scope source.scala
[2018-08-14 20:05:25.502] [renderer7] [info] No grammar found for scope source.dart
[2018-08-14 20:05:25.502] [renderer7] [info] No grammar found for scope source.postscript
[2018-08-14 20:05:25.502] [renderer7] [info] No grammar found for scope source.sass
[2018-08-14 20:05:25.502] [renderer7] [info] No grammar found for scope source.less
[2018-08-14 20:05:25.502] [renderer7] [info] No grammar found for scope source.stylus
[2018-08-14 20:05:27.450] [renderer7] [info] standard startup {"version":"1.26.0","ellapsed":1237,"timers":{"ellapsedExtensions":947,"ellapsedExtensionsReady":1635,"ellapsedRequire":356,"ellapsedEditorRestore":412,"ellapsedViewletRestore":22,"ellapsedWorkbench":553,"ellapsedWindowLoadToRequire":310,"ellapsedTimersToTimersComputed":11,"ellapsedNlsGeneration":0},"platform":"darwin","release":"16.6.0","arch":"x64","totalmem":17179869184,"freemem":670056448,"meminfo":{"workingSetSize":518864,"peakWorkingSetSize":0,"privateBytes":223776,"sharedBytes":295092},"cpus":{"count":4,"speed":3100,"model":"Intel(R) Core(TM) i5-6287U CPU @ 3.10GHz"},"loadavg":[2.8603515625,2.1787109375,2.03125],"initialStartup":false,"isVMLikelyhood":0,"hasAccessibilitySupport":false,"emptyWorkbench":false,"common.machineId":"4633f3340f0d022171f88a403decc6ae6d00c70269bea012854f06e6cdcb4790","sessionID":"2637a784-9a67-4049-bbb4-032c342791db1534241123880","commitHash":"4e9361845dc28659923a300945f84731393e210d","common.platformVersion":"16.6.0","common.platform":"Mac","common.nodePlatform":"darwin","common.nodeArch":"x64","timestamp":"2018-08-14T10:05:27.450Z","common.timesincesessionstart":3570,"common.sequence":20,"common.version.shell":"2.0.5","common.version.renderer":"61.0.3163.100","common.firstSessionDate":"Fri, 14 Jul 2017 00:07:39 GMT","common.lastSessionDate":"Tue, 14 Aug 2018 10:03:12 GMT","common.isNewSession":"0","common.instanceId":"a24babbe-5390-42e4-8172-735f9969680b"}
```


```
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4188 Overwriting grammar scope name to file mapping for scope source.ruby.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/ruby/syntaxes/ruby.tmLanguage.json.
New grammar file: file:///Users/gerry/.vscode/extensions/rebornix.ruby-0.20.0/syntaxes/ruby.cson.json
e.register @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4188
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1397  INFO No grammar found for scope source.graphql
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1397  INFO No grammar found for scope source.js.jquery
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1397  INFO No grammar found for scope source.applescript
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1397  INFO No grammar found for scope text.html.textile
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1397  INFO No grammar found for scope text.html.javadoc
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1397  INFO No grammar found for scope source.scala
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1397  INFO No grammar found for scope source.dart
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1397  INFO No grammar found for scope source.postscript
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1397  INFO No grammar found for scope source.sass
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1397  INFO No grammar found for scope source.less
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1397  INFO No grammar found for scope source.stylus
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] Rails Test Runner was activated
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3213 Extension host terminated unexpectedly. Code:  null  Signal:  SIGPIPE
w._onExtensionHostCrashed @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3213
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2386 Extension host terminated unexpectedly.
t.onDidNotificationChange @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2386
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1397  INFO standard startup Object
```

I've also noticed that this is only after opening a Ruby file.

If I open a JS file first I don't get this error, but as soon as I load a Ruby file it pops up. However I'm pretty sure this is not the trigger for @javafuns as they are not using any ruby extensions.

**Comment by wingrunr21** [comment]
Actually a bug in Electron. VSCode itself already mitigated the issue (see Microsoft/vscode#52583). Working on mitigating it in `vscode-ruby`.

**Comment by juliofarah** [comment]
I'm having the same issue with the VIM (vscodevim) + Go combination.
Is there a quick fix?

**Comment by bpasero** [comment]
I am merging this into https://github.com/Microsoft/vscode/issues/56387 to continue the discussion there.
