### ISSUE TITLE
Wonky formatting inside TSX brackets with `)}`

### ISSUE THREAD

**Issue by prencher** [Microsoft/vscode#5630]
- VSCode Version: 1.0
- OS Version: Any

When formatting a TSX document, `<span onClick={this.test()}>` gets formatted as `<span onClick={this.test() }>`.

It appears isolated to `)`, for example `<span onClick={this.test}>` is unaffected, as is every other case I could think of to test.

I would assume this is supposed to not have spaces, or respect the non-empty bracket setting added in 1.0.

**Comment by dbaeumer** [comment]
Agree. Moving to the TS team which provides the formatter.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#8246
