### ISSUE TITLE
在大量Html文件中进行文本检索，字符匹配异常

### ISSUE THREAD

**Issue by CallMeR** [Microsoft/vscode#56309]
- VSCode Version: Latest 1.26.0 1.25.1
- OS Version:Windows10  Ubuntu18.04

Steps to Reproduce:

1.在项目文件夹中载入大量的html文件。
2.进行某关键字搜索
3.设置为全字匹配模式
4.依次点击搜索结果，右侧对应的文件会出现如图所示的异常。
5.正则匹配模式，也有类似问题。

![tim 20180814151019](https://user-images.githubusercontent.com/11908641/44077176-52881d6c-9fd5-11e8-9cc2-e3ba55da0704.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
@CallMeR Can you please provide the summary and steps to reproduce in English?

**Comment by CallMeR** [comment]
1.In vscode and open a project folder.
2.Toggle to search，input some key words.
3.When Vscode output the result，it acts in the git blow.

![vscode](https://user-images.githubusercontent.com/11908641/44127289-3977da3e-a06f-11e8-923a-7d0221087297.gif)

Maybe it is relate to the file name  : )

**Comment by CallMeR** [comment]
I've E-mail you a default.7z which content the origin files.
default.7z hash:
sha256sum-9D5B305E13F2D5ACD3F8B5524C2149D9C342A17134C85DAA6D6D35DF0ECBF463

**Comment by roblourens** [comment]
This is due to your files having CR line endings. I'm seeing \r\r\n for each line ending. So, a CR then a CRLF. Not sure how you ended up that way, but if you edit the file in vscode then save it, it fixes the line endings, and then search works. https://github.com/Microsoft/vscode/issues/35797
