### ISSUE TITLE
Cannot show "Compare Selected" menu item for two unsaved "Untitled" files in View -> Explorer

### ISSUE THREAD

**Issue by johnnytemp** [Microsoft/vscode#56316]
- VSCode Version: 1.26.0
- OS Version: macOS 10.13.6

Steps to Reproduce:

1. Cmd-N twice to New two files, type "abc" in each document.
2. menu View -> Explorer, focus in "Open Editors" and select only the two new files, right click over "one of them", there should be "Compare Selected" menu item.  However, it is missing.  Only these 4 items is showing now: "Close", "Close Others", "Close Saved", "Close All".

(An in-pretty workaround I found is to right-click over another saved file when the two "Untitled" files selected.  However, it is difficult for users to find this trick, and should need a real fix)

Does this issue occur when all extensions are disabled?: Yes

**Comment by johnnytemp** [comment]
Seems reported and maybe fixed in 1.27.0 preview.  Will wait to try if ok in next version.

**Comment by johnnytemp** [comment]
But it is strange that until 1.26.0 this issue is still un-fixed, as the issue has been reported in like #42598 ?  Will it really work on next version?

**Comment by isidorn** [comment]
This works for me in latest stable and latest vscode insiders on os x
Please let me know what you are doing differently than me

![compare](https://user-images.githubusercontent.com/1926584/44137606-4d1ff484-a071-11e8-93e2-4c57c1931810.gif)

**Comment by johnnytemp** [comment]
Although I tested it work in latest vscode insiders preview, just worry that such code will be release in next minor version or not.  (Since the related tickets is closed long ago, but still not fixed in the recent released version).  Welcome to close it, and if next minor version not work, I will reopen it.

Thank you.

**Comment by wthenrichs** [comment]
I am also experiencing this issue. 
I'm exclusively using the Insiders preview.
The issue only appears if I open a new empty window of vs code. If I open a folder, I'm able to compare both saved, and unsaved files.
If it helps the context menu for the windows which have this problem only show 5 options:
Save As...
Close
Close Others
Close Saved [Ctrl+K U]
Close All [Ctrl+K W]


Current Versions:
Version: 1.27.0-insider
Commit: 346018a80dd299c50cbf213e0a706ef0f35f3a67
Date: 2018-08-24T05:19:27.628Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64


Please let me know if I can provide any more information.

**Comment by isidorn** [comment]
@wthenrichs can you please provide a gif, or a picture of what you are exactly doing. Step by step would also help

**Comment by wthenrichs** [comment]
I've attached two gifs. 
The first is of a new vscode window that is empty.
The second is a vscode windows which was empty but I opened a folder via File > Open Folder.
The folder is called demo and is an empty folder.

![new_window_no_compare](https://user-images.githubusercontent.com/1435012/44590313-d5d99f00-a788-11e8-8be1-4dd2dadccd25.gif)


![open_folder_compare](https://user-images.githubusercontent.com/1435012/44590323-db36e980-a788-11e8-8186-87e1a74d75ca.gif)

**Comment by isidorn** [comment]
@wthenrichs thanks for the lovely gifs.

@bpasero @jrieken this issue seems to be that `canHandleResource('untitled')` always returns `false`. How should we handle the `untitled` case?
@jrieken this seems to have broken this https://github.com/Microsoft/vscode/commit/76f25881115baabcd1027307cde56664d6c2b534
