### ISSUE TITLE
breadcrumb dropdown panel name truncation

### ISSUE THREAD

**Issue by boyvinall** [Microsoft/vscode#56318]
Issue Type: <b>Bug</b>

1. Install `ms-vscode.go` extension
2. Open a `.go` file containing struct method names or struct names longer than 20 chars
3. Enable breadcrumbs
4. Click on the struct name

The names in the dropdown could be more useful .. at the moment, the ellipsis truncation prevents seeing the details you care about. 

VS Code version: Code - Insiders 1.27.0-insider (8727085fff33bf7d8f5e27483b10f72508d4167a, 2018-08-14T05:12:11.579Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.72GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_1761710|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
EditorConfig|Edi|0.12.4
gitlens|eam|8.5.4
VS-code-vagrantfile|mar|0.0.7
hg|mrc|1.2.3
Go|ms-|0.6.86
indent-rainbow|ode|7.2.2

</details>

Screenshot below from following source code `test.go`:
```
package foo

type ImageCatalogueServer struct {}

func (s *ImageCatalogueServer) DoSomething() {}
func (s *ImageCatalogueServer) Speak() {}
```

![screen shot 2018-08-14 at 09 21 15](https://user-images.githubusercontent.com/1652176/44080264-73de5b66-9fa3-11e8-9796-9165f53ba01a.png)

**Comment by boyvinall** [comment]
Not sure whether this is also related to a previous issue I raised https://github.com/Microsoft/vscode/issues/10941, see also related issue for that one https://github.com/electron/electron/issues/6993

**Comment by jrieken** [comment]
Well, the name is the name but we can make the dropdown a little wider so that there is more space. We can also make sure the label has a title set

**Comment by boyvinall** [comment]
Thanks @jrieken.  Is it possible to change the ellipsis truncation so that it happens at the beginning/middle, not at at the end?

**Comment by jrieken** [comment]
Tricky... Currently, it's the browser adding those, not us.

**Comment by antcodd** [comment]
The current popup width is definitely far too narrow for descriptive function names in various languages. The above examples would be some of the shorter names in a non object-oriented non-overloading language like C that I work with.

Why not make the popup the same width as one of:
* the completion popup (preferably the wider version when the information panel isn't open). Perhaps it would be possible to even include some of the additional information from that longer term?
* at least the default side panel width (which I tend to find a little to narrow but generally gets the first few letters)
* resize to fit the widest item. It looks like it might currently be based loosely on the current (possibly truncated) breadcrumb item?

It would be even better if the popups were resizeable (preferably by dragging, but a config setting would work). Basically all other panels that can show a function signature are significantly wider and/or can be resized. There is already a lot of wasted space from chevron arrow expansions.

As for the breadcrumbs themselves, why are they truncated at all when there is available viewport width? You are likely have half a screen or more there.

**Comment by jrieken** [comment]
The panel is now proportional to the window width. Also, a title is assigned and the max-width restriction for breadcrumb items has been relaxed.
