### ISSUE TITLE
Function description and return value information is missing on Intellisense pop-up.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#5631]
- VSCode Version: 1.0.1-alpha
- OS Version: winodws10

Steps to Reproduce:
1. Launch app and open any folder which contains ts file.
2. Add below code in ts and verify intellisense for getElementById function.

    init: (s:string,p:string,c:string)=> void = function (startButton,pauseButton, clearButton) {
        document.getElementById(startButton)
    }
    
Actual: Getting param info, quick ino but API description and return information is missing.
![image](https://cloud.githubusercontent.com/assets/17735796/14726598/340a2e12-07d8-11e6-9204-fb736c9baff7.png)

Expected: Intellisense should display info about return value.
![image](https://cloud.githubusercontent.com/assets/17735796/14726620/597d320c-07d8-11e6-9248-d6c341501ead.png)

**Comment by dbaeumer** [comment]
I disagree: The return info is correctly shown when you select the method in intellisense. In this show situation it is all about method parameter hints. So to not confuse we only show the info for the parameter. Of what value is it if I complete the first parameter to know what value the function returns.
