### ISSUE TITLE
Not able to view debug console while debugging an extension without an open folder

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5632]
- VSCode Version: 1.0.1-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Start debugging an extension you wrote
2. Make sure the dev host did not open a folder or close the open folder in the host.
3. View > Toggle Debug Console

By default it opens a new window with no folder opened, which inherently doesn't allow you to view the debug console. It would be useful to see debug output in a dev host instance when creating or debugging an extension even without an open folder.

**Comment by isidorn** [comment]
Similar to #5633 this is designed behavior. The dev host window console is not indented to be used to inspect the dev host behvaior, for that you have the console in the original vs code.

Also closing as designed. Feel free to provide arguments as to why you disagree and we can reopen the issue.
