### ISSUE TITLE
rg.exe causes high cpu usage

### ISSUE THREAD

**Issue by yume-chan** [Microsoft/vscode#56328]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/1330321/44083857-b3f74f2a-9fe7-11e8-8484-cc7cb69563c3.png)

Command line:

````
C:\Users\Simon\OneDrive\Tools\Microsoft VS Code Insiders\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe" --files --hidden --case-sensitive -g **/tsconfig.json -g **/jsconfig.json -g **/tsconfig.*.json -g **/jsconfig.*.json --no-ignore --follow --quiet -- .
````

I understand what rg.exe is, and I have disabled all extensions, so I suspect it's caused by the built-in TypeScript extension.

VS Code version: Code - Insiders 1.27.0-insider (8727085fff33bf7d8f5e27483b10f72508d4167a, 2018-08-14T05:18:11.938Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3504)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (2.57GB free)|
|Process Argv|C:\Users\Simon\OneDrive\Tools\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by season19840122** [comment]
@yume-chan After the 1.26 version is installed, the CPU is high. I installed the 1.25.1 version and it is normal.

**Comment by medikoo** [comment]
I observe same thing on macOS after upgrading to 1.26

**Comment by roblourens** [comment]
This looks like #55649
