### ISSUE TITLE
don't copy the styles of the text when doing copy & paste of a line of code (e.g. into outlook)

### ISSUE THREAD

**Issue by lnaie** [Microsoft/vscode#56323]
hi,

i find it odd that the text that is being copied, by default, also copies the style of the background besides the style of the text (which btw is also not needed). wth?!

please fix that.

regards,
Lucian

![vs_code_issue](https://user-images.githubusercontent.com/1276077/44081507-22a6a292-9faf-11e8-990d-72b986aa777e.jpg)

**Comment by rebornix** [comment]
Close in favor of https://github.com/Microsoft/vscode/issues/21071#issuecomment-418887276. Thanks for your feedback.
