### ISSUE TITLE
Syntax highlight error in markdown file C code block define macro

### ISSUE THREAD

**Issue by RedLeavesSun** [Microsoft/vscode#56322]
- VSCode Version:1.26

use the code follow in markdown file C style code block will syntax highlight error

void mem_init(void)
{
#define MLK(b, t) b, t, ((t) - (b)) >> 10
#define MLM(b, t) b, t, ((t) - (b)) >> 20
#define MLG(b, t) b, t, ((t) - (b)) >> 30
#define MLK_ROUNDUP(b, t) b, t, DIV_ROUND_UP(((t) - (b)), SZ_1K)

#undef MLK
#undef MLM
#undef MLK_ROUNDUP
}

Does this issue occur when all extensions are disabled?: No

**Comment by mjbvz** [comment]
Upstream issue that is not fixable on our side. See explanation in https://github.com/Microsoft/vscode/issues/34525
