### ISSUE TITLE
False unused variable warnings

### ISSUE THREAD

**Issue by d8elessar** [Microsoft/vscode#56321]
Issue Type: <b>Bug</b>

I get too many warning for unused variables that are actually used in the same JS function.
For example:

```js
        var VerifyAddressConfig = {};//gets false warning
        var VerifyAddressTemplate = {};//gets false warning
(...)
          this.VerifyAddressConfig = AppFacade.Utilities.GetJSON(
            "VerifyAddressConfig.json"
          );
          this.VerifyAddressTemplate = AppFacade.Utilities.GetJSON(
            "VerifyAddressTemplate.json"
          );
```
P.S.: Sometimes it works fine.

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz (2 x 2000)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|8.00GB (2.57GB free)|
|Process Argv|C:\Users\VALERAL\AppData\Local\Programs\Microsoft VS Code\Code.exe C:\SVN\compass-9.0\webserver\PUBLIC\scripts\siebel\custom\DynamicSearchFormPM.js|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
color-info|bie|0.5.0
regex|chr|0.2.0
vscode-svgviewer|css|1.4.4
xml|Dot|2.3.1
prettier-vscode|esb|1.6.1
beautify|Hoo|1.3.2
minify|Hoo|0.3.0
icon-fonts|idl|2.1.1
vsliveshare|ms-|0.3.535
debugger-for-chrome|msj|4.8.2
vscode-css-peek|pra|2.1.0
live-sass|rit|3.0.0
LiveServer|rit|5.1.1
sass-indented|rob|1.4.9
stylelint|shi|0.38.1
vscode-todo-highlight|way|1.0.4
plsql-language|xyz|1.4.2

</details>

**Comment by yume-chan** [comment]
From your code, I can not see any usage of your `VerifyAddressConfig` and `VerifyAddressConfig` variables.

**Comment by d8elessar** [comment]
Sorry about that, the example wasn't clear.
Here are some more details:
In a single JS file, with multiple functions, VerifyAddressConfig is used like a global variable, being assigned in the DynamicSearchFormPM.prototype.Init, and then tested on the OnFieldChange function:

function () {
	AppFacade.DynamicSearchFormPM = (function () {
		var VerifyAddressConfig = {};
		var VerifyAddressTemplate = {};

		DynamicSearchFormPM.prototype.Init = function () {
			AppFacade.DynamicSearchFormPM.superclass.Init.call(this);

			this.consentCountries = AppFacade.Utilities.GetJSON(
					"ConsentCountries.json");

			this.VerifyAddressConfig = AppFacade.Utilities.GetJSON(
					"VerifyAddressConfig.json");
			this.VerifyAddressTemplate = AppFacade.Utilities.GetJSON(
					"VerifyAddressTemplate.json");
			this.AddMethod("FieldChange", OnFieldChange, {
				sequence: false,
				scope: this
			});
			
		};

		function OnFieldChange(control, value) {
			<some unrelated code>

			if (
				typeof this.VerifyAddressConfig[this.GetObjName()] != "undefined") {
				if (
					typeof this.VerifyAddressConfig[this.GetObjName()]["Controls"][
						control.GetName()
					] != "undefined") {
					if (
						<some unrelated code>
					}
				}
			}
		}

		return DynamicSearchFormPM;
	})();
	return "AppFacade.DynamicSearchFormPM";
}

Is it possible to avoid false positives in this scenario?

About the VerifyAddressTemplate variable, it is referenced by another JS file so I guess there is nothing that can be done in this case.

**Comment by mjbvz** [comment]
Sorry but the example really makes no sense. Shouldn't it be `VerifyAddressConfig` instead of  `this.VerifyAddressConfig`?
