### ISSUE TITLE
SignatureHelp gets confused when parameter labels are contained in function signature

### ISSUE THREAD

**Issue by ilya-biryukov** [Microsoft/vscode#56337]
- VSCode Version: 1.25
- OS Version: Debian 9

While working on [vscode-clangd](https://github.com/llvm-mirror/clang-tools-extra/tree/master/clangd/clients/clangd-vscode), we ran into a problem with `signatureHelp`

For the following code:
```cpp
int foo(int, int);

void bar() {
  foo(^10) // <-- call signatureHelp at '^'
}
```

We want to show a signature with a label `foo(int, int) -> int` (note the result type is at the end).
Since both the parameters and the return types are `int`, there are multiple possibilities for finding parameter ranges inside the signature label.
VSCode chooses incorrect ranges in our case, highlighting the second parameter instead of the first one:
![image](https://user-images.githubusercontent.com/809452/44086344-8a937f30-9fbc-11e8-8430-21fc33955016.png)

LSP response we send to VSCode:
```json
{
  "jsonrpc": "2.0",
  "result": {
    "activeParameter": 0,
    "activeSignature": 0,
    "signatures": [{
        "label": "foo(int, int) -> int",  
        "parameters": [{"label": "int"}, {"label": "int"}]
    }]
  }
}
```

It would be nice to allow specifying the ranges of parameters in the signature labels to avoid multiple interpretations of the response. Would it be reasonable to add that option to VSCode? Any other ideas on how we could fix this?

**Comment by jrieken** [comment]
This is a problem with our API. We always use the signature label and try to find (indexOf) the active parameter. Instead, we should allow parameters to provide a range which denotes the substring in the signature label that represents it.

**Comment by jrieken** [comment]
We could try to get away with something like this

```ts
export class ParameterInformation {
   /**
    * The start and end offset where this label occur in its contain signature 
    * label. Defaults to `label.lastIndexOf(this.label)`
    */
   labelRange?: [number, number]
}

```

**Comment by bobbrow** [comment]
Do you need an API for this, or can VSCode just limit the search to the text within the parentheses?

**Comment by jrieken** [comment]
I think API is needed for cases where parameter names repeat

**Comment by bobbrow** [comment]
Perhaps I don't understand.  It seems to work for me with repeating names:

![image](http://g.recordit.co/YFXLl3Vyhs.gif)

```
{
    "jsonrpc": "2.0",
    "id": 5,
    "result": {
        "signatures": [
            {
                "label": "int getInt(int, int, int)",
                "parameters": [
                    {
                        "label": "int"
                    },
                    {
                        "label": "int"
                    },
                    {
                        "label": "int"
                    }
                ]
            }
        ],
        "activeSignature": 0,
        "activeParameter": 0
    }
}
```

**Comment by jrieken** [comment]
So, this works by going backwards through the list of parameters and that's a pretty good heuristic. The problem is that we don't know the range to look at, e.g we don't know that you use parentheses to separate parameters (tho it might be a fair guess...)

**Comment by jrieken** [comment]
This is what's up for finalization: https://github.com/Microsoft/vscode/blob/fdf2dec52d1bafd37978e8cdf24371af7f49f8e7/src/vs/vscode.d.ts#L3025-L3032

**Comment by KamasamaK** [comment]
Shouldn't the constructor's `label` type be updated too?
