### ISSUE TITLE
Allow to move quick open and quick input

### ISSUE THREAD

**Issue by gdh1995** [microsoft/vscode#56333]
I'd like to move down the command palette (toggled by `ctrl+shift+p` / `ctrl+p`) to make the list center of the whole window (also center of the whole screen), so that I don't need to raise my head and adjust my glasses to see it clearly. The result might be like this:

![image](https://user-images.githubusercontent.com/5547703/44085785-1d12697c-9fed-11e8-904c-7907172f1c7f.png)

Maybe I can achieve the same effect by creating a new theme, but it seems too heavy to apply an new theme.

**Comment by mannfuri** [comment]
NEED THIS

**Comment by danielmcmillan** [comment]
This feature was recently completed https://github.com/microsoft/vscode/issues/17268, this was a duplicate.
