### ISSUE TITLE
Problem with PHP formatting in javascript tag

### ISSUE THREAD

**Issue by JohnyByk** [Microsoft/vscode#56339]
Hi.

I have problem with PHP code formatting in javascript tag. This problem appear on save.
Here is example.
[https://www.youtube.com/watch?v=rad9fqusTyg](url)

My custom config.
`"php.validate.run": "onType",
    "workbench.sideBar.location": "left",
    "editor.minimap.enabled": false,
    "workbench.startupEditor": "newUntitledFile",
    "git.autofetch": true,
    "workbench.list.openMode": "doubleClick",
    "editor.occurrencesHighlight": false,
    "emmet.triggerExpansionOnTab": true,
    "editor.wordSeparators": "`~!@#%^&*()-=+[{]}\\|;:'\",.<>/?",
    "workbench.iconTheme": "file-icons",
    "json.format.enable": false,`

Is any way to resolve this problem?
Regards

**Comment by roblourens** [comment]
What are you showing exactly? Please include exact steps to repro the issue.
