### ISSUE TITLE
[json] support JSON-LD

### ISSUE THREAD

**Issue by Sneezry** [microsoft/vscode#56334]
VS Code has already had built-in JSON schema support. It would be great if VS Code had [JSON-LD](https://json-ld.org/) support for json file.

**Comment by aeschli** [comment]
Can you elaborate what you want to be added?

You can already associate your json file with a scheme. See https://code.visualstudio.com/docs/languages/json#_json-schemas-settings.

**Comment by Sneezry** [comment]
Hi @aeschli , thanks for reply. JSON schema dosen't work well with JSON-LD. JSON schema and JSON-LD are two different things to description JSON files. Here's a discussion on relationship between JSON schema and JSON-LD: https://lists.w3.org/Archives/Public/public-linked-json/2014Oct/0010.html

**Comment by aeschli** [comment]
I understand that JSON schema and JSON LD are not same. 

What, from an editor perspective, can we provide to make editing JSON-LD easier.
Configuring a schema will help you with code completion and validation for property names and some of the static values sets.

What kind of other support were you thinking of?

**Comment by Sneezry** [comment]
We tried to use schema to edit JSON-LD documentation. But it doesn't work well.

For example, we have an object to describe motion state of an aircraft with JSON-LD:

```
{
  "@id": "http://example.com/aircraft/speed"
  "@context": "http://example.com/aircraft.json",
  "@type": "Object",
  "name": "speed",
  "fields": [
    {
      "name": "x",
      "unit": "kmph",
      "valueType": "double"
    },
    {
      "name": "y",
      "unit": "kmph",
      "valueType": "double"
    },
    {
      "name": "z",
      "unit": "kmph",
      "valueType": "double"
    }
  ]
}
```

`x`, `y`, `z` all are required, and we cannot have more than one field share the same name (object cannot have two properties with the same key). It seems impossible to do that with JSON schema.

**Comment by alexkreidler** [comment]
Hey @Sneezry I noticed in #63270 you mentioned you were building a JSON-LD language server. If you were to open source your work on this, I could take a look and would be happy to try integrating it into the existing JSON language server.

I might also try just writing one on my own, but it could be very helpful. Thanks!

**Comment by benatkin** [comment]
I suggest having a contribution point so an extension can easily provide support for a JSON document based on `@context` https://github.com/microsoft/vscode/issues/98442
