### ISSUE TITLE
(Ctrl + ) F5 opening new terminal everytime

### ISSUE THREAD

**Issue by sandeepjana** [Microsoft/vscode#56341]
Issue Type: <b>Bug</b>

I am working on Python project. Whenever try running debugger, it creates a new terminal. Why can't it reuse the same open terminal?

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.92GB (0.61GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.5.4
python|ms-|2018.7.1
vscodeintellicode|Vis|1.0.3

</details>

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-python/

**Comment by Ragnoroct** [comment]
I've posted the same type of bug on their repo. This only happens with `git bash/msys`
https://github.com/Microsoft/vscode-python/issues/2391
They closed it saying come to you. Something about vscode not liking the configuration of the terminal.

**Comment by Tyriar** [comment]
@Ragnoroct if it affects those shells only then this is likely an issue related to winpty https://github.com/Microsoft/vscode/issues/45693
