### ISSUE TITLE
Middle click and drag down selects too much

### ISSUE THREAD

**Issue by jonadem** [microsoft/vscode#56345]
![vs_bug](https://user-images.githubusercontent.com/5641556/44089863-9551cad8-9fc8-11e8-94fa-51a92890fcc1.gif)

- VSCode Version: 1.26.0
- OS Version: Win 10

Steps to Reproduce:

1. Create a text where the first line is shorter than another one
2. Middle click and drag down to the longest line
3. A part of the line is selected although the requested behavior is to select only each end of lines (as it is with Sublime Text)

**Comment by alexandrudima** [comment]
Duplicate of #49454
