### ISSUE TITLE
Breadcrumbs does not found any python methods and classes

### ISSUE THREAD

**Issue by mklemarczyk** [Microsoft/vscode#56347]
Breadcrumbs feature does not found any python methods and classes.
It shows only the python files without detecting the content.

- VSCode Version: 1.26.0
- OS Version: Windows 10 1803

Steps to Reproduce:
1. Open any folder with python scripts
2. Toggle on the Breadcrumbs

Does this issue occur when all extensions are disabled?: Yes

**Comment by mklemarczyk** [comment]
Hi there. I have vs code installed without extensions. Please notice that, so it can not be caused by extension in my case.

**Comment by mklemarczyk** [comment]
@jrieken if you are right there should be an information about that. There is nothing like so in the release notes and vs code docs.

**Comment by jrieken** [comment]
> Breadcrumbs always show the file path and, with the help of extensions, the symbol path up to the cursor position. The symbols shown are the same as in Outline view and Go to Symbol and so existing extensions will just work with breadcrumbs.
