### ISSUE TITLE
Handlebars indenting else if clause one more level than expected.

### ISSUE THREAD

**Issue by Serabe** [Microsoft/vscode#56346]
- VSCode Version: 1.26.0 and 1.27.0-insider
- OS Version: macOS High Sierra 10.13.6 (17G65)

Steps to Reproduce:

1. On a clean install, set "html.format.indentHandlebars" and "editor.formatOnSave" to true (the latter is not needed, but helps checking the issue.
2. Create a new handlebars file and add the code you see at the end of this bug report.
3. Save the file. It will indent the else if clause when it shouldn't (as it used to work in latest 1.25.

If this change is intentional, can we make it configurable?

Thanks!

Does this issue occur when all extensions are disabled?: Yes

```hbs
{{! Actual file }}
{{#if something}}
    <div></div>
{{else if somethingElse}}
    <span></span>
{{/if}}
```
```hbs
{{! File after wrong indentation }}
{{#if something}}
    <div></div>
    {{else if somethingElse}}
    <span></span>
{{/if}}
```

**Comment by aeschli** [comment]
We use [beautifyjs](http://jsbeautifier.org/) as the underlying HTML formatter. Would you mind filing this request directly against https://github.com/beautify-web/js-beautify ?

**Comment by aeschli** [comment]
We use [beautifyjs](http://jsbeautifier.org/) as the underlying HTML formatter. Would you mind filing this request directly against https://github.com/beautify-web/js-beautify ?

**Comment by Serabe** [comment]
Checked there and it is fixed in the latest RC. Hopefully, 1.8 will be released before the next VSCode version. Thanks!
