### ISSUE TITLE
Typescript intellisense does not recognize 'delete'd attributes

### ISSUE THREAD

**Issue by Barbiero** [Microsoft/vscode#56340]
Whenever you `delete`an attribute from an object, I'd expect intellisense to recognize that said attribute was removed.
Example of the problem:
![example](https://user-images.githubusercontent.com/5532443/44088985-8b44ed0e-9f9b-11e8-95a2-e5e1476943db.png)

The expected behavior would be for the autocomplete feature to NOT show the `date` attribute. Furthermore, if I were to call anything over said property(say, `example.date.toISOString()`) it should warn me of the undefined call. `delete`ing an attribute from a class/interface that does not define it as an optional attribute should also be an error IMO, though I don't know how feasible that is.

Either way, VSCode(or the typescript language server?) has no support for the side effects of `delete` atm.

- VSCode Version: 1.26

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#26549
