### ISSUE TITLE
VSCode break down when open python file(about 4000 lines) in version 1.26

### ISSUE THREAD

**Issue by cloudeal** [Microsoft/vscode#56349]
Issue Type: <b>Bug</b>

when i open a big python file(4000 line),vscode will break down after version 1.25.1 .and before 1.26,it can work very well.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:40:20.190Z)
OS version: Linux x64 4.15.0-30-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2598)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|7.70GB (1.38GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-css-formatter|aes|1.0.1
Bookmarks|ale|9.0.3
expressjs|ama|2.0.0
vscode-eslint|dba|1.4.12
githistory|don|0.4.2
gitlens|eam|8.5.4
node-module-intellisense|lei|1.5.0
vscode-jade-snippets|mrm|1.0.1
vscode-pugbeautify|mrm|1.0.2
vscode-language-pack-zh-hans|MS-|1.26.3
python|ms-|2018.7.1
debugger-for-chrome|msj|4.8.2
LiveServer|rit|5.1.1
vscode-icons|rob|7.25.0
code-settings-sync|Sha|3.0.0

(1 theme extensions excluded)

</details>

**Comment by cloudeal** [comment]
@rebornix Problem resolved after 1.26.1

**Comment by rebornix** [comment]
Thanks!
