### ISSUE TITLE
Terminal output sometimes doesn't generate links to code locations

### ISSUE THREAD

**Issue by Gurkenglas** [Microsoft/vscode#56355]
Issue Type: <b>Bug</b>

Install stack and build probably any project with compiler errors.

Sometimes links are generated, which made me realize that probably they should always be.

It might take you a while to build what I'm working on, but here's a branch: https://github.com/Gurkenglas/haskell-ide-engine/tree/missinglink

Or is it obvious from the terminal output why `Haskell\Ide\Engine\PluginsIdeMonads.hs:67:1` isn't turned into a link?

![](https://i.gyazo.com/367ee375f851eed7c531cf9162007b66.png)

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz (4 x 3293)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.92GB (3.11GB free)|
|Process Argv|D:\VSCode\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
