### ISSUE TITLE
Use code editor widget for rename widget

### ISSUE THREAD

**Issue by ravshansbox** [Microsoft/vscode#56351]
None of these commands work on "Rename symbol":
![image](https://user-images.githubusercontent.com/1499188/44093267-79e26a54-9fec-11e8-8105-532998c4ad04.png)

**Comment by jrieken** [comment]
Yep - it's not an editor but just a textbook.

**Comment by V-ed** [comment]
Related to #53498

Not a duplicate as it is more specific.

**Comment by V-ed** [comment]
I found that this issue is a duplicate of #53666
