### ISSUE TITLE
VSCode is hanging when I open the powershell script

### ISSUE THREAD

**Issue by rameshc-git** [Microsoft/vscode#56358]
Hi,

After update the recent version 1.26. I'm not able to open the ps1 file using Visual Studio Code. Please find the attached image for your reference. Thanks.

![vscode_hanging](https://user-images.githubusercontent.com/16361037/44095197-d68e8cde-9ff5-11e8-8a99-04610ed8ff6e.JPG)

**Comment by aeschli** [comment]
@rameshc-git Can you please share the input file?

**Comment by rameshc-git** [comment]
@aeschli It's powershell script having more than 10k lines code and also i can't share it due to organization policy. Is there any logs i can check vscode installed path?

**Comment by aeschli** [comment]
duplicate of #56430
