### ISSUE TITLE
UI should be localized according to the locale.json setting when execute "Reload window" command.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#5635]
- VSCode Version: 1.0.1-alpha
- OS Version: Windows10
Steps to Reproduce:
1. Launch app.
2. Launch command palette and type "configure Language".
3. Set the locale setting (e.g. 'ko') and save the changes.
4. Execute "Reload window" from command palette.
4. Verify UI for the targeted locale.

Actual: No changes on UI after reload and user has to close app manually to get the changes.
Expected: When user execute the "Reload window" command then UI should be loaded according to the locale setting provided in locale.json file.

**Comment by dbaeumer** [comment]
This is a technical limitation and can't be fixed. There is a main process that starts everything and determines the language to be used (necessary for menus which for example are shared on Mac). This process doesn't restart on a window reload.
