### ISSUE TITLE
Maximize Editor Group doesn't work/not a setting

### ISSUE THREAD

**Issue by philstach3** [Microsoft/vscode#56353]
- VSCode Version: 1.26.0
- OS Version: Mac OSX 10.12.6

Steps to Reproduce:

1. Open Settings (User or Workspace)
2. Search for either "Maximize Editor Group" or "workbench.action.minimizeOtherEditors"
3. The setting does not appear to be found.

The latest updates says it should be working, and I think even turned on by default, but I can't seem to find it or get it to work.

**Comment by bpasero** [comment]
This is not a setting but a command.

**Comment by philstach3** [comment]
@bpasero okay, but the command is not working and I can't find the setting for the command. Not sure if my wording is incorrect, but the feature seems to be not working.

**Comment by bpasero** [comment]
![before](https://user-images.githubusercontent.com/900690/44108121-bac1931c-9ff9-11e8-92b2-1cb8d9f58e35.gif)

It works just fine for me.

**Comment by philstach3** [comment]
Looks like I had to fully close and reopen VS Code. I was still running on the reopened window after the update, and that menu option to enable/disable it that you show wasn't there originally, but it's there now. Sorry for the ticket!
