### ISSUE TITLE
Unresponsive VSCode after upgrade to 1.26.

### ISSUE THREAD

**Issue by kabforks** [Microsoft/vscode#56364]
Hello! 

After installing VSCode 1.26, the GUI is almost completely unresponsive when I open my project. After a few minutes, it can be used. However, the CPU usage will remain at 24% (i have 4 cores). Even after the project or folder is closed.

If I open VSCode without a project or folder, it behaves.

VSCode is responsive if launched with --disable-extensions.

Could it be an extentions that misbehaves?

Here is a --status dump:

> Version:          Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
> OS Version:       Windows_NT x64 10.0.16299
> CPUs:             Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)
> Memory (System):  15.85GB (3.24GB free)
> VM:               0%
> Screen Reader:    no
> Process Argv:     C:\Users\forsbdan\AppData\Local\Programs\Microsoft VS Code\Code.exe
> GPU Status:       2d_canvas:                    enabled
>                   checker_imaging:              disabled_off
>                   flash_3d:                     enabled
>                   flash_stage3d:                enabled
>                   flash_stage3d_baseline:       enabled
>                   gpu_compositing:              enabled
>                   multiple_raster_threads:      enabled_on
>                   native_gpu_memory_buffers:    disabled_software
>                   rasterization:                enabled
>                   video_decode:                 enabled
>                   video_encode:                 enabled
>                   webgl:                        enabled
>                   webgl2:                       enabled
> 
> CPU %   Mem MB     PID  Process
>     0      100   34680  code main
>     0       84   22972     shared-process
>     0      146   23460     gpu-process
>    23     1271   28764     window (Program.cs - demo2 - Visual Studio Code)
>     0        6   26188       winpty-process
>     0       65   16204         C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
>     0       10   19472         console-window-host (Windows internal process)
>     0       51   30296       searchService
>     0       14   31020       electron-crash-reporter
>     0       11   31384       watcherService
>     0       10   21716         console-window-host (Windows internal process)
>     0      191   33784       extensionHost
>     0       38   22568         searchService
>     0        3   37816         cmd /s /c "C:\Users\forsbdan\.vscode\extensions\ms-vscode.csharp-1.15.2\.omnisharp\1.30.1\OmniSharp.exe -s c:\src\demo2\Fagkveld.sln --hostPID 33784 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4"
>     0       10    7140           console-window-host (Windows internal process)
>     0      115   19888           C:\Users\forsbdan\.vscode\extensions\ms-vscode.csharp-1.15.2\.omnisharp\1.30.1\OmniSharp.exe  -s c:\src\demo2\Fagkveld.sln --hostPID 33784 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4
> 
> Workspace Stats:
> |  Window (Program.cs - demo2 - Visual Studio Code)
> |    Folder (demo2): 83 files
> |      File types: json(15) cshtml(12) cs(8) js(5) ts(5) scss(5) cache(5)
> |                  map(3) vue(3) txt(2)
> |      Conf files: launch.json(2) tasks.json(2) sln(1) csproj(1)
> |                  package.json(1) tsconfig.json(1) webpack.config.js(1)
> |                  settings.json(1)
> |      Launch Configs: coreclr(2)

**Comment by ly-cultureiq** [comment]
experiencing the same issue - for a split second i can click into the text area but within a second the ui is unresponsive and after a minute the entire app show a "this window is no longer responding message"

**Comment by jtr109** [comment]
@ly-cultureiq Thanks for your references.

By the way, I think it isn't cause by the size of python file but syntax color rendering. Could you please have a try on the following code in a new `.py` file with python mode.

_By the way, remember to test it in a new workspace in case of crashing your own workspace._

```
record = {
    "headers": {k: str(v) for k, v in self.request.META.items() if k.startswith('HTTP_')}
}
```

**Comment by isidorn** [comment]
@ly-cultureiq @jtr109 please file that against the python extension
@kabforks can you also reproduce this if you open an empty vscode window? Or you only see it if you open a C# project? Do you also see the freeze if you disable the c# extension?

**Comment by jtr109** [comment]
Hi @isidorn:

Thanks for your reply.

I comment with my screenshot in the issue I reported. Unfortunately, the issue I meet can reproduced with python extension disabled.

**Comment by isidorn** [comment]
Forwarding to @aeschli since he is handling all these not repsonsive language issues with the new update

**Comment by aeschli** [comment]
dup of #56377
