### ISSUE TITLE
Breadcrumbs show a separator before first item, if custom colors defined

### ISSUE THREAD

**Issue by lllopo** [Microsoft/vscode#56362]
If a custom color is defined in the VS Code settings, this adds a <style> definition in the breadcrumbs container. VS Code CSS uses ":not(:first-child)" to avoid a separator on first item, but since the <style> definition becomes first child, this actually breaks the CSS and a separator appears. Possible ways to avoid this is either to add the <style> tag elswhere or to use ":first-of-type" to make sure the separator of the first div gets hidden.

**Comment by jrieken** [comment]
Can you please provide a sample and a screenshot.

**Comment by lllopo** [comment]
A screenshot with explanation follows, although I'm a bit wrong - it happens all the time. Simply the "style" element breaks the CSS condition. There you go :

![clipboard 1](https://user-images.githubusercontent.com/5485902/44169463-2abc4c00-a0dd-11e8-9308-97f58c250a33.png)
