### ISSUE TITLE
VSCode failing to update

### ISSUE THREAD

**Issue by iansan5653** [Microsoft/vscode#56363]
This morning, I used the gear menu -> Restart to update to update my Code installation. After attempting to install the update, I see the following error: 
![image](https://user-images.githubusercontent.com/2294248/44095572-2793666c-9fa7-11e8-96c7-0ad3638dfc03.png)
I'm using VSCode Insiders on Windows 10, and I updated yesterday. 
The aforementioned log file is here: 
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2287159/vscode-inno-updater.log)

- VSCode Version:
![image](https://user-images.githubusercontent.com/2294248/44095961-1c31a04e-9fa8-11e8-8b9e-37cda95f5d2c.png)

- OS Version:
![image](https://user-images.githubusercontent.com/2294248/44095997-2c236244-9fa8-11e8-8561-d3f5e66ef9c0.png)

Steps to Reproduce:

1. Click the Gear (1) in the bottom left
2. Click "Restart to update..."
2. Wait for the error to appear
On dismissing the error, VSCode restarts without any issues besides the failure to update.

Alternatively:

1. Open VSCode
2. Close VSCode
2. Wait for the error to appear
On dismissing the error, VSCode exits.

Does this issue occur when all extensions are disabled?: _I can't figure out how to launch the user version of Code Insiders from the run dialogue; `code-insiders --disable-extensions` doesn't work._

**Comment by iansan5653** [comment]
After restarting Windows, I was able to successfully update. I'd close this issue but I don't know if there's an underlying problem or not.

**Comment by joaomoreno** [comment]
Thanks, we already have a couple other issues following this problem.
