### ISSUE TITLE
Visual imporvements

### ISSUE THREAD

**Issue by lllopo** [Microsoft/vscode#56365]
I'm posting screens with the results of a custom CSS file, that I use to fix some visual annoyances in VS Code. It also fixes a few bugs, that I've already posted as separate bug reports. Here's the list of changes :
- improved vertical alignment of tabs items - icon, label and close button
- smaller tabs (this is a popular issue already reported) - tabs are unnecessary high, wasting vertical space for nothing.
- improved vertical alignment of breadcrumbs
- nicer breadcrumbs separator (chevron)
- breadcrumbs picker and menus use border instead of shadows for better readability (imo)
- fixed collapsing breadcrumbs separator on long items (already reported by me)
- fixed separator before first breadcrumbs when custom color defined in settings (already reported by me)
- breadcrumbs offset to gutter for better readability (imo)

Hopefully this can be useful to the devs for improving VS Code.

Before :
![withoutcss](https://user-images.githubusercontent.com/5485902/44095978-d1f97a48-9fe2-11e8-80db-7b7bbc8819ba.png)

After :
![withcss](https://user-images.githubusercontent.com/5485902/44095998-d8ddd462-9fe2-11e8-89f6-4254926df52a.png)

Here's the CSS :
```
.title.tabs .monaco-scrollable-element,
.tabs-container,
.tab.active,
.tab,
.monaco-workbench>.part.editor>.content .editor-group-container>.title .editor-actions .action-label,
.monaco-workbench>.part.editor>.content .editor-group-container>.title .editor-actions {
    height: 31px !important;
}

.tabs-container .tab .tab-border-top-container {
    height: 2px !important;
}

.tabs-container .tab .monaco-icon-label-description-container {
    display: flex;
}

.tabs-container .tab .monaco-icon-label-description-container .label-name {
    display: inline-block;
    line-height: 100%;
}

.monaco-menu-container,
.monaco-breadcrumbs-picker>div:last-child {
    box-shadow: none !important;
    border: 1px solid #d0d0d0 !important;
}

.monaco-breadcrumbs {
    background-color: #f9f9f9 !important;
    padding-left: 70px;
}

.monaco-breadcrumbs .label-name,
.monaco-breadcrumbs .hint-more {
    line-height: 25px;
    height: 25px;
}

.monaco-workbench>.part.editor>.content .editor-group-container>.title .tabs-breadcrumbs .breadcrumbs-control .monaco-icon-label:before {
    margin-top: 5px;
    padding-right: 3px;
    height: 15px;
}

.monaco-breadcrumbs .monaco-breadcrumb-item:before {
    background-image: url("data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2224%22%20height%3D%2224%22%20viewBox%3D%220%200%2024%2024%22%20fill%3D%22none%22%20stroke%3D%22%23000%22%20stroke-width%3D%222%22%20stroke-linecap%3D%22round%22%20stroke-linejoin%3D%22round%22%3E%0A%20%20%20%20%3Cpolyline%20points%3D%229%2018%2015%2012%209%206%22%2F%3E%0A%3C%2Fsvg%3E") !important;
    background-size: 65% !important;
    background-position: 50% !important;
    opacity: .5 !important;
    background-repeat: no-repeat;
    min-width: 16px;
}

.monaco-breadcrumbs .monaco-breadcrumb-item:first-of-type:before {
    display: none;
}

.monaco-workbench>.part.editor>.content .editor-group-container>.title .tabs-breadcrumbs .breadcrumbs-control .symbol-icon {
    padding-right: 3px;
    height: 25px;
    line-height: 25px;
    background-size: 15px;
    background-position: 0px 5px;
}

.monaco-breadcrumbs-picker {
    margin-left: -10px;
}

.monaco-breadcrumbs-picker>div:last-child {
    margin-top: 12px;
}

.monaco-breadcrumbs-picker>div:first-child {
    display: block;
    position: absolute;
    top: 7px;
    left: 0px;
    width: 10px !important;
    height: 10px;
    background: #FAFAFA;
    border-left: 1px solid #CAD5E0 !important;
    border-top: 1px solid #CAD5E0 !important;
    margin-left: auto !important;
    border-right: 0px none !important;
    border-bottom: 0px none !important;
    transform: rotate(45deg);
}
```

**Comment by nealot** [comment]
This looks so much better than the default.

**Comment by lllopo** [comment]
@nealot Yeah, I'm not saying it is all good. This is how I adjusted it to my liking. The adjustments like the menu borders, offset etc. are matter of personal taste, of course, and I'm not pretending to be the best possible. Many things are fixes, though. Most notably the adjusted vertical alignment of the tabs and breadcrumbs, which is really irritating in the original. So, whatever of the list is accepted by the devs - it is welcome.

**Comment by jrieken** [comment]
@lllopo Looks good about a PR or individual PRs?

**Comment by lllopo** [comment]
@jrieken Yup, but I'm not much into the VS Code CSS and I'm afraid to not break something else. I mean - this is the end result I'm targeting, but I'm not 100% sure the approach I'm using to achieve it is the right one.

**Comment by jrieken** [comment]
We could start with border/outline for the picker. That should be relatively easy, look at `breadcrumbscontrol.css`.

**Comment by tristan957** [comment]
Along these same lines. The breadcrumbs styling becomes different if it is displaying the `...` instead of a function definition for example.

![image](https://user-images.githubusercontent.com/11936772/44217254-a7cade00-a13c-11e8-9d1e-657d27ecfef8.png)

vs

![image](https://user-images.githubusercontent.com/11936772/44217291-baddae00-a13c-11e8-995e-326f734ee702.png)

The arrow gets much closer to the previous crumb in the second picture, and seems be elevated just a bit

**Comment by jrieken** [comment]
We have made many improvements and polished breadcrumbs. If there is more that you are missing then please file individual issues. Thanks
