### ISSUE TITLE
Possible to bring up multiple save dialogs on same file

### ISSUE THREAD

**Issue by psychopiz** [Microsoft/vscode#5636]
- VSCode Version: 1.0.0
- OS Version: windows 10

Steps to Reproduce:

1.Create a new file, and type something
2.Press down Ctrl+S more than one times as quick as you can
3.VS Code will open duplicate save dialog

Thank you ArianeLu!

**Comment by egamma** [comment]
Hello, the development team doesn't speak Chinese, sorry. Can you please find someone that helps you translate the issue to English.

**Comment by ArianeLu** [comment]
@egamma 

1. Create a new file, and type something
2. Press down Ctrl+S more than one times as quick as you can
3. VS Code will open duplicate save dialog

**Comment by bpasero** [comment]
Good catch!
