### ISSUE TITLE
Problems tab not up-to-date

### ISSUE THREAD

**Issue by sguillia** [Microsoft/vscode#56367]
Please take a look at the following screenshot:

![bug-vscode-2](https://user-images.githubusercontent.com/15984272/44096782-6050d090-9fdc-11e8-814c-fc20421e9b43.PNG)

Could you confirm there is something wrong?

The following looks wrong to me:
- There should be 4 problems, but only 2 warnings are shown
- The second _unused variable_ is "indented" but it shouldn't be.

This happened after I ran a build task with a problem matcher. My task ran, but the problems were not put into the "Problems" tab.

Reloading the window solves the problem.

This bug is hard to reproduce since it is quite a bit random...

I have the feeling that the problem matcher conflicts with the IntelliSense thing that looks for unused variables, but this is only a feeling. In that case, the bug would not reproduce without C/C++ extensions.

- Is this a bug?
- What should I do if it happens again in order to provide more information?

**Comment by DanTup** [comment]
Maybe same as #56371 (yours was opened first, but that one has more comments about it affecting many languages)?

**Comment by dbaeumer** [comment]
This indeed looks like a dup of #56371 which (due to the scrolling problem) might be even not a problem of the language services itself.

**Comment by sguillia** [comment]
I have this problem again, the Problems tab is not up-to-date

![bug-vscode-problems](https://user-images.githubusercontent.com/15984272/44654306-82b65500-a9f1-11e8-89a4-7d876326d11e.PNG)

`0 errors, 2 warnings` conflicts with `1 error, 3 warnings`

The thing is, I am running VS Code insiders with a more recent version than the one containing the fix for #56371.

- Either I am confused about versions
- Either the fix didn't fix everything
- Either this is not a duplicate but another bug

VS Code version: Code - Insiders 1.27.0-insider (3f8088b5c5f1d44b5e1af4a8e67448abbe66470e, 2018-08-27T07:36:47.732Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (9.24GB free)|
|Process Argv|C:\Users\GUILLIAMS.S\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|50%|

</details>

**Comment by dbaeumer** [comment]
@sandy081 please see above comment. I saw an issue from @chrisdias as well complaining about problems not showing.

**Comment by sandy081** [comment]
This is a new issue - https://github.com/Microsoft/vscode/issues/57292. Not sure what introduced it as I have not made any changes recently. Will fix it today.
