### ISSUE TITLE
VSCode hangs when opening python file

### ISSUE THREAD

**Issue by AlanRosenthal** [Microsoft/vscode#56377]
Issue Type: <b>Bug</b>

1) open vscode
2) open python file, eg tasks.py
3) vscode becomes unresponsive
4) try disabling python extension and observe same behavior

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:25:59.521Z)
OS version: Linux x64 4.15.0-30-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 3101)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 1|
|Memory (System)|15.37GB (9.79GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
arm|dan|0.2.0
gitlens|eam|8.5.4
plantuml|jeb|2.8.5
rainbow-csv|mec|0.4.2
atom-keybindings|ms-|3.0.4
cpptools|ms-|0.17.7
vscode-docker|Pet|0.1.0
gitconfig|sid|1.0.1
code-spell-checker|str|1.6.10
alphabetical-sorter|ue|2.0.1

</details>

**Comment by tekrat** [comment]
Same issue is happening with other plugins.  I'm having the issue with the PowerShell plugin. I have found that:

* Exit the application  (Task Manager on Windows)
* Open with a new work space so you are not point to old file that locked up the applications
* Disable your plugin
* Reload the application
* Reopen the file, change 1 character and save.
* Ensable your plugin
* Reload the application

Was there a new plug-in caching mechanic in the new version?

**Comment by AlanRosenthal** [comment]
@sandy081: looks like pasting this line causes a crash
`    cmd = "git-clang-format --style=\"{{BasedOnStyle: Google, ColumnLimit: 100, IndentWidth: 2, " \
          "AlignConsecutiveAssignments: true}}\" {COMMIT_SHA} -- ./**/*.proto > {OUTPUT}".format(`

**Comment by noahp** [comment]
It hangs for me (same version of vscode) around this position in that string (if entered manually):
`cmd = "git-clang-format --style=\"{{BasedOnStyle: Google, ColumnLimit: 100, In`
I'm wondering if the `{{` escape is not parsed, so the contents left of the `:` characters are being processed as format specifiers?
https://docs.python.org/3/library/string.html#formatstrings

**Comment by aeschli** [comment]
Sample from #56338:
```py
record = {
    "headers": {k: str(v) for k, v in self.request.META.items() if k.startswith('HTTP_')}
}
```

**Comment by aeschli** [comment]
File https://github.com/MagicStack/MagicPython/issues/150 against MagicPython.
