### ISSUE TITLE
Markdown Preview Flashes

### ISSUE THREAD

**Issue by RyanTaite** [Microsoft/vscode#56378]
Issue Type: <b>Bug</b>

When editing a Markdown file with the Preview open on the side, the Preview section flashes whenever it updates rather than having a smooth update.

It seems to happen more when editing lines in-between other lines, rather than lines at the bottom of the file.

My Markdown file has just under 1000 lines.

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.88GB (24.30GB free)|
|Process Argv|C:\Users\rtaite\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
spellright|ban|2.5.30
vscode-markdownlint|Dav|0.19.0
jshint|dba|0.10.19
vscode-eslint|dba|1.4.12
code-runner|for|0.9.4
beautify|Hoo|1.3.2
csharpextensions|jch|1.3.0
csharpfixformat|Leo|0.0.73
markdown-shortcuts|mdi|0.8.1
mssql|ms-|1.4.0
csharp|ms-|1.15.2

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Please share the contents of your markdown file

**Comment by RyanTaite** [comment]
@mjbvz Here you go, slightly edited:

[ryanTaiteMarkdownFileTextFormat.txt](https://github.com/Microsoft/vscode/files/2302904/ryanTaiteMarkdownFileTextFormat.txt)

**Comment by mjbvz** [comment]
We've made some fixed around this area recently and I can no longer reproduce this problem. Let me know if you still see this in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)
