### ISSUE TITLE
Nested user snippets are no longer triggered by prefixes

### ISSUE THREAD

**Issue by KeeganJ** [Microsoft/vscode#56373]
Issue Type: **Bug Report**

Nested user snippets are no longer triggered by prefixes. This is functionality that I used to use to scaffold out tests in mocha, but I noticed after updating that prefixes would no longer trigger snippets when used while still in the context of another snippet.

- VSCode Version: 1.26.0 (and Insiders 1.27.0)
- OS Version: macOS 10.13.6

Steps to Reproduce:

1. Add a user snippet that defines at least one field for user input (in the below example I added one for javascript)
2. Trigger the snippet using the defined prefix in a source file of the defined language
3. Attempt to trigger the snippet again using the same prefix. (Though in testing I found I couldn't trigger any other snippets through their prefixes).

![7wmdt1u9ov](https://user-images.githubusercontent.com/1531215/44098651-61d448b0-9fa6-11e8-9efd-8f8e24aea29a.gif)

Does this issue occur when all extensions are disabled?: **Yes** (Also tested in Insiders build running no extensions)

**Comment by jrieken** [comment]
We did that on purpose because many people disliked that behaviour. You can now control that with the `"editor.suggest.snippetsPreventQuickSuggestions": false` setting.

**Comment by KeeganJ** [comment]
@jrieken Thanks!
