### ISSUE TITLE
spawn .../corerun ENOENT when trying to debug C++ on Mac

### ISSUE THREAD

**Issue by DanB91** [Microsoft/vscode#5637]
- VSCode Version: 1.0.0 (1.0.0)
- OS Version: Mac OS X 10.11.4

Hi, I am trying to debug my program with the following configuration:

```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "C++ Launch (GDB)",
			"type": "cppdbg",
			"request": "launch",
			"launchOptionType": "Local",
			"miDebuggerPath": "/usr/local/bin/gdb",
			"targetArchitecture": "x64",
			"program": "${workspaceRoot}/build/rg",
			"args": [],
			"stopAtEntry": false,
			"cwd": "${workspaceRoot}/build",
			"environment": []
		}
	]
}
```

When I try to run this configuration I get the error: `spawn <home>/.vscode/extensions/ms-vscode.cpptools-0.4.2/debugAdapters/corerun ENOENT. Stopping the debug adapter.`

Can't seem to find this issue anywhere else. gdb is signed and works on the command line.

Steps to Reproduce:

1. Try to launch debug configuration

Any help would be greatly appreciated.  Thanks!

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/vscppsamples#28

**Comment by sushovannits** [comment]
Hi 
I am trying to run and debug a simple C++ program but I keep getting this same error.
![image](https://cloud.githubusercontent.com/assets/5388540/15498003/0bc761ca-21bb-11e6-978d-55b5b5e4aa93.png)

**Comment by dbaeumer** [comment]
@sushovannits please report the issue at: https://github.com/Microsoft/vscppsamples/issues/28
