### ISSUE TITLE
Auto-complete of @ in extension sidebar stops working when text is deleted from search box

### ISSUE THREAD

**Issue by waldyrious** [Microsoft/vscode#56375]
Having initially reported #46333, I was eager to test the functionality that was implemented in #53915. I came across the following issue that doesn't sound like desirable/intentional behavior.

- VSCode Version: 1.26.0
- OS Version: Ubuntu 16.04.5 LTS

Steps to Reproduce:

1. Open the extension sidebar.
2. Type @ in the search box. An auto-complete menu appears with several possible options (`@builtin`, `@disabled`, etc.)
3. Type or pick one of the options, e.g. `@builtin`. A list of extensions is shown below.
4. Select all the text in the box except the `@`, and delete it

Expected behavior: the initial list of available keywords should appear again.

Actual behavior: The autocomplete list is not shown, and the extension sidebar shows simply "No extensions found."

**Comment by JacksonKearl** [comment]
Does triggering suggestions cause the list to appear again? This is `ctrl+space` be default.

**Comment by JacksonKearl** [comment]
Testing on 1.26 just now I'm seeing that simply deleting to the `@` does not trigger suggestions, but pressing `ctrl+space` from there does show the suggestions again. This is as designed, it works the same in the editor: if you type `this.` suggestions will appear, but if you delete until the period, the wont appear. 

As a side note, you actually don't need to type the `@` at all; you can use `ctrl+space` from the empty search box or any word boundary within the query and it will show suggestions. The `@` is simply what we call a `trigger character`, which means the act of typing it forces suggestions to show, but the act of deleting something up until it does nothing.

**Comment by waldyrious** [comment]
> Does triggering suggestions cause the list to appear again? This is `ctrl+space` be default.

Yes, it does.
