### ISSUE TITLE
Unable to launch on RHEL7

### ISSUE THREAD

**Issue by gdelhomme** [microsoft/vscode#56376]
- VSCode Version: 1.26.0
- OS Version: RHEL7

Steps to Reproduce:

1. At start

Does this issue occur when all extensions are disabled?: Yes

This problem occurs when launching the last official 1.26 on RHEL7.
`[140720:0814/172715.230161:WARNING:browser_main_loop.cc(275)] <unknown>: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-5pHxz4cUAk: Connection refused [140720:0814/172718.546298:FATAL:nss_util.cc(632)] NSS_VersionCheck("3.26") failed. NSS >= 3.26 is required. Please upgrade to the latest NSS, and if you still get this error, contact your distribution maintainer.`
Any workaround ?

**Comment by bpasero** [comment]
@gdelhomme did it work before with version `1.25`?

**Comment by gdelhomme** [comment]
@bpasero Yes, perfectly.

**Comment by bpasero** [comment]
@gdelhomme does this version work for you? https://az764295.vo.msecnd.net/exploration/e6caa88a0261e72c41c76ab2ff454b8763a19f73/code-exploration-1534224413.tar.gz

**Comment by bpasero** [comment]
@gdelhomme can you update the required libraries and try again?

**Comment by gdelhomme** [comment]
@bpasero It doesn't update automatically as the last version I can get is:
`Name        : nss`
`Arch        : x86_64`
`Version     : 3.19.1`
`Release     : 18.el7`
`Size        : 2.5 M`
`Repo        : installed`
`From repo   : anaconda`
`Summary     : Network Security Services`
`URL         : http://www.mozilla.org/projects/security/pki/nss/`
`License     : MPLv2.0`
`Description : Network Security Services (NSS) is a set of libraries designed to`
`            : support cross-platform development of security-enabled client and`
`            : server applications. Applications built with NSS can support SSL v2`
`            : and v3, TLS, PKCS #5, PKCS #7, PKCS #11, PKCS #12, S/MIME, X.509`
`            : v3 certificates, and other security standards.`
Will it be necessary for all RHEL7 installations to manually upgrade NSS ?

**Comment by bpasero** [comment]
@Tyriar any clues?

**Comment by gdelhomme** [comment]
@bpasero @Tyriar Waiting for any new advises, I can only use the 1.25.1. I hope it is not an issue generalized to all RHEL7 installations.

**Comment by chrmarti** [comment]
Electron 2 requires a newer libnss3 (>= 3.26). What's surprising is that Electron 3 (that's experimental, right?) requires only libnss3 >= 3.22. I wonder if that was deliberate and if maybe Electron could again lower the required version.

We updated the dependencies for the .deb package here: https://github.com/Microsoft/vscode/issues/55008

**Comment by chrmarti** [comment]
(If they can't lower it we should update the rpm dependencies: https://github.com/Microsoft/vscode/blob/master/resources/linux/rpm/dependencies.json)

**Comment by bpasero** [comment]
Sounds good.

**Comment by bpasero** [comment]
@chrmarti I am puzzled now, isn't this issue the same as https://github.com/Microsoft/vscode/issues/55008 that you already fixed?

**Comment by chrmarti** [comment]
@bpasero That's for the .deb package. Given that there is no recent libnss3 package for RHEL7, I was wondering if depending on a particular version is really needed (given that Electron 3 depends on a lower version). Could you check with them?

**Comment by bpasero** [comment]
@chrmarti it looks like Electron is simply using `libnss3-dev` instead of `libnss3` (see https://github.com/electron/electron/commit/e0a117414b9ff6f999a73a07a2ebac0c2be1ce8e). Can we do the same?

**Comment by chrmarti** [comment]
`-dev` only adds header files. I wonder if their build machine simply uses a more recent version that is then backed in as a requirement, but things would still compile and run with the older libnss3.

**Comment by chrmarti** [comment]
The dependencies are explicit. The RPM build references 3.22, the DEB build has 3.26, if I read these correctly. The comments say they require more recent versions to include security fixes, not because of new API.
- .deb: https://chromium.googlesource.com/chromium/src/+/master/chrome/installer/linux/debian/additional_deps
- .rpm: https://chromium.googlesource.com/chromium/src/+/master/chrome/installer/linux/rpm/additional_deps

@gdelhomme Which versions of Chromium and Chrome can you run on your system?

**Comment by Tyriar** [comment]
I think we need to do something like this https://cs.chromium.org/chromium/src/chrome/installer/linux/rpm/additional_deps?l=23&rcl=21869868a07a3c4a60ee6e31580408d876484f47 to fix this

**Comment by bpasero** [comment]
@Tyriar where would we add that?

**Comment by chrmarti** [comment]
https://github.com/Microsoft/vscode/issues/56376#issuecomment-413448431 mentions 1.19.1 as the latest available version.

**Comment by chrmarti** [comment]
An old Fedora 24 install had an older `nss` installed that needed updating before code would run. We should add that dependency.

**Comment by jdmairs** [comment]
I just ran into this problem with v1.26.1
Its not clear, sorry, to me was this fixed in a future version or what the work around is.

Thanks,

John

**Comment by jdmairs** [comment]
I just tested 1.27.2, 1.32.3, and 1.33 and they all still fail to start.  Shouldn't this be clearly documented on system requirements for Linux?

**Comment by Tyriar** [comment]
Speculative fix in this branch https://github.com/Microsoft/vscode/tree/tyriar/56376_nss_dep

Queued a build, will post a test build for verification when it finishes.

**Comment by Tyriar** [comment]
Ok the build is done, can some people please test these builds to see if they fix the issue?

- 64 bit: https://az764295.vo.msecnd.net/insider/0714d8659df9bd9b6c09f5635fc581b0b37242c6/code-insiders-1.34.0-1555084730.el7.x86_64.rpm
- 32 bit: https://az764295.vo.msecnd.net/insider/0714d8659df9bd9b6c09f5635fc581b0b37242c6/code-insiders-1.34.0-1555084522.el7.i386.rpm

**Comment by jdmairs** [comment]
My centos7 at home does not have the same problem as RHEL7.  It will take about a week for me to test it on an actual RHEL7.

Thanks!

**Comment by Tyriar** [comment]
Still waiting on some verification using the build in https://github.com/Microsoft/vscode/issues/56376#issuecomment-482632519

**Comment by jdmairs** [comment]
> 
> 
> Still waiting on some verification using the build in [#56376 (comment)](https://github.com/Microsoft/vscode/issues/56376#issuecomment-482632519)

I'm downloading now...hope to get it installed soon.

**Comment by jdmairs** [comment]
I get the following:

Error: Package: code-insiders-1.34.xyzzy
    Requires libnss3.so (NSS_3.22)

**Comment by Tyriar** [comment]
@jdmairs oh ok, it can't download it if you're offline 🙁. Maybe the snap package would work better for you if you have issues with installing software (if you're able to get the snap tools installed)

**Comment by ay0407** [comment]
I still have the same issue with the new build:
rpm -U code-insiders-1.34.0-1555084730.el7.x86_64.rpm
error: Failed dependencies:
        libnss3.so(NSS_3.22)(64bit) is needed by code-insiders-1.34.0-1555084730.el7.x86_64

**Comment by ay0407** [comment]
> I still have the same issue with the new build:
> rpm -U code-insiders-1.34.0-1555084730.el7.x86_64.rpm
> error: Failed dependencies:
> libnss3.so(NSS_3.22)(64bit) is needed by code-insiders-1.34.0-1555084730.el7.x86_64

Okay, I was able to make it work after running:
sudo yum install nss
...
sudo rpm -i code-insiders-1.34.0-1555084730.el7.x86_64.rpm

and then launch code just fine

**Comment by Tyriar** [comment]
@ay0407 I think you need to install via yum in order for dependencies to install, installing with rpm just installed the package, like dpkg (the package installer) and apt (the package manager) with debs.

**Comment by ay0407** [comment]
I see, that makes sense. I will try next time. Thank you for the response.

**Comment by Uprzejmy** [comment]
Is this a duplicate: https://github.com/microsoft/vscode/issues/70363?

**Comment by amitchettri** [comment]
I have tried to install code-1.38.1-1568209352.el7.x86_64 and code-1.39.1-1570750844.el7.x86_64 but when i try to launch code i get below. is there any fix for this ?

]$ code .
/usr/share/code/bin/../code: /lib64/libnss3.so: version `NSS_3.22' not found (required by /usr/share/code/bin/../code)
/usr/share/code/bin/../code: /lib64/libdbus-1.so.3: no version information available (required by /usr/share/code/bin/../code)
