### ISSUE TITLE
Decrease delay for File Search

### ISSUE THREAD

**Issue by outcoldman** [Microsoft/vscode#5638]
Am I right that because of this https://github.com/Microsoft/vscode/blob/5b9ec15ce526decc5dd0488339e798f6bcb4ec46/src/vs/workbench/parts/search/browser/openAnythingHandler.ts#L43 files search never will be faster than 300ms? Why is this number so large? Why this delay actually exists?

**Comment by bpasero** [comment]
There are two use cases: Give the user a chance to finish his typing before starting the search. The other is to give the symbol search time to also participate. 

Once we tackle a faster search index that does not need to hit the disk all the time, I would think we can lift this delay.

**Comment by bpasero** [comment]
The delay is no longer being used once the file search cache is hot (which it is quickly). Closing.

**Comment by bpasero** [comment]
Verifier: run a quick open once for files and in the future verify that results are coming in fast and without noticable delay.
