### ISSUE TITLE
Window contents are clipped

### ISSUE THREAD

**Issue by arturogh** [Microsoft/vscode#56381]
Issue Type: <b>Bug</b>

On unlocking my machine both my WS Code window contents were clipped:

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/7030831/44104904-ebf61890-9fa4-11e8-94f5-e2461f080f2d.png">

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:20:44.170Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (4.93GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_32501501|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.12
tslint|eg2|1.0.34
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.6.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
path-autocomplete|ion|1.12.0
vscode-styled-components|jpo|0.0.21
better-line-select|kai|1.0.1
vscode-azureappservice|ms-|0.9.0
azure-account|ms-|0.4.3
vscode-jest|Ort|2.9.0
markdown-preview-enhanced|shd|0.3.5
ayu|tea|0.14.0

(2 theme extensions excluded)

</details>

**Comment by arturogh** [comment]
A resize of the window 'fixes' it.

**Comment by bpasero** [comment]
@arturogh is this reproducible everytime?

**Comment by arturogh** [comment]
Happened once. Hasn't happened again. Will report back if it does.

**Comment by bpasero** [comment]
Ok, will close until we have a reliable way of reproducing.
