### ISSUE TITLE
Unsaved content will be lost after replacing the filename with the “same” one

### ISSUE THREAD

**Issue by zamhown** [Microsoft/vscode#56384]
- VSCode Version: 1.27.0-insider
- OS Version: Windows 10.0.17713.1002

Steps to Reproduce:

1. Open a folder in the sidebar.
2. Create a file named "test.txt".
3. Modify the content of the document to "a", and save it.
4. Modify the content of the document to "b", but don't save it.
5. Modify the filename to "Test.txt". Oooops! the unsaved content is lost.
6. There is also a different way to reproduce:  modify the filename to a different one, and then change it back to "test.txt". The unsaved content will be lost too.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jdthoen** [comment]
Was just about to submit the same thing.
