### ISSUE TITLE
Extension host terminated unexpectedly after 1.26.0 update

### ISSUE THREAD

**Issue by natenorberg** [Microsoft/vscode#56387]
Issue Type: <b>Bug</b>

When I open VS Code I get a toast that says "Extension host terminated unexpectedly."

Usually this happens on startup, but occasionally extensions remain functional until I open, close, switch, or save a tab.

This never occurred before I updated to v.1.26.0 this morning. I saw a few similar issues, but they seem to end up being related to extensions I don't use such as ruby or go.

Dev tools output
```
 INFO no standard startup: not a new window
console.ts:136 [Extension Host]% {0: "extensions/defaults.json", 1: "{↵  "accents": {↵    "Acid Lime": "#C6FF00",↵    "…",↵    "Palenight High Contrast": "vs-dark"↵  }↵}"}
extensionService.ts:374 Extension host terminated unexpectedly. Code:  null  Signal:  SIGPIPE
w._onExtensionHostCrashed @ extensionService.ts:374
(anonymous) @ extensionService.ts:369
e.fire @ event.ts:140
t._onExtHostProcessExit @ extensionHost.ts:430
(anonymous) @ extensionHost.ts:215
emitTwo @ events.js:126
emit @ events.js:214
__dirname.ChildProcess._handle.onexit @ internal/child_process.js:198
notificationsAlerts.ts:41 Extension host terminated unexpectedly.
t.onDidNotificationChange @ notificationsAlerts.ts:41
(anonymous) @ notificationsAlerts.ts:27
e.fire @ event.ts:140
t.notify @ notifications.ts:113
t.notify @ notificationService.ts:56
t.prompt @ notificationService.ts:88
w._onExtensionHostCrashed @ extensionService.ts:382
(anonymous) @ extensionService.ts:369
e.fire @ event.ts:140
t._onExtHostProcessExit @ extensionHost.ts:430
(anonymous) @ extensionHost.ts:215
emitTwo @ events.js:126
emit @ events.js:214
__dirname.ChildProcess._handle.onexit @ internal/child_process.js:198
index.js:41 [uncaught exception]: Error: write EPIPE
onError @ index.js:41
(anonymous) @ index.js:160
emitOne @ events.js:116
emit @ events.js:211
window.onerror @ /Applications/Visual Studio Code.app/Contents/Resources/electron.asar/renderer/init.js:142
i.globals.onerror @ errorTelemetry.ts:79
index.js:44 Error: write EPIPE
    at _errnoException (util.js:1024)
    at WriteWrap.afterWrite [as oncomplete] (net.js:867)
onError @ index.js:44
(anonymous) @ index.js:160
emitOne @ events.js:116
emit @ events.js:211
window.onerror @ /Applications/Visual Studio Code.app/Contents/Resources/electron.asar/renderer/init.js:142
i.globals.onerror @ errorTelemetry.ts:79
events.js:183 Uncaught Error: write EPIPE
    at _errnoException (util.js:1024)
    at WriteWrap.afterWrite [as oncomplete] (net.js:867)
```

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:20:44.170Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (2.27GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme-italicize|Ser|0.0.14
better-comments|aar|1.2.6
Bookmarks|ale|9.0.3
react-pure-to-class-vscode|ang|1.1.6
snapshot-tools|asv|0.0.7
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.12
githistory|don|0.4.2
gitlens|eam|8.5.4
prettier-vscode|esb|1.6.1
vscode-flow-ide|gca|1.2.0
vscode-styled-components|jpo|0.0.21
vscode-todo-parser|min|1.9.1
atom-keybindings|ms-|3.0.4
vsliveshare|ms-|0.3.535
debugger-for-chrome|msj|4.8.2
color-highlight|nau|2.3.0
material-icon-theme|PKi|3.5.2
polacode|pnp|0.2.2
code-spell-checker|str|1.6.10
vim|vsc|0.16.0
quokka-vscode|Wal|1.0.136

(24 theme extensions excluded)

</details>

**Comment by ZRogerson** [comment]
I'm having the same issue. It seems to be killing prettier and possible other extensions.

**Comment by natenorberg** [comment]
The biggest problem for me was the vim extension. When the extension host went down it would leave me in command mode, but none of the commands would work.

Anyway, I installed the previous release and it auto-updated to 1.26.0 when i accidentally restarted Code. It seems to be working ok again.

**Comment by eahydra** [comment]
met the same

**Comment by sanjcho** [comment]
met the same, in my case disabling vscode-flow-ide extention made all working ok.

**Comment by lebalz** [comment]
same issue here, the ruby-extension is the killer in my case...

**Comment by Jorundur** [comment]
@sanjcho Same for me, disabling `vscode-flow-ide` seems to fix things. I uninstalled it and installed `Flow Language Support` instead.

**Comment by mickeygo** [comment]
In my case the Go extension make the problem, but the Go extension author is microsoft.

**Comment by dewey** [comment]
@mickeygo Yea they are aware of the issue: https://github.com/Microsoft/vscode-go/issues/1845

**Comment by alexandrudima** [comment]
Sorry about that! It looks like there are a few hiccups possibly caused by VSCode's Electron update. A short list of apparently impacted extensions:

* `vscode-ruby` - https://github.com/Microsoft/vscode/issues/56301#issuecomment-412902267
* `vscode-go` - https://github.com/Microsoft/vscode-go/issues/1845
* `vscode-flow-ide`

If you find other impacted extensions, please try to also reach out to them directly. I am not entirely sure at this point what is the root cause.

**Comment by natenorberg** [comment]
Thank you for looking into it. This seems like a difficult one to dig into

**Comment by bpasero** [comment]
Adding "Candidate" label just so that this shows up in our discussion round.

**Comment by ramya-rao-a** [comment]
@alexandrudima My findings were similar to what @wingrunr21 is saying above.

@wingrunr21 In `vscode-go` we don't need users to provide/configure the absolute paths. The extension figures out the path itself, makes sure the file exists and returns the absolute path of the file. If the file is not found, then the command is returned. That's why my mitigation was by checking for the absolute path.

The above mitigation works for https://github.com/Microsoft/vscode-go/issues/1845. I am still looking into  https://github.com/electron/electron/issues/13679

**Comment by wingrunr21** [comment]
@ramya-rao-a ah, that makes sense. That auto detection is a problem I'm still trying to solve as a lot of Ruby environments are configured via shell functions and can vary by directory. That's why I proposed checking via `command -v`

**Comment by trevorwhealy** [comment]
Updated yesterday. None of eslint, prettier, nor gitlens work.
Downloaded the version from June to get work done today. 
Works great. https://code.visualstudio.com/updates/v1_25

**Comment by mickeygo** [comment]
Now I change the plugin vscode-go settings in my Mac as below, it works fine.

![image](https://user-images.githubusercontent.com/5130371/44193391-394e4600-a165-11e8-8e0f-4628bb843ab8.png)

**Comment by alexandrudima** [comment]
A minimal repro:

```
const child = cp.spawn(`node1`);
child.stdin.write('hi standard in!');
```

**Comment by nirfse** [comment]
I have the same issue with the Python extension after 1.26.0 update:

```log
t.log @ /opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:272
/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] Failed to get interpreter information for '/home/user/.local/share/virtualenvs/webapp-Ab5ma23j/bin/python' SyntaxError: Unexpected token / in JSON at 
position 0
    at JSON.parse (<anonymous>)
    at PythonExecutionService.<anonymous> (/home/user/.vscode/extensions/ms-python.python-2018.7.1/out/client/common/process/pythonProcess.js:42:35)
    at Generator.next (<anonymous>)
    at fulfilled (/home/user/.vscode/extensions/ms-python.python-2018.7.1/out/client/common/process/pythonProcess.js:12:58)
    at <anonymous>

t.log @ /opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:272
/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] Summary:
/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host]% 19 parseable documents found
/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host]% 324 CSS class definitions found
/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host]% 102 unique CSS class definitions found
/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host]% 1 failed attempts to parse. List of the documents:
/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] /home/user/Projects/latest/srv_webapp/app/static/css/styles.css
/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] Failed to get interpreter information for '/home/user/.local/share/virtualenvs/webapp-Ab5ma23j/bin/python' SyntaxError: Unexpected token / in JSON at position 0
    at JSON.parse (<anonymous>)
    at PythonExecutionService.<anonymous> (/home/user/.vscode/extensions/ms-python.python-2018.7.1/out/client/common/process/pythonProcess.js:42:35)
    at Generator.next (<anonymous>)
    at fulfilled (/home/user/.vscode/extensions/ms-python.python-2018.7.1/out/client/common/process/pythonProcess.js:12:58)
    at <anonymous>

t.log @ /opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:272
/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] Python Extension: display.refresh TypeError: Cannot read property 'version' of undefined
    at InterpreterService.<anonymous> (/home/user/.vscode/extensions/ms-python.python-2018.7.1/out/client/interpreter/interpreterService.js:135:44)
    at Generator.next (<anonymous>)
    at fulfilled (/home/user/.vscode/extensions/ms-python.python-2018.7.1/out/client/interpreter/interpreterService.js:13:58)
    at <anonymous>

t.log @ /opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:272
/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:3213 Extension host terminated unexpectedly. Code:  null  Signal:  SIGPIPE

w._onExtensionHostCrashed @ /opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:3213
/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:2386 Extension host terminated unexpectedly.

t.onDidNotificationChange @ /opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:2386
```

**Visual Studio Code (binary, stable)**
Version: 1.26.0-3
OS: Linux
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Arch: x64

**Comment by alexandrudima** [comment]
It looks like the root cause is https://github.com/electron/electron/issues/13254. We have identified a simple workaround to avoid the crash.

Please verify this issue on all 3 platforms: windows, linux and mac.

To verify, you can use the following extension:

* `package.json`:
```js
{
    "name": "56387",
    "version": "0.0.1",
    "publisher": "alex",
    "engines": {
        "vscode": "^1.25.0"
    },
    "activationEvents": [
        "onCommand:extension.sayHello"
    ],
    "main": "./extension",
    "contributes": {
        "commands": [
            {
                "command": "extension.sayHello",
                "title": "Hello World"
            }
        ]
    }
}
```

* `extension.js`:
```js
const vscode = require('vscode');
const cp = require('child_process');

exports.activate = function(context) {
    let disposable = vscode.commands.registerCommand('extension.sayHello', function () {
        console.log(`in repro1`);
        const child = cp.spawn(`/node1`);
        child.stdin.write('hi standard in!');
    });
    context.subscriptions.push(disposable);
}
```

**Comment by nirfse** [comment]
@alexandrudima After 20 minutes of testing, I can confirm that provided patch so far fixes the issue. Tested on Arch Linux OS with the official VSCode binary. Thanks a lot!

**Comment by Kevin8428** [comment]
@alexandrudima could you clarify how to apply this patch?

**Comment by mickeygo** [comment]
The vscode-go update on my Mac today, now it works fine.

**Comment by Kevin8428** [comment]
@mickeygo @alexandrudima can anyone help me, I can't figure out how to implement this update. Thanks!

**Comment by mickeygo** [comment]
@Kevin8428 I mean that now the extension vscode-go update to 0.6.88 version and it will work fine on Mac, does not need to change the config file.  I don't know other extensions. Thanks !

**Comment by Kevin8428** [comment]
ahh same! thanks!
