### ISSUE TITLE
Better empty state for Debug sidebar

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#56391]
We currently provide empty state text for all of our sidebar panels except for Debug. My suggestion is to hide the content and use a similar message:

|Current|Suggestion|
|---|---|
|<img src="https://user-images.githubusercontent.com/35271042/44109210-4ec14c86-9fb1-11e8-95ff-071eedd94f73.png">| <img src="https://user-images.githubusercontent.com/35271042/44110456-9505980c-9fb4-11e8-970e-aecf1ded4999.png"> |

Here are the empty states for our sidebars:

**Explorer**
<img width="50%" src="https://user-images.githubusercontent.com/35271042/44110267-20c8231a-9fb4-11e8-92c1-f5a71df4ca19.png">

**Search**
<img width="50%" src="https://user-images.githubusercontent.com/35271042/44108831-5603c4fc-9fb0-11e8-907d-fbac7198cbaa.png">

**Git**
<img width="50%" src="https://user-images.githubusercontent.com/35271042/44108886-7f2c01f0-9fb0-11e8-80fc-e5070d205fef.png">

**Comment by misolori** [comment]
@isidorn in the scenario where they have watch expressions or breakpoints then I wouldn't expect to see this. This should only appear when there is nothing set.

I'm mostly interested in making it explicitly clear what state the view is in, it's weird to have those categories empty when we do show text in other views. 

I'd also be interested in seeing some message that is dismissible as well.

**Comment by isidorn** [comment]
@misolori but what if I am in an empty state and I want to add a watch expression? What do I do then? Also holds for function breakpoint.

**Comment by misolori** [comment]
@isidorn fair point. Would it be overkill if we had empty text for each section? Having a section empty still feels odd.

**Comment by isidorn** [comment]
@misolori empty text for each section sounds like to much noise to me.
I would prefer some easily dismisable overlay with some text and two buttons, one is "start simple debug", the other would be "got it". Just an idea on top of my head

**Comment by bpasero** [comment]
@misolori is this for when no folder is opened or in general when no debug configuration exists?

**Comment by isidorn** [comment]
Just for the record when no folder is opened we still support debugging, same as when no debug configuration exists.

**Comment by bpasero** [comment]
@isidorn yeah and in that case a blue button "Start Debug" could be an invitation to start debugging even if a user does not expect it works.

**Comment by isidorn** [comment]
@bpasero what a lovely invitation that would be
I am open for UX sketches and experimenting with this -> on deck

**Comment by misolori** [comment]
Something like this:
<img width="50%" src="https://user-images.githubusercontent.com/35271042/44483243-6b492780-a5ff-11e8-91cd-532625248c0b.png">

Or this:
<img width="50%" src="https://user-images.githubusercontent.com/35271042/44483363-ba8f5800-a5ff-11e8-971a-f7278f11801f.png">

**Comment by bpasero** [comment]
Yes 👍

**Comment by isidorn** [comment]
Defineetly looks bad inside the variables view.
Yeah I would say the proper thing would be to show it above the split view as @bpasero suggests.
That way we cover the corner cases (users can still add watch expressions while not debugging)

fyi @weinand

**Comment by bpasero** [comment]
The reason I like the blue button is that it invites the user to do something. If we want to get new users to debug something, I think a button could work well and would be  easier to use compared to the debug configuration dropdown.

**Comment by weinand** [comment]
- In many cases the blue button will not be able to do what it says. Providing an "Open Folder" button in the explorer is simple, but a "Start Debugging" button only works if the debug extension supports that. And if it doesn't "Start Debugging" just opens launch.json.
- having two UIs for the same functionality in close proximity is confusing:
  ![2018-08-23_11-31-06](https://user-images.githubusercontent.com/1898161/44517488-24733480-a6c8-11e8-820f-66ae59ab8877.png)
  the green button is stable and always and the blue button disappears at times...

**Comment by bpasero** [comment]
@weinand yeah good point, we can start with a message and show it as long as the user did not configure any launch configuration (and probably also as long as the user does not have breakpoints or watch expressions that could indicate the user is familar with debugging)

**Comment by isidorn** [comment]
Some good points rasied by @weinand 
I like the idea of changing the message based on the context - if the current file can be debugged we show message A, if the launch.json needs to be configured we show message B and so on..

**Comment by misolori** [comment]
From @chrisdias in https://github.com/Microsoft/vscode/issues/71664#issue-428867656:
> Most of the built in viewlets have some sort of information that tells you what to do with it. If no folder is open in the Workbench, the Explorer has a big button to open a folder. The Search viewlet has a Search input box. Extensions shows a list of extensions.
>
>The Debug viewlet is empty. We could have a simple prompt to help people get started by pressing F5 or configuring launch.json.
>![image](https://user-images.githubusercontent.com/1487073/55496575-45075380-55f4-11e9-8822-949be95ec0eb.png)

**Comment by isidorn** [comment]
I think we have improved the empty state for the debug viewlet, thus closing this.

**Comment by misolori** [comment]
Agreed, here's the latest version:

![image](https://user-images.githubusercontent.com/35271042/89211335-84420d80-d576-11ea-86b8-785d81917974.png)
