### ISSUE TITLE
`import(...)` shows up in type error messags

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#56396]
![image](https://user-images.githubusercontent.com/323878/44113665-ad904ddc-9fbd-11e8-9045-e6054f9f7e59.png)

Is this supposed to happen? I don't always see it. If you don't know what I'm talking about I can find a better reproable example...

**Comment by mjbvz** [comment]
Yes, if type import is referenced indirectly. It shouldn't show the full path though. What ts version was active in the workspace?

**Comment by roblourens** [comment]
3.0.1

**Comment by mjbvz** [comment]
Do you have repo steps in the vscode repo?
