### ISSUE TITLE
GIT Authentication failures with bitbucket

### ISSUE THREAD

**Issue by r3wt** [Microsoft/vscode#56399]
will you please fix this shit already? for the last 2 weeks git push always prompts to enter password with a little bitbucket login prompt, this always fails with "HttpRequestException", then you have to enter the password into the terminal. It also occassionally pops up the prompt when you open a project. what gives? it seems like this issue just keeps coming and going with vscode.

**Comment by joaomoreno** [comment]
What kind of authentication do you use with BitBucket? HTTPS, SSH?

**Comment by r3wt** [comment]
@joaomoreno https

heres the login prompt that pops up. it pops up on launch of a project, and also when trying to commit changes. no matter what, the login always fails for this form. but logging into through the terminal succeeds

![image](https://user-images.githubusercontent.com/4483325/44228602-5120cc80-a15b-11e8-8fb9-cc411f18e4da.png)

after this login fails(it always fails, whether password entered correctly or not), this appears in the terminal (in case of trying to push)

![image](https://user-images.githubusercontent.com/4483325/44228659-71508b80-a15b-11e8-91ff-fec19dce3c0b.png)

**Comment by joaomoreno** [comment]
Right, since the dialog isn't a part of VS Code and you get the same error in the command line as you do in VS Code... then the issue is very likely not related to VS Code at all.

Check here for more on this: https://www.google.ch/search?q=bitbucket+login+credentials+site:stackoverflow.com&sa=X&ved=2ahUKEwiB6rfHu_LcAhUhM5oKHWn4DPcQrQIoBDACegQICBAN&biw=1440&bih=803

**Comment by r3wt** [comment]
@joaomoreno screenshot is from terminal of vscode. vscode triggers these dialogs, i never asked for this horse shit.

**Comment by joaomoreno** [comment]
So, everything works perfectly fine in a terminal outside the VS Code?

Also, try to be nice, as I'm being nice to you too. That attitude will only get your issue to be closed without any answer.

**Comment by r3wt** [comment]
^ you get attitude because of your wrong assertion in an obvious effort to close this issue sereptiously without fixing the problem. this is aproblem with vscode authenticating. at some point, rather than having me enter the password in the terminal of vscode as normal, it began prompting me to enter it in this dialog. this blocks the terminal which annoying and disrupts my workflow. do you understand?

**Comment by r3wt** [comment]
and yes, it works just fine outside of vscode. no other terminal prompts me with a bitbucket login prompt when i type `git push`. why is this happening and how do i stop it?

**Comment by joaomoreno** [comment]
>  rather than having me enter the password in the terminal of vscode as normal

So, you usually use the terminal inside Code to do push, and that has stopped working. You are not using the `Git Pull` command, correct?

---

When you created this issue, you were prompted to provide this info, please do so:

- VSCode Version:
- OS Version:

**Comment by r3wt** [comment]
@joaomoreno no, there are two issues, they are both related! pay attention please. quit jumping to conclusion, there are clearly two seperate but extremely related issues (the login prompt fails for both and the prompt is an annoyance.)

1. WHEN LAUNCHING A PROJECT, vscode tries to gitfetch, which sometimes fails. when it fails, i get the small login prompt from the screenshot. This prompt always fails to submit, whether password is wrong or not. if you click the X on the prompt, the script aborts completely and you are not able to complete the action via terminal. So you must type text into the input and submit the form in order to continue with whatever you are doing.. Occassionally,  vscode just aborts, but sometimes, a small password input appears by the command pallete, asking me to enter my password. This prompt works normally.

2. WHEN TYPING `git push` FROM THE VSCODE TERMINAL, it prompts me with the SAME EXACT LOGIN PROMPT as shown in the screenshot. as mentioned, this always fails, no matter what you type. if you hit X the operation is aborted, so there is no possible way to proceed without typing atleast 1 character into the prompt and submitting it. After it fails with `HTTPRequestException` you may enter your password in the VSCODE TERMINAL and finish the `git push`.

so:
- annoying login prompt that always fails
- if you click x on the prompt, the operation is aborted.
- in order to finish, you must type atleast 1 character into the prompt and hit enter.
- after it fails, you may then enter your password in the vscode terminal to continue the operation.

VSCODE:
Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:43:53.668Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

OPERATION SYSTEM:
Windows 10 (latest version)

**Comment by joaomoreno** [comment]
> a small password input appears underneath the command pallete

Show me a screenshot of this.

> WHEN TYPING git push FROM THE VSCODE TERMINAL, it prompts me with the SAME EXACT LOGIN PROMPT as shown in the screenshot. as mentioned, this always fails, no matter what you type. 

This seems to me like you have issues with the Atlassian login credential manager. I suggest you uninstall/reinstall it or go and ask Atlassian why it is not working for you.

**Comment by reidca** [comment]
I have experienced the exact same issue as the OP.

This has been going on for a couple of weeks now and it's driving me crazy. I get asked for GIT credentials (for BitBucket) literally every time I do a PULL or PUSH. Often several times per operation it prompts for password either using the GUI or a dialog box at the top of VSCode's editor window. For some reason it does not accept the password the first time so prompts several times.

To try to fix this I have updated both "Git for Windows" and "Git Credential Manager for Windows" however for whatever reason the update does not seem to have applied.

If I run >>git credential-manager version
It always returns:

Git Credential Manager for Windows version 1.16.2

If I look in the installed program list however it shows
"Microsoft Git Credential Manager for Windows 1.17.1"

So my question is how do I make Git for Windows use the latest installed version of Git Credential Manager? I can't see anything in the user settings for which version VSCode uses.

Thank you

**Comment by joaomoreno** [comment]
> Git Credential Manager for Windows version 1.16.2

Well, that version must be installed somewhere in your system. Use a process inspection tool (like Process Hacker) to see where it lives, when the popup dialog appears.

**Comment by reidca** [comment]
That does not really answer my question which is how VSCode references the Git Credential Manager - if I know that I can most likely point it at the newly installed version. Finding out where the old version is will not allow me to change which version VSCode uses.

**Comment by joaomoreno** [comment]
Open a Command Prompt and type `git pull`. Does the popup open as well?

**Comment by reidca** [comment]
No, there is a prompt in the terminal session for the password. This is true in a Windows cmd prompt or in the Mingw64 terminal.

**Comment by joaomoreno** [comment]
And the prompt is in the Terminal, or in a window?

**Comment by reidca** [comment]
In the terminal

**Comment by joaomoreno** [comment]
Can you show me a screenshot of that terminal, when it asks for the credentials?
