### ISSUE TITLE
Move 'x' close button of Open Editor items to the right

### ISSUE THREAD

**Issue by ris58h** [Microsoft/vscode#56392]
Currently there is the close button on left side of the item which seems strange to me.
![open-editors-close-item](https://user-images.githubusercontent.com/511242/44110910-ac0ba9b0-a009-11e8-8b4d-f11c947ad4ec.png)
Shouldn't it be on the right side instead?

**Comment by isidorn** [comment]
Maybe. But I am not convinced to change it -> it would clash with the other decorations and people got used to it here.
I can leave this open as a feature request for now, but I have no immediate plan to tackle it
