### ISSUE TITLE
Breakpoints stay on their original line number (do not follow statements) when code is edited during a debug run

### ISSUE THREAD

**Issue by mawright** [Microsoft/vscode#56398]
I reported this bug to the vscode-python repo but was referred upstream to the core vscode repo. My example below is in Python but a Microsoft dev on vscode-python  confirmed it also affects the native Typescript debugger: https://github.com/Microsoft/vscode-python/issues/2389

- VSCode Version: 1.26.0, and 1.27.0-insider
- OS Version: Ubuntu 16.04

## Behavior
When lines are added/removed in the source code while a debug run is active (i.e., when paused at a breakpoint), all breakpoints stay at their line number and are not moved up or down as lines are added or removed. This means that when the debug run is relaunched, any breakpoints below added/removed lines will be on a different statement than when they were created.
This also means that the behavior of how breakpoints move is different between whether you are editing code while debugging or not. During normal operation, breakpoints move with their statements. During debugging, breakpoints stay in place.

## Expected Behavior
If code is edited during debugging, breakpoints follow their original statement (moving down 1 line for each line inserted above and up 1 line for each line deleted above) after the debug run is ended.

## Steps to Reproduce:

1. Non-debug behavior: Breakpoint moves with its original statement `c = 3`
![works_nondebug](https://user-images.githubusercontent.com/2333858/44108169-1f788182-9fe9-11e8-9eb1-edc3cc0b7b7a.gif)
2. Debug behavior: The statement `c = 3` begins at line 5, is moved down two lines, but the breakpoint stays at line 5, even after the debug run is completed.
![doesntwork_debug](https://user-images.githubusercontent.com/2333858/44108176-2892db8c-9fe9-11e8-8dbd-f1a8116a0ff2.gif)

Does this issue occur when all extensions are disabled?: N/A, since I can't run my Python test without the Python extension. However I tested it on the insiders build with the only installed extension being Python and it still happened.

**Comment by ichbineinNerd** [comment]
little addition: it happens on break points in any language, not only python.

**Comment by isidorn** [comment]
You can try out the fix in tomorrow's insiders and let me know if it is ok now. Thank you
