### ISSUE TITLE
Support more options for formatting text and inserting links to commands in Output Channel

### ISSUE THREAD

**Issue by seanmcbreen** [microsoft/vscode#564]
_From @ArtemGovorov on November 18, 2015 5:37_

More specifically:
- colors and other text formatting options.
- inserting links that can execute commands with parameters. I only need to open files, but the existing pattern matching doesn't work for me for 2 reasons: 
  - no relative paths support and long paths don't look good and waste space.
  - file links open files in the same pane where I had the Output pane opened. What I'd like to do is to open files in a text editor (if it's currently opened as well), so that the text editor and the Output pane could be used side by side.

So here is what I have in VS Code currently:

![screen shot 2015-11-18 at 2 59 37 pm](https://cloud.githubusercontent.com/assets/979966/11233066/6fca8066-8e05-11e5-9d44-79b8b22dc2a3.png)

Here is what I'd like to have:

<img width="423" alt="screen shot 2015-11-18 at 3 03 28 pm" src="https://cloud.githubusercontent.com/assets/979966/11233075/9b670d02-8e05-11e5-9e72-58d8d50e23e9.png">

_Copied from original issue: Microsoft/vscode-extensionbuilders#124_

**Comment by seanmcbreen** [comment]
Very fair request - we have been adding more to the debug console so this also makes sense @bpasero are you the right guy to think about this.

**Comment by seanmcbreen** [comment]
@ArtemGovorov how is Wallaby going I've not yet seen a publish Zurich will be online soon let us know if you need help.  For publishing @joaomoreno is your guy.

**Comment by seanmcbreen** [comment]
_From @ArtemGovorov on November 18, 2015 5:45_

@seanmcbreen Thanks, it's getting there, most of the functionality is working. I do need to do a few more things before publishing it though.

**Comment by seanmcbreen** [comment]
_From @SamVerschueren on November 18, 2015 7:54_

ANSI color codes (chalk) will be supported in the future. See https://github.com/Microsoft/vscode-extensionbuilders/issues/69.

**Comment by seanmcbreen** [comment]
_From @ArtemGovorov on November 18, 2015 8:12_

I'd rather use some higher level abstractions than using any specific colors. For example, it may be better to specify CSS classes (like `error` or `info`), that VS Code is using everywhere else, and to avoid specifying a fixed color that may not look good in a user theme.

I like how it's done in Atom:  you may use LESS variables (that may be changed by a theme) to define classes in your extension LESS file and you can later apply these classes in your HTML. But Atom allows to work with HTML/DOM while VS Code doesn't.

**Comment by seanmcbreen** [comment]
_From @SamVerschueren on November 18, 2015 8:16_

I would rather see that as a separate component then and keep the `OutputChannel` as is. I see the `OutputChannel` more like a cli that prints information to the screen.

**Comment by seanmcbreen** [comment]
_From @ArtemGovorov on November 18, 2015 8:38_

A separate  component with full HTML/JavaScript support [would be nice to have as well](https://github.com/Microsoft/vscode-extensionbuilders/issues/19), but for now all I need is theme friendly colours and enhanced links in the `OutputChannel`, I don't think it will make it less `cli`-ish.

**Comment by Tyriar** [comment]
Related: https://github.com/Microsoft/vscode/issues/571

**Comment by mattflix** [comment]
Chrome and Firefox do already handle this nicely with CSS styles (pass style objects to %c specifiers in the format string):

https://developer.chrome.com/devtools/docs/console#styling-console-output-with-css

It would great if the VS Code console could just support the same interface.  It's simple and easy to use.  Please don't reinvent the world.
