### ISSUE TITLE
complete documentation of all command line options

### ISSUE THREAD

**Issue by Mellbourn** [Microsoft/vscode#56401]
I have added command line completion for `code` to zsh (in [this PR](https://github.com/zsh-users/zsh/pull/24)) (i.e. so that `tab` after `code -` does nice things in zsh)
Now i'm updating the completions (in [this PR](https://github.com/zsh-users/zsh/pull/27))

When looking at the VS Code source code ([here](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/environment/node/argv.ts)) I can see that there are a number of undocumented command line paramerers, e.g.`--unity-launch`, `--file-uri`, `--export-default-configuration`, `--driver`, `--open-url`. I am unsure how to add these to the command line completion script, since I don't know what they do.

Could you document _all_ command line options somewhere?
Perhaps some of the undocumented parameters are experimental, but then it would be good to have that documented (so I could skip them in the script).

**Comment by bpasero** [comment]
@Mellbourn can you report this on our [vscode-docs](https://github.com/Microsoft/vscode-docs/issues) repository. I think a good place would be https://code.visualstudio.com/docs/editor/command-line
