### ISSUE TITLE
Some text starts to randomly show on the recommended extensions tab

### ISSUE THREAD

**Issue by tristan957** [microsoft/vscode#56407]
- VSCode Version: 1.26
- OS Version: Windows 10 64-bit 1709

Some text starts to randomly show on the recommended extensions tab.

![image](https://user-images.githubusercontent.com/11936772/44120402-e153cc7e-9fe1-11e8-86b2-53b5eadea131.png)

*hard to reproduce*

Steps to Reproduce:

1. Scroll around in installed extensions
2. Move your mouse quickly between installed extensions

Does this issue occur when all extensions are disabled?: N/A can't be reproduced without extensions installed

**Comment by tristan957** [comment]
![image](https://user-images.githubusercontent.com/11936772/44120509-317cbad0-9fe2-11e8-96a1-70d76ceeb3bb.png)

**Comment by tristan957** [comment]
I did not have to do anything except open VSCode and expand/shrink recommended tab

**Comment by sandy081** [comment]
@tristan957 Sorry, I cannot reproduce it with the steps you provided.

Is there another way to reproduce it consistently?

**Comment by tristan957** [comment]
I wish I could help more. Let me try and get a screen recorder and see if I reproduce it on video though, and maybe that will be of use. After a reload of VSCode, I can still reproduce the issue. 
![image](https://user-images.githubusercontent.com/11936772/44152099-2ded17ec-a06a-11e8-982b-da6f0c185860.png)

**Comment by tristan957** [comment]
The video is like a 1:30 long, and it took a while to reproduce. You can skip the first minute. Let me know what else I can help you with. https://drive.google.com/file/d/1C5OXrxPoCakG22QhjvjE08rE_2b1rCir/view?usp=sharing

**Comment by tristan957** [comment]
artifact did go away after clicking on an extension though

**Comment by sandy081** [comment]
Thanks for taking the time and providing the video. I see it is very hard to reproduce and I am afraid if I can. Will try though.

**Comment by tristan957** [comment]
Yea I don't expect it to really get fixed due to its hard reproducibility. Just wanted to bring it up in an issue so it could be documented. This may also just be something super specific to my setup (extensions, themes, etc.), which I would be happy to provide if you think it would be relevant

**Comment by tristan957** [comment]
I haven't noticed this in a while and might be worth closing
