### ISSUE TITLE
Input fields with validation should not use color alone to show validation state

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#56404]
Currently we only change the border color of the input field. This would cause an accessibility issue as screen readers aren't able to read style changes. We need to provide a way to show validation besides changing the color of an input field.

<img width="50%" src="https://user-images.githubusercontent.com/35271042/44118547-671131a6-9fcb-11e8-8c36-4b66a74befac.png">

**Comment by roblourens** [comment]
It might not be really necessary in this case because the query won't be used unless the user focuses the input box and presses enter. And when the focus the input box, they will see the error message.

**Comment by misolori** [comment]
Since our input boxes don't have a border by default and a border is added when there is focus + validation, this actually does not become an accessibility issue as the shape is included for showing meaning. I'll close this issue.
