### ISSUE TITLE
Typescript language server failed to start when switching OS user

### ISSUE THREAD

**Issue by SeriousLemon** [Microsoft/vscode#56405]
- VSCode Version: 1.26
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Install 1.26
2. Switch user
3. Open typescript file in code
4. See error "typescript language server failed to start"

It works fine on the original account Code was installed on. Reverting to 1.25 fixes the issue.

Does this issue occur when all extensions are disabled?: Yes

![ss](https://user-images.githubusercontent.com/5023169/44120716-9a340da2-a060-11e8-9ae8-6d399a396b97.jpg)

**Comment by jeswin** [comment]
Here's a poor/temporary workaround, but it shafts vscode for the account in which it was previously working. 

```sh
apt purge code
rm -rf .vscode 
apt install code
```

You're going to have to setup all extensions and redo settings again.

**Comment by mjbvz** [comment]
Are you using a workspace version of TypeScript, or the standard VS code version?

**Comment by SeriousLemon** [comment]
It happened with both. Workspace version is 2.9.2. I changed to the VS Code version with 1.26 which was 3.0.1 or whatever it was but it still occured.

**Comment by mjbvz** [comment]
@SeriousLemon Please share the text from the `typescript` section of the Output panel. Also, after switching users do you see similar errors when opening an html file or when trying to vs code's git tooling?

**Comment by SeriousLemon** [comment]
Thanks, I didn't know that typescript output panel existed. It seems the PATH on the user which it wasn't installed on is not `as` complete as the user on which it was installed on.

Output from alternate user:
`[Info  - 8:59:38 pm] Using tsserver from: /home/xxx/xxx/xxx/node_modules/typescript/lib
[Info  - 8:59:39 pm] Forking TSServer
PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin 
[Error  - 8:59:39 pm] Starting TSServer failed with error.
1`

**Comment by SeriousLemon** [comment]
Sorry, I've misreported this. Just realised the user it was installed with is irrelevant. Whichever user I log on with (and open a typescript file in VS Code) first works. If I log out or switch user, the second user receives the error. Regardless of which user it was initially installed with.

If I restart the pc, again the first user to open a typescript file works fine.

**Comment by mjbvz** [comment]
Can you please also try some other vscode functionality in this scenario, such as editing an html file or running git commands

**Comment by SeriousLemon** [comment]
Yes everything else appears to be fine. Other languages, HTML etc don't appear to have any issues. Git commands in the integrated terminal run fine. There are no other apparent issues.

**Comment by mjbvz** [comment]
One more thing to try: set `"typescript.disableAutomaticTypeAcquisition": true`. Then restart VS Code and try switching users again

**Comment by SeriousLemon** [comment]
No change, same error and output.

**Comment by nandowalter** [comment]
The same scenario on my laptop, rebooting machine solved the issue, until next user switch.

**Comment by SeriousLemon** [comment]
@mjbvz this appears to have been resolved as of 1.27.
