### ISSUE TITLE
VScode doesn't detect jsconfig.json

### ISSUE THREAD

**Issue by engmagdy87** [Microsoft/vscode#56416]
- VSCode Version: 1.26.0
- OS Version: Windows 10

Steps to Reproduce:

1. regenerate jsconfig.json on the level of src (react app)
2. 

```
{
  "compilerOptions": {
    "baseUrl": "./",
    "paths": {
      "@Components/*": ["Components/*"],
      "@Constants/*": ["Constants/*"],
    }
  },
  "exclude": ["node_modules", "dist"]
}
```

* the aliases doesn't appear in autocomplete menu

Does this issue occur when all extensions are disabled?: Yes/No
yes

**Comment by hegelstad** [comment]
remove the last comma in the paths.

**Comment by engmagdy87** [comment]
@hegelstad nothing happened
