### ISSUE TITLE
extreme lag for code completion

### ISSUE THREAD

**Issue by r3wt** [Microsoft/vscode#56411]
Issue Type: <b>Bug</b>

vscode has become laggy during code completion. there is a noticeable delay before code completion shows up, and a noticeable delay before it dissappears. ITs very annoying. it also lags out and freezes for 3 seconds when selecting from the code completion list. nothing happens during this timespan.

the entire program has become increasingly laggy as a whole, this is just the most notable symptom.

affected projects seem to be react and react-native(those are the only projects i am currently working on)

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (8.87GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
twigcs|cer|0.4.2
php-debug|fel|1.12.3
php-intellisense|fel|2.3.3
php-pack|fel|1.0.1

(1 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
How about telling me in what language that happens?

**Comment by r3wt** [comment]
@jrieken javascript (react and react-native)

**Comment by jrieken** [comment]
Closing for now. When this happens again, then please follow this guide: https://github.com/Microsoft/vscode/wiki/Performance-Issues#collect-information-about-the-running-vs-code. It will show how busy the extension host is.
