### ISSUE TITLE
Support "string | null" in settings editor?

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#56413]
#55794 implemented some compound/nullable types. But `string | null` is hard because different settings handle null vs '' differently.

So to handle this in the new settings editor we would either need

- New UI to set a text input to `null`
- Or a schema property to mark `string | null` settings that treat `''` and `null` the same

**Comment by rzhao271** [comment]
Changing this to a feature request.
I'm not too sure where this feature would be used.
