### ISSUE TITLE
'dnx web' doesn't execute in VSCode 1.0.0 on OpenSuSe Leap 42.1

### ISSUE THREAD

**Issue by s4rduk4r** [Microsoft/vscode#5641]
- VSCode Version: 1.0.0
- OS Version: OpenSuSe Leap 42.1

Problem: dnx web command doesn't execute, so I need to execute it manually via bash

Steps to Reproduce:

1. Install ASP.Net 5 as described here - http://docs.asp.net/en/latest/getting-started/installing-on-linux.html
2. Create project as described here - https://azure.microsoft.com/en-us/documentation/articles/web-sites-create-web-app-using-vscode/
3. Open it in VSCode
4. View->Command Palette->dnx Run Command->dnx web

**Comment by dbaeumer** [comment]
This issue was moved to OmniSharp/omnisharp-server#215
