### ISSUE TITLE
Explorer Outline

### ISSUE THREAD

**Issue by RonAndaya** [Microsoft/vscode#56418]
Issue Type: <b>Bug</b>

The Outline is not working anymore after the latest update. It is on 'Loading document symbols for...' 

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2687W v4 @ 3.00GHz (24 x 2993)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.92GB (47.41GB free)|
|Process Argv|C:\Users\randaya\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-great-icons|emm|2.1.41
mayaport|Jon|1.0.0
python|ms-|2018.7.1
cpptools|ms-|0.17.7
csharp|ms-|1.15.2
mel|sat|0.1.2
perforce|sle|3.1.0
shader|sle|1.1.3
pyqt-integration|zho|0.2.0

</details>

**Comment by jrieken** [comment]
How about telling me in what language that happens? This is likely an issue with the extension host being overly busy. Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

**Comment by RonAndaya** [comment]
@jrieken It happens in C++, C# and Python.

**Comment by jrieken** [comment]
Please follow this guide https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions also check this https://github.com/Microsoft/vscode/wiki/Performance-Issues#collect-information-about-the-running-vs-code
