### ISSUE TITLE
GTK File Opener Missing Icons

### ISSUE THREAD

**Issue by jadenPete** [Microsoft/vscode#56420]
- VSCode Version: 1.26.0
- OS Version: Arch Linux

Steps to Reproduce:

1. Click File -> Open Folder... [Ctrl+K Ctrl+O]

Does this issue occur when all extensions are disabled?: Yes
![screenshot from 2018-08-14 17-41-54](https://user-images.githubusercontent.com/13180372/44125893-e9ada9c8-9fe9-11e8-9ac6-76f6d164102a.png)

**Comment by bpasero** [comment]
@jadenPete how did this look like in our [previous release](https://az764295.vo.msecnd.net/stable/207ace21dfec3dccab52f1296a3880ac7644c978/code-stable-1533947775.tar.gz)?

**Comment by jadenPete** [comment]
@bpasero I get a Segmentation fault when I try to run the release you provided. This might be related to the issue with Electron and glibc, but that has been patched in the AUR package I'm using.

**Comment by bpasero** [comment]
Lets move into https://github.com/Microsoft/vscode/issues/55934
