### ISSUE TITLE
Javascript intellisense contains unrelated items

### ISSUE THREAD

**Issue by danderson00** [Microsoft/vscode#56422]
Issue Type: <b>Bug</b>

Many common keywords produce unrelated intellisense suggestions that are inserted incorrectly. For example, typing "test(" inserts "TextTrackList()" at the current cursor position. This obviously completely breaks workflow. This exact problem can be replicated on multiple machines.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (8.08GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Projects\scratch\New folder|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

Apologies for having to ZIP this file, github does not accept .mp4 files (?).

[intellisense.zip](https://github.com/Microsoft/vscode/files/2288942/intellisense.zip)

**Comment by mjbvz** [comment]
`TextTrackList` is a dom type. You can exclude dom suggestions by setting `"lib": ["es6"]` in a `jsconfig.json`:

```json
{
    "compilerOptions": {
        "target": "ES6",
        "lib": ["es6"]
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```

Or you can disable accepting suggestions when typing `(` by setting `"editor.acceptSuggestionOnCommitCharacter": false`

**Comment by medikoo** [comment]
@mjbvz can this be turned off, without a need to create `jsconfig.json`

It's quite a downside to create this file in every project to turn off nonsense suggestions.

**Comment by danderson00** [comment]
This doesn't seem to work for me. I have a `jsconfig.json` in the root folder with the contents pasted above, and I still get DOM and other suggestions.

**Comment by danderson00** [comment]
So... I tried moving `jsconfig.json` to the `.vscode` folder (which obviously doesn't work), and then after I moved it back to the root folder, it started working. **sigh** quality. Entirely possible it's me being an idiot, and I can no longer reproduce the issue.

I do agree with the comment made by @medikoo.

**Comment by medikoo** [comment]
@mjbvz I believe this should be reopened, as a need to create `jsconfig.json` for every project is obviously not a solution
