### ISSUE TITLE
Open file under cursor

### ISSUE THREAD

**Issue by bscipio** [Microsoft/vscode#56423]
**Feature Request**
built-in advanced "open file at cursor" or "open file under cursor"
functionality.  This functionality would make opening and editing various files from a reference in a original file very efficient.  

Similar to the following:

1. Extension: Open file
 - https://marketplace.visualstudio.com/items?itemName=Fr43nk.seito-openfile
 - https://github.com/fr43nk/seito-openfile
 - Does not require a workspace.
 - Seems to be handle quoted or unquoted file paths 

2. Extension: Open file from path
 - https://marketplace.visualstudio.com/items?itemName=jack89ita.open-file-from-path
 - https://github.com/Jack89ita/vscode-open-file-from-path
 - Requires a workspace to work
 - Needs a more flexible default regex
   - Such as automatically handle filenames whether in quotes or not.

3. vim "gf" : Open file under cursor
http://vim.wikia.com/wiki/Open_file_under_cursor

4. Analogous to "Go to definition" (F12, Cmd-Click) but for various files (.yml, .ini, .json, .etc) that
have references to other files.   

auto-search: This  feature could also auto-search from the currently open file's path
when the filepath as-is is not found.  Such as when a filepath under the cursor is not a fully defined
relative path,  but still expected to be somewhere relative to the currently open
file's path.  If implemented, auto-search probably should be configurable option.   
As last resort, the search could strip down the string to filename only (no relative
folders) to find the file.

Feature should be able to:
 - Handle absolute paths, 
 - Handle relative paths containing "..".  Assume paths defined relative to the open file.
 - Open file if only 1 match found, otherwise list possible choices.
 - Perhaps an option to prompt or auto-create referenced file when it is not found
 - Not require a workspace to be created
 - Be configurable
-  Mimic hyperlink behavior with custom mouse shortcuts

Thanks!

**Comment by roblourens** [comment]
Do those extensions cover it already? I would leave this up to an extension. If there are cases they don't cover, we also have the DocumentLinkProvider API for this sort of thing

https://github.com/Microsoft/vscode/blob/cb5558b99d633fb775b2ac0e56f7b7304ce3cff9/src/vs/vscode.d.ts#L3391

**Comment by bscipio** [comment]
Partially. They don't auto-search as described in first post.

My 2 cents: with it being so analogous to "Go to definition", which is not an extension, it makes more sense to me as a built-in.  

Also, the less we have to rely on IT to add extensions the better (corporate/firewalled environments).  It seems like a small feature relative to the Python & C++ extensions. Those 2 make sense to me as extensions.   

But it sounds like it might be worth adding feature requests to:
https://github.com/fr43nk/seito-openfile
and read more about the DocumentLinkProvider API
Thanks.
