### ISSUE TITLE
code hint in 1.26 can't continue

### ISSUE THREAD

**Issue by wszgrcy** [Microsoft/vscode#56428]
Issue Type: <b>Bug</b>

when I input some code and then display hint,when I tab select,and continue input ,the hint can't display,I must move right or left and then input that hint can display.
It's only on 1.26(both insider and release),I use on 1.25 is ok

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.85GB (0.81GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\NGP\海信\bms|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|1.2.6
vscode-file-peek|abi|1.0.1
html-snippets|abu|0.2.1
Bookmarks|ale|9.0.3
vscode-angular2-files|ale|1.6.1
ng-template|Ang|0.1.9
nestjs|ash|1.0.1
path-intellisense|chr|1.4.2
regex|chr|0.2.0
bracket-pair-colorizer|Coe|1.0.59
ionic3-vs-ionView-snippets|dan|1.0.2
xml|Dot|2.3.1
vscode-html-css|ecm|0.2.0
vscode-npm-script|eg2|0.3.5
auto-rename-tag|for|0.0.15
code-runner|for|0.9.4
beautify|Hoo|1.3.2
vscode-power-mode|hoo|2.2.0
docthis|joe|0.7.1
node-module-intellisense|lei|1.5.0
json-to-ts|Mar|1.5.5
Angular-BeastCode|Mik|6.2.10
vscode-scss|mrm|0.6.2
vscode-language-pack-zh-hans|MS-|1.26.3
debugger-for-chrome|msj|4.8.2
view-in-browser|qin|0.0.5
vscode-icons|rob|7.25.0
markdown-preview-enhanced|shd|0.3.5
stylelint|shi|0.38.1
ionic3-snippets|sit|1.0.1
autoimport|ste|1.5.3
move-ts|str|1.11.3
markdown-all-in-one|yzh|1.6.0

</details>

**Comment by sandy081** [comment]
Can you please provide a video(gif) of the issue you see?

**Comment by jrieken** [comment]
Add this to your configuration: `"editor.suggest.snippetsPreventQuickSuggestions": false,`. That enables quick suggestion to pop up while navigating a snippet. See #50776 for more details.
