### ISSUE TITLE
bad syntax highlight while '+=' in for?

### ISSUE THREAD

**Issue by zheung** [Microsoft/vscode#5642]
- VSCode Version:1.0.0
- OS Version:Windows 8

Syntax highlight does not working while use `+=` in `for`.

Code:
```javascript
var node;
for(var i; i< 45;i++) {
	node = 234;

	node.a = 122;
	node.b += 122;
	node.b += '1'+1+'2';
}
```

see gif pls...
![1](https://cloud.githubusercontent.com/assets/894004/14734759/3f0e9ee8-089f-11e6-97d1-79b9220bd0be.gif)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#152
