### ISSUE TITLE
Terminal output not support Chinnese encoding

### ISSUE THREAD

**Issue by CS4Fly** [microsoft/vscode#56425]
Issue Type: <b>Bug</b>

In Visual Studio Code editor , Chinese display normal , but display abnormal in Terminal.
I use other IDE could dispaly Chinese normal in terminal.

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 6.1.7601

<details>
![2333](https://user-images.githubusercontent.com/35210507/44128805-7975a1ea-a077-11e8-9951-0c71e5ca0cd6.png)

<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (3.73GB free)|
|Process Argv|E:\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|44%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-clang|mit|0.2.2
vscode-language-pack-zh-hans|MS-|1.26.3
cpptools|ms-|0.17.7

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
@tylerl0706 I think there's some workaround for this that involves passing some args to powershell on start up, do you know what it is?

**Comment by tylerl0706** [comment]
Nah, there's no such args. I'm a bit confused by the issue because it looks like Chinese characters are showing up in the screenshot.

@CS4Fly do you think you can circle the problem and say what you expect?

**Comment by tylerl0706** [comment]
On Windows, the console has a concept of code pages, but I doubt the vscode terminal inherited this problem.

Also, @CS4Fly, are you using PowerShell?

**Comment by daxian-dbw** [comment]
No idea what the problem is, but it's specific to VS Code. The default powershell terminal that comes with VS Code can take Chinese character input properly, but not the `PowerShell Integrated Console` comes with VS Code.

![image](https://user-images.githubusercontent.com/127450/45441690-9a8a0c00-b674-11e8-825a-2a8244762240.png)

![image](https://user-images.githubusercontent.com/127450/45441717-abd31880-b674-11e8-8150-b377ba773832.png)

**Comment by tylerl0706** [comment]
@daxian-dbw Yeah the integrated console does have some known issues with Chinese characters... 

However, based on the screenshot that the [issue filer supplied](https://user-images.githubusercontent.com/35210507/44128805-7975a1ea-a077-11e8-9951-0c71e5ca0cd6.png), they don't seem to be using PowerShell.

So I wanted to confirm that.

**Comment by daxian-dbw** [comment]
Ah, I didn't see such screenshot in the issue, and was assuming it's with the VS Code terminal.

**Comment by tylerl0706** [comment]
No worries! It was under the `System Info` dropdown.

**Comment by daxian-dbw** [comment]
The image is not properly rendered under `System Info` dropdown.
