### ISSUE TITLE
no provider for file:///... when moving file from FileSystemProvider to local

### ISSUE THREAD

**Issue by iann0036** [Microsoft/vscode#56426]
When moving a file from a workspace folder provided by a custom FileSystemProvider to a local folder, I get `no provider for file:///<fslocation>/file.txt`

Should we be providing an additional FileSystemProvider to serve file:// transfers (probably using the WorkspaceEdit actions)?

- VSCode Version: 1.26.0
- OS Version: Darwin

Steps to Reproduce:

1. Install MemFS sample extension
2. Populate the MemFS folder with files
3. Drag a file from the MemFS folder to a local folder

This issue does not throw an error when:

* Dragging a local file to a FileSystemProvider folder
* Dragging files between different FileSystemProvider folders

Does this issue occur when all extensions are disabled?: N/A

**Comment by iann0036** [comment]
Possibly related to https://github.com/Microsoft/vscode/issues/48034

**Comment by jrieken** [comment]
What kind of file are you dragging? Is it a text file or a binary file?

**Comment by jrieken** [comment]
nevermind, I can reproduce

**Comment by jrieken** [comment]
Closing this as a dupe of #41543. Internally, the file-scheme handling isn't really fit for interacting with data from file system providers.
