### ISSUE TITLE
White toolbar after upgrading to 1.26.0

### ISSUE THREAD

**Issue by zingdle** [microsoft/vscode#56427]
- VSCode Version: 1.26.0
- OS Version: Ubuntu 16.04 with GNOME 3.18.5

![screenshot from 2018-08-15 10-54-01](https://user-images.githubusercontent.com/31171119/44129169-9e28850a-a079-11e8-8b0d-9358fe8ef7be.png)

I upgraded from 1.25.X to 1.26.0. Is this a new feature or something else? I don't think it matches the dark theme though. 

Does this issue occur when all extensions are disabled?: Yes

||System Info|
-- | --
CPUs | Intel(R) Core(TM) i7-4712MQ CPU @ 2.30GHz (8 x 2186)
GPU Status | 2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled<br>
Load (avg) | 1, 1, 1
Memory (System) | 7.52GB (2.10GB free)
Process Argv | /usr/share/code/code --disable-extensions
Screen Reader | no
VM | 0%

**Comment by bpasero** [comment]
@zingdle how did this look like in our [previous release](https://az764295.vo.msecnd.net/stable/207ace21dfec3dccab52f1296a3880ac7644c978/code-stable-1533947775.tar.gz)?

**Comment by zingdle** [comment]
@bpasero It looks like this before
![](https://fedoramagazine.org/wp-content/uploads/2017/10/vsc-openfolder-1024x615.png)
The toolbar color matches well.

**Comment by zingdle** [comment]
@bpasero The configuration works, but with a slightly different toolbar. Hope this can be fixed later : -)

I tried the latest builds and the white background is still there.

**Comment by bpasero** [comment]
@zingdle is the menu looking white in other apps too for you? maybe there is a setting in the OS to change this?

**Comment by zingdle** [comment]
@bpasero The toolbar on other apps looks fine on my machine, though I don't know whether it's GTK 3 or 2.

**Comment by microcoder** [comment]
@zingdle You can also select GTK3 theme in a Application Style menu of KDE:
![kde_select_app_style](https://user-images.githubusercontent.com/2853555/44133152-e47d7cbc-a066-11e8-8cc5-0e9563849cf4.PNG)

But then the standard controls in the firefox are switched to dark mode :(
![firefox_controls](https://user-images.githubusercontent.com/2853555/44133452-81b896e6-a068-11e8-8dd2-90892c210caa.PNG)

**Comment by wooque** [comment]
Same, it used to be black now it's white after update.
Manjaro Xfce, Arc Darker theme.

**Comment by kmare** [comment]
The same is happening to me on Fedora 28, using the default dark adwaita theme on Gnome. Before it was working fine. But I'm glad vscode finally switched to electron 2.

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)
