### ISSUE TITLE
Eka Kurniawan

### ISSUE THREAD

**Issue by fruitstealer** [Microsoft/vscode#56436]
Issue Type: <b>Bug</b>

Cant change Version Control from git to svn

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.89GB (8.18GB free)|
|Process Argv|C:\Users\Ignite\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vue-peek|dar|1.0.2
vscode-eslint|dba|1.4.12
vscode-npm-script|eg2|0.3.5
vscode-svn|eli|0.1.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
svn-scm|joh|1.31.0
vuejs-extension-pack|mub|1.1.2
vscode-status-bar-format-toggle|tom|1.4.0
JavaScriptSnippets|xab|1.7.0

</details>

**Comment by joaomoreno** [comment]
This issue was closed because it doesn't meet our standards of a properly filled issue. Please read our guide about [Submitting Bugs and Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).
