### ISSUE TITLE
rg.exe占内存直接100%

### ISSUE THREAD

**Issue by MinHongwei** [Microsoft/vscode#56431]
所需的数据太大，无法直接发送。我们已经将其写入剪贴板，请粘贴。
Issue Type: <b>Performance Issue</b>

更新新版本 打开vscode 内存占用 直接慢慢变成100%，删除rg.exe后恢复正常。

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (3.91GB free)|
|Process Argv|D:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    5	   129	  4868	code main
    0	    64	  7052	   shared-process
    0	   194	  7460	   window (statVendorDevice.js - 无标题 (工作区) - Visual Studio Code)
    0	    41	  2420	     watcherService
    0	    35	  3084	     searchService
    0	    13	  5072	     electron-crash-reporter
    0	     6	  7920	     winpty-process
    0	    62	  8180	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     8	 13236	       console-window-host (Windows internal process)
    0	    60	 13552	     extensionHost
    0	    53	  1612	       electron_node tslintServer.js 
    0	    84	  7448	       electron_node electronForkStart.js tsserver.js 
    0	    57	 10384	         electron_node typingsInstaller.js tsserver.js typesMap.js 
    0	    36	 10988	       searchService
    0	    65	 12544	       electron_node eslintServer.js 
    0	   161	 11252	   gpu-process
    0	    80	 14852	   window (问题报告程序)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (statVendorDevice.js - 无标题 (工作区) - Visual Studio Code)
|    Folder (myworkvrsm): 5917 files
|      File types: js(3378) less(1014) md(729) ts(325) png(250) jpg(63)
|                  mp4(23) yml(16) json(16) svg(13)
|      Conf files: package.json(13)
|    Folder (minhw): 7666 files
|      File types: java(4638) js(543) xml(440) md(250) less(224)
|                  properties(215) ts(147) html(103) groovy(101) gradle(86)
|      Conf files: package.json(7) webpack.config.js(3) jsconfig.json(3);
```

</details>
<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.12
tslint|eg2|1.0.34
vscode-language-pack-zh-hans|MS-|1.26.3

</details>

**Comment by gdh1995** [comment]
我昨天台式机和笔记本各遇到了一次rg.exe的cpu占用率到了100%，台式机的rg被我kill了，笔记本跑了十几秒后rg.exe自己退出了，好像是刚打开工程文件夹时扫描所有文件的问题。之后我没怎么继续用笔记本，不知道会不会再次遇到。

**Comment by netjune** [comment]
开发人员能看懂中文吗? 什么时候会运行rg.exe? 跟插件有关? 还是VS Code部分功能依赖rg.exe?

**Comment by sandy081** [comment]
@JeanmarkD Can you please provide the issue summary and description in English. Also screenshots would be helpful.

**Comment by sandy081** [comment]
Assuming this is duplicate of #56328
