### ISSUE TITLE
Font is not looking crisp but blurry

### ISSUE THREAD

**Issue by JeanmarkD** [microsoft/vscode#56434]
Issue Type: <b>Bug</b>

更新完之后字体和界面容易出现模糊

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.86GB (4.17GB free)|
|Process Argv|D:\Users\hasee\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-eslint|dba|1.4.12
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.34
auto-rename-tag|for|0.0.15
vscode-language-pack-zh-hans|MS-|1.26.3
open-in-browser|tec|2.0.0
JavaScriptSnippets|xab|1.7.0
html-css-class-completion|Zig|1.17.1

</details>

**Comment by netjune** [comment]
Same here on Linux x86_64. Font is not as clear as the last version.

**Comment by sandy081** [comment]
@JeanmarkD Can you please provide the issue summary and description in English. Also screenshots would be helpful.

**Comment by hail2u** [comment]
Same here. v1.25.1 looks smoother to me.

v1.25.1:
![20180817090423](https://user-images.githubusercontent.com/68940/44241149-0c4d7200-a1fd-11e8-8e5e-04ebf888f2ff.png)

v1.26.0:
![20180817090630](https://user-images.githubusercontent.com/68940/44241150-0d7e9f00-a1fd-11e8-95ee-4341bf6acc79.png)

**Comment by chinacourt** [comment]
今天更新了1.26.1    字体模糊  无法工作   之前版本没有

**Comment by chinacourt** [comment]
已恢复   原因    1050Ti  更新显卡驱动后恢复
