### ISSUE TITLE
Need two buttons (1: Go Back  2: Go Forward)

### ISSUE THREAD

**Issue by netjune** [Microsoft/vscode#56437]
I like navigating code with mouse. I can go to definiton or go to declaration or switch file with mouse easily, but going back is not convenient with mouse(I need to MOVE mouse to the "Go" menu and then select the menu item).

Since they are so commonly used, can you make them convenient to use with mouse? (such as adding two buttons to somewhere or adding two menu items in the context menu)

**Comment by nelsonlaquet** [comment]
If you have a mouse with a fourth and fifth (thumb) button, they work as expected as back/forward. If you don't yet have a mouse with a fourth and fifth button, yet rely on mouse navigation, I _highly_ recommend one - many modern, and even cheap, mice will have them.

**Comment by netjune** [comment]
My mouse does have 5 buttons. But the fourth and fifth buttons don't work in VS Code. Maybe It doesn't work on Linux? I'm using Centos 7 Desktop.

They work well in GNU Emacs. They are recognised as mouse-8 and mouse-9.
