### ISSUE TITLE
VS Code Hangs When Opening Specific PowerShell File

### ISSUE THREAD

**Issue by Mibz** [Microsoft/vscode#56430]
Issue Type: <b>Bug</b>

I am experiencing a problem with VS Code hanging when opening a specific PowerShell file. I think the problem is with the Powershell Language Basics extension, not the Powershell extension, which is why I'm posting here.

When opening the specific script VS Code will hang and eventually I'll receive a prompt saying "The window is no longer responding" and I'm given the option to Reopen, Keep Waiting, or Close.

Reopening the window results in the same behaviour.
Keep Waiting results the same behaviour, though I only clicked it 5-6 times before giving up.
Closing the window works correctly.

If I disable the PowerShell extension and Powershell Language Basics extension, the file loads properly.
If I then re-enable the PowerShell extension and reload, VS Code hangs again.
<b>If I disable the PowerShell extension but leave the Powershell Language Basics extension enabled, the file fails to load.</b>

I can open any other PowerShell file with both extensions enabled, it's just the one file that causes problems. It's 29 KB and ~700 lines. I've tried on two different machines running the same version of Windows, VS Code, and the extensions with no difference in behaviour.

No logs are created in the `.vscode\extensions\ms-vscode.powershell-1.8.2\logs` folder when this error occurs.

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
<b>This was also attempted on 1.27.0-insider with the same results</b>
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.96GB (22.16GB free)|
|Process Argv|*removed by reporter*
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
PowerShell|ms-|1.8.2
vscode-autohotkey|sle|0.2.2

</details>

**Comment by Mibz** [comment]
Can confirm my behaviour seems identical. I pasted the file from that issue into VS Code without a problem, but once I saved it as .ps1 VS Code hung as it does with my script.

**Comment by aeschli** [comment]
I reverted the grammar to https://github.com/PowerShell/EditorSyntax/commit/6f5438611c54922ea94c81532a2dcfee72190039
where this this [file](https://github.com/larssb/HealOps/blob/master/Deployment/Install-HealOps.ps1) does no longer crash.
