### ISSUE TITLE
Highlight parent folder when creating a new file.

### ISSUE THREAD

**Issue by saurabhpati** [Microsoft/vscode#56440]
Feature:
I would really like if the folder in which a new file I am creating could be highlighted so that I know where that new file is going to land.

Problem: I create a lot of new files for a bunch of different side projects that I work on and I am sure there are many like me who like to work on side projects which involve creating a lot of files. I find it difficult if I have focused in on a folder unintentionally while creating a new file, it lands on that folder where it wasn't intended to.

Existing functionality:
I believe the folder in which we are creating a new file expands if it is closed indicating that there is where it is going to land but its difficult to spot if it is already open. I believe just a small feature of having other files and folders faded and only the parent folder of the file highlighted (or not faded) could be a much better indicator of where the new file is gonna land.

Screenshot for reference:
![image](https://user-images.githubusercontent.com/20544414/44133615-5312c544-a07e-11e8-9a50-ac049f43c12d.png)

Would love to know your thoughts. I hope I gave a good explanation.
Thanks.

**Comment by isidorn** [comment]
This is not a bad idea as sometimes it is hard to figure out where the file gets created.
However the tree is currently not supporting this and it might unneceserily take attention from the user

For now leaving this open and assigning it to the backlog for discussions
fyi @misolori
