### ISSUE TITLE
Vscode cannot be opened after today's update(China, Windows7 ,64bit)

### ISSUE THREAD

**Issue by miyoosan** [Microsoft/vscode#56447]
- VSCode Version:latest version2018年8月15日15:54:37
- OS Version:

Steps to Reproduce:

1.update Vscode
2.when updated, open Vscode

Does this issue occur when all extensions are disabled?: no any extensions

I just update my Vscode, but after updated, it doesn't work. And it's process dosen't exist in TaksManagement

**Comment by miyoosan** [comment]
Re-install cannot fix any problems;
Clear register and disk do nothing help;
Even, --rm Code file folder in Roaming has no effect for Vscode of latest versions; but for old version's, it works;

**Comment by miyoosan** [comment]
Is there anyone here?
I download the .zip 1.26version，it can works; but I don't know when next version comes updated, it will weather work or not;
Please help me. Thanks

**Comment by sandy081** [comment]
Can you please try opening VS Code from cli with `--verbose` option and check if you see any errors printed?

Also try pointing to a different user data directory using `--user-data-dir` option

**Comment by bpasero** [comment]
@miyoosan are you on Linux, maybe ArchLinux?

**Comment by flashery** [comment]
@bpasero I am on linux and I am experiencing the same issue. when Opening a file or opening workspaces

**Comment by nealot** [comment]
@flashery Perhaps you are experiencing https://github.com/Microsoft/vscode/issues/55934?

**Comment by flashery** [comment]
@nealot  thanks the have the updated version and fix the issue

**Comment by miyoosan** [comment]
@sandy081 @bpasero well, I am on Win7. I'd found my problem is similarily with #56503.
Since I have download then .zip Code, I can't recurrent the crash.
But I will  follow https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues and share more information about the crash when it happens inthe near futrue.

**Comment by bpasero** [comment]
@miyoosan please do. so you say you can run VSCode from the zip but not from the installation?

**Comment by miyoosan** [comment]
@bpasero yes

**Comment by bpasero** [comment]
This sounds like a installation issue to me then.

**Comment by joaomoreno** [comment]
Alright, let us know if you have more insights on the crash.

**Comment by miyoosan** [comment]
OK
