### ISSUE TITLE
"window.titleBarStyle": "custom" Menus with missing symbols

### ISSUE THREAD

**Issue by jpenna** [Microsoft/vscode#56445]
- VSCode Version: 1.26.0
- OS Version: Linux Debian 9 (Gnome 3.22.2)

Steps to Reproduce:
1. Set  "window.titleBarStyle": "custom"
2. Open any menu

Does this issue occur when all extensions are disabled?: Yes

There is a symbol after each line in the menu context and the arrow ( > ) are poorly rendered
![screenshot from 2018-08-15 15-34-13](https://user-images.githubusercontent.com/16005946/44137403-e88f6a5e-a0a2-11e8-9bfd-8622c38c4778.png)

The menus for Right Clicking are OK
![screenshot from 2018-08-15 15-37-54](https://user-images.githubusercontent.com/16005946/44137410-ee039fe6-a0a2-11e8-821a-b558398c14f4.png)

Might be related to my system's fonts? 
I think this would easily explain the ugly ">", but not the missing symbols though.

**Comment by sbatten** [comment]
Hi @jpenna, this is an unfortunate issue caused because the underlining of mnemonics is given via a Unicode character that some fonts are not able to render. I'm looking to fix this very soon. In the meantime, if you don't use mnemonics, you can disable them to avoid seeing the ugly boxes. `window.enableMenuBarMnemonics` -> `false`.

As for the arrows icon, this is also due to the font. Would you be able to check the font being loaded in the dev tools?

**Comment by jpenna** [comment]
Hey @sbatten, the `window.enableMenuBarMnemonics: false` removed some of the symbols, but not all of them. Everywhere there are submenus (arrows >) there is still the symbol. But it is much better this way at least, thanks.

![screenshot from 2018-08-16 14-47-51](https://user-images.githubusercontent.com/16005946/44192822-6d286c00-a163-11e8-9097-5289748f0ebf.png)

About the font, I don't if this is it.

![screenshot from 2018-08-16 14-44-31](https://user-images.githubusercontent.com/16005946/44192723-1e7ad200-a163-11e8-9a8e-45c7e50792b7.png)

If it is from this class, I copied the font family: `-apple-system,BlinkMacSystemFont,Segoe WPC,Segoe UI,HelveticaNeue-Light,Ubuntu,Droid Sans,sans-serif`

**Comment by misolori** [comment]
@sbatten I can create an svg icon to test with the submenu

**Comment by sbatten** [comment]
@misolori awesome, you can assign this back to me when we have an svg, thanks

**Comment by misolori** [comment]
@sbatten I think you already fixed this but assigning back to you.

**Comment by sbatten** [comment]
yes, this is now resolved, thanks
