### ISSUE TITLE
Breadcrumb file path starting at the workspace root

### ISSUE THREAD

**Issue by samuelmaier** [Microsoft/vscode#56442]
In the moment there are three options to choose from: on, off and last.
It would be great to have a fourth option to show all directories of the the file path starting from the workspace root.

**Comment by jrieken** [comment]
> of the the file path starting from the workspace root.

That's what is does. All paths of files that are contained in the current folder or workspace are shown relative to that. Not really sure what you want then.

**Comment by samuelmaier** [comment]
When I first tried it out, the file path started with "C:\Users\...", so I thought that's how its ment to be. But now it indeed starts at the workspace root and I cannot reproduce it. So we can close it, sorry!

**Comment by jrieken** [comment]
Ok. Thanks for getting back to me
