### ISSUE TITLE
Test: debug threads

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#5644]
- [x] win @kieferrm 
- [x] mac @jrieken 
- [x] linux @joaomoreno 

We have changed quite some things how threads are handled by the vscode debugger. Pick one language that supports multiple threads (e.g go, c++, mono, php) and verify:
* Newly created threads are reflected in the callStack view
* Multiple threads can be stopped at the same time and it is possible to inspect their call stack
* One thread resuming execution does not affect other stopped threads

**Comment by felixfbecker** [comment]
- A thread that exits should disappear from the call stack view
