### ISSUE TITLE
Every time I open vscode - it creates 10k+ instances of gitbash

### ISSUE THREAD

**Issue by ZVER3D** [Microsoft/vscode#56448]
- VSCode Version: 1.26
- OS Version: Windows 10 Pro 1709 x64

Steps to Reproduce:

1. Open VSCode
2. Wait 5 Seconds
3. See 5k+ instances of vscode in task manager

Does this issue occur when all extensions are disabled?: Yes

Yesterday i updated my vscode to version 1.26, created a few changes to my project, turned off my PC and went to sleep. Today, every single time I open vscode it produces git bash processes over and over again untill my system crashes. Turning off vscode in task manager doesn't stop it from producing new git bash processes. So I have to restart my computer every time I unsuccesfuly try to fix this issue. I've already checked my computer for viruses, using Kaspersky and than Avast, but didnt find any viruses, even when i explicitly made the antiviruses check vscode installation and vscode plugins folders.
Then I thought that there's some kinda issue with git bash, so i completely reinstalled it, but it didn't help either. I've tried to launch with all extensions turned off, but it also didnt help.
Also, I reinstalled vscode completely, but sadly, it didn't work. I have no idea what else to do or what could be causing the issue, so please help me fixing it or at least give me some ideas on what could be causing this issue.

**Comment by joaomoreno** [comment]
Can you install Process Hacker, enable the `Command Line` column in its table view, and show me a screenshot of all those bash processes with their `Command Line`, when they appear?
