### ISSUE TITLE
Duplicated monaco compile checks

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#56457]
https://github.com/Microsoft/vscode/commit/baf6fbc777fcf344e3c6876db83be2f28018bfda duplicated the monaco editor compile check. There is now `monaco-compile-check` and `check-monaco-editor-compilation`. Both are referenced by the build configs.

**Comment by joaomoreno** [comment]
@jrieken So... which one should be called? I don't know much about them.

**Comment by jrieken** [comment]
> which one should be called

It doesn't matter - both do the same. I have added `monaco-compile-check`, later you have added `check-monaco-editor-compilation` which you seem to like better

**Comment by joaomoreno** [comment]
I see, must've been on 🍺 at the time.
