### ISSUE TITLE
.wxml file can't show comments correctly.

### ISSUE THREAD

**Issue by kingsNow** [Microsoft/vscode#56453]
Issue Type: <b>Bug</b>

v1.25 is okey ! 
In v1.26 .wxml file Cannot display comments correctly!

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.47GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_516222|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-weapp-api|cod|0.1.8
vscode-wxml|cod|0.1.9
xml|Dot|2.3.1
gitlens|eam|8.5.4
vscode-html-css|ecm|0.2.0
beautify|Hoo|1.3.2
vue|jcb|0.1.5
docthis|joe|0.7.1
vscode-language-pack-zh-hans|MS-|1.26.3
js-patterns-snippets|nik|0.0.5
gitconfig|sid|1.0.1
JavaScriptSnippets|xab|1.7.0

</details>

**Comment by kingsNow** [comment]
I rolled back version. Thanks!

**Comment by sandy081** [comment]
@kingsNow Can you please show the screenshot of what is not getting displayed correctly?

**Comment by kingsNow** [comment]
https://pan.baidu.com/s/1VeFp7LZpuBQQs8uQsqPDAg
Use V2.5 and V2.6 open this file, and compaire. Thanks!

**Comment by kingsNow** [comment]
![sss](https://user-images.githubusercontent.com/7920157/45738474-1d860600-bc23-11e8-940e-4b2a3cfd1151.png)
@aeschli

**Comment by aeschli** [comment]
The problem is the nesting of comments. That's not allowed in XML and that's why the sytax highlighting shows everything as comment. 
See https://stackoverflow.com/questions/1324821/nested-comments-in-xml/35479062
