### ISSUE TITLE
Python string like r'.\xxx.jpg' causes editor rendering error color.

### ISSUE THREAD

**Issue by thesby** [Microsoft/vscode#56460]
Issue Type: <b>Bug</b>

path = r'.\023455.jpg'

input the code into your editor, you will find that the color '023' is error, seeming that no 'r'.

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4030U CPU @ 1.90GHz (4 x 1895)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.70GB (0.52GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
python|don|0.7.0
vscode-language-pack-zh-hans|MS-|1.26.3
mssql|ms-|1.4.0
python|ms-|2018.7.1
cpptools|ms-|0.17.7

</details>

**Comment by aeschli** [comment]
This issue was moved to MagicStack/MagicPython#152
