### ISSUE TITLE
Multi-Root Behaviour (definitions & debug)

### ISSUE THREAD

**Issue by zukoaang** [Microsoft/vscode#56469]
Hi,
Working on Nodejs system made from multiple mini-services.
Two issues occurred when I started using multi-root workspace.

1. cmd + click (or 'go to definition') isn't working anymore.
2. while debugging, if I set breakpoints across multiple files from different projects, all breakpoints will work regardless of my active project.

So, for both issues my question is, does this behaviour happen by design, or is it a configuration problem?

Feels to me that issue No. 2 might be intentional, though I'd like a way to have only the breakpoints on my active project to function, without having to edit them every time I switch active project.
But issue No. 1 feels like a bug or config problem since it works fine on a single-root folder.

**Comment by isidorn** [comment]
No 2 is by design. 
No 1 forwarding to @mattbierner

**Comment by mjbvz** [comment]
Please provide a code / small project example for 1
