### ISSUE TITLE
custom 'html' tags are in red color

### ISSUE THREAD

**Issue by VladimirAmiorkov** [Microsoft/vscode#56467]
- VSCode Version: 1.26.0 (1.26.0)
- OS Version: macOS High Sierra 10.13.6 (17G65)

Steps to Reproduce:

1. Download [this](url
https://github.com/telerik/nativescript-ui-samples-angular/blob/master/listview/app/examples/getting-started/listview-getting-started.component.html) html file or create one with "invalid" html tags
2. Open it in the latest version of Vs Code
3. The `GridLayout`, `RadListView` and `StackLayout` are coloured bright red as shown in the screenshot bellow

![screen shot 2018-08-15 at 15 25 01](https://user-images.githubusercontent.com/4989411/44148085-727d13be-a09f-11e8-99cb-d1a100ac6ba7.png)

Does this issue occur when all extensions are disabled?: Yes

I see that this is probably an new feature that has been added to show "invalid" html tags as red but in our realm we are developing [NativeScript with Angular](https://docs.nativescript.org/angular/start/introduction) which includes the creation of our custom html tags which are not part of the standard html tags. Can this be disabled or changed in any way, those tag where not coloured in bright red in the previous version, only in 1.26.0.

**Comment by aeschli** [comment]
This issue was moved to textmate/html.tmbundle#92
