### ISSUE TITLE
Terminal display ,some text is cut when resize window

### ISSUE THREAD

**Issue by yuyuxp** [Microsoft/vscode#56461]
- VSCode Version: 1.26.0
- OS Version:Windows 8.1 

Steps to Reproduce:

1.I use max size of vscode window ,  then I run the code , the terminal is output some log text ,
2.when I resize the vscode window,(cancel the max size ),the text in the terminal is cut . 

 
![vscode](https://user-images.githubusercontent.com/41459864/44143734-670082a6-a0b7-11e8-9abd-35407191c049.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
