### ISSUE TITLE
Keyboard input is not read by VoiceOver in terminal

### ISSUE THREAD

**Issue by Mohamed-Fayed** [microsoft/vscode#56468]
I'm a legally blind developer . I use voiceover on Mac OS 10.13.6 . I face some problems in dealing with terminal and text editor in Visual studio code .
In the terminal, I can't get any feedback from the screen reader . I can't hear what I type ,which is the same problem in text editor. And don't hear the output of my commands read aloud . I can't also access them using arrow keys in either modes of quick nav. 
Please add more support for Voiceover on Mac for visual studio code.
Thank you so much.

**Comment by Tyriar** [comment]
> I can't hear what I type ,which is the same problem in text editor

The text editor is accessible, make sure you enable accessibility mode using alt+f1 on mac. Also we're don't fully support voice over just yet but are working towards it in other issues https://github.com/Microsoft/vscode/labels/accessibility

**Comment by Mohamed-Fayed** [comment]
Ok, I used it and it works properly on the text editor. :)
Thank you so  much , :)
Sincerely,
Mohamed E. Fayed


On Sep 17, 2018, at 6:43 PM, Daniel Imms <notifications@github.com<mailto:notifications@github.com>> wrote:


I can't hear what I type ,which is the same problem in text editor

The text editor is accessible, make sure you enable accessibility mode using alt+f1 on mac. Also we're don't fully support voice over just yet but are working towards it in other issues https://github.com/Microsoft/vscode/labels/accessibility

**Comment by Tyriar** [comment]
@alexandrudima good to know, thanks.

**Comment by isidorn** [comment]
Typing anywhere in vscode latest the VoiceOver nicely echoes
However when typing in terminal the letters are not echoed.

I have verified this is not an electron issue. Removing electron.

@Tyriar could you investiagate if you are doing somethign differently than the editor. And if you can fix this in the terminal? (Do you have a hidden text input like the editor so everything gets read out by a screen reader?)

**Comment by Tyriar** [comment]
https://github.com/xtermjs/xterm.js/pull/2329

**Comment by rebornix** [comment]
Not sure if I made anything wrong, but it still doesn't echo what's being typed.
