### ISSUE TITLE
Git message box default text isn't localised

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#56462]
* start vscode in german
* see this

<img width="337" alt="screen shot 2018-08-15 at 12 24 32" src="https://user-images.githubusercontent.com/1794099/44144016-3cf6cb5e-a086-11e8-996c-3ee3ea246831.png">

**Comment by joaomoreno** [comment]
Yes, it is:

https://github.com/Microsoft/vscode/blob/master/extensions/git/src/repository.ts#L542

**Comment by jrieken** [comment]
Hm... Maybe not translated then?

**Comment by joaomoreno** [comment]
@danyeh It seems it's not translated at all in the German language pack:

![image](https://user-images.githubusercontent.com/22350/44215685-6e619500-a173-11e8-86b7-d3d96768385c.png)

**Comment by danyeh** [comment]
Next translation pull should have the issue fixed. It was not a new string.
https://www.transifex.com/microsoft-oss/vscode-extensions/translate/#de/$/132525549?q=text%3A'Message+(press'
