### ISSUE TITLE
Labels: the description part no longer shows with opacity

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#56465]
@misolori I assume this was another change for accessibility? What is the reasoning? Unfortunately there is no theming option to change this currently. 

![image](https://user-images.githubusercontent.com/900690/44146699-240c181e-a091-11e8-80a5-e0b24e0ea8ed.png)

I find it very hard to distinguish between the file name and the rest since the colors are the same. At the very minimum, please provide an option in the theme to change this again if the user prefers our old solution.

Nevertheless I would prefer if we revisited this change and go back to how it was.

**Comment by isidorn** [comment]
Might be caused by a change by @misolori 
@misolori let me know if you are aware of a change, if not then I might have broken this with some unreldated refactoring

Either way making the description not som promiment makes perfect sense and we should go back to our old behavior

**Comment by bpasero** [comment]
It originates from @misolori commit: https://github.com/Microsoft/vscode/commit/eb05098ab814c9f6d4af62ce3ab5bf00149515b5#diff-033e039e168b97d04878c24fd0cce4a4

**Comment by isidorn** [comment]
Yeah let's revert that, ok @misolori ? And try to fix the color contrast in some other way as lower priority.
After all it is a description which is not so important.

**Comment by misolori** [comment]
I can revert it but it will fail on the color contrast ratio when a row is selected. We could look into changing the opacity when it's selected. I'll re-open the original bug.

**Comment by isidorn** [comment]
@misolori thanks, I have commented in the newly created issue
