### ISSUE TITLE
Failed to install VS Code update.

### ISSUE THREAD

**Issue by sqkmarshall** [Microsoft/vscode#56474]
As instructed by updater I'm making a new issue here and attaching the requested log file. Seems its already been reported but you did ask for a new one :)

Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:43:53.668Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

Edition: Win 10 Enterprise
Version: 1709
OS Build: 16299.431

Error text:
> Failed to install VS Code update. Please download and reinstall VS Code.

> Please attach the following log file to a new issue on GitHub: C:\Users\%HOME%\AppData\Local\Temp\vscode-inno-updater.log

> You might want to try the new Windows User Setup available from version 1.25. You will be redirected to a link which provides more information: https://aka.ms/vscode-update-access-denied

[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2290567/vscode-inno-updater.log)

**Comment by joaomoreno** [comment]
You seem to have #47841.

Please read this comment if you can provide more detail: https://github.com/Microsoft/vscode/issues/47841#issuecomment-393101777

Please read this one to disable background updates: https://github.com/Microsoft/vscode/issues/47841#issuecomment-395017687

Also read this one to provide feedback on our new user setup: https://github.com/Microsoft/vscode/issues/47841#issuecomment-399941682
