### ISSUE TITLE
Badges in Tree View don't work if iconPath is set on tree items

### ISSUE THREAD

**Issue by sebastian-lenz** [Microsoft/vscode#56477]
- VSCode Version: 1.26.0
- OS Version: Windows 10

Steps to Reproduce:

1. Create a `TreeDataProvider`
2. Return tree items in `getTreeItem` that both have a `resourceUri` and `iconPath` set.

With the July update this great feature made it into the release of VS Code: https://github.com/Microsoft/vscode/issues/38426. However, as soon as you set a custom icon on the tree items, the feature breaks and badges are no longer shown.

**Comment by sandy081** [comment]
To verify:

- Clone https://github.com/Microsoft/vscode-extension-samples/tree/master/tree-view-sample
- Open `fileExplorer.ts`
- Add following lines after Line 293
```ts
treeItem.iconPath = {
			light: element.type === vscode.FileType.File ? path.join(__filename, '..', '..', '..', 'resources', 'light', 'document.svg') : path.join(__filename, '..', '..', '..', 'resources', 'light', 'folder.svg'),
			dark: element.type === vscode.FileType.File ? path.join(__filename, '..', '..', '..', 'resources', 'dark', 'document.svg') : path.join(__filename, '..', '..', '..', 'resources', 'dark', 'folder.svg')
		};
```
- `npm install`
- `npm run watch`
- `F5` to start debugging
- Open a folder in that window
- Custom File explorer view replicating the file explorer should be shown in the Explorer
- Verify that you can see badges (Problems, Git) for the files in this view
