### ISSUE TITLE
Garbled text displayed in output panel.

### ISSUE THREAD

**Issue by akq** [Microsoft/vscode#5647]
- VSCode Version: 1.0.0
- OS Version: Windows 10 simplified Chinese
- code page: 936

![image](https://cloud.githubusercontent.com/assets/1907927/14736025/0c652a40-08a7-11e6-9530-bd2ac8966f85.png)

Steps to Reproduce:

1. press F1 
2. input `taskc`
3. select `Grunt `and execute
4. task output window display gabled text. 

![image](https://cloud.githubusercontent.com/assets/1907927/14734900/26cba636-08a0-11e6-9694-057d8f7ec3cf.png)

I switch the locale to zh-CN and restart, but the same still happened. 

![image](https://cloud.githubusercontent.com/assets/1907927/14734979/b7ea9e24-08a0-11e6-84aa-3eab345d617a.png)

I believe it should be caused by the unmatched encoding used in output panel. 

Thanks.

**Comment by dbaeumer** [comment]
Dups: #974 & #3550

**Comment by jmglezgz** [comment]
I cannot find a solution. which is the correct issue?

Thanks,

**Comment by dbaeumer** [comment]
There is no solution right now. It is a bug we need to address.
