### ISSUE TITLE
Split terminal resize does not render correctly 

### ISSUE THREAD

**Issue by MiteshNWT** [Microsoft/vscode#56472]
Issue Type: <b>Bug</b>

When we split terminials and then resize the window , exsisting screen does not render well 

VS Code version: Code - Insiders 1.27.0-insider (ffa660576d3a8da3f6cf9b94cbfb879632688ebd, 2018-08-15T05:19:24.200Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (4.23GB free)|
|Process Argv|C:\Users\mitesh.pandya\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by MiteshNWT** [comment]
![image](https://user-images.githubusercontent.com/5683305/44211967-1d807b00-a138-11e8-9e58-0bff52e1c5b2.png)

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
