### ISSUE TITLE
When searching in loose files, always searches package.json

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#56487]
(Needs fix for https://github.com/Microsoft/vscode/issues/56433)

- Open empty vscode window
- Open Finder window on the vscode repo
- Drag README.md into the vscode window
- Search 'vscode'
- See results from README.md and also package.json, even though I never opened package.json

I guess some extension is creating a model for package.json. Who is wrong here? The extension, the model service, the search service? The search service just looks at

`let models = this.modelService.getModels();`

**Comment by bpasero** [comment]
@roblourens yeah, unhappy. Possibly fixable by checking for each model if it is opened via [`IEditorService.isOpen({ resource })`](https://github.com/Microsoft/vscode/blob/e2b722d26262a2a15c1e9246a6ab40475ea9c5ed/src/vs/workbench/services/editor/common/editorService.ts#L152)

The only downside I can think of is that we would no longer find results in embedded code editors.

**Comment by roblourens** [comment]
What do you mean by embedded code editors here?

**Comment by bpasero** [comment]
@roblourens 

![image](https://user-images.githubusercontent.com/900690/44248854-444cb900-a1ed-11e8-9f4b-d7c9342d0408.png)

**Comment by roblourens** [comment]
I wouldn't expect search to work in those tbh.
