### ISSUE TITLE
Themes | Not able to distinguish the scope for a function parameters used in the function body

### ISSUE THREAD

**Issue by kapalkat** [Microsoft/vscode#56488]
- VSCode Version: 1.26.0
- OS Version: OSX

Steps to Reproduce:
When creating a new color theme for VSC I am not able to distinguish the scope for function parameters used in the function body.
1. Create a function with parameters
2. Use those parameters in a function body

The scope for those parameters in a function body is either:
_variable.other.readwrite.js_
or
_variable.other.object.js_

There is no way to have different colors for the parameter and other read-write, object etc. variables used inside the function. In comparison, I have attached a screenshot of IntelliJ IDE where this is possible (parameter used in a function declaration and in a function body is just: Identifiers→Parameter)

The solution here might be adding an additional scope for parameters used in the function body: the scope could be like _variable.other.parameter.js_

VSC:
![image](https://user-images.githubusercontent.com/26725074/44164588-becee900-a0c6-11e8-85bc-8ae258d761a5.png)

IntelliJ
![image](https://user-images.githubusercontent.com/26725074/44164603-c8f0e780-a0c6-11e8-9f29-e268d65cd522.png)

This would allow us to create more consistent themes!

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by aeschli** [comment]
What you are asking for is not possible with TextMate grammars.
When seeing `productReviewed` there's no possibility to know to what that identifier resolves. Variable, parameter, field, even a type.

What you what can only be done with semantic highlighting.
https://github.com/Microsoft/vscode/issues/585 is the request for that.
