### ISSUE TITLE
Save logpoints / breakpoints in workspace

### ISSUE THREAD

**Issue by gandalfsaxe** [microsoft/vscode#56482]
Logpoints [are presented](https://code.visualstudio.com/docs/editor/debugging#_logpoints) as a smarter substitute for print statements. That may be in a solo project, but what about a collaborative code base? If one substitutes e.g. all Python prints/logs with VSCode logs, then only the person who made them benefit.

How about adding the capability to save logpoints in json format in the .vscode folder of a project? Perhaps even optionally breakpoints too. That would make them much more useful when working collaboratively, and even across multiple devices.

Side question: Where are breakpoint / logpoint information stored right now?

**Comment by isidorn** [comment]
Breakpoints / logpoints are currently stored in the local storage of chrome.
There is already an issue that wants this, you can find it if you search for issues with label debug and feature request

**Comment by GandalfSaxe** [comment]
@isidorn I can't find it. Could you post it here?

**Comment by isidorn** [comment]
It is closed, so we can reopen this one and keep it open as a feature request
https://github.com/Microsoft/vscode/issues/1131

**Comment by acestronautical** [comment]
Considering the number of views on this SO post I think this should be reopened: https://stackoverflow.com/questions/40225461/importing-and-exporting-breakpoints-in-visual-studio-code

**Comment by bogacg** [comment]
I believe this would be a useful addition, please re-open this.

**Comment by isidorn** [comment]
Yes, let's reopen this, it is a fair feature reuqest.

**Comment by isidorn** [comment]
Awesome idea for an extension.

**Comment by bogacg** [comment]
It would be "nicer" to point to API point(s) closing this issue for devs who are willing to write such an extension. 
For those who are reading this in the future and willing: only info related I can find [VS Code API : Breakpoints](https://code.visualstudio.com/api/references/vscode-api#debug.breakpoints) and a [StackOverflow question](https://stackoverflow.com/a/57770111/1539073) where in the answer it's explained better not to touch that db file (from 2019 so maybe even not valid anymore?)

**Comment by roblourens** [comment]
The `debug.breakpoints` and `debug.addBreakpoints` APIs are exactly what you need. You can read breakpoints and write to some file, then restore with addBreakpoints. That SO question probably predates the API.
