### ISSUE TITLE
Extensions Viewlet Search box now has a little inner padding around the text

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode#56489]
Issue Type: <b>Bug</b>

Compared to input boxes in other viewlets, the search box in the extensions viewlets looks slightly different with a little padding of a different color inside the box. 

VS Code version: Code - Insiders 1.27.0-insider (ffa660576d3a8da3f6cf9b94cbfb879632688ebd, 2018-08-15T05:19:24.200Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (7.27GB free)|
|Process Argv|C:\Users\stbatt\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by JacksonKearl** [comment]
This appears to be because the `Material Theme Lighter Higher Contrast` sets the background color to a transparent color (`rgba(0,0,0,0.2)`), if that is changed to `rgb(250,250,250)`, the look is the same but without the border. This seems like incorrect behavior of the renderer, as the type of color shouldn't affect what gets colored.

**Comment by JacksonKearl** [comment]
Actually, looks like the transparency is showing up differently on the different backgrounds. If you increase the alpha, it starts to look like this: 
![image](https://user-images.githubusercontent.com/8586769/44166655-c53a7200-a080-11e8-94d8-182415272f29.png)

I'll look in to making the transparency affect both equally
