### ISSUE TITLE
Source Control Manager: Warn Subject Line Length at 50 characters

### ISSUE THREAD

**Issue by Curdflappers** [Microsoft/vscode#56481]
When using the integrated Source Control pane in the Side Bar to stage a commit, users always receive a warning once they exceed 72 characters ("X characters over 72 in current line").

![screen shot 2018-08-15 at 11 30 28 am](https://user-images.githubusercontent.com/7833360/44159996-a4711d00-a07e-11e8-990e-97ec0bdd0ddc.png)

However, it's generally recommended that the subject line of a commit should be 50 characters or less:
* https://medium.com/@steveamaza/how-to-write-a-proper-git-commit-message-e028865e5791
* https://chris.beams.io/posts/git-commit/#limit-50

There should be an option to toggle a separate warning for the subject line, or, even better, implement a small column count at the bottom of the textbox.

**Comment by mark-wiemer** [comment]
@joaomoreno Unfortunately my issue is a bit different: I'm okay with description being limited to 72 characters per line, but the subject should have a separate configurable limit. Something like `git.subjectValidationLimit` and `git.descriptionValidationLimit` if that makes sense.

Thanks!
