### ISSUE TITLE
Visual Studio Code shuts down when opening a folder

### ISSUE THREAD

**Issue by jumicode** [Microsoft/vscode#56486]
Issue Type: <b>Bug</b>

When attempting to open a folder with File > Open Folder or using the associated keyboard shortcut Visual Studio Code shuts down unexpectedly.

OS: Arch Linux with Deepin Window Manager

Disabling extensions does not fix the problem. Running `code --verbose` produces the following relevant information:

```
windowsService#pickFolderAndOpen
(code:14853): Gtk-WARNING **: 19:57:00.929: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL):
Failed to load /usr/share/icons/deepin/mimetypes/16/image.svg:
Unable to load image-loading module:
/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so:
/opt/visual-studio-code/glibc/usr/lib/libc.so.6:
version `GLIBC_2.28' not found (required by /usr/lib/libxml2.so.2) (gdk-pixbuf-error-quark, 5)
```

The `image.svg` file is a link on my system. Also, I have the `gdk-pixbuf2` and `glibc` packages installed on my system. The issue started occurring in the  1.26.0 update of Visual Studio Code.

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:25:59.521Z)
OS version: Linux x64 4.17.14-arch1-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2328M CPU @ 2.20GHz (4 x 1406)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 1|
|Memory (System)|5.53GB (1.02GB free)|
|Process Argv|/opt/visual-studio-code/code|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.7.1

(2 theme extensions excluded)

</details>

**Comment by ramya-rao-a** [comment]
- Do you see this with extensions disabled? Close all VS Code instances and then run `code --disable-extensions`.
- Did this start happening after the latest release, or you've seen this in version 1.25.1 as well?
- Start VS Code from a terminal in verbose mode `code --verbose`, repro the issue and then share the verbose output from the terminal

**Comment by jumicode** [comment]
@ramya-rao-a Thank you for providing the steps. I have edited the issue to include the output of running in verbose mode.

**Comment by BobbyBabes** [comment]
From the author of that package :
> glibc 2.28-1 is problematic, it breaks electron apps. That's why I have included 2.27 in the PKGBUILD. Either wait for 2.28-4 to hit [core] (which reverts the problematic bits) or use this package with an update system, which should work fine. See previous comments for details.

Let's make Electron and glibc fight it out. We're sitting ringside.

**Comment by eli-schwartz** [comment]
The developers of both electron and glibc agree that it is electron's fault, and the electron developers are working to produce new electron 2 binaries. This isn't even slightly ambiguous.

I am merely pointing out that 1) your description is incorrectly assigning blame, 2) this will be fixed by the publication of a new electron version, not by assuming that some-but-not-all Linux distributions will apply **temporary hacks** to glibc.a

**Comment by BobbyBabes** [comment]
Oh dear!

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/55934
