### ISSUE TITLE
Go-to-definition IntelliSense F12 binding not working

### ISSUE THREAD

**Issue by arkuhn** [Microsoft/vscode#56490]
**Bug:**
Right clicking a function and selecting 'Go To Definition' works, however, using the F12 binding displays 'No Definition Found.' There are a number of open and closed issues surrounding IntelliSense go-to-function not working. None of them (that I saw) exhibited the same behavior. Closing and reopening does not fix the issue. I do see a peek definition of the function while hovering it.

**Info:**
Version: 1.26.0
Commit: 4e9361845dc28659923a300945f84731393e210d
Date: 2018-08-13T16:25:59.521Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
OS: Ubuntu 16.04

**Steps to Reproduce:**
1. Open the following snippit:
```
const hello = () => {
    console.log('Hello world');
};

hello();
```
2. Press F12 while hovering 'hello()'

Does this issue occur when all extensions are disabled? **Yes**

**Comment by mjbvz** [comment]
@arkuhn Where is the cursor when you press f12? Is it on `hello()` or are you just hovering over `hello()`?

@ramesh-cs Open a separate issue with example code
