### ISSUE TITLE
Add split terminal to Extensions API

### ISSUE THREAD

**Issue by MichaelSimmonds** [Microsoft/vscode#56495]
[done]

Currently there is no (documented) way to split a terminal window in the extension api.

My use case is that I would like to create a small extension that open 3 split terminals to show the server, frontend server and tests side by side

Thanks to everyone supporting this project - I'm really enjoying using the editor all day every day!

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/45407
