### ISSUE TITLE
Ctrl-Shift-e not working anymore

### ISSUE THREAD

**Issue by bkinsey808** [Microsoft/vscode#56492]
- VSCode Version: 1.26
- OS Version: Ubuntu 18.04.1 LTS

Steps to Reproduce:

1. recently updated vscode to 1.26
2. tried the breadcrumb feature

Does this issue occur when all extensions are disabled?: Yes/No

Now ctrl-shift-e no longer opens up the explorer side panel like it used to.

**Comment by sabrehagen** [comment]
@ramya-rao-a I believe this is a different issue to #48480 and should be reopened. I am experiencing this too, and it started happening long after the other issue was raised.

**Comment by ramya-rao-a** [comment]
@sabrehagen What OS are you on?

**Comment by sabrehagen** [comment]
Kubuntu 18

**Comment by ramya-rao-a** [comment]
Then it is the same issue as https://github.com/Microsoft/vscode/issues/48480

Yes, this issue was logged long before when we were investigating using electron 2.0

We only released electron 2.0 in VS Code 1.25. So that is when you would have see it.

**Comment by sabrehagen** [comment]
Thank you for the investigation and clarification Ramya.
