### ISSUE TITLE
New Settings GUI broken.

### ISSUE THREAD

**Issue by NeuralNeurosis** [Microsoft/vscode#56499]
I was trying to look through the settings menu and the new settings GUI crashed out.

- VSCode Version:
Version: 1.27.0-insider
Commit: ffa660576d3a8da3f6cf9b94cbfb879632688ebd
Date: 2018-08-15T05:19:24.200Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
- OS Version:
Win 10 latest update

Steps to Reproduce:

1.Open Settings
2.Go to Workbench
3.Go to Color Customizations 'Edit in settings.json'
3.1 This appeared 
![visual_code_insider_settings](https://user-images.githubusercontent.com/15053187/44169104-705b2380-a0a1-11e8-8fe9-26d9e741c0f7.PNG)
4. Now I can't do anything in the settings.

Thanks.

Does this issue occur when all extensions are disabled?: Yes/No
I have no extensions installed.

**Comment by beastdestroyer** [comment]
Damn... Also try using Developer Tools (Help > Toggle Developer Tools) and see if all that random junk are actually just extra pointless elements. If not... wow, I've never seen madness like this

**Comment by NeuralNeurosis** [comment]
It must have been a one off kinda thing because now I  can get into the settings again and can't reproduce it. Thanks for checking it out.

**Comment by nealot** [comment]
Forget about opening an issue; you should visit a computer exorcist.

**Comment by keiyunwong** [comment]
Just click the red rectangle area, then the list is huddling. I'm quite sure it is not something occasional.
![image](https://user-images.githubusercontent.com/28135009/44220877-6aa13300-a1b2-11e8-881f-46554ddde019.png)

![image](https://user-images.githubusercontent.com/28135009/44220892-742a9b00-a1b2-11e8-9d8c-9590ae21f791.png)
