### ISSUE TITLE
Provide auto completions scripts for common/popular shells

### ISSUE THREAD

**Issue by segevfiner** [Microsoft/vscode#56497]
It would be useful if VS Code provides an auto completion script, for the `code` command, for the commonly used/popular shells, such as Zsh, Bash, Fish, Powershell, etc.

There is already one bundled in Zsh in newer versions: [Zsh/Completion/X/Command/_code](https://github.com/zsh-users/zsh/blob/master/Completion/X/Command/_code). But VS Code can bundle it's own more complete and up-to-date version. Which will also be available for users of older Zsh versions.

All scripts should be bundled with all the various kinds of installers for all supported operating systems. What with people using Unix shells on Windows, via various means, and Powershell 6 being cross-platform. They should be installed/symlinked automatically to the correct location when it makes sense, depending on the platform and installation method.

**Comment by joaomoreno** [comment]
Would you like to contribute this in a PR?

**Comment by segevfiner** [comment]
P.S. You tagged this linux/mac but powershell is also for Windows.

**Comment by joaomoreno** [comment]
Closing per https://github.com/Microsoft/vscode/pull/56670
