### ISSUE TITLE
Document how to use VSCode as a platform for applications

### ISSUE THREAD

**Issue by firelizzard18** [Microsoft/vscode#56505]
SQL Operations Studio uses VSCode's source as an application platform. Please document how this can be done.

Specifically, I want to create a terminal/console/server-management application that utilizes VSCode as an application platform. VSCode is amazing, but often times, instead of one of my projects, I just want terminals and a list of servers I can SSH to.

**Comment by Tyriar** [comment]
VS Code is not a platform, you will have a lot of difficulty building on it as we don't provide a stable API outside of the extension API.
