### ISSUE TITLE
Unable to launch VS Code

### ISSUE THREAD

**Issue by silkfire** [Microsoft/vscode#56503]
- VSCode Version: 1.26
- OS Version: Windows 10 Home 1803

Steps to Reproduce:

1. Run VS Code from command line
2. Should launch  the application but getting error instead

Does this issue occur when all extensions are disabled?: Yes/No
Yes

As of version 1.26 I'm unable to run the application.
When launching it from the taskbar, nothing happens.
When running it from the CLI, the following error is returned:

```
Fatal error in c:\users\elecsa\buildagent\workspace\358518\src\v8\src\snapshot\snapshot.h, line 28
Check failed: IsSane().
```

![image](https://user-images.githubusercontent.com/1554615/44172268-f21c7280-a0dc-11e8-982a-be1203ffad94.png)

What figures?

**Comment by ramya-rao-a** [comment]
Can you run `code --verbose` and share the output?

**Comment by silkfire** [comment]
@ramya-rao-a I'm getting the same output. Running `code` takes me directly to the error, regardless of any flags appended to it.

**Comment by ramya-rao-a** [comment]
Can you follow https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues and share more information about the crash?

**Comment by Tyriar** [comment]
@jrieken are we doing anything with snapshots currently?

**Comment by bpasero** [comment]
@silkfire 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by jrieken** [comment]
re 
https://github.com/Microsoft/vscode/issues/56503#issuecomment-413350132. Nope, nothing with snapshots. Can then still be an issue with the default snapshots V8 contains.

**Comment by silkfire** [comment]
I think I might have solved it. After updating to 1.26 (from within the app), there's actually two copies of VS Code installed on the system: 1.25.1 and 1.26.

I removed both from 'Uninstall or change a program' and reinstalled 1.26. Now it seems to be working. I think 1.26 was also called 'Microsoft Visual Studio Code (User)' for some reason in the list, but it doesn't after I reinstalled it.

**Comment by bpasero** [comment]
OK thanks, closing then.

/cc @joaomoreno on https://github.com/Microsoft/vscode/issues/56503#issuecomment-413479454
