### ISSUE TITLE
Visual studio code considers file paths in lower case only when performing an operation

### ISSUE THREAD

**Issue by shake82** [Microsoft/vscode#56508]
- VSCode Version: 1.26.0
- OS Version: Windows 10 (Version 1703)

Steps to Reproduce:
1. Make sure that you have a file in the opened folder that has capital letters in its path (e.g. app\Core\Services\test.service.ts)
2. Perform search with key words that present in the file. The search results show the file twice
![image](https://user-images.githubusercontent.com/3976897/44176100-78718e00-a0b6-11e8-9293-de3192eb56d5.png)

Similarly if you ask VSCode to perform a refractory action (like add a new property automatically in a Typescript class), it opens the file again with lower case path with the new change
![image](https://user-images.githubusercontent.com/3976897/44176188-d9996180-a0b6-11e8-8298-d4a85f88f1a8.png)

**Does this issue occur when all extensions are disabled?:** [Yes]

**Comment by roblourens** [comment]
This is covered by the (large) https://github.com/Microsoft/vscode/issues/12448
