### ISSUE TITLE
Outline / Breadcrumbs broken for largeish Python files

### ISSUE THREAD

**Issue by tigerhawkvok** [Microsoft/vscode#56502]
- VSCode Version: 1.26
- OS Version: Windows 10 v1709 (Build 162.99547)

Steps to Reproduce:

1. Open a big-ish Python file. The one in the screenshot is 158kb

![image](https://user-images.githubusercontent.com/165937/44170657-ddb08980-a08c-11e8-826a-74e3c2cb78e6.png)

I also opened a Tensorflow example which failed to provide symbols

![image](https://user-images.githubusercontent.com/165937/44170919-a8f10200-a08d-11e8-9bad-f5f835cc6394.png)

Breadcrumb symbol navigation should be shown, and the outline should show available symbols. This worked in 1.25

Breadcrumbs and outline work as expected in the same folder and window for smaller files ( ~14kb)

![image](https://user-images.githubusercontent.com/165937/44171236-99be8400-a08e-11e8-9013-409ef5cfe9df.png)

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by ramya-rao-a** [comment]
I see that you have logged a similar issue in the repo for the python extension. https://github.com/Microsoft/vscode-python/issues/2399

Please follow up there. If it is determined there that this is an issue with VS Code and not the extension, we can re-open this one.
