### ISSUE TITLE
Fuzzy matching in command palette doesn't match words in ()

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#56507]
- In command palette, search "settings json"
- It should match "Open Settings (JSON)" but doesn't, unless you type `(json`
- Same for other commands like `Git: Pull (Rebase)`

**Comment by roblourens** [comment]
Also skip punctuation here?

https://github.com/Microsoft/vscode/blob/cb5558b99d633fb775b2ac0e56f7b7304ce3cff9/src/vs/base/common/filters.ts#L312

**Comment by bpasero** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/27636
