### ISSUE TITLE
Workbench should provide language agnostic actions to apply all quick fixes to a file

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#5650]
- VSCode Version: 1.0.0
- OS Version:

Instead of extensions and language servers providing their own language specific actions the workbench should provide actions to apply all available quick fixes to a file. I think that this is even possible with the extension API today since we can ask for all code actions for a given range.

See https://github.com/Microsoft/vscode-eslint/issues/70.

**Comment by jrieken** [comment]
I think we should do that in the quick fix UI. When there is more than one action we should offer _Apply all_

**Comment by dbaeumer** [comment]
ESLint does exactly what you recommend. The use case for an action / command is to bind it to a short cut. Easier to trigger then setting a cursor on a problem, clicking the light bulb, .... I doubt that a lot of devs do F1 > .....

**Comment by jrieken** [comment]
stretch for april, tho rain on sunday

**Comment by dbaeumer** [comment]
Rain on Saturday and snow on Sunday :-)

**Comment by jrieken** [comment]
Saturday is this: http://www.redbull.com/us/en/bike/events/1331753879682/uci-mtb-world-cup-2016-round-2-cairns-australia

**Comment by dbaeumer** [comment]
Accepted :-)

**Comment by jrieken** [comment]
to clarify: we want a command that fetches and applies all code actions UI-less? not another entry in the code action UI, correct?

**Comment by jrieken** [comment]
Actually this isn't simple. The problem is that our `CodeActions` are just commands, not necessarily text edits. That mean we cannot run them all at once we because the change on which they have been computed might be different already. We have to do this:

1. ask for all code actions
2. run the first code actions
3. if there is another code action, repeat at #1

**Comment by dbaeumer** [comment]
OK. See the problem. And we can't hook an handler for a language either since there can be more than one 'quick fix' provider per language. May be having a command 'ELint - fix all problems' is not a bad idea afterall.

**Comment by jrieken** [comment]
No action planned because there are challenges as outlined above

**Comment by dbaeumer** [comment]
Agree :-)
