### ISSUE TITLE
[html] Not getting suggestions for style attribute

### ISSUE THREAD

**Issue by dev-sandeep** [Microsoft/vscode#5651]
- VSCode Version:
- OS Version:

Steps to Reproduce:

Am not getting suggestion for css class. Also there should be a way to the code snippets from one to other when am comparing 2 files

**Comment by dbaeumer** [comment]
@jrieken not sure if you or Marin owns CSS.

**Comment by aeschli** [comment]
Is the CSS embedded in HTML?
Can you paste the code and show where request suggestions?

**Comment by dev-sandeep** [comment]
no its a separate file/external file
here is the hierarchy:

app
|_ css
      |_ style.css
|_html
      |_ index.html
      |_ app.html

so, in index.html i've included the css file , but in app.html am not getting any suggestion for css classes.

**Comment by aeschli** [comment]
Ah, it's about completion in HTML for the class attribute?
That we don't support that.
Marking as duplicate of #1005
