### ISSUE TITLE
[SCSS] Syntax highlighting of @function

### ISSUE THREAD

**Issue by ventrebleu** [Microsoft/vscode#56513]
- VSCode   ##Version:  Version 1.26.0 (1.26.0)
- OS Version: MacOS 10.12.6

Apparently, VS Code doesn't support syntax highlighting for `@function` or `@return`
 in SCSS.

**Comment by aeschli** [comment]
![image](https://user-images.githubusercontent.com/6461412/44212217-0f981d80-a16b-11e8-94ac-47d11c837e77.png)

Works for me. Can you give more details?

**Comment by ventrebleu** [comment]
@aeschli Thanks for your reactivity!

I did a bit more research and it appears to be that here:
<img width="850" alt="vscode-scss" src="https://user-images.githubusercontent.com/2122637/44217019-4bab8e00-a12b-11e8-8b09-41871212f51c.png">

It's the `@error` line that causes the problem: if I had a `;` everything is back to normal.
Intended behavior?

Thanks again,

**Comment by aeschli** [comment]
This issue was moved to atom/language-sass#255
