### ISSUE TITLE
[html]  html attibute double quotation marks can not auto close

### ISSUE THREAD

**Issue by wusfen** [Microsoft/vscode#56529]
Issue Type: <b>Bug</b>

```html
<div $1 $2>
```
当在$2位置书写属性时（就是紧贴">"时），双引号不会自动关闭
```html
<div class="" title=">
```

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 10.0.17134

**Comment by sandy081** [comment]
@octref Can you please help me in understanding the issue? Thanks.

**Comment by wusfen** [comment]
enen...

When I write html attribute on `<div $1 $2>` $2 site, the double quotation marks can not auto close...

3q~

**Comment by wusfen** [comment]
@sandy081 sory, can you understand what I say?

**Comment by KamasamaK** [comment]
If I understand this correctly, this should be fixed in v1.27 with new [auto closing functionality](https://code.visualstudio.com/updates/v1_27#_auto-closing-surrounding-characters).

**Comment by rebornix** [comment]
@KamasamaK thanks, auto closing always should fix this issue.
