### ISSUE TITLE
VScode not open a network share as workspace

### ISSUE THREAD

**Issue by joaloez** [Microsoft/vscode#5652]
- VSCode Version: 1.0.0
- OS Version: Win7 Service Pack1

Steps to Reproduce:
1. Open directory as network location type \\fileapp\Share\wwwDev02\www\
2. VSCode it hangs

**Comment by bpasero** [comment]
@joaloez what hangs exactly? can you provide more information on the setup?

**Comment by joaloez** [comment]
Step 1: 
![1](https://cloud.githubusercontent.com/assets/18613356/14741813/441514fe-0899-11e6-81d6-b1ad949385a6.PNG)

Step 2: 
It does nothing and disappears from the menu on the left

![2](https://cloud.githubusercontent.com/assets/18613356/14741729/a6c06e74-0898-11e6-8394-166164637d56.PNG)

**Comment by bpasero** [comment]
@joaloez could it be that this share is very slow in general? does vs code show up eventually? if yes, can you do this:
* when it is loaded, open developer tools from the help menu
* click on the "Profiles" tab
* click on "Collect JavaScript CPU profile"
* F1 > Reload Window
* when this is fully loaded click on "Stop"
* Save the profile and attach it here or send me on benjpas@microsoft.com

Thanks!

**Comment by joaloez** [comment]
I sent to your email the log.
I've been waiting five minutes and not the directory opened
Thanks

**Comment by bpasero** [comment]
Thanks. I fear there is not much we can do if file system operations are taking so long. We might be able to let the UI look better but after all if the network share does not respond fast, the experience will not be good with any tool out there.

**Comment by bpasero** [comment]
@joaloez when you open this share with the windows explorer, is it any faster?

**Comment by joaloez** [comment]
if I open it with Windows Explorer is immediate.
Also if I make a network drive is immediate.
Only happens slowly opening direction from the vscode

**Comment by joaloez** [comment]
I open developer tools and I found in the tab console this error:
![captura](https://cloud.githubusercontent.com/assets/18613356/14776177/f2e6c748-0ac4-11e6-945b-0e692906d4e9.PNG)

**Comment by bpasero** [comment]
@joaloez very good idea to check the console, so this seems to indicate that VS Code fails to resolve the workspace you want it to open with. 

Do you have sufficient permissions to access '\\fileapp\Share\wwwDev02'? Would you be able to try a little node.js script out on this share for me? Would be interesting to reproduce this with a little snippet.

**Comment by joaloez** [comment]
My project is in '\\fileapp\Share\wwwDev02\www\tmk\' and this is the netwok share that I open.
I don't know why VS Code fail in '\\fileapp\Share\wwwDev02' (I don't have sufficient permissions) and not grabs the entire directory.
I can ask at TI to try your node.js. Tell me what to do.

**Comment by bpasero** [comment]
Ok good, would be interesting if something changes between node.js 4.1.1 and node.js 5.10.0 (our latest use), so maybe you could try with both versions:
* run node from the command line
* type `require("fs").statSync("\\fileapp\\Share\\wwwDev02")`
* send me the output

Second try:
* run node from the command line
* type `require("fs").lstatSync("\\fileapp\\Share\\wwwDev02")`
* send me the output

**Comment by joaloez** [comment]
![node_v4 1 1](https://cloud.githubusercontent.com/assets/18613356/14778292/71dbda9a-0ad2-11e6-8999-03e4e429ed61.PNG)

![node_v5 10 0](https://cloud.githubusercontent.com/assets/18613356/14778299/78453ac0-0ad2-11e6-9806-2e7867d91bf5.PNG)

**Comment by bpasero** [comment]
@joaloez sorry you are right, please try with "\\\\fileapp\\Share\\wwwDev02"

**Comment by joaloez** [comment]
I tested each command with routes
"\\\\fileapp\\Share\\wwwDev02"
"\\\\fileapp\\Share\\wwwDev02\\www\\tmk"

node_v4.1.1
> require("fs").statSync("\\\\fileapp\\Share\\wwwDev02")
Error: EPERM: operation not permitted, stat '\\fileapp\Share\wwwDev02'
    at Error (native)
    at Object.fs.statSync (fs.js:849:18)
    at repl:1:15
    at REPLServer.defaultEval (repl.js:164:27)
    at bound (domain.js:250:14)
    at REPLServer.runBound [as eval] (domain.js:263:12)
    at REPLServer.<anonymous> (repl.js:393:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:210:10)
>
>
>
> require("fs").statSync("\\\\fileapp\\Share\\wwwDev02\\www\\tmk")
{ dev: 60,
  mode: 16822,
  nlink: 1,
  uid: 0,
  gid: 0,
  rdev: 0,
  blksize: undefined,
  ino: 6292509357911562000,
  size: 0,
  blocks: undefined,
  atime: Mon Apr 25 2016 12:53:34 GMT+0200 (Hora de verano romance),
  mtime: Thu Apr 21 2016 18:05:16 GMT+0200 (Hora de verano romance),
  ctime: Thu Apr 21 2016 18:05:16 GMT+0200 (Hora de verano romance),
  birthtime: Mon Feb 29 2016 17:04:56 GMT+0100 (Hora estándar romance) }
>
>
>
> require("fs").lstatSync("\\\\fileapp\\Share\\wwwDev02")
Error: EPERM: operation not permitted, lstat '\\fileapp\Share\wwwDev02'
    at Error (native)
    at Object.fs.lstatSync (fs.js:844:18)
    at repl:1:15
    at REPLServer.defaultEval (repl.js:164:27)
    at bound (domain.js:250:14)
    at REPLServer.runBound [as eval] (domain.js:263:12)
    at REPLServer.<anonymous> (repl.js:393:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:210:10)
>
>
>
> require("fs").lstatSync("\\\\fileapp\\Share\\wwwDev02\\www\\tmk")
{ dev: 60,
  mode: 16822,
  nlink: 1,
  uid: 0,
  gid: 0,
  rdev: 0,
  blksize: undefined,
  ino: 6292509357911562000,
  size: 0,
  blocks: undefined,
  atime: Mon Apr 25 2016 12:53:34 GMT+0200 (Hora de verano romance),
  mtime: Thu Apr 21 2016 18:05:16 GMT+0200 (Hora de verano romance),
  ctime: Thu Apr 21 2016 18:05:16 GMT+0200 (Hora de verano romance),
  birthtime: Mon Feb 29 2016 17:04:56 GMT+0100 (Hora estándar romance) }
>



node_v5.10.0
> require("fs").statSync("\\\\fileapp\\Share\\wwwDev02")
Error: EPERM: operation not permitted, stat '\\fileapp\Share\wwwDev02'
    at Error (native)
    at Object.fs.statSync (fs.js:892:18)
    at repl:1:15
    at REPLServer.defaultEval (repl.js:269:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:439:12)
    at emitOne (events.js:95:20)
    at REPLServer.emit (events.js:182:7)
    at REPLServer.Interface._onLine (readline.js:211:10)
>
>
>
> require("fs").statSync("\\\\fileapp\\Share\\wwwDev02\\www\\tmk")
{ dev: 60,
  mode: 16822,
  nlink: 1,
  uid: 0,
  gid: 0,
  rdev: 0,
  blksize: undefined,
  ino: 6292509357911562000,
  size: 0,
  blocks: undefined,
  atime: Mon Apr 25 2016 12:56:14 GMT+0200 (Hora de verano romance),
  mtime: Thu Apr 21 2016 18:05:16 GMT+0200 (Hora de verano romance),
  ctime: Thu Apr 21 2016 18:05:16 GMT+0200 (Hora de verano romance),
  birthtime: Mon Feb 29 2016 17:04:56 GMT+0100 (Hora estándar romance) }
>
>
>
> require("fs").lstatSync("\\\\fileapp\\Share\\wwwDev02")
Error: EPERM: operation not permitted, lstat '\\fileapp\Share\wwwDev02'
    at Error (native)
    at Object.fs.lstatSync (fs.js:887:18)
    at repl:1:15
    at REPLServer.defaultEval (repl.js:269:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:439:12)
    at emitOne (events.js:95:20)
    at REPLServer.emit (events.js:182:7)
    at REPLServer.Interface._onLine (readline.js:211:10)
>
>
>
> require("fs").lstatSync("\\\\fileapp\\Share\\wwwDev02\\www\\tmk")
{ dev: 60,
  mode: 16822,
  nlink: 1,
  uid: 0,
  gid: 0,
  rdev: 0,
  blksize: undefined,
  ino: 6292509357911562000,
  size: 0,
  blocks: undefined,
  atime: Mon Apr 25 2016 12:56:14 GMT+0200 (Hora de verano romance),
  mtime: Thu Apr 21 2016 18:05:16 GMT+0200 (Hora de verano romance),
  ctime: Thu Apr 21 2016 18:05:16 GMT+0200 (Hora de verano romance),
  birthtime: Mon Feb 29 2016 17:04:56 GMT+0100 (Hora estándar romance) }
>

**Comment by bpasero** [comment]
@joaloez so does it work if you try to open \\fileapp\Share\wwwDev02\www\tmk in vscode and not \\fileapp\Share\wwwDev02\www?

**Comment by joaloez** [comment]
In VS Code the directory I have always tried to open has been "\\\\fileapp\\Share\\wwwDev02\\www\\tmk" but in the error VS Code only takes "\\\\fileapp\\Share\\wwwDev02"

**Comment by bpasero** [comment]
@joaloez weird, out of curiosity when you try to open a folder even below \\fileapp\Share\wwwDev02\www\tmk, would that work?

Btw would you be able to run VS Code out of its sources as outlined here: https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source

**Comment by joaloez** [comment]
In other source, for example "\\fileapp\share.wwwdev01\apache.www\www.bpo\" I don't have any problem. I will ask TI difference between these servers

**Comment by joaloez** [comment]
Finally the problem was on the server configuration. He has to have active permission "through folders"

**Comment by bpasero** [comment]
Ok, closing then.
