### ISSUE TITLE
DiagnosticCollection not working properly

### ISSUE THREAD

**Issue by daishi4u** [Microsoft/vscode#56528]
I work on a vscode extension and use a DiagnosticCollection to show syntax errors alongside another extension that shows errors for the same language. I make sure I don't duplicate the existing errors when pushing my my DiagnosticCollection. When I delete the diagnostics from the collection everything works as expected and I remove my diagnostics after the other extension. However, when another syntax error is encountered and the other extension updates their diagnostics then not all the problems will show. For example, the pane will say I have 5 problems, but there are only two listed with the diagnostic messages. This worked fine in vscode v1.25.1 and below. Thanks.

**Comment by JorneVL** [comment]
This is the same issue as #56317 so far as I know.

**Comment by jrieken** [comment]
@daishi4u Can you check #56317 if this is a duplicate. Are you seeing this with C#? Iff not, do you have a sample that allows us to reproduce.

**Comment by daishi4u** [comment]
No, I'm not using C#. It is actually occurring with apex using the Salesforce apex language server extension and ForceCode (which is the extension I work on). I will paste an example a little later tonight, but if you have a class with a method in it and you leave out one of the curly braces on a method then the Salesforce extension will show 5 problems. Then when you save the class and the ForceCode extension lists additional problems then everything will still be fine. Now if you fix the problem by putting the curly brace in, all but the ForceCode problems will disappear until you save the class then they all disappear. Finally, to get reproduce the issue simply remove the curly brace again and the problems panel will show only 2 issues this time. If you save with the 2 problems showing then it gets really screwy and shows some problems out of place and off to the side.

Like I said I will share a code example a little later tonight and I will also provide a screenshot.

**Comment by daishi4u** [comment]
Also, looking at the other issue, it is similar, but it doesn't flicker like people are saying on that issue. Thanks

**Comment by jrieken** [comment]
Ok, please share the sample and steps

**Comment by daishi4u** [comment]
Sorry, my internet was down last night so I didn't get around to it, but as an update this issue seems to have been fixed with vscode v1.26.1
