### ISSUE TITLE
Allow to move an editor instead of duplicating it when splitting editor

### ISSUE THREAD

**Issue by ignatiusreza** [Microsoft/vscode#56520]
First of all, thanks a lot for adding the support for grid layout! :tada: 

For the feature request, it would be fantastic if we can configure the behavior of what to do with the active tab when using `Split (Up|Down|Left|Right)`.. currently, the behavior is to `duplicate` it into the new editor group.. it would be nice if we can configure it to `move` the active tab..

For an example of similar art, check on how [pain-split](https://atom.io/packages/pain-split) provide support to:

- split creating empty pane (group)
- split moving current tab
- split duplicating curent tab

**Comment by bpasero** [comment]
@ignatiusreza there are commands to move an editor instead of splitting it, is that enough?

**Comment by ignatiusreza** [comment]
i'm sorry, just noticed that moving will create the split if it's missing.. i just need to assign some shortcut to `moveEditorTo(Above|Below|Left|Right)Group`.. this is perfect..

thanks @bpasero! and once again, sorry for the noise..
