### ISSUE TITLE
collapse/expand button vanish when "find & replace" affects code inside and outside code collapsed code block

### ISSUE THREAD

**Issue by davalapar** [Microsoft/vscode#56527]
- VSCode Version: 1.25.1
- OS Version: Windows 7 x64

#### Steps to Reproduce:

1. Collapse a code block / region
2. Use find & replace **that affect lines INSIDE and OUTSIDE** that code block
3. Boom it's gone (the collapse / expand buttons); time to restart vscode.

#### Context note:

I was replacing `Boolean(member)` with `isEmpty(member)` using Find & Replace (CTRL+H).

#### Screenshots

https://i.imgur.com/zei8Ioi.png (bug, before restart)
https://i.imgur.com/rmuVgYN.png (code block collapsed, after restart)
https://i.imgur.com/j6Y8xSW.png (code block expanded, after restart)

Note that at screenshot # 1, the code also appeared to be mangled - but when I restarted it ended up looking fine (shown in screenshots # 2 & # 3).

In screenshot # 3, you'll see that there is also `isEmpty(member)` shown, meaning there was a line affected by Find & Replace inside the collapsed code block shown at screenshot # 1 and # 2.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
@aeschli What happens to folding ranges if the language server goes bad ?

**Comment by davalapar** [comment]
Just an update.. I tried it again but it appears to only happen occasionally - sometimes it happens, sometimes it doesn't. The only extension I have is ESLint.

My gut tells me it has something to do with the red / green / blue git bars appearing on the left hand side, because earlier I can still hover those red / green / blue bars and be able click them to see the preview of the changes, but the expand/collapse button wasn't visible anymore.

**Comment by aeschli** [comment]
@davalapar I'm not able to reproduce. Can you please attach a small code sample with the steps that cause the bug?

**Comment by davalapar** [comment]
Haven't came to the exact steps or scenario to this issue. Closing for now.
