### ISSUE TITLE
Copying text from the Output panel copies invisible characters too

### ISSUE THREAD

**Issue by garyking** [Microsoft/vscode#56533]
- VSCode Version: Version 1.26.0 (1.26.0)
- OS Version: 10.13.5 (17F77)

Steps to Reproduce:

1. Have some output in the Output panel.
2. Copy it, including the end of the line.
3. The copied text, when pasted in VSC, will have invisible chars at the end of the line. You can test this by deleting the invisible chars. There are about 3 at the end of each line.

These chars should be stripped when copying the text. According to [this site](https://www.soscisurvey.de/tools/view-chars.php), the invisible chars are **U+200B**.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
May I know from which channel in Output panel are you copying?

**Comment by garyking** [comment]
Yes, I'm using [Quokka](https://marketplace.visualstudio.com/items?itemName=WallabyJs.quokka-vscode). I was using it on an untitled file, typed some code, outputted a large array to the console, so that I could copy the result from the Output panel. 

I pasted the result into a JS file, and encountered a ton of errors, since it was confused with the hidden chars.

**Comment by sandy081** [comment]
@garyking Quokka extension contributes data to this output channel and it is also adding these invisible characters. Hence they are copied.

Please file an issue against Quokka extension.
