### ISSUE TITLE
Project Manager fully integrated

### ISSUE THREAD

**Issue by muuvmuuv** [Microsoft/vscode#56536]
I know that there is an extension for this, but I think a project Manager would be really useful for everyone and better if it starts on startup with VSCode. I have to wait ~7 sec until I can open the project manager extension.
When you have a look at Web/PHPStorm, they have a nice overview on the start (can be a pop-over box) where all projects are listed. This would be very useful for people that are working on many different projects. So they could easily and faster switch between them.

Here is the extension many people are using daily (like me): https://github.com/alefragnani/vscode-project-manager

**Comment by sandy081** [comment]
Average VS Code start up time is around 2s. Please check with the project manager extension to know why it is slow.

There are no plans to integrate project manager in VS Code.

**Comment by muuvmuuv** [comment]
What about an API to give this extension the ability to great a popover layout that displays recent and saved projects on startup plus sort options for categories or tags?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sandy081** [comment]
There is a view API where you can build the views you want
