### ISSUE TITLE
Installer fails with `Cannot create a stable key under volatile parent HKCU`

### ISSUE THREAD

**Issue by adityaka** [microsoft/vscode#56537]
Issue Type: <b>Bug</b>

Error Message : Cannot create a stable key under volatile parent HKCU

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 10.0.16299

<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.17.7
debugger-for-chrome|msj|4.8.2

</details>

**Comment by sn0wcat** [comment]
+ 1 , same effect. I had the global setup installed before, uninstalled it via add/remove programs and installed vscode for local user.

**Comment by sn0wcat** [comment]
![image](https://user-images.githubusercontent.com/1426617/44397163-99ffc900-a53f-11e8-897a-f22f3758d224.png)

**Comment by adityaka** [comment]
Once you install vscode with the global installer there is a recommendation to use the user install setup and  this is an annoyance since once you install it via the global setup and uninstall and re-install on a windows 10 system physical or virtual it fails.  I don't think it's system specific I have tried it on two different environment with the same effect.

**Comment by joaomoreno** [comment]
Unfortunately, I've run those exact same steps many times and never saw the error.

**Comment by joelstransky** [comment]
Same issue, tried multiple times, re-downloaded the installer multiple times. Tried on a fresh restart. I suspect it has something to do with how I.T. is managing their machines.

**Comment by joelstransky** [comment]
Any tips on how I can get the annoying modal in vscode to stop coming back?

**Comment by joelstransky** [comment]
The message that keeps coming up in vscode that says I should upgrade.

**Comment by joelstransky** [comment]
This is the message modal that keeps coming back.
![image](https://user-images.githubusercontent.com/200472/45051612-6d68a880-b039-11e8-9903-38baa92801a2.png)

**Comment by joaomoreno** [comment]
@joelstransky Click the gear, then "Never Show Again".

**Comment by paul-mcgrath** [comment]
Just experienced this today on a freshly-installed copy of Windows 10. 

Mashed retry/ignore until it finished the installation, but I would imagine that this is not the recommended workaround.

**Comment by johnduffynh** [comment]
Running the system installer worked for me.  That would create the registry keys under HKEY_LOCAL_MACHINE vs. HKEY_CURRENT_USER.  
RegEdt32.exe also would not create the key under HKEY_CURRENT_USER/.../Applications.  I believe the Applications folder on my machine is setup up as volatile.  Rebuilding that should work.

Also, turning off automatic updates will stop the annoying message.

**Comment by joshvorves** [comment]
> Just experienced this today on a freshly-installed copy of Windows 10.
> 
> Mashed retry/ignore until it finished the installation, but I would imagine that this is not the recommended workaround.

This worked for me! So far have noticed no ill effects

**Comment by jaalsuca** [comment]
I have installed the System Installer and works perfectly. In the beginning I had exactly the same problem but I noticed that you talked about UserInstaller then I tested with System Installer and works!
https://code.visualstudio.com/Download#
