### ISSUE TITLE
Double click does not honor editor.wordSeparators [1.26.0]

### ISSUE THREAD

**Issue by McNuggetSauce** [Microsoft/vscode#56535]
Issue Type: <b>Bug</b>

I removed "$" from the character list in editor.wordSeparators so that when double clicking on a variable with a "$" e.g. `$dependency` it selects the entire variable including the $ character. This is not the case when I updated to 1.26.0. Double clicking only highlights just the word.

Pressing CTRL + D however selects the entire variable just fine.

Here is the current value in the user settings:

> "editor.wordSeparators": "`~!@#%^&*()-=+[{]}\\|;:'\",.<>/?",

I've reloaded with extensions disabled and changes to the word separator setting still doesn't have an effect.

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 6.1.7601

**Comment by alexandrudima** [comment]
@McNuggetSauce I cannot reproduce. When I remove `$` from the word separators list, `$` is considered a word character:

![kapture 2018-08-17 at 18 01 55](https://user-images.githubusercontent.com/5047891/44276425-aa662a00-a247-11e8-954c-6f58127afd65.gif)

**Comment by alexandrudima** [comment]
@sandy081 can answer all the intricacies of how settings work.

**Comment by sandy081** [comment]
@McNuggetSauce It works for me in a workspace case (I have 4 folders). Word separator in user settings is getting recognised.

Can you please check if this setting is overridden in Folder settings?

**Comment by McNuggetSauce** [comment]
@sandy081 There is nothing in the folder settings. Anyway, I re-created a brand new workspace with the same folders that I have on my existing one and the user settings is getting recognized there. Not sure what is up but it works now even removing from the workspace settings on the existsing one.

Will close now since it's no longer an issue. Thanks!
