### ISSUE TITLE
"Edit in settings.json" does nothing

### ISSUE THREAD

**Issue by Xeonacid** [Microsoft/vscode#56538]
Issue Type: <b>Bug</b>

In any item of the ui settings that shows the button, when I click on the "Edit in settings.json", it does nothing.
But the "Open settings.json" in "..." on the top works fine.
I've disabled all extensions but no effect.

VS Code version: Code - Insiders 1.27.0-insider (e2b722d26262a2a15c1e9246a6ab40475ea9c5ed, 2018-08-16T05:18:43.362Z)
OS version: Windows_NT x64 10.0.18214

**Comment by roblourens** [comment]
Oops, good catch
