### ISSUE TITLE
VSCode long file opening.

### ISSUE THREAD

**Issue by Voznesenskiii** [Microsoft/vscode#56541]
Issue Type: <b>Bug</b>

Добрый день. Был установлен VS Code(версию не помню), начал предлагать установить VSCode(User)
Установил VSCodeUserSetup-x64-1.26.0
В итоге на компьютере установлено два VSCode, один старый, другой VSCodeUser 1.26.0
Причина обращения: Долго открываются файлы, любые, хоть по 2 кб. Удалил старую версию VSCode, не помогло. Удалил оба. Не помогло. Долго, это в районе 20 секунд. Стоит SSD. Остальные файловые редакторы(пусть и по легче они, без плагинов и тд, но открываются почти моментально). На счет плагинов. В процессе создания отчета о неполадках, отключал все расширения и повторял процедуру и ничего не изменилось. Все те же ~20 секунд. 

Это рабочий комп, ссд, 16 гб оперативы. Тут проблема появилась после установки VSCodeUserSetup-x64-1.26.0. Я думал он удалит старую сборку, а он взял и поставил ее в другую директорию.
Чистил реестр, были записи на C диске и на E. Удалив все дистрибутивы, почистил реестр от записей VS Code. Установил. Но все равно долго открываются файлики. 
Сейчас установлена единственная версия VSCodeSetup-x64-1.26.0

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.43GB (8.29GB free)|
|Process Argv|E:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
vscode-markdownlint|Dav|0.20.0
vscode-faker|dee|1.3.0
xml|Dot|2.3.1
turbo-log|fac|1.0.3
gc-excelviewer|Gra|2.1.25
rest-client|hum|0.19.1
output-colorizer|IBM|0.1.2
plantuml|jeb|2.8.5
eml|lei|0.2.2
start-git-bash|McC|1.2.1
vscode-language-pack-ru|MS-|1.26.3
mssql|ms-|1.4.0
debugger-for-chrome|msj|4.8.2
sqltools|mtx|0.15.0
java|red|0.29.0
LiveServer|rit|5.1.1
code-settings-sync|Sha|3.0.0
vscode-java-debug|vsc|0.11.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.8.0
vscode-maven|vsc|0.10.0
vscode-todo-highlight|way|1.0.4
plsql-language|xyz|1.4.2
yog-plantuml-highlight|Yog|0.0.5

</details>

**Comment by sandy081** [comment]
@Voznesenskiii Can you please provide description in English, I could not understand even after doing Google Translate.

**Comment by Voznesenskiii** [comment]
Good day!
@sandy081 

I had VSCode on my PC and after suggestion to install another version I installed VSCodeUserSetup-x64-1.26.0. After that, there are 2 versions on my computer. Due to it, any files are opened very long (even 2 kbs size). It takes about 20 seconds. 
I tried to delete old version VSCode then both versions, I cleaned register, turned off plugins and extensions - situation doesn't change. The rest file editors work fine. At this moment on my computer I have VSCodeSetup-x64-1.26.0 and it works bad, opens any file for 20 seconds.
My computer has SSD and 16GB OM. problems appeared after installation new version of VS Code.

**Comment by sandy081** [comment]
May I know which files are you try to open?
Can you please update VS Code to newer version (1.26.1) and try if you can reproduce it again?

**Comment by Voznesenskiii** [comment]
Версия: 1.26.1
Фиксация: 493869ee8e8a846b0855873886fc79d480d342de
Дата: 2018-08-16T18:38:57.434Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Архитектура: x64

.log 
Use a plugin
Output Colorizer
https://marketplace.visualstudio.com/items?itemName=IBM.output-colorizer
and 
.sql
.xml
and other

File extension and size does not matter

**Comment by sandy081** [comment]
Are you able to reproduce the issue without Output Colorizer extension?

**Comment by Voznesenskiii** [comment]
Yes, I turned off not only this extension but all of them. This problem reproduces only on this PC and only with VS Code app. On my personal PC at home with the same VS Code version, there are no problems.

Files with any extensions are opens 20-21 seconds. No more no less.

**Comment by sandy081** [comment]
Can you please profile your VS Code and provide us that data?
