### ISSUE TITLE
Quick search in explorer treeview

### ISSUE THREAD

**Issue by gorkemerdogann** [Microsoft/vscode#56547]
Hello,

Firstly sorry for my english, it's not my native language :) It is difficult to open files or folders when there are a lot of file or folder in treeview explorer panel. Maybe simple search feature can be added. It could be like this; click explorer panel and press ctrl+f or type text without key combination. While you typing search text, the treeview focus and highlight matching file or folder in list.

**Comment by gorkemerdogann** [comment]
I checked #51494.  It's different. This is feature request for search in treeview list :)

**Comment by roblourens** [comment]
#10026
