### ISSUE TITLE
no intellisense on objects stored on this

### ISSUE THREAD

**Issue by hegelstad** [Microsoft/vscode#56543]
- VSCode Version: 1.26.0
- OS Version: mac os 10.13.6 (17G65)

Steps to Reproduce:
1. `with const`
![screen shot 2018-08-16 at 10 12 04](https://user-images.githubusercontent.com/6997343/44196689-ebbde300-a13c-11e8-9b93-ff1f693282bb.png)
2. `with this`
![screen shot 2018-08-16 at 10 13 33](https://user-images.githubusercontent.com/6997343/44196805-38092300-a13d-11e8-9564-c2e17dd6778c.png)

Expected:
`this.graphComponent.mou` to yield same results as `graphComponent.mou`.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by sandy081** [comment]
Is it Typescript?
