### ISSUE TITLE
Inlucded Terminal WSL keystrokes lag

### ISSUE THREAD

**Issue by phifa** [Microsoft/vscode#56559]
Using VS Code 1.26.0 on a Win 10 Pro machine with WSL as integrated terminal, running zsh. 
I would like to do a screen record, but could not find a tool that shows the effect, I would need a higher frame rate to make the effect visible. 

When opening wsl.exe outside of VSC, typing does not lag, it all goes very smooth. In my integrated wsl in VS Code, things are very lagy. I tried running `code --disable-extensions`, but it did not help. 

When I simply push down on a key, like letter `a`, and hold, in the native wsl.exe it shows up very smoothly, but in VS Code, it make these lagy jumps.

**Comment by phifa** [comment]
I found this issue, could be somewhat related. I am too on a 4k monitor: 
https://github.com/Microsoft/vscode/issues/53782 

Also I noticed setting `"terminal.integrated.rendererType": "canvas"` makes it better.

**Comment by phifa** [comment]
I updated my graphics card driver, no the issue is gone. Closing this.

**Comment by Tyriar** [comment]
There was a regression in 1.26, in 1.27 it will be much faster again https://github.com/Microsoft/vscode/issues/56628
