### ISSUE TITLE
Highlight CodeLens with "0 references"

### ISSUE THREAD

**Issue by roman-petrov** [Microsoft/vscode#56551]
VSCode has built-in ability to show "references CodeLens" for TypeScript. It would be great, if "0 references" strings shown for methods/classes are highlighted with some accent color or event show "error/warning marks" on scroll bar area. This could be extremely helpful for project cleanup.

For example, if some public class/method has no references (this happens sometimes during development/refactoring), project members will easily see this and consider removing such functionality if it's really not being used anywhere.

**Comment by roman-petrov** [comment]
Another use case might be to mark somehow in VSCode Explorer classes that never referenced in current workspace

**Comment by mjbvz** [comment]
I think this would be a better fix for an extension such as tslint or estlint
