### ISSUE TITLE
${activeEditorLong} identic with ${activeEditorMedium}

### ISSUE THREAD

**Issue by bardware** [Microsoft/vscode#56550]
- VSCode Version: 1.26.0
- OS Version: Win 10 64bit German

Steps to Reproduce:

I have multiple projects with identic folders and files.
I have the setting `"window.title": "${dirty}${activeEditorLong}${separator}${appName}"`
In `cmd` I change into the folder of my first project and call code like
` code . --extensions-dir "C:\vscode\cfml\exts" --new-window`
I change into folder of second project and open a second code instance with the same command.
It used to be possible to distinguish the two code instances in the windows-taskbar because they displayed the complete path to the opened file. I modified my setting to read `"window.title": "${dirty}${activeEditorMedium}${separator}${appName}"` and nothing changed. I believe you altered the `${activeEditorLong}` variable...

Did you do this willingly?

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by bpasero** [comment]
@isidorn regression from the URI display service? The long title for a file is no longer its absolute path. 

![image](https://user-images.githubusercontent.com/900690/44251122-84b13480-a1f7-11e8-957d-81436af73726.png)

Setting candidate label since this seems to be a regression.

**Comment by isidorn** [comment]
@bpasero no sever enough to delay the recovery build today. I will investigate a bit later to consider if this should go in to a potential second recovery build

**Comment by bpasero** [comment]
@isidorn yeah, for second recovery, if any.

**Comment by bardware** [comment]
Saw it working in recent insider version

```
Version: 1.27.0-insider
Commit: 07618102efdd63f09949ce54c161e7fd2a954ee8
Datum: 2018-08-23T05:20:35.051Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architektur: x64
```

**Comment by isidorn** [comment]
@bardware thank you, adding verified label
