### ISSUE TITLE
Documentation needs updating

### ISSUE THREAD

**Issue by SDanton** [Microsoft/vscode#56554]
Please update your documentation at https://code.visualstudio.com/docs/other/unity

VS Code does not reside at "C:\Program Files (x86)\Microsoft VS Code\Code.exe" on Windows10, but rather  C:\Users\<user>\AppData\Local\Programs\Microsoft VS Code

**Comment by gregvanl** [comment]
This issue was moved to Microsoft/vscode-docs#1797
