### ISSUE TITLE
Make breadcrumbs picker styling consistent with menus

### ISSUE THREAD

**Issue by lllopo** [Microsoft/vscode#56552]
Since the breadcrumb picker is essentially a menu popup, I think it should follow the overall menu styling in VS Code. Currently the situation is rather inconsistent :
- it has it's own coloring settings for background in "workbench.colorCustomizations" - this is "breadcrumbPicker.background"
- it does not have a selected/hover foreground customization at all
- the selection foreground does not currently match the menu selection/hover foreground and it looks sort of a hardcoded color.

To avoid those inconsistencies, I believe the breadcrumbs picker should just follow the menus styling and customizations, including eventual shadows, borders, background, foreground, highlight colors etc.

**Comment by jrieken** [comment]
I don't think that menu compare well to the breadcrumb picker. In what it does and how it works its much closer to the quick pick and workbench trees.

**Comment by lllopo** [comment]
@jrieken Spot on, but the thing is quick pick should also obey the menu styling imo ... I just didn't put it in the list, but it falls in the same category, I think. 
Basically, in terms of UI, I split the elements in sidebar(which lives on it's own :-) ), panels and popovers. And all popovers - quickpick, menus, breadcrumbs picker etc. should eventually follow the same styling. 
Ok, for the internals of each of them can be some differences, which should be styled (and customized) separately, but the basic popover frame is the same and when the internals are a selectable list - it is again the same as a menu. So, the main styling - shadow, bordering, background etc. are kind of the same for all ... or at least should be, I believe.

**Comment by misolori** [comment]
@jrieken does the breadcrumb picker use the quick pick theme defaults if not set?

**Comment by jrieken** [comment]
Both have the same default background color

**Comment by misolori** [comment]
> it has it's own coloring settings for background in "workbench.colorCustomizations" - this is "breadcrumbPicker.background"

This defaults to `editorWidget.background` which is set to match the quick pick background with https://github.com/Microsoft/vscode/pull/58229

> it does not have a selected/hover foreground customization at all

These are the same styles as the list widget, which use all of the `list.*` theme colors (i.e. `list.focusBackground`, `list.activeSelectionBackground`, etc.)

> the selection foreground does not currently match the menu selection/hover foreground and it looks sort of a hardcoded color.

This is inherited by the `list.activeSelectionForeground` color

Given that the breadcrumbs picker is most similar to the quick pick and follows the same styling as the list widget in the explorer, will close this issue as `as-designed`. If there are additional issues you find please file a new issue. Thanks!

**Comment by lllopo** [comment]
@misolori As I concluded earlier - I think the quick pick itself should also obey all other popover/menu controls styling and so - same goes for the breadcrumbs picker etc. All these are much closer to a menu, than to the list control. I'm talking in terms of framing. It is not entirely true for the internals, of course (although partially it is).
If you think this is not fitting the VS Code concept - closing for being as-designed is the thing to do. Yet - If you want to put a second though on my point would be great.
