### ISSUE TITLE
Stop prompting to update to alternative version

### ISSUE THREAD

**Issue by sqllensman** [Microsoft/vscode#56562]
Issue Type: <b>Feature Request</b>

There appears to be a different install option for VSCode that you insist on constantlly produce annoying popup messages.

Please just stop!!!!

One message is probable one too many and the rest are just extremly annoying. If I cared I can see it in the release notices

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 10.0.17713

**Comment by tboby** [comment]
I agree, this is quite irritating because it's not a simple process. I would understand for a trivial upgrade, but this installer immediately tells you not to install it (as you already have vscode installed).

**Comment by joaomoreno** [comment]
You can click the ⚙️ gear icon and then `Don't Show Again`. I've pushed a change which will make that option more visible.
