### ISSUE TITLE
Live share doesn't work with workspace

### ISSUE THREAD

**Issue by rav84** [Microsoft/vscode#56569]
Issue Type: <b>Bug</b>

I am using a workspace (file) which has multiple root folders. When I start liveshare and share the link. My colleague only gets to see one (its first one) project.

VS Code version: Code - Insiders 1.27.0-insider (b00ab5288f314f6ef8d82923d89a0555ad15eb06, 2018-08-16T09:38:37.976Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (6.36GB free)|
|Process Argv|C:\Users\ravish.kumar.admin\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.5.4
tslint|eg2|1.0.34
mssql|ms-|1.4.0
python|ms-|2018.7.1
csharp|ms-|1.15.2
vsliveshare|ms-|0.3.535
debugger-for-chrome|msj|4.8.2
vscode-docker|Pet|0.1.0
vscode-icons|rob|7.25.0

(2 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Please report to the live share team https://github.com/MicrosoftDocs/live-share/issues
