### ISSUE TITLE
Search icon in sidebar was disappeared after setting search location to panel

### ISSUE THREAD

**Issue by daviestang** [Microsoft/vscode#56567]
After change search location to panel in User Settings such as:

`"search.location": "panel"`

The search icon was disappeared in left sidebar. This will cause can't open search panel by one-click. The user only can open the search panel through Menu or Keyboard shortcuts.

I'm not sure whether the developers already know this issue, and they treat this as a feature. But this really should be improved.

**Comment by roblourens** [comment]
This is by design, the activity bar should only show icons for features available in the sidebar. I recommend using the keyboard shortcut to show the search pane, for the fastest access.
