### ISSUE TITLE
Syntax highlighting disabled after a certain line in TypeScript React

### ISSUE THREAD

**Issue by andraaspar** [Microsoft/vscode#56561]
Issue Type: <b>Bug</b>

1. New file
2. Select Language Mode > typescriptreact
3. Paste code:

```TS
function highlightMe() {
    return (
        <Foo>
            <Bar
                fun={() =>
                    <Wicked_Compontent // Highlighting works
                        key={obj[0]} // Highlighting does not work
                    />
                }
            />
            <Quux>
                <em>I'm not highlighted :(</em>
            </Quux>
        </Foo>
    )
}
```

VS Code version: Code - Insiders 1.27.0-insider (b00ab5288f314f6ef8d82923d89a0555ad15eb06, 2018-08-16T09:38:37.976Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (1.85GB free)|
|Process Argv|C:\Users\aparditka\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by andraaspar** [comment]
I can see three things that trigger this together:

- the `fun` attribute with the function
- the underscore in `Wicked_Component`
- the `[0]`

Deleting some will re-enable highlighting. HTH

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#649
