### ISSUE TITLE
Integrated terminal pop-up error renderer seems to be slow

### ISSUE THREAD

**Issue by choeffer** [Microsoft/vscode#56563]
- VSCode Version: 1.26.0
- OS Version: Debian Stretch running in a VirtualMachine, VirtualBox with GuestAdditions installed and 3D Acceleration disabled.

Steps to Reproduce:

1. Open VSCode 
2. Warning/Error pops up when typring something in the integrated terminal "The standard renderer for the integrated terminal appears to be slow on your computer. Would you like to switch to the alternative DOM-based render which may improve performance?"

Does this issue occur when all extensions are disabled?: Yes

On the last build the error didn't appear, just after updating with apt-get dist-upgrade this morning it happened (followed this steps to install the repository by hand https://code.visualstudio.com/docs/setup/linux )

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/56628
