### ISSUE TITLE
Support javascript private properties defined with #

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [Microsoft/vscode#56566]
Currently vscode throws an invalid character error when defining javascript private methods or properties started with # symbol

![image](https://user-images.githubusercontent.com/29608698/44212183-101bbe80-a141-11e8-9c4c-dcf3269508e0.png)

**Comment by iansan5653** [comment]
Is this a native language feature? As far as I'm aware, that is not valid JavaScript and definitely should throw an error.

**Comment by diego-lipinski-de-castro** [comment]
Oh well, I read about this in many forums, didnt even noticed this 

```
Private class fields are now at Stage 2 in the JavaScript standard process. It's not finalized yet, but the JavaScript standards committee expects the feature to be developed and eventually included in the standard (although it may still change).
```

I though it was already done, im closing
