### ISSUE TITLE
Files fail to save occasionally

### ISSUE THREAD

**Issue by crewone** [Microsoft/vscode#56565]
Issue Type: <b>Bug</b>

This was not a problem in the previous build, but since updating to the latest insider-user build files occasionally fail to save - and by that I mean all open files. Ctrl+S or the menu does nothing. The file just doesn't change on disk.

A restart of the application fixes the problem, but it re-occurs soon after that.  (I have repeated this a few times now.)

After this occurs, the application fails to close. Need to close using task manager.

Also, the same configuration (using settings sync) with the non-insiders build works fine.

VS Code version: Code - Insiders 1.27.0-insider (b00ab5288f314f6ef8d82923d89a0555ad15eb06, 2018-08-16T09:38:37.976Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (8.62GB free)|
|Process Argv|C:\Users\Sander\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.0.3
git-easy|bib|1.9.1
vscode-git-grep|bok|0.0.7
gitignore|cod|0.5.0
bracket-pair-colorizer|Coe|1.0.59
vscode-eslint|dba|1.4.12
xml|Dot|2.3.1
gitlens|eam|8.5.4
git-project-manager|fel|1.6.1
php-debug|fel|1.12.3
php-intellisense|fel|2.3.3
auto-close-tag|for|0.5.6
sass-lint|gle|1.0.3
package-watcher|Gre|0.0.2
vscode-apache|mrm|1.1.1
vscode-scss|mrm|0.6.2
debugger-for-chrome|msj|4.8.2
php-docblocker|nei|1.6.0
vscode-icons|rob|7.25.0
blockalign|San|0.6.0
git-merger|sha|0.4.1
code-settings-sync|Sha|3.0.0
javascript-typescript|sou|0.0.7
JavaScriptSnippets|xab|1.7.0
html-css-class-completion|Zig|1.17.1

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by crewone** [comment]
I have not had the issue with the newer builds. I would chalk it up as "cannot reproduce" and close the issue.
