### ISSUE TITLE
Search all and switch back to explorer view conflicts  

### ISSUE THREAD

**Issue by ceyhunkerti** [Microsoft/vscode#56572]
VSCode Version: 1.26.0 also insider 1534412121 
OS Version: Ubuntu Mate 18.04
Steps to Reproduce:

1. open a project/ folder
2. ctrl + shift + f to search all
3. ctrl + shift + e to switch to explorer 

Does this issue occur when all extensions are disabled?: Yes

This also effects other shortcuts like ctrl + z
as far as i see.

This problem makes it very hard to use vscode, all of a sudden.

**Comment by ceyhunkerti** [comment]
switched back to 1.25.1 which does not have this problem

**Comment by roblourens** [comment]
What is the problem exactly?

**Comment by roblourens** [comment]
Do you have any custom keybindings that conflict here?

**Comment by ceyhunkerti** [comment]
in the latest build. 
i do search all with `ctrl + shift + f` then
i try to switch to explorer window with `ctrl + shift + e` 
but it prints wierd characters i mean it should switch back to explorer view but it does not.
also if you try to undo with `ctr+z` it prints just `"z"`
I think using the search all shortcut affects the after on some key bindings.

I can share a screencast if you like.  

As i said falling back to `1.25` solves the problem. I do not have set any special key binding btw.
I use the defaults.

**Comment by roblourens** [comment]
Are you using a non-english keyboard layout?

If you press ctrl+shift+e with focus other places, does it print the same characters?

**Comment by ceyhunkerti** [comment]
Focused On editor 
Ctrl shift e prints e
Ctrl z prints z

When focused on search panel
Ctl shift e print a non ascii char

**Comment by ceyhunkerti** [comment]
Focused On editor 
Ctrl shift e prints e
Ctrl z prints z

When focused on search panel
Ctl shift e print a non ascii char

**Comment by roblourens** [comment]
Does anything in this wiki page help?

https://github.com/Microsoft/vscode/wiki/Keybinding-Issues

**Comment by OnlyLys** [comment]
The problem is the `Ctrl+Shift+E` keybinding. GTK+ 3 is intercepting the keybinding. Please see issue thread #48480 for more info.

**Comment by ceyhunkerti** [comment]
don't get it? why it is working in `vscode 1.25` then ?

**Comment by ceyhunkerti** [comment]
Ok. After i looked at the issue #48480 i 've installed `ibus` and changed the input method to `ibus`
and removed the emoji shortcut. Nothing happened.
But, 
- i've removed the `ibus`
- Rebooted
- And changed the input method to `xim` 
Then the functionalty works without problem now. In 1.26 as well as in insider build.

Still have no clue what happened but. My issue is resolved.
Thanks...

**Comment by David-Else** [comment]
@ceyhunkerti I had some similar nonsense, you might find that `GTK_IM_MODULE=ibus code` now works (if you have ibus installed), there is some kind of bug somewhere that seems to make fixing the issue not as easy as it should be. Check https://github.com/Microsoft/vscode/issues/48480#issuecomment-414136710
