### ISSUE TITLE
很喜欢vscode,但是前几天发现一个bug:

### ISSUE THREAD

**Issue by arixse** [Microsoft/vscode#5657]
- VSCode Version:
- OS Version:
最新版本
Steps to Reproduce:

1. 由第三方工具（如gulp,grunt）创建的文件不能自动刷新出来，而且手动刷新也不行
2.

**Comment by dbaeumer** [comment]
@arixse could you please try to provide the description in English. We don't speak the language you used.

**Comment by ups216** [comment]
@dbaeumer quick translation, may help you a bit. 

the file created by 3rd party tools (e.g. gulp, grunt) cannot be shown automatically, he has to refresh manually to see the files.

**Comment by dbaeumer** [comment]
@ups216 thanks for the translation.

@arixse this should work. Is the folder the grunt or gulp file ignored in the settings?
