### ISSUE TITLE
Unable to paste (ctrl+v) when using in a browser with a mock node process

### ISSUE THREAD

**Issue by richardmward** [Microsoft/vscode#56577]
When using the vscode editor in a browser via `monaco-editor` (specifically the esm bundles using `monaco-editor-webpack-plugin`) the `platform` is not being identified correctly - `isWeb === false` and `isNative === true`. 

The issue appears when `node.process = 'mock'` in the webpack config, which means that `process.platform === "browser"`. As you can see from the below snippet from `platform.ts`, it only checks that `typeof process.platform === 'string'`, which it is in this case, but the string is `browser`. This results in it being treated as native rather than web - which in turn messes with the key bindings for pasting etc.

https://github.com/Microsoft/vscode/blob/4390abed32339f9cb6295d8d46ac886e67fd9c47/src/vs/base/common/platform.ts#L45

Maybe adding `&& process.platform !== "browser"` would be an accetable fix?

I was directed to this being the cause of the issue from https://github.com/Microsoft/monaco-editor-webpack-plugin/issues/17#issuecomment-408303369 - a closed issue, but I guess as the issue doesn't really reside in the plugin, it makes sense for it to be raised here instead?

- VSCode Version: Whatever is used by monaco-editor v0.13.1
- OS Version: Windows 10, Firefox 61

Steps to Reproduce:

_A stripped down version of the relevant parts of the webpack config_

``` js
const MonacoWebpackPlugin = require("monaco-editor-webpack-plugin");

module.exports = {
  node: {
    process: 'mock',
    ...
  },
  plugins: [
    new MonacoWebpackPlugin(),
    ...
  ],
  ...
}
```

Does this issue occur when all extensions are disabled?: N/A

**Comment by fabsenet** [comment]
changing the quoted line from @richardmward to 
```js
if (typeof process === "object" && typeof process.nextTick === "function" && typeof process.platform === "string" && process.platform !== "browser") {
```

fixed the issue for me.

if it is of any help: I used vue-cli and vue-cliservice to generate and serve/build my webapp. vue-cliservice uses webpack under the hood. I also use the MonacoWebpackPlugin().

maybe helpful dependency versions:
```js
    "monaco-editor": "^0.14.3",
    "monaco-editor-webpack-plugin": "^1.5.1",
    "vue": "^2.5.17",
    "vue-class-component": "^6.0.0",
    "vue-clipboard2": "^0.2.1",
    "vue-monaco": "^0.2.0",
    "vue-multiselect": "^2.1.0",
    "vue-property-decorator": "^7.0.0",
    "vue-router": "^3.0.1",
    "vue-tables-2": "^1.4.64",
    "vuex": "^3.0.1",
    "vuex-class": "^0.3.1"
    "@vue/cli-plugin-typescript": "^3.0.1",
    "@vue/cli-service": "^3.0.1",
    "node-sass": "^4.9.0",
    "sass-loader": "^7.0.1",
    "typescript": "^3.0.0",
    "vue-template-compiler": "^2.5.17"
```

**Comment by rebornix** [comment]
https://github.com/Microsoft/monaco-editor-webpack-plugin/issues/17#issuecomment-408303369 was reopened. IMO it's a webpack specific issue so we still track it there.
