### ISSUE TITLE
Replace Sketchy Application Installer for Linux

### ISSUE THREAD

**Issue by mbuttler** [Microsoft/vscode#56570]
Hey folks,

VSCode's installer for linux64_rpm is pretty sketchy:

![image](https://user-images.githubusercontent.com/3672022/44214486-44da4680-a13e-11e8-84a3-367fe50af087.png)

It would be nice to include the VSCode logo and... uh.. application name to make it easier to find and trust.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/37813
