### ISSUE TITLE
Broken breadcrumb background color

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#56576]
Issue Type: <b>Bug</b>

Don't know if this is intended, but if so at least we should fix the color for included themes.

![image](https://user-images.githubusercontent.com/4033249/44218130-e016f000-a12d-11e8-9fe1-7335d6fcd8ff.png)

![image](https://user-images.githubusercontent.com/4033249/44218066-bfe73100-a12d-11e8-9c67-5bed4585afcb.png)

VS Code version: Code - Insiders 1.27.0-insider (b00ab5288f314f6ef8d82923d89a0555ad15eb06, 2018-08-16T09:29:15.226Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.63GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_7927695|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-emoji|bie|0.0.7
markdown-preview-github-styles|bie|0.1.2
tslint|eg2|1.0.34
vsc-material-theme|Equ|2.3.0
prettier-vscode|esb|1.6.1
beautify|Hoo|1.3.2
theme-monokai-pro-vscode|mon|1.1.8
vscode-language-pack-ja|MS-|1.26.3
debugger-for-chrome|msj|4.8.2
vetur|oct|0.12.6
polacode|pnp|0.2.2
vscode-sort-json|ric|1.13.0
vue-vscode-snippets|sdr|1.3.0
vscode-csstree|sme|0.7.0
language-stylus|sys|1.9.2
vim|vsc|0.16.0

(2 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
The color can now be themed but it seems like a regression with Insiders...
