### ISSUE TITLE
Tiny fonts on 4K display

### ISSUE THREAD

**Issue by mbenkmann** [microsoft/vscode#56585]
- VSCode Version: 1.26
- OS Version: Linux

Steps to Reproduce:

1. Upgrade from 1.25 to 1.26 on a system with a 4K display
2. Fonts are tiny and hard to read

Does this issue occur when all extensions are disabled?: Yes

window.zoomLevel is not an adequate workaround, since it does not affect the menu bar and popup menus. My system's DPI value is properly set to 139 DPI and up to version 1.25 fonts were reasonably sized. The behaviour with 1.26 looks like the DPI value has been hardcoded to 96 now.

**Comment by nealot** [comment]
Can you post a screenshot? I have a 4k monitor and haven't experienced any issues running on linux.
