### ISSUE TITLE
All extensions do not contain "Details" in VSC-Insiders

### ISSUE THREAD

**Issue by Daneev** [Microsoft/vscode#56582]
![vsci](https://user-images.githubusercontent.com/30390132/44219776-e937a980-a18d-11e8-83dc-15c6c5681c27.JPG)

**Comment by Daneev** [comment]
Версия: 1.27.0-insider
Фиксация: b00ab5288f314f6ef8d82923d89a0555ad15eb06
Дата: 2018-08-16T09:38:37.976Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Архитектура: x64

Console errors are errors in the terminal. But they are not related to the surrendered problem. No extensions, including embedded ones, show the Details tab. The cursor over the position does not change its shape to a pointer.

![vsci-1](https://user-images.githubusercontent.com/30390132/44248011-2e44f580-a1f9-11e8-9a79-4b7f00383faa.JPG)

**Comment by Daneev** [comment]
Версия: 1.26.0
Фиксация: 4e9361845dc28659923a300945f84731393e210d
Дата: 2018-08-13T16:29:31.933Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Архитектура: x64
![vsci-2](https://user-images.githubusercontent.com/30390132/44248838-f42a2280-a1fd-11e8-95de-7431253b0247.JPG)

**Comment by ramya-rao-a** [comment]
So there are no errors in the console?

![image](https://user-images.githubusercontent.com/16890566/44370567-9876c800-a48f-11e8-92df-aa3daa4cd0f1.png)

![image](https://user-images.githubusercontent.com/16890566/44370591-b9d7b400-a48f-11e8-8836-9fc46392f14b.png)

**Comment by Daneev** [comment]
I will attach errors from both versions of the program.
![vsci-3](https://user-images.githubusercontent.com/30390132/44382918-e212f180-a527-11e8-88b2-9ddefb55b24f.JPG)

**Comment by Daneev** [comment]
[vsc.log](https://github.com/Microsoft/vscode/files/2304980/vsc.log)
[vsc-i.log](https://github.com/Microsoft/vscode/files/2304981/vsc-i.log)

**Comment by ramya-rao-a** [comment]
Those errors are from the logger and shouldnt affect the extensions details.

@sandy081 Any ideas on why the **details** section wouldnt show up just on Insiders?

**Comment by sandy081** [comment]
Is it just the details tab or other tabs (contributions) too?
Might not be the reason, but to exclude it, did you try VS Code in default english locale?

**Comment by Daneev** [comment]
Other tabs work. As an option in English.
![vsci-4](https://user-images.githubusercontent.com/30390132/44421417-7b2a2280-a591-11e8-9706-f09e33460cda.JPG)
![vsci-5](https://user-images.githubusercontent.com/30390132/44421421-7feed680-a591-11e8-934b-e9bd08a4bffa.JPG)

**Comment by Daneev** [comment]
The fact is that under the same conditions on a simple VSC, the detail tab works on a Russian language pack.

**Comment by sandy081** [comment]
Only difference between other tab and details tab is details tab is a web view.

@mjbvz May I know if this is anything to do with web view?

**Comment by Daneev** [comment]
Sorry, I did not quite understand the question. What needs to be done to respond to it? VSC-I does not display README.md

**Comment by sandy081** [comment]
@Daneev Above question is not meant for you.. Its to one of my colleagues

**Comment by Daneev** [comment]
Версия: 1.27.0-insider (user setup)
Фиксация: 1097b5e9ed81d5f9241648774b35048be168c203
Дата: 2018-08-31T10:38:54.277Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Архитектура: x64

The last update led to a clean window.
![vsci-7](https://user-images.githubusercontent.com/30390132/44955513-89e3d400-aec5-11e8-8889-cbcee55face5.JPG)
[vsc-i_02.09.2018.log](https://github.com/Microsoft/vscode/files/2343248/vsc-i_02.09.2018.log)

**Comment by RAYDENFilipp** [comment]
I have the same trouble too

**Comment by Daneev** [comment]
Версия: 1.27.0-insider
Фиксация: 8727085fff33bf7d8f5e27483b10f72508d4167a
Дата: 2018-08-14T05:18:11.938Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Архитектура: x64

Reinstalled on the simple path to the root on the drive "c: \". Before updating. Everything works, even the details of the expansion appear, although not immediately, but after a while.
![vsci-8](https://user-images.githubusercontent.com/30390132/45138047-20f9a600-b1bc-11e8-98d9-0ef0e5fb9585.JPG)
[version 1.27.0-insider_fix_8727085fff33bf7d8f5e27483b10f72508d4167a_data_2018-08-14T05_18-11.938Z_Electron_2.0.7_Chrome_61.0.3163.100_Node.js_8.9.3_V8_6.1.534.41.log](https://github.com/Microsoft/vscode/files/2355693/version.1.27.0-insider_fix_8727085fff33bf7d8f5e27483b10f72508d4167a_data_2018-08-14T05_18-11.938Z_Electron_2.0.7_Chrome_61.0.3163.100_Node.js_8.9.3_V8_6.1.534.41.log)

**Comment by Daneev** [comment]
Версия: 1.27.0-insider (user setup)
Фиксация: 7b9afc4196bda60b0facdf62cfc02815509b23d6
Дата: 2018-09-03T09:14:29.879Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Архитектура: x64
After the program is updated, everything disappears.
[-1536214069042.log](https://github.com/Microsoft/vscode/files/2355705/-1536214069042.log)
![vsci-9](https://user-images.githubusercontent.com/30390132/45138242-cca2f600-b1bc-11e8-8a11-c4013a9f9fbc.JPG)

**Comment by Daneev** [comment]
VSC
Версия: 1.26.1
Фиксация: 493869ee8e8a846b0855873886fc79d480d342de
Дата: 2018-08-16T18:38:57.434Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Архитектура: x64

After the update, it was installed in a new way containing the Cyrillic alphabet ("C:\Users\Домашний\AppData"). The details of the extensions are likewise gone. Before installation was along the way: ("C:\Program Files") and everything worked. Apparently the point is this.
![vsci-10](https://user-images.githubusercontent.com/30390132/45142985-ffec8180-b1ca-11e8-9ed1-1229aa57ffed.JPG)

**Comment by RAYDENFilipp** [comment]
It is definitely a problem with Cyrillic words used for a folder name. When I changed install direction when I tried to reinstall VS Code, I used the 'Program Files' folder instead. And it worked! Now I have extension details in my program.

**Comment by mjbvz** [comment]
You need to be on the latest 1.28 insiders to get the fix

**Comment by Winand** [comment]
Still empty.
![image](https://user-images.githubusercontent.com/53390/45318655-42ed8280-b546-11e8-8cbe-70f7ebfe1762.png)

**Comment by mjbvz** [comment]
@Winand What is your install path?

**Comment by Daneev** [comment]
Версия: 1.28.0-insider (user setup)
Фиксация: 96854113091424c07b28ba84b82b75a88b8455cb
Дата: 2018-09-10T05:18:57.119Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Архитектура: x64
![vsci1](https://user-images.githubusercontent.com/30390132/45340036-02255600-b5a6-11e8-8ee3-b69e8d6e6fd3.JPG)
[-1536644057601.log](https://github.com/Microsoft/vscode/files/2369435/-1536644057601.log)

**Comment by Winand** [comment]
@mjbvz it is `C:\Users\Андрей\AppData\Local\Programs\Microsoft VS Code Insiders`
p.s. see my comment to a957654db2cbf8df37f7d0139e103a7ecffdf926

**Comment by Winand** [comment]
I confirm. It works as expected on my system.
