### ISSUE TITLE
JavaScript IntelliSense NOT WORK In HTML file

### ISSUE THREAD

**Issue by shuaihuGao** [Microsoft/vscode#56580]
Hi .
Sir.
Now JavaScript IntelliSense Can't Work in HTML File . It's Only can work with Jquery.

**Comment by shuaihuGao** [comment]
Oh.
 i found that it could not automatically find d.ts files.

**Comment by mjbvz** [comment]
Please provide repo steps and example code that explains what is now working

**Comment by shuaihuGao** [comment]
jsconfig.json Setting as this.
<img width="758" alt="01" src="https://user-images.githubusercontent.com/29368118/44581171-3e4b6f00-a7cf-11e8-87c6-a1f698adfaee.png">

**Comment by mjbvz** [comment]
Thanks. After reviewing your example, this is a duplicate of #26338
