### ISSUE TITLE
On Switching Files file is not selected in left pane

### ISSUE THREAD

**Issue by drweb86-work** [Microsoft/vscode#56588]
Issue Type: <b>Bug</b>

Hello

When i switch between files files are no longer selected in left tree.,

Thank you.

VS Code version: Code - Insiders 1.27.0-insider (b00ab5288f314f6ef8d82923d89a0555ad15eb06, 2018-08-16T09:38:37.976Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6260U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (3.76GB free)|
|Process Argv|C:\Users\Sergey Kuchuk\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.12
tslint|eg2|1.0.34
vscode-scss|mrm|0.6.2
tsimporter|pmn|1.2.14
typescript-hero|rbb|2.3.2
vscode-icons|rob|7.25.0
stylelint|shi|0.39.0

</details>

**Comment by roblourens** [comment]
Did you set the `explorer.autoReveal` setting?

**Comment by drweb86-work** [comment]
Hello

This setting is enabled
![image](https://user-images.githubusercontent.com/29063147/44262918-724def80-a225-11e8-8e82-b71285afdec9.png)

**Comment by drweb86-work** [comment]
Navigation is not working anymore since this build.
![image](https://user-images.githubusercontent.com/29063147/44262950-a45f5180-a225-11e8-97b2-892dd9bd889a.png)
I have a workspace with project and additional folder. When i press Ctrl+T and navigate through it to file editor tree is still folded and i dont see files near

**Comment by drweb86-work** [comment]
Rigit click on file and press 'Reveal on Side Bar' does not do anything as well

**Comment by bpasero** [comment]
I can reproduce:
* be on Windows
* have an empty window
* File > Open > pick 2 folders
* You are now in an untitled workspace with 2 folders
* quick open a file from one folder
* 🐛 the file is not revealed in the explorer

Seems like a bad check around here where we have an uppercase drive letter in the explorer root but a resource with a lowercase drive letter:

![image](https://user-images.githubusercontent.com/900690/44266878-792c3080-a22c-11e8-926a-d6b0f4ea2982.png)

My understanding is that for resources the drive letter should always be lowercase.

/cc @isidorn

**Comment by bpasero** [comment]
> It would be cool if you can publish fix, because its not comfortable to work now.

!
