### ISSUE TITLE
False positives with PSScriptAnalyzer - "$null should be on the left side of equality comparisons"

### ISSUE THREAD

**Issue by JeremyTBradshaw** [Microsoft/vscode#56590]
Issue Type: <b>Bug</b>

Is this really a problem?:

> [PSScriptAnalyzer] $null should be on the left side of equality comparisons. (PSPossibleIncorrectComparisonWithNull)

I check to see if something is $null and then do stuff depending on the answer.  Why shouldn't $null be on the right side of equality comparisons?  Either side is just as good as far as I can tell.

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.76GB (2.96GB free)|
|Process Argv|C:\Users\jerem\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
PowerShell|ms-|1.8.3

(1 theme extensions excluded)

</details>

**Comment by Adondriel** [comment]
because you are comparing null to the thing that changes, best practice is to compare the thing that changes to the thing that is "constant." I'm sure you could find some journal article that shows how the CPU actually processes this, and that it's slower or something, but i believe it's mostly just standard practice and readability. 

Aside from that, is this error valid, or are you getting it in a place it shouldn't be?

**Comment by JeremyTBradshaw** [comment]
Hello and thanks.  I ended up just disabling that PSScriptAnalyzer check.  I think it just threw me off because only recently did this problem start to be called out.  I've been using $null on the right side forever, but none of my PowerShell work is intensive enough that I need the absolute best efficiency, so I never knew about this best practice.  We are good to close the issue as it's not really an issue, like you explained.

Thanks again.
