### ISSUE TITLE
unable to watch for file changes

### ISSUE THREAD

**Issue by SchrodingersCat00** [Microsoft/vscode#56596]
Issue Type: <b>Bug</b>

Every time I start vscode I get a notification that the file watcher is not working because the working directory has too many files. However this also appears when I open code in an empty directory. When I reinstall code it does not appear for a while, but after using code for a few days, it starts to appear again.Also the RAM usage is extremely high: 400MB in an empty folder. I'm using vscode on elementary OS 0.4.1 Loki

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:25:59.521Z)
OS version: Linux x64 4.15.0-30-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|3.75GB (0.11GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.7.1
java|red|0.29.0
stardog-rdf-grammars|sta|0.0.6
python|tht|0.2.3
vscode-java-debug|vsc|0.11.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.8.0
vscode-maven|vsc|0.10.0

</details>

**Comment by SchrodingersCat00** [comment]
Sure!
![screenshot from 2018-08-17 09 51 59_arrow](https://user-images.githubusercontent.com/37635647/44254680-d2339e80-a203-11e8-9e0c-0741d92cfdca.png)

**Comment by bpasero** [comment]
@SchrodingersCat00 can you follow the instructions?

**Comment by SchrodingersCat00** [comment]
I could, but I'm confused because the [instructions](https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc) tell me to increase the file watcher limit (_which is currently set to 8192_) when there are no files in my directory. I assume workspace is the same as current working directory? Since my system does not have too much memory, I'm not a big fan of increasing the file watcher limit.

**Comment by bpasero** [comment]
Hm, maybe an extension triggers that limit somehow. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces.

**Comment by SchrodingersCat00** [comment]
![image](https://user-images.githubusercontent.com/37635647/44258141-6a368580-a20e-11e8-9398-48f1bc5d052e.png)
I run the command and the message still pops up on startup.

**Comment by bpasero** [comment]
Does this reproduce if you restart and only start VSCode but nothing else?

**Comment by SchrodingersCat00** [comment]
I did some rebooting (about 10 times) and the message doesn't appear when I start vscode immediately after startup. But when I start it about 10 secs after rebooting it does appear, no matter how I launch vscode (taskbar, terminal, with and without extensions)

**Comment by bpasero** [comment]
So possibly some other app is requiring a lot of file handles?

**Comment by SchrodingersCat00** [comment]
You are right! When I closed [Ulauncher](https://ulauncher.io/) the message doesn't appear anymore. Since I'm new to operating systems, I'm not sure if this is normal behaviour for a application launcher to use so much file handles?

**Comment by bpasero** [comment]
Ok nice, maybe report to them. I am closing this one.
