### ISSUE TITLE
Respect the system wide network proxy configuration

### ISSUE THREAD

**Issue by sudheesh001** [Microsoft/vscode#5659]
- VSCode Version: 1.0.0
- OS Version: Mac OS X 10.11

Steps to Reproduce:

1. Try to download / list an extension behind a proxy (http/https)
2. Failure in download.

**Comment by joaomoreno** [comment]
Unfortunately, a [proxy requires manual configuration](https://code.visualstudio.com/docs/supporting/faq#_proxy-server-support).

**Comment by sudheesh001** [comment]
Agreed, but wouldn't auto configuring it according to the user, be a better idea ?

**Comment by joaomoreno** [comment]
Yeah... [everyone's](http://jjasonclark.com/how-to-setup-node-behind-web-proxy/) [just waiting](https://github.com/atom/apm#using-a-proxy) [for someone to fix it](https://discuss.atom.io/t/how-to-install-an-atom-package-on-windows-8-behind-a-proxy-server/12520/11).

**Comment by joaomoreno** [comment]
I could leave this open, but I'd argue this is an idea for a node module in itself. If someone ends up building it, we'd use it!
