### ISSUE TITLE
Emmet support for .liquid files 

### ISSUE THREAD

**Issue by brohlson** [Microsoft/vscode#56593]
Hey VS Code team, 

Looking for a solution for enabling Emmet html autocompletion in Shopify Liquid templating files. 

If there is already support, please let me know!

**Comment by ramya-rao-a** [comment]
Can you provide sample code and the extensions you use for such files?

**Comment by brohlson** [comment]
Hi Ramya, 

You can just create an `index.liquid` file in VS Code, and then start writing some HTML markup. 

For example, typing `div.foo-class` and then `tab` would normally result in `<div class="foo-class"></div>` with Emmet.  However, I've been unsuccessful in trying to enable it within these `.liquid` files. 

Let me know if you need any more info!

**Comment by frankspin89** [comment]
@brohlson have you enabled liquid support for emmet in your preferences file? 

```
"emmet.includeLanguages": { "liquid": "html" },
```

**Comment by brohlson** [comment]
Boom!  Thank you, this works.  Closing out.

**Comment by ramya-rao-a** [comment]
Thanks @frankspin89!

@brohlson For more, please read https://code.visualstudio.com/docs/editor/emmet
