### ISSUE TITLE
Add a command to prune non-existent workspaces / folders in Open Recent

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#56592]
Let's say I have opened 10 projects under `/project` from VS Code. One day I decided to rename `/project` to `/projects`. Now VS Code's Open Recent includes 10 dead links that'll always clog my search result.

**Comment by usernamehw** [comment]
Duplicate of #49056

**Comment by octref** [comment]
Related I guess, but this one is for projects.

**Comment by isidorn** [comment]
fyi @bpasero

**Comment by bpasero** [comment]
I think if we had such a command it should consistently across all history. Closing as duplicate of https://github.com/Microsoft/vscode/issues/49056
