### ISSUE TITLE
Multiline replace with control characters copied

### ISSUE THREAD

**Issue by gaby64** [Microsoft/vscode#56599]
VSCode 1.27
Windows 10

Wont let me do a replace of control characters selected from text

![issue](https://user-images.githubusercontent.com/2108555/44230330-dced2580-a168-11e8-91e1-5f7893fac2cc.jpg)

**Comment by rebornix** [comment]
We don't auto populate query string when it contains line breaks, but you can still type in `\n` to trigger the query.
