### ISSUE TITLE
Allow to open non-text files via API

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#566]
_From @ArtemGovorov on November 17, 2015 3:8_

I can open an image (PNG) in the editor manually and there's `workspace.openTextDocument`, but, as expected from the function name, I can't use it to open the image file: `"cannot open file:///.... Detail: File seems to be binary and cannot be opened as text"`. Perhaps there should be another function, such as `openFile` that could open any supported file type?

_Copied from original issue: Microsoft/vscode-extensionbuilders#117_

**Comment by seanmcbreen** [comment]
_From @jrieken on November 18, 2015 13:16_

I like. Idea is to make the underlying command we already have so that it can accept an uri `executeCommand`

**Comment by thomas-jeepe** [comment]
Progress so far?

**Comment by newtack** [comment]
Wallabyjs offers the ability to display a screenshot of the last screen in the unit test in other GUIs (WebStorm, etc.). We really want this functionality in our preferred code editor VSCode as well.

**Comment by jrieken** [comment]
I'll see what June allows

**Comment by ArtemGovorov** [comment]
@jrieken Thanks! No rush, I think I found a good alternative by essentially wrapping the image into an HTML page and displaying the HTML document with the `vscode.previewHtml` command (and custom content provider).

![vsc](https://cloud.githubusercontent.com/assets/979966/15530755/9ca76c7e-2299-11e6-810b-605beaad59dd.gif)

**Comment by jrieken** [comment]
`previewHtml` FTW

**Comment by thomas-jeepe** [comment]
Awesome!

**Comment by newtack** [comment]
Fantastic!

**Comment by jrieken** [comment]
@bpasero Is this low hanging? Can I use the usual trick with a ResourceEditorInput?

**Comment by bpasero** [comment]
No, because it's `resolve` method will try to make a text editor model out of it (https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/common/editor/resourceEditorInput.ts#L159)

**Comment by bpasero** [comment]
But from the workbench point of view you can pass in a `file:///` URI pointing to an image and it will open as image. So I think everything should just work if you end up calling `IEditorService.openEditor`.
