### ISSUE TITLE
Split editor doesn't work for webview view

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#56602]
- VSCode Version: 1.27.0 Insider
- OS Version: macOS High Sierra

Steps to Reproduce:

1. Run https://github.com/Microsoft/vscode-extension-samples/tree/master/webview-sample
2. Split Editor (Cmd + /) on the webview
3. Right side becomes an empty pane

![image](https://user-images.githubusercontent.com/4033249/44232440-eae57b00-a155-11e8-96bc-a51ac2f78392.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bpasero** [comment]
Because they opt out: [`supportsSplitEditor`](https://github.com/Microsoft/vscode/blob/fd610b4b6ab8d4735a4d84a2b59206ad3a9c8099/src/vs/workbench/parts/webview/electron-browser/webviewEditorInput.ts#L224)

**Comment by mjbvz** [comment]
This is by design. A webview is a single instance of an editor (backed by a single webview object held onto by the extension). If they could be split, the split webview would not be owned by the extension
