### ISSUE TITLE
[diffEditor] TS imports not resolved in one side of the diff editor when comparing with previous revision

### ISSUE THREAD

**Issue by ryenus** [Microsoft/vscode#56608]
- VSCode Version: 1.26.0
- OS Version: macOS 10.13.6

Steps to Reproduce:

1. open a `.ts` file
2. compare with its previous revision

![image](https://user-images.githubusercontent.com/610161/44235664-de583580-a1dc-11e8-90c6-4ec5d23dd440.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by sandy081** [comment]
Are you using an extension to compare it?

**Comment by ryenus** [comment]
That's right, I'm using GitLens.

Maybe the problem is because GitLens extracted the previous revision into a temporary dir, from where the imports using relative paths couldn't be resolved?

**Comment by sandy081** [comment]
Could be, please file an issue against Gitlens extension
