### ISSUE TITLE
Commands on terminal keeps active after closing

### ISSUE THREAD

**Issue by box3x4** [Microsoft/vscode#56603]
- VSCode Version: 1.26
- OS Version: Ubuntu 18.04.1

Steps to Reproduce:

1.Execute some command like 'ng serve' or 'node index.js' on the VS Code terminal
2.Close VS Code without ending the command
3.Command is still active, and has to be killed using killall via terminal

Does this issue occur when all extensions are disabled?: Yes

I don't know if this expected, but it's kind of annoying. Maybe it can be a feature if it's expected.

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
