### ISSUE TITLE
Launch Webview multiple times will pollute the Quick Open view

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#56601]
- VSCode Version: 1.26.1
- OS Version: macOS High Seirra

![image](https://user-images.githubusercontent.com/4033249/44232129-fd12e980-a154-11e8-97c7-7fd72e5ad3fc.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
This is caused by ea0315e54a350f0b4dcc1c2a9d3978c7451a45cc which reverted 37209a838e9f7e9abe6dc53ed73cdf1e03b72060

@bpasero What is the right fix here? Closed webviews should never be included in the recently opened list. Is there a way to remove the entry from the list when a webview editor is closed?

**Comment by bpasero** [comment]
@mjbvz something must be different for that "Coding Cat" example compared to a markdown preview (which also uses webview). Typically an entry in the history is removed when its input gets closed and thereby disposed:

https://github.com/Microsoft/vscode/blob/d8b0484dc878825898819bbc9d55578e5d3816d5/src/vs/workbench/services/history/electron-browser/history.ts#L424

A reproducible case would be helpful.

**Comment by bpasero** [comment]
@octref I can reproduce now.

@mjbvz the history uses the EditorInput.matches() method to compare entries. It looks like the check if very weak for webview editors and should probably take into account more state (like the resource URI).

![image](https://user-images.githubusercontent.com/900690/44350624-235fbe80-a4a0-11e8-9b93-ebbda54400c4.png)

**Comment by bpasero** [comment]
@mjbvz yeah sounds good

**Comment by bpasero** [comment]
As discussed, a possible solution is:
* implement `matches()` properly by checking for the ID
* serializing the ID down and restore it after restart
