### ISSUE TITLE
allow splitting [ problems, output, debug console, terminal ] panels / tabs

### ISSUE THREAD

**Issue by ilovett** [Microsoft/vscode#56606]
This would allow me to be able to view Debug Console and Terminal at the same time without having to switch between panel tab.

Use case:

1. run my test with debugging in the terminal
2. attach to debugging node process in vscode debugger
3. view test results & debug tests at the same time instead of switching between those tabs

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/11889
