### ISSUE TITLE
Breadcrumbs popup not using `widget.shadow` for its shadow

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#56604]
The breadcrumbs popup isn't using the theme `widget.shadow` for its shadow, so on very dark themes it can be hard to see.

**Comment by jrieken** [comment]
<img width="369" alt="screen shot 2018-08-17 at 09 54 04" src="https://user-images.githubusercontent.com/1794099/44254576-7ec15080-a203-11e8-81bd-35d94bc0ff6d.png">
