### ISSUE TITLE
Find In Files > Ability to "Collapse All" found result nodes 

### ISSUE THREAD

**Issue by emveeoh** [Microsoft/vscode#56600]
When performing a FIND IN FILES search, the found result nodes are automatically expanded. This is very nice feature! Please give us a quick way to collapse/close all nodes. 

Ideally, it might be a simple "Collapse All" button like you have on the File Explorer, or a menu item to "Collapse All".

Thank you for the consideration!

**Comment by roblourens** [comment]
![image](https://user-images.githubusercontent.com/323878/44243274-0915a000-a183-11e8-920b-ff072c59b313.png)

Did you see the middle button in the top right?

**Comment by emveeoh** [comment]
@roblourens  Thank you sir! Sorry to waste your time with this, but I appreciate the help.
