### ISSUE TITLE
WSL launched as a teminal in VS code is really slow 

### ISSUE THREAD

**Issue by thkrishn** [Microsoft/vscode#56609]
- VSCode Version:  1.26
- OS Version: Win 10 

Steps to Reproduce:

1. in the settings change the integrated terminal to WSL
2. launch terminal ctrl + ` 

Seems to be slow since very recently , if the WSL is used locally its more responsive than through VS code

**Comment by thkrishn** [comment]
I have tried both modes and auto in the settings

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

https://github.com/Microsoft/vscode/issues/56628
