### ISSUE TITLE
Settings search box missing border

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#56618]
Hey @JacksonKearl, I started fixing this by making SuggestEnabledInput themeable in sort of the same way InputBox is but ended up with some questions. Is there a reason why SuggestEnabledInput extends `Component` or is it ok if I change that?

A Component is a `Themeable` then there is also `IThemeable` which is not related to that. Seems like Components are larger parts of the workbench, but input controls and things like that are usually Widgets. So I think I want to make this a Widget and style it with a styler.

1.27:
![image](https://user-images.githubusercontent.com/323878/44243325-67428300-a183-11e8-8b06-4a0671bfe5b0.png)

1.26:
![image](https://user-images.githubusercontent.com/323878/44243338-79bcbc80-a183-11e8-8ad7-6e064b4c408a.png)

**Comment by JacksonKearl** [comment]
Sorry what is the issue being referenced here? I thought #56175 but that should have been fixed in #56177.

**Comment by JacksonKearl** [comment]
As for `Component` vs `Widget` I have no preference, I picked what seemed to make sense at the time.

**Comment by roblourens** [comment]
I just added screenshots, sorry

**Comment by roblourens** [comment]
Light+ theme

**Comment by JacksonKearl** [comment]
Looks like this is the culprit:
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/preferences/browser/media/preferences.css#L180

As the existing behavior is a fixed CSS rule that only applies to that particular input on that particular theme, I feel like the right fix is to just add a similar rule but with the new selectors. What do you think?

**Comment by roblourens** [comment]
Oh, I assumed it was from the theme token. Good catch. Yeah I'll add a rule.
