### ISSUE TITLE
String does not match the pattern

### ISSUE THREAD

**Issue by henriquesqs** [Microsoft/vscode#56613]
Issue Type: <b>Bug</b>

Hello, I keep receiving this error from c_cpp_properties.json .vscode file: 
"String does not match the pattern of "^\d{2}\.\d{1}\.\d{5}\.\d{1}$|^8\.1$"."

I do not have any ideias about what I have to do. May you please help me?

![image](https://user-images.githubusercontent.com/36971021/44241319-851ae280-a199-11e8-9030-2bc2a3407d40.png)

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 10.0.17134

**Comment by roblourens** [comment]
It looks like the cpp extension requires that property to be a value that matches that regex. Looks like it should be a valid version number. You should file an issue on the cpp extension if you think that message is in error.
