### ISSUE TITLE
Release notes content not loading after application update 

### ISSUE THREAD

**Issue by jimtryon** [Microsoft/vscode#56616]
Issue Type: <b>Bug</b>

I attempted to update VS Code by clicking on the Code dropdown, selecting Check for Updates, and waiting for VS code to restart.  I expected that after the restart the Release Notes would load in a separate tab and allow me to scroll through the release notes to see the new features and changes as it worked in the previous version. Instead what happens is the Release Notes tab will load, but none of the content is loading in the tab and VS Code will freeze or hang. I wait a few minutes for the tab to finish loading and then I close the tab after it does not load any content. 

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:20:44.170Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 5|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_1077511|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|8.0.0
color-info|bie|0.5.0
bracket-pair-colorizer|Coe|1.0.59
jshint|dba|0.10.19
vscode-eslint|dba|1.4.12
githistory|don|0.4.2
gitlens|eam|8.5.4
prettier-vscode|esb|1.6.1
code-runner|for|0.9.4
beautify|Hoo|1.3.2
color-highlight|nau|2.3.0
indent-rainbow|ode|7.2.2
polacode|pnp|0.2.2
vscode-css-peek|pra|2.1.0
java|red|0.29.0
vscode-icons|rob|7.25.0
open-in-browser|tec|2.0.0
highlight-matching-tag|vin|0.4.4
vscode-java-debug|vsc|0.11.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.8.0
vscode-maven|vsc|0.10.0
vscode-wakatime|Wak|1.2.3
ReactSnippets|xab|2.2.0
html-css-class-completion|Zig|1.17.1

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
Did you have any Python or PowerShell files opened when VS Code is restarted?

**Comment by jimtryon** [comment]
I did not have any other files opened when I restarted VS Code.

**Comment by joaomoreno** [comment]
Are you behind a proxy? Does Code run fine now? Can you run `Show Release Notes` from the command palette?

**Comment by jimtryon** [comment]
I am not behind a proxy. Code updated to 1.2.1 and has a tab in the editor for release notes but there is no text. I ran the command Show Release Notes and it produced the same result.
<img width="1279" alt="screen shot 2018-09-03 at 2 07 43 am" src="https://user-images.githubusercontent.com/8931936/44977894-318cf080-af1e-11e8-828f-3e176b0cafae.png">

**Comment by joaomoreno** [comment]
The screenshot shows the fully expanded Problems panel. Can you close it and screenshot it again?

**Comment by jimtryon** [comment]
So the issue was that I dd not close the Problems panel and the release notes were hidden from view.
