### ISSUE TITLE
Extension logs should share editor rules with application logs

### ISSUE THREAD

**Issue by nealot** [Microsoft/vscode#56615]
Presently, to modify the language settings for the extension output logs you need to use:
```json
"[Log]": {"editor.fontSize": 12}
```
But to modify the application logs (mainLog, sharedLog, windowLog, and extHostLog) you have to use:
```json
"[log]":{"editor.fontSize": 12}
```
Why is the the capital required in the first case? The actual files are using the .log extension so this is strange.

**Comment by sandy081** [comment]
log files have their own tokenisation(colour) and hence they have a unique languageId `log`. Using the same languageId for all will break other output channels.

See #43271
