### ISSUE TITLE
code folding trouble in php source.

### ISSUE THREAD

**Issue by shuaihuGao** [Microsoft/vscode#56620]
code folding will end at PHP Heredoc string.
sample::
```
public function querymenu()
-	{
		$con=$this->conn;
		$sql=<<<'SQL'
		select distinct m.pgm_id,m.pgm_nm_cn,m.pgm_parent,m.startparam,
		A.CHK_DOSEARCH search,
		A.CHK_DONEW "ADD",
		A.CHK_DOSAVE save,
		A.CHK_DODELETE remove,
		level
		from tb_cm_m_menu m,
			 tb_cm_m_authpgm a
		WHERE M.PGM_ID=A.PGM_ID(+)
		AND '20070350'=A.user_id(+)
		and m.pgm_id<>'root'
		START WITH a.CHK_DOSEARCH='Y'
		connect by nocycle  prior m.pgm_parent=m.pgm_id
		order by level desc,pgm_parent,pgm_id
SQL; //Will End At here
		$stmt=oci_parse($con,$sql);
		oci_execute($stmt);
		$rowcnt=oci_fetch_all($stmt,$data,null,null,OCI_FETCHSTATEMENT_BY_ROW);
		oci_free_statement($stmt);
		return $data;
	}

```

after close:

```

public function querymenu()
 +	{
SQL; 

		$stmt=oci_parse($con,$sql);
		oci_execute($stmt);
		$rowcnt=oci_fetch_all($stmt,$data,null,null,OCI_FETCHSTATEMENT_BY_ROW);
		oci_free_statement($stmt);
		return $data;
	}

```

**Comment by roblourens** [comment]
@aeschli I can't find the issue for this but I assume there is one?

**Comment by CallMeR** [comment]
@roblourens  If there is a space in front of the code “SQL; //Will End At here”  ，the bug will not triggered.

**Comment by aeschli** [comment]
By default we only offer folding based on indentation.
To have language aware folding, a PHP extension is required that implements a PHP folding provider.
I see that such a request has been filed against vscode-php-intellisense: https://github.com/felixfbecker/vscode-php-intellisense/issues/311 and PHP intelephense: https://github.com/bmewburn/vscode-intelephense/issues/99

**Comment by shuaihuGao** [comment]
thanks.

**Comment by peon501** [comment]
@shuaihuGao 
Dude, we are in the same boat. Will probably take ages for someone to implement this :older_man:
