### ISSUE TITLE
Decorations not visible on High Contrast theme

### ISSUE THREAD

**Issue by shardulm94** [Microsoft/vscode#5662]
- VSCode Version: 1.0.0
- OS Version: Windows 7

Steps to Reproduce:

1.Create a decoration for a range with the following `DecorationRenderOptions`

```
{
    borderRadius: "3px",
    borderWidth: "1px",
    borderStyle: "solid",
    backgroundColor: "rgba(255,0,0,0.3)",
    borderColor: "rgba(255,100,100,0.15)"
}
```

2.Switch to the `High Contrast` theme.

The decorations are no longer visible. Not sure if this is by design.

**Comment by dbaeumer** [comment]
@waderyan assigning to you. ChrisS designed the High Contrast theme. I don't know what the rules are in terms of decorations and high contrast. Is it a must that they are showing?

**Comment by waderyan** [comment]
Thanks @dbaeumer. I believe @bgashler1 did some work here. Maybe he can give us some help?

**Comment by shardulm94** [comment]
Not sure if work was done on this, but I can now see the decorations in the High Contrast Theme (as of v1.13.0).

**Comment by misolori** [comment]
This appears to be fixed, I've verified below using the "TODO" extension:

![image](https://user-images.githubusercontent.com/35271042/45390545-87276400-b5d4-11e8-9fd5-1d915133fe7f.png)
