### ISSUE TITLE
File specific pre-defined actions should be available upon right-clicking that file.

### ISSUE THREAD

**Issue by paritosh149** [Microsoft/vscode#56629]
In version 1.26, a feature is present to "Run Script" upon right-clicking sub-properties of "scripts" property inside package.json.
I suggest that all the actions should be made available in Left Explorer Pane. It should work in following manner;
1. Right-click package.json file name in Explorer pane.
2. Along with other actions already displayed, there should be group of action items (example, Run 'start' script, Run 'test' script, etc.).
3. This group should be based on the available sub-properties of "scripts" property inside package.json.

**Comment by egamma** [comment]
@paritosh149 have you tried to enable the [NPM Script explorer](https://code.visualstudio.com/updates/v1_23#_npm-script-running). It does all that and more. 

Not convinced yet that it makes sense to duplicate this in the Explorer.

**Comment by paritosh149** [comment]
@egamma, seems like I didn't keep track of [NPM Script Explorer](url). I tried it and I find it perfect fit for my script execution launching needs. Thanks.
