### ISSUE TITLE
Laggy Terminal

### ISSUE THREAD

**Issue by prashksingh** [Microsoft/vscode#56628]
Issue Type: <b>Bug</b>

Extremely laggy terminal after the last update. Not sure if this is because of some extension? 

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|15.87GB (7.85GB free)|
|Process Argv|C:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.7.1

</details>

**Comment by choeffer** [comment]
https://github.com/Microsoft/vscode/issues/56563 same here

**Comment by Tyriar** [comment]
It's because of the Chromium upgrade, workaround is to launch with `code --ignore-gpu-blacklist`

**Comment by Tyriar** [comment]
Actually there was a bad regression recently separately to the Electron change. I'll use this issue to track this one. https://github.com/xtermjs/xterm.js/issues/1620

**Comment by fractos** [comment]
Any word on this? I'm on 1.27.2 (windows 10) and seeing a 1000 line or so terraform operation in git-bash lock up across two separate Code instances, plus getting the dialog saying window is not responding in both instances. Very really not good.

**Comment by Tyriar** [comment]
@fractos you're probably seeing issues with electron's canvas acceleration, see https://github.com/Microsoft/vscode/issues/56517

**Comment by Tyriar** [comment]
I'm locking this as this specific issue is fixed, see https://github.com/Microsoft/vscode/issues/56517 for GPU rendering slowness.
