### ISSUE TITLE
Add a setting to disable back/forward with mouse buttons 4/5

### ISSUE THREAD

**Issue by ShadowRanger** [microsoft/vscode#56627]
One of the main reasons that I can't use Visual Studio Code is because my push to talk key for voice programs is Mouse Button 4. In Visual Studio Code, this switches between code windows. I have not had this issue with other Electron based code editors so it would be great to see an option to toggle this feature on or off.

**Comment by bpasero** [comment]
We do not specifically enable this behaviour so I can only speculate that this is a OS setting or mouse driver related.

**Comment by ShadowRanger** [comment]
Just to confirm, the forward and back functionality of mouse button 4 and 5 isn't something that is part of Visual Studio Code or Electron that can be controlled by Visual Studio Code?

**Comment by ShadowRanger** [comment]
@bpasero Could you please confirm the above question?

**Comment by bpasero** [comment]
@ShadowRanger I guess you do not mean "window" switching but "editor" switching? It is true that VS Code installs a listener for mouse buttons 4 and 5 to change editors and this is currently not configurable.

**Comment by ShadowRanger** [comment]
@bpasero Yes that is correct. For me to suggest for that to become configurable, should I create another  suggestion issue?

**Comment by bpasero** [comment]
Ok then lets reopen this one.

**Comment by bpasero** [comment]
Added a new setting: `workbench.editor.mouseBackForwardToNavigate`

via https://github.com/microsoft/vscode/commit/6c61f43084d7d659665b460d85ccd18897e4088c
