### ISSUE TITLE
Some Korean Character is not displayed properly

### ISSUE THREAD

**Issue by tlsdmstn56** [Microsoft/vscode#56631]
- VSCode Version: 1.26.0
- OS Version: Linux 4.15.0-30-generic#32-Ubuntu SMP x86\_64

Steps to Reproduce:

1. Change input source in Korean.
2. Press r (ㄱ) + k(ㅏ) + x(ㅌ)

Then it supposed to be displayed as '같' not '가ㅌ'(not properly composed)
Does this issue occur when all extensions are disabled?: Yes

I usually write markdown file for posting the article in my jekyll blog so it is very difficult.

I think writing file is okay because when the markdown file is properly displayed in my website even though the file is displayed in 가ㅌ in vscode editor.

Last year, I believe there was no issue in displaying Korean characters but one day this issue just occured.

I have been waiting for several month but still it does not fixed. Also, nobody report this bug on the github so I am writing this bug report.

Thank you :)

**Comment by tlsdmstn56** [comment]
I just found similar bug.

가ㅁ:  r (ㄱ) + k(ㅏ) + a(ㅁ)    // supposed to be '감'
가ㄴ:  r (ㄱ) + k(ㅏ) + s(ㄴ)    //supposed to be '간'

I think there might be bug after inputting r (ㄱ) + k(ㅏ)

**Comment by rebornix** [comment]
Can't reproduce this issue on Windows and macOS. Probably a Linux specific issue.

**Comment by tlsdmstn56** [comment]
@rebornix 
Thank you!
And yes, you are right. In my mac book, the issue could not be reproduced and Windows could not.

**Comment by rebornix** [comment]
@tlsdmstn56  can you confirm it might be the same as https://github.com/Microsoft/vscode/issues/10769 ?

**Comment by tlsdmstn56** [comment]
Yes, that is the same issue. It is not vscode's problem. Thank you! I will check ime and find other ways to fix it.
