### ISSUE TITLE
Autoupdate persists 

### ISSUE THREAD

**Issue by tomas-paronai** [Microsoft/vscode#56643]
Issue Type: <b>Bug</b>

I am having some issues with extensions on the latest 1.26 release. I downloaded 1.25.1 and downgraded. I have turned off autoupdates in user settings:
`"update.channel": "none"`,
`"update.enableWindowsBackgroundUpdates": false`

After mac restart it updated to 1.26. 
Please fix this or provide a solution how to disable autoupdates.
Thank you.

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:20:44.170Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 8, 4|
|Memory (System)|16.00GB (7.57GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
gherkin-indent|Ara|2.0.0
solargraph|cas|0.17.6
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.12
vscode-babel-coloring|dza|0.0.4
gitlens|eam|8.5.4
react-native-react-redux|EQu|1.9.1
json-tools|eri|1.0.2
flow-for-vscode|flo|0.8.2
auto-close-tag|for|0.5.6
graphql-for-vscode|kum|1.12.1
Arduino|moo|0.0.4
cpptools|ms-|0.17.7
platformio-ide|pla|0.17.4
ruby|reb|0.20.0
java|red|0.29.0
prettier-now|rem|1.4.9
vscode-java-debug|vsc|0.11.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.8.0
vscode-maven|vsc|0.10.0
vscode-react-native|vsm|0.6.13
vscode-yseopml|Yse|1.1.0

</details>

**Comment by joaomoreno** [comment]
This will definitely do it: "update.channel": "none"

After changing that setting, re-download 1.25 and it will not update.

**Comment by tomas-paronai** [comment]
@joaomoreno Why close? 
I **have** "update.channel": "none" in suer settings and it does update.

**Comment by joaomoreno** [comment]
I do believe you updated that value once it was already too late and Code was already downloading 1.26 in the background once again. That's why I suggest to keep that setting and reinstall 1.25... I believe it will not update, once it starts up with that setting in place.
