### ISSUE TITLE
cup内存爆炸

### ISSUE THREAD

**Issue by trj-web124** [Microsoft/vscode#56642]
Issue Type: <b>Bug</b>

更新IDE之后  打开内存100%  卡的很  希望检测下 谢谢

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (2.64GB free)|
|Process Argv|C:\Users\Dell\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-standardjs-snippets|cap|0.7.7
vscode-standardjs|che|1.2.3
vscode-wxml|cod|0.1.9
vscode-html-css|ecm|0.2.0
EditorConfig|Edi|0.12.4
vscode-element-helper|Ele|0.5.3
prettier-vscode|esb|1.6.1
autofilename|Jer|0.1.3
vscode-scss|mrm|0.6.2
vscode-language-pack-zh-hans|MS-|1.26.3
vetur|oct|0.12.6
vscode-css-peek|pra|2.1.0
view-in-browser|qin|0.0.5
prettier-now|rem|1.4.9
vscode-icons|rob|7.25.0
open-in-browser|tec|2.0.0

(4 theme extensions excluded)

</details>

**Comment by CallMeR** [comment]
-.- 这个描述亮了
你内存“爆炸”在Vscode执行什么阶段的什么操作时候啊？

**Comment by sandy081** [comment]
Can you please provide the issue summary and description in English?

**Comment by 456wyc** [comment]
我也是，更新之后，一打开文件，我的 chrome 就会被干崩溃或者卡死

**Comment by 456wyc** [comment]
@CallMeR 我也遇到了，我反复尝试了好几次，都是在打开项目文件夹的时候，会有一个 Code Helper 经常占用的内存很高，我每次一打开文件夹，我的 chrome 就会收影响，真正播放视频的网页就会崩溃，有时候系统也会很卡。我用的是 MacBook pro ，系统版本 10.13.6 , vscode 版本是1.26.1

**Comment by 456wyc** [comment]
@sandy081
I had the same problem when I upgraded to version 1.26.1.
I've tried this many times, and whenever I open a project folder with it, there's a code helper process that takes up a lot of memory, which causes my chrome to crash and my system to slow down.

**Comment by sandy081** [comment]
Does this happen with empty window or with a file opened?
Also please check if you can reproduce it by disabling all extensions?

And finally

Please follow this guide (https://github.com/Microsoft/vscode/wiki/Performance-Issues#visual-studio-code-starts-up-slowly) and attach the CPU profiles you get when starting with `--prof-startup`

**Comment by CallMeR** [comment]
- VSCode Version: <code>Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:34:20.517Z)</code>
- OS Version: <code>Linux x64 4.14.65-1-MANJARO</code>
- CPUs: <code>Intel(R) Pentium(R) CPU G2030 @ 3.00GHz (2 x 2977)</code>
- Memory (System): <code>7.69GB (1.29GB free)</code>
- Memory (Process): <code>198.70MB working set (230.81MB peak, 120.90MB private, 77.81MB shared)</code>
- Load (avg): <code>1, 1, 1</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|56|
|main|app.isReady => window.loadUrl()|545|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|243|
|renderer|require(workbench.main.js)|1569|
|renderer|create extension host => extensions onReady()|1149|
|renderer|restore viewlet|0|
|renderer|restore editor view state|1|
|renderer|overall workbench load|235|
|main + renderer|start => extensions ready|3598|
|main + renderer|start => workbench ready|2671|

---
[4c24-exthost.cpuprofile.txt](https://github.com/Microsoft/vscode/files/2323346/4c24-exthost.cpuprofile.txt)
[4c24-main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/2323356/4c24-main.cpuprofile.txt)
[4c24-renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/2323348/4c24-renderer.cpuprofile.txt)

**Comment by CallMeR** [comment]
An other output,with my laptop,opened a txt file...

- VSCode Version: <code>Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:34:20.517Z)</code>
- OS Version: <code>Linux x64 4.15.0-29deepin-generic</code>
- CPUs: <code>Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz (4 x 3397)</code>
- Memory (System): <code>7.48GB (5.63GB free)</code>
- Memory (Process): <code>232.43MB working set (241.46MB peak, 145.26MB private, 87.19MB shared)</code>
- Load (avg): <code>1, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|48|
|main|app.isReady => window.loadUrl()|398|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|265|
|renderer|require(workbench.main.js)|1336|
|renderer|create extension host => extensions onReady()|3284|
|renderer|restore viewlet|0|
|renderer|restore editor view state|734|
|renderer|overall workbench load|1010|
|main + renderer|start => extensions ready|5363|
|main + renderer|start => workbench ready|3078|

---
[3f4c-exthost.cpuprofile.txt](https://github.com/Microsoft/vscode/files/2323403/3f4c-exthost.cpuprofile.txt)
[3f4c-main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/2323406/3f4c-main.cpuprofile.txt)
[3f4c-renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/2323408/3f4c-renderer.cpuprofile.txt)

**Comment by sandy081** [comment]
@CallMeR May I know what is the issue you are seeing? Is the start up slow or there is a crash or VS Code hangs?

**Comment by CallMeR** [comment]
@sandy081    When opened a folder which contents some other folder or files ，reopen vscode will be slow at startup.

**Comment by sandy081** [comment]
@CallMeR Sorry not sure if I understand your scenario... Can you please provide a screencast which will be helpful to understand?
