### ISSUE TITLE
Removing entries from "Recently opened" picker closes the picker

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#56648]
- VSCode Version: 1.27 insiders
- OS Version: macOS

Steps to Reproduce:

1. open the recently opened quick pick
2. remove files by clicking on the "X" multiple times

=> 🐛 at random times the picker decides to close

**Comment by chrmarti** [comment]
When you click quickly the first click triggers the toolbar item and the second triggers a double click event in the list widget which then triggers a selection change that makes the picker close with the selected item as the result.

@joaomoreno Any ideas? Should we add an option to the list widget to disable selection on double click?

**Comment by joaomoreno** [comment]
> When you click quickly the first click triggers the toolbar item and the second triggers a double click event in the list widget

It sounds like the event shouldn't even reach the list, if it is supposed to be handled by the toolbar. The toolbar action should `stopPropagation`.

**Comment by chrmarti** [comment]
ActionBar already stops propagation: https://github.com/Microsoft/vscode/blob/43676d0cb7db94e2fa771f1d10bff10eaa01b453/src/vs/base/browser/ui/actionbar/actionbar.ts#L126

That does not seem to affect the double click event, which is listened on here: https://github.com/Microsoft/vscode/blob/43676d0cb7db94e2fa771f1d10bff10eaa01b453/src/vs/base/browser/ui/list/listWidget.ts#L455

**Comment by joaomoreno** [comment]
The event which needed to stop propagation was `dblclick`.
