### ISSUE TITLE
autocomplete start working

### ISSUE THREAD

**Issue by shahjehanali1** [Microsoft/vscode#56640]
We have written the needed data into your clipboard because it was too large to send. Please paste.

CPUs | Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (8 x 2594)
-- | --
GPU Status | 2d_canvas: enabledchecker_imaging: disabled_offflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwarerasterization: enabledvideo_decode: enabledvideo_encode: enabledwebgl: enabledwebgl2: enabled
Memory (System) | 15.93GB (6.68GB free)
Process Argv | C:\Users\SHAHJEHAN\AppData\Local\Programs\Microsoft VS Code\Code.exe
Screen Reader | no
VM | 0%

html-snippets | abu | 0.2.1
-- | -- | --
vscode-css-formatter | aes | 1.0.1
vscode-caniuse | aka | 0.5.3
vs-code-css-comments | ash | 1.0.5
htmltagwrap | bra | 0.0.7
php-autocomplete | bsc | 0.4.2
simple-react-snippets | bur | 1.2.2
vscode-css-modules | cli | 0.2.3
jshint | dba | 0.10.19
vscode-eslint | dba | 1.4.12
vscode-quick-select | dba | 0.2.6
githistory | don | 0.4.2
jquerysnippets | don | 0.0.1
gitlens | eam | 8.5.4
auto-rename-tag | for | 0.0.15
vscode-cdnjs | Jak | 0.14.3
auto-comment-blocks | kev | 1.0.1
expand-region | let | 0.1.2
vscode-scss | mrm | 0.6.2
node-debug2 | ms- | 1.27.0
sublime-keybindings | ms- | 4.0.0
team | ms- | 1.136.0
debugger-for-chrome | msj | 4.8.2
live-sass | rit | 3.0.0
LiveServer | rit | 5.1.1
sass-indented | rob | 1.4.9
vscode-idiomatic-css-comments | rya | 0.1.2
git-autoconfig | shy | 0.0.1
css-auto-prefix | spo | 0.1.7
open-in-browser | tec | 2.0.0
lorem-ipsum | Tyr | 1.2.0
vscode-jss-snippets | vis | 0.2.2
vscode-react-native | vsm | 0.6.13
html-css-class-completion | Zig | 1.17.1
vscode-open-in-github | ziy | 1.3.5

**Comment by shahjehanali1** [comment]
I'm stuck in auto complete

**Comment by sandy081** [comment]
Can you please explain more about the issue?

- Steps to reproduce with screenshots or gifs will be helpful.
