### ISSUE TITLE
How to pull from upstream and push to origin ?

### ISSUE THREAD

**Issue by raghav135** [Microsoft/vscode#5664]
- VSCode Version:1.0.0
- OS Version:windows

Steps to Reproduce:

1. Do a fork of a git repository
2. Clone the forked repository
3. add git remote of upstream as the original git repository

How do I pull from upstream and push to origin remote?

Tried searching documentation, couldn't find the way.

Kind Regards.

**Comment by joaomoreno** [comment]
As with every command in the workbench, the Command Pallette (<kbd>Ctrl Shift P</kbd> or <kbd>⌘ Shift P</kbd>) will let you find those:

![image](https://cloud.githubusercontent.com/assets/22350/14775806/fab84468-0ac1-11e6-9381-9f452cfe116a.png)

Additionally there are actions in the git view itself:

![image](https://cloud.githubusercontent.com/assets/22350/14775822/188dcd00-0ac2-11e6-93ba-469a6d0967c9.png)

Finally, the sync action in the status bar does a *pull + push* combination action:

![image](https://cloud.githubusercontent.com/assets/22350/14775832/2aecf476-0ac2-11e6-9618-0930f1d56948.png)

**Comment by raghav135** [comment]
My question was different. How will I pull from a remote1 and push to remote2.

**Comment by joaomoreno** [comment]
Not supported yet. I suggest to use the command line for that.

**Comment by adrianorc** [comment]
Is this features still not supported?

**Comment by joaomoreno** [comment]
Yes, still not supported.

**Comment by vijayst** [comment]
Atom had a git-control plugin which did it very well.
