### ISSUE TITLE
Git installation not found after updated to 1.26.0 or higher

### ISSUE THREAD

**Issue by TsumiNa** [Microsoft/vscode#56659]
- VSCode Version: ~1.26.0
- OS Version: MacOS High Sierra
- Git version: 2.18.0(using Homebrew installer)
- Shell: fish, version 2.7.1

Steps to Reproduce:

1. Update to 1.26.0 or higher.
2. Open VSCode.

This issue is not always reproducible. Sometimes but not always.

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by sandy081** [comment]
Thanks for nailing it down

**Comment by faustinoaq** [comment]
@TsumiNa I'll check this. Thanks for report this issue :+1:
