### ISSUE TITLE
Portable Mode create empty logs folder in %APPDATA%

### ISSUE THREAD

**Issue by zmni** [microsoft/vscode#56651]
- VSCode Version: 1.26.0
- OS Version: Windows 10 Enterprise 1803

Steps to Reproduce:

1. Download and extract VS Code 1.26.
2. Create `data` folder in VS Code's folder to enable Portable Mode.
3. Launch VS Code (Code.exe).
4. Logs folder created in `%APPDATA%\Visual Studio Code\logs`.

Does this issue occur when all extensions are disabled?: Yes

---

Update: Also occur in version 1.26.1 and windows 8.1 x64.

**Comment by joaomoreno** [comment]
Easily reproducible.

**Comment by joaomoreno** [comment]
Can't repro this with 1.25.

I'm 100% sure this happens at the Electron layer:

1. I've modified Code's `main.js` to simply and only call `console.log(fs.existsSync('path/to/that/folder'))` and it always returns true. That folder is created even before any JS runs.
2. I've modified Code's `main.js` to simply and only call `process.exit(0)` and still that folder gets created.

Seems to be an issue with Electron 2.

**Comment by bpasero** [comment]
I cannot reproduce with `electron-fiddle`, so we should find out what causes this from our code.

**Comment by joaomoreno** [comment]
I can repro this with vanilla Electron 2.0.5 on Windows:

1. Download and extract Electron 2.0.5 for Windows
2. Create the following files within:
    - `resources\app\package.json` with contents `{"main":"main.js"}`
    - `resources\app\main.js` with empty contents
3. Make sure `%APPDATA%\Electron` does not exist
4. Double click `electron.exe`

A wild `%APPDATA%\Electron` appears! :open_mouth: 

![pikachu](https://media.giphy.com/media/slVWEctHZKvWU/giphy.gif)

**Comment by bpasero** [comment]
@joaomoreno awesome, can you please report this to Electron and link the issue here?

**Comment by bpasero** [comment]
https://github.com/electron/electron/issues/14276

**Comment by joaomoreno** [comment]
@bpasero Did you test Electron 3?

**Comment by joernroeder** [comment]
@joaomoreno https://github.com/electron/electron/issues/14470#issuecomment-464517119
