### ISSUE TITLE
Toggle inner doc comment for Rust

### ISSUE THREAD

**Issue by jamesray1** [Microsoft/vscode#56655]
At the moment there are keyboard shortcuts for toggling a line comment, CTRL + /, and for toggling a block comment, CTRL + Shift + A. However, Rust has additional types of comments, such as [documentation comments](https://doc.rust-lang.org/book/2018-edition/ch14-02-publishing-to-crates-io.html#making-useful-documentation-comments), `///` and [inner doc comments](https://doc.rust-lang.org/book/2018-edition/ch14-02-publishing-to-crates-io.html#commenting-contained-items), `//!`. While I understand that enabling these by default in VS Code is probably not appropriate, since not everyone using VS Code uses Rust, it would be good if this could be enabled in settings such as in Keybindings, although I'm not sure what command you would use, and `when` you would use it.

**Comment by sandy081** [comment]
Please file an issue against Rust language extension
