### ISSUE TITLE
Previously open working files are not validated when reopening vscode

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#5665]
- VSCode Version: latest

Steps to reproduce:

```bash
mkdir temp
touch a b c
code .
```

- add `a`, `b` and `c` to working files
- close code

```bash
rm a
code .
```

Notice `a` is still in working files, clicking it results in a file not found error.

---

This happens most for me when I'm switching between branches, and forces me to clear out the working files manually.

**Comment by bpasero** [comment]
#4870
