### ISSUE TITLE
VS code can't connect to the internet 

### ISSUE THREAD

**Issue by youssefhad** [Microsoft/vscode#56657]
Issue Type: <b>Bug</b>

after migrating to user setup vscode can't connect to the internet

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (3.37GB free)|
|Process Argv|C:\Users\admin\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.0.3
spellright|ban|2.5.30
vscode-icontheme-nomo-dark|be5|1.3.6
gitlens|eam|8.5.4
php-debug|fel|1.12.4
php-intellisense|fel|2.3.3
vscode-mysql|for|0.3.0
vscode-icon-theme|jtl|1.6.2
php-symbols|lin|2.1.0
code-beautifier|mic|2.1.0
vscode-language-pack-fr|MS-|1.26.3
code-settings-sync|Sha|3.0.0
vscode-todo-highlight|way|1.0.4
vinala-ext|You|0.2.5

(1 theme extensions excluded)

</details>

**Comment by youssefhad** [comment]
I can't reach to the extension store or install new extension
![capturet](https://user-images.githubusercontent.com/10350147/44258264-57b84e00-a206-11e8-9d5e-f6cbaec1ac92.PNG)

**Comment by joaomoreno** [comment]
Are you behind a proxy? If you try to search for an extension, what happens?

**Comment by youssefhad** [comment]
no i'm not using any proxy,
when i try to search for an extension it give the messege "No extensions found",
the reboot solves the problem but only for one search of extension, then it give the same message,
that's only happend when i migrate to user setup

**Comment by joaomoreno** [comment]
Can you uninstall the User Setup and install the System Setup and see whether that fixes it?

**Comment by youssefhad** [comment]
yes, i uninstall the user setup and try the system setup, and it works .

**Comment by joaomoreno** [comment]
What if you download the ZIP release? Does that work?

**Comment by joaomoreno** [comment]
Did you have to, at some point, have to allow Code.exe to access network requests? Does it work if you disable firewall/network blocker tool?

**Comment by youssefhad** [comment]
i use both the user setup and the zip release in other computer and it works great , i guess the problem was in firewall even if it never show any request to use Code

**Comment by joaomoreno** [comment]
Yup, firewall sounds more and more like the culprit here. Let us know if you find any more details.
