### ISSUE TITLE
Do not use deprecated logger API

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#56658]
@jrieken removed this morning the `Logger` API via 1c72ab243c302f2d69551077c1be1d13f04101d8
This casued debugging to no longer work - just start debugging and you would get an exception (out of source).

The issue is that node-debug2 depends on the Logger which is proposed api. There are alternative solutions which we could use.
Also adding @weinand in case he is using the Logger in his extensions

Assigning to August since we should tackle this this week hopefully. If you do not have time let me know and I can look into it.
Once this is done, @jrieken can remove the Logger, for now we have reverted the change that removes the `Logger`

**Comment by weinand** [comment]
Both node debuggers use the proposed logger API.

Since the [plan](https://github.com/Microsoft/vscode/pull/43276#issuecomment-373446670) is to move the logger API from the extensionContext to the output channel, we'll have to wait for this adoption until the API becomes available at the new location.

**Comment by jrieken** [comment]
> we'll have to wait for this adoption until the API becomes available at the new location.

You can use `appendLine` already today

**Comment by roblourens** [comment]
Node2 doesn't use that logger API. We have our own logger that runs in the DA and writes to a file. We only use the logDirectory property which is becoming stabilized.

**Comment by roblourens** [comment]
node-debug does use the logger: https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/extension/configurationProvider.ts#L88

**Comment by weinand** [comment]
I've moved node-debug off the Logger API.
