### ISSUE TITLE
Quick Open: unhappy spread of highlight in this case

### ISSUE THREAD

**Issue by ris58h** [Microsoft/vscode#56667]
Expected highlighting: src/vs/editor/contrib/**smartSelect**
Actual highlighting: **s**rc/vs/editor/contrib/s**martSelect**

![vscode-quick-open-problem](https://user-images.githubusercontent.com/511242/44261778-606a4d80-a221-11e8-928c-631900a33b55.png)

- VSCode Version: 1.26.0
- OS Version: Ubuntu 18.04.1 LTS

**Comment by bpasero** [comment]
This is an unfortunate consequence of giving characters that match in the beginning of words a high bonus:

https://github.com/Microsoft/vscode/blob/e1a1e6d6d4e1e64fba2cad3aafbfe5bbc5571824/src/vs/base/parts/quickopen/common/quickOpenScorer.ts#L185

**Comment by bpasero** [comment]
Closing as designed, not planning to change this to avoid regressions in other places of the scoring.
