### ISSUE TITLE
Tree: multiple delayed expand calls can clash

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#56665]
From https://github.com/Microsoft/vscode-pull-request-github/issues/36

1. Install https://github.com/Microsoft/vscode-pull-request-github
2. Setup auth
3. Expand `Assigned to Me`
4. Click the `Refresh` icon of the `Github Pull Requests` and quickly click twice on one of the PRs

There will be duplicated entries in the tree. Worse, when collapsing the PR, half of them will stay in the DOM. :fearful:

**Comment by bpasero** [comment]
That issue seems fine, but doing some more crazy refresh/expand things I see this:

![image](https://user-images.githubusercontent.com/900690/44857063-455efb00-ac6f-11e8-8b9a-b09beb0b7cfe.png)

//cc @rebornix @RMacfarlane
