### ISSUE TITLE
Hang when while navigating through File menu in newly opened second instance that was not fully loaded yet

### ISSUE THREAD

**Issue by CherryDT** [Microsoft/vscode#56668]
Issue Type: <b>Bug</b>

I encountered an issue that I cannot reproduce, and I know it was in a version that's not the latest, but maybe this problem is interesting for you anyways.

I had opened an instance of VSCode with a project and then I used File->New Window. The new window was not fully loaded yet, but I already clicked File->Recent and then both VSCode windows became frozen.

Looking at the stack of the hung thread, I got this:

```
0, ntoskrnl.exe!IoGetRelatedDeviceObject+0x811
1, ntoskrnl.exe!KeWaitForSingleObject+0x1521
2, ntoskrnl.exe!KeWaitForSingleObject+0xadb
3, ntoskrnl.exe!KeWaitForMultipleObjects+0x467
4, ntoskrnl.exe!ObWaitForMultipleObjects+0x2a0
5, ntoskrnl.exe!ObReferenceObjectByHandle+0x787
6, ntoskrnl.exe!setjmpex+0x6ea3
7, ntdll.dll!ZwWaitForMultipleObjects+0x14
8, KernelBase.dll!WaitForMultipleObjectsEx+0xf9
9, KernelBase.dll!WaitForMultipleObjects+0xe
10, kernel32.dll!WerpLaunchAeDebug+0x27db
11, kernel32.dll!WerpLaunchAeDebug+0x228c
12, KernelBase.dll!UnhandledExceptionFilter+0x35b
13, ntdll.dll!memset+0x1c57
14, ntdll.dll!_C_specific_handler+0x96
15, ntdll.dll!_chkstk+0x11d
16, ntdll.dll!RtlWalkFrameChain+0x13f6
17, ntdll.dll!KiUserExceptionDispatcher+0x2e
18, Code - Insiders.exe!GetHandleVerifier+0xda5104
19, Code - Insiders.exe+0x2c524f
20, vcruntime140.dll!purecall+0x34
21, Code - Insiders.exe!GetHandleVerifier+0x12258bf
22, Code - Insiders.exe!GetHandleVerifier+0x126f260
23, Code - Insiders.exe!IsSandboxedProcess+0x2990e1
24, Code - Insiders.exe!IsSandboxedProcess+0x296832
25, Code - Insiders.exe!IsSandboxedProcess+0x29772d
26, Code - Insiders.exe!IsSandboxedProcess+0x5bbc84
27, Code - Insiders.exe!GetHandleVerifier+0x1211752
28, Code - Insiders.exe!GetHandleVerifier+0x122f66c
29, Code - Insiders.exe!IsSandboxedProcess+0x245c59
30, Code - Insiders.exe!IsSandboxedProcess+0x246086
31, Code - Insiders.exe!IsSandboxedProcess+0x245f0e
32, Code - Insiders.exe!IsSandboxedProcess+0x245cf1
33, Code - Insiders.exe!IsSandboxedProcess+0x50eb2b
34, Code - Insiders.exe!IsSandboxedProcess+0x217b0c
35, Code - Insiders.exe!IsSandboxedProcess+0x217baa
36, Code - Insiders.exe!GetHandleVerifier+0x125672d
37, Code - Insiders.exe!IsSandboxedProcess+0x27b173
38, Code - Insiders.exe!IsSandboxedProcess+0x27fe7f
39, Code - Insiders.exe!IsSandboxedProcess+0x27e954
40, Code - Insiders.exe!IsSandboxedProcess+0x24951c
41, Code - Insiders.exe!IsSandboxedProcess+0x248cb3
42, user32.dll!CallWindowProcW+0x4c1
43, user32.dll!DispatchMessageW+0x1d3
44, Code - Insiders.exe!GetHandleVerifier+0x726f7
45, Code - Insiders.exe!GetHandleVerifier+0x72252
46, Code - Insiders.exe!GetHandleVerifier+0x71ee4
47, Code - Insiders.exe!GetHandleVerifier+0x245ef
48, Code - Insiders.exe!IsSandboxedProcess+0x17c478
49, Code - Insiders.exe!IsSandboxedProcess+0x17d846
50, Code - Insiders.exe!IsSandboxedProcess+0x352022
51, Code - Insiders.exe!IsSandboxedProcess+0x5e0db8
52, Code - Insiders.exe!IsSandboxedProcess+0x31273d
53, Code - Insiders.exe!IsSandboxedProcess+0x312630
54, Code - Insiders.exe!IsSandboxedProcess+0x107d46e
55, Code - Insiders.exe!GetHandleVerifier+0x10eb1a0
56, Code - Insiders.exe+0xdbc85
57, Code - Insiders.exe!IsSandboxedProcess+0x1673843
58, kernel32.dll!BaseThreadInitThunk+0x14
59, ntdll.dll!RtlUserThreadStart+0x21

```

Screenshot of the state:
![image](https://user-images.githubusercontent.com/6010463/44263679-28aed600-a220-11e8-8b2b-4fa7dbf13446.png)

On a private channel, I can provide a full screenshot without blurring as well as a full dump file of the "Code - Insiders.exe" process that was in the hung state.

------

VS Code version: Code - Insiders 1.26.0-insider (0c2d71e2bb9a020995729ab7d5d5f8e4e897e657, 2018-08-03T05:18:49.586Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.83GB (7.07GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (80)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
rebound-delete|aar|1.1.0
paste-fixer|aar|1.0.0
calculate|aca|2.1.0
vscode-caniuse|aka|0.5.3
Bookmarks|ale|9.0.3
read-only-indicator|ale|0.7.0
vscode-lcov|ale|0.2.0
vscode-color|ans|0.4.5
code-gnu-global|aus|0.2.2
Doxygen|bbe|1.0.0
solidity-extended|bea|3.0.2
htmltagwrap|bra|0.0.7
vscode-standardjs-snippets|cap|0.7.7
vscode-standardjs|che|1.2.3
npm-intellisense|chr|1.3.0
jsrefactor|cms|2.13.1
gitignore|cod|0.5.0
compulim-vscode-closetag|Com|1.2.0
riot-tag|cri|0.1.7
autoit|Dam|0.2.0
vscode-markdownlint|Dav|0.20.0
jshint|dba|0.10.19
vscode-eslint|dba|1.4.12
vscode-new-file|dku|4.0.2
vscode-npm-source|dku|1.0.0
xml|Dot|2.3.1
gitlens|eam|8.5.4
EditorConfig|Edi|0.12.4
vscode-npm-script|eg2|0.3.5
LogFileHighlighter|emi|2.4.0
gc-excelviewer|Gra|2.1.25
JSDocTagComplete|Hoo|0.0.2
minify|Hoo|0.3.0
RelativePath|jak|1.4.0
hungry-delete|jas|1.5.0
docthis|joe|0.7.1
join-comment-aware|joh|0.0.3
typings-autoinstaller|jvi|1.2.0
format-indent|Kas|1.3.0
Lua|key|0.0.9
vscode-nsis|Kry|0.0.1
VBScript|lug|0.0.2
edge|luo|0.3.1
rainbow-csv|mec|0.4.2
dotenv|mik|1.0.1
ecdc|mit|0.12.0
HTMLHint|mka|0.5.0
find-jump|mks|1.2.4
prettify-json|moh|0.0.3
python|ms-|2018.7.1
cpptools|ms-|0.17.7
PowerShell|ms-|1.8.3
wordcount|ms-|0.1.0
debugger-for-chrome|msj|4.8.2
node-modules-resolve|nau|1.0.2
createGUID|nwa|0.0.2
ejs-language-support|Qas|0.0.1
quicktype|qui|12.0.38
json-organizer|rin|0.0.3
LiveServer|rit|5.1.1
ActiveFileInStatusBar|Ros|1.0.3
vscode-paste-and-indent|Rub|0.0.8
vscode-coverage-gutters|rya|2.1.1
bracket-jumper|sas|1.1.8
trailing-spaces|sha|0.2.11
vscode-autohotkey|sle|0.2.2
rewrap|stk|1.9.1
code-spell-checker|str|1.6.10
ignore-gitignore|stu|1.0.1
language-pde|Tob|1.2.2
js-complexity-analysis|Tom|2.0.0
sort-lines|Tyr|1.7.0
bracket-padder|via|0.0.1
vscode-devdocs|ben|0.1.0
quokka-vscode|Wal|1.0.138
vscode-todo-highlight|way|1.0.4
change-case|wma|1.0.0
FilterText|yhi|0.0.10
html-css-class-completion|Zig|1.17.1

</details>

**Comment by bpasero** [comment]
Yeah this sounds a lot like https://github.com/Microsoft/vscode/issues/55347, merging.
