### ISSUE TITLE
Updates not working on user based installation

### ISSUE THREAD

**Issue by Perneel** [Microsoft/vscode#56663]
- VSCode Version: 1.26.0 (User install)
- OS Version: Win10 x64

Steps to Reproduce:

1. Clicking "Restart to update"
2. Results in the following error message:
![image](https://user-images.githubusercontent.com/4124110/44259374-97d0fe00-a211-11e8-9f52-1dd5f0d0f957.png)

Log: 
Aug 17 11:34:30.420 INFO Starting: C:\Users\Steven\AppData\Local\Programs\Microsoft VS Code\Code.exe, false
Aug 17 11:34:30.421 INFO Checking for running Code.exe processes... (attempt 1)
Aug 17 11:34:30.426 INFO Code.exe is running, wait a bit
Aug 17 11:34:30.927 INFO Checking for running Code.exe processes... (attempt 2)
Aug 17 11:34:30.932 INFO Code.exe is running, wait a bit
Aug 17 11:34:31.433 INFO Checking for running Code.exe processes... (attempt 3)
Aug 17 11:34:31.442 INFO Code.exe is not running
Aug 17 11:34:31.442 INFO Checking for possible conflicting running processes... (attempt 1)
Aug 17 11:34:31.452 INFO Inno Updater v0.5.0
Aug 17 11:34:31.452 INFO Starting update, silent = false
Aug 17 11:34:31.476 INFO do_update: "C:\\Users\\Steven\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe", _
Aug 17 11:34:31.476 INFO move_update: "C:\\Users\\Steven\\AppData\\Local\\Programs\\Microsoft VS Code\\unins000.dat", _
Aug 17 11:34:31.476 INFO Delete: "Code.exe" (attempt 1)
Aug 17 11:34:31.527 INFO Delete: "Code.exe" (attempt 2)
Aug 17 11:34:31.728 INFO Delete: "Code.exe" (attempt 3)
Aug 17 11:34:32.179 INFO Delete: "Code.exe" (attempt 4)
Aug 17 11:34:32.980 INFO Delete: "Code.exe" (attempt 5)
Aug 17 11:34:34.231 INFO Delete: "Code.exe" (attempt 6)
Aug 17 11:34:36.031 INFO Delete: "Code.exe" (attempt 7)
Aug 17 11:34:38.483 INFO Delete: "Code.exe" (attempt 8)
Aug 17 11:34:41.684 INFO Delete: "Code.exe" (attempt 9)
Aug 17 11:34:45.734 INFO Delete: "Code.exe" (attempt 10)
Aug 17 11:34:50.736 INFO Delete: "Code.exe" (attempt 11)
Aug 17 11:34:50.736 ERRO Toegang geweigerd. (os error 5)

**Comment by R3un1** [comment]
Same here.

[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2296735/vscode-inno-updater.log)

**Comment by murilogiatti** [comment]
Same here.

**Comment by sgomanf** [comment]
Same here. Windows 7 32bits

[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2298738/vscode-inno-updater.log)

**Comment by LukeKolodziej** [comment]
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2299022/vscode-inno-updater.log)
Same here.
VSCode Version: 1.26.0 (User install)
OS Version: Win10 x64

**Comment by LukeKolodziej** [comment]
Downloading the installer (1.26.1) from the website will successfully update the installed version.

**Comment by markwhitaker** [comment]
Same here on Windows 10 Pro.

[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2299534/vscode-inno-updater.log)

**Comment by joaomoreno** [comment]
You seem to have #47841.

Please read this comment if you can provide more detail: https://github.com/Microsoft/vscode/issues/47841#issuecomment-393101777

Please read this one to disable background updates: https://github.com/Microsoft/vscode/issues/47841#issuecomment-395017687

Also read this one to provide feedback on our new user setup: https://github.com/Microsoft/vscode/issues/47841#issuecomment-399941682
