### ISSUE TITLE
Breadcrumbs dropdown should be wider

### ISSUE THREAD

**Issue by Srekel** [Microsoft/vscode#56661]
Issue Type: <b>Bug</b>

Programming in C, function names can get rather long. Take a look at the screenshot to see my problem - only the first part is shown.

![image](https://user-images.githubusercontent.com/1578924/44258188-8afedb00-a20e-11e8-9686-d9202b494977.png)

Suggestion: Make it as wide as the widest element. Alternatively, make the width a user setting.

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|1.2.6
overtype|ada|0.2.0
Bookmarks|ale|9.0.3
markdown-emoji|bie|0.0.7
markdown-preview-github-styles|bie|0.1.2
bracket-pair-colorizer|Coe|1.0.59
smoothscroll|cya|1.0.4
vscode-markdownlint|Dav|0.19.0
githistory|don|0.4.2
EditorConfig|Edi|0.12.4
LogFileHighlighter|emi|2.4.0
asciidecorator|hel|0.2.0
beautify|Hoo|1.3.2
contextualduplicate|laf|0.2.0
MagicPython|mag|1.0.12
python|ms-|2018.7.1
cpptools|ms-|0.17.7
indent-rainbow|ode|7.2.2
material-icon-theme|PKi|3.5.2
subtle-brackets|raf|2.1.1
snake-trail|ric|0.6.0
code-settings-sync|Sha|3.0.0
trailing-spaces|sha|0.2.11
markdown-preview-enhanced|shd|0.3.5
indenticator|Sir|0.6.0
vscode-fileutils|sle|2.10.3
shader|sle|1.1.3
code-spell-checker|str|1.6.10
ninja|sur|0.0.1
python|tht|0.2.3
sort-lines|Tyr|1.7.0
markdown-all-in-one|yzh|1.6.0

(2 theme extensions excluded)

</details>

**Comment by nealot** [comment]
See https://github.com/Microsoft/vscode/issues/56318.

**Comment by jrieken** [comment]
The picker is now approx a 1/4 of the editor width
