### ISSUE TITLE
Intellisense List missing c# on language selection

### ISSUE THREAD

**Issue by trevorscharf** [Microsoft/vscode#5666]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. 
2.

**Comment by dbaeumer** [comment]
@trevorscharf Are you talking about the language selection list. You need to install the C# extension:

![capture](https://cloud.githubusercontent.com/assets/1931590/14752373/41cd672e-08cf-11e6-9c56-c0e20a7f5312.png)

**Comment by trevorscharf** [comment]
Thanks. That was it!

On Fri, Apr 22, 2016 at 3:15 PM, Dirk Bäumer <notifications@github.com>
wrote:

> @trevorscharf <https://github.com/trevorscharf> Are you talking about the
> language selection list. You need to install the C# extension:
>
> [image: capture]
> <https://cloud.githubusercontent.com/assets/1931590/14752373/41cd672e-08cf-11e6-9c56-c0e20a7f5312.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/vscode/issues/5666#issuecomment-213558463>
>



-- 

Trevor Scharf

trevo <andrew@2gtech.com>rscharf@gmail.com

**Comment by dbaeumer** [comment]
Closing.
