### ISSUE TITLE
Indistinguishable color of an active button after upgrade to 1.26.0

### ISSUE THREAD

**Issue by ris58h** [Microsoft/vscode#56660]
- VSCode Version: 
Version: 1.26.0
Commit: 4e9361845dc28659923a300945f84731393e210d
Date: 2018-08-13T16:25:59.521Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
- OS Version:
Ubuntu 18.04.1 LTS

For example 'Discard All Changes' dialog:
![vscode-promt-color](https://user-images.githubusercontent.com/511242/44258009-6dce0a80-a216-11e8-89ad-02207af2e2a5.png)

**Comment by bpasero** [comment]
We do not control the styling of the native buttons. @ris58h how do dialogs in other apps look like?

**Comment by ris58h** [comment]
@bpasero I couldn't find any dialog with the same style. But I've installed VSCode 1.25.1 and this is what the same dialog looks like in older version.
![dialog-1 25 1](https://user-images.githubusercontent.com/511242/44299712-0c846500-a304-11e8-8fe3-a8d7bf114c9b.png)

**Comment by bpasero** [comment]
@ris58h that difference is expected, our previous version is using GTK2 dialogs and now we use GTK3.

**Comment by bpasero** [comment]
Merging into https://github.com/Microsoft/vscode/issues/57019
