### ISSUE TITLE
Align breadcrumb height with debug toolbar height

### ISSUE THREAD

**Issue by derekoakley** [Microsoft/vscode#56678]
Breadcrumbs add some nice extra height to the editor which is a great fit for the .net floating (pause, breakpoints, stop, etc) toolbar

**Comment by jrieken** [comment]
@derekoakley What's the issue here?

**Comment by derekoakley** [comment]
Sorry, this is a feature request not a issue

**Comment by jrieken** [comment]
We decided against this and went in favour of #56022. The height is now aligned with section headers in viewlets. We figured its the better fit and visually more pleasing.
