### ISSUE TITLE
[xml] syntax parser failed to parse comment with -- in the middle

### ISSUE THREAD

**Issue by jerry2013** [Microsoft/vscode#56679]
Issue Type: <b>Bug</b>

The syntax parser in vscode is unable to find the end of comment when -- is in the middle.

```xml
<test>
    <!-- good comment -->
    <a />
    <!-- unable to find -- the end of the comment -->
    <b/>
</test>
```

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

**Comment by Serega124** [comment]
https://stackoverflow.com/a/2757486

**Comment by aeschli** [comment]
![image](https://user-images.githubusercontent.com/6461412/44331722-91898e80-a46a-11e8-80e0-d20c18a6d0b2.png)

If you enter your sample in https://www.xmlvalidation.com/ you can see that the `--` is indeed a problem.
