### ISSUE TITLE
Markdown preview jumps to top when editing

### ISSUE THREAD

**Issue by wkronemeijer** [Microsoft/vscode#56674]
Before 1.26.1, I had disabled these four markdown settings:

* Double click to switch to editor
* Mark Editor Selection
* Scroll Editor With Preview
* Scroll Preview With Editor

When editing a markdown document, the preview stayed at (roughly) the same place in the document. After updating to 1.26.1 however, the markdown preview now jumps to the top when editing. The insiders build I tested (version: 1.27.0-insider, commit: fd610b4b6ab8d4735a4d84a2b59206ad3a9c8099) still showed this issue. 

VSCode Version: 1.26.1  
OS Version: Windows 10, 1803  

Steps to Reproduce:

1. Disable the four settings mentionend above
2. Create a markdown document with more than one screen of text (e.g. [lorem ipsum](http://loremipsum.nl/))
3. Open the markdown preview and scroll it to the bottom
4. Do a small edit, like inserting a 'x' at the end of the document

What I expected to happen: the preview stays at the end of the document.  
What actually happened: the preview jumped to the top. 

This issue still occurs when all extensions are disabled.

**Comment by mjbvz** [comment]
We made some fixes in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) for this. Please test this on a recent insiders build and let me know if you still see this issue

**Comment by wkronemeijer** [comment]
I can confirm this issue is fixed as of version: 1.28.0-insider, commit: 2558a72d6902015b142ef45c57b664ce1f09e03f.

👍
