### ISSUE TITLE
fail to upgrade v1.26.1 from v1.26.0

### ISSUE THREAD

**Issue by deepkolos** [Microsoft/vscode#56671]
Issue Type: <b>Bug</b>

![https://s1.ax1x.com/2018/08/17/PWWklD.png](https://s1.ax1x.com/2018/08/17/PWWklD.png)

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.93GB (4.38GB free)|
|Process Argv|d:\Program files\Microsoft VS Code\Code.exe .|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|1.2.6
Bookmarks|ale|9.0.3
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.59
vscode-svgviewer|css|1.4.4
vue-peek|dar|1.0.2
vscode-eslint|dba|1.4.12
githistory|don|0.4.2
gitlens|eam|8.5.4
tslint|eg2|1.0.35
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.6.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
npm-dependency-links|her|1.0.0
vue-snippets|hol|0.1.8
path-autocomplete|ion|1.12.0
vscode-conemu|ipa|1.0.4
vscode-postfix-ts|ipa|1.8.0
search-node-modules|jas|1.3.0
json-to-ts|Mar|1.5.5
vscode-language-pack-zh-hans|MS-|1.26.3
debugger-for-chrome|msj|4.8.2
vetur|oct|0.12.6
material-icon-theme|PKi|3.5.2
code-settings-sync|Sha|3.0.0
quokka-vscode|Wal|1.0.136
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.7.0

</details>

**Comment by joaomoreno** [comment]
Do you have the log file?

**Comment by deepkolos** [comment]
@joaomoreno i have clean it .... after i move _ dir's file into *Microsoft VS Code* dir, it can startup, but right click menu is borken, the error is fail to find the file **D:\Program files\Microsoft VS Code\Microsoft VS Code\code.exe**

so i choose to reinstall from new

**Comment by joaomoreno** [comment]
Yes, please fully reinstall VS Code.
