### ISSUE TITLE
caracteres UTF8

### ISSUE THREAD

**Issue by maurighar** [Microsoft/vscode#56673]
Issue Type: <b>Bug</b>

No toma correctamente el formato de los caracteres UTF8 en archivos de texto.

235.631 	16/08/2018 12:47:03 	30711848165 	TRANSPORTE Y SERVICIOS DON EMILIO S.A. 	S� 	VV: 2. NP: 1. (N: 2. P: 0) 	Seleccionar
235.630 	16/08/2018 12:28:11 	30711945608 	MEL'S LOGISTICA Y SERVICIOS SOCIEDAD ANONIMA 	S� 	VV: 2. NP: 1. (N: 2. P: 0) 	Seleccionar
235.629 	16/08/2018 11:53:51 	20141926064 	CARMONA VICENTE 	S� 	VV: 4. NP: 1. (N: 4. P: 0) 	Seleccionar
235.628 	16/08/2018 11:23:22 	20287571977 	FRIAS MORALES JORGE JOSE 	S� 	VV: 1. NP: 1. (N: 1. P: 0) 	Seleccionar
235.627 	16/08/2018 11:22:48 	20203351667 	DAMINATO HUGO ENRIQUE 	S� 	AV: 1. BV: 1. NP: 1. (N: 2. P: 0) 	Seleccionar

VS Code version: Code - Insiders 1.27.0-insider (fd610b4b6ab8d4735a4d84a2b59206ad3a9c8099, 2018-08-17T05:18:51.696Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (3.36GB free)|
|Process Argv|G:\AppLocal\VSCode64-insider\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.12
bulma|dem|0.0.9
css-minify|Die|0.1.10
jupyter|don|1.1.4
vscode-html-css|ecm|0.2.0
prettier-vscode|esb|1.6.1
php-debug|fel|1.12.4
php-intellisense|fel|2.3.3
php-pack|fel|1.0.2
auto-close-tag|for|0.5.6
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.0.15
gc-excelviewer|Gra|2.1.25
beautify|Hoo|1.3.2
vs-color-picker|lih|0.7.0
rainbow-csv|mec|0.4.2
vscode-language-pack-es|MS-|1.26.3
python|ms-|2018.7.1
sublime-keybindings|ms-|4.0.0
color-highlight|nau|2.3.0
python|tht|0.2.3

</details>

**Comment by bpasero** [comment]
Please create a new issue in english.
