### ISSUE TITLE
VSTS plugin Error

### ISSUE THREAD

**Issue by carloscds** [Microsoft/vscode#56675]
- VSCode Version: 1.27.0-insider
- OS Version: Wndows 10 Pro (Build 177123.1002)

Steps to Reproduce:

1. install VSTS plugin
2. try to connect
3. if connect, try to click over VSTS project name on bar

![vscode-error-vsts](https://user-images.githubusercontent.com/1697221/44265212-03a86c00-a1fc-11e8-8e5e-adffced94f22.png)

**Comment by sandy081** [comment]
Please file the issue against VSTS extension

**Comment by carloscds** [comment]
@sandy081 Sorry, but I didn't understand, this bug was fixed ?

**Comment by sandy081** [comment]
This functionality is provided by VSTS extension and please file issue against that extension here https://marketplace.visualstudio.com/items?itemName=ms-vsts.team
