### ISSUE TITLE
Failed to load plugin react: Cannot find module 'eslint-plugin-react' every time I open a .js file

### ISSUE THREAD

**Issue by ddieppa** [Microsoft/vscode#5667]
- VSCode Version: 
Version 1.0.0
Commit fa6d0f03813dfb9df4589c30121e9fcffa8a8ec8
Date 2016-04-13T14:08:36.599Z
Shell 0.35.6
Renderer 45.0.2454.85
Node 4.1.1

- OS Version: windows 8.1 Pro

Failed to load plugin react: Cannot find module 'eslint-plugin-react' every time I open a .js file, not even related with any react development

Steps to Reproduce:

1. right click on any .js file and open with VS Code
2. wait a few seconds and the error appears

![image](https://cloud.githubusercontent.com/assets/10607192/14752291/78dc4182-089c-11e6-82cc-7d713d11e9e4.png)

**Comment by dbaeumer** [comment]
@ddieppa do you have the eslint extension installed? Looks like the extension can't load the react plugin?

**Comment by ddieppa** [comment]
that's my point, I just installed VS Code 1.0 from scratch, and installed eslint plugin for VS Code, but I don't have to install the eslint-plugin-react

this is what I have globally installed in my pc:
![image](https://cloud.githubusercontent.com/assets/10607192/14752769/34467d32-089f-11e6-8a6d-4610a3faafb3.png)

and this are my installed extension in VS Code:
![image](https://cloud.githubusercontent.com/assets/10607192/14752800/5e868d1c-089f-11e6-8ba8-cc85d7ef8472.png)

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/vscode-eslint#71
