### ISSUE TITLE
F11 doesn't work with integrated terminal

### ISSUE THREAD

**Issue by sguillia** [Microsoft/vscode#56677]
**Steps to Reproduce**

1. Open VS Code on Windows
2. Open integrated terminal and focus it
3. Press F11 key
4a. If shell is git bash, `Function Key 11` appears in terminal as if I typed it
4b. If shell is cmd.exe, nothing happens

**Expected behavior**

Window toggles full screen when pressing F11, with respect to the following default setting.
```
{
  "key": "f11",
  "command": "workbench.action.toggleFullScreen"
}
```

**Details**
Reproduces without extensions: Yes
VS Code version: Code - Insiders 1.27.0-insider (fd610b4b6ab8d4735a4d84a2b59206ad3a9c8099, 2018-08-17T05:18:51.696Z)
OS version: Windows_NT x64 10.0.15063

**Comment by Tyriar** [comment]
Fixed in 1.28, in the meantime you can add the command ID to the list of commands in `terminal.integrated.commandsToSkipShell` to allow F11 to bypass the shell.
