### ISSUE TITLE
Code lens text jumps up and down during typing

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#56688]
A Dart Code user (@bergwerf) reported this to me - from the description I thought it might be caused by the code lens appear/disappearing, but from the screencapture it doesn't seem so - the text appears to be rendered in multiple positions during typing making it seem to bounce up and down (no other lines seem to shift though).

I can't repro myself though.

![vokoscreen-2018-08-17_16-03-21](https://user-images.githubusercontent.com/1078012/44271457-176ec500-a232-11e8-9fd7-a9554373f357.gif)

**Comment by alexandrudima** [comment]
@jrieken @aeschli What are the contents inside those code-lens? Could it be that the DOM elements and CSS rules we're using in there would cause this?

**Comment by alexandrudima** [comment]
@bergwerf what is your OS ?

**Comment by alexandrudima** [comment]
@bergwerf  Does it reproduce when launching `code --disable-gpu` ?

**Comment by bergwerf** [comment]
Yes. It doesn't really look like a rendering bug but rather a problem with the style rules. Version info:
```
1.26.1
493869ee8e8a846b0855873886fc79d480d342de
x64
```

I might be able to debug this later using the style inspector.

**Comment by bpasero** [comment]
@DanTup @bergwerf We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/code-exploration_1.28.0-1536650436_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/VSCodeUserSetup-x64-1.28.0-exploration.exe)

**Comment by bergwerf** [comment]
Might check later but I don't have time now.
