### ISSUE TITLE
JSX properties red if there is an underscore in prop name

### ISSUE THREAD

**Issue by marsiancba** [Microsoft/vscode#56685]
This is probably some bug in TSX syntax highlighting:

![image](https://user-images.githubusercontent.com/5137942/44269433-ce6c4000-a234-11e8-805d-43219aa161fb.png)

```
<Test
    a=''
    b_c='111'
    d=''
/>

function Test(props: { a: string, b_c: string, d: string }) { return <span /> };
```

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#648
