### ISSUE TITLE
Have a dark title bar in dark themes like in Visual Studio 2017

### ISSUE THREAD

**Issue by jjgriff93** [Microsoft/vscode#56681]
Currently there is no way to make the title bar dark in line with dark themes in VS Code, the only option is to full screen the application which I don't want to do in certain circumstances. Would be great if the title bar could inherit colours from themes instead of sticking out like a saw thumb unless you have a light theme.

![image](https://user-images.githubusercontent.com/25235950/44268469-7aa82980-a229-11e8-9e44-6a71c36d41be.png)

**Comment by levrik** [comment]
1.26.0 implemented a custom themable title bar. You can enable it in the settings.
