### ISSUE TITLE
Add Folder To Workspace crashes code

### ISSUE THREAD

**Issue by Legogris** [Microsoft/vscode#56687]
- VSCode Version: 1.26.0, 4e9361845dc28659923a300945f84731393e210d, x64
- OS Version: nixOS

Steps to Reproduce:

1. Open new window
2. Click File -> Add Folder to Workspace...
3. Process crashes

The same thing (instant crash) also happens when clicking the "Open folder" button or File -> Open Folder. I have looked through all the log files in `~/.config/Code/logs` but nothing out of the ordinary there.

This worked fine in previous versions and opening previously opened folders via "File -> Open Recent" works fine.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Legogris** [comment]
I do not know why @vscodebot tagged this as `extensions` :man_shrugging:

**Comment by bpasero** [comment]
@Legogris are you on ArchLinux by any chance?

**Comment by bpasero** [comment]
Assuming this is https://github.com/Microsoft/vscode/issues/55934
