### ISSUE TITLE
Multiple different types of terminal concurrently

### ISSUE THREAD

**Issue by jjgriff93** [Microsoft/vscode#56682]
It would be great to be able to load up a PowerShell integrated terminal, as well as Bash, CMD and others concurrently. My only way of doing this at the moment is going into settings, and uncommenting the terminal I want to use at a given moment, and then comment out the one I'm currently using. Then when clicking the + button, I get a different terminal as well as the one I had open originally.

Very long winded process and having a simple dropdown selection would save a lot of time.

**Comment by Tyriar** [comment]
Right now this functionality is deferred to extensions https://marketplace.visualstudio.com/items?itemName=Tyriar.shell-launcher

You can also run "cmd" or "bash" inside a powershell terminal.
