### ISSUE TITLE
Activity Bar Icons' Visibility Toggle Randomly

### ISSUE THREAD

**Issue by markwest1** [Microsoft/vscode#56697]
### Example 1
![image](https://user-images.githubusercontent.com/8137897/44275118-8ab01100-a209-11e8-9a13-83bf5c19c1f2.png)

### Example 2: Just hovering over a different Activity Bar Icon toggles the visibility of the `Find` icon
![image](https://user-images.githubusercontent.com/8137897/44274747-8fc09080-a208-11e8-86db-c2615327ac58.png)

### Example 3: Visibility does not toggle when only one icon is un-hidden in the activity bar
![image](https://user-images.githubusercontent.com/8137897/44274964-2bea9780-a209-11e8-83c5-2fbb290971b4.png)

- VSCode Version: **1.26.1**
  - Commit: **493869ee8e8a846b0855873886fc79d480d342de**
  - Date: **2018-08-16T18:38:57.434Z**
  - Electron: **2.0.5**
  - Chrome: **61.0.3163.100**
  - Node.js: **8.9.3**
  - V8: **6.1.534.41**
  - Architecture: **x64**
- OS Version: **Windows 7 Professional Service Pack 1**

Steps to Reproduce:

1. **Start VS Code**
2. **Look at the Activity Bar** (See attached images.)

Does this issue occur when all extensions are disabled?: **YES**

**Comment by sandy081** [comment]
@markwest1 When does the icons get reordered? After you hovered on them or after you reload the window?

**Comment by markwest1** [comment]
They don't get reordered.

They get blocked out by a white square. Even without hovering over them, at least two are blocked out, sometimes three.

**Comment by markwest1** [comment]
@sandy081 I'm closing this because once I stopped running VS Code as admin, this problem seemed to disappear. Thanks for looking into it.
-Mark
