### ISSUE TITLE
Poor performance when resizing terminal bottom panel on Windows

### ISSUE THREAD

**Issue by tburly** [Microsoft/vscode#56692]
I experience poor performance when resizing Bottom Panel in terminal mode (see the [linked GIFs](https://imgur.com/a/DnyVDgn)) What visibly helps:
- opening Side Bar (Panel's width shrinks)
- switching to other Panel mode (Problems/Output/Debug Console)
- going from full screen to a smaller window.
- closing some resource-heavy editor panes (like User Settings) - minor improvement

Also there's a pretty crippling lag when writing anything in Terminal. And it doesn't seem to matter if the opened shell is cmd.exe, Powershell or Git Bash.

Better performance in other Panel modes and also noticeably better performance when resizing Editor Panes points to this being solely a Terminal rendering issue.

- VSCode Version:

> Version: 1.26.1
> Commit: 493869ee8e8a846b0855873886fc79d480d342de
> Date: 2018-08-16T18:38:57.434Z
> Electron: 2.0.5
> Chrome: 61.0.3163.100
> Node.js: 8.9.3
> V8: 6.1.534.41
> Architecture: x64

> CPUs | Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz (8 x 2494)
> -- | --
> GPU Status | 2d_canvas: enabledchecker_imaging: disabled_offflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwarerasterization: enabledvideo_decode: enabledvideo_encode: enabledwebgl: enabledwebgl2: enabled
> Memory (System) | 15.88GB (9.50GB free)
> Process Argv | C:\Program Files\Microsoft VS Code\Code.exe D:\Poligon\vscode\temp\temp.code-workspace
> Screen Reader | no
> VM | 0%

> Extension | Author (truncated) | Version
> -- | -- | --
> vscode-great-icons | emm | 2.1.41
> python | ms- | 2018.7.1
> sublime-keybindings | ms- | 4.0.0
> vscodeintellicode | Vis | 1.0.3

- OS Version:
[OS info](https://imgur.com/a/z2ZIWq6)

Steps to Reproduce:

1. Install vscode on Windows
2. Run it
3. Toggle Panel visibility

Does this issue occur when all extensions are disabled?: Yes/No
Yes.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/56628
