### ISSUE TITLE
Allow to set order for breadcrumb items

### ISSUE THREAD

**Issue by metalfox6383** [Microsoft/vscode#56695]
Issue Type: <b>Feature Request</b>

Hi. I like breadcrumbs! I would like to ask you that your elements are arranged alphabetically. Así también, el ancho de las opciones pueda ser ajustable. Thanks

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

**Comment by tristan957** [comment]
The drop down menus are alphabetical. What is the point of breadcrumbs if the breadcrumbs are alphabetical? They are supposed to show how you got to where you are.

**Comment by redwolf2** [comment]
@tristan957 
Visual Studio Code would also behave more like Visual Studio 2017 for C#. There all methods are sorted alphabetically as a default. It helps you to find a function whose name you already know faster.

**Comment by jrieken** [comment]
> There all methods are sorted alphabetically as a default. It helps you to find a function whose name you already know faster.

While we don't have alphabetical sorting yet you can start typing the name of those functions and they should be highlighted and pre-selected

**Comment by stanislavgeorgiev** [comment]
> The drop down menus are alphabetical. What is the point of breadcrumbs if the breadcrumbs are alphabetical? They are supposed to show how you got to where you are.

@tristan957 I believe @metalfox6383 wants the each breadcrumb dropdown items to be sorted alphabetically. I would also very much like that because I can use the breadcrumbs as a replacement for the Code Outline panel in case I don't have that one opened at the moment.

**Comment by ryanclarke** [comment]
I'm interested in contributing and this issue looks open.

I believe I understand the problem. On the breadcrumbs, the last arrow shows the class/functions/etc. in file order and the original poster wanted them in alphabetical order, like the Outline window. Is this a change that the team wants to make? If so, should it be configurable?

**Comment by jrieken** [comment]
Correct, a few pointers

* [this the place](https://github.com/Microsoft/vscode/blob/a63b9e179b25babeef448116167d9ace72c389f6/src/vs/workbench/browser/parts/editor/breadcrumbsPicker.ts#L464) in which the symbol tree is setup, there already exists a matching [comparator](https://github.com/Microsoft/vscode/blob/a63b9e179b25babeef448116167d9ace72c389f6/src/vs/editor/contrib/documentSymbols/outlineTree.ts#L30)
* you will also need a new setting for this, see [this](https://github.com/Microsoft/vscode/blob/a63b9e179b25babeef448116167d9ace72c389f6/src/vs/workbench/browser/parts/editor/breadcrumbs.ts#L113) and [this](https://github.com/Microsoft/vscode/blob/a63b9e179b25babeef448116167d9ace72c389f6/src/vs/workbench/browser/parts/editor/breadcrumbs.ts#L69)

**Comment by ryanclarke** [comment]
Thanks for the direction. I got vscode building on my system and I'll start looking at this.

Should the current sort (file order) continue to be the default or should the default be changed to be alphabetical?

**Comment by ryanclarke** [comment]
Thanks for fixing #61179.

**Comment by jrieken** [comment]
@ryanclarke 👏
