### ISSUE TITLE
deleting large directory freezes vs code

### ISSUE THREAD

**Issue by graph** [Microsoft/vscode#56690]
- VSCode Version:
Version: 1.26.0
Commit: 4e9361845dc28659923a300945f84731393e210d
Date: 2018-08-13T16:29:31.933Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Steps to Reproduce:

1. make a directory with 19K+ files (I tested with one of my build directories)
2. delete it by doing move to recycle bin

info about what I deleted:

- 17,812 Files, 1,536 Folders
- just over 6GB total
- somewhere in D:/

It finishes eventually but all the UI is frozen. And VS code closed. My project is in D:/ maybe that's a factor I don't know.

I just tested with 1.26.1 and the issue still exists there too. It deleted quicker I guess the harddrive was already warmed up this time but it did freeze for a moment. Deleting needs progress or some form of indicator.

**Comment by bpasero** [comment]
Yes, having the entire drive opened in VSCode can result in freezes like this due to the massive amount of file events that are potentially send. The only way out is to configure certain (large) subfolders on this drive to be excluded from watching via the `files.watcherExcludes` setting.

**Comment by MicahZoltu** [comment]
I run into this problem all the time when trying to delete my `node_modules` folder.  Often this folder has many files, but is relatively small.  As a workaround, is it possible to do a system-wide `node_modules` watcher exclude that will ignore any directory that is part of a tree that includes `nodue_modules`?

**Comment by bpasero** [comment]
@MicahZoltu there was a recent bugfix in this area, can you try if it still reproduces with our insiders release?

**Comment by graph** [comment]
@bpasero This bug still occurs latest release

Version: 1.28.1 (system setup)
Commit: 3368db6750222d319c851f6d90eb619d886e08f5
Date: 2018-10-11T18:13:53.910Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
