### ISSUE TITLE
Run code directly by keyboard

### ISSUE THREAD

**Issue by dws-arjun** [Microsoft/vscode#56699]
there must be a feature developer can run code by pressing a key e.g `ctrl+b` (as sublime has build).

**Comment by nealot** [comment]
You can create a new task and use `ctrl+shift+b` to `Run Build Task`. 
See https://code.visualstudio.com/docs/editor/tasks.

**Comment by sandy081** [comment]
Thanks @nealot for helping out.

Please try tasks feature in VS Code
