### ISSUE TITLE
The VS code editor version 1.26.1 does not scale on the 4k screen. The version1.25.1 scales correctly instead.

### ISSUE THREAD

**Issue by JamiLu** [Microsoft/vscode#56696]
- VSCode Version: 1.26.1
- OS Version: KDE Neon, kernel 4.15.0-32-generic

Steps to Reproduce:

1. update or clean install 
2. open the vs code editor by double clicking the icon.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bpasero** [comment]
@JamiLu can you explain what you mean by scaling? can you share a screenshot?

**Comment by bpasero** [comment]
Does it reproduce when you run `code --disable-gpu` from the command line?

**Comment by JamiLu** [comment]
Yes it still opens the window the same.

**Comment by bpasero** [comment]
@JamiLu how does it look like with our "VSCode Exploration" build that is using a newer Electron framework: https://az764295.vo.msecnd.net/exploration/94da7241d11facbcc6dcc551d9e63b6170b58525/code-exploration-1535484534.tar.gz
