### ISSUE TITLE
Extension is not deactivated on closing the editor window

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#567]
_From @ArtemGovorov on November 16, 2015 7:15_

My extension spins up a few processes that I'd like to kill when it's deactivated.
The deactivation callback for `ExtensionContext`
``` JavaScript
context.subscriptions.push({dispose: () => ...});
```
works perfectly when I stop debugger for the Extension Development Host. However, if I just close the editor window on OSX, the deactivation callback is not invoked, so I can see all created processes hanging around and not being killed.

_Copied from original issue: Microsoft/vscode-extensionbuilders#113_

**Comment by seanmcbreen** [comment]
_From @ArtemGovorov on November 16, 2015 7:34_

Here's the workaround I use for now for OSX:
``` JavaScript
  process.on('SIGTERM', function () {
    // extension deactivation code
  });
```

**Comment by seanmcbreen** [comment]
_From @bpasero on November 16, 2015 7:38_

@ArtemGovorov is this only during extension development? Not when having the extension installed and closing the window?

**Comment by seanmcbreen** [comment]
_From @ArtemGovorov on November 16, 2015 7:39_

@bpasero Same for the installed extension (on OSX)

**Comment by seanmcbreen** [comment]
_From @bpasero on November 16, 2015 8:2_

@jrieken fyi that would be pretty bad, is the PH connected to the lifecycle service somehow?

**Comment by seanmcbreen** [comment]
_From @egamma on November 16, 2015 8:7_

@dbaeumer you shut down the language server on shutdown and it works correct?

**Comment by seanmcbreen** [comment]
_From @dbaeumer on November 16, 2015 9:29_

@egamma no, I currently fix this on the server side by observing the streams and exit the server is the input stream closes.

**Comment by daviwil** [comment]
See also: https://github.com/Microsoft/vscode/issues/537

**Comment by alexandrudima** [comment]
With 98473e0e88cecd52ba44551d512efe445b6af11e, VSCode's extension host will now call `deactivate()` if extensions export it and call `dispose()` on `ExtensionContext.subscriptions` on shutdown, then will wait 1s before exiting

**Comment by alexandrudima** [comment]
this was in the test plan
