### ISSUE TITLE
Git range staging does stage the whole file

### ISSUE THREAD

**Issue by sguillia** [Microsoft/vscode#56708]
Issue Type: <b>Bug</b>

The git range staging feature is acting weirdly.

Some issues happen quite randomly: sometimes I get ``Git: Illegal value for `line` ``, but I can't reproduce.

There is one thing that happens 100% of the time. There are the steps to reproduce.

1. Open some file in the git diff viewer, the file must be modified but unstaged
2. Select a range in the file
3. Right click > Stage selected ranges
4. Observe as the whole file gets staged
5. Open the file under _Staged Changes_
6. Observe that the whole file has been staged

Here is a screen recording of the problem as a GIF.

![project-staging](https://user-images.githubusercontent.com/15984272/44279450-b5be5300-a251-11e8-9bc6-e2d0bd4e5438.gif)

Here is the file: [demo.txt](https://github.com/Microsoft/vscode/files/2298125/demo.txt)

This issue may be somewhat related to  #50736 and #55995.

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (9.77GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
favorites|kdc|1.7.1
cpptools|ms-|0.18.0
vscode-fileutils|sle|2.10.3
vim|vsc|0.16.0

(1 theme extensions excluded)

</details>

**Comment by atitoa93** [comment]
@joaomoreno Did you tried to reproduce the issue? I tried but It works just fine.
Using mac.

**Comment by sguillia** [comment]
I tried it again.

Still reproduces with Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de)

Does not reproduce with Insiders 1.28.0-insider (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9)

**Comment by joaomoreno** [comment]
Excellent, closing it.

**Comment by jcarnevale89** [comment]
I'm on 1.28.2 and this is still happening.
