### ISSUE TITLE
Snippets: placeholder with both default value and transform don't work

### ISSUE THREAD

**Issue by thorn0** [Microsoft/vscode#56703]
Issue Type: <b>Bug</b>

```
	"foo": {
		"prefix": "foo",
		"body": "${1:placeholder/(.*)/${1:/downcase}/}", 
		"description": "foo"
	}
```

When I type foo and press tab, I get `placeholder/(.*)/placeholder/(.*)//downcase//` right in the editor.

VS Code version: Code - Insiders 1.27.0-insider (fd610b4b6ab8d4735a4d84a2b59206ad3a9c8099, 2018-08-17T05:18:51.696Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.65GB (4.11GB free)|
|Process Argv|C:\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.0.3
ng-template|Ang|0.1.9
bracket-pair-colorizer|Coe|1.0.59
vscode-eslint|dba|1.4.12
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.35
prettier-vscode|esb|1.6.1
angular2-switcher|inf|0.1.9
csharp|ms-|1.15.2
debugger-for-chrome|msj|4.8.2
code-spell-checker|str|1.6.10

</details>

**Comment by thorn0** [comment]
As per [this comment](https://github.com/Microsoft/vscode/pull/51621#issuecomment-413926053), seems like it's a wontfix. 😢

**Comment by thorn0** [comment]
Is there an issue about it already? Or should this one stay open?

Why not simply swap over the parts of the syntax?

`${1:placeholder/(.*)/${1:/downcase}/}` → `${1/(.*)/${1:/downcase}/:placeholder}`

**Comment by go2sh** [comment]
This actually might work. I should avoid the regression described in #52931. Maybe @jrieken can comment on it, if he would accept the grammar. I'am currently on holiday, maybe i find some time to elaborate this topic.

**Comment by jrieken** [comment]
Not a fan because we want to stay to the 'real' Textmate syntax as close as possible.
