### ISSUE TITLE
Update 1.26.1 Multiselect line movement selection loss

### ISSUE THREAD

**Issue by onyoo** [Microsoft/vscode#56707]
- VSCode Version: 1.26.1
- OS Version: Ubuntu 16.04.5 LTS

Steps to Reproduce:

1.Select multiple (consecutive) lines with ctl+click
2.move them up or down with alt+(up or down)
3.notice some lines have been deselected and haven't moved

![vs_code_bug ogv](https://user-images.githubusercontent.com/14326883/44278988-a664e880-a204-11e8-8091-54cb3b6ba4d8.gif)

**Comment by alexandrudima** [comment]
Duplicate of #22382
