### ISSUE TITLE
Settings editor doesn't return matches for edited setting values

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#56712]
- Open UI settings editor
- Set font family to "Fira Code"
- Search "Fira Code"
- No results

**Comment by BeatsX** [comment]
Is the problem solved

**Comment by BeatsX** [comment]
I I had the same problem

**Comment by rzhao271** [comment]
`_doFindMatchesInSetting` in `preferencesSearch.ts` is using the default setting value rather than the actual scoped setting value.
