### ISSUE TITLE
js commenter not toggling

### ISSUE THREAD

**Issue by tedfitzpatrick** [Microsoft/vscode#56710]
Issue Type: <b>Bug</b>

mac, js file, cursor inserted in 1 commented line (commented via //), use key combo command+k+c, the commenter adds another // so it comments the line twice vs uncommenting as expected 

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:20:44.170Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2400S CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (1.59GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by Nufflee** [comment]
@tedfitzpatrick It's because the default shortcut to remove line comment is `CTRL + K, CTRL + U` but you can customize it in `File->Preferences->Keyboard Shortcuts`. ;)

**Comment by sandy081** [comment]
`cmd+K cmd+C` adds line comment
`cmd+/` toggles line comment

Try the second one
