### ISSUE TITLE
With Editor Tabs disabled, command+click to jump to method definition not working

### ISSUE THREAD

**Issue by speterson-riskalyze** [Microsoft/vscode#56711]
Issue Type: **Bug**

- VSCode Version:1.26.1
- OS Version: MacOS High Sierra 10.13.6

Steps to Reproduce:

1. (standard working case) Enable editor tabs by adding `"workbench.editor.showTabs": true,` to User Settings
2. Go to any file in a project and try to command + click on a function usage to jump to that functions definition.
3. (seemingly broken case) Disable editor tabs by adding `"workbench.editor.showTabs": false,` to User Settings.
4. Go to the same file and try to command + click on the same function and notice that it doesn't jump to function definition.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
Can you please check if there are any errors in the developer tools console?

**Comment by speterson-riskalyze** [comment]
@sandy081 thanks for getting back to me. Didn't see anything in the developer tools this morning but the problem seems to have resolved itself. Restarted my computer last night so VS Code restarted as well. I think we can close this and if it happens again I will see if I can find more info and I will repost/re-open. Thanks again!
