### ISSUE TITLE
Unable to set keybinding for ctrl+p

### ISSUE THREAD

**Issue by illegalnumbers** [Microsoft/vscode#56716]
- VSCode Version: 1.26.0
4e9361845dc28659923a300945f84731393e210d
x64

- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Open keyboard shortcuts
2. Attempt to set 'Show All Commands' to Ctrl+P
3. Ctrl shows but p combo does not get added

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
@illegalnumbers Can you please provide a screenshot or gif of what you see

**Comment by illegalnumbers** [comment]
I just see the keyboard shortcut screen which has ctrl placed in it but not p.

Ubuntu doesn't lend itself very easily to doing screenshots while the change key hotkey menu item is up so I can't really do it without triggering another key combination or moving the menu off the screen.

**Comment by illegalnumbers** [comment]
It doesn't detect anything. When I use ctrl it detects that but then when I hit the p button nothing comes up. When I use 'p' in other keystroke combinations it's fine. If I set that command to pp or something that seems to work as well.

**Comment by sandy081** [comment]
@alexandrudima Do you know why the `p` key is not detected when it is typed after `ctrl`?

**Comment by alexandrudima** [comment]
@illegalnumbers @sandy081 The fact that we don't get the entire keybinding means that the OS or some other application is *stealing it* or that the keyboard is broken. 

@illegalnumbers Can you use `ctrl+p` successfully in other applications?
