### ISSUE TITLE
Edits in launch.json aren't reflected in the drop down

### ISSUE THREAD

**Issue by omartin2010** [Microsoft/vscode#56718]
Issue Type: <b>Bug</b>

When I edit my launch.json file, the new config isn't reflected in the drop down menu vis a vis Debug until I relaunch the process.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (6.18GB free)|
|Process Argv|C:\Users\omartin\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.20.0
nbpreviewer|jit|1.0.0
vscode-azurestorage|ms-|0.4.1
python|ms-|2018.7.1
vscode-ai|ms-|0.1.9
azure-account|ms-|0.4.3
azurecli|ms-|0.4.2
vsliveshare|ms-|0.3.535
vscode-docker|Pet|0.1.0
markdown-preview-enhanced|shd|0.3.5
markdown-all-in-one|yzh|1.6.0

</details>

**Comment by isidorn** [comment]
Sounds like missing file events -> @bpasero

**Comment by bpasero** [comment]
@omartin2010 can you:
- run "code --verbose"
- open the developer console (Help > Toggle Developer Tools > Console)
- watch the output (if any) that happens when you make a change to the file?

**Comment by omartin2010** [comment]
I'm not seeing the behavior just now but will try this step as soon as I re-see it.
