### ISSUE TITLE
Setup sync job for wiki

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#5671]
https://github.com/Microsoft/vscode.wiki.git needs to sync back and forth with https://github.com/Microsoft/vscode-wiki.git so PRs on vscode-wiki are pulled in to vscide.wiki and vise versa.

See https://github.com/Microsoft/vscode/issues/5669 and https://github.com/Microsoft/vscode/issues/5670

**Comment by gep13** [comment]
@Tyriar I started to do this work with a couple projects, but decided that the overhead wasn't worth it.  Instead, all documentation for my projects now live in the same repo as the source code, and I use https://readthedocs.org/ to display them.  That way, documentation PR's are exactly the same as code PR's.

Will be interesting to see what you put together though.

**Comment by Tyriar** [comment]
@gep13 that's what we just transitioned to, however we decided that we'd prefer to keep the doc PRs/commits away from the product changes.

This is only an issue because GitHub wiki's cannot be forked unfortunately :frowning:

**Comment by gep13** [comment]
>@Tyriar said...
however we decided that we'd prefer to keep the doc PRs/commits away from the product changes.

I can understand the need for that, we just like to keep everything in one place though :)

**Comment by Tyriar** [comment]
This is ready to go from a community perspective, we just need to sync the changes manually until the sync job is setup.

**Comment by Tyriar** [comment]
I setup a job on VSTS, building daily. Leaving this open for a while to confirm it works.

**Comment by gep13** [comment]
@Tyriar do you have any details of the VSTS job that you are running?  Thanks!

**Comment by Tyriar** [comment]
@gep13 it's closed unfortunately but it just runs a few git commands. Here's what it does:

```bash
git clone https://github.com/Microsoft/vscode-wiki.git
cd vscode-wiki
git remote remove upstream # continue if this line fails
git remote add upstream https://github.com/Microsoft/vscode.wiki.git
git fetch upstream
git merge upstream/master
git push origin HEAD:master
git push upstream HEAD:master
```

**Comment by gep13** [comment]
@Tyriar thank you for the information!

**Comment by Tyriar** [comment]
The job failed due to lacking git username/email, after adding that the job synced vscode-wiki and vscode.wiki just fine, merging in https://github.com/Microsoft/vscode-wiki/pull/4 to vscode.wiki https://github.com/Microsoft/vscode/wiki/How-to-Contribute#pull-requests :tada:

**Comment by ferventcoder** [comment]
This is interesting. Similar to what we do with choco. Typically however we'd do a rebase instead of a merge.
