### ISSUE TITLE
Paths start with slash in "Open Recent" menu

### ISSUE THREAD

**Issue by OneTone** [Microsoft/vscode#56728]
Issue Type: <b>Bug</b>

Steps to Reproduce:
1. Drap-n-drop a file in somewhere under HOME directory.  e.g. "~/workspace/a.txt"
2. "File" - "Open Recent" - "/~/workspace/a.txt"
3. Dialog "Path does not exist" popped up.
![vsbug](https://user-images.githubusercontent.com/4032523/44295191-19d72a80-a2d7-11e8-8589-e6dcee9ef5b1.png)

Reproducible on Linux & Mac.

Does this issue occur when all extensions are disabled?: Yes

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:34:20.517Z)
OS version: Linux x64 4.15.0-30-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4712MQ CPU @ 2.30GHz (8 x 2968)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|3, 1, 1|
|Memory (System)|7.70GB (0.94GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.4
project-manager|ale|8.0.0
QML|bbe|1.0.0
vscode-eslint|dba|1.4.12
vscode-dash|dee|1.10.0
line-counter|dol|0.5.2
githistory|don|0.4.2
gitlens|eam|8.5.4
bitbake|Eug|1.1.0
code-runner|for|0.9.4
beautify|Hoo|1.3.2
docthis|joe|0.7.1
autoconf|mae|0.0.7
cppcheck|mat|0.2.2
vscode-clang|mit|0.2.2
python|ms-|2018.7.1
cpptools|ms-|0.18.1
debugger-for-chrome|msj|4.8.2
makefiles-support-for-vscode|nae|0.0.3
material-icon-theme|PKi|3.5.2
vscode-icons|rob|7.25.0
bash-debug|rog|0.2.1
preview-vscode|sea|1.4.4
open-in-browser|tec|2.0.0
cmake|twx|0.0.17
cmake-tools|vec|1.1.1
markdown-pdf|yza|1.2.0
markdown-all-in-one|yzh|1.6.0

(2 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
I cannot reproduce this with our insiders version. @OneTone 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by OneTone** [comment]
@bpasero I tried the insider build, and was not able to reproduce this issue.
