### ISSUE TITLE
Debugger for Chrome does not open with recommended React configuration

### ISSUE THREAD

**Issue by pavilion** [Microsoft/vscode#56724]
- VSCode Version: 1.26.1
- OS Version: i3 Arch Linux
So I have configured the `launch.json` of my project like it suggests here: https://code.visualstudio.com/docs/nodejs/reactjs-tutorial#_debugging-react

I have also added `"runtimeExecutable": "/usr/bin/google-chrome-beta"` to the configuration as I have the beta version of Chrome (I have already tested with the stable version as well). When I set a breakpoint in a random component and click on debug (with npm start running on 3000 already), a about:blank page opens, and a few seconds later I get a notification on vscode saying 

`Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9222).`

Does this issue occur when all extensions are disabled?: Yes

This is my `launch.json`
```json
{
  "version": "0.2.0",
  "configurations": [{
    "name": "Chrome",
    "type": "chrome",
    "request": "launch",
    "url": "http://localhost:3000",
    "webRoot": "${workspaceRoot}/src",
    "sourceMapPathOverrides": {
      "webpack:///src/*": "${webRoot}/*"
    },
    "runtimeExecutable": "/usr/bin/google-chrome-beta"
  }]
}```

**Comment by roblourens** [comment]
See this section of the readme: https://github.com/Microsoft/vscode-chrome-debug#cannot-connect-to-the-target-connect-econnrefused-1270019222

If you already have an instance of Chrome running, you may want to configure a new user-data-dir or set `"userDataDir": true`.
