### ISSUE TITLE
"Open editors" appears in new window, even when disabled

### ISSUE THREAD

**Issue by garyking** [Microsoft/vscode#56729]
- VSCode Version: Version 1.26.1 (1.26.1)
- OS Version: Mac 10.13.5 (17F77)

Steps to Reproduce:

1. Set `explorer.openEditors.visible` to `0`.
2. Open a new window. In the Explorer, `Open Editors` is visible. It should not be visible.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
This is as designed. Empty window shows Open Editors view irrespective of the value
