### ISSUE TITLE
showInformationMessage

### ISSUE THREAD

**Issue by Shreyas-vgr** [Microsoft/vscode#56722]
Does vscode.window.showInformationMessage('string') have an option like a checkbox to provide to an option for developer to select not to remind again ??

**Comment by Nufflee** [comment]
I don't think there's a built in way of doing that but you can pass a button/action as a parameter to `showInformationMessage(message: string, ...items: string[]): Thenable<string | undefined>` and then use a then in which you can check that button with that name is pressed and execute some logic that would tell your extension to not show this information message again.

You can learn more [here](https://code.visualstudio.com/docs/extensionAPI/vscode-api) and next time when submitting an issue, please use a more descriptive title so your issue can be answered more easily. And always check the docs first ;).

**Comment by Shreyas-vgr** [comment]
Thanks, would be great if you an built in feature to allow checkbox to support not to remind again.
