### ISSUE TITLE
Problem matcher `fileLocation` isn't copied when using `base`

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#56721]
- VSCode Version: 1.26.1
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Create a problem matcher which sets `fileLocation` to `"absolute"`
2. Create a new problem matcher which sets `base` to the first matcher
3. Notice that the paths will be treated as `relative` rather than `absolute`

Does this issue occur when all extensions are disabled?: Yes/No

/cc @dbaeumer

**Comment by dbaeumer** [comment]
This works for me in an example like this

```json
			"problemMatcher": [{
				"base": "$eslint-stylish",
				"fileLocation": "relative"
			}]
```

**Comment by eamodio** [comment]
Here is the "step 1" problem matcher:
https://github.com/eamodio/vscode-tsl-problem-matcher/blob/master/package.json#L35-L55

Here is the "step 2" one:
https://github.com/eamodio/vscode-tsl-problem-matcher/blob/master/package.json#L84-L99

If I remove `"fileLocation": "absolute" from the 2nd one, the matched problems will come out as relative. Also it seems that `applyTo` has the same issue, hence why I repeated it here.

**Comment by dbaeumer** [comment]
Never thought about that someone does this in package.json, but it should be legal. Needs some more investigation.

**Comment by dbaeumer** [comment]
Fixed it but will push to master beginning of November. We are in end game.

**Comment by dbaeumer** [comment]
See https://github.com/Microsoft/vscode/tree/dbaeumer/56721

**Comment by dbaeumer** [comment]
Merged PR into master.
