### ISSUE TITLE
Customizable menu seperator color

### ISSUE THREAD

**Issue by morgzz** [Microsoft/vscode#56730]
I've looked everywhere, but  couldn't find a parameter for customizing the menu seperators.
It would be nice, if we had an option to set the color of seperators.

![vscode-feedback_menu-seperators](https://user-images.githubusercontent.com/880477/44295718-bc55c600-a263-11e8-9a1b-ef40f1e1c713.png)

**Comment by bpasero** [comment]
@cleidigh fyi the top menu bar is `workbench-menu`, not `menus` (which is more for the command based registration of things).

**Comment by cleidigh** [comment]
@bpasero 
I guess I need a cheat sheet ;-o !

**Comment by bpasero** [comment]
Added `menu.separatorBackground`
