### ISSUE TITLE
The code is unclear when I use VSCode, but Atom not.

### ISSUE THREAD

**Issue by mikisama** [Microsoft/vscode#56733]
- VSCode Version: 1.26.1
- OS Version: MacOS Mojave Beta

Steps to Reproduce:

1. Just open some code with VSCode

Does this issue occur when all extensions are disabled?: Yes

**Comment by kounelios13** [comment]
what do you mean unclear?

**Comment by jeroenvisser101** [comment]
Possible dupe of #51132

**Comment by sandy081** [comment]
@mikisama Please provide proper summary, description and steps to reproduce the issue

**Comment by mikisama** [comment]
This issue is on the whole the same as #51132. I‘m sorry for the lack of description. Thank you for all help!
