### ISSUE TITLE
Locking to Launcher defaults to an old version

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5673]
- VSCode Version: 1.0.1-alpha
- OS Version: Ubuntu 15.10

Steps to Reproduce:

1. Install/Run an old alpha version on Ubuntu
2. Lock to Launcher
3. Install/Run the latest alpha
4. Unlock and Re-lock to Launcher
5. Close and Reopen Code

Actual:
When reopening Code it defaults to an old commit.

**Comment by Tyriar** [comment]
Tried to reproduce, could not see anything particularly out of the ordinary so going to close.
