### ISSUE TITLE
[scss] problem with mixin

### ISSUE THREAD

**Issue by Babelfisch** [Microsoft/vscode#56743]
Issue Type: <b>Bug</b>

The syntax checker tells me 4 errors in this SCSS code:

```scss
@mixin sc-cols($postfix) {
	.sc-col#{$postfix}-2 {
		@include flex-basis(100%);
		max-width: 100%;
	}
}
```

But the SCSS mixin definition is correct.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:31:26.156Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (1.90GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
swift|Kas|0.0.3
flutter-snippets|ale|0.0.2
vscode-intelephense-client|bme|0.8.8
dart-code|Dar|2.17.1
flutter|Dar|2.17.1
vscode-html-css|ecm|0.2.0
sftp|lix|1.3.10
vscode-language-pack-de|MS-|1.26.3

(3 theme extensions excluded)

</details>

**Comment by Nufflee** [comment]
I'm not sure @Babelfisch but I'm sure this will help someone who knows more about it!

**Comment by octref** [comment]
The root cause is the parser generates error when using Selector Interpolations with numbers

```scss
.#{$foo}-1 {

}
```
