### ISSUE TITLE
Insert Tabs Instead of Spaces No Longer Works

### ISSUE THREAD

**Issue by robbpriestley** [Microsoft/vscode#5674]
- VSCode Version: 1.0.0
- OS Version: OSX El Cap 10.11.4

Steps to Reproduce:

1. Code --> Preferences --> User Settings
2. In settings.json, add `"editor.insertSpaces": false` and save
3. Restart VSCode
4. Open a source code document in the editor and position cursor somewhere
5. Hit tab key

Expected behaviour: a tab `\t` character is inserted
Actual behaviour: spaces are inserted (4 in my case)

Note: previously worked. Seems to have stopped working with 1.0.0 release.

**Comment by isidorn** [comment]
Hi @robbpriestley ,
 
One user already encountered a similar issue, please check it out as I explain the reasoning behind this
https://github.com/Microsoft/vscode/issues/5276

**Comment by robbpriestley** [comment]
@isidorn yes that is the case. Thank you.

**Comment by iSchlicht** [comment]
+same issue
