### ISSUE TITLE
Terminal issues

### ISSUE THREAD

**Issue by luis-velasquezg** [Microsoft/vscode#56746]
Issue Type: <b>Bug</b>

After resizing the VS Code window and while working on a Terminal, the text in the Terminal doesn't rearrange back or, simply, it gets distorted.
Plus, when the VS Code window is resized, the Terminal editor doesn't show the text that is being typed until the VS Code window is maximized back again.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU B830 @ 1.80GHz (2 x 1796)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.89GB (0.91GB free)|
|Process Argv|C:\Users\Luis\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|67%|

</details>Extensions: none

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
