### ISSUE TITLE
VSCode Path setup

### ISSUE THREAD

**Issue by todeosasa** [Microsoft/vscode#56747]
Trying to set the path for git in vscode user setting
Not sure what went wrong, I did:
1. Opened the user setting
2. Typed in the path "C:\\Program Files\\Git\\bin\\git.exe" in user settings tab
3. Clicked on the pen icon to the left of "git.path": null roll and select "Copy to Settings" which was the only option
4. Error occurs at bottom right corner "Can not add index to parent of type string"

![error](https://user-images.githubusercontent.com/14203415/44302489-902b5b00-a2de-11e8-87fb-96d30f128b58.png)

**Comment by todeosasa** [comment]
Apologize for the noobish question, tried every searching keywords but this seems to be to dumb to become a question or an issue for anyone else....

**Comment by nealot** [comment]
Hey, try this:
```
{
    "git.path": "[your path here]",
}
```

**Comment by todeosasa** [comment]
![newsettinggui](https://user-images.githubusercontent.com/14203415/44303986-160dcd00-a304-11e8-8497-bc620a532092.png)
I am struggling to find the place to input the path for git in the "new settings editor" as well. =.(

**Comment by nealot** [comment]
What do you mean "Saving it did nothing when checking before or after restarting VSCode."? What isn't working?

**Comment by todeosasa** [comment]
@nealot I typed in the path under the right side tab in both ways(one with only pathing, the other with `{git.path: ...}`), and tried to save by pressing Ctrl + S. Nothing happened nor was there any error. 
I have no idea how else could I save the change on `git.path`. The document from VSCode official site only says click on the pen-like icon to edit user setting with no detailed instruction. Tried google this, and did not find anyone with a similar issue with changing `git.path` from this UI.(most other ppl have a much more complicated problem it seems..)

**Comment by todeosasa** [comment]
![image](https://user-images.githubusercontent.com/14203415/44306139-55a4db00-a33d-11e8-912e-c902dcc62353.png)
Ok.. Tried it again, reinstalled VSC and git and restarted PC.
Did the following:
1. Opened User Settings and found `git.path`
2. In the right side of the panel with the title USER SETTINGS, typed in `"C:\\Program Files\\Git\\bin\\git.exe"
3. In the left side of the panel with the title DEFAULT USER SETTINGS, clicked the pen icon to the left of  `"git.path": null`.

**Comment by nealot** [comment]
Does git not work for you? Why are you changing the default git path?

**Comment by nealot** [comment]
Does git not work for you?

**Comment by sandy081** [comment]
@todeosasa Can you please replace the content in the right side with following

```json
{
"git.path": "C:\\Program Files\\Git\bin\\git.exe"
}
```

Looks like you entered an invalid json content
