### ISSUE TITLE
CompletionItem markdown docs fail at single-character bold & italics

### ISSUE THREAD

**Issue by ethall** [Microsoft/vscode#56749]
Issue Type: <b>Bug</b>

Developing a language-server based extension with the following dependencies:
```json
// ...
    "dependencies": {
        "vscode": "^1.1.21",
        "vscode-languageclient": "^4.4.2"
    }
// ...
```
It seems that whatever parser is being used to render CompletionItems with Markdown documentation has trouble formatting single-character bold and italics correctly.

I've included some test cases below that can be returned from the server's `onCompletion` handler.

<details>
<summary>Test Cases</summary>

```typescript
[
    {
        documentation: {
            kind: MarkupKind.Markdown,
            value: '*a* some words *b*'
        },
        label: 'fail1'
    },
    {
        documentation: {
            kind: MarkupKind.Markdown,
            value: '*a* some words *bc*'
        },
        label: 'fail2'
    },
    {
        documentation: {
            kind: MarkupKind.Markdown,
            value: '*a* some \
words *bc*'
        },
        label: 'multiline-failure'
    },
    {
        documentation: {
            kind: MarkupKind.Markdown,
            value: '*a* some\nwords *b*'
        },
        label: 'newline-fail1'
    },
    {
        documentation: {
            kind: MarkupKind.Markdown,
            value: 'pre words *bold* more words\n*a* some\nwords *b*'
        },
        label: 'newline-fail2'
    },
    {
        documentation: {
            kind: MarkupKind.Markdown,
            value: '*a* some words *b* post words'
        },
        label: 'postwords-fail1'
    },
    {
        documentation: {
            kind: MarkupKind.Markdown,
            value: '*a* some words *bc* post words'
        },
        label: 'postwords-fail2'
    },
    {
        documentation: {
            kind: MarkupKind.Markdown,
            value: 'pre words *a* some words *b* post words'
        },
        label: 'prepostwords-fail1'
    },
    {
        documentation: {
            kind: MarkupKind.Markdown,
            value: 'pre words *a* some words *bc* post words'
        },
        label: 'prepostwords-fail2'
    },
    {
        documentation: {
            kind: MarkupKind.Markdown,
            value: 'pre words *a* some words *b*'
        },
        label: 'prewords-fail1'
    },
    {
        documentation: {
            kind: MarkupKind.Markdown,
            value: 'pre words *a* some words *bc*'
        },
        label: 'prewords-fail2'
    },
    {
        documentation: {
            kind: MarkupKind.Markdown,
            value: '*ab* some words *cd*'
        },
        label: 'pass1'
    },
    {
        documentation: {
            kind: MarkupKind.Markdown,
            value: '*ab* some words *c*'
        },
        label: 'pass2'
    },
    {
        documentation: {
            kind: MarkupKind.Markdown,
            value: 'pre words *ab* some words *cd*'
        },
        label: 'prewords-pass1'
    },
    {
        documentation: {
            kind: MarkupKind.Markdown,
            value: 'pre words *ab* some words *c*'
        },
        label: 'prewords-pass2'
    },
    {
        documentation: {
            kind: MarkupKind.Markdown,
            value: 'pre words *ab* some words *cd* post words'
        },
        label: 'prepostwords-pass1'
    },
    {
        documentation: {
            kind: MarkupKind.Markdown,
            value: 'pre words *ab* some words *c* post words'
        },
        label: 'prepostwords-pass2'
    },
    {
        documentation: {
            kind: MarkupKind.Markdown,
            value: '*ab* some words *cd* post words'
        },
        label: 'postwords-pass1'
    },
    {
        documentation: {
            kind: MarkupKind.Markdown,
            value: '*ab* some words *c* post words'
        },
        label: 'postwords-pass2'
    },
]
```
</details>

The provided test cases are currently for italics, but also apply to bold.

For quick triage reference, first test case is rendered as
>*a\* some words \*b*

when it should be rendered as
>*a* some words *b*

as seen the following image 
![vscode-completionitem-markdown-failure](https://user-images.githubusercontent.com/6527226/44303374-4e65d900-a30d-11e8-9641-ca12106c070a.png)

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (8.45GB free)|
|Process Argv|C:\Users\Evan Hall\AppData\Local\Programs\Microsoft VS Code\Code.exe C:\Source\project-directory|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by jrieken** [comment]
@ethall Not sure sure this is actually a but. Checkout the marked demo page: https://marked.js.org/demo/?text=a*%20some%20words%20*b%0A

**Comment by jrieken** [comment]
a* some words *b

^ The same is actually true for markdown in GH. Closing this as designed.

**Comment by ethall** [comment]
I don't think I've communicated the issue properly, since GitHub renders `*a* some words *b*` properly (without backticks): *a* some words *b*.

The example I provided ("a some words b") was the minimum failure case, but seems to be causing some confusion. Here's a real-world example:
#### Raw, prerendered string:
> `Get or set the offset *b* used by the *mx + b* operation to a number from -1e+12 to +1e+12. Defaults to 0.`

#### Same string rendered *incorrectly* in VSCode:
![image](https://user-images.githubusercontent.com/6527226/45495235-d7bbd000-b740-11e8-81c7-cd2b80b1eb70.png)

#### Same string rendered *correctly* on the Marked demo page:
[https://marked.js.org/demo/?text=Get%20or%20set%20the%20offset%20*b*%20used%20by%20the%20*mx%20%2B%20b*%20operation%20to%20a%20number%20from%20-1e%2B12%20to%20%2B1e%2B12.%20Defaults%20to%200.%0A](https://marked.js.org/demo/?text=Get%20or%20set%20the%20offset%20*b*%20used%20by%20the%20*mx%20%2B%20b*%20operation%20to%20a%20number%20from%20-1e%2B12%20to%20%2B1e%2B12.%20Defaults%20to%200.%0A)

#### Same string rendered *correctly* on GitHub:
Get or set the offset *b* used by the *mx + b* operation to a number from -1e+12 to +1e+12. Defaults to 0.

**Comment by jrieken** [comment]
Ok, thanks for clarifying. We should probably update our dependency here...

**Comment by jrieken** [comment]
I have updated to marked 0.5.0 which has fixed this. Closing
