### ISSUE TITLE
.editorconfig built-in support for VSCode

### ISSUE THREAD

**Issue by nevinvalsaraj** [Microsoft/vscode#56742]
VSCode does not support/obey coding styles specified in .editorconfig file, out of the box. This functionality is currently provided by [EditorConfig for VS Code](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) plugin. 

[Editorconfig](https://editorconfig.org/) is a specification for coding styles and environment preferences to be obeyed while contributing/modifying source code. This is a feature increasingly supported by text editors of late as well as popular IDEs such as entire IntelliJ suite and Visual Studio 2017 as well. Can we have support for .editorconfig file built right in VS Code as well? 

The EditorConfig website (linked above) contains details on availability and support over different platforms.

**Comment by sandy081** [comment]
AS you said, there is an Editor config extension for this. I do not think we have plans to make it built in.

**Comment by zomp** [comment]
EditorConfig is [present](https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options) in Visual Studio, which may be confusing (at least I thought it is working even in VS Code).

**Comment by matthias-ccri** [comment]
Duplicate ticket: https://github.com/microsoft/vscode/issues/111396
