### ISSUE TITLE
Install extensions without restarting the editor

### ISSUE THREAD

**Issue by mquandalle** [Microsoft/vscode#5675]
I searched on the issue tracker and I wasn’t able to find an open discussion on this feature improvement. So here it is, the idea would be to remove the “Restart Code” step that we have to do after the installation of a new extension and which breaks the workflow (for instance if you have unsaved files you need to make a decision on them) and isn’t applied on every Code instances (cf. #3268).

I understand that from a technical point of view, it is easier to restart the editor if its code base changed because of a new extension. However it should still be possible to implement some dynamic extension loading with the correct abstractions and some engineering effort. So I would be happy if this issue could host the discussion on the technical challenges involved and the willingness to make dynamic loading happen.

**Comment by alexandrudima** [comment]
There are some things that are easy and some things that are not :).

All the extension point handlers are (through API shape) forced to be written as listeners, so all of them would correctly get a "late to the party" extension description. So from an infrastructure point of view, we would need to ping all extension hosts and renderers processes from the shared process that manages extensions and inform everybody there is a new extension available.

What I cannot tell is if we have places where we cache things or where we make decisions that cannot be revisited.

For example, if a "late to the party" extension contributes a new language (for file extensions .alex), if you open a file before the extension is installed it stays open in the `plaintext` language and new .alex files that you open will get the new language association. In this case, there is no real code prepared to go back and re-evaluate the language association decision.

Perhaps we should just turn this on from the infrastructure side and deal with the bugs on a case by case basis. Possible issues: in the users of `extensionService.onReady` that need to wait for extensions to be scanned before taking a decision.

**Comment by ritwickdey** [comment]
An extension ['Live Server'](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServe). Please give a try 😄. 
https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer

**Comment by mjbvz** [comment]
I believe this was added in 1.31: https://code.visualstudio.com/updates/v1_31#_no-reload-on-install
