### ISSUE TITLE
VSCode x64-1.26.0 fails to launch on Windows 7

### ISSUE THREAD

**Issue by sheldonfernandes** [Microsoft/vscode#56750]
- VSCode Version: VSCodeUserSetup-x64-1.26.0
- OS Version: Windows 7 Enterprise x86_64

I updated my VSCode from  x64-1.19.2 to  x64-1.26.0 using the usual automatic update path.
The update completed successfully (or so it seems) but the application did not launch and simply crashed without an error.
I tried the latest insider build VSCodeUserSetup-x64-1.27.0-insider but that did not help either

Note that **Version  VSCodeSetup-x64-1.19.2 runs without a problem.** 
Steps to Reproduce:

1. Install visual studio code VSCodeUserSetup-x64-1.26.0 . 

Does this issue occur when all extensions are disabled?: Yes

Attaching the log i pulled form C:\Users\sheldon_fernandes\AppData\Local\Temp\VSCode Crashes. I hope its the right one. Let me know if there are any other i need to attach.
[operation_log.txt](https://github.com/Microsoft/vscode/files/2299918/operation_log.txt)

**Comment by sheldonfernandes** [comment]
Attaching the log i pulled form C:\Users\sheldon_fernandes\AppData\Local\Temp\VSCode Crashes. I hope its the right one. Let me know if there are any other i need to attach.
[operation_log.txt](https://github.com/Microsoft/vscode/files/2299912/operation_log.txt)

**Comment by joaomoreno** [comment]
@sheldonfernandes What happens when you try to open Code?

**Comment by sheldonfernandes** [comment]
@joaomoreno nothing shows up on the screen. The application crashes without any message.

**Comment by sheldonfernandes** [comment]
@joaomoreno have attached a operation_log.txt log file i found. If you can point me to any others I can provide those.

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by joaomoreno** [comment]
Possible dupe #56810

**Comment by sheldonfernandes** [comment]
@bpasero  

- `code --verbose` did not return any output.
- And I cannot get inside VS Code to perform steps 2 and 3

I could not find any other logs besides the C:\Users\sheldon_fernandes\AppData\Local\Temp\VSCode Crashes\operation_log.txt log  which I had attached in the defect. 
Is there any other log file I should be looking for?

Thanks!
