### ISSUE TITLE
Have search match include filename

### ISSUE THREAD

**Issue by tansaku** [microsoft/vscode#56757]
I'd like the text search feature to also match the filename, e.g. I am searching for "changelog" but a file called "changelog" does not show up unless it has the words "changelog" appearing within it.  I find this counter-intuitive and confusing.  I think the default should be to match words in the file contents and filename

**Comment by roblourens** [comment]
I disagree. Quickopen searches file names, text search searches file contents. I think these are very different workflows.

**Comment by tansaku** [comment]
@roblourens sorry to hear you disagree - personally they are identical workflows to me ...  if I'm looking for, say a changelog, I want to see a file called that or anything that mentions it, i.e. that's a single workflow.

Even if one wanted to separate the two workflows, including filenames could still be an option on the search, and there could be a user setting to make it default include or not - then vscode would support my workflow and yours and others - sounds great doesn't it?

Thanks for leaving the issue open to increase the chances that others might chime in with information on their preferred workflow rather than just limiting the discussion to covering yours and mine ...

**Comment by Jawz84** [comment]
I'd love VSCode to include filenames in the search. Even if it would only be an optional thing I could enable. Thanks @tansaku for bringing this up.

**Comment by grgarcia-ms** [comment]
Me too, actually filed a feature request without noticing this thread. I don't know any other way to search for files in VSCode, I just don't. I figured they would be under 'search' but no, if there is a way I would like to know, and would suggest to make it more visible, or if possible, including it within the search panel

**Comment by roblourens** [comment]
Quick open (ctrl+p/cmd+p) searches files

**Comment by grgarcia-ms** [comment]
Nice! Any way of leaving that bar there? Not fond of shortcuts, but will do for now, thanks

**Comment by letmaik** [comment]
I'm also missing this. Ideally I also would like it if I could do a filename-only search by leaving the main search field empty but filling the "files to include" field.

**Comment by johanovic** [comment]
Here is a use-case: when replacing the name of a function/variable in the entire app often there are also templates (someFunction.html) that should also be changed... In this case it would be ideal to replace a string in both the text and the filenames.

**Comment by chadlavi** [comment]
No one in this thread introduced the notion of a user-configurable setting to allow this. That would be a nice way to handle this; no need for it to be all-or-nothing.
