### ISSUE TITLE
vs code json files not responding right

### ISSUE THREAD

**Issue by dman1969** [Microsoft/vscode#56752]
Issue Type: <b>Bug</b>

edit icon not working have to manually put everything in user settings plus the user settings or any json file has no color all plain white text, default user seetings has color and can not get a fresh vs code install keep getting the same one everytime

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU  N2830  @ 2.16GHz (2 x 2167)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.89GB (0.58GB free)|
|Process Argv|C:\Users\danny\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|36%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-eslint|dba|1.4.12
gitlens|eam|8.5.5
vscode-great-icons|emm|2.1.41
vscode-clang|mit|0.2.2
python|ms-|2018.7.1
cpptools|ms-|0.18.1
debugger-for-chrome|msj|4.8.2
vscode-icons|rob|7.25.0

</details>

**Comment by sandy081** [comment]
- Does this also happen when you disable all installed extensions?
- Can you see if there are any errors in the dev tools console?
- Can you please provide a screenshot?
