### ISSUE TITLE
Debugger

### ISSUE THREAD

**Issue by rogerjd** [Microsoft/vscode#56751]
Issue Type: <b>Bug</b>

Hi,
When stepping though code with the debugger (F10), why does the cursor (current line), jump back to a previous line, then forward again?
Thank you

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Athlon(tm) II X2 220 Processor (2 x 2812)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.75GB (1.40GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.15.2
Go|ms-|0.6.88
team|ms-|1.136.0

</details>

**Comment by isidorn** [comment]
Debuggers behave like that sometimes.
What are you debugging and can you please provide some reproducable steps? Like an example program? Thanks a lot
