### ISSUE TITLE
syntax highlighting

### ISSUE THREAD

**Issue by LexRiver** [Microsoft/vscode#56758]
After the last update if I have a line with comment like this:
```typescript
export /* comment */ class MyClass{
...
}
```
then I have a bug with syntax highlightning inside this class.
Previous version of vscode was fine.
It's a typescript *.ts file.

**Comment by Nufflee** [comment]
A screenshot could be useful here. And can you specify what version were you on when it worked wnad what version are you one now?

**Comment by LexRiver** [comment]
Screenshot is below

![vscode-bug](https://user-images.githubusercontent.com/1415005/44309639-75d2a980-a3d2-11e8-8532-f6b1831446b4.jpg)


Current version:

Version: 1.26.1
Commit: 493869ee8e8a846b0855873886fc79d480d342de
Date: 2018-08-16T18:38:57.434Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Previous version I don't know, sorry.

**Comment by jackhorton** [comment]
This may be related to a bug I just noticed when editing ChakraCore.

https://github.com/Microsoft/ChakraCore/blob/769922256afe021177babc675774b18e9cf54cf2/lib/Runtime/Library/InJavascript/Intl.js#L593-L601

After line 595, the majority of the rest of the document is interpreted as a string. Removing the end-of-line comment does not help. This worked in 1.25.x, but I don't know if it broke with 1.26 or 1.26.1

**Comment by jackhorton** [comment]
Minimal repro:

![image](https://user-images.githubusercontent.com/4370013/44325034-5ce6ea00-a40c-11e8-86dd-77fbffc5e5b2.png)

It specifically fails when concatenating strings across newlines when the trailing + has a space after (note that I have whitespace on -- the trialing space in the failure case is important)

**Comment by mjbvz** [comment]
@jackhorton Please open a separate issues

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript-TmLanguage/issues/650 to track this upstream

**Comment by jackhorton** [comment]
Is TypeScript-TmLanguage the preferred repo for my issue as well?

**Comment by mjbvz** [comment]
yes
