### ISSUE TITLE
XML + XSLT Transformation

### ISSUE THREAD

**Issue by datauduong** [Microsoft/vscode#56753]
Issue Type: <b>Feature Request</b>

Please Add XML Transformation (XSLT)

Thanks.
VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

**Comment by beastdestroyer** [comment]
I believe VSCode natively supports XSL, which means it should show some highlighting for XSLT too. If not, find some extensions such as XML Tools by dotjoshjohnson and others
