### ISSUE TITLE
Error: connect ENOENT \\.\pipe\winpty-conout..

### ISSUE THREAD

**Issue by devchacha** [Microsoft/vscode#56764]
- VSCode Version: 1.26.1 Stable
- Node.js 8.9.3
- OS Version: 10 64-bit

Steps to Reproduce:

1. Open Visual Studio Code.
2. Terminal doesn't working.
3. Fixed an everything you all an advice on Github and StackOverflow.
4. Edited user setting 
5. Clicked Toggles Developer Tools then get errors.

Does this issue occur when all extensions are disabled?: Yes

![capture](https://user-images.githubusercontent.com/38471605/44310816-db408d80-a406-11e8-8a29-7b02498aff62.JPG)

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
