### ISSUE TITLE
bracketPairColorizer default setting

### ISSUE THREAD

**Issue by hsk** [Microsoft/vscode#56762]
BracketPairColorizer is nice plugin.
However default setting is very heavy.
Please change default setting of bracketPairColorizer as follow:

    "bracketPairColorizer.scopeLineRelativePosition": false,
    "bracketPairColorizer.showHorizontalScopeLine": false,
    "bracketPairColorizer.showVerticalScopeLine": false,
    "bracketPairColorizer.timeOut": 100,

**Comment by hsk** [comment]
I think this setting is new Microsoft conspiracy. LOL

**Comment by hsk** [comment]
I think that it is better to change it so as not to drop Microsoft's reputation.

**Comment by Nufflee** [comment]
I'm not too sure what you're about but `Bracket Pair Colorizer` is not an extension made by Microsoft so you should open an issue [here](https://github.com/CoenraadS/BracketPair/issues).

**Comment by sandy081** [comment]
Please file an issue against the Bracket Pair Colorizer extension
