### ISSUE TITLE
Editor windows goes blank in low memory conditions

### ISSUE THREAD

**Issue by evancacka** [Microsoft/vscode#5676]
- VSCode Version: 1.0.0 (1.0.0) (2016-04-13T10:59:46.727Z)
- OS Version: Macintosh 10.10.5 (14F1713)

Steps to Reproduce:

Pre-requisite: Mac is memory starved -- I have FireFox and Safari sessions both running which are consuming GB of memory
1. Open any code file

Results:
Display is completely blank.  You can tell the editor believes stuff is there (it will scroll the window, etc), but you cannot see anything in your editor window.

Closing down the FireFox and Safari sessions consuming the large amounts of memory, and then restarting vscode will cause the code file to display normally again.

**Comment by alexandrudima** [comment]
I have seen issues like this in Chromium. e.g. https://bugs.chromium.org/p/chromium/issues/detail?id=593971

**Comment by alexandrudima** [comment]
fyi @bpasero -- this might be happening now on OSX.

**Comment by bpasero** [comment]
Since this issue is rather old, I am closing this and ask anyone to open a new issue if this is still happening.
