### ISSUE TITLE
Changing settings can fail silently

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#56768]
From https://github.com/Microsoft/vscode/issues/50249#issuecomment-414102996

- Set `editor.parameterHints` which has been replaced
- In the settings UI, set `"editor.parameterHints.enabled"`
- The change is made in the JSON but doesn't apply because of `editor.parameterHints`.
- Errors are written in the devtools console but there's no other way to know about the conflict.

@sandy081 Should these also show a notification error to the user?

https://github.com/Microsoft/vscode/blob/b6411f27b0e41588fa897d51c34eafb636f6cbae/src/vs/platform/configuration/common/configurationModels.ts#L270-L274

**Comment by roblourens** [comment]
I'm not sure of the right fix for this, for some reason this message is printed twice on startup from the same line. And this class doesn't currently use dependency injection, and is referenced in a bunch of places, and I don't want to spam the user with too many notifications.

I think we would want to show the notification on startup, and also just when the relevant setting is edited. But it's kind of a weird case. We also probably need a better way to show "unknown" setting entries like `editor.parameterHints`.

**Comment by dceddia** [comment]
I was bitten by this change. I don't think I saw a notification about it, just the yellow squiggly line under `"editor.parameterHints"`, which was subtle enough that I missed it.

A similar change bit me a while back, where `editor.hover` changed to `editor.hover.enable` and it took some hair pulling and googling before I came upon a Github issue that solved it.

(fwiw, I create screencasts and I like to turn off all the popups to cut down on distraction)

Deprecated settings seems like a thing that wouldn't be too common. Would it make sense to keep a list of them, and notify if a deprecated setting is present in `settings.json`?

**Comment by julianlam** [comment]
Is there no backwards compatibility for the settings? I'd assume that if I set `editor.parameterHints`, that the setting itself would be carried over even if `editor.parameterHints` is now `editor.parameterHints.enabled`.

**Comment by sandy081** [comment]
@roblourens I am not aware of any. Its the responsibility of the owner of the setting to make sure it is backward compatible.

**Comment by rzhao271** [comment]
Closing as wontfix for now; I only remember seeing one newer issue related to this, and it was for a non-builtin extension.
