### ISSUE TITLE
Allow "Do Not show Again" for "Tokenization is skipped" message

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#56773]
Tokenization is skipped for lines longer than 20k characters for performance reasons.

Current each time I need to close the notification, which is annoying:

![image](https://user-images.githubusercontent.com/4033249/44313734-66e3fb00-a3c2-11e8-8c9b-8c80565dac8c.png)

**Comment by inwardmovement** [comment]
Any plan on that?

**Comment by lramos15** [comment]
<img width="460" alt="Screen Shot 2019-07-30 at 11 15 07 AM" src="https://user-images.githubusercontent.com/4544166/62154342-54a15b00-b2bb-11e9-95bb-a04ac295a9a5.png"> I do not see an option to not show this error again.

**Comment by lramos15** [comment]
This works as expected, I just wasn't aware it was hidden under the gear
