### ISSUE TITLE
tsc --watch

### ISSUE THREAD

**Issue by Xiodra** [Microsoft/vscode#56778]
Issue Type: <b>Feature Request</b>

You want to integrate the 'tsc --watch' switch in the bottom status bar and, when opened, output compiled information in the Problem Panel or Terminal Panel

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

**Comment by sandy081** [comment]
You can create an extension to do it.
