### ISSUE TITLE
Console.ReadLine() causes Debug Console not to update

### ISSUE THREAD

**Issue by AchilleMerendino** [Microsoft/vscode#56772]
- VSCode Version: 1.26.1
- OS Version: Manjaro Linux 18.0 Beta 5 KDE
- Programming Language: C# .Net Core

Using a Console.ReadLine() after a Console.Write() causes the Debug Console not to show the output text. However when adding a New Line either using Console.WriteLine() or adding "\n" to the text, output text written before the New Line is shown. The correct text output also shows once I stop the execution.

`Console.Write("Write a word:"); `
`Console.ReadLine();`
This produces no output in the Debug Console.
![incorrect](https://user-images.githubusercontent.com/25868765/44313638-2b6e1e80-a40c-11e8-9105-c0386bb26091.png)

`Console.Write("Write a word:\n"); `
`Console.ReadLine();`
This produces the correct output in the Debug Console.
![correct](https://user-images.githubusercontent.com/25868765/44313629-15605e00-a40c-11e8-9e7d-a38e27b18ee8.png)

Also, I'm not able to send an input to the app through the Debug Console (thus triggering Console.ReadLine), but I guess this is just me being an ignorant beginner.

This issue occurs even when running `code --disable-extensions`

**Comment by weinand** [comment]
Programs cannot read input from the Debug Console (because the Debug Console is really a REPL).
In order to allow you program to read from stdin, you'll have to configure your debug session to use the integrated terminal. Please check the documentation of your C#/.net extension for how to do this.
