### ISSUE TITLE
How to Select the content of the tag in vscode?

### ISSUE THREAD

**Issue by biij5698** [Microsoft/vscode#5677]
How to Select the content of the tag in vscode like sublime with the key: Ctrl + Shift + A

**Comment by alefragnani** [comment]
Hi @biij5698 ,

I think it doesn't exist _in the core_, but maybe this extension [expand-region](https://marketplace.visualstudio.com/items?itemName=letrieu.expand-region) does the trick.

Hope this helps

**Comment by dbaeumer** [comment]
@jrieken don't know what our keys are right now to expand the selection. Can you help.

**Comment by KayLeung** [comment]
@dbaeumer 

https://code.visualstudio.com/docs/editor/editingevolved
"Shrink/expand selection"

It seems VSCode has this feature but doesn't work in my v1.0.0

**Comment by biij5698** [comment]
It is very regret

**Comment by jrieken** [comment]
for html there are issues, see #1808 and #4795

**Comment by Skura23** [comment]
`Shift+Alt+Right` will do the trick.
> Place the cursor inside the bracket (not directly next to a bracket) and execute editor.action.smartSelect.grow until everything inside the bracket is selected. The default shortcut is `Shift+Alt+Right`.
> 
> You can shrink the selection with editor.action.smartSelect.shrink which has the default shortcut `Shift+Alt+Left`.
[https://stackoverflow.com/questions/37835012/is-there-in-vscode-an-option-to-select-everything-between-matching-brackets](url)

**Comment by suit0r** [comment]
@Skura23 thanks. that was it

**Comment by peacefulseeker** [comment]
As an alternative could use a Ctrl+D to fast select text between tags =)
Seems that Ctrl+Shift+A does not work in VSCode as in Sublime
