### ISSUE TITLE
No icons in extention markeplace

### ISSUE THREAD

**Issue by oneslash** [Microsoft/vscode#56782]
Issue Type: <b>Bug</b>

I don't have any icons in my extention view.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:31:26.156Z)
OS version: Darwin x64 17.7.0
<img width="271" alt="screen shot 2018-08-20 at 08 24 39" src="https://user-images.githubusercontent.com/15870134/44323538-a8bc8200-a452-11e8-8a03-543eae94920b.png">
<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 5|
|Memory (System)|16.00GB (0.31GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
gitignore|cod|0.5.0
ansible-vault|dho|0.1.3
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.36
ansible|haa|0.2.8
terraform|mau|1.3.4
python|ms-|2018.7.1
Go|ms-|0.6.88
jenkinsfile-support|sec|0.1.0

</details>

**Comment by sandy081** [comment]
Can you please expand your side bar by resizing it. Icons are shown only when the side bar width is enough to show.
