### ISSUE TITLE
can we have account in vs code, that syncs all vscode configs and extension data accross all my devices.

### ISSUE THREAD

**Issue by saikatharryc** [Microsoft/vscode#56783]
well, 
like chrome does [syncs all data extensions and user settings accross all your devices you log in . ], 
if we have a vscode account , that syncs all my changes of settings and also the extensions and few essentials accross all my devices. 
so that it will be easy , not wasting time to setup and install all extension i need manually in defferent different systems.

it will be done by loging  in.

**Comment by sandy081** [comment]
duplicates #2743
