### ISSUE TITLE
enable/disable highlighting current line visual studio code

### ISSUE THREAD

**Issue by CestLou** [Microsoft/vscode#5678]
- VSCode Version: 1.0.0
- OS Version: 10.11.3

It would be very convenient to be able to toggle the line highlight feature. thus far I have not found a way to do this, or an open issue addressing this. apologies if this is a duplicate.

thanks vsc team!

**Comment by arraqib** [comment]
Add enable/disable feature or Remove default line highlighting. That will be better......

**Comment by alexandrudima** [comment]
Implemented with 0d5d779
