### ISSUE TITLE
python.formatting.provider yapf does not work

### ISSUE THREAD

**Issue by whiteWords** [Microsoft/vscode#56790]
Issue Type: <b>Bug</b>

I have follow this tips https://code.visualstudio.com/docs/python/editing#_formatting

it's still not work

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (8.53GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.12
tslint|eg2|1.0.36
vscode-language-pack-zh-hans|MS-|1.26.3
python|ms-|2018.7.1

</details>

**Comment by sandy081** [comment]
Please file an issue against https://marketplace.visualstudio.com/items?itemName=ms-python.python extension
