### ISSUE TITLE
Activating extension 'vscode.typescript-language-features' failed: Invalid Unicode escape sequence.

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#56792]
- VSCode Version: 1.27.0-insider 00649474f2e43a84c61ddbbbc356060257328372
- OS Version:

Steps to Reproduce:

1. Open a typescript project
2. 🐛 No typescript language services

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by sandy081** [comment]
@jrieken Could be related to changes done to nls?

![image](https://user-images.githubusercontent.com/10746682/44326337-9f83e300-a45b-11e8-9260-dcfebab01ed5.png)

**Comment by jrieken** [comment]
Hm, maybe... I see the errors but TypeScript works happily for me. Oh, this is windows...

**Comment by sandy081** [comment]
Do we need a new insiders build for this?

**Comment by jrieken** [comment]
It's on its way...
