### ISSUE TITLE
Weird selection behaviour for empty groups

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#56806]
Steps to Reproduce:

1. open 4 empty editor groups
2. click on them in the "open editors" view
=> 🐛 every click makes the entire view focused, not the group

![grid-tw](https://user-images.githubusercontent.com/900690/44330807-42425e80-a468-11e8-91a7-0768ec188975.gif)

**Comment by bpasero** [comment]
I had to revert due to https://github.com/Microsoft/vscode/commit/0e3a2219afbeed2996549468f6d656ce4713aeab#diff-175dcd61135308bda1aa5e1b240328a6L392

**Comment by isidorn** [comment]
@bpasero thanks for reverting, let me look into a proper fix

**Comment by isidorn** [comment]
Made sure the list is not empty now. Seems to work in all cases.

**Comment by bpasero** [comment]
There is still something weird going on:
* open 2 groups
* open 1 editor in each group
* click into the first editor
* click into the first group (it works)
* click into the second editor
* click into the first group 

=> it jumps to the editor

I think the intent is right, never allow to select a group if an editor is within.

**Comment by isidorn** [comment]
I actually like the current behavior.
It always jumps to the editor only if you actually changed the active group / editor. If there is no change it alows you to select what you want.

I can not fix this with the current apporach (that I am reacting on active editor / group change events and if the active group / editor stay the same I get no event). I am not reacting on my click events.

Closing as will not fix - like the behavior. I can reopen if give me some arguments why you find this weird.
