### ISSUE TITLE
minor functionality request

### ISSUE THREAD

**Issue by AlexanderZ11234** [Microsoft/vscode#56803]
Issue Type: <b>Feature Request</b>

Will you developing guys please add a minor functionality that when I define a function in Python, a ":" and an identation are automatically added upon tapping "Enter"?

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

**Comment by sandy081** [comment]
Please file an issue against python extension
