### ISSUE TITLE
选中代码片段后光标失灵

### ISSUE THREAD

**Issue by RoGoSo** [Microsoft/vscode#56808]
Issue Type: <b>Bug</b>

选中代码片段后要点击很多次鼠标才能重新选择代码

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3196)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (4.38GB free)|
|Process Argv|D:\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
prototxt|dmi|0.0.6
vscode-language-pack-zh-hans|MS-|1.26.3
python|ms-|2018.7.1
vscode-icons|rob|7.25.0
code-settings-sync|Sha|3.0.0

</details>

**Comment by sandy081** [comment]
Please file the summary, description and steps to reproduce in english.
