### ISSUE TITLE
Failed to install VS Code update

### ISSUE THREAD

**Issue by psychelzh** [Microsoft/vscode#56809]
Issue Type: <b>Bug</b>

Failed to install the latest update.

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.73GB (6.97GB free)|
|Process Argv|C:\Users\liang\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.2.3
better-toml|bun|0.3.2
compulim-vscode-closetag|Com|1.2.0
vscode-markdownlint|Dav|0.20.0
githistory|don|0.4.2
xml|Dot|2.3.2
gitlens|eam|8.5.5
git-project-manager|fel|1.6.1
vscode-mysql|for|0.3.0
matlab|Gim|0.9.0
gc-excelviewer|Gra|2.1.25
vscode-wordcount-cjk|hol|1.2.0
beautify|Hoo|1.3.2
r|Iku|0.6.1
r-lsp|Iku|0.0.7
rainbow-csv|mec|0.4.2
vscode-language-pack-zh-hans|MS-|1.26.3
cpptools|ms-|0.18.1
csharp|ms-|1.15.2
vsliveshare|ms-|0.3.535
bib|phr|0.3.0
material-icon-theme|PKi|3.5.3
java|red|0.29.0
vscode-icons|rob|7.25.0
markdown-preview-enhanced|shd|0.3.5
vscode-checkstyle|she|0.5.2
gitconfig|sid|1.0.1
searchdocsets-vscode|sil|1.0.1
vba|spe|1.2.0
pdf|tom|0.3.0
vscode-java-debug|vsc|0.11.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.8.0
vscode-maven|vsc|0.10.0
licenser|ymo|1.1.2
vscode-preview-server|yui|1.0.1

(1 theme extensions excluded)

</details>

**Comment by beastdestroyer** [comment]
You can just redownload from the website. It'll keep all your settings and extensions as long as you don't use the User-Distribution version.

**Comment by aanandranga** [comment]
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2301900/vscode-inno-updater.log)
Same issue while updating the vscode.
