### ISSUE TITLE
Editor no tabs: description part of label no longer overflows: ellipsis

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#56805]
Steps to Reproduce:

1. disable tabs
2. have a description part that overflows into actions:

![image](https://user-images.githubusercontent.com/900690/44330424-4457ed80-a467-11e8-84ef-4654ad9c853b.png)

=> 🐛 no more "..." in the description part of the label

Seems to be caused by this rule:

https://github.com/Microsoft/vscode/blob/6e559261f677793fea424c6eb5cb13d0301ffff1/src/vs/workbench/browser/parts/editor/media/notabstitlecontrol.css#L25

**Comment by jrieken** [comment]
@bpasero please provide steps to reproduce

<img width="833" alt="screen shot 2018-08-28 at 11 27 01" src="https://user-images.githubusercontent.com/1794099/44714322-5106c200-aab5-11e8-8613-1fc885ff74d6.png">

**Comment by bpasero** [comment]
Sorry, I had breadcrumbs enabled and was confused.
