### ISSUE TITLE
Add command resolving variable to tasks

### ISSUE THREAD

**Issue by n3rd4i** [Microsoft/vscode#56801]
- VSCode Version: 1.26.1
- OS Version: Windows [Version 10.0.17134.228]

Steps to Reproduce:

1. create a environment variable in tasks.json as specified in the [GH50766
](https://github.com/Microsoft/vscode/issues/50766)
2. the variable cannot be used, VSCode does not make the translation

Does this issue occur when all extensions are disabled?: N/A

**Comment by dbaeumer** [comment]
@n3rd4i did you try what I outline in the latest comment in #50766. As said your original example will not work. Can you provide an example that demos your problem?

**Comment by dbaeumer** [comment]
I see the problem but we can't abstract the way how shells access environment variables. To make your example work you can have three tasks (if you need to run in different shells) and have the task specify the shell it wants to use. Something like

```json
        {
            "type": "shell",
            "label": "PS-Task",
            "options": {
                "shell": {
                    "executable": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
                    "args": [
                        "-Command"
                    ]
                }
            },
            "command": "echo $env:foo"
        }

```

**Comment by dbaeumer** [comment]
Would that work for you?

**Comment by n3rd4i** [comment]
The idea was to have an environment variable calculated somehow for all my tasks, for example:
var: `$env:foo` is global and can be used across tasks.
if this cannot be used within WSL somehow, It does not help me because then I will need to set the default console to PS and relay all commands from PS to WSL, which breaks the actual point to default WSL (bash.exe) as my console.

**Comment by dbaeumer** [comment]
@isidorn can you point me to an example on how you use commands to resolve values. May be this is something we can easily add to tasks. That should then help with this secanrio

**Comment by isidorn** [comment]
@weinand is calling the variables resolving from [here](https://github.com/Microsoft/vscode/blob/20b2782ffa7ef868e04f93aea42d3c8462821702/src/vs/workbench/parts/debug/node/debugger.ts#L78)

**Comment by dbaeumer** [comment]
Thanks. How do you reference such a command variable in the launch.json?

**Comment by isidorn** [comment]
Here's an example `"processId": "${command:PickProcess}"`
And here is how the extension is contributing that it has a variable which uses the pick process command https://github.com/Microsoft/vscode-node-debug/blob/90879b496722ddfa53b8eb7508e36f8bc3a39140/package.json#L154

The only issue I see is that these variables are contributed under the `debugger` contribution. @weinand could we somehow make this more general? Or would @dbaeumer add a similar contribution under `tasks`

**Comment by weinand** [comment]
@dbaeumer it is no longer necessary to contribute debug specific "Variables". Any command can be used as a variable with the `${command:command-ID}` syntax.
The "Variables" mechanism is deprecated.

**Comment by weinand** [comment]
@n3rd4i Sorry, my statement from above is misleading: variables in launch.json and task.json are definitively **not** deprecated, only the "variables" section of the "debuggers" contribution point (see https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesdebuggers) is deprecated because it is no longer needed since every command can be used as a variable with the `${command:<command-id>}` syntax.

**Comment by n3rd4i** [comment]
can this issue be reopened ?

**Comment by dbaeumer** [comment]
I am reopening the issue to support command substitution in tasks. We have no plans to abstract env handling over shells.

**Comment by alexr00** [comment]
We now resolve commands in tasks.
