### ISSUE TITLE
Surface Precision Mouse scroll not responsive when using VSCode

### ISSUE THREAD

**Issue by xdvarpunen** [Microsoft/vscode#56800]
Please search existing issues to avoid creating duplicates. [Done]
Also please test using the latest insiders build to make sure your issue has not already been fixed: https://code.visualstudio.com/insiders/ [Done]

Use Help > Report Issue to prefill these. [DONE]
VSCode => Help => About
- VSCode Version: 1.26.1
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Buy Surface Precision Mouse
2. Scroll code vertically in VSCode

Launch with `code --disable-extensions` to check. Does this issue occur when all extensions are disabled?: Yes

In the nutshell Surface Precision Mouse scroll is not working as expected. In browser everything is fine, but in VSCode it does not stop when mouse scroll is stopped. Instead it keeps scrolling down.

**Comment by alexandrudima** [comment]
@xdvarpunen If you use the Surface Precision Mouse in **Chrome** and scroll in the editor at https://microsoft.github.io/monaco-editor/ , is the scrolling as you would expect ?

**Comment by xdvarpunen** [comment]
@alexandrudima As I stated it _works fine in browser_. I tested your given link https://microsoft.github.io/monaco-editor/ in **Chrome** and did not sense same happening there 😕

**Comment by xdvarpunen** [comment]
@alexandrudima It seems more Electron related: https://github.com/electron/electron/issues/8960 😮

**Comment by bpasero** [comment]
@xdvarpunen does it reproduce if you configure `window.smoothScrollingWorkaround: true`?

**Comment by xdvarpunen** [comment]
@bpasero Almost, it fixed it mostly. Scrolling is still slightly non-responsive when scrolling long file, but otherwise works in doable fashion 👍
