### ISSUE TITLE
BUG: Document saved with "Save as" not added to "Open Recent" menu

### ISSUE THREAD

**Issue by westurner** [Microsoft/vscode#5680]
- VSCode Version: 1.0.0
- OS Version: Fedora 23 x86_64

(A menu option to pre-fill this info would be great: https://github.com/Microsoft/vscode/issues/new?body=version_info )
```
Version 1.0.0
Commit fa6d0f03813dfb9df4589c30121e9fcffa8a8ec8
Date 2016-04-13T14:21:33.326Z
Shell 0.35.6
Renderer 45.0.2454.85
Node 4.1.1
```

Steps to Reproduce:

1. Install vscode from https://code.visualstudio.com/Docs/?dv=linux64_rpm and launch app
2. Type ``#!/usr/bin/env/python\nprint("Hello world!")``
3. Click "File" > "Save as" 
4. Click "Documents" > type  "example2.py" ("example3.py", "example4.py")
5. Click "File" > "Open Recent"
    * "~/Documents" shows in the Open Recent menu, but example2.py does not

**Comment by bpasero** [comment]
We only put things into the recent menu that you open from the native file picker or from the outside of Code into Code.

**Comment by westurner** [comment]
Okay. Pretty sure this is a bug (the dirname of the filename is added to the recent menu, but not the filename).
