### ISSUE TITLE
Explorer should support basename with dot

### ISSUE THREAD

**Issue by kutyel** [Microsoft/vscode#56812]
- VSCode Version: v1.26.1 (1.26.1)
- OS Version: macOS High Sierra v0.13.6 

When doing @reasonml, it's very annoying to have all those `**.bs.js` files generated (just like it was with @typescriptlang at the beginning), so I tried to ignore them in my file tree but it doesn't seem to work.

**Steps to Reproduce:**

1. Add this to your settings.json
```json
{
  "files.exclude": {
    "**/*.bs.js": { "when": "$(basename).re" }
  }
}
```
2. Reload, go to file explorer and see that you can still see the `*.bs.js` generated files. ⚠️ 

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by isidorn** [comment]
The problem is the double double extension in your setup.
So there is .bs.js, and the basename seems to take the .bs into account

fyi @bpasero 
I have no immediate plan to fix this -> backlog

**Comment by kutyel** [comment]
If you guide me more or less through the files involved I can provide a PR (I'm quite confident with TypeScript 😄)

**Comment by isidorn** [comment]
[Code pointer](https://github.com/Microsoft/vscode/blob/53e57b5ea03e19ec1002f1c0a2d69fa1dd2cc01b/src/vs/workbench/parts/files/electron-browser/views/explorerViewer.ts#L724)

We would accept a PR if it is clean and straight forward.

**Comment by kutyel** [comment]
Fixed it! 🎉

**Comment by kutyel** [comment]
I definitely want this issue to be fixed :)

**Comment by isidorn** [comment]
No need to reopen, there is already a duplicate here https://github.com/Microsoft/vscode/issues/59368
