### ISSUE TITLE
Failing to update

### ISSUE THREAD

**Issue by kaselis** [Microsoft/vscode#56816]
Issue Type: <b>Bug</b>

Once started, it shows that there is an update available and VSCode needs to be restarted ("Restart to Update.."). After clicking on it, VS Code restarts and update again is available. Checking version before and after the update they seem to be identical:

Version: 1.27.0-insider
Commit: fd610b4b6ab8d4735a4d84a2b59206ad3a9c8099
Date: 2018-08-17T05:18:51.696Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

VS Code version: Code - Insiders 1.27.0-insider (fd610b4b6ab8d4735a4d84a2b59206ad3a9c8099, 2018-08-17T05:18:51.696Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (4.96GB free)|
|Process Argv|C:\Users\nbk3415\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.4
python|ms-|2018.7.1

</details>

**Comment by kaselis** [comment]
Once I've closed all the running instances, but the last one, and clicked Restart to Update.. on the last running instance, it successfully has been updated.

**Comment by joaomoreno** [comment]
Good to know, closing for now.
