### ISSUE TITLE
Go to definition not working for sails application

### ISSUE THREAD

**Issue by AJ-Math** [Microsoft/vscode#56811]
- VSCode Version: 1.26.1
- OS Version: Windows 10

Steps to Reproduce:
1. Click go to definition or hover on a function.

Does this issue occur when all extensions are disabled?: Yes

Can't load the function inside services folder from controller or even in the same file.

**Comment by sandy081** [comment]
Please check if there is an extension supporting `sails`. If so, please file an issue against it.
