### ISSUE TITLE
(VS Code Insiders) Multiple clicks to expand and collapse folds

### ISSUE THREAD

**Issue by frankhale** [Microsoft/vscode#56818]
Issue Type: <b>Bug</b>

I'm using the daily build of VS Code Insiders and have noticed over the last week that folds now require multiple clicks to expand and collapse. It's sort of random how many times you have to click them to expand or collapse. Some folds operate normally but those are rare now. 

I'm editing JavaScript code if that helps.  I wish I could provide more information but I'm not sure what else to say. 

VS Code version: Code - Insiders 1.27.0-insider (6e559261f677793fea424c6eb5cb13d0301ffff1, 2018-08-20T08:36:52.887Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.96GB (10.95GB free)|
|Process Argv|C:\Users\frank\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
Bookmarks|ale|9.0.3
react-nitro-essentials|are|1.1.1
react-nitro-snippets|are|1.0.2
aurelia|Aur|1.0.3
vscode-custom-css|be5|2.7.1
vscode-icontheme-nomo-dark|be5|1.3.6
nebula-theme|Chi|1.2.1
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.14
githistory|don|0.4.2
xml|Dot|2.3.2
vscode-generate-getter-setter|DSK|0.5.0
vscode-babel-coloring|dza|0.0.4
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.36
vscode-great-icons|emm|2.1.41
vsc-material-theme|Equ|2.3.0
prettier-vscode|esb|1.6.1
code-runner|for|0.9.4
gc-excelviewer|Gra|2.1.25
beautify|Hoo|1.3.2
rest-client|hum|0.19.1
easy-icons|jam|0.3.1
love-launcher|Jan|1.0.5
sublime-babel-vscode|jos|0.2.10
vscode-icon-theme|jtl|1.6.2
theme-karyfoundation-themes|kar|18.0.1
Lua|key|0.0.9
vscode-simple-icons|Lau|1.8.4
typescript-javascript-grammar|ms-|0.0.43
debugger-for-chrome|msj|4.8.2
color-highlight|nau|2.3.0
pixelbyte-love2d|pix|0.1.17
material-icon-theme|PKi|3.5.3
polacode|pnp|0.2.2
vscode-icons|rob|7.25.0
code-settings-sync|Sha|3.0.0
vscode-parinfer|sha|0.6.2
bunker|sld|1.1.6
ayu|tea|0.15.0
yithemes|wan|0.7.0
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.8.0
ReactSnippets|xab|2.2.0
maple|yjt|1.2.7
markdown-pdf|yza|1.2.0

(115 theme extensions excluded)

</details>

**Comment by bl4met** [comment]
I was having the same issue and after reading this, I discovered if I click in the space to the right of the expand box, in the space between the box and the line, it would work every time.

**Comment by nealot** [comment]
@usernamehw That's https://github.com/Microsoft/vscode/issues/15888

**Comment by usernamehw** [comment]
No, stable version is working fine:
![screenshot 30](https://user-images.githubusercontent.com/9638156/44423739-88dea880-a58f-11e8-803a-06eb484a2873.png)

**Comment by rebornix** [comment]
Thanks all for the detailed information. I pushed a fix for it and let me know if you still run into issues.

**Comment by usernamehw** [comment]
Clicking is fixed, but SCM widget still broken.
