### ISSUE TITLE
PHP Included Libraries Function NOT PREDICTING

### ISSUE THREAD

**Issue by AmirMND** [Microsoft/vscode#56815]
Issue Type: <b>Bug</b>

no auto completion for those libraries I INCLUDED them from a file in my main script(PHP) 

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:11.471Z)
OS version: Windows_NT ia32 6.1.7601

**Comment by roblourens** [comment]
You need to use one of the PHP intellisense extensions for this intellisense
