### ISSUE TITLE
Small Syntax Highlighting Inconsistencies with CSS/SCSS

### ISSUE THREAD

**Issue by beastdestroyer** [Microsoft/vscode#56813]
Issue Type: Language Service Polish/Bug Report

An annoying thing that has been bugging me since I started using SCSS with VSCode is the small inconsistencies with themes when it comes to SCSS and CSS. Specifically, I'm going to be talking about attribute selectors and brackets as well as some bugs I found

- VSCode Version: 1.27.0-insiders
- OS Version: Windows 10 1803, 17134.228

> Note, using default dark to explain my examples
Reproducing Attribute Selector problem
1. In CSS Language, type something like this:
```css
p[data-theme="xd"] {}
```
2. In VSCode, the quotes are highlighted correctly (in that brownish colour) and so are the brackets, note this.
3. Switch it to SCSS mode, the brackets aren't highlighted in that colour, the quoted text is uncoloured and the attribute selector isn't highlighted in blue. After inspecting TM Scopes, it seems they are slightly different, which doesn't make sense to me since SCSS is essentially an extension to CSS, so surely they should have the same foundations?
Screenshots:
CSS Mode:
![image](https://user-images.githubusercontent.com/30497573/44336537-afa5bd80-a46f-11e8-860b-913c9fdbe46c.png)

SCSS Mode:
![image](https://user-images.githubusercontent.com/30497573/44336564-c0eeca00-a46f-11e8-81b9-6147e70b9f0b.png)

Reproducing Brackets problem
1. In CSS Language, type something like this:
```css
a:nth-child() {}
```
2. In VSCode, the brackets are highlighted the same as the pseudo-class.
3. Switch it to SCSS mode, the brackets aren't highlighted in that colour; it is the same problem: TM Scopes
Screenshots:
CSS Mode:
![image](https://user-images.githubusercontent.com/30497573/44336593-d82db780-a46f-11e8-8c97-9d50093020e0.png)

SCSS Mode:
![image](https://user-images.githubusercontent.com/30497573/44336624-f2679580-a46f-11e8-9624-4c88168897c9.png)

Finally, there is a weird error which occurs, this is very common with Math(s) functions such as calc() where for some reason, eventually the numbers don't get highlighted properly. To repro:
1. In SCSS, type this:
```scss
p {
  font-size: calc(10px + (56 - 10) * ((100vw - 320px) / (1920 - 320))); 
}
```
2. It highlights correctly for the most part (just that for some reason the * and / which are both operators don't seem to have a scope. Same issue occurs with CSS mode)
3. Switch to CSS mode and the 1920 and 320 at the end don't get highlighted, regardless of units.
4. TM Scopes yet again?
Screenshots:
CSS Mode:
![image](https://user-images.githubusercontent.com/30497573/44336657-11febe00-a470-11e8-8e6b-2ca71ba8ce99.png)

SCSS Mode:
![image](https://user-images.githubusercontent.com/30497573/44336665-1925cc00-a470-11e8-8b98-d55d150df43e.png)

Benefits of investigating:
- Would help with themes
- Solve missing polishes for a better overall look

Does this issue occur when all extensions are disabled?: Yes

**Comment by beastdestroyer** [comment]
Not relevant

**Comment by aeschli** [comment]
The css grammar and scss grammar are separate, so there can be differences. We get them from external repos, so it's not in our control.

Both emit `punctuation` scopes for the bracket.

But what results in the different color is that for css the `meta.selector.css` scope matches to a color. 
That's actually a bug with the default theme, as `meta` scopes should not be used to colorize.

![image](https://user-images.githubusercontent.com/6461412/44389956-826b1500-a52c-11e8-94e3-a7f39541a42e.png)

So I probably see if I can remove the `meta.selector` coloring from out default themes.
That's likely not what you wanted.

If you like bracket coloring, I suggest adding a custom rule with the coloring you want
```
"editor.tokenColorCustomizations": {
		"textMateRules": [
			{
				"scope": "punctuation",
				"settings": {
					"foreground": "#FF0000"
				}
			}
		]
	}
```

**Comment by aeschli** [comment]
- I fixed our default themes to not colorize 'meta.selector`. That fixes the `a:nth-child() {}` example.
- I filed https://github.com/atom/language-css/issues/147 against the css grammar for the `calc` example
- I created https://github.com/atom/language-sass/issues/257 against the scss grammar for the `p[data-theme="xd"] {}` example

**Comment by beastdestroyer** [comment]
Cool thanks!
