### ISSUE TITLE
Failed to install VS code update (error 32)

### ISSUE THREAD

**Issue by vijayanandmit** [Microsoft/vscode#56825]
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2302746/vscode-inno-updater.log)

When closing VS code, inno-update started running and trying to update VS code, and then crashed.

>The process cannot access the file because it is being used by another process

**Comment by powlam** [comment]
Is there any recommendation to recover VSCode after the crash during the update?  (I have had this problem updating to version 1.26.1).
Just to avoid reinstalling the extensions and reconfiguring the application manually...
