### ISSUE TITLE
Unable to Update VSCode

### ISSUE THREAD

**Issue by mcollier** [Microsoft/vscode#56823]
Issue Type: <b>Bug</b>

VS Code reports there is an update availabe.  I'm currently using version 1.26.0.  When VS Code attempts to update, I receive an error dialog with the following text:
"Failed to install VS Code update. Please download and reinstall VS Code. 

Please attach the following log file to a new issue on GitHub. 

C:\Users\<username>\AppData\Local\Temp\vscode-inno-updater.log"

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (3.63GB free)|
|Process Argv|C:\Users\mcollier\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
docs-markdown|doc|0.1.3
gitlens|eam|8.5.5
docker-explorer|for|0.1.6
rest-client|hum|0.19.1
vscode-azureappservice|ms-|0.9.0
vscode-azureeventgrid|ms-|0.1.0
vscode-azurefunctions|ms-|0.10.0
vscode-azurestorage|ms-|0.4.1
vscode-cosmosdb|ms-|0.8.0
vscode-service-fabric-reliable-services|ms-|0.1.2
mssql|ms-|1.4.0
python|ms-|2018.7.1
azure-account|ms-|0.4.3
azurecli|ms-|0.4.2
csharp|ms-|1.15.2
PowerShell|ms-|1.8.3
team|ms-|1.136.0
azurerm-vscode-tools|msa|0.4.2
vscode-docker|Pet|0.1.0
quicktype|qui|12.0.38
vscode-icons|rob|7.25.0
bash-debug|rog|0.2.2
code-settings-sync|Sha|3.0.0

</details>

**Comment by joaomoreno** [comment]
Do you have the update log?

**Comment by mcollier** [comment]
I thought I had attached the log file, but apparently it didn't take.  :(

I looked at my C:\Users\mcollier\AppData\Local\Temp directory, and the vscode-inno-updater.log file is no longer there.

**Comment by mcollier** [comment]
@joaomoreno I have this error on the VS Code Insiders build.  I have the vscode-inno-updater.log file.  Should I open a new GitHub issue, add here, or another issue about failed updates?

**Comment by MicrosoftEurope** [comment]
Hello Michael,

Could you please provide the error that you are getting?
