### ISSUE TITLE
Regional window blocked

### ISSUE THREAD

**Issue by NIRVANALAN** [microsoft/vscode#56821]
Sometimes, the window of vscode are covered by some screen part of the program, such as a picture (like a screenshot) of part of the output region covering the editor region, but when I click ("terminal") or switch to other function area, this problem vanishes and the everything goes well like before. Never encountering problems like this till the lates upgrade. I hope you can fix it in the next version.

**Comment by sandy081** [comment]
What platform are you on and what version of VS Code you are using?

**Comment by NIRVANALAN** [comment]
Windows 10 latest version, i7-6700HQ, latest vscode version(1.26.1)
I have attached a picture in this mail, and something like this frequently happened since I upgrade my vscode
And also I have installed two version( as vscode suggested in the latest upgrade), a user-version and a system-wide version
Since I uninstalled the system-wide version an hour ago, this problem have not appeared. But I am not sure whether it will work well in a long time and whether the problem lies on the version confliction
Sincerely



________________________________
发件人: Sandeep Somavarapu <notifications@github.com>
发送时间: Monday, August 20, 2018 10:19:47 PM
收件人: Microsoft/vscode
抄送: NIRVANA; Author
主题: Re: [Microsoft/vscode] Regional window blocked (#56821)


What platform are you on and what version of VS Code you are using?

―

**Comment by sandy081** [comment]
@NIRVANALAN I do not see any screenshot here

**Comment by NIRVANALAN** [comment]
I don't know if there are some problems with github, that I can not upload my screenshot. Can you access the link [https://blog.csdn.net/GROSSES/article/details/81988660](url), I have uploaded my screenshot here.

**Comment by sandy081** [comment]
Pasting your screenshot here

![image](https://user-images.githubusercontent.com/10746682/44569936-4a5a1100-a77c-11e8-87f4-eaba1191cf15.png)

**Comment by bpasero** [comment]
@NIRVANALAN does this go away when you run "code --disable-gpu"?

**Comment by NIRVANALAN** [comment]
It has gone away since I uninstalled the system-wide version of vscode, that I have not encountered this problem in these days and it works well now. I will try "code --disable-gpu" when I see this problem again.
I think it may be a rendering problem, this "lap" part sometimes shows another region of the editor, such as a piece of code fragment "screenshot" or part of the title panel.
