### ISSUE TITLE
"Toggle word wrap" - indicate current state

### ISSUE THREAD

**Issue by zhuxiangthu** [Microsoft/vscode#56832]
我用vscode写LaTeX，段落不需要手动分行，用自动换行就可以，但是每次重启后都调回不自动分行的模式。希望自动分行能一直保留。别的设置都是重启保持的，比如小地图和空格显示，只有这个不可以。
或者设计成，可选一直保留或者每次重启恢复。但我觉得一直保留上次配置是最合适的。
还有能不能把这几个菜单项改成“打开自动换行”打开后显示“关闭自动换行”？只是写“切换XXX”，不够严谨，最好在菜单项中体现出实时状态。
谢谢！

**Comment by roblourens** [comment]
Sorry, I don't understand. Google translate is not helpful here.

**Comment by byyxx128** [comment]
@zhuxiangthu 下次自己用英语说，而且不要说这么多废话，我都看不懂，谁给你看去……
@roblourens Just translation here:
"Word Wrap" won't keep on after restart of VSCode. An option in Settings may be needed. Then I can choose if "Word Wrap" will keep on next time.

**Comment by roblourens** [comment]
There is a setting for word wrap, and you can configure that if you want. Maybe the "Toggle word wrap" menu item/command can indicate the current state somehow? Although I think it's usually easy to tell whether lines are wrapped or not.

**Comment by alexandrudima** [comment]
There is a setting `editor.wordWrap` which can be saved on disk.

It is also possible to configure this per file type (per language type).
