### ISSUE TITLE
VS code prints update#setState logs to otherwise quiet stdout/stderr

### ISSUE THREAD

**Issue by vvuk** [Microsoft/vscode#56833]
- VSCode Version: 1.26.1 (has happened well before 1.26 as well)
- OS Version: Windows 10

Steps to Reproduce:

This is perhaps somehow related to running from a MSYS2 terminal.  Running `code .` or similar does from within an MSYS2 bash prompt seems to somehow imply `--wait` behaviour, even without that option.  The `code.exe` process does not return to the shell while the window is open.

While the shell is waiting, even without `--verbose`, `update#setState` messages are seen in stdout/stderr:

1. Run "code ." from a (MSYS2?) command prompt.
2. Observe:

```
$ code .

[main 9:00:20 AM] update#setState idle
[main 9:00:50 AM] update#setState checking for updates
[main 9:00:50 AM] update#setState idle
```

printed to console.

VS Code is otherwise quiet; it looks like these messages are going to the wrong log?

However, it's not clear why the process is waiting for the window to be closed -- it doesn't do that when started from cmd.exe or powershell.  Is there an env var that might affect this behaviour?

**Comment by joaomoreno** [comment]
What is your `$PATH` variable?
