### ISSUE TITLE
feature: toggling a maximized panel that was closed when maximize command was issued, should close it again

### ISSUE THREAD

**Issue by bkcsfi** [Microsoft/vscode#56831]
Please consider this workflow

1. Use CTRL-`  to open a terminal window, it appears with 'restored panel size' height (e.g. about 15 lines, below the editor groups)

2. Click 'X' to close all the panel, so that editor groups is maximized in height

3. press CTRL-SHIFT-Q to maximize the panel

4. press CTRL-SHIFT-Q again. I expect the panel to be closed, instead it's returned to the 'restored panel size' height of about 15 lines, below the editor groups.

--

During development I want to quickly toggle between full size code editor and unit test output. CTRL-SHIFT-Q seems the best way to do this, but it doesn't return the panel to the closed state when I expect it to.

In my example workflow above, I used terminal window as an example, but this should apply to any tab in the panel section.  If the panel is currently closed, then maximized, then maximized again, it should return to the close state, not to the 'restored' state.

thanks

**Comment by bkcsfi** [comment]
this feature suggestion does not appear to be related to #13906 nor #46017

**Comment by isidorn** [comment]
I can keep this open as a feature request but honestly not all users are expecting this behavior and could be confusing. Due to that I prefer to close this as out of scope since I know this will not be tackled.
For toggling the panel just use ctrl + J

**Comment by bkcsfi** [comment]
thanks for the response, I will adapt to using CTRL-J
