### ISSUE TITLE
Commit prompt stays open after commit

### ISSUE THREAD

**Issue by sguillia** [Microsoft/vscode#56837]
Issue Type: <b>Bug</b>

Steps to reproduce:

1. Open a versioned folder with VS Code
2. Stage something
3. Click on the commit button (that looks like a V) when the commit message is empty
4. A commit message is prompted, but in another place. Focus is given to it.
5. Click back on the `Message` field
6. **The prompt stays open** (this is the bug)
7. Enter some commit message
8. Click on the commit button
9. Now click on the prompt that is still open
10. Enter a commit message
11. Press Enter
12. VS Code throws a git error

Here is a screen recording. I hope it will be easier to understand than these steps.

![project-commit](https://user-images.githubusercontent.com/15984272/44354084-2c08c280-a4a9-11e8-8691-3d6b2fddf01d.gif)

VS Code version: Code - Insiders 1.27.0-insider (6e559261f677793fea424c6eb5cb13d0301ffff1, 2018-08-20T08:36:52.887Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (10.79GB free)|
|Process Argv|C:\Users\GUILLIAMS.S\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe --disable-extensions|
|Screen Reader|no|
|VM|50%|

</details>Extensions disabled

**Comment by joaomoreno** [comment]
This is a purposeful behaviour: https://github.com/Microsoft/vscode/blob/master/extensions/git/src/commands.ts#L1111

Many input boxes in the git extension stay open when focused out, because it's often the case that the user wants to navigate outside of them temporarily and get some information outside, before filling out the input.
