### ISSUE TITLE
emmet issue

### ISSUE THREAD

**Issue by Saiken9** [Microsoft/vscode#56835]
i can't get emmet inside vs code exploration ...
![screenshot 105](https://user-images.githubusercontent.com/31864825/44353727-ccf28000-a49f-11e8-9232-e76d3c12097d.png)

- OS Version: windows

Does this issue occur when all extensions are disabled?: Yes

**Comment by Saiken9** [comment]
please help me

**Comment by mwoskowicz** [comment]
The same happened for me...

**Comment by Saiken9** [comment]
when was the first time ?

**Comment by Saiken9** [comment]
and did you fix the problem ?

**Comment by mwoskowicz** [comment]
The first time was after installing version 1.26.1. I have tried every solution provided in vscode bugs archived issues but no happy ending.

**Comment by Saiken9** [comment]
...

**Comment by Saiken9** [comment]
vs code have a lot of problems recently

**Comment by Saiken9** [comment]
try to download older version of vs code and see if it works

**Comment by mwoskowicz** [comment]
Yes, 1.25.1 works. Using it now.

**Comment by Saiken9** [comment]
me too,it is working perfectly !
they need to fix it in the upcoming updates hopefully

**Comment by ramya-rao-a** [comment]
- @Saiken9 From your screenshot, the fontsize on the items in the auto-completion widget seem very small. Is that the issue? Or is it that you dont see emmet related completion items?
- @mwoskowicz Do you see the same as @Saiken9 i.e the font-size being too small?

**Comment by mwoskowicz** [comment]
@ramya-rao-a There are a few things broken with emmet. Also, the expand abbreviation is not working making the "tab" key not do anything.
I am sorry but personally I do not see any weird behaviour neither in @Saiken9 font, nor in mine
