### ISSUE TITLE
Terminal won't open and won't show error

### ISSUE THREAD

**Issue by gonensh** [Microsoft/vscode#56849]
- VSCode Version: 1.26.1
- OS Version: macOS Sierra

Steps to Reproduce:

1. Set  "terminal.integrated.cwd": "PATH_THAT_DOESNT_EXIST" (or a path containing ~ 😞 )
2. Open a new terminal

**Expected:** New terminal opens. If it cannot open, its panel should remain open showing the error/reason why it could not start.
**Observed:** The panel closes immediately, leaving the user with no information on how to resolve the issue.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/17450
