### ISSUE TITLE
Have a setting to make the breadcrum box wider

### ISSUE THREAD

**Issue by carlisia** [Microsoft/vscode#56846]
I am loving the new breadcrum feature!

But when using it with `Go`, it's impossible to see the name of functions that have a mid size length pointer receiver since it appears out of the edge of the box:

![image](https://user-images.githubusercontent.com/16508/44366068-5abe7300-a480-11e8-9a81-6a10852a4bc0.png)

**Comment by jrieken** [comment]
@carlisia What version of vscode are you using? insiders or stable?

**Comment by carlisia** [comment]
I was using stable. Now I'm using insider and that works perfectly.

**Comment by jrieken** [comment]
Ok, closing then (we have fixed an issue earlier this week which was about the picker width)
