### ISSUE TITLE
Strange text in terminal

### ISSUE THREAD

**Issue by qwergram** [Microsoft/vscode#56844]
Issue Type: <b>Bug</b>

# Actual vs Expected Results:
Here's a screenshot of the strange result:
![image](https://user-images.githubusercontent.com/8170987/44363419-fd72f380-a478-11e8-8584-71339f1b700a.png)

The left one is running a django server, the right one is running a celery worker. I can see them printing new text whenever I hit the website in the browser. They both work fine, but it's just the strange text.

# How to reproduce:
1. I'll work on some code after school and before bed. 
2. I'll put the computer on sleep with terminals running their respective tasks. 
3. When I wake it from sleep, I can't get rid of the strange looking text without closing effected terminals.

# Machine Details:
VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:34:20.517Z)
OS version: Linux x64 4.15.0-30-generic (Ubuntu 18.04.1 LTS)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz (6 x 4100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|15.60GB (0.94GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
django-html|bib|1.2.0
django|big|1.0.0
systemd-unit-file|coo|1.0.0
vscode-html-css|ecm|0.2.0
vscode-language-babel|mgm|0.0.20
python|ms-|2018.7.1
vetur|oct|0.12.6
vscode-docker|Pet|0.1.0
sass-indented|rob|1.4.9
vscode-nginx|sha|0.5.0

</details>

**Comment by Tyriar** [comment]
I suspect this is the Chromium-related corruption issue. Hiding and showing or resizing the terminal should fix it. This will hopefully be fixed in the future as we update Electron. let me know if that doesn't work around the issue.

**Comment by qwergram** [comment]
It seems that resizing the windows fixes only _one_ of the terminals. After some tinkering, it seems that your hunch is right: it's chromium. Other chromium apps suffer from this behavior as well. Guess I'll be looking forward to the electron updates!
