### ISSUE TITLE
When vscode run about 30 minutes later It was very slowly!

### ISSUE THREAD

**Issue by biij5698** [Microsoft/vscode#5684]
I love vscode and I use it to write all the code,But when it run after 30 minutes It begin to very slowly!
I must to restart vscode to continue my work!

**Comment by dbaeumer** [comment]
@bpasero assigning to you since you track comparable issues.

@biij5698 any additional information like what do you do, what kind of files are you editing, which OS are you on and which version are you using would be helpful.

**Comment by biij5698** [comment]
@dbaeumer The files are html,The OS is windows 7(32 bit),The vscode version is 1.0.0.

**Comment by bpasero** [comment]
Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` to see if it makes it better?

**Comment by biij5698** [comment]
@bpasero Hello,I'm work on window 7 and open the vscode by double blick.

**Comment by bpasero** [comment]
@biij5698 any extensions installed?

**Comment by biij5698** [comment]
@bpasero No,I don't have to install any extensions.

**Comment by biij5698** [comment]
@bpasero The only change is:
 // 控制字体系列。
	"editor.fontFamily": "Microsoft Yahei Mono",

	// 控制字体大小。
	"editor.fontSize": 17,

	// 控制行高。
	"editor.lineHeight": 24,
	
	"files.associations": {
		"*.tpl": "html"
	}

**Comment by bpasero** [comment]
@biij5698 are you saying you are just editing HTML files and nothing else? can you share your workspace with me?

**Comment by biij5698** [comment]
@bpasero Yes,and my workspace is :
// 将设置放入此文件中以覆盖默认设置
{
    // 控制字体系列。
	"editor.fontFamily": "Microsoft Yahei Mono",

	// 控制字体大小。
	"editor.fontSize": 17,

	// 控制行高。
	"editor.lineHeight": 24,
	
	//支持tpl文件
	"files.associations": {
		"*.tpl": "html"
	},
	//-------- 窗口配置 --------

	// 启用后，将在新窗口中打开文件，而不是重复使用现有实例。
	"window.openFilesInNewWindow": false,

	// 控制重启后如何重新打开文件夹。选择“无”以从不重新打开文件夹，选择“一个”以重新打开最后处理的文件夹，或选择“全部”以打开上次会话的所有文件夹。
	"window.reopenFolders": "all"
}

**Comment by bpasero** [comment]
I meant, can you share the contents of the workspace. Is it maybe at GitHub?
