### ISSUE TITLE
Breadcrumb dropdown omits items unresolved in current file

### ISSUE THREAD

**Issue by harikb** [Microsoft/vscode#56854]
- VSCode Version: 1.26.1
- OS Version: Mac OS 10.12.6

Steps to Reproduce:

1. Create two files in same directory, same package. Declare a new type and a method on it.
2. Move the definition of the type from one file to another. Only the file that resolves the declaration will have the correct breadcrumb

Does this issue occur when all extensions are disabled?: N/A

![bc1](https://user-images.githubusercontent.com/952886/44369823-98c19400-a48c-11e8-8317-48b5cf70bf1a.png)
![bc2](https://user-images.githubusercontent.com/952886/44369830-9bbc8480-a48c-11e8-9e39-625b32682a3a.png)

**Comment by jrieken** [comment]
Seems to be a problem with the go extension not providing elements

**Comment by ramya-rao-a** [comment]
This issue was moved to Microsoft/vscode-go#1864
