### ISSUE TITLE
Regression: folding by region / endregion (without #) doesn't work anymore

### ISSUE THREAD

**Issue by ggregoire** [Microsoft/vscode#56852]
Version: 1.26.1

Steps to Reproduce:

1. Hover the margin next to `// region`: there is no folding icon
2. Replace `// region` & `// endregion` with `// #region` & `// #endregion`: there is a folding icon

It worked before, my projects are full of `// region` without `#`.

My settings:

```
{
  "breadcrumbs.enabled": true,
  "codemetrics.basics.CodeLensHiddenUnder": 10,
  "codemetrics.basics.ComplexityColorExtreme": "#fd8d3c",
  "codemetrics.basics.ComplexityColorHigh": "#fecc5c",
  "codemetrics.basics.ComplexityColorLow": "#ffffb2",
  "codemetrics.basics.ComplexityColorNormal": "#c2e699",
  "editor.fontFamily": "Fira Code",
  "editor.fontLigatures": true,
  "editor.fontSize": 15,
  "editor.formatOnSave": true,
  "editor.minimap.renderCharacters": false,
  "editor.renderIndentGuides": true,
  "editor.renderControlCharacters": false,
  "editor.renderWhitespace": "none",
  "editor.tabSize": 2,
  "extensions.ignoreRecommendations": false,
  "files.trimTrailingWhitespace": true,
  "flow.useNPMPackagedFlow": true,
  "git.autofetch": true,
  "git.confirmSync": false,
  "javascript.referencesCodeLens.enabled": true,
  "javascript.updateImportsOnFileMove.enabled": "always",
  "javascript.validate.enable": false,
  "window.zoomLevel": 0,
  "workbench.activityBar.visible": true,
  "workbench.colorTheme": "Monokai Pro (Filter Machine)",
  "workbench.editor.labelFormat": "short",
  "workbench.editor.tabSizing": "shrink",
  "workbench.iconTheme": "Monokai Pro (Filter Machine) Icons",
  "workbench.statusBar.feedback.visible": false
}
```

**Comment by aeschli** [comment]
@ggregoire Which language?

**Comment by ggregoire** [comment]
@aeschli JavaScript

**Comment by mjbvz** [comment]
You should use `// #region`. The `#` makes the comment less ambiguous and is therefore the region syntax we officially support

**Comment by ggregoire** [comment]
Hi @mjbvz!

`// region` was officially supported when VSCode introduced the regions: https://code.visualstudio.com/updates/v1_17#_folding-regions

While I understand that you removed this syntax to be consistent with the other languages, a short entry in the last release notes would have been welcome since it's a small breaking change. :)

Anyway, thanks for the great work!

**Comment by vitalybe** [comment]
`// region` is the syntax supported by Webstorm. It would be nice if this could at least be configurable. As it stands, you can't use regions unless all your team members use the same IDE/editor.
