### ISSUE TITLE
Sync VSCode Profile to cloud / login

### ISSUE THREAD

**Issue by tjgruber** [Microsoft/vscode#56850]
In the same way that Firefox and Chrome store bookmarks, history, settings, etc. in a cloud account via login, I think it would be fantastic to offer that built-in functionality for VSCode to save in the Azure cloud the following:

- User and Workspace settings
- Installed extension
- Git repositories (not the repos themselves, but what's necessary to automatically resync)

This would help a lot when using multiple machines. To get up and running on a new computer, the idea is like this:

1. Install VSCode
2. Sign in
3. Done... all settings, extensions, and connections to your Git repositories are now automatically synchronized.

**Comment by Astrantia** [comment]
I would like to voice my opinion against any type of Sign In/Sign Ups in `vscode`. That's exactly the reason why vscode is so good now, because it isn't overweighted with stuff like that. If you do want to sync, you can download existing extensions or make your one.
