### ISSUE TITLE
Make the color of the window-appicon in custom window titlebar customizable

### ISSUE THREAD

**Issue by yuval-gilboa** [microsoft/vscode#56857]
This is a feature request for customizing the window-appicon in the custom workbench titlebar. The SVG image for the appicon should be defined using `fill: currentColor` so it inherits the foreground color of the titlebar, or better yet, add a special color entry for it in the workbench color customizations section. 

This would allow adjusting the appicon appearance to custom titlebar backgrounds and avoid contrast issues like below: 

![image](https://user-images.githubusercontent.com/4710322/44370475-0d272200-a4e3-11e8-92be-7a4a2cf3399a.png)

**Comment by misolori** [comment]
We could look at providing the option to use either the default icon or the foreground color (which is what the title bar text uses). This can get a little tricky as we currently use the icon to show what version of VS Code is being used (blue = stable, green = insiders).

@sbatten, thoughts?

**Comment by sbatten** [comment]
@misolori I'm not opposed to making the icon themable to the extent of using the foreground color. Just want to make sure that's something that fits in our guidelines.

**Comment by misolori** [comment]
This goes against our branding guidelines since we only ever use Blue (Stable), Green (Insiders), Orange (Explorations), Black/White when needed. So will be closing this as out of scope.
