### ISSUE TITLE
Unable to build on raspberry pi3

### ISSUE THREAD

**Issue by sorakiu** [Microsoft/vscode#5685]
- VSCode Version: 1.0.1
- OS Version: Linux raspbian 4.1.19-v7+ #858 SMP Tue Mar 15 15:56:00 GMT 2016 armv7l GNU/Linux

Steps to Reproduce:

1. followed Scott Hanselman's steps: http://www.hanselman.com/blog/BuildingVisualStudioCodeOnARaspberryPi3.aspx
I couldn't get the newer node / npm the way he suggested, so I used these steps:

curl -sL https://deb.nodesource.com/setup | sudo bash -
sudo apt-get install -y nodejs

2. then I ran 
:~/Downloads/vscode $ ./scripts/npm.sh install --arch=armhf --no-optional

> Code@1.0.1 preinstall /home/sorakiu/Downloads/vscode
> node build/npm/preinstall.js

npm WARN optional dep failed, continuing windows-mutex@0.2.0
npm ERR! Linux 4.1.19-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--arch=armhf" "--no-optional"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your operating system or architecture: fsevents@0.3.8
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: arm

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sorakiu/Downloads/vscode/npm-debug.log

I've seen this error listed several times on the net, but I don't really see a solution.

[npm-debug.txt](https://github.com/Microsoft/vscode/files/232794/npm-debug.txt)

**Comment by dbaeumer** [comment]
@joaomoreno assigning to you.

**Comment by joaomoreno** [comment]
You clearly **need** the node he suggests.

**Comment by ajstadlin** [comment]
Has anyone been able to do a repeatable VSCode installation procedure for Raspberry Pi3 running Raspbian Jessie?

**Comment by dotupNET** [comment]
I've some similar problems:

pi@dotup-pi001:~/source/vscode $ ./scripts/npm.sh install --arch=armhf
WARN optional dep failed, continuing fsevents@0.3.8

> code-oss-dev@1.8.0 preinstall /home/pi/source/vscode
> node build/npm/preinstall.js

-
npm WARN optional dep failed, continuing windows-foreground-love@0.1.0
npm WARN optional dep failed, continuing windows-mutex@0.2.0
npm WARN optional dep failed, continuing fsevents@0.3.8
npm WARN optional dep failed, continuing windows-foreground-love@0.1.0
npm WARN optional dep failed, continuing windows-mutex@0.2.0
npm WARN optional dep failed, continuing fsevents@0.3.8
npm WARN optional dep failed, continuing fsevents@0.3.8
\
> pty.js@0.3.0 install /home/pi/source/vscode/node_modules/pty.js
> node scripts/install.js

make: Entering directory '/home/pi/source/vscode/node_modules/pty.js/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
  SOLINK_MODULE(target) Release/obj.target/pty.node
  COPY Release/pty.node
make: Leaving directory '/home/pi/source/vscode/node_modules/pty.js/build'


> pty.js@0.3.0 postinstall /home/pi/source/vscode/node_modules/pty.js
> node scripts/post-install.js


> oniguruma@6.1.1 install /home/pi/source/vscode/node_modules/oniguruma
> node-gyp rebuild

make: Entering directory '/home/pi/source/vscode/node_modules/oniguruma/build'
make: *** No rule to make target 'Release/obj.target/oniguruma/deps/onig/regcomp.o'                          , needed by 'Release/obj.target/oniguruma.a'.  Schluss.
make: Leaving directory '/home/pi/source/vscode/node_modules/oniguruma/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_mod                          ules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.j                          s:200:12)
gyp ERR! System Linux 4.4.30+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_module                          s/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/source/vscode/node_modules/oniguruma
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

npm ERR! Linux 4.4.30+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--arch=armhf"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! oniguruma@6.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oniguruma@6.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/source/vscode/npm-debug.log

**Comment by chenbuer** [comment]
I encounter the same problem like @dotupNET
