### ISSUE TITLE
Breadcrumbs should inherit colors from the theme, not the defaults

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#56864]
I would expect breadcrumbs to look reasonable in my theme by it picking up defaults based on the theme's editor background or tab background colors, but it looks like it's pulling from the default dark colors instead:

![image](https://user-images.githubusercontent.com/2193314/44372961-7125f800-a49b-11e8-8de5-85198645c688.png)

Theme: https://marketplace.visualstudio.com/items?itemName=Tyriar.theme-sapphire

**Comment by jrieken** [comment]
@Tyriar It mostly does: https://github.com/Microsoft/vscode/blob/f7b8c9b7df54f23b02fb36ba0cb12a5a96c8c4e9/src/vs/platform/theme/common/colorRegistry.ts#L292-L300. What color doesn't work for you?

**Comment by Tyriar** [comment]
@jrieken these fall back to Dark+'s colors, notice in the screenshot that `breadcrumb.background` is not actually based on the `editor.background` but Dark+'s default editor background.

I rely on the theme color for the terminal background like so:

null defaults:

https://github.com/Microsoft/vscode/blob/f7b8c9b7df54f23b02fb36ba0cb12a5a96c8c4e9/src/vs/workbench/parts/terminal/common/terminalColorRegistry.ts#L16

Fallback to theme's `editor.background` if it's not set:

https://github.com/Microsoft/vscode/blob/f7b8c9b7df54f23b02fb36ba0cb12a5a96c8c4e9/src/vs/workbench/parts/terminal/electron-browser/terminalPanel.ts#L313-L314

**Comment by jrieken** [comment]
@aeschli Can you please advise to do here

**Comment by aeschli** [comment]
@jrieken is doing the right thing here. By declaring `registerColor('breadcrumb.background', { light: editorBackground, dark: editorBackground, hc: editorBackground }`, the 'breadcrumb.background' color will default to the *currently defined* editorBackground color.
![image](https://user-images.githubusercontent.com/6461412/44449084-69766880-a5ed-11e8-82d4-48446074d81b.png)

@jrieken You might want to do the same with the foreground colors If you want to add transparency, do something like here: https://github.com/Microsoft/vscode/blob/f938d63a285d470df9a407786d840b4d38d56503/src/vs/platform/theme/common/colorRegistry.ts#L251

@Tyriar I recommend you to also do the same

**Comment by jrieken** [comment]
I have no changed it so that breadcrumbs only reuse (and lighten/darken) existing colors.

**Comment by Tyriar** [comment]
Hm, maybe I was just on an older version as it's working now. @aeschli will look into it thanks 👍  https://github.com/Microsoft/vscode/issues/57038

**Comment by jrieken** [comment]
Yeah, in older versions the colors were hard coded
