### ISSUE TITLE
searching gb2312

### ISSUE THREAD

**Issue by LoyieKing** [Microsoft/vscode#56869]
searching result can not show chinese correctly while the file is based on gb2312
![1](https://user-images.githubusercontent.com/13981123/44375253-281a8600-a525-11e8-829d-5ba81c8948cf.png)

**Comment by LoyieKing** [comment]
[example.zip](https://github.com/Microsoft/vscode/files/2304438/example.zip)

**Comment by Maledong** [comment]
Have you tried by setting the encoding type to `GB2312`?
![encoding](https://user-images.githubusercontent.com/40081831/44376337-a0377a80-a52a-11e8-8d8c-97b6abd2af5b.PNG)

**Comment by roblourens** [comment]
This works when `"files.encoding": "gb2312"` is set. Search isn't able to detect the encoding automatically, you have to use that setting.
