### ISSUE TITLE
大纲无法刷新

### ISSUE THREAD

**Issue by Lujk926** [Microsoft/vscode#56867]
Issue Type: <b>Feature Request</b>

重启VSCode后大纲无法刷新函数

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 6.1.7601

**Comment by Lujk926** [comment]
![default](https://user-images.githubusercontent.com/41947230/44375078-62375800-a524-11e8-88ad-f90eb8fd1408.png)

**Comment by Maledong** [comment]
Can you elebrate it by pasing images in details?

**Comment by rebornix** [comment]
@Lujk926 the image seems broken

**Comment by Maledong** [comment]
Maybe you re-load this and tell in details.

**Comment by rebornix** [comment]
Close for now as we don't have enough information.
