### ISSUE TITLE
MarkupContent and plaintext should have roughly the same font-size

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#56862]
Top comes from ESLint, bot comes from Vetur. My message looks very small compared to the ones rendered from plaintext.

![image](https://user-images.githubusercontent.com/4033249/44372067-096dae00-a497-11e8-9520-e5c3b9939cb2.png)

**Comment by jrieken** [comment]
This might be obsolete after @sandy081's work

**Comment by sandy081** [comment]
@octref Can you please check how it looks after latest improvements?

**Comment by octref** [comment]
Still not that good.

![image](https://user-images.githubusercontent.com/4033249/57797616-aba58400-76ff-11e9-8e9e-b95171299ab2.png)

One is the diagnostic message. The other one is the hover content with `MarkupContent`.

**Comment by sandy081** [comment]
We use editor font for diagnostic message since they can have code. We give freedom to authors to provide hover messages as normal text or code (markdown). 

Let me know if you have any suggestions here?

**Comment by octref** [comment]
IMO diagnostics messages should be rendered in UI text so it looks same as problems view.

Unless the message is Markdown that contains backticked code snippets or code regions.

**Comment by sandy081** [comment]
Diagnostic messages are rendered in editor font because for some diagnostics which needs non-ascii characters to be properly aligned. There are some discussions to support markdown in diagnostic message, if we do then this can be thought about.

**Comment by jrieken** [comment]
@rebornix Is this now better?

**Comment by octref** [comment]
This depends on #54272 happening. We can revisit after doing it. I'll just append this info to #54272.
