### ISSUE TITLE
Do not count task time in timeout

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#56861]
- Have a `preLaunchTask` that would take longer than 10 seconds
- You'll never be able to debug the process :(

**Comment by isidorn** [comment]
@octref good catch, however there must be some timeout in case the task never ends
More details can be found here https://github.com/Microsoft/vscode/issues/35340

If there is a better suggestion on what to do in this case I am open to change the code (or to accept a PR). [Code pointer](https://github.com/Microsoft/vscode/blob/53e57b5ea03e19ec1002f1c0a2d69fa1dd2cc01b/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L895)

fyi @dbaeumer

**Comment by weinand** [comment]
@octref sorry, but before we can understand whether this is a new bug or the feature described in length in #35340 we need additional information.

What is the exact error message you are seeing?
What kind of `preLaunchTask` are you using?

**Comment by octref** [comment]
@weinand Thanks a lot for the explanation! I have two scenarios:

1. css-language-features: https://github.com/Microsoft/vscode/tree/master/extensions/css-language-features

- The `preLaunchTask` is a gulp task that could take close to 10 seconds on slower machines
- I run a compound launch config that starts both the Language Client (`extensionHost`) and then attach to the server
- The server debugging target only get (`10sec - compilation time`) to run. So if my compilation runs more than 10 seconds, the server could never attach

So maybe the only way out for me is to make the timeout for the `attach` debug config longer.

2. A custom extension that I'm building. I have a custom build script and I guess that falls into the category of `not well-behaving task`. I do remember seeing `Prelaunch task xxx cannot be tracked`.

I guess this is behaving as-designed, so I'll close the issue.

**Comment by weinand** [comment]
@octref so you are not running into a timeout of the prelaunch task, but a timeout of an "attach" config (which you can work around by increasing the `timeout` attribute.)

The underlying problem is that you are using a "composite" launch config (which runs things in parallel) for a problem that needs sequential execution.
