### ISSUE TITLE
Wrong Folder Path for Open after OSX Rename in picker

### ISSUE THREAD

**Issue by mattbierner** [Microsoft/vscode#5686]
- VSCode Version: 1.0.0
- OS Version: OSX 10.11

**Steps to Reproduce**
1. `File -> Open`
2. Browse to project folder (`example_proj`).
3. Right click in OSX file selector to rename project folder
   ![screen shot 2016-04-22 at 10 54 10 pm](https://cloud.githubusercontent.com/assets/212305/14759599/3156497a-08dd-11e6-9663-9d9e98b4d928.png)
4. Rename project folder (`new_example_proj`)
5. Project folder stays selected but now has new name.
6. Click Open

**Expected**
Project opens with renamed folder

**Actual**
![screen shot 2016-04-22 at 10 54 26 pm](https://cloud.githubusercontent.com/assets/212305/14759607/5fc95612-08dd-11e6-8fe8-e15af1d5c1e2.png)

Folder does not open.

Deselecting and reselecting the renamed project folder fixes the problem.

**Comment by bpasero** [comment]
Seems to work if you move focus away after renaming but not if you hit enter directly.

**Comment by bpasero** [comment]
@mattbierner I suggest you report this to Electron and see if this is something Electron can even control.
