### ISSUE TITLE
"Copy Setting Name" on non-commonly used settings gives unexpected result

### ISSUE THREAD

**Issue by JacksonKearl** [Microsoft/vscode#56860]
latest insiders.

Gear > Copy Setting Name of something in Commonly Used: get `Files: Auto Save` (or similar)
Gear > Copy Setting Name of something not in Commonly Used: get `: Auto Save` (or similar) (*caterpillar emogi*)

**Comment by JacksonKearl** [comment]
More generally I'm not sure if it makes sense to copy a setting's human readable name in the first place. is this for sharing settings to be searched for in the new editor? I feel like the more natural thing there is to copy the setting's fully quantified id so that people can search for it in the new editor or just paste it into the old.

**Comment by roblourens** [comment]
I have no idea whether this will be useful, I just put it in... yeah I agree that we should be relying on IDs.

**Comment by isidorn** [comment]
There is no longer copy settings name
Only copy id and copy as json -> verified
