### ISSUE TITLE
Update doesn't update

### ISSUE THREAD

**Issue by remy** [Microsoft/vscode#56879]
Issue Type: <b>Bug</b>

I keep getting update notification, but on "update now" closes Code, but never reopens it. I've repeatedly downloaded the latest VS Code manually to get around this problem.

I don't know what to include to help replicate this, and I'm sure it's some local my machine, but having to manually (visit site, download, install) update each time is a bit of a pain.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (1.39GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.2
z80-asm|Ima|0.0.2
vscode-docker|Pet|0.0.26
code-settings-sync|Sha|2.9.2
html-css-class-completion|Zig|1.17.1
react-pure-to-class-vscode|ang|1.1.4
copy-syntax|ati|0.5.1
vscode-styled-jsx|bla|0.2.3
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.59
vscode-markdownlint|Dav|0.18.0
vscode-eslint|dba|1.4.12
vscode-dash|dee|1.10.0
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.3.1
auto-close-tag|for|0.5.6
rest-client|hum|0.18.1
search-node-modules|jas|1.3.0
react-component|jer|1.0.1
copy-markdown-as-html|jer|1.1.0
jq-syntax-highlighting|jq-|0.0.1
graphql-for-vscode|kum|1.11.0
Go|luk|0.6.78
VS-code-vagrantfile|mar|0.0.7
vscode-language-babel|mgm|0.0.20
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
vscode-autoprefixer|mrm|2.1.2
cpptools|ms-|0.17.3
sublime-keybindings|ms-|4.0.0
wordcount|ms-|0.1.0
vsliveshare|ms-|0.3.379
debugger-for-chrome|msj|4.7.0
polacode|pnp|0.2.2
toggle|reb|0.0.1
postcss|ric|2.0.0
vscode-nginx|sha|0.5.0
alex|shi|0.1.1
scope-info|sie|0.2.0
vscode-fileutils|sle|2.10.3
addDocComments|ste|0.0.8
code-spell-checker|str|1.6.10
python|tht|0.2.3
react-redux-es6-snippets|tim|2.1.0
nodejs-extension-pack|wad|0.1.9
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.6.0
ReactSnippets|xab|2.0.0

(4 theme extensions excluded)

</details>

**Comment by remy** [comment]
The only thing I see in Console.app that might be useful is this:

> nw_path_close_fd Failed to close guarded necp fd 29 [9: Bad file descriptor]

I've tried [this](https://github.com/Microsoft/vscode/issues/7426#issuecomment-293170856) chmod change, but it doesn't help.

**Comment by joaomoreno** [comment]
Does an admin prompt come up when you try to update?

**Comment by remy** [comment]
No. Update looks to download, but when vscode closes it never reopens. And
reopening manually shows it's still the old version.

**Comment by joaomoreno** [comment]
Can you check in VS Code's log folder? <kbd>F1</kbd> `Developer: Open Logs Folder`

**Comment by remy** [comment]
I think I since manually updated (I'm on Version 1.26.1 (1.26.1)), but running that command ("Open Logs Folder") literally does nothing. The command palette is dismissed, but nothing has happened…

**Comment by joaomoreno** [comment]
OK. Next time it doesn't update, you can also run `code --verbose` and then see if there are any errors coming out as you try to update.
