### ISSUE TITLE
Allow extensions to provide language servers for the use of other extensions via LanguageClient. Provide native language servers by default.

### ISSUE THREAD

**Issue by jchurch33** [Microsoft/vscode#56873]
The extension development utilities in VS Code are great, but may require extension authors to build up their own language server from scratch. At least in regards to generic information about one's code base such as definitions, references, and nav trees, it would be much easier if an extension author could talk to a language server provided by another extension or native to VS Code itself (e.g. Typescript).

Here's how it could work:
 - When an extension author creates their own language server (implementing the LSP), they "provide" that server to VS Code in the form of a LanguageClient.
 - Another extension author can check the provided LanguageClient's within VS Code, and if the desired client exists (either natively or thanks to another extension they've installed), inject it into their extension and begin making requests. (If it is not provided, they could initialize their own LanguageClient in the usual way.)

In order for this to really be useful first and foremost the native language servers in VS Code would need to be available. Then contributors could create extensions that exclusively provide a language client and server. Then extensions that wish to leverage these language servers can focus on their own extension specific functionality.

I think this would change the approach to language tooling a bit, but ultimately for the better. Right now my own team is developing an extension that needs definition and reference info for Typescript and there doesn't seem to be any way to piggy back off of the native Typescript server. As a result we spin up _another_ Typescript server within our extension. This feels unnecessary and computationally wasteful (not to mention cumbersome).

**Comment by octref** [comment]
Related: https://github.com/Microsoft/vscode/issues/1751#issuecomment-414631804.

> and if the desired client exists (either natively or thanks to another extension they've installed), inject it into their extension and begin making requests.

It's possible, just not documented, see https://github.com/Microsoft/vscode/issues/47288.

However, it seems what you want is [TS Server Plugin](https://github.com/Microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin).

I'll close this because there is nothing actionable or not captured in other issues , but feel free to continue the conversation or bring up more questions.

**Comment by jchurch33** [comment]
@octref So, to be clear, I can create a plugin for the typescript server which would allow me to essentially create a typescript server proxy in my extension so I can directly make defintion, reference, etc, commands to the native Typescript server?

The key piece is that I need to be able to make deliberate requests to the typescript server _from_ my extension

**Comment by octref** [comment]
> So, to be clear, I can create a plugin for the typescript server which would allow me to essentially create a typescript server proxy in my extension so I can directly make defintion, reference, etc, commands to the native Typescript server?

Yes.

> The key piece is that I need to be able to make deliberate requests to the typescript server from my extension

You can create TS files in VS Code and use these API: https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands to get results of, say, a Hover request.

**Comment by jchurch33** [comment]
...wow. I know I looked at that page and I just didn't see it. I think I assumed that those commands wouldn't work because I hadn't created the providers myself. Thank you!

**Comment by octref** [comment]
Yeah, our extensibility doc could use better structures...
