### ISSUE TITLE
every time after using npm or cnpm, CPU usage is up as high as 100%

### ISSUE THREAD

**Issue by sunq0001** [Microsoft/vscode#56878]
OS: windows 7, x64
this has become a nightmare to me. 
every time after i use npm or cnpm to install package,  CPU usage is up as high as 100%.
no way to kill process in task manager, i have to reboot PC each time when i encounter this issue.
i search for answers in websites, but none of these solution is effective. 
and i also know it is a quite common issue, a lot people encounter it as well. 
prior to adding a lot of cool features, i suggest to solve it in the first place.

**Comment by rebornix** [comment]
This issue can be mitigated by 

* use npm
* set `search.followSymlinks` to `false`

and see reasons in https://github.com/Microsoft/vscode/issues/51652#issuecomment-396747433

**Comment by sunq0001** [comment]
it doesn't work.
![upload](https://user-images.githubusercontent.com/25739231/44440494-e0fec480-a5fa-11e8-92eb-9b943e7ff81e.png)
