### ISSUE TITLE
Windows task bar does not go behind window when in fullscreen or zen mode.

### ISSUE THREAD

**Issue by faldor20** [Microsoft/vscode#56871]
- VSCode Version: 1.27.0
- OS Version: winodws 10 build 17134

Steps to Reproduce:
1. press f11 or ctrl+k then z 
2. look at the taskbar which is still there.

For some reason zen mode won't hide the task bar, i can't tell you exactly when this started but it think it worked about 3 months ago.

**Comment by faldor20** [comment]
![capture](https://user-images.githubusercontent.com/26968035/44375952-a719b980-a539-11e8-8297-68bfc7753079.PNG) Here is a picture of what i was describing

**Comment by sbatten** [comment]
@faldor20 This sometimes happen in Windows and if you search around the web, you'll likely find this happens an my apps/games to people on occasion with many workarounds. Is this happening consistently for you?

**Comment by faldor20** [comment]
it seems to have been fixed after some windows updates.
