### ISSUE TITLE
Code Helper CPU usage hits 100% after adding an NPM package

### ISSUE THREAD

**Issue by garyking** [Microsoft/vscode#56874]
- VSCode Version: Version 1.26.1 (1.26.1)
- OS Version: OS X 10.13.5 (17F77)

Steps to Reproduce:

1. Open an NPM project. Install a dep, with NPM or Yarn.
2. Code Helper CPU usage will go to 100%, and can sometimes last for 15 seconds.
3. During this time, features such as dropdown for tab completion does not appear.

I also have a `jsconfig.json` file with `"exclude": [ "node_modules" ]`.

I already tested with all exts disabled. Is it possible to instead make the dropdown still work, when CPU usage is at 100%? And why does usage shoot to 100% when adding new packages, anyway?

If I add a large package, like `yarn add parcel`, then CPU usage goes to 100%, and VSC doesn't show snippets for several minutes.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sunq0001** [comment]
https://github.com/Microsoft/vscode/issues/56878

similar issue, but it was closed with 

`"search.followSymlinks": false`

 i tried, it's never worked out.

pls help pay more attention on that. it is a big bug!

**Comment by mjbvz** [comment]
Can you please try collecting the TS Server log:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a folder with a `tsserver.log` file in it

If you can share the log, someone on the TS team or I can take a look to see what may be causing the high cpu usage here

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by sunq0001** [comment]
Hi, @mjbvz 

> In VS Code, run the TypeScript: Open TS Server log command

where to run the commend?
i tried in Command Palette, there is no such command inside

**Comment by mjbvz** [comment]
Yes run it in the command palette. You must be focused on a js or ts file for the command to appear

**Comment by EdArrowz** [comment]
I'm having the same issue.   Mine is on Windows 7.  For the standard edition it takes 5 minutes before it calms down.  I reproduced it with the insider edition which has nothing else installed.  The insider edition is less time, but still an issue.  Logs are attached.


Version: 1.28.0-insider (user setup)
Commit: ee6a21fa49bd1906bd1378c2f2714cd656409e5c
Date: 2018-09-11T05:18:39.589Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64


[tsserver.log](https://github.com/Microsoft/vscode/files/2372144/tsserver.log)
[ti-8088.log](https://github.com/Microsoft/vscode/files/2372145/ti-8088.log)

**Comment by mjbvz** [comment]
@sunq0001 The `TypeScript: Open TS Server log command` command will only show up when you have a javascript or typescript file open. Please try collecting the logs if you are still running into this issue.

@EdArrowz Please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues#visual-studio-code-is-consuming-a-lot-of-cpu) to determine which specific process has the cpu usage space. Basically: first reproduce the issue and then run  `code-insiders --status` on the command line. This should print out a full of code processes and their resources usage

**Comment by EdArrowz** [comment]
@mjbvz here is the info you requested:

Version:          Code - Insiders 1.28.0-insider (31bf4ccab388c082fcf4edafeaae5b703f211b5b, 2018-09-12T05:18:53.705Z)
OS Version:       Windows_NT x64 6.1.7601
CPUs:             AMD A6 PRO-7050B R4, 5 Compute Cores 2C+3G      (2 x 2195)
Memory (System):  6.95GB (4.34GB free)
VM:               0%
Screen Reader:    no
Process Argv:     C:\Users\jrice\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      disabled_off
                  native_gpu_memory_buffers:    disabled_software
                  rasterization:                unavailable_software
                  video_decode:                 enabled
                  video_encode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled

CPU %   Mem MB     PID  Process
    0       71   16644  code-insiders main
    0       48    6688     gpu-process
    0       68   16420     shared-process
    0      193   17852     window (ΓùÅ NumberPadActionTypes.js - NumberPad (Workspace) - Visual Studio Code - Insiders [Administrator])
    0        4   16368       winpty-process
    0        3   17076         C:\Windows\system32\cmd.exe
    0       32   16300           electron_node cli.js
    1       49   17516             "C:\Users\jrice\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe" --status
    0       11   18108       electron-crash-reporter
    0       39   18176       watcherService
    3       62   18716       extensionHost
    0        3    4000         "C:\Program Files\Git\cmd\git.exe" rev-parse --show-toplevel
    2        0    4864           git.exe rev-parse --show-toplevel
   25       59   17496         electron_node tsserver.js
   32       56   17628           electron_node typingsInstaller.js tsserver.js typesMap.js
Workspace Stats:
|  Window (ΓùÅ NumberPadActionTypes.js - NumberPad (Workspace) - Visual Studio Code - Insiders [Administrator])
|    Folder (Dev): more than 20654 files
|      File types: svn-base(11800) mcs(1669) txt(1529) focus(1250) gz(356)
|                  so(322) png(315) js(312) dll(264) fs(243)
|      Conf files: package.json(9) webpack.config.js(3) jsconfig.json(2)
|                  settings.json(1) tsconfig.json(1) sln(1)

**Comment by sunq0001** [comment]
[tsserver.log](https://github.com/Microsoft/vscode/files/2449381/tsserver.log)
[ti-1744.log](https://github.com/Microsoft/vscode/files/2449382/ti-1744.log)

@mjbvz uploaded already.
once i open VS code, CPU go as high as 100% before any of my operation.

**Comment by mjbvz** [comment]
@sunq0001 Thanks. Please collect the log from vscode insiders though. The logs are using TypeScript 3.0 while insiders is using TypeScript 3.1.1. We've fixed some perf issues since 3.0

@EdArrowz Please also try collecting the server logs as described above.

**Comment by sunq0001** [comment]
[tsserver.log](https://github.com/Microsoft/vscode/files/2463830/tsserver.log)
[ti-17008.log](https://github.com/Microsoft/vscode/files/2463831/ti-17008.log)
@mjbvz 
done in vscode insider. 
this time CPU usage looks ok after i use cnpm or npm.

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/27673 to track this upstream
