### ISSUE TITLE
Extension pack recommendation message is too vague for users to know what extensions are included

### ISSUE THREAD

**Issue by SummerSun** [microsoft/vscode#56875]
The issue is related but not limited to Java extension pack, because the recommendation message looks like a template for all kinds of extension packs.

It will be much better if the recommendation message tells what exactly extensions are included.

In this way, users know everything and it helps with the decision to take the recommendation.

But now (without BI data backup, I just get the conclusion from my own experience), it asks too much for users to figure out the details and to install the pack, they just close/ignore it.

- VSCode Version:

Version: 1.26.1
Commit: 493869ee8e8a846b0855873886fc79d480d342de
Date: 2018-08-16T18:38:57.434Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

- OS Version:

Windows 10 
Build: 17134

- Steps to Reproduce:
1. Open a java file
2. Get the recommendation message for 'Java' extension pack
![image](https://user-images.githubusercontent.com/5179063/44380982-d849b800-a540-11e8-882b-7af9c0f15e60.png)

- Does this issue occur when all extensions are disabled?
Yes

**Comment by ramya-rao-a** [comment]
Including all the extensions that form the pack in the message would make the message very long. Would replacing the `Show Recommendations` with `View Extension Pack` help? This can then open the dependencies part of the extension details for the extension pack.

**Comment by sandy081** [comment]
Current prompt does not talk about the pack or extension, instead it mentions. `Do you want to install the recommended extensions for java` 

Hence closing this, please revalidate the issue with current version.
