### ISSUE TITLE
Cannot collapse TypeScript sections

### ISSUE THREAD

**Issue by ms-markda** [Microsoft/vscode#56870]
Issue Type: <b>Bug</b>

Collapse feature is entirely broken in TypeScript files. Missing [+/-] buttons next to sections, keyboard shortcuts do nothing, and Selection menu items (Expand/Shrink) do nothing. I think the start of this problem correlates to updating, but I am not sure.

Restarted VSCode and opened existing folder from recents list. These features stopped working in effectively all files. A few random files let me collapse, but it stopped working as I navigated around and came back. If I switch between TypeScript "Workspace version" and "VSCode version" then the [+/-] come back in some files, but do not work.

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz (24 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (2.75GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.59
tslint|eg2|1.0.36
prettier-vscode|esb|1.6.1
debugger-for-chrome|msj|4.8.2
java|red|0.29.0

</details>

**Comment by mjbvz** [comment]
Is this for all projects and files or just a specific one? Also what workspace version of TypeScript were you using?

**Comment by andy-ms** [comment]
I've recently noticed that clicking on the *left* half of the collapse button has no effect. But i can also click way out in the whitespace on its right. Verified by hitting ctrl-plus a bunch of times so the collapse button would be large.

**Comment by ms-markda** [comment]
Revision: The [+/-] become less responsive and/or take a while to show up, but the feature does seem to work if I wait a while for VSCode/project to fully load (whatever that means). Then all projects work as expected so long as VSCode is still running. Also, if the [+/-] showed up and I clicked it during the wait then it will collapse at that "loaded" time. All this seems to have gotten better than yesterday when it never figured itself out.

I recall now that I installed the "user-wide installation" and then these problems surfaced on the "system-wide installation" even without a restart. While I continue to use the "system" one, even after restarts, these problems affect larger projects. However, only my largest project has problems to the degree mentioned above. Medium-sized project just have these issues for a second or two after opening the folder.

None of these problems affect the "user-wide" installation. They continue to affect the "system-wide" installation.

VSCode TypeScript version 3.0.1
My project uses 2.8.0

**Comment by mjbvz** [comment]
@andy-ms Not sure about that. Can you please open a new issue.

It sounds like @ms-markda's problem is different though and related to a slow project load, see #51225. @ms-markda About how large are your large projects? Can you share the output of running `code --status` from the command line with the active vscode instance still running

**Comment by andy-ms** [comment]
Can't repro my issue any more in latest vscode insiders.

**Comment by mjbvz** [comment]
Closing as we need more information to investigate the original issue
