### ISSUE TITLE
Markdown preview does not auto-update without an open editor

### ISSUE THREAD

**Issue by TyOverby** [Microsoft/vscode#5687]
- VSCode Version: 1.0.0
- OS Version: OSX 

Steps to Reproduce:
1. Open a markdown file and split the window into 1-editor pane and 1-view pane.
2. Notice that edits made in the editor automatically update the view pane.
3. Open the file in vim and make edits.
4. Notice that the edits made in vim automatically update the view pane.
5. Close the editor pane.
6. Notice that vim changes no longer update the view pane.

**Comment by bpasero** [comment]
This is because we keep the editor model cached and fail to resolve it from disk when it updates. I would assume when markdown becomes a real extension this issue would also be resolved.

**Comment by bpasero** [comment]
This is still the case with the new extension. There is no model around to be updated. 

@kieferrm I think the extension also needs to listen to file changes that happen to the file and do the right thing.

**Comment by bpasero** [comment]
This actually is https://github.com/Microsoft/vscode/issues/20901
