### ISSUE TITLE
Intellisense ignores JSDoc given type of class variables set as empty object

### ISSUE THREAD

**Issue by Luka967** [Microsoft/vscode#56884]
Tested with:
- Windows 10 10.0.17134.165
- VSCode 1.26.1 x64 (`493869ee8e8a846b0855873886fc79d480d342de`) affected
- VSCode Insiders 1.27.0 x64 affected
- VSCode 1.25.1 x64 from [June 2018](https://code.visualstudio.com/updates/v1_25) not affected

Given anything resembling this code sample:
X.js
```js
/** @type {SimpleDictionary<number>} */
const item = { };

class Test {
    constructor() {
        /** @type {SimpleDictionary<number>} */
        this.item1 = { };
        /** @type {SimpleDictionary<number>} */
        this.item2 = new Object();
        /** @type {SimpleDictionary<number>} */
        this.item3 = null;
        /** @type {SimpleDictionary<number>} */
        this.item4 = new Test();
        /** @type {SimpleDictionary<number>} */
        this.item5 = {
            entry1: new Test(),
            entry2: null,
            entry3: item,
            /** @type {SimpleDictionary<number>} */
            entry4: { }
        };
        this.item6 = item;
    }
}
```
X.d.ts
```ts
interface SimpleDictionary<T> {
    [key: string]: T
}
```

should, as an expected result, have all the `item`s in `Test` class be of type `SimpleDictionary<number>`.

The actual result is that `item1`'s JSDoc type is ignored and gets defined as `{ [x: string]: any }`, a normal object:
![image](https://user-images.githubusercontent.com/15956695/44389420-163be180-a52b-11e8-8f60-e54a313a3034.png)
Weirdly enough, the class variables `item2` and `item5` and even the local constant `item` are not affected by this:
![image](https://user-images.githubusercontent.com/15956695/44389428-1dfb8600-a52b-11e8-80ae-7bd26d577837.png)
![image](https://user-images.githubusercontent.com/15956695/44389447-2653c100-a52b-11e8-93e4-3e946520774c.png)
![image](https://user-images.githubusercontent.com/15956695/44389702-d6292e80-a52b-11e8-888d-fd525b69aa91.png)

As expected, intellisense won't recognize the type of a value in `item1`:
![image](https://user-images.githubusercontent.com/15956695/44390180-f9081280-a52c-11e8-8c3a-2310fa375338.png)

Using `@typedef` in javascript won't work either:
![image](https://user-images.githubusercontent.com/15956695/44391352-e6430d00-a52f-11e8-9924-ddf2cbde6f4e.png)

I believe that this is a problem with versions using TypeScript 3.0.0 and above, as I've noticed this only after the upgrade. Version 1.25.1 with TypeScript 2.9.2 works fine:
![image](https://user-images.githubusercontent.com/15956695/44390503-b561d880-a52d-11e8-89f4-eb985b830df4.png)
![image](https://user-images.githubusercontent.com/15956695/44390594-f9ed7400-a52d-11e8-9d81-ae689ae5d940.png)

VSCode 1.26.1 about:
![image](https://user-images.githubusercontent.com/15956695/44390870-a3346a00-a52e-11e8-8485-6c9abf21de06.png)
VSCode 1.25.1 about:
![image](https://user-images.githubusercontent.com/15956695/44390509-bd217d00-a52d-11e8-90c7-cc892ff6d993.png)

No extensions are required for reproducing this.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#26573
