### ISSUE TITLE
Installing update fails and couldn't open VSCode from start menu

### ISSUE THREAD

**Issue by vidhya03** [Microsoft/vscode#56887]
Issue Type: <b>Bug</b>

I have installed the updates 1.26 from the notifications. However after installation i got error and now i couldn't access the vscode

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|15.65GB (2.41GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\_\Code.exe|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
scss-lint|ada|0.1.4
vs-code-semicolon-insertion|chr|0.0.6
vscode-markdownlint|Dav|0.20.0
gitlens|eam|8.5.5
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.36
prettier-vscode|esb|1.6.1
auto-rename-tag|for|0.0.15
rest-client|hum|0.19.1
ftp-simple|hum|0.6.7
Angular2|joh|6.1.5
Angular-BeastCode|Mik|6.2.11
python|ms-|2018.7.1
debugger-for-chrome|msj|4.8.2
material-icon-theme|PKi|3.5.3
LiveServer|rit|5.1.1
code-settings-sync|Sha|3.0.0
Angular2|UVB|0.4.1
colonize|vms|2.2.2

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Can you fully reinstall VS Code?

**Comment by vidhya03** [comment]
Actually the mcafee antivirus was running by that time i have triggered
automatic installation.
