### ISSUE TITLE
Occasionally launches with all extensions disabled

### ISSUE THREAD

**Issue by RichieAHB** [Microsoft/vscode#56888]
Unable to reproduce consistently but, as in the title, Code has opened with all extensions disabled perhaps 3 times in the last few months. The only thing that was perhaps unique this last time was that my mac shutdown due to low battery, restored the window, then the next time I opened something all extensions were disabled. I can't remember if anything similar happened on the previous occasions but thought it was worth mentioning.

I can't seem to find a previous issue for this.

Closing and reopening doesn't fix this issue and I have to manually enable all my extensions.

- VSCode Version: 1.26.1 (has happened on numerous previous versions)
- OS Version: macOS 10.13.3

`code --disable-extensions` is not going to help here!

**Comment by sandy081** [comment]
Did you try restarting VS Code and also with a different user data directory. Use cli arg `user-data-dir`?

**Comment by RichieAHB** [comment]
I did try restarting and it didn’t work. I didn’t try another user data dir
(and can’t as I’ve reenabled then all now).

**Comment by sandy081** [comment]
Not sure what would have caused this unless there is an execution of `Disable All Installed Extensions` command. 

To confirm that when it happens next time can you please provide us the following data?

- Open Developer tools. Use command `Developer: Toggle Developer Tools`
- Open Local storage as in below
![image](https://user-images.githubusercontent.com/10746682/44478610-7ec7b300-a63e-11e8-87be-c74effc7145d.png)
- Type `extensionsIdentifiers/disabled` and see what it contains
![image](https://user-images.githubusercontent.com/10746682/44478649-9ef77200-a63e-11e8-9d7b-3e8e3f2f88af.png)

**Comment by RichieAHB** [comment]
Will do thanks :+1

**Comment by sandy081** [comment]
I am closing it for now. Please reopen it when you see it again with above info
