### ISSUE TITLE
Empty line inside Blocks breaks Smart Select

### ISSUE THREAD

**Issue by ris58h** [Microsoft/vscode#56886]
I've added [tokenTree.test.js](https://github.com/ris58h/vscode/blob/token-tree-test/src/vs/editor/contrib/smartSelect/test/tokenTree.test.ts) which shows that an empty line breaks TokenTree building process (which is used for Smart Select).

As I found, the problem is that `ModelRawTokenScanner` doesn't skip empty lines https://github.com/Microsoft/vscode/blob/eea3e8adf40182aa4a80043a92c9fddcb6454656/src/vs/editor/contrib/smartSelect/tokenTree.ts#L177-L180
because `this._lineTokens.getCount()` always greater than 0 even for empty lines.

All this breaks Smart Select as shown below:
![token-tree-empty-line](https://user-images.githubusercontent.com/511242/44392921-05479c00-a53c-11e8-93b7-184879cfc71a.gif)

**Comment by rebornix** [comment]
@ris58h thanks for your help on troubleshooting!
