### ISSUE TITLE
Autocomplete on VSCode Latest Update is giving Blanks/Wrong Suggestions and black bar.

### ISSUE THREAD

**Issue by JamesReads** [Microsoft/vscode#56881]
I downloaded the latest version of VScode last Friday. When I code I want my autocomplete to work, but with VsCode Update, I either get a Black Bar with Grey Lines, without the ability to see suggestions.

Just to be clear, suggestions are present. I just can't see them. Also since Friday, autocomplete is so unreliable it is frustrating. For example, I type `clg ` for `console.log()` but I get `CLIENT_RENEG_WINDOW
`. 

I could give you many other examples. Now to the black bar problem. See image below:
![screenshot 2 _li](https://user-images.githubusercontent.com/36208691/44389396-64ed7980-a533-11e8-9e67-29f58aea3f36.jpg)

I believe this is a bug. My Version is 1.26.1, and I run Regular VsCode Install x64.

As far as Reproducing it, I have really no idea. It just happened. My VsCode Setup is the same for weeks. No new Extensions, or new Workflows. The only change was the update.

**Comment by rebornix** [comment]
@JamesReads can you run `code --disable-gpu` to see if you still run into this issue?

**Comment by JamesReads** [comment]
I tried that, and still, it runs on the same bug. Just to be clear, what I did is run `code --sable-gpu` in the console. It opened a new VSCode Window, and I start typing, and the same issue persists.

Just another information here. I downloaded the VSCode Insiders Edition, and it runs fine. I also tried removing the Code Install along with the Code Files, then install code again. It still doesn't work. If you need more info tell me.

**Comment by bpasero** [comment]
@JamesReads does it reproduce with a newer build that is using a newer UI framework: https://az764295.vo.msecnd.net/exploration/6907adf13dc9abd9cba53a0dd96df1a345fbefb5/VSCode-win32-x64-1.27.0-exploration.zip

**Comment by JamesReads** [comment]
Yes, it does reproduce there as well. I completely deleted it from my system, along with VSCode Insiders, and tried again.

Regular VSCode has that problem. VSCode Insiders doesn't. Anyway, I switched to Insiders for now. I will try periodically to see if it is fixed. I will close this for now..
