### ISSUE TITLE
Can't modify hosts file in Windows 10 with "retry as admin" function

### ISSUE THREAD

**Issue by wrlssqi** [Microsoft/vscode#56894]
Code can't modify hosts file even though click "retry as admin". The "retry as admin" notification just pops up again and again. But if code is run as administrator, it could successfully modify hosts file.
I'm not sure if this is a bug.
- VSCode Version:1.26.1
- OS Version: Win10 1803 17134.228

Steps to Reproduce:

1.Open code as normal mode.
2.open hosts file, and make some changes.
3.save the file, then "retry  as admin" notification pops up at right bottom corner. Click "retry as admin" button.
4. UAC pops up, then click 'yes'. Then  "retry  as admin" notification pops up again, and the file is not modified.

Does this issue occur when all extensions are disabled?: No

**Comment by bpasero** [comment]
I cannot reproduce on my Windows. Maybe this is a configuration issue where the elevation does not work properly for your user, but the Admin is able to save. I do not think we can fix this easily.
