### ISSUE TITLE
Improved Updater Screen

### ISSUE THREAD

**Issue by beastdestroyer** [microsoft/vscode#56896]
Issue Type: Updater Improvement

When Updating VSCode (Stable or Insiders whatever) and you click "Update Now", the window closes and it starts. Nothing special about that, but the way it looks is just ugh:
![annoyingupdater](https://user-images.githubusercontent.com/30497573/44396077-be55a880-a533-11e8-8192-584de2c0d5a1.png)

Complaints I have:
- Font isn't smooth regardless of whether it's enabled in Windows
- Doesn't go behind any other open windows, even if you click off it
- Doesn't look appealing:
  - Isn't as involved as the installer of VSCode/ VS2017
  - Just looks plain

It would be nice if there was a more styled updater/installer, and I know it usually doesn't take long for an update to finish, but it is really annoying that I can't hide it and let it do its thing behind the scenes. For example, Atom has a really nice (heck, even animated) updater/installer and you can hide it by clicking off into another window. Whilst I don't really expect a styled installer/updater, please could you at least add the ability to stop the updater showing in front of every window please?

**Comment by joaomoreno** [comment]
We definitely want this window to be as simple as possible. We don't want to waste time rendering fireworks just for the sake of it. How long does it take to run to completion on your machine?

**Comment by beastdestroyer** [comment]
Only takes a few seconds, but I can imagine for more older drives (previously I had an 8 year old HDD that took minutes, now with my 860 Evo it takes mere seconds), as long as there's a minimize button and/or we can hide it I'm fine 👍

**Comment by joaomoreno** [comment]
Closing as won't fix, tho the dialog has changed since.
