### ISSUE TITLE
The code I wrote is different from the actual editor parsing.

### ISSUE THREAD

**Issue by wanghaooo** [Microsoft/vscode#56895]
What problem have I encountered?
![18_09_05__08_21_2018](https://user-images.githubusercontent.com/26863173/44395850-badf1300-a56d-11e8-9391-c9256f750c8e.jpg)

The code I wrote is different from the actual editor parsing.This kind of writing should be correct, but it is wrong.

**Comment by wanghaooo** [comment]
I wrote a react component, ready to render the react subcomponent, but I wrote it is inconsistent with the editor's parsing, here is my complete code

`import * as React from 'react';
import * as CSSModules from 'react-css-modules';
import { connect } from 'react-redux';
import { bindActionCreators } from 'redux';

const style = require('./index.scss');

type WechatProps = {};
type WechatState = {
};

@CSSModules(style, { allowMultiple: true })
export class Index extends React.Component<WechatProps, Partial<WechatState>> {
  constructor(props:any, context:any) {
    super(props, context);
    this.state = {};
  }
  render() {
    return (
        <div>
            { this.props.children || <div></div> }
        </div>
    );
  };
}`

**Comment by wanghaooo** [comment]
I wrote a react component, ready to render the react subcomponent, but I wrote it is inconsistent with the editor's parsing, here is my complete code

import * as React from 'react';
import * as CSSModules from 'react-css-modules';
const style = require('./index.scss');

type WechatProps = {};
type WechatState = {};

@CSSModules(style, { allowMultiple: true })
export class Index extends React.Component<WechatProps, Partial<WechatState>> {
  constructor(props:any, context:any) {
    super(props, context);
    this.state = {};
  }
  render() {
    return (
        <div>
            { this.props.children || <div></div> }
        </div>
    );
  };
}

**Comment by wanghaooo** [comment]
I wrote a react component, ready to render the react subcomponent, but I wrote it is inconsistent with the editor's parsing, here is my complete code

```javascript
import * as React from 'react';
import * as CSSModules from 'react-css-modules';
import { connect } from 'react-redux';
import { bindActionCreators } from 'redux';

const style = require('./index.scss');

type WechatProps = {};
type WechatState = {};

@CSSModules(style, { allowMultiple: true })
export class Index extends React.Component<WechatProps, Partial<WechatState>> {
  constructor(props:any, context:any) {
    super(props, context);
    this.state = {};
  }
  render() {
    return (
        <div>
            { this.props.children || <div></div> }
        </div>
    );
  };
}

const map_state_to_props = (state:any) => {
  return {};
}

const map_dispatch_to_props = (dispatch:any) => {
  return bindActionCreators(
    {},
    dispatch,
  );
}

export let IndexContainer = connect(
  map_state_to_props,
  map_dispatch_to_props,
)(Index);
```

**Comment by mjbvz** [comment]
What is the language mode of your file? This is shown in the status bar. It should be `TypeScript React`

**Comment by wanghaooo** [comment]
Sorry for my mistake, my file format suffix is ​​"ts", but it should be "tsx", too embarrassing...

**Comment by mjbvz** [comment]
No problem. Glad the issue is resovled
