### ISSUE TITLE
showInputBox should respect all properties - prompt, value and placeholder

### ISSUE THREAD

**Issue by agrabhi** [Microsoft/vscode#5689]
- VSCode Version: 1
- OS Version: win 10

Steps to Reproduce:
showInputBox respects only one of three properties showInputBox should respect all three properties - prompt, value and placeholder. it should respect prompt and one  of placeholder and value property.

**Comment by jrieken** [comment]
@bpasero I do [this](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostQuickOpen.ts#L1920). Should it be different?

**Comment by bpasero** [comment]
I cannot reproduce this issue, for me prompt, value and placeholder can be used "alle 3 zusammen":

![image](https://cloud.githubusercontent.com/assets/900690/14778514/aa58c9d6-0ad3-11e6-853b-eaa834ba241a.png)

**Comment by jrieken** [comment]
@agrabhi ping

**Comment by agrabhi** [comment]
Hey off work currently. Well reply next week.

**Comment by jrieken** [comment]
Closing since info is still missing.
