### ISSUE TITLE
New version is full of lags. [v1.26.1]

### ISSUE THREAD

**Issue by adsingh14** [Microsoft/vscode#56897]
Issue Type: <b>Performance Issue</b>

Latest version is full of lag.
- Lag on scroll.
- Unresponsive while minimize/maximizing.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

**Comment by bpasero** [comment]
@adsingh14 can you reproduce if you configure `window.smoothScrollingWorkaround: true`

**Comment by hamzawii** [comment]
Lag issue after updating to 1.26.1 (Ubuntu 18.04 LTS, i7, full SSD) 
~3-4 seconds to show autocomplete 
~2 seconds to show/hide red error  underline

Is there any solution ?

Thanks,
