### ISSUE TITLE
Breakpoint mark stays visible after mouse leave

### ISSUE THREAD

**Issue by ris58h** [Microsoft/vscode#56892]
It's an issue that hard to reproduce on the first try :smiling_imp: but I get it occasionally and it confuses me
![breakpoint-stays-visible](https://user-images.githubusercontent.com/511242/44394384-bef43c00-a53f-11e8-82e3-ec4cec9a74e8.gif)

**Comment by isidorn** [comment]
Probably the event is not being fired [here](https://github.com/Microsoft/vscode/blob/eea3e8adf40182aa4a80043a92c9fddcb6454656/src/vs/workbench/parts/debug/electron-browser/debugEditorContribution.ts#L239)
Feel free to put a breakpoint there and investigate more
