### ISSUE TITLE
Gallery images are squashed in Edge

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#569]
_From @roblourens on November 13, 2015 18:15_

![image](https://cloud.githubusercontent.com/assets/323878/11153699/79c3dd66-89ef-11e5-84d5-12343938fb5f.png)

Looks fine in Chrome

_Copied from original issue: Microsoft/vscode-extensionbuilders#110_

**Comment by seanmcbreen** [comment]
It's interesting I can;t manage to repo that in Edge.  Could I ask you to try again (I'm on a pretty recent Windows build though and perhaps that is why).

**Comment by seanmcbreen** [comment]
_From @roblourens on November 13, 2015 20:10_

This is Win 10 RTM, I tried it on a second computer and saw the same thing. It's only on some extension pages though. Sounds like it could be an Edge bug.

**Comment by seanmcbreen** [comment]
Doh lets hope so - I'll keep checking as well - thanks!

**Comment by seanmcbreen** [comment]
![image](https://cloud.githubusercontent.com/assets/1051190/11160549/1b0d0c1c-8a20-11e5-9e40-6298792ca6d6.png)

second report :(

**Comment by seanmcbreen** [comment]
also repros on IE11 for SVG icons

**Comment by roblourens** [comment]
It actually looks ok now
