### ISSUE TITLE
Integrated terminal truncated

### ISSUE THREAD

**Issue by ggrimbert** [Microsoft/vscode#56908]
Hi,

Sorry if this has been already reported, but I haven't found it.

The lines inside the integrated terminal are truncated, as shown in the screenshot below : 

![image](https://user-images.githubusercontent.com/15869188/44405779-59fa0f80-a55a-11e8-8814-eaa613f857d2.png)

It happens with the "terminal" tab, works for regular terminal or tasks (tsc --watch) : 
![image](https://user-images.githubusercontent.com/15869188/44405888-a3e2f580-a55a-11e8-99f1-65083789fcb3.png)

I just passed to Kubuntu 18.04, before I was on 16.04 and there were no problems

- VSCode Version: 1.26.1
- OS Version: Kubuntu 18.04.1

Steps to Reproduce:

1. Open VSCode 
2. Open "terminal" tab and write anything

Does this issue occur when all extensions are disabled?: Yes

**Comment by ggrimbert** [comment]
I tried to change font / line size; it doesn't change anything to the problem

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/35901
