### ISSUE TITLE
for security reasons dtd is prohibited in this xml document test manager

### ISSUE THREAD

**Issue by crlybrcs** [Microsoft/vscode#56905]
![test manager activate license](https://user-images.githubusercontent.com/20788931/44401044-9a06c580-a54d-11e8-9440-ac37c1ad0660.JPG)
Issue Type: <b>Bug</b>

When starting Test Manager 2017, the problem occurs. Uninstallion and new installation does not help. 

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.69GB (6.21GB free)|
|Process Argv|C:\Users\Tatiana\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by rebornix** [comment]
@crlybrcs I don't think it's a VSCode issue, you can want to ask in Visual Studio Test Manager forum.
