### ISSUE TITLE
Remote attach linux program failed.

### ISSUE THREAD

**Issue by AbelaroJiang** [Microsoft/vscode#56901]
When I debug remote linux program by attach mode on windows, I failed and it display sh: 1: [: Linux: unexpected operator
![image](https://user-images.githubusercontent.com/22406984/44398043-09dc7680-a575-11e8-981c-8bb4e6d47855.png)

configuration below：
        {
            "name": "Remote Attach",
            "type": "cppdbg",
            "request": "attach",
            "program": "/smbshare/test/build/bin/Test",
            "processId": "${command:pickRemoteProcess}",
            "pipeTransport": {
                "pipeCwd": "",
                "pipeProgram": "ssh",
                "pipeArgs": [
                    "smite@192.168.1.78"
                ],
                "debuggerPath": "/usr/bin/gdb"
            },
            "sourceFileMap": {
                "/smbshare/test": "${workspaceRoot}"
            },
            "linux": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            },
            "windows": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            }
        }
Note: It  works well at before visual code version.

**Comment by isidorn** [comment]
Please file this against the cpp dbg extension
