### ISSUE TITLE
Intellisense very slow on latest version

### ISSUE THREAD

**Issue by premun** [Microsoft/vscode#56909]
Issue Type: <b>Performance Issue</b>

I have a very big project and with the latest update, any intellisense is very slow - displaying "Loading..." takes a very long time on 1.26.1.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.82GB (18.87GB free)|
|Process Argv|C:\Users\prvysoky\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    81	 10960	code main
    0	    76	  8372	   shared-process
    0	   520	  9712	   window (● DiversityPicker.tsx - clients - Visual Studio Code)
    0	    82	 15528	     extensionHost
    0	  1053	  4864	       electron_node electronForkStart.js tsserver.js 
    0	    47	 13556	         electron_node typingsInstaller.js tsserver.js typesMap.js 
    0	    21	  8468	       electron_node jsonServerMain.js 
    0	    65	 17356	       electron_node tslintServer.js 
    0	    46	 16228	     searchService
    0	     3	 21912	     electron-crash-reporter
    0	    11	 22416	     watcherService 
    0	     5	 20976	       console-window-host (Windows internal process)
    0	   254	 19992	   gpu-process
    1	    70	 23432	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● DiversityPicker.tsx - clients - Visual Studio Code)
|    Folder (clients): 19871 files
|      File types: js(5345) json(3925) h(2521) ts(1845) html(1520) tsx(973)
|                  png(833) java(342) cs(305) m(213)
|      Conf files: csproj(32) package.json(22) sln(6) gulp.js(3)
|                  tsconfig.json(2) project.json(1) settings.json(1)
|                  launch.json(1) tasks.json(1) tslint.json(1)
|                  webpack.config.js(1);
```

</details>
<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.36
vscode-git-blamer|how|1.1.2
json-to-ts|Mar|1.5.5
PowerShell|ms-|1.8.3
debugger-for-chrome|msj|4.8.2
project-snippets|reb|0.5.0
trailing-spaces|sha|0.2.11
sort-lines|Tyr|1.7.0

</details>

**Comment by mjbvz** [comment]
What type of project? Please provide more details about your project setup

**Comment by premun** [comment]
Sorry, I thought it will be in logs. It is a large TS/React project and TS intellisense is very slow. Every intellisense pop-up takes about 2-4 seconds even when about local variables.
It happens for the whole team across different MacOS & Windows and we all went back to 1.23 which fixed it.

Feel free to contact me internally for more information on prvysoky@microsoft.com.

**Comment by mjbvz** [comment]
Thanks. Please try collecting the TS Server log so we can investigate:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a folder with a `tsserver.log` file in it

Look through that log file for errors or stack traces. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by premun** [comment]
I sent you the logs via Microsoft Teams as it contains sensitive data.

**Comment by mjbvz** [comment]
Closing as we follow up internally. If you have not already done so, please open an issue against typescript and send them your logs

**Comment by premun** [comment]
@mjbvz I noticed that switching TypeScript version in VS code has no effect and using TS 2.8.0 still results in slow intellisense. Is this still TS issue?

**Comment by deftomat** [comment]
@premun Hi, I'm not sure if it can helps, but can you give a try to the latest version (`3.2.0-dev.20181006`)? It helps us a lot. For more info see https://github.com/Microsoft/TypeScript/issues/26680.

**Comment by premun** [comment]
@deftomat do I need to be on VS Code insiders or install custom TS for that? I checked and 1.28.0 of VS Code comes with 3.1.1.

**Comment by deftomat** [comment]
@premun No, you just need to install TS `3.2.0-dev.20181006` or newest and use a workspace version of TypeScript in VSCode.

**Comment by premun** [comment]
@deftomat I have tried today with your version and after VS Code starts, the first call for intellisense takes about 5 seconds, then my VS Code file scrollbar jumped to the top of file and after that everything was fast and working smooth as expected. I guess it's fine then! :)
