### ISSUE TITLE
[css] Incorrect "Property is ignored" warning when specifying width on inline replaced elements

### ISSUE THREAD

**Issue by PikeUK** [microsoft/vscode#56907]
Issue Type: <b>Bug</b>

When specifying a CSS width on an inline replaced element (e.g. an \<input>) the following warning is shown:

> Property is ignored due to the display. With 'display: inline', the width, height, margin-top, margin-bottom, and float properties have no effect.

The width isn't ignored for replaced inline elements (such as \<input>) as you can see in the following testcase: https://jsfiddle.net/Lczhqytu/

From CSS2 spec regarding width (section 10.2):

> This property does not apply to non-replaced inline elements.

The same issue applies to the other properties mentioned in the warning.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz (12 x 3300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (7.74GB free)|
|Process Argv|C:\Users\\\<username>\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.14
hg|mrc|1.2.3
vscode-apache|mrm|1.1.1
vscode-hexdump|sle|1.6.0

</details>

**Comment by octref** [comment]
While we haven't fixed it, you can set `"css.lint.propertyIgnoredDueToDisplay": "off"` to disable this linting rule.

**Comment by MorrisJohns** [comment]
<img> tags can be display: inline and have a width set (e.g. high density image set to logical pixels). Perhaps just change the warning text? Something like:
"Property may ignored on some inline elements. Due to the 'display: inline', the width, height, margin-top, margin-bottom, and float properties only affect replaceable inline elements (IMG, INPUT, TEXTAREA, CANVAS, VIDEO etc)."

**Comment by MorrisJohns** [comment]
PS: propertyIgnoredDueToDisplay worked fine.

For others: I went to File | Preferences in VS Code, searched for propertyIgnoredDueToDisplay and changed it to "ignore" and it applied the change immediately - nice work - thanks guys!

**Comment by zamarise** [comment]
@octref As mentioned in another comment, `"css.lint.propertyIgnoredDueToDisplay": "ignore` didn't work for me either. I set the following in User and Workspace settings and the warning remained.
```
 "css.lint.propertyIgnoredDueToDisplay": "ignore",
  "less.lint.propertyIgnoredDueToDisplay": "ignore",
  "scss.lint.propertyIgnoredDueToDisplay": "ignore"
```

**Comment by octref** [comment]
@aeschli Since there's no way to correctly detect this rule, can we deprecate and drop it?

**Comment by aeschli** [comment]
I would suggest fixing the text as suggested in https://github.com/microsoft/vscode/issues/56907#issuecomment-469472098

**Comment by octref** [comment]
@aeschli What about `float`? It applies to all elements. For the 5 properties "width, height, margin-top, margin-bottom, and float", do we have to describe all combinations where it doesn't apply to specific elements (such as the combination of `width` on "inline replaced element"), so this diagnostic is wrong?

**Comment by aderchox** [comment]
I'm having the same issue.

**Comment by hroger1030** [comment]
Bump, issue is still present. How long does it take to remove a rule that just isn't correct?

If this is something that a developer feels that needs to be identified and messaged, lets fix the existing problem (bad messaging) before we worry about how to identify and message for this correctly. No functionality is better than broken functionality.

**Comment by aeschli** [comment]
I removed the check.
