### ISSUE TITLE
Working on HTML pages became tough for me when suddenly i got a bug, whenever i click on any div it highlights all the div's instead of telling which div should be the closed one.

### ISSUE THREAD

**Issue by s1ssagar** [Microsoft/vscode#56911]
- VSCode Version: 1.26.1
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Make html div's
2. Select one
![screenshot from 2018-08-21 20-03-13](https://user-images.githubusercontent.com/13457095/44408174-76f40a00-a57d-11e8-982d-a0c9c305cf1a.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by rebornix** [comment]
You can disable this feature by turning off `editor.occurrencesHighlight`.
