### ISSUE TITLE
vsdbg on Linux crashes at startup when path is too long

### ISSUE THREAD

**Issue by kevingosse** [Microsoft/vscode#56916]
On Linux (CentOS 7), vsdbg crashes at startup with the message:

> terminate called after throwing an instance of 'PAL_SEHException'

After some trial and error, I discovered that the crash is caused by the length of the path from which vsdbg is running

Works:
`/home/k.gosse/bb485db3-8610-459d-9597-797b813a0846-S52/opt/mesos/slaves/bb485db3-8610-459d-9597-797b813a0846-S52/frameworks/2cd1b537-06cb-42ad-a7a1-1486920f9c54-0000/123456789012345`

Doesn't work:
`/home/k.gosse/bb485db3-8610-459d-9597-797b813a0846-S52/opt/mesos/slaves/bb485db3-8610-459d-9597-797b813a0846-S52/frameworks/2cd1b537-06cb-42ad-a7a1-1486920f9c54-0000/1234567890123456`

So it seems the limit is 181 characters. 

I suspect that it crashes when loading `Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.ResultProvider.vsdconfig` (74 characters long), as 182 +74 = 256.

**Comment by Tyriar** [comment]
How are you running vsdbg?

**Comment by kevingosse** [comment]
I'm launching it manually with `--interpreter=vscode` parameter

**Comment by Tyriar** [comment]
@kevingosse in an external terminal? It's not clear why you think this is an issue with VS Code, is it not an issue with `vsdbg`?

**Comment by kevingosse** [comment]
This is completely unrelated to VS Code, the issue is purely in vsdbg. But I was told to report it here: https://twitter.com/VisualStudio/status/1031893048974827521

I guess this is the wrong place then. Do you know who has ownership on vsdbg?

**Comment by Tyriar** [comment]
@kevingosse yeah this is the wrong place 😕 

If you saw it in Visual Studio and aren't using some extension then I'd follow the generic [report a problem in VS instructions](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017) and/or reply back the VS Twitter account.

Sorry about the hassle 🙂
