### ISSUE TITLE
Alt + enter in breadcrumbs should open file on right side

### ISSUE THREAD

**Issue by kasperpihl** [Microsoft/vscode#56915]
Similar to #54743, but with keyboard.

It would be amazing if alt+enter when using the keyboard also opened on the right side.
Currently I have to alt+click with the mouse to open on right side.
<3 VSCODE

**Comment by jrieken** [comment]
@kasperpihl You mean in the picker, right? Iff so, try `cmd+enter`

**Comment by kasperpihl** [comment]
Thanks for the super fast response!!! 🏎 
I tried the cmd+enter, but it seems that it opens current file on right side, not the one I selected.
If I'm in view.js and I open breadcrumbs, then move to view.css with keyboard and press cmd+enter, it opens up view.js on the right side, not view.css.
Guess this is a bug?

**Comment by jrieken** [comment]
Hm, that is interesting... Any chance you have a custom configuration for `cmd+enter`?

**Comment by jrieken** [comment]
D'oh, yeah actually a bug. I can reproduce now.

**Comment by jrieken** [comment]
Ok, pushed a fix for next insiders

**Comment by kasperpihl** [comment]
EPIC!!! 🎉 🕺 Thanks Johannes
