### ISSUE TITLE
ImportError: Error while finding module specification for 'module.name' (ModuleNotFoundError: No module named 'module')

### ISSUE THREAD

**Issue by capmark** [Microsoft/vscode#56924]
Just installed vs code and trying to run a simple file with 2 lines 
f= 2123
print(f)

I get the error 
ImportError: Error while finding module specification for 'module.name' (ModuleNotFoundError: No module named 'module')
in  both terminal and debug console

**Comment by capmark** [comment]
Env is Windows 7 Premium

**Comment by isidorn** [comment]
Please file this against the extension which you are using for running that file
