### ISSUE TITLE
Wrong translation on menu in Spanish language

### ISSUE THREAD

**Issue by juanrarodriguez18** [Microsoft/vscode#56922]
Issue Type: <b>Bug</b>

1º Right click on the search menu in any file resulting from the search.

Appear the option to delete as "Despedir", but the correct text would be "Eliminar" as it appears in the file browser.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.94GB (1.73GB free)|
|Process Argv|C:\Users\JuanRamón\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-nsp|ada|1.0.1
latex-preview|ajs|0.5.1
vscode-caniuse|aka|0.5.3
Bookmarks|ale|9.0.3
vscode-simpler-icons|dav|1.5.2
vscode-auto-open-markdown-preview|hnw|0.0.4
latex-workshop|Jam|5.8.2
Angular2|joh|6.1.5
vscode-todo|Mat|0.8.0
ecdc|mit|0.12.0
vscode-language-pack-es|MS-|1.26.3
python|ms-|2018.7.1
jscs|ms-|0.1.9
vscode-docker|Pet|0.1.0
searchdocs|rob|0.0.3
yo|sam|0.9.3
sonarlint-vscode|Son|1.5.0
code-spell-checker|str|1.6.10
react-beautify|tai|0.3.0
Angular2|UVB|0.4.1

</details>

**Comment by danyeh** [comment]
Thank you @juanrarodriguez18 for your feedback!
We host translation in Transifex and accept contribution from community. General guidance is here: https://aka.ms/vscodeloc.
It will be great if you can fix in Transifex and get enough vote from native speaker contributors so your fix get used in product.
Must be this string.

**Comment by danyeh** [comment]
This string: https://www.transifex.com/microsoft-oss/vscode-workbench/translate/#es/$/122408151?q=translation_text%3ADespedir

**Comment by juanrarodriguez18** [comment]
Thank you so much for your solution, I have put the suggestion of translation. 
I am going to close the Issue.
Regards.
