### ISSUE TITLE
Problems Panel is not clearing after compile

### ISSUE THREAD

**Issue by doug-episource** [Microsoft/vscode#56923]
Problems panel is not clearing on the new version, 1.26.1, after compiling with the "ForceCode" extension. Reproduction is tricky (you need to have a Salesforce Org), so I will post code attempts to clear the panel.

On an error, the following code is executed to add errors to the Problem Panel:
```
var diagnosticCollection: vscode.DiagnosticCollection = vscode.languages.createDiagnosticCollection(document.fileName);
var diagnostics: vscode.Diagnostic[] = [];
if (res.records && res.records.length > 0) {
    res.records.filter(r => r.State !== 'Error').forEach(containerAsyncRequest => {
        containerAsyncRequest.DeployDetails.componentFailures.forEach(failure => {
            // Create Red squiggly lines under the errors that came back
            if (failure.problemType === 'Error') {
                var failureLineNumber: number = Math.abs(failure.lineNumber || failure.LineNumber || 1);
                var failureRange: vscode.Range = document.lineAt(failureLineNumber - 1).range;
                if (failure.columnNumber > 0) {
                    failureRange = failureRange.with(new vscode.Position((failureLineNumber - 1), failure.columnNumber));
                }
                diagnostics.push(new vscode.Diagnostic(failureRange, failure.problem, failure.problemType));
            }
        });
    });
} else if (res.errors && res.errors.length > 0) {
    // We got an error with the container
    res.errors.forEach(err => {
        console.error(err);
    });
    vscode.window.forceCode.statusBarItem.text = `${name} ${DefType ? DefType : ''} $(alert)`;
} else if (res.State === 'Error') {
    vscode.window.forceCode.statusBarItem.text = `${name} ${DefType ? DefType : ''} $(alert)`;
}
diagnosticCollection.set(document.uri, diagnostics);
```
This code works perfectly fine, updates the status bar, and adds the errors correctly. However, on recompiling with no errors, under 1.25.1, the Problems Panel cleared correctly; in 1.26.1, it does not. On a success, the above code for `res.records.filter(r => r.State !== 'Error').forEach` is not executed, leaving diagnostics to be empty (or []) and to be set as normal.

I have modified the extension to explicitly call `diagnosticCollection.clear()`, `diagnosticCollection.delete(document.uri)` and `diagnosticCollection.dispose()`, but the Problems Panel does not clear.

This has only started happening with the 1.26 release.

System Info:
- VSCode Version: 1.26.1
- OS Version: macOS Sierra, 10.12.6

**Comment by jrieken** [comment]
Can you adjust for code sample so that I can run it and reproduce the issue. Thanks

**Comment by doug-episource** [comment]
I really wish I could, but it is a challenge.
First, I am not the author of the extension -- it has been deprecated in favor of a different Salesforce workflow -- and it needs to be modified because of broken dependencies and the NodeJS upgrade. I have made the necessary changes to the extension and recompiled, so I can provide a vsix for testing. 
Next, you would have to sign up for a free Salesforce Dev Org and deploy code to it. Then, after connecting the ForceCode extension to that Org, you can then deploy.
As you can see, there are quite a number of steps to take, so that is why I posted the extension's code for adding and clearing the Problems Panel. Not really sure how to proceed here, but it is a definite issue with v1.26 as it was working fine with v1.25. I know that a new feature let's you fix items in the Problems Panel, so I assume it is somehow related to that.

**Comment by jrieken** [comment]
Have you tried this with 1.26.**1**? We have made a critical fix for the problems panel, but from the sounds of it, it doesn't seem related to the new features

**Comment by doug-episource** [comment]
Yes, I did. I have reverted back to 1.25.1 and it works. It does not work on v1.26.1. Sorry, I stated the original version in my opening post, but neglected to mention the ".1" in my follow-up post.

**Comment by jrieken** [comment]
Funky, that was the only change in the diagnostics area between 1.25.x and 1.26.x. I suspect this is an issue with the extension because we don't receive other feedback like this. I'd still a set of reproducible steps tho

**Comment by atsushieno** [comment]
My language plugin that emits diagnostics got regression in 1.26.1 and this issue seems to be related to the problem. https://github.com/atsushieno/vscode-language-review/issues/17

**Comment by TravisTheTechie** [comment]
I can confirm this is happening with my extension now as well. Debugging, it looks like each successive call of [`languages.createDiagnosticCollection("Write-Good Lints")`](https://github.com/TravisTheTechie/vscode-write-good/blob/master/src/extension.ts#L40) produces a new diagnostics with owner of "Write-Good Lints0", "Write-Good Lints1", "Write-Good Lints2", etc. See https://github.com/TravisTheTechie/vscode-write-good/issues/10. createDiagnosticsCollection no longer appears to return a collection with the existing diagnostics in it as well, the collection is empty even though there are diagnostics that apply.

**Comment by doug-episource** [comment]
@TravisTheTechie I agree that it is not Extension related. The ForceCode Extension is not doing anything fancy - no parsing of output windows or anything. It builds the Problems Panel manually and cannot clear it. I added several lines to try to force clearing it, but it never clears and always show an empty collection when setting it up or getting the current one. Oh well, I will see if it gets resolved in a future VSCode version and update then.
