### ISSUE TITLE
Trouble clicking first character in line

### ISSUE THREAD

**Issue by natedawg1013** [microsoft/vscode#56920]
Issue Type: <b>Bug</b>

When trying to drag-select from the beginning of a line, clicking when the cursor goes from a pointer to a text cursor and dragging does not select anything. In order to start a selection, the cursor must be at least a few pixels into the first character of the line. This can be quite difficult at times. Sometimes I cannot select the first character at all and have tro make the selection right-to-left. Other times it is doable but difficult. No matter what though, a selection cannot begin to the left of the first character (though most editors allow this). And usually not anywhere within the first few pixels of that character.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.41GB (1.47GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
unique-lines|bib|1.0.0
vscode-astyle|chi|0.9.0
bracket-pair-colorizer|Coe|1.0.59
toggle-excluded-files|eam|1.6.0
base-converter|hoo|0.0.1
auto-comment-blocks|kev|1.0.1
vscode-smart-column-indenter|lmc|0.0.13
cppcheck|mat|0.2.2
vscode-devskim|MS-|0.2.2
python|ms-|2018.7.1
cpptools|ms-|0.18.1
sublime-keybindings|ms-|4.0.0
highlight-dodgy-characters|nac|1.0.0
preview-control-characters|nes|0.0.1
vscode-systemd|Neu|0.1.0
material-icon-theme|PKi|3.5.3
psi-header|psi|1.5.0
reloaded-cpp|rel|0.1.6
vscode-coverage-gutters|rya|2.1.1
perforce|sle|3.1.0
rewrap|stk|1.9.1

(1 theme extensions excluded)

</details>

**Comment by xStrom** [comment]
What's most bizzare is that the cursor changes from _normal select_ ![inter-mouse-image5](https://user-images.githubusercontent.com/754881/61579888-83753f80-ab0b-11e9-98aa-a0e782fecd58.png) to _text select_ ![inter-mouse-image7](https://user-images.githubusercontent.com/754881/61579889-83753f80-ab0b-11e9-85d4-9e6774d2bdd0.png) a few pixels before clicking has any effect! I have to move the cursor even more for clicking to actually select that position.

**Comment by xStrom** [comment]
It's unclear where I'm supposed to upvote this issue.
