### ISSUE TITLE
Make CSS linting error show rule name

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#56925]
![image](https://user-images.githubusercontent.com/4033249/44417722-2784ee00-a52b-11e8-85cf-0e1965e8da66.png)

This makes it hard for users to find which rule controls the error.

For example, in Vue, we have this:

![image](https://user-images.githubusercontent.com/4033249/44417733-353a7380-a52b-11e8-8606-aa8197a8b544.png)

So user could quickly identify which ESLint rule to disable.

**Comment by connorshea** [comment]
So this is where it's done in the vue package:

https://github.com/vuejs/vetur/blob/9c8f590391d10e291210f94e681e624d336c243c/server/src/modes/template/services/htmlValidation.ts#L12

Comparatively, we have this line in the css-language-service:

https://github.com/Microsoft/vscode-css-languageservice/blob/be0045761374ad632194fd4145b37d2534d63e0c/src/services/cssValidation.ts#L38

So we need to modify that line to provide us with the rule name and include that in the `message` argument. I think we just need to use the `getRule()` function alongside `getMessage()`.

**Comment by octref** [comment]
Oh ok, sounds good. Thanks!

**Comment by octref** [comment]
> EDIT: I reinstalled the vscode repo from scratch and now everything is fine 🤷‍♂️

Yeah, the deps change a lot so always rebuild, especially if VS Code upgrades electron version.
If you build `vscode-css-languageservice` and link it, you shouldn't get the errors anymore.

**Comment by connorshea** [comment]
I think there's a missing step in the `CONTRIBUTING.md`, because it never mentions the `yarn compile` step which seems to be required for `yarn watch` in `css-language-features/server` to work.

**Comment by bpasero** [comment]
@octref I suggest to make it clearer that the rule is the thing in parentheses, e.g. this looks weird:

![image](https://user-images.githubusercontent.com/900690/44772199-7f47d880-ab6d-11e8-8a00-493b90e74fc6.png)

**Comment by octref** [comment]
@connorshea This will indeed be a problem, thanks.

![image](https://user-images.githubusercontent.com/4033249/44814401-71a44a00-ab91-11e8-8f93-17032d0859ca.png)

I updated the logic, so if it's a linting rule, it'll show `[langId].lint.[lintRule]`. Otherwise, it falls back to using `document.languageId`.

![image](https://user-images.githubusercontent.com/4033249/44814476-af08d780-ab91-11e8-9bc3-837d2b4bb6f9.png)

**Comment by connorshea** [comment]
👍

**Comment by octref** [comment]
@connorshea Sorry this got reverted because of https://github.com/Microsoft/vscode/issues/62159. I'll try to bring it back next milestone.
