### ISSUE TITLE
Remove unsupported from title, ensure notification isn't annoying

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#56929]
Let's make the unsupported/patch message appear in the about page and the issue reporter. The notification should show once per version.

Feedback in https://github.com/Microsoft/vscode/issues/39137#issuecomment-414496476

**Comment by fabiospampinato** [comment]
[here](https://github.com/Microsoft/vscode/issues/30556) there's also some more feedback on the annoyance of the "unsupported" message.

I don't know if it's relevant to the discussion, but I'm personally patching VSC for the following reasons:
- [Titlebar-less VSCode](https://marketplace.visualstudio.com/items?itemName=lehni.vscode-titlebar-less-macos) - I get more vertical real estate, and it just looks awesome
- [Terminal/panel restoration](https://github.com/Microsoft/vscode/issues/39137#issuecomment-414496476) is driving me nuts.
- VSC's interface is a bit too cluttered for my tastes, I load a custom css file for removing some stuff.

There are currently 2 extensions, that I'm aware of, for removing the "unsupported" message from the titlebar, my [No Unsupported](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-no-unsupported) and @lehni's [Fix VSCode Checksum](https://marketplace.visualstudio.com/items?itemName=lehni.vscode-fix-checksums). Maybe @lehni you can also add to the discussion.
