### ISSUE TITLE
Having config menu popping up above bottom of windows instead of having to scroll

### ISSUE THREAD

**Issue by JeffHeon** [Microsoft/vscode#56921]
I use VS Code maximized or full screen, and clicking on the config gear always bring a truncated menu. I'd rather have it in full and higher because I have to scroll every time.

Showing might help, please see my two screen shots.

<img width="210" alt="screen shot 2018-08-21 at 12 03 43" src="https://user-images.githubusercontent.com/1154213/44414136-07f5c180-a53b-11e8-9fc0-39286d6a14d3.png">
<img width="285" alt="screen shot 2018-08-21 at 12 06 04" src="https://user-images.githubusercontent.com/1154213/44414137-088e5800-a53b-11e8-8228-76cda8f27744.png">

I'm using MacOS 10.13.16

Thank you for your time.

**Comment by isidorn** [comment]
Please file this against Electron https://github.com/electron/electron
