### ISSUE TITLE
Breakpoints position stopped updating on file changes

### ISSUE THREAD

**Issue by leonardoamx** [Microsoft/vscode#56930]
Issue Type: <b>Bug</b>

Breakpoints used to move when adding/removing lines, following the line they were added. Not they behave as if they were attached to line number, so I have to restore them when editing files :(

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz (8 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.84GB (1.48GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-file-peek|abi|1.0.1
Bookmarks|ale|9.0.3
vscode-multi-line-tricks|big|0.0.3
htmltagwrap|bra|0.0.7
turbo-console-log|Cha|1.2.5
vscode-quick-select|dba|0.2.6
vscode-style-formatter|dwe|1.0.0
gitlens|eam|8.5.5
vscode-html-css|ecm|0.2.0
hungry-backspace|ekl|1.0.0
json-tools|eri|1.0.2
php-debug|fel|1.12.4
php-intellisense|fel|2.3.3
vscode-quick-file-actions|fil|1.0.0
code-sync|gol|2.5.3
vsc-space-block-jumper|jmf|1.2.2
quicksnippet|mou|0.0.1
vscode-language-pack-es|MS-|1.26.3
debugger-for-chrome|msj|4.8.2
material-icon-theme|PKi|3.5.3
blockalign|San|0.6.0
sassyah|tom|0.0.3
highlight-matching-tag|vin|0.4.4
php-docblock-generator|vin|0.0.1
expand-selection-to-scope|vit|0.2.0
change-case|wma|1.0.0
join-lines|wma|0.2.2
wordpress-toolbox|wor|1.1.6

</details>

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/56398
