### ISSUE TITLE
Both "Go To Symbol on File / Workspace" are not working

### ISSUE THREAD

**Issue by mauriciogior** [Microsoft/vscode#56939]
Issue Type: <b>Bug</b>

1- Create a new Workspace.
2- Create a file called `test.php` with the following code:

```php
<?php
function example() {
    //
}
```

3- Save it and try searching `example` symbol on file with `@` or on workspace with `#`.
4- Both searches can't find any symbol.

**Screenshots:**
<img width="735" alt="screen shot 2018-08-21 at 16 40 53" src="https://user-images.githubusercontent.com/2918286/44425271-bd3b7000-a561-11e8-82ca-2682d2c10413.png">
<img width="734" alt="screen shot 2018-08-21 at 16 41 08" src="https://user-images.githubusercontent.com/2918286/44425278-c298ba80-a561-11e8-959d-59374a7b3705.png">

**Expected result (done with SublimeText 3):**
<img width="592" alt="screen shot 2018-08-21 at 16 47 07" src="https://user-images.githubusercontent.com/2918286/44425318-dcd29880-a561-11e8-8734-e7c74b966be6.png">

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.76GB free)|
|Process Argv|/private/var/folders/qf/1txzrysd3lgcgsc227106_dm0000gn/T/AppTranslocation/158E0426-E098-41B8-9C74-9AC2799FC6F0/d/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|2.3.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vscode-subword-navigation|ow|1.2.0
material-icon-theme|PKi|3.5.3
code-spell-checker|str|1.6.10

</details>

**Comment by roblourens** [comment]
Not out of the box, you will need to install one of the PHP intellisense extensions for this.
