### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by federhico** [Microsoft/vscode#56934]
- VSCode Version: 1.26.1
- OS Version: Win 10

Steps to Reproduce:

1. Open the "view" menu.
2. See all new features (Apparence , Toggle Breadcums) are not translated to spanish
3. Inside Editor Design, the option "Two Rows Right" also isn't translated to spanish

**Comment by dbaeumer** [comment]
They are translated for German so it looks like a translation problem.

<img width="502" alt="capture" src="https://user-images.githubusercontent.com/1931590/44453626-cd9f2980-a5f9-11e8-8da1-71d739375450.png">

**Comment by danyeh** [comment]
They were all localized in Transifex. Will investigate further.
https://www.transifex.com/microsoft-oss/vscode-workbench/translate/#es/$/149195306?q=text%3AAppearance

**Comment by danyeh** [comment]
It is ok now. But don't know the root cause. Looks like timing issue but strings were translated before last cutoff.
![image](https://user-images.githubusercontent.com/19785531/46028478-88ad5d80-c0a5-11e8-8112-2e90121ae523.png)
