### ISSUE TITLE
VS code works only in full screen

### ISSUE THREAD

**Issue by desitnit** [microsoft/vscode#56937]
Visual Studio code on my computer works only in full screen.
When not in full screen I see black screen.
When in full screen I still have some issues sometimes. The colors can change sporadically.
I don't have these kind of issues with other programs that I use.

![vscode](https://user-images.githubusercontent.com/31899940/44424350-bbf84c00-a53d-11e8-87e3-b3164d71b9ef.jpg)

**Comment by federhico** [comment]
Can you share your system configuration? 
-OS version
- vscode version
- graphic card ? drivers?
-etc...

**Comment by bpasero** [comment]
@desitnit does it work if you run "`code --disable-gpu`"?

**Comment by desitnit** [comment]
Yes, it does. I'll use it as a workaround for now, thank you.

**Comment by apwelsh** [comment]
When will this be fixed?  Running code --disable-gpu is not a good solution for those that use the Explorer integration.  I would think adding this to the default options setting and pushing out a hotfix would be an appropriate fix until the next release.

**Comment by desitnit** [comment]
It was actually fixed for me with one of the latest versions.

**Comment by apwelsh** [comment]
That’s a bummer.  The last two updates did not work for me, but the explorers build does
