### ISSUE TITLE
VSCode remembers my workspace even though window.restoreWindows=none

### ISSUE THREAD

**Issue by NiklasRosenstein** [Microsoft/vscode#56936]
- VSCode Version: 1.26.1
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Set setting `window.restoreWindows: "none"`
2. Open multiple folders in the same VS Code Window (eg. `code -a foo/ bar/`)
3. Close the Window that contains the workspace with the multiple folders as the last Window of VS Code
4. Start VS Code again and see the Window with the same workspace restored

Expected Result:

An empty VS Code Window.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
This is "as designed": if you open multiple folders in one window, that window creates a new "untitled" workspace for you and will restore it unless you explicitly change that window to another folder or workspace. Untitled workspaces potentially contain settings from you in the workspace file so we never drop it.

**Comment by bpasero** [comment]
Possibly duplicate: https://github.com/Microsoft/vscode/issues/30972

**Comment by NiklasRosenstein** [comment]
The documentation of the "none" mode is incorrect if that is behaviour as-designed.

> "Never reopen a window. Always start with an empty one."

Would it be possible to change the behaviour with an extension?
