### ISSUE TITLE
Debug quick open doesn't fuzzy search across words

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#56931]
![image](https://user-images.githubusercontent.com/323878/44420064-c7457a80-a531-11e8-8ccd-b4b01480d725.png)

- Open quick open, type `debug attach search`
- `Attach to Search Process` should be found, but it isn't
- `debug attach to search` works, but it would be great if the search was fuzzier. Not sure if individual quick pick handlers control this?

**Comment by isidorn** [comment]
Good catch. For some reason this works properly for `task` even though `Tasks` use a very similar [`QuickOpenHandler`](https://github.com/Microsoft/vscode/blob/19c19e91b704cdf5f72adb20a3f7449e7f4559e1/src/vs/workbench/parts/tasks/browser/taskQuickOpen.ts#L33) imelementation as [`debug`](https://github.com/Microsoft/vscode/blob/19c19e91b704cdf5f72adb20a3f7449e7f4559e1/src/vs/workbench/parts/debug/browser/debugQuickOpen.ts#L77)

@chrmarti is there some option or some configuration which I am missing in debug land, though I checked and I seem to be doing everything ok.

**Comment by chrmarti** [comment]
You're searching for a substring: https://github.com/Microsoft/vscode/blob/67c9cac441d56ad49745df805c5828c7c5cfbccf/src/vs/workbench/parts/debug/browser/debugQuickOpen.ts#L101

Can you try the fuzzy matching, like tasks? https://github.com/Microsoft/vscode/blob/67c9cac441d56ad49745df805c5828c7c5cfbccf/src/vs/workbench/parts/tasks/browser/quickOpen.ts#L138

**Comment by isidorn** [comment]
@chrmarti thanks, that makes perfect sence.
