### ISSUE TITLE
Tooltips in Watch Window are hardly shown

### ISSUE THREAD

**Issue by DonkeyKongJr** [Microsoft/vscode#56935]
- VSCode Version: 1.26.1
- OS Version: macOS Mojave (18A353d)

Steps to Reproduce:

1. Set Breakpoint
2. Start Debug
3. Add variable to watch window
4. Hover with mouse over variable
5. Hardly a tooltip with full value is shown
6. No Tooltip is shown when moving the mouse quickly between variables

<img width="537" alt="watch vs code debug" src="https://user-images.githubusercontent.com/29427429/44422407-56c74980-a583-11e8-8a0a-99afd4da5f31.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
This is just how the native browser hover behaves and there is nothing we can do about this.
Closing as out of scope as we do not want to have a custom hover implementation in the viewlet as the one we have  in the editor.
