### ISSUE TITLE
Separate color scheme for Output and Terminal window

### ISSUE THREAD

**Issue by cmoya212** [Microsoft/vscode#56938]
It would be great if the Output and Terminal window allowed you to specify a separate (say, Dark) color scheme that was separate than the overall VSCode color scheme.

**Comment by Tyriar** [comment]
Themes can set these separately, you can also override them for your theme of choice using the theme keys like so:

```
"workbench.colorCustomizations": {
  "terminal.background": "#ff0000"
}
```
