### ISSUE TITLE
How to Create a project

### ISSUE THREAD

**Issue by jeff881208** [Microsoft/vscode#5694]
I just read the document and experience it in Win 10 . It just show how to open or edit a C# Project, I want to know how to create and start a project . If I can't create a project , how could I start ,edit, debug, run ,and build a project ? Hope your feedback .

**Comment by dbaeumer** [comment]
@jrieken could you point him to the right OmniSharp doc.

**Comment by rhires** [comment]
@jeff881208 - I think you need to have a look at https://docs.asp.net/en/latest/ - it will give a much broader understanding of what you might be looking for, if I understand your question correctly. VSCode is merely the editor for the code, not the whole computing stack.

**Comment by jeff881208** [comment]
@rhires   Hi everyone, I just read the document at https://docs.asp.net/en/latest/client-side/yeoman.html and 
https://docs.asp.net/en/latest/dnx/console.html . I know to to create and run a project from command-line. But we I try to debug the project through VS Code. it doesn't work . It shows DebugAdapter bin folder not found on path C:/Users/Jeff/.vscode/extensions/ms-vscode.csharp-0.3.7/coreclr-debug/debugAdapters/OpenDebugAD7.exe. 

Thanks.
 
![Uploading Issues when debug.png…]()

**Comment by jeff881208** [comment]
@rhires Hi everyone, I just read the document at https://docs.asp.net/en/latest/client-side/yeoman.html and 
https://docs.asp.net/en/latest/dnx/console.html . I know to to create and run a project from command-line. But we I try to debug the project through VS Code. it doesn't work . It shows DebugAdapter bin folder not found on path C:/Users/Jeff/.vscode/extensions/ms-vscode.csharp-0.3.7/coreclr-debug/debugAdapters/OpenDebugAD7.exe.

Thanks.
