### ISSUE TITLE
Open Editors and Explorer tree does not remain synced

### ISSUE THREAD

**Issue by derekwallace** [Microsoft/vscode#56940]
Latest Insiders
vscode-python 2018..8.0-alph0

im working on a network drive with a large project.
Its not specific to a particular file. I see the issue in 2 scenarios.
Ctrl-P to open a recent file will open the file, but the Explorer tree will not sync to it.
Switching files in Open Editors will not sync the Explorer tree.

This scenario does work.
Scrolling to find a file in Explorer tree, and open it. In this case when you select the file in the Open Editors the Explorer tree will sync.

You end up with a list of Open Editors.. some of which will sync in Explorer and some wont.

**Comment by isidorn** [comment]
Can you reproduce if you disable all extensions?
If yes, please provide a step by step reproducable case. Or a even better a short gif showing the issue because your description is not clear
