### ISSUE TITLE
Red syntax highlighting for snake_case proptypes in JSX component

### ISSUE THREAD

**Issue by jessebond2** [Microsoft/vscode#56946]
This is an incredibly annoying change for codebases that use snake_case.

- VSCode Version: 12.6.1
- OS Version: osx 10.13.4

Steps to Reproduce:

1. With snake_case props red is visible
![image](https://user-images.githubusercontent.com/30394856/44432945-0fc45e80-a559-11e8-811f-482f94116473.png)

2. swap to non-snake_case and it isn't red anymore
![image](https://user-images.githubusercontent.com/30394856/44432956-236fc500-a559-11e8-952b-0c361783c30e.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/648
