### ISSUE TITLE
Latest build totally breaks formatOnSave and pegs extensionHost at 100% cpu

### ISSUE THREAD

**Issue by joelgetaction** [Microsoft/vscode#56951]
- VSCode Version: Version 1.27.0-insider (1.27.0-insider) 
 07796186d388044595cd101c49378c7cd48b350b  2018-08-21T08:33:22.481Z
- OS Version: macOS 10.13.6

Steps to Reproduce:

1. Open VS Code on a ReactNative workspace.
2. Improperly indent a file then save.  formatOnSave should reformat the file after/upon the save.  It does not.  If I show the process explorer, the extensionHost is constantly pegged at 100%.  Nothing has changed on my end.  No changes to code, extensions, OS or anything.  This only started happening when I upgraded VS Code.

Does this issue occur when all extensions are disabled?: Yes

![screen shot 2018-08-21 at 5 27 03 pm](https://user-images.githubusercontent.com/40219063/44436066-f37bee00-a567-11e8-95c2-ba38d2074fcd.png)

**Comment by joelgetaction** [comment]
Well, it seems to be related to Jest, since turning off the Jest extension seems to fix the issue, but that's bad news since this is a very popular extension so this might impact a lot of people.

See Jest: https://github.com/jest-community/vscode-jest

**Comment by joelgetaction** [comment]
See also https://github.com/jest-community/vscode-jest/issues/365

**Comment by rebornix** [comment]
Close this one in favor of https://github.com/jest-community/vscode-jest/issues/365
