### ISSUE TITLE
Provide UI for clearing keyboard shortcuts

### ISSUE THREAD

**Issue by lorensr** [Microsoft/vscode#56955]
When I hit the edit icon, I'm unable to clear it, even leaving the dialog blank and hitting enter. I'd like either that to work, or for a clear icon to be added.

![image](https://user-images.githubusercontent.com/251288/44436761-ede0d100-a584-11e8-8eb7-457cead24a0c.png)

**Comment by sandy081** [comment]
@lorensr You can use Remove Keybinding command from the context menu

![image](https://user-images.githubusercontent.com/10746682/44511810-f4706500-a6b8-11e8-997e-177a5811896c.png)
