### ISSUE TITLE
Pressing CTRL + C twice in integrated terminal does not terminate the process

### ISSUE THREAD

**Issue by malikhasan** [Microsoft/vscode#56958]
- VSCode Version: 1.26.1, 1.27.0 insider
- OS Version: Win 7 Enterprise x64 6.1.7601 SP1

Steps to Reproduce:

1. In integrated cmd Terminal, run a command like (gulp serve)
2. Press ctrl + c to terminate the process
3. This shows a message "^CTerminate batch job (Y/N)? ^C"
4. Pressing ctrl + c again keeps on adding "^C" in text format like "^CTerminate batch job (Y/N)? ^C^C^C^C^C^C^C^C^C^C^C^C"
5. You have to type "y" and then "Enter" to be able to terminate the job 
6. In separate cmd, this works correctly and pressing ctrl + c second time terminates the job

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
