### ISSUE TITLE
Intellisense for Typescript Very slow

### ISSUE THREAD

**Issue by filipmares** [Microsoft/vscode#56953]
Issue Type: <b>Bug</b>

Intellisense for Typescript has become very slow using the latests version. 

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:31:26.156Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|1.4.4
vscode-azurefunctions|ms-|0.10.0
python|ms-|2018.7.1
azure-account|ms-|0.4.3
project-snippets|reb|0.5.0
vscode-icons|rob|7.25.0
code-settings-sync|Sha|3.0.0
gitblame|wad|2.4.4
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by luchsamapparat** [comment]
There's already a lot of info in this thread:
https://github.com/Microsoft/vscode/issues/53541

**Comment by filipmares** [comment]
Seems faster in insiders with extensions turned off. Do you suggest I toggle some of my extensions or that there are some intellisense improvements in the insiders build?

**Comment by mjbvz** [comment]
Yes, please try insiders with extensions re-enabled. Then if you see the problem again, try toggling your extensions to see which one is causing this
