### ISSUE TITLE
Breakpoint not hit in extension debugging

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#5695]
This looks like a regression from 1.0 and might be related to the electron update:

* clone https://github.com/bpasero/vscode-markdown.git
* npm install
* open with VS Code
* add a breakpoint both into where the `extension.previewMarkdown` command does something as well as the virtual document provider to the top (`console.log("hit");`)
* run the extension
* open a file in the new window popping up
* invoke the command (`Markdown Preview`)
* the first breakpoint should get hit but the second is not for me
* this works fine with VS Code 1.0
* if you remove the breakpoint you will notice that `hit` is logged to the console so you can see the line is actually hit

@isidorn @weinand fyi

**Comment by isidorn** [comment]
I have looked into this and the simptoms are the same as for https://github.com/Microsoft/vscode/issues/5348
So node debug gets the same error from node.

This only happens in call back functions for some reasons - Martin also noticed that

**Comment by isidorn** [comment]
Verified it works now
