### ISSUE TITLE
Bad glyph rendering in editor

### ISSUE THREAD

**Issue by trabuzin** [Microsoft/vscode#5696]
- VSCode Version: 1.0.0
- OS Version: Windows 10 Pro 64-bit

VSCode is set to use Consolas font and when trying to edit attached file (runes.txt) with some rune glyphs, it displays just little squares with question mark inside.
Other editors such as Notepad++ and even basic Notepad that comes with the Windows, are able to display this file correctly when set to use Consolas font
![editor_compare](https://cloud.githubusercontent.com/assets/4740405/14761642/7b22e10a-0967-11e6-9a99-5f8ef3b6ef20.png)

.
I noticed that on linux system (Elementary OS 32-bit) VSCode 1.0.0 with the same Consolas font copied from Windows system displays same file correctly.
The file is UTF-8 encoded without BOM

Steps to Reproduce:
1. open attached file [runes.txt](https://github.com/Microsoft/vscode/files/232972/runes.txt) in VSCode on Widows

**Comment by anyong** [comment]
You can add more fonts to your editor font family in the settings. You should add a font like Segoe UI or something to add any characters that are not in Consolas.

**Comment by alexandrudima** [comment]
@realitylord Nice find. Nothing I tried on our side (messing extensively with the font family) helped. I have filed https://bugs.chromium.org/p/chromium/issues/detail?id=607528 against Chromium

**Comment by realitylord** [comment]
@alexandrudima Thanks for information. I had a hunch that it could be Chromium issue, but I didn't had time to investigate deeper.

**Comment by realitylord** [comment]
@alexandrudima I see that the issue on Chromium side was fixed.
Is there any chance to move this issue from Backlog to some milestone in near future? :)
Thanks.

**Comment by alexandrudima** [comment]
@realitylord It will take a while, but the fix will definitely come. We need to wait first for Electron to pick up a new version of Chromium that contains this fix and then we're pretty quick on our side in picking up new Electron versions.

I cannot say precisely when this would happen.

**Comment by realitylord** [comment]
@alexandrudima thanks for answer

**Comment by trabuzin** [comment]
I can confirm it's fixed now, VS Code 1.7.2, Win 10 x64.

Thanks 👍

**Comment by ramya-rao-a** [comment]
Marking as verified as the OP has confirmed so
