### ISSUE TITLE
vscode exception has occurred

### ISSUE THREAD

**Issue by JerryCao1985** [Microsoft/vscode#56960]
- VSCode Version: 1.26.1
- OS Version: MacOS High Sierra, Version 10.13.6

Steps to Reproduce:

1. Check out this project and build it (https://github.com/JerryCao1985/SORT)
2. Copy the attached resource file to bin folder and unzip it.
3. Setup VSCode on mac with LLDB
4. Run it by placing a point in pathtracing.cpp.
5. It will randomly give you an error 'vscode exception has occurred'. No further information in any other window 'Debug Console/Output'
[intermediate.zip](https://github.com/Microsoft/vscode/files/2308651/intermediate.zip)

Does this issue occur when all extensions are disabled?: Yes

**Comment by JerryCao1985** [comment]
<img width="2560" alt="screen shot 2018-08-22 at 10 42 33 am" src="https://user-images.githubusercontent.com/5715405/44439955-882e2c80-a5f8-11e8-9fb2-a3743a488542.png">
This is what I see and there is no disabling exception in my breakpoint section.

**Comment by isidorn** [comment]
Please file this against the cpp debug extension you are using

**Comment by JerryCao1985** [comment]
I'm using the official one provided by Microsoft.
https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools

According to its description, this is the place I should file this issue.

**Comment by isidorn** [comment]
Please file the issue here https://github.com/Microsoft/vscode-cpptools/issues

**Comment by JerryCao1985** [comment]
Thanks for the pointer, I apologize for the inconvenience caused.
