### ISSUE TITLE
PowerShell session has terminated

### ISSUE THREAD

**Issue by TrueKillRob** [Microsoft/vscode#56967]
Issue Type: <b>Bug</b>

Hello,

every time I copy something into one of the tabs via Copy Paste (Ctrl + v), the PowerShell session dies with the message: "The PowerShell session has ended due to an error, would you like to restart it?" Quelle: PowerShell (extension ) "

Kind regards
Robert

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3199)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (9.24GB free)|
|Process Argv|C:\Users\rob.ROB\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|40%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.2
gc-excelviewer|Gra|2.1.26
vscode-language-pack-de|MS-|1.26.3
PowerShell|ms-|1.8.3

</details>

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
