### ISSUE TITLE
In explorer too little contrast between titles and hover or selected

### ISSUE THREAD

**Issue by crystalfp** [Microsoft/vscode#56965]
Issue Type: <b>Feature Request</b>

I'm using the Dark+ dark theme, but this happens also with almost all dark themes.

In explorer there is too little difference between title bars (OPEN EDITORS, MYWORKSPACE, OUTLINE) background color and selected line background one. This makes difficult see the various sections of the window. Could the title bars made more contrasting, more different from the rest?

The Red theme does just the reverse (selected file visually popup more than the titles). The Tomorrow Night Blue is just a little better than the default one.

Now I will explore extension themes to see if they solved this problem better.

Thanks for considering!
mario

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

**Comment by crystalfp** [comment]
I should add that various dark theme extensions suffers the same problem. Seems like the styling of explorer is provided by the default dark theme and few themes care to override these factors. Is it true?

**Comment by crystalfp** [comment]
Just an example. In the marked area no difference is visible between title bar and active editor bar. Instead below the selected file is very visible. The theme is Dark (Visual Studio).

![capture](https://user-images.githubusercontent.com/865866/44448215-e9e79a00-a5ea-11e8-8841-09ef0f1a8574.PNG)

**Comment by isidorn** [comment]
This is provided by each team and is customizable. So please customize it in your settings and we have no plans to change this in the default theme currently
The colors which you want to edit are `list.inactiveFocusBackground` and other list customizable colors.

![screen shot 2018-08-23 at 10 44 33](https://user-images.githubusercontent.com/1926584/44514945-a1e77680-a6c1-11e8-9439-6e25b7d465fe.png)
