### ISSUE TITLE
Syntax highlight error (javascript)

### ISSUE THREAD

**Issue by vahpetr** [Microsoft/vscode#56975]
- VSCode Version: 1.26.0 4e9361845dc28659923a300945f84731393e210d x64
- OS Version:  macOS 10.13.6 (17G65)

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/10128393/44450748-1ad7c700-a60b-11e8-825c-20dc74f0fd06.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript-TmLanguage/issues/660 to track this upstream
