### ISSUE TITLE
Different colours for fields/variables on the same level. TypeScript 3.0.1 (and older), VS Code

### ISSUE THREAD

**Issue by dkoprowski** [Microsoft/vscode#56977]
- VSCode Version: 1.26.1
- OS Version: MacOS 10.13.4

Steps to Reproduce:

1. Use TypeScript file
2. Choose some theme which applies colour for object fields (e. g. Solarized Light, Kimbie Dark)
3. Create similar object to this one: 
```        
const obj = {
            attributes: 'val',
            categories: 'val',
            foo: 'val',
            history: 'val'
        };
```
4. Try to use those fields like `obj.attributes`.
5. See that `attributes` and `history` fields has different colour than other fields.
![image](https://user-images.githubusercontent.com/2902306/44451242-6ed6b180-a5f3-11e8-96a5-a23d3eaf1072.png)

Does this issue occur when all extensions are disabled?: **Yes**

_Additional info:_
I have strange issue with variables colouring. I don't understand if there is some dictionary which decides about colour of variable of what but sometimes I have multiple variables, same level and those are coloured different ways. It always take two colours. 

`obj` is just some object with  fields `foo, history, categories, attributes`. Fields `history, attributes` have different colour than `foo, categories`.

[Similar issue on StackOverflow](https://stackoverflow.com/questions/45369919/different-colors-for-same-variable-type-in-vs-code)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#657
