### ISSUE TITLE
Output Channel does not scroll down automatically

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/vscode#56974]
- VSCode Version: 1.26
- OS Version: Windows 10

Reported from Code Runner users: https://github.com/formulahendry/vscode-code-runner/issues/342 

In previous version of VS code, it works normally.

**Comment by isidorn** [comment]
Works fine for me in latest vscode insiders
Can you reproduce with insiders https://code.visualstudio.com/insiders/

If yes please create a minimal reproducable sample extension.

**Comment by CharlesFr** [comment]
Same issue here, the output window does not automatically scroll down

**Comment by formulahendry** [comment]
Install the [Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner) could easily repro.

In Command Palette, type `Run Code` to run any file.
If run put focus on Output Channel, the scroll down will stop, in previous version:
![56974-1](https://user-images.githubusercontent.com/1050213/44562068-5cdb4700-a78a-11e8-9f51-a59543b49fe4.gif)

Then in Command Palette, type `Stop Code Run`, then `Run Code` again, the scroll down also not work.
![56974-2](https://user-images.githubusercontent.com/1050213/44562162-e854d800-a78a-11e8-8c3c-abf35a1972d8.gif)

**Comment by sandy081** [comment]
This is because of the Smart scrolling behaviour - https://github.com/Microsoft/vscode/issues/49110

Last line is revealed if you focus on some text.

@isidorn FYI

**Comment by formulahendry** [comment]
I would argue that in some case, it would be a bug, or say it is not smart enough. User never have focus on the Output Channel, but the Output Channel is not scrolled. Previous `always scroll` would be better. Or there would be better to have a setting to config the behavior.
