### ISSUE TITLE
"Cannot connect to runtime process" in 1.27.0-insider

### ISSUE THREAD

**Issue by donaldpipowitch** [Microsoft/vscode#56972]
Since ~three days I can't attach my debugger to my Node process in the newest VS Code insiders edition.

- VSCode Version: 1.27.0-insider (1.26.1 works!)
- OS Version: Mac OSX 10.13.6

Steps to Reproduce:

1. `$ git clone https://github.com/donaldpipowitch/how-to-create-a-language-server-and-vscode-extension.git`
2. Open VS Code, Debug Panel and run task `Client + Server`.
3. Error: `Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:6009).`

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by donaldpipowitch** [comment]
> Does this issue occur when all extensions are disabled?: Yes/No

No.

I'm so sorry that I haven't tried that, because it seemed it appeared directly after an update. It looks like after removing all extensions it works again. Sorry :(

**Comment by donaldpipowitch** [comment]
Not yet, but I'll write a comment here, if I can figure it out.

**Comment by donaldpipowitch** [comment]
@weinand The behaviour doesn't seem to be flaky. Sometimes it works with all extensions. It looks to _always_ work without extensions. Are they always loaded in the same order...?

These are the extensions I currently use:

![image](https://user-images.githubusercontent.com/1152805/44506403-933f9600-a6a6-11e8-9c3e-84e92ddc5e41.png)

**Comment by weinand** [comment]
I suggest to use a bisect approach for figuring out which extension is the culprit.

**Comment by donaldpipowitch** [comment]
Hi @weinand ,

it seems like I have this error now no matter if I use Insiders or the normal build and no matter if I use extensions or not.

[My project](https://github.com/donaldpipowitch/how-to-create-a-language-server-and-vscode-extension/tree/74b850746d828d5c03ee43c520a3156d90e5d3d0). Using `"onLanguage:json"` (see [here](https://github.com/donaldpipowitch/how-to-create-a-language-server-and-vscode-extension/blob/74b850746d828d5c03ee43c520a3156d90e5d3d0/packages/client/package.json#L22)) and `"workspaceContains:**/.vscode/extensions.json"` seem to throw this error while `"onLanguage:plaintext"` works fine. Any ideas why?

**Comment by roblourens** [comment]
Are you sure the node process is starting in that case, ie your extension is being activated with that pattern?

**Comment by donaldpipowitch** [comment]
It doesn't look like it is starting correctly. Today it doesn't even work with `"onLanguage:plaintext"` anymore. Between yesterday and the original post 13 days ago I had this problem occasionally. I can't figure out a pattern behind this 😔

**Comment by roblourens** [comment]
So basically you open a plaintext file, but the extension doesn't activate?

**Comment by donaldpipowitch** [comment]
Hmm... I tried a couple more things.

First thing I learned: I needed `"onLanguage:jsonc"` and not `"onLanguage:json"`, because my JSON example included a comment. But that was not my only problem. It looks like the `Client + Server` task is the flaky part 🤔When I use `Launch Client` and `Attach Server` it seems to always work. (Does the 10000 ms timeout include the build time and startup time? Could it be that my build time just became too long? 🤔)

Now I just need to figure out why my `connection.onCompletion` callback isn't called for JSON files.

I _think_ this issue can be closed now, but I'm really interested why `Client + Server` became flaky after a while.

**Comment by roblourens** [comment]
> Does the 10000 ms timeout include the build time and startup time? Could it be that my build time just became too long?

The launch config that starts the task will not start counting until the task is done. But the attach config starts trying to attach immediately. So that isn't great, but you can work around it by setting `timeout` on the attach config to something larger.

**Comment by donaldpipowitch** [comment]
Thank you!
