### ISSUE TITLE
Energy impact too high in mac

### ISSUE THREAD

**Issue by SidharthRaveendran** [Microsoft/vscode#56976]
Issue Type: <b>Performance Issue</b>

I use webpack using terminal and also ssh. I also use chrome debugger extension

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:31:26.156Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   12	    66	 25575	code main
    1	    49	 25576	   gpu-process
    0	   262	 25577	   window (Running Extensions — Request (Workspace))
    0	     0	 25584	     /bin/bash -l
    0	     0	 25605	       node /usr/local/Cellar/yarn/1.9.4/libexec/bin/yarn.js start
    0	     0	 25620	         node /Users/sidharthraveendran/Documents/Sid/Clients/Digiworks/SABA/chatbot-request/node_modules/.bin/cross-env NODE_ENV=development node server
    0	   213	 25623	           node server
    0	    16	 25591	     searchService
    0	    82	 25592	     extensionHost
    0	     0	 25594	       searchService
    1	   492	 25596	       electron_node electronForkStart.js tsserver.js 
    0	     0	 25601	         electron_node typingsInstaller.js tsserver.js typesMap.js 
    0	     0	 25657	       electron_node jsonServerMain.js 
    0	     0	 27433	       electron_node htmlServerMain.js 
    0	     0	 25593	     watcherService
    0	     0	 27495	     /bin/bash -l
    0	    49	 32002	       /usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -S /Users/sidharthraveendran/Downloads/google-cloud-sdk/lib/gcloud.py compute --project saba-digiworks ssh --zone us-central1-f saba-react-dashboard-vm
    0	     0	 32014	         /usr/bin/ssh -t -i /Users/sidharthraveendran/.ssh/google_compute_engine -o CheckHostIP=no -o HostKeyAlias=compute.5760487887138033948 -o IdentitiesOnly=yes -o StrictHostKeyChecking=yes -o UserKnownHostsFile=/Users/sidharthraveendran/.ssh/google_compute_known_hosts sidharthraveendran@35.226.66.122
    0	   147	 28249	     electron_node stdForkStart.js chromeDebug.js 
    0	    33	 25590	   shared-process
    0	    98	 31544	   window (index.js — chatbot-dashboard)
    0	     0	 31545	     /bin/bash -l
    0	     0	 31591	       node /usr/local/Cellar/yarn/1.9.4/libexec/bin/yarn.js start
    0	     0	 31592	         node /Users/sidharthraveendran/Documents/Sid/Clients/Digiworks/SABA/chatbot-dashboard/node_modules/.bin/cross-env NODE_ENV=development node server
  136	    16	 31593	           node server
    0	     0	 31551	     searchService
    0	     0	 31552	     extensionHost
    0	     0	 31554	       searchService
    0	    16	 31556	       electron_node electronForkStart.js tsserver.js 
    0	     0	 31565	         electron_node typingsInstaller.js tsserver.js typesMap.js 
    0	     0	 31553	     watcherService
    4	    82	 32149	   window (Issue Reporter)
    1	     0	 32150	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.js — chatbot-dashboard)
|  Window (Running Extensions — Request (Workspace))
|    Folder (chatbot-dashboard): 401 files
|      File types: js(256) png(74) hbs(26) md(8) json(6) css(5) eps(4) pdf(4)
|                  svg(4) html(2)
|      Conf files: package.json(1)
|    Folder (chatbot-request): 552 files
|      File types: js(305) png(117) md(33) hbs(26) DS_Store(12) json(12)
|                  snap(7) mp3(5) eps(4) pdf(4)
|      Conf files: jsconfig.json(1) package.json(1) settings.json(1)
|                  launch.json(1)
|      Launch Configs: chrome;
```

</details>
<details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.14
phpunit|ema|2.1.1
prettier-vscode|esb|1.6.1
php-debug|fel|1.12.4
php-intellisense|fel|2.3.4
beautify|Hoo|1.3.2
phpcs|ika|1.0.5
node-module-intellisense|lei|1.5.0
php-namespace-resolver|Meh|1.1.0
vscode-language-babel|mgm|0.0.20
dotenv|mik|1.0.1
python|ms-|2018.7.1
Go|ms-|0.6.88
debugger-for-chrome|msj|4.8.2
vetur|oct|0.12.6
laravel-blade|one|1.18.0
laravel5-snippets|one|1.5.0
vscode-docker|Pet|0.1.0
react-beautify|tai|0.3.0
vscode-react-native|vsm|0.6.13

</details>

![screen shot 2018-08-22 at 1 30 43 pm](https://user-images.githubusercontent.com/7778385/44450875-b4a17300-a60f-11e8-89ba-30e7ac9e7516.png)

**Comment by Tyriar** [comment]
A lot of this is likely related to https://github.com/Microsoft/vscode/issues/56628 which will be fixed in 1.27
