### ISSUE TITLE
Possibility to scroll breadcrumbs hierarchy with mouse

### ISSUE THREAD

**Issue by Xarkam** [Microsoft/vscode#56979]
The actual breadcrumbs scroll bar is very tiny: (underlined in red)
![image](https://user-images.githubusercontent.com/331816/44451446-0fc56c80-a5f4-11e8-848e-f13d3681a204.png)

Make possibility to scroll breadcrumbs hierarchy with mouse :)

**Comment by jrieken** [comment]
Make sense - currently you need to scroll left/right but we could also support up/down scrolling

**Comment by jrieken** [comment]
Scrolling vertically and horizontally should now work
