### ISSUE TITLE
Terminal is unusably slow in 1.26.0 and 1.26.1 (--ignore-gpu-blacklist not help)

### ISSUE THREAD

**Issue by fessmage** [Microsoft/vscode#56970]
Issue Type: <b>Performance Issue</b>

After update vscode to 1.26.1 from 1.25.1 i experienced problem with unusably slow rendering. Switching renderertype from 'canvas' to 'dom' doesn't help me, neither --ignore-gpu-blacklist option. 

I checked problem and seen it in 1.26.0 too.

I am reverted vscode version from 1.26.1 to 1.25.1 because of it, in 1.25.1 terminal with renderertype 'canvas' works fast again. I stay with this version until some fix.

This problem looks like that comment -
 https://github.com/Microsoft/vscode/issues/56517#issuecomment-413555916, but i starting new issue because ignoring gpu blacklist doesn't help me, only old version.

My hardware - Core i5-2400, 16 GB RAM, no videocard (using integrated Intel), OS - Ubuntu 18.04.1 x64. VS Code installed from snap.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:34:20.517Z)
OS version: Linux x64 4.15.0-32-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 x 1941)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.40GB (5.23GB free)|
|Process Argv|/snap/vscode/51/usr/share/code/code|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   205	 15164	code main
    0	    32	 15166	   zygote
    0	    95	 15296	     shared-process
    0	   221	 15393	     window (Dockerfile - kali - Visual Studio Code)
    0	     0	 15414	       /bin/bash
    0	    47	 15423	       searchService
    0	    63	 15432	       extensionHost
    0	    63	 15437	       watcherService
    1	    95	 15489	     window (Issue Reporter)
    0	     0	 15518	   /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 15519	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Dockerfile - kali - Visual Studio Code)
|    Folder (kali): 1 files
|      File types:
|      Conf files:;
```

</details>
Extensions: none

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/56628, let me know if the [Insiders](https://code.visualstudio.com/insiders/) build doesn't fix the problem
