### ISSUE TITLE
Graphics card joke?

### ISSUE THREAD

**Issue by pcarrier** [Microsoft/vscode#5697]
> Note: Your graphics card provider might overwrite these default shortcuts.

— https://code.visualstudio.com/docs/editor/editingevolved

**Comment by dbaeumer** [comment]
@gregvanl can you please follow up.

**Comment by Tyriar** [comment]
I think Nvidia drivers conflict with certain combinations of <kbd>ctrl</kbd>, <kbd>alt</kbd>, <kbd>shift</kbd> and arrows. That's probably what it's referring to.

**Comment by pcarrier** [comment]
I do not want this to be taken the wrong way.

If it's an nvidia-only, Windows-only edge case, maybe a mention of that combo and/or a link to some specific issue would be more useful?

It made very little sense the way it was presented to me:

![image](https://cloud.githubusercontent.com/assets/8641/14763777/b6e41702-0955-11e6-822f-56b0d550e3cd.png)

**Comment by gregvanl** [comment]
Added NVIDIA mention with https://github.com/Microsoft/vscode-docs/commit/3365a30bc80ba074beb1bca42c103079b6aa64dd
