### ISSUE TITLE
segmentation fault on my fedora 28

### ISSUE THREAD

**Issue by bh1svr** [Microsoft/vscode#56980]
Both newest stable and insider version will cause Segmentation fault on my PC.
I installed x64 rpm package.
Error message is:
/usr/bin/code: 行 35: 17805 Segmentation fault      (核心已转储)ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"
My OS is Fedora release 28 (Twenty Eight)

**Comment by bpasero** [comment]
@bh1svr can you try this build that is using a newer Electron version: https://az764295.vo.msecnd.net/exploration/a5cda44f872b9b55122a108b99a170e1ed5fa66e/code-exploration-1.27.0-1534919256.el7.x86_64.rpm

**Comment by bh1svr** [comment]
It works. Thanks.
