### ISSUE TITLE
Calling WorkspaceEdit.createFile(uri, { ignoreIfExists: true }) twice discards future edits

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#56986]
`WorkspaceEdit`'s `create` function has an `ignoreIfExists` option for convenience to avoid us having to check if files exist. However, if you call it more than once, the edits made after the second call are discarded.

The following code:

```ts
changes.createFile(uri, { ignoreIfExists: true });
changes.replace(uri, new vs.Range(new vs.Position(0, 0), new vs.Position(0, 0)), "ONE");
changes.replace(uri, new vs.Range(new vs.Position(0, 0), new vs.Position(0, 0)), "TWO");
changes.createFile(uri, { ignoreIfExists: true });
changes.replace(uri, new vs.Range(new vs.Position(0, 0), new vs.Position(0, 0)), "THREE");
changes.replace(uri, new vs.Range(new vs.Position(0, 0), new vs.Position(0, 0)), "FOUR");
```

Results on `ONETWO` being inserted at the start of the document. The code executes without error (it hits the last line), the edits are just discarded.

This means we have to keep track of whether we've called it before when looping through edits from our language server - I don't think this is intended (it would be slightly more understandable if the first edits were lost, since the create call maybe was resetting the file, but this is very confusing).

**Comment by jrieken** [comment]
@DanTup For me the document shows `THREEFOURONETWO`

**Comment by DanTup** [comment]
Ugh, wha? :(

Here's my full code (I'm calling this from a command from the palette):

```ts
private async organizeImports(document: vs.TextDocument): Promise<void> {
	document = document || this.getActiveDoc();
	const uri = document.uri;
	const changes = new vs.WorkspaceEdit();
	changes.createFile(uri, { ignoreIfExists: true });
	changes.replace(uri, new vs.Range(new vs.Position(0, 0), new vs.Position(0, 0)), "ONE");
	changes.replace(uri, new vs.Range(new vs.Position(0, 0), new vs.Position(0, 0)), "TWO");
	changes.createFile(uri, { ignoreIfExists: true });
	changes.replace(uri, new vs.Range(new vs.Position(0, 0), new vs.Position(0, 0)), "THREE");
	changes.replace(uri, new vs.Range(new vs.Position(0, 0), new vs.Position(0, 0)), "FOUR");
	await vs.workspace.applyEdit(changes);
}
```

Here's what my doc looks like afterwards:

![screen shot 2018-08-22 at 12 00 30 pm](https://user-images.githubusercontent.com/1078012/44459863-fbd53700-a602-11e8-988b-c7dd7be2d1c5.png)

**Comment by DanTup** [comment]
Seeing same behaviour in latest Insiders too. Is your code any different to mine?

**Comment by DanTup** [comment]
Oh also:

> For me the document shows THREEFOURONETWO

That does not seem right - it should be ONETWOTHREEFOUR, right? The edit is atomic and the positions were all the same? Maybe you had two separate edits somehow?

**Comment by jrieken** [comment]
Below is my snippet. It matters if the file already exists the very first time or not. Also, there is an error being printed. @DanTup don't you see that error?

```
ERR Error: file:///Users/jrieken/Code/_samples/ConsoleAppDnx/test.fsx.txt has changed in the meantime
    at BulkEdit.<anonymous> (bulkEditService.js:409)
    at step (bulkEditService.js:50)
    at Object.next (bulkEditService.js:31)
    at fulfilled (bulkEditService.js:22)
    at <anonymous>
```

```ts
 let { document } = vscode.window.activeTextEditor;

        let edit = new vscode.WorkspaceEdit();
        let uri = document.uri.with({ path: document.uri.path + '.txt' });
        // let uri = document.uri;

        edit.createFile(uri, { ignoreIfExists: true });
        edit.replace(uri, new vscode.Range(new vscode.Position(0, 0), new vscode.Position(0, 0)), "ONE");
        edit.replace(uri, new vscode.Range(new vscode.Position(0, 0), new vscode.Position(0, 0)), "TWO");
        edit.createFile(uri, { ignoreIfExists: true });
        edit.replace(uri, new vscode.Range(new vscode.Position(0, 0), new vscode.Position(0, 0)), "THREE");
        edit.replace(uri, new vscode.Range(new vscode.Position(0, 0), new vscode.Position(0, 0)), "FOUR");

        vscode.workspace.applyEdit(edit);
```

**Comment by DanTup** [comment]
You're right, the behaviour differs if the file exists or not - but I think both are broken:

1. If the file already exists, the 3rd/4th edit are ignored - we're passing `ignoreIfExists` which suggests the `create` should be a no-op, so it doesn't seem right that edits are discarded
2. If the file does not exist, the file ends up saying `THREEFOURONETWO` but `ONETWOTHREEFOUR` is expected

I do not see the error you get, however if I try to close the unsaved file with the dev tools open, it does seem to pause on a rejected promise (though doesn't write to the console). I think that maybe normal (the ext. dev host doesn't show the save prompt).

**Comment by jrieken** [comment]
What are your save settings? Auto save, save on focus out?

**Comment by DanTup** [comment]
Just all defaults in dev host (no auto saving).

Weirdly, I *am* now seeing "Error: file:///Users/dantup/Desktop/Dart%20Sample/test/main.dart has changed in the meantime" when this code runs. I tried several times earlier and didn't see it :-/ Probably that's related to the issue then.

As for the other thing (breaking on promise reject when closing the window), that seems unrelated to the creation of the file since it happens even when modifying any file in the dev host and hitting Ctrl+W to close it. It may be normal, I guess rejected promises are treated like unhandled exceptions and break by default.

Looks like this (if you think it is an issue, I can open a new issue for it to avoid confusing this one):

![screen shot 2018-08-22 at 3 18 47 pm](https://user-images.githubusercontent.com/1078012/44469127-b1fa4a00-a61e-11e8-81d3-25fa040f87d1.png)

**Comment by DanTup** [comment]
@jrieken based on the https://github.com/Microsoft/vscode/issues/56986#issuecomment-415008802 it seems like this API doe the wrong thing whether the file exists or not. If there's no plan to fix it, should the docs at least be updated to mention this?

**Comment by taoqf** [comment]
`deleteFile` has the same behavior even if set `ignoreIfNotExists` to `true`, 
`createFile` use `overwrite` does the same. 
I am using vscode 1.39.1
