### ISSUE TITLE
integrated terminal - powershell command colors with light theme

### ISSUE THREAD

**Issue by jeffrson** [Microsoft/vscode#56985]
The default input color (of type command) in PowerShell is yellow. Obviously this is unreadable inside the integrated terminal when using a light theme.

The color may be changed by

`Set-PSReadlineOption -TokenKind Command -ForegroundColor Black`

however, this does not yield the expected result: Commands seem to be "hidden" (invisible, indeed). Instead, with

`Set-PSReadlineOption -TokenKind Command -ForegroundColor White`

the typed command is shown as (somewhat bold!) black.

So it seems white and black are (kind of) reversed.

While blue and green are not correct as well (in some themes), this may depend on the actual theme. However, black and white are wrong in lots of light themes, so I would assume it's a bug. Sorry if I'm wrong...

**Comment by Tyriar** [comment]
I think this is as designed as AFAIK it's the default for powershell (was it not designed to ever show on a light terminal?) and themes are meant to provide enough contrast to make out yellow on white.

/cc @tylerl0706

**Comment by tylerl0706** [comment]
Here's the issue you're looking for:

https://github.com/lzybkr/PSReadLine/issues/464

**Comment by jeffrson** [comment]
The real problem for me wasn't the yellow characters, but instead that White is bold black, and Black is invisible. But DarkGray is dark gray (what I'm using now).

Nevertheless, that PSReadline related discussion is interesting - for some reason I had only looked for issues in PowerShell archives.
