### ISSUE TITLE
Can't open file on a network folder while debugging

### ISSUE THREAD

**Issue by arnakazim** [Microsoft/vscode#56987]
VSCode version : 1.26.1
OS : Windows 8.1

My PHP project is on a network folder (//srv-fic01/utilisateurs/ArnaudO/Development/nutri-uk/). I opened it with this path (not a mapped folder).

I have setup breakpoints for debugging in a file. I launch debugging of the project with xdebug and the PHP Debug extension and execute the script in my browser.

The execution of the scripts stops at the first breakpoint (shown in the call stack of the debugging tool) but VSCode can't open the file to highlight where it has stopped and an error message is shown stating that it is unable to open the file.

The error message is showing that it is trying to open the file "file:///UTILISATEURS/ArnaudO/Development/nutri-uk/src/public/test.php" instead of the file "file:///**srv-fic01**/UTILISATEURS/ArnaudO/Development/nutri-uk/src/public/test.php" and it is where lies the issue.

![image](https://user-images.githubusercontent.com/18421982/44455823-4ce32c00-a5ff-11e8-8605-dea865ba5791.png)

**Comment by isidorn** [comment]
Thanks, but this issue comes from the php debug extension, please file it there. It should tell vscode to open the correct file in this case.

**Comment by arnakazim** [comment]
Okay thanks, I wasn't sure. I have posted the issue in the PHP Debug repository : https://github.com/felixfbecker/vscode-php-debug/issues/298

**Comment by isidorn** [comment]
I am not sure, but start with the extension and once they investigate they can come back to us
