### ISSUE TITLE
Broken diff editor layout

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#56981]
* have a diff
* reload vscode (have all editors closed)
* go to the SCM viewlet and click a modified file
Observe the diff editor has a broken layout (look to the right overview ruler)

![image](https://user-images.githubusercontent.com/5047891/44451894-4d76c500-a5f5-11e8-8af9-1429ecef6764.png)

**Comment by alexandrudima** [comment]
@rebornix I can only reproduce this when having the PR extension installed & enabled. If I disable the PR extension, then I can no longer reproduce. It might be related to the commenting support. Can you please take a look?

**Comment by rebornix** [comment]
The gutter width was adjusted when we have comments available and somehow the overview width was affected by this. I'm looking into it now.

**Comment by rebornix** [comment]
The width of the modified editor was not kept when we adjust the lineDecoration width.
