### ISSUE TITLE
Tons of debug spew in cmd window

### ISSUE THREAD

**Issue by Piscean** [Microsoft/vscode#5698]
- VSCode Version: 1.0.0
- OS Version: Windows 1511 (10586.104) But happens on Win7 as well

Steps to Reproduce:
1. Set VS Code to be the default app for opening .log files.  (Or any file, really)
2.  Open a cmd window
3.  Navigate to a directory with .log files.
4.  Type Logfile.log  (Or whatever the name of your log file is) And press Enter
5.  VS Code will launch and open the log file
6.  If you switch back to the cmd window, you'll see tons of debug spew being dumped into that window.  

Need a way to turn that off.

**Comment by bpasero** [comment]
Make sure you put C:\Program Files\Code\bin\code.cmd on the path and not the exe.

**Comment by Piscean** [comment]
Checked my path.  Last entry is "C:\Program Files\Microsoft VS Code\bin".  The only contents of that directory are code and code.cmd.

I suspect the problem comes from step 1 of my repro.  When you chose a default app, you're picking the exe, not a .cmd.  So by opening a .log file from the cmd window, the system is directly launching code.exe, not code.cmd from the path.

**Comment by bpasero** [comment]
@joaomoreno seems related to https://github.com/Microsoft/vscode/issues/4808

**Comment by joaomoreno** [comment]
@Piscean exactly right. We don't have a clear answer for this.

**Comment by joaomoreno** [comment]
Seems fixed.
