### ISSUE TITLE
Quick open position is off with custom menus and full screen

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#56990]
On Linux:

1. Enable custom menus
2. Go full screen
3. Open quick open

![screenshot from 2018-08-22 11-59-28](https://user-images.githubusercontent.com/22350/44457248-04c60880-a603-11e8-827f-533a943949d5.png)

**Comment by bpasero** [comment]
I can reproduce in insiders (was checking if this could be Electron 3.0.x related).
