### ISSUE TITLE
command 'easyLess.compile' not found

### ISSUE THREAD

**Issue by TheZoker** [Microsoft/vscode#56997]
I use [Easy Less](https://github.com/mrcrowl/vscode-easy-less) to autocompile less to css. 

When I try to compile LESS/Sass to CSS I get the following error:
`command 'easyLess.compile' not found`

The plugin is installed correctly and uninstalling and reinstalling them did not help. It worked well for the past couple of month

- VSCode Version: 1.27.0-insider
- OS Version: Windows 10 1803

Steps to Reproduce:

1. Install Easy LESS
2. Open command pallet
3. Type "Compile LESS to CSS"

First I thought this is a error with Easy LESS, but after installing [Live Sass Compiler](https://github.com/ritwickdey/vscode-live-sass-compiler) I had the same error there:
`command 'liveSass.command.watchMySass' not found `

**Comment by rebornix** [comment]
Please file issues with the extension you are using, this command is contributed by extensions but not core.

**Comment by TheZoker** [comment]
I disagree here, because without any update of the extension, but with an update of vs code the extension do not work anymore. They worked until like some updates ago. And now they don't.
This is bad, because when the developer does not update his extension frequently, it does not work with vs code anymore...

**Comment by SchoofsKelvin** [comment]
I hear from users of my extension that it happens sometimes, but isn't very reproducable: SchoofsKelvin/vscode-sshfs#1, SchoofsKelvin/vscode-sshfs#37

The commands are properly registered in `activationEvents` and in the activate method, which works most of the time. But it still rarely seems to fail, with me having no idea what's causing it.
