### ISSUE TITLE
Integrated terminal: powershell doesn't accept "-Command" parameter

### ISSUE THREAD

**Issue by jeffrson** [Microsoft/vscode#56991]
When I execute
`powershell -NoLogo -NoExit -Command "& { Write-Host }"`

from cmd.exe it works without error. However, when I put this
`"terminal.integrated.shellArgs.windows": ["-NoLogo", "-NoExit", "-Command \"& { Write-Host }\""]`

into my user settings, there's an error in the new terminal window:

> -Command : The term '-Command' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> At line:1 char:1
> \+ -Command "& { Write-Host }"

**Comment by Tyriar** [comment]
Does this work?

```
"terminal.integrated.shellArgs.windows": ["-NoLogo", "-NoExit", "-Command", "& { Write-Host }"]
```

**Comment by tylerl0706** [comment]
Yeah I would give the same advice 👍

**Comment by jeffrson** [comment]
Well - I would have sworn, I tried that. No - I'm sure I did! :-)

Then there must have been another error, because now it works.

Thanks - and sorry.
