### ISSUE TITLE
Getting a lightbulb in status for jsconfig.json but I have one in project root

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/vscode#5699]
"InfoCreate a jsconfig.json to enable richer IntelliSense and code navigation across the entire workspace."

https://github.com/opendirective/brian

**Comment by jrieken** [comment]
The problem is that TypeScript doesn't give us a value for the project name anymore. That's why we think your file is part of the _virtual_ project which makes us suggest this...

**Comment by jrieken** [comment]
@SteveALee To workaround this, remove `allowJS: true` setting from the jsconfig.json file.

**Comment by jrieken** [comment]
projectInfo data **without** `allowJS`

```
Sending request: projectInfo (6). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/jrieken/Code/_samples/brian/client/src/js/pathUtils.js",
    "needFileNameList": true
}

Response received: projectInfo (6). Request took 1 ms. Success: true 
Result: {
    "configFileName": "/Users/jrieken/Code/_samples/brian/jsconfig.json",
    "fileNames": [
        "/Users/jrieken/Code/vscode/extensions/typescript/server/typescript/lib/lib.es6.d.ts",
        "/Users/jrieken/Code/_samples/brian/client/src/js/pathUtils.js",
        "/Users/jrieken/Code/_samples/brian/client/webpack.config.js",
        "/Users/jrieken/Code/_samples/brian/client/src/js/globalError.js",
        "/Users/jrieken/Code/_samples/brian/client/src/js/drivers/speech.js",
        "/Users/jrieken/Code/_samples/brian/client/src/js/drivers/fullScreen.js",
        "/Users/jrieken/Code/_samples/brian/client/src/js/drivers/localStorage.js",
        "/Users/jrieken/Code/_samples/brian/client/src/js/runHot.js",
        "/Users/jrieken/Code/_samples/brian/client/src/js/components/view.js",
        "/Users/jrieken/Code/_samples/brian/client/src/js/components/viewAssistant.js",
        "/Users/jrieken/Code/_samples/brian/client/src/js/components/App.js",
        "/Users/jrieken/Code/_samples/brian/client/src/js/main.js",
        "/Users/jrieken/Code/_samples/brian/client/src/js/components/Card.js",
        "/Users/jrieken/Code/_samples/brian/client/src/js/config/defaultConfig.js",
        "/Users/jrieken/Code/_samples/brian/client/src/js/config/defaultSettings.js",
        "/Users/jrieken/Code/_samples/brian/server/handlers/pages.js",
        "/Users/jrieken/Code/_samples/brian/server/handlers/assets.js",
        "/Users/jrieken/Code/_samples/brian/server/routes.js",
        "/Users/jrieken/Code/_samples/brian/server/server.js"
    ]
}
```

and with (requires tsserver restart)
```
Sending request: projectInfo (1). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/jrieken/Code/_samples/brian/client/src/js/pathUtils.js",
    "needFileNameList": true
}

Response received: projectInfo (1). Request took 4 ms. Success: true 
Result: {
    "fileNames": [
        "/Users/jrieken/Code/vscode/extensions/typescript/server/typescript/lib/lib.d.ts",
        "/Users/jrieken/Code/_samples/brian/client/src/js/pathUtils.js"
    ]
}

```

**Comment by jrieken** [comment]
@aeschli Can we make an error/warning appear in jsconfig.json files that have that specific setting set?

**Comment by SteveALee** [comment]
Thanks. I don't fully understand the explanation but will try the workaround . This is a JS project though so turning off the option seems strange. I only use to for typings.

**Comment by jrieken** [comment]
I know sounds weird. I know the `allowJS` flag introduced for **ts**config.json files to allow JavaScript and the **js**config.json files should have that set implicit by  their name. Tho I don't understand why it breaks the project info

**Comment by SteveALee** [comment]
@jrieken  Thanks! I confirm that fixed it for me - though had to restart code (reasonable).
I've left this open as there is an open Q above for @aeschli

**Comment by aeschli** [comment]
@jrieken You could modify the schema so that true is not a valid option. I could also add support so a specific error message is shown.

**Comment by jrieken** [comment]
Also, I will add a check if there already is `jsconfig` before hinting

**Comment by SteveALee** [comment]
belt and braces! :)

Steve Lee
OpenDirective http://opendirective.com

**Comment by jrieken** [comment]
@aeschli Is there also a way to warn about properties that aren't defined in the schema? The underlying issue is that `allowJS` vs `allowJs` ([casing](https://github.com/Microsoft/TypeScript/issues/8279#issuecomment-214464529)).

**Comment by egamma** [comment]
There was a typo in the doc and in one place we use `AllowJS` which I have fixed.

**Comment by SteveALee** [comment]
Trust me to pick the incorrect 'allowJS'. I make a great Gorilla tester :)

So can you confirm if we should or should not use allowJs for Javascript projects?

**Comment by jrieken** [comment]
Only use it if the project file is `tsconfig.json` and you want to mix TypeScript and JavaScript development - like when migrating your project form JS to TS.

**Comment by SteveALee** [comment]
Thanks!
