### ISSUE TITLE
.config/Code/User/workspaceStorage taking up a lot of space

### ISSUE THREAD

**Issue by trillykins** [Microsoft/vscode#56993]
🚨 The issue tracker is not for questions 🚨

I have Visual Studio Code on Ubuntu 14.04 and have noticed that it is taking up an awful lot of storage in the .config folder.

Is this intended behaviour? How should I clean the folder? 

Attach screen dump.
![image](https://user-images.githubusercontent.com/2485138/44458386-57ed8a80-a606-11e8-892e-cc5f03a10843.png)

**Comment by dbaeumer** [comment]
@trillykins what kind of development do you usually do. C++ ?

**Comment by trillykins** [comment]
@dbaeumer I've only used C with this Code installation.

**Comment by dbaeumer** [comment]
@trillykins in this case you can delete the content to clean it up. The extension will recompute if necessary. For the more general clean-up this is a dup of https://github.com/Microsoft/vscode/issues/32461

Closing as duplicate
