### ISSUE TITLE
Preserve window position when open - in dual monitor setup

### ISSUE THREAD

**Issue by dgiridharan** [Microsoft/vscode#56999]
Platform: MacOS

When I open Visual Studio code on a dual monitor setup, it always opens on the primary window. If I move the editor to the secondary window and close it, I expect it to open in the last known location, when would be the secondary monitor.

However, it always opens in the primary monitor and it doesn't remember the position before it was closed.

This also happens on a single monitor setup as it always opens to the center of the screen. But this is much less of an issue when there is only one monitor.

It would be great to have VS code remember the last know location and restore itself there.

**Comment by bpasero** [comment]
@dgiridharan VSCode will always reopen on the monitor where you left it running, so something must be broken on your setup. Is the window maximized? Does it reproduce with opening just one window, moving it to the secondary monitor and then closing and reopening it?

**Comment by dgiridharan** [comment]
@bpasero - Sorry for the late reply. You're absolutely right. I always move my instance of vs code from one screen to another in full screen. If I were to move it without having it on full screen this works.

I'll close this bug. Thanks again for the really fast reply.
