### ISSUE TITLE
Extensions use incorrect locale (at least for date formatting)

### ISSUE THREAD

**Issue by PikeUK** [microsoft/vscode#56995]
Issue Type: <b>Bug</b>

I'm using Windows 10 Pro, set to en-GB.

Extensions aren't using the OS locale for date formatting. I first noticed this in the Hg extension's show history command but it's not specific to that extension.

STR:
1. Create a _New Extension (Javascript)_ with Yeoman (_npm install -g yo generator-code_ then _yo code_).
2. In the _activate_ function in extension.js, change _"Hello World!"_ to _new Date().toLocaleDateString()_
3. Press F5 to debug the extension then run the Hello World command.

Expected:
A notification should appear displaying the current date in the OS locale format.

Actual:
A notification appears displaying the current date in en-US format.

If you run _new Date().toLocaleDateString()_ in the Developer Tools console it correctly displays using the OS locale format. I've attached a screenshot showing my OS settings, the incorrect notification date, and the correct Developer Tools console date:

![tolocaledatestring](https://user-images.githubusercontent.com/15807255/44457664-bd884980-a5fb-11e8-8a1a-cf33cfeeeb03.PNG)

This could be related to or a duplicate of issue #16261 but that seems to be OSX specific.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz (4 x 3293)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|2.91GB (0.70GB free)|
|Process Argv|C:\Users\\\<username>\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.14
hg|mrc|1.2.3
vscode-apache|mrm|1.1.1
code-settings-sync|Sha|3.0.0

</details>

**Comment by ramya-rao-a** [comment]
@PikeUK Can you try running a simple minimal electron app and see what you get there when you use `new Date().toLocaleDateString()`?

See https://github.com/electron/electron-quick-start.

Since VS Code is based on electron, I want to rule out any upstream issues first

**Comment by PikeUK** [comment]
I can confirm that `new Date().toLocaleDateString()` uses the correct locale format in electron:

![image](https://user-images.githubusercontent.com/15807255/45409568-72e07700-b667-11e8-9548-ed8439a45bdb.png)

**Comment by sandy081** [comment]
This is nothing to do with extension management... Starting with @alexandrudima to see if it is related to extension host some how

**Comment by alexandrudima** [comment]
This does not work for me in Electron.

![image](https://user-images.githubusercontent.com/5047891/48651531-8f988280-e9fb-11e8-8ccd-cd43a05a48e0.png)

**Comment by ChrisMaunder** [comment]
> Thanks for your understanding

Not understanding at all, to be honest. We have a fundamental issue with dates which may not seem. big deal for a team that uses the format that only the US uses, but for the rest of the world with teams from multiple regions, date format matters. Especially when the default is the worst possible format: x/y/z.

I'm sorry your inbox is a little full. VSCode is an amazing, incredible gift to the world. But this bug seems fundamental and at the same time fairly straightforward to fix.Please don't brush this one under the carpet with a "thanks for understanding".

**Comment by Lachann** [comment]
This is 7 years old! How is this not fixed yet?!
