### ISSUE TITLE
Debug: no longer possible to debug a unit test in VSCode

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#56992]
- VSCode Version: 1.27-insiders
- OS Version: macOS

Steps to Reproduce:

1. add a breakpoint into a vscode unit test
2. run tests

=> breakpoint is not hit

**Comment by isidorn** [comment]
Works for me following exact steps by @bpasero 
1. Add "-g", "34210" to the args in `Unit Test` vscode configuration
2. Put breakpoint [here](https://github.com/Microsoft/vscode/blob/dc0932002fa1228ccc31db6083a22da28deb6820/src/vs/base/parts/quickopen/test/common/quickOpenScorer.test.ts#L590)

For me the breakpoint gets hit
@weinand can you also please try?

![screen shot 2018-08-22 at 12 28 37](https://user-images.githubusercontent.com/1926584/44458673-3d67e100-a607-11e8-9887-55249a30b729.png)

**Comment by bpasero** [comment]
I tried in a couple of places and it did not work.

**Comment by bpasero** [comment]
It seems unrelated to the recent refactorings from Isidor, I can also not hit that breakpoint with 1.26 stable. Weird.

**Comment by MicrosoftEurope** [comment]
:)

**Comment by bpasero** [comment]
@roblourens here you go:
[debugadapter.txt](https://github.com/Microsoft/vscode/files/2312957/debugadapter.txt)

**Comment by roblourens** [comment]
`SourceMaps: no sourcemap url found in generated script: /Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/quickopen/test/common/quickOpenScorer.test.js`

Did you do something weird? Does that file have a sourcemap footer at the bottom? The last line should be

`//# sourceMappingURL=quickOpenScorer.test.js.map`

**Comment by bpasero** [comment]
@roblourens good catch, I do not see that entry. I suggest you do a `git clean -xfd` followed by `yarn` to reproduce (also @isidorn). 

Maybe a consequence of @jrieken changes for webpack? Not sure...

**Comment by jrieken** [comment]
> Maybe a consequence of @jrieken changes for webpack? Not sure...

Unlikely, only emmet and git are webpack'ed

**Comment by isidorn** [comment]
@bpasero if I do a `git clean -fxd` I can still not reproduce this - breakpoints get hit properly.

**Comment by isidorn** [comment]
@bpasero at the end of quickOpenScorer.test.js I see the following
`//# sourceMappingURL=quickOpenScorer.test.js.map`

**Comment by bpasero** [comment]
@isidorn weird. I am no node `8.9.3` and yarn `1.9.3`, not sure that makes any difference.

**Comment by isidorn** [comment]
I am on node `8.9.1` and yarn `1.7.0`

**Comment by weinand** [comment]
Works fine for me too.
I'm using node v8.9.4 and yarn 1.9.4

**Comment by bpasero** [comment]
Sorry guys, I had `VSCODE_NO_SOURCEMAP` set in my bash profile.
