### ISSUE TITLE
Unable to spawn Code via child_process.exec

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#570]
_From @alefragnani on November 12, 2015 15:44_

When I try to spawn another **Code** instance using `child_process.exec`, nothing happens (neither an error). 

```
    exec('start \"open ui\" "C:\\Program Files\\Microsoft VS Code\\Code.exe" "C:\\Program Files\\Winmerge\\Files.txt"').
```

Original from issue #84 

_Copied from original issue: Microsoft/vscode-extensionbuilders#101_

**Comment by seanmcbreen** [comment]
_From @Tyriar on November 13, 2015 6:38_

I was looking into the same thing you were and I think this is the case because you cannot currently have more than 1 instance of Code open at once. At least on Windows 10, shift+clicking on the app icon or running `code` again in command prompt doesn't do anything.

**Comment by seanmcbreen** [comment]
_From @bpasero on November 13, 2015 7:53_

No thats ok, we detect this case with a socket and communicate to the first instance.

**Comment by seanmcbreen** [comment]
_From @alefragnani on November 13, 2015 9:38_

@Tyriar in fact you can, but you have to pass a new _folder / file_ via parameter, while running in **Command Prompt**.

* Running `Code "a_folder"` will open **Code** with **a_folder** 
* Running `Code` _(with no parameter)_ will reactivate the last focused/active **Code** instance 
* Running `Code .` _(with a dot)_ will open **Code** on the current folder.

This issue is while running **Code** via `child_process.exec`, inside a **Code** extension.

**Comment by seanmcbreen** [comment]
_From @mikiest on November 13, 2015 9:43_

As mentioned earlier, I think a **supported way** to open a new instance and/or in the same window, with a folder/file target would be better instead of having to use `child_process.exec`.

Maybe something like `vscode.open(path:string, newWindow:boolean))`?

I confirm I can reproduce the initial issue on my Windows 10, by the way.

**Comment by bpasero** [comment]
We will work on providing a way to open a folder from an extension. Closing.
