### ISSUE TITLE
Can't remove space between editor pallete and explorer

### ISSUE THREAD

**Issue by r8d8** [Microsoft/vscode#57003]
- VSCode Version: 1.26.1
- OS Version: Archlinux (kernel 4.17) + AwesomeWM tilling window manager

Steps to Reproduce:

1. Open VsCode
2. Enter "Zen mode" (Ctrl+k Z)
2. Maximize width of editor palete (see picture)

Does this issue occur when all extensions are disabled?: Yes
![2018-08-22-155628_1600x900_scrot](https://user-images.githubusercontent.com/8018746/44465479-63e94480-a626-11e8-8d92-cb963b096191.png)

**Comment by isidorn** [comment]
Put this in your settings
```
"zenMode.centerLayout": false
```

And also F1 > toggle centered layout
