### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#57007]
1. Start debugging
2. Have the loaded scripts view open
3. Stop debugging, notice exception in the console
4. I can not reproduce with Stable so it might be that my listener refactoring caused this

If you pause on exception you will see that [this call](https://github.com/Microsoft/vscode/blob/13414612090c61a6f31cb8504a969e3c405568c3/src/vs/workbench/parts/debug/browser/loadedScriptsView.ts#L392) caused it.

```
  ERR Cannot convert undefined or null to object: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at file:///Users/isidor/Development/vscode/out/vs/base/parts/tree/browser/treeView.js:606:35
    at file:///Users/isidor/Development/vscode/out/vs/base/common/async.js:272:28
    at Object.notifySuccess [as _notify] (file:///Users/isidor/Development/vscode/out/vs/base/common/winjs.base.js:1191:59)
    at Object.enter (file:///Users/isidor/Development/vscode/out/vs/base/common/winjs.base.js:867:30)
    at Promise_ctor._run (file:///Users/isidor/Development/vscode/out/vs/base/common/winjs.base.js:1089:29)
    at Promise_ctor._completed (file:///Users/isidor/Development/vscode/out/vs/base/common/winjs.base.js:1057:18)
    at file:///Users/isidor/Development/vscode/out/vs/base/common/async.js:277:23
errors.js:42 WARNING: Promise with no error callback:24
errors.js:43 {exception: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at file…, error: null, promise: _…e.C…s.d…e._creator, handler: undefined, id: 24, …}
errors.js:45 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at treeView.js:606
    at async.js:272
    at Object.notifySuccess [as _notify] (winjs.base.js:1191)
    at Object.enter (winjs.base.js:867)
    at Promise_ctor._run (winjs.base.js:1089)
    at Promise_ctor._completed (winjs.base.js:1057)
    at async.js:277
```

**Comment by isidorn** [comment]
@weinand did you have a chance to look into this? Or would you like me to investigate?
I suspect this is breaking the loaded scripts view and is the root cause for https://github.com/Microsoft/vscode/issues/57401

**Comment by weinand** [comment]
no, please investigate since this and #57401 was working before, and I haven't touched this code for two weeks.

**Comment by weinand** [comment]
@isidorn end session events are not arriving in  https://github.com/Microsoft/vscode/blob/93e30cc319bb2184756819aefbd4f16a27e7a17c/src/vs/workbench/parts/debug/browser/loadedScriptsView.ts#L388

As a consequence the tree for the session is not properly removed.

**Comment by isidorn** [comment]
I see something differnetly, the end sessions are arriving however when the last session end arrives view starts refreshing the tree and while that is in progress the view gets disposed which throws an exception. Looking into a fix...

**Comment by isidorn** [comment]
I have created a PR which address this issue https://github.com/Microsoft/vscode/pull/57491
