### ISSUE TITLE
 Cannot read property 'firstChild' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#57005]
Issue Id: <b>0ef4b72c-7d14-dc49-2565-85a53a8e8389</b><br /><br />*Versions* <br />- 1.26.0<br />-  493869ee8e8a846b0855873886fc79d480d342de<br />-  bda8a4de93278004d6d7c3628b92664f93f7e811<br />-  c827480be25bd63065e7ee2e106c24a707c08004<br />-  207ace21dfec3dccab52f1296a3880ac7644c978<br />*Stack* <br />TypeError: Cannot read property 'firstChild' of undefined<br />[/vs/base/browser/dom.ts#20:13 (clearNode)](https://github.com/microsoft/vscode/blob/4e9361845dc28659923a300945f84731393e210d/src/vs/base/browser/dom.ts#L20:13 (clearNode))<br />[/vs/base/browser/ui/breadcrumbs/breadcrumbsWidget.ts#286:6 (_renderItem)](https://github.com/microsoft/vscode/blob/4e9361845dc28659923a300945f84731393e210d/src/vs/base/browser/ui/breadcrumbs/breadcrumbsWidget.ts#L286:6 (_renderItem))<br />[/vs/base/browser/ui/breadcrumbs/breadcrumbsWidget.ts#265:8 (_render)](https://github.com/microsoft/vscode/blob/4e9361845dc28659923a300945f84731393e210d/src/vs/base/browser/ui/breadcrumbs/breadcrumbsWidget.ts#L265:8 (_render))<br />[/vs/base/browser/ui/breadcrumbs/breadcrumbsWidget.ts#256:7 (setItems)](https://github.com/microsoft/vscode/blob/4e9361845dc28659923a300945f84731393e210d/src/vs/base/browser/ui/breadcrumbs/breadcrumbsWidget.ts#L256:7 (setItems))<br />[/vs/workbench/browser/parts/editor/breadcrumbsControl.ts#227:16 (call)](https://github.com/microsoft/vscode/blob/4e9361845dc28659923a300945f84731393e210d/src/vs/workbench/browser/parts/editor/breadcrumbsControl.ts#L227:16 (call))<br />[/vs/base/common/event.ts#140:15 (fire)](https://github.com/microsoft/vscode/blob/4e9361845dc28659923a300945f84731393e210d/src/vs/base/common/event.ts#L140:15 (fire))<br />[/vs/workbench/browser/parts/editor/breadcrumbsModel.ts#218:21 (_updateOutlineElements)](https://github.com/microsoft/vscode/blob/4e9361845dc28659923a300945f84731393e210d/src/vs/workbench/browser/parts/editor/breadcrumbsModel.ts#L218:21 (_updateOutlineElements))<br />[/vs/workbench/browser/parts/editor/breadcrumbsModel.ts#177:9](https://github.com/microsoft/vscode/blob/4e9361845dc28659923a300945f84731393e210d/src/vs/workbench/browser/parts/editor/breadcrumbsModel.ts#L177:9)<br />    at <anonymous><br />    at process._tickCallback (aaaaaaaaaaaaaaaaaaaaaaaaaaaaa:188:7)<br />

**Comment by jrieken** [comment]
same root cause
