### ISSUE TITLE
 Cannot read property 'classList' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#57006]
Issue Id: <b>4240de92-3050-fab8-2a53-bb2ea93294ff</b><br /><br />*Versions* <br />- 1.26.0<br />-  493869ee8e8a846b0855873886fc79d480d342de<br />-  bda8a4de93278004d6d7c3628b92664f93f7e811<br />-  207ace21dfec3dccab52f1296a3880ac7644c978<br />-  c827480be25bd63065e7ee2e106c24a707c08004<br />*Stack* <br />TypeError: Cannot read property 'classList' of undefined<br />[/vs/base/browser/dom.ts#170:24 (removeClass)](https://github.com/microsoft/vscode/blob/4e9361845dc28659923a300945f84731393e210d/src/vs/base/browser/dom.ts#L170:24 (removeClass))<br />[/vs/base/browser/ui/breadcrumbs/breadcrumbsWidget.ts#200:8 (_focus)](https://github.com/microsoft/vscode/blob/4e9361845dc28659923a300945f84731393e210d/src/vs/base/browser/ui/breadcrumbs/breadcrumbsWidget.ts#L200:8 (_focus))<br />[/vs/base/browser/ui/breadcrumbs/breadcrumbsWidget.ts#258:7 (setItems)](https://github.com/microsoft/vscode/blob/4e9361845dc28659923a300945f84731393e210d/src/vs/base/browser/ui/breadcrumbs/breadcrumbsWidget.ts#L258:7 (setItems))<br />[/vs/workbench/browser/parts/editor/breadcrumbsControl.ts#227:16 (call)](https://github.com/microsoft/vscode/blob/4e9361845dc28659923a300945f84731393e210d/src/vs/workbench/browser/parts/editor/breadcrumbsControl.ts#L227:16 (call))<br />[/vs/base/common/event.ts#140:15 (fire)](https://github.com/microsoft/vscode/blob/4e9361845dc28659923a300945f84731393e210d/src/vs/base/common/event.ts#L140:15 (fire))<br />[/vs/workbench/browser/parts/editor/breadcrumbsModel.ts#218:21 (_updateOutlineElements)](https://github.com/microsoft/vscode/blob/4e9361845dc28659923a300945f84731393e210d/src/vs/workbench/browser/parts/editor/breadcrumbsModel.ts#L218:21 (_updateOutlineElements))<br />[/vs/workbench/browser/parts/editor/breadcrumbsModel.ts#181:12 (runner)](https://github.com/microsoft/vscode/blob/4e9361845dc28659923a300945f84731393e210d/src/vs/workbench/browser/parts/editor/breadcrumbsModel.ts#L181:12 (runner))<br />[/vs/base/common/async.ts#671:3](https://github.com/microsoft/vscode/blob/4e9361845dc28659923a300945f84731393e210d/src/vs/base/common/async.ts#L671:3)<br />

**Comment by jrieken** [comment]
same root cause as #56634
