### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'lineNumber' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#57002]
Issue Id: <b>c24b7a86-ab9f-869b-821f-d9031161a943</b><br /><br />*Versions* <br />- c827480be25bd63065e7ee2e106c24a707c08004<br />-  207ace21dfec3dccab52f1296a3880ac7644c978<br />-  4e9361845dc28659923a300945f84731393e210d<br />-  bda8a4de93278004d6d7c3628b92664f93f7e811<br />-  493869ee8e8a846b0855873886fc79d480d342de<br />*Stack* <br />TypeError: Cannot read property 'lineNumber' of null<br />[/vs/editor/common/core/range.ts#93:15 (containsPosition)](https://github.com/microsoft/vscode/blob/c827480be25bd63065e7ee2e106c24a707c08004/src/vs/editor/common/core/range.ts#L93:15 (containsPosition))<br />[/vs/editor/contrib/documentSymbols/outlineModel.ts#159:14 (_getItemEnclosingPosition)](https://github.com/microsoft/vscode/blob/c827480be25bd63065e7ee2e106c24a707c08004/src/vs/editor/contrib/documentSymbols/outlineModel.ts#L159:14 (_getItemEnclosingPosition))<br />[/vs/editor/contrib/documentSymbols/outlineModel.ts#153:14 (getItemEnclosingPosition)](https://github.com/microsoft/vscode/blob/c827480be25bd63065e7ee2e106c24a707c08004/src/vs/editor/contrib/documentSymbols/outlineModel.ts#L153:14 (getItemEnclosingPosition))<br />[/vs/editor/contrib/documentSymbols/outlineModel.ts#420:18 (getItemEnclosingPosition)](https://github.com/microsoft/vscode/blob/c827480be25bd63065e7ee2e106c24a707c08004/src/vs/editor/contrib/documentSymbols/outlineModel.ts#L420:18 (getItemEnclosingPosition))<br />[/vs/workbench/browser/parts/editor/breadcrumbsModel.ts#196:50 (_getOutlineElements)](https://github.com/microsoft/vscode/blob/c827480be25bd63065e7ee2e106c24a707c08004/src/vs/workbench/browser/parts/editor/breadcrumbsModel.ts#L196:50 (_getOutlineElements))<br />[/vs/workbench/browser/parts/editor/breadcrumbsModel.ts#181:40 (runner)](https://github.com/microsoft/vscode/blob/c827480be25bd63065e7ee2e106c24a707c08004/src/vs/workbench/browser/parts/editor/breadcrumbsModel.ts#L181:40 (runner))<br />[/vs/base/common/async.ts#671:3](https://github.com/microsoft/vscode/blob/c827480be25bd63065e7ee2e106c24a707c08004/src/vs/base/common/async.ts#L671:3)<br />

**Comment by jrieken** [comment]
#56158
