### ISSUE TITLE
Interference Pattern in Integrated Terminal (Ubuntu)

### ISSUE THREAD

**Issue by marktyers** [Microsoft/vscode#57013]
When a computer running Ubuntu 18.4 goes into standby and is subsequently unlocked the integrated terminal is not viewable but displays an interference pattern.

![screenshot from 2018-08-22 15-29-22](https://user-images.githubusercontent.com/207904/44470129-de16ca80-a620-11e8-9621-311f3abd7c0d.png)

Steps to Reproduce:

1. Launch Visual Studio Code 1.26.1
2. Let computer go into standby
3. Unlock computer

Does this issue occur when all extensions are disabled?: No

Extensions installed:

1. C/C++
2. Eslint

**Comment by Tyriar** [comment]
This is caused by Chromium corrupting the canvas, it will likely get fixed eventually when Chromium/Electron fixes it. In the meantime you can hide/show the terminal or resize the window to fix up the rendering
