### ISSUE TITLE
Modify fileLocation for problemMatcher

### ISSUE THREAD

**Issue by sguillia** [Microsoft/vscode#57015]
The problem matcher is useful because it allows to simply click on an error in the _Problems_ list, and the problematic source file opens right where the error occurred.

To do this, the problemMatcher needs to know where the source file is located. That location is configured by the `fileLocation` setting (in `tasks.json`) which can either be `absolute` or `relative`.

I am describing an use case where neither `absolute` nor `relative` works. 
I am not sure whether this is a bug or a feature request.

I am using the Windows Subsystem for Linux (WSL) which is no more than a regular shell.
I am editing a file called `main.c` and its location for Windows looks like:
`C:\Users\<user>\Desktop\main.c`
But its location from WSL is:
`/mnt/c/Users/<user>/Desktop/main.c`

For the sake of this issue I wrote this dummy main:
```
int main()
{
    return x;
}
```

When compiling with `gcc main.c`, this appears:
```
main.c: In function ‘main’:
main.c:4:12: error: ‘x’ undeclared (first use in this function)
     return x;
            ^
```

But when compiling with `gcc $(realpath main.c)` or `gcc /mnt/c/Users/<user>/Destkop/main.c`, this appears:
```
/mnt/c/Users/GUILLIAMS.S/Desktop/testdir/main.c: In function ‘main’:
/mnt/c/Users/GUILLIAMS.S/Desktop/testdir/main.c:4:12: error: ‘x’ undeclared (first use in this function)
     return x;
            ^
```

- I cannot use absolute because to VS Code, `/mnt` does not exist
- I cannot use relative because it is not a relative path
- Even if I could find the root filesystem of WSL inside `C:\` and then use relative path to it, this won't work because `/mnt` is a mount point (if I find `/mnt` on disk, it will be empty)
- Some users cannot use `gcc main.c` because of several reasons.

I can't invoke gcc with relative path because our huge build system is configured like that in my company. 
But I guess there are probably other use cases.

[That poor guy](https://stackoverflow.com/questions/48375130/can-i-modify-filelocation-for-problemmatcher) has the same problem.

One possible fix would be to add a new option called `fileLocationTruncate` or `fileLocationReplace` or something. 
In my case this would look like this:
```
"fileLocation": ["relative", "C:\"],
"fileLocationTruncate": "/mnt/c"
```

**Comment by roicpp** [comment]
I also need such a feature.
I think the solution which will answer the most use cases, will be to provide a more complex ProblemMatcher or at least the ProblemMatcher.uriProvider. 
I personally will be happy if I could provide one in the Task constructor or as a general ProblemMatcher, this I believe will answer a lot of needs and will give us, extension developers greater flexibility in helping our users understand errors.
Alternative solution is to have default case where if the file wasn't found using the current options, search for it throughout the workspace and give back the 1st result (as multiple files can be found)

BTW, my use case is both operating in a Windows system with a Linux build server and having a build system which only gives the file name in the error path (some variation of make) the file folder is a few lines after or before.

**Comment by kayle** [comment]
Need the same thing. If it's helpful you can use ```mklink /j``` to create a junction for the mnt location (& and gitignore the mnt directory).

**Comment by Tyriar** [comment]
We just announced remote development with VS Code, check out the blog post for details https://code.visualstudio.com/blogs/2019/05/02/remote-development

**Comment by aeschli** [comment]
verified in Version: 1.34.0-insider (user setup)
Commit: daf71423252a707b8e396e8afa8102b717f8213b
Remote - WSL 0.32.0
