### ISSUE TITLE
tab key inserts weird text, breaks undo

### ISSUE THREAD

**Issue by ridiculousfish** [Microsoft/vscode#5701]
- VSCode Version:
  Version 1.0.0 (1.0.0)
  fa6d0f03813dfb9df4589c30121e9fcffa8a8ec8

- OS Version: OS X El Capitan 10.11.4

Steps to Reproduce:

1. Open a CSS file with the following contents (note spacing is important)

        .foo {
        background: linear-gradient(180deg,white 0%);
        }

2. That `background:` line needs to be indented. Position the cursor at the beginning of that line.
3. Press tab to try to indent it.
4. Result: VS Code adds a bunch more lines, which are not indented:

        .foo {
        background: -webkit-linear-gradient(white 0%);
        background: -o-linear-gradient(white 0%);
        background: linear-gradient(white 0%);
        }

5. No, that's not what I want! Undo! Undo! (Cmd-Z)
6. VS Code deletes the file contents.

The two unexpected behaviors are:

1. Tab should adjust indentation, not do whatever it did in step 4.
2. Undo should undo the last change, not clear the file as in step 6.

**Comment by egamma** [comment]
The additional line come from the integrated emmet support. In the May version of VS Code we have added a setting to disable emmet expansion triggering on Tab. 

Pls see #4588 

You can already try this out in our  [insiders build](https://code.visualstudio.com/blogs/2016/02/01/introducing_insiders_build) today: http://code.visualstudio.com/Download#insiders

**Comment by ridiculousfish** [comment]
Ok. That Undo deletes a bunch of unmodified text still seems like a bug. I verified that this still happens in the insiders build. Would you like to reopen this, or shall I file a new one?
