### ISSUE TITLE
Move Line up/down causes Logpoint to misaligned with line to log on

### ISSUE THREAD

**Issue by yogeshlonkar** [Microsoft/vscode#57016]
- VSCode Version: 1.26.1
- OS Version: macOS 10.13.6

Steps to Reproduce:

1. Add a Logpint to any javascript file printing some variable
2. Launch debugger & complete the execution. (Logpoint works fine till here)
3. Move the any line below the Logpoint above it using `ALT` + `Up`
4. Restart debugger & continue stepping over. **Logpoint is not in sync with line it is being shown on**

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
https://github.com/Microsoft/vscode/issues/56398
