### ISSUE TITLE
CSS intellisense does not work in inline styles

### ISSUE THREAD

**Issue by shizengzhou** [Microsoft/vscode#57010]
Issue Type: <b>Bug</b>

IntelliSense can not be triggered automatically in inline styles, I have to use `Ctrl+Space` to trigger it.
1.25.1
![1.25.1](https://i.loli.net/2018/08/22/5b7d6eb9bc005.gif)
1.26.1
![1.26.1](https://i.loli.net/2018/08/22/5b7d6f187f0f5.gif)
VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz (4 x 2893)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (3.38GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by octref** [comment]
@jrieken 

HTML server returns the same result, `"style=\"$1\""` for completion item.

- 1.25.1: After getting `style="|"`, typing `b` would trigger another completion request.
- Now: After getting `style="|"`, typing `b` does **not** trigger another completion request.

**Comment by jrieken** [comment]
This was done purpose because of conflicts with tab when snippets and quick suggestions are active. There is a new setting that controls this: `"editor.suggest.snippetsPreventQuickSuggestions": false,`

**Comment by jrieken** [comment]
See #50776 for all the details
