### ISSUE TITLE
Failed to save file: Insufficient permissions. Select 'Retry as Admin' to retry as administrator

### ISSUE THREAD

**Issue by jdk339** [Microsoft/vscode#57020]
- VSCode Version: 1.26.1
- OS Version: macOS High Sierra 10.13.x

Steps to Reproduce:

1. Edit a moved file
2. Try to save the file

![image](https://user-images.githubusercontent.com/16578448/44474254-3d181780-a600-11e8-8b40-4c35b7c609e6.png)

I ran a script that moved a lot of files and now whenever I try to save those files that were moved, VS Code asks me to enter my password every.single.time. The permissions on the files are the same. Once I enter my password for a file I can save it again without reprompting. But I don't want to enter my password for hundreds of files I have to make changes to. I already feel like throwing my laptop against the wall after doing it a few times.

Does this issue occur when all extensions are disabled?: Yes/No

`Command not found`

**Comment by jdk339** [comment]
Those issues are not the same, so this is not a duplicate issue

**Comment by jdk339** [comment]
Only temporarily solution I found to solve this is to run VS Code as root:

`sudo code`

Note: You may need to install the `code` command in your PATH variable:

[](https://code.visualstudio.com/docs/setup/mac[](Mac setup))

**Comment by bpasero** [comment]
If you cannot save a file with VSCode it could mean that the place you moved the files to needs different user permissions. Could that be true?

**Comment by jdk339** [comment]
I think that could be true. It's no longer an issue after running `sudo chown -R myuser .`. I thought I had sufficient permissions, but this seems to have fixed it.
