### ISSUE TITLE
Intellisense doesn't recognize type defintions from base tsconfig

### ISSUE THREAD

**Issue by tzvipm** [Microsoft/vscode#57021]
Issue Type: <b>Bug</b>

I created a npm package called [`tsconfig-vscode-base`](https://www.npmjs.com/package/tsconfig-vscode-base) to demonstrate this behaviour in a consumign project [here](https://github.com/tzvipm/tsconfig-extends-vscode).

Note in the following screenshot that the `"*.css"` module in the npm package is not being propagated form the base tsconfig:
<img width="1680" alt="screen shot 2018-08-22 at 11 42 32 am" src="https://user-images.githubusercontent.com/1950680/44474631-20c8aa80-a601-11e8-86bb-c604039ebfa4.png">

Note, also, that running `tsc --noEmit` confirms there are no errors in the typescript side of things, so it appears to be a bug with intellisense:
<img width="1077" alt="screen shot 2018-08-22 at 11 43 04 am" src="https://user-images.githubusercontent.com/1950680/44474640-2625f500-a601-11e8-9999-4872786ab209.png">

VS Code version: Code - Insiders 1.27.0-insider (e0a68266321d1518bc12428b71d80524461a275b, 2018-08-22T05:12:41.569Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|/private/var/folders/km/tv43lbwd1zg9v9wgcf2rq_cr0000gn/T/AppTranslocation/280C6EDA-85A7-4D1D-A14D-B4770BAD5B57/d/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_6477357|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by mjbvz** [comment]
In `index.ts`, run the `Go to project configuration command`. Does this open the correct `tsconfig.json`. I suspect not because `index.ts` is not included in the `files` section of of the tsconfig
