### ISSUE TITLE
Error packge extension : Command failed: C:\WINDOWS\system32\cmd.exe /s /c "node ./node_modules/vscode/bin/compile"

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#5702]
- VSCode Version: 1
- OS Version: Win 10

When i try to publish the extension i get the following error.

> Executing prepublish script 'node ./node_modules/vscode/bin/compile'...
> Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "node ./node_modules/vscode/bin/compile"

Following is the package json scripts section
```
"scripts": {
    "vscode:prepublish": "node ./node_modules/vscode/bin/compile",
    "compile": "node ./node_modules/vscode/bin/compile -watch -p ./",
    "postinstall": "node ./node_modules/vscode/bin/install"
  },
```

**Comment by bpasero** [comment]
@shanalikhan do you have such a `compile` command in your node_modules folder? can you run `node ./node_modules/vscode/bin/compile ` from the command line?

**Comment by shanalikhan** [comment]
When i run the command and then run the npm install and set vsce package. It worked
Thanks
