### ISSUE TITLE
After running a command in the terminal, the terminal editor loses focus

### ISSUE THREAD

**Issue by drk-mtr** [Microsoft/vscode#57023]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by Tyriar** [comment]
Can you elaborate a little more on the problem? How to reproduce, system/vscode version details, etc.

**Comment by drk-mtr** [comment]
Apologies - looks like the issue submission failed. I've tested this on another PC using the same version of VS code and it works fine, so this could be plugin related - will close and raise a bug (properly!) if I can reproduce it.
