### ISSUE TITLE
how can i disable suggestion which is caused by 'Enter' key. 

### ISSUE THREAD

**Issue by LOGANLEEE** [Microsoft/vscode#57026]
- VSCode Version:Version 1.26.1 (1.26.1)
- OS Version: OSX 10.13.6

Steps to Reproduce:

[1.
<img width="1680" alt="screen shot 2018-08-23 at 1 34 55 am" src="https://user-images.githubusercontent.com/26853553/44477224-fc0e1a80-a674-11e8-9904-0f4a304e782a.png">

2. i used 'code suggestion' key as ` and i never set with enter key for some suggestion function or setting. But it suddenly( i assume this happened after auto update of Vscode) come out and border me toooooo much.
how can i disable this? thank you.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by ramya-rao-a** [comment]
Add `"editor.acceptSuggestionOnEnter": "off"` to your settings

**Comment by LOGANLEEE** [comment]
i pressed enter for breaking line but every single time that suggestion coming up after turned it off.
i want to turn off that suggestion function while keeping normal suggestion function

**Comment by LOGANLEEE** [comment]
i fixed problem that was the snippet suggestion function automatically turned on after updating VSCODE wether i want it or not
