### ISSUE TITLE
Autocomplete often incorrectly replaces typed text

### ISSUE THREAD

**Issue by rayrSC** [Microsoft/vscode#57037]
Issue Type: <b>Bug</b>

Often, while typing in the editor, when I press space after a word, the editor will replace the perfectly valid code with something invalid.  I am currently working in C#, and have this happen frequently with several keywords.  Today, I tried the Insiders build as well, but still run into the issue.  I have also attached a video of the problem happening.

Some examples:
- `new` becomes `nameof`
- `private` becomes `partial`
- `return` becomes `ref`

VS Code version: Code - Insiders 1.27.0-insider (e0a68266321d1518bc12428b71d80524461a275b, 2018-08-22T05:12:41.569Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (1.04GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_2015724|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.15.2
unity-debug|Uni|1.3.0

</details>

[bad-autocomplete.zip](https://github.com/Microsoft/vscode/files/2311514/bad-autocomplete.zip)

**Comment by ramya-rao-a** [comment]
Please log this issue in the C# extension that you are using.

**Comment by nicholasbraun** [comment]
I have the same issue with Javascript.

For example when I type:

```javascript
expect(wrapper.find(
```

as soon as I type the opening bracket, it autocompletes it to:

```javascript
expect(wrapper.BiquadFilterNode)
```

![screen shot 2018-09-21 at 11 00 21](https://user-images.githubusercontent.com/29401371/45871347-9608d600-bd8d-11e8-90db-d044e907ba0e.png)

**Comment by ramya-rao-a** [comment]
@nicholasbraun Please log a separate issue for this.
