### ISSUE TITLE
The sync button and remote commit status should be visible in the Git panel even when only 1 repo is selected

### ISSUE THREAD

**Issue by costincaraivan** [Microsoft/vscode#57030]
I have a workspace with multiple projects/repos/folders.

In the Git panel, each of them has a line like this:

(name) (SCM) (number of local commits) (branch icon) (sync icon) (number of remote commits to pull) (number of local commits to push)

For some reason, when the workspace has only 1 repo, the UI changes and it looks like this:

SOURCE CONTROL: GIT (commit checkmark) (refresh sign) (extra options button)

Summary: add the red boxes to the single folder workspace:

![vscode](https://user-images.githubusercontent.com/1235856/44511626-6dbb8800-a6b8-11e8-8135-6b475604862a.png)

The sync/commit number indicators are super useful. Please add them even for just 1 project/repo/folder.

**Comment by joaomoreno** [comment]
Set `"scm.alwaysShowProviders": false`.
