### ISSUE TITLE
Improve handling of fallback theme colors in terminal

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#57038]
See https://github.com/Microsoft/vscode/issues/56864#issuecomment-414939406

**Comment by ParkourKarthik** [comment]
I would like to pick this up. Before the PR, clarification on the change:

https://github.com/Microsoft/vscode/blob/07618102efdd63f09949ce54c161e7fd2a954ee8/src/vs/workbench/parts/terminal/common/terminalColorRegistry.ts#L16-L29
I believe the changes are to set the default nulls to their respective editor colors as defaults.
Ex:` registerColor('terminal.background', {
	dark: editorBackground,
	light: editorBackground,
	hc: editorBackground
}, ... `

I think that hardcoded defaults such as `TERMINAL_FOREGROUND_COLOR` need not be disturbed.

**Comment by Tyriar** [comment]
@ParkourKarthik great! Background and border should be changed to the better as they are the ones that fallback:

https://github.com/Microsoft/vscode/blob/f7b8c9b7df54f23b02fb36ba0cb12a5a96c8c4e9/src/vs/workbench/parts/terminal/electron-browser/terminalPanel.ts#L313-L316
