### ISSUE TITLE
TM Scope / Color for Typescript 3's `unknown` not set

### ISSUE THREAD

**Issue by babakness** [Microsoft/vscode#57035]
- VSCode Version: 1.26.0
- OS Version: MacOS 10.13.5

Steps to Reproduce:

1. Open Typescript file (.ts extension)
2. Set type of variable or object to `unknown`

Does this issue occur when all extensions are disabled?: Yes

Since Typescript 3 is included with the latest VS Code, I expected the 'unknown' type to be scope correctly. It is not, at least not for me.

**Comment by mjbvz** [comment]
Please provide a code example
