### ISSUE TITLE
String method names do not terminate string syntax highlighting

### ISSUE THREAD

**Issue by chadhietala** [Microsoft/vscode#5703]
- VSCode Version: 1.0.0 
- OS Version: OSX 10.10.5

Steps to Reproduce:

1. Have a class with stings as method names
2. Observe syntax highlighting is different from non-string method names

__String Method Name__
<img width="838" alt="screen shot 2016-04-23 at 1 56 50 pm" src="https://cloud.githubusercontent.com/assets/183799/14763949/4a0b7214-095b-11e6-9e4f-8dd77a027c77.png">

__Method Name__
<img width="870" alt="screen shot 2016-04-23 at 1 55 35 pm" src="https://cloud.githubusercontent.com/assets/183799/14763946/26a33b2c-095b-11e6-828f-17dd959f9ded.png">

**Comment by aeschli** [comment]
Reproduced with the following snippet:
```javascript
class TestCase {
    ['foo']() {
        this.registerComponent('foo-bar');
    }
}

class TestCase2 {
    foo() {
        this.registerComponent('foo-bar');
    }
}
```

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#154
