### ISSUE TITLE
Request textDocument/hover failed Error Code -36203

### ISSUE THREAD

**Issue by mcconn13** [Microsoft/vscode#57044]
Issue Type: <b>Bug</b>

I suspect this is an issue with one of the Ruby extensions that I have installed. I've made sure that I have all of the required Ruby gems installed on my machine and still get this error. I have gone through and disabled all the Ruby extensions but still get this error. I suspect its a Solargraph issue though.

Extenstions are: Ruby 0.20.0 (Peng Lv), ruby Language Colorization 0.0.6 (Drew Cain), and Ruby Solargraph 0.17.6 (Castwide).

It is reproduced whenever I hover over a section of code that contains my variables.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz (32 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.92GB (53.29GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
solargraph|cas|0.17.6
gc-excelviewer|Gra|2.1.26
ruby|gro|0.0.6
MagicPython|mag|1.0.12
rainbow-csv|mec|0.4.2
python|ms-|2018.7.1
ruby|reb|0.20.0
python|tht|0.2.3

(3 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
@mcconn13 please file issue against the ruby extension and start investigation from there first, thanks!
