### ISSUE TITLE
tabs overlapping when its open

### ISSUE THREAD

**Issue by williambrandino** [Microsoft/vscode#57040]
Issue Type: <b>Bug</b>

Opening a tab by the command `ctrl+p`,  this new tab overlap another focused tab.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:34:20.517Z)
OS version: Linux x64 4.15.0-32-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz (4 x 797)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 2, 2|
|Memory (System)|7.69GB (0.14GB free)|
|Process Argv|/usr/share/code/code /mnt/novoremote/assist/|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-postgres|cko|1.0.16
vscode-eslint|dba|1.4.14
php-debug|fel|1.12.4
php-intellisense|fel|2.3.4
php-pack|fel|1.0.2
php-cs-fixer|jun|0.1.84
vscode-language-pack-pt-BR|MS-|1.26.3
php-formatter|Sop|0.2.4
vscode-todo-highlight|way|1.0.4

</details>

**Comment by Tyriar** [comment]
Can you post a screenshot?

**Comment by williambrandino** [comment]
Sorry about that.
If I active ctrl+p AND Arrow, open a new tab.

I'm closing this.
