### ISSUE TITLE
Settings.json: Files.Exclude - Unable to exclude folders containing periods

### ISSUE THREAD

**Issue by alohaninja** [Microsoft/vscode#57048]
- VSCode Version: 1.25
- OS Version: Win10

### Steps to Reproduce:

1. add exclusion parameter for `code/myapp.web/**`

```
"files.exclude": {
        "code/myapp\\.web/**": true,
        "code/myapp\\.web/assets/**.js": true,
    }
```

Does this issue occur when all extensions are disabled?: Yes

Files and directory exclusions do not support period in the folder name.

**Comment by roblourens** [comment]
You don't have to escape the `.`. This works for me if I just add a pattern like `"code/myapp.web/**"`

**Comment by alohaninja** [comment]
Looks like I stumbled upon a case-sensitivity issue, not necessarily the period. Thanks for verifying! 🎉 

### Works

"files.exclude": {
        "code/MyApp\\.Web/**": true,
    }

### Doesn't Work

"files.exclude": {
        "code/myapp\\.web/**": true,
    }
