### ISSUE TITLE
macOS: Native Tabs still not working

### ISSUE THREAD

**Issue by psachs21** [Microsoft/vscode#57056]
Duplicate of https://github.com/Microsoft/vscode/issues/35361 but the issue is now locked.

VSCode Version: Latest Insiders
Version: 1.27.0-insider
Commit: e0a68266321d1518bc12428b71d80524461a275b
Date: 2018-08-22T05:12:41.569Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

OS Version: MacOS 10.13.6

Steps to Reproduce:

1. Downloaded fresh VSCode
2. Open preferences and enable window.nativeTabs
3. Restart
4. Open a new window (command + shift + N)

Notice the grey bar at the top.

![screen shot 2018-08-22 at 11 02 51 pm](https://user-images.githubusercontent.com/11449728/44502774-163dfd80-a661-11e8-955e-d7fd3cc8d832.png)

Tried everything else suggested in original
- toggling preference on/off several times
- installed a fresh copy of vscode

Using the workaround provided in #35361 still works:

1. Open Visual Studio Code - Insiders.app/Contents/info.plist
2. Change `CFBundleIdentifier` to `com.microsoft2.VSCodeInsiders`

Everything works as expected now.

**Comment by psachs21** [comment]
So, with another workaround provided from the original issue, if I launch Code like so:

`/Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron -- -NSUseImprovedLayoutPass true`

It works. Seems like somehow `NSUseImprovedLayoutPass` has been set to false... Somewhere. So I would assume `systemPreferences.registerDefaults({ NSUseImprovedLayoutPass: true });` (https://github.com/Microsoft/vscode/pull/52775/files#diff-fc6683f92061646324644f2cd92304cfR284) is not taking in my case.

**Comment by bpasero** [comment]
@psachs21 does it work with our previous 1.25 version? You can get it from [here](https://az764295.vo.msecnd.net/stable/1dfc5e557209371715f655691b1235b6b26a06be/VSCode-darwin-stable-unsigned.zip).

**Comment by psachs21** [comment]
@bpasero So running 1.25, it reproduced initially. I then reset the setting (on => off => on) and now it works. This did not work with 1.26... Except now. After i installed 1.25 and did the toggle setting, and reopened stable, it works properly... Sure. That was fun.

**Comment by bpasero** [comment]
@psachs21 I did indeed change some code around this in 1.26 and possibly this causes the issue you see. I have reverted that code back to how it was in 1.25. 

Btw I got a ping from Apple that they said they had fixed the issue, but the update is still not out it seems and I am not sure if it comes with a major update (Mojave) or not.

**Comment by psachs21** [comment]
@bpasero thanks for all the help. Hopefully nobody else runs into this weird issue. Hopefully it won't pop up again on the next update. Appreciate all your help on this.

**Comment by meandmax** [comment]
I still have this issue. But for me the tab bar is not even visible, anybody experiencing the same?

<img width="415" alt="screen shot 2018-09-10 at 9 41 22 am" src="https://user-images.githubusercontent.com/6309638/45270181-b4451b00-b4dd-11e8-9668-fd2873dd1e5a.png">
<img width="315" alt="screen shot 2018-09-10 at 9 40 45 am" src="https://user-images.githubusercontent.com/6309638/45270182-b5764800-b4dd-11e8-8e47-d39333806ca1.png">
