### ISSUE TITLE
Snippet transforms don't work with choice placeholders

### ISSUE THREAD

**Issue by a01fe** [Microsoft/vscode#57052]
Issue Type: <b>Bug</b>

Snippet placeholder transforms do not work when the placeholder has choices instead of a default value.

Reproduce with this snippet:

```
"test": {
	"prefix": "test",
	"body": [
		"placeholder thing ${1:this}",
		"choice thing ${2|this,that,other|}",
		"transform placeholder ${1/(this)|(that)|(other)/${1:+1}${2:+2}${3:+3}/}",
		"transform placeholder ${2/(this)|(that)|(other)/${1:+1}${2:+2}${3:+3}/}",
		"$0"
	],
	"description": "test test test"
}
```

Expanding the snippet with `that` entered for both placeholders results in:

```
placeholder thing that
choice thing that
transform placeholder 2
transform placeholder that
```

VS Code version: Code - Insiders 1.27.0-insider (e0a68266321d1518bc12428b71d80524461a275b, 2018-08-22T05:12:41.569Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|64.00GB (42.73GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|43%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.3.2
EditorConfig|Edi|0.12.4
asciidoctor-vscode|joa|0.15.0
vscode-emacs-friendly|lfs|0.8.2
mssql|ms-|1.4.0
python|ms-|2018.7.1
azure-account|ms-|0.4.3
PowerShell|ms-|1.8.3
gradle-language|nac|0.2.3
vscode-docker|Pet|0.1.0
remote-vscode|raf|1.1.0
java|red|0.29.0
code-spell-checker|str|1.6.10
vscode-java-debug|vsc|0.11.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.8.0
vscode-maven|vsc|0.10.0
plsql-language|xyz|1.4.2

</details>

**Comment by jrieken** [comment]
Yeah, that's the design and I don't think that Textmate snippets support that.

**Comment by a01fe** [comment]
Ahh, ok. If there's a design reason for disallowing placeholders with choice values to be used with transforms, then perhaps the documentation should reflect that?

**Comment by jrieken** [comment]
We have this document (and a grammar definition): https://code.visualstudio.com/docs/editor/userdefinedsnippets#_grammar

**Comment by ChuckJonas** [comment]
Come-on... At the very least the documentation needs to be updated to reflect this limitation.  Wasted a lot of time trying to figure this out.
