### ISSUE TITLE
Destructure + highlight issue for typescript 3.0.1

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#57053]
```ts
interface Boo {
  a: string,
  b: string
}
function foo(x) { return x }
foo(() => ({ a, b }: Boo) => {
  return a + b
})
foo(() => ({
  a, b }: Boo) => {
})
```
![image](https://user-images.githubusercontent.com/3254987/44497863-7cf6f300-a630-11e8-8469-cc54ed25be2b.png)
Note the second `Boo` highlight is incorrect.

VSCode: 1.26.1

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#659
