### ISSUE TITLE
input on snippet placeholder not show IntelliSense

### ISSUE THREAD

**Issue by baby5** [Microsoft/vscode#57060]
- VSCode Version: 1.26.1
- OS Version: win10 1803 17134.228

Steps to Reproduce:

1. input any snippet which has placeholders
2. input on placeholder, my input word would have gray background color and not show IntelliSense

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
We have a new setting for that, it is ` "editor.suggest.snippetsPreventQuickSuggestions": false,` and enables/disables quick suggestions when inserting snippets
