### ISSUE TITLE
Failed to install VS Code update. Please download and reinstall VS Code.

### ISSUE THREAD

**Issue by jphellemons** [Microsoft/vscode#57064]
<img width="349" alt="vscode-dialog" src="https://user-images.githubusercontent.com/1119134/44510718-b887d080-a6b5-11e8-8269-2e90dca488b1.PNG">
 

- VSCode Version: I removed the regular version and moved to the one with the new background update mechanism as suggested by that build. So I think that I am on the July update? I did had breadcrumbs enabled. perhaps that helps finding out what version I was upgrading from and to.
- OS Version: win 10 (1803) build 17134.228

Steps to Reproduce:

1. Business as usual. Notice the 1 at the gear icon.
2. click gear icon and select restart to update

Here is the inno update log (I will remove some duplicate lines for readability):

>Aug 23 09:15:31.368 INFO Starting: C:\Users\leode\AppData\Local\Programs\Microsoft VS Code\Code.exe, false
Aug 23 09:15:31.372 INFO Checking for running Code.exe processes... (attempt 1)
Aug 23 09:15:31.386 INFO Code.exe is running, wait a bit
... lines removed ....
Aug 23 09:16:00.691 INFO Code.exe is running, wait a bit
Aug 23 09:16:01.191 INFO Checking for running Code.exe processes... (attempt 59)
Aug 23 09:16:01.203 INFO Code.exe is running, wait a bit
Aug 23 09:16:01.704 INFO Checking for running Code.exe processes... (attempt 60)
Aug 23 09:16:01.717 INFO Gave up waiting for Code.exe to exit
Aug 23 09:16:01.717 INFO Checking for possible conflicting running processes... (attempt 1)
Aug 23 09:16:01.729 INFO Kill process if found: 18428, Code.exe
Aug 23 09:16:01.729 INFO Found Code.exe running, pid 18428, attempting to kill...
Aug 23 09:16:01.729 INFO Successfully killed Code.exe, pid 18428
Aug 23 09:16:01.730 INFO Kill process if found: 6936, Code.exe
Aug 23 09:16:01.730 INFO Found Code.exe running, pid 6936, attempting to kill...
Aug 23 09:16:01.730 INFO Successfully killed Code.exe, pid 6936
Aug 23 09:16:01.730 INFO Kill process if found: 24824, Code.exe
Aug 23 09:16:01.730 INFO Found Code.exe running, pid 24824, attempting to kill...
Aug 23 09:16:01.730 INFO Successfully killed Code.exe, pid 24824
Aug 23 09:16:01.730 INFO Inno Updater v0.5.0
Aug 23 09:16:01.731 INFO Starting update, silent = false
Aug 23 09:16:01.766 INFO do_update: "C:\\Users\\leode\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe", _
Aug 23 09:16:01.766 INFO move_update: "C:\\Users\\leode\\AppData\\Local\\Programs\\Microsoft VS Code\\unins000.dat", _
Aug 23 09:16:01.768 INFO Delete: "api-ms-win-core-console-l1-1-0.dll" (attempt 1)
Aug 23 09:16:01.769 INFO Delete: "api-ms-win-core-datetime-l1-1-0.dll" (attempt 1)
Aug 23 09:16:01.771 INFO Delete: "api-ms-win-core-debug-l1-1-0.dll" (attempt 1)
Aug 23 09:16:01.772 INFO Delete: "api-ms-win-core-errorhandling-l1-1-0.dll" (attempt 1)
Aug 23 09:16:01.773 INFO Delete: "api-ms-win-core-file-l1-1-0.dll" (attempt 1)
Aug 23 09:16:01.775 INFO Delete: "api-ms-win-core-file-l1-2-0.dll" (attempt 1)
Aug 23 09:16:01.777 INFO Delete: "api-ms-win-core-file-l2-1-0.dll" (attempt 1)
Aug 23 09:16:01.778 INFO Delete: "api-ms-win-core-handle-l1-1-0.dll" (attempt 1)
Aug 23 09:16:01.779 INFO Delete: "api-ms-win-core-heap-l1-1-0.dll" (attempt 1)
Aug 23 09:16:01.779 INFO Delete: "api-ms-win-core-interlocked-l1-1-0.dll" (attempt 1)
Aug 23 09:16:01.780 INFO Delete: "api-ms-win-core-libraryloader-l1-1-0.dll" (attempt 1)
Aug 23 09:16:01.781 INFO Delete: "api-ms-win-core-localization-l1-2-0.dll" (attempt 1)
Aug 23 09:16:01.783 INFO Delete: "api-ms-win-core-memory-l1-1-0.dll" (attempt 1)
Aug 23 09:16:01.785 INFO Delete: "api-ms-win-core-namedpipe-l1-1-0.dll" (attempt 1)
Aug 23 09:16:01.786 INFO Delete: "api-ms-win-core-processenvironment-l1-1-0.dll" (attempt 1)
Aug 23 09:16:01.787 INFO Delete: "api-ms-win-core-processthreads-l1-1-0.dll" (attempt 1)
Aug 23 09:16:01.788 INFO Delete: "api-ms-win-core-processthreads-l1-1-1.dll" (attempt 1)
Aug 23 09:16:01.789 INFO Delete: "api-ms-win-core-profile-l1-1-0.dll" (attempt 1)
Aug 23 09:16:01.791 INFO Delete: "api-ms-win-core-rtlsupport-l1-1-0.dll" (attempt 1)
Aug 23 09:16:01.792 INFO Delete: "api-ms-win-core-string-l1-1-0.dll" (attempt 1)
Aug 23 09:16:01.794 INFO Delete: "api-ms-win-core-synch-l1-1-0.dll" (attempt 1)
Aug 23 09:16:01.798 INFO Delete: "api-ms-win-core-synch-l1-2-0.dll" (attempt 1)
Aug 23 09:16:01.799 INFO Delete: "api-ms-win-core-sysinfo-l1-1-0.dll" (attempt 1)
Aug 23 09:16:01.800 INFO Delete: "api-ms-win-core-timezone-l1-1-0.dll" (attempt 1)
Aug 23 09:16:01.801 INFO Delete: "api-ms-win-core-util-l1-1-0.dll" (attempt 1)
Aug 23 09:16:01.802 INFO Delete: "api-ms-win-crt-conio-l1-1-0.dll" (attempt 1)
Aug 23 09:16:01.803 INFO Delete: "api-ms-win-crt-convert-l1-1-0.dll" (attempt 1)
Aug 23 09:16:01.803 INFO Delete: "api-ms-win-crt-environment-l1-1-0.dll" (attempt 1)
Aug 23 09:16:01.804 INFO Delete: "api-ms-win-crt-filesystem-l1-1-0.dll" (attempt 1)
Aug 23 09:16:01.805 INFO Delete: "api-ms-win-crt-heap-l1-1-0.dll" (attempt 1)
Aug 23 09:16:01.806 INFO Delete: "api-ms-win-crt-locale-l1-1-0.dll" (attempt 1)
Aug 23 09:16:01.807 INFO Delete: "api-ms-win-crt-math-l1-1-0.dll" (attempt 1)
Aug 23 09:16:01.809 INFO Delete: "api-ms-win-crt-multibyte-l1-1-0.dll" (attempt 1)
Aug 23 09:16:01.815 INFO Delete: "api-ms-win-crt-private-l1-1-0.dll" (attempt 1)
Aug 23 09:16:01.816 INFO Delete: "api-ms-win-crt-process-l1-1-0.dll" (attempt 1)
Aug 23 09:16:01.818 INFO Delete: "api-ms-win-crt-runtime-l1-1-0.dll" (attempt 1)
Aug 23 09:16:01.819 INFO Delete: "api-ms-win-crt-stdio-l1-1-0.dll" (attempt 1)
Aug 23 09:16:01.820 INFO Delete: "api-ms-win-crt-string-l1-1-0.dll" (attempt 1)
Aug 23 09:16:01.820 INFO Delete: "api-ms-win-crt-time-l1-1-0.dll" (attempt 1)
Aug 23 09:16:01.822 INFO Delete: "api-ms-win-crt-utility-l1-1-0.dll" (attempt 1)
Aug 23 09:16:01.823 INFO Delete: "bin" (attempt 1)
Aug 23 09:16:01.826 INFO Delete: "blink_image_resources_200_percent.pak" (attempt 1)
Aug 23 09:16:01.827 INFO Delete: "Code.exe" (attempt 1)
Aug 23 09:16:01.877 INFO Delete: "Code.exe" (attempt 2)
Aug 23 09:16:02.079 INFO Delete: "Code.exe" (attempt 3)
Aug 23 09:16:02.530 INFO Delete: "Code.exe" (attempt 4)
Aug 23 09:16:03.334 INFO Delete: "Code.exe" (attempt 5)
Aug 23 09:16:04.586 INFO Delete: "Code.exe" (attempt 6)
Aug 23 09:16:06.386 INFO Delete: "Code.exe" (attempt 7)
Aug 23 09:16:08.837 INFO Delete: "Code.exe" (attempt 8)
Aug 23 09:16:12.039 INFO Delete: "Code.exe" (attempt 9)
Aug 23 09:16:16.090 INFO Delete: "Code.exe" (attempt 10)
Aug 23 09:16:21.090 INFO Delete: "Code.exe" (attempt 11)
Aug 23 09:16:21.091 ERRO Toegang geweigerd. (os error 5)

I have seen some update errors as issues. But some where mac os related and I do not know if it is OS specific. Perhaps there is already a similar issue logged. If so, please ignore this one.

**Comment by bardware** [comment]
I have this error too. I started Insider-install running in c:\Programms.
I clicked install updates on the bottom left. Code asked for privileges which I confirmed.
I eventually closed code and a popup appeared. After a few moments I got the same error as the thread opener.
I wanted to restart code but got the message the exe has disappeared and the shortcut from start menu was deleted.
