### ISSUE TITLE
IDE does not understand Javascript multi-line string 

### ISSUE THREAD

**Issue by dsenthilraj** [Microsoft/vscode#5706]
- VSCode Version: 0.10.11 (0.10.11)
- OS Version: OSX

Steps to Reproduce:

1.  Create Java script file 

2. Add following lines
```javascript
$('.videos').append('<li> \
                <span>' + count + '</span> - \
                <a href="' + vList[i].player + '"> \
                    <span class="title">' + videoTitle + '</span> \
                </a> \
                </li>');
```

IDE understand first line as string but  line 2 -5 it try compile and high lights keywords and other stuff

**Comment by aeschli** [comment]
This seems to be fixed in 1.0:
![image](https://cloud.githubusercontent.com/assets/6461412/14779130/dfa6d97c-0ad6-11e6-96c5-c336620e7d57.png)
