### ISSUE TITLE
Language specific encoding not applied when file opened on startup

### ISSUE THREAD

**Issue by bddali** [Microsoft/vscode#57061]
Visual Studio Code 1.26.1 on Windows 10 and Windows Server 2016.

I have added a language specific encoding to my user settings:

```
"files.autoGuessEncoding": false,
"[perl]": {
    "files.encoding": "cp850",
},
```

If I open a perl file from within Visual Studio Code (File -> Open File...), the correct encoding is applied.

If Visual Studio Code is running and I open a perl file from Explorer using "Open with Code" context menu, the correct encoding is applied.

If Visual Studio Code is not running and I open a perl file from Explorer using "Open with Code" context menu, the correct encoding is NOT applied.

Starting Visual Studio Code from the command line with a perl file as parameter produces the same results.

**Comment by sdvesna48** [comment]
Vsc restart

**Comment by sdvesna48** [comment]
Open code

**Comment by bddali** [comment]
Not sure what you are saying, but restarting VSCode does not help.

**Comment by bpasero** [comment]
I can reproduce. If I add a console.log to the place where we read the encoding for the file ([here](https://github.com/Microsoft/vscode/blob/c1126302de7261d7d2bf3ada2fbfda5cb881b244/src/vs/workbench/services/files/electron-browser/encoding.ts#L95)) I can see that I get a value of utf8 at first (right on startup) and then later when I ask again, it is the correct encoding. Seems like an issue with the configuration service returning wrong values on startup to me.

**Comment by sandy081** [comment]
@bpasero Configuration service is returning the right value. But the language/mode that is being provided is not right. 

![image](https://user-images.githubusercontent.com/10746682/44571364-e554ea00-a780-11e8-8044-2e11913322b9.png)

In the above screenshot, IModelService / IModeService is first returning `plainText` as the languageId and is returning `perl` after some time. Guessing that the ModeService is not yet initialised by then?

**Comment by bpasero** [comment]
@alexandrudima adding you based on the findings from https://github.com/Microsoft/vscode/issues/57061#issuecomment-415678631

**Comment by bpasero** [comment]
Interestingly the status bar changes from "Plain Text" to "Perl" after some time, so there is probably a language mode change at a later point in time and the encoding does not react to that.

**Comment by bpasero** [comment]
This is not easy to fix because we do not want the editor to wait for the extension host to come up before loading the contents and we need an encoding when loading the file. If the language mode changes after we have loaded the file we can also not just reopen the file with a different encoding because the user might have made changes that got saved back to disk in the default encoding (utf8). Not sure what to do here, maybe show a notification when we detect this case...

**Comment by bddali** [comment]
I have used jEdit for a few years and it does two things that might be usable workarounds in this issue:

1. You can run jEdit in "server mode", it starts when you log on and runs in the background. If VSCode did that the correct encoding would be applied to all files opened.
2. You can add a comment to the file, either in the first 10 or last 10 lines, that instructs jEdit to use a specific encodint, i e "# :encoding=CP850:".

**Comment by sandy081** [comment]
@bpasero This is a dup of https://github.com/Microsoft/vscode/issues/39084

**Comment by bpasero** [comment]
@sandy081 wow, how did I not see that...

Thanks!
