### ISSUE TITLE
Add badgen.net to trusted badge providers

### ISSUE THREAD

**Issue by gkalpak** [Microsoft/vscode#57079]
Please consider adding [badgen.net](https://badgen.net/) (and [flat.badgen.net](https://flat.badgen.net/)) to [trusted badge providers](https://code.visualstudio.com/docs/extensionAPI/extension-manifest#_approved-badges).

##
I prefer using [badgen.net](https://badgen.net/) instead of the individual badge providers (Travis, AppVeyor, etc.) for configurability and consistency across badges. I'm using it in [gkalpak.aio-docs-utils](https://marketplace.visualstudio.com/items?itemName=gkalpak.aio-docs-utils#overview).
</sub>

**Comment by gkalpak** [comment]
No, it is not a duplicate.

**Comment by gkalpak** [comment]
:tada:

**Comment by gkalpak** [comment]
Not sure what you mean by "actually publish it", but I'm sure you know better :grin:

**Comment by octref** [comment]
@gkalpak There's a SVG whitelist in vsce tool, which is used for publishing all packages to marketplace.

**Comment by joaomoreno** [comment]
@octref @mjbvz There are 3 places to update when a new badge domain comes along: distro, vsce and documentation. I've updated all 3 now. You can always forward these requests to me.
