### ISSUE TITLE
Weird loading bar keeps getting around 

### ISSUE THREAD

**Issue by HasnainAshfaq** [Microsoft/vscode#57075]
Issue Type: <b>Bug</b>

I have a weird problem. Whenever I am working, after 20 mins or so I get a loading bar on top. Which keeps loadng forever. I have no idea if its an extension or so. Posted this on Twitter, I was told report it here because it seems like a rendering problem.
Details: https://twitter.com/auchenberg/status/1031666368003764224

![image](https://user-images.githubusercontent.com/900690/44520469-348f1200-a6d0-11e8-869b-9b042126463b.png)

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:31:26.156Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 3, 2|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
EditorConfig|Edi|0.12.4
html-snippets|abu|0.2.1
vscode-css-formatter|aes|1.0.1
vscode-color|ans|0.4.5
vscode-database|baj|1.5.2
vscode-custom-css|be5|2.7.1
vscode-intelephense-client|bme|0.8.8
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.4.12
es7-react-js-snippets|dsz|1.8.5
vscode-html-css|ecm|0.2.0
vscode-npm-script|eg2|0.3.5
vscode-great-icons|emm|2.1.41
react-native-react-redux|EQu|1.9.1
prettier-vscode|esb|1.6.1
php-debug|fel|1.12.4
php-intellisense|fel|2.3.3
php-pack|fel|1.0.2
auto-rename-tag|for|0.0.15
beautify|Hoo|1.3.2
ftp-simple|hum|0.6.7
classic-asp|ili|0.0.4
java-properties|ith|0.0.2
jkformat|jas|1.0.6
vscode-browser-sync|jas|1.3.1
Angular2|joh|6.1.4
php-cs-fixer|jun|0.1.84
ng-bootstrap-snippets|ktr|1.0.0
font-awesome-codes-html|med|0.0.7
python|ms-|2018.7.1
mono-debug|ms-|0.15.8
vsliveshare|ms-|0.3.535
vetur|oct|0.12.6
laravel-blade|one|1.18.0
laravel-extension-pack|one|0.4.0
laravel5-snippets|one|1.5.0
vscode-docker|Pet|0.1.0
vscode-css-peek|pra|2.1.0
laravel-artisan|rya|0.0.21
laravel-5-snippets|sac|2.0.1
html5-boilerplate|sid|1.0.3
ayu|tea|0.15.0
wordpress-snippet|tun|1.1.5
jinja|who|0.0.8

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.
