### ISSUE TITLE
User installer displays blocky / corrupted VScode logo

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/vscode#57071]
The installer used for `VSCodeUserSetup-x64-1.26.1.exe` has some mild graphics corruptions:

![image](https://user-images.githubusercontent.com/172594/44516131-2800be80-a6bc-11e8-9647-11d7f2a75fd5.png)

![image](https://user-images.githubusercontent.com/172594/44516142-318a2680-a6bc-11e8-9906-34a5bf370bfb.png)

**Comment by riptide-dev** [comment]
@mikemaccana - the latest version is:
Version: 1.27.2 (user setup)
Commit: f46c4c469d6e6d8c46f268d1553c5dc4b475840f
Date: 2018-09-12T16:17:45.060Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

![image](https://user-images.githubusercontent.com/36054829/45558938-1e77fb80-b80f-11e8-938b-b1b179c8bcef.png)


I *was* able to repro this on a test VM (Win 10 Pro, all updates) with janky display settings:
![from vm](https://user-images.githubusercontent.com/36054829/45559112-96debc80-b80f-11e8-8111-ab0757ccc2f2.png)

However, when I installed on my local machine: Win 10 Pro, all updates, using the NATIVE display settings:
![image](https://user-images.githubusercontent.com/36054829/45559163-b83fa880-b80f-11e8-8a08-f99c86803f7a.png)

It looked fine.

This is probably less of a _bug_ then it is a local display issue.

**Comment by mikemaccana** [comment]
I can repro it using recommended resolution, zoom level, and size on Surface Go hardware released two weeks ago, using the current 64 bit Windows 10 `.\VSCodeUserSetup-x64-1.26.1.exe`:

![image](https://user-images.githubusercontent.com/172594/45578975-79940780-b87c-11e8-833d-f2bb9273dfba.png)

**Comment by joeyfoo** [comment]
This can be reproduced on any display with scaling set above 100%. 

High-DPI images for the installation wizards are currently [not provided in the Inno Setup script](https://github.com/Microsoft/vscode/blob/4c963c08950f9c4b5623f4064f671967f13cd4ea/build/win32/code.iss#L22). InnoSetup does have [support for specifying alternative bitmaps for other DPI settings](http://www.jrsoftware.org/ishelp/index.php?topic=setup_wizardimagefile). 

As this issue involves VS Code's logo (which is not open source), fully fixing this issue will probably require adding high-DPI bitmaps to a non-public repository.

**Comment by joaomoreno** [comment]
I believe this is already fixed.
