### ISSUE TITLE
Usability problems in error popups

### ISSUE THREAD

**Issue by tetsuo** [Microsoft/vscode#57088]
* Error popup screens are too small
* Basically you interact with a fixed size window only by moving your mouse cursor, there is no way to keep them on the screen or change the size of the window, which is kind of weird since those popups are like one of the most important tools for writing TypeScript code
* Scrolling the text inside popups is painful
* Useful error messages are truncated by default. That'd be better if you can put a small "More information"  button in the bottom instead. I don't really understand the reasoning behind this, you truncate the text in a random manner, it's not like that you have two different formats for describing errors. If I disable `noErrorTruncation` (which is disabled by default) I don't get any useful information from this. If I enable it, error message is not readable anymore.

**Comment by joaomoreno** [comment]
Error popups support full Markdown. This requires adoption across extensions.

**Comment by tetsuo** [comment]
Thanks for your reply, @joaomoreno ! That's great to hear, I didn't know those small popups were also customizable.

I've realized that if you click on them, the border becomes highlighted and it stays on the screen even if you press any keys, which makes it possible to take screenshots on Macos using cmd+shift combo.

* Text truncation also works fine to some extent, but it becomes difficult to read the TypeScript compiler's output text (which is the line that starts with `[ts]` on the upper half of the popup) if you use too many union types and overloaded signatures and etc. Not sure if there's an easy way to replace the default vscode tsc with a wrapper of mine, so I can filter the original tsc output and pipe better formatted text into error screens.

* Maybe you can allow resizing the popup screen when you click on it? Keyboard events are already ignored in that stage, so you're not in the editing mode anymore. Why not add some fancy features while you're there?

**Comment by mjbvz** [comment]
I believe this was addressed by #67076. The error hover now expands to be wider and there's a button to open the inline error text
