### ISSUE TITLE
The regex in tmLanguage definition file cannot correctly match Unicode characters

### ISSUE THREAD

**Issue by gjy1992** [Microsoft/vscode#5708]
- VSCode Version:1.0.0
- OS Version:Windows 10 professional (10.0.10586.0)

Steps to Reproduce:

1. Create a new colorization extension, and set the patterns as [\u0080-\uffff]
2. debug it.

The result is:
![qq 20160424113017](https://cloud.githubusercontent.com/assets/5539385/14765355/6d6ced18-0a10-11e6-83b3-c024282ae31d.png)

While if I search it in editor itself, the result looks correct.
![qq 2](https://cloud.githubusercontent.com/assets/5539385/14765357/6d9e2efa-0a10-11e6-93b7-cc7e6faefe56.png)

**Comment by alexandrudima** [comment]
@gjy1992 The colorization is based on TextMate grammars, which were built and defined by TextMate using the oniguruma regex library. When we colorize, we use the oniguruma regexes to evaluate text. Syntax at https://github.com/kkos/oniguruma/blob/master/doc/RE

**Comment by gjy1992** [comment]
OK, thank you.
