### ISSUE TITLE
Can't create workspace with same name as a folder

### ISSUE THREAD

**Issue by ricosuave73** [Microsoft/vscode#57081]
Issue Type: <b>Bug</b>

Steps to reproduce:
Open a folder
Select "Save Workspace As..."
Navigate to a folder to save your workspace to
If there is a folder named "release" and you name your workspace "release", the workspace isn't saved as "release.code-workspace". Instead, the requester goes into the "release" folder

Expected result:
It should be possible to save a workspace to a location that has a folder with the name of your intended workspace name.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vbscript|Dar|1.0.4
classic-asp|ili|0.0.4
mssql|ms-|1.4.0
python|ms-|2018.7.1
debugger-for-chrome|msj|4.8.2

</details>

**Comment by bpasero** [comment]
This seems to be standard windows behaviour, I can reproduce the same when I use notepad.exe.
