### ISSUE TITLE
TAB issue in text editor

### ISSUE THREAD

**Issue by Th30wl** [Microsoft/vscode#57085]
Issue Type: <b>Bug</b>

When text is selected pressing TAB does not indent the selected text. In fact text editor loses focus and you focus different UI elements (buttons etc.)

Steps to reproduce:
1. add a code file (cpp in my case)
2. write some code :)
3. select some text
4. press TAB and code editor will lose focus 
  (I can't see what is focused on the first press but by continuing to press you will cycle throug activity bar buttons anf file tabs)

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-tfs|iva|0.6.0
csharpextensions|jch|1.3.0
cpptools|ms-|0.18.1
csharp|ms-|1.15.2
team|ms-|1.136.0
platformio-ide|pla|0.17.5
vscode-arduino|vsc|0.2.20

</details>

**Comment by ichbineinNerd** [comment]
that is not all of the steps needed to reproduce this issue, it works fine for me with those steps and the same version. I didn't check the add-ons, does it happen without them?

**Comment by Th30wl** [comment]
By bad. Somehow I have enabled the 'TAB moves focus' option by mistake.. :/
