### ISSUE TITLE
Display name conda environment

### ISSUE THREAD

**Issue by JackCaster** [Microsoft/vscode#57080]
Is it possible to add the name of the conda environment in use?

Right now, we can select the conda environment, but VSCode displays only the Python version (see below).
![image](https://user-images.githubusercontent.com/18400141/44522464-eaf5f580-a6d6-11e8-95ea-c1300d1a1a60.png)
I would like to get something like this:
![image](https://user-images.githubusercontent.com/18400141/44522665-8c7d4700-a6d7-11e8-9fec-89b2c0fe8822.png)

**Comment by rebornix** [comment]
@JackCaster I think the status bar items are contributed by some extension?

**Comment by JackCaster** [comment]
Oh right. It should be the [VSCode Python extension](https://github.com/Microsoft/vscode-python). I will post there instead.
