### ISSUE TITLE
Tree filtering: support recursive filtering

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#57089]
* have a tree
* have a filter that marks a child as visible but not its parent
* 😢 the children aren't visible...

there should be a filter that starts at the (visible) leafs and that rolls up the visibility state.

**Comment by joaomoreno** [comment]
Implemented in the new tree: https://github.com/Microsoft/vscode/blob/10b383c911417445aa073d03bd7cde83d41b67b4/src/vs/base/browser/ui/tree/tree.ts#L25

Refer to MarkersPanel for usage of the `ObjectTree`. I will showcase this for everyone so they know what they can use.

**Comment by joaomoreno** [comment]
Verification: the problems panel uses this feature when you filter it in the input box.
