### ISSUE TITLE
'git for Windows' won't alow user setup for vscode

### ISSUE THREAD

**Issue by mikemaccana** [Microsoft/vscode#57091]
See screenshot: 
![image](https://user-images.githubusercontent.com/172594/44531171-00275000-a6e8-11e8-9cfe-422cc9d3c8b9.png)

Ideally it might be better to ditch 'git for Windows' - bash etc already come with Windows 10.

**Comment by mikemaccana** [comment]
PS. If it's not obvious from the screenshot, it doesn't see the new user setup as being installed.

**Comment by Bill-Stewart** [comment]
Isn't this a problem for the git installer rather than vscode?
