### ISSUE TITLE
VS Code 1.26.1 recognizing 'htm' extension as opposed to 'html' extension for html docs

### ISSUE THREAD

**Issue by tpye** [Microsoft/vscode#57097]
Currently, my version of VS Code will not identify html documents as such, unless the file extension is set to 'htm' not html.

Trevor

**Comment by aeschli** [comment]
I can't reproduce, we also have not made any changes in that area. Can run code with extensions disabled and see if an extension causes that?
Also check the `"files.associations"` setting to see if `*.html` is associated with a different language.
