### ISSUE TITLE
VSCode not resolving index.js when using custom path aliases

### ISSUE THREAD

**Issue by Telokis** [Microsoft/vscode#57096]
Issue Type: <b>Bug</b>

## Situation

I am using the `jsconfig.json` file to specify custom aliases for my project like so:

```json
{
    "compilerOptions": {
        "target": "es6",
        "baseUrl": ".",
        "module": "commonjs",
        "paths": {
            "$config/*": ["./config/*"],
            "$models/*": ["./src/models/*"],
            "$helpers/*": ["./src/helpers/*"]
        }
    },
    "exclude": ["**/node_modules/*", "build", "coverage"]
}
```

In `app.js`, I try to do the following:

```js
const models = require("$models"); // resolved to "src/models/index.js"

const mediaType = new models.MediaType();
// ...
```

There is a file `src/models/index.js` which is imported and contains this:

```js
module.exports = {
    MediaType: require("./Mediatype"),
    // ...
};
```

## What happens

Inside the `app.js` file, the `require` clause works and vscode understands that it uses an alias as shown on this screenshot:
![image](https://user-images.githubusercontent.com/6382729/44538427-89974c00-a701-11e8-80f1-3e678bad15cc.png)

However, I have no intellisense on the variable `models` whatsoever. If I do `models.<Ctrl+Space>` I get a list of non relevant things showing every symbol available in the current file.

Moreover, if I put my cursor on the import and press F12 (Go to) it simply says that no definition is found.
![image](https://user-images.githubusercontent.com/6382729/44538536-df6bf400-a701-11e8-93b5-0fa4402723a5.png)

**Note:** If I explicitly use `const models = require("$models/index");`, everything works exactly as expected.

## What should happen

```js
const models = require("$models");
```
and
```js
const models = require("$models/index");
```
should both be equivalent if the former resolves to a directory.

## Specs

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.74GB (6.05GB free)|
|Process Argv|C:\Users\Telokis\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.59
vscode-eslint|dba|1.5.0
vscode-new-file|dku|4.0.2
es7-react-js-snippets|dsz|1.8.5
gitlens|eam|8.5.6
prettier-vscode|esb|1.6.1
code-runner|for|0.9.4
code-guid|jam|1.0.1
docthis|joe|0.7.1
csharp|ms-|1.15.2
sublime-keybindings|ms-|4.0.0
vscode-icons|rob|7.25.0
partial-diff|ryu|1.3.0
code-settings-sync|Sha|3.0.0
vscode-nginx|sha|0.5.0
quokka-vscode|Wal|1.0.140

</details>

**Comment by Telokis** [comment]
@mjbvz Excuse-me for tagging you but is this issue going to be resolved? Thanks!

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#27579
