### ISSUE TITLE
Code crashed and the window won't close.

### ISSUE THREAD

**Issue by vm95604b** [Microsoft/vscode#57107]
- VSCode Version: I think 1.26. I downloaded it today 8/23/18
- OS Version: 10.13.5

Steps to Reproduce:

1. Can't reproduce but I found a thread with the same problem that was closed in May due to inactivity.
2.

Does this issue occur when all extensions are disabled?: Yes/No
I had only the C++ extension installed when it happened. This is my crash report...

Process:               Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin [96480]
Path:                  /Users/USER/*/Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin
Identifier:            Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        Microsoft.VSCode.CPP.Extension.darwin [96467]
Responsible:           Electron [95879]
User ID:               501

Date/Time:             2018-08-23 15:45:02.113 -0400
OS Version:            Mac OS X 10.13.5 (17F77)
Report Version:        12
Anonymous UUID:        38D3F295-45B4-7184-4E3E-70657B5E2E66

Sleep/Wake UUID:       99F128A7-C50E-438A-881A-D8EA881FE721

Time Awake Since Boot: 510000 seconds
Time Since Wake:       5100 seconds

System Integrity Protection: enabled

Crashed Thread:        7

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000000010000007a

VM Regions Near 0x10000007a:
--> 
    __TEXT                 000000010027e000-0000000100725000 [ 4764K] r-x/rwx SM=COW  /Users/USER/*/*.darwin

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff5c353a1e __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff5c51c589 _pthread_cond_wait + 732
2   Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x000000010064ded5 neosmart::WaitForMultipleEvents(neosmart::neosmart_event_t_**, int, bool, unsigned long long, int&) + 1077
3   Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x000000010064c055 microsoft::vc::alertable_event::wait_for_multiple(microsoft::vc::alertable_event**, unsigned long, bool, unsigned int) + 325
4   Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x00000001006422a3 comm_server::wait_for_requests() + 99
5   Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x00000001002a46cc main + 332
6   libdyld.dylib                 	0x00007fff5c203015 start + 1

Thread 1:
0   libsystem_kernel.dylib        	0x00007fff5c353a1e __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff5c51c589 _pthread_cond_wait + 732
2   Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x000000010064ded5 neosmart::WaitForMultipleEvents(neosmart::neosmart_event_t_**, int, bool, unsigned long long, int&) + 1077
3   Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x000000010064c055 microsoft::vc::alertable_event::wait_for_multiple(microsoft::vc::alertable_event**, unsigned long, bool, unsigned int) + 325
4   Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x0000000100644d41 microsoft::vc::thread_pool::do_work(unsigned long) + 529
5   Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x0000000100645951 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, microsoft::vc::thread_pool::add_threads()::$_1> >(void*) + 49
6   libsystem_pthread.dylib       	0x00007fff5c51b661 _pthread_body + 340
7   libsystem_pthread.dylib       	0x00007fff5c51b50d _pthread_start + 377
8   libsystem_pthread.dylib       	0x00007fff5c51abf9 thread_start + 13

Thread 2:
0   libsystem_kernel.dylib        	0x00007fff5c353a1e __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff5c51c589 _pthread_cond_wait + 732
2   Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x000000010064ded5 neosmart::WaitForMultipleEvents(neosmart::neosmart_event_t_**, int, bool, unsigned long long, int&) + 1077
3   Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x000000010064c055 microsoft::vc::alertable_event::wait_for_multiple(microsoft::vc::alertable_event**, unsigned long, bool, unsigned int) + 325
4   Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x0000000100644d41 microsoft::vc::thread_pool::do_work(unsigned long) + 529
5   Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x0000000100645951 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, microsoft::vc::thread_pool::add_threads()::$_1> >(void*) + 49
6   libsystem_pthread.dylib       	0x00007fff5c51b661 _pthread_body + 340
7   libsystem_pthread.dylib       	0x00007fff5c51b50d _pthread_start + 377
8   libsystem_pthread.dylib       	0x00007fff5c51abf9 thread_start + 13

Thread 3:
0   libsystem_kernel.dylib        	0x00007fff5c353a1e __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff5c51c589 _pthread_cond_wait + 732
2   Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x000000010064ded5 neosmart::WaitForMultipleEvents(neosmart::neosmart_event_t_**, int, bool, unsigned long long, int&) + 1077
3   Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x000000010064c055 microsoft::vc::alertable_event::wait_for_multiple(microsoft::vc::alertable_event**, unsigned long, bool, unsigned int) + 325
4   Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x0000000100644d41 microsoft::vc::thread_pool::do_work(unsigned long) + 529
5   Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x0000000100645951 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, microsoft::vc::thread_pool::add_threads()::$_1> >(void*) + 49
6   libsystem_pthread.dylib       	0x00007fff5c51b661 _pthread_body + 340
7   libsystem_pthread.dylib       	0x00007fff5c51b50d _pthread_start + 377
8   libsystem_pthread.dylib       	0x00007fff5c51abf9 thread_start + 13

Thread 4:
0   libsystem_kernel.dylib        	0x00007fff5c353a1e __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff5c51c589 _pthread_cond_wait + 732
2   libc++.1.dylib                	0x00007fff5a15bcb0 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
3   Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x0000000100564c88 edge::an_edge_translation_unit_impl::compile_declaration(edge::snapshot_session const*, a_canonicalized_file_name, wchar_t const*, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, a_declaration_context const&, a_tracked_region_kind, a_region_namespace_info const&, bool, bool, bool, bool*, edge::query_action_data&) + 680
4   Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x000000010056169e edge::scoped_query_manager::check_and_compile(edge::file_position const&, edge::file_position const&, edge::file_position const&, bool, bool) + 1022
5   Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x00000001005651fd edge::scoped_query_manager::get_trees_overlapping_span(a_canonicalized_file_name, unsigned long, unsigned long, int, edge::tree_query_result_builder*) + 221
6   Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x0000000100592c0e edge::intellisense_operation::scope_at_cursor(edge::member_selection_entry**) + 174
7   Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x0000000100593d62 edge::intellisense_operation::get_auto_complete_members(edge::list<edge::symbol*>*, edge::intellisense_operation::member_list_kind, bool, bool&, bool&, bool&) + 514
8   Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x00000001002983cd std::__1::__function::__func<edge_intellisense_server_impl::handle_completion(microsoft::cpp::intellisense::CompletionRequest const&)::'lambda'(edge::intellisense_operation&, bool&), std::__1::allocator<edge_intellisense_server_impl::handle_completion(microsoft::cpp::intellisense::CompletionRequest const&)::'lambda'(edge::intellisense_operation&, bool&)>, void (edge::intellisense_operation&, bool&)>::operator()(edge::intellisense_operation&, bool&) + 45
9   Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x0000000100297c93 void edge_intellisense_operation::perform_isense_operation<bool>(wchar_t const*, microsoft::cpp::intellisense::DocumentPosition const&, std::__1::function<void (edge::intellisense_operation&, bool&)>, bool&, edge::allocator*) + 323
10  Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x0000000100282b6b edge_intellisense_server_impl::handle_completion(microsoft::cpp::intellisense::CompletionRequest const&) + 363
11  Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x00000001002a7b0e work_queue::worker_proc() + 190
12  Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x0000000100646178 std::__1::__function::__func<microsoft::vc::thread_pool::enqueue(std::__1::function<void ()>, std::__1::future<void>*)::$_2, std::__1::allocator<microsoft::vc::thread_pool::enqueue(std::__1::function<void ()>, std::__1::future<void>*)::$_2>, void ()>::operator()() + 24
13  Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x0000000100644e62 microsoft::vc::thread_pool::do_work(unsigned long) + 818
14  Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x0000000100645951 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, microsoft::vc::thread_pool::add_threads()::$_1> >(void*) + 49
15  libsystem_pthread.dylib       	0x00007fff5c51b661 _pthread_body + 340
16  libsystem_pthread.dylib       	0x00007fff5c51b50d _pthread_start + 377
17  libsystem_pthread.dylib       	0x00007fff5c51abf9 thread_start + 13

Thread 5:
0   libsystem_kernel.dylib        	0x00007fff5c353a1e __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff5c51c589 _pthread_cond_wait + 732
2   Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x000000010064d9e4 neosmart::UnlockedWaitForEvent(neosmart::neosmart_event_t_*, unsigned long long) + 180
3   Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x000000010064da5f neosmart::WaitForEvent(neosmart::neosmart_event_t_*, unsigned long long) + 63
4   Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x000000010064befe microsoft::vc::alertable_event::wait(unsigned int) + 30
5   Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x00000001006457de std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, microsoft::vc::thread_pool::thread_pool()::$_0> >(void*, void*) + 94
6   libsystem_pthread.dylib       	0x00007fff5c51b661 _pthread_body + 340
7   libsystem_pthread.dylib       	0x00007fff5c51b50d _pthread_start + 377
8   libsystem_pthread.dylib       	0x00007fff5c51abf9 thread_start + 13

Thread 6:
0   libsystem_kernel.dylib        	0x00007fff5c35514a read + 10
1   Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x000000010064c602 async_pipe_nix::read_sync_impl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) + 50
2   Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x000000010064c755 async_pipe_nix::read_thread_proc() + 149
3   Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x000000010064d1ed void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, async_pipe_nix::ensure_read_thread()::$_0> >(void*) + 45
4   libsystem_pthread.dylib       	0x00007fff5c51b661 _pthread_body + 340
5   libsystem_pthread.dylib       	0x00007fff5c51b50d _pthread_start + 377
6   libsystem_pthread.dylib       	0x00007fff5c51abf9 thread_start + 13

Thread 7 Crashed:
0   Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x0000000100371a90 scan_expr_full + 7776
1   Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x000000010037814d scan_expr_into_new_init_component + 77
2   Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x000000010036aaca scan_expr_list + 378
3   Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x000000010036b502 scan_call_arguments + 306
4   Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x000000010039e4ad scan_dependent_type_parenthesized_initializer + 109
5   Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x000000010034186b initializer + 2379
6   Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x000000010052b279 template_declaration + 14169
7   Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x000000010051a96f template_or_specialization_declaration + 2527
8   Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x0000000100519eda template_directive_or_declaration + 938
9   Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x0000000100335c80 scan_nonmember_declaration + 1264
10  Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x000000010033b054 declaration + 212
11  Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x000000010059b828 compile_fragment((anonymous namespace)::a_fragment_buffer const&, a_canonicalized_file_name, unsigned long, unsigned long, unsigned long, bool, a_declaration_context const&, a_region_namespace_info const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, bool, bool, bool, bool*) + 2872
12  Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x0000000100599819 end_of_parse_notification + 489
13  Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x000000010053caa6 process_translation_unit + 838
14  Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x00000001002bb539 cfe_main + 121
15  Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x000000010055ee89 cfe_main_exception_handler + 9
16  Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x00000001002bb629 edg_main + 9
17  Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x00000001005550c4 edge_compiler_main(int, char const**) + 7700
18  Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x0000000100599ddd preparse(int, char const**, a_scout_store*, edge::translation_unit*) + 237
19  Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x000000010056c03c a_compiler_thread::compiler_thread_routine(a_compiler_thread*) + 76
20  Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin	0x00000001005912cc void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(a_compiler_thread*), a_compiler_thread*> >(void*) + 44
21  libsystem_pthread.dylib       	0x00007fff5c51b661 _pthread_body + 340
22  libsystem_pthread.dylib       	0x00007fff5c51b50d _pthread_start + 377
23  libsystem_pthread.dylib       	0x00007fff5c51abf9 thread_start + 13

Thread 7 crashed with X86 Thread State (64-bit):
  rax: 0x0000000100000000  rbx: 0x000000010087c640  rcx: 0x000000010087c77c  rdx: 0x000000010087d5ff
  rdi: 0x00007000048e23e0  rsi: 0x0000000000000000  rbp: 0x00007000048e2750  rsp: 0x00007000048e2140
   r8: 0x0000000000000017   r9: 0x000000010087e278  r10: 0x0000000000000000  r11: 0x000000010087c460
  r12: 0x00000001003752c8  r13: 0x00007000048e25b0  r14: 0x00007000048e23e0  r15: 0x000000010087c360
  rip: 0x0000000100371a90  rfl: 0x0000000000010206  cr2: 0x000000010000007a
  
Logical CPU:     2
Error Code:      0x00000004
Trap Number:     14

Binary Images:
       0x10027e000 -        0x100724ff7 +Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin (0) <EE2AEF3B-6E6F-3E1B-B42C-41FD5FB8A443> /Users/USER/*/Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin
       0x108515000 -        0x10855f9df  dyld (551.3) <AFAB4EFA-7020-34B1-BBEF-0F26C6D3CA36> /usr/lib/dyld
    0x7fff59964000 -     0x7fff59997ff7  libclosured.dylib (551.3) <DC3DA678-9C40-339C-A9C6-32AB74FCC682> /usr/lib/closure/libclosured.dylib
    0x7fff59e9e000 -     0x7fff59e9fffb  libSystem.B.dylib (1252.50.4) <CDA73F3E-2A7D-3354-818A-580317A03255> /usr/lib/libSystem.B.dylib
    0x7fff5a155000 -     0x7fff5a1abfff  libc++.1.dylib (400.9) <7D3DACCC-3804-393C-ABC1-1A580FD00CB6> /usr/lib/libc++.1.dylib
    0x7fff5a1ac000 -     0x7fff5a1d0ff7  libc++abi.dylib (400.8.2) <EF5E37D7-11D9-3530-BE45-B986612D13E2> /usr/lib/libc++abi.dylib
    0x7fff5b5d8000 -     0x7fff5b9c93b7  libobjc.A.dylib (723) <BEEA51E2-1C4D-3672-87F6-F267B4AC6221> /usr/lib/libobjc.A.dylib
    0x7fff5c099000 -     0x7fff5c09dff7  libcache.dylib (80) <092479CB-1008-3A83-BECF-E115F24D13C1> /usr/lib/system/libcache.dylib
    0x7fff5c09e000 -     0x7fff5c0a8ff3  libcommonCrypto.dylib (60118.50.1) <029F5985-9B6E-3DCB-9B96-FD007678C6A7> /usr/lib/system/libcommonCrypto.dylib
    0x7fff5c0a9000 -     0x7fff5c0b0fff  libcompiler_rt.dylib (62) <968B8E3F-3681-3230-9D78-BB8732024F6E> /usr/lib/system/libcompiler_rt.dylib
    0x7fff5c0b1000 -     0x7fff5c0baffb  libcopyfile.dylib (146.50.5) <3885083D-50D8-3EEC-B481-B2E605180D7F> /usr/lib/system/libcopyfile.dylib
    0x7fff5c0bb000 -     0x7fff5c140fff  libcorecrypto.dylib (562.50.17) <67007279-24E1-3F30-802D-A55CD5C27946> /usr/lib/system/libcorecrypto.dylib
    0x7fff5c1c8000 -     0x7fff5c201ff7  libdispatch.dylib (913.60.2) <414353F7-3A9F-3091-AFCE-E66F74687D5D> /usr/lib/system/libdispatch.dylib
    0x7fff5c202000 -     0x7fff5c21fff7  libdyld.dylib (551.3) <CF59A5A5-288B-30E6-BD42-9056B4E4139A> /usr/lib/system/libdyld.dylib
    0x7fff5c220000 -     0x7fff5c220ffb  libkeymgr.dylib (28) <E34E283E-90FA-3C59-B48E-1277CDB9CDCE> /usr/lib/system/libkeymgr.dylib
    0x7fff5c22e000 -     0x7fff5c22eff7  liblaunch.dylib (1205.60.9) <4B2943A9-0994-3E8B-94B8-98DA9CED0021> /usr/lib/system/liblaunch.dylib
    0x7fff5c22f000 -     0x7fff5c233ffb  libmacho.dylib (906) <1902A611-081A-3452-B11E-EBD1B166E831> /usr/lib/system/libmacho.dylib
    0x7fff5c234000 -     0x7fff5c236ff3  libquarantine.dylib (86) <26C0BA22-8F93-3A07-9A4E-C8D53D2CE42E> /usr/lib/system/libquarantine.dylib
    0x7fff5c237000 -     0x7fff5c238ff3  libremovefile.dylib (45) <711E18B2-5BBE-3211-A916-56740C27D17A> /usr/lib/system/libremovefile.dylib
    0x7fff5c239000 -     0x7fff5c250fff  libsystem_asl.dylib (356.50.1) <3B24F2D1-B578-359D-ADB2-0ED19A364C38> /usr/lib/system/libsystem_asl.dylib
    0x7fff5c251000 -     0x7fff5c251fff  libsystem_blocks.dylib (67) <17303FDF-0D2D-3963-B05E-B4DF63052D47> /usr/lib/system/libsystem_blocks.dylib
    0x7fff5c252000 -     0x7fff5c2dbff7  libsystem_c.dylib (1244.50.9) <1187BFE8-4576-3247-8177-481554E1F9E7> /usr/lib/system/libsystem_c.dylib
    0x7fff5c2dc000 -     0x7fff5c2dfffb  libsystem_configuration.dylib (963.50.8) <DF6B5287-203E-30CB-9947-78DF446C72B8> /usr/lib/system/libsystem_configuration.dylib
    0x7fff5c2e0000 -     0x7fff5c2e3ffb  libsystem_coreservices.dylib (51) <486000D3-D8CB-3BE7-8EE5-8BF380DE6DF7> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff5c2e4000 -     0x7fff5c2e5fff  libsystem_darwin.dylib (1244.50.9) <09C21A4A-9EE0-388B-A9D9-DFF8F6758791> /usr/lib/system/libsystem_darwin.dylib
    0x7fff5c2e6000 -     0x7fff5c2ecff7  libsystem_dnssd.dylib (878.50.17) <C12E2075-3E4B-3187-8B3B-F6150FCB82E0> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff5c2ed000 -     0x7fff5c336ff7  libsystem_info.dylib (517.30.1) <AB634A98-B8AA-3804-8436-38261FC8EC4D> /usr/lib/system/libsystem_info.dylib
    0x7fff5c337000 -     0x7fff5c35dff7  libsystem_kernel.dylib (4570.61.1) <D7F2010A-EA32-3F62-90DE-85E3C5CC3065> /usr/lib/system/libsystem_kernel.dylib
    0x7fff5c35e000 -     0x7fff5c3a9fcb  libsystem_m.dylib (3147.50.1) <8CFB51C9-B422-3379-8552-064C63943A23> /usr/lib/system/libsystem_m.dylib
    0x7fff5c3aa000 -     0x7fff5c3c9fff  libsystem_malloc.dylib (140.50.6) <7FD43735-9DDD-300E-8C4A-F909A74BDF49> /usr/lib/system/libsystem_malloc.dylib
    0x7fff5c3ca000 -     0x7fff5c4faff7  libsystem_network.dylib (1229.60.3) <D17B38B7-BE5D-3A9C-9257-F045E7647E8A> /usr/lib/system/libsystem_network.dylib
    0x7fff5c4fb000 -     0x7fff5c505ffb  libsystem_networkextension.dylib (767.60.1) <1745C91F-9AF0-357D-BD40-34451A2D6A5E> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff5c506000 -     0x7fff5c50fff3  libsystem_notify.dylib (172) <08012EC0-2CD2-34BE-BF93-E7F56491299A> /usr/lib/system/libsystem_notify.dylib
    0x7fff5c510000 -     0x7fff5c517ff7  libsystem_platform.dylib (161.50.1) <6355EE2D-5456-3CA8-A227-B96E8F1E2AF8> /usr/lib/system/libsystem_platform.dylib
    0x7fff5c518000 -     0x7fff5c523fff  libsystem_pthread.dylib (301.50.1) <0E51CCBA-91F2-34E1-BF2A-FEEFD3D321E4> /usr/lib/system/libsystem_pthread.dylib
    0x7fff5c524000 -     0x7fff5c527fff  libsystem_sandbox.dylib (765.60.1) <E5DE4B2F-202D-3474-9F08-7CAB1501D411> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff5c528000 -     0x7fff5c529ff3  libsystem_secinit.dylib (30) <DE8D14E8-A276-3FF8-AE13-77F7040F33C1> /usr/lib/system/libsystem_secinit.dylib
    0x7fff5c52a000 -     0x7fff5c531ff7  libsystem_symptoms.dylib (820.60.2) <9C9E82AB-D1EE-3EC7-B20E-44338CE092AC> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff5c532000 -     0x7fff5c545fff  libsystem_trace.dylib (829.50.17) <6568D68B-1D4C-38EE-90A9-54821D6403C0> /usr/lib/system/libsystem_trace.dylib
    0x7fff5c547000 -     0x7fff5c54cff7  libunwind.dylib (35.3) <BEF3FB49-5604-3B5F-82B5-332B80023AC3> /usr/lib/system/libunwind.dylib
    0x7fff5c54d000 -     0x7fff5c57afff  libxpc.dylib (1205.60.9) <16132357-B57A-35F5-B165-487D3F759F45> /usr/lib/system/libxpc.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 2
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 26521937
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=209.2M resident=0K(0%) swapped_out_or_unallocated=209.2M(100%)
Writable regions: Total=163.1M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=163.1M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Kernel Alloc Once                    8K        2 
MALLOC                           150.2M       20 
MALLOC guard page                   16K        5 
STACK GUARD                       56.0M        9 
Stack                             11.6M       16 
__DATA                            3832K       43 
__LINKEDIT                       195.3M        4 
__TEXT                            13.9M       42 
shared memory                       12K        4 
===========                     =======  ======= 
TOTAL                            430.7M      136

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode-cpptools/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+crash
