### ISSUE TITLE
Make keyboard mappings sortable in the editor

### ISSUE THREAD

**Issue by hellerim** [Microsoft/vscode#57109]
I feel the necessity to repair the keyboard mappings in a VSCode instance which appear to be damaged. The keyboard table of https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf looks nice, but it's ordering is completely different from that shown in the VSCode keyboard mapping editor. This makes the work terribly boaring since, in addition, in VSCode the table is localized while the functions on the webpage are named in English. 
Having the possibility to order by key combination would be very helpful, and, moreover, thereby preserving the grouping by category would be phantastic.

**Comment by sandy081** [comment]
When you mean sort by key combination.. how exactly you are expecting to be sorted? Can you provide some examples?

> This makes the work terribly boaring since
Can you please provide an use case to support this?
