### ISSUE TITLE
Add code folding in markdown based on bullet point hierarchy level

### ISSUE THREAD

**Issue by youssefsharief** [Microsoft/vscode#57104]
I would like to be able to fold  markdown based on bullet point hierarchy level

![image](https://user-images.githubusercontent.com/21158003/44548818-76937480-a71f-11e8-9775-317ba26f49be.png)

**Comment by bpceee** [comment]
Hi there, nice feature to have, I have created a PR for it.

**Comment by mjbvz** [comment]
Fixed by #57899
