### ISSUE TITLE
Debug Toolbar Theme Not Updating

### ISSUE THREAD

**Issue by austin-laney** [Microsoft/vscode#57101]
- VSCode Version: 1.26.1
- OS Version: Windows 10 1709 build 16299.431

Steps to Reproduce:

1. Install theme which allows custom options bar and title bar
2. Enable `Window: Title Bar Style" in Settings and set to `custom`
3. Launch debug session and observe floating toolbar theme is not matched to rest of UI

Does this issue occur when all extensions are disabled?: Yes/No
No (themes are the extension).

**Comment by isidorn** [comment]
The issue is with the theme, please file this issue with the theme and let them know they should also customise "debugToolBar.background" and other debugToolBar colors
