### ISSUE TITLE
Jump to function beginning

### ISSUE THREAD

**Issue by acming92** [microsoft/vscode#57102]
I think it's useful provide a way to jump at the beginning of the current function, especially when the function is very long and team likes to define variable in the beginning of the function.

**Comment by waynchi** [comment]
Is there any update on this? Being able to jump to the beginning or end of functions has been pretty useful to me on emacs (C-M-a and C-M-e) and Vim.

**Comment by jrieken** [comment]
/duplicate of https://github.com/microsoft/vscode/issues/46153
