### ISSUE TITLE
Double-clicking on code doesn't select the text

### ISSUE THREAD

**Issue by dna5122** [Microsoft/vscode#57112]
Issue Type: <b>Bug</b>

Using the TSX editor to write some TypeScript code, trying to double click with the mouse on a variable name in order to select the text to use copy/paste, and the double click rarely works.  It acts like a single click, the code editor highlights all instances of that variable name in the file, but the text is not selected.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:37:28.532Z)
OS version: Windows_NT ia32 10.0.17134

**Comment by rebornix** [comment]
@dna5122  do you mind sharing some gifs to help trouble shoot?
