### ISSUE TITLE
[Extensibility] TextEditor instance got disposed if another document is opened on top of it

### ISSUE THREAD

**Issue by jeremymeng** [Microsoft/vscode#57119]
Issue Type: <b>Bug</b>

1. I have an extension that creates two Untitiled-* documents then shows them side by side at column one and column two.  I saved the two TextEditor instances so later the extension can update the contents of the two documents, instead of creating two new documents again.

![image](https://user-images.githubusercontent.com/7583839/44558067-f9eca000-a6f6-11e8-8de2-f94cff1ca161.png)

2. when the two documents are showing, if some other document window is opened in one of the column that has the focus

![image](https://user-images.githubusercontent.com/7583839/44558100-299ba800-a6f7-11e8-82b6-17c529925dac.png)

3. Now the TextEditor instance in that column does not work any more. Even the extension still can call the editor method to replace content.  The change isn't reflected in VS Code UI. The "Untitled-1" tab was expected to show code for the namespace, but previous code get stuck there.

![image](https://user-images.githubusercontent.com/7583839/44558147-64054500-a6f7-11e8-9070-f98911fb633f.png)

4. Here's the debugger showing `_disposed: true` for that instance of TextEditor
![image](https://user-images.githubusercontent.com/7583839/44558271-04f40000-a6f8-11e8-9a1d-f4bfafc34e77.png)

The relevant code is at https://github.com/icsharpcode/ilspy-vscode/blob/master/vscode-extension/src/extension.ts#L121-L158

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17741

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.76GB (15.96GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|1.4.4
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.36
vscode-firefox-debug|hbe|1.5.0
ilspy-vscode|ics|0.7.0
azurecli|ms-|0.4.2
csharp|ms-|1.15.2
Go|ms-|0.6.88
PowerShell|ms-|1.8.3
debugger-for-chrome|msj|4.8.2
debugger-for-edge|msj|1.0.2
vscode-docker|Pet|0.1.0
cordova-tools|vsm|1.4.0

</details>

**Comment by jrieken** [comment]
That is the design of editors in the API. A `TextEditor` is text document that is currently visible which in return means the editor is being disposed when not visible anymore. You can hold on to a document and open it again as (new) text editor
