### ISSUE TITLE
Reveal Active File in File Explorer doesn't work any more for files in node_modules

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#57110]
Issue Type: <b>Bug</b>

Jump to Definition takes me to the `d.ts` files in `node_modules` and I run the command `Reveal Active File in File Explorer` to reveal them. This doesn't work any more.

Just noticed that if you set `explorer.autoReveal` to true, it doesn't work either now for files in `node_modules`.

Only error I see from DevTool is:

```
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276 [Extension Host] Git extension API method 'getGitPath' is deprecated. (at c.r.value (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/git/dist/main.js:1:593175))
```

VS Code version: Code - Insiders 1.27.0-insider (07618102efdd63f09949ce54c161e7fd2a954ee8, 2018-08-23T05:12:28.997Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.65GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_11447018|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-emoji|bie|0.0.7
markdown-preview-github-styles|bie|0.1.2
vscode-eslint|dba|1.5.0
tslint|eg2|1.0.36
vsc-material-theme|Equ|2.3.0
prettier-vscode|esb|1.6.1
beautify|Hoo|1.3.2
vscode-pull-request-github|Mic|0.0.12
theme-monokai-pro-vscode|mon|1.1.8
debugger-for-chrome|msj|4.8.2
lsp-inspector|oct|0.0.1
vetur|oct|0.12.6
polacode|pnp|0.2.2
vscode-sort-json|ric|1.13.0
vscode-csstree|sme|0.7.0
language-stylus|sys|1.10.0
vim|vsc|0.16.0

(2 theme extensions excluded)

</details>

**Comment by octref** [comment]
Very strange, I cannot repro on my home laptop but I can repro consistently on work laptop.

**Comment by isidorn** [comment]
Works for me. I guess you are using the command palette action
`Reveal active file in Side Bar`
Try reproducing with all extensions disabled.
If you can still reproduce put a breakpoint [here](https://github.com/Microsoft/vscode/blob/d200e76c4902ea4904915a6511386a9bf1d981aa/src/vs/workbench/parts/files/electron-browser/fileActions.ts#L1365) and try to investigate more

**Comment by octref** [comment]
After a weekend it's not reproing on my work laptop now.
I'll keep an eye on it if it shows up again.
