### ISSUE TITLE
Flickering icons when resizing sidebar

### ISSUE THREAD

**Issue by StephanTLavavej** [Microsoft/vscode#57111]
- VSCode Version: 1.26.1 x64
- OS Version: Windows Server 2016

Steps to Reproduce:

1. Open a workspace.
2. Open the Explorer sidebar.
3. Observe that hovering over the file list in the Explorer displays icons in the Workspace header (New File, New Folder, Refresh, Collapse All). This is good.
4. Observe that hovering outside the Explorer (e.g. over an open file) causes those icons to disappear. This is also good.
5. Hover over the split between the Explorer and an open file; observe that the cursor changes to a horizontal resize cursor, and the Explorer icons are not displayed (as this isn't considered hovering over the Explorer file list). This is still good.
6. Click and hold, and drag to the left to make the Explorer sidebar narrower. **Bug:** Observe that as the mouse moves left, VSCode considers the cursor to be hovering over the file list, and displays the Workspace header icons. **Note:** This is sensitive to exactly where the resize begins (as the click target for beginning the resize is a few pixels wide). If the resize click starts very near the Explorer (to the left), then any amount of narrowing will cause the icons to appear, and they will remain visible if the mouse stops moving (while still holding the resize click). If the resize click starts closer to the open file (to the right), then the icons will appear only when the mouse is moving rapidly to the left (narrowing) and will disappear as the mouse slows. This flickering is what caught my attention.

Additionally, files in the file list will be hover-highlighted in a flickering manner, although this is somewhat more subtle.

Final note: This also occurs with the icons in the Open Editors list of the Explorer. It also occurs in other sidebars, e.g. Source Control, where the Commit/Refresh/More Actions icons are affected, so this is a general sidebar issue.

I work on MSVC and I can demonstrate this issue in person if my description is insufficient.

Suggested fix:

* While resizing the sidebar, the cursor should not be considered to be hovering over the sidebar, and icon display should be suppressed.

Does this issue occur when all extensions are disabled?: Yes. (I'm not using any extensions.)

**Comment by isidorn** [comment]
Can you pleae attach a GIF or a video which demonstraets this
Can you reproduce with latest vscode insiders https://code.visualstudio.com/insiders/
