### ISSUE TITLE
Integrated terminal

### ISSUE THREAD

**Issue by UlukDzhunsov** [Microsoft/vscode#57128]
Issue Type: <b>Bug</b>

In the new version, the integrated terminal became slow. Can you fix this ? ((

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:31:26.156Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.09GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.5.0
es7-react-js-snippets|dsz|1.8.5
gitlens|eam|8.5.6
graphql-for-vscode|kum|1.12.1
vscode-docker|Pet|0.1.0
alphabetical-sorter|ue|2.0.1

</details>

**Comment by Tyriar** [comment]
Duplicate: https://github.com/Microsoft/vscode/issues/56628

This will be fixed in 1.27, you can also use Insiders now https://code.visualstudio.com/insiders/
