### ISSUE TITLE
Show current Markdown section as a breadcrumb

### ISSUE THREAD

**Issue by garyking** [Microsoft/vscode#57125]
I have breadcrumbs enabled. When editing Markdown, if my cursor is on a heading like `# Test`, then `# Test` appears in the breadcrumbs. But if my cursor is one line below the heading, then the breadcrumb simply shows `...`. 

Instead, it should show the heading, since the cursor is still in the same section.

**Comment by mjbvz** [comment]
Fixed by 2c43eaebeccb4cba48f3aa6c54b020e1dd477c19

**Comment by carstenhag** [comment]
Could you explain what this does? coming here from the referenced issue, but I have no clue what this would look like
