### ISSUE TITLE
autohotkey not working, vscode completely ignores keybindings

### ISSUE THREAD

**Issue by masters3d** [Microsoft/vscode#57121]
Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:43:53.668Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

ALSO IN:

Version: 1.26.1
Commit: 493869ee8e8a846b0855873886fc79d480d342de
Date: 2018-08-16T18:38:57.434Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Steps to Reproduce:
 
Install https://autohotkey.com/, run any script, VS Code will complete ignore it. 

This is completely blocking me. I switched from macOS to Windows. I spent a lot of time setting up a script that helps me keep all [ custom shorcuts ](https://github.com/masters3d/supportfiles/blob/master/cheyo-macOS-mimic.ahk)

The only other app I had the same issue with was the Command Prompt but in that case I understand as Command Prompt is reading input in. I use http://cmder.net/ as my command line which respects global keybindings.

What changed between 1.24.1 and 1.25.1? 

Does this issue occur when all extensions are disabled?: Yes

IT WORKS FINE WITH:

Version 1.24.1
Commit 24f62626b222e9a8313213fb64b10d741a326288
Date 2018-06-13T17:51:32.889Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Version 1.23.0-insider
Commit 36e6cbb7667e7874748d8fbf2021b743d2d90afc
Date 2018-04-25T05:17:12.103Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by masters3d** [comment]
This is dependent of the way vscode gets launched. Only seems to happen with launching from Cmdr.

**Comment by alexandrudima** [comment]
I am not aware of us doing any of our input handling code differently when having different environmental variables ...
