### ISSUE TITLE
Outline pannel doesn't show functions inside classes

### ISSUE THREAD

**Issue by rickstaa** [Microsoft/vscode#57137]
**Problem description**
I just tried the outline feature in visual code but I noticed that functions which are defined as methods under a class do not show up in the outline panel or symbol search database ````ctrl + shift+ o```. I was not sure if this is a bug or that this still needs to be implemented.

**System information**
- VSCode Version: 1.27.0-insider
- OS Version: Windows 7 enterprise (Service Pack 1)

**Steps to Reproduce:**

1. Create a python file with a method defined inside a class
2. Look at the outline panel and see that the methods are not displayed as a sub level under a class.

**Does this issue occur when all extensions are disabled?:** 
Yes

**Pictures:**
![image](https://user-images.githubusercontent.com/17570430/44571971-b93a6880-a782-11e8-9d65-228b56a6250a.png)

**Comment by mjbvz** [comment]
Please file this issue against the python extension
