### ISSUE TITLE
Debug views: add line-height to center items in trees/lists

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#57131]
At least the breakpoints view seems to be missing a `line-height: 22px` so that the items are perfectly centered. I did not check the other views.

E.g. compare with the SCM view where each item has a line-height associated.

**Comment by isidorn** [comment]
@bpasero the breakpoints view was the only missing this since I transformed it to use a list a forgot to apply this css rule. Thanks for finding this.

**Comment by bpasero** [comment]
@isidorn great
