### ISSUE TITLE
Touchpad scrolling = Lag

### ISSUE THREAD

**Issue by PabloVortex** [Microsoft/vscode#57133]
**Visual Studio lags every time I open it. Going into full-screen mode then going back fixes it but this is really annoying.**
Steps to Reproduce:

1. Open a file with visual studio
2. Lag happens
3. Go into full-screen mode
4. Go back to windowed mode
5. Lag is gone
6. (Lag doesn't happen while in full-screen mode either)

Reproduces without extensions: Yes/No

Edit: Added the workaround:

Workaround: Restore/Maximize or resize the VS Code window
image

**Comment by bpasero** [comment]
Known issue that can be worked around by configuring: `window.smoothScrollingWorkaround: true`
