### ISSUE TITLE
Workspace: window title reads name of workspace file?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#57130]
Steps to Reproduce:

1. open a workspace
2. check the title (macOS, native title)

=> it seems to show the name of the workspace file
=> this should be the workspace name instead

![image](https://user-images.githubusercontent.com/900690/44567003-c4849880-a770-11e8-8243-1ccf1454dd12.png)

**Comment by isidorn** [comment]
@bpasero good catch, thanks for reporting great issues

**Comment by bpasero** [comment]
@isidorn my pleasure, this one was actually showing up as a failing smoke test too.
