### ISSUE TITLE
Windows file links with whitespace not recognized in terminal

### ISSUE THREAD

**Issue by hansmaad** [Microsoft/vscode#57139]
Issue Type: <b>Bug</b>

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.81GB (21.39GB free)|
|Process Argv|C:\Users\1234\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
githistory|don|0.4.2
tslint|eg2|1.0.36
vscode-npm-script|eg2|0.3.5
python|ms-|2018.7.1
cpptools|ms-|0.18.1
vsliveshare|ms-|0.3.577
cmake|twx|0.0.17
cmake-tools|vec|1.1.1

</details>

---
**Steps to reproduce:**
 - Create a file `c:\my folder\file.txt` (the file must exist to be matched)
 - Open an integrated terminal (I tested with `Git\\bin\\bash.exe`)
 - type `echo c:\my folder\file.txt`

**Expected behaviour:**
`c:\my folder\file.txt` will be highlighted and can be clicked. 

**Actual behaviour:**
Link is not highlighted. `c:\myfolder\file.txt` will work.

I found that the current `_localLinkPattern` for Windows is this 
```
"((([a-zA-Z]:|\\.\\.?|\\~)|([^\\0<>\\?\\|\\/\\s!$`&*()\\[\\]+'\":;])+)?((\\\\|\\/)([^\\0<>\\?\\|\\/\\s!$`&*()\\[\\]+'\":;])+)+)"
                                              ^
----------------------------------------------^  that \s ??
```

I'm not sure if it makes any sense to match such file paths, but my code is currently under `My Documents` and my gulp output won't be recognized.

```
[gulp-typescript] C:\Data\xyz\My Documents\code\project\src\xcontroller.ts(179,24): error TS2554 E
```

**Comment by Tyriar** [comment]
Tracking in https://github.com/xtermjs/xterm.js/issues/583
