### ISSUE TITLE
Copying

### ISSUE THREAD

**Issue by Awezome1996** [Microsoft/vscode#57140]
Add a feature where you keep copies in a clip board.so like a note location to keep multiple copies.

**Comment by V-ed** [comment]
This is a great idea for an extension, IMO. It's great to see that there's already an extension to manage your clipboard history!

Clipboard History extension : [Anjali.clipboard-history](https://marketplace.visualstudio.com/items?itemName=Anjali.clipboard-history) - found using a simple `vscode clipboard` search in google.
