### ISSUE TITLE
Space in workspaceFolder break task run

### ISSUE THREAD

**Issue by tomintaiga** [Microsoft/vscode#57148]
Issue Type: <b>Bug</b>

My working path for c++ project  is */home/tom/src/test/leetcode/Remove Duplicates from Sorted Array/*

I've add task to run my application:

```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Run",
            "type": "shell",
            "command": "${workspaceFolder}/build/example",
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

No when I try to run it, I've got an error:
```
> Executing task: /home/tom/src/test/leetcode/Remove Duplicates from Sorted Array/build/example <

/bin/bash: /home/tom/src/test/leetcode/Remove: No such file or directory
Процесс терминала завершен с кодом выхода: 127
```

If I rename "Remove Duplicates from Sorted Array" to "Remove_Duplicates_from_Sorted_Array" everything works fine.

Maybe it's part of https://github.com/Microsoft/vscode/issues/45832

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:34:20.517Z)
OS version: Linux x64 4.4.0-133-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 x 2651)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|13, 11, 10|
|Memory (System)|15.61GB (0.19GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|44%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
doxdocgen|csc|0.3.3
vscode-markdownlint|Dav|0.20.0
vscode-language-pack-ru|MS-|1.26.3
python|ms-|2018.7.1
cpptools|ms-|0.18.1
Go|ms-|0.6.88
makefiles-support-for-vscode|nae|0.0.3
vscode-docker|Pet|0.1.0
shader|sle|1.1.3
cmake|twx|0.0.17
cmake-tools|vec|1.1.1

</details>

**Comment by dbaeumer** [comment]
Since a single command can be a full command line VS Code doesn't do any automatic quoting (e.g the command could be `"echo Hello"` which shouldn't be quoted). You can either quote it yourself by using `'` in the string or quote it using a command literal

```
			"command": {
				"value": "${workspaceFolder}/build/example",
				"quoting": "weak"
			}
```

**Comment by tomintaiga** [comment]
This is not the behavior you expect. 

**${workspaceFolder}** is a variable in this file. I can't change it (maybe I don't know how?)

Look at CMake variables - no need to extra quoting.

If IDE is working on system, where spaces are usual in folder path, it will be smart to solve this problem without users attention.

I do not want to offend anyone, but in my opinion it is a bug.

**Comment by dbaeumer** [comment]
@tomintaiga I see your point. The problem I have is backwards compatibility. At the beginning we didn't quote at all and the user needed to put quotes into all commands.

> If IDE is working on system, where spaces are usual in folder path, it will be smart to solve this problem without users attention

Actually it is, however not in that backwards compatible case. I will change the code a little that it does the quoting even in cases where an empty args array is provided. This is all that can be done to keep all things running as well.

**Comment by dbaeumer** [comment]
To make it work the task must look like:

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Run",
            "type": "shell",
            "command": "${workspaceFolder}/build/example",
            "args": [],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

**Comment by dbaeumer** [comment]
Reopening since this needs more thinking. The fix did break an old working scenario.

**Comment by dbaeumer** [comment]
New attempt

**Comment by dbaeumer** [comment]
Fixed in https://github.com/Microsoft/vscode/tree/dbaeumer/57148

**Comment by dbaeumer** [comment]
Merged to master
