### ISSUE TITLE
Cmd+k cmd+c

### ISSUE THREAD

**Issue by johnkors** [Microsoft/vscode#57146]
Hi, 

VS Code has a default of toggling line comments via `cmd+k cmd+c`, but this opens up a prompt to provide a git commit message. How may I disable this, so it can do line commenting? I've tried to override it in keybindings.json, but no luck.

- Extension Name: git
- Extension Version: 1.0.0
- OS Version: Darwin x64 16.7.0
- VSCode version: 1.26.0

 We have written the needed data into your clipboard. Please paste:
```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 114,
		"activateCallTime": 6,
		"activateResolvedTime": 84,
		"activationEvent": "*"
	}
}
```

**Comment by joaomoreno** [comment]
> VS Code has a default of toggling line comments via cmd+k cmd+c, but this opens up a prompt to provide a git commit message.

Can you show me a screenshot of that prompt?

**Comment by johnkors** [comment]
<img width="652" alt="screen shot 2018-08-25 at 17 36 25" src="https://user-images.githubusercontent.com/206726/44619960-774a1900-a88d-11e8-84a7-0d4892085c00.png">

**Comment by joaomoreno** [comment]
Very interesting. Can you show me your full keybindings.json file?

**Comment by johnkors** [comment]
```
// Empty
[
    {
        "key": "cmd+l",
        "command": "workbench.action.terminal.toggleTerminal"
    },
    {
        "key": "ctrl+shift+[Equal]",
        "command": "-workbench.action.terminal.toggleTerminal"
    },
    {
        "key": "cmd+l",
        "command": "workbench.action.terminal.focus",
        "when": "!terminalFocus"
    },
    {
        "key": "alt+f12",
        "command": "-workbench.action.terminal.focus",
        "when": "!terminalFocus"
    }
]
```

**Comment by johnkors** [comment]
Seems this extension was the culprit: https://marketplace.visualstudio.com/items?itemName=k--kato.intellij-idea-keybindings
