### ISSUE TITLE
Integrated Terminal eventually turn mouse pointer into 'Precision Select' instead of 'Normal Pointer' or 'Text Select'

### ISSUE THREAD

**Issue by xenogew** [Microsoft/vscode#57141]
- VSCode Version: 1.26.1
- OS Version: Windows 10 (10.0.17134.228)

Steps to Reproduce:

1.  integrated terminal active.
2.  input any command to integrated terminal.
3.  swap/switch to another programs, I can't specify which condition will trigger the bug. But eventually I found mouse pointer is changed to **Precision Select** instead of **Normal Select** or **Text Select**. (name reference from Mouse properties window of Control Panel -> Mouse)

Does this issue occur when all extensions are disabled?: Yes/No
*  **Yes**

I can't capture the screenshot with Windows 10 function, the picture is excluded the cursor image. So there's no image to show you what happen.

**Comment by rcatajar** [comment]
I am running in the same issue (screenshot below)
![screenshot from 2018-08-24 11-49-08](https://user-images.githubusercontent.com/7900305/44578456-f2c79f80-a793-11e8-8261-5df07e6ea490.png)

VS Code version: 1.26.1
OS: Manjaro Linux (kernel 4.18.3)
Issue also occur with extensions disabled.

**Comment by Tyriar** [comment]
This happens when you _alt_+tab out of the window, the alt state isn't evaluated again when focus returns to the window.

**Comment by Tyriar** [comment]
Upstream: https://github.com/xtermjs/xterm.js/issues/1629

**Comment by faizaankhan** [comment]
@Tyriar : This is happening for me normally

**Comment by samarth-math** [comment]
+1

**Comment by alexr00** [comment]
Fixed by xtermjs/xterm.js#1636
