### ISSUE TITLE
Git commit message box in SCM view uses native scrollbar

### ISSUE THREAD

**Issue by V-ed** [microsoft/vscode#57158]
Issue Type: <b>Bug</b>

Entering a message that is tall enough (e.g. which makes enough lines to trigger the scrollbar) shows the native scrollbar of the OS.

I'm on Windows using a dark theme and the native white scrollbar made me go blind for few minutes.

![vscode-native-scrollbar](https://user-images.githubusercontent.com/16652915/44593117-8c8d4d80-a790-11e8-9d11-cbfe4fcac7e1.png)

Jokes aside, I really think there should be a custom scrollbar there to make it consistent with every other UIs there is in VSCode.

This is also present on the Insiders version as I'm writing this issue.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2294)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (1.04GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|1.2.6
Bookmarks|ale|9.0.3
project-manager|ale|8.0.0
copy-relative-path|ale|0.0.2
gitignore|cod|0.5.0
bracket-pair-colorizer|Coe|1.0.59
vscode-markdownlint|Dav|0.20.0
vscode-quick-select|dba|0.2.6
vscode-faker|dee|1.3.0
githistory|don|0.4.2
xml|Dot|2.3.2
gitlens|eam|8.5.6
EditorConfig|Edi|0.12.4
docblocker|fly|0.4.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vscode-auto-open-markdown-preview|hnw|0.0.4
output-colorizer|IBM|0.1.2
XMLLanguageSupport|IBM|0.0.1
autofilename|Jer|0.1.3
vscode-random|jre|1.3.2
vscode-github|Kni|0.30.0
expand-region|let|0.1.2
vs-color-picker|lih|0.7.0
dotenv|mik|1.0.1
vscode-todo-parser|min|1.9.1
vscode-duplicate|mrm|1.2.1
color-highlight|nau|2.3.0
snippet-creator|nik|0.0.4
material-icon-theme|PKi|3.5.3
view-in-browser|qin|0.0.5
java|red|0.29.0
vscode-icons|rob|7.25.0
code-settings-sync|Sha|3.0.0
selectline-statusbar|tom|0.0.2
vscode-input-sequence|tom|0.2.0
vscode-java-debug|vsc|0.11.0
vscode-maven|vsc|0.10.0
vscode-todo-highlight|way|1.0.4
better-align|wwm|1.1.6
markdown-all-in-one|yzh|1.6.0

(2 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Makes sense!

**Comment by V-ed** [comment]
@joaomoreno Sure, I don't mind looking into this, but I never really touched typescript and would prefer if I had some pointers to existing code to base myself on. Can you give me a link to one of those examples you are talking about?

**Comment by joaomoreno** [comment]
This guy here, check his usages: https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/scrollbar/scrollableElement.ts#L477

**Comment by V-ed** [comment]
@joaomoreno Awesome, thanks, I'll take a look!
