### ISSUE TITLE
[Bug] Pug syntax highlighting broken in latest VS Code version

### ISSUE THREAD

**Issue by Dan503** [Microsoft/vscode#57152]
Issue Type: <b>Bug</b>

I have this pug markup and it isn't being highlighted correctly

```pug
each markup, type in demoMarkup
  if type === 'js'
    .grid__cell(class=type)
      each js, jsType in markup
        if (jsType === 'es5')
          details.o-demo__details.o-demo__es5
            summary ES5 Syntax
            .o-demo__markup
              pre
                code(class=type)= js
        else
          .o-demo__markup.o-demo__segment.js(class=jsType)
            pre
              code(class=type)= js
  else if (type === 'html' && spec.showHTML || type !== 'html')
    - markup = type === 'html' ? html : markup;
    .grid__cell.o-demo__markup.o-demo__segment(class=type)
      pre
        code(class=type)= markup
```

This is how it is being highlighted:

![pug-incorrect-syntax-highlighting](https://user-images.githubusercontent.com/10610368/44587368-115e8280-a7f6-11e8-9d6f-a1e340fa6473.png)

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 3998)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (8.67GB free)|
|Process Argv|C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.0.3
vscode-twig-pack|baj|1.0.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.59
vscode-svgviewer|css|1.4.4
gitlens|eam|8.5.6
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.4
beautify|Hoo|1.3.2
RelativePath|jak|1.4.0
vscode-phpfmt|kok|1.0.30
vscode-regexp-preivew|le0|0.0.3
VS-code-drupal|mar|0.0.12
vscode-scss|mrm|0.6.2
debugger-for-chrome|msj|4.8.2
autotrim|Nat|1.0.6
format-html-in-php|rif|1.3.4
code-settings-sync|Sha|3.0.0
code-spell-checker|str|1.6.10
pdf|tom|0.3.0
quokka-vscode|Wal|1.0.141
vscode-import-cost|wix|2.8.0
html2jade|wma|0.2.0
markdown-all-in-one|yzh|1.6.0

(4 theme extensions excluded)

</details>

**Comment by lzlptk** [comment]
Using a filter in a tag breaks the syntax highlighting inside it.
```jade
script
    :uglify-js
        WebFont.load({
            google: {
                "families": ["Poppins:300,400,500,600,700", "Roboto:300,400,500,600,700"]
            },
            active: function() {
                sessionStorage.fonts = true;
            }
        });
```

![screenshot from 2018-09-02 21-32-27](https://user-images.githubusercontent.com/25512796/44960030-1e672a00-aef8-11e8-87b6-3ea55a8357c6.png)

Without a filter it looks good.
![screenshot from 2018-09-02 21-32-07](https://user-images.githubusercontent.com/25512796/44960026-160eef00-aef8-11e8-939d-e0a367dd6d8c.png)

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:34:20.517Z)
OS version: Linux x64 4.15.0-33-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz (4 x 1975)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|0, 1, 1|
|Memory (System)|7.69GB (0.69GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icons|rob|7.25.0
code-settings-sync|Sha|3.1.1

(1 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
This issue was moved to davidrios/pug-tmbundle#25
