### ISSUE TITLE
Occurrence instance color 

### ISSUE THREAD

**Issue by astanciu** [Microsoft/vscode#57159]
Let's say you have this code:
```
user.run()
user.click()
user.done()
```

you click somewhere on the first `user`, click CMD+D to select the first one, CMD+D and CMD+K to skip the second, then CMD+D to select the third. You end up with this:

![image](https://user-images.githubusercontent.com/1675025/44594516-69649d00-a794-11e8-93f0-bb72f27b4221.png)

As you can tell, other than the (blinking) cursor, there's no way to tell which are actually selected. It would be great if there was a setting to set the color for the other selected items.

Strangely enough, if the window is inactive, it does show correctly:
![image](https://user-images.githubusercontent.com/1675025/44594582-96b14b00-a794-11e8-9422-ecd1266386d2.png)

Maybe I'm missing something

**Comment by rebornix** [comment]
Selection highlight overrides the selected text highlight in this case.
