### ISSUE TITLE
Integrated Console blocks for 10 seconds on startup

### ISSUE THREAD

**Issue by nedludd** [Microsoft/vscode#57166]
Issue Type: <b>Bug</b>

Open a PS1 script and the interface blocks for up to 10 seconds while the Powershell Integrated Console opens. 

Is there an option to turn off initial loading of the console?

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2695 v2 @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Memory (System)|16.00GB (8.69GB free)|
|Process Argv|C:\FAST\VsCode\1.23.0\Code.exe --extensions-dir C:\FAST\VsCode\1.23.0\.vscode\extensions|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.12
vscode-npm-script|eg2|0.3.5
dotnet-test-explorer|for|0.5.1
expressjs-4-snippets|gur|1.0.2
vscode-perl|hen|1.14.4
rest-client|hum|0.18.4
search-node-modules|jas|1.3.0
svn-scm|joh|1.33.0
mattermost|JP |0.0.1
Lisp|mat|0.1.8
python|ms-|2018.6.0
Go|ms-|0.6.88
PowerShell|ms-|1.8.3
debugger-for-chrome|msj|4.8.2
vim|vsc|0.15.7
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.7.0

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
You should update VS Code, 1.26.1 is the latest. If you still see an issue you can report it against https://github.com/PowerShell/vscode-powershell
