### ISSUE TITLE
"Search in files" multiple times

### ISSUE THREAD

**Issue by Daijobou** [Microsoft/vscode#57169]
I like the search-icon in left side. Its fast access.
![grafik](https://user-images.githubusercontent.com/260343/44603212-4b258e00-a7e2-11e8-8c14-9e68dfaf7d46.png)

I wish when a "search in files" is filled up, its possible to add a second (or more) "search in files" without overriding recent search. I must search for a keyword A and get a long list of files to check. Now i detect I need more informations for analysis. So I must search with another keyword B to compare data that found with keyword A before. But thats impossible, because I can only start one "search in files" and not multiple times.

So I would like for a option that search-icon can create a new additional search and select like explorer with title-bar the one I need and add a new one.

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/16488

**Comment by Daijobou** [comment]
@roblourens 
That is not the same request? #16488 want mutliple search patterns for a single search result. SO I understood. I want mutliple independent searches. Each search-formular with a own list of results.

**Comment by roblourens** [comment]
I think you are asking for the same thing - keeping track of multiple independent searches simultaneously.
