### ISSUE TITLE
Tools and languages button on Welcome screen finds 0 extensions

### ISSUE THREAD

**Issue by PikeUK** [Microsoft/vscode#57160]
Issue Type: <b>Bug</b>

STR:
1. Click the _Tools and languages_ section on the Welcome screen (or the _more_ link inside the section).

Expected:
The extension manager opens showing a list of tools and languages.

Actual:
The extension manager opens but shows _No extensions found._

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz (12 x 3300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (7.50GB free)|
|Process Argv|C:\Users\\\<username>\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.5.0
hg|mrc|1.2.3
vscode-apache|mrm|1.1.1
code-settings-sync|Sha|3.0.0
vscode-hexdump|sle|1.6.0

</details>

**Comment by ramya-rao-a** [comment]
@chrmarti Clicking on `Tools and Extensions` opens up the extensions view and searches for `@sort:installs category:languages` which will never give any results as there is no category called "languages".

We should use `@category:"programming languages" @sort:installs` instead

**Comment by PikeUK** [comment]
FWIW searching for category:languages on the web version of the marketplace _does_ seem to work (it returns 1000s of results).
