### ISSUE TITLE
Automatically generating getter and setter

### ISSUE THREAD

**Issue by user414** [Microsoft/vscode#5716]
I couldn't find this issue already existing. I was starting to make variable public just to avoid the setter/getter manual writing, I knew it was time to look for something. Luckily someone beat me to it

https://marketplace.visualstudio.com/items?itemName=DSKWRK.vscode-generate-getter-setter

perhaps this code can be integrated in the mainline, or use as a basis for this new functionality.

**Comment by dbaeumer** [comment]
@waderyan this should come from the TS team.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#12417
