### ISSUE TITLE
rename case sensitive fail

### ISSUE THREAD

**Issue by idoros** [Microsoft/vscode#5717]
- VSCode Version:1.0.0
- OS Version:Windows 10

Steps to Reproduce:

1. select variable in the code
2. press F2
3. change case of a single letter (UP>LOW / LOW>UP)
4. press ENTER - nothing changes

**Comment by bpasero** [comment]
@idoros which language is this?

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Comment by idoros** [comment]
Sorry for missing the message. The text is in English.

**Comment by bpasero** [comment]
@idoros I meant which programming language.
