### ISSUE TITLE
Git repo in %appdata%\..\Roaming\code\user appear in project SCM

### ISSUE THREAD

**Issue by n3rd4i** [Microsoft/vscode#57170]
Issue Type: <b>Bug</b>

If one is creating a git repo in `%appdata%\..\Roaming\code\user` which adds VSCode settings to version control and subsequent also creates some updates on that repo, like changing settings, this is reflected as project SCM changes.
This is not expected since the project SCM should only care about project related repo (if exists).

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.18214

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3 CPU       M 370  @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|2.74GB (0.32GB free)|
|Process Argv|C:\Users\andrei\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-yaml|red|0.0.14

</details>

**Comment by n3rd4i** [comment]
The repo opens if someone is trying to edit the VSCode settings (and that's of course a file).

So in that sense, you could say that it opens if the settings file get's open.

**Comment by joaomoreno** [comment]
You can configure Code to ignore certain Git repositories using the `git.ignoredRepositories` setting.
