### ISSUE TITLE
Multi-cursor usability

### ISSUE THREAD

**Issue by GeraldNDA** [microsoft/vscode#57177]
When you have a single cursor, then move it out of viewable area makes the screen scroll in order to bring it into focus.

If you have multiple cursors, this functionality is turned off (understandably). However, it's really annoying when you have 3 or 4 cursors and all of a sudden you can see any of them. I have two suggestions that could potentially improve usability of multi-cursor:

1. A cursor count displayed in the bottom bar if you have more than 1
~2. Always have 1 cursor in focus. If all cursors go out of focus, then go to the nearest/newest one.~

**Comment by GeraldNDA** [comment]
#6995 is a duplicate of (2).

**Comment by alexdima** [comment]
Let's track in #6995 . The cursor count is shown in the status bar
