### ISSUE TITLE
Love to have a "save as pdf" option in the markdown preview

### ISSUE THREAD

**Issue by lovettchris** [Microsoft/vscode#57176]
Sometimes you need to share a snapshot of a markdown page with the team and it is most convenient to email a PDF in that case.  So it would be great if I could just do "save as pdf" on that preview window.

**Comment by mjbvz** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/39698

This is beyond the scope of core VS Code but can be implemented by an extension
