### ISSUE TITLE
Don't display system wide warning message for portable installations

### ISSUE THREAD

**Issue by ThadHouse** [Microsoft/vscode#57179]
I have a setup that is using a portable installation of VS Code, at the same time as having a local user level install. When I open the portable installation, I get a message box saying I am running a system-wide installtion of Code while also having a user-wide distribution. This error likely shouldn't be popped up when using portable mode, as well as it should say the correct message (portable mode instead of system-wide installation).

**Comment by joaomoreno** [comment]
We've removed the dialog altogether, coming next release.
