### ISSUE TITLE
Allow key bindings to be combined with mouse events (left, middle, right click)

### ISSUE THREAD

**Issue by carstenhag** [Microsoft/vscode#57171]
Basically, I want to press/click the combination of `Command + Left Click` in my source code (LaTeX) to run an extension command.

Everything of that works, apart from the `Command + Left Click`.

https://github.com/James-Yu/LaTeX-Workshop/issues/716  
Partly related, but just about middle clicks: https://github.com/Microsoft/vscode/issues/43794

**Comment by rebornix** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/3130
