### ISSUE TITLE
Unable to paste text by mouse middle button on Linux

### ISSUE THREAD

**Issue by mirao** [Microsoft/vscode#5718]
- VSCode Version: 1.0.0
- OS Version: Linux Ubuntu 16.04

Steps to Reproduce:

1. Edit a file in VSC
2. Mark a text in any app (e.g. in bash or in web browser)
3. Paste the text by mouse middle button into VSC

Expected result:
- it's possible

Actual result:
- the text cursor disappears, no text is pasted

BTW it works well in debug console shell in VSC

**Comment by Tyriar** [comment]
You can enable this by adding this to your settings:

```json
  "editor.selectionClipboard": true,
```

I think it will be on by default in the April release.
