### ISSUE TITLE
Portable mode does not allow running command line commands.

### ISSUE THREAD

**Issue by ThadHouse** [Microsoft/vscode#57185]
Using portable 1.26.1, I am attempting to run `Code.exe --list-extensions`. Instead of listing the installed extensions, VS Code opens, and the list is never printed. The same issue occurs with any non opening command, I was able to reproduce with both `--version` and `--install-extension`, along with `--list-extensions`

**Comment by joaomoreno** [comment]
You should run `bin\code` instead of `code.exe`.

**Comment by ThadHouse** [comment]
Ok. Can that be added to the command line documentation page? Nowhere in the docs was that said.
