### ISSUE TITLE
@ts-nocheck seems to be ignored on TS file

### ISSUE THREAD

**Issue by arsnl** [Microsoft/vscode#57187]
- VSCode Version: 1.26.1
- OS Version: macOS High Sierra 10.13.6
- TypeScript: 3.0.1

**Steps to Reproduce**

1. Add `// @ts-nocheck` at the start of any TypeScript file
2. Try to trigger any TS check error

**Result**

VS Code display TS error

![error](https://user-images.githubusercontent.com/763489/44613360-6a232080-a7e0-11e8-8f0d-58cd47d28cfc.jpg)

**Expected**

VS Code should not display TS error

Does this issue occur when all extensions are disabled?: Yes

**Snippet to try**

```TS
// @ts-nocheck

const test = (foo: string) => `${foo}-bar`;

test(1); // Should not display error

test('baz'); // Correct behavior with correct type

// @ts-ignore
test(1); // Correct behavior with @ts-ignore
```

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#26887
