### ISSUE TITLE
Cannot read property "focus" of null error when editing exclude widget

### ISSUE THREAD

**Issue by JacksonKearl** [Microsoft/vscode#57180]
This only happens occasionally, and I've only seen it when editing excludes with when clauses. But the relevant line is: https://github.com/Microsoft/vscode/blob/568d99275d8eabab3df5ab2f9c0ae92f2714a801/src/vs/workbench/parts/preferences/browser/settingsWidgets.ts#L461 , where `patternInput` is `null`. I really have no clue how this would happen, given we only ever assign to it from the constructor, and its even marked as `const`.

**Comment by JacksonKearl** [comment]
Ah, my bad. I missed that this is actually coming from the `inputBox`'s focus call, where it delegates to `this.input`, which is coming out as `null`.

**Comment by JacksonKearl** [comment]
Still dont know why it's input is null though

**Comment by roblourens** [comment]
Haven't seen this again 🤷‍♂️
