### ISSUE TITLE
Broken symlinks not showing in tree view

### ISSUE THREAD

**Issue by robtarr** [Microsoft/vscode#57189]
Issue Type: <b>Bug</b>

If the target of a symlink is missing, the symlink is not shown in the tree view. However, the symlink still exists, it's simply broken. The tree view should still show the symlink since it exists in the directory.

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:20:44.170Z)
OS version: Darwin x64 17.7.0

<img width="785" alt="screen shot 2018-08-24 at 11 05 12 pm" src="https://user-images.githubusercontent.com/270461/44614510-3e119a80-a7f4-11e8-83f0-c655660287f3.png">

After deleting b.txt
<img width="785" alt="screen shot 2018-08-24 at 11 05 49 pm" src="https://user-images.githubusercontent.com/270461/44614518-9c3e7d80-a7f4-11e8-8e74-fc5600faa35c.png">

<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7287U CPU @ 3.30GHz (4 x 3300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|16.00GB (1.12GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
html-css-class-completion|Zig|1.17.1
better-comments|aar|1.2.6
project-manager|ale|8.0.0
react-pure-to-class-vscode|ang|1.1.6
run-current-test|asv|0.2.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.59
erb|Cra|0.0.1
vscode-eslint|dba|1.5.0
githistory|don|0.4.2
gitlens|eam|8.5.6
vsc-material-theme|Equ|2.3.0
prettier-vscode|esb|1.6.1
php-debug|fel|1.12.4
php-intellisense|fel|2.3.4
beautify|Hoo|1.3.2
rest-client|hum|0.19.1
rainbow-csv|mec|0.4.2
dotenv|mik|1.0.1
ruby-rubocop|mis|0.7.0
prettify-json|moh|0.0.3
vscode-apache|mrm|1.1.1
atom-keybindings|ms-|3.0.4
cpptools|ms-|0.18.1
vsliveshare|ms-|0.3.577
color-highlight|nau|2.3.0
language-liquid|nei|0.0.3
printcode|nob|2.3.1
vscode-versionlens|pfl|0.21.1
material-icon-theme|PKi|3.5.3
ruby|reb|0.20.0
rust|rus|0.4.9
code-settings-sync|Sha|3.0.0
stylelint|shi|0.41.0
org-mode|too|0.5.0
vscode-arduino|vsc|0.2.20
quokka-vscode|Wal|1.0.142
vscode-import-cost|wix|2.8.0
city-lights-icon-vsc|Yum|1.0.1

(3 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
@rebornix Isidor owns the file explorer (since about 1 year).

**Comment by luckened** [comment]
can we reopen this? pycharm has an elegant solution that we can have as inspiration
