### ISSUE TITLE
Ejecutable se elimino luego de actualizacion

### ISSUE THREAD

**Issue by david19940403** [Microsoft/vscode#57181]
Issue Type: <b>Bug</b>

Di click en la opcion emergente.
El equipo esta en una red active directory asi que no tengo permisos de administrador.
el administrador me permitio esta instalacion.
inicie instalacion.
el programa se reinicio para aplicarla.
no volvio a iniciar
y el ejecutable se habia borrado

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.91GB (5.47GB free)|
|Process Argv|C:\Users\dev.android\Downloads\VSCode-win32-x64-1.26.1\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.5.0
githistory|don|0.4.2
xml|Dot|2.3.2
EditorConfig|Edi|0.12.4
vscode-npm-script|eg2|0.3.5
git-project-manager|fel|1.6.1
search-node-modules|jas|1.3.0
vscode-codemetrics|kis|1.17.1
node-module-intellisense|lei|1.5.0
vscode-azurefunctions|ms-|0.10.0
vscode-language-pack-es|MS-|1.26.3
azure-account|ms-|0.4.3
vsliveshare|ms-|0.3.577
vsliveshare-audio|ms-|0.1.32
debugger-for-chrome|msj|4.8.2
vscode-for-node-js-development-pack|nod|2.0.1
vscode-docker|Pet|0.1.0
code-settings-sync|Sha|3.0.0
nodejs-extension-pack|wad|0.1.9
vscode-import-cost|wix|2.8.0
JavaScriptSnippets|xab|1.7.0

</details>

**Comment by rebornix** [comment]
It's related to udpate/install based on google translate.

**Comment by joaomoreno** [comment]
This issue was closed because it doesn't meet our standards of a properly filled issue. Please read our guide about [Submitting Bugs and Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).
