### ISSUE TITLE
Javascript Multiline String Hide (or Collapse)

### ISSUE THREAD

**Issue by realivanjx** [Microsoft/vscode#57190]
Hi,

I would like if VS Code is able to collapse multiline strings. It doesn't have plus or minus sign to do so. Please note that I use ` instead of ' for multi line strings:

![screenshot_37](https://user-images.githubusercontent.com/12814796/44615088-24f00480-a85b-11e8-83ef-1a1ff42abe8b.png)

Thanks

**Comment by mjbvz** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/23382
