### ISSUE TITLE
VSC Insiders always thinks that this is my first start

### ISSUE THREAD

**Issue by LunarTwilight** [Microsoft/vscode#57193]
- VSCode Version: 1.27.0-insider (Commit: 346018a80dd299c50cbf213e0a706ef0f35f3a67)
- OS Version: Windows 10

Steps to Reproduce:
1. Open the program
2. Watch

Does this issue occur when all extensions are disabled?: Yes

(some things are kept, like settings.json and my extensions/themes, but other things are not, like the recent folders/files and activity sidebar popup width)

**Comment by bpasero** [comment]
@LunarTwilight to verify, you:
* start VSCode by clicking on the icon
* you resize the sidebar to a certain width
* you close VSCode
* you start VSCode by clicking on the icon
=> the sidebar width is not as you left it?

**Comment by LunarTwilight** [comment]
@bpasero yes, also I get the new start notification and the new start page opens in my browser.

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by LunarTwilight** [comment]
I don't see any errors in the dev tools' console, but from the command line I'm getting a lot of errors about it being unable to open storage.json, which I thought at first was due to the file not existing, but then I created the file and the error still exists. I've also tried running it as admin but it still happens.

**Comment by bpasero** [comment]
@LunarTwilight can you attach the output? does it reproduce with stable?

**Comment by LunarTwilight** [comment]
VSC Insiders updated, so now I'm on 43676d0cb7db94e2fa771f1d10bff10eaa01b453. I've put the output at https://gist.github.com/LunarTwilight/d35cdf6ec938a0373b02147a6cd2292f. No it doesn't happen on stable.

**Comment by bpasero** [comment]
@LunarTwilight it look slike the user data directory is not writeable for VSCode due to permissions errors. This means, no state is saved. There is not much VSCode can do. 

`[main 1:45:09 AM] { Error: EPERM: operation not permitted, open 'C:\Users\[RETRACTED]\AppData\Roaming\Code - Insiders\storage.json'`

**Comment by LunarTwilight** [comment]
Well, I'm running VSC Insiders as admin, I've disabled the parts of my AV that would prevent it from saving/opening/editing the file, and I've checked the premissions, and it still won't work. I also checked stable and I don't see a storage.json in it's the folder either, but it works fine?

**Comment by LunarTwilight** [comment]
Huh, I had to restart, and now its working (even tho I don't have a storage.json), thanks for the help~
