### ISSUE TITLE
File association broken in portable install of VSC 1.26.1, no options to open files from OS context menu

### ISSUE THREAD

**Issue by aliasflavius** [Microsoft/vscode#57198]
- VSCode Version:

_Version: 1.26.1
Commit: 493869ee8e8a846b0855873886fc79d480d342de
Date: 2018-08-16T18:38:57.434Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64_

- OS Version:

_Windows 10, v 1803, build 17134.191_

Steps to Reproduce:

_1. Install the portable version of VSC 1.26.1, after uninstalling the global version
2. File association is broken and "Open/Edit with VS Code" options in the context menus are missing_

Does this issue occur when all extensions are disabled?: Yes/No
_Neither have any effect._

I haven't found any option in VSC to fix file association. There is an option to add associated file extensions manually, but that's not a great option if you have to manually input every type of file that VSC can edit.
It used to work fine in the globally installed version. I suppose that once I uninstalled the global version, all file associations have been removed and so has the PATH that linked to VSC.
Is there any automated way of fixing this?

**Comment by aliasflavius** [comment]
This isn't related to "extensions", @vscodebot,  ya numpty.

**Comment by joaomoreno** [comment]
Portable mode, by definition, can't have file type associations. We won't support this.
