### ISSUE TITLE
"format code" formats the attribute of element in html file uncorrectly

### ISSUE THREAD

**Issue by PeichengLiu** [Microsoft/vscode#5719]
- VSCode Version:1.0.0
- OS Version:Windows 10

Steps to Reproduce:

1. Create a simple html file.
2. Set its content to be something like this :
   ````
   <!DOCTYPE html>
<html lang="en-US">

<head>
    <meat http-equiv="Content-Type" content="text/html;charset="utf-8" />
</head>
<body>
    <form>
        <input type="submit" value="Submit">
    </form>
</body>
</html>
````
3. Press Alt+Shift+F to format the code.
3. Some of the attribute now has a value with <em>redundant</em> blank.

**Comment by aeschli** [comment]
This seems to happen because of the unclosed quote in 
`content="text/html;charset="utf-8" />`
