### ISSUE TITLE
Something wrong in terminal while using MSYS 2 with zsh.

### ISSUE THREAD

**Issue by STLGirlfriend** [Microsoft/vscode#57195]
- VSCode Version: 1.26.1
- OS Version: Microsoft Windows 10.0.17134.228

Steps to Reproduce:

1. Launch VSCode's terminal.
2. Use MSYS 2 with zsh and oh-my-zsh.
3. Set zsh's theme "robbyrussell".
3. Type something.

Does this issue occur when all extensions are disabled?: Yes/No

In VSCode's terminal, I use MSYS 2 with zsh (oh-my-zsh theme is robbyrussell).

While using, my cursor is not always in the end of the line(like those pictures). I can't move it to the end.

![gif233](https://user-images.githubusercontent.com/27623826/44616452-a0b17780-a882-11e8-9c3c-7a85ba6d11d9.gif)

**Comment by Tyriar** [comment]
This is happening because your arrow character is an ambiguous width character, for now there is no way to work around this. This is related to https://github.com/xtermjs/xterm.js/issues/1467

I recommend not using the arrow in your prompt.
