### ISSUE TITLE
Builder removal

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#57196]
Goal is to remove `vs/base/browser/builder` from our sources and replace it with helper functions from our `vs/base/browser/dom` utility methods. Reasons:
* we can remove 1500 lines of code
* `Builder` has a very questionable stateful behaviour that results in very complicated code that is hard to understand (callback hell, `clone()` method to reset state)
* `Builder` hides the fact that there are event handlers to dispose within, using explicit disposable listeners makes the lifecycle much clearer

**Some Advice**
* *IMPORTANT*: `Builder` supports spaces in classes, so make sure to call `DOM.addClasses(class)` instead of `DOM.addClass()` if the class name is passed into your component from extern and you do not know the value of the class containing spaces or not (same for `removeClasses`)
* *IMPORTANT*: use `DOM.addDisposeableListener()` for event handlers and add them to your list of things to dispose. `Builder` used to take care of that automatically when calling `empty`/`destroy`, but this is no longer supported
* Do not use `querySelect` but keep variables around for DOM elements
* Prefer `innerText` over `textContent` ([explanation](http://kellegous.com/j/2013/02/27/innertext-vs-textcontent/))
* `DOM.$()` is a lightweight drop-in replacement for `Builder` to build HTML (e.g. `DOM.append(parent, $('.some-class')))`)
* `Builder.empty()` => `DOM.clearNode()`
* `Builder.destroy()` => `node.remove()`
* `Builder.show()/hide()` => `DOM.show()/hide()`

**Areas**
* [x] Welcome (`watermark.ts`, `welcomeOverlay.ts`) @chrmarti 
* [x] Search (`searchView.ts`) @roblourens 
* [x] Feedback (`feedback.ts`) @isidorn 
* [x] Debug (`debugActionsWidget.ts`) @isidorn 
* [x] Comments (`commentThreadWidget.ts`) @rebornix 
* [x] Editor (`referenceWidget.ts`) @rebornix
* [ ] Titlebar (`titlebarPart.ts`) @sbatten 
* [ ] Menu (`menu.ts`) @sbatten
* [x] Resource Viewer (`resourceViewer.ts`) @bpasero 
* [x] Binary Editor (`binaryEditor.ts`) @bpasero
* [x] Quickopen (`quickOpenWidget.ts`) @bpasero

**Comment by bpasero** [comment]
@mjbvz fyi I took care of `ResourceViewer` (via https://github.com/Microsoft/vscode/commit/195ef8061082e4d719fb217b4db9c1561f1b217f)

**Comment by bpasero** [comment]
@roblourens thanks for doing search, I will sign you off.

Only 8 TO GO!

![image](https://user-images.githubusercontent.com/900690/44983380-3af77680-af79-11e8-80a3-fa0d41a3d5ea.png)

**Comment by bpasero** [comment]
5!

![image](https://user-images.githubusercontent.com/900690/44993842-4b6d1880-af9c-11e8-909d-dd23e8d396a7.png)

**Comment by rebornix** [comment]
2 🚀 


<img width="362" alt="image" src="https://user-images.githubusercontent.com/876920/44999909-7e4fe600-af75-11e8-8af1-f502d4c9e4b7.png">

**Comment by bpasero** [comment]
Thanks! Its gone 🙌
