### ISSUE TITLE
Manage Projects with Templates

### ISSUE THREAD

**Issue by LinArcX** [Microsoft/vscode#57206]
Hello every body. i'm using vscode about 1.5 year and its awesome. but still, i feel some features needs to be added(from my view).
Imagine, i'm working on a c++ project with specific configurations and contracts. For example i have a __assets__ folder for fonts and images, __utility__ folder for helper classes and so on.
Every time i want to create a similar project from scratch, it is painfully job. I remember in some technologies like maven there is __template__ idea that let users to initialize projects with predefined configurations rapidly.
In other side, every body can create his/her own template or provide popular ones.( like mvp, mvc, etc..) and submit it in a area(like extensions, we can have templates user defined area)

**Comment by nealot** [comment]
Maybe an implementation like https://github.com/visualzoran/vz-file-templates?

**Comment by LinArcX** [comment]
Yes, just like that :)

**Comment by nealot** [comment]
It can generate a full project.
