### ISSUE TITLE
Hangs creating a linked markdown

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#57201]
Issue Type: <b>Bug</b>

When I create a link, will hang for a long time and I am force to kill the editor.

When I add the opening round bracket to the link below, I get a hang everytime. I have tried with plugins disabled.

```
[]https://hobbyking.com/en_us/turnigy-aerodrive-sk3-6374-192kv-brushless-outrunner-motor.html
```

VS Code version: Code - Insiders 1.27.0-insider (346018a80dd299c50cbf213e0a706ef0f35f3a67, 2018-08-24T05:15:28.387Z)
OS version: Linux x64 4.15.0-32-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Phenom(tm) II X4 940 Processor (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.66GB (2.65GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders /home/yadav/Documents/esb.md|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
dep|car|0.1.0
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.20.0
vscode-eslint|dba|1.5.0
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.36
sort-typescript-imports|mic|1.4.1
Angular-BeastCode|Mik|6.2.13
cpptools|ms-|0.18.1
angular2-inline|nat|0.0.17
java|red|0.29.0
language-stylus|sys|1.10.0
sort-lines|Tyr|1.7.0
vscode-java-debug|vsc|0.11.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.8.0
vscode-maven|vsc|0.10.0
better-align|wwm|1.1.6

(2 theme extensions excluded)

</details>

**Comment by cfjedimaster** [comment]
I'm seeing this too. As I work with Markdown a lot, I've had to go back to the non-Insiders version.

**Comment by chrmarti** [comment]
The duration of the freeze seems to depend on the length of the input. I get short freezes with:

Start from:
```
[a link](http://foobar:1234/foobar )
```

Insert a letter before the closing paren:
```
[a link](http://foobar:1234/foobar a)
```
