### ISSUE TITLE
no extension istallation possible

### ISSUE THREAD

**Issue by Tavi62** [Microsoft/vscode#57202]
Issue Type: <b>Bug</b>

When I try to install an extension nothing happens. the logo changes to installing ant that is it... If i look in the code window under console i see the following error:

events.js:183 Uncaught Error: ENOENT: no such file or directory, open 'p:\Temp\4326a223-5241-45c7-8219-3d37d7fc30be'

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz (4 x 3504)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.97GB (17.24GB free)|
|Process Argv|F:\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by sandy081** [comment]
@Tavi62 Can you please provide us the `sharedprocess` logs which can be found in Output panel
