### ISSUE TITLE
Debugger Tool appears below while there isn't any opened tab 

### ISSUE THREAD

**Issue by abdurrahmanarikan** [Microsoft/vscode#57204]
- VSCode Version: 1.26.1
- OS Version: Mac OS High Sierra

Steps to Reproduce:

1. Run any node project
2. Make debugger tool downside of the line.
2. While debugging, close all tabs 

![image](https://user-images.githubusercontent.com/24858031/44620961-7ec9ec00-a8a6-11e8-969e-a002f0d85ccd.png)

**Comment by isidorn** [comment]
This is as designed, the toolbar does not move automatically. You can drag it back up if you do not like it there.
Closing as designed as we have no plans to change this in the immediate future
