### ISSUE TITLE
Quotation Marks of PHP and HTML Attributes are confused

### ISSUE THREAD

**Issue by moritzpuchinger** [microsoft/vscode#57213]
- VSCode Version: 1.26.1
- OS Version: Windows 10 Home Version 1803 (Build 17134.228)

Extensions: ftp-sync (It still happened when it was disabled)
Steps to Reproduce:

1. Write someting like this in a PHP file:
`<div onclick='javascript:doSomething("<?php echo $parameters['something']");?>'>`

Which will look something like this:
![image](https://user-images.githubusercontent.com/39553654/44623050-61584a80-a8c5-11e8-9724-fa73c1378c28.png)

**What I expexted to see:**

I expected it to look something like this:
![image](https://user-images.githubusercontent.com/39553654/44623078-08d57d00-a8c6-11e8-9ddb-31d5e81e86ab.png)

**What is the issue?**

I think what happens is that VS Code thinks that the first two single quotation marks (the one after `onclick=` and the one after `parameters[` belong together. Therefore it comes to the conclusion that the rest after the second single quotation mark is wrong and colors it in a deep red. VS Code should not confuse quotation marks outside of PHP tags with quotation marks inside of PHP tags.

Does this issue occur when all extensions are disabled?: Yes

**Comment by WraithKenny** [comment]
This is probably blocked by not having https://github.com/Microsoft/vscode/issues/1751

**Comment by moritzpuchinger** [comment]
Yes I believe it's got something to do with that although it detects that it is JavaScript because the function call does get colored yellow. It just somehow confuses brackets inside the JavaScript with those of the PHP

**Comment by roblourens** [comment]
Since the upstream project has been archived, merging this into the general issue for a new SSH grammar. https://github.com/microsoft/vscode/issues/162707
