### ISSUE TITLE
Exception widget doesn't disappear when debug session ends

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#57215]
Have some code:

```ts
throw new Error('fail')
```

- Set ' ✔️Uncaught Exceptions'
- Start debugging
- Pause on the exception, see red exception widget
- Stop debugging
- The red exception widget doesn't go away, and there is no way to get rid of it. In 1.26 it hides when debugging stops.

**Comment by isidorn** [comment]
@roblourens very good catch. Thanks Rob. The issue was that the sessio change event was being fired  while the change has not been fully set
