### ISSUE TITLE
[Improve] Consider using SymbolInformation.container for Code Outline view.

### ISSUE THREAD

**Issue by liwangqian** [Microsoft/vscode#57218]
The Code Outline view currently relies on the Range of symbols to determine the parent-son relationship, but in some language for example LUA, this algo is not suitable, why not consider using the `SymbolInformation.container` to help determine the parent-son relationship?

```lua
local class = {}  -- class range is limited in this line

-- the method of class is defined out-of the class's range.
function class.method(arg1, arg2, ...)

end

```

If the `SymbolInformation.container` of `method` is `class`, then the parent-son relationship can be determined.
If there is two or more `SymbolInformation` which has the same name, then fallback to the range algo.

Or, by adding a property `id` for `SymbolInformation` to indentify the symbol in one document, and add `parent_id` to identify the parent of the symbol.

**Comment by jrieken** [comment]
> The Code Outline view currently relies on the Range of symbols to determine the parent-son relationship,

That's only true for extensions that haven't adopted the *new* `DocumentSymbol` type. That API allows to set the parent child relationship in code and no more containment heuristic is needed.
