### ISSUE TITLE
Editing markdown with preview window open, auto scrolls edit window on every keypress

### ISSUE THREAD

**Issue by PandaWood** [Microsoft/vscode#57216]
Issue Type: <b>Bug</b>

For me, I just edit any Markdown file and open the "preview" window (Commnd-K,V) 
Then scroll down some amount. From that point on, every single keypress in the markdown editor window, scrolls the markdown editor down one unit. Nothing happens to the preview window.
It's a bizarre behavior that makes impossible to work on it - is it just me?

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:31:26.156Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3 CPU         550  @ 3.20GHz (4 x 3200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|12.00GB (0.88GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.4
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.5.0
xml|Dot|2.3.2
tslint|eg2|1.0.36
vscode-npm-script|eg2|0.3.5
vscode-nupkg|eri|0.0.8
vs-code-xml-format|fab|0.1.5
dotnet|for|0.0.4
dotnet-test-explorer|for|0.5.1
beautify|Hoo|1.3.2
vscode-nuget-package-manager|jmr|1.1.6
haml|kar|1.1.0
vscode-apache|mrm|1.1.1
cpptools|ms-|0.18.1
csharp|ms-|1.15.2
vs-keybindings|ms-|0.2.0

</details>

**Comment by mjbvz** [comment]
This should be fixed in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) by #58852

Let me know if you still see this issue when using VS Code insiders
