### ISSUE TITLE
Runaway process persists after stopping debugging node.js in VSCode 1.26.1

### ISSUE THREAD

**Issue by WillAvudim** [Microsoft/vscode#57217]
- VSCode Version: 1.26.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Debug a node.js application in VSCode.
2. From time (very rarely) the application will persist and will not shut down after node.js debugging session is terminated in VSCode UI. The application functions correctly endlessly in the background.
3. The application can then be shut down manually by running 'fuser -k <PORT>/tcp' to release the port and enable VSCode to start the node.js application successfully again.

Does this issue occur when all extensions are disabled?: Yes (verified)

My understanding is that this rare bug is the direct result of the new stop debugging feature implemented in 1.26.1: https://code.visualstudio.com/updates/v1_26#_debugging
Would it be possible to put this feature under a flag, so we could disable it?

**Comment by weinand** [comment]
If you press the red stop button again, it will kill the process (and all sub-processes) in exactly the same way as it did in previous release.

**Comment by WillAvudim** [comment]
Thank you for your response! I'm going to close it for now and I'll reopen it again (and reference this bug) once I figure out the repro.
