### ISSUE TITLE
Focus Breadcrumb shortcut not working on macOS with German keyboard

### ISSUE THREAD

**Issue by rherrmann** [Microsoft/vscode#57228]
Issue Type: <b>Bug</b>

On a MacBook with a German keyboard layout, running macOS 10.13, the key binding <kbd>Shift+Cmd+<</kbd> to focus the breadcumbs has no effect.

Focussing the breadcrumbs through the command palette works though.

Note, that Germany keyboards have a single key for `<` and `>`, where pressing the key alone results in `<` and shift-pressing the key results in `>`.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:31:26.156Z)
OS version: Darwin x64 17.7.0

Extensions: none

**Comment by jrieken** [comment]
What does VS Code detect when you press the desired key combination? Please hover over the input box and take a screenshot:
![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

**Comment by jrieken** [comment]
This is likely because we only ship polished keybindings for english keyboard layouts. You can vote on this issue which is about shipping polished layouts for other languages: https://github.com/Microsoft/vscode/issues/1240

**Comment by rherrmann** [comment]
It seems, the <kbd><</kbd> key isn't detected at all.

If I press <kbd>Cmd</kbd> <kbd>Shift</kbd> <kbd><</kbd> (in this order) the input box shows `shift+cmd+`. 
Pressing <kbd>Cmd</kbd> <kbd><</kbd> shows `cmd+`.
Pressing <kbd><</kbd> alone shows `[Backquote]`.

**Comment by rherrmann** [comment]
Not that I am aware of. I haven't installed any system services on top of the stock macOS services. Retried after quitting all applications except VSCode, but it shows the same result.

Not sure if that makes the difference, however, my macOS language preferences are set to English.

**Comment by jrieken** [comment]
Is this by any change the macOS keybinding to go through windows of one app, e.g have two browser windows open and use `cmd <` and `cmd shift <`?

**Comment by rherrmann** [comment]
No, that would be <kbd>Cmd+Shift+`</kbd>.

I experimented with two VS Code windows, <kbd>Cmd+Shift+`</kbd>, as expected, switches between them, whereas <kbd>Cmd+Shift+<</kbd> has no effect.

**Comment by jrieken** [comment]
Hm, must be something else then. The fact that the keybinding doesn't reach us, indicated that some other app or the OS consumes it. There is nothing we can do except for #1240. Closing as dupe
