### ISSUE TITLE
Git extension should warn of missing user.email and user.name

### ISSUE THREAD

**Issue by kunalsb** [Microsoft/vscode#57222]
Issue Type: <b>Bug</b>

Whenever i make any commit , it is showing "Git:failed to execute".what should I do??

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (2.41GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
team|ms-|1.136.0
material-icon-theme|PKi|3.5.3
LiveServer|rit|5.1.1

</details>

**Comment by joaomoreno** [comment]
In the dialog, there's a Show Git Output button. When you click it, it shows you the error git is facing. What is it?

**Comment by kunalsb** [comment]
--This is what is showing in the output console. I dont know how to set that user.email.Please help!!
> git commit --quiet --allow-empty-message --file -

*** Please tell me who you are.
git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'Kunal@DESKTOP-RIC83H7.(none)')
> git config --get-all user.name

**Comment by kunalsb** [comment]
Thankyou so much!!! It is working now.

**Comment by PythooonUser** [comment]
@joaomoreno Since @kunalsb seems to have fixed the problem, why was this issue reopened? Can it be closed again?

**Comment by biglovisa** [comment]
I think because
> I'll keep this issue open to improve this specific error case. We should inform the user about what he should do, whenever this happens.

**Comment by PythooonUser** [comment]
Ah, thanks. There I was too quick :)
