### ISSUE TITLE
Remember Me

### ISSUE THREAD

**Issue by dangpro-1210** [Microsoft/vscode#57221]
Issue Type: <b>Feature Request</b>

Can we add the option remember me when push to Github. I don't like to put username and password every-single-time

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

**Comment by nealot** [comment]
Git can cache your credentials: https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage

**Comment by joaomoreno** [comment]
Please use a credential manager for Git.
