### ISSUE TITLE
"Pull from..." command no longer works

### ISSUE THREAD

**Issue by zspitz** [Microsoft/vscode#57224]
Issue Type: <b>Bug</b>

Steps to reproduce:

1. Execute command **Git: Pull from...**
![image](https://user-images.githubusercontent.com/312166/44626653-d4df7380-a928-11e8-9e0b-82521687fd3f.png)

2. Prompted to choose a remote; list is displayed.
![image](https://user-images.githubusercontent.com/312166/44626654-e0cb3580-a928-11e8-9286-11c48c6a8034.png)

3. On choosing `upstrean`, the prompt is again displayed without a list
![image](https://user-images.githubusercontent.com/312166/44626663-fe989a80-a928-11e8-8e14-f2a83fe2c2b8.png)

The same behavior happens when the command is executed from the command palette, and from the **More Actions** context menu in the SCM pane.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

I've seen the same behvaior on VS Code running on Linux (Fedora 28), same VS Code version.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU B980 @ 2.40GHz (2 x 2395)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.90GB (1.23GB free)|
|Process Argv|C:\Users\win8\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by zspitz** [comment]
Not sure why vscodebot has tagged this with integrated-terminal.

**Comment by joaomoreno** [comment]
Does it work if you pick `origin`? Seems to work fine for me.

**Comment by zspitz** [comment]
@joaomoreno `origin` seems to work fine.

**Comment by joaomoreno** [comment]
So, what branches are there in the upstream remote?

```
git branch -r | grep upstream
```

**Comment by zspitz** [comment]
No `grep`; I'm on Windows.

But `git branch -r` doesn't return any `upstream` branches, even though `git remote -v` returns `upstream` entries.

**Comment by joaomoreno** [comment]
So, upstream has no branches, that's why quick open appears empty.
