### ISSUE TITLE
LF CRLF switch broken on Windows

### ISSUE THREAD

**Issue by TheBegining** [Microsoft/vscode#57220]
Issue Type: <b>Bug</b>

Hi.
I create two html file on windows .named test.1.html  test.2.html
![image](https://user-images.githubusercontent.com/17702287/44625130-1aee0480-a934-11e8-9830-6a86dba3fb06.png)
![image](https://user-images.githubusercontent.com/17702287/44625131-204b4f00-a934-11e8-9dcd-493232988382.png)
![image](https://user-images.githubusercontent.com/17702287/44625132-27725d00-a934-11e8-9886-338b410f05cb.png)
uninstall all extensions.
![image](https://user-images.githubusercontent.com/17702287/44625127-090c6180-a934-11e8-9652-39e64b643189.png)
here,we open github desktop.
![image](https://user-images.githubusercontent.com/17702287/44625136-3e18b400-a934-11e8-9630-393ad699d239.png)
![image](https://user-images.githubusercontent.com/17702287/44625137-440e9500-a934-11e8-81b2-f99d7b34c29c.png)
It looks nice.
then,we change test.1.html CRLF to LF.And Save.
![image](https://user-images.githubusercontent.com/17702287/44625154-a8315900-a934-11e8-9888-7e69dc602ef1.png)
![image](https://user-images.githubusercontent.com/17702287/44625160-d6af3400-a934-11e8-98e9-c459de86684e.png)

github desktop give a warning :line endings have change from 'LF' to 'CRLF'.
It not right.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4100M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.83GB (3.21GB free)|
|Process Argv|C:\Users\cqh\AppData\Local\Programs\Microsoft VS Code\Code.exe D:\workspace\NUT|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.5.6
tslint|eg2|1.0.36
vscode-language-pack-zh-hans|MS-|1.26.3
open-in-browser|tec|2.0.0

</details>

**Comment by joaomoreno** [comment]
Github Desktop is telling you that it will commit the file with different line endings than what you expect. VS Code is saving the file the right way. Please use a HexEditor to confirm that.
