### ISSUE TITLE
CodeLens lifetime

### ISSUE THREAD

**Issue by maziac** [Microsoft/vscode#57227]
Hi,
I'm creating a code lens extension for assembler files.
This is working quite well however I have a problem with the lifetime of the vscode.CodeLens objects.
From what I could see from the API there is no mechanism to update the object. Once it is created in e.g. resolveCodeLens it stays until vscode decides to request it again.

So how to handle the situation that a reference has been added or removed in another file.
I.e. I would like to update the references count in the command title of the code lens.
But there is no trigger for this. E.g. vscode should call resolveCodeLens if other files have changed.

**Comment by jrieken** [comment]
You use the `onDidChangeCodeLenses`-event that your provider can (optionally) offer. See https://github.com/Microsoft/vscode/blob/3f8088b5c5f1d44b5e1af4a8e67448abbe66470e/src/vs/vscode.d.ts#L2163-L2166
