### ISSUE TITLE
open editors pane blurry

### ISSUE THREAD

**Issue by anothergituser** [Microsoft/vscode#57235]
Issue Type: <b>Bug</b>

Open editors pane has blurry text, other panes are ok

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:34:20.517Z)
OS version: Linux x64 4.17.17-200.fc28.x86_64

**Comment by bpasero** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/24957
