### ISSUE TITLE
set ulimits before starting a debug session

### ISSUE THREAD

**Issue by graph** [Microsoft/vscode#57231]
sometimes my app that I'm debugging consumes too much RAM. I want my app to just die during the debug session. One way I would do this is set ulimits in bash. I don't know if this is already possible in vs code. If not it would be good to add a ulimits entry for launch.json so I can set maximum memory limits for the debug session.

**Comment by isidorn** [comment]
fyi @weinand

**Comment by weinand** [comment]
Create a shell script that sets ulimit and then call node.js and passes all command line arguments, e.g.:
```
ulimit 12345
node "$@"
```
Make sure that the script is on your PATH.

In your launch config set the `runtimeExecutable` to the name of this script.

**Comment by graph** [comment]
I'm debugging in C++. I haven't looked in starting a gdb session via shell script and connecting it to vs code. I guess I should look into that first.

**Comment by weinand** [comment]
you might want to create an issue in their repository because aluch config features like  `runtimeExecutable` are debug extension specific and what I explained for node.js dies not automatically apply for C++.
