### ISSUE TITLE
Unexpected show snippets once enter key pressed without prefix

### ISSUE THREAD

**Issue by imageslr** [Microsoft/vscode#57230]
- VSCode Version: 1.26.1
- OS Version: macOS 10.13.6

Steps to Reproduce:

1. I have a customized user snippet file `vue.json`:

```JSON
{
  "i18n support": {
    "prefix": "i18n",
    "body": [
      "<i18n>",
      "{",
      "\t\"zh\": {",
      "\t\t$1",
      "\t},",
      "\t\"en\": {",
      "\t\t$2",
      "\t}",
      "}",
      "</i18n>"
    ],
    "documentation": "vue-i18n support"
  }
}
```
2. Open a `vue` file, and press `enter` key. It will jump to a new line and show `i18n` snippet even I don't type `i18n` prefix.

![image](https://user-images.githubusercontent.com/17822028/44629317-ef910700-a97f-11e8-97f3-d2fb7ffd4199.png)

It happens when I update to the latest version. In previous version the snippet will appear only when I type `i18n`. Now it shows whenever I press `enter`. I have to disabled it.

I have searched relevant documents and questions but have no solution. Could you please view that? I will appreciate.

Does this issue occur when all extensions are disabled?: No

**Comment by jrieken** [comment]
I cannot reproduce, the completions only show explicitly being invoked

**Comment by imageslr** [comment]
Maybe next version will solve this problem. I have deleted the snippet.

**Comment by jrieken** [comment]
does that mean you can still reproduce?

**Comment by imageslr** [comment]
Yes. 

First, open `vue.json` in snippets and write: 

```JSON
{
  // Place your snippets for vue-html here. Each snippet is defined under a snippet name and has a prefix, body and
  // description. The prefix is what is used to trigger the snippet and the body will be expanded and inserted. Possible variables are:
  // $1, $2 for tab stops, $0 for the final cursor position, and ${1:label}, ${2:another} for placeholders. Placeholders with the
  // same ids are connected.
  // Example:
  "i18n support": {
    "prefix": "i18n",
    "body": [
      "<i18n>",
      "{",
      "\t\"zh\": {",
      "\t\t$1",
      "\t},",
      "\t\"en\": {",
      "\t\t$2",
      "\t}",
      "}",
      "</i18n>"
    ],
    "documentation": "vue-i18n support"
  }
}
```

Then, open any `vue` file and press `enter` key. The snippet will show:

![image](https://user-images.githubusercontent.com/17822028/44904806-c76c2400-ad42-11e8-943a-0440e7de683d.png)


Here is my enabled extensions:

![image](https://user-images.githubusercontent.com/17822028/44905044-7446a100-ad43-11e8-9c45-36c0b665de18.png)



Here is my user settings:

```JSON
{
  "workbench.iconTheme": "vscode-great-icons",
  // 控制字体系列。
  // "editor.fontFamily": "Consolas, 'Courier New', monospace,'宋体'",
  "terminal.integrated.shell.windows": "D:\\Program Files (x86)\\Git\\bin\\bash.exe", // 这里是我电脑上bash.exe的路径
  // 以像素为单位控制字号。
  "editor.fontSize": 14,
  // 控制选取范围是否有圆角
  "editor.roundedSelection": false,
  // 建议小组件的字号
  "editor.suggestFontSize": 16,
  // 在“打开的编辑器”窗格中显示的编辑器数量。将其设置为 0 可隐藏窗格。
  "explorer.openEditors.visible": 0,
  // 是否已启用自动刷新
  "git.autorefresh": true,
  // 以像素为单位控制终端的字号，这是 editor.fontSize 的默认值。
  "terminal.integrated.fontSize": 14,
  // 控制终端游标是否闪烁。
  "terminal.integrated.cursorBlinking": true,
  // 一个制表符等于的空格数。该设置在 `editor.detectIndentation` 启用时根据文件内容进行重写。
  "editor.tabSize": 2,
  "extensions.ignoreRecommendations": false,
  // 格式化配置文件
  "clang-format.executable": "/usr/local/Cellar/clang-format/2017-06-22/bin/clang-format",
  "clang-format.style": "Chromium",
  "editor.formatOnPaste": true,
  "editor.formatOnSave": true,
  // Default formatter for <template> region
  // "vetur.format.defaultFormatter.html": "js-beautify-html",
  // 关闭eslint-vue验证：Validate vue-html in <template> using eslint-plugin-vue
  //"vetur.validation.template": false,
  // vetur配置eslint
  // 添加在下面属性中的文件将会被eslint检测，错误时标红
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    // 配置.vue文件的自动修复
    {
      "language": "html",
      "autoFix": true
    },
    {
      "language": "vue",
      "autoFix": true
    }
  ],
  // 当prettier与.eslintrc中的规则冲突时，prettier不作修改
  "prettier.eslintIntegration": true,
  // 保存时自动修复，这里与上面的editor.formatOnSave会同时生效，但是顺序不确定
  "eslint.autoFixOnSave": true,
  "explorer.confirmDelete": false,
  "emmet.triggerExpansionOnTab": true,
  "files.autoSave": "off",
  "[vue]": {},
  "files.associations": {
    "*.cjson": "jsonc",
    "*.wxss": "css",
    "*.wxs": "javascript"
  },
  "emmet.includeLanguages": {
    "wxml": "html"
  },
  "minapp-vscode.disableAutoConfig": true,
  "terminal.integrated.rendererType": "dom"
}

```

My workspace settings:

```JSON
{
	"folders": [
		{
			"path": "/Users/xxx/DevelopFolder/city-center-project"
		}
	],
	"settings": {
		"explorer.autoReveal": false
	}
}
```

Dictionary settings:

```JSON
{
  "prettier.eslintIntegration": true,
  "eslint.autoFixOnSave": true
}
```

By the way, the snippet will show in **every `.vue` file**. I create a new `a.vue` file and press `enter`, it just shows.

![image](https://user-images.githubusercontent.com/17822028/44904961-3a759a80-ad43-11e8-91c7-61847fa0c33a.png)

**Comment by imageslr** [comment]
Thank you for your kind response!

**Comment by jrieken** [comment]
Hm... Can you please try this with extensions disabled?

<img width="630" alt="screen shot 2018-08-31 at 11 35 19" src="https://user-images.githubusercontent.com/1794099/44905306-f9b15d80-ad11-11e8-9bd9-611ac5b971cc.png">

**Comment by imageslr** [comment]
Reload and vs code recognizes `.vue` file as plain text. 

There is no snippet when I type `i18n`. Is that because I write the snippet file in `vue.json`?

Then I change language for `.vue` as `HTML`, but still not shows the snippet:
![image](https://user-images.githubusercontent.com/17822028/44905655-54b07800-ad45-11e8-9f3c-93a276ae2248.png)

**Comment by imageslr** [comment]
Write the snippet definition in `html.json` after setting language mode as `HTML` and shows the snippet as expected:

![image](https://user-images.githubusercontent.com/17822028/44905745-99d4aa00-ad45-11e8-9183-344a47c4b3b3.png)

**Comment by imageslr** [comment]
**Supplement**:

When I disabled `vetur` extension, it just shows like when I disabled all extensions: 

![image](https://user-images.githubusercontent.com/17822028/44905953-3008d000-ad46-11e8-90ba-a06a741dfd87.png)


So I guess it might be cause by the extension?

**Comment by jrieken** [comment]
Yeah, this will be somehow the vetur-extension. Adding @octref for more insights

**Comment by imageslr** [comment]
Thanks your prompt response! 
I would appreciate it if you could check this issue @octref .

**Comment by octref** [comment]
@jrieken We have embedded languages:

```vue
<template>  // vue-html
  <div>     // vue-html
</template> // vue-html
            // vue
<script>    // js
            // js
            // js
</script>   // js
            // vue
```

The issue is that a snippet defined for language `vue` will show up in the entire document, no matter what language the sub-region is (`vue-html`, `js`, `css`).

**Comment by octref** [comment]
Ideally, the `i18n` snippet should only show up in the vue regions, that is, any lines not occupied by the `<template>`, `<script>` and `<style>` blocks.

**Comment by jrieken** [comment]
> Open a vue file, and press enter key. It will jump to a new line and show i18n snippet even I don't type i18n prefix.

@octref That doesn't explain why pressing enter triggers snippets to be shown. Is vetur doing that? Is it adding auto trigger characters?

**Comment by octref** [comment]
@jrieken Vetur only contributes a textmate grammar that divides the vue file into regions, and mark each regions with correct embedded languages: https://github.com/vuejs/vetur/blob/master/package.json#L98-L115

AFAIK, this snippet comes from VS Code, not Vue Langauge Server. For embedded languages, if you run "Inspect TM Scope", the `language` field used to indicate which snippets will be shown.

> It worked fine in one month ago, and suddenly had this bug. I don't know why. Could you please explain?

We are looking into it.

**Comment by jrieken** [comment]
> Type JUST an enter in ANYWEHRE will show the snippet.

@octref Just that we on the same page. The issue is that pressing Enter shows snippets. It has nothing to do with scopes or grammars but with triggering . 

@imageslr We still cannot reproduce this

**Comment by imageslr** [comment]
I guess this is because scopes. @jrieken @octref 

When I define the snippet in `vue-html`, it works fine. Only typing all `i18n` inside `template` tag will trigger the snippet.

**Type Enter in anywhere. Not trigger**
![image](https://user-images.githubusercontent.com/17822028/45004520-0d193d00-b020-11e8-9bdb-6100016a7891.png)

![image](https://user-images.githubusercontent.com/17822028/45004518-025ea800-b020-11e8-8c75-3447e2fd8dd0.png)

**Type all `i18n` inside `template`. Trigger**

![image](https://user-images.githubusercontent.com/17822028/45003854-6467df00-b019-11e8-9317-a61f8f2b74db.png)

**Comment by octref** [comment]
@imageslr Just to make sure, you are typing `enter`, not `ctrl + enter` for triggering snippets?

**Comment by imageslr** [comment]
@octref Yes. If I type `ctrl + enter`, nothing happens. cursor is still in its position and doesn't jump to next line.

**Comment by octref** [comment]
> Just that we are on the same page. The issue is that pressing Enter shows snippets. It has nothing to do with scopes or grammars but with triggering .

@jrieken See above response.

**Comment by octref** [comment]
@imageslr Sorry, I think this actually works as expected. Can you tell me all the Vue extensions that you are using?

![bug](https://user-images.githubusercontent.com/4033249/45046305-9e8dac80-b02a-11e8-96c9-ac704f45d4b7.gif)

**Comment by imageslr** [comment]
@octref Hi, here is my extensions.

![image](https://user-images.githubusercontent.com/17822028/45063759-4ade9a00-b0e2-11e8-8e38-4425a4ee3e0a.png)


Here is my user settings:

```JSON
{
  "workbench.iconTheme": "vscode-great-icons",
  // 控制字体系列。
  // "editor.fontFamily": "Consolas, 'Courier New', monospace,'宋体'",
  "terminal.integrated.shell.windows": "D:\\Program Files (x86)\\Git\\bin\\bash.exe", // 这里是我电脑上bash.exe的路径
  // 以像素为单位控制字号。
  "editor.fontSize": 14,
  // 控制选取范围是否有圆角
  "editor.roundedSelection": false,
  // 建议小组件的字号
  "editor.suggestFontSize": 16,
  // 在“打开的编辑器”窗格中显示的编辑器数量。将其设置为 0 可隐藏窗格。
  "explorer.openEditors.visible": 0,
  // 是否已启用自动刷新
  "git.autorefresh": true,
  // 以像素为单位控制终端的字号，这是 editor.fontSize 的默认值。
  "terminal.integrated.fontSize": 14,
  // 控制终端游标是否闪烁。
  "terminal.integrated.cursorBlinking": true,
  // 一个制表符等于的空格数。该设置在 `editor.detectIndentation` 启用时根据文件内容进行重写。
  "editor.tabSize": 2,
  "extensions.ignoreRecommendations": false,
  // 格式化配置文件
  "clang-format.executable": "/usr/local/Cellar/clang-format/2017-06-22/bin/clang-format",
  "clang-format.style": "Chromium",
  "editor.formatOnPaste": true,
  "editor.formatOnSave": true,
  // Default formatter for <template> region
  // "vetur.format.defaultFormatter.html": "js-beautify-html",
  // 关闭eslint-vue验证：Validate vue-html in <template> using eslint-plugin-vue
  //"vetur.validation.template": false,
  // vetur配置eslint
  // 添加在下面属性中的文件将会被eslint检测，错误时标红
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    // 配置.vue文件的自动修复
    {
      "language": "html",
      "autoFix": true
    },
    {
      "language": "vue",
      "autoFix": true
    }
  ],
  // 当prettier与.eslintrc中的规则冲突时，prettier不作修改
  "prettier.eslintIntegration": true,
  // 保存时自动修复，这里与上面的editor.formatOnSave会同时生效，但是顺序不确定
  "eslint.autoFixOnSave": true,
  "explorer.confirmDelete": false,
  "emmet.triggerExpansionOnTab": true,
  "files.autoSave": "off",
  "[vue]": {},
  "files.associations": {
    "*.cjson": "jsonc",
    "*.wxss": "css",
    "*.wxs": "javascript"
  },
  "emmet.includeLanguages": {
    "wxml": "html"
  },
  "minapp-vscode.disableAutoConfig": true,
  "terminal.integrated.rendererType": "dom"
}

```

My workspace settings:

```JSON
{
	"folders": [
		{
			"path": "/Users/xxx/DevelopFolder/city-center-project"
		}
	],
	"settings": {
		"explorer.autoReveal": false
	}
}
```

Dictionary settings:

```JSON
{
  "prettier.eslintIntegration": true,
  "eslint.autoFixOnSave": true
}
```

**Comment by imageslr** [comment]
I'm not sure that it's not caused by some factors outside the editor.This problem is not very important currently for me. Just kind of inconvenient. Thank you for taking time and checking this.  : )

**Comment by octref** [comment]
@imageslr Can you use Licecap to record your screen? https://www.cockos.com/licecap/

I tried, on Windows, with this setup: VS Code 1.27 with only Vetur installed:

Pressing `Enter` here: No suggestion.

![image](https://user-images.githubusercontent.com/4033249/45328540-461a4b80-b511-11e8-8769-28b8bce70efa.png)

Pressing `Ctrl-Enter` here: Suggestion shows up, no `i18n` snippet.

![image](https://user-images.githubusercontent.com/4033249/45328579-64804700-b511-11e8-990e-c69ea2cd5722.png)

Pressing `Enter` here: No suggestion.

![image](https://user-images.githubusercontent.com/4033249/45328607-81b51580-b511-11e8-94c1-490d8529dd5f.png)

Presssing `Ctrl-Enter` here: Suggestion show up, including `i18n`.

![image](https://user-images.githubusercontent.com/4033249/45328620-8e396e00-b511-11e8-8dee-f36d0b3891fb.png)

Typing `i18n` here. Shows `i18n` snippet.

![image](https://user-images.githubusercontent.com/4033249/45328633-9abdc680-b511-11e8-9319-9da620d88789.png)

These are all working as expected. I suggest that you try disabling all other extensions and only enable Vetur and see if this is caused by some other extensions:

![image](https://user-images.githubusercontent.com/4033249/45328669-bfb23980-b511-11e8-8c8e-e4db881aa5ac.png)

**Comment by imageslr** [comment]
I'm sorry... As I disabled all extensions and only enable vetur, It does work as expected. It turns out that the extension `minapp` caused this problem for it disturbs scopes in `.vue` files.  I sincerely apologize for wasting your time.
