### ISSUE TITLE
Add a better chevron [feature request]

### ISSUE THREAD

**Issue by NavyAdmiral** [microsoft/vscode#57237]
I think  ![image](https://user-images.githubusercontent.com/40662484/44632642-3cc8a500-a98f-11e8-9700-943e4db522e0.png) is not looking very beautiful and since it's so ubiquitous in vscode, I think it should be promptly replaced with a better looking one. 
Example picture with current chevron:
![image](https://user-images.githubusercontent.com/40662484/44632717-99788f80-a990-11e8-8267-8ce06b89d41e.png)

Here's a simple chevron that imho looks better than the current one. 
![image](https://user-images.githubusercontent.com/40662484/44632657-7bf6f600-a98f-11e8-9669-c95b506b1b48.png)

cc @misolori

**Comment by fabiospampinato** [comment]
Iconography in general deserves some more love https://github.com/Microsoft/vscode/issues/8017

**Comment by misolori** [comment]
This should be handle by #79130 so marking this as a duplicate, please upvote that issue.
