### ISSUE TITLE
A bug I don't know how and why but really arose and very terrible

### ISSUE THREAD

**Issue by kalihui** [Microsoft/vscode#57236]
- VSCode Version:1.0260
- OS Version: windows 10 1803
-extesion: C/C++ for Visual Studio Code: 0.18.1
                 Chinese (Simplified) Language Pack for Visual Studio Code: 1.26.3
                 R: 0.6.1

Steps to Reproduce:

I‘m a light vscode user, my win10 is not used to write code and i use vscode for file reading and changes . I always saved my changes before i close vscode but don't close the file. 
I have a file to record all my web accounts ,the file stored on my F drive which is a Seagate 1TB Mobile Hard disk. I  use vscode to read and change it. Most times, i'm enjoy of the beautiful interface.but today when I open my vscode I happended to find my web-accounts file  become a space file! The same time   another account record file in the same foder i opened together keep well. This is the third time i lost my web-accounts file.
I don't know which condition this is: 1.the file lost and when i open vscode it build a new file with the same name; 2.Some operation deleted all the chars.  for condition1, I checked my Recycling station（the oldest file keep a data of 8/19, i'm sure when my file is all good.）I checked C:\Users\kaihui\AppData\Roaming\Code\Backups, also nothing; for condition 2, I tried ctrl +Z and some other operation to cancel the delet operation, no result either.
I tried to review my operation the last time I cloded vscode, sadly i can't remember. but i'm sure no complex operation taked except save,write code.
I want to know how i can avoid this problem. 
Thanks for your reading, Your suggestion  would be the best help for me.

**Comment by joaomoreno** [comment]
It's very unlikely that VS Code is responsible for erasing your file. Please let us know if you can reproduce that VS Code indeed erases the file. Also, make sure you use `--disable-extensions` to confirm that.

**Comment by bpasero** [comment]
Yeah sounds a lot like https://github.com/Microsoft/vscode/issues/34915 if the drive is running out of disk space. @kalihui could that have been the case here?
