### ISSUE TITLE
How do I know what version I'm running?

### ISSUE THREAD

**Issue by clarkkarenl** [Microsoft/vscode#57233]
Issue Type: <b>Feature Request</b>

A message popped up in the lower right hand corner telling me I was running the global version of the application, but should instead use the User version (which I didn't realize was possible since the global verson was uninstalled). I've  switched to what I think is the correct version, but no where in the UI including in About... or Settings...  does it indicate I have the User version. Can you please add an indicator of this -- even just some initials in the corner of the About page -- so it's easier to tell? Thank you!

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

**Comment by joaomoreno** [comment]
Let's put it in the About dialog :+1:

**Comment by clarkkarenl** [comment]
Fabulous! Thank you @joaomoreno
