### ISSUE TITLE
Test built-in "LOADED SCRIPTS" view

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#57249]
- [x] macOS @roblourens 
- [x] linux @isidorn 
- [x] windows @alexandrudima

Complexity: 3
Ref: #55650

Authors: @weinand

We have moved the LoadedScripts view from node-debug into VS Code core.

In addition we have improved the way how the tree of loaded scripts is built by hiding all intermediate folder nodes if they only have one child. 

Verify that:
- loaded scripts are shown correctly for node and chrome debuggers,
- multiple root folders are shown as an additional tree level if there are more than one,
- multiple debug sessions add an additional level to the tree (which is not removed if the number of sessions drops to one again),
- the new algorithm for minimising the number of folders with one child works and is useful,
- find everything that is missing from the new implementation that make the LoadedScripts view behave differently than the VS Code explorer. E.g. hover, click behaviour, accessibility, etc.

**Comment by roblourens** [comment]
It's not working well for me, I think just because of https://github.com/Microsoft/vscode/issues/57401. So I'll test tomorrow when that's fixed.

**Comment by roblourens** [comment]
Tested with the private build
