### ISSUE TITLE
Intellisense does not pickup Typescript 3 references

### ISSUE THREAD

**Issue by tommedema** [Microsoft/vscode#57242]
- VSCode Version: 1.26.1
- OS Version: OSX High Sierra 

Steps to Reproduce:

1. `git clone git@github.com:tommedema/serverless-mono-example.git`
2. `cd serverless-mono-example && yarn install && code .`
3. if you change a typing in package `random`, it is not picked up by intellisense in typescript packages that reference to it in the same workspace (e.g. `sls-random`); you'd have to compile first

for example, change `fetchRandomNumber` in `random` to return a `Promise<string>`, and `sls-random` still expects a `Promise<number>`

Note that `sls-random` is connected with `random` through Typescript 3 references:

```
{
  "extends": "../../tsconfig.settings.json",
  "compilerOptions": {
    "outDir": "dist",
    "rootDir": "src"
  },
  "references": [
    { "path": "../random" }
  ]
}
```

And therefore intellisense should pickup the referenced typings dynamically.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#26913
