### ISSUE TITLE
VisualStudioCodeがぼやける

### ISSUE THREAD

**Issue by muraomakoto46** [Microsoft/vscode#57244]
Issue Type: <b>Bug</b>

ぼやけて字がよく読めない。
Atomのほうがマシだ。

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (23.99GB free)|
|Process Argv|C:\Users\村尾誠\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-ja|MS-|1.26.3
java|red|0.29.0
vscode-java-debug|vsc|0.11.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.8.0
vscode-maven|vsc|0.10.0

</details>

**Comment by dbaeumer** [comment]
@muraomakoto46 can you please provide the description in English

**Comment by dbaeumer** [comment]
Translation is I can't read the blurred character well.

Sounds like a dug of https://github.com/Microsoft/vscode/issues/57243 @muraomakoto46

**Comment by dbaeumer** [comment]
Closing as dup
