### ISSUE TITLE
Extension enable/disable for project

### ISSUE THREAD

**Issue by seanmars** [Microsoft/vscode#57240]
Can we have a list of template for set of extension enabled/disabled setting and in use/workspace can setting and switch what the template of extension set we want to use?
Like the default template is enable all extension, c# template is enable what about c# needed only.
And i can just setting all my c# project to use the c# template extension.

**Comment by sandy081** [comment]
@seanmars Not sure what you are asking for, but you can disable or enable extension per workspace. Let me know if this is what you are looking for

**Comment by seanmars** [comment]
@sandy081 Hi, Just like the color theme, can let we setting the extension enable or disable and save the status of extension then we can apply this status to other project.

**Comment by sandy081** [comment]
Extension enablement status is saved in local storage. I do not think we will have plans to move that to Settings.
