### ISSUE TITLE
Feature Request: Easily access to All Release notes from vscode

### ISSUE THREAD

**Issue by AdrieanKhisbe** [Microsoft/vscode#57248]
Currently you can access to last release note after updating vscode or by running the `Show Release Note` command.
However you cannot access to previous release note from vscode (at least I didn't find), just to the last one.
You can now browse them from the [repo](https://github.com/Microsoft/vscode-docs/tree/vnext/release-notes) but it would be nice if that could be done directly from vscode.

This would be a nice to have 😃 
(I could help to implement this if given some guidance)

**Comment by AdrieanKhisbe** [comment]
(@vscodebot Not sure the tag is relevant, ad the duplicate match seems false positive :) )

**Comment by dbaeumer** [comment]
Assuming that this is owned by @mattbierner due to Git history.

**Comment by mjbvz** [comment]
Prior release notes are available on our website or in the vscode docs repo
