### ISSUE TITLE
 Invalid start index: 1

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#57246]
Issue Id: <b>c06739bf-96b3-ca5f-4d05-b7dfe734ac7a</b><br /><br />*Versions* <br />- 207ace21dfec3dccab52f1296a3880ac7644c978<br />-  493869ee8e8a846b0855873886fc79d480d342de<br />-  4e9361845dc28659923a300945f84731393e210d<br />-  a8033aaf216d684d775e058489d25186702d28e3<br />-  aceb8771b1c0e116f684091986ad25769bdc0537<br />-  c827480be25bd63065e7ee2e106c24a707c08004<br />-  4fa62b246c4305b4ca00507551f77c58135ce928<br />-  c2ddece6536330f4b4ceef33de5eea6e406fb30a<br />-  21ddb4843b2f40e3cd82500794dc9a1b9404717d<br />-  bda8a4de93278004d6d7c3628b92664f93f7e811<br />*Stack* <br />Error: Invalid start index: 1<br />[/vs/base/browser/ui/list/listWidget.ts#951:9 (splice)](https://github.com/microsoft/vscode/blob/207ace21dfec3dccab52f1296a3880ac7644c978/src/vs/base/browser/ui/list/listWidget.ts#L951:9 (splice))<br />[/vs/editor/contrib/suggest/suggestWidget.ts#598:13](https://github.com/microsoft/vscode/blob/207ace21dfec3dccab52f1296a3880ac7644c978/src/vs/editor/contrib/suggest/suggestWidget.ts#L598:13)<br />    at <anonymous><br />    at process._tickCallback (aaaaaaaaaaaaaaaaaaaaaaaaaaaaa:188:7)<br />

**Comment by bpasero** [comment]
@joaomoreno this does not provide a lot of context, but became our number 2 top crash in error telemetry. Maybe we need to add more logging to get behind it?

**Comment by joaomoreno** [comment]
@bpasero This is an issue with the suggest widget.

**Comment by ramya-rao-a** [comment]
@patr0nus has a good set of repro steps in #57617

@joaomoreno 
When an item from a list is selected, the list gets focus, and the corresponding event handler is called. If the event handler deals with promises, then by the time the promise is resolved, the list is gone.

Should we probably have a way of identifying if the list got focus due to selection vs other cases?

**Comment by joaomoreno** [comment]
> If the event handler deals with promises, then by the time the promise is resolved, the list is gone.

> Should we probably have a way of identifying if the list got focus due to selection vs other cases?

I don't understand how the two things are related. If there is code which might access the list after it's been disposed, its caller should beware of this. It doesn't seem related to focus or selection at all.
