### ISSUE TITLE
August Endgame

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#57245]
**August 27th**: Code freeze for the endgame
**August 31th**: Endgame done

> **Note:** The `Insiders` build needs to be in the wild for 24 hours before we can enter the last phase of the endgame.

##### Monday
- [x] Run [OSS tool](https://github.com/Microsoft/vscode-distro/blob/master/distro-tools/README.md) **@bpasero**
  - *The LCA review of the ThirdPartyNotices.txt files is not needed anymore*
- [x] Code freeze at 5pm PT
- [x] Ensure we have a green build on all platforms at 5pm PT
- [x] All test items contain sufficiently comprehensive test descriptions by 6pm PT
- [x] Update your availability for testing here - https://vscode-tools.azurewebsites.net/

##### Tuesday
- [x] [Test plan items assigned](https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Atestplan-item+milestone%3A%22August+2018%22+) @bpasero
- [x] All closed feature-requests either have a `verification-needed` or `on-testplan` tag
- [x] Test build starts at 7am CET
- [x] Test plan ready by 8am CET
- [x] Testing
- [x] [Verification needed](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+-label%3Averified+is%3Aclosed+label%3Averification-needed)

##### Wednesday
- [x] Testing
- [x] Remind team members to assign issues that they intend to fix to the current milestone
- [x] Fixing (self-assigned, milestone assigned)
- [x] [Verification needed](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+-label%3Averified+is%3Aclosed+label%3Averification-needed)
- [x] [Verification](https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Abug+-label%3Averified+-label%3Aon-testplan+is%3Aclosed+-label%3Aerror-telemetry+-label%3Aduplicate+-label%3A*duplicate+-label%3Ainvalid+-label%3Aas-designed+milestone%3A%22August+2018%22+)

##### Thursday
- [x] Fixing (scrutiny sets in - major bugs only - to be discussed in stand-up meeting, labeled as `candidate`)
- [x] [Verification needed](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+-label%3Averified+is%3Aclosed+label%3Averification-needed)
- [x] [Verification](https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Abug+-label%3Averified+-label%3Aon-testplan+is%3Aclosed+-label%3Aerror-telemetry+-label%3Aduplicate+-label%3A*duplicate+-label%3Ainvalid+-label%3Aas-designed+milestone%3A%22August+2018%22+)
- [x] Check new OSS usage is entered into the [OSS registry](https://ossmsft.visualstudio.com/_apps/hub/ms.vss-oss-web.hub-oss) **@bpasero**

##### Friday
- [x] Pause scheduled `insider` builds **@bpasero**
- Satellite modules/npm packages ready, version updated, smoke tested
  - [x] vscode **@bpasero**
  - [x] yo generator **@aeschli**
  - [x] vsce **@joaomoreno**
  - [x] node debug **@weinand**
  - [x] node debug2 **@roblourens**
  - [x] node debugadapter node **@weinand**
- [x] All issues [verified](https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Abug+-label%3Averified+-label%3Aon-testplan+is%3Aclosed+-label%3Aerror-telemetry+-label%3Aduplicate+-label%3A*duplicate+-label%3Ainvalid+-label%3Aas-designed+milestone%3A%22August+2018%22+)
- [x] Fixing (only critical bugs)
- [Smoketest](https://github.com/Microsoft/vscode/wiki/Smoke-Test)
  - [x] Windows - @dbaeumer 
  - [x] OS X - @alexandrudima 
  - [x] Linux - @sandy081 
- [ ] All release notes updated
  - release notes are collected in a file named [*`v1_27.md`*](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_27.md) in this [repo directory](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/)
  - [x] @aeschli
  - [x] @alexandrudima
  - [x] @bpasero
  - [x] @chrmarti
  - [x] @dbaeumer
  - [ ] @egamma
  - [x] @isidorn
  - [x] @joaomoreno
  - [x] @jrieken
  - [x] @kieferrm
  - [ ] @mjbvz
  - [x] @octref
  - [x] @ramya-rao-a
  - [ ] @rebornix 
  - [x] @rmacfarlane
  - [x] @roblourens
  - [x] @sandy081
  - [x] @sbatten
  - [x] @tyriar
  - [x] @weinand
- [ ] Acknowledge pull requests in release notes. We acknowledge PRs from outside the team. Use the [thankyou](https://vscode-tools.azurewebsites.net/#acknowledgePRs) tool to generate the initial contents of the section. **owner**
  - [x] vscode **@bpasero**
  - [x] vscode-node-debug **@weinand**
  - [x] vscode-node-debug2 **@roblourens**
  - [x] vscode-debugadapter-node **@weinand**
  - [x] debug-adapter-protocol **@weinand**
  - [x] vscode-languageserver-node **@dbaeumer**
  - [x] language-server-protocol **@dbaeumer**
  - [x] vscode-textmate **@alexandrudima**
  - [x] vscode-loader **@alexandrudima**
  - [x] vscode-generator-code **@aeschli**
  - [x] vscode-vsce **@joaomoreno**
  - [ ] vscode-docs **@gregvanl**
  - [x] vscode-css-languageservice **@aeschli**
  - [x] vscode-json-languageservice **@aeschli**
  - [x] vscode-html-languageservice **@aeschli**
  - [x] jsonc-parser **@aeschli**
  - [ ] vscode-jscs **@chrisdias**
  - [ ] vscode-tslint **@egamma**
  - [x] vscode-eslint **@dbaeumer**
  - [x] vscode-jshint **@rmacfarlane**
  - [ ] vscode-recipes **@auchenberg**
  - [ ] localization **@danyeh**
  - [x] vscode-github-issues-prs **@chrmarti**
- [ ] Add notable fixes to the release notes **all**
- When done fixing/verifying and there are changes since last build at the end of day PT
  - [x] Trigger new insider build and publish it manually **@bpasero**

  ##### Friday/Monday
- [x] Redmond: Labor day on Monday
- [x] Branch code to `release/<x.y> **@bpasero**
- [x] Bump up the version in package.json - **@bpasero**
- [x] Announce master is open for business **@bpasero**
- [x] Let Daniel Ye know that the release branch `release/<x.y>` got created and that translation should be pulled from there and that the pull request has to be created against that branch **@bpasero**
- [x] Polish release notes **redmond**

##### Monday - Wednesday
- [ ] Polish release notes **redmond**
- [x] Cherry-pick hand-picked and reviewed changes to `release/<x.y>` **@bpasero**
- [x] Build `Insider` from `release/<x.y>` **@bpasero**
- [x] Manually release `Insider` **@bpasero**
- [ ] Documentation updated
  - [x] @aeschli
  - [x] @alexandrudima
  - [x] @bpasero
  - [x] @chrmarti
  - [ ] @dbaeumer
  - [ ] @egamma
  - [x] @isidorn
  - [x] @joaomoreno
  - [x] @jrieken
  - [ ] @kieferrm
  - [ ] @mjbvz
  - [ ] @octref
  - [x] @ramya-rao-a
  - [ ] @rebornix 
  - [x] @rmacfarlane
  - [x] @roblourens
  - [ ] @sandy081
  - [ ] @sbatten
  - [x] @tyriar
  - [x] @weinand

> **Note:** The `Insiders` build needs to be in the wild for 24 hours before we can enter the last phase of the endgame.

##### Wednesday/Thursday
- [x] Build stable for all platforms **@bpasero**
- [x] Make [rpm signing request](https://github.com/Microsoft/vscode-distro/blob/master/linux-repo/README.md) **@Tyriar**
- [x] Sanity check of installable bits
  - [x] Windows
    - [x] signed installer 32-bit **@bpasero**
    - [x] signed installer 64-bit **@bpasero**
	- [x] signed user installer 32-bit **@bpasero**
    - [x] signed user installer 64-bit **@bpasero**
    - [x] zip 32-bit **@bpasero**
    - [x] zip 64-bit **@bpasero**
  - [x] OS X - **@bpasero**
  - [x] Linux
    - [x] deb package 32-bit **owner**
    - [x] deb package 64-bit **@bpasero**
    - [x] rpm package 64-bit **owner**
    - [x] rpm package 32-bit **owner**
    - [x] archives **owner**
- [x] Publish website **@gregvanl**
- [x] Publish to stable **@octref**
- [x] Add a git tag to `HEAD` of `release/<x.y>` in format `x.y.z` (for vscode.d.ts download)  **@octref**
- [x] Publish deb and rpms to repositories manually **@Tyriar**
- [x] Enable scheduled `insider` builds **@octref**
- [x] Twitter announcement **@seanmcbreen**

**Comment by endgame** [comment]
Am I going to get subscribed to one of these every month? `=/`

**Comment by beastdestroyer** [comment]
Since they @ you, probably :P

**Comment by chrmarti** [comment]
@owner is in the same boat. ^^

**Comment by bpasero** [comment]
Sorry, will not happen again.

**Comment by Mlocik97-issues** [comment]
maybe you can do something like @#_ms-endgame

**Comment by jens1o** [comment]
Will the release be delayed?

**Comment by egamma** [comment]
@oneslash vscode-go is an important extension. It is driven by a broad community and this extension acknowledges contributions in the [Change Log](https://marketplace.visualstudio.com/items/ms-vscode.Go/changelog) of the extension.

**Comment by jens1o** [comment]
@egamma Well, you want to ship tomorrow, but there are many checkboxes(tasks) that are not done, yet.

**Comment by egamma** [comment]
@jens1o I appreciate that you track our progress, but you are off-by-one week 😎 . 

The endgame is done August 31 and we ship the week after the endgame. From [inside an iteration](https://github.com/Microsoft/vscode/wiki/Development-Process#inside-an-iteration):

![image](https://user-images.githubusercontent.com/172399/44850327-1e97c900-ac5d-11e8-9764-31c56226b665.png)

**Comment by jens1o** [comment]
Is this workflow new? Did I missed something?

**Comment by endgame** [comment]
@bpasero Thanks very much. I'm curious how you're fixing this - are you updating your processes, trying to get GH to change, or something else?

**Comment by bpasero** [comment]
@endgame we have a template in our wiki (https://github.com/Microsoft/vscode/wiki/Running-the-Endgame) that I just blindly copied from and that template included placeholders for endgame, redmond, etc with a `@` as prefix. I removed that prefix so that in the future this should not happen again.

**Comment by myfairsyer** [comment]
@endgame See https://github.com/Microsoft/vscode-wiki/commit/17b1e717d321fbe139655cd70ec9dcc952708569#diff-e877b64867bbefcd578947aec1fb7d01
