### ISSUE TITLE
extra quote added when use Chinese Input Method

### ISSUE THREAD

**Issue by hefei00** [Microsoft/vscode#57250]
- VSCode Version: 1.26.1
- OS Version: macOS Sierra 10.12.1

Steps to Reproduce:

1.  open a empty .js file
2. enter `const str = ''`
3. change the input method to Chinese Input Method
4. enter some words, but don't choose them, then press the backspace key to delete the input to empty
5. there is a extra quote left

here is a gif

![default](https://user-images.githubusercontent.com/3992113/44646505-cd45ca80-aa0d-11e8-9471-3fdb83ced979.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by hefei00** [comment]
I am sure the issue is not same with #26527 or #40344.

**Comment by alexandrudima** [comment]
@rebornix Could this be a regression introduced via https://github.com/Microsoft/vscode/commit/2d0bbd3a926d9c42b15dc03c7d6e1d7a2b0dba6f#diff-f8aa0da950270e2d56baecaf5819a4c5

**Comment by rebornix** [comment]
Since we don't know if users quit the composition mode, we should do auto close less aggressively for compositions. For this case, if the cursor is before a closing brace, we don't do auto close like what we usually do for non-composition mode.
