### ISSUE TITLE
"Debug session already running" error

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#57255]
In the course of fixing #49403 I was trying to supress an attach timeout message in this code: https://github.com/Microsoft/vscode/blob/e8b3a72e8306105a4d559d2e85b36cec13dcb10d/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L696-L725

First I did something similar as this https://github.com/Microsoft/vscode/blob/e8b3a72e8306105a4d559d2e85b36cec13dcb10d/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L696-L699

When testing this I noticed that after running once through the `return TPromise.as(null);` the next debug session (for the same debug config) would result in the error message "Debug session xxxx already running".

Moving my code to the very end of that code section fixed the problem for me:
https://github.com/Microsoft/vscode/blob/e8b3a72e8306105a4d559d2e85b36cec13dcb10d/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L720-L724

So I suspect that the code https://github.com/Microsoft/vscode/blob/e8b3a72e8306105a4d559d2e85b36cec13dcb10d/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L709-L713 is needed to clean all traces of a debug session.

Since there was already some issue with a spurious "Debug session already running" error, please make sure that https://github.com/Microsoft/vscode/blob/e8b3a72e8306105a4d559d2e85b36cec13dcb10d/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L696-L699 really works correctly (may be by just moving it down).

**Comment by octref** [comment]
I'm not sure how to verify this. Don't quite have the setup for #54378 either.
@weinand Can you code-review verify this issue? Thanks.

**Comment by weinand** [comment]
Yes, I've verified and code-reviewed this.

**Comment by DanTup** [comment]
There's a report of this issue still occurring in v1.27.0 here -> https://github.com/Microsoft/vscode/issues/54378#issuecomment-418881419

Not sure if it's expected to be gone in that version.
