### ISSUE TITLE
使用VScode 在开发react native应用时的设备选择

### ISSUE THREAD

**Issue by refiny** [Microsoft/vscode#57259]
Issue Type: <b>Performance Issue</b>

在启用react native工程中，已设置好debug android, F5启动之后，在output里输入如下：
[Warning] Target simulator is not supported for Android platform. If you want to use particular device or simulator for launching Android app, please specify  device id (as in 'adb devices' output) instead.

[Info] local.properties file doesn't exist. Using Android SDK location from PATH.

[Info] Starting React Native Packager.

Scanning folders for symlinks in e:\ReactNative\hoya\node_modules (128ms)
Could not find device with the id: "simulator".
Choose one of the following:
[ '621QECQ93YKYS' ]
根据提示，我只要选择了设备，就可以正常往下推进，但这是一个输出框，我如何选择目标设备？

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (9.51GB free)|
|Process Argv|D:\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    86	  8724	code main
    1	    57	  3836	   gpu-process
    0	    67	  4620	   window (Issue Reporter)
    0	    64	  8256	   shared-process
    0	   174	 11420	   window (launch.json - hoya - Visual Studio Code [Administrator])
    0	    33	  1488	     searchService
    0	    11	  2252	     watcherService 
    0	    65	  8360	     extensionHost
    0	    39	 10424	       electron_node jsonServerMain.js 
    0	     5	 10436	       adb -s 621QECQ93YKYS logcat *:S ReactNative:V ReactNativeJS:V
    0	     4	 12228	       C:\windows\system32\cmd.exe /c react-native.cmd start --port 8081
    0	   193	 12236	         node   "C:\Users\fangwei.ren\AppData\Roaming\npm\\node_modules\react-native-cli\index.js" start --port 8081
    0	    21	  3280	           electron_node child.js 
    0	    21	 12256	           electron_node child.js 
    0	    21	 12260	           electron_node child.js 
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (launch.json - hoya - Visual Studio Code [Administrator])
|    Folder (hoya): 3509 files
|      File types: xml(1396) png(1016) json(330) class(296) jar(120) so(108)
|                  java(36) js(33) ttf(33) txt(30)
|      Conf files: package.json(1) launch.json(1)
|      Launch Configs: reactnative;
```

</details>
<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.5.0
vscode-babel-coloring|dza|0.0.4
tslint|eg2|1.0.37
beautify|Hoo|1.3.2
vscode-language-babel|mgm|0.0.20
debugger-for-chrome|msj|4.8.2
vscode-react-native|vsm|0.6.14

</details>

**Comment by dbaeumer** [comment]
I am pretty confident that this is caused bu the vacode-react-native extension. Please report the issue there since VS Code doesn't ship with such a support out of the box.

Please ping if you think otherwise.
