### ISSUE TITLE
*.md opened in Preview forgets scroll position

### ISSUE THREAD

**Issue by dreitzner** [Microsoft/vscode#57254]
- VSCode Version: 1.26.1
- OS Version: Windows 10 PRO (1803)

Steps to Reproduce:

1. Open a *.md file in preview and some other files
2. Scroll in the *.md file
3. switch tabs back and forth
4. *.md file in preview looses scroll position

Does this issue occur when all extensions are disabled?: Yes

**Comment by dreitzner** [comment]
Checked the Experimental duplicate detection, none match

**Comment by mjbvz** [comment]
Possible fixed. Does this still reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?
