### ISSUE TITLE
Revisit chokidars multi-root handling

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#57256]
I suggest to revert the changes made in https://github.com/Microsoft/vscode/commit/44aa6c8aac6207f4e4d057287fa8a4cca18c7550#diff-5597965d68c27aafaea58151986d39c2 and instead leverage the NSFW watcher service for anything multi-root related.

**Comment by aeschli** [comment]
@bpasero I'd prefer to improve my changes in chockidar. Switching to NSFW is another story, especially as we are also not convinced of its correctness.

**Comment by paulmillr** [comment]
Be glad to help with chokidar stuff.

**Comment by aeschli** [comment]
@paulmillr Hi Paul, cool, thanks a lot for offering help. The change that Ben wants me to improve is actually in a wrapper around chockidar:
We need the capability to listen to multiple root folders (possibly nested) where each folder has it's set of 'ignore' patterns. We currently do that by manually filtering the output of the watcher, but of course, it would be much more efficient if that's done on the watcher level.

I created https://github.com/paulmillr/chokidar/issues/767 as a reference.
