### ISSUE TITLE
文件列表比较多时，sftp Download问题

### ISSUE THREAD

**Issue by mai00dou** [Microsoft/vscode#57252]
Issue Type: <b>Feature Request</b>

文件比较多，没有空白区域时，更新所有文件不友好，

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:03:31.083Z)
OS version: Darwin x64 17.7.0

**Comment by dbaeumer** [comment]
@mai00dou can you please provide the description in English?

**Comment by beastdestroyer** [comment]
@dbaeumer I believe they are talking about the experience when many files are open at once (part of it talks about "file lists"?) , I think they're trying to say it's lagging? But I do know they said the experience isn't good. I don't know what they mean by "sftp download"

**Comment by mai00dou** [comment]
<img width="454" alt="files_not_fill_screen" src="https://user-images.githubusercontent.com/9097858/44654913-f2463780-aa25-11e8-9b96-68d1ed989a2c.png">
 fig 1
<img width="433" alt="files_fill_screen" src="https://user-images.githubusercontent.com/9097858/44654917-f40ffb00-aa25-11e8-93f0-335170fb508b.png">
fig2

If the files not fill the screen in the picture 1, I can click the bottom blank area to upload or download files from server to my computer easily, but  in picture 2 ,When I have clicked the file, I can not upload or download all files.

**Comment by dbaeumer** [comment]
@mai00dou this looks like a problem with the SFTP extension. VS Code itself doesn't provide these context menu entries. Can you please report the problem to them.
