### ISSUE TITLE
shortcut to stop container docker

### ISSUE THREAD

**Issue by beardstudio** [Microsoft/vscode#57266]
Issue Type: <b>Bug</b>

I cannot use the ctrl+c to stop a container in the terminal of vs. Is there another possibility as shortcut to avoid docker stop id?

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:31:26.156Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-twig-pack|baj|1.0.0
auto-rename-tag|for|0.0.15
sublime-keybindings|ms-|4.0.0
debugger-for-chrome|msj|4.8.2
snippet-creator|nik|0.0.4
vscode-docker|Pet|0.1.0

</details>

**Comment by Tyriar** [comment]
How do you do it in other terminals?

**Comment by Tyriar** [comment]
Also are you launching through the vscode-docker ext?

**Comment by beardstudio** [comment]
Genrally, I do ctrl+c to stop the container (in the classical terminal of mac). I tried on the terminal included in vs and here, it doesn't work.

**Comment by Tyriar** [comment]
I recently changes how processes exit in the terminal in https://github.com/Microsoft/vscode/issues/56217, could you run the latest [Insiders](https://code.visualstudio.com/insiders/) and see if it happens there?

**Comment by beardstudio** [comment]
Yes, it works. Many thanks for that.
