### ISSUE TITLE
Minimap is offset when in full-screen

### ISSUE THREAD

**Issue by sguillia** [Microsoft/vscode#57265]
The minimap slider is offset when editing a huge file in full-screen mode.

By offset, I mean that the slider does not reflect the actual portion of code that is shown in the editor.

By huge, I mean a file that the minimap cannot display entirely so it needs to scroll.

**Steps to reproduce** 
Follow this screen recording

![project-minimap](https://user-images.githubusercontent.com/15984272/44660896-527ab080-aa09-11e8-95f5-4bc60fede3ec.gif)

1. Open a file with about 500 lines with VS Code. I used [your code](https://github.com/Microsoft/vscode/blob/master/src/main.js) for the demo.
2. Play with the minimap
2a. Watch as the minimap itself scrolls, this is normal
2b. The minimap is not offset at this point
3. Go full-screen (press F11)
4. Play with the minimap
4a. Watch as the minimap doesn't scroll anymore (this may be the bug)
4b. The minimap shows the wrong part of the code

I failed to reproduce with a file of 1000 lines, so I guess screen resolution, zoom level and source code length are tightly correlated. If you can't reproduce, try with shorter or longer files. I tested with 1920x1080 resolution.

Note that I had the following setting while recording, but it doesn't change anything:
`"editor.minimap.showSlider": "always"`

Does this issue occur when all extensions are disabled?: Yes

VS Code version: Code - Insiders 1.27.0-insider (3f8088b5c5f1d44b5e1af4a8e67448abbe66470e, 2018-08-27T07:36:47.732Z)
OS version: Windows_NT x64 10.0.15063

**Comment by alexandrudima** [comment]
@sguillia This might be very tricky to reproduce. I've tried yesterday on macOS and now have just spent 5 minutes playing with it on Windows, but I could not get it to reproduce. Are there any errors in the console (F1 > Developer: Toggle Developer Tools) when you can reproduce?

**Comment by sguillia** [comment]
I agree this is tricky to reproduce. At the time I created the issue it wasn't, but now on Insiders 1.28 I had a hard time to see it again.

The problem appeared somewhat randomly after 5 minutes playing around, but is present no matter if VS Code is in full screen or not.

I will test on macOS in one or two weeks.

There are 297 errors and two warnings in the developer console but I think they are all related to extensions (all are prefixed with `[Extension Host]`. Nothing related to this.

**Comment by alexandrudima** [comment]
:+1: Please keep an eye out, it might have been a mix of factors. LMK here if you see anything relevant to help reproduce.
