### ISSUE TITLE
Context menu by keyboard

### ISSUE THREAD

**Issue by mliv-cloud** [Microsoft/vscode#57264]
Issue Type: <b>Bug</b>

I get different context menu on launching by keyboard and mouse. 

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.14393

<details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.9
cake-vscode|cak|0.11.4
path-intellisense|chr|1.4.2
githistory|don|0.4.2
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.36
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.6.1
angular-essentials|joh|0.4.0
Angular2|joh|6.1.5
vscode-kubernetes-tools|ms-|0.1.12
csharp|ms-|1.15.2
PowerShell|ms-|1.8.3
debugger-for-chrome|msj|4.8.2
angular2-inline|nat|0.0.17
vscode-docker|Pet|0.1.0
material-icon-theme|PKi|3.5.3
vscode-yaml|red|0.0.14
postcss|ric|2.0.0

(1 theme extensions excluded)

</details>

**Comment by dbaeumer** [comment]
@mliv-cloud can you please provider more information. How do you launch VS Code in detail. Which context menu is different?

**Comment by dbaeumer** [comment]
I am closing the issue since the necessary information was not provided.
