### ISSUE TITLE
Detect large images and show progress while opening them

### ISSUE THREAD

**Issue by yyjazsf** [Microsoft/vscode#5726]
- VSCode Version:insider 1.0.1
- OS Version: OSX 10.11.4

Steps to Reproduce:

1. open a big img in project folder(9.6M  jpg)
2. vsc should be show me a dialog(cancel reopen close)

maybe if it's big img,open it with system soft

**Comment by bpasero** [comment]
@yyjazsf why would you want to see a dialog?

**Comment by yyjazsf** [comment]
sorry,I mean that when I open a big img file,the vsc show a dialog,vsc spend long time to open it,why not open it with system soft(when it is big img)?

**Comment by bpasero** [comment]
I see, thanks.

**Comment by bpasero** [comment]
Closing, I decided to block large images from loading due to memory consumption concerns. The limit is currently 1 MB.
