### ISSUE TITLE
Windows Logon-Screen Bug

### ISSUE THREAD

**Issue by ginodola** [Microsoft/vscode#57262]
Issue Type: <b>Bug</b>

In Visual Studio Code muss eine Datei geöffnet sein.
Über die Hotkeys WINDOWS-LOGOTASTE-TASTE + PUNKT (.) öffnet sich ein Popup mit Emojis.
Hält man die WINDOWS-LOHOTASTE GEDRÜCKT und drückt nun L, bleibt das Popup mit den Emojis geöffnet und ist auf der Windows-Logon Seite sichtbar und bedienbar!

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:37:28.532Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4900MQ CPU @ 2.80GHz (8 x 2794)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.91GB (24.96GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|0.8.8
tslint|eg2|1.0.37
php-intellisense|fel|2.3.4
vscode-git-blamer|how|1.1.2
twig-language-2|mbl|0.3.1
quicksnippet|mou|0.0.1
vscode-language-pack-de|MS-|1.26.3
debugger-for-chrome|msj|4.8.2
php-docblocker|nei|1.6.0
twig|wha|1.0.2

</details>

**Comment by dbaeumer** [comment]
@ginodola can you please report the issue to the Windows team. I also reproduce for me with other tools open (for example FireFox) so it is not releated to VS Code.
