### ISSUE TITLE
Node.js Debugging fails - Request VSCodeAdapterService.nodeFork failed unexpectedly

### ISSUE THREAD

**Issue by johnpapa** [Microsoft/vscode#57268]
Steps to Reproduce:

1. Open node project
2. Press F5 (choose node)

Does this issue occur when all extensions are disabled?: Yes/No
No - how do i tell which may cause it?

```
Vs Code Insiders 
Version 1.27.0-insider (1.27.0-insider)
```

When running a simple node express app and starting the debugger, I get this error

`Request VSCodeAdapterService.nodeFork failed unexpectedly without providing any details.`

and the debugger seems to hang. See video below.
![2018-08-27_09-24-26](https://user-images.githubusercontent.com/1202528/44662247-35c78400-a9db-11e8-9bab-437be189183e.gif)

**Comment by johnpapa** [comment]
I disabled the VS Live Share Extension pack and the debugger works again.

![image](https://user-images.githubusercontent.com/1202528/44663159-bbe4ca00-a9dd-11e8-8aa5-7757b8cc8221.png)


Cross posting there now ...

**Comment by weinand** [comment]
Yes, this is a LiveShare issue.

**Comment by johnpapa** [comment]
Thanks @weinand

**Comment by singcl** [comment]
Thanks @johnpapa I have the same problem.
