### ISSUE TITLE
Feature Request: Ability to split sidebar vertically

### ISSUE THREAD

**Issue by mrjones2014** [Microsoft/vscode#57269]
It would be really nice to be able to "split" the sidebar like you can the editor windows. For example, to be able to have the explorer sidebar take up the top half of the sidebar, and the debug sidebar on the bottom half of the sidebar.

This could work just like the "split editor" feature already works, except it probably would only make sense to split the sidebar vertically.

It could also have the little collapsible sidebar sections like already exist within each sidebar, but to collapse the entire sidebar section; e.g. if you have explorer as top half of sidebar and debug as bottom half of sidebar, you could be able to expand/collapse the debug section or explorer section.

**Comment by mrjones2014** [comment]
This feature request is not a duplicate. While it's _similar_ to #45866, I don't want a _second_ sidebar, but rather, the ability to split a single sidebar like you can split editor windows.

**Comment by Dgc2002** [comment]
I'm confused as to what happened here.  
  
@vscodebot incorrectly detected this as a duplicate of #45866 which @mrjones2014 clarified was an incorrect duplicate. Then @bpasero was assigned and manually marked it as duplicate then @vscodebot closed it. Let me know if I'm misunderstanding anything. 
  
As I understand it this isn't a duplicate and @mrjones2014 is requesting something similar to what IntelliJ IDEs offer:  
  
![image](https://user-images.githubusercontent.com/33530109/45383711-a07ae100-b5d1-11e8-8940-70192f34e7dd.png)

On the left hand side you can see that the top portion is the Project toolbar while the bottom portion is the Structure toolbar, both visible at the same time.  
  
I'd love to see this feature as well.

**Comment by bpasero** [comment]
The intent was to mark this as duplicate of https://github.com/Microsoft/vscode/issues/26777 that proposes to have multiple sidebars at the same time.

**Comment by mrjones2014** [comment]
@bpasero I don't really agree that this issue _is_ a duplicate of that one; I don't want a sidebar on both the left and right, I want a sidebar on _one_ side, split vertically.

**Comment by bpasero** [comment]
@mrjones2014 I would argue that the goal of #26777 is to move sidebar views freely around in the workbench layout (e.g. like editors in the grid).

**Comment by mrjones2014** [comment]
@bpasero I didn't really see anything in there about vertical alignment/splitting

**Comment by bpasero** [comment]
Ok trust me, I would not have it any other way than that.
