### ISSUE TITLE
Find and replace ctrl+enter only works when focus is in replace text box

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#5727]
Steps to Reproduce:

1. <kbd>ctrl</kbd>+<kbd>h</kbd>
2. Focus find
3. Type "a", or something with matches in the file
4. <kbd>ctrl</kbd>+<kbd>enter</kbd> **does not replace all**
5. Focus replace
6. <kbd>ctrl</kbd>+<kbd>enter</kbd> **replaces all**

Mousing over the replace all button shows the keybinding <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>enter</kbd>, not <kbd>ctrl</kbd>+<kbd>enter</kbd>. It also doesn't seem to have an entry in keybindings.json so I'm a little confused whether it's a bug that it works at all.

**Comment by alexandrudima** [comment]
I've looked at the code and improved the keybindings rule for 3 find related keybindings.

The ctrl+enter has a simple explanation. It is something "built-in" to the replace input. Similar how Enter on the find field goes to next match, Shift-Enter goes to previous match, how Enter on the replace field replaces next. They are not configurable, if the need arises for Enter to do something different while in those two input fields, we can dispatch those keys also through the keybinding service.
The explanation in code at https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/find/browser/findWidget.ts#L314 and https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/find/browser/findWidget.ts#L343

The keybinding you see when you hover over the replace all (Ctrl+Alt+Enter) works even when focus is outside the find widget (i.e. in the editor) and can be rebound:
```
{ "key": "ctrl+alt+enter",        "command": "editor.action.replaceAll",
                                     "when": "editorFocus && findWidgetVisible" },
```
