### ISSUE TITLE
Terminal is slow/laggy

### ISSUE THREAD

**Issue by ClockworkRobot79** [Microsoft/vscode#57279]
Issue Type: <b>Performance Issue</b>

Version: 1.26.1
Commit: 493869ee8e8a846b0855873886fc79d480d342de
Date: 2018-08-16T18:38:57.434Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

I'm on a Dell laptop with 32GB of RAM and a Radeon dedicated GPU in addition to the Intel integrated chip.

Lately I've noticed that the built in terminal (I use Powershell) is extremely slow/laggy when typing or scrolling in the Terminal itself and also seems to slow down typing responsiveness in code windows while the Terminal is visible.  The Debug Console does not exhibit the same slow down when scrolling or typing.  It is possible this has always been an issue and I just didn't use the integrated terminal as much before, but I have only really noticed it in the couple months.

There is no noticeable load on the CPU or GPU when the slowness is happening.  Not only is the Terminal itself slow, the responsiveness of the entire program is affected - resizing child windows and panels is extremely slow if the Terminal is visible, if I switch to the Debug Console the problem goes away and resizing behaves as expected.

Here is the output of running `code --status`:

Version:          Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS Version:       Windows_NT x64 10.0.17134
CPUs:             Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)
Memory (System):  31.85GB (18.68GB free)
VM:               0%
Screen Reader:    no
Process Argv:     C:\Users\erica\AppData\Local\Programs\Microsoft VS Code\Code.exe c:\granular\field-details
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    disabled_software
                  rasterization:                enabled
                  video_decode:                 enabled
                  video_encode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled
CPU %   Mem MB     PID  Process
    0       88   11556  code main
    0      166   11128     window (UrlService.ts - imagery - Visual Studio Code)
    0       12   13084       watcherService
    0        5    6544         console-window-host (Windows internal process)
    0      115   14628       extensionHost
    0       20    1364         electron_node tslintServer.js
    0       20    3464         electron_node eslintServer.js
    0       29    4268         C:\Users\erica\.vscode\extensions\ms-vsliveshare.vsliveshare-0.3.577\dotnet_modules\vsls-agent.exe --autoexit --pipe d690470156b94567a65d95d45189dd94 --service https://insiders.liveshare.vsengsaas.visualstudio.com/
    0        5    5316           console-window-host (Windows internal process)
    0      454    6260         electron_node electronForkStart.js tsserver.js
    0       20    5656           electron_node typingsInstaller.js tsserver.js typesMap.js
    0        2   12684         electron_node runner.js
    0       19    8988           node   "c:\granular\imagery\node_modules\.bin\\..\jest\bin\jest.js" --json --useStderr --outputFile C:\Users\erica\AppData\Local\Temp/jest_runner.json --watch
    0        5    9620           console-window-host (Windows internal process)
    0       23   14944         electron_node jsonServerMain.js
    0       21   14804       searchService
    0      209   13372     gpu-process
    0      340   13484     window (Map.test.jsx - field-details - Visual Studio Code)
    0        8    8676       winpty-process
    0       50   15640         C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0        3   17812           C:\WINDOWS\system32\cmd.exe /c ""C:\Program Files (x86)\Yarn\bin\yarn.cmd" test"
    0       26   18368             node  "C:\Program Files (x86)\Yarn\bin\\yarn.js" test
    0        2   23484               electron_node test.js
    0      134   16212                 node  scripts/test.js --env=jsdom
    3       11   17160         console-window-host (Windows internal process)
    0       21   13800       searchService
    0      204   13848       extensionHost
    0        3    3020         electron_node runner.js
    0        9   22496           console-window-host (Windows internal process)
    0       85   28484           node   "c:\granular\field-details\node_modules\.bin\\..\jest\bin\jest.js" --json --useStderr --outputFile C:\Users\erica\AppData\Local\Temp/jest_runner.json --watch
    0       29    9136         C:\Users\erica\.vscode\extensions\ms-vsliveshare.vsliveshare-0.3.577\dotnet_modules\vsls-agent.exe --autoexit --pipe fb0f806c48654e99a02b93712e7eb1db --service https://insiders.liveshare.vsengsaas.visualstudio.com/
    0        5   11604           console-window-host (Windows internal process)
    0       81   14672         electron_node eslintServer.js
    0      414   14968         electron_node electronForkStart.js tsserver.js
    0       26   14568           electron_node typingsInstaller.js tsserver.js typesMap.js
    0       31   15020         electron_node tslintServer.js
    0       23   15064         electron_node jsonServerMain.js
    0       11   13924       electron-crash-reporter
    0       17   14028       watcherService
    0        5   14036         console-window-host (Windows internal process)
    0        8   20944       winpty-process
    2       11    1600         console-window-host (Windows internal process)
    0       77   21728         C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0       78   13712     shared-process
Workspace Stats:
|  Window (Map.test.jsx - field-details - Visual Studio Code)
|  Window (UrlService.ts - imagery - Visual Studio Code)
|    Folder (field-details): 231 files
|      File types: js(56) jsx(37) html(36) ts(26) scss(13) tsx(10) json(9)
|                  md(6) png(5) props(4)
|      Conf files: package.json(1) tsconfig.json(1) tslint.json(1)
|                  launch.json(1)
|    Folder (imagery): 644 files
|      File types: html(243) ts(150) tsx(131) scss(28) js(19) svg(17) json(10)
|                  png(6) props(4) yml(3)
|      Conf files: package.json(1) tsconfig.json(1) tslint.json(1)
|      Launch Configs: node(3)

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.85GB (18.35GB free)|
|Process Argv|C:\Users\erica\AppData\Local\Programs\Microsoft VS Code\Code.exe c:\granular\field-details|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    93	 11556	code main
    0	   159	 11128	   window (UrlService.ts - imagery - Visual Studio Code)
    0	    12	 13084	     watcherService 
    0	     5	  6544	       console-window-host (Windows internal process)
    0	    91	 14628	     extensionHost
    0	    19	  1364	       electron_node tslintServer.js 
    0	    19	  3464	       electron_node eslintServer.js 
    0	    30	  4268	       C:\Users\erica\.vscode\extensions\ms-vsliveshare.vsliveshare-0.3.577\dotnet_modules\vsls-agent.exe --autoexit --pipe d690470156b94567a65d95d45189dd94 --service https://insiders.liveshare.vsengsaas.visualstudio.com/
    0	     5	  5316	         console-window-host (Windows internal process)
    0	   474	  6260	       electron_node electronForkStart.js tsserver.js 
    0	    18	  5656	         electron_node typingsInstaller.js tsserver.js typesMap.js 
    0	     2	 12684	       electron_node runner.js 
    0	    23	  8988	         node   "c:\granular\imagery\node_modules\.bin\\..\jest\bin\jest.js" --json --useStderr --outputFile C:\Users\erica\AppData\Local\Temp/jest_runner.json --watch
    0	     5	  9620	         console-window-host (Windows internal process)
    0	    21	 14944	       electron_node jsonServerMain.js 
    0	    20	 14804	     searchService
    1	    70	 12664	   window (Issue Reporter)
    0	   266	 13372	   gpu-process
    0	   363	 13484	   window (Map.test.jsx - field-details - Visual Studio Code)
    0	     8	  8676	     winpty-process
    0	    62	 15640	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     9	 17160	       console-window-host (Windows internal process)
    0	    19	 13800	     searchService
    0	   202	 13848	     extensionHost
    0	     3	  3020	       electron_node runner.js 
    0	     9	 22496	         console-window-host (Windows internal process)
    0	    86	 28484	         node   "c:\granular\field-details\node_modules\.bin\\..\jest\bin\jest.js" --json --useStderr --outputFile C:\Users\erica\AppData\Local\Temp/jest_runner.json --watch
    0	    30	  9136	       C:\Users\erica\.vscode\extensions\ms-vsliveshare.vsliveshare-0.3.577\dotnet_modules\vsls-agent.exe --autoexit --pipe fb0f806c48654e99a02b93712e7eb1db --service https://insiders.liveshare.vsengsaas.visualstudio.com/
    0	     5	 11604	         console-window-host (Windows internal process)
    0	    79	 14672	       electron_node eslintServer.js 
    0	   412	 14968	       electron_node electronForkStart.js tsserver.js 
    0	    25	 14568	         electron_node typingsInstaller.js tsserver.js typesMap.js 
    0	    30	 15020	       electron_node tslintServer.js 
    0	    21	 15064	       electron_node jsonServerMain.js 
    0	    11	 13924	     electron-crash-reporter
    0	    17	 14028	     watcherService 
    0	     5	 14036	       console-window-host (Windows internal process)
    0	     8	 20944	     winpty-process
    0	    10	  1600	       console-window-host (Windows internal process)
    0	    77	 21728	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    88	 13712	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Map.test.jsx - field-details - Visual Studio Code)
|  Window (UrlService.ts - imagery - Visual Studio Code)
|    Folder (field-details): 231 files
|      File types: js(56) jsx(37) html(36) ts(26) scss(13) tsx(10) json(9)
|                  md(6) png(5) props(4)
|      Conf files: package.json(1) tsconfig.json(1) tslint.json(1)
|                  launch.json(1)
|    Folder (imagery): 644 files
|      File types: html(243) ts(150) tsx(131) scss(28) js(19) svg(17) json(10)
|                  png(6) props(4) yml(3)
|      Conf files: package.json(1) tsconfig.json(1) tslint.json(1)
|      Launch Configs: node(3);
```

</details>
<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.0.3
vscode-eslint|dba|1.5.0
tslint|eg2|1.0.37
python|ms-|2018.7.1
cpptools|ms-|0.18.1
vsliveshare|ms-|0.3.577
debugger-for-chrome|msj|4.8.2
vscode-jest|Ort|2.9.0
mako|tom|0.2.0
gitblame|wad|2.4.4

</details>

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/56628
