### ISSUE TITLE
Clicking on settings TOC title should expand it

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#57273]
I expected it to expand, but you need to double click:

![image](https://user-images.githubusercontent.com/2193314/44665950-1d9c3880-a9cc-11e8-9e74-eb9be9414d3c.png)

**Comment by bpasero** [comment]
Still reproduces:
- reload window
- open settings
- click on "Workbench"

=> 🐛 "Workbench" gets bold but not expanded.

**Comment by roblourens** [comment]
Now we scroll to it, which triggers the expansion, then the click collapses it 🤦‍♂️

**Comment by rzhao271** [comment]
Seems to be fixed now. Closing.
