### ISSUE TITLE
The keyboard shortcut to reveal in explorer doesn't work

### ISSUE THREAD

**Issue by masackma** [Microsoft/vscode#57283]
Issue Type: <b>Bug</b>

1) Create a workspace.
2) Open a file in the workspace with ctrl+p > tyle something > right arrow
3) Make sure focus in on the file
4) Press shitf + alt + r

Expected: a new explorer.exe window opens with the file selected and keyboard focus on that specific file.
Actual: nothing happens

Note that if I right click on the tab and click "Reveal in explorer" with the mouse, the desired behavior occurs. And in that context menu, I see that the mentioned shortcut is "Alt+shift+r"

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17744

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.91GB (8.89GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|yes|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
gitlens|eam|8.5.6
vscode-nmake-tools|Mic|1.1.180810001
cpptools|ms-|0.18.1
sublime-keybindings|ms-|4.0.0
team|ms-|1.136.0
indent-rainbow|ode|7.2.4
trailing-spaces|sha|0.2.11

</details>

**Comment by sbatten** [comment]
this behavior has been like this for some time due to https://github.com/Microsoft/vscode/issues/49231

@rebornix

**Comment by rebornix** [comment]
We only reveal file in OS when the focus is not in the editor, that's being there from the very beginning AFAIK. If the keybinding's restriction doesn't make sense to you, you can add below to your keybindings file

```
	{
		"key": "shift+alt+r",
		"command": "revealFileInOS"
	},
```

**Comment by masackma** [comment]
@rebornix Thanks for the workaround. Works great! 👍
