### ISSUE TITLE
Unable to start terminal process: CreateProcess failed

### ISSUE THREAD

**Issue by joshcsmith13** [Microsoft/vscode#57285]
When I use the menu or hotkey to open a Terminal, nothing happens and I get the following error message displayed in the lower right of the editor:
Unable to start terminal process: CreateProcess failed

I'm on an enterprise Windows 10 machine.  I recently installed/upgraded to the "non-admin" version of VS Code (as it was constantly harassing me to do so).

I have tried "Run As Administrator" with no luck.

**Comment by Tyriar** [comment]
Can you share your VS Code version, Windows 10 version number and settings.json file? Also are you on the 64-bit version of VS Code?

**Comment by joshcsmith13** [comment]
![image](https://user-images.githubusercontent.com/8902423/44685640-2bbc7a00-aa09-11e8-8294-e0552ebd9709.png)
Visual Studio Code 
Version: 1.26.1 
Commit: 493869ee8e8aU6b085S873886fc79d480d342de 
Date: 2018-08 
Electron: 2.0.5 
Chrome: 61.0.3163.100
Node.js: 8.9.3 
V8: 6.1.534.41 
Architecture: x64

![image](https://user-images.githubusercontent.com/8902423/44685918-e5b3e600-aa09-11e8-8a97-5ca9a6586dfa.png)

**Comment by joshcsmith13** [comment]
[settings.json.txt](https://github.com/Microsoft/vscode/files/2325641/settings.json.txt)

**Comment by Tyriar** [comment]
I suspect this is related to restrictions placed by your IT support, can you reach out to them and ask them about this? Specifically this is the call that's failing:

https://github.com/Microsoft/node-pty/blob/2c1c0e78c8f110b4e3da87a3f9b88ebc9e7b33b8/deps/winpty/src/libwinpty/winpty.cc#L499

The executable that is being launched should be: `%windir%\System32\WindowsPowerShell\v1.0\powershell.exe`

We can verify what is being launched by closing VS Code, enabling debug logging by launching `code --log debug`, opening a terminal and then consulting the log (F1, "log file", enter). Search the log for "Terminal process launching".

**Comment by joshcsmith13** [comment]
Thank you for your help Tyriar.  You got me pointed in the right direction, but it turns out it was simpler(?) than that.  If I tried to launch Powershell from the Start menu, nothing happened.  When I tried running it from cmd, I got "The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail."  There are numerous suggestions on how to fix this, including reinstalling C libraries, etc.
Fortunately, I found one post where a user said that their config file was corrupted.  Accordingly, I tried to look at my powershell.exe.config file and found exactly that!  It was nothing but binary NULL characters.
I deleted the config file (after checking with a coworker with a similar setup and didn't have one) and everything seems to be working fine now.  :)  I can launch Powershell from Start and the Terminal window works in VS Code.
Thanks again!

**Comment by Tyriar** [comment]
@joshcsmith13 interesting case, glad you got it fixed! 😃
