### ISSUE TITLE
Scrolling in editor or terminal causing "ghosting" text artefacts

### ISSUE THREAD

**Issue by SmCTwelve** [Microsoft/vscode#57287]
Issue Type: <b>Bug</b>

Sometimes when scrolling in the editor window or the integrated terminal there is artefacts where the text on the previous frame isn't cleared so it blends together cuasing a weird ghosting effect that becomes unreadable. 

<img src=https://i.imgur.com/UJXZ4NR.gif>

<img src=https://i.imgur.com/kzeZLSk.png>

<img src=https://i.imgur.com/uxgqH4N.png>

This only started happening recently after I updated to the latest VS Code. Weirdly it seems to be related to the Material Icon Theme extension which changes the icons in the explorer. I don't think the extension itself is the problem though because it only changes the icons, it shouldn't have any effect on screen rendering or scrolling. I have checked their repository and can't find any other discussions about this either, so I thought it best to report here as it seems like a bigger issue. 

It doesn't happen every time I scroll so it's difficult to reproduce. It seems to be triggered most if: 
1) Material Icon Theme is enabled 
2) I scroll within the Explorer window or have an item focused there 
3) I use the mouse to scroll within the editor or terminal windows. 

Sometimes it's just small artefacts like this: 

<img src=https://i.imgur.com/rTv5pDZ.png>

The screen goes back to normal if I click within the editor or terminal to focus it or hover the mouse over an item. But it will happen again when scrolling with the above steps. 

I've tried the latest Insider's Build with all default settings and I can reproduce the issue, again with the Material Icon Theme enabled. Any idea why an icon theme would cause this? I've isolated the issue to VS Code, it doesn't happen in other editors, standalone terminal or in Chrome. 

 

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (4.50GB free)|
|Process Argv|C:\Users\Scott1\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.5.0
githistory|don|0.4.2
dotenv|mik|1.0.1
python|ms-|2018.7.1
debugger-for-chrome|msj|4.8.2
material-icon-theme|PKi|3.5.3
code-settings-sync|Sha|3.1.0
markdown-all-in-one|yzh|1.6.0

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
@SmCTwelve 
We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/883208e30da25777874a8ade5f90e1fea638a298/VSCode-win32-x64-1.28.0-exploration.zip)
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/883208e30da25777874a8ade5f90e1fea638a298/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/883208e30da25777874a8ade5f90e1fea638a298/code-exploration-1535724826.tar.gz)

**Comment by SmCTwelve** [comment]
@bpasero 

Downloaded the Windows build and I can reproduce the issue. The only extension I downloaded was Material Icon Theme, because that seemed to be the trigger. Sure enough, when I enabled it with Preferences > File Icon Theme and started scrolling I got the same problem. 

I guess the problem must be the extension then because it's difficult to reproduce without it enabled. I just find it extremely surprising that an icon theme would trigger this bug, and nobody else seems to be reporting it. Either it's something on my end or it's a very weird bug. I have managed to reproduce the issue on the latest stable VS Code, the Insiders Build, and now the Exploration Build.

**Comment by bpasero** [comment]
@SmCTwelve does it reproduce if you run `code --disable-gpu` from the command line?

**Comment by SmCTwelve** [comment]
@bpasero That seems to fix it. Strange that having a theme installed would affect GPU acceleration, I'm really scratching my head to figure out why the issue didn't occur without the icons. I have a GTX 970. 

Is there a setting to `--disable-gpu` permanently? And is there any negative impact from doing so in terms of performance?

**Comment by bpasero** [comment]
Ok good to know. We would like to stay away from supporting a setting for this because it can have quite negative impact on perf.
