### ISSUE TITLE
VS Code Insiders update failure

### ISSUE THREAD

**Issue by jlautman** [Microsoft/vscode#57286]
Updating gives message "Failed to install VS Code update. Please download and reinstall VS Code."

Log file attached.

[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2325089/vscode-inno-updater.log)

**Comment by dbaeumer** [comment]
@joaomoreno I saw that yesterday as well and there was a hanging `VS Code process`

**Comment by JohnnyWestlake** [comment]
It's annoying this keeps getting closed but no one is doing anything about it... seems to get a new issue opened about it nearly every single day.
