### ISSUE TITLE
New option for javascript.preferences.quoteStyle

### ISSUE THREAD

**Issue by jabacchetta** [Microsoft/vscode#57282]
Currently, if there aren't any existing imports in a file, the quote style is not inferred for auto imports. 

We have the option to to leave `javascript.preferences.quoteStyle` set to `auto`, but without imports it will default to `double`. And if we explicitly set it to `single`, it will always import as single, regardless of previous imports.

It'd be nice to get another setting, potentially named `auto-single` (changing `auto` to `auto-double`), that first attempts to infer the quote style, and then falls back to single quotes. This would eliminate a lot of manual refactoring for those who prefer (and mostly work with projects using) single quotes, but still want to infer double quotes if they exist (when possible).

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#26882
