### ISSUE TITLE
Test breadcrumbs polish items

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#57280]
- [x] Windows @bpasero
- [ ] macOS @auchenberg

Complexity: 3

There has been a bunch of small tweaks and polish items for breadcrumbs. Make sure to *verify* these items: [feature-request](https://github.com/Microsoft/vscode/issues?utf8=✓&q=assignee%3Ajrieken+milestone%3A%22August+2018%22+is%3Aclosed+label%3Afeature-request+-label%3Averification-needed+label%3Abreadcrumbs) and [polish items](https://github.com/Microsoft/vscode/issues?utf8=✓&q=assignee%3Ajrieken+milestone%3A%22August+2018%22+is%3Aclosed+label%3Apolish+-label%3Averification-needed+label%3Abreadcrumbs+-label%3Abug)

**Comment by auchenberg** [comment]
I take MacOS!
