### ISSUE TITLE
Settings UI should remember its search upon reload

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode#57289]
Issue Type: <b>Feature Request</b>

Some settings require reload and this may be in the middle of the user modifying settings. It would be cool if the settings UI could remember the search through reload.

**Comment by roblourens** [comment]
#58499

> I would say "the search should be persisted when reloading with the settings editor open".

**Comment by roblourens** [comment]
PR welcome.

- Use `getEditorMemento` to cache the state of the settings editor (settingsEditor2.ts)
- Implement `setVisible`, the state should only be cached or restored if the settings editor was visible when the window reloaded.

**Comment by roblourens** [comment]
Besides the search string, this should also cover the scroll position of the settings list per #57365
