### ISSUE TITLE
inline javascript toggle comment hotkey

### ISSUE THREAD

**Issue by Vaelek** [Microsoft/vscode#57288]
Issue Type: <b>Bug</b>

I have the following inline script in an html file
```
<script>
    $('#chkIsActive').on('click', (event) => {
        activeToggle(event, event.toElement);
    })
</script>
```

using the toggle comment option (Ctl-/), it turns it into
```
<script>
    $('#chkIsActive').on('click', (event) => {
        {% comment %} activeToggle(event, event.toElement); {% endcomment %}
    })
</script>
```

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz (12 x 3299)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (17.10GB free)|
|Process Argv|C:\Users\jim\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|40%|

</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vscode-django|bat|0.17.0
django-html|bib|1.2.0
django-snippets|bib|1.1.0
vscode-importmagic|bra|0.0.6
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.5.0
jupyter|don|1.1.4
python-extension-pack|don|1.4.0
vscode-npm-script|eg2|0.3.5
php-debug|fel|1.12.4
live-html-previewer|hdg|0.3.0
rest-client|hum|0.19.1
phpcs|ika|1.0.5
vscode-phpfmt|kok|1.0.30
sftp|lix|1.4.0
MagicPython|mag|1.0.12
mssql|ms-|1.4.0
python|ms-|2018.7.1
Go|ms-|0.6.88
vsliveshare|ms-|0.3.577
debugger-for-chrome|msj|4.8.2
indent-rainbow|ode|7.2.4
java|red|0.29.0
LiveServer|rit|5.1.1
code-settings-sync|Sha|3.1.0
markdown-preview-enhanced|shd|0.3.5
indenticator|Sir|0.6.0
html-preview-vscode|tht|0.1.1
vscodeintellicode|Vis|1.0.3
vscode-java-debug|vsc|0.11.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.8.0
vscode-maven|vsc|0.10.0
jinja|who|0.0.8
vscode-js-console-utils|wht|0.7.0

</details>

**Comment by aeschli** [comment]
When I try this I get

![image](https://user-images.githubusercontent.com/6461412/45509066-cc938f00-b796-11e8-9e64-bfe473c8453a.png)

I checked our source code and we don't use `{% comment %}`.
My guess is that this is caused by the [django extension](https://marketplace.visualstudio.com/items?itemName=batisteo.vscode-django) ?
