### ISSUE TITLE
Inconsistent InputBox value selection

### ISSUE THREAD

**Issue by HaaLeo** [Microsoft/vscode#57295]
Issue Type: **Question**/**Bug**

- VSCode Version: 1.26.1
- OS Version: Windows 10 Pro 1803

# Description:
In an extension I created an [`InputBox`](https://code.visualstudio.com/docs/extensionAPI/vscode-api#InputBox) and assigned the `InputBox.value` programmatically (in the gif it is 2342). Now when I debug the extension and invoke the command that shows the InputBox the **very first time**, the `InputBox`'s value is preselected. Now I press <kbd>Enter</kbd> which shows another `InputBox` for the very first time. Also the value of the second InputBox is pre-selected.  
So far everything is OK.  
Now it starts where I am getting confused: After both `InputBox`es were shown for the first time, when I invoke the command **again** (that shows the `InputBox`es), the value of those is **not pre-selected** anymore.  
Is this behaviour intended? If yes, why do you want to distinguish between the very first display and all others? Or is it just a bug? 😅 

![pre-selection-bug](https://user-images.githubusercontent.com/23164374/44684641-df455e80-aa49-11e8-8e03-61c24b84110c.gif)

# Steps to Reproduce:

1. Create an extension containing an `InputBox`
2. Asign the `InputBox.value`
3. Debug the extension
4. Show/hide the `InputBox` several times

Alternatively you can 
1. checkout [this branch](https://github.com/HaaLeo/vscode-timing/tree/bug/inconsistent-pre-selection)
2. Run `npm i`
3. Debug the extension
4. Invoke the command `timing.epochToIsoUtc`

## Acutal Behaviour
When the InputBox is shown the first time after the extension was started, the `value` is preselected. All other times it is not.

## Expected Behaviour
The value is **always** preselected. Or the developer can decide about `valueSelection` (#56759).

Does this issue occur when all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
Going with "just a bug" and keeping the feature request for later.
