### ISSUE TITLE
Add dirname context key

### ISSUE THREAD

**Issue by allileong** [Microsoft/vscode#57298]
Example use case: I would only like to make a command available in the “explorer/context” if the path for the file that was clicked contains the directory named `foo`. 

For example, expose the command when the file path for the file that is clicked is: `/workspace/src/foo/bar/exampleFile.js`. 
Do not expose the command when the file path for the file that is clicked is `/workspace/src/bar/exampleFile.js`

**Comment by isidorn** [comment]
So you would want somethink like a dirname context key. Leaving this open as a feature request.

**Comment by allileong** [comment]
A dirname context key would definitely be useful, but it still wouldn't solve the first example above where exampleFile.js is inside of the directory 'bar' that is inside of 'foo'. It would be nice to be able to know if my resource is inside of 'foo' even if it's several directory layers removed, but I'm not sure what the best way to achieve that would be.
