### ISSUE TITLE
confusing TS error message

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#57291]
I'm trying to compile the `vscode-docker` repository and one of the errors I am getting is on `tsconfig.json`:

![image](https://user-images.githubusercontent.com/1487073/44683000-cdd46600-a9f9-11e8-9e33-27bd5b8e890d.png)

Note that the description references `es2018` but the error references `es2017`.

**Comment by mjbvz** [comment]
I was not able to reproduce this. Are you perhaps using an older version of TypeScript in the workspace or in the build task? Can you please make sure you are on at least TS 2.9 and check if you still see the error
