### ISSUE TITLE
Error: The category 'Extension Packs' is not available in language 'en-us'

### ISSUE THREAD

**Issue by ericbiewener** [Microsoft/vscode#57290]
I just started receiving this error message when trying to publish an extension. I am indeed including the "Extension Packs" category, but this didn't cause a problem for me previously. I am using vsce v1.46.0, and [here's my full package.json file](https://github.com/ericbiewener/vscode-vandelay-js/blob/7ea0fdb77537c81f46416f3b16f1865d4d3658e5/package.json).

**Comment by sandy081** [comment]
@viradhamMS @pkuma-msft Please check if it is an issue with Market place

**Comment by pkuma-msft** [comment]
Looking into it..

**Comment by pkuma-msft** [comment]
@ericbiewener The issue should be fixed now.. let us know if you still run into trouble. Thank you for reporting this!

**Comment by ericbiewener** [comment]
All set, thanks!

**Comment by sandy081** [comment]
Thanks @pkuma-msft
