### ISSUE TITLE
Debugger stop working

### ISSUE THREAD

**Issue by gerhardcit** [Microsoft/vscode#57297]
Issue Type: <b>Bug</b>

After last update Debugger stop working
```
{
			"name": "Launch USSD",
			"type": "node",
			"request": "launch",
			"program": "${workspaceRoot}/src/app/myapp.ts",
			"stopOnEntry": false,
			"args": [],
			"cwd": "${workspaceRoot}",
			"preLaunchTask": null,
			"runtimeExecutable": null,
			"runtimeArgs": [
				"--nolazy"
			],
			"env": {
				"NODE_ENV": "development"
			},
			"console": "integratedTerminal",
			"sourceMaps": true,
			"outFiles": [
				"${workspaceRoot}/dist/app/**/*.js"
			]
		},
```
Errors popup with:
Request VSCodeAdapterService.nodeFork failed unexpectedly without providing any details

VS Code version: Code - Insiders 1.27.0-insider (3f8088b5c5f1d44b5e1af4a8e67448abbe66470e, 2018-08-27T07:28:09.336Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.39GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|8.0.0
githistory|don|0.4.2
gitlens|eam|8.5.6
tslint|eg2|1.0.38
vscode-npm-script|eg2|0.3.5
gc-excelviewer|Gra|2.1.26
rest-client|hum|0.19.1
vs-color-picker|lih|0.7.0
json-to-ts|Mar|1.5.5
vsliveshare|ms-|0.3.577
vscode-code-outline|pat|0.2.1
ejs-language-support|Qas|0.0.1
vscode-nginx|sha|0.5.0

</details>

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/57268
Caused by vsliveshare, please file against that extensions
