### ISSUE TITLE
rewrite completion list ui

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#573]
_From @BleyChen on November 12, 2015 9:56_

As we know , when you write JavaScript code in VSCode ,it will popup an Completion list UI as following.
![vscode](https://cloud.githubusercontent.com/assets/15098626/11115402/46d811bc-8966-11e5-919e-5b21bf3fe0e7.png)
I want to know whether i can overwrite the Completion list UI ,because i want to provide additional information for each JavaScript API, anyone can help me ? 

_Copied from original issue: Microsoft/vscode-extensionbuilders#99_

**Comment by seanmcbreen** [comment]
_From @jrieken on November 12, 2015 15:0_

You cannot change a completion item someone else created but you can provide your own set of completion items using the `CompletionItemProvider`.

**Comment by seanmcbreen** [comment]
_From @BleyChen on November 13, 2015 3:40_

do you know which API can let me get the information of completion item provided by someone else ? 
How to populate the Javascript auto-complete list in my own code?
How to get the function name list in my plugin, and populate them in my own intellisense provider?

the following steps is what i want to implement:
step 1. when user write js code in VSCode , it will popup Completion list UI.
![vscode](https://cloud.githubusercontent.com/assets/15098626/11137979/c52ac9c4-89f7-11e5-8bd7-d36aa7331d5f.png)

step 2. when user switch completion item , i can get the item information that current user select , and  use the completion item information to get some useful samples and show it in UI.

![vscode-next](https://cloud.githubusercontent.com/assets/15098626/11138128/7a06bb7c-89f9-11e5-9223-01f5066311fb.png)

i don't know whether it can be implemented  or not? can you help me ,thank you !

**Comment by seanmcbreen** [comment]
_From @jrieken on November 13, 2015 7:51_

Sorry, that isn't possible right now

**Comment by mjbvz** [comment]
With VSCode 1.17, the completion item's documentation is now a markdown string, so you are be able to include code snippets and other formatted content
