### ISSUE TITLE
Test previewOptions in search provider

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#57305]
Testing https://github.com/Microsoft/vscode/issues/57186

- [x] AnyOS @bpasero 
- [x] AnyOS @sbatten 

Complexity: 3

Write an extension that uses findTextInFiles, and verify that previewOptions is respected properly.
	
Try some different text searches and verify that builtin search returns the correct preview, and that clicking on a result highlights the correct range in the editor. When the search view is narrow, the preview will be shorter than when it is wide (like when it's in the panel).
	
Test it with `"searchRipgrep.enable": true` and `false`
	
And you could verify https://github.com/Microsoft/vscode/issues/31551 since this change also fixed that.

**Comment by sbatten** [comment]
verified other issue and left comments in opened issue
