### ISSUE TITLE
Upgrade js-beautify to 1.8.1

### ISSUE THREAD

**Issue by fengerzh** [Microsoft/vscode#57302]
- VSCode Version: 1.26.1
- OS Version: macOS 10.13.6

Steps to Reproduce:

1. https://www.npmjs.com/package/js-beautify JS Beautifier already upgrade to 1.8.1
2. But VSCode still use old 1.7.5

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
I do not see `js-beautify` being used directly by vscode core or our core extensions. You likely meant to file this against an extension
