### ISSUE TITLE
console.[log|info|debug] from a LSP client is no longer logged

### ISSUE THREAD

**Issue by midzelis** [Microsoft/vscode#57308]
- VSCode Version: 1.26.1
- OS Version: MacOS 10.13.6

Steps to Reproduce:

1. Launch a LSP Server in debug mode. (Will start a VSCode instance) 
2. Attach another VS Code instance to the running LSP Server
3. When console.log or any of its variants is encountered, it is no longer logged to Debug Console. (I also looked through all of the outputs, including all dropdowns, in all 3 open VSCode clients. 

Downgrading to 1.25.1 makes it work again. 

Does this issue occur when all extensions are disabled?: No

**Comment by octref** [comment]
https://github.com/Microsoft/vscode/issues/56169
https://code.visualstudio.com/updates/v1_26#_nodejs-update
