### ISSUE TITLE
Test: Path Completion and Jump to Definition for CSS/SCSS/Less's @import and url()

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#57309]
Testing #51331 and #29899

- [x] macOS @RMacfarlane 
- [x] linux @isidorn 
- [x] windows @bpasero 

Complexity: 2

Path completion and jump to definition has been added to css/scss's `@import` and `url()`.

Note that in SCSS, `@import 'foo';` actually imports `_foo.scss`, which is a partial. See: https://sass-lang.com/guide

MDN Link for `@import`: https://developer.mozilla.org/en-US/docs/Web/CSS/@import

Test:

- File path completions work for both CSS, SCSS and Less's `@import` and `url()`
- When importing SCSS files, the completion shows the partial's name `_foo.scss` but completes `foo`.
- In CSS, SCSS and Less, all `@import` and `url()` show underlines.
- Clicking into each underlined link brings up either an editor showing the file, or opens the browser for `http` or `https` links (e.g., `@import url('https://fonts.googleapis.com/css?family=Roboto');`).

**Comment by bpasero** [comment]
> When importing SCSS files, the completion shows the partial's name _foo.scss but completes foo
I did not test that because neither do I understand it nor did I see that behaviour.

**Comment by isidorn** [comment]
+1 to what Ben said, I also did not see that behavior
Is this unexpected? If yes then why?

![screen shot 2018-08-28 at 15 04 09](https://user-images.githubusercontent.com/1926584/44724679-b4075180-aad3-11e8-93d9-e34bce53ef62.png)

**Comment by octref** [comment]
@bpasero @isidorn 

Let's say you have two files:

```
/import.scss
/_foo.scss
```

`import.scss`
```scss
@import url('./_foo.scss');

@import './foo';
```

`_foo.scss`
```scss
.foo {
  color: blue;
}
```

When you run `sass import.scss`, it outputs:

```css
@import url("./_foo.scss");
.foo {
  color: blue; }
```

SASS leaves your `@import url()` alone, so even if the filename is `_foo.scss`, it completes that verbatim.
In the other case, it shows `_foo.scss` but completes `foo`.

![import](https://user-images.githubusercontent.com/4033249/44757222-d3f24180-aae2-11e8-97b9-0f70d2cd9312.gif)

**Comment by clarkio** [comment]
Should there be a prompt to update imports when the file path changes just like it is for JavaScript?

**Comment by octref** [comment]
Not really, you can open another feature request.

**Comment by clarkio** [comment]
@shinriyo that looks like an issue for "go to definition in non JS/TS files" which the latest release of VS Code does allow that for CSS now (that's what this issue was regarding to test). What will not work is if you move CSS files around. VS Code will not prompt you to update your import paths in CSS files referencing the moved file. This behavior is what I am asking about as VS Code has this for JS/TS.
