### ISSUE TITLE
html <img> tag not working in markdown preview

### ISSUE THREAD

**Issue by tos-kamiya** [Microsoft/vscode#5730]
- VSCode Version:

> v 1.0.0
> commit fa6d0f03813dfb9df4589c30121e9fcffa8a8ec8
> date 2016-04-13T14:21:33.326Z
> shell 0.35.6
> renderer 45.0.2454.85
> Node 4.1.1

- OS Version:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial
```

Steps to Reproduce:

(1) Write some markdown text including `<img>` tag, like:

```
Works.
![choco](choco.jpg)

Not works.
<img src="choco.jpg">  
```

(2)  Open markdown preview window. You will find the image is not shown in case of `<img>` tag.

**Comment by bpasero** [comment]
Works now 👍
