### ISSUE TITLE
Test settings editor

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#57304]
Testing https://github.com/Microsoft/vscode/issues/55791

Complexity: 4

- [x] Mac @chrmarti
- [x] Win @isidorn
- [x] Linux @jrieken

Test everything in the settings editor. Note that there are screen reader fixes still incoming.

Test combinations of `@filter`, search, and clicking on the TOC to filter during search. Test that editing settings works while searching and filtering.

Test that you can open multiple instances of the settings editor, and they don't get out of sync.

Test that you can navigate by keyboard in a sane way.

Test that the new setting to pick your preferred settings editor, `workbench.settings.editor`, works, and it applies to all the different ways to open settings (default keybinding, menu, activity bar, search viewlet, maybe others)

The settings editor loads pages of settings as you scroll. You can see the scrollbar jerk as you scroll to the end. Watch for any issues this might cause.

Test the gear icon context menu. Default keybinding is shift+f9.

Test editing in different scopes in multi and single folder workspaces, and empty windows. Test that you only see settings that are valid for the scope.

Test that the new dropdown control is a good experience and works the way a dropdown control should, and that enumDescriptions are shown and rendered as markdown when they should be.

Watch for descriptions or enumDescriptions that are not rendered as markdown when they should be (setting contributions now have to opt in to be rendered as markdown, and I had to manually find all descriptions that use markdown)

**Comment by isidorn** [comment]
@roblourens since you mention that screen reader fixes are incoming I did not test nvda support. Let me know once those land and I can re-test that.

**Comment by roblourens** [comment]
Total carnage 😆 thanks for the testing everyone!
