### ISSUE TITLE
Test: Custom Menubar Mnemonics

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode#57316]
- [x] Windows @rebornix 
- [x] Linux @jrieken  

Complexity: 4

Several bugs were fixed this iteration regarding the custom menubar mnemonics. I don't want to rely only on the bug validation to ensure everything works so this item is to get some scrutiny on the menubar as we plan to make this a default experience.

Verify:
- Alt can be used to focus the menu
- Alt can be used to unfocus the menu
- Alt+<mnemonics> can be used when the menu if not focused (including toggled away)
- Single letter mnemonics can be used to activate items in the menu
- Duplicate mnemonics cycle focus in the menu
- Mnemonics work in submenus
- Mnemonics can be enabled and disabled
- Mnemonics work different keyboard layouts and language packs.

If you question some behavior, please verify with notepad or notepad++ to see if we are doing something similar.

**Comment by jrieken** [comment]
This is pretty descent on Ubunutu 18.04 but it gave me a headache on Ubuntu 16.04 because Alt conflict with the ubuntu menu
