### ISSUE TITLE
Outline missing for local files (Python)

### ISSUE THREAD

**Issue by yoongkang** [Microsoft/vscode#57319]
Issue Type: <b>Bug</b>

I'm using Python. Outline only works when I'm looking at a library source file. When I am viewing my own files, the outline says "no symbols found".

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:31:26.156Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|8.00GB (0.39GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron kam.rb|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.4
project-manager|ale|8.0.0
solargraph|cas|0.17.6
gitignore|cod|0.5.0
bracket-pair-colorizer|Coe|1.0.59
vscode-svgviewer|css|1.4.4
vscode-eslint|dba|1.5.0
git-extension-pack|don|0.1.3
githistory|don|0.4.2
xml|Dot|2.3.2
gitlens|eam|8.5.6
tslint|eg2|1.0.38
LogFileHighlighter|emi|2.4.0
vsc-material-theme|Equ|2.3.0
ginfuru-vscode-jekyll-syntax|gin|0.0.5
mdmath|goe|2.3.2
gc-excelviewer|Gra|2.1.26
latex-workshop|Jam|5.8.2
nbpreviewer|jit|1.0.0
restructuredtext|lex|69.0.0
theme-monokai-pro-vscode|mon|1.1.8
python|ms-|2018.7.1
debugger-for-chrome|msj|4.8.2
vetur|oct|0.12.6
vscode-docker|Pet|0.1.0
material-icon-theme|PKi|3.5.3
polacode|pnp|0.2.2
ruby|reb|0.20.0
java|red|0.29.0
vscode-java-debug|vsc|0.11.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.8.0
vscode-maven|vsc|0.10.0
vscode-import-cost|wix|2.8.0
vscode-open-in-github|ziy|1.3.5

(4 theme extensions excluded)

</details>

**Comment by dbaeumer** [comment]
@yoongkang this is caused by the Python extension. Please report the issue there.
