### ISSUE TITLE
html format add </html>

### ISSUE THREAD

**Issue by yyjazsf** [Microsoft/vscode#5731]
- VSCode Version: insiders-1.01
- OS Version:OSX 10.11.4

Steps to Reproduce:

1. open a .html file
2. select all text,press keyboard shortcuts to format html
3.the first time,it's ok,then format html,again it will add </html> to file

**Comment by bpasero** [comment]
@yyjazsf I cannot reproduce, can you attach a sample?

**Comment by yyjazsf** [comment]
@bpasero 
![out](https://cloud.githubusercontent.com/assets/2438224/14804891/a0d76130-0b99-11e6-9f2b-8336a43c8475.gif)
