### ISSUE TITLE
Test: New auto closing options

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#57317]
Complexity 3

- [x] anyOS @octref  
- [x] anyOS @sandy081 

Test plan item for #8536, #36259, which came in as a PR #52634 from @JacksonKearl 

---

In the latest Insiders you'll find two new settings, and a change in the inputs accepted for the existing setting:
```
  // Controls whether the editor should automatically close brackets after the user adds an opening bracket.
  //  - always
  //  - languageDefined: Use language configurations to determine when to autoclose brackets.
  //  - beforeWhitespace: Autoclose brackets only when the cursor is to the left of whitespace.
  //  - never
  "editor.autoClosingBrackets": "languageDefined",

  // Controls whether the editor should automatically close quotes the user adds an opening quote.
  //  - always
  //  - languageDefined: Use language configurations to determine when to autoclose quotes.
  //  - beforeWhitespace: Autoclose quotes only when the cursor is to the left of whitespace.
  //  - never
  "editor.autoClosingQuotes": "languageDefined",

  // Controls whether the editor should automatically wrap selections.
  //  - always
  //  - brackets: Wrap with brackets but not quotes.
  //  - quotes: Wrap with quotes but not brackets.
  //  - never
  "editor.autoWrapping": "always",
```

Note that these will all be overridden by `editor.autoClosingBrackets` if it is set to `false`, so be sure to update that to use the new schema.

---

In the `language-configuration.json` file it is possible to define e.g. `` "autoCloseBefore": ";:.,=}])>` \n\t" `` . This language configuration will drive the `languageDefined` configuration key.

**Comment by innerlee** [comment]
note: this feature `"autoCloseBefore"` is not documented here https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributeslanguages
