### ISSUE TITLE
Loading Blue bar spinning for ever

### ISSUE THREAD

**Issue by alexesca** [Microsoft/vscode#57313]
Issue Type: <b>Bug</b>

Ctrl + Click  on a directive, component, name, html tag and the blue loading bar at the top continues for ever. 

VS Code version: Code - Insiders 1.27.0-insider (346018a80dd299c50cbf213e0a706ef0f35f3a67, 2018-08-24T05:19:27.628Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.74GB (7.38GB free)|
|Process Argv|C:\Users\sanda\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe --folder-uri file:///a%3A/EliteRoofing/spa-ng4|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
ng-template|Ang|0.1.9
path-intellisense|chr|1.4.2
angular-schematics|cyr|1.5.0
vscode-simpler-icons|dav|1.6.5
angular-extension-pack|dog|6.4.0
auto-rename-tag|for|0.0.15
beautify|Hoo|1.3.2
Angular2|joh|6.1.5
intellij-idea-keybindings|k--|0.2.24
Angular-BeastCode|Mik|6.2.14
typescript-javascript-grammar|ms-|0.0.43
es6-mocha-snippets|spo|0.2.1
move-ts|str|1.11.3
JavaScriptSnippets|xab|1.7.0
html-css-class-completion|Zig|1.17.1

</details>

**Comment by aeschli** [comment]
Is this still reproducing in the latest insider? If yes, can you provide a small code example?
Any extensions installed that cause that?

**Comment by alexesca** [comment]
It cannot be presented with code. It happens when VS highlights syntax errors in the HTML file. Even though I corrected the syntax errors VS keeps showing it, then browsing files and using intellisense gets messy.

I do not know how to reproduce it. It happens to me often in my old and new machine. 
It goes back to normal when I restart my laptop or install updates, but it happens again when VS highlights syntax errors. 

You can close this issue. We can re-open it if someone has the same issue or  I can reproduce it.

**Comment by aeschli** [comment]
The built-in HTML support only shows syntax errors in styles (css) and scripts. If you see errors in HTML, then this must be an extension.
You want to disable extensions to find out if all this is caused by a malfunctioning extension. If it is, please let me know so we can file an issue against the extension.
