### ISSUE TITLE
Add option to hide files from "Go to file" picker

### ISSUE THREAD

**Issue by garyking** [microsoft/vscode#57311]
I think it would be useful to have an option to hide a file from "Go to file". 

For example, I have a project that contains many subprojects. Each subproject has files that are very similar to the base code in the project. I rarely need to modify the subprojects, so whenever I use "Go to file", it is polluted with files in the subprojects.

I'd like to be able to hide these files in the subprojects from "Go to file", without hiding them from the sidebar.

**Comment by bpasero** [comment]
@garyking you could try to ignore via search.exclude setting, that would exclude it from fulltext searches too though.

**Comment by garyking** [comment]
Yep I'm aware of that option, but I'm making this suggestion because the `search.exclude` option is too aggressive for me (hides search results from files that I don't want to hide).
