### ISSUE TITLE
Failed to launch external program dot net . spawn dotnet ENOENT

### ISSUE THREAD

**Issue by asednev** [Microsoft/vscode#5732]
- VSCode Version: Version 1.0.0 (1.0.0)
- OS Version: Mac OS X 10.11.5

Steps to Reproduce:
1. Open Visual Studio Code with installed C# extension
2. Open C# project
3. Go to View -> Debug
4. Click "Start" button, select .NET Core Launch

Error appears in output window:

> Failed to launch external program dot net .
> spawn dotnet ENOENT

**Comment by bpasero** [comment]
@asednev I suggest you report this against the C# extension?

**Comment by bdqnwuqunqun** [comment]
hi, @asednev  I also encountered  this problem. How do you solve？

**Comment by yuzd** [comment]
i got same error . how do you solve?

**Comment by mmmeff** [comment]
@asednev @yuzd 

Had the same problem and fixed it by adding the dotnet environment variable to my user path. It gets added to the system path when installed, but for some reason the vscode extension had trouble opening dotnet if it wasn't in the user path.
