### ISSUE TITLE
Clicking on the description unexpectedly set/unset checkbox

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#57327]
re  #57304

* scroll to a setting that has a check box
* hover over its description
* notice that the mouse style is 'text cursor'
* click
* the check box toggles

I find that very irritating. Either change the mouse style or only toggle the checkbox state when clicking the checkbox. Other settings don't seem to be sensitive to clicking their description, e.g. a text field doesn't get focus.

**Comment by roblourens** [comment]
Where do you see the text cursor? It should be the default arrow on all settings. Maybe it should be pointer for bool instead.

**Comment by jrieken** [comment]
Sorry, not text cursor but default and pointer cursor...

![aug-29-2018 09-03-24](https://user-images.githubusercontent.com/1794099/44771138-7275b580-ab6a-11e8-98b4-41660e7f4ff7.gif)

**Comment by jrieken** [comment]
Verified that the cursor is now correct but the behaviour still seems weird to me
