### ISSUE TITLE
Settings editor shouldn't open a new instance when one is already open

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#57326]
re  #57304

* have a two column layout
* open settings editor in column one
* open a source file in column two, e.g. to test the effect of a setting
* press <kbd>Ctrl+,</kbd> to go back to settings
* 🐛 another instance of the settings editor is opened which is unwanted.

**Comment by roblourens** [comment]
Why not? Everything else works this way - keyboard shortcuts, old settings editor, even normal files

**Comment by jrieken** [comment]
Well, when I think about the Setting UI I really, really don't think about an editor or about editor behaviour. For me it's a single UI piece that happens to be implemented as editor and I don't see any advantage in it throwing new a context at me - I lose my scroll and filter state when this happen.

**Comment by jrieken** [comment]
> Should it be impossible to open two instances in different groups?

No sure. It would sure to reuse the existing setting editor when possible but I would prevent explicit split gesture and cmd-drag
