### ISSUE TITLE
No settings shown when having filter

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#57322]
re #57304

* open settings UI
* restart VS Code (quit, start)
* in the settings UI  type `@` and select `@tag:usesOnlineServices`
* it shows '13 Settings Found'
* 🐛 no setting is actually rendered

<img width="917" alt="screen shot 2018-08-28 at 09 24 03" src="https://user-images.githubusercontent.com/1794099/44707307-750dd780-aaa4-11e8-970b-1657c9666169.png">

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/57347
