### ISSUE TITLE
Unhelpful message when no settings are found

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#57321]
re  #57304

Search for something that doesn't match any setting. In comparison to search, the message is a little short and unfriendly. For instance, it could offer to undo some filters.

<img width="314" alt="screen shot 2018-08-28 at 09 21 16" src="https://user-images.githubusercontent.com/1794099/44707110-e26d3880-aaa3-11e8-9bc0-12dd7832793e.png">

better

<img width="242" alt="screen shot 2018-08-28 at 09 22 35" src="https://user-images.githubusercontent.com/1794099/44707126-ed27cd80-aaa3-11e8-86b9-4064e7e1493b.png">

**Comment by roblourens** [comment]
I'm not sure, would a button to clear the input field be helpful? Or remove the @ filters but leave the rest of the query?

**Comment by jrieken** [comment]
Both? A link for clearing @-filters and one for clearing the rest. Or know which on to remove by already testing them with changes in the background.

**Comment by roblourens** [comment]
Is that really useful though? Search needs it because people collapse the query details then forget that it's searching somewhere else, or don't know how to get rid of the filter. Here, there is clearly a text box and the user just typed in it.

**Comment by roblourens** [comment]
Would take a PR that adds two link/buttons to that message, one to remove filters (when filters are present), the other to clear the whole search string.
