### ISSUE TITLE
Smoke test: terminal tests failing for german keyboard layout

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#57328]
- OS Version: macOS

This is not a new issue for me, the terminal smoke tests for some reason are always failing when running out of sources:
* cd `test/smoke`
* run `tsc` to compile them
* run `npm run smoketest`
* wait for the terminal test

=> the terminal does not open and so the test fails

//cc @joaomoreno

**Comment by joaomoreno** [comment]
This test passes on my Linux box.

**Comment by bpasero** [comment]
Also works for me on Windows.

**Comment by bpasero** [comment]
It DOES NOT work for me on Linux either:

![image](https://user-images.githubusercontent.com/900690/44722068-2c6a1480-aacc-11e8-86f1-210507e892fe.png)

**Comment by bpasero** [comment]
We found out that its possibly related to my german keyboard layout.

**Comment by bpasero** [comment]
Verified via https://github.com/Microsoft/vscode/commit/a7a21f3118da5944e6cc76dafa524390cb3fb850
