### ISSUE TITLE
Extending a class of an imported script (<script>) that is typed with TS Defs looses the parameters in the overridden method

### ISSUE THREAD

**Issue by enjikaka** [Microsoft/vscode#57339]
- VSCode Version: Version 1.26.1 (1.26.1)
- OS Version: macOS 10.13.4 (17E199)

Steps to Reproduce:

Reproducible setup and steps here -> https://github.com/enjikaka/type-fail-params-vscode

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#26886
