### ISSUE TITLE
Show other matching extensions button looks mis-aligned

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#57336]
Testing #57306

![image](https://user-images.githubusercontent.com/10746682/44710329-2b28ef80-aaac-11e8-81f8-319deac3259c.png)

- Not sure if it has to be that prominent. It can be rendered as link next to `No Settings Message`
- Now you can have more descriptive label - Show extensions from Marketplace with this setting. 

Eg:

![image](https://user-images.githubusercontent.com/10746682/44710407-63303280-aaac-11e8-96ac-592cc24080db.png)

**Comment by roblourens** [comment]
It also can appear when there are local results though. Should we hide "no settings found" when that button is visible?

**Comment by sandy081** [comment]
Not sure have to see how it looks with results

**Comment by JacksonKearl** [comment]
Do we still even have this widget?
![image](https://user-images.githubusercontent.com/8586769/98594041-efdbfb00-2288-11eb-9669-0a6401cede9c.png)

**Comment by roblourens** [comment]
There are issues with the bing search service right now, so you probably won't see it. Gonna close this though.
