### ISSUE TITLE
Prophet Debugger not working on latest VScode Insider update

### ISSUE THREAD

**Issue by himaanshu24** [Microsoft/vscode#57337]
Prophet Debugger (debug )stopped working on updating the VScode insider but working again when rollback the update to the previous version.

The debugger keeps showing running underscore but never starts.

![image](https://user-images.githubusercontent.com/8476966/44710073-df387380-aac8-11e8-903c-9f89d0cc0406.png)

 **System Information:**

CPUs | Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)
-- | --
GPU Status | 2d_canvas: enabled 
Memory (System) | 15.70GB (3.56GB free)<br />checker_imaging: disabled_off <br/> <br/> flash_3d: enabled<br/> flash_stage3d: enabled<br/> flash_stage3d_baseline: enabled<br/> gpu_compositing: enabled<br/> multiple_raster_threads: enabled_on<br/> native_gpu_memory_buffers: disabled_software<br/> rasterization: enabled<br/> video_decode: enabled<br/> video_encode: enabled<br/> webgl: enabled<br/> webgl2: enabled
Process Argv | C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe
Screen Reader | no
Screen Reader | no
VM | 0%

**Comment by isidorn** [comment]
Please file this against the Prophet Debugger extension. Once they investigate what is wrong they can report back to vscode if it is on our side.
Thank you

**Comment by isidorn** [comment]
Also what extensions do you have installed?
