### ISSUE TITLE
VSCode Icon not shown on 2nd display

### ISSUE THREAD

**Issue by mrmunch** [Microsoft/vscode#57334]
- VSCode Version: 1.26.1
- OS Version: 10.0.15063

Steps to Reproduce:

1. Use two (or more) monitors
2. Open a file with VS Code

On my primary monitor, the VS Code Icon shows up correctly in my task bar:
![image](https://user-images.githubusercontent.com/12833236/44709199-4b0ae400-aaa9-11e8-8e24-353a25f768d8.png)
But on all other monitors, there is no VSCode icon displayed:
![image](https://user-images.githubusercontent.com/12833236/44709257-72fa4780-aaa9-11e8-8a98-e4fd68191586.png)

---

Also, there is no icon for "edit with code" when right-clicking on a file:
![image](https://user-images.githubusercontent.com/12833236/44709316-9f15c880-aaa9-11e8-8e5d-429aff28a9fd.png)
(by the way: what's the difference between "edit" and "open" in this context?)

**Comment by dbaeumer** [comment]
Might be Electron related.

**Comment by bpasero** [comment]
@mrmunch did it work before?

**Comment by bpasero** [comment]
Adding @joaomoreno

**Comment by joaomoreno** [comment]
Our distribution doesn't come with that `edit with code` action... you must've gotten that via some other way.

Does it work if you remove the shortcuts from the start menu and add them again?

**Comment by mrmunch** [comment]
@joaomoreno I did not install it with a start menu shortcut. But after adding it to the shortcuts, the icon on the second monitor shows up now, thanks!
But the second problem - "Edit with VS Code" - still occurs.

**Comment by joaomoreno** [comment]
Good to know.

`Edit with VS Code` isn't something VS Code contributes. Another software must've set that up for you.
