### ISSUE TITLE
Show parameter name and type when hovering the argument in function call (TypeScript)

### ISSUE THREAD

**Issue by Cristy94** [Microsoft/vscode#57341]
If I have a function with many parameters, it's hard to know which argument is for which parameter.

Let's say I have this function:
`const doSomething = (a: ObjectA, b: ObjectB, doA: boolean, doB: boolean, skipChecks: boolean) => {}`

And then I would call the function like this:
`doSomething(objA, objB, true, false, false);`

It would be really useful if when I **hovered** the arguments I would get a tooltip:
```
                           [doB: boolean] <-- tooltip
                                |
doSomething(objA, objB, true, false, false);
                               ^ (mouse over)
```

**Comment by dbaeumer** [comment]
@Cristy94 which language are you using. This is something that can be controlled by the language support which reacts on the hover request. So it needs to be implemented in the language server

**Comment by Cristy94** [comment]
I am using TypeScript.

**Comment by mjbvz** [comment]
Good feature request. I've opened https://github.com/Microsoft/TypeScript/issues/29408 to track this upstream. VS Code should pick up support automatically once the TS server adds this feature
