### ISSUE TITLE
Intellisense in JSON file is not working

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#57342]
Issue Type: <b>Bug</b>

- Open a Package.json file
🐛 Intelli-sense is not working

![image](https://user-images.githubusercontent.com/10746682/44712581-70035500-aab1-11e8-9254-9245414cd8c2.png)

VS Code version: Code - Insiders 1.27.0-insider (43676d0cb7db94e2fa771f1d10bff10eaa01b453, 2018-08-28T05:12:24.162Z)
OS version: Darwin x64 17.3.0

**Comment by aeschli** [comment]
fixed by https://github.com/Microsoft/vscode/commit/1cdea4a65412031b7a400207661715d7eb923303
