### ISSUE TITLE
Side Bar UI problem

### ISSUE THREAD

**Issue by maorui2014** [Microsoft/vscode#5734]
- VSCode Version: 1.0.1-insider
- OS Version: Windows 10 1511 - 14328.1000

Steps to Reproduce:

1.  view bar

![1](https://cloud.githubusercontent.com/assets/18439500/14775314/d505fe98-0af0-11e6-8c53-14ae27df4102.png)

2.  side bar
 
![2](https://cloud.githubusercontent.com/assets/18439500/14775839/85288068-0af4-11e6-8136-65e8543afc6c.png)

**Comment by bpasero** [comment]
Thanks, we fixed this meanwhile but have not yet pushed for another insider update!
