### ISSUE TITLE
We need a API - positionAt(byte offset)

### ISSUE THREAD

**Issue by owt5008137** [microsoft/vscode#5735]
- VSCode Version: 1.0.0
- OS Version: windows 10

I want to make the extension ["clang-format"](https://marketplace.visualstudio.com/items?itemName=xaver.clang-format) work better with chinese(or other asia languages).But clang-format only provide byte offsets of a text.Using [TextDocument.positionAt](https://code.visualstudio.com/docs/extensionAPI/vscode-api#TextDocument.positionAt), we will got a Position object with charactor offset but not byte offset.

Steps to Reproduce:
1. Run "clang-format -output-replacements-xml -style=llvm" for file https://github.com/atframework/atframe_utils/blob/master/include/string/ac_automation.h, we get the first replacement node with offset='288' and length='180'.
2. We use [TextDocument.positionAt](https://code.visualstudio.com/docs/extensionAPI/vscode-api#TextDocument.positionAt)(288), we get line=19 and col=15
3. But what we want is line=19 and col=1
4. The problem is "自动机算法实现"(UTF-8) takes 21 bytes, but VSCode think it has 7 charaters.

I think it's better for vscode provide a API to do so, than we analysis all the content again.

**Comment by owt5008137** [comment]
We also need the API byteOffsetAt which just like [TextDocument.offsetAt](https://code.visualstudio.com/docs/extensionAPI/vscode-api#TextDocument.offsetAt)

**Comment by jrieken** [comment]
fyi @alexandrudima

**Comment by jrieken** [comment]
@owt5008137 clang-format seems to have a line-based mode. http://clang.llvm.org/docs/ClangFormat.html

any special reasons you don't use 'lines' for what you want to achieve?

**Comment by owt5008137** [comment]
@jrieken We allow users only format the selected codes, and any user can select any code section, with or without the whole line.

**Comment by jrieken** [comment]
Understood, still you should consider using that since add support for bytes won't come soon as this is a huge effort across our whole stack

**Comment by owt5008137** [comment]
@jrieken Thanks.I use [Buffer](https://nodejs.org/dist/latest-v5.x/docs/api/buffer.html) class to decode the text and calculate the byte-offset now.I will replace the codes and use the decode result of VSCode after these APIs are provided.

**Comment by jrieken** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!

**Comment by nhooyr** [comment]
Does the reopening of this mean it will be considered?

At coder, we need this feature for our collaborative editing to work performantly. Could you provide a outline on exactly what needs to be done where and we might be able to get a PR in for it.
