### ISSUE TITLE
Breadcrumb: clicking into scrolled breadcrumb changes scroll position

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#57351]
Refs: https://github.com/Microsoft/vscode/issues/57280

- OS Version: Windows 10

Steps to Reproduce:

1. have a long enough breadcrumb that it scrolls
2. scroll to the middle
3. click on a breadcrumb entry

=> 🐛 the breadcrumb scrolls as soon as its clicked

I had tabs disabled in this case.

**Comment by jrieken** [comment]
yeah, was waiting for that one 🙈
