### ISSUE TITLE
Breadcrumbs: align decorations to the right

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#57353]
Refs: https://github.com/Microsoft/vscode/issues/57280

Looks like decorations in breadcrumbs come right after the label and not at the end:

![image](https://user-images.githubusercontent.com/900690/44714563-edc95f80-aab5-11e8-8c67-aec6e5ebcd6c.png)

I suggest having the same looks everywhere.

**Comment by jrieken** [comment]
Nice find - must be some recent regression.

**Comment by jrieken** [comment]
fixed via c3e2448766
