### ISSUE TITLE
Breadcrumbs: files.exclude not working

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#57356]
Testing: https://github.com/Microsoft/vscode/issues/57280

- OS Version: Windows 10

Steps to Reproduce:

1. open settings editor (the new one)
2. add `node_modules` to the rules
3. open the vscode folder
4. open a file

=> 🐛 the `node_modules` folder is not hidden

![image](https://user-images.githubusercontent.com/900690/44714933-ccb53e80-aab6-11e8-98ed-436a1817cd11.png)

Setting:
```
    "files.exclude": {
        "node_modules": true
    }
```

**Comment by jrieken** [comment]
Works when the pattering is `**/node_modules`. @bpasero What massage is required to the paths to make the pattern work? Does the explorer cut off the start of the file or does it add an implicit `**` to the patterns?

**Comment by bpasero** [comment]
@jrieken the explorer is actually checking the workspace relative folder name (in this case `node_modules`) when walking down the list of folders to traverse.

**Comment by jrieken** [comment]
Yeah, I have a [ghetto version of that](https://github.com/Microsoft/vscode/blob/f881f8c4229863782a01eae80d70b4d6d540e39d/src/vs/workbench/browser/parts/editor/breadcrumbsPicker.ts#L270-L272). The challenge is that `src/vs/workbench/browser/parts/editor/breadcrumbsPicker.ts` I cannot use node's path utility. Any reason other than legacy why it is `workbench/browser` and not `workbench/browser-electron`?

**Comment by jrieken** [comment]
Yeah, all fair options. In theory, there is a refactoring to the folder rename that updates all references. For now, I will go with the `**` prefix.

**Comment by jrieken** [comment]
I have pushed a change that make patterns that don't start with `**/` absolute, e.g. `node_modules` becomes `/User/foo/hacking/project1/node_modules`
