### ISSUE TITLE
typescript.tsdk misses UI

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#57367]
Issue Type: <b>Bug</b>

Testing #57304

It appears to be just a string, we could show a text box:

![image](https://user-images.githubusercontent.com/9205389/44715916-4a7a4980-aab9-11e8-9cd0-b3e14eb9d105.png)

VS Code version: Code - Insiders 1.27.0-insider (43676d0cb7db94e2fa771f1d10bff10eaa01b453, 2018-08-28T05:12:24.162Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 5, 4|
|Memory (System)|16.00GB (0.23GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron --user-data-dir /Users/chrmarti/Development/repos/tmp/user2 --extensions-dir /Users/chrmarti/Development/repos/tmp/ext2|
|Screen Reader|no|
|VM|33%|

</details>Extensions: none

**Comment by roblourens** [comment]
It's `string | null` which we can't handle yet: https://github.com/Microsoft/vscode/issues/56413
