### ISSUE TITLE
Webview does not work in built version of VS Code

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#5736]
Because vs/workbench/parts/html/browser/webview.html is missing from the build.

**Comment by bpasero** [comment]
@jrieken fyi

**Comment by jrieken** [comment]
@bpasero I though [this](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/html/browser/htmlPreviewPart.ts#L8) is enough

**Comment by bpasero** [comment]
Hm true, weird. Webview works for me after my change.

**Comment by jrieken** [comment]
now, I get it. Thanks for fixing
