### ISSUE TITLE
Settings: remove preview label

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#57366]
#57304

Either remove this statement completely
![screen shot 2018-08-28 at 11 54 07](https://user-images.githubusercontent.com/1926584/44715857-19017e00-aab9-11e8-8e93-373862119831.png)

Or make it clickable to go from there to the old settings.json experience
Also the Settings(Preview) title feels too much for me if we already have the title

**Comment by roblourens** [comment]
#57320
