### ISSUE TITLE
Right-click file, missing options

### ISSUE THREAD

**Issue by thany** [Microsoft/vscode#57363]
In the right-click menu on a file, the option for creating a new file and new folder is missing. They appear only when right-clicking on a folder.

- VSCode Version: 1.26.1
- OS Version: Windows 10

Steps to Reproduce:

1. Have the side bar shown.
2. Open some folder with files.
3. Right-click any file.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
This is as designed. If you would like to add that option also for files you can install some file operations extensions or write an extension yourself

**Comment by thany** [comment]
Not really. The option to create a file or folder are already implemented. Not having them where it *does* make sense, is a bug to me.

Extensions must not become bugfixes!
