### ISSUE TITLE
Settings: hover in content area does not bring useful information

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#57361]
Ref: #57304

Hover over the table of contents on the left, the hover just repeats whatever is there. It does not bring any information.

My suggestion is to remove it

![screen shot 2018-08-28 at 11 42 49](https://user-images.githubusercontent.com/1926584/44715265-a17f1f00-aab7-11e8-876e-1d2ee046813d.png)

**Comment by roblourens** [comment]
I thought there was an accessibility reason for these, we have other redundant tooltips too. I can get rid of them though.

**Comment by isidorn** [comment]
@roblourens check if the screen reader announces anything differently if you remove the `title`. I think there will be no change.

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/commit/7158f4997a14e0e4dd9b4fe9621ff2fbbc829251

I can't remember why I thought it was necessary...
