### ISSUE TITLE
Remove refresh button

### ISSUE THREAD

**Issue by thany** [Microsoft/vscode#57368]
The side bar is pretty darn cluttered, and a lot of stuff can be removed. For instance, the refresh button. I expect the project folder to refresh automatically, so the refresh button isn't needed.

We should have EITHER a refresh button and no auto refresh, OR auto refresh and no refresh button. An option in the right-click menu will do in the latter case.

**Comment by isidorn** [comment]
Now that I think about it I do agree that the refresh button is a little bit too prominent and if I redesigned the explorer I would put it as a top level context menu action.
However changin it now will piss off users who got used to it there.
Yeah we are the latter case and we have auto refresh. However let's leave this open and we might reconsider this in the future.
Another reason to keep it top level -> consisteny with git viewlet that also keeps it there

**Comment by thany** [comment]
Pissing of other users is a real concern? Microsoft has some history with that, are they going to find themselves in a better situation now? :)

Anyway, how can removing a *totally* useless button piss off anyone? If there's auto-refresh, literally no one is going to need it, given that auto refresh actually works good.

The git viewlet, I haven't used it, but I don't see why a git plugin needs a refresh button either. I use an external tool, GitKraken, which doesn't have a refresh button. You know why? Because it has auto-refresh, just like every git tool.
