### ISSUE TITLE
Enum setting change inconsistently displayed

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#57364]
Issue Type: <b>Bug</b>

Testing #57304

It is in the end shown as 'afterDelay' although I changed it back to 'off':

![aug-28-2018 11-51-03](https://user-images.githubusercontent.com/9205389/44715710-b8724100-aab8-11e8-8931-806ec0f6619a.gif)

VS Code version: Code - Insiders 1.27.0-insider (43676d0cb7db94e2fa771f1d10bff10eaa01b453, 2018-08-28T05:12:24.162Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron --user-data-dir /Users/chrmarti/Development/repos/tmp/user2 --extensions-dir /Users/chrmarti/Development/repos/tmp/ext2|
|Screen Reader|no|
|VM|33%|

</details>Extensions: none

**Comment by roblourens** [comment]
Good repro steps. I vaguely knew there was something wrong with this.
