### ISSUE TITLE
Settings: position not preserved across vscode sessions

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#57365]
Refs: #57304

1. Go to some custom settings in the settings editor
2. Reload window -> notice the settings editor is in the initial Commonly Used position

I would expect that we preserve the location since settings can be quite complex and it might be painful to go back to where I was and since we already do this for all our other editors so consistency.

**Comment by isidorn** [comment]
I would also expect the input box to be preserved
Use case: I always only want to see my modified settings, so I expect the @modifed to always be there

**Comment by roblourens** [comment]
Covered by #57289
