### ISSUE TITLE
Settings: show other matching extensions weird button

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#57376]
Refs: #57304

Settings ux > search for "debug breakpoint" for example
Notice the weird button
"Show other matching extensions" -> click on it, now the extensions viewlet is open with the following query
"@id:otris-software.vscode-janus-debug @id:vscjava.vscode-java-debug"

I am absolutetly puzzled as to what this button is supposed to do? And how it should help with anything. Can you please explain, am I missing something here or it is a bug?

![screen shot 2018-08-28 at 12 18 48](https://user-images.githubusercontent.com/1926584/44717208-c033e480-aabc-11e8-82e3-3e9cac785cb9.png)

**Comment by roblourens** [comment]
Bing now returns results for matching settings in all the extensions in the marketplace. We show these results for extensions that you don't already have installed.

**Comment by isidorn** [comment]
I would rename this button to
"Show not installed extensions" or "Show extensions from marketplace"

With the current title the issue is that I am not sure what "other" is refering to.

**Comment by roblourens** [comment]
I'll try "Show matching extensions"
