### ISSUE TITLE
lsp-sample: failure launching task

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#57379]
Testing #57276.

Elementary OS 0.4.1 (Built on "Ubuntu 16.04.2 LTS")

- clone the https://github.com/Microsoft/vscode-extension-samples.git
- cd to the lsp-sample
- npm install
- from the menu run 'Run Task...', pick `npm: watch:client`
- error 
`The terminal process command '/bin/bash -c ''npm run watch:client''' failed to launch (exit code: 127)`

Running ` /bin/bash -c "npm run watch:client"` in the internal terminal works
Running `npm run watch:client` in the internal terminal works

**Comment by bpasero** [comment]
Quite sure @dbaeumer fixed this already.

**Comment by dbaeumer** [comment]
Yes, fixed it yesterday.
