### ISSUE TITLE
Inconsistent behaviour between global and local mnemonics 

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#57375]
re #57316

* ubuntu 18.04
* press ALT
* press V, view menu shows
* now pressing F will open the File menu, where m doesn't open the Terminal menu but triggers the minimap. I am unsure how what the 'native default' is but it is confusing to me (being more a less a first time user)

**Comment by sbatten** [comment]
@jrieken good catch, looks like native doesn't let you switch menus like that so I've disabled mnemonics at the top level when a menu is open.
