### ISSUE TITLE
Screenreader should read gear button shortcut

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#57378]
Issue Type: <b>Bug</b>

Testing #57304

I couldn't find a way to navigate to the gear menu using the keyboard:

![image](https://user-images.githubusercontent.com/9205389/44717748-3553e980-aabe-11e8-96c2-078ef2d1438b.png)

VS Code version: Code - Insiders 1.27.0-insider (43676d0cb7db94e2fa771f1d10bff10eaa01b453, 2018-08-28T05:12:24.162Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron --user-data-dir /Users/chrmarti/Development/repos/tmp/user2 --extensions-dir /Users/chrmarti/Development/repos/tmp/ext2|
|Screen Reader|no|
|VM|33%|

</details>Extensions: none

**Comment by roblourens** [comment]
There is a keyboard shortcut, but we thought that it's not natural to have all of them as tab targets.

The keyboard shortcut needs to be read in the aria-label, which I haven't done yet...

**Comment by cleidigh** [comment]
@roblourens 
Are you thinking of having "Press alt-F9 for settings options" or something similar?
that's gonna be a lot of extra stuff, no?

**Comment by roblourens** [comment]
Yeah exactly, I'm not sure how that will work, but if it's not a tab target I think it needs to be more discoverable to keyboard users.

**Comment by cleidigh** [comment]
but I think we agree there are already too many tab targets
I wonder if one time announcement when arriving on the settings page would do it
the last thing an accessibility user needs is repetition of a behavior indicator that doesn't change

**Comment by roblourens** [comment]
> the last thing an accessibility user needs is repetition of a behavior indicator that doesn't change

One existing precedent I thought of is in the extension viewlet, aria-label for every item includes "Press enter for extension details". It's annoying but I'm not sure what else to do.

**Comment by cleidigh** [comment]
do you want me to look at this?

**Comment by roblourens** [comment]
Sure, if you have any ideas

**Comment by cleidigh** [comment]
I'm trying to understand exactly what you mean by your above statement 'element with describedby'
I'm rusty on the thread

**Comment by roblourens** [comment]
You use `describedby` to point at the description, which is how the description is read, right?

**Comment by cleidigh** [comment]
correct
I'm not clear on the latest problem.  Do you need a multiple component reader label? Not ideally the title?

**Comment by roblourens** [comment]
I think the screenreader should read the keyboard shortcut for the gear button after it reads the name and description of the setting, if that's possible.

**Comment by roblourens** [comment]
Oh, you can set multiple ids in describedby and it will read all of them? Sounds perfect.

**Comment by cleidigh** [comment]
yup, so can aria-labeledby !

targets have to be static, what I did is to add a div to to the option template with no content
but the aria-label attribute
