### ISSUE TITLE
Settings: enum description shows wrong one

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#57382]
Refs: #57304

Open some enum description in the select dropdown. Notice how the description always shows the wrong one, not the selected item.
For multiple options the issue is seens when the last option is selected. So when there are only 2 this is particularly noticable.

![screen shot 2018-08-28 at 12 37 54](https://user-images.githubusercontent.com/1926584/44718113-4f41fc00-aabf-11e8-8526-4b3261e79c3a.png)

**Comment by cleidigh** [comment]
@roblourens 
I will pick this up since it's in the select code...

**Comment by isidorn** [comment]
@cleidigh it would be cool if we do it this week, so I will assign this to August. Hope that is all right.

**Comment by roblourens** [comment]
Fixed in a different issue

**Comment by cleidigh** [comment]
@isidorn 
@roblourens 
HaHa - I was just looking at this and not seeing it !
