### ISSUE TITLE
Should CSS/SCSS import suggest each other?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#57388]
Refs: https://github.com/Microsoft/vscode/issues/57309

In the suggestions I see CSS and SCSS suggestions, but does a CSS file support a SCSS import?

![image](https://user-images.githubusercontent.com/900690/44719073-76e69380-aac2-11e8-89da-3d3fe027e40e.png)

**Comment by octref** [comment]
It's beyond me why people would want this, but this is doable with parcel and webpack, and people do use import in this way: https://github.com/webpack-contrib/sass-loader/issues/101

![image](https://user-images.githubusercontent.com/4033249/44756744-bfad4500-aae0-11e8-8e28-ac3c1371836f.png)
