### ISSUE TITLE
Screen cheese in settings editor

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#57385]
re  #55791

* open setting editor
* search for 'title'
* two entries show, they overlap

<img width="854" alt="screen shot 2018-08-28 at 12 55 29" src="https://user-images.githubusercontent.com/1794099/44718931-0770a400-aac2-11e8-85c9-7dc6da055b2c.png">

**Comment by roblourens** [comment]
This comes from estimating the description height which I have to do as an optimization. This is still not perfect but it's better now.

Verification:
- Look at different settings, resize the window horizontally, and make sure they are layed out correctly and don't overlap
- Try this while searching, not searching, and with the TOC visible and hidden (when the settings editor is narrow)
