### ISSUE TITLE
Settings: icon in suggest box does not seem useful

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#57380]
Refs: #57304

Trigger inteli-sense in the settings input box. Notice the weird icon left of the @ 
The point of using icons in inteli-sense is to diferentiate items, however since in this use cases all items use the same icon this looses the point.
I have also not seen this icon anywhere else in vscode.
So my recommendation is to remove it

Samo as for extensions input. The icon is just noise

@ramya-rao-a @misolori 

![screen shot 2018-08-28 at 12 30 43](https://user-images.githubusercontent.com/1926584/44717766-3edd5180-aabe-11e8-9c4c-71243dae65b7.png)

![screen shot 2018-08-28 at 12 32 48](https://user-images.githubusercontent.com/1926584/44717844-7ea43900-aabe-11e8-9f8d-a8ca62f31a42.png)

**Comment by isidorn** [comment]
Let's just remove the icon now and we can add them once we have categories (if that ever happens)

**Comment by roblourens** [comment]
Is it possible to remove it? I think all suggest widget items need an icon

**Comment by jrieken** [comment]
:-1: for type `none`. You should just tell that widget instance not to render icons. We already have the global ['iconsInSuggestion'](https://github.com/Microsoft/vscode/blob/3da2f86e4dfdf0f183810a9b6d5c5a22ba692e5e/src/vs/editor/contrib/suggest/suggestWidget.ts#L439) setting and I think it's just a matter of making that an instance thing

**Comment by roblourens** [comment]
I see that setting, it applies to the editor instance so it should be usable here. It just looks like I have to add a CSS rule for the `no-icons` class.

**Comment by ramya-rao-a** [comment]
@jrieken That setting is not exposed to the user. And the suggest widget doesnt really respect it. It adds the `no-icons` class to the element, but there is no css rule to make the icons disappear.

Was this is a old feature that got missed along the way?

**Comment by jrieken** [comment]
Yeah, maybe. @joaomoreno would know

**Comment by joaomoreno** [comment]
![shrug](https://media.giphy.com/media/3ov9k0MVnBQlJkflpS/giphy.gif)

**Comment by roblourens** [comment]
Added a new rule just for SuggestEnabledInput. Maybe we should just have a rule for all suggest widgets, but I see the outline panel is using the same class and I'm not sure what else it would disturb? 

Looks nicer though

![image](https://user-images.githubusercontent.com/323878/45640078-7eb4aa80-ba66-11e8-9c73-f35b74919d0f.png)

**Comment by ramya-rao-a** [comment]
@roblourens The outline panel does not use the suggest widget, so I dont know how the 2 are related. I would suggest add the css rule in https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/suggest/media/suggest.css#L145

**Comment by roblourens** [comment]
Oh, right. But still I don't know what monaco users are expecting or why the rule doesn't exist, so I'm not just going to add a css rule.
