### ISSUE TITLE
editor.codeActionsOnSave > source.organizeImports seems to break schematics templates

### ISSUE THREAD

**Issue by larsholleboom-luminis** [Microsoft/vscode#57391]
While creating a template for a component with angular cli schematics, I copied the components template folder of node_modules/@schematics/component and pasted it in my own project and edited the file.
When saving the following part with the setting editor.codeActionsOnSave: { source.organizeImports: true } 
`import { Pn<%= classify(name) %>Component } from './<%= dasherize(name) %>.component';`
is formatted to
`import {Pn} from <>;
%= classify(name) %>Component } from './<%= dasherize(name) %>.component';`
which is i.m.h.o. unexpected and unwanted behavior
Could you please make a fix for this in a next release version?

**Comment by mjbvz** [comment]
That is not valid JS and is beyond the scope of supporting in VS Code core. Other features such as formatting and intellisense may also not work.

Consider writing your own language extension if you want templated js like this supported
