### ISSUE TITLE
Improve context view placement around box

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#57399]
On Linux.

If I open the editor context menu in a small enough window, the action right below the mouse cursor will be executed instantly, since the change that makes an action run on mouse up. We should nudge the menu 1px to the side (to the right when on the right side, to the left when on the left) in order not to have the menu right below the mouse cursor.

It doesn't repro if the window is large enough since the menu will be 1px nudged down in that case.

**Comment by sbatten** [comment]
@joaomoreno sorry, I can't repro this on windows and I don't have access to my Linux VMs while traveling. Also, could you point me to where the nudging down happens so I can add left and right? I was looking in `contextview.ts` but didn't find it.

**Comment by joaomoreno** [comment]
The nudging happens here: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/contextmenu/contextmenu.ts#L99

This appears to be a bad place to do it, since it only affects editor context menus. I was able to fix my problem by adding 2 to the `x` coordinate, 1 was not enough. But other menus around the workbench still suffer from the same problem, e.g. explorer.

**Comment by bpasero** [comment]
This seems to not be a problem on Windows where the menu does not seem to open on mouse down.

**Comment by bpasero** [comment]
@sbatten PR up at https://github.com/Microsoft/vscode/pull/57614

**Comment by bpasero** [comment]
Talking with @joaomoreno, needs support from the context view component.

**Comment by eltian** [comment]
Can confirm. If I right-click to open the context menu and the cursor ends up somewhere in the middle of the menu, the action under the cursor gets executed. I can avoid this if I keep the mouse button down, though.
