### ISSUE TITLE
Loaded scripts: this.context.dataSource.getParent(...).then is not a function

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#57395]
#57249

Both on linux and osx.

Focus inside the loaded scripts view. Navigate through the loaded scripts view using up / down arrows, notice error notification:

`this.context.dataSource.getParent(...).then is not a function`

**Comment by weinand** [comment]
Great find!

**Comment by weinand** [comment]
fix: https://github.com/Microsoft/vscode/commit/eef783fb77fe68be5372c69f0a0fe7d67b174a12
