### ISSUE TITLE
JSON coloring is off

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#57398]
- Clone: https://github.com/Microsoft/vscode-eslint.git 
- open the top level package.json
- go to contribution `eslint.validate`

**Comment by aeschli** [comment]
Dark+
![image](https://user-images.githubusercontent.com/6461412/45508899-5db63600-b796-11e8-997e-964176f2ff53.png)
Light+
![image](https://user-images.githubusercontent.com/6461412/45508914-6dce1580-b796-11e8-8130-cc35cef0989a.png)


The grammar seems to be ok to me. Maybe an issue with the theme you use?

**Comment by aeschli** [comment]
(also we have tests for this...)
