### ISSUE TITLE
Use "Exclude" UI also for Watcher Excludes

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#57396]
Issue Type: <b>Bug</b>

Testing #57304

![image](https://user-images.githubusercontent.com/9205389/44722566-b9619d80-aacd-11e8-95ce-56dc1a68f7a3.png)

VS Code version: Code - Insiders 1.27.0-insider (f881f8c4229863782a01eae80d70b4d6d540e39d, 2018-08-28T09:47:27.146Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.17GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron --user-data-dir /Users/chrmarti/Development/repos/tmp/user2 --extensions-dir /Users/chrmarti/Development/repos/tmp/ext2|
|Screen Reader|no|
|VM|33%|

</details>Extensions: none

**Comment by bpasero** [comment]
@roblourens one thing to keep in mind is that `files.exclude` is being matched on the workspace relative path while `files.watcherExclude` is matched on the full absolute path. So the patterns need to have `/**` at the end for the watcher excludes.
