### ISSUE TITLE
Compare not working for large XML files?

### ISSUE THREAD

**Issue by fkauffmann** [Microsoft/vscode#5739]
- VSCode Version: 1.0.0
- OS Version: Windows 7 Enterprise SP1 64 bits
- .Net Framework 4.5.2 installed

Steps to Reproduce:
1. Download the two following sample XML files:
   https://drive.google.com/open?id=0B0GuFolRSbJ-aHhhLW5RRDU4eUU
   https://drive.google.com/open?id=0B0GuFolRSbJ-bDB0eFVZMTE4bkk
2. Choose "Select for Compare" on first file in Explorer bar
3. Choose "Compare with" on the second file

No highlight of differences. VSCode works fine with smaller files. Both files are UTF-8 encoded.

**Comment by bpasero** [comment]
@alexandrudima are we maybe disabling compare for large files?

**Comment by bpasero** [comment]
At least I see we stop coloring after some lines in those files.

**Comment by alexandrudima** [comment]
Diffing is (due to memory consumption in web workers reasons) limited to 5MB files.

**Comment by bpasero** [comment]
@alexandrudima didn't you remove this limit?

**Comment by alexandrudima** [comment]
Yeah, the limit is now removed :+1:
