### ISSUE TITLE
A parameterized action to open a file or folder

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#574]
_From @alefragnani on November 8, 2015 17:4_

Where can I find documentation for _core commands_, like `workbench.action.files.openFolder`?

I'm creating an extension to switch between projects (folders) and was thinking to use this command, indicating the destination folder (`vscode.commands.executeCommand("workbench.action.files.openFolder", "c:\somefolder\somesubfolder")`). But instead of switching to that folder, it only shows an _open dialog_. 

Of course, I don't know if I'm using the wrong command, or using it wrongly :)

Thanks in advance

_Copied from original issue: Microsoft/vscode-extensionbuilders#84_

**Comment by seanmcbreen** [comment]
_From @guillermooo on November 8, 2015 18:12_

You can check the default `keybindings.json` file to see more available commands. But that isn't a substitute for docs, though. :)

**Comment by seanmcbreen** [comment]
_From @alefragnani on November 8, 2015 19:4_

Yes :+1: 

It was in `keybindings.json` that I discovered the command, and it _appears to be the right one_. But `keybindings.json` doesn't say _how to use it_ (input parameters, expected result, etc). 

I think it will be available only on API Documentation.

**Comment by seanmcbreen** [comment]
Passing args to commands is something we don;t have a great story on.  To get a full list of commands this code can be used:

```TypeScript
		let oCommands:vscode.OutputChannel = vscode.window.createOutputChannel("List Commands");
		oCommands.show;
		
		let a = vscode.commands.getCommands().then( results => {
			results.forEach(i=>oCommands.appendLine(i)); 
		});
```

Then `F1` and open the output window and select the right channel.

@jrieken - any additional thoughts?

**Comment by seanmcbreen** [comment]
_From @jrieken on November 10, 2015 14:56_

Not really, tho we have a list of commands, which you either get via the `getCommands`-call or via the keybindings trick, it's not documented what parameters etc they require. Sorry, it will be past 0.10 for this..

**Comment by seanmcbreen** [comment]
_From @alefragnani on November 10, 2015 15:9_

Ok, No problem :)

But what about this `openFolder`  command?  It would be great to be able to use it on my extension.

Thanks

**Comment by seanmcbreen** [comment]
_From @jrieken on November 11, 2015 8:27_

@bpasero Anything low hanging there?

**Comment by seanmcbreen** [comment]
_From @bpasero on November 11, 2015 9:13_

This action is not meant to have parameters as it really goes to the main side to bring up a open folder dialog.

@alefragnani may I ask what list of folders you would show to the user? Is it recently opened folders?

**Comment by seanmcbreen** [comment]
_From @alefragnani on November 11, 2015 23:26_

Sure @bpasero ,

I want to open another **Code** instance, with an specific folder. This is part of my extension **project-manager** where the user can _save projects_ (folders) that he thinks to be important.

![vscode-package-manager-list-projects](https://cloud.githubusercontent.com/assets/3781424/11105823/ac78396a-88b8-11e5-8ebc-cc1cb4be27bd.png)

I tried to use `child_process.exec`, but I don't understand why it isn't working. I was thinking that I was doing something wrong, but the same code works for another applications.
```
   exec('start \"open ui\" "C:\\Program Files\\Microsoft VS Code\\Code.exe" "C:\\Program Files\\Winmerge\\Files.txt"').
```
I decided to try out `vscode.commands.executeCommand("workbench.action.files.openFolder", "c:\somefolder\somesubfolder")`, first as an alternative for this problem, and second as an alternative for the user to use _the same_ or _a new_ Code instance. 

Do you have any idea?

**Comment by seanmcbreen** [comment]
_From @bpasero on November 12, 2015 11:20_

@alefragnani it should work to spawn another instance of code but it is also quite ugly to be honest because in all cases you need to know the location of code, across platforms.

Can you rename this issue to the actual thing you want: A parameterized action to open a file or folder that you can use? We can look into it, but likely post November.

**Comment by seanmcbreen** [comment]
_From @alefragnani on November 12, 2015 14:43_

@bpasero too ugly, and I don't even think to use that code :smile: It was just a sample to show how the `path` was being used. I thought two alternatives:
* Try to detect across platforms (effectively)
* A `contributes-configuration` where the user defines the path

Wouldn´t be bettter to close this issue and open another one to check why it is not spawning another Code instance via `child_process.exec`? Because when VS Code becomes Open Source, I could check how **Open Recent** works, right?

**Comment by seanmcbreen** [comment]
_From @bpasero on November 12, 2015 14:53_

Yeah feel free to file a bug on the spawn issue if you want. "Open Recent" is not implemented as an extension but rather uses some internal "API" for this. I would even think that opening another folder might qualify for real API on the vscode API surface.

**Comment by seanmcbreen** [comment]
_From @alefragnani on November 12, 2015 15:48_

Thanks @bpasero. 
I renamed this issue as you suggested, since you consider it a good addition for the API and also created the issue #101 about spawning.

**Comment by jrieken** [comment]
there is now a command for this. See https://github.com/Microsoft/vscode/issues/58
