### ISSUE TITLE
Messages not showing up for new LSP trace setting

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#57404]
Refs: https://github.com/Microsoft/vscode/issues/57310

Configure:
```json
    "json.trace.server": {
        "verbosity": "message",
        "format": "text"
    }
```

No output. Works fine if verbosity is "verbose".

**Comment by octref** [comment]
The `verbosity` should be `messages` (note the last `s`). I just fixed the error in docs.

**Comment by octref** [comment]
To Verify: Check the doc here is updated: https://code.visualstudio.com/updates/v1_27#_vscodelanguageclient-json-log-format-and-log-streaming
