### ISSUE TITLE
Jump to definition opens Peek Definition windows

### ISSUE THREAD

**Issue by alexxx537** [Microsoft/vscode#5740]
- VSCode Version: 1.0.0
- OS Version: Windows 7

Steps to Reproduce:

1. KEIL Uvision 3 software creates text file that contains functions code and it's assembler codes. when I want to go to definition it opens peek definition window and shows me 2 definitions: one is that txt file with code and assembler code and second is real function. What is interesting, that I added OBJ folder to exclude files and i cant see this file in my file tree. And it is not only with functions but also with defines.

**Comment by bpasero** [comment]
This is a consequence of having multiple targets for the definition. I am not sure if we can/want to be smarter here.

**Comment by jrieken** [comment]
Some languages allow symbols to be defined in multiple places and if such situations are encountered we show all. @alexxx537 Having said that it might be an issue with the extension you are using.

**Comment by alexxx537** [comment]
But if I add that folder into exclude files how VSC can find it and show definition to me?
