### ISSUE TITLE
Brackets / Quotes are getting auto closed before new line character

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#57405]
Testing #57317

- Have following language configuration
```json
{
	"comments": {
		"lineComment": "REM"
	},
	"brackets": [
		["{", "}"],
		["[", "]"],
		["(", ")"],
	],
	"autoClosingPairs": [
		["{", "}"],
		["[", "]"],
		["(", ")"],
		["\"", "\""]
	],
	"surroundingPairs": [
		["{", "}"],
		["[", "]"],
		["(", ")"],
		["\"", "\""]
	],
	"autoCloseBefore": ";",
	"folding": {
		"markers": {
			"start": "^\\s*(::\\s*|REM\\s+)#region",
			"end": "^\\s*(::\\s*|REM\\s+)#endregion"
		}
	}
}
```
- Have following settings
```json
"editor.autoClosingBrackets": "languageDefined",
"editor.autoClosingQuotes": "languageDefined",
"editor.autoWrapping": "always"
```
- Open a new document with language having above configuration
- Type any of the characters `"` , `{`, `[`, `(`
Expected: They should not be auto closed. They should be auto closed only before `;` 
Observed: They are getting auto closed

**Comment by alexandrudima** [comment]
This is correct, but I find it hard to believe this is a real-life use-case. i.e. folks wanting to limit the auto-closing of brackets/quotes to not happen at the end of a line...

**Comment by alexandrudima** [comment]
There is no plan to add support for this...
