### ISSUE TITLE
Loaded scripts view does not get dynamically updated

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#57401]
Refs: #57249

Have the following JS workspace https://github.com/Microsoft/vscode/files/2238799/loadedScripts.zip
Start debugging hello.js, do a step by step. I would expect the loaded scripts updates and shows new scripts as they get required. Instead the view is always the same

![scripts](https://user-images.githubusercontent.com/1926584/44723216-a8199080-aacf-11e8-92f8-0192c7a4b94d.gif)

**Comment by weinand** [comment]
@isidorn I suspect that loadedScripts events are no longer arriving.

**Comment by weinand** [comment]
@isidorn the new sessions event are no longer arriving here:
https://github.com/Microsoft/vscode/blob/93e30cc319bb2184756819aefbd4f16a27e7a17c/src/vs/workbench/parts/debug/browser/loadedScriptsView.ts#L374

**Comment by isidorn** [comment]
The issue here was that the loaded scripts view gets created only after a session is already alive so he was missing listeners on session which is already present.

**Comment by weinand** [comment]
Careful: if the order of events has changed that drastically after your refactoring, we are potentially breaking extensions that use the newSessionEvent. I don't like this fix.

**Comment by isidorn** [comment]
The order of events has not changed. The only thing that changed is internaly how people register to the loadedScriptsEvent, since it is now on the session, not on the service.
So the extensions will not be affected by this.

**Comment by alexandrudima** [comment]
@isidorn Do we have a build with this fix to test #57249 further ? I can also test from sources, just LMK.

**Comment by isidorn** [comment]
@alexandrudima sorry about that. We do have linux and os x builds, however integration tests are faililng for windows. I will re-trigger builds since I see you have to test windows - they should be out in 30 minutes. And yes you can also test from source afaik
