### ISSUE TITLE
Quotes are not getting Auto closed before space when configured

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#57406]
Testing #57317

- Have following language configuration
```json
{
	"comments": {
		"lineComment": "REM"
	},
	"brackets": [
		["{", "}"],
		["[", "]"],
		["(", ")"],
	],
	"autoClosingPairs": [
		["{", "}"],
		["[", "]"],
		["(", ")"],
		["\"", "\""]
	],
	"surroundingPairs": [
		["{", "}"],
		["[", "]"],
		["(", ")"],
		["\"", "\""]
	],
	"folding": {
		"markers": {
			"start": "^\\s*(::\\s*|REM\\s+)#region",
			"end": "^\\s*(::\\s*|REM\\s+)#endregion"
		}
	}
}
```
- Have following settings
```json
"editor.autoClosingBrackets": "beforeWhitespace",
"editor.autoClosingQuotes": "beforeWhitespace",
"editor.autoWrapping": "always"
```
- Open a new document with language having above configuration
- Type text `abcd efgh`
- Place the cursor after character `d` and type `"`

🐛 Quote is not getting auto closed. Brackets are getting auto closed correctly.

**Comment by alexandrudima** [comment]
There is a built-in heuristic where quotes will not auto-close **after a word**. This heuristic cannot be configured currently.

The heuristic helps when writing prose like the following in a comment:
```
It's important to call this method with all arguments.
```

**Comment by alexandrudima** [comment]
There is no plan to add support for this...
