### ISSUE TITLE
Sticky current debug line after window reload

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#57403]
Testing #56822 on Linux

1. Start EH debugging
2. Hit breakpoint
3. Reload target window (by either <kbd>Ctrl R</kbd> in the window or the Reload action in the toolbar)

Debug toolbar and debug gutter decorations go back to normal, but the editor keeps the yellow current line decoration:

![image](https://user-images.githubusercontent.com/22350/44723716-10b53d00-aad1-11e8-9d6e-ef13a5db4fe2.png)

**Comment by isidorn** [comment]
@joaomoreno very good catch, thanks a lot for this
