### ISSUE TITLE
Bad debug Stop action

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#57409]
Testing #56822 on Linux

When trying our EH debugging, I'm clicking the Stop button before the window is open. I've noticed two distinct patterns:

- Clicking it right as soon as it opens, makes the toolbar go away and back again. Clicking it another time actually stops debugging.
- Clicking it a little bit after the button appears, but before the window is rendered causes a much **much** worse issue:
  - Sometimes the debug toolbar stays, others it dissapears
  - The target window somehow shows a debug target quick open picker
  - Once I close the target window, hundreds of code-insider processes come up, blocking my entire system.

I tried making a screen recording of the last issue, but my system actually crashed and ran out of memory:

![image](https://user-images.githubusercontent.com/22350/44723922-a781f980-aad1-11e8-946b-3bfbd2c056f7.png)

**Comment by isidorn** [comment]
@joaomoreno first issue I can reproduce and I acknowledge. The issue here is that the I am getting the `attach` event after the user clicked stop. I still respect that `attach` event. There are some other cases when the `attach` event can come and the session is already done when it should be re-created and since this is a corner case I would not fix this.

However the second more serious issue I could not reproduce both on OS X and on Linux and I tried around 10 times. Can you please get latest insiders and try to reproduce that one again? 
If you can still reproduce we can do a live session to debug deepter. Thank you

**Comment by joaomoreno** [comment]
@isidorn Keep trying in Linux, I'm sure you can reproduce. I just reproduced it after 5 tries on another Linux box, latest Insiders. It will be very hard to debug since the whole desktop crashes and I need to relogin.

**Comment by joaomoreno** [comment]
@isidorn I actually just hit this when debugging an extension. I cursed the heavens!

**Comment by isidorn** [comment]
@joaomoreno andre refactored a lot and this might no longer be happening
We should try to repro in the office and if we can than I can investigate further on your machine. Maybe tomorrow?

**Comment by isidorn** [comment]
@joaomoreno I see you are busy with the build, nobody else is seeing this so moving to On-Deck
Just ping me when you have some time so we look together.

**Comment by joaomoreno** [comment]
Finally progress! @isidorn and I just narrowed this down. This Reproduces on an Apple keyboard, in which the F keys require Fn to be pressed. Steps:

1. Hold Fn
2. Hold F5
3. Release Fn
4. Release F5

Electron keeps getting F5 key down events. Seems like an issue deep in the hid_apple driver.

**Comment by joaomoreno** [comment]
Linux kernel patch submitted: https://lkml.org/lkml/2019/6/10/898

**Comment by joaomoreno** [comment]
Patch is in the HID sub tree: https://git.kernel.org/pub/scm/linux/kernel/git/hid/hid.git/commit/?h=for-5.4/apple&id=aec256d0ecd561036f188dbc8fa7924c47a9edfd

We can close this! 💪

**Comment by isidorn** [comment]
Adding verified, @joaomoreno is the only guy who can confirm this.

**Comment by joaomoreno** [comment]
https://github.com/torvalds/linux/commit/aec256d0ecd561036f188dbc8fa7924c47a9edfd

You gotta get a `v5.4-rc2` or `v5.4-rc1` Linux kernel. :laughing:
