### ISSUE TITLE
editor.autoWrapping setting can be confused with other wrapping settings

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#57411]
Testing #57317

The new `editor.autoWrapping` setting has nothing to do with the wrapping but it auto surrounds selected text. Since it uses word wrapping it can be easily gets confused with other wrapping settings we have.

It is better to rename it. `editor.autoSurround` as @alexandrudima suggested.

**Comment by octref** [comment]
In the Vim universe this is also called surrond https://github.com/tpope/vim-surround.
