### ISSUE TITLE
LSP: "verbose" "text" outputs JSON

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#57414]
Issue Type: <b>Bug</b>

Testing #57310

`"text"` is misleading in this case.

VS Code version: Code - Insiders 1.27.0-insider (f881f8c4229863782a01eae80d70b4d6d540e39d, 2018-08-28T09:55:30.360Z)
OS version: Linux x64 4.15.0-32-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (2 x 2194)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|5.64GB (0.64GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.38
beautify|Hoo|1.4.2
theme-karyfoundation-themes|kar|18.2.1
vscode-open-in-github|sys|1.7.0
ayu|tea|0.15.0

</details>

**Comment by octref** [comment]
@chrmarti Can you show me how does the log look like?

I'm guessing you are seeing logs of this format?

```
[Trace - 1:26:07 PM] Sending notification 'initialized'.
Params: {}


[Trace - 1:26:07 PM] Sending notification 'workspace/didChangeConfiguration'.
Params: {
    "settings": {}
}


[Trace - 1:26:07 PM] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "file:///Users/octref/Code/work/css/css-test/test.md",
        "languageId": "markdown",
        "version": 1,
        "text": "k\n"
    }
}
```

Then it is expected. This is how logs used to look like.

JSON logs look like this:

```
[LSP   - 1:26:52 PM] {"type":"send-notification","message":{"jsonrpc":"2.0","method":"$/setTraceNotification","params":{"value":"verbose"}},"timestamp":1535574412305}
[LSP   - 1:26:57 PM] {"type":"send-notification","message":{"jsonrpc":"2.0","method":"textDocument/didChange","params":{"textDocument":{"uri":"file:///Users/octref/Code/work/css/css-test/test.md","version":2},"contentChanges":[{"text":"k\n\n"}]}},"timestamp":1535574417307}
[LSP   - 1:26:57 PM] {"type":"send-notification","message":{"jsonrpc":"2.0","method":"textDocument/didChange","params":{"textDocument":{"uri":"file:///Users/octref/Code/work/css/css-test/test.md","version":3},"contentChanges":[{"text":"k\n\n\n"}]}},"timestamp":1535574417588}
[LSP   - 1:26:57 PM] {"type":"send-notification","message":{"jsonrpc":"2.0","method":"textDocument/didSave","params":{"textDocument":{"uri":"file:///Users/octref/Code/work/css/css-test/test.md","version":3}}},"timestamp":1535574417711}
```

**Comment by chrmarti** [comment]
Ok, it's not exactly JSON then. I was wondering if there is a better name than `text`.
