### ISSUE TITLE
Allow to have language without any surrounding pairs

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#57413]
Testing #57317

- Have following language configuration
```json
{
	"comments": {
		"lineComment": "REM"
	},
	"brackets": [
		["{", "}"],
		["[", "]"],
		["(", ")"],
	],
	"autoClosingPairs": [
		["{", "}"],
		["[", "]"],
		["(", ")"],
		["\"", "\""]
	],
	"surroundingPairs": [],
	"folding": {
		"markers": {
			"start": "^\\s*(::\\s*|REM\\s+)#region",
			"end": "^\\s*(::\\s*|REM\\s+)#endregion"
		}
	}
}
```
- Have following settings
```json
"editor.autoClosingBrackets": "languageDefined",
"editor.autoClosingQuotes": "languageDefined",
"editor.autoWrapping": "brackets"
```
- Open a new document with language having above configuration
- Type some text and select the text and type `{`
Expected: Text should not be auto surrounded as no surrounds pairs are configured
Observed: Text is auto surrounded by `{`

**Comment by alexandrudima** [comment]
We should treat `"surroundingPairs": []` different than the key missing. The fact that we have it and it is empty indicates that no surrounding pairs should be available in this language.
