### ISSUE TITLE
Auto wrapping quotes does not auto surround the text with quotes

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#57417]
Testing #57317

- Have following surrounded pairs configuration
```json
{
	
	"surroundingPairs": [
		["{", "}"],
		["[", "]"],
		["(", ")"],
		["`", "`"]
	]
	
}
```
- Have following settings
```json
"editor.autoWrapping": "quotes"
```
- Open a new document with language having above configuration
- Type some text and select the text and type `"`
Expected: Text should be auto surrounded by `"`. But not.

**Comment by octref** [comment]
I have the same issue. I had the expectation that `quotes` and `brackets` would be two lists of symbols that get auto wrapping. What they really are are `quotes` and `brackets` in the `surrondingPairs` of a language configuration file.

**Comment by alexandrudima** [comment]
The `surroundingPairs` are still defined by a language configuration. In this case, the language configures `{}`, `[]`, `()` and ` `` ` as surrounding pairs. That means that someone looked at the syntax of the language and in this language, ` "" ` and ` '' ` are not used.

The user facing setting will use the set provided by the language configuration. i.e. if in this language, ` "" ` and ` '' ` are meaningful from a syntactical point of view, then you should file an issue to the language author to include them in there.
