### ISSUE TITLE
Editor crashes/freezes when Search string is too large 

### ISSUE THREAD

**Issue by actraiser** [microsoft/vscode#57416]
No major issue but I just pasted a large json string (40000 Lines)  by accident into the Find-InputField (STRG-F). The editor would instantly freeze and I had to restart VS Code. Maybe you can introduce some sanity check to avoid this problem.

- VSCode Version: 1.26.1
- OS Version: OSX 10.13.6

Steps to Reproduce:

1. Press STRG-F
2. Paste a very large string into the Input field

Greets
-act

**Comment by alexandrudima** [comment]
I think this happens with any of our `<input>` fields, e.g.

quick open, find input, replace input, search in files input etc.
