### ISSUE TITLE
Add isVisible to OutputChannel

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode#57410]
Would it be possible to add an **isVisible** flag to OutputChannel objects, similar to the TreeView ? 

Already having 'show' and 'hide' functions, it would seem sensible to know if the channel is actually visible or not. 

I have a use case where if the user has hidden the output channel, I would just like to pop up a notification rather than reveal the output channel. I don't want to keep showing the output channel if the user has decided to hide it.

**Comment by Gruntfuggly** [comment]
I've found a workaround for this - I now store the open editors when onDidChangeVisibleTextEditors, which includes the output channels. Feels a bit silly having to store the state in the extension, but it works at least.

**Comment by sandy081** [comment]
Closing this as user has a workaround and no other user is requiring this.

**Comment by starball5** [comment]
Interesting workaround, given @jrieken's comment in #106993.
