### ISSUE TITLE
editor.autoWrapping setting should have value `languageDefined` instead of `always`

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#57415]
Testing #57317

`editor.autoWrapping` setting has value `always`, this is ambiguous that the auto surround happens always for all characters?. Actually this happens only for configured surrounding pair characters. So, I think it makes sense to rename `always` value to `languageDefined`

**Comment by octref** [comment]
Agreed. And to avoid confusion, in the docs it should refer to the specific fields in `language-configuration.json`.
- In the `languageDefined` for `editor.autoWrapping`, `surrondingPairs` should be mentioned
- In the `languageDefined` for `editor.autoClosingBrackets` and `editor.autoClosingQuotes`, `autoClosingPairs` should be mentioned.

**Comment by octref** [comment]
@alexandrudima `languageDefined` is missing documentation. I just pushed a fix since it's a pretty minor change.
