### ISSUE TITLE
HTML find replace deletes closing attribute quote

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#57420]
Issue Type: <b>Bug</b>

I am replacing classes in a project. 

I search for 
`nc-icon-mini tech_print-round` which would appear in `<i class="nc-icon-mini tech_print-round"></i>`

replace with
`pbi-icon-mini pbi-printer`

It finds in 4 files, click replace all.  At least one of the replaced files now has an error, the closing quote has been deleted:
`<i class="pbi-icon-mini pbi-printer></i>`

This never happened before this verison.

VS Code version: Code - Insiders 1.27.0-insider (f881f8c4229863782a01eae80d70b4d6d540e39d, 2018-08-28T09:47:27.146Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.42GB free)|
|Process Argv|/Users/st016lo/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_18227553|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|1.2.6
Bookmarks|ale|9.0.3
project-manager|ale|8.0.0
bracket-pair-colorizer|Coe|1.0.59
vscode-eslint|dba|1.5.0
tslint|eg2|1.0.38
vscode-great-icons|emm|2.1.41
prettier-vscode|esb|1.6.1
path-autocomplete|ion|1.12.0
svg|joc|0.1.1
ecdc|mit|0.12.0
HTMLHint|mka|0.5.0
theme-monokai-pro-vscode|mon|1.1.8
vscode-scss|mrm|0.6.2
vscode-stylefmt|mrm|2.5.0
debugger-for-chrome|msj|4.8.2
angular2-inline|nat|0.0.17
incrementor|nms|0.1.0
vscode-versionlens|pfl|0.21.1
quicktype|qui|12.0.40
code-settings-sync|Sha|3.1.0
stylelint|shi|0.42.0
rewrap|stk|1.9.1
sort-lines|Tyr|1.7.0
vscode-terminal-here|Tyr|0.1.1
change-case|wma|1.0.0

(2 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment]
I think this is about find in files, not find within a file.

**Comment by smlombardi** [comment]
@alexandrudima Yes

**Comment by craggy2593** [comment]
Experienced the same issue. The find is selecting an additional character (see screenshot). 

In searching for `()=`, it is highlighting `()=>` (this is definitely after submitting the search), which is causing the additional character to be changed in the replace.
<img width="871" alt="screen shot 2018-08-29 at 14 58 30" src="https://user-images.githubusercontent.com/1264223/44792843-b71a4480-ab9c-11e8-9ac3-497a282adf77.png">

Insiders 1.27.0-insider ([47d0584](https://github.com/Microsoft/vscode/commit/47d0584301d16d4efd6618f6f33ef14099c92561) 2018-08-29T05:05:36.428Z)

**Comment by roblourens** [comment]
I think this was https://github.com/Microsoft/vscode/issues/57303. Please try in today's insiders and let me know if you see it again.
