### ISSUE TITLE
macOS native tabs: duplicate actions for tabs management showing up

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#57421]
related to https://github.com/Microsoft/vscode/issues/25919

* enabled native window tabs
* restart vs code (with just a single window)
* the window menu shows most tab specific action twice (once with managed enablement state and once without)

<img width="438" alt="screen shot 2018-08-28 at 15 43 20" src="https://user-images.githubusercontent.com/1794099/44727279-f6339180-aad9-11e8-8b88-cfb411bc6498.png">

**Comment by bpasero** [comment]
Wtf, I cannot reproduce running out of sources...

**Comment by jrieken** [comment]
🤯

**Comment by bpasero** [comment]
I am seeing this again for a reason I do not know. Looks like an electron issue to me that I cannot workaround.
