### ISSUE TITLE
setting.json error 

### ISSUE THREAD

**Issue by dwsong07** [Microsoft/vscode#57425]
- VSCode Version: 1.26.1
- OS Version: Windows 10 Version 1803

Opening setting.json will prompt the problem window to "Property detected".

Does this issue occur when all extensions are disabled?: Yes

**Comment by dbaeumer** [comment]
I can't reproduce this. Can you provide a screen shots that shows this?

**Comment by dwsong07** [comment]
![vscode_error](https://user-images.githubusercontent.com/27623326/44789284-27de5280-abd7-11e8-8912-1779142549c6.PNG)

**Comment by aeschli** [comment]
In JSON, after a comma, either a property or an array item is expected. This looks correct to me.
Maybe paste a more complete, small, example?
