### ISSUE TITLE
Reload file?

### ISSUE THREAD

**Issue by GandalfSaxe** [Microsoft/vscode#57423]
In many other editors, when I file changes from an external change, the file either auto reloads, or a pop-up window informs the user that the file has changed and ask if it should reload. However in VSCode nothing happens. I often find myself having to close the file and open it again.

Couldn't VSCode also ask if the user wants the file to be reloaded (making it non-dirty) or keep it as is (keeping it dirty)?

**Comment by bpasero** [comment]
@GandalfSaxe we do have a file watcher in place that will just reload the file automatically, unless it is dirty. File > Revert will also take the latest contents from disk. Could it be a file watching issue on your end?

**Comment by GandalfSaxe** [comment]
Hmm ok. I'll try to keep an eye open for under which conditions it happens.

**Comment by bpasero** [comment]
Ok

**Comment by GandalfSaxe** [comment]
For simplicity I’ll close the issue and then we can reopen if I can provide more clarity.

**Comment by GandalfSaxe** [comment]
@bpasero Ok so it happens for me especially when I use an external git client to discard changes sometimes.

Is it by design that it will maintain the contents against any changes made externally? In SublimeText you instead get a pop-up that says something like:

> The file has changed, do you want to reload?

The advantage of that is that you almost always want to reload the file with changes made externally so that becomes really easy, whereas in VSCode you have to take an action actively (File -> Revert). Is that a feature? Could it be considered to have a popup asking for revert/reload like ST?
