### ISSUE TITLE
ctrl+shift+a and ctrl+shift+e don't work in macOS

### ISSUE THREAD

**Issue by wbobeirne** [microsoft/vscode#57429]
- VSCode Version: 1.24.1
- OS Version: 10.13.2

Steps to Reproduce:

1. Open file in vscode macOS
2. Place yourself on any given line
3. Use the key command `ctrl+shift+[e|a]`, observe nothing happens
4. Go to any other text editor or text field on the operating system
5. Attempt the same command, observe that it highlights everything to the left / right of the cursor respectively

Does this issue occur when all extensions are disabled?: Yes

---

Visual Studio Code seems to maintain the emacs-like behavior built into OSX of going to beginning and  end of line with `ctrl+e` and `ctrl+a` respectively. However, when throwing the shift key into the mix, it doesn't work. I'd assumed this was due to a conflicting key command, but couldn't find anything mapped to this, and those keys don't seem to trigger anything.

I'm sure this is a niche command, but I find myself using it quite often, and it's a killer when trying to use vscode.

**Comment by limouren** [comment]
I can confirm Ctrl+Shift+E doesn't work as described under macOS Mojave 10.14.4 with Code 1.33.1 (1.33.1) with `--disable-extensions`.
