### ISSUE TITLE
Search results ellipsis only applies to end of results

### ISSUE THREAD

**Issue by Gruntfuggly** [Microsoft/vscode#57436]
The search results seem to use an algorithm to reduce the context of the result displayed in the tree, however sometimes I find that the width of the tree is still not enough to display the context and the result is truncated with an elipsis:

![image](https://user-images.githubusercontent.com/376658/44735151-87f3cc80-aae3-11e8-8a6a-9c5226277c40.png)

Note - sometimes the highlight is not even displayed because it is beyond the truncation.

Is it possible to truncate the start of the result aswell as the end, to try and keep the highlight within the view? 

I assume it's just using the standard CSS `text-overflow: ellipsis` at the moment, so I doubt it's a simple change, but I thought it might be worth asking.

**Comment by roblourens** [comment]
Yeah it's not straightforward, and I'm worried about the ellipsis taking up valuable screen real estate in a narrow search viewlet, but it's worth considering.

**Comment by roblourens** [comment]
Not sure what to do here. And the sidebar itself isn't supposed to be the best place to see everything about a search result. The user should open it in the editor for that.
