### ISSUE TITLE
Breadcrumb menu is often too large

### ISSUE THREAD

**Issue by misolori** [Microsoft/vscode#57437]
I've noticed in several places that the breadcrumb menu grows to a really large size that's often unnecessary. The menu should grow depending on the context, like the quick pick. We should set min/max widths and let the menu grow responsively.

![image](https://user-images.githubusercontent.com/35271042/44735812-5870a000-aaa2-11e8-9c43-880e2d10e1ee.png)

![image](https://user-images.githubusercontent.com/35271042/44735893-8c4bc580-aaa2-11e8-8060-3ec9dcc17e71.png)

So something closer to this:

![image](https://user-images.githubusercontent.com/35271042/44736148-50653000-aaa3-11e8-892f-0e957a87a3e5.png)

**Comment by jrieken** [comment]
Yeah, we see if we can grow the height. It is a little challenging because often we don't know the elements up front...

**Comment by jrieken** [comment]
![sep-07-2018 14-55-54](https://user-images.githubusercontent.com/1794099/45220367-30f1b280-b2ae-11e8-9da9-37c25c1723b2.gif)


The picker now adjusts its height with the number of elements it shows but doesn't grow further than 15 visible elements. Also, the height readjusts when filtering is happening

**Comment by nealot** [comment]
@jrieken I think the usability of breadcrumbs has regressed after this commit since it doesn't account for a situation with 1 top-level folder and multiple sub-files:
![screenshot_20180910_034505](https://user-images.githubusercontent.com/36805289/45283456-ec336a80-b4ab-11e8-94bc-7420e9cc7e4e.png)

What should happen with the file structure below? Perhaps breadcrumbs should adjust the height only after the minimum height has been exceeded?
```
folder1/
  folder2/
  file1
  file2
  file3
```

**Comment by jrieken** [comment]
Hm, good point @nealot. I was only looking at outline element (of which we always show all) I will make another change to ensure there is enough space

**Comment by jrieken** [comment]
@nealot Pushed another change that update the height when item expand/collpase

![sep-10-2018 10-25-57](https://user-images.githubusercontent.com/1794099/45285659-01c48680-b4e4-11e8-8303-56fcf38039bf.gif)

**Comment by nealot** [comment]
Can there be an option to set the min and max number of elements?

**Comment by jrieken** [comment]
Not sure... I went with how quick outline behaves, it doesn't add padding but has a max height only
