### ISSUE TITLE
Consolidate file opening across workbench trees and lists

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#57432]
There should be a common component which handles opening files which would take care of:
* double click to pin
* double click to pass focus
* alt + click to open to the side
* middle click to pin

e.g. have some kind of IListOpenListener that would fire with the right set of instructions
fyi @bpasero

**Comment by bpasero** [comment]
Yeah 🌮

**Comment by isidorn** [comment]
@joaomoreno did this. Thus closing
