### ISSUE TITLE
New dropdown control should not show enumDescription preview for files.encoding

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#57434]
![image](https://user-images.githubusercontent.com/323878/44733410-658a9080-aa9c-11e8-8ded-6d5297340257.png)

**Comment by cleidigh** [comment]
@roblourens 
I think this is a the same thing I just posted  #57447 having to do with problematic margin calculations with the new added descriptions.  Sound correct?

**Comment by roblourens** [comment]
`files.encoding` thing was fixed somewhere else.
