### ISSUE TITLE
Suggestions for other file types returned in css path completions

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#57446]
Issue Type: <b>Bug</b>

Testing https://github.com/Microsoft/vscode/issues/57309

I expected the completions to only be `.css` files, but this didn't seem to be the case:

![css_import](https://user-images.githubusercontent.com/3672607/44743497-8a403180-aab7-11e8-97a5-5d6f3058b096.gif)

VS Code version: Code - Insiders 1.27.0-insider (387c79f8de26cec749415bf400b6e2e99f2e8f14, 2018-08-28T13:04:31.269Z)
OS version: Darwin x64 17.7.0

**Comment by octref** [comment]
https://github.com/Microsoft/vscode/issues/57388#issuecomment-416775095

Welcome to the world of webpack/parcel :)

Yes, you can import JSON files, font files or any files (even gif/videos) in a CSS/JS file, as long as you setup a loader for it. I know this sounds crazy, but people do that.
