### ISSUE TITLE
Activity Bar seems to be trying to load icons for extensions that it shouldn't

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode#57441]
Even with extensions disabled, I am seeing the activity bar attempt to add the gitlens icon to the viewlet. It seems to be coming from the cached info in the user data dir. This is breaking layout for me. Here are some screenshots of dev tools:

![image](https://user-images.githubusercontent.com/6561887/44739910-f027bb80-aaad-11e8-96a5-30d8a3612174.png)

![image](https://user-images.githubusercontent.com/6561887/44739943-05044f00-aaae-11e8-9e44-d65fbd79e5c3.png)

**Comment by sandy081** [comment]
Fixed.
