### ISSUE TITLE
SCSS partials are completed with underscore

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#57449]
Issue Type: <b>Bug</b>

Testing https://github.com/Microsoft/vscode/issues/57309

I'm seeing the completion resolve to the filename with an underscore:
![scss_partial_completion](https://user-images.githubusercontent.com/3672607/44744017-e3f52b80-aab8-11e8-9012-3ce411648004.gif)

VS Code version: Code - Insiders 1.27.0-insider (387c79f8de26cec749415bf400b6e2e99f2e8f14, 2018-08-28T13:04:31.269Z)
OS version: Darwin x64 17.7.0

**Comment by octref** [comment]
This is as-designed, as sass compiles that to `@import url("./_partial.scss");` instead of doing file resolution. We only have the special handling when you do `@import` in SCSS without `url()`.
