### ISSUE TITLE
Allow to sort symbols in workspace

### ISSUE THREAD

**Issue by garyking** [microsoft/vscode#57458]
In "Go to symbol in file", we can sort the results with `@:`. But in "Go to symbol in workspace", we can't sort it with `#:`. Please make it possible to do so.

**Comment by dbaeumer** [comment]
@bpasero please reassign if this is not you.

**Comment by zachsiegel-capsida** [comment]
I think this is a good request. I also would appreciate this - for me, "Go to Symbol in Workspace..." is not very usable for this reason.

For what it's worth, I would appreciate settings to choose default sorting method, or even a keyboard shortcut to open the "Go to Symbol in Editor..." (or "...Workspace...") action with the `@:` (or `#:`) pre-filled, maybe the action could be called "Go to Symbol in Editor/Workspace and Sort by Type..."
