### ISSUE TITLE
$ref '/definitions/HProperties' in 'vscode://schemas/settings/user' can not be resolved.

### ISSUE THREAD

**Issue by coder3101** [Microsoft/vscode#57460]
- VSCode Version: 1.26.1
- OS Version: Ubuntu 18.04 LTS

Does this issue occur when all extensions are disabled?: Yes/No : N/A

All of a sudden I am getting this warning on all of my settings.json files. 

```
$ref '/definitions/HProperties' in 'vscode://schemas/settings/user' can not be resolved.
```

This occurs even in latest insider build. Line 1 at **{** in the Settings.json

**Comment by dbaeumer** [comment]
@aeschli @roblourens not sure who owns this.

**Comment by Hussien77** [comment]
The same problem I have. Wish Vscode's team releases urgent upating to solve this bug :)

**Comment by MathSSDev** [comment]
Getting the same problem on user settings and workspace settings. I'm trying to add a files.watcherExclude: { ... }

**Comment by aeschli** [comment]
@coder3101 Can you run with extensions disabled? This is likely an extension that contributes an invalid setting definition.

**Comment by aeschli** [comment]
It's caused by HookyQR/VSCodeBeautify:

https://github.com/HookyQR/VSCodeBeautify/blob/97790c4da01aad6d5bab8562c0ffdd3ddd16bd7d/package.json#L164

**Comment by aeschli** [comment]
created https://github.com/HookyQR/VSCodeBeautify/issues/266
