### ISSUE TITLE
Show intellisense documentation and parameter hints in a pane

### ISSUE THREAD

**Issue by rben01** [microsoft/vscode#57466]
When typing a word, the Intellisense window contains two sections: the autocomplete section, which has suggestions for the current word, and the documentation section, which contains the documentation for the current selection. Currently they are attached; the documentation selection appears immediately to the right of the Intellisense window and is roughly the same size. This is less than ideal for three reasons: 

1. Documentation is often long, and the documentation section of the Intellisense window is often not big enough (neither tall enough nor wide enough) to contain a useful portion of the documentation without the user having to scroll.
2. The documentation section is often unnecessary — especially while quickly moving through items in the autocomplete section, but also if you happen to be familiar with the API you're working with — and yet it takes up a sizable portion of the editor window and is placed immediately next to the cursor.
3. Since it's a part of the Intellisense window, it moves as you type, which makes reading it difficult while typing.

<img width="762" alt="image" src="https://user-images.githubusercontent.com/766670/44758555-b29d4f80-aafa-11e8-8836-917fd0d2fe50.png">

Ideally it would be possible to have documentation pop up in a separate location altogether, perhaps a pane in the panel, emulating the behavior of Emacs (at least how I've set it up; see screenshot).

<img width="852" alt="image" src="https://user-images.githubusercontent.com/766670/44758757-ce552580-aafb-11e8-806a-bc0eaea85f41.png">

Here, the documentation both has more space, making it more readable; isn't as intrusive/attention grabbing, making it more easily ignorable if you don't need it; and is stationary/doesn't move with the cursor, which makes it easier to read (albeit farther from the cursor) when you do want to look at it.

Furthermore, this panel-based documentation window could hold the parameter hints window, which currently also resides in the editor, and hence is covered by the Intellisense window. (That the parameter hint window isn't also tied to the Intellisense window is another issue, but one that would be resolved by moving things into the panel.)

<img width="597" alt="image" src="https://user-images.githubusercontent.com/766670/44759601-b9c75c00-ab00-11e8-95a9-807e8c5ac520.png">

**Comment by dbaeumer** [comment]
@alexandrudima @jrieken FYI.

**Comment by cipri-tom** [comment]
Isn't this the same as #51253 ?
