### ISSUE TITLE
Breadcrumbs: Changing zoom level makes the dropdown move to wrong position

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#57462]
Refs: #57280

OS: MacOS (no zooming)

Changing zoom level makes the dropdown move to wrong position.

![screenflow](https://user-images.githubusercontent.com/173559/44757668-0ef57480-aae5-11e8-8bb8-98b57c5edd86.gif)

**Comment by jrieken** [comment]
Yeah - we should close the panel when zooming happens
