### ISSUE TITLE
[RFC] How about merge VSCode and Atom editor to one editor?

### ISSUE THREAD

**Issue by netroby** [Microsoft/vscode#57467]
I am using Atom editor and VSCode editor. I love you two editors. 
I have a idea. Now Github as a Microsoft company. And VSCode also Microsoft company.
How about Merge two editor into one editor?

The Atom editor development team and VS Code editor development team can working together. Provided us very power editor on earth.
Atom and VSCode both base on Electron platform. 
So i guess it may possible use the same code base?

**Comment by beastdestroyer** [comment]
Microsoft has already said they will maintain Atom as it's own independent editor from VSCode, there are no plans to currently merge them too.

**Comment by egamma** [comment]
Pls see https://github.com/Microsoft/vscode/issues/57467#issuecomment-416843517, closing this issue.
