### ISSUE TITLE
"wating for debugger to disconnect

### ISSUE THREAD

**Issue by miberg81** [Microsoft/vscode#57479]
Issue Type: <b>Bug</b>

Randomely accurs.  Can't really understand why the issue is comimg. Sometimes adding new debugger will solve it and sometimes it doesnt.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3 CPU       M 350  @ 2.27GHz (4 x 2261)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.86GB (2.56GB free)|
|Process Argv|C:\Users\berge\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|50%|

</details>Extensions: none

**Comment by isidorn** [comment]
Can you please file this issue with exact reproducable steps.
Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/

**Comment by miberg81** [comment]
No! I cant. It simply happens again and again

**Comment by isidorn** [comment]
If you can not reproduce with insiders than it should be fixed in new stable soon.
