### ISSUE TITLE
Settings editor doesn't show the correct target when persisted open

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#57470]
- Open settings editor
- Select workspace settings
- Reload window
- User Settings is selected but workspace settings are shown

**Comment by chrmarti** [comment]
Still an issue in:
VS Code version: Code - Insiders 1.27.0-insider (051da84e0f85ec291fd2479b665f5c5c2c60ef72, 2018-08-30T07:25:39.746Z)
OS version: Darwin x64 17.7.0

![aug-30-2018 15-57-52](https://user-images.githubusercontent.com/9205389/44856402-97068600-ac6d-11e8-8bd3-e188a2e1357d.gif)
