### ISSUE TITLE
Test virtual document links

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#5747]
* [x] any os @bpasero 
* [x] any os @kieferrm 

#3676, make sure links in virtual document. Test that:

* you link to a document on disk, e.g `file:///Users/far/b.oo`
* you link to a virtual document, e.g. `virtual:some/path`
* you can jump to a line using the `#L32` notion, `file:///Users/far/b.oo#L42`
* you can invoke a command using using the command scheme and the command as path, like so `command:deleteLeft`
* you can invoke a command with arguments by adding a JSON-array of them as query

**Comment by bpasero** [comment]
@jrieken can you give an example for how a link needs to look like if you want to execute a command?

**Comment by bpasero** [comment]
Nevermind, found it! E.g. "a href='command:workbench.action.zoomIn'"
