### ISSUE TITLE
LSP stream inspector: weird scroll behaviour

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#57473]
Refs: https://github.com/Microsoft/vscode/issues/57310

Make sure that the LSP inspector page has a scroll bar and bring up the streaming example, you will notice that the page scrolls down automatically when the inspector output starts to scroll.

Might be a general webview issue (@mjbvz)

![grid-tw](https://user-images.githubusercontent.com/900690/44771865-8cb09300-ab6c-11e8-9d56-9fe56ff96237.gif)

**Comment by octref** [comment]
Fixed via https://github.com/Microsoft/language-server-protocol-inspector/commit/8a4b9560b128f83b4122284560e9df961528d55b
