### ISSUE TITLE
Not Expand/Collapsible  multi line comments

### ISSUE THREAD

**Issue by shaishab** [Microsoft/vscode#57477]
Currently unable to expand or collapse for multiline comments (for documentation). It would be better if we could that. 

![image](https://user-images.githubusercontent.com/3139652/44772337-60f2d480-ab8f-11e8-86b2-0005180c77fd.png)

**Comment by mjbvz** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/22732
