### ISSUE TITLE
Hotkey issue for Russian and Bulgarian Language pack

### ISSUE THREAD

**Issue by janbaltus** [Microsoft/vscode#57476]
- VSCode Version:1.27.1
- OS Version:

Steps to Reproduce:

1. File menu with Hotkey for Bulgarian and Russian language contain visible && in translation and Hotkey is not working. All other languages do not have this issue. There is no issue in translation string list.

![obrazek](https://user-images.githubusercontent.com/18324209/44772297-c33add80-ab6d-11e8-9527-af3ad4c60e5e.png)

![obrazek](https://user-images.githubusercontent.com/18324209/44772383-f9785d00-ab6d-11e8-9ce7-f8f181edfb5a.png)

2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by dbaeumer** [comment]
This seems to happen with the custom menu bar.

Assignig to @sbatten 

@bpasero FYI. Not sure if this is something that might be Electron related.

**Comment by bpasero** [comment]
Maybe related to https://github.com/Microsoft/vscode/commit/2c9408fecfc0507e78e1ac008e220d433cfef295 ?

**Comment by sbatten** [comment]
I reverted to using . instead of \w. which seems to work for underlining. Please verify that they can be triggered with a Russian or Bulgarian layout. No VMs setup while traveling.
