### ISSUE TITLE
Visual Studio Code Font

### ISSUE THREAD

**Issue by zhangxuan1340** [microsoft/vscode#57471]
Issue Type: <b>Feature Request</b>

系统整体字体界面非常糟糕，尤其超过1080后的分辨率

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

**Comment by beastdestroyer** [comment]
For a quick translation, they're saying that the font size of VSCode is very small and not good when on screen sizes larger than 1080p resolution

**Comment by dbaeumer** [comment]
You can control the font size of the editor with the following setting: `"editor.fontSize"`

**Comment by bpasero** [comment]
@zhangxuan1340 where? menus?

**Comment by beastdestroyer** [comment]
@bpasero Yh he was talking about user interface font, not editor font, forgot to mention that

**Comment by dmlemos** [comment]
Would be cool to have an option to change the size of the editor font
