### ISSUE TITLE
documentChanges isn't a good name for file management 

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#57484]
re #57276

The `documentChanges` property is slight misleading. It put things in the context of documents but it's (also) about file changes, like renaming a folder.

**Comment by dbaeumer** [comment]
Agree, but we had that one and adding another one makes it problematic to have a fixed order. Otherwise we would have needed to break and I though it is not worth it.

Objections to close?

@aeschli any ideas / comments

**Comment by jrieken** [comment]
Yeah, see https://github.com/Microsoft/vscode/issues/57485 - I would remove `changes` all together

**Comment by dbaeumer** [comment]
Agree, but that is breaking from a spec perspective. We can only do this in 4.0.

**Comment by dbaeumer** [comment]
Actually I created https://github.com/Microsoft/language-server-protocol/issues/562 since this has to change in the protocol.
