### ISSUE TITLE
labels for remote resources look like local labels

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#57489]
- install the remotehub extension
- launch `code-insiders --folder-uri remotehub://github.com/Microsoft/vscode`
- open an editor on a file in that folder

- explorer title no longer indicated that the folder is from a remote URL
- hover on files only show `/Microsoft/vscode/src/cli.js`
- recent menu entry looks like a local path
![image](https://user-images.githubusercontent.com/6461412/44779997-2eda7600-ab81-11e8-9fdd-2e8b22709787.png)

**Comment by isidorn** [comment]
* In order for the title to show that the folder is a remote URL the remotehub extension would have to register a labelProvider. However we currently do not support that through `package.json`. 
To tackle this I have changed that by default we show a workspace suffix which is the scheme unless somebody registers a custom suffix. And I also changed the file scheme to register an empty suffix (to not show `file`)
This seems to work just fine and does not feel like a hack as it was before.

As for the file hover I am not sure what you would expect and in case something is still missing there please create a new issue. Thank you

**Comment by octref** [comment]
@isidorn I'll reopen this because of the `(file)` issue that Ramya brought up and you planning to revert the change. I would suggest moving this to September.

**Comment by isidorn** [comment]
Pushed fix 10 minutes ago

**Comment by isidorn** [comment]
To verify:
1. Open vscode mulitple times on a local resource and make sure (file) is not shown in the brackets (for instance in the open recent list)
2. Open vscode on a remote resource (for instance remotehub), make sure that (remotehub) is shown in brackets

**Comment by bpasero** [comment]
Seems to work. The label is a bit weird:

![image](https://user-images.githubusercontent.com/900690/44906550-84e02280-ad15-11e8-944e-da05e58f4998.png)

Maybe `remotehub` should somehow be a prefix rather than show up at the end. I think something like `remotehub://<path>` (without backslash) would maybe make it look more like a URL and then people make the connection to remote.
