### ISSUE TITLE
内存占用过高

### ISSUE THREAD

**Issue by hjh302** [Microsoft/vscode#57487]
Issue Type: <b>Bug</b>

win10 vscode内存占用过高比浏览器占用的内存还要高

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (3.01GB free)|
|Process Argv|D:\软件\学习软件\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-javascript-snippet-pack|aka|0.1.5
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.59
vscode-eslint|dba|1.5.0
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.2.0
php-debug|fel|1.12.5
php-intellisense|fel|2.3.4
php-pack|fel|1.0.2
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.4
beautify|Hoo|1.4.2
vscode-gutter-preview|kis|0.13.1
vscode-language-pack-zh-hans|MS-|1.26.3
open-in-browser|tec|2.0.0

</details>

**Comment by dbaeumer** [comment]
@hjh302 can you please provide the description in English.

**Comment by beastdestroyer** [comment]
@dbaeumer They are saying that memory (RAM) usage is too high

**Comment by hjh302** [comment]
The vscode memory footprint of win10 is up to 700M
发送自 Windows 10 版邮件应用

发件人: Progracientist
发送时间: 2018年8月29日 18:02
收件人: Microsoft/vscode
抄送: hjh302; Mention
主题: Re: [Microsoft/vscode] 内存占用过高 (#57487)

@dbaeumer They are saying that memory (RAM) usage is too high

**Comment by dbaeumer** [comment]
@hjh302 The memory usage highly depends on the work you do, especially the language you program in. Can you please execute Help > `Open Process Explorer` and provide a screen shot here so that we can see which service consumes the memory.

**Comment by hjh302** [comment]
• Thank you for helping me out.

发送自 Windows 10 版邮件应用

发件人: Dirk Bäumer
发送时间: 2018年8月29日 20:43
收件人: Microsoft/vscode
抄送: hjh302; Mention
主题: Re: [Microsoft/vscode] 内存占用过高 (#57487)

@hjh302 The memory usage highly depends on the work you do, especially the language you program in. Can you please execute Help > Open Process Explorer and provide a screen shot here so that we can see which service consumes the memory.

**Comment by dbaeumer** [comment]
@hjh302 can you please provide the requested information.

**Comment by hjh302** [comment]
发送自 Windows 10 版邮件应用

发件人: Dirk Bäumer
发送时间: 2018年8月29日 21:57
收件人: Microsoft/vscode
抄送: hjh302; Mention
主题: Re: [Microsoft/vscode] 内存占用过高 (#57487)

@hjh302 can you please provide the requested information.

**Comment by byyxx128** [comment]
@hjh302 哥们，别老回复邮件了，他们不是给你发的邮件……你直接上 GitHub 上来看你的 issue。
给你个地址直接点开看。https://github.com/Microsoft/vscode/issues/57487
因为你直接回复邮件格式很乱，中英文夹杂我都看不明白，别说这些老外了……另外他们让你提供资源占用的数据，你截个图发上来，直接用 GitHub 特别方便。
***
✨**You guys needn't translate what I said above, because it's just what I explained to the author in Chinese.**

**Comment by hjh302** [comment]
Ok, thank you

**Comment by hjhyh** [comment]
![2](https://user-images.githubusercontent.com/41568503/44837312-dc29b880-ac6b-11e8-9db1-9fb7356164b1.PNG)

**Comment by hjh302** [comment]
https://user-images.githubusercontent.com/41568503/44837312-dc29b880-ac6b-11e8-9db1-9fb7356164b1.PNG

**Comment by hjhyh** [comment]
Thanks, solution!

**Comment by dbaeumer** [comment]
Closing the issue then.
