### ISSUE TITLE
git support: there is no active source control providers

### ISSUE THREAD

**Issue by muhammadsaud-10p** [Microsoft/vscode#57480]
**_This issue does not occur if you clone repo using vs code command palette._**

- VSCode Version: 1.26
- OS Version: ubuntu 16.4 

Steps to Reproduce:

1.  clone git repo using terminal
2.  open folder in vs code
3.  Press ctrl+shift+G, _it says there is no active source control providers_

setting "git.path" in user setting does not fix issue

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
If you open the terminal in VS Code and type `git status`, what's the result?
