### ISSUE TITLE
New settings editor - hidden selection color

### ISSUE THREAD

**Issue by sguillia** [Microsoft/vscode#57482]
Issue Type: <b>Bug</b>

The _Search settings_ field inside the new settings editor has no text selection color, or it is the same as the fields background.

When text is selected, one cannot see it.

Also, when pasting something in the middle of the text, the cursor goes all to the right.

Here is a screen recording of the problem
![project-settings-editor](https://user-images.githubusercontent.com/15984272/44776529-94763480-ab78-11e8-80de-52532dfc7ee2.gif)

I'm pressing Ctrl+X and Ctrl+V to cut/paste.

This issue is related to this comment: https://github.com/Microsoft/vscode/issues/50249#issuecomment-415794630. Initially I was thinking that selection did not work. It works, but no color appears.

VS Code version: Code - Insiders 1.27.0-insider (47d0584301d16d4efd6618f6f33ef14099c92561, 2018-08-29T05:18:47.523Z)
OS version: Windows_NT x64 10.0.15063

**Comment by roblourens** [comment]
This is probably from your theme, which theme are you using?

**Comment by roblourens** [comment]
Maybe same as https://github.com/Microsoft/vscode/issues/57281

**Comment by sguillia** [comment]
The two issues are probably the same.

The extensions search bar has the same problem.

Looks like it is the theme indeed. I am using [molokai](https://github.com/nonylene/vscode-dark-molokai-theme).

Should I open an issue in the theme's repository instead?

**Comment by roblourens** [comment]
No, I think we are not respecting the theme color correctly.
