### ISSUE TITLE
Remove WorkspaceEdit#changes

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#57485]
re #57276

There is now `changes` and `documentChanges` - the doc says the latter overrules the former. That makes me wonder why `changes` still exists? For instance, when I create a file (via `CreateFile`) I must also use `TextDocumentEdit` for textual changes etc.

**Comment by dbaeumer** [comment]
`changes` still exists for backwards compatibility. We would need to break to remove it. The current client / protocol still supports servers which send `changes` and not `documentChanges`. 

We can remove it in a `4.0` version of the protocol.

**Comment by jrieken** [comment]
> We would need to break to remove it

Yeah, break it if you can. Or overload it - when it's an object i'ts the old thing when it's an array it's the new thing.

**Comment by dbaeumer** [comment]
Yes, but in the past the C# and Java guys pushed back hard on `|` types. But they both found a solution for it. So I will keep this in mind.
