### ISSUE TITLE
[Snippsets] Remove snippet file (or/& as item in context menu).

### ISSUE THREAD

**Issue by Mlocik97-issues** [Microsoft/vscode#57496]
Now when I create new snippset, and after I want remove, I can remove only snippet, but empty snippsets file will remain. If I want remove this file to remove item from context menu (F1 - > Preferences: Configure User Snippset, there are empty file marked as Existing Snippet), so to remove it I need remove file from %appdata%/code/user/snippets/[language].json ... is there way how to remove it directly? If not, Can you add this?

(sry for my bad English)

**Comment by jrieken** [comment]
The easiest is to right click the editor title and select 'Reveal in Finder' or 'Reveal in Explorer' and then delete it from there. I have also created https://github.com/Microsoft/vscode/issues/57497 which is about being able to delete a file from the open editors view.

<img width="479" alt="screen shot 2018-08-29 at 13 54 41" src="https://user-images.githubusercontent.com/1794099/44786138-77029400-ab93-11e8-884c-157717951438.png">
