### ISSUE TITLE
apply file.exclude rules to reference search and go to declaration

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#5749]
As discusses here #5740, we should consider to honour the exclude settings for files in the reference search window, in go to declaration, and likely other places

**Comment by jrieken** [comment]
@alexandrudima this could help to avoid confusion with the addition of `monaco-editor.d.ts`

**Comment by ramya-rao-a** [comment]
Would excluding the said patterns be the responsibility of the language server or the core VS Code product?

As in will the extensions do the excluding before returning data to VS Code or will VS Code do the excluding after getting the data from the extensions?

**Comment by jrieken** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
