### ISSUE TITLE
Retrieve Package option is not visible from ForceCode Menu in Visual Studio Code

### ISSUE THREAD

**Issue by BindiyaGowri** [Microsoft/vscode#57494]
"Retrieve Package\Metadata" and its sub-options (Retrieve package by package.xml and Get All files from Org) are not visible

![image](https://user-images.githubusercontent.com/22540621/44784808-732f3b80-abac-11e8-8116-8bbc44247d6b.png)

**Comment by dbaeumer** [comment]
Please file the issue against the creator for ForceCode.
