### ISSUE TITLE
New Style Menu Buttons Don't Work

### ISSUE THREAD

**Issue by ds64** [Microsoft/vscode#57499]
Issue Type: <b>Bug</b>

Occasionally pressing buttons (e.g. File, Edit, etc.) doesn't work.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz (4 x 3696)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (7.12GB free)|
|Process Argv|C:\Users\anbo0717\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
soy|ant|0.0.1
beautify|Hoo|1.4.2
svn-scm|joh|1.33.0
csharp|ms-|1.15.2
debugger-for-chrome|msj|4.9.0
java|red|0.29.0
vscode-java-debug|vsc|0.12.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.8.0
vscode-maven|vsc|0.10.0

</details>

**Comment by sbatten** [comment]
@ds64 do you have any idea on what steps to take to get into a repro-able state?
