### ISSUE TITLE
Scroll bars should be added to the drop-down menu in the menu bar

### ISSUE THREAD

**Issue by zwuis** [Microsoft/vscode#57498]
Issue Type: <b>Feature Request</b>

Zoom in many times (such as 5).
Then click on the menu bar.
The lower half of the drop-down menu is not visible.

So a scroll bar should be added to the drop-down.

VS Code version: Code - Insiders 1.27.0-insider (47d0584301d16d4efd6618f6f33ef14099c92561, 2018-08-29T05:21:26.483Z)
OS version: Windows_NT ia32 10.0.17134

**Comment by zwuis** [comment]
I mean this:
![in this photo](https://github.com/zwuis/Hello-world/blob/master/..jpg)
(sry for my poor English before)

**Comment by sbatten** [comment]
duplicate of #52533
