### ISSUE TITLE
Disable breadcrumbs keybinding in preview editors

### ISSUE THREAD

**Issue by nealot** [Microsoft/vscode#57490]
Steps to reproduce:

1. Open markdown preview
2. Press `ctrl+shift+.`
3. Examine odd breadcrumbs behavior

The associated keybindings should be disabled for preview editors. Otherwise, the menu will open in the top left corner and you can't ESC to escape.

**Comment by mjbvz** [comment]
I can't repo this. Is the markdown preview focused when you press the keyboard shortcut? Please provide a screen shot of the odd behavior you are seeing

**Comment by nealot** [comment]
![screenshot_20180904_153952](https://user-images.githubusercontent.com/36805289/45053704-c7c53180-b058-11e8-9b60-02ac3b0230d6.png)

You have to make sure breadcrumbs are already enabled otherwise it doesn't work.

**Comment by mjbvz** [comment]
Thanks. I can repo now. Steps:

1. Open a markdown file
1. Open the markdown preview **in the same group** as the markdown file
1. Press `cmd+shift+.`
