### ISSUE TITLE
Let filtered settings behave the same as unfiltered

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#57504]
Issue Type: <b>Bug</b>

Verifying #57347

I somehow like how, when unfiltered, all settings are shown and the TOC is just used for navigation.

Currently the TOC filters the settings further when there is a filter value, that seems like an unnecessary change in UX compared to the unfiltered settings.

VS Code version: Code - Insiders 1.27.0-insider (47d0584301d16d4efd6618f6f33ef14099c92561, 2018-08-29T05:12:15.247Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 3|
|Memory (System)|16.00GB (1.90GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron --user-data-dir /Users/chrmarti/Development/repos/tmp/user2 --extensions-dir /Users/chrmarti/Development/repos/tmp/ext2|
|Screen Reader|no|
|VM|22%|

</details>Extensions: none

**Comment by roblourens** [comment]
Changed this in https://github.com/Microsoft/vscode/issues/55616 I'll let you and @ramya-rao-a fight it out :D

There is some discussion in that issue, basically we decided that the flat list layout + filtering feels better for a smaller number of settings.

**Comment by roblourens** [comment]
This could be configurable although it might be a pain to implement.

**Comment by chrmarti** [comment]
I think the UX would be easier to understand if it didn't change behavior when there is a filter value. Of the two modes I favor the TOC being for navigation only, that is very much like a website behaves, so it is very familiar.
