### ISSUE TITLE
Make "Modified in" navigable

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#57507]
Issue Type: <b>Feature Request</b>

Testing #57304 

Just a thought: When I see "Modified in: Workspace" I might want to go there and check. I'd keep font and color as they are and add an underline and pointer cursor to "Workspace" on hover.

VS Code version: Code - Insiders 1.27.0-insider (47d0584301d16d4efd6618f6f33ef14099c92561, 2018-08-29T05:12:15.247Z)
OS version: Darwin x64 17.7.0

**Comment by roblourens** [comment]
Good idea!

**Comment by roblourens** [comment]
I would take a PR for this

- "Modified in: Workspace" - the word Workspace is underlined
- When clicked, it switches to the Workspace scope, and copies the setting key into the search bar, so the view is filtered to just that one setting

**Comment by w9jds** [comment]
I'm interested in looking into this if that is alright.
