### ISSUE TITLE
Folding html tags not possible in Markdown

### ISSUE THREAD

**Issue by anton31kah** [Microsoft/vscode#57505]
- VSCode Version: 1.26.1
- OS Version: Windows 10 1803 (Education, if that matters)

Steps to Reproduce:

1. Add an HTML tag to a Markdown file
2. Notice how no folding (collapsing) icon appears

![Example](https://i.imgur.com/3VEo5Kw.jpg)

And this is actually possible with other editors, even Visual Studio supports this, so I thought this must be a bug, or maybe I should change something in the settings (but I don't know what)

Does this issue occur when all extensions are disabled?: Yes

**Comment by cursorial** [comment]
Can reproduce this on OS X 10.12.6 using VS Code 1.25.1

**Comment by cursorial** [comment]
I've had a quick look into this, seems as though this file is the culprit: `vscode/extensions/markdown-language-features/src/features/foldingProvider.ts`

I'd say it's something to do with this little chunk of code (lines 21-25):

    const isStartRegion = (t: string) => /^\s*/.test(t);
    const isEndRegion = (t: string) => /^\s*/.test(t);

    const isRegionMarker = (token: Token) => token.type === 'html_block' &&
        (isStartRegion(token.content) || isEndRegion(token.content));

**Comment by Hindol** [comment]
Additionally, code folding is not supported within code blocks inside Markdown. At least allowing folding at the code block beginning may be desirable?

**Comment by anton31kah** [comment]
I found [this extension](https://marketplace.visualstudio.com/items?itemName=maptz.regionfolder) which does work as intended (it's similar to [SyntaxFold](https://packagecontrol.io/packages/SyntaxFold) for sublime text, it does finish the work although I still believe it should be implemented directly without the need for regions and comments

**Comment by mjbvz** [comment]
@Hindol Folding within embedded language is out of scope. We don't provide intellisense or other language support inside fenced code blocks either. In 1.28 (current insiders builds) you can fold away the entire code block however
