### ISSUE TITLE
screen cheese with peek views

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#5750]
See attached screen shot. I get that every now and then when using reference search.

![screen shot 2016-04-25 at 13 58 17](https://cloud.githubusercontent.com/assets/1794099/14783126/e069f1e8-0aed-11e6-8898-db468ea8c1e1.png)

**Comment by alexandrudima** [comment]
Any steps or could you please ping me when you see it so we can debug.

**Comment by jrieken** [comment]
Will, do. happens only once in a while but I think more often since the last update

**Comment by alexandrudima** [comment]
@jrieken ping

**Comment by jrieken** [comment]
I just happens from time to time. Sorry, but no steps. I'll reopen if I have steps
