### ISSUE TITLE
Typescript Autocompletion Not Working For Function Overloads

### ISSUE THREAD

**Issue by MartinLoeper** [Microsoft/vscode#57509]
- VSCode Version: 1.25.1 1dfc5e557209371715f655691b1235b6b26a06be x64
- OS Version: Linux version 4.15.0-32-generic Ubuntu

Steps to Reproduce:   
I provided a small example of the issue (see screenshot below).

1. Create a function with two overloads
2. Try to invoke this function
3. Once you typed in the first parameter, the IDE recognizes that it matches the first overload's signature.
However, the auto-completion suggest the literals for both overloads.

I expect the auto-completion to show "BW" and "BY" only!

![_005](https://user-images.githubusercontent.com/5209395/44790221-18dbae00-ab9f-11e8-8d80-2dca57cbd5a1.png)

Does this issue occur when all extensions are disabled?: Yes

The code:
```ts

export class MomentHolidayFactory {
    public a(input: Germany, second: GermanState): string;
    public a(input: Austria, second: AustrianState): string;

    public a(input: Country, second: State): string {
        return "test";
    }

    public holidays() {
        this.a("de", ""
    }
}

type Country = Germany & Austria;
type Germany = "de" | "De" | "DE" | "germany";
type Austria = "Au" | "au" | "AU" | "austria";

type State = GermanState & AustrianState;
type GermanState = "BW" | "BY";
type AustrianState = "Stmk" | "Vbg";
```

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#26892
