### ISSUE TITLE
Dynamic menu: allow to pass over role from renderer

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#57510]
This would allow us to remove this hardcoded stuff that should not exist on the main side:

https://github.com/Microsoft/vscode/blob/7fd581283d452d6676353d1bc531998e249fdf14/src/vs/code/electron-main/menubar.ts#L718-L724

**Comment by sbatten** [comment]
@bpasero does this have any value on the render side? we would up doing the exact same if-block on the render side to send it over for just a couple of commands.

**Comment by bpasero** [comment]
@sbatten yeah I see the issue, not really worth it I suppose. I guess you are referring to the fact that a menu item registration does not care about roles and probably should not.

**Comment by sbatten** [comment]
@bpasero yea pretty much, thanks. closing issue
