### ISSUE TITLE
Integrated console inconsistent behavior with regular PS console - Copy-Item

### ISSUE THREAD

**Issue by mstrzelec** [Microsoft/vscode#57514]
- VSCode Version: 1.26.1
- OS Version: Win10

Steps to Reproduce:

1. Open VScode -> Powershell Integrated Console
2.  from any folder try to execute command like Copy-Item ".\Default_files\" "$($env:APPDATA)\Microsoft\Signatures\Something_Default_Files\" -Recurse -Force
(Result will be all files in .\Default_files\ will be copied to ...\Something_Default_Files\ - into that directory (no subdirs created)) assuming there is a subfolder called Default_files. 

3. Now open regular PS console, navigate to the same folder as step 2) and execute the same command - the result will be a subdirectory \Default_Files\ under "$($env:APPDATA)\Microsoft\Signatures\Something_Default_Files\"  

why there is different behavior between the two? You can try adding a * wildcard to create ".\Default_Files\*" which will then work in the normal console copying files only, but it won't copy anything at all in VSCode console and not return any error. 

Does this issue occur when all extensions are disabled?: Yes/No
Yes. Checked in the insiders without any extensions as well - looks the same.

Thank you!

**Comment by Tyriar** [comment]
https://github.com/PowerShell/vscode-powershell
