### ISSUE TITLE
What process.argv0 provides for Mac?

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#57511]
Can you guys tell me what `process.argv0' provides?
and what it will provide in Mac?

I need to get the executable path of code though api so i can get the `bin` folder later on.

**Comment by alexandrudima** [comment]
`process.argv0` evaluates for me to `"/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper.app/Contents/MacOS/Code - Insiders Helper"`

**Comment by shanalikhan** [comment]
I want to **read the bin directory** from 

"/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper.app/Contents/MacOS/Code - Insiders Helper"

bin will be present in
`/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper.app/Contents/MacOS/bin` ?

**Comment by alexandrudima** [comment]
There is a `bin` folder at `/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/bin`.

**Comment by alexandrudima** [comment]
I don't know. I don't think this path is added to the PATH as is the case on Windows and Linux. Perhaps @joaomoreno , you know ?

**Comment by joaomoreno** [comment]
It will stay that way. We don't add that path to the PATH, we add a symlink to it:

```
~ → ls -la /usr/local/bin/code-insiders
lrwxr-xr-x  1 joao  admin  79 Jun  3 22:17 /usr/local/bin/code-insiders -> /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/bin/code
```

**Comment by shanalikhan** [comment]
alright, in Settings Sync I need to call that even its not present in the Path so i need to get from the original directory.

Looks like I have to place a check for Mac Insiders to call `code`. 

IMO there should be consistency for code-insiders for all platforms for the files present in the `bin` directory in terms of name.

Thanks!
