### ISSUE TITLE
[html] fold attributes

### ISSUE THREAD

**Issue by NahianHyder** [microsoft/vscode#57520]
Hi,

I work a lot in HTML. I switched to VS Code a few months back from Sublime text 3 and I'm loving it. However I do miss some of the great built-in features of sublime text. I suggest following features along with system keyboard shortcuts.

- Fold tag attributes [Code Folding]
- Expand selection to tag
- Wrap selection with tag

Thanks in advance

**Comment by aeschli** [comment]
- expand selection to tag is https://github.com/Microsoft/vscode/issues/11458 (see Ramya's tip:  https://github.com/Microsoft/vscode/issues/11458#issuecomment-388857998)
- tag wrapping, see https://stackoverflow.com/questions/40155875/how-to-do-tag-wrapping-in-vs-code

**Comment by aeschli** [comment]
our folding infrastructure can only fold whole lines, so fold tag attributes is not easy to implement.

**Comment by xkubow** [comment]
+1 for Fold tag attributes

**Comment by aeschli** [comment]
#42287 is required for that. Marking as dup.
