### ISSUE TITLE
Search results disappear

### ISSUE THREAD

**Issue by spicybeef** [Microsoft/vscode#57527]
Issue Type: <b>Bug</b>

Step to reproduce:

1. Search
2. Wait a bit after search finishes

For some reasons, the search results disappear after a little bit of time passes.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2687W v4 @ 3.00GHz (48 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.88GB (42.58GB free)|
|Process Argv|C:\Users\mmkakulp\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|0.3.3
arm|dan|0.2.0
gitlens|eam|8.5.6
python|ms-|2018.7.1
cpptools|ms-|0.18.1
sublime-keybindings|ms-|4.0.0

</details>

**Comment by roblourens** [comment]
Not sure what you're seeing, can you include a screenshot or something?

**Comment by spicybeef** [comment]
Before:
![search_before](https://user-images.githubusercontent.com/3586674/44863666-913f7f00-ac32-11e8-8b0b-4e7a7b4ad562.PNG)
After:
![search_after](https://user-images.githubusercontent.com/3586674/44863673-94d30600-ac32-11e8-8eb9-16e7f7a38912.PNG)
I think it triggers when I start building my project.

**Comment by spicybeef** [comment]
Building is done through a Python script from within the source that executes the build and post-processing tools. It's a large chain of events, but I can tell you that it reads and modifies files within the source directory.

**Comment by spicybeef** [comment]
Not these files, no.

Would this happen if a single file gets deleted or modified?

**Comment by roblourens** [comment]
Yes. That would cause this, I can't think of anything else.

**Comment by roblourens** [comment]
I think that surely your build process is regenerating those files, or something similar.
