### ISSUE TITLE
Typescript Intellisense fails to reference inherited methods after private property in class

### ISSUE THREAD

**Issue by FadeZhanger** [Microsoft/vscode#57523]
- VSCode Version: 1.27.0-insider (latest commit on Aug 29)
- OS Version: Windows 10 build 17134
- Typescript version: 3.0.1 

Steps to Reproduce:

1. Create a .ts or .tsx file with a class that extends another class (example below)
```
class Parent {
  protected shouldWork() {
    console.log();
  }
}

class Child extends Parent {
  private hmm: string;
}
```
2. Give the child class a private property.
3. Try referencing the inherited method from the parent class below the private property in the child class. 

Expected: Intellisense autocomplete for the inherited method.  
Actual: Nothing shows up. Changing the private property to a public or protected property causes Intellisense to appear again.

Video: http://recordit.co/3AXtreY6pc

tsconfig:
```
{
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "checkJs": false,
    "experimentalDecorators": true,
    "jsx": "react",
    "lib": [
      "es2015",
      "es2016",
      "es2017",
      "dom"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": false,
    "outDir": "dist",
    "strictNullChecks": true,
    "target": "es5"
  },
  "exclude": [
    "node_modules",
  ],
}
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#26894
