### ISSUE TITLE
Marketplace: broken endless scrolling

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#57529]
When viewing [my profile](https://marketplace.visualstudio.com/publishers/fabiospampinato), on a large-enough or zoomed-out-enough screen I can't see all my extensions because the endless scrolling algorithm is broken.

I guess it assumes a scroll event will happen, which is not always the case, and it doesn't check if a new page should be loaded.

**Comment by gaurav42** [comment]
Thanks @fabiospampinato for reporting this. We are working on the fix.

**Comment by pkuma-msft** [comment]
Hi @fabiospampinato - this issue should have been fixed (actually a few weeks back but I missed updating this thread). Can you please confirm this?

**Comment by fabiospampinato** [comment]
I no longer see the problem, thanks.
