### ISSUE TITLE
Smarter file name suggestion

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#57528]
- VSCode Version: 1.26.1

My [Todo+](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-todo-plus) extension provides syntax highlighting for the following files:

<img width="147" alt="screen shot 2018-08-29 at 19 48 37" src="https://user-images.githubusercontent.com/1812093/44805452-8d751380-abc4-11e8-9f25-c565cfe6eeb4.png">

When saving a new "Todo" file this will be the suggested name:

<img width="368" alt="screen shot 2018-08-29 at 19 47 53" src="https://user-images.githubusercontent.com/1812093/44805483-a7165b00-abc4-11e8-8b3f-d78a0d365096.png">

Which doesn't really make sense, IMHO it should work like this:

1. Pick the first extension that starts with a dot, and suggest `Untitled-1.EXT`
2. If no extension starts with a dot pick the first one and suggest `EXT` instead of `Untitle-1EXT`

**Comment by bpasero** [comment]
I would accept a reasonably small PR to fix this.
