### ISSUE TITLE
VSCode lost my work

### ISSUE THREAD

**Issue by waynebloss** [Microsoft/vscode#57522]
Issue Type: <b>Bug</b>

I created an index.js file `src/lib/yada-yada-yada/`. I edited that file (I think I saved it). Then I attempted to move the file into the parent but VSCode warned me that another file with the same name existed. So I renamed the file first, then moved it. All of my work was lost except for the initial code that I had pasted into the file before I edited it.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.87GB (6.42GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\code\ta\api|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.5.0
EditorConfig|Edi|0.12.4
php-intellisense|fel|2.3.4
gc-excelviewer|Gra|2.1.26
search-node-modules|jas|1.3.0
vscode-json-editor|nic|0.2.0
vscode-docker|Pet|0.1.0
json-to-js-object|sal|0.0.4
rewrap|stk|1.9.1

</details>

**Comment by bpasero** [comment]
@waynebloss very sorry for that, I am quite sure this is the same as https://github.com/Microsoft/vscode/issues/56384 which has been fixed meanwhile. You could try it out from our insider release: https://code.visualstudio.com/insiders/
