### ISSUE TITLE
Error desconocido (no se puede guardar los cambios realizados en un archivo .ts)

### ISSUE THREAD

**Issue by MalignoAnubis** [Microsoft/vscode#57521]
Issue Type: <b>Bug</b>

No se pude guardar cambios realizados en un archivo .component.ts'

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 6.2.9200

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2310M CPU @ 2.10GHz (2 x 2095)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.94GB (0.33GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
aessoft-class-autocomplete|AES|0.1.0
ipl-vscode|aes|1.8.2
vscode-caniuse|aga|0.5.0
vscode-icontheme-nomo-dark|be5|1.3.6
htmltagwrap|bra|0.0.7
angular2-snippets|dan|1.0.19
vscode-simpler-icons|dav|1.6.5
macos-modern-theme|dav|1.1.0
vscode-eslint|dba|1.5.0
scopes|dua|0.40.0
vscode-great-icons|emm|2.1.41
php-debug|fel|1.12.5
php-intellisense|fel|2.3.4
file-icons|fil|1.0.16
auto-close-tag|for|0.5.6
React-JS-snnipets|Gaj|3.0.4
live-html-previewer|hdg|0.3.0
beautify|Hoo|1.4.2
theme-macos-classic|hua|1.1.1
crane|Hvy|0.3.8
vscode-angular2-emmet|jak|2.0.3
easy-icons|jam|0.3.1
autofilename|Jer|0.1.3
Angular2|joh|6.1.5
vscode-icon-theme|jtl|1.6.2
theme-karyfoundation-themes|kar|18.2.1
vscode-simple-icons|Lau|1.8.5
Angular-BeastCode|Mik|6.2.15
theme-monokai-pro-vscode|mon|1.1.8
vscode-language-pack-es|MS-|1.26.3
PowerShell|ms-|1.8.3
laravel5-snippets|one|1.5.0
material-icon-theme|PKi|3.5.3
seti-icons|qin|0.1.3
view-in-browser|qin|0.0.5
laravel-5-snippets|sac|2.0.1
bunker|sld|1.1.6
vscode-vba-icons|spe|1.0.2
vscode-field-lights|sve|0.0.11
sc-themes|Syn|1.4.1
ayu|tea|0.15.0
JavaScriptSnippets|xab|1.7.0
html-css-class-completion|Zig|1.17.1

(3 theme extensions excluded)

</details>

![error](https://user-images.githubusercontent.com/42811998/44800811-f769ca80-ab7c-11e8-8055-7ab3f2e9dd86.PNG)

**Comment by dbaeumer** [comment]
@MalignoAnubis can you please provide the tile and description in English.

**Comment by dbaeumer** [comment]
I am closing the issue. Will reconsider when the title and description is provided in English.
