### ISSUE TITLE
Wacom pen not draging file tabs

### ISSUE THREAD

**Issue by ridesirat** [Microsoft/vscode#57526]
Hi
yesterday, after the latest VSCodeUserSetup-x64-1.26.1 installation (after uninstalling the previous version), i'ts not possible to rearrange the files order on top because the pen doesn't drag the tabs. But with the mouse it's ok.

![image](https://user-images.githubusercontent.com/42814243/44804129-6284c280-abb8-11e8-80a7-50068636ce57.png)

I have no new extensions or installations and none of the other similar issues resolve this.
I hope this info helps.
Thanks!

**Comment by bpasero** [comment]
We never officially supported this, see https://github.com/Microsoft/vscode/issues/43562

**Comment by ridesirat** [comment]
Hi Benjamin. Thanks for the quick reply.
Sorry, maybe I didn't mention it but it was working before  the update installation.
This problem is with the Wacom Pen.
