### ISSUE TITLE
VS Code appears to create a second TSServer on shutdown

### ISSUE THREAD

**Issue by amcasey** [Microsoft/vscode#57534]
Currently, the evidence is anecdotal.  If you enable server logging (e.g. by setting the `TSS_LOG` environment variable), on shutdown, the log is clobbered by an almost empty log.  As of https://github.com/Microsoft/TypeScript/pull/26650, you can include the PID in each log path and now we see a new log (with a new PID) created on shutdown.

**Comment by amcasey** [comment]
FYI @ahejlsberg

**Comment by amcasey** [comment]
This is the TS Server log and the suggested issues appear to be about VS Code logs, so I don't believe this is a duplicate.

**Comment by mjbvz** [comment]
Using the `"typescript.tsserver.trace"` setting already creates unique log file for each start. 

To verifier:

1. In your environment, set the TSS_LOG environment variable as [described here](https://github.com/Microsoft/TypeScript/wiki/Standalone-Server-%28tsserver%29#logging)
1. Open vs code in environemtn
1. Perform some basic edits in a ts file. Verify that log has been created.
1. Then close vscode. 
1. Verify that log file has not been overwritten
