### ISSUE TITLE
Set new tab language

### ISSUE THREAD

**Issue by Swazimodo** [Microsoft/vscode#57531]
Issue Type: <b>Feature Request</b>

Sometimes I'll open a new tab to quickly prototype an edit but I do not plan on saving it. However, I do not see a way to set the language of the new tab to get syntax highlighting working. I think there is a way to set the default but that does not always work.

I could see a languages menu option like notepad++ uses being useful. Or if there was a hotkey to type in your language or extension that would also work.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 6.1.7601

**Comment by dbaeumer** [comment]
The language is indicated in the lower right corner (For new files `Plain Text`). Click it and it will open a picker to change the language.
