### ISSUE TITLE
Cover CSS extension with End to End tests

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#57532]
For certain language features, such as diagnostics, we don't have coverage.

We can cover the CSS extension with it: https://code.visualstudio.com/docs/extensions/example-language-server#_testing-the-language-server

**Comment by D-Jones-1** [comment]
I'd like to help with this, or another easier issue. Can someone explain to me what to do and I'll do the work? I can catch on fast. 👍

**Comment by octref** [comment]
Hi @D-Jones-1, I would need to do this myself. I suggest looking for `good first issue` issues as a starting point: https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

Here is our docs for Contributing: https://github.com/Microsoft/vscode/wiki/How-to-Contribute

**Comment by octref** [comment]
@D-Jones-1 All issues are assigned to an Assignee, who is the expert for that specific feature area. Just ask them in the issue you'd like to help out.

**Comment by D-Jones-1** [comment]
Thank you.

How can I join the list of beginner Assignees?


________________________________

**Comment by octref** [comment]
There is no such things such as beginner Assignee. All assignees are VS Code team members.

**Comment by D-Jones-1** [comment]
Ok.. I arrived here from an open sourcing volunteer site.. they sent me to VS code since you needed help..?


________________________________

**Comment by octref** [comment]
If you do want to help fixing bugs
- Read this: https://github.com/Microsoft/vscode/wiki/How-to-Contribute
- Find a bug you want to work on
- Make a fix or ask the bug's assignee (owner) for directions

**Comment by octref** [comment]
I think what we have now in css-language-features is only a slim layer on vscode-css-languageservice which is pretty well-tested, so closing this.
