### ISSUE TITLE
Very slow search after recent updates

### ISSUE THREAD

**Issue by Sara-Cagle** [Microsoft/vscode#57535]
Issue Type: <b>Bug</b>

Using the built-in search feature of VSCode has become unbearable because it is extremely slow after recent updates. My code base is of a small/manageable size, but whenever I search short, simple strings (not a regex search, and also not using Match Case and Match Whole Word), search takes at least a minute, and in some cases never returns results that it should.
This began happening after one of the recent updates.

For example, I search for: ngIf="false"
And I know I have a line of code in one of my files like this: <button type="button" *ngIf="false" ...

Yet the search ran for at least a minute and then never even returned the match. When I went in and searched *ngIf="false", then it returned instantly, after I opened the file in question to get the right syntax. After that, when I searched ngIf="false" (original query, but this time with the window open after searching *ngIf="false") it returned instantly.

I have witnessed this with many other search terms as well of similar style. I can no longer rely on the search feature to find things in my project.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:37:28.532Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (3.33GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.5.6
tslint|eg2|1.0.38
HTMLHint|mka|0.5.0
vsliveshare|ms-|0.3.577

</details>

**Comment by roblourens** [comment]
There are some tips for troubleshooting this sort of issue here: https://github.com/Microsoft/vscode/wiki/Search-Issues#slow-search-rg-running-for-a-long-time-or-consuming-lots-of-cpumemory

But this sounds different than a typical slow search issue. While the search is running, could you open Task Manager and check which processes are using high CPU? Do you see `rg` (the actual search process) or `MsMpEng.exe` (Windows Defender)?

**Comment by Sara-Cagle** [comment]
Yes. During the search, I am seeing Antimalware Service Executable (`MsMpEng.exe`) consuming over 50% CPU (highest consumption) for over a minute, as well as `rg.exe` (~5%) as part of VSCode (second highest consumption, but not nearly as significant.)

**Comment by roblourens** [comment]
Do you still see this? Have you installed the latest vscode, and have you installed all windows updates?

If this is just an issue with Windows Defender being slow, I don't think there's anything I can do.

The low CPU numbers tell me that your disk might be slow.
