### ISSUE TITLE
Not displaying server name of a file/folder opened from network share

### ISSUE THREAD

**Issue by f-w** [Microsoft/vscode#57533]
- VSCode Version: 1.26.1
- OS Version: Windows 7

Steps to Reproduce:

1. Open a file from network share such as \\\\server\e$\foo.txt
3. The file editor tab is not showing server name when hovering over, but only \e$\foo.txt
2. Close the file and go to File > Open Recent. I also only see \e$\foo.txt

![image](https://user-images.githubusercontent.com/12823994/44807212-d2c22280-ab7d-11e8-812b-03e214a610ec.png)

Does this issue occur when all extensions are disabled?: Yes

I use vscode to open files in the same relative folder on different servers so being able to see the server name is critical. The issue occurs since about 3 months ago. It used to be working.

**Comment by sandy081** [comment]
@isidorn Is this from new URILabelService?

**Comment by isidorn** [comment]
@sandy081 might be. Assigning to me to first investigate

**Comment by isidorn** [comment]
Fixed

**Comment by isidorn** [comment]
No need to verify, since this is a duplicate bug, removing bug adding duplicate
