### ISSUE TITLE
Loaded Script tooltip shows path component twice

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#57545]
Testing https://github.com/Microsoft/vscode/issues/57249

![screen shot 2018-08-29 at 2 08 18 pm](https://user-images.githubusercontent.com/323878/44816162-45d79300-ab96-11e8-8bab-9bd32265fbcd.png)

- https://github.com/Microsoft/vscode-chrome-debug/tree/master/testapp
- Run `gulp buildAndServe`, debug in vscode
- See test2.js in Loaded Scripts, the tooltip shows `client with space` twice in the script path

The DA sends the correct thing `To client: {"seq":0,"type":"event","event":"loadedSource","body":{"reason":"new","source":{"name":"test2.js","path":"http://localhost:8080/out/client%20with%20space/test2.js","sourceReference":1002}}}`

I don't see that with other scripts, maybe it's the space in the path?

**Comment by bpasero** [comment]
@weinand I am adding the candidate label, please check with @egamma before pushing changes that we did not talk about

**Comment by egamma** [comment]
👍 on fixing for August
