### ISSUE TITLE
All breakpoints are unverified when debugging on Angular 6/Node 10.9

### ISSUE THREAD

**Issue by Kalonjelen** [Microsoft/vscode#57540]
Issue Type: <b>Bug</b>

Create a project with Angular 6. 
Install Node.js 10.x (10.8 or 10.9 appear to replicate this)
Have debugger with the following options 
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:4201",
            "sourceMaps": true,
            "trace" : true,

Run your server locally, and then launch debugger. 

Expected: breakpoints enable as expected
Actual: breakpoints are all 'unverified'. Log points are also 'unverified'.

Some notes on this:
-if I put in 'debugger' - the command -  in the code file, it breaks into that file and gives a 'read only source copy' of that file. In that file, I can set breakpoints. 
-this occurs with using the extension debugger for chrome and debugger for edge

VS Code version: Code - Insiders 1.27.0-insider (47d0584301d16d4efd6618f6f33ef14099c92561, 2018-08-29T05:18:47.523Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz (12 x 3298)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.90GB (15.61GB free)|
|Process Argv|C:\Users\kalonj\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
debugger-for-chrome|msj|4.9.0

</details>

**Comment by Kalonjelen** [comment]
Note that this happens on both Insiders and generic VSCode. 

It also happens with the latest 'correct' release for Node.JS as well as the 10.9 version.

**Comment by roblourens** [comment]
Can you run the `.scripts` command to see how your sourcemap paths are being resolved?

**Comment by Kalonjelen** [comment]
Sure - how would you like the output? Here's the output for one of the files in question which has breakpoints and isn't getting picked up:
webpack:///./src/app/help/help-article.component.ts (${webRoot}\src\app\help\help-article.component.ts)

**Comment by roblourens** [comment]
You do need to set the webRoot in your launch config, which might just be `"webRoot": "${workspaceFolder}"`

**Comment by roblourens** [comment]
Great!
