### ISSUE TITLE
Terminal/Problems/Output buttons are pushed off-screen on Right

### ISSUE THREAD

**Issue by Shappenny** [Microsoft/vscode#57557]
Issue Type: <b>Bug</b>

# Actual Results
When you click the button "Move to Right" to move the Termnal, Problems, or Output windows to display vertically on the right side of the screen, these windows will hide some of their menu buttons (at the top of this vertical split) if the window is resized too narrowly. This is especially annoying because it can hide the button to switch the windows to the horizontal on bottom layout.  
This doesn't seem to affect the Debug Console--it snaps closed before getting too narrow to show the buttons.  

![vscode_sidebar_bug1](https://user-images.githubusercontent.com/6734343/44823511-b346ec00-abb5-11e8-94f5-82dd71b538ad.PNG)
![vscode_sidebar_bug2](https://user-images.githubusercontent.com/6734343/44823513-b346ec00-abb5-11e8-9a06-a35d1902f751.PNG)

# Expected Results
I expect 1) all of the buttons to show and prevent the windows from being narrowed beyond this level or 2) the buttons to "stack" into some sort of drop down button.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:34:20.517Z)
OS version: Linux x64 4.10.0-42-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-7900X CPU @ 3.30GHz (10 x 1599)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|1, 1, 1|
|Memory (System)|62.60GB (56.59GB free)|
|Process Argv|/usr/share/code/code|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.7.1
Go|ms-|0.6.88

</details>

**Comment by Shappenny** [comment]
Ah, this is a duplicate of https://www.github.com/Microsoft/vscode/issues/55944. My apologies.

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/46017
