### ISSUE TITLE
Python highlighting - raw string literals incorrectly colour escape sequences in some cases

### ISSUE THREAD

**Issue by akdor1154** [Microsoft/vscode#57555]
- VSCode Insiders Version: 1.27.0-insider 47d0584301d16d4efd6618f6f33ef14099c92561 x64
- VSCode Stable Version: 1.26

- OS Version: ubuntu 18.04 x64

Steps to Reproduce:

1. Open/create a python file
2. Write a raw string with some backslashes as a function parameter:
```py
open(r'C:\Jenkins\new-file.xml')
```
Observe the backslashes are incorrectly shown as being part of an escape sequence. Raw strings literals have literal backslashes, you can't write escape sequences in them. The string should be a solid colour. `\n` should not be highlighted as it is in a raw string, and `\J` should not be highlighted as it's not even an escape sequence in a normal string (normal string highlighting behaves correctly here).
Looks like GitHub highlighting gets it wrong too. :)

![image](https://user-images.githubusercontent.com/6732831/44823302-06b34b80-ac43-11e8-8d28-0b46db8c43a1.png)

**Comment by aeschli** [comment]
This issue was moved to MagicStack/MagicPython#155

**Comment by akdor1154** [comment]
@aeschli MagicPython considers this to be a feature. I as a VSCode user consider it to be a bug, as it's a non-standard "convention" that has been actively rejected by Python devs incl. van rossum. https://mail.python.org/pipermail/python-ideas/2015-October/thread.html#36947
I would like some way to turn this off in VSCode.

(Sorry this sounds a bit demanding, I don't mean it as such, just stating my opinions as a user.)
