### ISSUE TITLE
Aladdin's lamp is gone

### ISSUE THREAD

**Issue by cipchk** [Microsoft/vscode#57558]
Version: 1.26.1
Commit: 493869ee8e8a846b0855873886fc79d480d342de
Date: 2018-08-16T18:38:57.434Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Steps to Reproduce:

gif:

![a](https://user-images.githubusercontent.com/2987467/44825006-234b8580-ac3b-11e8-8d1b-36e9795eac62.gif)

There is an x-axis scroll bar, the Aladdin's lamp is gone.

Does this issue occur when all extensions are disabled?: No

**Comment by jrieken** [comment]
That's the design of lightbulb - we have considered different options (and actually had them implemented for a while) but none were better or more easy to use. Currently, no plans to change this.
