### ISSUE TITLE
[HTML] Align attributes of tag only if the line is too long but keep others intact

### ISSUE THREAD

**Issue by darkguy2008** [Microsoft/vscode#57556]
I did a search and found this issue https://github.com/Microsoft/vscode/issues/2204 but the bot blocked it and I can't comment. I've tried different HTML alignment settings but they don't seem to match what I'm looking for or maybe I haven't found the right settings? 

Here's an example (current code):

![code1](https://user-images.githubusercontent.com/6304136/44823330-10926b80-abbd-11e8-8400-962d40c6d210.png)

Now here's what I'd like. Notice there are some tags that haven't been aligned:

![code2](https://user-images.githubusercontent.com/6304136/44823335-19833d00-abbd-11e8-9aa1-b57e0563c538.png)

I know there's a line length limit in the formatting settings, but it seems to be enabled only for the entire document if there's a single line that surpasses the limit, but it doesn't affect the offending tag, but the entire document instead and that's not what I want.

Hopefully this can be considered as an improvement for an upcoming version.

**Comment by aeschli** [comment]
We use [beautifyjs](http://jsbeautifier.org/) as the underlying HTML formatter. Would you mind filing this request directly against https://github.com/beautify-web/js-beautify ?
