### ISSUE TITLE
HTML <big> tags not displaying properly

### ISSUE THREAD

**Issue by Nixinova** [Microsoft/vscode#57566]
Issue Type: <b>Bug</b>

HTML &lt;big&gt; tags are displaying coloured red as if they shouldn't be there but VS is not telling me of any issues with it apart from just the visual issue.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 2200G with Radeon Vega Graphics     (4 x 3493)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.95GB (3.14GB free)|
|Process Argv|C:\Program Files\Visual Studio Code\Code.exe C:\Users\GGPC\Documents\Website\maps\musical-blocks.html|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
marshal-command-code|din|1.1.2
vscode-nyanfi|kur|0.1.12
mcjson|Lev|0.3.0
incrementor|nms|0.1.0
datapack-helper|pca|0.6.1
minecraft-lang-colorizer|zz5|1.0.0

</details>

**Comment by alexr00** [comment]
That's because the `<big>` tag is deprecated in HTML5 😊

**Comment by octref** [comment]
We don't do any diagnostics for HTML since there are too many flavors of HTML.
This is as-designed.
