### ISSUE TITLE
Make os freeze on ubuntu like Chromium

### ISSUE THREAD

**Issue by hippyk** [Microsoft/vscode#57568]
I solve the problem of Chromium with the help of the answer blow. 
https://askubuntu.com/questions/765974/chrome-freeze-very-frequently-with-ubuntu-16-04

I guess it is the same problem on vscode. Can anyone check this?

**Comment by dbaeumer** [comment]
If this seems to be Electron related

**Comment by bpasero** [comment]
I have no clue.

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!

**Comment by hippyk** [comment]
It seems not a performance issue. I'm going to  try  'code --disable-gpu'  first to see if the problem still exists.

**Comment by bpasero** [comment]
OK
