### ISSUE TITLE
Improve DEBUG CONSOLE for program input

### ISSUE THREAD

**Issue by testforstephen** [Microsoft/vscode#57571]
In Java Debug, we found user often uses the DEBUG CONSOLE for program input by mistake. I guess it's because other IDEs like eclipse/intellij both support in-place text input in CONSOLE. Is it possible to improve the DEBUG CONSOLE behavior? Or at least improve the user awareness.

**Comment by weinand** [comment]
@testforstephen you could make VS Code's "integrated terminal" the default for Java because a REPL is not that important for Java, correct?

**Comment by testforstephen** [comment]
lots of Java users are using `evaluate` feature correctly, not sure how much REPL counts. Changing the default console to "integrated terminal" feels a little aggressive.

Another helpful tip is support comments when generate initial debug config. 
```
        {
            "type": "java",
            "name": "Debug (Launch)",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            // To support console input, please switch console to integratedTerminal or externalTerminal.
            // "console": "integratedTerminal",
            "console": "internalConsole",
            "stopOnEntry": false,
            "mainClass": "",
            "args": ""
        },
```
