### ISSUE TITLE
Getting error 

### ISSUE THREAD

**Issue by HeroSuperGaming** [Microsoft/vscode#57575]
- VSCode Version: 1.27 insiders 
- OS Version: Windows 10 1803

Steps to Reproduce:

1.Open VS Code 
2.On start you will get the error on start 

Does this issue occur when all extensions are disabled?: Yes/No Yes
![json_error](https://user-images.githubusercontent.com/28282044/44836332-5263f600-ac3f-11e8-914b-f01d1b26092e.png)

**Comment by dbaeumer** [comment]
@aeschli marking as important since it happens in insider.

**Comment by aeschli** [comment]
fixed by https://github.com/Microsoft/vscode/commit/051da84e0f85ec291fd2479b665f5c5c2c60ef72
