### ISSUE TITLE
support search history

### ISSUE THREAD

**Issue by bruceauyeung** [Microsoft/vscode#57578]
after i have searched something through left search panel(Ctrl + Shift + F), i try to find out what keywords i have searched,  but it seems there is no way to do so.
I suggest we should at least record search keywords, and display them using dropdown menu when user focusing search input box, and even further search results per keyword .
I'm using vscode version : 1.26.1
os : ubuntu 1604

**Comment by roblourens** [comment]
Up/down arrows

**Comment by bruceauyeung** [comment]
it would be better if having a hint to tell user, thanks!
