### ISSUE TITLE
Test notify Linux user when a new update is available

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#5757]
- [x] @aeschli
- [x] @seanmcbreen 

Linux users should now get update notifications in the workbench. An easy way to trigger this is to open your installed Code's `product.json`, change the commit to anything other than the current value and restart. The `Update` action should also appear in the `About` menu, although it'll only open a browser, in case there is an update available.

**Comment by seanmcbreen** [comment]
Worked like a charm - my related issue is about an install problem vs the update notification.
