### ISSUE TITLE
Select multilpe lines from the same column by holding ALT – like in Visual Studio

### ISSUE THREAD

**Issue by gabzdyl** [Microsoft/vscode#57573]
I really need to select multiple lines in text editor, but NOT from column 0. I can do it in Visual Studio by holding ALT on my keyboard. I would be very good to have this feature in VS Code too. Thanks

**Comment by alexandrudima** [comment]
Let's track in #34355

The reason is that alt+click introduces a new cursor (it can be introduced anywhere, unrelated to column selection), which is a feature that does not exist in Visual Studio.
