### ISSUE TITLE
"terminal.integrated.cursorStyle" setting is ignored when rendering terminal in DOM mode

### ISSUE THREAD

**Issue by gozzoo** [Microsoft/vscode#57587]
- VSCode Version: 1.26.1
- OS Version: Windows 7

Steps to Reproduce:

1. set cursor style to `underline`
`"terminal.integrated.cursorStyle": "underline",`

2. enable DOM rendering
`  "terminal.integrated.rendererType": "dom"`

Regardles of that setting the cursor is still style is still `block`.

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/xtermjs/xterm.js/issues/1640

**Comment by Hindol** [comment]
@Tyriar I want to pick this up but I need some guidance. Do I fix the upstream issue directly and then change `xtermjs` version in `vscode`?

**Comment by Tyriar** [comment]
@Hindol great 😃, just fix the upstream issue and I'll include it in vscode-xterm and republish. I'd also mention in https://github.com/xtermjs/xterm.js/issues/1640 that you're picking it up too.

**Comment by Hindol** [comment]
Cool. I'm on it.

**Comment by Tyriar** [comment]
Should be working now.
