### ISSUE TITLE
[insider bug] extra quotation marks included in search result for json file

### ISSUE THREAD

**Issue by wayou** [Microsoft/vscode#57583]
Issue Type: <b>Bug</b>

- create a json `a.json` file with content `{"b":"c"}`
- search for `c` and the match is `c"`

<img width="374" alt="insider_search_bug" src="https://user-images.githubusercontent.com/3783096/44842588-e0a89e00-ac78-11e8-8a08-e2a6c93e664f.png">

VS Code version: Code - Insiders 1.27.0-insider (47d0584301d16d4efd6618f6f33ef14099c92561, 2018-08-29T05:12:15.247Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|35, 13, 7|
|Memory (System)|8.00GB (0.36GB free)|
|Process Argv|/Users/wayou/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_7186138|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
bazel-code|Dev|0.1.9
EditorConfig|Edi|0.12.4
vscode-css-formatter|aes|1.0.1
codealignment-vscode|cpm|2.0.19
dart-code|Dar|2.17.1
flutter|Dar|2.17.1
devdocs|dei|0.1.4
githistory|don|0.4.2
vscode-bazel-tools|dpr|0.0.8
gitlens|eam|8.5.6
tslint|eg2|1.0.38
vsc-material-theme|Equ|2.4.2
carbon-now-sh|eri|1.2.0
prettier-vscode|esb|1.6.1
auto-close-tag|for|0.5.6
theme-macos-classic|hua|1.1.1
docthis|joe|0.7.1
vscode-styled-components|jpo|0.0.21
vscode-fileheader|mik|0.0.2
vscode-csscomb|mrm|5.2.2
python|ms-|2018.7.1
Go|ms-|0.6.88
vscode-code-outline|pat|0.2.1
material-icon-theme|PKi|3.5.3
seti-icons|qin|0.1.3
vscode-icons|rob|7.25.0
sass-indented|rob|1.4.9
code-settings-sync|Sha|3.1.1
html5-boilerplate|sid|1.0.3
file-icons-mac|way|1.0.1

(9 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Should be fixed in today's Insiders #57303
