### ISSUE TITLE
Breadcrumb: drive letter should be upper case

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#57588]
On Windows:

![image](https://user-images.githubusercontent.com/900690/44843619-f69e6a80-ac48-11e8-9368-b69c6cc8e809.png)

**Comment by jrieken** [comment]
@isidorn This uses `FileLabel` which I think should be in charge of this?

**Comment by isidorn** [comment]
Yeah the FileLabel has a dependency on the LabelService so in theory all should be good.
I would put a breakpoint [here](https://github.com/Microsoft/vscode/blob/712cd009f8ee594cc448a259dc8cdfec85659470/src/vs/workbench/browser/labels.ts#L194) and check if it is properly calling into the labelService

**Comment by jrieken** [comment]
Yeah, it goes through there but this is the label that's not being massaged, but the whole path.

**Comment by jrieken** [comment]
Assigning to @bpasero because he seems to own the `FileLabel`

**Comment by bpasero** [comment]
Weird now I cannot reproduce anymore:

![image](https://user-images.githubusercontent.com/900690/44852126-bba93080-ac62-11e8-8d75-1f1f5f2a5c8b.png)

Dunno what kind of setup I had.

**Comment by isidorn** [comment]
What might have happened is that the rendering happened before `file` schema label rendering rules got registered. I do not think I can do this any sooner https://github.com/Microsoft/vscode/blob/712cd009f8ee594cc448a259dc8cdfec85659470/src/vs/workbench/parts/files/electron-browser/files.contribution.ts#L180
