### ISSUE TITLE
Native tabs: "New Tab" becomes disabled once clicked once

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#57584]
- OS Version: macOS

Steps to Reproduce:

1. enable window native tabs in settings
2. pick Window > New Tab

=> 🐛 the action from now on stays disabled and cannot be triggered anymore

![image](https://user-images.githubusercontent.com/900690/44842641-afaf7580-ac46-11e8-82c8-6be60ec37c06.png)

**Comment by isidorn** [comment]
Verified out of source
