### ISSUE TITLE
document opening is very slow

### ISSUE THREAD

**Issue by olijf** [Microsoft/vscode#57582]
Issue Type: <b>Performance Issue</b>

I am running vscode on Ubuntu, but if I open documents it is very slow. I do not think this is a harddrive issue, as there is almost no disk activity. CPU usage is almost at 45%. I hava an older i7 in my thinkpad (T520) but I do not think the CPU should be the problem here. 
I hope you can help me make this better!

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:34:20.517Z)
OS version: Linux x64 4.15.0-33-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2620M CPU @ 2.70GHz (4 x 2999)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|11.62GB (2.09GB free)|
|Process Argv|/snap/vscode/51/usr/share/code/code|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    3	   131	  2983	code main
    0	    36	  2985	   zygote
    4	   488	  3146	     window (● Startup.cs - AdaFrontend - Visual Studio Code)
    0	     0	  3243	       /bin/bash
    0	    59	  3259	       searchService
    0	   119	  3264	       extensionHost
    0	    59	  3293	         searchService
    0	     0	  3324	         bash /home/olaf/.vscode/extensions/ms-vscode.csharp-1.15.2/.omnisharp/1.30.1/run -s /home/olaf/git/ada/AdaFrontend --hostPID 3264 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4
    0	   357	  3332	           /home/olaf/.vscode/extensions/ms-vscode.csharp-1.15.2/.omnisharp/1.30.1/bin/mono.linux-x86_64 /home/olaf/.vscode/extensions/ms-vscode.csharp-1.15.2/.omnisharp/1.30.1/omnisharp/OmniSharp.exe -s /home/olaf/git/ada/AdaFrontend --hostPID 3264 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4
    0	    59	  8507	         electron_node jsonServerMain.js 
    0	   155	 15843	         electron_node electronForkStart.js tsserver.js 
    0	    83	 15848	           electron_node typingsInstaller.js tsserver.js typesMap.js 
    0	    71	  3280	       watcherService
    0	   119	  3178	     shared-process
    1	   107	 17947	     window (Issue Reporter)
    4	   143	  3131	   gpu-process
    0	     0	 17965	   /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 17966	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● Startup.cs - AdaFrontend - Visual Studio Code)
|    Folder (AdaFrontend): 861 files
|      File types: dll(645) json(49) pdb(24) cache(24) js(19) so(18) ts(13)
|                  cs(10) svg(8) html(6)
|      Conf files: package.json(4) tsconfig.json(4) csproj(1)
|                  webpack.config.js(1) launch.json(1) tasks.json(1)
|      Launch Configs: coreclr(4);
```

</details>
<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-npm-script|eg2|0.3.5
vscode-npm|fkn|3.3.0
dotnet-core-essentials|Kis|0.0.5
csharp|ms-|1.15.2

</details>

**Comment by dbaeumer** [comment]
@olijf the attached performance trace doesn't show any high CPU usage for VS Code. Can you do the following:

- open Help > Process Explorer
- open the document and record which processes cause high CPU load. 

And does it reproduce if you disable all extensions (e.g. start vscode from the terminal and pass `--disable-extensions`

**Comment by olijf** [comment]
Hi Dirk,
I figured it out, I had several extensions running, but not very high cpu usage, however when I disabled almost all and enabled them one by one I found that everything was quicker and more responsive. When it took 4 seconds to open 1 *.cs file I figured which was the process that was making everything slow. I have disabled that extension for now. Thanks for pointing me in the right direction. 
You can close this for now.
