### ISSUE TITLE
Status line hidden

### ISSUE THREAD

**Issue by Vitalitix** [Microsoft/vscode#57581]
Issue Type: <b>Bug</b>

Windows 10
Place vscode window in display with task bar.
Set vscode to full screen.
The lower part (status line) is hidden under the display taskbar.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2320 CPU @ 3.00GHz (4 x 2993)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.98GB (2.10GB free)|
|Process Argv|C:\Users\rshra\AppData\Local\Programs\Microsoft VS Code\Code.exe c:\Users\rshra\Desktop\UnBaund\BlockCypher\ethereum|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.5.0
svn-scm|joh|1.33.0
mssql|ms-|1.4.0
debugger-for-chrome|msj|4.9.0
vetur|oct|0.12.6
java|red|0.29.0
vscode-java-debug|vsc|0.12.0

</details>

**Comment by bpasero** [comment]
@Vitalitix and a screenshot maybe to show the issue

**Comment by Vitalitix** [comment]
It happen when I have 2 monitors.
Once I had only one monitor it was fixed.
Switching back to 2 monitors, the issue was not seen.
![image](https://user-images.githubusercontent.com/5176338/44944250-2e89e700-addc-11e8-8dc8-b58a4aa1eb45.png)

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/883208e30da25777874a8ade5f90e1fea638a298/VSCode-win32-x64-1.28.0-exploration.zip)
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/883208e30da25777874a8ade5f90e1fea638a298/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/883208e30da25777874a8ade5f90e1fea638a298/code-exploration-1535724826.tar.gz)

**Comment by Vitalitix** [comment]
Can't reproduce anymore.
It was fixed by disabling and re-enabling multiple displays.
