### ISSUE TITLE
[theme] seti R Icon too large

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#57595]
![image](https://user-images.githubusercontent.com/900690/44846124-c908ef80-ac4f-11e8-80d1-406bac4e79cf.png)

**Comment by aeschli** [comment]
I filed https://github.com/jesseweed/seti-ui/issues/507

**Comment by bpasero** [comment]
Still: 

![image](https://user-images.githubusercontent.com/900690/46014318-1ea9ae00-c0cf-11e8-9383-fe70c53ea78d.png)

**Comment by aeschli** [comment]
It was closed as upstream...
