### ISSUE TITLE
VSCode freezes in markdown for brackets

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#57593]
1. Open a mardkown file
2. Have the following string

```
* [55323]https://github.com/Microsoft/vscode/issues/55323
```

Type a `(` right after the `]` -> vscode freezes. I can repro constantly on my os x.

**Comment by alexandrudima** [comment]
To troubleshoot:

1. Edit `node_modules/oniguruma/src/onig-reg-exp.cc`
2. Around line 50, add `printf("Searching for %s\n", source_.c_str());`
![image](https://user-images.githubusercontent.com/5047891/44847156-cfe53180-ac52-11e8-90c3-c6862dfa7d0f.png)
3. `cd node_modules/oniguruma`
4. `node-gyp build`
5. open the file that is causing the 100% cpu usage and look at the console for the last regex that was being searched.



For the md file `[55323](https://github.com/Microsoft/vscode/issues/55323` this is:

```
Searching for (?x)
  (\[)((?<square>[^\[\]\\]|\\.|\[\g<square>*+\])*+)(\])
                # Match the link text.
  (\()            # Opening paren for url
    (<?)((?<url>[^\s()]+|\(\g<url>*\))*)(>?)      # The url
    [ \t]*          # Optional whitespace
    (?:
        ((\().+?(\)))    # Match title in parens…
      | ((").+?("))    # or in quotes.
    )?            # Title is optional
    \s*            # Optional whitespace
  (\))
```

This comes from [this line](https://github.com/Microsoft/vscode/blob/712cd009f8ee594cc448a259dc8cdfec85659470/extensions/markdown-basics/syntaxes/markdown.tmLanguage.json#L2380) in the grammar

**Comment by chrmarti** [comment]
Additional examples (always involving links) are in #57201.

**Comment by alexandrudima** [comment]
@mjbvz I will revert all changes to the markdown grammars to the version we shipped in stable.
