### ISSUE TITLE
Test JSHint new features

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#5759]
- [x] @waderyan

 

We recently updated the jshint extension with extends and exclude support as described in the extensions ReadMe.md file.

No cross-platform testing required. A single platform suffices.

**Comment by waderyan** [comment]
OK. works. 

```
{
  "jshint.enable": true"
}
```

Doesn't work. 
```
{
  "jshint.exclude": {
       "./src/data.js": true,
       "Gruntfile.js": true
  }
}
```

![image](https://cloud.githubusercontent.com/assets/2449568/14832414/0d3a0372-0baf-11e6-95f3-0365df6f02d8.png)

Hovering over the green squiggle will show a jshint issue.

**Comment by kieferrm** [comment]
The exclude patterns are currently not relative to the workspace root. It makes sense to change that.

**Comment by waderyan** [comment]
OK. Resolved. Talked to @kieferrm about a couple of things he has on his roadmap.
