### ISSUE TITLE
Breadcrumbs: enable for diff editors if right hand side is file

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#57594]
I think breadcrumbs could just work if a diff editor is opened and the right hand side is a file. E.g. quick outline also just works on the right hand side. 

![image](https://user-images.githubusercontent.com/900690/44845704-8f83b480-ac4e-11e8-97ee-d17d5988b5c1.png)

**Comment by jrieken** [comment]
Yeah - was also waiting for that one ;-)
