### ISSUE TITLE
Changes are lost after commit and no commit is created

### ISSUE THREAD

**Issue by gazedash** [Microsoft/vscode#57599]
- VSCode Version: 

Version 1.24.1
Commit 24f62626b222e9a8313213fb64b10d741a326288
Date 2018-06-13T17:47:35.732Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- OS Version: Ubuntu 18.04.1 LTS

Steps to Reproduce:

1. Add files for staging
2. Commit them
3. Wait for pre-commit hooks
4. No errors are shown
5. No files are staging
6. No commit is created
7. Changes are lost

Git version:
git version 2.17.1

It usually shows errors if pre-commit hook failed, but there were no errors

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
Can you reproduce this just using the command line, without VS Code?

**Comment by gazedash** [comment]
@joaomoreno No, that's the issue - it only happens through VS code

**Comment by joaomoreno** [comment]
If you open `Git: Show Git Output`, what's the output that appears when the bug reproduces?
