### ISSUE TITLE
Replacing core commands

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#576]
_From @alefragnani on November 4, 2015 1:12_

Is there a _correct way_ to replace core commands? 
_(of course, if this is something that is available or in the roadmap)_

My intention is to create an extension to replace _Edit / Copy (`editor.action.clipboardCopyAction`)_ and _Edit / Cut (`editor.action.clipboardCutAction`)_ commands. So, when there is no selection, the _Copy/Cut_ would use the _current word_ instead of the _entire line_.

About coding, I can:
- Determine the word based on the cursor position
- Select the word
- Execute `vscode.commands.executeCommand("editor.action.clipboardCopyAction")` 
- Remove the selection, returning the cursor to its initial position.

But I was wondering if there is something else that I could (or couldn't) do, like defining the `keybindings` in `package.json` to `Ctrl + C / Ctrl + X`; or define `vscode.commands.registerCommand` for the core command, with my own code.

Thanks in advance

_Copied from original issue: Microsoft/vscode-extensionbuilders#79_

**Comment by jedmao** [comment]
I also need to override arrow-key navigation, backspace and delete key bindings for my plugin, TabSanity, which is a port of [`TabSanity`](https://visualstudiogallery.msdn.microsoft.com/ac4d4d6b-b017-4a42-8f72-55f0ffe850d7) from the full-blown Visual Studio.

Additionally, it would be ideal if we could "override" core commands, but still have the ability to execute the original commands manually for fallback cases.

**Comment by Ivan171** [comment]
I would like to replace "Save As" command to "Save All". I added the keybinding, but now theres two commands for the keybinding Ctrl+Shift+S.

**Comment by dannyvv** [comment]
@Ivan171 I had the same issue initially. Just override the other to empty:
```json
[
	{"key": "ctrl+shift+s", "command": "workbench.action.files.saveAll"}
	{ "key": "",          "command": "workbench.action.files.saveAs" },
]
```
