### ISSUE TITLE
Can copy but can not edit user/workspace settings

### ISSUE THREAD

**Issue by bin16** [Microsoft/vscode#57606]
Issue Type: <b>Bug</b>

1. Let's start edit user settings or workspace settings
2. From left, click on the pencil icon to copy an item to right. e.g. `"beautify.tabSize": 0`
3. I CAN NOT EDIT / DELETE / TYPE SOME WORDS or anything else on the key-value item at right. It is read only, but no way to change the value? (PS: if the value is boolean, i see a pencil to toggle true/false, but not a tool for number or string)

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17746

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (1.87GB free)|
|Process Argv|C:\Users\ms\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.5.0
xml|Dot|2.3.2
vscode-html-css|ecm|0.2.0
EditorConfig|Edi|0.12.4
vue-snippets|hol|0.1.8
smarty|imp|0.3.0
VS-code-drupal|mar|0.0.12
Kotlin|mat|1.6.0
code-beautifier|mic|2.1.0
vscode-language-pack-zh-hans|MS-|1.26.3
mssql|ms-|1.4.0
python|ms-|2018.7.1
csharp|ms-|1.15.2
Go|ms-|0.6.88
PowerShell|ms-|1.8.3
vetur|oct|0.12.6
html-css-class-completion|Zig|1.17.1

</details>

**Comment by bin16** [comment]
Thanks @roblourens i don't know why, but it works now. May be we can close that.

**Comment by roblourens** [comment]
Let me know if it happens again
