### ISSUE TITLE
'Shown matching extensions' is confusing

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#57601]
I search for one of the html settings and see a `Show matching extensions` button next to the setting.
What is it for?

![image](https://user-images.githubusercontent.com/6461412/44847736-a4634680-ac54-11e8-9eeb-e3e6f620adb5.png)

**Comment by roblourens** [comment]
The Bing service searches settings in extensions that you may want to install, the button shows you the extensions.

**Comment by aeschli** [comment]
is it based on the search query ('html server' in my case)? In that cse, the button could be closer to the search field.
Or place the button right under the search results (on the left, below the tree) and call it something 'Find more results in marketplace..'. A hover on the button could also explain what it does. 'Search for settings matching 'html server' in the marketplace'
