### ISSUE TITLE
Do not render focus border when mouse click

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#57608]
Settings ux > click on the table of context > notice the focus outline is rendered and looks ugly

I recommend to draw focus outline only if I am navigating with the keyboard not if I click with the mouse. I believe a bunch of our other ux components behave just like this.

![screen shot 2018-08-30 at 14 30 44](https://user-images.githubusercontent.com/1926584/44851709-7801f700-ac61-11e8-8e16-8a2d118a9f99.png)

**Comment by roblourens** [comment]
How can I tell the difference? I think we have to show focus. I often switch between clicking and keyboard anyway.

**Comment by isidorn** [comment]
You are right, we should not differnetiate.
So for this I would just like some design actually. The focus border looks ugly, could we use some blue background color for focus like in all our other lists?
@misolori

**Comment by roblourens** [comment]
I think I used this instead of a normal background color because it looks weird to have a rectangle of color there when the TOC isn't in a container like the sidebar.

**Comment by misolori** [comment]
I am also not a fan of the focus border on click (that's what the brighter and bolder text is for), but that focus treatment does make sense for keyboard focus.

**Comment by roblourens** [comment]
I think that I have to know where focus is, regardless of how it got there. This matches other stuff

**Comment by isidorn** [comment]
@roblourens I believe this is not fixed, just closed, correct? Since I tried to verify and it is still like that. In that case removing bug label so it goes away from my verification query
