### ISSUE TITLE
Breadcrumb: use same style for scrollbar as in tabs

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#57600]
Seems a bit weird that we have 2 scrollbars so close to each other that are not looking the same. I think the height is different:

![image](https://user-images.githubusercontent.com/900690/44847776-c6f55f80-ac54-11e8-8189-cfba2adca182.png)

**Comment by jrieken** [comment]
@bpasero is that windows?

**Comment by bpasero** [comment]
@jrieken yeah I think so

**Comment by jrieken** [comment]
I actually don't see a difference... 

![sep-07-2018 15-15-48](https://user-images.githubusercontent.com/1794099/45221237-297fd880-b2b1-11e8-8ce8-ec67aa3af515.gif)

**Comment by bpasero** [comment]
Yeah funky, I checked in dev tools and both have the same height of 3px, though they look different:

![image](https://user-images.githubusercontent.com/900690/45235511-5c3dc700-b2d9-11e8-9c03-2701b18034bf.png)

I have no real explanation, feel free to close.

**Comment by jrieken** [comment]
Maybe a windows issue? Is it possible that the tabs scrollbar is cut off somewhere? Let's take a look on your windows machine

**Comment by bpasero** [comment]
Yes I think this could be the tabs cutting off the scrollbar, I can check on that.

**Comment by bpasero** [comment]
This is changing depending on my zoom level, sometimes it looks OK sometimes the one is larger compared to the other. I could not find any CSS difference, in both cases the slider is positioned absolute in the parent container with a height of 3px. There does not seem to be an overflow issue either. Closing.
