### ISSUE TITLE
Allow extension to Reload Code

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#57605]
Settings Sync installs extension but needs to reload the visual studio code to take affect.

There should be a API to allow extension authors to initiate reload process, when they call API - Code should inform user that Code will be reloaded alongwith some text sent by extension authors.
Upon user acceptance Code should be reloaded.

Or there should be some notification pending that should be enabled by extension authors in status bar to let user click and reload the code

**Comment by jrieken** [comment]
There is the reload window command. Isn't that enough or too much?

**Comment by jrieken** [comment]
sure, `executeCommand` is your friend ;-) tho, there might even be a command to only restart the extension host

**Comment by shanalikhan** [comment]
>  command to only restart the extension host

Settings Sync open summary in code output channel, while reloading i dont want it to flush but keep it alive and displayed while restarting the extension host only
