### ISSUE TITLE
Syntax highlighting breaks in shell scripts when combination of `` and << is used

### ISSUE THREAD

**Issue by JaPyR** [Microsoft/vscode#57611]
VS Code (starting from line 20):
![vscode](https://user-images.githubusercontent.com/7773301/44854003-b69ab000-ac67-11e8-96d3-5df2080955e2.png)

And the same file in Vim:
![vim](https://user-images.githubusercontent.com/7773301/44854022-c0bcae80-ac67-11e8-88c3-e7b161d0e8f1.png)

File itself:
[bug.zip](https://github.com/Microsoft/vscode/files/2336520/bug.zip)

Version: 1.26.1
Commit: 493869ee8e8a846b0855873886fc79d480d342de
Date: 2018-08-16T18:38:57.434Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by aeschli** [comment]
reproduced with
```sh
LOAD=`abc -s $def<<EOF
set echo ob
EOF`

# comment
```

**Comment by aeschli** [comment]
This issue was moved to atom/language-shellscript#122
