### ISSUE TITLE
Editor rgb nao aparece

### ISSUE THREAD

**Issue by sebastiaoLa** [Microsoft/vscode#57615]
Issue Type: <b>Bug</b>

Quando passa o mouse por cima de um style='background-color:rgb(255,255,255)' o editor de cor pisca mas nao fica na tela tempo suficiente para ser utilizado

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:34:20.517Z)
OS version: Linux x64 4.15.0-33-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (2 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|1, 1, 1|
|Memory (System)|4.97GB (0.40GB free)|
|Process Argv|/usr/share/code/code .|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.5.6
Angular2|joh|6.1.5
Angular-BeastCode|Mik|6.2.16
dotenv|mik|1.0.1
vscode-language-pack-pt-BR|MS-|1.26.3
python|ms-|2018.7.1
vscode-djaneiro|the|1.4.2

</details>

**Comment by sebastiaoLa** [comment]
if you need translation i can do it for you

**Comment by Tyriar** [comment]
Rgb editor does not appear

When you hover your mouse over a style = 'background-color: rgb (255,255,255)' the color editor will blink but it will not stay on the screen long enough to be used

**Comment by rebornix** [comment]
![cp](https://user-images.githubusercontent.com/876920/45103758-7911a900-b0e5-11e8-9941-868be41c779c.gif)

Can you provide more detailed information about how to reproduce?
