### ISSUE TITLE
Terminal: Faulty rewrapping when horizontally resizing

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#57612]
Issue Type: <b>Bug</b>

Verifying #48136

![aug-30-2018 15-26-44](https://user-images.githubusercontent.com/9205389/44854602-4d1ba100-ac69-11e8-9d0e-9c93addf4914.gif)

VS Code version: Code - Insiders 1.27.0-insider (051da84e0f85ec291fd2479b665f5c5c2c60ef72, 2018-08-30T07:34:01.017Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|5.98GB (2.39GB free)|
|Process Argv|C:\Users\chrmarti\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
remotehub|eam|0.2.0
EditorConfig|Edi|0.12.4
vscode-azureappservice|ms-|0.9.0
vscode-azurefunctions|ms-|0.10.0
vscode-azurestorage|ms-|0.4.1
vscode-cosmosdb|ms-|0.8.0
azure-account|ms-|0.4.3
azurecli|ms-|0.4.2
github-issues-prs|ms-|0.9.0
vscode-node-azure-pack|ms-|0.0.3
azurerm-vscode-tools|msa|0.4.2
debugger-for-chrome|msj|4.9.0
vscode-docker|Pet|0.1.0
vscode-open-in-github|sys|1.7.0

</details>

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693

**Comment by PsychoXIVI** [comment]
Not really fixed :| 

![image](https://user-images.githubusercontent.com/23557839/45259225-e6fcef80-b3c7-11e8-959c-7b2cd11688c0.png)

And caused #58256 "likely" :C

**Comment by PsychoXIVI** [comment]
Not really fixed: (newest `master`)
![image](https://user-images.githubusercontent.com/23557839/45259356-2842ce80-b3cb-11e8-9595-c1e309f55acd.png)

**Comment by Tyriar** [comment]
It's not fixed, it is expected to be fixed/improved as part of #45693
