### ISSUE TITLE
[Feature] Please add ability to 'Cut' files/folders in Explorer Tree view

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode#57616]
I've searched through the issue list for this, but either I can't seem to find the right combination of keywords to find a discussion on it, or it's not been discussed. But, I'd like to point out the glaring lack of **Cut** functionality in the file explorer view. I sometimes end up leaving duplicate code in two or more places when I forget to delete a file after copying it to another location.

Please add ability to *Cut* a file, because <kbd>Copy</kbd> + <kbd>Delete</kbd> just doesn't *Cut* it anymore (pun intended).

![image](https://user-images.githubusercontent.com/760112/44856253-97f9e080-ac8a-11e8-8f47-7001d0170e88.png)

**Comment by isidorn** [comment]
There are already extensions which add this -> you can find them in the marketplace.
Nice pun

**Comment by vit100** [comment]
Request by Kumarshar is valid - cut/paste should be in Explorer View, and it is not related to any extensions, it is basic file operation...

**Comment by kumarharsh** [comment]
@isidorn sorry for getting back after this long, but I basically searched the store for extensions. The best I could find was `sleistner.vscode-fileutils`. It's pretty good for what it can offer, but the UX of moving a file is terrible. I have to remember paths just to move a file.

If I may ask, what is the reason for not including this in the core editor? It seems like a very very basic need which many would face. I have twice mistakenly deleted files while juggling with the currently recommended copy-paste-delete process for moving files.

**Comment by vit100** [comment]
> If I may ask, what is the reason for not including this in the core editor? It seems like a very very basic need which many would face. I have twice mistakenly deleted files while juggling with the currently recommended copy-paste-delete process for moving files.

It is just bug - there is cut/paste in menu bar, which is also defective... 
and they don't want to accept it.

**Comment by isidorn** [comment]
@kumarharsh then you can write a new extension which adds just this.
We do not want to add it becuase adding things to the menu will easily make the menu bloated. We prefer to solve issues like this via an extension, such that each user can customize his experience
