### ISSUE TITLE
Debuggee process needs to be stopped twice unexpectedly

### ISSUE THREAD

**Issue by ruslan-bikkinin** [Microsoft/vscode#57626]
Hey guys, we have an issue https://github.com/Microsoft/vscode-react-native/issues/784 in React Native Tools extension related with [new stop debug behavior](https://code.visualstudio.com/updates/v1_26#_improved-stop-debug-behavior) and we need a help from you regarding this because we couldn't find detailed documentation about how to deal with this new behavior. 

According to [these notes](https://github.com/Microsoft/vscode/issues/54384#issue-341439100), If the debuggee has no SIGINT handler, the debuggee will terminate and end the debug session. In our case, this is not happening and to stop debugging we need to click on a stop button twice. 
I am not sure, but seems to be that these new changes in debugging in 1.26 breaks us in the sense that for those debuggers which hasn't support for this should not be affected, but our debugger is affected, unexpectedly. I tested it on Ubuntu and Mac with the same results.

Steps to Reproduce:

1. Open VS Code and install latest version of `React Native Tools` extension
2. Clone [this demo project](https://github.com/ruslan-bikkinin/stop_debugging_repro), open it with VS Code.
3. Start simulator of Android or iOS device/connect real device.
4. Start debugging by choosing "Debug Android" or "Debug iOS".
5. Wait for app launch and debugging panel appearing, then click "Stop" on it.

After debugger process initialized:
![image](https://user-images.githubusercontent.com/30265843/44860850-e5bd1b80-ac7f-11e8-814f-af0f6ce4d3b9.png)

After first time clicking on "Stop" - debuggee isn't stopped, error in debug console appeared:

![image](https://user-images.githubusercontent.com/30265843/44860965-25840300-ac80-11e8-8f3f-80922b5b0101.png)

After second time clicking on "Stop" - debuggee finally terminated

![image](https://user-images.githubusercontent.com/30265843/44860986-37fe3c80-ac80-11e8-84fb-126a504cd74a.png)

Please, let me know if you need any help/information from my side.

 

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:34:20.517Z)
OS version: Linux x64 4.15.0-33-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz (4 x 2856)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.62GB (4.65GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.38
cordova-tools|vsm|1.4.0
vscode-react-native|vsm|0.6.16

</details>

**Comment by ruslan-bikkinin** [comment]
Hi @weinand, after further investigation we figured out that actually, we clone NodeDebugAdapter instance from built-in node-debug2 extension and modify it for our needs so in fact we inherit new behavior as well. So, we made this workaround for now https://github.com/Microsoft/vscode-react-native/pull/789 to get back previous behavior. Seems to be that our issue has resolved since that.

**Comment by weinand** [comment]
@ruslan-bikkinin I'm glad that you were able to resolve this. Thanks.

**Comment by ruslan-bikkinin** [comment]
@weinand anyway, I believe it would be better if docs for extension authors were updated with more detailed information about this new behavior.
