### ISSUE TITLE
Multiple selections in large workspaces decrease performance dramatically

### ISSUE THREAD

**Issue by IanDavey** [Microsoft/vscode#57624]
Issue Type: <b>Performance Issue</b>

0. Use a workspace with several folders/projects (mine is omitted due to sensitive/NDA'd info),
1. Open a file with a lot of repeating text (e.g., a unit test file)
2. Select one piece of repeating text (e.g., `it(`)
3. Ctrl+D until all are selected.  The entire workspace should get progressively and unacceptably slower with each Ctrl+D.
4. Unselect by clicking somewhere else.  It will take a while for workspace performance to be regained.

Notably, Task Manager reports VSCode gobbling up multiple megabytes with each successive selection.

This was fine a month ago.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (16 x 3198)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.91GB (37.92GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
Bookmarks|ale|9.0.3
code-gnu-global|aus|0.2.2
bracket-pair-colorizer|Coe|1.0.59
vscode-eslint|dba|1.5.0
xml|Dot|2.3.2
vscode-npm|fkn|3.3.0
vscode-clang|mit|0.2.2
prettify-json|moh|0.0.3
python|ms-|2018.7.1
cpptools|ms-|0.18.1
csharp|ms-|1.15.2
PowerShell|ms-|1.8.3
java|red|0.29.0

</details>

**Comment by alexandrudima** [comment]
@IanDavey Does this reproduce when disabling all extensions?

**Comment by alexandrudima** [comment]
@IanDavey So... does this reproduce when disabling all extensions? (I'm asking because I'm trying to find the problem)
