### ISSUE TITLE
swipeToNavigate not working

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#57629]
* i have added ` "workbench.editor.swipeToNavigate": true`
* restarted
* do 3-finger swipe after some file navigation -> nothing happens
* do 3-finger swipe in browser -> works

**Comment by bpasero** [comment]
Electron requires this for reasons I do not fully understand (copied from https://github.com/Microsoft/vscode/issues/25325):

**Note**: in order for this to work you need to configure the trackpad in settings as below:

![image](https://cloud.githubusercontent.com/assets/900690/25441163/bad143e4-2aa1-11e7-98d0-26471d105135.png)

**Comment by jrieken** [comment]
A little documentation would be helpful

**Comment by bpasero** [comment]
This is broken since Electron 3 it seems 😱

**Comment by bpasero** [comment]
Reported as https://github.com/electron/electron/issues/19131

**Comment by bpasero** [comment]
I decided to pull out `workbench.editor.swipeToNavigate` given it has been broken for months without someone complaining and given it requires Electron API and cannot be implemented with Web API (as far as I know - if someone can implement this via Web API, fire up a PR).
