### ISSUE TITLE
Do not ship CodeSignSummary files

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#57620]
* Install VS Code user install in a new folder on windows.
* Observe there is a file called CodeSignSummary-b2a55d32-b8b2-4752-a92c-095e4019820b.md
* We should not ship this file

**Comment by joaomoreno** [comment]
Aha! I had a feeling I had seen this: https://github.com/Microsoft/vscode/issues/52982

I only fixed it for the ZIP, didn't even consider the Setup...
