### ISSUE TITLE
Ctrl+O is behaving as Open Folder, which is Ctrl+K, Ctrl+O

### ISSUE THREAD

**Issue by JeffHanna** [Microsoft/vscode#57622]
Issue Type: <b>Bug</b>

The key chord Ctrl+O is behaving as 'Open Folder' in the latest Insider's Build. Shouldn't Ctrl+O be 'Open File'? 'Open Folder' is Ctrl+K, Ctrl+O

VS Code version: Code - Insiders 1.27.0-insider (051da84e0f85ec291fd2479b665f5c5c2c60ef72, 2018-08-30T07:34:01.017Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4820K CPU @ 3.70GHz (8 x 3702)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|47.94GB (35.45GB free)|
|Process Argv|C:\Users\jeff.hanna\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|0.11.1
language-maxscript|ate|1.8.3
autodocstring|njp|0.2.2
chat|kar|0.5.7
python|ms-|2018.7.1
vscode-icons|rob|7.25.0
perforce|sle|3.1.0

</details>

**Comment by isidorn** [comment]
@bpasero this is a clear regression and a clear candidate.
I was trying to be overly smart with context keys and introduced a regression. Now I have gone back to the previous behavior and an if check for platform - please code review it is quite simple. So if we are on mac I will not even call register workbench command which does some things while ignoring the when context (keybinding)
I have verified on windows that this fixes the issue for me.
