### ISSUE TITLE
Copy pasting from HEAD version of a file to original causes bugs

### ISSUE THREAD

**Issue by georgeaf99** [Microsoft/vscode#57632]
- VSCode Version: 1.26.0
- OS Version: OSX 10.13.6

Steps to Reproduce:

1. Open modified file and file at HEAD
2. Copy from HEAD file
3. Paste into modified file
4. Press undo
5. Watch the entire modified file revert to HEAD

Does this issue occur when all extensions are disabled?: N/A

**Comment by dbaeumer** [comment]
Not sure if this is a Git or editor issue. Starting with Git

**Comment by joaomoreno** [comment]
Can you record a screencast of this? I don't really understand what's happening here.
