### ISSUE TITLE
[Python] Code Outline: Loading document symbols

### ISSUE THREAD

**Issue by ablaze8** [Microsoft/vscode#57638]
Issue Type: <b>Bug</b>

- VS Code version:
1.26.1 (Commit: 493869ee8e8a846b0855873886fc79d480d342de)

- Extensions (1)
python  | ms- | 2018.7.1 -- | -- | --

- OS and version: 
Ubuntu 18.04.1 LTS Kernel Linux 4.15.0-33-generic x86_64

- Python version
Anaconda, Inc. Python 2.7.15 (base)

## Actual behavior

I did not notice until later, that VS Code now has code outline / code structure view.When I tried to expand it, it said "Loading document symbols for '<current_file_name>.py"

Screen shot :

[Screenshot](https://i.imgur.com/PP5gUk5.png)

## Expected  behavior

The code outline should parse the currently open code fiel and populate the symbols regardless, if the code file is newly created or it already existed. The code might or might not compile but code outline should be able to enlist all the symbols in order they appear in the code. The user should also be able to sort this list alphabetically.

## Steps to reproduce:
- I tried to open an existing file on an existing project, created with VS Code to start with. 

- Next, I expanded the "Outline" window by clicking on it.

- Not sure it matters, but I gave my consent when VS Code asked me to install/update pylint. It executed this command for me:

```
pip install -U "pylint<2.0.0"
```

## Logs

Nothing in the output or terminal window. Pylint did notice following issues with my code. I do not think those are relevent to this issue, but I have included them here, anyway.

1. W1401:Anomalous backslash in string: '\D'. String constant might be missing an r prefix.
1. W1401:Anomalous backslash in string: '\P'. String constant might be missing an r prefix.
1. W1401:Anomalous backslash in string: '\s'. String constant might be missing an r prefix.
1. W1401:Anomalous backslash in string: '\S'. String constant might be missing an r prefix.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:34:20.517Z)
OS version: Linux x64 4.15.0-33-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2820QM CPU @ 2.30GHz (8 x 2849)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 3, 2|
|Memory (System)|15.58GB (8.53GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.7.1

</details>

**Comment by dbaeumer** [comment]
Since this is python related please report the issue against the ms python extension.

**Comment by ablaze8** [comment]
Thanks. [Done](https://github.com/Microsoft/vscode-python/issues/2468).
