### ISSUE TITLE
Visual Studio Code Terminal presents some character glitches related to formatting

### ISSUE THREAD

**Issue by felipeportella** [Microsoft/vscode#57634]
Using the terminal shows some display glitches like "←[0m" with certain applications like az interactive. This odd characters seems to be related to formatting not being supported ... see example below of a VSCode Terminal:

Microsoft Windows [versão 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Todos os direitos reservados.

C:\Users\bu8n>az interactive
←[?25l←[0m←[?7l←[0m←[J←[0m
←[0mDo you agree to sending telemetry (yes/no)? Default answer is yes: ←[0m

--------------
Extension	Author (truncated)	Version
vscode-service-fabric-reliable-services	ms-	0.1.2
python	ms-	2018.7.1
azurecli	ms-	0.4.2
azurerm-vscode-tools	msa	0.4.2
vscode-docker	Pet	0.1.0

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
