### ISSUE TITLE
Errors when building vscode-docker

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#57635]
- VSCode Version: Insiders latest
- OS Version: MacOS

Related to: https://github.com/Microsoft/vscode/issues/57292

Steps to Reproduce:

``` console
git clone https://github.com/microsoft/vscode-docker
cd vscode-docker && npm install && code-insiders .
```

Press `F5` to launch the extension. The `npm build` task will run as a `preLaunchTask`. You should end up with ~20 errors complaining about various types.  

Open the `Problems` panel, click on a link, the error should go away.  As you click, occassionally you may see an error that indicates it can't find/navigate to the file.  

Eventually, the problems go away by themselves, if you just let VS Code sit for a while.  I have a repro case right now on a Windows machine.

**Comment by mjbvz** [comment]
I tried building on windows but was unable to reproduce this. Does it only happen when you use the old version of TypeScript? When I ran npm install, I got TypeScript 2.9.2 in the workspace

**Comment by chrisdias** [comment]
when i'm in the office we can debug it on one of my machines that exhibits the problem.

**Comment by chrisdias** [comment]
@chrisdias to write up how to remedy the problem in this issue for others...

problems:
- old version of Typescript in workspace
- old version of @types/request 

remedy
- remove node_modules, package-lock.json
- npm install
