### ISSUE TITLE
'dotnet new' cli not recognizing any command options

### ISSUE THREAD

**Issue by mjcataldi** [Microsoft/vscode#57639]
# Issue Type: <b>Bug</b>

## Description
I'm having some issues using the dotnet project template initializer.  I had a previous version of VSCode where this worked fine (the version before 1.26.1), but when the new upgrade to VSCode User Edition came out, this feature stopped working.  I tried using PowerShell, GitBash and Command Prompt in the terminal but none of them work in either the new standard edition or new user edition. 

## Steps to Reproduce
Using a fresh installation of VSCode (either the new standard or user edition):
1. Open VSCode (either regular or administrator mode)
2. Navigate to the terminal (either Command Prompt, Git Bash or PowerShell)
3. Enter 'dotnet new console MyFirstApp' in a directory of choice to scaffold a new .NET project.
4. Next two lines read:
 - 'Specify --help for a list of available options and commands.'
 - 'Unrecognized command or argument 'console''
5. Enter 'dotnet new --help' to reveal available CLI Commands.  None are revealed.

## Machine Specs
VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.87GB (10.53GB free)|
|Process Argv|C:\Users\mcataldi\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|
</details>

<details><summary>Extensions (2)</summary>

|Extension|Author (truncated)|Version|
|---|---|---|
csharp|ms-|1.15.2
spgo|Sit|1.3.2

</details>

<details><summary>Images</summary>

## No Templates Available
<img width="561" alt="notemplatesavailable" src="https://user-images.githubusercontent.com/22238259/44874511-09bd3480-ac61-11e8-9fe0-dccc768b0423.png">

## Standard VSCode with Command Prompt
<img width="482" alt="regularversioncommandprompt" src="https://user-images.githubusercontent.com/22238259/44874513-09bd3480-ac61-11e8-95af-67573763e4d2.PNG">

## Standard VSCode with Git Bash
<img width="563" alt="regularversiongitbash" src="https://user-images.githubusercontent.com/22238259/44874515-0a55cb00-ac61-11e8-8953-41e16bfeffce.PNG">

## Standard VSCode with PowerShell
<img width="463" alt="regularversionpowershell" src="https://user-images.githubusercontent.com/22238259/44874516-0a55cb00-ac61-11e8-8aad-0c4017884c14.PNG">

## User Version of VSCode with Command Prompt
<img width="588" alt="userversioncommandprompt" src="https://user-images.githubusercontent.com/22238259/44874518-0a55cb00-ac61-11e8-87ea-ae67dfe3fd3d.PNG">

## User Version of VSCode with Git Bash
<img width="549" alt="userversiongitbash" src="https://user-images.githubusercontent.com/22238259/44874519-0a55cb00-ac61-11e8-86b6-7a72a2345359.PNG">

## User Version of VSCode with PowerShell
<img width="462" alt="userversionpowershell" src="https://user-images.githubusercontent.com/22238259/44874520-0a55cb00-ac61-11e8-8e0a-6520e672468b.PNG">

</details>

**Comment by joaomoreno** [comment]
This hardly has anything to do with the user setup. Use these two builds to experiment:

- [1.26.1](https://az764295.vo.msecnd.net/stable/493869ee8e8a846b0855873886fc79d480d342de/VSCode-win32-x64-1.26.1.zip)
- [1.25.1](https://az764295.vo.msecnd.net/stable/1dfc5e557209371715f655691b1235b6b26a06be/VSCode-win32-x64-1.25.1.zip)

Which works, which doesn't?
