### ISSUE TITLE
ctrl-shift-e do nothing on ubuntu kde since 1.25.1

### ISSUE THREAD

**Issue by pohmelie** [Microsoft/vscode#57648]
Ubuntu 17.10, kde

1.25.1:
* focus editor
* ctrl+shift+f
* search activated
* focus editor
* ctrl+shift+e
* explorer activated

1.26.0, 1.26.1:
* focus editor
* ctrl+shift+f
* search activated
* focus editor
* ctrl+shift+e
* nothing happend

vscode 1.26.0+ do not detect final «e» key, while 1.25.1 do. Also, this behavior present only when focus is in "editable" elements, so if focus, say, search results, then ctrl+shift+e works fine. 1.26.0 implements some extra binding on ctrl+shift+e: 
``` json
{
  "key": "ctrl+shift+e",
  "command": "workbench.action.quickOpenNavigatePreviousInFilePicker",
  "when": "inFilesPicker && inQuickOpen"
}
```
Maybe this is the reason, but turning this off did not fix issue.

**Comment by VoltiSubito** [comment]
I've observed the same in Fedora Linux.  I've seen this issue in both KDE and Gnome.

**Comment by rightaway** [comment]
Same in archlinux. When the focus is in an editor or search box then this shortcut doesn't work.

**Comment by roblourens** [comment]
Are any of you using non-english keyboards? Or is it possible that the OS is using that keybinding for something else?

**Comment by nealot** [comment]
Seems like a duplicate of https://github.com/Microsoft/vscode/issues/48480

**Comment by roblourens** [comment]
Oh I thought it sounded familiar, thanks @nealot
