### ISSUE TITLE
Kill running terminal processes at restart / close

### ISSUE THREAD

**Issue by flddr** [Microsoft/vscode#57646]
When installing extensions and restarting VS Code, the running terminal processes becoming detached and running in background instead, even when just closing terminal.

Thats annoying, especially when running some more processes, like workers, which will restart killed workers.

Is it possible instead to kill all running (master) processes automatically?

**Comment by Tyriar** [comment]
What's your OS? If it's mac or linux could you test on the latest version of [Insiders](https://code.visualstudio.com/insiders/)? Might be fixed with https://github.com/Microsoft/vscode/issues/56217

**Comment by flddr** [comment]
Oh, well, no, its Windows 10, but i can boot linux tomorrow and check this - thanks 👍

**Comment by Tyriar** [comment]
Ah for Windows we have changes which we hope to solve as part of this issue https://github.com/Microsoft/vscode/issues/45693, stay tuned 😃
