### ISSUE TITLE
TypeScript intermittently shows errors with declaration file

### ISSUE THREAD

**Issue by dfee** [Microsoft/vscode#57647]
- VSCode Version: Version 1.26.1 (1.26.1)
- OS Version: Mac OS 10.13.6

Steps to Reproduce:

1. edit a file that uses information declared in a typescript declaration file
2. open the declaration file and watch the errors disappear, close the declaration and watch the errors re-populate

Does this issue occur when all extensions are disabled?: Yes

![ts](https://user-images.githubusercontent.com/262602/44885217-7a218100-ac74-11e8-8215-e112bec72a80.gif)

**Comment by mjbvz** [comment]
Do you have a [tsconfig.json](https://code.visualstudio.com/Docs/languages/typescript#_tsconfigjson)?

**Comment by dfee** [comment]
I did. I can actually close this now. I had to create a file named `custom.d.ts`. I'm not sure why it *had* to be `custom` though and not a handful of other filenames. Also, I had to move it to the root of my project (not the subfolder where all the markdown files were).
