### ISSUE TITLE
Merge global recently opened list with workspace recently opened

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#57642]
I have files listed in Files > Open Recent that aren't present when I press Ctrl + P and look through the files marked as recently used. I imagine this is an intentional design and that recent files in the file picker are saved with the state of a particular open folder/workspace, so I'd like to request a potential change.

I constantly move between quite a few project/folders at work. I keep a Work Log.txt and a To Do.txt on a network drive so no matter what I'm working on I can quickly get to them to make changes. Each time I open a folder in VS Code I press Ctrl + P and type 'work' in an attempt to bring up my work log. Most of the time it isn't there because I haven't opened the file in this particular workspace, even if I just switched from a workspace where it was open. I end up having to go through the File > Open Recent menu to get to the file.

I recognize the value of having files from Workspace A show up in the file picker for Workspace B. However, I think there may be a compromise where files within a workspace are saved within the workspace state, while files that aren't inside the workspace are saved in a global state of some sort, and both sets of recent files are shown in the file picker. Functionally, it appears this storage separation is already implemented. And selecting File > Open File > More actually _does_ show those files in the file picker. So I'm hoping this request mostly boils down to "show both set of recent files in the file picker at the same time".

**Comment by bpasero** [comment]
@akbyrd the Ctrl+P list includes results from the local workspace while the "Open Recent" is global. Are you suggesting to have a picker for only the recently opened (global) or a setting to merge them all into one?

**Comment by akbyrd** [comment]
I'm suggesting to merge them all into one. Ctrl + P plus all files (not folders) from "Open Recent".
