### ISSUE TITLE
Prueba5 inicio

### ISSUE THREAD

**Issue by rcr2016** [Microsoft/vscode#57644]
Issue Type: <b>Bug</b>

Nexando

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz (4 x 3092)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.69GB (3.22GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.2
npm-intellisense|chr|1.3.0
gitignore|cod|0.5.0
gitlens|eam|8.5.6
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.6.1
start-git-bash|McC|1.2.1

</details>

**Comment by dbaeumer** [comment]
@rcr2016 can you please provide the description and the title in English.

**Comment by dbaeumer** [comment]
I am closing the issue. Will reopen when the title and description in provided in English.
