### ISSUE TITLE
auto format removed space around equal sign in generic default declaration

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#57657]
- VSCode Version: 1.26.1

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/3254987/44893283-32fcb580-ac9f-11e8-82ae-e731c570d6da.png)

```ts
function foo<T extends string[]=[string]>() {

}
// should be
function foo<T extends string[] = [string]>() {

}
```

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#26879
