### ISSUE TITLE
Suggestions not showing when cursor is in snippets

### ISSUE THREAD

**Issue by yubaoquan** [Microsoft/vscode#57652]
- VSCode Version: 1.26.1
- OS Version: Mac OS 10.13.6

Steps to Reproduce:

1. add two snippets into ts snippets: 
```
  "console.infoString": {
    "prefix": "cis",
    "body": "console.info(`$1`)"
  },
  "arrowFunction": {
    "prefix": "af",
    "body": [
      "($1) => {",
      "\t$2",
      "}"
    ]
  },
```
2. open a ts file, type in "cis", see the suggestion of console.infoString
3. type af enter, the arrow function will show up. 
4. type tab to move the cursor into the function body
5. type cis, this time, the suggestion not show up anymore, and what you write is auto selected.

Does this issue occur when all extensions are disabled?: Yes

**Comment by yubaoquan** [comment]
![aug-31-2018 10-09-13](https://user-images.githubusercontent.com/2340296/44888950-4f800880-ad06-11e8-90cf-9f2b3201f68f.gif)

**Comment by jrieken** [comment]
There is a new setting for this: `"editor.suggest.snippetsPreventQuickSuggestions": false`. With that you will get suggestion while tabbing throw snippets.
