### ISSUE TITLE
Disabling keypresses until an extension loads (or until timeout)

### ISSUE THREAD

**Issue by rben01** [Microsoft/vscode#57659]
I use the Vim extension, and it takes a few seconds to load when VSCode starts up. Since I expect Vim to be loaded as soon as VSCode displays an open document, I'll often start typing Vim commands, only to have the characters typed inserted into the open file, which is annoying. Ideally, certain packages critical to editing itself could block user input until loaded (or until a few-second timeout, to avoid blocking VSCode altogether in case of any issues loading the package) to avoid this. Alternatively it might be easier to allow users to specify packages that should block editing until loaded. The goal is to prevent users' keystrokes from doing something other than expected due to missing a not-yet-loaded package.

**Comment by alexandrudima** [comment]
Thanks, I've reached out to the extension -- https://github.com/VSCodeVim/Vim/issues/3016

**Comment by rben01** [comment]
@alexandrudima Thanks!
