### ISSUE TITLE
monaco-tree-row miscalculates height when ASCII color escapes are used.

### ISSUE THREAD

**Issue by hfhchan** [Microsoft/vscode#57656]
Issue Type: <b>Bug</b>

monaco-tree-row in debug console miscalculates height when ASCII color escapes are used.

try

> console.log('\x1B[33;1;4mfoobar[repeat as necessary]foobar\x1B[0m');

versus

> console.log('foobar[repeat as necessary]foobar');

with `foobar` repeated until the first line causes `height:36px` but the content is only actually `height:18px`

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:31:26.156Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
debugger-for-chrome|msj|4.9.0
java|red|0.29.0
vscode-java-debug|vsc|0.12.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.8.0
vscode-maven|vsc|0.10.0

</details>

**Comment by alexandrudima** [comment]
I think this is about evaluating stuff in the debug console.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/53747
