### ISSUE TITLE
Crash-recovery

### ISSUE THREAD

**Issue by r-math** [Microsoft/vscode#57660]
Issue Type: <b>Feature Request</b>

Recover data from crash of the system. 

My experience: i had opened a new file and made some edits on the same (but not saved).  However, my laptop crashed. After the reboot, VS code did not have the file open, nor did any edits.

P.S.:  Something like Chrome's "Restore Tabs" after a Chrome/Windows crash

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.16299

**Comment by Tyriar** [comment]
@r-math hot exit is meant to do this already, it saves all edited files against a folder and restores them when you next open VS Code. Are you sure you opened the same folder up again? Can you share your settings.json file and also check the contents of the `%APPDATA%\Code\Backups` directory which is where the backups are stored.
