### ISSUE TITLE
Add Clear Filter button to settings search

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#57665]
Issue Type: <b>Feature Request</b>

Similar to 'Clear Search Results' in the search viewlet.

VS Code version: Code - Insiders 1.27.0-insider (8a7067a1c7b00df999b4560d393a8fb6e48a2da3, 2018-08-31T05:12:12.237Z)
OS version: Darwin x64 17.7.0

**Comment by roblourens** [comment]
Is that really needed? Keyboard Shortcuts doesn't have one

**Comment by chrmarti** [comment]
Depends on how kind you want to be to the user. ;)

**Comment by roblourens** [comment]
I'm not convinced, and you could use that argument to justify any feature 😁

**Comment by chrmarti** [comment]
That's what I usually do. :p
