### ISSUE TITLE
VS Code not reporting update error in macOS

### ISSUE THREAD

**Issue by doroncy** [Microsoft/vscode#57664]
Issue Type: <b>Bug</b>

VS Code is not updating, it is always stuck on 'Downloading update..."
The extensions are updating fine.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (3.08GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
json2ts|Gre|0.0.6
vscode-paste-and-indent|Rub|0.0.8
jsx|Twe|0.0.1
html-css-class-completion|Zig|1.17.1
better-comments|aar|1.2.6
Bookmarks|ale|9.0.3
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.12
vscode-instant-markdown|dba|1.4.2
githistory|don|0.4.2
vscode-babel-coloring|dza|0.0.4
gitlens|eam|8.5.6
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.35
vscode-npm-script|eg2|0.3.5
copy-relative-path|eno|0.1.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
html-tag-wrapper|hwe|0.2.3
search-node-modules|jas|1.3.0
react-vscode-extension-pack|jaw|0.3.0
Angular2|joh|6.1.5
presentationmode|jsp|1.1.5
intellij-idea-keybindings|k--|0.2.24
ts-extension-pack|loi|0.0.1
vscode-autoprefixer|mrm|2.1.2
vscode-scss|mrm|0.6.2
vsliveshare|ms-|0.3.623
debugger-for-chrome|msj|4.9.0
rxjs-snippets|pko|0.0.2
tsimporter|pmn|1.2.14
polacode|pnp|0.2.2
vscode-icons|rob|7.25.0
sass-indented|rob|1.4.9
angular-follow-selector|san|1.2.0
git-merger|sha|0.4.1
code-settings-sync|Sha|3.1.1
vscode-multiclip|sle|0.1.4
code-spell-checker|str|1.6.10
move-ts|str|1.11.3
quokka-vscode|Wal|1.0.143
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.7.0
ReactSnippets|xab|2.2.0

(2 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Can you run with `code --verbose` and see what errors come up in the console, as you check for updates?

**Comment by DAddYE** [comment]
Same for me, I get:

```
[63928:0831/120912.523828:INFO:CONSOLE(1403)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1403)
[63928:0831/120912.619777:INFO:CONSOLE(1403)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1403)
[main 12:09:14 PM] update#checkForUpdates, state =  idle
[main 12:09:14 PM] update#setState checking for updates
[main 12:09:15 PM] update#setState downloading
[main 12:09:15 PM] UpdateService error:  Could not create temporary directory: Permission denied
[main 12:09:15 PM] update#setState idle
```

**Comment by doroncy** [comment]
```
[main 10:45:26 PM] update#checkForUpdates, state =  idle
[main 10:45:26 PM] update#setState checking for updates
[9032:0901/224526.320462:INFO:CONSOLE(1375)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1375)
[9032:0901/224526.320619:INFO:CONSOLE(1375)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1375)
[9032:0901/224526.320743:INFO:CONSOLE(1375)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1375)
[9032:0901/224526.320819:INFO:CONSOLE(1375)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1375)
[main 10:45:27 PM] update#setState downloading
[main 10:45:39 PM] update#checkForUpdates, state =  downloading
2018-09-01 22:47:56.085 Electron[9032:109556] Download completed to: file:///Users/doroncy/Library/Caches/com.microsoft.VSCode.ShipIt/update.rCyQ399/VSCode-darwin-stable.zip
[main 10:48:16 PM] UpdateService error:  ditto: /Users/doroncy/Library/Caches/com.microsoft.VSCode.ShipIt/update.rCyQ399/VSCode-darwin-stable.zip: Permission denied
[main 10:48:16 PM] update#setState idle
```

**Comment by joaomoreno** [comment]
Please read https://github.com/Microsoft/vscode/issues/7426#issuecomment-277737150

I'll leave the issue open since it appears Code isn't showing the error message in the UI: it should.

**Comment by joaomoreno** [comment]
**Verification:**

1. Download an old version of Code, which has this commit **OR** download a version which has this commit and change the commit in `product.json`.
2. Double click Code to open it
3. Verify with `htop` that the process command line runs in a tmp location and not its real path
4. Attempt to get an update

You should get a nice error message in the workbench.

**Comment by isidorn** [comment]
I got this nice error message

```
Cannot update while running on a read-only volume. The application is on a read-only volume. Please move the application and try again. If you're on macOS Sierra or later, you'll need to move the application out of the Downloads directory. See this link for more information.
```
