### ISSUE TITLE
Exclude non-workspace items from search results

### ISSUE THREAD

**Issue by garyking** [Microsoft/vscode#57663]
Please allow us to exclude non-workspace items from search results.

In my workspace, I opened a file in `/private/var` created by `git show`, and now it appears in search results. I can't remove it from there, with different combinations in `search.exclude`, like `/private/**`, `/private/var/**`, `**/private/**`, etc.

**Comment by roblourens** [comment]
That file is probably still opened in a tab somewhere, if you close it, it should go away.

Or, an extension is involved and is keeping a model of it.
