### ISSUE TITLE
Improve settings editor dropdown layout

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#57662]
Fork of https://github.com/Microsoft/vscode/issues/57447

The dropdown with details in the settings editor needs to account for the size of the details view when sizing and positioning itself, and when it needs to layout in an upwards direction, should (probably) have the details on top.

**Comment by cleidigh** [comment]
@roblourens 
finally back online, FYI my normal schedule ranges from around two to usually around eleven or later.  bit of an odd schedule, just  so you know.  pretty much working on VSC each day.

Is this the first thing you'd like me to work on for September?  I assume no commits during endgame other than the critical bugs?

**Comment by roblourens** [comment]
We've created the release branch for 1.27 now, so commits to master are ok and will go into the September release.

**Comment by roblourens** [comment]
I think this is the best thing to work on right now

**Comment by cleidigh** [comment]
If this looks good to you, I will clean and merge.

<img width="960" alt="2018-09-03-23-35-17" src="https://user-images.githubusercontent.com/25272315/45008704-21364d80-afd2-11e8-9fe0-27d48fe32638.png">


<img width="960" alt="2018-09-03-23-36-30" src="https://user-images.githubusercontent.com/25272315/45008728-3d39ef00-afd2-11e8-9fc2-ab700e7b5f78.png">

**Comment by roblourens** [comment]
I think that looks great! 😁

**Comment by cleidigh** [comment]
yeah, until it doesn't...  ran into a very odd list focus issue, seems there several ways where the list gets focus as opposed to a list item.  Result is a focus ring on the whole list. I got subscriptions done but still working this. Just so you didn't think I disappeared...  Once I bang my head some more I'll post something.
