### ISSUE TITLE
experimentalDecorators works fine in one root workspace but warning  in multi-root workspaces 

### ISSUE THREAD

**Issue by lcoder** [Microsoft/vscode#57667]
- VSCode Version: 1.26.1 (1.26.1)
- OS Version:macOS High Sierra10.13.6 (17G65)

Steps to Reproduce:
I had set "javascript.implicitProjectConfig.experimentalDecorators": true
in my personal settings and `project.code-workspace` files
but I still get warnings
![image](https://user-images.githubusercontent.com/5225853/44899215-be278b00-ad33-11e8-8dce-31a1f6fe4603.png)
when I change to one root wokspace. There is no warnings anymore.
![image](https://user-images.githubusercontent.com/5225853/44899505-8a009a00-ad34-11e8-8895-106bd9d620b9.png)

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by mjbvz** [comment]
Please file this issue against the vue extension. Our built-in js/ts don't support vue files
