### ISSUE TITLE
Command Palette not finding Settings (UI)

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#57666]
* we have an entry 'Preferences: Settings (UI)'
* open command palette
* type 'settings' -> settings (ui) entry shows
* type 'settingsu'
* 🐛 nothing shows

<img width="642" alt="screen shot 2018-08-31 at 09 27 31" src="https://user-images.githubusercontent.com/1794099/44898783-28bed380-ad00-11e8-9315-c563c7f6ab86.png">
<img width="457" alt="screen shot 2018-08-31 at 09 27 35" src="https://user-images.githubusercontent.com/1794099/44898784-28bed380-ad00-11e8-8fcf-c303ad0b4dd4.png">

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/1964
https://github.com/Microsoft/vscode/issues/27636
