### ISSUE TITLE
Test: New extension/Marketplace query support to filter extensions 

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#5767]
Test plan item for #4849.

- [x] any - **@sandy081**

Searching for extensions is now a live query against the Marketplace.

- Search for popular extensions and make sure they appear
- Install & update extensions
- The results in quick open are paged (page size 50) and loaded on demand. Play around with the scrolling, make sure they always load eventually.

**Comment by joaomoreno** [comment]
Closed as we will only deliver this in May.

**Comment by sandy081** [comment]
Looks good. Closing.
