### ISSUE TITLE
"Show matching extensions" too much to the right

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#57676]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/9205389/44905597-d3d88880-ad12-11e8-9fa1-02f313fc21aa.png)

VS Code version: Code - Insiders 1.27.0-insider (8a7067a1c7b00df999b4560d393a8fb6e48a2da3, 2018-08-31T05:12:12.237Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron --user-data-dir /Users/chrmarti/Development/repos/tmp/user2 --extensions-dir /Users/chrmarti/Development/repos/tmp/ext2|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azure-account|ms-|0.4.3

</details>

**Comment by roblourens** [comment]
Let's use https://github.com/Microsoft/vscode/issues/57601 to think about the placement of this in September
