### ISSUE TITLE
Settings: opening settings.json from new UI should handle filter better

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#57673]
Since settings.json does not support the @ modified, it should probably be removed:

![image](https://user-images.githubusercontent.com/900690/44905348-164d9580-ad12-11e8-992d-a1889d4da657.png)

I started in the UI with that filter and then used the action to go to editor.

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/57619
