### ISSUE TITLE
Automated smoke test fails in  CSS - verifies that warning becomes an error once setting changed

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#57678]
OS: Windows

I looked into this and the smoke test fails adding the setting into the settings editor and hence the warning never turns into an error.

What I noticed is that the search box got focused when opening / revealing the settings editor in insider. In stable the right and side text editor is focused.

**Comment by dbaeumer** [comment]
@aeschli FYI

**Comment by bpasero** [comment]
Reproduces for me as well but only on Windows.

**Comment by dbaeumer** [comment]
Running it manually works as expected.
