### ISSUE TITLE
files.watcherExclude is not working..

### ISSUE THREAD

**Issue by SivaThiyagarajan** [Microsoft/vscode#57675]
I need to avoid the src/assests folder from being watched(to avoid the change detection on that folder), So i tried like
	"files.watcherExclude":{
		"**/src/assets/**": true,	
                   "**/src/**": true,	
	}

But nothing is working.

**Comment by bpasero** [comment]
You will have to use "**" to match on absolute paths. So try with `/src/assets/**`

**Comment by SivaThiyagarajan** [comment]
I tried with 
	"files.watcherExclude":{
		"/src/assets/**": true
	}
still the refresh is happening.
