### ISSUE TITLE
Debug toolbar is still displayed when the program already exited

### ISSUE THREAD

**Issue by WangNanN** [Microsoft/vscode#57670]
- VSCode Version: 1.26.1
- OS Version: ubuntu-16.04.3-desktop-amd64
- C# Extension version: v1.16-beta4

Steps to Reproduce:

1. Create a dotnet core console app
2. Open this app with VSCode
3. Start debugging

Expected behavior:
Debug toolbar should not be displayed

Actual behavior:
The program already exited, but the debug toolbar is still displayed
![image](https://user-images.githubusercontent.com/32088084/44900372-fc727980-ad36-11e8-80d4-c9bb5181bd34.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
And also try with latest vscode insiders https://code.visualstudio.com/insiders/
