### ISSUE TITLE
The scroll bar of output panel still scrolls when it turns to locked

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/vscode#57681]
Issue Type: <b>Bug</b>

Repro Steps:

1. Make sure there have information on the output panel.
2. Switch the lock icon to the locked state.
3. Check whether the scroll bar of the output panel can be scrolled or not.

Expect:
The scroll bar of output panel can't be scrolled.
Actual:
The scroll bar of output panel can be scrolled.

VS Code version: Code - Insiders 1.27.0-insider (051da84e0f85ec291fd2479b665f5c5c2c60ef72, 2018-08-30T07:34:01.017Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|16.00GB (4.11GB free)|
|Process Argv|C:\Users\AzureTest\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-azureappservice|ms-|0.9.1
vscode-azurefunctions|ms-|0.10.1-alpha
vscode-azurestorage|ms-|0.4.1
vscode-cosmosdb|ms-|0.8.1-alpha
azure-account|ms-|0.4.3
vscode-docker|Pet|0.1.1-alpha

</details>

**Comment by sandy081** [comment]
@v-xianya What do you mean by `The scroll bar of output panel can be scrolled.` ?

Are you able to scroll the scroll bar manually or it scrolls automatically?

**Comment by v-xianya** [comment]
The scroll bar of output panel can be scrolled manually when the lock icon is be locked.

**Comment by sandy081** [comment]
The lock action is to lock the scroll bar to scroll automatically when the content comes in. You can always scroll manually.

**Comment by v-xianya** [comment]
When the lock icon is unlocked, the scroll bar does not appear to scroll automatically.
