### ISSUE TITLE
Use webpack for all big extensions

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#57680]
We can ship less and gain more. This is a simple sample that enables webpack for extensions: [`extension.webpack.config.js`](https://github.com/Microsoft/vscode/blob/1097b5e9ed81d5f9241648774b35048be168c203/extensions/emmet/extension.webpack.config.js#L10). All configs should inherit from the shared config, get in touch with me if something doesn't work.

* it is important to name the file `extension.webpack.config.js`
* try this with `npx webpack --config extensions/<your-extension>/extension.webpack.config.js`
* update the `.vscodeignoe` file, exclude the `out` folder and config-file
* run a full product build via `yarn run gulp vscode-darwin` etc before pushing 

Extensions that should be webpack'ed:

* [x] markdown @mjbvz 
* [x] extension-editing @chrmarti 
* [x] npm @egamma 
* [x] configuration-editing @jrieken
* [x] php @aeschli @roblourens 
* [x] merge-conflict @jrieken @chrmarti 
* [x] search-rg @roblourens 
---
* [ ] 💪 node2 @roblourens
* [ ] 💪 node @weinand or @roblourens

**Comment by roblourens** [comment]
How about the debug extensions? It's more complicated because I'd have to webpack the vscode-chrome-debug-core npm module but node-debug2 is much bigger than search-rg.

**Comment by jrieken** [comment]
sure, everything that reduces the bundles size it good

**Comment by jrieken** [comment]
https://github.com/Microsoft/ApplicationInsights-node.js/pull/426 is about making the AppInsights module (which most extension depend on via vscode-extension-telemetry) webpack friendly. Having that will reduce the bundle size drastically.

**Comment by weinand** [comment]
@jrieken how should extensions living outside of VS Code source tree "inherit from the shared config"?

**Comment by jrieken** [comment]
Yeah, that's the question. The config can be copied but more tweaks will be required because some build trickery that we do in VS Code won't be available to you.

**Comment by weinand** [comment]
Ok. I will look into that in October...
