### ISSUE TITLE
Update Status should refresh automatically

### ISSUE THREAD

**Issue by beastdestroyer** [Microsoft/vscode#57689]
Issue Type: Bug
No matching issues found

- VSCode Version: 1.27.0-insiders (Users, but also happens with Global)
- OS Version: Windows 10 1803 17134.228

Steps to Reproduce:

1. Get an update, and click install
2. Don't click off the menu, just hold it there
3. When the update is ready to install, the menu will still stay `Installing Update...`

Here is a screenshot to demonstrate:
![update](https://user-images.githubusercontent.com/30497573/44913869-764e3700-ad26-11e8-94c7-af2e859a1476.png)

Expected:
Afetr it finished installing, it should have changed to `Restart to update`

Does this issue occur when all extensions are disabled?: Yes

**Comment by beastdestroyer** [comment]
Not relevant, and first time seeing the bot actually reply instantly without page reload 0_0

**Comment by joaomoreno** [comment]
Closing as won't fix. It's just not a common enough scenario. Once closed and reopened, the menu shows the correct action.
