### ISSUE TITLE
Search and replace should focus in search not replace

### ISSUE THREAD

**Issue by euphoricz** [Microsoft/vscode#57693]
Issue Type: <b>Bug Report</b>

Clicking ctrl+h brings up the search and replace popup however focus is in the replace text box, not the search.  I always end up shift tabbing to get back to the search textbox first.

Not a big deal, just an annoyance.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 6.1.7601

**Comment by roblourens** [comment]
You should see it focus the search box if there is no text persisted in there. If there's text there it should focus the replace box. If that's what you see, this is by design.

You can tab back or ctrl+f to focus the search box.

**Comment by euphoricz** [comment]
I guess it is just an odd workflow to me because I have used visual studio for years and that is not how visual studio handles the same scenario.  

Once there is text in the search and replace boxes there is never not text in those boxes unless you manually remove it.  

I would bet if you did a usability study you would find that when a user presses ctrl+h they want to change the text in the search box first, tab, then replace the text in the replace box 99% of the time.

Out of curiosity, after you have completed a search and replace why would you want to slightly change your replace text to search and replace the same search string?  It doesn't make any sense to me because the search string changed after you did the last search and replace so it won't find any results... either way you have to tab back to the search text box before you can continue.

Like I said, it isn't a big deal, this is a throw away issue, however some would say that usability can make or break an application.  Just trying to help.

If it is by design then I shall close it.

**Comment by roblourens** [comment]
I think it's optimized for the case where the user selects some text and presses ctrl+h, the selected text goes to the search input, and the cursor goes to replace. I think it's worth considering not moving the focus in this case where the user presses ctrl+h and there is some random old text in the search input.

Find widget/search should match, thoughts @rebornix ?

**Comment by rebornix** [comment]
We have two similar issues talking about this case https://github.com/Microsoft/vscode/issues/32617 and https://github.com/Microsoft/vscode/issues/37102 . IMO the request makes sense, especially when you have Find opened once, and then 

* Put the cursor on a word, do not select
* Run Ctrl-H to open Replace dialog
* The previous query is populated into the search box, and we move the focus into the replace box.

@roblourens I agree with you that we can at least optimize for this case.
