### ISSUE TITLE
Previewing large diff prevents diffing other files for about 10-20 seconds

### ISSUE THREAD

**Issue by borekb** [Microsoft/vscode#57697]
- VSCode Version: 1.26.1
- OS Version: macOS High Sierra, Windows 10

Steps to Reproduce:

1. Have a version-controlled project with a large file, for example, `yarn.lock` or `package-lock.json` are usually good suspects to reproduce this.
2. Make some change in that large file, e.g., install new npm dependency.
3. Make some other, "normal" change to some source file so that you have two changes to commit.
4. In the VCS sidebar, click the large file (e.g., `yarn.lock`) – VSCode opens the diff editor.
5. Click the other file, notice that the much smaller diff is not being opened for quite a while (can be somewhere between 10-20 seconds on my machine).

VSCode is responsive during this time but clicking files in the VCS panel does nothing, or appears to. I've been observing this issue for many versions of VSCode and finally decided to report it :)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
@borekb Can you please give the files that reproduce or some files very similar in shape (if you cannot share the original files) ?

**Comment by borekb** [comment]
@alexandrudima I just found out that it's most likely caused by some extension as I can't reproduce it in Insiders. Good luck to me finding out which one it is as I have quite a few of them:

My VSCode stable extensions:

Extension|Author (truncated)|Version
---|---|---
spellright|ban|2.5.32
emojisense|bie|0.4.1
markdown-preview-github-styles|bie|0.1.3
vscode-tailwindcss|bra|0.1.11
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.20.0
githistory|don|0.4.2
gitlens|eam|8.5.6
remotehub|eam|0.2.0
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.39
vscode-npm-script|eg2|0.3.5
LogFileHighlighter|emi|2.4.1
markdown-table-formatter|fcr|1.3.2
php-debug|fel|1.12.5
auto-rename-tag|for|0.0.15
vscode-pull-request-github|Git|0.1.5
rest-client|hum|0.19.1
crane|Hvy|0.3.8
vscode-github|Kni|0.30.0
goto-last-edit-location|kri|0.2.1
git-tree-compare|let|1.3.0
terraform|mau|1.3.4
dotenv|mik|1.0.1
vscode-docker|Pet|0.2.0
code-settings-sync|Sha|3.1.2
vscode-scss-formatter|Sib|1.0.2
vscode-markdown-link-suggestions|Tom|11.0.1
vscode-terminal-here|Tyr|0.1.1
es-quotes|vil|0.2.6
quokka-vscode|Wal|1.0.148
wallaby-vscode|Wal|1.0.93
markdown-all-in-one|yzh|1.6.0

My Insiders extensions:

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.1.3
vscode-markdownlint|Dav|0.20.0
gitlens|eam|8.5.6
EditorConfig|Edi|0.12.4
code-settings-sync|Sha|3.1.2
vscode-markdown-link-suggestions|Tom|11.0.1
markdown-all-in-one|yzh|1.6.1

**Comment by alexandrudima** [comment]
@borekb This is pretty easy to figure out. Just run F1 > Show running extensions and press the record button. You might need to restart in order to run the extension host with debugging turned on.

Then, do the steps that reproduce for you and the extension with the most CPU time will show up. You can also save the profile if you want to and attach it here.

**Comment by borekb** [comment]
Thanks, I'll try that.

**Comment by borekb** [comment]
Hmm, after reproducing the behavior and running profiler at the same time, this is the result after roughly 10 seconds. I.e., "nothing":

![image](https://user-images.githubusercontent.com/101152/45647273-c0287280-bac5-11e8-8863-cb39d51e5910.png)

VSCode is perfectly responsive at all time, I just hear CPU fan spinning faster and clicking on other files in SCM view does nothing.

Any other suggestions on where to look?

**Comment by borekb** [comment]
Will do. By the way, I have many more extensions as shown in https://github.com/Microsoft/vscode/issues/57697#issuecomment-421488863, the screenshot is a small part of it.

**Comment by alexandrudima** [comment]
One way I would approach this would be to open VS Code and do the minimal steps necessary to reproduce. From your extension list, it looks like you opened markdown files, JSON files and TS/JS files before reproducing. Every time you do something, it is more likely more extensions get activated and begin to do something ...

**Comment by borekb** [comment]
@alexandrudima Hi, he're a profile of the following situation: no tabs open, only two files changed in SCM panel: `package.json` and `yarn.lock`. I started profiling, clicked `yarn.lock`, seen the diff open, clicked `pakcage.json`, it did not open so I stopped profiling and exported this file:

[CPU-20180926T065255.265Z.cpuprofile.txt](https://github.com/Microsoft/vscode/files/2418454/CPU-20180926T065255.265Z.cpuprofile.txt)

**Comment by borekb** [comment]
BTW, I see the same behavior not only in the SCM panel but also e.g. with the [Git Tree Compare](https://marketplace.visualstudio.com/items?itemName=letmaik.git-tree-compare) extension which also opens diffs.

**Comment by alexandrudima** [comment]
@borekb In the CPU profile you have attached, there is a lot of CPU usage in a method named `getGitProviderOwnerAndRepositoryFromGitConfig`. Almost like it is called in a loop or something:

<img width="761" alt="screen shot 2018-10-08 at 15 24 30" src="https://user-images.githubusercontent.com/5047891/46611510-515f9780-cb0e-11e8-9c4d-34e0a661ff52.png">

After searching for the long method name on GitHub, I had a hit [here](https://github.com/KnisterPeter/vscode-github/blob/bf407f787e30c43559e64fb8022ef9b4ba6e4294/src/git.ts#L126)

So it would be best to reach out to @KnisterPeter and create an issue directly at https://github.com/KnisterPeter/vscode-github .

**Comment by borekb** [comment]
@alexandrudima Thanks! Will do.
