### ISSUE TITLE
JSON seems to keep diagnostics around when document closes

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#5769]
<img width="515" alt="screen shot 2016-04-25 at 16 50 37" src="https://cloud.githubusercontent.com/assets/1794099/14787922/ea9a27f6-0b05-11e6-8755-3314a42dfe27.png">

I cann't get that error away, tho the document is closes (not showing in working files set)

**Comment by aeschli** [comment]
@dbaeumer Dirk, what is the expected behavior? Do we only show diagnostics of documents that are open? Do I need to clean diagnostics on the server when I see a text document is closed?

**Comment by dbaeumer** [comment]
@aeschli IMO we need to rethink this strategy here. Currently the workbench removes the markers for closed documents which causes issues. However if the service for some reason recomputes them they are added back.

This is something we need to tackle in May to get a better consistent story here.

**Comment by dbaeumer** [comment]
This will be addressed with a new marker story that is targeted for June.

**Comment by dbaeumer** [comment]
WE decided on the following story. Single file markers should be removed when a file closes. Moving to @aeschli to fix.
