### ISSUE TITLE
Code folding with unindented #define/#undef is broken

### ISSUE THREAD

**Issue by Flamefire** [Microsoft/vscode#57696]
Issue Type: <b>Bug</b>

When using the following C++ code and completely dedenting the `#define` and/or `#undef` VSC adds folding marks to them.

While the folding for `#define` is (kinda) OK the folding for the `#undef` folds the following members which is wrong.

Furthermore both break the folding of the surrounding class: Code will only be folded till the `#define/#undef`. Once those 2 lines are indented by more than 1 space the folding of them disappears making it work for the outer scopes. However a multi-line `#define` can then not folded

```
class Foo{
  int x;
#define FOO(x) int x
  FOO(bar);
  FOO(baz);
#undef FOO
  float yy;
};
```

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:34:20.517Z)
OS version: Linux x64 4.15.0-33-generic

**Comment by aeschli** [comment]
The folding strategy that you are seeing is based purely on the indentation of lines. A folding region starts when a line has a smaller indent than one or more following lines and ends when there is a line with the same or smaller indent.

To be smarter and to, for example, understand #ifdef syntax, this would have to be provided by a language extension. I  see that the cpptools already has a request for this: https://github.com/Microsoft/vscode-cpptools/issues/407.

Please upvote that feature.
