### ISSUE TITLE
Edit of adjacent ranges does not work.

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#577]
_From @vilic on October 31, 2015 17:29_

For example:

```ts
edit.delete(new Range(1, 1, 1, 2));
edit.delete(new Range(1, 2, 1, 3));
```

This issue applies to other operations like `replace` as well.

_Copied from original issue: Microsoft/vscode-extensionbuilders#72_

**Comment by seanmcbreen** [comment]
_From @vilic on November 9, 2015 1:42_

@seanmcbreen Any comment on this?

**Comment by seanmcbreen** [comment]
_From @jrieken on November 9, 2015 8:55_

@alexandrudima  will know

**Comment by seanmcbreen** [comment]
@vilic just mailed Alex to ensure he has seen this.

**Comment by seanmcbreen** [comment]
_From @alexandrudima on November 14, 2015 0:49_

@vilic Yeah, the edits are not allowed to touch. As a workaround, why not do a single edit instead?

```javascript
edit.delete(new Range(1, 1, 1, 3));
```

**Comment by seanmcbreen** [comment]
_From @vilic on November 14, 2015 1:32_

@alexandrudima The ranges are results of other code, transforming these edits to a single one means for every series of edits I'll need to ensure they do not touch, and if so, merge them properly. Which could be non-trivial work.

Is there a reason why edits of adjacent ranges are not allowed?

**Comment by seanmcbreen** [comment]
_From @alexandrudima on November 16, 2015 17:18_

@vilic It is some debt left over from how multiple cursors were implemented. I still need to migrate some internal code that I think still depends on this limitation, then I can relax the touching check.

**Comment by seanmcbreen** [comment]
_From @vilic on November 17, 2015 1:30_

@alexandrudima Thanks for clarification~ Feel free to close this issue if you want it closed for now. :)

**Comment by alexandrudima** [comment]
Let's track this in #761
