### ISSUE TITLE
Bash Scripting Feature Requests

### ISSUE THREAD

**Issue by jasonislike** [Microsoft/vscode#57709]
Hello, I am aware that you are not to request multiple features within a request but, I am anyway.

I create many complex bash scripts and would like to request some new features that would provide general quality of life improvements. I find it annoying having to go back and fourth between multiple editors when dealing with bash scripts and VS tends to be the more suitable lightweight editor for creating bash scripts when not on a console.

**1. Include ".bsh" for a file extension type for shellscripts.** 
- I am aware that it can be done by adding in the file associate like shown below, but generally speaking, it should be included.
`"files.associations": { "*.bsh": "shellscript" },`

**2. Syntax Coloring for positional arguments, variables, functions, and common plugins should have syntax coloring to make them standout**
- Code such as $1 and $var
- Plugins such as "openssl" and "keytool"
`myFunction $1`
`myVar=$1`
`echo $myVar`
`functionName() { ... }`
`openssl req -new -sha256 -nodes -out exmple.csr -newkey rsa:4096 -keyout example.key -config <( cat $File1 )`
`keytool -printcert -file $1`

**3. Folding block comments**
- Multiple lines of comments (2 or more) should fold/unfold
`#Fold Start`
`#Words`
`#Fold End`

- This should also be true for "echo's" over multiple lines
`echo "Fold start here...`
`words that are still in the quotes but on new line...`
`words that are still in the quotes but on new line...`
`end of fold" >> example.txt`

**4. Formatting. I currently use the "Bash Beautify" extension to format my code, generally speaking, it is okay. I am curious why no shellscript/bash formatting tool in generally included with this.**

**Comment by dbaeumer** [comment]
You are correct that you shouldn't request multiple feature in one issue. Especially since the once you request affect multiple owners solutions.

1. to my knowledge `.bsh` is the extension for BeanShell not Bash shell. Am I missing something.

2 - 4: these are extension opportunities. Most of our language support comes through extensions and is not built into the core of VS Code.

**Comment by dbaeumer** [comment]
@jasonislike please ping in this issue if I misunderstood (1.) and I will reconsider the issue.
