### ISSUE TITLE
Why cancel this design？

### ISSUE THREAD

**Issue by Sakuiro** [Microsoft/vscode#57703]
![3b3f1f77fae8f7441d3c482d3cbfec56](https://user-images.githubusercontent.com/28353930/44925946-75e38980-ad82-11e8-82e5-bb86da9e413c.jpg)
i love it.but,
today,it's change.
![image](https://user-images.githubusercontent.com/28353930/44925987-9875a280-ad82-11e8-9d89-4cc531c52c37.png)

**Comment by ngyikp** [comment]
Try changing `window.titleBarStyle` in settings to `custom`?

**Comment by bpasero** [comment]
The custom menu will become default in the release after the next release.
