### ISSUE TITLE
Escape key while dragging selection should leave selection unchanged

### ISSUE THREAD

**Issue by kfasick** [microsoft/vscode#57708]
Issue Type: <b>Bug</b>

Escape key while dragging selection should leave selection unchanged just like it does with (traditional apps on) Windows.
Repro:
Select something and begin to drag it. Keep mouse pressed.
Decide it was better left where it was. Keep mouse pressed.
Tap Escape key.
Observe content drops as if the mouse button were released.
Expect mouse button to release, but content to fall back where it was before beginning the action.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (7.00GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Users\v-kafasi\Microsoft\FastTrackAnalytics-DataPlatformTeam - Performance Tuning\20180814\1 p_load_FastTrackTenantService_Extended\p_load_FastTrackTenantService_Extended - top memory consumer.sqlplan|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.59
vscode-markdownlint|Dav|0.20.0
docs-article-templates|doc|0.1.2
docs-markdown|doc|0.1.4
docs-preview|doc|0.3.12
xml|Dot|2.3.2
gitlens|eam|8.5.6
azure-arm-template-helper|ed-|0.0.17
git-project-manager|fel|1.6.1
Ionide-FAKE|Ion|1.2.3
Ionide-fsharp|Ion|3.25.3
Ionide-Paket|Ion|1.12.0
dupchecker|jia|0.0.9
kusto-syntax-highlighting|jos|1.0.1
vscode-regexp-preivew|le0|0.0.3
rainbow-csv|mec|0.4.2
vscode-azurestorage|ms-|0.4.1
vscode-cosmosdb|ms-|0.8.0
mssql|ms-|1.4.0
azure-account|ms-|0.4.3
azurecli|ms-|0.4.2
csharp|ms-|1.15.2
github-issues-prs|ms-|0.9.0
PowerShell|ms-|1.8.3
wordcount|ms-|0.1.0
vsliveshare|ms-|0.3.623
vsliveshare-audio|ms-|0.1.32
vsliveshare-pack|ms-|0.1.2
azurerm-vscode-tools|msa|0.4.2
material-icon-theme|PKi|3.5.3
ruby|reb|0.20.0
snake-trail|ric|0.6.0
vscode-filter-json|ric|1.0.0
vscode-sort-json|ric|1.13.0
glassit|s-n|0.1.3
usql-vscode-ext|usq|0.2.14
vscodeintellicode|Vis|1.0.3
markdown-all-in-one|yzh|1.6.0
vscode-open-in-github|ziy|1.3.5

(2 theme extensions excluded)

</details>

**Comment by christopherkang** [comment]
I've reproduced this on Windows, too. Is this issue applicable to Mac/Linux?
