### ISSUE TITLE
VB script appearing in my index.html files

### ISSUE THREAD

**Issue by SirG97** [Microsoft/vscode#57701]
Issue Type: <b>Bug</b>

I keep seeing something like this in my html files, I clear it and after some time, it appears again after the closing body tag
<SCRIPT Language=VBScript></SCRIPT>

**Comment by Tyriar** [comment]
Does it happen when you disable extensions by closing all windows and running `code --disable-extensions`?

**Comment by SirG97** [comment]
I've disabled my extension now to know if it's the problem, though I
recently got a notification that my installation is corrupt. I will reply
here if I notice another development

sirg97

**Comment by aeschli** [comment]
The built-in HTML extension does not automatically enter any tags such as `<SCRIPT Language=VBScript></SCRIPT>`
