### ISSUE TITLE
feat(editor): make grammer highlights more visible

### ISSUE THREAD

**Issue by thefliik** [microsoft/vscode#57719]
Apologies if this is a duplicate, but I couldn't find anything.

VS code will helpfully highlight linting / grammar errors in a file with a green squiggly line. The location of errors in a file also shows up as a green "notch" in the scroll bar area (also very helpful).

Sometimes though, a highlighted grammar error is very small--maybe a single character. In these cases I find it very hard to visually scan a file to find the highlighted section. I oftentimes find myself relying on the scroll bar to show me where an error is by
1. clicking on a line
2. inspecting the scrollbar area to see where the cursor indicator is in relation to the green grammar error "notch" indicator.
3. Do a "guestimate" of how many lines down the error is in the file, and click on that line.
4. Inspect the scrollbar area to see if the cursor is on the same line as the grammar error.
   - If yes, closely inspect the current line to find the grammar error.
   - If no
     - Is the grammar error above the current line? If so, do a "guestimate" of how many lines up the error is in a file and click on that line. Repeat step 4.
     - Is the grammar error below the current line? If so, do a "guestimate" of how many lines down the error is in a file and click on that line. Repeat step 4.

Obviously this workflow isn't ideal. It would be very helpful if grammar errors showed up in the line number gutter area on the left side of an open editor pane (in a similar manner to how line additions / deletions receive an indicator in the line number gutter area of a file). This would make visually scanning a file to find a grammar error much easier, as I could use the scroll bar indicator to jump to the approximate area of the grammar error, and then scan the line number gutter area to find the line the grammar error is on.

Sorry if this is a confusing explanation. I don't know of a "proper" name for these UI components.

Thanks!

*Search terms:
grammar error visibility; linting error visibility; syntax error visibility*

**Comment by lambainsaan** [comment]
One thing we can do is on hover over the errors listed in the scrollbar, it zooms into that section, and allows the user to pick a position to go to, all the errors in the vicinity of the hovered area shows up in the zoomed-in panel, the user can click on some point in the zoomed-in section, which takes the user to that position. Even I have a similar workflow, and it's very cumbersome.
