### ISSUE TITLE
German: "File->Open file" menu text contains "&&" characters, and CTRL+O does not work

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode#57712]
Issue Type: <b>Bug</b>

Expected: Datei öffnen…  (with CTRL+O shortcut)
Actual: Datei &&öffnen…   (with no working shortcut)
![image](https://user-images.githubusercontent.com/6913354/44932777-9c220e80-ad1b-11e8-93e3-530dd3f17587.png)

VS Code version: Code - Insiders 1.27.0-insider (47d0584301d16d4efd6618f6f33ef14099c92561, 2018-08-29T05:18:47.523Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E31230 @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.96GB (3.53GB free)|
|Process Argv|C:\Users\stephwe\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe --folder-uri file:///c%3A/Repos/AzureCR/vscode-docker|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-azure-storage-utility|Com|0.0.2
vscode-markdownlint|Dav|0.20.0
vscode-eslint|dba|1.5.0
tslint|eg2|1.0.38
rest-client|hum|0.19.1
csharpfixformat|Leo|0.0.74
vscode-mocha-sidebar|mat|0.20.18
vscode-antlr4|mik|2.0.4
vscode-language-pack-de|MS-|1.27.1
azure-account|ms-|0.4.3
vscode-docker|Pet|0.1.0

</details>

**Comment by bpasero** [comment]
@StephenWeatherford does it reproduce with the latest insider build too from yesterday?

**Comment by StephenWeatherford** [comment]
Nope, it's fixed, thanks.
