### ISSUE TITLE
target snippets to sub-syntax, define sub syntax based on file name

### ISSUE THREAD

**Issue by leejroberts** [Microsoft/vscode#57717]
I'd like a way to create a sub-syntax for Minitest and Rspec files in Ruby. Tests and specs are indicated with _test or _spec in the file name, and I need a way to target that for snippets without adding them globally to my Ruby syntax. Ideally, the syntax would extend the core ruby syntax. Is this already possible or could this feature be added?

**Comment by aeschli** [comment]
You could do that programmatically in an extension
- If it's just about adding snippets, then your extension could create completion proposals for these snippets when it detects that you are in a `_test` or `_spec` file and at the right location.
- if this also involves syntax highlighting, you probably have to define a new language.
