### ISSUE TITLE
"typescript.preferences.importModuleSpecifier": "non-relative" doesn't work

### ISSUE THREAD

**Issue by zpdDG4gta8XKpMCd** [microsoft/vscode#57718]
Visual Studio Code - Insiders
Version: 1.27.0-insider (system setup)
Commit: 1097b5e9ed81d5f9241648774b35048be168c203
Date: 2018-08-31T10:38:54.277Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

TypeScrtipt: 

![image](https://user-images.githubusercontent.com/937933/44937917-b672e100-ad49-11e8-976a-0f7796e32130.png)

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/937933/44937865-6b58ce00-ad49-11e8-8a02-5c807cb49589.png)

![image](https://user-images.githubusercontent.com/937933/44937943-dbffea80-ad49-11e8-9149-7290da911552.png)

Expected:

![image](https://user-images.githubusercontent.com/937933/44938008-487ae980-ad4a-11e8-891c-447985860339.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Can you please share your `tsconfig.json`

**Comment by aleksey-bykov** [comment]
```json
{
    "compilerOptions": {
        "strict": true,
        "noFallthroughCasesInSwitch": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "noImplicitReturns": true,
        "outDir": "./scripts",
        "rootDir": "../",
        "baseUrl": "../",
        "jsx": "react",
        "lib": [
            "esnext",
            "dom"
        ],
        "target": "es2017",
        "module": "amd",
        "types": []
    }
}
```

**Comment by mjbvz** [comment]
Please share a small example project that demonstrates this issue
