### ISSUE TITLE
RelativePattern should be removed from documentation

### ISSUE THREAD

**Issue by lextm** [Microsoft/vscode#57713]
https://code.visualstudio.com/docs/extensionAPI/vscode-api#RelativePattern

It seems to be obsolete experimental API. Should be removed to avoid confusion.

**Comment by jrieken** [comment]
The [`GlobPattern`](https://github.com/Microsoft/vscode/blob/45f782ae951584b0a7fb92e2971a5e269b91f32f/src/vs/vscode.d.ts#L1844) uses that
