### ISSUE TITLE
Golang rune type not colored like others

### ISSUE THREAD

**Issue by willfaught** [Microsoft/vscode#57725]
- VSCode Version: 1.26.1 (1.26.1) 493869ee8e8a846b0855873886fc79d480d342de
- OS Version: macOS High Sierra 10.13.6 (17G65)

Please see https://github.com/Microsoft/vscode-go/issues/1894.

Does this issue occur when all extensions are disabled?: Yes

**Comment by ramya-rao-a** [comment]
@willfaught Which theme are you using? I tried all the themes that ship out of the box, and I don't see the issue

**Comment by willfaught** [comment]
The default theme.

**Comment by db47h** [comment]
uh... looks like that was fixed in 98d3a0b3f238682131a448f33fd580d090f8e8e8 for #56515, but it's not available yet in vscode stable.

**Comment by ramya-rao-a** [comment]
And it was me who fixed it! I can't believe I couldn't recall that.

Thanks again @db47h 

@willfaught Please try our [Insiders](https://code.visualstudio.com/insiders) or wait for an update to the stable bits which should be out sometime this week
