### ISSUE TITLE
Search Results show in 'Other files' w/ workspace bucketting

### ISSUE THREAD

**Issue by grork** [Microsoft/vscode#57720]
- VSCode Version: 1.27-insiders
- OS Version: Windows 10 10.0.17234.228

Steps to Reproduce:

1. Have multiple workspaces that are in a file system provider sourced URI
2. Have one of the workspaces in `protocol:/`, and another in `protocol:/bob`
2. Have a search provider that will provide the search results, rather than  having VS code do the search
3. Have a search result under the `protocol:/` workpace

Expected behaviour:
The result will show under the correct workspace grouping

Actual result:
It shows under the 'Other Files' section. This is because here: https://github.com/Microsoft/vscode/blob/a0ce75fffb8ad610d7effffca711e5b2a93f486d/src/vs/workbench/parts/search/common/searchModel.ts#L696

It uses `fsPath`, so with assumptions in the matching logic, it doesn't find a match and gives up

**Comment by roblourens** [comment]
Verification - run https://github.com/Microsoft/vscode-extension-samples/tree/roblou/searchProviderExample/fsprovider-sample, have two memfs folders in the workspace. Do a text search, verify that the results are shown in their folders correctly.
