### ISSUE TITLE
[html] Allow to drag CSS or JS files into HTML to generate <link> tag or <script> tag

### ISSUE THREAD

**Issue by 1264072** [Microsoft/vscode#5772]
- VSCode Version: 1.0.0
- OS Version: Windows 10

Everytime I want to drag a CSS or JS file into HTML, it always open that file whenever I click on it. I had tried to config my workspace setting but can't find thing that I need.

**Comment by aeschli** [comment]
This is difficult to implement as it would have to become a new language service.
No plans for this at the moment.

**Comment by dalper01** [comment]
I was wondering why this is so difficult when Visual Studio has had this feature for ever
