### ISSUE TITLE
Unable to override PATH via `env` option when creating a terminal...

### ISSUE THREAD

**Issue by busticated** [Microsoft/vscode#57724]
hi there :wave:

i'm trying to create a terminal via the `window.createTerminal()` api. i want this terminal to use a custom $PATH env var. my custom $PATH would basically take the user's existing and prepend a single value to it - aim being to have _my_ binaries sourced _first_ when running in this terminal.

here's what i'm doing:

```javascript
createTerminal({ name, env: { [PATH.key]: PATH.value } })
```

where `[PATH.key]` resolves to the platform-specific name (e.g. `PATH` on *nix, `Path` on windows) and `PATH.value` is the platform-specific lookup list.

these values are known-good as i use them in the tasks i provide via `registerTaskProvider()` (using `Task`, `ShellExecution`, and related) and things work as expected over there.

after launching my custom terminal, the output of `echo $PATH` (macOS) returns a string formatted as such: `<default os paths><my injected paths><user's paths>` where `<my injected paths>` ends up being my single addition plus `<user's paths>` (so those end up duplicated).

i was hoping to simple override the existing `PATH` with mine. is there a way to do this?

- VSCode Version: v1.26.1
- OS Version: macOS v10.13.6

thanks 🙏

**Comment by Tyriar** [comment]
Your terminal launch scripts are probably filling in the os paths and user paths. You could try launch with `bash --noprofile --norc`?

**Comment by busticated** [comment]
@Tyriar 🤔 

> Your terminal launch scripts are probably filling in the os paths and user paths.

well, yes? i noted above that:

> my custom $PATH would basically take the user's existing and prepend a single value to it

so, my `PATH` object on macOS looks like:

```javascript
{
    key: 'PATH',
    value: '/path/to/bins-i-want-to-expose:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/path/to/user-added-bins'
}
```

which can be seen as: `<my injected paths><default os paths><user's paths>` (but is simply the result of _prepending_ a value to the existing PATH)

i then create my terminal as such: `createTerminal({ name, env: { [PATH.key]: PATH.value } })`

running `echo $PATH` within the newly spawned shell, i see:

`/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/path/to/bins-i-want-to-expose:/path/to/user-added-bins:/path/to/user-added-bins`

which can be seen as: `<default os paths><my injected paths><user's paths><user's paths>`

creating my terminal with:

```javascript
createTerminal({
    name,
    env: { [PATH.key]: PATH.value },
    shellArgs: ['--noprofile', '--norc'],
    shellPath: '/bin/bash'
})
```

then running `echo $PATH` within the newly spawned shell, i see:

`/path/to/bins-i-want-to-expose:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/path/to/user-added-bins`

or more simply: `<my injected paths><default os paths><user's paths>`

which is exactly what i want :tada:

but of course **now any other customizations the user may have made via their `~/.profile` are lost.**

so 🤷‍♂️

**Comment by Tyriar** [comment]
> i was hoping to simple override the existing PATH with mine. is there a way to do this?

The only way to do this is to prevent your profile or rc file from running, that's how the default paths are getting injected/rearranged.

> but of course now any other customizations the user may have made via their ~/.profile are lost.

Note that the terminals inherit VS Code's path which is created by launching a login shell:

https://github.com/Microsoft/vscode/blob/2eb78b54ed3c2f31205b5f11d023bef49cab9fc2/src/vs/code/node/shellEnv.ts#L27

So when the task is run, you will still get those customizations, you will just need to relaunch VS Code to have the VS Code environment pick them up.

**Comment by busticated** [comment]
ah, nice - thanks @Tyriar 🙏 :+1:
