### ISSUE TITLE
remote debug is super slow

### ISSUE THREAD

**Issue by cscetbon** [Microsoft/vscode#57721]
- VSCode Version: 1.26.1
- OS Version: MacOS 10.13.4
- Extension : Go 0.6.89

Steps to Reproduce:

1. remote debug a pod in Kubernetes
2. test manually using dlv client (to connect to the remote dlv server running in the pod) and see that it takes 2 seconds to go to next step
3. test with VSCode (which also uses the remote dlv server running in the pod) and see that it takes 40 seconds to go to next step

When I'm in debug mode I noticed that I also need to click twice for an operation (next step, restart) to work.

**Comment by weinand** [comment]
Please file this issue against go extension.
