### ISSUE TITLE
Tree View Controls, Address bar, with focus, enhancements.

### ISSUE THREAD

**Issue by wesleyolis** [Microsoft/vscode#57738]
Its as simple as providing and address bar for a treeview at the top of the treeview control space.
Think good old windows address bar in explorer, one can always see the current path one is in.
Currently on is not able to know the context of were one is in the tree view of the workspace folder,
because so many modules include modules folder and other recursively. Also src and output folders for js have identical folder structure, so one ends up editing files in the wrong place often due to navigation taken one to the output of a build.

[Image of Workspace folder TreeView Address Bar](https://drive.google.com/file/d/1mPdIGLiQ2fmOIwCYNNLtOIo39GuOkW8j/view)

Please also introduce all the keyboard relevant shortcuts for a full set of all options.
For example:
Ctrl + up: moves to the next item in the tree that is the parent of the current.
Ctrl+ down would do the same.
Ctrl + left, would close the current path, place the parent item under focus.
Ctrl + right, would open the current path.

Ctrl + Alt + up / down, is modifier which will then jump to the next item, that doesn't begin with the same letter.
Ctrl + Alt + Left/Right, is a modifier which will then jump to the next item, that doesn't begin with same 2 first letters, which allows for more granularity of navigation control.

Ctrl + Backspace, navigate back though the navigation history.
Ctrl + Shift + Backspace navigate forward though the navigation history.

Ctrl + Shift + Enter, Will set the address bar into focus on the current item.

Obviously on should support page up. page down, home and end.

Ctrl in the address bar, should jump between path identifiers.

Overall layout navigation for VSCode.
Ctrl +Shift+Alt plus an arrow key, navigation, should allow navigation, which respect to the current control in focus, if arrow left, it will set the control to the left in as potential for focus, by highlight it area, with orange color. Opun hitting enter the control will then be put into focus. This allows me to simple navigate on the keyboard to the control I want then hit focus, to trigger all the UI stuff.

The tree view should also refocus the tree on the current file being edit.

If you want example of focus, you can download Albion and check out how the focus thing works.
[Albion GIS](https://sites.google.com/site/wiprogamming/Home/albion)

**Comment by dbaeumer** [comment]
VS Code has support for a breadcrumb in the editor.

**Comment by bpasero** [comment]
Yeah, enable it via `"breadcrumbs.enabled": true`
