### ISSUE TITLE
Debug console does not allow empty input string to be executed

### ISSUE THREAD

**Issue by daviwil** [Microsoft/vscode#5773]
In PowerShell, it's fairly common for the user to press Enter in response to a prompt on the screen.  For example, there could be a prompt for the user's choice which allows a default value to be accepted by pressing Enter.  There's also the scenario where the user might be asked for a string of input where an empty string may be valid or indicate the use of a default.

Could the debug console allow empty inputs to be sent to the debug adapter?  Sending it across as a null or empty string would be fine.

Thanks!

---

- VSCode Version: 1.0.0
- OS Version: Windows 10

Steps to Reproduce:

1. Install the PowerShell extension
2. Open workspace path `c:\Users\<yourusername>\.vscode\extensions\ms-vscode.PowerShell-0.5.0\examples`
3. Select file `DebugTest.ps1` and press F5
4. Pause the debugger while executing
5. In the Debug Console, execute the following line `Read-Host -Prompt "Enter a string"`
6. When the prompt is displayed, try to press Enter or press the spacebar and then press Enter.
7. Observe that the prompt does not proceed.  Only after typing a non-empty string can the prompt be completed.

**Comment by daviwil** [comment]
Woohoo, thanks!

**Comment by weinand** [comment]
In node-debug the empty string now evaluates to an "undefined"...
