### ISSUE TITLE
Nodejs debugger infinite restart

### ISSUE THREAD

**Issue by Lev09** [microsoft/vscode#57732]
Issue Type: <b>Bug</b>

Create a simple node app and run debugger without installing needed node packages for project.
After starting debugger it will run project, print error in console and restart, and so on.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:34:20.517Z)
OS version: Linux x64 4.4.0-134-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz (4 x 2861)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 0|
|Memory (System)|7.65GB (2.25GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.5.0
githistory|don|0.4.2
gitlens|eam|8.5.6
vscode-npm-script|eg2|0.3.5
vscode-great-icons|emm|2.1.41
auto-close-tag|for|0.5.6
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.0.15
search-node-modules|jas|1.3.0
react-vscode-extension-pack|jaw|0.3.1
vsliveshare|ms-|0.3.623
debugger-for-chrome|msj|4.9.0
react-proptypes-intellisense|OfH|1.0.3
JavaScriptSnippets|xab|1.7.0
ReactSnippets|xab|2.2.0

</details>

**Comment by weinand** [comment]
how does your launch config look like?

**Comment by MechanicalHuman** [comment]
I have the same problem with `nodemon` and `pm2-dev`.

```json 
 {
      "type": "node",
      "request": "launch",
      "name": "nodemon",
      "runtimeExecutable": "nodemon",
      "program": "${workspaceFolder}/bin/api.js",
      "restart": true,
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen"
    }
```

**Comment by connor4312** [comment]
With `"restart": true,`, that's working as designed -- the debugger was asked to restart the program when it exited.

Haven't received any more info from the original poster, thus closing.
