### ISSUE TITLE
Add "execute next line", not just "step over next line"

### ISSUE THREAD

**Issue by steinhh** [Microsoft/vscode#57735]
When debugging & stopping at a breakpoint, I often want to see things evolve as lines are executed one by one. So I'd like to have an "execute next line" or "step through next line" button, not just a "step over [next line]" button

**Comment by weinand** [comment]
I don't understand what you mean.
VS Code surfaces exactly the stepping actions available from the underlying debugger.

**Comment by steinhh** [comment]
Ah, it seems I simply misunderstood the meaning of "step over", which in my ears sounds like "skip next line and move to the one after that". But it actually _does_ execute the next line. Wish it was called "execute next line" or "step through next line", but that's not a big deal for _me_ anymore :). Closing the issue.
