### ISSUE TITLE
Unable to debug in VSCode

### ISSUE THREAD

**Issue by hanct** [Microsoft/vscode#57739]
Node js used: v10.8.0
electon : v2.0.7
VScode IDE: v1.25.1
OS: window 10

Hi all,

My debug of an electron application in VSCode was successful with this launch.json configuration

    {
                "type": "node",
                "request": "launch",
                "name": "Electron Main Process 1",
                "runtimeExecutable": "${workspaceRoot}/src/node_modules/.bin/electron",
                "runtimeArgs": ["."],
                "cwd":"${workspaceFolder}/src"
    }

Then I refactor this launch.json configuration to make it look like this as shown below: I merely refactor the command to execute to the package.json, that is , the configuration "start": "electron ."   in the package.json.

    {
                "type": "node",
                "request": "launch",
                "name": "Electron Main Process",
                "runtimeExecutable": "${workspaceRoot}/nodeJS/npm",
                "runtimeArgs": ["start"],
                "cwd":"${workspaceFolder}/src"
    }

The debugging no longer works and i get a popup box indicating "Cannot connect to runtime process, timeout after 10000 ms - (reason: cannot connect to the target: connect ECONNREUSED 127.0.0.1:36236).

I was tried to resolve this for days, but still can't resolve it.

**Comment by weinand** [comment]
This problem results from the way how npm passes arguments to scripts.

If you look closer at the output in the debug console then you will see that based on your launch config VS Code runs the following command :
```
npm start --inspect-brk=5569
```
but npm just runs this:
```
electron
```
So the debug port is missing and VS Code times out when it tries to attach to the debug port.

For details see this:
https://stackoverflow.com/questions/11580961/sending-command-line-arguments-to-npm-script

This launch config should work:
```
{
            "type": "node",
            "request": "launch",
            "name": "Electron Main Process",
            "runtimeExecutable": "${workspaceRoot}/nodeJS/npm",
            "runtimeArgs": ["start", "--" ],
            "cwd":"${workspaceFolder}/src"
}
```

**Comment by weinand** [comment]
BTW, this recipe might be of interest to you:
https://github.com/Microsoft/vscode-recipes/tree/master/Electron

**Comment by hanct** [comment]
Thank weinand! u solved my days of problem! I have previously noticed that vscode IDE actually append the --inspect-brk=5569 to my npm start.  And I thought since it added -- for me already, there is no need for me to add another --, in the runtimeArgs.   But i was wrong.

The receipt u send will be useful to me, cos i am not only wanted to debug the Main Process, but also the Renderer Process.
