### ISSUE TITLE
Extension failed to download everytime.

### ISSUE THREAD

**Issue by iamRavikantSingh** [Microsoft/vscode#57733]
Issue Type: <b>Bug</b>

whenever i try to download a extension for visiual code it starts downloading but then failed to install .
then i have to download it manually and install it this way it works fine.
i am using vs code on macOS X high sierra in mackbook pro

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (8.81GB free)|
|Process Argv|/Users/ravikantsingh/Downloads/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-great-icons|emm|2.1.41
Angular-BeastCode|Mik|6.2.16
python|ms-|2018.7.1
cpptools|ms-|0.18.1
csharp|ms-|1.15.2

</details>

**Comment by sandy081** [comment]
@iamRavikantSingh Can you please provide following information

- What error do you see?
- Please set the log level to Trace using `Set Log Level` command and try installing the extension again. Please share us the `Shared Process` logs. You can find them in Output Panel
