### ISSUE TITLE
Horizontal scrollbar

### ISSUE THREAD

**Issue by alifrontend499** [Microsoft/vscode#57737]
Can we scroll horizontally using our mouse scroller like I do on my laptop using the touchpad?
it would be so helpful if I can do it on pc or mac to using the mouse. you can add something like pressing ctrl + s + mouseScroll if possible.

**Comment by alexandrudima** [comment]
Not sure what you mean. You can use <kbd>Shift</kbd> + mouse wheel to scroll horizontally. Do you mean something different?

**Comment by alifrontend499** [comment]
It's kinda same as what I wanted
