### ISSUE TITLE
How to shield CSS units from being automatically lowercase when formatting

### ISSUE THREAD

**Issue by youshao** [Microsoft/vscode#57731]
Using the px2rem plugin, some units have to be written as Px so that it doesn't automatically become rem. The current problem is that when I write Px, the formatting code will automatically become lowercase Px.

**Comment by beastdestroyer** [comment]
Well if you don't mind disabling formatting as a whole for css, you can add this into your `settings.json`: 
```json
"[css]": {
  "editor.formatOnSave": false
}
```
That will only disable formatting (as a whole) on CSS, but if you rely on formatting CSS but just to solve this issue, this won't work. You could of course do the classic Replace All trick:
- Press Ctrl/Cmd Shift F to open Find and Replace dialogue. 
- In the top box, type `px`; in the second box, type `Px`
- Click the replace all button (or if you want to be more specific, keep pressing Next [the arrow buttons next to the box] and pressjng Replace when necessary) 

That should get all px into Px

**Comment by aeschli** [comment]
Please file the issue against the extension that provides the formatter (There's no built-in css formatter in VSCode)
