### ISSUE TITLE
Find -> Select All

### ISSUE THREAD

**Issue by cjbarth** [Microsoft/vscode#57741]
Sublime has a feature where I can perform a find and then choose to select all occurrences which will result in multiple cursors in my document. I can then start typing to replace, or do any other global navigation. I use this feature all the time for cleaning up copy-paste logs, code snips, etc. Please add this to VS Code.

**Comment by alexandrudima** [comment]
Duplicate of #14836

You can press `Alt+Enter` in the find input.
