### ISSUE TITLE
TextDocumentContentProvider renders gibberish with 1.26.1 update

### ISSUE THREAD

**Issue by Almenon** [Microsoft/vscode#57749]
- VSCode Version: 1.26.1
- OS Version: Windows 10

In the [AREPL ](https://github.com/Almenon/AREPL-vscode)extension I update TextDocumentContentProvider frequently whenever I get a result/print from my python backend. This used to work fine but as of 1.26.1 update it has some serious problems. The updates are throttled to once every 50 ms but even with once every 500 ms I see problems.

Steps to Reproduce:

1. Download AREPL extension
2. Activate AREPL (control-shift-q)
3. Paste the following in:

```python
print(1)
print(2)
print(3)
print(4)
print(5)
print(6)
```

In this case on the first run you get **_complete gibberish_**

> link rel=" hce/"3A/Ue="text/css"shc/f="file:///c%3A/Usess/aalmenon/.vsclme/pxt-nsions/.1menon.4rmpl-0d1.4amedia//ythonPreview.css"jsonRenderer.js"> scri t rcad>l///c%3A/Urs/a/.vs/extenson/mn.arepl-0.1.4/di/jsRener.j">scrit on o d f(){ srVar={}; jenrr=edjon.s_cs('+', '-') defadl icd="ferokbtwd, orrding .ae _se w_ o_ vil(2) >Tweet #arepl .set_max_st g_lengdcunt.getEeenByI("reslts").apndChd(jnRnder(urVar); } 
PrintOtut:1 2 3 4 5 6 0 s

> brdiv id="foor" pmargn0x;repissu ⭐| talkongitter | Twet#arepl bdy>

On the second run you get less gibberish:

> s ip > i i i oprgrm <> < style="i:p"> ort an rettptuleoarelcode> < e="htesaceeamorreetsrateme re"https://git.o" a estteointeeeuthe dieo i ttcoe p Print737 0tp:68<2v91id="printd">1"results"> 0 ms

> report an issue | ⭐ rate me ⭐ | talk on gitter | Tweet #arepl

And on the third run and all runs after that it works fine.

I know this is not a problem with my extension because it only started happening after the v1.26.1 release.  But I have no idea what could have caused the issue - I looked through the [1.26.1 issues](https://github.com/Microsoft/vscode/milestone/76?closed=1) and didn't see anything suspicous.

**Comment by dbaeumer** [comment]
@Almenon can you please provide the links to the screen shots.

Might be a dup of https://github.com/Microsoft/vscode/issues/51789

@mjbvz assigning to you since the extension seems to use a WebView via the content provider.

**Comment by mjbvz** [comment]
Your extension doesn't seem to create a valid html document (no docstring, trailing divs, potentially other issues). Please make sure the html content is valid, fully compliant html

**Comment by Almenon** [comment]
@mjbvz Oops, sorry about that.  I haven't tested it with python 3.7 yet.  I think I know why you are getting an error so I should be able to have a fix for that shortly.

**Comment by Almenon** [comment]
@mjbvz I just released a new version.  It has python 3.7 support and fully compliant html, among other unrelated fixes.

**Comment by Almenon** [comment]
I looked through the relevant webview files (extHostDocumentContentProvider, webview-pre.js, webviewElement.ts) and none of them got changed between 1.26 and 1.26.1

In fact, none of the files inside the webview folder got changed in the time frame between 1.26 and 1.26.1 (august 13th - august 16th).  The last change to the webview folder before august 16th was a merge on the 6th, but that would have gone out with 1.26

But I used a mac with a old version of vscode and my extension worked fine, so there definitely was a problem introduced somewhere 🤔 

I think I'll try switching to the new [webview](https://code.visualstudio.com/docs/extensions/webview). Maybe that will help.

**Comment by Almenon** [comment]
Looks like the new webview works :D

**Comment by mjbvz** [comment]
Ok, thank you for taking a look. Yes I recommend using a webview going forward.

Since I have not see this reported reported for any other extensions using the `previewHtml` api and since the previewHtml api is now deprecated, I'm going to close this issue as wont-fix

**Comment by Almenon** [comment]
@mjbvz I didn't know previewHtml is now deprecated - is this in any of the documentation yet?

I didn't see anything in the docs and vscode-extension-samples still has a sample with previewHtml
https://github.com/Microsoft/vscode-extension-samples/tree/master/previewhtml-sample
https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands

**Comment by mjbvz** [comment]
Extension example show it as deprecated now :) https://github.com/Microsoft/vscode-extension-samples/tree/master/previewhtml-sample

Will also update documentation for next release
