### ISSUE TITLE
Don't show release notes

### ISSUE THREAD

**Issue by IDIDIR** [Microsoft/vscode#57740]
When I click on "Help - Relesae notes", an empty tab opens.
I completely uninstalled the VSC with all regedit's parametres, it was useless.
Win 8.1 x64
Version: 1.26.1
Commit: 493869ee8e8a846b0855873886fc79d480d342de
Date: 2018-08-16T18:38:57.434Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by dbaeumer** [comment]
@chrmarti not sure if this is you.

**Comment by joaomoreno** [comment]
@IDIDIR Are you behind a proxy?

**Comment by IDIDIR** [comment]
No, I do not use a proxy.

**Comment by joaomoreno** [comment]
If you open Developer Tools, and try to open the Release Notes, there should be a Network request coming in, can you see its details?

**Comment by IDIDIR** [comment]
![ssds](https://user-images.githubusercontent.com/21132031/45017093-7614ab00-b048-11e8-87a7-8a20e97ac17a.png)

**Comment by joaomoreno** [comment]
What about in the Console tab, is there anything there?

**Comment by joaomoreno** [comment]
No, in the Devtools, there is a `Console` tab at the top. Can you check it?

**Comment by IDIDIR** [comment]
![111](https://user-images.githubusercontent.com/21132031/45144147-1997c400-b1df-11e8-8ec1-20e2147efdd4.png)

**Comment by joaomoreno** [comment]
@mjbvz Any ideas why the webview would not render? The user appears to have correctly fetched the release notes.
