### ISSUE TITLE
重新打开后不直接显示之前打开的项目

### ISSUE THREAD

**Issue by wyxnl** [Microsoft/vscode#57746]
所需的数据太大，无法直接发送。我们已经将其写入剪贴板，请粘贴。

**Comment by Almenon** [comment]
Google Translation (翻译): Do not directly display previously opened items after reopening

The data required is too large to be sent directly. We have already written it to the clipboard, please paste it.

**Comment by bpasero** [comment]
@wyxnl can you provide more info in english?
