### ISSUE TITLE
Try after installed

### ISSUE THREAD

**Issue by transdigiware** [Microsoft/vscode#57755]
Issue Type: <b>Bug</b>

looking another launge for support extension

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 6.1.7600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz (4 x 3599)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.94GB (0.99GB free)|
|Process Argv|C:\Users\USER\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
code-gnu-global|aus|0.2.2
path-intellisense|chr|1.4.2
EditorConfig|Edi|0.12.4
vscode-npm-script|eg2|0.3.5
php-debug|fel|1.12.5
auto-rename-tag|for|0.0.15
code-runner|for|0.9.4
cpptools|ms-|0.18.1
csharp|ms-|1.15.2
debugger-for-chrome|msj|4.9.0
vscode-icons|rob|7.25.0
sass-indented|rob|1.4.9
vscode-maven|vsc|0.10.0
JavaScriptSnippets|xab|1.7.0

</details>

**Comment by dbaeumer** [comment]
@transdigiware please provide more information about what is not working for you, best with steps on how to reproduce the issue.

**Comment by dbaeumer** [comment]
Closing the issue. It is not actionable without additional information. Will reopen when information is available.
