### ISSUE TITLE
Setting default `executable` in ShellExecutionOptions causes tasks provided via registerTaskProvider() to fail...

### ISSUE THREAD

**Issue by busticated** [Microsoft/vscode#57757]
hi again :wave:

i'm trying to customize the shell in which the tasks i provide via `TaskProvider` will run. as a test, i'm creating a `ShellExecution` ([docs](https://code.visualstudio.com/docs/extensionAPI/vscode-api#ShellExecution)) object as such:

```javascript
new ShellExecution('make', ['clean'], { executable: '/bin/bash' });
```

when i run using this configuration, i get:

```
/bin/bash: make clean: No such file or directory
The terminal process terminated with exit code: 127
```

however, when i remove `executable: '/bin/bash'` from my `ShellExecutionOptions` object, my task runs as expected.

based on the default setting `"terminal.integrated.shell.osx": "/bin/bash"`, my assumption was that setting the same value via the `executable` field would yield the same results.

- VSCode Version: v1.26.1
- OS Version: macOS v10.13.6

**Comment by dbaeumer** [comment]
If you specify a shell you also need to pass the arguments necessary to execute a single command. In the case of bash this is `-c`. If you use `PowerShell` then this is `-Command`. So you also need to specify the args. I have updated the documentation for this. 

Let me know if this works for you now.

**Comment by busticated** [comment]
@dbaeumer that works, thanks!

is `{ executable: '/bin/bash', shellArgs: ['-c'] }` sufficient to properly run the shell or do i also need to specify `ShellQuotingOptions`? 

actually, can you help me better understand [ShellQuotingOptions](https://code.visualstudio.com/docs/extensionAPI/vscode-api#ShellQuotingOptions)? specifically:

1. when should they be used?
2. what drives the settings choices? iow, are they tuned to specific use-cases or are they based solely on which shell you are trying to run?
3. can you point me at the current defaults? (e.g. if `/bin/bash` is the default `executable` on macOS & Linux, what are the corresponding `ShellQuotingOptions`?)
4. can you point me at any example usages out in the wild?

**Comment by dbaeumer** [comment]
That is sufficient. Regarding quoting: A good article about quoting in shells is this for bash http://wiki.bash-hackers.org/syntax/quoting and this for PowerShell: https://ss64.com/ps/syntax-esc.html

If you don't specify anything the task runner will pick the right quoting characters based on the OS / shell. For Linux / Mac I don't know any shell that uses a different quoting style than the one defined by bash. And for Windows we pick the right one for PowerShell and CMD.exe. You only need to configure this if you use a fancy shell that has different quoting styles.

OK to close

**Comment by busticated** [comment]
thanks @dbaeumer 👍 

fwiw, i found what appear to be the default `ShellQuotingOptions ` here:
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/tasks/electron-browser/terminalTaskSystem.ts#L76

> OK to close

yep 👍

**Comment by dbaeumer** [comment]
Good. Closing then.
