### ISSUE TITLE
Highlight HTML/CSS/JS in different language

### ISSUE THREAD

**Issue by imperez** [Microsoft/vscode#5775]
I'm not sure if this is already possible but the documentation seems scarce about how to do this. I created a Language extension for the Smarty templating language. This has a special tag called `literal` which when used should show the natural syntax highlighting. Currently this doesn't work at all and greys out a lot of the "literal" code. 

Is there a way to do what the tag is intending in VSCode? Also see my attached images to see how VSCode handles it vs Netbeans.

![7caf2742-0311-11e6-906d-610bb6967c54](https://cloud.githubusercontent.com/assets/481144/14794612/fe747f82-0af2-11e6-8bba-31bc66ba701a.jpg)
![dbc99042-0310-11e6-88c0-e9eeccdfcc50](https://cloud.githubusercontent.com/assets/481144/14794613/fe78f44a-0af2-11e6-8169-e98e84a5dce4.jpg)

**Comment by aeschli** [comment]
In your language's grammar you can include grammars of other languages.
See https://manual.macromates.com/en/language_grammars, 12.3 Rule Keys, 'include'.

You can see that in action in a jade.file:
```jade
script(type="text/javascript").
  if (10 == 10) {
    alert("working");
  }
```
where the coloring of the 'if' clause is driven by the javascript grammar.
Check the Jade grammar `vscode/extensions/jade/syntaxes/Jade.tmLanguage` and look for` source.js
`
