### ISSUE TITLE
Output window is showing incorrect UI

### ISSUE THREAD

**Issue by wizchick7** [Microsoft/vscode#57758]
Issue Type: <b>Bug</b>

Install VSCode Insider
Install C/C++ extension
Reload VSCode
Go to Debug -> Start Debugging
Go to Output section
Expected: See the print statements from C++ program
Actual: See attached image

VS Code version: Code - Insiders 1.27.0-insider (1097b5e9ed81d5f9241648774b35048be168c203, 2018-08-31T10:38:54.277Z)
OS version: Windows_NT x64 10.0.18213

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (7.99GB free)|
|Process Argv|C:\Users\cimoli\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.18.1

</details>

![output](https://user-images.githubusercontent.com/1242893/44949847-dc05f600-adee-11e8-9327-a5ad4cf50b77.png)

**Comment by dbaeumer** [comment]
@wizchick7 please file the issue against the cpp extension here: https://github.com/Microsoft/vscode-cpptools
