### ISSUE TITLE
No menu overflow causes problems with narrow windows/long titles

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#57756]
![image](https://user-images.githubusercontent.com/2193314/44949529-6eef6200-ade8-11e8-89f0-ddde02a4191f.png)

It can also look like this after alt+f, right to terminal menu

![image](https://user-images.githubusercontent.com/2193314/44949535-81699b80-ade8-11e8-9fa6-34359dd8643b.png)

**Comment by bpasero** [comment]
Isn't this fixed with the new scrollbar in menus?

**Comment by sbatten** [comment]
@bpasero this is the second part where the top-level menu needs a more menu when the window width is too small. PR incoming...

**Comment by bpasero** [comment]
Had to revert https://github.com/Microsoft/vscode/commit/fa87e67ebfd6b8014ba697ddbc6c2d6c0e2cb970

See https://github.com/Microsoft/vscode/issues/64292

**Comment by sbatten** [comment]
closed by #64365
