### ISSUE TITLE
Se necesita agregar mas opciones

### ISSUE THREAD

**Issue by WilsonGrave** [Microsoft/vscode#57759]
Seria bueno de irme abrir el vinculo delas capeta directamente al enlace que e incluido.
como si fuera direccion de enlace https://bestvaluevpn.com/
ejemplo: 
dar click, se abre la ubicacion del archivo
href="bower_components/font-awesome/css/font-awesome.min.css">
https://bestvaluevpn.com/
estas 2 link funciona en extencion html, pero otros extencion no, como php

**Comment by dbaeumer** [comment]
@WilsonGrave please provide the title and description of the issue in English.

**Comment by dbaeumer** [comment]
I will close the issue. Will reopend when title and description is available in English.
