### ISSUE TITLE
Weird Pylint bug

### ISSUE THREAD

**Issue by youssefsharief** [Microsoft/vscode#57767]
Pylint does not work in vs code if one of the files in the directory is called `token.py` or `tokenize.py`

Steps to Reproduce:

1. Have a file called test_file.py and another file called token.py in one directory
2. Open this directory via VS code

If you renamed the token.py to anything.py it works

**Comment by dbaeumer** [comment]
@youssefsharief I assume that you have install a Python extension to lint the files using Pylint. Please file the issue against the owner of the Python extension. 

If this happens without a Pyhton extension installed please provide steps how you run the linter and we will reconsider the issue.

**Comment by youssefsharief** [comment]
Thanks @dbaeumer. You could see in this link that VS code comes with Pylint by default without an extension

https://code.visualstudio.com/docs/python/linting#_pylint

**Comment by dbaeumer** [comment]
The requires the installation of an external extension (see https://code.visualstudio.com/docs/python/python-tutorial). The extension is maintained here: https://github.com/Microsoft/vscode-python
