### ISSUE TITLE
Active workspace detection for launch.json

### ISSUE THREAD

**Issue by richbully** [Microsoft/vscode#57761]
I have a very large web application with 21 multi root folders, one is a server side app, another is for the client side code and the others are libraries that I use. I like to have them all visible like this as it is very easy to switch over to a lib and check something out. 

![biglist4](https://user-images.githubusercontent.com/11023398/44950236-c5b37500-ae96-11e8-8cea-77ce1512d513.JPG)

Initially I had a launch.json file for each folder and each launch.json contained 6-7 configurations for launching chrome, firefox, edge and node and for each of the browsers I had a testing launch and a main app launch. This results in a very large drop down when trying to debug and hard to make sure the right one is selected sometimes. The image below shows what it looks like after I've removed all of the launch.json files from my libs and just kept the client side and server side launch files. Can you see the node launch? Because I then removed all the launch files you also get lots of 'Add Config' menu items.

![biglist2](https://user-images.githubusercontent.com/11023398/44950231-98ff5d80-ae96-11e8-9da1-fab8bf7213d4.jpg)

Unless I've done something wrong it would be nice to have an option to select the active workspace root, this could either be done manually i.e. a dropdown to select which workspace-root is active and then only the launch configs from that workspace-root would show. You could also allow automatically selecting the active workspace-root by seeing which file currently has focus? 

This initially could just apply to the debug launch but could be extended to the search so it would only look in the active and are sure it could be useful in other places like creating a new terminal.

Kind Regards

**Comment by isidorn** [comment]
I understand that the current debug droopdown design does not scale in your case, and I am leaving this feature request open in case more users complain and we get some ideas on how to fix it.
However selecting the master workspace folder is not something which we have in plan since we have always designed against this.

**Comment by richbully** [comment]
Is the idea to have a separate drop down next to the debug launch to select the workspace (defaults to all) invalid?

**Comment by weinand** [comment]
VS Code has no notion of an "active workspace root". Introducing such a fundamental concept just as a workaround for a scalability issue of the drop down menu cannot be done lightly.

**Comment by richbully** [comment]
I'm not saying my solution is the best or the only way but having your debug drop down go off the screen is obviously not a good thing!

This is definitely a scalability issue but its a lot more then just the drop down. It can also apply to the search engine, new terminal, task runners, keyboard shortcuts and code completion for instance. It would also increase the performance. Its also something that could be done slowly rather than all in one go.

**Comment by weinand** [comment]
But this issue has not yet sparked a lot of reaction by the community, right?

BTW, why are all those folders multi root folders anyway? Only two of them seems to be important: the client and the server.  Have you ever considered to use a different setup? How many launch configs do you have in your 19 libraries? What is the benefit to use 19 root folders for your library instead?

**Comment by richbully** [comment]
Understandably the community and the likes of yourself and your colleagues would determine the priority that anything would get done.

Each of my libraries is an independent project which can be used my multiple apps, for example I have a collection library with lists, dictionary's etc and this has its own application which allows playing around with it via a GUI and it also has an app for running tests on it. Your documentation says that this is what multi-root systems are for? 

My original and desired workflow had a launch.json file for each of my libs as well. Each launch.json file had the 'Main' app and the 'Testing' app and for each I would have a launch for all of the browsers which meant in turn I had 6-10 launch options for each of my libs, the screenshot I originally provided only shows the output after I renamed the launch.json for the libs. I've attached a screenshot at the bottom to illustrate what it looks like with some of these added back in.

The libs are important to me as I'm constantly modifying them and they are all used by the client and server app. The main benefit for me is that its useful to be able to open the file structure up from the explorer in VSCode without having to close and reopen projects.

This brings up another issue, as I've removed the launch.json files from each of my libs to reduce the drop down size, if I was to open my list library as a standalone project, I would need to put the launch.json file back in to run my 'play' or 'testing' app.

Perhaps if having an active workspace root is too hard, at the very least could you please put a horizontal divider in between the different workspace launches in the same way you put a divider between the Launch options and the 'Add Config xxx' list.

![image](https://user-images.githubusercontent.com/11023398/45715492-7f754a00-bbe8-11e8-874b-1c0d5384dc06.png)
