### ISSUE TITLE
Intellisense is extremely slow to load

### ISSUE THREAD

**Issue by klong15** [Microsoft/vscode#5776]
- VSCode Version: 1.0.0
- OS Version: OSX Yosemite 10.10.5
- Unity Version: 4.6.9f1
- VSCode Unity Plugin: 2.50-RELEASE

I set up VSCode with Unity by following the guide here: https://code.visualstudio.com/docs/runtimes/unity

When using VSCode everything works great, the only problem is that intellisense takes many minutes to load when ever I do a single line of change. Reference counts go away. Autocomplete stops working. Jumping to declarations don't do anything, then it will jump to the declaration about 5 minutes after I clicked the action. Just hitting enter to start typing on a new line messes everything up.

How can I speed up load times for this? Did I set something up wrong?

Mono should be up to date. I updated dnvm stuff suggested by some stackoverflow post. When I do 'dnvm list' on terminal, I get this:

    Active Version              Runtime Architecture OperatingSystem Alias
    ------ -------              ------- ------------ --------------- -----
           1.0.0-rc1-update2    coreclr x64          darwin          
      *    1.0.0-rc1-update2    mono                 linux/osx       default

I don't get any actual errors. I will get a message when ever I make a change saying, "Some projects had trouble loading. Please review the output for more details." The omnisharp log for this is:

    [INFO] Starting OmniSharp at 'PROJECTPATH/client-csharp.sln'...
    [INFO] Started OmniSharp from '/Users/KingKlong/.vscode/extensions/ms-vscode.csharp-0.3.7/bin/omnisharp' with process id 91421...
    [INFORMATION:OmniSharp.Startup] Omnisharp server running using stdio at location 'PROJECTPATH' on host 90813.
    [INFORMATION:OmniSharp.Dnx.DnxPaths] Using runtime '/Users/KingKlong/.dnx/runtimes/dnx-mono.1.0.0-rc1-update2'.
    [INFORMATION:OmniSharp.Dnx.DnxProjectSystem] Scanning 'PROJECTPATH' for DNX projects
    [INFORMATION:OmniSharp.Dnx.DnxProjectSystem] No project.json based projects found
    [INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] Detecting projects in 'PROJECTPATH/client-csharp.sln'.
    [INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] Loading project from 'PROJECTPATH/Assembly-CSharp-firstpass-vs.csproj'.
    [INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] Loading project from 'PROJECTPATH/Assembly-CSharp-vs.csproj'.
    [INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] Loading project from 'PROJECTPATH/Assembly-CSharp-Editor-firstpass-vs.csproj'.
    [INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] Loading project from 'PROJECTPATH/Assembly-CSharp-Editor-vs.csproj'.
    [INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Detecting CSX files in 'PROJECTPATH'.
    [INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Could not find any CSX files
    [INFORMATION:OmniSharp.Startup] Solution has finished loading

Also, the flame icon on the bottom right corner says "0 projects". When I click on it, it lists two .sln files. One is client.sln . The other is client-csharp.sln. When I click either of them, they seem to work the same. The flame icon will still say "0 projects" after I click either of them. The guide says to click the -csharp one, but other stackoverflow posts say to choose the other. Which one should I be clicking?

**Comment by bpasero** [comment]
@jrieken please decide if this issue should be moved

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#246
