### ISSUE TITLE
Switch LF as line end appears text blur on windows10

### ISSUE THREAD

**Issue by bursto7** [Microsoft/vscode#57765]
Issue Type: <b>Bug</b>

By default, there is no problem opening vscode.However, after clicking CRLF at the bottom to switch, vscode will have rendering problems and the font will be blurred.Restart vscode without clicking CRLF.
In addition, when switching other Windows in the front, vscode will appear blurred.
The blurry screenshot below：
![image](https://user-images.githubusercontent.com/11030027/44951833-da493a80-aea1-11e8-980e-7d9a469592c6.png)

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (10.68GB free)|
|Process Argv|E:\Program File\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.26.3
python|ms-|2018.7.1
cpptools|ms-|0.18.1

</details>

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/51789
