### ISSUE TITLE
Paste Broken only on python debug interactive window

### ISSUE THREAD

**Issue by AviP1234** [Microsoft/vscode#57769]
- VSCode Version: 15.8.2
- OS Version: Microsoft windows 10 pro (10.0.17134)

Steps to Reproduce:

1. Run a python code in debug mode.
2. Try to paste any text (both using ctrl+c or "paste" using left click).

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by weinand** [comment]
@AviP1234 where exactly do you paste the text?

**Comment by AviP1234** [comment]
Any place in python debug interactive window:
![image](https://user-images.githubusercontent.com/31180090/44955236-c0ffb880-aeb8-11e8-86fa-3f3dcd0f240f.png)

**Comment by weinand** [comment]
You are not using VS Code.
