### ISSUE TITLE
Segmentation fault in Ubuntu Cosmic (18.10)

### ISSUE THREAD

**Issue by fenris** [Microsoft/vscode#57776]
- VSCode Version: 1.27.0-1535712400
- OS Version: Ubuntu Cosmic Cuttlefish (development branch) \n \l

Steps to Reproduce:
$ sudo dpkg -i code-insiders_1.27.0-1535712400_amd64.deb 
Selecting previously unselected package code-insiders.
(Reading database ... 404505 files and directories currently installed.)
Preparing to unpack code-insiders_1.27.0-1535712400_amd64.deb ...
Unpacking code-insiders (1.27.0-1535712400) ...
Setting up code-insiders (1.27.0-1535712400) ...
Processing triggers for desktop-file-utils (0.23-3ubuntu1) ...
Processing triggers for gnome-menus (3.13.3-11ubuntu2) ...
Processing triggers for mime-support (3.60ubuntu1) ...
$ code
/usr/bin/code: line 35: 30533 Segmentation fault      (core dumped) ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"
fenris@X240:~/Downloads$ code
code           code-insiders  codepage       
$ code-insiders 
/usr/bin/code-insiders: line 35: 30561 Segmentation fault      (core dumped) ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by fenris** [comment]
$ gdb core
GNU gdb (Ubuntu 8.1-0ubuntu8) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
"/home/fenris/core": not in executable format: File format not recognized
(gdb) bt
No stack.
(gdb)

**Comment by fenris** [comment]
$ sudo npm install -g electron-atos
npm ERR! write after end
npm ERR! write after end
npm ERR! write after end


   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 5.8.0 → 6.4.1    │
   │       Run npm i npm to update       │
   │                                     │
   ╰─────────────────────────────────────╯


npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fenris/.npm/_logs/2018-09-03T16_38_20_751Z-debug.log
$ sudo npm i npm
npm notice created a lockfile as package-lock.json. You should commit this file.
+ npm@6.4.1
added 387 packages from 770 contributors in 6.461s
$ sudo npm install -g electron-atos
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for electron-atos@1.2.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fenris/.npm/_logs/2018-09-03T16_39_19_332Z-debug.log

**Comment by bpasero** [comment]
Yeah, electron-atos only seems to work on macOS, not Linux. Without a symbolified stack this will be hard to understand.

We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/883208e30da25777874a8ade5f90e1fea638a298/VSCode-win32-x64-1.28.0-exploration.zip)
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/883208e30da25777874a8ade5f90e1fea638a298/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/883208e30da25777874a8ade5f90e1fea638a298/code-exploration-1535724826.tar.gz)

**Comment by fenris** [comment]
the code exploration works as per attached

![vscode-exploration](https://user-images.githubusercontent.com/405473/45003908-fff94f80-b019-11e8-93bb-b7dc86d05089.png)

btw, is there any .deb package for the code exploration?

**Comment by bpasero** [comment]
Great to hear, unfortunately it will take a bit of time before we can make the move and publish packages that auto update.

**Comment by Tyriar** [comment]
I told Canonical and they said it's not released yet and in pre-alpha. I don't think we need to worry about this on our end.

**Comment by flexiondotorg** [comment]
This issue is fixed in Electron 2.0.8.

  * https://github.com/electron/electron/issues/13972

**Comment by prantlf** [comment]
code 1.27.2-1536736588 does not work on Ubuntu 18.10 from today.

code-insiders 1.28.0-1537261834 does work on Ubuntu 18.10 from today.

**Comment by batjko** [comment]
> code 1.27.2-1536736588 does not work on Ubuntu 18.10 from today.
> code-insiders 1.28.0-1537261834 does work on Ubuntu 18.10 from today.

Thanks for that. I'm switching to Insiders then...
