### ISSUE TITLE
C++ class name not highlighted

### ISSUE THREAD

**Issue by obhi-d** [Microsoft/vscode#57771]
- VSCode Version: 1.26.1
- OS Version: Ubuntu 18.04

Hello everyone,
I notice that class name with attributes preceding it are not highlighted when declared.
As you can see in this image, the EXPORT keyword is presumed to be the class name by syntax highlighter.
![screenshot from 2018-09-02 11-55-00](https://user-images.githubusercontent.com/7620636/44954801-c3f2ad00-aea8-11e8-9c39-f441214b944d.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
This issue was moved to textmate/c.tmbundle#62
