### ISSUE TITLE
Keybinding shortcuts in all capitals for some languages

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5777]
- VSCode Version: 1.0.1-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Change language to German (de), Italian (it), or Russian (ru).
2. Open command palette (F1) 
3. Notice the keybindings of some functions

![keybindingsit](https://cloud.githubusercontent.com/assets/12900364/14796096/7c977c4c-0ae0-11e6-8f17-1cc333580e80.PNG)

In the majority of languages they are like this:
![keybindingsfr](https://cloud.githubusercontent.com/assets/12900364/14796109/89755542-0ae0-11e6-8fc9-eb6ffbd00403.PNG)

**Comment by dbaeumer** [comment]
IMO even in German, French we should not all caps these. In English they are:

![capture](https://cloud.githubusercontent.com/assets/1931590/15113772/95697056-15f6-11e6-9b7e-0f5ea3ee6055.png)

**Comment by johnliu2016** [comment]
@lukaschal  Key combination, keyname elements are in, e.g. deu
[keyCodes.nls.resx.lcl](https://monacotools.visualstudio.com/DefaultCollection/Monaco/_git/MonacoLocalization#path=%2FLocalize%2Fdeu%2Fvscode%2Fsrc%2Fvs%2Fbase%2Fcommon%2FkeyCodes.nls.resx.lcl&version=GBmaster&_a=contents)

Please review all of the languages, note the keys are in pair (short and long), 
such as "ctrlKey" and "ctrlKey.long", some of the short key may have to be shortened

**Comment by lukaschal** [comment]
Capitalization of strings "Ctrl", "Alt", "Shift" is fixed on all languages.
