### ISSUE TITLE
Find in Files: newline matches the whole line

### ISSUE THREAD

**Issue by anthonyvdotbe** [Microsoft/vscode#57775]
- VSCode Version: Version: 1.26.1 (Commit: 493869ee8e8a846b0855873886fc79d480d342de)
- OS Version: Windows 10.0.17134.228

Steps to Reproduce:

1. on any file, do "Find in Files", check "Use Regular Expression", and search for "\n"

Expected: only the line endings are matched (as is the case when doing the same with "Find")
Actual: the whole line is matched, which makes it impossible to do a replace

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
When you search for a newline, you should get a message that says `Literal '\n' not supported`. Do you not see that? But I do see that we aren't handling these matches that wrap around properly and I can fix that...

**Comment by anthonyvdotbe** [comment]
No, I don't see that message. Actually, what happens is that the whole line is matched _except_ for the newlines (because when I do a replace, the newlines remain): https://ibb.co/ewqUAK
When I do the same with Find, it's exactly the inverse, and only the newlines are matched, as expected: https://ibb.co/gqzg7z

**Comment by roblourens** [comment]
Verification steps according to what I saw:

- Open some file
- Search \n with regex turned on
- When search is submitted, every line in the editor blinks orange for an instant
- Then an error message appears that `\n` is not supported, and the editor highlights are cleared.

Maybe there was some other case where the highlights are not cleared...

**Comment by anthonyvdotbe** [comment]
Ok, I've experimented some more and have seen the behavior you're describing as well now. However, I'm still able to reproduce this, as follows: add the following to your settings:
> "workbench.startupEditor": "newUntitledFile"

then restart VS Code, just type some random lines in the untitled file, and search \n with regex turned on via Find in Files

**Comment by roblourens** [comment]
Oh, you probably don't have a folder open. In that case I do see what you described. My fix is still the same.
