### ISSUE TITLE
Whole file content erased when it failed to save a file from a remote mount

### ISSUE THREAD

**Issue by vasu-msbits** [Microsoft/vscode#57777]
Version: 1.26.1
Commit: 493869ee8e8a846b0855873886fc79d480d342de
Date: 2018-08-16T18:34:20.517Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
Steps to Reproduce:
1. Mount a remote file path
2. Open a file from there
3. Do some editing
4. simulate n/w issue
5. Try to save the file

Expected: We should loose only the edited content
Actual: Whole file has been emptied

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by vasu-msbits** [comment]
I generally edit the code from remote server with ssh mounts
I lost my unit tests code while editing the unit tests ; 
un-installing the vscode due to this unexpected behavior for now

**Comment by bpasero** [comment]
@vasu-msbits sorry to hear that, it should not happen. can you give some instructions how to get into your setup? on what OS is this?

**Comment by vasu-msbits** [comment]
Hi @bpasero

Thanks for your response
Its elementory OS loki, 
I connect to the remote system CentOS through ssh through application "Files" 
Then I open the folder in VSCode to edit the files under it

I did face any problem doing this till I faced the above issue

**Comment by bpasero** [comment]
@vasu-msbits but how was the condition that caused the network failure?

**Comment by hugosp** [comment]
That happens like every other day for me, and has been doing for a long time, it happens if you press save to close to another save, so its not completed

**Comment by bpasero** [comment]
Are there any errors in the console?

**Comment by vasu-msbits** [comment]
> That happens like every other day for me, and has been doing for a long time, it happens if you press save to close to another save, so its not completed

Hi @hugosp,
Thanks for your comment on the issue
Could please elaborate a bit on when exactly it happens and how can we avoid this problem?

Thanks in advance
