### ISSUE TITLE
Caret position issues in terminal

### ISSUE THREAD

**Issue by blackj0221** [Microsoft/vscode#57781]
- VSCode Version: 1.26.1
- OS Version: Windows 10, 17134.228

![caret](https://user-images.githubusercontent.com/26616056/44958085-fb4b7300-af15-11e8-931e-5864dcbdd7dc.png)
![caret2](https://user-images.githubusercontent.com/26616056/44958094-fe466380-af15-11e8-85c9-b5cdbeb749f3.png)

1. In integrated terminal, the caret starts after some spaces.
2. Small preview text(?) is appeared when typing Korean.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
