### ISSUE TITLE
No funciona el autocompletar C#.

### ISSUE THREAD

**Issue by X278** [Microsoft/vscode#57783]
Issue Type: <b>Bug</b>

Solamente muestra funciones y cosas básicas (cuando escribo "Console + . No aparece absolutamente nada, y ya verifiqué que estuviera el "build system" en C# "), por favor, lo he intentado todo.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:37:28.532Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G620 @ 2.60GHz (2 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|2.92GB (1.80GB free)|
|Process Argv|D:\Instalacion de juegos aqui!\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-standardjs|che|1.2.3
jquerysnippets|don|0.0.1
eppz-code|epp|1.2.41
code-runner|for|0.9.4
jquery-snippets|Hri|1.0.0
csharpextensions|jch|1.3.0
vscode-language-pack-es|MS-|1.26.3
python|ms-|2018.7.1
csharp|ms-|1.15.2
js-atom-grammar|ms-|0.1.14
vscode-js-console-utils|wht|0.7.0
JavaScriptSnippets|xab|1.7.0

</details>

**Comment by dbaeumer** [comment]
@X278 can you please provide the desription and title in English.

TO get proper C# support you need to install the C# extension from the market place: https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp
