### ISSUE TITLE
Single tab bar per multiple splits, change focused one

### ISSUE THREAD

**Issue by naufraghi** [Microsoft/vscode#57780]
I'm quite used to a single tab bar, even for multiple splits, the tab change updates the focused spit, and I very miss this feature in vscode.

The main point is that one can directly decide what to show where, without interacting with multiple tab bars and duplicated file names.

![gvim-tabs](https://user-images.githubusercontent.com/106029/44958062-fae1b680-aeda-11e8-950a-133e726b7663.png)

![vscode-tabs](https://user-images.githubusercontent.com/106029/44958064-0634e200-aedb-11e8-9c99-98ea91a7e225.png)

Hiding the tabs and using the shortcut to open a file is a good fail-over,  but I think the single tab bar UX is valuable the same.

**Comment by bpasero** [comment]
@naufraghi you can disable tabs in settings (`"workbench.editor.showTabs": false`), does that help?

**Comment by naufraghi** [comment]
@bpasero yes, that is the fail-over solution I'm using (cited at the bottom of the issue description, thanks for the config name I forgot to mention).

Having used the single tab bar for a long time, I find that solution less confusing in general, just my 2 cents.

**Comment by bpasero** [comment]
@naufraghi do you maybe want to hide the title bar above the editor entirely?

**Comment by naufraghi** [comment]
... no, the "missing" feature is that now each split has it's own tab bar that is used to change the buffer shown in the paired window, another UI option is to have a single tab bar that changes the buffer shown in the split that has the focus.

This is not a bug report, it's a feature proposal :)

**Comment by bpasero** [comment]
Ok got it, someone reported this already to be able to split editors without splitting the tab bar.
