### ISSUE TITLE
资源管理器切换文件的时候总是跟随，好恶心啊，我不想跳过去的，不知道怎么关掉

### ISSUE THREAD

**Issue by dforel** [Microsoft/vscode#57785]
Issue Type: <b>Feature Request</b>

资源管理器切换文件的时候总是跟随，好恶心啊，我不想跳过去的，不知道怎么关掉

VS Code version: Code 1.22.0 (6b4d53cdab8bcae1eaaa4934d93c077319b573db, 2018-04-05T17:27:42.363Z)
OS version: Windows_NT x64 6.1.7601

**Comment by dbaeumer** [comment]
@dforel can you please provide the title and description in English.

**Comment by shizengzhou** [comment]
@dforel You can set `"explorer.autoReveal": false`

**Comment by dforel** [comment]
@shizengzhou thanks.
