### ISSUE TITLE
VSCode fails to process paths with back slashes returned from debug adapter

### ISSUE THREAD

**Issue by dibyendumajumdar** [Microsoft/vscode#5778]
- VSCode Version: 1.0
- OS Version: Windows 10 64-bit

Steps to Reproduce:

1. Create a debug server that responds to the 'launch' request by sending a response with 'path' containing back slashes 
2. VSCode shows error and the debug session is terminated.

Above is inconsistent because the 'program' field sent by VSCode contains path with back slashes.

**Comment by verysimplenick** [comment]
Looks like same in 1.7.1, but debugging not terminated, I can step over for example, but can't open source file (file exists, but VS Code don't like `/` in path)
![cant_open_file](https://cloud.githubusercontent.com/assets/922660/20157774/e1f06a42-a6e7-11e6-9af9-6d753c79627e.jpg)

**Comment by isidorn** [comment]
@verysimplenick I see that the original fix for this issue is still in our source code. Can you provide some repro steps. E.g. on windows? Does this happen for all files that the adapter returns with forward slashes? You use your custom debugger?

**Comment by isidorn** [comment]
Continuing discussion here https://github.com/Microsoft/vscode/issues/15270
