### ISSUE TITLE
where should i put my global tasks.json file vscode keeps creating it locally 

### ISSUE THREAD

**Issue by NikosEfthias** [Microsoft/vscode#5779]
- VSCode Version:1.0.0
- OS Version:ubuntu 16.4

Steps to Reproduce:
where should i put my global tasks.json file vscode keeps creating it locally

**Comment by bpasero** [comment]
We currently do not support global tasks. @dbaeumer to chime in if this is a feature he had in mind.

**Comment by Aarilight** [comment]
What's a good alternative for a global task? I want to run a shell command on a keypress with minimal effort ideally haha

**Comment by faceyspacey** [comment]
+1
