### ISSUE TITLE
Wrong syntax highlighting in field value

### ISSUE THREAD

**Issue by rickyah** [Microsoft/vscode#57797]
Issue Type: <b>Bug</b>

Using this snippet makes any text written after the BUG_SAMPLE variable to render as a string:

```
final class Example
{
    private static final String MODULE = "test"

    private static final String BUG_EXAMPLE = "window." + TEST + "aFunction();";

    Example(PopupWebView popupWebView)
    {
        this.popupWebView = popupWebView;
    }
}
```

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:31:26.156Z)
OS version: Darwin x64 17.7.0

<details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
puppet|Bor|0.3.2
unity-debug|Uni|1.3.0
unity-snippets|Ycl|0.1.2
gitignore|cod|0.5.0
gitlens|eam|8.5.6
EditorConfig|Edi|0.12.4
vscode-great-icons|emm|2.1.41
ruby-linter|hoo|1.0.0
cmake-tools-helper|mad|0.2.1
ruby-rubocop|mis|0.7.0
prettify-json|moh|0.0.3
python|ms-|2018.7.1
cpptools|ms-|0.18.1
csharp|ms-|1.15.2
sublime-keybindings|ms-|4.0.0
material-icon-theme|PKi|3.5.3
ruby|reb|0.20.0
java|red|0.30.0
shader|sle|1.1.3
code-eol|soh|0.3.3
cmake|twx|0.0.17
cmake-tools|vec|1.1.1
clang-format|xav|1.6.2

(1 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
This issue was moved to atom/language-java#158
