### ISSUE TITLE
Copy the text to the vscode editor will change the character t to the chinese character seven

### ISSUE THREAD

**Issue by JYG-V** [Microsoft/vscode#57791]
Issue Type: <b>Bug</b>

# -*- coding:utf-8 -*-
def useproxy(proxy_addr,url):
impor七urllib.reques七
proxy= urllib.reques七.ProxyHandler({'h七tp':proxy—addr})
opener = urllib.request.build_opener(proxy, urllib.request.HTTPHandler)
urllib.reques七.ins七all_opener(opener)
da七a = urllib . reques 七. urlopen (url) . read () . decode ('u七f-8')
re七urn data
proxy_addr="202.75.210.45:7777"
data=use_proxy(proxy_addr,"h七tp://www.baidu.com")
print(len(da七a))

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (4.64GB free)|
|Process Argv|C:\Users\Icarus\AppData\Local\Programs\Microsoft VS Code\Code.exe C:\Users\Icarus\Desktop|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.4
vscode-language-pack-zh-hans|MS-|1.26.3
python|ms-|2018.7.1
vscode-icons|rob|7.25.0

(1 theme extensions excluded)

</details>

**Comment by JYG-V** [comment]
Here are my vscode plugin
![qq 20180903192212](https://user-images.githubusercontent.com/17162810/44984257-adcf1480-afae-11e8-937a-a6ff6016469d.png)
This text's copy should be like this
![qq 20180903192412](https://user-images.githubusercontent.com/17162810/44984406-2afa8980-afaf-11e8-8f2c-d7509749dd2b.png)
But it sounds like wrong with this
![qq 20180903192633](https://user-images.githubusercontent.com/17162810/44984432-49608500-afaf-11e8-9095-69118e5d7250.png)

**Comment by JYG-V** [comment]
And I don't know if this is related to the Chinese display plugin(Chinese Language Pack), or others

**Comment by JYG-V** [comment]
Today, the first thing that I think it related to Chinese language pack,so, I uninstall the pack and restart it.
The result of what i see is it doesn't work like that
![qq 20180904123214](https://user-images.githubusercontent.com/17162810/45010158-92abe580-b03e-11e8-8435-1dbc9974c18c.png)
and Now, I think it isn't the Chinese Language Pack's fault, it maybe the editor's self.
Here are my userseting.json, I do not think it would be wrong set
![qq 20180904123512](https://user-images.githubusercontent.com/17162810/45010239-136ae180-b03f-11e8-9edc-dd3bf2f67527.png)

**Comment by alexandrudima** [comment]
@JYG-V Do you mean you have a problem when opening a certain file? Can you attach the file with the problem? The text you have pasted contains this funny character and does not contain two `t`'s

In other words, what are the steps you do, what do you expect to happen vs. what happens?

**Comment by JYG-V** [comment]
That's interesting question and answer, I mean I copy the example code or the demo, other than open, it isn't Encoding's Proplem, I know reEncoding GBK will be good support for Chinese language ,and then paste it to the vscode editor, it was amazing and fantastic editor,i love it.and because of i'm chinese, i wish it could be better support for chinese to program or code, i'm learing Python Spider and Regulation Expression, I copy the sample code from the pdf file and just want to test it and figure it out what can it doing or can do something else. And you see, i met this problem, and it makes me not convenient to code any more, this pdf file are too larger 43MB size, maybe will upload failed,and my network isn't good

**Comment by JYG-V** [comment]
Yet, the github's regulation is no more than 10MB file, i upload failed!

**Comment by JYG-V** [comment]
Now, I'm trying to reappear the situation that i met.
First, i open the pdf file 精通Python网络爬虫 核心技术框架与项目实战 韦玮.pdf
![qq 20180905223012](https://user-images.githubusercontent.com/17162810/45100051-486c5680-b15b-11e8-82b5-feb1dfdb73f9.png)
Then i go to the character5 regulation expression proxy setup,and i copy the sample code
![1](https://user-images.githubusercontent.com/17162810/45100389-f2e47980-b15b-11e8-8e76-adc492dedb5c.png)
Then i open the vscode editor and new a file choose to python and save as a test.py

**Comment by JYG-V** [comment]
Please trust me, i do not have any other bad habits,, what happen is what you see.
![1264](https://user-images.githubusercontent.com/17162810/45100863-d5fc7600-b15c-11e8-91df-620c37eb48f8.png)

**Comment by JYG-V** [comment]
I wish vscode editor could fix that problem, yet,, althought it's too small to negelect it, and not important than others, i think it isn't only i met this problem.Why does the vscode editor happen to t otherwise any other characters?i present think it's a vscode colorful eggs(amazing),but it is not friendly to me, thank you for your answer.

**Comment by alexandrudima** [comment]
@JYG-V I believe the PDF itself contains `七` instead of `t`. What happens if you copy from the PDF and paste in another software, like e.g. Notepad ?

**Comment by JYG-V** [comment]
I'm so sorry to hear that, It seems that you still don't believe me.
![qq 20180906163418](https://user-images.githubusercontent.com/17162810/45145217-badc4580-b1f2-11e8-950b-93fe5682f57f.png)

**Comment by JYG-V** [comment]
emmm, I have write a email to your email address, attach a larger attachment PDF file which contains 七 instead of t, Please Check it out,  and i'm glad to hear your good news, good luck, Thank you!

**Comment by JYG-V** [comment]
It seems that actually the pdf file's character t instead of the chinese character 七, but the pdf file's author have no way to do that, because when you type import ,it can't be typed as 七, it isn't convenient, but the stranger thing is that, you will see the pdf file clearly that t is t,not 七
Actually, VSCode Editor has been added picture viewer,then there is a question, why not add a plugin such as edge PDF viewers?All in one, plugin is everything, can create anything.That's why I like to use vscode.

**Comment by JYG-V** [comment]
And why do it only change t to 七？why other characters not changed?I have no way to type t as 七

**Comment by alexandrudima** [comment]
@JYG-V From your previous screenshot where you show Notepad, it looks like when you paste in Notepad you also get the `七` character and not the latin `t` character. I can therefore conclude this is not a problem with VS Code, but rather a problem with the PDF you are copying from.

Here, select the following text and paste it to VS Code or Notepad:

`this is a sentence that uses t a lot`

Are the characters pasted as `t` or as `七`?

If the characters are pasted as `t` you have further proof that this is a problem with the PDF.

**Comment by JYG-V** [comment]
Okay, thank you very much, I misunderstand the editor, it's my fault.
