### ISSUE TITLE
How to get whole CompletionItems that vscode provided in language service API "registerCompletionItemProvider"?

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#578]
_From @BleyChen on November 10, 2015 6:57_

I want to develop an extension for JavaScript Intellisense in VSCode , And now i meet an problem that when i call the API "registerCompletionItemProvider" in the following code , i can't get the whole completionItems that provided by the VSCode itself in method "provideCompletionItems",anyone can help me?

      vscode.languages.registerCompletionItemProvider("javascript",
	{
		resolveCompletionItem(item:vscode.CompletionItem, token: vscode.CancellationToken): vscode.CompletionItem 
		{
			
		   var completionItem1:vscode.CompletionItem = new vscode.CompletionItem("id");
		   completionItem1.detail = "aaa";
		   completionItem1.filterText = "aa";
		   completionItem1.insertText = "aa";
		   return completionItem1;
		}
		,
		provideCompletionItems(document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken): Promise<vscode.CompletionItem[]> 
		{
        // I want to get 	completionItems that provided by the VSCode itself ,not like following code ,provided by myself. does any variable has stored completionItems.

			return new Promise((resolve, reject) => { 
			var completionItems:vscode.CompletionItem[] = [];
			var completionItem:vscode.CompletionItem = new vscode.CompletionItem("bb");
			completionItem.detail = "bde";
			completionItem.filterText = "bb";
			completionItem.insertText = "bb";
			completionItems.push(completionItem);
			return resolve(completionItems) ;
						});
		}
	})

_Copied from original issue: Microsoft/vscode-extensionbuilders#89_

**Comment by seanmcbreen** [comment]
_From @jrieken on November 10, 2015 14:48_

unsure if i have understood your question correctly, but wrt `provideCompletionItems` and `resolveCompletionItem` note the following:

1. VS Code will always call `provideCompletionItems` to get a list of all completions available at a position.
2. If the provider implements the _optional_ method `resolveCompletionItem` it will be invoked when a completion is selected in the completion list UI. You should fill in detail and documentation if it was too expensive to fill in for each item during step #1.

so, to just get completions it's enough to return an array of completion items from `provideCompletionItems`

**Comment by seanmcbreen** [comment]
_From @BleyChen on November 11, 2015 2:54_

sorry ,maybe my description is not very clear ,as we know , when we write JavaScript Code in JS File ,it will pop up completion list,  what I want to know is that whether I can get completion list provided by the VSCode itself  in provideCompletionItems.

**Comment by seanmcbreen** [comment]
_From @BleyChen on November 13, 2015 3:53_

jrieken,  i have two questions as following
1# .i just want to know whether has an variable stored completion items that provided by the VSCode itself that i can use in  method provideCompletionItems . (my extension need use completion item to get additional information) , 

2#. i found that resolveCompletionItem will be triggered only when completion item which is provided by myself  was selected ,so i want to know whether resolveCompletionItem  can be called when user select someone else completion item in completion list UI, thank you!

**Comment by seanmcbreen** [comment]
_From @jrieken on November 13, 2015 12:11_

Sorry, you cannot do either. The item someone else provided, including those VSCode provides, cannot be access by someone at that time, also resolveCompletionItem will be called with items your provider created.

**Comment by seanmcbreen** [comment]
_From @BleyChen on November 17, 2015 8:27_

jrieken, thanks your replay , and I want to ask your some questions as following:

class CompletionItem {
        label: string;
        kind: CompletionItemKind;
        detail: string;			// 
        documentation: string;	// 
        sortText: string;		// 
        filterText: string;		// 
        insertText: string;
        textEdit: TextEdit;		// 
        constructor(label: string);
    }

1. CompletionItem has one property named textEdit ,do you know what's the function of this property?
2. do you know whether the words in documentation property  of completionitem can wrap , the following code that I write can't wrap in the UI and only show in one line ,if words is more longer it will be clipped.

                 provideCompletionItems(document: vscode.TextDocument, position: vscode.Position,          token: vscode.CancellationToken): Promise<vscode.CompletionItem[]> 
		{
			return new Promise((resolve, reject) => { 
					
			var completionItems:vscode.CompletionItem[] = [];
			var completionItem:vscode.CompletionItem = new vscode.CompletionItem("id");
			completionItem.detail = "test javascript detail";
			completionItem.documentation = "mde\r\nadfdsf nadfdsf nadfdsf nadfdsf nadfdsf nadfdsf nadfdsf nadfdsf nadfdsf nadfdsf nadfdsf nadfdsf nadfdsf nadfdsf nadfdsf nadfdsf nadfdsf nadfdsf nadfdsf nadfdsf nadfdsf nadfdsf nadfdsf nadfdsf nadfdsf nadfdsf nadfdsf nadfdsf nadfdsf nadfdsf nadfdsf nadfdsf";
			completionItem.filterText = "test";
			completionItem.insertText = "bb";
			completionItem.label = "test";
})
}
![image](https://cloud.githubusercontent.com/assets/15098626/11206130/01d4f630-8d48-11e5-8245-3fa5d89006f9.png)

**Comment by seanmcbreen** [comment]
We also ave this issue and it's something we need to work on - but for now the message is cropped at one line.  This hits people in the VSCode API a lot as well.

**Comment by seanmcbreen** [comment]
`F8` hitting `F8` should give you more space if that works for your users?

**Comment by seanmcbreen** [comment]
Actually sorry I lie that's for a diagnostic not a completion :(

**Comment by jrieken** [comment]
We have now API Commands for this

**Comment by BleyChen** [comment]
@jrieken  which API Commands ,can you tell me ,thank you!
