### ISSUE TITLE
using pen tool alike in Blender 3d to make fast live marks e.g when explaining scopes in visual way, etc

### ISSUE THREAD

**Issue by pgrycz** [Microsoft/vscode#57805]
I often would get better explained things in more advanced code with such tool using code editor/IDE,
the idea is alike MS paint but used in non-graphical software: at any time the tool can be used like to do a quick snapshot of the fragment of the code we want to discuss or focus on and e.g easily mark all scopes in higher ordered funcion which has a callback so to explain how 'this' works and where it has what context, stuff like that, it probably may have many other purposes of use. Or have tools in which mode switched to whole workplace window where the code is is treated as non editable but alike graphic area to quick erase all the content around the fragment of the discussed code or even mark some parts of the code we would like to move away a little from each other to make it more readable. Nothing too advanced, just for simple fast use. Maybe such quick operations are achievable via editor mode?

**Comment by dbaeumer** [comment]
I actually think something like this could come from an extension.

**Comment by nealot** [comment]
Maybe related: https://github.com/Microsoft/vscode/issues/23109
