### ISSUE TITLE
Allow to duplicate files in the explorer (Cmd+D on macOS)

### ISSUE THREAD

**Issue by tobiasfabian** [Microsoft/vscode#57801]
Issue Type: <b>Feature Request</b>

I can’t duplicate files or folders with cmd+d when I selected file(s)/folder(s) in the Explorer sidebar.

Duplicating files with cmd+d is a standard behavior on macOS.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:31:26.156Z)
OS version: Darwin x64 17.7.0

**Comment by Gruntfuggly** [comment]
There is an extension that provides this...
https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-duplicate
