### ISSUE TITLE
NRE when starting debugger

### ISSUE THREAD

**Issue by galvesribeiro** [Microsoft/vscode#57808]
- VSCode Version: 1.26.1
- OS Version: OSX 10.13.6

Steps to Reproduce:

1. `code .`
2. Press F5 to start the application.
3. No errors appear on Electron console: 
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/4714040/44988132-fe6b5100-af5f-11e8-8bca-bd4474a57af1.png">
4. Application don't start and VSCode show this message:  
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/4714040/44988248-6f126d80-af60-11e8-8b3a-f3d5fada9526.png">

Does this issue occur when all extensions are disabled?: No. If I disable the extensions I can't run C# projects.

The launch.json is the following:

```json
{
  "version": "0.2.0",
  "configurations": [
      {
          "name": "Kube Debugger",
          "type": "coreclr",
          "request": "launch",
          "program": "/app/EventStore.Kube.dll",
          "cwd": "/app",
          "sourceFileMap": {
              "/src": "${workspaceFolder}"
          },
          "pipeTransport": {
              "debuggerPath": "/root/vsdbg/vsdbg",
              "pipeCwd": "${workspaceFolder}",
              "windows": {
                  "pipeProgram": "kubectl",
                  "pipeArgs": [
                      "exec",
                      "-i",
                      "eventstore",
                      "--namespace",
                      "giro",
                      "--"
                  ],
                  "quoteArgs": false
              }
          }
      }
  ]
}
```

It was working properly but after recent VSCode updates it now fail with this NRE.

**Comment by weinand** [comment]
Please file this issues against the C#/.net extension
