### ISSUE TITLE
Visual Studio Code crash when internal terminal application do character overflow

### ISSUE THREAD

**Issue by h0m3** [Microsoft/vscode#57814]
Visual Studio Code crash when you open any application that do a character overflow at the internal terminal

- VSCode Version: 1.26.1 Commit: 493869ee8e8a846b0855873886fc79d480d342de x64
- OS Version: Arch Linux 4.18.5-arch1-1-ARCH x86_64

Steps to Reproduce:

Open any software that do a character overflow such as a infinite loop, a example:

```
#include <stdio.h>
int main() {
    while(1)
        printf("B");
    return 0;
}
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
@h0m3 can you repro this using `yes`? Also can you try on the Insiders build https://code.visualstudio.com/insiders
