### ISSUE TITLE
Don't insert spaces for JavaScript object braces

### ISSUE THREAD

**Issue by ma11hew28** [Microsoft/vscode#57813]
I like the inserted spaces here `if (true) { return; }` but not here `let params = { limit: 1 }`.

Maybe a format setting named, for example, `insertSpaceAfterOpeningAndBeforeClosingObjectBraces` should be added?

I also want this style for TypeScript.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#26878
