### ISSUE TITLE
VSCode Hangs on focus

### ISSUE THREAD

**Issue by Jouwee** [Microsoft/vscode#57818]
Issue Type: <b>Performance Issue</b>

I have noticed that it freezes when I focus another window (usually another electron based app) and return focus to VSCode. It freezes for about 3-5 seconds and uses a lot of CPU. According to the Process Explorer, it's not the extension host that is using the CPU

This happens from time to time when I leave VSCode open for a long time. I have been using VSCode for 6 hours with a workspace with 7 small (< 20kB) NodeJS projects open.

<details>
<summary>Process Info on hang</summary>
code --status

Version:          Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS Version:       Windows_NT x64 10.0.17134
CPUs:             Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)
Memory (System):  7.95GB (2.54GB free)
VM:               0%
Screen Reader:    no
Process Argv:     D:\Programs\x64\Microsoft VS Code\Code.exe
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    disabled_software
                  rasterization:                enabled
                  video_decode:                 enabled
                  video_encode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled
CPU %   Mem MB     PID  Process
    0       74    1308  code main
    0       58     640     shared-process
   43      387    9160     window (ÔùÅ microservice-connector.js - azleads-data (Workspace) - Visual Studio Code)
    0        5     544       winpty-process
    0       10    9296         console-window-host (Windows internal process)
    0        4   14652         C:\Windows\System32\bash.exe
    0        4    3016           C:\WINDOWS\System32\lxss\wslhost.exe {12345678-1234-5678-0123-456789abcdef} 400 408 412
    0        5    3512             console-window-host (Windows internal process)
    0       24    1452       searchService
    0       32    6860       watcherService
    0      104    9340       extensionHost
    0      177    1832         electron_node electronForkStart.js tsserver.js
    0       53    4836           electron_node typingsInstaller.js tsserver.js typesMap.js
    0      125    2688         electron_node server.js
    0       32    3540         electron_node tslintServer.js
    0      106    5228         electron_node eslintServer.js
    0       15   11648         electron_node jsonServerMain.js
    0       24   11880         C:\Users\Pichau\.vscode\extensions\ms-vsliveshare.vsliveshare-0.3.623\dotnet_modules\vsls-agent.exe --autoexit --pipe dbcdcc8dbddb488e8220dabec8f376bf --service https://insiders.liveshare.vsengsaas.visualstudio.com/
    0        4    8900           console-window-host (Windows internal process)
    0        5   13968         extensionHost
    0        5   14020         extensionHost
    0        6   14208         extensionHost
    0       64   12440     gpu-process
Workspace Stats:
|  Window (ÔùÅ microservice-connector.js - azleads-data (Workspace) - Visual Studio Code)
|    Folder (crawler): 54 files
|      File types: log(40) js(6) json(4) babelrc(1) gitignore(1) sh(1) yml(1)
|      Conf files: package.json(1) launch.json(1)
|    Folder (scraper): 112 files
|      File types: log(78) js(28) json(3) babelrc(1) gitignore(1) yml(1)
|      Conf files: package.json(1)
|    Folder (categorizer): 35 files
|      File types: log(15) js(11) json(3) babelrc(1) gitignore(1) sh(1) md(1)
|                  yml(1) txt(1)
|      Conf files: package.json(1) launch.json(1)
|    Folder (unifier): 43 files
|      File types: log(30) js(6) json(3) babelrc(1) gitignore(1) md(1) yml(1)
|      Conf files: package.json(1)
|    Folder (transposer): 41 files
|      File types: log(29) js(5) json(3) babelrc(1) gitignore(1) sh(1) yml(1)
|      Conf files: package.json(1)
|    Folder (importer-cnpjs-receita): 57 files
|      File types: log(47) json(3) js(3) babelrc(1) gitignore(1) md(1) yml(1)
|      Conf files: package.json(1)
|    Folder (commons): 163 files
|      File types: log(86) js(69) json(4) babelrc(1) gitignore(1) yml(1) md(1)
|      Conf files: package.json(1)
|      Launch Configs: node(3)
|      Launch Configs: node

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134
</details>
<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.95GB (2.52GB free)|
|Process Argv|D:\Programs\x64\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	    82	  1308	code main
    0	    58	   640	   shared-process
    0	   398	  9160	   window (● microservice-connector.js - azleads-data (Workspace) - Visual Studio Code)
    0	     8	   544	     winpty-process
    0	    11	  9296	       console-window-host (Windows internal process)
    0	     4	 14652	       C:\Windows\System32\bash.exe
    0	     4	  3016	         C:\WINDOWS\System32\lxss\wslhost.exe {12345678-1234-5678-0123-456789abcdef} 400 408 412
    0	     5	  3512	           console-window-host (Windows internal process)
    0	    24	  1452	     searchService
    0	    32	  6860	     watcherService
    0	   111	  9340	     extensionHost
    0	   177	  1832	       electron_node electronForkStart.js tsserver.js 
    0	    53	  4836	         electron_node typingsInstaller.js tsserver.js typesMap.js 
    0	   125	  2688	       electron_node server.js 
    0	    32	  3540	       electron_node tslintServer.js 
    0	   106	  5228	       electron_node eslintServer.js 
    0	    15	 11648	       electron_node jsonServerMain.js 
    0	    24	 11880	       C:\Users\Pichau\.vscode\extensions\ms-vsliveshare.vsliveshare-0.3.623\dotnet_modules\vsls-agent.exe --autoexit --pipe dbcdcc8dbddb488e8220dabec8f376bf --service https://insiders.liveshare.vsengsaas.visualstudio.com/
    0	     4	  8900	         console-window-host (Windows internal process)
    0	     5	 13968	       extensionHost
    0	     5	 14020	       extensionHost
    0	     6	 14208	       extensionHost
    1	    73	 12440	   gpu-process
    0	    77	 34084	   window (Process Explorer)
    1	    69	 34644	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● microservice-connector.js - azleads-data (Workspace) - Visual Studio Code)
|    Folder (scraper): 112 files
|      File types: log(78) js(28) json(3) babelrc(1) gitignore(1) yml(1)
|      Conf files: package.json(1)
|    Folder (unifier): 43 files
|      File types: log(30) js(6) json(3) babelrc(1) gitignore(1) md(1) yml(1)
|      Conf files: package.json(1)
|    Folder (transposer): 41 files
|      File types: log(29) js(5) json(3) babelrc(1) gitignore(1) sh(1) yml(1)
|      Conf files: package.json(1)
|    Folder (importer-cnpjs-receita): 57 files
|      File types: log(47) json(3) js(3) babelrc(1) gitignore(1) md(1) yml(1)
|      Conf files: package.json(1)
|    Folder (crawler): 54 files
|      File types: log(40) js(6) json(4) babelrc(1) gitignore(1) sh(1) yml(1)
|      Conf files: package.json(1) launch.json(1)
|    Folder (categorizer): 35 files
|      File types: log(15) js(11) json(3) babelrc(1) gitignore(1) sh(1) md(1)
|                  yml(1) txt(1)
|      Conf files: package.json(1) launch.json(1)
|    Folder (commons): 163 files
|      File types: log(86) js(69) json(4) babelrc(1) gitignore(1) yml(1) md(1)
|      Conf files: package.json(1)
|      Launch Configs: node
|      Launch Configs: node(3);
```

</details>
<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.5.0
tslint|eg2|1.0.38
vsliveshare|ms-|0.3.623
sass-indented|rob|1.4.9
autoimport|ste|1.5.3
code-spell-checker|str|1.6.10
code-spell-checker-portuguese-brazilian|str|0.1.0
quokka-vscode|Wal|1.0.143
vscode-import-cost|wix|2.8.0

</details>

**Comment by dbaeumer** [comment]
This is actually the rendered consuming 43% CPU. Can you follow the steps in https://github.com/Microsoft/vscode/wiki/Performance-Issues#the-rendererwindow-process-consumes-a-lot-of-cpu about collecting a performance trace when you see this the next time. This would help tracking this down.
