### ISSUE TITLE
Unable to drag PR changes view around in SCM view

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#57811]
I am not able to drag the bottom view in the following screenshot around:

![image](https://user-images.githubusercontent.com/900690/44989846-84eb5700-af8f-11e8-8c61-51f91e92d78f.png)

**Comment by sandy081** [comment]
@bpasero Where are you trying to drag and drop? You can drop the bottom view to the view above it.

**Comment by bpasero** [comment]
@sandy081 yeah I tried that but did not work somehow, come to my desk tomorrow and we can check

**Comment by bpasero** [comment]
@sandy081 actually it seems possible to reorder the views from the PR extension! But what I cannot do is drag the PR extension view above the outgoing changes view from SCM. Maybe that is just not supported yet?
