### ISSUE TITLE
Unable to debug markdown-language-features extension after connecting to process

### ISSUE THREAD

**Issue by imdadahad** [Microsoft/vscode#57817]
- VSCode Version: Development
- OS Version: High Sierra

Steps to Reproduce:

1. Download source and build locally
2. Edit `vscode/extensions/markdown-language-features/src/features/workspaceSymbolProvider.ts` in `provideWorkspaceSymbols` (in my case)
3. Set a breakpoint in that method
4. Run in Debug and connect to the Vscode extension process
5. Trigger Search Symbol in Workspace

The breakpoint isn't hit

Does this issue occur when all extensions are disabled?: N/A

**Comment by weinand** [comment]
Works fine for me.
I'm using the "Attach to Extension Host" launch config and after a reload of the extension host window I do a F1 and then execute "Go to Symbol in Workspace...":

![2018-09-13_13-18-01](https://user-images.githubusercontent.com/1898161/45485343-8ff47300-b757-11e8-897a-a4dc20303493.png)
