### ISSUE TITLE
UI font size is not customizable and it doesn't honor system font size settings

### ISSUE THREAD

**Issue by sryze** [Microsoft/vscode#57812]
Issue Type: <b>Bug</b>

1. Install Visual Studio Code on Ubuntu
2. Open it
3. Observe tiny text size

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:34:20.517Z)
OS version: Linux x64 4.17.0-9-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|11.53GB (4.29GB free)|
|Process Argv|/usr/share/code/code .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
javascript-ejs-support|Dig|0.3.2
minify|Hoo|0.3.0
vscode-css-formatter|aes|1.0.1
sql-formatter|cym|1.0.2
vscode-eslint|dba|1.5.0
gitlens|eam|8.5.6
EditorConfig|Edi|0.12.4
vscode-great-icons|emm|2.1.41
beautify|Hoo|1.4.2
xml-format|mik|0.0.4
cpptools|ms-|0.18.1
vscode-jsp|pth|0.0.2
vscode-hexdump|sle|1.6.0
uridecode|sry|0.3.4
cmake|twx|0.0.17
highlight-matching-tag|vin|0.4.4

</details>

**Comment by Tyriar** [comment]
Can you provide a screenshot of the problem? Also the version of Ubuntu?

**Comment by m-thorsen** [comment]
Distro/DE version shouldn't matter in this case as any Linux DE has customizable system fonts and sizes, which don't get respected by VSCode as the workbench font uses a hardcoded stack/size off `11px "-apple-system,BlinkMacSystemFont,Segoe WPC,Segoe UI,HelveticaNeue-Light,Ubuntu,Droid Sans,sans-serif"`

I'd say it's related to #10144 (and its numerous duplicates).

Can be worked around in fontconfig using aliases and pixelsize assigning, but that can and will backfire rather quickly as VSCode uses a common web font stack.

Screenshot to illustrate. Note workbench font size (I've already used fontconfig to alias Segoe UI to Noto Sans, but the size is way off)

![screenshot_20180905_224052](https://user-images.githubusercontent.com/14907694/45118040-82d3f480-b157-11e8-953f-bff645696985.png)

**Comment by sryze** [comment]
I believe it happens on all Ubuntus regardless of version like @m-thorsen said. I'm using a GNOME desktop though, font settings are configurable there via GNOME Tweak Tool

```
sudo apt-get install gnome-tweak-tool
gnome-tweak-tool
```

Font settings are under "Fonts" tab.
