### ISSUE TITLE
Debugger trying to connect to wrongly formatted file path and failing to attach to running process!

### ISSUE THREAD

**Issue by techsin** [Microsoft/vscode#57826]
- 1.26.1
- Windows 10

Steps to Reproduce:

1. Run your nodejs server with --inspect flag
2. Click debugger, choose Attach by Proccess ID and click Run
3. Choose your node process
4. Wait few seconds. And you get this error.

Does this issue occur when all extensions are disabled?: Yes

`"Cannot connect to runtime process, timeout after 10000 ms - (reason: Can't attach to this target that may have Chrome DevTools attached: file://C_Users_username_Desktop_Projects_example_app.js). "`

filepath is obviously wrong.

**Comment by techsin** [comment]
chrome debugger opens up as it starts with --inspect flag

and nodejs version is 9.3.0

**Comment by techsin** [comment]
Yes I have tried both auto attach enabled and disabled

**Comment by techsin** [comment]
if i launch even without inspect flag it still says same thing

**Comment by techsin** [comment]
also note i'm using gulp > use gulp-nodemon > that launches node app.js

**Comment by techsin** [comment]
if nodejs can have only one debugger, then i suppose one problem I'm having is "How to prevent --inspect from opening chrome debugger and wait for auto attach to work" and wait for gulp command execution.

**Comment by techsin** [comment]
i figured it out, sorry for wasting your time. But I guess for documentation.

Node can have only one debugging process attached to it.
I have chrome extension NIM installed that also looked for any opened connections and connected to it.
Which 9/10 prevented VScode from connecting. Disabling extension prevents debugger from getting attached which gives time to vscode debugger to get attached instead.

Thanks for everyone's time.

**Comment by roblourens** [comment]
Ah yes, I should have asked about NIM. Good catch.

Chrome supports multiple debuggers, Node hopefully will in the future too.

**Comment by techsin** [comment]
I type gulp to start server.

gulp has nodemon plugin, css watch/transpile plugin, transpile es6 to js, webpack plugin, etc.
whenever i make changes in backend files, nodemon restarts the server (app.js)

All processes running put their output to the terminal in which i typed in gulp command. So I've full view of database transactions, server requests, console logs, etc... in one place.

To debug though, I have auto attach on. which connects vscode to debugger start by gulp/nodemon/node --inspect. debugger works.

Problem is now i've TWO terminals to look at. I wish everything could be in just debug console.

Which I can partly do if I launch gulp through launch.json but it rather restarts whole gulp process each time change is made. Instead of reattaching to new nodemon process. Or If I disable restart flag. Then it doesn't connect except the first time it was launched. regardless of auto attach is on or not.

Let me know if it make sense.

**Comment by roblourens** [comment]
I see. I don't have a good solution to that. If the output from your node process also goes to the terminal, maybe you can just see the output there, although it's not interactive.
