### ISSUE TITLE
_tryExtHostHandshake depends on winjs.promise timing

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#57820]
This commit https://github.com/Microsoft/vscode/commit/7224bb340dfbd5d7eb11944b39c43675eb58a557 apparently broken debug in weird ways. The `$registerDebugTypes` was called anymore. This commit fixed it again: 
https://github.com/Microsoft/vscode/commit/407a48525a7732774a1fa1a6123f4ff75d4749e7

**Comment by alexandrudima** [comment]
How can that break debugging 🦀

**Comment by jrieken** [comment]
Good question... I was in revert mode only but my theory is that it sends a message before we are ready for it to be processed (it sends something in a ctor-call).

**Comment by alexandrudima** [comment]
After some investigation: this is not about the ctor.

`TPromise` and `Promise` behave in the same way around the invocation order of the ctor.

The difference is the invocation of `then`, where `Promise` always invokes `then` on the next tick. The result of the promise is an `IMessagePassingProtocol` and in between those ticks to invoke the `then` handler, a message (or more) get lost.

I will look into how it would be possible to refactor this... It would almost need pause/resume functionality on `IMessagePassingProtocol`...
