### ISSUE TITLE
Debug Console only looks at the first "clear" escape sequence in a log message

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#57828]
- Debug this code:

`console.log('1\u001b[2J2\u001b[2J3');`

- The debug console shows `23`, it should show `3`

**Comment by roblourens** [comment]
Hope you don't mind me fixing it, I saw it was an easy fix.

**Comment by isidorn** [comment]
@roblourens always fell free to jump on issues, of course I do not mind
