### ISSUE TITLE
breakpoints "move" or won't stick

### ISSUE THREAD

**Issue by SogoGolf** [Microsoft/vscode#57829]
Issue Type: <b>Bug</b>

breakpoints in React app magically move, or won't stick or... really annoying and time  wasting when trying to work and debug

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:31:26.156Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.34GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.0.3
aws-amplify-vscode|aws|0.0.4
xml2json|bui|1.1.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
open-html-in-browser|cod|0.1.21
gitignore|cod|0.5.0
dart-code|Dar|2.18.0
githistory|don|0.4.2
xml|Dot|2.3.2
gitlens|eam|8.5.6
prettier-vscode|esb|1.6.1
vscode-console-wrapper|fab|0.4.0
php-debug|fel|1.12.5
php-intellisense|fel|2.3.5
php-pack|fel|1.0.2
file-icons|fil|1.0.16
flow-for-vscode|flo|0.8.2
code-runner|for|0.9.4
gc-excelviewer|Gra|2.1.26
docthis|joe|0.7.1
Kotlin|mat|1.6.0
python|ms-|2018.7.1
csharp|ms-|1.15.2
node-debug2|ms-|1.27.1
debugger-for-chrome|msj|4.9.0
color-highlight|nau|2.3.0
vetur|oct|0.12.6
remote-vscode|raf|1.1.0
vscode-icons|rob|7.25.0
code-settings-sync|Sha|3.1.2
msbuild-project-tools|tin|0.2.39
vscode-react-native|vsm|0.6.16
gitblame|wad|2.4.4
vscode-todo-highlight|way|1.0.4
twig|wha|1.0.2
vscode-js-console-utils|wht|0.7.0
vscode-import-cost|wix|2.8.0
JavaScriptSnippets|xab|1.7.0
linecount|yyc|0.1.7

(10 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
This is fixed in latest vscode. If you can still reproduce please file with reproducable steps and I will reopen
