### ISSUE TITLE
Manually restoring modified file back to saved state requires save

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5783]
- VSCode Version: 1.0.1-alpha
- OS Version: Windows 10 / Ubuntu 15.10

Steps to Reproduce:
1. Open a file with some code and save. For example

``` javascript
var test = "test"
```
1. Delete and re-type "test"

Actual:
Even though the file is restored back to its saved state, it still requires a save. This is the same behavior as VS Full, but Atom supports remembering the saved state and does not require save if the file is restored to the saved state.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/919
