### ISSUE TITLE
Proxied types are not loaded.

### ISSUE THREAD

**Issue by zavr-1** [Microsoft/vscode#57833]
Issue Type: <b>Bug</b>

When a package loads some modules via another module, their will lack Intellisense and it is not possible to click through to their definition.

VS Code version: Code - Insiders 1.27.0-insider (346018a80dd299c50cbf213e0a706ef0f35f3a67, 2018-08-24T05:12:36.061Z)
OS version: Darwin x64 15.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     P7350  @ 2.00GHz (2 x 2000)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: unavailable_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Load (avg)|7, 8, 6|
|Memory (System)|8.00GB (0.16GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_24582|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.5.0
code-spell-checker|str|1.6.10

</details>

from file A
```js
import { throws, equal } from 'zoroaster/assert'
```

where `zoroaster/assert` is a proxy file (only has `module.exports = require(./build/assert)`) to `zoroaster/build/assert` which has: 

```js
let throws = require('assert-throws'); if (throws && throws.__esModule) throws = throws.default;
const $assert = require('assert');
const $assert_diff = require('assert-diff');



module.exports.assert = $assert
module.exports.equal = $assert.equal
module.exports.ok = $assert.ok
module.exports.deepEqual = $assert_diff.deepEqual
module.exports.throws = throws
//# sourceMappingURL=index.js.map
```

```
1. git clone https://github.com/artdecocode/vscode-require-types.git
2. code-insiders vscode-require-types
```
3. open test/spec/default.js
4. try use throws function, there will be no intellisense. try click through -- it will get to the parent package, but not any further than that.

![test](https://user-images.githubusercontent.com/21156791/45008852-89eeeb80-b00d-11e8-9b4d-9265c13eef35.png)

5. Uncomment `// import assertThrows from 'assert-throws'` line. Now, `throws` works fine. 

![test](https://user-images.githubusercontent.com/21156791/45008880-bdca1100-b00d-11e8-9db0-eb8736b4e994.png)

Whenever the proxy in form of `zoroaster/assert` is removed in favour of `zoroaster/build/assert`, then things work. I suppose I have to `ln` the `assert` rather than use `module.exports = require('./build/assert')` but it's still a bug.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#26921
