### ISSUE TITLE
Freezes when searching using RegExp

### ISSUE THREAD

**Issue by imanjra** [Microsoft/vscode#57834]
- VSCode Version: 1.26.1 and 1.27
- OS Version: Windows 10

Steps to Reproduce:

1. Open a file (JSON file for me, but issue should be same for other files)
2. Open inline search (CTRL+ f) and enable RegExp option
3. "\d+"=>(.|\s|\n)*?,
_As soon as the comma after the question mark is added in step 3, vs code freezes and have to be relaunched_

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/30874
