### ISSUE TITLE
Command not readable when keybinding row is selected in light theme

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#57836]
Issue Type: <b>Bug</b>

- Open keybindings editor in light theme
- Search for "suggest"
- Click on any row

The "suggest" word in the command is not readable

<img width="522" alt="screen shot 2018-09-03 at 10 57 40 pm" src="https://user-images.githubusercontent.com/16890566/45012671-fc8ba700-afcc-11e8-8d72-e6d9c1e1539f.png">

VS Code version: Code - Insiders 1.27.0-insider (1097b5e9ed81d5f9241648774b35048be168c203, 2018-08-31T10:32:54.890Z)
OS version: Darwin x64 15.6.0

**Comment by bpasero** [comment]
@misolori didn't you fix this for breadcrumbs?

**Comment by misolori** [comment]
Applied the same fix for the breadcrumbs:

![image](https://user-images.githubusercontent.com/35271042/45046471-1f4ca880-b02b-11e8-9503-d99e64810f57.png)


The only other minor issue is that the Mono font doesn't have additional font weights so on selection the highlight text blends and doesn't stand out:

![image](https://user-images.githubusercontent.com/35271042/45046537-4c00c000-b02b-11e8-973d-8de97ed78a0e.png)
