### ISSUE TITLE
Sync/Export Settings and installed extensions to other devices?

### ISSUE THREAD

**Issue by nathanatgit** [Microsoft/vscode#57839]
I'm using Code in three different devices in lab, home and personal computer, one linux and two windows.
It takes me a lot of time to setup for the same coding environment.
I made some changges in settings or installed a new extension, then i have to do the same thing on other two devices.

I'm wondering is there a way to export current user settings and installed extension of VS code?
or a more modern way like syncing them using microsoft account? (of course there should be a setting on which can be synced and which can't)

Thanks for consideriation.

**Comment by sandy081** [comment]
Duplicate of #2743


You can also try https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync syncs extensions
