### ISSUE TITLE
Option to disable forced interpreter name aliasing?

### ISSUE THREAD

**Issue by VernonBush1795** [Microsoft/vscode#57832]
Hello,

I recently started using python with Anaconda, and I'm having an issue with my environment getting aliased.  

Initially, I could activate my environment from the vs code terminal with no issue just using ctrl+shift+p and then selecting the interpreter, but ever since it's gotten aliased to "base" (I'm assuming this happens after a certain number of times of selecting a given interpreter?), it refuses to work and seems like it defaults back to Anaconda's default environment (which is also named base) to run things.  

Specifically, the name of the selectable interpreter changed from Anaconda, Inc, Python 3.6.6 to Anaconda, Inc, Python 3.6.6(base).  If I click the interpreter and run a "python" command before this name alteration, it tells me I'm using python 3.6.6 and worked fine, but since "base" got appended to the end, it tells me I'm using 3.6.5 and fails to find any of my modules.

It should be noted that if I run "activate -virtenv-" from an external terminal, it works as expected (we get to 3.6.6).  However, if I run "activate base" in the external terminal, we go to 3.6.5.  Is there anyway to force vscode to not alias the name of my interpreter?  

System info/Specs/Extensions:

CPUs | AMD Ryzen 7 1700X Eight-Core Processor (16 x 3394)
-- | --
GPU Status | 2d_canvas: enabledchecker_imaging: disabled_offflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwarerasterization: enabledvideo_decode: enabledvideo_encode: enabledwebgl: enabledwebgl2: enabled
Memory (System) | 11.93GB (4.09GB free)
Process Argv | C:\Program Files\Microsoft VS Code\Code.exe
Screen Reader | no
VM | 0%

html-snippets | abu | 0.2.1
-- | -- | --
vscode-file-templates | bam | 1.1.0
vscode-django | bat | 0.17.0
django-html | bib | 1.2.0
django-snippets | bib | 1.1.0
vscode-intelephense-client | bme | 0.8.8
npm-intellisense | chr | 1.3.0
path-intellisense | chr | 1.4.2
php | cod | 0.9.0
web | cod | 0.9.0
bracket-pair-colorizer | Coe | 1.0.59
vscode-eslint | dba | 1.5.0
jupyter | don | 1.1.4
python-extension-pack | don | 1.4.0
vscode-npm-script | eg2 | 0.3.5
prettier-vscode | esb | 1.6.1
php-debug | fel | 1.12.5
php-intellisense | fel | 2.3.5
auto-close-tag | for | 0.5.6
code-runner | for | 0.9.4
beautify | Hoo | 1.4.2
search-node-modules | jas | 1.3.0
node-module-intellisense | lei | 1.5.0
MagicPython | mag | 1.0.12
vscode-exec-node | mir | 0.5.0
vscode-apache | mrm | 1.1.1
mssql | ms- | 1.4.0
anaconda-extension-pack | ms- | 1.0.0
python | ms- | 2018.7.1
csharp | ms- | 1.15.2
debugger-for-chrome | msj | 4.9.0
vscode-code-outline | pat | 0.2.1
vscode-yaml | red | 0.0.15
LiveServer | rit | 5.1.1
vscode-zipexplorer | sle | 0.3.1
php-ci | sma | 0.2.10
python | tht | 0.2.3
vscodeintellicode | Vis | 1.0.3
nodejs-extension-pack | wad | 0.1.9
jinja | who | 0.0.8
JavaScriptSnippets | xab | 1.7.0
html-css-class-completion | Zig | 1.17.1

**Comment by dbaeumer** [comment]
@VernonBush1795 I am pretty confident that this is caused by the Python extension you are using. Please reoport the bug there.

If you think otherwise please ping me and I will reopen the issue.
