### ISSUE TITLE
Files.WatcherExclude not reflecting the Settings.........

### ISSUE THREAD

**Issue by SivaThiyagarajan** [Microsoft/vscode#57849]
I need to upload some image in src/assets folder. when I tried to upload an image, the page is getting refreshed. After that I came to know it is due to filewatching. So to avoid the folder from being watched I Created a workspace setting in .vscode/settings.json and made the following codes

    "files.watcherExclude": {
        "**/.git/objects/**": true,
        "**/.git/subtree-cache/**": true,
        "**/node_modules/*/**": true,
        "**/src/assets/**":true
    }

But sadly its not working.Still the Refresh is happening, Thanks in  advance.

**Comment by SivaThiyagarajan** [comment]
I tried that glob pattern also but not working.

**Comment by bpasero** [comment]
@SivaThiyagarajan which OS are you on?
