### ISSUE TITLE
Open recent project issue

### ISSUE THREAD

**Issue by thenexus00** [Microsoft/vscode#57844]
Issue Type: <b>Bug</b>

In the latest version of the app when you go to file > new window and hit "more" to open a new project and start looking/typing for the project the window flickers to a blank project with open folder button in the tree view.

I am on a mac with latest OS and VSC and this has only started to happen since the most recently release.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:31:26.156Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 4|
|Memory (System)|16.00GB (0.36GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
Bookmarks|ale|9.0.3
flutter-snippets|ale|0.0.2
vscode-color|ans|0.4.5
razor-plus|aus|0.1.4
htmltagwrap|bra|0.0.7
bracket-pair-colorizer|Coe|1.0.59
vscode-svgviewer|css|1.4.4
dart-code|Dar|2.18.0
flutter|Dar|2.18.0
githistory|don|0.4.2
jquerysnippets|don|0.0.1
string-convert|dxc|0.1.4
vscode-html-css|ecm|0.2.0
vsc-material-theme|Equ|2.4.2
prettier-vscode|esb|1.6.1
live-html-previewer|hdg|0.3.0
beautify|Hoo|1.4.2
vscode-nuget-package-manager|jmr|1.1.6
drupal-7-snippets|jun|0.0.7
vscode-liquid-snippets|kil|1.1.1
sftp|lix|1.4.1
VS-code-drupal|mar|0.0.12
ecdc|mit|0.12.0
prettify-json|moh|0.0.3
vscode-apache|mrm|1.1.1
cpptools|ms-|0.18.1
csharp|ms-|1.15.2
vsliveshare|ms-|0.3.623
debugger-for-chrome|msj|4.9.1
language-liquid|nei|0.0.3
vscode-css-peek|pra|2.1.0
java|red|0.30.0
aspnet-helper|sch|0.6.4
vscode-spotify|shy|2.6.1
pdf|tom|0.3.0
lorem-ipsum|Tyr|1.2.0
vscode-java-debug|vsc|0.12.1
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.8.0
vscode-maven|vsc|0.10.0
quokka-vscode|Wal|1.0.144
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.7.0
ReactSnippets|xab|2.2.0
html-css-class-completion|Zig|1.17.1

(7 theme extensions excluded)

</details>

**Comment by dbaeumer** [comment]
@thenexus00 can you provide a screen cast that demos this?

**Comment by thenexus00** [comment]
Sorry for the delay.
http://recordit.co/y4cbgWxYPa
I am not touching anything.
So from the time you have a new window, go to open an existing project and your reading to select the right one it closes.

**Comment by bpasero** [comment]
@thenexus00 hm, I cannot reproduce with one file I tried. Does this reproduce with all files? Also what about folders?

**Comment by thenexus00** [comment]
It’s not files, it’s the selecting of folders. If your not quick it just closes the explorer part. The window remind open with the “open folder” button in the nav. 
Only since the last update and one of my other devs has now realised this is happening to him as wel.

**Comment by thenexus00** [comment]
Just as a note: the release today - but still exists for me.
The other team members do more key command route to open projects. I am a bit more mouse use based myself and why I see it more then they do, but if I try on their mac’s I can replicate.

**Comment by thenexus00** [comment]
I am not sure if this is helpful but it also may be the sidebar.
When I open a new window and leave it you can see it automatically opens as an empty project with the sidebar:
http://g.recordit.co/a1QbE3dH7a.gif

Touching nothing, so when I open new window and then click more and start to look at a folder it may slow this but it still happens unless I am fast enough to select the project first.

So I do not think it is the picker, it is a refresh of the window as a result of this making an empty project folder window on its own.

**Comment by thenexus00** [comment]
A little more:
Uf U start the "more" access window but do nothing (no typing) the Explorer change does not effect it. If I have started typing to find a site and the Explorer sidebar updates it closes the window.

**Comment by chrmarti** [comment]
This looks like an extension is causing the Explorer to be revealed. Does it reproduce when starting with `code --disable-extensions`?

**Comment by thenexus00** [comment]
First thing I tried. 100%.

**Comment by bpasero** [comment]
@thenexus00 does it reproduce if you run "`code --user-data-dir <some empty folder>`"?
