### ISSUE TITLE
Ctrl+Shift+E inerts special characters into file instead of showing Explore Pane

### ISSUE THREAD

**Issue by cbsiddharth** [Microsoft/vscode#57842]
I waited for an answer at [stackoverflow](https://stackoverflow.com/questions/52032340/ctrlshifte-inerts-special-characters-into-file-instead-of-showing-explore-pane) for 10 days before posting the same question here.

===

I prefer having the "Activity Bar" hidden and use the key combinations Ctrl+Shift and E,F,G or X to reach the individual panes.

When I am in the Search pane (revealed with Ctrl+Shift+F) with focus on the editor, I hit Ctrl+Shift+E with the intention of reaching the Explorer pane; instead of exposing the Explorer pane, code inserts the character e (all subsequent characters) with a black underline.

Now, I suppose this is some feature to insert special characters into editors but, Ctrl+Shift+E as a shortcut for this seems little too conspicuous don't you think? especially when it is already been used for something else?

I'm not sure when this behavior was changed but I remember that it used to work earlier. I there a way by which I can disable this special character insertion feature and restore order?

**Comment by bpasero** [comment]
@cbsiddharth are you on Linux?

**Comment by stuartspencer** [comment]
I'm having the same issue. I am using Linux.

**Comment by stuartspencer** [comment]
Actually, my own experience is that ctrl + shift + E in an editor pane prints the 'e' character and any other subsequent characters entered. Then, if backspace is pressed the whole word is deleted, but any other alphanumeric is pressed it prints the string chunk again but with the last character replaced with the new character input. Pressing space seems to delete it and exit this mode.

Not sure what is going on but it seems to be a mode of behaviour.

**Comment by cbsiddharth** [comment]
@bpasero, yes. Thanks.

@David-Else, seriously, this has crossed the just-an-annoyance line.
