### ISSUE TITLE
Clicking a stack frame with no source causes all other thread stacks to collapse

### ISSUE THREAD

**Issue by andrewcrawley** [Microsoft/vscode#5784]
- VSCode Version: master (b2f6194)
- OS Version: Ubuntu 14.04

Steps to Reproduce:

1. Compile https://gist.github.com/edumunoz/6e2ca90d4b5d3dbfa5340576e79ac113 with `g++ -g -std=c++11 -pthread hello.cpp -o hello`
2. Install the [C++ debug adapter](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools)
3. Set a breakpoint on line 7 (the body of the `test` function)
4. When the breakpoint is hit, expand all the threads so you can see their stack frames
5. Click a stack frame that doesn't have source (e.g. `clone` or `create_thread`)

At this point, all threads except the one with the frame that was clicked collapse.  Clicking a stack frame that has symbols (e.g. `main()` or `test()`) doesn't cause any any other threads to collapse.

I would expect that the code view would change to the "Source ... is not available" view without collapsing any of my expanded threads.

@isidorn @weinand

**Comment by andrewcrawley** [comment]
Verified that this worked as I'd expect in build 0.10.13-insider.

**Comment by isidorn** [comment]
@aeschli you are on a linux machine, and all this should work out of the box so giving to you to verify.
