### ISSUE TITLE
Allow to run multiple sessions on different display servers

### ISSUE THREAD

**Issue by cbuschardt** [microsoft/vscode#57843]
VSCode Version: 1.26.1
OS Version:  Ubuntu 18.04.1 LTS

Steps to Reproduce:

1.  Run vncserver
2.  Connect to vncserver
3.  Run visual studio code from VNC
4.  Launch visual studio from outside VNC, and note new window appears in VNC

Does this issue occur when all extensions are disabled?: Yes

Steps to resolve:
1. The contents of the DISPLAY variable should be used in determining whether a running instance of code is a candidate for use.

**Comment by ewnavilae** [comment]
+1

**Comment by fyangw** [comment]
+1, We need this feature as well.

**Comment by omicronns** [comment]
Is there any workaround for this? I can't run two instances of vscode on two vnc sessions on same machine, because when trying to run second instance, it appears on display where first instance is already running. When i close all vscode windows it appears on correct session display.

**Comment by ewnavilae** [comment]
Are there any news regarding this issue? I'm not even aware if this is something that has been merely neglected or actually takes a lot of effort to implement. Can we have some feedback? Should someone be mentioned here?

**Comment by ewnavilae** [comment]
Makes sense! Thank you for the feedback, bot! If it ever becomes critical I'll fork it and submit a pull request :)

**Comment by odedsa3** [comment]
+1, for us this is a must, please add.

**Comment by messiem** [comment]
+1 here as well, I routinely use several VNC sessions on the same machine and can only open vscode within one of them.

**Comment by mackerelKhin** [comment]
+1, hope this feature will be added.

**Comment by messiem** [comment]
I just checked and it only works if using 2 different data directories, which means setting up some sort of sync between them to ensure things remain consistent (I tried with a symlink, doesn't work).

**Comment by wc1620** [comment]
It used to work for me to have 2 code running on different VNC servers session but now it just stopped for me, anyone has any work around for this?

**Comment by relliky** [comment]
vscode/1.52.1 fixed this problem. 

The problem is coming back at 1.76.2. I will stick with 1.52.1 then
