### ISSUE TITLE
Remove artificial 500ms delay from symbol search

### ISSUE THREAD

**Issue by matklad** [Microsoft/vscode#57845]
Hi!

Currently, there's at least [500 ms delay](https://github.com/Microsoft/vscode/blob/2c894f1998153dc700f63619ed32e94e843dc095/src/vs/workbench/parts/search/browser/openSymbolHandler.ts#L133) when searching for symbols. The delay is very noticeable, and makes VS Code feel slow, in contrast to IntelliJ, which pops up symbol search results immediately.

I suggest removing/reducing this delay, at least for cases where query string is not empty.

**Comment by SirIntruder** [comment]
Pretty please, this is very noticeable and flaky.

Reason why this existed in the first place is probably extremely slow rendering time of symbol search results. It got improved over time, but maybe further improvements are necessary. Problem is, in non trivial projects you can get 10s of thousands of symbols when you start typing, and nothing is displayed until they all got rendered.

One thing to consider is to add symbol count cap on the vscode side. 99.99% of time you don't care about displaying a list of 10000 symbols  - users can simple narrow down search result by typing more characters. Having a default cap of ~100 symbols would solve performance without impacting users much. Some "incremental rendering" where you display best matches right away would probably be "the right thing" (I would be perfectly happy with a stupid cap)
