### ISSUE TITLE
Cannot search extensions 

### ISSUE THREAD

**Issue by jdaviesttm** [Microsoft/vscode#57853]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Open VSC
2. Search for any extension
3. No results shown

![screen shot 2018-09-04 at 11 15 58](https://user-images.githubusercontent.com/26899786/45025642-ef55d300-b033-11e8-9cbc-34843212359c.png)

I want to install Quokka.js but cannot search for any extensions.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Kamshak** [comment]
Same as https://github.com/Microsoft/vscode/issues/57851

**Comment by mglgmz** [comment]
looks like someone messed the marketplace

![image](https://user-images.githubusercontent.com/20958398/45038054-d3076580-b036-11e8-8a0a-5490c9ff3a9e.png)

**Comment by Tamozafari** [comment]
the marketplace is down

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/57851

**Comment by kinglion580** [comment]
I also get this problem

**Comment by Fpckalk** [comment]
Guessing most of you already know this, but the marketplace is up again. Could be a lucky timewindow for me, but here's hoping.

**Comment by elciopa** [comment]
The marketplace is up right now but are you able to search any extensions by typing a part of the name or the full name? I get the list of them only by precompiled searches like "Show Popular Extensions" or "Show Recommended Extensions", etc..

**Comment by jdaviesttm** [comment]
Can't search by part name or full name. Nothing appears in the search
