### ISSUE TITLE
Extensions not showing

### ISSUE THREAD

**Issue by sommy1994** [Microsoft/vscode#57859]
I installed vscode for ubuntu yesterday and tried installing an extension which worked fine, but today i cant see any other extensions, and i get errors in my console.
![screenshot from 2018-09-04 12-49-52](https://user-images.githubusercontent.com/30838087/45029614-35fdfa00-b041-11e8-8823-002b68569107.png)

**Comment by Markoscl** [comment]
I think they are down for everyone at the moment:

https://marketplace.visualstudio.com/

![image](https://user-images.githubusercontent.com/7879631/45029885-66966180-b04a-11e8-8674-501a9630c305.png)

**Comment by sommy1994** [comment]
Okay. Thanks..
