### ISSUE TITLE
QuickPick: Selection cleared immediately

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#57850]
This seems to be a bugfix for multi-select that affects single-select: https://github.com/Microsoft/vscode/blob/d33f082f5450db160bbd4b5230bfc402234b87f1/src/vs/workbench/browser/parts/quickinput/quickInputList.ts#L288

**Comment by aeschli** [comment]
The fix breaks my file dialog. After a selection event from clicking I set new inputs items.
Due to the change, all new items become active and are marked as selected.

**Comment by aeschli** [comment]
I reverted the change with 8d3a6477afbed1ee3ac629a573ff154b614a59d0

**Comment by chrmarti** [comment]
@aeschli Was this closed by accident?
