### ISSUE TITLE
No extensions found

### ISSUE THREAD

**Issue by rajat19** [Microsoft/vscode#57856]
Issue Type: <b>Bug</b>

No extensions are displayed when we search for them.
Also no popular extension or any search results displayed

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:34:20.517Z)
OS version: Linux x64 4.15.0-33-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 2720)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.69GB (0.13GB free)|
|Process Argv|/usr/share/code/code .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.5.0
gitlens|eam|8.5.6
python|ms-|2018.7.1
cpptools|ms-|0.18.1
material-icon-theme|PKi|3.5.3
vscode-icons|rob|7.25.0
JavaScriptSnippets|xab|1.7.0
markdown-all-in-one|yzh|1.6.0

(1 theme extensions excluded)

</details>

**Comment by carlopolisini** [comment]
I am experiencing the same issue on Ubuntu 18.04 and same VSCode version. Even selecting Recommended or Popular extensions, no results are found and No extensions found is shown as message.

**Comment by RevoluPowered** [comment]
duplicate of https://github.com/Microsoft/vscode/issues/57851

**Comment by rajat19** [comment]
Seems marketplace is itself down
Closing this issue as other similar issues are already present https://github.com/Microsoft/vscode/issues/57851 and https://github.com/Microsoft/vscode/issues/57853
