### ISSUE TITLE
Feature Request: Browser debugging with javascript coming off different subdomain

### ISSUE THREAD

**Issue by pipja** [Microsoft/vscode#5785]
- VSCode Version: 1.0.0
- OS Version: Win7 Professional 64bit
- Umbraco v4

Steps to Reproduce:
1. Your local webroot: &lt;drive&gt;:\ \<webroot&gt;\ \<yoursite&gt;
2. Your local js directory: &lt;drive&gt;:\ \<webroot&gt;\ \<yoursite&gt;\ \<jspath&gt;\file.js
3. Your local website: http://abc.xyz.something/ pointing to yoursite (you may have multiple subdomains pointing to different sites, umbraco style)
4. Your javascript delivery: http://js.xyz.something/ \<jspath&gt;/file.js
5. Firing chrome browser debugger on http://abc.xyz.something/ will start Chrome and goes to the page but can't hook onto the javascript, potentially because of routing confusion?

Suggestion:
Improve chrome browser debugging to allow for custom subdomain/host binding so that browser debugging will hook properly

**Comment by bpasero** [comment]
@pipja can you please report this against the Chrome Debug extension?
