### ISSUE TITLE
[loc][Query] Proposed resource text review

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#57869]
For string below community member is suggesting that source text is strangely worded. Can you please check it and confirm whether it would make sense to update it? Thanks!

**Original comment**
EN_GB ISSUE
Is this string correct? It seems very strangely worded.
by Swotboy2000, 7 days ago

````
'editor.hover.delay': {
'type': 'number',
'default': EDITOR_DEFAULTS.contribInfo.hover.delay,
'description': nls.localize('hover.delay', "Time delay in milliseconds after which to the hover is shown.")
},
````

[**File link**](https://github.com/Microsoft/vscode/blob/a455e51841552ba3ffae27f5a650802e4e819157/src/vs/editor/common/config/commonEditorConfig.ts#L355)

**Comment by ramya-rao-a** [comment]
Updated to "Controls the delay in milliseconds after which the hover is shown."

**Comment by josefhosek** [comment]
@ramya-rao-a Thanks!
