### ISSUE TITLE
Settings not saved when using new installer

### ISSUE THREAD

**Issue by jdmichel** [Microsoft/vscode#57868]
We have written the needed data into your clipboard because it was too large to se
Issue Type: <b>Bug</b>

VSCode kept nagging me after the latest update to instead use the msi installer, and assured me it would not lose settings. On one machine I installed without removing the current version, and when it popped up a dialog warning me that I should first uninstall the old version, I chose to go ahead with the install, and ended up with both installed. 
On a second machine, I chose to listen to the dialog and first uninstall, but lost all of my settings. (I mainly notice that my keyboard shortcuts are reset to default).  You might want to make your notifications a little more clear.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.61GB (22.65GB free)|
|Process Argv|C:\Users\justin.michel\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vetur|oct|0.12.6

</details>
nd. Please paste.

**Comment by joaomoreno** [comment]
> On a second machine, I chose to listen to the dialog and first uninstall, but lost all of my settings.

Code will not delete your settings and/or keybindings on uninstall. Something else must've gone broken. Please check `%APPDATA%\Code\User\settings.json` to see whether you still find them there.

**Comment by mohsenkhanpour** [comment]
Same happened to me too. I had created a `data` folder to make my setting portable, unfortunately the latest update has deleted all my extensions and settings from this folder.
