### ISSUE TITLE
Server returned 503 error.

### ISSUE THREAD

**Issue by mamton** [Microsoft/vscode#57867]
I have just installed VSCode from your website but for some reason I am continually getting a "Server returned 503" error and I have no idea how to fix it. If I try to install support for JavaScript i get the error, if I go to the extensions tab it just shows a blank with no extensions listed, if I search for an extension such as Chrome it shows no extensions for Chrome.

As far as I know there is no proxy setup, unless my internet provider has set one up (we live in dubai). 

I have installed it on my new Macbook Pro as well and it is having the exact same issue as my iMac. I have attached a few pictures. 

I'm totally lost, any help would be appreciated. Chrome, Firefox, Safari all work perfectly.
![screen shot 2018-09-04 at 5 08 00 pm](https://user-images.githubusercontent.com/12251489/45033426-8dae5c80-b065-11e8-8985-cbe5ee0ca9e8.png)
![screen shot 2018-09-04 at 5 04 40 pm](https://user-images.githubusercontent.com/12251489/45033427-8dae5c80-b065-11e8-9dc0-985ab94332f8.png)
![screen shot 2018-09-04 at 5 12 06 pm](https://user-images.githubusercontent.com/12251489/45033488-b9314700-b065-11e8-953a-2d006b95eb87.png)

**Comment by exetico** [comment]
@Javac7 - Guess this is why. I'm pretty exiced about Google already cached this issue 🗡 👍 

```Sorry! Our services aren't available right now.
We're working to restore all services as quickly as possible. Please check back soon.

Ref A: 1234C41DAAD5413CAFA66A746083CDE0 Ref B: AMS04EDGE0109 Ref C: 2018-09-04T13:55:23Z```

**Comment by devalnor** [comment]
![relax](https://media.giphy.com/media/tyqcJoNjNv0Fq/giphy.gif)

**Comment by evillt** [comment]
I thought is my network problem too, hah hah.🙃

**Comment by sangyumimi** [comment]
exactly the same issue, wasted half hours to figure out if my proxy(live in China) failed me...

**Comment by as842718** [comment]
Facing same ! Any idea when it will up

**Comment by H3dgy** [comment]
Same issue, hoping it will be up again soon

**Comment by isc30** [comment]
OH MY! after 3 hours of changing network configurations I find this hahahahaha

**Comment by prakashbsamanta** [comment]
was about to reinstall vs code .. glad .. saw this thread first ...
hope the server will get back online pretty soon..

**Comment by marcosgabbardo** [comment]
praying for the coder god...

**Comment by atroach** [comment]
Ugh, just reinstalled then found this thread. At least I was planning on moving over to the user setup distribution anyway.

**Comment by WCarrollSTO** [comment]
They must be running Windows Server.

**Comment by zigang93** [comment]
opsss.. i also wonder why not able to search..

**Comment by Jaszczab** [comment]
I've just setted up my fresh linux install and i was thinking that this error is my fault. But now I'am happy in my sadness...

**Comment by ClarkNguyen** [comment]
I though that cause my network problem...

**Comment by mjbvz** [comment]
Duplicate of #57851

**Comment by suarezluis** [comment]
And there I was uninstalling and re-installing lol

**Comment by AsnelChristian** [comment]
Damn, I had to reinstall thrice, before getting here :) :)

**Comment by miki80x** [comment]
For the heavens sake, I reinstalled VS twice.

**Comment by alexod87** [comment]
Ха, Смешные ребята))) Переустанавливали несколько раз??? Зачем??
