### ISSUE TITLE
suggest

### ISSUE THREAD

**Issue by mwc** [Microsoft/vscode#5787]
- VSCode Version: 1.0.1-insiders
- OS Version: Windows 10 14328

(in Chinese)
1. [HTML] 属性在输入 = 号时，自动补全 " "
2. [HTML] 智能提示 url 补全，如 script / link / img 等标签的 src=" "  或 href=" "，支持提示文件夹内的文件列表。
3. [HTML] 支持 style=" " 的样式智能提示
4. [HTML] 修改开始标签时，自动同时修改关闭标签，反之亦然
5. [VSCode - Side Bar - Explorer] 右击 HTML 文件增加菜单 "使用浏览器打开(IE/Chrome .e.g.)
6. [Editor] 编辑器中的文本鼠标拖拽位置
7. [VSCode] 文件另存为网页/图片
8. [CSS] 支持点击颜色值显示颜色选择对话框
9. [CSS] 支持图片转 base64 编码字符串
10. [VSCode - Side Bar - Explorer] 支持类似 ASP.NET 的文件关联显示，如：

    index.aspx (可折叠)
         index.aspx.cs

    对于 TS 文件则可以：
    app.ts
        app.js
             app.min.js

**Comment by yyjazsf** [comment]
要转英文，老外看不懂😄

**Comment by bpasero** [comment]
Please report this issue again in english. Thanks!
