### ISSUE TITLE
language setting is invalid

### ISSUE THREAD

**Issue by HeartAndSoul001** [Microsoft/vscode#57872]
Issue Type: <b>Bug</b>

After I modified the file .json to change the language, then close the vscode, and restart it, the modification of language has not work.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.84GB (11.10GB free)|
|Process Argv|D:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.8.7
cmake-tools-helper|mad|0.1.1
cpptools|ms-|0.15.0
cmake-tools|vec|0.10.4
debug|web|0.21.2

</details>

**Comment by mjbvz** [comment]
Can you please explain what "change the language" means? What are the exact steps to do this?

**Comment by HeartAndSoul001** [comment]
I want to change the display language.Then I follow the instruction on the internet:first,input crtl+shift+p to configurate the display language;second,use "ch-CN" to replace the "en";finally,I save the json file and restart the vscode.However,it doesn't work.

**Comment by HeartAndSoul001** [comment]
I want to change the display language.Then I follow the instruction on the internet:first,input crtl+shift+p to configurate the display language;second,use "ch-CN" to replace the "en";finally,I save the json file and restart the vscode.However,it doesn't work.

**Comment by mjbvz** [comment]
Can you please make sure that you are fully restarting VS Code and not just closing the current window? Also, are you using the user level VS Code install or the system level one?

**Comment by HeartAndSoul001** [comment]
![default](https://user-images.githubusercontent.com/34875851/45064788-4c12c580-b0e8-11e8-9ec3-1a8ed25f39e0.png)
this picture is what it display when I restart the vscode.

**Comment by non-non** [comment]
I'm facing the same problem.
