### ISSUE TITLE
[loc][Query] Potential source text issue

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#57870]
For string below community member is suggesting potential source text update. Can you please check it and confirm whether it would make sense to update it? Thanks!

**Original comment**
EN_GB ISSUE
Should this string read as '...the find operation is carried out on...'
by Swotboy2000, 7 days ago

````
'editor.find.autoFindInSelection': {
'type': 'boolean',
'default': EDITOR_DEFAULTS.contribInfo.find.autoFindInSelection,
'description': nls.localize('find.autoFindInSelection', "Controls whether the find operation is carried on selected text or the entire file in the editor.")
},
````

[**File link**](https://github.com/Microsoft/vscode/blob/a455e51841552ba3ffae27f5a650802e4e819157/src/vs/editor/common/config/commonEditorConfig.ts)

**Comment by ramya-rao-a** [comment]
Updated to "Controls whether the find operation is carried **out** on selected text or the entire file in the editor."

**Comment by josefhosek** [comment]
@ramya-rao-a thanks!
