### ISSUE TITLE
Allow to follow symlink / open original from explorer

### ISSUE THREAD

**Issue by borekb** [Microsoft/vscode#57873]
Since #11539, explorer indicates symlinks like this:

![image](https://user-images.githubusercontent.com/101152/45038421-7b322400-b061-11e8-93cc-20897f78681d.png)

It would be nice to be able to navigate to the actual location quickly, either by a command in a context menu or something like Cmd+click on the arrow.

**Comment by borekb** [comment]
Good question. I only had this specific `node_modules/.bin` use case in mind in which case the explorer sidebar would just "scroll" me to the right location but you're right that the file might live outside of the workspace. In that case, probably the best behavior would be to open Finder / Windows Explorer on that file.

**Comment by borekb** [comment]
The same as if I opened the symlinked file and invoked "Reveal Active File in Sidebar".

For example, `<workspace>/node_modules/.bin/tsc` is a symlink to `<workspace>/node_modules/typescript/bin/tsc`. When I invoke this hypothetical **Show Original** command, it scrolls me from `.bin/tsc` to `typescript/bin/tsc` in VSCode's explorer.

**Comment by bpasero** [comment]
@borekb in most cases the symlinked file is probably not in the explorer tree but somewhere outside, what should hapen then?

**Comment by borekb** [comment]
I think it would be best then to open the file in Finder / Windows Explorer as suggested [above](https://github.com/Microsoft/vscode/issues/57873#issuecomment-418398976).

**Comment by Azmisov** [comment]
For those coming across this issue, I've tried the **Symlink Follow** extension by zaucy and it works well for this.

**Comment by vorburger** [comment]
> **Symlink Follow** extension by zaucy

That's https://marketplace.visualstudio.com/items?itemName=zaucy.symlink-follow, which has the most installs; this opens a pop-up what says: _"... is a symlink. The real path is ... [Cancel] [Follow Symlink]"._

There's also:

* https://marketplace.visualstudio.com/items?itemName=AlanZhang.open-symlink-source, from https://github.com/zcfan/vscode-open-symlink-source, which adds a _Open Symlink Source_ command

* https://marketplace.visualstudio.com/items?itemName=nemytchenko.show-symlink-source, from https://github.com/inem/vscode-show-symlink-source (which is apparently a fork and continuation of https://github.com/zcfan/vscode-open-symlink-source); this _"will automatically display the path to the original file in the status bar"_

* https://marketplace.visualstudio.com/items?itemName=qpwo.follow-symlinks, from (supposedly) https://github.com/qpwo/follow-symlinks, that's is no longer available, which does not inspire confidence.
