### ISSUE TITLE
Avoid extension host communication if possible

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#57876]
Run with `--logExtensionHostCommunication` or with code change for `LOG_EXTENSION_HOST_COMMUNICATION`

* Create an empty folder
* Create a text file
* Enable auto save
* Type one character

Observe, as part of saving the extension host is invited to participate in saving, but this is a text file and there are no extensions that I have installed for formatting text files, nor do I have enabled the format on save setting.

<img width="1144" alt="screen shot 2018-09-04 at 16 52 52" src="https://user-images.githubusercontent.com/5047891/45039153-44f5a400-b063-11e8-81ee-08256f895295.png">

**Comment by jrieken** [comment]
The `$participateInSave` is used to trigger the `onWillSave`-event - it is unrelated to formatting. I can now go in and wait for the first and last subscribers to this event and send IPC messages to enalbe/disable the main-side-listener but I doubt that will make a difference (apart from complexity). So @alexandrudima what is the cost of an empty IPC message? Do we really wanna go all in here, do the same with `onDidSave`, `onDidChangeTextDocument` etc?

**Comment by alexandrudima** [comment]
> The `$participateInSave` is used to trigger the `onWillSave`-event

Aha! Then we should leave it in. From its name I thought this message was about save participants (i.e. it was not called `$acceptOnWillSave`)
