### ISSUE TITLE
Broken syntax highlighting when combine overloading and export default

### ISSUE THREAD

**Issue by HitalloExiled** [Microsoft/vscode#57889]
- VSCode Version: 1.26.1
- OS Version: Windows 10

Steps to Reproduce:

```ts
//index.ts
export default function foo(): void;
export default function foo(bar: string): void;
export default function foo(bar?: string): void
{ }
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#663
