### ISSUE TITLE
Node debugger cannot debug node program specified by folder

### ISSUE THREAD

**Issue by waynebloss** [Microsoft/vscode#57887]
- VSCode Version: 1.26.1
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Run `node "C:\code\my\project"` and observe that node runs the program.
2. Try to debug the same program in VSCode by creating a global `launch` configuration that specifies `"program": "${workspaceFolder}"` and observe an error: `Cannot launch program "C:\code\my\project"`.

This is a bug or a bad design - *Node.js does not require a path to a `.js` file to run a program*, but VSCode is requiring it. I don't want to specify the path because I want Node.js to inspect my `package.json` file itself and run whatever is specified in there.

Without a fix for this bug, I can never have a global `launch` configuration in my `User Settings` unless every single project used the same entrypoint.

The reason I want a global launch config is because VSCode does not capture `std` output from Node and I can't see any `winston` logging output when I run debug in VSCode, so I have to add `console` and `captureOutput` settings to every project to run them properly. Here is the global launch config I was trying to create:

```js
    // Debug
    "launch": {
      "version": "0.2.0",
      "configurations": [
        {
        "type": "node",
        "request": "launch",
        "name": "Launch Program",
        "program": "${workspaceFolder}",
        "console": "internalConsole",
        "outputCapture": "std"
      }],
      "compounds": []
    }
```

**Comment by weinand** [comment]
If you have no launch configuration and press F5 then the VS Code node debugger will look inside the package.json too.

**Comment by waynebloss** [comment]
So then the bug is that when you actually use Node to run your program, you can see `stdout` but not when you run it with VSCode.

If you try to remedy the situation by adding `"console": "internalConsole", "outputCapture": "std"` to your launch config, you lose the ability to only specify folder as the path to debug.

**Comment by waynebloss** [comment]
To put it another way - The bug is that when you have a launch configuration, you cannot specify just a folder like you can when using just Node.js to run the program.

Alternatively, the bug is that when you run the VS Code debugger without a launch configuration it acts differently than when it does have a launch configuration. Furthermore, you don't see `stdout` at all.

Should I resubmit this with alternate wording or can we open this back up?
