### ISSUE TITLE
打开vsc狂占cpu！关闭就好了

### ISSUE THREAD

**Issue by xiaoping0505** [Microsoft/vscode#5788]
- VSCode Version:1.0
- OS Version: win7

![Uploading QQ截图20160426130328.png…]()
![Uploading QQ截图20160426130328.png…]()

**Comment by tishion** [comment]
Next time you create one issue please try your best to describe it in English. And make sure the screenshots can be displayed correctly.
fFr this performance issue, you need to provide at least one mini dump to locate the cause.

**Comment by bpasero** [comment]
Please report this issue again in english. Thanks!

**Comment by tishion** [comment]
Ok,  I can translate it for you. He means  that once he launched vsc, it  would consume high cpu usage. And after he closed it CPU usage would  go  down.

**Comment by xiaoping0505** [comment]
https://github.com/xiaoping0505/images/blob/master/QQ%E6%88%AA%E5%9B%BE20160426140231.png
https://github.com/xiaoping0505/images/blob/master/QQ%E6%88%AA%E5%9B%BE20160426140757.png
