### ISSUE TITLE
no extensions found

### ISSUE THREAD

**Issue by minh98** [Microsoft/vscode#57884]
OS: mac 10.13.4
VERSION: 1.26.1
when i search anything then vs code show no extensions found 
pls help me!

**Comment by minh98** [comment]
![screen shot 2018-09-04 at 10 46 20 pm](https://user-images.githubusercontent.com/26597466/45042456-ee08c280-b094-11e8-920b-1a31281ae86e.png)
![screen shot 2018-09-04 at 10 46 35 pm](https://user-images.githubusercontent.com/26597466/45042475-f8c35780-b094-11e8-9175-e2d03f536ca9.png)

**Comment by igorbb** [comment]
It seems the marketplace is down. 
https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery

Returns ```
Sorry! Our services aren't available right now.

We're working to restore all services as quickly as possible. Please check back soon.
Ref A: 868A3528BAD74109953D51EF4BB90CF4 Ref B: HEL01EDGE0314 Ref C: 2018-09-04T15:53:33Z ```

**Comment by aguilera51284** [comment]
same here!

**Comment by igorbb** [comment]
https://blogs.msdn.microsoft.com/vsoservice/?p=17405 

Also this seems to be a duplicate of :

https://github.com/Microsoft/vscode/issues/57851

**Comment by minh98** [comment]
yep

**Comment by minh98** [comment]
hope it coming soon :))

**Comment by Torraca-JZ** [comment]
Yeah, I was setting my new computer and ran into the same problem as you found. Hope they get round this problem soon.
