### ISSUE TITLE
Unverified breakpoints

### ISSUE THREAD

**Issue by Jason9199** [Microsoft/vscode#57882]
- VSCode Version: 1.26.1
- OS Version: Windows 10

Steps to Reproduce:

- for reference https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-2.1&tabs=visual-studio

1. Install dotnet core 2.1
2. Create a project using `dotnet new angular`
3. Inside the ClientApp directory run `npm install`
3. Open project in VSCode
4. Run with debugging (F5) with any break points in typescript files

Does this issue occur when all extensions are disabled?: Yes (as many as I can disable and still run dotnet core with debugging)

**Comment by weinand** [comment]
please file this issue against the dotnet debugger you are using.

**Comment by Jason9199** [comment]
@weinand I am a bit confused as to your answer. The extension I think you are referencing is the C# extension which uses OmniSharp as a debugger. However, it is not C# debugging I am having issues with. As I described in my issue, this is only a problem with debugging in TypeScript files, which leads me to believe that VSCode is not properly reading how Angular does the mapping between the TS files and the resulting JS files. C# debugging works just fine when I'm having this problem.

**Comment by weinand** [comment]
What kind of debugging are you using then?
Node.js, Chrome?

**Comment by Jason9199** [comment]
Here is my launch.json
```{
   // Use IntelliSense to find out which attributes exist for C# debugging
   // Use hover for the description of the existing attributes
   // For further information visit https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md
   "version": "0.2.0",
   "configurations": [
        {
            "name": ".NET Core Launch (web)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            // If you have changed target frameworks, make sure to update the program path.
            "program": "${workspaceFolder}/bin/Debug/netcoreapp2.1/core-template.dll",
            "args": [],
            "cwd": "${workspaceFolder}",
            "stopAtEntry": false,
            "internalConsoleOptions": "openOnSessionStart",
            "launchBrowser": {
                "enabled": true,
                "args": "${auto-detect-url}",
                "windows": {
                    "command": "cmd.exe",
                    "args": "/C start ${auto-detect-url}"
                },
                "osx": {
                    "command": "open"
                },
                "linux": {
                    "command": "xdg-open"
                }
            },
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            },
            "sourceFileMap": {
                "/Views": "${workspaceFolder}/Views"
            }
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command:pickProcess}"
        }
    ,]
}```

I do not have a specific extension installed for debugging the angular or typescript files. However my browser I'm working with is Chrome. This is the code that you get when you run `dotnet new angular` so it is the angular template for dotnet core. At first I was able to place break points in the editor in my TS files and debug without issue. So I don't know if it's an update to VSCode that I installed that contributed to the problem or not. But it is happening with a fresh project from the template both in the stable build, and the insiders build.

**Comment by weinand** [comment]
Both launch configs are of type "coreclr" which is the C# debugger.
I cannot see any TypeScript debugging in your launch.json.

**Comment by Jason9199** [comment]
Thank you for your help. I thought for sure I had debugged typescript files before in this project and I only use VSCode. Maybe something caused my launch.json configuration to change, or maybe I'm just remembering wrong. But I appreciate your help a great deal, and I'll investigate that further.

**Comment by weinand** [comment]
You can add launch configs of different types to the launch.json. Just press on the "Add Configuration..." button and pick a debug config from the list: 

![2018-09-04_22-11-40](https://user-images.githubusercontent.com/1898161/45055252-9451c980-b08f-11e8-8dcd-711c866ae35b.png)

Every installed debugger contributes to that list. And the node.js debugg is builtin. If you want to debug client side JS/TS please install "The Debugger for Chrome".
