### ISSUE TITLE
Terminal Links are broken

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#57891]
It's working in 1.26.1 but not in Insiders.

Repro:

- `npm i -g serve`
- Run it in terminal

1.26.1 (left) vs Insider (right):

![terminal-bug](https://user-images.githubusercontent.com/4033249/45049258-f0d2cb80-b032-11e8-9be7-13e3bdf699af.gif)

Marking as `important` since this impact:
- People running cli tools that output file paths for errors, such as `webpack`
- People running local versions of website

**Comment by octref** [comment]
This somehow does not repro now, although it repros a minute ago...
I'll find out the exact repro steps and update the issue.

**Comment by Tyriar** [comment]
I can't repro either and I looked at the code and nothing i sticking out as obviously wrong. Let me know if you see against and get a reliable repro.

**Comment by schmamps** [comment]
…and it's still broken after I downgraded to 1.26. Is this xterm?

**Comment by maxshelley** [comment]
> Updated from 1.26 to 1.27.0 (mainstream, High Sierra) today and having this issue with file paths, but not URLs.

I also have the same issue and can confirm it only seems to be affecting file paths but not URLs.

Possible duplicate of #57987?

Let me know if there's any debugging info I can provide.

**Comment by Tyriar** [comment]
Tracking this in https://github.com/Microsoft/vscode/issues/58256 now
