### ISSUE TITLE
Weird validation message for negative tabSize

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#57892]
![image](https://user-images.githubusercontent.com/323878/45050207-7a839880-b035-11e8-9e51-9ee5d84d04d3.png)

**Comment by roblourens** [comment]
The first part of this just comes from the `errorMessage` on editor.tabSize, which is old and doesn't seem needed anymore.

@alexandrudima that error message is from more than 2 years ago, is it ok if I delete it? Probably not many people still upgrading from an old version that had `"auto"` https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/config/commonEditorConfig.ts#L287

**Comment by alexandrudima** [comment]
:+1: to change the message. `"auto"` was used in the first few months of VS Code.
