### ISSUE TITLE
npm task detection finds nothing in multi-root workspace

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [Microsoft/vscode#57897]
Issue Type: <b>Bug</b>

1. Open one npm project in a workspace, observe that npm tasks are detected
2. Add a second npm project to the workspace, observe that no npm tasks are detected at all

Note: tried downgrading to 1.26.0, same problem there.  I suspect this is a compatibility issue with some system/environmental update, as it broke for me on ~ Aug 30th.  I had installed 1.26.1 on Aug 17th, and this was not broken initially then.

I've tried launching with all extensions disabled and the problem persists.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:34:20.517Z)
OS version: Linux x64 4.9.0-8-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 3208)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|15.55GB (3.38GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.10
markdown-preview-github-styles|bie|0.1.3
vscode-markdownlint|Dav|0.20.0
vscode-eslint|dba|1.5.0
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.38
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.6.1
beautify|Hoo|1.4.2
debugger-for-chrome|msj|4.9.0
vscode-docker|Pet|0.1.0
html-preview-vscode|tht|0.1.1
reflow-paragraph|Tro|1.3.0

(1 theme extensions excluded)

</details>

**Comment by mgabeler-lee-6rs** [comment]
Also possibly of note:

The Tasks output console reports `Error: script.match is not a function`, and then `Error: The npm task detection didn't contribute a task for the following configuration:` for each npm task configured in each project's `.vscode/tasks.json` -- all of which are Tasks 2.0.0.

**Comment by egamma** [comment]
@mgabeler-lee-6rs I cannot reproduce this problem. I´ve tried the setup below. I´ve created it as follows:

- File>Open folder  -> `project1`
- File>Add Folder to Workspace -> `project2`

Both projects contain a tasks.json file. As you can see below the tasks are properly detected.

![image](https://user-images.githubusercontent.com/172399/45551620-cf41c300-b82e-11e8-8d68-b081ede1bbfa.png)

**Comment by mgabeler-lee-6rs** [comment]
Here's a minimal test procedure that repro's the issue for me:

1. `mkdir tmp1`
2. `cd tmp1`
3. `npm init` -- accept all defaults, creates a minimal `package.json` with a placeholder `test` script
4. `cd ..`
5. Repeat above but using `tmp2` for the package
6. From a fresh empty workspace in vscode, add `tmp1` -- its `test` script shows in the 'NPM SCRIPTS' panel
7. Add `tmp2` to the workspace -- only `tmp1` shows in the detected npm scripts
8. Remove `tmp1` from the workspace -- npm scripts is now empty
9. Remove `tmp2` from workspace -- npm scripts is of course empty
10. Add `tmp2` back to the workspace -- npm scripts still empty
11. Add `tmp1` back to the workspace -- npm scripts _still_ empty

Screenshot of final state:
![image](https://user-images.githubusercontent.com/41014492/45554533-b6241c80-b804-11e8-8252-b378069a9fc8.png)

Is there a way to get debug output out of the npm task detection?  I rummaged through all the output windows and, unlike my real use case, don't even see the warning(?) messages I mentioned in the original post.

**Comment by egamma** [comment]
@mgabeler-lee-6rs thanks for the repro. There is a caching issue when a new root folder is added. The extension should also watch for workspace folder changes. 

As a work around you can I reload the window, then all the tasks are detected, see below. 

![image](https://user-images.githubusercontent.com/172399/45634582-0a4c2c80-baa3-11e8-899e-48d237c879b3.png)

**Comment by mgabeler-lee-6rs** [comment]
While the workaround addresses the repro case, it doesn't address my real case.  Trying to find a better repro that matches my real case.

**Comment by mgabeler-lee-6rs** [comment]
I was able to bisect-ish my real repo and isolate it to a package.json from a dependency in my monorepo.

`bunyan-prettystream` as a weird / invalid scripts section in its `package.json`.  Presence of this file in the `node_modules` / `pnpm` cache directories for the monorepo seems to break task detection entirely.

https://github.com/mrrama/node-bunyan-prettystream/blob/master/package.json#L26
```
  "scripts": {
    "test": "make test",
    "travis-cov": { "threshold": 70 }
  }
```

Minimal test case:
1. `mkdir tmp1 && cd tmp1 && npm init && cd -` -- take defaults for npm
2. `mkdir -p tmp2/tmp3 && cd tmp2/tmp3`
3. `npm init` -- take defaults
4. (still in `tmp2/tmp3`): Edit package.json, add:
```
  "dependencies": {
    "bunyan-prettystream": "0.1.3"
  }
```
5. `cd ..` and edit `rush.json`:
```
{
  "rushVersion": "5.0.0",
  "pnpmVersion": "2.13.6",
  "projects": [
      {
          "packageName": "tmp3",
          "projectFolder": "tmp3"
      }
  ]
}
```
6. (still in `tmp2`): `rush update`
7. Add `tmp2` and `tmp3` to a workspace, reload the window as many times as you want, no npm tasks.
8. Does show `Error: script.match is not a function` in the console

I'm guessing that it's assuming the value of each `script` key is going to be a string, and trying to call `match` on it to see if it looks like something ... scripty?  But when the package has a bogus-ish script key whose value is an object, it breaks, and the thrown exception aborts task detection?

**Comment by egamma** [comment]
Reopening

**Comment by mgabeler-lee-6rs** [comment]
Note: in addition to the "bad" `package.json` entry, it seems somehow related to the monorepo using `pnpm` instead of `npm` -- I tried just creating a simple package that installs the problem dependency via `npm`, and it didn't repro the error.  Perhaps because the 'bad' `package.json` was inside a `node_modules` folder that vscode knew to ignore, but the `pnpm` cache dirs that `rush` sets up doesn't trigger vscode to ignore them?

**Comment by egamma** [comment]
I could repro the issue with this minimal package.json

```
{
  "scripts": {
    "test": "echo test",
    "travis-cov": { "threshold": 70 }
  }
}
```

The code didn´t handle object valued scripts properly. It now skips over them since they cannot be run.
