### ISSUE TITLE
Menu interface shows glitches when hovering files in split editor

### ISSUE THREAD

**Issue by janpieterz** [Microsoft/vscode#5789]
- VSCode Version: 1.0.0, Commit fa6d0f... Shell 0.35.6, Renderer 45.0.2454.85, Node 4.1.1 (would be great if I could simply copy and paste this all from the about menu btw)
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. Open a folder.
2. Open something in split editor.
3. Move mouse

See the GIF for more insight. This is just an example project, in a bigger real life project it even goes more berserk (See image)
![vscode](https://cloud.githubusercontent.com/assets/383634/14808948/e539c594-0b89-11e6-97a0-4bd37ba85613.gif)
![image](https://cloud.githubusercontent.com/assets/383634/14808949/e89f3e3a-0b89-11e6-8dda-7f9c7635e301.png)

**Comment by bpasero** [comment]
Wow. Does it look better with your latest insider release? 
You can give it a try from our insiders release today: http://code.visualstudio.com/Download#insiders

**Comment by janpieterz** [comment]
Just tested it (same locations) and it doesn't occur there. Could it be that some kind of extension or setting is causing this, and is there an easy way for me to test this without removing all from my normal install? Sort of a chrome-incognito mode?

Another interesting facet: When the dev tools are opened, it doesn't happen.

**Comment by bpasero** [comment]
No, it is the large update coming with insiders from Chrome 45 => Chrome 49.
