### ISSUE TITLE
Extensions not loading

### ISSUE THREAD

**Issue by victorhugooo98** [Microsoft/vscode#57893]
- VSCode Version: 1.26.1
- OS Version: Windows 10 Home Single Language

What I expected:
- Extensions loaded successfully and ready to install

What I've got:
- No extensions found.

Steps to Reproduce (the same for insiders (v1.27.0) version):

1. Open Visual Studio Code
2. Toggle Developer Tools (Ctrl+Shift+P > Developer: Toggle Developer Tools)
3. Reload Window (Ctrl+Shift+P > Reload Window)
4. Click in the Extensions Tab (Ctrl+Shift+X)

With all steps reproduced, you should get something like this in the normal version:
![image](https://user-images.githubusercontent.com/33769126/45050367-79fbf980-b057-11e8-8752-cd72d01f791d.png)

and this in the insiders version:
![image](https://user-images.githubusercontent.com/33769126/45050396-913ae700-b057-11e8-8353-a044ad03c3ab.png)

**Comment by RevoluPowered** [comment]
Duplicate.

Workaround has been found, which may help.

https://github.com/Microsoft/vscode/issues/57851
