### ISSUE TITLE
Search results are truncated in the beginning

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#57895]
Issue Type: <b>Bug</b>

This is a regression, as it does not repro on 1.26.1.

Repro:

- Have a file with following content:
  ```js
  import * as fs from 'fs-extra'
  import * as path from 'path'
  ```
- Try a few searches, notice the results are truncated in the beginning of the lines

![image](https://user-images.githubusercontent.com/4033249/45051335-afddb580-b038-11e8-81c9-04c882a60c83.png)

![image](https://user-images.githubusercontent.com/4033249/45051354-b835f080-b038-11e8-83ed-c5ed47ae009d.png)

![image](https://user-images.githubusercontent.com/4033249/45051382-c7b53980-b038-11e8-957e-c0204c38f4b6.png)

VS Code version: Code - Insiders 1.27.0-insider (7b9afc4196bda60b0facdf62cfc02815509b23d6, 2018-09-03T09:07:33.052Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.89GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_14749200|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-emoji|bie|0.0.7
markdown-preview-github-styles|bie|0.1.3
vscode-eslint|dba|1.5.0
tslint|eg2|1.0.38
vsc-material-theme|Equ|2.4.2
prettier-vscode|esb|1.6.1
beautify|Hoo|1.4.2
theme-monokai-pro-vscode|mon|1.1.8
vscode-language-pack-ja|MS-|1.27.1
python|ms-|2018.7.1
debugger-for-chrome|msj|4.9.0
lsp-inspector|oct|0.0.1
vetur|oct|0.12.6
polacode|pnp|0.2.2
vscode-csstree|sme|0.7.0
language-stylus|sys|1.10.0
vim|vsc|0.16.2

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
The relevant extension API is here https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.proposed.d.ts#L113 I think that maybe we should actually get rid of `leadingChars` and just let the extension decide what to do with its allotment of `totalChars`. It would be much simpler. Also, we used to have code that would find a good place to trim the result line around a word boundary. We could bring that back.
