### ISSUE TITLE
Cannot install plugins from Marketplace

### ISSUE THREAD

**Issue by Ch3ck** [Microsoft/vscode#57898]
- VSCode Version:  1.26.1 (1.26.1)
- OS Version: Mac OS High Sierra

Steps to Reproduce:

1. Open extensions
2. Search for "Prettier" or "Simple React Snippets.

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by adammparker** [comment]
@Ch3ck Looks like the marketplace is down: https://marketplace.visualstudio.com/

**Comment by opalenet-leo** [comment]
```
Sorry! Our services aren't available right now.
We're working to restore all services as quickly as possible. Please check back soon.

Ref A: 476471B2C82C4C95A6BC715B9599BB09 Ref B: BL2EDGE0910 Ref C: 2018-09-04T20:30:37Z
```

[https://marketplace.visualstudio.com/](https://marketplace.visualstudio.com/) is down for hours T_T

**Comment by ramses132** [comment]
what a hell is going on bill what are u doing with ur money...

**Comment by mjbvz** [comment]
Duplicate of #57851
