### ISSUE TITLE
VSCode doesn't show anything when Marketplace is offline

### ISSUE THREAD

**Issue by davicoradini** [Microsoft/vscode#57901]
Issue Type: <b>Bug</b>

VS Marketplace is offline right now, when you try to find some extension it does not show anything.
I've tried reinstalling VSCode, removing all files from %user% folder, I've lost so many time before I saw that the marketplace is offline! It should have some error handling at least!

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz (8 x 2395)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (11.40GB free)|
|Process Argv|C:\Users\davic\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by mjbvz** [comment]
Marketplace issues are tracked by #57851

Keeping this issue open to track improving the user experience when the marketplace is down

**Comment by beastdestroyer** [comment]
@mjbvz How about a more useful error message that is returned if it detects it can't connect to the Marketplace like:

`Unfortunately, we cannot seem to connect to the Marketplace at this time, please check back later` and perhaps add a link to a Marketplace status monitor of some sorts, or integrate it right into the message itself?

**Comment by ramya-rao-a** [comment]
@beastdestroyer That is a good idea.

Updated to show `We cannot connect to the Extensions Marketplace at this time, please try again later.` when the request to connect to the Marketplace fails

Will show the existing `No extensions found.` when the request is successful, but no results were found indeed.

Additional info from the http request status text will show up in the console (Help -> Toggle Developer Tools -> Console) as before.
