### ISSUE TITLE
On problem mach there always is Add to include path bulb when pointing to problem line

### ISSUE THREAD

**Issue by alexxx537** [Microsoft/vscode#5790]
- VSCode Version: 1.0.0
- OS Version: windows 7

Steps to Reproduce:

1. Compile project with errors or warnings
2. Go to problem
3. When pointing on problem line there is yellow bulb that tells add to include path.

**Comment by bpasero** [comment]
@alexxx537 is this with the C# extension?

**Comment by alexxx537** [comment]
No, it is C/C++ extension.

**Comment by bpasero** [comment]
Please report this to the C/C++ extension repository, thanks!
