### ISSUE TITLE
Repetitive problem message when pointing to problem line

### ISSUE THREAD

**Issue by Aukstkalnis** [Microsoft/vscode#5792]
- VSCode Version: 1.0.0
- OS Version: windows 7

Steps to Reproduce:
1. In one header create warning message
2. Include this header into multiple files
3. Compile and go, to problem Mach in this header
4. Problem message shows a list repetitive messages

It is strange to see list of problem messages that are the same.

**Comment by bpasero** [comment]
@alexxx537 what language is this?

**Comment by alexxx537** [comment]
It is C language. I am using C/C++ extension.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/vscppsamples#41

**Comment by sridmad** [comment]
This is not related to the C++ extension as it does not support build not does it process the output. I think this has to do with VSCode processing warnings and errors from Tasks.

**Comment by sridmad** [comment]
@dbaeumer, @bpasero  please re-open the issue as this is related to VSCode handling of Task output.

**Comment by dbaeumer** [comment]
@Aukstkalnis how do you build the project ?

**Comment by Aukstkalnis** [comment]
See this issue:
https://github.com/Microsoft/vscppsamples/issues/41

**Comment by dbaeumer** [comment]
@Aukstkalnis Just to double check. The tasks.json must normally sit in a settings folder. This is the case in your setup.

**Comment by dbaeumer** [comment]
Sorry a .vscode folder.

**Comment by Aukstkalnis** [comment]
Yes, my task.json is in the .vscode folder which is generated in my project root directory.

**Comment by dbaeumer** [comment]
I can't reproduce this using our setup. Here is what I see using version 17.x of cl:
```
Microsoft (R) C/C++ Optimizing Compiler Version 17.00.60610.1 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.
Source.cpp
p:\mseng\vscode\playgrounds\bugs\consoleapplication1\warning.h(5) : error C2146: syntax error : missing '}' before identifier 'TestWarning_three'
p:\mseng\vscode\playgrounds\bugs\consoleapplication1\warning.h(6) : error C2059: syntax error : '}'
p:\mseng\vscode\playgrounds\bugs\consoleapplication1\warning.h(6) : error C2143: syntax error : missing ';' before '}'
```

Setting up the problem matcher for this pattern makes the errors show up correctly.

@Aukstkalnis how does the output of the nmake run look on your system.

**Comment by Aukstkalnis** [comment]
This is my project example from https://github.com/Microsoft/vscppsamples/issues/41:
[ConsoleApplication1.zip.txt](https://github.com/Microsoft/vscode/files/290783/ConsoleApplication1.zip.txt)

With this example I am able to reproduce this problem.

**Comment by dbaeumer** [comment]
@Aukstkalnis could you still provide me with the output of running build.bat. You seem to call a g++ compiler and the error format mostly depends on compiler and its version.

**Comment by Aukstkalnis** [comment]
I get this output:

c:\Users\aukstkalnis.de\Desktop\ConsoleApplication1>g++ -c hello.cpp 
In file included from hello.cpp:1:0:
warning.h:5:5: error: expected '}' before 'TestWarning_three'
     TestWarning_three
     ^
warning.h:6:1: error: expected initializer before '}' token
 };
 ^
warning.h:6:1: error: expected declaration before '}' token
c:\Users\aukstkalnis.de\Desktop\ConsoleApplication1>g++ -c main.cpp 
In file included from main.cpp:4:0:
warning.h:5:5: error: expected '}' before 'TestWarning_three'
     TestWarning_three
     ^
warning.h:6:1: error: expected initializer before '}' token
 };
 ^
warning.h:6:1: error: expected declaration before '}' token

**Comment by dbaeumer** [comment]
@Aukstkalnis thanks. Now I see. Need to think about how to best address this.

**Comment by dbaeumer** [comment]
@Aukstkalnis this got addressed a while ago by de-duping error message in the problem collector.
