### ISSUE TITLE
After updating and rebooting, vscode vanishes

### ISSUE THREAD

**Issue by husunwang** [Microsoft/vscode#57920]
i downloaded vscode on 2018/08/01, and upadated it yesterday without rebooting.
today, i open my laptop, and find vscode disappeared.
does vscode updating need some windows service?
(for preventing getting raped by wins os auto-updating, i close some of windows service.
maybe this cause the vanishing?)

**Comment by joaomoreno** [comment]
Sorry about that. You can set `"update.enableWindowsBackgroundUpdates": false` to prevent it from happening. You can also look for `vscode-*.log` log files in `TEMP`, they would point us to why it is happening.
