### ISSUE TITLE
Unable to install/search extensions in latest macOS Mojave beta

### ISSUE THREAD

**Issue by jasonmccallister** [Microsoft/vscode#57924]
- VSCode Version: 1.26.1
- OS Version: macOS Mojave 10.14 Beta (18A384a)

Steps to Reproduce:

1. Open VSCode
2. Search for extensions
3. See 503 error in developer console

Does this issue occur when all extensions are disabled?: Yes

<img width="649" alt="screen shot 2018-09-04 at 10 01 28 pm" src="https://user-images.githubusercontent.com/5354908/45066868-615b0600-b08e-11e8-921b-a27db3bd82a3.png">

**Comment by programkode** [comment]
Can confirm this happens on my Linux machine as well, so it's not platform specific.

https://marketplace.visualstudio.com/ - The whole Marketplace seems to be down

**Comment by jasonmccallister** [comment]
Easy bug fix then, well at least for the repo - I’m sure someone else is pretty busy right now...
