### ISSUE TITLE
python highlight error

### ISSUE THREAD

**Issue by baby5** [Microsoft/vscode#57930]
- VSCode Version: 1.26.1
- OS Version: win10 1803 17134.228

Steps to Reproduce:
![example](https://user-images.githubusercontent.com/12880800/45069904-6311e180-b101-11e8-8578-3166d6681f27.png)
1.related import "important_module" should not be highlight

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Please share the text of the code along with screenshots

**Comment by baby5** [comment]
@mjbvz `from .important_module import something`

**Comment by aeschli** [comment]
This issue was moved to MagicStack/MagicPython#160
