### ISSUE TITLE
Search in keybindings editor by pressing keyboard shortcut

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#57935]
I type keyboard shortcuts into the keybindings editor pretty often - like `cmd+shift+...` and that can be a lot of typing. And the dialog to add keybindings by pressing them is very nice

![image](https://user-images.githubusercontent.com/323878/45072614-9a947580-b090-11e8-8b8b-02560f2d6b8f.png)

So I was thinking, what if I can search for a keybinding by just pressing it? A button in the search bar or some keyboard shortcut can activate that dialog, then I press the shortcut, and it's pasted into the search bar.

**Comment by sandy081** [comment]
You can now record keys and search them by checking `Record Keys` action. You can come out of that mode by typing `escape` once if search box is empty otherwise twice (first to clear the input and next to off the recording). You can also enter into the recording mode using default keybinding `alt+k` (`cmd+alt+k` on Mac).

![kapture 2018-09-17 at 12 43 56](https://user-images.githubusercontent.com/10746682/45618945-cee83880-ba77-11e8-80f8-c56d258f2005.gif)

**Comment by roblourens** [comment]
This is awesome, thanks! But I wonder if it would be better to use the dialog that pops up for editing, instead of intercepting all keypresses in search. I can toggle this mode on with the keyboard shortcut, but then I'm trapped and I can't disable it, navigate to the results, or do anything else until I grab the mouse and untoggle that button.

**Comment by roblourens** [comment]
But I'm imagining that it would take the input and insert it into the search box. So it wouldn't be two places to search, more like a faster way to type input into the same search box. I think it's confusing that we now have two different experiences for capturing keyboard shortcuts when they basically are trying to do the same thing.

**Comment by sandy081** [comment]
@roblourens If the dialog just insert it into the search box then I do not understand the need of the dialog? You can do that directly in the search box by enabling the recording mode. Prompting a new input box from an input box is not a good user experience. 

Please try try the new feature which is already in the dev and see how it is. BTW one feedback I got from the team is to enable the recording mode by default which means with your suggestion we cannot do it.

@misolori FYI

**Comment by roblourens** [comment]
I did try it, and the experience feels weird. I think something that traps keyboard input should be a modal dialog, not just one part of the UI. I press one shortcut to enable it, and a different shortcut to disable it? 

I'm not sure about enabling it by default, it could be confusing. 

(But regardless, it's much better than having to type out `"cmd+shift+f10"` or whatever by hand!)

**Comment by sandy081** [comment]
Hmm.. Not convinced. I would prefer single UI element rather multiple. Let me wait for the feedback before doing the change.

**Comment by misolori** [comment]
I actually like that I'm able to enter into this "mode", though I wish I could run a keyboard shortcut to toggle that mode (I know you can tab to the toggle). 

I do think that once you're in this mode, we should update the placeholder text to indicate how to exit this mode:

![image](https://user-images.githubusercontent.com/35271042/45701017-f0eac500-bb22-11e8-96c0-fd8db86241d5.png)

**Comment by sandy081** [comment]
@misolori There is a shortcut to enter in to that mode. `alt+k` (`cmd+alt+k` on Mac). I liked to update the message.

**Comment by sandy081** [comment]
@roblourens Thanks for running in the stand up there. I will put this in UX channel to gather the feedback.

**Comment by alexr00** [comment]
Cool feature!
