### ISSUE TITLE
Saving an existing file "DELETES" metadata - ACLS/DATES/STREAMS etc

### ISSUE THREAD

**Issue by smallscript** [Microsoft/vscode#57936]
# Title: Saving an existing file "DELETES" metadata - ACLS/DATES/STREAMS etc

This behavior is NOT what `Notepad`, `Visual Studio` etc do. It actually stems from a Microsoft CRT bug in handling of `fopen` mode "+" (as in "w+").

I've reported and documented the precise CRT issue(s) via `Visual Studio` bug reporter. 

NOTE: `Visual Code` is affected by the CRT bug, `Visual Studio` works correctly.

Error in stdlib fopen mode __acrt_stdio_parse_mode_plus in corecrt_internal_stdio.h line 471 (deletes all metadata ACL and streams). Because "+" is ignored, and thus `dwCreationDisposition` always uses `CREATE_ALWAYS` instead of `OPEN_ALWAYS` (which is what "+" _update_ should use) by the time it gets to [CreateFile](https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-createfilew).

https://developercommunity.visualstudio.com/content/problem/328164/error-in-stdlib-fopen-mode-acrt-stdio-parse-mode-p.html

If one issues a fopen(path, mode) where mode = "wb+" the flow of code gets to __acrt_stdio_parse_mode_plus in corecrt_internal_stdio.h:471.

Where it then leaves >`result._lowio_mode = _O_WRONLY | _O_CREAT | _O_TRUNC;` intact > ignoring result._stdio_mode |= _IOUPDATE; 

which then flows into decode_open_create_flags in open.cpp:335 where: >`case _O_CREAT: return OPEN_ALWAYS;` should be invoked but isn't. Instead it becomes: >`_O_CREAT | _O_TRUNC: return CREATE_ALWAYS;` 

The final result of which is that "wb" and "wb+" act the same. When "wb+" should use OPEN_ALWAYS not CREATE_ALWAYS. The final effect of which is that ALL attributes, streams, ACL/SACL is lost on the file. It is a **terrible** lossy bug.

The _O_TRUNC should be REMOVED by __acrt_stdio_parse_mode_plus OR result._stdio_mode should` be passed to lower layers. As it is written, the "+" is simply ignored/discarded.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by smallscript** [comment]
I will be glad to try and test it again with tomorrow's nightly build. But it has a 100% easy repro. 

1. Create a markdown file. 
2. Add a NTFS stream manually (or simply add a "comment" to the file using Desktop File Explorer which uses the NT Storage Api to record the comments). 
3. Do a `dir /R` to see _streams_. 
4. Edit the file in `Visual Code`. 
5. Do a `dir /R` to see _streams_. _(now it is gone)

You can actually do any number of things, _streams_ are just an example. It actually _deletes_ the file, then writes it. So all metadata (times, acls, streams, etc) are lost.

**Comment by bpasero** [comment]
Please do.
