### ISSUE TITLE
Setting window.title to blank should remove the title bar text

### ISSUE THREAD

**Issue by misolori** [Microsoft/vscode#57933]
If you set `window.title` to blank, the title bar still shows text:

<img width="50%" src="https://user-images.githubusercontent.com/35271042/45071615-117b3f80-b08c-11e8-8227-c439560a5256.png">

This is not expected as I want to explicitly remove any text from the title bar. This forces me to use a hacky workaround by copying a unicode space instead (not desirable). This should work as expected.

**Comment by bpasero** [comment]
@misolori usecase?

**Comment by misolori** [comment]
@bpasero I just want to have a minimal look:

![image](https://user-images.githubusercontent.com/35271042/45072319-4ccb3d80-b08f-11e8-9bdf-e4b71dc4edd8.png)

**Comment by bpasero** [comment]
@misolori ah you talk about the `window.title` setting and not the DOM property. This is actually independent from the custom title and also applies to the native title.

I think it is not a good idea to not have any title for an application because the title is used to distinguish the application from others (e.g. when you switch applications).

**Comment by oneslash** [comment]
Offtopic, @misolori what is the color theme you are using in the second screenshot?

**Comment by misolori** [comment]
@oneslash it's one of my themes [I've been working on](https://twitter.com/miguelsolorio_/status/1025131670154895360) (haven't published it yet).

**Comment by sbatten** [comment]
@misolori I can see the appeal of no title and there are other ways to differentiate windows imo

**Comment by bpasero** [comment]
@sbatten actually I take it back, since the window has a custom title, its contents will likely not show up in the native OS switcher anyways, so in that case of custom title I think its fine to allow for an empty title.
