### ISSUE TITLE
Clicking on check for update opens empty chrom tab

### ISSUE THREAD

**Issue by sameer-coditas** [Microsoft/vscode#57938]
- VSCode Version: 1.26.1
- OS Version:  Linux 16.04 LTS

Steps to Reproduce:

1. Click on Settings bottom-left corner of VScode.
2. Click on Check for update (if not updated).
3. Will open a empty browser window.

Does this issue occur when all extensions are disabled?: Yes
[vscode-issue.zip](https://github.com/Microsoft/vscode/files/2351528/vscode-issue.zip)

**Comment by sameer-coditas** [comment]
This is not the case only with update, any this that require browser action opens empty browser window without redirection. steps i gave you was just another example.
For an instance if I got to Help > Introductory Videos; it does the same thing i.e. opens empty browser window and no redirection.

**Comment by joaomoreno** [comment]
https://github.com/electron/electron/issues/6531
