### ISSUE TITLE
VS code doesn't recognize GCC built-in __int128 type

### ISSUE THREAD

**Issue by z16166** [Microsoft/vscode#57941]
Issue Type: <b>Bug</b>

VS code doesn't recognize GCC built-in __int128 type.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:34:20.517Z)
OS version: Linux x64 4.13.0-36-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (2 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|7.77GB (0.14GB free)|
|Process Argv|/usr/share/code/code|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
cmake-tools-helper|mad|0.2.1
python|ms-|2018.7.1
cpptools|ms-|0.18.1
cmake|twx|0.0.17
cmake-tools|vec|1.1.1

</details>

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-cpptools
