### ISSUE TITLE
Allow to disable step commands

### ISSUE THREAD

**Issue by rherrmann** [Microsoft/vscode#57947]
I implement a very simple debug adapter that can start, suspend and continue execution of the debuggee. As soon as the debug adapter sends a `stopped` notification to the client, the actions to _Step Over_, _Step Into_ and _Step Out_ are enabled. However my debug adapter implementation cannot handle these requests.

I would like to propose to extend the protocol to ask the debug adapter if it can handle step requests. Or is there a workaround/best practice to disable these actions?

**Comment by weinand** [comment]
We are not planning to add support for this to the DAP because debuggers not supporting those stepping actions is very typical.
I suggest that you just implement the corresponding DAP requests as no-ops.

If there are more developers requesting this feature, we will reconsider this...

**Comment by weinand** [comment]
Please see #45116 for a related feature request.
