### ISSUE TITLE
make easy to get particular  file using < > keys

### ISSUE THREAD

**Issue by Chandramouli1997** [Microsoft/vscode#57944]
Issue Type: <b>Feature Request</b>

please upgrade feature like sublime text editor that is < > keys to help geting particular file when  many files  open in sublime text
in visual studio code i use ctrl+tab button to get particular  file 

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

**Comment by bpasero** [comment]
@Chandramouli1997 what exactly do you expect to happen when you press < or >?

**Comment by Chandramouli1997** [comment]
![screenshot 18 _li](https://user-images.githubusercontent.com/37043858/45251703-58a55100-b368-11e8-9a7f-13238ae7461f.jpg)
this feature is recommended for visual studio code
![screenshot 20](https://user-images.githubusercontent.com/37043858/45251705-74105c00-b368-11e8-890b-3f38d413884b.png)
