### ISSUE TITLE
Protocol: "inspector" inside launch.json is ignored

### ISSUE THREAD

**Issue by Kamilius** [Microsoft/vscode#57943]
Issue Type: <b>Bug</b>

**Steps**:
1. Create following configuration for mocha/typescript unit tests:
```json
{
  "type": "node",
  "request": "launch",
  "protocol": "inspector",
  "name": "Mocha Current File",
  "program": "${workspaceFolder}/packages/common/node_modules/mocha/bin/_mocha",
  "args": [
    "-r",
    "ts-node/register",
    "--timeout",
    "999999",
    "--colors",
    "${file}"
  ],
  "console": "integratedTerminal",
  "internalConsoleOptions": "neverOpen"
}
```
2. Run test against selected typescript spec file

**Actual**:
- Getting modal with following error:
`Cannot connect to runtime via 'legacy' protocol; try to use 'inspector' protocol.`
- Getting deprecation warning `(node:26438) [DEP0062] DeprecationWarning: 'node --debug' and 'node --debug-brk' are invalid. Please use 'node --inspect' or 'node --inspect-brk' instead.` inside of a terminal, as if `protocol: legacy` was set in `launch.json` configuration.

Same configuration works perfectly well on latest stable version of VSCode (just finished running both side by side).

**Expected**:
- Debugger launches, attaches to mocha test run and triggers breakpoints, same as for VSCode's latest stable version (Version 1.26.1 (1.26.1)).

VS Code version: Code - Insiders 1.27.0-insider (7b9afc4196bda60b0facdf62cfc02815509b23d6, 2018-09-03T09:07:33.052Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 3|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (60)</summary>

Extension|Author (truncated)|Version
---|---|---
json-to-ts|Mar|1.5.5
vscode-html-scss|P-d|0.0.42
indenticator|Sir|0.6.0
html-css-class-completion|Zig|1.17.1
vscode-file-peek|abi|1.0.1
html-snippets|abu|0.2.1
vscode-ngrx-snippets|ahs|0.0.4
ng-template|Ang|0.1.10
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-svgviewer|css|1.4.4
vscode-eslint|dba|1.5.0
vscode-protractor-snippets|dee|1.0.5
githistory|don|0.4.2
xml|Dot|2.3.2
vscode-babel-coloring|dza|0.0.4
gitlens|eam|8.5.6
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.38
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.6.1
git-project-manager|fel|1.6.1
vscode-yarn|gam|1.6.0
todo-tree|Gru|0.0.82
beautify|Hoo|1.4.2
docthis|joe|0.7.1
angular-essentials|joh|0.4.0
Angular2|joh|6.1.5
vscode-colorize|kam|0.7.1
es6-angular-snips|kas|0.0.3
MagicPython|mag|1.0.12
code-coverage|mar|0.0.2
HTMLHint|mka|0.5.0
prettify-json|moh|0.0.3
vscode-scss|mrm|0.6.2
python|ms-|2018.7.1
debugger-for-chrome|msj|4.9.1
angular2-inline|nat|0.0.17
material-icon-theme|PKi|3.5.3
polymer-ide|pol|0.6.0
seti-icons|qin|0.1.3
vscode-sort-json|ric|1.13.0
vscode-icons|rob|7.25.0
sass-indented|rob|1.4.9
vscode-coverage-gutters|rya|2.1.1
salesforcedx-vscode|sal|43.14.0
salesforcedx-vscode-apex|sal|43.14.0
salesforcedx-vscode-apex-debugger|sal|43.14.0
salesforcedx-vscode-apex-replay-debugger|sal|43.14.0
salesforcedx-vscode-core|sal|43.14.0
salesforcedx-vscode-lightning|sal|43.14.0
salesforcedx-vscode-visualforce|sal|43.14.0
code-settings-sync|Sha|3.1.2
stylelint|shi|0.42.0
simontest|Sim|0.18.4
python|tht|0.2.3
vsfire|tob|1.3.2
vscode-todo-highlight|way|1.0.4
JasmineSnippets|xab|1.0.1
JavaScriptSnippets|xab|1.7.0

(3 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Can you try starting with `--disable-extensions` and running it again?

It looks like you don't have the Live Share extension installed but this seems like the kind of bug it could cause.

**Comment by Kamilius** [comment]
@roblourens running VSCode with `--disable-extensions` ?

**Comment by roblourens** [comment]
Right

**Comment by Kamilius** [comment]
@roblourens did it, having same issues

**Comment by roblourens** [comment]
I'm stumped, @weinand?

We release 1.27 today, I assume it's the same if you update?

**Comment by Kamilius** [comment]
My version of insider is `Version 1.27.0-insider (1.27.0-insider)`
![screen shot 2018-09-06 at 8 47 58 am](https://user-images.githubusercontent.com/3115794/45137505-9f047f80-b1b1-11e8-8d12-593a70a51a5c.png)

**Comment by weinand** [comment]
Since you didn't provide information about your setup, I came up with this project: 
[bug57943.zip](https://github.com/Microsoft/vscode/files/2356364/bug57943.zip)

This works for me just fine in VS Code 1.27.

My steps:
- unpack the zip
- `cd bug57943`
- `npm install``
- `code .`
- open test/hello.ts
- set breakpoint in line 6
- F5

Breakpoint is hit.

**Comment by Kamilius** [comment]
@weinand ok, but shouldn't it be `$ code-insiders .` instead of a `$ code .`? Because everything works perfectly fine on stable version of a `VSCode` as well.

**Comment by weinand** [comment]
Insiders has become Stable yesterday, but because of a serious issue we had to stop the release.
Since I do not know whether you have upgraded already, you have to decide yourself what version to use. I suggest to try it in both.

**Comment by Kamilius** [comment]
Node.js version: v8.9.3
Output of integrated terminal is as follows:
![screen shot 2018-09-06 at 12 36 56 pm](https://user-images.githubusercontent.com/3115794/45149180-9f147780-b1d1-11e8-9907-346623d68f5d.png)

**Comment by weinand** [comment]
@Kamilius from the screenshot I noticed that you are trying to run the launch.json instead of a typescript file. This doesn't make a lot of sense. Please make sure that your active editor contains a typescript file because that's what your launch.json id refering to with the `"${file}"` argument.

**Comment by Kamilius** [comment]
Yeah that's my bad in terms of this exact example. But running against a proper file still brings same issue as you may see on a fresh screenshot below:
![screen shot 2018-09-06 at 12 42 29 pm](https://user-images.githubusercontent.com/3115794/45149535-793ba280-b1d2-11e8-8065-4d30e0b2c3d0.png)

**Comment by weinand** [comment]
Please try with my project.
Since I don't have your setup I cannot speculate about it.

**Comment by Kamilius** [comment]
Fails on your example:
![screen shot 2018-09-06 at 1 13 35 pm](https://user-images.githubusercontent.com/3115794/45151413-e8b39100-b1d6-11e8-9979-7fff4b36c9f1.png)


![screen shot 2018-09-06 at 1 11 28 pm](https://user-images.githubusercontent.com/3115794/45151246-717dfd00-b1d6-11e8-971c-e57f4889a39f.png)

**Comment by weinand** [comment]
- Open a terminal outside of VS Code
- run `which node`
- run `node --version`

What's the output of both commands?

**Comment by Kamilius** [comment]
@weinand 

> Is seems something in your VS Code setup is broken.

I've found that `Node Debug` was `disabled` and only `Node Debug (legacy)` was `enabled`. 
Enabling `Node Debug` solved my issue.
On the other hand it is strange, that it was disabled, as I've never touched `@builtin` extensions...

Nevertheless - thanks for helping me in solving this setup issue

**Comment by weinand** [comment]
@Kamilius thanks for helping us getting this resolved.

@sandy081 are you aware of any issues why a built-in extension could be disabled accidentally?
In addition, it should not be possible that "Node Debug (legacy)" is enabled if "Node Debug" is not (because Node Debug (legacy)" depends on "Node Debug").

**Comment by sandy081** [comment]
It can happen if a user tries to disable an extension that has a dependency to built in extension and selects to disable all. 

From 1.27 I have changed this behaviour to not to ask to disable dependency extensions. Only the extension which is requested to disable will be disabled
