### ISSUE TITLE
debug - paused at invisible breakpoints

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#5795]
Unsure how I ended up there but the debugger paused at breakpoints I have had removed a while ago. That was when debugging an extension I created with `yo code`.
![screen shot 2016-04-26 at 10 54 22](https://cloud.githubusercontent.com/assets/1794099/14812426/7fbad8ca-0b9d-11e6-947d-1dbb9d422294.png)
![screen shot 2016-04-26 at 10 54 56](https://cloud.githubusercontent.com/assets/1794099/14812428/80b6ccac-0b9d-11e6-96ed-e9cf82167667.png)

**Comment by isidorn** [comment]
Please re-try this with latest alpha, there were issues with extensions debugging

**Comment by jrieken** [comment]
nope
