### ISSUE TITLE
Debug does not work for file in symlinked folder

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#57954]
- VSCode Version: 1.28 (master)
- OS Version: Linux Ubuntu 18

Steps to Reproduce:

1. create a symbolic link to a folder (`ln -s source target`)
2. open the folder (running out of master where our `realpath` logic is removed and you can open the link)
3. add a app.js node.js file with just one console.log statement
4. add a breakpoint
5. create a launch config:

```json
{
    "type": "node",
    "request": "launch",
    "name": "Launch Program",
    "program": "${workspaceFolder}/app.js",
    "runtimeArgs": [
        "--preserve-symlinks"
    ]
}
```

6. Debug

=> :bug: breakpoint is not hit

Works fine when opening the folder with its real path.

**Comment by roblourens** [comment]
`--preserve-symlinks` is simply not working here...

**Comment by roblourens** [comment]
I see the same behavior with chrome devtools, this just isn't working the way I expect. Node always resolves the symlink for `process.cwd()` and the main script is resolved relative to that.

![image](https://user-images.githubusercontent.com/323878/45107811-a2cfcd80-b0ef-11e8-8608-3c735194fcea.png)

Maybe we can work around it for the debugger by always resolving the main script to an absolute path, if it's in a symlinked folder, and if the user has set `--preserve-symlinks` in their config?

**Comment by bpasero** [comment]
If it helps, `fs.realpath` can be used to resolve a symlink to its actual path. That is what we used to do when opening any folder.

**Comment by roblourens** [comment]
Yeah I guess we could also always resolve paths to their real path, and advise users not to use `--preserve-symlinks`, but that could be a breaking change. And users might have other reasons for using it - I think it actually affects where require() looks for files. Or they want to see the right paths in stack traces.

I said that resolving the script to an absolute path would work around it but that's actually not true. The main script is still excluded from `--preserve-symlinks`. If you use node 10 then you can also pass `--preserve-symlinks-main` which does what you'd expect for the main script.

So if you use both of those flags, _and_ we pass the script as an absolute path, then it does work.

**Comment by bpasero** [comment]
I think its fine to support `--preserve-symlinks` again if possible. You guys should probably update your docs because you still say that as a workaround.

**Comment by roblourens** [comment]
It should still work in the case of having a symlinked folder inside your workspace, but not this scenario.

**Comment by bpasero** [comment]
Ah ok got it.

**Comment by ivan-section-io** [comment]
I guess, damned if you do, damned if you don't.
VSCode resolving links had previously broken my golang editing+debugging experience, by resolving outside of the nicely constructed GOPATH those symlinks had placed everything into.

The question is: is VSCode the tool that just breaks the paths for everything (and hopes other tools will still work), or the tool that will have to cater specifically for the other "path breaking" tools?

I hope the later. But it sound like some things may have come to rely upon it... https://xkcd.com/1172/

**Comment by roblourens** [comment]
Do we know how common this scenario is for node developers? My gut says not that common. I still don't have a < node 10 solution.

**Comment by weinand** [comment]
one common scenario is "npm link": using an npm module under development in node.js project (e.g. the vscode-debugadapter).

**Comment by roblourens** [comment]
Debugging with a linked npm module still works. What doesn't work is when the main script itself is inside a symlinked path.

**Comment by roblourens** [comment]
The best fix I have is to detect when the cwd is in a symlinked path, and if so, always use an absolute path instead of resolving it to a relative path. This is needed because `--preserve-symlinks-main` applies to whatever is passed in as the main script, but if a relative path is given and must be resolved with the cwd, the cwd is always resolved to its real path.

I'll update the docs to tell users when to use `--preserve-symlinks-main`

**Comment by bpasero** [comment]
@roblourens so what is the full fix for this? I need:
* node.js 10
* have the following launch config

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}/index.js",
            "runtimeArgs": [
                "--preserve-symlinks",
                "--preserve-symlinks-main"
            ]
        }
    ]
}
```

?

**Comment by roblourens** [comment]
Correct
