### ISSUE TITLE
Negated lookahead pattern in search gives regex parsing error

### ISSUE THREAD

**Issue by tHBp** [Microsoft/vscode#57953]
- VSCode Version: 1.26.1
- OS Version: Windows 10

Steps to Reproduce:

1. Search for any negated look-ahead pattern.
    For example, taken from [MDN RegExp docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions) /\d+(?!\.)/ matches a number only if it is not followed by a decimal point.
2. The search returns error with following message:
"Error parsing regex near '\d+(?!\.)' at character offset 5: Unrecognized flag: '!'. (Allowed flags: i, m, s, u, U, x.)"

Does this issue occur when all extensions are disabled?: Yes

Happens for any type of negated lookahead search. 
Let me know if additional information is required to triage the issue.

**Comment by roblourens** [comment]
That isn't supported. vscode uses ripgrep to power search which doesn't support some advanced regex features. https://code.visualstudio.com/docs/editor/codebasics#_advanced-search-options

**Comment by tHBp** [comment]
Ahh, I see. Thanks for the quick turnaround anyway.
