### ISSUE TITLE
Software thinks changes have been made when there are none

### ISSUE THREAD

**Issue by JustAnotherG** [Microsoft/vscode#57967]
Issue Type: <b>Bug</b>

All I did was update to the latest version and now when files are re-opened in the editor they are being immediately flagged as "having changed". There are no changes being made.

In other words, I'm not loading the files myself using any menus. The Code software is loading previously loaded files. Please look into this bug. Thanks.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17738

**Comment by mjbvz** [comment]
Does this still happen if you disable all of your extensions and restart VS Code?

**Comment by JustAnotherG** [comment]
I have never installed any extensions, myself, for this software. I did try to reproduce the error and it's not happening again. Maybe it's only a transient bug after the update goes in. I'll update this if I see it again.

**Comment by JustAnotherG** [comment]
Okay, I have more info. This is still happening. I'm bouncing between 2 systems and that's why I couldn't reproduce the issue earlier. There is actual some Application Error showing in the eventvwr.exe and it appears Windows Error Reporting has already phone home with the information.

**Comment by joaomoreno** [comment]
Can you show me a screenshot of what you mean by "having changed"?

**Comment by JustAnotherG** [comment]
By changed, I mean, when exiting the Code editor you are asked if you want
to save your changes. And there is a solid circle next to the file name.
Let me apologize and state that I may have misunderstood the exact
circumstances under which I reported this bug. It may be my fault for not
understanding how the software works. So, let me try to reproduce this
situation once again (although if it's a transient bug that occurs after
installation that won't be possible).

This isn't a groundbreaking issue but if I can reproduce the error I'll
send a screenshot.

**Comment by JustAnotherG** [comment]
I'm guessing that a dirty file is defined as a file that Visual Studio Code saves for the user upon a hasty exit or at certain time intervals in case of power loss but it not explicitly saved by the user him or herself?
I'm seeing the "circle" again when launching Visual Studio Code. If I've exited the editor and relaunched it, how can the file NOT have already been saved. So, I came up with the theory above. Can you define it and may I recommend defining this in the help for Visual Studio Code if it is not already? Thanks.

**Comment by bpasero** [comment]
You can disable that behaviour: `files.hotExit: off`
