### ISSUE TITLE
Indentation problems when moving and pasting code

### ISSUE THREAD

**Issue by Instagit** [microsoft/vscode#57964]
```
Version: 1.26.1
Commit: 493869ee8e8a846b0855873886fc79d480d342de
Date: 2018-08-16T18:34:20.517Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
OS Version: Ubuntu 16.04
```

Steps to Reproduce:

1. Move a line of code with the keyboard shortcut ALT + arrow keys up/down
2. All switch statements along the way have their indentation broken

Does this issue occur when all extensions are disabled?: Yes

Example. Start off with this code. Move line 3 to the bottom.

````php
<?php

echo "Why is this bug still there?";

switch ($variable) {
    case 'value':
        # code...
        break;
    
    default:
        # code...
        break;
}

?>
````

Afterwards it looks like this:

````php
<?php


switch ($variable) {
    case 'value':
    # code...
    break;
    
    default:
    # code...
    break;
}
echo "Why is this bug still there?";

?>
````

There are many different indentation styles for switch structures, but as far as I know, having case and statement on the same indentation level isn't very popular.

What I expected: VS Code should get the indentation right or if it can't, leave it the way it is.

**Comment by Instagit** [comment]
This seems to be a general problem after all. It also happens in many cases where no switch statement is involved.

**Comment by roblourens** [comment]
Do you have `editor.formatOnPaste` set?

**Comment by Instagit** [comment]
> Do you have `editor.formatOnPaste` set?

Yes.

**Comment by roblourens** [comment]
It looks like formatOnPaste disables autoIndent when pasting. But we don't ship a PHP formatter out of the box, so this just doesn't work for PHP unless you disable formatOnPaste.

Is that right @rebornix? Maybe autoIndent should still apply, if there is no formatter installed?

**Comment by Instagit** [comment]
Disabling ````formatOnPaste```` helps, but is there a way to also disable the autoIndent when moving code line by line with ALT+up/down?

I think if there's no formatter, autoIndent should be disabled for that file. That's better than potentially messing up all indentation.

Alternatively, maybe there could be a set of safe cross-language indentation defaults. The cases we posted here are fairly common in most languages and shouldn't cause problems, even without a specific formatter.
