### ISSUE TITLE
Open file/folder dialog needs to know its target window

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#5796]
#5338
- start with `yo code`
- change the command to be like shown below
- set a break point on the `executeCommand`
- run, breakpoint hit, chose a folder
- ⚡ instead of the debuggee window the dev window opens a new folder

```
  // Display a message box to the user
  vscode.commands.executeCommand('vscode.openFolder');
```

**Comment by bpasero** [comment]
Corner case because you manage to change window focus between the invocation of the command and the actual result. Fix is to make sure that calls to the native file/folder picker know the target window.
