### ISSUE TITLE
Task of type "shell" is not executed when shellArgs are set

### ISSUE THREAD

**Issue by jeffrson** [Microsoft/vscode#57963]
The following examples are not really useful, but (hopefully) demonstrate the bug.

Let's say I have this in user settings:
```
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
    "terminal.integrated.shellArgs.windows": ["/K", "calc"],

```
This works - it opens calculator when starting the terminal. Then I have this task:
```
        {
            "command": "notepad",
            "label": "TEST",
            "type": "shell",
            "problemMatcher": []
        },
```

It opens the calculator as well, but not notepad. However, when `terminal.integrated.shellArgs.windows` is not set, notepad is started correctly as soon as I launch the task. I would expect that both (calc/notepad) will run from the task.

The behaviour is the same when using PowerShell.

**Comment by Tyriar** [comment]
This is acting as expected, basically you shouldn't be configuring the integrated terminal to launch something like calc every time it launches. You should be able to configure a task to launch both if that's desired.

**Comment by jeffrson** [comment]
@Tyriar 
Unfortunately it's not that simple. calc and notepad were only used to demonstrate the behaviour.

In my use case, it's not actually something like calc that's executed, but a configuration script which changes some parameters of the shell inside the integrated terminal. Which works fine.

However, when I run a task, it configures the shell (according to my script or the PowerShell cmdlet, respectively) and then presents the shell prompt instead of running the task.

Maybe it would help to have different settings for the shell when run for the terminal and when run for a task?

**Comment by dbaeumer** [comment]
You can define the shell used and it args when executing a task. Something like:

```
			"options": {
				"shell": {
					"executable": "...",
					"args": [
						"..."
					]
				}
			}
```

**Comment by dbaeumer** [comment]
This is only possible per tasks not globally. But there are requests to define this gloablly.

**Comment by jeffrson** [comment]
Yes, a global solution would be great - we have a larger number of tasks...
