### ISSUE TITLE
Azure Functions extension doesn't create function.json and debugging doesn't work

### ISSUE THREAD

**Issue by emrekenci** [Microsoft/vscode#57960]
Issue Type: <b>Bug</b>

On windows 10, install latest versions of jdk, maven, vscode, vs code azure functions extension.

Click create new project in the functions extension, choose an empty folder, choose java.

In the resulting project structure, there has to be a function.json file that is required for azure functions but it's not created.

Then click debug, it fails. ""C:\works\event-hubs-to-cosmos-function\target\azure-functions\event-hubs-to-cosmos\" doesn't exist."

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (5.27GB free)|
|Process Argv|C:\Users\emkenci\AppData\Local\Programs\Microsoft VS Code\Code.exe C:\works\event-hubs-to-cosmos-function|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.5.0
solidity|Jua|0.0.46
vscode-attrs-sorter|mrm|2.1.0
vscode-azurefunctions|ms-|0.10.0
python|ms-|2018.7.1
azure-account|ms-|0.4.3
csharp|ms-|1.15.2
PowerShell|ms-|1.8.4
vscode-docker|Pet|0.1.0
java|red|0.30.0
vscode-java-debug|vsc|0.12.1
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.8.0
vscode-maven|vsc|0.10.0

</details>

**Comment by mjbvz** [comment]
Please file this issue against the azure function extension
