### ISSUE TITLE
Feature request to support querying for running extensions in extensions search

### ISSUE THREAD

**Issue by ashrafhadden** [microsoft/vscode#57969]
## Similar Issues
> Create groups to organize installed extensions #35891 
> Extension search filters should compose #55697 
> Create Categories/Groups for extensions #20599 #35891
> Group highlighting / bulk actions for extensions #47053

All of these issues are attempting to address the broader issue of **installed extension organization**. When you only have a few extensions it isn't a big deal. But for most of us extension junkies, finding one or a group of installed extensions among a single long and convoluted list is a headache, especially with all of the themes mixed in.

Solving any of one these smaller github issues would be a giant leap towards the overall goal of installed extension organization.

## Feature Requests / Solutions
_By order of impact on organizability..._
1. Make`@category` combinable/composable with `@installed`, `@enabled`, etc. #55697 
2. Add `@sort:category`, `@sort:unused`
3. Add installed extensions custom groupings #20599 #35891
4. Add Enable/`Disable Selected Extensions` (would require ability to `⌘`, `⇧`, `⌘ a` select groups of extensions), or perhaps even easier would be Enable/`Disable Filtered Extensions` #47053

### Example Use-Cases
- **Troubleshooting Extension cross-collision/interference problems**
You could narrow down the issue by disabling entire groups of extensions by category instead of having to `Disable All Installed Extensions`
- **Uninstalling unused/unnecessary extensions** w/ `@sort:unused` for example, improving overall performance

**Comment by ShivanshuKantPrasad** [comment]
Something similar to emacs mode would be awesome.
Modes define what plugins they enable and then certain modes are enabled during when certain languages are active. 
There are many plugins which are awesome for a certain language but unnecessarily clutters the interface while doing nothing for other languages. It would be nice to have some easy way to manage plugins based on active languages.

**Comment by ramya-rao-a** [comment]
@ashrafhadden #47053 tracks the feature request for carrying out actions on multiple extensions using multi select. That should take care of your 4th point, so I've updated the issue description with the link to #47053

With that the only remaining item in this issue that does not have an issue tracking it already is the ability to have a view that shows only the extensions that are currently activated which is definitely do-able.

Therefore, I'll update the title of this issue to reflect just that for easy tracking

@ShivanshuKantPrasad Thanks for that insight. That definitely sheds more light on why we need this feature.

**Comment by ramya-rao-a** [comment]
We have the `Developer: Show Running Extensions` command that 
- shows all the running extensions
- their startup time
- Link to report issue
- Option to profile the extensions.

Therefore, we don't really need another "view" i.e an option in the menu shown below for running extensions

<img width="575" alt="screen shot 2018-09-20 at 10 47 47 am" src="https://user-images.githubusercontent.com/16890566/45836802-a43df000-bcc2-11e8-8689-36ae43a1c220.png">

What is still helpful is a way to filter the extension query in the search box to include only running extensions.

Will update the title of this issue accordingly (again)

**Comment by sandy081** [comment]
Closing this in favour of existing `Developer: Show Running Extensions` view.
