### ISSUE TITLE
 ioctl(2) failed.

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#57976]
Issue Id: <b>2600fd81-4885-05ff-0629-b8f73d22962f</b><br /><br />*Versions* <br />- 207ace21dfec3dccab52f1296a3880ac7644c978<br />-  493869ee8e8a846b0855873886fc79d480d342de<br />-  4e9361845dc28659923a300945f84731393e210d<br />-  c827480be25bd63065e7ee2e106c24a707c08004<br />-  bda8a4de93278004d6d7c3628b92664f93f7e811<br />*Stack* <br />Error: ioctl(2) failed.<br />    at UnixTerminal.resize (/node_modules.asar/node-pty/lib/unixTerminal.js:227:13)<br />[/vs/workbench/parts/terminal/node/terminalProcess.ts#123:19 (resize)](https://github.com/microsoft/vscode/blob/207ace21dfec3dccab52f1296a3880ac7644c978/src/vs/workbench/parts/terminal/node/terminalProcess.ts#L123:19 (resize))<br />[/vs/workbench/parts/terminal/electron-browser/terminalProcessManager.ts#158:17 (setDimensions)](https://github.com/microsoft/vscode/blob/207ace21dfec3dccab52f1296a3880ac7644c978/src/vs/workbench/parts/terminal/electron-browser/terminalProcessManager.ts#L158:17 (setDimensions))<br />[/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#999:72 (onComplete)](https://github.com/microsoft/vscode/blob/207ace21dfec3dccab52f1296a3880ac7644c978/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L999:72 (onComplete))<br />[/vs/base/common/winjs.base.js#1191:0 (_notify)](https://github.com/microsoft/vscode/blob/207ace21dfec3dccab52f1296a3880ac7644c978/src/vs/base/common/winjs.base.js#L1191:0 (_notify))<br />[/vs/base/common/winjs.base.js#867:0 (enter)](https://github.com/microsoft/vscode/blob/207ace21dfec3dccab52f1296a3880ac7644c978/src/vs/base/common/winjs.base.js#L867:0 (enter))<br />[/vs/base/common/winjs.base.js#1089:0 (_run)](https://github.com/microsoft/vscode/blob/207ace21dfec3dccab52f1296a3880ac7644c978/src/vs/base/common/winjs.base.js#L1089:0 (_run))<br />[/vs/base/common/winjs.base.js#1057:0 (c)](https://github.com/microsoft/vscode/blob/207ace21dfec3dccab52f1296a3880ac7644c978/src/vs/base/common/winjs.base.js#L1057:0 (c))<br />[/vs/workbench/parts/terminal/electron-browser/terminalProcessManager.ts#63:4 (call)](https://github.com/microsoft/vscode/blob/207ace21dfec3dccab52f1296a3880ac7644c978/src/vs/workbench/parts/terminal/electron-browser/terminalProcessManager.ts#L63:4 (call))<br />[/vs/base/common/event.ts#140:15 (fire)](https://github.com/microsoft/vscode/blob/207ace21dfec3dccab52f1296a3880ac7644c978/src/vs/base/common/event.ts#L140:15 (fire))<br />[/vs/workbench/parts/terminal/electron-browser/terminalProcessManager.ts#132:24 (call)](https://github.com/microsoft/vscode/blob/207ace21dfec3dccab52f1296a3880ac7644c978/src/vs/workbench/parts/terminal/electron-browser/terminalProcessManager.ts#L132:24 (call))<br />[/vs/base/common/event.ts#140:15 (fire)](https://github.com/microsoft/vscode/blob/207ace21dfec3dccab52f1296a3880ac7644c978/src/vs/base/common/event.ts#L140:15 (fire))<br />[/vs/workbench/parts/terminal/node/terminalProcess.ts#104:25 (_sendProcessId)](https://github.com/microsoft/vscode/blob/207ace21dfec3dccab52f1296a3880ac7644c978/src/vs/workbench/parts/terminal/node/terminalProcess.ts#L104:25 (_sendProcessId))<br />[/vs/workbench/parts/terminal/node/terminalProcess.ts#69:8](https://github.com/microsoft/vscode/blob/207ace21dfec3dccab52f1296a3880ac7644c978/src/vs/workbench/parts/terminal/node/terminalProcess.ts#L69:8)<br />

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/Microsoft/node-pty/issues/220
