### ISSUE TITLE
Multiple Terminal Options in UI

### ISSUE THREAD

**Issue by kd7vrc** [Microsoft/vscode#57970]
Currently, the setting `"terminal.integrated.shell.windows":` sets only one terminal (command prompt, PowerShell, bash, etc.) for any file type.

I would like to add multiple terminals in the settings, bound to languages or file extensions, and one default terminal.  I can set it so when I open the terminal while editing a .ps1 file, the terminal is PowerShell.  When editing a .sh file, it opens bash.  When editing a .py file, it could even open ipython.  These could be the default terminals set in settings, but the UI could have a dropdown with all configured terminals to choose from.

I'm getting along just fine with PowerShell as my one terminal, and launching ipython within PowerShell, but I think more terminal options in the UI would be nice.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/45444
