### ISSUE TITLE
Improve detection of current Markdown heading

### ISSUE THREAD

**Issue by garyking** [microsoft/vscode#57979]
- VSCode Version: Version 1.27.0 (1.27.0) 
- OS Version: Mac 10.13.5 (17F77)

Steps to Reproduce:

In this code: 

```
# a

- b

---

- c
```

In VSC right now, `- c` is considered to be part of the `# a` heading, in the outline and breadcrumbs. But it probably shouldn't be? In my own Markdown files, I consider `- c` to not be part of `# a`, because the `---` is meant to separate the two. So, in VSC, that should also be the case. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Due to the lack of further feedback on this issue, I'm closing it as out of scope
