### ISSUE TITLE
Fails to start from the launcher (Ubuntu 14, VMWare)

### ISSUE THREAD

**Issue by bughit** [Microsoft/vscode#57972]
- VSCode Version: 1.26.1 x64
- OS Version: ubuntu Ubuntu 14.04.5 x64 in a vmware vm

Steps to Reproduce:

1. launch from ubuntu launcher

![image](https://user-images.githubusercontent.com/895588/45107010-3a401b00-b106-11e8-9118-111eb81d04fa.png)

- removing and adding to the launcher, reinstalling does not resolve this
- this used to work, not sure if a vscode or a ubuntu update broke it
- launching from the terminal works

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by bughit** [comment]
running from the command line does not manifest the problem

terminal
```
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[main 11:19:40 AM] Starting VS Code
[main 11:19:40 AM] from: /usr/share/code/resources/app
[main 11:19:40 AM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  add: false,
  a: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  'open-url': false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  issue: false,
  'skip-getting-started': false,
  'skip-release-notes': false,
  'sticky-quickopen': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'skip-add-to-recently-opened': false,
  status: false,
  s: false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false }
[main 11:19:40 AM] Resolving machine identifier...
[main 11:19:40 AM] Resolved machine identifier: 
[main 11:19:40 AM] update#setState idle
xdg-settings: unexpected/missing argument
Try 'xdg-settings --help' for more information.
[main 11:19:40 AM] windowsManager#open
[31596:0906/111942.745001:INFO:CONSOLE(1397)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1397)
[31596:0906/111942.847339:INFO:CONSOLE(1397)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1397)
[31596:0906/111942.862605:INFO:CONSOLE(1397)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1397)
[31596:0906/111943.019421:INFO:CONSOLE(1397)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1397)
[main 11:19:43 AM] IPC#vscode-workbenchLoaded
[main 11:19:43 AM] windowsService#whenSharedProcessReady
[main 11:19:43 AM] windowsService#getRecentlyOpened 1
[main 11:19:43 AM] windowsService#getRecentlyOpened 1
[main 11:19:43 AM] windowsService#setRepresentedFilename 1
[main 11:19:43 AM] windowsService#getRecentlyOpened 1
[main 11:19:43 AM] windowsService#setRepresentedFilename 1
[main 11:19:43 AM] windowsService#getWindowCount
[31596:0906/111943.542295:INFO:CONSOLE(1397)] "%c INFO", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1397)
[main 11:19:44 AM] windowsService#isFocused 1
[31596:0906/111944.788183:INFO:CONSOLE(1397)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1397)
[31596:0906/111946.035757:INFO:CONSOLE(1397)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1397)
[31596:0906/111946.038283:INFO:CONSOLE(1397)] "%cTRACE", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1397)
[main 11:20:10 AM] update#checkForUpdates, state =  idle
[main 11:20:10 AM] update#setState checking for updates
[main 11:20:10 AM] RequestService#request https://vscode-update.azurewebsites.net/api/update/linux-x64/stable/493869ee8e8a846b0855873886fc79d480d342de
[main 11:20:11 AM] update#setState available for download
[31596:0906/112037.639724:VERBOSE1:CONSOLE(8192)] "Main._createAppUI: 18.617919921875ms", source: chrome-devtools://devtools/bundled/inspector.js (8192)
[31596:0906/112037.658599:VERBOSE1:CONSOLE(8192)] "Main._showAppUI: 17.7861328125ms", source: chrome-devtools://devtools/bundled/inspector.js (8192)
[31596:0906/112037.724584:VERBOSE1:CONSOLE(8192)] "Main._initializeTarget: 4.9521484375ms", source: chrome-devtools://devtools/bundled/inspector.js (8192)
[31630:0906/112922.451706:WARNING:x11_util.cc(1353)] X error received: serial 65, error_code 3 (BadWindow (invalid Window parameter)), request_code 4, minor_code 0 (X_DestroyWindow)
```

console.log
```
TRACE openWorkbench configuration {"_":[],"help":false,"h":false,"version":false,"v":false,"wait":false,"w":false,"diff":false,"d":false,"add":false,"a":false,"goto":false,"g":false,"new-window":false,"n":false,"unity-launch":false,"reuse-window":false,"r":false,"open-url":false,"performance":false,"p":false,"prof-startup":false,"verbose":true,"logExtensionHostCommunication":false,"disable-extensions":false,"disableExtensions":false,"list-extensions":false,"show-versions":false,"nolazy":false,"issue":false,"skip-getting-started":false,"skip-release-notes":false,"sticky-quickopen":false,"disable-restore-windows":false,"disable-telemetry":false,"disable-updates":false,"disable-crash-reporter":false,"skip-add-to-recently-opened":false,"status":false,"s":false,"file-write":false,"file-chmod":false,"driver-verbose":false,"appRoot":"/usr/share/code/resources/app","machineId":"9b9bd05a72f3b8a6291f3efd5bcde8dad9c077f08948b95039c7a3caaf6a544b","execPath":"/usr/share/code/code","userEnv":{"VSCODE_IPC_HOOK":"/run/user/1000/vscode-d32d3ff9-1.26.1-main.sock","VSCODE_NLS_CONFIG":"{\"locale\":\"en-us\",\"availableLanguages\":{}}","VSCODE_LOGS":"/home/user1/.config/Code/logs/20180906T111940"},"isInitialStartup":true,"filesToOpen":[],"filesToCreate":[],"filesToDiff":[],"nodeCachedDataDir":"/home/user1/.config/Code/CachedData/493869ee8e8a846b0855873886fc79d480d342de","backupPath":"/home/user1/.config/Code/Backups/1520882264199","windowId":1,"logLevel":0,"fullscreen":false,"highContrast":false,"accessibilitySupport":false,"baseTheme":"vs","backgroundColor":"#ffffff","maximized":false,"perfEntries":["mark","main:started",1536247180281,0,0,"mark","main:appReady",1536247180365,0,1,"mark","main:loadWindow",1536247181035,0,0],"perfStartTime":1536247180281,"perfWindowLoadTime":1536247181036}
log.ts:147 TRACE lifecycle: starting up (startup kind: 1)
log.ts:147 TRACE lifecycle: phase changed (value: 2)
log.ts:147 TRACE lifecycle: phase changed (value: 3)
log.ts:159  INFO no standard startup: not just one text editor
log.ts:147 TRACE CommandService#executeCommand setContext
log.ts:147 TRACE lifecycle: phase changed (value: 4)
log.ts:147 TRACE RequestService#request https://az764295.vo.msecnd.net/experiments/experiments.json
```

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/883208e30da25777874a8ade5f90e1fea638a298/VSCode-win32-x64-1.28.0-exploration.zip)
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/883208e30da25777874a8ade5f90e1fea638a298/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/883208e30da25777874a8ade5f90e1fea638a298/code-exploration-1535724826.tar.gz)

**Comment by bughit** [comment]
same problem with exploration build

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by bughit** [comment]
There's no crash.  Why don't you try to repro this?  There is nothing unusual about my install, it's an ubuntu 14.04 vmware vm with all updates.

**Comment by bpasero** [comment]
If anyone with a Ubuntu 14 could see if VSCode starts, that would be great.

**Comment by clockcloud** [comment]
I have the same problem on Ubuntu 14.04.5 & vmware 14.1.3
1.26.1 x64 and 1.27.1 x64 have the same problem, but 1.25.1 x64 works fine

**Comment by Tyriar** [comment]
@bpasero no at the moment, I even bricked my office Ubuntu 18.04 install 😱

**Comment by bpasero** [comment]
I cannot reproduce this:

![image](https://user-images.githubusercontent.com/900690/45476250-c5409700-b73e-11e8-8aaa-c129f0bebffe.png)

Running 14.04 LTS, `3.16.0-77-generic`

Tried with: [Download](https://az764295.vo.msecnd.net/stable/7b9afc4196bda60b0facdf62cfc02815509b23d6/code_1.27.0-1536125615_amd64.deb)

Closing due to this, I see no fix on our end that could have an impact currently.

**Comment by bughit** [comment]
@bpasero 

- Why did you change the title? It contained pertinent info.
- in your reproduction
  - was it a vmware vm? (the two reports in this issue are on vmware)
  - was it a fully updated 14.04? (an ubuntu update could have contributed)
  - were you starting from the launcher or the command line? (you removed "fails to start from ubuntu launcher" from the title)

**Comment by bpasero** [comment]
> was it a vmware vm? (the two reports in this issue are on vmware)

Parallels

> was it a fully updated 14.04? (an ubuntu update could have contributed)

Yes, always latest.

> were you starting from the launcher or the command line? (you removed "fails to start from ubuntu launcher" from the title)

I started from the launcher (the thing that you can search for applications)

**Comment by bughit** [comment]
Ubuntu also calls the "dock" the launcher (lock to launcher, unlock from launcher), that's what I was referring to. However I can repro also from the search, so that miscommunication wasn't significant.

**Comment by bughit** [comment]
> but 1.25.1 x64 works fine

confirming

**Comment by bughit** [comment]
here's the corresponding electron issue: electron/electron#13624

it affects all version after 1.x

can be worked around with --disable-gpu

this should be fixable in electron which can blacklist drivers e.g.
https://github.com/electron/libchromiumcontent/pull/665/files#diff-698cc208a47d511601941e01060994e3R106

**Comment by bughit** [comment]
By the way, you command line launcher (`/usr/share/code/bin/code`) somehow manages to launch successfully with the electron gpu process, it does not use `--disable-gpu`. So it seems you already have some work-around for this, why can't you use it in the main electron process?

**Comment by bughit** [comment]
Also [redirecting stdout](https://github.com/electron/electron/issues/13624#issuecomment-404591743) gets around this somehow, which is what your cmdline launcher probably does (or something similar).

Any plans to address this?

**Comment by summer-tt** [comment]
@bpasero @bughit 

I have the same problem with VS Code 1.30.2. My OS is Ubuntu 14.04.5 LTS running in VMware Workstation 14.1.2.

I tried the following method, and it fixed the issue:
I modified the .desktop file of Visual Studio Code (path: /usr/share/applications/code.desktop) as following:

![.desktop file](https://user-images.githubusercontent.com/656838/50888329-64954280-1430-11e9-9049-a9c6b835304b.png)

I modified line 5, changed `/usr/share/code/code` to `/usr/share/code/bin/code`.

**Comment by bpasero** [comment]
@summer-tt this does not help in my case, however I managed to get rid of this issue by configuring `StartupNotify=false`

@Tyriar please give that a try and consider to change it, seems to work perfect for me once I change that.

**Comment by Tyriar** [comment]
@bpasero I can't repro in virtualbox, did you need vmware to repro? Reading through https://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html I don't think we notify to false might be the right option?

@flexiondotorg any insights here? Are Electron apps meant to have `StartupNotify=true`/false?

**Comment by bughit** [comment]
This specific bug (vmware + 14.04) is not affected by `StartupNotify=false`

The generric electron workarounds are [here](https://github.com/electron/electron/issues/13624#issuecomment-404591743)

And the vscode specific one is to use the command line launcher (`/usr/share/code/bin/code`)

**Comment by flexiondotorg** [comment]
@Tyriar I've not investigated the effect of `StartupNotify` with Electron apps. That said, true or false should not impact the ability to start the application at all. Next week I'll test and see if Electron apps honor the `StartupNotify`

**Comment by bpasero** [comment]
@Tyriar sorry, I don't know how but my comment ended up here even though it was meant for https://github.com/Microsoft/vscode/issues/65460. My comment being a fix for not being able to start VSCode on Ubuntu 14 is a red herring, ignore it.

**Comment by bpasero** [comment]
@bughit does it still reproduce with our latest insider builds (that use Electron 3.0.13)?

**Comment by bughit** [comment]
I haven't tried your builds but the underlying issue appears to be fixed in the latest electrons 3.0.14, 3.10, 4.0.1

**Comment by bpasero** [comment]
I am curious what change in 3.0.14 would that be: https://github.com/electron/electron/compare/v3.0.13...3-0-x

We run with 3.0.13 and there it reproduces still?

**Comment by bughit** [comment]
electron 3.0.13 is ok

**Comment by bpasero** [comment]
Can this be closed then?

**Comment by bughit** [comment]
sure
