### ISSUE TITLE
VScode crash and core dump on start

### ISSUE THREAD

**Issue by yanntm** [Microsoft/vscode#57978]
- VSCode Version: code-1.26.1-1534444904.el7.x86_64   
- OS Version: [GNU C Library (GNU libc) stable release version 2.28. Compiled by GNU CC version 8.2.1 20180824.] It's a Mageia Linux.

Steps to Reproduce:

1. install : dnf install code
2. run `code`

Does this issue occur when all extensions are disabled?: Yes

Result :
/bin/code: line 35: 31564 Segmentation fault      (core dumped) ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"

This is the same problem described in #51917 but that issue was closed for some reason, without the problem being solved afaics. Please provide a workaround that does not involve downgrading glibc, that is not an option.

**Comment by yanntm** [comment]
Yes, it's the same crash, but I'm not on Arch linux. If this is (yet another ) dup of #55934 then that issue should be renamed to something more general. idk what electron is or does (nor do I care) and I'm not on Arch.

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by JohnzBallad** [comment]
Just did @bpasero. As I read at  #57776, electron-atos only works in macOS and I use Kubuntu 18.10, as I told before. Also, i'm trying code-exploration and I let you know if something good pops up! 

Thanks, anyway.

**Comment by bpasero** [comment]
Yeah please do.

**Comment by JohnzBallad** [comment]
Working just fine, lol. 
![image](https://user-images.githubusercontent.com/13936071/45139562-859a0e00-b186-11e8-9d58-28236bd2db28.png)

**Comment by bpasero** [comment]
Maybe @yanntm could try that too.

**Comment by marcelhekking** [comment]
I have exactly the same error. This is on Ubuntu 18.10. Code-exploration just works

**Comment by marcelhekking** [comment]
@bpasero Can I make my the 'Code-exploration' works with my current vscode installation?

**Comment by bpasero** [comment]
@marcelhekking I would advise against that as the exploration build uses a much newer Electron version. But you can copy over the keybindings.json, settings.json and extensions.

**Comment by marcelhekking** [comment]
And also all my extensions?

**Comment by marcelhekking** [comment]
OK! And where should I copy them to?

**Comment by marcelhekking** [comment]
Btw, do you think that this bug will be likely fixed in coming insiders builds?

**Comment by bpasero** [comment]
@marcelhekking copy over from `/home/user/.config/code/` to `/home/user/.config/code-exploration/`

**Comment by marcelhekking** [comment]
Great! Thanx

**Comment by JohnzBallad** [comment]
@bpasero what is happening with electron in the 1.27 build of vscode? I mean, will I have to change to code-exploration for good? :(

**Comment by JohnzBallad** [comment]
Nothing yet?

**Comment by yanntm** [comment]
I gave up, doing c++ on eclipse CDT is not awesome, but at least it runs.
