### ISSUE TITLE
Dismissing a workbench message doesn't wrap up API promise

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#5797]
Testing #5743

The promise returned by `vscode.window.showInformationMessage()` never completes if the user dismisses it with <kbd>Escape</kbd>.

I expected it to complete with `undefined`, similarly to when pressing `Close`.

**Comment by jrieken** [comment]
Good find. @bpasero How do I find out when dispose by Esc happens?

**Comment by bpasero** [comment]
@jrieken hm, not so straight forward but I can see two possible options with the existing way it works:
* I seem to dispose the actions of messages when they get hidden so you could detect that in your action (e.g. the close action if you have one) and know that the message hides
* there is an event `onMessagesCleared` that gets fired after all messages get cleared (https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/message/browser/messageService.ts#L55). this event is currently not exposed on `IMessageService` but we could add it there

**Comment by jrieken** [comment]
I can go with option #1
