### ISSUE TITLE
Breadcrumb Bar Not Detecting Functions

### ISSUE THREAD

**Issue by kd7vrc** [Microsoft/vscode#57973]
Issue Type: <b>Bug</b>

The breadcrumb bar works intermittently.  It sometimes does not detect functions in my .py code (complete and valid).  When I click through the code, it doesn't show the function my cursor is currently in.  I also can't browse functions.  There is no arrow after the file name to select sub-objects (functions).

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.49GB (8.81GB free)|
|Process Argv|C:\Users\browns\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
dealii-prm|dav|0.0.1
pgsql|dou|0.1.3
vs-code-xml-format|fab|0.1.5
hive-sql|jos|0.0.4
mssql|ms-|1.4.0
python|ms-|2018.7.1
PowerShell|ms-|1.8.4
java|red|0.30.0
vscode-sql-beautify|sen|0.0.4
line-endings|ste|1.0.2

</details>

**Comment by mjbvz** [comment]
Do you mean the breadcrumbs at the top of the document?

<img width="902" alt="screen shot 2018-09-05 at 9 47 51 am" src="https://user-images.githubusercontent.com/12821956/45108192-c6dfde80-b0f0-11e8-9cd7-3ef991b45a19.png">

Or the minimap to the right of the document?

<img width="437" alt="screen shot 2018-09-05 at 9 48 50 am" src="https://user-images.githubusercontent.com/12821956/45108229-e840ca80-b0f0-11e8-8de5-1abd6177f6fc.png">

**Comment by anishghosh103** [comment]
don't you know the right side view of the whole code is called minimap..

**Comment by kd7vrc** [comment]
Sorry, I mean breadcrumbs.  I'll correct the issue accordingly.

**Comment by mjbvz** [comment]
The breadcrumbs contents come from the python extension. Please file this issue against that extension
