### ISSUE TITLE
not avlue to open cpp file

### ISSUE THREAD

**Issue by jonycodes** [Microsoft/vscode#57981]
Issue Type: <b>Bug</b>

If you have access to the OS branch try to navigate to os_\src\onecoreuap\admin\dm\tools\dmlaunch, if you go through VSCode you won't see any files there. But if you go through regular Windows Explorer you will find three files main.cpp. main.h and sources. Also when you try to open the file main.cpp it says unable to open main.cpp: file not found. I'm able to open it in Notepad so I don't think it's the file. Also, tried again 10 minutes later and it worked, so it's a pretty weird bug. 

VS Code version: Code - Insiders 1.27.0-insider (346018a80dd299c50cbf213e0a706ef0f35f3a67, 2018-08-24T05:19:27.628Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (18.89GB free)|
|Process Argv|C:\Users\jopinale\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
cobol|bit|3.4.3
dep|car|0.1.0
cpptools|ms-|0.18.1
csharp|ms-|1.15.2
platformio-ide|pla|1.1.0

</details>

**Comment by bpasero** [comment]
@jonycodes can you show a screen shot where you want to open that file?
