### ISSUE TITLE
Any way to add google analytics code in extension to get manually reports

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#5798]
Hi , 
Is there any way to get the extension user usage from Google Analytics or any other 3rd party tool by integrating the code in Extension code.

**Comment by bpasero** [comment]
@chrisdias can you chime in?

**Comment by seanmcbreen** [comment]
Hi,

I can jump in.

As an extension you certainly could add your own custom telemetry code - leveraging GA or other tools - we use Application Insights.  However, there is no set of best practices established today for community extensions.  We would be interested in anything you come up with.

I'll close this issue for now - but please fell free to re-open.

Sean

**Comment by DanTup** [comment]
@shanalikhan I did some Googling and found this sample in an Google repo that makes it look like sending efforts is a very trivial HTTP request. I haven't tried it yet, but looks promising :)

https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/appengine/analytics/app.js#L31

```
function trackEvent (category, action, label, value, cb) {
  var data = {
    v: '1', // API Version.
    tid: GA_TRACKING_ID, // Tracking ID / Property ID.
    // Anonymous Client Identifier. Ideally, this should be a UUID that
    // is associated with particular user, device, or browser instance.
    cid: '555',
    t: 'event', // Event hit type.
    ec: category, // Event category.
    ea: action, // Event action.
    el: label, // Event label.
    ev: value // Event value.
  };

  request.post(
    'http://www.google-analytics.com/collect', {
      form: data
    },
    function (err, response) {
      if (err) {
        return cb(err);
      }
      if (response.statusCode !== 200) {
        return cb(new Error('Tracking failed'));
      }
      cb();
    }
  );
}
```
