### ISSUE TITLE
vscode.executeDocumentSymbolProvider command only returns SymbolInformation[] rather than DocumentSymbol[]

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#57984]
Currently the `vscode.executeDocumentSymbolProvider` returns instances of `SymbolInformation` rather than the newer `DocumentSymbol`. I'm sure this was done for backward compatibility. Can a flag be added to `vscode.executeDocumentSymbolProvider` to allow it to return `DocumentSymbol`? Or maybe a new complex command to access the `DocumentSymbol`s?

I would really like for GitLens to be able to have access to the better range information contained in the `DocumentSymbol`s. 

Also if there is consensus on the direction of this, I can provide a PR.

/cc @jrieken

**Comment by jrieken** [comment]
Yeah, we weren't sure yet how to do that... It is for backwards compatibility and this command is very frequently used. I can check if that's still the case

**Comment by eamodio** [comment]
Maybe `vscode.executeDocumentSymbolProvider.v2` or something along those lines (that could be used for any complex command)

**Comment by jrieken** [comment]
Yeah, not sure yet. We always wanted to be more relaxed with those commands and have the freedom to kinda break them. Tho this is a special case since there is many user of that command. I am thinking of some kind of merged type ala `vscode.DocumentSymbol & vscode.SymbolInformation`. That should be the best of both worlds...

**Comment by eamodio** [comment]
Somewhat related (especially with a merged type), I see internally `DocumentSymbol` has `containerName` just like `SymbolInformation`, why is that not exposed on the vscode.d.ts version of `DocumentSymbol`?

**Comment by eamodio** [comment]
How do you get the parent info? Isn't there only children access?
