### ISSUE TITLE
Editor doesn't detect duplicate keys in Redux mapDispatchToProps / mapStateToProps

### ISSUE THREAD

**Issue by RockinRonE** [Microsoft/vscode#57986]
- VSCode Version: 1.26.1
- OS Version: 10.13.6

<img width="669" alt="screen shot 2018-09-05 at 2 07 34 pm" src="https://user-images.githubusercontent.com/8163241/45115304-146e4280-b115-11e8-86c1-ebbd0b9093dd.png">

The editor is able to detect the duplicate `const test` declaration, but it's not able to detect the duplicate `modalHide` in `mapDispatchToProps`. Intellij is able to detect this.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Is this in a typescript file? Or are you using checkJs in a js file?

**Comment by RockinRonE** [comment]
@mjbvz Thanks for looking into this! It is not a typescript file and no checkJs. Please let me know anything else you need!

**Comment by mjbvz** [comment]
Can you share a screenshot of the message when you hover over the error squiggly on `test`. Our built-in js support should not report semantic errors so I need to know where it the error is coming from

**Comment by RockinRonE** [comment]
So...in desperation I installed eslint globally and added a global eslintrc file. That's what was producing the red line. I've since removed the eslintrc file. 

Are you saying VSCode doesn't detect these type of errors...such as duplication?

**Comment by mjbvz** [comment]
Yes we only report syntax errors by default in js files, mainly because js allows for lots of craziness that would produce a lot of false positive errors in our tooling.

Consider using [checkJs](https://code.visualstudio.com/Docs/languages/javascript#_type-checking) if you want more advanced built-in semantic analysis, or another extension like  eslint

**Comment by RockinRonE** [comment]
@mjbvz Thanks for the recommendation! All setup and does what I was looking for 👍
