### ISSUE TITLE
VS Code removed from the machine after latest update

### ISSUE THREAD

**Issue by rugved** [Microsoft/vscode#57983]
- VSCode Version: V 1.27 
- OS Version: windows 10

Steps to Reproduce:

1. Open V 1.26 vs code
2. Click on prompt to update the vs code
3. Entire vs code is removed from the machine. Can't find it in control panel as well.

Solution
Download and install again

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by pietrodicaprio** [comment]
Got same issue here.
Last night W10 was updated to April release, now VS Code tried to update and provided an error message saying that an anti virus (maybe) is blocking the installation but no AV is installed on my PC.
Error log attached. In the last lines you can see that deletes the complete installation of VSC and then gives a "ERRO" (lol):

> ERRO The process cannot access the file because it is being used by another process. (os error 32)

[vscode-inno-updater-1536175437.log](https://github.com/Microsoft/vscode/files/2354292/vscode-inno-updater-1536175437.log)
