### ISSUE TITLE
NVDA reads placeholder text in showQuickPick dropdown twice

### ISSUE THREAD

**Issue by cait1inhennessy** [Microsoft/vscode#57999]
Repro Steps:
1. Show any dropdown with the vscode.window.showQuickPick API
2. Check whether NVDA is reading the placeholder text in the input box only once

OR
1. Install Live Share extension for VSCode
2. Press customized keyboard shortcut for "Sign In using browser(Sign In)" to open the Sign In window in browser.
3. Navigate to the Name of the user logged in and press enter
4. Start NVDA 
5. Check whether NVDA is reading the placeholder text in Collaboration only once

Actual Result:-
NVDA is reading the placeholder text twice

Expected Result:-
All the content and controls in the page should read only once by the screen reader until and unless users gives a command to read for multiple times

User Impact:-
Screen reader users feel difficulty in using application if NVDA reads the content twice

MAS Reference:-
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={1ee227a7-e3c5-47b8-ab18-48ca8595077b}

OS: Windows 10 Enterprise 17134.228

**Comment by cait1inhennessy** [comment]
![capture2](https://user-images.githubusercontent.com/16658549/45172326-dc6d0b00-b1b9-11e8-8d43-1499df766e41.PNG)

In our case, the quick pick menu looks like this.  The text being read twice is the placeholder "What would you like to do..."

**Comment by bpasero** [comment]
@chrmarti I am not getting twice announced e.g. when opening the language picker:

![image](https://user-images.githubusercontent.com/900690/46091059-4cb3ee80-c1b2-11e8-876a-2c78e05651ad.png)

What is so special about the quick input API, isn't it the same control after all?

**Comment by chrmarti** [comment]
Using `aria-describedby` to fix part of #58105 has silenced the `title` attribute with NVDA and VoiceOver. :D

**Comment by ramya-rao-a** [comment]
I would re-open this issue.

The expectation was that the placeholder is read only once.
Now it is not read at all.

**Comment by chrmarti** [comment]
@ramya-rao-a Did you enable Screen Reader mode when testing? This needs some special handling (not focusing the first item) to work.

**Comment by ramya-rao-a** [comment]
Works when in screenreader mode
