### ISSUE TITLE
Add an option for including comments when using 'Copy to Settings' for 'User Settings'.

### ISSUE THREAD

**Issue by changeling** [Microsoft/vscode#57993]
It would be useful to include comments when editing a setting using `Copy to Settings` for `User Settings`, at least as an option for those who prefer that aesthetic.

Either as a setting itself, or as a menu item when editing:

Something like:

> `Copy to Settings`
> `Copy with Comment to Settings`

And/or a setting to define default behavior for `Copy to Settings`. This might be best, as most folks will likely prefer one over the other for all settings.

Maintaining consistency with `Default User Settings` file is more comfortable when visually scanning `User Settings` for some. Scanning a compact list for others.

**Comment by roblourens** [comment]
We are focused on the new settings UI now, so I probably won't be investing much more in the JSON editor features.
