### ISSUE TITLE
Apply an account to join vscode-dev-community.slack.com

### ISSUE THREAD

**Issue by zhaoyi0113** [Microsoft/vscode#58004]
Could you let me know how to apply an account to access vscode-dev-community.slack.com? I couldn't find anywhere mentioned the process so I create an issue here.

**Comment by auchenberg** [comment]
Hi,

You can join the community run Slack channel by using this link, https://vscode-dev-community.slack.com/join/shared_invite/enQtMjIxOTgxNDE3NzM0LWU5M2ZiZDU1YjBlMzdlZjA2YjBjYzRhYTM5NTgzMTAxMjdiNWU0ZmQzYWI3MWU5N2Q1YjBiYmQ4MzY0NDE1MzY

/k

**Comment by auchenberg** [comment]
New link for the Slack community, https://aka.ms/vscode-dev-community
