### ISSUE TITLE
Live Share: loss of focus after clicking custom pin button in top editor bar

### ISSUE THREAD

**Issue by cait1inhennessy** [Microsoft/vscode#58001]
Repro Steps:-
1. Install Live Share extension for VSCode
2. Press customized keyboard shortcut for "Sign In using browser(Sign In)" to open the Sign In window in browser.
3. Open the link shared by host to join collaboration session in browser.
4. Then navigate till pin button present in the upper right corner
5. Verify whether there is loss of focus

![capture1](https://user-images.githubusercontent.com/16658549/45119889-7af16180-b111-11e8-980a-0de5d210af6c.png)

Actual Result:-
There is loss of focus after we select or deselect the pin button
When we click on follow/unfollow button focus is missing

Expected Result:-
There should not be any loss of focus in the application

User Impact:-
Users will face difficulties while using the application if there is loss of focus

Note: Similar issue is observed in Mac as well.

MAS Reference:-
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={0de7fbe1-ad7e-48e5-bcbb-8d986691e2b9}

OS: Windows 10 Enterprise 17134.228

**Comment by isidorn** [comment]
Please file this against the live share extension
