### ISSUE TITLE
When searching in new Settings windows some search criteria with no "No Settings Found" is overlaid with found items

### ISSUE THREAD

**Issue by LordHog** [Microsoft/vscode#58008]
With the newest release of VSC, v1.27, was searching for settings and found some cases when search criteria was entered resulted in "No Settings found" overlaid with results.  Here is an image of one case:

![image](https://user-images.githubusercontent.com/970098/45125225-68335880-b122-11e8-8132-60b58569bb37.png)

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/57991

**Comment by LordHog** [comment]
@roblourens Oh, thanks.  I did search for "settings", but I didn't see that one. Thanks.
