### ISSUE TITLE
Vs Code fails to update in Windows 10

### ISSUE THREAD

**Issue by Nicodebug** [Microsoft/vscode#58013]
Issue Type: <b>Bug</b>

Despues de actualizar de la version 1.26 a la version 1.27.0 VS Code no arranca, queda con la ventana negra y no responde a ninguna funcion. Borré extensiones y Datos locales pero aun asi no funciono.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (5.08GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-es|MS-|1.23.1

</details>

**Comment by Nicodebug** [comment]
El problema ocurrió  al hacer Update a la version 1.27.0, este reporte lo hago desde el PC que falló pero con una nueva instalación en la version 1,23,1

**Comment by mjbvz** [comment]
> After upgrading from version 1.26 to version 1.27.0 VS Code does not start, left with the black window and does not respond to any function. I deleted local extensions and data but it still didn't work.

> The problem occurred when updating the version 1.27.0, this report I do from the PC that failed but with a new installation in version 1, 23,1

**Comment by marigonzes** [comment]
Same as #57982

**Comment by AndusMcCoatover** [comment]
Following error log generated when updating VSCode from ver 1.26.1 on Windows 10 ver 1803 build 17134.228

[vscode-inno-updater-1536191308.log](https://github.com/Microsoft/vscode/files/2354947/vscode-inno-updater-1536191308.log)
