### ISSUE TITLE
"There are no active source control providers"

### ISSUE THREAD

**Issue by dragonfax** [Microsoft/vscode#58017]
Issue Type: <b>Bug</b>

I was happily working along, changing code, checking it in. I restarted VS Code, and now it cant' find git.

It had no problem finding git before (located in /usr/local/bin/git). but sometimes it finds and sometimes it doesn't. Its non-deterministic. I've tried starting it from macos finder, and starting it from the command line. Both situations it could or could not find git.

VS Code version: Code 1.27.0 (7b9afc4196bda60b0facdf62cfc02815509b23d6, 2018-09-05T05:22:06.672Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.32GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.4
vscode-docker|Pet|0.1.0
vscode-database|baj|1.5.2
solargraph|cas|0.17.6
dart-code|Dar|2.18.0
cpptools|ms-|0.18.1
Go|ms-|0.6.89
gradle-language|nac|0.2.3
ruby|reb|0.20.0
java|red|0.30.0
vscode-arduino|vsc|0.2.20
vscode-java-debug|vsc|0.12.1
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.8.0
vscode-maven|vsc|0.10.0
vim|vsc|0.16.3
JavaScriptSnippets|xab|1.7.0
vscode-open-in-github|ziy|1.3.5

</details>

**Comment by dragonfax** [comment]
Looks like my email attachments never made it into the Issue. Here they are.

<img width="1332" alt="running_extensions_ _flutter_2048" src="https://user-images.githubusercontent.com/933806/45170634-2d2e3500-b1b5-11e8-9155-bc555f9ec362.png">
<img width="570" alt="jstillwell_ _-bash_ _80x24" src="https://user-images.githubusercontent.com/933806/45170635-2d2e3500-b1b5-11e8-9f93-9185a954c4ea.png">
<img width="1073" alt="developer_tools_-_file____applications_visual_20studio_20code_app_contents_resources_app_out_vs_workbench_electron-browser_bootstrap_index_html_config__7b_22__22_3a_5b_5d_2c_22help_22_3afalse_2c_22h_22_3afalse_2c_22version_22_3afalse_2c_22v" src="https://user-images.githubusercontent.com/933806/45170636-2d2e3500-b1b5-11e8-8a5b-8feaadd3fca7.png">

**Comment by dragonfax** [comment]
The `/usr/local/bin/git` comes from brew.
All xcode licenses are accepted.  (that used to be a cause of this issue)

**Comment by joaomoreno** [comment]
In Code's devtools Console, what does `process.env.PATH` return?

**Comment by dragonfax** [comment]
"/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin:/Users/jstillwell/.yarn/bin:/Users/jstillwell/Code/zendesk/docker-images/dockmaster/bin:/usr/local/opt/qt@5.5
/bin:/usr/local/sbin:~/flutter/bin:/Users/jstillwell/.nvm/versions/node/v6.3.0/bin:/Users/jstillwell/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/Wireshark.app/Contents/MacOS:~/Library/google-cloud-sdk/bin/:~/Code/depot_tools:~/Library/Android/sdk/platform-tools/:~/go/bin"

This seems to happen with some specific projects.
It doesn't seem to matter if I start vscode from Finder, or via the command
line tool.
I checked the path value for both a working and non-working project, and
they both have the same path.

Thanks again for the help, btw.

**Comment by joaomoreno** [comment]
> This seems to happen with some specific projects.

Any way we can maybe use this to try to find out what is it that causes the issue? Which projects work and which don't?

**Comment by joaomoreno** [comment]
What if you open a Flutter project with `code --disable-extensions`?

**Comment by dragonfax** [comment]
That won't disable the built-in extensions?

**Comment by dragonfax** [comment]
Sorry, it has no affect. "there are no source control providers" when I
open a problem project.

**Comment by dragonfax** [comment]
Wait, let me take that back.

`code --disable-extensions` didn't disable the extensions in the project.
even from the project directly.

but `code -disable-extensions .` did.

And with extensions disabled, the git built-in extension did start to work.

So I'll track down which extension is conflicting with git.

**Comment by dragonfax** [comment]
Yeah, its the dart extensions. I'll take it to them to find out why its
stopping the git extension.

**Comment by dragonfax** [comment]
Thanks for the help.

**Comment by DanTup** [comment]
@joaomoreno I'm the author of the Dart/Flutter extensions. I don't think there's anything in here that should be able to affect Git so I'm not sure how to troubleshoot this (it doesn't seem to happen locally for me). If there's anything I can do that might help track this down, please let me know.

**Comment by dragonfax** [comment]
Thanks for the response.

Seems to be fixed since I added `"git.ignoreMissingGitWarning": false` to my settings.

**Comment by joaomoreno** [comment]
No idea.

@dragonfax You haven't showed us the output of `Git: Show Git Output`?

**Comment by dragonfax** [comment]
It doesn't show up when the git extension isn't active.

**Comment by dragonfax** [comment]
When everything is working. this is what we've got.

```
Looking for git in: /usr/local/bin/git
Using git 2.14.1 from /usr/local/bin/git
> git rev-parse --show-toplevel
> git config --get commit.template
Open repository: /Users/jstillwell/Code/dragonfax/XXXXXX
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git check-ignore -z --stdin
```

**Comment by joaomoreno** [comment]
The command doesn't appear in the command palette at all? Or, you run it and it doesn't show up?

**Comment by dragonfax** [comment]
You know. frustratingly, even when I put `"git.ignoreMissingGitWarning":
true` back into my settings.json. The Git extensions continues to work
fine. Even with the problem projects.

In other words, I can no longer replicate the issue.

It could have been some legacy thing. Since I don't remember doing it, I
probably enabled ignoreMissingGitWarning more than a year ago, possibly
several years.  Having disabled it (the default value) at least once, has
fixed everything going forward.

**Comment by joaomoreno** [comment]
Too bad. Let me know if it comes back.
