### ISSUE TITLE
Pinned taskbar icon disappears after User Setup updates

### ISSUE THREAD

**Issue by itowlson** [Microsoft/vscode#58019]
Issue Type: <b>Bug</b>

I have VS Code pinned to my taskbar.  VS Code auto-updated from 1.26.1 to 1.27.0.  During this process the taskbar icon disappeared.

Additionally, when I re-pinned the application, it had lost the workspaces I had pinned in the jumplist.

_Duplicate warning: This or a similar issue has been reported as https://github.com/Microsoft/vscode/issues/54419. But that was closed and locked, and I can't reopen or add comments, so I'm raising this as a new issue._

Steps to reproduce:

* Run VS Code 1.26.1 using User Setup
* Right-click the taskbar icon and choose "Pin to Taskbar"
* Right-click the icon again, choose something from the MRU list, and click the 'pin' button
* Wait for VS Code to update

Expected results:

* The taskbar icon remains in place, and the jump list still contains the pinned item

Actual results:

* The taskbar icon disappears
* On re-running Code and re-pinning it, the jumplist entry has disappeared.

VS Code version: Code 1.27.0 (7b9afc4196bda60b0facdf62cfc02815509b23d6, 2018-09-05T05:29:44.670Z)
OS version: Windows_NT x64 10.0.17744

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz (12 x 3492)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.93GB (46.11GB free)|
|Process Argv|C:\Users\itowlson\AppData\Local\Programs\Microsoft VS Code\Code.exe .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
gitlens|eam|8.5.6
tslint|eg2|1.0.38
python|ms-|2018.8.0
azure-account|ms-|0.4.3
Go|ms-|0.6.89
PowerShell|ms-|1.8.4
vscode-yaml|red|0.0.15

</details>

**Comment by joaomoreno** [comment]
@bpasero At some point you investigated this. Why is this happening?

**Comment by bpasero** [comment]
The fact that all jump-list entries disappear when the task icon is not pinned anymore seems like expected behaviour to me (though I am not an expert in that area).

What I do not understand is how the task bar icon can loose its pinned state in the first place.

**Comment by bpasero** [comment]
I take it back:
* for me the recently opened list stays intact even when I un-pin Code from the task bar
* updating Code did not remove the pinned task bar for me

@itowlson could it be you switched from global installation to user installation?

**Comment by itowlson** [comment]
@bpasero I switched from global to user at 1.26.0.  But now I think about it, I later (while trying to solve a performance problem) uninstalled user, reinstalled global, downgraded global, uninstalled global, and then reinstalled user.  Now I _thought_ I had re-pinned my taskbar item after all this, and am _pretty sure_ I'd seen the jump list items since reinstalling user... but you've put doubt in my mind!  Certainly there's been enough uninstalling-rather-than-updating that I don't feel I can justly pin this on the 1.27.0 update.  Let's close it as PEBKAC - if it happens again with 1.28 then we can always reopen.

Thanks for your attention, and many apologies for forgetting all the messing around I'd done!
