### ISSUE TITLE
terminal LANG still being set with terminal.integrated.setLocaleVariables = false

### ISSUE THREAD

**Issue by dvlsg** [microsoft/vscode#58015]
Issue Type: <b>Bug</b>

I believe issue #35550 is affecting me. Using VSCode 1.27.0 (User Setup), I still get LANG set in my integrated powershell terminal. I have `terminal.integrated.setLocaleVariables` set to `false` in my user settings, and my workspace settings are empty. Launching a separate powershell instance (outside of vscode) does not have LANG set.

I noticed #35550 is still just in a backlog, so I'm not 100% sure it's released to non-insider branches. But I do have the `terminal.integrated.setLocaleVariables` available in the settings search in this version, so I was assuming it should be available:

![image](https://user-images.githubusercontent.com/4721566/45127066-73d74d00-b12b-11e8-9c66-df97f752e47a.png)

---

I ran into this while trying to interact with the node [os-locale](https://github.com/sindresorhus/os-locale/blob/c52eef38093e592965268cea9946d39baa3e2bfb/index.js#L11) package, by launching the app instance from my vscode terminal. Took me a little bit to figure out why the locale being reported didn't match the windows system locale, which I was modifying to test some globalization functionality in my app. :)

----

Version: 1.27.0 (user setup)
Commit: 7b9afc4196bda60b0facdf62cfc02815509b23d6
Date: 2018-09-05T05:29:44.670Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

VS Code version: Code 1.27.0 (7b9afc4196bda60b0facdf62cfc02815509b23d6, 2018-09-05T05:29:44.670Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|15.91GB (8.81GB free)|
|Process Argv|C:\Users\Dave\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.5.0
gitlens|eam|8.5.6
tslint|eg2|1.0.38
prettier-vscode|esb|1.6.1
vsc-space-block-jumper|jmf|1.2.2
terraform|mau|1.3.4
csharp|ms-|1.15.2
vsliveshare|ms-|0.3.623
vscode-docker|Pet|0.1.0
vscode-icons|rob|7.25.0
markdown-preview-enhanced|shd|0.3.5
change-case|wma|1.0.0

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
I can't seem to repro, do you have the `$LANG` variable set on your system elsewhere or did you launch VS Code from a terminal which had it set? Anything to help repro would be good.

**Comment by dvlsg** [comment]
Hmm. I can reproduce on my home machine (which is using `1.27.1 (user setup)`, just double checked) and my work machine.

Just to be safe, I opened a powershell prompt to `C:\Users\Dave\AppData\Local\Programs\Microsoft VS Code>`, made sure that entering in `$env:LANG` doesn't return anything, then launched vs code from that same powershell terminal using `.\Code.exe --disable-extensions` (although, I get the same behavior with extensions still on - just wanted to rule them out).

Once vscode launches, then inside my intergrated powershell terminal, running `$env:LANG` echoes back `en_US.UTF-8`. User settings contains `"terminal.integrated.setLocaleVariables": false`, and my workspace settings are completely empty. 

Any other debugging information I could provide that would help narrow it down? Happy to send whatever else might be helpful.

**Comment by Tyriar** [comment]
Hm, it looks like you're right and it falls back to `en_US.UTF-8`, I'll try look into the history of this setting more for the 1.28 release.

https://github.com/Microsoft/vscode/blob/bfbb4835708b6a98bf6016682ec6347820671c54/src/vs/workbench/parts/terminal/electron-browser/terminalProcessManager.ts#L118-L120

https://github.com/Microsoft/vscode/blob/bfbb4835708b6a98bf6016682ec6347820671c54/src/vs/workbench/parts/terminal/node/terminalEnvironment.ts#L85-L89

https://github.com/Microsoft/vscode/blob/bfbb4835708b6a98bf6016682ec6347820671c54/src/vs/workbench/parts/terminal/node/terminalEnvironment.ts#L100-L106

**Comment by Tyriar** [comment]
I'm going to leave the behavior as is for non-Windows, for Windows `$LANG` will no longer be set unless the setting is true (this could be useful for WSL).

**Comment by Tyriar** [comment]
We should not set LANG in cmd or powershell, we need it in git bash definitely and maybe wsl.

**Comment by Tyriar** [comment]
The setting has been improved in the upcoming version, see `detectLocale` in the upcoming release notes.
