### ISSUE TITLE
[BUG]version 1.27 can't open file!

### ISSUE THREAD

**Issue by WilliamHuge** [Microsoft/vscode#58026]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.I singing a song and coding my code, suddenly, vs code alert the msg what It is updating.The result  that is not work. 
![image](https://user-images.githubusercontent.com/40257445/45131313-f3622c00-b1be-11e8-96f1-c54e433df6f4.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Duplicate of #58020

**Comment by GreenHand-Ben** [comment]
I am the same question. Are you ready now?
