### ISSUE TITLE
Breadcrumbs positioned incorrectly when horizontally split

### ISSUE THREAD

**Issue by nealot** [Microsoft/vscode#58027]
Steps to reproduce:
1. split window horizontally
2. make sure there isn't enough room to fit the menu below the **bottom** editor
3. open breadcrumbs on the **bottom** editor

Screenshot:

![screenshot_20180905_223918](https://user-images.githubusercontent.com/36805289/45131799-8a49cc80-b15c-11e8-90fd-ce12450f7972.png)

**Comment by jrieken** [comment]
Cannot reproduce that...

<img width="436" alt="screen shot 2018-09-06 at 09 53 58" src="https://user-images.githubusercontent.com/1794099/45143177-cd3a8d00-b1ba-11e8-85f8-f0ed9729dd6e.png">

**Comment by nealot** [comment]
Did you check the bottom editor? The top one works fine.

**Comment by jrieken** [comment]
@nealot thanks for clarifying...

**Comment by jrieken** [comment]
this is related to #57437

**Comment by jrieken** [comment]
@nealot Keeping this since there are still ways in which this might look bad. I will add logic to render the arrow at the bottom when nothing else is possible
