### ISSUE TITLE
Opening multiple files simultaneously with line/col options only applies to last file 

### ISSUE THREAD

**Issue by johnnytemp** [microsoft/vscode#58023]
- VSCode Version: 1.26.1
- OS Version: macOS

I'm one contributor of the extension "Open file" (by Frank Stuetzer).
The plug in allow open multiple files by selecting multiple lines like:

    file1:line:column
    file2:line:column

However, only the last opened file jump to the right position.  It's using core option (showTextDocument's options.selection) so the bug is in vscode side. (Better fix this also for other tools' future use)

Steps to Reproduce:

1. Install extension (by Frank Stuetzer)
2. Paste the above lines with real existent files (and line & column numbers), and select two lines.
3. Press Alt+P to jump to both files.
4. Only one currently focused file has the right text-cursor position.

Does this issue occur when all extensions are disabled?: Yes

**Comment by johnnytemp** [comment]
This seems extremely easy to fix, just comment the line in src\vs\workbench\api\node\extHostTextEditors.ts:84 (of commit 0b8e20847a7730235a449b0150c0b19613cb1636):

    throw new Error(`Failed to show text document ${document.uri.toString()}, should show in editor #${id}`);

Could anyone help to fix?  I'm not sure if appropriate to just comment it without some log...

**Comment by johnnytemp** [comment]
This seems easier to happen on fewer RAM and slower PC.  Originally, the problem was experienced on Windows 10 32-bit 2GB RAM.

I have tested on Windows 10 64-bit, with 8GB RAM, and open 110 files.  The first 19 files have the position not jumped, while the others can jump correctly.

I have used this command in a project to get the file paths to open:

    grep --include='*.php' -rIPn -m 1 -w if | code -

And then "Select All" in the new file, right-click and trigger "Open file under cursor" from the "Open file" plug-in.

Thanks.

**Comment by alexandrudima** [comment]
This ends up calling `IEditorService.openEditor`

https://github.com/Microsoft/vscode/blob/798549bff79b9c81f70056d7c78c62dd3f89d4f5/src/vs/workbench/api/electron-browser/mainThreadEditors.ts#L118:L139

**Comment by johnnytemp** [comment]
When could this be fixed? I cannot open a bunch of files at the desired lines from a grep-like search result. Must I always do such file-line selection one-by-one (that slow)?

P.S.
- Recent VSCode version - 1.41.1 - do even poorer job, because it can really only line-jump for the last file. Before, multiple files can be line-jumped simultaneously , but only a few files failed, when there are about 30 files.
- In some cases, I want to search with a grep-like command-line tool, because VSCode is not always suitable for files searching.

**Comment by johnnytemp** [comment]
I also found that `code --goto file1:line1 file2:line2` OR `code --goto index.php:2 --goto htaccess.txt:2` not work (it does nothing for both cases)

**Comment by johnnytemp** [comment]
>     * Recent VSCode version - 1.41.1 - do even poorer job, because it can really only line-jump for the last file. Before, multiple files can be line-jumped simultaneously, but only a few files failed, when there are about 30 files.
> 

I found that it "can only line-jump for the last file" when all the target files are already opened in VSCode. If all are not opened already, maybe only some files failed to line-jump. Thus, this may not be related to recent VSCode change.

**Comment by johnnytemp** [comment]
In summary, this issue is related to robustness of the following VSCode's API calls, when it is called multiple times with different files (to position to line 10 for example):

let range = iDoc.lineAt(10).range; // highlight line 10
let showOptions = { selection: new vscode.Selection(range.start, range.end) };
`vscode.window.showTextDocument(iDoc, showOptions)`

In such cases, the selection is sometimes not positioned. We could say the API is unreliable/broken unless it's only handling one file in an action. This affect any API development when multiple files cursor positioning is needed.

I think such use case is useful (e.g. by open all results from a special search tools at once).

Could you give a good reason why close this issue?

**Comment by Friksel** [comment]
Just had the same issue today without using any extension; just using the VS Code command line commands. According to the online manual it should work, but it isn't working, so I'm very surprised this one is closed instead of solving, as it's clearly a bug.

+1 to make this work!
