### ISSUE TITLE
vs code1.27版本打开之后为什么只有菜单栏显示，别的都不显示了，并且菜单栏里面的功能

### ISSUE THREAD

**Issue by GreenHand-Ben** [Microsoft/vscode#58029]
![image](https://user-images.githubusercontent.com/42233756/45132328-14c51700-b1c3-11e8-8b2c-6a0d851aeb57.png)

**Comment by GreenHand-Ben** [comment]
菜单栏里面的功能也失效，是我安装出错了么？安装了好多次了，下载1.26版本就可以，然后一更新就又这样了

**Comment by shaohong1987** [comment]
我的也是,打开调试工具,发现有脚本错误

**Comment by GreenHand-Ben** [comment]
我打开调试工具也出错，估计是原本的扩展插件导致的吧，我准备安装1.26把插件全部卸载在更新1.27试试

**Comment by mjbvz** [comment]
Duplicate of #57982
