### ISSUE TITLE
August Recovery Endgame

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#58032]
- [x] Bump up the version in package.json @bpasero 
- [x] Build stable for all platforms @bpasero
- [x] Verify all issues in [Recovery Milestone](https://github.com/Microsoft/vscode/milestone/77) **team**
- [x] Make rpm signing request @Tyriar 
- [x] Sanity check of installable bits
  - [x] Windows 64
    - [x] signed installer  
    - [x] user installer  
    - [x] zip 
  - [x] Windows 32  
    - [x] signed installer  
    - [x] user installer  
    - [x] zip 
  - [x] OS X  
  - [x] Linux
    - [x] deb package 64-bit  
    - [x] deb package 32-bit  
    - [x] rpm package 64-bit  
    - [x] rpm package 32-bit  
    - [x] archive 64-bit  
    - [x] archive 32-bit 
- [x] Update release notes with milestone link @bpasero  
- [x] Add a git tag to `HEAD` of `release/<x.y>` in format `x.y.z` @bpasero 
- [x] Publish website **@bpasero**
- [x] Publish to stable @bpasero 
- [x] Publish deb and rpms to repositories manually @chrmarti

**Comment by ddotlic** [comment]
@bpasero Didn't want to pollute with yet another silly issue, so FYI here: on a macOS (fully updated), neither my "regular" nor insider 'see' the newly released August update. Updates have been coming in regularly before for years.

**Comment by bpasero** [comment]
@ddotlic we temporarily stopped the update due to https://github.com/Microsoft/vscode/issues/47883

**Comment by ddotlic** [comment]
@bpasero Ah, seems like a very sensible thing to do 😉 , thanks! I was slightly confused (and more people are probably going to as well) because I've seen the tweet and release notes are up on the VS Code web site (maybe put a message there to avoid confusion)?

**Comment by bpasero** [comment]
Yeah we can do that.

**Comment by mapl** [comment]
is it feasible to provide some extra status information after manually hitting "check for updates..."?
Something like "Automtatic Updates has been temporarily disabled due to issue #xxxxxx..."

I searched for local network releated proxy issues first and then disovered this issue :)

**Comment by bpasero** [comment]
Website is updated btw.

**Comment by ddotlic** [comment]
> Website is updated btw.

Great, I can also confirm that my insider has just been updated (am on a macOS so the fix should not concern me but good to know that insider updates are back).

**Comment by bpasero** [comment]
Yes, unfortunately we cannot stop the update per OS (see https://github.com/Microsoft/vscode/issues/58043). Latest insiders on all platforms is 1.27.1 to test the fix.

**Comment by bpasero** [comment]
Released.
