### ISSUE TITLE
Wrong debugging in Python after update

### ISSUE THREAD

**Issue by vpalex999** [Microsoft/vscode#58033]
Issue Type: <b>Bug</b>

File "d:\env\lib\site-packages\_pytest\debugging.py", line 67, in fin
    sys.breakpointhook = sys.__breakpointhook__
AttributeError: module 'sys' has no attribute '__breakpointhook__'

VS Code version: Code 1.27.0 (7b9afc4196bda60b0facdf62cfc02815509b23d6, 2018-09-05T05:29:44.670Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (9.12GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe --folder-uri file:///d%3A/VV/Automation_order_268|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
Bookmarks|ale|9.0.3
flask-snippets|cst|0.1.0
vscode-eslint|dba|1.5.0
jquerysnippets|don|0.0.1
knockoutjs|fur|0.1.0
gc-excelviewer|Gra|2.1.26
Python-autopep8|him|1.0.2
reg|ion|0.0.2
easy-icons|jam|0.3.1
gitlab-mr|jas|1.3.0
restructuredtext|lex|74.0.0
vscode-language-pack-ru|MS-|1.27.2
python|ms-|2018.8.0
debugger-for-chrome|msj|4.9.1
vscode-docker|Pet|0.1.0
vscode-css-peek|pra|2.1.0
todotasks|san|0.5.0
jenkinsfile-support|sec|0.1.0
vscode-djaneiro|the|1.4.2
pdf|tom|0.3.0
bootstrap-3-snippets|wcw|0.1.0

(15 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Please file this against the python extension
