### ISSUE TITLE
debug - no truncation?

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#5803]
#4952

* test plan says truncation happens at strings longer 10000 characters
* have code like this
```
        let longString = new Array(10001).join('oooooo');
        longString += '<TOO LARGE>';
        console.log(longString);
```
* ⚡ console doesn't truncate the string, shows `<TOO LARGE>`

![screen shot 2016-04-26 at 11 30 10](https://cloud.githubusercontent.com/assets/1794099/14813557/84c81738-0ba2-11e6-937f-202c9eb374d6.png)

**Comment by jrieken** [comment]
maybe related to #5802

**Comment by bpasero** [comment]
@jrieken assigning back to you to retest this scenario with a newer Alpha build that includes our node-debug fix to actually enable debug injection for Electron.

**Comment by jrieken** [comment]
works with latest chances
