### ISSUE TITLE
Will Visual Studio Code ever support the Acrylic material in the custom title bar?

### ISSUE THREAD

**Issue by infinnie** [microsoft/vscode#58034]
The Acrylic material is a brush that is part of the Fluent Design language, which I think could make the UI more intuitive and natural. I wonder whether it would ever be supported here.

**Comment by A55imilat0r** [comment]
Oh hell yes and please add to this a full fluent design theme with pure black background

**Comment by DRSDavidSoft** [comment]
#52707.

**Comment by sbatten** [comment]
this will be closed for the same reasoning as the PR linked above
