### ISSUE TITLE
Wrong highlighting in launch.json

### ISSUE THREAD

**Issue by burner1024** [Microsoft/vscode#58031]
- VSCode Version: 1.27.0
- OS Version: Ubuntu 18.04

Steps to Reproduce:
1. Open [launch.json](https://github.com/Microsoft/vscode-extension-samples/blob/master/lsp-sample/.vscode/launch.json) in VSCode
2. Highlighting is off:
![captura de pantalla de 2018-09-06 12-20-00](https://user-images.githubusercontent.com/1279852/45136720-a76bb300-b1cf-11e8-9a96-f9c253101819.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by burner1024** [comment]
right

**Comment by mjbvz** [comment]
That's by design. We de-emphisie the parts of the launch json that normally aren't relevant

**Comment by burner1024** [comment]
Oh, I see. All right.
