### ISSUE TITLE
Terminal Window error navigation

### ISSUE THREAD

**Issue by DmitryKurkin** [Microsoft/vscode#58041]
Issue Type: <b>Feature Request</b>

Looks like the feature is broken again.

I cannot navigate using the mouse from the terminal window to the actual place where the error occured

VS Code version: Code 1.27.0 (7b9afc4196bda60b0facdf62cfc02815509b23d6, 2018-09-05T05:29:44.670Z)
OS version: Windows_NT x64 10.0.16299

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/58256
