### ISSUE TITLE
Better represent long file names in quick open

### ISSUE THREAD

**Issue by bm-stschneider** [microsoft/vscode#58040]
Issue Type: <b>Feature Request</b>

I work in a deeply nested folder structure so that using quick open is a bit of a hassle because it cuts of the path name right before I can make out in what folder is the file I was trying to open.
The files are generally named the same but are in different folders.
Would it be maybe possible to have the quick open floating on top of the editor so it can have a variable width for example?

VS Code version: Code - Insiders 1.27.0-insider (7b9afc4196bda60b0facdf62cfc02815509b23d6, 2018-09-03T09:07:33.052Z)
OS version: Darwin x64 17.7.0

**Comment by bpasero** [comment]
@bm-stschneider you want the quick open widget to be wider, is that it?

**Comment by bm-stschneider** [comment]
or have it floating in the middle of the screen or something. I don't know how static the position is currently.
