### ISSUE TITLE
Ctrl+C does not stop the process in external terminal on Windows

### ISSUE THREAD

**Issue by oliverjanik** [Microsoft/vscode#58047]
- VSCode Version: 1.27.0
- OS Version: Win 10

Steps to Reproduce:

1. Press Ctrl+Shift+C
2. External terminal opens (CMD)
3. Run any longer process (serve)
4. Press Ctrl+C,
5. The process does **not** stop

Does this issue occur when all extensions are disabled?: Yes

This has been a problem on/off for the longest time and a major frustration. I searched for duplicates but they're all closed:
- #20798
- #25195

Please note  there is another ongoing effort for integrated terminal:
- #9347

That might or might not be related.

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693

**Comment by oliverjanik** [comment]
Hmm this issue is about the external terminal yet "integrated-terminal" tag got attached....

Also is the winpty issue about integrated terminal or external terminal? It also has "integrated-terminal" tag.

**Comment by oliverjanik** [comment]
How so? This is the only program that has this problem as far as I know.

Can you please point to a specific issue?

Otherwise reopen please.

As I said this issue comes up: #20798. #25195 and always gets closed falsely.

*note*: It's very frustrating to have bug reports misread and dismissed so quickly with no discussion.

**Comment by Tyriar** [comment]
FYI @bitcrazed
