### ISSUE TITLE
acceptSuggestionOnCommitCharacter

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#58048]
- VSCode Version: 1.27.0
- OS Version: macOS

**`this`, `super`, `console` isn't finished after pressing `.`**

![this_super_console](https://user-images.githubusercontent.com/10441177/45143551-45598080-b1c4-11e8-989a-75f6134f83ba.gif)

The issue was also with 1.26.1 version.

**Comment by svipben** [comment]
@mjbvz As I know you know how this setting works. I really like it and I'm trying to use it as much as possible instead of Tab or Enter cuz' it will reduce some typing, but it kinda annoying when it doesn't work in such cases...

**Comment by mjbvz** [comment]
Second part (from comment) is upstream issue https://github.com/Microsoft/TypeScript/issues/25691

**Comment by svipben** [comment]
You're my hero! 😄
