### ISSUE TITLE
vscode steals focus when opening a new window

### ISSUE THREAD

**Issue by johannes-z** [Microsoft/vscode#58049]
- VSCode Version: 1.26.1
- OS Version: Windows 10 Pro Build 1803

Steps to Reproduce:

1. Open vscode
2. Immediatly click on "More" under `Recent` (Folders)
3. The search will popup, while vscode is loading/restoring the UI, it will steal focus or restore the window, closing the popup.

Does this issue occur when all extensions are disabled?: No

**Comment by bpasero** [comment]
@johannes-z are you using the custom title style with custom menus?

**Comment by johannes-z** [comment]
@bpasero Yes I am!

**Comment by johannes-z** [comment]
@sbatten yes! it doesn't matter what you open. E.g. the terminal also loses focus a few seconds after opening vs code. 
I tried both custom and native menus, it happens with both of thrm.

**Comment by sbatten** [comment]
@bpasero doesn't appear to be specific to new menus. 

@johannes-z I notice this was reported on 1.26.1, does it also repro on 1.27.1?

**Comment by bpasero** [comment]
Closing as designed. As a workaround you can configure `workbench.quickOpen.closeOnFocusLost: false`

**Comment by johannes-z** [comment]
@bpasero @sbatten As designed? Stealing focus is **never** good UX. Even if there is an option to disable `closeOnFocusLost`, e.g. writing in a terminal still steals focus. in the `quickOpen`
