### ISSUE TITLE
gulp editor-distro fails

### ISSUE THREAD

**Issue by akosyakov** [Microsoft/vscode#58051]
```
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^
{"errorCode":"load","moduleId":"vs/css","neededBy":["===anonymous2==="],"detail":{"errno":-2,"code":"ENOENT","syscall":"open","path":"out-build/vs/css.build.js"}}
```

What am I missing?

**Comment by akosyakov** [comment]
`gulp compile-client-build --max_old_space_size=4095` did the trick

**Comment by paulyoung** [comment]
Could this be re-opened? I think it's at least a documentation issue since it's not mentioned in https://github.com/Microsoft/monaco-editor/blob/master/CONTRIBUTING.md#shipping-a-new-monaco-editor-npm-module

**Comment by paulyoung** [comment]
I also had to change `shakeLevel`.
