### ISSUE TITLE
debugger for chrome throws this bug

### ISSUE THREAD

**Issue by Zebzhong** [Microsoft/vscode#58053]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.enter F5, start debug ,throws error

![image](https://user-images.githubusercontent.com/29706072/45148201-4eb11000-b1f9-11e8-9fa8-276e6eff069a.png)

2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by weinand** [comment]
How does your launch config look like?

**Comment by roblourens** [comment]
What runtime or version of Chrome?

That's not required so I'll handle the error...

**Comment by roblourens** [comment]
Please update the chrome-debug extension and let me know if that doesn't fix it
