### ISSUE TITLE
Performance report 

### ISSUE THREAD

**Issue by hardeyem** [Microsoft/vscode#58055]
Issue Type: <b>Performance Issue</b>

VS Code has been using more CPU resources lately constantly. Kindly look into this issue 

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.92GB (1.76GB free)|
|Process Argv|C:\Users\DELL\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	    80	  9300	code main
    1	    70	  2860	   window (Issue Reporter)
    0	   779	  8208	   window (requests.js - kbtripservice - Visual Studio Code)
    0	   308	  9580	     extensionHost
    0	     9	  6880	       electron_node eslintServer.js 
    0	     2	  8136	       electron_node server.js 
    0	     8	  9796	       electron_node jsonServerMain.js 
    0	    26	 11736	       electron_node electronForkStart.js tsserver.js 
    0	     4	 12640	         electron_node typingsInstaller.js tsserver.js typesMap.js 
    0	   190	 12828	       electron_node language-server-stdio.js 
    0	     6	 14300	       electron_node tslintServer.js 
    0	     8	 15444	       searchService
    0	     7	 11684	     watcherService 
    0	     4	 16288	       console-window-host (Windows internal process)
    0	     5	 17288	     searchService
    0	     3	 11536	   C:\Users\DELL\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-stable-7b9afc4196bda60b0facdf62cfc02815509b23d6.exe /verysilent /update="C:\Users\DELL\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-stable-7b9afc4196bda60b0facdf62cfc02815509b23d6.flag" /nocloseapplications /mergetasks=runcode,!desktopicon,!quicklaunchicon
    0	     7	 12444	     "C:\Users\DELL\AppData\Local\Temp\is-QNGMN.tmp\CodeSetup-stable-7b9afc4196bda60b0facdf62cfc02815509b23d6.tmp" /SL5="$A0C52,44597149,159232,C:\Users\DELL\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-stable-7b9afc4196bda60b0facdf62cfc02815509b23d6.exe" /verysilent /update="C:\Users\DELL\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-stable-7b9afc4196bda60b0facdf62cfc02815509b23d6.flag" /nocloseapplications /mergetasks=runcode,!desktopicon,!quicklaunchicon
    2	    70	 13600	   gpu-process
    0	    27	 14140	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (requests.js - kbtripservice - Visual Studio Code)
|    Folder (kbtripservice): 25 files
|      File types: js(16) json(3) hbs(3) babelrc(1) css(1)
|      Conf files: package.json(1) gulp.js(1);
```

</details>
<details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
aessoft-class-autocomplete|AES|0.1.0
ng-template|Ang|0.1.10
code-gnu-global|aus|0.2.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
dart-code|Dar|2.18.0
flutter|Dar|2.18.0
vscode-eslint|dba|1.5.0
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.38
vscode-npm-script|eg2|0.3.5
php-debug|fel|1.12.5
php-intellisense|fel|2.3.5
php-pack|fel|1.0.2
local-history|gay|0.0.3
githd|hui|1.2.1
rest-client|hum|0.19.1
crane|Hvy|0.3.8
node-module-intellisense|jhe|1.6.0
intellij-idea-keybindings|k--|0.2.25
node-module-intellisense|lei|1.5.0
code-beautifier|mic|2.1.0
vscode-scss|mrm|0.6.2
python|ms-|2018.7.1
cpptools|ms-|0.18.1
csharp|ms-|1.15.2
team|ms-|1.136.0
debugger-for-chrome|msj|4.9.1
vscode-docker|Pet|0.1.0
angular-cli|pko|1.0.1
java|red|0.30.0
php-ci|sma|0.2.10
javascript-typescript|sou|0.0.7
html-preview-vscode|tht|0.1.1
html-css-class-completion|Zig|1.17.1

</details>

**Comment by jrieken** [comment]
There is no CPU utilisation shown... @hardeyem sure its vscode? can you run code --status when it busy
