### ISSUE TITLE
Add new function

### ISSUE THREAD

**Issue by SXXhh** [Microsoft/vscode#58056]
Issue Type: <b>Feature Request</b>

可以添加一个账号登录功能可以同步，账号内的所有配置：比如：皮肤、插件等

VS Code version: Code 1.27.0 (7b9afc4196bda60b0facdf62cfc02815509b23d6, 2018-09-05T05:29:44.670Z)
OS version: Windows_NT x64 6.1.7601

**Comment by mjbvz** [comment]
Duplicate of #2743
