### ISSUE TITLE
ux - merge debug output into output

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#5805]
we have _Debug Output_ and _Output_. The latter isn't output but a container for output channels like _Task_, _Git_, etc. It's actually configurable. So, my question is why doesn't debug fit into this and needs it own container? On the downside there is clear more view management with todays implementation as it makes me switch between debug output and output>something.

**Comment by jrieken** [comment]
fyi @stevencl @isidorn

**Comment by isidorn** [comment]
Nobody really picked up on this. Closing as will not do it.
