### ISSUE TITLE
Windows7 : unable to update

### ISSUE THREAD

**Issue by Guema** [Microsoft/vscode#58058]
- VSCode Version: 1.26.1
- OS Version: Windows 7 x64

Steps to Reproduce:

1. gear/help > click Check for update
bug :
![image](https://user-images.githubusercontent.com/8943532/45149409-c0716580-b1c9-11e8-9b36-4e93d3125288.png)

Other way :

1. Go on https://code.visualstudio.com/
2. Click "download for windows"
> this is 1.26.1
3. Install
bug : does not update to latest version.

$ Tried to wait until vscode search by itself.
$ Tried without extensions.
$ Tried waiting some minutes to let vscode establish connexion with server, and then retrying.

> No result.

- The official website also only offers me the 1.26.1 even if it 1.27 is spotlighted
- I had to go on update's page to download 1.27
- 1.27 is working fine on win7.
- i did not see any "we end windows 7 support"-like paragraph in changelog
- I was able to update my personal Win10 without any problem

Does this issue occur when all extensions are disabled?: Yes

note: this is the default "user version".

**Comment by Guema** [comment]
Just noticed the message about non-ASCII characters.
so it is unrelated, my bad.

**Comment by bardware** [comment]
I was looking for the update also to install it on my work pc in the company after I got it yesterday on a private notebook.
It would be nice if it read somewhere the update was revoked because of these issues:
https://github.com/Microsoft/vscode/issues/58044
https://github.com/Microsoft/vscode/issues/58060

**Comment by bardware** [comment]
`1.27.1` is available (got it as auto update)
