### ISSUE TITLE
Editor is not focused when selecting a file from Open Editors panel

### ISSUE THREAD

**Issue by myandrienko** [Microsoft/vscode#58062]
Issue Type: <b>Bug</b>

1. Open two files
2. Switch from one of the files to another using Open Editors panels

Expected behavior: editor is focused after the file is selected.
Actual behavior: focus remains in sidebar.

Since Open Editors panel is used as an alternative to tabs for switching between opened files, it should behave the same way and focus the editor immediately after a file is selected.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:34:20.517Z)
OS version: Linux x64 4.13.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3768)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 0|
|Memory (System)|7.69GB (0.49GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by bpasero** [comment]
Closing as designed, we never move focus out of a list/tree when clicking, otherwise you could not give that widget focus and use keyboard to navigate.

**Comment by myandrienko** [comment]
Thanks @bpasero, I understand that decision. However I feel like it makes vscode a little less usable without tabs, since a user basically loses his cursor position within a file every time he switches files. Possibly there's room for improvement there.

**Comment by bpasero** [comment]
You can double-click to move focus into the editor if that helps.
