### ISSUE TITLE
Sort results in "Go to file" by how close they are to the working file (usability)

### ISSUE THREAD

**Issue by janmarek** [microsoft/vscode#5806]
Sometimes I have files with the same name in different folders. When I work on something and want to open a file I prefer the file in the same folder to appear first in the list. Now it's sorted (probably) alphabetically.

When working on file `foo/something.js` and searching for "lorem", the list in Go to file should look like:
- foo/lorem.js
- bar/lorem.js

When working on file `bar/something.js` and searching for "lorem" it should be the other way round:
- bar/lorem.js
- foo/lorem.js

**Comment by Nowaker** [comment]
Trying to open `index.html` in root and it's almost impossible.

![image](https://user-images.githubusercontent.com/611746/65364258-46463000-dbd6-11e9-8bc3-7e8b22fd61f4.png)
