### ISSUE TITLE
Update results in removal of all Marketplace extensions

### ISSUE THREAD

**Issue by BravoAlpha59** [Microsoft/vscode#58066]
We have written the needed data into your clipboard because it was too larg
Issue Type: <b>Bug</b>

The installation of the last two rounds of Code updates (1.26 & 1.27) resulted in having no Marketplace extensions installed. For example, I am nearly an exclusively Python & QT developer and have been using ms-python.python since it has been available. Installing the Code updates results in no extensions. Additionally, any workspace or user settings I have made associated with these extensions have to be recreated.

VS Code version: Code 1.27.0 (7b9afc4196bda60b0facdf62cfc02815509b23d6, 2018-09-05T05:29:44.670Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (1.29GB free)|
|Process Argv|D:\VSCode\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.5.0
gitlens|eam|8.5.6
file-icons|fil|1.0.16
code-runner|for|0.9.4
beautify|Hoo|1.4.2
python|ms-|2018.8.0
pyside2-vsc|Oll|0.1.0
pyqt-integration|zho|0.2.0

(1 theme extensions excluded)

</details>
e to send. Please paste.

**Comment by joaomoreno** [comment]
> Installing the Code updates results in no extensions. 

Updates to Code should not touch your extensions at all. Do you use Portable mode at all?
