### ISSUE TITLE
breadcrumb.background does not work with tabs turned off

### ISSUE THREAD

**Issue by obambrough** [Microsoft/vscode#58067]
Issue Type: <b>Bug</b>

The breadcrumb background is the wrong color

![vs code no header breadcrumb problem](https://user-images.githubusercontent.com/1922249/45153657-cacc3900-b1a2-11e8-9026-6fe16e2af772.png)

### Steps to reproduce

Modify VS Code's settings to disable tabs and set the header background to a custom color. Also set the breadcrumb background color to match.
```
   "workbench.editor.showTabs": false,
   "workbench.colorCustomizations": {
      "editorGroupHeader.noTabsBackground": "#5d4d7a",
      "breadcrumb.background": "#5d4d7a",
   },
   "breadcrumbs.enabled": true,
```

### Expected Results

The breadcrumb background color will match the noTabsBackground color.

### Actual Results

The breadcrumb background is black, not the defined color.

NOTE: All other breadcrumb settings do take effect, such as breadcrumb.foreground and breadcrumbPicker.background.

### System Info
VS Code version: Code 1.27.0 (7b9afc4196bda60b0facdf62cfc02815509b23d6, 2018-09-05T05:22:06.672Z)
OS version: Darwin x64 17.7.0

I verified the issue is still present in insiders build 1.27.1-insiders (5944e81f3c46a3938a82c701f96d7a59b074cfdc)

**Comment by jrieken** [comment]
It's on purpose that we ignore it then because we want it to have the color of the title. Tho it seems that it falls back to editor background, not the title background

**Comment by jrieken** [comment]
the background color will now be transparent when using no tabs
