### ISSUE TITLE
File header remains in preview mode after double-clicking the file in sidebar

### ISSUE THREAD

**Issue by myandrienko** [Microsoft/vscode#58064]
Issue Type: <b>Bug</b>

1. Set `workbench.editor.showTabs` to `false`
2. Open any project
3. Double click any file in Explorer

Expected behavior: file header should be in regular font, since opening a file with double click disables preview mode.
Actual behavior: file header is still in italics, as if the file was still in preview mode. (However file name in Open Editors panel is not in italics.)

![screenshot from 2018-09-06 13-39-05](https://user-images.githubusercontent.com/975978/45152989-3df1a180-b1db-11e8-9845-8b757443cf7a.png)

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:34:20.517Z)
OS version: Linux x64 4.13.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3528)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.69GB (0.37GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by bpasero** [comment]
Good catch.
