### ISSUE TITLE
Extremely slow start on standard account

### ISSUE THREAD

**Issue by shedding-reptile** [Microsoft/vscode#58068]
When using the regular standard account (Active Directory user), Visual Studio Code takes a very long time to start.
When running as admin, it starts in a few seconds.

**Comment by jrieken** [comment]
@shedding-reptile Can you follow this guide and report back with some results: https://github.com/Microsoft/vscode/wiki/Performance-Issues#visual-studio-code-starts-up-slowly. Thanks

**Comment by shedding-reptile** [comment]
[CPU-20180906T112334.cpuprofile.txt](https://github.com/Microsoft/vscode/files/2357654/CPU-20180906T112334.cpuprofile.txt)

**Comment by shedding-reptile** [comment]
I generated a profile using the JavaScript Profiler.
By running  code --prof-startup I couldn't locate any profiler file. I'm
not sure what "home-directory" should be on Windows. I tried %USERPROFILE%
but there are no files there.

**Comment by jrieken** [comment]
Thanks. Calling spawn (to start another process) seems to take forever here. That's often caused by AV software

<img width="741" alt="screen shot 2018-09-06 at 17 33 47" src="https://user-images.githubusercontent.com/1794099/45168225-08f54700-b1fb-11e8-9a9c-2a159b33d263.png">
