### ISSUE TITLE
when you define one struct new type without name, the ouline display _unnamed_struct_1afa_1 info.

### ISSUE THREAD

**Issue by hawkinchina** [Microsoft/vscode#58061]
Issue Type: <b>Bug</b>

when you define one struct new type without name, just like typedef struct  { ...  } MyNewBufferContext.   the ouline display _unnamed_struct_1afa_1 and its field variables and MyNewBufferContext both.  is it ok?   or  just only display MyNewBufferContext and its field variables. 

VS Code version: Code 1.27.0 (7b9afc4196bda60b0facdf62cfc02815509b23d6, 2018-09-05T05:22:06.672Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1796)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|8.00GB (0.29GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|1.2.8
comments|Ale|1.0.4
doxdocgen|csc|0.3.3
c-cpp-project-generator|dan|1.1.1
php-debug|fel|1.12.5
php-intellisense|fel|2.3.5
php-pack|fel|1.0.2
code-runner|for|0.9.4
HdsCppSnippets|hua|0.0.1
vscode-fileheader|mik|0.0.2
vscode-clang|mit|0.2.2
vscode-language-pack-zh-hans|MS-|1.27.2
cpptools|ms-|0.18.1
vscode-docker|Pet|0.1.0
vscode-icons|rob|7.25.0
code-settings-sync|Sha|3.1.2
comment-snippets|Tob|0.2.0
code-navigation|vik|0.2.0
vim|vsc|0.16.3
debug|web|0.22.0

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Please file this issue against the c++ extension

**Comment by hawkinchina** [comment]
OK, thanks, I will report this issue against vscode-cpptools extension of Microsoft.
