### ISSUE TITLE
"Ctrl+,"  keybinding to open settings.json 

### ISSUE THREAD

**Issue by goodday2you** [Microsoft/vscode#58063]
Can't edit keybindings.json to bind "ctrl+," to open settings.json.

Don't have much use for new settings interface. I want to use the old shotcut which is "Ctrl+," to open
settings.json and not the new settings interface.

And yes I know that I can open settings.json by clicking, but I want to use the same old shortcut to
open settings.json.

Something like this in keybindings.json:
  {
    "key": "ctrl+,",
    "open": "~/.config/Code/User/settings.json",
  },

P.S. New settings interface looks like the one in Atom, and that is one of the resons I never used that
editor.

**Comment by Anheurystics** [comment]
Can't you just set "workbench.settings.editor" to "json"?
