### ISSUE TITLE
Can't run single method or class unit test using PyTest in editor

### ISSUE THREAD

**Issue by imortkz** [Microsoft/vscode#58070]
Issue Type: <b>Bug</b>

No more `run test` & `debug test` in the editor.
Only can run unit tests using the command prompt.
Tests discovery won't help.

VS Code version: Code - Insiders 1.27.1-insider (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T07:41:14.241Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz (8 x 2694)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (5.96GB free)|
|Process Argv|C:\Users\Валентин Ким\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
routeros-syntax|cpe|1.0.0
vscode-eslint|dba|1.5.0
githistory|don|0.4.2
gitlens|eam|8.5.6
php-debug|fel|1.12.5
php-intellisense|fel|2.3.5
php-pack|fel|1.0.2
shell-format|fox|1.1.3
githd|hui|1.2.1
python|ms-|2018.8.0
Go|ms-|0.6.89
PowerShell|ms-|1.8.4
debugger-for-chrome|msj|4.9.1
monitor-file|rko|1.0.1
git-add-remote|sam|0.0.2

</details>

**Comment by imortkz** [comment]
Yep, it was Git Lens which causing this. Thank you.

**Comment by mungojam** [comment]
@Dr-Nutter
