### ISSUE TITLE
editor find history

### ISSUE THREAD

**Issue by jaydeep1958** [Microsoft/vscode#58077]
When we search for  a particular string in editor , the search works fine . However , if we need to search for text for which the searches were done  earlier , we need to re-enter the search string . A drop down of selection of previous searches would be help full 
![findfeatue](https://user-images.githubusercontent.com/36105211/45163428-0ea85800-b20e-11e8-9b65-243b4c6ff13a.PNG)

**Comment by roblourens** [comment]
You can use the up/down arrow keys to see the history
