### ISSUE TITLE
Debug threads need more UI affordances

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#5807]
Testing #5644

The list is too empty. At first glance, it's even not so trivial to understand that I'm looking at threads.

![image](https://cloud.githubusercontent.com/assets/22350/14813949/63205b84-0ba4-11e6-93e5-21e5b7e15489.png)

Idea: We could use some kind of label to the right of each thread. Use a default value of `Thread`. Let each debug adapter overwrite that value. The C# one could for example say `Main Thread`, `Worker Thread #1`, etc...

**Comment by isidorn** [comment]
I like this idea. For start, as Joao suggests, I would render 'Thread'.
@weinand should we add some more optional data to our [protocol](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L543) such that the adapter could specify what to render instead of the default 'Thread'

**Comment by isidorn** [comment]
@joaomoreno now next to each thread we show paused / running, that should help with this problem.
The issue with appending thread is that some debug adapter give nice names to threads already, like `Worker Thread 1`. 
Can you please try it with the new paused / running badge and let me know what you think?

![screen shot 2016-05-03 at 22 37 30](https://cloud.githubusercontent.com/assets/1926584/14997590/cc74ab04-117f-11e6-9ab1-3544a30e1a56.png)

**Comment by joaomoreno** [comment]
Just make sure it says `Thread` when I hover it...

**Comment by weinand** [comment]
@isidorn a debug adapter can already return any name for a thread (and mono-debug makes use of it by returning the name of the C# thread). So I don't think that we have to change the protocol here, but we should better document that the name returned from the adapter for a thread should make clear that it is a thread.
