### ISSUE TITLE
Excessive calls to the marketplace when rendering extensions viewlet

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#58074]
For every row render of the extensions viewlet, there's a marketplace request:

![bug](https://user-images.githubusercontent.com/22350/45160984-11de1c80-b1eb-11e8-84ec-b49ca00043a9.gif)

This was introduced by: https://github.com/Microsoft/vscode/commit/109f6b514ff15244c043bdbd61b4ca9f803ff627

@ramya-rao-a What is the goal here? Localizable descriptions?

cc @sandy081

**Comment by joaomoreno** [comment]
Yeah, I believe you can do a single request per page, asking for specific details of a collection of extensions.

**Comment by ramya-rao-a** [comment]
Re-opening the issue as we have to wait for all the language packs to be re-published using the latest vsce
