### ISSUE TITLE
Typing in not loaded `goToSymbol` not filtering symbols

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#58089]
It's happening on a slow laptop, not sure if it can be repro on a fast PC (probably still can be done in a larger workspace/file or if there's something heavy runs in background).

1. Open a file (>3k lines) with symbol provider (maybe open a big project first)
2. Quickly open `go to symbol in file`
3. Quickly type several first characters of the symbol you know this file has
4. The filtering is not done (probably file is still loading or the symbol provider) and there is no progress indication

If you type 1 more symbol or <kbd>backspace</kbd> the filtering will complete.

**Comment by bpasero** [comment]
Via https://github.com/Microsoft/vscode/commit/03e8f61f981b68f378018e972a4928014b9e38b2 there is now cancellation wired into goto symbol. Please verify from tomorrows insider build.

**Comment by usernamehw** [comment]
Looks fixed to me.
