### ISSUE TITLE
"http.proxy" setting no longer allows socks5 proxies

### ISSUE THREAD

**Issue by duanehutchins** [Microsoft/vscode#58080]
- VSCode Version: 1.27.1 (user setup)
- OS Version: Win 8.1

Steps to Reproduce:

1. Go into User Settings
2. Try setting http.proxy to `socks5://127.0.0.1:8080`
3. Error: `String does not match the pattern of "^https?://([^:]*(:[^@]*)?@)?([^:]+)(:\d+)?/?$|^$".`

SOCKS5 proxy was allowed in this setting since #9971. Please fix the regex verification to allow it again.

**Comment by joaomoreno** [comment]
SOCKS5 was never supported in the `http.proxy` setting. Read https://code.visualstudio.com/docs/setup/network for more details.
