### ISSUE TITLE
Allow to pass arguments to external terminal

### ISSUE THREAD

**Issue by FFY00** [Microsoft/vscode#58086]
It's pretty much what was said in the title. VS Code doesn't seem to allow us to invoke an external terminal with a set of arguments.

**Comment by Tyriar** [comment]
They are already being invoked with a set of arguments, I recommend creating an extension if you need to tweak this further.

**Comment by FFY00** [comment]
What kind of arguments? How does that work if every terminal has its own arguments? I'm not following.

**Comment by Tyriar** [comment]
@FFY00 these are the arguments passed on Windows for example:

https://github.com/Microsoft/vscode/blob/74b096b6be864f92cdeadae2304b7d872034669f/src/vs/workbench/parts/execution/electron-browser/terminalService.ts#L94-L96

**Comment by FFY00** [comment]
Do you understand what I am asking is to allow us to use custom arguments in **external** terminals, right? I don't know why the `integrated-terminal` label was added.

**Comment by Tyriar** [comment]
@FFY00 yes. There is no label for the external terminal as it's such a minor feature. The point I'm trying to get across is that it complicates things and is out of the scope of the feature. It can be easily accomplished with an extension though.

**Comment by FFY00** [comment]
Ok, even though I don't agree with "is out of the scope of the feature" I understand.

Thanks anyway.
