### ISSUE TITLE
Can't hit the breakpoint in the venv environment 

### ISSUE THREAD

**Issue by Reyshawn** [Microsoft/vscode#58085]
- VSCode Version: 1.27.1
- OS Version: macOS HighSierra 10.13.6

Steps to Reproduce:

1. `python3 -m venv test`
2. open the test folder and change the workspace settings `"python.pythonPath": "${workspaceFolder}/bin/python3"`
3. then try to write some python code, set a breakpoint, click the debug, a `runpy.py` file popped up and the program stops at line 85: `exec(code, run_globals)`, as the following image shows. 

 
<img width="1136" alt="screen shot 2018-09-06 at 23 54 21" src="https://user-images.githubusercontent.com/10696897/45169807-f39b0f80-b230-11e8-95ca-b5e58447676f.png">

Does this issue occur when all extensions are disabled?: Yes/No
When Python extension is disabled, it's not allowed to debug a python file. When all extensions except Python are disabled, this issue still occurs.

**Comment by mjbvz** [comment]
Please file this issue against the python extension
