### ISSUE TITLE
Commenting at the beginning of a folded line should comment all folded lines (and keep collapsed)

### ISSUE THREAD

**Issue by mattwelke** [microsoft/vscode#58081]
- VSCode Version: 1.27.0
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Collapse block of code by clicking on the - in the small box to the left of the top line of the block (ex. a function
2. Highlight the collapsed line of code
3. Press "ctrl-/" to comment every line selected

Does this issue occur when all extensions are disabled?: Yes

__________________________________________________

I'm not sure if this is a bug or intended design, but when I use the ctrl-/ feature to comment any code selected, every line in the collapsed block gets commented (which is great, very helpful) but then the block gets automatically expanded back to its original form. This can throw me off when my workflow involves highlighting a large block of code in the middle of a file and commenting it out. I would prefer it to stay collapsed when all of its inner lines are commented, so that I can continue working with the now commented out block collapsed. The way it is now, the commented block is also no longer collapsible.

**Comment by aeschli** [comment]
The current design is to expand whenever something gets modified inside the folder block.
Also, most likely, what you have commented out is no longer a folding range, so preserving in not so easy here.

**Comment by marconi** [comment]
@aeschli would it be possible to have a settings so we can opt-out not to expand commented collapsed code? Just like the way Atom handles commenting collapsed code.

**Comment by aeschli** [comment]
Can you explain more how that feature would work? As soon as you add comments, the folding ranges go away, unless you happen to have a new folding range for the comment.

**Comment by marconi** [comment]
@aeschli like this 

![t7qtfhwp4a](https://user-images.githubusercontent.com/49830/45324957-31c26700-b582-11e8-8a4d-88eb565458d8.gif)

**Comment by aeschli** [comment]
Ah, I now I understand, the comment feature is smart and always expands to the whole folding range. That's a nice idea.

**Comment by marconi** [comment]
Thanks, can't wait to see this. This always put me off vscode when refactoring a rather large file. 😄
