### ISSUE TITLE
Cannot enable proposed API via CLI

### ISSUE THREAD

**Issue by csvn** [Microsoft/vscode#58098]
- VSCode Version: 1.27.1-insider
- OS Version: Windows 10.0.17134

Steps to Reproduce:

1. Clone https://github.com/csvn/vscode-test-comment-proposal-api
2. Run debug by pressing F5
3. The extension will error (see below message)

```
Activating extension 'none.test-comment-proposal-api' failed: [none.test-comment-proposal-api]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api none.test-comment-proposal-api.
```

Does this issue occur when all extensions are disabled?: Yes

----------------------------------------------------------------

The top line in the debug console shows the command executed, which correctly has the string `--enable-proposed-api none.test-comment-proposal-api`:

```
C:\Users\<username>\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe --debugBrkPluginHost=27175 --debugId=4307de92-9443-4e43-9771-a7845c67c81b --enable-proposed-api none.test-comment-proposal-api --extensionDevelopmentPath=C:\Dev\test-comment-proposal-api 
```

I followed the steps in https://code.visualstudio.com/updates/v1_27#_proposed-extension-apis and tried to follow the error message's instructions. I also tried variations such as `--enable-proposed-api=<extension-id>`, but I have not found anything that works. I could not find any issues that relates to this either. Seems to me to either be a bug, or the error message is not entirely correct for how to run with proposed API's.

The repository above is a fresh `yo code` project based on Javascript, [with this commit](https://github.com/csvn/vscode-test-comment-proposal-api/commit/dd066936fcf207ecb0bdeb566fb471ba2ca58e4c) trying to add support for proposed API's.

**Comment by jrieken** [comment]
@csvn Can you attach the readings form the dev tools console?

**Comment by jrieken** [comment]
this might be the same as #55340

**Comment by jrieken** [comment]
This is actually a doc issue, it should be enableProposed*Api* not enableProposed*API*. I will follow up to make sure we update our release notes. cc @gregvanl

**Comment by jrieken** [comment]
@gregvanl can we get this fixed in the release note? It should be Api not API.

**Comment by jrieken** [comment]
fixed it here: https://github.com/Microsoft/vscode/wiki/Extension-API-process#about-proposed-api

**Comment by jrieken** [comment]
Seems like June, July, and August release notes got this wrong...

**Comment by gregvanl** [comment]
Fixed in release notes https://github.com/Microsoft/vscode-docs/commit/dcf7c6d94c34c0053ed45231ec200c7a5954cc8c

**Comment by csvn** [comment]
@jrieken Yeah this was only a doc issue, but I didn’t realize it at first. Maybe I should have been clearer about that when I realized it. Just thought to leave it open intill at least the release notes are updated, to avoid simular issues in the future.
