### ISSUE TITLE
debug - large array not abbreviated

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#5809]
#4951

* have extension code (node v5.10.0) like below

```
        let data = new Array(10001);
        data.fill(42);
        
        console.log(data.length);

        let longString = data.join('oooooo');
        longString += '<TOO LARGE>';
        
        console.log(longString);
```

* break in there and inspect the `data` variable using the viewlet and/or hover
* ⚡ each properly of the array is shown as is as well as the `[0...99]` groups
* note that this only happens after filling the array (`data.fill(42)`) and it shows 10000 element eagerly

![screen shot 2016-04-26 at 11 51 03](https://cloud.githubusercontent.com/assets/1794099/14814186/75744f9c-0ba5-11e6-80f9-ae49325eb7cf.png)

**Comment by bpasero** [comment]
@jrieken assigning back to you to retest this scenario with a newer Alpha build that includes our node-debug fix to actually enable debug injection for Electron.

**Comment by jrieken** [comment]
fixed with latest chances
