### ISSUE TITLE
Debugger controls and "debugging" / "running" status never finishes running python script

### ISSUE THREAD

**Issue by Balky79** [Microsoft/vscode#58094]
- VSCode Version: 1.27.1
- OS Version: Windows 10

Steps to Reproduce:

1. Run any python script that finishes gracefully or uses exit() to exit. 
2. Debugger remains on screen, and VS code remains "executing" the script using 0% of proc. 

Does this issue occur when all extensions are disabled?: Yes/No
If i disable all python extensions, I can't run the python code, so... No they are not. 
![vscodebug2](https://user-images.githubusercontent.com/18532205/45172218-a3a25580-b1fc-11e8-84e0-ac10c60198d8.png)

**Comment by mjbvz** [comment]
Please try filing this issue against the python extension first
