### ISSUE TITLE
Cpp Debugging fails since 1.26.1

### ISSUE THREAD

**Issue by yamcenutzer** [Microsoft/vscode#58091]
- VSCode Version: 1.26.1, 1.27.1
- OS Version: Centos 7.x

Steps to Reproduce:
1. install cpptools extension
2. try to launch (cpp) debugger

Does this issue occur when all extensions are disabled?: Yes, except for the cpptools ext. , obviously

I have added an issue in the cpptools extensions site, but since it seems to depend on vscode itself, I am entering an issue here too.

Summary: up to vscode 1.25.1 with cpptools extensions (all versions) everything was fine, after that things break.
More details + history:
https://github.com/Microsoft/vscode-cpptools/issues/2489

**Comment by weinand** [comment]
Please file this issue against the debugger extension you are using.
