### ISSUE TITLE
Automated maximize of minimized editors No Longer Working, 

### ISSUE THREAD

**Issue by peterson-umoke** [Microsoft/vscode#58099]
- VSCode Version:  1.27.1
- OS Version: Win10

Steps to Reproduce:

1. Open any two file in either grid view
2. reduce the width of one and try to switch to either file.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@peterson-umoke I cannot reproduce, can you show a video?
