### ISSUE TITLE
Lost debugger current line indicator

### ISSUE THREAD

**Issue by tchapin** [Microsoft/vscode#58106]
Issue Type: <b>Bug</b>

After upgrading to 1.27.1 and applying the new setting "window.titleBarStyle" = "custom" the Python debugger no longer shows the current line. Reverting the window.titleBarStyle back to "native" does not resolve, even after a restart.

Instructions to change the title bar and menus to a dark theme:
https://code.visualstudio.com/updates/v1_27#_custom-title-bar-and-menus-on-windows-and-linux

I'm using the Python 2018.8.0 extension.

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:18.328Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (8.14GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.3.2
python|ms-|2018.8.0
open-in-browser|tec|2.0.0

</details>

**Comment by tchapin** [comment]
I tested on another machine. After the upgrade to 1.27.1 the Python debugger correctly shows the current line. It's only after applying the setting "window.titleBarStyle" = "custom" does the problem occur.

**Comment by tchapin** [comment]
Here is a demo. While stepping through, there is no indication of the current line
![vscode debug missing current line](https://user-images.githubusercontent.com/6968474/45176063-ebb18000-b1dc-11e8-8af6-2edf87ac7ab6.gif)

**Comment by tchapin** [comment]
update: after further investigation, I discovered that this problem is only present when the folder was opened via a UNC path. It works correctly when the folder is mapped to a drive letter.

**Comment by isidorn** [comment]
Please file this against the python extension. And make sure you can reproduce with latest vscode insiders https://code.visualstudio.com/insiders/
Python is probably sending wrong paths for UNC paths to vscode
