### ISSUE TITLE
Search History doesn't survive changing search pane location

### ISSUE THREAD

**Issue by bryceschober** [Microsoft/vscode#58108]
- VSCode Version:1.27.1
- OS Version:Ubuntu 14.04

Steps to Reproduce:

1. Search for several different terms
2. Change settings to move search panel from sidebar to panel or vice versa
3. Use alt+up/down to navigate history. No history is available

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/44491
