### ISSUE TITLE
debug - missing translation

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#5810]
* see screen shot
* it says _paused on Haltepunkt_ which is only half german. unsure if this bad translation or bad string externalisation. 

![screen shot 2016-04-26 at 12 05 01](https://cloud.githubusercontent.com/assets/1794099/14814629/6624ea0e-0ba7-11e6-838c-475ece576736.png)

**Comment by isidorn** [comment]
All good, haltepunk is comming from debug adapter and that is translated. 
Paused on is coming from vscode and we are about to recieve those translations some time this week

**Comment by isidorn** [comment]
To verify please wait for translations to come in - start of next week I believe (just mailed them to check status)

**Comment by joaomoreno** [comment]
![image](https://cloud.githubusercontent.com/assets/22350/19800134/a99fe718-9cfa-11e6-8370-50b3cf4d4c64.png)
