### ISSUE TITLE
Message not found popup

### ISSUE THREAD

**Issue by hadiidbouk** [Microsoft/vscode#58100]
This popup appear whenever I change a file name.

![capture](https://user-images.githubusercontent.com/19314956/45173768-cdb24280-b211-11e8-97ee-794f54340796.PNG)

**Comment by mjbvz** [comment]
We need more information to investigate this. Please use [this guide](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests) to report a proper issue

**Comment by mjbvz** [comment]
Closing as this issue is not actionable without more information

Please try using the latest vscode insiders builds to see if you still see this error
