### ISSUE TITLE
Breadcrums on csharp are not working as good as typescript.

### ISSUE THREAD

**Issue by Jonatthu** [Microsoft/vscode#58103]
vscode 1.27 (and 1.26 too) mac and windows

When I click the method name, breadcrums are just fine.
![image](https://user-images.githubusercontent.com/3742176/45175248-d418ce00-b1c1-11e8-96e5-bb5b5e4595da.png)

When I click inside the method the breadcrums is not in sync with the method name
![image](https://user-images.githubusercontent.com/3742176/45175293-f1e63300-b1c1-11e8-99d2-0333394e5e2b.png)

On typescript even if I am clicking in the body method is working fine.
![image](https://user-images.githubusercontent.com/3742176/45175409-3e317300-b1c2-11e8-83bd-706332afea1c.png)

I have created a bug on the omnisharp repo as well 
https://github.com/OmniSharp/omnisharp-vscode/issues/2496

**Comment by mjbvz** [comment]
This is a c# extension issue. Please follow up with the issue against them
