### ISSUE TITLE
move section/elements in outline view

### ISSUE THREAD

**Issue by tolot27** [Microsoft/vscode#58107]
It would be great if its possible to move/reorder elements or sections (i. e. in a markdown document) within the outline view just by drag-and-drop (i. e. by pressing CTRL at the same time). For markdown it should adapt the header depth accordingly.
This feature can be helpful for other document types/editors, as well, i. e. html or reording functions in source code files.

**Comment by nealot** [comment]
Related to https://github.com/Microsoft/vscode/issues/49925

**Comment by aisbergde** [comment]
@tolot27 did you find a solution? Maybe any extension which could be used? It is not possible to recreate a similar issue, the bot will assign it to this closed issue.

I have seen a similar feature implemented in MindForger https://github.com/dvorka/mindforger
but it is hard to use the program on a high resolution screen.

**Comment by tolot27** [comment]
@aisbergde My feature request is identical to the Drag/Drop reording mentioned in https://github.com/microsoft/vscode/issues/49925#issuecomment-401848520. #49925 is still open.
