### ISSUE TITLE
Preview window in different place than the code

### ISSUE THREAD

**Issue by moseleyi** [Microsoft/vscode#58118]
Recently I started using markdown files to keep interesting and needed docs about various things to not have to search for them in Google. 

But I experienced an issue where I'm editing the end of the file but the preview scrolls to a point where I can't see anything.

This is my starting point:

![md1](https://user-images.githubusercontent.com/16131590/44228605-b7115200-a163-11e8-90d7-d6c725daea87.jpg)

Now I go to the last line and delete a whitespace at the end of it

Suddenly the preview jumps to the following state:

![md2](https://user-images.githubusercontent.com/16131590/44228641-c8f2f500-a163-11e8-9e3e-8d0c0ecd1e34.jpg)

So I have to scroll to the top to preview it. Not sure if this is a bug or I just haven't configured something?

-- Edit
After suggestions from vscode-markdown plugin forum I changed the following settings

 ```
"markdown.preview.scrollEditorWithPreview" : false,
    "markdown.preview.scrollPreviewWithEditor" : false,
```

But the problem still persists, now if I scroll the preview to any place and then edit the file in any place, the preview goes back to the beginning, always. I disabled the extension to see if it had an impact but unfortunately the problem is still there

**Comment by mjbvz** [comment]
Please share some example markdown text that demonstrates this problem

**Comment by Astrantia** [comment]
@mjbvz I can confirm the preview view is broken. For me it's already blank on startup. Same with Latex extension preview. Thought it was only Latex at first and blamed the extension but apparently it's the same with Markdown and it's not only me. Note that I'm using latest insider

**Comment by mjbvz** [comment]
@Astrantia That is #58203. Unrelated to this issue

**Comment by moseleyi** [comment]
Any text demonstrates this problem as per my screenshot, it was one of many
