### ISSUE TITLE
Text selection persists despite clicking outside of the section

### ISSUE THREAD

**Issue by solonaarmstrong** [Microsoft/vscode#58117]
I don't find an existing matching issue.

![selectvscode](https://user-images.githubusercontent.com/6239480/45183111-046b6700-b1d8-11e8-9c4f-ce94bcb73b8c.gif)

I would like to be able to click outside a selection area once to undo the selection.

**Comment by alexandrudima** [comment]
@rebornix I think this is caused by the dnd logic. Perhaps we can check for this case (the target is the empty area below text) and cancel the selection in this case.

@solonaarmstrong In the meantime, a possible workaround is to use `"editor.dragAndDrop": false`

**Comment by rebornix** [comment]
To reproduce this issue

* Selecting some text
* Mouse down on empty area and move a little bit before releasing the mouse
* The selection is not cleared.
