### ISSUE TITLE
When registering new task, also provide problem matcher

### ISSUE THREAD

**Issue by roicpp** [Microsoft/vscode#58110]
Hi,
I need enhanced options to handle my compilation errors and the current ProblemMatcher json definition doesn't give me the options I need.
I thought the best way is when defining a new Task to also have the option to register a new ProblemMatcher with it, or maybe even have the option to register ProblemMatcher.
I also commented on the post #57015 but I thought this request deserves a separate post.
Also, will you receive a pull request regarding adding such feature?

BTW, my use case is both operating in a Windows system with a Linux build server and having a build system which only gives the file name in the error path.

**Comment by dbaeumer** [comment]
I am not sure what you requesting. Supporting registering a problem matcher in code will not provide more power since it will still be limited to regular expressions. 

I think what you are asking for is that a task can intercept the task output and write its own matcher. Is this correct ?

**Comment by dbaeumer** [comment]
I am still don't understand what you are requesting. Can you provide me with an example?

**Comment by roicpp** [comment]
Sure, currently when I receive compilation error, it looks like this:
random_file.c:84:18: error: \x used with no following hex digits
In the build server random_file.c is under /home/admin/demo_project/internal_folder/random_file.c
I'm executing a build command from a Windows machine which executes the command on my Linux build system.
Also random_file.c location for vscode is C:\projects\demo_project\internal_folder\random_file.c
So I have here 2 issues:
* The build system only outputs the file name and not the complete file path
* And even if I overcame the first issues, vscode still expects to receive the Windows file path and not the Linux path

To tackle this issues, if I can have a custom uriProvider/problem matcher where I can do my own file finding logic, I'll be able to locate the file.

**Comment by dbaeumer** [comment]
But how would that work using regular expression. You want to execute code. Right?

**Comment by roicpp** [comment]
Yep, I want to execute code during the file finding stage.

**Comment by dbaeumer** [comment]
I will mark as a dup of https://github.com/Microsoft/vscode/issues/11663 since this ask for solving the same problem.

**Comment by roicpp** [comment]
It's indeed similar. 
For the sake of completion below is an output example I need to handle:
`gmake[3]: Entering directory `/home/admin/modules/ide/proxyis/is/util'
[Thu Sep 13 15:35:28 IDT 2018] Start doing VANILLA variation...
gcc   -DDEBUG -g  -fpic -DDYNAMIC_COMP -Wall -Wno-parentheses -Wno-unreachable-code -Wno-write-strings -Wno-comment -Wno-sign-compare -Wno-unknown-pragmas -Wno-unused -Wno-deprecated-declarations -Wno-misleading-indentation -Wno-trigraphs -Wno-switch -Wno-format -Werror -pipe -march=i686 -Dlinux50 -DARCH_STR='"linux50"'  -fdiagnostics-show-option -I/home/admin/modules/ide/proxyis/include -fno-strict-aliasing -fno-common -fno-omit-frame-pointer -Dlinux -DUNIXOS=1  -c -Wdeclaration-after-statement -Wno-implicit-function-declaration -Wno-pointer-sign -o linux50/debug.dynamic/classify.o classify.c
classify.c: In function 'destroy_info':
classify.c:129:2: error: expected expression before 'if'
  if (((clsf_node_t *)clsf)->mime)
  ^~
classify.c:129:2: error: 'return' with a value, in function returning void [-Werror]
classify.c:124:1: note: declared here
 destroy_info(void *clsf)
 ^~~~~~~~~~~~
cc1: all warnings being treated as errors
gmake[5]: *** [linux50/debug.dynamic/classify.o] Error 1`

As you can see the issue is in classify.c.
It's Linux path is /home/admin/modules/ide/proxyis/is/util/classify.c - this is where it's compiled
In the error line I only get classify.c
And the path vscode know is: C:\modules\ide\proxyis\is\util\classify.c
