### ISSUE TITLE
autoFindInSelection should disable 'in selection' when replacing single-line selection

### ISSUE THREAD

**Issue by Spongman** [microsoft/vscode#58111]
Issue Type: <b>Bug</b>

to repro:
1) set `"editor.find.autoFindInSelection": true,` in your settings 
2) open a multi-line text file
3) select a _single_ word in the file
4) hit 'Ctrl-H' (Edit->Replace)

NOTE:
- the search box is (correctly) initialized with the selected word.
- the focus is (correctly) placed in the 'replace' box.
however
- the 'Find in Selection' box is **incorrectly** checked/enabled.

it _never_ makes sense to have the 'Find in Selection' box selected in this case (when initializing the search box from a single-line selection during a replace), since here the selection _is_ the thing being searched for.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3403)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (1.50GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.5.6
macros|ged|1.2.1
beautify|Hoo|1.4.2
hg|mrc|1.2.3
csharp|ms-|1.15.2
typescript-javascript-grammar|ms-|0.0.44
debugger-for-chrome|msj|4.9.1
live-server-preview|neg|0.1.2
typescript-hero|rbb|2.3.2
shader|sle|1.1.3

</details>

**Comment by Spongman** [comment]
this is not actually a duplicate of that bug, and it still occurs in 1.28.0

again, if you have `autoFindInSelection` checked, select a single word and hit ctrl-H the find/replace dialog **shouldn't** have the 'find in selection' option checked - it only makes sense for multi-line selections.

**Comment by Spongman** [comment]
ctrl-F3 is also broken by this.

**Comment by rebornix** [comment]
Re https://github.com/microsoft/vscode/issues/27083#issuecomment-546539918.
