### ISSUE TITLE
API to dynamically control which snippets are shown 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#58112]
Proposed fix for #1304

**Problem**
Snippets are currently shown at all locations in a file. In js/ts for example, this results in us suggesting the `for` loop snippet inside of class bodies or in function calls

**Proposal**
Allow built-in and user snippets to specify a `when` clause that determines if the snippet should be shown:

```json
{
	"Print to console": {
		"prefix": "log",
		"body": [
			"console.log('$1');",
			"$2"
		],
		"description": "Log output to console",
		"when": "completionContext ~= statement"
	}
}
```

Then allow this `when` clause to be dynamically controlled by an extension. One thought is to provide this as metadata on the `CompletionList` object:

```ts
export class CompletionList {
    isIncomplete?: boolean;
    items: CompletionItem[];
    
    completionContext?: string;
}
```

In this example, the `completionContext` contextkey used in the `when` would be set from `CompletionList` that VS Code gets from the extension.

**Comment by jrieken** [comment]
That's an interesting idea

**Comment by jrieken** [comment]
One could argue tho that the provider should return those snippets then. E.g don't define them statically but compute them on the fly when suggestions are requested... The downside of that is that some feature don't work, like tab-completions. However, we can also think about enabling those for all kind of suggestions...

**Comment by octref** [comment]
This seems to couple the syntax of the `completionContext` to a LS. What happens if someone is using Flow LS instead of TS?

But I do like the general idea.

**Comment by mjbvz** [comment]
@jrieken Yes that would solve the context problem but eliminates some of the usefulness of snippets, such as being easily user configurable and being available before language servers come online. Still lots of open questions about this proposal though

@octref The completion context can be a string enum or something like `CodeActionKind` instead of a plain string. A few possible contexts:

- statement 
- expression
- class body
- module (at top level of a file)

**Comment by octref** [comment]
@mjbvz That seems quite arbitrary a list. For example, for CSS I want `property` and `propertyValue`, for HTML I want `attribute` and `attributeValue`. It's probably impossible to enumerate all of them in our dts file.
