### ISSUE TITLE
debug - large ArrayBuffer kills debugging

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#5811]
#4951

* take default extension from `yo code`
* put this inside the command
```
        let v = process.version;
        console.log(v);

        let buffer = new ArrayBuffer(320000);
        console.log('byte buffer', buffer.byteLength);

        let view = new Int32Array(buffer);
        console.log('int32 view', view.length);

        for (let i = 0; i < view.length; i++) {
            view[i] = i * 2;
        }

        console.log('made it...');
```
* put a breakpoint on the first and last line
* run, break, steps until the for-loop, hint continue to run the last statement
* ⚡ eventually I get told that nodejs isn't responding anymore, debugging is in a weird state like Continue, Stepping being enabled but dysfunctional

**Comment by bpasero** [comment]
@jrieken assigning back to you to retest this scenario with a newer Alpha build that includes our node-debug fix to actually enable debug injection for Electron.

**Comment by jrieken** [comment]
fixed with latest changes
