### ISSUE TITLE
Insiders: Markdown syntax highlighting not preserved across lines

### ISSUE THREAD

**Issue by gmarino2048** [Microsoft/vscode#58122]
- VSCode Version: 1.27.1-insider 
- OS Version: macOS 10.13.6

Steps to Reproduce:

1. Open any markdown document
2. Start a line with bold/code/italics syntax
3. Hit return key
4. End line with bold/code/italics syntax
5. Code is not highlighted blue as normal

<img width="250" alt="screen shot 2018-09-06 at 5 47 12 pm" src="https://user-images.githubusercontent.com/23267637/45186868-eb28e180-b1fc-11e8-8a69-a5e0cb54ef0c.png">

<img width="218" alt="screen shot 2018-09-06 at 5 48 22 pm" src="https://user-images.githubusercontent.com/23267637/45186923-14497200-b1fd-11e8-9055-114f0d2d3675.png">

<img width="242" alt="screen shot 2018-09-06 at 5 50 05 pm" src="https://user-images.githubusercontent.com/23267637/45187000-54105980-b1fd-11e8-9aed-fe365643b9f3.png">

This does not affect bolding/code/italics in markdown preview.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Closing as out of scope. Achieving line spanning matches like this is very difficult to do using the textmate grammars that power our syntax highlighting. Not worth it for these cases
