### ISSUE TITLE
Terminal leaves detached background processes running on reload in windows.

### ISSUE THREAD

**Issue by tracker1** [Microsoft/vscode#58126]
- VSCode Version: 1.27.1
- OS Version: Windows 10

Steps to Reproduce:
1. Start a process in a terminal, such as a node server
2. Install a plugin and click "reload"

Does this issue occur when all extensions are disabled?: Yes

It would be nice if VSCode could track what processes are open and either kill them, or reattach the I/O to a new terminal on restart/reload scenarios.  Likewise shutting down VS Code should kill anything running in a terminal.

I'm uncertain if I've ever noticed the behavior in Linux or MacOS, but it's definitely irritating in Windows.

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
