### ISSUE TITLE
Cannot connect after compile error

### ISSUE THREAD

**Issue by andr3medeiros** [Microsoft/vscode#58128]
Issue Type: <b>Bug</b>

1. Connect to a node debug session using the following configuration:
```
"configurations": [
        {
          "type": "node",
          "request": "attach",
          "name": "Attach to Docker",
          "preLaunchTask": "tsc-watch",
          "port": 9229,
          "restart": true,
          "localRoot": "${workspaceFolder}",
          "remoteRoot": "/usr/src/app/",
          "outFiles": [
            "${workspaceFolder}/www/**/*.js"
          ]
        }
      ]
```
2. Change your code, inserting some compile error.
3. When the [dialog](https://imgur.com/a/Aztvayj) asks if you want to "see errors or debug anyway", click "show erros". 
4. Correct errors and click try to debug again. Nothing happens.

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:47.222Z)
OS version: Linux x64 4.4.0-134-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2404)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|15.57GB (1.22GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
swagger-viewer|Arj|2.0.2
vscode-node-readme|ben|3.0.2
vscode-markdownlint|Dav|0.20.0
FreeMarker|dco|0.0.9
tslint|eg2|1.0.38
prettier-vscode|esb|1.6.1
vsliveshare|ms-|0.3.623
vscode-docker|Pet|0.1.0

</details>

**Comment by isidorn** [comment]
Thanks for trying it out, closing

**Comment by andr3medeiros** [comment]
> This should be fixed in the latest insiders
> @andr3medeiros can you please try reproducing this with the new insiders https://code.visualstudio.com/insiders/

It does not show the dialog anymore. Is this intentional?

**Comment by isidorn** [comment]
@andr3medeiros no, the dialog should be show. Are there build errors? Do you see them in the problems panel or in the status bar?

**Comment by andr3medeiros** [comment]
@isidorn Yes, there were build errors, they are printed correctly in the console, and I could reconnect after correcting them.

But the dialog indeed is not showing.

Version: 1.28.0-insider
Commit: 83d5a29433d7f576b59db8019575a0c9dc78a967
Date: 2018-10-01T13:24:42.941Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by isidorn** [comment]
@andr3medeiros is it possible that you create a repository on github which shows this problem. So I can simply clone it and investigate more?
