### ISSUE TITLE
Output panels are not upated on Windows

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#58127]
- Open VS Code
- Set log level to trace
- Open Shared Process log channel
- Play around in Extensions viewlet that will generate some shared process logs

🐛 Shared process log is not updated.

Root cause is that `FileService` file watcher is not triggering change event. See the following video

![kapture 2018-09-07 at 0 38 50](https://user-images.githubusercontent.com/10746682/45189025-3e1f8a80-b237-11e8-80f4-f2ad5960d4a8.gif)

**Comment by sandy081** [comment]
It works totally fine if I use my old file watcher - https://github.com/Microsoft/vscode/commit/df34abbdf989719fa42b01ba66f49ae59fe8a7b4#diff-68e53ca915552b4eacef1a1c946a87ee

**Comment by bpasero** [comment]
@sandy081 `fs.watchFile` is the worst watcher to have because it will stat the file every second to see for changes (you could argue that this is also the most reliable way of detecting file changes).

Does this reproduce only sometimes or always?

**Comment by sandy081** [comment]
@bpasero You can reproduce it on current insiders on windows. For eg Git log will not be updated unless you hide and show the channel again.

**Comment by sandy081** [comment]
After discussing with @bpasero I implemented my own watcher for output channel files using file service
