### ISSUE TITLE
TypeScript version selection in JS-only project

### ISSUE THREAD

**Issue by AlCalzone** [Microsoft/vscode#58120]
Issue Type: <b>Feature Request</b>

When working in a JS-only project, it is very cumbersome to select the version of TypeScript to use. One has to fiddle with the paths in the workspace settings.

An easy workaround is to create a ts file, change the version there with the button in the status bar and delete the ts file afterwards. IMO there should be an easier or more intuitive way to change the version when editing JS files.

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:18.328Z)
OS version: Windows_NT x64 10.0.17134

**Comment by mjbvz** [comment]
Use the `Select typescript version` command in the command palette. It works in both js and ts files
