### ISSUE TITLE
Cannot configure build tasks by clicking on the suggested bar (after trying to execute a task)

### ISSUE THREAD

**Issue by Navis-Raven** [Microsoft/vscode#58124]
- VSCode Version:
1.27.1
5944e81f3c46a3938a82c701f96d7a59b074cfdc
x64
French Locale
- OS Version: Windows 7 professionnal

Steps to Reproduce:

1. Do de steps in this official tutorial until (with any code) 12:40 https://www.youtube.com/watch?v=X7CXjKGi_ro
2. In this version there is no "task" menu, so instead go to terminal menu, then click on "execute task" 
3. This is not as beautiful as in the video but it will tell you like in the video that "no build task found, configure tasks..."
4. Click on configure tasks

Acutual results: nothing happens, not like in the video in which it creates a configuration file

Not applicable

**Comment by Navis-Raven** [comment]
no duplicate detected

**Comment by dbaeumer** [comment]
This works for me using an empty workspace

![cast](https://user-images.githubusercontent.com/1931590/45206816-536fd580-b286-11e8-96d2-b6d14b21baa9.gif)

I can't comment on whether this makes a difference with the CPP tools installed as shown in the video. If you see problems with the CPP tools please report the issue there.

**Comment by Navis-Raven** [comment]
@dbaeumer it works because you didn't respect the protocol to reproduce the bug. The steps you do in your video are working for me as well:  You went to "configurer les tâches de génération par défaut" instead of "exécuter la tâche"

I've just reproduce the bug on another PC with Windows 8.1

Again,

Here are a simplified steps to reproduce the bug. Please follow these:
0. From an empty workspace like you did
1. go to Terminal menu
2. Then click on "Exécuter la tâche"
3. The click on "Aucune tâche à exécuter.... configurer les tâches"

Then you'll see that nothing happens

**Comment by dbaeumer** [comment]
You are correct.

**Comment by Navis-Raven** [comment]
You have all infos you need now. Good luck to fix it.

**Comment by dbaeumer** [comment]
@chrmarti this fails do to an exception in the list widget

```
  ERR Invalid index 0: Error: Invalid index 0
    at WorkbenchList.List.open (file:///C:/Users/dirkb/Projects/mseng/VSCode/vscode/out/vs/base/browser/ui/list/listWidget.js:1048:27)
    at MouseController.onMouseDown (file:///C:/Users/dirkb/Projects/mseng/VSCode/vscode/out/vs/base/browser/ui/list/listWidget.js:426:31)
    at file:///C:/Users/dirkb/Projects/mseng/VSCode/vscode/out/vs/base/common/event.js:456:70
    at file:///C:/Users/dirkb/Projects/mseng/VSCode/vscode/out/vs/base/common/event.js:442:57
    at Emitter.fire (file:///C:/Users/dirkb/Projects/mseng/VSCode/vscode/out/vs/base/common/event.js:151:38)
    at HTMLDivElement.fn (file:///C:/Users/dirkb/Projects/mseng/VSCode/vscode/out/vs/base/browser/event.js:9:48)
```

Interestingly when I debug through it it does not happen. So seems timing related.

**Comment by chrmarti** [comment]
The problem is that the selection change event lets QuickInput clear the list and then the list's code for the open event fails because the clicked element is no longer there: https://github.com/Microsoft/vscode/blob/1c921394696edbecac21f2993155dfcc4a67b167/src/vs/base/browser/ui/list/listWidget.ts#L507

I can fix this by disabling the open event, which is not used by QuickInput.

@joaomoreno Isn't this a bug in the list widget?

**Comment by joaomoreno** [comment]
@chrmarti Maybe just disable open for now.
