### ISSUE TITLE
官方便携版更新问题

### ISSUE THREAD

**Issue by azagz** [Microsoft/vscode#58138]
Issue Type: <b>Bug</b>

官方便携版无法后台更新，每次更新必出错

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:18.328Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (12.71GB free)|
|Process Argv|D:\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.5.6
php-debug|fel|1.12.5
php-intellisense|fel|2.3.5
rest-client|hum|0.19.1
gitignore|mic|1.0.1
vscode-language-pack-zh-hans|MS-|1.27.2
vscode-format|rya|0.0.6

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
> Official portable version does not update in the background, every update must be error

**Comment by joaomoreno** [comment]
@azagz Do you have an error log file?
