### ISSUE TITLE
使用官方便携方式制作的vscode，无法自动升级

### ISSUE THREAD

**Issue by azagz** [Microsoft/vscode#58136]
- VSCode Version:
- OS Version:
win10
Steps to Reproduce:

1.根据官方教程制作便携版，放到d盘，无访问权限问题
2.有更新时，无法自动更新，总是失败

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by byyxx128** [comment]
@azagz 
你们反馈的时候这么大字看不见？
![image](https://user-images.githubusercontent.com/20079289/45194233-2a1c5e80-b220-11e8-970d-0475011f8664.png)
另外，官方有便携版，你再自己制作一遍是……你要是能看懂官方教程，说明你会说英语啊……
Anyway，翻译一下。
***
**Translation here:**
> 1. I create a portable version as shown in official guide. There's always no access permissions if I put it in the D drive (not an OS part).
> 2. It can't be updated automatically if an update is available. Updates always fail.

**Comment by joaomoreno** [comment]
#58138
