### ISSUE TITLE
removeFromRecentlyOpened Command Broken

### ISSUE THREAD

**Issue by daytonellwanger** [Microsoft/vscode#58131]
VSCode Version: 1.27.1-Insiders
OS Version: Win10

Steps to Reproduce:

1. Create an extension that uses the `removeFromRecentlyOpened` command (e.g. `vscode.commands.executeCommand('vscode.removeFromRecentlyOpened', 'somePath')`)
2. Run the extension

EXPECTED:
Path is removed from list of recently opened files.

ACTUAL:
Command fails with `[UriError]: Scheme contains illegal characters`.

The stack shows the error is coming from electron:
```
Error: [UriError]: Scheme contains illegal characters."
1:"    at C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:59:35"
2:"    at t.e (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:59:461)"
3:"    at new t (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:60:990)"
4:"    at Function.e.revive (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:60:845)"
5:"    at C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:353:512"
6:"    at Array.map (<anonymous>)"
7:"    at e.call (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:353:450)"
8:"    at e.onPromise (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:162:803)"
9:"    at e.onRequest (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:163:968)"
10:"    at e.onRawMessage (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:163:885)"
```

More info:
I've tried passing in strings that have the path formatted in various ways, and am pretty confident they are valid URIs. Additionally, this is a regression. I can run the same extension, use the same argument to the command, on VS Code 1.26.1 (Stable) and have the expected result.

**Comment by bpasero** [comment]
Arguable a candidate if this is a regression.

**Comment by sandy081** [comment]
`file-uri` changes went into 1.27

**Comment by aeschli** [comment]
@daytonellwanger Do you remember what the path was?

**Comment by daytonellwanger** [comment]
@aeschli looks like you've the issue resolved. Let me know if I can provide further information. I'll verify the fix once it ships.

**Comment by daytonellwanger** [comment]
I just tested this with today's build 
(Version: 1.28.0-insider (system setup)
Commit: 7fcd81cd0f88bb2040f249b09cf6bdd83d9ea2ef
Date: 2018-09-17T09:37:55.086Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64)
and am still seeing this issue.
Here's the path I was passing as the argument: `C:\Users\daellwan\AppData\Local\Temp\tmp-4CFE9B9A2EED67B43699F7C3340FDD091F7E\Visual Studio Live Share.code-workspace`

**Comment by daytonellwanger** [comment]
Here's how I'm invoking the command and seeing this error:
```
try {
    await vscode.commands.executeCommand('vscode.removeFromRecentlyOpened', currentWorkspacePath);
} catch (e) {
    debugger;
}
```

**Comment by bpasero** [comment]
I see this when running `vscode.commands.executeCommand('vscode.removeFromRecentlyOpened', 'C:\\Users\\daellwan\\AppData\\Local\\Temp\\tmp-4CFE9B9A2EED67B43699F7C3340FDD091F7E\\Visual Studio Live Share.code-workspace');`
 on Windows:

![image](https://user-images.githubusercontent.com/900690/45665269-584b4980-bb10-11e8-9371-fc761e8f2f4f.png)
