### ISSUE TITLE
New Python Language Server doesn't seem to work with namespace packages

### ISSUE THREAD

**Issue by mfeif** [Microsoft/vscode#58139]
Issue Type: <b>Bug</b>

I'm using the bare package made by python-cookiecutter here:
https://github.com/ionelmc/python-nameless

A fresh checkout followed by a `pipenv install -e  .` results in a couple of problems for VSCode:

1. It can't find tests, though they are in the root, or more accurately, it says it can't find the tests, but if I look at the output log, it's running the tests, but failing on the initial import.

2. Opening a python file `src/__main__.py` shows green error lines on the `from nameless.cli import main`... it can't find nameless.cli with the following message in the tooltip: "[Python (analysis)] Unable to resolve 'nameless.cli'. IntelliSense may be missing for this module."

This isn't my code, but my code was made with this tool, and using this package directly from checkout should help eliminate any pilot error of my own doing :-)

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:31:26.156Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (4.18GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.59
vscode-eslint|dba|1.5.0
vscode-great-icons|emm|2.1.41
vsc-material-theme|Equ|2.4.2
prettier-vscode|esb|1.6.1
python|ms-|2018.8.0
indent-rainbow|ode|7.2.4
vscode-css-peek|pra|2.1.0
sass-indented|rob|1.4.9
json-template|sto|0.3.1
highlight-matching-tag|vin|0.4.4
html-css-class-completion|Zig|1.17.1

</details>

**Comment by mjbvz** [comment]
Please file this issue against the python extension

**Comment by mfeif** [comment]
It's not an extension; it's the built-in language server.
