### ISSUE TITLE
debug - show console action should toggle better

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#5813]
- have the debug viewlet open
- have the output visible, like git output
- select the output action in the debug viewlet, it shows the debug console
- select the output action again
- it hides the bottom panel but I would expect it to restore my previous UI state. that is reveal the output channels again, not hide the panel. Tho obviously when it brought up the panel it should hide it

**Comment by isidorn** [comment]
@jrieken can you please clarify what you mean by 'output action in the gitviewlet'?
I understood that as - open git viewlet and 'show git output' (the one under elipses)
Click on the 'show git output' always opens the git output channel for me so I think I am missing something here.

**Comment by jrieken** [comment]
@isidorn misspelled, fixed the description.
