### ISSUE TITLE
cmd-click-hold window title shows dir menu, but also drags window

### ISSUE THREAD

**Issue by rusmaxham** [Microsoft/vscode#58130]
Issue Type: <b>Bug</b>

- open a file
- cmd-click and hold window title to show dir menu
- still holding cmd-click, try to select a dir
- window drags and dir menu with it, so can't select anything in the dir menu

VS Code version: Code 1.27.0 (7b9afc4196bda60b0facdf62cfc02815509b23d6, 2018-09-05T05:22:06.672Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.24GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_8939654|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
autotrim|Nat|1.0.6
unity-debug|Uni|1.3.0
unity-snippets|Ycl|0.1.2
eppz-code|epp|1.2.41
gfxapi-ls|Goo|0.0.1
csharpfixformat|Leo|0.0.74
camelcasenavigation|map|0.3.48
python|ms-|2018.8.0
cpptools|ms-|0.18.1
csharp|ms-|1.15.2
sublime-keybindings|ms-|4.0.0
ruby|reb|0.20.0
java|red|0.30.0
unity-tools|Tob|1.0.5
vscode-java-debug|vsc|0.12.2
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.8.0
vscode-maven|vsc|0.10.0

</details>

**Comment by sbatten** [comment]
unfortunately, the dragging ability comes from electron and we cannot prevent it when this menu is triggered. however, if you just cmd-click (do not hold), you should be able to select something in the dir menu without issue.

**Comment by rusmaxham** [comment]
decent workaround.
