### ISSUE TITLE
High CPU utilization 

### ISSUE THREAD

**Issue by TusharMathur2017** [Microsoft/vscode#58146]
Issue Type: <b>Bug</b>

On Windows 10 
Open VS Code latest version 
Open Task manager 
You will see that CPU utilization is very high 

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:18.328Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (7.34GB free)|
|Process Argv|C:\Users\42TCM\AppData\Local\Programs\Microsoft VS Code\Code.exe C:\Collaboration%20Software\CodeOfConduct\CertificationPage|
|Screen Reader|no|
|VM|40%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
xml|Dot|2.3.2
auto-rename-tag|for|0.0.15
code-runner|for|0.9.4
terminal|for|0.0.10
minify|Hoo|0.3.0
PowerShell|ms-|1.8.4
team|ms-|1.136.0
code-spell-checker|str|1.6.10
ayu|tea|0.16.0

</details>

**Comment by mjbvz** [comment]
Please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information so that we can investigate this

**Comment by mjbvz** [comment]
Closing as this issue is not actionable without more information
