### ISSUE TITLE
字体虚化

### ISSUE THREAD

**Issue by ensleep** [Microsoft/vscode#58142]
整个界面，包括菜单栏/编辑器内的文字待都出现严重的虚化以致于看不到字样，当鼠标移动或焦点改变时，虚化的情况会有所变化 ，但是，有可能变好有可能变得更坏。

windows 10
27寸2k显示器，dpi为100%
显卡gtx1070TI

其它软件诸如dota2/word/chrome/qq待一切正常。

**Comment by mjbvz** [comment]
Are you using VS Code 1.27.1? There was a bug in 1.27.0 that could cause an issue similar to what you describe

**Comment by mjbvz** [comment]
Closing as likely fixed by 1.27.1
