### ISSUE TITLE
Vscode can't render interface

### ISSUE THREAD

**Issue by annder** [Microsoft/vscode#58141]
- VSCode Version:1.27.0
- OS Version:Windows 17134.228

Steps to Reproduce:

1. 
2.

Does this issue occur when all extensions are disabled?: No

**Comment by annder** [comment]
Supplement: The submission number is`769afc`，The submission date is:2018-09-05

**Comment by mjbvz** [comment]
Sounds like #57982. Please update to 1.27.1
