### ISSUE TITLE
editor - sticky parameter hints

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#5814]
The editor input has changed but the old parameter hints still show

![screen shot 2016-04-26 at 12 43 50](https://cloud.githubusercontent.com/assets/1794099/14815601/a3500396-0bac-11e6-8066-ebd4b67369a4.png)

**Comment by jrieken** [comment]
@alexandrudima @joaomoreno unsure to whom this belings

**Comment by bpasero** [comment]
I have seen this too!
