### ISSUE TITLE
Some part of VS code started using port 8080

### ISSUE THREAD

**Issue by mmusket** [Microsoft/vscode#58144]
- VSCode Version: 1.27.1
- OS Version: Windows 10

Steps to Reproduce:

1. Launch a vue app on port 8080
2. The port is in use and vue uses 8081 instead 
3. The app is setup to use 8080 and used to work until recently, this is a change in behaviour. 
4. Running netstat and killing the process that uses port 8080 kills the extension host 

Does this issue occur when all extensions are disabled?: Yes/No

No 

So I suppose an extension is using that port, although I cannot determine which one is causing the problem. 

Is there a way to see the extension port usage?

**Comment by bm-stschneider** [comment]
Try `netstat -anob | findstr "8080"` maybe you can identify the process there.

**Comment by joaomoreno** [comment]
You can selectively disable extensions until you find the culprit.

**Comment by bm-stschneider** [comment]
`netstat -tunlp | findstr "8080"` sorry, my bad. With vscode process explorer you may find the process.

**Comment by bm-stschneider** [comment]
https://stackoverflow.com/questions/48198/how-can-you-find-out-which-process-is-listening-on-a-port-on-windows maybe this helps.

**Comment by mmusket** [comment]
@joaomoreno that is what I ended up doing.. 
The culprit was Visual Studio Code Tools for AI

Using netstat shows 8080 being used. Killing the process kills all VS code extensions so it is not suitable solution unfortunately. 

The ideal solution is to have some kind of diagnostic in vscode itself. I suppose this is not something that happens often so it is a low priority..

**Comment by joaomoreno** [comment]
Please file an issue for that extension if you feel it is an issue.
