### ISSUE TITLE
Not removing red line after correct the syntax error

### ISSUE THREAD

**Issue by narendra-leadsense-project** [Microsoft/vscode#58149]
Issue Type: <b>Bug</b>

If there is any syntax error then VS code highlight that line with a red line. After correcting that  syntax error VS code is not removing that line until the file is not saved again. Some time it is confusing that even after the syntax is corrected it shows zig zag redline. I think if the syntax is corrected then VS code should again check the syntax error in whole file and if there any syntax error then it should show zin zag red line rather then until file  is not saved the redline will not disappear.

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:47.222Z)
OS version: Linux x64 4.4.0-134-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz (4 x 2671)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|7.70GB (2.75GB free)|
|Process Argv|/usr/share/code/code .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-cloudformation-yaml|Dan|0.2.2
python|ms-|2018.8.0
vscode-yaml|red|0.0.15
sockscode-vscode|shy|1.0.1
python|tht|0.2.3

</details>

**Comment by mjbvz** [comment]
What language are you working in?

**Comment by narendra-leadsense-project** [comment]
I am using Python

**Comment by mjbvz** [comment]
Please file this issue against the python extension
