### ISSUE TITLE
vs code consuming all of my ram .. please help

### ISSUE THREAD

**Issue by techapoorva** [Microsoft/vscode#58143]
here is an image of my htop 
![screenshot from 2018-09-07 09-30-47](https://user-images.githubusercontent.com/16129526/45198093-5d8fd500-b282-11e8-8f30-84dd33831ee7.png)

thanks I appreciate your help

**Comment by mjbvz** [comment]
Please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information so that we can investigate this

**Comment by mjbvz** [comment]
Closing as this issue is not actionable without more information
