### ISSUE TITLE
Something wrong in the menu bar like this NewFile(<u aria-hidden='true'>N</u>) version 1.28.0

### ISSUE THREAD

**Issue by SanJin-hx** [Microsoft/vscode#58156]

**Comment by usernamehw** [comment]
1. Use <kbd>Alt</kbd> to toggle focus on menu bar
2. Open any menu
![screenshot 46](https://user-images.githubusercontent.com/9638156/45206654-363f0500-b28e-11e8-90df-95f5b828ff6b.png)

VS Code version: Code - Insiders 1.28.0-insider (a3f9f2e7240106aeec2f1d4bc03d7876bd42e2e4, 2018-09-07T05:20:29.346Z)
OS version: Windows_NT x64 10.0.17134

**Comment by sbatten** [comment]
Saw this and resolved this morning. Should be fixed in the next insiders build. For the day since this is very ugly, you can disable menu bar mnemonics with `window.enableMenuBarMnemonics: "false"`

**Comment by sbatten** [comment]
fixed with 4ca21ffb190842ae594c98d83cb01f2929bca8c7
