### ISSUE TITLE
Right click menu crash when menu is beyond editor border.

### ISSUE THREAD

**Issue by V0idk** [Microsoft/vscode#58154]
- VSCode Version: 1.27.1
- OS Version: Linux asd 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce: just add a lot of right click menu item and make it beyond editor border. 

![peek 2018-09-07 14-27](https://user-images.githubusercontent.com/17514799/45202032-29c8a580-b2aa-11e8-93f2-90da0b9fe070.gif)

As you can see, when editor space is enough to hold menu, it doesn't crash.

**Comment by V0idk** [comment]
It's a big problem, please fix it.

**Comment by sbatten** [comment]
duplicate #58154

**Comment by sbatten** [comment]
@V0idk sorry about that. correct issue is #57399
