### ISSUE TITLE
Git errors - give me action to show output

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#5815]
#5766

1. have a git error
2. I would like to see an action left of the 'Close' - 'Open Output', that would take me directly to the git ouput - that way the message and the cause would not be so disconected as now

![screen shot 2016-04-26 at 13 04 54](https://cloud.githubusercontent.com/assets/1926584/14816146/892d3eb8-0baf-11e6-8bde-ef236de43fc6.png)

**Comment by joaomoreno** [comment]
Can't reproduce.

![image](https://cloud.githubusercontent.com/assets/22350/14853001/e764f626-0c89-11e6-8022-6dfaffb2f71e.png)

**Comment by isidorn** [comment]
Here's how I can always repro:

1. Open any file in our repo and remove a semicolon on end of line
2. command pallette > git commit
3. commit will fail due to lint check and I do not get the show output action

**Comment by joaomoreno** [comment]
@bpaseroThis command is a workbench actions which returns an error that [has resolution actions](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/git/browser/gitServices.ts#L706). This pattern works when giving this error directly to the message service. Do you know why this is not getting properly wired up all the way to the message service?

**Comment by joaomoreno** [comment]
👍
