### ISSUE TITLE
Can't start debugging session (extension debugging)

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#58150]
Issue Type: <b>Bug</b>

When I try debugging an extension I get the following error.
![image](https://user-images.githubusercontent.com/641685/45201233-87290c00-b242-11e8-9bdb-1e53ab7bca6b.png)

/cc @weinand 

VS Code version: Code - Insiders 1.28.0-insider (a3f9f2e7240106aeec2f1d4bc03d7876bd42e2e4, 2018-09-07T05:20:29.346Z)
OS version: Windows_NT x64 10.0.17754

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (15.51GB free)|
|Process Argv|C:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by weinand** [comment]
@eamodio I cannot reproduce this and I could not find the error message in our code.
Do you still see this problem if you are running with extensions disabled?

**Comment by eamodio** [comment]
Argh -- it seems like it is caused by Live Share 😢

**Comment by weinand** [comment]
@rodrigovaras the `__sessionId` is an implementation detail of EH debugging and I started to use it only for that. Are you relying on that property in any way?
