### ISSUE TITLE
Error occured while trying to create file

### ISSUE THREAD

**Issue by grekkster** [Microsoft/vscode#58152]
Issue Type: <b>Bug</b>

When I open VSCode, after a while error message pops up:
>Error
>C:\Program Files\MS VS Code\uninst000.exe
>An error occured while trying to create a file in the destination directory:
>Access denied.
>Click Retry to....

I have reinstalled Code with recommended new version with silent updates. It's not a problem with PC, it happens on work PC and home PC.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (10.45GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
pascal|ale|6.3.0
vscode-eslint|dba|1.5.0
xml|Dot|2.3.2
code-runner|for|0.9.4
rest-client|hum|0.19.1
mssql|ms-|1.4.0
csharp|ms-|1.15.2
Go|ms-|0.6.89
PowerShell|ms-|1.8.4
debugger-for-chrome|msj|4.10.0
vscode-docker|Pet|0.2.0
java|red|0.30.0
vscode-yaml|red|0.0.15
vscode-fileutils|sle|2.10.3
sonarlint-vscode|Son|1.5.0
vscode-java-debug|vsc|0.12.2
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.8.0
vscode-maven|vsc|0.10.0

</details>

![vscode-err](https://user-images.githubusercontent.com/35041444/45201834-1bad6180-b277-11e8-87d9-5891a921c60b.png)

**Comment by joaomoreno** [comment]
The UserSetup can only be installed on a path which your user owns. Your user probably doesn't have write access to `C:\Program Files`. Why don't you take the default installation directory?

**Comment by grekkster** [comment]
I believe i have one and only administrator account on one of the PCs with VSCode installation, no other accounts and i installed VSCode into that directory in first place, so i don't think problem is with the write access. Also before i reinstalled the reccomended distribution, there was no problem at all.

And for the second part - I want to decide where my installations go to and i think it's a common feature for the past 20 years at least.

**Comment by joaomoreno** [comment]
Can you show me a screenshot of Code's About dialog?

**Comment by grekkster** [comment]
I can paste it if you dont mind since there is a button in About dialog fot that:
Version: 1.27.1 (user setup)
Commit: 5944e81f3c46a3938a82c701f96d7a59b074cfdc
Date: 2018-09-06T09:21:18.328Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
But this is after update so maybe useless. Yesterday i tried to set VSCode to run as an administrator, then i tried to install updates and it worked without problems. Since then, the error message is gone.

When i get home, maybe i can paste the original About info from my home PC, there should still be the original version with this problem.

**Comment by joaomoreno** [comment]
Right... so did you run the UserSetup as Administrator?

**Comment by blackening** [comment]
![image](https://user-images.githubusercontent.com/1753927/45355386-de3c3180-b5f2-11e8-8534-4b25c2a05ae8.png)

Also having the same problem, this is the about dialog.

**Comment by grekkster** [comment]
Here is the copied About info from my home PC:
Version: 1.26.1
Commit: 493869ee8e8a846b0855873886fc79d480d342de
Date: 2018-08-16T18:38:57.434Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
problem still here, also installed in program files. I don't think i've run UserSetup as an admin, but i'm not sure.

**Comment by joaomoreno** [comment]
@grekkster I suggest to fully uninstall and install the latest windows system install: https://code.visualstudio.com/docs/?dv=win64

**Comment by zhuhang-jasper** [comment]
Have this issue on Windows 10 64bit.
Current workaround is to run VsCode as admin, but it shouldn't be this way.

Why is this issue closed?

**Comment by joaomoreno** [comment]
@zhuhang-jasper If you use the user setup, please install Code in a location that your user has full access to.

**Comment by swingguy0** [comment]
@zhuhang-jasper thanks for posting that it works if you run the program as admin, that worked for me.

RE: @zhuhang-jasper "If you use the user setup, please install Code in a location that your user has full access to."

I am the only user and admin on my computer and have full edit permissions to the "C:\Program Files" directory and am still experiencing this issue.

**Comment by joaomoreno** [comment]
Still:

- Using the user setup, do not install to Program Files
- Using the system setup, feel free to install to Program Files
