### ISSUE TITLE
Problem with keys when running VS Code by X11 forwarding on Mac

### ISSUE THREAD

**Issue by DAA233** [Microsoft/vscode#58155]
- VSCode Version: 1.27.1
- OS Version: Ubuntu 16.04 && Mac OS 10.13.6

Steps to Reproduce:

1. On Ubuntu desktop, install VS Code 1.27.1.
2. On Mac OS, connect the Ubuntu desktop by SSH with `-Y` option and open the remote VS Code by terminal command.

After opening the VS Code, some keys do not work in the X11 forwarding VS Code on Mac OS. For example, 'Backspace' does not work, 'E' works like 'Backspace', 'R' works like 'Tab'...

By the way, it works well when connecting from another Ubuntu desktop rather than a Mac.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
https://github.com/Microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-linux-keybindings

![image](https://user-images.githubusercontent.com/5047891/45283983-a0021d80-b4df-11e8-868e-4de23f64024a.png)

**Comment by DAA233** [comment]
Thank you a lot! Already solved.
