### ISSUE TITLE
Quick pick closes when opening context menu in input field

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#58164]
Issue Type: <b>Bug</b>

1. `"window.titleBarStyle": "custom"`
1. Using `open recent` open context menu on input
1. The context menu is below the list

VS Code version: Code - Insiders 1.28.0-insider (a3f9f2e7240106aeec2f1d4bc03d7876bd42e2e4, 2018-09-07T05:20:29.346Z)
OS version: Windows_NT x64 10.0.17134

**Comment by sbatten** [comment]
this is not just a display issue. the behavior I see is that the context menu takes focus, thus removing the quick pick altogether.
/cc @bpasero

**Comment by sbatten** [comment]
fixed by shadow dom menus it seems

**Comment by bpasero** [comment]
Works, but needs `"workbench.quickOpen.closeOnFocusLost": false`

![image](https://user-images.githubusercontent.com/900690/97564147-6b65be80-19e4-11eb-92d3-1639e12812f8.png)
