### ISSUE TITLE
Custom title bar and menus: Title Position Not Centered

### ISSUE THREAD

**Issue by GordonSmith** [Microsoft/vscode#58169]
- VSCode Version:  1.27.1
- OS Version:  WIndows 10 

Steps to Reproduce:

1. Enable "window.titleBarStyle": "custom"
2. Looking at the title position - it is centered between the last menu item and the MinMaxButtons.
**Expected**:  It should be centered relative to the entire Window.
**Why**:  Muscle memory - when a user wants to quickly look at which application instance any given window is (the visible title), the user has been trained by windows to look at the title bar and specifically to look at the middle section.  In the current  implementation I keep looking at "white space" and my workflow is broken while my brain decides if I need to look left (the menu items) or right, the actual title.
**Bonus Marks**:  It may be worth while giving the title some additional "flare" maybe make it bold and whiter (in dark theme) so its clearly different to the menu items?
![image](https://user-images.githubusercontent.com/966863/45207382-bca01a80-b27f-11e8-84ff-bd86fa296e90.png)
**Bonus Marks II**:  When the menu + title do collide, clipping the menu items, the menu should include a "chevron" or "..." menu item, so you can access the now hidden menus.
![image](https://user-images.githubusercontent.com/966863/45207491-fd982f00-b27f-11e8-9e0d-05c5ee8823f6.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
duplicate #56273
