### ISSUE TITLE
Git commit is slow

### ISSUE THREAD

**Issue by dvxiaofan** [Microsoft/vscode#58160]
- VSCode Version:  1.27.1
- OS Version:  Mac OS， 10.13.4

Now when submitting with `git commit,` the info input interface will appear for at least 5 seconds. It used to appear almost immediately.

**Comment by dvxiaofan** [comment]
In fact, there will be more than ten seconds, more than five seconds.

**Comment by joaomoreno** [comment]
@bpasero This seems to be related to the `code.editor` setting.

**Comment by dvxiaofan** [comment]
@bpasero When I using ‘git commint’ in the terminal to bring up the input interface of Vscode, it takes at least 10 seconds. Whether it is a system terminal or a terminal of Vscode. But today I updated Vscode and the problem seems to be gone.

**Comment by bpasero** [comment]
> But today I updated Vscode and the problem seems to be gone.

OK closing then.

**Comment by dvxiaofan** [comment]
@bpasero thankyou
