### ISSUE TITLE
getaddrinfo ENOTFOUND marketplace.visualstudio.com marketplace.visualstudio.com:443

### ISSUE THREAD

**Issue by marcpoggi** [Microsoft/vscode#5816]
Hello, 
I am unable to load the library nor get any info about installed plugin. 
I am behind a proxy driven by ntlm @localhost:7124 
- VSCode Version: 0.10.11
- OS Version: Windows 7 

All my app are fine except VS !!

Steps to Reproduce:
1. CTr+ Shift P 
2. ext install 
   get following error message :

"getaddrinfo ENOTFOUND marketplace.visualstudio.com marketplace.visualstudio.com:443"

My user config 

{   "strict-ssl":false,
    "http.proxyStrictSSL": false,
    "http.proxy": "localhost:7124",
    "https.proxy": "localhost:7124",
    "git.enabled": true,
    "git.path": "c:\Applications\tools\git\bin\git.exe"
}

How to solve this issue ? g

**Comment by joaomoreno** [comment]
@marcpoggi Set `http.proxy` to `https://localhost:7124`.

**Comment by marcpoggi** [comment]
don't work . 
same message

I tried this 
{   "strict-ssl":false,
    "http.proxyStrictSSL": false,
    "http.proxy": "htttps://localhost:7124",
    "https.proxy": "https://localhost:7124",
    "git.enabled": true,
    "git.path": "c:\\Applications\\tools\\git\\bin\\git.exe"
}
and this
{   "strict-ssl":false,
    "http.proxyStrictSSL": false,
    "http.proxy": "htttp://localhost:7124",
    "https.proxy": "https://localhost:7124",
    "git.enabled": true,
    "git.path": "c:\\Applications\\tools\\git\\bin\\git.exe"
}

**Comment by joaomoreno** [comment]
Your `http.proxy` value has 3 `t` characters: `htttp`. Make sure it only has 2.

Also, the configuration setting `https.proxy` does not exist; only `http.proxy`.

**Comment by marcpoggi** [comment]
I already got it , but not still working

last attempts
{   "strict-ssl":false,
    "http.proxyStrictSSL": false,
    "http.proxy": "http://localhost:7124",
    "https.proxy": "https://localhost:7124",
    "git.enabled": true,
    "git.path": "c:\\Applications\\tools\\git\\bin\\git.exe"
}
and with
{   "strict-ssl":false,
    "http.proxyStrictSSL": false,
    "http.proxy": "https://localhost:7124",
    "https.proxy": "https://localhost:7124",
    "git.enabled": true,
    "git.path": "c:\\Applications\\tools\\git\\bin\\git.exe"
}

**Comment by marcpoggi** [comment]
Not Working 
I tried 
{   "strict-ssl":false,
    "http.proxyStrictSSL": false,
    "http.proxy": "http://localhost:7124",
    "git.enabled": true,
    "git.path": "c:\\Applications\\tools\\git\\bin\\git.exe"
}

and {   "strict-ssl":false,
    "http.proxyStrictSSL": false,
    "http.proxy": "https://localhost:7124",
    "git.enabled": true,
    "git.path": "c:\\Applications\\tools\\git\\bin\\git.exe"
}

.... Not successful

**Comment by joaomoreno** [comment]
Also make sure you restart Code every time you change them.

This is very unfortunate. We're looking into a way to detect your system's proxy settings and using them accordingly.

**Comment by marcpoggi** [comment]
Yes I restarted each time.
I am not fortunate , you're right.

Anyway to workaround this problem ?

ᐧ

Marc Poggi
+33(0)6 84 085 086

-----------------------------------------------
*FEELTEST*
*11 Avenue Bataillon Carmagnole Liberté*
*69120 Vaulx en Velin*
+33(0)954 909 111
-----------------------------------------------
www.feeltest.com



2016-04-27 10:01 GMT+02:00 João Moreno <notifications@github.com>:

**Comment by joaomoreno** [comment]
Not as far as I know.

Can you give me the output of the following commands?

```
node -p "require('dns').getServers()"
node -e "require('dns').resolve4('marketplace.visualstudio.com ', (err, result) => console.log(err, result))"
node -e "require('dns').lookup('marketplace.visualstudio.com ', (err, result) => console.log(err, result))"
```

**Comment by marcpoggi** [comment]
first command

$ node -p "require('dns').getServers()"
[ '10.171.108.2',
  '10.171.34.57',
  '10.171.30.4',
  'fec0:0:0:ffff::1' ]

second one
node -e "require('dns').resolve4('marketplace.visualstudio.com ',
function(err, result){console.log(err, result)})"


{ [Error: queryA ENOTFOUND marketplace.visualstudio.com ]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'queryA',
  hostname: 'marketplace.visualstudio.com ' } undefined

and final one  !!
node -e "require('dns').lookup('marketplace.visualstudio.com ',
function(err, result){console.log(err, result)})"

{ [Error: getaddrinfo ENOTFOUND marketplace.visualstudio.com ]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'marketplace.visualstudio.com ' } undefined


ᐧ

Marc Poggi
+33(0)6 84 085 086

-----------------------------------------------
*FEELTEST*
*11 Avenue Bataillon Carmagnole Liberté*
*69120 Vaulx en Velin*
+33(0)954 909 111
-----------------------------------------------
www.feeltest.com



2016-04-27 12:25 GMT+02:00 João Moreno <notifications@github.com>:

**Comment by joaomoreno** [comment]
Can you maybe talk to your system's administrator and show him the results of that query? Looks like the DNS server isn't responding well to those domain names.

**Comment by marcpoggi** [comment]
I dont think problem comes from there ...
my collegue doesn't resolve the address too, both resolve4 and lookup
but yet it works for him in VS !


ᐧ

Marc Poggi
+33(0)6 84 085 086

-----------------------------------------------
*FEELTEST*
*11 Avenue Bataillon Carmagnole Liberté*
*69120 Vaulx en Velin*
+33(0)954 909 111
-----------------------------------------------
www.feeltest.com



2016-04-27 15:03 GMT+02:00 João Moreno <notifications@github.com>:

**Comment by joaomoreno** [comment]
Oh interesting. What happens if you copy his settings? Where is your settings file located?

**Comment by marcpoggi** [comment]
settings are the same .
location too (c:users/myident/AppData/Roaming/Code/User
ᐧ

Marc Poggi
+33(0)6 84 085 086

-----------------------------------------------
*FEELTEST*
*11 Avenue Bataillon Carmagnole Liberté*
*69120 Vaulx en Velin*
+33(0)954 909 111
-----------------------------------------------
www.feeltest.com



2016-04-27 15:36 GMT+02:00 João Moreno <notifications@github.com>:

**Comment by rjreutbd** [comment]
Installating extension with following proxy setting is working for me!!!!!!! 
// Place your settings in this file to overwrite the default settings
{
    "http.proxy": "http://porxy server address:port",
    "http.proxyStrictSSL": false,
}

**Comment by joaomoreno** [comment]
Merging with #27838
