### ISSUE TITLE
High CPU Usage and second electron_node

### ISSUE THREAD

**Issue by bm-stschneider** [Microsoft/vscode#58166]
Issue Type: <b>Bug</b>

Sometimes when I start a task, I get an additional electron_node Server that sucks up all the cpu and does not release it. I have no idea what it is doing or why I have to servers running.

![image](https://user-images.githubusercontent.com/30625381/45206720-00961e00-b286-11e8-9461-c47df7c89720.png)

VS Code version: Code - Insiders 1.28.0-insider (a3f9f2e7240106aeec2f1d4bc03d7876bd42e2e4, 2018-09-07T05:12:19.624Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_2183701|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.4
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.59
vscode-svgviewer|css|1.4.5
vscode-eslint|dba|1.5.0
gitlens|eam|8.5.6
tslint|eg2|1.0.38
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.4.2
prettier-vscode|esb|1.6.1
comment-anchors|Exo|1.1.1
beautify|Hoo|1.4.2
smarty|imp|0.3.0
docthis|joe|0.7.1
php-cs-fixer|jun|0.1.85
vscode-codemetrics|kis|1.17.1
php-symbols|lin|2.1.0
VS-code-vagrantfile|mar|0.0.7
twig-language-2|mbl|0.3.1
php-namespace-resolver|Meh|1.1.0
vscode-scss|mrm|0.6.2
debugger-for-chrome|msj|4.10.0
color-highlight|nau|2.3.0
vetur|oct|0.12.6
vscode-docker|Pet|0.2.0
vscode-versionlens|pfl|0.21.1
material-icon-theme|PKi|3.5.3
ruby|reb|0.20.0
vscode-yaml|red|0.0.15
code-settings-sync|Sha|3.1.2
autoimport|ste|1.5.3
easy-snippet-maker|tar|0.0.6
Snippet|vsc|0.2.4
vim|vsc|0.16.3
quokka-vscode|Wal|1.0.146
vscode-import-cost|wix|2.8.0
sort-js-object-keys|zen|1.0.1

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
What is the full process info of the process with high cpu usage? You can right click to copy this

**Comment by bm-stschneider** [comment]
`115	573	34570	             electron_node server.js `

**Comment by bm-stschneider** [comment]
![image](https://user-images.githubusercontent.com/30625381/45296705-35fb6f80-b503-11e8-8723-ee656a9285f4.png)

**Comment by jrieken** [comment]
> Sometimes when I start a task,

A task as in `F1 > Run Task`?

**Comment by jrieken** [comment]
And what task is that?

cc @dbaeumer

**Comment by jrieken** [comment]
Ok, that's weird. Your [screen shot](https://github.com/Microsoft/vscode/issues/58166#issuecomment-419890454) point to a language server (which hints that this is caused by an extension) but I don't understand how that is related to executing a task

**Comment by dbaeumer** [comment]
@jrieken is correct. The server.js is very likely not spwaned by the task. I suspect that the ant task that you start by executing `Vagrant Grunt JS` does something to the file system to which the server.js reacts to (may be a bad implemented listening stratgy).

Can you reproduce this with all extensions disabled (--disable-extensions). If not, please find the extension that owns the server and report the issue there (meta comment: all server VS Code ships with have a language type in its named, so it is not one of ours :-)).

**Comment by bm-stschneider** [comment]
Is there a way to get more information about the server.js stuff?

**Comment by dbaeumer** [comment]
OK. Let us know if you find something out.
