### ISSUE TITLE
Touchbar steps are reversed prev/next

### ISSUE THREAD

**Issue by g4challenge** [Microsoft/vscode#58161]
On Macbook with Touchbar the Icons are Next/Prev while anywhere else they are Prev/Next.

- VSCode Version: 1.27.1
- OS Version: 10.13.6 

Steps to Reproduce:

1. Launch VS Code
2. Touchbar shows icons reversed > <

If this is intended it may be suitable to improve the icons to clarify the intended use.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@g4challenge this sounds a lot like https://github.com/Microsoft/vscode/issues/35906 where I did not get any info. Please check my comments there and follow them to find out more. In the end it would be interesting if you can reproduce when running out of sources.

**Comment by bpasero** [comment]
Actually this will be fixed with https://github.com/microsoft/vscode/issues/85453
