### ISSUE TITLE
Terminal not drawing properly after computer wake up from suspension

### ISSUE THREAD

**Issue by wewearglasses** [Microsoft/vscode#58168]
Issue Type: <b>Bug</b>

Open terminal in VS Code
Set computer to suspend
Wake up from suspension
Terminal window shows corrupted texture, like those GL not cleared patch

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:34:20.517Z)
OS version: Linux x64 4.15.0-33-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 4299)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|7.71GB (1.13GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
anaconda-extension-pack|ms-|1.0.0
python|ms-|2018.8.0
cpptools|ms-|0.18.1
vscode-yaml|red|0.0.15
vim|vsc|0.16.3

</details>

**Comment by Tyriar** [comment]
This is related to Chromium, the fix will probably trickle down from there eventually.
