### ISSUE TITLE
Unable to select git more menu. Execute where the cursor located

### ISSUE THREAD

**Issue by mochrira** [Microsoft/vscode#58165]
- VSCode Version: 1.27.1 (user setup)
- OS Version: Windows 10 64-bit Build 17134.228

Steps to Reproduce:

1. Click SCM -> More Actions...
2. Menu will overlap the "three dots" more action button while the click still on hold. As quick as i release the mouse click, the menu will close and execute the menu i hovered.
3. This behaviour occurs when im using mouse, and works correctly when i using touchpad.

Solution:

1. Keep git more menus displayed below the button
2. Give menu overflow scroll if overflow the window

OR

1. Remove mouse up event  from menu and wait until the second click

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Ildarik** [comment]
Same in Ubuntu. "More actions..." works only if I hide SC providers
![screenshot from 2018-09-08 08-43-56](https://user-images.githubusercontent.com/10713674/45250790-62688d80-b343-11e8-8b8f-e46919a83abf.png)
