### ISSUE TITLE
[html] Word based suggestion has a problem

### ISSUE THREAD

**Issue by shizengzhou** [Microsoft/vscode#58172]
Issue Type: <b>Bug</b>

![suggestion](https://user-images.githubusercontent.com/24318019/45209342-53d89280-b2bf-11e8-83d9-34616b5b5dcf.png)

There should be a "p" in the suggestions.

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:18.328Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (3.40GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.5.0
auto-rename-tag|for|0.0.15
svn-scm|joh|1.34.0
vscode-language-pack-zh-hans|MS-|1.27.2
vscode-jsp|pth|0.0.2
vscode-icons|rob|7.25.0
open-in-browser|tec|2.0.0

(1 theme extensions excluded)

</details>

**Comment by maomaobug** [comment]
The same problem experienced in macOS 10.13.6, vscode Version 1.27.1. Also after pressed ctrl + space, it's showing loading forever. 
![screen shot 2018-09-07 at 5 28 31 pm](https://user-images.githubusercontent.com/5878327/45211089-ef6c0200-b2c3-11e8-88b2-256dd7415f4a.png)

I experienced this after disabled vim plugin and reloaded.

**Comment by SpenceUK** [comment]
I have similar issue in linux, no suggestions or code completion. When using Java placing a dot after object name no longer brings up method list. vscode v1.27
Used to be able to ctrl + mouse click on a type to go to definition/view source code, this no longer works.

**Comment by acurry** [comment]
Same here, MacOS High Sierra, VSCode 1.27.1. Suggestions no longer work on Javascript files.

**Comment by aeschli** [comment]
@shizengzhou I'm not able to reproduce with a simple example. 
```html
<body>
	<p></p>
	p
</body>
```
Do you see it with this sample? If not, an you paste a sample where this shows?
Also make sure that the editor is in `html` mode. It never hurts to turn off all extensions and see if this makes a difference.

**Comment by aeschli** [comment]
@SpenceUK @acurry Please file separate issue as every language is driven by a different language server.

**Comment by aeschli** [comment]
I think that's because the proposal is filtered as the current prefix already fully matches the 'p' tag.

You can see that `p` is there:

![screenshot from 2018-09-18 15-02-26](https://user-images.githubusercontent.com/6461412/45689583-aaae5980-bb54-11e8-95be-5a21b3717a5d.png)
