### ISSUE TITLE
debug - don't use uuid to generate tree element ids

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#5817]
I have profiled the Debug Console when under heavy load and one thing that stands out is usage of `uuid` in the [`OutputElement`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugModel.ts#L158). Generating UUIDs (which consist of 32 random numbers) is overkill for this problem and a simple static counter should be enough.

**Comment by isidorn** [comment]
Thanks a lot for this investigation, will use a counter
