### ISSUE TITLE
Middle clicking files in breadcrumbs explorer opens as preview

### ISSUE THREAD

**Issue by scriptcoded** [Microsoft/vscode#58176]
- VSCode Version: 1.27.1
- OS Version: Windows 10 Pro

As of 1.27.1 "it is possible to use the middle mouse click in the Explorer view to open a file in a new editor". This should also be the case in the breadcrumbs explorer.

![2018-09-07_11-36-36](https://user-images.githubusercontent.com/6452991/45211360-5f619480-b292-11e8-8db8-8bc8c42c0615.gif)

Steps to Reproduce:

1. Make sure `breadcrumbs.enabled` is set to `true`
2. Open a file
3. Open a file in the breadcrumbs explorer with middle mouse click
4. File is opened in preview mode

Does this issue occur when all extensions are disabled?: Yes

**Comment by haddigan** [comment]
This is the case with middle clicking files from the Source Control tab as well. Middle click behavior should be consistent across all methods of opening files

**Comment by Hindol** [comment]
If I recall correctly, there is a setting to enable/disable preview mode. Should we split the setting into three settings, one for each scenerio?

**Comment by scriptcoded** [comment]
@Hindol To me, no. I would say it's the same feature, so only one option should be necessary. If we don't have to clog up the settings, the why do?

**Comment by haddigan** [comment]
Middle clicking should always open in non-preview mode, so enabling/disabling preview mode itself should have no bearing on middle click's functionality

**Comment by jrieken** [comment]
> Should we split the setting into three settings, one for each scenerio?

Just one setting, so re-using the existing setting, should be enough.

**Comment by Hindol** [comment]
I just checked. There are two settings related to preview.

1. Enable preview, and,
1. Enable preview from quick open.

I think having a third option *Enable preview from breadcrumbs explorer* makes it consistent. @scriptcoded @jrieken 

This is in addition to what @haddigan has mentioned, i.e. middle click **always** opens non-preview editor.

**Comment by Moniarchy** [comment]
@jrieken is this something that is open for me to work on?

**Comment by jrieken** [comment]
Of course it is! Check this: https://github.com/Microsoft/vscode/blob/141f055452864ff34898c07e159210551bd4c207/src/vs/workbench/browser/parts/editor/breadcrumbsControl.ts#L322-L326


That the handler that runs when something in the picker has been selected. The `data` argument has a payload property which eventually gets you to the actual event that has triggered this. Extract the middle click data from there and feed it into the [`_revealInEditor`](https://github.com/Microsoft/vscode/blob/141f055452864ff34898c07e159210551bd4c207/src/vs/workbench/browser/parts/editor/breadcrumbsControl.ts#L413) - it will be the `pinned` option when calling `openEditor`.

**Comment by Moniarchy** [comment]
@jrieken Thanks! I'll try to have something for you soon.

**Comment by Shobhit1** [comment]
Is this still open to be taken up? I can try whatever you suggested @jrieken . If @Moniarchy has not started on this already?

**Comment by Moniarchy** [comment]
Hey @Shobhit1 this is still something I've been working on.

**Comment by Shobhit1** [comment]
Awesome. Good luck. @Moniarchy

**Comment by jrieken** [comment]
fixed via #59797
