### ISSUE TITLE
Emmet balance inward not select all inward elements when there is no selected text in the beginning

### ISSUE THREAD

**Issue by sabastore** [Microsoft/vscode#58173]
Issue Type: <b>Bug</b>

Hi
I want to select all inward elements of div tag so i use Emmet balance inward but that isn't selects all inward elements of div tag.

When i use Emmet balance inward just selects first child and its children.

my HTML code:

<div>
    <div>this is a text</div>
    <div>this is a another text</div>
</div>

selected code with emmet balance inward action:

<div>this is a text</div>

plase help me.

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:18.328Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3450S CPU @ 2.80GHz (4 x 2794)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.97GB (11.14GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|0.2.0
live-html-previewer|hdg|0.3.0
beautify|Hoo|1.4.2
contextualduplicate|laf|0.2.0
HTMLHint|mka|0.5.0
bootstrap4-vscode|the|4.3.0
highlight-matching-tag|vin|0.4.4
bootstrap-v4-snippets|Zac|0.1.2

(1 theme extensions excluded)

</details>

**Comment by sabastore** [comment]
Hi again
my html code not entered, sorry.

i enter my html code here:
`<div>
<div>this is a text</div>
<div>this is a another text</div>
</div>`

selected code with emmet balance inward action:
`<div>this is a text</div>`

**Comment by ramya-rao-a** [comment]
Did you select any text before running the balance inward action? If yes, what was the selection? If no, where was the cursor before running the balance inward action

**Comment by ramya-rao-a** [comment]
I understand now. Thanks for reporting!
I am pushing a fix and it should be available in tomorrow' [Insiders](https://code.visualstudio.com/insiders)

**Comment by sabastore** [comment]
Thanks for helping again ;)
