### ISSUE TITLE
Version 1.27.1 on Mac kill the CPU - Editor is not usable at all

### ISSUE THREAD

**Issue by samuells** [Microsoft/vscode#58179]
- VSCode Version: 1.27.1
- OS Version: Mac OS High Sierra 10.13.6

Steps to Reproduce:

1. Start VS Code 
2. Mac is CPU and Memory just jump to 100% of usage and nothing can be used.

Does this issue occur when all extensions are disabled?: No

**Comment by samuells** [comment]
Looks like it was caused by CSS Peek Plugin ( https://marketplace.visualstudio.com/items?itemName=pranaygp.vscode-css-peek ) - uninstall helped me

**Comment by dzienisz** [comment]
@samuells thanks for this plugin, can't wait when they will fix that and I will be able to use it.
