### ISSUE TITLE
Ignore empty string argument when starting Code

### ISSUE THREAD

**Issue by johnnytemp** [microsoft/vscode#58177]
- VSCode Version: 1.26.0
- OS Version: macOS

Steps to Reproduce:

1. run `code ''` in command line.
2. VS Code seems opened a workspace of current directory folder, like `code .`

Does this issue occur when all extensions are disabled?: Yes

### Reason the above behavior is improper
When I run some command like `code "$(some command to get the file)"` (e.g. `code "$(which "$1")"` in Linux), if the inner command failed, it return empty string as argument.  VSCode shouldn't open current directory and replace the workspace (which is annoying), but should just open or focus the application instead.

**Comment by bpasero** [comment]
@johnnytemp what would you expect to happen, open an empty window?

**Comment by johnnytemp** [comment]
Yes.  Or focus existing window only.  Just like running `code`.

**Comment by johnnytemp** [comment]
Wrong press

**Comment by Ragnoroct** [comment]
Can I be assigned to this? I'd like to take a stab at it.

**Comment by Ragnoroct** [comment]
@bpasero I've added code that should do the trick. I've tested that it removes an empty `''` argument. I wasn't able to test the actual functionality though because both `./scripts/code.bat` and `./scripts/code-cli.bat` change the current directory. I couldn't figure out how to mimic production without hacking the startup scripts.

**Comment by johnnytemp** [comment]
I just edited the main description to add an example usage - `code "$(which "$1")"` - which open a script file in environment PATH by VS Code to edit it.

### Reason worth a fix

If the argument "$1" for the script name above have typo, VS Code open a big slow workspace folder annoyingly.  The existing behavior has no use, and it put the burden to script writers to write extra lines of if-else code to avoid it.
