### ISSUE TITLE
"editor.autoSurround":"brackets" is not working properly

### ISSUE THREAD

**Issue by PieterSwitten** [Microsoft/vscode#58170]
I added 
```json
"[handlebars]": {
    "editor.autoClosingBrackets":"always",
    "editor.autoClosingQuotes": "always",
    "editor.autoSurround":"brackets"
  },
```

But the brackets are still replacing the selected text.

Also, could there be a option add "Always"? Now its not possible to have it for "brackets" and "quotes"

- VSCode Version: 1.27.1 (and also in the insiders version)
- OS Version: macOS Hight Sierra

Steps to Reproduce:

1. Add the json to the settings.json file
2. Create a file with language mode "Handlebars"
3. Try to encapsulate selected text

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by alexandrudima** [comment]
Our built-in handlebars defines the following surrounding pairs:

https://github.com/Microsoft/vscode/blob/be4ea0f0421280a409247a6ee3f124b9b633c7d5/extensions/handlebars/language-configuration.json#L19:L23

```
	"surroundingPairs": [
		{ "open": "'", "close": "'" },
		{ "open": "\"", "close": "\"" },
		{ "open": "<", "close": ">" }
	]
```

Out of those, `<` is a bracket and `'` and `"` are quotes. When typing `<`, selected text is surrounded with `<` and `>` for me. Is that list incomplete for Handlebars?

**Comment by PieterSwitten** [comment]
Oh I see, I use handlebars for `.stache` files where alot of `{}` and `()` characters are used. Would be nice if it was added.
Or do I need to config that myself?

**Comment by alexandrudima** [comment]
So should we then add `{}` and `()` to the `surroundingPairs` list of handlebars?

(I don't use handlebars so I don't know)

**Comment by pbrubaker** [comment]
I've been attempting to get this to work for an extension I'm authoring for http://ispc.github.io and I would have assumed that the language configuration would be able to specify these pairs using:

	```
"brackets": [
		["{", "}"],
		["[", "]"],
		["(", ")"]
	],
	"autoClosingPairs": [
		{ "open": "[", "close": "]" },
		{ "open": "{", "close": "}" },
		{ "open": "(", "close": ")" },
		{ "open": "'", "close": "'", "notIn": ["string", "comment"] },
		{ "open": "\"", "close": "\"", "notIn": ["string"] }
	],
	"surroundingPairs": [
		["{", "}"],
		["[", "]"],
		["(", ")"],
		["\"", "\""],
		["'", "'"],
		["<", ">"]
	]
```

Is that not the case as I can't seem to get it working.

**Comment by alexandrudima** [comment]
@pbrubaker Yes, that is how it should work. If you still have trouble getting it to work, can you please create a separate issue with a complete `package.json` and a complete language configuration file, to try to reproduce.
