### ISSUE TITLE
Not all keybindings hints ported in custom titleBar

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#58186]
Issue Type: <b>Bug</b>

`"window.titleBarStyle": "custom"`

Activity bar context menu 
![activity_bar_context_menu](https://user-images.githubusercontent.com/9638156/45205013-a6975780-b289-11e8-8714-ab502dad0298.png)

Hide sidebar 
![hide_sidebar](https://user-images.githubusercontent.com/9638156/45205040-b2831980-b289-11e8-96bc-bf10217488fc.png)

Context menu for open editors 
![context_menu_open_editors](https://user-images.githubusercontent.com/9638156/45205058-be6edb80-b289-11e8-95f5-c337d332f387.png)

Copy error for problems panel context menu 
![copy_on_error_context_menu](https://user-images.githubusercontent.com/9638156/45205095-d5153280-b289-11e8-8cbd-4432117a0d35.png)

Terminal context menu 
![terminal_context_menu](https://user-images.githubusercontent.com/9638156/45205106-dcd4d700-b289-11e8-9220-15ac17a3d3f8.png)

Hide panel for panel context menu 
![hide_panel](https://user-images.githubusercontent.com/9638156/45205124-ee1de380-b289-11e8-93b9-d371bdf56f80.png)

Almost all inputs context menu 
![inputs_context_menu](https://user-images.githubusercontent.com/9638156/45205136-f9710f00-b289-11e8-90fb-a57939480475.png)

Keybindings GUI context menu 
![keybindings_context_menu](https://user-images.githubusercontent.com/9638156/45205153-03930d80-b28a-11e8-962d-d1c3d92ff1b3.png)

VS Code version: Code - Insiders 1.28.0-insider (a3f9f2e7240106aeec2f1d4bc03d7876bd42e2e4, 2018-09-07T05:20:29.346Z)
OS version: Windows_NT x64 10.0.17134

**Comment by bpasero** [comment]
@sbatten fyi went ahead and fixed it because I was not happy with how the native context menu service differs here to the custom one. Turns out the service should just depend on the keybindings service as a way to resolve the keybindings for the menu.
