### ISSUE TITLE
Allow searching trough files when the 'task' keyword is used

### ISSUE THREAD

**Issue by yanikore** [Microsoft/vscode#58188]
I have files with filenames like `task.overview.twig`.

When searching for a file using Ctrl+P (`workbench.action.quickOpen`), I'd like to not limit my search results to tasks only when the `task` keyword is appended by a space.

**Comment by dbaeumer** [comment]
Has nothing to do with tasks.

Could be @jrieken  for scoring

**Comment by yanikore** [comment]
Here are some pictures:

Normal file search dialog when `task` is written:

![](https://i.imgur.com/LJHr8BW.png)

Dialog when `task.over` is written (note the "dot"):

![](https://i.imgur.com/13XE0ah.png)

Dialog when `task over` is written (no "dot"):

![](https://i.imgur.com/PW2VU4l.png)

As you can see, the `task` keyword forces to search through tasks from within the file search dialog, instead of the behavior where it simply splits on spaces, like this:

![](https://i.imgur.com/IrYi3x8.png)

I have the F12 key bound to the task dialog so this functionality isn't useful for me especially because of the many files with `task` in their name.

**Comment by bpasero** [comment]
Yeah I see the issue but I have no good idea how to fix because "task" is reserved by the task quick open to show tasks. Quick open does not allow to force it to be used for file search in this case. 

@yanikore why do you want to type the space at all when searching for files?
