### ISSUE TITLE
Breadcrumbs reset file scroll for simple files

### ISSUE THREAD

**Issue by SailorMax** [Microsoft/vscode#58182]
- VSCode Version: 1.27.1
- OS Version: Windows 10 1803

Steps to Reproduce:

1. Open simple but long PHP file without classes and functions
2. Scroll to the bottom
3. click on "..." in breadcrumbs to output list of variables

Expected: no file scroll changed
Actual: VSCode show start of file. But when close list of variables, scroll position restored. But if close list of variables by click inside of opened document, we have new selection in result.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
That's the design of the feature. When a symbol is selected it is scrolled into view and highlight (just like quick outline). On dismiss the original view state is restored

**Comment by SailorMax** [comment]
@jrieken But what about selection, when user close the list by mouse click on any place of opened file? It looks like bug.
