### ISSUE TITLE
breadcrumbs in YAML files

### ISSUE THREAD

**Issue by dzienisz** [Microsoft/vscode#58184]
Hi, this is my first Feature request to VS Code.

I would like to **see** and **be able to copy in one click** YAML file breadcrumbs.

![zrzut ekranu 2018-09-07 o 12 25 09](https://user-images.githubusercontent.com/3521624/45214110-d8181f00-b299-11e8-9606-c7e48df79160.png)

Similar feature and behaviour I found in my workmate Webstorm IDE.

Thanks

**Comment by mjbvz** [comment]
We only provide basic syntax highlighting support for yaml out of the box. More advanced yaml language support—such as breadcrumbs—can be provided by an extension. Please consider filing a feature request for this against an existing yaml extension such as https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml (if it does not already add this)
