### ISSUE TITLE
Allow default to be set for compound launch configs

### ISSUE THREAD

**Issue by j-turner28** [Microsoft/vscode#58189]
I've tried searching for this and wasn't able to find anything, but apologies if this has already been addressed.

I have a launch.json set up which consists of a coreclr launch config and a chrome launch config. I also have a compound configured to start both of these together. They work correctly launched separately and as part of the compound.

The issue that I'm having is that the coreclr launch config is more of a requirement, I don't use it for debugging very often. Most of my debugging is done via the chrome debugger (I'm debugging an Angular app). However, when I launch my compound, the coreclr launch config is selected by the debugger and I have to manually select the chrome one every time.

On top of this, if I refresh the web page after the chrome debugger has been selected then it switches back to coreclr.

As you can imagine, this gets old really quickly. I've tried changing the order of the configurations in both the launch.json configurations array and in the compounds configurations array. I've even tried renaming them in case it was an alphabetical sort.

I'm fairly certain that the chrome debugger starts much quicker than the coreclr one and so gets added to the list first. Then the coreclr one starts, gets added to the list second and gets selected. This makes sense, but there is nothing that I can do about this so I'm stuck with the ordering right now.

If you could add a way to configure which compound configuration should be selected by default then this issue could be resolved very easily.

**Comment by weinand** [comment]
You could set a breakpoint so that the chrome debugger always stops and becomes the active debug session.
