### ISSUE TITLE
debug - show if a thread is running or not

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#5818]
The ui for running/paused threads is confusing because the running thread seems to be represented as tree nodes that can be expanded into nothing. I would have expected an indication if the thread is paused or not.

![screen shot 2016-04-26 at 13 15 15](https://cloud.githubusercontent.com/assets/1794099/14817969/b62a2cd6-0bba-11e6-9630-b9a0f03186f5.png)

![screen shot 2016-04-26 at 13 15 24](https://cloud.githubusercontent.com/assets/1794099/14817973/bb43c5ce-0bba-11e6-9f4d-27393df5c32e.png)

**Comment by isidorn** [comment]
@jrieken we are now showing paused / running next to the thread. Check it out and let me know what you think :)

**Comment by jrieken** [comment]
@isidorn Nice batches for Pause/Running. Tho, I still see a thread which is paused but has no children. How is that possible? Should the UI show a placeholder?

<img width="404" alt="screen shot 2016-05-26 at 13 39 15" src="https://cloud.githubusercontent.com/assets/1794099/15573439/59b84cae-2347-11e6-84f1-e5fade5bbdc4.png">


(to repo)

* get latest dot net cli stuff and have an app like this
```
using System;
using System.Threading.Tasks;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var rnd = new Random();

            Task.Factory.StartNew(async () => {
                while(true) {
                    await Task.Delay((int) (rnd.NextDouble() * 4000));
                    Console.WriteLine("1");
                }
            });

            Task.Factory.StartNew(async () => {
                while(true) {
                    await Task.Delay((int) (rnd.NextDouble() * 4000));
                    Console.WriteLine("2");
                }
            });

            Console.WriteLine("Hello World!");
            Console.ReadLine();
        }
    }
}

```

**Comment by isidorn** [comment]
It is still possible for a thread to be stopped and that for some reason the callstack could not be retrieved (like in the node v6 issue that andre was mentioning in the standuo).
It is up to the adapter to decide if it reports a thread with no call stack as stopped. So this is comming from the c# debug adapter.

fyi @weinand @gregg-miskelly

**Comment by gregg-miskelly** [comment]
@jrieken if you were confused, you can certainly open a bug at https://github.com/Omnisharp/Omnisharp-vscode/issues for us to add a placeholder (ex: '[No current call stack]') frame.
