### ISSUE TITLE
Unable to close main menu by clicking in caption.

### ISSUE THREAD

**Issue by jschroedl** [Microsoft/vscode#58197]
Issue Type: <b>Bug</b>

Use the experimental menu bar with window.titleBarStyle set to custom.

Click the Help menu to show it. Now click on the title of your document (anywhere to the right of the shown menu). The Help menu should dismiss but does not. 

Dismissing a menu this way seems to be a habit I have and that's not native menubars work on Windows and I'd appreciate it if I could click-away the custom menus in a a similar fashion.

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:18.328Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2630 v2 @ 2.60GHz (24 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.95GB (17.20GB free)|
|Process Argv|C:\Users\saspjs\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-perforce|bam|1.1.3
markdown-preview-github-styles|bie|0.1.3
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.5.0
svgeditor|hen|2.3.0
python|ms-|2018.8.0
cpptools|ms-|0.18.1
csharp|ms-|1.15.2
PowerShell|ms-|1.8.4
vscode-versionlens|pfl|0.21.1
vscode-icons|rob|7.25.0
partial-diff|ryu|1.4.0
perforce|sle|3.1.0
markdown-all-in-one|yzh|1.6.0

</details>

**Comment by sbatten** [comment]
duplicate #53479
