### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by FranklinZhang91** [Microsoft/vscode#58191]
- VSCode Version: 1.26.1
- OS Version: Windows10 1803

Steps to Reproduce
[vscode-inno-updater-1536324210.log](https://github.com/Microsoft/vscode/files/2361080/vscode-inno-updater-1536324210.log)
:

1.Fail to update

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
Does `C:\Users\ZFY\AppData\Local\Programs\Microsoft VS Code\Code.exe` exist?
