### ISSUE TITLE
Expose settings editor to other JSON files

### ISSUE THREAD

**Issue by yufeih** [Microsoft/vscode#58196]
The new settings editor provides a great UI to edit _flat_ json configs based on json schema. Can it be extended to edit other json config files? This is very helpful to improve the configuration experience for a wide range of tools.

If an extension marks a file to show settings editor using `contributes. jsonValidation`, an editor will be shown to edit the file, using the same schema provided for validation.

```json
"contributes": {
    "jsonValidation": [{
        "fileMatch": ".jshintrc",
        "url": "http://json.schemastore.org/jshintrc",
        "settingsEditor": true
    }]
}
```

**Comment by roblourens** [comment]
The settings editor is designed specifically for vscode settings, not as a generic json editor. It wouldn't do a good job with other json patterns.

**Comment by yufeih** [comment]
Right, I understand that it won't work well with arbitrary json like `.jshintrc` in the above example. 

Would it be possible to extend it to files that followed vscode settings convention?

[docfx](https://github.com/dotnet/docfx) wanted an UI to manage its configuration, preferably right inside vscode. Now extension settings only goes to _/.vscode/settings_.

If settings editor can be used to edit other json files, we are more than happy to align our settings format with whatever vscode desires.

**Comment by roblourens** [comment]
That's pretty unlikely, the current editor doesn't even parse or write JSON directly. It just talks to our ConfigurationService.

**Comment by roblourens** [comment]
Normal settings in vscode extensions **will** show up in the new settings editor automatically.

**Comment by yufeih** [comment]
Thank you for the info. For now, we can try having a vscode extension populate the settings editor, and sync settings from _.vscode/settings.json_ back to _docfx.json (our own settings file)_
