### ISSUE TITLE
Horizontal Scrolling

### ISSUE THREAD

**Issue by mritunjaymusale** [microsoft/vscode#58198]
Issue Type: <b>Feature Request</b>

If I can scroll veritcally using Ctrl+Up/Down arrow is it possible integrate a new option like Alt+left/right for scrolling horizontally (usually won't be needed but certain code documentations are really lengthy ) 

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:47.222Z)
OS version: Linux x64 4.15.0-33-generic

**Comment by NotWearingPants** [comment]
I suggest <kbd>Alt</kbd>+<kbd>Home</kbd>/<kbd>End</kbd> as shortcuts as all the shortcuts with left/right arrow plus modifiers are taken.
