### ISSUE TITLE
Typescript: auto-complete type signature when overriding a superclass method

### ISSUE THREAD

**Issue by aleclarson** [Microsoft/vscode#58193]
### Suggestion

In `vscode v1.26.1`, overriding a method doesn't have auto-completion for the type signature. Only the method *name* is auto-completed. Auto-completion of the type signature should be possible, and maybe the cursor would be moved into the body of the method.

### Use Cases

Less typing.

### Search Terms

- typescript autocomplete method override
- superclass method type signature autofill

**Comment by mjbvz** [comment]
Duplicate of #46038 / https://github.com/Microsoft/TypeScript/issues/25207
