### ISSUE TITLE
Goto definition on other file

### ISSUE THREAD

**Issue by Tchoupinax** [Microsoft/vscode#58194]
Hello,

Is it possible to have the `goto definition` feature (CTRL + click) available through file ? (Function is declared in other file).

Thank you ! :)

**Comment by roblourens** [comment]
It is, you just need an extension that supports the language you're using. If it's JS/TS it should be built in.

**Comment by Tchoupinax** [comment]
That's the problem, i'm using Javascript. It works well in the same file but not if function is declared outside. I'm not alone in my team so we thought it was not implemented.

**Comment by mjbvz** [comment]
Please provide some example code or small example project that demonstrates this problem

**Comment by Tchoupinax** [comment]
Hello,

i found i know why it does not work. I try with direct import and it works. My code is this following : 
```javascript
class ApiController {
  constructor({
    apiService,
  }) {
    super();
    this.apiService = apiService;
  }

  async somthinng() {
    const response = await this.apiService.myAwesomeFunction(); 
  }
}
```

apiService parameter is an object from class `ApiService` and passed to ApiController at its initialization. I would like when i CTRL + click on `myAwesomeFunction` it opens ApiService file and focus the function but it can't because it "does not know" about which type is apiService, does know even what it is.

Is it a way to explain which class is it or add a feature to VSCode to detect this way and find the function in the good file ?

Thank you for your time,
Regards,

**Comment by mjbvz** [comment]
Yes, you need to add a [jsdoc annotation](https://github.com/Microsoft/TypeScript/wiki/JsDoc-support-in-JavaScript) that tells vs code what the type of `apiService` is. This could be something like:

```js
class ApiController {
    /**
     * @param {{ apiService: MyOtherClass }} param0 
     */
    constructor({
        apiService,
    }) {
        super();
        this.apiService = apiService;
    }

    async somthinng() {
        const response = await this.apiService.myAwesomeFunction();
    }
}
```
