### ISSUE TITLE
Support Wacom pen for dragging

### ISSUE THREAD

**Issue by ridesirat** [microsoft/vscode#58190]
Hi
This post was closed as a duplicate of  [#43562](https://github.com/Microsoft/vscode/issues/43562) but it's not the same problem. Apparently it's not a "touch" problem.
The wacom pen was working on VSCode. It stoped after the latest VSCodeUserSetup-x64-1.26.1 installation.

![image](https://user-images.githubusercontent.com/42814243/44804129-6284c280-abb8-11e8-80a7-50068636ce57.png)

Now i'ts not possible to rearrange the files tabs because the pen doesn't drag them. With the mouse it's ok. The pen could drag them before the update.

I have no new extensions or installations and none of the other similar issues resolve this.
I hope this info helps.

**Comment by bpasero** [comment]
We do not explicitly support any device besides "Mouse" and "Keyboard", so I will mark this as feature request. It could be that the Electron update (to 2.0.x) broke this.

We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/883208e30da25777874a8ade5f90e1fea638a298/VSCode-win32-x64-1.28.0-exploration.zip)
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/883208e30da25777874a8ade5f90e1fea638a298/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/883208e30da25777874a8ade5f90e1fea638a298/code-exploration-1535724826.tar.gz)

**Comment by anonymoushelpishere** [comment]
Dragging a folder on the files menu, which works with the mouse, also does not work with the surface pen.

**Comment by ridesirat** [comment]
Hi bpasero
VSCode runs under chromium, I suppose.
I was having the same problem in Chrome after an update but there it wasn't possible to select text and drag some things - tabs were ok, though.
Now it's ok and the solution was to Disable "Direct Manipulation Stylus" in chrome://flags.
Maybe some cross-solution with VSCode?
Thanks

**Comment by themooserooster** [comment]
Tried the exploration build for Windows. No dice, same issues.

Pen tablet support is 100% an accessibility issue and critical.  I have chronic tendonitis, so 5 minutes with a mouse and my arm is on fire for the rest of the day. 

Without drag functionality, there's no scrolling, no highlighting, no rearranging panels. The IDE is rendered nearly useless to me because of this.

**Comment by ridesirat** [comment]
I agree.
This is a major issue.
I hope it's not being neglected.
I hoped it would be a easy fix, as it was working fine and we have the exact moment it stopped working.
And I thought it would be just a before/after comparison of all the functions involving pen clicks & dragging.

**Comment by greensci** [comment]
its still not added. i really need this feature.

**Comment by s-h-a-d-o-w** [comment]
People, upvote the original post, not just the comments below.
That's how issues gain visibility!
