### ISSUE TITLE
Copying Folded Code

### ISSUE THREAD

**Issue by vkiranmaniya** [Microsoft/vscode#58209]
Copying folded code is not working well as it should. when i tried to copy the folded code, only the visible tag after folding is copid. you can try as,
step 1 : fold the code block first.
step 2 : copy the folded block of code
step 3 : paste copied code block to somewhere, and you will get what actually happening.

**Comment by aeschli** [comment]
You have to make a selection that covers the end of the folded range as well.

duplicate of #51232
