### ISSUE TITLE
@type {import('.')} Type fails when a file does not have non-comments.

### ISSUE THREAD

**Issue by zavr-1** [Microsoft/vscode#58201]
Issue Type: <b>Bug</b>

When trying to import a type from a file which has purely JSDoc comments, it will fail. 

VS Code version: Code - Insiders 1.27.0-insider (1097b5e9ed81d5f9241648774b35048be168c203, 2018-08-31T10:32:54.890Z)
OS version: Darwin x64 15.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     P7350  @ 2.00GHz (2 x 2000)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: unavailable_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Load (avg)|6, 4, 4|
|Memory (System)|8.00GB (0.15GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_2511461|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.5.0
svg|joc|0.1.2
code-spell-checker|str|1.6.10
vscode-wakatime|Wak|1.2.3

</details>

```js
// a.js
/** @typedef {import('.').Coordinate} Type */
```

```js
// index.js
/**
 * @typedef {{ x:number, y: number }} Coordinate
 */
```

The above does not work, but when changed to the below, starts working.

```js
// index.js
/**
 * @typedef {{ x:number, y: number }} Coordinate
 */

export {}
```

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#27036
