### ISSUE TITLE
Annoying "Auto Import" sintaxe with accent 

### ISSUE THREAD

**Issue by rodrigojcmello** [Microsoft/vscode#58200]
- VSCode Version: 1.27.1
- OS Version: MacOS High Sierra 10.13.6

Steps to Reproduce:

1. Import some module with accent using "auto import"

Auto import with accent works fine but is ugly/annoying to see how is imported (In portuguese there are a lot of words with accents);

Before import the module looks ok in auto complete but it changes after importation.

Does this issue occur when all extensions are disabled?: Yes

<img width="1280" alt="captura de tela 2018-09-07 as 11 41 28" src="https://user-images.githubusercontent.com/5174526/45226102-6a1d2900-b294-11e8-8ac0-c34525a916f3.png">
<img width="1280" alt="captura de tela 2018-09-07 as 11 41 52" src="https://user-images.githubusercontent.com/5174526/45226101-6a1d2900-b294-11e8-85d9-2edf7988fe9c.png">

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#26967
