### ISSUE TITLE
Regression: WebView fails to render

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#58203]
Issue Type: <b>Bug</b>

Any extensions using the Webview api fail to render webviews in today's insiders build.

Maybe related to Electron 3? (Is that in insiders yet?)
/cc @bpasero @mjbvz 

VS Code version: Code - Insiders 1.28.0-insider (a3f9f2e7240106aeec2f1d4bc03d7876bd42e2e4, 2018-09-07T05:20:29.346Z)
OS version: Windows_NT x64 10.0.17754

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (17.31GB free)|
|Process Argv|C:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by mjbvz** [comment]
Not electron 3 related. Windows only afaik, issue around file path normalization

**Comment by bpasero** [comment]
Yeah for me no rendering works, even markdown preview.

**Comment by icyJoseph** [comment]
Markdown preview as well as REST client preview of responses are both failing.
