### ISSUE TITLE
Breadcrumb selection in picker is not easy to see 

### ISSUE THREAD

**Issue by sambhare** [Microsoft/vscode#58206]
Issue Type: <b>Bug</b>

1. Choose Visual Studio Light or Visual Studio Light+ as theme
2. Open a file
3. Focus breadcrumbs (Ctrl+Shift+;)
4. Press the down arrow to navigate thru the breadcrumbs
Exactly which item is selected in the picker is too hard to see. (e.g. See "TextEncoder" below.)

![screenshot_2018-09-07_11-39-10](https://user-images.githubusercontent.com/11561830/45229928-48707180-b295-11e8-97d2-de887cc63922.png)

(This issue happens in the latest release as well as insiders.)

VS Code version: Code - Insiders 1.28.0-insider (a3f9f2e7240106aeec2f1d4bc03d7876bd42e2e4, 2018-09-07T05:22:14.915Z)
OS version: Linux x64 4.15.0-33-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2388)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.71GB (0.58GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders --unity-launch|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by sambhare** [comment]
@jrieken Just noticed that yes, explorer tree has same colors. Didn't even realize this was a feature on the explorer tree as I had never "seen" the light blue selection background against the light gray background. I would say this is even a bug on the explorer tree.

For now I have worked around it by setting `"breadcrumbPicker.background": "#fff"`

**Comment by misolori** [comment]
I have a PR (https://github.com/Microsoft/vscode/pull/58229) that will slightly brighten the background color of the breadcrumb picker (it will match the picker background color):

| Before | After|
|---|---|
| ![image](https://user-images.githubusercontent.com/35271042/45313002-7bf40b80-b4e2-11e8-86d7-3e71e4d3e08e.png) | ![image](https://user-images.githubusercontent.com/35271042/45313010-7eeefc00-b4e2-11e8-8b72-cada24ad154a.png)

This list selection color (`list.focusBackground`) is used in a lot of different places (it's the list widget, I believe) and there are multiple text colors that are used in conjunction with this state that need to pass the color contrast ratio. If we ever update this color we'll need to do a pass of those various states.

**Comment by sambhare** [comment]
@misolori Thanks for looking into this. In your screenshots, I really can't tell which colors have been changed between the Before and After?

**Comment by sambhare** [comment]
If I set ""list.focusBackground": "#add6ff", (the same color as the selection background for text), things look good. As a bonus, the contrast improves everywhere "list.focusBackground" is used, including the explorer tree.  

![screenshot_2018-09-11_09-03-39](https://user-images.githubusercontent.com/11561830/45361970-9d67fc80-b5a1-11e8-8513-c87dc437430b.png)

**Comment by misolori** [comment]
@sambhare thanks for taking a look at this, really appreciate it! 

The `list.focusBackground` is part of the list widget, which that is used in several places (explorer, outline, quick pick, breadcrumb, etc.). The challenge we face is getting all of the colors to work well together while still passing the color contrast ratio for accessibility. Here's a screenshot of the variants:

![image](https://user-images.githubusercontent.com/35271042/45396367-08d8bb00-b5f0-11e8-9ca5-b35e4d1df619.png)

While I do like that `#c7e3ff` has great contrast on the breadcrumbs, there's a few areas (updated, filtered) where the colors don't pass:

<img width="50%" src="https://user-images.githubusercontent.com/35271042/45396395-3c1b4a00-b5f0-11e8-91fa-441ca623e363.png">

I'll definitely keep this in mind while I find the right color that works across the various uses of the list widget, appreciate you taking a look!

**Comment by misolori** [comment]
This is now fixed in master
