### ISSUE TITLE
Slow performance when running through RDP

### ISSUE THREAD

**Issue by simra** [microsoft/vscode#58207]
Hi, I'm experiencing significant latency using VS Code (both release and insiders builds) over RDP.  It doesn't seem to be specific to any particular file type or extension- the window is just slow to load and render, and once loaded all keyboard/mouse events take a long time to trigger any response.  I don't see the issue locally and I don't see the issue with other remote apps (eg visual studio).  I can repro the issue on multiple remote machines (same client, however- I will also reboot the client and report back if it makes a difference).

  nbVersion: 1.27.1 (user setup)
Commit: 5944e81f3c46a3938a82c701f96d7a59b074cfdc
Date: 2018-09-06T09:21:18.328Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Steps to Reproduce:

1. Install latest builds of VS code and use them (release and insiders).
2.

Does this issue occur when all extensions are disabled?: Yes

**Comment by simra** [comment]
for completeness, rebooting the client machine did not resolve the issue.

**Comment by simra** [comment]
I was able to work around the issue using `code . --disable-gpu`
Both the remote machines I'm using have had GPU workloads in the last few days, but only one is actively running a workload. A reboot of the one without a workload did not resolve the issue, but I will also try a cold start of the machine.

**Comment by simra** [comment]
A quick follow-up on this: I encountered similar issues with chrome in the same configuration.  It would be good to get some corroborating reports of the issue, otherwise it may just be a transient driver or windows problem.  At this present moment Code and Chrome are behaving normally.  Feel free to close no repro if no other reports come in.

**Comment by blackn1ght** [comment]
I was able to resolve this by updating my GPU driver.  I no longer need to use the `--disable-gpu` flag on VSCode or Google Chrome.
