### ISSUE TITLE
Phontom-File

### ISSUE THREAD

**Issue by NachtmahrEDM** [Microsoft/vscode#58215]
Issue Type: <b>Bug</b>

## Symptome
C#-File of Unity-Project opens every time I start up visual code.
Even as I disabled any file cache, deleted the containing folder, it'll be still there, including it's contents.
It is shower as an open, but unsaved file. If I try to open the containing folder, VC crashes. Even if I start visual code using "code /my/nodejs/project" or similar, I'll always open another instance of code with this file. 

## Replication
1) Install Unity and create a new project
2) create a new unity-class.
3) Clode VC.
4) Delete Project and uninstall unity
5) Restart VC.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:34:20.517Z)
OS version: Linux x64 4.15.0-33-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1605)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 2, 1|
|Memory (System)|7.51GB (3.37GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
asciidoctor-vscode|joa|0.15.1
vscode-language-pack-de|MS-|1.26.3
vscode-docker|Pet|0.2.0
pdf|tom|0.3.0

</details>

**Comment by bpasero** [comment]
@NachtmahrEDM if a file is dirty we will always restore it. Can you close the file and try again?
