### ISSUE TITLE
Problems View: Indicate which errors come from tasks / problem matchers

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#58210]
**Problem**
JS/TS uses the same diagnostic identifier for errors from tasks and for errors from the editor. This can be confusing if you have a mismatched typescript version, as some errors will only show up in the editor or in the task run. Tracking down which error came from which source can be difficult

**Proposal**
Add an icon or other indicator in the problems list that indicates if a problem comes from a task / problem matcher vs the editor.

/cc @chrisdias

**Comment by dbaeumer** [comment]
We could also change the source here https://github.com/Microsoft/vscode/blob/master/extensions/typescript-language-features/package.json#L662 to a different value (e.g. `ts-task`. Being able to render a task diagnostic differently requires a bit on the diagnostic object to indicate this. Currently the error list doesn't know the source of a diagnostic besides the source string. 

I am happy to adopt a bit in tasks framework if available on the diagnostics.

**Comment by mjbvz** [comment]
@dbaeumer Wouldn't that cause the errors to not be de-deplicated correctly?

**Comment by dbaeumer** [comment]
@mjbvz they will still be dedup. There is an owner (used to dedup) and a source to render the source of a problem.

**Comment by sandy081** [comment]
Problems view just show the data it gets, It is no aware that they come from Editor or Build. This info has to be provided by the respective soruces.
