### ISSUE TITLE
Can't see font when open folders.

### ISSUE THREAD

**Issue by XsiSec** [Microsoft/vscode#58213]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/visual-studio-code.
I am running debian Stetch 9 with Openbox and font Tamsyn.

when I am running visual code and trying to open any folder I can't see any font only 'squares'.
In my user-settings file I have got:
{
    "workbench.startupEditor": "newUntitledFile",
    "workbench.colorTheme": "Material Theme",
    "workbench.iconTheme": "eq-material-theme-icons",
    "terminal.integrated.shell.linux": "/bin/bash",
    "terminal.integrated.fontWeightBold": "normal",
    "terminal.integrated.fontSize": 14,
    "editor.fontFamily": "'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'",
    "html.suggest.angular1": true,
    "html.suggest.html5": true
   
}
though still can't see any font for the folders:
see attached image
![2018-09-07-201151_3840x1080_scrot](https://user-images.githubusercontent.com/17006430/45235869-7e841480-b2da-11e8-9920-86ad22087ed2.png)

Thank you

**Comment by Tyriar** [comment]
This looks to be an OS/display manager issue. That UI is provided by the OS, not Electron.
