### ISSUE TITLE
Cannot run extension tests from vscode workspace

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#58214]
Issue Type: <b>Bug</b>

1. Open vs code folder in vscode
1. Try running the `VS Code Tokenizer Test` launch config

**Bug**
See popup with:

```
__sessionId not found on configuration
```

Also applies to emmet, markdown, and typescript tests

VS Code version: Code - Insiders 1.28.0-insider (a3f9f2e7240106aeec2f1d4bc03d7876bd42e2e4, 2018-09-07T05:12:19.624Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 5, 5|
|Memory (System)|16.00GB (0.21GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_6407708|
|Screen Reader|no|
|VM|18%|

</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.10
color-info|bie|0.5.0
comment-tagged-templates|bie|0.2.0
emojisense|bie|0.4.1
folder-source-actions|bie|0.0.4
markdown-checkbox|bie|0.1.1
markdown-emoji|bie|0.0.7
markdown-image-size|bie|0.0.2
markdown-mermaid|bie|1.0.0
speech|bie|0.0.2
vscode-svgviewer|css|1.4.5
dart-code|Dar|2.18.0
vscode-eslint|dba|1.5.0
tslint|eg2|1.0.38
vscode-npm-script|eg2|0.3.5
vscode-memfs|jri|0.0.3
theme-karyfoundation-themes|kar|18.2.1
hg|mrc|1.2.3
vscode-azurefunctions|ms-|0.10.0
vscode-cosmosdb|ms-|0.8.0
vscode-language-pack-zh-hans|MS-|1.27.2
mssql|ms-|1.4.0
python|ms-|2018.8.0
azure-account|ms-|0.4.3
csharp|ms-|1.15.2
Go|ms-|0.6.89
vsliveshare|ms-|0.3.623
debugger-for-chrome|msj|4.10.0
angular2-inline|nat|0.0.17
vscode-docker|Pet|0.2.0
ruby|reb|0.20.0

(15 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Seems to work for me?

**Comment by mjbvz** [comment]
No but it doesn't repo if I disable all extensions. Seems to happen for basically any debug config

**Comment by mjbvz** [comment]
@chrisdias Looks like docker is causing this somehow. Repos if I have the extension enabled but not when I disable it

**Comment by roblourens** [comment]
Live share?

**Comment by mjbvz** [comment]
Actually never mind. With docker disabled, if I wait a moment then I start seeing the error again. Trying live share now

**Comment by mjbvz** [comment]
Yep live share. Upstream duplicate of https://github.com/MicrosoftDocs/live-share/issues/968

**Comment by sreevani12thapril** [comment]
I too get this error, are there any workarounds for this?

**Comment by weinand** [comment]
Use today's Insiders build or disable the Liveshare extension.
