### ISSUE TITLE
VS Code MarkDown Preview doesn't show as expected. 

### ISSUE THREAD

**Issue by zhangxiang1993** [Microsoft/vscode#58211]
- VSCode Version: 1.27.1
- OS Version: win10

Extensions I installed:
![image](https://user-images.githubusercontent.com/17421593/45235449-c761ac00-b28d-11e8-995a-7a90f2ee9f9c.png)

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/17421593/45235409-a305cf80-b28d-11e8-8b15-8a476426507b.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Does this reproduce with all extensions disabled?

Please share your markdown content (as text) as well

**Comment by zhangxiang1993** [comment]
Yes, this reproduce with all extension disabled

I copy-pasted my content here. 

# Purpose
    ImageTests are to test all kinds of scenarios that are related to images.

# Test Coverage

### 1. Devices

 > Which Device the Test  will use.

    * GPU
    * CPU

### 2. Evaluation Strategy
    * EvalutateAsync
    * EvaluateSync
    * MultipleEvaluations (TODO)
    * SwapChain (TODO)
    * Chain (TODO)

### 3. Output Binding Strategy
    *  Bound
        ```
        auto outputtensordescriptor = model.OutputFeatures().First().Current().as<ITensorFeatureDescriptor>();
		auto outputtensorshape = outputtensordescriptor.Shape();
		VideoFrame outputimage(BitmapPixelFormat::Rgba8, outputtensorshape.GetAt(3), outputtensorshape.GetAt(2));
		ImageFeatureValue outputTensor = ImageFeatureValue::CreateFromVideoFrame(outputimage);
        ```
    *  Unbound

### 4. Models
    a. [Input Image Metadata](https://github.com/onnx/onnx/blob/master/docs/MetadataProps.md)
        * No metadata provided (TODO)
        * BitmapPixelFormat
            * Bgr8
            * Rgb8
            * Gray8
            * Bgra8 (TODO)
            * Rgba8 (TODO)
            * yuv (TODO)
        * ColorSpaceGamma
            * sRGB
            * Linear (TODO)
        * NomialPixelRange
    * FNS-candy_Bgr8_freeDimInput
    * FNS-candy_Bgr8
    * FNS-candy_Rgb8
    * FNS-candy_Tensor
    * Model takes Gray8 image as input and also output image (TODO, Mnist outputs tensor)
    * 

### 5. Input Image Files
    * fish_720.png
    * fish_720_gray.png

### 6. Input Images Sources
    * FromImageFeatureValue
    * FromVideoFrame
    * FromGPUResource
    * FromCPUResource

### 7. InputPixelFormats
    * Bgra8
    * Rgba8
    * Gray8

**Comment by zhangxiang1993** [comment]
Yes, It is reproduced with all extensions disabled.
The attachment file is the markdown content.
[README.txt](https://github.com/Microsoft/vscode/files/2362287/README.txt)

**Comment by zhangxiang1993** [comment]
Hi @mjbvz 

The issue is not because of VS Code but because of bugs in my content. I will close this issue. Thank you and sorry for wasting your time. 

I copy pasted my content to several online markdown editors. And they show the same preview as shown in VSCode. And it turns out that it is because of the intent error in my content cause this problem.
