### ISSUE TITLE
Build failed on Linux Fedora 23 x86_64

### ISSUE THREAD

**Issue by helio-frota** [Microsoft/vscode#5821]
- VSCode Version: source HEAD
- OS Version: linux Fedora 23

Steps to Reproduce:

1. After clone the repository run:
2. ./scripts/npm.sh install --arch=x64

```
86131 silly lifecycle native-keymap@0.1.2~install: Args: [ '-c', 'node-gyp rebuild' ]
86132 silly lifecycle native-keymap@0.1.2~install: Returned: code: 1  signal: null
86133 info lifecycle native-keymap@0.1.2~install: Failed to exec install script
...
```

**Comment by bpasero** [comment]
@alexandrudima this seems to fail compiling native-keymap.

**Comment by alexandrudima** [comment]
@helio-frota Have you installed [all the necessary prerequisites at the minimum specified versions](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source) ?

It is possible native-keymap fails because it is the first native node module encountered by npm.

**Comment by helio-frota** [comment]
@alexandrudima sorry:

python --version
Python 2.7.10
node --version
v5.11.0
npm --version
3.8.6
gcc --version
gcc (GCC) 5.3.1 20151207 (Red Hat 5.3.1-2)

**Comment by helio-frota** [comment]
@bpasero @alexandrudima thanks it worked with:

```
sudo dnf install libX11-devel.x86_64
```

**Comment by alexandrudima** [comment]
@helio-frota Thank you. I have updated the [wiki](https://github.com/Microsoft/vscode/wiki/How-to-Contribute) to make this clear:

![image](https://cloud.githubusercontent.com/assets/5047891/14820851/aa3d190c-0bc8-11e6-974f-678ab2b53089.png)
