### ISSUE TITLE
UriDisplayService is missing remote share path name

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode#58222]
Issue Type: <b>Bug</b>

1. Open file on remote smb share in VS Code. e.g. \\mysmb\folder\file.txt
2. Hover over editor tab or right click > copy path for said file.

Expected path:
\\\mysmb\folder\file.txt

Actual path: 
\folder\file.txt

VS Code version: Code - Insiders 1.28.0-insider (a3f9f2e7240106aeec2f1d4bc03d7876bd42e2e4, 2018-09-07T05:20:29.346Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (7.10GB free)|
|Process Argv|C:\Users\stbatt\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by isidorn** [comment]
The issue here was that I was ignoring the authority when registering the `file` formatter.
On remote share paths the authority is the first part of the path which should be displayed.
For local files the authority is empty so this case should also be covered.
uri.fsPath was always doing this [here](https://github.com/Microsoft/vscode/blob/e0f506eac8e754d5ebbf8e1e9b8b3ab1cc9aeda9/src/vs/base/common/uri.ts#L542)

**Comment by msftrncs** [comment]
@isidorn , not sure this is fixed yet.  Using:

```
Version: 1.28.0-insider (user setup)
Commit: 2558a72d6902015b142ef45c57b664ce1f09e03f
Date: 2018-09-21T05:19:52.215Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

I now see the server name when the path to files are shown, but if I copy the path, the path reads without the leading `\\` so its still not a complete path.  Also, maybe because of this, the 'compare with saved' still doesn't work for files on UNC paths.

**Comment by msftrncs** [comment]
the error message I get, when comparing with saved is actually still fails to show the server name, so this may be a different but maybe related issue:

```
Unable to open 'TheBigTestFile.ps1 (on disk) ↔ TheBigTestFile.ps1': File not found (file:///User Documents/Carl/PowerShell Scripting/VS Code Language Syntax/sample scripts/TheBigTestFile.ps1).
```
`User Documents` is the share name, the server name is completely gone.

**Comment by isidorn** [comment]
@sbatten can you please verify if this is fixed
@msftrncs compare with is an unrelated bugs, please file new issue. Copy path should I will look into fixing

**Comment by sbatten** [comment]
@isidorn it now shows the full path but in the form "mysmb\folder\file.txt" which is strange because you can't copy and `cd` to that path. I would expect the path to maintain the leading`\\`

**Comment by ThubLives** [comment]
This doesn't seem to be fixed, only slightly less broken.  I just tried with the Insider build and I get `server\share\file.ext` -- which is not a valid UNC path -- instead of `\\server\share\file.ext`.  Should this be issue be re-opened?

**Comment by sbatten** [comment]
@ThubLives the latest fix is not yet available in insiders. Should be in the next build.

**Comment by msftrncs** [comment]
Got the latest insiders, path now shows server with \\, copy path includes it as well.   'compare with saved' was not affected by this fix.

**Comment by isidorn** [comment]
@msftrncs thanks for trying it out, adding verified label
