### ISSUE TITLE
code helper process

### ISSUE THREAD

**Issue by alexhidalgo** [Microsoft/vscode#58221]
Issue Type: <b>Bug</b>

code helper process CPU is 99%. unable to edit docs.
happens on every re-start of vscode

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:14:32.385Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (3.20GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
bracket-pair-colorizer|Coe|1.0.59
vscode-eslint|dba|1.5.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
highlight-matching-tag|vin|0.4.4
vim|vsc|0.16.3

</details>

**Comment by mjbvz** [comment]
Please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information. Share the output of `code --status`

**Comment by alexhidalgo** [comment]
[CPU-20180907T210838.247Z.cpuprofile.txt](https://github.com/Microsoft/vscode/files/2362536/CPU-20180907T210838.247Z.cpuprofile.txt)

**Comment by mjbvz** [comment]
Can you also please share the output of `code --status` as described here: https://github.com/Microsoft/vscode/wiki/Performance-Issues#visual-studio-code-is-consuming-a-lot-of-cpu

**Comment by mjbvz** [comment]
Closing as we need the process status information to investigate this
