### ISSUE TITLE
Crash collection steps do not work on Windows Server Core

### ISSUE THREAD

**Issue by pjh** [Microsoft/vscode#58233]
This is a bug for the wiki page https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues.

I'm experiencing a VSCode crash on Windows Server version 1803, which is a Core-only configuration (no desktop). After reporting my issue (https://github.com/Microsoft/vscode/issues/51504) I was directed to collect a crash dump by following the steps on https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues. I successfully downloaded and installed DebugDiagx64.msi, which put a number of files under `C:\Program Files\DebugDiag\`. If I cd to that directory in a command prompt running as a non-Administrator and run "DebugDiag.Collection.exe 2 Collection" I get the following error and the collection window does not appear.

![debugdiag-error](https://user-images.githubusercontent.com/280787/45248262-b9c71900-b2c3-11e8-8bd6-a2cfc97fb078.png)

Curiously, when I try to run that command as an Administrator in either cmd or PowerShell, nothing happens at all. I tried this on Windows Server 2016 and when I run the command the debug collection windows appears as expected.

I noticed that the debug tool [webpage](https://www.microsoft.com/en-us/download/details.aspx?id=49924) says it's supported on Windows Server 2012 but not Windows Server 2016 or beyond. Perhaps https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues should offer special guidance for those Windows versions.

**Comment by bpasero** [comment]
Thanks for letting us know, if someone has ideas how to collect crash information on Windows Core, please update this issue. Meanwhile I will close it as it is unrelated to VSCode.
