### ISSUE TITLE
Opening recent folders in a new window while holding 'Ctrl' key doesn't work unless Ctrl key is released and reheld

### ISSUE THREAD

**Issue by tehlordvortex** [Microsoft/vscode#58235]
Issue Type: <b>Bug</b>

Steps to Reproduce:
 - Open VS Code
 - Type "Ctrl+R"
 - Select a folder with the keyboard while still holding Ctrl

Expected Result: VS Code opens the folder in a new window (This was the behaviour in previous versions)
Actual Result: VS Code opens the folder in the same window.

Additional Information: If I release Ctrl after the popup, then hold it again while selecting a folder, it opens the folder in a new window.

Does this occur when all extensions are disabled?: Yes.

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:47.222Z)
OS version: Linux x64 4.15.0-33-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1926)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|7.59GB (0.46GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
lorem-ipsum|Tyr|1.2.0
QML|bbe|1.0.0
love|bsc|0.3.6
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
vscode-css-modules|cli|0.2.3
bracket-pair-colorizer|Coe|1.0.59
dart-code|Dar|2.18.0
flutter|Dar|2.18.0
vscode-eslint|dba|1.5.0
tslint|eg2|1.0.38
vsc-material-theme|Equ|2.4.2
prettier-vscode|esb|1.6.1
php-debug|fel|1.12.5
php-intellisense|fel|2.3.5
php-pack|fel|1.0.2
discord-vscode|icr|2.9.0
vscode-styled-components|jpo|0.0.21
graphql-for-vscode|kum|1.12.1
Kotlin|mat|1.6.0
dotenv|mik|1.0.1
vscode-apache|mrm|1.1.1
python|ms-|2018.7.1
cpptools|ms-|0.18.1
csharp|ms-|1.15.2
Go|ms-|0.6.89
debugger-for-chrome|msj|4.9.1
php-docblocker|nei|1.6.0
vetur|oct|0.12.6
laravel-blade|one|1.18.0
vscode-docker|Pet|0.1.0
material-icon-theme|PKi|3.5.3
quicktype|qui|12.0.40
sass-indented|rob|1.4.9
laravel-5-snippets|sac|2.0.1
vscode-spotify|shy|2.6.1
ayu|tea|0.16.0
vscode-react-native|vsm|0.6.16

(7 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
Reproduces for me and probably is a regression from the move to the quick pick widget.
