### ISSUE TITLE
Intellisence can't work in unity3d when double click a symbolic link c# file.

### ISSUE THREAD

**Issue by DFVSQY** [Microsoft/vscode#58246]
- VSCode Version: 1.27.1
- OS Version: win10 pro x64

Steps to Reproduce:

1. Create an empty unity3d project and create a symbolic link c# file to point other location.
2. Set the vscode as the default editor, then double click the c# file and it will be opened, but the c# file does't appear any intellisence tip.
Note: if I set visual studio 2017 as the default editor, it works well.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by calebeaires** [comment]
Same here with Angular. 

VSCode Version: 1.27.1
OS Version: MacOS 10.13.6

Steps to Reproduce:

1. Create an empty angular 6 project: `ng new project`;
2. Try to get intellisense from reserved words of Angular 6
3. No intellisence

**Comment by mjbvz** [comment]
File this against the c# extension
