### ISSUE TITLE
title bar when using window.nativeTabs on MacOS doesn't respect Dark Mode setting

### ISSUE THREAD

**Issue by nreilly** [Microsoft/vscode#58240]
- VSCode Version: Version 1.27.1 (1.27.1)
- OS Version: 10.14 Beta (18A384a)

Steps to Reproduce:

1. Run Mojave (10.14)
2. Enable Dark Mode (System Preferences > General > Appearance: Dark
3. Enable window.nativeTabs in VSCode
4. Expect dark title bar 
5. Get sad when it's light

Does this issue occur when all extensions are disabled?: Yes

**Comment by nreilly** [comment]
I don't think it is a duplicate as this is specific to supporting the dark mode feature introduced in 10.14 on MacOS

**Comment by bpasero** [comment]
@nreilly can you share a screenshot?

**Comment by fakebanana** [comment]
Here's a screenshot
![vscode doesn t support dark mode](https://user-images.githubusercontent.com/2114420/45731819-6a2bfb80-bba7-11e8-945a-4569b0893758.png)

**Comment by aziz** [comment]
This is not a duplicate and it's a real issue

**Comment by dlake89** [comment]
Just confirmed this also. I added custom colors for the titlebar and they did not work until I changed nativeTabs to false. This was running the non-beta version of Mojave.

**Comment by mssngr** [comment]
I would also like to see this gain traction. The white tabs on the dark interface is really distracting.

**Comment by alessandrodimarco** [comment]
https://github.com/Microsoft/vscode/issues/59283
