### ISSUE TITLE
Change the minimize, maximize, close buttons to Linux default.

### ISSUE THREAD

**Issue by avi3333** [Microsoft/vscode#58243]
Hi,
I just love the new custom menu bar feature in vs code. But I use a Linux machine and when I enable this custom menu bar feature, the minimize, maximize, close icons looks like windows default icons. It would be great if you guys change the icons to Linux default for the Linux edition.
Regards,
Avi

**Comment by m-thorsen** [comment]
There is no "Linux default" for the title bar. It would have to follow the system's GTK3 theme as well as respect whether to show min/max/close buttons and on which side.

Might be a bigger task than is feasible at the moment.

**Comment by sbatten** [comment]
As @m-thorsen indicates, since there is no Linux default, this is not something we intend to address and one of the reasons we are not making it the default experience for Linux currently. There is a separate issue regarding the icon location that is under consideration.

**Comment by marvinside** [comment]
A config option like window.titlebarBarButtonLayout with "left" and "right" would be nice.
For Auto detection, the command "gsettings get org.gnome.desktop.wm.preferences button-layout" can be used on gnome Desktops.

**Comment by rhcarvalho** [comment]
As per #65608, version 1.32 will make the native title bar the default on Linux. Using the custom title bar will still be possible.

https://code.visualstudio.com/docs/setup/linux#_using-the-custom-title-bar
