### ISSUE TITLE
Consider providing Uri.tryParse instead of console.warn-ing on schemeless URI

### ISSUE THREAD

**Issue by TomasHubelbauer** [Microsoft/vscode#58250]
[I haven't found related issues](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+tryParse+is%3Aopen), but there is a related ticket #56108, see below.

Currently, `Uri.parse` will `console.warn` if the string used to create it doesn't contain a scheme:

https://github.com/Microsoft/vscode/blob/ed1cd5130794db3381c558fc2fc3c51dee6c2b44/src/vs/base/common/uri.ts#L19

The documentation for `Uri.parse` used to say it will throw:

https://github.com/Microsoft/vscode/commit/699d778579995f2e423feef07437b275f4178c49#diff-158dcbfd31a2238ddd6a89b8a4a23316L1244

And it did as evidenced by the commented out `throw` statement right above the previous line:

https://github.com/Microsoft/vscode/blob/ed1cd5130794db3381c558fc2fc3c51dee6c2b44/src/vs/base/common/uri.ts#L18

This seems to have been changed by @jrieken in reference to #56108. Unfortunately, no longer throwing on this and instead printing a warning has an unfortunate side effect of no longer being able to use `Uri.parse` to determine if something is indeed a URI.

```ts
try {
    uri = Uri.parse(value);
} catch (error) {
    // not a URI
}
```

I used this mechanism to be able to use the `Uri` class and see if a URI is a non-file URI, or a file URI and then I already have the instance to pass to other VS Code APIs or it is something like `./README.md` which means I need to further process it to make it into a URI for VS Code APIs.

Now that this ability has been removed, parsing the URI is pushed on me where I have to repeat the work which used to be done by VS Code and risk inconsitency.

Hence I'd like to request for either this throw/warn behavior be reverted or (which I feel like is a better option) for a new method, `tryParse` to be provided, which would allow extension developers to do what that `try`-`catch` above did, but nicer.

We already have [`_validateUri`](https://github.com/Microsoft/vscode/blob/ed1cd5130794db3381c558fc2fc3c51dee6c2b44/src/vs/base/common/uri.ts#L14) which should make this possible, `tryParse` would essentially be `parse` but instead of returning the URI it would return a boolean based on whether `_validateUri` threw or not.

**Comment by jrieken** [comment]
> Now that this ability has been removed, parsing the URI is pushed on me where

That's not correct, we have never complained about missing schemes and that's the issue. We now want to throw an error when the scheme is missing but there is high potential for carnage. That's why we have a warning for a (long?) while before we make it an error.

**Comment by TomasHubelbauer** [comment]
I see, I didn't realize my code wasn't actually checking for valid issues because I had extra check for safety on if `scheme === null` just in case because I didn't looked into enough detail into if it actually throws, I just assumed it did.

I am happy to hear it will start throwing at some point in the future.

**Comment by KamasamaK** [comment]
So I take it based on the non-action here that we are expected to use a try/catch around `Uri.parse` instead of have something (like a `Uri.validate`) available in the public API. Is that correct?

**Comment by jrieken** [comment]
> here that we are expected to use a try/catch around Uri.parse instead of have something

Yes, that was always the case and inline with other URI/URL implementations.
