### ISSUE TITLE
Breakpoint doesn't move to original place after undoing.

### ISSUE THREAD

**Issue by zwuis** [Microsoft/vscode#58255]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Open a folder in the sidebar.
2. Create a file named "test.cpp" (or other source file of programming language).
3. Type code in random.
4. Set a breakpoint in line 3.
5. Select line 2 to line 4, then delete it.
6. Undo.
7. The breakpoint move to another place.

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:10.934Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G2020 @ 2.90GHz (2 x 2893)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.41GB (1.17GB free)|
|Process Argv|C:\Users\Mike\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.59
vsc-material-theme|Equ|2.4.2
code-runner|for|0.9.4
vscode-clang|mit|0.2.2
vscode-language-pack-zh-hans|MS-|1.27.2
cpptools|ms-|0.18.1
color-highlight|nau|2.3.0
indent-rainbow|ode|7.2.4
vscode-icons|rob|7.25.0
trailing-spaces|sha|0.2.11

(2 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Agree that this is happening. However will not fix due to it being a corner case and how we have currently techincaly solved this.
