### ISSUE TITLE
View lost when switch wrap text mode

### ISSUE THREAD

**Issue by tdchien** [Microsoft/vscode#58254]
Issue Type: <b>Bug</b>

Today I got a problem, that is lost view when switch wrap text mode. View should be keep at line where we're working. Please check this screenshot 
![image](https://lh3.googleusercontent.com/-XQt-00L2bPU/W5O-wAt0JpI/AAAAAAAAAv0/OYShADhjiVswicktoxcpgtsUwtJe5xASQCHMYCw/s0/2018-09-08_19-21-08.gif)

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:18.328Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.91GB (0.45GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (59)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.0.3
copy-relative-path|ale|0.0.2
alignment|ann|0.3.0
random-string-password-generator|bib|1.0.1
unique-lines|bib|1.0.0
laravel-blade|cjh|1.1.2
goto-documentation|cxf|0.0.1
vscode-quick-select|dba|0.2.6
vscode-faker|dee|1.3.0
javadebugger|don|0.1.5
xml|Dot|2.3.2
simple-alignment|ear|0.0.5
vscode-html-css|ecm|0.2.0
EditorConfig|Edi|0.12.4
vscode-npm-script|eg2|0.3.5
LogFileHighlighter|emi|2.4.1
vscode-great-icons|emm|2.1.41
vs-code-xml-format|fab|0.1.5
php-debug|fel|1.12.5
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
beautify|Hoo|1.4.2
rest-client|hum|0.19.1
ftp-simple|hum|0.6.7
composer|ika|0.7.1
phpcs|ika|1.0.5
mysql-syntax|jak|1.3.1
vscode-text-pastry|jkj|1.2.0
php-cs-fixer|jun|0.1.85
auto-comment-blocks|kev|1.0.1
vscode-phpfmt|kok|1.0.30
sshextension|kon|0.3.1
expand-region|let|0.1.2
php-symbols|lin|2.1.0
twig-language|mbl|0.2.9
twig-language-2|mbl|0.3.1
php-namespace-resolver|Meh|1.1.0
code-beautifier|mic|2.1.0
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
vscode-apache|mrm|1.1.1
sublime-keybindings|ms-|4.0.0
debugger-for-chrome|msj|4.10.0
php-docblocker|nei|1.6.0
editorconfiggenerator|nep|0.2.1
psibit-vscode-favorites|Psi|0.0.1
nginx-formatter|ray|0.0.4
partial-diff|ryu|1.4.0
vscode-workspace-switcher|sad|1.9.0
code-settings-sync|Sha|3.1.2
vscode-nginx|sha|0.5.0
vscode-fileutils|sle|2.10.3
laravel-goto-controller|ste|0.0.4
html-preview-vscode|tht|0.1.1
selectline-statusbar|tom|0.0.2
shell-launcher|Tyr|0.2.0
highlight-matching-tag|vin|0.4.4
bootstrap-3-snippets|wcw|0.1.0
change-case|wma|1.0.0

</details>

**Comment by mjbvz** [comment]
Does this still occur when all extensions are disabled?
