### ISSUE TITLE
Cannot click relative paths in terminal

### ISSUE THREAD

**Issue by StephenHillAtWork** [Microsoft/vscode#58256]
Issue Type: <b>Bug</b>

Run a compiler on a file with an error, and hold down the Alt button and click on the pathname. Nothing happens.

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:18.328Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|31.89GB (23.46GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
rainbow-brackets|2gu|0.0.6
vscode-whitespacer|dee|1.0.0
EditorConfig|Edi|0.12.4
CppSnippets|har|0.0.13
JSDocTagComplete|Hoo|0.0.2
MagicPython|mag|1.0.12
python|ms-|2018.8.0
cpptools|ms-|0.18.1
vscode-clearcase|Ope|1.12.1
trailing-spaces|sha|0.2.11
vscode-hexdump|sle|1.6.0
addDocComments|ste|0.0.8
python|tht|0.2.3
comment-snippets|Tob|0.2.0

</details>

**Comment by PsychoXIVI** [comment]
Same for me, just updated: I was thinking "ok fine update", then there my favorite functionality doesn't work...

**Comment by PsychoXIVI** [comment]
Related:
* There was updates for `xtermjs` addons ([`search`](https://github.com/xtermjs/xterm.js/tree/master/src/addons/search) and [`webLinks`](https://github.com/xtermjs/xterm.js/tree/master/src/addons/webLinks)) which is used in termial panel.
* `webLinks` is used in [`TerminalInstance`](https://github.com/Microsoft/vscode/blob/release/1.27/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts) with [`TerminalLinkHandler`](https://github.com/Microsoft/vscode/blob/release/1.27/src/vs/workbench/parts/terminal/electron-browser/terminalLinkHandler.ts) which is used to find file paths (and lines).

I bet @Tyriar can fix it ;F 

It looks like there is problem with current working directory:
Full paths are working (i.e. on Windows `E:/Some/main.cpp`), but relative aren't. There is [suspicious looking TODO comment](https://github.com/Microsoft/vscode/blob/release/1.27/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L307)... :C

**Comment by Tyriar** [comment]
@PsychoXIVI wow, nice investigation! @octref noticed links not working but we couldn't repro after that, this being a race condition makes sense as to why we couldn't repro so easily. I've definitely seen it before as well.

A PR would be awesome if you can put it together quick, this might go in the recovery build that we will probably release next week so if you can put a fix together in the next couple of days that would be best.

I think the best and easiest fix here is use `TerminalInstance. processReady` and set `initialCwd` on `TerminalLinkHandler`, and probably remove it from the constructor since it's not very useful there.

**Comment by PsychoXIVI** [comment]
We can propably revert https://github.com/Microsoft/vscode/commit/4ed24e070ab4bf4995af829e5cfaabcf01ff4d45 to make it work, since its looks like this commit doesn't fixes #57612. 

#57612 is still an issue:
![image](https://user-images.githubusercontent.com/23557839/45259242-317e6c00-b3c8-11e8-8108-f0d083ee2d3c.png)

And this feature doesn't work because of that :C

**Comment by Tyriar** [comment]
@PsychoXIVI we only need the initial cwd to be set to fix this regression. Getting the actual cwd in realtime is another feature which is a bunch of work (mainly because it's tough on Windows currently).

**Comment by Tyriar** [comment]
@PsychoXIVI I think I'll put the fix together for this today as it will likely be included in 1.27.2, thanks again for the investigation!

**Comment by somewhatabstract** [comment]
Still not working for me after updating to 1.27.1 on macOS

**Comment by szhu** [comment]
Just tried out 1.27.2, the issue still exists. 1.26.x is also broken but 1.25.x works fine.

**Comment by Tyriar** [comment]
@szhu can you share a screenshot and text of the failing line?

**Comment by szhu** [comment]
![screen recording 2018-09-14 at 10 47 am](https://user-images.githubusercontent.com/1570168/45566499-a9ef8d80-b80b-11e8-9d8b-dbb1a6fb7939.gif)

```
.
./Music
./Music/.localized  ← Recognized
./.gnupg
./.CFUserTextEncoding  ← Recognized
./Pictures
./Pictures/.localized  ← Recognized
./.atom
./.atom/styles.less  ← Recognized
./.atom/.apm
./.atom/.apm/cool-trim
./.atom/.apm/sb-callsite
./.atom/.apm/asap
./.atom/.apm/sb-debounce
./.atom/.apm/disposify
./.atom/.apm/sb-react-table
./.atom/.apm/loose-envify
./.atom/.apm/ms
./.atom/.apm/atom-package-deps
```

**Comment by Tyriar** [comment]
@szhu folders never worked. https://github.com/Microsoft/vscode/issues/29499

@somewhatabstract works for me:

<img width="482" alt="screen shot 2018-09-14 at 12 25 41 pm" src="https://user-images.githubusercontent.com/2193314/45570930-6dc32980-b819-11e8-9237-a9b7abe326b3.png">

**Comment by somewhatabstract** [comment]
It appears to be linked with resizing.

![terminallinks](https://user-images.githubusercontent.com/1266297/45572213-49257c80-b82e-11e8-8b61-78578022fdd6.gif)

**Comment by Tyriar** [comment]
@somewhatabstract that's an unrelated bug that should get fixed with https://github.com/Microsoft/vscode/issues/23688

**Comment by b00f** [comment]
It worked for me before, Now it is disabled.

**Comment by Tyriar** [comment]
@b00f did you update to 1.27.2? Please report a new issue if so.

**Comment by b00f** [comment]
@Tyriar Thanks. It is fixed in this version. Hopefully you have integration test for this feature then it won't be an issue in later versions.
