### ISSUE TITLE
wsl apps executable

### ISSUE THREAD

**Issue by edwinhuish** [Microsoft/vscode#58251]
**I found in win10 can run WSL apps with command  "wsl" like below ( in CMD and POWER SHELL )** 

![image](https://user-images.githubusercontent.com/5207925/45253036-e9912200-b392-11e8-9cc9-2367bd419f67.png)

![image](https://user-images.githubusercontent.com/5207925/45253040-00d00f80-b393-11e8-8b5b-5975181e784a.png)

** When I set the plugin's executablePath, as ``` "php.validate.executablePath": "wsl php" ``` , VSCODE return the error like below. **

** Is there any way to support using WSL apps? **
![image](https://user-images.githubusercontent.com/5207925/45253076-9f5c7080-b393-11e8-8d5f-baf043b6b030.png)

**Comment by roblourens** [comment]
See https://github.com/Microsoft/vscode/issues/29194
