### ISSUE TITLE
VS Code crashing several time

### ISSUE THREAD

**Issue by zbandhan** [Microsoft/vscode#58262]
- VSCode Version:  1.27.1
- OS Version: Linux Mint 18.3

Steps to Reproduce:

1. while typing php code fast
2. happening in php files

Other issues
1. lag in typing performance in php
2. intelisense slow in php

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Are you using any PHP extensions? Does it happen when starting with `--disable-extensions`?

**Comment by zbandhan** [comment]
Yes I'm using "PHP Intelepense" a php extension and the crashing is occurring still when the extension is disabled. Vscode is not crashing suddenly but hanging while typing fast and a bit later showing the following dialog box

![crashing](https://user-images.githubusercontent.com/10957285/45304137-44647e00-b539-11e8-9fd1-4d6392fa55ad.png)

Sometimes the typing performance is lagging like the robot dance and as soon as hanging the editor with that dialog box.

`--verbose` gives me the following error.
[main 8:28:57 PM] [VS Code]: detected unresponsive
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

**Comment by roblourens** [comment]
Are you just disabling that one extension? Can you try disabling all extensions? This just helps narrow it down.

When the window hangs, can you check whether there is a process using lots of CPU, and which one it is? https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by zbandhan** [comment]
No. I've checked the problem disabling all extensions at the same time but no luck.
You can see one of the CPU processes which is 25 and red color in the process explorer that is using lots of CPU and others are fine.

![cpu](https://user-images.githubusercontent.com/10957285/45313723-784b9d80-b551-11e8-92e4-e41855cd1543.png)

**Comment by zbandhan** [comment]
Yes it does only in PHP files to me and only in Version: 1.27.1. Other files are alright. 
Computer specs:

![computer](https://user-images.githubusercontent.com/10957285/45317870-12651300-b55d-11e8-94b9-836960c54b5e.png)

**Comment by zbandhan** [comment]
One more clearance, The problem occurs only where the PHP codes are nested with the HTML. Only plain PHP or HTML does not make any occurrence. Whenever I mix PHP and HTML at the same PHP file that I have to do for working with WordPress project, makes the issue.

**Comment by roblourens** [comment]
Could you try a couple more things:

Try disabling the builtin PHP support
- Search `@builtin` in the extensions viewlet
- Find PHP Language Features
- Right click, disable

If that doesn't help, maybe it could be related to the colorizer. If you change the file to plain text (click on PHP in the status bar, select Plain Text in the quickopen) is that any different?

**Comment by zbandhan** [comment]
Disabling "PHP Language Basics" solves the problem :+1:

**Comment by roblourens** [comment]
Thanks. Likely a tokenizer issue like https://github.com/Microsoft/vscode/issues/46907
