### ISSUE TITLE
It adds tab spaces and doesn't allow to change this!

### ISSUE THREAD

**Issue by t-zander** [Microsoft/vscode#58265]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Well, just try to write function() {
 something here
}
It also has to do with html tags and I am sure with many other templates.
Please look at lines 9, 10
Is there no way to change this
![image](https://user-images.githubusercontent.com/34350867/45257554-93cb7280-b3b0-11e8-89fd-940ba27ade91.png)
to this
![image](https://user-images.githubusercontent.com/34350867/45257555-9c23ad80-b3b0-11e8-8d31-8366bb4c989a.png)
After autosaving or saving second variant becomes frist. It's really annoying because I am get used to tabs style as it is displayed in the second image. I tried tabsize, space, 
I have changed my settings to 

> "editor.tabSize": 2,
> "editor.insertSpaces": false,
>  "editor.detectIndentation": false,
However still have this annoying behavior which makes code unconvenient.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Does this issue occur when all extensions are disabled?

**Comment by t-zander** [comment]
If I disable all extensions it's gone
