### ISSUE TITLE
Placeholders order

### ISSUE THREAD

**Issue by Capidunord** [Microsoft/vscode#58267]
Issue Type: <b>Bug</b>

I have two snippets (for latex documents) defined in latex.json snippets file : 
```
{
    "pth": {
		"prefix": "pth",
		"body": "\\pth{$1}$0"
	},
    "interval": {
		"prefix": "interval",
		"body": "\\itv{${1:left}}{${2:right}}{${3:left_value}}{${4:right_value}}$0"
	}
}
```

There is something I don't understand concerning placeholders order.

If I use the "interval" snippet alone, there is no problem : using TAB, I can switch placeholders in expected order : `1:left->2:right->3:left_value->4:right_value->0`.

But if I use the "pth"snippet, then, inside of this snippet, if I trigger the "interval" snippet, I would expect being able to browse placeholders in the same order than in the previous case, however it's not the case : the actual order is `1:left->2:right**->0->**3:left_value->4:right_value->0(from pth snippet)`

![vscode placeholders order](https://user-images.githubusercontent.com/16908020/45257781-0f76f080-b3ac-11e8-9c25-04fdb5c2f9d3.gif)

Is this a bug or is there something I did not understand ?

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:18.328Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.83GB (10.25GB free)|
|Process Argv|C:\Users\steph\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
latex-workshop|Jam|5.8.2
vscode-language-pack-fr|MS-|1.27.2
python|ms-|2018.8.0
csharp|ms-|1.15.2
autodocstring|njp|0.2.3
vscode-docker|Pet|0.2.0
ayu|tea|0.16.0

(1 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
Yeah, that order is actually quite weird...

**Comment by jrieken** [comment]
@Capidunord Thanks for reporting this! I have just pushed a fix and it will be available in tomorrows Insider build. Please give it a try: https://code.visualstudio.com/insiders/

**Comment by Capidunord** [comment]
Now working as expected in insiders build, many thanks !

**Comment by jrieken** [comment]
Thanks for using Insiders!
