### ISSUE TITLE
php date_add() api description is wrong

### ISSUE THREAD

**Issue by zealitude** [Microsoft/vscode#58260]
Issue Type: <b>Bug</b>
```
<?php 
   date_add();  // mouseover this function, it different from php.net
```
VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:14:32.385Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.51GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_1450338|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.4
vscode-file-peek|abi|1.0.1
vscode-angular2-files|ale|1.6.1
ng-template|Ang|0.1.10
tslint|eg2|1.0.38
sublime-keybindings|ms-|4.0.0
guides|spy|0.9.2

</details>

**Comment by roblourens** [comment]
Looks the same to me, what difference are you seeing?
