### ISSUE TITLE
Disabling extensions clears activity bar visibility preferences

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#58271]
Repro:

1. Install live share extension
2. Reload
3. Right click activity bar icon and hide live share
4. Disable live share extension
5. Reload
6. Enable live share extension
7. Reload

The live share activity bar entry will be visible. This may have been intentional but I believe the best experience is to only purge live share from the preferences when uninstalling the extension, not disabling.

**Comment by sandy081** [comment]
It is hard to know in the activity bar if an extension is uninstalled or disabled. 

Sorry this cannot be fixed.
