### ISSUE TITLE
Typescript: broken syntax highlighting for `import * as $`

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#58279]
- VSCode Version: v1.27.1
- OS Version: macOS v10.13.5

The following snippet of code is not properly highlighted, both under the "typescript" and "javascript" languages. The `as` keyword in `import * as $` should be red:

<img width="237" alt="screen shot 2018-09-09 at 05 51 54" src="https://user-images.githubusercontent.com/1812093/45260940-aa93b880-b3f4-11e8-87af-682216289d85.png">

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#665
