### ISSUE TITLE
js : and " mess

### ISSUE THREAD

**Issue by DeDuckProject** [Microsoft/vscode#5827]
- VSCode Version: 1.0.0
- OS Version: OsX El Capitan

Javascript does mess when has a : inside a string ("").

Steps to Reproduce:

1. type:
```javascript
matchQuery.find().then(function (results) {
		for (i=0;i<results.length;i++){
			notificationQuery.find().then(function (notifications){
				var j;
				for (j=0;j<notifications.length;j++){
					console.log('safeDeleteRoute notification result'+j);
					notifications[j].destroy();
				}
				res.destroy();
			});
		}
	},function(error){
		alert("Error: "+error.code + " " + error.message);
	});
```
2. notice the bad coloring on the last "alert" and how the last closing bracket connects to the after alert and not the one after the first line.
3. delete the : in the last alert and see how it is fixed.

**Comment by bpasero** [comment]
I can reproduce.

![image](https://cloud.githubusercontent.com/assets/900690/14820577/86906abe-0bc7-11e6-9cc2-a70e5534d961.png)

**Comment by brunnopleffken** [comment]
Is not the **:** inside quotes, and remove it doesn't fix it. Actually there's a bug when using "lower-than" symbol without spaces... This is the code @DeDuckProject posted, but indented (even with indentation, the issue persists):

<img width="497" alt="screen shot 2016-04-26 at 12 19 33" src="https://cloud.githubusercontent.com/assets/3427344/14823530/4965d854-0ba9-11e6-83a3-896d2596cb20.png">

With one space each side, the syntax highlight works fine throughout the code!
 
<img width="509" alt="screen shot 2016-04-26 at 12 22 13" src="https://cloud.githubusercontent.com/assets/3427344/14823690/ce6560b0-0ba9-11e6-85d8-ea79c8323514.png">

**Comment by brunnopleffken** [comment]
This is what's happening (animated GIF):

![untitled](https://cloud.githubusercontent.com/assets/3427344/14825368/fe25ed82-0baf-11e6-9fb3-b40eb1170f53.gif)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#156
