### ISSUE TITLE
Preserve folding state per file open/close

### ISSUE THREAD

**Issue by Amr1977** [Microsoft/vscode#58278]

**Comment by aeschli** [comment]
@Amr1977 Please give more details.
Add a small code sample, describe what you see and what you expect.

**Comment by Amr1977** [comment]
I just upgraded to latest vscode 1.27.1, the requested feature is now there, I was talking about preserving fold/unfold state for files between file open/close, meaning if I fold a section of a file and close that file then reopen the file I expect the folded part to keep being folded, I just retested it now and it is implemented.

Thank you very much for the brilliant job :+1:

**Comment by aeschli** [comment]
Thanks. We had that for a long time. Must have been a bug that this didn't work. If you have reproducible steps, please reopen.
