### ISSUE TITLE
Typings from npm package not being used in js files.

### ISSUE THREAD

**Issue by eparizzi** [Microsoft/vscode#58275]
Version: 1.27.1 (user setup)
Commit: 5944e81f3c46a3938a82c701f96d7a59b074cfdc
Date: 2018-09-06T09:21:18.328Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
Windows 10 Pro x64

Steps to Reproduce:

1. Create a simple javascript project.
2. Add a jsconfig.json
3. Install an npm package that includes its own typings (i.e. `styled-components`, `axios`)

Intellisense it now shown for the package. F12 on package name shows "No definitions found for ..."

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
How are you importing and referencing `styled-components`?

**Comment by emzero** [comment]
Does that matter?

When importing other packages (like react and react-dom) it doens't matter what I put in the first part of the import. As long as `from package-name` is there, VS is able to infer its typings.
![image](https://user-images.githubusercontent.com/412489/45320583-736af780-b519-11e8-8f02-0b3ed27a8c64.png)

In the sshot above VSCode is getting the react typings via ATA.  

Styled-components provides their own typings and the definition file is properly defined in its package.json, in the typings property.
![image](https://user-images.githubusercontent.com/412489/45320703-c5138200-b519-11e8-84e2-c3ee0042bca0.png)

But VSCode is unable to find them.
![image](https://user-images.githubusercontent.com/412489/45320734-de1c3300-b519-11e8-917e-439448b6db6c.png)

![image](https://user-images.githubusercontent.com/412489/45320746-e5dbd780-b519-11e8-9afc-fb404fc73b08.png)

**Comment by emzero** [comment]
This happens too with `axios`, which also includes its own typings.
![image](https://user-images.githubusercontent.com/412489/45320971-68fd2d80-b51a-11e8-881a-f9dab3628124.png)

It seems type definition are only searched in `node_modules\@types` and the folder where VSCode saves the types download via ATA.

**Comment by mjbvz** [comment]
I can't repo this in VS Code insiders. A few more questions

- Do you have a jsconfig or tsconfig in your project? 
- What version of styled components?
- Have you configured a workspace version of typescript at any point?

Please share a small example project if you are able to

**Comment by emzero** [comment]
-  Yes, I have a jsconfig file.
-  Latest version. Also it happens with axios.
-  Yes I have configured a workspace version of typescript, but for another project (saved in workspace settings, not user's).

[Here's the small project](https://github.com/emzero/vs-code-typings-not-working) I'm trying. I'm using the normal, not the insiders, version of VS Code.

**Comment by emzero** [comment]
On the other hand, the response from TSServer is:

```json
{

    "projectName":"d:/Desktop/vscode/jsconfig.json",
    "typeAcquisition":{
        "enable":true,
        "include":[
        ],
        "exclude":[
        ]
    },
    "compilerOptions":{
        "allowJs":true,
        "maxNodeModuleJsDepth":2,
        "allowSyntheticDefaultImports":true,
        "skipLibCheck":true,
        "noEmit":true,
        "target":2,
        "configFilePath":"d:/Desktop/vscode/jsconfig.json",
        "allowNonTsExtensions":true
    },
    "typings":[
        "d:/Desktop/vscode/node_modules/axios/index.d.ts"
    ],
    "unresolvedImports":[
        "axios"
    ],
    "kind":"action::set"
}
```

And while it lists the proper axios typings path, it also shows axios as "unresolverImports".

**Comment by mjbvz** [comment]
I still can't repo this on the latest VS code versions with TS 3.4.3:

![Screen Shot 2019-04-12 at 3 07 29 PM](https://user-images.githubusercontent.com/12821956/56068735-bfdb1780-5d34-11e9-8519-074f21483053.png)
![Screen Shot 2019-04-12 at 3 07 33 PM](https://user-images.githubusercontent.com/12821956/56068736-c073ae00-5d34-11e9-83f6-12207d4ec4c0.png)

Let me know if you still see this
