### ISSUE TITLE
Multilanguage for extensions

### ISSUE THREAD

**Issue by mc-hovanskiy** [Microsoft/vscode#58286]
Please add multilanguage for extensions.

**Comment by mjbvz** [comment]
Please explain what you mean. See [this guide](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions) on how to write a proper issue

**Comment by mc-hovanskiy** [comment]
We need to solve this problem: https://github.com/alefragnani/vscode-project-manager/issues/147

**Comment by mjbvz** [comment]
Take a look at this sample extension: https://github.com/Microsoft/vscode-extension-samples/tree/master/i18n-sample

**Comment by Inter-Net-Pro** [comment]
@mjbvz Please tell me the localization files should be in the root directory or in a separate folder to be stored?
