### ISSUE TITLE
Git works but does not show any commits (empty history)

### ISSUE THREAD

**Issue by frevds** [Microsoft/vscode#58289]
Issue Type: <b>Bug</b>

After some recent update the Source Control tab stopped showing commits. It is now completly empty, however, I can commit changes (those are shown), and there are no error messages in the Git console nor the developer tools. 
I disabled the GitLens extension but it had no effect. Using git 2.14.1.windows.1

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:18.328Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1505M v6 @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.86GB (19.50GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icons|rob|7.25.0

</details>

**Comment by eamodio** [comment]
@frevds The built-in vscode Git extension never provided a view of commits. If you were using GitLens, it does provide a repository explorer where you can see the history of branches, etc. In a somewhat recent release of GitLens, I moved all the GitLens explorers (views) into its own GitLens activity on the sidebar (if you were using the defaults). You can move each individual explorer that GitLens provides into other activities (i.e. Explorer, Source Control). It is easiest to control this by using the GitLens interactive settings editor (run `GitLens: Open Settings` from the command palette).

Hope that helps.

**Comment by frevds** [comment]
Oh. I wasn't aware of that, thanks for pointing that out and mentioning the settings. So what I was actually observing was a change in GitLens. I moved it back into the SourceControl tab. Will close this issue.
