### ISSUE TITLE
respect showUser flag in errors

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#5828]
#5644

* stepped around in a C# program that uses tasks
* eventually I got the error below

![screen shot 2016-04-26 at 14 55 51](https://cloud.githubusercontent.com/assets/1794099/14818768/1535d4ec-0bbf-11e6-874b-2c044afdb907.png)

**Comment by jrieken** [comment]
I see this when I press quickly, no idea if this is us or omnisharp

**Comment by isidorn** [comment]
This is coming from the debug adapter, please file it against the extension.

**Comment by jrieken** [comment]
@isidorn Why is rendered prominently my face? Is that extension?

**Comment by isidorn** [comment]
@jrieken we have the [showUser flag](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L535) but it might be in this case not respected. Due to this I have renamed and reopend the bug
