### ISSUE TITLE
选中多行文本时有异常表现 / Strange behavior when choosing multiline text

### ISSUE THREAD

**Issue by reserveword** [Microsoft/vscode#58283]
- VSCode Version:1.14.2
- OS Version:10.0.17134

Steps to Reproduce:

1.选中多行文本
2.当一行文本选中的部分后面还有字符,并且选中位置与上一行结尾齐平,就会出现异常表现.
Picture explains it better:
![2018-09-09_150831](https://user-images.githubusercontent.com/12995615/45262136-64197a80-b443-11e8-8ae0-4786829f2a52.png)
![2018-09-09_145351](https://user-images.githubusercontent.com/12995615/45262137-64197a80-b443-11e8-83bf-23e4fe61bb11.png)
The right end of chosen area is not smooth and has a zigzag.

Does this issue occur when all extensions are disabled?: Yes

**Comment by zwuis** [comment]
“string”后面的那块空白是换行符
That blank after “string” is line break

**Comment by mjbvz** [comment]
This is by-design. As @zwuis notes, the extra space is the newline character
