### ISSUE TITLE
When is Setting font at settings.json but Custom title bar and menus on MacOS High Sisrra  font not change

### ISSUE THREAD

**Issue by BeatsX** [Microsoft/vscode#58280]
Issue Type: <b>Bug</b>

I changed VS Code font,  top title bar and left menus  not change font.   

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:14:32.385Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 1|
|Memory (System)|16.00GB (7.73GB free)|
|Process Argv|/Users/dendi/Desktop/Softs/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
pug|ama|1.0.1
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.5.0
EditorConfig|Edi|0.12.4
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.6.1
vue-snippets-js-html-pug-razor|heb|0.0.3
vue-snippets|hol|0.1.9
beautify|Hoo|1.4.2
intellij-idea-keybindings|k--|0.2.25
vscode-pugbeautify|mrm|1.0.2
vscode-puglint|mrm|2.3.0
debugger-for-chrome|msj|4.10.0
vetur|oct|0.12.6
minapp-vscode|qiu|1.8.0
vscode-icons|rob|7.25.0
vue-vscode-snippets|sdr|1.3.0
code-settings-sync|Sha|3.1.2
language-stylus|sys|1.10.0
stylus-supremacy|thi|2.12.3
vscode-pug-template-literal|zok|0.1.1

(1 theme extensions excluded)

</details>

**Comment by BeatsX** [comment]
![image](https://user-images.githubusercontent.com/26688426/45261209-afc22900-b42f-11e8-853f-48b048dfe311.png)

**Comment by BeatsX** [comment]
![image](https://user-images.githubusercontent.com/26688426/45261224-2c550780-b430-11e8-825b-b2cc61121ffb.png)

**Comment by BeatsX** [comment]
Please help me, I have ocd

**Comment by sbatten** [comment]
@BeatsX the setting you have changed only affects the editor font. It is not currently possible to modify the font of the workbench as you want. There is an existing feature request open for this #519
