### ISSUE TITLE
Fix all providers (code cleanup) in VS Code

### ISSUE THREAD

**Issue by HamedFathi** [Microsoft/vscode#58284]
Hi

Based on great PR by @savpek for [Roslyn analyzers and code fixes](https://github.com/OmniSharp/omnisharp-roslyn/pull/1076) I asked a question about [How to apply all refactors](https://github.com/OmniSharp/omnisharp-roslyn/pull/1076#issuecomment-419408031) automatically by VS Code. (not by the user with choosing light bulb)

In other great explanation about how to refacting something in Visual studio @heejaechang described the ways [in here](https://github.com/OmniSharp/omnisharp-roslyn/pull/1076#issuecomment-419520998)

> just FYI. in VS there is 3 different mode of "fixing" issue
> one by one - user choose 1 light bulb (or diagnostic, or fixer whatever name you call it) and apply it
> fix all - user chooses 1 light bulb and says fix the same issue over whole document, project or solution.
> code cleanup - user chooses a document and says fix every issue on this document.
> difference is that
> (1) is the default. user choose 1 issue, and fix that issue only.
> (2) is user choose 1 issue and fix all occurnaces of the same issue over document, project or solution.
> (3) is user choose a scope first (document) and then fix all issues (which are multiple kinds of issues such as unused usings, simplify type names and etc) on that scope.
 
At the end of discussion, @DustinCampbell [guide me](https://github.com/OmniSharp/omnisharp-roslyn/pull/1076#issuecomment-419533299) this feature should exist in VS Code at first.

So, It would be great if VS Code supports all refacting functionality like VS especially fix all automatically.

**Comment by jrieken** [comment]
This is currently implemented by each extension individually, e.g. TypeScript has 'remove this unused declaration' or 'remove all unused declarations'. It might too late to make this a general concept...

**Comment by jrieken** [comment]
We will have that with the next release
