### ISSUE TITLE
Tearing(?) in embedded terminal

### ISSUE THREAD

**Issue by dfee** [Microsoft/vscode#58282]
- VSCode Version: Version 1.27.1 (1.27.1)
- OS Version: 10.13.6 (17G2208)

Steps to Reproduce:

1. use the embedded terminal for a while
2. encounter some form of tearing

Does this issue occur when all extensions are disabled?: Yes

<img width="191" alt="asdf" src="https://user-images.githubusercontent.com/262602/45261926-64246680-b3c0-11e8-9093-e3a52e1e350c.png">

**Comment by Tyriar** [comment]
Can you share your settings.json file?

**Comment by dfee** [comment]
```{}```

**Comment by dfee** [comment]
That's my settings.json file...

**Comment by Tyriar** [comment]
@dfee can you run with `"window.zoomLevel": 0` for a while and let me know if it repros?
