### ISSUE TITLE
Add API to detect when activeTextEditor is undefined because of a large file is active

### ISSUE THREAD

**Issue by qcz** [Microsoft/vscode#58290]
Currently when a large file (>50 Mb) is opened, it is not visible to extensions, and `vscode.window.activeTextEditor` is undefined. I've created an extension to filter large log files and came as a surprise that there is no way to distinguish whether there is really nothing is opened or a large file is active.

Please provide an API to detect this state, so extension authors will be able to show proper error messages, and maybe even provide the details of the file, so the extension can process it externally, if it wants it.

**Comment by alexandrudima** [comment]
I don't see how we can do this without breaking existing extensions.

`vscode.window.activeTextEditor` must point to a valid `TextEditor`, i.e. one that has a `document`. The `document` must be a valid one with correct text inside. Anything else will cause existing extensions to break (e.g. having `document` point to `null`).

We could try to make the value configurable and we could present a warning to the user.

**Comment by alexandrudima** [comment]
Actually, a good amount of discussion already has taking place in #31078, so let's track there.
