### ISSUE TITLE
Click to link in import CSS doesn't always work

### ISSUE THREAD

**Issue by dippas** [Microsoft/vscode#58296]
- VSCode Version: 1.27.1
- OS Version: Windows 10 Pro v1803 x64

**Steps to Reproduce:**

1. Create a partial file SCSS __partial.scss_
2. Import file partial **without extension**, something like:
`@import folder/partial`
3. Press `Ctrl+click` to follow the link to the partial file

**Desired Outcome:**
 
- **Always Open** the partial file

**Actual Outcome:**

- **Sometimes** Open the partial,
- Mostly the times throws an error 
> Unable to open _partial file-: File not found (file:_Absolute path to the partial file_) 

The only way to have the desired outcome is to have the extension `.scss`, [which is not mandatory in @import directive in Sass.](https://sass-lang.com/guide#topic-5)

[Video demonstrating the bug ](https://github.com/Microsoft/vscode/files/2364375/video-bug-partial.zip)

Does this issue occur when all extensions are disabled?: Yes

**Comment by octref** [comment]
@dippas Thanks, I learned about that SCSS feature from another issue: https://github.com/Microsoft/vscode/issues/58204#issuecomment-419717096. I'll track this issue over there and fix it this month.
