### ISSUE TITLE
Location of new file

### ISSUE THREAD

**Issue by hanpari** [Microsoft/vscode#58297]
After Ctrl+Shift + P + New file (or folder for the matter) new item is created somewhere in active folder structure. 

![obrazek](https://user-images.githubusercontent.com/7354817/45266052-61278580-b455-11e8-8ddd-61b9fca60e53.png)

This is sometimes not exactly what one would like. I suggest the new item textbox be it file or folder can be moved by arrow keys. With RIGHT arrow you would navigate higher (parent folder) in structure, LEFT lower in structure (Children folder). The  UP and DOWN for the same level navigation.

After new file or folder is in desired position, it can be confirmed as usual. Right now I have to navigate to correct place by mouse which takes my fingers from keyboard.

**Comment by isidorn** [comment]
Left and right are already taken to navigate inside the input box.
Thanks for the suggestion but not a big fan of this personally
