### ISSUE TITLE
Cut line and paste bug

### ISSUE THREAD

**Issue by MuseBoy** [Microsoft/vscode#58293]
Issue Type: <b>Bug</b>

* write 3 lines
  ```
  first line
  second line
  third line
  ```
* place cursor in the first line, use ctrl+x to cut the whole line
* place cursor at the end of the third line, use ctrl+v to paste it
* expect result:
  ```
  second line
  third linefirst line
  ```
* actual result:
  ```
  second line
  first line
  third line
  ```

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:47.222Z)
OS version: Linux x64 4.15.0-33-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2296)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|5.72GB (1.61GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.59
output-colorizer|IBM|0.1.2
dakara-foldplus|dak|1.3.1
vscode-markdownlint|Dav|0.20.0
vscode-eslint|dba|1.5.0
translation|dus|0.0.4
gitlens|eam|8.5.6
vscode-highlight|fab|1.2.8
code-runner|for|0.9.4
select-highlight-minimap|mde|0.0.8
markdown-shortcuts|mdi|0.8.1
vscode-language-pack-zh-hans|MS-|1.27.2
python|ms-|2018.8.0
cpptools|ms-|0.18.1
java|red|0.30.0
partial-diff|ryu|1.4.0
code-settings-sync|Sha|3.1.2
markdown-preview-enhanced|shd|0.3.5
markdown-all-in-one|yzh|1.6.0

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by MuseBoy** [comment]
@mjbvz yes

**Comment by dvdnhm** [comment]
You cut the line but expecting it to paste as a selection. Isn't it defy the purpose of cutting as a line.

I can see the need for this, so a secondary 'paste as selection' behavior with shift+ctrl+v shortcut would be nice

**Comment by alexandrudima** [comment]
The described behaviour is as designed
