### ISSUE TITLE
All extensions cannot be used after a period of startup

### ISSUE THREAD

**Issue by 1758231591** [Microsoft/vscode#58295]
Issue Type: <b>Feature Request</b>

It can be used at any time

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:18.328Z)
OS version: Windows_NT x64 10.0.17134

**Comment by mjbvz** [comment]
Closing as we need more information to investigate this
