### ISSUE TITLE
debug - sort order of threads isn't stable

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#5830]
#5644

* debug a C# program that uses two tasks
* have a breakpoint in one task action
* when hit step
* ⚡ the order of the containing thread in the call stack view isn't stable

![screen shot 2016-04-26 at 14 59 27](https://cloud.githubusercontent.com/assets/1794099/14818888/b77b9e8a-0bbf-11e6-8eaf-222e8b8640ce.png)

![screen shot 2016-04-26 at 14 59 36](https://cloud.githubusercontent.com/assets/1794099/14818891/badcffba-0bbf-11e6-953c-8d6f28305e4c.png)

**Comment by jrieken** [comment]
might be my bad cos I missed a build in dot net cli

**Comment by isidorn** [comment]
ok, let me know if you can repro. Also the thread order is coming from the adapter - so if you did not misbuilt then it is an issue in the c# debug adapter I believe

**Comment by isidorn** [comment]
There is nothing we can do here, as the threads are coming from the debug extension.
@jrieken let me know if you can repro and I will file a bug against the debug adapter extension
