### ISSUE TITLE
Empty debug viewlet picker

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#58308]
![image](https://user-images.githubusercontent.com/323878/45268037-20ffdd00-b42c-11e8-9630-22780875bb01.png)

- Disable extensions so the search process doesn't start when vscode starts (or break the search debug config by changing the port)
- Start the launch config "Search and renderer processes"
- As soon as the vscode window appears, open the developer tools so the launch config is disconnected
- Then the search process times out, and I see what's in the screenshot

I can still start debugging again, I'm not blocked

**Comment by isidorn** [comment]
@roblourens sorry for the slow responce I was on vacation.
Andre did a big refactoring of debug, can you still reproduce this in latest vscode inisders?

**Comment by roblourens** [comment]
Yes

**Comment by roblourens** [comment]
And when I click "disconnect" on the empty picker, I get this

![image](https://user-images.githubusercontent.com/323878/45635440-d698e480-ba59-11e8-9b65-3168c85895e6.png)

**Comment by isidorn** [comment]
@roblourens thanks Rob, this was a very good find. The issue was that the session was not properly settings it's state to inactive when being disconnected. 
I verified and could not repro this again after the fix.
