### ISSUE TITLE
 Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#58306]
Issue Id: <b>ecc1f526-e5f9-6321-da26-84e95422cf6d</b><br /><br />*Versions* <br />- 1.27.1<br />*Stack* <br />TypeError: Cannot read property 'forEach' of undefined<br />[/vs/workbench/browser/parts/titlebar/menubarControl.ts#419:19 (updateMnemonicVisibility)](https://github.com/microsoft/vscode/blob/5944e81f3c46a3938a82c701f96d7a59b074cfdc/src/vs/workbench/browser/parts/titlebar/menubarControl.ts#L419:19 (updateMnemonicVisibility))<br />[/vs/workbench/browser/parts/titlebar/menubarControl.ts#368:7 (setUnfocusedState)](https://github.com/microsoft/vscode/blob/5944e81f3c46a3938a82c701f96d7a59b074cfdc/src/vs/workbench/browser/parts/titlebar/menubarControl.ts#L368:7 (setUnfocusedState))<br />[/vs/workbench/browser/parts/titlebar/menubarControl.ts#353:8 (onConfigurationUpdated)](https://github.com/microsoft/vscode/blob/5944e81f3c46a3938a82c701f96d7a59b074cfdc/src/vs/workbench/browser/parts/titlebar/menubarControl.ts#L353:8 (onConfigurationUpdated))<br />[/vs/workbench/browser/parts/titlebar/menubarControl.ts#438:78 (call)](https://github.com/microsoft/vscode/blob/5944e81f3c46a3938a82c701f96d7a59b074cfdc/src/vs/workbench/browser/parts/titlebar/menubarControl.ts#L438:78 (call))<br />[/vs/base/common/event.ts#140:15 (fire)](https://github.com/microsoft/vscode/blob/5944e81f3c46a3938a82c701f96d7a59b074cfdc/src/vs/base/common/event.ts#L140:15 (fire))<br />[/vs/workbench/services/configuration/node/configurationService.ts#672:34 (triggerConfigurationChange)](https://github.com/microsoft/vscode/blob/5944e81f3c46a3938a82c701f96d7a59b074cfdc/src/vs/workbench/services/configuration/node/configurationService.ts#L672:34 (triggerConfigurationChange))<br />[/vs/workbench/services/configuration/node/configurationService.ts#541:7 (onUserConfigurationChanged)](https://github.com/microsoft/vscode/blob/5944e81f3c46a3938a82c701f96d7a59b074cfdc/src/vs/workbench/services/configuration/node/configurationService.ts#L541:7 (onUserConfigurationChanged))<br />[/vs/workbench/services/configuration/node/configurationService.ts#80:76 (call)](https://github.com/microsoft/vscode/blob/5944e81f3c46a3938a82c701f96d7a59b074cfdc/src/vs/workbench/services/configuration/node/configurationService.ts#L80:76 (call))<br />[/vs/base/common/event.ts#140:15 (fire)](https://github.com/microsoft/vscode/blob/5944e81f3c46a3938a82c701f96d7a59b074cfdc/src/vs/base/common/event.ts#L140:15 (fire))<br />[/vs/platform/configuration/node/configuration.ts#33:107 (call)](https://github.com/microsoft/vscode/blob/5944e81f3c46a3938a82c701f96d7a59b074cfdc/src/vs/platform/configuration/node/configuration.ts#L33:107 (call))<br />[/vs/base/common/event.ts#140:15 (fire)](https://github.com/microsoft/vscode/blob/5944e81f3c46a3938a82c701f96d7a59b074cfdc/src/vs/base/common/event.ts#L140:15 (fire))<br />[/vs/base/node/config.ts#197:35 (callback)](https://github.com/microsoft/vscode/blob/5944e81f3c46a3938a82c701f96d7a59b074cfdc/src/vs/base/node/config.ts#L197:35 (callback))<br />[/vs/base/node/config.ts#106:11](https://github.com/microsoft/vscode/blob/5944e81f3c46a3938a82c701f96d7a59b074cfdc/src/vs/base/node/config.ts#L106:11)<br />    at \node_modules.asar\graceful-fs\graceful-fs.js:78:16<br />    at FSReqWrap.readFileAfterClose [as oncomplete] (original-fs.js:511:3)<br />

**Comment by ramya-rao-a** [comment]
This got introduced with https://github.com/Microsoft/vscode/commit/1db4cac7af627623be2edbf4f9b40ae7f6c71844
