### ISSUE TITLE
Clear scrollback history in Terminal is just repositioning to first line

### ISSUE THREAD

**Issue by oodboo** [Microsoft/vscode#58316]
After running Unit test there is a lot of text that sticks in Powershell terminal.
In Windows PowerShell, cls / Clear-Host would clear everything in VS-code it is just repositioned to the first line.
Is this a bug or Windows issue?

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
