### ISSUE TITLE
Changing width of vertical console causes duplicate lines

### ISSUE THREAD

**Issue by Kondax** [Microsoft/vscode#58317]
Issue Type: <b>Bug</b>

Lines are duplicated when resizing the vertical console.

![Demonstration](https://i.imgur.com/hDGRn5w.gif)

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:18.328Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz (12 x 3300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.84GB (16.45GB free)|
|Process Argv|C:\Users\kondax\AppData\Local\Programs\Microsoft VS Code\Code.exe e:\Quadrant Exchange\tron-web|
|Screen Reader|no|
|VM|40%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|8.0.0
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.5.0
vscode-npm-script|eg2|0.3.5
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
beautify|Hoo|1.4.2
discord-vscode|icr|2.9.0
docthis|joe|0.7.1
dotenv|mik|1.0.1
mssql|ms-|1.4.0
python|ms-|2018.8.0
cpptools|ms-|0.18.1
debugger-for-chrome|msj|4.10.0
vscode-gtm|s3r|0.2.0
vscode-wakatime|Wak|1.2.3
html-css-class-completion|Zig|1.17.1

(2 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
