### ISSUE TITLE
VS ignores "workflows" directory

### ISSUE THREAD

**Issue by enuggetry** [Microsoft/vscode#58319]
Issue Type: <b>Bug</b>

visual studio seems to ignore directories nameed "workflows".  I have a few projects with a workflows directory either at the root or in a deeper directory structure.  The directory name appears in the workspace, but cannot drill into it or edit files under it from within visual studio.  It is not defined in .gitignore no .npm ignore.
I can however edit those files outside of VS, and git command will process them outside of VS just fine.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:34:20.517Z)
OS version: Linux x64 4.15.0-33-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (2 x 2598)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|3, 2, 1|
|Memory (System)|3.85GB (1.51GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.5.0
restructuredtext|lex|77.0.0
notepadplusplus-keybindings|ms-|1.0.2
rst-vscode|tht|2.0.0

</details>

**Comment by mjbvz** [comment]
Is this regular visual studio, or visual studio code?

**Comment by enuggetry** [comment]
Thanks.
It's Visual Studio Code.

I also noticed that if I edit a file (that is in the workflows dir) outside of VS, it does show up under Source Control within VS.

Tried disabling extensions.  It didn't help.

**Comment by mjbvz** [comment]
Do you have any workspace or user settings that could be causing this? Try looking at `files.exclude` or in your `.gitignore` file

**Comment by enuggetry** [comment]
This is what I've noticed:
I have several projects associated with my given workspace.
If /workflows is defined in .gitignore of one project, workflows is ignored in all the projects, apparently.  
.gitignore should only apply to the directory it is in and the subdirs. 

I have also noticed that defining /workflows should only ignore the /workflows and not /bin/workflows.  But, in fact, in VS, it affects /bin/workflows.  (i.e. the function is not aligned with git command.)

**Comment by isidorn** [comment]
The issue seems to be that the gitignore decoration provider files get ignored outside of the workspace that the .gitignore file lives. Forwarding to @joaomoreno and @jrieken

**Comment by jrieken** [comment]
> The issue seems to be that the gitignore decoration provider files get ignored outside of the workspace that the .gitignore file lives. Forwarding to @joaomoreno and @jrieken

@isidorn I don't think so. The decoration provider changes the color and might add an appendix to the label but it doesn't prevent drilling into a folder or anything like that.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/58466
