### ISSUE TITLE
Rename packages from code to vscode

### ISSUE THREAD

**Issue by spyderz42** [Microsoft/vscode#58322]
Thank you for creating a package repository and making vscode available in there, but please consider renaming code to vscode. Code is to generic and is hard to find (apt search code returns 19k lines). Everyone I know refers to it as vscode and that is what the old zip files installed it as. Thanks for your consideration.
https://code.visualstudio.com/docs/setup/linux

**Comment by Tyriar** [comment]
This was a discussion I started several years ago but the consensus was it was already too late to switch at that point. Plus `code` is our CLI so it makes sense for the package name to match that.
