### ISSUE TITLE
debug - unwanted console.log output

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#5832]
while debugging a C# app I see this: `rawDebugSession.ts:363 waiting for v8 protocol on stdin/stdout`

![screen shot 2016-04-26 at 15 03 29](https://cloud.githubusercontent.com/assets/1794099/14818943/0e50410c-0bc0-11e6-92ca-834256274492.png)

**Comment by isidorn** [comment]
This is coming from the debug adapter, they are loging that on the stderr - please file it agains the extension.
We are forwarding that data to the console because it helps adapter developers to investigate errors while developing
fyi @weinand

**Comment by jrieken** [comment]
It's still us printing to the console. If it's required for dev we should give them an output channel

**Comment by isidorn** [comment]
Forwarding to @weinand to decide how we want to precide with this. I do not have a strong opinion here

**Comment by felixfbecker** [comment]
Imo stderr output of debug adapters should continue to appear in the dev console for getting stack traces when it crashes (aka "debug adapter terminated unexpectedly").

**Comment by weinand** [comment]
@felixfbecker and getting the same information (stack traces etc.) in an output window like the following would not work for you?

![2016-05-04 10-57-31](https://cloud.githubusercontent.com/assets/1898161/15009527/18de3d04-11e7-11e6-9103-42ce59107c63.png)

**Comment by felixfbecker** [comment]
@weinand That would work too, but it is only for extension developers, so I have no problem with going to the dev console for this. But node-debug still logs a message on stderr on startup, which appears in the debug console... I think that should be changed to an OutputEvent

**Comment by weinand** [comment]
@felixfbecker the message 'waiting for stdin/stdout...' had been removed from the vscode-debugadapter module for v1.8.0:
https://github.com/Microsoft/vscode-debugadapter-node/commit/e6f8ad955b562cef26e5db1e6ef8ed5b64f7cb60

**Comment by weinand** [comment]
@isidorn let's try to use an output channel for the debug adapter's stderr pipe.

**Comment by isidorn** [comment]
@weinand sure, what name do you propose for the output channel?

**Comment by felixfbecker** [comment]
Please consider: Is the stderr output of the debug adapter relevant to the user? It is only relevant for extension devs. If adapters want to log info for the user, the can use an OutputEvent...

**Comment by weinand** [comment]
@felixfbecker if a debug adapter is crashing for some reason, a user should be able to find (and report) the stack trace more easily than using the dev console.

**Comment by weinand** [comment]
@isidorn I suggest not to introduce a new channel but reuse the 'Extensions' channel instead.
