### ISSUE TITLE
September Issue/PR Grooming - review, categorization, assignment

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#58336]
During September we want to get our open issues down. As a first step we will review the assigned issues. 

## Review

During the review pass please make sure to:

- close obsolete/fixed issues
- each issue must have a [type](https://github.com/Microsoft/vscode/wiki/Issue-Tracking#issue-types) 
  - **Note**: All type labels are grey (Bugs grey with a touch of red).
- assign the `important` label to issues that
  -  result in data loss
  - a breakage of extension
  - critical security, performance issues
  - UI issue that makes a feature unusable
- each issue needs to be assigned to a [feature area](https://github.com/Microsoft/vscode/wiki/Feature-Areas)
- assign bugs that you plan to fix during September to the September milestone
- issues that the community can take up should be labeled as `help-wanted`
- if issues are suitable for beginners you can also add the `good-first-issue` label and add code pointers that help beginners to get started with a PR
- feature requests that should be implemented as extensions should be labeled `extensions-candidate` and be closed

## Tracking:
Please make sure that you also do this grooming in our satellite repositories:
  - [x] @alexandrudima
  - [x] @weinand
  - [x] @chrmarti
  - [x] @tyriar
  - [ ] @dbaeumer
  - [x] @bpasero
  - [x] @egamma
  - [x] @isidorn
  - [x] @joaomoreno
  - [x] @jrieken
  - [x] @kieferrm
  - [x] @aeschli
  - [x] @rebornix
  - [x] @ramya-rao-a
  - [x] @roblourens
  - [x] @sandy081
  - [x] @mjbvz
  - [x] @octref 
  - [x] @auchenberg 
  - [ ] @chrisdias 
  - [x] @seanmcbreen  (covered by @egamma)
  - [x] @danyeh

**Comment by bpasero** [comment]
@egamma there are issues assigned to people that are not showing up in the list to sign off:
* https://github.com/Microsoft/vscode/issues/assigned/auchenberg
* https://github.com/Microsoft/vscode/issues/assigned/chrisdias
* https://github.com/Microsoft/vscode/issues/assigned/seanmcbreen (!)
* https://github.com/Microsoft/vscode/issues/assigned/danyeh
