### ISSUE TITLE
Markdown preview cannot be resized anymore

### ISSUE THREAD

**Issue by scottrudy** [Microsoft/vscode#5833]
- VSCode Version:1.0.1-insider
- OS Version:Windows 10 1511 (Build 10586.164)

Steps to Reproduce:

1. Open a Markdown file
2. Open a Preview of Markdown file to the side
3. Attempt to re-size the split windows

**Comment by bpasero** [comment]
@scottrudy so what does happen when you try to resize?

**Comment by scottrudy** [comment]
The app never responds to the mouse-up event and resizing only seems to work in one direction, unless you move the mouse to the top of the window. After clicking around a bit the mouse-up event eventually fires, but I haven't been able to produce a consistent action.

**Comment by bpasero** [comment]
Looks like a regression...

**Comment by bpasero** [comment]
Marking important, this makes markdown preview and html preview unusable.

**Comment by bpasero** [comment]
My fix is to disable any mouse events on iframes as soon as a sash is moving because an iframe would eat the mouse move otherwise.

Please verify this change across Windows, Mac and Linux. You should be able to move sashes as before and especially move 1-N markdown previews with sashes properly.
