### ISSUE TITLE
SCM viewlet shows 'no active source control providers' during load time

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#58335]
This status message is confusing since there are source control providers, but they are not loaded yet.

I suggest to add a special message for the loading state, e.g., 'Loading Source Control Providers...'

![image](https://user-images.githubusercontent.com/172399/45280677-a68b9780-b4d5-11e8-980c-29252c2d0fd4.png)

**Comment by joaomoreno** [comment]
@egamma Source control providers are not contributed declaratively, so there is no "checkpoint" in time to do this.

**Comment by joaomoreno** [comment]
As discussed, rephrased to: `No source control providers registered.`.
