### ISSUE TITLE
Terminal Timestamp Option

### ISSUE THREAD

**Issue by dac88** [Microsoft/vscode#58338]
Would it be possible to have a auto-timestamp option in the integrated terminal on the left hand side margin? 

This would be useful for such things as long running scripts to be able to see when the previous command started running from, and also to see when commands were run further in the history.

Thanks,
Dean.

**Comment by Tyriar** [comment]
You can do this easily with the prompt, I don't think it's worth it right now to support this at a lower level.

**Comment by dac88** [comment]
Thanks Tyriar. Shame because it is a feature i would really like. Changing the config on various shared remote machines to suit my preferences is not realistic. I understand if the implementation of this is tricky, however it is a feature i believe would be useful and as an opensource project i thought it worth putting it forward.

**Comment by DanielAsher** [comment]
> You can do this easily with the prompt, I don't think it's worth it right now to support this at a lower level.

This is incorrect, as the prompt message is not repeated on every `stdout` or `stderr`. The prompt only features for interactive user input.
