### ISSUE TITLE
[Json]  value expected

### ISSUE THREAD

**Issue by Mornedeklerk** [Microsoft/vscode#58339]
![image](https://user-images.githubusercontent.com/33857313/45287093-bd3aea00-b4e7-11e8-88b7-20b77ddb133e.png)

**Comment by usernamehw** [comment]
So?

**Comment by joaomoreno** [comment]
Since the file isn't valid JSON, the error is telling you exactly that.

**Comment by Mornedeklerk** [comment]
how so i get rid of it ?

**Comment by Mornedeklerk** [comment]
How  do i get rid of it ?
