### ISSUE TITLE
Missing flag in documentation about Python App Engine debugging

### ISSUE THREAD

**Issue by julian-lumapps** [Microsoft/vscode#58347]
- VSCode Version: 1.27.0
- OS Version: Ubuntu 18.04

See [my description of the problem](https://stackoverflow.com/questions/52249076/how-to-setup-vscode-python-debugger-for-an-app-engine-app/52257015#52257015) on stackoverflow. It looks like the documentation about [Python App Engine debugging](https://code.visualstudio.com/docs/python/debugging#_google-app-engine-debugging) should instruct to use the `--threadsafe_override=default:false` flag in addition to the `--max_module_instances=default:1` flag.

**Comment by weinand** [comment]
please file against python extension
