### ISSUE TITLE
VS Code completely broken by extension

### ISSUE THREAD

**Issue by levrik** [Microsoft/vscode#58349]
- VSCode Version: 1.27.1
- OS Version: macOS 10.13.6

Sometimes the search and file name search just stop working and only a restart of the system helps.
You cannot force kill these ghost processes with no CPU time at all.
Also you cannot cleanly restart macOS. You have to force kill the whole machine.
Also extensions don't want to load anymore including built-in ones like Git.

![image](https://user-images.githubusercontent.com/9491603/45296648-f9c80f00-b502-11e8-9e2f-4000126fec2c.png)

Does this issue occur when all extensions are disabled?: No

I will try to find out which extension causes this behaviour.

**Comment by levrik** [comment]
Okay. This issue seems to be caused by the vscode-spotify extension. I will file an issue over there.

**Comment by levrik** [comment]
@joaomoreno Still one thing: Personally I think for an extension it shouldn't be possible to completely break VS Code. If I have time I could try to find out what exactly causes this issue and file a new issue.

**Comment by joaomoreno** [comment]
Totally agree. Can you reproduce if you reinstall the spotify extension?

**Comment by levrik** [comment]
@joaomoreno I will take a look at it tomorrow.

**Comment by pzelnip** [comment]
FWIW I have the [Spotify extension](https://marketplace.visualstudio.com/items?itemName=shyykoserhiy.vscode-spotify) installed and don't have this problem.  My versions:

VS Code: 1.27.1
Spotify Extension: 2.6.1
OSX: Sierra (10.12.6)

**Comment by levrik** [comment]
@pzelnip Yeah. I saw some issue where the maintainer stated that this issue is fixed. I will reinstall the extension tomorrow to check this. But still I would like to investigate how it was possible for the extension to break VS Code completely.

**Comment by joaomoreno** [comment]
Thanks, let me know what you find.

**Comment by levrik** [comment]
After reinstalling the extension I didn't experience any issues anymore.
It looks like this commit fixed the issue.
https://github.com/ShyykoSerhiy/vscode-spotify/commit/8a0b16650a6928b414c78b6e352829f6b3dd5391
Looks a bit like there was something not stopping to poll which somehow let the initialization of VS Code hang.

**Comment by joaomoreno** [comment]
Others: #56647 #55229

**Comment by alexandrudima** [comment]
This is difficult to reproduce with the spotify extension. I have created two separate issues to track two different things when having a *bad* extension that executes and endless loop via while true or via process.nextTick:

1. Show something in the UI that the extension host process is in a *bad* state -- #58612
2. Kill the *bad* extension host process after closing the affected window -- #58606

I would continue tracking this issue in the two issues from above as those have clear, easy reproducible steps.
