### ISSUE TITLE
Allow npm module suggestions to be disabled in javascript import paths

### ISSUE THREAD

**Issue by kevinmarrec** [Microsoft/vscode#58340]
Hi, I've tried many and many changes around VSCode settings to get rid of npm "modules" Import auto-completion, but I didn't find a solution, so it may be a bug ...

Actual Behavior :
![screenshot_2](https://user-images.githubusercontent.com/25272043/45287983-e2c8f300-b4e9-11e8-8422-0af5726dd3a0.png)

with these User Settings (I tried EVERYTHING, but it still shows up):
![screenshot_1](https://user-images.githubusercontent.com/25272043/45287879-b0b79100-b4e9-11e8-8674-6d33647fd210.png)

=> Autocompletion should not show up with this stuff, it is really annoying to have these entries in autocompletion when working on my project..

If it's not a "bug", please forward me to a solution, cause I looked over and over undreds of "kind of related" topics.

EDIT : VSCode provides this autocompletion looking over `package.json` file or `node_modules` folder. So I guess there is an option to disable it ?

Thanks in advance !

**Comment by kevinmarrec** [comment]
The only way to get rid of the autocompletion is to both remove `package.json` file and `node_modules` folder.

**Comment by mjbvz** [comment]
Does this reproduce with all extensions disabled?

**Comment by kevinmarrec** [comment]
@mjbvz Yes, unfortunately, it does.

![screenshot_2](https://user-images.githubusercontent.com/25272043/45308222-41f62a00-b521-11e8-889f-3560db51734c.png)

**Comment by kevinmarrec** [comment]
@mjbvz Thanks ! Still we'll be able to have the rest of autocomplete working ? The option needed here is to have the possibility to only disable paths provided by Package.json, node_modules, :)

**Comment by mjbvz** [comment]
This setting will disable all path suggestions. Suggestions in code will remain the same

**Comment by kevinmarrec** [comment]
So there is no solution to have `./foo.js` and not paths from `node_modules` ?

My aim is likely to have a workspace where I can autocomplete relative paths without having `node_modules` polluting the suggestions :/

I think that `node_modules` suggestions should show up if there is no `/` yet where the user typing.

Like 
`import a from '` => Node modules + Relative paths
`import a from 'b` => Node modules + relative paths matching `b`
`import a from 'b/` => Only relative paths in the `b` folder
`import a from './` => Only relative paths in current directory.

My problem is not really disabling node_modules, the problem is the unfriendly autocomplete in many cases, example  :
`import a from `b/c/d/e/` => Node_modules shows up, why ?

**Comment by mjbvz** [comment]
That is a bug. I've opened https://github.com/Microsoft/TypeScript/issues/27033 to track is upstream 

Closing this issue on our side with the fix of making `"typescript.suggest.paths"` and `"javascript.suggest.paths"` disable all path intellisense. Will continue tracking the bug with node_module suggestions showing in unexpected places within path completions upstream

**Comment by kevinmarrec** [comment]
Alright ! Thanks !
