### ISSUE TITLE
"Open New Terminal" does not work for empty workspace

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#5834]
We can make this command actually work when not having a workspace open.

**Comment by bpasero** [comment]
Verify that "Open New Terminal" works for when you do not have a folder open and it takes the parent folder of the currently active file if any.

**Comment by joaomoreno** [comment]
@bpasero Verified, but should't we open a terminal even if there is no open file? We could just open it at `~`. What do you think?

**Comment by bpasero** [comment]
Yup, https://github.com/Microsoft/vscode/issues/5977
