### ISSUE TITLE
Settings tab view is reset after jumping back from another tab

### ISSUE THREAD

**Issue by nammaianh** [Microsoft/vscode#58341]
Issue Type: <b>Feature Request</b>

When i jump to another tab from Settings tab, and then back to Settings tab. The settings page is reset like it has just been opened. That makes me feel tired and angry after several times of having to scrolling down after each time i check if the settings were ok.

Steps:
1. Open Settings tab.
2. Jump to another tab.
3. Come back to Settings tab.

Please make it stop re-rendering the view for the next release.

Thank you!

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:14:32.385Z)
OS version: Darwin x64 17.7.0

**Comment by roblourens** [comment]
The settings editor should be fixed in Insiders. So I assign this to @mjbvz for the release notes webview...

**Comment by mjbvz** [comment]
Release notes should also be fixed in insiders
