### ISSUE TITLE
There is something wrong with "display language configure"

### ISSUE THREAD

**Issue by blackmarkCH** [Microsoft/vscode#58358]
Issue Type: <b>Bug</b>

when i type "zh-cn"  in   the line of  "locale",the vs-code told   me  "zh-cn" is valid value.but after I restart the vs-code,"zh-cn" is not accepted.

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:47.222Z)
OS version: Linux x64 4.15.0-33-generic

<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.8.0
cpptools|ms-|0.18.1

</details>

**Comment by dbaeumer** [comment]
@blackmarkCH you need to download the corresponding language pack from the market place here: https://marketplace.visualstudio.com/search?target=VSCode&category=Language%20Packs&sortBy=Downloads 

I am closing the issue. If this doesn't help, please ping.

**Comment by blackmarkCH** [comment]
> @blackmarkCH you need to download the corresponding language pack from the market place here: https://marketplace.visualstudio.com/search?target=VSCode&category=Language%20Packs&sortBy=Downloads
> 
> I am closing the issue. If this doesn't help, please ping.

Thank you~!
