### ISSUE TITLE
Close inminent

### ISSUE THREAD

**Issue by ewcastroh** [Microsoft/vscode#58350]
Some time I am working and intantantly VS Code stops giving to me 3 options; Reopen, Wait and close.
The unique way to continue is reopen or close. When VS Code opens again I lose my previews opened files, but at least it saves my changes.

**Comment by ewcastroh** [comment]
Hi Benjamin
I worked with no plugins then I uninstalled the lastests plugins and the VS Code has worked successfuly.
At the moment I haven't could know what plugin was broken, but I am fine until the moment with my IDE.
Thank you so much for your help.
Best regards.

**Comment by bpasero** [comment]
OK closing then.
