### ISSUE TITLE
Hyperlinks in configuration settings

### ISSUE THREAD

**Issue by Gruntfuggly** [Microsoft/vscode#58353]
The new settings tab is really nice, but when the configuration is complex and it needs to drop back to the old settings, it would be nice if a clickable hyperlink could be used so that the user can get some more details, in same way as some of the application configuration settings have 'Read more'.

**Comment by roblourens** [comment]
Some settings that have their own docs do have this. What other details are you looking for?

**Comment by Gruntfuggly** [comment]
Sorry - I missed an important part of the puzzle!

I'd like to be able to add my own links in my extension's `package.json`, e.g.

```
                "todo-tree.defaultHighlight": {
                    "type": "object",
                    "description": "Default configuration for highlighting, see https://github.com/Gruntfuggly/todo-tree#highlighting",
                    "default": {}
                },
```

At the moment, this just renders as plain text. It would be cool if it got picked up and made into a clickable link. Even better, would be if I could use markdown format, ie.

```
"Default configuration for highlighting, see [here](https://github.com/Gruntfuggly/todo-tree#highlighting) for details."
```

**Comment by roblourens** [comment]
You can switch to `markdownDescription` instead of `description` and it will be rendered as markdown. I need to document this, I wonder where the right place is...
