### ISSUE TITLE
JS syntax highlighter falsely highlight `export`

### ISSUE THREAD

**Issue by Yzhibin** [Microsoft/vscode#58351]
Issue Type: <b>Bug</b>

In a JS file, if a line starts with keyword `export`, then `export` part will be highlighted. 
E.g.
```js
    var exporter;
    exporter = {...};
```
In this case, it will highlight `export` part in Line 2.

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:14:32.385Z)
OS version: Darwin x64 17.7.0

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript-TmLanguage/issues/664 to track this upstream
