### ISSUE TITLE
Cannot debug flask after latested update to vscode

### ISSUE THREAD

**Issue by dungeontiger** [Microsoft/vscode#58352]
Issue Type: <b>Bug</b>

I've detailed the steps here in stackoverflow.  Very very simple.

https://stackoverflow.com/questions/52240227/cannot-debug-flask-with-vscode-after-update

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:14:32.385Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (4.55GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_65552|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.5.0
python|ms-|2018.8.0
team|ms-|1.136.0
vscode-docker|Pet|0.2.0
java|red|0.30.0
vscode-java-debug|vsc|0.12.2
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.8.0
vscode-maven|vsc|0.10.0

</details>

**Comment by weinand** [comment]
please file against Python extension
