### ISSUE TITLE
how to delete another user Git?

### ISSUE THREAD

**Issue by ghost** [Microsoft/vscode#58356]
Hello, I ran into the problem of how to remove the old user. The fact is that the problem is with VSCode
A new branch of the user is connected, and how to remove the old user?
https://github.com/xekeapp/layout-web/blob/master/Untitled-2.jpg
remote: Permission to xekeapp/layout-web.git denied to appath.
fatal: unable to access 'https://github.com/xekeapp/layout-web.git/': The requested URL returned error: 403

**Comment by joaomoreno** [comment]
Can you please list the exact steps to reproduce this?
