### ISSUE TITLE
unins000.exe

### ISSUE THREAD

**Issue by AnthonyJacob** [Microsoft/vscode#58364]
Every 5 minutes this error notification appears on my screen when vscode is running:

[image](https://imgur.com/BLM3ncv)

**Comment by gahobbsau** [comment]
Same here.  I am also using Jupyter files in browser at same time. Error appeared first time today when I opened an .ipynb file in VS Code.

unins000.exe appears to be an uninstall file and is accompanied by a .dat and .msg file of same name, both binary. Dragging them into Notepad++ reveals some readable text that appears to include messages that might appear during an installation.
.msg file top line: Inno Setup Uninstall Log (b)
.dat file top line: Inno Setup Messages (5.5.3)

**Comment by joaomoreno** [comment]
When you installed the UserSetup of VS Code... did you run the setup as an administrator?

**Comment by gahobbsau** [comment]
I was logged to my Win10 Notebook in an account that is an administrator. 
Did I need to right click the setup file and "Run as administrator" as well?
If so, can I uninstall VSCode, then reinstall, with settings saved?
I expect that I would need to note and reinstall extensions.
(Would the same all apply to my Visual Studio install?)

**Comment by joaomoreno** [comment]
> Did I need to right click the setup file and "Run as administrator" as well?

No no. That's exactly what you shouldn't do.

> If so, can I uninstall VSCode, then reinstall, with settings saved?

Yes you can, nothing will be deleted.

**Comment by gahobbsau** [comment]
So, Is there anything that should be done so as to "run the setup as an administrator" - other than be logged on as an administrator?
And, does it matter whether it installed for All Users or only Current User (if it asks).
The VS Code install guideline pages seem to offer very limited guidance, such as at https://code.visualstudio.com/docs/setup/setup-overview
This 3rd party one looks more helpful https://www.thewindowsclub.com/visual-studio-code-download
Is there a better guide so as to get the install correct?
==
BTW, this unins000.exe error has only appeared in the last couple of days when using a couple of particular Jupyter notebooks. I have only recently starting use Code and VStudio but this issue did not occur till yesterday.

**Comment by gahobbsau** [comment]
Something to consider.
I also have Anaconda installed on this laptop and Anaconda recently added vscode to its distribution. In the Anaconda Navigator, I now see vscode 1.26.1 available to "Launch" which appears to open the same vscode with the same set of installed extensions.

**Comment by joaomoreno** [comment]
Keeping my suggestion:

If you are going to install VS Code on a machine for other users to use, please use the old, global, system-wide Setup. Do not use the UserSetup.

If you are already doing that, and this specific error still shows up, let me know.

**Comment by gahobbsau** [comment]
In my case, I uninstalled and re-installed VS Code with it installed into my user appdata folder.
Since doing that I no longer receive the unins000.exe error.
