### ISSUE TITLE
Webview panel does not remove on dispose()

### ISSUE THREAD

**Issue by ivankravets** [Microsoft/vscode#58360]
- VSCode Version: 1.27.1
- OS Version: macOS

# Code

```js
panel = vscode.window.createWebviewPanel(...);
this.subscriptions.push(panel.onDidDispose(this.onPanelDisposed.bind(this)));

  onPanelDisposed() {
    console.log('onPanelDisposed');
    this._currentPanel = undefined;
  }

  dispose() {
    console.log('Home::dispose', this._currentPanel);
    if (this._currentPanel) {
      console.log('Going to kill home');
      this._currentPanel.dispose();
      this._currentPanel = undefined;
    }
}
```

# Problem

1. I don't know is it a feature or bug of VSCode, but each time when we add a new folder to workspace VSCode kills our extension via `deactivate()` and then `activate()` again. This workflow requires a lot of CPU resources for our `activate()` implementation. https://github.com/platformio/platformio-vscode-ide/blob/develop/src/main.js

2. When VSCode calls `deactivate()`, we call `panel.dispose()`, to close active PIO Home tab. Sometimes it works, sometimes does not. See log from debug console:
```
deactivating extension
extension.js:409
Home::dispose
home.js:132
Object
_isDisposed:false
_visible:true
_active:true
_onDisposeEmitter:Object
_onDidChangeViewStateEmitter:Object
_handle:"1"
_proxy:Object
_viewType:"pioHome"
_options:Object
_viewColumn:1
_title:"PIO Home"
_webview:Object
_iconPath:Object
Going to kill home
home.js:134
onPanelDisposed
home.js:127
activating extension
extension.js:26
starting language server
```

# Result

Our panel is not closed

**Comment by mjbvz** [comment]
Sorry, this fell off my radar. 

I can't reproduce this issue in the latest VS Code insiders build. If you are still running into this issue, can you share a small example extension that demonstrates it so I can make sure I am testing the right thing

**Comment by ivankravets** [comment]
Yes, it seems that works now. Thanks!
