### ISSUE TITLE
add Remote editing broswing or add good API for it

### ISSUE THREAD

**Issue by 07pepa** [Microsoft/vscode#58361]
Please add standardized support for remote browsing and editing files with multiple schemes (sftp, ftp ...etc.)

I know there are extensions for this but they do not play well with other extensions ( like linting does not work) therefore standardized approach or standardized API is needed.

thanks

**Comment by mjbvz** [comment]
We just announced remote development with VS Code, check out the [blog post](https://code.visualstudio.com/blogs/2019/05/02/remote-development) for details
