### ISSUE TITLE
http cache don't expire even after reopen VS Code

### ISSUE THREAD

**Issue by 928PJY** [Microsoft/vscode#58362]
- VSCode Version: 1.27.1
- OS Version: win10

Steps to Reproduce:

1. Send an HTTP request to a fake server to get some content
2. Change the response of the server
3. Reopen VS Code or run the command `Reload Window`.
4. Send same HTTP request and get the content.

It still the same response with the first time.

**Comment by joaomoreno** [comment]
> Send an HTTP request to a fake server to get some content

How do you do this?

**Comment by 928PJY** [comment]
I am creating an extension, I have to get some external resource by http request in this extension. to provide a better performance, I have not set the ‘no-cache’ header, but I want to force clean up the cache by reopen vscode,  it doesn’t work

**Comment by joaomoreno** [comment]
How do you make the HTTP request, show me some code.

**Comment by 928PJY** [comment]
here is the HTTP request [code](https://github.com/redhat-developer/yaml-language-server/blob/master/src/server.ts#L161)

**Comment by joaomoreno** [comment]
`request-light` doesn't do any caching, nor does VS Code. Please check your setup once again, you might be doing something wrong.

**Comment by 928PJY** [comment]
this is a mistake, we are using the raw content of a GitHub file( https://raw.githubusercontent.com/... ), but when we change the GitHub content, the raw content is not synced in real-time, so we still get the old content.
But there is still one question, there is no cache even if I have not set `no-cache` header?

**Comment by aeschli** [comment]
Caching could also be done on a proxy.
The cache control headers are coming from the server  *https://raw.githubusercontent.com/... ), so if they are missing, this needs to be fixed there.
