### ISSUE TITLE
'Show active file in explorer' should be 'Reveal active file in explorer'

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#5837]
#5329

I believe 'Reveal active file in explorer' is a better name because it revealse the file and this name is more connected to the setting name `explorer.autoReveal`

I for instance needed some time to find the corresponding action in the command pallete because I was looking for **reveal**.

**Comment by bpasero** [comment]
I explicitly decided against that because it would make the other reveal action be #2 which imho has a lot more users.

**Comment by yomed** [comment]
FWIW it did take me a while to figure out that the command was `workbench.files.action.showActiveFileInExplorer`
