### ISSUE TITLE
Markdown viewer jitter with new custom title bar in fullscreen mode

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#58375]
The new custom title bar landed in 1.27. It fixes a lot of the issues with UI pieces twitching for a frame when toggling the title bar, however I found one remaining place where this still occurs. When viewing a markdown file the 'scroll to top' button in the bottom right and the scroll bar jitter. The scroll bar only jitters when scrolled the bottom of the window.

For one frame you can see the button and scroll bar move up too far then settle into the correct location.

![jitter](https://user-images.githubusercontent.com/484784/45315353-10fa0300-b4e9-11e8-87dd-e7a1f0435df9.gif)

**Comment by sbatten** [comment]
@akbyrd in the above gif, I can see the editor tab shift down. This is with the custom titlebar?

**Comment by akbyrd** [comment]
Yea, this is with the custom title bar. Sorry, didn't realize the recording cut the window top off. In the gif I'm just mashing the alt button to show/hide the title bar repeatedly.

**Comment by sbatten** [comment]
@akbyrd can you possibly make a new gif with the whole window so I can see what's happening with the rest of the UI?

**Comment by akbyrd** [comment]
Steps to repro:

Add to settings.json
```
"window.menuBarVisibility": "toggle",
"window.titleBarStyle": "custom",
```

Open release notes (Help > Release notes)
Scroll to bottom
Press Alt

**Comment by sbatten** [comment]
@akbyrd Unfortunately I am unable to repro this with 1.27.0, 1.27.2 or 1.28.0-insiders currently.

**Comment by akbyrd** [comment]
I forgot the step to enter full screen. Can you try again with that?

(My normal way of capturing gifs doesn't work for full screen. That's why the top is cut off above and I'm giving repro steps instead of making another gif.)

**Comment by sbatten** [comment]
AH! Thanks @akbyrd confusion gone :)

**Comment by sbatten** [comment]
jitter seems to be gone even though the scrollbar shifts a little
