### ISSUE TITLE
Task with showReuseMessage set to false displays a blank line

### ISSUE THREAD

**Issue by GoaLitiuM** [Microsoft/vscode#58371]
- VSCode Version: 1.27.1
- OS Version: Windows 10 (Build 17677)

Steps to Reproduce:
1. Change a simple (build) task setting presentation.showReuseMessage to false
2. Run the task
3. Observe a blank line where the reuse message used to show up, instead of no extra line displayed at all

Does this issue occur when all extensions are disabled?: Yes

I was expecting this setting to reduce the overall lines printed by running the task, but all it does is prints an empty line instead of removing the line completely.

**Comment by dbaeumer** [comment]
@Tyriar I currently set `waitOnExit = '\u200B'`. I can't simply set it to false since this would close the terminal.

Any advice how to avoid the blank line?

**Comment by Tyriar** [comment]
I guess you want to pass in `true` and handle it here:

https://github.com/Microsoft/vscode/blob/ac7ead397b8de27cfc2a2b11e4c42fa96ba10c35/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L789-L794

**Comment by dbaeumer** [comment]
OK. I will change the code as follows:

- if waitOnExit is a boolean honor it and never print a message
- if it is a string wait and print the provided message.

Is this OK for you ?
