### ISSUE TITLE
Ability to set Activity Bar icons per project/folder

### ISSUE THREAD

**Issue by TheScarfix** [Microsoft/vscode#58378]
I am using VS Code for multiple programming languages and projects and I don't need every activity bar icon in every project so the ability to activate/deactivate them on a project/folder basis would be awesome and make the UI cleaner.

**Comment by sandy081** [comment]
What are the icons you want to configure per folder? Are they default one or contributed to extensions?

**Comment by TheScarfix** [comment]
both if possible although mainly extensions since I don't need docker in non docker projects for example

**Comment by sandy081** [comment]
@TheScarfix Then you can disable docker extension in this case and enable docker extension only in the docker projects

**Comment by TheScarfix** [comment]
how can I do that? and do I have to do this every time I switch project or is the extension config saved?

**Comment by TheScarfix** [comment]
did not know this is possible, thanks :)
