### ISSUE TITLE
Can't search if there is a workspace folder for a scheme that has no search provider

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#58370]
Issue Type: <b>Bug</b>

If you have a workspace opened where one of the folders is a non-`file://` scheme (a `FileSystemProvider`) you can't search across the files in the workspace folders that can be searched.

![image](https://user-images.githubusercontent.com/641685/45312698-c71a1880-b4fa-11e8-9f0f-e6ebf235f379.png)

I would have expected the search to only return results for the workspace folders that supported searching with optionally a notice that not all workspaces were searched

/cc @roblourens 

VS Code version: Code - Insiders 1.28.0-insider (96854113091424c07b28ba84b82b75a88b8455cb, 2018-09-10T05:18:57.119Z)
OS version: Windows_NT x64 10.0.17755

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (15.32GB free)|
|Process Argv|C:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by roblourens** [comment]
The question here is, what do we do when a folder doesn't have a search provider? Search all folders/open files that we can, but show an error popup notification? Or still show an error notification on the search input? 

If we expect people to search regularly in their 3 of 4 folders that have providers, maybe showing an error each time is too noisy. But you do need to know why that folder is missing results... and this applies to quick open too.

**Comment by eamodio** [comment]
imo having a warning (not error) notice when searching across all files might be nice (but maybe dismissable per workspace?). Because once you know it's just going to be annoying. As for the other places I would just leave it silent (other than in the documentation for the apis).

To me search becomes something folders can participate in just like other (code intelligence) apis. It's not a guaranteed feature.

**Comment by eamodio** [comment]
Just wanted to bump this as GitLens users have started reporting it: https://github.com/eamodio/vscode-gitlens/issues/587

**Comment by sherlockwang** [comment]
I still got the same issue. I don't think this should be closed. I tried reinstall gitlens. But either with or without that extension, I got the same message.

**Comment by gjsjohnmurray** [comment]
@sherlockwang did you try it with the current Insiders build (1.31.0-insider)? When I do that, 'Find in Files' now works on a multi-root workspace with one root provided by a FileSystemProvider that doesn't support search.
