### ISSUE TITLE
On Windows 10 using Linux Subsystem & "useWSL" set to true, unable to specify which Node version to launch debugger with

### ISSUE THREAD

**Issue by MikeSeguin** [Microsoft/vscode#58381]
Visual Studio Code is run within the Windows environment, but the debugger launches the app within the Linux subsystem (WSL).

Currently unable to specify which version of Node to launch the debugger with. Despite several attempts to specify the version, it always launches with an incorrect default version.

**Expected Result:** App launches with Node v8.11.4 
**Actual Result:** App launches with Node v6.14.3

Steps to reproduce:
1. Working from Windows 10, configure Visual Studio Code's launch config to launch with "useWSL" set to true.
2. Try to launch your app with a node version different than the default.

Things I've tried, to no success:
1. Setting default node to 8.11.4
Result: Launches with 6.14.3

2. Specifying path to node using runtimeExecutable param:
Result: Editor hangs, unable to connect to app
runtimeExecutable value: ${env:HOME}/.nvm/versions/node/v8.11.4/bin/node

3. Specifying runtimeVersion:
Result: Launches with 6.14.3
runtimeVersion value: 8.11.4

**Comment by weinand** [comment]
By using the "useWDL" option, VS Code uses the default version of node installed in linux. Basically VS Code runs node via the "wsl" CLI command:  `wsl node program.js`.
 
You can find the default version by running `wsl node --version` from a command prompt in Windows.

If you want to use a different version of node, you will have to install it on linux and then verify it by running `wsl node --version` again.

**Comment by MikeSeguin** [comment]
@weinand Windows command prompt does not recognize 'wsl' as a valid command. Am I missing something windows-side?

**Comment by weinand** [comment]
Then you are not using a recent version of WSL

You can use `bash -c` instead of `wsl`, e.g. `bash -c node --version`

**Comment by MikeSeguin** [comment]
@weinand When running bash -c node --version, the command line just drops down to a new (blank) line awaiting input, as shown:
![screencap_002](https://user-images.githubusercontent.com/35303711/45362417-c3da6780-b5a2-11e8-9256-a5aded88d8e7.PNG)

**Comment by MikeSeguin** [comment]
@weinand My default version of Node is 8.11.4, as it should be. I've even uninstalled node v6.14.3. Yet somehow it keeps launching with v6.14.3

**Comment by weinand** [comment]
Please try `bash -c "node --version"`

**Comment by MikeSeguin** [comment]
@weinand Aha, now we're on to something. It's showing 6.14.3 as the default version.

Am I right in assuming my next step is to run a command from this command prompt something like this:

`bash -c "nvm alias default 6.1.0"`

**Comment by weinand** [comment]
Just call `bash` without arguments to get an interactive shell  on linux. There you can run `nvm alias default 8.11.4` etc.

**Comment by MikeSeguin** [comment]
@weinand Perhaps it's my fault for not clarifying, but the output is different between running the command from the command line, and then again from the Bash command line.

Running your version query returns 6.14.3, which is the incorrect version that I'm trying to solve. However, once in bash, it properly defaults to 8.11.4 and I have already set the alias to default to it.

So, clearly, whatever's causing the query to return 6.14.3 from windows command line `bash -c "node -v" is also responsible for why my Visual Studio Code is launching with that version. However, I'm relatively new to linux/node/nvm/npm, so I'm not quite understanding why there's a disconnect between what I'm seeing from the bash terminal and the command sent from a regular Windows command line.

See attached image for reference.

Additionally; when within the Bash terminal, node v6.14.3 does not even appear to be installed, furthering my confusion!

![image](https://user-images.githubusercontent.com/35303711/45371282-343fb380-b5b8-11e8-8ee4-e84c6a517e48.png)

**Comment by weinand** [comment]
I suspect that the difference is that "bash" start an interactive shell and "bash -c ..." does not. And for the interactive shell you are  running some specific setup in your .bash profile set results in a different version of node than when running bash non-interactively.

So this is clearly not a VS Code issue.

**Comment by MikeSeguin** [comment]
@weinand Hm ok, I'll do the ol' reboot and see if that fixes anything, couldn't hurt.

I'll investigate that avenue (interactive vs. non-interactive); could it also be a possibility that the difference stems from the fact that, within the Bash terminal, I'm logged in; and when accessing from the windows command line, I'm not?

**Comment by weinand** [comment]
Yes, that's basically what I meant with "interactive shell" versus "non-interactive shell".
