### ISSUE TITLE
custom titleBarStyle breaks mouse cursor in editor

### ISSUE THREAD

**Issue by G-Ray** [microsoft/vscode#58383]
- VSCode Version: v1.27.1
- OS Version: Fedora 28
- screen: 3200x1800px

Steps to Reproduce:

1. Set `window.titleBarStyle="custom"`
2. restart vscode in a window
3. The cursor mouse does not work everywhere in the editor.

Gif demonstrating the issue: https://i.imgur.com/vQi0iWV.gif

The issue does not happen when vs code is in fullscreen, or when titleBarStyle is set to "native".
The issue does not appear on another computer on Fedora 28 too, with a 1080p screen.

**Comment by sbatten** [comment]
@G-Ray can you reliably repro this with the custom title bar enabled? Is it possible to reproduce this with the native title bar?

**Comment by G-Ray** [comment]
@sbatten Here are some more info:

- I can repro this 100% when custom title bar is enabled + my gnome desktop display settings scale the display at 200%. As my laptop screen is 3200x1800, I always use a scale setting of 200%.

- No issue when the scaling is set to 100%.

- when titlebar is native, I can't repro the issue, no matter what is the scaling percentage.

I guess when the style is native vscode uses gtk3, and there is no issues at all with the way gnome/gtk are scaling the app. However when the titleBar is set to custom, gtk libs may not be loaded, and this causes this issue ?

**Comment by G-Ray** [comment]
@sbatten Any news ? Can you reproduce this behavior in a GNU/Linux distro ?

**Comment by sbatten** [comment]
@G-Ray thanks for the extra info, I was able to repro the issue in Electron as well and have reported upstream: https://github.com/electron/electron/issues/14787

**Comment by sbatten** [comment]
confirmed
