### ISSUE TITLE
Breadcrumbs' position

### ISSUE THREAD

**Issue by zbandhan** [Microsoft/vscode#58386]
Currently Breadcrumbs bar is located to the top of the editor. It should be configurable to locate it at the bottom of the editor too. B4 Vscode I've used an Editor which has breadcrumbs located to bottom. 
Note: Mostly I use breadcrumbs for HTML DOM.

**Comment by liangya123** [comment]
;;;;;

**Comment by liangya123** [comment]
--;;;
