### ISSUE TITLE
I am sometimes loosing output for git in the output panel

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#5838]
I am seeing this from time to time that I run a git operation that fails and then when I want to show output I do not see the git output. Even when I explicitly refresh git viewlet where more output should show up (e.g. "fetch...") no more output is added.

I do not have steps to reproduce and a refresh typically fixes it but wanted to report it if others hit this?

**Comment by isidorn** [comment]
Never saw it on mac

**Comment by bpasero** [comment]
![untitled](https://cloud.githubusercontent.com/assets/900690/14914456/83212950-0e0a-11e6-8340-a02d7685b66c.gif)

@isidorn please plan for May, this is pretty bad. I had selfhost running for a while, did not use output at all and I stop getting output for git.

**Comment by bpasero** [comment]
@isidorn @joaomoreno debugged this and it seems the git event is not being fired in https://github.com/Microsoft/vscode/blob/ben/stacks/src/vs/workbench/parts/git/browser/gitOutput.ts#L26

**Comment by joaomoreno** [comment]
I see it too...

**Comment by isidorn** [comment]
People see it all the time, adding important to raise awerness

**Comment by joaomoreno** [comment]
![all the time](https://m.popkey.co/66ce04/WxEN7.gif)

**Comment by joaomoreno** [comment]
Repro: wait 2 minutes before running a git action.
