### ISSUE TITLE
Windows Server core でエクスプローラー画面

### ISSUE THREAD

**Issue by tsumuri** [Microsoft/vscode#58384]
Windows Server core のファイルメニューより[ファイルを開く][フォルダーを開く]を選択するとVScodeが終了してしまいます。

メモ帳にて[開く]を選択するとエクスプローラーのような画面が出ると思いますが、Server Core でもこの機能を実装できるようにしてほしいです。

**Comment by joaomoreno** [comment]
Can you elaborate with a screen recording?
