### ISSUE TITLE
Allow rejections in RenameProvider.prepareRename

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#58394]
From #58393

**Problem**
`RenameProvider.provideRenameEdits` is only invoked after we have shown the rename input and the user has tried to enter a new name. This can result is a frustrating UX if rename is not valid, such as trying to rename `class` in `class Foo {}`. In these cases, I believe we should show an error message as soon as the rename is triggered 

**Proposal**
Allow a rename provider to reject a rename before it begins by returning a rejected promise from `prepareRename`. The returned error would be shown to users in the editor, just like rejections from `provideRenameEdits`

**Comment by mjbvz** [comment]
Actually this already sort of works. A few problems:

-  The rejection in `prepareRename` is treated as an error if you are debugging (and maybe in our logs?)
- You cannot return a string in the rejection; it has to be an error object
- The inline error message is prefixed with `Error: `:

<img width="434" alt="screen shot 2018-09-10 at 6 10 29 pm" src="https://user-images.githubusercontent.com/12821956/45332380-15dca800-b525-11e8-9397-0c9ecfef8e7b.png">

**Comment by jrieken** [comment]
Yeah, we can make it accept a string, just like provideRenameEdits does
