### ISSUE TITLE
Hang on start on systems with cmd.exe blocked.

### ISSUE THREAD

**Issue by iboyperson** [Microsoft/vscode#58392]
- VSCode Version: 1.27.1
- OS Version: Windows 10 Build: 1607

Steps to Reproduce:

1. Attempt to launch VSCode (Portable or Other) on a computer with cmd.exe blocked.

Fix:
The issue is resolved by killing the cmd.exe process spawned at start. After doing this one the issue appears to go away.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
What do you mean by "cmd.exe blocked"?

**Comment by iboyperson** [comment]
Sorry should have been more descriptive. What I mean by "cmd.exe blocked" is when access to cmd.exe is restricted by an administrator. For context I am trying to get vscode working on laptops at my school at which they restrict access to cmd.exe.

**Comment by joaomoreno** [comment]
What if you download the ZIP installer and simply double click Code.exe?

**Comment by iboyperson** [comment]
Running Code.exe from the zip results in the same hang

**Comment by joaomoreno** [comment]
Can you confirm that `cmd.exe` is spawned when you double click that zip? Can you figure out any more details?

**Comment by iboyperson** [comment]
It is difficult to gather any more information as this issue is because we have no administrative rights on the computer. If there is any information I can provide without admin privileges however feel free to ask for it.

**Comment by sbatten** [comment]
the getmac npm package we use calls getmac by opening cmd.exe as indicated by @iboyperson 

I've created an upstream issue to pass `shell: false` when spawning getmac to avoid cmd.exe creation.

For now we can timeout the call in the event that getmac isn't responding
