### ISSUE TITLE
Add secondary button style to theme

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#58399]
Related to https://github.com/Microsoft/vscode-pull-request-github/issues/295

It would be great if there was an option for a secondary button style so that views with multiple buttons could differentiate the primary vs secondary. Below is a webview example that has multiple buttons:

![image](https://user-images.githubusercontent.com/35271042/45335156-e339ac00-b532-11e8-902e-22d234219162.png)

It would be great if we could get the following:
- button.secondary.background
- button.secondary.foreground
- button.secondary.hoverBackground

**Comment by cleidigh** [comment]
FWIW:  Slightly related, stronger differentiation of focused button... importance will be increased with multiple button types.

**Comment by bpasero** [comment]
@misolori would it work if we had a lighter blue for secondary buttons maybe? Feel free to make a proposal (best with a screenshot like the one above where this is applied).

I think we should implement a secondary color only for our themes and let theme authors decide wether they want to implement it or not so that we are not breaking existing themes too much.

**Comment by misolori** [comment]
@bpasero I agree that these shouldn't break existing themes and should only be optional styles to be used. My thinking was using a neutral color and allowing the default to serve as the "primary" style like so:

**Dark** 
![image](https://user-images.githubusercontent.com/35271042/45339968-7382eb80-b549-11e8-8d96-3ae8ab0230e1.png)


**Light**
![image](https://user-images.githubusercontent.com/35271042/45339989-9dd4a900-b549-11e8-8ae2-9cd9f46ec1c2.png)

**Proposed colors**
```typescript
export const buttonSecondaryBackground = registerColor('button.secondary.background', { dark: '#0E639C', light: '#007ACC', hc: null }, nls.localize('buttonSecondaryBackground', "Secondary button background color."));
export const buttonSecondaryHoverBackground = registerColor('button.secondary.hoverBackground', { dark: lighten(buttonSecondaryBackground, 0.2), light: darken(buttonSecondaryBackground, 0.2), hc: null }, nls.localize('buttonSecondaryHoverBackground', "Secondary button background color when hovering."));
```

**Comment by bpasero** [comment]
@misolori yeah looks like it could work. Are you suggesting to use these styles consistently across the UI or only in specific places? E.g. notifications often show multiple buttons, but we do not really have the concept of a default button in our APIs.

**Comment by bpasero** [comment]
@misolori not sure, if we change this people might confuse the grey color as a "disabled" button. We can take it to the UX call maybe.

**Comment by bpasero** [comment]
@misolori didn't we do this or talked about it recently?

**Comment by misolori** [comment]
@bpasero yes, we discussed it in our UX sync call and said we should add it. I'll add it to the backlog.

**Comment by misolori** [comment]
Verifiers: check that you can use and modify the following colors in a Webview:

- `button.secondaryForeground`
- `button.secondaryBackground`
- `button.secondaryHoverBackground`
