### ISSUE TITLE
Preview in Issue Reporter opens the browser behind it

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#58390]
Issue Type: <b>Bug</b>

- Use Issue reporter and click on the Preview on Github button
- The browser opens behind the Issue reporter instead of in front of it.

This doesnt happen if the browser is already open in a different monitor or if it was last opened in a different monitor

Extra info: My default browser is Edge

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

**Comment by RMacfarlane** [comment]
@ramya-rao-a Does this also happen on 1.27? I'm always seeing the browser open in front of the issue reporter, and based on 

```

	interface OpenExternalOptions {
		/**
		 * true to bring the opened application to the foreground. The default is true.
		 */
		activate: boolean;
	}
```

in `electron.d.ts` this should be the default behavior

**Comment by ramya-rao-a** [comment]
Yes, still happening with 1.27

**Comment by RMacfarlane** [comment]
I wasn't able to repro the issue myself, but I changed the call to `openExternal` to be on the main process instead of the renderer, which should fix this according to https://github.com/electron/electron/issues/4349#issuecomment-256365499 

Let me know if it works for you
