### ISSUE TITLE
Don't show rename UI if you cannot actually rename something in js/ts

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#58393]
1. In a js file:

```js
class Foo {}
```

1. Trigger a rename on `class` 

**Bug**
See the rename input box and you can enter text. Only upon pressing enter do you see the `You cannot rename this element` message

**Comment by mjbvz** [comment]
This was sort of busted by https://github.com/Microsoft/TypeScript/issues/27373. You should see a generic error message when trying to rename something like `class`

Try using TS 3.0 to see the correct error message

**Comment by isidorn** [comment]
Adding verified since the rename inbox box is no longer shown. But yes i get a funky error message
