### ISSUE TITLE
编码时候输入中文卡顿

### ISSUE THREAD

**Issue by GamesSoul** [Microsoft/vscode#58398]
近期更新后，敲代码的时候输入中文特别卡顿，需要等待很久，甚至会未响应提示是否重新打开vscode

**Comment by joaomoreno** [comment]
This issue was closed because it doesn't meet our standards of a properly filled issue. Please read our guide about [Submitting Bugs and Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).
