### ISSUE TITLE
zsh: fork failed: resource temporarily unavailable

### ISSUE THREAD

**Issue by atian25** [Microsoft/vscode#58397]
Issue Type: <b>Bug</b>

```bash
➜  egg git:(2.11.0) ✗ git add .
➜  egg git:(2.11.0) ✗ git commit -m 'Release 2.11.0'
zsh: fork failed: resource temporarily unavailable
iterm2_decorate_prompt:11: fork failed: resource temporarily unavailable
zsh: fork failed: resource temporarily unavailable

zsh: fork failed: resource temporarily unavailable

zsh: fork failed: resource temporarily unavailable

➜  egg git:(2.11.0) ✗ git commit -m 'Release 2.11.0'
[2.11.0 4ed30f079] Release 2.11.0
 2 files changed, 58 insertions(+), 9 deletions(-)
```

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:14:32.385Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 6, 5|
|Memory (System)|16.00GB (0.36GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_31202752|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
output-colorizer|IBM|0.1.2
Bookmarks|ale|9.0.3
copy-syntax|ati|0.5.1
vscode-gpm|axe|1.0.0
transformer|dak|1.6.0
vscode-markdownlint|Dav|0.20.0
vscode-eslint|dba|1.5.0
vscode-npm-source|dku|1.0.0
gitlens|eam|8.5.6
tslint|eg2|1.0.38
code-runner|for|0.9.4
beautify|Hoo|1.4.2
path-autocomplete|ion|1.12.0
search-node-modules|jas|1.3.0
vscode-github|Kni|0.30.0
vscode-mocha-sidebar|mat|0.20.18
vsliveshare|ms-|0.3.623
debugger-for-chrome|msj|4.10.0
node-modules-resolve|nau|1.0.2
syncing|non|1.8.1
vetur|oct|0.12.6
vscode-docker|Pet|0.2.0
gitlink|qez|0.4.5
LiveServer|rit|5.1.1
unittest-navigate|rob|0.0.2
es6-mocha-snippets|spo|0.2.1
code-navigation|vik|0.2.0
JavaScriptSnippets|xab|1.7.0

</details>

**Comment by joaomoreno** [comment]
Why do you think this is an issue of VS Code?

**Comment by atian25** [comment]
only happen in new version of vscode terminal, not at standalone iterms. I will try to make it clear later

**Comment by Tyriar** [comment]
I don't think this is an issue with VS Code, it even mentions some iterm2 in the message 😕 

```
iterm2_decorate_prompt:11: fork failed: resource temporarily unavailable
```

I'd love to be proven wrong though, let me know if you have more info on a repro.

**Comment by jamesone** [comment]
I can confirm that this occurs for me. Sometimes when I click on an intellisense path (e.g on an imported component), vscode will show a blue loading bar above the tabs which keeps on displaying. As soon as I try click on the imported component, it'll show the loading bar, and prevent me from using my terminal which prints: `zsh: fork failed: resource temporarily unavailable` whenever I try run a command.
