### ISSUE TITLE
Add Quick info panel 

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#584]
_From @Krzysztof-Cieslak on October 11, 2015 18:9_

Quick Info panel is "small margin located at the bottom of the code editor. It automatically shows errors and warnings under the cursor, eliminating the need to use mouses to see tooltips with the same info." 

That's how it looks like in Ionide Atom - 
![image](https://cloud.githubusercontent.com/assets/5427083/10418149/4e564d68-7053-11e5-96ce-ef123dfd91da.png) Same feature is also implemented in Visual F# Power Tools - https://fsprojects.github.io/VisualFSharpPowerTools/quickinfopanel.html

IMO, it might be interesting addition to language services API.

_Copied from original issue: Microsoft/vscode-extensionbuilders#6_

**Comment by seanmcbreen** [comment]
_From @reflectiondm on October 11, 2015 21:3_

Great thought!

**Comment by seanmcbreen** [comment]
_From @egamma on October 12, 2015 7:40_

There are the go to next/previous error actions (F8). They show you the error/warning in place using the peek UI also avoid the need for hovering:

![error-peek](https://cloud.githubusercontent.com/assets/172399/10423272/166fbd18-70c5-11e5-9231-a3e22b0633e3.png)

**Comment by seanmcbreen** [comment]
_From @Krzysztof-Cieslak on October 12, 2015 8:48_

Right, this handles error and warnings. But some editors / plugins are using it also for different information (I haven't mentioned it in 1st post, my bad) such as type / function signatures (what is useful in languages with strong type inference - F# / OCaml / Haskell etc.)

**Comment by seanmcbreen** [comment]
_From @jrieken on October 14, 2015 12:41_

Agreed, we have `setStatusBarMessage` already today but we don't expose calling language service features from extensions.

**Comment by seanmcbreen** [comment]
_From @jrieken on October 14, 2015 12:50_

somehow related to #10, at least my previous comment...

**Comment by seanmcbreen** [comment]
_From @jrieken on October 31, 2015 13:3_

So, with 0.10 there be will some sweet changes that enable this. We will expose the brains-behind language service features as commands. For instance all folks that can compute the definition of a symbol can be trigger like so:

```javascript
commands.executeCommand('vscode.executeDefinitionProvider', <args>)
    .then(locations => {...})
```

The arguments will correspond to those the provider needs, usually a document and a position or range. This isn't a UI operation but just the back-office operation. An extension could do the following:

* listen to selection changes
* trigger the commands to compete extra information/hover
* show the results in the status bar -> :dancers:

**Comment by jrieken** [comment]
Should be done as outlined in my previous comment.
