### ISSUE TITLE
new version translate incomplete

### ISSUE THREAD

**Issue by yipanhuasheng** [Microsoft/vscode#58407]
There is a new version update today, but the file's property interface and client's settings interface are in English and are not translated into Chinese.

**Comment by dbaeumer** [comment]
@yipanhuasheng can you please provide a screen shot. It is translated for me:

<img width="1013" alt="capture" src="https://user-images.githubusercontent.com/1931590/45347724-13259580-b5ad-11e8-9f45-ffd514f855f8.png">

@roblourens assigning to you. If there are untranslated strings check if they are localized. If, please assign to @danyeh

**Comment by yipanhuasheng** [comment]
It’s ok now.
