### ISSUE TITLE
Can't move folder/file to root

### ISSUE THREAD

**Issue by QianChenglong** [Microsoft/vscode#58401]
![image](https://user-images.githubusercontent.com/1881126/45337644-a1087d00-b5bb-11e8-93a1-a8ce47366c5e.png)

Create folder always in clicked folder AND can't move to top level !

**Comment by QianChenglong** [comment]
I'm sure no existing one. I just need to create or move folder to top level/

**Comment by QianChenglong** [comment]
How to move an existing one to top?

**Comment by isidorn** [comment]
Just drop it in the empty area below.
I understand this can be hard to do if you have too many files and fodlers but there is already an issue covering that.
