### ISSUE TITLE
Split screen issues

### ISSUE THREAD

**Issue by pocalyps** [Microsoft/vscode#58406]
Issue Type: <b>Bug</b>

Whenever I split view, I can't type anything in the new, split tab.

-I have an html and a css file open in my window. 
-I then initiate split view by either:
a. dragging one tab to the right side of the window
b. click the split view icon on the top right
-I can't type anything in that new tab.

I have already restarted VS a couple of times. I can still type in single view, but would definitely like to have the option available.

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:20:44.170Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|15, 13, 15|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv|/private/var/folders/1q/43mq9h910x1c2gfqccs33g_h0000gp/T/AppTranslocation/3C9C4FF4-D8E5-45A5-9B87-64FBCB8BC82B/d/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-markdownlint|Dav|0.20.0
githistory|don|0.4.2
gitlens|eam|8.5.6
vscode-html-css|ecm|0.2.0
auto-rename-tag|for|0.0.15
vs-color-picker|lih|0.7.0
vsliveshare|ms-|0.3.666
team|ms-|1.136.0
live-server-preview|neg|0.1.2
LiveServer|rit|5.1.1
vscode-spotify|shy|2.6.1
html5-boilerplate|sid|1.0.3
ayu|tea|0.16.0
vscode-wakatime|Wak|1.2.3

(7 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
@ZombieWombie can you share a video of what happens exactly?
