### ISSUE TITLE
Some menu/command callbacks include a new parameter { groupId: number }

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#58413]
Issue Type: <b>Bug</b>

It seems that certain menu/command callbacks include a new parameter `{ groupId: number }` -- which seems to be the number of the editor group. It seems like on command executed from the `editor/title` context have this new parameter.

Is this intentional? If so, why is it only on `editor/title` and not `editor/context` or `editor/title/context`?

VS Code version: Code - Insiders 1.28.0-insider (96854113091424c07b28ba84b82b75a88b8455cb, 2018-09-10T05:18:57.119Z)
OS version: Windows_NT x64 10.0.17755

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (14.34GB free)|
|Process Argv|C:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by bpasero** [comment]
Closing, I can see the same context for `editor/title` as for `editor/title/context`. The editor context menu has no awareness of the editor group currently and I would leave it as that.
