### ISSUE TITLE
Unfolding not possible

### ISSUE THREAD

**Issue by DarkLite1** [Microsoft/vscode#58414]
Consider the following PowerShell file:

**Test.ps1**

```powershell
        $ImportedMatrix = @(Get-ChildItem -Path ImportDir:\* -Include *.xlsx -File).Where({
            $_.FullName -ne $DefaultsItem.FullName}).ForEach({
            Try { 
                $Obj = [PSCustomObject]@{
                    File = @{
                        Item = $_
                        SaveFullName = $_.FullName
                        ExcelInfo = $null
                        LogFolder = $null
                        Check = @()
                    }
                    Settings = @()
                    Permissions = @{ 
                        Import = @()
                        Check = @()
                    }
                }

                $Obj
            }
            Catch {
                Write-Warning $_
                Send-MailHC -To $ScriptAdmin -Subject FAILURE -Priority High -Message $_ -Header $ScriptName
                Write-EventLog @EventErrorParams -Message ($env:USERNAME + ' - ' + "FAILURE:`n`n- " + $_)
                Write-EventLog @EventEndParams; Exit 1
            }
        })
```

1. Perform the action `Fold all` with the command palette
2. Try to `click` the `plus sign` to unfold, notice that unfolding is not possible with the mouse.

![image](https://user-images.githubusercontent.com/10828570/45294815-df8b3280-b4fc-11e8-83f3-44f5757d80dd.png)

Workarounds: 
1. `Unfold all` with the command palettte.
2. Move the code `$_.FullName -ne $DefaultsItem.FullName}).ForEach({` after the `Where` clause on the same line

```
Version: 1.28.0-insider (user setup)
Commit: 96854113091424c07b28ba84b82b75a88b8455cb
Date: 2018-09-10T05:18:57.119Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

**Comment by aeschli** [comment]
It's a problem in the Powershell extension. It returns a range 1-2 which overlaps with the next range.
![screenshot from 2018-09-11 16-04-24](https://user-images.githubusercontent.com/6461412/45365274-74189200-b5dc-11e8-97c7-f1bba0f32181.png)

**Comment by aeschli** [comment]
This issue was moved to PowerShell/vscode-powershell#1523
