### ISSUE TITLE
JSON: DeprecationWarning: Buffer() is deprecated due to security and usability issues

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#58417]
I get this popping up in the Electron 3.0.x exploration builds everytime I start VSCode and open a file:

![image](https://user-images.githubusercontent.com/900690/45343504-6396f600-b5a1-11e8-92de-841ce603aa9d.png)

I created and merged https://github.com/Microsoft/vscode-languageserver-node/pull/408 a while ago but I guess we are not using that version yet?

**Comment by dbaeumer** [comment]
Yes. I merged it in and created new pre-releases. I will release an official new version this week which people need to adopt. There is nothing else I can do. 

Assigning the item to @aeschli to adopt the new version. Will ping you when available.
