### ISSUE TITLE
VS Code is not deleting the folder from the folder

### ISSUE THREAD

**Issue by yvrkarthik** [Microsoft/vscode#58419]
- VSCode Version: 1.27.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open a folder containing project code.
2. Create a docs folder
3. Right-click on the folder and delete the folder
    ![image](https://user-images.githubusercontent.com/1669197/45344612-417c9280-b5f8-11e8-9c3c-7a6245d5afa7.png)
4. Editor will delete the folder from its explorer  
   ![image](https://user-images.githubusercontent.com/1669197/45344645-5d803400-b5f8-11e8-84eb-fb7d9768e27e.png)
5. But the folder still exists in the project directory    
   ![image](https://user-images.githubusercontent.com/1669197/45344743-94564a00-b5f8-11e8-8bf5-49f45ab8f0cb.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by yvrkarthik** [comment]
Here's the output from the console 

TRACE openWorkbench configuration {"_":[],"help":false,"h":false,"version":false,"v":false,"wait":false,"w":false,"diff":false,"d":false,"add":false,"a":false,"goto":false,"g":false,"new-window":false,"n":false,"unity-launch":false,"reuse-window":false,"r":false,"open-url":false,"performance":false,"p":false,"prof-startup":false,"verbose":true,"logExtensionHostCommunication":false,"disable-extensions":false,"disableExtensions":false,"list-extensions":false,"show-versions":false,"nolazy":false,"issue":false,"skip-getting-started":false,"skip-release-notes":false,"sticky-quickopen":false,"disable-restore-windows":false,"disable-telemetry":false,"disable-updates":false,"disable-crash-reporter":false,"skip-add-to-recently-opened":false,"status":false,"s":false,"file-write":false,"file-chmod":false,"driver-verbose":false,"appRoot":"c:\\Program Files\\Microsoft VS Code\\resources\\app","machineId":"4947608b2ed236940c2907200d8121a996d21e8aa3a966afd725405fa687abaf","mainPid":14380,"execPath":"C:\\Program Files\\Microsoft VS Code\\Code.exe","userEnv":{"VSCODE_IPC_HOOK":"\\\\.\\pipe\\55d605eb18f3d56ea831b3d18bbffb18-1.27.1-main-sock","VSCODE_NLS_CONFIG":"{\"locale\":\"en-us\",\"availableLanguages\":{},\"_languagePackSupport\":true}","VSCODE_LOGS":"C:\\Users\\Rajiv_yanamandra.DC01\\AppData\\Roaming\\Code\\logs\\20180911T204116"},"folderUri":{"$mid":1,"fsPath":"e:\\Github\\Repos\\BuildConnectionStrings","external":"file:///e%3A/Github/Repos/BuildConnectionStrings","path":"/e:/Github/Repos/BuildConnectionStrings","scheme":"file"},"filesToOpen":[],"filesToCreate":[],"filesToDiff":[],"nodeCachedDataDir":"C:\\Users\\Rajiv_yanamandra.DC01\\AppData\\Roaming\\Code\\CachedData\\5944e81f3c46a3938a82c701f96d7a59b074cfdc","backupPath":"C:\\Users\\Rajiv_yanamandra.DC01\\AppData\\Roaming\\Code\\Backups\\897054deff5c74d25af5c38308387ddb","windowId":1,"logLevel":0,"zoomLevel":0,"fullscreen":false,"highContrast":false,"accessibilitySupport":false,"maximized":true,"frameless":true,"perfEntries":["mark","main:started",1536655276636,0,0,"mark","main:appReady",1536655276679,0,1,"mark","main:loadWindow",1536655276903,0,0,"mark","main:loadWindow",1536655343078,0,1]}
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE lifecycle: starting up (startup kind: 1)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE lifecycle: phase changed (value: 2)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE terminalInstance#ctor (id: 1) Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE lifecycle: phase changed (value: 3)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411  INFO no standard startup: not just one text editor
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 DEBUG Terminal process launching Object E:\Github\Repos\BuildConnectionStrings 186 21 Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE Sending broadcast to main from window 1:  Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/optInStatus Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/activatePlugin Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/keyboardLayout Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/workspaceLoad Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/editorOpened Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/extensionsScanned Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3260 [PeterJausovec.vscode-docker]: Command `vscode-docker.delete-ACR-Image` appears multiple times in the `commands` section.
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/extensionsMessage Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/customKeybindingsChanged Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4236 Overwriting grammar scope name to file mapping for scope source.sql.
Old grammar file: file:///c%3A/Program%20Files/Microsoft%20VS%20Code/resources/app/extensions/sql/syntaxes/sql.tmLanguage.json.
New grammar file: file:///c%3A/Users/Rajiv_yanamandra.DC01/.vscode/extensions/ms-mssql.mssql-1.4.0/syntaxes/SQL.plist
e.register @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4236
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 DEBUG Terminal process ready (shellProcessId: 24348)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/activatePlugin Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/galleryService:query Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE RequestService#request https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/startupTimeVaried Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE lifecycle: phase changed (value: 4)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE RequestService#request https://az764295.vo.msecnd.net/experiments/experiments.json
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/experiments Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/workspace.remotes Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/workspace.hashedRemotes Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/workspce.tags Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/activatePlugin Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/activatePlugin Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/activatePlugin Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/activatePlugin Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/activatePlugin Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/activatePlugin Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/activatePlugin Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/activatePlugin Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/activatePlugin Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/activatePlugin Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/activatePlugin Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/activatePlugin Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/activatePlugin Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/activatePlugin Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/activatePlugin Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/activatePlugin Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/activatePlugin Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/activatePlugin Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/activatePlugin Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE SearchService#search {"folderQueries":[{"folder":{"$mid":1,"fsPath":"e:\\Github\\Repos\\BuildConnectionStrings","external":"file:///e%3A/Github/Repos/BuildConnectionStrings","path":"/e:/Github/Repos/BuildConnectionStrings","scheme":"file"}}],"type":1,"exists":true,"includePattern":{"*.csproj":true,"*.sln":true,"*.csx":true,"*.cake":true,"**/*.csproj":true,"**/*.sln":true,"**/*.csx":true,"**/*.cake":true},"useRipgrep":true,"ignoreSymlinks":false}
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:276 [Extension Host] Looking for parseable documents... (at C:\Users\Rajiv_yanamandra.DC01\.vscode\extensions\Zignd.html-css-class-completion-1.17.1\out\src\extension.js:28:21)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE ContextViewService#showContextView
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE ContextViewService#hideContextView
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:276 [Extension Host] vscode-icons is active! (at activate (C:\Users\Rajiv_yanamandra.DC01\.vscode\extensions\robertohuertasm.vscode-icons-7.26.0\out\src\index.js:44:13))
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE ContextViewService#showContextView
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE SearchService#search {"folderQueries":[{"folder":{"$mid":1,"fsPath":"e:\\Github\\Repos\\BuildConnectionStrings","external":"file:///e%3A/Github/Repos/BuildConnectionStrings","path":"/e:/Github/Repos/BuildConnectionStrings","scheme":"file"}}],"type":1,"maxResults":null,"disregardExcludeSettings":false,"useRipgrep":true,"ignoreSymlinks":false,"includePattern":{"**/*.{css,html}":true},"fileEncoding":"utf8","excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true}}
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE SearchService#search {"folderQueries":[{"folder":{"$mid":1,"fsPath":"e:\\Github\\Repos\\BuildConnectionStrings","external":"file:///e%3A/Github/Repos/BuildConnectionStrings","path":"/e:/Github/Repos/BuildConnectionStrings","scheme":"file"}}],"type":1,"maxResults":null,"disregardExcludeSettings":false,"useRipgrep":true,"ignoreSymlinks":false,"includePattern":{"tsconfig.json":true},"excludePattern":{"**/node_modules/**":true,"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true},"fileEncoding":"utf8"}
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE SearchService#search {"folderQueries":[{"folder":{"$mid":1,"fsPath":"e:\\Github\\Repos\\BuildConnectionStrings","external":"file:///e%3A/Github/Repos/BuildConnectionStrings","path":"/e:/Github/Repos/BuildConnectionStrings","scheme":"file"}}],"type":1,"maxResults":null,"disregardExcludeSettings":false,"useRipgrep":true,"ignoreSymlinks":false,"includePattern":{"**/package.json":true},"excludePattern":{"**/node_modules/**":true,"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true},"fileEncoding":"utf8"}
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/activatePlugin Object
24/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE CommandService#executeCommand setContext
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE SCMService#registerSCMProvider
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE CommandService#executeCommand setContext
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3277 [File Watcher (C#)] [CHANGED] e:\Github\Repos\BuildConnectionStrings\.git\FETCH_HEAD
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3277 [File Watcher (C#)]  >> normalized [CHANGED] e:\Github\Repos\BuildConnectionStrings\.git\FETCH_HEAD
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 DEBUG SearchService#search rg --files --hidden --case-sensitive -g '/*.csproj' -g '/*.sln' -g '/*.csx' -g '/*.cake' -g '**/*.csproj' -g '**/*.sln' -g '**/*.csx' -g '**/*.cake' --no-ignore --follow --quiet -- '.'
 - cwd: e:\Github\Repos\BuildConnectionStrings
 - Sibling clauses: {}
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 DEBUG SearchService#search rg --files --hidden --case-sensitive -g '**/*.{css,html}' -g '!**/.git' -g '!**/.svn' -g '!**/.hg' -g '!**/CVS' -g '!**/.DS_Store' --no-ignore --follow -- '.'
 - cwd: e:\Github\Repos\BuildConnectionStrings
 - Sibling clauses: {}
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE CommandService#executeCommand setContext
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE CommandService#executeCommand workbench.files.action.refreshFilesExplorer
2/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE CommandService#executeCommand setContext
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 DEBUG SearchService#search rg --files --hidden --case-sensitive -g '/tsconfig.json' -g '!**/node_modules/**' -g '!**/.git' -g '!**/.svn' -g '!**/.hg' -g '!**/CVS' -g '!**/.DS_Store' --no-ignore --follow -- '.'
 - cwd: e:\Github\Repos\BuildConnectionStrings
 - Sibling clauses: {}
4/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE CommandService#executeCommand setContext
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE ContextViewService#hideContextView
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 DEBUG SearchService#search rg --files --hidden --case-sensitive -g '**/package.json' -g '!**/node_modules/**' -g '!**/.git' -g '!**/.svn' -g '!**/.hg' -g '!**/CVS' -g '!**/.DS_Store' --no-ignore --follow -- '.'
 - cwd: e:\Github\Repos\BuildConnectionStrings
 - Sibling clauses: {}
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE SearchService#search: 817ms
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/searchComplete Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE CommandService#executeCommand setContext
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE SearchService#search: 963ms
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/searchComplete Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE SearchService#search: 979ms
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/searchComplete Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:276 [Extension Host] Found all parseable documents. (at C:\Users\Rajiv_yanamandra.DC01\.vscode\extensions\Zignd.html-css-class-completion-1.17.1\out\src\extension.js:35:21)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:276 [Extension Host] Parsing documents and looking for CSS class definitions... (at C:\Users\Rajiv_yanamandra.DC01\.vscode\extensions\Zignd.html-css-class-completion-1.17.1\out\src\extension.js:40:21)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE SearchService#search: 1358ms
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/searchComplete Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3277 [File Watcher (C#)] [CHANGED] e:\Github\Repos\BuildConnectionStrings\.git\FETCH_HEAD
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3277 [File Watcher (C#)]  >> normalized [CHANGED] e:\Github\Repos\BuildConnectionStrings\.git\FETCH_HEAD
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE RequestService#request https://az764295.vo.msecnd.net/extensions/workspaceRecommendations.json.gz
5/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE CommandService#executeCommand setContext
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE ContextViewService#showContextView
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:276 [Extension Host] Summary: (at C:\Users\Rajiv_yanamandra.DC01\.vscode\extensions\Zignd.html-css-class-completion-1.17.1\out\src\extension.js:60:21)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:276 [Extension Host]% 106 parseable documents found (at C:\Users\Rajiv_yanamandra.DC01\.vscode\extensions\Zignd.html-css-class-completion-1.17.1\out\src\extension.js:61:21)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:276 [Extension Host]% 13375 CSS class definitions found (at C:\Users\Rajiv_yanamandra.DC01\.vscode\extensions\Zignd.html-css-class-completion-1.17.1\out\src\extension.js:62:21)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:276 [Extension Host]% 2036 unique CSS class definitions found (at C:\Users\Rajiv_yanamandra.DC01\.vscode\extensions\Zignd.html-css-class-completion-1.17.1\out\src\extension.js:63:21)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:276 [Extension Host]% 1 failed attempts to parse. List of the documents: (at C:\Users\Rajiv_yanamandra.DC01\.vscode\extensions\Zignd.html-css-class-completion-1.17.1\out\src\extension.js:64:21)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:276 [Extension Host] /e:/Github/Repos/BuildConnectionStrings/node_modules/serve-index/public/directory.html
 (at C:\Users\Rajiv_yanamandra.DC01\.vscode\extensions\Zignd.html-css-class-completion-1.17.1\out\src\extension.js:65:21)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/activatePlugin Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:276 [Extension Host] Git extension API method 'getGitPath' is deprecated. (at c.r.value (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\dist\main.js:1:594904))
t.log @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:276
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE CommandService#executeCommand setContext
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE telemetry/workbenchActionExecuted Object
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE ContextViewService#hideContextView
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE CommandService#executeCommand moveFileToTrash
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE DialogService#confirm Are you sure you want to delete 'docs' and its contents?
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3277 [File Watcher (C#)] [DELETED] e:\Github\Repos\BuildConnectionStrings\docs
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3277 [File Watcher (C#)]  >> normalized [DELETED] e:\Github\Repos\BuildConnectionStrings\docs
2/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE CommandService#executeCommand setContext
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1411 TRACE CommandService#executeCommand workbench.action.toggleDevTools

**Comment by bpasero** [comment]
@yvrkarthik yeah looks like the delete goes through, at least from this line:

` >> normalized [DELETED] e:\Github\Repos\BuildConnectionStrings\docs`

Is the folder empty after this?

**Comment by yvrkarthik** [comment]
@bpasero no, the folder the still has contents. the folder just disappears from the editor's explorer.
   
   ![image](https://user-images.githubusercontent.com/1669197/45350480-fc605c80-b607-11e8-9e03-e0af0c4f5e1f.png)

**Comment by bpasero** [comment]
@yvrkarthik any difference if you select Shift before opening the menu and then pick "Delete Permanently"? This will bypass the trash, so take caution.

**Comment by yvrkarthik** [comment]
@bpasero selecting Shift before opening the menu did delete the contents in the folder but has thrown a system error as it found a subfolder

![image](https://user-images.githubusercontent.com/1669197/45352362-72ff5900-b60c-11e8-89f5-fac21aa9ca67.png)

but after selecting retry, it has deleted both the folder and subfolder

**Comment by bpasero** [comment]
@yvrkarthik could be that some other process locked that folder for some reason. Does it reproduce now with other folders too?

**Comment by yvrkarthik** [comment]
I have found the root cause of the issue. I have installed a node module called cpx and using it to copy files from the build folder to docs folder after building the app.  This module is holding a lock onto the docs folder. So, I will close the issue now.
