### ISSUE TITLE
After upgrade from 1.25 to 1.26 and 1.27 emmet doesn't  work well CSS

### ISSUE THREAD

**Issue by STurbiarz** [Microsoft/vscode#58424]
Issue Type: <b>Bug</b>

Hello, I have problem with emmet. When i write CSS code and click TAB to confirm code and i want to change declared value i dont have tips.

Example:
position: relative; If i want to change to absolute i have to delete and move right and then left to show TIPS.

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:14:32.385Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (1.64GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_233529|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.59
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.6.1
auto-rename-tag|for|0.0.15
code-runner|for|0.9.4
color-highlight|nau|2.3.0
LiveServer|rit|5.1.1
vscode-icons|rob|7.26.0

(1 theme extensions excluded)

</details>

**Comment by ramya-rao-a** [comment]
Emmet in css is used to provide abbreviations that expand to a property - value pair.

In your example, `position: relative` is already a property - value pair
After deleting "relative", you are expecting emmet to suggest "absolute" which is not what emmet does. There is no abbreviation to expand at this point.

Auto-completion/tips for the value is provided by the css extension. So if you have `position: ` and hit Ctrl+Space to trigger auto-completion , then you will get all applicable values for the "position" property.

> position: relative; If i want to change to absolute i have to delete and move right and then left to show TIPS.

I tried this, and I am not able to the get the tips even after following your steps. Can you provide more detailed steps?

**Comment by ramya-rao-a** [comment]
Emmet adds a snippet. When still in snippet mode, we disabled auto-completions in 1.26.

You can either press escape key to escape the snippet mode and then press `a`, you will get the auto-completions back.

Or add the setting `"editor.suggest.snippetsPreventQuickSuggestions" : false`.

**Comment by STurbiarz** [comment]
"editor.suggest.snippetsPreventQuickSuggestions" : false.
Thank's, It's work well now.
👍
