### ISSUE TITLE
CentOS fails to launch any terminal by default

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#5842]
Testing #5463

CentOS comes with `gnome-terminal` installed, yet Code fails to launch it. It fails to launch any terminal, actually.

[This detection](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/execution/electron-browser/terminal.ts#L9) might be too overzealous.

Here's the reason:

```
[joao@localhost]~% echo $DESKTOP_SESSION 
gnome-classic
```

**Comment by joaomoreno** [comment]
Setting `"externalTerminal.linuxExec": "gnome-terminal"` works.

**Comment by Tyriar** [comment]
It would be pretty easy to change the logic to include `gnome-classic` as well to prevent a possible regression in April if you want to do that @joaomoreno, https://github.com/Microsoft/vscode/issues/5780 is planned to improve upon this in the long term.

**Comment by joaomoreno** [comment]
Not critical, no.

**Comment by Tyriar** [comment]
Closing in favor of #5780
