### ISSUE TITLE
 duplicate results

### ISSUE THREAD

**Issue by silverphoenix1110** [Microsoft/vscode#58420]
Search all show duplicate results in a file because it doesn't match case the path of the file
ex: 
1. app\controller\JobsController.php (false - duplicated)
2. app\Controller\JobsController.php (true)

I am using windows version

![capture22](https://user-images.githubusercontent.com/6715648/45345325-40d00600-b5d0-11e8-90d0-ac3c2c0cc090.PNG)

**Comment by oneslash** [comment]
@silverphoenix1110, I see you have two folders, one is with capital `C`, `Controllers` and another is `controllers`.

**Comment by roblourens** [comment]
Do you have the file open with the wrong case? Any idea where it comes from?

**Comment by silverphoenix1110** [comment]
@roblourens My project doesn't have "controller" folder. I don't know why searching return that result. 
![capture23](https://user-images.githubusercontent.com/6715648/45396200-3c552d00-b664-11e8-8599-1770c1970372.PNG)

**Comment by roblourens** [comment]
- Is the file open? 
- Does it still show up if you search without `./app`?
