### ISSUE TITLE
Provide a mechanism to set a menu entry to "checked"

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#58422]
It looks like this is a hack only for one menu item: https://github.com/Microsoft/vscode/blob/677b68da48fb4e1f518801fd06fba2200fdc6e41/src/vs/workbench/browser/parts/titlebar/menubarControl.ts#L491

There should be a general solution to set a menu entry to be checked or not. This enables: https://github.com/Microsoft/vscode/issues/46807 and https://github.com/Microsoft/vscode/issues/14986

**Comment by eamodio** [comment]
It would be wonderful if extensions could get in on this too!
