### ISSUE TITLE
UNITY PROJECT STOPS LOADED AFTER UPDATE

### ISSUE THREAD

**Issue by zendorx** [Microsoft/vscode#58429]
Issue Type: <b>Bug</b>

[fail]: OmniSharp.MSBuild.ProjectManager
        Attemped to update project that is not loaded: c:\work\IDLE-CITY\Project\Assembly-CSharp.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attemped to update project that is not loaded: c:\work\IDLE-CITY\Project\Assembly-CSharp-firstpass.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: NavMeshComponents
[fail]: OmniSharp.MSBuild.ProjectManager
        Attemped to update project that is not loaded: c:\work\IDLE-CITY\Project\Assembly-CSharp-Editor.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attemped to update project that is not loaded: c:\work\IDLE-CITY\Project\Assembly-CSharp-Editor-firstpass.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attemped to update project that is not loaded: c:\work\IDLE-CITY\Project\NavMeshComponentsEditor.csproj

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:18.328Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (7.76GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\work\IDLE-CITY\Project -r -g C:\work\IDLE-CITY\Project\Assets\Scripts\MainController.cs:1|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.59
transformer|dak|1.6.0
json-tools|eri|1.0.2
python|ms-|2018.8.0
csharp|ms-|1.16.0
python|tht|0.2.3
unity-tools|Tob|1.0.5
unity-debug|Uni|1.3.0

</details>

**Comment by zvinless** [comment]
This is probably an issue with the [C# plugin](https://github.com/OmniSharp/omnisharp-vscode/issues) (I'm seeing some issues after the plugin update too)

**Comment by extirpare** [comment]
I'm also seeing these same issues after the plugin update.

**Comment by EvheniyChobotar** [comment]
Same issue

**Comment by EvheniyChobotar** [comment]
Thank you) Finally it wotks)

ср, 12 сент. 2018 г. в 0:22, Rémi Sormain <notifications@github.com>:
