### ISSUE TITLE
Search in excluded folder

### ISSUE THREAD

**Issue by emilevictorportenart** [Microsoft/vscode#58426]
Issue Type: <b>Bug</b>

Since this morning, when I do a search, I looked for the information even in excluded folder

https://gmkr.io/s/5b97821b6ad5d3715ba5d0d2/0

Any idea?

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:14:32.385Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
indent4to2|Com|0.1.2
javascript-ejs-support|Dig|0.3.2
vscode-eslint|dba|1.5.0
vsc-material-theme|Equ|2.4.2
sass-lint|gle|1.0.3
prettify-json|moh|0.0.3
vscode-todo-highlight|way|1.0.4

(3 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
You need to toggle that button on the right side of the "files to exclude" input. It disables exclude patterns.

**Comment by emilevictorportenart** [comment]
Arf sorry for that!
