### ISSUE TITLE
This is a display bug

### ISSUE THREAD

**Issue by liper** [Microsoft/vscode#58427]
- VSCode Version: 1.27.1 (user setup)
- OS Version: Windows 10 17134.254

Steps to Reproduce:

1. set the `window.titleBarStyle` as `custom`
2. Maximizing the vscode window
3. then At the bottom of the window there will be a black border.

![The img](http://wx1.sinaimg.cn/mw690/0060lm7Tly1fv5piv8e2dj307h02odfq.jpg)

if I set the  `window.titleBarStyle` as `native` , it look like this

![](http://wx1.sinaimg.cn/mw690/0060lm7Tly1fv60v6thjsj306i02pa9w.jpg)

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by sbatten** [comment]
Seems this is an electron issue https://github.com/electron/electron/issues/8350 which merged to https://github.com/electron/electron/issues/8332
