### ISSUE TITLE
New windows open in the background

### ISSUE THREAD

**Issue by DarkLite1** [Microsoft/vscode#58423]
In the `PowerShell ISE` when executing `Get-Help Out-File -ShowWindow` the help window is opened in the front:

![image](https://user-images.githubusercontent.com/10828570/45346049-621cfc00-b5a8-11e8-930f-b42b1cfad970.png)

When executing the same command in VS Code the window is opened in the background, this makes the user think that nothing happened:
![image](https://user-images.githubusercontent.com/10828570/45346125-9c869900-b5a8-11e8-80ea-0efdcc41d149.png)

Would it be possible to change this?

```
Version: 1.28.0-insider (user setup)
Commit: ee6a21fa49bd1906bd1378c2f2714cd656409e5c
Date: 2018-09-11T05:18:39.589Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

**Comment by Tyriar** [comment]
@chrmarti I think you might have experienced this with the azure login extension? Do you know if this is a duplicate? I can't find it.

**Comment by Tyriar** [comment]
Found it: https://github.com/Microsoft/vscode/issues/42356
