### ISSUE TITLE
editorGroup.border fails when used with window.zoomLevel

### ISSUE THREAD

**Issue by PavanKundagol** [microsoft/vscode#58437]
- VSCode Version:1.26.1
- OS Version:Ubuntu16.04
Commit: 493869ee8e8a846b0855873886fc79d480d342de
Date: 2018-08-16T18:34:20.517Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Steps to Reproduce:

1. Add 
    "window.zoomLevel": -2,
    "workbench.colorCustomizations": {
        "editorGroup.border":"#ff0000"
    }
to .config/Code/User/settings.json
2. Drag the editorGroup border (may also be called as "split editor border"), observe while dragging at some places the border color disappears. And if you leave your mouse press at that time then there is no red border now. But if you drag again and leave it while the color is still visible then it stays with the same color red.
3. If you remove 
    "window.zoomLevel": -2,  
then it works fine.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/code-exploration_1.28.0-1536650436_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/VSCodeUserSetup-x64-1.28.0-exploration.exe)

**Comment by PavanKu-Kore** [comment]
Tried the Linux version, issue exists, with
"window.zoomLevel": -2,
"workbench.colorCustomizations": {
"editorGroup.border":"#ff0000"
}
dragging the border at some places makes the color disappear. 

I actually wanted to clearly see where the split is so that I can easily grab it and move it. Now because it is disappearing at some places. Its not useful to have that bright color.

**Comment by PavanKundagol** [comment]
Tried the Linux version, issue exists, with
"window.zoomLevel": -2,
"workbench.colorCustomizations": {
"editorGroup.border":"#ff0000"
}
dragging the border at some places makes the color disappear.

I actually wanted to clearly see where the split is so that I can easily grab it and move it. Now because it is disappearing at some places. Its not useful to have that bright color.

**Comment by PavanKundagol** [comment]
Just now found a workaround for my problem, by setting "editor.mouseWheelZoom" to true (default is false) I can zoom in or out just the editor text, which is what I wanted. window.zoomlevel is not useful for me. And "workbench.colorCustomizations": {"editorGroup.border":"#ff0000"} is anyway working at default window.zoomlevel.
