### ISSUE TITLE
Add Normal and Selected Foreground styles for activity bar to theme settings

### ISSUE THREAD

**Issue by lannonbr** [Microsoft/vscode#58431]
currently there is `activityBar.foreground` to style the activity bar's icons overall but I think it would also be useful to have a selected or active foreground color when you either are hovering over a icon or clicked on one.

**Comment by lannonbr** [comment]
Can this be reopened? The issue it thinks is a duplicate is actually not the same

**Comment by lannonbr** [comment]
I am referring to specifically theming these icons in the activity bar:

![screen shot 2018-09-12 at 9 39 09 am](https://user-images.githubusercontent.com/3685876/45428764-e7b7af00-b66f-11e8-9836-e2c273dc8de2.png)

I do not believe this is a duplicate of #33346

**Comment by bpasero** [comment]
Its https://github.com/Microsoft/vscode/issues/51796

**Comment by lannonbr** [comment]
Okay thank you
