### ISSUE TITLE
v1.27 can not navigate to file in terminal

### ISSUE THREAD

**Issue by lerit** [Microsoft/vscode#58432]
- VSCode Version:1.27
- OS Version:ubuntu 18
![ladpbbcc1s03tm7napjna9i_978_664_meitu_1](https://user-images.githubusercontent.com/4743467/45360508-5a8a4100-b602-11e8-9fd2-e2a36eaa33c3.jpg)

Steps to Reproduce:
1.i use eslint-friendly-formatter to show eslint error
2.when some error show in terminal,i can ctrl + the link to file and line
3.work fine in 1.26.1 and before
4.after upgrade to 1.27 ,it not work
5.it is a relative path,but work fine before
6.i guess vscode not support relative path in 1.27?
7.work still fine when a absolute path(such as generate by custom-tslint-formatters)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/58256
