### ISSUE TITLE
Clicking on image links either does not open or opens within

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#5843]
Refs: https://github.com/Microsoft/vscode/issues/5747

Repo: https://github.com/bpasero/vscode-markdown.git

Open a markdown preview (F1 > Open Markdown Preview) with badges from a readme.md (e.g. the express module) and click on a badge. On Linux nothing happens for me, on Mac I am able to open the link within the preview:

![image](https://cloud.githubusercontent.com/assets/900690/14820804/73bda63a-0bc8-11e6-9ebc-e48735f0334e.png)

**Comment by jrieken** [comment]
hm, I intercept click event on A tag with href, but this is an IMG...

**Comment by bpasero** [comment]
Maybe there is a way to prevent any page navigation in the web view? I guess soemone could also navigate via JS

**Comment by jrieken** [comment]
from my understanding that's quite hard to achieve

**Comment by bpasero** [comment]
https://github.com/electron/electron/blob/master/docs/api/web-view-tag.md#event-will-navigate

Maybe this can be prevented from the event?

**Comment by jrieken** [comment]
read the last sentence of that paragraph...

**Comment by jrieken** [comment]
also return something from `onbeforeunload` isn't helpful...

**Comment by jrieken** [comment]
I guess I will extend my link interception and if someone writes to `window.location` it's though luck

**Comment by jrieken** [comment]
I have improved the logic to detect when a links comes into play but I am still open for suggestions how to prevent page navigation, eg. writing to window.location. I tried

* the `will-navigate` event which doesn't allow cancellation and also the wrong place cos the actual contents lives inside the an iframe
* use `onbeforeunload` which didn't have an effect
* fiddle with window.location which is readonly 
* fiddle with replacing window with a proxy
* use the `sandbox` property

**Comment by bpasero** [comment]
Verified that things work with image links now. I think in the end this is something Electron should provide so that a webview - after being created - will never attempt to change its location and you get an event to handle this.
