### ISSUE TITLE
Methods labeled as properties when defined by assigning earlier-defined function to prototype

### ISSUE THREAD

**Issue by JobLeonard** [Microsoft/vscode#58439]
- VSCode Version: 1.27.1
- OS Version: Linux

![image](https://user-images.githubusercontent.com/259840/45366431-1df91e00-b5df-11e8-9faf-fec05344da20.png)

![image](https://user-images.githubusercontent.com/259840/45365884-ca3a0500-b5dd-11e8-8aa8-c76499dd56cd.png)

## Steps to Reproduce

Create a JavaScript file with the following code:

```JavaScript
function A(){
    this.test = "`this` is bound to the right object";
}

A.prototype.aMethod = function(){
    return "this is a method";
};

const someFunction = function(){ 
    return this.test; 
};

A.prototype.aProperty = someFunction;

const a = new A();

a.aProperty(); // ==> "`this` is bound to the right object"
```

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#27037
