### ISSUE TITLE
Make LoadedSourcesRequest arisen before SetBreakpointRequest

### ISSUE THREAD

**Issue by ArphonePei** [Microsoft/vscode#58438]
I am working on a debug adapter and struggling to find a way to check if the source loaded is modified. I know I could compare the checksum, but while start debugging in Attach mode, in SetBreakpointRequest I have no way to know source's checksum except sending an extra request to my application, and this seems to be not so straight forward. My idea is that if LoadedSourcesRequest could be arisen before SetBreakpointRequest then it is able to tell vscode about sources' checksum, then I will know it in SetBreakpointRequest .

**Comment by weinand** [comment]
the "LoadedSources" request is triggered by the UI (the LoadedScripts View) and is completely optional, so you cannot rely on it.

But I do not really understand what problem you are trying to solve...

**Comment by ArphonePei** [comment]
If in "Initialize" request I send response with capability "supportsLoadedSourcesRequest = true", then "LoadedSouces" request will be arisen between "SetBreakpoints" request and "ConfigrationDone" request, isn't it? My version is 1.27.0-insider. 

The source will be compiled while loading in debugee, at the same time the source file paths and location information (lines and columns) will be stored.  After that it is possible that user might modify the source files, then when breakpoint is triggered (or an exception is thrown) the location information stored in debugee will not match the location in source files. I want to check if source files are modified by comparing checksum, and my problem is while debug session is initialing there is not a good way to ask checksum from debugee (except sending a request to debugee in "SetBreakpoints" request).

**Comment by weinand** [comment]
It depends on whether you show or hide you LoadedScripts view. You cannot depend on any timing here.
You will have to use a file watcher for that (exists in extension API). Whenever a setBreakpoint event is send by VS Code to the DebugAdapter (DA), you can remember that file and let your filewatcher know that you are interested in changes to that file. If the filewatcher detects a change, you can update the breakpoint and your runtime. In addition you can send out a breakpointsEvent to update the breakpoint in VS Code too.
