### ISSUE TITLE
Copy Path Broken for Network Locations

### ISSUE THREAD

**Issue by fldcf-kkaufmann** [Microsoft/vscode#58443]
Issue Type: <b>Bug</b>

* Open a file located on a network share (using UNC path)
* Right-click tab of opened file and select "Copy Path"
* Path copied does not include server portion of UNC path
  * Also, path displayed in tab does not show server portion of UNC path

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:18.328Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|31.64GB (19.21GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.3.2
vscode-guid|hea|1.4.0
mssql|ms-|1.4.0
csharp|ms-|1.16.0
PowerShell|ms-|1.8.4
highlight-dodgy-characters|nac|1.0.0

</details>

**Comment by bpasero** [comment]
If this is true we should look into a fix for September.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/58222
