### ISSUE TITLE
OnEnterRule#oneLineAboveText

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#58440]
Via #51557 a new API sneaked in and it should go the normal API way. https://github.com/Microsoft/vscode/blob/9982055873dd8d883ece2d74a703000d02e13619/src/vs/vscode.d.ts#L3741-L3744

API proposal:
```ts
export interface OnEnterRule {
	/**
	 * This rule will only execute if the text above the this line matches this regular expression.
	 */
	previousLineText?: RegExp;
}
```

**Comment by alexandrudima** [comment]
@jrieken I have moved the new property to `vscode.proposed.d.ts` to follow the API process.

**Comment by alexandrudima** [comment]
Since we missed the API sync of last week which is according to our process the only time API can be finalized, we will have to try again in the debt week of October.

**Comment by jrieken** [comment]
There is always some slack in the process and small API changes can take the fast lane but it does require to talk to people, esp. when concerns have already been expressed.

**Comment by alexandrudima** [comment]
@aeschli I am sorry if I misread [your comment](https://github.com/Microsoft/vscode/pull/51557#issuecomment-408028392):

> @alexandrudima and @rebornix have the final word here, but [...]

I have considered (in silence) the implications of bringing tokenization information into the implementation of the OnEnterRules and I have considered it is better to leave that implementation token agnostic, as that is a personal invention I've done in the spirit of indentation rules which are also regex and not tokens based. I have briefly expressed these thoughts in my comment [here](https://github.com/Microsoft/vscode/pull/51557#issuecomment-420282000).

Given I am the author and maintainer of the OnEnter implementation, what other blessings do I need to obtain before settling this additional property added to the API?

**Comment by rebornix** [comment]
OnEnter rules is the fast lane of indentation adjustment for typing (it comes first so it shadows 4 indentation rules we introduced later). It's simple and fast as it only checks one or two lines of content (so cheaper than indentation rules which sometimes check multiple lines above) and it's token agnostic (then we don't need to worry about whether the text is cheap to tokenize). I love how this new rule is introduced.

**Comment by alexdima** [comment]
cc @jrieken @aeschli I would like to make this stable in January.

The background is we want to allow that this can be specified in the language configuration json file which will also be read by others -- https://github.com/microsoft/vscode/issues/114348 -- and we also have https://github.com/microsoft/vscode/issues/113782 which asks that this becomes stable.

**Comment by elahehrashedi** [comment]
@alexdima is this property available in insiders release right now? or do I have to use `vscode.proposed.d.ts`?

**Comment by alexdima** [comment]
@elahehrashedi In 1.53, the property will be available in stable `vscode.d.ts`, as well as it will be usable from `language-configuration.json` files. 1.53 is currently released on the Insiders Channel and in the next few days, it will be released on the Stable Channel.
