### ISSUE TITLE
there is no lightbulb in the ubuntu 15.10

### ISSUE THREAD

**Issue by soundtina** [Microsoft/vscode#5844]
- VSCode Version: 1.0
- OS Version: ubuntu 15.10

Steps to Reproduce:
1. when i type some code such as $ there is no lightbulb to suggest me to add a jquery typedscript. I know in windows there have the feature

**Comment by bpasero** [comment]
I would not expect this feature to be platform specific.

**Comment by dbaeumer** [comment]
@aeschli do we still have that feature ?

**Comment by aeschli** [comment]
The JavaScript quick fixes were lost when we updated to Salsa.

**Comment by egamma** [comment]
This is issue is obsolete, there is now support for automatic type acquisition that replaces the lightbulb.

**Comment by soundtina** [comment]
I have updated to the latest version. Thanks a lot
