### ISSUE TITLE
Sidebar Polishes and Improvements

### ISSUE THREAD

**Issue by beastdestroyer** [Microsoft/vscode#58445]
Issue Type: Polish/UI/Feature Request
No relevant issues found.

> Note: the * (**, *** etc.) denotes more info at the bottom

The items (search boxes, section headers and icons) for the sections in the sidebar are misaligned or could do with some improvements. I will go through the views in the sidebar and detail what I feel could be done.

## Explorer
Will be using this as reference for section headers and some icon alignment.

## Search View
Whilst the Search is compact and somewhat easy to get used to, it should be able to utilize the space it has and be more user friendly. My suggestions are as follows:
- Firstly, these could probably be sorted into 2 sections: `EDITOR` and `RESULTS`. (Or anything more relevant)
  - The `EDITOR` section would still contain the Search and Replace Bar, but with a few differences:
  - The `Match Case`, `Match Whole Word` and `Use Regular Expression` icons could be moved below the Replace Bar into checkboxes* rather than toggle icons, for these reasons:
    - Better Accessibility
    - According to the W3C HTML/WAI-ARIA Specs, it is recommended for forms with multiple selectable choices to use checkboxes, which is essentially what this situation is.
   - The "Replace All" icon could probably also be an actual button too
   - I'm sure the find Dialog `Ctrl/Cmd+F` could remain the same, since it is a more compact and "on-the-go" version
 - These could probably go in-line with the consistency and be sentence-case so it becomes  `Files to include` etc.
- Similarly to what I mentioned about the checkboxes, this change should also apply to the `Use Exclude Settings and Ignore Files`
  - This section should be auto-collapsed just like it is now.
- The `RESULTS` section uncollapses (is collapsed by default, when uncollapsed, it should give a message such as `There is either no match for your query or you have not searched for anything`) when results are found. Current semantics can remain the same.
![search](https://user-images.githubusercontent.com/30497573/45377554-d8dee700-b5f2-11e8-9f33-eabc9d3ec117.png)

## SCM
- The `CHANGES` section should have the same treatment as the other Section Headers (collapsible, correct background colour).
- The Icons that appear when this section header is hovered should have the equivalent spacing between them, and that spacing should be equal to the icons in Explorer
- The `...` with all those options should probably have some split into secondary dropdowns
  - Eg: Pull could have a dropdown containing Pull, `All`, `Rebase` and `From...`
  - The Commit category could be pushed into just one secondary dropdown:
    - With: `All`, `All (Amend)`, `All (Signed Off)`, `Staged` etc..
    - Alternatively, you could split it into `Commit All` and `Commit Staged dropdowns`
  - The rest seem fine
- Some reasons are:
  - Doesn't look good on zoomed in windows**
  - It is just too long in comparison to VSCode's other dropdowns, especially for it being placed slightly lower than others its size
![scm](https://user-images.githubusercontent.com/30497573/45377557-dc726e00-b5f2-11e8-8f10-f494f25dfef5.png)

## Debug
- The sections should display some text when there is no debug session currently active, such as: `There are no active debug sessions`
- The Title area where it says `Debug` is a pure mess and looks very rushed. The Dropdown for configuration could probably receive the nice looking dropdown treatment (such as the ones in the titlebar) because it looks much more aesthetically pleasing
  - It could probably also move into its own Section named `Configuration` of the sorts, with perhaps more control over what the user wants to happen. I personally don't have much experience with this menu (only started using it recently to develop extensions in my own time) so I'll leave that idea here.
  - The Start Debug arrow can move to join with the other icons there, and perhaps be a button inside the new section too
- The search box which appears when going to `BREAKPOINTS` > `Add Function Breakpoint` is not in-line with the similar one in `WATCH` > `Add Expression`***. Should probably fix.
![debug](https://user-images.githubusercontent.com/30497573/45377568-e300e580-b5f2-11e8-82f2-8a11e6d6ca1e.png)

## Extensions
Everything seems all fine and dandy!
![extensions](https://user-images.githubusercontent.com/30497573/45377581-e98f5d00-b5f2-11e8-97fb-654a4cb81c36.png)

## Padding and Searchboxes
This happens in almost every view (except Explorer) but the padding around searchboxes is off. For example, the padding on the right is ALWAYS less than the padding on the left. There are different spaces between the right edge and the icons too. My solution is to increase the right padding to be equal. It would also look much nicer!

Additionally, there should be increased bottom padding of searchboxes, this will again give it a nice equal look and be pleasing albeit small!.

> \* The Checkboxes should utilise the new custom one in the Settings GUI in my opinion. Keeps things nice and consistent. This should be applied to the Welcome page, and also in the Debug and just everywhere

> ** It also just automatically comes off when zoomed in, at least for my screen, perhaps because my height isn't that large (768px) and it goes off screen, hence my suggestions for it

> \*** That `Add Expression` checkbox also uses the Consolas font and not the default one for some reason.

EDIT: If there no changes that are detected by the SCM, there should be a line which could print: `There are no files with an SCM detected` or some sort

**Comment by joaomoreno** [comment]
Though we appreciate the enthusiasm, we can't accept this wide ranging issue. Please read our guide about [Submitting Bugs and Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).
