### ISSUE TITLE
snippets, tool tips suggestions won't go away

### ISSUE THREAD

**Issue by timestocome** [Microsoft/vscode#58448]
Issue Type: <b>Bug</b>

wth? I keep turning all this crap off and it keeps turning itself back on 

How do I remove every single suggestion, tip, or pop up in the editor?

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:18.328Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (12.92GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|1.4.6
vscode-emacs|hir|0.1.1
anaconda-extension-pack|ms-|1.0.0
python|ms-|2018.8.0
vscode-yaml|red|0.0.15

</details>

**Comment by joaomoreno** [comment]
Can you share a screenshot of what is bothering you?

**Comment by joaomoreno** [comment]
We're sorry to see you go. Let me know if you ever manage to show me a that screenshot.
