### ISSUE TITLE
Setting GUI "More Actions" Gear should not hide when menu is open

### ISSUE THREAD

**Issue by beastdestroyer** [Microsoft/vscode#58441]
Issue Type: Bug
No duplicates found.

- VSCode Version: 1.28.0-insiders
- OS Version: Windows 10 1803 17134.254

Steps to Reproduce:
1. Open Settings GUI
2. Go onto any settings' "More Actions" gear (appears next to the left of the setting on hover)
3. Click on it to open the menu, but don't click off it
4. Move your mouse anywhere else, the menu is still open but gear isn't showing, as per this screenshot:

![image](https://user-images.githubusercontent.com/30497573/45369830-b93dc380-b5de-11e8-9929-59d7ee0cedb0.png)
 

Does this issue occur when all extensions are disabled?: Yes

**Comment by beastdestroyer** [comment]
Not a duplicate

**Comment by beastdestroyer** [comment]
Also, the Gear shouls appear when the mouse is over the WHOLE setting container, not just a little area to the left of it. It makes it more noticeable

**Comment by roblourens** [comment]
> Also, the Gear shouls appear when the mouse is over the WHOLE setting container, not just a little area to the left of it. It makes it more noticeable

I disagree, we decided that's too distracting. I think it will get noticed.
