### ISSUE TITLE
Ability to specify workspaceFolder explicitly

### ISSUE THREAD

**Issue by akbyrd** [Microsoft/vscode#58444]
Currently workspaceFolder is determined by the directory containing the `.code-workspace` file. I find this to be undesirable in some circumstances. For example, I have a ton of projects cloned into a single folder

- code
  - common
  - editor
  - engine
  - ispc

Depending on my current task, I open different workspaces that include different projects and different settings. I don't want to have a bunch of loose VS Code files so I want to stick the workspace files in a .vscode subfolder like so

- code
  - .vscode
    - editor.code-workspace
    - engine.code-workspace
  - common
  - editor
  - engine
  - ispc

However, this forces `workspaceFolder` to be `.vscode` when I really want it to be the shared root folder `code`. In turn this causes issues with the C++ extension because it wants to make a `.vscode` folder in the `workspaceFolder` and I end up with nested `.vscode` folders. I _could_ have separate `.vscode` folders inside each project, but for basic stuff that can be shared across all of them, such as include directories for dependencies, I'd like the option to push it up to a shared workspace directory.

I'd like to have an option in the `.code-workspace` to override the `workspaceFolder` variable.

**Comment by bpasero** [comment]
@akbyrd can you explain what you mean by workspaceFolder? Is that a variable in settings or debug? It should never point to the location of the workspace file but rather to the folder you are currently in (e.g. in a multi root workspace it should be one of the multi root folders).

**Comment by akbyrd** [comment]
> It should never point to the location of the workspace file but rather to the folder you are currently in

Yea, I misunderstood this when making the request. Luckily default C++ settings can be specified in the workspace settings which solves my concern.
