### ISSUE TITLE
After update my editor fonts disappeared

### ISSUE THREAD

**Issue by AlexaforMuggles** [Microsoft/vscode#58456]
Issue Type: <b>Bug</b>

Hi 
After the newest update my editor fonts disappeared. Old files appear with the correct font colors but all new files are just 100% white. Furthermore it stopped adding '' when I type ' . How do I get my old settings back? Also I am pretty new to coding so please express yourself simply. Thanks. 

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:14:32.385Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|8.00GB (2.16GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-babel-coloring|dza|0.0.4
python|ms-|2018.8.0
sublime-keybindings|ms-|4.0.0

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
> Old files appear with the correct font colors but all new files are just 100% white.

What file types are we talking about? Can you share a screenshot of what you mean?

>  Furthermore it stopped adding '' when I type ' .

What does this mean?

**Comment by AlexaforMuggles** [comment]
Not sure why, but it works now. Thanks for your help Joao.
