### ISSUE TITLE
nested outline in C++

### ISSUE THREAD

**Issue by micmelesse** [Microsoft/vscode#58455]
It would be useful if the members and methods in a C++ struct or class could be nested. Especially when the outline is sorted by position. 

Consider the following outline view of the `coins.h` file in the bitcoin repo. A nested view would be very useful to get a quick high level view of the file. 

![image](https://user-images.githubusercontent.com/16394078/45387738-d0bf8100-b5cb-11e8-92b1-d4c3bb17a103.png)

**Comment by mjbvz** [comment]
The outline contents come from the C++ extension. Please file this issue against that extension
