### ISSUE TITLE
Links not clickable in the integrated terminal

### ISSUE THREAD

**Issue by akshita31** [Microsoft/vscode#58452]
Issue Type: <b>Bug</b>

The filepaths in the integrated terminal are not clickable. 
I confirmed and it worked correctly till atleast 1.25.0 

This is the screenshot from 1.25:
![vscode1 25](https://user-images.githubusercontent.com/12554141/45383601-91d7fe00-b5c0-11e8-8965-dd76aa29302b.PNG)

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:18.328Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.90GB (19.73GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.5.6
tslint|eg2|1.0.38
vscode-pull-request-github|Git|0.1.2
csharp|ms-|1.16.0
PowerShell|ms-|1.8.4
vsliveshare|ms-|0.3.666
debugger-for-chrome|msj|4.10.0
sonarlint-vscode|Son|1.5.0
code-spell-checker|str|1.6.10
wallaby-vscode|Wal|1.0.93

</details>

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/58256
