### ISSUE TITLE
Debug: Node program never stops debugging

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#5845]
Testing #4954

- Create an empty `.js` file.
- Configure Code to debug it.
- Launch debugging.

Debugging should stop immediately since the file doesn't do anything. It never does! 👎

**Comment by joaomoreno** [comment]
Setting important due to regression

**Comment by isidorn** [comment]
I also see this behavior in stable 1.0.0 and I think it was like this forever.
I do not think it is imporant and I also think dup of #5831
Let me know if you disagree and I will reopen

**Comment by joaomoreno** [comment]
It's a dupe, isi, you could've just added the verified tag. :/
