### ISSUE TITLE
Cannot focus on NPM Scripts in Explorer via keyboard

### ISSUE THREAD

**Issue by marbois** [Microsoft/vscode#58469]
- VSCode Version: 1.27.1
- OS Version: Ubuntu 18.04.1 LTS (bionic)

Steps to Reproduce:

1. Edit Settings -> Enable explorer view for NPM Scripts
2. Try to access NPM Scripts in Explorer via keyboard

NOTE: There is no "Focus on NPM Scripts View" command, but the following commands are available:
- Focus on Open Editors View
- Focus on Files Explorer
- Focus on Outline

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
@marbois There are no individual commands for each view. There is a general command `Open View` from which you can open the view.

Such a view specific command should come from the custom view extension.

**Comment by egamma** [comment]
@marbois the `Open View` command can be used to focus the NPM script explorer using the keyboard. One view is CMP + P and then typing ´view npm´. So I´ll label this as a feature request.

**Comment by egamma** [comment]
@sandy081 I´ve looked into providing a `Focus NPM Script Explorer` command. However, I didn´t find an API for the TreeView to change the focus. Did I overlook something?

**Comment by sandy081** [comment]
@egamma No, you are right there is no API support to focus or open a view. There are two approaches

1. Core can create commands `Focus: ${view_name}` for all views where all extensions can get this feature for free

2. Expose an API / command to focus / open the view and extension can contribute the command.

I think first approach is preferable. What do you think?

**Comment by sandy081** [comment]
Verify that there are commands to focus all views in the side bar
