### ISSUE TITLE
Microsoft.Python.LanguageServer.exe

### ISSUE THREAD

**Issue by falonso-caa** [Microsoft/vscode#58463]
Issue Type: <b>Bug</b>

Python Language Server uses ~16-18 GB RAM on a 24 GB RAM laptop. Causing my memory usage to hang around 95%. It's also chewing through disk with 20-40 MB/s. It's a hungry, hungry hippo.

![](https://i.imgur.com/OSzSOkn.png)

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|23.84GB (0.67GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
gc-excelviewer|Gra|2.1.26
r|Iku|0.6.1
rainbow-csv|mec|0.5.0
mssql|ms-|1.4.0
anaconda-extension-pack|ms-|1.0.0
python|ms-|2018.8.0
PowerShell|ms-|1.8.4
vscode-yaml|red|0.0.15
gitblame|wad|2.4.4

</details>

**Comment by mjbvz** [comment]
Please file this issue against the python extension
