### ISSUE TITLE
Multiple Extension Paths (Multiple Extension Search paths)

### ISSUE THREAD

**Issue by paxsonsa** [Microsoft/vscode#58465]
Multiple Extension Paths (Multiple Extension Search paths)
I am looking to understand or implement the use of multiple paths for extension installation locations.
For context, we work in a small firm that would like to have globally available extensions but allow users to install their own. It would help to allow vscode to search multiple locations for extensions.

Is that something the community has worked around OR has an implementation for us?

**Comment by sandy081** [comment]
Can you please elaborate your use case? What do you mean by globally available extensions? Is it like recommendations for your project?

**Comment by paxsonsa** [comment]
@sandy081 Sure thing!

One use case of ours is having a "Global" Shared Extensions on NFS and let users still customize their extensions. 

Within an organization that may have a number of tools/extensions that they want ALL developers to have but we don't want to prevent the users from customizing their own vscode with their choice of extensions. In the current implementation of VSCode's Extension Installation path you can specify ONE path.

Having the ability to load extensions from multiple paths would allow for some hierarchy when loading extensions.

**Example:**
```
code --extensions-dir /path/to/global/extensions /path/to/user/extensions
```

**Comment by sandy081** [comment]
@paxsonsa Sharing an extension directory for all users might makes things complicated.

- Do you want to restrict disabling / updating / uninstalling shared extensions?
- Shared extensions will not work if multiple users from different platforms are connecting to it.

I think what you might need is to have a list of extensions always installed in VS Code and a way to provide this list to VS Code may be through a setting?

**Comment by paxsonsa** [comment]
@sandy081 those are good points.

> Do you want to restrict disabling / updating / uninstalling shared extensions?

Yes. In our use case we can control permissions via file/dir perms.

> Shared extensions will not work if multiple users from different platforms are connecting to it.

Correct. We would have to separate out platforms in our use case but thats nothing new.

I think you right about having a list of always installed extensions that might be a good method....if we weren't air-gapped but that is something vscode should not necessarily cater too. 

I like your settings idea. Do you imagine something like a setting that you specify extensions to be present and then if they are not installed at launch time then install them or maybe something like the requirments.txt file in pip that CLI can be installed with? 

I could also imagine that, like other applications, you have your local user location and a system/global location to install extensions. Users can choose to install into their own config or into the system but, like some applications, if the user does not have permissions (talking a simple a file permissions) the operation of installation would fail into the system location.

**Comment by sandy081** [comment]
@paxsonsa 

Thanks for understanding the complexities. Please ignore the settings idea because it will also need user configuring this setting manually which is as good as installing extensions manually. 

We generally recommend as a system administrator when you install VS Code in users machines, system administrator has to install extensions as part of the set up so that all users have VS Code with required extensions. If you want project recommended extensions you can leverage workspace recommendations feature.

With above explanation and suggestions, I am sorry to say that this feature request cannot be considered. Hence closing this.

**Comment by paxsonsa** [comment]
Thanks for taking the time.
