### ISSUE TITLE
git integration does not respect .gitignore for root dir only

### ISSUE THREAD

**Issue by enuggetry** [Microsoft/vscode#58466]
Issue Type: <b>Bug</b>

In .gitignore, this ignores the root level /utils directory, but not the subdirectory.
`/utils/`

If directory looks like:

```
- bin
 ┕ utils
- utils
```

In VS workspace, files in /bin/utils are not accessible.
However, if files are edit outside of VS, they do appear in the Changed list in VS.

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:47.222Z)
OS version: Linux x64 4.15.0-33-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (2 x 2598)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|1, 1, 1|
|Memory (System)|3.85GB (0.21GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.20.0
jshint|dba|0.10.20
vscode-eslint|dba|1.6.0
githistory|don|0.4.2
gitlens|eam|8.5.6
vscode-npm-script|eg2|0.3.5
restructuredtext|lex|77.0.0
notepadplusplus-keybindings|ms-|1.0.2
vscode-icons|rob|7.26.0
rst-vscode|tht|2.0.0

</details>

**Comment by joaomoreno** [comment]
What about standalone `git`? Does `git` in the command line respect it?
