### ISSUE TITLE
User installer fails with AppLocker publisher rules

### ISSUE THREAD

**Issue by keatoinc** [Microsoft/vscode#58471]
- VSCode Version: VSCodeUserSetup-x64-1.27.1.exe
- OS Version: Windows 10 1803

Steps to Reproduce:

1. Create an AppLocker executable publisher rule in enforcement mode with the following allow permissions.
Publisher: O=MICROSOFT CORPORATION, L=REDMOND, S=WASHINGTON, C=US
Product name: VISUAL STUDIO CODE
File name: *
File version: *

2. Launch VSCodeUserSetup-x64-1.27.1.exe

Does this issue occur when all extensions are disabled?: N/A

The following error message is produced by the installer when run:

> Unable to execute file in the temporary directory. Setup aborted.
> Error 1260: This program is blocked by group policy.

The issue is due to the installer extracting an executable into a temp directory which isn't signed with the product name.  The fqbn for the two files are:

VSCODEUSERSETUP-X64-1.27.1.EXE: 
O=MICROSOFT CORPORATION, L=REDMOND, S=WASHINGTON, C=US\VISUAL STUDIO  CODE\\1.27.1.00

VSCODEUSERSETUP-X64-1.27.1.TMP 
O=MICROSOFT CORPORATION, L=REDMOND, S=WASHINGTON, C=US\\\51.1052.0.00

The insiders build has the same issue with the product name missing from the signed image extracted into the temp folder.

**Comment by joaomoreno** [comment]
Please use the ZIP archive in situations like this.
