### ISSUE TITLE
global not work  on win7

### ISSUE THREAD

**Issue by doubao86** [Microsoft/vscode#58477]
Hi there,

GNU global doesn't work with vscode on my Windows 7, it has annoyed me for some days.
I've googled for the below error, but failed to solve it:

    [Extension Host] Error: Error: spawn C:\Windows\system32\cmd.exe;C:\Program Files\Java\bin ENOENT `global --encode-path " " -xa QPayDecrypt3DES` (exited with error code ENOENT)

What makes me confused is that why there is some `java/bin` path in the above error message:(

The related configure is:

    "contributes":{
        "configuration":{
            "codegnuglobal.executable": "C:\\gnu_global\\bin\\global.exe",
        },
    },

And my system PATH is like this:

    C:\gnu_global\bin\;...

And if I execute the command on the console inside vscode, it works.

What is the problem? any help will be appreciate.

**Comment by joaomoreno** [comment]
Is this related to a VS Code extension?
