### ISSUE TITLE
[Themes] - 'list.inactiveFocusBackground' should have better default colors

### ISSUE THREAD

**Issue by nealot** [Microsoft/vscode#58474]
Possibly due to https://github.com/Microsoft/vscode/issues/40390, very few themes customize 'list.inactiveFocusBackground' (including the default themes). I suggest that the default colors change to darker versions of 'list.inactiveSelectionBackground' to avoid inconsistencies within themes.

**Comment by nealot** [comment]
For reference:
![screenshot_20180918_023158](https://user-images.githubusercontent.com/36805289/45668523-0ba14780-baeb-11e8-83fe-c0d13263e096.png)

**Comment by misolori** [comment]
We've fixed this and have tracked it in #68697. Closing as duplicate.

**Comment by rediffusion** [comment]
Where and what does this feature change (can you provide some screenshot)?

> list.inactiveFocusBackground
