### ISSUE TITLE
Debugger focus on restart

### ISSUE THREAD

**Issue by ShayBox** [Microsoft/vscode#58479]
Currently I have my project restart on save, and vsc to auto attach when it detects a process, but every time it switches to the debugger tab and I have to click back to the file tree, I like that it focus's the debugger console, but I only want it to focus the debugger tab when there's an actual error.

An option to stop the debugger tab from taking focus on start.

**Comment by isidorn** [comment]
Use the following setting please:
`"debug.openDebug": "neverOpen"`
