### ISSUE TITLE
源代码管理 -更多操作-鼠标左键点击 菜单不能停留

### ISSUE THREAD

**Issue by guojhq** [Microsoft/vscode#58478]
所需的数据太大，无法直接发送。我们已经将其写入剪贴板，请粘贴。

**Comment by joaomoreno** [comment]
This issue was closed because it doesn't meet our standards of a properly filled issue. Please read our guide about [Submitting Bugs and Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).
