### ISSUE TITLE
Launch extension in empty folder if target folder already opened in window

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#5847]
- VSCode Version: Alpha
- OS Version: OS X

Steps to Reproduce:

1. open any folder in vscode
2. open a new window in vscode and open your extension
3. launch your extension -> notice that the first vscode window is focused, and a new third window is not opened

Works in stable -> important

**Comment by bpasero** [comment]
@isidorn actually I noticed that I do have code in to prevent this from happening, here are my steps:
* open another workspace on a hello-world extension
* run the extension and open a folder A in there
* close extension
* open another window and open folder A in there
* run extension again
=> it should now open with empty folder

Same works for me when I explicitly pass a folder over in the launch.json.

Please reopen with steps to reproduce!

**Comment by isidorn** [comment]
I can no longer easily reproduce, will let you know if I get steps
