### ISSUE TITLE
Can't open vscode extension development host

### ISSUE THREAD

**Issue by faqndo97** [Microsoft/vscode#58470]
Hi guys!

I'm trying to start develop extension for vscode. I'm following you hello world guide and I'm trying to open the extension development host. When I press f5 nothing happen, and I open debugger side menu and hit run but nothing happen again. Do you know why this is happening?

Thanks for you help! 

🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/visual-studio-code.

**Comment by faqndo97** [comment]
This is my lunch.json

```json
// A launch configuration that launches the extension inside a new window
// Use IntelliSense to learn about possible attributes.
// Hover to view descriptions of existing attributes.
// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
{
	"version": "0.2.0",
    "configurations": [
        {
            "name": "Extension",
            "type": "extensionHost",
            "request": "launch",
            "runtimeExecutable": "${execPath}",
            "args": [
                "--extensionDevelopmentPath=${workspaceFolder}"
            ]
        },
        {
            "name": "Extension Tests",
            "type": "extensionHost",
            "request": "launch",
            "runtimeExecutable": "${execPath}",
            "args": [
                "--extensionDevelopmentPath=${workspaceFolder}",
                "--extensionTestsPath=${workspaceFolder}/test"
            ]
        }
    ]
}
```

**Comment by TheOpenDevProject** [comment]
I can confirm when trying to debug with an xDebug extension there is no way to launch the debugger.

![image](https://user-images.githubusercontent.com/6072108/45404840-8279b300-b69b-11e8-9db7-e150fc9dea44.png)

**Comment by weinand** [comment]
@TheOpenDevProject "xDebug" has nothing to do with extension host debugging. What's the purpose of your comment?
"xDebug" is php debugging, right? Please don't hijack random issues.

**Comment by faqndo97** [comment]
@weinand This is my vscode information

![captura de pantalla 2018-09-12 a la s 09 55 52](https://user-images.githubusercontent.com/16840674/45426270-1898e380-b672-11e8-9ae5-c28dbac4d0de.png)


If you need any other information only tell me thanks!

**Comment by weinand** [comment]
@faqndo97 what do you see in the debug console after pressing F5?

**Comment by weinand** [comment]
Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces.

**Comment by faqndo97** [comment]
@weinand Nothing happen again

**Comment by weinand** [comment]
Please "Toggle the Developer Tools" (via Help Menu), and open the "Console".
Are there any errors or other messages?

**Comment by weinand** [comment]
Please open the "Extension" viewlet and from the drop down menu behind the "..." run the "Show Built-in extensions". In the features section scroll down until you see "Node Debug" and "Node Debug (legacy)". Both should be enabled.

**Comment by faqndo97** [comment]
Finally I deleted my vscode and install again and now works fine!! Something in my last config or environment works bad. Thanks for your help.

**Helpful link** - For complete delete of vscode I follow this [post](https://medium.com/@jimkang/complete-uninstall-remove-vscode-mac-5e48bef3bdec)
