### ISSUE TITLE
Source link support for VSCode

### ISSUE THREAD

**Issue by klick-barakgall** [Microsoft/vscode#58472]
Apologies if this is a duplicate, I had a quick gander and couldn't find anything similar among the open issues.

A quick google did find this issue on a repo that seemed relevant: https://github.com/ctaggart/SourceLink/issues/195

The feature I would like is Source Link support within VSCode to allow me to debug things like ASP.Net Core internals instead of having to guess why my code is behaving the way it is.

I feel this would be a massive cutdown on production time for me (so I imagine others would also benefit?).

NOTE: I'm making a large assumption that Source Link supports .Net-core symbol files and such. If this is not the case any functionality that can help me investigate the internals of other open source projects I'm working with would be a huge boon for me.

**Comment by weinand** [comment]
Sorry, but what is "Source Link" support?
