### ISSUE TITLE
no longer able to jump to line from error/warning in terminal

### ISSUE THREAD

**Issue by jlgerber** [Microsoft/vscode#58485]
Issue Type: <b>Bug</b>

Up until this version of vscode, I could hover over an error file attribution, push option (im on mac) click on the filepath, and vscode editor would jump to the file and line in question. This doesnt seem to work anymore.

VS Code version: Code 1.27.0 (7b9afc4196bda60b0facdf62cfc02815509b23d6, 2018-09-05T05:22:06.672Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.76GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_4437051|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
haskero|Van|1.3.1
Bookmarks|ale|9.0.3
project-manager|ale|8.0.0
code-gnu-global|aus|0.2.2
vscode-database|baj|1.5.2
toml|be5|0.0.3
gotemplate|cas|0.2.0
vscode-svgviewer|css|1.4.6
vscode-eslint|dba|1.6.0
gitlens|eam|8.5.6
CppSnippets|har|0.0.13
hoogle-vscode|jca|0.0.7
golang-tdd|joa|0.0.9
open-in-vim|jon|0.4.1
simple-vim|jpo|0.0.4
language-haskell|jus|2.5.0
cpp-symbols|mir|0.0.1
vscode-clang|mit|0.2.2
python|ms-|2018.8.0
azure-account|ms-|0.4.3
cpptools|ms-|0.18.1
Go|ms-|0.6.89
vscode-open-iterm2|mus|0.0.4
vscode-code-outline|pat|0.2.1
vscode-docker|Pet|0.2.0
vscode-icons|rob|7.26.0
rust|rus|0.4.10
partial-diff|ryu|1.4.0
RustyCode|sav|0.19.1
elm|sbr|0.21.0
preview-vscode|sea|1.4.4
cmake|twx|0.0.17
es-quotes|vil|0.2.6
pestfile|xor|0.0.1
markdown-all-in-one|yzh|1.6.0

(2 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by Mmisiek** [comment]
I have the same problem in 1.28.1
