### ISSUE TITLE
Unable to launch VSCode Debugger (Nothing happens)

### ISSUE THREAD

**Issue by TheOpenDevProject** [Microsoft/vscode#58486]
- VSCode Version: 1.27.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open a project that previously could be debugged using VSCode
2. Hit F5 / Press green play button / Launch through menu
3. Nothing happens. No errors, no warnings, no debugging, nothing.

Does this issue occur when all extensions are disabled?: Unknown but unrelated as never reaches this point.

**Comment by weinand** [comment]
How does your launch config look like?

**Comment by TheOpenDevProject** [comment]
@weinand Issue resolved by disabling all extensions. Closing. Spoke too soon on the "unrelated" part.

**Comment by weinand** [comment]
do you have Liveshare installed?
