### ISSUE TITLE
The breakpoint is not validated

### ISSUE THREAD

**Issue by aixiaoxiang** [Microsoft/vscode#58483]
Issue Type: <b>Bug</b>

The breakpoint is not validated

# golang

1: config to settings.json
---
<img width="427" alt="image" src="https://user-images.githubusercontent.com/8416556/45412630-b65bd500-b6a9-11e8-8492-0412ad41809d.png">

<img width="377" alt="image" src="https://user-images.githubusercontent.com/8416556/45412749-09ce2300-b6aa-11e8-916b-83a6e778ca40.png">

<img width="1111" alt="image" src="https://user-images.githubusercontent.com/8416556/45412878-66c9d900-b6aa-11e8-93a3-6d29cd1c5e65.png">

---
2: config to settings.json

<img width="508" alt="image" src="https://user-images.githubusercontent.com/8416556/45412800-29fde200-b6aa-11e8-8a35-f484676b21f6.png">

<img width="349" alt="image" src="https://user-images.githubusercontent.com/8416556/45412812-37b36780-b6aa-11e8-96bb-15febce35181.png">

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/8416556/45412841-5154af00-b6aa-11e8-9b81-cbbd3f769cb5.png">

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:14:32.385Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (0.07GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.1.3
vscode-mysql|for|0.3.0
vscode-language-pack-zh-hans|MS-|1.27.2
Go|ms-|0.6.89
vetur|oct|0.12.6
rust|rus|0.4.10
markdown-preview-enhanced|shd|0.3.5
markdown-all-in-one|yzh|1.6.0

</details>

**Comment by joaomoreno** [comment]
Care to elaborate?

**Comment by weinand** [comment]
What debugger are you using?
How does your launch config look like?

**Comment by aixiaoxiang** [comment]
@weinand 

# golang

1: config to settings.json
---
<img width="427" alt="image" src="https://user-images.githubusercontent.com/8416556/45412630-b65bd500-b6a9-11e8-8492-0412ad41809d.png">

<img width="377" alt="image" src="https://user-images.githubusercontent.com/8416556/45412749-09ce2300-b6aa-11e8-916b-83a6e778ca40.png">


<img width="1111" alt="image" src="https://user-images.githubusercontent.com/8416556/45412878-66c9d900-b6aa-11e8-93a3-6d29cd1c5e65.png">

---
2: config to settings.json

<img width="508" alt="image" src="https://user-images.githubusercontent.com/8416556/45412800-29fde200-b6aa-11e8-8a35-f484676b21f6.png">


<img width="349" alt="image" src="https://user-images.githubusercontent.com/8416556/45412812-37b36780-b6aa-11e8-96bb-15febce35181.png">


<img width="1157" alt="image" src="https://user-images.githubusercontent.com/8416556/45412841-5154af00-b6aa-11e8-9b81-cbbd3f769cb5.png">

**Comment by weinand** [comment]
Please file this issue against go debugger.
