### ISSUE TITLE
cannot find runtime node on path visual studio code

### ISSUE THREAD

**Issue by ckargus** [Microsoft/vscode#58480]
I have looked everywhere and tried about everything is someone could help me that would be great. 
this is my launch.json file
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}/.vscode\\Untitled-1.js"
        }
    ]
}
I've tried to type where node in the terminal but nothing happens so anything would be great.

**Comment by weinand** [comment]
You need to have node.js installed. 
Please open a terminal and type "node --version", what do you see?

**Comment by ckargus** [comment]
typed in node --version on the vs terminal and got this

node : The term 'node' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path
was included, verify that the path is correct and try again.
At line:1 char:1
+ node --version
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (node:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by ckargus** [comment]
i hate to admit it but i didn't know i didn't have node.js installed and that fixed it thank you

**Comment by weinand** [comment]
Yes, VS Code uses node.js internally but does not make that available for the user. So you are free to install any version of node.js as you like and VS Code will not get into your way.
But that means that you'll have to install node.js first...
