### ISSUE TITLE
Go To File does not find all files when `search.useRipgrep` is true

### ISSUE THREAD

**Issue by vkalpias** [Microsoft/vscode#58488]
Issue Type: <b>Bug</b>

When using Cmd+P to Go To File, not all files are displayed in the search results unless the file is already open. This is fixed if I set `search.useRipgrep` to false. 

The files I'm looking for are not under a special directory that should be ignored. 

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:14:32.385Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 5|
|Memory (System)|16.00GB (0.30GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_622744|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
mustache|daw|1.1.1
vscode-eslint|dba|1.6.0
gitlens|eam|8.5.6
python|ms-|2018.8.0
csharp|ms-|1.16.0
vscode-docker|Pet|0.2.0
vim|vsc|0.16.4

</details>

**Comment by vkalpias** [comment]
It looks like the problem is fixed if I set Use Ignore Files to false. However the .gitignore file that is in that project does not ignore the files in question. In fact even if I use an empty .gitignore file then the files are not found in Go To File with Use Ripgrep set to true.

**Comment by roblourens** [comment]
Thanks for tracing it down to Use Ignore Files. Do you have a `.ignore` file? Is there a `.gitignore` file in a different folder (parent or child directory) that could be taking effect?

If it's just a particular set of files that are being lost, they must be matched by an ignore file somewhere.

**Comment by vkalpias** [comment]
So I managed to isolate this even further. It looks like it is fixed if I remove the `.git` subfolder. I even tried leaving the `.git` subfolder and deleting all of the files under`.git/*` and that didn't fix it. Only if I completely remove the `.git` folder it seems to work again... In my test I deleted any .gitignore files. There is no .ignore file.

**Comment by roblourens** [comment]
Do you have a `.git/info/exclude` file?

**Comment by vkalpias** [comment]
Turns out I had a `~/.gitignore_global` file somehow so after I fixed that the issue is resolved. Sorry for wasting your time! 

As a side note it might be useful to add this file to the list of files mentioned in the Settings so that users can consider it if they run into this issue as well. Thanks again!
