### ISSUE TITLE
Optimal utilization of space on search window when docked at bottom

### ISSUE THREAD

**Issue by WinCPP** [Microsoft/vscode#58489]
Lot of space is occupied in search results window leaving small space for the search results when the search window / panel is docked at bottom. As in visual studio, it would be good to have following features,

1. Open a popup to accept inputs for search, include files, exclude files, etc. and remove the same from the search result window as seeing it hardly matters after results are displayed. That will increase the number of lines visible in search results.
2. If point 1 is not possible at least add a collapsible sub-panel to hide off the include / exclude text boxes, just like the chevron on left of 'search' text box controls visibility of the 'replace' text box.
3. If even point 2 is not possible, put the label and the text box in single line. That is, put the label "files to include" on left side of the include criteria text box, etc.
4. Display the search results in table format just like visual studio with first column for text, second for Fully Qualified File Name, third for line numbers. And make search result window switchable between grouped (current view) or tabular outputs.

Attached an image to emphasize how much of space is lost in the current layout when docked at bottom. Appreciate if you can consider this.

Thanks,
Mandar

![horizontalsearchresults](https://user-images.githubusercontent.com/8945458/45407821-2f4a3500-b688-11e8-8d33-3147cf315be5.png)

**Comment by roblourens** [comment]
1. We won't open a popup, that just doesn't fit with vscode UI patterns
2. It can be collapsed if you click the ... button on the right side
3. We tried that, it was very unpopular :)
4. Currently we are trying to not have a totally different layout between sidebar and panel views, I think it's not likely that I'll make a change like that.
