### ISSUE TITLE
Signature help inappropriately fired in totally unrealistic scenario

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/vscode#58492]
Great work on signature help characters @mjbvz! The scenario I really cared about seems significantly better.

I did find that holding down the comma character still does trigger signature help though.

![holdcommadown](https://user-images.githubusercontent.com/972891/45411252-9e903c80-b628-11e8-93fb-6c62792a1821.gif)

**Comment by mjbvz** [comment]
Interesting case. Here's what why this happens:

- We debounce signature help requests to only fire every 250ms or so.
- The signature help request is counted as a retriever if either: the  sig help is already showing or we have a pending signature help request that has been debounced but not applied yet. 
- In this case, we queue up two or more requests before actually asking TS for sig help. This results in the request we do finally fire being marked as a  `retrigger`
- I believe marking the request as a retrigger causes ts to return these sig help incorrectly here

Possible fixes

- Only mark a request as retrigger if the sig help ux was really showing
- Never make a trigger character a retrigger. Introduce a separate set of retrigger characters. However moving the cursor about would count as a retrigger.
