### ISSUE TITLE
Backslash character escape in choice tabstop doesn't work

### ISSUE THREAD

**Issue by yangshuairocks** [Microsoft/vscode#58494]
- VSCode Version:
```
Version: 1.27.1
Commit: 5944e81f3c46a3938a82c701f96d7a59b074cfdc
Date: 2018-09-06T09:21:18.328Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```
- OS Version: Win 10

Steps to Reproduce:

1. Create a snippet like this and save it
```
{
    "test choice": {
        "prefix": "test",
        "body": [
            "${1|\\,,},$,\\||}"
        ],
        "description": "test choice"
    }
}
```
2. Create a new text editor tab and type `test` <kbd>tab</kbd> to trigger the snippet

![20180912160822](https://user-images.githubusercontent.com/39968/45411325-83641200-b6a6-11e8-9998-2172f1bc4670.png)

3. Modify the snippet to add a new item that is only a backslash character `\`.
```
{
    "test choice": {
        "prefix": "test",
        "body": [
            "${1|\\,,},$,\\|,\\\|}"
        ],
        "description": "test choice"
    }
}
```
4. Trigger the snippet again and it doesn't work as expected.

![20180912161404](https://user-images.githubusercontent.com/39968/45411549-0be2b280-b6a7-11e8-995d-31c82abf95ca.png)

---

The document  at [https://code.visualstudio.com/docs/editor/userdefinedsnippets#_grammar](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_grammar) says:
> Below is the EBNF (extended Backus-Naur form) for snippets. With \ (backslash), you can escape $, } and \. Within choice elements, the backslash also escapes comma and pipe characters.

It seems the escaping of `\` doesn't work as expected. I've tried `\\\`, `\\\\`, `\\\\\`, `\\\\\\` for them and all not work. Seems like a bug to me. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
This will now work

```json
"test choice": {
		"prefix": "zz",
		"body": [
			"${1|\\,,},$,\\|,\\\\|}"
		],
		"description": "test choice"
	},
```
