### ISSUE TITLE
Visual studio Code restart

### ISSUE THREAD

**Issue by maxteebabs** [Microsoft/vscode#58491]
Upon restarting Visual studio code, my workspace does not load. Unlike sublime, that stores your workspace, vsc does not open the last workspace that was opened.

**Comment by bpasero** [comment]
@maxteebabs does this happen all the time? E.g. try this:
* start VSCode
* open a folder
* select File > Quit
* start VSCode

=> is the folder opened again?

**Comment by bpasero** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/12058
