### ISSUE TITLE
Do not hardcode border color for monaco-menu-container in HC theme

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#58496]
It looks like a color sneaked into CSS that should use our theming story instead: https://github.com/Microsoft/vscode/blob/abca8c3ce9c267605efc74d5b79ca2a23e746de1/src/vs/workbench/browser/parts/titlebar/media/titlebarpart.css#L205

We have this color defined (`contrastBorder` I think).

**Comment by sbatten** [comment]
hijacking this issue to fix https://github.com/Microsoft/vscode/commit/5dec58794d15d735e7fb1821625d810e818ccc34#r30473824 as well

**Comment by bpasero** [comment]
@sbatten its a tradeoff, for example in https://github.com/Microsoft/vscode/pull/58498 I decided to leave the default color in the CSS file simply because it would involve quite a bit of code to make that change programmatically. So just see how much pain it would be to remove the CSS color and then decide 👍
