### ISSUE TITLE
"Copy Relative Path": is not doing the right thing in multi-root

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#58504]
Steps to Reproduce:

1. open a multi-root workspace
2. right click into a file of a folder and pick "Copy Relative Path"

=> the outcome is e.g. this: `ticino-playground • Driver.ts`
=> it should rather be `ticino-playground/Driver.ts` or maybe just `Driver.ts`

Moving to September because imho this is a regression.

**Comment by oneslash** [comment]
@bpasero could you check my PR #58511

**Comment by isidorn** [comment]
@bpasero not sure what is expected `ticino-playground/Driver.ts` or `Driver.ts`. However I went with the latter due to how I implemented it.
Let's see if people find this strange and we can easily change.

**Comment by bpasero** [comment]
@isidorn yeah I think that is fair
