### ISSUE TITLE
PowerShell script debug with arguments

### ISSUE THREAD

**Issue by tms320** [Microsoft/vscode#58501]
Issue Type: <b>Bug</b>

My powershell script "test.ps1" is located in "C:\Program Files (x86)\SomeFolder\" folder.
If I start debug this script (F5 key) without command line arguments then everything works fine.
But if I start debug with command line argument (for example "param1") then I get error in powershell console (the message is in russian, sorry:)):
PS C:\Program Files (x86)\SomeFolder> . c:\Program` Files` (x86)\SomeFolder\test.ps1 param1
x86 : Имя "x86" не распознано как имя командлета, функции, файла сценария или выполняемой программы. Проверьте правильность написания имени, а также наличие и правильность пути, после чего повторите попыт
ку.
строка:1 знак:23
+ . c:\Program` Files` (x86)\SomeFolder\test ...
+                       ~~~
    + CategoryInfo          : ObjectNotFound: (x86:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS: I manually set command line argument via 'launch.json' file, for configuration 'PowerShell Launch Current File' as follows:
"args": ["param1"],
or like this:
"args": ["\"param1\""],
I also tried configuration 'PowerShell Launch Current File w/Args Prompt' - the problem remains.

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:10.934Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (3.65GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
include-autocomplete|ajs|0.0.4
togglehs|bbe|0.1.2
xml|Dot|2.3.2
php-intellisense|fel|2.3.5
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.4
vscode-clang|mit|0.2.2
cpptools|ms-|0.18.1
csharp|ms-|1.16.0
PowerShell|ms-|1.8.4
python|tht|0.2.3

(1 theme extensions excluded)

</details>

**Comment by weinand** [comment]
Please file this issue against the PowerShell extension.
