### ISSUE TITLE
Excessive TypeScript-related resource usage

### ISSUE THREAD

**Issue by oliversalzburg** [Microsoft/vscode#58509]
Issue Type: <b>Bug</b>

Seems like every instance of VS Code has a child like this one, eating up my CPU resources:
![image](https://user-images.githubusercontent.com/1658949/45423787-9f5eb800-b694-11e8-9622-fb836a44c483.png)

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:18.328Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3672)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.91GB (35.81GB free)|
|Process Argv|C:\Users\OliverSalzburg\AppData\Local\Programs\Microsoft VS Code\Code.exe core-rpc2.code-workspace|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.59
vscode-eslint|dba|1.6.0
EditorConfig|Edi|0.12.4
vscode-esformatter|how|1.6.0
output-colorizer|IBM|0.1.2
vscode-lebab|mrm|2.5.0
vscode-puglint|mrm|2.3.0
debugger-for-chrome|msj|4.10.1

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Which column of that report is the cpu usage? The `8.08`? Do you only see this when interacting with VS Code or is the cpu usage always there?

Also, does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by oliversalzburg** [comment]
Yes, the 8.08 are the CPU usage. The CPU usage was always there. Which is why I have now fully disabled TypeScript for the time being. When *that* results in further things breaking, I will revisit the situation.
