### ISSUE TITLE
Run extension test in docker

### ISSUE THREAD

**Issue by vitahlin** [Microsoft/vscode#58507]
I want to develop extentison in docker centos7.
Then I run test `npm test` it would report an error.
I found that it will open VSCode when run test. But it can not work well in bash.
Is there some way to avoid open VSCode when I run `npm test`？

**Comment by bpasero** [comment]
No, the extension-tests require a window to open because they run within a VSCode instance. If you have unit tests you should run them separately.

**Comment by vitahlin** [comment]
Got it, thanks.
