### ISSUE TITLE
VSC Insiders windows can't be manipulated by external apps anymore

### ISSUE THREAD

**Issue by GandalfSaxe** [Microsoft/vscode#58512]
Issue Type: <b>Bug</b>

I can't reposition or resize the windows of VSCode anymore on Mac. This is a major painpoint. I can't be sure when it was introduced, but it's only broken in Insiders.

Have tried both [Magnet](http://magnet.crowdcafe.com) and [BetterTouchTool](https://folivora.ai) and neither of them can move or resize the windows. Did something happen on a fundamental level, perhaps with Electron? I hope this can be corrected soon.

I wish I could be more detailed steps to reproduce or refer to freeware apps. I'm sure plenty of people on the VSCode team must be using windows managers on their MacBooks though, so hopefully this shouldn't be hard to reproduce.

VS Code version: Code - Insiders 1.28.0-insider (31bf4ccab388c082fcf4edafeaae5b703f211b5b, 2018-09-12T05:12:04.730Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|/Users/gandalf/Documents/portable/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by bpasero** [comment]
Nothing has changed in VSCode as far as I know. I am closing this as it seems like an issue with the tools you are using, not VSCode itself. I suggest to follow up with them.

**Comment by GandalfSaxe** [comment]
Two important facts point to this not being an issue with the tools:
1. I have *never* had this issue with any app before on Mac.
2. It *only* happens on Insiders.

So it's obviously something that's changed with VSCode. Surely there must be *someone* on the VSCode team that uses any sort of window manager on Macbook that could confirm?

Meanwhile I can contact the developers of the tools also. But the problem is with VSCode, that much I'm 99.9% certain of.
