### ISSUE TITLE
TypeScript formatter converts everything to spaces

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#58518]
Happens in selfhost. This has happened 3 times to me today, need to use git to revert the file.

Can't get reliable repro steps.

cc @bpasero

**Comment by bpasero** [comment]
Happened to me as well already last week. Only way out was to "Convert spaces to tabs" command.

**Comment by DanTup** [comment]
I'm seeing this too (Insiders) - running `Convert to tabs` fixes it, but as soon as I format-on-save it goes back to Spaces. The settings in the status bar are set correct (tab size: 4).

**Comment by joaomoreno** [comment]
This is so annoying. :cry:

**Comment by DanTup** [comment]
Ugh, I've just started seeing this on Stable too :(

**Comment by joaomoreno** [comment]
Happens very very often.

**Comment by mjbvz** [comment]
@joaomoreno Please:

1. Set `"typescript.tsserver.trace": "verbose"`
1. When this issue first happens in a session, open the output panel and share the `typescript` output

**Comment by joaomoreno** [comment]
@mjbvz Repro steps:

1. Open a TS file in vscode
2. Reload
3. Press `Ctrl S` every 0.5 seconds until it happens.

Recorded a verbose log and stopped as soon as it happened: https://gist.github.com/joaomoreno/8cd7fe72097d40197e86cd342278e4ba

**Comment by mjbvz** [comment]
Thanks @joaomoreno! I believe I have narrowed down the root cause and submitted a fix. Let me know if you see this again the next insiders build.
