### ISSUE TITLE
Workspace stats creating bad uris

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#58516]
Repro:

```
git init --bare bare
git clone bare clone
code clone
```

Open DevTools:

![image](https://user-images.githubusercontent.com/22350/45427959-78a67e80-b6a0-11e8-80f2-77c9af2f5f2c.png)

**Comment by joaomoreno** [comment]
The warning is valid. We're passing a path to `Uri.parse`, which is wrong. Git remote addresses are not always uris.

**Comment by ramya-rao-a** [comment]
So the consumers of `URI.parse` should beforehand check if what they are passing is valid uri or not? Doesnt that fail the purpose of `parse` ?

`JSON.parse` is used to parse json content. We can pass non json to it as well. It throws an error.

Can we not expect something similar from `URI.parse`?

**Comment by jrieken** [comment]
> So the consumers of URI.parse should beforehand check if what they are passing is valid uri or not? Doesnt that fail the purpose of parse ?

Yes, parse will throw an error but it never used to do that for missing scheme. I didn't think it's a good idea to now start throwing errors at first because not everyone encloses `parse` in a try catch block and also often people confuse `URI.parse` and `URI.file`.
