### ISSUE TITLE
Add option to open markdown preview inside same tab as markdown editor instead of new tab. 

### ISSUE THREAD

**Issue by ccarse** [Microsoft/vscode#58525]
I'd like the option to be able to open the markdown preview inside the same tab as the markdown editor. I use a single column layout for my editors like most people I know but when I want to preview a markdown file I'm working on it opens a new tab in a new column, instead I'd like it to show the preview in the current tab using some sort of split panel. I hope that makes sense. 

Thanks, VSCode is amazing!

**Comment by mjbvz** [comment]
Duplicate of #37883

**Comment by mjbvz** [comment]
The normal `Open markdown preview` command (instead of `open preview to side`) will open the preview in the same group

Support for a single group split editor falls under #22068
