### ISSUE TITLE
Click Html Missing Property Reference to Create field in TypeScript Component 

### ISSUE THREAD

**Issue by MarkPhillips** [Microsoft/vscode#58521]
Scenario:  An Angular Component property is referenced in the HTML template, but that property has not yet been created in the Angular Component.  The missing property appears underlined in the HTML.

Desired Functionality:  Provide functionality to create the property in the Component from the Context Menu or by clicking the underlined HTML. Upon this action the Component.ts file would open in the editor to allow user to complete the property definition. 

![propertycreation](https://user-images.githubusercontent.com/4471426/45431155-11270980-b675-11e8-94ce-d31212ea9e78.PNG)

**Comment by aeschli** [comment]
This problem marker comes from an external Angular extension. Can you file the issue against the extension that you are using?

**Comment by MarkPhillips** [comment]
Ok thanks

**Comment by MarkPhillips** [comment]
I'll look into that.  Thanks.
