### ISSUE TITLE
CPU runs at 100%

### ISSUE THREAD

**Issue by ricardomatias** [Microsoft/vscode#58524]
This happens whether I'm using it or it's just open.
I've disable auto-updates (which I thought the issue was related to), but this is still happening.

**With extensions**:
`3017 100.0  2.3  5449792 383260   ??  R     9:43AM   2:10.06 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /var/folders/s4/ffqt6x516015rf37_gl41sqm0000gn/T/vscode-typescript/tscancellation-02e37620f35c155d56fe.tmp* --locale en --noGetErrOnBackgroundUpdate`

**Without extensions**:
`/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /var/folders/s4/ffqt6x516015rf37_gl41sqm0000gn/T/vscode-typescript/tscancellation-3fad16c5862f653ec1c8.tmp* --locale en --noGetErrOnBackgroundUpdate`

- VSCode Version: 1.27.1
- OS Version: macOS High Sierra 10.13.6

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
As a first step, can you please try upgrading your workspace to use `typescript@next` by following [these instructions](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions). Let me know if you still see this problem when using that version of TypeScript
