### ISSUE TITLE
Disable suggested English words for text / markdown files

### ISSUE THREAD

**Issue by mikemaccana** [Microsoft/vscode#58523]
When editing plain text documents, vscode will suggest English (or whatever locale) words:

![image](https://user-images.githubusercontent.com/172594/45432591-236b6c80-b6a2-11e8-97ca-856a238814b1.png)

This is incredibly distracting and not particularly useful. Could suggested words please be disabled by default for text / markdown etc files?

**Comment by mjbvz** [comment]
You can disable these by setting:

```
  "editor.wordBasedSuggestions": false
```

**Comment by mikemaccana** [comment]
@mjbvz I know about the setting. The issue was for:

> Could suggested words please be disabled by default

Has this changed?
