### ISSUE TITLE
Search Sidebar Improvements

### ISSUE THREAD

**Issue by beastdestroyer** [Microsoft/vscode#58528]
Issue Type: UI/Feature Request
This is a continuation of #58445 except it is more inline with the Submitting Bugs and Suggestion guide.

## Search View
The following points outline my vision for an improved Search sidebar:
- Firstly, these could probably be sorted into 2 sections: `EDITOR` and `RESULTS`. (Or anything more relevant)
  - The `EDITOR` section would still contain the Search and Replace Bar, but with a few differences:
  - The `Match Case`, `Match Whole Word` and `Use Regular Expression` icons could be moved below the Replace Bar into checkboxes* rather than toggle icons, for these reasons:
    - Better Accessibility
    - According to the W3C HTML/WAI-ARIA Specs, it is recommended for forms with multiple selectable choices to use checkboxes, which is essentially what this situation is.
   - The "Replace All" icon could probably also be an actual button too
   - I'm sure the find Dialog `Ctrl/Cmd+F` could remain the same, since it is a more compact and "on-the-go" version
 - These could probably go in-line with the consistency and be sentence-case so it becomes  `Files to include` etc.
- Similarly to what I mentioned about the checkboxes, this change should also apply to the `Use Exclude Settings and Ignore Files`
  - This section should be auto-collapsed just like it is now.
- The `RESULTS` section uncollapses (is collapsed by default, when uncollapsed, it should give a message such as `There is either no match for your query or you have not searched for anything`) when results are found. Current semantics can remain the same.
![search](https://user-images.githubusercontent.com/30497573/45377554-d8dee700-b5f2-11e8-9f33-eabc9d3ec117.png)

**Comment by roblourens** [comment]
Why would we create these two sections, when would you collapse or hide them? 

Also I disagree about making the toggle buttons more verbose. Sometimes the meaning isn't immediately obvious, but I don't think it's a big problem and but being consistent with the find widget is good.

**Comment by beastdestroyer** [comment]
One reason is for aesthetics, whilst I can say they don't have to be collapsible, and rather there could be a message saying `There is either no match for your query or you have not searched for anything`,
for times where there will be many results, it would make searching through them much easier as you could scroll for example. 

Secondly, my inspiration for the checkbox toggles is ease of usage. A newbie would most likely be exploring the UI, they probably won't know that Ctrl+F exists until they try it; and with the large amount of icons in VSCode, seeing these checkboxes would immediately make them associate this filter with that icon, rather than having to experiment and see what it actually does. 

Also, if checkboxes still won't work, how about an Icon colour/background colour change as well as the focus, it would definitely be more effective

**Comment by roblourens** [comment]
The groups don't seem necessary with the current design, if I collapse the "files to include/exclude" then the controls don't take up much room.

Adding labels to the checkboxes just takes up a lot of room and feels like overkill to me.

> Good timing, we were just discussing that https://github.com/Microsoft/vscode/issues/36439#issuecomment-421423606
