### ISSUE TITLE
Some commands cannot be searched with aliases

### ISSUE THREAD

**Issue by EbXpJ6bp** [Microsoft/vscode#58520]
Issue Type: <b>Bug</b>

Commands added to the CommandPalette using `MenuRegistry.appendMenuItem(MenuId.CommandPalette` cannot be searched by both English and Japanese.

![ja](https://user-images.githubusercontent.com/8474118/45430269-ffc71700-b6df-11e8-890a-4db3000b1933.png)
![en](https://user-images.githubusercontent.com/8474118/45430271-ffc71700-b6df-11e8-9b98-9649dcc3faad.png)

expected:
![a](https://user-images.githubusercontent.com/8474118/45473279-a1e30f80-b771-11e8-838e-d531a253fc93.png)

VS Code version: Code - Insiders 1.28.0-insider (31bf4ccab388c082fcf4edafeaae5b703f211b5b, 2018-09-12T05:18:53.705Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.95GB (1.59GB free)|
|Process Argv|D:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
language-hugo-vscode|bud|0.11.0
vscode-pull-request-github|Git|0.1.3
vscode-language-pack-ja|MS-|1.27.2
vscode-language-pack-zh-hans|MS-|1.27.2

</details>

**Comment by bpasero** [comment]
This needs support in the `appendMenuItem` method to pass over an english alias for the command.

**Comment by jrieken** [comment]
we have that: https://github.com/Microsoft/vscode/blob/3da2f86e4dfdf0f183810a9b6d5c5a22ba692e5e/src/vs/platform/actions/common/actions.ts#L25-L26

**Comment by bpasero** [comment]
Learnt something 👍 . Made a pass over all registrations.
