### ISSUE TITLE
File exclusion and inclusion are behaving differently in search with same regex.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#5852]
- VSCode Version:1.1.0-alpha
- OS Version: Windows10

Setup:
My Directory structure for CSS file.
{$workspaceRoot}\timer-styles1.css
{$workspaceRoot}\Scripts\timer-styles3.css
{$workspaceRoot}\Contents\app.css

Steps to Reproduce:
1. Launch app and open any folder which contains .CSS and .ts file with keyword "width".
2. Perform search for keyword: width. 
- Include .css file with regex: *.css
-Exclude .css file with regex: *.css

3. Verify search result in both the conditions.

Actual: File exclusion is only excluding .css file which is located at the root dir (in my case {$workspaceRoot}\timer-styles1.css)  whereas file inclusion is displaying result for all the available css file (root dir as well as sub directories)
Expected: File include and exclude filter should work uniformly for same regex.
![searchregexissueforexcludefile1](https://cloud.githubusercontent.com/assets/17735796/14824298/5698f124-0b8a-11e6-891d-9ec54e467b78.gif)

**Comment by bpasero** [comment]
Make sure you uncheck the "use glob pattern" toggle that you have enabled. This changes the pattern.
