### ISSUE TITLE
Debug changed variables highlight does not fade away

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#5853]
- VSCode Version: 1.1.0
- OS Version: Windows 10

Observe how `al` is highlighted, but the highlight does not fade away after a while.

![debug-highlight-no-fade](https://cloud.githubusercontent.com/assets/5047891/14824645/f3baa29e-0bd6-11e6-9762-9b05b3283d1b.gif)

**Comment by alexandrudima** [comment]
fyi @isidorn

**Comment by bgashler1** [comment]
That's odd.  It should fade using the animation `debugViewletValueChanged`.

```
@keyframes debugViewletValueChanged {
	0% { background-color: rgba(86, 156, 214, 0) }
	5% { background-color: rgba(86, 156, 214, .75) }
	100% { background-color: rgba(86, 156, 214, .3) }
}
.debug-viewlet .monaco-tree-row .expression .value.changed {
	padding: 2px;
	margin: 4px;
	border-radius: 4px;
	background-color: rgba(86, 156, 214, .5);
	animation-name: debugViewletValueChanged;
	animation-duration: .75s;
	animation-fill-mode: forwards;
}
```

However, I noticed that it's not using the correct `animation-name`.  See below.  This seems to be happening at build time (see blow web inspection of it in VS Code Alpha).

![screen shot 2016-04-26 at 11 57 57 am](https://cloud.githubusercontent.com/assets/11839736/14830563/2a10cfac-0ba6-11e6-8b0b-0822a62f1b6e.png)

**Comment by bgashler1** [comment]
@isidorn could you take a look at what's going on with this.

**Comment by isidorn** [comment]
@bgashler1 sure, I can investigate

**Comment by isidorn** [comment]
Yup, this was happening due to css minification, with Joao's help we could fix it.

**Comment by alexandrudima** [comment]
That looks scary

**Comment by bgashler1** [comment]
You guys are pros! Thanks
