### ISSUE TITLE
snippet transforms: upcase with replacement

### ISSUE THREAD

**Issue by dharrington** [Microsoft/vscode#58539]
Issue Type: <b>Feature Request</b>

Say you have a variable for which you want to replace slashes, and upper case the result. i.e.
"/path/to/file" -> PATH_TO_FILE
This doesn't appear possible. 
You can either substitute slashes
${var/\\//_/g}
Or apply uppercase
${var/(.*)/${1:/upcase}/}

I think you need two substitutions here. This would be possible if you allow recursive transforms: ${${...}/regex.../}

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:47.222Z)
OS version: Linux x64

**Comment by jrieken** [comment]
You can combine multiple match groups. This will do it: 

`"${TM_FILEPATH/([^\\/])|(\\/)/${1:/upcase}${2:+_}/g}"`

It matches on everything thats not the slash, captures in group 1, and applies the upcase-transform. Then there is group 2 which matches on slash only  and applies the replace with _
