### ISSUE TITLE
Terminal scrollbar starts at top

### ISSUE THREAD

**Issue by DBjelovuk** [Microsoft/vscode#58532]
- VSCode Version: 1.27.1
- OS Version: macOS High Sierra 10.13.5

Steps to Reproduce:

1. Open terminal
2. Scroll down

Does this issue occur when all extensions are disabled?: Yes

Resurgence of  #45134.

**Comment by Tyriar** [comment]
I think I saw this at one point recently but I had a lot of difficultly reproducing, any more info on a repro would be helpful.

**Comment by rotemdan** [comment]
I'm experiencing this consistently and was just about to report.

I was able to reproduce this on a fresh install of latest insider edition (Windows 10 64bit) with no extensions and no custom settings:

![terminalsrcollissue1](https://user-images.githubusercontent.com/8589488/45447839-7ca2c280-b6d9-11e8-8181-0fec428977f9.gif)

**Comment by Tyriar** [comment]
Just trying to repro again I notice that the scrollbar is broken in another way too. This happens after running `tree`, scrolling a little and then pressing ctrl+end 😕 

![image](https://user-images.githubusercontent.com/2193314/45455720-e81a6f00-b69c-11e8-8911-b21f7d37d432.png)

**Comment by parmentf** [comment]
I found this too, but only when having a lot of lines in the terminal (after running a script yielding several hundred lines of text).

After that, I can use Shift-PgUp to go one page up (from bottom), *but using the middle button of the mouse*, I can not, because the scroll bar is at top.
![vscode-scroll-terminal-pb2](https://user-images.githubusercontent.com/595509/45473867-80b1fd00-b738-11e8-839e-27371502b5c7.png)

**Comment by NoChapter** [comment]
Easy to reproduce. 

1. make terminal height over than one screen 
2. `` CRTL+` `` to hide terminal panel
3. ` CRTL+` `` again to reopen terminal panel ---- You would see the scroll bar is at top

Now, press `ENTER`, then the scroll bar would be at bottom immediately, as shown in the end of the following gif

![wkhjanjbs2](https://user-images.githubusercontent.com/1981743/45585436-bf9da980-b916-11e8-8fdd-c9219d1d6f45.gif)

**Comment by Tyriar** [comment]
@NoChapter thanks! 👍
