### ISSUE TITLE
Feature Request: cursor focus to integrated terminal on VSCode reload

### ISSUE THREAD

**Issue by emveeoh** [Microsoft/vscode#58534]
Upon a re-launch/re-load of VS Code, please re-apply the cursor focus to the integrated terminal if it was the last item to have focus before a re-load. This will save us from having to grab the mouse then click into the integrated terminal to give it focus again before continuing our typing.  Currently, the integrated terminal will lose focus after a re-launch of VS Code.

**Comment by Tyriar** [comment]
The editor always gets the focus by design. You could probably write an extension to do what you're after.
