### ISSUE TITLE
Allow multiple extension installs at one time from the CLI

### ISSUE THREAD

**Issue by ThadHouse** [Microsoft/vscode#58535]
I have an installer that is installing a list of extensions into VS Code via the CLI. Currently, I have to pass in my VSIX's one at a time, in the correct order in case of extension dependencies. It would be nice to be able to pass in a list of VSIX's that would get installed, and would detect dependencies between the extensions to ensure everything is good. 

This is for an offline setup for a standardized setup, so installing from the GUI is not an option.

**Comment by joaomoreno** [comment]
You can use `--install-extension EXT1 --install-extension EXT2`
