### ISSUE TITLE
Output channel for telemetry.log file

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#58536]
As per work done for #54001, we now have a telemetry.log file in the logs folder that tracks all telemetry events being logged in VS Code.

This file has been accessible using the `Open Log File` or `Open Log Folder` commands.

Since all the other "log" files also have a corresponding output channel, the telemetry.log file is an odd person out.

Also, due to recent [refactoring](https://github.com/Microsoft/vscode/commit/0f84693cb8c4b6b73802501e971e300f2d388567), the file is no longer accessible via the `Open Log File` command in 1.28 insiders.

This issue is to have an output channel for the `telemetry.log` file to make it more inline with the other log files.

cc @sandy081

**Comment by sandy081** [comment]
@ramya-rao-a Just to be clear, telemetry file was not accessible even before (refactoring). Because `Open Log File...` command always used to open `Log Viewer` which uses Output channels.

**Comment by ramya-rao-a** [comment]
@sandy081 Not true. The telemetry file is indeed accessible in 1.27.1
- Set log level to trace
- Open a few files
- Use the command `Open Log File..` and select `Telemetry` from the quick pick. 

The file will open in VS Code and will have the events corresponding to the file opens

**Comment by sandy081** [comment]
@ramya-rao-a I take back my comment. Yes you are right, it was showing the telemetry log before in the log viewer. 

I can enhance the log viewer to show log files which are not registered in output channel. Personally I think it will be much consistent if telemetry log is also part of the output channel just like others.

**Comment by ramya-rao-a** [comment]
If we do add an output channel for telemetry log, would it be possible to do that only when the user changes the log level to `trace`? Because otherwise, that channel will always be empty.

**Comment by sandy081** [comment]
May be register and de-register it ?
