### ISSUE TITLE
Gear doesnt appear on settings that take boolean

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#58538]
Issue Type: <b>Bug</b>

- Open new settings editor
- Hover over a setting that takes text value. Observe the gear
- Hover over a setting that takes boolean i.e it has a check box. Observe no gear

VS Code version: Code - Insiders 1.28.0-insider (31bf4ccab388c082fcf4edafeaae5b703f211b5b, 2018-09-12T05:18:53.705Z)
OS version: Windows_NT x64 10.0.17134

**Comment by itamark** [comment]
@ramya-rao-a @roblourens okay if I take a try at this?

**Comment by roblourens** [comment]
If you can do it within the next couple days, go ahead 😁 

But it's annoying me and I need to fix it soon.

**Comment by roblourens** [comment]
The bool control needs an element like this for the toolbar: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/preferences/browser/settingsTree.ts#L616

Which should be created here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/preferences/browser/settingsTree.ts#L788

Then some CSS rules may need to be tweaked, I'm not sure.

**Comment by itamark** [comment]
Hey - @roblourens @ramya-rao-a I see the issue in insiders build, but can't see it in OSS - do you?

<img width="732" alt="screen shot 2018-09-20 at 10 05 57 am" src="https://user-images.githubusercontent.com/1757393/45826320-f8fe5c80-bcfc-11e8-90cc-36a3c57b2b06.png">

**Comment by roblourens** [comment]
I can, I actually fixed it yesterday (and just pushed the commit) sorry
