### ISSUE TITLE
Parameter Hints Keep Coming Back

### ISSUE THREAD

**Issue by svanetten1976** [Microsoft/vscode#58547]
Downloaded the latest version yesterday (1.27.1) and I've gone into Preferences and unchecked the "Parameter Hints: Enabled" setting twice today and it keeps coming back. The old JSON preferences config worked just fine. What's the deal?!

 

- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
Can you share a screenshot of those parameter hints?

**Comment by svanetten1976** [comment]
Hey @joaomoreno - sure thing. Here is an example of the parameter hints that keep popping up. I've gone into Preferences and unchecked the "Parameter Hints: Enabled" box several times and it somehow keeps getting  turned back on. Definitely a bug in the software that this setting can't be saved. Not sure if this effects other settings. I previously used the old JSON settings, and that always worked fine. Thanks for looking into this
![vs-code-error](https://user-images.githubusercontent.com/1958184/45490769-fff20180-b735-11e8-8fd9-e10c63184e3f.png)

**Comment by svanetten1976** [comment]
@joaomoreno I erroneously closed this issue earlier when I posted the screenshot for you. This is definitely a bug

**Comment by joaomoreno** [comment]
So... just to confirm: you go to the settings, uncheck Parameter Hints and eventually the setting comes back? Does this reproduce with `--disable-extensions`?

**Comment by svanetten1976** [comment]
Yeah, basically I uncheck the box, close the settings and it comes back as checked immediately the next time I open the settings if I'm using the new Settings GUI. I found a workaround by opening the original settings.json file and manually adding "editor.parameterHints.enabled": false and that gets rid of these unwanted param hints.
  I kind of like handling the settings this way better than the GUI, but there is definitely a bug in the software for sure. Haven't tried disabling extensions because I actually need all the ones that I use (ESLint, JSX, Prettier, and TFS).

**Comment by roblourens** [comment]
Do you have `"editor.parameterHints"` set in your json file? That's the old form of that setting. It was renamed last month and the settings UI isn't able to handle the conflict. But there should be a warning in the JSON.

**Comment by svanetten1976** [comment]
actually, yeah that was my workaround -- opening settings.json and manually adding:
"editor.parameterHints.enabled": false

**Comment by roblourens** [comment]
I'm talking about `"editor.parameterHints"` not `"editor.parameterHints.enabled"`. Setting the second one doesn't work if the first is set.

**Comment by Pyrolistical** [comment]
Thank you @roblourens for the solution to actually disable parameter hints.

I cannot express how poorly this settings change was. I hate stuff that pops up on my cursor, so I disabled it. Then it comes in this bad change due to lack of settings migration. Then after I add the new setting it doesn't take affect because the previous one is in the way. This is the worst dev experience I've had with VS Code.
