### ISSUE TITLE
VSCode is not resolving aliases in tsconfig.json paths.

### ISSUE THREAD

**Issue by ashok-sc** [Microsoft/vscode#58543]
- VSCode Version: Version 1.27.1 (1.27.1)
- OS Version: MacOS High Sierra 10.13.4 (17E199)

Steps to Reproduce:

1. Create tsconfig.json file at root of my project with paths object.
2. Some files are able to resolve the aliases, but new files created are not able to resolve them.

Here's the `tsconfig.json` file (this is also the only tsconfig file in the entire project):
```
{
  "compilerOptions": {
    "outDir": "./compiled/",
    "sourceMap": true,
    "noImplicitAny": true,
    "module": "commonjs",
    "lib": ["es6", "dom", "esnext"],
    "target": "es6",
    "jsx": "react",
    "allowJs": true,
    "noUnusedLocals": true,
    "baseUrl": ".",
    "paths": {
      "@core/*": [
        "src/core/*"
      ],
      "@server/*": [
        "src/server/*"
      ],
      "@client/*": [
        "src/client/*"
      ],
      "@shared/*": [
        "src/shared/*"
      ]
    }
  },
  "include": [
    "./declarations/*",
    "./src/client/*",
    "./src/server/*",
    "./src/server/models/*",
    "./src/core/*"
  ],
  "exclude": [
      "./node_modules/"
  ]
}
```

Here's the path being resolved in one file (`src/client/store/actions/auth.ts`):
<img width="680" alt="screen shot 2018-09-12 at 11 43 54 am" src="https://user-images.githubusercontent.com/32855087/45446235-3752a680-b681-11e8-810b-5d1fe2d91ffc.png">

Here's the path NOT being resolved in another file (`src/client/store/actions/portfolio.ts`):
<img width="660" alt="screen shot 2018-09-12 at 11 45 03 am" src="https://user-images.githubusercontent.com/32855087/45446286-59e4bf80-b681-11e8-9802-b4f97be7788b.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
In `portfolio.ts`, if you run the `Typescript: Go to project configuration` command from the command palette, does it open the correct `tsconfig.json`?
