### ISSUE TITLE
Ctr+space shortcut does not open autocomplete suggestions anymore

### ISSUE THREAD

**Issue by bramvbilsen** [Microsoft/vscode#58548]
I used to be able to press "ctrl" and "space" at the same time to get my autocomplete suggestions. For some reason, that is not the behavior I see on my new computer with a fresh windows 10 install. Instead, the shortcut now switches windows.

I've searched for a way to revert this behavior but with no luck. Is this possible?

**Comment by ramya-rao-a** [comment]
- Do you have any extensions installed that might override the default keybinding?
- Run the command `Preferences: Open Keyboard Shortcuts` and look for `ctrl+space` and share a screenshot of that here

**Comment by bramvbilsen** [comment]
There are two keybindings assigned to `ctrl+space`:

- toggleSuggestionDetails
- triggerSuggest
I'm guessing these are equivalent.

**Comment by ramya-rao-a** [comment]
Yes.

@alexandrudima Any ideas why the Ctrl+Space keybinding is being taken over by the OS?

**Comment by bramvbilsen** [comment]
Just to add some more info:
I use a QWERTY international keyboard layout. I did not install any software to add keybindings to my OS and I do not believe that is possible without additional software on Windows 10.
The computer is a Dell XPS 9575 (15 inch 2 in 1). But I do not believe that makes a difference.

**Comment by alexandrudima** [comment]
@bramvbilsen Can you check if the keybinding reaches VS Code?

What does VS Code detect when you press the desired key combination? :
![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

**Comment by bramvbilsen** [comment]
Hi @alexandrudima, I just found the problem! It does actually work, but not when a program called "Terminus" is open. It is basically a alternative terminal and I almost always have it open to run commands.
Mystery solved! I guess I better make an issue on there github repo 🙂

**Comment by ramya-rao-a** [comment]
Thanks for getting back on that @bramvbilsen
