### ISSUE TITLE
Give better structure to `view`

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#58555]
![image](https://user-images.githubusercontent.com/4033249/45453940-185f0f00-b697-11e8-92dd-828562100d08.png)

Currently this command is very confusing in two ways:

- Why are panel items shown here? Are they "Views" or not?
- This quick pick result flattens the original hierarchy. Views contain Explorer, and Explorer contains the Sub Trees. It doesn't make sense that in the result `Explorer` and `Open Editors` are in the same level.

**Comment by bpasero** [comment]
Adding @sandy081 

I like the structure of the picker, it gives access to anything you can focus to in our UI. It is the one piece to discover everything we have, besides command palette. I would not go as far and introduce some tree or anything.

@octref can you make some suggestions what to change without changing the picker UX too much?

**Comment by sandy081** [comment]
I like the current picker hierarchy which is flat and shows groups.

`View` is an abstraction for all type widgets: Viewlets / Sections / Panels. Reasoning behind current picker is

- Show Viewlets and Panels first
- Show sections in each viewlet/panel

I would simplify more by removing Panels group and merge it in Views group

**Comment by octref** [comment]
@bpasero @sandy081 Functionality-wise, I think it's fine. The motivation was to https://github.com/Microsoft/vscode/issues/58226#issuecomment-419678487 and hope we can achieve some consistency in using the name "View" in our user doc.

> View is an abstraction for all type widgets: Viewlets / Sections / Panels.

That's the confusion here. When I say "views", am I referring to only the sidebar views or all the views?

@bpasero 

I think we can change the section header to the right a bit.

- `Explorer` to `Views/Explorer`, or alternatively `Views -> Explorer`
- `Output` to `Panels/Output`, or alternatively `Panels -> Output`

**Comment by bpasero** [comment]
@octref wanna do a PR for the changes you have in mind? That would be easier for me to see if it works or not. Keep in mind though that "view" and "panel" is a term we use in our commands as well.

**Comment by octref** [comment]
@bpasero Sure. Will do a PR.

**Comment by octref** [comment]
What I ended up with:

![image](https://user-images.githubusercontent.com/4033249/45850053-6bfdd800-bce9-11e8-842b-7417b4b7efb0.png)

PR at https://github.com/Microsoft/vscode/pull/59070.

**Comment by nealot** [comment]
My intention with that comment was never to change the behavior of the menu; I quite like how everything is organized without sub-labels because it just seems cleaner. I only wanted clarification on what a "view" represented because of how often the term was used.

> View is an abstraction for all type widgets: Viewlets / Sections / Panels. Reasoning behind current picker is

This seems like a reasonable explanation and the docs would benefit if it was added under an overview section.

My only concern is that the concept of a view is not currently explained well enough and its usage as a prefix in many commands is unnecessarily confusing. I think if the docs embraced a layout like https://atom.io/docs/api/v1.30.0/Workspace this issue might be remedied.

**Comment by sandy081** [comment]
@octref Not sure if I like `Views / Explorer` to represent views in Explorer. I think `Explorer` groups as is apts more. Also what is `Output / Extensions ` and `Panels / Output` ?

**Comment by eamodio** [comment]
What do you call the treeviews in each sidebar view? From a user point of view? In GitLens I call them explorers but would like to align terminology

**Comment by sandy081** [comment]
All of them are views and there can be explorers like File explorer, Gitlens explorer, History explorer etc.,

**Comment by octref** [comment]
> Views / Explorer to represent views in Explorer

That's why I said we need better terminologies. Here, ideally, it should be called `Sidebar Views / Explorer`. The `Views` comes from the first group (upper right). It does not refer to the generic "views" meaning.

> Output / Extensions

That's a bug I just fixed.

> Panels / Output

That means "Output Tab" in "Panels".

<img width="667" alt="illu" src="https://user-images.githubusercontent.com/4033249/45892792-06a7f680-bd7e-11e8-9f3a-8dd00784ee05.png">

**Comment by eamodio** [comment]
So explorers are the sidebar activities/views? And inside explorers are views (each tree?)

**Comment by eamodio** [comment]
Sidebar View (being on of Explorer, Search, etc) makes a lot of sense. Then each sidebar view has a set of views (the trees, etc). And then there are Panels (terminal, output, etc)

**Comment by bpasero** [comment]
@sandy081 since you added the views of a viewlet into the picker I am moving this to you to decide if this should go in or not. I am fine with the current approach but also with the new approach.

The only thing that seems a bit weird is to use "/" to outline the hierarchy of a view. Maybe there is a better character to use (Views > Extensions).

**Comment by sandy081** [comment]
@octref I see `Views /` is repeating for all. I think Group on the right is to mention the location of the views. Other than for side bar views group rest all are correctly mentioning the location in the group. How about just changing the first group name to `Side Bar` or `Activity Bar`?

**Comment by octref** [comment]
@sandy081 For being consistent with `Panels`, I think it should be `Sidebar Views`.

**Comment by sandy081** [comment]
I would just call `Side Bar` and `Panel` this is also consistent with our commands

`Toggle Side Bar Visibility` & `Toggle Panel`

**Comment by octref** [comment]
@sandy081 But in this single command, is `Panels / Output` consistent with `Side Bar / Explorer`?

The way the user would understand the strcuture is:

- I'm running `view`, so I expect results to be views
- I see `Sidebar Views` of 5 items, and later `Sidebar Views / Explorer`, so I understand the Sidebar has 5 views, and the later groups are sub-groups
- I also see `Panels` of 4 items, so I guess panel is a kind of view. `Panels / Output` should be a sub-category just like `Sidebar Views / Explorer`.

**Comment by sandy081** [comment]
If I understand correctly your suggestion is 

- `Side Bar`
  - `Explorer`
  - `Source Control`
- `Panels`
  - `Problems`
  - `Output`
- `Side Bar / Explorer`
  - `Open Editors`
- `Side Bar / Source Control`
  - `Gitlens`
- `Panels / Output`
  - `Tasks`
- `Panels / Terminal`
  - `Terminal 1`

It makes sense, but `Side Bar /` or `Panel /` prefix is not redundant? Is it possible to add screenshots of both options?

We can also get @misolori opinion for UX here.

**Comment by octref** [comment]
Let's get @misolori's opinion too, but what I'm saying is:
- `Panels` is a plural. `Problem` is a `Panel`, so is `Output`.
- `Side Bar` is a location. `Explorer` and `Source Control` are **not** `Sidebar` instances.
- `Side Bar` has no clear connection to the `view` prefix in the quickpick

My exact suggestion is:

- `Sidebar Views`
  - `Explorer`
  - `Source Control`
- `Panels` (or `Panel Views`)
  - `Problems`
  - `Output`
- `Sidebar Views / Explorer`
  - `Open Editors`
- `Sidebar Views / Source Control`
  - `Gitlens`
- `Panels / Output`
  - `Tasks`
- `Panels / Terminal`
  - `Terminal 1`

**Comment by misolori** [comment]
I find the redundancy of "views" and "side bar" a bit overkill and adds more confusion. If everything is a view then the word becomes meaningless, so I'd lean on using that word sparingly.

I do like @octref's suggestion (minus the views/sidebar repetition I mention above).

**Comment by octref** [comment]
If group names like `Sidebar Views` and `Panel Views` are a no-go, how about `Sidebar` and `Panel`? It matches the existing doc https://code.visualstudio.com/docs/getstarted/userinterface

So it would look like:

- `Sidebar`
  - `Explorer`
  - `Source Control`
- `Panel`
  - `Problems`
  - `Output`
- `Sidebar / Explorer`
  - `Open Editors`
- `Side Bar / Source Control`
  - `Gitlens`
- `Panel / Output`
  - `Tasks`
- `Panel / Terminal`
  - `Terminal 1`

**Comment by sandy081** [comment]
I like it except the repetition of `Sidebar / ${}` or `Panel / ${}`. If you do not think it is a redundancy please go ahead. Thanks.

**Comment by alexr00** [comment]
As far as I can tell this looks the same in stable and insiders right now. 
Stable:
![image](https://user-images.githubusercontent.com/38270282/47794177-3bfe1780-dd20-11e8-83aa-6932ab303b81.png)
Insiders:
![image](https://user-images.githubusercontent.com/38270282/47794227-56d08c00-dd20-11e8-8ce2-2638bc14d4cb.png)
@octref, how should this be verified?
