### ISSUE TITLE
Resizing VS Code Window causes Terminal to not update

### ISSUE THREAD

**Issue by catmorgan** [Microsoft/vscode#58553]
Issue Type: <b>Bug</b>

1. Run something in the terminal (preferrably something that takes at least a few seconds)
2. Resize your window
3. See that your terminal is frozen

Clicking on a different tab, say "Debug Console" and then going back to Terminal resolves it 

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:18.328Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3598)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.91GB (17.35GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.4
python|ms-|2018.8.0
cpptools|ms-|0.18.1
csharp|ms-|1.16.0
vscode-docker|Pet|0.2.0

</details>

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
