### ISSUE TITLE
Reopen closed files should also reopen closed editors

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#5855]
while testing #5586

- VSCode Version: alpha
- OS Version: linux

Steps to Reproduce:

1. open a file in an editor, close it by closing the editor (cltr + w)
2. ctrl + shift + t, the file is not reopened

I understand that the file is still in the working files and that the action might not be designed to do this. But IMHO this is very confusing for the user, most of our users have no clue what is a difference between closing an editor and closing a file and this action would just confuse them.

Setting to april for discussion
FYI @bpasero

**Comment by isidorn** [comment]
Also a smarter time to introduce this action might be when we do our tab changes, then these concepts should be clearer to users.

**Comment by isidorn** [comment]
Also a rename of action to 'Reopen Closed Working File' might reduce the confusion

**Comment by bpasero** [comment]
I would leave it as is and revisit this once we implement tabs and stack. Because then it will work more closely as expected.

**Comment by bpasero** [comment]
This should work ok now.

**Comment by isidorn** [comment]
Yeah - works much nicer with the new model
