### ISSUE TITLE
Syntax rule 'begin-end' stretch over too much, and extend it's parent range out

### ISSUE THREAD

**Issue by PrsPrsBK** [Microsoft/vscode#58551]
- VSCode Version: バージョン: 1.27.1 (user setup)
コミット: 5944e81f3c46a3938a82c701f96d7a59b074cfdc
日付: 2018-09-06T09:21:18.328Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

- OS Version: (`ver` output on `cmd.exe`) Microsoft Windows [Version 10.0.17134.228]

Steps to Reproduce:

1. Open this syntax highlighting project. [branch for this report](https://github.com/PrsPrsBK/vs-reST-highlight/tree/issue1)
2. With F5 key, start debugging, and insert backquote(`), also called backtick or so, like in screen shots.
  - Between first image and second, differnce is that underline and red color zone is stretching over or not.

This means two things. 
  1. Syntax begin-end rule, in this case \`... <>\`_ (spec is more complicated but the same happen),
    stretching over the range of parent. It's shown by underline.
    As shown in third image, this syntax rule works well inside middle paragraph.
  2. Parent block(middle paragraph) also stretcing. It's shown by red color stretch more than underline.

Parent block is also 'begin-end' syntax rule, the spec is [here](https://github.com/PrsPrsBK/vs-reST-highlight/blob/5cda111651d0e1538b7bb9080588ad9276fc67dc/syntaxes/reST.tmLanguage.json#L5), 
    and other syntax rules are soon below.

![2018-09-13_vs-issue01](https://user-images.githubusercontent.com/24764443/45451040-dd9bbc00-b714-11e8-897a-1faef311f17a.jpg)

![2018-09-13_vs-issue02](https://user-images.githubusercontent.com/24764443/45451065-f2784f80-b714-11e8-8829-cb56bf67ae55.jpg)

![2018-09-13_vs-issue03](https://user-images.githubusercontent.com/24764443/45451075-f86e3080-b714-11e8-96d5-b487798b9f1f.jpg)

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
From what I understand, that's how textmate grammars are supposed to work. Your last rule's begin pattern matches everything until it finds a backtick or underscore.

If you think this is a bug in our TextMate engine ([vscode-textmate](https://github.com/Microsoft/vscode-textmate)), please try your sample in the original [TextMate editor](https://macromates.com/download).

**Comment by PrsPrsBK** [comment]
> please try your sample in the original TextMate editor.

I'm Windows user and can not try, but thanks for reply and info. 
I understand and can decide to exclude  multiline link from highlighting.
