### ISSUE TITLE
"Fix all" doesn't fix all

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#58557]
- Add `"prefer-const": true` to tslint.json
- Open searchview.ts
- Find one of the many warnings
- Press cmd+. and run "Fix all: 'Identifier xyz never reassigned..."
- A random subset of them are fixed, not all of them. Same for "Fix all auto-fixable problems"

**Comment by mjbvz** [comment]
Hey can you please test this with the latest vscode-tslint-plugin installed. I replaced all `const` `let` and then triggered the code action. All of them seemed to be fixed

**Comment by roblourens** [comment]
Sorry do you mean the TS plugin or the eg2.tslint?

**Comment by mjbvz** [comment]
The vscode-tslint-plugin. It's the recommended one in our workspace now

**Comment by roblourens** [comment]
Yeah that seems to have worked.

**Comment by usernamehw** [comment]
https://github.com/Microsoft/vscode-tslint/issues/414
