### ISSUE TITLE
Having option to have multiple tabs as dropdowns

### ISSUE THREAD

**Issue by nat-** [Microsoft/vscode#58554]
In the bottom panel it would be nice to have the different terminals as tabs instead of the dropdown.
![image](https://user-images.githubusercontent.com/4308070/45453899-3cbdf880-b736-11e8-99b0-4e56a112df78.png)
also would be nice to use shortcut ```ctrl + ` + [number] ``` to swap between terminals.

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/10546
