### ISSUE TITLE
Visual studio code no longer allows cntrl-click to go to an error after latest update.

### ISSUE THREAD

**Issue by gilcolgate** [Microsoft/vscode#58552]
Issue Type: <b>Bug</b>

1. Type the command line to build a program using gcc into the integrated terminal in visual studio code.
2. Note that you have a syntax error.
3. Try to control click on the error message.
4. It doesn't do anything. It should take you to the line in the file in question.

Formerly I could just run build commands in the integrated terminal, and then control click on the error results to jump to the associated files. This has stopped working with the recent update.

I do not use tasks.json or 'build', I just run the command directly in the terminal. 

Note: I have never used build tasks, but when I try (given hints about this on the web) I see a lot of npm build tasks for our javascript. Turning these off in preferences continued to show these. 

 

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:47.222Z)
OS version: Linux x64 4.15.0-33-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HK CPU @ 2.90GHz (8 x 3736)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 1|
|Memory (System)|31.37GB (12.57GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
bazel-code|Dev|0.1.9
code-gnu-global|aus|0.2.2
githistory|don|0.4.2
gitlens|eam|8.5.6
jumpprotobuf|ldc|0.0.3
rainbow-csv|mec|0.5.0
vscode-clang|mit|0.2.2
cpptools|ms-|0.18.1
vscode-epics|nsd|0.0.2
blank-line-organizer|rin|0.1.2
trailing-spaces|sha|0.2.11
code-spell-checker|str|1.6.10
clang-format|xav|1.6.2

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by gilcolgate** [comment]
Yes it is fixed
