### ISSUE TITLE
Latest visual studio code crashes on Ubuntu

### ISSUE THREAD

**Issue by jonnygrant** [Microsoft/vscode#58556]
Issue Type: <b>Bug</b>

Click File->Preferences

All default install. I'm a new user, clean machine

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:47.222Z)
OS version: Linux x64 4.15.0-34-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz (8 x 1719)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 2|
|Memory (System)|15.55GB (1.27GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by joaomoreno** [comment]
> crashes

Where is the crash? Screenshot? Log file? Screen recording? Please provide more info.

**Comment by jonnygrant** [comment]
Does it include a crash dumper? It didn't output anything

1. install ubuntu LTS, with gnome classic desktop
2. install vs code latest
3. Click Applications->Programming->Visual Studio Code
4. Click File->Preferences
5. Observe the application closes (crashed right?)

How to make a log file? where does it dump them when it crashes?

**Comment by joaomoreno** [comment]
Here is a **checklist** to find out more about the freeze/slow/crash
- [ ] it reproduces with extensions disabled (`code --disable-extensions` from the command line - NOT the integrated terminal of Code)
    - if it does not reproduce with extensions disabled, you can stop testing and report this!
- [ ] it was not happening in the previous stable release
- [ ] it reproduces in insiders builds (get it from [here](http://code.visualstudio.com/Download#insiders))
- [ ] there is no suspicious output when running from the command line (`code --verbose`)
- [ ] there is no suspicious output in the window itself (Help | Toggle Developer Tools | Console)
- [ ] it reproduces on Windows, Linux and Mac
- [ ] it reproduces after deleting `<appdata>/User/keybindings.json` and `<appdata>/User/settings.json` (backup first! see below for paths)
- [ ] it reproduces when opening empty (`code -n` from the command line)
- [ ] it reproduces opening any folder
- [ ] it reproduces opening any file
- [ ] it reproduces when only having a single window open
- [ ] it reproduces by just using Code without external tools running on the same folder
- [ ] it reproduces from a workspace that is not under Git version control
- [ ] it reproduces independently if a file is opened or not after startup
- [ ] it reproduces when running with GPU disabled (`code --disable-gpu`)
- [ ] it reproduces when being offline
- [ ] it reproduces when disabling the file watching (set `files.watcherExclude` to `"**/**": true`)
- [ ] it reproduces after uninstalling and reinstalling
- [ ] it reproduces after deleting the application data directory (backup first! see below for paths)
- [ ] I have not played around with permissions or ran Code as administrator
- [ ] I am seeing a single CPU process spin high (please share the full command line arguments)
- [ ] I am seeing Code consuming lots of memory in a short time

**Application Data Directory for VS Code:**
* Windows: `C:\Users\<user>\AppData\Roaming\Code`
* Mac: `/Users/<user>/Library/Application Support/Code`
* Linux: `/home/<user>/.config/Code`

**Application Data Directory for VS Code Insiders:**
* Windows: `C:\Users\<user>\AppData\Roaming\Code - Insiders`
* Mac: `/Users/<user>/Library/Application Support/Code - Insiders`
* Linux: `/home/<user>/.config/Code - Insiders`

**Comment by jonnygrant** [comment]
Forgive me, but I don't work for Microsoft. It looks like you're not responding to my questions.

Did you read my message and try and reproduce?

"How to make a log file? where does it dump them when it crashes?£

Did anyone do as I asked, and add the missing automatic crash dumper?

If you're not willing to co-operate with me, better just close the ticket and we'll go back to other developer environment.

**Comment by joaomoreno** [comment]
> Did you read my message and try and reproduce?

Yes, it doesn't reproduce for me.

Check here to understand how to debug crashes: https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues#linux

**Comment by jonnygrant** [comment]
Any reason it doesn't generate the crash dump automatically like other Linux packages do?

**Comment by joaomoreno** [comment]
cc @bpasero for answering that.

Anyway... did you figure anything out?

**Comment by jonnygrant** [comment]
Waiting for the auto crash dumper

**Comment by joaomoreno** [comment]
OK.
