### ISSUE TITLE
languages.createDiagnosticCollection() behavior changed, no longer returns existing diagnostic collection

### ISSUE THREAD

**Issue by TravisTheTechie** [Microsoft/vscode#58564]
- VSCode Version: 1.27.1
- OS Version: All (confirmed Linux & macOS)

Steps to Reproduce:

1. `let diagnosticCollection = languages.createDiagnosticCollection("Write-Good Lints");`
2. `diagnosticCollection.clear();`
3. diagnostics are expected to be cleared. What happens, it appears, is that a new "owner" is assigned each time ("Write-Good Lints", "Write-Good Lints0", "Write-Good Lints1", etc) and thus existing diagnostics are not associated with the call. 

Prior to 1.26.1 (?),  [`languages.createDiagnosticCollection("Write-Good Lints")`](https://github.com/TravisTheTechie/vscode-write-good/blob/master/src/extension.ts#L40) worked as expected. Now there is no way for me to clear old diagnostics and they continue to build up every activation. 

Does this issue occur when all extensions are disabled?: No. It's extension behavior. 

Re: https://github.com/Microsoft/vscode/issues/56923
Re: https://github.com/TravisTheTechie/vscode-write-good/issues/10
Re: [Test validating this behavior, that breaks existing behavior](https://github.com/Microsoft/vscode/blame/25d5dfe63a7dcfdb7ba541a26baf61605fb679f9/src/vs/workbench/test/electron-browser/api/extHostDiagnostics.test.ts#L369-L370)
Re: https://github.com/Microsoft/vscode/commit/b9459731b046fbb27e739e4822f0ca3894633e25 comment adding this behavior.

**Comment by TravisTheTechie** [comment]
@doug-episource I've opened a new issue rather than attempting to resurrect the old issue on this topic, I imagine you have interest in this.

**Comment by jrieken** [comment]
> Prior to 1.26.1 (?), languages.createDiagnosticCollection("Write-Good Lints") worked as expected. 

That was a bug in the implementation of diagnostic collections. See https://github.com/Microsoft/vscode/issues/54359. It was never intended that collection get re-used, that why it is prefixed with *create* and not *getOrCreate*DiagnosticCollection

> Now there is no way for me to clear old diagnostics and they continue to build up every activation.

That's not true. Just keep a reference to the collection you have created and call [`collection.set(undefined)`](https://github.com/Microsoft/vscode/blob/3da2f86e4dfdf0f183810a9b6d5c5a22ba692e5e/src/vs/vscode.d.ts#L4151), [`collection.clear`](https://github.com/Microsoft/vscode/blob/3da2f86e4dfdf0f183810a9b6d5c5a22ba692e5e/src/vs/vscode.d.ts#L4165), or [`dispose`](https://github.com/Microsoft/vscode/blob/3da2f86e4dfdf0f183810a9b6d5c5a22ba692e5e/src/vs/vscode.d.ts#L4197). That will clear all diagnostics from the collection. Also, use `set` with a specify uri to replace the diagnostics for a single file.
