### ISSUE TITLE
window (filename.extension - folder)taking over 100% cpu

### ISSUE THREAD

**Issue by dereknelson** [Microsoft/vscode#58561]
Issue Type: <b>Bug</b>

[Screenshot](https://prnt.sc/ktr0oc) 

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:14:32.385Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz (12 x 3300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (1.16GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.59
vscode-eslint|dba|1.6.0
auto-close-tag|for|0.5.6
camelcasenavigation|map|0.3.48
vscode-react-native|vsm|0.6.16
vscode-wakatime|Wak|1.2.3
vscode-jumpy|wma|0.3.1

(1 theme extensions excluded)

</details>

 

- VSCode Version:
- OS Version:

--status output: 
```
Version:          Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:14:32.385Z)
OS Version:       Darwin x64 17.6.0
CPUs:             Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz (12 x 3300)
Memory (System):  16.00GB (1.75GB free)
Load (avg):       2, 3, 3
VM:               0%
Screen Reader:    no
Process Argv:     /Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_49164
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    enabled
                  rasterization:                unavailable_software
                  video_decode:                 enabled
                  video_encode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled
CPU %   Mem MB     PID  Process
   16       98     431  code main
   54       66     517     gpu-process
    0       66     678     shared-process
   93      393    9958     window (ProfileScreen.js — code)
    6      131    9961       extensionHost
    0       66    9965         electron_node eslintServer.js
    0       33   10402         /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=9961
    0      279   16749         electron_node tsserver.js
    0       33    9962       watcherService
    0       16    9980       searchService
    0        0   16980       /bin/zsh -l
    0        0   17252         bash /usr/local/bin/code --status
   17       49   17263           electron_node cli.js
    1       82   16493     window (Process Explorer)

Workspace Stats:
|  Window (ProfileScreen.js — code)
|    Folder (code): 1391 files
|      File types: js(1279) ttf(33) png(21) DS_Store(14) json(11) xml(5)
|                  properties(3) gradle(3) java(2) svg(2)
|      Conf files: settings.json(3) package.json(2) launch.json(1)
|      Launch Configs: reactnative
```

Does this issue occur when all extensions are disabled?: No, it seems to be related to [indent-rainbow and Rainbow Brackets](http://prntscr.com/ktr3ka) but this issue has come out of nowhere

**Comment by mjbvz** [comment]
Since this only reproduces when you have those extensions enabled, please start by filing issues against those extensions. Then if the extension authors believe it is actually a VS Code issue, they can move it back to our side
