### ISSUE TITLE
Emmet doesn’t work inside html file with the script tag

### ISSUE THREAD

**Issue by serhii12** [Microsoft/vscode#58562]
Emmet works with:
 
`div.example tab = <div class="example"></div>
` 
or the external JS file

It doesn't work with this:
<img width="291" alt="screenshot 2018-09-12 19 48 37" src="https://user-images.githubusercontent.com/37387626/45459120-dcdb3980-b6c4-11e8-8251-77f727919bbb.png">

- VSCode Version: Version 1.27.1 (1.27.1)
- OS Version: macOS High Sierra 10.13.6

**Comment by ramya-rao-a** [comment]
Pushed a fix to allow html emmet completions inside script tag if javascript is mapped to html in the `emmet.includeLanguages` setting

**Comment by serhii12** [comment]
Thank you for the assistance @ramya-rao-a  !👍
