### ISSUE TITLE
Matplotlib import issue with latest VSCode update

### ISSUE THREAD

**Issue by benjaminpaik** [Microsoft/vscode#58569]
We have written the needed data into your clipboard because it was too large to send. 
Issue Type: <b>Bug</b>

I am using Anaconda 3.6 with VSCode on Windows 10. I have been having some issues running scripts that use matplotlib where none of the plots will appear (even though they were previously working fine only a few weeks ago). After troubleshooting a bit I discovered that changing "python.pythonPath": "C:\\ProgramData\\Anaconda3\\pythonw.exe" to use "python.exe" instead of "pythonw.exe" seems to get the plots to display again. At first I thought this was due to the latest VSCode update, but now I suspect it is likely due to the python plugin since reinstalling the older VSCode version didn't seem to work. In any case, I am fine with the workaround as everything seems fully functional again.

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:18.328Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.92GB (3.62GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|2.18.0
flutter|Dar|2.18.0
Kotlin|mat|1.6.0
anaconda-extension-pack|ms-|1.0.0
python|ms-|2018.8.0
cpptools|ms-|0.18.1
team|ms-|1.136.0
vscode-yaml|red|0.0.16

</details>
Please paste.

**Comment by octref** [comment]
This should be an issue reported for the Python extension. Thanks!
https://github.com/Microsoft/vscode-python
