### ISSUE TITLE
Intellisense timing out

### ISSUE THREAD

**Issue by bmorganatlas** [Microsoft/vscode#58567]
Issue Type: <b>Bug</b>

I'm working in a basic node project on ubuntu and intellisense seems to be timing out.

ctrl-space doesn't complete and  i get a status bar flashing along the top of the editor.

I haven't got a way to reproduce this atm though, It just seemed to happen when I started using vscode.

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:47.222Z)
OS version: Linux x64 4.15.0-34-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 1830)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.62GB (1.91GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.6.0
tslint|eg2|1.0.39
intellij-idea-keybindings|k--|0.2.26

</details>

**Comment by bmorganatlas** [comment]
I currently have several directories in a single workspace. When I open the node project alone (outside of the workspace) intellisense is fine.
For now I'll just open folders directly rather than using workspaces as a workaround

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by bmorganatlas** [comment]
I just tried the workspace on the latest insiders build and it works fine.

thanks

BeN Morgan

Senior Developer

**Comment by mjbvz** [comment]
Thanks. Please let me know if you start seeing this again
