### ISSUE TITLE
Go to symbol in workspace gets borked when large TypeScript codebases are still loading

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/vscode#58560]
Noticed this with @ahejlsberg

1. Clone https://github.com/Microsoft/TypeScript
2. Open Code in `src/compiler`.
3. Open `checker.ts`
4. Use go-to-symbol-in-workspace (`Ctrl+T`) and type in `inferType` in the 5-6 seconds before colorization finishes and TypeScript loads the project.
5. Let the project load
6. Try using go-to-symbol-in-workspace is borked. Results don't get populated in the pane.

**Comment by mjbvz** [comment]
Adding @jrieken and @bpasero since this looks like an issue in vscode core. In the file `openSymbolHandler.ts` in `getResults`, we end up not re-invoking `doGetResults`. When debugging I never see the delayer triggering again

**Comment by roblourens** [comment]
What do I expect to see exactly? I follow the steps in the OP and get "no symbols matching". Then if I wait and try again, I get symbols.

**Comment by mjbvz** [comment]
The original bug is that triggering search early broke symbol search for the entire rest of the session until you restarted vscode. For verification, make sure that once the js/ts language features come online, symbol search starts working
