### ISSUE TITLE
Use of second code line plt.axis('equal') prevents 2nd quiver plot

### ISSUE THREAD

**Issue by j-a-lewis** [Microsoft/vscode#58579]
I am graphing vectors using matplotlib.pyplot imported as plt and the quiver method.  As part of setting up the graph, I have a code line plt.axis('equal').  To avoid file multiplicity and to graph another vector within the same batch of code but trying to practice writing Python code as much as possible, I just start over again from scratch rewriting pretty much the same code to graph yet another vector.  Works fine, unless I include in the 2nd batch of code another copy of the setup line plt.axis('equal')  If I do that, I fail to get the 2nd quiver plot and I get an error of the following type: 

2-MagnitudeAmplitudeChanges.py", line 45, in <module>
    plt.axis('equal')
TypeError: 'str' object is not callable

If I comment out the second copy of that line, e.g., # plt.axis('equal'), the 2nd plot is also done and no error msgs.  At the very least, there ought to be a better error message than "'str' object is not callable"   Below I copy the code in question:

# HOORAY!  This Code works

# Demonstrates that matrix transformations of vectors can result
# in either magnitude or amplitude (direction) changes or both

# Magnitude Change only
import numpy as np 
import matplotlib.pyplot as plt 

# Define vector v and matrix A
v = np.array([1,0])
A = np.array([[2,0],
              [0,2]])

t = A @ v
print('Here is vector v\n', v)

print('\nTransformed vector t by scalar\n', t)

# now plot v and t
vecs = np.array([t,v])
origin = [0], [0]
plt.axis=('equal')
plt.grid()
plt.ticklabel_format(style='sci', axis='both, scilimits=(0,0)')
plt.quiver(*origin, vecs[:,0], vecs[:,1], color=['blue','orange'],scale=10)
plt.show()

# Now transform vector by amplitude (direction) but not by magnitude with a matrix

# NOTE THE CODE BELOW WILL NOT GIVE PLOT UNLESS I COMMENT OUT plt.axis('equal') below
import numpy as np 
import matplotlib.pyplot as plt
# %matplotlib inline #only needed for Juypter

u = np.array([1,0])
B = np.array([[0,-1],
              [1,0]])

r = B @ u
print('\nOriginal u\n', u)
print('\nB @ u = r, direction changed but not magnitude\n', r)

# Now plot u and r
vecs = np.array([u,r])
origin = [0], [0]
# NOTE: line below must be commented out to get 2nd plot, no error msgs
plt.axis('equal')
plt.grid()
plt.ticklabel_format(style='sci', axis='both', scilimits=(0,0))
plt.quiver(*origin, vecs[:,0], vecs[:,1], color=['orange', 'blue'], scale=10)
plt.show()

**Comment by joaomoreno** [comment]
This issue was closed because it doesn't meet our standards of a properly filled issue. Please read our guide about [Submitting Bugs and Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).
