### ISSUE TITLE
Panel: remove the "toggle location" action in the panel header and move it to menu

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#58575]
I would like us to clean up the amount of actions in the panel:

![image](https://user-images.githubusercontent.com/900690/45470252-5c045800-b72d-11e8-8e0b-d78ac7bcc3ff.png)

The action to move the panel to the right is quite prominent imho. I know we probably added it for discoverability of this feature, but how often is it actually being used from there?

I suggest to check with telemetry and maybe remove it in favour of our command palette and menu. Turns out this command is actually currently not in the "Appearance" menu, where it should probably be added.

/cc @misolori @stevencl

**Comment by isidorn** [comment]
Yeah the reason it is there is discoverabilty, users only click it once.
I can check telemetry for numbers. Also fyi Chrome dev tools keeps it very prominent.

So I suggest we remove it from there and add it to the appearance menu and we also add it as a context menu on the panel title area.
To be consistent we could also add Move Sidebar Right / Left to the sidebar context menu area. Above Hide Sidebar

![screen shot 2018-09-18 at 12 55 21](https://user-images.githubusercontent.com/1926584/45682909-1cc97300-bb42-11e8-9d2a-c403edab778c.png)

Above hide panel

![screen shot 2018-09-18 at 12 55 31](https://user-images.githubusercontent.com/1926584/45682921-2652db00-bb42-11e8-8279-547495776b04.png)

**Comment by bpasero** [comment]
Yeah I like that. Not sure about the side bar having a need to have the command so prominently, simply because it seems a much less often command people would invoke compared to the other.

**Comment by isidorn** [comment]
Let's do this in october, since I am swamped in issues after vacation in this milestone.

**Comment by misolori** [comment]
We currently don't have a "Move Side Bar Right" in the context menu of the activity bar so I wouldn't assume that we'd do the same for the panel.

**Comment by isidorn** [comment]
Well as I mentioned above we can add it in both places. Or as Ben believes the panel is moved to the right more often so it is the only that deserves this (a bit fishy). IMHO I would just add it in both places, but let's see next milestone
