### ISSUE TITLE
Json File Warning

### ISSUE THREAD

**Issue by fourcels** [Microsoft/vscode#58571]
Issue Type: <b>Bug</b>

Problems loading reference 'http://json-schema.org/draft-07/schema': Unable to load schema from 'http://json-schema.org/draft-07/schema': Unable to connect to http://json-schema.org/draft-07/schema. Error: connect ECONNREFUSED 185.199.108.153:80

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:14:32.385Z)
OS version: Darwin x64 17.7.0

**Comment by aeschli** [comment]
I verified that the URL is valid. This is likely a connectivity issue. See https://code.visualstudio.com/docs/setup/network#_legacy-proxy-server-support for how to configure proxy support.
