### ISSUE TITLE
Clicking a moved file's git entry attempted to load the file - from its old location

### ISSUE THREAD

**Issue by mgerner** [Microsoft/vscode#5857]
I moved a file from one folder to another (by dragging it in the explorer tree), and then also renamed it. Clicking the git entry for the "deleted" file path apparently attempted to open the file at its old location, causing an error. This seems wrong - the application should've known that the file isn't there.

However, I wasn't actually able to reproduce it - doing the move/rename again and clicking the equivalent git entry didn't try to open it. Restarting VS Code, I can now click the git entry again (for "internal_user_nav.html") and it displays the contents of the file (at the time of the move).

This is minor, of course, but reporting it anyway since something clearly wasn't completely correct, even if it was transient.

- VSCode Version: 1.0.0 (Commit fa6d0f03813dfb9df4589c30121e9fcffa8a8ec8)
- OS Version: Debian stretch

Steps to Reproduce:

1. Unknown.

![screenshot](https://cloud.githubusercontent.com/assets/995315/14825709/dca010fc-0bd2-11e6-8117-c6a56cf3d107.png)

**Comment by bpasero** [comment]
I am not able to reproduce on Ubuntu.
