### ISSUE TITLE
html文件右键格式化问题

### ISSUE THREAD

**Issue by wangyongjie2017** [Microsoft/vscode#58578]
Issue Type: <b>Bug</b>

##### html文件，在style中书写完css样式后，右键格式化后出现url链接中 "http:" 与 "//" 之间存在空格的问题。
![image](http://gfs12.gomein.net.cn/T12fJbB7Cv1RCvBVdK.png)

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:14:32.385Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570R CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.18GB free)|
|Process Argv|/Users/opg/Desktop/myTool/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
css-compressor|bes|0.0.2
vscode-gutter-preview|kis|0.14.1
vscode-language-pack-zh-hans|MS-|1.27.2
LiveServer|rit|5.1.1
vscode-preview-server|yui|1.0.1

</details>

**Comment by aeschli** [comment]
Can you please add a sample code? Also, the screenshot seems to be broken

**Comment by wangyongjie2017** [comment]
> 你能加一个示例代码吗？此外，截图似乎已被打破

##### html文件，在style中书写完css样式后，右键格式化后出现url链接中 "http:" 与 "//" 之间存在空格的问题。（Right-click formatting has a space problem）

[问题图片 (Screenshot)](http://gfs12.gomein.net.cn/T12fJbB7Cv1RCvBVdK.png)

**Comment by aeschli** [comment]
reproduced with
```html
<html>
<style>
    .foo {
        background: url(http://abc.com)
    }
</style>

</html>
```

**Comment by wangyongjie2017** [comment]
#### Right click on the formatted code and a space will appear in the url link.
[Question](https://ws1.sinaimg.cn/large/93838f95ly1fv89xuxr9lj21d00gqjua.jpg)

<img width="882" alt="9" src="https://user-images.githubusercontent.com/27724335/45494283-46ca1080-b7a3-11e8-8b57-f8c8e19e402a.png">

**Comment by aeschli** [comment]
Thanks. I pushed a fix by updating to the latest version of jsbeautify

**Comment by wangyongjie2017** [comment]
#### Thank you, I am very happy to communicate with you, thank you very much.
