### ISSUE TITLE
Ansi color code got garbled when start ipython from integreted terminal

### ISSUE THREAD

**Issue by fksad** [Microsoft/vscode#58576]
- VSCode Version: 1.27.1 (system setup)
- OS Version: win10, 1803, os.version=17134.228

Steps to Reproduce:

1. start integrated terminal (cmd or cmder)
2. start ipython
3. get garbled ansi color code 

![image](https://user-images.githubusercontent.com/10517914/45470268-b74f3e00-b75f-11e8-9494-eb0986e66c34.png)

when I use cmd or cmder without vscode, ipython just works fine.

![image](https://user-images.githubusercontent.com/10517914/45470365-1e6cf280-b760-11e8-8ae4-c59ad9c97045.png)

p.s. I tried start ipython with arg "--simple_prompt" which works fine, however, those handy feature such as auto-completation can not use.

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
