### ISSUE TITLE
光标总变粗不能够正常使用

### ISSUE THREAD

**Issue by Mmxya** [Microsoft/vscode#58573]
Issue Type: <b>Bug</b>

光标总变粗不能够正常使用，无法正常打字

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:02:28.333Z)
OS version: Darwin x64 17.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.11GB free)|
|Process Argv|/private/var/folders/q8/p3kf8q493nz7dbh4ngsbzmvc0000gn/T/AppTranslocation/FF62508E-BF92-45E6-8200-9D6FE217BE90/d/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-javascript-snippet-pack|aka|0.1.5
html-class-suggestions|And|1.0.7
vscode-eslint|dba|1.4.12
vscode-babel-coloring|dza|0.0.4
html-to-javascript-string|evi|0.0.6
vue|liu|0.1.5
vscode-language-babel|mgm|0.0.20
vscode-language-pack-zh-hans|MS-|1.25.3
team|ms-|1.136.0
vscode-janus-debug|otr|1.0.10
vscode-html-scss|P-d|0.0.42
vscode-css-peek|pra|2.1.0
html-to-jsx|ria|0.0.1
sass-indented|rob|1.4.9
vim|vsc|0.16.4
prettify|whi|0.0.2
vscode-js-console-utils|wht|0.7.0
JavaScriptSnippets|xab|1.7.0
html-css-class-completion|Zig|1.17.1

</details>

**Comment by alexandrudima** [comment]
@Mmxya uninstall the vim extension.
