### ISSUE TITLE
Zoom affecting search bar in Extensions viewlet

### ISSUE THREAD

**Issue by tinkode56** [Microsoft/vscode#58585]
Issue Type: <b>Bug</b>

When you zoom in your code, it affects the text you write in the Extension search bar.

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:18.328Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3591)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (3.33GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Users\uia94882\Desktop\web|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
jsrefactor|cms|2.14.1
gitlens|eam|8.5.6
vsc-material-theme|Equ|2.4.2
beautify|Hoo|1.4.3
cpptools|ms-|0.18.1
LiveServer|rit|5.1.1
vscode-arduino|vsc|0.2.20

(1 theme extensions excluded)

</details>

![1](https://user-images.githubusercontent.com/15201231/45475981-8282bd00-b746-11e8-89fd-469cc05fade1.png)
![2](https://user-images.githubusercontent.com/15201231/45475982-8282bd00-b746-11e8-8392-d8e287e2b681.png)

**Comment by ramya-rao-a** [comment]
@tinkode56 
I can't replicate this on Windows using VS Code 1.27.1
Can you share your settings?

**Comment by ramya-rao-a** [comment]
@tinkode56 Did you zoom in using the mousewheel? Do you have the `editor.mouseWheelZoom` setting enabled? If yes, then #58784 is tracking this issue.
