### ISSUE TITLE
Django python debug lines of code with debug symbols are not highlighted  

### ISSUE THREAD

**Issue by AliEzzatOdeh** [Microsoft/vscode#58594]
- VSCode Version:1.27.1
- OS Version: Windows 10 Enterpise

Steps to Reproduce:

1.Debug a Django project with some debug symbols on views.py
2.After the project runs successfully start navigating from your application to make some point attached

Current behavior:
Application in browser pauses, but visual studio code is not activated as if nothing is attached, once it is navigated back to visual studio code the debug tab is activated but no line is highlighted and continuing or jumping to other symbols is not reflected in UI,  also variables information and call stack are not displayed.
-------------------------------------------------------------------------
I tried installing version 1.25.1 to debug same project with same settings and reinstalled python extension to get everything working again as expected

**Comment by weinand** [comment]
Please file this issue against the Python extension.
