### ISSUE TITLE
C# Extension Broke during VS Code Update

### ISSUE THREAD

**Issue by 4verage** [Microsoft/vscode#58598]
- VSCode Version: 1.27.1
- OS Version: Windows 10 Home 1803

Steps to Reproduce:

1. Update VS Code to 1.27.1
2. Open C# Project Folder
3. Uninstall / Reload C# Extension
4. Install / Reload C# Extension
5. Restart VS Code
6. Open C# Project Folder (again)

Does this issue occur when all extensions are disabled?: Yes/No

Can't successfully answer, build fails and references launch.json, but opening the file contains no specific reason for failure.

**ISSUE**

Upon closing VS Code there was an "updating" widget on my desktop from where apparently VS Code was updating in the background. On the next launch all C# Code was underlined in red and getting Predefined errors for simple objects like 'System.Object' not being an item.

Removed C# OmniSharp Extension, and all highlighting went away, but unable to compile code. Re-installed and highlighting returned with over 10k errors. Code was working perfectly before this update.

I can't find anyone else experiencing this problem, but I cannot determine what I am doing wrong. 

Thank You!

**Comment by joaomoreno** [comment]
Please file this issue in https://github.com/OmniSharp/omnisharp-vscode/issues
