### ISSUE TITLE
Feature Request: Debug view as explorer sub-view or right-pane view.

### ISSUE THREAD

**Issue by serhiisol** [Microsoft/vscode#58595]
During debugging session it's nice to have access to the explorer at the same time without switching views. Currently if you want to open another file to put a breakpoint I have to switch to explorer, find file, put breakpoint and again switch view to debug view to see variables, stack trace etc.

So the idea is to put debug view as subview of explorer (like outline view) or create another sidebar where debugger view can be open.

Example of the feature:
As debug view in a separate sidebar
![debugview](https://user-images.githubusercontent.com/8107129/45484478-ea440280-b75c-11e8-9667-90a48770395b.png)

As subview
![debugsubview](https://user-images.githubusercontent.com/8107129/45485358-009f8d80-b760-11e8-81e3-176b8bbb25f1.png)

**Comment by nealot** [comment]
See https://github.com/Microsoft/vscode/issues/26777 and https://github.com/Microsoft/vscode/issues/15038.

**Comment by serhiisol** [comment]
That's not exactly what I've tried to explain/request here. I've focused this request on debug view. It can be either new view in new sidebar (yes, those tickets are good for pointing) or as subview (which also solves an issue).
