### ISSUE TITLE
Annoying incorrect autocomplete when typing fast

### ISSUE THREAD

**Issue by enisdenjo** [Microsoft/vscode#58590]
- VSCode Version: 1.27.1
- OS Version: macOS High Sierra 10.13.6
- Mac Pro: 3.5 GHz 6-Core Intel Xeon E5, 32GB RAM, PCIe-based SSD

Steps to Reproduce:

1. Have a averagely sized TypeScript project
2. Type `console.log` fast
3. Type in an opening bracket `(`
4. Often enough `console()` will be autocompleted!

Does this issue occur when all extensions are disabled?: **Yes**

Example **with all extensions disabled**:
![untitled](https://user-images.githubusercontent.com/11807600/45482255-ce853000-b74d-11e8-8b5b-e2aaed2a02b5.gif)

I find this extremely annoying!

Maybe clear the auto-suggestions immediately when a dot (`.`) is typed?

**Comment by mjbvz** [comment]
Please test in [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled. Report if you still see this on #57072
