### ISSUE TITLE
Terminal: underscores render as spaces on Linux

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#58605]
At least on my Linux setup, the default monospace font (`'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'`) seems to render underscores `_` as spaces, as if there's nothing there. I have to use another font (`Fira Code`) to see them.

@Tyriar Let me know if there's some more details I can give you.

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/35901
