### ISSUE TITLE
Extension Host process never exits when having endless loop in extension

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#58606]
(The UI side of things is tracked in #58612)
* Create an extension with a while (true) or process.nextTick endless loop
* Close VS Code completely
* Observe, the extension host process lingers around

Here is an example extension:

* `package.json`:
```js
{
  "name": "bad",
  "publisher": "alex",
  "version": "0.0.0",
  "engines": { "vscode": "^1.22.0" },
  "activationEvents": [ "*" ],
  "main": "index.js"
}
```
* `index.js`:
```js
const vscode = require('vscode');
exports.activate = function() {
    console.log(`I am now entering while true loop`);
    while (true) {
        // do nothing, like a pro
    }
}
```

Observe that after exiting vs code the extension host process runs forever, until it must be **manually** killed.

**Comment by alexandrudima** [comment]
The extension host process will now quit at most within 7 seconds of the parent process quitting.

**Comment by joaomoreno** [comment]
@alexandrudima I love you. You just fixed half of my Windows installation issues.
