### ISSUE TITLE
Dependency Issue on Linux Install - Git

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#5860]
Related to #5757 

While testing this I attempted to do a fresh install on Ubuntu through the package GUI.  I was using the .deb package from our home page on code.vs.com.

I got errors on getting several Git packages that blocked install.

* Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/git/git-man_1.9.1-1ubuntu0.1_all.deb 404  Not Found [IP: 91.189.91.26 80]
* Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/git/git_1.9.1-1ubuntu0.1_amd64.deb 404  Not Found [IP: 91.189.91.26 80]

Looking at the raw registry those files are indeed not there:
http://security.ubuntu.com/ubuntu/pool/main/g/git/

I assume they could have been updated?

I also did this via the console:
parallels@ubuntu:~/Downloads$ sudo dpkg -i vscode-amd64.deb 
[sudo] password for parallels: 
Selecting previously unselected package visual-studio-code.
(Reading database ... 196182 files and directories currently installed.)
Preparing to unpack vscode-amd64.deb ...
Unpacking visual-studio-code (1.0.0-1460557031) ...
dpkg: dependency problems prevent configuration of visual-studio-code:
 visual-studio-code depends on git; however:
  Package git is not installed.

dpkg: error processing package visual-studio-code (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.10.1-0ubuntu2) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu1) ...
Processing triggers for bamfdaemon (0.5.1+14.04.20140409-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for mime-support (3.54ubuntu1) ...
Errors were encountered while processing:
 visual-studio-code
parallels@ubuntu:~/Downloads$

**Comment by seanmcbreen** [comment]
I could of course fix this by installing Git
sudo apt-get install git

Then I needed to each up some additional stuff
sudo apt-get -f install

Then I could install Code
sudo dpkg -i vscode-amd64.deb

But lots of ugly output...

**Comment by Tyriar** [comment]
This happened to @bgashler1, see https://github.com/Microsoft/vscode/issues/4922 for more context.

Apparently just a run of `sudo apt-get update` will fix it, or checking download software while installing Ubuntu should do it too. It's a trade off, remove the dependency and git doesn't work out of the box, keep it and this happens if the user hasn't fetched packages (which the software updater does periodically anyway).

**Comment by bgashler1** [comment]
@Tyriar Is there no way to run a hook on the first run of VS Code where it checks for things that aren't available (like Git) and then installs them very quickly (or to run a hook as part of the deb/rpm package installation). That way, we don't block installation, but also everything works on the first run as well?

**Comment by Tyriar** [comment]
Didn't we modify the documentation to say run update of you're  having issues? If not that solves the problem imo. We can also say run it before installing via command line too.

**Comment by Tyriar** [comment]
The `dpkg` error should be fixed when we offer our official repos. I added an item to the FAQ for the git error https://github.com/Microsoft/vscode-docs/commit/c1ff6fafa2fc00e7d866b5dff708c1fb40a775a3
