### ISSUE TITLE
Copy line down

### ISSUE THREAD

**Issue by Sparksss** [Microsoft/vscode#58602]
Issue Type: <b>Bug</b>

Hello! I got problem with copy html tag "textarea" with alt+shift+down(arrow)/

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:14:32.385Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (4.97GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
soy|ant|0.0.1
code-gnu-global|aus|0.2.2
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.6.0
tslint|eg2|1.0.39
vscode-npm-script|eg2|0.3.5
apacheconf-snippets|eim|1.1.9
vsc-material-theme|Equ|2.4.2
php-intellisense|fel|2.3.5
mysql-syntax|jak|1.3.1
svn-scm|joh|1.34.1
node-module-intellisense|lei|1.5.0
code-beautifier|mic|2.1.0
vscode-clang|mit|0.2.2
vscode-apache|mrm|1.1.1
vscode-language-pack-ru|MS-|1.27.2
cpptools|ms-|0.18.1
mysql-inline-decorator|odu|0.0.5
vscode-docker|Pet|0.2.0
html-css-class-completion|Zig|1.17.1

(4 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment]
@Sparksss Can you please give more steps? For me, copy line down works correctly. Have you tried to disable all extensions?

**Comment by Sparksss** [comment]
Hello! Then i copy line code with "alt+shift+down"  and the tag and its contents take up several lines(textarea)
example

<textarea name="" id="" cols="30" rows="10">
    orem Ipsum is simply dummy text of the printing and typesetting industry. 
    Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
     when an unknown printer took a galley of type and scrambled it to make a type specimen book.
</textarea>

copy only close tag </textarea>, but not the entire tag with its contents.

**Comment by alexandrudima** [comment]
@Sparksss This works correctly for me:

![kapture 2018-09-14 at 16 47 42](https://user-images.githubusercontent.com/5047891/45557454-ee941c80-b83d-11e8-8236-1c56a21aec39.gif)

**Comment by V-ed** [comment]
@alexandrudima : I think @Sparksss tries to use the Copy Line Down command from the last line duplicate the whole tag like so :

![vscode-copy-line-down](https://user-images.githubusercontent.com/16652915/45691881-73758380-bb27-11e8-8304-a31805cc8ca5.gif)

> and its contents take up several lines(textarea)

> **copy only close tag </textarea>**, but not the entire tag with its contents.

@Sparksss : If I'm not mistaken and you see the behavior my gif shows up, make sure to select every line you want to use with Copy Line Down (`alt+shift+down(arrow)`), Copy Line Down does not take the tag context for its behavior! ;)

**Comment by alexandrudima** [comment]
@Sparksss Can you please let us know what do you mean?
