### ISSUE TITLE
Typo in menu?

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#58603]
Issue Type: <b>Bug</b>

There's an ampersand in "check for updates"

<img width="328" alt="screen shot 2018-09-13 at 9 23 22 am" src="https://user-images.githubusercontent.com/835148/45491076-ca014d00-b736-11e8-8dfc-5684b8ceee4c.png">

VS Code version: Code - Insiders 1.28.0-insider (8330a695712c43f861ce5c47533d82637d3cb374, 2018-09-13T11:17:52.961Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 7, 5|
|Memory (System)|16.00GB (1.55GB free)|
|Process Argv|/Users/st016lo/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_38409375|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|1.2.9
Bookmarks|ale|9.0.3
project-manager|ale|8.0.0
bracket-pair-colorizer|Coe|1.0.59
vscode-eslint|dba|1.6.0
tslint|eg2|1.0.39
vscode-great-icons|emm|2.1.41
prettier-vscode|esb|1.6.1
path-autocomplete|ion|1.12.0
svg|joc|0.1.2
ecdc|mit|0.12.0
HTMLHint|mka|0.5.0
theme-monokai-pro-vscode|mon|1.1.8
vscode-scss|mrm|0.6.2
vscode-stylefmt|mrm|2.5.0
debugger-for-chrome|msj|4.10.1
angular2-inline|nat|0.0.17
incrementor|nms|0.1.0
vscode-versionlens|pfl|0.21.1
quicktype|qui|12.0.42
code-settings-sync|Sha|3.1.2
stylelint|shi|0.43.0
rewrap|stk|1.9.1
sort-lines|Tyr|1.7.0
vscode-terminal-here|Tyr|0.1.1
change-case|wma|1.0.0

(2 theme extensions excluded)

</details>

**Comment by joaosamouco** [comment]
Related with: https://github.com/Microsoft/vscode/pull/58412
