### ISSUE TITLE
Only top-left quadrant of window drawn after display/resolution change

### ISSUE THREAD

**Issue by fiendish** [Microsoft/vscode#58608]
Issue Type: <b>Bug</b>

Problem happens usually when I've just plugged in external monitors (dual side-by-side Dell U2718Q connected via USBC-DisplayPort cables) and woken my laptop (MacBook Pro 15-inch, 2017)  up from sleep. But I can also sometimes reproduce it when switching between maximum and scaled less than maximum screen resolutions in macOS (10.13.6) system preferences.

Problem manifests as only the top-left quadrant of the window being drawn and the rest being blank white (as shown here in images). As you can see, it also affects the bug reporting window.

<img width="1682" alt="screen shot 2018-09-13 at 10 24 46 am" src="https://user-images.githubusercontent.com/201996/45495299-020d8d80-b741-11e8-9011-81e1d9fe88dd.png">

<img width="706" alt="screen shot 2018-09-13 at 10 26 05 am" src="https://user-images.githubusercontent.com/201996/45495310-05087e00-b741-11e8-91bc-d00dbb2b89dd.png">

The problem fixes itself (the window fully paints) if I drag the window past the barrier between my displays and then back.

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:14:32.385Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (1.11GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
emojisense|bie|0.4.1
markdown-preview-github-styles|bie|0.1.3
vscode-svgviewer|css|1.4.6
vscode-markdownlint|Dav|0.20.0
jupyter|don|1.1.4
gitlens|eam|8.5.6
gc-excelviewer|Gra|2.1.26
nbpreviewer|jit|1.0.0
theme-dark-plus-contrast|k3a|0.1.101
rainbow-csv|mec|0.5.0
python|ms-|2018.8.0
rewrap|stk|1.9.1
vscode-gitmoji-snippets|thi|3.2.0
vscode-lua|tri|0.12.4
python-extended-snippets|tus|0.0.1
markdown-all-in-one|yzh|1.6.0
propertylist|zho|0.0.2

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/code-exploration_1.28.0-1536650436_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/VSCodeUserSetup-x64-1.28.0-exploration.exe)

**Comment by fiendish** [comment]
I am trying the exploration build now. So far so good, but if it happens again I'll report back.

**Comment by bpasero** [comment]
Ok please do

**Comment by fiendish** [comment]
I think I can pretty reliably confirm now that the exploration build does fix the problem.

**Comment by bpasero** [comment]
Closing this issue given that we plan to release VSCode stable early February with Electron 3.x. If you want to benefit from the fix already, consider to use our insiders version that already contains the fix: https://code.visualstudio.com/insiders/
