### ISSUE TITLE
VSCode lost after logging off because setup installed to temporary folder AppData\Local

### ISSUE THREAD

**Issue by alexhass** [Microsoft/vscode#58615]
Someone who has no idea about roaming profiles has set the default folder of current setup to AppData\Local. There are default rules from Microsoft that delete all folders of AppData\Local on user logoff. This means the software gets lost.

If you install into this folder you need to expect that all software is deleted. This can only done for data that can get lost. Otherwise software need to be installed to "Program Files" or "AppData\Roaming".

*Beginners*

**Comment by joaomoreno** [comment]
Aside from the possibility of installing VS Code on any folder you'd like, to avoid situations like this, we also distribute a system-wide setup which will let you install Code for all your users.

@alexhass This is your last warning. Be polite.

**Comment by alexhass** [comment]
I try to understand why software should break and data loss is an acceptable situation. Can you explain the reasons for intentionaly wrong setup design and why you refuse to fix serious bugs like this, please?

**Comment by alexhass** [comment]
Any chance you may answer the question - why software should break and data loss is an acceptable situation?

> note that we haven't had a single one so far

Only because I'm the first who is telling you about this bug, it does not mean the design issue does not exist. Aside of this the per user installed is quite new. So it is clear that not many people can have told you about this.
