### ISSUE TITLE
Running mouse over the Debug menu selections kills VSCode

### ISSUE THREAD

**Issue by kadickerss** [Microsoft/vscode#58614]
Issue Type: <b>Bug</b>

After opening VSCode, I click on debug, then I hover the mouse up and down the Debug menu options. VSCode dies.

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:18.328Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (11.29GB free)|
|Process Argv|C:\Users\kadicke1\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.6.0
tslint|eg2|1.0.39
debugger-for-chrome|msj|4.10.1

</details>

**Comment by isidorn** [comment]
Can you reproduce this with latest vscode insiders? https://code.visualstudio.com/insiders/
If yes can you please add a gif showing the problem. Thank you
Also what exact menu do you mean?

**Comment by kadickerss** [comment]
I installed the insider version. I cannot recreate this issue. 
I did notice that the Debug menu options for Step Over, Step Into, Step Out, and Continue are disabled in the insider version. In the version having the problem, these are active, even when not debugging.
Ok to close if you wish.

**Comment by isidorn** [comment]
Yeah let's close because the latest version seems to have the fix.
If you still see this once you get a stable update please let us know and we will reopen here
