### ISSUE TITLE
Scrollbar jumps to top of terminal window

### ISSUE THREAD

**Issue by ramblor** [Microsoft/vscode#58617]
Issue Type: <b>Bug</b>

When there is enough text in the terminal window to see the scrollbar if you switch to another tab, e.g. PROBLEMS, and then switch back the scrollbar will jump to the top of the terminal (though the terminal cursor itself remains in the same position). If you then try to scroll you will end up back at the top of the terminal window which is confusing and unexpected.

It looks like the same issue that was reported here: https://github.com/Microsoft/vscode/issues/45134

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:18.328Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700T CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (6.53GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.6.0
beautify|Hoo|1.4.3
vetur|oct|0.12.6

</details>

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/58532
