### ISSUE TITLE
autoClosingPairs in language-configuration.json doesn't allow multiple entries that use quotes.

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#58619]
I'm looking for a way to support autoClosingPair of:

`' ' `, `" "`, `@' '@`, and `@" "@`

However, when I add, for example:

`["@'","'@"]` to the `language-configuration.json` it doesn't work and still autocloses just ` ' ` so it looks like `@''`.

If I remove [this entry](https://github.com/Microsoft/vscode/blob/master/extensions/powershell/language-configuration.json#L16) from the autoClosingPairs, then `@'` closes properly to become `@''@`. But then `'` no longer completes.

Is there a way to do what I'm trying to do?

**Comment by rmunn** [comment]
It looks like this is related to #72177, which is a slightly different issue but probably caused by the same underlying bug.

**Comment by TylerLeonhardt** [comment]
Since this is an extensibility issue, I find it hard to believe that this will get the required likes to not be closed.

Please consider not doing that...

This can be viewed as a bug (or at least a silly limitation) as I can have auto closing pairs of `'` and auto closing pairs of `@'` but not together.

**Comment by TylerLeonhardt** [comment]
Pls no

**Comment by rmunn** [comment]
It's up to 25 votes now, so I think it's safe. But I agree with what you wrote in https://github.com/microsoft/vscode/issues/91714#issuecomment-595524174 about how the autoclose process selects against extension-related issues since a lot fewer people experience them.

**Comment by alexdima** [comment]
@TylerLeonhardt This works fine for me on latest VS Code. If I add:
```
{ "open": "@'", "close": "'@", "notIn": ["string", "comment"]},
```
to `extensions/powershell/language-configuration.json`, this is the behaviour I get:

![Kapture 2020-04-14 at 10 29 41](https://user-images.githubusercontent.com/5047891/79203166-ea294e80-7e3a-11ea-9e9c-030962959e19.gif)

I believe this got addressed with the changes for #79430 . Can you please confirm?

**Comment by TylerLeonhardt** [comment]
Awesome - let me give this a test.

Why was this closed? The change will need to be in this repo so that the maximum amount of people are affected (aka those that don't install the PowerShell extension but edit a PowerShell script).

**Comment by alexdima** [comment]
@TylerLeonhardt I closed the issue because I considered the initial issue is resolved. So now "autoClosingPairs in language-configuration.json **does** allow multiple entries that use quotes". 

Was this issue meant to be about PowerShell specifically? I thought that was given just as an example. Do you want that we add `@'` and `'@` as auto-closing pairs to the built-in PowerShell language configuration?

**Comment by TylerLeonhardt** [comment]
Thanks @alexdima, makes sense! Yes we should add those to the built-in PowerShell language configuration. I was about to send a PR your way 😄

**Comment by TylerLeonhardt** [comment]
@alexdima PR sent: https://github.com/microsoft/vscode/pull/95245
