### ISSUE TITLE
[mac] vscode doesn't integrate with find pasteboard

### ISSUE THREAD

**Issue by dwt** [Microsoft/vscode#58618]
Issue Type: <b>Bug</b>

On the mac there is a specialized shared keyboard for the search and replace dialogs across apps. This is called the find pasteboard. Here is a similar issue in atom: https://github.com/atom/atom/issues/4650 .

The problem is that all mac applications should show the same find text - but vscode does not.

How to reproduce:
* Select some text in the mac terminal application
* Hit command-e to put that text into the find clipboard
* verify by opening the find panel with command-f
* switch to vscode
* open the find panel with command-f
* see that the selected text is not shown there

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:14:32.385Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|/Users/dwt/Applications/Programmieren/Editoren/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
fish|Ted|0.0.4
html-css-class-completion|Zig|1.17.1
vscode-django|bat|0.17.0
gitignore|cod|0.5.0
compulim-vscode-closetag|Com|1.2.0
vscode-markdownlint|Dav|0.20.0
jshint|dba|0.10.20
vscode-eslint|dba|1.6.0
vscode-dash|dee|1.10.0
jupyter|don|1.1.4
python-extension-pack|don|1.4.0
vscode-todotxt|dun|1.0.4
gitlens|eam|8.5.6
vscode-html-css|ecm|0.2.0
ansible|haa|0.2.8
rest-client|hum|0.19.1
mysql-syntax|jak|1.3.1
fish-ide|lun|0.4.0
MagicPython|mag|1.0.12
vscode-scss|mrm|0.6.2
vscode-language-pack-de|MS-|1.27.2
python|ms-|2018.8.0
vsliveshare|ms-|0.3.666
vetur|oct|0.12.6
vscode-versionlens|pfl|0.21.1
vscode-icons|rob|7.26.0
sass-indented|rob|1.4.9
edit-with-shell|ryu|1.0.1
fish-vscode|sky|0.2.0
vscodeintellicode|Vis|1.0.3
jinja|who|0.0.8
livereload|zee|0.1.1

</details>

**Comment by rebornix** [comment]
This feature can be enabled by setting `editor.find.globalFindClipboard` to `true`.

**Comment by dwt** [comment]
Thanks, that helps. Can you tell me what the rationale is to have this feature off by default? There is (to my knowledge) almost no other OS X application that behaves this way.

**Comment by rebornix** [comment]
@dwt we have this turned on by default at the very beginning but later on we found that it will lead to a lot of troubles. We can have multiple editors open and each one of them can have a find widget, if we share the find query and everytime when you switch the editor, we will update the query in the find widget in that specific editor, which makes finds in multiple editors impossible to use.

**Comment by dwt** [comment]
@rebornix I don't quite get it - what you are describing as a problem is (to my knowledge) the standard behavior on all other OS X apps - and the whole reason why vscode behaves in a surprising way.

Are you saying that you guys found it surprising that when having multiple editors open and you selected some text for searching in one, then switching editors to another window it showed that same search query? Because in that case, it might be prudent to enable this setting by default on MacOS again, as that is exactly what a Mac user would expect VSCode to do.
