### ISSUE TITLE
case insesitive find all fail to find string with hyphen - characters

### ISSUE THREAD

**Issue by a7madgamal** [Microsoft/vscode#58613]
Issue Type: <b>Bug</b>

searching for `A1-MyOrders-Loading` with case insensitive settings off in whole project failed although  `a1-myOrders-loading` exists and can be found using `a1-myOrders-loading`

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:14:32.385Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.5.6
tslint|eg2|1.0.39
vsc-material-theme|Equ|2.4.2
prettier-vscode|esb|1.6.1
nasc-touchbar|fel|1.11.0
vscode-pull-request-github|Git|0.1.4
stylelint-disable-snippets|hed|1.0.1
vscode-duplicate|mrm|1.2.1
vscode-versionlens|pfl|0.21.1
material-icon-theme|PKi|3.6.0
vscode-icons|rob|7.26.0
code-settings-sync|Sha|3.1.2

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Do you have `search.smartCase` set?

**Comment by roblourens** [comment]
We did have an idea for that although I thought it might be overkill https://github.com/Microsoft/vscode/issues/42687
