### ISSUE TITLE
Can't terminate a debug session while it's initializing

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#58623]
Originally fixed as part of https://github.com/Microsoft/vscode/issues/47863, it doesn't work anymore.

- Start an attach config
- Try to kill it, I have to wait for the timeout to end

**Comment by isidorn** [comment]
You can terminate it using the shortcut or via the command palette, we just do not display the debug toolbar while the debug session is initialising for other cases https://github.com/Microsoft/vscode/issues/55026

I am open to change this but it obviously makes sense in some cases, while in others it does not.
@weinand thoughts welcome

**Comment by roblourens** [comment]
Oh, I didn't notice that the keyboard shortcut still works. That's good enough for me, but showing the toolbar might help other people.

**Comment by isidorn** [comment]
@roblourens I do not want to add more states, that is asking for trouble :)
For now closing this as will not fix, you have the shortcut as a workaround.
If more users complain I can be convinced to show the toolbar in the initializing phase
