### ISSUE TITLE
Git integration crashes once you upload a big file

### ISSUE THREAD

**Issue by Fenwil** [Microsoft/vscode#5862]
- VSCode Version: 1.0.0
- OS Version: 10.11.4

Steps to Reproduce:

1. Commit and push a big file like a psd (around 40 megabytes).
2. Git will push it but it will stay like constantly uploading the file when already has finished and will not refresh new changes to files to make others commits or push.
3. You will have to reset VSC in order to make the Git Integration works again.

**Comment by sprinkle131313** [comment]
Can't reproduce with current version of VSCode, tried pushing a ~100 MB random file with and without git-lfs support. Was able to do both.

**Comment by joaomoreno** [comment]
Thanks for letting us know!
