### ISSUE TITLE
restarting VSCode after update overwrites system path

### ISSUE THREAD

**Issue by diminutivesloop** [Microsoft/vscode#58629]
Issue Type: <b>Bug</b>

Whenever I restart VSCode after an update my system path is overwritten leaving only my user path defined. As a result I have to restart my computer to regain normal functionality.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4930MX CPU @ 3.00GHz (8 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.94GB (17.27GB free)|
|Process Argv|C:\Users\npalmer\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
project-manager|ale|8.0.0
ng-template|Ang|0.1.10
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.6.0
find-related|eam|0.7.0
gitlens|eam|8.5.6
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.39
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.6.1
todo-tree|Gru|0.0.86
path-autocomplete|ion|1.12.0
java-properties|ith|0.0.2
search-node-modules|jas|1.3.0
vscode-duplicate|mrm|1.2.1
vsliveshare|ms-|0.3.666
debugger-for-chrome|msj|4.10.1
tsimporter|pmn|1.2.14
java|red|0.30.0
sass-indented|rob|1.4.9
sort-lines|Tyr|1.7.0
highlight-matching-tag|vin|0.4.4
vscode-java-debug|vsc|0.12.2
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.8.0
vscode-maven|vsc|0.10.0
vim|vsc|0.16.4

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
> my system path is overwritten leaving only my user path defined

What do you mean by this?

**Comment by diminutivesloop** [comment]
In Windows you can modify environment variables by going to **Control Panel** > **System** > **Advanced system Settings** > **Environment Variables**. In this dialog the variables are grouped under "User variables" and "System variables". When Windows starts up it concatenates the `path` environment variable defined under "User variables" with the one under "System variables" to construct my full `path` environment variable. For whatever reason VSCode is deleting the component of my `path` variable defined under "System variables" leaving only the "User variables" component.

**Comment by joaomoreno** [comment]
Got it. During the initial Setup, it asked you if you'd like to include Code in the PATH, to which you very likely replied no. So, with every update, he's taking that decision and probably he's erasing it over and over again. If you reinstall Code and reply Yes to that question, then it will stop removing it. Let me know how it goes.

**Comment by diminutivesloop** [comment]
I reinstalled VSCode, and while I can't yet verify what the behavior is when updating, I did notice that the same path clobbering occurs when I run the installer. This happens whether or not I select the option to add VSCode to my path.

**Comment by diminutivesloop** [comment]
@joaomoreno What do you mean by "user setup"?

**Comment by joaomoreno** [comment]
Check here: https://code.visualstudio.com/#alt-downloads

We provide 2 alternative setup packages for Windows. One which installs Code for all users, another which does it for just your user. You can check which one you have by going in `Help > About`.

**Comment by diminutivesloop** [comment]
Ok then yes I am using the user install.

**Comment by joaomoreno** [comment]
Strange... What is the actual change made to the system variables? Can you check?

**Comment by diminutivesloop** [comment]
Well now that I'm trying to reproduce this defect I can't anymore. I guess I'll wait till the next update and if the issue is still present I can share more details and if not then we can just close the issue.
