### ISSUE TITLE
Breadcrumbs doesn't work with functions written in R

### ISSUE THREAD

**Issue by balmungsama** [Microsoft/vscode#58628]
- VSCode Version: 1.27.1
- OS Version: Windows 10, build 1803

Steps to Reproduce:

1. Open/create an R script containing user-defined functions
2. Check the breadcrumb for the currently active R script

In other languages, such as Matlab, clicking on the currently opened script in the breadcrumbs bar gives the user an overview of functions defined in the script. No such aid is provided in R. Is this a bug or simply an unsupported language?

Does this issue occur when all extensions are disabled?: Yes/No

Yes

**Comment by mjbvz** [comment]
We only ship with basic support for R, such as syntax highlighting. For more advanced language features like breadcrumbs and intellisense, you need to install one of the R language extensions
