### ISSUE TITLE
Paste and Highlight

### ISSUE THREAD

**Issue by calvinypark** [Microsoft/vscode#58621]
If copied text is pasted using ctrl+shift+v, I would like it to be pasted and highlighted at the same time.  I would like to see this feature with multiple cursors mode as well.

Keep up the good work!

I just found a somewhat duplicate request ticket - #47814

My feature request extends to the multiple cursors mode though.  I will leave up to you guys to handle this issue. :)

**Comment by alexandrudima** [comment]
Let's track in #47814
