### ISSUE TITLE
Getting invalid type errors randomly in project

### ISSUE THREAD

**Issue by ChuckJonas** [Microsoft/vscode#58626]
- VSCode Version: 1.27.1 (1.27.1)
- OS Version:10.12.6

Steps to Reproduce:
I can't quite seem to figure what triggers it, but have having my project open for a while I start to get type errors that are seemly incorrect.  

<img width="457" alt="index_d_ts_ _apex-pmd" src="https://user-images.githubusercontent.com/5217568/45508371-e2cb2c00-b751-11e8-85c9-db690c54c000.png">

<img width="555" alt="lib_es2015_d_ts_ _apex-pmd" src="https://user-images.githubusercontent.com/5217568/45508404-faa2b000-b751-11e8-8b06-5f856bead9b8.png">

If I edit the file, or run `restart ts server` they go away for a couple minutes, then will come back

My ts-config

```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es6",
        "outDir": "out",
        "lib": [
            "es6"
        ],
        "sourceMap": true,
        "rootDir": "."
    },
    "exclude": [
        "node_modules",
        ".vscode-test"
    ]
}
```
dev deps
```json
    "devDependencies": {
        "@types/node": "^10.9.4",
        "mocha": "^5.2.0",
        "typescript": "^3.0.3",
        "vscode": "^1.0.0"
    }
```

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by ChuckJonas** [comment]
I've been using insiders build for a couple hours with no extensions and haven't come across it

**Comment by mjbvz** [comment]
Closing since we haven't heard back on this issue
