### ISSUE TITLE
git push for private repo

### ISSUE THREAD

**Issue by vortechron** [Microsoft/vscode#58631]
sometime, pushing private repo will cause authentication failure, vs code should have an ability to ask developer for their username and password. not just simple throw HttpRequestException

**Comment by joaomoreno** [comment]
Can you share a screenshot of the error?

**Comment by vortechron** [comment]
![capture](https://user-images.githubusercontent.com/22893960/45541557-079ecc80-b842-11e8-8a2f-66bcfb41278f.PNG)

**Comment by joaomoreno** [comment]
What happens if you use the Command Prompt to push?

**Comment by vortechron** [comment]
@joaomoreno it ask me to put my username and password.. using push button on vs code sometime ask for my username and password but mostly it throw error that i mention earlier

**Comment by joaomoreno** [comment]
Can you show me how it asks you, is it in the terminal or is it a popup box?
