### ISSUE TITLE
Can't install extensions on Ubuntu LTS 14.04

### ISSUE THREAD

**Issue by Cyber1000** [Microsoft/vscode#5863]
- VSCode Version:1.0.0
- OS Version: Ubuntu 14.04 (via deb-package) on a virtualbox (via vagrant if that matters)

Steps to Reproduce:

1. Open fresh installed VSCode within Ubuntu 14.04/virtualbox/vagrant
2. ext install tslint (or any other, as it doesn't matter)
3. Press the download button
4. Nothing happens (No popup, no install, no extension-dir in my home-folder, no errormessage)

No problem on the same setup with VSCode 0.10.xx (which was not really installed via deb, but only by extracted zip-File of VSCode, I think deb wasn't available at this time). Where may I take a look at, is there a log-File or something more verbose?

Thanks!

**Comment by bpasero** [comment]
@Cyber1000 anything in the console (help > toggle developer tools)?

**Comment by joaomoreno** [comment]
Do you have a proxy?

**Comment by Cyber1000** [comment]
In developer tools I'm getting this some seconds after pressing enter on "ext install {whatever}":

![bildschirmfoto von 2016-04-28 22-07-31](https://cloud.githubusercontent.com/assets/1142765/14899733/bba29b42-0d8d-11e6-8f5b-ed251b1c7ae8.png)

**Comment by Cyber1000** [comment]
Virtualbox is NATted, if that matters (some weeks ago with 0.10.xx it worked with the same settings), no proxy.

I'll try to switch to bridged network.

**Comment by Cyber1000** [comment]
No difference, internet works within virtualbox, but installing extensions in VSCode always throws an error.

Reinstall also didn't work.

Can I download marketplace-extensions manually (to test if downloading is the problem).
What more can I do?

Thanks!

**Comment by joaomoreno** [comment]
Seems to not be network related.

Does the user under which Code runs have permissions to write to the following paths?

- `$TMPDIR`
- `~/.vscode`
- `~/.vscode/extensions`

Is there something inside `~/.vscode/extensions`?

**Comment by Cyber1000** [comment]
Oh damn (... sorry)
~/.vscode/extensions had a wrong user, cause I'm creating that on provisioning of my vagrant-virtualbox.

Sorry for the inconvinience, a proper error-message would be fine though.
Thanks for your fast help :+1:

**Comment by joaomoreno** [comment]
I'll keep it open, to take care of displaying the error message. 👍

**Comment by vilinski** [comment]
similar behaviour:
Ubuntu 16.04 in VirtualBox with NAT
proxy over cntlm on windows host
http_proxy and https_proxy env vars on ubuntu are set, and other linux cli tools are working
installed latest april deb package
Ctrl+Shift+P ext install -> endless activity indicator
developer tools console (but no new entries after above command):
connect ETIMEDOUT 191.232.139.254:443
connect ETIMEDOUT 40.114.241.141:80

**Comment by joaomoreno** [comment]
Verification:

- Change the owner of extensions folder to be root, eg: `sudo chown root ~/.vscode-oss-dev/extensions`.
- Try to install an extension
- You should see an error message in the workbench, something containing `EPERM`.

**Comment by jrieken** [comment]
@joaomoreno I don't see an error messages with those steps

**Comment by joaomoreno** [comment]
See anything in the dev tools? Sure you have latest?

**Comment by joaomoreno** [comment]
Ok found a problem in installing extensions, you might be seeing it instead: #6947

**Comment by jrieken** [comment]
yeah, I saw something like that. Tho I could install backspace-plusplus and after changing the _owner_ I could uninstall it.

**Comment by joaomoreno** [comment]
@jrieken Just pushed fixes... Can you try verifying again?

**Comment by hikidd** [comment]
Similar issue, vscode can't work in vagrant/ubuntu16.04
VSCode Version:1.4.0
OS Version: Ubuntu 16.04 on a virtualbox

![unnamed_20160901_105618_632](https://cloud.githubusercontent.com/assets/17465708/18302314/cb8ae6ca-7509-11e6-9066-59e0f8d3d1fb.png)
