### ISSUE TITLE
[BUG] Graphic glitches.

### ISSUE THREAD

**Issue by Mlocik97-issues** [Microsoft/vscode#58632]
Issue Type: <b>Bug</b>

After new update I have a lot of Graphic glitches in vscode:

JavaScript:
![1](https://user-images.githubusercontent.com/31345346/45512073-fb156800-b79e-11e8-8598-c03e881a90be.png)

JSON:
![2](https://user-images.githubusercontent.com/31345346/45512173-492a6b80-b79f-11e8-99c7-33ce612ad3a3.png)
![3](https://user-images.githubusercontent.com/31345346/45512553-52680800-b7a0-11e8-88c7-6ee49ed532c2.png) cursor is on line 18

or I had (this only one time) scrollbar out from box "Open Editors" in Explorer.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (10.10GB free)|
|Process Argv|C:\Users\Mloci\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by alexandrudima** [comment]
The first screenshot appears to show links decorations and the second one bracket match decorations. @Mlocik97-issues what steps do you do when this happens? Are there any errors in the Developer Tools Console?

**Comment by Mlocik97-issues** [comment]
no errors in console... it happen when you open some files (I had opened about 20-30 files). After click on that "decoration" it disappear, but if I open few files again, these "decorations" will appear often again, but it's randomly on random positions. One time it appear in one file or on line 20, next time in another file or on line 6...

**Comment by Mlocik97-issues** [comment]
if I remove <style type="text/css" class="contributedColorTheme">...</style> from DOM, glitches dissapear.

**Comment by alexandrudima** [comment]
I could not reproduce, but I did a brief code review of the bracket matching code. I found one case where the bracket matching code could still end up using cached results (namely when the cursor position between two files is the same and two files are switched and they happen to have the same version id -- like 1 -- meaning they are both freshly opened).

I don't know about the links. Rather than me doing another code review in there (where the logic is quite more complicated), can you please keep a look out and check if you find any relevant steps.

Thanks!

**Comment by alexandrudima** [comment]
I have managed to find reproducible steps. To the verifier:

* create a file `file1.json`
```json
{
    "hello": "world"
}
```

* create a file `file2.json`
```json
{
    "hello": "world",
"SOME TEXT"
}
```

* have the files opened in two tabs in the same editor group
* on both files place the cursor at (1;1)
* leave `file1.json` opened
* reload window (such that both files are clean at version 1)

![kapture 2018-09-17 at 11 36 24](https://user-images.githubusercontent.com/5047891/45615818-f0dcbd80-ba6d-11e8-9445-c32cb01c8421.gif)

c77cc9898f389bd50d309d0162390fa2fd2e69d1 fixes this issue.
