### ISSUE TITLE
Tab reorder hangs vscode x64 unless GPU disabled on Ubuntu

### ISSUE THREAD

**Issue by anchepiece** [Microsoft/vscode#58639]
Issue Type: <b>Bug</b>

When using the mouse to reorder the editor tabs vscode becomes unresponsive.
![vscode_1 27 1x64_ubuntu_tab_reorder](https://user-images.githubusercontent.com/279146/45515555-7dd5fd00-b776-11e8-800e-2623c505f6ad.png)
I was unable to capture a screencast of the issue, likely that its on the gpu by then.

Workaround: running with `./code --disable-gpu` fixes the issue
Additionally, when enabling/disabling `"window.titleBarStyle": "custom"` after the settings invoked restart the issue does not occur.
 
The last known good version: 1.25.1
Affected versions: 1.26.1 through insiders

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:47.222Z)
OS version: Linux x64 4.15.0-34-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz (4 x 2976)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
</details>

Steps to Reproduce:

1. Launch
2. Attempt to re-order editor tabs
3. Visual artifact left on screen and window unresponsive

Does this issue occur when all extensions are disabled?: Yes

Are there any tools available to investigate this gpu issue on linux more thoroughly?

**Comment by bpasero** [comment]
I think I am also hitting this but could not figure out what's the cause. If someone wants to chime in, help is welcome.

**Comment by anchepiece** [comment]
@bpasero Are you able to reproduce the problem going away when switching titleBarStyle then restarting?

**Comment by bpasero** [comment]
@anchepiece I have to try next week when I am back at that machine, are you saying this only reproduces for you with the custom title style enabled?

**Comment by anchepiece** [comment]
No, the issue is present in both modes, however if after launching, making a settings change that requires a restart, save, get prompt to restart, restart, the issue goes away until next launch. See if that is the case for that machine as well, changing window.titleBarStyle is an example setting, but changing "update.channel" or "telemetry.enableCrashReporter" also works. 

Once you close the editor and launch again the issue reappears.

I also noticed that the issue is present when launched from a terminal, but not from a built in launcher like `xfce4-appfinder` so something about how code is launched is causing this issue.

Running `nohup code` seems to fix the issue as well. Here is the `nohup.out` contents:

$ cat nohup.out | 
------------ | 
[main 9:26:50 AM] update#setState idle
xdg-settings: default-url-scheme-handler not implemented for xfce
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
[27577:0914/092652.660927:ERROR:buffer_manager.cc(453)] [.DisplayCompositor-0x3b0dfec3f000]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[27577:0914/092653.705992:ERROR:buffer_manager.cc(453)] [.DisplayCompositor-0x3b0dfec40800]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[0914/092655.043475:ERROR:archive.cc(170)] Failed to parse header size from /home/dev/code/Microsoft/vscode/extensions/css-language-features/server/test/pathCompletionFixtures/src/data/foo.asar

**Comment by anchepiece** [comment]
It looks like this issue falls on electron as seen here:
https://github.com/electron/electron/issues/12820
Closing with upstream reference.

Anyone tracking this issue can follow this earlier related issue here: https://github.com/Microsoft/vscode/issues/57766 

Thanks for the assistance @bpasero
