### ISSUE TITLE
executeWorkspaceSymbolProvider not returning symbols executeDocumentSymbolProvider does

### ISSUE THREAD

**Issue by TomasHubelbauer** [Microsoft/vscode#58637]
VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:18.328Z)
OS version: Windows_NT x64 10.0.17134

In my `activate`, I register a symbol provider followed by a link provider:

```ts
languages.registerDocumentSymbolProvider(markDownDocumentSelector, new MarkDownLinkDocumentSymbolProvider());
languages.registerDocumentLinkProvider(markDownDocumentSelector, new MarkDownLinkDocumentLinkProvider());
```

The symbol provider generates some dummy symbols and then link provider picks some of them out and turns them into links like this:

```ts
export class MarkDownLinkDocumentLinkProvider implements DocumentLinkProvider {
    public async provideDocumentLinks(document: TextDocument, _token: CancellationToken) {
        const symbols = (await commands.executeCommand('vscode.executeWorkspaceSymbolProvider', '')) as SymbolInformation[];
        const links = symbols.filter(symbol => … && symbol.kind === SymbolKind.String);
        return links.map(link => new DocumentLink(link.location.range, Uri.parse(…)));
    }
}
```

When I run my extension logging both `provideDocumentSymbols` and `provideDocumentLinks` and wait to see what shows up in the debug console, I get these logs:

```
provideDocumentSymbols 14 # My symbol provider is invoked
provideDocumentLinks 2 0 # My link provider is invoked but it doesn't see my symbols, just VS Code's
provideDocumentSymbols 14 # My symbol provider is invoked again, not sure why
```

This is without any user interaction, just a load with a MarkDown file open. When I do close and reopen the file, I see the symbol provider generating my symbols again, but the link provider doesn't see them. It does get invoked, but it gets the same old VS Code symbols excluding mine.

When I press <kbd>Ctrl+Shift+O</kbd>, the dummy symbols show up in the UI.

When I replace `executeWorkspaceSymbolProvider` with `executeDocumentSymbolProvider`, I get my symbols just fine.

I think I should get my symbols either way as the file I am operating on is opened as a part of a directory which should count as sort of a virtual workspace, right?

**Comment by KamasamaK** [comment]
A [`WorkspaceSymbolProvider`](https://code.visualstudio.com/docs/extensionAPI/vscode-api#WorkspaceSymbolProvider) is distinct from a [`DocumentSymbolProvider`](https://code.visualstudio.com/docs/extensionAPI/vscode-api#DocumentSymbolProvider). Also see [guideline](https://code.visualstudio.com/docs/extensionAPI/language-support#_show-all-symbol-definitions-within-a-document).

**Comment by TomasHubelbauer** [comment]
I read all your links but to me it sounds like workspace symbol provider should invoke symbol providers across all workspace documents, so any result I get from individual document's symbol provider I should also get in the workspace symbol provider, isn't that correct?

**Comment by TomasHubelbauer** [comment]
Thank you!
