### ISSUE TITLE
Support Sublime Text plugins

### ISSUE THREAD

**Issue by digeff** [Microsoft/vscode#5864]
I'd be really cool if you added some kind of adapter, so Sublime Text plugins could be used in VS Code as-is.

**Comment by digeff** [comment]
Support for atom packages would also be good

**Comment by mjbvz** [comment]
Closing as out of scope currently. Please let us know if you run into any limitations that prevent porting a sublime plugin to vscode

**Comment by auchenberg** [comment]
For settings please see, https://github.com/Microsoft/vscode-sublime-importer and for keybindings we have https://github.com/Microsoft/vscode-sublime-keybindings
