### ISSUE TITLE
Re:Update  Installation issue

### ISSUE THREAD

**Issue by theklr** [Microsoft/vscode#58645]
Issue Type: <b>Bug</b>

Referencing https://github.com/Microsoft/vscode/issues/58090
1.Removed previous vs code and cleared logs,cache 
2. Installed vscode from site
3. Attempted updating application as suggested
Application closes , I have to manually re-open, with the application suggesting to update.

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:14:32.385Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (4.74GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (78)</summary>

Extension|Author (truncated)|Version
---|---|---
output-colorizer|IBM|0.1.2
ejs-language-support|Qas|0.0.1
sharecode|Rol|0.4.1
indenticator|Sir|0.6.0
ejs-snippets|Tao|0.1.0
Bookmarks|ale|9.0.3
jenkins-status|ale|0.6.1
project-manager|ale|8.0.0
react-pure-to-class-vscode|ang|1.1.6
cform|aws|0.0.15
vscode-database|baj|1.5.2
react-food-truck|bur|1.0.2
simple-react-snippets|bur|1.2.2
vscode-exports-autocomplete|cap|0.5.4
npm-intellisense|chr|1.3.0
gitignore|cod|0.5.0
bracket-pair-colorizer|Coe|1.0.59
language-postcss|cpy|1.0.5
open-in-sketch|dav|2.1.0
vscode-eslint|dba|1.6.0
git-extension-pack|don|0.1.3
githistory|don|0.4.2
gitlens|eam|8.5.6
vscode-npm-script|eg2|0.3.5
terraform-autocomplete|erd|0.0.8
prettier-vscode|esb|1.6.1
vscode-todo-plus|fab|4.4.4
shell-format|fox|1.1.3
css2react|got|0.0.6
gc-excelviewer|Gra|2.1.26
path-autocomplete|ion|1.12.0
react-jest-vscode-snippets|jal|0.0.3
jenkins-declarative-support|jmM|0.1.0
svg|joc|0.1.2
sublime-babel-vscode|jos|0.2.10
ejs-eval|kev|1.0.1
contextualduplicate|laf|0.2.0
vscode-smart-column-indenter|lmc|0.0.13
lambda-snippets|log|0.2.0
aws-cli-configure|mar|0.3.0
terraform|mau|1.3.4
postcss-language|mhm|2.1.0
dotenv|mik|1.0.1
vscode-autoprefixer|mrm|2.1.2
vscode-postcss-sorting|mrm|3.0.1
vscode-stylefmt|mrm|2.5.0
vscode-azureterraform|ms-|0.2.2
azure-account|ms-|0.4.3
vsliveshare|ms-|0.3.666
debugger-for-chrome|msj|4.10.1
live-server-preview|neg|0.1.2
vscode-jest|Ort|2.9.0
vscode-docker|Pet|0.2.0
vscode-versionlens|pfl|0.21.1
vscode-gitignore-generator|pio|1.0.1
cf-templates|pra|0.1.1
seti-icons|qin|0.1.3
diff|raf|0.0.1
vscode-yaml|red|0.0.16
postcss|ric|2.0.0
vscode-sort-json|ric|1.13.0
chai-spec-generator|rin|0.4.0
vscode-icons|rob|7.26.0
terraform-doc-snippets|run|0.3.0
partial-diff|ryu|1.4.0
jenkinsfile-support|sec|0.1.0
code-settings-sync|Sha|3.1.2
stylelint|shi|0.43.0
css-auto-prefix|spo|0.1.7
guides|spy|0.9.2
quokka-vscode|Wal|1.0.148
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.9.0
webpack-progress|wk-|0.0.8
JavaScriptSnippets|xab|1.7.0
local-history|xyz|1.7.0
markdown-all-in-one|yzh|1.6.0
vscode-open-in-github|ziy|1.3.5

(5 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Can you maybe disable background updates and try again? `"update.enableWindowsBackgroundUpdates": false`

**Comment by theklr** [comment]
Still same issue.

**Comment by joaomoreno** [comment]
OK so, with that setting set to `false`, what happens when you press Restart to Update?

**Comment by theklr** [comment]
It closes for updating, but I still have to manually open vs code, for it to still requesting an update.

**Comment by joaomoreno** [comment]
> It closes for updating

It closes, and nothing happens... stays closed?

**Comment by theklr** [comment]
Correct

**Comment by joaomoreno** [comment]
Oh I failed to see you are on macOS. Make sure Code is not in quarantine: https://github.com/Microsoft/vscode/issues/7426#issuecomment-277737150
