### ISSUE TITLE
opening containing folder (a function of evince) is occupied by vscode

### ISSUE THREAD

**Issue by Infinemen** [Microsoft/vscode#58651]
Issue Type: <b>Bug</b>

1. When I view pdf in evince, I want to check where the location of the file. And evince supports to find the containing folder by "open containing folder". But when vscode is installed in the system, vscode will be opened not the file manager any more.

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:47.222Z)
OS version: Linux x64 4.18.1-arch1-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3279)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.58GB (7.69GB free)|
|Process Argv|/opt/visual-studio-code/code /home/men/Zotero/storage/VSM2D37G/Tskhakaya_2017_One-dimensional plasma sheath model in front of the divertor plates.pdf|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
fortran-ls|han|0.2.0
latex-workshop|Jam|5.9.0
linter-gfortran|krv|1.3.1
python|ms-|2018.8.0
cpptools|ms-|0.18.1
material-icon-theme|PKi|3.6.0
markdown-all-in-one|yzh|1.6.0

</details>

**Comment by Tyriar** [comment]
Try tweaking your xdg-mime settings. See https://github.com/Microsoft/vscode/issues/28423 for more context.
