### ISSUE TITLE
Find history 

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/vscode#5865]
- VSCode Version: 1.0.0
- OS Version: 10.11

I am missing the find history functionality from Sublime Text. In ST you can use arrow keys to go back to previous queries.

**Comment by anseki** [comment]
This feature helps us because I often want to use "Add Selection" (`Ctrl+D`) while continuing the "Find".
When I am using "Find" `foo` to check whether all `foo`s were written correctly, I found incorrect `bar`. I selected `bar` and pressed `Ctrl+D`, to fix the `bar`. Then, the "Find" text box was changed to `bar` unintentionally.
I have to type `foo` again into the "Find" text box to continue the checking.

**Comment by dilijev** [comment]
This has been bothering me as well. I've been thinking I'd like to try hacking on something and this doesn't seem so bad. I would have time over the weekend of the 9th. Mind if I pick this up then if it hasn't already been done @alexandrudima @bpasero?

**Comment by alexandrudima** [comment]
PR welcome :+1:

**Comment by dilijev** [comment]
(Obviously haven't had time; my next free weekend is 8/20 so no need to wait if someone else wants to dive in.)

**Comment by ducdigital** [comment]
I'd love to have this feature <3

**Comment by dilijev** [comment]
I haven't had time to work on this and most likely will not have time any time soon. Don't wait for me if someone else wants to jump in on a patch.

**Comment by alexandrudima** [comment]
I think @sandy081 already implemented this

**Comment by dfroze** [comment]
Yes it is already implemented.
Just add the following lines in keybinding.json:
```
    { "key": "alt+left",        "command": "workbench.action.navigateBack" },
    { "key": "alt+right",       "command": "workbench.action.navigateForward" },
```

**Comment by sandy081** [comment]
Yes this feature was implemented in September - https://github.com/Microsoft/vscode/issues/5508

`alt+left` and `alt+right` are the default shortcuts to navigate history.

**Comment by dilijev** [comment]
Thanks! I'm seeing that it's actual Alt+Up and Alt+Down to to previous and next search phrases respectively. Alt+Left and Alt+Right don't seem to do anything in that view.

**Comment by sandy081** [comment]
@dilijev Yes, I am mistaken. Its Alt+Up and Alt+Down.

**Comment by devonparsons** [comment]
Some of the information in these comments were a bit confusing/misleading. Here are the actual commands and contexts required, and I chose to simply use 'up' and 'down' keys when the find widget is focused:

 ```  
{ "key": "up",   "command": "find.history.showPrevious", "when": "editorFocus && findInputFocussed && findWidgetVisible"},
 { "key": "down", "command": "find.history.showNext",     "when": "editorFocus && findInputFocussed && findWidgetVisible"}
```
