### ISSUE TITLE
html word wrap not work

### ISSUE THREAD

**Issue by moontaicn** [Microsoft/vscode#58654]
Issue Type: <b>Bug</b>

    Even set 'Editor: Word Wrap' to 'wordWrapColumn' or 'bounded', and set 'Editor: Word Wrap Column' to '120' or other number value, the html code has already passed 120 words in one line, but the editor's wordWrap also can't work. 
    This's not conveniently for user to see and write the html code in the editor. 
    I hope the editor's developer can fixed this bug very soon.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.95GB (0.90GB free)|
|Process Argv|D:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
aessoft-class-autocomplete|AES|0.1.0
project-manager|ale|8.0.0
vscode-angular2-files|ale|1.6.2
ng-template|Ang|0.1.10
typings-installer|ben|0.2.0
git-easy|bib|1.9.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.6.0
jquerysnippets|don|0.0.1
vscode-generate-getter-setter|DSK|0.5.0
vscode-html-css|ecm|0.2.0
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.39
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vue-snippets|hol|0.1.9
beautify|Hoo|1.4.3
autofilename|Jer|0.1.3
docthis|joe|0.7.1
git-indicators|lam|2.1.1
node-module-intellisense|lei|1.5.0
vscode-emacs-friendly|lfs|0.8.2
vscode-language-pack-zh-hans|MS-|1.27.2
js-atom-grammar|ms-|0.1.14
debugger-for-chrome|msj|4.10.1
vetur|oct|0.12.6
ionic2-snippets|oud|1.0.0
vscode-css-peek|pra|2.1.0
LiveServer|rit|5.1.1
vscode-icons|rob|7.26.0
vscode-uppercase|rui|1.0.1
vue-vscode-snippets|sdr|1.3.0
code-settings-sync|Sha|3.1.2
autoimport|ste|1.5.3
ionic2|Tha|3.0.2
quokka-vscode|Wal|1.0.148
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.7.0

(2 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment]
@moontaicn Can you please explain more clearly what steps you are doing and what is happening vs what you expect?

When I am configuring the editor with:
```
"editor.wordWrap": "wordWrapColumn",
"editor.wordWrapColumn": 80,
"editor.rulers": [ 80 ],
```

I am seeing everything as expected:

![image](https://user-images.githubusercontent.com/5047891/45543622-3e122280-b815-11e8-8c64-1d803b1995ed.png)
