### ISSUE TITLE
Support dynamic tasks and launch configurations.

### ISSUE THREAD

**Issue by liudonghua123** [Microsoft/vscode#58655]
I use vscode to write a lot of C/C++ examples, I build it by using make, and I also write a general purpose makefile which supports compile the source code via `make <filename_exclude_extension>`

Now my tasks.json contains something duplicate configurations like this.

![image](https://user-images.githubusercontent.com/2276718/45525060-09e23600-b804-11e8-8c42-c58f5a5fb449.png)

And my launch.json contains something duplicate configurations like this.

![image](https://user-images.githubusercontent.com/2276718/45525153-680f1900-b804-11e8-8e16-78f0ade88d4b.png)

So it would be nice and excellent if support dynamic placeholder in these configurations like this.

![image](https://user-images.githubusercontent.com/2276718/45525213-a6a4d380-b804-11e8-879d-5e8983248e0b.png)

![image](https://user-images.githubusercontent.com/2276718/45525254-c3d9a200-b804-11e8-9ab5-792808a7c484.png)

**Comment by dbaeumer** [comment]
The ${filename} is supported as an arg in the `tasks.json` and to my knowledge in the lauch.json (@isidorn). 

You could name the task 'Build current file' and from a compiling persepcetive everything should work for you. Do you see problems with this.

**Comment by liudonghua123** [comment]
@dbaeumer Thanks, I made it works now, here is my configurations.

tasks.json

![image](https://user-images.githubusercontent.com/2276718/45534093-86890a80-b82c-11e8-80e6-6294cf32c297.png)

launch.json

![image](https://user-images.githubusercontent.com/2276718/45534136-b7693f80-b82c-11e8-8bc6-2d85f5a10a0d.png)
