### ISSUE TITLE
Selection issue with custom titlebar

### ISSUE THREAD

**Issue by Kelvinoo7** [Microsoft/vscode#58664]
Issue Type: <b>Bug</b>

1) Set window title style to custom.
2) Open any file.
3) Start selecting text from middle and extend selection to any menu on custom title bar and leave mouse button.
4) Now without clicking anywhere move mouse on the text area.

Now your selection changes only with mouse move without any click.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vue-format|feb|0.1.2
auto-rename-tag|for|0.0.15
beautify|Hoo|1.4.3
sublime-babel-vscode|jos|0.2.10
vscode-icon-theme|jtl|1.6.2
debugger-for-chrome|msj|4.10.1
vetur|oct|0.12.6
material-icon-theme|PKi|3.6.0
code-spell-checker|str|1.6.10

(1 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
duplicate #58446
