### ISSUE TITLE
Show git status for files in explorer

### ISSUE THREAD

**Issue by rakkarage** [Microsoft/vscode#5866]
what if i have a folder of 100 files all changed except one or two
i can see the changed one in git view but how to find the unchanged ones?
if the modified files were a different color in explorer then it would be easy to see (like Atom)
thanks

**Comment by CristyTarantino** [comment]
+1

**Comment by eosrei** [comment]
Duplicate of #178 @bpasero

**Comment by rdewolff** [comment]
Any plugin doing that?
