### ISSUE TITLE
Extension Host is unresponsive/Extension Host is now responsive

### ISSUE THREAD

**Issue by lyndonjohn** [Microsoft/vscode#58663]
Issue Type: <b>Bug</b>

"Extension Host is unresponsive" dialog occasionally pops up.

![screen shot 2018-09-14 at 2 52 22 pm](https://user-images.githubusercontent.com/29518229/45534573-314df880-b82e-11e8-9688-3c411edf4c7a.png)

I don't know how to reproduce it, it just occasionally pops up. I tried disabling all my extensions, restart VS Code but it popping out.

Sometimes this dialog will show up:

![screen shot 2018-09-14 at 2 56 50 pm](https://user-images.githubusercontent.com/29518229/45535164-24ca9f80-b830-11e8-8833-86a6aff81dba.png)

VS Code version: Code - Insiders 1.28.0-insider (a542a0afb5ff12a878dcf4b6a914f10d1318cb2e, 2018-09-14T05:12:35.372Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|13, 11, 8|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron --inspect-extensions=4355|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.0.3
disableligatures|Coe|0.0.8
gitlens|eam|8.5.6
vsc-material-theme|Equ|2.4.2
php-debug|fel|1.12.5
php-intellisense|fel|2.3.5
vscode-pull-request-github|Git|0.1.5
beautify|Hoo|1.4.3
path-autocomplete|ion|1.12.0
vscode-insertdatestring|jsy|2.2.3
vscode-phpfmt|kok|1.0.30
es6-css-minify|olb|2.0.3
selectline-statusbar|tom|0.0.2
html-css-class-completion|Zig|1.17.1

(4 theme extensions excluded)

</details>

**Comment by lyndonjohn** [comment]
#58661 same issue

**Comment by spencerdavis2000** [comment]
I think this has to do with something involving "Git" extensions like Git Lens or Git History.

**Comment by MAQ7** [comment]
I am facing the same issue as well. Do you know the root cause? Any solution please?

**Comment by chrisbull** [comment]
Same

**Comment by Leandermen** [comment]
Same

**Comment by Baziliq** [comment]
same, is there a way to turn of this notification ... it jumps every 2-3 seconds
it started showing after latest update and since then the editor is unusable

**Comment by mintzopg** [comment]
got this also only in my windows laptop, linux works fine!

**Comment by MathiasBoisgardDev** [comment]
Same problem
Ubuntu 16.10 with Visual Studio's last update (1.28.0)

**Comment by deluksic** [comment]
Same problem, windows 10.

**Comment by pmsoltani** [comment]
Same thing on macOS Mojave
