### ISSUE TITLE
VS Code does not read modified PATH variable

### ISSUE THREAD

**Issue by realivanjx** [Microsoft/vscode#58665]
I just added a path variable to gradle. I restarted the cmd and vscode but cmd in vs code cant read the gradle path. Here is the output in vscode's cmd:

`'gradle' is not recognized as an internal or external command`

But in windows cmd:

```
Welcome to Gradle 4.10.1!
etc...
```

I just found out that to get the vscode's cmd to work, i need to restart the windows 10 and it is really uncomfortable especially when im opening a lot of files and programs.

Thanks.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/47816
