### ISSUE TITLE
Can't search in panel output when webview is open

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#58668]
1. Open a webview editor, eg Release Notes
2. Open the Output view in the panel, focus it
3. Press <kbd>Ctrl F</kbd>

The webview find widget comes up. There's no way to open the Output find widget.

**Comment by mjbvz** [comment]
@bpasero I believe this comes from b9d6a2cbacc383e1551b428b94750047e2d0e276. Any ideas on how the context key be tweaked to avoid this case?
