### ISSUE TITLE
`onDidOpenTextDocument` fires when adding diagnostics collection

### ISSUE THREAD

**Issue by ChuckJonas** [Microsoft/vscode#58666]
- VSCode Version: Version 1.28.0-insider (1.28.0-insider)
- OS Version: 10.12.6

I'm writing an extension and encountered some unexpected behavior. It seems that the `workspace.onDidOpenTextDocument` event fires when a `Diagnostic` is added for a URI.  

**Is this expected behavior?**  And if so, is there an even for when a document is ADDED to an editor (tab) for the first time?  `window.onDidChangeActiveTextEditor` will kinda work for what I need, but results in a lot of extra processing (I only really need to run the command when the file is first opened).

Steps to Reproduce:
Create an extension with the following code:

```
vscode.workspace.onDidOpenTextDocument((document) => {
   console.log('fired!');
});

const collection = vscode.languages.createDiagnosticCollection('testing');
collection.set(....);
```

Does this issue occur when all extensions are disabled?: Yes/No
N/A? No other extensions installed

**Comment by jrieken** [comment]
>  It seems that the workspace.onDidOpenTextDocument event fires when a Diagnostic is added for a URI.

We shouldn't be triggering this but you might have an extension that does that. I need more information to know for sure. Anyways, always be prepared for open events to happen.
