### ISSUE TITLE
Failed to install VS Code update

### ISSUE THREAD

**Issue by cognociente** [Microsoft/vscode#58673]
[vscode-inno-updater-1536911377.log](https://github.com/Microsoft/vscode/files/2382460/vscode-inno-updater-1536911377.log)
 

- VSCode Version:1.26.1
- OS Version: Windows 10 latest update (not insider build)

Version: 1.26.1
Commit: 493869ee8e8a846b0855873886fc79d480d342de
Date: 2018-08-16T18:38:57.434Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Steps to Reproduce:
It keeps trying to update a few times per day and fails. Instruction on failure is to create an issue and insert the log file (as attached)

Does this issue occur when all extensions are disabled?: YES!!

**Comment by arpadbarta** [comment]
Same here:
Version: 1.27.1 (user setup)
Commit: 5944e81f3c46a3938a82c701f96d7a59b074cfdc
Date: 2018-09-06T09:21:18.328Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Have been having this issue since the user setup, previously everything was ok.
