### ISSUE TITLE
Extension Host is unresponsive when alt-tabbing

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#58672]
Issue Type: <b>Bug</b>

* Launch VS Code and alt-tab
* After 10s a popup shows
![image](https://user-images.githubusercontent.com/5047891/45536801-c935ed00-b802-11e8-9dcf-e4c833368eeb.png)

* When returning to VS Code to popup says the Extension Host is now responsive

![image](https://user-images.githubusercontent.com/5047891/45536773-b7ece080-b802-11e8-8d96-6467270dfcff.png)

VS Code version: Code - Insiders 1.28.0-insider (a542a0afb5ff12a878dcf4b6a914f10d1318cb2e, 2018-09-14T05:12:35.372Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz (4 x 3300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.89GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron --logExtensionHostCommunication|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by alexandrudima** [comment]
Here is an extension that reproduces the behaviour:

* `package.json`:
```js
{
    "name": "nopromise",
    "publisher": "alex",
    "version": "0.0.0",
    "engines": {
        "vscode": "^1.28.0"
    },
    "activationEvents": [
        "*"
    ],
    "main": "index.js",
    "contributes": {
        "commands": [
            {
                "command": "nopromise",
                "title": "Command that never ends - promise"
            }
        ]
    }
}
```

* `index.js`:
```js
const vscode = require('vscode');

exports.activate = function() {
    vscode.commands.registerCommand('nopromise', function() {
        return new Promise((resolve, reject) => {

        });
    })
}
```

**Comment by weinand** [comment]
I'm seeing this problem without doing anything.
After upgrading Insiders the notification shows up in every window.

**Comment by alexandrudima** [comment]
I think we have some promises in our core set of extensions that are never resolved/rejected.

**Comment by eamodio** [comment]
@alexandrudima I am still seeing this -- FAR less often since the fix, but it still keeps popping up.

```
Version: 1.28.0-insider (user setup)
Commit: 29e6dce4352db76d8956035990b8630580226588
Date: 2018-09-14T08:23:30.210Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

**Comment by alexandrudima** [comment]
Having thought about it more, I can increase the threshold. i.e. show a popup if we're waiting for more than 1 request, perhaps it just so happens that the last request is taking a very long time or is one of those never resolved promises...

**Comment by PowerMogli** [comment]
> @alexandrudima I am still seeing this -- FAR less often since the fix, but it still keeps popping up.
> 
> ```
> Version: 1.28.0-insider (user setup)
> Commit: 29e6dce4352db76d8956035990b8630580226588
> Date: 2018-09-14T08:23:30.210Z
> Electron: 2.0.9
> Chrome: 61.0.3163.100
> Node.js: 8.9.3
> V8: 6.1.534.41
> Architecture: x64
> ```

1+

```
Version: 1.28.0-insider (user setup)
Commit: cd9d71a31f731baf17330a84448c3efdeabc873f
Date: 2018-09-17T05:20:06.620Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

**Comment by alexandrudima** [comment]
@PowerMogli @eamodio I have just pushed a kind of "blind" fix... 

But it would be great if I could reproduce what you're seeing... perhaps it has to do with the list of extensions you have installed, etc. Is the CPU usage going up when you see this? (i.e. perhaps the extension host really is unresponsive?) Do you see this on startup? Please don't hesitate to open separate issues via the issue reporter so I can see your list of installed extensions, etc.

**Comment by bpasero** [comment]
@alexandrudima I was also seeing this when running "out of sources" and Alt-Tabbing away. Do we have a theory what causes this, maybe some things get throttled when running in the background? We do set [`backgroundThrottling: false`](https://github.com/Microsoft/vscode/blob/712cd009f8ee594cc448a259dc8cdfec85659470/src/vs/code/electron-main/window.ts#L147) for each window though.

**Comment by alexandrudima** [comment]
Yes, we have discovered one more flaw in the logic -- tracked in #58794.

The unreseponsive message might pop up if an external process takes a long time to compute something, like the TS server. I'm working on addressing that, will possibly trigger a rebuild.

**Comment by brandonkal** [comment]
This bug reappeared after the 1.28.0 update.
431ef9da3cf88a7e164f9d33bf62695e07c6c2a9
