### ISSUE TITLE
Editor: Replace in selection feature

### ISSUE THREAD

**Issue by demigor** [Microsoft/vscode#58676]
There is a tool button Search in Selection in Search/Replace dialog.
However if one what to replace text in selection, that seems to be impossible.

Please add button Replace in Selection, or just make Search in Selection button as toggle one.

**Comment by roblourens** [comment]
I don't quite understand, "Search in selection" seems to work with replace.

Is this covered by https://github.com/Microsoft/vscode/issues/17563 or https://github.com/Microsoft/vscode/issues/22254?

**Comment by demigor** [comment]
Search works, but not Replace

**Comment by demigor** [comment]
Detailed steps to reproduce:
1) Ensure Auto Find In Selection option is deactivated. If not, deactivate and restart VS Code.
2) Open any text file.
3) Select some multiline text.
4) Press Ctrl-H for Search/Replace Dialog.
5) Enter search and replace text
6) Question? What button do I press to replace all search occurrences in selection?
7) Pressing Replace All, replaces all occurrences in text, not in selection.

**Comment by rebornix** [comment]
Before Step 4, we can toggle "Find In Selection" by clicking on the toggle button left to the close button

<img width="435" alt="image" src="https://user-images.githubusercontent.com/876920/45640481-a5271580-ba67-11e8-9579-9f8dd50a24bd.png">

And then the selection will be preserved for both search and replace.
