### ISSUE TITLE
Git folder shows .VC.db* files as modified

### ISSUE THREAD

**Issue by sumonto** [Microsoft/vscode#5868]
- VSCode Version: 1.0
- OS Version: OS X Elcapitan

Steps to Reproduce:

1. Open a git repository
2. .vscode, and *.VC.* files are shown as modified,

These files should be auto ignored

**Comment by bpasero** [comment]
Please configure your .gitignore.

**Comment by sumonto** [comment]
I have configured
$ git config --global core.excludesfile ~/.gitignore_global
and added them to .gitignore_global it does not work

**Comment by sumonto** [comment]
Also configuring .gitignore in a custom case like this is not the correct solution.
Since these are VS created files VS should do the needful.
