### ISSUE TITLE
Update delete settings

### ISSUE THREAD

**Issue by Mordef** [Microsoft/vscode#58682]
After Updating today to 1.27.2, the folder "data" was deleted and all Settings/extensions where gone.

**Comment by Mordef** [comment]
Other system, same error. VS Code was still running. I quit it and the update start autttomaticly, i was to slow to save the data-folder, now its gone, all settings and extensions gone.

Is there a setting to say dont update on end?

**Comment by joaomoreno** [comment]
Please do not use Portable mode with the Windows Setup. It is not supported. https://code.visualstudio.com/docs/editor/portable

You can only use Portable mode on the ZIP distribution.

/duplicate #57990
