### ISSUE TITLE
Debugger attached. Waiting for the debugger to disconnect...

### ISSUE THREAD

**Issue by sagg155** [Microsoft/vscode#58686]
- VSCode Version:  1.27.2
- OS Version: Windows 10 Pro 64bit OS,x64-based processor

Steps to Reproduce:

1. Start Node Debugger
2. Error
   Debugger attached.
   Waiting for the debugger to disconnect...

Does this issue occur when all extensions are disabled?: Yes

I have tried everything as follows  but nothing works->
1. restarted vs code
2. restarted my machine
3. uninstall node,npm,vs code 

please suggest some solution for this bug.Basically i'm debugging typescript file.

**Comment by sagg155** [comment]
No,that above given issues not solves my problem.

**Comment by isidorn** [comment]
Can you reproduce this with the latest vscode insiders https://code.visualstudio.com/insiders/
If yes please provide a minimal reproducable repository so we can investigate this further

**Comment by decoder318** [comment]
VS Code debugger worked fine for a while, now it starts having this issue. I restarted my machine, reinstalled VS Code and the problem's still there.

**Comment by zimmermanw84** [comment]
This is also a problem for me. It worked yesterday, and today it no longer works.
```
~/.nvm/versions/node/v8.11.0/bin/node -r ts-node/register --inspect-brk=37579 .vscode/launch.json 
Debugger listening on ws://127.0.0.1:37579/8636a323-3cda-4699-81a9-f62854befe42
Debugger attached.
Waiting for the debugger to disconnect...
```
launch.json
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch current file w/ ts-node",
      "protocol": "inspector",
      "args": ["${relativeFile}"],
      "cwd": "${workspaceRoot}",
      "runtimeArgs": ["-r", "ts-node/register"],
      "internalConsoleOptions": "openOnSessionStart"
    }
  ]
}```

System Info
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
NodeJs: v8.11.0

Not really sure how to repro. One possible path.
I left my computer on all night in sleep mode with the debugger running. In the morning it worked until I stopped the debugger and tried to start it again.
