### ISSUE TITLE
exact meaning of command.commitEmpty, please

### ISSUE THREAD

**Issue by aldonetti** [Microsoft/vscode#58681]
during translation phase it's not clear what the exact meaning of this string is and therefore how it should be translated - can you please clarify?
in file https://github.com/Microsoft/vscode/blob/master/extensions/git/package.json
string "title": "%command.commitEmpty%" --> "Commit Empty" 
is it an action to perform an Empty Commit? or else?
thanks!

**Comment by joaomoreno** [comment]
It is an action to perform an Empty Commit? 👍
