### ISSUE TITLE
VS code activation

### ISSUE THREAD

**Issue by SpillChek2** [Microsoft/vscode#58692]
- Extension Name: debug-auto-launch
- Extension Version: 1.0.0
- OS Version: Windows_NT x64 10.0.17692
- VSCode version: 1.28.0-insider

 We have written the needed data into your clipboard. Please paste:
```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 40,
		"activateCallTime": 0,
		"activateResolvedTime": 0,
		"activationEvent": "*"
	}
}
```

**Comment by alexandrudima** [comment]
@SpillChek2 What is the issue and what are the steps to reproduce?
