### ISSUE TITLE
Folder path relative workspace placeholder in tasks

### ISSUE THREAD

**Issue by elch10** [microsoft/vscode#58690]
I have makefile, and I need to pass to `make` the path relative to workspace. I need to do something like that:
```json
    "version": "2.0.0",
    "tasks": [
        {
            "label": "echo",
            "type": "shell",
            "command": "make ${pathRelativelyWorkspace}",
        }
    ]
```
But vscode has not placeholder with similar behavior. It only has `${workspaceFolderBasename}`, but it gives all path with `/home/...`. I need the only the path relative to workspace where file is in. 
E.g. if `file` has path `/home/abc/workspace/fol/der/file` then I want to get only a `/fol/der`
P.S. there is also be good if I will can get only the basename of path. 
E.g. if we take the same example, I want get only `/der`

**Comment by alexr00** [comment]
Solved by https://github.com/microsoft/vscode/issues/77616!
