### ISSUE TITLE
Support to open multiple folders in one window

### ISSUE THREAD

**Issue by sumonto** [Microsoft/vscode#5869]
- VSCode Version:1.0
- OS Version: OS X

Steps to Reproduce:

1. Open a git folder in explorer
2. Open a 2nd one, the first one is closed.

VS Code Explorer should support multiple Git folders.

**Comment by bpasero** [comment]
Closing as duplicate of #2686

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/396
