### ISSUE TITLE
Start up for Git

### ISSUE THREAD

**Issue by SpillChek2** [Microsoft/vscode#58696]
- Extension Name: git
- Extension Version: 1.0.0
- OS Version: Windows_NT x64 10.0.17692
- VSCode version: 1.28.0-insider

 We have written the needed data into your clipboard. Please paste:
```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 1901,
		"activateCallTime": 36,
		"activateResolvedTime": 945118,
		"activationEvent": "*"
	}
}
```

**Comment by joaomoreno** [comment]
What is the issue?
