### ISSUE TITLE
Cannot set shortcut to ctrl+alt+down in linux

### ISSUE THREAD

**Issue by ddeath** [Microsoft/vscode#58704]
Issue Type: <b>Bug</b>

When I want to set for example shortcut for copyLineDown to ctrl+alt+down it is not possible as the vscode is not registering downArrow when I press it and all it shows is ctrl+alt

However if I want to set it to ctrl+down  then it is working ok..

VS Code version: Code - Insiders 1.27.0-insider (7b9afc4196bda60b0facdf62cfc02815509b23d6, 2018-09-03T09:15:27.927Z)
OS version: Linux x64 4.15.0-33-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 934)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.21GB (1.29GB free)|
|Process Argv|/usr/share/code-insiders/code-insiders --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-mjml|att|1.4.0
mjml-syntax|dig|0.0.1
cpptools|ms-|0.18.1
vsliveshare|ms-|0.3.666
gitconfig|sid|2.0.0

</details>

**Comment by joaomoreno** [comment]
Ctrl+alt+down is a common desktop navigation shortcut in Linux, at least in the Gnome desktop. You need to disable it there first, such that the desktop lets Code handle that keyboard shortcut.
