### ISSUE TITLE
Git integration does not recognize untracked files ??!!

### ISSUE THREAD

**Issue by lorenjerickson** [Microsoft/vscode#58706]
Issue Type: <b>Bug</b>

This is pretty hard to believe, especially since it's been a problem for such a long, long time.  I'm hoping it's just a Code or Git setting that is messed up. 

Right now my SCM (Git) view in Code shows no changes, but when I run `git status` on the local repo I have five untracked files.  Why on earth would the SCM view not show these files?  This has bitten me more than once, relying on the SCM view in code to get stuff checked in, pushing it to origin and watching the build break because half the story is still sitting untracked on my disk.  

Why isn't there a way to show untracked files?

VS Code version: Code - Insiders 1.28.0-insider (29e6dce4352db76d8956035990b8630580226588, 2018-09-14T08:23:30.210Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (9.03GB free)|
|Process Argv|C:\Users\loren\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.3.2
tslint|eg2|1.0.39
vscode-guid|hea|1.4.0
code-beautifier|mic|2.1.0
debugger-for-chrome|msj|4.10.1

</details>

**Comment by joaomoreno** [comment]
If you modify a file, does it show up?
