### ISSUE TITLE
[folding] editor.showFoldingControls: never

### ISSUE THREAD

**Issue by jabacchetta** [microsoft/vscode#58708]
`editor.showFoldingControls` only allows for "always" and "mouseover". It would be nice if we could disable it entirely.

The only way to remove the controls (and save space in the editor) is to set `"editor.folding": false`. However, this will also disable the keyboard shortcuts for folding.

Preferably, we could disable the UI controls (saving space in the editor by decreasing the gutter width), while still being able to use the keyboard shortcuts.

UI controls are not necessary for simple folding (fold imports, fold a method, etc.).

**Comment by aeschli** [comment]
duplicate of #40384

I still haven't heard that request from other users.

**Comment by jabacchetta** [comment]
Went ahead and opened this back up after getting more time to work in VS Code and find out what my use cases were.

Specifically, I prefer to have imports folded. And occasionally I find myself wanting to use folding commands (e.g. "Fold All"). Neither can be done with a shortcut if hiding the UI controls.

Not sure how many others care about this feature. Some might not realize that they can save editor space by turning off the UI controls. And for what it's worth, this is possible in WebStorm.

**Comment by garytyler** [comment]
I always do folding with key commands. It would be nice to hide the the little toggles.

**Comment by wxjzeke** [comment]
+1

**Comment by dsynkd** [comment]
I think this is one of the best solutions to decreasing the gutter width, an [issue that has over 100 upvotes](https://github.com/microsoft/vscode/issues/30795) at the moment.

**Comment by aeschli** [comment]
Happy to take a PR!

**Comment by jzyrobert** [comment]
Had a go at this PR since I never use the decorators, have a look.
