### ISSUE TITLE
Consider extending SymbolInformation with metadata field

### ISSUE THREAD

**Issue by TomasHubelbauer** [Microsoft/vscode#58714]
Hello, I have implemented a `DocumentSymbolProvider` to pick out MarkDown links from MarkDown files, so now I can get symbols whose name is e.g. `[VS Code](https://code.visualstudio.com/)`, however, if I wanted to access either the text or the path of the link, I'd have to further parse the symbol text.

Alternatively I could either replace this symbol or accompany this symbol with two other symbols, one for the text and one for the path (and potentially bind the text and path symbols to the link one using `containerName`).

If I did that, I could centralize the link parsing in the symbol provider, but would make it harder for the consumer to identify pairs of symbols that together represent one link. It's not impossible, the symbols could be matched using the `containerName`, but it's not the most natural code to write, identifying these pairs.

I thought I could just create a new class extending `SymbolInformation`, but when obtaining the symbols using `commands.execute('vscode.executeDocumentSymbolProvider')`, the instances are transformed (presumably because they are serialized and deserialized, same thing that would happen over LSP).

Hence I'd like to propose either a new field was added for metadata or any unknown fields were preserved upon transfer so that something like `textSymbol.associatedPathSymbolLocation` (being a `Location`) could be used.

**Comment by jrieken** [comment]
Not really sure what you are trying to achieve? Do you want to make links appear in the outline views? (tree, quick outline, breadcrumbs)

**Comment by TomasHubelbauer** [comment]
Sorry, I went about this wrong and since have found I way what I wanted to achieve.
