### ISSUE TITLE
(New Settings editor UI) display the default setting value next to the 'Reset Setting' text, inside the cogwheel menus

### ISSUE THREAD

**Issue by darkred** [Microsoft/vscode#58712]
Using VSCode 1.27.2 in win10.

I really enjoy the New Settings editor UI.
There's only one thing I miss from the previous way (i.e. the two panel direct settings.json editing), 
is to be able to view the default settings values, before resetting a setting to it.

**My suggestion is to display the default setting value next to the text 'Reset setting' cogwheel menus.**

Example:

Default settings content of settings.json :
```
"editor.multiCursorModifier": "alt"
```

My suggestion:

e.g. in the menu that appears when you click the cogwheel icon that appears when you hover the mouse on the "Editor: Multi Cursor Modifier" entry,
change the `Reset Setting` text into `Reset Setting ("alt")`

![2018-09-14_210912](https://user-images.githubusercontent.com/723651/45567545-bd7a1300-b862-11e8-8232-dc4f8c4e55dc.jpg)

**Comment by cleidigh** [comment]
@roblourens 
Related, another thing I have thought of is a default indicator/icon within the enum list.

**Comment by roblourens** [comment]
@darkred It would make sense for some settings, but for lots of them, the value won't fit or won't look good in a menu.

@cleidigh I do like that suggestion!

**Comment by darkred** [comment]
Yeah, I prefer @cleidigh suggestion too!

@roblourens I see you immediately closed the issue.
Wouldn't it be better if it remained open, renamed according to cleidign's suggestion ?

**Comment by roblourens** [comment]
I opened a new issue for it https://github.com/Microsoft/vscode/issues/58724

I prefer opening new issues rather than pivoting issues to slightly different topics.

**Comment by darkred** [comment]
Alright, thank you for your time!
