### ISSUE TITLE
ESLint lightbulb not showing up in certain circumstances

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#5871]
- VSCode Version: 10.12-alpha
- OS Version: Mac

Regarding test item #5654 
I'm not getting a lightbulb on one of my custom rules.

Also while this is less important, in my opinion it's not very intuitive for me to have to put my cursor at the beginning of an error.  Could you enable it whenever the cursor is over any part of an error (Maybe that's not possible)?

**Problems:**
## 1
With this setting,
```
"no-use-before-define": [
    "error"
]
```

I get an error, as expected, on trying to increment `brad` before I've defined it as a variable.  However, I get no lightbulb when the cursor is positioned at `brad` like I would get with some other error.

```
brad ++;
var brad = 1;
```

## 2
With no trailing commas rule, I also can't get a light bulb.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/vscode-eslint#75
