### ISSUE TITLE
Filename with `:` in name shows incorrect symbol in explorer

### ISSUE THREAD

**Issue by Klauswk** [Microsoft/vscode#58715]
- VSCode Version: 1.26.1
- OS Version: Windows 10

Steps to Reproduce:

1. Simple run `touch :fileName` in `git-bash`
2. It shows the incorrect name in the explorer

![incorrect_name](https://user-images.githubusercontent.com/17770979/45569379-bc7ebc80-b835-11e8-9184-88847813894a.png)

**Comment by isidorn** [comment]
: is an invalid character on windows. Even the windows explorer does not properly display this
That is why we also show an error when you try to create this file in the explroer directly.
I have no plans to fix this -> closing
