### ISSUE TITLE
tree expand subfolder doesn't work anymore

### ISSUE THREAD

**Issue by rkdmen** [Microsoft/vscode#58717]
- VSCode Version: Update 1.27.2
- OS Version: mac 10.13.6

Steps to Reproduce:

1. Option + click folder with subfolder doesn't expand subfolders.

*Collapsing all folder works fine with Option + click, when it is expanded.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/9456
