### ISSUE TITLE
Add editorUnnecessary.foreground

### ISSUE THREAD

**Issue by jabacchetta** [Microsoft/vscode#58710]
`editorUnnecessary.foreground` was replaced in favor of `editorUnnecessaryCode.opacity`.

Unfortunately, opacity control by itself does not give unused variables enough prominence, making them easy to miss. This is especially a problem with certain color themes.

**Comment by mjbvz** [comment]
This was previously discussed on #53519. I'm not in favor of it because overriding the foreground color makes vscode's syntax highlighting look broken. If opacity does not work, try setting `editorUnnecessaryCode.border` to add an underline to unused variables instead
