### ISSUE TITLE
Documentation confusion with ExtensionContext.logPath

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/vscode#58729]
I was working on adding the new `logPath` functionality to an extension of mine, but the documentation was very confusing, and I'm not able to use it for my purpose. Bases on the current wording, it seemed like each extension would get a unique directory, and this directory would be the same across VS Code invocations. However, through testing, I am getting a unique directory per time VS Code is opened. Can this be cleared up in the documentation? It makes a major difference in the usefulness of the API.

**Comment by jrieken** [comment]
> It makes a major difference in the usefulness of the API.

Can you explain why that is? Are reading files from there?

**Comment by ThadHouse** [comment]
I wanted my users to be able to send logs if something went wrong, however it's highly likely they will have restarted vs code by the time they ask for help and I ask for the logs. At that point, it is not possible programmatically to find the failing log, as there is no way to get old directories from the extension.  

I think a much better API would be to give us a folder unique to the extension that does not change between restarts, and then an incrememnting counter that is guaranteed to change every restart. That way we could create our own unique subfolders per extension execution, but we would have a full folder we could tell our users to zip and send us.

**Comment by jrieken** [comment]
Understood. Adding @mjbvz how implemented `getLogDirectory`. Is that something you have considered way back when this has been proposed? Is there an command like "Show Log> Foo-extension" like there is "Show Logs > Main"?

**Comment by mjbvz** [comment]
Closing this since the API has been stable for a few years now and we have not seen other reports of confusion.

If you feel the documentation could be improved, please submit a PR
