### ISSUE TITLE
Bug: Unable to use PowerShell for terminal

### ISSUE THREAD

**Issue by jakub-astrahit** [Microsoft/vscode#58725]
- VSCode Version: 1.27.2
- OS Version: Windows 7 Enterprise

<img width="364" alt="screen shot 2018-09-15 at 00 30 12" src="https://user-images.githubusercontent.com/19378338/45577904-ad702c80-b87e-11e8-9cc0-85b91baff0d8.png">

Steps to Reproduce:
1. Use following user settings (with a valid path to PowerShell):
```
"terminal.explorerKind": "external",
"terminal.external.windowsExec": "C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\powershell.exe"
```

2. Open terminal. It opens regular windows command line instead of PowerShell. No error provided.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
What terminal are you trying to open? Can you provide a screenshot?

**Comment by jakub-astrahit** [comment]
@Tyriar Here you go.

![cmd](https://user-images.githubusercontent.com/19378338/45630372-dbc95400-ba98-11e8-961b-b29ac6cd2b99.PNG)

**Comment by Tyriar** [comment]
That's the integrated terminal, you're configuring the external terminal. This this:

```
"terminal.integrated.shell.windows": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
```

**Comment by jakub-astrahit** [comment]
Oh sorry for confusion. Thanks!
