### ISSUE TITLE
Error Stack Trace Overflows Debug Console

### ISSUE THREAD

**Issue by dyllandry** [Microsoft/vscode#58721]
![Image of issue.](https://i.imgur.com/9mw9tXJ.png)
I am logging an error using Node's `console.error()`, however the stack trace is overflowing the debug console. Is there a setting, or better approach to reading errors, that I can utilize to view the entire stack trace? 
Using VSCode version 1.27.2 on macOS 10.13.6 (17G65)

**Comment by isidorn** [comment]
Yes this is the current limitation fo the debug console.
As a workaround you can     
`"workbench.tree.horizontalScrolling": true`
Which will add the horizontal scroll to all the trees in vscode - including the debug console. Not that this makes the tree less performant.
Closing as I have no plans of tackling this
