### ISSUE TITLE
EACCES while renaming file owned by root. rename is successful

### ISSUE THREAD

**Issue by KuromiAK** [Microsoft/vscode#58727]
- VSCode Version: 1.27.2
- OS Version: Ubuntu 18.04.1 LTS

Steps to Reproduce:

1. Create a file as root. `sudo touch foo`
2. Rename the file using VSCode Explorer.

Actual Behaviour:

- File is successfully renamed
- An EACCES error notification is shown.
![EACCES error notification](https://user-images.githubusercontent.com/12407671/45580500-91e92f80-b846-11e8-96c7-b7c2335f78e3.png)

Expected Behaviour:

- No EACCESS error should be shown.

Does this issue occur when all extensions are disabled?: Yes

It seems the error is triggered when vscode [opens the file to update timestamp](https://github.com/Microsoft/vscode/blob/878a6e0cbfbe1ce9f2aeb71fbe1e04a26c362e80/src/vs/base/node/extfs.ts#L321) after the rename is complete. I do not expect an error to be raised in this case, as I got the impression that the file was not renamed when I first encountered this error notification.

**Comment by bpasero** [comment]
VSCode cannot rename a file system resource that was created with a different user that has higher priviliges.
