### ISSUE TITLE
Settings UI - mark default enum value

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#58724]
https://github.com/Microsoft/vscode/issues/58712#issuecomment-421489838

In a dropdown control, the default value should be indicated somehow like with a `*`.

**Comment by cleidigh** [comment]
Any similar UI examples, something better than just *  ?

**Comment by roblourens** [comment]
I can't think of an analogy but we can do better than *.

Since it's the custom dropdown, we can style something however we want. Maybe a better comparison is the detail text on some file labels like in search

![image](https://user-images.githubusercontent.com/323878/45578336-b983cc00-b835-11e8-89cb-7a2cf4073c2e.png)

We could have `(default)` in smaller grayed out text

**Comment by roblourens** [comment]
I wouldn't know what either of those mean.

If we want to save space in the actual row, we could add "(default)" to the description. But I think it should be indicated in the row somehow.

**Comment by cleidigh** [comment]
I guess that begs the question, regardless of what symbol we use, do we need to reference it somewhere as the default symbol?  I agree we should not put it in the description, for one thing until you moved the selection to the default you would not know where it is.

There are a ton of HTML symbols, that's where I got the two above, double arrows, a fancier Asterix?

**Comment by roblourens** [comment]
No, I don't really think that any other symbol will be more clear. I think we should either be explicit and use the word "default" or just use an asterisk.

**Comment by cleidigh** [comment]
I guess I would vote for the Asterix, 'default' takes up a lot of real estate.  Maybe someone comes up with something brilliant ;-)

**Comment by roblourens** [comment]
Do you think it would take too much space? Most values seem short and "default" is not too long, but translated forms might be longer.

We could use `*`, then in the description, append `* default` as a sort of explanation.

**Comment by cleidigh** [comment]
I have to add some layout for Left/Right justification either way.  I'll post the two examples.

**Comment by roblourens** [comment]
I guess I am thinking of the case when the user is looking at a non-configured enum setting, and it says "default", and that is obvious since the setting is not configured. But it could be useful if they are running through all the enum values without expanding the control.

**Comment by cleidigh** [comment]
after playing with this, I am making the new option interface include a primary option entry and a right justified 'extra' field.  This way a client can include a variety of indicators.  In this scenario we will pass in
the extras in the same way as the extended descriptions.

For settings, Asterix or '(default)' ?

**Comment by roblourens** [comment]
What happens when they run into each other?

**Comment by cleidigh** [comment]
💥 🔥🔥🔥

I'm thinking the extra will collapse and favor the primary

**Comment by roblourens** [comment]
No worries, thanks

**Comment by cleidigh** [comment]
Addressed with PR #64267
See PR for verification steps
