### ISSUE TITLE
Make extension ui similar to the settings ui

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#58726]
The extension preview doesn't seem as well organized as the new settings preview. Here are my suggestions for improving consistency:

### Hide "Scroll Back to Top" button

Is there any telemetry data on how often this button is used? Neither the markdown nor the settings preview show this button, so displaying here doesn't make much sense. Also, I don't think it's themable so it just sits there looking de<i>press</i>ed.

![screenshot_20180914_183244](https://user-images.githubusercontent.com/36805289/45578683-0b861b00-b851-11e8-92cd-f41a96521ba2.png)

### Use same nav style

![screenshot_20180914_190225](https://user-images.githubusercontent.com/36805289/45578644-bfd37180-b850-11e8-8eaf-df293f714ec6.png)

![screenshot_20180914_190301](https://user-images.githubusercontent.com/36805289/45578655-d11c7e00-b850-11e8-8ecc-e0bc3db4ac7a.png)

The first image shows how the settings ui styles its nav headers and I personally find it more modern.

### Make navbar more condensed

![screenshot_20180914_184019](https://user-images.githubusercontent.com/36805289/45578950-6f5d1380-b852-11e8-980a-dff98d377922.png)

The current navbar is pretty verboose and it covers 1/3 of my screen while I'm reading the details or contributions. Maybe it could benefit from being sticky or even redesigned?

**Comment by ramya-rao-a** [comment]
> Hide "Scroll Back to Top" button

I agree. We are not being consistent here. This is available in the Details and Changelog section, but not in the Contributions. 
Another issue is the weird text shown on hover:

![image](https://user-images.githubusercontent.com/16890566/45774334-88264a00-bc01-11e8-95ce-318e36be032a.png)

> Use same nav style

Yes, the style in the settings editor does look modern and much better

> The current navbar is pretty verboose and it covers 1/3 of my screen while I'm reading the details or contributions. Maybe it could benefit from being sticky or even redesigned?

It already is sticky. i.e when you scroll the page, the header remains where it is. Are you referring to something else?

Some thoughts on re-design:
- Skip the description line. By default, we show the README for the extension which should have the required details. The description is covered in the list item in the extension viewlet as well, which the user would have read before clicking on the item which then opens the extension editor
- Move the Disable/Uninstall buttons to the first line next to the extension name and title

cc @misolori

**Comment by nealot** [comment]
I meant something like https://www.w3schools.com/howto/howto_js_sticky_header.asp where the extension information is separate from the navigation and is hidden when scrolling.

**Comment by ramya-rao-a** [comment]
Ah, that definitely is a good idea

**Comment by misolori** [comment]
This should be covered under https://github.com/microsoft/vscode/issues/68527 so closing this as a duplicate.
