### ISSUE TITLE
Range of returned document symbol for TypeScript too short

### ISSUE THREAD

**Issue by letmaik** [Microsoft/vscode#58732]
- VSCode Version: 1.27.2
- OS Version: Windows 10

Steps to Reproduce:

1. `commands.executeCommand('vscode.executeDocumentSymbolProvider', file)` where `file` is the uri of  vscode\src\vs\workbench\browser\viewlet.ts.
2. For the `run` symbol, the range is returned as [41:8, 41:53] which corresponds to `() => this.partService.setSideBarHi` instead of `run: () => this.partService.setSideBarHidden(true)`

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
The returned column values are line offsets (not visual column values). When using tabs in that document, I see that that row has 53 characters in it so the offset of column 8-53 look like it correctly marks the offsets of the function definition: `() => this.partService.setSideBarHidden(true)`
