### ISSUE TITLE
Duplicate commands in Terminal

### ISSUE THREAD

**Issue by MonirAbadi** [Microsoft/vscode#58738]
Issue Type: <b>Feature Request</b>

In the Terminal why the duplicate commands when using UP/DOWN arrow ?
You must DISTINCT it.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

**Comment by Tyriar** [comment]
Please provide more information on what you mean, a screenshot might also help.

**Comment by MonirAbadi** [comment]
I will, I am sorry
![descripe](https://user-images.githubusercontent.com/43251728/45624910-504dc400-ba94-11e8-85f8-3208de3028f2.png)

**Comment by Tyriar** [comment]
This is PowerShell's behavior, you'll need to report this to the PowerShell team. There's probably already a discussion at https://github.com/PowerShell/PowerShell
