### ISSUE TITLE
[git] keep "create a new branch" option always

### ISSUE THREAD

**Issue by oneslash** [Microsoft/vscode#58730]
**Problem**
The time you search for the branch and not find any, there are no other options to proceed.
<img width="682" alt="screen shot 2018-09-15 at 11 06 09" src="https://user-images.githubusercontent.com/15870134/45584640-8b56c880-b8d7-11e8-8554-fbbc462bb8dc.png">

I as a developer would need to delete the search and then click on "create a new branch".

**Solution**
Keep "create a new branch" option always.
<img width="656" alt="screen shot 2018-09-15 at 11 22 56" src="https://user-images.githubusercontent.com/15870134/45584757-b8a47600-b8d9-11e8-9ccb-0e178a0b10bf.png">

**Comment by joaomoreno** [comment]
@chrmarti Is this supported from an extension? Eg: keep an option always visible.

**Comment by oneslash** [comment]
@guywald1, since my PR is merged already, feel free to create a PR with tests :)

**Comment by guywald1** [comment]
I added a PR to add tests and also fix a small bug (when explicitly settings items on a `QuickPick` the field was not properly propagated).

Additional thoughts I had (should open another issue for discussion?):

* In my opinion, items that should always be shown shouldn't display search highlights. The highlights are possibly redundant and IMO it would look more elegant without

* I feel like after accepting the `Create new branch` option, the input text should be preserved. Would a PR to address this be accepted?
Also, possibly should this behavior be exposed for user control? (i.e. similarly to a `shouldAlwaysShow` field, a `preserveInput` field.)

**Comment by joaomoreno** [comment]
> I feel like after accepting the Create new branch option, the input text should be preserved. Would a PR to address this be accepted?

:+1: 

> Also, possibly should this behavior be exposed for user control?

Nah, sounds like a very good default value.
