### ISSUE TITLE
Settings Inputs are clipped at certain resolutions

### ISSUE THREAD

**Issue by beastdestroyer** [Microsoft/vscode#58739]
Issue Type: Bug
No relevant issues have been found

- VSCode Version: 1.28.0-insiders (User, 15th September).
- OS Version: Windows 10 1803 17134.285

Steps to Reproduce:
The time it takes can vary depending on monitor size and window scaling. Mu monitor is a 1360x768 and so I tested with that. I have experimented with zoom levels, and toggling views of the sidebar. This issue is persistent across all tests.

1. Open DevTools
1.5 (Optional) Change Window Zoom
2. Don't enter responsive mode, just resize by dragging the edge. At certain boundaries, the inputs started to be clipped:
![image](https://user-images.githubusercontent.com/30497573/45588857-739d3580-b913-11e8-8c0d-93215f03fed1.png)
As you can see, the arrow of the dropdown starts to be clipped. The whole input starts to be clipped at the right. In this specific case, this clipping was visible at resolutions of (Width x Height) 651 x 768 to 670 x 768

Here it is again but with the sidebar open:
![image](https://user-images.githubusercontent.com/30497573/45588875-e0183480-b913-11e8-9552-102a25c6ee32.png)

I know Visual Studio Code wasn't designed for mobile type screens (if you could call it that?) since the options at the titlebar are also clipped, but figured this might be worth mentioning

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Changed a lot of layout last week and I can't see this anymore. Let me know if you can.

**Comment by beastdestroyer** [comment]
It does happen but it is mainly fixed 
Using a screen of 1360 x 768,opening the sidebars to about the letter 'a' under Terminal, then opening Devtools and resizing still makes it clip however the actual screen estate for the Settings GUI is very thin and I doubt anyone is using VSCode with the editor width of a mobile screen.
