### ISSUE TITLE
Debug console is now outputting tabs as spaces

### ISSUE THREAD

**Issue by MarkBird** [Microsoft/vscode#58733]
Issue Type: <b>Bug</b>

Since the latest update, debug console has started outputting tabs as spaces.

I had a simple script that output tabbed data which I would paste into Excel and use Text to Columns delimited on tabs, which now does not work.

To reproduce I created a new Python script tab.py with the following code:

`print("x\ty")`

Copy and paste the output from the Debug Console into a text editor with white space showing (I used Notepad++) and you can see the tab has been substituted with a single space. This was not happening until the latest update.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.82GB (8.21GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe --disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled

**Comment by isidorn** [comment]
File against the python extension please
