### ISSUE TITLE
Mirroring sequence of nested placeholders not selected properly on backjumping

### ISSUE THREAD

**Issue by andreyorst** [Microsoft/vscode#58736]
- VSCode Version: 1.27.2
- OS Version: Arch Linux, Windows 10

### Steps to Reproduce:
Use this snippet for C filetype:
```json
"nested miroring test": {
	"prefix": "bug",
	"body": "${3:nest1 ${1:nest2 ${2:nest3}}} $3",
	"description": "bug"
}
```
1. Jump until `nest3` placeholder is selected:
![image](https://user-images.githubusercontent.com/19470159/45587861-53ba4180-b914-11e8-88d8-3e308615918e.png)
2. Replace it with any text:
![image](https://user-images.githubusercontent.com/19470159/45587866-63d22100-b914-11e8-9173-228f6828f49f.png)
3. Jump back once:
![image](https://user-images.githubusercontent.com/19470159/45587874-6f254c80-b914-11e8-9d42-1f714be9dd36.png)
4. Replace selected placeholder with some text:
![image](https://user-images.githubusercontent.com/19470159/45587878-7c423b80-b914-11e8-94a0-424200ee9686.png)
5. Jump forward:
![image](https://user-images.githubusercontent.com/19470159/45587883-85cba380-b914-11e8-9f10-8f6bcf70dd45.png)
6. Jump forward, to the placeholder `$3` which should select whole nested sequence selects only part in the mirroring sequence:
![image](https://user-images.githubusercontent.com/19470159/45587901-dd6a0f00-b914-11e8-8571-e2959d91f545.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
@andreyorst thanks for reporting this. I have just pushed a fix and next (tomorrows) [Insiders build](https://code.visualstudio.com/insiders/) will already have this fix.
