### ISSUE TITLE
"Failed to install VS Code update"

### ISSUE THREAD

**Issue by axmccx** [Microsoft/vscode#58743]
- VSCode Version: 1.27.1
- OS Version: Windows 10 Pro 64 bit 1803

This issue has been happening for the past 3 releases. I've had to download the installer from the website to update. 

Steps to Reproduce:

1. Click the gear icon at the bottom left
2. Click "Restart to update..."
3. VSCode closes itself, and the small window with text "Updating VS Code" appears
4. Following prompt appears

![image](https://user-images.githubusercontent.com/3931007/45589370-ab47b580-b8f2-11e8-96e2-632545039494.png)

Here are the logs the error says to attach. 

[vscode-inno-updater-1537035438.log](https://github.com/Microsoft/vscode/files/2385976/vscode-inno-updater-1537035438.log)

Once I close the prompt, VS Code restarts itself. The "Restart to update..." is a grey button with the label "Installing update...". After a short while, this prompt appears. 

![image](https://user-images.githubusercontent.com/3931007/45589412-172a1e00-b8f3-11e8-9376-4bfcd98e7bcf.png)

Clicking retry bring the window back. 

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by NaxxoBG** [comment]
I get exactly the same error.
