### ISSUE TITLE
Add regex support for sourceFileMap (debugging config)

### ISSUE THREAD

**Issue by datgame** [Microsoft/vscode#58740]
I wish to translate paths from a compile-time unknown generated path names into a path vscode can find the files.
This could be solved with a regex, or similar.

For example translate /home/me/dev/.tup/mnt/@tupjob-665/home/me/dev/build/lib to /home/me/dev/lib (I think), since the file is in /home/me/dev/lib/flag.cpp

This situation happens e.g. when building code using ([https://github.com/gittup/tup]) 
The 665 number is different during each build.
The added /build is because the current working directory when compiling is different from the source directory, to not place object files in the source folder.

Example output from objdump -W
    <11>   DW_AT_name        : (indirect string, offset: 0x1d07): flag.cpp
    <15>   DW_AT_comp_dir    : (indirect string, offset: 0x121cd): /home/me/dev/.tup/mnt/@tupjob-665/home/me/dev/build/lib

**Comment by weinand** [comment]
VS Code is not involved in this operations. Please file an issue against the debugger you are using.
