### ISSUE TITLE
Aero snap stops working if program is closed while snapped and reopened

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#58745]
I'm not sure if this is a Windows bug or a VS Code bug, so I'm filing it on both sides. (I _believe_ it's a VS Code bug.) https://aka.ms/AA2l4z3

I frequently use Windows Key + Left/Right to snap windows to sides of my display and to move windows from one display to another. When VS Code is closed while it is snapped, after it is reopened it is only be able to be snapped in one direction, not the other. 

Steps to reproduce:
1. Pin VS Code to the right side of the screen.
2. Close the program.
3. Re-open the program.
4. Press Windows + Left.
5. Notice it doesn't do anything.
6. Press Windows + Right.
7. Notice it works as expected.
8. Notice moving or resizing the window manually fixes snapping.

It looks like this sort of thing only happens with programs that attempt to remember and restore their window position. I wonder if there is an 'is currently snapped' flag that is getting saved and restored? I also see this behavior with Firefox and not with Chrome, for what it's worth.

EDIT: Firefox and Chrome appear to have been fixed since this issue was created.

**Comment by akbyrd** [comment]
Different issue from the bot link, but possibly the same or a similar root cause.

**Comment by akbyrd** [comment]
@bpasero I'm not entirely sure this should be closed as a duplicate. This and the other issue are describing two different behaviors. They *may* have the same underlying cause, but that's not known currently. It seems like any fix should explicitly verify that this behavior is fixed. And it seems like it should be prioritized higher than 'the window size is slightly wrong' because it breaks basic Windows functionality.

**Comment by chrisdias** [comment]
per @Tyriar's comment: https://github.com/microsoft/vscode/issues/22010#issuecomment-368182147 I rans some quick tests:

Do not restore snapped:
- notepad 
- notepad++
- edge (old)
- office apps 
- slack 

Chrome acts like VS Code at times, and in some cases it is actually worse. Pressing Win+L or Win+R repeatedly will eventually cause it to only take up a quarter of the screen.

The only apps I test that restored snapped were Teams and Firefox.

So, it looks like the correct Windows behavior is to restore normally, not snapped.  

@bpasero any pointers to the code? Not sure if this is something I could PR but could take a look.

**Comment by bpasero** [comment]
@Tyriar @chrisdias windows restore happens in https://github.com/microsoft/vscode/blob/df96e402b2c1bcd7a9cc22f647a1c33f9a906677/src/vs/code/electron-main/window.ts#L51

**Comment by akbyrd** [comment]
@chrisdias When you say 'restore' are you referring to the built-in Windows action that is available on a maximized window or the state when opening a window after it was closed?

To be clear, the issue here is that Win+L and Win+R stop working entirely, not whether the window opens directly into the snapped state. I don't expect windows to open and automatically snap themselves, I just want my keyboard shortcuts not to break.

**Comment by chrisdias** [comment]
@akbyrd Agreed, there are two parts to this problem, the restore state and the key bindings not working.  Sorry for not being clear.
