### ISSUE TITLE
Unable to access application main menu from keyboard

### ISSUE THREAD

**Issue by AnrDaemon** [Microsoft/vscode#58744]
Issue Type: <b>Bug</b>

Hitting Alt on keyboard merely flashes menu access keys.
Hitting F10 have no effect at all.
The menu remains inaccessible.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3550 CPU @ 3.30GHz (4 x 3303)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.96GB (9.32GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe \\HOSTING64.DARKDRAGON.LAN\wwwroot\ccenter"|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|0.8.8
php-debug|fel|1.12.5
smarty|imp|0.3.0
svn-scm|joh|1.34.1

</details>

**Comment by sbatten** [comment]
Can you share a gif of your experience?

**Comment by ramya-rao-a** [comment]
@AnrDaemon

Are you using the native or custom menu style? i.e What is the value of your setting `window.titleBarStyle`? Is it `native` or `custom`? 

I dont see the flashing when using custom, but I do see it when using native

**Comment by AnrDaemon** [comment]
It is set to "native" of course.
Checked with "custom" and I can confirm your findings. The menu is accessible as intended.
But the look is unbearable. I don't want my desktop turned into parading mess of styles and epochs.

**Comment by sbatten** [comment]
@AnrDaemon Sorry to hear that you aren't a fan of the appearance of the new menu. If you wish to customize the appearance to match the old experience, there are several theme colors you may choose to set here https://code.visualstudio.com/docs/getstarted/theme-color-reference#_menu-bar-colors. 

As the new experience is intended to address the accessibility concerns of the old menu bar, this issue will be closed as out of scope. The new experience will be the default for Windows in the upcoming release.

**Comment by AnrDaemon** [comment]
This is not about colors, this is about consistency of user interface.
Which new appearance utterly ruin.
