### ISSUE TITLE
Some shortcuts not working on Linux

### ISSUE THREAD

**Issue by gigi206** [Microsoft/vscode#58747]
- VSCode Version: 1.27.2
- OS Version: Linux Fedora 28

Some shortcuts that working on Windows and also described on [documentation](https://code.visualstudio.com/shortcuts/keyboard-shortcuts-linux.pdf) don't working.

On Windows there is no problem but on Linux I need to reconfigure some shortcuts :
```
[
  {
    "key": "ctrl+[Quote]",
    "command": "workbench.action.terminal.toggleTerminal"
  },
  {
    "key": "ctrl+[Period]",
    "command": "editor.action.blockComment",
    "when": "editorTextFocus && !editorReadonly"
  },
  {
    "key": "ctrl+[Backslash]",
    "command": "editor.action.jumpToBracket"
  }
 ]
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
@gigi206 The documentation describes keybindings for the US keyboard layout? Are you perhaps using a different keyboard layout?

**Comment by gigi206** [comment]
Yes I use french Keyboard but some shortcuts works on Windows but not on Linux (some shortcuts on Linux seems not defined).

**Comment by alexandrudima** [comment]
We ship out of the box with good keybindings for the US keyboard layout. When we detect a different keyboard layout, we try to map them to the current keyboard layout, but this is not always possible (e.g. if the character cannot be produced by the keyboard layout or if producing it already requires pressing a certain modifier key).

Let's continue tracking in #1240 , which you can upvote, such that we ship in the future with per keyboard layout optimized defaults.
