### ISSUE TITLE
VS Code not honoring ComSpec environment variable value

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#5874]
- VSCode Version: 1.1.0 Alpha
- OS Version: Windows 10

Regarding #5463
VS Code continues to open the Windows-default Command Prompt, even though my %ComSpec% variable is set to `C:\Program Files\JPSoft\TCCLE14x64\tcc.exe`.

@Tyriar also a heads up that the setting you gave to set PowerShell as the default in #5463 does not work for me.  But the following setting did `"externalTerminal.windowsExec": "powershell"`

Steps to Reproduce:

1. Install the TCC/LE cmd replacement
2. Set it as the default in the %COMSPEC% variable
3. Right click a folder in the file explorer and click "Open in Command Prompt"

**Comment by Tyriar** [comment]
This is just a matter of grabbing COMSPEC here https://github.com/Microsoft/vscode/blob/f412e4f444ab848a1bafe047a91a8bf3ac266c7c/src/vs/workbench/parts/execution/electron-browser/terminal.ts#L25
