### ISSUE TITLE
Search "include" and "exclude" features not working when searching remote drive on windows

### ISSUE THREAD

**Issue by MoayyadMaswadeh** [Microsoft/vscode#58758]
Issue Type: <b>Bug</b>

It is now September 16th and my version is 1.27.2, however, I noticed the issue on the last update before 1.27.2, the "exclude" feature in search is not working, and node_modules for example is always being searched even if I add it to the "exclude" list, I tried many ways by adding * to the beginning and end and many other combinations, nothing worked, I also noticed that "include" feature is not working as well.

Looking forward to see this issue fixed, thanks :)

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3540M CPU @ 3.00GHz (4 x 2990)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (4.89GB free)|
|Process Argv|C:\Users\moayad.maswadeh\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.10
tortoise-svn-for-vscode|cds|0.1.1
vscode-eslint|dba|1.6.0
tslint|eg2|1.0.39
Angular-BeastCode|Mik|6.2.25

</details>

**Comment by MohQut** [comment]
+1

**Comment by roblourens** [comment]
Can you check the search issues wiki to see if any troubleshooting tips in there are relevant? https://github.com/Microsoft/vscode/wiki/Search-Issues

**Comment by samjacobclift** [comment]
seems to be affecting me on mac os x too

**Comment by samjacobclift** [comment]
Ahh found the reason, was because I did have the `Use Exclude Settings and Ignore Files` toggle on

<img width="323" alt="screen shot 2018-09-18 at 16 16 35" src="https://user-images.githubusercontent.com/1868592/45697682-3ed0ee80-bb5e-11e8-89dc-a47321c4f668.png">

**Comment by MoayyadMaswadeh** [comment]
> Ahh found the reason, was because I did have the `Use Exclude Settings and Ignore Files` toggle on
> 
> <img alt="screen shot 2018-09-18 at 16 16 35" width="323" src="https://user-images.githubusercontent.com/1868592/45697682-3ed0ee80-bb5e-11e8-89dc-a47321c4f668.png">

Hi @samjacobclift,
Unfortunately, I tried this but it didn't work.


Not just that, I uninstalled VSCode completely, deleted all related files under the %USERPROFILE% and AppData including extensions, then I downloaded the latest version (1.27.2) installer from Microsoft website, installed again, and I'm experiencing the same issue even though I haven't installed any extensions.

Anyone with the same issue? or anyone with a fix for it?
Appreciated.

**Comment by xxjapp** [comment]
> > Ahh found the reason, was because I did have the `Use Exclude Settings and Ignore Files` toggle on
> > <img alt="screen shot 2018-09-18 at 16 16 35" width="323" src="https://user-images.githubusercontent.com/1868592/45697682-3ed0ee80-bb5e-11e8-89dc-a47321c4f668.png">
> 
> Hi @samjacobclift,
> Unfortunately, I tried this but it didn't work.
> 
> Not just that, I uninstalled VSCode completely, deleted all related files under the **%USERPROFILE%** and **AppData** including extensions, then I downloaded the latest version **(1.27.2)** installer from Microsoft website, installed again, and I'm experiencing the same issue even though I haven't installed any extensions.
> 
> Anyone with the same issue? or anyone with a fix for it?
> Appreciated.

Exactly the same problem on two windows 7 pc.

**Comment by xxjapp** [comment]
Uninstalling 1.27.2 (NG) and installing 1.26.1 solved my problem.
[https://code.visualstudio.com/updates/v1_26](https://code.visualstudio.com/updates/v1_26)

**Comment by xxjapp** [comment]
After 1.26.1 is installed, vs code auto-upgraded to 1.27.2 on background. But this time the excluding input works now after restart vscode.

**Comment by roblourens** [comment]
Please do the following

- Run the command "Set log level" and change it to "Trace"
- Run the search again
- Show the search-related messages in the "Log (Window)" output panel

![image](https://user-images.githubusercontent.com/323878/35987940-02aae15a-0cb2-11e8-83f1-d95c5dc3881b.png)

**Comment by MohQut** [comment]
Hi @roblourens 

I have the same issue but I have noticed that this issue occurs only when the code is not on my machine, I usually open the code that is on the server from my machine

I have tested both cased and attached the logs for both as you have instructed
[working.log](https://github.com/Microsoft/vscode/files/2408598/working.log)
[not working.log](https://github.com/Microsoft/vscode/files/2408599/not.working.log)

Kindly advise

**Comment by roblourens** [comment]
That scenario seems to work fine for me.

What exactly is it getting wrong? Are you using the files to include/exclude fields? Can you try with no open files since those are handled differently?

**Comment by MohQut** [comment]
I am trying to search while excluding a specific path or extension as you can see in the screenshot below
![image](https://user-images.githubusercontent.com/10207395/45995862-88f82980-c0a2-11e8-99f3-a6b7d9435dd7.png)
but the excluded extension is not excluded

**Comment by roblourens** [comment]
I can repro

**Comment by MoayyadMaswadeh** [comment]
Any update on this please? @roblourens

**Comment by roblourens** [comment]
I have a fix, as a workaround you can enable `searchRipgrep.enable` because it seems to work in that mode.
