### ISSUE TITLE
Ablility to Select what to open when opening new terminal

### ISSUE THREAD

**Issue by kameshkotwani** [Microsoft/vscode#58753]
It would be very nice if I could get to select which terminal to open every time when creating a new terminal, like cmd or PowerShell or Linux bash or Git Bash. I should get a drop-down list to select from one of these every time I press CTRL+` or I click on the + icon in the integrated terminal. Or you guys can also create a submenu in the terminal menu to choose one. Also, when splitting up terminal I should be able to open different terminals side by side, as one to be bash and one to be PowerShell. It would be really good for my demonstration purposes.

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/45444

**Comment by kameshkotwani** [comment]
Can I please know the reason why this issue is closed? It's a feature
request.

**Comment by Tyriar** [comment]
@kameshkotwani it's a duplicate:

<img width="405" alt="screen shot 2018-09-17 at 5 52 10 am" src="https://user-images.githubusercontent.com/2193314/45624013-eb677f00-ba3d-11e8-84db-ef7a02824f14.png">

**Comment by kameshkotwani** [comment]
Just because some of the phrases or words are same that does not mean that
it is duplicate. It's a bot. Please read my suggestion first.

**Comment by Tyriar** [comment]
> Allow more than one terminal shell configuration 

> terminal, like cmd or PowerShell or Linux bash or Git Bash

It's the same concept, if you read through the issue you will find a workaround https://marketplace.visualstudio.com/items?itemName=Tyriar.shell-launcher
