### ISSUE TITLE
Integrate Dependency checker into typescript compiler

### ISSUE THREAD

**Issue by AsiFefer** [Microsoft/vscode#58754]
Issue Type: <b>Feature Request</b>

Hello,

Typescript compiler first task, should be dependency check. In case compiler found any dependendy, between 2 modules, then it should display a warning about it, In VS code Terminal window.
For example, lets assume that module A use Module B which in turn use Module A. So the following warning should be displayed:
Warning: A -> B -> A.

Dependency check is easy to implement:
Compiler reads the content of the files in the project. It reads the Import section of each module. It then follows the import to the next file. It does so, until he reaches a module that has no imports. In case he starts from some module, and on the way he gets back to that module, then this is a dependency between 2 modules.

Thanks,
Asi.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#27147
