### ISSUE TITLE
VSCode interface freeze but still working.

### ISSUE THREAD

**Issue by Visonnn** [Microsoft/vscode#5875]
- VSCode Version: 1.0.0
- OS Version: Windows 10.0.10586 Professional 64bit

Steps to Reproduce:

1. Open a folder which contain a git project
2. Drag VSCode to screen left side edge, and drag Chrome to right side, let them take half width of screen both
3. Browsing YouTube or some other website :dancers: 
4. Then the VSCode UI went freeze, and I found that it still working, resize the window can recover it.

This situation occurs **randomly**, and I'm not sure it can be reproduced with the above steps.

Thanks

**Comment by bpasero** [comment]
@Visonnn does it reproduce with our latest insider build? 
You can give it a try from our insiders release today: http://code.visualstudio.com/Download#insiders

**Comment by Visonnn** [comment]
@bpasero Thanks for your reply.

Now I'm trying the insider version today and will update later.

**Comment by Visonnn** [comment]
@bpasero 

Hi,

I've installed VSCode (Version: 1.1.0-insider) today and the UI freeze again just now.

Installed extension:

* jshint (0.10.10)

* One Dark Theme (0.2.5)

**Comment by bpasero** [comment]
Could it be that you use G-Sync functionality from Nvidia? See https://github.com/Microsoft/vscode/issues/3743
