### ISSUE TITLE
Format

### ISSUE THREAD

**Issue by vronney** [Microsoft/vscode#58750]
Issue Type: <b>Bug</b>

Not too sure why my code is apearing in this manner. Don't lkike it.  How do I reset.  

class App extends Component {
    render() {
        return ( <
            div className = "App" >
            <
            ContactList contacts = {
                [
                    { name: "Michael" },
                    { name: "Ryan" },
                    { name: "Tyler" }
                ]
            }
            / > <
            ContactList contacts = {
                [{
                        name: "Ron"
                    },
                    {
                        name: "Elsa"
                    },
                    {
                        name: "Daisy"
                    }
                ]
            }
            / > 
            </div>
        );
    }
}

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.1.0
project-manager|ale|8.1.0
vagrant|bbe|0.5.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-eslint|dba|1.6.0
githistory|don|0.4.2
xml|Dot|2.3.2
gitlens|eam|8.5.6
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.39
vscode-npm-script|eg2|0.3.5
vscode-optimize-images|fab|1.0.4
auto-close-tag|for|0.5.6
knockoutjs|fur|0.1.0
vscode-firefox-debug|hbe|1.6.0
beautify|Hoo|1.4.3
rest-client|hum|0.19.1
docthis|joe|0.7.1
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vs-cron|mkl|2.0.1
vs-deploy|mkl|14.0.0
vs-remote-debugger|mkl|2.0.0
vs-rest-api|mkl|3.0.1
vs-script-commands|mkl|7.0.0
vs-swiss-army-knife|mkl|1.0.3
python|ms-|2018.8.0
atom-keybindings|ms-|3.0.4
csharp|ms-|1.16.1
sublime-keybindings|ms-|4.0.0
team|ms-|1.136.0
debugger-for-chrome|msj|4.10.1
createGUID|nwa|0.0.2
prettier-vscode-with-tabs|pas|1.1.0
vscode-docker|Pet|0.2.0
typescript-hero|rbb|2.3.2
LiveServer|rit|5.1.1
vscode-icons|rob|7.26.0
code-spell-checker|str|1.6.10
lorem-ipsum|Tyr|1.2.0
html-css-class-completion|Zig|1.17.1

</details>

Issue Type: <b>Bug</b>

Not too sure why my code is apearing in this manner. Don't lkike it.  How do I reset.  

class App extends Component {
    render() {
        return ( <
            div className = "App" >
            <
            ContactList contacts = {
                [
                    { name: "Michael" },
                    { name: "Ryan" },
                    { name: "Tyler" }
                ]
            }
            / > <
            ContactList contacts = {
                [{
                        name: "Ron"
                    },
                    {
                        name: "Elsa"
                    },
                    {
                        name: "Daisy"
                    }
                ]
            }
            / > 
            </div>
        );
    }
}

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.1.0
project-manager|ale|8.1.0
vagrant|bbe|0.5.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-eslint|dba|1.6.0
githistory|don|0.4.2
xml|Dot|2.3.2
gitlens|eam|8.5.6
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.39
vscode-npm-script|eg2|0.3.5
vscode-optimize-images|fab|1.0.4
auto-close-tag|for|0.5.6
knockoutjs|fur|0.1.0
vscode-firefox-debug|hbe|1.6.0
beautify|Hoo|1.4.3
rest-client|hum|0.19.1
docthis|joe|0.7.1
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vs-cron|mkl|2.0.1
vs-deploy|mkl|14.0.0
vs-remote-debugger|mkl|2.0.0
vs-rest-api|mkl|3.0.1
vs-script-commands|mkl|7.0.0
vs-swiss-army-knife|mkl|1.0.3
python|ms-|2018.8.0
atom-keybindings|ms-|3.0.4
csharp|ms-|1.16.1
sublime-keybindings|ms-|4.0.0
team|ms-|1.136.0
debugger-for-chrome|msj|4.10.1
createGUID|nwa|0.0.2
prettier-vscode-with-tabs|pas|1.1.0
vscode-docker|Pet|0.2.0
typescript-hero|rbb|2.3.2
LiveServer|rit|5.1.1
vscode-icons|rob|7.26.0
code-spell-checker|str|1.6.10
lorem-ipsum|Tyr|1.2.0
html-css-class-completion|Zig|1.17.1

</details>

**Comment by joaomoreno** [comment]
What do you mean? A screenshot would be helpful.

**Comment by vronney** [comment]
Here is a sample of the code.

eturn ( <
div className = 'list-contacts' > { JSON.stringify(this.state) } <
div className = 'list-contacts-top' >
<
input className = 'search-contacts'
type = 'text'
placeholder = 'Search contacts'
value = { this.state.query }
onChange = {
(event) => this.updateQuery(event.target.value)
}
/ > < /
div >

**Comment by joaomoreno** [comment]
Please provide a screenshot and a detailed explanation of the issue.

**Comment by joaomoreno** [comment]
@vronney Please come to Github and open this issue in your browser. You will immediately see why I can't really understand what you problem is.

Please, **please**, send me a screenshot, or I will be forced to close this issue.

**Comment by vronney** [comment]
Here is  a screen shot.
I circle the areas to show as an example.  The code editor is formatting
the tags in the following manner.  It separates the tag.  Makes it hard to
read.  How can I fix this?
[image: image.png]

**Comment by joaomoreno** [comment]
Sorry, the screenshot still does not appear. Come to GitHub and upload it in the browser.

Closing this issue for now.
