### ISSUE TITLE
Additional instance starts in wrong virtual desktop

### ISSUE THREAD

**Issue by rojepp** [Microsoft/vscode#5876]
- VSCode Version:1.0.0
- OS Version: Windows 7

I'm using desktops.exe from SysInternals to add virtual desktops to Windows 7.
When having an open instance of code in a not active desktop, starting an additional instance will not start on the currently active desktop. 

Steps to Reproduce:

1. Open VSCode in desktop 1
2. Switch to desktop 2
3. Start another VSCode instance: `code .`. The new instance starts in desktop 1

**Comment by bpasero** [comment]
Marking as upstream as this might require changes in Electron to support the scenario.

**Comment by rojepp** [comment]
I can confirm that Atom behaves the same, so it probably is upstream.

**Comment by bpasero** [comment]
It is ok to leave open our upstream issues to keep track on them. Thanks for finding out about Atom

**Comment by bpasero** [comment]
@rojepp I wonder if our recent Electron update changed something? 
You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by bpasero** [comment]
Please reopen if this still happens with our 1.6.0 release.
