### ISSUE TITLE
VSCode 'crashed' --> very slow, extensions problem

### ISSUE THREAD

**Issue by devAbu** [Microsoft/vscode#58766]
Hi, 

I installed VSCode long ago, and it's work perfectly until I uninstall it and use Atom for 2 months and then instal VSCode again (before several days or weeks)...I uninstall it because of the issue I had with Github Desktop, once I fix it I immediately install VSCode again. But since I re-install it I had problems with it. It's slower than before, and the biggest problem is because the extensions don't work. For example, emmet, beautify and so on. Some of them run at the beginning and then crashed. For example, todo extension (it shows me all todos I wrote, but once I delete one or add new, it again shows me the previous todos (it doesn't add new or remove one, even if I refresh the list). Please tell me how can I fix it, or if it's problem from you.

Thanks in advance,

Best regards.

**Comment by devAbu** [comment]
It works perfectly and faster when I run "code --disable-extensions"; so the problem is with some extension, is there any way to automatically know which extension makes the problem.

**Comment by joaomoreno** [comment]
You can selectively disable one by one until you figure out which one causes the issue. Let me know.

**Comment by devAbu** [comment]
So there is no easier way of doing that? 

I disabled all extensions and then enable several of them I need the most and it works fine now, I will from time to time enable extensions that I will need. Thanks!

**Comment by joaomoreno** [comment]
Let me know if you ever find out which extension does that.
