### ISSUE TITLE
gui broken

### ISSUE THREAD

**Issue by kolzar** [Microsoft/vscode#58762]
- VSCode Version: [1.27.2]
- OS Version: Win10 student

Steps to Reproduce:

1. i open vs code
2. for few seconds i dont use the application
3. appears the vs code in this state.
4. I can't understand this app's behavior.

![screenshot](https://user-images.githubusercontent.com/4801679/45595044-b90a4300-b9a5-11e8-94d8-5df674ebc73b.PNG)

**Comment by kolzar** [comment]
I see the application blurred when I do not use it.

**Comment by roblourens** [comment]
So it actually appears blurred in the way that it appears in the screenshot?

Have you ever seen that happen with another app on Windows? I don't know whether that's some Windows feature? Or an electron issue?

Can you tell me anything else about what happens, e.g. do you see it switch from clear to blurry after a few seconds?

**Comment by kolzar** [comment]
So it actually appears blurred in the way that it appears in the screenshot? yes, when i move the focus on other application.

Have you ever seen that happen with another app on Windows? I don't know whether that's some Windows feature? Or an electron issue? No, it appears only in the vs code window. it's normal outside of this window.

Can you tell me anything else about what happens, e.g. do you see it switch from clear to blurry after a few seconds? Exacly, appears like this screenshot.

**Comment by roblourens** [comment]
> yes, when i move the focus on other application.

So if you move the focus back to vscode, does it stay blurry?

**Comment by kolzar** [comment]
So if you move the focus back to vscode, does it stay blurry? No, it come back normally.

Can you use vscode at all in this state? If you click in the window, does anything happen? Come back normally.

**Comment by roblourens** [comment]
Oh ok, so you're not blocked from using it normally, it just looks blurry in the background, right?

**Comment by kolzar** [comment]
Exactly.

**Comment by roblourens** [comment]
Ok. FYI @Tyriar for Electron maybe

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/51789
