### ISSUE TITLE
wls shell cmd fail to execute with tasks.json

### ISSUE THREAD

**Issue by honghuadi** [Microsoft/vscode#58763]
- VSCode Version: 1.27.2, 1.28.0-insider
- OS Version:  Win10 Enterprise 64b (10.0, build 16299)

Steps to Reproduce:
Same issue as 
https://github.com/Microsoft/vscode/issues/32349#issuecomment-321918399
which is suppose to be fixed already.

1.  set default shell to WLS bash, no problem to open terminal window as "1.wsl" 
![image](https://user-images.githubusercontent.com/42500439/45595470-8748aa80-b9ac-11e8-8f18-8ce6d05b39a7.png)

2.  create new task in tasks.json

![image](https://user-images.githubusercontent.com/42500439/45595473-9def0180-b9ac-11e8-9f8c-c97a3f464dfa.png)

3. ctrl + shift + b, choose above task to run

4. return in terminal window "2.Task - Test(test)"
![image](https://user-images.githubusercontent.com/42500439/45595433-05f11800-b9ac-11e8-9630-9ef0e67229ca.png)

5. Try workaround in another post by change command to "\"pwd\"", problem still there.

6. no problem if I use cmd.exe as default shell and run task with command "dir"

**Comment by alexr00** [comment]
This should be fixed now. We were missing the run argument for wsl.exe.
