### ISSUE TITLE
Extension Icons missing after update to 1.27

### ISSUE THREAD

**Issue by msaleixo** [Microsoft/vscode#58767]
Issue Type: <b>Bug</b>

After I updated to version 1.27 the icons on the extensions list are missing

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2310M CPU @ 2.10GHz (4 x 2095)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.94GB (0.58GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.1.0
vscode-eslint|dba|1.6.0
gitlens|eam|8.5.6
php-intellisense|fel|2.3.5
intellij-idea-keybindings|k--|0.2.26
vscode-language-pack-es|MS-|1.27.2
vetur|oct|0.12.6
local-history|xyz|1.7.0
vscode-surround|yat|1.0.2

</details>

**Comment by sandy081** [comment]
@msaleixo Can you please post a screenshot ?
