### ISSUE TITLE
A VS Scratchpad at the panel

### ISSUE THREAD

**Issue by folarinmartins** [Microsoft/vscode#58774]
Reference: Geany Scribble feature. Let's be able to drop snippets, passwords, tokens etc in a scratch pad suitably located beside the terminal tab of the panel. That location is strategic and easy to reach just the way it's implemented in Geany text editor
![scribbe](https://user-images.githubusercontent.com/11775526/45599832-a7975a00-b9ea-11e8-9ef0-8df5c068cca6.png)

**Comment by oneslash** [comment]
I would love to work on this task

**Comment by nealot** [comment]
What is the benefit of this over opening an editor and typing in there?

**Comment by folarinmartins** [comment]
It's not treated so why is it closed. It's an excellent feature to have on an excellent editor.
-A always need my multiple cpanel/ftp/google-console apis/web service tokens and all.
-Code snippets from stakexchange search or just inspiring code snippets or quotes
-Or plane, things I just care to have
These are best always before me. Not as an everyday editor, because they are not documents, it's just a scratch pad
-The incompleteness of the geany implementation is the fact that your notes are not synced online

@oneslash should you get to put this up, please hit this thread

Great work guys
