### ISSUE TITLE
Stripping blanks when pasting

### ISSUE THREAD

**Issue by pevans360** [Microsoft/vscode#58778]
Issue Type: <b>Bug</b>

Frequently when copying/pasting code, you want to keep the leading spaces.  For example, I just had to add the same class into a bunch of HTML elements after existing class names.  It was class="class1" ... wanted to change to class="class1 class2".   Copied " class2" (with a leading space) into the clipboard.  When pasting, now get class="class1class2" ... leading space is stripped out and has to be added manually.  

I think it's the same with trailing spaces.  Seems like a small thing, but it comes up alot.  I almost never copy leading/trailing spaces when they're not needed.  So this does more harm than good.  

Thanks

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4930K CPU @ 3.40GHz (12 x 3400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.94GB (43.31GB free)|
|Process Argv|G:\Program Files\Microsoft VS Code\Code.exe -n|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
debugger-for-chrome|msj|4.10.1
Angular2|UVB|0.4.1

</details>

**Comment by rebornix** [comment]
![leading-space](https://user-images.githubusercontent.com/876920/45640776-68a7e980-ba68-11e8-8c27-6b9f152b0b33.gif)

I didn't reproduce this issue (see above gif), can you help provide ways to reproduce this issue stably? IMO this should not happen as we don't trim the spaces for copy pasting.

**Comment by pevans360** [comment]
Thanks for checking.  Looked at my settings.  ‘Format on paste’ was turned On.  Turned it off and the ‘blank trimming’ stopped.  Of course that means there’s no formatting on paste …

**Comment by rebornix** [comment]
Thanks!
