### ISSUE TITLE
Typing relative paths with intelligence

### ISSUE THREAD

**Issue by chuyik** [Microsoft/vscode#5877]
- VSCode Version: 1.0.0 (1.0.0)
- OS Version: OS X 10.11

This is a feature request rather than a issue.

I hope the code intelligence could happen whenever we need to enter a relative path, and a dropdown list shows up to give us some hints for selecting a file to import without looking at the file tree.

There are some scenarios:
- HTML/CSS file: when a HTML src attribute or a CSS background attribute is being set, shows a list of some images relative path
- Node.js file: when we need to require a node module, shows a list of local/installed node.js files relative path

In fact, there's a Sublime plugin named [NodeRequirer](https://github.com/ganemone/NodeRequirer) provides the exact same feature and works very well, but only help writing node.js.

**Comment by bpasero** [comment]
@aeschli fyi

**Comment by mjbvz** [comment]
This has been implemented for js/ts

For html, try this extension: https://marketplace.visualstudio.com/items?itemName=christian-kohler.path-intellisense
