### ISSUE TITLE
no error when installing extension with disabled dependency

### ISSUE THREAD

**Issue by Spongman** [Microsoft/vscode#58775]
@ivankravets, re #https://github.com/platformio/platformio-vscode-ide/issues/339

Issue Type: <b>Bug</b>

to repro:
- fresh VS install
- install `ms-vscode.cpptools`
- disable `ms-vscode.cpptools`
- install `platformio.platformio-ide`

NOTE: installation is successful, no error. however, the extension fails to activate:
```
console.ts:136 [Extension Host] Extension 'platformio.platformio-ide' failed to activate. Reason: unknown dependency 'ms-vscode.cpptools'.
```

1) there should be messaging that indicates to the user that required dependency extensions are disabled, and installing the extension would likely result in failure.
2) also, there should be an option, when installing, to enable the full tree of disabled dependency extensions.

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:18.328Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Quad CPU           @ 2.66GHz (4 x 2671)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|8.00GB (3.79GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe E:\play\p5.js|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.5.6
beautify|Hoo|1.4.3
cpptools|ms-|0.18.1
platformio-ide|pla|1.2.0
ts-extract-interface|ril|0.1.2
stylelint|shi|0.43.0
shader|sle|1.1.3

</details>

**Comment by sandy081** [comment]
@roblourens You are right. But it is same as installing a dependency extension. I would not like to introduce prompts and go this as default behaviour.
