### ISSUE TITLE
Why do the files that do not exist in the "problem" suggest a lot of errors?

### ISSUE THREAD

**Issue by wanghaooo** [Microsoft/vscode#58779]
This problem has been confusing me for a long time. These files are not in my project. I can't find them, but I will report a lot of errors. Maybe these are compiled cache files? So how do I eliminate these error tips?
<img width="1091" alt="2018-09-17 1 00 56" src="https://user-images.githubusercontent.com/26863173/45606791-a3b31880-ba7a-11e8-87a9-d906f52c1bdc.png">

**Comment by wanghaooo** [comment]
These errors do not affect my project running and compiling, but it is always there and cannot be eliminated.

**Comment by joaomoreno** [comment]
Which extensions are you running? Can you figure out which extension causes these errors?

**Comment by joaomoreno** [comment]
Does the problem reproduce with `--disable-extensions`?

**Comment by joaomoreno** [comment]
Yep, this is coming Gitlens: https://github.com/eamodio/vscode-gitlens/blob/14e2aa67bfcd432a6b5af297cd5c20aafc182600/src/git/git.ts#L206

@eamodio Any chance we can use the TextDocumentProvider API there?

**Comment by eamodio** [comment]
Yup, the next version of GitLens will fix this (although I went with implementing a FileSystemProvider rather than a TextContentProvider). Unfortunately it's all part of a large set of changes coming to GitLens but I'm hoping to have an alpha version ready soon.

**Comment by wanghaooo** [comment]
So is this a problem with Gitlings? After careful recall, it seems that this problem has occurred since the installation of Gitlens, but I can not reproduce this problem, because sometimes there are a lot of errors and sometimes not, after I close the editor to restart, there will be no error. Then, after a few hours, a lot of errors were reported.

**Comment by eamodio** [comment]
Yeah, the issue is currently GitLens uses temp files when viewing diffs of revisions. And the language services see these temp files and try to analyze them. The next version won't create any temp files so this won't happen anymore.

**Comment by wanghaooo** [comment]
I understand, thank you for your answer. ^_^
