### ISSUE TITLE
Watch for auto compilation of typescript file not working well

### ISSUE THREAD

**Issue by Brakkar** [Microsoft/vscode#5878]
- VSCode Version: 1.0
- OS Version: OSX 10.11.4

Hi,
here is the code of my tasks.json:

{
	// See http://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "0.1.0",
	"command": "tsc",
	"isShellCommand": true,
	"args": ["-w", "-p", "."],
	"showOutput": "always",
	"isWatching": true,
	"problemMatcher": "$tsc-watch"
}

 But the compilation of ts to js and map is really random. I edit a file, and nothing happens. I must force build, or save file for the compilation to happen. Could it be a bug or a problem with my settings ?.

**Comment by bpasero** [comment]
@dbaeumer I assume this is not our file watcher doing the watching but the tsc?

**Comment by Brakkar** [comment]
Quite possibly, I followed the instructions, not sure how to enable your file watcher ?

**Comment by Brakkar** [comment]
So is this a setting problem or a bug ? tks

**Comment by dbaeumer** [comment]
I rely on the tsc watcher here. 

@Brakkar which version of tsc are you using (run tsc --version). And do you expierence the same behavior when starting tsc directly in a terminal for this project.

**Comment by Brakkar** [comment]
@dbaeumer 

tsc --v
Version 1.8.10

On the terminal I ran "tsc" from within project directory, the compiler did its job. But editing and saving files subsequently from vscode didn't trigger an rebuild.

**Comment by dbaeumer** [comment]
@Brakkar just to be sure. When you edit and save files in VS Code is the built triggered in the terminal running tsc? 

To make sure things do not infer please don't start the task inside VS Code.

**Comment by Brakkar** [comment]
@dbaeumer No. I when into terminal folder, ran tsc. Got correct build message (that contains error related to my code). Then went into vscode, made some saves.... but the rebuild didn't happen in terminal.

**Comment by dbaeumer** [comment]
@Brakkar thanks. This then sounds like a watching problem with the tsc compiler. In the terminal you started tsc with tsc -w -p .

**Comment by Brakkar** [comment]
@dbaeumer On terminal, when I launch tsc -w -p it says "Compiler option 'project' expects an argument."
When I run 'tsc -w' it DOES auto compile on the terminal when i save file. It didn't auto compile in the terminal previously because I only launched with 'tsc'.

In vscode 1.1.1, it's the same: after launching the first build with shift+command+b it builds and watches for changes. But it then rebuilds only when I save files. Isn't it supposed to auto rebuild without needed a save ?

For a reminder, here are my options in tasks.json:

{
// See http://go.microsoft.com/fwlink/?LinkId=733558
// for the documentation about the tasks.json format
"version": "0.1.0",
"command": "tsc",
"isShellCommand": true,
"args": ["-w", "-p", "."],
"showOutput": "always",
"isWatching": true,
"problemMatcher": "$tsc-watch"
}

**Comment by dbaeumer** [comment]
@Brakkar Sorry, the correct command line should have been tsc -w -p . 

tsc currently only support recompile on save. We don't support recompiling on type. However VS Code support auto save which goes then nicely with tsc in watch mode.

Any objection to close this issue?

**Comment by Brakkar** [comment]
@dbaeumer ok thanks, everything is clear now. I will post a suggestion on uservoice.
Maybe this should be clarified in the docs on the site, unless I missed it.
