### ISSUE TITLE
side bar content chooser when activity bar is hidden

### ISSUE THREAD

**Issue by SailorMax** [Microsoft/vscode#58787]
Can you replace side bar title with side bar content chooser when activity bar is hidden to leave possibility to switch, for example, from Explorer to SCM without hotkeys or menu.

thank you.

**Comment by isidorn** [comment]
I understand the need for this, however it is not on our immediate plan to tackle this thus closing.
I personally use this setup and hotkeys do the job for me.
I do not like adding a mini activity bar if you have hidden the activity bar
