### ISSUE TITLE
Autosave does not set checkbox in the first time

### ISSUE THREAD

**Issue by oneslash** [Microsoft/vscode#58788]
Issue Type: <b>Bug</b>

1. Open vscode
2. Click File -> Autosave
3. Open File menu and see that it is not checked

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:04:11.329Z)
![untitled](https://user-images.githubusercontent.com/15870134/45611705-a30d8880-ba60-11e8-85d4-0979bd1158f3.gif)

OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 6, 6|
|Memory (System)|16.00GB (1.81GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
gitignore|cod|0.5.0
vscode-eslint|dba|1.6.0
ansible-vault|dho|0.1.3
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.39
php-debug|fel|1.12.5
php-intellisense|fel|2.3.5
php-pack|fel|1.0.2
ansible|haa|0.2.8
terraform|mau|1.3.4
python|ms-|2018.8.0
Go|ms-|0.6.89
debugger-for-chrome|msj|4.10.1
vscode-docker|Pet|0.2.0
jenkinsfile-support|sec|0.1.0

</details>

**Comment by bpasero** [comment]
@oneslash does this reproduce all the time reliably?

Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by oneslash** [comment]
@bpasero cannot reproduce it this time, let's close the issue for now.
