### ISSUE TITLE
Gulp tasks aren't detected

### ISSUE THREAD

**Issue by Xarkam** [Microsoft/vscode#5879]
- VSCode Version: 1.0
- OS Version: Win10 x64

Steps to Reproduce:

1. Make gulpfile.js on the root project folder.
2. Make tasks.json for vscode
3. ctrl+shift+P, type run task or task and nothing appear.

![image](https://cloud.githubusercontent.com/assets/331816/14846691/5a4d4d34-0c65-11e6-9592-027beeff81b2.png)
![image](https://cloud.githubusercontent.com/assets/331816/14846725/81e3871e-0c65-11e6-9014-035a2603071d.png)

**Comment by SamVerschueren** [comment]
Might be missing something here but why do you need the `tasks.json` file? `gulp` tasks are automatically picked up by VS Code.

As you can see, I didn't define a `tasks.json` file, I only have a `gulpfile.js`.

![task](https://cloud.githubusercontent.com/assets/1913805/14910248/09a99b52-0dec-11e6-8b31-478276e4ec2c.gif)

**Comment by Xarkam** [comment]
Ok I see. This is because VScode are automatically in french and I need to type "tâches" on place of tasks.

It is very disturbing to have the commands in French;)

I look of pass vscode in english ^^
