### ISSUE TITLE
Run task in external terminal

### ISSUE THREAD

**Issue by MeikTranel** [microsoft/vscode#58790]
Issue Type: <b>Feature Request</b>

Just like the launch.json supports the ability to host the application, i would like to be able to host my tasks in an external console window. Some console workloads i have are to heavy for xTerm.js and the ability to accidentally kill one of those processes when killing terminal processes with the trash can button is a little bit annoying.

VS Code version: Code - Insiders 1.28.0-insider (cd9d71a31f731baf17330a84448c3efdeabc873f, 2018-09-17T05:20:06.620Z)
OS version: Windows_NT x64 10.0.17134

**Comment by dbaeumer** [comment]
This will have the downside that we will not be able to capture any output and detect problem markers in the output.
