### ISSUE TITLE
http-equiv="X-UA-Compatible" in 2018

### ISSUE THREAD

**Issue by web2033** [Microsoft/vscode#58796]
Do we still need

`<meta http-equiv="X-UA-Compatible" content="ie=edge">` 

that ships with Emmet => `! tab` ?

**Comment by ramya-rao-a** [comment]
We use the emmet snippets from an upstream emmet project.
Please log the issue at https://github.com/emmetio/snippets.
Once it is resolved there, we can absorb the changes in VS Code

**Comment by web2033** [comment]
There's no "Issues" tab on that repo.

**Comment by ramya-rao-a** [comment]
@web2033 Try https://github.com/emmetio/expand-abbreviation
