### ISSUE TITLE
Option to enable extension for workspace files only

### ISSUE THREAD

**Issue by vladimir-didenko** [Microsoft/vscode#58797]
Right now there is no way (or may be I am wrong but I googled hard) to enable extension for workspace files only. Sometimes it leads to really annoying results
1. If you open source file that is out of project just to check content then language extension activates unconditionally and highlights half of content by red underlines (half of scrollbar is also red) because there is no settings configured for this files.
2. It is especially annoying when extension becomes active for temporary files. E.g. GitHistory extension generates temporary files that are processed by cpp-tools. Then you close temporary files and trying to jump to function definition (F12) - vscode could easily jump to temporary file ( though it shows main file in alternative list).

**Comment by sandy081** [comment]
Extensions runtime behaviour is scoped per window but not per files or folders. Not sure if it can be done.

**Comment by alexandrudima** [comment]
@vladimir-didenko The contract we have on VSCode's side is the following: if you open a certain file type, e.g. a `.py` file, we will send an activation event `onLanguage:python` and then extensions get activated. Take, for example, the JSON or the CSS language services we have. They work fine regardless if the file you open is from the current workspace, the current folder, or not...

The extensions themselves are then responsible for analyzing the file, figuring out if the file belongs to a project, etc.

I suggest you reach out directly to the author(s) of the extension you are using and explain your use-case and check with them how it would be possible to define a project or some other means of limiting their processing of temporary files.
