### ISSUE TITLE
code --inspect-brk-extensions is broken

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#58798]
* start code via `code --inspect-brk-extensions=9988`
* 🐛 the extension is *not* paused

This happens because there is an explicit check for the extension host development case here: https://github.com/Microsoft/vscode/blob/eabec00675ec0bc6f47b911cf9a656d3c03ec0c9/src/vs/workbench/services/extensions/electron-browser/extensionHost.ts#L94-L99

**Comment by jrieken** [comment]
Appart from not being able to debug the startup sequence anymore it also breaks `--prof-startup`

**Comment by weinand** [comment]
And you are seeing this issue in the case where no "extensionDevelopmentPath" is passed as a CLI argument, right?
