### ISSUE TITLE
Ext Host unresponsive warning when open file

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#58794]
* use todays insiders
* open `marked.js` from our workspace
* you get an unresponsive info tho the extension host seems to be snappy

<img width="519" alt="screen shot 2018-09-17 at 10 22 34" src="https://user-images.githubusercontent.com/1794099/45614153-d522e880-ba68-11e8-97e3-2c34f25b6994.png">

**Comment by alexandrudima** [comment]
From debugging, this might happen if the last request takes a very long time. We saw a reproducible case where the TS server was busy and then the last request, for code actions was taking more than 10s to resolve.
