### ISSUE TITLE
Boolean settings can't be un-set at workspace level using new settings editor if set at user level

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#58791]
If I have `formatOnSave: true` in my user settings but want to disable it for a specific workspace, I can do it by setting `formatOnSave: false` in my workspace settings json file, but I can't do it via the settings editor - it only allows tick/untick, and unticking it just removes the setting, it does not explicitly set it false.

I think there should be some way to override a boolean setting with a false in the workspace settings editor.

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/58038
