### ISSUE TITLE
executeDocumentSymbolProvider no longer returns full (flat) list (Insiders)

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#58793]
In current stable, the `executeDocumentSymbolProvider` command returns a flat list of symbols (as `SymbolInformation`) even when the provider gives them as a tree of `DocumentSymbol`. In Insiders, as far as I can tell we only get back the top-level results but they still claim to be `SymbolInformation`.

If I inspect the values, they do seem to have the children in the underlying objects, but they seem to be typed as SymbolInformation which has no `children` property:

```ts
const a = await vs.commands.executeCommand("vscode.executeDocumentSymbolProvider", currentDoc().uri);

a[0] instanceof vs.DocumentSymbol
false
a[0] instanceof vs.SymbolInformation
true
a[0].children
Array(11) [r, r, r, r, r, r, r, r, …]
```

I'm not sure what the correct way is for me to enumerate these. Should they be returned as `DocumentSymbols`?

@jrieken Maybe slightly related to https://github.com/Microsoft/vscode/issues/52874#issuecomment-400215870. Should `instanceof vs.DocumentSymbol` here be returning `true`?

**Comment by DanTup** [comment]
Looks like just casting them to `DocumentSymbol` works - they have properties from both types (eg. `location` and `range`), so I think probably whatever is causing `instanceof` to show the wrong type just needs fixing. I'll change code to treat them as `DocumentSymbols`.

This might be a breaking change; but I don't know if anyone is really using this API for anything outside testing (that's all I'm using it for).

**Comment by DanTup** [comment]
The new behaviour in Insiders only returns the top level items which means we have to treat them as `DocumentSymbol` in order to traverse the children (but it feels weird for `instanceof` to be wrong in that case).

I think probably either:

1. The API should continue to flatten the list (eg. the API continues to be `SymbolInformation` and is always flat - as it is today in Stable)
2. The `instanceof` should match what was returned by the provider (eg. the consumer can use `instanceof` checks to detect a `DocumentSymbol` and then access `.children`)

**Comment by liangya123** [comment]
sss

**Comment by jrieken** [comment]
> The instanceof should match what was returned by the provider (eg. the consumer can use instanceof checks to detect a DocumentSymbol and then access .children)

This falls apart as soon as you have mixed results

> SymbolInformation but you must cast them so you can access the children.

Technically you are not casting anything but you simply trust that the returned objects are `DocumentSymbols` and you start using them like that.

**Comment by DanTup** [comment]
> This falls apart as soon as you have mixed results

I don't understand why - if it's valid for the provider to return mixed results, why can't this call?

> Technically you are not casting anything but you simply trust that the returned objects

Yeah, I understand - but it'd feel much nicer if I was treating it as the type that `instanceof` claimed it was. It feels really weird to return `DocumentSymbols` from the provider, then get `SymbolInformation`s (according to `instanceof`) back, but have to treat them as `DocumentSymbol`s to actually access the full list.

If they're going to be return as if they were `SymbolInformation`s for compatibility reasons, surely the full list should be supplied for compatibility reasons? The change is already breaking (only the top level ones come through now, in stable the full flattened list comes back) so it makes sense to break it properly and have a clean API at the end IMO.

**Comment by jrieken** [comment]
> The change is already breaking (only the top level ones come through now, in stable the full flattened list comes back) so it makes sense to break it properly and have a clean API at the end IMO.

Disagree. There are IMO two use-cases

1. *Your provider, your unit test*: You have one provider for fooLang and you use the command to expect that data to be the data you have computed. If your *existing* code has an instanceof-check it still works and is not broken. Your new code will not pass the instanceof-check but will have the proper data. No problem
2. *Forgein providers, your feature*: You have an extension that does something with document symbols like printing them to a document. What you print is out of your control, it depends on the providers the user has installed. Yes, data is now hierarchical but that's closer to the truth than an artificially flattened list. Also, you can produce a flat list from a hierarchy with ease but the other way around isn't possible anymore. 

I know this isn't ideal but a reasonable default which is the most stable of all solutions. The requirement is that the new API  (hierarchy of document symbols) is reflected in the API command and a little change is to be expected here.

**Comment by DanTup** [comment]
I guess I don't understand why changing `instanceof` to be the correct type isn't a good fix. People with old code are not doing `instanceof` checks (since there was never any need) and anyone who is doing an `instanceof` check is trying to handle both types. As I see it, fixing `instanceof` doesn't break anybody but it does allow consuming the API in the way people would expect.

That said, I respect you're way better placed to decide (and more invested in the API) than I am so if I haven't convinced you yet, I probably won't. Thanks for reading and responding anyhow!

**Comment by Coder-256** [comment]
@jrieken Please reconsider restoring the old behavior. This broke the tests for [Vetur](https://marketplace.visualstudio.com/items?itemName=octref.vetur), the [15th most downloaded](https://marketplace.visualstudio.com/search?target=VSCode&category=All%20categories&sortBy=Downloads) extension on the entire marketplace, when these changes landed in 1.28 stable.

**Comment by jrieken** [comment]
Did you consider updating your tests? Symbol provider can now create a hierarchy and that should be honoured IMO

**Comment by Coder-256** [comment]
@jrieken I already submitted a PR to update the tests, but for now they're still broken. I agree that the new API is better designed, but this should have been an additive change rather than breaking tests without notice.

**Comment by jrieken** [comment]
>  but this should have been an additive change rather than breaking tests without notice.

The problem is that tests are written using the `vscode.xyz` commands. Their result reflect what the UI shows not what providers return, e.g sorting & merging has happened, invalid result items might have been dropped etc which makes then a bad fit for a unit test. 

If you are testing your provider why not call it straight away? Why go through a command first?

**Comment by jrieken** [comment]
> that they were supported

They were not supported/designed for testing - they worked under an assumption that isn't correct. 

>  so in this case testing the UI is more important IMO to make sure that 

If you think that is important then you have to live with such changes. I think testing something you don't control isn't feasible. IMO you should stop testing where the API contract ends - we ask for data and we manage the representation, you should trust us to get that right - in the same way we trust (and not test) chromium to render the html correctly.

**Comment by Coder-256** [comment]
Sorry, I was unaware that these methods were unsupported. That was not made at all clear from [the documentation](https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands). Full disclaimer: I did not write the original code that used those APIs.

Anyway I think we'll have to agree to disagree about "trust". In my opinion: since all code can have bugs, it is always important to test that other peoples' software works with yours. In fact, such testing is *especially* important because issues with dependencies are more likely to go unnoticed, but as a developer I am still responsible for making sure that my product as a whole works as expected, rather than just the parts that I write. *My* code working as expected is not enough; any issue with a dependency will also affect my product. I cannot rely on other peoples' code to be bug-free; almost no code is ever bug-free, no matter how well written; and bugs in code I use can cause bugs in my software. Therefore it is vitally important to do UI/E2E testing in order to ensure that things actually work in practice. For instance, if VS Code were to ship a stable version that crashed because of a bug in Chromium, it would still be Microsoft's problem to fix and roll back the changes until they are fixed. This is just my opinion.
