### ISSUE TITLE
Untitled: reveal when saving

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#58799]
When saving untitled files, we should open them in the background so that a filename can more easily be determined based on the contents. Extracted from https://github.com/Microsoft/vscode/issues/37414

**Comment by isidorn** [comment]
Verification steps?
If I just save an untitled file I see no difference than before

**Comment by bpasero** [comment]
@isidorn open multiple untitled files and trigger "Save All". at each dialog that opens, the file in the background should become active that is being saved.
