### ISSUE TITLE
Count of currently visible lines in current Editor

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#588]
_From @jsturtevant on October 26, 2015 23:25_

Is there an API or way to detect which lines are visible in the current editor?

In a large file if i use 

``` typescript
let count = doc.getLineCount();
```

I get all the count of all the lines in the document but I my case I need to restrict my search to only the current visible lines.  In the example below I would get a count of 35 lines although the file is 90+.

![image](https://cloud.githubusercontent.com/assets/648372/10745288/bae66598-7c16-11e5-8337-641032000ba7.png)

_Copied from original issue: Microsoft/vscode-extensionbuilders#63_

**Comment by seanmcbreen** [comment]
I'm not aware of such an API sorry we should add it to the backlog.

**Comment by seanmcbreen** [comment]
_From @jrieken on November 3, 2015 11:31_

@jsturtevant Just that we get a better understanding of the requirement, what would you use such an API for?

**Comment by jsturtevant** [comment]
My extension is only interested in the text that is currently visible in the editor.  If it is not visible I do not need to work with those lines.  At a basic level, Given user input I am highlighting anything that is visible inside the current editor that matches the request,  if is not visible I do not need to highlight it.  I think there are many ways to meet the requirement, not only through line count.  Let me know if you need/want more clarification.

**Comment by jrieken** [comment]
Yeah, is it for performance reasons that you want that? You can use the decorations api for highlighting parts of the editor content and you wrt perf shouldn't need to care if the lines are visible or not

**Comment by jsturtevant** [comment]
Not for performance reasons.  I am providing shortcuts to jump around the visible screen.  If the text is not on the screen then numbering would be off,  which is not a huge deal if there isn't a way to determine the text is visible but would be ideal to not skip letter.  Here is a screen shot from my extension in Visual Studio 
 
![image](https://cloud.githubusercontent.com/assets/648372/11910282/98a92e14-a5c1-11e5-9b01-939d02f1aae0.png)

**Comment by rnordin100** [comment]
Skip

**Comment by wmaurer** [comment]
@jrieken I'm also looking for the ability to determine the current visible lines in the current editor. And yes, for performance reasons, as I want to do a text search only over these lines. Searching the entire document in the text editor would be unnecessary and potentially bad for performance, especially if the document is large.

**Comment by wmaurer** [comment]
@jrieken further info, this feature would be specifically useful for my [Jumpy](https://github.com/wmaurer/vscode-jumpy) extension, where I have to hard code (or provide as a user setting) how many lines back and forward from the current cursor position to search.

**Comment by jrieken** [comment]
Sorry, no update yet. @alexandrudima would be the man to talk to. We haven't made decision how to forward with this request

**Comment by wmaurer** [comment]
Ok, thanks @jrieken. @alexandrudima, it'd be awesome if you could keep this issue updated on the possibility of this feature.

**Comment by CoenraadS** [comment]
https://github.com/Microsoft/vscode/issues/14756#issuecomment-423148870
