### ISSUE TITLE
color theme doesn't affect status bar

### ISSUE THREAD

**Issue by zxeoc** [Microsoft/vscode#5880]
- VSCode Version: 1.0.0
- OS Version: Windows 10 / Ubuntu Mate 15.10

Steps to Reproduce:

1. File-Preferences-Color Theme

no matter which theme is selected( except "High Contrast"), the status bar remains purple

**Comment by bpasero** [comment]
Currently we do not support theming of the entire workbench but there are feature requests open for it.
