### ISSUE TITLE
chain colorize not right

### ISSUE THREAD

**Issue by natqe** [Microsoft/vscode#58803]
- VSCode Version: 1.27.2
- Windows Version: 10

source code:
```typescript
  readonly options: string[] = _.map(this.objects, 'name').
    concat('Blob', 'Time', 'String', 'Boolean', 'Date', 'Datetime', 'Decimal', 'Double', 'ID', 'Integer', 'Long', 'Object')
```

In the ide it doesn't look good.
See via screenshot: [https://i.imgur.com/Ju6cok4.png](https://i.imgur.com/Ju6cok4.png)

**Comment by octref** [comment]
From the `readonly` keyword I guess you are using TypeScript? If so please report issue at: https://github.com/Microsoft/TypeScript-TmLanguage.

**Comment by natqe** [comment]
@octref but it doesn't connect especially to typescript, its connect also to javascript

**Comment by octref** [comment]
That repository is for both JS/TS. You can just open an issue there.
