### ISSUE TITLE
'Extensions' is with project icons, but it belongs with Settings

### ISSUE THREAD

**Issue by mikemaccana** [Microsoft/vscode#58805]
On the left of vscode is:

 - Explorer - project specific
 - Search - project specific
 - Source control - project specific
 - Debug - project specific
 - Extensions - specific to vscode
 - [SPACER]
 - Settings - specific to vscode

It would be more logical to move Extensions to be with Settings

 - Explorer - project specific
 - Search - project specific
 - Source control - project specific
 - Debug - project specific
 - [SPACER]
 - Settings - specific to vscode
 - Extensions - specific to vscode

![image](https://user-images.githubusercontent.com/172594/45619771-72364f00-ba72-11e8-9846-76f120e9facf.png)

**Comment by sandy081** [comment]
@ramya-rao-a I remember this was already brought up once (may be in planning or UX call). Do you have the reference to the dup?
