### ISSUE TITLE
No snippets suggestion on long lines beyond character 100

### ISSUE THREAD

**Issue by jlelong** [Microsoft/vscode#58807]
The snippet suggestions mechanism stops working passed character 100. See the two following screenshots. When the cursor is before character 100
![capture d ecran 2018-09-17 a 13 39 45](https://user-images.githubusercontent.com/2910140/45621213-dc092580-ba7f-11e8-9490-85d2a61b8026.png)

When the cursor is after character 
![capture d ecran 2018-09-17 a 13 40 07](https://user-images.githubusercontent.com/2910140/45621204-d4498100-ba7f-11e8-8837-dd11f5264238.png)

- VSCode Version: 1.27.2
- OS Version: OSX 10.13.6
Does this issue occur when all extensions are disabled?: Yes

Steps to reproduce: 

1. open a `.md` file
2. type in 
```
This is a very long line going with more 100 characters and this makes intellisense become a little crazy.
```
3. Test snippet insertion on various places (before and after character 100)

The same problem occurs with all the filetypes I have tested.

**Comment by jrieken** [comment]
Thanks for reporting this @jlelong! I have just pushed a fix which will be in tomorrows Insider build. Please give it a try: https://code.visualstudio.com/insiders/ #HappyCoding!
