### ISSUE TITLE
Let me decline the recomendations

### ISSUE THREAD

**Issue by AndreasGrip** [Microsoft/vscode#58808]
Issue Type: <b>Feature Request</b>

It would be very nice to be able to mark a recomended extension as "unwanted" at least for a period of time. It's ALMOST as annoying as the android naging about activate 'ok google'

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.16299

**Comment by ramya-rao-a** [comment]
To disable recommendations for individual file types or workspace recommendations, use the "Dont show again" option

![image](https://user-images.githubusercontent.com/16890566/45653926-838d5480-ba8e-11e8-8dc5-51cd5e912536.png)

To disable recommendations in the extensions viewlet under the "Recommendations" section, 
see [Dismiss Recommendations](https://code.visualstudio.com/updates/v1_25#_dismiss-extension-recommendations)
