### ISSUE TITLE
PlatformIO Extension Does Not Complete Installation

### ISSUE THREAD

**Issue by jurgenbeck** [Microsoft/vscode#58813]
- VSCode Version: 1.27.2
- OS Version: macOS 10.13.6

The issue occurs when in a new VSCode installation the Git update modal dialog appears in the lower right-hand corner. This prevents the PlatformIO extension to not fully install until the Git update modal dialog is closed. However, the dialog appears as just a notification panel and is not suspected as a dialog that prevents other processes to finish.

This causes the user to wonder why the PlatformIO extension UI elements and functionality is not present in VSCode.

Steps to Reproduce:

1. Install VSCode
2. Install a new extension
3. If Git update notification modal dialog appears, don't confirm or close it

Does this issue occur when all extensions are disabled?: No

**Comment by sandy081** [comment]
@jurgenbeck May I know if you are getting a native dialog like this one

![image](https://user-images.githubusercontent.com/10746682/45673248-7c1b8900-bb2a-11e8-861e-c35d1063c7fa.png)

or a prompt like 

![image](https://user-images.githubusercontent.com/10746682/45673282-8dfd2c00-bb2a-11e8-914d-8f0450bb8d53.png)

**Comment by jurgenbeck** [comment]
It was the second (dark) prompt sitting in the lower right-hand corner, thus the confusion. If it had been a native dialog, it would have been clear what to do, as the application would not have let me continue. With the second dialog, it appeared to give me a choice whether to complete it now or at another time and not something that interfered with the successful install completion of the PIO extension.

**Comment by sandy081** [comment]
@jurgenbeck Can you please let me know what dialog from Git it is? Also set the log level to trace and get the logs (shared process) from output channel while you are doing it.
