### ISSUE TITLE
Intellisense stops working after a brief period

### ISSUE THREAD

**Issue by keithoconor** [Microsoft/vscode#58812]
Issue Type: <b>Bug</b>

Editing C# using OmniSharp, I can use Intellisense for a brief period of time, but after ctrl-clicking to follow a few links and then returning to the first document, intellisense fails and then stops working for all documents. 

This happened some time in the last two weeks, and started affecting everyone in the office at the same time. We use VSCode to edit .csharp projects generated by Unity 2018.2. 

I've tried using and old version on OmniSharp (1.30.0) but the issue persists.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1800X Eight-Core Processor          (16 x 3593)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.93GB (45.52GB free)|
|Process Argv|C:\Users\keith\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.1.0
bracket-pair-colorizer|Coe|1.0.60
csharp|ms-|1.16.1
vscode-icons|rob|7.26.0
copy-copy-paste|roc|0.0.6
brscript|Ron|0.9.0
code-settings-sync|Sha|3.1.2
perforce|sle|3.1.0
vscode-hexdump|sle|1.6.0
code-spell-checker|str|1.6.10
vscode-lua|tri|0.12.4
unity-debug|Uni|1.3.0

</details>

**Comment by Tyriar** [comment]
https://github.com/OmniSharp/omnisharp-vscode
