### ISSUE TITLE
"Close Others" action isn't working

### ISSUE THREAD

**Issue by lannonbr** [Microsoft/vscode#58819]
Issue Type: <b>Bug</b>

1) Open two editors side by side
2) Right click on one and click on "Close Others" or press the keyboard shortcut (cmd+opt+t on mac)
3) See no editors close

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:04:11.329Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|16.00GB (1.75GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
quote-flipper|all|0.0.1
vscode-node-readme|ben|3.0.2
touch-bar-display|bla|1.1.1
vscode-standardjs|che|1.2.3
bracket-pair-colorizer|Coe|1.0.60
vscode-clock|Com|0.0.1
gitlens|eam|8.5.6
remotehub|eam|0.2.0
gitlab-workflow|fat|0.6.0
auto-rename-tag|for|0.0.15
vscode-js-annotations|lan|0.8.4
vscode-teddy-snippets|lan|1.0.1
debugger-for-chrome|msj|4.10.1
material-icon-theme|PKi|3.6.0
vscode-todo-highlight|way|1.0.4
zoombar-vscode|wra|1.0.0

(3 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
@lannonbr that command only operates within an editor group, not across.

**Comment by lannonbr** [comment]
Thanks @bpasero for the insight!
