### ISSUE TITLE
New TSX syntax highlighting bugs

### ISSUE THREAD

**Issue by frevds** [Microsoft/vscode#58810]
Issue Type: <b>Bug</b>

1. Something makes the syntax highlighting break in the line below, already in the itemIcon attribute. 
I couldn't find out exactly what, seems to do with the function (if I break the onRenderItemLink on a separate line it works), but reordering the itemIcon-Attribute sometimes shows it correct (sometimes means on position 1 it can be correct or incorrect depending whether I moved the second attribute before the first attribute or whether I moved the first one behind the second, which is weird since the result is the same). 

```tsx
const foo = <PivotItem itemKey={tabDef.ItemID.toString()} linkText={tabDef.Caption} title={tabDef.Tooltip} itemIcon={ tabDef.ItemID ? (tabDef.Image || null) : 'Add' } onRenderItemLink={ (props, defaultRenderer) => { const link = defaultRenderer(props); FormRenderUtil.makeDesignable(link, { file: tabDef, elementFlags: DesignerTargetElementFlags.None }, false, true); return link; } }>Foo</PivotItem>; 
```

![tsx](https://user-images.githubusercontent.com/5341447/45622274-b847de80-ba83-11e8-8098-f06222883f22.png)

2. An inline-comment followed after a switch statement is not being highlighted correctly: 

`
switch (refreshMode)  // discard and renew state per mode
`
![comment](https://user-images.githubusercontent.com/5341447/45622188-6c953500-ba83-11e8-854c-e132b8fd56c7.png)

Also applies to latest V1.27.2

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:18.328Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1505M v6 @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.86GB (17.49GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe -n|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.5.6
vscode-icons|rob|7.26.0

</details>

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/Microsoft/TypeScript-TmLanguage/issues/666 and https://github.com/Microsoft/TypeScript-TmLanguage/issues/667 to track these upstream
