### ISSUE TITLE
Steps suggestion doesn't work in place of  snippet

### ISSUE THREAD

**Issue by alexkrechik** [Microsoft/vscode#58811]
- VSCode Version: Version 1.26.1 (1.26.1) and Insider VSCode (Version 1.28.0-insider (1.28.0-insider))
- OS Version: OSX 10.12.6

Steps to Reproduce:

1. Enter some text to get suggestion with  `kind: CompletionItemKind.Function` string
2. Choose this string from suggestions list
3. Ensure, that cursor jumped to the some 'Suggestion' part
4. Enter some text to get some additional suggestion here

CR:
No suggestion appear in the 'suggestion' string part:
![No Suggestion](https://user-images.githubusercontent.com/5772406/45622194-d1ed2400-ba8b-11e8-86d4-226ee3e657a8.gif)
Issue appear in some of the last VSCode releases.

Does this issue occur when all extensions are disabled?: Can't check, due to I can get current suggestion/snippets variant using my extension alexkrechik.cucumberautocomplete only. But reproduced issue with all the other extensions absent.

**Comment by jrieken** [comment]
There is a setting for this. It's called `editor.suggest.snippetsPreventQuickSuggestions` and defines if quick suggestions appear when editing a snippet.
