### ISSUE TITLE
Resolve "restart" inconsistencies

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#58817]
Currently the debugger implementation has three ways to restart a debug session:
- EH debugging: new rawDS is created and old rawDS is abandoned; DebugSession stays the same, 
- restart without DAP restartRequest: DebugSession (and its rawDS) is terminated and new DebugSession (with new ID) is created with the heavy "startDebugging" API.
- restart with DAP restartRequest: DebugSession and rawDS is kept but if the preLaunchTask fails, and user requests to debug anyway a new DebugSession will be created on top of the still existing old DebugSession. This asks for trouble...

We need to fix this by following these principles and suggestions:
- the DebugSession and its ID must survive the restart. To achieve this we should use the EH Debugging as a model: [`DebugService.attachExtensionHost`](https://github.com/Microsoft/vscode/blob/01e438743cae9e16437f0f4b5da83bfcce48b860/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L399) shows what needs to be done to reuse the DebugSession. Basically it just replaces the rawDebugSession by a new one.
- Ideally `DebugService.restartSession` should become similar to `DebugService.attachExtensionHost` because they do the same thing (and serve the same UI button).
- [`DebugService.runTask`](https://github.com/Microsoft/vscode/blob/01e438743cae9e16437f0f4b5da83bfcce48b860/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L657) is used both for the postTask and the preLaunchTask but its implementation still assumes [here](https://github.com/Microsoft/vscode/blob/01e438743cae9e16437f0f4b5da83bfcce48b860/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L660) and [here](https://github.com/Microsoft/vscode/blob/01e438743cae9e16437f0f4b5da83bfcce48b860/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L671) that it is only meant for the preLaunchTask. `runTask` should better return a enum value to let its caller know what to do instead of doing it itself.

**Comment by isidorn** [comment]
First of all thanks for this great feedback.

I have cleaned up the restart in the following way:

- now the session is preserved across restarts in all cases
- there should be no different behavior between automatic / custom / manual restarts
- code looks cleaner and there is some minor code share between attach to extension host and restart
