### ISSUE TITLE
Missing SCM actions in insiders

### ISSUE THREAD

**Issue by sstoychev** [Microsoft/vscode#58820]
- VSCode Version: 1.28.0-insider
- OS Version: Windows 10

Version: 1.28.0-insider (user setup)
Commit: 7fcd81cd0f88bb2040f249b09cf6bdd83d9ea2ef
Date: 2018-09-17T09:37:55.086Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

![image](https://user-images.githubusercontent.com/11898259/45630704-dd4b4a00-baa1-11e8-9781-a8e0e9ef7f53.png)

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
What is the issue?

**Comment by joaomoreno** [comment]
Got it.
