### ISSUE TITLE
Emmet: Update Tag not working for js/jsx/react files

### ISSUE THREAD

**Issue by DBjelovuk** [Microsoft/vscode#58829]
- VSCode Version: 1.27.1
- OS Version: macOS High Sierra 10.13.5

Steps to Reproduce:

1. Run `Emmet: Update Tag` command in a react file

Does this issue occur when all extensions are disabled?: Yes

Resurgance of #20953.

**Comment by DBjelovuk** [comment]
Seems to be duplicate of #41618

**Comment by ramya-rao-a** [comment]
Closing this in favor of #41618. Please upvote #41618
