### ISSUE TITLE
onDidEndTaskProcess's callback is not always fired when a task exits quickly

### ISSUE THREAD

**Issue by g-arjones** [Microsoft/vscode#58828]
- VSCode Version: 1.27.2
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Register a callback using `vscode.tasks.onDidEndTaskProcess`
2. Execute a process (/bin/false) that returns a non zero code using `vscode.tasks.executeTask` API 
3. Check `event.exitCode` passed to the callback (should be non zero)

Does this issue occur when all extensions are disabled?: Yes

**Comment by g-arjones** [comment]
@jrieken @dbaeumer @bpasero Would anyone confirm this, please?

**Comment by dbaeumer** [comment]
This works for me under Windows using the following shell execution `exit 1`. 

task
```json
{
	// See https://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "2.0.0",
	"tasks": [
		{
			"label": "exit",
			"type": "shell",
			"command": "exit 1",
			"problemMatcher": []
		}
	]
}
```

code:

```typescript
    vscode.tasks.onDidEndTaskProcess((event) => {
        console.log(`Exit code ${event.exitCode}`);
    });

```

Output
```
Exit code 1
```

**Comment by g-arjones** [comment]
Could you try with a task provided by an extension? Also, I had the issue with a ProcessExecution, not sure if it works with a ShellExecution.... Will have a look

**Comment by dbaeumer** [comment]
Same if I contribute the task via a provider.

**Comment by dbaeumer** [comment]
I can reproduce under Linux. The reason is that the underlying terminal never signals a `terminal.processReady`  and to not send an unbalance begin/end pair a end process is not signaled either.

@Tyriar any insights why this never fires. Is there a different way for me to know when the process actually started.

**Comment by Tyriar** [comment]
@alexr00 recently touched this area, https://github.com/Microsoft/vscode/commit/a37adb6ba1d6a9973f9981c2f50adee24269f4f0#diff-dc09948028c646a458fac5f5b5d32276 prevents the process ID promise from firing, but only when the terminal exits immediately.

**Comment by g-arjones** [comment]
> but only when the terminal exits immediately.

Interesting, it seems that that is a different bug though (and that my bug report is not as accurate as it should have been).

The problem I was having was that killed processes are reported with exitCode == 0, which is obviously wrong. What I suggested as step to reproduce actually hits the other bug you mention (the callback is not fired at all).

Please, let me know if you guys would like me to open another issue for that...

**Comment by alexr00** [comment]
@g-arjones , can you share a task definition that you're seeing this with?

**Comment by g-arjones** [comment]
@alexr00 You could use [this...](https://github.com/g-arjones/vscode-task-provider-bug)

1. If you run the "Quick task" that is provided by that test extension you will notice that onDidEndTaskProcess callback is not fired at all (which is the bug @Tyriar) mentions..

2. If you run the "Slow task" and send a SIGTERM or SIGKILL to the task's process, you will notice that the callback is called with exitCode === 0, which is not expected (my original bug report).

Let me know if you need further details..

**Comment by sergei-dyshel** [comment]
I'm also experiencing that. Had to prepend `sleep 0.3` to my shell command (which fails immediately) for the event to be fired.

**Comment by g-arjones** [comment]
@alexr00 Did you get the time to have a look into this? Thank you!

**Comment by alexr00** [comment]
@g-arjones, I haven't been able to reproduce this with Windows. I'm trying with Linux next.

**Comment by alexr00** [comment]
@g-arjones, ok I can reproduce with Linux and I'm looking into it.

**Comment by g-arjones** [comment]
@alexr00 thanks a lot!

**Comment by alexr00** [comment]
The task exit code being 0 on Linux has been occurring since at least the beginning of September(went back and checked) so that isn't related to the change I made. This appears to be an upstream issue since 0 is the exit code that we're getting from node-pty.

**Comment by alexr00** [comment]
@g-arjones, as you can see I'm working on a change for the exit event not being fired.
For the exit code being 0, I did a bit of research and it looks like the exit code is correctly 0, it's the exit _signal_ that should be set. However, we don't currently expose the exit signal through vscode.tasks.onDidEndTaskProcess. If you want the exit signal (not available on Windows) then feel free to open a separate issue as a feature request 😄

**Comment by g-arjones** [comment]
> as you can see I'm working on a change for the exit event not being fired

Yes, I can see that. Thank you very much for the effort. :smile: 

> I did a bit of research and it looks like the exit code is correctly 0, it's the exit

Strictly speaking, on POSIX systems, if the process is killed there is no exit code ([or, to be precise, the exit code portion of the exit status is unset](https://www.systutorials.com/docs/linux/man/2-waitpid/#lbAG)). But the point is: returning 0 as exit code for processes that did not really exit is misleading for extension authors (and would be considered a bug by some, specially given that zero indicates sucess in this context). What shells typically do is return something greater than 127 to indicate that a process was signaled. So, couldn't you do something like that (setting exit code to an arbitrary high number) [here](https://github.com/Microsoft/vscode/blob/7a02ef771c35f5f2fbf9efa5a51ae822243b6f98/src/vs/workbench/parts/terminal/node/terminalProcess.ts#L77)? [node-pty provides the information you need for that.](https://github.com/Microsoft/node-pty/blob/7360eb70b16a9e0b122a33844be58769db21010a/typings/node-pty.d.ts#L57). On Windows that is a non-issue because the code is never 0 for terminated processes anyway...

/cc @dbaeumer @Tyriar @alexr00

**Comment by dbaeumer** [comment]
We could also use `null` to indicate that the process actually didn't provide an exit code.

**Comment by g-arjones** [comment]
Sounds good...

**Comment by alexr00** [comment]
@Tyriar, what is your preference on how we handle exit codes?

**Comment by alexr00** [comment]
New issue for the zero exit code: #62043.
