### ISSUE TITLE
Source Control Empty 

### ISSUE THREAD

**Issue by dhpdx** [Microsoft/vscode#58821]
Version: 1.27.2 (user setup)
Commit: f46c4c469d6e6d8c46f268d1553c5dc4b475840f
Date: 2018-09-12T16:17:45.060Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

### Steps to reproduce
With pending changes in Source Control, change the editor layout to two columns. Click Source Control and click on a file with current changes.

### Expected: 
The left column is split into two, with the far left column showing original code for your changed file, middle column showing your changes for your changed file, and the right column showing your unrelated file that was open.

### Actual:
The left and middle columns aren't showing anything except for line numbers. If you scroll  to the right in one of the blank columns sometimes the code appears, but disappears if you scroll back to the left.

![blanksource1](https://user-images.githubusercontent.com/1616159/45631025-f800cd00-ba67-11e8-8728-187054047643.PNG)

**Comment by joaomoreno** [comment]
Can you record a screencast? I can't really understand the issue.

**Comment by dhpdx** [comment]
![sourcecontrolblank](https://user-images.githubusercontent.com/1616159/45634851-74e47480-ba71-11e8-9138-43541f46fd57.gif)

It's a little hard to tell from this but scrolling left and right will sometimes make the code show, but clicking will make it disappear. This also only happens if full-screen.

**Comment by Aymanknalysis** [comment]
I am having the same issue since I run the last update for VSC. The version control tab is empty. Git is not within the extension although I installed it.   
![vc](https://user-images.githubusercontent.com/41392919/45643399-627a3300-ba91-11e8-84b6-7b604a059a44.PNG)

**Comment by joaomoreno** [comment]
@Aymanknalysis Please file a separate issue, don't jump on other issues.

@alexandrudima Something seems very off in this user's diff editor.

**Comment by alexandrudima** [comment]
Does this reproduce when running with `code --disable-gpu` ?

**Comment by dhpdx** [comment]
It's not quite the same but the text still disappears. I realized from testing this only happens in full-screen mode on my external monitor. Can't repro on main display at all.

![nogpu1](https://user-images.githubusercontent.com/1616159/45693800-df59eb00-bb2b-11e8-8ddc-905841b9c48a.gif)

**Comment by dhpdx** [comment]
@alexandrudima it looks like the issues stop if the horizontal window size is ~4940px or smaller.

**Comment by bpasero** [comment]
@dhpdx 
We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/code-exploration_1.28.0-1536650436_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/VSCodeUserSetup-x64-1.28.0-exploration.exe)
