### ISSUE TITLE
Go To Definition Not Working

### ISSUE THREAD

**Issue by Buhbooh** [Microsoft/vscode#58837]
Issue Type: <b>Bug</b>

Right Click on a custom type.  Click 'Go To Definition'. The top progress bar is infinitely active, and I am not taken to the class definition. 

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|15.64GB (3.23GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-npm-script|eg2|0.3.5
vscode-npm|fkn|3.3.0
PowerShell|ms-|1.8.4

</details>

**Comment by Tyriar** [comment]
What language are you using?

**Comment by beebeeep** [comment]
Same here, 1.27.2 @ MacOS X,  using Go with ms-vscode.go

**Comment by Tyriar** [comment]
@beebeeep no problem, also for future reference, any language-specific issues we redirect to the language extension. So https://github.com/Microsoft/vscode-go would have been the place to report that one.
