### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by abruestle** [Microsoft/vscode#58839]
Issue Type: <b>Bug</b>

On update to new version, VSCode does a Segmentation Fault error on trying 'npm install', 'ng serve', 'yarn install', 'node -v', 'env -i env', 'code -v', 'mkdir test', 'git add .'
cd is the only one that works (that I know of).
I tried even going back to a previous version of VSCode, but whatever it broke did not revert.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HK CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.87GB (17.01GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.4.3
compareit|in4|0.0.2
git-tree-compare|let|1.3.0
Angular-BeastCode|Mik|6.2.25
python|ms-|2018.8.0
debugger-for-chrome|msj|4.10.1
JavaScriptSnippets|xab|1.7.0

</details>

**Comment by bpasero** [comment]
@abruestle where are you typing these commands, in the integrated terminal? are you saying that typing "code -v" triggers this too?

**Comment by abruestle** [comment]
I was doing it in the integrated terminal. ...I have since learned though that this is a problem with Git Bash's Git/bin/bash.exe. ...So it can work if I use Git/git-bash.exe, but then the terminal is not integrated.

**Comment by abruestle** [comment]
And yes, code -v triggers it. Everything besides cd triggers it afaik.

**Comment by abruestle** [comment]
And now Git/git-bash.exe doesn't work either...

**Comment by Tyriar** [comment]
I'm guessing this was a change in Windows 10 and will be fixed when we replace winpty https://github.com/Microsoft/vscode/issues/45693

**Comment by yyynnn** [comment]
add args `"--login", "-i"`
https://stackoverflow.com/questions/50326422/vscode-terminal-windows-git-bash-aliases-getting-ignored
