### ISSUE TITLE
TSX React import defaults to "import =" syntax

### ISSUE THREAD

**Issue by dontsave** [Microsoft/vscode#58832]
Currently when vscode auto-imports react into a TSX file (upon detecting JSX markup for example), it uses the `import React = require("react");` syntax, which is unsupported by babel's transform typescript plugin. The does not appear to be a way to change the import syntax to use `import * as React from 'react'` syntax.

- VSCode Version: 1.27.2
- OS Version: Windows 10

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#27152
