### ISSUE TITLE
Basic one-line monaco editors are scrollable

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#58834]
Open settings UI or extensions viewlet, use the mousewheel on the search inputs

![image](https://user-images.githubusercontent.com/323878/45642803-326d6880-ba6e-11e8-9a81-c82160c4f0af.png)

![image](https://user-images.githubusercontent.com/323878/45642809-38fbe000-ba6e-11e8-9325-4cd6eeca3aff.png)

The editor has a 22px line inside a 20px container, changing its lineHeight from 22 to 20 fixes it, but I don't know why the editor is sized to 20px, @rebornix do you know?

![image](https://user-images.githubusercontent.com/323878/45642868-719bb980-ba6e-11e8-9474-72ee57a67e6b.png)

**Comment by rebornix** [comment]
Need some insights from @alexandrudima here, we tried to get the outer height of the editor from its container but I don't how we end up with `20` in our workbench.

**Comment by alexandrudima** [comment]
This can be controlled with the option `lineHeight` and with calling `editor.layout(w, h)`. i.e. configure `lineHeight: 20` and call `editor.layout(w, 20)`.

If you want the editor to get the height from its container, then you can scan for that height (`domNode.clientHeight`) and use it for both the `lineHeight` and the `layout` call.

**Comment by roblourens** [comment]
I didn't notice that, thanks!
