### ISSUE TITLE
Align the content of the html preview

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#5883]
1.1.0- alpha, from testing #5748 

 - create an extension that uses the htmlPreview command that shows just some text with some tags.(se code below)
 - The content of the HTML preview lacks a margin.

I'd suggest to always add the same margin as for the title label. The containing page could not and should not have to guess that.

![image](https://cloud.githubusercontent.com/assets/6461412/14847680/32fc9e2e-0c6a-11e6-8d81-df93e640e27f.png)

```typescript
'use strict';
import * as vscode from 'vscode';
export function activate(context: vscode.ExtensionContext) {
    let virtualDocumentUri = vscode.Uri.parse('speciale://authority/path');

    let disposable = vscode.commands.registerCommand('extension.sayHello', () => {
        vscode.commands.executeCommand('vscode.previewHtml', virtualDocumentUri).then(success => {
        });
    });
    let counter = 0;
    let eventEmitter = new vscode.EventEmitter<vscode.Uri>();
    let textDocumentContentProvider : vscode.TextDocumentContentProvider = {
        provideTextDocumentContent(uri) {
            return `Content of URI <b>${uri.toString()}</b>` + counter;
        },
        onDidChange: eventEmitter.event
    }
    
	let registration = vscode.workspace.registerTextDocumentContentProvider('speciale', textDocumentContentProvider);
    setInterval(() => {
        counter++;
        eventEmitter.fire(virtualDocumentUri);
    }, 5000);

    context.subscriptions.push(disposable);
}

```

**Comment by jrieken** [comment]
@bpasero Is there something I can inherit by the fact that html preview is an editor?

**Comment by bpasero** [comment]
We don't have a shared CSS rule for this yet, but could probably add it.

**Comment by testerez** [comment]
I guess that this issue is the reason why I have a sort of margin on the left of my content.
I'd like to have my content fill the entire viewPort of the previewHtml. It there any way to do it?
