### ISSUE TITLE
Telemetry service not finding machine ID

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#5884]
Testing #5691 
- VSCode Version: 1.0.0 stable & 1.1.0-alpha
- OS Version: Windows 8.1 & Windows 10
- Does not repro in: Windows 7

Our registry library fails to find the machine's ID in the registry for some reason...

![screen shot 2016-04-27 at 11 26 13](https://cloud.githubusercontent.com/assets/22350/14847850/1efbb710-0c6b-11e6-8b55-cd913c7210a7.png)

I do have the registry key.
## 

The latest version of `winreg` seems to give more details on the error

![screen shot 2016-04-27 at 11 31 52](https://cloud.githubusercontent.com/assets/22350/14847969/b4d1cf40-0c6b-11e6-8606-13a9dd65e256.png)

cc @bpasero

**Comment by joaomoreno** [comment]
We do seem to have plenty of empty ids in our telemetry data.

**Comment by joaomoreno** [comment]
@egamma I assigned it to you, as we need to find a telemetry champion.

**Comment by joaomoreno** [comment]
From my experience, interacting with the registry via spawning the command line registry tool is playing with fire. We should invest in a native API wrapper.

**Comment by bpasero** [comment]
Is this a regression from the update? maybe we always had this issue?

**Comment by joaomoreno** [comment]
Nah, not related to update. It repros in both stable and alpha. Alpha (which uses winreg 1.2.0) just returns better error messages.

**Comment by egamma** [comment]
Assigning to @kieferrm for triaging.

**Comment by ramya-rao-a** [comment]
We use the windows registry to get the sqm.machineId and this is specific to Windows.
We use the getmac module to get the machineid across platforms which eventually is used as THE machineid in telemetry reports.

Closing this issue as there is nothing I can see that we need to do here.
