### ISSUE TITLE
When saving file point to the location of explorer focus

### ISSUE THREAD

**Issue by moseleyi** [Microsoft/vscode#58840]
When I go to a particular folder in explorer and create new file when I press CTRL+S I would like the default path to be the folder I still have selected in my explorer, not the latest folder used.

Steps:

1. Go to a directory in your explorer, different then one that you worked with previously
2. Press CTRL+N to create new file
3. Press CTRL+S to save the file
4. The save path is the one used recently not the currently highlighted folder in the explorer

**Comment by isidorn** [comment]
Not sure if I would change this, however the save command would need to get this somehow from the explorer.
@bpasero thoughts? Where do you pass the folder for the save dialog?

**Comment by bpasero** [comment]
I am -1 for changing this btw. But fair feature request.

**Comment by moseleyi** [comment]
Totally understandable @bpasero 

I, on the other hand, use it to create files in many different folders and navigating through them every time I want to save a file is a bit of a pain. Would be nice to be able to configure this.
