### ISSUE TITLE
Extension runner is unresponsive.

### ISSUE THREAD

**Issue by mahburg** [Microsoft/vscode#58843]
Issue Type: <b>Bug</b>

Every few minutes a popup notification appears saying "Extension host is unresponsive" with 2 buttons. "Show running extensions" and "Restart Extension Host"

VS Code version: Code - Insiders 1.28.0-insider (7fcd81cd0f88bb2040f249b09cf6bdd83d9ea2ef, 2018-09-17T09:30:49.336Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|16.00GB (1.52GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_3089138|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
html-css-class-completion|Zig|1.17.1
html-snippets|abu|0.2.1
cypress-snippets|and|1.2.0
react-pure-to-class-vscode|ang|1.1.7
vscode-node-readme|ben|3.0.2
htmltagwrap|bra|0.0.7
react-food-truck|bur|1.0.2
simple-react-snippets|bur|1.2.2
vscode-exports-autocomplete|cap|0.5.4
nightcode|car|1.2.0
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.60
vscode-svgviewer|css|1.4.6
vscode-eslint|dba|1.6.0
vscode-npm-source|dku|1.0.0
githistory|don|0.4.2
gitlens|eam|8.5.6
vscode-npm-script|eg2|0.3.5
vscode-great-icons|emm|2.1.41
prettier-vscode|esb|1.6.1
css2react|got|0.0.6
beautify|Hoo|1.4.3
easy-icons|jam|0.3.1
dotenv|mik|1.0.1
python|ms-|2018.8.0
cpptools|ms-|0.18.1
vsliveshare|ms-|0.3.666
debugger-for-chrome|msj|4.10.1
indent-rainbow|ode|7.2.4
material-icon-theme|PKi|3.6.0
quicktype|qui|12.0.42
sass-indented|rob|1.4.9
vscode-javascript-booster|sbu|0.10.2
code-settings-sync|Sha|3.1.2
trailing-spaces|sha|0.2.11
vscode-fileutils|sle|2.10.3
code-spell-checker|str|1.6.10
pdf|tom|0.3.0
vscode-react-native|vsm|0.6.16
quokka-vscode|Wal|1.0.149
wallaby-vscode|Wal|1.0.93
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.9.0
JavaScriptSnippets|xab|1.7.0

</details>

**Comment by alexandrudima** [comment]
@mahburg @alexdevero This indicates that you have an extension that is consuming a lot of CPU and is unresponsive. In other words, one extension you have installed is going crazy and interfering significantly (blocking for more than 10s) the execution of other extensions.

Can you please go to `F1 > Developer: Running Extensions` and then hit the record button. Then, proceed to do what you are doing that triggers the high CPU usage. That will relaunch VS Code with the extension host in debug mode and then you can record and profile the extension host. You can view the results right in the editor (sorted by the extension that takes most CPU time at the top) and you can save the profile and report the problem to the extension that causes the high CPU usage.
