### ISSUE TITLE
Can't drag the scrollbar outside of the vscode window 

### ISSUE THREAD

**Issue by charlesg99** [Microsoft/vscode#58851]
On Arch Linux - gnome 3.30. Seems like in the latest version (1.27.2) the scrollbar can't be dragged while the cursor is outside of the vscode window. Not sure when this happened but it used to be possible. Without releasing the mouse button:

![peek 2018-09-17 20-58](https://user-images.githubusercontent.com/33044886/45658347-81da8580-babc-11e8-8fa9-f8b60db2c077.gif)

**Comment by alexandrudima** [comment]
No code change in there since >1yr. If this is a regression, then it must be caused by the Electron update.

**Comment by charlesg99** [comment]
Not sure if this is related or helps but the scrollbar works fine when the "release notes" are displayed.

**Comment by charlesg99** [comment]
It is fixed on 1.31.1
