### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by xiongxiaocui** [Microsoft/vscode#58856]
- Extension Name: debug-auto-launch
- Extension Version: 1.0.0
- OS Version: Darwin x64 17.7.0
- VSCode version: 1.28.0-insider

 We have written the needed data into your clipboard. Please paste:

**Comment by octref** [comment]
Please follow https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#reporting-issues for issues. Thanks!
