### ISSUE TITLE
Git: Support remote file systems

### ISSUE THREAD

**Issue by basictheprogram** [microsoft/vscode#58853]
<img width="57" alt="register-receipt_php_ _fuse_and_how_to_report_a_problem_with_visual_studio_2017_-_visual_studio___microsoft_docs" src="https://user-images.githubusercontent.com/6723257/45658544-2d7fd780-bab5-11e8-930a-6e2d03cbd1d5.png">
Issue Type: <b>Bug</b>

The source control icon on the left side of VSC always shows the busy or working icon.

```
Looking for git in: /usr/local/bin/git
Using git 2.19.0 from /usr/local/bin/git
> git rev-parse --show-toplevel
> git config --get commit.template
Open repository: /Users/tanner/projects/clients/CUSTOMER.com/FUSE
> git status -z -u
> git show :www.CUSTOMER.com/html/secure/undergraduate/contests/mcm/register-give-control-number.php
> git check-ignore -z --stdin
> git ls-files --stage -- www.CUSTOMER.com/html/secure/undergraduate/contests/mcm/
> git check-ignore -z --stdin
> git show :www.CUSTOMER.com/html/secure/undergraduate/contests/mcm/register-receipt.php
> git ls-files --stage -- www.CUSTOMER.com/html/secure/undergraduate/contests/mcm/
> git show :www.CUSTOMER.com/html/secure/undergraduate/contests/mcm/register-receipt.html
> git ls-files --stage -- www.CUSTOMER.com/html/secure/undergraduate/contests/mcm/
> git show :www.CUSTOMER.com/html/secure/undergraduate/contests/mcm/register-receipt.php
> git ls-files --stage -- www.CUSTOMER.com/html/secure/undergraduate/contests/mcm/
> git show :www.CUSTOMER.com/html/secure/undergraduate/contests/mcm/register-receipt.php
> git ls-files --stage -- www.CUSTOMER.com/html/secure/undergraduate/contests/mcm/
> git show :www.CUSTOMER.com/html/secure/undergraduate/contests/mcm/register-receipt.php
> git ls-files --stage -- www.CUSTOMER.com/html/secure/undergraduate/contests/mcm/
```

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:04:11.329Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.8.0
azure-account|ms-|0.4.3
PowerShell|ms-|1.8.4
vscode-docker|Pet|0.2.0
remote-vscode|raf|1.1.0

</details>

**Comment by joaomoreno** [comment]
Do you have any files open? Does it reproduce with `--disable-extensions`? Do you have any special file systems mounted?

**Comment by basictheprogram** [comment]
> Do you have any files open? Does it reproduce with `--disable-extensions`?

Yes, I can duplicate the problem with `--disable-extensions`

> Do you have any special file systems mounted?

Yes, the file system I am working on is CIFS mounted from a samba server running on Linux.

**Comment by joaomoreno** [comment]
> Yes, the file system I am working on is CIFS mounted from a samba server running on Linux.

That can explain it. Can you try on a local file system, does it reproduce there?

**Comment by basictheprogram** [comment]
Can duplicate the problem with sshfs mounted file system too.

Local filesystem works fine. 

What's odd is this worked fine before I upgraded to 1.27.2 (sorry, do not know what version I was running before the upgrade).

**Comment by DarthSpock** [comment]
I also use sshfs to remote to a Linux server that hosts my source code. So getting this working would be invaluable.

**Comment by joaomoreno** [comment]
This is now supported under VS Code Remote.

**Comment by WSLUser** [comment]
Great, we'll call a proprietary solution the "fix". What about users of sshfs or some other open-source ssh extension?
