### ISSUE TITLE
Go to function Definition is not working

### ISSUE THREAD

**Issue by AdeelBaloch** [Microsoft/vscode#58866]
Kindly fixe this issue 
this feature is most usefull 
i love VS Code 
i always hard with using visual code but this issue is westing my time
kindly fix it

**Comment by octref** [comment]
Please follow the issue reporting guideline: https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#reporting-issues.

**Comment by AdeelBaloch** [comment]
Kindly fixe this issue
this feature is most usefull
i love VS Code
i always hard with using visual code but this issue is westing my time
kindly fix it

**Comment by octref** [comment]
Please follow the issue reporting guideline: https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#reporting-issues.
