### ISSUE TITLE
Tab tooltip shows different contents based on exact mouse positioning

### ISSUE THREAD

**Issue by Adam13531** [Microsoft/vscode#58864]
Issue Type: <b>Bug</b>

Video repro: https://clips.twitch.tv/DeafHyperYamTinyFace

Text repro:
1. Open SCM
2. Click a file that has changes. Not sure if it matters, but my `workbench.editor.enablePreview` is `false`.
3. Hover over the resulting tab in the padding *beneath* the text in the tab.

Expected: it shows the same results as if you'd hovered over the text in the tab (which is the full path to the file)
Actual: it shows the text in the tab (which is just the name of the file). See the picture below for more information:

![image](https://user-images.githubusercontent.com/7192897/45669712-bd357e00-bad5-11e8-909c-d41b855828a7.png)

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:18.328Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (8.27GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.1.0
snapshot-tools|asv|0.0.7
multi-cursor-case-preserve|Car|1.0.4
bracket-pair-colorizer|Coe|1.0.60
sql-formatter|cym|1.0.2
transformer|dak|1.6.0
vscode-eslint|dba|1.6.0
githistory|don|0.4.2
gitlens|eam|8.5.6
prettier-vscode|esb|1.6.1
vscode-eval|exp|1.2.1
vscode-todo-plus|fab|4.4.4
vscode-pull-request-github|Git|0.1.5
toggler|hid|0.0.3
vscode-power-mode|hoo|2.2.0
vscode-insertdatestring|jsy|2.2.3
center-editor-window|kai|2.1.1
theme-karyfoundation-themes|kar|18.2.1
contextualduplicate|laf|0.2.0
expand-region|let|0.1.2
codeacejumper|luc|1.1.8
indent-rainbow|ode|7.2.4
dumb-copy-paste|she|1.0.0
incremental-search|sie|0.2.1
vscode-autohotkey|sle|0.2.2
rewrap|stk|1.9.1
transpose|v4r|0.0.5
vscode-vtools|ven|1.0.4
change-case|wma|1.0.0

(8 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
@bpasero all good now?

**Comment by bpasero** [comment]
@isidorn yes, turns out I was not setting the title for the `ResourceLabel` when tabs are disabled. I changed that now.
