### ISSUE TITLE
Outline: Add setting to control which symbols are displayed similar to Code Outline

### ISSUE THREAD

**Issue by derekwallace** [microsoft/vscode#58862]
VS Code version: 1.28 insiders
    Extension version (available under the Extensions sidebar): Python 2018.8.0
    OS and version: Win 10
    Python version (& distribution if applicable, e.g. Anaconda): 3.6 python.org

The extension "Code Outline" offered more control ability of what was displayed in the outline.
e.g. you could specify just to display functions, class and methods.

"symbolOutline.topLevel": [
"Function", "Method", "Class"
],

Request that the something similar can be done.

**Comment by murraycollingwood** [comment]
Hi Johannes
Can you summarise what has been changed and where we find the setting please?

**Comment by Kukulkano** [comment]
I'm interested in the same functionality but I don't find such settings. By which setting am I able to hide elements like variables? Or at least make it start all collapsed beyond level 1?
