### ISSUE TITLE
Text transform to `Capitalize`.

### ISSUE THREAD

**Issue by adsingh14** [Microsoft/vscode#58867]
What if we get textCapitalization feature for selected text ?

- Suggested keybinding : `Ctrl+K` `Ctrl+'`

-Filename: `keybindings.json`
```
{
        "key": "ctrl+k ctrl+oem_7",
        "command": "editor.action.transformToCapitalize",
        "when": "editorTextFocus"
 }
```

**Comment by rebornix** [comment]
We already have `editor.action.transformToUppercase` for this feature.

**Comment by adsingh14** [comment]
@rebornix Yes, I already knew that! Text Capitalization is a bit different thing.

eg.:
- aman :arrow_right:  AMAN (**transformToUppercase**) 
  - CSS prop. `text-transform: uppercase`
- aman :arrow_right: Aman (**transformToCapitalize** or **capitalizeText**) 
  - CSS prop. `text-transform: capitalize`

**Comment by rebornix** [comment]
I would suggest to implement this feature in an extension ;)
