### ISSUE TITLE
Extension API TextEditorEdit.replace only works on primary selection?

### ISSUE THREAD

**Issue by Inori** [Microsoft/vscode#5886]
- VSCode Version:1.0.0
- OS Version:Win7x64

I'm trying to make an extension for vscode.
A function like this:
```
public insertNumbers() : void
    {
        let selections : vscode.Selection[] = this._textEditor.selections;
        
        for (var i = 0; i < selections.length; i++) 
        {
            let curSelection : vscode.Selection = selections[i];

            this._textEditor.edit
            (
                function (builder) 
                {
                    builder.replace(curSelection, "test");
                }
            )
        }  
    }
```
will only replace the text within the first selection:

![bug](https://cloud.githubusercontent.com/assets/6732524/14849188/33caa94c-0ca4-11e6-943b-d7864e1f22c4.gif)

Even if I convert the 'Selection' to 'Range': 

`let curRange = new vscode.Range(curSelection.start, curSelection.end);`

then use 

`builder.replace(curRange, "test");`

the same thing will happen.

`TextEditorEdit.insert` doesn't work as expected either.

It seems that the official sample: [MDTools](https://github.com/Microsoft/vscode-MDTools) has the same problem: [#4](https://github.com/Microsoft/vscode-MDTools/issues/4) with similar [code](https://github.com/Microsoft/vscode-MDTools/blob/master/extension.ts#L28)

From the Extension API reference, it says that the primary selection is always at index 0. So the replace api will only work with the  primary selection? Then how to make a selection a primary one?
Or this is a bug of vscode extension module?

**Comment by SamVerschueren** [comment]
I'm not sure if this is the reason why it fails, but you should not call `edit` for every selection. I suggest to do the looping inside the edit callback.

```js
public insertNumbers(): void {
	const selections: vscode.Selection[] = this._textEditor.selections;

	this._textEditor.edit(builder => {
		for (const selection of selections) {
			builder.replace(selection, 'test');
		}
	});
}
```

**Comment by bpasero** [comment]
@alexandrudima can you chime in?

**Comment by Inori** [comment]
@SamVerschueren Wenderful! It is the reason! Thank you very much!
I think the official sample MDTools should also fix this bug. ha ha ha.

**Comment by seanmcbreen** [comment]
@Inori - good catch - I fixed up the MDtools example sorry about that.
@SamVerschueren  - you were right on the money - embarrassing I remembered to do that in the general method but not in toUpper and toLower :)
