### ISSUE TITLE
Git: Could not hash object when staging selected ranges

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#58874]
Issue Type: <b>Bug</b>

* Have a diff like a one line added in a file.
* Select the line and at least one line above and at least one line below.
* Run Git: Stage Selected Ranges

Observe Error:
![image](https://user-images.githubusercontent.com/5047891/45676394-e8e65180-bb31-11e8-8886-54b9e34936cc.png)

Here are the last (relevant) contents of the git log:
```
> git remote --verbose
> git fetch
> git show :src/vs/workbench/services/extensions/electron-browser/extensionHost.ts
> git ls-tree -l HEAD -- c:\Alex\src\vscode\src\vs\workbench\api\node\extHost.protocol.ts
> git show 079fb3a64d81a059555a7b650793b2e72c8c528e
> git show HEAD:src/vs/workbench/api/node/extHost.protocol.ts
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git show HEAD:src/vs/workbench/api/node/extHost.protocol.ts
> git hash-object --stdin -w --path src/vs/workbench/api/node/extHost.protocol.ts
> git hash-object --stdin -w --path src/vs/workbench/api/node/extHost.protocol.ts
> git hash-object --stdin -w --path src/vs/workbench/api/node/extHost.protocol.ts
> git hash-object --stdin -w --path src/vs/workbench/api/node/extHost.protocol.ts

```

Here is the git version:
```
> git --version
git version 2.18.0.windows.1
```

VS Code version: Code - Insiders 1.28.0-insider (98d2fd80d2d37efad35161ad5a0b59ef322b2954, 2018-09-18T06:10:01.706Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (9.63GB free)|
|Process Argv|C:\Alex\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|67%|

</details>

**Comment by joaomoreno** [comment]
Can't repro, maybe show me?

**Comment by JarLob** [comment]
Ran into the same issue. The repro is clear. Could you please fix it?
