### ISSUE TITLE
No insight into method signature as part of property.

### ISSUE THREAD

**Issue by zavr-1** [Microsoft/vscode#58879]
Issue Type: <b>Bug</b>

It is not possible to see what function's signature looks like when it is being passed as part of the configuration object. 

VS Code version: Code - Insiders 1.28.0-insider (cd9d71a31f731baf17330a84448c3efdeabc873f, 2018-09-17T05:12:08.581Z)
OS version: Darwin x64 15.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     P7350  @ 2.00GHz (2 x 2000)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: unavailable_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (1.15GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.6.0
svg|joc|0.1.2
code-spell-checker|str|1.6.10
vscode-wakatime|Wak|1.2.3

</details>

---

On the first screenshot, I can see what arguments a function accepts.

![screen shot 2018-09-18 at 13 16 21](https://user-images.githubusercontent.com/21156791/45681006-18528980-bb45-11e8-896f-ee4f7923e189.png)

However, when I've already typed in the function name, I get no useful information at all about what I should pass to it.

![screen shot 2018-09-18 at 13 17 21](https://user-images.githubusercontent.com/21156791/45681049-3324fe00-bb45-11e8-92e4-85a6536e1281.png)

This makes me to comment out that line, and start typing the property name again to see what I can give to it as arguments. Pretty inconvenient.

**Comment by mjbvz** [comment]
For a program:

```ts
interface I {
    bar?: (x: number) => void
}

function foo(x: I) { }

foo({
    bar
})
```

I now see the expected hints in VS Code insiders with TypeScript 3.2.1:

![nov-29-2018 08-40-25](https://user-images.githubusercontent.com/12821956/49237180-87a0f100-f3b2-11e8-9475-c1d932905bcb.gif)
