### ISSUE TITLE
Suggestions do not work on async properties.

### ISSUE THREAD

**Issue by zavr-1** [Microsoft/vscode#58878]
Issue Type: <b>Bug</b>

If a method accepts an `async` function as a property of its configuration, in contrast to a sync method, it will not be suggested.

VS Code version: Code - Insiders 1.28.0-insider (cd9d71a31f731baf17330a84448c3efdeabc873f, 2018-09-17T05:12:08.581Z)
OS version: Darwin x64 15.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     P7350  @ 2.00GHz (2 x 2000)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: unavailable_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Load (avg)|2, 3, 4|
|Memory (System)|8.00GB (1.95GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.6.0
svg|joc|0.1.2
code-spell-checker|str|1.6.10
vscode-wakatime|Wak|1.2.3

</details>

----

On the first screenshot, the suggestions work fine:

![screen shot 2018-09-18 at 13 11 39](https://user-images.githubusercontent.com/21156791/45680761-7337b100-bb44-11e8-944a-a216c623e571.png)

On the second example, the suggestion does not work because the method starts with `async`.

![screen shot 2018-09-18 at 13 12 20](https://user-images.githubusercontent.com/21156791/45680784-8480bd80-bb44-11e8-9ec1-43a7459a5060.png)

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/27198 to track this upstream
