### ISSUE TITLE
"Select all occurrences of current selection"can not select the contents of more than 1000 rows.

### ISSUE THREAD

**Issue by yisibl** [Microsoft/vscode#5887]
- VSCode Version:1.0.0
- OS Version: 10.11.4 (15E65)

Steps to Reproduce:
1. Select a section of content
2. ⇧⌘L
3. Can not select the contents of more than 1000 rows

**Comment by yisibl** [comment]
Who can help take a look?

**Comment by alexandrudima** [comment]
Related: #496

**Comment by alexandrudima** [comment]
Related: #1110

**Comment by agauniyal** [comment]
1000 occurrences in a single file aren't too large, please raise the limit to somewhat reasonable number.

**Comment by cprogrammer1994** [comment]
where is this limit defined? file?

**Comment by alexandrudima** [comment]
PR #36410 has made it feasible that we remove this limitation.
