### ISSUE TITLE
Menus: submenu arrow is huge on Linux

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#58873]
Compared to other menus, the submenu arrow is quite large on Linux.

/cc @misolori

**Comment by misolori** [comment]
Can we make the icons slightly smaller on Linux? Looking at other apps, they all appear smaller:

**Firefox**
![image](https://user-images.githubusercontent.com/35271042/45703206-7624a880-bb28-11e8-9676-4c57f58eaad1.png)

**System Files**
![image](https://user-images.githubusercontent.com/35271042/45703233-83da2e00-bb28-11e8-8b8b-a4cc79427b28.png)

If you bump the size down to 10px, it _looks_ about right:
![image](https://user-images.githubusercontent.com/35271042/45703341-eb907900-bb28-11e8-9f64-7ce9ee10df3d.png)
