### ISSUE TITLE
npm is not recognized in the tasks.json

### ISSUE THREAD

**Issue by hanct** [Microsoft/vscode#58886]
Node js used: v10.8.0
electon : v2.0.7
VScode IDE: v1.25.1
OS: window 10

Currently, i have a launch configuration with  preLaunchTask set to "RunTSC". This task is configured in tasks.json as shown below. But i keep getting error: "The term 'npm' is not recognized as the name of a cmdlet, function, script file, or operable program...."      

    {
            "label":"RunTSC",
            "type": "npm",
            "script": "tsc",
            "path": "src/",
            "env":{},
            "problemMatcher": [],
      }

Very obvious, npm is not recognized.  I admit that my OS's env variables do not have the PATH set to the location of npm.  But i did set the "env" setting of the launch configuration to point to the npm location.

Can i say that the "env" only applies the launch configuration, and not the task that it prelaunch? If yes, then how do I specify the location of the npm in the visual studio code.  In other word, is there a way to specify any environment variable globally via visual studio code, instead of via windows.

**Comment by dbaeumer** [comment]
This task needs to be contributed / auto detected by the npm extension. You can always contribute a shell task that starts npm directly. Something like 

```json
{
    "label": "Run TSC",
    "type": "shell",
    "command": "my path to npm",
    "args": ["run", "tsc"]
}
```

@egamma moving to you to comment on whether the npm location can be configured in the npm extension.

**Comment by hanct** [comment]
> This task needs to be contributed / auto detected by the npm extension. You can always contribute a shell task that starts npm directly. Something like
> 
> ```json
> {
>     "label": "Run TSC",
>     "type": "shell",
>     "command": "my path to npm",
>     "args": ["run", "tsc"]
> }
> ```
> 
> @egamma moving to you to comment on whether the npm location can be configured in the npm extension.

Hi,  It working now!!!  Based on the reply, i conclude that visual studio does not have a global setting (yet) to set the environment variables, such that launch.json, tasks.json , etc are able to use it. Do correct me if I am wrong.  Nevertheless, thank you very much!
