### ISSUE TITLE
VS Code hanging when opening particular C# file

### ISSUE THREAD

**Issue by nadako** [Microsoft/vscode#58883]
- VSCode Version: 1.27.2 (happened long before as well)
- OS Version: any

Steps to Reproduce:

1. Create the `Function.cs` file with the following contents: https://gist.github.com/nadako/816ed023418b3558f927dd0aa478a19b
2. Open it in VS Code.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sr229** [comment]
Can be Reproduced here as well on Windows 10 Anniversary Update.

**Comment by aeschli** [comment]
This issue was moved to dotnet/csharp-tmLanguage#137
