### ISSUE TITLE
Since Aug 2018 update can not do simple debugging tasks

### ISSUE THREAD

**Issue by SueMcMetzger** [Microsoft/vscode#58882]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

I have very simple code. Can run Debug in both integrated and external terminal with expected results. However, the minute I set a breakpoint, I get an error indicating an IndexError that begins with this:
Traceback (most recent call last):
  File "c:\Users\smcfarla\.vscode\extensions\ms-python.python-2018.8.0\pythonFiles\experimental\ptvsd\ptvsd\wrapper.py", line 1254, in done
    fut.result()
  File "c:\Users\smcfarla\.vscode\extensions\ms-python.python-2018.8.0\pythonFiles\experimental\ptvsd\ptvsd\futures.py", line 40, in result
    reraise(self._exc_info)

If I choose Step In, the program runs but seems to ignores the breakpoint and does not display values for the variable listed in the Watch panel.

This was working just fine prior to the Aug 2018 update and also prior to recent Windows udpates.

Suggestions?
Thanks,
Sue

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (2.29GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
anaconda-extension-pack|ms-|1.0.0
python|ms-|2018.8.0
vscode-yaml|red|0.0.16

</details>

**Comment by weinand** [comment]
please file this against the python debugger
