### ISSUE TITLE
Error highlighter displays a couple of validation errors when trying to assign CSS style attribute value using {{ }} syntax

### ISSUE THREAD

**Issue by izdwuut** [Microsoft/vscode#58880]
Hi there!

I'm working on a [Hugo](https://gohugo.io/) theme using your lovely editor. Unfortunately a file that I edit fails to validate at `css-propertyvalueexcepted` rule:

```
<span style="color: {{ .Get "color" }}">❤</span>
```

The code above uses the syntax described [here](https://gohugo.io/templates/introduction/#access-a-predefined-variable) and is supposed to display a heart with it's color assigned to the value passed to the template. 

Furthermore, the editors displays `css-rcurlyexpected` error for the following snippet of code. It also yields a `[css] do not use empty rulesets (emptyRules)` notification:
```
<span style="{ .Get "style" }}">❤</span>
```

I consider it a bug because the following code gets parsed correctly and I know of no HTML tag attribute that starts with `{`:
```
<span {{ .Get "attributes" }}>❤</span>
```
It persists despite of disabling extensions.

**Steps to reproduce:**
1. Create an `.html` file with contents:
```
<span style="color: {{ .Get "color" }}">❤</span>
<span style="{ .Get "style" }}">❤</span>
```
2. Open the file with VSCode.
3. The editor should inform you of `css-propertyvalueexcepted`, `css-rcurlyexpected` and `emptyRules` errors.

**System specs**:
```
         Operating System: Windows 10 Enterprise 64-bit (10.0, Build 15063) (15063.rs2_release.170317-1834)
                 Language: English (Regional Setting: English)
                Processor: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 CPUs), ~3.4GHz
                   Memory: 16384MB RAM
          DirectX Version: DirectX 12
            Graphics card: Intel(R) HD Graphics 4600
```

**VSCode version output**:
```
Version: 1.27.2 (system setup)
Commit: f46c4c469d6e6d8c46f268d1553c5dc4b475840f
Date: 2018-09-12T16:17:45.060Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

**Comment by aeschli** [comment]
The template syntax that you are using interferes with the css syntax.
You have turn off the styles validation:
`"html.validate.styles": false,`

**Comment by izdwuut** [comment]
I think that it's hardly a fix, as I'd be rendered with no styles validation whatsoever.

**Comment by aeschli** [comment]
The HTML language mode is intended for pure HTML, but tempting languages are not HTML (from a language syntax perspective)

The setting is just turning off the validation errors. You still get color decorators, code completions and hovers (as a best effort, of course we have no chance knowing what `{.. } means and what it could possible stand for."

**Comment by izdwuut** [comment]
Thanks. Now I see that the problem is more complex. And common, too. I've just checked how Notepad++ handles it and this syntax confuses him as well. On top of that I was wrong before. The snippet that I posted:
```
<span style={{ .Get "attributes" }}>❤</span>
```
Doesn't pass the validation as well. It just didn't strike me at first. I think that it invalidates (what an irony!) my point. What a cool feature would it be, though!

**Comment by aeschli** [comment]
The right way would be if there's a extension for your templating language. That extension could correctly parse the document and generate a real html document to pass it to the html service for validation.

That's quite some work of course. I take your point that this is a common use case and we're constantly discussing what we can do to provide better support for templating languages, but no actual plan yet.

**Comment by izdwuut** [comment]
> That's quite some work of course.
Certainly. Well, I think that we're done here. Thanks for your assistance and have a nice day!
