### ISSUE TITLE
Running terminal as a different user

### ISSUE THREAD

**Issue by boston51** [Microsoft/vscode#58894]
Part of my normal process is to run multiple PowerShell consoles at a time, including one as a different user which is a domain admin account.

I can easily run multiple terminals (which would be nice if they could 'pop out' on their own, hint hint) but I cannot figure out a way to launch a terminal as a different user. This would definitely make thing smoother for me, and I imagine others who haven't tried this yet.

**Comment by boston51** [comment]
Please add the 'Feature-Request' label

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/41753
