### ISSUE TITLE
Settings editor: gear missing for boolean entry

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#58891]
Version: 1.28.0-insider
Commit: d59d9f5aa5708c006e409c1a7b197c27fecb54a4
Date: 2018-09-18T09:05:00.360Z
Electron: 2.0.9

- open the settings editor
- enter `html.sty` in the filter field
- try to copy the settings ID for the HTML > Validate: Styles setting
  -> Gear is missing

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/58538

**Comment by itamark** [comment]
@roblourens @ramya-rao-a I saw the bug in my insiders build, but I can't see it in OSS build. Am I missing something?
<img width="732" alt="screen shot 2018-09-20 at 10 05 57 am" src="https://user-images.githubusercontent.com/1757393/45801544-d2b8cc80-bcbc-11e8-86bb-25f0610e408a.png">
