### ISSUE TITLE
Continue select bug from #58273

### ISSUE THREAD

**Issue by pixieaka** [Microsoft/vscode#58897]
Continue select bug from #58273

[ 'status' => 'تمت عمليه الحفظ بنجاح' ];

![s](https://user-images.githubusercontent.com/17777237/45706666-1efcf300-bb7d-11e8-8035-9174fddf7398.gif)

**Comment by alexandrudima** [comment]
There is no problem here. This is also how native textareas work in browsers. AFAIK only word editors (where they break selections at the model layer in order for them to paint as a single selection at the view layer)

Screen recording of Chrome (the same happens in Edge and in Notepad):

![58897](https://user-images.githubusercontent.com/5047891/45825991-cef46c80-bcf3-11e8-8029-0d1fad8362e2.gif)
