### ISSUE TITLE
Find highlights both camelcase and non-camelcase for the same spelled word

### ISSUE THREAD

**Issue by lupee431** [Microsoft/vscode#58899]
I did a find on "objectStore".
It highlighted both "objectStore" and "objectstore".
I verified it on another word. Same behaviour.
Is this the desired behaviour?

Lew

**Comment by octref** [comment]
Toggle on "Match Case":

![image](https://user-images.githubusercontent.com/4033249/45847278-669b9000-bcdf-11e8-886f-2ffcc7868258.png)
