### ISSUE TITLE
Support Extensions Providing TypeScript Definition Files

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#589]
_From @thoughtentity on October 27, 2015 4:59_

As part of the extension I'm developing, I'm developing a TypeScript definition file to light up the editor with intellisense for the JavaScript APIs my users will be using when working with my extension in their project. Currently, to support this I need to explicitly inject the type definition files into a user's project through an init command provided by the extension. I'd be nice if VS Code supported this scenario better by implicitly loading definition files from an extension's typings directory. Users can override the extension provided definitions by providing their own type definition files that redefine the typings the extension provided.

_Copied from original issue: Microsoft/vscode-extensionbuilders#64_

**Comment by seanmcbreen** [comment]
Not a bad suggestion adding @egamma.  

This won't make the November release unfortunately.  One option which is a little hacky is to write the file to disk yourself from the extension on init.  Or even better you could run the TSD command - one option for this is https://www.npmjs.com/package/run-in-terminal.

@jrieken - any other thoughts?

**Comment by seanmcbreen** [comment]
_From @jrieken on October 31, 2015 12:53_

@thoughtentity My recommendation would be run TSD from API. This [PR](https://github.com/DefinitelyTyped/tsd/pull/227) happened a while ago and might be on npm already. It will give you a nicer programming experience.

**Comment by jrieken** [comment]
Sticking with my recommendation of using TSD for that. No work planned.
