### ISSUE TITLE
Why instant mark written code with red first???

### ISSUE THREAD

**Issue by christer54** [Microsoft/vscode#58905]
Issue Type: <b>Performance Issue</b>

If I type in an existing function it immediately mark the typed function with red (misspelled). After few seconds it realise that the function exist and remove the red marking.
Why not let typed things be OK first, and then mark, if it is wrong.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:04:11.329Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_38302853|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.5.6
cpptools|ms-|0.18.1
csharp|ms-|1.16.1
vscode-docker|Pet|0.2.0
cmake-tools|vec|1.1.1

</details>

**Comment by mjbvz** [comment]
What language are you writing?

**Comment by christer54** [comment]
Writing C++ code. Using VS Code on Mac OS X.

**Comment by mjbvz** [comment]
Thanks. Please file this issue against the c++ tools extension
