### ISSUE TITLE
Allow prepareRename to return ranges that do not include original position

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#58907]
**Problem**
TypeScript would like to support renaming files by hitting F2 anywhere in the import path.

```js
import * as _ from './dir1/dir2/file'
```

Here, hitting F2 anywhere in in the string `'./dir1/dir2/file'` should trigger a rename only on the `file` part of the path. However, in `prepareRename`, we currently can't return rename ranges that do not include this original rename position. This means that we cannot support hitting F2 anywhere on `'./dir1/dir2/``

**Proposal**
Relax this restriction, either eliminating it entirely or perhaps only requiring the rename range to be on the same line as the original position

**Comment by jrieken** [comment]
@mjbvz I have eased the restrictions and also removed from workaround check from the TS extension but still wasn't able to test this. It seems TS server errors on a rename request on the `class`-keyword...
