### ISSUE TITLE
Lost all extensions on Version 1.27.2 (1.27.2) update

### ISSUE THREAD

**Issue by moe123** [Microsoft/vscode#58902]
All duplicates about this topic are closed and restricted ; hence forced to open a new one.

- VSCode Version:  Version 1.27.2 (1.27.2)
- OS Version: macOS 10.13.6

Steps to Reproduce:

1. trust 
2. update
4. getting upset
5. fill an issue

Does this issue occur when all extensions are disabled?: No

**Comment by octref** [comment]
Can you also link to the issues that were closed?

**Comment by moe123** [comment]
Hello,

https://github.com/Microsoft/vscode/issues/41894
https://github.com/Microsoft/vscode/issues/45016

**Comment by sandy081** [comment]
@moe123 Sorry for what happened. Can you please provide us following information

- Can you please open the extensions folder and let us know what you see there
- Can you please open the logs folder and go to the sessions before and after you updated. Provide us the shared process log in these sessions.

**Comment by moe123** [comment]
Ok sorry for the late answer ; I only see the re-installed extensions ; (modified date, matching create date) ; no tmp/invisible or left over cruft ; maybe I should have checked out before re-running all installs.

**Comment by sandy081** [comment]
You can go to logs folder using the command `Open Logs Folder`

**Comment by moe123** [comment]
[logs.zip](https://github.com/Microsoft/vscode/files/2444370/logs.zip)
