### ISSUE TITLE
"Git: Failed to execute git" dialog but git works in terminal

### ISSUE THREAD

**Issue by fischeme** [Microsoft/vscode#58910]
Issue Type: <b>Bug</b>

As of approximately August, git integration no longer works, but git commands work fine from the terminal within VS Code.   

I can reliably reproduce by opening a project folder with .git repository, clicking on source control tab in sidebar and pressing "Refresh" icon.  VS Code then presents a dialog with "Git: Failed to execute git".  From there,  opening the git log shows a normal log, with a series of commands and no errors:

```
Looking for git in: C:\Program Files\Git\cmd\git.exe
Using git  from C:\Program Files\Git\cmd\git.exe
> git rev-parse --show-toplevel
> git config --get commit.template
Open repository: \.
> git status -z -u
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel

...the log shows periodic calls to the following two commands from then on:
> git status -z -u
> git rev-parse --show-toplevel
```

user.email and user.name are already set globally so this solution is not a problem.

Issue occurs on insider edition of VS code and it also occurs when running as administrator and when running with --disable-extensions.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz (8 x 2793)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.63GB (7.97GB free)|
|Process Argv|C:\Users\IBM_ADMIN\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
jshint|dba|0.10.20
php-debug|fel|1.12.5
printcode|nob|2.3.1

</details>

**Comment by fischeme** [comment]
Also would add that --verbose gave no clue on problems.  I think we just need to get at exactly what is failing in the git call... I believe this is an edge case related to something about my workstation's configuration - environment, path, permissions.  I am suspicious that VSCode is internally executing git in a way that is not the same as is happening in terminal.

**Comment by joaomoreno** [comment]
Can you reproduce in other git repositories in your system?

**Comment by fischeme** [comment]
At the time this occurred I had two projects under git control and both broke.  I added a new project, and it broke too.  As a sanity check, I opened one of the projects in the Netbeans IDE and it correctly integrated with git, showing project status, current branch, and allowing me to diff a changed file in the IDE. So I think git and the git repo are fine.
The first symptom I noticed of the problem was that vscode was no longer showing the current branch in the footer.
Incidentally, I have uninstalled both vscode and git multiple times with no effect.

**Comment by joaomoreno** [comment]
No repository works, then?

Are the repositories located in a special file system, eg remote?

**Comment by fischeme** [comment]
Joao, looks like we posted at the same time (see my comment above)... strangely a Windows system update solved the problem. To answer your last question though, all repositories were affected and they were in the local file system.  So there is a strange dependency on some aspect of the OS.  I'm going to close this issue.

**Comment by mrkbutty** [comment]
I have the same problem.
Git works everywhere except within VScode.
Changes are not tracked - I even delete repository and initialized again and still does not work.
At the moment manual git terminal commands are needed.

Similar git log output; with no results to the command;
```
Looking for git in: C:\Program Files\Git\cmd\git.exe
Using git  from C:\Program Files\Git\cmd\git.exe
> git rev-parse --show-toplevel
> git config --get commit.template
Open repository: \.
> git rev-parse --show-toplevel
> git status -z -u
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
```

**Comment by fischeme** [comment]
@mrkbutty, if you have the same problem I had, then GIT GUI will also fail to launch with an error.  Solution on Win7 strangely came from a system update.  This is still a very strange problem so maybe @joaomoreno will want to work with you now that it's been seen again...

**Comment by mrkbutty** [comment]
@fischeme Yes it is strange as it was working a week or so ago.  I also have similar problem in pycharm (which was also working fine a week ago).  Pycharm says "Cannot run git: Empty git --version output".  So I do think this is environmental.

But I can run git fine in any console.  

I have seen a similar problem in the past when "Beyond Trust" service was stopping Docker from controlling VBox.  It interfered which with spawning of the VBox CLI commands - stopping the service fixed it.  

 - No such luck this time though!  I have looked at monitoring output from Carbon Black and the running of Git does seem to work successfully in both VsCode and PyCharm - it looks like the output streams are getting interference which stops the parents from picking up the output.

You wouldn't happen to know which update was applied do you? - My Win7 system seems up to date based on fixes released by my Organisation (I suspect we lag the most up to date fixes).

I would be happy to work with @joaomoreno or anyone to fix this so I don't have to manually run Git at terminal.

**Comment by joaomoreno** [comment]
@mrkbutty Maybe try fully reinstalling Git and VS Code.

**Comment by mrkbutty** [comment]
Some more intrigue....

I created 2x scripts one in python another in go, below are the scripts and output.
Python works but Go does not...

```
import subprocess
result = subprocess.run(['C:\Program Files\Git\cmd\git.exe', '--version'], stdout=subprocess.PIPE)
print('stdout:', result.stdout)
```

```
C:\temp>testgit.py
stdout: b'git version 2.19.0.windows.1\n'
```

```
package main
import (
	"bytes"
	"fmt"
	"log"
	"os/exec"
)
func main() {
	cmd := exec.Command("C:\\Program Files\\Git\\cmd\\git.exe", "--version")
	var stdout bytes.Buffer
	var stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	err := cmd.Run()
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("StdOut: %q\n", stdout.String())
}
```

```
C:\temp>testgit.exe
StdOut: ""
```

**Comment by fischeme** [comment]
@mrkbutty, see my post from Sep 19 for the OS updates that were done.  Still not sure if it was the updates themselves or housekeeping as part of the update process (does the update process always do an OS scan and repair?) that did the trick for me.  A whole bunch of other updates related to MS Office were also installed plus an update to .NET (KB44577035).  I would focus first on making sure you have the Windows and NET updates then I can send you the long list of Office Updates that were done but would be surprised if those mattered.

**Comment by mrkbutty** [comment]
@fischeme yes I have the same issue with gitgui. But I also have all those updates already installed. 
I have a bad feeling this may relate to carbon black, I've had nothing but problems ever since my corporate started to use it.

**Comment by zhiminwen** [comment]
I have the same issue since around August. The git command is running fine from the cmd shell. But not for the VScode. 

I am using the git from cmder. This is the git window output
```
Using git  from C:\Tools\cmder\vendor\git-for-windows\cmd\git.exe
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git config --get commit.template
Open repository: \.
> git status -z -u
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git status -z -u
```
@mrkbutty, I have the same output as your go program. No output of the go program.

Funny enough, I also have the Carbon Black installed around August time frame...

I have no choice now to work the git stuff from command line... Please share any update on this issue.

**Comment by fischeme** [comment]
The plot thickens...  I also got Carbon Black in August, exactly when my problems began.  But then they resolved.... I have version 3.2.1.51 of "Cb Defense Sensor 64-bit".  Maybe I got an update?  I'm going to reopen this as it seems to be an interaction that the MS team will want to dig into some more...  Here there is some discussion about dependence on vendor patches and weirdness about if/when a registry key should be pushed... https://www.carbonblack.com/2018/01/05/carbon-black-solutions-currently-compatible-major-os-vendor-patches-meltdown-spectre/

**Comment by fischeme** [comment]
Reopening due to multiple instances of this now and better information on possible root cause...

**Comment by joaomoreno** [comment]
I'm gonna focus here on @fischeme, since he already has a lot of detail around his issue. If you feel like you have a similar issue, please file a new one.

@fischeme Let's try to keep this simple: Does this reproduce on every git repository in your system?

**Comment by joaomoreno** [comment]
@fischeme Do you still have the issue?

**Comment by fischeme** [comment]
I do not have the issue any longer (see: https://github.com/Microsoft/vscode/issues/58910#issuecomment-423043490)

**Comment by TheAifam5** [comment]
I have this issue now which is really annoying since throws like 1k errors pro second.
I'm using Workspaces and Typescript with react.

And I'm 100% sure that's a VS Live Share since I tested all extensions by disabling them and reloading window, and then when I found the problem - I enabled them again and toggled VS Live Share.

So the next reason why should I uninstall it :D
