### ISSUE TITLE
After the update to version 1.27.1, Vscode always crashes!!!!

### ISSUE THREAD

**Issue by ddzy** [Microsoft/vscode#58917]
When I open Vscode and run for a period of time, the program always crashes, sometimes a pop-up window, prompting me to restart Vscode ... And sometimes I have to turn it off in the process manager!

**Comment by octref** [comment]
@ddzy Can you provide more info? What was the actions you were performing before the crash? What does the pop-up window say? Before it crashes, can you run `code --status` in command line and paste the content here?

**Comment by ddzy** [comment]
> @ddzy Can you provide more info? What was the actions you were performing before the crash? What does the pop-up window say? Before it crashes, can you run `code --status` in command line and paste the content here?

Oh, I've solved this problem, probably because of the conflict in my workspace, thank you!

**Comment by octref** [comment]
@ddzy Conflicts in workspace shouldn't crash VS Code though. What is the conflict?

**Comment by ddzy** [comment]
> @ddzy Conflicts in workspace shouldn't crash VS Code though. What is the conflict?

Crashes occur when there are several different project directories in my workspace that open multiple endpoints ... I have to force the Vscode to close in the resource Manager ... This is not the case when there is only one project directory in my workspace.

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!
