### ISSUE TITLE
Settings: Utilize Button for all 'Edit settings.json' link

### ISSUE THREAD

**Issue by cleidigh** [microsoft/vscode#58923]
@roblourens 

While keyboarding through the settings I think it might look better to utilize a button instead of a link.
The Link sort of dangles a bit.  Additionally there are two functional issues:
- The link gets read with the extra hyperlink baggage
- Separately , for any of these non-typical input elements , having the User Land on a button which also uses described by will be more obvious for accessibility users.
- For elements like 'Files Exclude' , starting on the Add button would also be a little bit more obvious than the link in the description.

![image](https://user-images.githubusercontent.com/25272315/45729193-6b562c00-bb99-11e8-9136-e70789e72fbb.png)

**Comment by roblourens** [comment]
I think that using a button for "Edit settings.json" makes sense. 

> For elements like 'Files Exclude' , starting on the Add button would also be a little bit more obvious than the link in the description.

What do you mean "starting on"?

**Comment by cleidigh** [comment]
by start on I mean the first element landed on by Tab within an element setting.

For input boxes you have the first tab index on the input element and from a reader perspective we read out the element title and then the extended description which may include links.

On several of the glob settings or others, the first tab index is a link within the description so in excess ability user does not get the readout of the element title in until one or more tabs.

Starting on the applicable button would allow us to read out in the same way as the other elements.

**Comment by roblourens** [comment]
I think that it's important for tab order to follow the document order, I think that's what people expect.

**Comment by cleidigh** [comment]
actually I misspoke, if an input box has a link in the description, you do 'start' there.

What do you think about the fact that the reader then reads the link but the user does not know what the element is.  Would not starting on the input element with its associated labels make sense?

Otherwise we could add the element title to the links? Just a thought .

**Comment by cleidigh** [comment]
sounds good
I can help with that whenever

**Comment by isidorn** [comment]
@roblourens if we do not have plans to tackle this I would close.

**Comment by roblourens** [comment]
Not really planning to do this, and the other focus issue is covered by other settings editor accessibility issues.
