### ISSUE TITLE
SelectBox: Update ctor, organize for new options eg Settings requirements

### ISSUE THREAD

**Issue by cleidigh** [microsoft/vscode#58922]
SelectBox additions over time, especially new requirements in the settings editor (extended descriptions, labels) has resulted in a non optimal ctor and widget interface.  Needs some re- factoring.

- Consolidate selectOptionEntry options into new option interface
- Support option details/aria labels in both ctor and updated setOptions
- Improve details provider, use interface not callback
- Update SelectBox clients as necessary

**Comment by cleidigh** [comment]
@roblourens 
I am rationalizing and improving the select box ctor and option interface:
Jackson added an unused option MarkdownActionHandler, is this a callback handler if the user selects
the details of the end of the select box?  There is no supporting code, should I remove this ?

```ts

export interface ISelectBoxOptions {
	ariaLabel?: string;
	minBottomMargin?: number;
	hasDetails?: boolean;
	markdownActionHandler?: IContentActionHandler;
}
```

**Comment by roblourens** [comment]
Yeah that was for supporting links in enumDescriptions, which we decided to just not support. So you can remove that.

**Comment by cleidigh** [comment]
@bpasero 
@isidorn 
Just wanted to flag this since I'm going to start on this and the related "Default" option addition #58724 .  I will propose the constructor signature change before going too far, but I wanted to check if there is any reason I should not change the constructor.  I will also post the PR for review/merged by yourselves.

**Comment by bpasero** [comment]
@cleidigh sounds good, maybe we do the discussion when you have some proposed changes in a PR

**Comment by cleidigh** [comment]
Yep, just wanted to give a heads up.

**Comment by cleidigh** [comment]
See PR #64109 for verification steps
