### ISSUE TITLE
Reenable dynamic menus on macOS in Insiders

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode#58928]
As part of this, investigate the caching of menu items to quickly populate the menu on launch.

* Cache items and restore a menu with everything enabled by default
* When no window is open, use cached menu show disabled menu items
* When item is triggered without render process, it will be scheduled.

/cc @bpasero

**Comment by sbatten** [comment]
related #55347

**Comment by bpasero** [comment]
@sbatten I think we need the same trick on Windows as well (keep old menus around for a bit).

**Comment by bpasero** [comment]
@sbatten just so that we do not forget, this needs a test plan item or verification needed at least. I will add the label now so we do not forget.
