### ISSUE TITLE
Regression: editorService doesn't open `http`/`https` schema URLs as of 1.25

### ISSUE THREAD

**Issue by BoykoAlex** [Microsoft/vscode#58924]
- VSCode Version: 1.25 and up
- OS Version: OSX, but should be reproducible on Win and Linux

A block of code has been removed: 
```
		// Support opening foreign resources (such as a http link that points outside of the workbench)
		const resourceInput = <IResourceInput>input;
		if (resourceInput.resource instanceof URI) {
			const schema = resourceInput.resource.scheme;
			if (schema === Schemas.http || schema === Schemas.https) {
				window.open(resourceInput.resource.toString(true));

				return TPromise.wrap<IEditor>(null);
			}
		}
```
it used to be in the `WorkbenchEditorService` under `editor/commons`. Now it seems to be moved under `editor/browser` and class is EditorService

Here is the commit that introduced the regression: https://github.com/Microsoft/vscode/commit/ef92f85c06587053810e29b641f619021d62468c#diff-7260c109d203125646107c652086f25c

Our VSCode extension was relying on this behaviour to open URL in the browser for a workspace symbol with `Location` `uri` property being an `http`/`https` schema URL.

Are there any workarounds?
If not any chance this code can be put back or moved in here for example? https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/quickopen.ts#L276

**Comment by martinlippert** [comment]
Here is the issue that I opened a while ago to clarify that http should work for workspace symbols: https://github.com/Microsoft/language-server-protocol/issues/320

**Comment by bpasero** [comment]
@BoykoAlex @martinlippert how exactly was the code triggered. Imho it is wrong to run this through the editor service, so I removed it. But we can think about putting it back in places where HTTPS links make sense.

**Comment by martinlippert** [comment]
This is triggered by a SymbolInformation coming from a language server pointing to a http:// resource instead of a file:// resource

(as described in the issue/question that I mentioned above). Is that all you need to know or are you looking for something different?

**Comment by bpasero** [comment]
@martinlippert and what piece of UI shows symbol information? I guess this would only ever be the symbol picker right? This would not get triggered from interacting with the editor?

**Comment by martinlippert** [comment]
@bpasero Yes, I think so, can't think of a use case (from our scenarios) where this is triggered from within the editor. We have code lenses that show HTTP URLs and open that URL when clicked, but that is done via a different mechanism (not symbols).

**Comment by martinlippert** [comment]
in our concrete case, it is the "go to symbol in workspace" popup...

**Comment by jrieken** [comment]
> in our concrete case, it is the "go to symbol in workspace" popup...

Oh, interesting use-case. @bpasero Instead of the editor service we could use the opener service instead

**Comment by bpasero** [comment]
@jrieken yeah that is the fix I am thinking of

**Comment by martinlippert** [comment]
Awesome, thanks for the super quick fix. Any idea when this will show up in a VSCode update? Your colleagues and I would love to our feature which needs this fix next week at a conference... :-)

**Comment by BoykoAlex** [comment]
Thanks a lot for the fix! That should do it for us!

**Comment by bpasero** [comment]
@martinlippert yes, Monday (https://code.visualstudio.com/insiders/). good luck at the conference 👍

**Comment by martinlippert** [comment]
Thanks!!! 😀
