### ISSUE TITLE
Provide option to change the color of whitespaces

### ISSUE THREAD

**Issue by papaiatis** [Microsoft/vscode#5892]
Please provide an option to change the color (argb) of whitespaces when `editor.renderWhitespace` is enabled. I like the dark background but I can't really see the whitespace markers on it, which are also dark.

**Comment by egamma** [comment]
// @alexandrudima

**Comment by alexandrudima** [comment]
@papaiatis The colors for the whitespace is taken from the `invisibles` property in themes, so the color is customizable via themes.

e.g. https://github.com/Microsoft/vscode/blob/5b9ec15ce526decc5dd0488339e798f6bcb4ec46/extensions/theme-monokai/themes/Monokai.tmTheme#L19

**Comment by papaiatis** [comment]
Ah okay. So I need to create a new Theme myself and adjust this color.
According to [this](https://code.visualstudio.com/docs/tools/yocode) page I need to specifiy an existing theme to be based on my theme on. So where is the default dark theme located on Linux? I couldn't find it.

**Comment by alexandrudima** [comment]
@aeschli What is the easiest way for @papaiatis to create a custom theme based on our default dark theme?

**Comment by aeschli** [comment]
Create your own extension and start with vscode/extensions/theme-defaults/themes/dark_vs.json

**Comment by alexandrudima** [comment]
This ability exists through themes => closing this

**Comment by mikelward** [comment]
Changing the color for `invisibles` has no effect, at least not in Python and C.  Theme bug?  TM Scopes bug?

https://stackoverflow.com/questions/43034430/color-scheme-for-whitespace

**Comment by alexandrudima** [comment]
perhaps a regression ... @aeschli ?

**Comment by mikelward** [comment]
Hmm, I can't repro.  TM Scopes not showing a token is probably expected for whitespace.  Sorry for the noise.

**Comment by Flerox** [comment]
Now it seems like the whitespace color is white all the time, _whatever_ theme I pick.

**Comment by aeschli** [comment]
@Flerox Coloring the whitespace seems to work for me:
![image](https://user-images.githubusercontent.com/6461412/27171929-9e2c759a-51b3-11e7-8cf1-6543117fdb26.png)

Please file a new bug that gives more details so we can reproduce.

**Comment by Flimetta** [comment]
@aeschli This is the result for me. The arrow color changes when I switch theme, but I can't seem to overwrite it.
![whitespace](https://user-images.githubusercontent.com/17824899/27172297-025071c4-51b5-11e7-949c-b4544245c2a9.PNG)

**Comment by aeschli** [comment]
@Flimetta What version of VSCode? Are the settings saved and not overwritten by workspace settings? 
Can you check with dev tools (Help > Toggle Developer Tools) what styles are applied?
![image](https://user-images.githubusercontent.com/6461412/27173886-639b3eaa-51ba-11e7-88e3-7fbb85e77145.png)
