### ISSUE TITLE
Workspace settings should use User setting as default setting

### ISSUE THREAD

**Issue by RedTailBullet** [Microsoft/vscode#58927]
When the default setting has been modified in the user setting, workspace setting should be based on user setting instead of the default setting.

Under current behavior, if user settings already modified this setting, we are unable to overwrite the workspace settings to set it as the default value.

This might only be the issue with boolean type settings.

## Example:  

Given setting A.
A's default setting is false.
In user settings, A is set to true.
In workspace settings, A can be set to false again.
When doing the "reset setting" in workspace settings, A should be set to true which is the user setting.

**Comment by roblourens** [comment]
This is a good idea, I will roll it into https://github.com/Microsoft/vscode/issues/58038
