### ISSUE TITLE
Bug: Workspace/User settings has a GUI

### ISSUE THREAD

**Issue by prmichaelsen** [Microsoft/vscode#58936]
### Description
It appears some bug was added in a recent release that introduced a GUI to the settings.json editor.

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:18.328Z)
OS version: Windows_NT x64 10.0.15063

### Steps to Reproduce:
`Ctr + , `

#### Expected Behavior:
Settings.json opens

#### Actual Behavior:
Some ridiculously convoluted GUI appears when I could just be editing a .json file

**Comment by davec21** [comment]
If you click the 3 dots to the right side of the settings GUI you have the ability to edit the .json file. 

I agree though, why have a super easy and simple gui for changing settings when you could be manually editing a text file... /s

**Comment by prmichaelsen** [comment]
@davec21 I’m glad you agree

**Comment by roblourens** [comment]
You can still use the JSON editor any time you want, and if you prefer, you can change the default by setting `"workbench.settings.editor": "json"`

**Comment by prmichaelsen** [comment]
I wasn’t aware you can change the default. Thanks for the info 🤗
