### ISSUE TITLE
getConfiguration.update not working 

### ISSUE THREAD

**Issue by dabedoc** [Microsoft/vscode#58931]
- VSCode Version: 1.27
- OS Version: kubuntu 18
I am making an extension which needs some configuration to run commands. I am asking user to input configuration when they try to run the command if it is already not in the user configuration. If it is not, then I get the input from the user and trying to update the value in the user configuration but it doesn't work. 
```javascript
  try {
            if(!token) {
                let input = await vscode.window.showInputBox({
                    prompt: "Please add your token and login again!"
                });
                await config.update('token', input, true);
                hookie.login(input);
            }
            hookie.login(token as string); 
        } catch (e) {
            vscode.window.showErrorMessage(e)
        }
    }));
```
the code looks like above.

**Comment by sandy081** [comment]
@dabedoc Do you get any errors in the console? Are not you seeing the written value in the user settings?

**Comment by dabedoc** [comment]
nope. I am not seeing anything. In fact update function doesn't even resolve so the line below it doesn't run either.

**Comment by sandy081** [comment]
@dabedoc Did you register the configuration in the package.json? 

Ref: https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesconfiguration

**Comment by dabedoc** [comment]
yes I did.

**Comment by dabedoc** [comment]
get function works but update doesn't work.

**Comment by sandy081** [comment]
@dabedoc Can you please open dev tools and see if there is any errors?

**Comment by dabedoc** [comment]
okay I checked and found nothing. I dug deeper and found that there was a problem with the file system permission in my environment due to which the update was not working so I solved it by changing the file system permissions.
