### ISSUE TITLE
extension报错

### ISSUE THREAD

**Issue by Hellowworld123** [Microsoft/vscode#58934]
- Extension Name: configuration-editing
- Extension Version: 1.0.0
- OS Version: Windows_NT x64 6.3.9600
- VSCode version: 1.28.0-insider

 We have written the needed data into your clipboard. Please paste:

**Comment by octref** [comment]
Please follow our [issue reporting guideline](https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#reporting-issues).
