### ISSUE TITLE
Follow links in terminal that look like `file(line,col)`

### ISSUE THREAD

**Issue by aliak00** [Microsoft/vscode#58944]
Follow links in terminal that look like `file(line,col)`

They are not linkified.

Sample output:
```
source/optional/optional.d(93,23): Error: cannot implicitly convert expression value of type int[] to immutable(int[])
tests/optional.d(424,11): Error: template instance `optional.optional.Optional!(int[]).Optional.__ctor!(int[], immutable(Optional!(int[])))` error instantiating
tests/optional.d(424,11): Error: none of the overloads of this are callable using argument types (int[]), candidates are:
source/optional/optional.d(97,5):        optional.optional.Optional!(immutable(int[])).Optional.this(const(None) _param_0)
source/optional/optional.d(92,5):  
```

Produced by compiling [D](dlang.org) source code with the `dmd` compiler.

Does this mean adding a regex entry here?: https://github.com/timbanaveen/vscode/blob/3984e251fd64c6e744d5d97d166e2437fb62e819/src/vs/workbench/parts/terminal/electron-browser/terminalLinkHandler.ts#L35

**Comment by aliak00** [comment]
Sorry, forgot:
vscode version: 1.27.2
macOS High Sierra.

**Comment by Tyriar** [comment]
I can't seem to reproduce:

<img width="301" alt="screen shot 2018-09-19 at 7 45 58 am" src="https://user-images.githubusercontent.com/2193314/45760944-18ec2e00-bbe0-11e8-9808-016acb04c812.png">

Note that this only works currently if the _initial_ current working directory is the one that contains `source/` and `tests/` as we don't track the cwd changes yet.

**Comment by aliak00** [comment]
Ah! I see. Ya I seemed to have opened it from a different cwd indeed ! Does
work fine otherwise 🙇‍♂️

**Comment by Tyriar** [comment]
@aliak00 good news 🙂, here's the feature request for tracking the cwd for links https://github.com/Microsoft/vscode/issues/27107
