### ISSUE TITLE
Tasks: non-helpful error message ´The process task system can only execute custom tasks´

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#58941]
1) git clone https://github.com/jrieken/ApplicationInsights-node.js
2) open the package.json
3) hover over the `clean` script
4) execute `Run Script` from the hover

You get the error message

![image](https://user-images.githubusercontent.com/172399/45738992-14307580-bbf2-11e8-86ad-38db72851753.png)

This is caused by the fact that the project contains a v1 tasks.json.

**Comment by dbaeumer** [comment]
Made it more clear that the tasks.json needs to move to version 2.0.0.
