### ISSUE TITLE
Under high memory and CPU usage, the plugin will fail when quickly switching pages

### ISSUE THREAD

**Issue by 1758231591** [Microsoft/vscode#58947]
Issue Type: <b>Feature Request</b>

Above 70% CPU usage, memory usage by more than 85%, when the CPU temperature above 70 °, quickly switch the page, the plugin will failure, need to restart

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

**Comment by octref** [comment]
Please try out [Performance Issue Reporting Guideline](https://github.com/Microsoft/vscode/wiki/Performance-Issues).
