### ISSUE TITLE
"Replace all occurences" desyncs occurences when going to new line by accident

### ISSUE THREAD

**Issue by leoste** [microsoft/vscode#58940]
- VSCode Version: 1.27.2
- OS Version: MacOS High Sierra 10.13.6

Steps to Reproduce:

1. Write the same word in multiple places in your code; make sure that there are separate amount of tabs/spaces in the beginning of each of the lines that the words are in.
2. Use "replace all occurences" on the word and press Enter to go to a new line. All occurences of the word went to a new line, however the amount of whitespace before them stays as it was per word, and is different for each of them.
3. Start deleting characters until you have removed the newly generated lines. During this, you can see that different occurences of the word delete the new line at different times, so when you have gotten rid of the new line for all of them, some of the instances of the word no longer match the others.

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
@leoste sorry I don't quite understand the issue you run into, do you mind sharing a gif or something to help troubleshoot?

**Comment by leoste** [comment]
@rebornix sorry for taking so long to reply. I recorded a video illustrating this issue. https://youtu.be/y3uFcyc-pf0

**Comment by rebornix** [comment]
This is how the multiple cursor works, once you use Replace All Occurrences, then vs code creates cursors for every occurrence, from that moment, every cursor works in their own context.
