### ISSUE TITLE
Don't take focus after --wait

### ISSUE THREAD

**Issue by tollus** [Microsoft/vscode#5894]
- VSCode Version: 1.0.0 (1.0.0)
- OS Version: Mac OSX 10.10.5

Steps to Reproduce:

1. Open VS Code working on a code base.
2. In a terminal window run `code --wait <filename>`
3. (optionally) On the newly opened window, make changes and save
4. Close the newly opened window with `workbench.action.closeWindow`
5. See that instead of letting focus go back to the terminal window, the focus goes to the previous VS Code window.

Is it possible to not take focus after the `closeWindow`?

**Comment by bpasero** [comment]
There is really no way for us to give focus to where you where coming from.

**Comment by tollus** [comment]
Okay, I didn't mean to specifically give focus to something else. I just meant not to take focus after closing a different window. (I didn't know if this was an intentional choice, or OS specific)

Thanks!
