### ISSUE TITLE
Snippets not working when pressing tab before auto-complete appears

### ISSUE THREAD

**Issue by alexanderte** [Microsoft/vscode#58948]
Issue Type: <b>Bug</b>

Not sure if this is considered a bug or a feature request. I have a snippet for `console.log($1)` with prefix `cl`. I would love to and excpect `cl<tab>` to trigger the snippet. However, when doing so two spaces (tab indentation) are inserted instead in most cases. I have to wait for the auto-complete to appear in order for it to work as expected.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.61GB (1.33GB free)|
|Process Argv|C:\Users\Alexander Teinum\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|2.4.2
prettier-vscode|esb|1.6.1
theme-karyfoundation-themes|kar|18.2.1
theme-monokai-pro-vscode|mon|1.1.8

(9 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
Try `editor.tabCompletion: 'onlySnippets'`
