### ISSUE TITLE
OpenEditors shows items when should invisible

### ISSUE THREAD

**Issue by AboElnuoR** [Microsoft/vscode#58951]
Issue Type: <b>Bug</b>

I wanted to hide explorer openEditors using this edit     "explorer.openEditors.visible": 0

But I have openEditors visible with open files appears.
![screenshot-20180919121436-1313x493](https://user-images.githubusercontent.com/16509141/45747605-a0e52e80-bc06-11e8-8d36-6b54b1d291be.png)
this was working in previous versions.

Thanks

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:11:15.873Z)
OS version: Linux x64 4.15.0-34-generic

**Comment by isidorn** [comment]
This works for me.
Just right click on the open editors view -> hide open editors
