### ISSUE TITLE
npm ERR! Code EINTEGRITY 

### ISSUE THREAD

**Issue by RaviRajaM** [Microsoft/vscode#58953]
I was trying to install the npm after the creation of the angular application by using the command 
npm install -g @angular/cli 

then I was getting the following error:
** PS D:\Project\rr> npm install -g @angular/cli@latest
npm ERR! code EINTEGRITY
npm ERR! sha512-z8H8/diyk76B7q5wg+Ud0+CqzcAF3mBBI/bA5ne5zrRUUIvNkJY//D3BqyH571KuAC4Nr7Rw7CjWX4r0y9DvNg== integrity checksum failed
 when using sha512: wanted sha512-z8H8/diyk76B7q5wg+Ud0+CqzcAF3mBBI/bA5ne5zrRUUIvNkJY//D3BqyH571KuAC4Nr7Rw7CjWX4r0y9DvNg== but got
 sha512-SniK8bztT8Gdnh4naDvDF80ePEd5am8p6Gr0jxDjAQbrt0CDXrGE9QcUYWsSTIlKlbsplwFeunOq1gd5QRdrVQ==. (1597 bytes) **

And I need to know the PATH to be added in the Variables section.

**Comment by octref** [comment]
Please open issue for angular-cli.

**Comment by RaviRajaM** [comment]
I got the solution, by giving proper proxy settings
