### ISSUE TITLE
Save/Export/Import preferences

### ISSUE THREAD

**Issue by LuizCostaa** [Microsoft/vscode#58955]
For some reason, if i want to reinstall VS Code, i lose all plugins and personal configs, and need to remember or make a note with plugins i have allready installed.

Not a good idea to make a profile or something like this to save my plugins? Maybe a function to export the users settings, workspace settings and plugin's refference, just for the moment i import, download all again.

Thanks for attention.

**Comment by carlocardella** [comment]
This extension can help: https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync
The Marketplace offers a few different sync extensions if this one does not suits you

**Comment by LuizCostaa** [comment]
wow, i did not know about this plugin, lot of thanks!!
