### ISSUE TITLE
VS Code window won't get focus after opening a file when VS Code is already running

### ISSUE THREAD

**Issue by OndrejVrsan** [Microsoft/vscode#5895]
- VSCode Version: 1.0.0
- OS Version: 6.1. Build 7601

**Steps to Reproduce:**
0. _VS Code is **not** running_
1. Focus File Explorer window
2. Open a file (e.g. A.txt) -> _**VS Code window opens on top and gets focus**_
2. Focus another window, e.g. File Explorer
3. Open another file (e.g. B.txt)

**Actual:**
VS Code icon is shining in taskbar, File Explorer window is still on top

**Expected:**
New VS Code window is opened on top and has focus, just like in step 2

**Note:**
_It works as expected when you met these two conditions
1. in User settings_ `"window.openFilesInNewWindow": false`
_2. After opening file A.txt in step 2 above, you minimize the VS Code window._

**Comment by bpasero** [comment]
Known windows issue, filed already.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/929
