### ISSUE TITLE
100% cpu usage when switching workspace

### ISSUE THREAD

**Issue by af6140** [Microsoft/vscode#58958]
- VSCode Version: 1.27.2
- OS Version:  unbunt 16.04

Steps to Reproduce:

1. Create multiple workspaces that contains multiple folders(git repo)
2. Open on worksapce, navigating around and then switch to another workspace

Does this issue occur when all extensions are disabled?: Yes

Suspicous one is the sql tool, since it's the dangling process after close vscode.

.vscode/extensions/mtxr.sqltools-0.15.0/node_modules/vscode-languageclient/lib/utils/electronForkStart /home/dwang/.vscode/extensions/mtxr.sqltools-0.15.0/dist/languageserver/index.js --node-ipc --clientProcessId=6968

**Comment by octref** [comment]
You can try to use Process -> Open Process Explorer to find out the culprit. If it's not caused by extension, feel free to reopen.
