### ISSUE TITLE
SelectBox: Able to select the separator in drop-down

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#58961]
- Open Debug view or Output panel
- Click on Debug configurations or Output channels

🐛 I can select the separator

![image](https://user-images.githubusercontent.com/10746682/45759520-62f90200-bc28-11e8-9766-2cd7d14d8eeb.png)

**Comment by cleidigh** [comment]
Actually yes in a related context.  The debug viewlet passes a separator even when there are no configurations.  I was going to remove that, at the same time I noticed being able to select it.

Adding to my list.  I'm doing a variety of cleanup since we've had so many additions...

**Comment by bpasero** [comment]
Thanks

**Comment by Tyriar** [comment]
FYI this introduced https://github.com/Microsoft/vscode/issues/59876
