### ISSUE TITLE
N of VS code image run on background process

### ISSUE THREAD

**Issue by vikrantsahoo** [Microsoft/vscode#58967]
I am using Windows 7 and whenever I open VS Code my PC performance went down, when I checked performance monitor my CPU and memory is using all, and in process I found N number of VS Code is running even for one VS Code editor and when I close my Code editor Memory and CPU usage number went down.
Its really very frustrating to work with slower environment, Kindly take a look

**Comment by octref** [comment]
Those are processes that help VS Code perform its functions. Can you follow https://github.com/Microsoft/vscode/wiki/Performance-Issues to report a new issue? Thanks.
