### ISSUE TITLE
File Name can be interpreted as a digit

### ISSUE THREAD

**Issue by jacoby** [Microsoft/vscode#58968]
- VSCode Version:  1.27.2
- OS Version: Ubuntu `6.04 LTS

Steps to Reproduce:

1. Mount a remote file system with SMB
2. make a subdirectory named dev/project2fortress within that filesystem
3. make file with a name like 2551.e1280822 (like TORQUE/PBS STDERR files) in that directory
4. code -n 2551.e1280822

Code interprets that file name as Infinity

Not in ~/. Not in /mount/fs. Not mounting same FS in Windows and opening from Explorer.

But from /mount/fs/dev/project2fortress, for me, every time.

I *believe* it is interpreteing 2551.e1280822 as 2551 to the power of 1280822, which is so huge as to be taken as Infinity.

![infinity](https://user-images.githubusercontent.com/56015/45768948-30d9a700-bc0c-11e8-847f-39b46a83f954.png)

I can route around it most of the time -- I don't do much queue submission -- but it is WAY weird.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jacoby** [comment]
I made another directory named project2fortress.

touch 2541.e10
code -n 2541.e10

File tab says it's 25410000000000, which is 2541 * 10 to the power of 10. 

So you can forget all that stuff about mounting directories

**Comment by jacoby** [comment]
But it is very much via `code <file>`; you can't open from Explorer and get it to work this way.

![replicated](https://user-images.githubusercontent.com/56015/45778491-b5d1ba00-bc26-11e8-8ae3-f350ab81ca8b.PNG)

**Comment by bpasero** [comment]
This is https://github.com/substack/minimist/issues/130
