### ISSUE TITLE
Incorrectly marking JS syntax as invalid

### ISSUE THREAD

**Issue by curxxx** [Microsoft/vscode#58964]
So for some reason this just started a few months ago and has persisted after resetting my Code installation including removing all installed extensions.

I have a .JS file which contains lots of JavaScript, including some jQuery.

Now, for some reason, a few seconds after opening the file, Code marks almost every line as containing a syntax error - incorrectly. The file has no syntax issues whatsoever, which has been confirmed by multiple validators. 

This occurs no matter what type of file Code is treating it as, be it JS or HTML.

It only started happening after an update months ago.

<img width="737" alt="screen shot 2018-09-19 at 11 29 35 am" src="https://user-images.githubusercontent.com/5109969/45764520-e30b7180-bc00-11e8-9800-acc7efee7edb.png">

This screenshot I'm uploading shows the first function in the file, as you can see, it's even marking the word var as invalid...

Honestly, this is making it impossible to be productive using Code and really needs to be fixed ASAP.

**Comment by mjbvz** [comment]
Please share the full text of a minimal piece of code that shows this problem
