### ISSUE TITLE
Exclude the .svn folder from Find in Files by Default

### ISSUE THREAD

**Issue by FranklinWhale** [Microsoft/vscode#5896]
- VSCode Version: 1.0.0
- OS Version: Windows 8.1

Steps to Reproduce:

1. Open a folder with a .svn folder inside in Visual Studio Code 
2. Start Find in Files

Expected Result:

Files in the .svn folder are excluded

Actual Result:

Files in the .svn folder are shown in the search result

I think `.svn/*` should be added to `files.watcherExclude` in default settings

**Comment by bpasero** [comment]
@FranklinWhale good point. I pushed a change to actually exclude it from the explorer too (same as the .git folder).

**Comment by FranklinWhale** [comment]
Thanks!
