### ISSUE TITLE
Menubar does not respond to pen

### ISSUE THREAD

**Issue by soundstripe** [Microsoft/vscode#58970]
Issue Type: <b>Bug</b>

1. Open VS.Code.
2. Touch File menu with tip of stylus.

*Expected Outcome:* File menu is displayed, and a choice can be made with the pen/stylus
*Actual Outcome:* No menu is displayed, Menu header does not highlight. Stylus touch appears to have no effect.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (2.62GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
ibm-developer|IBM|0.0.14
python|ms-|2018.8.0

</details>

**Comment by sbatten** [comment]
@soundstripe Are you using the new custom title/menu bar? Or is this with default settings?

**Comment by soundstripe** [comment]
Default settings—I did install the update and it mentioned a custom menu at but I didn’t configure it.


________________________________

**Comment by sbatten** [comment]
@soundstripe  would you mind trying out the new menu bar by enabling the setting `"window.titleBarStyle": "custom"` and see if the issue is resolved?

**Comment by soundstripe** [comment]
New menu bar works fine with pen for me!


________________________________
