### ISSUE TITLE
Extension Host is unresponsive.

### ISSUE THREAD

**Issue by manikanta-talanki** [Microsoft/vscode#58971]
Issue Type: <b>Bug</b>

Extension Host is unresponsive.

VS Code version: Code - Insiders 1.28.0-insider (45986ca7abf63460dc96409a61fb2f0c98ba0b70, 2018-09-19T09:26:20.526Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 3|
|Memory (System)|16.00GB (0.30GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_1089244808 --inspect-extensions=22282|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.1.0
go-snippets|ban|0.1.2
vscode-django|bat|0.17.0
sqlformatter|bre|0.0.7
better-toml|bun|0.3.2
gotemplate|cas|0.2.0
vscode-markdownlint|Dav|0.20.0
vscode-eslint|dba|1.6.0
jupyter|don|1.1.4
python-extension-pack|don|1.4.0
php-debug|fel|1.12.5
php-intellisense|fel|2.3.5
php-pack|fel|1.0.2
vscode-mysql|for|0.3.0
gc-excelviewer|Gra|2.1.26
beautify|Hoo|1.4.3
rest-client|hum|0.19.1
mysql-syntax|jak|1.3.1
google-complete-me|jay|1.0.6
dupchecker|jia|0.0.9
golang-tdd|joa|0.0.9
ruby-markers|jua|0.2.1
goa-snippets|kaw|0.0.7
MagicPython|mag|1.0.12
python|ms-|2018.8.0
atom-keybindings|ms-|3.0.4
Go|ms-|0.6.89
go-doc|msy|0.1.1
vscode-docker|Pet|0.2.0
material-icon-theme|PKi|3.6.0
quicktype|qui|12.0.42
ruby|reb|0.20.0
java|red|0.31.0
annotator|ryu|0.11.0
jenkinsfile-support|sec|0.1.0
vscode-spotify|shy|2.6.1
vscodeintellicode|Vis|1.0.4
vscode-java-debug|vsc|0.13.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.8.0
vscode-maven|vsc|0.11.0
vscode-react-native|vsm|0.6.16
jinja|who|0.0.8
markdown-all-in-one|yzh|1.6.1
vscode-proto3|zxh|0.2.1

</details>

**Comment by octref** [comment]
Please follow our [issue reporting guideline](https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#reporting-issues).
