### ISSUE TITLE
Terminal resize slow with high CPU usage

### ISSUE THREAD

**Issue by ProTip** [Microsoft/vscode#58975]
Since upgrading from 1.25.1 there have been a number of performance related issues with the terminal:
- #57279
- #56628

It appears the performance issues related to typing in the terminal have been resolved, however the high CPU usage and slowness when resizing the terminal persists for me. I have downgraded to `1.25.1` and back up to confirm the issue was not present in that version.

The problem has all the hallmarks of triggering a refresh on the terminal too often on element resize, however I have not profiled or otherwise confirmed this.

Info:
- VSCode Version: 1.27.2
- OS Version: Ubuntu 16.04(VirtualBox)

Steps to Reproduce:
1. Launch vscode
2. Open the terminal and create a lot of lines in the output(can just press enter a lot)
3. Resize the terminal window from the top or the side sash; witness lag and high CPU usage

**Comment by Tyriar** [comment]
The high CPU usage is due to a lot of things that need to happen when the terminal is resized, and this problem is amplified when you have more terminals. https://github.com/xtermjs/xterm.js/blob/290c95ad71f8b1264139a7ed6f070c4741a8987e/src/Buffer.ts#L112

We're working on improvements, see:

- https://github.com/xtermjs/xterm.js/issues/791
- https://github.com/xtermjs/xterm.js/issues/1685
- https://github.com/xtermjs/xterm.js/issues/622

**Comment by ProTip** [comment]
Is this a known performance regression from `1.25`? I'm only using one terminal per the repro steps, and this issue is not present in `1.25`.

**Comment by ProTip** [comment]
@Tyriar there is severe lag in both resizing and scrolling when the terminal is filled with text that is not present in version `1.25`. Running with `code --ignore-gpu-blacklist` does not appear to resolve the issue, and I have not seen this particular regression addressed or acknowledged in the other issues. Should I open a new issue that's more explicit about this being a performance regression from `1.25`, or is this known?

**Comment by Tyriar** [comment]
@jrieken I notice that in 1.25 we seem to debounce the window resize event and only reflow when no changes come in after a short period, but not in 1.28? Do you know more about this change?

**Comment by jrieken** [comment]
> Do you know more about this change?

No, maybe @bpasero

**Comment by bpasero** [comment]
@Tyriar code proof?

**Comment by Tyriar** [comment]
@bpasero @jrieken I'm not seeing this anymore, feel free to unsubscribe.

@ProTip I notice no major difference in performance between the two, in fact 1.28 seems to be a little faster (as expected), at least on mac. Could you record a performance trace of the issue you're seeing, save and upload it? https://developers.google.com/web/tools/chrome-devtools/evaluate-performance/timeline-tool

**Comment by Tyriar** [comment]
Actually, this is almost certainly to do with the update from Electron 1.7 to Electron 2. Closing this in favor of the issues mentioned in https://github.com/Microsoft/vscode/issues/58975#issuecomment-422930957, plus https://github.com/Microsoft/vscode/issues/52629

**Comment by ProTip** [comment]
I may still get a perf cap if you are interested. For what it's worth, I see this issue in my XUbuntu 16.04 VM but not on OSX.
