### ISSUE TITLE
DevTool hijacks input

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#58973]
1.27.2 or Insider:

- Open DevTools
- Focus editor
- Start typing

Expected: Characters shown in editor
Actual: Characters shown in DevTools

**Comment by alexandrudima** [comment]
@octref I cannot reproduce

![58973](https://user-images.githubusercontent.com/5047891/45783236-81312300-bc65-11e8-89ea-4af03cf8147e.gif)

**Comment by octref** [comment]
Interesting, I noticed it requires 2 specific behavior to repro:

1. You need to have the devtool undocked beforehand. Try to undock it, reload VS Code and open devtool to repro it.
2. Help -> Toggle Developer Tools does it, but my shortcut Cmd+Shift+I doesn't.

Peng also noticed it doesn't repro on Windows.

![devtool](https://user-images.githubusercontent.com/4033249/45786146-f67c0400-bc23-11e8-8809-9cc2c70960ab.gif)

**Comment by octref** [comment]
Findings this morning with @roblourens:

- While in the corrupted state, VS Code window is not focused (notice the titlebar color) although it is brought to the foreground on click.
- While in that state, clicking on activity bar icons to bring out viewlets works, but focusing into any input field in Search viewlet doesn't work.
- I cannot repro it on my own laptop.
- When I try to do `code --disable-extensions --user-data-dir repro`, it does not repro on first launch. But if I close VS Code and relaunch, I can repro it.
- Finally I tried restarting my Mac. After that I cannot repro the bug any more.

I'll keep an eye on it if it comes back again. 

Wondering why all the mystic bugs happen to my Mac...https://github.com/Microsoft/vscode/issues/11654
