### ISSUE TITLE
Windows Environment Variables

### ISSUE THREAD

**Issue by jsloyer** [Microsoft/vscode#5897]
- VSCode Version: latest
- OS Version: Windows

I was looking into how to get user environment variables on Windows and it looks like vscode currently doesnt support that, https://github.com/Microsoft/vscode/blob/5b9ec15ce526decc5dd0488339e798f6bcb4ec46/src/vs/base/node/env.ts#L17.  If this is the intention would you be ok if I opened a PR for reading Windows envars or is there another means inside of vscode to get environment variables such as `HOMEDRIVE`, `HOMEPATH`, and `USERPROFILE`?

**Comment by bpasero** [comment]
@jsloyer they should be present out of the box, otherwise please file a bug.

@joaomoreno fyi

**Comment by jsloyer** [comment]
awesome yeah that worked.  I was trying to get them through the contextservice but calling `process.env` works with those vars
