### ISSUE TITLE
Styled components doesnt offer preview of the colors

### ISSUE THREAD

**Issue by edoantonioco** [Microsoft/vscode#58977]
So on CSS on vscode next to the colors that you write (like background-color: #ffffff) appears a small box that shows what color it is about.

But on styled components, at least on ReactJS (react native), there is no small box that let me know what color I am typing.

So it would be nice to get that feature that you already implemented on CSS, to have it available on styled components on javascript.

**Comment by mjbvz** [comment]
This should come from an extension. Here's a feature request tracking it for the styled components extension: https://github.com/styled-components/vscode-styled-components/issues/95
