### ISSUE TITLE
duplicate files open one in normal case and one in lower case

### ISSUE THREAD

**Issue by graph** [Microsoft/vscode#58988]
Version: 1.27.2 (system setup)
Commit: f46c4c469d6e6d8c46f268d1553c5dc4b475840f
Date: 2018-09-12T16:17:45.060Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

On windows 10

Steps to Reproduce:

1. create and open eXAmple.cpp (case sensitive)
2. make compiler output an error with by printing in lowercase. Sometimes MSVC does this for some reason I don't know exactly why. For simplicity you can just setup an echo command to give a bogus error.
3. Check the problems tab after compiling now click on the problem.
4. Observe that now you have 2 tabs of the same file open.

When searching CTRL+SHIFT+F you will get 2 of the same results as VSCode thinks those are different files.

**Comment by octref** [comment]
Well, it's not that hard to repro...

- Create foo.txt
- `mv foo.txt FOO.txt`
- Now you can open two tabs for the same file.

I have run into this problem myself.
