### ISSUE TITLE
'Unable to open' error if local relative URL path has query string as part of path

### ISSUE THREAD

**Issue by Howshall** [Microsoft/vscode#5898]
- VSCode Version: 1.0.0
- OS Version: Windows 8.1 Enterprise

I received consistent "Error Unable to open '...'" error when trying to Ctrl+click to open URL in locally saved HTML document with valid relative path to other locally saved document IF the file path included query string contents on it (e.g. ?skin=1242&pcl=true ) 
As soon as end query string was removed VSCode was able to open the file fine. See below for steps to reproduce.

Steps to Reproduce:
1. Create a new empty HTML document on local file system with the following contents:

`<!DOCTYPE HTML>`
`<html>`
`<head>`
`<meta http-equiv="Content-Type" content="text/html; charset=utf-8">`
`<title>Untitled Document</title>`
`</head>`
`<body>`
`<iframe id="iframe" src="iframe/2044v01.html?skin=1242&pcl=true" style="width:100%;" frameborder="0">`
`Your browser does not support iFrames, please instead <a href="iframe/2044v01.html?skin=1242&pcl=false">continue to card entry</a> in full screen mode`
`</iframe>`
`</body>`
`</html>`
1. Create a new empty HTML document on local file system inside relative 'iframe' sub directory with '2044v01.html' filename to match above example code. Contents of this 2nd HTML file doesn't matter.
2. Open Step 1 HTML file in VSCode editor and try to Ctrl+Click on either IFRAME src= or A href= URLs and VSCode will report a "Unable to open '2044v01.html?skin=1242&pcl=false': File not found (c:\Users\700952470\Documents_Projects\BT MyDonate Appeals__SVN Repository\mdft-html-templates\donate\sa2016\iframe\2044v01.html?skin=1242&pcl=fal.." error message
3. If you however edit the URLs in Step 1 HTML from with Query string 'iframe/2044v01.html?skin=1242&pcl=true' to just 'iframe/2044v01.html' then VSCode will open linked page fine on Ctrl+Click

So it appears that current v1.0.0 of VSCode gets confused if there is a query string on filenames and incorrectly says that file can't be opened, even though shown local path is correct and intended file is present in that location.

![error unable to open screenshot](https://cloud.githubusercontent.com/assets/13105488/14857723/3a363e9a-0c95-11e6-994e-184333f86a58.JPG)

**Comment by jrieken** [comment]
The problem see to be [this](https://github.com/Microsoft/vscode/blob/master/src/vs/languages/html/common/htmlWorker.ts#L579) inside the html worker. It takes the path derived from the token content (which includes the query) and sets it as uri path - hence the encoding.

**Comment by alexandrudima** [comment]
The html language is now owned by @aeschli

**Comment by aeschli** [comment]
Tested in 1.12. We now correctly try to open `iframe/2044v01.html`, ignoring the query parameter.
