### ISSUE TITLE
Overriding index signatures

### ISSUE THREAD

**Issue by BobFrankston** [Microsoft/vscode#58991]
I'm sure this has been discussed but I can't find it.

The Index signature is a very useful feature but the current implementation runs into the power of JavaScript objects in being able to have exceptions. I'm using a file generated by EXIFTOOL which is a JSON dump of meta information from images. So it makes sense to declare a string indexer. But when it comes to linking I want to add extra fields but indexers are fighting me. Why?

```
interface exentry {
    [key: string]: string,
    SourceFile: string;
    FileName: string;
    Directory: string;
    byProp: any;    // Really { [prop: string]: byProperty }
    nearby: any; //  exentry[];
}
```
There are complex work-arounds but why impose old school rigidity on the structures? At very least there should be an allow exceptions option in the config since this is a style issue and some of see the ability to add extra bags of goodies to an object as a feature not a bug.

Note that I explicitly declare some entries for clarify. I would like to have a way to say I must use [] for indexers rather than just the . notation so as to protect myself from typos by listing the common cases.

At least indexers aren't as bad as C# dynamic types which require everything have an override.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#27228
