### ISSUE TITLE
Building windows binary uses electron icon instead of vscode icon

### ISSUE THREAD

**Issue by jsloyer** [Microsoft/vscode#5899]
- VSCode Version: latest
- OS Version: Windows server 2k12

Steps to Reproduce:

1. Run `gulp vscode-win32`
2. The created binary uses the electron icon instead of [the vscode icon](https://github.com/Microsoft/vscode/blob/master/resources/win32/code.ico)

**Comment by joaomoreno** [comment]
We use [rcedit](https://github.com/atom/node-rcedit/tree/master/bin) to patch the icon. Make sure it executes in your machine.

**Comment by joaomoreno** [comment]
Did you find the root cause?

**Comment by jsloyer** [comment]
I installed rcedit and after the binary is built with `gulp vscode-win32` I run the following.  It might be worthwhile updating the wiki with this.

```
rcedit '..\VSCode-win32\VSCode.exe' --set-icon resources\win32\code.ico
```

**Comment by joaomoreno** [comment]
You shouldn't need to do that manually. `gulp vscode-win32` will do that for you... I'm curious in knowing why it didn't
