### ISSUE TITLE
VScode will not permit long file names

### ISSUE THREAD

**Issue by adamsteer** [Microsoft/vscode#58993]
Using VScode Version 1.27.1 (1.27.1), on MacOS High Sierra (10.3.6), with a HFS+ formatted volume:

VScode reports that my filenames need to be less than 31 characters long.

This is not a restriction inherent in MacOS, or other systems being interacted with (eg github; other Linux platforms).

Ideally, VScode would permit whatever the underlying OS/filesystem permits.

**Comment by isidorn** [comment]
This works for me. Can you please add some reporducable steps
Can you repro with vscode insiders https://code.visualstudio.com/insiders/
![screen shot 2018-09-21 at 10 06 05](https://user-images.githubusercontent.com/1926584/45868444-fa279c00-bd85-11e8-9867-312cb99fb34a.png)
