### ISSUE TITLE
Settings UI - Not Showing Language Specific fields

### ISSUE THREAD

**Issue by pxwee5** [microsoft/vscode#58995]
Issue Type: <b>Bug</b>

User settings JSON:
```
  "[javascript]": {
    "editor.tabSize": 2,
    "editor.insertSpaces": true
  },
  "[php]": {
    "editor.tabSize": 2,
    "editor.insertSpaces": true
  },
```

Settings UI - Not showing language specific fields at all. Just a general tab size. 
![image](https://user-images.githubusercontent.com/14123790/45788139-da806d00-bccc-11e8-9116-363f783295c6.png)

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:04:11.329Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.82GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
html-css-class-completion|Zig|1.17.1
html-snippets|abu|0.2.1
silverstripe|adr|0.0.5
vscode-sqlite|ale|0.3.1
vscode-intelephense-client|bme|0.8.8
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.6.0
gitlens|eam|8.5.6
prettier-vscode|esb|1.6.1
graphql-for-vscode|kum|1.12.1
php-import-checker|mar|0.1.3
php-namespace-resolver|Meh|1.1.0
vetur|oct|0.12.6
highlight-matching-tag|vin|0.4.4
ReactSnippets|xab|2.2.0

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Yes, this is not supported. We consider this an advanced feature and you will still have to use the json settings editor for this.

**Comment by devuxer** [comment]
@roblourens,

The problem is not really the need to edit a JSON file, it's that the feature is not discoverable, and therefore it appears that the global`tabSize` setting is malfunctioning. This was driving me crazy with YAML files, until I finally reported it as an issue (#69011) and was informed about the back-door YAML `tabSize` setting.

It's OK to have advanced settings but not when a hidden advanced setting overrides the behavior of a regular setting. So, these settings either should appear in the UI or an additional `obeyGlobalTabSize` setting (which defaults to `true`) should be added to each editor.

**Comment by kertzi** [comment]
I have same annoying type problem as in [#69011](https://github.com/microsoft/vscode/issues/69011)
But with .yml files specifically, .yaml works. When I want set tabSize to 2 it always resets to 4 which is not configured anywhere I can find. I have tried to go thru workspace/user/global settings without luck. 

Here is snippet from my user settings.json:
`   
 "files.associations": {
      "*.yaml": "yaml",
      "*.yml": "yaml"
    },
    "[yaml]": {
        "editor.detectIndentation": true,
        "editor.insertSpaces": true,
        "editor.tabSize": 2,
        "editor.autoIndent": "none",
    },
`
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:07:18.473Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

**Comment by rzhao271** [comment]
Merging to #131707.
