### ISSUE TITLE
"Unable to open 'rpc.proto': File not found (filepath) error every time I open the program, due to a reorg

### ISSUE THREAD

**Issue by jamesray1** [Microsoft/vscode#58996]
Issue Type: <b>Bug</b>

I get three file not found errors every time that I open the program.

E.g.:

"Unable to open 'rpc.proto': File not found (file:///home/james/Rust/jrl/floodsub/rpc.proto)."

This file still exists but just has a different path due to a restructure of the workspace.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:11:15.873Z)
OS version: Linux x64 4.14.69-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5 CPU       M 560  @ 2.67GHz (4 x 1198)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|3.72GB (0.11GB free)|
|Process Argv|/opt/visual-studio-code/code|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
rust|rus|0.4.10
vscode-proto3|zxh|0.2.1

</details>

**Comment by octref** [comment]
It should go to https://github.com/rust-lang-nursery/rls-vscode.
