### ISSUE TITLE
Add onDidStopChangingTextDocument

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#590]
_From @Krzysztof-Cieslak on October 26, 2015 15:23_

Idea is to add new event on workspace which will fire whenever user stop editing document for X milliseconds.

The problem with `onDidChangeTextDocument` is that it fires on every key stroke what is often not necessary (or not possible for more expensive / longer operations).

Implementing it is easy (just a timeout (re)started on every `onDidChangeTextDocument` ) but I think it would be nice to have built-in helper for it in API.

_Copied from original issue: Microsoft/vscode-extensionbuilders#61_

**Comment by seanmcbreen** [comment]
_From @jrieken on November 3, 2015 11:33_

We have utilities that allow to delay event execution and event merging. I am more in favour of making that a node module such that it can be used by any event consumer.

**Comment by seanmcbreen** [comment]
Did we end up publishing a module for this I should add to my spell checker so it's a little less eager :)

**Comment by seanmcbreen** [comment]
_From @jrieken on November 12, 2015 21:14_

Not yet...

**Comment by jrieken** [comment]
This should be an external library (node_module) that enriches events, debouncing, filtering, mapping, etc. Our goal is to keep the API small and keep the amount of util-functions to a minimum. Therefore the library-approach. Closing because the change will happen in another repo
