### ISSUE TITLE
Entering “Tab” is always moving focus instead of  inserting a tab in code.

### ISSUE THREAD

**Issue by Lynn-cc** [Microsoft/vscode#59008]
- VSCode Version: 1.27.1
- OS Version: windows7

Steps to Reproduce:

1.C-M or not，entering  ‘tab’ is always moving the focus。
2.

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by alexandrudima** [comment]
@Lynn-cc I cannot reproduce. When I open for example an untitled file and press <kbd>Tab</kbd> I get the `\t` character or 4 spaces (depending on my settings) inserted in the editor.

**Comment by Lynn-cc** [comment]
@alexandrudima How could I show you this problem ? It do happens anytime, Even I closed all the project and restarted the VSCode and opened a new file. Make a video?

**Comment by alexandrudima** [comment]
@Lynn-cc Does this reproduce if you disable all extensions? What is shown in the keybindings editor (ctrl+k ctrl+s) if you search for <kbd>Tab</kbd>:

![image](https://user-images.githubusercontent.com/5047891/45882255-e132e100-bdad-11e8-92ef-e403abc307e0.png)

**Comment by Lynn-cc** [comment]
- yes
- show these lines

![image](https://user-images.githubusercontent.com/540202/45923680-fe3af180-bf1e-11e8-909f-6e4ca6fa18c2.png)

**Comment by alexandrudima** [comment]
@Lynn-cc By using `Control-M` it is possible to toggle the behaviour of <kbd>Tab</kbd>. Does your status bar show "Tab Moves Focus"?

![image](https://user-images.githubusercontent.com/5047891/46598707-55c38a80-cae5-11e8-8526-1490db043b1f.png)

Alternatively, you can execute F1 > Toggle Tab Key Moves Focus

This toggles the <kbd>Tab</kbd> key between trapping focus (inserting the `\t` character or spaces) and moving focus.

**Comment by ben-powley** [comment]
Hey @alexandrudima 

I'm experiencing this issue as well. I'm running version 1.28.0.

Unfortunately, I'm not able to reliably replicate it but sometimes when I hit tab when my cursor is at the start of a new line, it removes focus from the main editor window.

When I'm having the issue, toggling tab mode with Control-M does not change the behaviour and both modes seem to remove focus.

If I'm able to reliably reproduce it, I'll add a comment with the steps I took.

Thanks

**Comment by Lynn-cc** [comment]
@alexandrudima I do see the label at the status bar, but nothing changed. The 'tab' key always moves the focus whenever the label shows or not.

**Comment by alexandrudima** [comment]
@Lynn-cc "Tab Moves Focus" is a **mode** that is entered manually. i.e. when VS Code starts up, it is not in this mode. This mode is entered through the action "Toggle Tab Key Moves Focus" which is bound out-of-the-box to <kbd>Ctrl</kbd>+<kbd>M</kbd>.

To leave this mode, it is possible to run the same action again, i.e. "Toggle Tab Key Moves Focus" or <kbd>Ctrl</kbd>+<kbd>M</kbd> again. It is also possible to click on the green indication from the status bar to leave this mode.

If you enter this mode accidentally and you don't find it useful, perhaps you are pressing <kbd>Ctrl</kbd>+<kbd>M</kbd> by accident. It is possible to remove this keybinding from the Keybindings Editor (Ctrl+K Ctrl+S) > Search for the action > Right click > Remove Keybinding. This should hopefully make it that you never end up in this mode by accident.

**Comment by Lynn-cc** [comment]
@alexandrudima I think a gif I made could explain everything:
[record](https://i.postimg.cc/cJ8CXNWC/record.gif)

I just want to add 'tab' in my files for better coding experience, but VSCode can't do it now.
