### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by VNXtreme** [Microsoft/vscode#59005]
Issue Type: <b>Performance Issue</b>

Happen: after recent update and a little while of usage.
Edited: RAM goes high. VS code has taken almost 50% CPU without me doing anything. Code suggestion no longer works.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G3240 @ 3.10GHz (2 x 3093)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.92GB (3.86GB free)|
|Process Argv|D:\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    86	  4740	code main
    1	    68	  8828	   window (Issue Reporter)
    1	   132	 11040	   gpu-process
    0	   181	 11456	   window (carousel-home.blade.php - hoangkhangevent - Visual Studio Code)
    0	    36	  3968	     searchService
    0	    12	  4544	     electron-crash-reporter
    0	    13	  8152	     watcherService 
    0	     9	  2576	       console-window-host (Windows internal process)
   41	    65	 12324	     extensionHost
    0	    71	  3048	       electron_node htmlServerMain.js 
    0	    70	  4588	       "D:\Programs\Microsoft VS Code\Code.exe" "d:\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain" --node-ipc --clientProcessId=12324
    0	    65	 11640	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (carousel-home.blade.php - hoangkhangevent - Visual Studio Code)
|    Folder (hoangkhangevent): 9393 files
|      File types: php(7020) md(245) phpt(227) js(196) json(187) test(177)
|                  xml(165) txt(114) yml(98) jpg(87)
|      Conf files: makefile(4) package.json(2);
```

</details>
<details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
es7-react-js-snippets|dsz|1.8.6
vscode-phpmd|eco|1.1.0
prettier-vscode|esb|1.6.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
beautify|Hoo|1.4.3
vscode-phpfmt|kok|1.0.30
php-namespace-resolver|Meh|1.1.0
php-docblocker|nei|1.6.0
laravel-blade|one|1.18.0
colonize|vms|2.2.2

</details>

**Comment by octref** [comment]
What's the perceived performance issue? Anything that becomes slow?

@aeschli Since its seems to come from htmlServer.

**Comment by VNXtreme** [comment]
RAM goes high. VS code has taken almost 50% CPU without me doing anything. Code suggestion no longer works

**Comment by aeschli** [comment]
@VNXtreme Can you open the VSCode process explorer (Help > Process Explorer) and see which VSCode process is busy?
