### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by indraraj26** [Microsoft/vscode#59004]
- VSCode Version: 1.27.2
- OS Version:

![image](https://user-images.githubusercontent.com/23274631/45792150-35ed3380-bcaa-11e8-8517-7c48b87dfda8.png)

![image](https://user-images.githubusercontent.com/23274631/45792160-400f3200-bcaa-11e8-93b6-7ed8ba6e8a81.png)

Steps to Reproduce:

Add this following extension in your VS code studio and do some work you will get popup of extension host terminated unexpectedly in within 10 mins
1.
![image](https://user-images.githubusercontent.com/23274631/45792567-e6a80280-bcab-11e8-91c8-56b05f432219.png)

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by octref** [comment]
I suggest that you report this to https://github.com/angular/angular. They have a bunch of issues for its language service: https://github.com/angular/angular/issues?q=is%3Aopen+is%3Aissue+label%3A%22comp%3A+language-service%22
