### ISSUE TITLE
Keybindings with when clause editorTextFocus is being ignored for some key combinations when terminal is focused

### ISSUE THREAD

**Issue by btruhand** [Microsoft/vscode#59012]
- VSCode Version: 1.27.2
- OS Version: MacOS High Sierra 10.13.6

I have my own user-defined keybinding for moving line up and down. For me I like to set it to `shift+j` and `shift+k`. I've set up the `when` clause to be `"editorTextFocus && !editorReadOnly && vim.mode != 'Insert'"` for both of them. However when I type `shift+k/j` in the integrated terminal, unexpectedly the lines in opened editor also starts to move.

This does not happen if I change the input command to `shift+up/down` weirdly enough

Steps to Reproduce:

1. Go to your keybindings
2. Create a user keybinding for editor.action.moveLinesDownAction and editor.action.moveLinesUpAction with the inputs `shift+j` and `shift+k` respectively
3. Open a file and fill in some lines
4. Open an integrated terminal and type either one of the inputs above

Here is a GIF recording of it to showcase what happens http://g.recordit.co/L2RdfI0B59.gif

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
@btruhand , You'll need to add those actions to "terminal.integrated.commandsToSkipShell" in your user settings. Related #19770

**Comment by btruhand** [comment]
Tried adding "editor.action.moveLinesUpAction" and "editor.action.moveLinesDownAction" to "terminal.integrated.commandsToSkipShell" but still pressing `shift+j` or `shift+k` causes the lines in the editor to move up/down

**Comment by Tyriar** [comment]
@btruhand does it work without the `when` clause, or with a simplified one?

**Comment by alexr00** [comment]
@btruhand , I misread your issue. You want to make sure "editor.action.moveLinesUpAction" and "editor.action.moveLinesDownAction" are **not** in "terminal.integrated.commandsToSkipShell". I'm also interested in @Tyriar 's question about the when clause. Does this still happen if you remove `vim.mode != 'Insert'"`?

**Comment by btruhand** [comment]
@Tyriar @alexr00 sorry just got back, but yes to both of your queries

I tried changing to `alt+j` and `alt+k` and those work as expected (typing in terminal doesn't cause the lines in editor to move up/down)
