### ISSUE TITLE
fold code

### ISSUE THREAD

**Issue by baobz** [Microsoft/vscode#59014]
- VSCode Version:1.27.2
- OS Version:

Steps to Reproduce:

1. Fold the code in vscode, close vscode and open it again, the code is not folded
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by aeschli** [comment]
That's already implemented and should work. I tried with the latest insiders and all looked good to me.

Do you have the same file open in two editors? Did you make modifications to the file while VSCode was closed?

**Comment by baobz** [comment]
Thank you for your reply.I will check again if it is related to settings or plug-ins
----- 原始邮件 -----
发件人：Martin Aeschlimann <notifications@github.com>
收件人：Microsoft/vscode <vscode@noreply.github.com>
抄送人：baobz <baobz@sina.cn>,  Author <author@noreply.github.com>
主题：Re: [Microsoft/vscode] fold code (#59014)
日期：2018年09月21日 15点19分

That's already implemented and should work. I tried with the latest insiders and all looked good to me.
Do you have the same file open in two editors? Did you make modifications to the file while VSCode was closed?

&mdash;

**Comment by aeschli** [comment]
closing. please reopen if you see this again and have steps to reproduce
