### ISSUE TITLE
syntax highlighting has a problem in identifying vue.js‘s file

### ISSUE THREAD

**Issue by PeterChen1997** [Microsoft/vscode#59010]
- VSCode Version:1.24.1 (1.24.1)
- OS Version: macOS High Sierra (10.13.6)

Steps to Reproduce:

1.git clone git@github.com:vuejs/vue.git
2.open file src/core/vdom/create-elemenet.js and scroll to line 55

Does this issue occur when all extensions are disabled?: Yes/No

YES

![image](https://user-images.githubusercontent.com/21072589/45797807-e9b9e780-bcd9-11e8-9a19-1ce977a832f5.png)

and the github.com syntax highlighting works fine

![image](https://user-images.githubusercontent.com/21072589/45797842-1837c280-bcda-11e8-9fb0-e25f744a4517.png)

**Comment by mjbvz** [comment]
Try  installing a flow syntax highlighting extension and then set the language mode on the file to `flow`. We don't support flow out of the box

**Comment by PeterChen1997** [comment]
Hi mjbvz, i think it's real a problem for flow

before:
![image](https://user-images.githubusercontent.com/21072589/45856831-bb471580-bd88-11e8-811a-5e33811449d8.png)
after:
![image](https://user-images.githubusercontent.com/21072589/45856899-095c1900-bd89-11e8-971f-91def5040bb4.png)

and i fixed it by using this extesion:https://marketplace.visualstudio.com/items?itemName=joshpeng.sublime-babel-vscode

but i think it's not prettiy as before..
