### ISSUE TITLE
VS code shuts down while hovering over help menu

### ISSUE THREAD

**Issue by BIMSOMS** [Microsoft/vscode#59013]
Issue Type: <b>Bug</b>

cklick the help menu and hover over the entries for a couple of minutes. VS code shuts down without any message 

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.86GB (27.00GB free)|
|Process Argv|C:\Users\...\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
pascal|ale|6.4.0
better-toml|bun|0.3.2
vscode-nupkg|eri|0.0.8
vscode-solution-explorer|fer|0.2.33
innosetup|idl|1.2.0
csharpextensions|jch|1.3.0
vscode-nuget-package-manager|jmr|1.1.6
vscode-csproj|luc|0.7.0
dotenv|mik|1.0.1
vscode-language-pack-de|MS-|1.27.2
python|ms-|2018.8.0
vscode-ai|ms-|0.2.0
cpptools|ms-|0.18.1
csharp|ms-|1.16.1
notepadplusplus-keybindings|ms-|1.0.2
PowerShell|ms-|1.8.4
team|ms-|1.136.0
vscode-json-editor|nic|0.2.0
quicktype|qui|12.0.42
addlocalnetreferences|Raf|0.0.3
rust|rus|0.4.10
crates|ser|0.3.2
vscode-hexdump|sle|1.6.0
vsc-jsonsnippets|wmo|0.1.4

</details>

**Comment by octref** [comment]
Are you using the custom title bar?

**Comment by sbatten** [comment]
If you are using the custom titlebar, this is new, but if you are using native, this is likely caused by #55347

**Comment by BIMSOMS** [comment]
Hi Pine,I'm using out of the box vs code. Mit freundlichen GrüßenMatthias SchneiderBüro für Ingenieurdienstleistungen Matthias Schneider | Am Spritzenmättle 1 | 77704 Oberkirch | Germany | tel.: (+49) 7802 803 450 | mobile: (+49) 152 285 285 22e-mail: info@BIMSO.de | web: www.BIMSO.de | Steuer-Nr.: 14408/38006 | USt-IdNr.: DE264666650 | Bankverbindung: Volksbank Offenburg | BLZ: 66490000 | Konto: 50044807Pine <notifications@github.com> hat am 20. September 2018 um 20:38 geschrieben:  Are you using the custom title bar?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by sbatten** [comment]
Out of the box 1.27.2 indicates you are using the native title bar and native menu bar. As a workaround you can enable the custom title bar now via the setting `window.titleBarStyle` by changing it to `custom`. The issue with the native bar is https://github.com/Microsoft/vscode/issues/55347
