### ISSUE TITLE
Clarify how to use previewHtml command within documents being previewed

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#5902]
Testing #5747

Tried to follow the example given in https://github.com/Microsoft/vscode/issues/3676#issuecomment-209953630.

The only way I could get a link to be previewed correctly (when being followed from within the preview is the following (externalFileUri is a string):
`<a href="command:vscode.previewHtml${encodeURIComponent(JSON.stringify(externalFileUri))}">htmlPreview of the file on disk</a>`.

Same for virtual documents.

- VSCode Version: 1.1.0-alpha e77003fd6ca90d944feb572b54fc1d122d91d704
- OS Version: MacOS

**Comment by jrieken** [comment]
I will update the docs around the preview command

**Comment by jrieken** [comment]
The doc is [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostApiCommands.ts#L160) from which  @gregvanl will generate this page: https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands
