### ISSUE TITLE
connect launcher timeout

### ISSUE THREAD

**Issue by ly1016799291** [Microsoft/vscode#59029]
Issue Type: <b>Bug</b>

The runtime is not connected to launcher 10060, but right click can run in the terminal. 

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) m3-6Y30 CPU @ 0.90GHz (4 x 1512)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.91GB (0.92GB free)|
|Process Argv|D:\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.26.3
python|ms-|2018.8.0
python|tht|0.2.3

(1 theme extensions excluded)

</details>

**Comment by weinand** [comment]
pls file against Python extension

**Comment by ly1016799291** [comment]
Thank you for your answer. Next I will continue to try to find its solution.
