### ISSUE TITLE
使用vscode写js文件变卡了

### ISSUE THREAD

**Issue by shengaiyishi** [Microsoft/vscode#59024]
您好，最近使用vscode for Mac版本才写了4000行的js文件，写代码的时候会有卡的现象，比如说，点击折叠代码的+没有任何效果，或者写了一个fun也没有任何提示，插件才装了16个

**Comment by af6140** [comment]
Translation here: Recently he wrote a js(javascript) file with vscode for Mac, in the process he experienced pauses/lags. For example, when click on the folding "+" symbol and nothing happened. Some times there is no code completion prompt. He has 16 plugins installed.

**Comment by mjbvz** [comment]
Closing as we cannot investigate this issue without more information, such as if this happens when extensions are disabled
