### ISSUE TITLE
Git: Support glob patterns in 'git.ignoredRepositories'

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#59020]
From https://github.com/Microsoft/vscode/issues/45098#issuecomment-422594343

cc @jd-carroll

**Comment by ParkourKarthik** [comment]
@joaomoreno I tried the `npm link` for a module with git. But, VSCode doesn't recognise the git repository of the linked module as it exists under `node_modules` which is ignored in `.gitignore`.
Have there been any recent changes regarding this? Or Am I missing something here?
If this is the expected case, let me know how the glob patterns should actually work?

Note: `Auto Repository Detection` settings is set to `true`

**Comment by joaomoreno** [comment]
If you open a file within that repo, does the repo get recognized?

**Comment by ParkourKarthik** [comment]
I tried opening and changing the file even within that repo, the repo or the changes were not recognized in the workspace.

**Comment by memeplex** [comment]
Here is an even more basic request to support tilde expansion:

https://github.com/microsoft/vscode/issues/73608

**Comment by r44083** [comment]
Hi, could you please also add support of relative git.ignoredRepositories path? So it could be possible to add ignored repository in the following way:
```
"git.ignoredRepositories": ["./openwrt"]
or 
"git.ignoredRepositories": ["${workspaceFolder}/openwrt"]
```
instead of
```
"git.ignoredRepositories": ["/home/username/some/absolute/path/openwrt"]
```

**Comment by crazy-matt** [comment]
Hi guys,
Could this one be added in the next year roadmap?

**Comment by hongwen000** [comment]
2 years later, request for this issue to open again.

**Comment by michalfita** [comment]
It has my vote to be reopened as well. This feature doesn't seem to be well known, but it's flawed without globs.

**Comment by kszonek** [comment]
Same here, seems crucial in some usecases

**Comment by SplitGemini** [comment]
Reopen please.
