### ISSUE TITLE
Mix on inline/external defined properties corrupt javascript intellisense

### ISSUE THREAD

**Issue by mobisga** [Microsoft/vscode#59033]
Issue Type: <b>Bug</b>

Defining a variable:
var test = { prop1: '' }; test.prop2 = '';
intellisense does NOT recognize prop2 as a property belonging to test

Whereas defining:
var test = {  }; test.prop2 = '';
intellisense does recognize prop2 as a property belonging to test as it should

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500T CPU @ 2.70GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.85GB (9.39GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Users\_\Desktop\KeyEventsRuleTest.html|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.10
tslint|eg2|1.0.39
csharp|ms-|1.16.1
debugger-for-chrome|msj|4.10.1

(1 theme extensions excluded)

</details>

**Comment by mobisga** [comment]
![jsvscodebadintellisense](https://user-images.githubusercontent.com/43438245/45811831-78c10280-bcce-11e8-9c4d-a3488770608d.png)
![jsvscodeokintellisense](https://user-images.githubusercontent.com/43438245/45811833-78c10280-bcce-11e8-8159-7d464cf4b5e9.png)

**Comment by yoyo837** [comment]
Hey guy, why is this closed?

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#27245
