### ISSUE TITLE
V 1.27.2: Go To Definition Not Working (Javascript)

### ISSUE THREAD

**Issue by may215** [Microsoft/vscode#59039]
Issue Type: **Bug**

Right-click on Javascript method of class
Select Go-To-Definition
UI reports definition doesn't exist.

- VSCode Version: 1.27.2
- OS Version: Ubuntu 16.04

Does this issue occur when all extensions are disabled?: Yes

**List of extensions:**
christian-kohler.npm-intellisense@1.3.0
christian-kohler.path-intellisense@1.4.2
donjayamanne.githistory@0.4.2
DotJoshJohnson.xml@2.3.2
EditorConfig.EditorConfig@0.12.4
eg2.tslint@1.0.39
jhessin.node-module-intellisense@1.6.0
leizongmin.node-module-intellisense@1.5.0
mauve.terraform@1.3.4
mike-co.import-sorter@2.0.4
mikestead.dotenv@1.0.1
ms-python.python@2018.8.0
ms-vscode.Go@0.6.89
msjsdiag.debugger-for-chrome@4.10.1
Orta.vscode-jest@2.9.0
PeterJausovec.vscode-docker@0.2.0
PKief.material-icon-theme@3.6.0
redhat.vscode-yaml@0.0.16
streetsidesoftware.code-spell-checker@1.6.10
vsmobile.vscode-react-native@0.6.17

**Comment by mjbvz** [comment]
Please provide a code example or small example project that demonstrates the problem
