### ISSUE TITLE
Distraction free mode: hide comments

### ISSUE THREAD

**Issue by flddr** [Microsoft/vscode#59032]
Today most lines in code are comments - about 70-80%? It becomes harder and harder to view the real things, scrolling and eye-filtering increases more and more. Because _comments_ themselves are recognizable in _every_ language - would it be possible to become a switch like **hide comments** in VS Code? As every IDE would need that, it would be fantastic if VS Code becomes the first one that implement this :1st_place_medal:

**Comment by aeschli** [comment]
You can fold all comments with the `Fold comments` command.

https://github.com/Microsoft/vscode/issues/40338 is about being able to define an initial folding state.

**Comment by flddr** [comment]
Thats not what i want. Look at UWP apps - between every line is now a folded comment line. Thats not nice :-1: 

Whats the problem to hide comments?
