### ISSUE TITLE
debugging

### ISSUE THREAD

**Issue by pxlotus** [Microsoft/vscode#59034]
We have written the needed data into your clipboard because it was too large to
Issue Type: <b>Bug</b>

my debug after the update is nolonger fast. it continually stops the launch with .json'settings. how can i improve that?

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU  N3060  @ 1.60GHz (2 x 1600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.91GB (0.57GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-django|bat|0.17.0
django-html|bib|1.2.0
django-snippets|bib|1.1.0
django|big|1.0.0
vscode-styled-jsx|bla|1.0.0
vscode-postgres|cko|1.1.1
python-snippets|cst|0.2.0
jupyter|don|1.1.4
python-extension-pack|don|1.4.0
vscode-html-css|ecm|0.2.0
sass-lint|gle|1.0.3
svn-scm|joh|1.36.2
saltstack|kor|0.0.5
node-module-intellisense|lei|1.5.0
MagicPython|mag|1.0.12
anaconda-extension-pack|ms-|1.0.0
python|ms-|2018.8.0
cpptools|ms-|0.18.1
csharp|ms-|1.16.1
PowerShell|ms-|1.8.4
vsliveshare|ms-|0.3.709
team|ms-|1.136.0
vscode-yaml|red|0.0.16
vscode-icons|rob|7.26.0
python|tht|0.2.3
vscodeintellicode|Vis|1.0.4
vscode-wakatime|Wak|1.2.3
jinja|who|0.0.8
html-css-class-completion|Zig|1.17.1

</details>
 send. Please paste.

**Comment by roblourens** [comment]
I don't understand the issue. Can you explain in more detail?
