### ISSUE TITLE
VS Code won't update

### ISSUE THREAD

**Issue by lifesthateasy** [Microsoft/vscode#59031]
Issue Type: <b>Bug</b>

I get a popup telling me to restart VS Code to update it. I click restart, VS Code quits. Nothing happens for minutes. I start VS Code again, same message. This has happened on previous versions, too, only way to update was to remove the installation and reinstall the newest version from scratch.

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:14:32.385Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz (4 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 7|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
ftp-sync|luk|0.3.3
python|ms-|2018.8.0
debugger-for-chrome|msj|4.10.1
python|tht|0.2.3

</details>

**Comment by mxschmitt** [comment]
Looks like your System is out of Memory. (8.00GB (0.03GB free))
That could be the reason, that the updater cannot be started.

**Comment by joaomoreno** [comment]
Please check whether Code is in quarantine. Check https://github.com/Microsoft/vscode/issues/7426#issuecomment-277737150
