### ISSUE TITLE
Provide a way to dismiss the COMPARE message without comparing files

### ISSUE THREAD

**Issue by rojorojo** [Microsoft/vscode#5903]
- VSCode Version: 0.10.15-insider
- OS Version: Windows 10.0.10586

My example is related to the package.json file. 
Steps to Reproduce:

1. Open package.json and make a change but don't save
2. Install new node packages
3. Note the opened file does not update with the new changes, attempt to save

Note there will be a prompt that says changes on disk are newer than the open file and give you the ability to compare the two. But what if the user is not interested in comparing and simply wants to close the file without saving. While closing the file without saving is possible there seems to be no way to dismiss the "compare" prompt without clicking the compare button. 

See image: ![vscode-insider-compare-message](https://cloud.githubusercontent.com/assets/1466812/14859796/640eed2c-0c6b-11e6-9b65-21b8e26ead03.png)

It would be nice to have a way to dismiss this message without having to go into compare mode.

**Comment by bpasero** [comment]
@rojorojo does `Revert File` work?

**Comment by rojorojo** [comment]
Yes it works perfectly. But the prompt still remains on the top of the screen. I think adding an "X" or "CLOSE" next to the compare button would solve the problem I am trying to describe.

**Comment by bpasero** [comment]
I think the right thing is to close the message once you revert.

**Comment by bpasero** [comment]
Well actually we could just have the revert action in the message :)

**Comment by rojorojo** [comment]
In my case I didn't want to take any action on the file (but the message was forcing me to). I just wanted to close and reopen it.

**Comment by bpasero** [comment]
@rojorojo how would that work though, there are changes you did and changes on disk.

**Comment by isidorn** [comment]
@bpasero I still get the same message, is this expected?

![screen shot 2016-05-06 at 14 15 50](https://cloud.githubusercontent.com/assets/1926584/15072725/136acbf8-1395-11e6-8a28-7de1338bf82a.png)

**Comment by bpasero** [comment]
@isidorn yes sure the message is still there but it should go away automatically once e.g. you revert your dirty changes.

**Comment by harikiran019** [comment]
i am not able to save my changes because of this error message. please help me with the steps to disable this message.

**Comment by bpasero** [comment]
@harikiran019 when do you get it?

**Comment by harikiran019** [comment]
when i try to save my changes, i get this message to compare and after comparing i cant save it because it keeps asking me the same message again and again. 

Works, when I have to revert my changes and then update my code again with the changes i have made. this process is consuming more time though.

**Comment by bpasero** [comment]
@harikiran019 this sounds like I fixed this for the current milestone already (insiders). 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders
