### ISSUE TITLE
Status bar appearance not restoring after debugging program terminates

### ISSUE THREAD

**Issue by YangHanlin** [Microsoft/vscode#59037]
- VSCode Version: 1.28.0-insider (user setup)
- OS Version: Windows 10.0.17760.1

Steps to Reproduce:

1. Start debugging any C++ program (I meet this problem when debigging C++, **but I am not sure whether it occurs when programming with other languages**);
2. You will see the status bar change color;
3. Terminate the built executable and exit debugging;
4. You will **not** see the status bar restore to its initial appearance.

Does this issue occur when all extensions are disabled?: Yes when I did not disable the extension *cpptools*, as I cannot start debugging without it.

**Update:**
I just found that when you start debugging again, **the appearance of the status bar will return to normal just before the build task before debugging runs**.

**Comment by weinand** [comment]
@isidorn I can reproduce this in today's Insiders on Windows.

**Comment by isidorn** [comment]
@YangHanlin hanks for using insiders and for filling timely issues like this, it is very valuable to us

**Comment by YangHanlin** [comment]
@weinand @isidorn Thank you all for timely fix for this bug : )
