### ISSUE TITLE
Issues with "Jump to definition" CSS links introduced in August release

### ISSUE THREAD

**Issue by juanpablob** [microsoft/vscode#59046]
- VSCode Version: 1.27.2
- OS Version: macOS 10.13.6

Steps to Reproduce:

1. Create a CSS file called `hello-world.scss/css`
2. Create another CSS file, and put `@import 'hello-world.scss`
3. After ⌘/Ctrl + clicking the path, you'll get this error: `Unable to open 'hello-world': File not found (file:///fakepath/css/hello-world).`

While naming `hello_word.scss` don't trigger any error. As I can guess, the regex in charge is missing filenames with dashes in between.

Cheers!

**Comment by octref** [comment]
Duplicate of #58204.
