### ISSUE TITLE
Node Debug Auto-attach

### ISSUE THREAD

**Issue by psummitt** [Microsoft/vscode#59048]
- Extension Name: debug-auto-launch
- Extension Version: 1.0.0
- OS Version: Linux x64 4.18.7-200.fc28.x86_64
- VSCode version: 1.28.0-insider

 We have written the needed data into your clipboard. Please paste:```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 8,
		"activateCallTime": 1,
		"activateResolvedTime": 0,
		"activationEvent": "*"
	}
}
```

**Comment by octref** [comment]
Pleas follow our [issue reporting guideline](https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#reporting-issues).

**Comment by psummitt** [comment]
You are really helpful, octref.  Thanks.
