### ISSUE TITLE
Mac git enter passphrase no input

### ISSUE THREAD

**Issue by aryarovana** [Microsoft/vscode#59045]
Hey sorry if it's a duplicate or something been bugging me for more than a year and can't figure this thing out:

https://ibb.co/jBs4We

I can't seem to figure out how to fix it, every other git app works fine, but I prefer to use my IDE for most of my development process.

when I type "git pull" in the embedded terminal of vscode things work fine, but when I use the Command Palette "Git Pull" this dialogue comes up and I have no way of inputting my passphrase.

when I google this problem nothing even remotely related comes up, am I the only one who has this problem ?

**Comment by joaomoreno** [comment]
Try adding your ssh key to the ssh agent: https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#adding-your-ssh-key-to-the-ssh-agent

This will simply avoid asking for the passphrase in the future.

**Comment by aryarovana** [comment]
Sir, you are a life saver. No matter how i searched I didn't come across this.
There was other results about adding to keychain, which I did the instructions but they didn't work. 
Thanks a lot!

still though isn't showing a window asking for a passphrase and not giving the user any option to input that passphrase a bug ?

**Comment by joaomoreno** [comment]
Sure, we have another open issue for that. Glad I could help.
