### ISSUE TITLE
Git: Support sync cancellation

### ISSUE THREAD

**Issue by eli-crow** [microsoft/vscode#59047]
I'd like to be able to cancel running tasks in the source control panel. I use a VPN for work and sometimes forget to connect to it. I try syncing the repo, which obviously doesn't work, then connect to the VPN, then have to wait ~30 seconds for the source control panel task to timeout to be able to use it again. This happens daily.

**Comment by joaomoreno** [comment]
Added the following setting to enable this: `git.supportCancellation`.
