### ISSUE TITLE
acceptSuggestionsOnEnter: smart not working properly

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#59044]
Have `"acceptSuggestionsOnEnter": "smart"`
Open a javascript file and type `console`, notice how I get auto intelisense. After `console` is typed press `enter`, I would expect a new line to be entered, however the suggestion is accepted which is not what the setting is supposed to do.
This is particularly noticable when using the debug console.
This was working before, so it feels like a regression.

![smart](https://user-images.githubusercontent.com/1926584/45826509-e849e880-bcf4-11e8-9cdd-827f65aabab2.gif)

**Comment by jrieken** [comment]
works for me

**Comment by isidorn** [comment]
@jrieken did you try with an emtpy user dir and just with that setting? Because it easily reproduces for me than.
You can also drop by my machine to investigate more.

**Comment by jrieken** [comment]
Ok, now I can repro... It depends on what element is focused, what suggestions you have, and when a suggestion is focused. It seems that I don't receive a focus change event when the same element is being refocused...

**Comment by jrieken** [comment]
Seems to be triggered by [this **two** year old line of code](https://github.com/Microsoft/vscode/blob/3a3284a8e3ed67b8129db58c4733da50be9d30f2/src/vs/editor/contrib/suggest/suggestWidget.ts#L569-L571)

**Comment by isidorn** [comment]
Works nicely now, thanks
