### ISSUE TITLE
Allow for block relation line colors.

### ISSUE THREAD

**Issue by erickbrenesLT** [microsoft/vscode#59043]
I am trying to see if you can update the colors for each block relation line. Similar to how [Bracket Pair Colorizer](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer) extention works when coding JS in VSCode. Nothing is more annoying than tracking the same color line down. As you can see in the pic they are all light gray. It would be nice to have a couple different colors... like grandparent = light green, parent light blue, child light red - repeat down or the option to put 3 colors of your choice in.

Stackoverflow - https://stackoverflow.com/questions/52415082/how-can-you-change-the-block-relation-line-colors-in-vs-code?noredirect=1#comment91776609_52415082

<img width="158" alt="esili" src="https://user-images.githubusercontent.com/31771611/45824332-62f31380-bcb5-11e8-8cf8-e73b8414273b.png">

**Comment by okonon** [comment]
that would be nice!

**Comment by erickbrenesLT** [comment]
Alex Myers, on my stackoverflow post (linked above), gives a nice working around using the Bracket Pair extension. The fix is close, but not the actual lines.  It is still better than nothing.

**Comment by hediet** [comment]
This is basically #122193, but relative to the active indentation and not to the root.

I think that could cause some noise when the cursor moves around.
