### ISSUE TITLE
Unable to use HelpMessage attributes in the VSCode terminal

### ISSUE THREAD

**Issue by shaneis** [Microsoft/vscode#59042]
There does not appear to be any current issues for this.

- VSCode Version: 1.27.2 (user setup)
- OS Version: Windows 10 Pro

**About VSCode:**

Version: 1.27.2 (user setup)
Commit: f46c4c469d6e6d8c46f268d1553c5dc4b475840f
Date: 2018-09-12T16:17:45.060Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Steps to Reproduce:

1. Create an advanced function including a parameter with a HelpMessage and Mandatory attribute.
2. Run the function and type '!?' to try and receive the help message.

```
function Test-ParametersAndPrompts {
    [cmdletbinding()]
    param(
        [parameter(Mandatory, HelpMessage = 'Enter the location of the folder.')]
        [string]
        $Path
    )

    process {
        $path
    }
}
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by rjmholt** [comment]
This is a PowerShell extension feature request. I've moved the issue over to https://github.com/PowerShell/vscode-powershell/issues/1538. This issue can be closed
