### ISSUE TITLE
Please add MIME type for .code-workspace file

### ISSUE THREAD

**Issue by galgalesh** [microsoft/vscode#59040]
A Visual Studio Code workspace file is currently recognised in Linux as a normal plain text file. This is because there isn't a MIME type for this file. Applications can provide additional MIME types as described here: 

https://developer.gnome.org/integration-guide/stable/mime.html.en

Not having a MIME type has a couple of issues, for example the files are shown as plain text files in the GUI, which makes it hard to distinguish source code files from the workspace file. This slows down navigating to a workspace and opening it.

*Find the workspace in the following screenshot*

![image](https://user-images.githubusercontent.com/1492981/45818239-6a301680-bce1-11e8-8770-984d9127bda8.png)

It's currently impossible to theme such a file because it's not seen as a different MIME type: https://github.com/snwh/suru-icon-theme/issues/87#issuecomment-417743275

**Comment by mgabeler-lee-6rs** [comment]
This also means that you can't make double clicking the workspace from a file browser open it in vscode, unless you're OK with all text files opening in vscode, which is probably not what most folks want.

**Comment by joaomoreno** [comment]
Hi @galgalesh, can you verify this issue? Check out the previous comment.

**Comment by connor4312** [comment]
I tried to verify this but am not sure how to do this myself. I've not used desktop linux extensively; I tried reinstalling Insiders from the `.deb` to see if it associated `.code-workspace` files with VS Code, but that didn't happen.
