### ISSUE TITLE
[v1.27.2] Source file links still not clickable.

### ISSUE THREAD

**Issue by AlCalzone** [Microsoft/vscode#59052]
Followup to https://github.com/Microsoft/vscode/issues/54788, https://github.com/Microsoft/vscode/issues/57987 and https://github.com/Microsoft/vscode/issues/58256
I'm using version v1.27.2 now and the issue still persists. This is a huge pain in a monorepo I'm currently working on. What more information can I provide you guys with to get this resolved?

cc @Tyriar

**Comment by Tyriar** [comment]
@AlCalzone 

1. What directory did you open the terminal in?
2. Is the link you're pointing at relative to the directory the terminal was opened in?
3. Can you provide a screenshot?

**Comment by AlCalzone** [comment]
1. like I wrote in https://github.com/Microsoft/vscode/issues/57987#issue-357364727, its a kinda long path with a space in it: `C:\users\....\Something with space\Repositories\repo-name`. This is the directory I open inside VSCode. I then press <kbd>CTRL</kbd> + <kbd>ö</kbd> (german version) to open the terminal in that directory.
2. Yes, inside the directory is (among others) a directory `src`. I then run the typescript compiler, which finds an error in a file and prints a link to there: `src/folder/filename.ts:1234:1`. This link is not clickable.
3. I'm currently on another machine where there's no space in the root directory name. Here it works:
![unbenannt](https://user-images.githubusercontent.com/17641229/45863309-dfe5c200-bd75-11e8-9af5-6093837d4d7b.png)
I'll provide a screenshot from my other machine where its not working later today as I don't have access right now. Not sure how much that helps you though, as you won't see the underline or the tooltip.

**Comment by Tyriar** [comment]
@AlCalzone a screenshot would still be helpful, just make sure you launch the terminal in the same way. I don't think there is anything that would make directories with spaces in the path not work 🤔

**Comment by Tyriar** [comment]
I can repro on Windows 7, everything seems to work fine until the path with the space in the root path appears. Also it doesn't appear to be related to the @ symbol or the line/col annotation but the spaces as you suggest.

**Comment by Tyriar** [comment]
It's happening because this `exec` is returning the path before the first space and then goes on to fail validation:

https://github.com/Microsoft/vscode/blob/079518239fa8643678b74ef87fbe687ce760e3c7/src/vs/workbench/parts/terminal/electron-browser/terminalLinkHandler.ts#L304-L310

**Comment by Tyriar** [comment]
I think this issue will have to be solved when the link system is improved in https://github.com/Microsoft/vscode/issues/21125, I'll make a note over there about this case.
