### ISSUE TITLE
ES5 Exports No Longer Colored Properly

### ISSUE THREAD

**Issue by nathanjd** [Microsoft/vscode#59055]
The preferred pattern for es5 exports is no longer colored properly. I expect this to either:

1. Be colored properly.
2. Allow for switching code coloring from es6 to es5 mode.

https://nodejs.org/api/modules.html#modules_exports_shortcut

- VSCode Version: Version 1.27.2 (1.27.2)
- OS Version: 10.12.6 (16G1408)

Steps to Reproduce:

1. Create a file with the following content:

```javascript
module.exports = exports = function foo(bar) {
    const {
        bar,
        baz,
        "qu-ux": quux
    } = {bar};
};

```

2. See that code coloring breaks due to considering the `export` portion of `exports` as an es6 keyword rather than an es5 global variable.

Screenshot of the bad coloring. Sorry that I can't figure out how to get a proper inline image url from google drive.

[https://drive.google.com/open?id=1wI23SqWRtP5_ENV5B28kxhpIMVVcxHZr](https://drive.google.com/open?id=1wI23SqWRtP5_ENV5B28kxhpIMVVcxHZr)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This is fixed in the current vscode insiders builds:

<img width="491" alt="screen shot 2018-09-20 at 3 05 29 pm" src="https://user-images.githubusercontent.com/12821956/45849421-b29e0300-bce6-11e8-9415-3a7f126c3262.png">

**Comment by nathanjd** [comment]
Thanks! Apologies for the non-valid javascript in the example. I'll make sure to test the insider build before submitting and further issues.
