### ISSUE TITLE
[ts]

### ISSUE THREAD

**Issue by mahmad-labib** [Microsoft/vscode#59051]
Issue Type: <b>Bug</b>

errors every where for nothing at typescript files

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-6410 APU with AMD Radeon R5 Graphics     (4 x 1996)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|4.94GB (1.43GB free)|
|Process Argv|C:\Users\Mahamad Labib\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
auto-rename-tag|for|0.0.15
vscode-language-babel|mgm|0.0.20
vscode-docker|Pet|0.2.0
vscode-icons|rob|7.26.0
ayu|tea|0.16.0
vscode-react-native|vsm|0.6.17

</details>

**Comment by mjbvz** [comment]
Please see this guide on what to include in a proper issue report: https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests

Start with reproducible steps and what you expected versus what you actually saw.
