### ISSUE TITLE
Debugger doesn't hit breakpoints when running Jest tests

### ISSUE THREAD

**Issue by rswerve** [Microsoft/vscode#59056]
Issue Type: <b>Bug</b>

Trace attached.
[debugadapter.txt](https://github.com/Microsoft/vscode/files/2402407/debugadapter.txt)

Steps to Reproduce:

1.   Write Jest tests
2.  Set breakpoints in the tests
3.  Use launch.json to run the tests

The breakpoints say "breakpoint set but not yet bound" and remained grayed out for the duration of the tests.

I'd expect the breakpoints to be hit.  Console.log in the files with breakpoints do work and the tests run properly.  This persists when all extensions are disabled.  

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:04:11.329Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.39GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_19890935|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
sort-lines|Tyr|1.7.0
vscode-eslint|dba|1.6.0
xml|Dot|2.3.2
tslint|eg2|1.0.39
macros|ged|1.2.1
beautify|Hoo|1.4.3
docthis|joe|0.7.1
terraform|mau|1.3.4
vs-code-quick-require|mil|0.2.4
prettify-json|moh|0.0.3
vsliveshare|ms-|0.3.709
debugger-for-chrome|msj|4.10.1
vetur|oct|0.12.6
partial-diff|ryu|1.4.0
code-settings-sync|Sha|3.1.2

(7 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/54485

I don't see the files with breakpoints being loaded. What's your launch config like? Have you seen the docs?

**Comment by rswerve** [comment]
I have read the docs, but the tests are running as expected, so I'm not sure what "loaded" means here.

I think the launch config is in the trace, but here it is, including commented options that I tried changing to no avail.

        {
            "type": "node",
            "request": "launch",
            "name": "Jest Tests",
            "program": "${workspaceRoot}/node_modules/platform-vic/lib/index",
            "args": [
                "test"
            ],
            "runtimeArgs": [
                "--nolazy"
            ],
            "protocol": "inspector",
            "console": "integratedTerminal"
            // "runtimeVersion": "10.10.0",
            // "cwd": "${workspaceRoot}",
            // "preLaunchTask": null,
            // "runtimeExecutable": null,
            // "env": { "NODE_ENV": "test" },
            // "internalConsoleOptions": "openOnSessionStart",
        }

I'm passing "test" to our test-runner, which then runs Jest.

**Comment by roblourens** [comment]
I meant to paste the link to the Jest docs for vscode in my last comment, and left it out by mistake. https://jestjs.io/docs/en/troubleshooting#debugging-in-vs-code

They recommend using `"--runInBand"`, normally it spawns a new process for the test code, which is just what the log shows. That flag loads the test code in the process which is being debugged.

**Comment by rswerve** [comment]
Thanks, I had seen those docs and had tried "--runInBand".  Attached is the trace of trying that again just now, which unfortunately didn't make a difference (I can see that the test files are being run one-by-one, so it has an effect, but the breakpoints still aren't hit.)
[debugadapter.txt](https://github.com/Microsoft/vscode/files/2403578/debugadapter.txt)

**Comment by roblourens** [comment]
I don't see runInBand being used in that log

```
From client: launch({
    "type": "node2",
    "request": "launch",
    "name": "Jest Tests",
    "program": "/Users/matighi/mercury/grid-screener-vic/node_modules/platform-vic/lib/index",
    "args": ["test"],
    "runtimeArgs": ["--nolazy"],
    "protocol": "inspector",
    "console": "integratedTerminal",
    "trace": true,
    "cwd": "/Users/matighi/mercury/grid-screener-vic",
    "internalConsoleOptions": "neverOpen",
    "logFilePath": "/Users/matighi/Library/Application Support/Code/logs/20180913T153123/ms-vscode.node-debug_2/debugadapter.txt",
    "__sessionId": "2f4e28ec-9665-46b2-8118-4e4b8e334482"
})
```

**Comment by rswerve** [comment]
Yeah, it’s passed in by our test runner.  I wonder if that test runner is the problem.  Breakpoints in that do get hit.

**Comment by roblourens** [comment]
Oh, so you're debugging something that then spawns jest? In that case, the debugger is not attached to the process actually running the tests.

**Comment by rswerve** [comment]
Yes, that’s correct.

**Comment by Contrapuntist** [comment]
Don't know if this is related, but it's driving me crazy.  I'll set breakpoints in my test file and when I launch the debugger, the breakpoints will change.  Its been happening to me all week.   

I'm new to working with the VSCode debugger. I thought it was something I was doing.  But maybe it's something else. 

Set before launch. 
![test_breakpoints_set_before_launch](https://user-images.githubusercontent.com/6516311/45896516-f736a680-bd99-11e8-9f28-369331ce7cc4.PNG)


what happens after launch:  
![breakpoints after launch](https://user-images.githubusercontent.com/6516311/45896554-17666580-bd9a-11e8-9d81-8cb2b7a5cfc8.PNG)

The above happens with and without the Jest extensions enabled.  I thought it might be the extension, so I turned it off. It's still occurring.  

I've had a couple different configurations, but this is the most current, which is taken from Jest website: 
    {
      "name": "Debug Jest Tests",
      "type": "node",
      "request": "launch",
      "runtimeArgs": [
        "--inspect-brk",
        "${workspaceRoot}/node_modules/jest/bin/jest.js",
        "--runInBand"
      ],
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      "port": 9229
    },

**Comment by roblourens** [comment]
@Contrapuntist please open a new issue. A repo where I can see the issue would be great.

@rswerve I don't know what your setup is exactly, but you'll have to change it somehow such that the jest process is the thing that's started in debug mode. If you can change it to pass `--inspect-brk=<some port>` to the jest process, and add that port num to your launch config, that may work.

**Comment by rswerve** [comment]
I’ll try that.  Thanks.

**Comment by ryanwmarsh** [comment]
@roblourens @rswerve did this get resolved? I'm having the same problem.
