### ISSUE TITLE
[search] Add option to exclude globs from .gitignore

### ISSUE THREAD

**Issue by guywald1** [Microsoft/vscode#59057]
Currently, when searching, it is only possible to have all the globs to exclude in a single input.

A toggle to also exclude files from `.gitignore` would be really useful.

**Comment by roblourens** [comment]
This is supported by default, assuming you  have not turned off the `search.useIgnoreFiles` setting, or turned off the "Use Exclude Settings and Ignore Files" button (bottom right)

![image](https://user-images.githubusercontent.com/323878/37785522-9b4d3162-2db7-11e8-9011-5ca513e789b9.png)

**Comment by guywald1** [comment]
Wow, TIL 😅 I barely use the search panel (use vim for searching) but tried giving it a shot and with a stroke of brilliance didn't assume it could be in the settings.
It is turned on by default but did not work earlier for some strange reason, probably my fault.

Thanks, closing.
