### ISSUE TITLE
Syntax highlighting messed up after 1.27.2 update.

### ISSUE THREAD

**Issue by KashyapCKotak** [Microsoft/vscode#59053]
Does this issue occur when all extensions are disabled?: Yes

After I recently updated my VS code, all the syntax highlighting is messed up. I have some file with HTML, a bit of PHP and JS contained in it and all the JS code is white. also in files with on JS code (.js files), the syntax highlighting is not working. Attached the screenshot:
![image](https://user-images.githubusercontent.com/20476571/45834263-535ee380-bd24-11e8-88ee-b485d3435e08.png)

My file is greater than 300 lines.

**Comment by mjbvz** [comment]
Please share the text of the code along with screenshots

**Comment by oneslash** [comment]
Additionally would be useful to share the name of your theme

**Comment by KashyapCKotak** [comment]
Thanks for looking into it.
I have already attached the screenshot... May be you missed?
The theme that I am using is Visual Studio Dark theme.

**Comment by oneslash** [comment]
@KashyapCKotak, to debug it would be useful if you attach code as a text.

**Comment by KashyapCKotak** [comment]
Here is a sample code copied from internet for demonstration purpose:
var rows = prompt("How many rows for your multiplication table?");
    var cols = prompt("How many columns for your multiplication table?");
    if(rows == "" || rows == null)
   		 rows = 10;
    if(cols== "" || cols== null)
   		 cols = 10;
    createTable(rows, cols);
    function createTable(rows, cols)
    {
      var j=1;
      var output = "<table border='1' width='500' cellspacing='0'cellpadding='5'>";
      for(i=1;i<=rows;i++)
      {
    	output = output + "<tr>";
        while(j<=cols)
        {
  		  output = output + "<td>" + i*j + "</td>";
   		  j = j+1;
   		}
   		 output = output + "</tr>";
   		 j = 1;
    }
    output = output + "</table>";
    document.write(output);
    }


This was placed in a file called sample.js and below is how it looks in vs code:
![image](https://user-images.githubusercontent.com/20476571/45892198-0b53c580-bde5-11e8-95e5-2b357493dac4.png)

Only strings and var/for/while/function are colored.

**Comment by yogeshkotadiya** [comment]
There is nothing wrong with syntax highlighting in VSCode, you are using 'Dark theme' which have minimum syntax highlighting support try switching to 'Dark+' or any other dark theme.

**Comment by KashyapCKotak** [comment]
Oh Yes!! That was silly... Thanks for pointing out... Not sure how my theme was changed from Dark+ to VS dark after update though...
