### ISSUE TITLE
Way to disable horizontal scrolling

### ISSUE THREAD

**Issue by matsieftw** [Microsoft/vscode#59054]
I currently have word wrap on, but my files still horizontal scroll unnecessarily. This is especially evident when I use a Mac Magic Mouse. I'd love to be able to toggle the horizontal scrolling off completely (regardless of whether I have word wrap on).

**Comment by alexandrudima** [comment]
@matsieftw Can you provide steps? Do you use a font which is non-monospace?

**Comment by matsieftw** [comment]
I am using BlexMono Nerd Font Mono font. I would like to be able to disable horizontal scrolling.

**Comment by alexandrudima** [comment]
Let's track in #2654

**Comment by alexandrudima** [comment]
@matsieftw I've reopened this issue to try to figure out what is your unique problem. Can you post a screenshot?
