### ISSUE TITLE
Unable enter text or navigate with the keyboard

### ISSUE THREAD

**Issue by aardvarkk** [Microsoft/vscode#59062]
Issue Type: <b>Bug</b>

I was editing a specific file and was trying to append to the end of a line. I could type a period, but as soon as I went to type the remainder of the word, the navigation would lock up and no longer accept my text. I could edit the file fine in NVim. I tried disabling all of my extensions, but the problem persisted. The UI is still responsive, but none of my insertion commands are being respected. I can change my selection with something like Command-A (to select all), and it responds and shows the selection, but if I type something to replace it, it just sits there as if nothing happened. Very strange, but makes the editor unusable right now!

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:04:11.329Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 3|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-database|baj|1.5.2
rails|bun|0.8.1
vscode-gemfile|bun|0.0.2
gitlens|eam|8.5.6
go-to-spec|Lou|0.1.2
rails-run-spec-vscode|nok|0.1.2
ruby|reb|0.20.0
vim|vsc|0.16.4

</details>

**Comment by rebornix** [comment]
@aardvarkk can you type in other UI components? Like the terminal, input box of Find Widget or Search viewlet?

**Comment by aardvarkk** [comment]
Yes — typing into other components is fine. And some keyboard commands (Select All) operate correctly. I can select all and then tab/untab and that works. But as soon as I try to type, nothing happens.

**Comment by alexandrudima** [comment]
Does typing work if you disable the vim extension?

**Comment by aardvarkk** [comment]
Actually yes, that fixes the issue.

I had mistakenly said before that I had tried disabling all extensions, but I had neglected to *reload after disabling them*. Disabling the vim extension fixes the issue, and I can type again.
