### ISSUE TITLE
`editor.selectionClipboard: false` still copies to clipboard when selecting text in global Search sidebar

### ISSUE THREAD

**Issue by Arnavion** [Microsoft/vscode#59065]
- VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:11:15.873Z)
- OS version: openSUSE Tumbleweed, KDE PlasmaShell, X11

Steps to Reproduce:

1. Set `editor.selectionClipboard` to `false` in user settings.
1. Copy something to the primary buffer from another application, like double-clicking some text in a terminal.
1. Invoke the global Search sidebar (<kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>F</kbd>) and type some text into the textbox.
1. Select all the text in the textbox (<kbd>Ctrl</kbd>-<kbd>A</kbd>) and delete it (<kbd>Del</kbd>).
1. Press middle mouse button in the textbox with the intention to paste the text from step 2. The text that you deleted in step 4 gets pasted instead. The act of selecting the existing test in step 4 overwrote what was in the primary buffer from step 2, even though the `editor.selectionClipboard` setting was false. This can also be verified by middle-click-pasting in any other application.

This does not happen in the regular code tabs, only in the Search sidebar. That is, selecting text in a regular code tab does *not* automatically copy that text to the primary buffer. It also does not happen with the textbox in the "Extensions" sidebar, so it doesn't seem to be a general problem with all sidebars.

I don't *think* this is the same as #49305, since that one is about middle-click-pasting from the primary buffer and implies the setting is broken everywhere, whereas this issue is about selections getting *copied* to the primary buffer and is only broken in the Search sidebar.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
The search sidebar doesn't use the `editor.selectionClipboard` but it also doesn't explicitly put selected text in the clipboard. Is it possible that's an OS feature? That textbox is a normal html <input>, if you see the same on webpages I would expect it to work the same. I'm not familiar with how this feature is supposed to work.

**Comment by Arnavion** [comment]
It's an OS feature, yes. In that case, why does it not behave the same for the textbox in the Extensions sidebar?

**Comment by roblourens** [comment]
Because that's actually not a native `<input>` but an instance of the editor that is capable of using that setting.

I'm not sure whether it's possible for us to turn it off for every native input field in the electron window. @Tyriar any idea?

**Comment by Arnavion** [comment]
Okay, thanks. If you can't figure out a way of disabling it for the Search sidebar textbox you can close this issue. I'm investigating how to disable the feature globally in KDE anyway.

**Comment by Tyriar** [comment]
I don't think `editor.selectionClipboard` was meant to disable the feature outright, but allow the feature to be turned off _within the editor_ on performance grounds. The only reason the setting exists at all is because monaco is not a standard text input and has to do a bunch of work to get it working.

This is as designed, I'm not even sure we could disable it if we wanted to since it's an OS-level thing and we're build on the web platform.
