### ISSUE TITLE
Option to disable Image Preview's Zoom on Click

### ISSUE THREAD

**Issue by cdeutsch** [Microsoft/vscode#59068]
I love that there is a way to preview an image in VS Code and the default zoom is spot on, unfortunately I spend a ton of time having to reset the zoom, because I accidentally zoom in when I click back on to the editor. 

It'd be great if there was an option to disable that feature and just allow zooming via keyboard or from the bottom menu.

**Comment by innerlee** [comment]
This feature is very useful!
Could you reopen it?

**Comment by cdeutsch** [comment]
Agreed. Without it, it's a usability issue; and I now avoid looking at images in VS Code

**Comment by gibson-kim** [comment]
Is there a way to disable this feature?
