### ISSUE TITLE
debug not disconnect

### ISSUE THREAD

**Issue by ruiblaese** [Microsoft/vscode#59061]
Issue Type: <b>Bug</b>

I debug in nodejs and execute process.exit(0)... debug is running forever

VS Code version: Code - Insiders 1.28.0-insider (af3614909b837c46a260666cb7baab7a8468a9c8, 2018-09-20T14:09:20.109Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (7.75GB free)|
|Process Argv|C:\Users\rui\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.6.0
vscode-icons|rob|7.26.0
markdown-preview-enhanced|shd|0.3.5

</details>

**Comment by ruiblaese** [comment]
code exemple

`const a = require('./a');
const a = require('./../../../a');
const a = require('./../../../a');
const a = require('./../../../a');

require('events').EventEmitter.defaultMaxListeners = 0;

async function mainTeste() {

    .
    .
    .

    logger.info("finalizando execucao!");
    process.exit(0);
}
mainTeste();`

**Comment by ruiblaese** [comment]
![image](https://user-images.githubusercontent.com/12955543/45839938-0b23cf00-bcec-11e8-887c-cd7f8141119a.png)

**Comment by ruiblaese** [comment]
I never sent any errors to any project, if you are doing something wrong please tell me.

the problem started today
before using command "process.exit (0)" the debug would automatically shut down.

**Comment by weinand** [comment]
@isidorn I can reproduce this in today's Insiders on Windows.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/59037

**Comment by isidorn** [comment]
@ruiblaese Thanks for using insiders and for filling timely issues like this, it is very valuable to us
