### ISSUE TITLE
Some key bindings conflict with those of the window manager

### ISSUE THREAD

**Issue by 10098** [Microsoft/vscode#5906]
- VSCode Version: 1.0.0
- OS Version: Ubuntu 14.04 LTS, Cinnamon desktop environment

Steps to Reproduce:

1.  Open more than one files on the side (so that the editor ends up with multiple columns)
2.  Try using Ctrl+Alt+Shift+<Left/Right> to switch between editors

Expected behavior:
Editors are switched

Observed behavior:
Cinnamon intercepts the shortcut and switches workspaces instead

Is it possible to configure the editor's key bindings manually?

**Comment by bpasero** [comment]
I do not think we can overwrite any of the OS taken keys. @alexandrudima ?

**Comment by alexandrudima** [comment]
Each desktop environment "eats" different keybindings, it is almost impossible for us to have defaults that work in all Linux desktop environments.

@10098 I recommend customizing the keybindings via `File > Preferences > Keyboard Shortcuts`
