### ISSUE TITLE
The titlebar should center window title 

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#59067]
Issue Type: <b>Bug</b>

In these cases it's clearly not centered: 

![image](https://user-images.githubusercontent.com/4033249/45847121-cd6c7980-bcde-11e8-9c32-2774dcfb056c.png)

![image](https://user-images.githubusercontent.com/4033249/45847132-d9f0d200-bcde-11e8-8134-f9da738f6f13.png)

VS Code version: Code - Insiders 1.28.0-insider (af3614909b837c46a260666cb7baab7a8468a9c8, 2018-09-20T14:01:25.124Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (4.06GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-emoji|bie|0.0.7
markdown-preview-github-styles|bie|0.1.3
vscode-eslint|dba|1.6.0
tslint|eg2|1.0.39
vsc-material-theme|Equ|2.4.2
beautify|Hoo|1.4.3
theme-monokai-pro-vscode|mon|1.1.8
vscode-language-pack-ja|MS-|1.28.0
python|ms-|2018.8.0
debugger-for-chrome|msj|4.10.1
vetur|oct|0.12.6
webview-lsp-inspector|oct|0.0.1
polacode|pnp|0.2.2
vscode-csstree|sme|0.7.0
language-stylus|sys|1.10.0
vim|vsc|0.16.4

(1 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
was fixed earlier. re-open if you see with newer builds

**Comment by ralshammrei2** [comment]
في الجمعة، ٢١ سبتمبر، ٢٠١٨ ١٢:١١ ص Pine <notifications@github.com> كتب:
