### ISSUE TITLE
workbench.action.terminal.deleteWordLeft Doesn't Work, Outputs ^W

### ISSUE THREAD

**Issue by CoryOwens** [Microsoft/vscode#59071]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Open the VS Code terminal (`` Ctrl+` ``, by default).
2. Type a command or a word into the terminal. (Ex: `foo`)
3. Press `Ctrl+Backspace`.  (By default, `Ctrl+Backspace` is bound to `workbench.action.terminal.deleteWordLeft` when `terminalFocus`.)

Expected result: The word to the left of the cursor is deleted. 

Actual result: The character `^W` appears in the terminal input line. 

This happens even if you change the shortcut. For instance, if you bind `Alt+Backspace` to `workbench.action.terminal.deleteWordLeft`, it will it too input `^W`.

An older case (#19697) described the same (or at least similar) issue, but was closed as duplicated (#11314), even though the other case was specific to Mac. 

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (7.95GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.8.0
cpptools|ms-|0.18.1
PowerShell|ms-|1.8.4
code-settings-sync|Sha|3.1.2

</details>

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
