### ISSUE TITLE
cls command doesn't work if ctrl+HOME

### ISSUE THREAD

**Issue by coolit** [Microsoft/vscode#59073]
- VSCode Version:
latest
- OS Version:
win10 amd64
Steps to Reproduce:

1. In the terminal, run 'cls'
2. run some other command
3. press ctrl+HOME
4. all the old info before running cls, comes back again

**Comment by Tyriar** [comment]
See https://github.com/xtermjs/xterm.js/issues/106 for some history

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
