### ISSUE TITLE
Freeze after long uptime

### ISSUE THREAD

**Issue by 10098** [Microsoft/vscode#5907]
- VSCode Version: 1.0.0
- OS Version: Ubuntu 14.04 LTS

Steps to Reproduce:

1. Open a bunch of files in the editor
2. Leave it running for a long period of time (over 8 hours)
3. Editor becomes unresponsive and needs to be restarted

I think it's actually a fairly common scenario to leave the editor running in the background and leave the office for more than 8 hours :)

**Comment by bpasero** [comment]
@10098 does it reproduce with our insiders build? 
You can give it a try from our insiders release today: http://code.visualstudio.com/Download#insiders

**Comment by 10098** [comment]
I haven't tried that build. I'll download it today and let you know tomorrow how it goes.

**Comment by bpasero** [comment]
@10098 thanks!

**Comment by 10098** [comment]
Looks like the same issue happens with the insider build. I downloaded and used it for a day, and left it running before leaving the office. This morning it is no longer responding.

**Comment by 10098** [comment]
This may or may not be related to this issue - while most of the time the editor feels very responsive, I've  noticed that sometimes it becomes sluggish and responds to keystrokes with about a half-second delay. It doesn't happen often (once every few days maybe). Sometimes the slowness goes away by itself, and other times I have to restart it.

**Comment by bpasero** [comment]
this is #508 then
