### ISSUE TITLE
editor.action.selectHighlights automatically

### ISSUE THREAD

**Issue by SavePointSam** [microsoft/vscode#59072]
I really like being able to see all the occurrences of something I highlight easily. Atom has this capability and I don't see any reference to this being a default feature in Code.

I would like to highlight a string and highlight occurrences of that string, automatically, in the same file, but also all other files that are open. This commonly comes up when I'm verifying prop-drilling in react applications. Props are often named the same across different components and it would be great to see the logical flow at a glance and all the references to these across files.

**Comment by SavePointSam** [comment]
I see. Selection highlighting didn't appear to be working in same file for me the other day, but it is working correctly for me now. Across open files is what I would like to see now.

Thank you!

**Comment by designbyadrian** [comment]
Selection highlighting in every open editor is a must-needed feature
