### ISSUE TITLE
You must use command netsh winsock reset to open.

### ISSUE THREAD

**Issue by q592840919** [Microsoft/vscode#59075]
Issue Type: <b>Bug</b>

You can't open it all the time. The lookup method is to use the Netsh Winsock reset command to open it, but you have to use this command every time you start it

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.96GB (5.19GB free)|
|Process Argv|D:\devTool\vscode\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.26.3

</details>

**Comment by Tyriar** [comment]
@q592840919 are you saying you need to run netsh in order to open VS Code?
