### ISSUE TITLE
Keyboard Shortcuts: more "when" clause contexts are required related to Focus.

### ISSUE THREAD

**Issue by dsanz006** [Microsoft/vscode#59084]
So I am customizing my VS Code shortcuts and I like them to behave differently depending on where my cursor is focusing. For instance, if I am focusing on the editor, the shortcut "Ctrl+Alt+D" does one thing, because in the definition of this shortcut I added `"when": "editorFocus"`. If I do "Ctrl+Alt+D" inside the terminal context, then the command does another thing, because I have `"when": "terminalFocus"`.

The problem is that I can't perform similar actions when my cursor is in other contexts, for example the side bar, the debug window... I am missing `"when"` clause conexts such as `"sideBarFocus"`, `"searchFocus"`, `"debugFocus"`, `"problemsFocus"`... Or, alternatively, you could add another keyword, similar to `"activeViewlet"` or `"activePanel"` called `"focusViewlet"` or `"focusPanel"` so that we can compare it with `'workbench.view.search'` `'workbench.view.debug'`, `'workbench.panel.match'` ...

**Comment by dsanz006** [comment]
Actually, it should be enough with `"sideBarFocus"` and `"panelFocus"`. Then focus on more specific contexts could be guessed:

- `"searchFocus"` would be `"sideBarFocus && activeViewlet == 'workbench.view.search'"`
- `"debugFocus"` would be `"sideBarFocus && activeViewlet == 'workbench.view.debug'"`
- `"problemsFocus"` would be `"panelFocus && activeViewlet == 'workbench.panel.match'"`

**Comment by octref** [comment]
Yep we have it now. Glad you are happy :p
