### ISSUE TITLE
problems tab always showing "no problems have been detected in the workplace so far"

### ISSUE THREAD

**Issue by inessaid** [Microsoft/vscode#59080]
Issue Type: <b>Bug</b>

problems tab always showing "no problems have been detected in the workplace so far" even when I purposely type errors, it does not show them anymore.
It was working a few hours ago but I'm not sure what changed.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.85GB (9.94GB free)|
|Process Argv|C:\Users\ines\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
cpptools|ms-|0.18.1

</details>

**Comment by sandy081** [comment]
@inessaid When you mean you are purposely typing errors? Do you see them in the editor?
