### ISSUE TITLE
Keyboard shortcuts: "when": "activePanel == 'workbench.panel.match'" doesn't seem to work

### ISSUE THREAD

**Issue by dsanz006** [Microsoft/vscode#59083]
So I have a couple of customized keyboard shortcuts, they look like this:

`{`
`    "key": "meta+t d",`
`    "command": "workbench.action.closePanel",`
`    "when": "activePanel == 'workbench.panel.terminal'" //when terminal is visible`
`},`

`{`
`    "key": "meta+r d",`
`    "command": "workbench.action.closePanel",`
`    "when": "activePanel == 'workbench.panel.match'" //when problems view is visible`
`},`

The first command works correctly: when the terminal is visible, I press "meta+t d" and it hides. But for some reason the second one doesn't work: when the problems view is visible, I press "meta+r d" and nothing happens. The problem seems to be the "when" condition. Is 'workbench.panel.match`deprecated?

- VSCode Version: 1.27.2
- OS Version: Ubuntu 16.04.5 LTS

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Docs: https://code.visualstudio.com/docs/getstarted/keybindings#_active-view-or-panel-when-clause-context

**Comment by sandy081** [comment]
@dsanz006 I do not think there is any panel with id `workbench.panel.match`. Id of Problems panel is `workbench.panel.markers`. It works when I use correct id.

**Comment by dsanz006** [comment]
Thank you @sandy081, I will try it with id `workbench.panel.markers`. However, the documentation that @Tyriar references should be fixed, because there it says `workbench.panel.match`.

**Comment by sandy081** [comment]
Thanks @dsanz006 for pointing it out. Fixed the docs.
