### ISSUE TITLE
Could you make IntelliSense working independently from the order of the "multi cursoring"?

### ISSUE THREAD

**Issue by ndsvw** [Microsoft/vscode#59086]
IntelliSense works fine for me (mostly):
<img width="622" alt="bildschirmfoto 2018-09-21 um 09 14 37" src="https://user-images.githubusercontent.com/21332313/45866154-28a27880-bd80-11e8-9882-0ab2be463e49.png">

And when I write a string, it does not suggest me anything (as expected):
<img width="610" alt="bildschirmfoto 2018-09-21 um 09 14 50" src="https://user-images.githubusercontent.com/21332313/45866213-5ab3da80-bd80-11e8-83b6-caf4b227f26a.png">

But there is something that could be improved IMO. It affects the multi cursor feature.
If I write a code like this, there are 2 ways to use the multi-cursor-feature.
<img width="372" alt="bildschirmfoto 2018-09-21 um 09 33 35" src="https://user-images.githubusercontent.com/21332313/45866533-74095680-bd81-11e8-8cbe-c25560bd6b02.png">

1. I click between the brackets in line 4 and use the multi-cursor-feature **after that** between the quotes in line 3. => IntelliSense works:
<img width="678" alt="bildschirmfoto 2018-09-21 um 09 34 34" src="https://user-images.githubusercontent.com/21332313/45866580-9dc27d80-bd81-11e8-8125-1697bfa02de2.png">

2. But when I do it the other way (clicking between the quotes in line 3 **first** and use the multi-cursor-feature between the brackets in line 4 then), it does not suggest me anything:
<img width="352" alt="bildschirmfoto 2018-09-21 um 09 37 03" src="https://user-images.githubusercontent.com/21332313/45866707-eda14480-bd81-11e8-8881-f3e04887e621.png">

Wouldn't it be better if IntelliSense would suggests me sth. independent from the order of multi-cursoring the code?

---

Let me explain why this is also useful.
VSCode allows snippets (like [this](https://github.com/nathanchapman/vscode-javascript-snippets)).
A useful one of them is *console.log labeled (shortcut is cll)* in my oppinion.
The template looks like this:

`console.log('${0}', ${0});`

So I write *cll* in a new line and press Enter. Then the code in this line changes to `console.log('', );` and there are two cursors in this line.
The problem: VSCode seems to create the cursor for the string first. That meens that there won't be any IntelliSense altough it would be very helpful.
<img width="292" alt="bildschirmfoto 2018-09-21 um 09 53 29" src="https://user-images.githubusercontent.com/21332313/45867661-38bc5700-bd84-11e8-9853-4942708daa0a.png">

---

My question/suggestion: Could you make IntelliSense working independently from the order of the "multi cursoring" or (if that's not wanted/possible) could you make VSCode cursoring the Not-Strings of templates first?

_English is not my mother language. So I'm sorry if it's hard to understand me._

**Comment by ramya-rao-a** [comment]
@ndsvw The intellisense feature is driven by the text preceding the cursor. In multi-cursor mode, each cursor can have different text before it. So, we choose to use the text before the first cursor and provide intellisense there.

If we provided Intellisense for all cursors, that can be confusing in the final result.
If we calculate intellisense for all cursors, and use the first one that has some results, then this wouldnt be a consistent experience. Therefore, we wont be changing this behavior.

About the snippet `console.log('${0}', ${0});`, I think it is not a right one.
The first parameter is supposed to be a string with substitutions, the second is the substitution value. I cant think of any case where they are the same.
