### ISSUE TITLE
Intellisense popup flickers on and off

### ISSUE THREAD

**Issue by smidyo** [microsoft/vscode#59096]
Issue Type: <b>Bug</b>

Sometimes when I go to hover to see the Intellisense popup, it quickly flashes on and off.

Goes away after a while. Seems to be mainly on large red squigglies

https://youtu.be/1OKy1XTs8a8

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:14:32.385Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_118813|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vscode-css-formatter|aes|1.0.1
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.6.0
tslint|eg2|1.0.39
vs-code-xml-format|fab|0.1.5
firebase-snippets|has|0.0.1
beautify|Hoo|1.4.3
useful-react-snippets|igo|1.4.4
Angular2|joh|6.1.5
generate-react-component|jos|0.2.1
vscode-github|Kni|0.30.0
python|ms-|2018.8.0
csharp|ms-|1.16.1
material-icon-theme|PKi|3.6.0
nbsp-vscode|pos|0.0.1
vscode-graphql|Pri|0.1.5
LiveServer|rit|5.1.1
bootstrap4-vscode|the|4.3.0
ReactSnippets|xab|2.2.0

</details>

**Comment by octref** [comment]
I have never seen this. If you can still reproduce this in latest, **with all extensions disabled**, feel free to open a new issue.
