### ISSUE TITLE
Switching tab takes long time, 

### ISSUE THREAD

**Issue by amerrnath-murugan-E0711** [Microsoft/vscode#59094]
Issue Type: <b>Bug</b>

1. Switching to different file tabs takes average of 2 sec to open the file.
2. Typing becomes so slow, due to some info box shows  unwanted hierachy of class. 

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:03:31.083Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.41GB free)|
|Process Argv|/private/var/folders/w3/8q4z6d417n5g8md88xygy98shd2wlw/T/AppTranslocation/FC4312A4-E731-40A1-9207-BD34C717C79D/d/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by amerrnath-murugan-E0711** [comment]
<img width="750" alt="screen shot 2018-09-24 at 2 58 55 pm" src="https://user-images.githubusercontent.com/35023832/45945221-6ca8ae00-c00a-11e8-88be-157db927779a.png">

@bpasero  This the hint box slows the typing and movement cursor response.

**Comment by bpasero** [comment]
@amerrnath-murugan-E0711 

> Switching to different file tabs takes average of 2 sec to open the file.

Are these files local on disk? Can you try to run "code --disable-extensions" to see if it still happens?

**Comment by amerrnath-murugan-E0711** [comment]
yes I have disabled all extension and still seeing this result

**Comment by bpasero** [comment]
Are these files local on disk?

**Comment by amerrnath-murugan-E0711** [comment]
yes

**Comment by bpasero** [comment]
@amerrnath-murugan-E0711 is it also slow after you once switched and then switch again between the same tab?

**Comment by amerrnath-murugan-E0711** [comment]
Yes, it's been the same result when disabling all extensions, switching to different files takes average of 2 or 3 sec

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!
