### ISSUE TITLE
How to read languages/colorizer settings?

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#591]
_From @alefragnani on October 24, 2015 0:31_

How could I get  some language/colorizer settings?

I'm creating an extension to add personalized comments, and would like to get the _line comment_ language/colorizer setting (`//`, `#`, etc) from the current language.

I did take a look at [vscode-comment](https://github.com/Microsoft/vscode-comment) demo and `export interface ILanguage`, but didn't find how to _read_ the setting.

Thanks in advance

_Copied from original issue: Microsoft/vscode-extensionbuilders#57_

**Comment by seanmcbreen** [comment]
@egamma do you know how to do this?

**Comment by egamma** [comment]
This is not exposed in the API currently.
