### ISSUE TITLE
Watch expressions export and filter

### ISSUE THREAD

**Issue by waldirio** [microsoft/vscode#59109]
I found the question but without answer.
https://stackoverflow.com/questions/51838064/vscode-export-or-copy-a-debug-watch-expression-to-another-program

Good morning, so the big point here is, should be awesome export the content from watch list to a file, could be a simple JSON. My scenario is, I'm writing a python app and consuming the API, that said, I'm looking for some specific name variable.

Currently, I've to expand the structure and check one by one to view the content, exporting to a json file will be amazing, a simple grep will resolve the question.

Another interesting feature *maybe will override this one*, could add the search field on the watch list. On this case, the filter will be on the fly and directly on the vscode. AMAZING.

Thank you.
Waldirio

**Comment by isidorn** [comment]
Both are valid feature requests but they are not yet on the plan.

**Comment by isidorn** [comment]
Filter you can do, focus on the watch expression view and start typing. Hover over the widget and click the filter button.
Second request is out of scope
