### ISSUE TITLE
Tasks with scope = the last folder in workspaceFolders array do not show up

### ISSUE THREAD

**Issue by g-arjones** [Microsoft/vscode#59102]
- VSCode Version: 1.27.2
- OS Version: Ubuntu 16.04 (also tested on macOS High Sierra)

Steps to Reproduce:

1. [Clone this test repository](https://github.com/g-arjones/vscode-task-provider-bug)
2. Run the extension
3. Start with a fresh workspace
4. Add at least two folders to the workspace
5. Hit "Run Task" from the command palette (BUG: "Dummy Task" does not show up)
6. Hit "Reload Window"  from command palette
7. Hit "Run Task" from the command palette (BUG: "Dummy Task" now shows up?)
8. Add another folder and tasks will stop showing again... :(

Does this issue occur when all extensions are disabled?: Yes

This feels really bad since every time a user adds a folder he/she must restart VS Code in order to be able to use tasks provided by the extension

**Comment by dbaeumer** [comment]
This works for me using a workspace with two empty workspace folders. Is there anything more to it:

<img width="851" alt="capture" src="https://user-images.githubusercontent.com/1931590/45945420-c5b61900-bfed-11e8-836f-a8829142607b.png">

**Comment by dbaeumer** [comment]
Works under Linux / Ubuntu as well for me. Same output as under Windows.

**Comment by g-arjones** [comment]
Did you follow the steps from the issue description? If you start the workspace with two folders on it, the task will show.. If you start with an empty workspace and then add the folders, it won't...

**Comment by dbaeumer** [comment]
Now I can't :-)

**Comment by dbaeumer** [comment]
Can you clarify your step 3. I am not able to reproduce this anymore.

**Comment by g-arjones** [comment]
I can consistently reproduce if I start with an empty, add one, check the "run task menu" add another one and check the "run task menu" again. If I reload the window then the task will show, if I add empty3, it won't again.

Are you on Linux?

**Comment by dbaeumer** [comment]
I am testing this right now under Linux.

**Comment by g-arjones** [comment]
> Can you clarify your step 3. I am not able to reproduce this anymore.

That is a workspace after I have closed a previously open workspace

**Comment by g-arjones** [comment]
Could you try with a non empty folder (i.e an actual project). Not sure if this makes any sense but we are just guessing at this point...

**Comment by dbaeumer** [comment]
Actually the thing that makes i fail is if you add a folder that has no `tasks.json` file. If it has it will work as expected. The reason is that I rely on a configuration change only but need to recompute some of the stuctures on workspace folder change as well.

**Comment by g-arjones** [comment]
So your empty1 and empty2 actually had tasks.json in them?

**Comment by dbaeumer** [comment]
Yes, after I tried to reproduce your other bug :-)

**Comment by g-arjones** [comment]
Got it. So, it is indeed a bug, right?

**Comment by dbaeumer** [comment]
Yes, it is a bug. Thanks for reporting it.

**Comment by g-arjones** [comment]
No problem.. Thanks!

![vscode-task-provider-bug](https://user-images.githubusercontent.com/17409636/45950874-d22f7700-bfd7-11e8-8bf6-b5a9d1d785d7.gif)
