### ISSUE TITLE
Missing directory separators in file open window

### ISSUE THREAD

**Issue by skilleter** [Microsoft/vscode#59104]
Issue Type: <b>Bug</b>

Select 'Open File' on the 'File' menu
The 'Open File' window appears
The path shown in the window at the top of the directory listing does not contain separators so that, '/home/username/documents' is shown as 'homeusernamedocuments'.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:11:15.873Z)
OS version: Linux x64 4.15.0-34-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6440HQ CPU @ 2.60GHz (4 x 2592)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|0, 0, 0|
|Memory (System)|10.25GB (1.30GB free)|
|Process Argv|/snap/vscode/59/usr/share/code/code|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.0
vscode-django|bat|0.17.0
django-html|bib|1.2.0
django-snippets|bib|1.1.0
vscode-puppet|bit|0.4.5
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.20.0
vscode-instant-markdown|dba|1.4.2
githistory|don|0.4.2
jupyter|don|1.1.4
python-extension-pack|don|1.4.0
file-icons|fil|1.0.16
auto-close-tag|for|0.5.6
code-runner|for|0.9.4
terminal|for|0.0.10
vscode-auto-open-markdown-preview|hnw|0.0.4
beautify|Hoo|1.4.4
path-autocomplete|ion|1.12.0
puppet-vscode|jpo|0.11.1
MagicPython|mag|1.0.12
terraform|mau|1.3.4
terraform-snippets|min|2.1.0
vscode-todo-parser|min|1.9.1
HTMLHint|mka|0.5.0
python|ms-|2018.8.0
cpptools|ms-|0.18.1
Go|ms-|0.6.89
vs-keybindings|ms-|0.2.0
vsliveshare|ms-|0.3.709
vscode-docker|Pet|0.2.0
subtle-brackets|raf|3.0.0
ruby|reb|0.20.0
vscode-yaml|red|0.0.16
markdown-preview-enhanced|shd|0.3.5
code-spell-checker|str|1.6.10
sort-lines|Tyr|1.7.0
vscodeintellicode|Vis|1.0.4
gitblame|wad|2.4.4
vscode-todo-highlight|way|1.0.4
jinja|who|0.0.8
markdown-pdf|yza|1.2.0
markdown-all-in-one|yzh|1.6.0

</details>

**Comment by bpasero** [comment]
@skilleter how do dialogs from other applications look like? We do not have much control over the dialogs.

**Comment by skilleter** [comment]
I'd not previously seen this issue in any other applications. However, I've just installed Atom and it has the same problem.

**Comment by bpasero** [comment]
Closing this issue given that we plan to release VSCode stable early February with Electron 3.x. If you want to benefit from the fix already, consider to use our insiders version that already contains the fix: https://code.visualstudio.com/insiders/
