### ISSUE TITLE
Cant run a python file in terminal

### ISSUE THREAD

**Issue by MinhTri18** [Microsoft/vscode#59101]
Issue Type: <b>Bug</b>

Usually when I right click there is  a button 'Run Python file in Terminal' but now it wouldn't appear. The  only things it shows is 'Change Occurance',  Copy, Paste, Cut, and Command Pallete

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.87GB (0.69GB free)|
|Process Argv|C:\Users\acer\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vsliveshare|ms-|0.3.709

</details>

**Comment by Tyriar** [comment]
You must have uninstalled an extension that was doing this for you.
