### ISSUE TITLE
Current menu item isn't highlighted

### ISSUE THREAD

**Issue by skilleter** [Microsoft/vscode#59103]
Issue Type: <b>Bug</b>

Click on entry on menu bar (e.g. 'File')
Move mouse pointer over enties in menu
I'd expect the entry until the mouse to be highlighted, but it does change.
I can interact with the menus as normal (e.g. click on 'New File' to create a new file) - it is just that the current menu item is not highlighted.

Similarly, I can navigate the menus using the keyboard - e.g. press ALT+F for the file menu, cursor down 3 times and ENTER to create a new file, but the current entry in the menu is not highlighted when moving up and down the menu.

Changing the theme or the menu foreground/background/selection colours has no effect on this behaviour.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:11:15.873Z)
OS version: Linux x64 4.15.0-34-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6440HQ CPU @ 2.60GHz (4 x 2592)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|1, 1, 1|
|Memory (System)|10.25GB (0.93GB free)|
|Process Argv|/snap/vscode/59/usr/share/code/code|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.0
vscode-django|bat|0.17.0
django-html|bib|1.2.0
django-snippets|bib|1.1.0
vscode-puppet|bit|0.4.5
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.20.0
vscode-instant-markdown|dba|1.4.2
githistory|don|0.4.2
jupyter|don|1.1.4
python-extension-pack|don|1.4.0
file-icons|fil|1.0.16
auto-close-tag|for|0.5.6
code-runner|for|0.9.4
terminal|for|0.0.10
vscode-auto-open-markdown-preview|hnw|0.0.4
beautify|Hoo|1.4.4
path-autocomplete|ion|1.12.0
puppet-vscode|jpo|0.11.1
MagicPython|mag|1.0.12
terraform|mau|1.3.4
terraform-snippets|min|2.1.0
vscode-todo-parser|min|1.9.1
HTMLHint|mka|0.5.0
python|ms-|2018.8.0
cpptools|ms-|0.18.1
Go|ms-|0.6.89
vs-keybindings|ms-|0.2.0
vsliveshare|ms-|0.3.709
vscode-docker|Pet|0.2.0
subtle-brackets|raf|3.0.0
ruby|reb|0.20.0
vscode-yaml|red|0.0.16
markdown-preview-enhanced|shd|0.3.5
code-spell-checker|str|1.6.10
sort-lines|Tyr|1.7.0
vscodeintellicode|Vis|1.0.4
gitblame|wad|2.4.4
vscode-todo-highlight|way|1.0.4
jinja|who|0.0.8
markdown-pdf|yza|1.2.0
markdown-all-in-one|yzh|1.6.0

</details>

**Comment by skilleter** [comment]
![vscode-no-menu-highlighting](https://user-images.githubusercontent.com/5267905/45945718-4bce6180-bfe6-11e8-9181-67b1a9020122.png)

I would expect the menu item under the mouse to be highlighted.

**Comment by bpasero** [comment]
@skilleter it is possible that this is just the way the menu works for your Linux distribution. To get our new menu style which is custom and supports this, you can configure: `"window.titleBarStyle": "custom"` in settings.

**Comment by skilleter** [comment]
I've not seen the issue on other applications, but setting the custom menu style does fix the problem, at the expensive of having the menu in the title bar, which I'm not keen on, but will live with.

Thanks

John

**Comment by bpasero** [comment]
Closing this issue given that we plan to release VSCode stable early February with Electron 3.x. If you want to benefit from the fix already, consider to use our insiders version that already contains the fix: https://code.visualstudio.com/insiders/
