### ISSUE TITLE
IntelliSense popup object inspector should display type signature information at the very top

### ISSUE THREAD

**Issue by ziomio** [Microsoft/vscode#59105]
If I hover over the `polygon` object name in the last line of this source code:
```
let polygon = {
  y: "hello",
  z: "goodbye"
};
polygon.y += 5;
```
IntelliSense will display this popup:
![screenshot](https://user-images.githubusercontent.com/2357073/45885562-6f639300-bdbf-11e8-9ae6-d86002f1f868.png)

It displays `[x: string]: any;` **inside** curly braces, but inside curly braces (in my opinion) must be only object properties. If I look quickly over that popup I can assume that object `polygon` has x,y,z properties, when in fact `x` property is absent. Therefore I propose to display that `[x: string]: any;` information at the most top line of that popup window.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#27316
