### ISSUE TITLE
isWrapped exception in terminal

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#59114]
https://github.com/xtermjs/xterm.js/issues/1702

**Comment by IlyaBiryukov** [comment]
@Tyriar 

I'm hitting an error about isWrapped property in 1.28.0, is this the same issue you just fixed?

In Chrome debug console:
```
TypeError: Cannot read property 'isWrapped' of undefined
    at Buffer.getWrappedRangeForLine (c:\Program Files\Microsoft VS Code Insiders\resources\app\node_modules.asar\vscode-xterm\lib\Buffer.js:205)
    at BufferStringIterator.next (c:\Program Files\Microsoft VS Code Insiders\resources\app\node_modules.asar\vscode-xterm\lib\Buffer.js:305)
    at Linkifier._linkifyRows (c:\Program Files\Microsoft VS Code Insiders\resources\app\node_modules.asar\vscode-xterm\lib\Linkifier.js:63)
    at c:\Program Files\Microsoft VS Code Insiders\resources\app\node_modules.asar\vscode-xterm\lib\Linkifier.js:53
```

**Comment by Tyriar** [comment]
@IlyaBiryukov yep, let me know if you see it again in Monday's build

**Comment by chrmarti** [comment]
Seeing this in todays build.

VS Code version: Code - Insiders 1.28.0-insider (5ba5f14c954682df46f04a541f0b272166605366, 2018-09-26T07:25:01.336Z)
OS version: Darwin x64 17.7.0

**Comment by Tyriar** [comment]
I guess my fix only covered one of the cases.

The latest xterm.js should fix this due to the additional bound checking in https://github.com/xtermjs/xterm.js/pull/1693, but since this is an error I expect to have minimal impact on the actual experience and there were some issues when upgrading xterm.js last, I'd say we hold off on this until 1.29.

**Comment by Tyriar** [comment]
Fixed in https://github.com/Microsoft/vscode/commit/aaee349207f2e5eb1d0b215391bc0a11a6d80437

**Comment by chrmarti** [comment]
@Tyriar This happens quite often (testing on Linux) and will make it difficult to spot other errors. I'd suggest to still fix this for the September milestone.

**Comment by StephenWeatherford** [comment]
This is extremely annoying since it keeps bringing up the chrome debugging window and when it happens it makes the terminal extremely slow.

**Comment by Tyriar** [comment]
This is not showing up in our error telemetry, I don't have a repro and pulling in the fix in isolation is non-trivial so I'm removing candidate.
