### ISSUE TITLE
phpcs plugin with wsl on windows 10

### ISSUE THREAD

**Issue by ctjdpascua** [Microsoft/vscode#59111]
Hi I tried to connect the phpcs plugin with WSL in Win10, I used the next code in .bat file:

@echo OFF
setlocal ENABLEDELAYEDEXPANSION

rem Collect the arguments and replace:
rem  '\' with '/'
rem  'c:' with 'mnt/c'
rem  '"' with '\"'
set v_params=%*
set v_params=%v_params:\=/%
set v_params=%v_params:C:=/mnt/c%
set v_params=%v_params%
set v_params=%v_params:"=\"%

rem Call the windows-php inside WSL.
rem windows-php is just a script which passes the arguments onto
rem the original php executable and converts its output from UNIX
rem syntax to Windows syntax.
C:\Windows\System32\wsl.exe ~/.config/composer/vendor/bin/phpcs %v_params%

but when I enabled the extension, Visual Studio launch this error

phpcs: The file ""--report=json"" does not exist

someone has been able to solve this??

Thanks.

**Comment by bpasero** [comment]
This is not the right place to file issues for WSL.exe
