### ISSUE TITLE
Allow some way to differentiate between multiple folder directories of the same name in a workspace

### ISSUE THREAD

**Issue by tommai78101** [Microsoft/vscode#59119]
Note that this feature request is not for this issue, https://github.com/Microsoft/vscode/issues/43188.

Right now, I have a workspace set up with folder directories required for me to work with across multiple hard drives.

This is what it looks like right now:

![image](https://user-images.githubusercontent.com/6444116/45892956-b2aa0b80-bd97-11e8-9529-718929ba7c60.png)

I would like for a way to differentiate between the folder names, kind of like how we handle this with multiple tabs of the same document file names, like so:

![image](https://user-images.githubusercontent.com/6444116/45893215-7dea8400-bd98-11e8-8599-b05434a00800.png)

(The difference is, one is located in the `Client\` directory, and the other one is located in `Client\EdgePackaging`. But there would be another issue reported in regards to the backslash not showing correctly in the tab.)

(On second thought, I don't know if that is the intended way of displaying the folder directory next to the tab document's name.)

I just wanted to keep this requested feature be consistent with the multiple tabs directory listing in the second picture.

Thanks.

**Comment by bpasero** [comment]
@tommai78101 each workspace folder in the workspace file can have a name that you can set to distinguish.

**Comment by tommai78101** [comment]
@bpasero But if it's part of the TFS, we can't rename them.

**Comment by tommai78101** [comment]
@bpasero I found it.  But it requires me to edit the file via external tools, like Notepad++ for instance. The Drag-n-Drop feature in VS Code would supersede the ability to open the file for editing. That will be for another issue.

https://code.visualstudio.com/docs/editor/multi-root-workspaces#_workspace-file-schema

Will look into this.
