### ISSUE TITLE
Command pallette should auto close when losing focus

### ISSUE THREAD

**Issue by CZDanol** [Microsoft/vscode#59118]
Issue Type: <b>Bug</b>

Command pallette should auto close when losing focus

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

**Comment by bpasero** [comment]
It does, unless you changed settings.

**Comment by CZDanol** [comment]
Oh I see, I had "workbench.quickOpen.closeOnFocusLost": false. I thought quickOpen are those tabs whose name is in cursive.
