### ISSUE TITLE
How to force a new line before every closing tag auto-generated?

### ISSUE THREAD

**Issue by mateus-so** [Microsoft/vscode#59115]
Hi, mates!
I'm having some problems trying to get these settings to work as I want. I need indentation so I can code quick, as I move a lot of blocks all the time.

HTML tags are closed automatically as I code, but for some reason, it doesn't matter if I force or request the editor to format my code nor if I hit save, it doesn't move the closing tags to a new line, although it preserves the indentation. So, instead of outputting, for.eg:

```
<tr>
 <td>
  <a>
   <img />
  </a>
 </td>
 <td>
  <a>
   <img />
  </a>
 </td>
</tr>
```
it outputs 
```
<tr>
 <td>
  <a>
   <img /></a></td>
 <td>
  <a>
   <img /></a></td>
</tr>
```
Is there anyway to force either VSC, Beautify or Emmet to generate the line break before every closing tags, either on save or on type?
Sorry, I searched a lot here and on StackOverflow, but couldn't find any solution.

**Comment by mateus-so** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [use language server for onEnterRules (#57968)](https://www.github.com/Microsoft/vscode/issues/57968)

Not quite the same question, as I don't need the automation to be done as I write within tags, neither do I need it to be as I type. My priority is to hit save and be able to get my code formatted as I mentioned, with every tag alone on their own line, and its content between.

**Comment by aeschli** [comment]
There is format on save (use `"editor.formatOnSave": false`) but in this example, the formatter decides not to put the tags on new lines.
We use https://github.com/beautify-web/js-beautify as the formatter. Would you mind filing an issue there? I guess the question is, why are no new lines added in this example
```
<tr>
	<td><a href=""><img src="" alt=""></a></td>
</tr>
```

I suspect that this is because it would alter the rendered HTML.
