### ISSUE TITLE
tsconfig with paths and include causes vscode to drop intellisense on paths

### ISSUE THREAD

**Issue by ca0v** [Microsoft/vscode#59116]
- VSCode Version: 1.27.2
- OS Version: win10

Steps to Reproduce:
[this gist](https://gist.github.com/ca0v/11f7ba0ffa9e3aa3a96e513a9ca58b5f) show the steps to reproduce but it comes down to this tsconfig.json file:

```
{
	"compilerOptions": {
		"baseUrl": "./",
		"paths": {
			"@app/*": ["./app/*"]
		}
	},
	"xinclude": ["app/**/*.ts"]
}
```

If you remove the "x" in "xinclude" intellisense immediately breaks in vscode:

```
import { MyApp } from "@app/myapp";
```

**Comment by ca0v** [comment]
There is a workaround to this.  Keep your primary tsconfig.json file free if "files", "include" and "exclude" elements and introduce a derived tsconfig file:

```
{
	"extends": "./tsconfig",
	"compilerOptions": {
		"outFile": "./built/app.max.js"
	},
	"include": ["./app/**/*.ts"]
}
```

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#27318
