### ISSUE TITLE
remove selection next find match 

### ISSUE THREAD

**Issue by Vict0rSch** [Microsoft/vscode#59125]
Hitting `cmd + d` adds the next matching string to the current selection. 

What if I went too far, pressed `cmd + d` too many times and want to remove the last occurrence from that selection? 

As it is I need to drop the selection (`esc`) and be careful with the number of times I hit `d`.
Instead, it would be nice if `cmd + shift + d` (or something else) worked as a reversal for the last selection added.

**Comment by rebornix** [comment]
You can run `Cmd+U` to undo the last action.
