### ISSUE TITLE
bug: clicking x on open tab results in awkward scroll right of the tab bar

### ISSUE THREAD

**Issue by r3wt** [Microsoft/vscode#59122]
Issue Type: <b>Bug</b>

1. open a bunch of editors (so many that the width of the tab bar exceeds available space and needs a scrollbar).
2. scroll to middle of tab bar.
3. close a tab.
4. the tab bar scrolls awkwardly to the right.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (8.53GB free)|
|Process Argv|C:\Users\user\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
twigcs|cer|0.4.2
php-debug|fel|1.12.5
php-intellisense|fel|2.3.5
php-pack|fel|1.0.2

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
@r3wt that is expected behaviour, we always try to reveal the active tab in the visible viewport. Can you share a screencast?
