### ISSUE TITLE
Intellisense jsconfig.json imports *everything* as a relative import

### ISSUE THREAD

**Issue by ablakey** [microsoft/vscode#59126]
- VSCode Version: 1.27.2
- OS Version: Ubuntu 16.04

If I have a jsconfig with these settings, ANYTHING I import occurs relatively.  If I don't have the jsconfig, lots of wild stuff happens like trying to import from `../../../../.cache/typescript/redux/index`
```
{
    "compilerOptions": {
        "target": "es6"
    },
    "exclude": [
        "node_modules"
    ]
}
```

![peek 2018-09-21 14-20](https://user-images.githubusercontent.com/9021944/45899022-c65e6d80-bda9-11e8-9b28-4859aad6a43c.gif)

What might be related to this is that IntelliSense does not detect most modules installed. Though sometimes it appears it can find components, classes, etc. from a module that's already got at least 1 import elsehwere.

**Comment by ablakey** [comment]
In exploring this further. I tried making a new workspace with no jsconfig.json.  I get weird behaviour (or maybe I just don't understand how it works).

It won't find `createStore` unless I've exported something, like a class.

![peek 2018-09-21 14-38](https://user-images.githubusercontent.com/9021944/45899883-1fc79c00-bdac-11e8-8eb7-8983bd5b553f.gif)

**Comment by ablakey** [comment]
And just to be thorough, here's what happens in my not-so-clean project, regardless of the presence or absence of a `jsconfig.json`

![peek 2018-09-21 14-43](https://user-images.githubusercontent.com/9021944/45900135-e0e61600-bdac-11e8-8e89-9ec5d0f811c7.gif)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)? This includes a new TypeScript version that has a number of bug fixes

**Comment by ablakey** [comment]
Yes I just tried and the same effects occur.

This seems easy to reproduce. I would graciously appreciate if anyone reading this is interested in trying this themselves.  If nothing else, it would be great to get a sense of whether this is an issue in VSCode or there's something environmental causing this.

Thank you.

**Comment by mjbvz** [comment]
Sorry this issue fell off my radar. Can you please test this in the latest vscode. If you still see the problem, share a small example project that demonstrates this behavior so we can investigate

**Comment by ablakey** [comment]
Hey no problem!

For one reason or another this issue has gone away so we can close the ticket. 

Thanks.
