### ISSUE TITLE
macOS: don't see any text in terminal 

### ISSUE THREAD

**Issue by frunny** [Microsoft/vscode#59127]
Issue Type: <b>Bug</b>

on macOS, I don't see any text in the terminal window. However the scrollbars indicate that there must be some text in the window. I can copy it and past it somewhere else. I found out that the font was not set to monospace - so I did change that - but still no text available in the terminal window. I'm on High Sierra on a MacPro 

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:04:11.329Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU           E5520  @ 2.27GHz (16 x 2260)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (18.62GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
alexa-skills-kit-toolkit|ask|0.2.1

</details>

**Comment by Tyriar** [comment]
Some questions:

- Did this just start happening or has it always happened?
- What's in your settings.json?
- Does resizing the terminal panel fix the issue?
- Can you provide a screenshot?

**Comment by Tyriar** [comment]
@frunny hmm... More questions:

- Is that Alexa title there because you renamed the terminal inside VS Code or something in your launch script?
- Can you cmd+a, cmd+c to copy and paste the contents of the terminal and are they correct?
- Does this problem go away if you add this setting: `"terminal.integrated.rendererType": "dom"`

**Comment by frunny** [comment]
"terminal.integrated.rendererType": "dom" did the trick 👍 Thanks!

The Alexa title is coming from the Alexa Skills Kit Toolkit Extension that is installed. 
copy paste - yes the content is there - as I mentioned in my first post

**Comment by ltodorov** [comment]
Hi,
I have the same issue with the current stable version:
Version: 1.30.1 (user setup)
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Date: 2018-12-18T18:12:07.165Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17763

The terminal UI looks broken. "terminal.integrated.rendererType": "dom" doesn't fix the problem.
The only workaround that I found is to press the Enter key to display the working folder path.

**Comment by ltodorov** [comment]
![image](https://user-images.githubusercontent.com/1941826/50204567-f9df7280-036d-11e9-93a6-4c5e4a61a341.png)

**Comment by ltodorov** [comment]
I downgraded to version 1.29.1 that was working fine on my computer before the last Windows update. The terminal on first open is also broken so it should be something related to the Windows version. Hope this information can help for resolving that annoying issue.
