### ISSUE TITLE
Extension Debug Mode

### ISSUE THREAD

**Issue by jabacchetta** [Microsoft/vscode#59120]
Before filing a bug report for VS Code, it's best practice to first disable all extensions to ensure that an extension isn't causing the issue. The workflow for going through this process looks like the following:

1. Make a list of all of your disabled extensions.
2. Disable all extensions.
3. Verify bug.
4. Enable all extensions.
5. Go through list of your extensions that should be disabled and manually disable each one again.

Instead, it'd be nice to put enabled extensions into a temporarily disabled (debug) mode. The workflow would then look more like this:

1. Enable debug mode.
2. Verify bug.
3. Disable debug mode.

**Comment by RMacfarlane** [comment]
There's a `Reload Window with Extensions Disabled` command you can use to temporarily set all extensions to disabled. Reloading the window again will revert extensions to their previous state.

**Comment by jabacchetta** [comment]
Perfect!
