### ISSUE TITLE
When the Updater runs, app disappears

### ISSUE THREAD

**Issue by aarongustafson** [microsoft/vscode#59130]
Issue Type: <b>Bug</b>

Whenever Visual Studio Code or VS Code Insiders does it update, the app disappears from the taskbar & start menu on Windows. The shortcuts are broken and the system asks to remove them.

VS Code version: Code - Insiders 1.28.0-insider (2558a72d6902015b142ef45c57b664ce1f09e03f, 2018-09-21T05:19:52.215Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.74GB (21.17GB free)|
|Process Argv|C:\Users\aarongu\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-pull-request-github|Git|0.1.6

</details>

**Comment by aarongustafson** [comment]
@joaomoreno Do you mean is it a user vs. a global install? It is a new laptop and I just went with the default install (I don’t recall which that is).

**Comment by joaomoreno** [comment]
Help > About should tell you which installation type it is.

**Comment by joaomoreno** [comment]
Actually, I can't repro. If you reinstall VS Code, does it keep happening?

**Comment by aarongustafson** [comment]
It looks like it’s a user install. I’ll try wiping and re-installing.

**Comment by aarongustafson** [comment]
And now we wait for the next update…

**Comment by matheusgrieger** [comment]
Ok so I started having the same issue now for the first time with 1.35, which changed Code's icon. Is there a way to restore shortcuts and `code .` CLI functionality without reinstalling Code?
