### ISSUE TITLE
launch command limited to 1024 characters

### ISSUE THREAD

**Issue by boneskull** [microsoft/vscode#59135]
- VSCode Version: 1.28.0-insider
- OS Version: macOS 10.13.6

Steps to Reproduce:

*This is how I discovered the issue, but it's not specific to `runtimeVersion`.  I'm not sure if variable expansion is something that can happen, but if it could, outputting `env "PATH=/path/to/node/version:${PATH}"` would seemingly be a workaround.*

*Apologies if this is a dupe; I searched but nothing was jumping out at me.*

1. Set `PATH` to something approaching 1024 characters.  One way to do this, evidently, is to use zsh & antigen with a bunch of plugins.  :smile: [Example of large `PATH` here](https://gist.github.com/boneskull/b7f99a0c51a3254d28a882b17d6289c4); you could also just add a bunch of nonsense via something like
    ```json
    "env": {
      "FOO": "<insert 1024 random characters here>"
    }
    ```
1. Launch VS Code
1. Add a launch config containing `runtimeVersion`, such as:
    ```json
    {
      "type": "node",
      "request": "launch",
      "name": "node-red",
      "runtimeExecutable": "node",
      "runtimeVersion": "8.1.2",
      "program": "app.js",
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen"
    }
    ```
1. Start debugging.  Terminal will show something like this: ![image](https://user-images.githubusercontent.com/924465/45902355-0ec25f00-bd9b-11e8-95fb-5a95042911de.png)
 That's a limit of 1024 characters. You can ignore the `%`

1. Once timeout is hit, you should see this alert: 
![image](https://user-images.githubusercontent.com/924465/45902279-dd499380-bd9a-11e8-9e46-1a99c26f5508.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by boneskull** [comment]
A workaround is to specify `PATH` in the `env` instead of using `runtimeVersion`, e.g.:

```json
{
  "type": "node",
  "request": "launch",
  "name": "app",
  "runtimeExecutable": "node",
  "program": "app.js",
  "console": "integratedTerminal",
  "internalConsoleOptions": "neverOpen",
  "env": { 
    "PATH": "/path/to/.nvm/versions/node/v8.12.0/bin:$PATH"
  }
}
```

**Comment by roblourens** [comment]
There is some issue with using sendText with very long strings, #38137

But Daniel says that it's not necessary to pack the whole cwd and environment into that sendText, and that we can create a terminal with the appropriate environment using its API. Tasks does something like this already. @isidorn @weinand

**Comment by laripappa** [comment]
Hope it's resolved soon

**Comment by laripappa** [comment]
@weinand This issue seems resolved in my case with latest vscode 1.37.0 because environment values became unfolded. I'm not the limitation is still existing..

**Comment by laripappa** [comment]
@weinand fyi - Recent build, for example, version 1.45.1, has this issue again because every environmental values become folded, which turns out that vscode cannot attach with this error message

```
Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:18189)
```

**Comment by MattReimer** [comment]
I'm still having this problem with `zsh` for VSCode version Version: 1.48.1

The reason is that I have a particularly large `.env` file I'm passing in using `envFile` param in `launch.json`

I needed a workaround for my typescript module so I made a wrapper script that uses the [NPM dotenv module](https://www.npmjs.com/package/dotenv) to load the environment instead.

#### `dev_launch.ts`

```ts
import * as dotenv from 'dotenv'

if (process.argv.length < 3) throw new Error('You must specify the env file')

dotenv.config({ path: process.argv[2] })

require('./myModule')
```

#### `launch.json`

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      "name": "MyModuleRunner",
      "program": "${workspaceFolder}/dist/dev_launch.js",
      "request": "launch",
      "restart": true,
      "sourceMaps": true,
      "args": ["../../.env.development"],
      "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/nodemon",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "type": "pwa-node"
    }
  ]
}
```

This seems hack-y to me but it gets the job done.
