### ISSUE TITLE
Git: Expose blame information in API

### ISSUE THREAD

**Issue by TomasHubelbauer** [microsoft/vscode#59134]
I'd like to request new method be added to the Git extension API detailed in:

https://github.com/Microsoft/vscode/blob/master/extensions/git/src/api/git.d.ts

My use case for this are is that in my extension [MarkDown To-Do](https://marketplace.visualstudio.com/items?itemName=TomasHubelbauer.vscode-markdown-todo) I currently shell out to Git to get blame for a line in order to determine the age of a MarkDown checkbox (`- [ ] checkbox`) on that line.

This feature request is prompted by @joaomoreno after his comment in #48674.

**Comment by joaomoreno** [comment]
Let's split this into two separate feature request issues. Can you clean this one up and create another one?

Let's keep the blame one here.

**Comment by anirudhrb** [comment]
The blame API is already available:
https://github.com/microsoft/vscode/blob/8a806778ea25e16314750eb4c3fc313f736442a6/extensions/git/src/api/git.d.ts#L175-L177

and implemented like so:
https://github.com/microsoft/vscode/blob/8a806778ea25e16314750eb4c3fc313f736442a6/extensions/git/src/git.ts#L1485-L1501

Is there something more that is needed?
