### ISSUE TITLE
how to comment out the codes with shortcut？？？

### ISSUE THREAD

**Issue by jasonshaw** [Microsoft/vscode#5913]
- VSCode Version:1.0.0
- OS Version:win7 sp1

Steps to Reproduce:

1. open a html file 
2. press ctrl+/ 

then the codes I selected are wrapped by {#...#}, instead of  commenting out the selected codes

**Comment by maxdeviant** [comment]
Does the editor show the correct language type in the corner?

![image](https://cloud.githubusercontent.com/assets/1486634/14863863/79221800-0c85-11e6-9b39-b92023257480.png)

**Comment by bpasero** [comment]
@jasonshaw do you maybe have an extension installed that takes over the ctrl+/ command?

**Comment by jasonshaw** [comment]
how can i comment out the codes in html css js php and so on without any extensions

**Comment by bpasero** [comment]
Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions`

**Comment by jasonshaw** [comment]
from the command line, it works, it seems that the problem is caused by some extension, but how to dig it out？

**Comment by bpasero** [comment]
@jasonshaw what extensions do you have installed?

**Comment by jasonshaw** [comment]
how can i export my ext list?

**Comment by bpasero** [comment]
@jasonshaw I fear the only way is to uninstall each extension until you found the one that causes this and report this as bug to the extension owner.

**Comment by jasonshaw** [comment]
I figure it out, that is the extension of emmet  name twig pack, can you fix it?  I just need the emmet function.
thx.
