### ISSUE TITLE
Debug toolbar doesn't reset after running .Net project

### ISSUE THREAD

**Issue by jtsom** [Microsoft/vscode#59143]
Issue Type: <b>Bug</b>

With a .Net Core web application, I can hit the "Run" button in the Touchbar to launch the application. Previously, when I hit the Stop button, the application would stop, and the start button would reappear. 

Now, however, the run button never returns when the application terminated.

VS Code version: Code - Insiders 1.28.0-insider (2558a72d6902015b142ef45c57b664ce1f09e03f, 2018-09-21T05:12:46.853Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (7.15GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
json-to-ts|Mar|1.5.5
ng-template|Ang|0.1.10
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.60
githistory|don|0.4.2
tslint|eg2|1.0.39
auto-rename-tag|for|0.0.15
Angular2|joh|6.1.5
csharp|ms-|1.17.0-beta2
vsliveshare|ms-|0.3.709
debugger-for-chrome|msj|4.10.1
vscode-docker|Pet|0.3.0
material-icon-theme|PKi|3.6.0

(3 theme extensions excluded)

</details>

**Comment by jtsom** [comment]
Not a duplicate.

**Comment by jtsom** [comment]
Further checking - It's more than just the Touch Bar, VS Code does not reset the bottom status bar when the application terminates. It stays orange.

**Comment by isidorn** [comment]
Fixed in latest, thanks for reporting
