### ISSUE TITLE
Support file watching over network drives

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#59146]
* Samba share (https://github.com/Microsoft/vscode/issues/1551)
* Mounted network drive (https://github.com/Microsoft/vscode/issues/29807)
* SSHFS (https://github.com/Microsoft/vscode/issues/49838)

**Comment by lopugit** [comment]
still broke? :(

**Comment by lopugit** [comment]
it takes a while I think, eventually shows changes

**Comment by lae0901** [comment]
is there an alternative way for an extension to be notified when a mapped network drive file is changed in vscode?  How does source control detect file changes?
