### ISSUE TITLE
Unicode characters (emojis?) messing up terminal

### ISSUE THREAD

**Issue by dnfield** [Microsoft/vscode#59145]
- VSCode Version: 1.27.2
- OS Version: macOS High Sierra

Steps to Reproduce:

1. Paste 🌑🌘🌗🌖🌕 into the terminal
2. Try to edit the line or delete the characters

The characters don't get deleted properly, and too much space is used before and after them.  Seems like a unicode handling bug.  This is particularly annoying if a tool uses those characters to print progress updates in a terminal, which drives it crazy and gets them stuck all over the place until the terminal is hidden and open again:

![image](https://user-images.githubusercontent.com/8620741/45913662-9df76300-bdeb-11e8-8b95-48fc3e4241e0.png)

/cc @DanTup FYI

**Comment by dnfield** [comment]
I usually use the terminal.  Habits!

**Comment by DanTup** [comment]
You'll miss out on things like debugging, hot-reload-on-save, inspect widget and other stuff from the terminal :-)

But if there are things you use the terminal for that don't have equivs built-in, do let me know. For ex., I don't think we have a Clean command, but hopefully we've got all the common things covered.

(I can't offer any help for this bug though, seems to be entirely the built-in terminal and unrelated to the extensions or Flutter).

**Comment by Tyriar** [comment]
Tracking this is https://github.com/Microsoft/vscode/issues/59145
