### ISSUE TITLE
Marketplace search for publisher: "name" (with space) includes extensions from other publishers

### ISSUE THREAD

**Issue by TomasHubelbauer** [Microsoft/vscode#59142]
Searching for `publisher: "Tomas Hubelbauer"` shows my extensions and then an extension from one other publisher. I think this should match the exact value unless I am missing something.

I am using the VS Code query made to the Marketplace API to pull stats for my extensions periodically and it obtains extensions that are published by me using this query, so if exact matching on publisher name is not supported by Marketplace search, I'd like to find out if there is a reliable way to get extensions for a publisher using the Marketplace API?

I know about the [publisher page](https://marketplace.visualstudio.com/publishers/TomasHubelbauer), but in terms of stability even a non-public API is better than scraping that page.

**Comment by ramya-rao-a** [comment]
Interestingly, if you remove the space between the `:` and the `"`, you get the right results

**Comment by TomasHubelbauer** [comment]
Cool find with the space, thank you!

**Comment by harishkragarwal** [comment]
@viradhamMS

**Comment by pkuma-msft** [comment]
@TomasHubelbauer To add more details, the search term **publisher: "Tomas Hubelbauer"** (with a space) gets tokenized into two search words 'publisher' and 'Tomas Hubelbauer' and the first term 'publisher' matches with mfk-vscode-publisher (tokenized), that's the reason the other publisher's extension show up.

Without the space the search term is treated specially (sort of like our own query language) which specifically looks for an exact match in the publisher name. 

We can close this issue. (cc @ramya-rao-a , @joaomoreno)

**Comment by kesane-msft** [comment]
@ramya-rao-a / @TomasHubelbauer this has been fixed. Could you please verify?

**Comment by TomasHubelbauer** [comment]
It seems to be fixed. I am getting only my extensions when searching for both `publisher:"Tomas Hubelbauer"` and `publisher: "Tomas Hubelbauer"`.
