### ISSUE TITLE
Auto File Imports Inline Rather than at the Top of the File.

### ISSUE THREAD

**Issue by cgen01** [Microsoft/vscode#59149]
### Description

There seems to be an issue with importing files. When I start to type a file to add to my component, VSCode used to import it to the top of the file. Now it imports it inline. Is there a setting for this that I'm not aware of? Or is this a bug?

### Example

![screencast 2018-09-22 05-58-10](https://user-images.githubusercontent.com/39174127/45916089-43332b00-be2e-11e8-9dbe-5c268ed01177.gif)

### Information

- VSCode Version: 1.28.0-insider
- OS Version: macOS 10.13.6
- Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/27317 to track this upstream
