### ISSUE TITLE
Can't see describe of extensions

### ISSUE THREAD

**Issue by lakid1** [Microsoft/vscode#59150]
Issue Type: <b>Bug</b>

Hello I can't see describe of any extensions or describe of new update. Last time when I was using VS code I have at bottom of my screen white line from errors to option button.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

**Comment by sandy081** [comment]
@lakid1 Not sure if I understood your issue. Can you please provide screenshot of what you are seeing to get better understanding?

**Comment by lakid1** [comment]
![image](https://user-images.githubusercontent.com/43139326/46082105-90046200-c19e-11e8-8770-f9af9a5d09d9.png)

**Comment by sandy081** [comment]
@mjbvz Could be related to web view?

@lakid1 Can you please check if the other tabs are showing content?

**Comment by lakid1** [comment]
Still the same. I am actually tried to reinstall vscode but no results.

**Comment by sandy081** [comment]
@lakid1 You mean you do not see anything in `Contributions` tab?

Can you open developer tools and let us know if there are any errors?

**Comment by mjbvz** [comment]
Duplicate of #57209 

Please try this in [latest VS Code insiders build](https://code.visualstudio.com/insiders/)
