### ISSUE TITLE
String output is truncated in Linux

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5915]
- VSCode Version: alpha
- OS Version: Ubuntu 15.10
#4952

Steps to Reproduce:
1. Create a javascript variable with 10,000 characters called string then:

``` javascript
console.log(string);
```
1. Use a tool to count the characters in the debug console, or create a new string with the copied output and output the length. 

My 10,000 string is only showing 9679 characters in the output.

**Comment by isidorn** [comment]
The output event which I recieve does not contain the full string.
The repl is capable of showing the full string which can be seen if you simply evaluate that string in the repl

Here's a simple repro
```
for (var i = 1; i < 10000; i++) {
    s += 'x';
    
} 

s += 'A';
console.log(s);
```

Forwarding to @weinand to check why the output event does not contain the full string

**Comment by weinand** [comment]
Cannot reproduce in VS Code 1.1.1 and latest.

**Comment by isidorn** [comment]
I still see this with latest using the sample above

**Comment by weinand** [comment]
This works fine on Windows.
On OS X and linux only 8192 characters are coming through the output event. It seems that console.log uses a buffer of that size.

**Comment by garthk** [comment]
Could this be nodejs/node#6456 in action?

**Comment by weinand** [comment]
no longer an issue with "inspector" node-debug.
