### ISSUE TITLE
Changing extensions/user settings directories

### ISSUE THREAD

**Issue by Inhert** [Microsoft/vscode#59158]
Hi,

My university would like to use this program for teaching purposes.
However, due to a restricted work environment it is difficult to configure installs with extension support for hundreds of users.

Would it be possible to implement a feature for setting the files under the user account to another location, for example a network drive? 

I've tried the portable installation, but it takes up too much space and can be quite slow and unwieldy to use in this scenario.

**Comment by sandy081** [comment]
@Inhert You can configure the location of extensions directory using `--extensions-dir` cli option. But it is not recommended to do it under a shared location.
