### ISSUE TITLE
Docker Workspace removes quotes in go files.

### ISSUE THREAD

**Issue by miloup** [Microsoft/vscode#59153]
Hi,

I just installed the Docker workspace plugin for virtual studio on my Mac, and I am using a 'golang' Docker container straight from the Docker hub image (it uses an Ubuntu OS).
When I write my Go code on VS and save it, VS removes the double quotes from my file which makes it un-executable on the container (removes quotes from `import "fmt"` for example).

Anyway I can get this fixed?

Thanks

**Comment by miloup** [comment]
Hi @ramya-rao-a and sorry for misleading you. Indeed, I was talking about Virtual Studio Code.

**Comment by ramya-rao-a** [comment]
In that case, there might be some other extensions that is interfering. Can you disable all the extensions other than Go and Docker and see if you still have the issue?
