### ISSUE TITLE
Add events to extension API to capture editor opened / editor closed

### ISSUE THREAD

**Issue by Divni** [Microsoft/vscode#59159]
At the moment there is no proper way of capturing that the user opened or closed a tab. You can capture whether they switched between tabs, and you can capture opens/closes of text documents, but not editors.

Note that the text document events aren't helpful here because they trigger any time you switch between files.

As a workaround I've noticed that when switching tabs the onDidChangeActiveTextEditor event is called before onDidCloseTextDocument. When closing a tab it's the inverse. You can use this information to infer whether a tab was closed or just switched, but that requires you to use some very error-prone timing.

This request is similar to but not the same as https://github.com/Microsoft/vscode/issues/15178

**Comment by jrieken** [comment]
> This request is similar to but not the same as #15178

It is the same

**Comment by Divni** [comment]
@jrieken with due respect I disagree. Not to say it cannot be solved the same way, the linked ticket is requesting an API to retrieve a list of open editors. I'm requesting an API to listen for events for opened / closed editors. These are not the same things, though they can certainly address similar use-cases.

**Comment by jrieken** [comment]
> These are not the same things, though they can certainly address similar use-cases.

Rest assured that we will tackle the open-editor-issue properly. That means expose read access and events when those change (e.g. you have to read again).
