### ISSUE TITLE
Don't open debug panel on run

### ISSUE THREAD

**Issue by jpsauv** [Microsoft/vscode#59154]
If I'm only running a code file (not debugging), the side bar should not switch to the debug panel but stay where it is. So if I'm running a code file from the Explorer panel and click Run over the main method, key ^F5, etc to run **without** the debugger, then the side bar should stay where it is, on the Explorer and not jump to the Debug panel.

**Comment by stuartjamesmiller** [comment]
I'm not sure if a seprate issue but it is extremely annoying when using nodemon and every time I hit save the debugger panel opens and the explorer closes as this triggers a restart. If the code running hits a break point then opening the debugger makes sense but otherwise it's really disruptive.

**Comment by octref** [comment]
@isidorn How to "run code from explorer panel without debugger"?

**Comment by isidorn** [comment]
@octref F1 > Debug: Start Without Debugging
