### ISSUE TITLE
Weird character loss on C&P from code to the terminal

### ISSUE THREAD

**Issue by 3manuek** [Microsoft/vscode#59167]
Issue Type: <b>Bug</b>

I did a copy of all the file and somehow the paste lost a few characters that made the command fail ("ext,\n" was the missing piece ). I re-copied only the last part that failed so I can show the missing pieces. 

```
... above commands ran ok ...
test=# CREATE TABLE IF NOT EXISTS im_not_ok_no_replica_identity (
test(#     x bigserial ,
test(#     o text default random()::t    o text defastamp default clock_timestamp()
test(# );
ERROR:  syntax error at or near "o"
LINE 3:     o text default random()::t    o text defastamp default c...
                                          ^
test=#
test=# CREATE INDEX imCnot_ok_no_replica_identity_partial_index ON im_not_ok_no_replica_identity(x) WHERE x > 2;
ERROR:  relation "im_not_ok_no_replica_identity" does not exist
test=#
test=# CREATE TABLE IF NOT EXISTS im_not_ok_no_replica_identity (
test(#     x bigserial ,
test(#     o text default random()::text,
test(#     d timestamp default clock_timestamp()
test(# );
CREATE TABLE
```

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:04:11.329Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
go|Twe|0.0.1
code-gnu-global|aus|0.2.2
vscode-markdownlint|Dav|0.20.0
vscode-instant-markdown|dba|1.4.2
xml|Dot|2.3.2
pgsql|dou|0.1.3
godot-tools|gee|0.3.7
mdmath|goe|2.3.4
mdhelper|jos|0.0.11
vscode-gutter-preview|kis|0.14.2
markdown-shortcuts|mdi|0.8.1
vscode-clang|mit|0.2.2
python|ms-|2018.8.0
cpptools|ms-|0.18.1
Go|ms-|0.6.89
Spell|sea|1.0.0
vscode-sql-beautify|sen|0.0.4
vscode-multiclip|sle|0.1.4
vscode-mermaid-preview|vst|0.10.1
markdown-pdf|yza|1.2.0
markdown-all-in-one|yzh|1.6.0

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
It's not clear what part is missing? Maybe a screenshot would help?
