### ISSUE TITLE
VSCode is trying to enable bluetooth without a reason. It's a privacy issue

### ISSUE THREAD

**Issue by tairosonloa** [microsoft/vscode#59162]
VSCode is trying to enable bluetooth. I don't know why. I can't realize why a code editor will need bluetooth for any reason, and indeed is a privacy issue.

I cant see that on my system log every time I open VSCode:

If I open VSCode and next:
```
$ journalctl -xe | grep code
sep 22 18:43:29 hostname dbus-daemon[407]: [system] Activating via systemd: service name='org.bluez' unit='dbus-org.bluez.service' requested by ':1.2018' (uid=1000 pid=24366 comm="/opt/visual-studio-code/code ")
```
Same problem with extensions disabled
```
$ journalctl -xe | grep code
sep 22 18:49:25 hostname dbus-daemon[407]: [system] Activating via systemd: service name='org.bluez' unit='dbus-org.bluez.service' requested by ':1.2038' (uid=1000 pid=24918 comm="/opt/visual-studio-code/code --disable-extensions ")
```

- VSCode Version: 1.27.2
- OS Version: GNU/Linux with kernel 4.14.71-1-lts (it occurs in other kernels too)

Steps to Reproduce:

1. Open VSCode
2. Check system log with journalctl

Does this issue occur when all extensions are disabled?: Yes

**Comment by btruhand** [comment]
@tairosonloa do you have any idea how to do the same checking on OSX? Just curious

**Comment by tairosonloa** [comment]
I haven't and never had an apple computer, so I have no idea @btruhand

**Comment by tairosonloa** [comment]
I didn't want to close the issue...

**Comment by ti-mo** [comment]
Just noticed the same behaviour here. Why does this happen?

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)

**Comment by tairosonloa** [comment]
The original issue was on an ArchLinux based distro. Do you have an amd64 binary or source code to build my own?

**Comment by tairosonloa** [comment]
However, with code 1.39.1 88f15d17dca836346e787762685a40bb5cce75a8 x64 this issue isn't reproducing anymore, as this thread is more than a year old.
