### ISSUE TITLE
Gutter Diffs: rollback, allow editing, de-dupe surrounding code

### ISSUE THREAD

**Issue by keyframer** [Microsoft/vscode#59164]
Re: https://github.com/Microsoft/vscode/issues/10782 :
Often when I'm jumping between inline diffs (using `editor.action.dirtydiff.next`) I want to completely rollback the chunk, or select some of the old code to copy into my change.

This inline editor also displays lines before and after the diff, so there's lines doubled up making the code really hard to read.

I also can't edit in the inline diff view so it's clumsy to make these changes (extra clumsy because I see the line I need to change twice: once inside the read-only editor and again immediately after.

IntelliJ really gets this workflow right!
VSCode's diff view while in Inline View is pretty close:
- PRO Way easier to read surrounding code w/o the inline diff chrome and doubled-up lines.
- PRO Can make edits because you're in a real editor.
- CON Can't select/copy the red changed code.
- CON Can't rollback the entire chunk.

You also want the workflow that the new inline diffs give you of clicking in the gutter or navigating with keyboard shortcuts.  If you merged the features of the classic Inline Diff View and this newer Gutter Diffs you'd have something really great!

Check out the first GIF in the issue that started this feature for some missing rollback/copy features.
https://github.com/Microsoft/vscode/issues/10782
And the comments after the feature was built but before the thread was closed for supporting comments.

Thank you!

**Comment by joaomoreno** [comment]
Can't copy original buffer: #8226

There are actions at the top of the widget, on the right side. The arrow `Revert Change` lets you rollback the entire chunk. Did you try that?
