### ISSUE TITLE
The editor easily jammed

### ISSUE THREAD

**Issue by qq250933400** [Microsoft/vscode#59178]
Issue Type: <b>Bug</b>

when the Code hinting drop-down box pops up, or when select text easily jammed, this problem can occur easily in HTML

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.10240

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|3.86GB (0.96GB free)|
|Process Argv|H:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
mpvue-snippets|ban|1.2.1
vscode-eslint|dba|1.6.0
app-migrator|deb|0.0.6
tslint|eg2|1.0.39
apacheconf-snippets|eim|1.1.9
php-file-types|fet|1.2.1
php-snippets|heb|0.0.3
crane|Hvy|0.3.8
vscode-react-typescript|inf|1.0.17
vscode-icon-rotation|kri|1.0.4
code-beautifier|mic|2.1.0
vscode-apache|mrm|1.1.1
vscode-language-pack-zh-hans|MS-|1.27.2
minapp-vscode|qiu|1.8.1
easy-compile|ref|1.1.2
vscode-icons|rob|7.26.0
php-formatter|Sop|0.2.4
wepy-snippets|wle|1.5.14
tslint-snippets|zuo|1.1.0

</details>

**Comment by bpasero** [comment]
@qq250933400 can you explain what you mean, maybe with a screenshot?
