### ISSUE TITLE
Terminal opens at 

### ISSUE THREAD

**Issue by matjazmav** [Microsoft/vscode#59176]
Issue Type: <b>Bug</b>

Terminal starts at C:\Windows\System32\WindowsPowerShell\v1.0> not at the folder that is currenty opended.

terminal.integrated.cwd is empty

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.92GB (6.80GB free)|
|Process Argv|C:\Users\matja\AppData\Local\Programs\Microsoft VS Code\Code.exe C:\Users\matja\Downloads\[CourseClub.NET] Lynda - React js Essential Training\Ex_Files_React_EssT_Upd\Ex_Files_React_EssT_Upd\Exercise Files\Ch02\02_01\start\dist|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
gitlens|eam|8.5.6
EditorConfig|Edi|0.12.4
beautify|Hoo|1.4.4
mssql|ms-|1.4.0
csharp|ms-|1.16.1
vscode-docker|Pet|0.3.0
code-spell-checker|str|1.6.10

</details>

**Comment by Tyriar** [comment]
How are you opening the terminal? Can you share your settings.json file?

**Comment by matjazmav** [comment]
After restarting, terminal opened at folder location. I couldn't repeat it.
