### ISSUE TITLE
Template string syntax highlighting fails together with ((): + object member

### ISSUE THREAD

**Issue by gforge** [Microsoft/vscode#59175]
- VSCode Version: 1.27.2
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Create a file with the following code:

```js
// @flow

class MyClass {
  b = undefined;

  getMarker4Tool(a: string) {
    b = ((a: any): MyType);
  }

  aFunction(history) {
    history.push(`/goto/${b}`);
  }

  log() {
    console.log('this part is brown :-(');
  }
}
``` 
2. You should see the following highlight (this is with  `code --disable-extensions`):
![buggy vscode highlight](https://user-images.githubusercontent.com/2198913/45925059-63d2b200-bf0e-11e8-9ceb-030b06b10124.png)

This is all caused by the pattern in `b = ((a: any): MyType);` in combination with the `history.push` that can be boiled down to `(():` + accessing an object member + template string. Just do `push()` and the error disappears.

**Comment by mjbvz** [comment]
Please install the flow extension. Our built-in js grammars don't support flow syntax

**Comment by gforge** [comment]
Oh, sorry. I have the `Flow Language Support` and this seems to be a known bug where they wait for the main JS highlighter to be fixed: https://github.com/flowtype/flow-for-vscode/issues/103

Anyway, as suggested in the comments the [sublime-babel-vscode](https://marketplace.visualstudio.com/items?itemName=joshpeng.sublime-babel-vscode) solves the issue.

Thanks and sorry for posting in the wrong place :pensive:
