### ISSUE TITLE
Column selection issue with ctrl+shift+arrows

### ISSUE THREAD

**Issue by youngminpark2559** [microsoft/vscode#59171]
I left a question about this column selection issue on stackoverflow.
https://stackoverflow.com/questions/52241239/column-selection-issue-with-ctrlshiftarrows

But I didn't get reply and I'm thinking this feature is not supported by vscode.
So, I'm trying to raise a new feature request.

When I use column selection, cursors are not arranged like this.
![olwvg](https://user-images.githubusercontent.com/30585126/45923101-b369ab80-bf17-11e8-85ef-7ec8b4822bce.png)

This disarrangement of cursors breaks structure of code when rearranging code.

Atom editor does keep the arrange of cursor like this
![gbsak](https://user-images.githubusercontent.com/30585126/45923109-ca100280-bf17-11e8-8f49-c9590da5c2f3.png)

So, it supplies good functionality for rearranging code structure

I wonder if there is preference option for this and if not I hope that will be provided in the future as new feature.

Thanks.

**Comment by spbroma** [comment]
I'm surprised that this issue has no discussion. This behavior is extremely annoying and in Sublime Text I found extension to fix it, but no one in VS Code.

This problem can be solved by selecting with mouse, but it is not right way. I wonder, if in could be build-it option in Setting.
