### ISSUE TITLE
emmet has parse error when using p(lorem10)

### ISSUE THREAD

**Issue by xjl456852** [microsoft/vscode#59172]
Issue Type: <b>Bug</b>

When I use emmet  to parse  expression, it  doesn't  parse properly .
expression:
table.table-row[role='table']>(thead>tr>td{item $@120}*5)+(tbody>tr>(td.item$$@-)lorem10*5)

I try it in sublime text 3 use emmet , It can be parse correctly

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.82GB (10.64GB free)|
|Process Argv|D:\soft\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|40%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.27.2
LiveServer|rit|5.1.1
livereload|zee|0.1.1

</details>

**Comment by ramya-rao-a** [comment]
In https://docs.emmet.io/ that expands to 
```
<table class="table-row" role="table">
    	<thead>
    		<tr>
    			<td>item 120</td>
    		</tr>
    	</thead>
    	<tbody>
    		<tr>
    			<td class="item01">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore voluptatum nobis nostrum labore mollitia dignissimos officia molestias nisi non asperiores. Ipsa labore sunt perferendis voluptas reprehenderit, repellat quis vel expedita natus ex dolore aspernatur id veritatis exercitationem quo suscipit nisi aliquid aperiam accusantium totam quibusdam, fugiat debitis adipisci quod. Sit nihil cupiditate asperiores reiciendis cumque, ducimus quaerat sapiente officiis, dolorem saepe aperiam laudantium at! Fugit optio illum, itaque laborum expedita nesciunt eos debitis minima. Sapiente, itaque delectus eligendi at repellendus impedit possimus magni modi et necessitatibus repudiandae voluptates tempora rem, corrupti maxime culpa vel quae incidunt, quam, temporibus vitae autem. Ab, dolore in illum nulla!</td></tr>
    	</tbody>
    </table>
```

Is that the expected output?

**Comment by ramya-rao-a** [comment]
`table.table-row[role='table']>(thead>tr>td{item $@120}*5)+(tbody>tr>td.item$$@-*5>lorem10)` expands to what you would expect

The reason is that `(p)lorem10` is a valid syntax as per https://docs.emmet.io/ and the old emmet.
VS Code uses the new emmet modules where it is not valid. But `p>lorem10` is valid.

I have logged an upstream issue in emmet. https://github.com/emmetio/expand-abbreviation/issues/24

**Comment by rzhao271** [comment]
I'm closing this issue because currently other text editors also use `p>lorem10` instead of `(p)lorem10`.
