### ISSUE TITLE
Weird rendering for files with Emoji filenames

### ISSUE THREAD

**Issue by clsource** [Microsoft/vscode#59174]
Hello I found this little bug. Thanks for your awesome code editor 👍 

- VSCode Version: 1.27.2 (1.27.2)
- OS Version: MacOS 10.13.6 (17G65)

Steps to Reproduce:

1. Create a file with an emoji filename (Example `😀_file.txt`)
2. Open in the editor. Weird rendering would appear in the
Open Editors Section and File Tab.

![imagen](https://user-images.githubusercontent.com/292738/45924164-3581b200-becf-11e8-9dad-d78e18bc4fd0.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by fedorg** [comment]
What is the problem here? Is the kerning around the italics emoji a little weird or something? I can't think of a reason why this might be a *bug*.

**Comment by clsource** [comment]
You are right I just forgot that VS Code do italics to files in those areas.
My mistake for programing late xd.

Thank you.
