### ISSUE TITLE
Custom snippets stop working in long sentences

### ISSUE THREAD

**Issue by croaton23** [Microsoft/vscode#59189]
- VSCode Version: 
Version: 1.27.2 (system setup)
Commit: f46c4c469d6e6d8c46f268d1553c5dc4b475840f
Date: 2018-09-12T16:17:45.060Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

- OS Version: Windows 10 1803 (OS Build 17134.285)

Steps to Reproduce:
1. Create some custom user snippets for HTML. 
2. Open an HTML document, start typing some text.
3. After the first or second word try to insert your snippet by typing its prefix. It works.
4. Continue typing. After you have around 15-20 words in a paragraph, try inserting your snippet 2-3  times. It does not work.
For some strange reason, my snippets stop working randomly in the document. In some places, it is possible to insert a snippet, in others - snippet does not appear in the drop-down list.
I've tried reinstalling VS Code, disabled all extensions and reproduced this with code --disable-extensions. It is also present in the insider build.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
Good news: This is fixed in [VS Code Insiders](https://code.visualstudio.com/insiders/).
