### ISSUE TITLE
C++ syntax highlighting not working properly

### ISSUE THREAD

**Issue by chengzeyi** [Microsoft/vscode#59186]
- VSCode Version: 1.27.2
- OS Version: Ubuntu 18.04 LTS

Steps to Reproduce:

1. Create a new cpp source code file.
2. name a local variable or a function parameter "sEnd".
```c++
bool match(string::const_iterator iterS, const string::const_iterator& sEnd, CompiledPattern::const_iterator iterP, const CompiledPattern::const_iterator& pEnd) const

int sEnd;
```
The color of "sEnd" is the same as class member's, not what it should be.
In my case,  the color should be white but in fact it is rendered to be sky blue.
Other names like siEnd don't have this problem. Is it resulted from bugs of vscode syntax highlighting engine?

Does this issue occur when all extensions are disabled?: No

**Comment by aeschli** [comment]
This issue was moved to atom/language-c#285
