### ISSUE TITLE
Formatted comments/documentation

### ISSUE THREAD

**Issue by generateui** [microsoft/vscode#59185]
Documentation is painful to read when reading plain (C#/[insert language]) code. You must perform human parsing on the xml elements.

It would be great if there can be different rendering based on the type of AST node you're in, starting and ending with a line.

---

Instead of this:
https://imgur.com/a/x1deCKZ
![image](https://user-images.githubusercontent.com/5047891/46601639-00d84200-caee-11e8-9048-b9cc2b84af74.png)

---

I want this:
https://imgur.com/a/AuhIL7q
![image](https://user-images.githubusercontent.com/5047891/46601649-07ff5000-caee-11e8-96d8-a5ac7849656c.png)

---

To achieve this, I imagine some sort of renderer registered to certain AST nodes (CommentRenderer for CommentNode). 

*Edit*: Inlined images

**Comment by MatthiasWinkelmann** [comment]
See https://github.com/Microsoft/vscode/issues/3220#issuecomment-430124153 for discussion of a similar request.
