### ISSUE TITLE
Commas are inconsistently added to JSON completion

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#5918]
- VSCode Version: 1.1.0-alpha
- OS Version: Mac

Steps to Reproduce:

Regarding test plan #5753
Just found this very small bug (not an urgent one—ok to delay if necessary).

1. Type just a package name in bower.json with no leading quotation mark (so it autocompletes the quotes for you)
2. Now try adding a package *with* a leading quotation mark.

Note that in the first case a comma is not added, but in the second case a comma is added.  Not a huge deal, but consistency would be nice.

Preferably, if it knows that it's on the last line of properties (i.e. the next line is a closing brace), then it would not insert a comma.  But if it's in the middle of the list (i.e. the next line is another property in the JSON), then it would add a comma.

**Comment by aeschli** [comment]
I always get a comma:
```json
{
    "dependencies": {
       d
       "hui": "latest",
       "angular-latest": "latest"
    }
}
```
Code assist after `d`: Completes to  `"d-style": "latest",`
Code assist after `"d`: Completes to  `"d-style": "latest",`
Code assist inside `"d"`:Completes to  `"d-style": "latest",`

```json
{
    "dependencies": {
       "hui": "latest",
       "angular-latest": "latest",
       d
    }
}
```
Code assist after `d`: Completes to  `"d-style": "latest"`
Code assist after `"d`: Completes to  `"d-style": "latest"`
Code assist inside `"d"`:Completes to  `"d-style": "latest",` -> Bug

Let me know if you saw another issue.

**Comment by bgashler1** [comment]
@aeschli yes, that's what I was seeing.  Thanks for checking!
