### ISSUE TITLE
Editor is forcefully focused after using inline staging

### ISSUE THREAD

**Issue by SanderRonde** [Microsoft/vscode#59190]
- VSCode Version: 1.27.2
- OS Version: Windows 10 Pro version 1803

Steps to Reproduce:

1. Make some changes to a file that is set up with git
2. Use the inline staging feature to stage a single change
3. Click the "message" box in the source control panel in order to direct focus there
4. Start typing
5. Staging completes for the change
6. The editor focuses the next change in the file and steals focus from the source control panel

[Video that more clearly shows the problem](https://cdn-b-east.streamable.com/video/mp4/trxlr.mp4?token=TFpSiEH63x6KSQG6NS-tLA&expires=1537733629)

This is not as much of an issue when git is faster than you are able to click the "message" box, but in my experience, git tends to take a few seconds on Windows. This issue then becomes quite annoying because you always have to wait it out or type faster than git stages the change.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
We no longer focus the next change in the file since this month (you can try this behavior in Insiders).

**Comment by SanderRonde** [comment]
I have tried this again in the newest insider build and the issue still persists, even though it happens a bit differently. You're right that the next change is no longer being focused, but the editor itself is still being focused. [Here is a video of it in action (using the latest insider build)](https://cdn-b-east.streamable.com/video/mp4/jm9cl.mp4?token=iOlsbPOmqsb2iMcXoCeCxw&expires=1537812692).
