### ISSUE TITLE
Align app icon in top left corner with sidebar icons

### ISSUE THREAD

**Issue by Splike** [microsoft/vscode#59191]
The picture below shows what I mean.
I've made a mockup with a slightly larger icon(36x36 pixels), in contrast to the original (28x28 pixels), as I think it looks better with a larger icon to match the size of the side-panel icons.

![image](https://user-images.githubusercontent.com/7159527/45932080-703f2500-bf77-11e8-8dc5-db0e13411a6a.png)

**Comment by sbatten** [comment]
@Splike Is the left side what you are seeing in the product today? If so, do you always see this or is this after some resizing or some other relayout behavior?

**Comment by Splike** [comment]
Yes, this is what I see in the product today (1.27.2), where I have set `"window.titleBarStyle": "custom"` and no additional options have been set or resizing done.

**Comment by Splike** [comment]
I've had to reinstall VS code and now mine does look like your picture.

But would it still be possible to align  and center the icon, like in my right picture?

**Comment by sbatten** [comment]
@Splike Thanks for the suggestion, I'll try it out and get back.
