### ISSUE TITLE
configurationRegistry Library

### ISSUE THREAD

**Issue by KamalAman** [Microsoft/vscode#59195]
The implementation and UI of the vscode configurationRegistry has progressed a long way from the initial implementation. 

If the configurationRegistry was pulled out into its own library, it would be very powerful tool.

I see two parts to this library, the first part is the configurationRegistry itself that would allow developers to add and defined configurations to a registry. 

The send part to this, would be a UI component that would allow editing of the registry itself to create the override file.

**Comment by sandy081** [comment]
@KamalAman Are you asking to extract configuration component into separate node_module?

**Comment by KamalAman** [comment]
Yes, if that is something that would be possible.

**Comment by sandy081** [comment]
Sorry we do not have plans to do it.
