### ISSUE TITLE
Crash when File > Open Recent menu is opened

### ISSUE THREAD

**Issue by taitcw** [Microsoft/vscode#59194]
Issue Type: <b>Bug</b>

1. Start VS Code
2. Click File
3. Click Open Recent
4. Browse the list for a while (10-20 sec)
5. Crash - VS Code stopped responding, Close Program etc.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (10.51GB free)|
|Process Argv|C:\Users\taid\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|0.12.0
rainbow-csv|mec|0.6.0
python|ms-|2018.8.0
cpptools|ms-|0.18.1
vscode-hexdump|sle|1.6.0
code-spell-checker|str|1.6.10

</details>

**Comment by bpasero** [comment]
@taitcw are you using the new custom menu or standard one?

**Comment by taitcw** [comment]
I am using the standard menu (I haven't customised any menu).  I tried to reproduce the problem (crash) after I submit the ticket but so far it hasn't crashed again.  I will note down the steps if it does crash again.

**Comment by bpasero** [comment]
That would be great!
