### ISSUE TITLE
Incorrect green highlighting of variable in separate files

### ISSUE THREAD

**Issue by mrag89** [Microsoft/vscode#592]
Here is how to reproduce the problem: 

I have a folder open in VS Code where I made two files: fileA.js and fileB.js

fileA.js was made first and a variable called "example" was declared and defined with a string. fileB.js was made after and another variable, also called "example" was declared and defined, but this time with an integer. The variable "example" in fileB.js is underlined green with the message "Subsequent variable declarations must have the same type".

Is this behavior correct?

I am using VS Code 0.10.1

**Comment by jrieken** [comment]
Indeed that's indented but you can configure it with the `redeclaredVariables` JavaScript lint option. Even tho the functions are defined in two files they share the same (global) scope.
