### ISSUE TITLE
Insider Edition to only applying the latest update

### ISSUE THREAD

**Issue by wsmelton** [Microsoft/vscode#59207]
In situations where we have Insider Edition and it may be a machine that has not been touched in a few days (at most a week). It is always the case that we have to let all of the updates that were pushed out be applied in order/sequence they were released.

Is there a reason it cannot just install the latest update found at the time of startup or when it checks?
Is there something around how the releases for Insider are pushed out that prevents it from just pulling the latest release/commit to update against?

**Comment by joaomoreno** [comment]
> It is always the case that we have to let all of the updates that were pushed out be applied in order/sequence they were released.

I don't think that's true. In the worst case, the machine was running for those days and downloaded an old update. If you update to it and restart, you just need to do one more update: the current one. You do not have to do all updates since that version.

/duplicate #44685
