### ISSUE TITLE
Bower JSON completion not suggesting versions

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#5920]
- VSCode Version:1.1.0-alpha
- OS Version: Mac

Regarding test item #5753
Just found this issue a day after I did my testing.

Steps to Reproduce:

1. In a bower.json file, type in a package in the dependency section (I used lodash as the package).  It will auto-complete and give you `"lodash":"latest"`
2. Try changing `latest` to something else, like `^1.0.0`
3. Note that it does not give you a suggestion like it would in a package.json file.

**Comment by aeschli** [comment]
I just haven't found a server API yet that would give me all versions. https://github.com/bower/registry/issues/26 is talking about that.
Duplicate of #4630
