### ISSUE TITLE
mac 10.13.6 (17G65) - vs code won't open

### ISSUE THREAD

**Issue by samlotti** [Microsoft/vscode#59200]
Upgraded mac to 10.13.6, trying to open vs code gets a process stuck.
Trying to open again and get:  Another instance of Code is running but not responding

Deleted VS Code, redownloaded it and same thing happens.

**Comment by bpasero** [comment]
@samlotti does it happen after a OS restart too?

**Comment by samlotti** [comment]
I rebooted and it did fix the issue.
Thank you
