### ISSUE TITLE
Enable IntelliSense for Javascript functions parameters

### ISSUE THREAD

**Issue by b1tdust** [Microsoft/vscode#59204]
Is it possible to make a reference to a .d.ts file in order to enable IntelliSense for the function parameters?

To explain my self, I'm writing tests with [puppeteer](https://pptr.dev) and I have this module
```javascript
class LoginTester {
    /**
     * Login 
     * @static
     * @param {Page} page // puppeteer Page Class
     * @memberof LoginTester
     */
    static async logIn(page) {
        
    }
}
```

The typings for **Page** are declared in **/node_modules/@types/puppeteer/index.d.ts**. Could yo add the possibility to enable IntelliSense  for the function parameters listed inside its documentation?
For instance, It would be awesome to be able to do something like this:

```javascript
    /**
     * @param {puppeteer.Page} page
     * @param {puppeteer/Page} page
     * @param {/node_modules/@types/puppeteer/index.d.ts} page
    **/
```
Thanks to all the team and collaborators for such an awesome editor!

**Comment by IanMitchell** [comment]
I think you can do this already via the following:

```javascript
/** @typedef {import('puppeteer').Page} Page */
```

**Comment by b1tdust** [comment]
Super cool! Thanks!
