### ISSUE TITLE
VSCode 1.28.0-insider fails with `--list-extensions`

### ISSUE THREAD

**Issue by kankaristo** [Microsoft/vscode#59212]
Issue Type: <b>Bug</b>

The latest insider version (1.28.0-insider) fails to show the list of installed extensions with `code-insiders --list-extensions`.

Error message:
```
diagnostic_channel_1.channel.unsubscribe is not a function
```

VS Code version: Code - Insiders 1.28.0-insider (79f79a2c971d6eab36b92d78505402b42ffcae93, 2018-09-24T05:21:23.908Z)
OS version: Linux x64 4.18.7-200.fc28.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-8350 Eight-Core Processor (8 x 2490)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 4, 7|
|Memory (System)|15.65GB (7.23GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (58)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
Bookmarks|ale|9.1.0
jenkins-status|ale|2.2.0
project-manager|ale|9.0.0
clipboard-history|Anj|1.0.7
QML|bbe|1.0.0
vscode-toggle-quotes|Bri|0.3.2
vscode-glsllint|CAD|0.0.3
gitignore|cod|0.5.0
vscode-svgviewer|css|1.4.6
dart-code|Dar|2.18.0
jshint|dba|0.10.20
vscode-eslint|dba|1.6.0
gitlens|eam|8.5.6
tslint|eg2|1.0.39
vscode-npm-script|eg2|0.3.5
json-tools|eri|1.0.2
code-runner|for|0.9.4
macros|ged|1.2.1
mdmath|goe|2.3.4
todo-tree|Gru|0.0.88
vscode-settings-cycler|hoo|1.0.1
latex-workshop|Jam|5.10.1
Angular2|joh|6.1.5
language-haskell|jus|2.5.0
restructuredtext|lex|78.0.0
Lisp|mat|0.1.8
Angular-BeastCode|Mik|6.2.27
vscode-scss|mrm|0.6.2
python|ms-|2018.8.0
cpptools|ms-|0.18.1
csharp|ms-|1.16.1
debugger-for-chrome|msj|4.10.1
material-icon-theme|PKi|3.6.0
qub-xml-vscode|qub|1.2.8
java|red|0.31.0
vscode-coverage-gutters|rya|2.2.0
scratchpadmd|saa|0.0.4
vscode-open|san|0.1.0
trailing-spaces|sha|0.2.11
stylelint|shi|0.43.0
shader|sle|1.1.3
shellcheck|tim|0.5.1
vscode-lua|tri|0.12.4
sort-lines|Tyr|1.7.0
haskelly|UCL|0.5.4
unity-debug|Uni|1.3.0
vscode-arduino|vsc|0.2.20
vscode-java-debug|vsc|0.13.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.8.0
vscode-maven|vsc|0.11.0
vscode-todo-highlight|way|1.0.4
highlight-bad-chars|wen|0.0.3
vscode-jumpy|wma|0.3.1
better-align|wwm|1.1.6
swig|zhu|0.0.5
vscode-ag|zjh|0.3.1

</details>

**Comment by sandy081** [comment]
@joaomoreno Any quick insight about this error?

**Comment by joaomoreno** [comment]
@jrieken @ramya-rao-a app insights changes?

**Comment by kankaristo** [comment]
Updated both computers to:
```
1.28.0-insider
fe8d9d2470ddffb9dc2da604b23f5bd8a185cd66
x64
```

Now `--list-extensions` gives the same error message on both computers.

So, this has broken some time after https://github.com/Microsoft/vscode/commit/45986ca7abf63460dc96409a61fb2f0c98ba0b70 and before (or in) https://github.com/Microsoft/vscode/commit/79f79a2c971d6eab36b92d78505402b42ffcae93.

**Comment by sandy081** [comment]
This error is coming from the app insights library 

https://github.com/Microsoft/vscode/blob/master/src/vs/platform/telemetry/node/appInsightsAppender.ts#L28

**Comment by ramya-rao-a** [comment]
Fixed with https://github.com/Microsoft/vscode/commit/c9b88c68cc8ac784ae713cab1f9cf9e8ab6b6614
