### ISSUE TITLE
Can't access the terminal.

### ISSUE THREAD

**Issue by Prudvi01** [Microsoft/vscode#59213]
Issue Type: <b>Bug</b>

It just doesn't show anything and I can't type anything. I just can't I don't know how it happened.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2467M CPU @ 1.60GHz (4 x 1596)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.89GB (0.78GB free)|
|Process Argv|C:\Users\prudv\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|75%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
open-html-in-browser|cod|0.1.21
vs-code-http-server-and-html-preview|Fli|2.1.1
code-runner|for|0.9.4
octave|lea|0.1.1
python|ms-|2018.8.0
cpptools|ms-|0.18.1
PowerShell|ms-|1.8.4
team|ms-|1.136.0
LiveServer|rit|5.1.1
python|tht|0.2.3
octave-debug|tia|0.0.3
octave|toa|0.0.3

</details>

**Comment by octref** [comment]
Help -> Toggle Developer Tools, any error?

**Comment by Prudvi01** [comment]
Hi Daniel, turns out my cmd path was missing. I fixed it and it's working
now.
