### ISSUE TITLE
Output channel is not correctly cleared via API

### ISSUE THREAD

**Issue by ArtemGovorov** [Microsoft/vscode#59210]
- VSCode Version: Version 1.28.0-insider (1.28.0-insider) 2558a72d6902015b142ef45c57b664ce1f09e03f
- OS Version: macOS 10.13.3

Steps to Reproduce:

1. Create a simple extension with the following code:

```js
  const outputChannel = window.createOutputChannel(`My Test`);
  outputChannel.append('Test 1\n');
  outputChannel.show();
  setTimeout(() => {
    outputChannel.clear();
  }, 500);
  setTimeout(() => {
    outputChannel.append('Test 2\n');
  }, 1000);
```

2. Run the extension and observe the following output in the `My Test` output channel:

```
Test 1
Test 2
```

The expected output (just like it works in v1.27.2) is 

```
Test 2
```

The issue may be caused by the same change causing https://github.com/Microsoft/vscode/issues/59209

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
This is caused because of buffering the appended output and flushing it in regular intervals. But when signalled clear content should be flushed and cleared immediately. So fix is

- flush the content from the buffer
- clear it

**Comment by sandy081** [comment]
To verify:

- Verify the scenario described in description
- Another scenario

```typescript
const outputChannel = vscode.window.createOutputChannel(`My Test`);
    outputChannel.appendLine('Test 1');
    outputChannel.show();
    outputChannel.clear();
    setTimeout(() => {
        outputChannel.append('Test 2\n');
    }, 1000);

```

Expected output:

```
Test 2
```
