### ISSUE TITLE
Bug :: Opening wrong recently worked files every time

### ISSUE THREAD

**Issue by msudgh** [Microsoft/vscode#59214]
- VSCode Version: 1.27.2
- OS Version: Arch x64

Steps to Reproduce:

1. Create a workspace with some directory
2. In the case which `example1.txt`, `example2.txt` files are opened I've closed vscode 
3. Opening vscode and I'm seeing `example1.txt`, `example2.txt` as the recent files that I've worked on them
4. Again, I've closed vscode with these files: `example4.txt`, `example5.txt`
5. After restart system and executing vscode. Now, It opened `example1.txt`, `example2.txt` files as recently worked files which is wrong.

**Comment by bpasero** [comment]
@msudgh can you be more specific how you open the two files in the 3. step?

**Comment by msudgh** [comment]
@bpasero Imagine I've worked on some files then closed my vs code and started working on the project tomorrow but the files which opened with vscode as recently files aren't same as the files that last time I've closed my vscode.

**Comment by bpasero** [comment]
@msudgh I am not understanding you will have to give me a step by step example how to reproduce.

**Comment by msudgh** [comment]
@bpasero I've edited the issue's step's to reproduce with more explanation. I think it's clear.

**Comment by bpasero** [comment]
@msudgh I cannot reproduce that behaviour, see my video, the list of recently opened files is restored:

![peek 2018-09-24 12-04](https://user-images.githubusercontent.com/900690/45946763-28111880-bff2-11e8-9d77-d726fbd16a29.gif)

**Comment by msudgh** [comment]
@bpasero Before running vscode again, restart your pc. do the same files open again?

**Comment by msudgh** [comment]
I didn't tell about restart PC while vscode is running. Look at steps 4 and 5. I've tried to close vscode and then turned off or restart my pc not exactly at the time which vscode is running.

**Comment by bpasero** [comment]
@msudgh I do not think that would make a difference. If you do not restart, does it make a difference?
