### ISSUE TITLE
SCM: Support to automatically change active provider based on current open file

### ISSUE THREAD

**Issue by msudgh** [microsoft/vscode#59215]
In case I've created and opened a `workspace`, I think it'd be better `vscode` change the source control providers according to the currently active directory.

**Comment by joaomoreno** [comment]
What do you mean by "currently active directory"? How do you switch that?

**Comment by msudgh** [comment]
Switching action will perform by VSCode. In definition of current active directory i mean when one file is opend and editor focused on the file, the active directory is the directory that user added it into workspace tree in explorer pane and the opened and focused file is belong to the directory.

**Comment by joaomoreno** [comment]
So, you would like the SCM provider to automatically change based on the currently focused file?

**Comment by msudgh** [comment]
Exactly!
