### ISSUE TITLE
Settings: layout bug

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#59217]
- VSCode Version: 1.28-insider (2558a72d6902015b142ef45c57b664ce1f09e03f)
- OS Version: OSX 10.12.6

Steps to Reproduce:

1. Split the editor like in the first screenshot
2. Open the settings panel

The categories overwrite each setting, making the panel barely readable.

The weird thing is that reducing the Settings tab width fixes the problem, because it's reaching a media query limit I guess.

Does this issue occur when all extensions are disabled?: Yes

First screenshot:

![image](https://user-images.githubusercontent.com/199648/45943572-2aba4080-bfe7-11e8-9d01-ff8cc1758f67.png)

Second screenshot (reduced tab width):

![image](https://user-images.githubusercontent.com/199648/45943589-3b6ab680-bfe7-11e8-8da4-963f70354b8a.png)

My screen resolution: 27" 2560x1440 with default OSX scale.

**Comment by warpdesign** [comment]
@roblourens I updated to build fe8d9d2470ddffb9dc2da604b23f5bd8a185cd66 But there are still bugs:

![image](https://user-images.githubusercontent.com/199648/46005201-09278a80-c0b5-11e8-8933-c78fe78487d3.png)

**Comment by roblourens** [comment]
I still can't repro this, can you come up with steps to repro the issue from a clean state?

**Comment by warpdesign** [comment]
Opening VSCode, splitting it in 3 columns, selecting the middle column and opening preferences is enough to trigger the layer bug.

Here is the inspector on the TOC element:

![image](https://user-images.githubusercontent.com/199648/46040379-73214d80-c110-11e8-904e-225ea617c52f.png)

**Comment by warpdesign** [comment]
After more tests it seems it's related to the theme I'm using: this only happens with the `Nord` theme.

I was pretty sure I had tried with extensions disabled :/

I opened up an issue there: https://github.com/arcticicestudio/nord-visual-studio-code/issues/101

**Comment by roblourens** [comment]
So weird! I can repro with Nord too. I see the issue, tbh, I don't know why it doesn't look that way all the time.

**Comment by warpdesign** [comment]
That was fast! :)
