### ISSUE TITLE
CPU profile on startup stable vs insiders has changed in a weird way

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#59216]
Probably related to the change to use `requestIdleCallback()`.

**Stable:**
![image](https://user-images.githubusercontent.com/900690/45943470-b4b5d980-bfe6-11e8-872f-241c0b38e2e1.png)

**Insiders:**
![image](https://user-images.githubusercontent.com/900690/45943476-baabba80-bfe6-11e8-9b19-2dfbc29e68a1.png)

[old.zip](https://github.com/Microsoft/vscode/files/2410165/old.zip)
[new.zip](https://github.com/Microsoft/vscode/files/2410166/new.zip)

**Comment by jrieken** [comment]
I don't think its related to the idle callback... How did you create the Insiders profile?

**Comment by bpasero** [comment]
@jrieken yeah was just a guess. in both cases, from the command line: "code-insiders --prof-startup"

**Comment by jrieken** [comment]
Hm... the lower (Insider version) looks like cached data is being used. There is a flag --no-cached-data which need to be set for meaningful profiles. That should happen automatically when using --prof-startup tho...

**Comment by bpasero** [comment]
@jrieken I ran the profile again ensuring that for both I get the output "Standard Startup" and pretty much see the same (also used `--no-cached-data`)

[old-nocache.zip](https://github.com/Microsoft/vscode/files/2410520/old-nocache.zip)
[new-nocache.zip](https://github.com/Microsoft/vscode/files/2410521/new-nocache.zip)

**Comment by bpasero** [comment]
This is on Linux btw.

**Comment by bpasero** [comment]
Also tried with a fresh `user-data-dir` and get this:

![image](https://user-images.githubusercontent.com/900690/45948577-d5872a80-bff8-11e8-80c3-a85c18a0acf2.png)

I wonder if this is another Electron update regression or bootstrap refactoring issue...

**Comment by jrieken** [comment]
What of process is that? renderer, main, exthost?

**Comment by jrieken** [comment]
So, when running locally via `code-cli` its seems that profiling of the renderer start quite late. We cannot start it paused so we tell it to be debuggable and then aggressively try to connect to start profiling. That might have changed now...

**Comment by jrieken** [comment]
Yeah, that's a regression from friday...
