### ISSUE TITLE
Test: debug session refactored

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#59225]
- [x] win @sbatten 
- [x] os x @bpasero 
- [x] linux @sandy081 

Complexity: 3

As part of debt @weinand and me have heavily refactored the lifecycle of a debug session. Due to that have a very simple repository which you can debug (for example smoke test repo or a start extension) and verify:
* You can start / stop / restart debugging and hit a simple breakpoint and the debug toolbar is always in a good state
* You can start multiple debug sessions and the debug toolbar always reflects the focused session. (Easiest to start an additional debug session is adding a new launch configuration which can be a copy of the previous one but with a different name)
* Have a broken launch configuration, verify vscode properly reports the error and that debugging is not left in a broken state
* Be creative with stopping and starting debug session and try to get it into a broken state (usually reflected by the debug toolbar)

**Comment by sbatten** [comment]
Did testing on this today, ran into the same issue as @sandy081 but I will do some more testing tomorrow with the fix before signing off
