### ISSUE TITLE
The context menu is mesbehaving 

### ISSUE THREAD

**Issue by Akumzy** [Microsoft/vscode#59223]
Issue Type: <b>Bug</b>

The context menu is mesbehaving 
immediately I right click it'll click something else

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:11:15.873Z)
OS version: Linux x64 4.15.0-34-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2348M CPU @ 2.30GHz (4 x 1264)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|7.69GB (0.44GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.60
vue-peek|dar|1.0.2
vscode-eslint|dba|1.6.0
gitlens|eam|8.5.6
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.6.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
firebase-snippets|has|0.0.1
vue-snippets|hol|0.1.9
vscode-JS-CSS-HTML-formatter|lon|0.2.3
dotenv|mik|1.0.1
vscode-attrs-sorter|mrm|2.1.0
Go|ms-|0.6.89
vsliveshare|ms-|0.3.709
debugger-for-chrome|msj|4.10.1
vetur|oct|0.12.6
polacode|pnp|0.2.2
live-sass|rit|3.0.0
LiveServer|rit|5.1.1
vscode-icons|rob|7.27.0
vue-vscode-snippets|sdr|1.3.0
code-settings-sync|Sha|3.1.2
vuejspack|she|1.3.2
vsfire|tob|1.3.2
quokka-vscode|Wal|1.0.149
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.9.0
JavaScriptSnippets|xab|1.7.0

(2 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Please provide more information, what context menu, where did you click, which is the something else that is clicked instead?
