### ISSUE TITLE
VSCode extracted from .tar.gz files doesn't work

### ISSUE THREAD

**Issue by YousefSaber** [Microsoft/vscode#59221]
VSCode extracted from the compressed .tar.gz file doesn't work on my linux System ( elementary OS) 

VSCode v1.27
elementary OS v0.4.1 loki 64 bit
![image](https://user-images.githubusercontent.com/33742499/45949458-349a6e80-bffc-11e8-84b7-7b0fea19047f.png)
![image](https://user-images.githubusercontent.com/33742499/45949471-3e23d680-bffc-11e8-9456-5803e38f4842.png)

![image](https://user-images.githubusercontent.com/33742499/45949244-9a3a2b00-bffb-11e8-8359-6b8fb891a977.png)
![image](https://user-images.githubusercontent.com/33742499/45949278-b938bd00-bffb-11e8-9aa3-87535f8d81cd.png)
![image](https://user-images.githubusercontent.com/33742499/45949294-c2c22500-bffb-11e8-9cd2-6c23db8fd071.png)
![image](https://user-images.githubusercontent.com/33742499/45949501-63184980-bffc-11e8-83b4-08350ba05c3a.png)
![image](https://user-images.githubusercontent.com/33742499/45949520-6f9ca200-bffc-11e8-99ae-d22dfae0d78a.png)

for perspective my OS could run Firefox and telegram apps which were extracted from .tar.gz

**Comment by yogeshkotadiya** [comment]
Try to open with terminal
`$ ./code`

**Comment by YousefSaber** [comment]
@yogeshkotadiya didn't work here's the terminal commands I/O

```
joseph@joseph-G31M-ES2L:~/Downloads/VSCode-linux-x64$ ./code 
./code: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
joseph@joseph-G31M-ES2L:~/Downloads/VSCode-linux-x64$ cd .
joseph@joseph-G31M-ES2L:~/Downloads/VSCode-linux-x64$ cd ..
joseph@joseph-G31M-ES2L:~/Downloads$ ./code 
bash: ./code: No such file or directory
joseph@joseph-G31M-ES2L:~/Downloads$
```

**Comment by yogeshkotadiya** [comment]
ok looks like libgconf package is missing, install it using this command
`sudo apt install libgconf2-4`
and try again.

**Comment by YousefSaber** [comment]
@yogeshkotadiya it worked VSCode now works thanks a lot please update this details on your website docs 
https://code.visualstudio.com/docs/setup/linux

![image](https://user-images.githubusercontent.com/33742499/46131582-54b87080-c23c-11e8-9c18-df313bc49aa7.png)
