### ISSUE TITLE
cli: check if a given extension (.vsix file) is (already) installed

### ISSUE THREAD

**Issue by Iniesta8** [Microsoft/vscode#59220]
Hey,

I'm currently working on a shell script to install given extensions (out of a folder with .vsix files) if these aren't already installed. Unfortunatelly the vscode cli doesn't provide an opportunity to check if a given .vsix file is installed. I can only get all installed extensions (--list-extensions (and --show-versions)) and compare with a list of extensions I have in my folder. In this case, all the names of the .vsix files must have the special form _publisher.name-version.vsix_.

Would it be possible to extend the cli?

Thanks in advance.

**Comment by sandy081** [comment]
I do not think this will be implemented in the near future and not many requested for this I am closing this as out of scope. We will get back to this if more requested.

**Comment by sandy081** [comment]
I do not think this feature will be implemented in near future and hence I am closing this as out of scope. We will get back to this if there are more similar requests. Thanks.
