### ISSUE TITLE
Intellisense for C++

### ISSUE THREAD

**Issue by arijeet317** [Microsoft/vscode#59222]
Issue Type: <b>Feature Request</b>

When I load a workspace on VScode the inellisense does not give me suggestion of members defined in  other files in the workspace for C++ . I have used VScode for Angular5 and it was working fine. 

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.15063

**Comment by mjbvz** [comment]
Please install the c++ tools extension or file an issue against them if you already have it installed but it is not working
