### ISSUE TITLE
Icons display in Suggestions

### ISSUE THREAD

**Issue by shashikantdurge** [Microsoft/vscode#59239]
Issue Type: <b>Bug</b>

When I try to lookup the Icons in suggestions. it shows html code. you know what I want to see. please look into it.

I am developing Flutter app using  Dart language.

Thank you

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.87GB (4.36GB free)|
|Process Argv|C:\Users\vasan\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
emojisense|bie|0.4.1
dart-code|Dar|2.18.0
flutter|Dar|2.18.0
gitlens|eam|8.5.6
tslint|eg2|1.0.39
plantuml|jeb|2.9.0
vscode-todo-highlight|way|1.0.4

</details>

**Comment by Tyriar** [comment]
Can you provide a screenshot of the issue?

**Comment by shashikantdurge** [comment]
![screenshot 34](https://user-images.githubusercontent.com/20161204/45961730-e2c60880-c03c-11e8-92ed-91c16b75c2f5.png)

**Comment by Tyriar** [comment]
I think you should report this again the dart-code extension as they're using an unsupported icon format.
