### ISSUE TITLE
vscode crash and break my file.

### ISSUE THREAD

**Issue by szthanatos** [microsoft/vscode#59233]
the vscode crash down and recover automatically, then I find my file opened before is broken. it say '此文件是二进制文件或使用了不支持的文本编码，无法在编辑器中显示。' now. In English maybe like 'This file is a binary file or uses an unsupported text encoding and cannot be displayed in the editor.' 

here is my [broken file](https://1drv.ms/u/s!Ah_ERAs2VkpJgYMJ9n8ymG623z_b1A) , there should be only Chinese and English characters in it. does anyone can fix it... :(

**Comment by bpasero** [comment]
That seems not encoding but hot-exit related.
