### ISSUE TITLE
Integrated Cmder terminal does not save command history

### ISSUE THREAD

**Issue by ford04** [Microsoft/vscode#59230]
- VSCode Version: 1.27.2 Portable
- OS Version: Windows 10 1803

Steps to Reproduce:

1. Cmder is integrated in VS Code by doing steps proposed [here](https://github.com/Microsoft/vscode/issues/12006) 
```
    "terminal.external.windowsExec": "cmder",
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",
    "terminal.integrated.shellArgs.windows": [
        "/K",
        "%CMDER_ROOT%\\vscode.bat"
    ],
```
2. Start cmder externally with `cmder.exe`. Execute `echo test`. Now the command is still listed as first entry in command history when (re)starting a)  `cmder.exe`  b) VS Code integrated Cmder and pressing up arrow.
3. In VS Code integrated Cmder execute command `echo test2`. The command will be in the history of current opened shell. But when I open a) Cmder externally or b) close and restart the integrated terminal afterwards, the command does not appear there and gone completely.

Does anyone experience similar issues out there? What could be a solution to persist command history across cmder usage as external and integrated terminal?

Greetings

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/43557
