### ISSUE TITLE
Clone in VS Code from AzureDevOps doesnt work in Ubuntu 18.04

### ISSUE THREAD

**Issue by azureDaveOps** [Microsoft/vscode#59235]
- VSCode Version: 1.27.2
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Use Azure Dev Ops service to create an Azure Repo
2. Click "Clone", then click "Clone in VS Code"
3. Firefox attempts to open the url: "vscode://vscode.git/clone?url=BLAH" and hits this error:
"The address wasn't understood"

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Linux URL handling was only implemented this month. It will be available next major release.
