### ISSUE TITLE
extension manager does not show the ext by url

### ISSUE THREAD

**Issue by fthiagogv** [Microsoft/vscode#5924]
- VSCode Version: 1.1.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Ctrl+P
2. ext install theme-material-ocean-next-plus

This will show all extensions similar, but not the extension that I wanna install.

Should be able to install executing the command, instead search all time.

**Comment by joaomoreno** [comment]
Stable will not roll out with those changes in May. Experience is still being polished.
