### ISSUE TITLE
Settings search for "menu" doesn't return "window.titleBarStyle"

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#59242]
i expected to find the `window.titleBarStyle` setting to turn on the HTML menus on Windows but searching for "menu" does not show the right results.

![image](https://user-images.githubusercontent.com/1487073/45960312-f7c57c00-bfe9-11e8-9635-98243b588797.png)

**Comment by rzhao271** [comment]
Just tested it on the latest Insiders and it seems to be fixed now. Closing this issue.
