### ISSUE TITLE
Test Installing or Enabling an extension with URI handler

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#59244]
Ref #57636

- [x] any @ramya-rao-a 
- [x] any @bpasero 

Complexity: 3

<details>
  <summary>Sample Extension</summary>

- Create an extension that contributes url (protocol) handler 

```ts
vscode.window.registerUriHandler(<vscode.UriHandler>{
        handleUri(uri: vscode.Uri) {
            vscode.window.showInformationMessage(uri.path);
        }
    });
```

- Add `onUri` activation event in `package.json`

</details>

### URI Format

Uris directed towards extension vscode.git, for example, all share the following prefix:

```{scheme}://vscode.git```

{scheme}://vscode.git

For example, for VS Code Insiders, these are valid Uris which will be handled by the git extension's protocol handler:

```
vscode-insiders://vscode.git
vscode-insiders://vscode.git/
vscode-insiders://vscode.git/status
vscode-insiders://vscode.git/clone?url=foobar
```

### How to Open

Windows: type explorer URI in a command prompt
macOS: type open URI in a shell
Linux: type xdg-open URI in a shell

You can also open a URL from the command line with --open-url URL

### Verify:

- Opening an URL handled by an extension
  - Installs the extension if not installed
  - Enables the extension if disabled
- After extension is installed/enabled you are asked to reload the window. 
- After reload, extension will be activated and URL handler is called immediately.

**Comment by bpasero** [comment]
Since I did not want to publish a test extension to the market place I decided to test the flow with a disabled git extension.
