### ISSUE TITLE
Test: command to navigate to last edit location

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#59243]
Ref #19120

Complexity: 2

- [x] anyOS @ramya-rao-a 
- [x] anyOS @misolori 

There is now a new command `workbench.action.navigateToLastEditLocation` to navigate to the last location in a file that was edited (shortcut: `Cmd+K Cmd+Q`). Verify this works as advertised.

**Comment by ramya-rao-a** [comment]
I expected the command to be usable multiple times i.e Use it twice to go to the edit before the last edit. Like the `Go Back` command. But that might just be me.

**Comment by bpasero** [comment]
No, there is no history for edit locations (there is another feature request open for that).
