### ISSUE TITLE
Clip ctrl+up/down cursor to bottom/top of moving window

### ISSUE THREAD

**Issue by dwilliamson** [Microsoft/vscode#59247]
Issue Type: <b>Feature Request</b>

One experience I miss from Visual Studio is the behaviour of ctrl+up/down for moving the view window in a document while keeping the cursor static.

In VSCode it remains truly static. If I ctrl+down over a few pages, let go and then move the cursor, the window pops right back to where the cursor was left behind.

In Visual Studio the cursor remains static until it reaches the limit of the current window, after which it's dragged up or down with the window. You can then resume normal cursor movement from your current position.

It would be great to have a toggle for this kind of behaviour.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

**Comment by alexandrudima** [comment]
You can use the `editorScroll` command in your `keybindings.json`:

e.g.

```
{
	"key": "ctrl+up",
	"when": "editorTextFocus",
	"command": "editorScroll",
	"args": {
		"to": "up", // 'up', 'down'
		"by": "line", // 'line', 'wrappedLine', 'page', 'halfPage'
		"value": 1, // number of units to move
		"revealCursor": true
	}
}
```

**Comment by dwilliamson** [comment]
Oh my word, this is beautiful.
