### ISSUE TITLE
Cant fold or un-fold a function (JS)

### ISSUE THREAD

**Issue by vaderj** [microsoft/vscode#59257]
Issue Type: <b>Bug</b>

1.) Have a deadline
2.) Have unfinished code

Other than that, I dont know why.  I can switch to another JS tab and I can collapse and expand as expected, but randomly VSCode likes to just deny that feature.   I have a screenshot but apparently that was determined to be useful for reporting a bug

Cant unfold/expand:
![image](https://user-images.githubusercontent.com/6461412/45973613-43564500-c03f-11e8-81b1-d725b4d53dda.png)

Can't fold/collapse:
![image](https://user-images.githubusercontent.com/6461412/45973626-4c471680-c03f-11e8-8d75-a4d7eea4b5f2.png)

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2694)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.67GB (1.39GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.8.0
csharp|ms-|1.16.1

</details>

**Comment by aeschli** [comment]
@vaderj Can you paste the a code example where this reproduces?

When you have syntax errors its quite possible that no folding regions can be created.

**Comment by vaderj** [comment]
The first screenshot shows this function folded and unable to be unfolded: 
`
function onlyUnique(value, index, self) 
{ 
	return self.indexOf(value) === index;
}
`

**Comment by aeschli** [comment]
If you can paste a full example so I can reproduce this in my machine would be helpful.

Do the fold/unfold commands still work for this area (`Ctrl+ Shift + [`, `Ctrl+ Shift + ]`) ?

**Comment by vaderj** [comment]
> If you can paste a full example so I can reproduce this in my machine would be helpful.
> 
> Do the fold/unfold commands still work for this area (`Ctrl+ Shift + [`, `Ctrl+ Shift + ]`) ?

The issue is inconsistent ... it doesn't appear to be reacting to my code specifically.  After restarting, it clears up for a time.  I have previously tried closing and reopening the tab, but that had no apparent effect on the behavior.

So a minute a go I had two VS Code windows open, both with 2 tabs open.  In one instance, I opened 4 existing files, and at that point, those four files after being open for a few minutes developed the behavior.  Right after I opened the files, each tab one was successfully able to fold and unfold functions.  After checking all the tabs in both VS Code instances, the behavior developed on the 4 newly opened tabs.

**Comment by vaderj** [comment]
> c

I just checked again: The same "newly opened" tabs still exhibit the behavior (do not allow folding and unfolding) and I noted two things:


1.) I was able to copy one of the folded functions and it copied the entire text to the clipboard (instead of just copying the visible text)


2.) Inserting the cursor at the end of the last visible line and inserting a CR creates a new line but does not unfold the folded code beneath

**Comment by paule96** [comment]
I have the same Issue. In some files I can fold in another not. 

I can solve this to save all files as "LF" and not as "CRLF". This worked for me. Maybe this help you too :)

**Comment by mjbvz** [comment]
Closing this issue as out of date.

@vaderj If you still see this in the most recent VS Code builds, please share some example code and steps to reproduce it
