### ISSUE TITLE
VSCode should provide an API to allow extensions to launch a debug adapter

### ISSUE THREAD

**Issue by gregg-miskelly** [Microsoft/vscode#5925]
In order to enable the C# extension to be able to launch the debugger against unit tests, we need to allow the many body of the C# extension to be able to start the debugger, and we need some way to tell the debugger what to do (in our case attach to a specific process).

To solve this, we would like there to be an API exposed to extensions which allows launching the debugger with a specified set of launch option json. Something like:

export function launchDebugger(launchOptions :any) : Thenable\<boolean\>

**Comment by jrieken** [comment]
@isidorn Isn't there a command for this? Then `executeCommand` should do it

**Comment by isidorn** [comment]
Dup of #4615
