### ISSUE TITLE
add containing folder to workspace in right click for open editors in explorer bar

### ISSUE THREAD

**Issue by msftrncs** [Microsoft/vscode#59254]
Issue Type: <b>Feature Request</b>

Add a 'Add Containing Folder to Workspace' in the context menu for open editors in the Explorer bar, so I can quickly get to the rest of the items in a folder a open file is contained in.   Of course, this is only needed if the containing folder is not already in the workspace somewhere.

I might only start with a file, and then decide that it would be useful to have its folder open as a workspace item.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/52713
And then an extension could do it
