### ISSUE TITLE
Intellisense not recognizing "this" within JS Prototype

### ISSUE THREAD

**Issue by ReiMcCl** [Microsoft/vscode#59250]
- VSCode Version: 1.27.2
- OS Version: Windows 10 Pro 64-bit

Steps to Reproduce:

1. Create a new Javascript file with the below defined:
```
function MyConstructor () {
    this.a = 5;
}

MyConstructor.prototype = {
    /**
     * @this MyConstructor
     */
    send: function () {
        this.a = 0;
    }
};
```

2. Hover over "this" within the prototype or attempt to assign to a, intellisense is recognizing the object being created rather than the constructor.

![image](https://user-images.githubusercontent.com/12534799/45965086-71c42800-c01f-11e8-9744-eefdf44a50f6.png)
![image](https://user-images.githubusercontent.com/12534799/45965092-75f04580-c01f-11e8-97fe-17812b790e0d.png)

Working:
![image](https://user-images.githubusercontent.com/12534799/45965229-db443680-c01f-11e8-9a10-97dff175a8e2.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This seems to work in the latest VS Code insiders build:

<img width="1017" alt="screen shot 2018-09-24 at 11 39 21 am" src="https://user-images.githubusercontent.com/12821956/45971691-863bfc80-bfee-11e8-90b4-911aace41c5e.png">
