### ISSUE TITLE
Terminal's scrollbar does not move with keyboard input

### ISSUE THREAD

**Issue by OnlineCop** [Microsoft/vscode#59259]
Issue Type: <b>Bug</b>

When there is enough text in the terminal window for the scrollbar to appear, Ctrl+PgUp and Ctrl+PgDown will move the view properly, but the scrollbar itself does not move.

If the mouse wheel is used to scroll, both the view and the scrollbar move up and down properly. If the scrollbar is moved to the top of the text and the user types input into the terminal, the scrollbar remains at the top of the terminal window, but the view returns to the bottom as expected (so the text can be seen as it is typed).

The scrollbar _will_ move to the bottom of the view if the user hits Enter to create a new line.

May be related to #58532 and #45134

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:11:15.873Z)
OS version: Linux x64 4.4.0-112-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (32 x 1394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|62.81GB (1.16GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
sort-lines|Tyr|1.7.0
code-gnu-global|aus|0.2.2
CppSnippets|har|0.0.13
cmake-tools-helper|mad|0.2.1
mlextension|Mag|0.9.5
cpptools|ms-|0.18.1
remote-vscode|raf|1.1.0
cmake|twx|0.0.17
cmake-tools|vec|1.1.2
clang-format|xav|1.6.2

</details>

**Comment by Tyriar** [comment]
This is fixed in master, coming in 1.28
