### ISSUE TITLE
Blurred texts on external screen in macOS 10.14

### ISSUE THREAD

**Issue by kwrush** [Microsoft/vscode#59268]
- VSCode Version: 1.27
- OS Version: macOS 10.14 Mojave

Does this issue occur when all extensions are disabled?: Yes

After I updated my macOS to 10.14, texts are blurred on external display. It's not that obvious from the screenshot but it was much sharper in 10.13.

![jietu20180924-225852](https://user-images.githubusercontent.com/8037780/45979052-207f5d00-c04e-11e8-992e-636701ca50f1.jpg)

**Comment by cdnil** [comment]
duplicate of https://github.com/Microsoft/vscode/issues/51132

try to execute this command in terminal and restart:
`defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO`
