### ISSUE TITLE
macOS: switch dark/light theme when system theme changes

### ISSUE THREAD

**Issue by sergeysova** [microsoft/vscode#59262]
What about add function to set light and dark themes and switch them on system theme changes?

Like in IINA

![image](https://user-images.githubusercontent.com/5620073/45974717-d5b01600-c04a-11e8-80db-242d81d42421.png)

When system theme changes, then changes theme in app.

![image](https://user-images.githubusercontent.com/5620073/45974737-ec566d00-c04a-11e8-8d04-200a759bcdc7.png)

**Comment by sergeysova** [comment]
Reference: https://github.com/electron/electron/issues/13387

**Comment by LinusU** [comment]
For anyone that doesn't want to wait, I made a little extension that does this for you:

https://marketplace.visualstudio.com/items?itemName=LinusU.auto-dark-mode

You can set the dark and light mode in the settings:

<img width="391" alt="screenshot 2018-11-21 at 12 59 28" src="https://user-images.githubusercontent.com/189580/48842851-4ba3d580-ed8d-11e8-8aaf-1c85347c4ca8.png">

Hope this helps someone!

**Comment by LinusU** [comment]
@Lapsusone I think that the only thing that was in the last release was that the window borders and system dialogues will now follow the system dark theme settings. It still doesn't have a mechanism for automatically switching the editor theme...

**Comment by samplenull** [comment]
@LinusU, thanks for extension, it works!

**Comment by sergeysova** [comment]
@LinusU So thank you!

**Comment by sergeysova** [comment]
@bpasero what about add built in support of that feature?

**Comment by misolori** [comment]
I would also like this, but I can see this getting complicated with themes that provide multiple light/dark themes. Here is what GitHub Desktop does this:

<img width="472" alt="image" src="https://user-images.githubusercontent.com/35271042/54146068-6ce80a80-43ec-11e9-916f-e86cf14990f9.png">

**Comment by jerguslejko** [comment]
I'd love to see this built-in. I've been using @LinusU's extension (https://marketplace.visualstudio.com/itemdetails?itemName=LinusU.auto-dark-mode) which works well most of the time but sometimes does not pick up the change.

Anyhow, I think it makes sense for this to be in the core.

**Comment by rapgru** [comment]
As I wasn't completely satisfied with @LinusU's extension, there's now another extension for this task:

[ThemeSwitch on VS Code Marketplace](https://marketplace.visualstudio.com/items?itemName=rapgru.themeswitch)

It is **customizable** and can therefore switch between more than 2 themes. You can choose any time of day and combine that time with the theme you prefer at that time.
