### ISSUE TITLE
visual studio code open https://github.com/OldFisher/lua-api-pp.git/ syntax highlight invalid

### ISSUE THREAD

**Issue by wangyongxina** [Microsoft/vscode#5926]
- VSCode Version: 1.0.0
- OS Version:windows 7

Steps to Reproduce:

1. svn check out https://github.com/OldFisher/lua-api-pp.git/
2. use vscode open one of hxx file

vscode will show '}'in red color

**Comment by aeschli** [comment]
That go fixed in the latest with the update of the C++ grammar.
