### ISSUE TITLE
Breakpoint not shown in gutter on active line

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#59261]
Issue Type: <b>Bug</b>

1. Set a breakpoint in a js file
1. Start debugging and hit the breakpoint

**Bug**
Notice that the breakpoint is not shown in the left gutter:

![screen shot 2018-09-24 at 11 55 56 am](https://user-images.githubusercontent.com/12821956/45972607-0a8f7f00-bff1-11e8-9123-c0acbbd18ede.png)

Stepping to the next line, the breakpoint becomes visible again  

VS Code version: Code - Insiders 1.28.0-insider (2558a72d6902015b142ef45c57b664ce1f09e03f, 2018-09-21T05:12:46.853Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_11406048|
|Screen Reader|no|
|VM|22%|

</details>

**Comment by isidorn** [comment]
Can not repro. What are you doing differently than me?
Can you repro in a simple javascript file?
Is the breakpoint red before you hit it?
If you can only repro in a specific situation please give me steps 

![screen shot 2018-09-25 at 17 50 30](https://user-images.githubusercontent.com/1926584/46026383-82da6b00-c0eb-11e8-91b5-ac8460b6f4fa.png)

**Comment by mjbvz** [comment]
Ok I'm not able to repo anymore either. Will let you know if I hit this again.
