### ISSUE TITLE
Test find in terminal improvements

### ISSUE THREAD

**Issue by alexr00** [Microsoft/vscode#59267]
Ref #58826 

Complexity: 2

- [x] Mac @isidorn 
- [x] linux @chrmarti  
- [x] Windows @rebornix 

Find widget in terminal should now find across wrapped lines(note that it still only finds the first occurrence in each line), find using regex, find whole word, and find case sensitive.

**Comment by chrmarti** [comment]
@alexr00 For me #59321 needs to be fixed before I can continue testing. Maybe prioritize that for today, so we can do some more testing tomorrow.

**Comment by alexr00** [comment]
@chrmarti, it's fixed already so you should be good for testing tomorrow already. It looks like the latest update of xterm.js had some regressions. @Tyriar reverted the update in 1e058b76ea

**Comment by alexr00** [comment]
Closed the wrong issue.

**Comment by rebornix** [comment]
Tested https://github.com/Microsoft/vscode/issues/30874 and since we are using js regex search in main thread, it still crashes VSCode. We share the same root cause here.
