### ISSUE TITLE
Visual Studio Code won't launch!

### ISSUE THREAD

**Issue by treelevitt** [Microsoft/vscode#59269]
- VSCode Version: 1.27
- OS Version: 10.13.4

Steps to Reproduce:

1. Downloaded VSCode-darwin-stable.zip to Downloads folder
2. Unzipped to same directory
3. Click-and-dragged VSC app to Applications
4. Double-clicked on VSC to launch
5. VSC icon shows up on dock, bounces a few times, then disappears

Does this issue occur when all extensions are disabled?: Not sure

My feeling is that this app was never properly installed. 

I checked on Console but couldn't even find any reports on VSC, which may sound very strange.

 Any suggestions/advice would be highly appreciated!

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by treelevitt** [comment]
Hello,

I dragged the Electron file into the terminal and ended up with this message:

[main 4:53:25 PM] Startup error: ,Error: EACCES: permission denied, mkdir '/Users/TeresaLeong 1/.vscode'

**Comment by treelevitt** [comment]
Even when I try to open VSC from terminal, I get this message:

Teresas-MacBook-Pro:Applications TeresaLeong$ open -a visual studio code
The files /Applications/studio and /Applications/code do not exist.

But the app is clearly there and installed on my computer!

**Comment by treelevitt** [comment]
Sorry I closed the issue by accident yesterday. I'm still unable to open the app.

**Comment by Eznoka** [comment]
Hi, same issue here (on fedora 29 beta).

/usr/bin/code : ligne 35 :  5840 Erreur de segmentation  (core dumped)ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by treelevitt** [comment]
I waited for the newest release to download and tried again. Now it works on my computer. Thanks!

**Comment by n8agrin** [comment]
I occasionally have the same problem.

@bpasero here's what I see on the console

```
> code . --verbose
[main 4:14:42 PM] Sending env to running instance...
[main 4:14:42 PM] Sent env to running instance. Terminating...
[main 4:14:42 PM] Lifecycle#kill()
```
