### ISSUE TITLE
Test DocumentCommentProvider edit and delete

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#59278]
https://github.com/Microsoft/vscode/issues/58078

Complexity: 4

- [x] Mac @chrmarti 
- [x] linux @sandy081 
- [x] Windows @aeschli   

`DocumentCommentProviders` now expose a way to edit and delete comments.  When the provider has `editComment` or `deleteComment` methods and a comment within a document has the `canEdit` or `canDelete` flag set, an action bar should appear on hover or focus of the comment.  Things to test:
- Is documentation clear?
- The action bar for comments shows up at appropriate times
- UI for edit and delete behave as expected
- throwing within `editComment` and `deleteComment` is safely handled by VSCode

**Comment by sandy081** [comment]
@RMacfarlane Is there a sample that can be followed? Otherwise it is hard to test.

**Comment by chrmarti** [comment]
@sandy081 I implemented a `DocumentCommentProvider` from the proposed API.

**Comment by RMacfarlane** [comment]
@sandy081 I haven't made a sample yet since this is still proposed API, but here's a comment provider that provides a comment on the first line of any document

```ts
export function activate(context: vscode.ExtensionContext) {
    const _onDidChangeDocumentCommentThreads = new vscode.EventEmitter<vscode.CommentThreadChangedEvent>();

    vscode.workspace.registerDocumentCommentProvider({
        onDidChangeCommentThreads: _onDidChangeDocumentCommentThreads.event,
        provideDocumentComments: async (document: vscode.TextDocument, token: vscode.CancellationToken): Promise<vscode.CommentInfo> => {
            return {
                threads: [{
                    threadId: '1',
                    resource: document.uri,
                    range: new vscode.Range(new vscode.Position(0, 0), new vscode.Position(0, 0)),
                    comments: [{
                        commentId: '1',
                        body: new vscode.MarkdownString('hello world'),
                        userName: 'me',
                        gravatar: ''
                    }]
                }],
                commentingRanges: []
            }
        },
        createNewCommentThread: async (document: vscode.TextDocument, range: vscode.Range, text: string) => {
            throw new Error('Not implemented');
        },
        replyToCommentThread: async (document: vscode.TextDocument, range: vscode.Range, thread: vscode.CommentThread, text: string) => {
            throw new Error('Not implemented');
        }
    });
}
```
