### ISSUE TITLE
Markdown doesn't mark emphasis correctly when it ends with space

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#59275]
This causes a jarring typing experience:

![md](https://user-images.githubusercontent.com/4033249/45982581-235a5d80-c00e-11e8-8243-b97cc69d31b2.gif)

**Comment by mjbvz** [comment]
Yes this is not great but it does match what the preview will render:

![sep-24-2018 15-30-49](https://user-images.githubusercontent.com/12821956/45982758-ddea6000-c00e-11e8-885b-92fbe7d37774.gif)

Not sure we can reasonable avoid the flashing while typing without breaking the tm-grammar for some cases

**Comment by octref** [comment]
What are the cases it'll break? When typing `**` in 90% of the cases there would be spaces at the end of the inner string. This is such a common case that I think we should fix.
