### ISSUE TITLE
searching for files using Ctrl+P is really really slow

### ISSUE THREAD

**Issue by alvarorahul** [Microsoft/vscode#5928]
- VSCode Version: 1.1.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Open a folder with a large number of files. My repo folder which I opened has about 34000 files within 5000 folders.
2. Use Ctrl+P to find a file.

EXPECTED: the file is found quickly.
ACTUAL: it takes a really long time to find a file.

**Comment by bpasero** [comment]
#55
