### ISSUE TITLE
autopep8 formatting no working

### ISSUE THREAD

**Issue by HathawayZhu** [Microsoft/vscode#59285]
The file is not formatting automatically when I save the file. I checked with trouble-shooting for formatting, I think I'm right in each step.

- VSCode Version: 1.27.2
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1. install Python extension for Visual Studio Code
2. install autopep8, pep8, flake8

Does this issue occur when all extensions are disabled?: Yes

Here is my setting.json:
{
    "python.pythonPath": "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3",
    "python.linting.enabled": true,
    "python.linting.flake8Enabled": true,
    "python.linting.flake8Path": "/Library/Frameworks/Python.framework/Versions/3.6/bin/flake8",
    "python.linting.flake8Args": [
        "--ignore=E221,E223"
    ],
    "python.linting.pep8Enabled": true,
    "python.linting.pep8Path": "/Library/Frameworks/Python.framework/Versions/3.6/bin/pep8",
    "python.formatting.provider": "autopep8",
    "python.formatting.autopep8Path": "/Library/Frameworks/Python.framework/Versions/3.6/bin/autopep8",
    "editor.formatOnSave": true,
    "[python]": {
        "editor.formatOnSave": true
    },
    "editor.fontSize": 14,
    "editor.minimap.enabled": false,
    "workbench.colorTheme": "Monokai",
    "workbench.startupEditor": "newUntitledFile",
    "workbench.iconTheme": "file-icons",
    "terminal.integrated.shell.osx": "/bin/bash",
    "files.trimTrailingWhitespace": true,
}

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
