### ISSUE TITLE
Terminal resolves symlink path

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#59291]
- Open a folder under a symlinked path. After #18837 vscode doesn't resolve the symlinked path anymore
- Open a terminal
- The terminal opens with a cwd which is the resolved symlink path

This is mentioned in #18837 and https://github.com/Microsoft/node-pty/pull/156 already addressed this but was closed.

**Comment by thecp** [comment]
That's pretty annoying. Even with explicitely setting `terminal.integrated.cwd` to the symlinked path, it gets resolved

**Comment by mkogan1** [comment]
it's possible to mitigate this on linux using `mount --bind` instead of `ln -s`
