### ISSUE TITLE
Refresh button doesn't update left side file explorer

### ISSUE THREAD

**Issue by mgdevstack** [Microsoft/vscode#59290]
Issue Type: <b>Bug</b>

Many times it is been observed that left side file explorer doesn't reflect new files added when this new file is fetched from git. Vscode editor requires restart to reflect new files in explorer.

Issue Scenario-1:
1. Git fetch causes either updating same file or adding new file in folder.
2. After clicking refresh button from vscode side explorer, new file is not found or sometime new content in existing file is missing.
3. Once vscode is restarted all files are shown as expected.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:04:11.329Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.20.0
LogFileHighlighter|emi|2.4.1
beautify|Hoo|1.4.4
vscode-github|Kni|0.30.0
vscode-elixir|mjm|1.1.0
mssql|ms-|1.4.0
cpptools|ms-|0.18.1
Go|ms-|0.6.89
vscode-ginkgo|ons|0.0.1
vscode-docker|Pet|0.3.0
pretty-exception|piz|0.0.1
vscode-icons|rob|7.27.0
sourcegraph|sou|1.0.12
markdown-all-in-one|yzh|1.6.0
vscode-proto3|zxh|0.2.1

</details>

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/28432
