### ISSUE TITLE
Snippets: error parsing braces in nested placeholders

### ISSUE THREAD

**Issue by cipchk** [Microsoft/vscode#59292]
## Version

Version: 1.27.2 (system setup)
Commit: f46c4c469d6e6d8c46f268d1553c5dc4b475840f
Date: 2018-09-12T16:17:45.060Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

## Reproduce

I want to render the following code, where `req` is a nested placeholder.

```
<st [req]="{params: params}"></st>
```

Different ways to get different results, But not correct.

> Unified template style
> ```
> "html st": {
>     "prefix": "na-st",
>     "body": "<st${1: [req]=\"\\{params: params\\}\"}></st>",
> }
>

**Type 1**

```
<st${1: [req]=\"{params: params}\"}></st>
```

render

```
<st [req]="{params: params"}></st>
```

**Type 2**

```
<st${1: [req]=\"\\{params: params\\}\"}></st>
```

render

```
<st [req]="\{params: params}"></st>
```

Does this issue occur when all extensions are disabled?: No

**Comment by jrieken** [comment]
You don't need to escape the opening curly. This will work: `"<st${1: [req]=\"{params: params\\}\"}></st>"`
