### ISSUE TITLE
How to increase maxNumberOfProblems being displayed in Python?

### ISSUE THREAD

**Issue by NagarjunPrasad1** [Microsoft/vscode#59297]
I would like to know how I can increase the the number of problems being displayed. I tried increasing the same by setting the `python.linting.maxNumberOfProblems` to a high number but I saw that the upper limit is 1001. The number works fine for smaller files but in very large and non linted files 1001 problems fills up very fast so if you are editing something at the bottom of the file We can't see any linting errors at all.

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
