### ISSUE TITLE
Updating Visual Studio Code uninstalled it

### ISSUE THREAD

**Issue by phistuck** [Microsoft/vscode#59296]
- VSCode Version: I think it was the original August update. So updating 1.26.1 to 1.27.0?
- OS Version: Windows 10

Steps to Reproduce:
1. I think I switched to a user-level installation because Visual Studio Code recommended, some weeks before the update.
2. August update came along, so I clicked on "Restart to Update...".

Expected -
An up to date Visual Studio Code.

Actual -
I guess there was some update installation issue. Visual Studio Code was uninstalled from the system. I had to download it manually and install it again.

Unless you keep old installation/update/uninstallation logs somewhere, I am not sure I am able to provide more details.

**Comment by joaomoreno** [comment]
Did you get an error popup?

**Comment by phistuck** [comment]
I believe so, I think it said it had an issue during the update and that it is uninstalling now. Not sure exactly what the message was, sorry, I was in a hurry and could not be bothered by it at that moment, but I thought it is significant enough to report it after the fact, even if I do not have enough details.

**Comment by joaomoreno** [comment]
Got it. Closing as a duplicate of #47841.
