### ISSUE TITLE
Unable to open more than 2 editors

### ISSUE THREAD

**Issue by Ankur1014** [Microsoft/vscode#59295]
Issue Type: <b>Bug</b>

When I click on multiple files in my workspace, my editor only shows 2 of them atmost.

When I click one more file, the previous one gets closed or hidden

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 3492)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.90GB (41.61GB free)|
|Process Argv|C:\Users\abose\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.18.1

</details>

**Comment by bpasero** [comment]
Follow our docs to resolve this: https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode
