### ISSUE TITLE
target enum should include es2015

### ISSUE THREAD

**Issue by jdalton** [Microsoft/vscode#593]
Currently the "target" [enum field](https://github.com/Microsoft/vscode/blob/8883fcd03b7afd2eba21ea845bdd2dfbaf3d4c38/src/vs/languages/json/common/jsonSchemaService.ts#L1536) has
```js
 ['ES3', 'ES5', 'ES6', 'es3', 'es5', 'es6']
```

It should also have `'es2015'` and `'ES2015'`.

**Comment by alexeagle** [comment]
This is further broken because TS renames `es6` to `es2015` in `tsc install`:

```
$ ./node_modules/.bin/tsc --version
message TS6029: Version 1.7.5
$ ./node_modules/.bin/tsc --init --target es6 --experimentalDecorators --emitDecoratorMetadata
message TS6071: Successfully created a tsconfig.json file.
$ code .
```
VSCode now shows an error in `tsconfig.json` at `"target": "es2015"` and cannot compile stuff (acts like there is no tsconfig.json at all, eg, `cannot compile modules unless the --module flag is provided`)

**Comment by egamma** [comment]
The `target` enum field now includes `es2015`. We use the schema from http://json.schemastore.org/tsconfig
