### ISSUE TITLE
Support trace record-until-full to stop tracing after window has loaded

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#59307]
re  #59234

* run with `--trace-options record-until-full --trace`
* the trace still stops when windows show or after a timeout

**Comment by bpasero** [comment]
@jrieken what would you expect to happen when using `record-until-full` (which is the default btw)? To stop after a certain size of the trace has been reached?

**Comment by jrieken** [comment]
> To stop after a certain size of the trace has been reached?

Yes, that's what it does. It has an internal buffer and it will record until that buffer is full, it won't stop before that (just like the performance tab does)

**Comment by bpasero** [comment]
@jrieken unfortunately I see no API to get an event when the trace recording is "full" so I would not know when to stop the recording and save to disk. Looks like this maybe not be supported from Electron, I would have to follow up with Electron.

**Comment by bpasero** [comment]
@jrieken yeah I did that and I got back numbers that do not correlate to my understanding of "100% means full". The first one was going a little bit above 1 and the second not even close to 100, just stopped somewhere at one point.
