### ISSUE TITLE
trace options put files into unfriendly location

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#59302]
re #59234

* run with `--trace`
* expect a trace file to be placed into my home folder or the current dir -> nothing
* the log shows `/var/folders/jh/nmq5w60n2vn_491r573nf0fr0000gn/T/.com.microsoft.VSCodeInsiders.uAqpkW` which is very unfriendly because its cryptic and hidden
* if we want user to actually upload those files we should place them somewhere nice

**Comment by bpasero** [comment]
@jrieken I actually find the fact that we put stuff into the home folder very questionable, I always see files there that I forget to clean up and imho the root of the home dir should not be something where temporary files are added. I think the location is fine (tmp dir) given that this data should be cleaned up eventually and not be something left on disk.

**Comment by jrieken** [comment]
> I think the location is fine (tmp dir) given that this data should be cleaned up eventually and not be something left on disk.

Well the point is that we ask users to run that command and share the data with us. So, we shouldn't make it hard for them but easy. Creating hidden files in a temp folder is hard.

**Comment by bpasero** [comment]
Changed location and also showing a dialog now:

![image](https://user-images.githubusercontent.com/900690/46074630-6dffe500-c188-11e8-887e-3add8f3ca7a4.png)

**Comment by jrieken** [comment]
I like. Bonus points for `.txt` so that it can be uploaded to GH without renaming
