### ISSUE TITLE
Could the QuickFix Widget look as cool as the IntelliSense autocompletion dropdown?

### ISSUE THREAD

**Issue by Zundrium** [Microsoft/vscode#59300]
It maybe due to some technical limitations, but I wonder if the Quick Fix widget - as bland as it is - could get a face-lift. It's not the best for dark skins, and it might as well use the same keyboard shortcuts as the IntelliSense autocompletion dropdown. I tried to find the HTML view of `editor.action.quickfix` but I couldn't find it.

Any help and/or info appreciated :)

**Comment by bpasero** [comment]
@Zundrium can you show a screenshot or cast what you mean?

**Comment by Zundrium** [comment]
@bpasero Sorry if the words weren't enough. Maybe I used the incorrect terms? Anyway here are the screens:

Widget dropdown (`CTRL` + `.`) to get quickfixes provided by OmniSharp:
![code_2018-09-26_10-35-40](https://user-images.githubusercontent.com/4927792/46067901-2f622e80-c178-11e8-818c-7dfcde4a12b8.png)

And the more complete dropdown used for generic autocompletion:
![code_2018-09-26_10-36-02](https://user-images.githubusercontent.com/4927792/46067952-4d2f9380-c178-11e8-9cc9-9100d8655314.png)

Hopefully this is enough to understand what I mean :)

**Comment by bpasero** [comment]
@Zundrium try with this setting:

`"window.titleBarStyle": "custom"`

**Comment by Zundrium** [comment]
Sorry for my late response, but this works perfectly @bpasero ! I hope this will be used by default some day :)
