### ISSUE TITLE
Open Workspace button in .code-workspace files

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#59305]
It would be great if we showed a button to Open Workspace floating in .code-workspace files.
This will help the users easily open the workspace if they accidently opened a .code-workspace file.
You should just use the [`FloatingClickWidget`](https://github.com/Microsoft/vscode/blob/7a629db3521b6af5dd9c3f15ba7b8abf5a48591e/src/vs/workbench/parts/preferences/browser/preferencesWidgets.ts#L708)
Here's an example how I do this for launch.json [here](https://github.com/Microsoft/vscode/blob/7a629db3521b6af5dd9c3f15ba7b8abf5a48591e/src/vs/workbench/parts/debug/electron-browser/debugEditorContribution.ts#L521)

**Comment by bpasero** [comment]
Needs https://github.com/Microsoft/vscode/issues/59308

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/46209047-f1f2d200-c32c-11e8-975d-f79dfbff93ed.png)

**Comment by isidorn** [comment]
Fancyyyy
