### ISSUE TITLE
case senstive search

### ISSUE THREAD

**Issue by ajaykrishnalla** [Microsoft/vscode#59301]
Issue Type: <b>Bug</b>

while i am searching for something ,it should be case sensitive but it is not

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz (4 x 3293)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.89GB (1.19GB free)|
|Process Argv|C:\Users\Ajaypc\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.6.0
tslint|eg2|1.0.39
php-debug|fel|1.12.6
php-intellisense|fel|2.3.5
php-pack|fel|1.0.2
python|ms-|2018.8.0
sublime-keybindings|ms-|4.0.0
laravel-blade|one|1.18.0
vscode-icons|rob|7.27.0

(2 theme extensions excluded)

</details>

**Comment by DickvdBrink** [comment]
There is this button on the search bar where you can enable this.

See attached screenshot
![image](https://user-images.githubusercontent.com/765657/46004400-180d3d80-c0b3-11e8-91c3-cfe45297e51c.png)

**Comment by ajaykrishnalla** [comment]
Not there in documents
