### ISSUE TITLE
Debt: make FloatingClickWidget a reusable thing

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#59308]
Currently FloatingClickWidget seems to be living in `src/vs/workbench/parts/preferences/browser/preferencesWidgets.ts` but is already used in several places:
* keybindings
* debug

I would like to start using it for https://github.com/Microsoft/vscode/issues/59305. I find it already weird that debug has to depend on preferences to use it. I suggest to find a better place for it that avoids a dependency from debug to preferences.

**Comment by isidorn** [comment]
I can do this in debt week.

**Comment by bpasero** [comment]
I can do it together with https://github.com/Microsoft/vscode/issues/59305
