### ISSUE TITLE
Go to end of line with Ctrl+E in terminal

### ISSUE THREAD

**Issue by KyrychukD** [Microsoft/vscode#59304]
<kbd>Ctrl</kbd>+<kbd>A</kbd> and <kbd>Ctrl</kbd>+<kbd>E</kbd> behave like <kbd>Home</kbd> and <kbd>End</kbd> in terminals. Unfortunately, in vscode the keystroke <kbd>Ctrl</kbd>+<kbd>E</kbd> is assigned to the `workbench.action.quickOpen` command. It would be nice if this keybinding was not active when terminal is in focus so that <kbd>Ctrl</kbd>+<kbd>E</kbd> would move cursor to the end of line rather than show the quick open popup.

The workaround for this that I am currently using is to put the following to my `keybindings.json`:
```json
    {
        "key": "ctrl+e",
        "command": "-workbench.action.quickOpen",
    },
    {
        "key": "ctrl+e",
        "command": "workbench.action.quickOpen",
        "when": "!terminalFocus"
    }
```

I think this keybinding could be defined with `"when": "!terminalFocus"` by default so that the workaround above is not necessary.

**Comment by KyrychukD** [comment]
@Tyriar I tried to make a PR but tslint won't allow me to `import { KEYBINDING_CONTEXT_TERMINAL_NOT_FOCUSED } from 'vs/workbench/parts/terminal/common/terminal'` in `src/vs/workbench/browser/parts/quickopen/quickopen.contribution.ts`. Let me know if this issue will be resolved as I suggested (by adding `"when": "!terminalFocus"`), I will then investigate a bit more and make a proper PR.

**Comment by Tyriar** [comment]
I don't think we can change this at this point unfortunately as there would be many users that expect ctrl+e to work. I suggest just sticking with the workaround you have (I use a similar one). You can contribute a common question to describe the workaround to the website if you want:

- https://code.visualstudio.com/docs/editor/integrated-terminal#_common-questions
- https://github.com/Microsoft/vscode-docs/blob/master/docs/editor/integrated-terminal.md
