### ISSUE TITLE
List recently updated extensions

### ISSUE THREAD

**Issue by MeikTranel** [Microsoft/vscode#59315]
As a user, who enjoys reading patch notes it'd be cool if there was a way to sort an extension by the date of the update/install. That way i can still use autoupdate and in the event of an error that suddenly erupts i could help extension authors by providing context, when the issues first appeared and if its correlating with the installation or update of an extension.

**Comment by nealot** [comment]
I believe this is being tracked with https://github.com/Microsoft/vscode/issues/53405

**Comment by MeikTranel** [comment]
Yes, that's correct. I didn't see this one. Closing in favor of #53405
