### ISSUE TITLE
Shortcut key bug when using Simplified Chinese as display language

### ISSUE THREAD

**Issue by Yoctillion** [Microsoft/vscode#5931]
- VSCode Version: 1.0.0
- OS Version: Windows 10

When closing a modified file without saving, the popup dialog use the same shortcut key for '保存' (Save) and '不保存' (Don't Save).

Steps to Reproduce:

1. Change locate to zh-CN
2. Open or create a file
3. Modify the file without saving
4. Close the file from '工作文件' (WORKING FILE) or close the editor directly
5. On the popup saving dialog, '保存' (Save) and '不保存' (Don't Save) use the save shortcut key 'S'

**Comment by johnliu2016** [comment]
Dup of #6184
