### ISSUE TITLE
Show full line in search results

### ISSUE THREAD

**Issue by mak-ableton** [microsoft/vscode#59310]
After updating to 1.27.2 (I don't know the exact prior version I was on), search results only show a very small part of the line that the result is in. I can only assume that this change was intentional, so I'm filing this as a feature request: 

Please add an option to show the full line of each search result — I need more context to judge which search result is the one I'm looking for. It can be very confusing to not even see the beginning of the line. (There are people asking about this on StackOverflow already: https://stackoverflow.com/questions/52488545/show-full-line-in-search-results)

Alternatively, it would be great to optionally show even more context (i.e. lines above and below the search result) similar to what Sublime Text does.

**Comment by chadunit** [comment]
Given that there is specifically an option to use the search panel for "more space", it makes no sense to fail to use that space by truncating results. Please show whole lines in search results.

![vscode search panel 1](https://user-images.githubusercontent.com/25489524/48449165-17199380-e767-11e8-907a-c1850f5b2958.png)
![vscode search panel 2](https://user-images.githubusercontent.com/25489524/48449175-1c76de00-e767-11e8-817b-7145ffe27185.png)

**Comment by tillmanchen2015** [comment]
This issue still remains. Why nobody cares? If I search ERROR in log file, how can I check its date??!!!!!

**Comment by roblourens** [comment]
This was already improved quite a bit, e.g. from the above example:

![image](https://user-images.githubusercontent.com/323878/54621071-6547e780-4a24-11e9-93b7-fd28323c6875.png)

@tillmanchen2015 can you give an example that doesn't work as expected?

**Comment by tillmanchen2015** [comment]
> This was already improved quite a bit, e.g. from the above example:
> 
> ![image](https://user-images.githubusercontent.com/323878/54621071-6547e780-4a24-11e9-93b7-fd28323c6875.png)
> 
> @tillmanchen2015 can you give an example that doesn't work as expected?

for example, my text is:
10:00  hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello world 
10:00  hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello world 
10:00  hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello world 
10:00  hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello world 
10:00  hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello world 
10:00  hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello world 
10:00  hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello world 
10:00  hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello world 
10:00  hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello world 
10:00  hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello world 

I want to search world.
![image](https://user-images.githubusercontent.com/24838630/55856480-00079200-5b9d-11e9-83b2-ccb4ac2e86a1.png)

So do you notice the time stamp cannot be shown?
regards

**Comment by tillmanchen2015** [comment]
If I analyze log with vs code, searching key words is a normal operation. If I cannot read out time stamp from search result, it is useless completely.

**Comment by roblourens** [comment]
Thanks for the PR @Foolment, is this the way people would expect it to work? If the UI is not wide enough to see the actual match, you would just be able to see the beginning of the line, is that expected?

Would it be better to show the first X characters of the line, then snip a segment out, then show the actual match? `Foo [...] Bar`

Or would people expect a setting that lets you configure the number of leading characters to show?

Or should we come up with a guess for the number of leading characters based on the width of the search view at the time the search is executed?

Or something else I haven't considered? I don't think there is a perfect solution.

**Comment by mat-m** [comment]
@roblourens : Notepad++ introduced scrollbars :)
My view is: provide the more context you can about the matched string:
- If there is too much text before and after, center the text on the match, like `...aaaa RESULT bbbb...`
  - the dots will express the line was truncated
- If both sides are not balanced, use available "free" space for this:
  - `...aaaa bbbb RESULT cc;`
  - `aaaa RESULT bbbb cc...`
- Maybe we can have something like wrapping the line to have it totally whatever the length

**Comment by mak-ableton** [comment]
I would expect a preference to show the either the "full line" or a "truncated line" in search results. 

The "full line" option doesn't need a lot of configurability or smartness. Scroll bars or wrapping would both be fine if the window isn't wide enough. Ideally, word wrap would be configurable like in the editor.

If the "truncated line" option is chosen, I agree with @mat-m that an ellipsis should be shown to indicate that the line was truncated. I don't think you need to go overboard with the smartness about where to truncate since the "full line" option is available in cases where the truncated version becomes confusing.

**Comment by Foolment** [comment]
Thanks for the advises and discussion @roblourens.
I'm very much agree with @mak-ableton.

I think i can recode the PR to add just two simple options of a new configuration (`Result Line Display`)
1. `full-line`: full line + scrollbar.
2. `focus-match`: focus on the actual match (same as now and default form of display).

Maybe the better way is putting an option button into the search view instead of global settings, then we can easily switch the display of result line for each search.

**Comment by roblourens** [comment]
There is already a setting to allow horizontal scrolling but I think it's a crappy experience, especially since we put buttons after the text. With that you have to scroll far to get to the buttons. But maybe we could change the search view to show the full line if that setting is set.

Another thing to consider is that including the full text of a very long line in the results can cause things to get very slow, and we don't even get the full line of text from the search process, just the match and some surrounding text. Accidentally searching a minified file and getting long line results used to be a big problem.

**Comment by mak-ableton** [comment]
I think it's okay if the full line match makes things slow in certain cases. I can also totally live with the buttons after the text being hard to reach. After all, showing the full line would be just an option with its own set of upsides and downsides. Maybe this is one of those cases where perfect is the enemy of good.

**Comment by hsx2117** [comment]
> Thanks for the PR @Foolment, is this the way people would expect it to work? If the UI is not wide enough to see the actual match, you would just be able to see the beginning of the line, is that expected?
> 
> Would it be better to show the first X characters of the line, then snip a segment out, then show the actual match? `Foo [...] Bar`
> 
> Or would people expect a setting that lets you configure the number of leading characters to show?
> 
> Or should we come up with a guess for the number of leading characters based on the width of the search view at the time the search is executed?
> 
> Or something else I haven't considered? I don't think there is a perfect solution.

I think you can refer to sublime or notepad++.
There are very good search experiences in these apps when i find some problems by logs

**Comment by roblourens** [comment]
I will leave this issue open but I'm going to close the PR. It has gotten stale and would need some more thinking. However, this might get resolved when we do search results in a tab: https://github.com/microsoft/vscode/issues/23931. Will revisit it if it isn't.

**Comment by yuqilin** [comment]
I think it's useful. I used to Notepad++ search experience on Windows, that is really good. Hope to support the feature. Thanks.

**Comment by jenuc78** [comment]
I think is useful to see the full line of search results and also to have a history of previous searches, similar to notepad++ or jedit
Any plans to do something?

**Comment by rob3c** [comment]
I find it incredibly frustrating to click on a result that looks like active code, and then wasting time clicking the search result only to see it's actually commented out. This is worse in a mixture where some results show commented-out lines due to the hit being early in the line, combined with hits later in the line where the comment chars aren't visible.

The excerpts would be fine, except pulling out the sidebar to make it wider doesn't show any more of the result lines. Sheesh.

**Comment by GH4Arlene** [comment]
As a work-around: If you click on the "Open in editor" link at the top of the search results list, you can see the full lines.
