### ISSUE TITLE
Weird dialog for extension that supports no links

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#59314]
Testing #59244

* install `davidanson.vscode-markdownlint`
* run `xdg-open vscode-insiders://davidanson.vscode-markdownlint`
* you get this dialog that is not very helpful all the time:

![image](https://user-images.githubusercontent.com/900690/46006232-4c82f880-c0b7-11e8-8f05-92b4fa75952d.png)

**Comment by sandy081** [comment]
@bpasero What do you mean by extension that supports no links? Is it that extension has no URL handler registered?

**Comment by bpasero** [comment]
@sandy081 yeah just tried it out with the markdownlint extension. I just picked it as example, it probably does not register a URL handler.

**Comment by sandy081** [comment]
We cannot know upfront if an extension handles the URL or not. I do not think this case exists in real. Hence closing this.

@joaomoreno FYI

**Comment by joaomoreno** [comment]
@sandy081 Should it be `activated`, instead of `loaded`?

**Comment by sandy081** [comment]
An extension could be loaded but not yet activated (activation event). In this case extension is not loaded at all.
