### ISSUE TITLE
mac os 10.14 split screen

### ISSUE THREAD

**Issue by FernandoMiguel** [Microsoft/vscode#59318]
Issue Type: <b>Bug</b>

When i try to split screen (full screen on maos 10.14) of Code and a Chrome window, 
I can't resize either windows

VS Code version: Code - Insiders 1.28.0-insider (fe8d9d2470ddffb9dc2da604b23f5bd8a185cd66, 2018-09-25T07:29:33.175Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
spellright|ban|3.0.0
better-toml|bun|0.3.2
githistory|don|0.4.2
gitlens|eam|8.5.6
mdhelper|jos|0.0.11
vscode-github|Kni|0.30.0
terraform|mau|1.3.5
prettify-json|moh|0.0.3
vscode-docker|Pet|0.3.0
vscode-nginx|sha|0.5.0
sort-lines|Tyr|1.7.0

</details>

**Comment by FernandoMiguel** [comment]
cross linked bug
https://bugs.chromium.org/p/chromium/issues/detail?id=888950

**Comment by bpasero** [comment]
@FernandoMiguel I cannot reproduce so this maybe an issue with software you have installed.

**Comment by FernandoMiguel** [comment]
this is clearly a MacOS 10.14 bug.
i was able to reproduce it with more apps.

the cursor changes to arrow, but you can't drag it... only on a very specific location when you over shows a different overlay and then you can resize

**Comment by FernandoMiguel** [comment]
FYI, fixed on macos 10.14.1 beta

**Comment by bcarriereupgrade** [comment]
In case someone runs into this again, there's another scenario where this is happening - not just with VSCode but seems that developers use this feature a lot so I'm reporting it here.

For me the new resizing handle would not appear on my external 4k screen but it worked on the built-in Retina. I had to switch my external monitor to use native resolution instead of a scaled (retina) resolution and then it started working perfectly.

**Comment by FernandoMiguel** [comment]
@bruno the most recent betas seem to fix the issue almost for all scenarios
I had.

In case you are still seeing this, usually swapping windows panels will
make it show

--
Fernando Miguel
