### ISSUE TITLE
HTML comment inside a script tag in HTML 

### ISSUE THREAD

**Issue by vishalgarale** [microsoft/vscode#59313]
I'm facing this  [#44267](https://github.com/Microsoft/vscode/issues/44267) bug. 

- VSCode Version: 1.27.2
- OS Version: Ubuntu 18 LTS

Steps to Reproduce:
1. Create HTML page with script tag inside
2. Comment script code

HTML commenting happening inside script tag.

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
I tried with this example and was not able to reproduce:
```html
<html>
<head>
	<script>
		for (const key in object) {
			
		}		
	</script>
</head>
</html>
```
- select line 4 to 6, press `Ctrl + /`
- `//` are added to each line

@vishalgarale Can you please paste your (minimal) code sample with the steps.
Please let me know what language the editor is in ('html') and please run with all extensions disabled.

**Comment by vishalgarale** [comment]
PFA Snapshot of same code snippet. 

![issue](https://user-images.githubusercontent.com/9536053/46949944-b8e28d80-d0a0-11e8-8846-ba71b180629c.png)

**Comment by duranivan** [comment]
It is happening to me as well for both scripts and css styling inside html. In both cases the comment produced with `ctrl+/` is the html one, not the JS or CSS corresponding one.

(VS Code Version 1.28.2) - Mac OS Mojave.

**Comment by aeschli** [comment]
Still not able to reproduce. Please paste the example code here.
