### ISSUE TITLE
Debug: cannot start multiple debug sessions

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#59327]
Testing: #59225

OS: macOS Mojave

* have a folder with 2 files (index.js, index1.js) only having a simple console.log() statement.
* create a launch config as below
* add breakpoints to both files
* first start one config, then the other from the debug viewlet

=> only the first seems to have started, at least when looking at the debug toolbar

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program INDEX",
            "program": "${workspaceFolder}/index.js"
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program INDEX 1111",
            "program": "${workspaceFolder}/index1.js"
        }
    ]
}
```

**Comment by isidorn** [comment]
Might be related to https://github.com/Microsoft/vscode/issues/59331
Both me and Ben can not repro anymore -> closing
