### ISSUE TITLE
Extension revert

### ISSUE THREAD

**Issue by bingzheyuan** [Microsoft/vscode#5932]
Is it possible that I can revert to an older version of an extension since the new one is buggy?

**Comment by bpasero** [comment]
I think not. @joaomoreno ?

**Comment by joaomoreno** [comment]
Not really, unfortunately. Maybe communicate with the extension's authors and try to get it fixed for everyone?

**Comment by bingzheyuan** [comment]
Well I have managed to make it work again by copying code and dependencies of old version. This issue can be closed.
