### ISSUE TITLE
ModuleEvent raised by Debug Adapter has no effect

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#59329]
- VSCode Version: 1.27.2
- OS Version: Windows 10, x64

Steps to Reproduce:

1. Create a Debug Adapter extension, or modify vscode-mock-debug sample
2. Set supportsModulesRequest = true in initializeRequest
3. Implement modulesRequest
4. Implement a way of raising a ModuleEvent with reason="new", for example in the REPL loop's call to evaluateRequest
5. Set a breakpoint in your modulesRequest
6. Test the extension. Trigger the ModuleEvent. The breakpoint in modulesRequest isn't hit. Nor is there any visible change to the VSCode UI

I guess it's possible that VSCode doesn't yet make use of the Module capabilities of the DA protocol.

**Comment by isidorn** [comment]
This is simply not yet implemented

**Comment by Trass3r** [comment]
Example custom implementation for inspiration: https://github.com/vadimcn/vscode-lldb/blob/master/extension/modulesView.ts

**Comment by weinand** [comment]
@Trass3r thanks a lot for your example custom implementation

**Comment by weinand** [comment]
IIRC VisualStudio supports this, but VS Code does not (and there are no plans to implement this in the next 6 months).

**Comment by Trass3r** [comment]
Actually the debug adapter part has been merged recently for the cpp extension: microsoft/MIEngine#1040.
This ticket keeps track of the client side to display that info.
