### ISSUE TITLE
Thin cursor in the beginning of a line

### ISSUE THREAD

**Issue by neilsustc** [Microsoft/vscode#59328]
Issue Type: <b>Bug</b>

Open a document, type some words

![image](https://user-images.githubusercontent.com/7588612/46011614-52300c80-c0be-11e8-95fd-40615959a3a2.png)

![image](https://user-images.githubusercontent.com/7588612/46011622-58be8400-c0be-11e8-8bb5-cb4694fe9ba4.png)

VS Code version: Code - Insiders 1.28.0-insider (fe8d9d2470ddffb9dc2da604b23f5bd8a185cd66, 2018-09-25T05:31:33.193Z)
OS version: Windows_NT x64 10.0.18242

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (3.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by rebornix** [comment]
@neilsustc do you happen to zoom in/out the editor or change the font size ? It would be great if you can share more information to help troubleshoot.

**Comment by neilsustc** [comment]
No zoom (and even no `zoomLevel: 0`)
Font size 16

**Comment by roblourens** [comment]
I see this too, even with no settings. I can show you or debug @rebornix

**Comment by rebornix** [comment]
@roblourens thanks! I got it reproduced. It seems only happening on a high resolution monitor (like retina) I'll see if it's an upstream issue or not.

**Comment by rebornix** [comment]
It's introduced by https://github.com/Microsoft/vscode/commit/5c5e503c00a3f1ad517fca8943d52cc4eccaca57 which decreases the cursor `left` position by 1.

**Comment by alexandrudima** [comment]
The cursor is really difficult to see when indent guides are turned on:

![image](https://user-images.githubusercontent.com/5047891/46658644-79550680-cbb3-11e8-930e-6f161bc4bd1b.png)

**Comment by isidorn** [comment]
Looks great now -> verified
![screen shot 2018-10-11 at 16 17 23](https://user-images.githubusercontent.com/1926584/46810534-2d4fc080-cd71-11e8-8525-6ac18fd51444.png)
