### ISSUE TITLE
Misleading name for setting

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#59325]
re #58385

There is now `insertParametersForFunctionCalls` which talks about parameters but in reality it will also complete function calls that have no parameters, e.g. `foo()`.

**Comment by mjbvz** [comment]
How about: `insertTemplateForFunctionCalls`?

**Comment by jrieken** [comment]
Not sure if saying template instead of snippet helps... Maybe avoid it all together and have something like `suggestFunctionCalls` or `completeWithFunctionCalls`
