### ISSUE TITLE
Debug: extension host debug no longer hits breakpoint

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#59326]
Testing: https://github.com/Microsoft/vscode/issues/59225

OS: macOS Mojave
* install a hello world extension (yo code)
* add a breakpoint into the hello world code
* trigger it

=> my breakpoint is not hit

**Comment by isidorn** [comment]
Works for me.
Let me know what you are doing differently than me. I can also drop by your machine to investigate
![extension](https://user-images.githubusercontent.com/1926584/46014542-f5d5e880-c0cf-11e8-95fc-3687d8883da7.gif)

**Comment by bpasero** [comment]
Does not reproduce for me anymore.
