### ISSUE TITLE
Typing in the problems view filters with massive delay

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#59323]
re #7337

* start typing in the problems view
* nothing happens
* 🐌 eventually the UI catches up and I am not sure if this is overly aggressive debouncing or an actual perf issue...

**Comment by sandy081** [comment]
Yeah this is due to debouncing delay of 500ms

**Comment by mrkno** [comment]
Does anyone mind if I look at fixing this? It seems like it could be a relatively easy bug to solve for someone new to vscode
