### ISSUE TITLE
Find in terminal does not find across wrapped lines

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#59321]
Refs: #59267

OS X, zshell

Have a long line of continous characters wrapped in the terminal
Search for something which is wrapped -> no results

In my case:
`klasjdlajsdlkasjdlkanlcknxoiqhorihwoufbvbiubdoasdoasindoncxzonoqwioqwiejqwqewoiqwenoinczoxnoiadjoiwqjeoijasdoiasjoiczxjoicjoijwqeoijqwoidjasoijoijoi[WRAPPEDHERE]asdjo`
I search for `joia` -> no results

**Comment by chrmarti** [comment]
This blocks testing of the various modes:
![sep-25-2018 15-46-46](https://user-images.githubusercontent.com/9205389/46018523-5833e680-c0da-11e8-814c-c35d6a579959.gif)

**Comment by alexr00** [comment]
This appears to be related to 1e058b76ea. The latest from master doesn't have this issue.

**Comment by chrmarti** [comment]
Still in:
VS Code version: Code - Insiders 1.28.0-insider (5ba5f14c954682df46f04a541f0b272166605366, 2018-09-26T07:28:12.336Z)
OS version: Linux x64 4.15.0-33-generic

![sep-26-2018 10-49-57](https://user-images.githubusercontent.com/9205389/46068735-27a38980-c17a-11e8-9457-a6012166c6dc.gif)

**Comment by chrmarti** [comment]
I noticed that it starts working after the first page. On the first page the matches keep being offset.

**Comment by alexr00** [comment]
@chrmarti did you by chance launch the terminal, resize the terminal, then repro?

**Comment by chrmarti** [comment]
Not in this case. I just checked and it reproduces after reloading the window without any resizing.

**Comment by chrmarti** [comment]
Ok to close for me. Can no longer reproduce in:
Version: 1.30.0-insider
Commit: 241923763dbeaf3b64443187e935d55b29f6125d
Date: 2018-12-07T22:25:15.966Z
OS: Linux x64 4.15.0-39-generic
