### ISSUE TITLE
Improve output channel API options

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#59322]
Testing #59238

There's a couple issues with the current API:

```ts
/**
 * Creates a new [output channel](#OutputChannel) with the given name.
 *
 * By default, Output channels use a separate transport mechanism when appending data.
 * This helps to reduce CPU load on the UI process but also means that the output channel UI updates with a small delay.
 * Use the force-flag to enforce immediate updates at the cost of higher CPU usage.
 *
 * @param name Human-readable string which will be used to represent the channel in the UI.
 * @param options Options to control how the channel will be created.
 */
export function createOutputChannel(name: string, options?: { force?: boolean }): OutputChannel;
```

- The type of `options` should be extracted to an independent type: `OutputChannelOptions`.
- The perf description is very confusing. Eg `Output channels use a separate transport mechanism when appending data`... separate from what? Let's go straight to the point and just mention the different options for creating output channels and their implications.
- The description about output channels perf should be documenting the `force` field of the `options` bag, not the `createOutputChannel` function.
- `force` is a terrible name. @jrieken can surely come up with a better abstraction, he usually does
  - Should it be a `type` instead? That way it'll make it easier to describe that there are two different types of output channels, each with its own perf/qos characteristics, and the caller can override from the default type, etc.

**Comment by jrieken** [comment]
@joaomoreno welcome to the party: https://github.com/Microsoft/vscode/pull/58116#issuecomment-421054393

**Comment by jrieken** [comment]
> The type of options should be extracted to an independent type: OutputChannelOptions

@sandy081 I actually don't know why we have options instead of a simple boolean?

**Comment by joaomoreno** [comment]
`inMemory` was actually not too bad!

**Comment by jrieken** [comment]
Since it's not very intuitive we try to avoid something optional that defaults to true

**Comment by sandy081** [comment]
@jrieken I think you had the same question during review and it is because 

There is a request to set a lang id for channels. If so it has to be set while creating. Hence created options object.

**Comment by sandy081** [comment]
I also think `inMemory` as a better option even though we use log files on the renderer side when `true`. When channel is open, data directly goes into in memory model where as in other case it first goes to file and then to the model.

**Comment by jrieken** [comment]
> other case it first goes to file and then to the model.

and that means it is not in memory?

**Comment by jrieken** [comment]
Well, you decide, these are the constraints

* don't have something optional that default to true
* because we want people to use the log-file use a name that kinda means 'I am doing something bad/expensive'
* don't use a technical term, esp. not inMemory because that also shows up as scheme

Last, be aware that you created this problem just for yourself (trying to avoid a third argument in the future) and that using a parameter gives you the flexibility to change it later

**Comment by sandy081** [comment]
```ts
/**
 * Options to configure the behavior of the [OutputChannel](#OutputChannel)
 */
export interface OutputChannelOptions {

	/**
	 * By default, data appended to Output channels is written into a log file and is not piped to UI process immediately.
	 * Output channel UI is updated by listening to the corresponding log file changes.
	 * This helps to reduce CPU load on the UI process but also means that the output channel UI updates with a small delay.
	 *
	 * Enabling this flag will allow the data to be piped to UI process for immediate updates at the cost of higher CPU usage.
	 */
	readonly enablePiping?: boolean

}

/**
 * Creates a new [output channel](#OutputChannel) with the given name.
 *
 * @param name Human-readable string which will be used to represent the channel in the UI.
 * @param options Options to configure the behavior of the channel.
 */
export function createOutputChannel(name: string, options?: OutputChannelOptions): OutputChannel;


```

What do you think?

**Comment by jrieken** [comment]
> What do you think?

I think you should make it a param instead of an object and pick any name because that's not set in stone

**Comment by sandy081** [comment]
Removed the options completely.
