### ISSUE TITLE
Task arguments ignored when quotes inside argument

### ISSUE THREAD

**Issue by sguillia** [Microsoft/vscode#59334]
Issue Type: <b>Bug</b>

The arguments of my task command are merely ignored whenever there are quotes inside them.

**Steps to reproduce**

1. Create an executable script that shows the number of arguments that are passed to it.
I called it _show_args.sh_
```
#!/bin/bash
echo Nb args: $#
echo $@
```

2. Define some task in _tasks.json_
```
        {
            "label": "VS Code bug repro",
            "type": "shell",
            "command": [
                "/d/show_args.sh hello \"world\""
            ],
            "problemMatcher": []
        }
```

3. Run the task

4. See the output
```
> Executing task: /d/show_args.sh hello "world" <

Nb args: 0

```

Even the _hello_ argument is ignored.

Remove the quotes around _world_ and the script will work:
```
> Executing task: /d/show_args.sh hello world <

Nb args: 2
hello world

```

This bug makes the task feature unusable when quotes are required

VS Code version: Code - Insiders 1.28.0-insider (fe8d9d2470ddffb9dc2da604b23f5bd8a185cd66, 2018-09-25T05:31:33.193Z)
OS version: Windows_NT x64 10.0.15063

**Comment by dbaeumer** [comment]
@sguillia which shell (bash) are you using? WSL?

**Comment by dbaeumer** [comment]
I am able to reproduce this using the following setup:

tasks.json
```json
{
	"version": "2.0.0",
	"tasks": [
    	{
			"label": "VS Code bug repro",
			"type": "shell",
			"options": {
				"shell": {
					"executable": "C:\\Program Files\\Git\\bin\\bash.exe",
					"args": [
						"-c"
					]
				}
			},
			"command": [
				"./show_args.sh hello \"world\""
			],
			"problemMatcher": []
		}
	]
}
```

./show_args.sh
```sh
#!/bin/bash
echo Nb args: $#
echo $@
```

Using ' around world works as expected.

@Tyriar here is the shell launch config I use to start the terminal:

<img width="1190" alt="capture" src="https://user-images.githubusercontent.com/1931590/46135642-f2fd0400-c245-11e8-9325-3c9282e7481f.png">

Any advice you can give to make this work for " as quotes. In general the data looks good to me.

**Comment by Tyriar** [comment]
@alexr00 recently made a change in this area and might have an idea what's going on with this case.

**Comment by Tyriar** [comment]
Possible candidate, marking with September.
