### ISSUE TITLE
Diff editor's close button not right most

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#59338]
Issue Type: <b>Bug</b>

Should be the right-most action:
![image](https://user-images.githubusercontent.com/9205389/46015539-dab8a800-c0d2-11e8-8a92-64d2ce1d9a6a.png)

VS Code version: Code - Insiders 1.28.0-insider (fe8d9d2470ddffb9dc2da604b23f5bd8a185cd66, 2018-09-25T05:58:58.560Z)
OS version: Linux x64 4.15.0-33-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (2 x 2194)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|5.61GB (0.28GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.39
beautify|Hoo|1.4.4
theme-karyfoundation-themes|kar|18.2.1
lsp-inspector|oct|0.0.1
vscode-open-in-github|sys|1.7.0
ayu|tea|0.16.0

</details>

**Comment by bpasero** [comment]
I will push a workaround, but the real fix is https://github.com/Microsoft/vscode/issues/59346

**Comment by bpasero** [comment]
Na, [NO](https://github.com/Microsoft/vscode/commit/605b95d31cf2b44a96b943197c3c5848178236ed) [HACKS](https://github.com/Microsoft/vscode/commit/c38ebd77f5f15f9b2ddcaabe3a652fc61f975652)
