### ISSUE TITLE
presentationHint with kind="virtual" should also affect Expressions

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#59336]
- VSCode Version: 1.27.2
- OS Version: Windows 10, x64

Steps to Reproduce:

1. Create a debug adapter that sets presentationHint: {kind: 'virtual'} on a variable it returns from variablesRequest
2. Do the same on a variable that evaluateRequest returns when called with context='watch'
3. Observe that the variable name in the Variables panel is faded but the one in the Watch panel is not.

The fade behaviour was hinted at in  #50331 but it doesn't seem to work in the Watch panel.

**Comment by isidorn** [comment]
Works for me.
To investigate further, put a brekapoint [here](https://github.com/Microsoft/vscode/blob/f652102ec28fd6204882fa6fdcb3463f9f0b72d7/src/vs/workbench/parts/debug/common/debugModel.ts#L191)
And check if the presentationHint is properly passed.
If yes, F1 > developer tools > then inspect the element using chrome dev tools and check if the `virtual` class is on the element inside the watch expression view.

**Comment by gjsjohnmurray** [comment]
I just verified the problem by tweaking the vscode-mock-debug so it adds a presentationHint with kind='virtual' when evaluateRequest is returning a response from a request whose args.context was 'watch'

		response.body = {
			result: reply ? reply : `evaluate(context: '${args.context}', '${args.expression}')`,
			presentationHint: {kind: (args.context === 'watch') ? 'virtual' : 'data'}, /* MY EXTRA LINE */
			variablesReference: 0
		};
		this.sendResponse(response);

By running mock-debug in debug mode, adding a watch expression, and setting a breakpoint on the sendResponse line above I confirmed the response to the request was given the correct presentationHint ('virtual')

Using Developer Tools I found no sign of the virtual class getting added to the element inside the watch expression view.

As verification, I tweaked mock-debug's variablesRequest to make it add the presentationHint to one of the entries it adds to the Variables view.

			variables.push({
				name: id + "_s",
				type: "string",
				value: "hello world",
				presentationHint: {kind: "virtual"}, /* MY ADDED LINE */
				variablesReference: 0
			});

That entry dimmed as expected, and DevTools showed me the additional class.

**Comment by isidorn** [comment]
Thanks for providing more details.
The issue here is that the VariablesPresentationHint is only implemented for Variables, not for top level Watch Expressions since they are expressions.
Children of those expressions can be variables and they should be nicely shown dimmed, but not the top level ones.

For now leaving this open as a feature request and we can see if more users ask for this
