### ISSUE TITLE
Error while Launching a program 

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#59331]
Testing #59225

- Launch a program
- Stop it
- Edit the `program` attribute to some invalid value
- Launch the program again

🐛 Nothing happens

- Launch the program again

🐛 An error that the program is already running

![kapture 2018-09-25 at 14 11 55](https://user-images.githubusercontent.com/10746682/46013588-0d5fa200-c0cd-11e8-8e4a-8f995fce42fe.gif)

**Comment by isidorn** [comment]
@sandy081 Fixed in latest. Can you please try out of source or wait for the new insiders in 20minutes?
