### ISSUE TITLE
Breadcrumbs in diff editor: navigate while keeping diff

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#59332]
Verifying https://github.com/Microsoft/vscode/issues/57594

* Open a diff with outline
* Use the outline to navigate to symbols of the file
* Select a symbol
* 🐛 you are navigating to the file

I would expect to navigate within the diff on the right hand side.

**Comment by jrieken** [comment]
> I would expect to navigate within the diff on the right hand side.

Me too

**Comment by jrieken** [comment]
@bpasero Is that something that the editor service supports via some kind of options or this something that needs alex-editor knowledge?

**Comment by bpasero** [comment]
@jrieken we have a similar problem for the editor commands that start a navigation (e.g. "Go to definition"). If the definition is in the same file, we do not want to exit the diff editor. All of the editor commands leverage [`ICodeEditorService.openCodeEditor()`](https://github.com/Microsoft/vscode/blob/515c90a9fe1d8a28c0794420c3d82f7060bce73c/src/vs/workbench/services/codeEditor/browser/codeEditorService.ts#L39) for this purpose. This one is implemented in the workbench to support diff editors. Can you give it a try and see if that works?
