### ISSUE TITLE
Breadcrumb: item not fully clickable

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#59333]
Steps to Reproduce:

1. open breadcrump picker
2. navigate to the next breadcrumb item
3. 🐛 only the upper part of the item can be clicked (for me, on macOS Mojave)

![grid-tw](https://user-images.githubusercontent.com/900690/46013890-d047df80-c0cd-11e8-9fc4-18f84707acc1.gif)

**Comment by jrieken** [comment]
The problem is that the arrow expands the bounds of the context view and the context view eats mouse events...

<img width="442" alt="screenshot 2018-09-26 at 09 52 28" src="https://user-images.githubusercontent.com/1794099/46067466-2755bf00-c177-11e8-92c5-ab7d8fd982f6.png">
