### ISSUE TITLE
Outline won't highlight corresponding function entry when clicking inside C function body in editor

### ISSUE THREAD

**Issue by linuxjh** [Microsoft/vscode#59335]
Outline won't highlight corresponding function entry when clicking inside C function body in editor, while the status bar at the bottom can show the corresponding function prototype in its C/C++ Navigation.

If vscode can deal with big files and provide both file and project wide outlines (symbol lists) with performance as good as Source Insight, it can replace the later source code editor for lots of people on more operating systems.

- VSCode Version: 1.27.2
- OS Version: macOS 10.14
- Extension: ms-vscode.cpptools

**Comment by bpasero** [comment]
@linuxjh you are talking about the breadcrumb right?

**Comment by linuxjh** [comment]
hi @bpasero 

![screenshot20180925at8 33 28pm](https://user-images.githubusercontent.com/9011764/46015145-11f37d00-c104-11e8-8742-4db601466f46.png)

**Comment by linuxjh** [comment]
is it related to the so called language server protocol implementation? 
when will it be completed?
