### ISSUE TITLE
problem of indicate selection at vscode.window.showQuickPick() with octicons

### ISSUE THREAD

**Issue by wraith13** [Microsoft/vscode#59343]
- VSCode Version: 1.27.2(lang:ja), 1.28(insider, lang:en)
- OS Version: Windows, Mac

Steps to Reproduce:

1. run this code in extension
```typescript
        await vscode.window.showQuickPick
        (
            [
                {
                    label: `$(primitive-dot) $(file-text) Untitled-1`,
                    description: "description",
                    detail: "detail"
                },
                {
                    label: `$(primitive-dot) $(file-text) Untitled-2`,
                    description: "description",
                    detail: "detail"
                }
            ],
            {
                placeHolder: "Select a unsaved file",
            }
        );
```
![image](https://user-images.githubusercontent.com/645907/46016804-ba0f4300-c110-11e8-8b2c-186929ddf1c7.png)

2. type `unt`

![image](https://user-images.githubusercontent.com/645907/46016830-c8f5f580-c110-11e8-80b0-cc1b04f0e332.png)

Result:
The display of octicon will be broken and the wrong place will be selected and displayed.

Does this issue occur when all extensions are disabled?: No( this problem is at api for extensions )

**Comment by bpasero** [comment]
@chrmarti I am quite sure I fixed this a while back for normal quick open, maybe it is a regression from the new quick input widget?

**Comment by bpasero** [comment]
My change was: https://github.com/Microsoft/vscode/commit/ee9f1e7e4179ad68266150bfb272bc37a403982b
