### ISSUE TITLE
Suggest selection not respecting recently used?

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#59345]
- VSCode Version: 1.27.2
- OS Version: macOS 10.13.6

Steps to Reproduce:

I have a JavaScript file with this code: `const styles = {};`.

When I write `styl`, the suggest selection is `styleMedia` (some browser global, I think).

![image](https://user-images.githubusercontent.com/921609/46019886-fcb32a00-c0d4-11e8-89ff-6ad8e4313f01.png)

I change the suggest selection to my `styles` object and accept the suggestion.

If I then repeat these steps, I expect VSCode to automatically select the `styles` suggestion instead of `styleMedia`—as per the default [`editor.suggestSelection` (`recentlyUsed`)](https://code.visualstudio.com/docs/editor/intellisense#_suggestion-selection)—but it doesn't. Instead it selects `styleMedia`.

This happens every time, even though I've never used `styleMedia` in my whole life. :-(

![image](https://user-images.githubusercontent.com/921609/46019994-3a17b780-c0d5-11e8-982a-358dd4a55fde.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
> When I write styl,

Do you run with quick suggestions enabled? E.g. does the suggest window show already when starting to type the word? The default of `recentlyUsed` means that it only selects an history item when typing (e.g. a prefix like "styl") does select another item. You can try `recentlyUsedByPrefix` which is more aggressive in selecting historic items

**Comment by OliverJAsh** [comment]
> Do you run with quick suggestions enabled? E.g. does the suggest window show already when starting to type the word?

Yes, as per the default settings IIUC.

> The default of `recentlyUsed` means that it only selects an history item when typing (e.g. a prefix like "styl") does select another item

Can you clarify what you mean by this?

**Comment by jrieken** [comment]
> Can you clarify what you mean by this?

Sure. There is difference between the position at which suggestions have been triggered and the current position. That is because you can type while suggestions are showing - we call that type-to-select and the default setting (`recentlyUsed`) get over-ruled by type-to-select. Use `recentlyUsedByPrefix` instead

**Comment by jrieken** [comment]
I am very open for suggestions!

**Comment by OliverJAsh** [comment]
I would suggest adding something about the type-to-select mechanism and how it interacts/overrides `editor.suggestSelection` to [these docs](https://code.visualstudio.com/docs/editor/intellisense#_suggestion-selection) and in the settings here:

![image](https://user-images.githubusercontent.com/921609/46071765-ab5c7680-c178-11e8-8f5d-49abdb23fc49.png)

Furthermore, I think these docs should be consistent. The latter provides more information (although still not enough).

**Comment by jrieken** [comment]
cc @gregvanl
