### ISSUE TITLE
Inconsistencies with Windows conventions with custom title bar

### ISSUE THREAD

**Issue by daniel-white** [Microsoft/vscode#59347]
- VSCode Version: 1.27.2
- OS Version:  Windows 10 v1803

Steps to Reproduce:

1. Use `"window.titleBarStyle"` set to `"custom"`
2. Double click the icon that is in the system menu location.
    - Observe maximization. The Windows convention is to close the window.
4. Single click the icon.
    - Observe no behavior. The Windows convention is to open the system menu, flush under the title bar to the left.

Does this issue occur when all extensions are disabled?: N/A

**Comment by sbatten** [comment]
@daniel-white thanks for reporting, please see #58199 for explanation.
