### ISSUE TITLE
Should editComment's text parameter be a MarkdownString?

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#59349]
Issue Type: <b>Bug</b>

Testing #59278

Since the API is using MarkdownString in Comment#body too. Maybe also rename the parameter to `newBody` (or similar) that makes it clearer what it is.

VS Code version: Code - Insiders 1.28.0-insider (fe8d9d2470ddffb9dc2da604b23f5bd8a185cd66, 2018-09-25T07:29:33.175Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (5.66GB free)|
|Process Argv|--user-data-dir /Users/chrmarti/Development/repos/tmp/user2 --extensions-dir /Users/chrmarti/Development/repos/tmp/ext2|
|Screen Reader|no|
|VM|33%|

</details>Extensions: none

**Comment by RMacfarlane** [comment]
Closing since this version of the proposed API has been removed
