### ISSUE TITLE
define what 'args' is in IKeybindingService#executeCommand

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#5934]
The keybinding services allows to manually invoke a command. The signature today is `executeCommand(commandId: string, args?: any): TPromise<any>;` but it is unclear what `args` is esp. w.r.t. multiple arguments and the type (there is some massaging going on).

**Comment by jrieken** [comment]
related to #5902 and #5614

**Comment by alexandrudima** [comment]
obsolete I think
