### ISSUE TITLE
debug hover far away from target

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#5935]
see attached screen shots. the debug hover (showing large data) is very far away from the symbol I hover over. Compare background of the text with hover position.

<img width="549" alt="screen shot 2016-04-28 at 11 23 24" src="https://cloud.githubusercontent.com/assets/1794099/14881381/fdfa7a32-0d33-11e6-827a-5b450cb4af3d.png">
<img width="306" alt="screen shot 2016-04-28 at 11 24 15" src="https://cloud.githubusercontent.com/assets/1794099/14881382/fe1ca65c-0d33-11e6-851a-f404e8ac39a3.png">

Likely a regression from #5801

**Comment by isidorn** [comment]
This is happening because the string is too large and the editor decides to place the hover as high as possible to show the most data. To solve this we need to introduce a max string length to show in the hover

**Comment by jrieken** [comment]
> max string length to show in the hover

which is probably not a bad idea considering the space you have the loads of data some strings, arrays, etc contain
