### ISSUE TITLE
Portable mode not picking user-data (settings and keybindings)

### ISSUE THREAD

**Issue by ncodefun** [Microsoft/vscode#59355]
Extensions work though.

The folders structure is exactly the same as in the instructions, no typo...
i.e. `vscode-portable\data\user-data\...`
- VSCode Version: 1.27.2
- OS Version: Win 10 (1803)

Steps to Reproduce:

1. Follow the instructions to migrate to a portable folder (https://code.visualstudio.com/docs/editor/portable#_migrate-to-portable-mode)
2. Open Code.exe
3. command palette > open settings.json -> "empty". (or drop a folder on Code.exe)

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
What's the file path of that settings.json file which opens when you open it via the command palette?
