### ISSUE TITLE
workbench.action.terminal.focusNextPane  and workbench.action.terminal.focusPreviousPane not working on Mac OS X Mojave

### ISSUE THREAD

**Issue by wmcbain** [Microsoft/vscode#59358]
- VSCode Version: 1.28.0-insider
- OS Version: Mac OS X 10.14

Steps to Reproduce:

1. Open the integrated terminal
2. Create a new terminal pane
3. Attempt to use the focusNextPane keyboard shortcut
4. Change the focusNextPane and focusPreviousPane bindings to something new/unique
5. Attempt to focus between panes again
6. Panes should not switch in either case

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by Tyriar** [comment]
Cannot repro on High Sierra or Mojave, maybe another app is conflicting with the keybindings like Spectacle?
