### ISSUE TITLE
Nothing happens when editComment returns null

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#59354]
Issue Type: <b>Bug</b>

Testing #59278

It looks like the operation is still running. (Similar to #59348.)

VS Code version: Code - Insiders 1.28.0-insider (fe8d9d2470ddffb9dc2da604b23f5bd8a185cd66, 2018-09-25T07:29:33.175Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.83GB free)|
|Process Argv|--user-data-dir /Users/chrmarti/Development/repos/tmp/user2 --extensions-dir /Users/chrmarti/Development/repos/tmp/ext2|
|Screen Reader|no|
|VM|33%|

</details>Extensions: none

**Comment by RMacfarlane** [comment]
I'm not sure I understand what returning null is meant to signify in this context - that there was no update? What is the expected behavior in that case?

**Comment by chrmarti** [comment]
It's a extension's error. I'd expect it to be handled in a way that does not leave the UI in that intermediate state like it is still updating. Maybe handle it similarly to when an error is thrown.

**Comment by RMacfarlane** [comment]
Based on feedback of https://github.com/Microsoft/vscode/issues/59460, I changed the return type of editComment to `Promise<void>`. So the extension should now either return nothing and succeed, or throw
