### ISSUE TITLE
Cant Update my Vscode

### ISSUE THREAD

**Issue by kartikdutta28** [Microsoft/vscode#59359]
Sep 25 21:44:24.268 INFO Starting: C:\Program Files\Microsoft VS Code\Code.exe, false
Sep 25 21:44:24.269 ERRO Bad arguments: Code path doesn't seem to exist: C:\Program Files\Microsoft VS Code\Code.exe

**Comment by joaomoreno** [comment]
@kartikdutta28 Does `C:\Program Files\Microsoft VS Code\Code.exe` exist?

**Comment by xiaodeaux** [comment]
Uninstalling and reinstalling fixed the update issue for me. I also rebooted my computer. That may have done something as well.
