### ISSUE TITLE
VSCode not honouring the VSTS Personal Access Token behind a Proxy

### ISSUE THREAD

**Issue by westerdaled** [Microsoft/vscode#59357]
- VSCode Version: 1.25.1
- OS Version: Windows 10

Steps to Reproduce:

1. Added the proxy settings to user settings: http://daniel.westerdale@domain.com:MyPassword@proxy-I-am-forced-to-used:80
2. Created a PAT in VSTS
3. Ctrl-P Team:signin
4. choose the default: reset PAT option
5. Enter my newly created PAT
6. Click sync changes in VSCode
7. VSCode requests Password
8. Visual Studio Code dialog appears 
9. Enter my username and PW ( not this the same client domain cred I have associated with our VSTS user account.
10. VSCode request User and PW 
11. After a while VSCode reports error.

> git check-ignore -z --stdin
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
fatal: no upstream configured for branch 'master'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git push -u origin master
fatal: UriFormatException encountered.
   queryUrl
Logon failed, use ctrl+c to cancel basic credential prompt.
fatal: Authentication failed for .....
'https://ourdomain.visualstudio.com/...

Does this issue occur when all extensions are disabled?: Yes/No

Note I am able to connect to GITHub (not VSTS) with just my username,pw and proxy url via the .http setting.

**Comment by joaomoreno** [comment]
Please create an issue on the extension's repository. There are already a few proxy ones: https://github.com/Microsoft/azure-repos-vscode/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+proxy
