### ISSUE TITLE
Code color issue after update

### ISSUE THREAD

**Issue by TwentyFourColors** [Microsoft/vscode#59366]
I updated VSC to the version 1.27.2.

The colours of the code in Dark mode are terrible. I almost cannot see them clearly.

The problem is same like this https://stackoverflow.com/questions/43914872/visual-studio-2017-code-color-issue-after-update to Visual Studio.

Before Update
<img width="367" alt="screenshot 2018-09-25 at 20 39 33" src="https://user-images.githubusercontent.com/16758515/46035380-2be09000-c103-11e8-85b6-9b87ff4ed31c.png">

After Update
![screenshot 2018-09-25 at 20 36 52](https://user-images.githubusercontent.com/16758515/46035259-f045c600-c102-11e8-9386-86e323e76427.png)

I don't know what do to solved. 

Thanks by the help

**Comment by TwentyFourColors** [comment]
I solved this problem. 

The problem was related with the new MacOS Mojave.

Here the solution -> https://ahmadawais.com/fix-macos-mojave-font-rendering-issue/ 

More information related with this -> https://www.howtogeek.com/358596/how-to-fix-blurry-fonts-on-macos-mojave-with-subpixel-antialiasing/

Thanks !!

: )

**Comment by aeschli** [comment]
So this was about font rendering, not the colors.
