### ISSUE TITLE
files.associations is not case sensitive ("*.c": "c", "*.C": "cpp" doesn't work)

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#59369]
On any OS, files.associations with `"*.c": "c"` and `"*.C": "cpp"` are treated identically (case insensitive), but .c needs to be associated with the "C" and language and .C with the "C++" language. When both are present, the last one ends up getting used.

Our C/C++ extension may be able to add some special case workaround for this (not sure yet).

**Comment by sean-mcmanus** [comment]
Does anyone know what the duplicate issue is? I searched and couldn't find it:

![image](https://user-images.githubusercontent.com/19859882/46100002-3c355100-c17d-11e8-8773-20b626edd10f.png)

**Comment by inweblife** [comment]
No help, no nothing, why?

**Comment by sean-mcmanus** [comment]
@inweblife You mean why wasn't my question answered?

@bpasero Do you know what issue is tracking this issue and/or what I should search for to find the duplicate issue?
