### ISSUE TITLE
trace-to-console trace option doesn't appear to change behavior

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#59367]
Testing https://github.com/Microsoft/vscode/issues/59234

- Run with `--trace-options trace-to-console --trace`

I expected data to be printed to a console instead of written to a file. Trace is still written to a file, and I don't see anything printed to the terminal I launched from, debug console, or dev tools console

**Comment by bpasero** [comment]
Works for me, the output shows up in the main side so you need to run with --verbose to keep the process running: `code-insiders --trace-options trace-to-console --trace --verbose`

![image](https://user-images.githubusercontent.com/900690/46072090-c41d5a00-c181-11e8-9be8-18b896fc52c0.png)
