### ISSUE TITLE
Respect global .gitignore when searching

### ISSUE THREAD

**Issue by vanossj** [Microsoft/vscode#59364]
The global .gitignore file, aka git config `core.excludesfile` setting should be used when searching, just like the local .gitignore file is.

Currently files/folders will be ignored if they are in the local .gitignore, but not if they are only in the global git ignore.

#49239 asked about this feature, but it was incorrectly closed.

**Comment by roblourens** [comment]
I can add a setting to be opted into this, but I disabled it by default because it confused too many people

**Comment by roblourens** [comment]
Would take a PR that adds a setting, false by default, for whether to add this flag: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/search/node/ripgrepTextSearch.ts#L514
