### ISSUE TITLE
Find match was not cleared after researching

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#59372]
#59267. 

* Open vscode repo folder
* `ls`
* Find `.editorConfig`, press enter, `.editorConfig` was selected
* Change query to `.editor`, press enter, selection was not updated.

**Comment by euler16** [comment]
is anyone else working on the issue? I would like to contribute.

**Comment by Tyriar** [comment]
Thanks to @skprabhanjan in https://github.com/xtermjs/xterm.js/pull/1756, this should be fixed in tomorrow's Insiders build 🎉

**Comment by mjbvz** [comment]
In 97ad72a02c351d6cde0fd32b41d9700a43e5964a, when following @rebornix's exact steps, the search result is cleared after pressing enter for `.editor`

**Comment by Tyriar** [comment]
Looks fixed
