### ISSUE TITLE
Caton, delay

### ISSUE THREAD

**Issue by liust2014** [Microsoft/vscode#5937]
- VSCode Version:1.0.0
- OS Version:Windows 10 home

Steps to Reproduce:

1. VSCode After open system becomes very card, open the folder and any text file card after open system becomes very card, open the folder and any text file。

**Comment by liust2014** [comment]
The whole system become caton

**Comment by bpasero** [comment]
@liust2014 sorry I am having trouble to understand what you mean

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
