### ISSUE TITLE
First match is not the first match in the viewport

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#59376]
#59267 

Actually I don't know how we determine where to start when we do first search, the first match we find can be any one each time

![terminal-find-position](https://user-images.githubusercontent.com/876920/46040884-56602800-c0c6-11e8-98c0-bb139e677fea.gif)

**Comment by Tyriar** [comment]
Upstream: https://github.com/xtermjs/xterm.js/issues/1749

**Comment by Kailash0311** [comment]
Can I take this up , if no one is already working on it!

**Comment by Tyriar** [comment]
@Kailash0311 sure, it looks like @Marina-Miranovich has a commit referencing the upstream issue at https://github.com/xtermjs/xterm.js/issues/1749, not sure if that was just experimenting or not?
