### ISSUE TITLE
No regex validator for terminal find widget

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#59378]
#59267

We can add the same regex validator for the terminal find widget input box if the underling regex engine is JavaScript regex. Close this one if we are using another regex engine somehow in xterm.js.

**Comment by Tyriar** [comment]
So in the terminal widget show things like this and reject the search?

<img width="238" alt="screen shot 2018-10-11 at 11 58 06 am" src="https://user-images.githubusercontent.com/2193314/46827282-16977280-cd4d-11e8-9d0c-596d463c17ee.png">

**Comment by CometS1** [comment]
I would like to try and work on this feature. Could someone tell me where to start working on this feature?

**Comment by Tyriar** [comment]
@CometS1 the terminal find widget code is here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/terminal/browser/terminalFindWidget.ts

It extends the SimpleFindWidget: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/find/simpleFindWidget.ts

Not sure where the validator is but I'd look around the findInput.ts and findWidget.ts files.
