### ISSUE TITLE
Match word doesn't align with editor find widget

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#59379]
#59267

In the editor, `CODE` with march word turned on will not match anything in `CODE_OF_CONDUCT` as `_` is seen as a whole word but in terminal find widget, it matches `CODE`. IMO we don't have any word separators set for the terminal but having different behaviors of find widget options seems weird.

**Comment by alexr00** [comment]
These are the non-word characters right now: ` ~!@#$%^&*()_+`-=[]{}|\;:"\',./<>?`. Looks like underscore should be removed. Are there any others that stand out?

**Comment by Tyriar** [comment]
@alexr00 just underscore seems right to me.
