### ISSUE TITLE
navigateToLastEditLocation isn't cosistent about the position

### ISSUE THREAD

**Issue by misolori** [Microsoft/vscode#59382]
Issue Type: <b>Bug</b>

Testing #59243

My cursor position isn't consistent when I go back to the last edit position. This happens when 

**Steps to reproduce**

1. Make an edit to a line, go to end of line
2. Navigate away
3. Use the shortcut command to navigate to last edit location (cmd+k cmd+q)
4. Line returns to a character before the last line

**Expected results**
1. Line to return at the end of line (where I last was)

![gif](https://user-images.githubusercontent.com/35271042/46041727-5e20cc00-c0c8-11e8-8546-9c043f38815e.gif)

VS Code version: Code - Insiders 1.28.0-insider (fe8d9d2470ddffb9dc2da604b23f5bd8a185cd66, 2018-09-25T07:29:33.175Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|22%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|1.4.6
gitlens|eam|8.5.6
vscode-pull-request-github|Git|0.1.6
beautify|Hoo|1.4.4
vscode-colorize|kam|0.7.2
theme-monokai-pro-vscode|mon|1.1.8
ayu|tea|0.16.0
sort-lines|Tyr|1.7.0

(9 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
@misolori the logic is literally to record the cursor position at the time the model has changed. I pushed a fix for https://github.com/Microsoft/vscode/issues/59370 which should make the detection smarter. However, it would never return to a location that was not edited. So if you move to the end of the line, and that does not change the content, I would not record that as "last location that was edited". 

Also, if characters are inserted automatically (quotes, double quotes) and the cursor does not move, it would not use the location after the quotes as "last location that was edited".

Closing thereby, please test again with my fix for https://github.com/Microsoft/vscode/issues/59370
