### ISSUE TITLE
Workspace files notification wording

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#59381]
Testing https://github.com/Microsoft/vscode/issues/59241

Currently the wording of the notification ends with `Do you want to open it (click here to learn more)?` or `Do you want to open one (click here to learn more)?`

I suggest either adding a "Learn More" option on the notification instead or changing it to `Click here to learn more. Do you want to open it?`

**Comment by egamma** [comment]
Introducing a link with ´click here´ is unusual. Also it would be good to tell up front, what I can learn more about.

So I suggest something like. 'Do you want to open it? [Learn more](https://code.visualstudio.com/docs/editor/multi-root-workspaces#_workspace-file) about workspace files.`'

I would also make the link more specific and link to the workspace file section  https://code.visualstudio.com/docs/editor/multi-root-workspaces#_workspace-file

**Comment by bpasero** [comment]
Changed to:

![image](https://user-images.githubusercontent.com/900690/46064190-0be6b600-c16f-11e8-9010-83faf11cb40a.png)

I am not able to use our `fwlink` tool to open a URL that includes a `#`

**Comment by RMacfarlane** [comment]
When opening a folder with multiple code-workspaces files in it, the link isn't displayed correctly:
![screen shot 2018-09-27 at 3 33 36 pm](https://user-images.githubusercontent.com/3672607/46178248-eccd4e80-c26a-11e8-96d5-237cd0ef5942.png)

Looks like the {1} should be {0} in the template string

**Comment by bpasero** [comment]
@RMacfarlane thanks1
