### ISSUE TITLE
Yellow JS file icons are hard to see at small sizes on windows

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#59380]
Testing #59246

1. On windows, with vscode file icons configured 
1. View a `.js` file in the explorer's `details` or `small icons` view

**bug**
The yellow against the white background is quite hard to make out at small sizes:

![screen shot 2018-09-25 at 11 59 12 am](https://user-images.githubusercontent.com/12821956/46041456-b0adb880-c0c7-11e8-94d4-91ce4b85e266.png)

**Comment by misolori** [comment]
Since #59361 has been fixed (shows logo on small icons) this issue should be resolved.
