### ISSUE TITLE
Extension without publisher should be able to run / debugged

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#59387]
- `yo code`
- Remove `publisher` field
- Error

```
[/Users/octref/Code/language-extension-samples/grammar-hello-world]: property `publisher` is mandatory and must be of type `string`"
```

Why do I have to have a publisher to run/debug an extension?

**Comment by sandy081** [comment]
@octref Is this coming from yo code?

**Comment by octref** [comment]
@sandy081 No the error comes from VS Code. VS Code literally doesn't allow me to run the extension using launch.json, if its package.json doesn't contain a publisher.

**Comment by sandy081** [comment]
@octref It comes from [here[(https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/extensions/node/extensionPoints.ts#L370)

Publisher id is mandatory because it is used to generate the id of the extension. So I think this cannot be made optional.
