### ISSUE TITLE
Escapce to dismiss terminal find widget doesn't refocus the terminal

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#59388]
#59267

* Open the terminal, search
* Escape to dismiss the find widget
* The terminal doesn't regain the focus

**Comment by TomerPacific** [comment]
@Tyriar ,
Is this issue still relevant and if so, can I try to solve it?

**Comment by Tyriar** [comment]
@TomerPacific still needed yes, code pointer:

https://github.com/Microsoft/vscode/blob/0e7b34db425af89c86c41abc9371903d19e4e476/src/vs/workbench/parts/terminal/electron-browser/terminal.contribution.ts#L478-L481

**Comment by tmax** [comment]
what version exactly is this tied to? I'm on:

 ```
Version 1.28.1 (1.28.1)

3368db6750222d319c851f6d90eb619d886e08f5

2018-10-11T18:00:44.561Z
```

Mac OS: `10.11.6 (15G22010)`

Is this an issue only in a particular build and/or os version?

**Comment by tmax** [comment]
this is kind of related, and I'm assuming a few things here, so correct me if I'm wrong, but.... should vscodebod app have _not_ filed this issue?  It seems there are some vital informations missing from the ticket description in order to pinpoint exactly how and where to find the bug here.  

cc @Tyriar 	?

**Comment by Tyriar** [comment]
> I keep getting issues regarding vscode-fsevents. It says that the platform win32 is not compatible with this module.

@TomerPacific you can safely ignore that, it just means yarn skipped the installation.

> Can we close this issue? Seems to not be a bug at least on the latest build.

Someone else must have fixed this over the past couple of days, it was definitely happening when I added the labels 😕. Thanks for pointing it out.

**Comment by tmax** [comment]
Just curious, but do you happen to know which issue it was fixed in?

**Comment by Tyriar** [comment]
@TomerPacific https://github.com/Microsoft/vscode/labels/good%20first%20issue is the list of beginner stuff available, the more general query https://github.com/Microsoft/vscode/labels/help%20wanted has all the changes we want help but and may also have some easy ones.

**Comment by Tyriar** [comment]
@tmax not sure, don't think it's worth the time to investigate.
