### ISSUE TITLE
[folding] navigateToLastEditLocation doesn't expand folded regions

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#59383]
Issue Type: <b>Bug</b>

Testing #59243

This works on a single file, however when you navigate to another file it doesn't expand folded regions.

**Steps to reproduce**

1. Make an edit to a line
2. Navigate to another tab
3. Use the shortcut command to navigate to last edit location (cmd+k cmd+q)
4. Line returns to last line in folder region (doesn't go to last edit location)

**Expected results**
1. Line to expand folded regions and return to previous position

![gif](https://user-images.githubusercontent.com/35271042/46042226-be643d80-c0c9-11e8-9795-7e5e8b1c893e.gif)

VS Code version: Code - Insiders 1.28.0-insider (fe8d9d2470ddffb9dc2da604b23f5bd8a185cd66, 2018-09-25T07:29:33.175Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|22%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|1.4.6
gitlens|eam|8.5.6
vscode-pull-request-github|Git|0.1.6
beautify|Hoo|1.4.4
vscode-colorize|kam|0.7.2
theme-monokai-pro-vscode|mon|1.1.8
ayu|tea|0.16.0
sort-lines|Tyr|1.7.0

(9 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
@rebornix looks like an issue with the editor to me. I am calling [`editor.setSelection()`](https://github.com/Microsoft/vscode/blob/495ff68b85d358022a65b224ac69442589d6b3c6/src/vs/workbench/common/editor.ts#L868) but the folded region is not expanded. This is possibly a race condition because the editor is not yet rendered when calling the method?

**Comment by rebornix** [comment]
@bpasero we get the folding model asynchronously so the folding regions are restored after the selection is set. The sequence of navigating to an invisible editor and setting selections is 

* File open 
* Restore view state --- > [Folding.restoreViewState](https://github.com/Microsoft/vscode/blob/8ab695c975bc33870b53805aa5e2929c40461cc4/src/vs/editor/contrib/folding/folding.ts#L151)
* [editor.setSelection()](https://github.com/Microsoft/vscode/blob/495ff68b85d358022a65b224ac69442589d6b3c6/src/vs/workbench/common/editor.ts#L868)
* Folding.restoreViewState -> [this.getFoldingModel().then( foldingModel.applyMemento )](https://github.com/Microsoft/vscode/blob/8ab695c975bc33870b53805aa5e2929c40461cc4/src/vs/editor/contrib/folding/folding.ts#L168)

It behaves differently when the target editor is already visible as there will be no `restoreViewState`.
