### ISSUE TITLE
'Unnecessary using directive' is falsely flagged when required for XML cref comments.

### ISSUE THREAD

**Issue by lake-fall** [Microsoft/vscode#5938]
- VSCode Version: 1.0.0
- OS Version: WIndows 10 Version 1511

Steps to Reproduce:

1. Create a C# class.
2. Add an XML comment with `/// <see cref="SqlCommand.Parameters" />`
3. Add the using using `System.Data.SqlClient;` to the namespace.
4. The warning `Unnecessary using directive` appears.
5. This is in conflict to Visual Studio 2015 Community, where removing the using directive generates the warning `CS1574 XML comment has cref attribute 'SqlConnection' that could not be resolved`.

**Comment by bpasero** [comment]
@lake-fall please report C# issues against the omnisharp repository.

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-roslyn#542
