### ISSUE TITLE
Per file type icons used on windows even at smaller sizes

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#59385]
Testing #59246

From the description on #59246, it sounds that like on windows the vs code file type specific icons should only be shown at large and medium icon sizes. However I also seem them being used at small sizes (although in a different variant that does not include the vscode logo in the bottom right corner). Is this the expected behavior?

**Comment by misolori** [comment]
That is a bug, it should show the VS Code logo only on smaller sizes. I filed #59361 this morning in response to it.
