### ISSUE TITLE
vs code  debuging asp net core watch error 

### ISSUE THREAD

**Issue by pzhxd** [Microsoft/vscode#5939]
- VSCode Version: 1.0
- OS Version: win7 x64

Steps to Reproduce:
debug cli-samples HelloMvc, when add breakpoint watch variables  "s"  show error, please help !
![qq 20160428181727](https://cloud.githubusercontent.com/assets/18717913/14883131/fb7b7a1e-0d6e-11e6-8010-d4c0f63f7c97.png)

**Comment by bpasero** [comment]
@isidorn I guess this issue should be moved to Omnisharp?

**Comment by isidorn** [comment]
Yes, @pzhxd can you please file this issue against the extension https://github.com/OmniSharp/omnisharp-vscode

thanks
