### ISSUE TITLE
Emmet Syntax Profiles tag_nl adds extra white space

### ISSUE THREAD

**Issue by charliecalvert** [Microsoft/vscode#59395]
- VSCode Version: 1.27.2
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Add this to my User Settings:

```
   "emmet.syntaxProfiles": {
        "html": {
            "tag_nl": false            
        }
    },
```
2. Type some text: foo

 3. Select emmet: Wrap with Abbreviation and select a tag such as h1

Expected: **&lt;h1&gt;foo&lt;/h1&gt;**
Actual: 

```
<h1> 	foo </h1>
```
Note the extra white space.

Does this issue occur when all extensions are disabled?: Yes/No 

Not sure how to answer this as I believe emmet is an extension.

**Comment by irrationalRock** [comment]
Hi, I'm interested in this. I'm guessing a good place to start is `doWrapping()` in `abbreviationActions.ts`?

**Comment by ramya-rao-a** [comment]
Thanks @irrationalRock 
Yes, thats the right file.
My suspicion is that this is related to https://github.com/Microsoft/vscode/blob/1.27.2/extensions/emmet/src/abbreviationActions.ts#L610
