### ISSUE TITLE
DA tracker always reports error

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#59396]
#59110

I get

```
debugAdapterError: Error: read error
debugAdapterExit: 130
``` 

every time when debugging ends. Do you see that? I'm not sure about the exist code but the "read error" error seems like it comes from vscode every time the DA stdout closes, isn't that expected?

**Comment by weinand** [comment]
I think that error is expected. It is definitively not an error of the tracker, as the tracker is only the messager. In normal operation VS Code sees the error too but surpresses it.

**Comment by Trass3r** [comment]
To be closed?

**Comment by weinand** [comment]
yes, that is fixed.
