### ISSUE TITLE
Symlinks still gets resolved on MacOS

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#59394]
Issue Type: <b>Bug</b>

Testing https://github.com/Microsoft/vscode/issues/59245

Symlinks still gets resolved on MacOS.

Steps:
1) Create symlink `dev -> /%HOME%/Downloads` in HOME
2) Open `code-insiders ~/dev`
3) Notice that the symlink has been resolved in the explorer, and editor paths (to Downloads/) but the terminal shows `dev`

VS Code version: Code - Insiders 1.28.0-insider (fe8d9d2470ddffb9dc2da604b23f5bd8a185cd66, 2018-09-25T07:29:33.175Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
jsx|Twe|0.0.1
chrome-vs-code|fab|0.0.1
vscode-pull-request-github|Git|0.1.6
vscode-azureappservice|ms-|0.9.1
azure-account|ms-|0.4.3
debugger-for-chrome|msj|4.10.1
vscode-icons|rob|7.27.0

</details>

<img width="720" alt="microsoft teams notification 2018-09-25 15-08-59" src="https://user-images.githubusercontent.com/173559/46046191-fd4bc080-c0d4-11e8-9c23-b1084cbecfbc.png">

**Comment by bpasero** [comment]
@auchenberg I cannot reproduce, here is the exact steps I followed:
* `cd ~`
* `ln -s ~/Downloads/ dev`
* `code-insiders ~/dev`

I see that `~/dev` is preserved
![image](https://user-images.githubusercontent.com/900690/46071529-81a74d80-c180-11e8-9575-7c788e31f135.png)

**Comment by auchenberg** [comment]
Verified working in today's build.
