### ISSUE TITLE
Auto save in new settings results in multiple validation errors when typing text

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#59391]
Continuing discussion from #58537

> Steps to Reproduce:
> 
> Open new settings editor, search for "emmet extension"
> Emmet: Extensions Path is a setting that takes path to a directory. Start typing a path
> Since we auto-save in 100ms, the config change event is fired for almost every other character typed, which results in validation checks from the emmet extension resulting in a series of error notifications.
> 
> There might be other extensions in the marketplace that do such validations after listening the config change event.

**Comment by roblourens** [comment]
If we're considering adding a save button, there's a difference between a save button for an individual setting vs a save button for the whole settings editor.

I think I'd be more open to a save button on certain individual text fields than a save button for the whole settings editor. In the first case, the impact is very minor and it only affects settings that really need it. In the second case, it would be very frustrating to open the settings UI, click a checkbox, then have to click a save button as well.

**Comment by michelleangela** [comment]
@roblourens the [C/C++ extension](https://github.com/microsoft/vscode-cpptools) is also affected by the fast auto save feature from the settings UI editor (see issue #3644).

The [C/C++ extension](https://github.com/microsoft/vscode-cpptools) has a similar settings UI editor accessed via command `C/C++: Edit configurations (UI)`. Changes to any text field from the UI editor is saved when an input text field loses focus. Can we also do the same for the VS Code settings text field input?

**Comment by rzhao271** [comment]
Closing as out of scope. Repro cases also seem outdated.
