### ISSUE TITLE
"Explorer: Focus $View" commands do not include english label in command palette 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#59392]
Testing #58469

Issue Type: <b>Bug</b>

1. Using a different UI language in VS Code, such as `de`
1. With the npm scripts explorer enabled
1. Try running the `Explorer: focus npm script explorer` command

**Bug**
Notice that only the localized description is shown in the command palatte:

![screen shot 2018-09-25 at 2 46 09 pm](https://user-images.githubusercontent.com/12821956/46045344-44848200-c0d2-11e8-8ff9-1367270d24b3.png)

Most built-in command include both the localized version as the main title and the english version beneath 

VS Code version: Code - Insiders 1.28.0-insider (fe8d9d2470ddffb9dc2da604b23f5bd8a185cd66, 2018-09-25T07:29:33.175Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.22GB free)|
|Process Argv|--locale=de|
|Screen Reader|no|
|VM|22%|

</details>

**Comment by sandy081** [comment]
Good catch

**Comment by mjbvz** [comment]
I believe that the `viewDescriptor.name` will still be localized in the details text even after this change. Is there a way to use the english view name here?

**Comment by sandy081** [comment]
@dbaeumer Do I get localized string 
https://github.com/Microsoft/vscode/blob/087ee56e75b166850a6a664f176c132b36602293/src/vs/platform/actions/common/actions.ts#L18

if the author has a translated string for name property?

**Comment by jrieken** [comment]
<img width="963" alt="screenshot 2018-09-28 at 14 18 46" src="https://user-images.githubusercontent.com/1794099/46207989-81968180-c329-11e8-9083-f2f34ba0dbaa.png">

Still seeing, no english alternative...

**Comment by sandy081** [comment]
@dbaeumer View is an extension point with following schema 

```json
{ 
    id: string;
	name: string;
	when?: string;
}
```

If an extension provides a localised string for name like `%view.name%` and when I am reading the extension point in core, do I receive localised string or a localised string object that has both original and localised value?

**Comment by sandy081** [comment]
@jrieken I think it is because the german language pack extension is not yet up to date providing the translations for these commands. Only view name is translated because the view is registered with translated string. Once the language pack extension is updated you can see both strings.

**Comment by jrieken** [comment]
ok
