### ISSUE TITLE
command 'psi-header.insertFileHeader' not found

### ISSUE THREAD

**Issue by danofa** [Microsoft/vscode#59402]
Issue Type: <b>Bug</b>

Actual results:

When trying to use Header Insert command (ctrl-p) the following message is received:
command 'psi-header.insertFileHeader' not found

In the DEV tools the following error seems to be causing it:

/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:3260 Activating extension 'psioniq.psi-header' failed: Cannot find module 'minimatch'.

Expected results:
It inserts the header.

Extension version: 1.5.1
VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:11:15.873Z)
OS version: Linux x64 4.15.0-20-generic

**Comment by franzarmas** [comment]
I have the same problem with the same versions only that I use Windows.

**Comment by Fnine59** [comment]
same!!!

**Comment by franzarmas** [comment]
[SOLVED]... solved by running "npm install" from inside the extension folder to get the necessary node_modules installed.

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
