### ISSUE TITLE
"Run Active File" does not escape spaces in the path

### ISSUE THREAD

**Issue by patrickshao** [Microsoft/vscode#59401]
1. Create a folder with a space "foo bar"
2. Put PowerShell code in "foo bar" 
3. Open in VScode. Click Teriminal > "Run Active File"

Expected result: File is executed.
Actual result: Path is split by the space with an error message not recognizing the cmdlet, function, script or operable program.

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/56109
