### ISSUE TITLE
Resizing editor windows in 4k causes contents to not render sometimes.

### ISSUE THREAD

**Issue by fkrenso** [Microsoft/vscode#59412]
Issue Type: <b>Bug</b>

The line numbers and file previews are still present, but no code will display.  Tested with at least 1 vertical split (happens with more as well) between editor and terminal.  Resizing the editor/terminal split can cause the editor contents to not render at all.

Problem still occurs with extensions disabled.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.85GB (18.80GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|40%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
yara|inf|1.3.5
MagicPython|mag|1.0.12
python|ms-|2018.8.0
cpptools|ms-|0.18.1
proto|pet|0.0.2
material-icon-theme|PKi|3.6.0
markdown-preview-enhanced|shd|0.3.5
markdown-pdf|yza|1.2.0

(10 theme extensions excluded)

</details>

**Comment by fkrenso** [comment]
Unsure if the issue is specific to larger resolutions such as 4k, but I didn't notice this problem until I upgraded my monitors.  Happens mostly when application is made wide enough to flow across 2 4k monitors.

**Comment by Tyriar** [comment]
@fkrenso does it happen when you have only editors or only terminals?

@rebornix have you seen this with your 4k monitor? It could also be related to the GPU issues in Electron 2.

**Comment by fkrenso** [comment]
@Tyriar I can only get it to manifest when there is a split view.  The split can either be two editor windows or and editor and a terminal.  Appears to occur when I resize the left or right editor down to around 160-180 columns wide.

**Comment by rebornix** [comment]
@Tyriar I didn't see any issue with rendering recently with my 4k but I can try with the steps mentioned above.
