### ISSUE TITLE
Expose SourceControlResourceState in ApiChange in vscode.git extension

### ISSUE THREAD

**Issue by IlyaBiryukov** [Microsoft/vscode#59419]
Issue Type: <b>Feature Request</b>

In `vscode.git` extension API `Repository.State.*Changes` don’t contain any data. There is nothing in the `ApiChange` class that these arrays use.

Can you please add `SourceControlResourceState` to `ApiChange` class? E.g. by either exposing their `Resource` constructor's argument as their property, or by copying `SourceControlResourceState` data into `ApiChange` class.

This is to support sharing Git source control state over a Live Share collaboration session.

VS Code version: Code - Insiders 1.28.0-insider (2558a72d6902015b142ef45c57b664ce1f09e03f, 2018-09-21T05:19:52.215Z)
OS version: Windows_NT x64 10.0.17134

**Comment by IlyaBiryukov** [comment]
cc @joaomoreno

**Comment by skprabhanjan** [comment]
@joaomoreno , which method should be followed here?
Can i just add a property and write getter and setter for the same property in ApiChange class?
Here is something similar https://github.com/Microsoft/vscode/blob/master/extensions/git/src/api/api1.ts#L15 
Thanks :)

**Comment by joaomoreno** [comment]
@skprabhanjan Please stick to `help wanted` issues.

**Comment by IlyaBiryukov** [comment]
Here is more specific API we'd need to get Git integration working in Live Share collaboration session. All these are simple wrappers of the existing properties and methods. There may be more needed, we discover them as we do the prototype work. 

1. Have `Status` enum public in `git.d.ts`.
2. Have the following new properties on `Change` in `git.d.ts`:
```typescript
	readonly resource: SourceControlResourceState;
	readonly resourceUri: Uri;
	readonly status: Status;
	readonly original: Uri;
	readonly renameResourceUri: Uri | undefined;
```
3. Have the following new methods on `Repository` in `git.d.ts`:
```typescript
	detectObjectType(object: string): Promise<{ mimetype: string, encoding?: string }>;
	buffer(ref: string, filePath: string): Promise<Buffer>;
```

I have a private change to VSCode git provider that adds all these, and I could submit a PR if you're fine with this.
