### ISSUE TITLE
[Suggest ] Save Load spyList template

### ISSUE THREAD

**Issue by djmisterjon** [Microsoft/vscode#59411]
Hi
I would like very much the ability to save a **spyList** and **reload** it when i needed.
The problem is that I like to load a different list according to my needs in some specific modules.
And adding all ~~ 50 becomes quickly unreadable and unproductive.
For now, I add them manually, but these rather boring.

![saveloadspylist](https://user-images.githubusercontent.com/24865815/46049485-a528b480-c0fc-11e8-8edc-f0ccf505dd6e.jpg)

Do you believe that it would be something easily to add?
What do you think about this
Thanks guys

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
