### ISSUE TITLE
Relavtive Links from Terminal

### ISSUE THREAD

**Issue by oggy22** [Microsoft/vscode#59416]
Issue Type: <b>Feature Request</b>

When reporting errors and warnings C# compiler provides relative paths with lines and columns. When the compilation is done through VS Terminal Window these relative paths should be understood by VS Code as appropriate links to places in the code.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

**Comment by Tyriar** [comment]
The links should work provided that the links are relative to the initial directory the terminal was opened under (see #27107). There is also an issue on Windows where the paths don't work when the root folder has a space in it (see https://github.com/Microsoft/vscode/issues/21125#issuecomment-423769407).

**Comment by oggy22** [comment]
For some reason C# guys decided to make the relative paths relative to the project they appear. Why VS Code can not work with that?

Alternatively, can it be part of "C# for Visual Studio Code (powered by OmniSharp)"?

Thanks!
