### ISSUE TITLE
Undo after save with trimTrailingWhitespace enabled moves cursor to beginning of file.

### ISSUE THREAD

**Issue by geon** [Microsoft/vscode#5942]
- VSCode Version: 1.0.0 fa6d0f03813dfb9df4589c30121e9fcffa8a8ec8
- OS Version: OS X 10.11.3 (15D21)

Steps to Reproduce:

1. Enable trimTrailingWhitespace
2. Move the cursor down a few lines
2. Type in whitespace at the end of the line
3. Save
4. Undo

The cursor will jump to the beginning of the file.

**Comment by nrkn** [comment]
I get the same thing, it's really annoying when you want to step backward or forward through the command history trying to find a certain state, and after each undo/redo it jumps to the top, making it very difficult to tell if you've gone back/forward to the right place.

**Comment by alexandrudima** [comment]
For verification: this only happens if autoSave is off. We did not record correctly the previous cursor state before applying the trim whitespace edits.
