### ISSUE TITLE
"rename" on missing property shows empty warning popup

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#59426]
![image](https://user-images.githubusercontent.com/323878/46053593-6264dd80-c0f8-11e8-8496-b5cf33c24fb3.png)

- Access a property that doesn't exist
- Press F2 to rename
- See blue popup warning but it seems to have no warning message

**Comment by mjbvz** [comment]
Root cause is https://github.com/Microsoft/TypeScript/issues/27373

But we should handle errors more gracefully here. Will fix that for September
