### ISSUE TITLE
Search not working for network drives on Mojave on Insiders

### ISSUE THREAD

**Issue by sampotts** [Microsoft/vscode#59427]
Issue Type: <b>Bug</b>

1. Mount a network drive and open in Code Insiders
2. Search for files within Code Insiders
3. Notice search hangs and does nothing (the spinner/loader just keeps animating) and only searches open files:

![image](https://user-images.githubusercontent.com/719092/46053651-14e38180-c187-11e8-9ebd-7b0130a02c2f.png)

4. Clicking "stop" also has no effect 

Local projects seem to work fine. This was also working on High Sierra prior to the Mojave upgrade. 

Here's my search log as requested:

```javascript
TRACE SearchService#search {"type":2,"folderQueries":[{"folder":{"$mid":1,"fsPath":"/Volumes/Source/drachma/src/Drachma.Web/assets/js","external":"file:///Volumes/Source/drachma/src/Drachma.Web/assets/js","path":"/Volumes/Source/drachma/src/Drachma.Web/assets/js","scheme":"file"},"fileEncoding":"utf8"}],"usingSearchPaths":true,"excludePattern":{"/Volumes/Source/drachma/**/.git":true,"/Volumes/Source/drachma/**/.svn":true,"/Volumes/Source/drachma/**/.hg":true,"/Volumes/Source/drachma/**/CVS":true,"/Volumes/Source/drachma/**/.DS_Store":true,"/Volumes/Source/drachma/**/node_modules":true,"/Volumes/Source/drachma/build":true,"/Volumes/Source/drachma/test.local":true,"/Volumes/Source/drachma/**/bower_components":true,"/Volumes/Source/drachma/src/Drachma.Core/Resources/Postcodes":true,"/Volumes/Source/drachma/src/Drachma.Web/assets/compiled":true,"/Volumes/Source/drachma/src/Drachma.Web/assets/min":true,"/Volumes/Source/drachma/libs":true,"/Volumes/Source/drachma/packages":true},"maxResults":10000,"contentPattern":{"pattern":"searchParams","isRegExp":false,"isCaseSensitive":false,"isWordMatch":false,"isSmartCase":false,"wordSeparators":"`~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?"},"useRipgrep":true,"disregardIgnoreFiles":false,"disregardExcludeSettings":false,"ignoreSymlinks":false,"previewOptions":{"matchLines":1,"charsPerLine":250}}
```

VS Code version: Code - Insiders 1.28.0-insider (fe8d9d2470ddffb9dc2da604b23f5bd8a185cd66, 2018-09-25T07:29:33.175Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz (8 x 3700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 4|
|Memory (System)|48.00GB (22.90GB free)|
|Process Argv|-psn_0_57358|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
mustache|daw|1.1.1
vscode-eslint|dba|1.6.0
es7-react-js-snippets|dsz|1.8.6
vsc-material-theme|Equ|2.4.2
prettier-vscode|esb|1.6.1
php-debug|fel|1.12.6
vscode-styled-components|jpo|0.0.22
vscode-apache|mrm|1.1.1
vscode-less|mrm|0.6.3
language-gettext|mro|0.1.1
PowerShell|ms-|1.8.4
debugger-for-chrome|msj|4.10.1
language-liquid|nei|0.0.3
vscode-versionlens|pfl|0.21.2
polacode|pnp|0.2.2
ejs-language-support|Qas|0.0.1
stylelint|shi|0.43.0
babelrc|wad|1.0.0
vscode-todo-highlight|way|1.0.4
twig|wha|1.0.2
vscode-import-cost|wix|2.9.0

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
@sampotts any output in the developer console? Open Help > Toggle Developer TOols

**Comment by sampotts** [comment]
Hey @bpasero, I did that too but nope only that trace log I included sadly.

**Comment by roblourens** [comment]
This works for me, thanks for the log, do you see a long line right after that says `SearchService#search rg [...]`?

Can you try running `ls /Volumes/Source/drachma/src/Drachma.Web/assets/js` in a terminal to be sure that you can get a result? And is it very slow?

**Comment by sampotts** [comment]
The `ls` was fast - even `ls -R`. Regardless, I just updated to 10.14.1 Beta (18B45d) and it seems to be working as before. I did try rebooting prior of course.

**Comment by roblourens** [comment]
Thanks for the follow up.
