### ISSUE TITLE
Error '<stdio.h> file not found' occured when editing document in workspace

### ISSUE THREAD

**Issue by Warren1732** [Microsoft/vscode#59422]
When I edit inside a folder(which contains .vscode folder and all neccessary .json files), no errors occured.But when I create a new workspace that includes the former folder and write '#include <stdio.h>' ,the '<stdio.h>' is highlighted and tells me '<stdio.h> file not found'. I cannot figure out the problem.
Please do help me.

**Comment by Warren1732** [comment]
But it seems that I can still compile my code and run it in the terminal.

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
