### ISSUE TITLE
The window has crashed

### ISSUE THREAD

**Issue by losthua** [Microsoft/vscode#59424]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.17134
- Extensions: none
---
After opening 1.5g of SQL and closing, this happens every time you start。

![image](https://user-images.githubusercontent.com/33113433/46052724-31c18a00-c172-11e8-9841-a86ed7b95b64.png)

![image](https://user-images.githubusercontent.com/33113433/46052740-3f770f80-c172-11e8-8a00-1a74e45cb1a6.png)

Steps to Reproduce:

1. After opening 1.5g of SQL and closing
2.Unsaved close

**Comment by rebornix** [comment]
@losthua  can you please download the latest version and try again? We don't support this large file with version 1.16.

**Comment by losthua** [comment]
Thanks，removed C:\Users\XX\AppData\Roaming\Code\Backup file,The normal.

**Comment by rebornix** [comment]
Great!
