### ISSUE TITLE
TSLint flags don't all work naturally in VSCode

### ISSUE THREAD

**Issue by jpike88** [Microsoft/vscode#59425]
I know this is technically a TS/TSLint issue at its core, but its the TSLint plugin that has the shortcoming and that may be a VSCode issue too.

https://github.com/palantir/tslint/issues/3399
The above issue states that type checking is no longer done by TSLint, rendering some of its flags useless unless its paired with a TS compilation step, in the interests of performance

Then, on the TS side:
https://github.com/Microsoft/TypeScript/issues/13376
TS wants to distance itself from this as it considers it outside the scope of what TS would care about.

VSCode seems to be real point of failure here. Shouldn't TSLint be given whatever information it needs from TS information piped through VSCode in order to allow flags that require type checking to function correctly?

**Comment by mjbvz** [comment]
This not really a vscode issue. The TSLint extension needs to coordinate a way to consume type info from typescript running inside vs code. See the effort here for an example of how this can be done by making tslint a typescript server plugin: https://marketplace.visualstudio.com/items?itemName=eg2.ts-tslint
