### ISSUE TITLE
View headerBorder is not applied consistently

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#59439]
This seems to be a long regression from https://github.com/Microsoft/vscode/issues/32003 that now surfaces stronger since I introduced a new color `sideBarSectionHeader.border` (from https://github.com/Microsoft/vscode/issues/36674). Once set (e.g. to red), notice how the color is not applied in some viewlets for the second view or wrongly for the first view:

**Explorer (after a reload)**
![image](https://user-images.githubusercontent.com/900690/46064975-2b7ede00-c171-11e8-95b5-b24331f06463.png)

**Extensions (wrongly shows it for first view)**
![image](https://user-images.githubusercontent.com/900690/46065021-47827f80-c171-11e8-8be9-af3f72f535a8.png)

**Comment by sandy081** [comment]
@bpasero May I know how it is a regression? I think the new colour you added is not completely implemented. 

Looking at the implementation, new colour is added only from second view. But there is missing implementation to remove/add the colour of existing view when a view is added or removed on the top.

**Comment by bpasero** [comment]
@sandy081 you refer to this I guess?

https://github.com/Microsoft/vscode/blob/5f53ed3/src/vs/workbench/browser/parts/views/panelViewlet.ts#L326

**Comment by sandy081** [comment]
@bpasero Yes.
