### ISSUE TITLE
Possible to have the custom checkboxes global

### ISSUE THREAD

**Issue by beastdestroyer** [microsoft/vscode#59432]
Issue Type: UI

In light of the new Settings GUI, the beautiful custom checkboxes appear. This is a small issue so, I don't mind if it's closed, however in the Debug panel, Welcome screen etc., I was wondering if you could replace the default checkboxes with the new ones.

**Comment by beastdestroyer** [comment]
Not related.

**Comment by roblourens** [comment]
We have discussed it but other people prefer a native control wherever possible.

**Comment by beastdestroyer** [comment]
Do you think it would be worth it to have a toggle such as `Toggle native control style` similar to how there is a toggle for menu style?

**Comment by roblourens** [comment]
Hm, possibly.
