### ISSUE TITLE
debt - is IContextViewService just hot air?

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#5943]
I see we have a [`IContextViewService`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/contextview/browser/contextView.ts#L16) and I see it being injected but somehow I don't anyone actually using it in the sense of calling methods except for the content _menu_ service.

**Comment by jrieken** [comment]
unsure if this is @joaomoreno or @bpasero

**Comment by joaomoreno** [comment]
It used to be used by more UI contributions...

Now, if I'm not mistaken, it is used by menus and [the feedback widget](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/feedback/electron-browser/feedbackStatusbarItem.ts#L59), although the use in the latter does have a bit of a type mess...

What do you suggest?

**Comment by jrieken** [comment]
nuke it

**Comment by joaomoreno** [comment]
Do you have any suggestion how?

**Comment by jrieken** [comment]
Yeah, by removing all references that actually do nothing and then see what's left. It seems like nothing talks about that service interface but if they talk about [this](https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/contextview/contextview.ts#L41) abstraction in `browser/ui/contextview`. I am not saying it must be removed but the existence of the service seems somewhat artificial

**Comment by joaomoreno** [comment]
Actually it is also used by the InputBox down in base: for when the user types an invalid regex for example. It is hidden away an identical interface `ContextViewProvider` since services don't exist down there.
