### ISSUE TITLE
Weird glitch when typing a ~ inside the integrated terminal

### ISSUE THREAD

**Issue by warpdesign** [microsoft/vscode#59438]
- VSCode Version: 1.28.0-insiders (fe8d9d2470ddffb9dc2da604b23f5bd8a185cd66)
- OS Version: OSX 10.12.6

Steps to Reproduce:

1. Open the integrated terminal
2. Type the ~ character (on a French keymap you need to press `alt + n`)

What happens:

Until you press another character, the ~ appears shifted to the right. Once another key has been pressed, it's shifted to the left again.

Note: this does not happen when typing this character in VSCode in an opened file, only inside the integrated terminal.

![tilde](https://user-images.githubusercontent.com/199648/46064925-05f1d480-c171-11e8-9f7a-51fc78e34765.gif)

Both Editor & Terminal are using the same font-family: `Monaco`.

**Comment by Tyriar** [comment]
I can repro, alt+n appears to trigger an IME which is why it looks different, this also happens in the editor. So I guess the underlying issue is that the IME box is not in the correct position.

**Comment by hugmanrique** [comment]
I don't know if related, but typing the tilde character (~) on the integrated terminal using a Spanish (ES-ES) keyboard inserts two fours (4) and the tilde, instead of the expected single four and the tilde.

i.e.

```
AltGr+4 twice
Expected: ~~
Output: 44~
```

It seems like VS Code ignores the state of AltGr when inserting the first four.

**Comment by Tyriar** [comment]
Upstream: https://github.com/xtermjs/xterm.js/issues/2151

**Comment by Tyriar** [comment]
Seems to work now

**Comment by warpdesign** [comment]
@Tyriar I am still reproducing with VSCode 1.38.1 on OSX Mojave. What version are you using?

![bugVScode](https://user-images.githubusercontent.com/199648/66434418-cff15c80-ea22-11e9-806f-5093515f873d.gif)

**Comment by Tyriar** [comment]
10.14.6 Mojave

![Kapture 2019-10-09 at 6 53 55](https://user-images.githubusercontent.com/2193314/66487723-ad326880-ea61-11e9-9c4c-b950ac93e6cb.gif)

Using this layout:

<img width="563" alt="Screen Shot 2019-10-09 at 6 54 55 AM" src="https://user-images.githubusercontent.com/2193314/66487757-ba4f5780-ea61-11e9-9d7e-552de3e83359.png">

**Comment by warpdesign** [comment]
Which keys do you have to press to make a `~` with this keymap? That's
weird. I'll try with a MacBook to see if I can reproduce it there too. It
may depend on the keymap used.

Le mer. 9 oct. 2019 à 15:58, Daniel Imms <notifications@github.com> a
écrit :

**Comment by warpdesign** [comment]
That's the layout I am using:

![Capture d’écran 2019-10-09 à 18 07 46](https://user-images.githubusercontent.com/199648/66499258-c0742100-eabf-11e9-882a-d5172e209f33.png)

**Comment by Tyriar** [comment]
@warpdesign that was with alt+n in the gif

**Comment by maxtorete** [comment]
Hi,

The issue #73876 was marked as duplicated of #68262, which was marked as duplicated of this one. This issue seems to be fixed, but the problem with accented characters as described in #73876 is still there.

Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:40.634Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.3.5-200.fc30.x86_64 (Fedora 30)

**Comment by loganmzz** [comment]
I wtill have the issue with following version:

```
Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 6.1.7601
```

**Comment by Tyriar** [comment]
People still having this issue please try repro and report upstream https://github.com/xtermjs/xterm.js/issues

There are a few issues open related to IMEs currently: https://github.com/xtermjs/xterm.js/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Aarea%2Fime+
