### ISSUE TITLE
Automatic Type Aquisition not working

### ISSUE THREAD

**Issue by JacksonKearl** [Microsoft/vscode#59436]
Issue Type: <b>Bug</b>

This may be upstream, but I have lately been forced to manually install all typings I use, even for popular modules (i.e. express). I've tried clearing the TypeScript typings cache, toggling the VS Code `typescript.disableAutomaticTypeAcquisition` setting, and forcing ATA to retrigger by adding and removing the modules from my `package.json`, but I still get an error on all imports of express telling me to install `@types/express` (which I'd rather not litter my (dev)dependencies with).

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:04:11.329Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (4.77GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
sublime-commands|Zar|0.1.0
gitlens|eam|8.5.6
tslint|eg2|1.0.39
vscode-npm-script|eg2|0.3.5
haskell-linter|hoo|0.0.6
c-cpp-perf-tools|jac|0.0.2
latex-workshop|Jam|5.10.2
language-haskell|jus|2.5.0
python|ms-|2018.8.0
cpptools|ms-|0.18.1
debugger-for-chrome|msj|4.10.1
code-spell-checker|str|1.6.10
haskelly|UCL|0.5.4

</details>

**Comment by JacksonKearl** [comment]
Also, for some reason my typings cache at `~/Library/Caches/Typescript/` is not repopulating at all since clearing it. The only module in its `node_modules` is `types-registry`.

**Comment by JacksonKearl** [comment]
Possibly related: https://github.com/Microsoft/TypeScript/issues/27302

**Comment by JacksonKearl** [comment]
Getting this in latest insiders as well, with additional strange error in package.json: 
<img width="579" alt="image" src="https://user-images.githubusercontent.com/8586769/46092891-e44e1880-c183-11e8-9e27-978e60cd6968.png">
I do not have that module installed or even listed anywhere in my package.json

**Comment by mjbvz** [comment]
Can you please try collecting the TS Server typings install log:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a folder with a `ti-xxx.log` file in it


To answer your questions:

* ATA should kick in for javascript when we see an import for a module like `express` that has an `@types` package.
* You generally should not need to manually install `@types` packages for javascript (but you do need to manage `@types` for typescript)

**Comment by JacksonKearl** [comment]
I did not realize I need to manually install types for TS, that was the issue. Thanks!
