### ISSUE TITLE
Go To Implementation not working with Python 

### ISSUE THREAD

**Issue by wesleybowman** [Microsoft/vscode#59434]
- VSCode Version:  1.27.1
- OS Version: Ubuntu 18.04

Steps to Reproduce:

Create a new python file and use the following code:
```python
class TestClass:

    def run_this(self):
        self.try_and_click_through()

    def try_and_click_through(self):
        print('Does this work?')


def test_functions():
    does_this_work()


def does_this_work():
    print('How about this?')
```

If I try "Go To Definition" on either `self.try_and_click_through()` or `does_this_work()`, it takes me to the definition. However, once I am at the definition, I cannot "Go To Implementation". I have tried both using the "Ctrl + F12" as well as manually trying to do it. I know you can use "Find All References" to do something similar, but it's not the same. 

I think ideally this would work with a "Ctrl + right click", like "Go To Definition" but in reverse, if you are already at the definition.

Does this issue occur when all extensions are disabled?: Yes

(This is the last hurdle I have come across when trying to migrate from PyCharm to VS Code.)

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
