### ISSUE TITLE
Dark mode of Chinese input method (IME)

### ISSUE THREAD

**Issue by HaloWang** [Microsoft/vscode#59433]
- VSCode Version:  1.27.2 (1.27.2) / Version 1.28.0-insider (1.28.0-insider)
- OS Version:  macOS Mojave 10.14(18A391)
- macOS system preferences: dark appearance

Steps to Reproduce:

1. Open vscode, set the color theme to **Dark+**
2. Switch input method to **Pinyin - Simplified**
3. Type any words
4. The appearance of input method this light mode, but I expect dark mode.

<img width="365" alt="screen shot 2018-09-26 at 1 49 16 pm" src="https://user-images.githubusercontent.com/7344724/46059710-0602cc00-c193-11e8-8353-a94111b2101c.png">

Does this issue occur when all extensions are disabled?: For 1.28.0-insider, No.

**Comment by HaloWang** [comment]
<img width="238" alt="screen shot 2018-09-26 at 1 54 25 pm" src="https://user-images.githubusercontent.com/7344724/46059896-ba9ced80-c193-11e8-92a0-fec382918f7b.png">
This is what I can see in Xcode

**Comment by bpasero** [comment]
Via https://github.com/Microsoft/vscode/pull/59742
