### ISSUE TITLE
TypeScript shows duplicated suggestions

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#59437]
* have the snippet below
* trigger intellisense inside the toString-method
* :bug: toString appears twice, one insert this.toString, the other just toString
* the label or details should outline the difference

<img width="449" alt="screenshot 2018-09-26 at 09 33 00" src="https://user-images.githubusercontent.com/1794099/46064292-536d4200-c16f-11e8-9401-ae5419194fde.png">

```ts
class FooClass {

    field = 1234;
    readonly fold = true


    toString(): void {
        
        
    }
}
```

**Comment by songleilei999** [comment]
erewr

**Comment by mjbvz** [comment]
The second suggestion (the one without the `this.`) is for the DOM window object's `toString` method. You can reference `toString` as a global function in browsers contexts

**Comment by mjbvz** [comment]
Reopen as your point about displaying these better still stands

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/27487 to track this upstream
