### ISSUE TITLE
Custom Window Issue

### ISSUE THREAD

**Issue by AlirezaDadrass** [Microsoft/vscode#59447]
Hi.
I set vs code window style to custom and then i saw menu bar in debug console.
Screenshot:
![screenshot 4](https://user-images.githubusercontent.com/18461364/46070155-f468f680-c189-11e8-8fd2-96e689034ae3.png)

Now how i must fix that?
Thank you.

**Comment by AlirezaDadrass** [comment]
No, it's always there. Sometimes the contents of the console are displayed

**Comment by AlirezaDadrass** [comment]
> We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
> 
> * macOS: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/VSCode-darwin-exploration.zip)
> * Linux: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/code-exploration_1.28.0-1536650436_amd64.deb)
> * Windows: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/VSCodeUserSetup-x64-1.28.0-exploration.exe)

Thank you!
this version is OK.

**Comment by bpasero** [comment]
Ok good. You can use the old version again with "`code --disable-gpu`" and it should also be fine.

**Comment by AlirezaDadrass** [comment]
Thanks a lot.
