### ISSUE TITLE
Simplify suggest result

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#5945]
At some point, @jrieken, you mentioned there it no more need to return [an array of arrays of suggestions](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/suggest/common/suggest.ts#L24), but one array would be enough. How can we get there?

**Comment by jrieken** [comment]
That's as simple as its gets. Before, we returned an array of arrays but now it's an array of suggest results. We need the latter to have a back reference to the provider/support that computed the individual suggestions when we ask for details and when asking again in case of incomplete results. 

see https://github.com/Microsoft/vscode/commit/5723a2d97f7db963d417a552c83d91808c5d9c8b#diff-518e736f78c3288400a5d064bb875c59

**Comment by joaomoreno** [comment]
Alright, thanks. I thought we hadn't go through it yet, I was waiting on it.
