### ISSUE TITLE
loadedSource event unable to add entry to Loaded Scripts panel when source name / path contains % character

### ISSUE THREAD

**Issue by gjsjohnmurray** [Microsoft/vscode#59457]
- VSCode Version: 1.27.2
- OS Version: Windows 10, x64

Steps to Reproduce:

Revise the vscode-mock-debug tweak previously documented in #59281 to make it prefix the source name with %

			if (matches && matches.length === 2) {
				const src = new Source(`\%YJM${matches[1]}.txt`, `debug:\%YJM${matches[1]}.txt`);
				this.sendEvent(new LoadedSourceEvent('new', src));
				reply = src.path + ' entry added to Loaded Scripts panel';
			}

2. Test the extension. In the REPL field enter 'ls 1' followed by 'ls 2'. this time nothin appears even after the second source is added.

**Comment by weinand** [comment]
This works fine in the latest:
![2018-10-29_22-34-13](https://user-images.githubusercontent.com/1898161/47681831-d0566600-dbca-11e8-9726-12a316f8bb8a.png)

**Please note**: the "path" attribute must be a file-system path, not a url with scheme "debug".

**Comment by weinand** [comment]
the "debug" scheme is an internal concept that is not documented and there should no need to use this in extensions. VS Code will send a "sourceRequest" for whatever source you pass to VS Code.

**Comment by gjsjohnmurray** [comment]
It seems the DA only gets a "sourceRequest" if a sourceReference > 0 is set on the instance of Source that the DA originally gave to the client (e.g. as part of a StackFrame). That behaviour isn't a problem now that I understand it and am assigning positive sourceReference values.
