### ISSUE TITLE
Text search should support context

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#59458]
We should consider something like the `--context` option (https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#common-options) instead of the current preview options. They currently don't allow to show a multi line context around a match and make implementing a textual representation of search results very hard...

**Comment by roblourens** [comment]
I would add

```ts
export interface TextSearchPreviewOptions {
    contextLines?: number;
}
```

**Comment by jrieken** [comment]
Yeah, that would be nice but might also be problematic. When having `context: boolean` the search engine can decide, e.g. show 5 lines (two above & below) for normal matches but only show parts of a line for monster lines

**Comment by roblourens** [comment]
Sometimes it's up to the user how much context should be shown. In Atom I can change leading and trailing context via the UI independently.

If you are showing results as text with context, is it annoying that multiple results on one line are given as multiple result objects, possibly with overlapping previews? Should the API keep the one-result-per-line model instead?

One difficulty here is when you have a long line with one match at the beginning and one at the end.

**Comment by jrieken** [comment]
> Should the API keep the one-result-per-line model instead?

That means to show more context (line above/below) the file needs to opened and I don't that feasible...

**Comment by roblourens** [comment]
I'm referring to something else, not context lines. When you have two matches on the same line, the API will send two result objects. For your extension, it might be better if you can get a single result object that indicates the two matches. That's what I mean by one result per line.

Kai had the suggestion of just using exactly ripgrep's format: https://burntsushi.net/stuff/libripgrep/doc/grep_printer/struct.JSON.html

**Comment by roblourens** [comment]
Please verify by calling the findTextInFiles API from an extension with the context options, check that you get something reasonable.
