### ISSUE TITLE
Scheme is missing when clicking in source hover

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#59469]
Issue Type: <b>Bug</b>

![sep-26-2018 15-47-15](https://user-images.githubusercontent.com/9205389/46084238-7fa2b600-c1a3-11e8-8cd7-029bf31e6a58.gif)

VS Code version: Code - Insiders 1.28.0-insider (5ba5f14c954682df46f04a541f0b272166605366, 2018-09-26T07:25:01.336Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|33%|

</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
unique-lines|bib|1.0.0
ssh|chr|0.0.4
vscode-eslint|dba|1.6.0
Spot|der|0.4.0
ghlink|dt|1.0.2
remotehub|eam|0.2.0
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.39
vscode-pull-request-github|Git|0.1.6
rest-client|hum|0.19.1
solidity|Jua|0.0.46
theme-karyfoundation-themes|kar|18.2.1
graphql-for-vscode|kum|1.12.1
vscode-azureappservice|ms-|0.9.1
vscode-azurefunctions|ms-|0.11.0
vscode-cosmosdb|ms-|0.8.0
azure-account|ms-|0.4.3
azurecli|ms-|0.4.2
github-issues-prs|ms-|0.9.1
PowerShell|ms-|1.8.4
debugger-for-chrome|msj|4.10.1
vscode-docker|Pet|0.3.1
vscode-versionlens|pfl|0.21.2
vscode-workspacecontains-canary|rob|0.0.2
vscode-open-in-github|sys|1.7.0
ayu|tea|0.16.0
azure-iot-toolkit|vsc|1.4.0

</details>

**Comment by mjbvz** [comment]
I don't think these links ever worked properly so the bug is that we now log errors too. Will look into this for October

**Comment by jrieken** [comment]
The error logging is me because we want to educate people to not create uris that lack a scheme

**Comment by chrmarti** [comment]
The error is gone, marking verified.
