### ISSUE TITLE
Ubuntu hotkeys

### ISSUE THREAD

**Issue by kbytin** [Microsoft/vscode#5946]
- VSCode Version: 1.0.0
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Ctrl+Shift+Alt+Down - default ubuntu hotkeys to move window to other desktop

I set Ctrl+Shift+D for me right now, but it will be nice to have OS dependency of hotkeys out of the box

**Comment by Tyriar** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/509
