### ISSUE TITLE
vscode keeps saying password authentication is not avaliable

### ISSUE THREAD

**Issue by b3rgman** [Microsoft/vscode#59468]
- VSCode Version: 1.27.2
- OS Version: W10

Steps to Reproduce:

1. Git Setup personal access token
2. Add token
3. Clone Repo
4. Commit changes
5. Push Changes

When pushing changes it tells me that Password authentication is not available for github operations.  This was working yesterday.  Now this morning it is not working.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by b3rgman** [comment]
Personal Access token was working then on a push it asked me to enter windows credentials.  I canceled it and ever since then it has been asking.  I have:

1. Delete the Repo
2. removed the token
3. added the token
4. deleted the work space
5. Cloned the repo
5. "Revo Uninstalled" vscode
7. rebooted.

The same result is present.

**Comment by joaomoreno** [comment]
Can you show me screenshots of what you mean? I'm not sure I understand any of the steps, are they in VS Code? In git? In GitHub for Windows?

**Comment by b3rgman** [comment]
Hi @joaomoreno  
These are all in VC Code.  I installed the github module
![image](https://user-images.githubusercontent.com/33910436/46142439-fd5ad600-c224-11e8-814a-cafefef270e9.png)

I added the personla access token

![image](https://user-images.githubusercontent.com/33910436/46142460-0ba8f200-c225-11e8-8692-45f6843f62a0.png)


I cloned my repo
![image](https://user-images.githubusercontent.com/33910436/46142484-23807600-c225-11e8-94db-4d716f5b1682.png)


I made a change and did git commit

![image](https://user-images.githubusercontent.com/33910436/46142517-3eeb8100-c225-11e8-9f02-bf3638ca4acb.png)


I pushed the code and get this message

![image](https://user-images.githubusercontent.com/33910436/46142540-532f7e00-c225-11e8-931b-c7e81b56031b.png)


![image](https://user-images.githubusercontent.com/33910436/46142563-617d9a00-c225-11e8-984f-fcd2e843fd54.png)



My token is there. as I can remove it

![image](https://user-images.githubusercontent.com/33910436/46142576-6f331f80-c225-11e8-8339-26ea18e3b88d.png)



I hope this makes it a little more clear.   I followed the same steps on my laptop and it is still working.

**Comment by joaomoreno** [comment]
Got it, please file an issue to https://github.com/KnisterPeter/vscode-github

**Comment by b3rgman** [comment]
Thanks @KnisterPeter.

@joaomoreno  Please re open and explain how this worked in the past and it did not.

**Comment by joaomoreno** [comment]
@b3rgman Can you git push from the command line?

**Comment by joaomoreno** [comment]
@b3rgman Can you git push from the command line?

**Comment by b3rgman** [comment]
Hi @joaomoreno .  From command line.

![image](https://user-images.githubusercontent.com/33910436/46406763-9a60b780-c6da-11e8-92d6-0907161d8b71.png)

**Comment by b3rgman** [comment]
@joaomoreno ,
Any update?  This is now happening with a colleague of mine now.  same issue.  Worked.  Then all of a sudden didnt.

**Comment by joaomoreno** [comment]
I don't understand whether you can push via the command line or otherwise. What is the result of that screenshot?

**Comment by b3rgman** [comment]
The result of the screenshot is I get the same result when using VSC.  It is asking for a token.  Which I have already set.

**Comment by joaomoreno** [comment]
And does the push work?

**Comment by b3rgman** [comment]
The push does not work.  Please see above image.   IT wants me to reference the token.  Which I have.  Please note this did work for a few days. Then stopped.

**Comment by joaomoreno** [comment]
Right. VS Code simply runs `git push` in the background. So if `git push` doesn't work, VS Code won't work either. You need to restart the credential configuration setup for whatever repository you're using.

> This was working yesterday. Now this morning it is not working.

I'm not sure what has changed, but it was definitely not VS Code. I would reach out to the developers of whatever github authentication app you are using.

**Comment by b3rgman** [comment]
@joaomoreno  so if I understand you correctly, VS Code uses git bash for the git portion?

**Comment by joaomoreno** [comment]
It uses Git for Windows and spawns `git.exe` within.

**Comment by b3rgman** [comment]
Have found a way around this.  Continue to use VSC and just do the push with GitHub Desktop.   VSC push seems flaky.  I had it working on 2 machines and not it will no push.  No changes were made.  Also had a colleague have the same issue.
