### ISSUE TITLE
[json] Warning when opening settings.json

### ISSUE THREAD

**Issue by sguillia** [Microsoft/vscode#59470]
Issue Type: <b>Bug</b>

Related to: #36197, #12588, #15524 

This message appeared in my Problems tab when editing `settings.json`:

```
Problems loading reference 'http://json-schema.org/draft-07/schema': Unable to load schema from 'http://json-schema.org/draft-07/schema': Unable to connect to http://json-schema.org/draft-07/schema. Error: connect ETIMEDOUT 185.199.111.153:80
```

- I don't care about the json schema not being loaded
- My proxy is well configured
- Even if it wasn't, I could be running without internet connection
- I have no way to clear the problems tab (and you denied feature request https://github.com/Microsoft/vscode/issues/15524)

Could you please provide a way to get this message out of my problems tab?

VS Code version: Code - Insiders 1.28.0-insider (5ba5f14c954682df46f04a541f0b272166605366, 2018-09-26T07:32:21.753Z)
OS version: Windows_NT x64 10.0.15063

**Comment by aeschli** [comment]
I agree that there shouldn't be any warnings when opening settings.json. I will provide a fix for this by bundling `draft-07/schema` as we did with `draft-04/schema`
