### ISSUE TITLE
Its unclear what the status/clone uri handler from git is supposed to do

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#59474]
Testing #59244 on Windows

- Ran `explorer vscode-insiders://vscode.git/status` in an external command prompt, got the dialog on "Allow an extension to open an URL" in VS Code, I press "Open". Nothing happens. Is the status expected to show up somewhere? What is the expected outcome?

- Ran `explorer vscode-insiders://vscode.git/clone?url=https://github.com/ramya-rao-a/test-extension`. It opened the browser for the url. No cloning happened. No dialog opened in VS Code.

**Comment by sandy081** [comment]
@joaomoreno Does the git extension handles these URLs?

**Comment by ramya-rao-a** [comment]
@sandy081 We noticed that the cloning worked as expected when on Mac

**Comment by sandy081** [comment]
Assigning to @joaomoreno for URL handling in Git.

**Comment by joaomoreno** [comment]
The git extension doesn't handle `/status` at all. `/clone` is the only thing that it handles: https://github.com/Microsoft/vscode/blob/master/extensions/git/src/protocolHandler.ts#L22 That URI is just a hypothetical example of an extension URI.

`vscode-insiders://vscode.git/clone?url=https://github.com/ramya-rao-a/test-extension` is not a valid URI. You must encode the uri component. URI should be `vscode-insiders://vscode.git/clone?url=https%3A%2F%2Fgithub.com%2Framya-rao-a%2Ftest-extension`.
