### ISSUE TITLE
Should the '_workbench.downloadResource' command allow overwriting existing files?

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#59473]
Testing #59112

**Repo**
Execute the `_workbench.downloadResource` command twice with the same target folder on disk but different resources to download

**Expected**
Unclear what should happen here since we are trying to overwrite an existing file

**Actual**
The resource on disk is overwritten when the command in invoked the second time

**Comment by sandy081** [comment]
Does the resources have the same name?
