### ISSUE TITLE
Zooming in and out rapidly causes weird settings behavior

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#59478]
I did the following:

1. Zoom in twice
2. Zoom out twice

And repeated in quick succession, I noticed the following:

- I got a settings is dirty error, settings.json was marked as dirty but there wasn't any undo stack and it wasn't different to what's on disk
- The theme reverted to the default theme, settings.json still said my custom theme (sapphire), zooming in/out again fixed this back
- After the theme was fixed I noticed that the colors on TODO/FIXME here which define are defined by the surrounding block are incorrect:

   ![image](https://user-images.githubusercontent.com/2193314/46100461-4e63bf00-c17e-11e8-9887-f1ed89ac276b.png)

**Comment by AdrienViala** [comment]
I lost my colour theme settings while zooming out rapidly. 

 * Versions :
Version: 1.30.2 (system setup)
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:53:57.820Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT ia32 10.0.14393

![image](https://user-images.githubusercontent.com/39263057/52065453-d74c9600-2576-11e9-918d-3dd59f54eb4c.png)

* Steps : 

1. Set a coloured theme
2. Press Ctrl+`-` on windows (zooms out) multiples times at high frequency
3. Alternatively, just keep the `-` touch down until max zoom out is reached
4. Keep doing it with Ctrl+`-` and Ctrl+`+` until theme flashes to default dark+ 
5. If you are lucky, your theme will reset after a very short while. If you are not so lucky, you should be reading this issue :) 

Probably relevant log :

ERR Cannot read property 'getValue' of null: TypeError: Cannot read property 'getValue' of null
    at c (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3611:867)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3612:51
    at e.fire (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:189:512)
    at e.applyTheme (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4478:272)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4476:987
    at <anonymous>

**Comment by sandy081** [comment]
This is same as https://github.com/Microsoft/vscode/issues/47763.
