### ISSUE TITLE
Issues with VS Code that seems to affect MacBook Pro USB Port

### ISSUE THREAD

**Issue by michaelamican** [Microsoft/vscode#59476]
- VSCode Version: 1.27.2
- OS Version: macOS Sierra v 10.12.6 on MacBook Pro

So, really bizarre issue. I downloaded VS Code and had multiple instances of a terminal running (Angular project with Mongo), with a second screen connected to the USB port closer to the user (by the `~ key). I step away, computer goes into sleep mode, I come back, USB not connecting and the icon for VS Code has turned into a '?'. 

This has happened four times now. The only solution I've found is to turn the computer off and on twice. Is it a compatibility issue on your end, or on macOS?

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bpasero** [comment]
I do not see how VSCode has a bug here, I suggest to ask the OS company.
