### ISSUE TITLE
should we merge IMessageService#setStatusMessage and IStatusBarService?

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#5947]
We have a [IStatusBarService](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/statusbar/common/statusbarService.ts#L45) and [IMessageService.setStatusMessage](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/message/browser/messageService.ts#L135) which looks like duplication or re-exporting. Should we move the setStatusMessage feature into the status bar service?

**Comment by jrieken** [comment]
fyi @alexandrudima as the only consumer of `setStatusMessage`

**Comment by alexandrudima** [comment]
:+1: I can happily call into any service

**Comment by bpasero** [comment]
Yes, we should and it will probably fix https://github.com/Microsoft/vscode/issues/5688. I am merging this issue into https://github.com/Microsoft/vscode/issues/5688
