### ISSUE TITLE
Output: opening panel with focus:true no longer puts focus to editor within

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#59471]
Every other panel gets the focus nicely, but when you do View > Output when the output panel is not visible, the editor does not get focus. Maybe a regression from the delayed output handling?

This makes the recently changed toggle-panel action behaviour a bit odd because that action requires focus to really end up within the panel to work nicely. Moving to September thereby.

**Comment by sandy081** [comment]
@bpasero This is not a regression from last milestone. I can reproduce this also on the stable. Toggling the panel is not focusing the Output panel editor.

**Comment by sandy081** [comment]
I am afraid the changes are not small. Do we need the fix for this milestone?
