### ISSUE TITLE
Notification progress messages are not read by screen reader

### ISSUE THREAD

**Issue by cait1inhennessy** [Microsoft/vscode#59486]
For notifications created with the `vscode.window.withProgress` API, NVDA only reads the title and not the progress messages.  For example, when we show this notification in Live Share, NVDA reads "Sharing workspace" but does _not_ read "Share workspace starting".

![capture](https://user-images.githubusercontent.com/16658549/46105782-c8e70b80-c18b-11e8-9bef-e608b395d415.PNG)

Platform: Windows 10
VSCode: 1.28.0-Insider

**Comment by bpasero** [comment]
I am now announcing the notification message again whenever it changes.
