### ISSUE TITLE
[Insiders] launch.json is no longer generated when .Net Core environment is selected from dropdown

### ISSUE THREAD

**Issue by jramsay** [Microsoft/vscode#59487]
Version: 1.28.0-insider (user setup)
Commit: 5ba5f14c954682df46f04a541f0b272166605366
Date: 2018-09-26T07:32:21.753Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
OS Version: Win 10

Steps to Reproduce:

1. Open a basic C# Console App in VS Code and open a C# file Program.cs
2. Select "Not Now" when you get a prompt to add required assets
![image](https://user-images.githubusercontent.com/8161247/46106511-c38ac080-c18d-11e8-8a3a-675fb4145496.png)

No launch.json will be generated

3. Set a breakpoint in Progrma.cs and start debugging (No configurations). The Select Environment dropdown will appear. Select ".Net Core"

![image](https://user-images.githubusercontent.com/8161247/46106676-427ff900-c18e-11e8-94af-9f966f0851bc.png)

4. Nothing happens. In VS Code stable a launch.json would be created with the new configuration and then the user would be able to start debugging.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by isidorn** [comment]
@jramsay thanks for the great steps.
I have created a PR in the C# extension repository which fixes this, along with the analysis of the issue https://github.com/OmniSharp/omnisharp-vscode/pull/2558
Let's keep this issue open to track if the extension merges this, if they do not than we can do some ugly workaround in vscode which I would prefer not to do.

**Comment by isidorn** [comment]
The PR looks good and it is going to get merged it seems. I will provide the same PR for C++.
Closing this issue since no changes on the vscode side are required.

**Comment by isidorn** [comment]
Verifier: this can only be verified once the C# updates their extension.

**Comment by sbatten** [comment]
verified by packaging https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.16.2 and installing manually
