### ISSUE TITLE
[VS Live Share] Cannot find a program to debug when no launch.json present

### ISSUE THREAD

**Issue by jramsay** [Microsoft/vscode#59485]
Version: 1.28.0-insider (user setup)
Commit: 5ba5f14c954682df46f04a541f0b272166605366
Date: 2018-09-26T07:32:21.753Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
OS Version: Win10

Steps to Reproduce:

Install latest VS Live Share extension:
1. VS Code Host: Open a Node.js console app with no launch.json and share
 and set a breakpoint in js file
2. VS Code Guest: join the collboartion session and attempt to start debugging.
![image](https://user-images.githubusercontent.com/8161247/46105722-9ccb8a80-c18b-11e8-864e-d6a35b3bbecf.png)

Does this issue occur when all extensions are disabled?: No

The cause of the issue:

@aeschli : It looks like getLastActiveWorkspaceRoot now uses a “file” SchemeFilter (add scheme filter to getLastActiveFile) and since our remote VS Live Share resources have the “vsls” scheme undefined is being returned instead of the actual folder resource 
![image](https://user-images.githubusercontent.com/8161247/46105858-fb910400-c18b-11e8-9a39-a08223a571a3.png)

**Comment by isidorn** [comment]
@jramsay thanks a lot for this great investigation! Really appreciate it.

**Comment by alexr00** [comment]
On my host, if I just start debugging it runs the javascript file and breaks in at my break point. On the guest, it create a launch.json then a notification and doesn't run. When I try to start debugging again now that I have this launch.json this notification shows:

![image](https://user-images.githubusercontent.com/38270282/46235205-23b86880-c32e-11e8-8ab2-0d1bbaded8bf.png)

There doesn't seem to be a way for the host to enable debugging.

**Comment by isidorn** [comment]
@alexr00 thanks for trying this out but let's leave this one to @jramsay to verify since he knows the scenario exactly.
