### ISSUE TITLE
macos mojave: “Visual Studio Code” would like to administer your computer.

### ISSUE THREAD

**Issue by huguesalary** [microsoft/vscode#59484]
Issue Type: <b>Bug</b>

On macos Mojave, running `code` at the command line systematically shows this message:

```
“Visual Studio Code” would like to administer your computer. 
Administration can include modifying passwords, networking, and system settings.
[Don't Allow] [Ok]
```

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:04:11.329Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (1.17GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron /Volumes/infrastructure|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
asciidoctor-vscode|joa|0.15.1
php-cs-fixer|jun|0.1.85
Go|ms-|0.6.89

</details>

**Comment by bpasero** [comment]
Sounds a bit like https://github.com/Microsoft/vscode/issues/55236. Do you get the same when you run from the Dock?

**Comment by huguesalary** [comment]
I do not have the issue when I run from the Dock.

Worth noting I also am not logged in as `root` nor using `sudo`. Simply running `code` under my local user.

**Comment by bpasero** [comment]
@huguesalary yeah, I have not seen this so far and I recently updated to Mojave as well. If you find out anything more about it please let us know.

**Comment by oznu** [comment]
Same issue here.

![image](https://user-images.githubusercontent.com/3979615/51644209-84497080-1fc3-11e9-902f-227587a108f2.png)

I found [this guide](https://gitlab.com/gnachman/iterm2/wikis/fulldiskaccess) which explained a fix for the same problem in iTerm 2, I have applied the same changes to VS Code and it seems to have fixed the issue.

System Preferences -> Security & Privacy -> Privacy -> Full Disk Access -> Add Code.

![image](https://user-images.githubusercontent.com/3979615/51644449-50227f80-1fc4-11e9-94f2-6ff79a29c2bf.png)

**Comment by firelizzard18** [comment]
@oznu's solution seems to be working for me

**Comment by bpasero** [comment]
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to the code. As such, I will go ahead and close it. If you can identify the component that is causing the issue, please report it upstream:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.
