### ISSUE TITLE
Show progress indicator while performing marketplace searches

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#59497]
From testing #57901 

**Steps to Reproduce:**

1. Open extension view
2. Search for `a` in the marketplace (This query takes a bit of time. You can also repo this on a slow network with other queries)

**Bug**
No visual indicator that the search is being performed. I just see an empty extensions view

**Comment by isidorn** [comment]
Do we plan to tackle this issue some time in the future?
If not, why not? IMHO this is an issue and not a feature request (limiation compared to other viewlets)

**Comment by sandy081** [comment]
Regression from https://github.com/Microsoft/vscode/issues/52611
