### ISSUE TITLE
VS Code not revealing weird characters

### ISSUE THREAD

**Issue by MikkelHegn** [Microsoft/vscode#59495]
Issue Type: <b>Bug</b>

In VS Code I have a .ps1 file open with UTF-8 encoding. Opening the same file (with UTF-8) encoding in Notepad reveasl characters not shown in VS Code

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (6.15GB free)|
|Process Argv|C:\Users\mikhegn\AppData\Local\Programs\Microsoft VS Code\Code.exe --folder-uri file:///c%3A/src/IgniteBPDemo|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|3.0.0
vscode-svgviewer|css|1.4.6
vscode-markdownlint|Dav|0.20.0
sf-mesh-tools|mfe|0.8.0
azurecli|ms-|0.4.2
csharp|ms-|1.16.1
PowerShell|ms-|1.8.4
vscode-docker|Pet|0.3.1
code-spell-checker|str|1.6.10

</details>

**Comment by rebornix** [comment]
You can see those characters by setting `editor.renderControlCharacters` to `true`.
