### ISSUE TITLE
100% CPU usage from "Code Helper", even when VS Code is closed. (MAC OS X)

### ISSUE THREAD

**Issue by xoxota99** [Microsoft/vscode#59491]
Cam here from https://github.com/Microsoft/vscode/issues/11963

- VSCode Version: 1.27.2
- OS Version: Mac OS X Sierra (10.12.6)

Steps to Reproduce:

1. Launch VS Code
2. Wait

Does this issue occur when all extensions are disabled?: No idea how launch this with command-line params on mac.

from ps -aux | grep <processID> it looks like at least TWO of these processes are spawned, take up 100% CPU, and don't end when I exit VS Code:
`/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=extensionHost`

**Comment by xoxota99** [comment]
Can't tell if it's a dupe, but the symptoms are very similar (LAunch VS Code, don't open any files, eventually it randomly starts taking all CPU, fans go crazy, etc.)

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!
