### ISSUE TITLE
Extension icons and details can get into weird state if you lose network connectivity

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#59498]
Testing #57901

**Steps to Reproduce:**

1. Open standard extensions view
1. Disconnect computer from network
1. Perform a marketplace search  
1. Cancel this search to see default extensions view again

**Bug**
Many of the installed extensions will now be missing icons:

![screen shot 2018-09-26 at 3 22 29 pm](https://user-images.githubusercontent.com/12821956/46112677-487ed580-c1a0-11e8-8a8c-20c6c345c1b8.png)

Additionally, you cannot view their `details` pages. This only seems to happen if you lose the network after starting vscode. If you start vscode while already offline, we  grab the icons and detail pages locally

**Comment by sandy081** [comment]
Cannot repro this anymore.
