### ISSUE TITLE
Code has stopped responding.

### ISSUE THREAD

**Issue by bobmajdakjr** [Microsoft/vscode#595]
I am going to need help to actually get you useful information to debug this. As it stands my only data is "versions 0.10.0 and up have a bug where it randomly locks up, tells me it locked up, asks if i want to wait, and if i say yes wait, locks so hard windows itself cannot even close it without killing the process"

0.9.0 did not do this.

it will be fine running all weekend alone doing nothing, but then within minutes of actually using it it just gives up. i can constantly cause it by just using it, always happens in mid-stride while typing a string. i'm working in a php file almost every time it happened. and it happens fairly quickly (in under 10 minutes).

it affects both 0.10.0 and 0.10.1.

i'm running windows 10 on the fast insider ring, code on the insider ring, um. i got nothing else.

**Comment by seanmcbreen** [comment]
Can you let us know what languages are you using - for instance we have a pretty nasty PHP issue we are fixing up.  If you are using PHP that will cause this issue.

**Comment by bobmajdakjr** [comment]
PHP, HTML, and Javascript. I can't say for sure, but I am /fairly/ certain that it almost always happens while in the middle of working on a double quoted string. Like yesterday I had `echo "<p></p>"; and it happened while I was adding text inside the paragraph. I want to say it feels like it has almost always while doing that.

**Comment by bobmajdakjr** [comment]
Nah, so it just happened while typing some CSS in a file that is running the PHP language syntax. a scoped style tag. So it's not just double quoted strings or anything like that.

**Comment by h2u** [comment]
@bobmajdakjr , looks like it does not matter what language you are using in .php files. Read #160 , maybe you will find out answers.

**Comment by bpasero** [comment]
Very likely #160.

**Comment by bobmajdakjr** [comment]
agreed, sounds like that much lower bug number.
