### ISSUE TITLE
Settings Editor: Tab causes text to jiggle

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#59502]
Probably caused by the corner going from squared to rounded

![jiggle](https://user-images.githubusercontent.com/4033249/46114577-18d3cb80-c1a8-11e8-9e20-b87411bc0223.gif)

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/commit/674200fd49ad8c1557f884903fd09647975270f8

@bpasero is it ok to use `border-color: transparent` here instead?

**Comment by bpasero** [comment]
@roblourens yes totally, I use the same trick in other places.
