### ISSUE TITLE
Disabled extension should still contribute settings

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#59501]
If I have settings for an extension and I disable the extension temporarily, the settings will be marked as "unknown settings".

Similar to https://github.com/Microsoft/vscode/issues/23356, I think settings should be registered no matter the state of the extension.

**Comment by sandy081** [comment]
@octref In #23356 Extensions are enabled and loaded they are just not activated yet. But in this case extensions are not loaded at all. So the registry will not be populated and populating unloaded extension is not a good idea.

Best we can do is not to show the warning - #33931
