### ISSUE TITLE
Make profiles go to a folder `~/Desktop` by default

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#59505]
Currently, when you run `code --prof-startup`, it puts the profiles in `~`.

I suggest putting them into a folder, and not under `~`. Something like `~/Desktop/prof-<date-or-hash>` would be better.

**Comment by jrieken** [comment]
I like the prof-prefix but I am not so sure about putting them into a separate folder

**Comment by jrieken** [comment]
I have pushed a change to prefix the names with `prof`, despite `cpuprofile` being part of their name already. With this change things sort/group nice. I stick to the home folder.

**Comment by octref** [comment]
I'm giving it a bug label so this can get verified.

**Comment by octref** [comment]
Opened #62406 while testing this. @misolori can successfully run the command, though.
