### ISSUE TITLE
Auto import uses require, absolute paths

### ISSUE THREAD

**Issue by aaroncraig10e** [Microsoft/vscode#59506]
Issue Type: <b>Bug</b>

Recently, VSCode Insiders has started auto-importing incorrect paths.

```Typescript
import moment = require('moment');
import { Color } from 'components/props/colors';

const m = moment();
const c = Color;
```

Requiring an external dependency from node_modules results in using `require`, while importing an internal dependency uses an (incorrect) absolute path.

I would expect to see:
```Typescript
import moment from 'moment';
import { Color } from '../props/colors';

const m = moment();
const c = Color;
```
I don't _believe_ I've installed anything new recently to cause this change of behavior, and at any rate the behavior is the same with all plugins disabled.

VS Code version: Code - Insiders 1.28.0-insider (5ba5f14c954682df46f04a541f0b272166605366, 2018-09-26T07:25:01.336Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (1.00GB free)|
|Process Argv|-psn_0_4981952|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.1.0
project-manager|ale|9.0.1
vscode-eslint|dba|1.6.0
javascript-ejs-support|Dig|0.3.2
githistory|don|0.4.2
gitlens|eam|8.5.6
tslint|eg2|1.0.39
prettier-vscode|esb|1.6.1
vscode-pull-request-github|Git|0.1.6
jenkins-declarative-support|jmM|0.1.0
terraform|mau|1.3.5
dotenv|mik|1.0.1
python|ms-|2018.8.0
atom-keybindings|ms-|3.0.4
azure-account|ms-|0.4.3
vsliveshare|ms-|0.3.735
debugger-for-chrome|msj|4.10.1
vscode-jest|Ort|2.9.2
vscode-docker|Pet|0.3.1
material-icon-theme|PKi|3.6.0
ruby|reb|0.20.0
java|red|0.31.0
jenkinsfile-support|sec|0.1.0
slack|soz|0.0.14
code-spell-checker|str|1.6.10
vscode-java-debug|vsc|0.13.0
vscode-java-test|vsc|0.9.0
vscode-react-native|vsm|0.6.18
markdown-all-in-one|yzh|1.6.2

(6 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
The first part (the `moment` import) seems like https://github.com/Microsoft/TypeScript/issues/27152

For the absolute paths, can please your share your `jsconfig` or `tsconfig`? You can also try setting: `"typescript.preferences.importModuleSpecifier": "relative"` to see if that fixes the issue

**Comment by aaroncraig10e** [comment]
@mjbvz Regarding the first case -- that is possible, but my example is in a `.ts` file, so if it's adopting JSX behaviors, then there's another problem.

**Comment by aaroncraig10e** [comment]
`tsconfig`

```
{
  "compilerOptions": {
    "module": "commonjs",
    "esModuleInterop": true,
    "target": "es6",
    "noImplicitAny": false,
    "strictNullChecks": true,
    "moduleResolution": "node",
    "sourceMap": true,
    "outDir": "dist",
    "baseUrl": "./",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "noUnusedLocals": true,
    "declaration": true,
    "jsx": "react",
    "paths": {
      "*": [
        "node_modules/*",
      ]
    },
    "lib": [
      "es7",
      "es2017.object",
      "dom"
    ],
    "skipLibCheck": true
  },
  "include": [
    "components/**/*",
    "__tests__/**/*"
  ],
  "exclude": [
    "jest.setup*",
    "jest.config*"
  ]
}```

**Comment by aaroncraig10e** [comment]
@mjbvz Switching preferences to "relative" did solve the second case.

**Comment by jpike88** [comment]
Might be related to this one

https://github.com/Microsoft/vscode/issues/59815

**Comment by jpike88** [comment]
This is an annoying one... if there's ```import a from 'b'``` syntax in the file, shouldn't that be easy enough to detect? I don't know of any scenario where mixing both is allowed

**Comment by filipef101** [comment]
Also happenig the same to me, could it be related to moment itself? doing CMD + '.' to auto import does "import moment = require('moment')" with the autoimport as I write it does "import { 'moment' } from 'moment'"

Should be "import 'moment' from 'moment'"

**Comment by jbockle** [comment]
I am also having this issue and it was only specific node modules this occurred on, all local source imports properly.  `typescript.preferences.importModuleSpecifier:"relative"` did not work for me either.  

It appears to be how some typings are declared, see this example: https://github.com/jbockle/vscode-ts-autoimport-issue

**Comment by jpike88** [comment]
Would appreciate guidance from the VSCode team on this, it seems like a pretty important issue to me.

**Comment by mjbvz** [comment]
This import style should never be used in js files. We are tracking it in this upstream issue https://github.com/Microsoft/TypeScript/issues/29038
