### ISSUE TITLE
Go to definition doesn't work in jsdoc comments

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#59504]
ctrl+click works but F12/right click go to def doesn't

![image](https://user-images.githubusercontent.com/2193314/46114686-926bb980-c1a8-11e8-92c0-fd1a3f146a9b.png)

Tested in vscode.d.ts

**Comment by mjbvz** [comment]
Those links don't actually come from typescript but from our extension editing extension

The proper js doc way to express a reference is using the `@link` tag which we currently don't support: https://github.com/Microsoft/TypeScript/issues/16498
