### ISSUE TITLE
Choice snippets not working

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#59507]
Issue Type: <b>Bug</b>

Testing #58494

**Repo**
1. Configure a js user snippet:

```json
	"test choice": {
		"prefix": "zz",
		"body": [
			"${1|one,two,three|}"
		],
		"description": "test choice"
	},
```

1. In a js file, trigger this snippet and accept it with tab

**Bug**
Suggestions retrigger so that you cannot see the snippet choices

![sep-26-2018 16-57-09](https://user-images.githubusercontent.com/12821956/46115750-3fe0cc00-c1ad-11e8-86c6-3a23c94954a0.gif)

VS Code version: code-oss-dev 1.28.0 (Commit unknown, Date unknown)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|25%|

</details>

**Comment by jrieken** [comment]
😱
