### ISSUE TITLE
Outline Explorer's filter token lost when switch to other file and back

### ISSUE THREAD

**Issue by liwangqian** [Microsoft/vscode#59515]
1. Open a file
2. Enter some token in the filter input of the Symbol Outline Explorer
3. Switch to other file, and back
4. The filter token is lost.

**Comment by jrieken** [comment]
Yeah, we do that on purpose because when switching to that other file the filter likely doesn't make sense

**Comment by jrieken** [comment]
The filter is now kept for different inputs
