### ISSUE TITLE
Goto definition not working in vscode for multi-level object like $this->Model->Method()

### ISSUE THREAD

**Issue by mittultechnobrave** [Microsoft/vscode#59518]
I am using VSCOde and getting one problem for one feature called **goto definition**.

When I am pressing <kbd>Ctrl</kbd>+*Click* on any Definition it's working and when I am pressing <kbd>Ctrl</kbd>+*Click* on `$this->Function()` it also working but when i am pressing **`$this->class->method()`** it's not working (I wanted to open Method function of class).

Language i am using PHP, javascript, JQuery

Can anyone please help me?

**Comment by roblourens** [comment]
This isn't provided by vscode out of the box. If you are using a PHP extension, please file an issue on them.
