### ISSUE TITLE
Undo brings back last commit made by other users

### ISSUE THREAD

**Issue by sanketdsanghavi** [Microsoft/vscode#59513]
Issue Type: <b>Bug</b>

-Checkout a new branch from master
-Make a change in a file
-Save the file
-Undo the file change
-Undo one more time
-This removes changes from the last commit on the file by some other user.

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:31:26.156Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.57GB free)|
|Process Argv|/Users/ssanghav/Desktop/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sync-rsync|vsc|0.27.1

</details>

**Comment by bpasero** [comment]
@sanketdsanghavi that is very unlikely, you can undo until you get back to the point where the file was when you opened it. This is as designed.
