### ISSUE TITLE
Snippet transforms don't work

### ISSUE THREAD

**Issue by garyking** [Microsoft/vscode#59516]
- VSCode Version: Version 1.27.2 (1.27.2)
- OS Version: 10.13.6 (17G65)

Steps to Reproduce:

1. Use the snippet from [here](https://stackoverflow.com/a/51274700/420217).
2. Try it out. With it, I get the following, after typing `Asdf`: `Asdf -> Asdf`. Instead, it should show `Asdf -> ASDF asdf`.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
Works for me... @garyking For the transformation to happen, you need to jump to next placeholder. Did you do that?

![sep-27-2018 09-49-12](https://user-images.githubusercontent.com/1794099/46130870-a19b4780-c23a-11e8-8cc7-14dbc0608331.gif)
needs

**Comment by garyking** [comment]
Thanks, didn't know I had to hit Tab at the end again to trigger the transformation. It works now.
