### ISSUE TITLE
Find widget layout breaks when there is not enough space

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#5951]
- VSCode Version: alpha
- OS Version: os x

Steps to Reproduce:

1. open find widget, search for something which is not present in the document
2. reduce the editor size until the find widget is the smallest possible, notice the red overflowing in the bottom

![screen shot 2016-04-28 at 17 18 36](https://cloud.githubusercontent.com/assets/1926584/14891060/5ff1877c-0d65-11e6-8e70-d092b230ecd9.png)

**Comment by alexandrudima** [comment]
Dup of #2338
