### ISSUE TITLE
program not responding and Finder becomes white

### ISSUE THREAD

**Issue by cheioKID** [microsoft/vscode#59514]
Issue Type: <b>Bug</b>

Yesterday, after opening the C file, mac set asleep. With awaking mac today morning, the program is not responding. After the forced termination, the desktop becomes white. Restarting Finder is also invalid. Finally, only restored mac solved this problem

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:04:11.329Z)
OS version: Darwin x64 16.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 2|
|Memory (System)|16.00GB (4.30GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_299081|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-markdownlint|Dav|0.20.0
cpptools|ms-|0.18.1

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Do you meant that you think vscode breaking caused finder to break and you needed to _restart_ to fix your mac?

**Comment by cheioKID** [comment]
> Do you meant that you think vscode breaking caused finder to break and you needed to _restart_ to fix your mac?

Yes, but not break exactly, Finder is serving fine, just the desktop becomes white. The white  can not be fix even restart Finder.

**Comment by Tyriar** [comment]
FYI @bpasero, looks like maybe a macOS bug? Not sure this is actionable on our end.

**Comment by bpasero** [comment]
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to the code. As such, I will go ahead and close it. If you can identify the component that is causing the issue, please report it upstream:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.
