### ISSUE TITLE
Unable to scroll to heading in file with "%3A" in filename

### ISSUE THREAD

**Issue by jltgroup** [Microsoft/vscode#59523]
This bug may be the same as the one reported by #58985, but I wasn't too sure.

- VSCode Version: 1.27.2
- OS Version: Win 7 (64 bit)

**Steps to Reproduce**:

1. Open VSCode

2. Create a new file, and enter the following text:

   ```markdown
   # Example
   
   - [Example](#example)
     - [Heading 1](#heading-1)
     - [Heading 2](#heading-2)
   
   ## Heading 1
   
   Irure proident incididunt duis eiusmod anim tempor voluptate consequat.
   
   ## Heading 2
   
   Irure proident incididunt duis eiusmod anim tempor voluptate consequat.
   ```

3. Save the file as `"Example.md"`.

4. Using the mouse, press and hold `Ctrl` and click on the link `#heading-2`. The application should scroll to "Heading 2" successfully.

5. Now save the file as `"Example%3A 1.md"`.

6. Repeat step 4, the application should fail to scroll, and display the following error message:

   ```
   Unable to open 'Example: 1.md': File not found (file:///c:/Example: 1.md).
   ```

**Does this issue occur when all extensions are disabled?**: Yes

**Comment by mjbvz** [comment]
This works for on-disk files in insiders. Untitled files still are broken

**Comment by RMacfarlane** [comment]
I'm still able to reproduce this issue on this version:

Version: 1.29.0-insider (user setup)
Commit: d7ac6e838f51a03f7d417b4758f5fb075878d615
Date: 2018-11-01T06:20:59.729Z
