### ISSUE TITLE
Do not allow markers with no message to float through our system

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#5952]
Possible sources:
* extension host @jrieken 
* tasks framework @dbaeumer 

Starting with extension host. I have seen we hit a lot #5325 in error telemetry. This is because we try to add a decoration for a marker that contains a `source` but does not contain a `message`. I also find it funny that `IMarker` is defined as `message:string` and we check if `Array.isArray(marker.message)` in there.

I have added a check on my side, but IMHO we should not have such markers in our system since they are useless or represent a bug somewhere else. My suggestion: throw or ignore invalid markers when they get added into the system.

**Comment by jrieken** [comment]
> we check if Array.isArray(marker.message) in there.

I believe that's because the standalone editor would support html formatted [messages](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/htmlContent.ts#L13) at one point?

**Comment by alexandrudima** [comment]
:eyes: Wasn't me
