### ISSUE TITLE
markdown file preview bug report

### ISSUE THREAD

**Issue by chj6** [Microsoft/vscode#59521]
Vscode Version: 1.27.2
OS Version： mac 10.13.6

Sometimes I wirte .md file and preview by this plug, when i push the .md file to github, the file will have special symbol: �。

When I open .md file used by GitHub Pages, the � symbol will parse html code：
<span class="cm-invalidchar" title="\u8" aria-label="\u8" cm-text="�">•</span>

**Comment by chj6** [comment]
version: 1.27.2 (1.27.2)
system: mac

**Comment by mjbvz** [comment]
Please share some example text that contains the unknown character. Also what file encoding are you using?

**Comment by chj6** [comment]
> Please share some example text that contains the unknown character. Also what file encoding are you using?

Thanks for reply!

The character in the github will analysis below code：
<span class="cm-invalidchar" title="\u8" aria-label="\u8" cm-text="�">•</span>
[git history record](https://github.com/chj6/learn/blob/15b8a70cf985fd75dbe8193a7699e060962d5383/js/%08video-safari-record.md)

Encoding：UTF8

**Comment by mjbvz** [comment]
From your description, this seems like a bug with how github renders those unicode characters.

Closing as external
