### ISSUE TITLE
error highlight in TypeScript and JavaScript file 

### ISSUE THREAD

**Issue by houfeng0923** [Microsoft/vscode#59522]
- VSCode Version: 1.27.2
- OS Version: MacOS / Win10

Steps to Reproduce:

I see the commonjs `exports` keyword has error highlight : 
![image](https://user-images.githubusercontent.com/1825420/46129610-ceb31e80-c269-11e8-8dd7-2b7a4f1a55fa.png)

i check the grammar for Typescript and Javascript in [repo](https://github.com/Microsoft/TypeScript-TmLanguage), it has update the problem .

Now, i can install [ms-vscode.typescript-javascript-grammar](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) to fix this problem .

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Already fixed in VS Code insiders
