### ISSUE TITLE
Integrated Terminal drop box does not change to Task terminal when a task is run

### ISSUE THREAD

**Issue by chewlm86** [Microsoft/vscode#59520]
Version: 1.28.0-insider
Commit: 5ba5f14c954682df46f04a541f0b272166605366
Date: 2018-09-26T07:28:12.336Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
KDE Neon Bionic 18.04
Steps to Reproduce:

1. Add a "bash" Integrated terminal
2. Run Task when the bash terminal is being selected
3. When task is complete, You will noticed that the terminal drop box is still selecting the "bash" terminal.

![screenshot_20180927_140828](https://user-images.githubusercontent.com/5851437/46126337-6e1ee400-c25f-11e8-9b11-3a19741772e9.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
@alexr00 this is pretty old at this point, might already be fixed?

**Comment by alexr00** [comment]
I can't reproduce it, so it seems fixed.
