### ISSUE TITLE
I need to run a function to make decision whether the custom menu item is visible or not

### ISSUE THREAD

**Issue by Brighttll** [Microsoft/vscode#59529]
I found a list for when clause context, but I need more complex validation to make decision when to show the custom menu item. Is there any way to do that?

Like following:
package.json
"view/item/context": [
	{
		"command": "extension.test",
		"when": "funMakeDecision",
		"group": "new"
	}
]

extension.ts
export function funMakeDecision(){
        ...
	...
	...
	return true;
}

**Comment by jrieken** [comment]
See here: 
https://github.com/Microsoft/vscode/issues/10471#issuecomment-239764839
