### ISSUE TITLE
[html] follow id (#) html links

### ISSUE THREAD

**Issue by BartolomeSintes** [microsoft/vscode#59536]
It would be nice if VSCode would open/follow html links to anchors (elements with id attribute).
1. Target in the same document
Ctrl+click could be used to scroll down/up to the target element.
&lt;p>Link to &lt;a href="#target">end of the page&lt;/a>&lt;/p>
...
&lt;p id="target">This is the end, my friends.&lt;/p>

2. Target in another document
Using Ctrl+click you can open another linked document, but the document is opened at the beginning. It would be nice if VSCode would scroll down to the target.
Document 1:
&lt;p>Link to &lt;a href="document-2.html#target">end of another page&lt;/a>&lt;/p>
Document 2:
&lt;p>This is the beginning.&lt;/p>
...
&lt;p id="target">This is the end, my friends&lt;/p>

Thanking you in advance,

**Comment by saideepd** [comment]
Hey @aeschli I could do this task of opening link in same document on Ctrl+Click. In which html files it needs to be implemented ?

**Comment by aeschli** [comment]
@saideepd Thanks for your interest, you can find the code here: https://github.com/Microsoft/vscode-html-languageservice/blob/5c334c1025e3b5313b30ca82110bad28ddf09aa9/src/services/htmlLinks.ts#L93

Also see the tests there.

The URIs that you return can have the format `file:///some/file.js#73,84` (line, column)

**Comment by BartolomeSintes** [comment]
Very nice! When will this feature be available in Insiders?

**Comment by aeschli** [comment]
To verify create a HTLM document with ids and links that jump to these ids.
Note: Does not work across files!
