### ISSUE TITLE
Can't add shortcut ' ctrl + shift + / ' for multi line comment

### ISSUE THREAD

**Issue by cyberz** [Microsoft/vscode#59532]
- VSCode Version: 1.27.2
- OS Version: MacOS Mojave

Steps to Reproduce:

1. Open shortcut prefences
2. Try to change "Toggle Block Comment" shortcut to "ctrl + shift + /"
3. Instead applying shortcut combination VSCode running menu: Help > Search

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
That's a system shortucut, you should be able to remove it through System Preferences > Keyboard > Shortcuts > App Shortcuts > Show Help Menu
