### ISSUE TITLE
Git: Clone with network drive

### ISSUE THREAD

**Issue by Anti-Distinctlyminty** [microsoft/vscode#59544]
- VSCode Version: 1.27.2
- OS Version: Windows 10

Steps to Reproduce:

1. Have a git repo on a network drive.
2. Ctrl+Shift+P > Git: Clone and hit enter
3. Paste the URL of the repo on the network drive. Hit enter
4. Select the folder for the repo location and click Select Repository Location.
5. Receive a 'Git fatal: could not create leading directories of...'

Does this issue occur when all extensions are disabled?: Yes

I'm not sure if this is working as designed or not, but I guess it's relative obvious as to what is going on.
I know it says URL, but I was hoping the integrated commands should work if the equivalent terminal commands do.

**Comment by joaomoreno** [comment]
Can you show me an example URL?

**Comment by Anti-Distinctlyminty** [comment]
The 'URL' in my case was a mapped network drive, so in step 3 I would paste
`T:\__SharedAssets\Assets_Houdini_Dev\houdini16.5\python2.7libs`
I'm guessing that it only expects something like a github URL, but the equivalent git command in the terminal does work. So it would be good if this worked.

**Comment by OneThatWalks** [comment]
```
let baseFolderName = decodeURI(url).replace(/^.*\//, '').replace(/\.git$/, '') || 'repository';
let folderName = baseFolderName;
let folderPath = path.join(parentPath, folderName);
```
When Just passing 'T:\__SharedAssets\Assets_Houdini_Dev\houdini16.5\python2.7libs' the base folder name cannot be determined.  Using file:\\ before that works.

I am trying to get into contributing, if this is worth looking into further I would like to pick this up.  The fix could be determining if this is a drive first in the uri.

**Comment by OnorioCatenacci** [comment]
Just for the reference of anyone else that may see this: It's not "_file:\_" that is a workaround for this.  It's "_file://_" that works around this issue.

**Comment by aeschli** [comment]
Verified by cloning a git repo on a UNC path.
