### ISSUE TITLE
CLI: Print out current open file

### ISSUE THREAD

**Issue by guywaldman** [microsoft/vscode#59542]
Issue Type: **Feature Request**

Could perhaps be done by changing an environment variable (and unsetting it when editor closes).

Use case for this is when you want to execute a command on a file-by-file basis but want to see the file open in the editor, like running the currently open script from the command line, staging a file with the git CLI etc.

Should probably be opt-in.

**Comment by guywald1** [comment]
@skprabhanjan I think it’s better to wait for a maintainer to OK this since I’m not sure if this should be a feature, was just a suggestion and I wanted to raise a discussion.
But as far as implementing, have at it 🙂

**Comment by guywald1** [comment]
@skprabhanjan I think it’s better to wait for a maintainer to OK this since I’m not sure if this should be a feature; Was just a suggestion that I myself am not sure about, but thought that would be situationally really useful.
But as far as implementing, have at it 🙂

**Comment by skprabhanjan** [comment]
@guywald1 , thanks for that, i will wait for the same :)

**Comment by Tyriar** [comment]
An environment variable wouldn't work for this as once the environment is set and the shell is forked off, we can no longer change it. One way to solve this would be to add a CLI to access the current file of the last active window, but it seems like something that would seldom be used. Moving back to you @joaomoreno 😉

**Comment by ionagamed** [comment]
Hey! I see that this is marked as out-of-scope, just wondering — does this mean that PRs for this feature would also not get accepted? Or only that the team wouldn't implement it, but PRs from others are good?

**Comment by Tyriar** [comment]
@ionagamed I don't think we would accept it tbh, it's a bit of a strange CLI API imo and therefore I suspect would get very little use. We need to be concerned about bloat as well.
