### ISSUE TITLE
setScrollPosition should be able to set horizontal scroll position

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#59546]
refs: https://github.com/Microsoft/vscode/issues/52511

**Comment by Spongman** [comment]
can you please re-open #52511 as a feature request?

**Comment by ChuckJonas** [comment]
for the love of god the debug inspect window is maddeningly small.  Please reopen some of these issues so people can at least discuss it

**Comment by isidorn** [comment]
That is fixed in latest vscode insiders, you can try it out.
