### ISSUE TITLE
After update throwing : Couldn't find declaration for many modules 

### ISSUE THREAD

**Issue by Apostata** [Microsoft/vscode#59547]
It was working before.
now at import the module:
import { Validation } from 'bunnyjs/src/Validation';

[ts]
Could not find a declaration file for module 'bunnyjs/src/Validation'. 'c:/Dev/Notanet/frontend-env/cockpit/node_modules/bunnyjs/src/Validation.js' implicitly has an 'any' type.
  Try `npm install @types/bunnyjs` if it exists or add a new declaration (.d.ts) file containing `declare module 'bunnyjs';`

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?
