### ISSUE TITLE
PHP syntax highlighting breaks with backticks

### ISSUE THREAD

**Issue by mcdado** [microsoft/vscode#59545]
- VSCode Version: 1.27.2
- OS Version: 10.14 (18A391)

Steps to Reproduce:

Code without backticks:
![no-backticks](https://user-images.githubusercontent.com/898057/46144477-52b2d980-c25d-11e8-9738-c052ece26532.png)

Code with backticks
![backticks](https://user-images.githubusercontent.com/898057/46144488-59d9e780-c25d-11e8-9439-dbaa1e597ee1.png)

The problem is that the presence backticks don't allow the current string to be closed, which is opened with single quotes. In fact, if I use double quotes, the variable inside is highlighted but the concatenations dot are not, showing that it is considered a single string. Also I added the `WHERE = 1` at the end to show that the string is considered from the beginning thanks to the presence of `SELECT`.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mcdado** [comment]
Actually the behavior is cool, since the continuity of the whole query is preserved, but then also the in-between highlighting should be preserved somehow 🤔

**Comment by rzhao271** [comment]
@mcdado this issue still occurs on the latest VS Code (tested on Insiders 1.51)
Is this still an issue for you, though, based on your comment [here](https://github.com/microsoft/vscode/issues/59545#issuecomment-425068979)?

**Comment by mcdado** [comment]
Well, inside the backticks (second example above) is still sub-optimal.

**Comment by IZSkiSurfer** [comment]
I can confirm the backtick-problem:
![image](https://user-images.githubusercontent.com/47118575/105045245-00b6a300-5a68-11eb-8110-ec918196570f.png)

It's very annoying in combination with SQL queries.
For standalone files I then switch back to N++ which highlights correctly :(

If you need full (complex) example file to reproduce please feel free to text me.
