### ISSUE TITLE
Notifications are broken when shown very early on startup

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#59552]
These notifications have long messages:

```ts
notificationService.notify({
	severity: Severity.Error,
	message: 'Cannot update while running on a read-only volume. The application is on a read-only volume. Please move the application and try again. If you\'re on macOS Sierra or later, you\'ll need to move the application out of the Downloads directory. See https://github.com/Squirrel/Squirrel.Mac/issues/182 for more information.',
	source: 'update service',
});
```

No buttons:

![image](https://user-images.githubusercontent.com/22350/46148625-cad2cc80-c268-11e8-97b7-b2055b67c576.png)

No buttons expanded:

![image 1](https://user-images.githubusercontent.com/22350/46148656-d7efbb80-c268-11e8-8920-9b1a4a4c1e17.png)

Buttons:

![image 2](https://user-images.githubusercontent.com/22350/46148667-dde59c80-c268-11e8-89f2-334d12652a3d.png)

I would expect the same behavior of collapse/expand independent of whether buttons are present or otherwise.

**Comment by bpasero** [comment]
@joaomoreno cannot reproduce on macOS at least:

![image](https://user-images.githubusercontent.com/900690/46154653-e8f2f980-c275-11e8-961f-e6e25273f603.png)

Are you on Linux?

**Comment by joaomoreno** [comment]
Yes, this was on Linux.

**Comment by bpasero** [comment]
This happens for notifications that are triggered early enough that the workbench is not done loading yet and did not receive a layout call yet.

**Comment by roblourens** [comment]
Verification tip??

**Comment by joaomoreno** [comment]
@roblourens Try running that snippet at the ctor of the active viewlet (eg Search), that's how it reprod: if messages were sent to the notification service before the workbench was ready.
