### ISSUE TITLE
Cannot read property 'firstElementChild' of null

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#59558]
1. Open a markdown file
2. Open a preview (not side by side but in the same group)
3. Close all editors in group
`Cannot read property 'firstElementChild' of null`

I can no longer reproduce it always.

**Comment by bpasero** [comment]
@isidorn do you really only have these 2 editors (markdown and preview) opened and then close all?

Looking at callers of `firstElementChild`, this could originate from [here](https://github.com/Microsoft/vscode/blob/a75f4bcf4e31e7adde117a1c0a94e13f2bf5a06e/src/vs/base/browser/ui/grid/grid.ts#L144) in grid.ts (@joaomoreno)

**Comment by isidorn** [comment]
@bpasero after that I was getting some grid error, so it is definetly that.
Sorry for pathetic repro steps, will try to get better now.

**Comment by isidorn** [comment]
Can not repro it now, no matter what I do.
I am sure that I was doing cmd + w, which is on my machine Close all editors in group. I am sure that I was left with just the right hand side markdown (which was in the right group).
I am sure that further pressing of cmd + w reulsted in the error

**Comment by bpasero** [comment]
@isidorn ok maybe @joaomoreno has an idea

**Comment by isidorn** [comment]
I just searched all my logs for 'firstElementChild' and there is nothing in them. Sorry

**Comment by bpasero** [comment]
Ok, just reopen when you see this again and attach the stack.
