### ISSUE TITLE
Snippet transformation format does not support \u

### ISSUE THREAD

**Issue by DavidHenri008** [Microsoft/vscode#59554]
According to the [VSCode documentation](https://code.visualstudio.com/docs/editor/userdefinedsnippets), the snippet syntax follows the one of [TextMate snippet syntax](https://macromates.com/manual/en/snippets).
The TextMate site state that the \u command may be used in transform format in order to capitalize a capture group however this option does not work.

``` 
{
  "MySnippet": {
    "scope": "javascript",
    "prefix": "snippet1",
    "body": [
		"My file ${TM_FILENAME_BASE/(.)(.)(.*)/$1\u$2$3/};",
	],
    "description": "Capitalize the second letter of the filename."
  }
}
```

- VSCode Version: 1.27.2
- OS Version: Windows 10 Enterprise 1709

Steps to Reproduce:

1. Create a code snippet
2. Add a variable with a transform
3. Use the syntax with \u like in the "TextMate snippet syntax"

**Comment by jrieken** [comment]
Yeah, it only follows it.. The challenge is different regex-engines which forced us down a different path. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_transform-examples.

**Comment by DavidHenri008** [comment]
@jrieken Thanks for the quick response. I do understand the differences and the regex-engine differences/limitations. As an improvement I would recommend clarifying the documentation since it is confusing. The confusion comes from the usage of the word "follows" and then the mention of a single exception. The \u syntax is not part of the stated exception.

(As a note I do not consider this a question but more an error according to the documentation).

Thank you.

**Comment by jrieken** [comment]
> (As a note I do not consider this a question but more an error according to the documentation).

Ok, please file an issue here https://github.com/Microsoft/vscode-docs. Thanks for your help
