### ISSUE TITLE
Support custom variables in snippet

### ISSUE THREAD

**Issue by DavidHenri008** [Microsoft/vscode#59557]
I would really appreciate to be able to create my own variable in a code snippet.
This variable would be interpret at the very beginning of the script and then its value could be used by the snippet.
For example:
```
{
  "MySnippet": {
    "scope": "javascript",
    "prefix": "snippet1",
    "body": [
                "`${MY_ID:215}`"
                "`${MY_FILENAME:${TM_FILENAME_BASE/(.)(.)(.*)/$1\u$2$3/}}`"
		"My file ID:  ${TM_ID};",
		"My filename:  ${TM_FILENAME};",
	],
    "description": "Test"
  }
}
```
I am using the back tick in order to identify the declaration of a variable.
Also, another alternative could be to support the 'interpolated shell code'.

Thanks.

**Comment by jrieken** [comment]
The back tick syntax is already reserved for evaluation (see #10561). Apart from that I am not convinced that this is a use addition and worth going further off the "standard". When this is local to a snippet how much value would it bring?

**Comment by DavidHenri008** [comment]
In my case it would greatly lighten the code since the value of my variable would be a long and complex regex expression applied on the filename. Meaning I would define this variable once and then re-use it everywhere.
Again by supporting the 'interpolated shell code', and I understand it may not be trivial, I think I may be able to achieve something similar my declaring my own [shell variable](https://macromates.com/manual/en/environment_variables#context_dependent_variables).

```
shellVariables = (
   {  name = 'TM_MY_VAR';
      value = 'MyValue ';
   },
);
```

**Comment by DavidHenri008** [comment]
It is true that my request is pretty similar to what you were describing in the [#10561](https://github.com/Microsoft/vscode/issues/10561). Maybe my case could be covered by this solution. Now this is 2 years old, have you an idea of the feasibility/chance to be implemented? I assume it is based on votes (thumbs up).

**Comment by jrieken** [comment]
> Now this is 2 years old, have you an idea of the feasibility/chance to be implemented? I assume it is based on votes (thumbs up).

Hard to say. Generally 👍 count and we also have some slack time to work on random stuff. The challenge with #10561 is that it will make insert snippet asynchronous (since we must call something). Today snippets insert sync, so it will be a bigger behaviour change...

**Comment by antmdvs** [comment]
@jrieken @DavidHenri008 I'm looking for project-level variable support. Perhaps this is an oversimplification, but instead of #10561, could this implemented by adding another VariableResolver implemention, e.g.: `EnvironmentVariableResolver` or `ConfigFileVariableResolver`?

https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/snippet/snippetVariables.ts#L39

Thanks!
