### ISSUE TITLE
Extension Debugee does not start even after configuring the task

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#59550]
- Open the hello-world extension in VS Code
- Have a watch npm script in package.json
```json
"watch": "tsc -watch -p ./"
```
- Have the following launch configuration with preLaunchTask to debug the extension
```json
{
    "name": "Launch Extension",
    "type": "extensionHost",
    "request": "launch",
    "runtimeExecutable": "${execPath}",
    "args": [
        "--extensionDevelopmentPath=${workspaceRoot}"
    ],
    "stopOnEntry": false,
    "sourceMaps": true,
    "outFiles": [
        "${workspaceRoot}/out/src/**/*.js"
    ],
    "preLaunchTask": "npm: watch"
}
```
- Start Debugging "Launch Extension"
- After some time a prompt comes with one option is to configure the task
- Configure the task and create `npm:watch` task. Following is my `tasks.json`

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "type": "npm",
            "script": "watch",
            "problemMatcher": []
        }
    ]
}
```

- Kill the terminal
- Start Debugging "Launch Extension" again

🐛 You see the prompt again

**Comment by isidorn** [comment]
That is perfectly fine.
You need to define 
`isBackground: true` in your tasks.json

Closing asDesigned.

fyi @dbaeumer
