### ISSUE TITLE
Syntax highlighting for json5 in markdown

### ISSUE THREAD

**Issue by gldraphael** [Microsoft/vscode#59567]
Would be great if VS Code would recognize `json5` as a language and provide the same syntax highlighting it does for `json`.

GitHub supports commented markdown code blocks when the language is set as json5.
```json5
{
  "foo": "bar" // uses json5
}
```

```json
{
  "foo": "bar" // uses json
}
```

**Comment by mintunitish** [comment]
This seems interesting. Any tips on how to proceed?

**Comment by mjbvz** [comment]
The markdown grammar comes from [this repo](https://github.com/Microsoft/vscode-markdown-tm-grammar/). This file is what defines the fenced code block languages: https://github.com/Microsoft/vscode-markdown-tm-grammar/blob/master/build.js After updating it, run the build to regenerate the grammar

**Comment by arshadkazmi42** [comment]
I would like to take this up. This is going to be my first contribution. Is it still available? Also can someone guide me where can I start to work on this

**Comment by cedric05** [comment]
can i take this up?

**Comment by arshadkazmi42** [comment]
@cedric05 I have already started working on this. Thanks

**Comment by cedric05** [comment]
ok @arshadkazmi42  please go ahead.  just to be clear, will you be creating new file json5.tmLanguage like this https://github.com/microsoft/vscode/blob/master/extensions/json/syntaxes/JSONC.tmLanguage.json.

**Comment by arshadkazmi42** [comment]
@cedric05 This is my first contribution to vscode. So I was exploring it, is that file required? I was thinking that adding an entry here https://github.com/Microsoft/vscode-markdown-tm-grammar/blob/master/build.js for json5.

**Comment by cedric05** [comment]
as per my knowledge that will be enough, but json5 has lot more features that json. so it would be better to those as well.

**Comment by cedric05** [comment]
may be it is out of scope. don't bother me @arshadkazmi42

**Comment by scrthq** [comment]
@cedric05 / @arshadkazmi42 - you wouldn't need to create a new TM file, you would want to update the existing Markdown TM file that @mjbvz linked in his comment since the syntax you would need to update is specific to Markdown files, not JSON5. You should be able to copy the existing JSON bits from there since Code supports comments in JSON markdown blocks as if it was JSONC/JSON5 already:

![image](https://user-images.githubusercontent.com/12724445/46360152-7b0d5000-c630-11e8-89b2-8305e7ee3337.png)

**Comment by scrthq** [comment]
@arshadkazmi42 just seeing your comment acknowledging the same, carry on 💃

**Comment by arshadkazmi42** [comment]
@scrthq So just to confirm, I will add an entry there similar to json.

`{ name: 'json5', language: 'json5', identifiers: ['json', 'sublime-settings', 'sublime-menu', 'sublime-keymap', 'sublime-mousemap', 'sublime-theme', 'sublime-build', 'sublime-project', 'sublime-completions'], source: 'source.json' },`

something like this. will this be fine? Also I was checking this PR #59779 reading comments there, I thought this bug does not needs any fixing.

Is the fix i am trying to do correct? And does it needs fixing?

**Comment by mjbvz** [comment]
You pretty much just need to add `json5` to the list of `identifiers` in the existing `json` section

**Comment by arshadkazmi42** [comment]
@mjbvz So it does not need any other change? I have added it in the identifiers list here

https://github.com/Microsoft/vscode-markdown-tm-grammar/blob/master/build.js#L42

if that is all, i  will create a PR right away
