### ISSUE TITLE
Cannot scroll in the debug window

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode#59562]
_From @amittleider on September 27, 2018 8:0_

The debug window does not allow scrolling left and right, so sometimes when there is a long output you can't do anything to see the values.

Does this belong in the `vscode-python` does it need to go upstream to the `vscode` repo?

![image](https://user-images.githubusercontent.com/1625951/46131410-d956bf00-c23b-11e8-8687-fbc0ba61df59.png)

## Environment data

- VS Code version: Version: 1.27.2
- Extension version (available under the Extensions sidebar): 2018.8.0
- OS and version: Ubuntu 16.04
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.6
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv 

## Actual behavior

No scroll bar or method of seeing all the values in the debugger except select all and copy/paste into the editor.

## Expected  behavior

A scroll bar when the text extends past the line length of the debug window

_Copied from original issue: Microsoft/vscode-python#2707_

**Comment by DonJayamanne** [comment]
@amittleider 	
I'll move this to VS Code, yes this issue needs to be reported in the VS Code repo.

**Comment by isidorn** [comment]
`workbench.tree.horizontalScrolling`: true

**Comment by isidorn** [comment]
No for performance reasons.
Debug console has word wrapping turned on. I am not sure why it does not properly wrap in your case - probably a flaw in my heuristic how I calculate line width.
