### ISSUE TITLE
Rename "Toggle Search View Position" feature

### ISSUE THREAD

**Issue by sjetha-pason** [microsoft/vscode#59565]
Hi,

I have an issue with the "Toggle Search View Position" feature shown here, but I don't know if it's a bug or a feature request.
![image](https://user-images.githubusercontent.com/11927856/46161010-81bb5200-c241-11e8-84ba-4202a1868d55.png)

The first time I used this feature on my vertically-mounted monitor, the search panel seemed to disappear completely from view. It was also toggled when right-clicking on a file, so my assumption was that it would affect the comparison view and not move the search panel itself.
My issue with this is two-fold:
1. It is not clear that the search panel is going to move to the bottom of the window when it is toggled.
Toggling, in itself, should be something that can be triggered from the same place over and over again. 
2. Even if the option were a button within the search box, it would be better, but ideally it should be somewhere in the menus so that it can be found again and again, always in the same spot.

As I said, I'm not sure if this is a bug or a feature, or both, and would like some direction on how I can have my issues looked at.

 Shafiq.

**Comment by roblourens** [comment]
> The first time I used this feature on my vertically-mounted monitor, the search panel seemed to disappear completely from view

Can you explain that some more? Did it not show up in the panel, or do you just mean that you didn't notice it?

I agree that it would make sense for this to be a menu option, but it's probably not commonly used enough to have it in the menu, they are full enough. It can be found in the command palette which is stable, we just added it to the context menu for discoverability.

**Comment by sjetha-pason** [comment]
Hi Rob,
The fact that it is vertically-mounted might have made it only appear that the search window disappeared. I've been unable to make it disappear completely, so it might have been something that I experienced rather than an issue with the application.
Your reasoning around discoverability makes sense, it was just a bit jarring for me when it happened the first time. I'm sure there's some UX lingo for when this happens.

**Comment by roblourens** [comment]
Do you think there's a wording change for that command that might have made the result more predictable?

**Comment by sjetha-pason** [comment]
Maybe. The word "toggle" gives me the impression that it affects something else, especially since the way I triggered it originally was that I right clicked on a file in the search window, and it was an option at the bottom.
Toggle, to me, suggests that it will be there if I need to revert what I had done, but when the whole window moved around, it was a little jarring.

**Comment by isidorn** [comment]
Let's keep this open and see if more users find it confusing.
We use toggle thorught our UX and for now I would not change it.

**Comment by chris-topher** [comment]
The "Toggle Search View Position" needs moving to the context menu or panel section menu shown here:
![image](https://user-images.githubusercontent.com/4648005/60823263-1377c880-a19f-11e9-9169-319c47d85b0d.png)

Its very difficult to find otherwise and is un-intuitive. Other panels move by accessing the menu in panel title so the search box movement should be in the similar location.

![image](https://user-images.githubusercontent.com/4648005/60823476-83864e80-a19f-11e9-8180-1a295659d46e.png)
