### ISSUE TITLE
Node js: Cannot start debugging: EMFILE: too many open files

### ISSUE THREAD

**Issue by tapika** [Microsoft/vscode#59564]
Using Visual studio 2017, create new project , Javascript/Node.js/Basic vue.js Web Application.
- Initialize project using "npm install"
- Launch chrome using command line argument 
"--remote-debugging-port=9222"

In project properties set Debugger port to 9222.

Start debugging.

Visual studio launches chrome, but local host cannot be reached. While checking Visual studio state, you can see in output window following information:

Verbose logs are written to:
C:\Users\user\AppData\Local\Temp\vscode-node-debug2.txt
The program 'vue-cli-service.js' has exited with code -1 (0xffffffff).

And if you open that log file - you can see following error:
---------------------------------------
...
SourceMaps: expanded globs and found 11364 scripts
SourceMaps: could not preload for generated script: d:\PrototypingQuick\VuejsApp1\VuejsApp1\node_modules\caniuse-lite\data\regions\AN.js. Error: Error: EMFILE: too many open files, open 'd:\PrototypingQuick\VuejsApp1\VuejsApp1\node_modules\caniuse-lite\data\regions\AN.js'
....

Last error message repeated multiple times.

This is probably a duplicate of similar closed case - I suspect either fix was not picked up into release or it's new bug:

https://github.com/Microsoft/vscode/issues/49074

I've tried to raise this bugcase originally to Microsoft, but they rejected the case - in here:

https://developercommunity.visualstudio.com/content/problem/331767/node-js-cannot-start-debugging-emfile-too-many-ope.html

as it's not bug in their environment.

**Comment by isidorn** [comment]
This github repository is for visual studio code, not for visual studio. Sorry
