### ISSUE TITLE
manifest is not valid json. line 1 column 1 unexpected token

### ISSUE THREAD

**Issue by drowkn** [Microsoft/vscode#59563]
I recently tried to do a chrome extension, but every time i try to install it in my browser i receive the following message: "manifest is not valid json. line 1 column 1 unexpected token".
I tried some lints and my code is ok, but still getting this error. In my project i have three files:

manifest.json:
```
{
    "manifest_version": 2,
    "version": "0.0.1",
    "name": "Hello World",
    "description": "Extension Hello World",
    "author": "Daniel",
    "browser_action": {
   	 "default_title": "Hello World",
   	 "default_popup": "index.html",
   	 "default_icon": "icon.png"
    }
}
```
index.html, a regular html file

and icon.png, but this one has no code, its just the icon of the extension, so i don't think it matters in this question.

**Comment by aeschli** [comment]
@drowkn How is this related to VSCode?
