### ISSUE TITLE
visual studio code - insiders search not working due to not indexing files in project folder

### ISSUE THREAD

**Issue by olitreadwell** [Microsoft/vscode#59566]
Issue Type: <b>Bug</b>

all i've had to do is open a project folder in visual studio code insiders and try to search for a file using command T

at which point it just hangs despite knowing files with the search for key word exist

VS Code version: Code - Insiders 1.28.0-insider (b4d09d27509f2c023f63d4315aa966a5ec7581e9, 2018-09-27T14:37:17.724Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.60
vscode-eslint|dba|1.6.0
vscode-npm-script|eg2|0.3.5
vscode-great-icons|emm|2.1.42
prettier-vscode|esb|1.6.1
auto-close-tag|for|0.5.6
path-autocomplete|ion|1.12.0
docthis|joe|0.7.1
vscode-subword-navigation|ow|1.2.0
material-icon-theme|PKi|3.6.0
vscode-icons|rob|7.27.0
stylelint|shi|0.43.0
code-spell-checker|str|1.6.10
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.7.0
html-css-class-completion|Zig|1.17.1

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
cmd+T search symbols by default. Are you searching symbols or files? And can you be more clear what you mean by "hangs"?
