### ISSUE TITLE
When doing comparison in source control view in split screen, content on the left is blank

### ISSUE THREAD

**Issue by jyavenard** [Microsoft/vscode#59560]
This is a regression with the latest version.
VS Code version: 1.27.2
Platform: Windows 10 or macOS 10.13.6

Step to reproduce

In a modified file (saved), present under configuration control (such as git).
Press Ctrl-Shift-G to go to Source Control view.
Click on the name of the modified file. It opens the file with "(Working Tree)" showing side by side comparison of the change.

Now split the screen with Ctrl-2.

Result: The left half of the screen is now blank
Expected result: it's not blank, and it shows the content

note that if on the left pane you scroll the text to the right, it usually appears once you reach the extreme right.

If you close the 2nd half opened when you did Ctrl-2, then the text in the comparison window re-appear.

![capture](https://user-images.githubusercontent.com/505748/46153374-4e91b680-c273-11e8-8ca2-7741167711b2.PNG)

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/code-exploration_1.28.0-1536650436_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/VSCodeUserSetup-x64-1.28.0-exploration.exe)

**Comment by jyavenard** [comment]
yes, the issue doesn't reproduce with this exploration version

**Comment by jyavenard** [comment]
Saying it's a duplicate is great, but linking to the other bug would be better.
