### ISSUE TITLE
Implementations Code Lens shows wrong count for interfaces used in constructors

### ISSUE THREAD

**Issue by philraj** [Microsoft/vscode#59575]
Issue Type: <b>Bug</b>

Enter the following code with implementations code lens enabled:

```ts
interface I {
  num: number;
}

class C1 {
  constructor(public things: I) {}
}

class C2 {
  public things: I = { num: 0 };
}
```

**Expected Result:**
The implementation counter above the interface definition shows 2.

**Actual Result:**
The implementation counter shows 1 (the usage in C1's constructor isn't counted).

![adsasdads](https://user-images.githubusercontent.com/16470658/46169105-323c4c80-c268-11e8-8941-b94e401b28a8.png)

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:04:11.329Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
apib|Jar|0.0.1
Bookmarks|ale|9.1.0
vscode-intelephense-client|bme|0.8.8
bracket-pair-colorizer|Coe|1.0.60
vscode-eslint|dba|1.6.0
gitlens|eam|8.5.6
tslint|eg2|1.0.39
smarty|imp|0.3.0
vscode-icon-theme|jtl|1.6.3
vscode-language-babel|mgm|0.0.20
code-beautifier|mic|2.1.0
dotenv|mik|1.0.1
vsliveshare|ms-|0.3.735
vscode-docker|Pet|0.3.1
material-icon-theme|PKi|3.6.0
gitconfig|sid|2.0.0
ayu|tea|0.16.0
vscode-todo-highlight|way|1.0.4
jinja|who|0.0.8

(5 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Why should it be 2 in in this case? Isn't `things` the only implementation of the interface?

**Comment by philraj** [comment]
Maybe I'm missing something about the meaning of "implementation" being used here, but I don't see the conceptual difference between assigning a literal value to a typed instance property in a constructor vs. assigning a constructor parameter to a typed instance property in a constructor.

**Comment by mjbvz** [comment]
It sounds like you are want the reference code lens instead. In `C1` you are just referencing `I`. In `C2`, `I` is both referenced and then implemented with `{ num: 0 }`

**Comment by philraj** [comment]
Fair enough, thanks.
