### ISSUE TITLE
code block pasted into terminal or ran with runSelectedText gets garbled

### ISSUE THREAD

**Issue by clayms** [Microsoft/vscode#59574]
related to but different than:
1.  https://github.com/Microsoft/vscode/issues/11253
1.  https://github.com/Microsoft/vscode/issues/11281

When trying to run a block of code in the integrated terminal running ipython, the code gets garbled and broken up in a strange way.  
1.  `[55;1` gets inserted randomly
1.  random letters get capitalized
1.  the lines get broken in the middle of the string rather than the end
1.  some text just disappears all together

A single line of code runs just fine using either method, the problem only occurs when you select multiple lines of code.

Steps to Reproduce:

1.  Open integrated terminal (I used powershell)
1.  start ipython
1.  run code in terminal by:
     1.  select block of code to run and then  `runSelectedText`  "Terminal: Run Selected Text in Active Terminal" via the Command Palette (`Ctrl+Shift+P`)
     1.  OR - copy and paste code into terminal

selected block of code to run:
```py
import os
import pandas as pd
import numpy as np
import string
import regex as re
import sys
import random
import Levenshtein as lv
import pickle
```

Output using `runSelectedText`  i.e. "Terminal: Run Selected Text in Active Terminal" via the Command Palette (`Ctrl+Shift+P`)
```py
In [32]: import os
s
In [33]: ort pandas as pd
  File "<ipython-input-33-22c9fba746cb>", line 1
    ort pandas as pd
             ^
SyntaxError: invalid syntax


In [34]: mpy as np
t  File "<ipython-input-34-6c759181cff9>", line 1
    mpy as np
         ^
SyntaxError: invalid syntax


In [35]: ort string
r  File "<ipython-input-35-6c5359d06aa8>", line 1
    ort string
             ^
SyntaxError: invalid syntax


In [36]: port regex as re
  File "<ipython-input-36-a3aced042c4d>", line 1
    port regex as re
             ^
SyntaxError: invalid syntax


In [37]: ort sys
t  File "<ipython-input-37-8ed77366cec2>", line 1
    ort sys
          ^
SyntaxError: invalid syntax


 In [38]: port ra[55;1Rndom
    ...: import Levenshtein as lv
    ...: import pickle
    ...:
```

Output by simply copying and pasting the code into the terminal
```py
In [39]: import os
da
sIn [40]: port pandas as pd
  File "<ipython-input-40-c38575850d93>", line 1
    port pandas as pd
              ^
SyntaxError: invalid syntax


In [41]: t numpy as np
ing  File "<ipython-input-41-37140a097691>", line 1
    t numpy as np
          ^
SyntaxError: invalid syntax



In [42]: mport string
  File "<ipython-input-42-b137b9645724>", line 1
    mport string
               ^
SyntaxError: invalid syntax


In [43]:  regex as re
  File "<ipython-input-43-6b9a39db3f43>", line 1
    regex as re
           ^
SyntaxError: invalid syntax

^[
[In [44]: mport sys
  File "<ipython-input-44-4cdb4843525d>", line 1
    mport sys
            ^
SyntaxError: invalid syntax


In [45]: port random
  File "<ipython-input-45-f64e7cda21fb>", line 1
    port random
              ^
SyntaxError: invalid syntax


In [46]: impo[55;1Rrt Levenshtein as lv
    ...: import pickle
    ...:
```

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (8.31GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter|don|1.1.4
vsc-material-theme|Equ|2.4.2
macros|ged|1.2.1
nbpreviewer|jit|1.0.0
sftp|lix|1.5.9
MagicPython|mag|1.0.12
python|ms-|2018.8.0
vscode-icons|rob|7.27.0

(7 theme extensions excluded)

</details>

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
