### ISSUE TITLE
Hovering over buttons in find / replace mode doesn't show built-in help tooltips

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#5957]
- VSCode Version: Insiders and current
- OS Version: Windows 10 RTM

Steps to Reproduce:

1. Create a new file
2. Press CTRL + F
3. Hover the mouse over the buttons in the search / replace box
4. Notice that the help tooltips don't appear

Cheers,
**Trevor Sullivan**
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by bpasero** [comment]
I cannot reproduce on Mac nor Windows.

**Comment by alexandrudima** [comment]
@pcgeek86 I also cannot reproduce. I get all the tooltips on WIndows 10, even for disabled (greyed out) buttons.

**Comment by pcgeek86** [comment]
@bpasero @alexandrudima Is there some way to investigate what's going on here? Debug logs or something?
