### ISSUE TITLE
The terminal garbled

### ISSUE THREAD

**Issue by firebat1314** [Microsoft/vscode#59589]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.![image](https://user-images.githubusercontent.com/21351033/46183668-79781b00-c304-11e8-9cd8-79c02db79bb8.png)

2.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
