### ISSUE TITLE
Request Console History in Debug Mode

### ISSUE THREAD

**Issue by GarethJacobsNZ** [Microsoft/vscode#59585]
When executing [PowerShell] in Debug mode [DBG]:, the UP and DOWN arrows should be able to recall command line history.

**Comment by isidorn** [comment]
They do, if you go up and down in the debug console you will see history.
Can you post some pictures, or a video. Or actualy some steps on how to reproduce this.

Do you also see this in vscode insiders?
https://code.visualstudio.com/insiders/
