### ISSUE TITLE
Add back workbench.action.moveEditorToSecondGroup...

### ISSUE THREAD

**Issue by safield** [Microsoft/vscode#59583]
In version 1.25.1 the following commands were removed...

workbench.action.moveEditorToSecondGroup
workbench.action.moveEditorToThirdGroup

 I would propose they be added back in (group 1-8), potentially unmapped to a key shortcut. They are subjectively superior for certain workflows, and would mirror SublimeText functionality. I don't see any justification for their removal.

 With the new grid view for VScode, as well as the following command...

"workbench.editor.closeEmptyGroups": false,

I am able to use a workflow where I have a fixed and unchanging window configuration. Because of this, I think of each window unwaveringly as window 1 or window 4 or window 3, etc. I quite often want to send a file directly from one window, to another window.  

Further more, I propose they they could be renamed to be more clear and concise...

workbench.action.moveEditorToGroup1
workbench.action.moveEditorToGroup2
workbench.action.moveEditorToGroup3
workbench.action.moveEditorToGroup4
workbench.action.moveEditorToGroup5
workbench.action.moveEditorToGroup6
workbench.action.moveEditorToGroup7
workbench.action.moveEditorToGroup8

This would closely follow the behaviour in Sublime Text...
	{ "keys": ["ctrl+shift+1"], "command": "move_to_group", "args": { "group": 0 } },
	{ "keys": ["ctrl+shift+2"], "command": "move_to_group", "args": { "group": 1 } },
	{ "keys": ["ctrl+shift+3"], "command": "move_to_group", "args": { "group": 2 } },
	{ "keys": ["ctrl+shift+4"], "command": "move_to_group", "args": { "group": 3 } },
	{ "keys": ["ctrl+shift+5"], "command": "move_to_group", "args": { "group": 4 } },
	{ "keys": ["ctrl+shift+6"], "command": "move_to_group", "args": { "group": 5 } },
	{ "keys": ["ctrl+shift+7"], "command": "move_to_group", "args": { "group": 6 } },
	{ "keys": ["ctrl+shift+8"], "command": "move_to_group", "args": { "group": 7 } },
	{ "keys": ["ctrl+shift+9"], "command": "move_to_group", "args": { "group": 8 } },

**Comment by bpasero** [comment]
While we do not assign this command any keybinding, there is a moveActiveEditor command that allows to receive arguments (see [here](https://github.com/Microsoft/vscode/blob/caaa5369cb4d22b7481e6ff97252cf92937709eb/src/vs/workbench/browser/parts/editor/editorCommands.ts#L82)). An extension can leverage this to offer advanced commands.

**Comment by safield** [comment]
I would consider this basic and core editor behaviour. I would delegating it to extensions would be the wrong choice.
