### ISSUE TITLE
JavaScript & TypeScript: delete keyword highlighted in non-keyword context

### ISSUE THREAD

**Issue by prencher** [Microsoft/vscode#5958]
- VSCode Version: Any
- OS Version: Any

The `delete` keyword is being highlighted in non-keyword contexts, such as:

```typescript
const items = new Set<string>([ 'foo', 'bar' ]);
items.delete('foo');
```

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#157
