### ISSUE TITLE
Navigating overflowed menu with arrow keys - menu items revealed at the wrong time?

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#59580]
- Set `"window.menuBarVisibility": "toggle"`
- Size window so menu will overflow
- Press alt and expand a menu
- Use arrow keys to move around
- Seems that when I step over the point where it overflows, the next menu is shown but the menu bar doesn't adjust until I press the arrow key one more time

![sep-27-2018 14-00-27](https://user-images.githubusercontent.com/323878/46174423-d076e500-c25d-11e8-9060-d17dcc89aa38.gif)

**Comment by sbatten** [comment]
duplicate https://github.com/Microsoft/vscode/issues/57756
