### ISSUE TITLE
can't install 64-bit version

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#59588]
_From @amhani on September 28, 2018 0:36_

when download and install 64-bit version of code in windows，it show 'please uninstall the 32-bit version of code before installing this 64-bit version', but i have deleted all the file and directory about the before (32-bit) version  

_Copied from original issue: Microsoft/vscode-docs#1883_

**Comment by joaomoreno** [comment]
@amhani If you open the Control Panel, is Code 32 bit still listed in there?
