### ISSUE TITLE
vs running slow

### ISSUE THREAD

**Issue by rajendharitguy** [Microsoft/vscode#59593]
It's too slow using terminal in vs. i need immediate respond.

**system information:**

CPUs | Intel(R) Atom(TM) CPU Z3735F @ 1.33GHz (4 x 1333)
-- | --
GPU Status | 2d_canvas: unavailable_softwarechecker_imaging: disabled_offflash_3d: unavailable_softwareflash_stage3d: unavailable_softwareflash_stage3d_baseline: unavailable_softwaregpu_compositing: unavailable_softwaremultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwarerasterization: unavailable_softwarevideo_decode: unavailable_softwarevideo_encode: unavailable_softwarewebgl: enabled_readbackwebgl2: unavailable_off
Memory (System) | 1.94GB (0.17GB free)
Process Argv | C:\Users\R A J E N D R A\AppData\Local\Programs\Microsoft VS Code\Code.exe
Screen Reader | no
VM | 0%

enabled extensions:

Extension | Author (truncated) | Version
-- | -- | --
vscode-sqlite | ale | 0.3.1
tslint | eg2 | 1.0.39
apacheconf-snippets | eim | 1.1.9
vsc-material-theme | Equ | 2.4.2
php-debug | fel | 1.12.6
beautify | Hoo | 1.4.4
mysql-syntax | jak | 1.3.1
vscode-phpfmt | kok | 1.0.30
Angular-BeastCode | Mik | 6.2.28
dotenv | mik | 1.0.1
vscode-autoprefixer | mrm | 2.1.2
mssql | ms- | 1.4.0
mysql-inline-decorator | odu | 0.0.5
laravel-blade | one | 1.18.0
live-sass | rit | 3.0.0
LiveServer | rit | 5.1.1
bootstrap4-vscode | the | 4.3.0

**Comment by Tyriar** [comment]
> 2d_canvas: unavailable_software

Canvas hardware acceleration is off, you can try the following workarounds:

- Add setting `"terminal.integrated.rendererType": "dom"`, or
- Launch using code.exe --ignore-gpu-blacklist
