### ISSUE TITLE
Breadcrumbs file selector opens in a wrong place

### ISSUE THREAD

**Issue by jsynowiec** [Microsoft/vscode#59596]
- VSCode Version: 1.27.2 (1.27.2)
- OS Version: macOS 10.14

Steps to Reproduce:
1. Open a few files
2. Open keyboard shortcuts tab
3. Trigger `breadcrumbs.focusAndSelect` command with a keybinding

Result:
<img width="573" alt="screenshot 2018-09-28 at 10 11 05" src="https://user-images.githubusercontent.com/1029142/46196450-661a7f00-c307-11e8-8184-0aea0295ddfb.png">

This breadcrumbs _pane_ can't be closed by hitting Esc. You have to change focus to something else for it to disappear.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
Good news: This is fixed in [VS Code Insiders](https://code.visualstudio.com/insiders/).

**Comment by jsynowiec** [comment]
@jrieken can you please link the mentioned issue? I couldn't find it.

And it seems right, I updated my insider version and no longer can reproduce it on `caaa5369cb4d22b7481e6ff97252cf92937709eb`.

**Comment by jrieken** [comment]
> @jrieken can you please link the mentioned issue? I couldn't find it.

it will be in here: https://github.com/Microsoft/vscode/issues?q=label%3Abreadcrumbs+is%3Aclosed

**Comment by jsynowiec** [comment]
Really? Thank you 😒 Never mind then. The important thing is that it's fixed.

**Comment by jrieken** [comment]
Well, GH issue search is as bad for me as it is for you. I know from the top of my head that this issue has been fixed and that it has been labeled with `breadcrumb`. That is the important bit here. So, sorry, if are really, really interested in knowing the exact issue number you have to find it in that narrowed down list.
