### ISSUE TITLE
Terminal broken in latest insider

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#59595]
I can't open a terminal anymore in latest insider

Version: 1.28.0-insider (user setup)
Commit: caaa5369cb4d22b7481e6ff97252cf92937709eb
Date: 2018-09-28T05:18:20.266Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

I never see the prompt

<img width="1104" alt="capture" src="https://user-images.githubusercontent.com/1931590/46194092-a5919d00-c300-11e8-97b5-64626a031f28.png">

**Comment by dbaeumer** [comment]
Nothing in the console. 

The forth try opened one :-) with a usalable prompt

**Comment by Tyriar** [comment]
Already tracked here: https://github.com/Microsoft/vscode/issues/57803

Nothing I can do on my end apart from complain more towards the Windows Console team. Pressing enter should give you a prompt.
