### ISSUE TITLE
Screen Reader Optimized status bar item inconsistent behavior

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#59597]
Verifying #52036

Clicking on the status bar item behaves somewhat inconsistently. If I previously clicked 'Yes' in the notification, clicking on the status bar item reopens the notification. If I previously just closed the notification (on X), clicking on the status bar item no longer opens the notification.

**Comment by isidorn** [comment]
This sounds like a general notification issue -> forwarding to @bpasero

**Comment by chrmarti** [comment]
From looking at the fix it seemed like it was specific to that.
