### ISSUE TITLE
Show default values in jsdoc quick-info.

### ISSUE THREAD

**Issue by Wolfonye** [Microsoft/vscode#59609]
I hope I didn't overlook any issue that poses the same request in a different wording; if yes I am sorry.

The request: 
I repeatedly encounter situations where I would be glad to see the default values
for optional parameters (if specified) in the ctrl+shift+space quick-info. 

Is there anything speaking against such a feature?

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#27442
