### ISSUE TITLE
Configurable tooltip hover delay

### ISSUE THREAD

**Issue by nealot** [Microsoft/vscode#59608]
Since the tooltip uses my system theme, I find it too distracting when working: I'd like to disable it or at-least increase the delay before it's visible. There is https://github.com/Microsoft/vscode/issues/23946 and https://github.com/Microsoft/vscode/issues/55098 which illustrate scenarios where this feature would be desirable.

**Comment by bpasero** [comment]
@nealot to be clear, you do not talk about the hover within the editor right?

**Comment by nealot** [comment]
@bpasero No, that's already covered with `editor.hover.delay` and `editor.hover.enabled`.
