### ISSUE TITLE
We should make sure that markers are cleared in the following situations.

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#59601]
- when the extension host crahs (not sure if this already happens due to the extension host restart logic)
- when an extension deactivates.

**Comment by jrieken** [comment]
> when the extension host crahs (not sure if this already happens due to the extension host restart logic)

This happens already today

**Comment by jrieken** [comment]
> when an extension deactivates.

Today, deactivation only happens on shutdown and that's the same as a crash - [`MainThreadDiagnostics#dispose`](https://github.com/Microsoft/vscode/blob/ac8b1fbb90c128ef83309fa4d73723d55111c01a/src/vs/workbench/api/electron-browser/mainThreadDiagnostics.ts#L25) will be called. 

@dbaeumer what scenarios do you have in mind?

**Comment by dbaeumer** [comment]
@jrieken this came up in another issue were people where complaining about stale markers (e.g. an extension not cleaning them). There I agree that if something bad happens to markers that VS Code needs to ensure that they are cleaned (for example the extension host crashes). If this is the case I am OK to close the issue. Just wanted to make sure it is the case.

**Comment by jrieken** [comment]
Yeah, I think we are good here. What people might be issues is this https://github.com/Microsoft/vscode/issues/58564

**Comment by dbaeumer** [comment]
@jrieken thanks.
