### ISSUE TITLE
1 second delay after tab press

### ISSUE THREAD

**Issue by SphericalPotatoInVacuum** [Microsoft/vscode#59607]
VS code version: 1.27.2
OS: Ubuntu 16.04

As the title says there is around 1 second delay after tab press anywhere in the editor:
- In the editor field
- In the search field
- In the terminal

I tried disabling every keybinding related to tab, excluding the tab itself, but the delay is still there. I also tried disabling all the extensions, but that didn't help either

**Comment by bpasero** [comment]
@SphericalPotatoInVacuum you mean you hit the "Tab" key to enter a tab into the editor?

**Comment by SphericalPotatoInVacuum** [comment]
Yes

**Comment by SphericalPotatoInVacuum** [comment]
Issue Type: <b>Performance Issue</b>

I spotted it randomly, but it still persists with all extensions turned off, so I guess it was here since the startup

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:11:15.873Z)
OS version: Linux x64 4.15.0-34-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1520)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|11.30GB (5.30GB free)|
|Process Argv|/usr/share/code/code|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   139	 18923	code main
    0	    35	 18925	   zygote
    0	   104	 19042	     shared-process
    0	    93	 18960	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Bear api - Visual Studio Code)
|    Folder (Bear api): 3 files
|      File types: json(2) js(1)
|      Conf files: package.json(1);
```

</details>
Extensions: none

Here is a javascript profile I took. The strange thing is the "KeyDown" event fires around 800-1000ms after I press the tab key, because I press it almost at the same time as I click the mouse in the editor field.
[profile.zip](https://github.com/Microsoft/vscode/files/2428224/profile.zip)

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by SphericalPotatoInVacuum** [comment]
There aren't any lags in the "pure" version. I will install some extensions and see if it will change something.

**Comment by bpasero** [comment]
OK

**Comment by SphericalPotatoInVacuum** [comment]
I installed all the extensions except for themes (but I installed icon packs) and I can't spot any delays now

**Comment by bpasero** [comment]
@SphericalPotatoInVacuum does it perform better if you use the stable version again but pick a different user data directory: `code --user-data-dir <some folder>`?

**Comment by SphericalPotatoInVacuum** [comment]
Nope, the same 0.7-8 second delay

**Comment by bpasero** [comment]
@SphericalPotatoInVacuum ok so it could have been fixed through our nightly builds and that one ends to be the released one next week. I suggest we close this issue and you try out next week when stable is out.

**Comment by SphericalPotatoInVacuum** [comment]
Thanks for your support! :+1:
