### ISSUE TITLE
Delay when searching inside extension pages

### ISSUE THREAD

**Issue by SpectralKH** [Microsoft/vscode#59606]
Issue Type: <b>Bug</b>

1. Open an extension page
2. Bring up search by shortcut, then immediately start typing something

You'll see that your first character is missing, assuming you type fast enough. This happens because VSCode does not give the search field focus before the animation is finished. When searching within the editor, this is not an issue, as the search field gains focus before the animation starts.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:04:11.329Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|32.00GB (0.31GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
arepl|alm|1.0.1
vscode-django|bat|0.17.0
color-info|bie|0.5.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
python-preview|don|0.0.4
jupyter|don|1.1.4
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.4.2
html-slim-scss-css-class-completion|gen|1.1.1
beautify|Hoo|1.4.4
MagicPython|mag|1.0.12
VS-code-vagrantfile|mar|0.0.7
theme-monokai-pro-vscode|mon|1.1.8
vscode-autoprefixer|mrm|2.1.2
python|ms-|2018.8.0
atom-keybindings|ms-|3.0.4
color-highlight|nau|2.3.0
vscode-docker|Pet|0.3.1
vscode-versionlens|pfl|0.21.2
material-icon-theme|PKi|3.6.0
sass-indented|rob|1.4.9
code-settings-sync|Sha|3.1.2
slim|sia|0.1.2
ayu|tea|0.16.0
vscodeintellicode|Vis|1.0.4
quokka-vscode|Wal|1.0.150
jinja|who|0.0.8

(11 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
I can't repro this, can you include a gif?

**Comment by SpectralKH** [comment]
@roblourens Will do this once I get back to my PC.

When you press cmd/ctrl+f, do you see that the search field doesn't immediately get focused? You should be able to tell by the border around the search field lighting up.

**Comment by roblourens** [comment]
It seems to be focused immediately for me. I assume when you say "extension page" you mean the page that's opened when you click an extension in the extension viewlet.

**Comment by sandy081** [comment]
Search feature is coming from markdown/webview editor.

**Comment by SpectralKH** [comment]
@roblourens Yes, it's the page opened when you click an extension in the extension viewlet.

Apparently the issue exists in the terminal as well.

Video: https://youtu.be/iVV4nBCuoYs
Slow down the speed to 0.25, and you'll see that the search field is coming before I start typing.

**Comment by roblourens** [comment]
Oh, I do see this now. 

- Press cmd+f
- Immediately start typing

In the editor, all the characters show up in the find widget. In the terminal and webview find, it doesn't get characters until the animation is finished. You would have to have very fast reflexes to hit this in real life. But now that I've noticed it I may never "unnotice" it...

**Comment by mjbvz** [comment]
For verification: also test this with the markdown preview and in the release notes view
