### ISSUE TITLE
Source control frozen

### ISSUE THREAD

**Issue by lucacattide** [Microsoft/vscode#59605]
Issue Type: <b>Bug</b>

Hi, I noticed that sometimes the SCM manager freezes. I was convinced that was caused by some corrupted plugins, but either with a clean installation with none of them, after N commits/pushes the panel doesn't work anymore. No actions run on button click, neither new edits being tracked. Every time this happens I'm forced to quit/relaunch the program.

Thanks for your assistance.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:04:11.329Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2500S CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (1.37GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
vue-material|abh|0.0.2
silverstripe|adr|0.0.3
laravel-blade-spacer|aus|1.0.2
vscode-database|baj|1.5.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
laravel-blade|cjh|1.1.2
laravel-goto-view|cod|1.2.1
compulim-vscode-closetag|Com|1.2.0
vue-peek|dar|1.0.2
vscode-markdownlint|Dav|0.20.0
vscode-eslint|dba|1.6.0
xml|Dot|2.3.2
EditorConfig|Edi|0.12.4
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.6.1
php-debug|fel|1.12.6
php-intellisense|fel|2.3.5
vscode-npm|fkn|3.3.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
npm-dependency-links|her|1.0.0
beautify|Hoo|1.4.4
vscode-npm-dependency|how|1.2.0
composer|ika|0.7.1
smarty|imp|0.3.0
webpack|jer|2.1.0
docthis|joe|0.7.1
node-module-intellisense|lei|1.5.0
vscode-language-babel|mgm|0.0.20
dotenv|mik|1.0.1
vscode-apache|mrm|1.1.1
debugger-for-chrome|msj|4.10.2
vuejs-extension-pack|mub|1.1.3
vetur|oct|0.12.7
laravel-blade|one|1.18.0
laravel-extension-pack|one|0.4.0
laravel5-snippets|one|1.5.0
vscode-css-peek|pra|2.1.0
ruby|reb|0.20.0
phpdoc-comment-vscode-plugin|rex|1.1.0
laravel-artisan|rya|0.0.22
code-settings-sync|Sha|3.1.2
vscode-status-bar-format-toggle|tom|1.4.0
vscode-npm-scripts|tra|0.2.1
vscode-import-cost|wix|2.9.0
webpack-progress|wk-|0.0.8
JavaScriptSnippets|xab|1.7.0
html-css-class-completion|Zig|1.17.1

</details>

**Comment by joaomoreno** [comment]
Can you reconfirm that the issue still reproduces with no plugins loaded? You have to shutdown Code and run with `code --disable-extensions`.

**Comment by lucacattide** [comment]
I tried with a fresh install too with no extensions installed.
Today I'm using my default setup (with extensions too). I'll try to launch it with that command and I'll post an update once I have made a test.

**Comment by lucacattide** [comment]
I tested the IDE for a day and half and I don't had any issue related to that I mentioned above. I think that some taces of old extensions still in my system either if I removed them before the fresh install.

I'll continue to investigate in order to find the corrupted one. Thanks for your support.
