### ISSUE TITLE
Allow to configure `window.title` with _external variables_

### ISSUE THREAD

**Issue by Idealien** [microsoft/vscode#59616]
A re-submit of https://github.com/Microsoft/vscode/issues/22037 as the 6-12 month period mentioned in closing the previous is coming up.

In the[ February Release](https://code.visualstudio.com/updates/v1_10#_configurable-window-title), we can now Customize the Window Title, based on a set of variables, which is a great feature 👍

Had you thought about allowing extensions to publish new variables to be used by window.title setting?

The immediate use-case example for [Project Manager Extension](https://github.com/alefragnani/vscode-project-manager/issues/98) is to add Project Name as a variable for the window.title.

**Comment by elkinjosetm** [comment]
That would be AWESOME!
