### ISSUE TITLE
git is working every 10 seconds

### ISSUE THREAD

**Issue by johnpapa** [Microsoft/vscode#59618]
Issue Type: <b>Bug</b>

Here is what i see in vs code every 10 seconds in git output. This happens even if git.autoFetch is false (in settings)

git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose

I just found a setting where if i add it and set it to false, this stops happening.

"git.autorefresh": false,
                                               
Is this intentionally set to true by default?

It is distracting to see the git icon with a timer working every few seconds in the sidebar icon.

VS Code version: Code - Insiders 1.28.0-insider (5ba5f14c954682df46f04a541f0b272166605366, 2018-09-26T07:25:01.336Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz (16 x 3200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.10
markdown-preview-github-styles|bie|0.1.3
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.20.0
vscode-eslint|dba|1.6.0
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.39
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.6.1
vscode-pull-request-github|Git|0.1.6
Angular1|joh|0.2.0
angular-essentials|joh|0.4.0
Angular2|joh|6.1.5
dotenv|mik|1.0.1
vscode-azureappservice|ms-|0.9.1
vscode-azurefunctions|ms-|0.11.0
vscode-cosmosdb|ms-|0.8.0
azure-account|ms-|0.4.3
azurecli|ms-|0.4.2
vsliveshare|ms-|0.3.735
vsliveshare-audio|ms-|0.1.32
vsliveshare-pack|ms-|0.1.3
debugger-for-chrome|msj|4.10.1
angular2-inline|nat|0.0.17
vetur|oct|0.12.7
vscode-docker|Pet|0.3.1
material-icon-theme|PKi|3.6.0
polacode|pnp|0.2.2
vue-vscode-snippets|sdr|1.3.0
code-settings-sync|Sha|3.1.2

(1 theme extensions excluded)

</details>

cc @chrisdias - per our chat yesterday

**Comment by joaomoreno** [comment]
Git will refresh its state due to file change events, at most once every 10 seconds. So your workspace must have some file change events occurring. Does it

**Comment by johnpapa** [comment]
I have auto save on but even fin I sit there and just watch it we can see it working. 

Please reopen

**Comment by joaomoreno** [comment]
@johnpapa Does this only happen on a single project, or on all the git repositories in your system?

Let's try something:

1. Fully shutdown Code.
2. In a command line, run `code --verbose FOLDER`. Please reference the folder in which this issue occurs.
3. Open the devtools
4. Wait

While you wait, are there any file events?
