### ISSUE TITLE
VSC debugger errors out with ts_helpers.js not found

### ISSUE THREAD

**Issue by bearoutthere** [Microsoft/vscode#59610]
When trying to run debugger in VSC with stopOnEntry: true debugger throws the following error and stops.

```
Unable to open 'ts_helpers.js': File not found (file:///data/data/com.appxxx/files/internal/ts_helpers.js).
```
I’m not sure where this path is set so i looked in the file systems and found a couple of similar folders

/home/xxx/dev/appxxx/platforms/android/app/build/intermediaries/assets/debug/internal
/home/xxx/dev/appxxx/platforms/android/app/src/main/assets/internal

When VSC shows the error it also offers to create the missing file. When clicked it also errors out with the “Permissions denied” error.

I’ve changed permissions on the above folders and contained files to 777 (wide open to all) but with the same result.

Setting stopOnEntry: false resolves the problem but then i miss some early breakpoints.

I’ve tried everything i could think of and Google is not being helpful on this matter.

Please help.
Thanks in advance.

**Comment by bearoutthere** [comment]
Also if i ignore the error messages above and attempt to walk through the application in debugger i also get bundle.js not found error.  Searching for that file yield the following folders

/home/zzz/dev/appxxx/platforms/android/app/build/intermediates/assets/debug/app/bundle.js
/home/zzz/dev/appxxx/platforms/android/app/src/main/assets/app/bundle.js

changing file permissions to 777 does not change anything.  it appears that the debugger is looking for these files in a different place but i have no idea where these path settings are specified.

**Comment by bearoutthere** [comment]
It's a Nativescript core / Typescript app.  What other info do you need?

**Comment by roblourens** [comment]
Can you share your launch config?

**Comment by bearoutthere** [comment]
```

{
            "name": "Launch on Android",
            "type": "nativescript",
            "request": "launch",
            "platform": "android",
            "appRoot": "${workspaceRoot}",
            "sourceMaps": true,
            "stopOnEntry": true,
            "watch": true,
            "sourceMapPathOverrides": {
                "webpack:///*": "${workspaceRoot}/app/*"
            },
            "tnsArgs": [
            "--bundle"
            ]
        },

**Comment by bearoutthere** [comment]
I've reinstalled everything again.  Reran nativescript-dev-webpack update scripts that generated new webpack config file.  I also tried without the --bundle option.  The same result.  Unable to open ts_helpers.js.    If i ignore the error and continue it works sometimes but sometimes debugger crashes.
I can be on skype if you'd like a more real time feedback.

**Comment by bearoutthere** [comment]
The debugger crash is reproduceable.  It happens on any file change after the initial debugger launch and is caused by topmost().currentEntry being null when trying to navigate to a page.

**Comment by bearoutthere** [comment]
Perhaps its a problem with the nativescript plugin with VSC.  I'll try posting there as well.

**Comment by roblourens** [comment]
Yeah it looks like you are debugging with the nativescript extension, please file an issue on their repo
