### ISSUE TITLE
Current branch in status bar confusing with multi-folder workspace

### ISSUE THREAD

**Issue by dotchev** [Microsoft/vscode#59611]
- VSCode Version: Version 1.27.2 (1.27.2) f46c4c469d6e6d8c46f268d1553c5dc4b475840f
- OS Version: macOS 10.13.6 (17G65)

Steps to Reproduce:
1. Add several folders to the workspace, where each folder is a different git repo on a different branch
2. Open different files from different folders, the branch in the status bar does not change

It seems the branch in the status bar reflects the currently selected project in the Source Control view.
This can be confusing as this may not match the branch of the file you are currently working on.

Does this issue occur when all extensions are disabled?: Yes

I see two possible solutions
1. Show in the status bar the branch of the currently selected file
2. Show in the status bar the project name together with the branch

Even both of these can be implemented.

**Comment by joaomoreno** [comment]
This has been fixed in the last month. Will be out in the next release. The status bar will track the currently open file.
