### ISSUE TITLE
scroll jumps too much sometimes

### ISSUE THREAD

**Issue by graph** [Microsoft/vscode#59628]
Version: 1.27.2 (system setup)
Commit: f46c4c469d6e6d8c46f268d1553c5dc4b475840f
Date: 2018-09-12T16:17:45.060Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
Happens in all platforms: Windows, Mac, Linux

This one is very hard to reproduce and happens randomly, and happens in the editor & terminal view. Sometimes after reading stuff on the internet I come back to vs code and scroll a a single tick with my mouse wheel and it jumps by more than a full page. On linux it's most pronounced as it jumps all the way to the bottom.  This seems to happen only when vs code has been inactive for a while and when I return. It doesn't always happen and I don't know anyway to reproduce this 100% of the time. I feel like the latest version it happens more often.

Here are my settings:

```
{
    "files.autoSave": "onFocusChange",
    "editor.rulers": [
        80,
        100
    ],
    "editor.smoothScrolling": true,
    "editor.fontFamily": "'DejaVu Sans Mono', Consolas, 'Courier New', monospace, 'Segoe UI Emoji'",
    "editor.fontWeight": "bold",
    "files.eol": "\n",
    "editor.minimap.enabled": false,
    "window.zoomLevel": -1,
    "editor.fontSize": 12,
    "editor.folding": false,
    //"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",
    "C_Cpp.commentContinuationPatterns": [],
    "terminal.integrated.fontSize": 12,
    "terminal.integrated.fontFamily": "'DejaVu Sans Mono'",
    "editor.dragAndDrop": false,
    "window.titleBarStyle": "custom"
}
```

**Comment by Tyriar** [comment]
I'm guessing this is related to Electron as it affects all platforms, can you see if it happens on our experimental Electron v3 builds?

* macOS: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/code-exploration_1.28.0-1538127308_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/VSCodeUserSetup-x64-1.28.0-exploration.exe)

**Comment by graph** [comment]
Yeah It might be electron as I experience the same thing in the Slack app. I'll continue using the experimental builds and let you know if it happens.

**Comment by graph** [comment]
after googling this is probably a duplicate of the issue with this comment https://github.com/Microsoft/vscode/issues/28795#issuecomment-391258341 That comment is probably on to something as I couldn't replicate the issue with the steps of OP. But if I use my trackpad then my mouse scroll wheel smooth scrolling is disabled for a little while. The experimental and stable builds on windows behave the same way as I described.

**Comment by graph** [comment]
so I've been using both versions stable and experimental. And so far both of them are behaving fine. Once I'm focused on triggering a bug it's so much more harder to trigger it lol.
