### ISSUE TITLE
Why after one preLaunchTask run, vscode always states on subsequent runs that there are errors (only resets after you fully restart vscode)

### ISSUE THREAD

**Issue by NinoFloris** [Microsoft/vscode#5962]
Why after one preLaunchTask run, vscode always states on subsequent runs that there are errors? This only resets if you fully restart vscode.

- VSCode Version: 1.1.0-insider
- OS Version: OSX 10.11

Steps to Reproduce:

1. Setup a C# dotnet core debuggable project, that you know compiles.
2. For debug purposes, set showOutput to always in tasks.json (for the task that the debugger runs)
2. Run dotnet build in the terminal to cache the compilation bits, so the output stays exactly the same for both times in the vscode output window.
3. Run the debugger, no error bar should appear and you should see ```Project %name% was previously compiled. Skipping compilation.``` in the output window.
4. Launch debug again, and again and watch ad nauseam as the error bar keeps appearing while the build was successful/had no errors.
5. To know for sure this error information stays cached somewhere just restart vscode and run debug, there will appear no error bar the first time, and it's there again the second.

Is this because the markerService does not get reset?

(Talking about the markerService in this class)
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugService.ts

**Comment by bpasero** [comment]
@dbaeumer @isidorn fyi. maybe this issue should be moved to the omnisharp repository.

**Comment by isidorn** [comment]
Yes, this is the current limitation of our prelaunch task in debug world.
Namely, after a prelaunch task is run, we check if there are errors anywhere in the workspace, not errors related to the prealaunch task. Thus if you have any errors you will still get the notificaiton (thus we have the 'debug anyway' button).
When you see this do you see some errors in your workspace in the lower left corner of your screen?

**Comment by NinoFloris** [comment]
Yes there are, but what in heavens does that have to do with a preLaunch task, I might even run a totally unrelated command. One that has nothing to do with my workspace.

And the errors are mainly because the ecosystem is not stable yet and omnisharp sometimes complains about assembly version mismatches or those pcl issues like "The type object is defined in an assembly that is not referenced." However, dotnet build has no problems with these so called errors.

**Comment by isidorn** [comment]
As mentioned in my previous comment this is the current limitaiton of the prelaunch task, we currently have no way to get errors produced by a specific task. Thus forwarding this to @dbaeumer

**Comment by NinoFloris** [comment]
Is just exitcode (as you do have that) not enough for these tasks?

**Comment by isidorn** [comment]
Yes it is not enough, as watching tasks do not exit for instance.
Though feel free to experiment - maybe check if it is a watching task, PRs are welcome :)

**Comment by mattflix** [comment]
@isidorn  The preLaunchTask probably doesn't make sense to be a watching task.  But, to the point that @NinoFloris made, if the preLaunchTask exits with non-zero, then probably launch should not proceed (at least without warning prompt).  But, if it exits with zero, then just go.

Yes, if the preLaunchTask is a watching task (I suppose there could be a use case for that), then just have an launch.json option to indicate that the preLaunchTask is "fire and forget" or "kill and restart".

**Comment by dbaeumer** [comment]
I could add information about whether a specific task run has generated problems. Then we would have the needed information. @isidorn as an alternative you could check how many errors existed before and after to see if the task added some.

**Comment by isidorn** [comment]
@dbaeumer both approaches make sense to me. Also as @mattflix and @NinoFloris pointed out I could look into the exitCode of the [ITaskSummary](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/tasks/common/taskSystem.ts#L188) - should I get that reliably from the tasks framework?

If you decide to add the information then ping me once you push that and I can adopt on my side. Otherwise I can use the errorCode or the before/after idea.

**Comment by dbaeumer** [comment]
@isidorn can you start with the before after idea. Need to see what came in as new issues the last two weeks I was away.

**Comment by isidorn** [comment]
Just tried the before / after and that approach breaks our extension development story. Since the marker service gets continously updated when developing TS, so the error would be present event before the preLaunchTask is run. Thus I could not use the heuristic since errors while developing TS extensions would be undetected by debug. Thus it would be cool if the task framwork gave me more data.

I have started to look into the exitCode and if present and 0 I just start debugging
@NinoFloris @mattflix our alpha channel should be open to public soon so you will be able to just try it out and let me know how it works for you

**Comment by marvinhagemeister** [comment]
I'm affected by the same problem. Here is a stack trace and a [Repository](https://github.com/marvinhagemeister/vscode-todo2/tree/vscode_prelaunch) to reproduce the bug (checkout the `vscode_prelaunch` branch).

First run of the `Test Extension` task is fine, all subsequent runs produce the described error message `Build errors have been detected during preLaunchTask 'npm'`.

```js
e.doShow                                       @  messageService.ts:128
e.show                                         @  messageService.ts:112
i.configurationManager.adapter.i.runPreLaunchTask.then.i.messageService.show.message  @	debugService.ts:537
__dirname.undefined.t.Class.define.then        @  winjs.base.raw.js:1826
(anonymous function)                           @  debugService.ts:530
__dirname.undefined.t.Class.define.then        @  winjs.base.raw.js:1826
(anonymous function)                           @  debugService.ts:513
__dirname.undefined.t.Class.define.then        @  winjs.base.raw.js:1826
(anonymous function)                           @  debugService.ts:512
h                                              @  winjs.base.raw.js:1440
__dirname.undefined.P.enter                    @  winjs.base.raw.js:1127
__dirname.undefined.t.Class.define._run        @  winjs.base.raw.js:1343
__dirname.undefined.t.Class.define._completed  @  winjs.base.raw.js:1311
__dirname.undefined.t.Class.define.then        @  winjs.base.raw.js:1826
__dirname.undefined.L.enter                    @  winjs.base.raw.js:1023
__dirname.undefined.t.Class.define._run        @  winjs.base.raw.js:1343
__dirname.undefined.t.Class.define._setCompleteValue  @  winjs.base.raw.js:1327
h                                              @  winjs.base.raw.js:1440
__dirname.undefined.P.enter                    @  winjs.base.raw.js:1127
__dirname.undefined.t.Class.define._run        @  winjs.base.raw.js:1343
__dirname.undefined.t.Class.define._completed  @  winjs.base.raw.js:1311
h                                              @  winjs.base.raw.js:1440
__dirname.undefined.P.enter                    @  winjs.base.raw.js:1127
__dirname.undefined.t.Class.define._run        @  winjs.base.raw.js:1343
__dirname.undefined.t.Class.define._completed  @  winjs.base.raw.js:1311
d                                              @  winjs.base.raw.js:2072
q.then.a.(anonymous function)                  @  winjs.base.raw.js:2097
h                                              @  winjs.base.raw.js:1440
__dirname.undefined.P.enter                    @  winjs.base.raw.js:1127
__dirname.undefined.t.Class.define._run        @  winjs.base.raw.js:1343
__dirname.undefined.t.Class.define._completed  @  winjs.base.raw.js:1311
(anonymous function)                           @  configurationService.ts:65
(anonymous function)	                       @  /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/graceful-fs/graceful-fs.js:76
readFileAfterClose                             @  fs.js:404
```

VSCode version: 1.1.1 (tried insider as well)
Node: v6.2.0

**Comment by NinoFloris** [comment]
This is fixed now right?

**Comment by dbaeumer** [comment]
I would say no :-). @isidorn did you change something here?

**Comment by isidorn** [comment]
@dbaeumer I see a commit attached to this issue so I believe I have changed something
https://github.com/Microsoft/vscode/commit/1759568b8b6df4fbb53400f75801607fd43334f4

**Comment by ikkyjeff** [comment]
This is fixed now right?

**Comment by JBLeung** [comment]
This is fixed now right?

**Comment by danielsss** [comment]
Is this fixed right now ?
