### ISSUE TITLE
Visual Studio Code Crashes

### ISSUE THREAD

**Issue by smistert** [Microsoft/vscode#59625]
Version:          Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:04:11.329Z)
OS Version:       Darwin x64 17.7.0
CPUs:             Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3400)
Memory (System):  16.00GB (4.88GB free)
Load (avg):       3, 3, 3
VM:               0%
Screen Reader:    no
Process Argv:     /Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_1823165
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    enabled
                  rasterization:                enabled
                  video_decode:                 enabled
                  video_encode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled

I have no extensions installed. Only the default MAC installation downloaded and installed on 2018-09-26.

Steps to Reproduce:

1. Starts VSC from terminal console passing a file name
1. View the text file and scroll down and up 
2. VSC Crash after a few minutes and print the following message on the console:

2018-09-28 08:14:01.471 code[22801:691781] *** Assertion failure in +[SQRLDirectoryManager currentApplicationManager], /Users/sattard/projects/Squirrel.Mac/Squirrel/SQRLDirectoryManager.m:30

My user is not "sattard" and I don't have Squirrel installed......

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by smistert** [comment]
Thanks Benjamin,

The insider version seems to work just fine!

Sylvain

**Comment by bpasero** [comment]
Ok, could be an installation issue then. I suggest you stay on the insiders version, it is updated daily.

**Comment by smistert** [comment]
Just crashed on me the same way with the Insider version:

2018-10-01 11:04:52.652 Code - Insiders Helper[54600:1320989] Couldn't set
selectedTextBackgroundColor from default ()

[main 11:05:12 AM] update#setState checking for updates

2018-10-01 11:05:12.870 code[54598:1320876] *** Assertion failure in
+[SQRLDirectoryManager currentApplicationManager],
/Users/sattard/projects/Squirrel.Mac/Squirrel/SQRLDirectoryManager.m:30

Illegal instruction: 4
