### ISSUE TITLE
Consider multiline strings/comments when auto detecting indentation

### ISSUE THREAD

**Issue by WOo0W** [microsoft/vscode#59626]
- VSCode Version: 1.27.2
- OS Version: Windows 10

Steps to Reproduce:

1.  Code like this:
```
test = '''
test
  www
    www
'''

def Test():
    pass
```
2. Reopen the file, you will find the tab size has changed to 2

![image](https://user-images.githubusercontent.com/24245520/46214548-fdb2b880-c36d-11e8-9ad5-4fff2fab872d.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
@WOo0W I am not 100% sure what the issue is here? Do you mean that the file is detected to be with indentation Spaces @ 2 when opening it ?

**Comment by WOo0W** [comment]
I think indent check should not be enabled for multi-line string in Python, just like comments.

**Comment by alexandrudima** [comment]
Ok, I understand. The indentation guessing code is language agnostic and does not use syntax highlighting to try to exclude multiline strings or multiline comments. In other words, if the same file were renamed to `test.txt`, the indentation detection results would be 100% the same.

We can use this issue to track the feature request that the indentation detection would take syntax into account, but given this indentation detection needs to execute very quickly when a file is opened (before tokenization is executed), I don't think we will change it...
