### ISSUE TITLE
Auto Save enabled when set to Off

### ISSUE THREAD

**Issue by ttroutindy** [Microsoft/vscode#59622]
I have found that when Auto Save is set to off  and the Auto Save Delay is set to 1000 (default settings), files are saving automatically when they shouldn't. 

Setting the Auto Save Delay to 0 and setting the Auto Save to off will allow files to not auto save. The statement on Auto Save Delay says that it only applies when Auto Save is set to afterDelay, so that seems to be broken.

I have disabled all extensions and tried this with the same results.

**Comment by bpasero** [comment]
@ttroutindy 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by ttroutindy** [comment]
Closing issue, found the problem was that the User Settings was being overwritten by the workspace settings. The Auto Save for the workspace was set to afterDelay which then was using the After Save Delay field.
