### ISSUE TITLE
Extension triggered quick open no longer focuses first item

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#59624]
This doesn't seem to apply to cmd/ctrl+p.

Repro:

1. Install git project manager https://marketplace.visualstudio.com/items?itemName=felipecaputo.git-project-manager
2. Configure paths:

   ```
   "gitProjectManager.baseProjectsFolders": [
       "$HOME/dev",
       "%USERPROFILE%\\Documents\\dev"
   ],
   ```
3. Run `GPM: Open Git Project` command
4. Type "vscode"

1.28.0-insiders (not focused):

<img width="328" alt="screen shot 2018-09-28 at 7 19 14 am" src="https://user-images.githubusercontent.com/2193314/46214116-365f7d00-c2ef-11e8-9d7b-34aee9a8eb73.png">

1.27.2 (focused):

<img width="347" alt="screen shot 2018-09-28 at 7 23 12 am" src="https://user-images.githubusercontent.com/2193314/46214188-63ac2b00-c2ef-11e8-986c-c5c8b8554f43.png">

**Comment by chrmarti** [comment]
@Tyriar Did you have Screen Reader mode enabled in 1.28-insiders?

**Comment by Tyriar** [comment]
@chrmarti yes. Why is there a difference in how quick open handles ctrl/cmd+p and extensions?

**Comment by chrmarti** [comment]
QuickPick does not focus the first item when in screen reader mode to let the screen readers first read the placeholder in the input field. QuickOpen should do the same.
