### ISSUE TITLE
Visual studio code extension host teminated unexpectedly.

### ISSUE THREAD

**Issue by vaibhav0320** [Microsoft/vscode#59620]
- VSCode Version:1.15.1
- OS Version:windows 10

Does this issue occur when all extensions are disabled?: Yes

Removing 'Git' folder from "C:\Program Files\Microsoft VS Code\resources\app\extensions" the problem is solved. So, there is an issue with the files in this folder.

**Comment by joaomoreno** [comment]
Please update your VS Code to the current version: https://code.visualstudio.com/
