### ISSUE TITLE
Open SSH SSH client window pops up when resizing terminal

### ISSUE THREAD

**Issue by guilala** [Microsoft/vscode#59630]
- VSCode Version: Version: 1.28.0-insider (user setup)
Commit: b4d09d27509f2c023f63d4315aa966a5ec7581e9
Date: 2018-09-27T14:44:27.811Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
- OS Version: Windows 10 Home 1803

Steps to Reproduce:

1. Open panel
2. Select terminal (accelerated, canvas) for PowerShell session
3. Connect to some host over ssh
> if the issue didn't occur already
4. Split terminal for second PowerShell
5. Make a second ssh connection
6. Drag border between terminals to resize them
7. An Open SSH SSH client window pops up with content identical to one of the two terminals

Does this issue occur when all extensions are disabled?: Yes

<img width="1041" alt="vscodeghostterminal" src="https://user-images.githubusercontent.com/108651/46216790-a5b18d00-c340-11e8-9603-1924bb48ec0d.png">

**Comment by guilala** [comment]
This issue is not a duplicate of the following:
- Git: Allow to configure location of ssh keys (#33284)
- Feature Request: Remote Operations (#18829)

**Comment by Tyriar** [comment]
@rprichard have you seen this happen before? Looks like the hidden console window is showing 😕

**Comment by rprichard** [comment]
I haven't seen that before, and I wasn't able to reproduce it.

**Comment by Tyriar** [comment]
I expect this to get fixed as part of https://github.com/Microsoft/vscode/issues/45693
