### ISSUE TITLE
Loses My Bug Report -- which was It Won't Install Kite.

### ISSUE THREAD

**Issue by DavidLJ** [Microsoft/vscode#59637]
Issue Type: <b>Bug</b>

1.) I just typed my bug report.  Then clicked "Report a bug" and it gave me this form, without the report I had just typed.

2.) Earlier today it pretended to install Kite, but in reality just gave my the flashing undescores as thumper for half an hour.
2a.) Now it won't even pretend.  It just asks for my e-mail and password, then sits there doing nothing.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Phenom(tm) II X4 965 Processor (4 x 3415)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.50GB (0.44GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
kite|kit|0.40.0
anaconda-extension-pack|ms-|1.0.0
python|ms-|2018.8.0
vscode-yaml|red|0.0.16

</details>

**Comment by Tyriar** [comment]
FYI @RMacfarlane
