### ISSUE TITLE
Terminal.processId property is not updated once terminal's process is changed

### ISSUE THREAD

**Issue by g-arjones** [Microsoft/vscode#59635]
- VSCode Version: 1.27.2
- OS Version: Ubuntu 16.04 64-bit

Steps to Reproduce:

1. [Clone this repo](https://github.com/g-arjones/vscode-task-provider-bug)
2. Run the extension
3. Run the "Terminal Test Task" provided by the extension
4. You should see something like `1111 == 1111` 
5. Run the same task again, you should see that Terminal.processId doesn't get updated

Does this issue occur when all extensions are disabled?: Yes

**Comment by g-arjones** [comment]
@Tyriar How may I help?

**Comment by Tyriar** [comment]
To fix this you need to symlink an extension that uses the API to `~/.vscode-oss-dev/extensions/<extname>` (on macOS, might be different on Linux).

The files of interest are:

- https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostTerminalService.ts
- https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/electron-browser/mainThreadTerminalService.ts
- terminalService, terminalInstance

**Comment by g-arjones** [comment]
Oh, I see. Were you able to reproduce it?

**Comment by Tyriar** [comment]
@g-arjones no, but I believe I've heard this issue before.

**Comment by g-arjones** [comment]
@Tyriar Well, unless I am overlooking something, seems to be a regression from 35ae86231af1afd17bedc69ae89daf6fc3bd0d92
