### ISSUE TITLE
Can't start VSCode without internet connection

### ISSUE THREAD

**Issue by rjmholt** [Microsoft/vscode#59634]
Looked for a duplicate for this -- saw https://github.com/Microsoft/vscode/issues/58581, but there was no indication of what it was a duplicate of.

- VSCode Version: 1.28-insider (also occurs in 1.27.2)
- OS Version: Microsoft Windows 10.0.18247

Steps to Reproduce:

1. Disconnect from internet (I pulled out my Ethernet cable).
2. `code-insiders`

Does this issue occur when all extensions are disabled?: Yes

Full repro:
```
> code-insiders.cmd --disable-extensions
dns.js:246
    this._handle = new ChannelWrap();
                   ^

Error: EFILE
    at new Resolver (dns.js:246:20)
    at dns.js:377:25
    at dns.js:431:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at net.js:45:13
    at net.js:1730:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at internal/child_process.js:6:13
```

**Comment by rjmholt** [comment]
Ah, all those issues look like the same one I'm looking at. Thanks vscodebot.

However, none of those issues give fuller details or say what was fixed.

I'll see if I can collect more information:

```
> code-insiders.cmd --verbose
dns.js:246
    this._handle = new ChannelWrap();
                   ^

Error: EFILE
    at new Resolver (dns.js:246:20)
    at dns.js:377:25
    at dns.js:431:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at net.js:45:13
    at net.js:1730:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at internal/child_process.js:6:13
```

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/45498d93166483c2eff886e28f8dab915ae382fc/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/code-exploration_1.28.0-1538127308_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/VSCodeUserSetup-x64-1.28.0-exploration.exe)

**Comment by rjmholt** [comment]
@bpasero I ran the Windows build and can report that it starts up perfectly without an internet connection :)

**Comment by thecakeisalie25** [comment]
Can reproduce on stable.

**Comment by rjmholt** [comment]
I'll use the exploration build for the next little week or so if that helps @bpasero

**Comment by rjmholt** [comment]
@bpasero Can you link to what issue this one is a duplicate of? I noticed the other issues like it were all marked as duplicates and closed, but there doesn't seem to be an original open issue.

**Comment by bpasero** [comment]
@rjmholt the search functionality in GH is not great, but actually works for this case. We ask people that file issues to use search to reduce work on developers always having to hunt down duplicates.

![before](https://user-images.githubusercontent.com/900690/46271975-542b1d00-c54f-11e8-871e-441cef969e8d.gif)

**Comment by rjmholt** [comment]
Yes I performed that search before using the keyword "internet" and didn't find anything — "offline" was not a term that struck me at the time.

But here you've closed the issue as a duplicate, but haven't noted what of. My assumed convention was that there would be a canonical issue that all others are a duplicate of.

Looks like the first issue is this one: https://github.com/Microsoft/vscode/issues/7570

**Comment by wolf99** [comment]
+1 on estimate of Electron 3 inclusion for release. My v1.28.2 Windows installation reports the Electron  used is v2.0.9. 

As Electron 3.0.0 has now been out for over a month and given the below mentioned percentage, I would have expected that a fast release of VS Code with the fix included would be pretty high priority.

Despite what the media yammers on about we don't all live in the "always on" world just yet. Frankly, an editor that only works when I'm connected to the internet is useless for ~80% of the time 😕
