### ISSUE TITLE
Ctrl+/ to create comment when cursor is at the beginning of the line puts the cursor in a strange position

### ISSUE THREAD

**Issue by dilijev** [Microsoft/vscode#5964]
- VSCode Version: 1.0.0
- OS Version: Win 10 (10586.218)

Steps to Reproduce:
1. Open a JS or C++ file, probably others that use // as the comment token (make sure the appropriate syntax mode is in the bottom right)
2. Place cursor at the beginning of a line (Col 1)
3. Press Ctrl+/
4. Observe that the cursor is now at Col 7 (not the same place in the previous text)

Desired behavior case:
1. same as above
2. Place cursor at any column besides Col 1 (e.g. Col 2)
3. Press Ctrl+/
4. Observe that the cursor is moved 3 columns to the right (the length of the inserted comment token and space `'// '`), and that the cursor is at the same position in the text of the line as it was before pressing the hotkey.

The desired behavior case written above is a much better experience because the code author can better predict where his cursor will be after pressing the hotkey.

Edit: the file I'm editing has CRLF line endings, in case that makes a difference.

**Comment by bpasero** [comment]
Hm I cannot reproduce. @dilijev are you using an extension? Can you try without?

Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions`

**Comment by dilijev** [comment]
I ran VS Code with `code --disable-extensions`. Still repros for me. See screenshots below of steps 2-4 from the repro case.

This also repros when I change the line endings to LF.

I wanted to try to change encoding to ASCII instead of UTF-8 but that wasn't in the list of possible encodings. Is there some other equivalent to ASCII in that list?

![image](https://cloud.githubusercontent.com/assets/494055/14924921/9ada2490-0df9-11e6-9baa-f1d80e06d824.png)
![image](https://cloud.githubusercontent.com/assets/494055/14924932/a5771854-0df9-11e6-9ba1-fb042ff9e150.png)
![image](https://cloud.githubusercontent.com/assets/494055/14924942/ac411554-0df9-11e6-8f1e-2b1b98e8ca17.png)

**Comment by dilijev** [comment]
Confirmed repros in:
- VSCode Version: Code - Insiders 1.3.0-insider (5eaf9f05038b0a9818ebff510e1aafe07ac1ae68, 2016-06-23T05:07:59.360Z)
- OS Version: Windows_NT ia32 10.0.14366

**Comment by octref** [comment]
@alexandrudima Still repros in today's Insider. macOS on a js file.

**Comment by octref** [comment]
Oh nvm you just fixed it 7 hours ago which isn't in Insider yet.
