### ISSUE TITLE
Start without debugging switches sidebar to debug

### ISSUE THREAD

**Issue by alekseyt** [Microsoft/vscode#59649]
Issue Type: <b>Bug</b>

1. Ctrl-Shift-P -> Debug: Start without debugging (Ctrl-F5? I don't know if that's default)

Result: sidebar switches to debug mode.

I ended up setting "debug.openDebug" option to "openOnDebugBreak" (whatever really) as a workaround.

Please also reconsider default value for this option. Before it was probably "openOnFirstSessionStart", this was mildly annoying but it was switching only once and didn't bother me after that, so it was OK-ish.

Now it always interferes with my working layout, i prefer to have source control open in sidebar most of the time. Another example: i'm doing search in files and while search is running, i'm launching app in background (start w/o debugging), sidebar switches to debug and i have to switch it back to see search results.

Nonetheless, i think "Start without debugging" opening debug in sidebar is a plain bug, this won't work anyway, right?

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:11:15.873Z)
OS version: Linux x64 4.4.0-112-generic

<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
nightswitch-lite|gha|2.1.0
cpptools|ms-|0.19.0
Go|ms-|0.6.89
shader|sle|1.1.3
cmake|twx|0.0.17
vscode-todo-highlight|way|1.0.4
lua-for-vscode|xxx|0.0.23

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
This is fixed in latest vscode insiders and will be available in vscode stable in about a week.
