### ISSUE TITLE
Requiring commands in activationEvents seems unnecessary and error-prone

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode#59643]
Why do you require *everything* to be manually spelled out in activationEvents?  It's easy to forget to add it when you add a new command, and then you have a bug which is quite likely to be noticed only by the end user.

It seems like you've got all the information you need already in the package.json to fill out 99% of the activation events automatically.  It seems much better to only require activationEvents for stuff that can't be determined manually.

Thx.

**Comment by alexandrudima** [comment]
@StephenWeatherford Most of the times, there is a correlation between the `contributes` section and the `activationEvents` section. But that is not necessary.

Take, for example, keymap extensions, like this one -- https://github.com/Microsoft/vscode-atom-keybindings/blob/master/package.json . That extension contributes a lot of `keybindings` where a lot of `commands` are named. That does not mean that extension needs to be activated when those commands are invoked. 

So, contributing a keybinding (a binding from a key press to a command) should not necessarily result in the activation of an extension. Similarly, contributing a UI binding (a binding from a F1 list title to a command) should not necessarily result in the activation of an extension. Technically, when one contributes a `commands`, one simply adds an entry with that title in the F1 list. 

I think it is a solid approach to have the `activationEvents` spelled out and not do any magic here on our side.

I agree that can get tedious for you as an extension author, so why don't you write an extension or a task that fills those in for you all the time.

e.g. of a quick js snippet I put together that can help you automate this:

```js
const fs = require('fs');

let pkg = JSON.parse(fs.readFileSync('package.json'));
let commands = pkg.contributes.commands.map(item => item.command);

commands.forEach(function(command) {
    let activationEvent = `onCommand:${command}`;
    if (pkg.activationEvents.indexOf(activationEvent) === -1) {
        pkg.activationEvents.push(activationEvent);
    }
});

fs.writeFileSync('package.json', JSON.stringify(pkg, null, '    '));
```
