### ISSUE TITLE
Shift+Tab doesn't work on Xubuntu 18.04 with LANG=th_TH.UTF-8

### ISSUE THREAD

**Issue by peat-psuwit** [microsoft/vscode#59646]
Issue Type: <b>Bug</b>

I can't de-indent text using Shift-Tab on Xubuntu 18.04 if my locale is set to `th_TH.UTF-8`. The problem doesn't occur if the locale is `C.UTF-8` and doesn't occur if I'm using GNOME desktop (Ubuntu 18.04) even with `th_TH.UTF-8` locale.

Step to reproduce:
1. From an installation of Xubuntu 18.04, install package `language-pack-th` to generate the locale.
2. Install VS Code as usual.
3. Launch VS Code as `LANG=th_TH.UTF-8 code` or `LANG=th_TH.UTF-8 code-insiders`
4. Create a new document and press Tab a couple of times.
5. Press Shift+Tab
Expected behavior: the text gets de-indented.
Actual Behavior: nothing happens.

Workaround: on a system with `th_TH.UTF-8` as a default locale, launch VS Code as `LANG=C.UTF-8 code` instead. As VS Code detach itself from launching terminal, this is relatively painless.

Additional Information:
This is the screenshot from keybinding detection screen, which indicate that VS Code doesn't receive keybinding correctly:
![image](https://user-images.githubusercontent.com/6771175/46229122-b852b300-c38e-11e8-9ac0-27e04999b530.png)

This is the screenshot of `keydown' event, captured from Developer tools' console (+ environment variable related to locale):
![image](https://user-images.githubusercontent.com/6771175/46229199-fcde4e80-c38e-11e8-91ae-b95b39bba2ef.png)

This is key mapping inspection: https://gist.github.com/peat-psuwit/af92ddfedd72993628bf99bbe4e1efc2

P.S.: Using the method in the second picture, I can say that this problem doesn't exist in Electron demo app (with Electron upgraded to 2.0.7) & Chromium 69.0.3497.100 (both showing correct event).

VS Code version: Code - Insiders 1.28.0-insider (caaa5369cb4d22b7481e6ff97252cf92937709eb, 2018-09-28T05:17:56.394Z) (Also reproducible on 1.27.2)
OS version: Linux x64 4.15.0-34-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     P7350  @ 2.00GHz (2 x 1751)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 3|
|Memory (System)|3.60GB (1.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by alexandrudima** [comment]
@peat-psuwit Thank you for the thorough issue!

If `Shift+Tab` is received correctly in the Electron 2.0.9 demo app, then the only thing that could be different that could impact things would be the menu. 

Does this reproduce when disabling native menus? (`window.titleBarStyle` to `custom`) or when hiding them?

**Comment by peat-psuwit** [comment]
With `"window.titleBarStyle": "custom"` as the only setting, the problem is still reproducible both on 1.27.2 &  1.28.0-insider (431ef9d 2018-10-03T12:37:10.832Z).

Upon further (accidental) test, I also found that this symptom (getting 'unknown' keybinding) also happens when pressing letters alone or with 'Shift'. Although it doesn't happen if the letter is pressed with 'Ctrl'. (For example, this will happen if I press 'a' or 'Shift + a', but doesn't happen if press 'Ctrl + a'.) Text input seems to work properly though. All none-letter keys works properly. (And, of course, this doesn't happen with LANG=C.UTF-8).

P.S: For reproduction purpose, The election demo app I use to test is electron/electron-quick-start@dc1585b with electron upgraded to 2.0.7 (not 2.0.9) to match what's used by VSCode.

**Comment by peat-psuwit** [comment]
Update: the issue is still reproducible on Code - Insiders 1.34.0-insider (d234937, 2019-04-05T05:13:22.859Z)
