### ISSUE TITLE
JS suggested auto-imports stopped working with latest insiders release

### ISSUE THREAD

**Issue by jscheel** [Microsoft/vscode#59644]
If I type the name of an exported value and press the autosuggest keyboard shortcut, I no longer get auto-import suggestions. This works properly in the stable release, but is broken in the latest insiders release.

- VSCode Version: 1.28.0-insider  (works in 1.27.2)
- OS Version: macOS 10.12.5

Steps to Reproduce:

1. create exported js value in a module
2. in another file, type the name of the value, press suggestions keybinding, auto-import suggesting is missing

Does this issue occur when all extensions are disabled?: YES

**Comment by jscheel** [comment]
I probably should clarify and say that autocomplete seems totally broken, not just when manually triggering suggestions

**Comment by mjbvz** [comment]
To help investigate, can you please try collecting the TS Server log:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a folder with a `tsserver.log` file in it

Look through that log file for errors or stack traces. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by mjbvz** [comment]
Closing as we need more information to investigate this
