### ISSUE TITLE
Markdown Codeblocks in documentation contain unwanted asterisks

### ISSUE THREAD

**Issue by trevorade** [Microsoft/vscode#59641]
- VSCode Version: 1.27.1
- Monaco Version: 0.14.3

Does this issue occur when all extensions are disabled?: Yes

Steps to Reproduce:

1.  Write a JSDoc with a MarkDown code block in TypeScript (or JavaScript presumably or many other languages):

```typescript
/**
 * Some documentation is **nice**.
 * 
 * Example usage:
 * 
 * ```
 * function main() {
 *   return hello('world');
 * }
 * ```
 */
function hello(world: string): number {
  return 1337;
}
```

2.  View function documentation from auto-completion, hover, or parameter hints.  Unwanted asterisks appear in the code block.

VSCode 1.27.1:
![image](https://user-images.githubusercontent.com/13050011/46225022-45592600-c315-11e8-81f8-42f9ee20a210.png)

Monaco 0.14.3:
![image](https://user-images.githubusercontent.com/13050011/46225092-78031e80-c315-11e8-9a05-0a4e40fc507c.png)

On an unrelated note, you can see some paragraph spacing issues present in Monaco but not VsCode.

## Work around

The workaround for this is to remove the asterisks from the JSDoc:

![image](https://user-images.githubusercontent.com/13050011/46225216-d03a2080-c315-11e8-9502-115dc1c3efda.png)

**Comment by mjbvz** [comment]
Thanks. This is already being tracked upstream by https://github.com/Microsoft/TypeScript/issues/23517

**Comment by trevorade** [comment]
Thanks @mjbvz,

While I've got your ear and you seem good at tracking down duplicate issues... do you have an Issue which tracks supporting MarkDown for documentation from .d.ts files?

Example (see below :
![image](https://user-images.githubusercontent.com/13050011/46230067-a1777680-c324-11e8-96c9-c262d42979f7.png)

For reference, the code I'm playing with at the [Monaco Playground](https://microsoft.github.io/monaco-editor/playground.html) is:

```javascript
monaco.languages.typescript.javascriptDefaults.addExtraLib(
    `/**
 * A delicious _cooker_ of \`rabbits\`.
 * 
 * Call like this:
 * 
 * \`\`\`
 * aaCookRabbit(0); // Cooking rabbits is cruel
 * \`\`\`
 * 
 * Don't mess with those rabbits.
 * 
 * @param num The number of rabbits to cook.
 * @return How many rabbits got away.
 */
function aaCookRabbit(num: number): number;`,
    'myDefault:some.file.d.ts'
);

monaco.languages.typescript.javascriptDefaults.setCompilerOptions({
    allowJs: true,
    allowNonTsExtensions: true,
    target: monaco.languages.typescript.ScriptTarget.ESNext,
    checkJs: true,
    lib: ['myDefault:some.file.d.ts'],
});

monaco.editor.create(document.getElementById("container"), {
    value: "",
    language: "javascript"
});
```
