### ISSUE TITLE
Mardown in JSDoc from TypeScript .d.ts lib treated as plain text

### ISSUE THREAD

**Issue by trevorade** [Microsoft/vscode#59654]
- VSCode Version: 1.27.1
- Monaco Version: 0.14.3

Steps to Reproduce:

1.  Register a .d.ts file with `monaco.languages.typescript.FOOscriptDefaults.addExtraLib`
2.  Trigger documentation in autocomplete or hover.  Markdown in JsDocs of the .d.ts file is not rendered:
    ![image](https://user-images.githubusercontent.com/13050011/46234216-d38fd500-c332-11e8-8029-1ecc3409a4a4.png)

The unwanted asterisks in the MarkDown code block is tracked by Microsoft/TypeScript#23517 but the larger issue here is separate.

Here's the code I'm using in the [Monaco Playground](https://microsoft.github.io/monaco-editor/playground.html):

```javascript
monaco.languages.typescript.javascriptDefaults.addExtraLib(
    `/**
 * Function documentation **bold** _italics_.
 * 
 * Example :
 * 
 * \`\`\`
 * aaExampleFunction(0);
 * \`\`\`
 * 
 * More markdown text
 * 
 * @param num Parameter description
 * @return Return type description.
 */
function aaExampleFunction(num: number): number;`,
    'myDefault:some.file.d.ts'
);

monaco.languages.typescript.javascriptDefaults.setCompilerOptions({
    allowJs: true,
    allowNonTsExtensions: true,
    target: monaco.languages.typescript.ScriptTarget.ESNext,
    checkJs: true,
    lib: ['myDefault:some.file.d.ts'],
});

monaco.editor.create(document.getElementById("container"), {
    value: "",
    language: "javascript"
});
```

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/monaco-editor#1079
