### ISSUE TITLE
some problems about UI

### ISSUE THREAD

**Issue by endingly** [Microsoft/vscode#59661]
Issue Type: <b>Bug</b>

I want the toolbar to be consistent with the theme elements.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200H CPU @ 2.80GHz (4 x 2794)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (4.88GB free)|
|Process Argv|D:\Users\47155\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.4
vscode-github|Kni|0.30.0
vscode-language-pack-zh-hans|MS-|1.27.2
open-html-in-browser|pea|0.0.3
material-icon-theme|PKi|3.6.0
html-css-class-completion|Zig|1.17.1

</details>

**Comment by Tyriar** [comment]
Can you point out the problem with a screeshot?
