### ISSUE TITLE
Animated Dropdown Menus

### ISSUE THREAD

**Issue by beastdestroyer** [microsoft/vscode#59665]
Continuation of #56021 to meet guidelines for feature-requests.

In light of new custom controls, I feel that the small fades dropdowns have could have some additions. To detail them individually :

1. Sub Dropdowns
  - Sub dropdowns (ones indicated with an arrow), when hovered on, could have the menu shoot out from the side and exalnd down to full height, where the items would then fade in. This is actually similar to some Microsoft Apps that I've used also.

2. Menu Uncollapsing
  - Similar to No. 1, when menus are toggled, they could exapnd to max width and then max-height with the items appearing afterwards.

3. Covering the individual menu items and menu dividers 
  - They should slide in and fade from translarent to opaque. The distance for slide can be small but large enough so that it is opaque when sliding stops, and vice versa. 

Possibly? Transition betweem adjacent dropdowns 

Similarly to Office 2016, when a tab is clicked, it transitions the ribbon to have the new items. This could possibly be done in VSCode but may be hard since all dropdowns have separate instances, rather than re-rendering the same element

Let's say a dropdown such as File is active, then Edit is clicked: it would fade out the menu items and slide to them left, move the box over and fade in the new items and slide them in from the right. It would go the opposite way if it was from Edit to File.

These are purely suggestions and it doesn't matter if they aren't considered. Thanks for reading

**Comment by misolori** [comment]
Thanks for the suggestions! The dropdown menus that we use for macOS are from Electron (which have no customization options), but the Windows/Linux custom menu might be able to explore this.
