### ISSUE TITLE
Consecutive backslashes fail to work in snippets

### ISSUE THREAD

**Issue by wdscxsj** [Microsoft/vscode#59668]
- VSCode Version: 1.27.2
- OS Version: Windows 10

Steps to Reproduce:

Say we want to add a linebreak between "hello world" in a LaTeX or any other snippet:

```
"hw": {
    "prefix": "hw",
    "body": "hello\\\\\nworld"
}
```

Expected:

```
hello\\
world
```

Got:

```
hello\
world
```

The expected result is achieved with 2 extra backslashes:

```
"hw": {
    "prefix": "hw",
    "body": "hello\\\\\\\nworld"
}
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
https://github.com/Microsoft/vscode/issues/33933#issuecomment-328793257
