### ISSUE TITLE
Powerline problems in integrated terminal on Fedora 28

### ISSUE THREAD

**Issue by brndd** [Microsoft/vscode#59676]
![screenshot_20180929_190252](https://user-images.githubusercontent.com/5822375/46247929-1e851780-c41b-11e8-93ee-b1ab49a4969f.png)

The integrated terminal fails to display Powerline characters when they are installed through the Fedora package `powerline-fonts`. This package should enable Powerline support for many fonts without having to use patched fonts. It works with the fonts Liberation Mono and Noto Mono in Konsole, but does not work in the vscode terminal using the same fonts.

 

- VSCode Version: 1.27.2
- OS Version: Fedora 28

Steps to Reproduce:

1. Install Powerline fonts on Fedora 28 using `dnf install powerline-fonts`
2. Use a shell with these enabled
3. Powerline characters work in konsole, but not the Visual Studio Code integrated terminal despite both of them using the same font.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Did you set the font in vscode? See https://github.com/Microsoft/vscode/issues/7116

**Comment by brndd** [comment]
Yes. More specifically, the way [this particular Fedora package](https://fedora.pkgs.org/28/fedora-x86_64/powerline-fonts-2.6-7.fc28.noarch.rpm.html) installs the Powerline glyphs it should not be necessary to change the font. To my understanding, what the package does is installs a separate PowerlineSymbols.otf font and creates a Fontconfig rule that enables the glyphs for all supported monospace fonts. Here is an exceprt from the fontconfig file it provides:

```
<alias>
        <family>monospace</family>
        <prefer><family>PowerlineSymbols</family></prefer>
</alias>
```

My font in vscode is set to Droid Sans Mono (and then monospace), which is supported by the package, but I've also tried with Liberation Mono. Both of them display the glyphs in Konsole, but do not in vscode. Perhaps vscode does not respect the fontconfig rule? It's entirely possible for this to be a bug in the Fedora package, too. I admit I am an ignoramus when it comes to font rendering.

**Comment by Tyriar** [comment]
@brndd I suspect it's Chromium not respecting it, I wouldn't be surprised if it treats "monospace" specially as well to improve website compatibility. I'm closing this as out of scope as powerline fonts do work when configured explicitly, and the issue you're seeing is likely an upstream problem (or as designed).

**Comment by brndd** [comment]
For what it's worth, you're right; it appears to be a Chromium issue. At least the fonts don't work in the Chromium browser either, but do in Firefox (which is clearly the superior browser because of this!)
