### ISSUE TITLE
"browse.VC.db" created after opening folder in cmd line & remains when VS Code is closed

### ISSUE THREAD

**Issue by nbosco** [Microsoft/vscode#5967]
- VSCode Version: 1.0.0
- OS Version: OSX 10.11.4

Steps to Reproduce:

1. Open a repository with cmd line 
2. A db file named "browse.VC.db" will be created automatically, it doesnt delete after closing VS Code is closed

https://gyazo.com/ed6c5ebad70f9c6da2ca34a164ba6fe7

**Comment by bpasero** [comment]
@nbosco this is due to the installed C++ extension and was reported already.
