### ISSUE TITLE
1.27 installer moved code.exe from bin, but path stayed the same

### ISSUE THREAD

**Issue by DarwinJS** [Microsoft/vscode#59673]
- VSCode Version: 1.27
- OS Version: Windows 10

Steps to Reproduce:

1. Install legacy VS Code which puts "c:\program files\microsoft vs code\bin" on the path
2. Update with installer for 1.27
3. Using "code" at the command line no longer works because path is not to remove "c:\program files\microsoft vs code\bin" and add an appropriate path.  (the \bin subfolder no longer exists)

I find "code.exe" in "c:\program files\microsoft vs code\_" - but underbar as a folder level is odd to the point of making me wonder if I should set the path to that or not.

Perhaps the path check code is a substring rather than a specified check?

**Comment by joaomoreno** [comment]
This happened due to a failed update, unfortunately. Can you fully reinstall VS Code?
