### ISSUE TITLE
Django: Debugging fails to run

### ISSUE THREAD

**Issue by GaramNick** [Microsoft/vscode#59674]
- VSCode Version: 1.27.2
- OS Version: Ubuntu 16.04.5

Steps to Reproduce:

1. Add Django configuration to launch.json
`{
            "name": "Django",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/manage.py",
            "args": [
                "runserver",
                "--noreload",
                "--nothreading"
            ],
            "pythonPath": "/home/ubuntu/.local/share/virtualenvs/xyz/bin/python",
            "django": true
        }`
2. F5
3. Terminal output:
`cd /home/ubuntu/CODE/djangoapp ; env "DEBUG=True" "DJANGO_SECRET_KEY=xyz" "PYTHONIOENCODING=UTF-8" "PYTHONUNBUFFERED=1" "PYTHONPATH=/home/ubuntu/.vscode/extensions/ms-python.python-2018.8.0/pythonFiles/experimental/ptvsd" /home/ubuntu/.local/share/virtualenvs/xyz/bin/python -m ptvsd --host localhost --port 40075 /home/ubuntu/CODE/djangoapp/manage.py runserver --noreload --nothreading
bash: !g$!g!: event not found`
4. Prompt: Timeout waiting for debugger connection

`!g$!g!` is a snippet from the Django secret key. I assume the debugger fails when reading this variable from the .env file.

Does this issue occur when all extensions are disabled?: No, Python is not recognised without the extension.

**Comment by isidorn** [comment]
https://github.com/Microsoft/vscode-python
