### ISSUE TITLE
Fonts are not equal in width on macOS Mojave

### ISSUE THREAD

**Issue by Kerminate** [Microsoft/vscode#59688]
I have updated to macOS 10.14 (Mojave) and I have noticed that fonts are not equal in width on VSC. The font I am using is Menlo.
![image](https://user-images.githubusercontent.com/26789139/46254508-28faec00-c4c3-11e8-84b6-e2885b36c769.png)

**Comment by zac-garby** [comment]
Looks like ligatures are messing up "fi" combinations. See if you can disable ligatures in settings.

**Comment by Kerminate** [comment]
Thanks.It is true that setting the disabling of the ligatures text is normal.

**Comment by Kerminate** [comment]
> Looks like ligatures are messing up "fi" combinations. See if you can disable ligatures in settings.

Thanks.It is true that setting the disabling of the ligatures text is normal.
