### ISSUE TITLE
Javascript short circuit syntax not respected by syntax highlighting 

### ISSUE THREAD

**Issue by bradbart** [Microsoft/vscode#5968]
- VSCode Version: 1.0.0 fa6d0
- OS Version: Windows 10 

Steps to Reproduce:

1. Write a function in a javascript function with the following definition: 
```javascript
function test(err) {
    err && return; 
    console.log('error'); 
}
```

Even though this syntax is valid, VS code underlines the return statement indicating that it expects an expression and that the console.log code is unreachable.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#8530
