### ISSUE TITLE
Contents of the window rendered within the editor

### ISSUE THREAD

**Issue by lssbq** [Microsoft/vscode#59682]
Issue Type: <b>Bug</b>

screen shot
![image](https://user-images.githubusercontent.com/17997151/46251306-18765180-c482-11e8-83d4-ea393c30a4b7.png)

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.88GB (23.13GB free)|
|Process Argv|C:\Users\shanba\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|33%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.6.0
tslint|eg2|1.0.39
prettier-vscode|esb|1.6.1
vs-code-xml-format|fab|0.1.5
Angular2|joh|6.1.5
vs-color-picker|lih|0.7.0
vscode-exec-node|mir|0.5.0
team|ms-|1.136.0
debugger-for-chrome|msj|4.10.2
material-icon-theme|PKi|3.6.0
vscode-hexdump|sle|1.6.0

</details>

**Comment by lssbq** [comment]
If I put the cursor at then end of the file, this image will flashing with the cursor.
It is randomly appearing.

**Comment by Tyriar** [comment]
Do you mean that the foreground window appears and flashes with the cursor? But it doesn't actually exist?

**Comment by lssbq** [comment]
Well, from the attached picture you can find the flushing image is like a screen shot in my current active monitor(that time I only have one maximize VSCode). BTW, I have 3 monitors.

And this issue encounted after I upgrade to 1.27.0.

It does not affect the functionality except for appearance. And I wonder that VS will monitor my screen or just a weird bug.

**Comment by bpasero** [comment]
@lssbq a couple of questions:
* does it reproduce if you run "code --disable-gpu"?
* does it reproduce

**Comment by thered121** [comment]
@bpasero I am experiencing the same issue (reported it in issue #61001 ) and can confirm that launching code --disable-gpu remediates the issue (running version 1.28.2 now).

**Comment by bpasero** [comment]
@thered121 can you test those builds linked in https://github.com/Microsoft/vscode/issues/59682#issuecomment-432564848

**Comment by thered121** [comment]
@bpasero I can confirm the Windows Exploration Build (1.29.0) works as expected, I can't confirm for Linux or macOS as I do not have access to any devices of those types.

**Comment by bpasero** [comment]
@thered121 great thank you, this issue does not seem to exist on any platform but Windows.

**Comment by bpasero** [comment]
Closing this issue given that we plan to release VSCode stable early February with Electron 3.x. If you want to benefit from the fix already, consider to use our insiders version that already contains the fix: https://code.visualstudio.com/insiders/
