### ISSUE TITLE
Extension Pack tab missing for Java Extension Pack

### ISSUE THREAD

**Issue by akaroml** [Microsoft/vscode#59684]
Java Extension Pack was updated to use the new "extensionPack" entry in package.json. However, the Extension Pack tab is missing in VS Code:
<img width="796" alt="screen shot 2018-09-30 at 8 54 50 am" src="https://user-images.githubusercontent.com/16755094/46251744-90e30f80-c48e-11e8-8ef2-d6d04af4dd30.png">
Instead, we see "Contributions" and "Changelog"

But for other extension packs, VS Code works this way:
<img width="728" alt="screen shot 2018-09-30 at 8 56 18 am" src="https://user-images.githubusercontent.com/16755094/46251751-bc65fa00-c48e-11e8-8c6a-77b9cf589680.png">
And now we see "Extension Pack"

Do we miss anything?

**Comment by sandy081** [comment]
@akaroml It is because of using old version of `vsce` to publish the extension. Please use the latest `vsce` and try.

**Comment by akaroml** [comment]
@sandy081 thank you for the info.

@testforstephen please help upgrade `vsce` to the latest version in our CI pipeline.
