### ISSUE TITLE
Ubuntu Bash, file not found

### ISSUE THREAD

**Issue by apollomatheus** [Microsoft/vscode#59685]
Issue Type: <b>Bug</b>

All files created directly through VSC is not saved in ubuntu folder, so you need to restart the terminal.
I think the solution would be to create a pipe connection between ubuntu bash and VSC, so every new file is registered by linux system.

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.17134

**Comment by Tyriar** [comment]
Can you elaborate a little more on the problem? Some repro steps would be great.

**Comment by apollomatheus** [comment]
Usually I open all my workspaces in WSL root folder.
In this case, the steps would be:

1) Open any folder inside roots ( Using **VSC** )
2) Create a file in the **VSC panel**, inside the folder.
3) Now in the **Bash terminal**, you won't be able to find the file, until you reopen the terminal.

I always need to restart the terminal before run 'make' or any other task.

**Comment by Tyriar** [comment]
This must be a problem with wsl then, we're just hosting the wsl process and don't control the output.
