### ISSUE TITLE
Untitled files sometimes remain open in the background

### ISSUE THREAD

**Issue by garyking** [Microsoft/vscode#59680]
- VSCode Version: Version 1.27.2 (1.27.2)
- OS Version: macOS 10.13.6 (17G65)

Steps to Reproduce:

1. Open a new untitled tab. 
2. Type something in it. 
3. Close it, and it will tell you there are still unsaved changes. Choose `Don't save`.
4. Sometimes, the `1` badge will still appear on the `Explorer` icon, indicating that the unsaved document is still open in the background.

This occurs to me about once a day. I notice it when I close a workspace, and it notifies me that there are still unsaved changes, yet I can't see any, except for the badge. I frequently open new untitled tabs, type something in them, then close them, without saving. 

It's very difficult to pinpoint the cause. It seems to matter at what point I close the tab. 

The problem may *possibly* occur when I close the document and the `Git` icon is showing the `refresh` badge. Since the `refresh` badge appears for less than a second, and perhaps once every minute or so, it's hard to reproduce this event purposely, yet the event of closing an unsaved document and this badge appearing occurs pretty frequent on a daily basis, by accident.

I've had this bug for months, perhaps about three months or more.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
First time I hear this, please try to distill reproducible steps 👍

**Comment by garyking** [comment]
Yeah I have been having this problem for months, but I have never been able to purposefully reproduce it. It happens about once a day. I have never seen anyone else report this. 

I was able to reproduce this once, by simply opening a VSC workspace, then opening a new document, typing random text, then closing it and choosing "Don't save". This tells me that whatever causes it, isn't some action that I personally take. Some automatic action that VSC performs, must conflict with the closing of the document, at the exact same time. 

Could very well be an extension that's causing the problem too, but that's very hard to pinpoint. I'll just report back if I am ever able to reproduce this.

**Comment by bpasero** [comment]
Yeah please do.

**Comment by bpasero** [comment]
@garyking that is weird. do you know ever get out of the state of having this invisible file or not?

**Comment by garyking** [comment]
No, once an invisible file exists, I've never been able to get rid of it, other than closing the window and choosing `Don't save`.

**Comment by bpasero** [comment]
@garyking ok but after doing so, it does not come back at least.

**Comment by bpasero** [comment]
What I find weird is that you end up with a file path of `file:///Untitled-1`. That does not sound right unless you maybe opened VSCode on root folder?

**Comment by garyking** [comment]
Nope, I always open VS Code workspace files, and they're all in `~/Projects/`.

**Comment by garyking** [comment]
I think that this bug happens when I close an untitled tab, and the "unsaved" badge on the Explorer icon refreshes (it flashes; as in, it disappears then re-appears), at the exact same time that I close the untitled file.

**Comment by bpasero** [comment]
@garyking you get first prompted to save or discard the untitled file right?

**Comment by garyking** [comment]
Yeah, if untitled document has the unsaved icon, yet there's no content, and if I try to close it, then I do get prompted to save, just like any unsaved document.

**Comment by bpasero** [comment]
For me when I close an untitled file, the dirty counter goes down nicely. Is this when you have more than one dirty file maybe?

**Comment by garyking** [comment]
No, this bug is that occasionally, when I close an untitled file, the dirty counter does not go down. It is very difficult to reproduce. Like I said, I've noticed that the dirty icon on the Explorer icon will sometimes "refresh" (disappear then re-appear), and if I close an untitled document at the exact same time, then the untitled document seems to remain open in the background.

**Comment by bpasero** [comment]
I wonder if there is any exception, can you:

Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by garyking** [comment]
Am I supposed to open the console, then reproduce the bug? Because the bug is very difficult to intentionally reproduce.

**Comment by bpasero** [comment]
@garyking yeah so if there is actually an exception you would see it also when not running with --verbose by checking the developer console output.
