### ISSUE TITLE
Suppressing "The import path cannot end with a '.ts' extension" error?

### ISSUE THREAD

**Issue by hooper-hc** [Microsoft/vscode#59690]
when i use 

`import { PI } from './module.1.ts'` 

import an  module . 

vscode linter notice  me an error 

'The import path cannot end with a ".ts" extension. Consider changing to import “./module.1”。'

hao can i hidden the notice ?

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#27481
