### ISSUE TITLE
Keyboard shortcut to navigate and close "global search"

### ISSUE THREAD

**Issue by humblecoder** [Microsoft/vscode#59699]
I use "global search" reasonably often.  However, once I've used it, I need easy access to the results, and an easy way to get rid of the pane.  As an example, in Atom.io, the problem is solved by opening the global search in its own tab, thereby treating it like any other "citizen"; after which a quick `CMD + W` closes it.  Also, the results are easily navigable with the keyboard in said tab.  Similar behavior in VS Code would be desirable.

**Comment by roblourens** [comment]
> easy access to the results

cmd+shift+f?

> an easy way to get rid of the pane

cmd+b?

It's not clear what new feature you're asking for, can you be more specfic?

**Comment by humblecoder** [comment]
@roblourens `cmd + b` only toggles the left pane.  I have `Search` set up to open on the right side because I use the left side 100% of the time for the file tree view.  Also, I'm not interested in toggling it, but in actually closing it.  I realize that if it's a pane that's simply semantics, but I want it to go away no matter the positioning.  Again, I'm not sure if it's feasible, but it seems like having it open in a **tab**  (instead of a pane) might be an option;  unless you could recommend a plugin.

**Comment by roblourens** [comment]
Sounds like you have search in the panel, cmd+j will toggle that.

There is a feature request for search in a tab: https://github.com/Microsoft/vscode/issues/23931

**Comment by humblecoder** [comment]
@roblourens `cmd + j` did it!  I'll follow the "search" thread.  Thanks.
