### ISSUE TITLE
Git: Support fetch prune

### ISSUE THREAD

**Issue by vicary** [Microsoft/vscode#59693]
Issue Type: <b>Feature Request</b>

Currently if a remote branch is deleted by others, the only way to have Code know about it is to manually run `git fetch -p` in the terminal and then the `Git: Fetch` command in Code.

We should at least have an option, if not default, to add `-p` on `Git: Fetch` or `Git: Sync`.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:04:11.329Z)
OS version: Darwin x64 18.0.0

**Comment by usmanhf** [comment]
Hey I'd like to work on this feature. It might take me a couple of days to get started because of midterms, so if anyone else solves it in the meantime that's cool. :)

**Comment by greybax** [comment]
Is this issue could be closed?

**Comment by joaniedavis** [comment]
Was this issue closed by #59735? If so should it be closed?

**Comment by joaomoreno** [comment]
Closed!
