### ISSUE TITLE
settings.json should open in plain editor like keybindings.json

### ISSUE THREAD

**Issue by safield** [Microsoft/vscode#59706]
When I open the default keybindings editor UI, it gives me an option to open keybindings.json file.

When I proceed to open keybindings.json file, it will open it in a normal editor view. This contains all the functionality of a normal editor window.

Conversely, opening settings.json does not match this. In my opinion, it should.

When I open the default settings editor view, it allows me to open the settings.json. When I do so, It opens in a special editor view with a limited search box.

The search box and search functionality does not behave as expected.

-editor.action.nextMatchFindAction does not work
-editor.action.moveSelectionToNextFindMatch
-match case, match whole word, and match regular expression do not work.

Settings.json should open in plain editor like keybindings.json

**Comment by bpasero** [comment]
`"workbench.settings.openDefaultSettings": false`

**Comment by safield** [comment]
That setting does specifically do what is requested here.

"workbench.settings.openDefaultSettings": false opens only the user settings.json....

What I requested is that open settings.json behave exactly as opening keybindings.json.

It should open BOTH the default settings and the user settings, side-by-side, but both in normal text editors, and with normal search, and not the limited settings search box.
