### ISSUE TITLE
Settings.json search box fails to match lines starting with "//  - "

### ISSUE THREAD

**Issue by safield** [Microsoft/vscode#59707]
Version: 1.28.0-insider
OS: Linux Mint 19 (Cinnamon 3.8.8).

-Open the default settings editor UI.
-hit the "..." under the search box hit select "Open settings.json"
-search for a string in any line that begins with "//  - "

The search will fail to match.

**Comment by sandy081** [comment]
@safield Search bar tries to match settings and matches comments only for default settings. To search in comments you can use normal editor find.

![image](https://user-images.githubusercontent.com/10746682/46275692-1bdf0b00-c55e-11e8-9aca-20e94de4f899.png)

**Comment by safield** [comment]
I might be confused, but I can not find a "normal editor find".

When I hit ctrl+F it just focuses the specialised settings search box. I am unable to open a normal editor find box.

**Comment by sandy081** [comment]
In Settings Editor default Find command focuses to Search box. You can use Edit -> Find to open find box in the file. If you want that to be default behaviour you can update following in `keybindings.json` file

```
{
    "key": "cmd+f",
    "command": "-settings.action.search",
    "when": "inSettingsEditor"
},
{
    "key": "alt+cmd+f",
    "command": "settings.action.search",
    "when": "inSettingsEditor"
}
```

**Comment by safield** [comment]
This is not a sufficient solution.

The normal editor find box will only open if I am focused in the user settings json editor. If I am focused in the default settings editor pane on the left, the find box will not open. The default settings is of course the much larger file, and the only one I am motivated to perform searches in.

In my opinion I think the settings editor interface could be rethought to be a much more reliable and consistent user experience based on simpler design.

**Comment by sandy081** [comment]
@safield If you are on latest VS Code you should be seeing a new settings editor already

![image](https://user-images.githubusercontent.com/10746682/46393194-76a26f00-c6e4-11e8-93a8-335a6bbc5150.png)
