### ISSUE TITLE
Go to definition stuck and taking up processor resource

### ISSUE THREAD

**Issue by fittyCent** [Microsoft/vscode#59702]
Issue Type: <b>Bug</b>

Right click and select "Go to Definition". Sometimes VSCode gets stuck looking for the definition and doesn't find it somehow but it keeps trying, taking up a significant amount of processing resource. Laptop's fan starts going crazy, and there's no way to stop it unless I close vscode and reopen.

Metadata:
macOS mojave (was happening high sierra too)
javascript
react.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:04:11.329Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 7, 7|
|Memory (System)|8.00GB (0.05GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
php-intellisense|fel|2.3.5
auto-close-tag|for|0.5.6
ftp-simple|hum|0.6.7
highlight-matching-tag|vin|0.4.4
html-css-class-completion|Zig|1.17.1

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?
