### ISSUE TITLE
Add a setting to specify an alternative theme for copy with syntax highlighting

### ISSUE THREAD

**Issue by scottbass** [microsoft/vscode#59709]
I searched before adding this feature request.  Apologies if it is a duplicate.
This request is similar to Remove background color for "Copy text with formatting" feature #23734 which is closed.

I use a dark theme but, when copying to email, MS Word, etc, I don't want the dark background, but I do want the rest of the syntax highlighting.  But, the dark theme may mean that other formatting, when applied to say a white background, would be unreadable.

A solution would be the ability to specify a default theme when "Copy text with formatting".  If that setting is not specified, the current theme would be used (as it is now).  If that setting is specified, I would want that theme to override all my other settings.

For example, I use these settings to override my theme (Monokai):

    "editor.tokenColorCustomizations": {
        "comments": "#19fd05"
    },
  "workbench.colorCustomizations": {
    "editor.background": "#000000"
  },

I would want those settings to be ignored;  I'm happy with being forced to create (or find) a (light) theme that explicitly sets all the formatting I want for copy text with formatting.

A 2nd possible option would be to set the default theme as described above, but also allow the selection of a specific theme via a dropdown when the copy is done, say via Cntl-Shift-V or Cntl-Alt-V, or some other key binding.

**Comment by rebornix** [comment]
Related https://github.com/Microsoft/vscode/issues/20837
