### ISSUE TITLE
Problem pane reports and persists errors in plugin info page

### ISSUE THREAD

**Issue by aaroncraig10e** [Microsoft/vscode#59708]
Issue Type: <b>Bug</b>

I'm on VSCode Insiders.

Navigate to Plugins > Codestream

In the problems pane, I see an error reported (for the `cSpell Checker` plugin) for `webview.html` inside the codestream plugin package.

Should the problem pane even be sending plugin files for code checks?
When I navigate away from the plugin page back to my code, the error message persists.

Related:
- https://github.com/Microsoft/vscode/issues/59363
- https://github.com/Microsoft/vscode/issues/58088

VS Code version: Code - Insiders 1.28.0-insider (caaa5369cb4d22b7481e6ff97252cf92937709eb, 2018-09-28T05:12:22.044Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.58GB free)|
|Process Argv|-psn_0_6034881|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.1.0
project-manager|ale|9.0.1
codestream|Cod|0.13.0
vscode-eslint|dba|1.6.0
javascript-ejs-support|Dig|0.3.2
githistory|don|0.4.2
gitlens|eam|8.5.6
tslint|eg2|1.0.39
prettier-vscode|esb|1.6.1
vscode-pull-request-github|Git|0.1.6
jenkins-declarative-support|jmM|0.1.0
terraform|mau|1.3.5
dotenv|mik|1.0.1
python|ms-|2018.8.0
atom-keybindings|ms-|3.0.4
azure-account|ms-|0.4.3
vsliveshare|ms-|0.3.735
debugger-for-chrome|msj|4.10.2
vscode-jest|Ort|2.9.2
vscode-docker|Pet|0.3.1
material-icon-theme|PKi|3.6.0
ruby|reb|0.20.0
java|red|0.31.0
jenkinsfile-support|sec|0.1.0
slack|soz|0.0.14
code-spell-checker|str|1.6.10
vscode-java-debug|vsc|0.13.0
vscode-java-test|vsc|0.9.0
vscode-react-native|vsm|0.6.18
markdown-all-in-one|yzh|1.6.2

(6 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
This seems like a bug with code stream. I believe they are somehow causing `webview.html` to be opened as a text document instead of as webview content. It's possible they are using the old `TextDocumentContentProvider` API but I'm not sure. Using the new Webview API this should never be possible

Please file the issue upstream
