### ISSUE TITLE
VS Code writes the log to FAR Manager panel

### ISSUE THREAD

**Issue by softshape** [Microsoft/vscode#5971]
- VSCode Version: 1.0.0
- OS Version: Windows 10

Steps to Reproduce:

1. Run Far Manager (www.farmanager.com)
2. Run VS Code.

You'll see VS Code logs in the Far Manager console they just fill the panels making impossible to work until you reload panels.
![snap 2016-04-29 at 14 00 14](https://cloud.githubusercontent.com/assets/107505/14909196/3845aefc-0e13-11e6-868d-241882612438.png)

**Comment by bpasero** [comment]
@softshape make sure you run code from the C:\Program Files\VS Code\bin folder.

@joaomoreno given the amount of issues we get from this I suggest you add an entry to our FAQ :)

**Comment by joaomoreno** [comment]
@softshape Code.exe will output much garbage to the console, we can't seem to prevent it. If you use the `.zip` distributable, you are stuck. If you use the `Setup.exe` one, make sure you launch Code from `C:\Program Files (x86)\Microsoft VS Code\bin\code.cmd`.

@bpasero What would that entry contain? 😕

**Comment by softshape** [comment]
I just use the shortcut which VS Code installer adds to Windows Start menu. It points to "C:\Program Files (x86)\Microsoft VS Code\Code.exe".

**Comment by joaomoreno** [comment]
Yeah that's the one that won't work. If you want to launch it from the command line, you should use `C:\Program Files (x86)\Microsoft VS Code\bin\code.cmd`. Setup adds `C:\Program Files (x86)\Microsoft VS Code\bin` to your `%PATH%` for that reason.

**Comment by softshape** [comment]
I launch it from Start menu, not from FAR Manager. It's just opened on my computer all the time.

**Comment by joaomoreno** [comment]
This is strange. Let me see if I get the straight: you have Far Manager running on some terminal window; you then, using the mouse, go to the start menu, open Code and suddenly Code's output appears in Far Manager's terminal window?

**Comment by softshape** [comment]
Just found the reason. I use VS Code as an alternative editor on Far Manager. This is the case when VS Code is actually started from command line. After updating Far editor settings to C:\Program Files (x86)\Microsoft VS Code\bin\code.cmd the problem solved. Thank you!!!!
