### ISSUE TITLE
Auto block comment in Typescript for Arrow functions is not working

### ISSUE THREAD

**Issue by rkramakrishna17** [Microsoft/vscode#59723]
- VSCode Version: 1.27.2
- TypeScript Version: 3.0.3
- Angular Version: 6.0.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Create an arrow function inside an angular component
2. Then for writing a block comment for the arrow function, enter '/**'
3. Then auto suggest will popup prompting JsDoc comment
4. After selecting the suggestion, the params are not being listed

example:
for a normal function:

`example1 (val1) {`
`    console.log(val1);`
`}`

Here when you start typing '/**' before the example 1 function, then JsDoc auto suggest pops up.
After you select that, the code appears like this
    `/**`
    ` * `
    ` * @param value1` 
    ` */`
    `example1 (value1) {`
    `     console.log(value1);`
    `}`

But when you type the same for arrow function
`example2 = (value1) => {`
`    console.log(value1);`
`}`

Here when you start typing '/**' before the example 2 function, then JsDoc auto suggest pops up.
After you select that, the code appears like this
    `/**`
    ` * `
    ` */`
    `example2 = (value1) => {`
    `     console.log(value1);`
    `}`

The function params are missing

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Is `example2` inside of a class? Is a declaration (using `let`, `const`, or `var`), or just a normal assignment?
