### ISSUE TITLE
Intellisense, auto complete, confirmed and selected using tab!

### ISSUE THREAD

**Issue by wesleyolis** [Microsoft/vscode#59721]
Issue Type: <b>Bug</b>

Hi,

The productivity loss I have from the space key, automatically selecting an item, is insane.
Please return the functionality to be tab, because everytime I type "fieldA :" I now have my field name change some auto suggestioned delay pop up value,
because I am typing faster than the computer.

I must now type "FieldA" [escape] [space] [colon]

Kind Regards,

Wesley Oliver

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:04:11.329Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.45GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-enhanced|shd|0.3.8
json-schema-validator|tbe|0.1.0

</details>

**Comment by jrieken** [comment]
> The productivity loss I have from the space key, automatically selecting an item, is insane.

This isn't something that we have defined - it's still tab and enter. This can be a custom keybinding configuration of yours (please check) or a commit character of the suggestion in question. To know that I need more information, like the language in which this happens, the extension your are using, and the completion in question. In short, I need reproducible steps

**Comment by wesleyolis** [comment]
I am using the stock standard out the box, install of VSCode.
Were space now seems to be the bind key for code completion.
If you like any other settings check, please ask away.

**Comment by jrieken** [comment]
To know that I need more information, like the language in which this happens, the extension your are using, and the completion in question. In short, I need reproducible steps
