### ISSUE TITLE
Error when trying to attach debugger to Docker container: "Attribute 'localRoot' does not exist"

### ISSUE THREAD

**Issue by juristr** [Microsoft/vscode#59725]
- VSCode Version: 1.28.0-Insider
- OS Version: MacOS High Sierra (0.13.6)

Steps to Reproduce:

1.  Run a NodeJS process inside a Docker container (with debugging exposed)
2. Launch the Code debugger with the following configuration:

```
{
  "type": "node",
  "request": "attach",
  "name": "Docker: Attach to Node",
  "port": 9229,
  "address": "localhost",
  "localRoot": "${workspaceFolder}/node/proxy-coordinator",
  "remoteRoot": "/home/node/app",
  "protocol": "inspector"
},
```
Path mappings need to be adjusted ofc. This did still work last Thursday (27 Sept).

I receive the following error message:

![image](https://user-images.githubusercontent.com/542458/46280579-944cc880-c56c-11e8-905a-1d04f1ef9cc9.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Are you sure it exists? It simply checks whether that path exists, that's it.

**Comment by juristr** [comment]
@roblourens 🙈damnit. path changed after last git pull...sorry 😅
