### ISSUE TITLE
false syntax error in python(django)code

### ISSUE THREAD

**Issue by conall1995** [Microsoft/vscode#59728]
Issue Type: <b>Bug</b>

hi 
code have false error in django code
all=Model.objects.all()

[pylint] E1101:Class 'model' has no 'objects' member
my code work fine :)

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:57:45.963Z)
OS version: Windows_NT ia32 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz (8 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (2.13GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|25%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.17.0
jupyter|don|1.1.4
python-extension-pack|don|1.4.0
php-debug|fel|1.12.6
MagicPython|mag|1.0.12
python|ms-|2018.8.0
atom-keybindings|ms-|3.0.4
cpptools|ms-|0.19.0
vscodeintellicode|Vis|1.0.4
jinja|who|0.0.8

</details>

**Comment by RMacfarlane** [comment]
Hi @conall1995, this looks like a problem with a python extension and not VSCode itself. Can you try to narrow down what extension is giving this error by disabling them one at a time? Please file the issue on that extension.
