### ISSUE TITLE
Auto import not use alias then move root project in subdirect

### ISSUE THREAD

**Issue by dimensi** [microsoft/vscode#59722]
- VSCode Version: 1.27.2
- OS Version: macOS mojave

Steps to Reproduce:
I moved the project with the client to the "client" folder and I broke "auto imports"
Before i move files to client folder
<img width="1508" alt="2018-10-01 11 54 16" src="https://user-images.githubusercontent.com/11390039/46279081-ce1fce00-c570-11e8-9573-074795e0fd99.png">
After 
<img width="1552" alt="2018-10-01 11 59 56" src="https://user-images.githubusercontent.com/11390039/46279353-8baac100-c571-11e8-9764-9781b94fa435.png">

and how auto imports work
![oct-01-2018 11-58-50](https://user-images.githubusercontent.com/11390039/46279395-a2511800-c571-11e8-8b44-7d640ef257fa.gif)
![oct-01-2018 11-58-35](https://user-images.githubusercontent.com/11390039/46279407-a9782600-c571-11e8-83c6-c2e1acc0ebb0.gif)

My jsconfig
```
{
  "exclude": [
    "node_modules",
    "dist"
  ],
  "include": [
    "src/**/*",
    "tests/**/*"
  ],
  "compilerOptions": {
    "lib": [
      "es2018",
      "es2017",
      "es2016",
      "es2015",
      "dom",
    ],
    "baseUrl": "./",
    "paths": {
      "src/*": ["src/*"]
    }
  }
}
```

**Comment by bpasero** [comment]
@dimensi are you using typescript or javascript?

**Comment by dimensi** [comment]
@bpasero sorry, i missclick and send report too early. Wait please

**Comment by dimensi** [comment]
@bpasero i use javascript in project and set jsconfig.json in root.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by dimensi** [comment]
@mjbvz some problem on insider
![image](https://user-images.githubusercontent.com/11390039/46344338-87ea6d80-c649-11e8-981f-d4fd80ceb315.png)

**Comment by jbialobr** [comment]
The same happens for typescript.

**Comment by mjbvz** [comment]
@dimensi Please share a small example project that demonstrates this problem
