### ISSUE TITLE
html-script-indent

### ISSUE THREAD

**Issue by alexzshl** [Microsoft/vscode#59726]
Issue Type: <b>Feature Request</b>

input "scr" , then press Tab:
    <script></script>
then press Enter:
```
    <script>
        </script>
```

strange!

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.16299

**Comment by alexzshl** [comment]
`    <script>
        </script>`

**Comment by aeschli** [comment]
![html-script-indent](https://user-images.githubusercontent.com/6461412/46339199-78135f00-c632-11e8-81a7-dc1b0dd089d1.gif)

That's what I see. Is this about the new line missing?

**Comment by rashnk** [comment]
in any .html files
```
<script type="text/ng-template" id="btn.html">
</script>
```

below items wont work inside <script> tag
no code format ,
no auto tag close
html tag attributes auto list
![vscode](https://user-images.githubusercontent.com/12730428/46393965-0e17ba00-c705-11e8-86ad-cd2750ff92ba.gif)

**Comment by aeschli** [comment]
@rashnk Please open a separate issue.

**Comment by rashnk** [comment]
OK, @aeschli

**Comment by aeschli** [comment]
@alexzshl can you give more information about what the problem is?
