### ISSUE TITLE
Set editor font in a such a way that it doesn't need to be reset by widgets (e.g. find widget)

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#5972]
e.g. https://github.com/Microsoft/vscode/issues/5154#issuecomment-215413581

**Comment by bpasero** [comment]
@alexandrudima thanks for picking this up, I still see some places where we have to copy the font-family into the CSS:
* https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/inputbox/inputBox.css#L21
* https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/parameterHints/browser/parameterHints.css#L111
* https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/quickFix/browser/quickFix.css#L95
* https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/suggest/browser/suggest.css#L93

**Comment by alexandrudima** [comment]
@bpasero Since I don't force it on widgets anymore, I removed the font declarations from the obvious places. We should track these places in separate debt issues going to the owners of those widgets.

**Comment by bpasero** [comment]
Filed: https://github.com/Microsoft/vscode/issues/6171, https://github.com/Microsoft/vscode/issues/6170 and https://github.com/Microsoft/vscode/issues/6169
