### ISSUE TITLE
on mac, can't use right click open file, only open the application and a new file

### ISSUE THREAD

**Issue by sigon** [Microsoft/vscode#5973]
- VSCode Version:1.0.0
- OS Version:Mac OS X 10.11.4

Steps to Reproduce:

1. use right click open a xml file
2. VSCode opened,and a new file, no xml file

**Comment by SamVerschueren** [comment]
You mean right click on your file system right? Works perfectly fine here to be honest. Does it work with another file type like `json` or `html`? Have you tested it with a minimal `xml` file of only 1 line?

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
