### ISSUE TITLE
Precondition is not working when adding a menu item to editor title

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#59733]
- Open Keybindings Editor
- Type some search value or clear the value

🐛 Clear action is not getting enabled/disabled

Under the hoods, this action has a precondition while adding to the editorTitle menu registry. Context value used in this precondition is getting set correctly but still the action is not getting enabled/disabled.

https://github.com/Microsoft/vscode/blob/7b521edfad9707766415f6e23f815bb35a119fd7/src/vs/workbench/parts/preferences/electron-browser/preferences.contribution.ts#L413

**Comment by bpasero** [comment]
I can see how https://github.com/Microsoft/vscode/blob/4567f19ef87c2d189bee67b7b0c70aadff4533b9/src/vs/workbench/parts/preferences/browser/keybindingsEditor.ts#L292 is called but https://github.com/Microsoft/vscode/blob/4567f19ef87c2d189bee67b7b0c70aadff4533b9/src/vs/workbench/browser/parts/editor/titleControl.ts#L222 does not seem to be called at that time.

/cc @jrieken maybe I am missing something?

**Comment by bpasero** [comment]
@jrieken the issue is within this check: https://github.com/Microsoft/vscode/blob/6617952c182a3e182832cb365df95d19b5e85ec7/src/vs/platform/actions/common/menu.ts#L51

Do we miss to fill in the items precondition to that filter?

**Comment by bpasero** [comment]
I fixed this and @jrieken will look into making the actions disposable so that we are not leaking this newly introduced listener.
