### ISSUE TITLE
Provide a way to show BOM characters

### ISSUE THREAD

**Issue by rogierlommers** [Microsoft/vscode#59732]
Please see attached screenshot. When I open the file in textmate, it shows that the file has a byte-order-mark. However VSC does not show this. You can find the file [here](https://dump.lommers.org/download/20181001-da4e3275-37e1-42d6-8942-9dfaa414b01f?download=true). So my question is: don't we need a feature to "show" these kind of characters?

![bom](https://user-images.githubusercontent.com/3907131/46283812-df1f0e00-c575-11e8-87e6-24626157d47d.png)

**Comment by rogierlommers** [comment]
I don’t want to change something in the way the encoding is saved, I just want to have insights in the fact that a file has a Byte Order Mark.

**Comment by axetroy** [comment]
I got same problem #54913

**Comment by alexandrudima** [comment]
@bpasero I'm not 100% sure, is this not already shown in the status bar? (`UTF8 with BOM`)

**Comment by bpasero** [comment]
@alexandrudima yeah that is right, however I thought this issue asks for actually printing the BOM as text of the editor so that (I guess) you can potentially remove the BOM (or add it?)

![image](https://user-images.githubusercontent.com/900690/46617671-9808be00-cb1d-11e8-84de-15374f3b74b4.png)

**Comment by alexandrudima** [comment]
I don't think it would be useful for us to show the BOM. That can be controlled from the status bar entry where the file can be saved as UTF8 with/without BOM. The BOM is not a character in the file like other characters. AFAIK all editors should use the BOM as an encoding hint and should not present it to users.

In other words, I believe we are doing the right thing, the BOM is an "implementation detail" of the encoding and is not part of the "proper file contents".
