### ISSUE TITLE
Can't inform vscode of new function breakpoints

### ISSUE THREAD

**Issue by davidcummingsaapl** [Microsoft/vscode#59746]
- VSCode Version: 1.28.0-insider (29e6dce4352db76d8956035990b8630580226588)
- OS Version: macOS

The debug protocol provided by vscode allows the IDE to inform the debug server of function breakpoints that should be set by sending a SetFunctionBreakpoints request. This request contains an array of objects of type FunctionBreakpoint.

The debug protocol also allows the debug server to inform the IDE that breakpoints have been set by sending a BreakpointEvent. This event contains information on whether the breakpoint was added, removed or changed and contains an object of type Breakpoint representing the event. 

Unfortunately this Breakpoint type is for source breakpoints and doesn't contain the ability to specify information about function breakpoints. I tried a few different things by not setting line numbers, source file etc. but they all resulted in issues with the breakpoints view in vscode.

I had a look through debugSession.ts in the vscode source (see line 365) and there is some logic for function breakpoints, but it doesn't apply if the reason on the event is 'new'

**Comment by weinand** [comment]
@davidcummingsaapl please file this request against the [DAP](https://github.com/Microsoft/debug-adapter-protocol/issues) since this feature requires a protocol change.
