### ISSUE TITLE
Color picker doesn't work well with Undo

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#59741]
```css
body {
    color: red;
}
```

1. Type something on line 3
2. Hover over `red`, change color via color picker
3. Undo

Both changes will be undone!

It seems this might've been fixed a year ago, but it's broken today: https://github.com/Microsoft/vscode/issues/33348

**Comment by rebornix** [comment]
Verifiers: please make sure file auto save is turned off otherwise there is always an undo stop before the change.
