### ISSUE TITLE
Race condition in extension search

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#59750]
Issue Type: <b>Bug</b>

Reproduce steps:

* Open search viewlet 
* Type `v`
* Wait a little bit but before you get any result back, type `im` so now the keyword is `vim`
* Firstly we will get Vim related results and then it's being refreshed with Vetur results. 

![race-condition-search-extension](https://user-images.githubusercontent.com/876920/46302524-28636380-c55e-11e8-8242-a6345a2a19a4.gif)

The final search results we saw are from the keyword `v` which started earlier but not cancelled.

VS Code version: Code - Insiders 1.28.0-insider (c432054ae59c91fab2fc11511ce6d2cb4d84dc52, 2018-09-28T19:09:05.553Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (13.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.6.0
gitlens|eam|8.5.6
tsl-problem-matcher|eam|0.0.4
tslint|eg2|1.0.39
vscode-pull-request-github|Git|0.1.6
Angular2|joh|6.1.5
debugger-for-chrome|msj|4.10.2
vim|vsc|0.16.5

(3 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
Not sure if it's because I'm a slow typist (or fast?), I ran into this issue half of the time.

**Comment by georgekarapi** [comment]
Same here

**Comment by grunxen** [comment]
Search over one letter is quite slow and next search will be overridden by first one. First search is done over extensions list and recommended extensions. Next search will be only over extensions list. One of the ways to fix it is to add search queue as I made in https://github.com/Microsoft/vscode/pull/61071.
