### ISSUE TITLE
Cannot install VSIX extension when internet drops

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#59755]
See https://github.com/vuejs/vetur/issues/919

To repro:

- Open VS Code with internet connected
- Disconnect from internet
- Install a VSIX file, like https://github.com/vuejs/vetur/releases/download/v0.12.6/vetur-0.12.6.vsix

**Comment by octref** [comment]
Here's the error:

![image](https://user-images.githubusercontent.com/4033249/46305342-05d54880-c566-11e8-97ad-9f1752fc46a9.png)

**Comment by sandy081** [comment]
@octref it works for me. Can you please try again to repro?

**Comment by octref** [comment]
Can confirm, not reproducible any more.
