### ISSUE TITLE
Error after updating to Mojave MacOS

### ISSUE THREAD

**Issue by kunallanjewar** [Microsoft/vscode#59767]
Issue Type: <b>Bug</b>

/usr/local/go/pkg/tool/darwin_amd64/link: /usr/local/go/pkg/tool/darwin_amd64/link: combining dwarf failed: Unknown load command 0x32 (50)

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:04:11.329Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.22GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
vscode-markdownlint|Dav|0.20.0
githistory|don|0.4.2
xml|Dot|2.3.2
gitlens|eam|8.5.6
git-project-manager|fel|1.7.1
Go|ms-|0.6.89
vscode-docker|Pet|0.3.1

(1 theme extensions excluded)

</details>

**Comment by RMacfarlane** [comment]
This looks like this is related to Go, not VSCode itself. See https://github.com/golang/go/issues/25908

What version of Go are you using, and can you try upgrading it?

**Comment by kunallanjewar** [comment]
Thanks! upgrading the go version from 10 to 11 fixed the issue.
