### ISSUE TITLE
Fix TS 3.1 error in "src/vs/base/parts/tree/browser/treeDefaults.ts"

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#59762]
With d37076a we updated to use TS 3.1 to build VS Code. As part of this upgrade, I added a few `any` casts to workaround typing error in our code. These casts unblock the build but should be addressed and removed

Please address the comment in this file: https://github.com/Microsoft/vscode/blob/d37076a5967dd09868b34215cabbbca51444d10c/src/vs/base/parts/tree/browser/treeDefaults.ts#L269

**Comment by joaomoreno** [comment]
Unfortunately, this resulted from the keybindings refactoring a long time ago by @alexandrudima. Even though the type of the handler is now `void`, I'm not brave enough to believe that it will always be `void` at runtime. Closing it as I intend to kill this tree.
