### ISSUE TITLE
Bar not hide

### ISSUE THREAD

**Issue by schneiderbruno** [Microsoft/vscode#59760]
Issue Type: <b>Bug</b>

The bar position top in scrips, run indeterminate... not break.. 
The only soluction is restart the visual studio code.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (3.01GB free)|
|Process Argv|C:\Users\Bruno\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-eslint|dba|1.6.0
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.2.0
php-debug|fel|1.12.6
php-intellisense|fel|2.3.5
php-pack|fel|1.0.2
beautify|Hoo|1.4.4
debugger-for-chrome|msj|4.10.2
java|red|0.31.0
templex|sle|0.1.1
vscode-java-debug|vsc|0.13.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.9.0
vscode-maven|vsc|0.11.0

</details>

**Comment by Tyriar** [comment]
Can you show the problem in a screenshot?
