### ISSUE TITLE
[ts] Cannot find name / [ts] Cannot find module

### ISSUE THREAD

**Issue by taoqf** [Microsoft/vscode#5976]
- VSCode Version:1.0.0
- OS Version:Linux version 4.5.0-3-default

i have the same issues as [https://github.com/Microsoft/vscode/issues/4601](https://github.com/Microsoft/vscode/issues/4601)  while changing module to amd would not same me [https://github.com/Microsoft/vscode/issues/3865](https://github.com/Microsoft/vscode/issues/3865)
please help me.
i do not want put `/// <reference path="../typings/main.d.ts" />` in to every ts file.
by the way, i had this yesterday but it gone later.
it comes out today again, any help?

**Comment by taoqf** [comment]
tsc would not throw any error. so i believe my tsconfig.json is right.

**Comment by dbaeumer** [comment]
@taoqf can you share your project. Otherwise it is very hard to understand what might cause this.

**Comment by rinogo** [comment]
For others who may chance upon this Issue, try checking out #7018.
