### ISSUE TITLE
Data Explorer / Variables Pane

### ISSUE THREAD

**Issue by aminevsaziz** [Microsoft/vscode#59770]
Are there plans to support a data explorer, or variables view where one would execute a command and have the ability to explore the variable or even get some information about the variable (type, min, max...etc). Similar to how Rstudio/Pycharm has.

**Comment by isidorn** [comment]
VSCode already supports custom tree views via extension API, so this is a question if an extension would support this.
Since you are interested in R and Python it would be best to head over to those extensions github repos and ask them this question.
