### ISSUE TITLE
Can't find/replace new line in Ctrl+Shift+F search/replace

### ISSUE THREAD

**Issue by stevenbrix** [Microsoft/vscode#59771]
Issue Type: <b>Bug</b>

This works when using Ctrl+F inside a file, but doesn't work across all files open in the folder. Easiest thing to do is use Ctrl+Shift+F, make sure the regex search is enabled, and type in '\n'. You get an error message that '\n' is not supported.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.79GB (16.46GB free)|
|Process Argv|c:\Users\stevenki\AppData\Local\Programs\Microsoft VS Code\Code.exe x:\dev\nike|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-nmake-tools|Mic|1.1.180913009
cpptools|ms-|0.19.0
csharp|ms-|1.16.1
PowerShell|ms-|1.9.0
team|ms-|1.136.0

</details>

**Comment by RMacfarlane** [comment]
This isn't supported yet in global search - https://github.com/Microsoft/vscode/issues/13155
