### ISSUE TITLE
[folding] when going through search results, collapse region again

### ISSUE THREAD

**Issue by Lovecircle** [microsoft/vscode#59776]
- VSCode Version: 1.27
- OS Version: Win 7 x64

Steps to Reproduce:

Issue #1:
1. When I search for something and go through search results, if a result is located in the folded block of code - this block will be unfolded even though very often I do not need to change it - all I need is to see that this search result is not what I was looking for. 

Now:
![3](https://user-images.githubusercontent.com/6691153/46310664-a8261800-c5c8-11e8-8138-34dc2dee38d2.gif)

Desirable:
 ![4](https://user-images.githubusercontent.com/6691153/46310672-b1af8000-c5c8-11e8-9404-11f083bd426e.gif)

Issue #2:
1. Copy folded block of code.
2. Paste it. The code will be unfolded, which is very time-consuming to refold everything when reorganizing large blocks of carefully folded code.

Now: 
![1](https://user-images.githubusercontent.com/6691153/46310720-cb50c780-c5c8-11e8-950a-c997be65073a.gif)

Desirable:
![2](https://user-images.githubusercontent.com/6691153/46310739-d277d580-c5c8-11e8-89b6-d916f5a3a2da.gif)

 

Issue #3:
1. Please do not unfold code on one click or when clicking on empty space of the folded line : 
![last](https://user-images.githubusercontent.com/6691153/46310489-33eb7480-c5c8-11e8-9c9b-18e5ef1f2f94.gif)

Or at least give a "unfold on double-click" option in settings. Many times I unfolded blocks by mistake simply by clicking what seems to be an empty space of the editor.

Suggestion:
Make folded blocks more visible in the code or give an option to do so:

Now:
 ![6](https://user-images.githubusercontent.com/6691153/46310627-89278600-c5c8-11e8-824e-ad0d87691142.png)

Desirable:
 ![5](https://user-images.githubusercontent.com/6691153/46310642-95134800-c5c8-11e8-92fb-65c92d0841a6.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
Only one request per issue, please.

Using this one for issue 1.

Issue 3 is #53886
