### ISSUE TITLE
Filter explorer view to show only changed files and directories

### ISSUE THREAD

**Issue by dalemanthei** [microsoft/vscode#59773]
The explorer currently highlights files which are new or changed from the latest in the SCM. It would be nice to have a command toggle (via ⌘⇧P) to show only these files.

In our case we have a mono-repo style of project and similar or even same named files are very common. It requires care to pick (⌘P) the one based on the folder name. If the explorer could remove unchanged files finding and selecting your target files would be relatively quick and more precise.

The current folder highlighting is helpful to mouse or keyboard to the desired folder but the number of folders makes it tedious.

In this small example below, the folder `tools/gulp` would appear in the explorer. Opening the gulp folder would show only `tsconfig.json` file:

![tsconfig_json_ _vdl-angular-1](https://user-images.githubusercontent.com/6266984/46308944-9587f080-c580-11e8-9cac-51f2b0e20afd.png)

**Comment by NimaZahedi** [comment]
I'd like to work on this issue.

**Comment by isidorn** [comment]
@NimaZahedi just because it is a feature request does not mean we accept PRs that tackle it.
If you would like to contribute to this project I recommend reading our how to contribute wiki and than to find an issue with "help-wanted" and "good-first-issue" tag.

**Comment by NimaZahedi** [comment]
@isidorn I'm wondering to ask if only *help-wanted* and *good-first-issue* are supposed to be picked up for contributing.

**Comment by isidorn** [comment]
@NimaZahedi those are the best. Some feature-request might make sense to pick up but it is always best first to ask.

**Comment by joejordan** [comment]
I found myself in want of this feature today. I have a rather large code base and a rather diverse commit upcoming and I wanted to review all of the files changed without having to scroll and find all the modified files amongst the sea of unmodified files.

I realize the Source Control tab offers the list of modified files with the ability to edit, but I don't need to see the old version for comparison, I just want to be able to toggle "Show all" vs "Show Changed" in the Folders window, which gets increasingly helpful once you've focused your changes on a particular commit.

**Comment by svoop** [comment]
This would be such a great help and make my workarounds (listing tabs in the left column + tasks extension) obsolete while being zero configuration.

@NimaZahedi Couldn't this be implemented as an extension and thus without the need of convincing the core devs?

**Comment by HosseinSalmanian** [comment]
@isidorn  It would be a handy feature, working with so many files in file explorer makes an impact on productivity.

**Comment by v1ggs** [comment]
This would definitely be a very useful thing to have.

**Comment by grassdionera** [comment]
i would like to see this feature to

**Comment by SashaKryzh** [comment]
I need this feature

**Comment by freewind** [comment]
This feature is so useful +1

**Comment by AdmiralRazorbeard** [comment]
There is a workaround for this, use the  `"git.openDiffOnClick": false` option
Now when you use the source control panel, clicking on each file will open the file (not the changes). If you want to open the changes you will have to click right here
![image](https://user-images.githubusercontent.com/6703087/152195073-5e05311d-be7a-4df5-951d-05e5d33f4df0.png)

**Comment by gus-morales** [comment]
Setting `"git.openDiffOnClick": false` and `"scm.defaultViewMode": "tree"` did it for me, thank you!

**Comment by royOST** [comment]
You can also filter the Problems to only show files you have actively in an editor:
<img width="422" alt="image" src="https://user-images.githubusercontent.com/56088145/167132211-ed8a8e1e-6ca7-4aa3-aecf-b5d68858e0cf.png">

**Comment by gorbat-o** [comment]
Hello, it would still be better if it was in the Explorer. (xcode implements this feature very well) it sounds like a basic feature to have, particularly if the code base is big.

**Comment by jan-hlavsa-mindplexic** [comment]
Same opinion here - it would be great to have a simple button in Explorer to switch the view to see only changed files.

**Comment by piotrjak** [comment]
it'd be a nice feature - it sometimes takes a while to find the correct file. we have CMD+P, but it'd be easier to see it in the Explorer
