### ISSUE TITLE
Pleaaaase make a better app icon.

### ISSUE THREAD

**Issue by paul321** [Microsoft/vscode#59778]
Here is a screenshot from Windows 10, the app icon it's almost invisible.
![untitled-1](https://user-images.githubusercontent.com/555502/46311132-ebcd5180-c5c9-11e8-91fe-7064e383f625.jpg)

**Comment by vipulgupta2048** [comment]
A good hack around this would be to change the Windows color bar through the settings > appearance. Some lighter colors or black would be good. Logo's are made of colors, this problem would arise in any logo that would be made.

**Comment by beastdestroyer** [comment]
Perhaps have it have a dark background like it does as a start tile

**Comment by paul321** [comment]
I know i can change my task bar color, but we are in 2018 almost 2019 and this icon is really poorly designed with just one color someone rush it out.

**Comment by chrisdias** [comment]
this is being tracked in https://github.com/Microsoft/vscode/issues/71827
