### ISSUE TITLE
Save and sync extensions to the cloud

### ISSUE THREAD

**Issue by MashMathias** [Microsoft/vscode#59780]
I would like to use my outlook account (or other Microsoft account) to save and sync settings and extensions across all my machines running Visual Studio Code.

**Comment by RMacfarlane** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/2743

There's a settings sync extension that can help with this: https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync
