### ISSUE TITLE
[SCM] Capture git hook output to SCM output panel

### ISSUE THREAD

**Issue by Ash258** [Microsoft/vscode#59787]
Vscode should be able to capture output of git hooks and append it to scm output panel. 

See: https://github.com/Microsoft/vscode/issues/42275#issuecomment-425906395

- Version: 1.28.0-insider
- Commit: 83d5a29433d7f576b59db8019575a0c9dc78a967
- Date: 2018-10-01T13:31:33.485Z
- Electron: 2.0.9
- Chrome: 61.0.3163.100
- Node.js: 8.9.3
- V8: 6.1.534.41
- Architecture: x64
- OS Version: Windows 10 1803 (17134.285)

**Comment by joaomoreno** [comment]
I suggest to do this behind a feature flag.

**Comment by rdosanjh** [comment]
I'd like to take this 🙂

**Comment by rdosanjh** [comment]
I just had a look at this and i can't reproduce the issue.  I will say that the output does not respect the colours of the text.
<img width="399" alt="screen shot 2018-10-06 at 15 27 31" src="https://user-images.githubusercontent.com/8139394/46572354-4ffe6580-c97c-11e8-9654-d2a181c09a67.png">

**Comment by Ash258** [comment]
Since few insiders version (noticed it about 5 days ago) I can see commit hook output. 🤔

![Hook](https://i.imgur.com/ZrwQ0WE.png)

**Comment by joaomoreno** [comment]
Awesomesauce.
