### ISSUE TITLE
File Context Menu "Split <direction>"  Should Remove Initial File From Editor

### ISSUE THREAD

**Issue by MarkPhillips** [Microsoft/vscode#59788]
Issue Type: <b>Bug</b>

Open File
Right Click File Tab
Select Split Right
File Correctly Moves To New Grouping On The Right
But Original File Remains Open In Old Grouping
(I use Split to be able to view multiple files at one time.  To me, leaving duplicate files open is unneeded noise.)

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.89GB (23.79GB free)|
|Process Argv|C:\Users\mgphi\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|9.0.1
ng-template|Ang|0.1.10
htmltagwrap|bra|0.0.7
npm-intellisense|chr|1.3.0
gitignore|cod|0.5.0
bracket-pair-colorizer|Coe|1.0.60
git-extension-pack|don|0.1.3
gitlens|eam|8.5.6
EditorConfig|Edi|0.12.4
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.6.1
auto-rename-tag|for|0.0.15
rest-client|hum|0.19.1
output-colorizer|IBM|0.1.2
path-autocomplete|ion|1.12.0
Angular2|joh|6.1.5
TypeScriptImport|kev|1.17.0
debugger-for-chrome|msj|4.10.2
quicktype|qui|12.0.46
LiveServer|rit|5.1.1
vscode-icons|rob|7.27.0
ActiveFileInStatusBar|Ros|1.0.3
JasmineSnippets|xab|1.0.1
vscode-open-in-github|ziy|1.3.6

</details>

**Comment by bpasero** [comment]
I am closing this "as designed", I do not plan to change this. The split icon makes it clear that you will end up with 2 editors.
