### ISSUE TITLE
Integrated terminal isn't accessible with JAWS and NVDA

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#59794]
_Report from Ryan Shugart over email_

I have some unfortunate news, I just tried to use the terminal in VS Code with both JAWS and NVDA, and it doesn’t seem to be working for me.  I also had Tamas who is joining our team and is a big NVDA user and more familiar with VS Code overall than me try the terminal and he couldn’t get it to read properly either.  We made sure screen reader mode was turned on with alt+f1.

**Comment by goatandsheep** [comment]
This is a big issue for us as well

**Comment by Tyriar** [comment]
Follow ups from meeting yesterday:

- Fix terminal when `editor.accessibilitySupport` is set to `"auto"`
- Document terminal scroll commands in accessibility docs as it wasn’t they were available obvious
- Figure out why buffer navigation using browse mode works in NVDA but not in JAWS

**Comment by Tyriar** [comment]
@adil-s the fix I did 3 days ago fixed this in the Insiders build, the terminal will now respect automatic screen reader detection.

**Comment by Tyriar** [comment]
To verify on Windows:

- Start NVDA
- Open VS Code, it should auto detect a screen reader
- Verify the screen reader voices terminal input and output (eg. dir)
