### ISSUE TITLE
[VS Live Share]  localPath not found on debug configuration on guest restart

### ISSUE THREAD

**Issue by jramsay** [Microsoft/vscode#59795]
Version: 1.27.2 (user setup)
Commit: f46c4c469d6e6d8c46f268d1553c5dc4b475840f
Date: 2018-09-12T16:17:45.060Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
OS: Window 10

Steps to Reproduce:

Install Latest VS Live Share extension on Insiders
1.  Host: Share a Node JS App, set a breakpoint and start debugging
2. Guest: Join collaboration session (guest automatically joins debug session)
3.  Guest: Restart debug session

![image](https://user-images.githubusercontent.com/8161247/46322332-15bc4f00-c59d-11e8-84a6-865a64a5adb4.png)

This issue appears to be due to recent debug restart refactoring:

https://github.com/Microsoft/vscode/commit/d4ba91f1034c79d7ea5fa4b8510ff280f75a762b

The issue occurs in debugService's restartSession.  When the VS Live Share Guest clicks restart the correct resolved and unresolved debug configurations are found on the session. The unresolved configuration does not equal the session.unresolvedConfiguration. 

needsToSubstitute is set to true and the sessions resolved configuration ends up getting replaced with an unresolved configuration that doesn't contain the required information for VSLS to properly initialize the debug session (ex: localPath, joinUniqueId, etc is missing)

**Resolved configuration is set correctly if substituteVariables isn't called:**

![image](https://user-images.githubusercontent.com/8161247/46322792-b6137300-c59f-11e8-82fd-ac395aff15d2.png)

**When subsituteVariables is called required debug configuration information is lost:**

![image](https://user-images.githubusercontent.com/8161247/46322833-f7a41e00-c59f-11e8-93c1-1b2b82b3b3b1.png)

**Comment by isidorn** [comment]
Thanks a lot for filling this issue with great steps and detail.
I have explained the reson what caused this regression in https://github.com/Microsoft/vscode/pull/59819
This pr is merged, so this should be fixed in the next stable and from Insiders tomorrow.

I have verified this worked for me when doing a live share session with myself on my mac.
Though it would be great if you can also verify @jramsay

**Comment by jramsay** [comment]
Thanks @isidorn! Verified this resolves the associated issues.

**Comment by isidorn** [comment]
@jramsay great, adding verified label!
