### ISSUE TITLE
[Build] Add yarn script for executable optimized build

### ISSUE THREAD

**Issue by Jaakkonen** [Microsoft/vscode#59790]
Hi!
There's currently only yarn macro for unoptimized build (watch).
I'd suggest a new macro:
```
gulp optimize-index-js
electron out-build/main.js
```
That'd enable developers and foil hats to use only the open source parts of vscode easier.

**Comment by dbaeumer** [comment]
@Jaakkonen I am not understanding what you are suggesting. Adding additional scripts to  the package.json ?

**Comment by joaomoreno** [comment]
Sorry @Jaakkonen this is not under our main development flow. If you still feel strong about it, submit a minimal PR; otherwise, we won't get to it.
