### ISSUE TITLE
Please consider opening the source for the website

### ISSUE THREAD

**Issue by strugee** [Microsoft/vscode#59796]
I was looking at code.visualstudio.com just now and thought it would be nice to add a link to the source code under the big green download button - after all, it is open source :-)

I would have sent a PR but AFAICT the website code is not actually open. It would be super rad if it was.

**Comment by octref** [comment]
The code is open source, and all the content of the website is open source at https://github.com/microsoft/vscode-docs, but unfortunately we cannot open source the website. There are many reasons, one of them being that the website code often contains internal content that cannot be shared until certain point of time. Thanks for understanding.

**Comment by octref** [comment]
The link is available in the bottom: 
![image](https://user-images.githubusercontent.com/4033249/46513496-9a150900-c80d-11e8-9dd6-d70cf81c256c.png)

When we update the homepage next time we'll consider making it more prominent. Thanks!
