### ISSUE TITLE
Fail to copy big content

### ISSUE THREAD

**Issue by rodrigoestevao** [Microsoft/vscode#59799]
Issue Type: <b>Bug</b>

I'm trying to copy a text with more or less 90MB and the VS just brokes. If the file is bigger (~ 180MB) it is broking just when the text is being seleced.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:11:15.873Z)
OS version: Linux x64 4.15.0-34-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700 Eight-Core Processor (16 x 1374)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|2, 1, 1|
|Memory (System)|15.68GB (7.30GB free)|
|Process Argv|/usr/share/code/code .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.60
jshint|dba|0.10.20
vscode-eslint|dba|1.6.0
githistory|don|0.4.3
jupyter|don|1.1.4
tslint|eg2|1.0.39
gc-excelviewer|Gra|2.1.26
beautify|Hoo|1.4.4
rest-client|hum|0.19.1
Angular2|joh|6.1.5
mssql|ms-|1.4.0
anaconda-extension-pack|ms-|1.0.0
python|ms-|2018.8.0
typescript-javascript-grammar|ms-|0.0.45
debugger-for-chrome|msj|4.10.2
vscode-yaml|red|0.0.17
LiveServer|rit|5.1.1
vscode-icons|rob|7.27.0
sass-indented|rob|1.4.9
bootstrap4-vscode|the|4.3.0
JavaScriptSnippets|xab|1.7.0

(2 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
Can you try running vscode from command line with flag `code --max-memory=4096` and see if you can still reproduce this issue?
