### ISSUE TITLE
Enable error highlighting syntax toggle on/off

### ISSUE THREAD

**Issue by sashaburchuk** [Microsoft/vscode#598]
There are certain aspects of code that are experimental that the VSCode Editor doesn't recorgnize. It would be useful to easily be able to toggle error highlighting on/off.

**Comment by jrieken** [comment]
@sashaburchuk Can you provide a little more detail? Are you talking about a programming language and if which one?

**Comment by sashaburchuk** [comment]
I'm working in Typescript, and text editors seem to have a particularly hard time analyzing @autobind. I know that autobind is working because I haven't had to change scope, but everything is still underlined. 

I did try going in to the settings.json file in Application Support and changing 

"javascript.validate.syntaxValidation": to false. 

That didn't help. 

Here's a screenshot so you can see what I'm seeing. 
![screen shot 2015-11-25 at 9 47 09 am](https://cloud.githubusercontent.com/assets/4923907/11405207/3941b9a0-935b-11e5-9fb6-caeaf0968b29.png)

**Comment by dbaeumer** [comment]
@sashaburchuk which version of TS are you using. You can point VSCode to use the latest TS server by using the typescript.tsdk setting. See https://code.visualstudio.com/updates/v0_8_0 for details regarding the setting

**Comment by sashaburchuk** [comment]
Hi @dbaeumer. I'm using version ^1.6.2. I'm a bit wary of changing the typescript.tsdk setting because this code is being used in production. 

Is there any other way to disable validation? I also tried adding ```"javascript.validate.enable": false``` to settings.json without any luck.

**Comment by dbaeumer** [comment]
@sashaburchuk can you run tsc --version to see which version you are actually using ^1.6.2 will for example install the current 1.7.3 version

**Comment by sashaburchuk** [comment]
@dbaeumer I'm using 1.7.3 now, and the issue seems to be resolved with this version of Typescript.

**Comment by dbaeumer** [comment]
Error reporting can now be disabled using javascript.validate.enable and typescript.validate.enable.
