### ISSUE TITLE
cpu 100%

### ISSUE THREAD

**Issue by jlamb1** [Microsoft/vscode#59804]
Issue Type: <b>Bug</b>

I've been trying to fix this for months and can't seem to get this to work. I've tried disabling all extensions, monitoring processes in devtools, setting files.exclude and files.watcherExclude to exclude node_modules and vendor files - nothing seems to work. This is a 2017 macbook pro, 2.9Ghz processor with 16BG ram and discrete graphics, and I cannot run this app without sounding like a helicopter trying to take off.

This does happen most when running apps using Docker if it helps

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:04:11.329Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.31GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
html-css-class-completion|Zig|1.17.1
vscode-standardjs|che|1.2.3
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.6.0
prettier-vscode|esb|1.6.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
sass-lint|gle|1.0.3
twig-language-2|mbl|0.3.1
sublime-keybindings|ms-|4.0.0
vscode-docker|Pet|0.3.1
sass-indented|rob|1.4.9
rewrap|stk|1.9.1
jinja|who|0.0.8

(1 theme extensions excluded)

</details>

**Comment by wad3g** [comment]
I've been experiencing the exact same issue(s) as @jlamb1 and have tried all of the potential solutions mentioned above on my 2018 MacBook Pro.

I'm not sure how this issue and Docker are associated, but killing the Code Helper process in Activity Monitor temporarily solves the problem, sometimes.

**Comment by id0Sch** [comment]
I am having the same issue, I think I have isolated it to the Code Helper that runs the typescript server.
For me it happens in medium sized projects who run typescript, when going to . a definition or opening the auto-complete menu - it skyrockets to 100% and will stay there forever.

**Comment by jrieken** [comment]
we need to know more, please follow this guide: https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by jrieken** [comment]
ping  @jlamb1
