### ISSUE TITLE
Make it easier to add a javadoc to a .jar file

### ISSUE THREAD

**Issue by Kulkinz** [Microsoft/vscode#59807]
I've switched over to VSCode since FRC is now supporting this as it's official IDE. I've set up .jar files for my robot code, yet I can't seem to figure out how to attach a Java Source Attachment, a way to show what each class does, to the jar. Nothing seems to work. It's different from Eclipse where I could just right click the jar and go to settings.

My request is just for a simple way to attach a Java Source Attachment.

I've never done an Issue before, so apologies if I did this wrong.

**Comment by isidorn** [comment]
You did an issue just good, however we prefer to seperate issues per extension. So please file this issue in the java extension here
https://github.com/redhat-developer/vscode-java
Or whatever other java extensions you arae using
