### ISSUE TITLE
When you change ts file folder will get the "Duplicate identifier" message

### ISSUE THREAD

**Issue by wangyibu** [Microsoft/vscode#5980]
- VSCode Version:1.0.0
- OS Version:window7 sp1 build 7601
- VS2015: commuity 2015 update1
- system path:  C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.7;

Steps to Reproduce:

1.add two ts file and compile

![1](https://cloud.githubusercontent.com/assets/14134768/14912855/95bd0bde-0e31-11e6-8289-36e5e878e8f2.png)

![2](https://cloud.githubusercontent.com/assets/14134768/14912859/a0574316-0e31-11e6-94d4-174b19554a36.png)

2.add new folder
 
![3](https://cloud.githubusercontent.com/assets/14134768/14912898/e0a9252e-0e31-11e6-9908-e81c22dbb254.png)

3. move all ts file and js file to new folder 
![image](https://cloud.githubusercontent.com/assets/14134768/14912921/fc6fe90a-0e31-11e6-99eb-c106f8092e52.png)

**Comment by wangyibu** [comment]
supplement: when I change namespace  "Wd3.Test" -> "Wd3" is work
Steps to Reproduce:
1. 

2.

**Comment by dbaeumer** [comment]
@wangyibu can you provide the content of the tsconfig.json file?

**Comment by wangyibu** [comment]
not set config
tsconfig.json is empty

**Comment by dbaeumer** [comment]
Moving to TS since it looks like the tsserver doesn't honor the move of files correctly.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#8543
