### ISSUE TITLE
Click on background window clears selection

### ISSUE THREAD

**Issue by nudefireninja** [Microsoft/vscode#59800]
- VSCode Version: Code - Insiders **1.28.0**-insider (83d5a29433d7f576b59db8019575a0c9dc78a967, 2018-10-01T13:24:08.681Z)
- OS Version: **Darwin x64 13.4.0** (Mac OS 10.9)

Steps to Reproduce:

1. Select some portion of code.
2. Switch to another window or application.
3. Click on the original window (somewhere on the code).

Expectation: the clicked window should become active and **the previous selection should remain intact.**

Reality: the previous selection is cleared and the cursor jumps to the clicked area.

![vscode-window-click-selection-bug](https://user-images.githubusercontent.com/6565746/46324730-d9184400-c5ec-11e8-8ff1-bb0c5998ee54.gif)

Does this issue occur when all extensions are disabled?: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2760QM CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|8.00GB (0.10GB free)|
|Process Argv|-psn_0_987377|
|Screen Reader|no|
|VM|0%|

**Comment by RMacfarlane** [comment]
@nudefireninja Thanks for reporting this, but this is by design. Clicking somewhere else in the editor while text is selected is meant to change the cursor selection. If you want to switch back and forth between windows and preserve the text selection, you can use `Cmd ~`, or click the title bar instead of the editor to focus the window.

**Comment by nudefireninja** [comment]
Ok, but it's a strange design decision as no other app does this, code editors or otherwise, and I see no benefit. It simply means I cannot click to activate windows with the mouse if I have text selected that I want to copy for example. I know how to switch windows with the keyboard but that's not always the most convenient (for me anyway).

There are no extensions to change this behavior and there seems to be no way to undo/reselect the last selection. I was looking to switch to a better editor/IDE from TextMate and I think this is a deal breaker for me. I'm leaning toward using Atom now.
