### ISSUE TITLE
Python debugging, call stack and variables panes are blank when paused on breakpoints

### ISSUE THREAD

**Issue by chrisdlangton** [Microsoft/vscode#59813]
searched 3 pages of existing issues that had 'python' or 'debug'

- VSCode Version: both `code-insiders_1.28.0-1538437803_amd64.deb` and `code_1.27.2-1536736588_amd64.deb` (today's stable and insiders)
- OS Version: Ubuntu (4.15.0-34-generic)

Steps to Reproduce:

1. `dpkg -P code; apt purge code vscode; snap uninstall vscode; mv ~/.vscode/ ~/BACKUP/.vscode; mv ~/.config/Code/ ~/BACKUP/.config/code`

2. `dpkg -i code-insiders_1.28.0-1538437803_amd64.deb`
3. run `code` in terminal (cannot use `--disable-extensions` read on)
4. install microsoft python plugin
5. create a file with a single variable assignment and on second line a print
6. break point line 2
7. press `F5` which runs for you `env "PYTHONIOENCODING=UTF-8" "PYTHONUNBUFFERED=1" "PYTHONPATH=/home/chris/.vscode/extensions/ms-python.python-2018.8.0/pythonFiles/experimental/ptvsd" /home/chris/workspace/github/aws-sec-review/bin/python -m ptvsd --host localhost --port 43707 /home/chris/workspace/github/aws-sec-review/src/test.py`
8. observe the debugger view tells you `PAUSED ON BREAKPOINT` but there are no details in the `CALL STACK` or `VARIABLES` panes. 

The debugger is pretty much useless without showing any variables or the call stack.

If this is not the correct repo to report this issue please help me with advice how to report it effectively.

**Comment by RMacfarlane** [comment]
This repo is meant to track issues with the core of VSCode, the correct place to report this is https://github.com/Microsoft/vscode-python. Please reopen this there. Thanks!

**Comment by chrisdlangton** [comment]
thank you
https://github.com/Microsoft/vscode-python/issues/2769
