### ISSUE TITLE
can not open on fedora 29

### ISSUE THREAD

**Issue by zgjff** [Microsoft/vscode#59812]
- VSCode Version: 1.27.2-1536736788.el7
- OS Version: fedora 29

**Comment by roblourens** [comment]
What is the problem exactly? Please include more details

**Comment by zgjff** [comment]
I installed it according to this method. However, after the installation, I have been unable to open it, it seems to crash after loading 2s, I did not even enter the interface.

**Comment by dralley** [comment]
It's this issue, it has supposedly already been fixed, but there's no updated package yet unless you're using insiders.  

https://github.com/Microsoft/vscode/issues/59526

**Comment by roblourens** [comment]
Thanks @dralley. Stable release probably comes tomorrow (Thursday)
