### ISSUE TITLE
Slow code navigation and autocomplete

### ISSUE THREAD

**Issue by masimplo** [Microsoft/vscode#59821]
Issue Type: <b>Performance Issue</b>

Go to definition for typescript files included in the projects takes several seconds. 
Autocomplete also takes a few seconds to show results for the first autocomplete I do per file.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:04:11.329Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.42GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   25	    82	  7281	code main
   17	    49	  7282	   gpu-process
    1	    66	  7577	   shared-process
    9	   360	 16899	   window (avatar-api.service.mock.ts — covve.Ionic2)
    3	   246	 16900	     extensionHost
    0	    16	 16905	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=16900
    0	    16	 16930	       /Users/michael/.vscode/extensions/ms-vsliveshare.vsliveshare-0.3.735/dotnet_modules/vsls-agent --autoexit --pipe ded32eeb5af24f8b85237f40bb150107 --service https://insiders.liveshare.vsengsaas.visualstudio.com/
    0	    16	 16987	       electron_node server.js 
    0	   393	 24052	       electron_node tsserver.js 
    0	    16	 24064	         electron_node typingsInstaller.js tsserver.js typesMap.js 
    0	   590	 24055	       electron_node server.js 
    0	    82	 24056	       electron_node tslintServer.js 
    0	   393	 24082	       extensionHost
    0	    33	 24083	       extensionHost
    0	   164	 24089	       extensionHost
    0	   131	 24114	       extensionHost
    0	   131	 24121	       extensionHost
    0	    66	 24195	       extensionHost
    0	    66	 24201	       extensionHost
    0	   475	 24202	       extensionHost
    0	     0	 24409	       electron_node eslintServer.js 
    0	    33	 24747	       electron_node server.js 
    0	     0	 24748	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain --node-ipc --clientProcessId=16900
    0	     0	 24754	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/server/dist/htmlServerMain --node-ipc --clientProcessId=16900
    0	    49	 16901	     watcherService
    0	    33	 19361	     searchService
   70	    82	 39822	   window (Issue Reporter)
    0	     0	 39823	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (avatar-api.service.mock.ts — covve.Ionic2)
|    Folder (covve.Ionic2): 8801 files
|      File types: js(1524) ts(869) map(821) html(784) class(592) h(528)
|                  dex(503) png(481) flat(306) java(298)
|      Conf files: package.json(53) sln(3) csproj(3) webpack.config.js(1)
|                  settings.json(1) tsconfig.json(1) tasks.json(1)
|                  project.json(1) makefile(1) tslint.json(1) launch.json(1)
|      Launch Configs: chrome(2);
```

</details>
<details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.4
ng-template|Ang|0.1.10
npm-intellisense|chr|1.3.0
gitignore|cod|0.5.0
bracket-pair-colorizer|Coe|1.0.60
vscode-eslint|dba|1.6.0
gitlens|eam|8.5.6
tslint|eg2|1.0.39
vscode-npm-script|eg2|0.3.5
svgeditor|hen|2.6.0
docker-linter|hen|0.5.0
docthis|joe|0.7.1
vscode-language-babel|mgm|0.0.20
Angular-BeastCode|Mik|6.2.29
dotenv|mik|1.0.1
vscode-csscomb|mrm|5.2.2
vscode-scss|mrm|0.6.2
vsliveshare|ms-|0.3.735
snippet-creator|nik|0.0.5
vscode-docker|Pet|0.3.1
tsimporter|pmn|1.2.14
code-settings-sync|Sha|3.1.2
trailing-spaces|sha|0.2.11
quokka-vscode|Wal|1.0.150
wallaby-vscode|Wal|1.0.96
vscode-import-cost|wix|2.9.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?
