### ISSUE TITLE
Xcode like completion for IntelliSense

### ISSUE THREAD

**Issue by salmankhann** [Microsoft/vscode#59828]
I love the IntelliSense that comes with VSCode but I would like an option for autocompletion like XCode that instead of pressing tab to select an option, cycles through to the next available Capital letter in the suggestion.

For example, if the IntelliSense suggests the following 2 list items 'imageView' and 'imageViewInFrame', pressing tab once will highlight image, tab twice will highlight imageView. At that point I can either press enter to choose imageView or another tab to select imageViewInFrame.

How can something like this be done in VSCode? Is there either,

1. An Extensibility API that can allow for such behavior that can be packaged as an extension
2. If not, where should I start in the VSCode source to try and incorporate such a functionality? 
3. Is there any other option?

Thanks for your help!

**Comment by jrieken** [comment]
@salmankhann We will ship this with the next release, see 
https://github.com/Microsoft/vscode/issues/28215#issuecomment-422310232

**Comment by salmankhann** [comment]
@jrieken although the current feature in the Insiders is better than before, I was looking for something a bit different that is implement in Xcode. 

See how tab keeps the IntelliSense open, as well as keeps highlighting matched elements.


![443dkek1qmoxy6uulp](https://user-images.githubusercontent.com/2960078/46394594-a0ff2700-c6fa-11e8-9cc3-1df05b84e2fa.gif)
