### ISSUE TITLE
raw_input() extra \r in the returned string

### ISSUE THREAD

**Issue by Zaeyi** [Microsoft/vscode#59820]
- VSCode Version:1.27.2
- OS Version:windows10

Steps to Reproduce:

1.I am a primary Python learner, when I use raw_input(), The length of the string is always one bit more than what it should be. When print it, it looks no problem in VSCODE console. And then I find the end of the string is \r, but when I use CMD or Pycharm this problem doesn't exist, So I think this may be VSCODE's wrong.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by Zaeyi** [comment]
@flowkraD 
![qq 20181003130518](https://user-images.githubusercontent.com/43777779/46390942-06f4aa00-c70d-11e8-8c96-b810b92ba98b.png)

**Comment by Zaeyi** [comment]
@flowkraD 
And another error shows me the extra one is \r
I only input D:\1.txt
But the error shows D:\1.txt\r
![qq 20181003131117](https://user-images.githubusercontent.com/43777779/46391137-d9f4c700-c70d-11e8-9523-043aa6a60d8d.png)

**Comment by flowkraD** [comment]
I tried the second one on Linux and no errors flash. I would wait for someone more experienced with this part of code base to comment on this issue.

**Comment by Zaeyi** [comment]
ok， thanks

**Comment by RMacfarlane** [comment]
@Zaeyi Hmm, the actual runtime behavior of python should be determined by python itself. It looks like the terminal you're using in VSCode is PowerShell. Can you check the Python version in both cmd and PowerShell by running `python --version`? Are the environments the same? Are you running the program in the same way?
