### ISSUE TITLE
Variable for the software's path.

### ISSUE THREAD

**Issue by RayCore** [Microsoft/vscode#59824]
I'm using the zip version of vs-code(aka portable) with MinGW for school, it would be nice to have a variable that points to the code.exe file, so that i could specify the compiler path relative to that location.  
Something like "${appPath}/...".

For now i have to use a path relative to the working folder, which enforces me to place my projects in a specific folder.
I could hard code the paths in the settings, but then i would need to change them sometimes if i change pc. Since i use the portable version only for school it really isn't a big deal, just something nice to have.

**Comment by RayCore** [comment]
I'm not sure what you mean by feature.
I'd use it in the settings.json file to set the cpp default compiler path and clang-format.exe path(and every other path i might need). 
The idea is to have all paths i want to set relative to vscode's path so that i can have a "IDE" folder that i'll never touch, while still being able to place my project folders wherever i want without breaking all the paths(unlike the way i'm doing it right now)

**Comment by sandy081** [comment]
@RayCore May I know the settings you are talking about?
