### ISSUE TITLE
search.useRipgrep ignores exclude setting

### ISSUE THREAD

**Issue by Hrnkas** [Microsoft/vscode#59822]
It seems that search.useRipgrep ignores the exclude settings.
I had problem that my search results always included the .svn directory.
Exclude started working when I disabled search.useRipgrep.

My Environment:
Windows 10
VSC installed in User Directory (as recommended per last Update).
My code is on an Active Directory roaming profile (\Redir$\Bojan\Documents\Projects\...\commissions_table.php)

**Comment by roblourens** [comment]
This looks like #58758
