### ISSUE TITLE
Expression input field not looking nice on Linux

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#59829]
See

![image](https://user-images.githubusercontent.com/900690/46355467-20d8b300-c661-11e8-8a7d-d7d8ff6de75e.png)

compared to in the explorer:

![image](https://user-images.githubusercontent.com/900690/46355486-2a621b00-c661-11e8-9e66-1cdc03209e36.png)

It also feels like the text jumps more for the first case.

**Comment by isidorn** [comment]
Pushed a fix to clear tree focus and highlight when debug input is created.
As for the text jumping might be connected to the other line-height issue we are discussing.
