### ISSUE TITLE
Webview's "retainContextWhenHidden" is broken in the latest 1.28

### ISSUE THREAD

**Issue by ivankravets** [Microsoft/vscode#59823]
- VSCode Version: 1.28-insider ( 99b5434b0a90a024caab1cb35a1f7ca06708fefc )
- OS Version: macOS 10.13.6

See https://github.com/platformio/platformio-vscode-ide/issues/346 . 

@mjbvz Could you fix this issue? Otherwise, we have to inform our community to avoid updating to VSCode 1.28. It totally breaks our web-based PlatformIO Home.

Thanks in advance!

**Comment by mjbvz** [comment]
Yes needs fixing on our side

In the future please make sure you have users testing your extension on VS Code insiders. As far as I can tell this has been broken over the entire month that 1.28 insiders has been going out

**Comment by ivankravets** [comment]
Thanks, it's my mistake. Next time I'll open issue here.

**Comment by mjbvz** [comment]
Not your fault. We really need better test coverage on our side. The timing here is unfortunate since we're only hearing about this a few days before we planned to ship 1.28. Since the webview is such as complicated area, we currently do reply on extension authors reporting issues with it

**Comment by ivankravets** [comment]
Is it possible to cover "retainContextWhenHidden" with a unit test?

P.S; Thanks for the quick fix! 👍
