### ISSUE TITLE
Using code.cmd --installextension results in a [createInstance] warning

### ISSUE THREAD

**Issue by GabeDeBacker** [Microsoft/vscode#59831]
- VSCode Version: 1.27.2
- OS Version: - X64 Windows

Steps to Reproduce:

1. Use the command line for vscode "code.cmd --install-extension <path to vsix>
2. VSCode logs to the console (through console.warn) 
   "[createInstance] extensionManagementService depends on downloadService which is NOT registered." (this happens in VSCode 

Does this issue occur when all extensions are disabled?: Yes

This is an issue for us beause we have scripts and eventually a larger wrapped installer that are trying to detect whether either an install or upgrade of an VSCode extension has failed.

Currently the exit code of the process is always zero, so that cannot be used as an indicator, errors do come through "Standard Error", but due to the warning above, without doing some type of string parsing, we cannot reliably tell if the extension successfully installed.

**Comment by sandy081** [comment]
Fixed. Please try latest insiders or wait for new stable release (in couple of days)
