### ISSUE TITLE
screen cheese with german and keybinding ui

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#5983]
see screen shot. text overflows the box

![screen shot 2016-04-29 at 15 28 06](https://cloud.githubusercontent.com/assets/1794099/14918028/2289a618-0e22-11e6-865b-a268d2f6c7b2.png)

**Comment by alexandrudima** [comment]
Neeeein!!

**Comment by alexandrudima** [comment]
Duplicate of #24817
