### ISSUE TITLE
Code Helper > 100% CPU

### ISSUE THREAD

**Issue by nomadoda** [Microsoft/vscode#59834]
Issue Type: <b>Performance Issue</b>

It seems to be related to testing my mocha suite. I set one expect `it` test case to `it.only`, then try to run through debugger and CPU hits the roof, with no tests running.

***launch.json:***

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Mocha All",
      "program": "${workspaceFolder}/node_modules/mocha/bin/_mocha",
      "args": [
        "--require",
        "ts-node/register",
        "-u",
        "bdd",
        "--timeout",
        "999999",
        "--colors",
        "${workspaceFolder}/src/modules/**/*.test.ts"
      ],
      "env": {
        "NODE_ENV": "test"
      },
      "internalConsoleOptions": "openOnSessionStart",
      "protocol": "inspector"
    }
  ]
}

```

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:04:11.329Z)
OS version: Darwin x64 17.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   13	    82	 91080	code main
    0	   123	 91081	   gpu-process
    0	   180	 91084	   window (Index.vue — bitgigs-admin)
    0	     0	 91374	     /bin/bash
    0	    16	 91604	       npm
    0	    25	 91605	         node /Users/Adam/Bitgigs/bitgigs-admin/node_modules/.bin/vue-cli-service serve
    0	    16	 91610	           electron_node service.js 
    0	    74	 91422	     extensionHost
    0	    33	 91591	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=91422
    0	   106	 92670	       electron_node tsserver.js 
    0	    25	 92671	         electron_node typingsInstaller.js tsserver.js typesMap.js 
    0	   131	 92673	       electron_node vueServerMain.js 
    0	    25	 91533	     watcherService
    0	    25	 91594	     searchService
    0	    57	 91575	   shared-process
    0	   180	 91833	   window (employee.test.ts — bitgigs-server)
    0	     0	 91834	     /bin/bash
   98	   582	 91871	     extensionHost
    0	    66	 92048	       electron_node tsserver.js 
    0	    25	 92063	         electron_node typingsInstaller.js tsserver.js typesMap.js 
    0	    25	 92068	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=91871
    0	    33	 92001	     watcherService
    0	    25	 92051	     searchService
    0	    82	 92853	   window (Issue Reporter)
    0	     0	 92901	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (employee.test.ts — bitgigs-server)
|  Window (Index.vue — bitgigs-admin)
|    Folder (bitgigs-server): 235 files
|      File types: js(63) ts(59) map(58) csv(16) json(11) xml(11) graphql(11)
|                  md(1) log(1) DS_Store(1)
|      Conf files: package.json(1) tsconfig.json(1) launch.json(1)
|                  settings.json(1)
|    Folder (bitgigs-admin): 125 files
|      File types: vue(27) ts(21) js(20) map(17) xml(11) json(7) svg(6)
|                  jpeg(2) ico(2) html(2)
|      Conf files: package.json(1) tsconfig.json(1) tslint.json(1)
|      Launch Configs: node;
```

</details>
<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.60
prettier-vscode|esb|1.6.1
gc-excelviewer|Gra|2.1.26
graphql-for-vscode|kum|1.12.1
vetur|oct|0.12.7
es6-mocha-snippets|spo|0.2.2

</details>

**Comment by nomadoda** [comment]
<img width="628" alt="screen shot 2018-10-02 at 18 01 36" src="https://user-images.githubusercontent.com/25898698/46361159-3ce25180-c66d-11e8-9bc1-babc8d9547db.png">

<details>
<summary>Open files and ports</summary>

> cwd
/
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Squirrel.framework/Versions/A/Squirrel
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/A/ReactiveCocoa
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Mantle.framework/Versions/A/Mantle
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/snapshot_blob.bin
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/natives_blob.bin
txt
/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/node-pty/build/Release/pty.node
txt
/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node
txt
/usr/lib/dyld
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
txt
/usr/share/icu/icudt59l.dat
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/icudtl.dat
txt
/private/var/db/dyld/dyld_shared_cache_x86_64h
0
->0xe26bacd9a1904b5
1
->0xe26bacd9a18e895
2
->0xe26bacd9a18f8fd
3
->0xe26bacd9a18ff3d
4
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/icudtl.dat
5
->0xe26bacd9a18f76d
6
->0xe26bacd9b037615
7
->0xe26bacd9b038f95
8
count=2, state=0x8
9
->0xe26bacd9b038c95
10
->0xe26bacd9b038e15
11
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/icudtl.dat
12
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/snapshot_blob.bin
13
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/natives_blob.bin
14
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/en_GB.lproj/locale.pak
15
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/content_shell.pak
16
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/pdf_viewer_resources.pak
17
->0xe26bacd7a8e9795
18
->0xe26bacd9b037c15
19
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/snapshot_blob.bin
20
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/natives_blob.bin
21
count=0, state=0xa
22
->0xe26bacd7a8ea815
23
->0xe26bacd7a8e9cd5
24
->0xe26bacd9a18f515
25
/Applications/Visual Studio Code.app/Contents/Resources/electron.asar
26
/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar
27
/dev/urandom
28
/dev/null
29
->0xe26bacd9a18f1f5
30
/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar
31
/Users/Adam/Library/Application Support/Code/logs/20181002T174641/exthost3.log
32
/var/folders/x7/dpd0pjpx79zdpgy_ppx892j00000gn/T/vscode-git-askpass-04a1bd4194ab8616455e97ab5eca7d225e1
33
35
/dev/ptmx
36
->0xe26bacd9a190325
37
->0xe26bacd96e7a0cd
38
->0xe26bacd9a190965
40
->0xe26bacd9a191135
41
->0xe26bacd96e78d45
42
->0xe26bacd9a18f385
44
->0xe26bacd9a18ef9d
45
->0xe26bacd96e79f3d
47
->0xe26bacd96e7a195

</details>

**Comment by nomadoda** [comment]
<img width="447" alt="screen shot 2018-10-02 at 18 04 43" src="https://user-images.githubusercontent.com/25898698/46361372-ba0dc680-c66d-11e8-8ab1-281b334deea9.png">
<img width="505" alt="screen shot 2018-10-02 at 18 05 08" src="https://user-images.githubusercontent.com/25898698/46361373-ba0dc680-c66d-11e8-97db-fe10350b621f.png">

**Comment by nomadoda** [comment]
Oh, now after perhaps 10 minutes or so the CPU process returns to normal and I receive this error message in VS Code:

![screen shot 2018-10-02 at 18 05 58](https://user-images.githubusercontent.com/25898698/46361432-ef1a1900-c66d-11e8-9cdc-98a27bd1940f.png)

**Comment by isidorn** [comment]
@nomadoda can you reproduce this issue with all extensions disabled?
How about with using vscode insiders https://code.visualstudio.com/insiders/

**Comment by nomadoda** [comment]
I can confirm since disabling Prettier extension problem is resolved. I will submit an issue on Prettier instead.
