### ISSUE TITLE
`code --list-extensions` should show version number

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#59838]
When I run `code --list-extensions`, I got this output:

Version 1.27.2 (1.27.2)

```
Code > code --list-extensions
[createInstance] extensionManagementService depends on downloadService which is NOT registered.
arcticicestudio.nord-visual-studio-code
dbaeumer.vscode-eslint
eg2.tslint
Equinusocio.vsc-material-theme
esbenp.prettier-vscode
msjsdiag.debugger-for-chrome
octref.vetur
vscodevim.vim
```

I suggest list versions as well. This is useful for diagnosing if an issue is caused by extensions.

A possible output could be:

```
arcticicestudio.nord-visual-studio-code@1.0.0
dbaeumer.vscode-eslint@2.0.0
```

**Comment by mcgrathg** [comment]
You can get the extension version with an extra argument `--show-versions`.
```
code --list-extensions --show-versions
```

**Comment by octref** [comment]
Even though I work on VS Code, I didn't realize that flag was there...Wondering why it's not the default behavior and need an extra flag.
