### ISSUE TITLE
Debug tree views not centerted properly on linux

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#59833]
On linux the text in elements in debug views is not centered properly
This is very weird since I set the line-height to 22px the same way as the explorer does and explorer is centered properly.

@joaomoreno let me know if you have some clue what might be going on here, did some investigation but I ran out of ideas. verticaly centering has no effect. Setting the line-height to 25px fixes the issue but that feels wrong since their actual size is 22px.
I also noticed that one of the contianers is not 100% height, it is 21.67px on linux, but chaning it to have height 100% and go up to 21.99px does not actually fix the issue.

found by @bpasero 

![image](https://user-images.githubusercontent.com/1926584/46360121-16231b80-c66b-11e8-9717-92cc996fe7ef.png)

**Comment by isidorn** [comment]
I'll fix this like a boss by adopting the new tree, pushing to November 🤠

**Comment by joaomoreno** [comment]
It will probably not be fixed in the new tree, since this is irrelevant to the tree. Linux is famously bad at text layouting, so you're just gonna have to experiment with height and line-height values.

**Comment by isidorn** [comment]
Sounds fun. I'll still leave this for a rainy november day to match my mood

**Comment by isidorn** [comment]
New tree. Optimistically closing this 🤠
