### ISSUE TITLE
Editor status remains empty when forcing to open a binary file as text

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#59832]
Steps to Reproduce:

1. open a file we think is binary
2. click on the link to force open as text
3. the editor status bar does not update

**Comment by bpasero** [comment]
If someone wants to chime in, please discuss the approach here first before starting to code :+1:

**Comment by atitoa93** [comment]
Hello @bpasero, I would like to start debugging/working on this issue. Although this issue didn't get labeled as a good first issue, this is my first contribution to vscode. Please, if you have some insights regards the issue and the starting point, please share it. Till then I will be investigating the code base more figuring out from where should I start. Thanks.

**Comment by atitoa93** [comment]
Hello again @bpasero, after some debugging I'm able to understand what's going on there. but my question is, what is the expected behavior? What should be updated on the status bar? Line and column numbers? Mode?
Thanks

**Comment by bpasero** [comment]
@atitoa93 I would expect that when I jump from binary file to text file, the editor status bar shows the same content as if the file was opened just normally. Currently we are missing an event when the editor goes from binary view to text view and `editorStatus.ts` does not react properly.

**Comment by atitoa93** [comment]
Thanks for replying back, I got it working now. I just need to double check with you before making the PR as you recommended.
The thing is the binary files link that forces the document to open as a text file, opens it in the same document and the status bar updates only if active editor changed. So what I had to do is just updating the status bar on visible editor change as well. What do you think?

![ezgif com-optimize](https://user-images.githubusercontent.com/30963134/46399807-70010100-c6be-11e8-998f-c11bf85d0a6f.gif)

**Comment by bpasero** [comment]
@atitoa93 interesting, good finding that this fixes the issue. The downside of listening to that event is that it will fire even if the active editor remains the same, so there is a chance to do work in the status bar even though nothing has changed.

Feel free to open a PR on this and I can see if this event is firing too much or not. For sure we would not have to listen to both active editor change and visible editor change. Both will fire when the active editor changes (maybe you could verify that).
