### ISSUE TITLE
Make it possible to confirm/apply popup action using keyboard

### ISSUE THREAD

**Issue by jkovzels** [Microsoft/vscode#5984]
Currently popup messages could be only dismissed using keyboard. I would be good to have a way to apply affirmative action using keyboard as well.

![popup-warn](https://cloud.githubusercontent.com/assets/351671/14917822/881a13c6-0e29-11e6-825f-817920dfb627.png)

Besides, from UX point of view 'Close' label could be misleading, as it is not always obvious that will be closed. Consider changing to 'Cancel'.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/5538
