### ISSUE TITLE
Integrated terminal select box does not update when navigating between terminals using keybindings

### ISSUE THREAD

**Issue by FadeZhanger** [Microsoft/vscode#59840]
- VSCode Version: 1.28-insider (latest commit)
- OS Version: Windows 10
- Typescript Version: 3.1.1

**Steps to Reproduce:**
1. Open two integrated terminal instances
2. Navigate between them using the "Focus Previous Terminal" and "Focus Next Terminal" keybindings (e.g. set to Alt + LeftArrow / Alt + RightArrow)

**Expected:**  
Select box changes to reflect the currently focused terminal

**Actual:**
No change in the select box

**Video:** 
http://recordit.co/FxaoctUqlq

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/59876#issuecomment-426723039
