### ISSUE TITLE
Translation Offered

### ISSUE THREAD

**Issue by loox37** [Microsoft/vscode#59843]
Hi, I can translate from English to Arabic and vice versa. I was searching in the repo but didn't find anything related to the "translation" thing-y. Any recommendations from where to start?

**Comment by lanedraex** [comment]
This [page](https://code.visualstudio.com/docs/getstarted/locales) says that vscode translations are provided via marketplace [extensions](https://marketplace.visualstudio.com/search?target=VSCode&category=Language%20Packs&sortBy=Downloads).

You can check out how to create a language pack [here](https://github.com/Microsoft/vscode-loc#visual-studio-code-language-packs).

**Comment by RMacfarlane** [comment]
Hi @loox37, thank you for your willingness to help! Right now we don't have support for right to left languages, here is the issue tracking it: https://github.com/Microsoft/vscode/issues/11770

Once that is added we would appreciate your help in translating. Here is the guide to contributing: https://github.com/Microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project

**Comment by loox37** [comment]
Damnit... I was looking forward to contribute in something :/
