### ISSUE TITLE
Add `sidebarFocus`, `panelFocus`, a real `editorFocus` and `focus` for each view

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#59858]
Related: https://github.com/Microsoft/vscode/pull/44796#issuecomment-382808742

I opened https://github.com/Microsoft/vscode/pull/59270 to add 4 commands:

- `workbench.action.previousPanelView`
- `workbench.action.previousSidebarView`
- `workbench.action.nextPanelView`
- `workbench.action.nextSidebarView`

The way I want it to work:

`Ctrl-[`:
- `workbench.action.previousPanelView` when `panelFocus`
- `workbench.action.previousSidebarView` when `sidebarFocus`
- `workbench.action.previousEditor` when `editorFocus`

`Ctrl-]`:
- `workbench.action.nextPanelView` when `panelFocus`
- `workbench.action.nextSidebarView` when `sidebarFocus`
- `workbench.action.nextEditor` when `editorFocus`

They are impossible because of many keybinding issues:

- We only have `filesExplorerFocus` for sidebar views. It's not even `explorerFocus`, meaning that focusing on `Open Editors` or `Outlines` doesn't work
- We only have `terminalFocus` for panel views.
- `editorFocus` applies to the input box in search view, input in debug console, etc. There is no context key for `editorFocus`
- `activeViewlet` and `activePanel` do not help. For example, if I have both sidebar and panel open, `activeViewlet` always wins in the following setting, even if I'm focused on terminal.

```json
[
    {
        "key": "cmd+]",
        "command": "workbench.action.nextEditor"
    },
    {
        "key": "cmd+[",
        "command": "workbench.action.previousEditor"
    },
    { "key": "cmd+]", "command": "workbench.action.nextSidebarView", "when": "activeViewlet == workbench.view.explorer" },
    { "key": "cmd+]", "command": "workbench.action.nextSidebarView", "when": "activeViewlet == workbench.view.search" },
    { "key": "cmd+]", "command": "workbench.action.nextSidebarView", "when": "activeViewlet == workbench.view.scm" },
    { "key": "cmd+]", "command": "workbench.action.nextSidebarView", "when": "activeViewlet == workbench.view.debug" },
    { "key": "cmd+]", "command": "workbench.action.nextSidebarView", "when": "activeViewlet == workbench.view.extensions" },
    { "key": "cmd+[", "command": "workbench.action.previousSidebarView", "when": "activeViewlet == workbench.view.explorer" },
    { "key": "cmd+[", "command": "workbench.action.previousSidebarView", "when": "activeViewlet == workbench.view.search" },
    { "key": "cmd+[", "command": "workbench.action.previousSidebarView", "when": "activeViewlet == workbench.view.scm" },
    { "key": "cmd+[", "command": "workbench.action.previousSidebarView", "when": "activeViewlet == workbench.view.debug" },
    { "key": "cmd+[", "command": "workbench.action.previousSidebarView", "when": "activeViewlet == workbench.view.extensions" },
    { "key": "cmd+]", "command": "workbench.action.nextPanelView", "when": "activePanel == workbench.panel.markers" },
    { "key": "cmd+]", "command": "workbench.action.nextPanelView", "when": "activePanel == workbench.panel.output" },
    { "key": "cmd+]", "command": "workbench.action.nextPanelView", "when": "activePanel == workbench.panel.repl" },
    { "key": "cmd+]", "command": "workbench.action.nextPanelView", "when": "activePanel == workbench.panel.terminal" },
    { "key": "cmd+]", "command": "workbench.action.nextPanelView", "when": "activePanel == workbench.panel.comments" },
    { "key": "cmd+]", "command": "workbench.action.nextPanelView", "when": "activePanel == workbench.view.search" },
    { "key": "cmd+[", "command": "workbench.action.previousPanelView", "when": "activePanel == workbench.panel.markers" },
    { "key": "cmd+[", "command": "workbench.action.previousPanelView", "when": "activePanel == workbench.panel.output" },
    { "key": "cmd+[", "command": "workbench.action.previousPanelView", "when": "activePanel == workbench.panel.repl" },
    { "key": "cmd+[", "command": "workbench.action.previousPanelView", "when": "activePanel == workbench.panel.terminal" },
    { "key": "cmd+[", "command": "workbench.action.previousPanelView", "when": "activePanel == workbench.panel.comments" },
    { "key": "cmd+[", "command": "workbench.action.previousPanelView", "when": "activePanel == workbench.view.search" }
]
```

**Comment by bpasero** [comment]
> I'm wondering if it's possible to generate a focus context key for each view, as implementing it in each view seems redundant.

Yes, possibly in the base class of all panels and views (`composite.ts`?)

How does this work when an extension contributes a view?

**Comment by octref** [comment]
Maybe `focusedViewlet` and `focusedPanel` similar to `activeViewlet` and `activePanel`, and make `workbench.view.<viewId>` available?

Together with a `sidebarFocus` and `panelFocus` that's managed by sidebar/panel part this would solve my problems and open up a lot of customization possibilities.

**Comment by isidorn** [comment]
@octref your last comment makes sense.
Let's assign this issue to you so you can tackle it with a PR, and I can review. If you do not have time let me know and I can look into this.
Any way this should not be assigned to Alex

**Comment by octref** [comment]
For those who are interested, here's my config:

```json
[
  { "key": "cmd+]",                 "command": "workbench.action.nextEditor" },
  { "key": "cmd+[",                 "command": "workbench.action.previousEditor" },
  {
    "key": "cmd+]",
    "command": "workbench.action.nextSidebarView",
    "when": "sidebarFocus"
  },
  {
    "key": "cmd+[",
    "command": "workbench.action.previousSidebarView",
    "when": "sidebarFocus"
  },
  {
    "key": "cmd+]",
    "command": "workbench.action.nextPanelView",
    "when": "panelFocus"
  },
  {
    "key": "cmd+[",
    "command": "workbench.action.previousPanelView",
    "when": "panelFocus"
  }
]
```

**Comment by JamesGreenaway** [comment]
The release notes shows @octref's keybindings working whilst navigating through all the panels, however when I try this myself I find it gets stuck on the terminal.  I have tried adding workbench.action.nextPanelView and workbench.action.previousPanelView to my Commands To Skip Shell however this had no effect. Does anybody know how to overcome this?
