### ISSUE TITLE
VScode deleted all the files on 1 of my branches!!!

### ISSUE THREAD

**Issue by chadidi** [Microsoft/vscode#59859]
So I was editing a file in branch "X" then I moved to branch "Y" without saving the changes in the file, then VS code deleted all files from Branch "Y".

Version: 1.27.2 (user setup)
Commit: f46c4c469d6e6d8c46f268d1553c5dc4b475840f
Date: 2018-09-12T16:17:45.060Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Steps to Reproduce:

1. edit a file from branch "X" without saving.
2. checkout to branch "Y" with VSCode editor.

**Comment by chadidi** [comment]
@joaomoreno I tried to reproduce it, with 1 file and 2 branches, and with the same repo but I couldn't reproduce it at this point, I don't know why this error happened. 

I am confused 😕.

**Comment by joaomoreno** [comment]
Alright, please keep trying, let me know if you can reproduce it.
