### ISSUE TITLE
How do I pass arguments when I use vscode to debug a program

### ISSUE THREAD

**Issue by djom20** [Microsoft/vscode#59860]
Hi Team,

Currently I'm using vscode to debug my protractor tests like a nodejs project. I add the launch.json file with this config:

```
{
     "name": "Launch",
     "type": "node",
     "request": "launch",
     "program": "${workspaceRoot}/node_modules/protractor/bin/protractor",
     "stopOnEntry": false,
     "args": [
         "${workspaceRoot}/cucumber_conf.js",
         "--cucumberOpts.tags=@surveys",
         "--cucumberOpts.tags=~@widgets",
         "--cucumberOpts.tags=~@iframes",
         "--cucumberOpts.tags=~@todo",
         "--disableChecks"
     ]
}
```

Usually I can change any command thought the command line so my doubt is how I could set whatever parameter in the args before run the debugger no need to modify the file? or if not exists any way to do that I would like to propose you add it, and maybe the debugger bar could have one dropdown with options by each arguments to customize them.

Thanks so much.

**Comment by isidorn** [comment]
Well to add args you can just modify that args array.
Currently we have no way to dynamically type them before each debug start and that is currently out of scope for us. 
An alternative how to achive this is to write an extension that would resovle debug configuraitons. That extension could use the quick pick API to get user input and fill the args array automatically. This sounds like something you would want.
