### ISSUE TITLE
[php] Non colored php function texts.

### ISSUE THREAD

**Issue by ugurozturk** [Microsoft/vscode#5986]
- VSCode Version: 1.0.0
- OS Version: Win 10

Steps to Reproduce:

1. Write Some php code like (define, session_start)
2. Then see they are like normal texts. And this is makes me feel sick.

Some codes wors well like "isset, if, for"

**Comment by aeschli** [comment]
I changed the PHP grammar to use the latest textmate grammar from https://github.com/atom/language-php.
Now when you use a theme like Monokai, you will get the coloring you want.
The VS Code default themes do, by design, only colorize declarations, not references.
