### ISSUE TITLE
VS Code mangles copyright symbol

### ISSUE THREAD

**Issue by anrossi** [Microsoft/vscode#59868]
Issue Type: <b>Bug</b>

I edited a powershell source file in VS Code which contained a Copyright symbol, ©.
I didn't edit the line with the symbol, but VS Code change the symbol to this when I saved the file: �
This only became apparent when I used git diff to see my changes, and the diff showed this change as the byte values:

```
-    Copyright = "<A9>"
+    Copyright = "<EF><BF><BD>"
```

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.18231

<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-nmake-tools|Mic|1.1.180913009
cpptools|ms-|0.19.0
PowerShell|ms-|1.9.0

</details>

**Comment by bpasero** [comment]
VS Code supports a wide range of file encodings. You can see the full list when you click on the lower right status bar where the encoding is shown and then choose to either reopen the file with a specific encoding or save the file with a specific encoding:

![image](https://user-images.githubusercontent.com/900690/33760971-db202986-dc07-11e7-8ca0-f8d8938cef7f.png)

There are two options how to configure the encoding for files

**Configure the encoding as a setting for all files or files of specific type**
We provide a `files.encoding` setting that you can use to set an encoding for all files. You can also configure this encoding for specific file types, e.g. like this:

```json
"[markdown]": {
    "files.encoding": "utf8"
}
```

**Configure VS Code to automatically detect the encoding when opening files**
We provide a `files.autoGuessEncoding` setting that you can enable to let VS Code detect the encoding of every file automatically. Note that this approach is known to not be accurate in all cases. This guessing of encoding is rather a heuristic that can produce wrong results (that is also why this setting is not enabled by default).

Please also check out issues that are already reported with the `files-encoding` label: https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afile-encoding
