### ISSUE TITLE
Terminal location doesnt change to bottom

### ISSUE THREAD

**Issue by hamedqaderi** [Microsoft/vscode#59878]
Issue Type: <b>Bug</b>

I just changed the terminal location to the right, and then when I tried to send it back to the bottom, it doesn't work. I've changed the settings to go to the bottom and even changed the JSON file manually but it doesn't work too. 

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:04:11.329Z)
OS version: Darwin x64 18.0.0

<details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|0.8.8
jshint|dba|0.10.20
vscode-eslint|dba|1.6.0
vandelay|edb|1.0.2
php-debug|fel|1.12.6
php-intellisense|fel|2.3.5
php-pack|fel|1.0.2
dotenv|mik|1.0.1
vscode-apache|mrm|1.1.1
color-highlight|nau|2.3.0
snippet-creator|nik|0.0.5
vetur|oct|0.12.7
advanced-new-file|pat|1.2.0
open-in-browser|tec|2.0.0
vim|vsc|0.16.6

(2 theme extensions excluded)

</details>

**Comment by hamedqaderi** [comment]
Sorry, it was my mistake. The terminal window was so tight that I couldn't see the move to the bottom button. When I drag the terminal to make it a little wider, this button just shows up.

**Comment by isidorn** [comment]
We have another issue for this, layout sometimes gets cut off. We'll try to fix that one
