### ISSUE TITLE
locale.json instructions are not externelized

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#5987]
I would expect these comments to be externalized since this is the entry point for changing vscode language preferences

![screen shot 2016-04-29 at 16 17 47](https://cloud.githubusercontent.com/assets/1926584/14918778/fb92ff7e-0e25-11e6-863d-0abf8927df82.png)

**Comment by dbaeumer** [comment]
They are however the content is generated on the first time use. If you switch later we don't replace the content. No further action planned.
