### ISSUE TITLE
Keybinding to focus next terminal does not update terminal dropdown list

### ISSUE THREAD

**Issue by carlocardella** [Microsoft/vscode#59876]
- VSCode Version:
```
Version: 1.28.0-insider (user setup)
Commit: 85d970acdee48f6dcecf909a0faeb3c6882217a9
Date: 2018-10-02T22:27:52.997Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```
- OS Version: Windows 10 Pro, 1803

I have added a keybinding to show the precious/next terminal when terminal has focus: 

```json
    {
        "key": "ctrl+tab",
        "command": "workbench.action.terminal.focusNext",
        "when": "terminalFocus"
    },
    {
        "key": "ctrl+shift+tab",
        "command": "workbench.action.terminal.focusPrevious",
        "when": "terminalFocus"
    },
```
The keybinding works as expected, the next or precious terminal is displayed but the dropdown with the list of open terminals is not updated accordingly, so it can be confusing to figure out which terminal is actually selected

_powershell terminal_
![image](https://user-images.githubusercontent.com/5784415/46390608-82167b80-c68d-11e8-8cef-8cf9a42b32df.png)

_git bash, but the dropdown still shows the previous powershell terminal_
![image](https://user-images.githubusercontent.com/5784415/46390626-978ba580-c68d-11e8-971c-6e14efda052b.png)

If I use the dropdown to switch terminal then everything works as expected: the problem is with the keybinding

Does this issue occur when all extensions are disabled?: Yes

**Comment by martellaj** [comment]
This isn't a new bug. It's a minor one that I haven't bothered creating an issue for, but finally decided to do it and found this. It's definitely been happening (on Insiders) for at least a week (possibly longer).

**Comment by Tyriar** [comment]
This only appears to happen on Windows, weird 😕 /cc @cleidigh

**Comment by Tyriar** [comment]
This was introduced by abee50e7650a2cd8b371652429075300d2dd96e9

**Comment by Tyriar** [comment]
Fixed in master, keeping open to pull into release/1.28

**Comment by cleidigh** [comment]
@Tyriar 
Thanks.
I think with all your new features of terminal I have to add some more tests for the select box role :-(

**Comment by martellaj** [comment]
Looks like it's resolved in today's Insiders build! 🎉

**Comment by carlocardella** [comment]
Yes, it's resolved, thanks 👍

**Comment by Guema** [comment]
Using [AutoLaunch](https://marketplace.visualstudio.com/items?itemName=philfontaine.autolaunch) ext and got the same problem without using any shortcut. since last release only (1.28).

AutoLaunched taks is displayed in terminal, but dropdown controls keeps bad state

Related ?

**Comment by Tyriar** [comment]
Merged into release/1.28 with https://github.com/Microsoft/vscode/pull/60545

**Comment by ddrrqq** [comment]
Good job! I use the Windows 10 1511 version, and I liked to use **cmd**.
I usually use **tsc** & **web server** in _tasks.json_, sometimes I switch them to view bugs infomation and use git or others, and it not work.
At first, I thought it was my **cmd** that caused this problem.
I tried a lot of ways to reset **cmd** settings. 😂

**Comment by 1020431880** [comment]
嗨，程序猿们

**Comment by Tyriar** [comment]
@0888946595 report that against the python extension https://github.com/Microsoft/vscode-python
