### ISSUE TITLE
Blocked window : we are sorry !???

### ISSUE THREAD

**Issue by djmisterjon** [Microsoft/vscode#59875]
wow what is this bug guys ?

from my side , it happen when i use batch renaming search and a app nwjs debug run from crash.
I am was batch renaming variables...
![image](https://user-images.githubusercontent.com/24865815/46390338-57382180-c6a5-11e8-8871-8de9806d89f8.png)

**Comment by djmisterjon** [comment]
that not good 
![image](https://user-images.githubusercontent.com/24865815/46390398-99616300-c6a5-11e8-8879-5d9ba6ebae41.png)

Now a lost all my change clipboard, and i can not use ctrl+Z because vscode reset !!

**Comment by djmisterjon** [comment]
i have only this debug setup 
![image](https://user-images.githubusercontent.com/24865815/46390498-18569b80-c6a6-11e8-9293-abab86664ab4.png)

**Comment by djmisterjon** [comment]
am lucky , i just made a commit , so am able to get Back , but this is not good!

**Comment by isidorn** [comment]
I have no clue what you are saying, sorry.
Please file a new issue with nice reproducable steps. Here's some guidelines on how to file issue https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions
