### ISSUE TITLE
ctrl + \ should change

### ISSUE THREAD

**Issue by MufassirShaw** [Microsoft/vscode#59879]
Issue Type: <b>Bug</b>

I was in need of using the OR binary operator but couldn't use it coz ctrl + \ is already a shortcut for opeing a split screen tab. I belive that should change. Thanks

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

**Comment by RMacfarlane** [comment]
What keyboard layout are you using?

We want to avoid changing default keyboard shortcuts as this will negatively impact people already using them. You can configure your keyboard shortcuts with `File > Preferences > Keyboard Shortcuts`. https://code.visualstudio.com/docs/getstarted/keybindings
