### ISSUE TITLE
when i running visual studio code my whole system get slow 

### ISSUE THREAD

**Issue by vino-vinoth** [Microsoft/vscode#59880]
Issue Type: <b>Performance Issue</b>

after i start visual studio the whole system will slowdown and hanging up 

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:11:15.873Z)
OS version: Linux x64 4.15.0-34-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz (4 x 2192)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|1, 1, 0|
|Memory (System)|1.77GB (0.12GB free)|
|Process Argv|/snap/vscode/59/usr/share/code/code|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   136	 10669	code main
    0	    42	 10671	   zygote
    0	   248	 10716	     window (Release Notes: 1.27.2 - Untitled (Workspace) - Visual Studio Code)
    0	    87	 10758	       extensionHost
    0	    60	 10793	         /snap/vscode/59/usr/share/code/code /snap/vscode/59/usr/share/code/resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=10758
    0	    63	 10759	       watcherService
    0	   128	 10734	     shared-process
    0	   127	 10779	     window (undefined)
    1	   107	 10800	     window (Issue Reporter)
    0	     0	 10817	   /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 10819	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Release Notes: 1.27.2 - Untitled (Workspace) - Visual Studio Code)
|    Folder (material-design): 0 files
|      File types:
|      Conf files:;
```

</details>
<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.5.6
vscode-ungit|Hir|1.6.0

</details>

**Comment by SethRzeszutek** [comment]
If you uninstall and then reinstall, is this problem repeatable? I am running an almost exact OS and version. I would try that and report back if it continues or doesn't.

**Comment by RMacfarlane** [comment]
Please follow the guide in https://github.com/Microsoft/vscode/wiki/Performance-Issues to help diagnose the issue

**Comment by RMacfarlane** [comment]
Specifically, the information that would help is 
- Do you see the same problem if you disable all extensions
- What types of files are you opening/how large is the folder?

Also, I assume by visual studio, you mean visual studio code, right?

**Comment by vino-vinoth** [comment]
> Specifically, the information that would help is
> 
> * Do you see the same problem if you disable all extensions
> * What types of files are you opening/how large is the folder?
> 
> Also, I assume by visual studio, you mean visual studio code, right?

yes, i am using vs code and i disabled all extensions but  still i got hanging whole system when opening either  when i am using 
is that problem related low memory i  my  system or intel core i3 processors i don't why??
 thanks for replying as quickly:) sorry for my poor english.

**Comment by vino-vinoth** [comment]
> If you uninstall and then reinstall, is this problem repeatable? I am running an almost exact OS and version. I would try that and report back if it continues or doesn't.
