### ISSUE TITLE
File -> Open Recent doesn't show the final destination folder with long paths

### ISSUE THREAD

**Issue by fadeevab** [microsoft/vscode#59886]
- VSCode Version: 1.27.2
- OS Version: Ubuntu 18.04

**What is wrong**: File -> Open Recent with the long similar paths does not show the final directory. Seems like it is a regression, because before (in earlier vscode versions) I managed to see the final destination.

**Steps to Reproduce**:

1. File -> Open Recent:
   ~/long/long/long/long/long/long/long/long/path1
   ~/long/long/long/long/long/long/long/long/path2
   ~/long/long/long/long/long/long/long/long/path3
2. What do I see:
   ~/long/long/long/long/long/long/long....  ?
   ~/long/long/long/long/long/long/long....  ?
   ~/long/long/long/long/long/long/long....  ?
3. **What should I see**:
   ~/long/long/long/long/long/lo..../**path1**
   ~/long/long/long/long/long/lo..../**path2**
   ~/long/long/long/long/long/lo..../**path3**

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
@isidorn is this something that would have changed with the UriDisplayService?

**Comment by isidorn** [comment]
@sbatten no, but it could be a feature request against the UriDisplayService which I think makes sense.
There could be a `maxLength: number` [here](https://github.com/Microsoft/vscode/blob/8795a9d6423a579a13c5fea4353e54e0f10ecc78/src/vs/platform/label/common/label.ts#L34) the menu would pass the maxLength and the uriDisplayService would properly cuttoff

**Comment by fadeevab** [comment]
One more: for now I use the "trick" to see the final destination: File -> Open Recent -> **More...**, there is a directory in the blue box at the start of the each line of the dropped menu.
