### ISSUE TITLE
gulp export --component vscode-distro does not work on mac

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#5988]
* mac
* git clone https://monacotools.visualstudio.com/DefaultCollection/Monaco/_git/MonacoLocalization
* gulp export --component vscode-distro 
* get the following error

Seems to be a path issue

![screen shot 2016-04-29 at 16 19 59](https://cloud.githubusercontent.com/assets/1926584/14918851/401488de-0e26-11e6-982c-12bdf4a4e97e.png)

I also had issues setting this on my win machine but for april milestone there were no strings update to vscode distro so all is good.

**Comment by dbaeumer** [comment]
As said in the OneNote I only tested it under Windows :-). And the vscode-distro translations are Windows only. Need to check if this makes it fail.

**Comment by dbaeumer** [comment]
The problem is that some of the arguments are paths and under Mac / Linux they need to be entered with forward slashes. I could also look into converting these.

**Comment by dbaeumer** [comment]
Fix in localization repository.
