### ISSUE TITLE
Master Page Template Option

### ISSUE THREAD

**Issue by vishalksuthar** [Microsoft/vscode#59895]
Please provide master page template option in HTML page design like Dreamweaver page template feature.
If we want to develop HTML static content website that time we need to change every page section one by one. If we create one master layout page for all child pages like header menu. so if we change the header menu then all child page automatically will be updated.

**Comment by chrmarti** [comment]
VS Code is all about source code editing, not about project setups. Maybe you are looking for a project generator like Yeoman or a static site generator like Gatsby.js?

**Comment by vishalksuthar** [comment]
Yes, I agreed on this source code editor, but if you provide us like site-manager option, Like we have layout option in MVC and master page in ASP.NET.  If we have this kind feature in VSCode so it is easy for HTML template designer. 
For Example.

My Client wants to develop an application but before we want to develop an application, we create HTML static pages then we going toward development.  The header section is common for all pages so if we create header layout and assign to all child pages, so easy for modification in future if any header changes.

**Comment by chrmarti** [comment]
VS Code doesn't come with support for a specific UI library/framework built-in, you need to decide which one you want to use and then install extensions and tools that support it. You can browse the available VS Code extensions here: https://marketplace.visualstudio.com/vscode

A quick way to get a basic layout and server running might be the Express.js generator. See, e.g.: https://medium.com/@bhanushali.mahesh3/creating-a-simple-website-with-node-js-express-and-ejs-view-engine-856382a4578f

**Comment by vishalksuthar** [comment]
Thank you so much.

**Comment by ali-itechpro** [comment]
@vishalksuthar 
Did you find anything similar to Dreamweaver's page template or Visual Studio master page in Visual Studio Code? I am also looking for quite a while. But could not able to find.

Master Page in Visual Studio, makes life easier. It would be good if something is similar in Visual Studio Code. I appreciate if anybody comes with that solution.

**Comment by HotelOps** [comment]
> 
> 
> @vishalksuthar
> Did you find anything similar to Dreamweaver's page template or Visual Studio's master page in Visual Studio Code? I am also looking for quite a while. But could not able to find.
> 
> Master Page in Visual Studio, makes life easier. It would be good if something is similar in Visual Studio Code. I appreciate if anybody comes up with that solution.

No Dear , I did't find any proper master page solution plugin.
