### ISSUE TITLE
Almost 100% of CPU usage after few minutes.

### ISSUE THREAD

**Issue by CaptainYouz** [Microsoft/vscode#59898]
- VSCode Version: 1.27.2
- OS Version: macOS High Sierra

Steps to Reproduce:

1. Start VS Code
2. After some time, this process `Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js` take almost 100% of CPU usage (see screenshot for process with flag, and sorry for the small font size, I had to reduce it to get all of the flags). And it does not decrease after that.

![screen shot 2018-10-03 at 15 55 53](https://user-images.githubusercontent.com/2973285/46415359-62cb2d00-c725-11e8-9f96-28fddc850021.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by robclancy** [comment]
I been getting this for like 3 months now. Can't wait for it to be ignored again and linked to "we need more details" like they won't even consider it their problem until 100 people have sent some form.

**Comment by Aghassi** [comment]
I'd like to add to this that I've had this issue beyond killing the application. I can quite VSCode, and still have CodeHelper pinning my CPU at 100%. I have to force quit it via Activity Monitor to clean it out.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by CaptainYouz** [comment]
@mjbvz 
Few comments on how/when it appears. I'm not sure at 100% but this appear generally after a file opened in the editor is changed by the system (for example if you have your `package.json` opened and you're adding/deleting modules with `npm` commands). Also, when this problem appear, it messes up the collapse system in the current files opened. Part of codes that were collapsed can not be opened anymore. I'm not sure if this is relevant or not but hope it can help you :)

**Comment by mjbvz** [comment]
Thanks. Please try collecting the TS Server log to help us investigate:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a folder with a `tsserver.log` file in it

Look through that log file for errors or stack traces. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by chris-dopuch** [comment]
I am having the exact same problem as @CaptainYouz 

VSCode Version: 1.27.2
OS Version: macOS High Sierra 10.13.6
all extensions disabled

I have a brand new create-react-app open in VSCode, my package.json is open, and I do a new `npm install`, then codehelper starts eating up my CPU and my fans start going, and it does not stop.
I'm also running htop, I get the same exact thing OP had. 

Here's a snippet of my TS Server logs, very similar to the above:
```
Info 4603 [9:39:3.262] Elapsed:: 18ms DirectoryWatcher:: Triggered with /Users/Chrisd/Projects/my-cra-app/node_modules/lodash/flatMapDepth.js :: WatchInfo: /Users/Chrisd/Projects/my-cra-app 1 Project: /dev/null/inferredProject1* WatchType: Directory of Failed lookup locations in module resolution
Info 4604 [9:39:3.262] DirectoryWatcher:: Triggered with /Users/Chrisd/Projects/my-cra-app/node_modules/lodash/_listCacheSet.js :: WatchInfo: /Users/Chrisd/Projects/my-cra-app 1 Project: /dev/null/inferredProject1* WatchType: Directory of Failed lookup locations in module resolution
Info 4605 [9:39:3.279] Elapsed:: 17ms DirectoryWatcher:: Triggered with /Users/Chrisd/Projects/my-cra-app/node_modules/lodash/_listCacheSet.js :: WatchInfo: /Users/Chrisd/Projects/my-cra-app 1 Project: /dev/null/inferredProject1* WatchType: Directory of Failed lookup locations in module resolution
Info 4606 [9:39:3.279] DirectoryWatcher:: Triggered with /Users/Chrisd/Projects/my-cra-app/node_modules/lodash/_Symbol.js :: WatchInfo: /Users/Chrisd/Projects/my-cra-app 1 Project: /dev/null/inferredProject1* WatchType: Directory of Failed lookup locations in module resolution
Info 4607 [9:39:3.297] Elapsed:: 18ms DirectoryWatcher:: Triggered with /Users/Chrisd/Projects/my-cra-app/node_modules/lodash/_Symbol.js :: WatchInfo: /Users/Chrisd/Projects/my-cra-app 1 Project: /dev/null/inferredProject1* WatchType: Directory of Failed lookup locations in module resolution
Info 4608 [9:39:3.298] DirectoryWatcher:: Triggered with /Users/Chrisd/Projects/my-cra-app/node_modules/lodash/_insertWrapDetails.js :: WatchInfo: /Users/Chrisd/Projects/my-cra-app 1 Project: /dev/null/inferredProject1* WatchType: Directory of Failed lookup locations in module resolution
Info 4609 [9:39:3.315] Elapsed:: 17ms DirectoryWatcher:: Triggered with /Users/Chrisd/Projects/my-cra-app/node_modules/lodash/_insertWrapDetails.js :: WatchInfo: /Users/Chrisd/Projects/my-cra-app 1 Project: /dev/null/inferredProject1* WatchType: Directory of Failed lookup locations in module resolution
Info 4610 [9:39:3.315] DirectoryWatcher:: Triggered with /Users/Chrisd/Projects/my-cra-app/node_modules/lodash/isMatchWith.js :: WatchInfo: /Users/Chrisd/Projects/my-cra-app 1 Project: /dev/null/inferredProject1* WatchType: Directory of Failed lookup locations in module resolution
Info 4611 [9:39:3.332] Elapsed:: 17ms DirectoryWatcher:: Triggered with /Users/Chrisd/Projects/my-cra-app/node_modules/lodash/isMatchWith.js :: WatchInfo: /Users/Chrisd/Projects/my-cra-app 1 Project: /dev/null/inferredProject1* WatchType: Directory of Failed lookup locations in module resolution
Info 4612 [9:39:3.333] DirectoryWatcher:: Triggered with /Users/Chrisd/Projects/my-cra-app/node_modules/lodash/pullAll.js :: WatchInfo: /Users/Chrisd/Projects/my-cra-app 1 Project: /dev/null/inferredProject1* WatchType: Directory of Failed lookup locations in module resolution
Info 4613 [9:39:3.351] Elapsed:: 18ms DirectoryWatcher:: Triggered with /Users/Chrisd/Projects/my-cra-app/node_modules/lodash/pullAll.js :: WatchInfo: /Users/Chrisd/Projects/my-cra-app 1 Project: /dev/null/inferredProject1* WatchType: Directory of Failed lookup locations in module resolution
Info 4614 [9:39:3.352] DirectoryWatcher:: Triggered with /Users/Chrisd/Projects/my-cra-app/node_modules/lodash/_castArrayLikeObject.js :: WatchInfo: /Users/Chrisd/Projects/my-cra-app 1 Project: /dev/null/inferredProject1* WatchType: Directory of Failed lookup locations in module resolution
Info 4615 [9:39:3.369] Elapsed:: 17ms DirectoryWatcher:: Triggered with /Users/Chrisd/Projects/my-cra-app/node_modules/lodash/_castArrayLikeObject.js :: WatchInfo: /Users/Chrisd/Projects/my-cra-app 1 Project: /dev/null/inferredProject1* WatchType: Directory of Failed lookup locations in module resolution
Info 4616 [9:39:3.369] DirectoryWatcher:: Triggered with /Users/Chrisd/Projects/my-cra-app/node_modules/lodash/round.js :: WatchInfo: /Users/Chrisd/Projects/my-cra-app 1 Project: /dev/null/inferredProject1* WatchType: Directory of Failed lookup locations in module resolution
Info 4617 [9:39:3.387] Elapsed:: 18ms DirectoryWatcher:: Triggered with /Users/Chrisd/Projects/my-cra-app/node_modules/lodash/round.js :: WatchInfo: /Users/Chrisd/Projects/my-cra-app 1 Project: /dev/null/
```

It just keeps logging these same types of errors over and over. 
I can send the full log too if that helps.

**Comment by CaptainYouz** [comment]
Hi @mjbvz 
Any news on this one?

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/vscode/issues/59898 to track this upstream
