### ISSUE TITLE
Add a setting to ignore characters in quickOpen

### ISSUE THREAD

**Issue by dorian-marchal** [Microsoft/vscode#59894]
I would like to exclude some characters from the quickOpen fuzzy search.
These characters would act like spaces (currently, spaces are ignored in quickOpen).
For example, excluding `\` would help me to quickly find PHP files corresponding to a given namespace:

When I search `\foo\bar\Baz`, I would like to find `/foo/bar/Baz.php`

(This is the behavior of Atom).

**Comment by dorian-marchal** [comment]
Related to: https://github.com/Microsoft/vscode/issues/11371

**Comment by roblourens** [comment]
I see what Atom is doing, I don't understand the reasoning behind the ignored characters. - is ignored, + is not, etc.

Are you copying/pasting from code into quickopen? Otherwise I don't understand why you have backslashes.

It probably makes sense to treat `\` as `/` at least.

**Comment by bpasero** [comment]
@roblourens at least the scorer in quick open would have to understand that / === \ (e.g. [here](https://github.com/Microsoft/vscode/blob/702633545197f9ddf6d0ae8ea7589cc53ce70455/src/vs/base/parts/quickopen/common/quickOpenScorer.ts#L152)).

Not sure how much benefit this brings.

**Comment by dorian-marchal** [comment]
> Are you copying/pasting from code into quickopen? Otherwise I don't understand why you have backslashes.

Yep, I copy paste code in quickOpen, a lot.

**Comment by roblourens** [comment]
Yeah I think it would actually be tough to implement...
