### ISSUE TITLE
Quite often when opening VS Code my display driver crashes

### ISSUE THREAD

**Issue by jsweiler** [Microsoft/vscode#5989]
- VSCode Version:1.0.0
- OS Version: Windows 10 10586.218

Steps to Reproduce: 
It happens sporadically so I'm afraid I can't give steps that will always make it happen. However it happens probably once a day, and doesn't matter if I just open it normally or use open with VS Code in File Explorer. If I close Code and open it again then it just works.

All my monitors flash black and after about a second or two I get a Windows notification that My AMD display driver stopped responding and recovered.

Just a few days ago I noticed an AMD Driver update came through Windows update, but that didn't make it any better.

I'm not sure if its a VS Code problem or a driver problem, any guidance would be appreciated.

**Comment by joaomoreno** [comment]
Strange. Can you dedicate some time to just experiment with [Electron](https://github.com/electron/electron/releases/download/v0.37.6/electron-v0.37.6-win32-ia32.zip) itself? Just open & close it, etc, see if it reproduces.

**Comment by jsweiler** [comment]
I haven't gotten it to happen just opening electron. And also it hasn't happened with Code for a little while now as well. I'm going to keep an eye out for it and see if it happens again.

**Comment by joaomoreno** [comment]
Alright closing it then, feel free to reopen.
