### ISSUE TITLE
auto closing brackets bug with non-English input

### ISSUE THREAD

**Issue by MuseBoy** [Microsoft/vscode#59892]
Issue Type: <b>Bug</b>
* change input method to non-English language(what we input won't go directly to the editor)
* type `[` and the editor auto closes brackets, so we get `[]`
*  type something, then press `esc`, the editor will auto closes brackets again, so now we get `[]]`
* repeat step 3 and we'll get more and more `]`

[bugScreenRecord.zip](https://github.com/Microsoft/vscode/files/2441827/bugScreenRecord.zip)

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:11:15.873Z)
OS version: Linux x64 4.15.0-34-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 1725)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 1|
|Memory (System)|5.72GB (0.74GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
output-colorizer|IBM|0.1.2
bracket-pair-colorizer|Coe|1.0.60
dakara-foldplus|dak|1.3.1
vscode-markdownlint|Dav|0.20.0
vscode-eslint|dba|1.6.0
translation|dus|0.0.4
gitlens|eam|8.5.6
vscode-highlight|fab|1.2.8
code-runner|for|0.9.4
select-highlight-minimap|mde|0.0.8
markdown-shortcuts|mdi|0.8.1
vscode-language-pack-zh-hans|MS-|1.27.2
python|ms-|2018.8.0
cpptools|ms-|0.19.0
java|red|0.32.0
partial-diff|ryu|1.4.0
code-settings-sync|Sha|3.1.2
markdown-preview-enhanced|shd|0.3.8
vscode-fileutils|sle|2.11.0
markdown-all-in-one|yzh|1.6.0

</details>

**Comment by rebornix** [comment]
This issue was fixed in Insiders and next Stable version.
