### ISSUE TITLE
[css] Figure out how to keep css.plist in sync with Atom css.cson?

### ISSUE THREAD

**Issue by dstorey** [Microsoft/vscode#599]
While VS Code uses the same css.plist for CSS syntax highlighting as TextMate, Atom has this own forked version that is way more up to date:
https://github.com/atom/language-css/blob/01146c2eac7d47455d5c964dd65eaeb209cfa778/grammars/css.cson

Would be nice to find a way to keep all three in sync.

Not all parts of css.plist are used in VSCode. For example some features such as the Media Query media features are highlighted from css.plist, but CSS properties that are not included in the file such as the flex box properties get highlighted anyway. I’m not 100% sure which ones need to always be up to date, and which ones don't matter for VSCode yet.

**Comment by waywardmonkeys** [comment]
I had this issue as well with my support for the [Dylan](http://opendylan.org/) language. There, we currently have highlighters for Textmate, Atom, Sublime Text and now VSCode. Unfortunately, they're all a bit different and have evolved over time.

I saw what [Magic Python](https://github.com/MagicStack/MagicPython) did though and am [trying out their toolchain](https://github.com/dylan-lang/dylan-syntax-support). This also allows for testing the syntax support which is nice.

**Comment by aeschli** [comment]
There are different possibilities here:
a. we start using the text mate bundle from https://github.com/atom/language-css
b. someone can make an extension to replace or tokenizer with the Atom one.
c. we help merging back changes from Atom https://github.com/textmate/css.tmbundle, and we can continue to use their bundle

Both a. and c. are fine with me. But as you mention, for the community it would probably be the best if we attempt c.

**Comment by egamma** [comment]
We can already do a) by converting the cson to json. If the atom one is that much better then we should do so, but in general c) is helps all the communities and I agree with @aeschli .

Option b) FirstMate used in Atom is slower than the one we have now implemented for VS Code. So the replacement would have to be at least as performant :smile: The implementation also needs to be consistent with our contribution guidelines, i.e., contributions are in TypeScript.

**Comment by dstorey** [comment]
I'm happy to update our version and commit the changes back to TextMate. When I'm finished with my current commits I'm doing we'll me more up to date than the Atom one anyway. 

I've not updated everything in the .plist yet as it doesn't look like we use parts of that file, but I can do that anyway so that TextMate doesn't get just partial updates. I just means duplicate work.

**Comment by aeschli** [comment]
@dstorey Then I wait for your new version? Otherwise I can also update to the Atom grammar and you can build on that. Let me know what you prefer.

**Comment by dstorey** [comment]
@aeschli I should be ready either tomorrow or thursday.

**Comment by aeschli** [comment]
Updating milestone to January.

**Comment by aeschli** [comment]
With @dstorey contributions from #1217 we now have our own fork of css.plist. @dstorey If this is still easy doable, it would be great to contribute our changes back to TextMate.

**Comment by dstorey** [comment]
@aeschli I can do that. Only thing is we now don't use all the info (as we don't highlight between recognised and unrecognised values), so some will only be kept up to date for TextMate and probably not tested well as I won't see the changes in VSCode.

**Comment by dstorey** [comment]
…we should also probably document somewhere what parts of this file are used (e.g. css properties, @rules) and which parts aren't (CSS values, other things?)
