### ISSUE TITLE
Enable and Disable multiple extensions

### ISSUE THREAD

**Issue by brunotassis** [Microsoft/vscode#59906]
It would be useful in the workspace settings to list all the extensions that the project uses and to enable or install automatically.

- Enable and Disable multiple extensions in GUI.
- Enable and Disable multiple extensions on the command line in the project folder.
- In the recommended extensions allow or deny the installation / automatic activation.
- In the user settings enable default extensions for all projects.

**Comment by RMacfarlane** [comment]
The first part is covered by https://github.com/Microsoft/vscode/issues/15442

For enabling/disabling multiple extensions at once, I believe https://github.com/Microsoft/vscode/issues/49826 and https://github.com/Microsoft/vscode/issues/27147 cover this

**Comment by brunotassis** [comment]
> The first part is covered by #15442
> 
> For enabling/disabling multiple extensions at once, I believe #49826 and #27147 cover this
-------------------------------------------------------------------------------------------------------------
I'm sorry for not seeing these issues.
I searched for a few hours something similar but had not found.
