### ISSUE TITLE
Collapsed panel is marked as visible

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#59900]
* set a breakpoint in `OutlinePanel#setVisible`
* collapse the outline
* reload window
* :bug: `setVisible` is called with `true` (also layout is called)

**Comment by sandy081** [comment]
Visibility and Collapsed state are different. View is visible even when it is collapsed. But the tree in outline view is not visible when the view is visible.

https://github.com/Microsoft/vscode/blob/8d44ab61c65e2928183bd46d6bef65902d06b3e5/src/vs/workbench/parts/files/electron-browser/views/openEditorsView.ts#L302
