### ISSUE TITLE
VSTS Add and CheckIn options have same description for TFS

### ISSUE THREAD

**Issue by jmjohnson117** [Microsoft/vscode#5990]
- VSCode Version: 1.0.0
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Alt-T for TFS VSTS extension menu
2. "Add" and "CheckIn" menu items have same description (seems unintentional)
![vsts menu](https://cloud.githubusercontent.com/assets/8682930/14922264/a519842c-0e04-11e6-95e5-9f7719be1bea.png)

**Comment by bpasero** [comment]
@jmjohnson117 please report against the extension!
