### ISSUE TITLE
VSC for Python

### ISSUE THREAD

**Issue by oleksandr17** [Microsoft/vscode#59901]
Issue Type: <b>Bug</b>

It's quite annoying problem 'Definition is not found'. I can't easily refer to third party packages and in some cases to my own files. I think because of sometimes autocompletion also doesn't work.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:04:11.329Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.56GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.3
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
python|ms-|2018.8.0
vsliveshare|ms-|0.3.735
python|tht|0.2.3
vscodeintellicode|Vis|1.0.4
markdown-all-in-one|yzh|1.6.0

</details>

**Comment by RMacfarlane** [comment]
This issue was moved to Microsoft/vscode-python#2785
