### ISSUE TITLE
Proxy authentication dialog does not show in the taskbar

### ISSUE THREAD

**Issue by cossio** [Microsoft/vscode#59902]
The proxy authentication dialog does not show in the taskbar in Linux Mint (I suspect it should be the same in other Linux distros). Clicking on any other window will bring this dialog to the back, and it becomes hard to find if you have many windows open.

The dialog is also not modal, so it gets hidden behind the VS code main window.

**VS Code info:**

Version: 1.27.2
Commit: f46c4c469d6e6d8c46f268d1553c5dc4b475840f
Date: 2018-09-12T07:11:15.873Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Steps to Reproduce:

1. Launch vscode in Linux Mint 18.3, behind a proxy that requires authentication
2. The proxy authentication window requesting username and password will show up, but it does not show in the taskbar.

**Comment by cossio** [comment]
Not a duplicate of that one.

**Comment by joaomoreno** [comment]
It shouldn't appear in the taskbar, since it's just a secondary window... but it is set to appear as modal, as long as there's a last focused window:

https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/auth.ts#L62

Can you show me a screenshot of how it looks?

**Comment by cossio** [comment]
I'll do when it shows up again.

**Comment by cossio** [comment]
I'm closing this, since now every time I've seen the window, it's been a proper dialog box (it doesn't hide behind the main vscode window).
