### ISSUE TITLE
Cannot run launch task after failed build - .NET Core

### ISSUE THREAD

**Issue by Blackbaud-MitchellThomas** [Microsoft/vscode#59907]
Issue Type: <b>Bug</b>

When there is a an error in my .NET Core project that causes the build triggered by the launch task to fail, I can't run a launch task until I reload the window unless I select "Debug Anyway". I hit the launch button and nothing happens. There is no log output when trying to launch the second time.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:04:11.329Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.89GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|17%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.20.0
gitlens|eam|8.5.6
dotnet-test-explorer|for|0.5.4
csharpextensions|jch|1.3.0
docomment|k--|0.1.2
azure-account|ms-|0.4.3
csharp|ms-|1.16.1
vsliveshare|ms-|0.3.735
team|ms-|1.136.0
vscode-versionlens|pfl|0.21.2
material-icon-theme|PKi|3.6.0
vscode-coverage-gutters|rya|2.2.0
code-settings-sync|Sha|3.1.2

</details>

**Comment by dbaeumer** [comment]
@isidorn assigning to you first since this is more about launch then task running. If there is something I can help with or need to address please ping.

@Blackbaud-MitchellThomas do you have a GitHub repository we can clone that demos this ?

**Comment by dbaeumer** [comment]
@isidorn might be the same as https://github.com/OmniSharp/omnisharp-vscode/issues/2575

**Comment by isidorn** [comment]
@Blackbaud-MitchellThomas can you reproduce this behavior with the latest vscode insiders
https://code.visualstudio.com/insiders/

**Comment by Blackbaud-MitchellThomas** [comment]
I created a vanilla ASP.NET web API project and confirmed I see the issue there.

https://github.com/Blackbaud-MitchellThomas/vscode-build-failure-launch-issue

I can reproduce it in the latest Insiders. I tried yesterday and confirmed again this morning with the new simple project.

**Comment by isidorn** [comment]
Let's wait for the resolution of OmniSharp/omnisharp-vscode#2575
Looks like the duplicate of that one, @Blackbaud-MitchellThomas can you please follow the discussion there

**Comment by Blackbaud-MitchellThomas** [comment]
Yep, I'll follow it. It appears to be the same issue.

**Comment by Blackbaud-MitchellThomas** [comment]
We narrowed down the cause to a bad interaction with the Live Share extension. The Live Share team is working on a fix. Closing this issue.
