### ISSUE TITLE
History: does not work on active file after reload

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#59908]
Steps to Reproduce:

1. open 1 file with > 20 lines of code
2. click into first line
3. reload window
4. click at the end of the file
5. Go > Back

=> does not work because the history is not tracking the active file properly

**Comment by mjbvz** [comment]
@bpasero Was this a candidate for September? Or just wrong milestone?

**Comment by bpasero** [comment]
@mjbvz sorry, October.
