### ISSUE TITLE
editor.parameterHints.enabled stuck at true if editor.parameterHints is false in user settings

### ISSUE THREAD

**Issue by julianlam** [Microsoft/vscode#59909]
- VSCode Version: v1.28.0-insider
- OS Version: Linux 4.15.0-34-generic #37~16.04.1-Ubuntu SMP Tue Aug 28 10:44:06 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1. In user settings json file, set `editor.parameterHints` to `false`
2. Open settings page, and **uncheck** "Parameter Hints"
3. Observe that when mouse moves away, checkbox is checked once again.
4. Remove `editor.parameterHints` from user settings json file
5. Observe that now parameter hints can be unchecked via settings page.

----

Context:

* Parameter hints is always on and obscures some code so I'd like to disable it.
* #28380 suggests using `editor.parameterHints` which was already set to `false`
* I then discovered in the settings page that if I unchecked Parameter hints, the moment the mouse leaves the checkbox it is automatically re-enabled
* Then I discovered the option is actually `editor.parameterHints.enabled`, and editor.parameterHints overrides this as always true even if the value set is false. Perhaps backwards compatibility is not right?

**Comment by roblourens** [comment]
This is https://github.com/Microsoft/vscode/issues/56768 :(

**Comment by julianlam** [comment]
Thanks
