### ISSUE TITLE
VSTS extension errors on check-in policies

### ISSUE THREAD

**Issue by jmjohnson117** [Microsoft/vscode#5991]
- VSCode Version: 1.0.0
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Alt-T in VSTS TFS extension
2. CheckIn
3. Add comment on file where check-in policies are required
4. CheckIn attempted, non-descript error reported

If there are options to specify a linked Work Item or an Override Warning, these are not shown or documented.
![error](https://cloud.githubusercontent.com/assets/8682930/14922376/3cd1c90a-0e05-11e6-8243-458f3b43b12c.PNG)

**Comment by bpasero** [comment]
@jmjohnson117 please report against the extension!
