### ISSUE TITLE
Find using whole word option doesn't work for special characters

### ISSUE THREAD

**Issue by thenem** [Microsoft/vscode#59913]
Issue Type: <b>Bug</b>

When using find with whole word option, searching for == was still finding ===.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700T CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (5.23GB free)|
|Process Argv|C:\Users\nemecb\AppData\Local\Programs\Microsoft VS Code\Code.exe .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.10
path-intellisense|chr|1.4.2
xml|Dot|2.3.2
vscode-babel-coloring|dza|0.0.4
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.39
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.6.1
angular-essentials|joh|0.4.0
Angular2|joh|6.1.5
python|ms-|2018.8.0
csharp|ms-|1.16.1
PowerShell|ms-|1.9.0
team|ms-|1.136.0
debugger-for-chrome|msj|4.10.2
angular2-inline|nat|0.0.17
material-icon-theme|PKi|3.6.0
ruby|reb|0.20.0
python|tht|0.2.3

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
It searches for "word boundaries" which are usually defined by non-alphanumeric characters, not just whitespace. It sort of seems like it should match neither, but this case isn't well-defined. This seems consistent with other editors.

I recommend searching ` == ` or using a regex.
