### ISSUE TITLE
Explorer: copy symlink instead of target when doing copy/paste operations

### ISSUE THREAD

**Issue by db585** [microsoft/vscode#59916]
![screencast 2018-10-03 20-15-27](https://user-images.githubusercontent.com/20629939/46427209-7d170200-c749-11e8-9494-7309f961c5e0.gif)

- VSCode Version: 1.27.2
- OS Version: MacOS 10.14

Steps to Reproduce:

1. In Explorer. Right click on symlink/ copy
2. On any folder right click/ paste 

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@isidorn I think my change would not make a difference for this case. I am not sure what to do here best, we could detect if the thing that is selected is a link and then copy the link, but that might confuse people that expect the opposite to happen...

**Comment by isidorn** [comment]
@bpasero yeah it is a bit leaning towards user preference. No action for now and let's wait for more feedback and we might introduce an option in the future.

**Comment by db585** [comment]
> @isidorn I think my change would not make a difference for this case. I am not sure what to do here best, we could detect if the thing that is selected is a link and then copy the link, but that might confuse people that expect the opposite to happen...

Hello, Thank You for the fast reaction.

I have my doubt that majory of people expect that coping symlink they will get whole folder been copied.
It's better look at OS behavior.
1. Finder copies just symlink
2.  Terminal 
`cp Downloads temp/`
cp: Downloads is a directory (not copied).

    but 
`cp -R Downloads temp/`
copied just symlink

BR.

**Comment by EricUW** [comment]
This feature would support our workflow that uses symlinks to shared components. +1

**Comment by celynwalters** [comment]
User preference would be great.
Seeing as though symlink status is shown in the explorer, it would at least be obvious to the user what has been copied.
+1

**Comment by awvalenti** [comment]
Same issue here on Linux. For folders, I don't know. For files, I think it's reasonable to copy file content, not to point to original target. At least, a message should be emitted to inform what's happening.
