### ISSUE TITLE
TreeDataProvider.onDidChangeTreeData can seem to block other UI

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#59928]
Issue Type: <b>Bug</b>

In the next version of GitLens (9.0), I have rebuilt how GitLens populates and updates its views. I have basically ended up with a model, that has no overhead while a view is hidden/not in view/collapsed, but when a view becomes visible again I trigger a full refresh of the tree. Functionally everything works fine, but if there is work to be done (git calls, etc) to build the nodes behind the tree, it seems to cause other UI to block. Can seemingly stop me from interacting with other trees, or switching to other activities, etc.

I can't say if this is old or new behavior as I've changed how GitLens deals with the trees, but I don't feel like any tree updates have ever affected other interactions (out side of that tree).

VS Code version: Code - Insiders 1.28.0-insider (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-03T12:44:29.343Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (19.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by eamodio** [comment]
@sandy081 I think this can be closed now -- I haven't seen it happen in a long time and I think it was related to be leaking tree items at one point.

**Comment by sandy081** [comment]
Ok. Feel free to reopen it with the profile information if you see it again.
