### ISSUE TITLE
<tab> being inserted instead of actual tabs

### ISSUE THREAD

**Issue by ssgtmccrae** [Microsoft/vscode#59925]
Occurs randomly throughout the day, not occurring in any other applications, fixed by restarting VSCode. Also having issues with VSCode forgetting the replace tabs with 2 spaces even though detect indentation is turned off. Please let me know if this human error :-)

register: lxc_info
  when: ansible_distribution_release == 'bionic'

- name: DEBUG - DEBUG - DEBUG
\<tab>\<tab>\<tab>\<tab>\<tab>\<tab>\<tab>

- name: Template Preseed file for 18.04
  template:

**Comment by vityas-off** [comment]
Have the same problem since yesterday.
os: `arch linux`,
code: `1.27.0-insider 07618102efdd63f09949ce54c161e7fd2a954ee8`
addons: 
```2gua.rainbow-brackets
Dart-Code.dart-code
Dart-Code.flutter
dbaeumer.vscode-eslint
eamodio.gitlens
eg2.tslint
esbenp.prettier-vscode
freebroccolo.reasonml
James-Yu.latex-workshop
octref.vetur
oderwat.indent-rainbow
patrys.vscode-code-outline
PeterJausovec.vscode-docker
PKief.material-icon-theme
robinbentley.sass-indented
vscodevim.vim
```

**Comment by ssgtmccrae** [comment]
Sorry for the late reply, here's the requested info.

OS: Ubuntu 18.04.1

VSCode:
Version: 1.28.0-insider
Commit: 431ef9da3cf88a7e164f9d33bf62695e07c6c2a9
Date: 2018-10-03T12:37:10.832Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Extensions:
Ansible 0.5.1
Django 0.17.0
Docker 0.3.1
GitLens 8.5.6
Jinja 0.0.8
Jupyter 1.1.4
MagicPython 1.1.0
Markdown All In One 1.6.2
markdownlint 0.20.0
Python 2018.8.0
Python Extension Pack 1.4.0
Vim 0.16.5
Visual Studio Intellicode - Preview 1.0.4
vscode-ansible-linter 0.11.0
vscode-icons 7.27.0

**Comment by RMacfarlane** [comment]
Thanks @ssgtmccrae and @vityas-off for the additional info!

Do you think this is related? https://github.com/VSCodeVim/Vim/issues/2499
Or is it less deterministic than just when you are doing a replace?

**Comment by RMacfarlane** [comment]
Yeah, I think this is an issue with the extension. Someone else has already filed at issue about it in that repo: https://github.com/Microsoft/vscode/issues/59925

Looks like the releases page has all of the previous `.vsix` files, so you could set `extensions.autoUpdate` to false and manually install an older version as a temporary workaround.

**Comment by shawnaxsom** [comment]
^^ PR is merged and should be resolved with the next VSCodeVim release.
