### ISSUE TITLE
Reopening: Step Into (F11) steps into transpiled JavaScript when debugging TypeScript that uses async/await

### ISSUE THREAD

**Issue by kabua** [Microsoft/vscode#59920]
vscode Version: 1.27.2
OS Version: Windows 10 Pro
Node Version: 8.9.3
TypeScript Version: 2.9.2

To learn more about TypeScript's `async/await` feature I've been building and stepping through the Microsoft's Sample [async app](https://github.com/Microsoft/TypeScriptSamples/tree/master/async) (that is, once I fixed 2 TS upgrade issues).

In the original "Step Into (F11) steps into transpiled JavaScript when debugging TypeScript that uses async/await #4798" issue @weinand suggested using `smartstep: true` in the `launch.json` file.

With `smartstep` set to true, I'm now taken to `async_hooks.js emitInitNative()` method and have to hit `shift-F11` to get back to the real function call.

@weinand would it be possible to have the `smartstep` skipped the `emitInitNative()` function as well?

**Comment by roblourens** [comment]
smartStep only skips unmapped lines in file with sourcemaps, but `"skipfiles": "<node_internals>/**"` should do it for you.
