### ISSUE TITLE
C++ initializer list not recognized

### ISSUE THREAD

**Issue by LoJoDo** [Microsoft/vscode#59929]
Issue: VS Code will not accept C++ initializer list

[GCC] Error Reported relative to EACH line of the source code (84 errors in total):
{
	"resource": "/home/jim/CodeProjects/HexGameProject/HexGame/Source/gamepiecemanager.cpp",
	"owner": "cmake-build-diags",
	"code": "undefined",
	"severity": 8,
	"message": "expected primary-expression before '0'",
	"source": "GCC",
	"startLineNumber": 597,
	"startColumn": 27,
	"endLineNumber": 597,
	"endColumn": 1000
}

Installed Version; Code-OSS Ver. 1.27.2

Installed Extensions:

C/C++
C/C++ Snippets
Clang-Format
CMake
CMake Tools
Git History
Material Icon Theme
Shader languages support for VSCode

Source Code:

namespace Engine
{
	class UTF32 //char character, unicode value
	{
		private:
			std::map<uint8_t, unsigned long> CharCodeMap =
			{
				{u8' ', 0x20},
				{u8'!', 0x21},
				{u8'#', 0x23},
				{u8'$', 0x24},
				{u8'%', 0x25},
				{u8'&', 0x26},
				{u8'(', 0x28},
				{u8')', 0x29},
				{u8'*', 0x2a},
				{u8'+', 0x2b},
				{u8',', 0x2c},
				{u8'-', 0x2d},
				{u8'.', 0x2e},
				{u8'/', 0x2f},
				{u8'0', 0x30},
				{u8'1', 0x31},
				{u8'2', 0x32},
				{u8'3', 0x33},
				{u8'4', 0x34},
				{u8'5', 0x35},
				{u8'6', 0x36},
				{u8'7', 0x37},
				{u8'8', 0x38},
				{u8'9', 0x39},
				{u8':', 0x3a},
				{u8';', 0x3b},
				{u8'<', 0x3c},
				{u8'=', 0x3d},
				{u8'>', 0x3e},
				{u8'?', 0x3f},
				{u8'@', 0x40},
				{u8'A', 0x41},
				{u8'B', 0x42},
				{u8'C', 0x43},
				{u8'D', 0x44},
				{u8'E', 0x45},
				{u8'F', 0x46},
				{u8'G', 0x47},
				{u8'H', 0x48},
				{u8'I', 0x49},
				{u8'J', 0x4a},
				{u8'K', 0x4b},
				{u8'L', 0x4c},
				{u8'M', 0x4d},
				{u8'N', 0x4e},
				{u8'O', 0x4f},
				{u8'P', 0x50},
				{u8'Q', 0x51},
				{u8'R', 0x52},
				{u8'S', 0x53},
				{u8'T', 0x54},
				{u8'U', 0x55},
				{u8'V', 0x56},
				{u8'W', 0x57},
				{u8'X', 0x58},
				{u8'Y', 0x59},
				{u8'Z', 0x5a},
				{u8'[', 0x5b},
				{u8']', 0x5d},
				{u8'^', 0x5e},
				{u8'_', 0x5f},
				{u8'`', 0x60},
				{u8'a', 0x61},
				{u8'b', 0x62},
				{u8'c', 0x63},
				{u8'd', 0x64},
				{u8'e', 0x65},
				{u8'f', 0x66},
				{u8'g', 0x67},
				{u8'h', 0x68},
				{u8'i', 0x69},
				{u8'j', 0x6a},
				{u8'k', 0x6b},
				{u8'l', 0x6c},
				{u8'm', 0x6d},
				{u8'n', 0x6e},
				{u8'o', 0x6f},
				{u8'p', 0x70},
				{u8'q', 0x71},
				{u8'r', 0x72},
				{u8's', 0x73},
				{u8't', 0x74},
				{u8'u', 0x75},
				{u8'v', 0x76},
				{u8'w', 0x77},
				{u8'x', 0x78},
				{u8'y', 0x79},
				{u8'z', 0x7a},
				{u8'{', 0x7b},
				{u8'|', 0x7c},
				{u8'}', 0x7d},
				{u8'~', 0x7e}
			};

void GamePieceManager::Create_GPF_Map()
{
	uint32_t Ndx{};

	GPF_Map.insert({0x30, {u8'0', ++Ndx}});
	GPF_Map.insert({0x31, {u8'1', ++Ndx}});
	GPF_Map.insert({0x32, {u8'2', ++Ndx}});
	GPF_Map.insert({0x33, {u8'3', ++Ndx}});
	GPF_Map.insert({0x34, {u8'4', ++Ndx}});
	GPF_Map.insert({0x35, {u8'5', ++Ndx}});
	GPF_Map.insert({0x36, {u8'6', ++Ndx}});
	GPF_Map.insert({0x37, {u8'7', ++Ndx}});
	GPF_Map.insert({0x38, {u8'8', ++Ndx}});
	GPF_Map.insert({0x39, {u8'9', ++Ndx}});
}

**Comment by mjbvz** [comment]
Please file this issue against the c++ tools extension
