### ISSUE TITLE
TreeView.reveal seems to always take focus, even with { focus: false } when the view is in SCM view container

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#59926]
Issue Type: <b>Bug</b>

This seems like a recent regression -- `TreeView.reveal` seems to always steal input focus even if `focus` is set to `false` (or left `undefined` as the default is `false`).

/cc @sandy081 

VS Code version: Code - Insiders 1.28.0-insider (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-03T12:44:29.343Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (18.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by sandy081** [comment]
I cannot reproduce it now. May be got fixed meanwhile with other changes.

**Comment by eamodio** [comment]
@sandy081 I can still reproduce this on today's insiders.

**Comment by sandy081** [comment]
I tried with example [here](https://github.com/Microsoft/vscode-extension-samples/blob/ext-docs/tree-view-sample/src/testView.ts) and it worked for me. Can you please give me your example so that I can try?

**Comment by eamodio** [comment]
Damn, I tried with your sample and it behaves as expected, but with GitLens (the new v9 alpha) it steals focus.

Here is the call:
https://github.com/eamodio/vscode-gitlens/blob/6857f7c6b51bce1115222ba72b9d0eb9a624541e/src/views/nodes/repositoriesNode.ts#L138-L139

Which ultimately calls this:
https://github.com/eamodio/vscode-gitlens/blob/6857f7c6b51bce1115222ba72b9d0eb9a624541e/src/views/viewBase.ts#L177-L192

**Comment by sandy081** [comment]
@eamodio Is it possible for you to debug and figure out where the focus is being set? I can help you with providing some pointers.

**Comment by eamodio** [comment]
Yeah will try. I did try writing a sample that was closer to what GitLens does but I can reproduce it so far. But still 100% of the time with GitLens.

**Comment by sandy081** [comment]
That's awesome if you can reproduce. Please check what reveal options are being sent here

https://github.com/Microsoft/vscode/blob/03f7c83b237ceb2ea8fd5eac90c21bd3b2512ceb/src/vs/workbench/api/node/extHostTreeViews.ts#L225

**Comment by eamodio** [comment]
@sandy081 I think I finally found the reproducible case -- it ONLY happens if the view is on the SCM sidebar. If it is in its own sidebar or in the explorer sidebar it all works fine.

**Comment by eamodio** [comment]
It looks like it is because of this line, as it isn't checking the focus flag first: 
https://github.com/Microsoft/vscode/blob/220bff273eed39013f24b6d26fc17f2a742ce10f/src/vs/workbench/parts/scm/electron-browser/scmViewlet.ts#L1490

It also seems to me that here, we should be passing the `focus` flag in:
https://github.com/Microsoft/vscode/blob/220bff273eed39013f24b6d26fc17f2a742ce10f/src/vs/workbench/browser/parts/views/views.ts#L549

**Comment by eamodio** [comment]
@sandy081 should that first line just be protected from being called when `focus` is falsey? And for the 2nd should `focus` be passed in?

**Comment by eamodio** [comment]
If so I can send a PR if that helps.

**Comment by eamodio** [comment]
@sandy081 sorry to bug you about this -- but I'm really hoping to get a fix in for October if possible, because this impacts a GitLens feature I'm hoping to release in the next week or two.

**Comment by sandy081** [comment]
Team decided not to take it because of our end game rules. Hence moved to November.

**Comment by eamodio** [comment]
@sandy081 this should probably be closed as this is now fixed.
