### ISSUE TITLE
Node Debugging Tools Preload Modules

### ISSUE THREAD

**Issue by andrewtomai** [Microsoft/vscode#59933]
Currently, the Node debugging tools allow you to add arguments for the program you wish to run, but there is no way to add arguments/options for node itself.  Specifically, it would be nice to be able to [preload modules when debugging](https://nodejs.org/api/cli.html#cli_r_require_module). 

Then, in `launch.json`, you could have a configuration something like the following:
```JSON
{
            "type": "node",
            "request": "launch",
             "nodeArgs": [ "--require", "reify"],
            "name": "Launch Program",
            "program": "${file}",
}
```

**Comment by isidorn** [comment]
As far as I know this is possible with an extension: 
Write an extension that contributes the nodeArgs field to launch.json and contributes a [provideDebugAdapter](https://github.com/Microsoft/vscode/blob/8795a9d6423a579a13c5fea4353e54e0f10ecc78/src/vs/vscode.proposed.d.ts#L553). The provideDebugAdapter would simply read out the nodeArgs from the config and would return them as `args` in the `DebugAdapterExecutable`.
So closing as an extension candidate.

@weinand feel free to reopen if there is a leaner way to do this

**Comment by isidorn** [comment]
After reading the api again it seems there is a limitation that `An extension is only allowed to register a DebugConfigurationProvider with a provideDebugAdapter method if the extension defines the debug type`.
So reopening and letting Andre to decide.

**Comment by weinand** [comment]
@andrewtomai @isidorn of course you can add arguments/options for node itself: just use the `runtimeArgs` property of a launch config.

I suggest that you make yourselves familiar with the available launch config properties: https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_launch-configuration-attributes

**Comment by isidorn** [comment]
@weinand forgot about those. Yeah makes perfect sense we already have such a basic thing
