### ISSUE TITLE
Find in selection button is not toggleable via the space key

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#59932]
Issue Type: <b>Bug</b>

1. Open find widget
2. Type text
3. Tab to the "Find in selection" toggle
4. Press space to toggle
5. Nothing happens

Expected to toggle the button since the rest of the toggles are toggleable via the space key. GIF below shows each toggle turning on via space, the find in selection does nothing.

![gif](https://user-images.githubusercontent.com/35271042/46439692-12989e80-c716-11e8-969a-8d9994cba1f5.gif)

VS Code version: Code - Insiders 1.28.0-insider (99b5434b0a90a024caab1cb35a1f7ca06708fefc, 2018-10-01T23:43:58.560Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.57GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|20%|

</details>

**Comment by rebornix** [comment]
Fixed via #83317.
