### ISSUE TITLE
Cursors lose sync when using "Ctrl+Arrows" during "Change all occurences (Ctrl+F2)"

### ISSUE THREAD

**Issue by guneyozsan** [Microsoft/vscode#59937]
Issue Type: <b>Bug</b>

1) Select a word and Ctrl+F2 on it.
2) Move to left or right a couple of times using Ctrl+Arrow keys. Make sure to leave the original selection
3) Come back to original selection using plain arrow without using Ctrl.
4) Cursors will lose location sync and edit different places of the original selection.
![vs-bug](https://user-images.githubusercontent.com/19275187/46443748-815a1400-c777-11e8-9706-76580205a634.gif)

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz (8 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (8.66GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|0.8.8
dart-code|Dar|2.19.0
flutter|Dar|2.19.0
php-debug|fel|1.12.6

</details>

**Comment by alexandrudima** [comment]
This is as designed. The cursors move according to your instructions. When you press arrow left/right, the cursors move by **1 character**. When you press ctrl+arrow left/right, the cursors move by **1 word**. In other words, the cursors move as you want them to move, they are not synced in any special way, they are not tied up to the initial selection in any way.

**Comment by guneyozsan** [comment]
Thanks for the explanation. Coming from Visual Studio Home, I'm having difficulty adapting (works chaotic when compared to `Ctrl+R+R`). Especially when the selection edited has some of its corresponding parts out of the visible page, this causes plenty of unintended edits during speed coding (I accidentally move out, come back, edit, all visible occurences look ok, however one occurence out of the visible area has a typo, which leads to an error. Maybe ok for compiled languages but cause run-time errors on script languages. And also blocks workflow, simple renaming turns into typo hunting.).

**Comment by alexandrudima** [comment]
@guneyozsan I'm not familiar with the keybinding `Ctrl+R+R` from Visual Studio Home, perhaps that has a name that I can search online and learn about it. Perhaps someone else already has asked for that feature in one of the existing issues?

**Comment by guneyozsan** [comment]
@alexandrudima Sorry my bad. `Ctrl+R+R` is the binding for `Refactor.Rename`. Reference: https://docs.microsoft.com/en-us/visualstudio/ide/default-keyboard-shortcuts-in-visual-studio?view=vs-2017

**Comment by alexandrudima** [comment]
@guneyozsan No problem. We also have rename, but the keybinding is `F2`. We have rename support out-of-the-box for JavaScript and TypeScript, but you need to install extensions that add this support for other programming languages.
