### ISSUE TITLE
Color scheme randomly changes to something else

### ISSUE THREAD

**Issue by edysuh** [Microsoft/vscode#59938]
Issue Type: <b>Bug</b>

Not really sure how to repro, but every now and then, the color scheme will change to a different one. Not sure, but it seems to happen when a complex key combination is pressed while using VsCodeVim. 

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (6.98GB free)|
|Process Argv|C:\Users\v-etsuh\AppData\Local\Programs\Microsoft VS Code\Code.exe --folder-uri file:///c%3A/Users/v-etsuh/Development/e2e|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.20.0
gitlens|eam|8.5.6
tslint|eg2|1.0.39
vsc-material-theme|Equ|2.4.2
python|ms-|2018.8.0
Go|ms-|0.6.90
PowerShell|ms-|1.9.0
material-icon-theme|PKi|3.6.0
vim|vsc|0.16.6

(1 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
@edysuh we don't do this in the core, so if you disable all extensions you won't reproduce this bug. Please file issues against the bad extension which is doing so or start with VSCodeVim for troubleshooting.
