### ISSUE TITLE
titleBarStyle custom on Linux has no shadow

### ISSUE THREAD

**Issue by Yanpas** [Microsoft/vscode#59931]
- VSCode Version: 1.27.2
- OS Version: Kubuntu 18.04

If you set **titleBarStyle**  to **custom** then window manager won't paint a shadow on the border of the window.

Screenshot 
![image](https://user-images.githubusercontent.com/7345761/46460928-0ff58200-c7c6-11e8-819e-b733ecf4421a.png)

**Comment by sbatten** [comment]
https://github.com/electron/electron/issues/2380
