### ISSUE TITLE
Longstanding Intellisense bug

### ISSUE THREAD

**Issue by Figbash** [Microsoft/vscode#5993]
Will somebody please give this bug some attention?  There are many of us that haven't been able to move from version 0.10.3 in December.  I would very much like to run an up to date version of VSCode.

https://github.com/OmniSharp/omnisharp-roslyn/issues/371
https://github.com/OmniSharp/omnisharp-vscode/issues/6

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#269
