### ISSUE TITLE
Triple dot for destructuring invokes and accepts completion results 

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#59934]
![dot](https://user-images.githubusercontent.com/4033249/46441736-45459580-c71c-11e8-9d72-770689ae0f39.gif)

Repro:

- Install any package with types, for example `request` and `@types/request`
- Try to type three dots in a object literal that is used as an option parameter
- `.` invokes completion and accepts them

**Comment by defaults** [comment]
@octref I would like to take this up. This will be my first contribution so can you help me get started? I have already familiar with contributing guidelines.

**Comment by octref** [comment]
@mjbvz Owns this part and he could help you out.

**Comment by mjbvz** [comment]
Thanks @defaults but this is not a good first issue as it is more complicated than it appears and may need to be fixed in 1.28.1 recovery build

**Comment by defaults** [comment]
@mjbvz thanks, will look into other issues to get familiar with codebase or you can suggest too.

**Comment by mjbvz** [comment]
Take a look at [good first issue](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) and [help wanted issues](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) to get started

**Comment by mjbvz** [comment]
Fixed upstream in TS 3.2 by https://github.com/Microsoft/TypeScript/issues/27742

Re-adding scoped workaround for this iteration since we will not be picking up 3.2 yet
