### ISSUE TITLE
Extension stop " debug-auto-launch"

### ISSUE THREAD

**Issue by vladknp** [Microsoft/vscode#59946]
- Extension Name: debug-auto-launch
- Extension Version: 1.0.0
- OS Version: Windows_NT x64 10.0.14393
- VSCode version: 1.28.0-insider

 We have written the needed data into your clipboard. Please paste:
```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 24,
		"activateCallTime": 1,
		"activateResolvedTime": 0,
		"activationEvent": "*"
	}
}
```

**Comment by RMacfarlane** [comment]
Does this happen every time you open VSCode, or only for certain projects? Can you describe in more detail the behavior you see?
