### ISSUE TITLE
WSL: Allow to save files as admin

### ISSUE THREAD

**Issue by vmaleev** [Microsoft/vscode#59941]
- VSCode Version: 1.27.2 plus Nginx.conf extension 0.5.0
- OS Version: Windows 10 Education, Ubuntu 18.04 LTS on Windows 10

Steps to Reproduce:

1. Install Ubuntu 18.4 LTS from Windows Store
2. Install X410 from Windows Store
3. Configure X410 by using article from developer https://token2shell.com/howto/x410/customizing-xfce-desktop-for-ubuntu-wsl/
4. Install VS Code from repository by this manual: https://code.visualstudio.com/docs/setup/linux
5. Run code
6. Edit any file in /etc folder
7. Save file
8. Click button: "Retry as Admin..". User can click button many times.

Result in log:

[2018-10-03 17:09:52.646] [renderer1] [error] doSave(1) - exit - resulted in a save error: Error: Permission denied writing to file (file:///etc/nginx/nginx.conf) {"$mid":1,"fsPath":"/etc/nginx/nginx.conf","external":"file:///etc/nginx/nginx.conf","path":"/etc/nginx/nginx.conf","scheme":"file"}

Does this issue occur when all extensions are disabled?:  Yes

**Comment by bpasero** [comment]
This is very unlikely to be supported by VS Code, but will keep this issue open for a bit in case somebody has opinions.

**Comment by dubfactor** [comment]
This issue was seen by many last night in my class all using WSL & VS Code. I would consider it an open subject as I have still not found a SOLVED on it.

**Comment by abelfubu** [comment]
You can change permission of the folder instead with: sudo chown -R <username> <folder>

**Comment by dubfactor** [comment]
@abelfubu 

> You can change permission of the folder instead with: sudo chown -R

Is this a result of WSL 2.0? Or was this a solution all along?

**Comment by abelfubu** [comment]
Solution!
