### ISSUE TITLE
`[ts]` problems have to be toggled with javascript.validate.enable

### ISSUE THREAD

**Issue by jamesgpearce** [microsoft/vscode#59942]
These seem to be errors relating to TypeScript but you toggle them off not with the `typescript.validate.enable` setting but `javascript.validate.enable`.

I now lose JavaScript diagnostics just because I want to use a different type system.

Expected: that I disable the `typescript.validate.enable` checkbox to lose the typescript warnings, not the JavaScript one. Also the warning is a bit disingenuous because there _are_ other type systems 😄 

![is_js_ts](https://user-images.githubusercontent.com/90942/46448995-864ea180-c73e-11e8-8520-64e4951403da.gif)

**Comment by egamma** [comment]
@jamesgpearce from looking at the screenshot I see that the language used for the file is 'JavaScript.' Therefore the error message is correct. It would be more clear when the error message is reported with the prefix `[js]` and not `[ts]`. @mattbierner and idea why this happens?

I also see that you have the flow extension installed, but this extension does not [contribute a language](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributeslanguages). I would have expected that the flow extension contributes a new language e.g. 'JS-Flow' that takes overs the `.js` file suffix. An external contribution should win over a built-in extension. A consequence for this is that the language would also need to define a grammar for colorization and some configuration for smart editing (bracket matching etc), but this could reuse the JS/TS artifacts. I haven´t tried this, but this would be better answered by the author of the flow extension.
