### ISSUE TITLE
Settings descriptions bleed into the scrollbar area

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#59940]
- VSCode Version: 1.28 Insiders
- OS Version: Windows

![image](https://user-images.githubusercontent.com/16890566/46446398-053cdd80-c731-11e8-9033-724ecb6287b7.png)

**Comment by roblourens** [comment]
Did you do something to disable word wrap in that editor? Seems that word wrap is always enabled for me even if I turn the setting off.

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/preferences/browser/preferencesEditor.ts#L1029

**Comment by ramya-rao-a** [comment]
@roblourens Looks like this only happens when `"editor.accessibilitySupport": "on"`

**Comment by roblourens** [comment]
Oh, got it. I think it's technically right because the scrollbar is supposed to overlay the code, it just looks weird because there's no border there. But I'm not going to fix it.
