### ISSUE TITLE
Cannot install extension from VSIX

### ISSUE THREAD

**Issue by GasCreature** [Microsoft/vscode#59948]
- VSCode Version: 1.27.2
- OS Version: macOS Mojave version 10.14

Steps to Reproduce:

1. Download rebornix.Ruby-0.20.0.vsix from marketplace and place file in a parking directory.
2. In VSCode, Install from VSIX... Then select the rebornix.Ruby file. Click Install.

Got ECONNREFUSED error. See attached screenshot from VSCode.

![screen shot 2018-10-03 at 11 36 21 pm](https://user-images.githubusercontent.com/2017354/46457938-eeb27880-c768-11e8-9f33-37a9c00aa7cd.png)

**Comment by auchenberg** [comment]
@GasCreature What happens if you install the extension from the Marketplace directly? Does this only happen if you install the extension as VSIX from your disk?

Try here https://marketplace.visualstudio.com/items?itemName=rebornix.Ruby

**Comment by auchenberg** [comment]
@GasCreature How come you can't access the marketplace? Are you behind firewall or proxy?

Looks like something is blocking the connection between the VS Code front-end and the back-end, which we call our "extension host"

**Comment by GasCreature** [comment]
No, I'm not behind any firewall. I've just rebooted in case that "shared.socket" thing was an orphan. No luck. I can try running tcpdump/packet trace tomorrow if I know what to look for. Here is the netstat output edited for only the shared.sock lines.

`Active LOCAL (UNIX) domain sockets
Address          Type   Recv-Q Send-Q            Inode             Conn             Refs          Nextref Addr
84b82ee27df9851f stream      0      0                0 84b82ee27df98457                0                0 /Users/fr/Library/Application Support/Code/1.27.2-shared.sock
84b82ee27df9838f stream      0      0 84b82ee2850ec3ef                0                0                0 /Users/fr/Library/Application Support/Code/1.27.2-shared.sock
`

**Comment by sandy081** [comment]
Looks like Shared process socket is not released. 

@joaomoreno Can you please advise how to get this released?

**Comment by joaomoreno** [comment]
Of course it's not released, the shared process is listening on it.

The hint appears in the screenshot... @GasCreature  where does that `/u/fr/aa` come from?

**Comment by GasCreature** [comment]
My natural home directory is /Users/fr. I symlinked /Users to /u. In addition, I set HOME to /u/fr/aa.
