### ISSUE TITLE
Not reading the prototype chain correctly

### ISSUE THREAD

**Issue by TANGL3SIT3S** [Microsoft/vscode#59943]
```js
function _super(parent, child) {
    parent.call(this);
    child.prototype = Object.create(parent.prototype);
    child.prototype.constructor = child;
}

const Animal = (function (){
    let ssn = '';

    function Animal(name) {
        this.name = name;
    }

    Animal.prototype.sayHello = function () {
        ssn = '458-49-2285';
        console.log(ssn);
    }

    return Animal;
})();


const Dog = (function () {
    let ssn = '';

    function Dog(name) {
        this.name = name;
    }

    _super(Animal, Dog);

    Dog.prototype.sayGoodbye = function () {
        console.log("Goodbye");
    }

    return Dog;
})();

console.log(new Dog().sayHello());
```
-----------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------

VSCode is telling me that sayHello() is not on the prototype chain, even though in Chrome the console reads it correctly. I believe that its a Typescript error it is saying that sayHello() is not on type on Dog, when in fact it IS.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#27554
