### ISSUE TITLE
Code Folding: support golang multiline strings

### ISSUE THREAD

**Issue by wcharczuk** [Microsoft/vscode#5994]
- VSCode Version: 1.10-insider
- OS Version: OS X 10.11.4

Steps to Reproduce:

1. Start a golang project.
2. Create a function in the form:

```go
func foo() {
    bar := `
this is a multiline string.
`
}
```

Try and collapse `func foo() {` and the multiline string is not collapsed with it.

**Comment by aeschli** [comment]
The currently implemented folding strategy is based purely on the indentation of lines. A folding region starts when a line has a smaller indent than one or more following lines, and ends when there is a line with the same or smaller indent.

To be more smart and to, for example, understand go multiline strings, we will have to go one step further and introduce language agnostic folding regions. We have issue #3422 for this.
