### ISSUE TITLE
Emmet bug: fsz12 matches with font-style instead of font-size

### ISSUE THREAD

**Issue by muratdogan17** [microsoft/vscode#59951]
- VSCode Version: 1.27.2
- OS Version: Mac OS High Sierra

Steps to Reproduce:

1. open an scss file
2. type fsz18

Does this issue occur when all extensions are disabled?: Yes

I'm using built-in emmet function while writing scss. When I start to type fsz in an scss file the tooltip show it stands for font-size : 

![image](https://user-images.githubusercontent.com/8065824/46461494-75963e00-c7c7-11e8-9f5a-2b43902983a4.png)

But If I continue to writing with a value like fsz12 it shows font-style:12px anymore.

![image](https://user-images.githubusercontent.com/8065824/46461604-c1e17e00-c7c7-11e8-8fdd-ef4660deb2ab.png)

It makes declaring font size even harder. I think this is an issue and if you think so I'll fix this issue and send a PR

**Comment by muratdogan17** [comment]
hi @blunket it works as you mentioned. But I've been using emmet for a long time and I'm familiar with the `fsz` 

I think I should fix this issue :)

**Comment by ramya-rao-a** [comment]
The issue that `fsz12` should match with `font-size` and not `font-style` is a valid one.

Emmet tries fuzzy matching to match whatever you have typed with the closest match. The emmet module we use for this fuzzy matching is https://github.com/emmetio/css-snippets-resolver

@muratdogan17 If you are interested in fixing this issue, then start with https://github.com/emmetio/css-snippets-resolver

**Comment by muratdogan17** [comment]
Hi @ramya-rao-a I'll take a look at this and try to fix it. Thanks for your detailed introductions.

**Comment by ramya-rao-a** [comment]
@muratdogan17 FYI @irrationalRock has started looking into this as well. 
See https://github.com/emmetio/css-snippets-resolver/pull/10

**Comment by irrationalRock** [comment]
I submitted a PR to fix this issue.

**Comment by rzhao271** [comment]
Closing since issue fixed now on 1.49.3
