### ISSUE TITLE
Shortcut background broken with centered editor layout

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#59952]
Steps:

1. Open new Window
2. Toggle Centered Editor layout
3. Resize the editor while holding Alt, so the other sash doesn't resize

<img width="1552" alt="screenshot 2018-10-04 at 09 24 08" src="https://user-images.githubusercontent.com/22350/46461736-54c5ec80-c7b7-11e8-9d0a-d0e0125b2c66.png">

**Comment by isidorn** [comment]
The issue here is that the watermark-box element is not belonging to the editor-area split view, thus it does not get centered.
IMHO it should be creataed inside the editor area split view just like the background image is.
forwarding to @chrmarti

**Comment by joaomoreno** [comment]
Just came here to file this issue once again. 😆

**Comment by isidorn** [comment]
Would be cool if we fix this. Workaround:
```
	"workbench.tips.enabled": false
```

**Comment by timfenney** [comment]
What are the steps to reproduce? I opened a split view editor, and even on a 4k monitor with low scaling couldn't repro it.

**Comment by joaomoreno** [comment]
Added steps to first comment. 🆗

**Comment by najmieh** [comment]
The default value in this part has to be reversed? 
https://github.com/microsoft/azuredatastudio/blob/7c6368b4b65b289c8c4c94acf020fd97ba4fd218/src/vs/workbench/contrib/watermark/browser/watermark.ts#L107-L114

**Comment by najmieh** [comment]
I 

> Would be cool if we fix this. Workaround:
> 
> ```
> 	"workbench.tips.enabled": false
> ```

I edited this part https://github.com/microsoft/azuredatastudio/pull/17977

**Comment by LSViana** [comment]
@joaomoreno I'm trying to start contributing and I noticed this could be a possible first issue to solve. After a few hours, I did solve the issue and the solution is working consistently, but I'm pretty sure it's not optimal (and it doesn't have tests 😅).

Is it okay if I submit a PR for this to get some feedback and try polishing it?

**Comment by JacksonKearl** [comment]
@LSViana yes feel free to submit a PR and we can take it from there

**Comment by LSViana** [comment]
@JacksonKearl Thanks for your prompt response!

I just submitted #149132 and I need help because I have little (to no) knowledge about the VS Code codebase.

**Comment by p4nu** [comment]
If it's okay to @LSViana I could take a look at this

**Comment by p4nu** [comment]
Do we want a css change or should we move the creation of watermark to editor area split view?

I have found the place where the background is created but I need to figure out how to move the creation of watermark there. Any examples in the codebase would be appreciated!

**Comment by p4nu** [comment]
<img width="506" alt="image" src="https://user-images.githubusercontent.com/28947061/172658483-fdf7abf9-91ed-4281-b40c-12ef34fbace4.png">

<img width="504" alt="image" src="https://user-images.githubusercontent.com/28947061/172658677-61536350-53c0-4253-ab3d-973023a4cd71.png">
