### ISSUE TITLE
Allow to copy content of call stack in left panel

### ISSUE THREAD

**Issue by jyavenard** [Microsoft/vscode#59959]
See https://github.com/Microsoft/vscode-cpptools/issues/2600 for additional information.

But additionally, it is currently not possible to copy the text showing in the debug view under call stack.

It would be good to allow for this.. Providing the call stack in the event of a crash is an essential part of bug tracking/reporting.
Something that Visual Studio Code doesn't allow on Windows.

**Comment by jyavenard** [comment]
Thanks for that.. I had missed that opion.

However. when you have 100+ threads running, having to get and right click on every single of those threads to copy the stack is a rather tenuous job.

**Comment by isidorn** [comment]
Agree but that is another feature request which we do not plan to tackle rigth now, closing

**Comment by jyavenard** [comment]
What is this habit of closing bugs telling it's done somewhere else, yet not linking to the duplicate?

quite frustrating

**Comment by isidorn** [comment]
No you misunderstood. I am saying copying stack trace of multiple threads is not what your initial comment is requesting, it is a different feature request. There is no duplicate for it, nobody requested it. And I do not think we will work on this in the forseable feature. Though if you are passionate about it feel free to open a new issue - thanks

**Comment by jyavenard** [comment]
and letting me edit the title wouldn't have been an easier approach?
