### ISSUE TITLE
Python: Writing \n in f-string causes suggestion menu to open

### ISSUE THREAD

**Issue by dxf** [Microsoft/vscode#59956]
Issue Type: <b>Bug</b>

1. Type something like `print(f'hello'), then type \n
2. Voila, needless suggestion box when you add a new line.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4130 CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.93GB (0.57GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|2.4.2
python|ms-|2018.8.0

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-python/
