### ISSUE TITLE
Provide context to format provider so it knows whether a format came from a save request/manual invocation

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#59953]
I have users that need to disable format-on-save for some sub-tree within their project. Since they can't put settings in sub-folders (without making them workspace folders, which duplicates them at the top - see https://github.com/Microsoft/vscode/issues/45470) my plan is to implement a setting where they can configure a list of files (patterns, like `files.exclude`) to exclude from formatting.

However, it'd be bette if we could exclude them from *automatic* formatting without making explicit format requests silently fail. Currently it doesn't seem like the format provider is given enough information for this.

**Comment by jrieken** [comment]
This sounds just like workarounds. what you want is settings in sub folders.

**Comment by DanTup** [comment]
> what you want is settings in sub folders

Yes, that's true! Is it on the cards? (I assumed not, but that would be *waaay* better)

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/32693

**Comment by DanTup** [comment]
I think there's actually another reason to have this that settings don't provide.

If a formatter refuses to format invalid code (which seems valid as a misplaced brace could mess everything up), it may be confusing to a user if the formatting request just "doesn't work" without giving some indication of why. Displaying a message seems reasonable.

However, if the format is being run on-save, then showing an error may be somewhat spammy.

The same is true for other commands (I opened https://github.com/microsoft/language-server-protocol/issues/1018 in LSP about this.. right now all my commands tha may be useful to run on-save just fail "silently").
