### ISSUE TITLE
Settings editor needs minimum size constraints

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#59954]
The new settings editor should have minimum size constraints:

<img width="308" alt="image" src="https://user-images.githubusercontent.com/22350/46462030-34e2f880-c7b8-11e8-86f5-057313a5b66a.png">

For example, the old settings editor can't go smaller than this: 

<img width="524" alt="image" src="https://user-images.githubusercontent.com/22350/46462110-6eb3ff00-c7b8-11e8-9d71-f414ffbc7211.png">

**Comment by roblourens** [comment]
Cool, I didn't realize I could do that...
