### ISSUE TITLE
Cmd + 2 in setting input breaks the layout

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#59958]
1. VScode out of source
2. press Cmd + 2, layout gets completly broken

I can not repro with stable, insiders.
I can not repro triggering any other group commands from the command pallete.
I do not have cmd + 2 customized to any command, it is the default set to `workbench.action.focusSecondEditorGroup`
I can alway repro. I do not see anything in the console

In the gif below the layout gets broken as soon as I press cmd + 2
![layout](https://user-images.githubusercontent.com/1926584/46466944-e3913400-c7cc-11e8-8f86-c8e98be21193.gif)

**Comment by bpasero** [comment]
@isidorn is only the left hand group broken or the right hand as well? what happens if you open an editor?

**Comment by bpasero** [comment]
@joaomoreno moving to you

**Comment by joaomoreno** [comment]
@isidorn @bpasero 

That's why you shouldn't horse a winning change... you shouldn't change a horsing win... shouldn't win a changing horse... damn it... don't touch the GRID!

**Comment by isidorn** [comment]
Works fine now -> verified

**Comment by bpasero** [comment]
@joaomoreno stay out of breaking grid, otherwise the grid-council will call you again :D
