### ISSUE TITLE
Auto updater for mac

### ISSUE THREAD

**Issue by jsloyer** [Microsoft/vscode#5995]
I have noticed there is not an auto updater for mac.  I have coded one up and would be willing to share.  What are yalls plans for updates for mac?  The way this one works that I wrote is you just pull down the zip file and you gotta open the zip file and drag the new app into Applications.

**Comment by bpasero** [comment]
@jsloyer we do use the Electron auto updater framework (Squirrel for Mac).

**Comment by jsloyer** [comment]
@bpasero it looks like there are some methods missing in the code base to do this, http://electron.atom.io/docs/api/auto-updater/.  Are you all copying in some methods to handle the updates or how does that work?  Also as of electron 0.34.0 the electron auto updater is available on windows now.  any thoughts on replacing https://github.com/Microsoft/vscode/blob/b24be3a8cefb387df045d465936285656f2fe44e/src/vs/code/electron-main/auto-updater.win32.ts with it?

**Comment by bpasero** [comment]
@joaomoreno can chime in on the questions.

**Comment by jsloyer** [comment]
@bpasero, @joaomoreno I figured it out.

Since electron now supports an installer for windows, will vscode switch to that and replace [auto-updater.win32.ts]?

**Comment by bpasero** [comment]
@jsloyer unlikely, we have moved away from Squirrel for Windows a long time ago and use a scriptable installer instead.

**Comment by joaomoreno** [comment]
I don't understand the OS X part of this. We do have auto updates.

For Windows, we moved away from the official Electron's solution into our own a while ago, and we're pretty happy with it.
