### ISSUE TITLE
Add ability to scroll horizontally in Explorer view

### ISSUE THREAD

**Issue by nikitavoloboev** [Microsoft/vscode#59955]
Not sure if this is a bug or a feature request but I can't scroll sideways in explorer view in cases where the file names are too long. I have to resize the explorer tab itself and it's annoying. 

I am on macOS 10.14 and 1.27.2 version of VS Code.

**Comment by isidorn** [comment]
Turn this on

![screen shot 2018-10-04 at 11 15 11](https://user-images.githubusercontent.com/1926584/46464493-c78a9400-c7c6-11e8-8c07-9bf397956506.png)
