### ISSUE TITLE
Fuzzy quick open should use selected text as a starting point

### ISSUE THREAD

**Issue by rojepp** [microsoft/vscode#59957]
When I select some text on a single line and hit Cmd-p/Ctrl-p to open a file, I'd like the selected text 
to be pre-populated in the fuzzy search. It should also be selected so a single keystroke will replace the pre-populated text. 

This would help with finding a reference to a file in code and quickly opening that file even when there's no definition to go to.

**Comment by RMacfarlane** [comment]
@rojepp There should already be a setting for this behavior - `editor.find.seedSearchStringFromSelection`

**Comment by rojepp** [comment]
@RMacfarlane No, that controls find, and I already had this set to true, which is the default. I want it to be able to seed the quick open as well. Sorry if my terminology is off, I'm not sure what it's called. Cmd-P/Ctrl-P.

**Comment by RMacfarlane** [comment]
Got it, I misunderstood. Thanks for clarifying!
