### ISSUE TITLE
[snippets] prefix not matching forward slashes

### ISSUE THREAD

**Issue by enjoylife** [Microsoft/vscode#5996]
- VSCode Version:1
- OS Version: win7

Steps to Reproduce:

1.  Create a snippet for the sass language: 
```
"docblock": {
		"prefix": "///",
		"description": "Creates a simple sassdoc block.",
		"body": [
			"/// $1",
			"///",
			"$2"
		]
	},
```
2.  Open up a sass file and try the snippet

However it never matches. I tried escaping them as well but to no avail. Are forward slashes not recognized?

**Comment by enjoylife** [comment]
Thanks for the bug fix.. :clap:

**Comment by jrieken** [comment]
@aeschli This still has some rough edge, esp with revealing on type and when the prefix ends with a whitespace:

```
        "prefix": "// --- ",
        "description": "TOC",
        "body": [
            "// --- $1 ------",
            "$2"
        ]
```
