### ISSUE TITLE
Flickering source control

### ISSUE THREAD

**Issue by sguillia** [microsoft/vscode#59964]
Issue Type: <b>Bug</b>

The source control system is broken. I don't know how to exactly reproduce.

I'm using Code Insiders. Please take a look at this screen recording:

![project-flicker](https://user-images.githubusercontent.com/15984272/46472421-691ce000-c7dd-11e8-8854-e6bc237dd902.gif)

Steps to reproduce:
1. Open a versioned folder (must contain .git)
2. Open a file (doesn't need to be versioned but must be saved)
3. The problem appears
4. Unfocus VS Code (click somewhere else on the OS taskbar)
5. Problem disappears in few seconds
6. See "No source control providers registered"

When the 'flickering' happens, VS Code seems to be alternating between two states:
- "Source control: git" (seems to be scanning .git)
- "No source control providers registered"

Once VS Code is unfocused, source control dies and stops to be scanned.

Re-open a file in that folder to re-trigger the issue.

In order to make a sreen recording, I had to use the screen recorder keyboard shortcuts, otherwise a click on the "Record button" would make the flickering disappear (but source control stays out of service)

My _.git_ directory was freshly git-cloned and is thus well-formed

I never had this problem before updating VS Code today.

VS Code version: Code - Insiders 1.28.0-insider (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-03T12:44:29.343Z)
OS version: Windows_NT x64 10.0.15063

**Comment by joaomoreno** [comment]
Can you reproduce with `--disable-extensions`?

**Comment by sguillia** [comment]
Yes, the screen recording has been done with `--disable-extensions`

**Comment by sguillia** [comment]
Still reproduces on 1.29.0-insider (cc5e2b41c3add18a31e87f84b5d6162566a38d6e)

But it doesn't happen on all repositories... I haven't figured out what's the triggering condition yet

**Comment by sguillia** [comment]
Seems to happen whenever the repo has a submodule

**Steps to reproduce**
There could be several ways to reproduce
1. `git clone https://github.com/sguillia/test-a` (this will clone its submodule `test-b`)
2. `code-insiders --disable-extensions test-a`
3. Flickering happens

**Full steps to reproduce**
1. Create a git repository on your own github from github.com's interface (I called it `test-a`)
2. Create a git repository on your own github from github.com's interface (I called it `test-b`)
3. `git clone https://github.com/<user>/test-a`
4. `git clone https://github.com/<user>/test-b`
5. `git submodule add https://github.com/<user>/test-b`
6. `git commit -m "Submodule" && git push`
7. `code-insiders --disable-extensions test-a`

Note: my shell is zsh under WSL on Windows 10
Note: tested with 1.29.0-insider (cc5e2b41c3add18a31e87f84b5d6162566a38d6e)

**Comment by sguillia** [comment]
I guess you can close this

This issue is old and does not reproduce on linux

I'll re-open if I ever encounter the problem again
