### ISSUE TITLE
Cannot choose vscode as default editor used by git

### ISSUE THREAD

**Issue by Sti2nd** [Microsoft/vscode#59960]
Hi,

I just want to tell you that on a new PC when downloading and installing VSCode (and restarting because of adding code to PATH) the option to choose vscode as default editor is grayed out.

Windows 10 October 2018 Update

![image](https://user-images.githubusercontent.com/6373430/46467684-a9c12d00-c7ce-11e8-8550-3ecf620307ed.png)

**Comment by equal-l2** [comment]
I think this is not a issue of VSCode but is a issue of Git for Windows.
See https://github.com/git-for-windows/git/issues/1741.

**Comment by rebornix** [comment]
Close it as it's an external issue.
