### ISSUE TITLE
Customize "Problems" number in UI to e.g. only count errors, not warnings

### ISSUE THREAD

**Issue by bfelbo** [microsoft/vscode#59967]
We'll often be working with many warnings from our linter such as a `no-console` warnings saying that a particular variable was defined, but never used. These warnings can often be safely ignored and fixed later (if they need to be fixed at all). The VS Code UI counts all these warnings along with the errors as the number displayed on the `Problems` tab and so it's hard to know when in one of the other tabs (e.g. `Debug Console`) whether there's an error that needs to be fixed. The end result is that the number gets ignored and important errors are missed.

It would be amazing if I can in the preferences set a filter similar to the one available in the `Problems` tab that determines which warnings/errors count toward the number displayed.

**Comment by sanasl1234** [comment]
Bump. The number is quite meaningless when it is overwhelmed by those unnecessary Infos from lint tools.

**Comment by hongwen000** [comment]
+1
