### ISSUE TITLE
Reopen Closed File for closed New File shows invalid resource error

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5997]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Open a new window (with no folder open)
2. Remove Untitled-1 from Working Files
3. File > Open Recent > Reopen Closed File (or Ctrl+Shift+T)

![reopenuntitled](https://cloud.githubusercontent.com/assets/12900364/14926297/518eeeea-0e00-11e6-9877-0c27d1bc4a22.PNG)

It only shows the error the first time you try to reopen the file.

**Comment by bpasero** [comment]
@Tyriar I can reproduce. I think it does not make much sense to reopen a non-modified untitled file when using the action.
