### ISSUE TITLE
Sync Across Installations

### ISSUE THREAD

**Issue by avinash-savant** [Microsoft/vscode#59975]
Use Case (as an End User):
1) I have multiple machines with VS Code installed on each of those, I want a way by which I can just resume the point where I left off on one machine to another.

Right now, I have to find the project, the files load them and then resume work. Tedious! isn't it?

2) Also, every time I install an extension on one machine and create a specific file, I have to remember the plugin, search and then install it. Not so friendly.

I think a cloud-based sync should be added to VS Code to make it cloud-enabled.

THANK YOU.

**Comment by NextLevelCloudSolutions** [comment]
While I would love to have a native sync feature there's a fantastic extension available which I use daily. I'll provide the link below:

https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

**Comment by avinash-savant** [comment]
Thanks Eric! It works just awesome. Solves my purpose.
