### ISSUE TITLE
Editor blackout rendering bug when showing diff or doing expensive actions

### ISSUE THREAD

**Issue by kwiesmueller** [Microsoft/vscode#59977]
Issue Type: <b>Bug</b>

Whenever I open diff views for search or git in random occasions over the last few months I get this annoying bug where parts of the ui get greyed out by background colored boxes and are no longer visible.
Can not reproduce intentionally and can't explain why.

Makes me freak out every time when it happens because everyhting looks good, but once you move your cursor there its gone.

![image](https://user-images.githubusercontent.com/20727293/46487185-b742db00-c7ff-11e8-9aef-cd91414d9654.png)

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:11:15.873Z)
OS version: Linux x64 4.18.9-arch1-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2101)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|4, 4, 4|
|Memory (System)|15.43GB (3.98GB free)|
|Process Argv|/opt/visual-studio-code/code|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.10
emojisense|bie|0.4.1
vscode-svgviewer|css|1.4.6
vscode-markdownlint|Dav|0.20.0
bazel-code|Dev|0.1.9
gitlens|eam|8.5.6
remotehub|eam|0.2.0
vsc-material-theme|Equ|2.4.2
vscode-pull-request-github|Git|0.1.6
todo-tree|Gru|0.0.92
kubesquash|ile|0.0.4
code-beautifier|mic|2.1.0
Angular-BeastCode|Mik|6.2.30
vscode-scss|mrm|0.6.2
vscode-kubernetes-tools|ms-|0.1.14
python|ms-|2018.8.0
Go|ms-|0.6.90
color-highlight|nau|2.3.0
vscode-yaml|red|0.0.17
code-spell-checker|str|1.6.10
sensitive-replace|vil|0.1.1
vscode-todo-highlight|way|1.0.4
vscode-open-in-github|ziy|1.3.6

(2 theme extensions excluded)

</details>

**Comment by kwiesmueller** [comment]
I also get this when moving my mouse above the code, so nothing list specific (i guess).

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/45498d93166483c2eff886e28f8dab915ae382fc/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/code-exploration_1.28.0-1538127308_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/VSCodeUserSetup-x64-1.28.0-exploration.exe)

**Comment by kwiesmueller** [comment]
I am currently using the aur package here:
https://aur.archlinux.org/packages/visual-studio-code-bin

Got to figure out how to use the version you suggested, might take until next week.

**Comment by bpasero** [comment]
@kwiesmueller https://github.com/Microsoft/vscode/issues/59977#issuecomment-428440740

**Comment by hceny-architect** [comment]
@bpasero Ok, thank you very much, I am trying to reinstall this version to see if there will be similar problems.
