### ISSUE TITLE
Code hints: intellisense layout could be improved

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#59970]
Here is how intellisense shows autocomplete information:

![image](https://user-images.githubusercontent.com/199648/46479170-c8cfb700-c7ee-11e8-90f5-09168e2bbf09.png)

As you can see, the default wrap of the description makes it really hard to read.

Suggestion: do not wrap autocomplete/intellisense text if it's not needed.

I'd rather have an horizontal scrollbar than have new lines in the middle of function parameters.

**Comment by ramya-rao-a** [comment]
Covered in #29757 and #29126
