### ISSUE TITLE
Icon for Settings, Keyboard Shortcuts and Extensions?

### ISSUE THREAD

**Issue by beastdestroyer** [microsoft/vscode#59985]
This is just a small little thing. It would improve the aesthetic: 
- Adding Gear icon to the Settings tab
- Adding say a Keyboard Button to Keyboard Shortcuts tab
- Adding an extension icon to any extension which is opened as a tab. Perhaps this could be the default logo that is present on all extensions when there isn't any image

This really doesn't need explaining so I won't go on about it.

**Comment by misolori** [comment]
@beastdestroyer just to confirm, are you talking about these file type icons:
![image](https://user-images.githubusercontent.com/35271042/46493546-7f1ea680-c7c5-11e8-8faf-a91fc087486d.png)

**Comment by beastdestroyer** [comment]
@misolori Yup

**Comment by misolori** [comment]
The file type icons are set by the `seti-ui` icon theme, so the icon would need to come from there. The only generic one that is applicable is the gear icon:
![image](https://user-images.githubusercontent.com/35271042/46494190-1cc6a580-c7c7-11e8-8591-591f5721dcbb.png)

@roblourens @sandy081 thoughts on this?

**Comment by roblourens** [comment]
I like it, is that icon used for some file type now?

**Comment by misolori** [comment]
Right now it's just used for config files (editorconfig, env, etc.)

**Comment by roblourens** [comment]
Sounds perfect for settings and keyboard shortcuts. I'm not sure about extensions?

**Comment by beastdestroyer** [comment]
@roblourens How about the icon which is used for extensions with no cover image, except edited so it would actually be seeable.If so, I could raise issues in a popular icon theme of mine too

**Comment by sandy081** [comment]
Yeah.. it does not get well with extensions editor.
