### ISSUE TITLE
Validation of debug configuration prior to debugging

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode#59989]
**Problem:**
* Users of the python extension start debugging without selecting a proper python interpreter (either not selecting one or selecting an invalid item).

**Requirement:**
We'd like to ensure user has selected a python interpreter prior to debugging. If one hasn't been selected, we'd like to display a message.

**Options:**
* Perform the validation in the launch request of the debug adapter and return an error message.
Cons: VSC displays a message, however also includes the button `[Open launch.json]`. We'd like to display the message without this button.
* Perform the validation in the `DebugConfigurationProvider.resolveDebugConfiguration`.
If invalid, then display a message to the user and return `undefined` from this method.
Cons: VSC automatically opens the `launch.json` window.

**Comment by isidorn** [comment]
Use option 2 and return `undefined`. VSC will not open the `launch.json` - more details https://github.com/Microsoft/vscode/issues/54213
Also please use vscode insiders to always be on the latest.

**Comment by isidorn** [comment]
Great. Let me know how it works for you guys.

**Comment by DonJayamanne** [comment]
Its perfect.
