### ISSUE TITLE
Breakpoint line numbers don't update in UI when sending a `changed` BreakpointEvent

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#59984]
I'm working on the debugger for Dart. I'm trying to fix a long-standing issue where we never properly "resolved" breakpoints which could result in breaking on a different line to the one the user picked. However, I've found that when trying to resolve breakpoints and sending Code a BreakpointEvent, it doesn't update the line number in the UI.

Before the debug session, my code/breakpoints looks like this:

![screen shot 2018-10-04 at 5 46 04 pm](https://user-images.githubusercontent.com/1078012/46489485-6af69b80-c7fd-11e8-9823-ff92e858c655.png)

When I run this, my DA returns an empty array for breakpoints from the `setBreakpointsRequest` call and then shortly after I sent BreakpointEvents to add the breakpoints (first at their original location) then to change them (fix the locations and mark as resolved):

```ts
} else if (kind === "BreakpointAdded") {
	this.sendBreakPointToCode(this.knownBreakpoints[event.breakpoint.id] ? "changed" : "new", event.isolate, event.breakpoint);
} else if (kind === "BreakpointResolved") {
	this.sendBreakPointToCode("changed", event.isolate, event.breakpoint);
} else if (kind === "BreakpointRemoved") {
	this.sendBreakPointToCode("removed", event.isolate, event.breakpoint);
}

// ...

private async sendBreakPointToCode(action: string, isolate: VMIsolateRef, breakpoint: VMBreakpoint): Promise<void> {
	const bp = await this.vmBpToCodeBp(isolate, breakpoint);
	console.log(`Sending ${action} BP to Code (ID: ${bp.id}) line: ${bp.line} col: ${bp.column} in ${bp.source.path}`);
	this.sendEvent(new BreakpointEvent(action, bp));
}
```

My logging outputs:

```text
Sending BP to VM for thread isolates/1019045726 file:///Users/dantup/Desktop/Dart%20Sample/bin/donotformat/test.dart 2:undefined
Sending BP to VM for thread isolates/1019045726 file:///Users/dantup/Desktop/Dart%20Sample/bin/donotformat/test.dart 9:undefined
Sending new BP to Code (ID: 1) line: 2 col: undefined in /Users/dantup/Desktop/Dart Sample/bin/donotformat/test.dart
Sending new BP to Code (ID: 2) line: 9 col: undefined in /Users/dantup/Desktop/Dart Sample/bin/donotformat/test.dart
Sending changed BP to Code (ID: 2) line: 10 col: 5 in /Users/dantup/Desktop/Dart Sample/bin/donotformat/test.dart
Sending changed BP to Code (ID: 1) line: 2 col: 13 in /Users/dantup/Desktop/Dart Sample/bin/donotformat/test.dart
```

However, VS Code never updates the breakpoint from line 9 to line 10:

![screen shot 2018-10-04 at 5 50 02 pm](https://user-images.githubusercontent.com/1078012/46489677-f53eff80-c7fd-11e8-8ae4-e3e5e41eedd8.png)

![screen shot 2018-10-04 at 5 50 06 pm](https://user-images.githubusercontent.com/1078012/46489685-f8d28680-c7fd-11e8-844d-0c8c4a0943bf.png)

**Comment by DanTup** [comment]
I can repro with a hard-coded `setBreakpointsRequest` that just sends a BP after 2 seconds then tries to change its line and resolve it after 4:

```
sponse.body = { breakpoints: [] };
setTimeout(() => {
	this.sendEvent(
		new BreakpointEvent("new",
			new Breakpoint(
				false, 9, undefined,
				new Source("test.dart", "/Users/dantup/Desktop/Dart Sample/bin/donotformat/test.dart")
			),
		),
	);
}, 2000);
setTimeout(() => {
	this.sendEvent(
		new BreakpointEvent("new",
			new Breakpoint(
				true, 9, undefined,
				new Source("test.dart", "/Users/dantup/Desktop/Dart Sample/bin/donotformat/test.dart")
			),
		),
	);
}, 3000);

this.sendResponse(response);
```

**Comment by isidorn** [comment]
@DanTup thanks for the repro steps in the last comment. However I see that you are sending two "new" breakpoint events. You should be sending first a "new" and than a "changed" event. The "changed" event shold properly update the breakpoint.
If it does not, please put a breakpoint [here](https://github.com/Microsoft/vscode/blob/b58200ca9f0feae938340b21fb2a6c8384b2b5f7/src/vs/workbench/parts/debug/electron-browser/debugSession.ts#L686) and let us know what you find

**Comment by DanTup** [comment]
Whoops, that was a bad paste - however, the repro seems to work on this machine :/ I'll try again on my work machine when I can and post back, and if the repro is good I'll put breakpoints there in the real code that's failing. Thanks!

**Comment by isidorn** [comment]
No problem, let me know how it goes.

**Comment by DanTup** [comment]
This turned out to be a silly error on my part - there was a code path that logged that it was sending a `BreakpointEvent` but did not (the code is slightly complicated by breakpoints being per-thread and there may be 0 threads at the time `setBreakpointsRequest` is called). Apologies!

**Comment by DanTup** [comment]
Actually, this is still failing. I put a breakpoint where requested and the first two hits are as expected - a `new` breakpoint with id `1` and `2`. However when the the `changed` request comes in to move breakpoint `2` to `line: 10` I see this:

![screen shot 2018-10-08 at 8 53 25 am](https://user-images.githubusercontent.com/1078012/46597368-c06dc980-cad7-11e8-9f8e-a57664b3cce6.png)

It looks like `breakpoint` is undefined (eg. it didn't find `breakpoing.id=2` in the model). However, I'm unable to inspect any values here (watch/console just return undefined for everything) and trying to add breakpoints to lines puts them in the wrong place, so it's hard to debug properly.

**Comment by DanTup** [comment]
From there, I hit `Step Over` and it stopped on line 382 (as expected), then I hit `Step Over` again expecting it to stop on 391 but it didn't, it stopped on 399. I don't know whether that's really where it is or not. 

![screen shot 2018-10-08 at 8 55 46 am](https://user-images.githubusercontent.com/1078012/46597442-fdd25700-cad7-11e8-8ad1-d4245c70f243.png)

**Comment by DanTup** [comment]
Ok, somehow my tooltips are showing more info here. Not sure what's with `idFromAdapter` here - it should be `2` but it's showing `(...)` (I don't appear to be able to inspect it any further - `this.model` doesn't exist in console/watch window):

![screen shot 2018-10-08 at 9 01 37 am](https://user-images.githubusercontent.com/1078012/46597624-df209000-cad8-11e8-932a-fcece15bde1d.png)

**Comment by DanTup** [comment]
Aha, I was able to `Store in Global variable` to get at it. The `(...)` was a getter, and when invoked, it returned `undefined`:

![screen shot 2018-10-08 at 9 03 38 am](https://user-images.githubusercontent.com/1078012/46597697-2018a480-cad9-11e8-8063-a53f913aeb49.png)

So the issue seems to be that `idFromAdapter` is not set correctly on the original breakpoints so it's not finding it during the `changed` event).

Breaking back on the call where the breakpoint was added with `new`, we definitely had the ID:

![screen shot 2018-10-08 at 9 05 37 am](https://user-images.githubusercontent.com/1078012/46597766-5ce49b80-cad9-11e8-86d3-6ede253e81f6.png)

However, it seems like on the next hit, the `idFromAdapter` getter calls `getSessionData` and gets `undefined` back.

I'll see if I can try and get my small repro working; it'll probably be much easier if you can repro it than my blindly stepping through code I'm not familiar with.

**Comment by isidorn** [comment]
@DanTup cool investigation. I pushed some simplification which I think will not fix the issue but might affect it.
We are very close, can you just dig a bit deeper in your previous to last comment.
What I am interested in is when `idFromAdapter` call `getSessionData` and gets `undefined` back can you check what is the `this.sessionId` and how does the `sessionData` map look like?

I did not follow your repro steps since I have to clone your repo for it as far as I undertand. If you could create a simple repo on github with that code that I just clone, that would be better.

**Comment by DanTup** [comment]
@isidorn Sorry for the delay. Looks like the `sessionID` is a GUID but `sessionData` is empty:

![screen shot 2018-10-17 at 10 48 59 am 2](https://user-images.githubusercontent.com/1078012/47078105-6fa65100-d1fa-11e8-92f4-55444351bbe4.png)
![screen shot 2018-10-17 at 10 49 05 am 2](https://user-images.githubusercontent.com/1078012/47078106-6fa65100-d1fa-11e8-89af-7b35eaa12936.png)

Let me know if I should try anything (or if you can't repro this yourself and think it's specific to my DA, let me know and I can try to make a copy of my extension with no dependencies that you could just run).

**Comment by DanTup** [comment]
(note: I was tested in the current Insiders, so it had the change you mentioned above).

**Comment by isidorn** [comment]
Great. One more time and I think we are good

Put a breakpoint [here](https://github.com/Microsoft/vscode/blob/eda14d219f89fd0a7456304f7551e53f8264d995/src/vs/workbench/parts/debug/electron-browser/debugSession.ts#L696)
And please figure out why this [call](https://github.com/Microsoft/vscode/blob/eda14d219f89fd0a7456304f7551e53f8264d995/src/vs/workbench/parts/debug/electron-browser/debugSession.ts#L726) does not set the sessionData on the breakpoint - it should not be an empty map.

**Comment by DanTup** [comment]
@isidorn At the time that idFromAdapter is called (and returns undefined), the code you point to has never been executed - it's inside `event.body.reason === 'changed'` but the first entry to here was `reason === 'new'`. Should there by some code in the `event.body.reason === 'new'` path that also set the session data?

**Comment by DanTup** [comment]
@isidorn Let me know if the above makes sense or you need any more info from me (the issue is currently tagged needs-more-info).

**Comment by isidorn** [comment]
@DanTup thanks a lot for this great investigation. I believe I have fixed the issue, can you please try it out in tomorrow's insiders and let me know if the issue is fixed. Thank you

**Comment by DanTup** [comment]
@isidorn Now when the breakpoint is added, a space appears in the breakpoint list, but the breakpoint text/file/line/etc. do not appear:

![screen shot 2018-10-24 at 2 33 08 pm](https://user-images.githubusercontent.com/1078012/47434148-d77c0f00-d799-11e8-94b6-4e41212e8686.png)

The breakpoint shown here is an existing one - the space below it is where the new one should be (that space only appeared after 2 seconds, when my code fired).

Console has this error:

```
 ERR Cannot read property 'toString' of undefined: TypeError: Cannot read property 'toString' of undefined
    at e.renderElement (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4786:182)
    at e.renderElement (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:854:762)
    at e.insertItemInDOM (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:425:295)
    at e._splice (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:422:965)
    at e.splice (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:421:805)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:7:407
    at Array.forEach (<anonymous>)
    at e.splice (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:7:378)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:860:86
    at e.bufferEvents (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:186:889)
    at i.e.splice (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:860:42)
    at t.onBreakpointsChange (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4783:981)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4779:587
    at e.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:183:466)
    at e.setBreakpointSessionData (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2634:661)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4847:236
    at e.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:183:466)
    at t.eventCallback (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2652:207)
    at t.e.acceptMessage (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2663:318)
    at t.handleData (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2664:595)
    at Socket.<anonymous> (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2664:91)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

**Comment by DanTup** [comment]
`breakpoint.lineNumber` is undefined:

![screen shot 2018-10-24 at 2 36 30 pm](https://user-images.githubusercontent.com/1078012/47434343-49ecef00-d79a-11e8-934c-ac73cfb93d85.png)
![screen shot 2018-10-24 at 2 36 45 pm](https://user-images.githubusercontent.com/1078012/47434345-49ecef00-d79a-11e8-8cfd-9aebfd42d104.png)

**Comment by isidorn** [comment]
I believe that is because you are sending the `"lineNumber": 5` in the `Breakpoint` body. You should send `"line": 5` since `lineNumber` is called `line` in the debugProtocol. I bit weird yeah I know. https://github.com/Microsoft/vscode/blob/e3938ba331f36aa1739356b8d93a8586a8e549de/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L1470

**Comment by DanTup** [comment]
Ugh, doh! You're right - me repo works correctly with that fixed!

I'll see if I can wire it all up for real now, thanks for your help!

**Comment by isidorn** [comment]
Welcome, let me know if it works so I add the verified label here

**Comment by DanTup** [comment]
@isidorn I'm still having issues when I switch to my real code - which is weird because I've copied the JSON and sending the same events in timeouts from setBreakpointRequest appears to not have the issue!

I'm trying to debug, but when I put breakpoints in this code, it seems to break on different lines. For example, if I try to put breakpoints on line 721 here, it always immediately jumps to 726 (and then never gets hit). I'm not sure if the source maps are somehow out of date/incorrect. Is there a better way to debug this?

**Comment by DanTup** [comment]
Ok, I think I know what's going wrong. I think it's related to having two ways to provide breakpoints - one in the response to `setBreakpointRequest` and one via `sendEvent(new BreakpointEvent())`.

I was trying to return an empty list from `setBreakpointsRequest` and always send events (because that way I don't need to keep track of which breakpoints I already returned from `setBreakpointsRequest` so I know to send `changed` instead of `new`), however if those events arrive *before* `setBreakpointsEvents` returns, it seems like things don't work correctly.

Are there any issues with sending events for breakpoints with `reason: new` even though they were already returned from `setBreakpointsRequest` (or always using `changed`) so I don't have to keep track of breakpoints returned from `setBreakpointsRequest` and delay the breakpoint events that from from my VM if `setBreakpointsRequest` hasn't finished yet?

**Comment by DanTup** [comment]
Ugh, I tried some things out and they didn't work, so I reverted them, and now it appears to be working! And it turns out I was already tracking BPs I'd sent to Code (either from events or `setBreakpointsRequest`) and using that to decide whether to use `new` or `changed`). That said, I still think it'd be nice to have an add-or-update to simplify things :-)

Anyway, I'll add some integration tests around this and post back shortly if I think it's all working fine (I suspect it is).

**Comment by DanTup** [comment]
Whoops, think I found what the difference was ;-)

<img width="830" alt="screen shot 2018-10-25 at 4 56 12 pm" src="https://user-images.githubusercontent.com/1078012/47513812-f13f5400-d876-11e8-8335-4edeb8e5bba8.png">

**Comment by DanTup** [comment]
Sorry for the spam :(

I think the issue happens when I send an empty array of breakpoints in `setBreakpointsRequest`. This happens when my VM hasn't got any threads yet (I can only send breakpoints to threads).

Is it valid to send an empty array back from `setBreakpointsRequest` and then just send events later, or do I need to send back the same list that was sent to `setBreakpointsRequest`? (they're different types, so I'd have to map them).

**Comment by DanTup** [comment]
Ok, I can repro my issue with hard-coded code now.

```ts
protected async setBreakPointsRequest(
	response: DebugProtocol.SetBreakpointsResponse,
	args: DebugProtocol.SetBreakpointsArguments,
): Promise<void> {

	setTimeout(() => {
		this.sendEvent(
			new BreakpointEvent("new",
				{
					column: undefined,
					id: 2,
					line: 13,
					source: new Source("test.dart", "/Users/dantup/Desktop/Dart Sample/bin/donotformat/test.dart"),
					verified: false,
				} as DebugProtocol.Breakpoint,
			),
		);
	}, 2000);
	setTimeout(() => {
		this.sendEvent(
			new BreakpointEvent("changed",
				{
					column: undefined,
					id: 2,
					line: 14,
					source: new Source("test.dart", "/Users/dantup/Desktop/Dart Sample/bin/donotformat/test.dart"),
					verified: true,
				} as DebugProtocol.Breakpoint,
			),
		);
	}, 4000);

	response.body = { breakpoints: [] };
	this.sendResponse(response);
}
```

This code sends 0 breakpoints in response to `setBreakPointsRequest` to simulate my code - I can't provide any breakpoints yet because there are no threads. Then 2 seconds later it sends a `new` breakpoint (simulating that a thread started, and I sent the breakpoint, and got one back from the VM with an ID). Then 2 seconds later it tries to update that breakpoint (simulating that the VM resolved the breakpoint).

However, the UI remains showing line 13.

**Comment by DanTup** [comment]
I got slightly further by returning the original breakpoints instead of an empty list:

```ts
response.body = {
			breakpoints: args.breakpoints.map((b) => ({
				column: b.column,
				line: b.line,
				source: args.source,
			} as DebugProtocol.Breakpoint)),
		};
```

This way the breakpoint goes grey (unresolved), but the updates don't work. My guess is that's because I don't have IDs assigned in the response to `setBreakpointsRequest` (but I can't provide IDs at this point, since I don't have them).

I'm starting to think that maybe it's not valid/expected to not be able to respond to `setBreakpointsRequest` with breakpoints with IDs if I want to be able to modify them later? I'd really like to return nothing, and just send the events when my VM is awake later.

**Comment by isidorn** [comment]
@DanTup can we create a new issue with some repro steps and clear concise information?
Reading the above comments it is a bit cryptic to me what is going on :)

**Comment by DanTup** [comment]
I've opened #62264.
