### ISSUE TITLE
Incorrect bracket matching razor files

### ISSUE THREAD

**Issue by CoenraadS** [microsoft/vscode#59980]
Issue Type: <b>Bug</b>

```
@{
    // Loop over numbers and display them.
    for (int i = 0; i < 5; i++)
    {
        for (int i = 0; i > 5; i++)
        {
        
        }
    }
}
```

![image](https://user-images.githubusercontent.com/5593825/46488310-97f97d00-c802-11e8-83d2-57bc2d96783f.png)

`<>` are matched although they are maths operators

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|3.0.2
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
githistory|don|0.4.3
tslint|eg2|1.0.39
python|ms-|2018.8.0
cpptools|ms-|0.19.0
debugger-for-chrome|msj|4.10.2
show-offset|ram|0.0.4
rust|rus|0.4.10
partial-diff|ryu|1.4.0
code-settings-sync|Sha|3.1.2
unity-debug|Uni|1.3.0
markdown-all-in-one|yzh|1.6.0

</details>

**Comment by CoenraadS** [comment]
The brackets are some what language aware, it doesn't happen in c# for example. Not sure what the difference is.

**Comment by thany** [comment]
I suspect bracket matches is done with a nasty regex. So it's language-aware in that it knows which types of brackets to match, but doesn't know (rather, doesn't care) *how* to match them.
