### ISSUE TITLE
Deleting a folder in Code that is open in another instance does nothing

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5999]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Open a folder
2. Open a new window a directory above the already open folder
3. Delete the originally opened folder in the new instance

It hangs for a few seconds, then removes the folder from the explorer but does not move it to the recycle bin and effectively does nothing. No warnings or errors. Refreshing the folder just relists it in explorer.

**Comment by bpasero** [comment]
@vsccarl you cannot delete a folder that is open as workspace in another vs code instance. the file watcher will lock it. You will need to close the window first before doing that.
