### ISSUE TITLE
Keybindings: Focus on repl not working if focused on terminal 

### ISSUE THREAD

**Issue by Lee182** [Microsoft/vscode#59998]
Issue Type: <b>Bug</b>

Hello I've configured these keybindings so that I quickly go from terminal stuff to node debugging

```
  {
    "key": "ctrl+3",
    "command": "workbench.action.terminal.focus"
  },
  {
    "key": "ctrl+4",
    "command": "workbench.debug.action.focusRepl"
  }
```
I've noticed that if I'm already focused on the terminal, pressing ctrl+4 to focus on the debug console does not work. weirdly though If i press ctrl+1 to  focus on the first editor then ctrl+4 it will focus on the repl.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:11:15.873Z)
OS version: Linux x64 4.14.71-1-MANJARO

**Comment by Tyriar** [comment]
You need to add `"workbench.debug.action.focusRepl"` to the `"terminal.integrated.commandsToSkipShell"` setting to have it bypass the terminal process.
