### ISSUE TITLE
Angular Language Service infinit progress when going to definition

### ISSUE THREAD

**Issue by alexesca** [Microsoft/vscode#59993]
Issue Type: <b>Bug</b>

After a while of having my editor open, Angular Language Service stops working. It stays in an infinit progress. The blue bar keeps spinning for ever.

This extension has had problems sinces I started using it. I need to reset VS Code insider or install the last update so that it can continue to work normally.

VS Code version: Code - Insiders 1.28.0-insider (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-03T12:44:29.343Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.74GB (6.17GB free)|
|Process Argv|--folder-uri file:///a%3A/EliteRoofing/contract-estimator|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
ng-template|Ang|0.1.10
path-intellisense|chr|1.4.2
angular-schematics|cyr|1.8.1
vscode-simpler-icons|dav|1.6.5
angular-extension-pack|dog|6.5.3
auto-rename-tag|for|0.0.15
beautify|Hoo|1.4.4
Angular2|joh|6.1.5
intellij-idea-keybindings|k--|0.2.27
Angular-BeastCode|Mik|6.2.30
python|ms-|2018.8.0
typescript-javascript-grammar|ms-|0.0.45
es6-mocha-snippets|spo|0.2.2
code-spell-checker|str|1.6.10
move-ts|str|1.11.3
JavaScriptSnippets|xab|1.7.0

</details>

**Comment by rebornix** [comment]
@alexesca please file issue against Angular extension and start investigation from there first, thanks!
