### ISSUE TITLE
Several Problems after new installation of Windows 10 1809

### ISSUE THREAD

**Issue by flddr** [Microsoft/vscode#59996]
Issue Type: <b>Bug</b>

After complete new installation of 1809 i tried both, **VS Code 1.27.2 User and System**, but i have the following problems:

![image](https://user-images.githubusercontent.com/42785945/46505234-c8f0a680-c830-11e8-9ad7-643fa3d119bb.png)

#### 1) terminal window: no cursor (looks dead); initial wrong textposition
![image](https://user-images.githubusercontent.com/42785945/46505025-0ef93a80-c830-11e8-8ebc-3217981d7387.png)
This is with _powershell_ and _cmd_

#### 3) Git-2.19.0-64-bit.exe installer does not work with VS Code as editor ("next" inactive)
![image](https://user-images.githubusercontent.com/42785945/46505082-3c45e880-c830-11e8-930d-a19ba2a5b5c4.png)
![image](https://user-images.githubusercontent.com/42785945/46505160-7b743980-c830-11e8-8b71-36f165f672a4.png)

I tried several times.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2640M CPU @ 2.80GHz (4 x 2791)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (13.67GB free)|
|Process Argv|C:\Users\name\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by jsschultz** [comment]
I am having the same issue (also installed Windows 10 October 2018 update recently). Let me know if you need more info.

**Comment by flddr** [comment]
**integrated-terminal** 2 times in an hour: my SSH-Connection also "..reset by peer.." after some time, but server stays online. This actually with `"terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe"`

After that, my internet connection (WLAN) is broken.

**With normal Windows cmd (standalone) everything is ok.**

**Comment by Astrantia** [comment]
Can confirm the issue with the terminal on 1809.
cc @bpasero

**Comment by benc-uk** [comment]
Yep seeing the same here on Windows 10 1809
Happens with PowerShell, PowerShell Core (pwsh) and good old fashioned CMD

**Comment by ksiazkowicz** [comment]
Same here. In my case, terminal window just looks empty (scrolled to bottom) and text doesn't even appear until I press Enter.

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/57803

**Comment by sunil220** [comment]
Same here. In my case, terminal window just looks empty (scrolled to bottom) and text doesn't even appear until I press Enter......many times i couldn't launch the vs code after starting the windows.... please resolve that issue it's so irritating quickly do that ....

**Comment by sunil220** [comment]
![screenshot 7](https://user-images.githubusercontent.com/42406852/46941217-49f93a80-d088-11e8-80eb-e0e29853a688.png)

I m trying to update the vs code and its giving the error message what should i do ....Is there any solution for this issue
