### ISSUE TITLE
MarkDown preview links are too agressive

### ISSUE THREAD

**Issue by srl295** [Microsoft/vscode#59999]
Issue Type: <b>Bug</b>

The VS Code preview linkifier is too agressive. In the following markdown (generated by JSDoc)…

```md
| Param | Type | Description |
| --- | --- | --- |
| [opts] | <code>Object</code> | items to update |
| [opts.name] | <code>String</code> | name of the thing |
```

> | Param | Type | Description |
> | --- | --- | --- |
> | [opts] | <code>Object</code> | items to update |
> | [opts.name] | <code>String</code> | name of the thing |

… hovering over `opts.name` resulted in a link to `http://opts.name` !  Neither Github's preview, nor another processor (`marked` on NPM) linkify `[opts.name]`.  Same goes for `[opts.com]`.

Here the brackets are JSDoc for an optional parameter. 

VS Code version: Code - Insiders 1.28.0-insider (caaa5369cb4d22b7481e6ff97252cf92937709eb, 2018-09-28T05:12:22.044Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.48GB free)|
|Process Argv|gp-hpe-agent/|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
codecover|bra|1.1.0
vscode-eslint|dba|1.6.0
perl-syntax|jac|0.0.7
dotenv|mik|1.0.1
vscode-language-pack-es|MS-|1.28.2
vscode-kubernetes-tools|ms-|0.1.14
python|ms-|2018.8.0
cpptools|ms-|0.19.0
vscode-docker|Pet|0.3.1
platformio-ide|pla|1.3.1
java|red|0.32.0
vscode-yaml|red|0.0.17
vscode-java-debug|vsc|0.13.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.9.0
vscode-maven|vsc|0.11.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
This comes from markdown-it. That library automatically linkifies anything that looks like it could be a url, and `.name` is a valid top level domain.

If you believe this behavior incorrect, please file an issue against the linkifier: https://github.com/markdown-it/linkify-it/

You can also wrap the param names in backticks so that they are treated as code instead of normal text

Closing as upstream

**Comment by mjbvz** [comment]
Many markdown converters linkify http://example.com

Github doesn't linkify example.com but other converts do. We need a very convincing reason to change a default behavior that many users are now likely used to. This edge case is not it

**Comment by srl295** [comment]
http://example.com is fine, but this actually linkifies the following:

> first.name last.name 



anyway, at least it's configurable.… thanks

For the record, this is disableable with:

```json
    "markdown.preview.linkify": false
```
