### ISSUE TITLE
Can't paste anything

### ISSUE THREAD

**Issue by Alexandria65r** [Microsoft/vscode#59991]
Running the contributed command:'editor.action.clipboardPasteAction' failed.

**Comment by RMacfarlane** [comment]
Hi @Alexandria65r, can you please provide the following info?

- VSCode version
- What OS are you using?
- Do you have extensions installed, and are you able to reproduce the problem after running `Reload Window with Extensions Disabled`?
- What were you doing before you saw the error message? Do you always see this error when trying to paste?
