### ISSUE TITLE
Immediately-invoked function expressions are an error in the linter

### ISSUE THREAD

**Issue by thomas-jeepe** [Microsoft/vscode#600]
[In case you don't know what that thing is.](https://en.wikipedia.org/wiki/Immediately-invoked_function_expression)

This code `(function(){})()` is an error in the linter despite being perfectly valid, it says string literal expected. 

I also want to say, the intellisense on the editor is amazing and I can't wait for jsx support :)

**Comment by egamma** [comment]
I assume this is in a JS file. Do you have an linter jshint, eslint, jscs enabled? if yes you should file it against the corresponding linter.

**Comment by alexandrudima** [comment]
@thomas-jeepe ping:
* what linter have you configured?
* is this TypeScript or JavaScript?

**Comment by thomas-jeepe** [comment]
Sorry, didn't get the notifications. I haven't configured a linter at all, used the one out of the box, It was originally in a flowtype file where I got the error, I just tried it in js file and I got the error.

Looks like it is after an es6 import statement without semicolons

```javascript
// lints fine
var ONE = (function(a){return 1}())

// lints fine
(function(a){return 1})

// lints fine
import blah from 'blah';
(function(a){return 1})

// errors
import blah from 'blah'
(function(a){return 1})
```

**Comment by alexandrudima** [comment]
@thomas-jeepe Thank you for getting back to us. I can reproduce, I also get squigglies when the semicolon is missing.

**Comment by jrieken** [comment]
This is either an issue with the TypeScript compiler or specified as that. See TS playground for reference: http://www.typescriptlang.org/Playground#src=%2F%2F%20errors%0D%0Aimport%20blah%20from%20'blah'%0D%0A(function%20(a)%20%7B%20return%201%20%7D%20())%0D%0A

**Comment by jrieken** [comment]
This issue was moved to Microsoft/TypeScript#5931
