### ISSUE TITLE
Terminal should not bind Ctrl K - or any other Ctrl key

### ISSUE THREAD

**Issue by nitrologic** [Microsoft/vscode#60005]
The terminal in visual studio code should not be entitled to bind any control keys for it's own purposes. I may be mistaken but this seems such poor design it is a bug (Ctrl-K no longer works in bash nano sessions etc.)

**Comment by Tyriar** [comment]
ctrl+k is bound to clear the terminal on Windows only and it can be disabled by either unbinding the `workbench.action.terminal.clear` keybinding or by removing the clear command from `terminal.integrated.commandsToSkipShell`.

**Comment by nitrologic** [comment]
Is it possible to view / link the design doc? What other control keys can I expect to not be working now or in the future due to this "philosophy"?

**Comment by nitrologic** [comment]
Thank you for workaround and for taking another look. I think a good rule is that a terminal should respect at minimum all ASCII codes. I suppose the copy and paste overrides seem like a good idea but even there I think the native windows command line has it right and uses right click for paste so ctrl-v aka SYN is unmolested.

**Comment by Tyriar** [comment]
@nitrologic well yeah, it comes down to what we think users would expect to happen. ctrl+p is an example where it's skipped on Linux and Windows because it's such a prominent keybinding and it would suck if that didn't work. The good thing is that it's always possible to change the behavior in the setting (which will improve eventually when we action #19770).

**Comment by Tyriar** [comment]
Also copy/paste behavior is copied from the most popular terminals on each platform:

- Windows:
  - ctrl+c when there is a selection copies
  - ctrl+v pastes
  - right click to copy/paste based on selection
- Linux
  - ctrl+shift+c/v
  - middle click to paste PRIMARY clipboard
- macOS
  - cmd+c/v

And everything is configurable so you could bring the right click behavior to macOS if you wanted to for example, with the exception of the PRIMARY clipboard as it's OS-specific.
