### ISSUE TITLE
Undo last commit: keep staged files via `git reset --soft`

### ISSUE THREAD

**Issue by borekb** [Microsoft/vscode#60002]
The **Undo Last Commit** currently behaves like `git reset --mixed`: it undoes the commit _and_ discards anything that has been staged. If I had previously carefully added files or hunks to the stage, this work is lost.

I think it would be better to switch to the `git reset --soft` behavior:

- If adding to index was carefully done, this work would be preserved. 
- If the users wants the `--mixed` behavior, i.e., reset all the staged files, VSCode already has a convenient button for that. 

Because of the latter point, I'd propose VSCode changes the behavior, not introduce an option for mixed vs. soft behavior.

**Comment by steevsachs** [comment]
I’d like to work on this if it’s agreed to move ahead with the change. 

For the record, I agree with the proposed change, but I could also see this as a configuration to preserve behavior for users used to it.

**Comment by joaomoreno** [comment]
Fixed by https://github.com/Microsoft/vscode/pull/60104
