### ISSUE TITLE
editor.smoothScrollingSpeed : "1.0"

### ISSUE THREAD

**Issue by safield** [microsoft/vscode#60003]
I think the current setting...

editor.smoothScrolling

should be accompanied by....

editor.smoothScrollingSpeed

I would like to be able to slow it down a little bit.

**Comment by alexandrudima** [comment]
@safield Do you mean you would like for the animation to play slower? The animation duration is for now hard-coded at 125ms -- https://github.com/Microsoft/vscode/blob/e2027598992e56d7f6f6f26f804d53449ea1a2ee/src/vs/editor/common/viewLayout/viewLayout.ts#L16
