### ISSUE TITLE
Saving file and quickly closing app can result in the file getting emptied

### ISSUE THREAD

**Issue by Scott-Cooper** [Microsoft/vscode#60009]
I have lost a few files after saving and closing the application.  The file becomes zero bytes.

Steps to Reproduce:
- File must not be dirty
- Save file
- Close application.  Must follow save by less than a second
- Save onto slowish USB flash device
- Could not re-produce with faster internal SSD
- All extensions disabled

If file is dirty, the normal file save location might still become zero bytes, but vscode can restore the contents using magic journalling or something.

 Similar to [#50942](https://github.com/Microsoft/vscode/issues/50942) and [51016](https://github.com/Microsoft/vscode/issues/51016)

Test machine:
Windows 10
PNY 64GB USB 3.0 FD flash drive

Version: 1.27.2 (system setup)
Commit: f46c4c469d6e6d8c46f268d1553c5dc4b475840f
Date: 2018-09-12T16:17:45.060Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by bpasero** [comment]
@Scott-Cooper would you be willing to conduct a small experiment and setup your machine where you see this to run VSCode out of its sources so that I can give you some modifications to see if it helps? The instructions are here: https://github.com/Microsoft/vscode/wiki/How-to-Contribute

**Comment by bpasero** [comment]
@Scott-Cooper great, can you do this to try out if it helps:
* open fileService.ts line 580
* change the code `if (!exists || !isWindows) {` to `if (!exists || isWindows) {` (remove the `!` from isWindows)
* recompile typescript
* save on that USB drive

Does it reproduce?

**Comment by bpasero** [comment]
@Scott-Cooper ping
