### ISSUE TITLE
Powershell colors make it extremely difficult to read

### ISSUE THREAD

**Issue by jsschultz** [Microsoft/vscode#60001]
Issue Type: <b>Bug</b>

I have tried 2 different color themes in VS Code and both have color combinations (background and foreground) colors that make reading very difficult. For example, silver background with yellow text. This is what I get when using powershell in the Visual Studio Dark theme. Cmd prompt is fine, but Powershell is not.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.76GB (6.84GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.19.0
PowerShell|ms-|1.9.0
team|ms-|1.136.0
vim|vsc|0.16.6

</details>

**Comment by Tyriar** [comment]
I consider this a powershell issue, https://github.com/PowerShell/vscode-powershell would be a more appropriate place to report. FYI @tylerl0706

**Comment by tylerl0706** [comment]
No I'm pretty sure this is a [PSReadLine](https://github.com/lzybkr/PSReadLine) issue not being able to detect the color of the background and change accordingly. 

@jsschultz are you seeing this in the PowerShell console or the PowerShell Integrated Console?

Also, have you messed with the PSReadLine colors in your profile?

**Comment by jsschultz** [comment]
I am only seeing this in Powershell integrated console. I don't think I've touched PSReadLine (I've never heard of that before)

**Comment by tylerl0706** [comment]
Interesting. Can you send me a screenshot of what you're seeing?

Also, PSReadLine ships with PowerShell. So you're using it if you use PowerShell 😊.... Except in the PowerShell Integrated Console. It's not there yet for reasons.

You could check what's in your profile by opening the file that's in `$profile`

**Comment by jsschultz** [comment]
So this is what I see in another application that has an integrated terminal, where it actually uses a library from vscode:
![image](https://user-images.githubusercontent.com/10843297/46563267-51b12600-c8b5-11e8-8223-fa8b819498ba.png)

Note the yellow 'dir' with the beige background.

This is what I see in vscode:
![image](https://user-images.githubusercontent.com/10843297/46563307-8e7d1d00-c8b5-11e8-8a5e-c1b0d2ff88a3.png)

Note the gray 'dir' on black background.

**Comment by jsschultz** [comment]
For reference, this is what my cmd prompt looks like ([Solarized Light](https://github.com/neilpa/cmd-colors-solarized/blob/master/solarized-light.reg) colors applied):
![image](https://user-images.githubusercontent.com/10843297/46563434-50ccc400-c8b6-11e8-851f-b2e627d54cec.png)

**Comment by Tyriar** [comment]
@jsschultz oh I know what this is. You're seeing the issue where changing the theme in cmd.exe breaks the colors.

This is what the built in solarized light looks like for me:

![image](https://user-images.githubusercontent.com/2193314/46566371-fe010580-c8d1-11e8-92a7-f522e6a4b46e.png)

If you change cmd.exe's theme back to normal it should look like me. This is an issue with winpty https://github.com/Microsoft/vscode/issues/45693

**Comment by tylerl0706** [comment]
@jsschultz  so for context... 
![image](https://user-images.githubusercontent.com/2644648/46566211-17548280-c8cf-11e8-9e56-ffd90d536661.png) 

this means that you're using the the regular powershell terminal in vscode. The "integrated console" says "PowerShell Integrated Console" which is the one that ships in the PowerShell extension.

The regular powershell terminal in vscode is using the regular powershell.exe so that's why when you type, you get yellow text. That's PSReadLine trying to give you syntax highlighting. You can configure PSReadLine's colors here:
https://superuser.com/questions/676140/how-to-set-colors-in-psreadline-in-powershell



@Tyriar It's interesting that the text is dark grey... and on dark themes I'm guessing it's the default yellow. Was there work done to make powershell look better for different themes?

**Comment by Tyriar** [comment]
@tylerl0706 I'm guessing it was a miscommunication above:

> I am only seeing this in Powershell integrated console.

I think he means powershell in vscode is like this, but not the regular powershell/conhost window.

> The regular powershell terminal in vscode is using the regular powershell.exe so that's why when you type, you get yellow text.

It looks to me like a bug I saw a lot in the past where winpty messes up pulling t he colors if you change the background color of conhost.
