### ISSUE TITLE
Reorder integrated terminal panes via drag/drop

### ISSUE THREAD

**Issue by zachsa** [Microsoft/vscode#60017]
I really like the integrated terminal feature in VS Code, and how you can have multiple panes open. I use workspaces and I especially like how you can choose which directory to open the new terminal window in.

I like the familiarity of ordering my terminals consistently. Would it be possible to allow for reordering terminal windows via drag/drop? The current alternative is to manually `cd` in the terminal windows to order as I want them. (Which isn't so bad)

**Comment by Tyriar** [comment]
Closing in favor of https://github.com/Microsoft/vscode/issues/10546 for now, we've discussed the possibility of DND after tabs.
