### ISSUE TITLE
{ "moduleResolution": "node" } support incomplete; doesn't understand package.json files

### ISSUE THREAD

**Issue by mattflix** [Microsoft/vscode#6001]
- VSCode Version: 1.0.0
- OS Version: Mac OS 10.11.3

Steps to Reproduce:

1. Create the following project structure.
2. Open the root folder in VS Code.
3. Observe errors and poor Intellisense in ./src/entry.js.

It appears that the "Node module resolution" support in VS Code is incomplete, and only understands two variants:

- how to resolve a single [file as a module](https://nodejs.org/api/modules.html#modules_file_modules) (e.g., ./src/node_modules/foo.ts),
- how to resolve a [folder as a module](https://nodejs.org/api/modules.html#modules_folders_as_modules) that contains an "index" file (e.g., ./src/node_modules/bar/index.ts).

It doesn't understand the third variant:

- how to resolve a [folder as a module](https://nodejs.org/api/modules.html#modules_folders_as_modules) that contains a "package" file (e.g., ./src/node_modules/baz/package.json pointing to ./src/node_modules/baz/main.ts).

All three of these variants (in any mixture) are _vital_ to proper support for "Node module resolution" in modular Node project structures.

Also, _none_ of these variants work when the file extensions are .js instead of .ts (even when using a jsconfig.json file or allowJs=true).  This is terrible, and makes VS Code useless for navigating many existing Javascript projects.  The fact than any of the variants work for .ts files is great, but they should definitely work for .js files!

**./tsconfig.json**
```
{
    "compilerOptions": {
        "module": "es6",
        "moduleResolution": "node"
    }
}
```
**./src/entry.ts**
```
import foo from 'foo'; // OK
import bar from 'bar'; // OK
import baz from 'baz'; // [ts] Cannot find module 'baz'.

foo.foo(); // has Intellisense
bar.bar(); // has Intellisense
baz.baz(); // does not have Intellisense
```
**./src/node_modules/foo.ts**
```
export function foo(x: string) {}
```
**./src/node_modules/bar/index.ts**
```
export function bar(y: number) {}
```
**./src/node_modules/baz/package.json**
```
{
    "name": "baz",
    "version": "1.0.0",
    "main": "./main.ts"
}
```
**./src/node_modules/baz/main.ts**
```
export function baz(z: boolean) {}
```

**Comment by dbaeumer** [comment]
Moving to TS.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#8527
