### ISSUE TITLE
Markdown syntax highlighting breaks at collapsed JSX element

### ISSUE THREAD

**Issue by DanielSWolf** [Microsoft/vscode#60015]
Issue Type: <b>Bug</b>

Create a text document with the following content and save it with a .md extension:

    This is JSX:

    ```js
    const a = <div>test</div>;
    const b = <div />;
    const i = 42;
    function blubb(a, b) { return a + b; }
    ```

Then activate the Markdown preview. It looks like this:

![image](https://user-images.githubusercontent.com/5963162/46528186-70062a00-c893-11e8-8d65-922d134b6563.png)

Note how the embedded JavaScript and JSX are highlighted correctly *until the collapsed element `<div />`*. At this position, the highlighter seems to break. All following JavaScript code within the code block is not highlighted, but black.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:57:45.963Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (3.05GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-pdf|yza|1.2.0

</details>

**Comment by mjbvz** [comment]
We use highlight-js to power our markdown preview's syntax highlighting. This sounds like this upstream bug: https://github.com/highlightjs/highlight.js/issues/931
