### ISSUE TITLE
TreeDataProvider#getChildren is called despite being collapsed

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#60014]
* implement a tree data provider that logs when getChildren is being called (see below)
* remove the tree from the explorer
* reload
* add the tree back (right click explorer title, select tree)
* 🐛 the `getChildren`-function is being called even though the tree isn't showing (only its header)

```ts
    vscode.window.registerTreeDataProvider('fooTree', new class implements vscode.TreeDataProvider<string> {
        onDidChangeTreeData?: vscode.Event<string>;
        getTreeItem(element: string): vscode.TreeItem | Thenable<vscode.TreeItem> {
            return {
                label: element,
                resourceUri: vscode.window.activeTextEditor && vscode.window.activeTextEditor.document.uri
            }
        }
        getChildren(element?: string): vscode.ProviderResult<string[]> {
            console.log('HERE', element);
            if (!element) {
                return ['foo', 'bar', 'bazz', 'far', 'boo'];
            }
        }
    })
```

```json
"views": {
			"explorer": [
				{
					"id": "fooTree",
					"name": "Foo Tree"
				}
			]
		},
```

**Comment by sandy081** [comment]
@jrieken I cannot reproduce it. Is there a step I am missing?

![kapture 2018-10-31 at 16 21 32](https://user-images.githubusercontent.com/10746682/47798649-1aedf480-dd29-11e8-8d27-d0f0477b486f.gif)

**Comment by jrieken** [comment]
This is what I do:[Screen Recording 2018-11-02 at 14.38.27.mov.zip](https://github.com/Microsoft/vscode/files/2542611/Screen.Recording.2018-11-02.at.14.38.27.mov.zip)

**Comment by sandy081** [comment]
Interesting. I used the same code you provided in the description. Let's catch up directly.
