### ISSUE TITLE
setExpanded isn't called

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#60011]
* implement a ViewPanel
* implement `setExpanded`
* expand the panel, setExpanded is called
* refresh workbench
* 🐛 setExpanded isn't called

**Comment by joaomoreno** [comment]
I assume this is about implementing an `IView` and extending from `ViewletPanel`.

**Comment by jrieken** [comment]
And then I would have to call `setExpanded` myself? Is that what we call nice API?

**Comment by joaomoreno** [comment]
It sounds like you want to change some state (say, from A to B) when your view is expanded. That state should already be in B, given that your view was constructed with the knowledge that it is already expanded. It's not about API niceness. It's about performance. Why would the widget call an extra method, having given that information already previously?

**Comment by jrieken** [comment]
> Why would the outside caller call an extra method, having given that information already in the ctor?

I am saying it's confusing AF. Why do I get a `layout` or `setVisible` call then? Now I have two ways how to deal with expansion, worst when I am in the constructor `renderBody` hasn't been called yet so that I need to cached that information. 

> Think about it as an onDidChangeExpansion event. Why fire it, when it hasn't actually changed from the initial value?

That's the wrong comparison IMO. Everything in the panel & viewlet world works by inheritance except for this.

**Comment by joaomoreno** [comment]
So, what do you propose?

**Comment by bpasero** [comment]
@jrieken fyi I adopted the new `onDidChangeBodyVisible` event in outline panel which I think addresses this. The event is fired:
* right on startup if the view is expanded and visible
* when expand/collapse state changes
* when visibility changes

Refs: https://github.com/Microsoft/vscode/commit/01659db1a4351a09bcb13ce57a55077ae04bf3d0#diff-9e98764ac7ade37e9da21c39768fc818R376
