### ISSUE TITLE
Old Issue

### ISSUE THREAD

**Issue by gordingin** [Microsoft/vscode#60028]
Issue Type: <b>Bug</b>

Not sure why, bug I get this old error again.

[ts] Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.

Still can compile - just and IDE issue.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz (8 x 2794)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|31.91GB (22.82GB free)|
|Process Argv|C:\Users\Ralph.Krausse\AppData\Local\Programs\Microsoft VS Code\Code.exe .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|1.6.1
debugger-for-chrome|msj|4.10.2
autoimport|ste|1.5.3

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Run `typescsript: go to project configuration`. Does this open up the tsconfig that enables `experimentalDecorators`?

**Comment by mjbvz** [comment]
Run that command in the command palette with the ts or js file open
