### ISSUE TITLE
Toggle Word Wrap still broken

### ISSUE THREAD

**Issue by tigoe** [Microsoft/vscode#60021]
- VSCode Version:  1.27.2 
- OS Version: MacOS 10.12.6 (16G1510)

Steps to Reproduce:

1. open a document with lines longer than the word wrap column setting
2. turn word wrapping on

This has no effect on the document's appearance

3. set word wrapping to wordWrapColumn

Still no effect

4. set word wrapping to bounded

Still no effect

I know this issue has been reported many times, and they have all been closed. Nevertheless, word wrapping still doesn't work. And none of the explanations that have been given make a difference. I have tried them all. I've tried it with saved and unsaved files. I've tried with different file extensions. What's the secret to making it work?

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
@tigoe Most of the times people have configured something and then have forgotten about it, like e.g. in a folder setting.

Can you please do the following for me:
* open VS Code
* File > New Window to get a brand new window (no folder settings)
* File > New File to get a brand new file (no language specific settings)
* paste a long text like this one: `This is a long text. This is a long text. This is a long text. This is a long text. This is a long text. This is a long text. This is a long text. This is a long text. This is a long text. This is a long text. This is a long text. This is a long text. This is a long text. This is a long text. This is a long text. This is a long text. This is a long text. This is a long text. This is a long text. This is a long text.`
* press <kbd>Alt</kbd>+<kbd>Z</kbd>
* is word wrapping working in this case?

![kapture 2018-10-08 at 12 17 57](https://user-images.githubusercontent.com/5047891/46603716-3c760a80-caf4-11e8-8110-af1e00f40fc5.gif)


If yes, then we need to find out what exactly is keeping it from working in your initial case? Do you have extensions installed? Did you try running with all extensions disabled? Did you try reviewing your folder settings? Did you try reviewing your user settings?

**Comment by tigoe** [comment]
I followed those steps to the letter, and word wrapping still does not work.

I also launched vscode with all extensions off (got that from one of the other issue reports) and still it does not work. 

In the user settings, word wrap is on, columns 80. 

I found the culprit though: I have the screen reader optimization on, in order to test what I'm doing for visually impaired users, and that disables word wrap. So I guess there's no way to have both word wrap and accessible mode? I can see why you'd think they don't need to coexist, but I seem to have found a use case where it'd be nice if they did.

**Comment by alexandrudima** [comment]
> I can see why you'd think they don't need to coexist, but I seem to have found a use case where it'd be nice if they did.

It is not a choice. We have no technical ability to express wrapping points to the Screen Readers, so they would read a newline whenever we had a wrapping point. This would lead to a lot of confusion when operating the editor using a Screen Reader.

You can configure `"editor.accessibilitySupport": "off"` and that will prevent VS Code from applying this workaround (and others, like disabling folding for example).
