### ISSUE TITLE
Allow disabling "Replace Preview"

### ISSUE THREAD

**Issue by dsanz006** [Microsoft/vscode#60027]
I think it should be possible to disable "Replace Preview" in the settings. Currently, whenever I want to replace a word, the "Replace Preview" opens for every file, because I have file preview disabled.

**Comment by roblourens** [comment]
Are you talking about the diff editor that opens when you click a result? What do you expect to see in that case?

**Comment by dsanz006** [comment]
Yes that's what I'm talking about. I would like to see just the file without a diff. Then when I click on replacing the text it would just replace it directly.

**Comment by roblourens** [comment]
This seems reasonable and I would take a PR that adds a setting to disable the replace preview. FYI @sandy081 

Starting point: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/search/browser/searchView.ts#L1405 and https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/search/browser/searchActions.ts#L581

**Comment by ToothlessGear** [comment]
I'd like to take a look at this.
