### ISSUE TITLE
Problem of "go to defination" using python environment.

### ISSUE THREAD

**Issue by benbenji** [Microsoft/vscode#60020]
Hello,Today I wrote python code with module "tensorflow", I found the hint which is given by vscode is different form that "help" function in python shows,the hint is "def truncated_normal(shape, dtype, seed=0, seed2=0, name=None) " but the help of python shows the doc is "truncated_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)" ,after I look over the source code of tensorflow ,I found the tensorflow have two definition of this function ,it use one @tf_export("truncated_normal")  which is used to specify one of the functions. Vscode found the wrong definition because of that.Is it a bug or vscode could not work for it at under these circumstances? I know it maybe very difficult for vscode without import the whole module.But could you tell me is it possible for vscode python navigation become more intelligent to deal with this situation? When I tried this in pycharm .it can found the correct definition . but I prefer vscode very much! Thank you.

**Comment by mjbvz** [comment]
Please file this issue against the python extension
