### ISSUE TITLE
Debugger breaks the connection of aerospike DB

### ISSUE THREAD

**Issue by NitinHsharma** [Microsoft/vscode#60026]
- VSCode Version:  1.27.2
- OS Version: MAC 10.13.6
- aerospike version: 3.13.0.1

Steps to Reproduce:

1. write nodejs application which creates a single connection of aerospike on the app load. 
2. write CRUD operation of aerospike and try to run using the debugger.

It's breaking if we run the CRUD operation in debugging mode, but working the same while running without debugging mode.

What it looks like when we use the debugger, heartbeat of DB connection got lost (might be debugger take CPU lock cycle or it takes main thread)

Maybe using separate thread or co-worker for debugger can solve the above issue. 

NOTE: same case with another DB (mongo, redis ) working fine with and without a debugger. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
TThis souns like a nodejs bug or aerospike. Please file ti there and not in vscode. Thanks
