### ISSUE TITLE
Debugger attached. Waiting for the debugger to disconnect

### ISSUE THREAD

**Issue by decoder318** [Microsoft/vscode#60022]
Issue Type: <b>Bug</b>

Write any simple nodeJS program, and put a debugger statement or a breakpoint anywhere, and debug -> click the Launch Program button..

This worked for some time, and then it just doesn't work. Restarting machine, reinstalling VS Code didnt help

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (3.66GB free)|
|Process Argv|C:\Users\Renu\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by decoder318** [comment]
it's not really covered anywhere. I will switch to Sublime Text until this is addressed and fixed.

**Comment by PabloVent** [comment]
Very frustrating!!!!  I'm still getting this issue even after updating to version 1.30.1.  All vscodebot robot does is refer you to previously unresolved and closed issues.

**Comment by isidorn** [comment]
I can not reproduce.
Please file with exact reproducable steps please. For example post a minimal GitHub sample repo for which you can reproduce this

**Comment by PabloVent** [comment]
Thanks I'll figured it out. I had to manually add code to a launch.json
file; what a shame, I'd've thought VS would do it for you automatically.

**Comment by isidorn** [comment]
Will reopen this issue once somebody provides exact steps
