### ISSUE TITLE
Seconds of unuse.

### ISSUE THREAD

**Issue by ianfhunter** [Microsoft/vscode#60033]
Issue Type: <b>Performance Issue</b>

I have many tabs and windows open, but for some reason the active window causes a big drop in performance for a few seconds and i can't type in the editor. It says 22 % cpu on the window in the status commandline, but my cpu% in htop is at 100. Extension host is at 0% cpu

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:11:15.873Z)
OS version: Linux x64 4.13.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|31.34GB (5.50GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
makeRunner|ale|0.1.1
code-gnu-global|aus|0.2.2
prototxt|dmi|0.0.6
flatbuffers|gab|0.1.0
plantuml|jeb|2.9.2
plantuml|jke|1.8.1
rainbow-csv|mec|0.6.0
python|ms-|2018.8.0
cpptools|ms-|0.19.0
partial-diff|ryu|1.4.0
code-spell-checker|str|1.6.10
rst-vscode|tht|2.0.0
gitblame|wad|2.4.4
debug|web|0.22.0
markdown-all-in-one|yzh|1.6.0
swig-tpl|zha|0.0.6

(1 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
Could you follow https://github.com/Microsoft/vscode/wiki/Performance-Issues to provide more information when you run into this issue again?
