### ISSUE TITLE
Makefile: incorrect syntax handling hashtag (#) symbols

### ISSUE THREAD

**Issue by Artalus** [Microsoft/vscode#60030]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/10381253/46543321-35b77f80-c8c9-11e8-8398-984f7f3a063d.png)

As the comment says, '#' symbols do not mark comments when put in quotes.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:11:15.873Z)
OS version: Linux x64 4.14.69-1-MANJARO

**Comment by aeschli** [comment]
moved to https://github.com/fadeevab/make.tmbundle/issues/1
