### ISSUE TITLE
Window is not responding at random

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#6003]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows 10

Not sure of the repro steps since I was not doing anything similar the few times this has happened. I do have this error in the Developer Tools console:

![loggingwarning](https://cloud.githubusercontent.com/assets/12900364/14932181/58595a2c-0e27-11e6-9ae1-6836bee27378.PNG)

I have C#, ESLint, jshint, and yo extensions installed. The window is responsive before and after clicking wait.

**Comment by bpasero** [comment]
#1000
