### ISSUE TITLE
Find widget has overlapping elements at small widths

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#60037]
Issue Type: <b>Bug</b>

1. In an editor
1. Open the find widget
1. Reduce the editor size so that it is quite narrow

**Bug**
Find widget has overlapping elements:

<img width="442" alt="screen shot 2018-10-02 at 1 48 52 pm" src="https://user-images.githubusercontent.com/12821956/46549163-fc115500-c885-11e8-865b-e31a0b64fd0b.png">

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-04T16:40:40.180Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (1.00GB free)|
|Process Argv|-psn_0_17563839|
|Screen Reader|no|
|VM|25%|

</details>

**Comment by mjbvz** [comment]
I still see this in 97ad72a02c351d6cde0fd32b41d9700a43e5964a

![screen shot 2018-10-31 at 6 00 20 pm](https://user-images.githubusercontent.com/12821956/47826748-da957300-dd36-11e8-870e-1b8ec87558a8.png)

**Comment by ramya-rao-a** [comment]
Verified from source
