### ISSUE TITLE
Computer crashing when using visual studio code.

### ISSUE THREAD

**Issue by ChamuMutezva** [Microsoft/vscode#60036]
I am not sure what is causing my laptop to crash everytime i open visual studio code. I cannot  stay coding for even 3 minutes before the computer becomes unresponsive.  This problem started recently after the new Windows 10 upgrade.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.93GB (0.96GB free)|
|Process Argv|C:\Users\Precious Mutezva\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
tinypng|and|0.2.0
vscode-refresh-html|baj|0.0.2
vscode-markdownlint|Dav|0.20.0
jshint|dba|0.10.20
vscode-eslint|dba|1.6.0
vscode-gitbuild|grz|1.0.1
imagesprites|gur|1.0.0
vscode-jasmine-test-adapter|hbe|1.1.0
vscode-test-explorer|hbe|2.0.8
beautify|Hoo|1.4.4
rcs|iap|0.0.3
hg|mrc|1.2.3
python|ms-|2018.8.0
atom-keybindings|ms-|3.0.4
PowerShell|ms-|1.9.0
sublime-keybindings|ms-|4.0.0
team|ms-|1.136.0
debugger-for-chrome|msj|4.10.2
vscode-gitignore-generator|pio|1.0.1
view-in-browser|qin|0.0.5
java|red|0.31.0
LiveServer|rit|5.1.1
view-in-default-application|see|3.3.0
perforce|sle|3.1.0
source-depot|sup|0.0.2
vscode-java-debug|vsc|0.13.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.9.0
vscode-maven|vsc|0.11.0

</details>

**Comment by ChamuMutezva** [comment]
I have to take out the battery and reboot again to use the computer again.
Non of the keys will be responding.

**Comment by InnovativeCoder** [comment]
@ChamuMutezva Is your problem resolved?

**Comment by ChamuMutezva** [comment]
Yes the problem has been eliminated. I reinstalled visual studio code and has been working fine.

**Comment by ChamuMutezva** [comment]
The freezing problem is back again and i still haven't figured out why it is associated with Visual Studio Code.  If i use Sublime Text it doesn't happen. Interestingly this has started again after a Windows 10 update(I wish there are ways to **STOP** this  automatic Windows 10 update) The again the computer is rendered useless until i reboot it again.

**Comment by sbatten** [comment]
@ChamuMutezva have you seen an improvement here @ChamuMutezva

**Comment by ChamuMutezva** [comment]
@sbatten , i am now using **Visual Studio Code Insiders** to solve the problem. I could not find a fix to the normal VSC.

**Comment by sbatten** [comment]
@ChamuMutezva glad its fixed in insiders and hopefully that means it will be fixed for you when stable is updated this milestone. If you still see the issue next month in stable after updating, I suspect an issue with local storage or cached data and you can re-open the issue. Thanks for the details.

**Comment by ChamuMutezva** [comment]
@sbatten, please can you explain further on  the local storage/cached data issue as you suggested that it might be the problem.
