### ISSUE TITLE
View full size images and allow image zoom

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#6004]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Open a large image

By default the image is scaled down to fit the screen with no options to zoom or to see the full resolution image. It would be a nice feature and is supported in other editors.

**Comment by bpasero** [comment]
For July you can click on an image that does not fit workbench size to make it fully expanded in size.
