### ISSUE TITLE
Add multiple task.json configuration files

### ISSUE THREAD

**Issue by deriegle** [microsoft/vscode#60043]
Is there a current way to have multiple `launch.json` or `tasks.json` files?

It would be really nice to be able to have a user's custom launch.json/tasks.json for workspaces so that we could have our `.vscode` folder under version control so everyone has the same copy of the standard tasks/debug configurations while working on the project, but they could also have their own tasks/debug configurations without committing them or having unstaged changes floating around.

**Comment by dbaeumer** [comment]
No, this is currently not possible.

**Comment by isidorn** [comment]
For launch.json you can have your own using workspace or user launch configuraiont 
More details - use a multi root setup but just open your single folder https://code.visualstudio.com/docs/editor/multi-root-workspaces#_debugging
https://code.visualstudio.com/docs/editor/debugging#_global-launch-configuration

Leaving this open as a feature request for tasks

**Comment by s1eepwalker** [comment]
Need like sublime text 3 'build_systems'. tasks.json move to workspace config

**Comment by N7K4** [comment]
I would _love_ to combine multiple tasks.json (e.g. npm, gem, jekyll) in one big file. So I would avoid copy & paste issues. Or I can link / download my tasks from platforms like github and just reuse them.

**Idea A:** Just use all files with name `*-tasks.json` (or similar) as tasks.json from `.vscode` folder.

**Idea B:** Make the additional tasks.json files available as a embedded file.

```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "My NPM Tasks (with subfolder)",
            "fromFile": "./myTasks/npm/tasks.json"
        },
        {
            "label": "My Jekyll Tasks",
            "fromFile": "./myTasks/Jekylltasks.json"
        }
  ]
}
```

**Comment by alexr00** [comment]
Global tasks.json is supported now in Insiders! You can create a tasks.json next to your global settings.json and put `shell` and `process` type tasks in it. 
Note: you have to manually create the tasks.json next to your you user settings.json. I haven't added a command to create it for you yet.

**Comment by vas1468** [comment]
any update regarding this? @N7K4 idea is what I was looking as well.

> I would _love_ to combine multiple tasks.json (e.g. npm, gem, jekyll) in one big file. So I would avoid copy & paste issues. Or I can link / download my tasks from platforms like github and just reuse them.
> 
> **Idea A:** Just use all files with name `*-tasks.json` (or similar) as tasks.json from `.vscode` folder.
> 
> **Idea B:** Make the additional tasks.json files available as a embedded file.
> 
> ```json
> {
>     "version": "2.0.0",
>     "tasks": [
>         {
>             "label": "My NPM Tasks (with subfolder)",
>             "fromFile": "./myTasks/npm/tasks.json"
>         },
>         {
>             "label": "My Jekyll Tasks",
>             "fromFile": "./myTasks/Jekylltasks.json"
>         }
>   ]
> }
> ```

**Comment by dotarj** [comment]
@N7K4 idea is also what I was looking for.
 
> I would _love_ to combine multiple tasks.json (e.g. npm, gem, jekyll) in one big file. So I would avoid copy & paste issues. Or I can link / download my tasks from platforms like github and just reuse them.
> 
> **Idea A:** Just use all files with name `*-tasks.json` (or similar) as tasks.json from `.vscode` folder.
> 
> **Idea B:** Make the additional tasks.json files available as a embedded file.
> 
> ```json
> {
>     "version": "2.0.0",
>     "tasks": [
>         {
>             "label": "My NPM Tasks (with subfolder)",
>             "fromFile": "./myTasks/npm/tasks.json"
>         },
>         {
>             "label": "My Jekyll Tasks",
>             "fromFile": "./myTasks/Jekylltasks.json"
>         }
>   ]
> }
> ```

**Comment by vortechs2000** [comment]
Having a way to include other `launch.json` files would be invaluable.  Currently if the `.vscode/launch.json` is checked into source code, that can cause all kinds of problems as random changes get checked in.  But if we could have a common set of debug launch settings in a different folder checked into source control, and *include/concat* that with the settings in `.vscode/launch.json`, we could share common debug tasks.

**Comment by zowers** [comment]
tasks.json.d directory as it is done in linux for configuration would be useful

**Comment by gtherond** [comment]
Is there any news around this feature? It's marked as closed and the parent request suggesting to use an include block too because of "Duplicate" but those aren't duplicate, it's hard to tell if many splitted tasks file is now supported within vscode.

@zowers What about: tasks.d rather? that would shorten the naming and allow for a markup language change in futur if ever happening.

**Comment by Veenkar** [comment]
I found a way to have more than one tasks.json files in a workspace.
Simply crate a folder inside your repository, you can name it for example vscode_common.
Inside this folder crate a .vscode directory with tasks.json in it.
Add the vscode_common folder to your workspace (as another folder, it doesn't matter that it already appears in root directory).
This way tasks.json from vscode_common directory will be included in your workspace and launchable from your command palette.

**Comment by mxfh** [comment]
@Veenkar 
great feature, should be noted that some paths might need to be adjusted for the configurations to work accordingly as before for file resolution in debug sessions.

like
`"webRoot": "${workspaceFolder}"`
in a sampleapp folder in a multi-root workspace now becomes
`"webRoot": "${workspaceFolder:sampleapp}"`

https://code.visualstudio.com/docs/editor/multi-root-workspaces#_workspace-launch-configurations

**Comment by georglauterbach** [comment]
I'd also like to see the option to include other tasks and debug confihgurations - that would indeed be extremely valuable for sharing common definitions.
