### ISSUE TITLE
Running scripts with right click not giving feedback when it ends.

### ISSUE THREAD

**Issue by jesusbibieca** [Microsoft/vscode#60047]
- VSCode Version: 1.27.2
- OS Version: MacOS Sierra 10.12.6

Steps to Reproduce:

1. While on a project, go to `package.json` 
2. Go to the `scripts` section and right click any script, then click on `Run Script`
3. After the script runs and finished you need to manually hit `Enter` to exit out that terminal

I wish it exited out after it ended or rather notify me that it ended so I can hit `Enter`

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by morgannewman** [comment]
I'd love to give this issue a go! Is help wanted?

**Comment by RMacfarlane** [comment]
@jesusbibieca What type of script are you running? Does this launch a different terminal, or run within the integrated terminal in VSCode?

This sounds like behavior being determined by the script, not VSCode

**Comment by jesusbibieca** [comment]
It's happening on all scripts I try... I work with node mainly, so what I mean is if I go to `Package.json` and I look for the script named `test` instead of goind to VScode console and typing `npm run test`, you right click the script name on the `package.json` and it shows run script as the first option. I click that and in the same VScode terminal it will run the command/script, however when it is done it does not return to the regular terminal unless I hit enter.
@RMacfarlane does it make it clearer now? BTW if I run `npm run test` in the vscode terminal it runs and finished (allow me to type another command) just when I run it the other way it does not.


![screenshot from 2018-10-07 22-45-10](https://user-images.githubusercontent.com/29680762/46590680-23814100-ca83-11e8-8a13-82ed7b750a4a.png)

Here it will start
![screenshot from 2018-10-07 22-49-13](https://user-images.githubusercontent.com/29680762/46590718-6e9b5400-ca83-11e8-97f7-ad963b4fbe4e.png)


Here it ends, but it just stays there until I hit enter:

![screenshot from 2018-10-07 22-50-29](https://user-images.githubusercontent.com/29680762/46590727-81158d80-ca83-11e8-8a8a-592705e08b1e.png)

**Comment by weinand** [comment]
@egamma I'm not sure whether this is tasks or npm?

**Comment by egamma** [comment]
The expected behavior is that the terminal shows an info line at the bottom 'Terminal will be reused...' when a task has finished:
![image](https://user-images.githubusercontent.com/172399/46669347-6ea86a80-cbcf-11e8-98ed-7a82fd85b847.png)

When running the npm from the context menu then the info line is not shown and it appears the terminal hangs
![image](https://user-images.githubusercontent.com/172399/46669412-a44d5380-cbcf-11e8-96a6-8e43069e1161.png)

**Comment by egamma** [comment]
// CC @Tyriar in both 1.27 and 1.28 the behaviour is as described above and the info line is missing. In the latest insiders it looks like there is an endless loop.

**Comment by Tyriar** [comment]
Here's the underlying cause for both issues @dbaeumer 

https://github.com/Microsoft/vscode/blob/a7db2fbb3c55cca8b3d26b832f4fe44ff62caf7b/src/vs/workbench/parts/tasks/electron-browser/terminalTaskSystem.ts#L533

**Comment by jesusbibieca** [comment]
I'm glad I was able to help you identify this to get it fixed. Thank you for the good work that you guys are doing!

**Comment by dbaeumer** [comment]
@Tyriar hmm, this is actually on purpose and I even think you advised this. The problem is that I don't want to exit the terminal immediately but don't want a message either. Since an empty string falsifies I use zero width blank which doesn't falsifies but doesn't print something either and is not selectable.

**Comment by dbaeumer** [comment]
The real issue with not showing the message was that if no presentation options were provided when executing a task the show reuse message defaulted to false.

**Comment by dbaeumer** [comment]
Fixed
