### ISSUE TITLE
Add Visual studio collapse feature (outlining)

### ISSUE THREAD

**Issue by pixieaka** [microsoft/vscode#60054]
Add Visual studio collapse feature (outlining)

Toggle Outlining Expansion
Toggle All Outlining
Collapse to Definitions

https://docs.microsoft.com/en-us/visualstudio/ide/outlining?view=vs-2017

**Comment by RMacfarlane** [comment]
Hey @pixieaka, this feature already exists in VSCode. Check out https://code.visualstudio.com/docs/editor/codebasics#_folding

If you think there's something missing from this feature, please describe it in more detail.

**Comment by pixieaka** [comment]
@RMacfarlane  I want [ Ctrl+K Ctrl+2 ] without comments, like
1- folds all regions of level 2 with [ Ctrl+K Ctrl+2 ]
2- Expand All Block Comments  [ reverse Ctrl+K Ctrl+/ ]

& Can add reverse Fold All Block Comments  [ Ctrl+K Ctrl+/ ]

**Comment by VDerGoW** [comment]
Very need feature **Collapse to Definitions**, like `Ctrl M, Ctrl O` in Visual Studio.

**Comment by JohnLeicht** [comment]
It may help to know HOW collapse/expand is being used...
I have a lengthy help.html file. It would be useful when adding topics to be able to collapse all to level n (2 -  for example) to see/add/rename topics/subtopics etc. I would use this extensively when coding, as well.

**Comment by aeschli** [comment]
`Toggle Outlining Expansion` got added in September
Collapse to Definitions is '#33449'

Toggle All Outlining is not planed.
