### ISSUE TITLE
Copy in File Explorer does not paste into Code Explorer 

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#6005]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Right click > copy or Ctrl+C a file in File Explorer
2. Go to Code, Right click > Paste or Ctrl+V in Explorer

Actual:
Nothing happens unless you already copied a file in Code, then it will paste that instead.

I read some other issues similar to this, but I'm wondering why dragging files from File Explorer into Code works and this doesn't. I'm guessing an Electron issue?

**Comment by f111fei** [comment]
Electron did not seem to provide an api to get the file data in clipBoard.

**Comment by bpasero** [comment]
Yeah, somewhere I filed this already some time ago, please dig it up.
