### ISSUE TITLE
diff decorations always showing inlined

### ISSUE THREAD

**Issue by doomstrike** [Microsoft/vscode#60056]
Issue Type: <b>Question</b>

New to vscode so forgive a noob.

I've been tinkering with the default settings regarding diffs in the editor and no matter which option I've tried to change it seems that the line diff highlight is always on (ie showing red for deleted lines or green for added lines). I find this noisy and would prefer to just have the indications in the gutter; preferably just a color coded +/- in the gutter is my ideal.

 Is there an option to change this or is this stock vscode behaviour that can't be changed?

Note I've turned off all my extensions while trying to figure it out.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:11:15.873Z)
OS version: Linux x64 4.15.0-36-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (4 x 2712)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|1, 1, 1|
|Memory (System)|10.77GB (4.89GB free)|
|Process Argv|/usr/share/code/code .|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|9.0.1
vscode-django|bat|0.17.0
vscode-new-file|dku|4.0.2
jupyter|don|1.1.4
python-extension-pack|don|1.4.0
xml|Dot|2.3.2
gitlens|eam|8.5.6
git-project-manager|fel|1.7.1
MagicPython|mag|1.1.0
python|ms-|2018.9.0
atom-keybindings|ms-|3.0.4
java|red|0.32.0
vscode-icons|rob|7.27.0
tmlanguage|Tog|0.9.0
vscodeintellicode|Vis|1.0.4
vscode-java-debug|vsc|0.13.0
vscode-java-test|vsc|0.9.0
vscode-maven|vsc|0.11.0
jinja|who|0.0.8
copy-with-line-numbers|yas|0.0.4

(1 theme extensions excluded)

</details>

**Comment by RMacfarlane** [comment]
There's an `scm.diffDecorations` setting that can be used to set the behavior in editors. There's no setting to change the line highlight in diff editors.

Issues in this repository are meant to track bugs and feature requests, please ask questions at https://stackoverflow.com/questions/tagged/visual-studio-code. Thanks!
