### ISSUE TITLE
Allow extensions to provide contributed/detected launch configurations

### ISSUE THREAD

**Issue by g-arjones** [microsoft/vscode#60057]
This would allow the user to debug projects without the need to create launch.json files. Akin detected/contributed tasks, the provided launch configurations would show up in the debug viewlet along with other launch configurations that the user might define in a launch.json. With that, he/she would be able to seamlessly switch between extension provided launch configurations and user defined ones.

Does that make sense? @jrieken @isidorn

**Comment by isidorn** [comment]
We already have quite some mechanisms for providing launch configurations. Please check out our docs https://code.visualstudio.com/docs/extensions/example-debuggers
What you seem to be wanting is a debug adapter which resolves a debug configuration provider fully such that the user does not have to add anything. That in theory is possible with the resolveDebugConfiguration api.

I understand that you want to resolve a confiugration which does not exist which is also possible but only if there is no launch.json. If there is a launch.json than this is not possible.
Leaving open as a feature request.

**Comment by g-arjones** [comment]
> which is also possible but only if there is no launch.json. If there is a launch.json than this is not possible

When working in multi-root workspaces, a launch.json in one folder prevents you from debugging any other folder without a launch.json.

Also, I would like to see debug configurations provided by an extension showing up in the debug viewlet combobox (along with the ones from launch.json files). Kinda lilke how task configuration providers work..
