### ISSUE TITLE
"Reload to deactivate" after uninstall message is confusing

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#60053]
Issue Type: <b>Bug</b>

When i click "uninstall" of an extension in the extension's editor, the button changes to "Reload to Deactivate". 

![image](https://user-images.githubusercontent.com/1487073/46563061-3f82b800-c8b4-11e8-90c6-e5fc2a9ec106.png)

I understand that it is the inverse of "Reload to Activate" after clicking on "Install", which makes sense.  But, in the case of uninstall, we are not "deactivating" the extension on reload, we are removing it.  "Deactivate" sounds like the extension will not be removed, but instead just disabled.

I suggest something like this (there is plenty of room):

![image](https://user-images.githubusercontent.com/1487073/46563141-b91aa600-c8b4-11e8-8dc1-1edf48ccd4a4.png)

or this is even more accurate I believe.

![image](https://user-images.githubusercontent.com/1487073/46563188-f41cd980-c8b4-11e8-9017-04c9c16796f7.png)

**Comment by ramya-rao-a** [comment]
I am leaning towards `Reload to finish uninstall` instead of `Reload to remove the extension`.

User has already clicked on `Uninstall` to "remove the extension"...

**Comment by sandy081** [comment]
I think the extension is already is installed/uninstalled and `Reload to finish` gives an expression that it is still not installed / uninstalled. Actually we need to Reload to load or unload the extension in the window. It would be nice if the wordings are along these lines.

**Comment by sandy081** [comment]
Ok.

**Comment by sandy081** [comment]
@ramya-rao-a Good point. You can always check if an extension is disabled or not right? A newly installed extension is enabled but not loaded.

I was also thinking about enable/disable scenario and what would be the message in this case?

**Comment by ramya-rao-a** [comment]
> Good point. You can always check if an extension is disabled or not right? A newly installed extension is enabled but not loaded.

@sandy081 Turns out, by the time extensionWorkbenchService fires the `onChange` event when a disabled extension is enabled, the enablementService marks it as "enabled". So the below `if` condition (which checks for `!isDisabled`) evaluates to true for both "enabling" and "installing" an extension.

https://github.com/Microsoft/vscode/blob/125260e63f179a87cfa1f8228cff9d6afc435c99/src/vs/workbench/parts/extensions/electron-browser/extensionsActions.ts#L1080-L1084

> I was also thinking about enable/disable scenario and what would be the message in this case?

I was thinking of the below:
- Reload to complete installing the extension.
- Reload to complete uninstalling the extension.
- Reload to complete updating the extension.
- Reload to complete enabling the extension.
- Reload to complete disabling the extension.

**Comment by sandy081** [comment]
May be you need to compute both `disabled` and `enabled` and an installed extension has `false` for both

**Comment by ramya-rao-a** [comment]
> installed extension has false for both

Wow, I didnt know that.

**Comment by ramya-rao-a** [comment]
@NavyAdmiral The PR for the changes is already linked to this issue.

**Comment by sandy081** [comment]
@NavyAdmiral sqlite migrations will not help us completely in avoiding reload. It just removes one obstacle away and there is more needed for that.

**Comment by sandy081** [comment]
@ramya-rao-a Changes are good, but not sure if long labels look good in the UI.

![image](https://user-images.githubusercontent.com/10746682/47415089-e69b9680-d772-11e8-9820-0766d83855a6.png)

Sorry if I forgot, what is the reason to have verbose labels instead of tool tips?

**Comment by misolori** [comment]
@sandy081 it originally came from #56028 that I filed about users not understanding that reloading is required to load an extension

While I like how verbose the text is, the text is quite long. Maybe @gregvanl has any ideas on how to make it shorter but yet succinct?

**Comment by ramya-rao-a** [comment]
We can skip the `this extension.` in the end?

**Comment by sandy081** [comment]
Also removing `complete`? Also since enabled extensions are those which are currently running... How about following?

`Reload to Enable`
`Reload to Disable`
`Reload to Uninstall`

**Comment by ramya-rao-a** [comment]
That would result in `Enable` button turning to `Reload to Enable`. Wouldnt that be confusing/annoying? The user just clicked a button to enable the extension, and now we ask them to reload to do the same. 

How about going back to simple "Reload"? A simple text below the buttons can have the full text of `Please reload Visual Studio Code to complete the installing of this extension`

**Comment by sandy081** [comment]
I like it.

**Comment by ramya-rao-a** [comment]
I'll move this to November then

**Comment by luabud** [comment]
I'm sorry if I missed some part of the conversation, but why exactly is the "to activate" being removed from the reload button? I think that "reload to activate" is more informative than just "reload". I remember the first time I installed an extension and I didn't know what "reload" meant nor that I needed to do it in order to activate the extension.

**Comment by sandy081** [comment]
@luabud Its not just about activate, there are other scenarios like uninstall where we cannot have small and proper label. To be consistent we have `Reload` label and description showing why it has to be reloaded.
