### ISSUE TITLE
Markdown Preview using Ctrl+K V not working

### ISSUE THREAD

**Issue by ckarras** [Microsoft/vscode#60063]
I'm having the issue described in https://github.com/Microsoft/vscode/issues/31140 on a fresh install of VSCode, it seems the bug has reappeared.

I tested with the latest release version available on 2018-10-06, and also the latest insiders build, and both have this issue

- VSCode Version: 1.27.2 (user setup) and 1.28.0-insider (user setup)
- Commit: f46c4c469d6e6d8c46f268d1553c5dc4b475840f and 431ef9da3cf88a7e164f9d33bf62695e07c6c2a9
- OS Version: Windows 10 Version 1803 (OS Build 17134.285)

Steps to Reproduce:

1. Open a markdown file (.md)
2. Press Ctrl+K, V
3. Status bar shows "The key combination (Ctrl+K, Ctrl+V) is not a command

Additional checks:
1. Press Ctrl+Shift+P and search for "preview". Shows that the command "Markdown: Open Preview to the Side" is bound to Ctrl+K V
2. Move mouse over to the "Open Preview to the Side" icon in the top right of the window. Tooltip shows that the command is bound to Ctrl+K V
3. The command works when accessed through Ctrl+Shift+P or by a mouse click, it only fails when I try to use the keyboard shortcut.

Does this issue occur when all extensions are disabled?: Yes

**Comment by usernamehw** [comment]
<kbd>Ctrl</kbd>+<kbd>K</kbd> <kbd>Ctrl</kbd>+<kbd>V</kbd>
and
<kbd>Ctrl</kbd>+<kbd>K</kbd> <kbd>V</kbd>
are different commands

**Comment by RMacfarlane** [comment]
Hey @ckarras, thanks for reporting!

From
> Status bar shows "The key combination (Ctrl+K, Ctrl+V) is not a command

It sounds like you might be holding `Ctrl` down for the whole command. For VSCode keyboard shortcuts, if a key should be used in both parts of the chord, it will be listed twice. Does letting go of `Ctrl` before hitting `V` work as expected?

**Comment by ckarras** [comment]
Thanks @RMacfarlane, yes that was the issue. I also tried changing the binding to Ctrl+K Ctrl+V to make it work as I expected, and this works too.
