### ISSUE TITLE
ActionBar items aren't triggerable via keyboard

### ISSUE THREAD

**Issue by w9jds** [Microsoft/vscode#60067]
- VSCode Version: 1.28.0-insider
- OS Version: MacOS Mojave

Steps to Reproduce:
1. Enter into SettingsEditor2
2. Focus the search input
3. Press tab until you get to the Action Item "Workspace Settings"
4. Press space or enter

Expected: Focused tab will be selected
Actual: Nothing happens

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment]
@w9jds Hmm, I'm not able to reproduce this. Is this the most recent insiders?

**Comment by w9jds** [comment]
@RMacfarlane Oh, interesting. If I try it in insider it works, but when I try it in `Code - OSS` for latest master branch it doesn't work. Then when I put in my fix then it works in `Code - OSS`

**Comment by RMacfarlane** [comment]
Ah, I see. Nice catch!
