### ISSUE TITLE
Prefer type `any` to `number` for thread ids in debug protocol

### ISSUE THREAD

**Issue by indiejames** [Microsoft/vscode#6006]
- VSCode Version: 1.0.0
- OS Version: OS X 10.11.4

The debug protocol identifies threads with a unique `number`, but in some languages (e.g., on the JVM) threads are identified by names using a string. It would be more flexible if the debug protocol used `any` instead of `number` to reference threads.

**Comment by weinand** [comment]
@indiejames this is a good suggestion, but I cannot change the protocol in a backward compatible way. So this will have to wait until we start the 'debug protocol 2.0'.

I'll move this request over to the debug protocol repository.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-debugadapter-node#26
