### ISSUE TITLE
Microsoft.Python.LanguageServer used too much memory

### ISSUE THREAD

**Issue by Milkiweed** [Microsoft/vscode#60062]
- VSCode Version: Visual Studio - Insiders
- OS Version: macOS Mojave

Steps to Reproduce:
1. When i open some any file models.py ( in Django app) python server will eat all my memory
2. 
![image](https://user-images.githubusercontent.com/27918941/46569252-f33e8300-c95a-11e8-8c1a-cfd844c52238.png)

Does this issue occur when all extensions are disabled?: No

**Comment by Milkiweed** [comment]
UPD. I see where my problem. When i open file models.py ( in Django app) python server will eat all my memory

this is my file https://pastebin.com/kG4RFHTr

**Comment by Milkiweed** [comment]
help(

**Comment by RMacfarlane** [comment]
@Milkiweed Since this is an issue with an extension and not VSCode itself, please re-open it on the extension: https://github.com/Microsoft/vscode-python
