### ISSUE TITLE
No selection effect on text background

### ISSUE THREAD

**Issue by pixieaka** [Microsoft/vscode#60064]
![capture](https://user-images.githubusercontent.com/17777237/46572719-db7ef300-c98a-11e8-8014-cb3518594e4c.gif)

**Comment by pixieaka** [comment]
@RMacfarlane 
![capture](https://user-images.githubusercontent.com/17777237/46572911-f1da7e00-c98d-11e8-8a28-ea113651605d.PNG)
![ss](https://user-images.githubusercontent.com/17777237/46572918-0454b780-c98e-11e8-8f76-06beb5e55784.PNG)

**Comment by pixieaka** [comment]
The selection copy & paste is working selection background effect only the problem here

**Comment by bpasero** [comment]
@roblourens only seems to reproduce in your settings editor, maybe you can check

**Comment by roblourens** [comment]
This is fixed already in master
