### ISSUE TITLE
Unable to run spring boot app

### ISSUE THREAD

**Issue by angelddios999** [Microsoft/vscode#60060]
We have written the needed data into your clipboard because it was too large
Issue Type: <b>Bug</b>

1. Compile a spring boot app.
2. Click on run from the  Spring-Boot Dashboard
3. The following error is shown:

Failed to launch debuggee VM. Reason: java.io.IOException:Cannot run program "C\Program Files\Java\jdk1.8.0_131\bin\java" (in directory "C\codebase\xxx-xxxxxxxxxxxx"): CreateProcess error=206, The filename or extension is too long

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|15.89GB (6.85GB free)|
|Process Argv|C:\DEV\VSCode\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.6.0
xml|Dot|2.3.2
gitlens|eam|8.5.6
tslint|eg2|1.0.39
gulptasks|nic|1.2.1
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.0.0
vscode-manifest-yaml|Piv|1.0.0
vscode-spring-boot|Piv|1.0.0
java|red|0.32.0
vscode-java-debug|vsc|0.13.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.9.0
vscode-maven|vsc|0.11.0
vscode-spring-boot-dashboard|vsc|0.1.2
vscode-spring-initializr|vsc|0.4.0

</details>
 to send. Please paste.

**Comment by RMacfarlane** [comment]
Hey @angelddios999, since this is an issue with an extension, please report in on the extension itself: https://github.com/Microsoft/vscode-spring-boot-dashboard

From the error message, it sounds like the problem is the length of the path to your code. https://stackoverflow.com/questions/10519558/createprocess-error-206-the-filename-or-extension-is-too-long-when-running-main has some suggestions on this
