### ISSUE TITLE
adding feature like "find usages" which search for occurrences across files for a method/function in VSCode

### ISSUE THREAD

**Issue by rinoldsimon** [Microsoft/vscode#60072]
Visual Studio Code version `1.27.2`

`Find all References` only list references in the `current file`. I need to find all references across files in a project.

Is it possible ?

Something like `find usages`

If you right click a symbol and select "find usages". If the current symbol is a function, then "find usages" searches for all places where this function is called. If the current symbol is a variable, then "find usages" searches for all places where this variable is used etc etc.

**Comment by RMacfarlane** [comment]
@rinoldsimon What language are you using?

**Comment by rinoldsimon** [comment]
@RMacfarlane  `Ruby on Rails`

**Comment by RMacfarlane** [comment]
Thanks @rinoldsimon. The `Find All References` feature for Ruby isn't built into VSCode by default, but added by an extension. Please reopen this issue on the extension you're using

**Comment by rinoldsimon** [comment]
even it doesn't work for Javascript files

**Comment by RMacfarlane** [comment]
@rinoldsimon Hmm, can you describe exactly what you're seeing or give a small code example? I'm able to use `Find All References` to find something across files
