### ISSUE TITLE
Terminal not show text "PS: ...."

### ISSUE THREAD

**Issue by natuan62** [Microsoft/vscode#60078]
- VSCode Version:  1.27.2 (user setup)
- OS Version: Windows 10 Version 1809 (17763.1)

Steps to Reproduce:

1. Open VSCode 

![image](https://user-images.githubusercontent.com/10808157/46577901-96ef6800-ca1b-11e8-9649-61df5e918fcc.png)

Does this issue occur when all extensions are disabled?: Yes
![image](https://user-images.githubusercontent.com/10808157/46577915-dd44c700-ca1b-11e8-861d-61726bd02280.png)

**Comment by egml** [comment]
I have the same issue. This behavior appeared after last Windows 10 Autumn 2018 update (1809). 

![vscode-terminal-blank-screen-problem-2018](https://user-images.githubusercontent.com/2691888/46583571-ba91cd00-ca72-11e8-85eb-467878a00854.gif)

When integrated terminal first appears, there is nothing in it, but it accepts input. And when you type first command and execute it, terminal starts to operate normally.

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/57803
