### ISSUE TITLE
Allow to set CSS for the editor background

### ISSUE THREAD

**Issue by Naixor** [Microsoft/vscode#6007]

**Comment by SamVerschueren** [comment]
Don't believe it's possible. Why do you need it? What's the use case?

**Comment by wowse** [comment]
@SamVerschueren, use case is same as use case for color themes. much editors already have that feature/plugin for that.

**Comment by bgashler1** [comment]
Related #459

**Comment by jrieken** [comment]
@aeschli isn't this doing via theming?

**Comment by aeschli** [comment]
Yes, the editor background is set by the current theme.

**Comment by jrieken** [comment]
ok. closing as the editor background color can be set using themes

**Comment by wowse** [comment]
You can only set background color with theme, not set css of the background.

**Comment by THCloud** [comment]
Atom can set background image now, and it has wonderful performance.
Don't support css on background is the only reason that I don't use vscode ...
I really hope you will concern this ... It looks has no use, but it's really important to persons like me ......

**Comment by SamVerschueren** [comment]
I really wonder why this could be an important feature for someone and even drives the decision of the used text editor? It's a serious question because I'd like to know and understand. To me usability and performance are the ones that make it or break it for me.

**Comment by THCloud** [comment]
There is no doubting that vscode is a powerful editor, and it has so many great features.
But, for example, vscode has 100 features, but only 50 features is useful in my work, and for these 50 features, sublime or atom has 45
then I think I won't use vscode , cause in this case, vscode is a little better than others, but other editors could feed me, too.
it needs cost for a sublime user or an atom user to use vscode (like keybindings) , so I think usability is not the only reason to drive the decision of the used text editor, some other factors will affect me, too (like set css for editor, although it looks useless, but it surely approve its appearance for some person.)

iPhone is really more expensive than Android's, but most people buy it.
IOS has better performance than Android, but I don't think this is the only reason ... iPhone has the most beautiful appearance，these
two reason drive me to buy iPhone.

I remember that vscode is based on Electron，is it hard to add this feature？ If so，er... then you can ignore this . 
But if it isn't, I think this will be a good feature.
Just in my opinion.
I really hope vscode could be better and better.

**Comment by 3DEsprit** [comment]
This is one of those features I felt was required with any editor, almost always due to your theme having a background which didn't fit your needs. Having to find another _good_ theme with the desired color value is an annoying, monotonous, and sometimes impossible. 

With that said, I use the Custom CSS and JS Loader extension, and change it using this:

`.lines-content .monaco-editor-background {
  background-color: #141517;
}`
