### ISSUE TITLE
Activate VS Code actions from command line during startup

### ISSUE THREAD

**Issue by rrmistry** [Microsoft/vscode#60070]
## _Use VS code as JIT debugger for .NET_

I can probably solve this problem if I [add vs code executable path to Windows Registry](https://docs.microsoft.com/en-us/visualstudio/debugger/debug-using-the-just-in-time-debugger). But I would like to see a more cross-platform solution.

The way I would like to solve this problem is in such a way that it can open the door to automation and boost productivity with VS code.

## My use case

The way I see this working is that my .NET code would be as such:
```
using System.Diagnostics;
using System.Threading;
...
// Store current process which gets passed into VS Code command line by its ID
var CurrentProcess = Process.GetCurrentProcess ();

// Start VS Code and activate a command on initialization
Process.Start ($"Code.exe --execute \"CSharp:Attach {CurrentProcess.Id}\" ");

// Now wait for VS Code to initialize
while (!Debugger.IsAttached)
   Thread.Sleep (100);

// Break the debugger at the specified location on demand (like JIT)
Debugger.Break();
...
```

## Some Considerations

The command line can be specific to .NET Core as a minimum-viable-product (e.g. `Code.exe dotnet attach 12345`). But if we add the _capability_ to execute the VS Code actions on initialization then this can support a `Macro` (#4490) or `VS Code Script` nicely.

Common functionality can be set aside in a VS Code Script file, e.g. `datalake_env_setup.vscs`:
```
# Some interaction may be required
Azure: Login
ADL: Login

# Setup environment dynamically
File: Open File
my_path/pass.usql
View: Move Editor into Right Group
File: Open File
my_path/test.usql

# Perform repetitive tasks
ADL: Compile Script
```
followed by `Code.exe --folder-uri "C:/my_folder/" --execute "datalake_env_setup.vscs"`
____

I am not sure if this is possible via an extension. I would love to get feedback and offer my support.
Thanks,

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/10979

**Comment by rrmistry** [comment]
@isidorn thank you for finding the duplicate.

My apologies for not finding it earlier.
