### ISSUE TITLE
allow renaming integrated-terminal tabs

### ISSUE THREAD

**Issue by barretojs** [Microsoft/vscode#60075]
i wanted to be able to rename the terminal tabs, instead of it just showing the current command that's being executed.

for example: i have 3 microservices that'll run on 3 separate docker containers, and i want to separate each execution in the terminal tabs. but, since it only show the current command, all of the tabs are named "docker". it's not a huge problem, but it could simply be solved by renaming each of the tabs according to the microservice that's being executed, for example. it'd be a lot easier to remember which tab i'm supposed to go to see the logging from my services.

a picture to illustrate better:
![screenshot from 2018-10-06 18-03-19](https://user-images.githubusercontent.com/43803300/46575759-26e8cf80-c992-11e8-983f-d16785a0f114.png)

**Comment by Tyriar** [comment]
There is a command to do this: ctrl/cmd+shift+p:

<img width="166" alt="screen shot 2018-10-07 at 10 50 52 am" src="https://user-images.githubusercontent.com/2193314/46584959-00bd4100-ca1f-11e8-95d6-005d0ffd2e3a.png">
