### ISSUE TITLE
Doesn't start on Windows 10 October 2018 Update

### ISSUE THREAD

**Issue by giooohernandez** [Microsoft/vscode#60086]
Issue Type: <b>Bug</b>

After a few uses on W10 October 2018 Update, the application doesn't start up. If likes the app never has been installed on the PC.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17763

**Comment by muhammaddicky** [comment]
#7570

**Comment by joaomoreno** [comment]
Please fully reinstall VS Code and keep an open eye for whether it happens again.
