### ISSUE TITLE
problem with replacing with history value 

### ISSUE THREAD

**Issue by fenyiwudian** [microsoft/vscode#60084]
- VSCode Version:
Version: 1.27.2 (user setup)
Commit: f46c4c469d6e6d8c46f268d1553c5dc4b475840f
Date: 2018-09-12T16:17:45.060Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
- OS Version:
windows10 and macOS seirra 10.12.6

Steps to Reproduce:

1.  open a file with content:
```
aaa
bbb
ccc
ddd
```
2. using search and replace view search 'aaa' and input 'a0a' as replacement, then click replace button => ok: 'aaa' was replaced with 'a0a'
3. search 'bbb' and input 'b1b' as replacement and click replace button => ok: 'bbb' was replaced with 'b1b'
4. search 'ccc' and use arrow key to change replacement to 'a0a'(The replace history) then click replace button => problem: 'ccc' was replace with 'b1b' rather than 'a0a'
5. redo step 4 but do something extra: after using arrow key to switch replacement to 'a0a', changing 'a0a' => 'a0' => 'a0a' then click replace button ok: 'ccc' was replaced with 'a0a'

+ conclusion: It seems like arrow key operation only changed the UI displayed replacement and forgot to change the real replacement.

**Comment by roblourens** [comment]
I can't repro this, can you record a gif or video?

**Comment by sandy081** [comment]
@rebornix Let me know if it is something to do with History.

**Comment by davidkwan95** [comment]
I can take this if I can get some pointers on where to start

**Comment by rebornix** [comment]
I can no longer reproduce this issue.
