### ISSUE TITLE
CSS files imported into JS not clickable

### ISSUE THREAD

**Issue by dwelle** [Microsoft/vscode#60088]
- VSCode Version: 1.27.2
- OS Version: win 7

Steps to Reproduce:

1. `import` a css file into a js file
2. the css file is not clickable (cannot jump to file via `ctrl+click`)

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/5153846/46579829-4a0a9200-ca19-11e8-815e-02e854c7ac4c.png)

**Comment by skprabhanjan** [comment]
@mjbvz , Can i work on this issue?

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/Microsoft/TypeScript/issues/15146
