### ISSUE TITLE
Auto Import in C# for a ASPNET Core Project is not working

### ISSUE THREAD

**Issue by Ammat-ALLAH** [Microsoft/vscode#60085]
Issue Type: <b>Bug</b>

Auto fix and Ctrl+. and Ctrl + space is not getting me any suggestion for the import statment for example I typed ICollection to declare a variable and as previously behaviour we type CTRL + . this Auto imports the name space of the collevtion generics , but the actual behaviour was nothing Suggested 

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (4.13GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-postgres|cko|1.1.3
angular2-snippets|dan|1.0.20
tslint|eg2|1.0.39
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
beautify|Hoo|1.4.4
rest-client|hum|0.19.1
csharpextensions|jch|1.3.0
diff-tool|jin|0.0.1
Angular2|joh|6.2.0
postgresql|JPT|0.0.2
vscode-extension-auto-import|mop|1.3.3
mssql|ms-|1.4.0
csharp|ms-|1.16.1
team|ms-|1.136.0
debugger-for-chrome|msj|4.10.2
aspnet-helper|sch|0.6.4
vscode-auto-install|spe|1.0.1
autoimport|ste|1.5.3
save-and-run|wk-|0.0.21

</details>

**Comment by RMacfarlane** [comment]
Hey @Ammat-ALLAH, since the C# extension is responsible for suggestions for C#, please re-open it on the extension: https://github.com/OmniSharp/omnisharp-vscode

**Comment by Ammat-ALLAH** [comment]
> Hey @Ammat-ALLAH, since the C# extension is responsible for suggestions for C#, please re-open it on the extension: https://github.com/OmniSharp/omnisharp-vscode
thanks @RMacfarlane but I am already having it
I used this pack for installing
https://marketplace.visualstudio.com/items?itemName=temilaj.asp-net-core-vs-code-extension-pack
and it`s including everything needed, but I am still having the same problem, No code IntelliSense ,documentation nor auto import

**Comment by RMacfarlane** [comment]
Hey @Ammat-ALLAH, sorry for the confusion.

This is a problem with the C# extension, not VS Code itself. So please report the issue on the C# extension, by creating a new issue here: https://github.com/OmniSharp/omnisharp-vscode

This repository is for problems with VS Code.

**Comment by Ammat-ALLAH** [comment]
> 
> 
> Hey @Ammat-ALLAH, sorry for the confusion.
> 
> This is a problem with the C# extension, not VS Code itself. So please report the issue on the C# extension, by creating a new issue here: https://github.com/OmniSharp/omnisharp-vscode
> 
> This repository is for problems with VS Code.

Thanks, I`ll report the issue there
