### ISSUE TITLE
Warning `rejected promise not handled within 1 second` when running arbitrary extensions.

### ISSUE THREAD

**Issue by Anti-Li** [Microsoft/vscode#60081]
Issue Type: <b>Bug</b>

Warning `rejected promise not handled within 1 second` when running arbitrary extensions. Even the example "mock-debug", or a empty extension generated by "yo code".

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.92GB (0.54GB free)|
|Process Argv|C:\Users\andyl\AppData\Local\Programs\Microsoft VS Code\Code.exe --folder-uri file:///c%3A/Users/andyl/Projects/c-cpp-compile-run|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by Anti-Li** [comment]
![image](https://user-images.githubusercontent.com/28052536/46579239-07a87b80-ca40-11e8-9796-41f1555ba5bf.png)

**Comment by RMacfarlane** [comment]
I haven't been able to reproduce this yet. Are there any additional details in the dev console (`Developer: Toggle Developer Tools`)?

**Comment by Anti-Li** [comment]
![image](https://user-images.githubusercontent.com/28052536/46603088-9ee6ff00-cb24-11e8-93e3-a750465b0469.png)

## From the development host

![image](https://user-images.githubusercontent.com/28052536/46603179-e4a3c780-cb24-11e8-96b5-e270a9aa28c4.png)


<details>
<summary>Log from Toggle Developer Tools</summary>
[-1538993358905.log](https://github.com/Microsoft/vscode/files/2455509/-1538993358905.log)
</details>

**Comment by RMacfarlane** [comment]
Thanks! Based on the callstack in the second screenshot, this warning is from the C++ extension: https://github.com/Microsoft/vscode-cpptools

Since this is being caused by an extension, please reopen it there
