### ISSUE TITLE
help menu appeared 2 times in the menubar

### ISSUE THREAD

**Issue by duongphuhiep** [Microsoft/vscode#60089]
Issue Type: <b>Bug</b>

Open the Issue Reporter, then close it
and I saw 2 help menu items, with exactly the same content

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:11:15.873Z)
OS version: Linux x64 4.4.0-137-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 3499)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.56GB (5.12GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (154)</summary>

Extension|Author (truncated)|Version
---|---|---
html-class-suggestions|And|1.0.7
EditorConfig|Edi|0.12.4
crane|Hvy|0.3.8
XMLLanguageSupport|IBM|0.0.1
postgresql|JPT|0.0.2
autofilename|Jer|0.1.3
format-indent|Kas|1.3.0
format-php|Kas|1.1.2
console-log|Lui|0.0.1
vscode-html-scss|P-d|0.0.42
go-test-outline|Rom|0.2.0
ActiveFileInStatusBar|Ros|1.0.3
php-formatter|Sop|0.2.4
vscode-surround|Swo|1.0.1
lorem-ipsum|Tyr|1.2.0
html-css-class-completion|Zig|1.17.1
better-comments|aar|2.0.1
html-snippets|abu|0.2.1
Bookmarks|ale|9.1.0
project-manager|ale|9.0.1
copy-relative-path|ale|0.0.2
vscode-color|ans|0.4.5
code-gnu-global|aus|0.2.2
vscode-intelephense-client|bme|0.8.8
htmltagwrap|bra|0.0.7
pgformatter|bra|1.5.1
phpserver|bra|2.4.6
materialcolorsnippets|bru|1.0.0
better-phpunit|cal|1.0.0
dep|car|0.1.0
gotemplate|cas|0.2.0
Gradle|caz|1.1.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
bracket-pair-colorizer|Coe|1.0.60
supersharp|cra|0.1.4
vscode-svgviewer|css|1.4.6
vue-peek|dar|1.0.2
vscode-markdownlint|Dav|0.20.0
jshint|dba|0.10.20
vscode-eslint|dba|1.6.0
githistory|don|0.4.3
javadebugger|don|0.1.5
xml|Dot|2.3.2
pgsql|dou|0.1.3
Vue2|duc|0.1.3
vscode-babel-coloring|dza|0.0.4
gitlens|eam|8.5.6
vscode-html-css|ecm|0.2.0
vscode-npm-script|eg2|0.3.5
LogFileHighlighter|emi|2.4.1
prettier-vscode|esb|1.6.1
php-debug|fel|1.12.6
php-intellisense|fel|2.3.5
php-pack|fel|1.0.2
php-file-types|fet|1.2.1
vscode-npm|fkn|3.3.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.4
dotnet|for|0.0.4
vscode-javac|geo|0.2.5
another-word-completion|get|0.0.4
pug2html|gin|0.0.5
name-that-color|gui|0.1.2
docker-linter|hen|0.5.0
npm-dependency-links|her|1.0.0
vue-snippets|hol|0.1.9
beautify|Hoo|1.4.4
pgsql-html|hub|0.0.7
javascript-unit-test-snippet|iZD|1.0.0
composer|ika|0.7.1
java-properties|ith|0.0.2
google-complete-me|jay|1.0.6
csharpextensions|jch|1.3.0
copy-markdown-as-html|jer|1.1.0
sharppad|jma|1.0.5
golang-tdd|joa|0.0.9
docthis|joe|0.7.1
vscode-csharp-snippets|jor|0.3.1
vscode-random|jre|1.3.2
fuzzy-definitions|jri|0.0.3
php-cs-fixer|jun|0.1.85
docomment|k--|0.1.2
wordcounter|kir|1.3.0
vscode-phpfmt|kok|1.0.30
net-core-project-manager|ksu|0.3.6
csharpfixformat|Leo|0.0.74
php-symbols|lin|2.1.0
sftp|lix|1.5.11
vscode-JS-CSS-HTML-formatter|lon|0.2.3
ftp-sync|luk|0.3.3
Kotlin|mat|1.6.0
code-beautifier|mic|2.1.0
prettify-json|moh|0.0.3
graphql|mqu|0.1.2
vscode-attrs-sorter|mrm|2.1.0
vscode-pugbeautify|mrm|1.0.2
vscode-scss|mrm|0.6.2
mssql|ms-|1.4.0
cpptools|ms-|0.19.0
csharp|ms-|1.16.1
Go|ms-|0.6.90
vs-keybindings|ms-|0.2.0
go-doc|msy|0.1.1
sqltools|mtx|0.15.1
vuejs-extension-pack|mub|1.1.3
php-docblocker|nei|1.6.0
vetur|oct|0.13.0
laravel-blade|one|1.18.0
marko|pca|0.3.0
vscode-docker|Pet|0.3.1
vscode-versionlens|pfl|0.21.2
quicktype|qui|12.0.46
addlocalnetreferences|Raf|0.0.3
java|red|0.32.0
classynaming|ref|1.2.0
format-html-in-php|rif|1.3.6
create-file-folder|rit|0.0.5
vscode-icons|rob|7.27.0
sass-indented|rob|1.4.9
iferrblocks|rst|1.1.1
gi|rub|0.2.11
rust|rus|0.4.10
yo|sam|0.9.3
aspnet-helper|sch|0.6.4
vue-vscode-extensionpack|sdr|0.1.3
vue-vscode-snippets|sdr|1.3.0
vue|sea|0.4.2
preview-vscode|sea|1.4.4
code-settings-sync|Sha|3.1.2
vuejspack|she|1.3.2
stylelint|shi|0.43.0
html5-boilerplate|sid|1.0.3
vscode-fileutils|sle|2.11.0
react-beautify|tai|0.3.0
msbuild-project-tools|tin|0.2.42
vscode-status-bar-format-toggle|tom|1.4.0
java-imports-snippets|tus|0.0.1
java-snippets|tus|0.0.1
vscode-glide|vit|1.0.2
babelrc|wad|1.0.0
quokka-vscode|Wal|1.0.151
vscode-todo-highlight|way|1.0.4
html-snippets|wge|0.1.5
twig|wha|1.0.2
vscode-import-cost|wix|2.9.0
webpack-progress|wk-|0.0.8
vscode-jumpy|wma|0.3.1
JasmineSnippets|xab|1.0.1
JavaScriptSnippets|xab|1.7.0
local-history|xyz|1.7.0
editorconfig-vscode-snippet|zgu|0.2.0

(2 theme extensions excluded)

</details>

**Comment by RMacfarlane** [comment]
@duongphuhiep Does this happen reliably, every time you open and close the issue reporter? Do you also see this when all extensions are disabled? (Can run the command `Reload Window with Extensions Disabled` to test this)

**Comment by duongphuhiep** [comment]
I can no longer reproduce the problem, maybe it due to recent extensions update.
