### ISSUE TITLE
Cannot edit in read-only editor

### ISSUE THREAD

**Issue by amirafshari** [Microsoft/vscode#60096]
Issue Type: <b>Bug</b>

Hi, I don't exactly know when it happened, but recently when I want to enter any input in output pannel I get that blue box which it says: 'Cannot edit in read-only editor'. I can edit my code, but I cant input anything from 'input()' command. How can I fix this?

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz (8 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (2.50GB free)|
|Process Argv|F:\Installed\Microsoft VS Code\Code.exe C:\Users\Amir\Desktop\sum1.py|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.4
mssql|ms-|1.4.0
python|ms-|2018.8.0
PowerShell|ms-|1.9.0

(3 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Output pannel was always read only and nothing changed here.
Try changing the panel by clicking on the debug console or on the integrated terminal. Or jsut type in the editor which is not readonly.

**Comment by myheartwillgoon** [comment]
you maybe click files from git staged changes panel.It happened when i git stash pop.

**Comment by myheartwillgoon** [comment]
you maybe click files from git staged changes panel.It happened when i exec git stash pop.
