### ISSUE TITLE
Visual Studio Code (User), Git for Windows (System) causes Segmentation Fault on every bash.exe command in Integrated Terminal

### ISSUE THREAD

**Issue by SubhamSatyajeet** [Microsoft/vscode#60099]
- Visual Studio Code Version: 1.27.2 (User Setup)
- OS: Windows 10, version 17134.320

Steps to Reproduce:

1. Install Visual Studio Code (User Setup)
2. Install Git for Windows (System Setup) i.e. provide Administrator rights to the installer when prompted via UAC, and install within the default Program Files directory
3. Open Visual Studio Code. It asks for the Default Shell right away. Select bash from the list of options.
4. Open a folder in Visual Studio Code. Open the terminal by using ` + Ctrl.
5. Try to execute any command (clear, git init etc).
6. The error "segmentation fault"/"segmentation fault (core dumped)" is shown, depending on the command run. If the "segmentation fault (core dumped)" is shown, a stack dump file is created in the present working directory.

Does this issue occur when all extensions are disabled? Yes

Known Workarounds:
1) Install using the System Installer for both Visual Studio Code and Git Bash. I am currently using this setup, but this is not recommended for Visual Studio Code since version 1.27. Also, the User installer has a smoother update process - no UAC prompts for administrator privileges.
2) Install using the User Installer for Visual Studio Code. Also, install Git Bash for the current user only by clicking on Cancel when Git for Windows installer asks you for elevated permissions in the UAC prompt.

**Comment by Tyriar** [comment]
@joaomoreno have you seen issues with this around the user installer? Is the "fix" here perhaps to just to use the system installer as @SubhamSatyajeet is?

**Comment by joaomoreno** [comment]
Not really, I doubt that this is related to the kind of setup used... The bits within each setup are 100% identical. Needs more investigation.

**Comment by Tyriar** [comment]
In that case this is likely in the class of issues that will be fixed with conpty https://github.com/Microsoft/vscode/issues/45693, stay tuned 😃
