### ISSUE TITLE
Solution Explorer disable won't stick

### ISSUE THREAD

**Issue by ruant** [Microsoft/vscode#60093]
Issue Type: <b>Bug</b>

Open up some files so they are some in the tab.
Right click, uncheck solution explorer.
Change to a new tab.
Solution explorer is active again.
Change back to the tab that you disabled solution explorer on, active there too.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17763

<details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-database|baj|1.5.2
vscode-markdownlint|Dav|0.20.0
gitlens|eam|8.5.6
tslint|eg2|1.0.39
vscode-solution-explorer|fer|0.2.34
beautify|Hoo|1.4.4
csharp|ms-|1.16.1
debugger-for-chrome|msj|4.10.2
vscode-docker|Pet|0.3.1
quicktype|qui|12.0.46
markdown-preview-enhanced|shd|0.3.8
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.9.0
markdown-all-in-one|yzh|1.6.0

</details>

**Comment by RMacfarlane** [comment]
Hey @ruant, since the solution explorer extension is responsible for determining when this view gets shown, please reopen this on the extension: https://github.com/fernandoescolar/vscode-solution-explorer Thanks
