### ISSUE TITLE
Implementing an alternative jump to file?

### ISSUE THREAD

**Issue by spion** [Microsoft/vscode#601]
I'd like to implement an alternative jump to file that uses a [custom matching algorithm](https://github.com/spion/fuzzy-matcher). Is this possible, or is the extension API too limited to do this?

The closest thing seems to be [the quickpick api](https://code.visualstudio.com/docs/extensionAPI/vscode-api#QuickPickOptions), and it falls short. Perhaps `QuickPickItem` could be allowed to implement a `matches(input:string):boolean` method?

**Comment by egamma** [comment]
This is not exposed in the API and is not a priority, so the route for you is a contribution see https://github.com/Microsoft/vscode/wiki/How-to-Contribute and if successful do a PR.

**Comment by jrieken** [comment]
closing as duplicate of #426
