### ISSUE TITLE
terminal 

### ISSUE THREAD

**Issue by saipradc** [Microsoft/vscode#60102]
Issue Type: <b>Bug</b>

when i m running the terminal, i guess the code is execuiting properly. But the terminal is not displying anything. 

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (3.54GB free)|
|Process Argv|C:\Users\saich\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|44%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
plsql|cas|0.0.3
vscode-mysql|for|0.3.0
mysql-syntax|jak|1.3.1
mysql-scratchpad|jbl|0.1.1
puppet-vscode|jpo|0.12.0
vscode-swift|kia|0.8.0
mssql|ms-|1.4.0
python|ms-|2018.8.0
vscode-docker|Pet|0.3.1
vscode-yaml|red|0.0.17
plsql-language|xyz|1.5.0

</details>

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/57803
