### ISSUE TITLE
VS Code isn't opens many times

### ISSUE THREAD

**Issue by AbhieShinde** [microsoft/vscode#60101]
Issue Type: <b>Bug</b>

Couple of times i'm not able to run VS Code on my Lenovo IP520 ! I had to uninstall Code followed by Reinstallation to atleast open Code on next boot!!!!!! Please solve this? 

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (11.75GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by RMacfarlane** [comment]
Did this start after updating windows? https://github.com/Microsoft/vscode/issues/60086

**Comment by DanCarl857** [comment]
Hello, 

I too face this issue both with Visual Studio Code and the Insiders version. Sometimes even reinstalling doesn't fix the problem.

OS version: Mac OS Sierra

**Comment by DanCarl857** [comment]
No I didn't get this with earlier versions of VSCode. Sorry not really able to test `code --verbose` because I have already uninstalled and reinstalled VSCode but once I get that again, I'll test and share what it says
