### ISSUE TITLE
Dynamic Menu Bar Priority?

### ISSUE THREAD

**Issue by Astrantia** [Microsoft/vscode#60110]
https://github.com/Microsoft/vscode/issues/14986 This has only 2 upvotes and from what I'm able to tell the October Iteration focuses on making vscode menu bar say Enter Full Screen / Exit Full Screen on state changes. How is this even important with regards to all the other upvoted feature requests? Why does this have any priority at all if it's not a 1 day fix?  refs https://github.com/Microsoft/vscode/issues/60106
@bpasero

**Comment by RMacfarlane** [comment]
Hi @Astrantia, please limit new issues to bugs and features requests. It helps us to manage issues if discussion is not spread across a number of different issues.

You can see our roadmap [here](https://github.com/Microsoft/vscode/wiki/Roadmap), one piece of this is the menu bar, which has been changed to a custom implementation recently. We do consider upvotes when planning, but improving and polishing existing features is also a priority to us.
