### ISSUE TITLE
#region

### ISSUE THREAD

**Issue by XiaoDaJun** [microsoft/vscode#60114]
写出成对的#region后，在后面写当前#region的标题，敲回车，发现#region前多了一个#符号，变成 ##region，而且，回车后在#region内部的光标没有自动缩进；
另一个问题是，其他的自动补全代码，比如if（）{}，在括号中填写完内容， 敲回车，就会把右括号换到下一行中。
以上问题，是相比较visual studio类似功能来说的，VS中这两个操作已经很完美。

**Comment by RMacfarlane** [comment]
> After writing the paired #region, write the title of the current #region in the back, hit enter, find a ## before the #region, become ##region, and, after the carriage return, the cursor inside #region does not Automatic indentation;
Another problem is that other auto-completion code, such as if(){}, fills in the content in parentheses, hits Enter, and changes the right parenthesis to the next line.
The above problem is compared to the similar functions of visual studio. These two operations in VS are perfect.

@XiaoDaJun What version of VSCode are you using? What language are you coding in?

**Comment by XiaoDaJun** [comment]
VSCode Version: 1.27.2 (user setup)
Commit: f46c4c469d6e6d8c46f268d1553c5dc4b475840f
Date: 2018-09-12T16:17:45.060Z

I use C#.
Thanks.

At 2018-10-08 11:07:15, "Rachel Macfarlane" <notifications@github.com> wrote:


After writing the paired #region, write the title of the current #region in the back, hit enter, find a ## before the #region, become ##region, and, after the carriage return, the cursor inside #region does not Automatic indentation;
Another problem is that other auto-completion code, such as if(){}, fills in the content in parentheses, hits Enter, and changes the right parenthesis to the next line.
The above problem is compared to the similar functions of visual studio. These two operations in VS are perfect.

@XiaoDaJun What version of VSCode are you using? What language are you coding in?
