### ISSUE TITLE
Bug: Right clicking in the editor cause abnormal behaviour.

### ISSUE THREAD

**Issue by i-shubhamprakash** [Microsoft/vscode#60119]
- VSCode Version: 1.27.2
- OS Version: Linux mint 19

# Bug description:

1. When I right click on the editor (not on the code), it opens Branch History menu.
2. When I right click on any code, it opens git diff view.
3. when I select text and then right click, it opens function definition view.
4. Sometimes it shows random behavior on right-clicking anywhere in the editor. For example, it opens the Github repository page in chrome or git diff page in chrome, or even try to run code-runner extension etc.

> **This problem occur only when window title bar is set to custom. 
        i.e. when ( "window.titleBarStyle": "custom" ) in user setting.**

> Note: This problem occurs more when Gitlens extension is installed and enabled.

**Please also look at this bug report in gitlens repo:**
Link: https://github.com/eamodio/vscode-gitlens/issues/518 

Please fix this issue, it is very annoying.
All the best.
I love vscode.
Thanks :)

**Does this issue occur when all extensions are disabled?**: Yes/No
No problem is seen when all extension is disabled.
However, this issue only occurs when Gitlens extension is enabled.
Link: https://github.com/eamodio/vscode-gitlens/issues/518

**Comment by RMacfarlane** [comment]
@i-shubhamprakash Just to confirm, this is version 1.27.2 of VSCode?

**Comment by i-shubhamprakash** [comment]
Yes, My mistake. it is actually 1.27.2
I'll edit that.
Thanks

**Comment by sbatten** [comment]
@i-shubhamprakash you may be experiencing these symptoms as a result of #57399. With the latest update to 1.28, this could be fixed for you. Could you give it a try?

**Comment by i-shubhamprakash** [comment]
Yes! I also think #57399 might be the reason of this issue. I'll update my vs code to v 1.28 and let you know if the issue is reaolved or not.
Thanks.

**Comment by i-shubhamprakash** [comment]
@sbatten  I updated the app to v 1.28 and the issue seems to be fixed. I am not experiencing any problem with the right click.
Thanks for the help.

**Comment by sbatten** [comment]
@i-shubhamprakash thanks for confirming :)
