### ISSUE TITLE
Emmet Typing semicolon should lead to skipping expanded semicolon character for CSS abbreviations

### ISSUE THREAD

**Issue by lmmm0013** [microsoft/vscode#60117]
I installed emmet，coding css

enter "w" key，choose "width: |;" options，
enter some value "width: 100px|;", now, the cursor is in the vertical line.
I have to use the right ARROW key to skip this Semicolon. 
BUT, on the sublime, i just enter ';' auto replace cursor next Semicolon，like this "width: 10px|;" enter ";" result "width: 10px;|"

Can you give a setup option, like the sublime input method?

**Comment by lmmm0013** [comment]
This happens when I use the sublime habit of Editing.
.header { width: 100px; height: 60px; font-size: 36px;|;;;}  line is cursor

**Comment by GongT** [comment]
same here, using webstrom.

**Comment by ramya-rao-a** [comment]
@lmmm0013, @GongT Until we fix this, you can add the below to your settings
```
"emmet.preferences": {
		"css.propertyEnd": ""
	}
```

This will stop adding the `;` at the end of the expanded abbreviation allowing you to add it when typing out the value.

**Comment by octoxan** [comment]
This is killing me right now.
