### ISSUE TITLE
No hay proveedores de control de código fuente activos

### ISSUE THREAD

**Issue by jcjocop** [Microsoft/vscode#60112]
Hemos escrito los datos necesarios en su Portapapeles porque eran demasiado grandes para enviarlos. Ahora debe pegarlos.

**Comment by jcjocop** [comment]
Tengo instalado Git. Luego instalé la última versión de VSCode (VSCodeUserSetup-x64-1.27.2). Sin embargo, al seleccionar en la barra lateral izquierda el ícono de "control de código fuente" me indica que no "no hay proveedores de control de código fuente activos".

Qué puedo hacer ? 

Gracias.

**Comment by homerybart** [comment]
Hola
  Acabo de instlar VSCode versión 1.28.2 y utilizo GIT, al arrancar VSCode en la salida me pone: "Usando GIT 2.18.0.windows.1 desde F:\PortableApps\Git\cmd\git.exe", pero en el panel de control de código fuente sale: "No hay proveedores de control de código fuente registrados" el path de Git es correcto, y con la versión anterior de VSCode funcionaba correctamente, ¿puede ser un bug?

Gracias

**Comment by homerybart** [comment]
Hola
  Solucionado!! faltaba por inicializar el repositorio con "Initialize Repository"

Gracias

**Comment by RMacfarlane** [comment]
@jcjocop Are you still seeing this problem?
