### ISSUE TITLE
一键打开hosts文件

### ISSUE THREAD

**Issue by bmqy** [Microsoft/vscode#60125]
Issue Type: <b>Feature Request</b>

希望可以支持，一键打开hosts文件以供开发人员快速编辑

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

**Comment by GongT** [comment]
👎 这不是一个编辑器或者通用的IDE该做的     
不过你可以写个插件

**Comment by GongT** [comment]
She wants a "open hosts file" button on VS Code

**Comment by bmqy** [comment]
> 这不是一个编辑器或者通用的IDE该做的
> 不过你可以写个插件


试过，没有成功，请问如何打开hosts文件，设置的打开路径没有反应，用的这个方法
let uri = Uri.file('/some/path/to/folder');
let success = await commands.executeCommand('vscode.openFolder', uri);

**Comment by bmqy** [comment]
> We try to keep VS Code lean and we think the functionality you're asking for is great for a VS Code extension. Maybe you can already find one that suits you in the [VS Code Marketplace](https://aka.ms/vscodemarketplace). Just in case, in a few simple steps you can get started [writing your own extension](https://aka.ms/vscodewritingextensions). See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.
> 
> Happy Coding!


试过，没有成功，请问如何打开hosts文件，设置的打开路径没有反应，用的这个方法
let uri = Uri.file('/some/path/to/folder');
let success = await commands.executeCommand('vscode.openFolder', uri);

**Comment by bmqy** [comment]
已发布：https://github.com/bmqy/fast-hosts
