### ISSUE TITLE
Please provide a split terminal to a separate suspendable top function

### ISSUE THREAD

**Issue by muyu66** [Microsoft/vscode#60127]
Please provide a split terminal to a separate suspendable top function

I am using CMDER to connect windows10's WSL now. When i find vscode support WSL, i am happy.
I wish vscode's terminal can split to a Window so that i can work like Windows Terminal before

**Comment by Tyriar** [comment]
It's not clear what you're after, do you mean being able to pull the terminal outside of the main window? This? https://github.com/Microsoft/vscode/issues/34442
