### ISSUE TITLE
莫名假死

### ISSUE THREAD

**Issue by bensonzhow** [Microsoft/vscode#60129]
Issue Type: <b>Bug</b>

打开typescript编译后的文件，几分钟后莫名假死！需要重新打开！

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (5.97GB free)|
|Process Argv|D:\vscode\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
vs-treeview|DaG|2.5.2
markdown-table-prettify|dar|2.2.0
vscode-markdownlint|Dav|0.20.0
es7-react-js-snippets|dsz|1.8.6
vscode-babel-coloring|dza|0.0.4
todo-tree|Gru|0.0.92
node-module-intellisense|lei|1.5.0
git-tree-compare|let|1.3.0
markdown-shortcuts|mdi|0.8.1
code-beautifier|mic|2.1.0
vscode-extension-auto-import|mop|1.3.3
vscode-language-pack-zh-hans|MS-|1.27.2
debugger-for-chrome|msj|4.10.2
ejs-language-support|Qas|0.0.1
vscode-react-native|vsm|0.6.18
full-react-snippets|wal|1.1.2
JavaScriptSnippets|xab|1.7.1
markdown-all-in-one|yzh|1.6.0

(2 theme extensions excluded)

</details>

**Comment by WangZishi** [comment]
Maybe you can try to disable all the 3rd part extensions first and see whether it is the extensions problem.

**Comment by mjbvz** [comment]
Yes, please check if this happens with all extensions disabled. Also provide more info about what is going wrong
