### ISSUE TITLE
Indentation should consider escape sequence for SQL language 

### ISSUE THREAD

**Issue by AbhishekSharma20** [Microsoft/vscode#60124]
Issue Type: <b>Bug</b>

If you see this command on vs_code, the code does not gets indented properly because of a ' character in the string which is escaped by \.

SELECT 0                                  AS passed,
       4195                                      AS pre_id,
       f.id,
       f.sig_id,
       f.build_id,
       f.tc_id,
       f.batch_id,
       spf.cycles,
       spf.cpu_time,
       spf.cps 
  FROM sims_fail___4195                     AS f JOIN sim_perf_fail___4195 AS spf 
    ON spf.id = f.sim_perf_id JOIN sigs___289 AS sigs 
    ON sigs.id = f.sig_id JOIN batches___289  AS b 
    ON b.id = f.batch_id 
 WHERE sigs.signature = 'C_ASSERTION:`false\'' 
   AND NOT ((b.name LIKE '%\\_\\_enablement%')) 
   AND b.state in (1,8,6,3) 
   AND b.owner = 'ainfra' 
   AND b.use_model in ('regr simulation') 
   AND f.start_timestamp BETWEEN '2018-07-12 00:00:00' 
   AND '2018-07-18 23:59:59'
UNION 
SELECT 0        AS passed,
       4196                                      AS pre_id,
       f.id                                      AS id,
       f.sig_id                                  AS sigId,
       f.build_id                                AS buildId,
       f.tc_id                                   AS tcId,
       f.batch_id                                AS batchId,
       spf.cycles                                AS cycles,
       spf.cpu_time                              AS cpuTime,
       spf.cps                                   AS cps
  FROM sims_fail___4196                     AS f JOIN sim_perf_fail___4196 AS spf 
    ON spf.id = f.sim_perf_id JOIN sigs___289 AS sigs 
    ON sigs.id = f.sig_id JOIN batches___289  AS b 
    ON b.id = f.batch_id 
 WHERE sigs.signature = 'C_ASSERTION:`false\'' 
   AND NOT ((b.name LIKE '%\\_\\_enablement%')) 
   AND b.state in (1,8,6,3) 
   AND b.owner = 'ainfra' 
   AND b.use_model in ('regr simulation') 
   AND f.start_timestamp BETWEEN '2018-07-12 00:00:00' 
   AND '2018-07-18 23:59:59'

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
sqlformatter|bre|0.0.7
xml|Dot|2.3.2
sftp|lix|1.5.13
mssql|ms-|1.4.0
cpptools|ms-|0.19.0
ruby|reb|0.20.0
partial-diff|ryu|1.4.0

</details>

**Comment by egamma** [comment]
please file the issue against the SQL extension.
