### ISSUE TITLE
Visual Studio Code - Fedora Rawhide Segfault

### ISSUE THREAD

**Issue by present86** [Microsoft/vscode#60128]
Hello installed visual studio code from Microsoft repo git this error

`/usr/bin/code: line 35:  3391 Segmentation fault      (core dumped) ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"
`

- VSCode Version: 1.27.2
- OS Version: Fedora Rawhide

Steps to Reproduce:

1. Reinstall VS Code still same
2. Reinstall Glibc as reffered on Archlinux but still fail

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
It should work in the build released today https://github.com/Microsoft/vscode/issues/55934
