### ISSUE TITLE
Auto-save on type

### ISSUE THREAD

**Issue by avi12** [Microsoft/vscode#60123]
There's an [extension](https://marketplace.visualstudio.com/items?itemName=akhail.save-typing) that does this.  
Would be nice if it would be a built-in feature, as this extension isn't perfect - if the file isn't already saved, the extension will prompt to save the file on every keyboard stroke.

**Comment by egamma** [comment]
@avi12 can you please elaborate what is the difference between this extension and enabling `Auto Save` as provide by VS Code out of the box (File>Auto Save).
