### ISSUE TITLE
Javascript Intellisense "await" keyword missed

### ISSUE THREAD

**Issue by Cow258** [Microsoft/vscode#60133]
Issue Type: <b>Bug</b>

1. Install VSCode Insiders 1.28.0
2. Create .js file
3. Create async function
4. Enter "aw"

await keyword is working on VSCode 1.27.2

Here are some screenshoot with 
[VSCode 1.27.2](https://drive.google.com/file/d/1FnrJWjiG0KRtNDbJnIhGDSlkvDdJvH1x/view?usp=sharing)
[VSCode Insiders 1.28.0](https://drive.google.com/file/d/1vqJyaR4GUGf51pUmVey2f-OtzmGOu7kM/view?usp=sharing)

VS Code version: Code - Insiders 1.28.0-insider (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-03T12:36:03.286Z)
OS version: Darwin x64 18.0.0 (macOS Mojave 10.14)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|24.00GB (1.45GB free)|
|Process Argv|-psn_0_1757613|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
Handlebars|and|0.4.1
vscode-eslint|dba|1.6.0
githistory|don|0.4.3
gitlens|eam|8.5.6
vscode-mysql|for|0.3.0
minify|Hoo|0.3.0
code-beautifier|mic|2.1.0
vscode-filesize|mkx|2.1.1
vscode-language-pack-zh-hant|MS-|1.28.2
material-icon-theme|PKi|3.6.0
ejs-language-support|Qas|0.0.1

</details>

**Comment by vibhor1997a** [comment]
Facing the very same issue in version `1.28.0`

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/27622 to track this upstream
