### ISSUE TITLE
Its getting really slow these days, trying to commit my file not showing my changes

### ISSUE THREAD

**Issue by garima-birdeye** [Microsoft/vscode#60134]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
jsx|Twe|0.0.1
html-css-class-completion|Zig|1.15.0
html-snippets|abu|0.2.1
vscode-eslint|dba|1.4.10
vscode-html-css|ecm|0.1.8
intellij-idea-keybindings|k--|0.2.17
react-beautify|tai|0.3.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
Can you elaborate on the issue?
