### ISSUE TITLE
Can't start as normal user on Arch Linux

### ISSUE THREAD

**Issue by Thunkar** [Microsoft/vscode#6013]
- VSCode Version: 1.0.0 and 1.1.0
- OS Version: Arch Linux x64

VSCode doesn't start, either from a shortcut or the terminal when launched as a normal user. The insider version works as sudo, but not as a normal user. The GUI doesn't appear and the process must be killed manually. Launching it with the --verbose option generates a blank output.

Things I've tried:

Manual install & from the AUR package
.config and .vscode folders have the correct permissions
Using electron's --enable-logging and --v=10 gives different outputs for a normal (failing) launch and a sudo (correct) launch:

Results in hang:
![image](https://cloud.githubusercontent.com/assets/5404052/14935294/43393f5e-0ecc-11e6-958c-1fbe6a9a9e69.png)

Works as expected:

![image](https://cloud.githubusercontent.com/assets/5404052/14935303/86460cb4-0ecc-11e6-83db-d0b2a96378ac.png)

**Comment by joaomoreno** [comment]
Double check that `.vscode*` and `.config/Code*` really do have the right permissions. As proof, simply rename those to some other names and relaunch Code, which should recreate them.

**Comment by Thunkar** [comment]
I renamed the folders to .vscode_bk and .config/Code-bk and it recreated them, but the bug persists. I noticed the .config/Code has 700 permissions and got an error message about 'storage.json', so I changed the permissions to 755 and copied the file from /root/.config/Code/storage.json (and set the correct ownership and permissions) to no avail. Since the app is installed in /opt, I also changed the ownership of the files inside /opt/visual-studio-code, still not working.

**Comment by joaomoreno** [comment]
Where did you get the AUR package?

**Comment by Thunkar** [comment]
I use pacaur, but I have also tried to install it manually from the official website. Anyways, the package pacaur uses should be this one: https://aur.archlinux.org/packages/visual-studio-code/

**Comment by joaomoreno** [comment]
Also, I noticed you mentioned the insiders build. When renaming the folders, make sure you also rename the `-insider` ones. Did you try that?

**Comment by Thunkar** [comment]
Yes, everything I'm testing I repeat it with the insiders build making the appropriate changes to the folder names.

**Comment by joaomoreno** [comment]
Do you get the same behaviour when running a [plain vanilla Electron](https://github.com/electron/electron/releases/tag/v0.37.6)?

**Comment by Thunkar** [comment]
I'm going to test it ASAP and report back, but mind that I can run other Electron apps (such as [GitKraken](https://www.gitkraken.com/)) with no issue.

**Comment by joaomoreno** [comment]
Let's try to see if some other user owns your files... can you also run this over both folders we talked about?

```
ls -Rl | awk '{print $3}' | sort | uniq
```

It should only show your user in there. Otherwise, you can see which files don't belong to your user with:

```
ls -Rl | awk '{print $3"\t\t"$9}' | sort
```

**Comment by Thunkar** [comment]
Confirmed that plain electron works (on its own showhing the "drop your app here" dialog and also with a node app that I had lying around here) and the commands above only report my user.

**Comment by joaomoreno** [comment]
Alright... I'll get Arch linux installed. Anything else special about your system, that you recall?

**Comment by Thunkar** [comment]
I'm sorry you have to go through all the hassle =/. Here, this is the exact distro I use:

https://apricityos.com/

Should be pretty easy to get it up and running. Just mind that it doesn't have the latest version of pacaur by default, eveything else should be maxed out.

**Comment by joaomoreno** [comment]
Installed Apricity... everything seems to work ok. 😕

**Comment by Thunkar** [comment]
Well, must be something specific of my system/configuration...I'm going to try and debug/build it from source and report back if I find the root cause. In case nothing shows up, I'll close this ASAP.

Thanks a lot for the help, and sorry for the trouble!

**Comment by joaomoreno** [comment]
No worries, I'd definitely be interested in knowing what is happening. 👍

**Comment by cuganator** [comment]
This issue hasn't been updated in a while but I wanted to report that I have the exact same issue (on arch linux) and can provide any details you required to try and figure this out as I would love to use vscode again (worked up until the March release I believe and then it hasn't worked for me since).

**Comment by joaomoreno** [comment]
@cuganator Do you see any interesting messages? What if you run with `--verbose`? What do you see exactly?

**Comment by cuganator** [comment]
It is identical to the screenshots at the top of this issue by Thunkar when run by normal user (no GUI comes up) and root (works fine)

**Comment by msaadat** [comment]
Increasing the max watches solves the issue e.g. with 
echo fs.inotify.max_user_watches=524288 | sudo tee /etc/sysctl.d/40-max-user-watches.conf && sudo sysctl --system

**Comment by Tyriar** [comment]
Closing since the watch count issue is mentioned on the faq https://code.visualstudio.com/docs/setup/linux#_error-enospc
