### ISSUE TITLE
Is there a way for an extension to prompt to install another extension?

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#60135]
We're considering moving some functionality from the Dart extension into the Flutter one (which is currently essentially empty with a dependency on Dart). We'd like to be able to prompt users to install the Flutter extension if they open a Flutter project with only the Dart extension installed.

I saw `workbench.extensions.action.showExtensionsWithId` in the source, but I was unable to make it work. I was also unable to find a way to pass `vscode:extension/Dart-Code.flutter` to the `vscode.open` command.

Is there a way to have a button in a notification that would take the user to the marketplace view for an extension to allow the user to easily install it?

**Comment by egamma** [comment]
@DanTup have you tried to create an extension pack and to recommend this extension pack for .dart files? 

Not sure that we want to open the door to extensions to make recommendations. Currently extension recommendations are based on a market place look up, that is, if the user opens a file and there no language extension for this language installed, then do a lookup on the market place and recommend these extensions.

**Comment by DanTup** [comment]
> What you can do today is to include a link in a notification that opens the extension in the market place. 

That's what I've implemented, but it feels weird to send the user from VS Code to their browser to come back to VS Code.

> have you tried to create an extension pack and to recommend this extension pack

Yep, but the extensions are already dependant in the other way. We're trying to split functionality from the Dart extension to the Flutter extension (the Flutter extensions currently, and will always, depend on the Dart extension, since Flutter apps are written in Dart). Originally we only had DSart so all of the Flutter behaviour is in there; but we'd like to expose less Flutter things (eg. commands) for users that chose to only install Dart.

However, since today lots of people *only* have Dart installed and it all works for Flutter, we need to guide them to install the Flutter extension before we start migrating any functionality.

I understand if this is an uncommon request and you don't want to provide it (so feel free to close if you're unlikely to do it) - it was more of a question about whether I could currently do better before I ship the version with a button to open the website. I thought maybe the command I mentioned was usable and I was just calling it wrong.

Thanks!

**Comment by Eskibear** [comment]
> I was also unable to find a way to pass vscode:extension/Dart-Code.flutter to the vscode.open command.

@DanTup , I'm able to pass it to `vscode.open` in v1.36, but it doesn't work for VS Code Insider. The url is always opened in VSCode Stable version if I have both installed.

**Comment by DanTup** [comment]
@Eskibear there's a command that allows you to install extensions now:

```ts
vs.commands.executeCommand("workbench.extensions.installExtension", flutterExtensionIdentifier);
```

We prompt the user, and if they  agree to install it, we just call that now.

(@egamma I think this issue is handled by `workbench.extensions.installExtension` now, so probably it doesn't need anything new?)
