### ISSUE TITLE
Breakpoint set but not yet bound (Issue #625) still exists

### ISSUE THREAD

**Issue by rafaelbdb** [Microsoft/vscode#60139]
Issue Type: <b>Bug</b>

VSCode version 1.27, and the breakpoint issue is not solved yet.

I try to set breakpoints (clicking on the red dots), but when I run the debugger, it says "Breakpoints set but not yet bound".

-------------

Same as issue #625:
https://github.com/Microsoft/vscode-react-native/issues/625

I'm creating this new issue acording to #625's last comment by ruslan-bikkinin.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-6300 Six-Core Processor              (6 x 3516)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.98GB (8.28GB free)|
|Process Argv|C:\Users\rafae\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
laravel-blade-spacer|aus|1.0.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.6.0
vscode-quick-select|dba|0.2.7
gitlens|eam|8.5.6
vscode-html-css|ecm|0.2.0
EditorConfig|Edi|0.12.4
vscode-npm-script|eg2|0.3.5
php-debug|fel|1.12.6
php-intellisense|fel|2.3.5
search-node-modules|jas|1.3.0
react-vscode-extension-pack|jaw|0.4.0
php-cs-fixer|jun|0.1.85
MagicPython|mag|1.1.0
php-namespace-resolver|Meh|1.1.0
vscode-language-babel|mgm|0.0.20
vscode-language-pack-pt-BR|MS-|1.27.2
python|ms-|2018.8.0
vsliveshare|ms-|0.3.735
debugger-for-chrome|msj|4.10.2
php-docblocker|nei|1.6.0
laravel-blade|one|1.18.0
laravel-extension-pack|one|0.4.0
laravel5-snippets|one|1.5.0
material-icon-theme|PKi|3.6.0
java|red|0.32.0
LiveServer|rit|5.1.1
sass-indented|rob|1.4.9
laravel-artisan|rya|0.0.22
todotasks|san|0.5.0
code-settings-sync|Sha|3.1.2
sort-lines|Tyr|1.7.0
vscode-java-debug|vsc|0.13.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.9.0
vscode-maven|vsc|0.11.0
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.7.1
ReactSnippets|xab|2.2.1

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
vscode-react-native

**Comment by rafaelbdb** [comment]
@isidorn Thanks, but I don't have such extension. 
Already tried to disable 'react-vscode-extension-pack' and 'ReactSnippets', but had no effect. 
Also: My VSCode has just updated to version 1.28.0, and there was no effect either. 
Problem persists!
