### ISSUE TITLE
Store plugin activated/deactivated in .vscode/plugins.json

### ISSUE THREAD

**Issue by muuvmuuv** [Microsoft/vscode#60132]
I would like to activate and deactivate some plugins for different projects. I know this is already possible within the extensions tab, but I would like to control this by a file. 

This feature would be very useful for coding with others in my team. So their VS Code would not load any PHP extension in a js project but still for other projects.

The file would be stored in `.vscode/plugins.json`

There could be an option to enabled/disable this behaviour, like: `vscode.enableExtensionHandlingByFile` and inside is an array of allowed extension authors or just a `true/false`.

Another option would be that VS Code is asking the user to install the extensions the project want to activate. Something like `vscode.enableExtensionInstallByFile`

> This is just a performance feature

**Comment by egamma** [comment]
@muuvmuuv  VS Code already activates extensions lazily by file type. So unless a user opens a .php file the PHP extension will not be activated.  You can verify this using the command `Developer: Show Running Extensions`. 

It can happen that an extension defines that it wants to be activated on start, but this is an issue of the extension and the extension should improve its behavior.
