### ISSUE TITLE
@fileoverview auto-completes to @fileOverview

### ISSUE THREAD

**Issue by mprobst** [Microsoft/vscode#60148]
Issue Type: <b>Bug</b>

When typing `/** @fi[ ]` in a TS file, VS Code auto-completes to `@fileOverview` (note the camel case). That's wrong, there's only `@file` or `@fileoverview`:
http://usejsdoc.org/tags-file.html

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:04:11.329Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -g .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.39
g3|eva|0.0.1
vscode-clangd|llv|0.0.6
python|ms-|2018.8.0
Go|ms-|0.6.90
debugger-for-chrome|msj|4.10.2
remote-vscode|raf|1.1.1
java|red|0.32.0
final-newline|sam|0.3.2
rewrap|stk|1.9.1
vscode-java-debug|vsc|0.13.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.9.0
vscode-maven|vsc|0.11.0
clang-format|xav|1.6.2
vscode-proto3|zxh|0.2.1

</details>

**Comment by mjbvz** [comment]
This is fixed in at least TS 3.1+ https://github.com/Microsoft/TypeScript/issues/25653:

![screen shot 2018-10-08 at 2 45 32 pm](https://user-images.githubusercontent.com/12821956/46635319-d5168580-cb08-11e8-8679-c8a77229b455.png)
