### ISSUE TITLE
Not responding PHP

### ISSUE THREAD

**Issue by jaume-solis** [Microsoft/vscode#6014]
- VSCode Version: 1.0.0
- OS Version:Windows 10

Steps to Reproduce:
Open PHP files
Few minutes later appears "Not Responding" message

**Comment by bpasero** [comment]
Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions`

**Comment by aeschli** [comment]
@jaume-solis See Ben's comment.

**Comment by aeschli** [comment]
Closing. Please add more information.
