### ISSUE TITLE
Git: Can't rebase continue or commit without modified files

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#60149]
From @schollii

1. While a branch is checked out, I do a `git rebase master` from command line (bash on ubuntu), and git hits a conflict. 
2. I then go to the vs code window where the folder is open. In the Git panel on the left, I can see the file listed under Merge with a C as status, and I can see there are conflict markers in the file. 
3. I resolve each conflict and save.
4. The file status changes to M once all conflicts resolved. 
5. Then I can click the plus sign on the file, and the file disappears from the Merge (perhaps a commit occurs then?). But a rebase continuation does not happen, there is nothing under Commit, and there is no option to do rebase continue.

**Comment by skprabhanjan** [comment]
@joaomoreno , can i work on this? :)

**Comment by matteobosc** [comment]
@joaomoreno thank you for referencing my issue, I'm going to subscribe to this thread :)

**Comment by matteobosc** [comment]
@skprabhanjan referring to the issue I've opened yesterday (#60275 ), the steps are a bit different. When I accept the current changes (so the file is identical to the version of the last commit) and I click on "+" sign the file disappears from "Merge Changes" but **doesn't** appear under "Staged Changes".

Hope you find this useful, thanks in advance

**Comment by skprabhanjan** [comment]
@matteobosc , I understand your point that the steps are different but I guess all these will be fixed under the same issue 
@joaomoreno should confirm upon this :)

**Comment by joaomoreno** [comment]
> Clicked on the "+" sign to stage the changes and it did disappear from the "Merge Changes" and came under "Staged Changes" (This did not run the commit )

You gotta resolve the changes by taking all changes from one side, in order for the file not to end up in the Staged Changes at all.

**Comment by skprabhanjan** [comment]
@joaomoreno , I will try understanding this more deeply.
Will get back to you in case on any doubts :)
Thanks!

**Comment by skprabhanjan** [comment]
@joaomoreno , is this approach good ?
Should we include something similar to https://github.com/Microsoft/vscode/blob/master/extensions/git/src/repository.ts#L775 in this function (https://github.com/Microsoft/vscode/blob/master/extensions/git/src/repository.ts#L764) ? 
Thanks !

**Comment by joaomoreno** [comment]
Well, no... the staging it correct. Staging those files will end up in a no-op. The problem is that you can't commit in VS Code without changes, although you'd want to continue the rebase/merge in this case. I will remove the `help wanted` label as this seems to be an advanced issue.

**Comment by dmstern** [comment]
I run into this issue several times. If I try to `continue` the rebase via terminal, it tells the following:

```
git rebase --continue
Applying: original commit message here
No changes - did you forget to use 'git add'?
If there is nothing left to stage, chances are that something else
already introduced the same changes; you might want to skip this patch.
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
```

If there *are* other changes than the conflicted files, VSCode can continue the rebase by just using the commit message box (<kbd>ctrl</kbd>+<kbd>enter</kbd>). Here that doesn't work.

The line that helped me was the following from the error log above:

```
You can instead skip this commit: run "git rebase --skip".
```

**My workaround:**
* add the resolved conflicting files by clicking the `+` 
* run `git rebase --skip` in the terminal

**Suggestion:**
So maybe a solution could be (analog to the `rebase` behavior) to tell VSCode to run `git rebase --skip` if there are no staged files in `rebase in progress` state when the user presses <kbd>ctrl</kbd>+<kbd>enter</kbd> in the commit box.

**Comment by kczx3** [comment]
I run into this from time to time as well.  Just this last time, I had to `git rebase --skip` all the commits locally.  Then I click the button to pull/push to my remote which then introduced the same merge conflicts that I had during my first --skip locally.  Resolved those and committed.  Then my pull/push commit counts changed from 3/22 to 0/23.  Clicked the button again to push all 23 back up to my remote.  Very confusing process though.

**Comment by balonik** [comment]
I know this is quite old, but currently when I hit this scenario and click the `commit` icon vscode asks me if I want to do an empty commit and if I confirm the rebase process continues.

**Comment by Woodz** [comment]
> I know this is quite old, but currently when I hit this scenario and click the `commit` icon vscode asks me if I want to do an empty commit and if I confirm the rebase process continues.

This only works if you have configured VS Code to allow empty commits

**Comment by reloxx13** [comment]
i still cannot continue the rebase wiht ui cause of empty commit. the old FR #6614 took 2 years, how long will it be this time

**Comment by dkyeremeh** [comment]
I encountered the same issue yesterday. The issue occurs primarily because vs code ui does not have an option that triggers `git rebase - - skip`. 


### Explanation 
When the user applies the current changes and saves during a rebase conflict, there's no changes to save so the file disappears from the staged area. When the user attempts to commit, the app runs `git rebase - - continue` in the background instead of `git rebase - - skip`. If empty commits is not enabled, this triggers the error described by @joaomoreno

To solve this, a skip button can be displayed next to the commit button during rebase. The skip button can also be used to trigger a skip when the user thinks the commit is no longer necessary

**Comment by gautam-borkar** [comment]
@skprabhanjan I encountered this issue while pulling the changes from the upstream. 

**Explanation** 
- Did a git pull of upstream to master. 
- Encounter a conflict
- Accepted all the current changes
- Clicked on `+` sign for staging changes
- File disappears

**Comment by lszomoru** [comment]
Steps to verify:
- Launch VS Code Insiders (2022-07-28 or later)
- Open a folder/workspace that contains a git repository
- Create a topic branch (ex: `rebase-test`)
- Switch back to the `main` branch, make a change in a file, and commit
- Switch to the topic branch, modify the same line in the same file, and commit
- From the command palette execute the `Git: Rebase Branch...` command and choose the `main` branch
  - Confirm that you get a notification that there is a conflict that you have to resolve
- Resolve the conflict by accepting all changes from the `main` branch
- After resolving the conflict, save the file, and click on the `+` action to stage the change
  - Confirm that the file does not appear any more in the "Source Control" view
- Click on the "Continue" action button
  - Confirm that the rebase operation completes

**Comment by reloxx13** [comment]
4 years later
