### ISSUE TITLE
Add popup when quitting if terminal is running a command

### ISSUE THREAD

**Issue by rsmith54** [Microsoft/vscode#60157]
When quitting VS Code, if there is a command running in the terminal, it would be great to have a popup show up asking "are you sure you want to quit" if there is a currently running process in an integrated terminal.  Right now, I sometimes use Code while waiting for a build, open another text file, and accidentally close the running build.

**Comment by usernamehw** [comment]
There is already one `"terminal.integrated.confirmOnExit": false,`, only it's not working too great... #23808
