### ISSUE TITLE
Intellisense, navigation (ctrl+click) stops working for react-native projects

### ISSUE THREAD

**Issue by miqmago** [Microsoft/vscode#6015]
- VSCode Version: 1.1.0-insider
- OS Version: 10.10.5

In a react-native project, in this issue https://github.com/facebook/react-native/issues/3099#issuecomment-163567498 it is suggested to follow this steps in order to avoid `../../../../..` paths in requires:

package.json:

```json
{
  "name": "@whatever"
}
```

(or without `@` it works too)
Then in your files you can load a package like this:

```javascript
import MyComponent from '@whatever/components/myComponent';
```

The problem with this is that navigation (ctrl+click), intellisense, etc. stops working

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#8528
