### ISSUE TITLE
Disabling extension does not remove it from activity bar

### ISSUE THREAD

**Issue by misolori** [Microsoft/vscode#60159]
Issue Type: <b>Bug</b>

Steps to reproduce
1. Disable VS Live Share extension
2. Reload
3. See that VS Live Share is still in the activity bar

Also seeing this from the context menu:
![image](https://user-images.githubusercontent.com/35271042/46622163-66bccd80-cade-11e8-8933-114c905f3bcf.png)

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-04T16:40:40.180Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.16GB free)|
|Process Argv|-psn_0_778430|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
(1 theme extensions excluded)

**Comment by usernamehw** [comment]
Duplicate of #60097

**Comment by sandy081** [comment]
@misolori I am not able to reproduce this. Can you please try with latest insiders and check if you can reproduce it again?

**Comment by misolori** [comment]
@sandy081 must've been fixed by something recently, can't repro anymore.
