### ISSUE TITLE
Wrong suggestions in extension search for @category when using @id

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#60166]
Issue Type: <b>Bug</b>

Copy and paste "@id:vscjava.vscode-java-" into the extensions search. Type `p` at the end.
You get suggestions for @category which doesn't make any sense

![image](https://user-images.githubusercontent.com/16890566/46625642-9ae9bb80-cae9-11e8-835e-09810d979a87.png)

VS Code version: Code - Insiders 1.29.0-insider (1358e903716cf77711493770d63dde1ea178a73e, 2018-10-08T05:16:11.119Z)
OS version: Windows_NT x64 10.0.17134

**Comment by egamma** [comment]
@ramya-rao-a please help me to assign this further given that the internship has ended.

**Comment by ramya-rao-a** [comment]
This would be me. I forgot to assign it. Thanks!

**Comment by ramya-rao-a** [comment]
Occurs only in Insiders 1.29 and not in Stable 1.28

**Comment by ramya-rao-a** [comment]
This is also fixed with https://github.com/Microsoft/vscode/commit/11cb54e1a98bca8bacf003d64a728a0f23ab9c41
