### ISSUE TITLE
Word wrapping turns automatically on and can't be turned off

### ISSUE THREAD

**Issue by imsedim** [Microsoft/vscode#6016]
- VSCode Version:1.0.0
- OS Version: Windows 10

Steps to Reproduce:
1. Create new file
2. Type a string longer than 300 characters - let's say 310 times character 'a'
3. Create new file (using ctrl+n)
4. Return to the first file (using ctrl+tab)
5. The line you've just typed is now wrapped on viewport width. "Toggle Word Wrap" command does not have any effect until you restart the VS Code.

**Comment by bpasero** [comment]
Maybe an extension like editorconfig?

**Comment by imsedim** [comment]
I tried to download VSCode insider build and run it without any extensions and could still reproduce the bug.

**Comment by alexandrudima** [comment]
The wrapping settings are getting an overhaul with #21262
