### ISSUE TITLE
1.29.0 Regression - CTRL + ` does not close terminal unless terminal is in focus

### ISSUE THREAD

**Issue by ajbowler** [Microsoft/vscode#60171]
- VSCode Version: 1.29.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open integrated terminal - I have it set to Git Bash in this case.
2. Place focus in the editor
3. CTRL + ` doesn't close terminal (this worked previously).
4. Put focus on terminal.
5. CTRL + ` closes the terminal.

**Comment by Astrantia** [comment]
Can reproduce.

**Comment by usernamehw** [comment]
https://github.com/Microsoft/vscode/issues/19400#issuecomment-423074454 ?

**Comment by Tyriar** [comment]
Yes this is by design
