### ISSUE TITLE
c# no work

### ISSUE THREAD

**Issue by inweblife** [Microsoft/vscode#60179]
Issue Type: <b>Bug</b>

c# no work and do not run, debug and more
scriptcs "c:\Users\ivan7\OneDrive\Работен плот\test\new.cs"
'scriptcs' is not recognized as an internal or external command,
operable program or batch file.

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3340M CPU @ 2.70GHz (4 x 2691)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (4.04GB free)|
|Process Argv|C:\Users\ivan7\OneDrive\Работен плот\test\new.cs|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
code-gnu-global|aus|0.2.2
vscode-django|bat|0.17.0
vscode-standardjs|che|1.2.3
vscode-eslint|dba|1.6.0
jupyter|don|1.1.4
python-extension-pack|don|1.4.0
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.39
vscode-great-icons|emm|2.1.44
php-debug|fel|1.12.6
php-intellisense|fel|2.3.5
code-runner|for|0.9.4
csharpextensions|jch|1.3.0
csharpfixformat|Leo|0.0.75
MagicPython|mag|1.1.0
code-beautifier|mic|2.1.0
vscode-clang|mit|0.2.2
HTMLHint|mka|0.5.0
vscode-language-pack-bg|MS-|1.28.2
python|ms-|2018.8.0
atom-keybindings|ms-|3.0.4
cpptools|ms-|0.19.0
csharp|ms-|1.16.2
Go|ms-|0.6.90
material-icon-theme|PKi|3.6.0
ruby|reb|0.20.0
LiveServer|rit|5.1.1
vscode-icons|rob|7.27.0
stylelint|shi|0.43.0
python|tht|0.2.3
vscodeintellicode|Vis|1.0.4
jinja|who|0.0.8
html-css-class-completion|Zig|1.17.1

(1 theme extensions excluded)

</details>

**Comment by inweblife** [comment]
Issue Type: <b>Bug</b>

c# no work and do not run, debug and more
scriptcs "c:\Users\ivan7\OneDrive\Работен плот\test\new.cs"
'scriptcs' is not recognized as an internal or external command,
operable program or batch file.

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3340M CPU @ 2.70GHz (4 x 2691)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (4.04GB free)|
|Process Argv|C:\Users\ivan7\OneDrive\Работен плот\test\new.cs|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
code-gnu-global|aus|0.2.2
vscode-django|bat|0.17.0
vscode-standardjs|che|1.2.3
vscode-eslint|dba|1.6.0
jupyter|don|1.1.4
python-extension-pack|don|1.4.0
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.39
vscode-great-icons|emm|2.1.44
php-debug|fel|1.12.6
php-intellisense|fel|2.3.5
code-runner|for|0.9.4
csharpextensions|jch|1.3.0
csharpfixformat|Leo|0.0.75
MagicPython|mag|1.1.0
code-beautifier|mic|2.1.0
vscode-clang|mit|0.2.2
HTMLHint|mka|0.5.0
vscode-language-pack-bg|MS-|1.28.2
python|ms-|2018.8.0
atom-keybindings|ms-|3.0.4
cpptools|ms-|0.19.0
csharp|ms-|1.16.2
Go|ms-|0.6.90
material-icon-theme|PKi|3.6.0
ruby|reb|0.20.0
LiveServer|rit|5.1.1
vscode-icons|rob|7.27.0
stylelint|shi|0.43.0
python|tht|0.2.3
vscodeintellicode|Vis|1.0.4
jinja|who|0.0.8
html-css-class-completion|Zig|1.17.1

(1 theme extensions excluded)

</details>

**Comment by egamma** [comment]
please file the issue against the C# extension.

@DustinCampbell fyi in case this is an issue with VS Code 1.28

**Comment by inweblife** [comment]
I do not undarstandWhat is the problem?c# no workHow to write?08.10.2018, 22:05, "Erich Gamma" <notifications@github.com>:Closed #60179.

**Comment by egamma** [comment]
@inweblife this repository is the issue repository for Visual Studio Code. Visual Studio Code does not include the support for C#. The support for C# is provided by this extension https://github.com/OmniSharp/omnisharp-vscode which has its own repository. Therefore please report issues against C# into this repository.

**Comment by egamma** [comment]
Also I´ve tested a hello world program in 1.28 and it worked as expected.

![image](https://user-images.githubusercontent.com/172399/46630900-02355900-cb46-11e8-8aa2-5f189af52f91.png)

**Comment by inweblife** [comment]
No work! It is a big problem
