### ISSUE TITLE
VCS sync buttons missing from status bar

### ISSUE THREAD

**Issue by DavSanchez** [Microsoft/vscode#60175]
Hello there!

I've been having this problem for quite a bit now, I was expecting to see it somehow fixed by the recent update but it didn't happen.

The thing is, the icons/buttons for Git/VCS remote syncing are missing, replaced by a vertical white line that seems out of place. Attaching an image:

<img width="136" alt="VCS buttons missing" src="https://user-images.githubusercontent.com/11422515/46627052-2175bb80-cb31-11e8-9003-54b6c9bab5a7.png">

I don't know what I did to cause it, so I can't replicate the issue in other computer installations where the status bar looks fine (even with the same repositories cloned from remote and opened). I'm running the OS X, non-insiders version.

**Edit for more info:** today I installed the insiders version (first time ever) and the problem appears there as well. Before doing that, a couple of days ago I tried uninstalling and reinstalling the non-insiders version, to no avail.

Does anyone know where to start looking, or a way to _reset_ the status bar views?

Thank you!

**Comment by joaomoreno** [comment]
Do any of the git features work?

**Comment by DavSanchez** [comment]
Yes! I can review modified files and make commits through VS Code's graphical interface (I mean selecting the SCM option in the activity bar). Pushing and pulling though requires using the command line.

**Comment by DavSanchez** [comment]
**Update**

Well, I don't know what's happening, but it is somehow _fixed_. I cloned a new repository just now and opened in VSCode (via the command `code .` in my terminal emulator). It opened in a non-maximised window and the problem was gone from there! However, opening the old repositories make the problem appear again no matter the window size.

Attaching image of a Python repo in a maximised window and a Haskell repo in a smaller window over the former. Note that both repositories have a remote repo (Python's remote is private on GitLab, [Haskell's on GitHub](https://github.com/haskell/haskell-ide-engine)), so the sync icon should be in both and not just in the Haskell one (where I guess I wouldn't be able to pull anything even if I wanted, since it's not a fork!).

<img width="263" alt="screen shot 2018-10-09 at 20 33 42" src="https://user-images.githubusercontent.com/11422515/46694183-e2646a80-cc03-11e8-98a0-8ae12234c230.png">

The first image that I uploaded in this thread comes from a C++ repo, where the problem of the icons missing and the white vertical line still persists even opening it after both former repos.

Hope I explained myself...

**Comment by joaomoreno** [comment]
What does `git rev-parse --symbolic-full-name master@{u}` return on the broken repository?

**Comment by DavSanchez** [comment]
Putting the command output in some of my repos:

- TeX repo (broken, has remote): `fatal: upstream branch 'refs/heads/master' not stored as a remote-tracking branch`.
- C++ repo (broken, does not have remote): `fatal: no upstream configured for branch 'master'`
- Python repo (broken, has remote): `fatal: upstream branch 'refs/heads/master' not stored as a remote-tracking branch`.
- Multilanguage repo (not broken, has remote): `refs/remotes/origin/master`.
- Haskell repo (not broken, has remote): `refs/remotes/origin/master`.

We got a clear pattern here. If it helps, the TeX, the Python and the multilanguage repos where pushed directly to private GitLab repos via the command `git push --set-upstream https://gitlab.example.com/namespace/nonexistent-project.git master` (substituting the URL of course), which automatically creates a new project in my GitLab.com account.

I don't know what is the deal with the C++ repo though, but I guess it has nothing to do with specifying a remote nor pushing it anywhere, since I did not do any of those things in the first place.

**Comment by joaomoreno** [comment]
The white line is irrelevant to this, it's a rendering glitch for which we have another issue to track.

As you have figured it out, the sync button only works if there's an upstream branch configured, so I'll close this for now, since all you have to do is set up an upstream branch.
