### ISSUE TITLE
"Gulp not found" after running `npm install ` in console

### ISSUE THREAD

**Issue by wallyzielinski** [Microsoft/vscode#60173]
After installing a node package from the terminal ( `npm install {package}` ), Visual Studio Code fails to find the local installation of gulp, and this error is thrown:
`Local gulp not found in C:\... Try running: npm install gulp`

Even re-running `npm install gulp-cli` or `npm install gulp-cli -g` does not always seem to resolve the issue. I usually have to delete node_modules folder and run a full `npm install` before the issue resolves. This, unfortunately, doesn't always help in the event the package I'm installing isn't part of the package.json (for instance, if I'm testing a new package for a company boilerplate).

- VSCode Version: 1.28.0
- OS Version: Windows 10 (1803)

Steps to Reproduce:

1. Run a gulp task from the vscode terminal
2. Install a new package using `npm i` or `npm install`
3. Try to run the same gulp task in vscode terminal

Other info, if it helps debug:
I have user settings set to override the default integrated terminal's `cwd` (current working directory). 

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by Tyriar** [comment]
This is either an issue with your environment (gulp needs to exist on your PATH in order to be found), or your node setup.
