### ISSUE TITLE
Integrated terminal with git bash is getting some errors on international keyboards

### ISSUE THREAD

**Issue by kleber-swf** [Microsoft/vscode#60177]
After the September's update the integrated terminal started to act weird when using git bash on Windows .
This is my setup:
* Windows 10
* VSCode (September 2018)
* Git bash as the integrated terminal
* Brazilian ABNT2 keyboard layout

Inside the integrated terminal, while typing a command, I accidentally typed the `´` character. I erased it but when I pressed Enter to execute it, the character was still there (sort of).

```bash
$ cordova platform add browser
Cordova does not know ´platform; try `cordova help` for a list of all the available commands.
```

```bash
$ cordova platform add browser
Cordova does not know Âplatform; try `cordova help` for a list of all the available commands.
```

```bash
$ cordova platform
bash: cordovaa: command not found
```

Steps to reproduce:
1. start typing a command inside the integrated terminal (with git bash)
2. type an accent character (with a keyboard layout of a language that accepts accents in letters, like Portuguese, Spanish or French)
3. type other letters in front of the accent character
4. erase the command up to the accent character
5. type the command correctly and press enter

Things to note:
* Git bash alone works as expected
* Other terminal integrations work too (PowerShell and Cmd)
* US Keyboard layout also works

---
VSCode info:
```
Version: 1.28.0 (user setup)
Commit: 431ef9da3cf88a7e164f9d33bf62695e07c6c2a9
Date: 2018-10-05T14:58:53.203Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

**Comment by Tyriar** [comment]
This should hopefully improve with the adoption of conpty, see https://github.com/Microsoft/vscode/issues/45693
