### ISSUE TITLE
Automatic Updates not automatic

### ISSUE THREAD

**Issue by gggustafson** [Microsoft/vscode#60182]
I am using the following VS Code on Windows 7 SP1:

```
Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:43:53.668Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64
```
I have "update_channel":"default" so it should have upgraded automatically to 1.27 and now to 1.28. But it did not. Thoughts?

**Comment by joaomoreno** [comment]
What happens if you click the gear in the bottom left corner and choose `Check for updates...`?

**Comment by gggustafson** [comment]
Unfortunately, when the gear icon is clicked, the following is displayed:

```
Command Palette...
---------------------
Settings
Keyboard Shortcuts
Manage Extensions
---------------------
User Snippets
---------------------
Color Theme
File Icon Theme

```
No "Check for updates..."!

**Comment by gggustafson** [comment]
I found that the following procedure works:

Go to [Visual Studio Code](https://code.visualstudio.com).
Choose Updates from the menu. 
Click on the Download button to the far right in the menu.
Click on the download you want.
