### ISSUE TITLE
Pylint undefined property PyQt5

### ISSUE THREAD

**Issue by angelhdz** [Microsoft/vscode#60189]
Pylint throws error of undefined PyQt5 modules (and maybe other modules installed by pip), but when debugging/building the Python app it works fine and I get code hint/auto-complete.

Tried to set the path to the site_packages but no success. Tried to install another version of PyLint but apparently I have the latest one.

Read and read on Google and didn't find the answer.

Note: I'm not using virtual env.

[https://marketplace.visualstudio.com/items?itemName=ms-python.python#review-details))](url)

**Comment by egamma** [comment]
Please file the issue against the python extension

**Comment by angelhdz** [comment]
Thank you?

If I posted here it's because no one answer me in the extension's forum/support.
This is the  extension suggested by VS Code when working with Python. So at least point us in the right direction? The editor should have code hint and linter for each language by default. No extension required. Without these, the editor is just useless.
