### ISSUE TITLE
vscodebot not helpful

### ISSUE THREAD

**Issue by gggustafson** [microsoft/vscode#60186]
I opened a new issue regarding the failure of VS Code to automatically upgrade. I was advised by vscodebot that a number of similar issues were raised. Having visited each so called answer, I was still left with the question - why isn't VS Code automatically upgrading? I appears that vscodebot is too aggressive and rather than point to an answer, just dumps junk answers.  It needs to be fixed and my question needs to be answered!

**Comment by gggustafson** [comment]
If anyone is interested, I found that the following procedure works:

Go to [Visual Studio Code](https://code.visualstudio.com).
Choose Updates from the menu. 
Click on the Download button to the far right in the menu.
Click on the download you want.

**Comment by lramos15** [comment]
The duplicate detection has since been removed so the aggressiveness has been fixed.
