### ISSUE TITLE
shortcuts for snippets not showing up in today's insiders

### ISSUE THREAD

**Issue by johnpapa** [Microsoft/vscode#60188]
Issue Type: <b>Bug</b>

when i type snippet shortcuts, they stopped showing up as of today's insiders update. it worked yesterday. also works in today's release of stable vs code.

VS Code version: Code - Insiders 1.29.0-insider (1358e903716cf77711493770d63dde1ea178a73e, 2018-10-08T05:11:18.105Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.10
markdown-preview-github-styles|bie|0.1.3
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.20.0
vscode-eslint|dba|1.6.0
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.39
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.6.1
Angular1|joh|0.2.0
angular-essentials|joh|0.4.0
Angular2|joh|6.2.0
dotenv|mik|1.0.1
vscode-azureappservice|ms-|0.9.1
vscode-azurefunctions|ms-|0.11.0
vscode-cosmosdb|ms-|0.8.0
azure-account|ms-|0.4.3
azurecli|ms-|0.4.2
debugger-for-chrome|msj|4.10.2
angular2-inline|nat|0.0.17
vetur|oct|0.13.0
vscode-docker|Pet|0.3.1
material-icon-theme|PKi|3.6.0
polacode|pnp|0.2.2
vue-vscode-snippets|sdr|1.3.0
code-settings-sync|Sha|3.1.2

(1 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
Simple case works for me... @johnpapa Please provide reproducible steps

<img width="822" alt="screenshot 2018-10-09 at 08 45 44" src="https://user-images.githubusercontent.com/1794099/46651312-e199ed00-cb9f-11e8-9471-29da53679bf2.png">

**Comment by TheSolly** [comment]
Same problem here with the latest code insiders as of writing this on macOS 10.14, extension snippets stopped showing up at all.
installed a couple of React snippets extensions, and when creating a js file and writing the snippets prefix, nothing show up in the snippet Suggestions!

**Comment by jrieken** [comment]
>  extension snippets stopped showing up at all.

Ah, extension snippets. they seem avol...

**Comment by johnpapa** [comment]
Does this mean you know what the cause and fix is @jrieken ?

**Comment by jrieken** [comment]
Yeah, that's usually what closed bug means 🤓

**Comment by johnpapa** [comment]
Thank you. 

I asked because I didn’t see a comment explaining you fixed it.
