### ISSUE TITLE
[Integrated Terminal] Tab in dropdown doesn't update when switching tabs with keyboard shortcut

### ISSUE THREAD

**Issue by adeeb1** [Microsoft/vscode#60195]
- VSCode Version: 1.28.0
- OS Version: Ubuntu 18.04.1

After updating to VSCode 1.28.0, the dropdown on the integrated terminal that indicates which tab you are viewing does not update when keyboard shortcuts are used. When a new tab is created, the tab updates; however, it does not update consistently when the focus changes between tabs using the keyboard.

**Tab 1 (notice the "2:bash" - it should read "1:bash")**
![vs code - tab 1](https://user-images.githubusercontent.com/4312320/46632455-93351180-caff-11e8-85b8-bf326d6c9059.png)

**Tab 2**
![vs code - tab 2](https://user-images.githubusercontent.com/4312320/46632459-94663e80-caff-11e8-9a22-15253bd20a0b.png)

Steps to Reproduce:

1. Set up the following keyboard shortcuts in your `keybindings.json`:

```
{
    "key": "ctrl+left",
    "command": "workbench.action.terminal.focusPrevious",
    "when": "terminalFocus"
},
{
    "key": "ctrl+right",
    "command": "workbench.action.terminal.focusNext",
    "when": "terminalFocus"
},
{
    "key": "ctrl+t",
    "command": "workbench.action.terminal.new",
    "when": "terminalFocus"
}
```

2. Open the integrated terminal and focus on it
3. Press the `ctrl + t` keyboard combination to open a new integrated terminal tab
4. Switch back to the previous integrated terminal tab by pressing `ctrl + left arrow key`. Note that the dropdown still shows that you are on the second tab

Does this issue occur when all extensions are disabled?: **Yes**

**Other notes**

This is a high impact issue for me. My workflow involves having multiple tabs open, and I heavily rely on the tab numbers to set the context in which I am working.

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/59876
