### ISSUE TITLE
Extensions using lodash no longer load in Insiders (issue with global)

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode#60190]
Issue Type: <b>Bug</b>

This is a regression - it used to work fine in Insiders, and it still works fine in non-Insiders 1.27.2.

1) git clone https://github.com/Microsoft/vscode-cosmosdb.git
2) cd vscode-cosmos
3) npm install
4) load in vscode Insiders and press F5
!) Extension fails to activate due to error here:

node_modules\gremlin\node_modules\lodash\index.js:718:
    var arrayProto = Array.prototype, <<<<<<<<<<< Array is undefined
TypeError: Cannot read property 'prototype' of undefined
	at runInContext (C:\Users\stephwe\Repos\vscode-cosmosdb\node_modules\gremlin\node_modules\lodash\index.js:718:28)
	at Object.<anonymous> (C:\Users\stephwe\Repos\vscode-cosmosdb\node_modules\gremlin\node_modules\lodash\index.js:12320:11)
	at Object.<anonymous> (C:\Users\stephwe\Repos\vscode-cosmosdb\node_modules\gremlin\node_modules\lodash\index.js:12351:3)
	at Object.<anonymous> (C:\Users\stephwe\Repos\vscode-cosmosdb\node_modules\gremlin\node_modules\lodash\index.js:12353:3)
	at Module.t._initNodeRequire.i._compile (c:\Users\stephwe\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:16:65)

This appears to have to do with the definition of "global" inside module loading.  Here's the value of global in Insiders inside lodash:
![image](https://user-images.githubusercontent.com/6913354/46631838-73045300-cafd-11e8-80f6-924e0cfe70e8.png)
And here it's value in regular vscode 1.27.2:
![image](https://user-images.githubusercontent.com/6913354/46631881-93341200-cafd-11e8-839f-5caf94dc1eb9.png)

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:57:45.963Z)
OS version: Windows_NT ia32 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.73GB (18.23GB free)|
|Process Argv|C:\Users\stephwe\Repos\vscode-docker\.vscode-test\stable\Code.exe --folder-uri file:///c%3A/Users/stephwe/Repos/vscode-docker|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.39
vscode-antlr4|mik|2.0.4
vscode-azurestorage|ms-|0.4.2
vscode-cosmosdb|ms-|0.8.0
azure-account|ms-|0.4.3
csharp|ms-|1.16.2
vscode-docker|Pet|0.3.1

</details>

**Comment by DonJayamanne** [comment]
I believe this is the cause for Python Extension not loading as well #60196 (again related to global variable `Reflect` that's updated by `reflect-metadata`). 
I.e. issue with `global`

**Comment by StephenWeatherford** [comment]
Fixed for me, thanks!
