### ISSUE TITLE
Expanding debug variables

### ISSUE THREAD

**Issue by foobar8675** [Microsoft/vscode#6019]
- VSCode Version: 1.0.0
- OS Version:10.11.4

Steps to Reproduce: when debugging, there is an extra mouse click to open my variables. it would be nice if there were a keyboard shortcut or (better) if the variables were expanded by default.

https://www.youtube.com/watch?v=ttB2hH5vsdU&feature=youtu.be

if you look at this vid. expanding variables can get tedious after a while

**Comment by isidorn** [comment]
We are now auto-expanding elements in the repl that have children. This makes sense to me since if a user typed an expression in the repl he is interested to drill down inside that expression.

**Comment by foobar8675** [comment]
awesome. i'm not sure how to tell what commits are in the downloadable version? http://code.visualstudio.com/Download

**Comment by isidorn** [comment]
This issue is assigned to May which means it will come out with our may release - which usualy comes out early June (I know it is a bit confusing) :)
