### ISSUE TITLE
cmd-s in SCM Window does not commit file

### ISSUE THREAD

**Issue by bcatubig** [Microsoft/vscode#60193]
- VSCode Version: 1.28
- OS Version: OSX Mojave

Steps to Reproduce:

1. Open up a folder that has been initialized with a git repo
2. Modify a file
3. In the source control tab, type a message and press `cmd + s`

Does this issue occur when all extensions are disabled?: Yes

**Comment by bcatubig** [comment]
It appears this has been changed to `cmd + enter` 

xref: #42862

**Comment by joaomoreno** [comment]
You can configure that by overriding the keybindings for the `scm.acceptInput` command.
