### ISSUE TITLE
Feedback popup does not appear when zoomed in too much

### ISSUE THREAD

**Issue by dangerman** [Microsoft/vscode#602]
**Steps to reproduce**
1. Open VS Code and zoom in as much as possible.
2. Click feedback button ☺️
**Expected**
- Feedback popup appears, and is zoomed in along with everything else.
- There are scroll bars so you can see the whole popup.

**Actual**
- Feedback popup is not visible.
- Can tab into the feedback popup.
  - After tabbing into it, there are no scrollbars.
- This happens when the **height** of the popup is greater than that of the main text area (see screenshots).

**Before zoom**
![before_zoom](https://cloud.githubusercontent.com/assets/1149641/11385769/eddf97c6-9313-11e5-8c13-a818ed2a6ce9.PNG)

**After zoom**
![after_zoom](https://cloud.githubusercontent.com/assets/1149641/11385773/f9f30fd4-9313-11e5-9eea-bf2954468c87.PNG)

**Version**
Found in version 0.10.1
![image](https://cloud.githubusercontent.com/assets/1149641/11386027/c90014ce-9315-11e5-984f-553a0ee5c526.png)

**Comment by SofianHn** [comment]
We are actually removing send-a-smile all together. We will have a blog post soon after next release explaining our feedback channels now that we are OSS.

**Comment by SofianHn** [comment]
reopening this as the send-a-smile was pulled back into the Dec release. We are not fixing this bug for Dec though.
