### ISSUE TITLE
"Rejected cached data from file"

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#60203]
When debugging vscode built from master, it sometimes hangs on start. Whether it hangs or not, it prints this error a lot:

``` [Extension Host] Rejected cached data from file: /Users/roblou/Library/Application Support/Code - Insiders/CachedData/1358e903716cf77711493770d63dde1ea178a73e/labels-06252ff0bee9a4567f40865b7c480a61.code (at Object.ConfigurationOptionsUtil.validateConfigurationOptions.options.onNodeCachedData (/Users/roblou/code/vscode/out/vs/loader.js:309:33))
console.ts:134
[Extension Host] Rejected cached data from file: /Users/roblou/Library/Application Support/Code - Insiders/CachedData/1358e903716cf77711493770d63dde1ea178a73e/index-ba75381d72ed269d95213d3cebf6e1ea.code (at Object.ConfigurationOptionsUtil.validateConfigurationOptions.options.onNodeCachedData (/Users/roblou/code/vscode/out/vs/loader.js:309:33))
console.ts:134
[Extension Host] vscode-icons is active! (at activate (/Users/roblou/.vscode-oss-dev/extensions/robertohuertasm.vscode-icons-7.25.0/out/src/index.js:41:13))
console.ts:134
[IPC Library: Search] Rejected cached data from file: /Users/roblou/Library/Application Support/Code - Insiders/CachedData/1358e903716cf77711493770d63dde1ea178a73e/ipc.cp-88e888fd37eb83e448f36f36744c07c6.code
console.ts:134
[IPC Library: Search] Rejected cached data from file: /Users/roblou/Library/Application Support/Code - Insiders/CachedData/1358e903716cf77711493770d63dde1ea178a73e/fs-5375bbbde4e0a00b8c94c3f6a7a624e5.code
console.ts:134
[IPC Library: Search] Rejected cached data from file: /Users/roblou/Library/Application Support/Code - Insiders/CachedData/1358e903716cf77711493770d63dde1ea178a73e/polyfills-830fec48b9d7d625cb86a165bde6cf8e.code
console.ts:134
[IPC Library: Search] Rejected cached data from file: /Users/roblou/Library/Application Support/Code - Insiders/CachedData/1358e903716cf77711493770d63dde1ea178a73e/legacy-streams-5df9f3bd57e868c47805670375661e41.code
console.ts:134
[IPC Library: Search] Rejected cached data from file: /Users/roblou/Library/Application Support/Code - Insiders/CachedData/1358e903716cf77711493770d63dde1ea178a73e/processes-258a0012a6102821d14879092405b2ee.code
console.ts:134
[IPC Library: Search] Rejected cached data from file: /Users/roblou/Library/Application Support/Code - Insiders/CachedData/1358e903716cf77711493770d63dde1ea178a73e/decoder-33e38e835d55a34e247ce5ecaf298bb5.code
console.ts:134
[Extension Host] Problems writing cached data file: /Users/roblou/Library/Application Support/Code - Insiders/CachedData/1358e903716cf77711493770d63dde1ea178a73e/index-ba75381d72ed269d95213d3cebf6e1ea.code (at Object.ConfigurationOptionsUtil.validateConfigurationOptions.options.onNodeCachedData (/Users/roblou/code/vscode/out/vs/loader.js:312:33))
console.ts:134
[Extension Host] Error: ENOENT: no such file or directory, unlink '/Users/roblou/Library/Application Support/Code - Insiders/CachedData/1358e903716cf77711493770d63dde1ea178a73e/index-ba75381d72ed269d95213d3cebf6e1ea.code' (at Object.ConfigurationOptionsUtil.validateConfigurationOptions.options.onNodeCachedData (/Users/roblou/code/vscode/out/vs/loader.js:313:33))
```

I didn't pull, I think this happened after updating Insiders. So it seems that OSS is trying to read cached data from the Insiders cached data directory?

**Comment by jrieken** [comment]
> So it seems that OSS is trying to read cached data from the Insiders cached data directory?

That is very, very unlikely... We always use the `userDataPath`

**Comment by jrieken** [comment]
@roblourens Can you update the steps? What exactly are you doing? Also, check the `CachedData` dirs in `~/Library/Application Support/Code - OSS/CachedData` and `~/Library/Application Support/Code - Insiders/CachedData`

**Comment by roblourens** [comment]
The steps were literally just 1. launch code.sh 2. see the errors, but today it seems to be working fine.

**Comment by jrieken** [comment]
hm, please keep an eye open...

**Comment by roblourens** [comment]
Actually it does still happen.

- Run Launch VS Code config
- See errors

It actually seems like it only happens when debugging vscode, not when just running code.sh. So that's weird, let me know how I can help debug

**Comment by roblourens** [comment]
Do you not see this? I see the error output on windows and mac. I don't think I've seen it hanging again recently so that must be unrelated.

**Comment by jrieken** [comment]
> Do you not see this? I see the error output on windows and mac

No, I use `scripts/code.sh` from the console, not via a launch config. What puzzles me is that we don't seem to set `VSCODE_DEV` when running via F5. How does the launch config work? It seems to never go through here: https://github.com/Microsoft/vscode/blob/1da6593b3df5e28db777d3daa0bed6ca30dc575a/src/main.js#L266-L273

**Comment by jrieken** [comment]
yeah, the config is a puzzle to me. I have added `--no-cached-data` to the runtime args but it seems to be without effect... @roblourens how does this work?

**Comment by roblourens** [comment]
The launch config just invokes `code.sh` so it in theory should be basically the same as running that in a terminal.

It looks like that file is copied to `out` with no sourcemap so you will have to set a bp in `out/main.js`

Also, change the "Launch VS Code" config to use `--inspect-brk` instead of `--inspect` otherwise there will be a race to attach and set the bp before that line runs.

When I do those two things I can hit breakpoints in that file.

**Comment by jrieken** [comment]
This is a problem with the launch config. The `VSCODE_DEV` variables doesn't make it to the *main* thread. Also the `--no-cached-data` flag doesn't make it to the process. Everything works fine with launching via `scripts/code.[sh|bat]` (with or without the `--no-cached-data` flag). 

I am not the right person to fix, understand, debug the launch config. I suggest to use the script straight from the command line while the config is broken

**Comment by roblourens** [comment]
What is VSCODE_DEV? I don't set that when running code.sh in the terminal either.

**Comment by roblourens** [comment]
It seems to be set for me, can you explain some more what the problem is?

![image](https://user-images.githubusercontent.com/323878/47100317-0e778100-d1ec-11e8-911f-2c118e75d4ed.png)

**Comment by jrieken** [comment]
> What is VSCODE_DEV? 

That is the env-variable that we use (in many places) to detect that we are running out of development. ~30 references to https://github.com/Microsoft/vscode/blob/f0101b07d43ddb8c62c8929d05e2db8bc19bac73/src/vs/platform/environment/node/environmentService.ts#L204

**Comment by roblourens** [comment]
Pushed a change to clear the `VSCODE_NODE_CACHED_DATA_DIR` if `--no-cached-data` is set, and added `--no-cached-data` to the launch config.

**Comment by roblourens** [comment]
I've also added a launch config for the main process, which makes it much easier to debug the main process' startup code. Now you can set a bp there, run `Launch VS Code (Main Process)` and hit it without the workaround of modifying the existing `Launch VS Code` config.

**Comment by roblourens** [comment]
@weinand, We apparently keep a list of vscode env vars to remove from the terminal environment. Should we do the same for debug adapters?

https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/terminal/node/terminalEnvironment.ts#L70

**Comment by chrmarti** [comment]
Seeing this in todays insiders build when I open the dev tools:

![image](https://user-images.githubusercontent.com/9205389/48253394-6d08d700-e407-11e8-8dd1-b0c727b88591.png)

**Comment by jrieken** [comment]
Did we rebuild from the same commit?

**Comment by chrmarti** [comment]
No, there are changes in from yesterday.

**Comment by jrieken** [comment]
Weird. The files are stored in a folder which name is the commit id of the build. @chrmarti Did you see this on first start after update or on a subsequent start?

**Comment by chrmarti** [comment]
I think it was on first start (not 100% sure).
