### ISSUE TITLE
Support RenameTextSpan from TypeScript

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#60204]
Add support for TypeScript 3.2's [`RenameTextSpan`]( https://github.com/Microsoft/TypeScript/pull/27356). This allows us to fix cases such as: https://github.com/Microsoft/TypeScript/issues/12007

Planning to pick up support in October but we'll only ship TS 3.2 in November. You can use typescript@next to try it out early.

**Comment by mjbvz** [comment]
For verification, upgrade your test workspace to see typescript@next and see Microsoft/TypeScript#12007 for example test case

**Comment by roblourens** [comment]
Awesome, I have wanted this
