### ISSUE TITLE
Git dialog freezes app

### ISSUE THREAD

**Issue by schollii** [Microsoft/vscode#60208]
- VSCode Version: 1.27.2 
- OS Version: ubuntu 18.04

Steps to Reproduce:

1. checkout a non-master branch of a repo, make changes to a file, commit changes (do not push)
2. attempt to change branch to master
3. The dialog grabs the mouse and freezes the GUI; even the use of mouse in other windows (say a terminal) is damaged

There are 2 ways out of this: 
1. force release of mouse grab (see e.g. https://unix.stackexchange.com/a/40472/269386); the Git dialog then becomes usable again so you can cancel the operation
2. kill VS Code (and start it again)

Does this issue occur when all extensions are disabled? Yes

**Comment by yuvanathan** [comment]
Issue is coming in v1.28.0  and ubuntu.
**Pressing Esc button or using Alt + F4 dismisses the dialog.** GUI becomes normal.

**Comment by joaomoreno** [comment]
What dialog appears?

**Comment by schollii** [comment]
@joaomoreno the Git dialog asking what to do, the dialog that freezes the app

**Comment by joaomoreno** [comment]
> the Git dialog asking what to do

Can you show me a screenshot?
