### ISSUE TITLE
Integrated Terminal does not bring up prompt, & also duplicates copyright info, etc.

### ISSUE THREAD

**Issue by anthcool** [Microsoft/vscode#60202]
- VSCode Version: 1.27.x and 1.28.0
- OS Version:  Windows 10 Enterprise Version 1809, build 17763.1
CPUs | Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)
-- | --
GPU Status | 2d_canvas: enabledchecker_imaging: disabled_offflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwarerasterization: enabledvideo_decode: enabledvideo_encode: enabledwebgl: enabledwebgl2: enabled
Memory (System) | 7.88GB (2.75GB free)
Process Argv |  
Screen Reader | no
VM | 0%

NO EXTENSIONS INSTALLED AT ALL.

Steps to Reproduce:

1.  Press CTRL + ~ to launch integrated terminal (Powershell) in Bottom position (or drag into view).
![image](https://user-images.githubusercontent.com/5133304/46635111-794ffa80-cb10-11e8-8491-2b3c9bb17fc1.png)
As shown above, terminal is scrolled to bottom of initial space given.  Can't see intro text w/copyright unless you scroll up.
2.  Scroll up to see intro text and copyright info.  See the following w/o PS prompt visible.
![image](https://user-images.githubusercontent.com/5133304/46635208-c502a400-cb10-11e8-805a-83c69d980676.png)
3  Start to type anything and get the following, with still no prompt visible, but entered text visible and executable:
![image](https://user-images.githubusercontent.com/5133304/46635233-e19edc00-cb10-11e8-896e-3f5919a32787.png)

4. Click Move to Right button. Exit integrated terminal.
5. Open integrated terminal again, now opening to the side.
6. Sometimes get the prompt to populate correctly, sometimes not.
7. Drag integrated terminal left and right to wrap intro text and copyright info a few times to see bug where text is duplicated...  See below effects:
![image](https://user-images.githubusercontent.com/5133304/46635327-422e1900-cb11-11e8-905f-a51e094661a1.png)

Please fix this soon.  The integrated terminal still works, but really buggy.   It's happening on my colleagues work PC too.

Thanks,
anthcool

**Comment by xenogew** [comment]
I think I got a same issue.
`VS Code: 1.28.0; 64 bits`
`OS: Windows 10.0.17763.1`

![vscode-terminal-cursor-weird](https://user-images.githubusercontent.com/756484/46646346-baa1e200-cbc4-11e8-9873-0f82f438bea9.png)

From the image attached, with integrated terminal with `cmd`, the cursor started in the weird place. Even it can call the command then it will locate at the proper place (behind `C:\...> [cursor position]`.

**Comment by romanoledergerber** [comment]
Same Issue !

VS Code 1.28.0; 64 bits
OS: Windows 10 Pro; 64 bits 1809 update (10.0.17763.1)

**Comment by erashov** [comment]
I've got the same bug!

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/57803
