### ISSUE TITLE
Custom icons should be allowed for all icon sizes

### ISSUE THREAD

**Issue by musm** [Microsoft/vscode#60200]
Thanks for adding custom icon support, but why can't we have custom file icons for all the sizes? Right
now this feature is almost useless since the file icon size has to be *massive* (**at a size I never use**) to be visible. 

See how large the icons have to be, to become visible
![f](https://user-images.githubusercontent.com/4319522/46627440-7f41dd80-cb08-11e8-8976-6c9302acd5a5.gif)

The current rational is that the custom icons do not look good at small sizes, which means that different icons should be used  for different sizes, which is the standard approach and is just a technical issue.

**Comment by Astrantia** [comment]
Agreed. You really need massive icons to see the new icons now.

**Comment by misolori** [comment]
@bpasero I can work on adding them back to insiders this week

**Comment by bpasero** [comment]
Feel free to push / PR.

**Comment by misolori** [comment]
Verification steps:

1. Uninstall vscode, restart
2. Install vscode (if on Windows, check "Register Code as an editor for supported file types)
3. Set Code as the default for opening a file type:
   - Windows: Right-click on file > Open with > Choose another app > Code (check "Always use this app to open *filetype* files")
   - Mac: Right-click on file > Get Info > Open With > Code (click the "Change all" button)
4. Go to Finder/File explorer where the same file type exists and set view to "List"
5. Verify that the file type icon is shown (you might need to refresh your list view to see the update):

|Windows|Mac|
|---|---|
|![image](https://user-images.githubusercontent.com/35271042/47800895-53221280-dcea-11e8-92e7-e346815a91bf.png)|![image](https://user-images.githubusercontent.com/35271042/47800867-443b6000-dcea-11e8-8da7-3efa233c31de.png)|

**Comment by musm** [comment]
@misolori, is it available on version 1.28.2?

**Comment by misolori** [comment]
@musm this will be in for the 1.29 release, the verification steps are for the vscode team to verify for this week's testing.
