### ISSUE TITLE
Todo+ extension broken on Insiders

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#60206]
- VSCode Version: 1.29.0-insider (1.29.0-insider) `1358e903716cf77711493770d63dde1ea178a73e`
- OS Version: v10.13.5 

Steps to Reproduce:

1. Install the [extension](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-todo-plus) from the marketplace.
2. Notice that it's not working.
3. Open the devtools, there should be a message saying `Activating extension 'fabiospampinato.vscode-todo-plus' failed: Cannot read property 'prototype' of undefined.`.

Needless to say that the same version works on the latest stable release (v1.28.0).

**Comment by nealot** [comment]
https://github.com/Microsoft/vscode/issues/60168
