### ISSUE TITLE
Disable flipped/custom cursor for line numbers

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#60209]
On Linux, I'm using a relatively small [cursor theme](https://cn.pling.com/img/9/7/a/5/84b855075d1e843ead31a9fdb98b437868df.png) that has a black fill with a white border. When I hover over a line number vscode insists on displaying a larger cursor with a white fill and a black border. Furthermore, the cursor is actually flipped so there's a jarring animation every time I move my cursor over to the sidebar. I find this behavior odd and would appreciate if it could be disabled.

https://github.com/Microsoft/vscode/issues/362 is related.

I'm currently resorting to https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css for a solution.

If this is one of those ux things you guys want to keep consistent with VS then I'll just stick with the custom css, but I'll still think it's a strange feature.

**Comment by alexdima** [comment]
This has been removed since a while.
