### ISSUE TITLE
Alternative to double-click to close code lens

### ISSUE THREAD

**Issue by devuxer** [microsoft/vscode#60210]
Please allow something besides double-click to close code lens.

I often use code lens to make edits to my code, and one of my favorite editor shortcuts is double-clicking to select a word. The way it works now, I have to stop myself from double-clicking a word to prevent code lens from disappearing. Unfortunately, I frequently forget to do this. This requires me to return to the tab where I spawned code lens from in the first place and re-spawn it, then find my place again within the list of results.

This could all be avoided if code lens had some other shortcut that didn't conflict with a common editor shortcut.

**Comment by jrieken** [comment]
This actually exists since a long time as this setting: `editor.stablePeek`

**Comment by devuxer** [comment]
@jrieken, Ahh, cool, thanks. If only I had thought to search for "stablepeek"...
