### ISSUE TITLE
Refactoring (rename symbol) is broken in certain cases

### ISSUE THREAD

**Issue by DavidRigglemanININ** [Microsoft/vscode#6021]
- VSCode Version: 1.0.0
- OS Version: OS X Yosemite
- Language: TypeScript

Steps to Reproduce:

1. Paste the following code snippet into VS Code
```
export class Test {
    private static _meta = {
        foo: "string"
    };

    private p = Test._meta;

    private static test(me: Test) {
        var myTestVar = me.p.foo;
    }
}
```
2. Right click on foo on line 3 and select rename symbol
3. Change "foo" to "fooNew" and press enter
4. Expected: me.p.foo should be updated to me.p.fooNew
5. Actual: rename does not work leaving broken code that does not build

It may be worth mentioning that this code snippet is just a trivial example to highlight the problem. So in case you are wondering why anyone would want to do this, we do have a valid use case that's just too complex to put here. Also, Visual Studio handles the refactoring just fine.

**Comment by DavidRigglemanININ** [comment]
This may or may not be related but in case it is, I also have issues where the hover of the value of a property during debugging doesn't work. For example, hovering over "me" displays the value correctly, but hovering over "foo" in "me.p.foo" simply shows nothing. This is another thing that Visual Studio gets right.

**Comment by stereokai** [comment]
I have another issue with renaming symbols. Trying to refactor a class name in a Typescript file across a project, VSCode fails and alerts "No result."

```
class MyClass extends AnotherClass {
  constructor() {
    super();
  }

  // ...
}
```

<img width="618" alt="screen shot 2016-05-05 at 12 05 36" src="https://cloud.githubusercontent.com/assets/2685357/15039988/ba5ab856-12b9-11e6-99d8-c1162bcc59ba.png">

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#8526
