### ISSUE TITLE
`vsce publish`'s message about the 5 keywords limit is annoying

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#60214]
I often get the following message after running `vsce publish`: 

```
The keyword list is limited to 5 keywords; only the following keywords will be in your extension: (...).
```

This is getting quite annoying for me. 

I don't understand, why is the number of keywords even limited?

**Comment by joaomoreno** [comment]
Unfortunately, the limit is set. I suggest to reduce the number of keywords in your extension. How many do you have?

**Comment by fabiospampinato** [comment]
7, I don't want to remove them just to work around this. 

I mean this isn't really important, I could run `yes | vsce publish` instead of `vsce publish`, but couldn't `vsce` just be smarter and not prompt that if the resulting keywords didn't change since the previous release and the current?

**Comment by joaomoreno** [comment]
You do realize that saying `yes` will trim the list down to 5, right?

**Comment by fabiospampinato** [comment]
Yes I do.

I also have that list synchronised with GitHub, which doesn't have such limitation. As I said this isn't really important, just an annoyance.

**Comment by joaomoreno** [comment]
Would an environment var help in this case? `VSCE_IGNORE_KEYWORD_LENGTH`? Or not worth the hassle?

**Comment by fabiospampinato** [comment]
If there was one I would use it.

**Comment by joaomoreno** [comment]
Moved to https://github.com/Microsoft/vscode-vsce/issues/296
