### ISSUE TITLE
Allow global text search using the PCRE2 engine

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#60218]
This enables advanced regex features, although we can still only support features supported by the JS regex engine

More details: https://github.com/BurntSushi/ripgrep/blob/master/FAQ.md#how-do-i-use-lookaround-andor-backreferences

**Comment by skprabhanjan** [comment]
@roblourens , are you working on this ?

**Comment by roblourens** [comment]
yes

**Comment by weikinhuang** [comment]
@roblourens Negative lookbehind doesn't seem to be working with that flag:

![screen shot 2018-10-30 at 4 44 32 pm](https://user-images.githubusercontent.com/794658/47749402-76ee4580-dc63-11e8-8d28-f18e836a48f0.png)

According to pcre.org/current/doc/html/pcre2syntax.html#SEC19, that is the correct syntax for a PCRE2 lookbehind regex

**Comment by dwelle** [comment]
Can reproduce that both lookbehind/negative-lookbehind doesn't work (invalid regex) despite PCRE2 flag being enabled.

OS: Win7
Version: 1.29.0-insider (user setup)
Commit: 97ad72a02c351d6cde0fd32b41d9700a43e5964a
Date: 2018-10-31T06:19:46.141Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by weikinhuang** [comment]
Looks like lookbehind was shipped in chrome 62, see #52629 for status of updating to electron v3
