### ISSUE TITLE
Interrupt references code lens requests if user performs an action

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#60213]
**Repo**
1. With `"typescript.referencesCodeLens.enabled": true`
1. Load file that has lots of references that take a while to resolve
1. While the references are still coming in, request completions

**Bug**
We only return the completion result after the references requests are all resolved. This may take a little while.

**Root Cause**
VS Code calls `resolveCodeLens` for all visible references. This results in a number of requests being queued up against the TS server when we first load a file. Since VS Code's server communication queue is sequential and the TS server is single threaded, this means that any completions request  must wait for all of the references requests to process before it can be sent

Potential fix would be to introduce the concept of a lo-priority request that other requests move in front of. Lo-pri requests already in progress would not be cancelled, but this would keep us from waiting until all code lenses are resolved before continuing.

**Comment by ParkourKarthik** [comment]
Hi @mjbvz , I would like to pick this up. Might need some guidance.

**Comment by ParkourKarthik** [comment]
@mjbvz I tried loading a typescript file with more references after enabling `"typescript.referencesCodeLens.enabled"`, but I was able to do simple user actions before all the references being loaded.
What kind of user action would make a completion request? Also it would be helpful if you could provide a sample ts with more references (may be in vscode source itself).

**Comment by mjbvz** [comment]
To repo, just add a delay in https://github.com/Microsoft/vscode/blob/797161bd324200dcaf1cf297998a92b84c70ea9d/extensions/typescript-language-features/src/features/referencesCodeLens.ts#L20

The main point that needs to be updated to fix this issue is the request queue: https://github.com/Microsoft/vscode/blob/797161bd324200dcaf1cf297998a92b84c70ea9d/extensions/typescript-language-features/src/server.ts#L77

Instead of a generic `push`, the queue needs to have the concept of a 'priority', with normal priority requests moving in front of low priority ones like the references computations

**Comment by mjbvz** [comment]
Use a larger file such as `src/vs/editor/common/modes.ts` for verification
