### ISSUE TITLE
can't see detail of the  outline 

### ISSUE THREAD

**Issue by hulinfa** [Microsoft/vscode#60222]
before I updated it,we can saw the code outline(by using the pluge named code outline),after I  updated ,the out layer of the outline  still exist,but  the we can't see the datail (about methods or properties),like this:
![image](https://user-images.githubusercontent.com/20656670/46641966-165d7280-cba7-11e8-8cd9-52f359dbfe4e.png)

**Comment by egamma** [comment]
This is not the outline view that is bundled with VS Code. Please file the issue against the
