### ISSUE TITLE
Emmet only through TAB, you can not customize keyboard shortcuts

### ISSUE THREAD

**Issue by nailao** [Microsoft/vscode#60224]
Issue Type: <b>Bug</b>

Emmet only through TAB, you can not customize keyboard shortcuts

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz (4 x 3912)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (3.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|1.4.6
jquerysnippets|don|0.0.1
vscode-fileheader|mik|0.0.2
vscode-language-pack-zh-hans|MS-|1.28.2
vetur|oct|0.13.0
minapp-vscode|qiu|1.9.0
vscode-icons|rob|7.27.0
vscode-sass-format|sas|1.1.6
code-settings-sync|Sha|3.1.2
vscode-jumpy|wma|0.3.1

(1 theme extensions excluded)

</details>

**Comment by ramya-rao-a** [comment]
How did you try the customizing? Can you share your keybinding?

**Comment by nailao** [comment]
> How did you try the customizing? Can you share your keybinding?

![image](https://user-images.githubusercontent.com/19665552/46708568-ec24b700-cc71-11e8-8169-5cf772ff4242.png)

I have always been this setting, it will be invalid after upgrading to 1.28.

**Comment by ramya-rao-a** [comment]
I see it working in 1.28, but not in 1.29 Insiders.

Are you sure, its not working for you in 1.28?

**Comment by tamatebako** [comment]
I have the same trouble as you have.

**Comment by nailao** [comment]
I am sure that I can use it before I upgraded 1.28.

**Comment by ramya-rao-a** [comment]
Can you set `emmet.triggerExpansionOnTab` to true in your settings and try again?

**Comment by nailao** [comment]
> Can you set `emmet.triggerExpansionOnTab` to true in your settings and try again?

Thanks, finally resolved, but why would a default is false？

**Comment by ramya-rao-a** [comment]
tab is the most popular keybinding used for expanding emmet abbreviations. But tab is also meant for inserting an actual tab i.e `\t`. Therefore when the cursor is not next to an actual emmet abbreviation, we had to add the `\t`. Thats the history for introducing the setting `emmet.triggerExpansionOnTab`. When that is set to `true`, we do the fallback to actual tab when required.

So the keybinding for emmet has this setting in its `when` clause

![image](https://user-images.githubusercontent.com/16890566/46984387-c3e5ef80-d099-11e8-8647-60b0fdd2157c.png)

When you change the keybinding to something else, you will have to either update the when clause to remove the `config.emmet.triggerExpansionOnTab` part or you should set `emmet.triggerExpansionOnTab` to true in settings
