### ISSUE TITLE
Name of month missing on website's update notification banner

### ISSUE THREAD

**Issue by myfairsyer** [Microsoft/vscode#60225]
They grey bar/banner underneath the navigation, which always tells about the current VSC release on https://code.visualstudio.com/ currently lacks the word "september":

![image](https://user-images.githubusercontent.com/13559472/46643494-a89c5100-cb7c-11e8-8442-4eb8868a2ec7.png)

**Comment by gregvanl** [comment]
Fixed in vscode-website repo.
