### ISSUE TITLE
Debugger stopped working (context python)

### ISSUE THREAD

**Issue by sastrytumuluri** [Microsoft/vscode#6022]
- VSCode Version: 1.0.0
- OS Version: Ubuntu Mate 16.04 LTS

Error Text:
> Traceback (most recent call last):
>>   File "/tmp/tmp-158678DPRC7D7mLdu/visualstudio_py_debugger.py", line 1646, in loop cmd()
>>   File "/tmp/tmp-158678DPRC7D7mLdu/visualstudio_py_debugger.py", line 1918, in command_execute_code
>>    thread.run_on_thread(text, cur_frame, eid, frame_kind, repr_kind)
>>   File "/tmp/tmp-158678DPRC7D7mLdu/visualstudio_py_debugger.py", line 1246, in run_on_thread
>>    self.schedule_work(lambda : self.run_locally(text, cur_frame, execution_id, frame_kind, repr_kind))
>>   File "/tmp/tmp-158678DPRC7D7mLdu/visualstudio_py_debugger.py", line 1238, in schedule_work
>>    self.unblock()
>>   File "/tmp/tmp-158678DPRC7D7mLdu/visualstudio_py_debugger.py", line 1234, in unblock
>>    self._block_lock.release()
> RuntimeError: release unlocked lock

Steps to Reproduce: (*was working properly, no idea why it stopped*)

1. Try to debug a simple Hello World Python program (press F5 to start)
2. press F11 to Step-Into (error occurs right at the first line)

Tried deleting all /tmp/tmp-* files & directories (there were a huge number). Also found a number of /tmp/vscode-* directories. Deleted them as well and restarted vscode. Error persists.

**Comment by bpasero** [comment]
@weinand @isidorn fyi

**Comment by isidorn** [comment]
This looks like an issue with the vscode pyhton extension 
@sastrytumuluri can you please file the issue against https://github.com/DonJayamanne/pythonVSCode

**Comment by weinand** [comment]
@sastrytumuluri did you upgrade VS Code and python stopped working after the upgrade?
