### ISSUE TITLE
Extension Host is now responsive.

### ISSUE THREAD

**Issue by yandifao** [Microsoft/vscode#60223]
- Extension Name: configuration-editing
- Extension Version: 1.0.0
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:

**Comment by alete89** [comment]
Since 1.28.0 Extension host is getting unresponsive and responsive again a few seconds later. It's kind of annoying.

**Comment by percyF** [comment]
It's been happening to me also. 1.29.0 Insiders Edition. Has been going on for a while and it's annoying to have to keep clicking it off. 

Otherwise, the best editor out there.

**Comment by kieferrm** [comment]
Please have a look at https://code.visualstudio.com/updates/v1_28#_extension-host-unresponsive.
