### ISSUE TITLE
Double click window bar icon to close on Windows when using custom title bar style

### ISSUE THREAD

**Issue by GMMan** [Microsoft/vscode#60220]
Perhaps a little-known Windows feature carried over way back from I think around Windows 3.x is the ability to close a window by double clicking the window icon from the title bar. A single click opens the system menu, and the default action on that menu is close. Looks like with the custom title bar style, clicking on the icon no longer brings up the system icon and the default action is maximize/restore. It would be nice if the original behavior could be added back as an option.

**Comment by GMMan** [comment]
Welp, someone beat me to it. #58199

**Comment by waynebloss** [comment]
This is also a standard feature on many Linux desktop systems as I mentioned in 58199.
