### ISSUE TITLE
Portable mode not working 

### ISSUE THREAD

**Issue by eegod** [Microsoft/vscode#60231]
- VSCode Version: 1.28.0 (user setup)
- OS Version: Windows 10

Steps to Reproduce:

1. [Enable portable mode](https://code.visualstudio.com/docs/editor/portable#_enable-portable-mode) in v1.27.2
2. Update to v1.28.0
3. `data` folder is still in the Code's folder, but portable mode is not enabled. 
4. I have reinstalled v1.27.2 and everything works fine. 

Does this issue occur when all extensions are disabled?: No

**Comment by kieferrm** [comment]
@eegod, just to be sure, you enabled portable mode from the zip install, correct? That's the only supported configuration for portable mode. So, in step 2, you downloaded the 1.28 zip and you copied the data folder from your 1.27.2 zip install over to the 1.28 zip install?

**Comment by eegod** [comment]
@kieferrm, I just realised you have deprecated portable mode support for Windows installer. I tried ZIP archive and it goes fine. 
Thanks for your time!
