### ISSUE TITLE
Document selector match - unexpected result value

### ISSUE THREAD

**Issue by Sneezry** [Microsoft/vscode#60232]
We are trying to write a customized JSON language server for JSON-LD. **JSON schema is not enough for our scenario.[[why?](https://github.com/Microsoft/vscode/issues/56334#issuecomment-424376826)]**

However, we have an issue to make our customized JSON language server work correctly. When we register completion item provider, we use this document selector for our file:

```
{
  language: 'json',
  scheme: 'file',
  pattern: '**/*.interface.json'
}
```

**Firstly**, pattern doesn't work as expected:

```
const selector = {
  language: 'json',
  scheme: 'file',
  pattern: '**​/*.interface.json'
};

vscode.workspace.onDidOpenTextDocument(document => {
  console.log(vscode.languages.match(selector, document), document.uri.fsPath)
});
```

The output for code above is `0 c:\Users\zlhe\Desktop\test.interface.json`. **Obviously, `c:\Users\zlhe\Desktop\test.interface.json` should match `**​/*.interface.json`. I have no idea why the score is zero.**

**Secondly**, I learnt from [vscode source code](https://github.com/Microsoft/vscode/blob/c63c97c12848e85769e717209b73110e83c18ef6/src/vs/editor/common/modes/languageSelector.ts#L87) that the score would not be larger than 10. That is to say, no matter what we do, auto completion provider will be override by vscode built-in JSON language server.

That's a big problem to us. For example, JSON-LD has a `@id` field, when the user writes a JSON-LD document, we'd like to list `@id` as an option to let user select. However, only `$schema` is listed.

**Comment by jrieken** [comment]
> The output for code above is 0 c:\Users\zlhe\Desktop\test.interface.json. Obviously, c:\Users\zlhe\Desktop\test.interface.json should match **​/*.interface.json. I have no idea why the score is zero.

What is the *full* uri for that document? This might very well be a non-file scheme because the git extension creates virtual documents for keeping track of the original state.

> That is to say, no matter what we do, auto completion provider will be override by vscode built-in JSON language server.

No, it will not overridden but both completion providers will be asked at the same time and their results will be merged. 

So, I haven't seen a completion item provider here... Where is it and is it really not called?

**Comment by Sneezry** [comment]
@jrieken thanks for reply.

> What is the full uri for that document? This might very well be a non-file scheme because the git extension creates virtual documents for keeping track of the original state.

The full uri is `file:///C:/Users/zlhe/Desktop/test.interface.json` (not sure if this is what you mean). The file is not in a git repo, but just a single file. I open it with vscode directly. No folder or workspace opened in vscode.

> No, it will not overridden but both completion providers will be asked at the same time and their results will be merged.

It's not exactly on my side. If I remove the pattern from selector, my code will be reached in debug. However, if I add the pattern, my code will NOT be reached. Also, even my code is reached, the result is not merged.

Here's the detail:

My code:

```
vscode .languages.registerCompletionItemProvider({
    language: 'json',
    scheme: 'file'
}, {
    provideCompletionItems(document, position, token): vscode.CompletionList {
        var text = document.getText();
        var json = Json.parse(text);
        var offset = document.offsetAt(position);
        var stack = getContextFromOffset(json.value, offset);
        if (stack.length === 0 && json.value.valueKind === Json.ValueKind.ObjectValue) {
            const jsonValue = json.value as Json.ObjectValue;
            const keyList = ['@id', '@context', '@type', 'comment', 'contents', 'description', 'displayName', 'schemas'];
            const completionKeyList = [];
            for (const key of keyList) {
                if (!jsonValue.hasProperty(key)) {
                    completionKeyList.push(key);
                }
            }
            const completionItems = getCompletionItemsFromArray(completionKeyList);
            return new vscode.CompletionList(completionItems, true);
        }
    }
}, '"', '{');
```

The code logic is simple: provide a completion list when user type `"` or `{`.

When I type `"`, I can only get `$schema`, and result my code returns doesn't be merged:

![snipaste20181009_155355](https://user-images.githubusercontent.com/1621293/46654710-293e6a00-cbdc-11e8-86a4-77e3d5b77a20.png)

However, if I type `{`, I can see result my code returns:

![snipaste20181009_155418](https://user-images.githubusercontent.com/1621293/46654745-3ce9d080-cbdc-11e8-8887-85733c0caf15.png)


**Summary**

I have two problems:

1. Pattern doesn't work as I expect
2. Completion item is not merged

**Comment by jrieken** [comment]
@Sneezry Your pattern is bad, it contains an invalid character. Use `**/*.interface.json` instead

**Comment by jrieken** [comment]
> Completion item is not merged

Trust me, it is merged. We have many extensions that work like this. Make sure your item isn't filtered by providing a range with the completion item (don't trust the default word range in JSON) and make sure that the filterText (or label if skipped match what you want to insert)

**Comment by Sneezry** [comment]
It works after I set range, thanks @jrieken !
