### ISSUE TITLE
Debugger fails silently (Python)

### ISSUE THREAD

**Issue by sastrytumuluri** [Microsoft/vscode#6023]
- VSCode Version: 1.0.0
- OS Version: Ubuntu Mate 16.04 LTS

Steps to Reproduce:
1. Create a Hello World Python program, with a syntax error. 
2. Make sure the Debug Console is closed. 
3. Press F5 to start debugger

Get this notification at the top:
> [Error] Debug adapter process has terminated unexpectedly      [Close]

*If the Debug Console is open, sometimes (not every time) it shows the syntax error*

**Comment by bpasero** [comment]
@weinand @isidorn fyi

**Comment by isidorn** [comment]
This looks like an issue with the vscode pyhton extension.
@sastrytumuluri can you please file the issue against https://github.com/DonJayamanne/pythonVSCode

I will make sure on the vscode side to always show the debug console if there are errors.

**Comment by isidorn** [comment]
We are now always showing the console on errors in the debug.
Dup of #5870
