### ISSUE TITLE
1.27.2 update to 1.28 lost all settings & extensions

### ISSUE THREAD

**Issue by azagz** [Microsoft/vscode#60239]
Issue Type: <b>Bug</b>

i use portable 1.27.2, today vscode auto update 1.28, and i lost all settings & extensions. no error, no warn. what the f--k ???
win10 1809 update lost user data, vscode 1.28 update lost user data, what u want for us, microsoft!

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (12.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.28.2

</details>

**Comment by kieferrm** [comment]
@azagz sorry to hear that. Since you got auto-updated, you must have used Portable mode with the Windows Setup. This is not supported: https://code.visualstudio.com/docs/editor/portable. You can only use Portable mode on the ZIP distribution.

/duplicate #57990
