### ISSUE TITLE
Issue Reporter: Issues arriving with "paste from clipboard" - Instructions or missing logic?

### ISSUE THREAD

**Issue by cleidigh** [microsoft/vscode#60237]
Many issues are coming in like
https://github.com/Microsoft/vscode/issues/60235
https://github.com/Microsoft/vscode/issues/60230

with only version information and the clipboard message.  Is it not clear for people to paste in the detailed info?  we cannot transfer everything directly?  Maybe a warning message to the user before submission?

**Comment by RMacfarlane** [comment]
Closing this since I've added an additional dialog prompt for this case - https://github.com/microsoft/vscode/issues/50659
