### ISSUE TITLE
org mode outline please.

### ISSUE THREAD

**Issue by dandananddada** [Microsoft/vscode#60249]
Plugin or integration, org mode outline please.
Vs code is pretty a wonderful edit tools, I usually organize my documents on it too. Hope can supply feature like org mode outline, It's quite convenient to manage document outlines.

**Comment by egamma** [comment]
pls see https://marketplace.visualstudio.com/items?itemName=tootone.org-mode

**Comment by dandananddada** [comment]
> pls see https://marketplace.visualstudio.com/items?itemName=tootone.org-mode

I used it , but it's a org mode todo plugin otherwise an outline~
