### ISSUE TITLE
Bottom status bar should match the theme

### ISSUE THREAD

**Issue by shanmukhananda** [Microsoft/vscode#60246]
**Pre-requisite:**
Current theme Dark+ (default dark)
**Action:**
View > Appearance > Show Status Bar
**Expected Behavior: (New Feature Request)**
Bottom status bar should be Dark colored
**Current Behavior:**
Bottom status bar is in Blue color

**Comment by egamma** [comment]
The status bar color is themable, so this depends on the theme.  I suggest to try out another theme that uses a different color. 

The Dark+ color scheme is established and we have no plan to change the coloring for now.
