### ISSUE TITLE
SCM: All File action buttons open comparison

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#60240]
Issue Type: <b>Bug</b>

VS Code version: Code - Insiders 1.29.0-insider (1358e903716cf77711493770d63dde1ea178a73e, 2018-10-08T05:16:11.119Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.87GB (19.75GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-snippet-pack|aka|0.1.5
Bookmarks|ale|9.1.0
pascal|ale|6.4.0
git-easy|bib|1.9.1
bracket-pair-colorizer|Coe|1.0.60
vscode-eslint|dba|1.6.0
gitlens|eam|8.5.6
tslint|eg2|1.0.39
git-project-manager|fel|1.7.1
file-icons|fil|1.0.16
vscode-npm|fkn|3.3.0
code-runner|for|0.9.4
macros|ged|1.2.1
innosetup|idl|1.2.0
csharpfixformat|Leo|0.0.75
start-git-bash|McC|1.2.1
python|ms-|2018.8.0
csharp|ms-|1.16.2
debugger-for-chrome|msj|4.10.2
vscode-icons|rob|7.27.0
git-add-remote|sam|0.0.2
code-settings-sync|Sha|3.1.2
vscode-hexdump|sle|1.7.0
gitblame|wad|2.4.4
JavaScriptSnippets|xab|1.7.1

(1 theme extensions excluded)

</details>

Steps to reproduce:

- make change to tracked file
- open SCM sidebar
- Keyboard or mouse to action icon on changed file
- any button opens comparison, cannot to other actions

See static screenshot after pressing "revert" button

![image](https://user-images.githubusercontent.com/25272315/46648191-e50e8380-cb61-11e8-9609-4c13f7cece3f.png)

**Comment by joaomoreno** [comment]
I can't understand the English in the following two points:

- Keyboard or mouse to action icon on changed file
- any button opens comparison, cannot to other actions

**Comment by cleidigh** [comment]
@joaomoreno 
Tonight's insiders update I just got appears to fix this.

Closing.
