### ISSUE TITLE
内存占用太高

### ISSUE THREAD

**Issue by kafeile7983** [Microsoft/vscode#60245]
Issue Type: <b>Performance Issue</b>

使用VSCODE打开android源码工程时占用内存过高

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (0.85GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe --folder-uri file:///i%3A/YZTG88_android60|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    86	  4176	code main
    0	    68	  1028	   gpu-process
    0	   191	  1712	   window (BlinkBluetoothManager.cpp - YZTG88_android60 - Visual Studio Code [管理员])
    0	     8	  1876	     electron-crash-reporter
    0	     9	  3504	     watcherService 
    0	    21	  4508	     searchService
    0	    85	  4704	     extensionHost
    4	  3284	  8036	       c:\Users\Administrator\.vscode\extensions\ms-vscode.cpptools-0.19.0\bin\Microsoft.VSCode.CPP.Extension.exe
    0	     4	  3212	         c:\Users\Administrator\.vscode\extensions\ms-vscode.cpptools-0.19.0/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.exe 8036 9
    0	    58	  5916	         c:\Users\Administrator\.vscode\extensions\ms-vscode.cpptools-0.19.0/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.exe 8036 8
    0	    55	  6164	         c:\Users\Administrator\.vscode\extensions\ms-vscode.cpptools-0.19.0/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.exe 8036 7
    0	     4	  6628	         c:\Users\Administrator\.vscode\extensions\ms-vscode.cpptools-0.19.0/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.exe 8036 6
    2	    73	  3480	   window (问题报告程序)
    0	    25	  4772	   utility
    0	    57	  4880	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (BlinkBluetoothManager.cpp - YZTG88_android60 - Visual Studio Code [管理员])
|    Folder (YZTG88_android60): more than 39188 files
|      File types: c(11162) h(8765) cpp(2040) txt(1973) mk(1644) cc(772)
|                  in(614) xml(536) sh(446) html(433)
|      Conf files: makefile(769) cmake(46) sln(12) settings.json(1);
```

</details>
<details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.1
markdown-nomnoml|amo|0.0.2
code-gnu-global|aus|0.2.2
vscode-markdownlint|Dav|0.20.0
vscode-great-icons|emm|2.1.44
vscode-javac|geo|0.2.5
CppSnippets|har|0.0.13
vscode-clang|mit|0.2.2
vscode-language-pack-zh-hans|MS-|1.27.2
cpptools|ms-|0.19.0
java|red|0.32.0
markdown-preview-enhanced|shd|0.3.8
vscode-java-debug|vsc|0.13.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.9.0
vscode-maven|vsc|0.11.0
debug|web|0.22.0

(1 theme extensions excluded)

</details>

**Comment by egamma** [comment]
Translation: 
Using VSCODE to open the android source project, the memory is too high.

This is a C++ workspace. Please file the issue against the C++ extension.

![image](https://user-images.githubusercontent.com/172399/46650855-52400a00-cb9e-11e8-820a-13a52f2d2a46.png)
