### ISSUE TITLE
No snippets suggestion beyond character 100 if not at end of line

### ISSUE THREAD

**Issue by jlelong** [Microsoft/vscode#60247]
This is a follow up on #58807.
The snippet suggestions mechanism stops working beyond character 100 if the cursor is not at end of line (the test in [snippetsService.test.ts#L264](https://github.com/Microsoft/vscode/blob/43c2879d2e365c4542126c36f3b75e4805d0d6f2/src/vs/workbench/parts/snippets/test/electron-browser/snippetsService.test.ts#L264) only checks it at the end of line)

- VSCode Version: 1.28.0

Steps to Reproduce:

1. Take the exemple from #58807
2. Try to trigger snippet completion between character 100 and the end of line

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
Oops, that was an oversight...
