### ISSUE TITLE
Markdown preview cannot support language highlights

### ISSUE THREAD

**Issue by saibing** [Microsoft/vscode#6024]
I am using vscode coding and write book.

**It was magical, the editor is the best I have ever used**

I hope the markdown preview can supports highlights the programming languages such as c++, c#, javascript,  python, go...

just like Atom's markdown preview plug-in does.
![python](https://cloud.githubusercontent.com/assets/5676390/14940483/eab6d5ce-0fa9-11e6-9356-2709c95063a6.png)

**Comment by ysle** [comment]
:+1:

**Comment by bpasero** [comment]
Should be ok now.

**Comment by saibing** [comment]
It's ok, thank your great work
