### ISSUE TITLE
“Remove from recent opened” takes no effect

### ISSUE THREAD

**Issue by liuyji** [Microsoft/vscode#60243]
Issue Type: <b>Bug</b>

1. On the Welcome screen click More... below Recent to open a recent list.
2. click × 
3. It should have remove some items but actually do nothing

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (3.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by kieferrm** [comment]
On Mac I see the following behavior:
- Ctrl+R
- remove one or more entries by clicking the `x`
- ESC
- Ctrl+R
-> the previously removed entries are back in the list

**Comment by bpasero** [comment]
@chrmarti picker related?

**Comment by ko-dever** [comment]
Any suggestion for a temporary workaround to avoid this bug ?

**Comment by jpotterm** [comment]
The list is stored in `~/Library/Application Support/Code/storage.json` which you can manually edit as a workaround.

**Comment by chrmarti** [comment]
A regression from https://github.com/Microsoft/vscode/issues/58131.

**Comment by bpasero** [comment]
@aeschli fyi

**Comment by ko-dever** [comment]
> The list is stored in `~/Library/Application Support/Code/storage.json` (on macOS) which you can manually edit as a workaround.

Thanks @jpotterm 😉 .

**Comment by orzv** [comment]
The list is stored in `C:\Users\xxx\AppData\Roaming\Code\storage.json` on Win10
