### ISSUE TITLE
Breaking: Todays Insider doesn't show files content anymore

### ISSUE THREAD

**Issue by kurtextrem** [Microsoft/vscode#60252]
- VS Code Version: Version: 1.29.0-insider (user setup)
Commit: c1100eff93b35dc220ce63e2ed0d5ace54259795
Date: 2018-10-09T06:54:02.898Z
Electron: 2.0.11
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
- OS Version: Win 10 x64, Fall update

Steps to Reproduce:

1. Launch VS Code
2. Open any file

Does this issue occur when all extensions are disabled?: Yes

**Comment by franta** [comment]
after latest update editor is still not working
