### ISSUE TITLE
Toolbars

### ISSUE THREAD

**Issue by L0CTAR0GAR** [Microsoft/vscode#60250]
Issue Type: <b>Feature Request</b>

Toolbars don't follow the theme color. White is good.

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 10.0.15063

**Comment by egamma** [comment]
>Toolbars don't follow the theme color. White is good.

VS Code does not have tool bars do you mean menu bars? Can you pls  include a screenshot of what you would like to see

**Comment by L0CTAR0GAR** [comment]
![tim 20181009145235](https://user-images.githubusercontent.com/41992918/46651670-5b979980-cbd3-11e8-8f7f-4cf6a14ce0b6.png)

**Comment by egamma** [comment]
@L0CTAR0GAR thank you for following up. This area is what we refer to as the menu bar. The color of the menubar is themable and can also be overwritten in the user settings.

**Comment by L0CTAR0GAR** [comment]
OK，thanks .
