### ISSUE TITLE
Wrong Cursor location when we typing faster

### ISSUE THREAD

**Issue by viniston** [Microsoft/vscode#60255]
Issue Type: <b>Bug</b>

When we keep typing fast suddenly the cursor location is automatically moving somewhere in the same file.

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.64GB (8.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
angular-material|1to|0.13.0
html-snippets|abu|0.2.1
ng-template|Ang|0.1.10
angulardoc-vscode|Ang|6.1.1
path-intellisense|chr|1.4.2
angular-schematics|cyr|1.8.1
vscode-simpler-icons|dav|1.6.5
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.39
vscode-great-icons|emm|2.1.44
prettier-vscode|esb|1.6.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
json2ts|Gre|0.0.6
angular2-switcher|inf|0.1.9
Angular2|joh|6.2.0
vscode-simple-icons|Lau|1.8.7
angular-extension-pack|loi|0.6.0
Angular2Tests|Mar|0.7.3
csharp|ms-|1.16.2
debugger-for-chrome|msj|4.10.2
ng-fortytwo-vscode-extension|NG-|0.0.9
material-icon-theme|PKi|3.6.0
typescript-hero|rbb|2.3.2
vscode-icons|rob|7.27.0
simontest|Sim|0.19.0
autoimport|ste|1.5.3
move-ts|str|1.11.3
Angular2|UVB|0.4.1

</details>

**Comment by egamma** [comment]
Please provide steps for how to report this issue, can you provide an animated GIF that illustrates the problem?
