### ISSUE TITLE
终端显示错误

### ISSUE THREAD

**Issue by yangmin4052** [Microsoft/vscode#60256]
终端使用gitbash，在执行命令git  log后，commit内容显示错误，显示为<E8><96><AA><E8><B5><84><E6><A1><A3><E6><A1><88><E6><A0><B7><E5><BC><8F>之类

**Comment by Tyriar** [comment]
@yangmin4052 what version of Windows are you on?

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/60428
