### ISSUE TITLE
Incorrect "convert to async function" refactoring

### ISSUE THREAD

**Issue by chrfrasco** [Microsoft/vscode#60257]
- VSCode Version: 1.28.0
- OS Version: macos 10.13.6

If/else is stripped out by convert to async refactor, and convert all to async does nothing

Steps to Reproduce:

1. Convert `bar` to async function

```
function foo() {
  return Promise.resolve(Math.random())
}

function bar() {
  return foo()
    .then(num => {
      if (num > 0.5) {
        return fetch("/big")
          .then(() => 'big');
      } else {
        return fetch("/small")
          .then(() => 'small');
      }
    })
    .catch(() => -1);
}
```
2. Get this

```
async function bar() {
  try {
    const num = await foo();
    await fetch("/big");
    return 'big';
    await fetch("/small");
    return 'small';
  }
  catch (e) {
    return -1;
  }
}
```

3. convert all to async does nothing

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#27641
