### ISSUE TITLE
YAML files show as blank

### ISSUE THREAD

**Issue by Klionheart** [Microsoft/vscode#60258]
Issue Type: <b>Bug</b>

- Open any YAML file.

Expected result: the file opens and is readable
Actual result: the file opens, but shows as blank.

VS Code version: Code - Insiders 1.29.0-insider (c1100eff93b35dc220ce63e2ed0d5ace54259795, 2018-10-09T06:54:02.898Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2760QM CPU @ 2.40GHz (8 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (3.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|40%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.5.6
terminal|for|0.0.10
python|ms-|2018.8.0
bash-beautify|sha|0.1.1

</details>

**Comment by egamma** [comment]
Cannot reproduce in the latest insiders Version: 1.29.0-insider (user setup)
Commit: 5bd6ebe2dbc4dee510699020a25f70a69784ce8c
Date: 2018-10-09T09:31:07.090Z
Electron: 2.0.11
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Please reopen if you can still reproduce the problem.

**Comment by Klionheart** [comment]
The latest build indeed seems to have it fixed. Thanks!
