### ISSUE TITLE
Frequent svn command attempts on file save

### ISSUE THREAD

**Issue by hxlnt** [Microsoft/vscode#6025]
- VSCode Version: 1.0.0
- OS Version: OS X El Capitan 10.11

Steps to Reproduce:
1. Save any file. (Seems to often pop up while editing unsaved settings.json, too.)

Note that this is on a fresh install of VSCode 1.0.0 on a new Mac without Xcode or developer tools installed. Not sure why changing settings.json would repeatedly try to initiate svn, though.

<img width="519" alt="screen shot 2016-05-01 at 1 43 17 am" src="https://cloud.githubusercontent.com/assets/9647195/14940588/f490775c-0f41-11e6-89c6-56103ae19ae2.png">

**Comment by bpasero** [comment]
Maybe an extension that causes this? 
Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions`

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
