### ISSUE TITLE
Allow searching in settings.json file

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#60259]
It seems like it's not currently possible to search your `settings.json` file. I just opened mine because I want to re-enable Git. I use the JSON view because I really can't get on with the new editor (it feels much more complicated than the JSON for just editing a few values).

I opened the file, hit Ctrl+F and typed `git`. This is what I saw:

<img width="1203" alt="screen shot 2018-10-09 at 8 42 01 am" src="https://user-images.githubusercontent.com/1078012/46653902-3721ca00-cb9f-11e8-8168-d7c97e72f3b2.png">

The search has only searched the left column. Even if I keep hitting `<enter>` to go through the results, it wraps around the left column. This appears to make it impossible to search in the right column (even if I put focus there, then hit Ctrl+F, it searches the left column) and I'm left to manually scroll through my settings.

In this case, I know I can search for `git.enabled`, but that's only because I remember the name of the setting. If I didn't, searching through all of the `git` settings when I know the one I want is right in the file on the right (and the only instance of `git`) is annoying.

**Comment by Muchiachio** [comment]
It works but you have to focus your right settings window and press `F3`.
I do agree that it should search in the focused window with the usual `CTRL+F`.

**Comment by DanTup** [comment]
Oh wow, that is confusing :/

**Comment by roblourens** [comment]
You can change the `settings.action.search` keybinding so it doesn't override the normal editor ctrl+f, or use a workaround like opening the replace widget. (ctrl+h on windows I think)

Feel free to open issues for whatever you find difficult with the settings UI.

**Comment by roblourens** [comment]
I don't plan to invest a lot in the split JSON editor, I think the workaround above is enough for now.
