### ISSUE TITLE
A link in setting/extension : "report a problem with this extension" (link to its github repo)

### ISSUE THREAD

**Issue by WiliTest** [microsoft/vscode#60251]
Someone told me the feature already exist. There is a link "repository" only on the explorer/extension/enabled. It would be intuitive to have a "report a problem with this extension" link in settings/extension/My-extension. Thanks!

**Comment by egamma** [comment]
The link is shown when you open 'Developer: Show Running Extensions'

**Comment by mjbvz** [comment]
We also now support reporting issues directly against extensions using the issue reporter
