### ISSUE TITLE
[Fuzzy text search] Search with "syntax synonyms" (simple quote = double quote, no spaces...)

### ISSUE THREAD

**Issue by maximelebastard** [microsoft/vscode#60264]
Hi !

> First of all, sorry if this is a duplicate. I was unable to find something similar with my own words. But I'm maybe not the first to request this.

On PHP or NodeJS, I sometimes perform searches to find the declaration of a variable (with a dynamic name) - or an array definition. The search varies in different syntaxes - in PHP for example:

`
$foo = "foo";
$foo = 'foo';
$foo='foo';
$foo =
    "foo";
`

or with arrays

`
$array = ['a','b','c'];
$array = ['a', 'b', 'c'];
$array=['a', 'b', 'c'];
`

Those examples exists in every language - all of them have "syntaxical synonyms".

It would be awesome to get an option on the search to search with those synonyms (simple/double quotes, spaces or not, backspace or not...)

**Comment by roblourens** [comment]
Unfortunately language-specific search features are not really practical
