### ISSUE TITLE
Copy All in search results no longer copies entire line

### ISSUE THREAD

**Issue by cultivatedvariety** [Microsoft/vscode#60260]
Issue Type: <b>Bug</b>

Previously, when selecting 'Copy all' from search results the entire line containing the matching text was copy. 

Now, only a portion of the line is copied.

Steps to Reproduce:

1. Ctrl+Shift+F to bring up search
2. Enter a term
3. Right click on results and select 'Copy All'
4. Paste into editor
5. Only a small portion of the line instead of the whole line is copied

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (6.96GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
dotenv|mik|1.0.1
csharp|ms-|1.16.2

</details>

**Comment by roblourens** [comment]
It should have a large portion of the line, but not necessarily the entire line. This is by design to avoid sending lots of text between processes.

**Comment by cultivatedvariety** [comment]
This is definitely a change in behaviour from https://github.com/Microsoft/vscode/issues/42120 

Only 35 characters are being copied. Prior to the latest update I had lines of over 100 characters copied in full.

**Comment by roblourens** [comment]
I think the max is something like 75 in 1.28... but it has actually changed again so you should get at least a couple hundred in 1.29 (next release)
