### ISSUE TITLE
Startup activation time

### ISSUE THREAD

**Issue by roroland** [Microsoft/vscode#60262]
- Extension Name: LiveServer
- Extension Version: 5.1.1
- OS Version: Darwin x64 17.2.0
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:
```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 4663,
		"activateCallTime": 3,
		"activateResolvedTime": 0,
		"activationEvent": "*"
	}
}
```

**Comment by jrieken** [comment]
@roroland what is this for?

**Comment by roroland** [comment]
Sorry, since last update of VS when I start the editor the extension manager says something like "Extension manager unresponsive".... then "Extension manager is responsive again", when I see the time of some of the extensions I use to start up running I assume it was due a bug with this last update or eventually with the extension

**Comment by roroland** [comment]
Any news about this? I get several extensions unresponsive messages every day. Is a known bug from VS or should be some extension I have installed ?
Thanks

**Comment by alexandrudima** [comment]
We have pushed an update where we no longer show the message. The root cause of the message is **always** an extension.
