### ISSUE TITLE
Debug dropdown isn't updated to reflect selected launch config with `workbench.action.debug.selectandstart` command

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#60261]
Issue Type: <b>Bug</b>

After running `workbench.action.debug.selectandstart` and selecting a launch config the Debug dropdown isn't updated to reflect the selected launch config -- even though it has become the "active" config -- e.g. the next time you press F5 it will run the last config selected by `workbench.action.debug.selectandstart`.

TBH, I would rather have `workbench.action.debug.selectandstart` not affect the "active" config at all -- meaning the "active" config would be what is in the dropdown rather than the last one run by `workbench.action.debug.selectandstart`

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 10.0.18252

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (15.05GB free)|
|Process Argv|c:\Users\Eric\code\codestream\vscode-codestream\codestream.code-workspace|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by isidorn** [comment]
I can not reproduce this with latest vscode insiders.
Can you repro with vscode insiders?

If yes, do you see the same behavior if you simple type `debug ` in the quick open and choose the debug configuration from there?

**Comment by eamodio** [comment]
I can't repo with today's insiders, only with 1.28.

**Comment by isidorn** [comment]
Then it is fixed in latest, and this is not something which we will fix for stable.
