### ISSUE TITLE
Ability to customise size of a custom view

### ISSUE THREAD

**Issue by csicky** [microsoft/vscode#60266]
Issue Type: <b>Bug</b>

The problem is that the Favorites side panel is growing in height after I close open files. Closing the files makes Open Editors side panel smaller, but should increase the height of the project view side panel not the height of Favorites. I know the Favorites panel comes from an extension, I am not sure if this should be reported there, or here.
Is there a way to freeze the height of a side panel?

https://www.useloom.com/share/ebc8bbb2c51540dc92dbe20dabd454da

Thank you.

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-04T16:47:36.731Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.87GB (7.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.60
vscode-eslint|dba|1.6.0
EditorConfig|Edi|0.12.4
prettier-vscode|esb|1.6.1
auto-close-tag|for|0.5.6
favorites|kdc|1.9.8
vetur|oct|0.13.0
language-stylus|sys|1.10.0

</details>

**Comment by sandy081** [comment]
There is no way to configure the size of a custom view like in Open Editors.

**Comment by csicky** [comment]
I don't understand how a **bug** clearly reported with a video is closed and marked as out of scope.
