### ISSUE TITLE
Consider syncing the release naming with the release month

### ISSUE THREAD

**Issue by johnbillion** [Microsoft/vscode#60274]
a.k.a. skip the October release and call it the November release.

---

I really enjoy the monthly release cycle of Code. It's strange that the release naming follows the month in which the development work was completed, not the month in which the release occurred. I think it would make sense from an end user perspective to see anNovember release in November, rather than an October release in November.

**Comment by beastdestroyer** [comment]
But then VSCode loses its uniqueness...

Jk, in all seriousness, I think it's fine tbh, it's similar to how Windows 10 works, their most recent update (1809, September 2018) released in October (though it was on the 2nd so quite close to September nonetheless) and what usually tends to happen is they spend the whole month working on VSCode, then they spend a final few weeks clearing it up whilst working on the next month.

Once they're ready to release, they do and then put all efforts on a recovery and the next month.

> It's strange that the release naming follows the month in which the development work was completed, not the month in which the release occurred

I understand what you mean, but I think the VSCode team wants users to know this specifically happened/started on this month, and next month we will have this etc. From the team's perspective (i guess?), they want the end user to know what they have been focusing on every month (even so by their iteration and endgame plans).

That's just my 2 cents, have a great day.

**Comment by kieferrm** [comment]
It would make sense, but we have no plan to change this. (When you think about it, we are not so different from the rest of the world: 2019 car models are released in Summer 2018,  magazine issues for January 2019 are published in November 2018, ..., we just go the other way. 😄)
