### ISSUE TITLE
 Contributing a menu item to explorer/context when a file matches the specified regex or glob pattern

### ISSUE THREAD

**Issue by Codeneos** [Microsoft/vscode#60271]
Is there a way to only enable a certain menu item when the file or folder name matches a certain regex or glob pattern? In summary I want to enable a right click context menu only when the file name ends with `_pack.json`, as the documentation on the `when` property is only lightly documented I wasn't able to figure out if or how this could be done:

What I tried so far:
```
                {
                    "when": "resourceFilename == *_pack.json",
                    "command": "extension.unpackJson",
                    "group": "1_modification"
                }  
```

**Comment by egamma** [comment]
This is supported, pls see https://github.com/redhat-developer/vscode-java/blob/7b0e8845d90c4a956fde066fa2b5422835fb64b2/package.json#L311
