### ISSUE TITLE
Not launching in Fedora 22

### ISSUE THREAD

**Issue by nirajniroula** [Microsoft/vscode#60277]
vscode 1.27 and 1.28 installs but doesn't launch in fedora 22 while version 1.25 is doing well.

**Comment by Tyriar** [comment]
What happens when you try to launch?

**Comment by nirajniroula** [comment]
Actually, nothing happens. I have uninstalled the latest version and using 1.25  for now.

**Comment by Tyriar** [comment]
@nirajniroula you're running through some dash or the terminal? If terminal does it return to the prompt?

Does running `code --verbose` provide any output?

**Comment by Tyriar** [comment]
We don't support Fedora 22 https://code.visualstudio.com/docs/supporting/requirements#_platforms

**Comment by JWleo** [comment]
which one can support Fedora20?

**Comment by Tyriar** [comment]
@JWleo we don't support < Fedora 23 https://code.visualstudio.com/docs/supporting/requirements#_platforms

**Comment by nirajniroula** [comment]
@JWleo I'm not sure about Fedora20. But vscode 1.25 is working good with Fedora 22. I suggest you to try the versions 1.25 or lesser.

**Comment by JWleo** [comment]
@nirajniroula It's fine. Vscode 1.25 can work with Fedora 20.
