### ISSUE TITLE
"Move to a new file" translation should be translatable

### ISSUE THREAD

**Issue by doggy8088** [Microsoft/vscode#60272]
- VSCode Version: `1.28.0`
- OS Version: `10.0.17134.285`

According to [this issue](https://github.com/Microsoft/Localization/issues/29), the **Move to a new file** term is unable to be translated and nobody know where it is.  Is it possible to move this out of the VSCode and make it easy translatable?

![image](https://user-images.githubusercontent.com/7632413/45605076-d2c28d80-ba6c-11e8-8791-d8eae83f87bd.jpg)

**Comment by mjbvz** [comment]
These strings come from typescript and are translatable on their side. See the `typescript.locale` setting that controls this.

Please follow up on the TS project github repo if you believe there is an error in the translation
