### ISSUE TITLE
Add keybinding commands to open files in preview or non-preview mode

### ISSUE THREAD

**Issue by dsanz006** [microsoft/vscode#60276]
If I enable file preview mode, then I can choose if I open a file in preview mode with a single-click, or in non-preview mode (keeping  it) with double-click. However, currently this can't be done with the keyboard: I can only open a file from the explorer pressing Enter, and it is always in preview mode. It would be great to have commands which we can add keybindings to, to open files in preview or non-preview mode.

**Comment by isidorn** [comment]
This is a fair feature request. Keeping it open for now

**Comment by lonix1** [comment]
From my [other issue](https://github.com/Microsoft/vscode/issues/69124):

To open a file from the "palette", in a preview tab:
- <kbd>ctrl-p</kbd>, type filename, choose file
- press <kbd>enter</kbd>

But if I then open another file (from the palette, or from the sidebar), the first preview tab is replaced by the second preview tab.

It would be nice to press some shortcut to open it in a non-preview tab, e.g.:
- ...as above
- **press <kbd>shift-enter</kbd>**

**Comment by JacksonKearl** [comment]
Alternatively, a command to make the current tab not a preview, which we could bind to a keyboard shortcut.

**Comment by isidorn** [comment]
fyi @bpasero

**Comment by bpasero** [comment]
@JacksonKearl there is `workbench.action.keepEditor`

**Comment by bpasero** [comment]
Not sure, it matches this very visible UI piece: 

![image](https://user-images.githubusercontent.com/900690/63743640-26547280-c89d-11e9-8c2f-c0ec1c5dfba0.png)
