### ISSUE TITLE
overriding core command doesn't fix key binding hint on menu

### ISSUE THREAD

**Issue by burtonrodman** [Microsoft/vscode#6027]
- VSCode Version:  1.0.0
- OS Version:  Windows 10 - 10586

I have overridden Ctrl+Shft+S to be Save All and that correctly calls the saveAll command, but the menu still shows Ctrl+Shft+S on the Save As... menu.

{
        "key": "ctrl+shift+s",
        "command": "workbench.action.files.saveAll",
        "when": ""
    },
    {
        "key": "",
        "command": "workbench.action.files.saveAs",
        "when": ""
    }

**Comment by bpasero** [comment]
you mean the top level file menu?

**Comment by burtonrodman** [comment]
yes, File -> Save As... still shows Ctrl+Shft+S after restarting

**Comment by bpasero** [comment]
@burtonrodman works for me though, you need a restart!

<img width="829" alt="screen shot 2016-05-02 at 17 10 28" src="https://cloud.githubusercontent.com/assets/900690/14958239/0dca9538-108a-11e6-82a4-66a78ed97407.png">

**Comment by burtonrodman** [comment]
tried on a different computer with this key bindings and it works.  I must have had multiple instances open, because I restarted several times.  Or the order matters.

[
    { "key": "",          "command": "workbench.action.files.saveAs" },
    { "key": "ctrl+shift+s",          "command": "workbench.action.files.saveAll" }
]
