### ISSUE TITLE
node debug auto-attach extention is not working in VS code.

### ISSUE THREAD

**Issue by nidhinavya** [Microsoft/vscode#60280]
- Extension Name: emmet
- Extension Version: 1.0.0
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:

**Comment by egamma** [comment]
Please provide steps for how to reproduce the problem you are experiencing with auto-attach.

**Comment by egamma** [comment]
Closing pls see #60318
