### ISSUE TITLE
Extension host not responsive

### ISSUE THREAD

**Issue by ajaywebaroo** [Microsoft/vscode#60286]
- Extension Name: emmet
- Extension Version: 1.0.0
- OS Version: Windows_NT x64 10.0.15063
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:

**Comment by egamma** [comment]
This is a warning please see https://code.visualstudio.com/updates/v1_28#_extension-host-unresponsive for how you can help us to find the extension that is causing the problem. If you have identified the extension then please file an issue against the extension.
