### ISSUE TITLE
code intellisense

### ISSUE THREAD

**Issue by aboodh95** [Microsoft/vscode#60287]
Issue Type: <b>Bug</b>

Hi,

after the new update the code intellisense not working with TypeSciprt

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.88GB (7.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-custom-css|be5|3.0.0
bower|don|0.0.3
xml|Dot|2.3.2
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.39
vscode-npm-script|eg2|0.3.5
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.4
gc-excelviewer|Gra|2.1.26
beautify|Hoo|1.4.4
ftp-simple|hum|0.6.7
dynamics-crm-js|JLa|1.2.4
vscode-nuget-package-manager|jmr|1.1.6
docthis|joe|0.7.1
vscode-liquid-snippets|kil|1.1.1
shopify-liquid-preview|kir|1.0.2
prettify-json|moh|0.0.3
csharp|ms-|1.16.2
PowerShell|ms-|1.9.0
team|ms-|1.136.0
language-liquid|nei|0.0.3
es6-css-minify|olb|2.0.3
vscode-template-literal-editor|pli|0.9.0
qub-xml|qub|1.2.1
typescript-types-view|Ret|0.3.2
LiveServer|rit|5.1.1
code-spell-checker|str|1.6.10
bootstrap4-vscode|the|4.3.0
JavaScriptSnippets|xab|1.7.1
html-css-class-completion|Zig|1.17.1

</details>

**Comment by egamma** [comment]
Please provide steps for how to reproduce the failing Intellisense in TypeScript.

**Comment by aboodh95** [comment]
i was working on VScode, i restarted my machine and after i start VSCode it showed me that it was updated, after that i'm not getting any thing once i'm typing

**Comment by mjbvz** [comment]
We need more information to investigate this. Please follow [this guide](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests) to provide the required information about what is going wrong and the steps to reproduce the issue
