### ISSUE TITLE
Code navigation / intellisense broken with wrapped module.exports

### ISSUE THREAD

**Issue by giannisp** [Microsoft/vscode#60299]
- VSCode Version: 1.28.0
- OS Version: macOS 10.14

Steps to Reproduce:

1. Create a JS file like `const app = (module.exports = {});` (usual Prettier format)
2. Add a function like `app.foo = () => {};`
3. Try require / referencing `{ foo }` from any other file. Neither code navigation nor intellisense works.

- Worked just fine on the previous stable version with the wrapped form.
- Works just fine on the current stable version with the non-wrapped form: `const app = module.exports = {};`

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#27639
