### ISSUE TITLE
Node debug auto attach

### ISSUE THREAD

**Issue by VenkattaPidikiti** [Microsoft/vscode#60292]
- Extension Name: debug-auto-launch
- Extension Version: 1.0.0
- OS Version: Windows_NT x64 10.0.14393
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 399,
		"activateCallTime": 1,
		"activateResolvedTime": 1,
		"activationEvent": "*"
	}
}
```

**Comment by egamma** [comment]
Closing pls see #60318
