### ISSUE TITLE
json response time

### ISSUE THREAD

**Issue by VenkattaPidikiti** [Microsoft/vscode#60297]
- Extension Name: json-language-features
- Extension Version: 1.0.0
- OS Version: Windows_NT x64 10.0.14393
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:```json 
{
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 1681,
		"activateCallTime": 44,
		"activateResolvedTime": 0,
		"activationEvent": "onLanguage:json"
	}
}
```

**Comment by egamma** [comment]
Closing pls see #60318

**Comment by creal1976** [comment]
Stop emailing me!

Sent from my Verizon Wireless 4G LTE DROID


Venkatta <notifications@github.com> wrote:


  *   Extension Name: json-language-features
  *   Extension Version: 1.0.0
  *   OS Version: Windows_NT x64 10.0.14393
  *   VSCode version: 1.28.0

We have written the needed data into your clipboard. Please paste:```json
{
"activationTimes": {
"startup": false,
"codeLoadingTime": 1681,
"activateCallTime": 44,
"activateResolvedTime": 0,
"activationEvent": "onLanguage:json"
}
}
