### ISSUE TITLE
late response

### ISSUE THREAD

**Issue by VenkattaPidikiti** [Microsoft/vscode#60293]
- Extension Name: emmet
- Extension Version: 1.0.0
- OS Version: Windows_NT x64 10.0.14393
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 605,
		"activateCallTime": 5,
		"activateResolvedTime": 0,
		"activationEvent": "*"
	}
}
```

**Comment by egamma** [comment]
@VenkattaPidikiti what is the issue and what are the steps to reproduce the issue?

**Comment by egamma** [comment]
Closing pls see #60318
