### ISSUE TITLE
Endless loop in terminal

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#60291]
* open vscode-nls-dev repo
* run task > tsc --watch
* open package.json, hover over scripts > test
* select run test in hover
* 🐛 vscode is toast, terminal is stuck in endless loop

<img width="1328" alt="screenshot 2018-10-09 at 12 59 14" src="https://user-images.githubusercontent.com/1794099/46665144-4ca8eb00-cbc3-11e8-9715-201338a9fd5e.png">

**Comment by Tyriar** [comment]
@jrieken did you have the TypedArray buffer implementation enabled?

**Comment by Tyriar** [comment]
It's happening on 0x200B character (zero width space), `CharWidth_1.wcwidth(0x200B)` returns 0
