### ISSUE TITLE
Git commit through Integrated Terminal doesn't work

### ISSUE THREAD

**Issue by pastelmind** [Microsoft/vscode#60294]
- VSCode Version: 1.28.0 (user setup)
- OS Version: Windows 10 Enterprise
- Using Git for Windows 2.19.1

Steps to Reproduce:

1. Open a git repository directory in VS code, and stage any changes
2. Enter `git commit` in integrated terminal
3. Enter commit message, save and close `COMMIT_EDITMSG`
4. The Integrated Terminal hangs indefinitely with the message "hint: Waiting for your editor to close the file..."
5. Ctrl+C aborts the git commit process with the following error message:
```
error: There was a problem with the editor ''C:\Users\Phil\AppData\Local\Programs\Microsoft VS Code\Code.exe' --wait'.
Please supply the message using either -m or -F option.
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by pastelmind** [comment]
Changing `git config core.editor` to `'C:\Users\Phil\AppData\Local\Programs\Microsoft VS Code\Code.exe' --wait -n` seems to circumvent the issue--when I attempt to commit or interactively rebase using the integrated terminal, a new instance of VS Code pops up for editing `COMMIT_EDITMSG`, and closing it completes the commit/rebase. However, I strongly prefer the old behavior, where I could edit `COMMIT_EDITMSG` inside the *current* open instance of VS Code.

**Comment by bpasero** [comment]
@Tyriar this sounds like https://github.com/Microsoft/vscode/issues/60192

**Comment by Tyriar** [comment]
I tried `code-insiders.cmd --wait ./Documents/dev/Microsoft/vscode/package.json` and it released just fine for me on Windows after closing the tab.
