### ISSUE TITLE
debug doesn't work on node v6

### ISSUE THREAD

**Issue by Mirodil** [Microsoft/vscode#6029]
- VSCode Version: 1.0.0
- OS Version: Windows 10

Steps to Reproduce:

1. install node v6
2. generate express application
3. open the app folder with vscode
4. open console and run `node --debug bin\www`
5. attache to node process with vscode
6. set break point to `users.js:line:6`
7. and navigate in the web browser to '/users'

it works with node v5.10

**Comment by bpasero** [comment]
@weinand @isidorn fyi, node 6 was just released last week with V8 50.

**Comment by isidorn** [comment]
@weinand mentioned that we have not yet tested node v6 and that he is planning to take a look once he is back from vacation. I think Andre is back from vacation this week so forwarding to him.

**Comment by Mirodil** [comment]
the same issue with NodeJS v6.1.0 and VSCode 1.1.0

**Comment by weinand** [comment]
@Mirodil are you debugging node v6 with VS Code 1.1 in 'attach' mode? If yes, please launch node with `--debug-brk` instead of `--debug`. Does it make a difference?

**Comment by Mirodil** [comment]
yes, it works with `--debug-brk` flag

**Comment by weinand** [comment]
@Mirodil thanks for trying. Here is the explanation:

VS Code injects code into node.js to work around slowness issues with large data structures. For reasons we do not yet understand this injected code fixes the issue in node v6 that requesting the call stack results in an "Internal error: illegal access" error.
VS Code injects the code with an 'evaluate' request.
The injected code uses a 'require(...)' which is only available if node is stopped. This is only the case if node is started wit --debug-brk.

We hope that the node v6 issue will be eventually fixed.

**Comment by Mirodil** [comment]
thank you, I got it

**Comment by weinand** [comment]
Node-inspector has the same issue: https://github.com/node-inspector/node-inspector/issues/864

Since code injection fixes the issue for the `--debug-brk` case, we only have to find a way to inject code when node has been started with `--debug`.

**Comment by stevehipwell** [comment]
+1

**Comment by weinand** [comment]
I found a way to inject code into a node.js started with `--debug`. This fixes the initial problem.
The fix will be available in VS Code - alpha.

**Comment by matthiasg** [comment]
It is possible there is still an issue when a 'proxied' accessor method is used ?
I have VSC 1.7.1 and node 6.9.1 on Win10 x64 and whenever i debug onto a call accessing a proxied getter function the debugger just halts. Calling the getter in the Debug Console outputs `illegal access`.

Normal running of the code with attached debugger works fine.

**Comment by weinand** [comment]
@matthiasg yes, proxies are a problem with the old node debugger of VS Code. Please try the new node debugger by using the debug type "node2" in your launch config.
