### ISSUE TITLE
Integrated terminal font issue (oh my zsh) after 1.28

### ISSUE THREAD

**Issue by mantzas** [Microsoft/vscode#60295]
Issue Type: <b>Bug</b>

After upgrading to 1.28 the integrated terminal does not show the symbols of oh-my-zsh anymore.
The font seems different, more bold. Probably uses not the previous font anymore.

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:52:58.945Z)
OS version: Linux x64 4.15.0-36-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1247)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|15.40GB (2.72GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
toml|be5|0.0.3
vscode-intelephense-client|bme|0.8.8
better-toml|bun|0.3.2
thrift|cdu|0.0.1
gitignore|cod|0.5.0
vscode-svgviewer|css|1.4.6
vscode-markdownlint|Dav|0.20.0
githistory|don|0.4.3
gitlens|eam|8.5.6
phpunit|ema|3.0.0
code-runner|for|0.9.4
vscode-php-cs-fixer|fte|0.1.0
vscode-pull-request-github|Git|0.1.7
docomment|k--|0.1.2
csharpfixformat|Leo|0.0.75
rainbow-csv|mec|0.6.0
dotenv|mik|1.0.1
vscode-kubernetes-tools|ms-|0.1.14
python|ms-|2018.8.0
csharp|ms-|1.16.2
Go|ms-|0.6.90
vsliveshare|ms-|0.3.735
vscode-docker|Pet|0.3.1
vscode-yaml|red|0.0.17
rust|rus|0.4.10
code-spell-checker|str|1.6.10
vscode-lldb|vad|1.0.0
vscodeintellicode|Vis|1.0.4
debug|web|0.22.0

</details>

**Comment by ManoelLobo** [comment]
I am having the same issue. Setting the terminal font in vscode settings solved the problem tough. It seems the terminal is not 'inheriting' the editor font as default.

**Comment by mantzas** [comment]
it would be nice if it did inherit the default in order to avoid having to set it up in many places..

**Comment by ManoelLobo** [comment]
Yes, and this was the default behavior until 1.27. It is also stated in the settings screen in 1.28. Probably a bug was introduced and will be fixed by the time 1.28.1 will be available.

**Comment by Tyriar** [comment]
You're likely affected by https://github.com/Microsoft/vscode/pull/56429, eventually this workaround will go away but in the meantime it fixes the issue of underscore not displaying for many users (https://github.com/Microsoft/vscode/issues/35901).
