### ISSUE TITLE
mssql: A SQL editor must have focus before executing this command

### ISSUE THREAD

**Issue by tobygrichards** [Microsoft/vscode#60290]
Having installed the extension in Manjaro Linux and set up a connection profile, when using the command palette and selecting 'MS SQL: Connect' this error occurs 'mssql: A SQL editor must have focus before executing this command' and nothing else happens. 

Version info:
Version: 1.27.2
Date: 2018-09-14T00:41:55.375Z
Electron 2.0.11
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by egamma** [comment]
Please file the issue against the SQL extension,
