### ISSUE TITLE
npm response time

### ISSUE THREAD

**Issue by VenkattaPidikiti** [Microsoft/vscode#60296]
- Extension Name: npm
- Extension Version: 1.0.1
- OS Version: Windows_NT x64 10.0.14393
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:```json 
{
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 1681,
		"activateCallTime": 44,
		"activateResolvedTime": 0,
		"activationEvent": "onLanguage:json"
	}
}
```

**Comment by egamma** [comment]
Closing pls see #60318

**Comment by creal1976** [comment]
Stop emailing me!!!

Sent from my Verizon Wireless 4G LTE DROID


"vscodebot[bot]" <notifications@github.com> wrote:


(Experimental duplicate detection)
Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:

  *   VS code activation (#58692)<https://www.github.com/Microsoft/vscode/issues/58692>
  *   late response (#60293)<https://www.github.com/Microsoft/vscode/issues/60293>
  *   Emmet (#60197)<https://www.github.com/Microsoft/vscode/issues/60197>
  *   Node Debug Auto-attach (#59048)<https://www.github.com/Microsoft/vscode/issues/59048>
  *   emmet (#59049)<https://www.github.com/Microsoft/vscode/issues/59049>
