### ISSUE TITLE
Make `preselect` of Completion Items last longer

### ISSUE THREAD

**Issue by innerlee** [microsoft/vscode#60305]
Currently when you type any character, the preselected item will lose its selection if it is not the first entry.
I would propose to make the preselected item preselected until it does not match any more.

This would enable emulating a simple priority model for auto-suggestions: just set all the frequently used items as preselected. 
This feature would be super useful for extensions such as latex. There will be more than two thousand completion items mixed without priority, otherwise.

**Comment by innerlee** [comment]
In the LaTeX case, I want `\alpha`, `\beta` etc. to be preselected when typing `\a` or `\b`. The current behavior is like the following, which is obviously not optimal.

![ezgif-4-2a1351a7b8e8](https://user-images.githubusercontent.com/9464825/46676911-1b0c4000-cc14-11e8-901d-c98d86b3076f.gif)

**Comment by jrieken** [comment]
It should. What is your snippet sort priority?

**Comment by innerlee** [comment]
`\alpha` is set as `preselected` while others are not.

**Comment by innerlee** [comment]
You can reproduce using this branch https://github.com/innerlee/LaTeX-Workshop/tree/zz/preselect

**Comment by innerlee** [comment]
related configs (other than the first line, most are default):
```json
"editor.suggestSelection": "recentlyUsedByPrefix",
"editor.suggest.filterGraceful": true,
"editor.suggest.snippetsPreventQuickSuggestions": true,
"editor.snippetSuggestions": "inline",
"editor.tabCompletion": "off",
"editor.quickSuggestions": {
    "other": true,
    "comments": false,
    "strings": false
  },

```

**Comment by jrieken** [comment]
Where are these suggestions defined: `\begin{align}...`

**Comment by innerlee** [comment]
They are defined in https://github.com/James-Yu/LaTeX-Workshop/blob/master/data/environments.json#L65, and loaded at https://github.com/James-Yu/LaTeX-Workshop/blob/master/src/providers/completion.ts#L33. Then they are provided from https://github.com/James-Yu/LaTeX-Workshop/blob/master/src/providers/completion.ts#L74-L96.

**Comment by innerlee** [comment]
filterText and sortText of Environments (e.g., `\begin{blah}`) are not set, see https://github.com/James-Yu/LaTeX-Workshop/blob/master/src/providers/completer/environment.ts#L17. But those of the Commands (like `\alpha`) are set here https://github.com/James-Yu/LaTeX-Workshop/blob/master/src/providers/completer/command.ts#L146

**Comment by jrieken** [comment]
> But those of the Commands (like \alpha) are set here https://github.com/James-Yu/LaTeX-Workshop/blob/master/src/providers/completer/command.ts#L146

Do what value? E.g for `\alpha`?

**Comment by innerlee** [comment]
Oh sorry, the field seems unused...

**Comment by jrieken** [comment]
No changes planned
