### ISSUE TITLE
macOS multiline editing with Option key (alt) not working

### ISSUE THREAD

**Issue by alexandercerutti** [microsoft/vscode#60301]
Hello, I've looked for other existing issues, but didn't find what I'm suggesting. Maybe it already exists, but I didn't find it both in VSCode or issues.

In text editors, I often use multiline editing through keeping pressed Option button (Alt) and dragging the cursor. E.g. in Sublime Text, I can do something like this.

![registrazione](https://user-images.githubusercontent.com/5442545/46666553-3f8dfb00-cbc7-11e8-9b97-7ad4bbfa478e.gif)

I think WSCode should absolutely support this. Is it possible? Thank you.
Otherwise, how to add it as custom keybinding?

 

- VSCode Version: 1.28.0
- OS Version: macOS HighSierra (10.13.6)

**Comment by willdot** [comment]
Option + CMD + up / down should do this. Swear I've done it on MacOS.

**Comment by alexandercerutti** [comment]
The key sequence you suggested works with up or down but not with mouse clicks, but if I have an empty row among the selected ones, it will put characters also in there, at the beginning of the line.

**Comment by alexandercerutti** [comment]
I discovered in a completely casual way that in VSCode I have to press also Shift, so the key sequence is `Shift+alt` and drag the mouse.

Anyway, the sequence brings sometimes to a weird (or buggy, don't know) behavior. A sequence of steps to reproduce follows below the gif.

The drag is done from left to right (and happens too if done vice-versa).

![selection](https://user-images.githubusercontent.com/5442545/46808827-7f8ee280-cd6d-11e8-9d22-f930593f7f0e.gif)

1) Use the provided keys sequence and select a text
2) If you try to select another area starting from the same side (outside) of last selected area starting side (e.g. you select first from right to left and then select again starting from right), the text get selected first and then start unselecting up to the start point of the first area.

The same behaviour happens if the second selection starts from top and bottom (outside) of the starting side of the first area.

Doing the same above and below the first selected area, works fine and let you select also text on the other side of the first selected area.

**Comment by alexandrudima** [comment]
This has been improved in 1.32. See https://code.visualstudio.com/updates/v1_32#_improved-column-selection

Let's track the rest of the gaps in #5402
