### ISSUE TITLE
Git: Separate the commit length limit of subject line and description lines

### ISSUE THREAD

**Issue by jmlntw** [Microsoft/vscode#60300]
Since VS Code 1.28 we have a new `git.inputValidationLength` to set the commit length limit, but I think the subject line and the description lines should have different length settings, as @mark-wiemer  mentioned in #56481.

[This article](https://chris.beams.io/posts/git-commit/) says the subject line is preferably limited 50 characters, and the description lines are 72 characters per line. Also, GitHub web UI displays a warning message if your commit subject line is more than 50 characters.

![screenshot_2018-10-09](https://user-images.githubusercontent.com/16081977/46666060-3b2e0600-cbf8-11e8-893c-4d62679cf877.png)

How about something like `git.subjectValidationLength` and `git.descriptionValidationLength`?

**Comment by jrkong** [comment]
I'd love to take a look at this if no one's working on it yet! Could anyone tell me which files I have to look at to fully integrate these settings after adding them to `extensions/git/package.json`?
