### ISSUE TITLE
Organize imports feature is not working anymore

### ISSUE THREAD

**Issue by FlorianLeitgeb** [Microsoft/vscode#60303]
After the last update, my organize imports feature is not working anymore. I have default shortcuts (ctrl+alt+o) and also tried to set various different shortcuts for it, because maybe a global shortcut is overruling. But it still does not work. 

Is there also a possibility to use the feature without the shortcut? I really need this all the time.

 

- VSCode Version: 1.28.0 (user installer)
- OS Version: Windows 10 Pro (1803)

Steps to Reproduce:

1. Install the last update
2. Try to organize imports with default shortcut 

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
You can also trigger this using the `source actions` content menu. Just right click in a js/ts file and select `Source Action...`

Does that still work?

**Comment by ashley-hunter** [comment]
I was getting the same issue, however I noticed VS Code was using the workspace version of TypeScript, which is my case was 2.7.2. Changing this to use TypeScript v3.1.1 seems to have corrected the issue, perhaps you have a similar set up?

**Comment by FlorianLeitgeb** [comment]
WOW!!! That`s was the problem. How can that be? I thought this is a VSCode feature. Or is VSCode only using the Typescript Service?

**Comment by mjbvz** [comment]
Yes typescript powers vscode's js/ts language features. Many features require a min version of TS. 

Either change your workspace version of typescript or upgrade your project to use a newer version of TS

**Comment by FlorianLeitgeb** [comment]
It would be great, to get a warning or so, when I try to use such a feature where VSCode also offers built in shorctus, that my version is too low. Otherwise people gonna complain about VSCode not working and bad Microsoft software and so on. Yes, the do it and it is unfair. Would be so easy to avoid this.
