### ISSUE TITLE
Scrolling issues windows 10 switching desktop

### ISSUE THREAD

**Issue by dinesh-dev** [Microsoft/vscode#6030]
- VS Code Version: 1.0.0
- OS Version: Windows 10 Home Build 10586.218

Steps to Reproduce:
1. Open two desktops.
2.  Open VS Code in one of the desktops with scroll-able content. Scrolling works fine now.
3. Switch to the other desktop and back to VS Code. Now scroll the same content using touch-pad. It does not scroll, looses focus.

**Comment by bpasero** [comment]
@dinesh-dev you mean scrolling in the editor or somewhere else?

**Comment by dinesh-dev** [comment]
in the editor

**Comment by bpasero** [comment]
@dinesh-dev when you say it looses focus, where does it go?

**Comment by dinesh-dev** [comment]
@bpasero The editor does not allow the contents to be scrolled after switching desktops using touch-pad. 
![scrollable content](https://cloud.githubusercontent.com/assets/11528019/15003692/a62b10ee-117c-11e6-9a54-fc2c370ae957.png)
![taskview](https://cloud.githubusercontent.com/assets/11528019/15003693/a62c0a26-117c-11e6-980f-5b73ae4c90ad.png)

In the first screenshot I have a file open that has scroll-able content in Desktop 2. When I switch to Desktop 1 using task view and switch back to Desktop 1 the content does not scroll, even when I click inside the file.

Hopefully this helps.

**Comment by bpasero** [comment]
@dinesh-dev does any other interaction work in that case, just not scrolling?

**Comment by dinesh-dev** [comment]
Just scrolling using touch-pad. Other interactions work fine. @bpasero

**Comment by feliperyan** [comment]
Scrolling on a HTML file of 400 lines is unusable. Skips whole sections, very jumpy

**Comment by chaopeng** [comment]
@dinesh-dev Did you also see this issue on Chrome/Chromium?

**Comment by alexandrudima** [comment]
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.
