### ISSUE TITLE
Trigger Suggest (Ctrl+Space) very slow in python

### ISSUE THREAD

**Issue by montant** [Microsoft/vscode#60317]
Issue Type: <b>Bug</b>

When using Ctrl-Space with a python file (fine with C++), tooltip menu opens with statement "Loading" and takes a lot of time (20 s, 30 s, even more) for being filled.

- If I disable all extensions, this issue is gone.
- If I change parameters of extension python for not using 'jedi' but Microsoft engine for completion, this issue is gone too (but other issue comes with Microsoft engine, thus this workaround is not usable for me, and it is a workaround anyway, as default 'jedi' seems to bring the issue)

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 5120 CPU @ 2.20GHz (56 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|127.65GB (121.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.5.6
python|ms-|2018.8.0
cpptools|ms-|0.19.0
perforce|sle|3.1.0
cmake|twx|0.0.17
cmake-tools|vec|1.1.2

</details>

**Comment by egamma** [comment]
please report the issue against the python extension.
