### ISSUE TITLE
Debug hover scrollbars get in the way of interaction

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#60316]
In this debug tooltip the horizontal scrollbar makes it difficult to click the arrow to expand. It appears whenever the mouse is in that area.

<img width="765" alt="screen shot 2018-10-09 at 2 11 47 pm" src="https://user-images.githubusercontent.com/1078012/46671720-5c2d3180-cbcd-11e8-96a6-b1f1d702cd10.png">

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/59452
