### ISSUE TITLE
Github is asking credentials every single time

### ISSUE THREAD

**Issue by diegomolinavera** [Microsoft/vscode#60319]
Since it was updated I'm facing the next thing
![image](https://user-images.githubusercontent.com/37162199/46674844-84a83200-cbb3-11e8-8cf2-369f46f07a1e.png)

This modal prompt is launched every time I hit push to github. If typed the password It doesn't work, but if I cancel it, i have the chance to type my username and my password. It's really annoying because I can click on cancel several times, sometimes, and it appears again and again 

VSCode Version: 1.28.0
OS Version: MacOS High Sierra 10.13.3

**Comment by diegomolinavera** [comment]
indeed, It is a configuration of the credentials. But I've been working on this computer for almost a year and it happens the same thing in some updates.

I removed the credentials from the key store and it doesn't shows up the prompt asking me to type the password anymore.

It is not a vscode related thing but definitely some updating breaks the git config

**Comment by joaomoreno** [comment]
I'm pretty sure it is irrelevant to VS Code's updating, since VS Code simply spawns `git push`. There's no deeper integration that that. VS Code happens to update often and it could coincide with whatever it is that breaks that.
