### ISSUE TITLE
User confusion about 'Extension Host not responsive' notification

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#60318]
We have received many crippled issues like #60297 #60293 #60292.

This is triggered by https://code.visualstudio.com/updates/v1_28#_extension-host-unresponsive.

Here is how users create these issues:
- user sees the Extension Host not responding notification
- user clicks the Show Running extensions from the notification
- user clicks the `Report Issue` button (we show many of them) for one or more of these extensions
- the action copies some timing information to the clipboard, often users forget to paste the clipboard contents when creating the issue.

**Comment by egamma** [comment]
Suggest to either improve this flow or to not show the warning, since it isn´t helpful for ordinary users.

**Comment by madcampos** [comment]
As I'm not debugging the extensions and when dealing with large files (~10k lines) this message keeps popping up and is _really_ annoying as the extensions are taking some time to process the file, this looks normal as the file is very large.

**Comment by egamma** [comment]
@madcampos the plan is that we can toggle profiling when an extension is not responsive for a period of time.

**Comment by alexandrudima** [comment]
Until we have a more polished experience in this area, we will remove the notification.

**Comment by alexandrudima** [comment]
For verification, you can write an extension:

* `package.json`:
```js
{
  "name": "bad",
  "publisher": "alex",
  "version": "0.0.0",
  "engines": {
    "vscode": "^1.22.0"
  },
  "activationEvents": [
    "*"
  ],
  "contributes": {
    "commands": [
      {
        "command": "bad.loop",
        "title": "Bad: Create endless loop"
      },
      {
        "command": "bad.work",
        "title": "Bad: Create 15s work"
      }
    ]
  },
  "main": "index.js"
}
```

* `index.js`:
```js
const vscode = require('vscode');

exports.activate = function () {
    vscode.commands.registerCommand('bad.loop', () => {
        doNothingInALoop();
    });
    vscode.commands.registerCommand('bad.work', () => {
        doSomeWorkFor15s();
    });
}

function doNothingInALoop() {
    console.log(`I am now entering while true loop`);
    while (true) {
        // do nothing, like a pro
    }
}

function doSomeWorkFor15s() {
    console.log(`I will now be busy for 15s!`);
    let start = Date.now();
    while (true) {
        if (Date.now() - start > 15 * 1000) {
            console.log(`Finished busy work!`);
            break;
        }
    }
}
```

* Execute "Bad: Create endless loop"
* The extension host CPU goes to 100%
* No prompt is shown even when waiting more than 10s.

**Comment by levrik** [comment]
@alexandrudima Is there a new ticket already?

**Comment by ipapoutsidis** [comment]
@egamma 
Thank you for solving this issue by updating the VSC!
