### ISSUE TITLE
Ctrl + arrows and Ctrl + backspace aren't working anymore

### ISSUE THREAD

**Issue by sharno** [Microsoft/vscode#60322]
Since the new release (1.28) various keyboard shortcuts aren't working as they did before.
- Ctrl + arrows to move by word right or left didn't work anymore, I had to set it up manually in the keyboard shortcuts file to make it work again.
- Ctrl + backspace doesn't remove a word anymore.
- Also, the same shortcuts stopped working in the git commit message box.

**Comment by marcorichetta** [comment]
It works on Ubuntu 18.04, like always did.
```
Versión: 1.28.0
Confirmación: 431ef9da3cf88a7e164f9d33bf62695e07c6c2a9
Fecha: 2018-10-05T14:52:58.945Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Arquitectura: x64
```
Could it be an OS configuration?

**Comment by sharno** [comment]
I found out that restarting the editor solved it. Had to switch to native UI too as shortcuts triggered visual artifacts on the editor. Not sure if the new UI is related to that temporary issue

**Comment by REEMERGEMEDIA** [comment]
CMD+Enter does not work for me in the Git commit box. I tried mapping CMD+Enter to git.commit (staged) but it has me then needing to pick the repository to commit to, which is not how it operated before. This keybinding/mapping is still an issue since updating.

**Comment by alexandrudima** [comment]
@sharno I cannot reproduce on a new installation of VS Code Stable.
* <kbd>Ctrl</kbd>+<kbd>Left</kbd>/<kbd>Right</kbd> do word navigation
* <kbd>Ctrl</kbd>+<kbd>Backspace</kbd> deletes word left
It might be some sort of timing coincidence (with the VS Code update), but perhaps you have an extension that is tweaking keyboard shortcuts or perhaps you have previous changes in your `keybindings.json`. In any way, I cannot reproduce what you are reporting.

@REEMERGEMEDIA "but it has me then needing to pick the repository to commit to". Can you perhaps open a separate issue? I don't think your issue (committing on mac) is related to this issue (word navigation on Windows).

**Comment by sharno** [comment]
@alexandrudima I cannot reproduce it anymore.
Disabling all extensions then restarting the editor and enabling again seem to have solved it. Not sure what the cause was.

Thank you
