### ISSUE TITLE
Debug adapter process has terminated unexpectedly (exit code: 1)

### ISSUE THREAD

**Issue by atomclip** [Microsoft/vscode#60327]
<img width="460" alt="schermafbeelding 2018-10-09 om 15 59 26" src="https://user-images.githubusercontent.com/27486864/46678977-34969300-cbe6-11e8-933e-f8d1fc75da21.png">

I get this error with the gnu-debugger extension on macOS.
https://marketplace.visualstudio.com/items?itemName=atomclip.gnu-debugger

I could not figure out what the problem was after a day of testing, it is somewhere deep inside vscode or node. Everything still worked on Sunday.

Finally I tested on Linux.
On Debian I tested with version 1.26.1 and everything worked.
Installed version 1.28 and got the same error. 
Installed 1.26.1 again and everything worked again.

I uninstalled version 1.28 on macOS and installed 1.27.2 now the extension works.

What has changed in version 1.28 that causes this problem?

**Comment by isidorn** [comment]
Please file this against the gnu debugger extension. I understand that we did an update which seems to break something, but the extension first needs to investigate on their side .Thanks

**Comment by atomclip** [comment]
@isidorn,

I am the developer of the extension and already spent a day figuring out what the problem is. It is somewhere deep inside vscode or node. If I have any clue I may be able to fix things. I did a google search on the subject and discovered that this problem frequently shows up. There is however nothing that points me in the right direction. 

This is the repository:
https://github.com/atomclip/gnu-debugger

**Comment by isidorn** [comment]
@atomclip I suggest the following start vscode F1 > developer tools > source
Put a breakpoint [here](https://github.com/Microsoft/vscode/blob/4312f42a4fc4fdc790375bc09a21782a27f5e35a/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L510)
Try to see why the adapter exited.

If that does not provide useful information than I suggest you try to capture on your adapter side some stack trace when it exits so we try to find the cause.

**Comment by atomclip** [comment]
@isidorn,

I tried to do the suggestion breakpoint but I only see a minified workbench.js and workbench.main.js.

When I push F5 to start the extension I see a lot of errors and violations but it is in code I did not write.

<img width="1052" alt="schermafbeelding 2018-10-11 om 09 39 39" src="https://user-images.githubusercontent.com/27486864/46788367-34a7a780-cd3a-11e8-9327-95b075acf746.png">
<img width="1052" alt="schermafbeelding 2018-10-11 om 09 40 22" src="https://user-images.githubusercontent.com/27486864/46788385-3a04f200-cd3a-11e8-8435-89517888f78e.png">
<img width="1053" alt="schermafbeelding 2018-10-11 om 09 40 36" src="https://user-images.githubusercontent.com/27486864/46788390-3cffe280-cd3a-11e8-9ad6-5e8048a2ff08.png">

**Comment by isidorn** [comment]
I suggest to debug it on your end, that will be easier for you and try to figure out why it exited unexcepectedly

**Comment by atomclip** [comment]
How, do I have to download and install a debug version of vscode?

I tried setting breakpoints in the extension but it stops before ever getting there.

**Comment by isidorn** [comment]
Aaaaa you do not have your own debug adapter, but you are piggy backing on the node debug adapter. Reopening and assigning to @roblourens he can provide guidance

**Comment by atomclip** [comment]
@isidorn 

I don't understand you, what do you mean by piggy backing on the node debug adapter?

**Comment by isidorn** [comment]
@atomclip sorry your avatar looked like react icon, so I thought that you are using the node debugging. After clicking in your repo I saw you have your own type GNU-debugger.
Thus you have your own debug adapter which you yourself wrote. Thus I believe you know how to debug it since you own that code.
Appologies for the confusiong, clsoing since this is casued by extension as I originally thought

**Comment by atomclip** [comment]
I know how to debug code. Please leave this open till the issue is closed.

**Comment by atomclip** [comment]
When I select Extension + Server as debug I get this in the debug console.
For some reason it can't find vscode.

<img width="1012" alt="schermafbeelding 2018-10-11 om 11 26 53" src="https://user-images.githubusercontent.com/27486864/46794723-bacaea80-cd48-11e8-896b-5902c45855d1.png">

**Comment by atomclip** [comment]
I have this in session.ts

import * as vscode from 'vscode';

It is used to show a progress window in vscode.

**Comment by atomclip** [comment]
I removed the progress window. Now the message is gone but still the same problem.

I also have
import * as os from 'os';

To read the current home directory.

<img width="1012" alt="schermafbeelding 2018-10-11 om 11 44 15" src="https://user-images.githubusercontent.com/27486864/46795688-1bf3bd80-cd4b-11e8-9cb3-90eee566b2b6.png">

**Comment by atomclip** [comment]
Removed depend on os. Still the same problem.

**Comment by roblourens** [comment]
The debug adapter process can't access the `vscode` module, only the extensionhost process can. Could you file an issue on that extension? If it's your extension, there are some docs regarding the debug adapter model here https://code.visualstudio.com/docs/extensions/example-debuggers

**Comment by atomclip** [comment]
@roblourens,

Sorry, 
Can you point me to the exact line where it says that the debug adapter can't access the vscode module. I read the text multiple times but I can't find anything. Why did it work on previous versions? How do you build a progress window from you debugger?

I based the extension on the Mock Debug.

Already waisted several days on this. Finally I cloned the Mock Debug from git again.  
The Mock Debug extension is broken as well. 

After running the fix you can't debug the extension anymore. Only the breakpoint in extension.ts works the rest of the breakpoints do not work. Extension development is broken! I can't debug so I can never find the cause. 

<img width="1078" alt="schermafbeelding 2018-10-11 om 19 19 00" src="https://user-images.githubusercontent.com/27486864/46822099-d5be4e80-cd8a-11e8-8726-b274ccd890e5.png">
<img width="360" alt="schermafbeelding 2018-10-11 om 19 13 36" src="https://user-images.githubusercontent.com/27486864/46822114-e078e380-cd8a-11e8-92dc-20f6cd816389.png">
<img width="422" alt="schermafbeelding 2018-10-11 om 19 13 49" src="https://user-images.githubusercontent.com/27486864/46822117-e40c6a80-cd8a-11e8-966e-c1bfd8db33ad.png">
<img width="292" alt="schermafbeelding 2018-10-11 om 19 23 00" src="https://user-images.githubusercontent.com/27486864/46822242-406f8a00-cd8b-11e8-8476-cd0e67f3e617.png">

**Comment by roblourens** [comment]
I'm not having any problems with the mock debug extension, what exactly is broken? What is that diff? I don't really understand what the issue is.

**Comment by atomclip** [comment]
The diffs are in the screen dumps above.

When you run npm install you get error messages and warnings for outdated and vulnerable libraries.
If you do the suggested fix you end up with the diffs in the top image. After you do that you can no longer debug the Mock Debug extension. Debug is broken by updating the libraries. 

If you update all libraries to the latest versions you have to fix the line:
**config.debugServer = this._server.address().port**

These diffs are exactly what I did for GNU_debugger extension. That is the reason why I can't debug the extension and fix the problem. 

To see this problem you need to take the following steps.
- git clone Mock Debug
- run npm install
- run the suggested fix
- run npm install again
- set breakpoints on the given lines
- set debug to Extension + Server
- run debug

What I get on both macOS and Linux is that the debuggers only stops at  the breakpoint in extension.ts. Breakpoints in mockDebug.ts and mockRuntime.ts do not work.

**Comment by roblourens** [comment]
I did `npm audit fix` and it did not run the `postinstall` task which downloads vscode.d.ts. Is that your problem? Besides that I don't have any issue setting breakpoints. Make sure you set `"debugServer": 4711` in your "mock" launch config.

**Comment by atomclip** [comment]
To get the Mock Debug extension working again I did git clone and the following mods:

package.json
Use the latest version of the dependencies
<img width="1080" alt="schermafbeelding 2018-10-13 om 08 30 04" src="https://user-images.githubusercontent.com/27486864/46902278-cc380200-cec2-11e8-9b7f-ac922e457de4.png">

extension.ts
Enabled debugging and fixed an error
<img width="1084" alt="schermafbeelding 2018-10-13 om 08 31 17" src="https://user-images.githubusercontent.com/27486864/46902296-1a4d0580-cec3-11e8-9d40-725b3708941f.png">
<img width="1082" alt="schermafbeelding 2018-10-13 om 08 30 46" src="https://user-images.githubusercontent.com/27486864/46902297-1de08c80-cec3-11e8-9838-b7a57454854c.png">

**Comment by atomclip** [comment]
I did the same modifications as above on the gnu-debugger extension. Updating the dependencies fixed the problem and the extension is functional again. Thanks for the support. You can close the issue.
