### ISSUE TITLE
The Intellisence works slow after enter "." in python.

### ISSUE THREAD

**Issue by makyo5** [Microsoft/vscode#60324]
Python 3.6.6. 
write the python code normally. (here I use the numpy)
type any code such include "." (example: np.)
the intellisence works slow that could not come out fastly.

![11](https://user-images.githubusercontent.com/16131127/46678263-d46c1500-cc16-11e8-9126-16cb9c5653f5.png)

**Comment by makyo5** [comment]
This issue also happens in .net core 2.1.x

**Comment by coolit** [comment]
Same problem here, but for golang in my case. Fast in the first few days, then very slow.

**Comment by mjbvz** [comment]
Please file this issue against the python extension
