### ISSUE TITLE
layout trashing in titlebarPart

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#60326]
* close all editors et al
* start performance recording
* reload workbench
* 🐌 notice how the titlebar part trashes the layout

<img width="723" alt="screenshot 2018-10-09 at 17 11 42" src="https://user-images.githubusercontent.com/1794099/46679056-6a3b7c00-cbe6-11e8-9fce-e992bd777586.png">

**Comment by jrieken** [comment]
the irony is that no title bar part is showing, its hight is `0` which makes me wonder why the part is alive to begin with

**Comment by jrieken** [comment]
@isidorn maybe this is also you and about not layouting parts that are hidden

**Comment by bpasero** [comment]
@sbatten it seems you introduced this for the custom menu. I would think:
* this is not needed when the title bar is native
* this is not needed when the menu is not custom
* if needed, this should run ideally not on the startup but right after if possible

I see a lot of time spend on startup:

![image](https://user-images.githubusercontent.com/900690/46716163-394d5c80-cc63-11e8-96a2-17a21a4c83ad.png)

**Comment by sbatten** [comment]
@jrieken the titlebarPart should exist as it house the menubarControl which is responsible for populating the menubar (native or custom) it likely does not need to layout however.
