### ISSUE TITLE
Javascript Code Formatter Jumps to End of Module

### ISSUE THREAD

**Issue by Whobeu** [Microsoft/vscode#60339]
- VSCode Version: 1.28
- OS Version: Windows 10 1809

Steps to Reproduce:

1. Open a Javascript module.
2. Make some changes to the code formatting.
3. Press Control-A followed by Control-K, Control-F
4. The module will be formatted but you will be at the end of module rather than remaining on the line you were working on. If you go back to your line and make no changes requiring reformatting, the key sequence in step 3 will have no effect. But make any change that causes reformatting to happen with Control-K, Control-F and you will again be at the bottom of the module. This appears to have just started with 1.28. I did not observe the behavior in 1.27.2.

Does this issue occur when all extensions are disabled?: Yes/No Yes

**Comment by mjbvz** [comment]
Only seems to happen for `format selection`, not for `format document`. Also happens in html files so I do not  believe this is language specific.

@alexandrudima or @rebornix Can you please take a look

**Comment by alexandrudima** [comment]
@Whobeu @mjbvz I don't understand the issue.

In step 3, "Press Control-A followed by Control-K, Control-F". Control-A takes the cursor to the end of the file and Control-K, Control-F keeps it there, so I'm not sure I understand the issue here.

![60339](https://user-images.githubusercontent.com/5047891/47000503-b6c41180-d128-11e8-9f87-3a44543f13b5.gif)

**Comment by Whobeu** [comment]
For example, I have a module with 400 lines. If I go to line 150 and hit Control-A, everything is selected but I am still on line 150 in the window. This is the same behavior as in 1.27 and older. However, if I format the text and it is successful which deselects the text or I hit escape and manually cancel the selection, I am now brought to the bottom of the document. Prior to 1.28, my screen stayed on the current line. There was an oddity in the prior versions where I would be dropped to the bottom if I typed something but I always clicked the mouse on my current line and the cursor stayed put. When I think about it, it is possible the old behavior was a bug and this current behavior is the way it is supposed to work. Coming from Visual Studio I was used to the Control-K, Control-F sequence and used that with VS Code. I am now using Control-Alt-F so that my window does not jump to the bottom.

**Comment by alexandrudima** [comment]
Yes, that change was intentional. The cursor is revealed after a format command is applied. The change was done in #48051.

fyi @jrieken
