### ISSUE TITLE
Add a menu for extension commands

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#6033]
https://github.com/Microsoft/vscode/pull/6000 introduces a new top level menu for extension commands. We should discuss if such a menu is desired or not.

![1](https://cloud.githubusercontent.com/assets/7069719/14929697/5e4848f2-0e91-11e6-8641-f683860decda.png)

@Microsoft/vscode for input

**Comment by bpasero** [comment]
my 2 cents: I find this menu a workaround for not being able to allow extensions to fill in commands anywhere in the top level menu. I would rather want to provide explicit API so that extension writers can hook into existing menus. It is up for debate if we would want to allow for creating new top level menus or not.

**Comment by jrieken** [comment]
duplicate of #365
