### ISSUE TITLE
Importing from extensions is slow

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/vscode#60338]
- VSCode Version: v1.28.0
- OS Version: macOS v10.13.5

The following extension takes about 260ms on my machine to execute:

```ts
const start = Date.now ();

import * as globby from 'globby';

const activate = function ( context: vscode.ExtensionContext ) {
  globby;
};

export {activate};

const end = Date.now ();
const elapsed = end - start;
import * as vscode from 'vscode';
vscode.window.showInformationMessage ( `Elapsed: ${elapsed}ms` );
```

While executing the compiled JS directly from node (v8.4.0 and v10.11.0) takes about half as much, 130ms:

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const start = Date.now();
const globby = require("globby");
const activate = function (context) {
    globby;
};
exports.activate = activate;
const end = Date.now();
const elapsed = end - start;
console.log(`Elapsed: ${elapsed}ms`);
//# sourceMappingURL=extension.js.map
```

Maybe this is normal, but you might want to take a look into this.

**Comment by jrieken** [comment]
Hm, interesting... We do [patch](https://github.com/Microsoft/vscode/blob/05e1c11111cb74586de5fb3a29d9db12126c02bb/src/vs/workbench/api/node/extHost.api.impl.ts#L855-L858) the `require` function and give extensions a specific instance of the vscode-module, but that is fast and you aren't requiring the `vscode` module anyways... 

@fabiospampinato How/when did you activate your extension? Was it on startup? Did it maybe suffer from noise neighbours?

**Comment by fabiospampinato** [comment]
@jrieken the extension was activated on startup (`"*"`), but I did some extra tests:

- I've debugged the extension from a pristine VSC Insiders build with only a custom theme enabled, I'm still seeing ~300ms.
- I've changed the activation time from `"*"` to `"onLanguage:json"`, still seeing ~300ms.
- I've packaged the app and installed it directly, thinking that maybe it was something related with debugging, and now the extension is a bit faster (~250ms), but still not as fast as executing the code directly from node.

Maybe the noisy neighbor is VSC itself? 

I guess either the slowness is caused by some other piece of code or the [rest](https://github.com/Microsoft/vscode/blob/05e1c11111cb74586de5fb3a29d9db12126c02bb/src/vs/workbench/api/node/extHost.api.impl.ts#L860-L878) of the body of that function is slow and for some reason it gets speculatively executed anyway 🤷‍♀️ 

I've attached the extension, in case you want to try this yourself.

[hello-slow.zip](https://github.com/Microsoft/vscode/files/2478606/hello-slow.zip)

**Comment by jrieken** [comment]
> Maybe the noisy neighbor is VSC itself?

It surely is doing other things... I will do a profiling session to see if there is something obviously broken but it might just be how things are... 

Maybe activating on forgein command execution, e.g. `type`, is the least noice scenario...

**Comment by alexandrudima** [comment]
This cannot be explained by the noisy neighbour problem. The `require` call is synchronous, so while that is executing, the event loop is busy and no other extension (nor vscode) is executing.

IMHO the culprit could be the ASAR support baked-into Electron. They are patching the `require` implementation to make ASAR work. To prove this, one could run an experiment where a process is forked from Electron, once with the env variable to disable ASAR support, and once without it (the default). Then, comparing profiles could show the root cause.

**Comment by alexdima** [comment]
I could no longer reproduce a large difference. Here is what I have tried:
* `package.json`:
```json
{
    "name": "60338",
    "publisher": "alex",
    "version": "1.0.0",
    "engines": {
        "vscode": "^1.31.0"
    },
    "activationEvents": [
        "*"
    ],
    "main": "index.js",
    "dependencies": {
        "globby": "^11.0.0"
    }
}
```
* `index.js`:
```js
const vscode = require('vscode');

const start = Date.now();
const globby = require('globby');
const end = Date.now();

exports.activate  = function (context) {
    globby;
    const elapsed = end - start;
    vscode.window.showInformationMessage(`Elapsed: ${elapsed}ms`);
};
```
* `index2.js`:
```js
const start = Date.now();
const globby = require('globby');
const end = Date.now();

globby;
const elapsed = end - start;
console.log(`Elapsed: ${elapsed}ms`);
```

I also just installed the latest `globby`.

Loading it in a vscode extension:  51ms
Loading it via `node index2.js`: 44ms

I can explain this by the fact that the machine is a bit busier when launching the extension host than when launching nodejs on the terminal.

@fabiospampinato Please let us know if this is impacting your extensions.
