### ISSUE TITLE
Java Selenium library is throwing an error in import lines in Visual Studio Code but not in Eclipse

### ISSUE THREAD

**Issue by ajay340** [Microsoft/vscode#60331]
- VSCode Version: 1.28.0
- OS Version: Mac OS 10.13.6

Steps to Reproduce:

1. Generate maven repository of jdk8.
2. Add selenium dependency to pom.xml
3. Update configurations
4. Write in App.java: 
```
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
```
5. Observe how VSCode calls an error on the import lines and outputs "package org.openqa.selenium does not exist"
6. Observe that one can still debug and run code using selenium functions but it is not being recognized and instead being called an error
7. Open that same repository in eclipse and eclipse can run and debug the same code without any errors in the import lines

Proof:
In Visual Studio Code:
<img src="https://i.imgur.com/96tmBsj.png">
In Eclipse:
<img src="https://i.imgur.com/QH5Z81q.png">

Does this issue occur when all extensions are disabled?: Yes/No
Terminal command doesn't work on mac

**Comment by egamma** [comment]
Please report the issue against the Java extension.
