### ISSUE TITLE
Integrated terminal selector not updated when using shortcut keys to focus them

### ISSUE THREAD

**Issue by stgogm** [Microsoft/vscode#60334]
Issue Type: <b>Bug</b>

1. Open an integrated terminal.
2. Rename the integrated terminal.
3. Open another integrated terminal.
4. Rename the new terminal.
5. Cycle with keyboard shortcuts (`workbench.action.terminal.focusNext` or `workbench.action.terminal.focusPrevious`)

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:52:58.945Z)
OS version: Linux x64 4.15.0-36-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3549)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.60GB (2.30GB free)|
|Process Argv|--unity-launch --ignore-gpu-blacklist --ignore-gpu-blacklist|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.6.0
vscode-html2pug|dba|0.1.0
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.6.1
xml-format|mik|1.0.0
vscode-pugbeautify|mrm|1.0.2
vscode-puglint|mrm|2.3.0
vetur|oct|0.13.0
code-settings-sync|Sha|3.1.2
code-spell-checker|str|1.6.10
code-spell-checker-spanish|str|1.0.1
vscode-wakatime|Wak|1.2.3
change-case|wma|1.0.0

</details>

**Comment by Tyriar** [comment]
Fix coming soon https://github.com/Microsoft/vscode/issues/59876
