### ISSUE TITLE
JSDoc comment no more available (JS Doc Completion setting no more working)

### ISSUE THREAD

**Issue by tiusnonos** [Microsoft/vscode#60335]
- VSCode Version: 1.28.0
- OS Version: Windows 7 (x64)

Steps to Reproduce:

1. Create a JS file and define a MyClass class.
2. Add the following function to the class: MyClass.prototype.myFunction = function (param1, param2) {};
3. Place the cursor on line on the top of that function
4. Type /** and press enter: an empty JSdoc is created
<pre><code>
    /**
     * 
     */
    MyClass.prototype.myFunction  = function (param1, param2) {
    };
</code></pre>
5. Previous behavior: the following JSdoc was created:
<pre><code>
    /**
     * 
     * @param {*} param1  
     * @param {*} param2 
     */
    MyClass.prototype.myFunction  = function (param1, param2) {
    };
</code></pre>
This issue happen with no extension and no user or workspace settings.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/Microsoft/TypeScript/issues/27638 to track root cause upstream
