### ISSUE TITLE
Razor(.cshtml) wrong color highlight with if block and html

### ISSUE THREAD

**Issue by Creta5164** [Microsoft/vscode#60336]
- VSCode Version : 1.28.0 (installer x64) / 1.29.0-Insider (no extension)
- OS Version : Windows 10 Pro (1803)

Adding HTML tags with any attributes(if that has = then also happen) in the `if {}` block makes syntax highlighting strange.\
pure 1.29.0-Insider also happen this problem.

![razor syntax not working](https://user-images.githubusercontent.com/13521406/46683824-21a6b180-cc2c-11e8-962c-78c70a1a6ef2.png)

Steps to Reproduce : 

1. Create ASP.NET Core MVC project `dotnet new mvc`
2. Open `View/Home/Index.cshtml`
3. Add snippet below
```cshtml
@if (/*anything*/) {
    <div style=""></div>
    //or
    <meta property="" content=""/>
    //or anything html tag if it has =
}
```
Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
moved to https://github.com/demyte/language-cshtml/issues/24
