### ISSUE TITLE
Tab scrolling does not work with split panels

### ISSUE THREAD

**Issue by piedrahitapablo** [Microsoft/vscode#60333]
Hi, thank you for developing vs code, it has been very helpful and fun to work with. The issue that I'm having right now has to do with tabs scrolling, when I split the editor vertically and open a number of tabs that exceeds the available space, tab scrolling stops working. I searched for similar issues but found nothing.

Thanks for your help.

- VSCode Version: 1.28.0
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Open an editor window
2. Open various tabs to enable tabs scrolling
3. Split the editor vertically
4. Open various tabs on the new editor panel to enable tabs scrolling
5. Now the tab scrolling does not work on the new panel

Does this issue occur when all extensions are disabled?: Yes

**Comment by egamma** [comment]
Tab scrolling works for me, please see the screenshot below, the scrollbar is shown below the tabs.

![image](https://user-images.githubusercontent.com/172399/46720244-4a509a80-cc70-11e8-99e8-bfee1b74ae04.png)

Cannot reproduce the issue given the provided information.

**Comment by piedrahitapablo** [comment]
I just retried those steps and the issue is still present, see the screenshots below:

first panel with scroll working:

![crop1](https://user-images.githubusercontent.com/6783539/46750200-0f089880-cc7d-11e8-970b-463012f2d5d3.png)

second panel with scroll not working:

![crop2](https://user-images.githubusercontent.com/6783539/46750239-22b3ff00-cc7d-11e8-9350-c3a689fe1f83.png)

is there any other info that I could provide for this issue? maybe a log or something?

**Comment by egamma** [comment]
What would be helpful is to include an animated GIF of the full setup.

**Comment by piedrahitapablo** [comment]
This gif illustrates the steps, and shows the scroll working on the left side panel and not working on the right side panel

![peek 2018-10-11 09-44](https://user-images.githubusercontent.com/6783539/46812468-67ea3680-cd3a-11e8-8b8c-28c1b47cd3f8.gif)

Thanks for your help

**Comment by bpasero** [comment]
Great find.

**Comment by piedrahitapablo** [comment]
Thanks for your help!
