### ISSUE TITLE
Integrated Terminal in VSCode 1.28 does not show unicode characters corrrectly

### ISSUE THREAD

**Issue by pastelmind** [Microsoft/vscode#60330]
- VSCode Version: 1.28.0
- OS Version: Windows 10 Enterprise
- Git version: 2.19.1.windows.1 (Git for Windows)
- Note: Integrated terminal is configured to Git Bash (`C:\Program Files\Git\bin\bash.exe`)

Steps to Reproduce:

1. Checkout any repository that contains non-ASCII text files
2. Run `git diff @~` in the Integrated Terminal
3. Any non-ASCII character in the diff result is displayed as a sequence of control characters.
    * Example: `패치` &rarr; `<ED><8C><A8><EC><B9><98>`, `버전` &rarr; `<EB><B2><84><EC><A0><84>`
4. Note: Downgrading to VSCode 1.27.2 solves the issue.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693

**Comment by Tyriar** [comment]
@pastelmind What version of Windows are you on?

**Comment by Tyriar** [comment]
Also reported in https://github.com/Microsoft/vscode/issues/60256

**Comment by pastelmind** [comment]
I found a workaround: as mentioned [here](https://github.com/Microsoft/vscode/issues/60428#issuecomment-428886997), providing an environment variable `LESSCHARSET=utf8` solves the problem. To make the environment variable available to all VS Code instances, I added the following to my user settings (`settings.json`):

```json
{
    "terminal.integrated.env.windows": {
        "LESSCHARSET": "utf-8"
    }
}
```

Oddly enough, the problem does not occur when I run `git diff` directly in Git Bash, even though it does not have the `LESSCHARSET` environment variable set.

> @pastelmind What version of Windows are you on?

Windows 10 Enterprise (Korean) version 1803 (build 17134.345)

**Comment by pastelmind** [comment]
It seems that the issue is not restricted to Git diff results; the `ls` command also displays garbled characters for unicode (Korean) file names.

To fix the issue, use `LC_ALL=C.UTF-8` instead of `LESSCHARSET`.

In your `settings.json`:

```json
{
    "terminal.integrated.env.windows": {
        "LC_ALL": "C.UTF-8"
    }
}
```
