### ISSUE TITLE
syntax highlight fails

### ISSUE THREAD

**Issue by hasyee** [Microsoft/vscode#6036]
- VSCode Version: 1.0.0
- Win Version: 10

Steps to Reproduce:

1. insert this line somewhere:
`const directionCorrespondingRelations = direction > 0 ? [">", ">="] : ["<", "<="];`
2. after that line syntax highlight fails

If you replace the last array to a number example, then it truns to right

**Comment by rozzzly** [comment]
`.ts` or `.js`?

I'm assuming its `javascript`
I got the same error,
some other things that blow it up

```
const dcr = (direction > 0) ? ['>'] : ['<'];
const dcr = (direction > 0) ? '>' : ['<'];
const dcr = direction > 0 ? '>' : ['<'];
const dcr = (direction > 0) ? '>' : () => '<';
const dcr = direction > 0 ? '>' : () => '<';
const dcr = (direction > 0) ? '>' : (() => '<');
const dcr = direction > 0 ? 7 : 5;
```

but  this works:
```javascript
const dcr = direction > 0 ? 7 : 'foo';
const dcr = direction > 0 ? ['wtf'] : 'foo';
const dcr = direction === false ? ['wtf'] : 'foo';
const dcr = direction == 'wtf' ? ['wtf'] : 'foo';
```

looks like the only thing it wants on the `else` condition in the ternary is a string... strange.

**Comment by hasyee** [comment]
Yes, it's .js.

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#164
