### ISSUE TITLE
Unable to upgrade from 1.27.2

### ISSUE THREAD

**Issue by sumitkumarm** [Microsoft/vscode#60375]
Issue Type: <b>Bug</b>

I am unable to upgrade from 1.27.2 to the latest version. I keep getting the process in use error, and I have tried several times already.

ERRO Failed to create file handle: The process cannot access the file because it is being used by another process.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17763

<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.8.0
Go|ms-|0.6.90
vscode-docker|Pet|0.3.1
java|red|0.32.0
scala|sca|0.2.0
vscode-checkstyle|she|0.5.2
vscode-java-debug|vsc|0.13.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.9.0
vscode-maven|vsc|0.11.0

</details>

[vscode-inno-updater-1539018490.log](https://github.com/Microsoft/vscode/files/2461730/vscode-inno-updater-1539018490.log)
[vscode-inno-updater-1539018731.log](https://github.com/Microsoft/vscode/files/2461731/vscode-inno-updater-1539018731.log)
[vscode-inno-updater-1539019201.log](https://github.com/Microsoft/vscode/files/2461732/vscode-inno-updater-1539019201.log)
[vscode-inno-updater-1539109516.log](https://github.com/Microsoft/vscode/files/2461733/vscode-inno-updater-1539109516.log)
[vscode-inno-updater-1539109850.log](https://github.com/Microsoft/vscode/files/2461734/vscode-inno-updater-1539109850.log)

**Comment by brotherdust** [comment]
Same issue here. Screenshots attached.
<img width="307" alt="2018-10-09_13-02-28" src="https://user-images.githubusercontent.com/10413016/46692235-fee0b280-cbc3-11e8-8df1-7f4c4d4d1f86.png">
<img width="311" alt="2018-10-09_13-02-56" src="https://user-images.githubusercontent.com/10413016/46692236-fee0b280-cbc3-11e8-9f96-2fa6ac35cd95.png">
<img width="283" alt="2018-10-09_13-05-12" src="https://user-images.githubusercontent.com/10413016/46692237-fee0b280-cbc3-11e8-86be-5cdb2b0ede5e.png">
<img width="206" alt="2018-10-09_13-05-58" src="https://user-images.githubusercontent.com/10413016/46692273-17e96380-cbc4-11e8-9867-71413a005f8a.png">

**Comment by temelj** [comment]
https://github.com/Microsoft/vscode/issues/60393 <=== this is not related.

The issue here is a failure to install the VS Code update.

**Comment by mauskin** [comment]
In my case a restart of my machine helped.

**Comment by zyx4843** [comment]
Same issue here, restart my machine is no helped
error log is:
Oct 10 20:17:43.310 INFO Starting: E:\Program Files (x86)\Microsoft VS Code\Code.exe, false
Oct 10 20:17:43.311 ERRO Bad arguments: Code path doesn't seem to exist: E:\Program Files (x86)\Microsoft VS Code\Code.exe

**Comment by carlocardella** [comment]
Do you have files/folders open from OneDrive (not sure if Dropbox or the like have similar problems)? 
#55885

**Comment by sumitkumarm** [comment]
No, I am restarting from a state where the only files that are open are "Unsaved" files.
