### ISSUE TITLE
VS Code not picking up HTML tags after Razor code.

### ISSUE THREAD

**Issue by DanJ210** [Microsoft/vscode#60376]
Issue Type: <b>Bug</b>

Take a look at the screenshot. You can see <li> tags with a razor action link and then the closing <li> tags after that are not being picked up afterwards.

![Uploading VS-code_Razor.PNG…](HTML Tags not Picked Up)

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (5.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vue-peek|dar|1.0.2
vscode-eslint|dba|1.6.0
githistory|don|0.4.3
vscode-npm-script|eg2|0.3.5
vscode-great-icons|emm|2.1.44
prettier-vscode|esb|1.6.1
php-debug|fel|1.12.6
php-intellisense|fel|2.3.5
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
dotnet-test-explorer|for|0.5.4
beautify|Hoo|1.4.4
minify|Hoo|0.3.0
vscode-tfs|iva|0.6.0
nuget-reverse-package-search|jes|0.1.68
vscode-nuget-package-manager|jmr|1.1.6
docthis|joe|0.7.1
docomment|k--|0.1.2
dotnet-core-essentials|Kis|0.0.5
vscode-attrs-sorter|mrm|2.1.0
csharp|ms-|1.16.2
vsliveshare|ms-|0.3.735
vsliveshare-audio|ms-|0.1.32
team|ms-|1.136.0
debugger-for-chrome|msj|4.10.2
debugger-for-edge|msj|1.0.6
vuejs-extension-pack|mub|1.1.3
vetur|oct|0.13.0
vscode-docker|Pet|0.3.1
vscode-gitignore-generator|pio|1.0.1
tslint-vue|pro|1.5.6
vscode-format|rya|0.0.6
yo|sam|0.9.3
vscode-status-bar-format-toggle|tom|1.4.0
wilderminds-aspnetcore-snippets|wil|0.2.1
JavaScriptSnippets|xab|1.7.1

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
https://github.com/OmniSharp/omnisharp-vscode
