### ISSUE TITLE
Restart button no longer working (.dll's locked with "process cannot access the file" errors)

### ISSUE THREAD

**Issue by winzig** [Microsoft/vscode#60372]
In the last couple weeks I've started experiencing a problem with VS Code (Insiders) where the Restart button does not successfully restart the debugging process. Instead, I get this error over and over in the TERMINAL tab of vscode:

`/usr/local/share/dotnet/sdk/2.1.105/Microsoft.Common.CurrentVersion.targets(4118,5): warning MSB3026: Could not copy "obj/Debug/netcoreapp2.0/Web.dll" to "bin/Debug/netcoreapp2.0/Web.dll". Beginning retry 1 in 1000ms. The process cannot access the file '/Users/tom/Documents/Repositories/code/Web/bin/Debug/netcoreapp2.0/Web.dll' because it is being used by another process.  [/Users/tom/Documents/Repositories/code/Web/Web.csproj]`

- VSCode Version: Version 1.29.0-insider (1.29.0-insider)
- OS Version: macOS High Sierra 10.13.6 (17G65)

Steps to Reproduce:

1. Hit the "Play" button to start debugging a .NET Core web project
2. After a while, hit the Restart button to restart debugging
3. See the above error over and over in the terminal tab
4. Give up and hit the stop button, followed by the start button.

Does this issue occur when all extensions are disabled?: Unknown. When I tried to launch code-insiders with no extensions loaded, I get an error "Configured debug type 'coreclr' is not supported."

**Comment by winzig** [comment]
@vscodebot I checked that issue and it doesn't seem related to me. That one seems to be related to node.

**Comment by egamma** [comment]
This issue related to the c# extension and its debugger, please file the issue against this extension.

**Comment by winzig** [comment]
OK, for anyone that stumbles across the issue in the future, I opened an issue with the C# extension: https://github.com/OmniSharp/omnisharp-vscode/issues/2596

**Comment by gregg-miskelly** [comment]
This is actually a VS Code issue. See https://github.com/Microsoft/vscode/issues/60593
