### ISSUE TITLE
```json  { 	"activationTimes": { 		"startup": true, 		"codeLoadingTime": 6, 		"activateCallTime": 0, 		"activateResolvedTime": 0, 		"activationEvent": "*" 	} } ```

### ISSUE THREAD

**Issue by cookcm** [Microsoft/vscode#60370]
- Extension Name: debug-auto-launch
- Extension Version: 1.0.0
- OS Version: Darwin x64 17.7.0
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:

**Comment by mjbvz** [comment]
See #60318
