### ISSUE TITLE
Ability to add scratch files in vscode 🔥

### ISSUE THREAD

**Issue by siwalikm** [Microsoft/vscode#60377]
Like intellij and most modern IDE does, scratch files are immensely helpful for any dev. project.

What?
Scratch files are just new files which you create while in a project but it is stored in some temp directory outside workspace, so it doesn't come up in git diff.

Why?
Almost all the time while working on something, we create a new file to try out some idea or write down a snippet. Not necessarily this file is a part of the current workplace but this is something we need to keep open or reference. So only option is to mark this file as unchanged or stash and re-apply every single time after a commit.

How?
While creating a new file, it can by default be a scratch file always, from some temporary directory. Only on trying to save it, we might ask the user to chose folder or path.

**Comment by egamma** [comment]
Given the VS Code supports hot exit (dirty files are saved for you) this is already supported. Just create an untitled file and you do not even get prompted on exit. Please give this a try, this is how I work with scratch files all the time.
