### ISSUE TITLE
can't parse special characters.

### ISSUE THREAD

**Issue by bearuse** [Microsoft/vscode#60388]
Issue Type: <b>Bug</b>

when I use '\"', it can't parse properly. below sentences' color is not matched.

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2194)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (1.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-great-icons|emm|2.1.44
capl-vector|kma|0.1.1
clangcomplete|kub|1.0.1
vscode-language-pack-ko|MS-|1.28.2
cpptools|ms-|0.19.0
reloaded-cpp|rel|0.1.6
vscode-icons|rob|7.27.0
vscode-hexdump|sle|1.7.0

(13 theme extensions excluded)

</details>

**Comment by egamma** [comment]
Where is the color not properly matched. Please provide more information and a screenshot that illustrates the problem.
