### ISSUE TITLE
Unable to find project.json or *.csproj if there are multiple *.csproj

### ISSUE THREAD

**Issue by duongphuhiep** [Microsoft/vscode#60381]
Issue Type: <b>Bug</b>

"Create a new C# class" failed "Cannot find *.csproj or project.json" => however the .csproj is right here..

![image](https://user-images.githubusercontent.com/1638594/46692686-383b1180-cc08-11e8-90dd-348663926d20.png)

Extension version: 1.3.0
VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:11:15.873Z)
OS version: Linux x64 4.4.0-137-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 3499)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|15.56GB (2.50GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by mjbvz** [comment]
Please file this issue against the c# extension
