### ISSUE TITLE
Can't navigate to "find" field of replace widget with shift-tab

### ISSUE THREAD

**Issue by itsravenous** [Microsoft/vscode#6038]
- VSCode Version: 0.10.6
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Press `Ctrl-H` to open replace widget
2. Realise you want to edit the "find" field
3. Press `Shift-Tab` repeatedly
4. Focus just cycles between the close and replace buttons

Interestingly, cycling using `Tab` goes around more of the buttons, but then tabs out of the widget and starts inserting tabs in the document (see end of screencast)

![replace_blackbird](https://cloud.githubusercontent.com/assets/1737376/14952766/3d1803f4-105b-11e6-8a7d-a4eb0a47736c.gif)

In conjunction with #4566, makes for a very frustrating experience :) I don't mind the "replace" field being focused by default, as long as I can `Shift-Tab` to the "find" field if what I want isn't in there.

**Comment by itsravenous** [comment]
For anyone looking for a workaround in the meantime: `Ctrl-F` opens the same widget, but with the "find" field focused. You can also press `Ctrl-F` after you've opened the widget with `Ctrl-H` to shift the focus to "find"

**Comment by alexandrudima** [comment]
@itsravenous You are on a really old version of VSCode, please update to 1.0.0, we have made a ton of improvements since 0.10.6 (including fixing lots of issues in the find widget).

**Comment by itsravenous** [comment]
Thanks - I had checked the releases page here (where the version numbers seem different) but didn't think to check the main website.

**Comment by alexandrudima** [comment]
Good point, I have created #6175 to look into improving our process.
