### ISSUE TITLE
TS JavaScript intellisense completely off

### ISSUE THREAD

**Issue by marvinhagemeister** [Microsoft/vscode#60385]
- VSCode Version: 1.29.0-insider 5bd6ebe2dbc4dee510699020a25f70a69784ce8c
- OS Version: Mac OSX Mojave

This always seems to happen when quickly typing jsdoc types, especially with `@type`. When it happens intellisense seem to be applied to a cached version of the current document which doesn't match the current changes anymore. It's a bit hard to explain, so here is a gif showing it:

![vscode_intellisense](https://user-images.githubusercontent.com/1062408/46694936-6de2f900-cc0e-11e8-80e6-4bf458e5dd33.gif)

Note for example that instead of showing `_previousVTree` in the tooltip, it displays `reviousVTree` as an object key instead. The same bug occurs for me when launching the insiders build with all extensions disabled.
 
Steps to Reproduce:

1. Open some JS code
2. Quickly create or modify `@type` jsdoc comments

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Are you using any typescript server plugins, such as styled or lit-html?

**Comment by marvinhagemeister** [comment]
@mjbvz No, this issue occurs for me in stock vscode without any extensions installed. Just verified that with a fresh install.

**Comment by marvinhagemeister** [comment]
Narrowed the steps to reproduce it down a bit. I'm using the stock insider builds without any extensions installed.

1. Enable `javascript.implicitProjectConfig.checkJs` so that TS will check the js
2. Create an `internal.d.ts` file with the following content:

```ts
export interface Foo {
  foo: number;
  bar: number;
}
```

3. Create another js file this time and create a type violation. Something like:

```js
/** @type {import('./internal').Foo} */
const a = 2;
```

4. Add a second **valid** variable:

```js
/** @type {import('./internal').Foo} */
const a = 2;

/** @type {import('./internal').Foo} */
const b = {
  foo: 2,
  bar: 2,
};
```

5. Comment out the first variable:

```js
// /** @type {import('./internal').Foo} */
// const a = 2;

/** @type {import('./internal').Foo} */
const b = {
  foo: 2,
  bar: 2,
};
```

At this point the intellisense is off. It still things the first variable is __not__ commented out and gives wrong autocompletion from this point forward.

Video demonstration:
![vscode_intellisense2](https://user-images.githubusercontent.com/1062408/46783988-b4c71080-cd2c-11e8-8d8a-f44b051596a4.gif)

**Comment by mjbvz** [comment]
Thanks for the detailed repo steps. Can I repo this in the current vs code insiders but not if I update the workspace to use the latest version of typescript

Can you please try upgrading your workspace to use `typescript@next` by following [these instructions](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions) and seeing if you are still able to reproduce this error

**Comment by mjbvz** [comment]
Closing as upstream /  fixed by typescript@next
