### ISSUE TITLE
Reserved file names allowed.

### ISSUE THREAD

**Issue by jk8jk8** [microsoft/vscode#60383]
I can create a source file named aux.rs (aux is among reserved file names under Windows) as well as rename existing files to a reserved file name.

While an error message is produced by an attempt to use a file name that contains a reserved character (eg. a question mark), no such error is reported when using reserved names, which are allowed silently. Programs fail to compile due to the invalid file name being used.

- VSCode Version: 1.28.0
- OS Version: Windows 10.0.17134 Build 17134

Steps to Reproduce:

1. Create source file aux.rs within a VS Code Rust project; or
2. Rename an existing file to aux.rs within a Rust src folder in VS Code.

Does this issue occur when all extensions are disabled?: Yes, same situation.

**Comment by bpasero** [comment]
I guess this is from the file explorer.

**Comment by isidorn** [comment]
I do not really see the downside of allowing reserved files to be created via the explorer.
Does windows explorer allow you to create such a file? I believe yes.

Anyways leaving this open as a feature request

**Comment by jk8jk8** [comment]
The downside is that you can be spending a while searching your code for the reason why your program doesn't compile, when the problem is not the code but the OS refusing to send the misnamed file to the compiler (or something like that). In my case I had to find help online and it still took a while before someone spotted the problem. I'm not sure how it was possible for the file system to accept an illegal name in the first place.

**Comment by bensladden** [comment]
In my case i created a file named con.js. in windows. Everything was fine (including building & running the application) however when running git add . the system would freeze. It took a awhile to work out what was going on.
