### ISSUE TITLE
CRITICAL BUG in 1.28.0 and later Preventin RELOAD/LUNCH WITOUT INTERNET

### ISSUE THREAD

**Issue by 07pepa** [Microsoft/vscode#60384]
There is bug in https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-browser/workbench/workbench.js#L9  or  in  used library

if you lose conection you can't reload or lunch visual studio code  tested on windows 10 but probable on all OS

[error in console](http://prntscr.com/l45nbd)

Steps to Reproduce:

1. lose conection to internet
2. reload or lunch vs code

**Comment by sboh1214** [comment]
It will solve if you install exploration build which use Electron 3.0.x
Also this is already existing issue [https://github.com/Microsoft/vscode/issues/7570](https://github.com/Microsoft/vscode/issues/7570)
Here is newer electron build [https://github.com/Microsoft/vscode/issues/7570#issuecomment-422815878](https://github.com/Microsoft/vscode/issues/7570#issuecomment-422815878)

**Comment by 07pepa** [comment]
@sboh1214  already using 1.28.0 .... and it hapen also nigtly so @bpasero  it is not duplicate
