### ISSUE TITLE
"Install types" helper should detect yarn

### ISSUE THREAD

**Issue by tlycken** [Microsoft/vscode#60386]
Issue Type: <b>Bug</b>

Run the following commands:

```
yarn init -y
yarn add node-fetch
echo "const fetch = require('node-fetch')" > foo.js
```

When opening `foo.js`, a suggestion (the little lightbulb menu) pops up to install `@types/node-fetch`. However, if you choose to do so, it uses `npm` rather than `yarn` (creating a `package-lock.json` and leaving `yarn.lock` untouched).

It would be nice if it could correctly dtect which package manager to use (e.g. by the presence of `yarn.lock`).

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
prettier-vscode|esb|1.6.1
Ionide-FAKE|Ion|1.2.3
Ionide-Paket|Ion|1.12.0
language-julia|jul|0.10.3
csharp|ms-|1.16.2
PowerShell|ms-|1.9.0
aspnet-helper|sch|0.6.4
shell-launcher|Tyr|0.2.0
vscode-import-cost|wix|2.9.0

</details>

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/Microsoft/TypeScript/issues/19269
