### ISSUE TITLE
Docs: Explain `scope` Field within `configuration` Contribution Point...

### ISSUE THREAD

**Issue by busticated** [Microsoft/vscode#60399]
the docs for the `configuration` contribution point make no mention of the `scope` field - yet we are warned about setting it / not setting it under certain circumstances. what does `scope` do?

docs:
https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesconfiguration

example:
https://github.com/Microsoft/vscode-extension-samples/blob/master/configuration-sample/package.json#L42

warning:
https://github.com/Microsoft/vscode/issues/36623
https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs#run-time-diagnostics

thanks 🙏

**Comment by KamasamaK** [comment]
This issue was supposed to be created in [Microsoft/vscode-docs](https://github.com/microsoft/vscode-docs/issues).

**Comment by busticated** [comment]
ah, whoops! thanks @KamasamaK 

closing
