### ISSUE TITLE
Typescript: Can't rename `size` property

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#60392]
Create the following interface in our sources:

```ts
interface foo {
	size: number;
}
```

Attempt to rename `size`:

![image](https://user-images.githubusercontent.com/22350/46698517-9fac8d80-cc17-11e8-8a92-efd89884f698.png)

Use any other property name, and rename will work.

**Comment by mjbvz** [comment]
Very mysterious why only `size` seems to trigger this. Opened https://github.com/Microsoft/TypeScript/issues/27663 to track this upstream

**Comment by joaomoreno** [comment]
Halloween is coming. 👻
