### ISSUE TITLE
Prefix CSS in vscode

### ISSUE THREAD

**Issue by younesnes** [Microsoft/vscode#60398]
Hii
I see any time i want to make css prefix with emmet abbreviations in vscode give me something like this : 
 
![capture1](https://user-images.githubusercontent.com/25667175/46700421-b4d3ed00-cc14-11e8-84e7-36c750df9b1a.PNG)

but when i tape the same emmet abbreviations " df " in Sublime text 3 or Bracket give me like this : 

![capture2](https://user-images.githubusercontent.com/25667175/46700625-39267000-cc15-11e8-9ee0-b5627ab93fc4.PNG)

![capture3](https://user-images.githubusercontent.com/25667175/46700633-404d7e00-cc15-11e8-8b77-d825d55fa548.PNG)

I love to add this Feature ( add the exact "all prefix" in the CSS abbreviations ) in the next update because is very interessting for web integration.
I find my self and other friends in my agency stuck in Bracket to make a web pages and switch to vscode for other works.

Thanks

**Comment by ramya-rao-a** [comment]
@younesnes 

Can you explain the difference between `display: -webkit-flex` and `-webkit-display: flex`? Perhaps point me to some documentation around it?
