### ISSUE TITLE
Building for Launch Extension never finishes

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode#60396]
Issue Type: <b>Bug</b>

I've been having this trouble the last couple of days only (both insiders and vscode).  Press F5 shows that it's trying to launch, but the "Building..." step never finishes.
![image](https://user-images.githubusercontent.com/6913354/46699372-73205380-cbce-11e8-90e1-f4ff36e0129c.png)

1) git clone https://github.com/Microsoft/vscode-docker.git
2) cd vscode-docker
3) npm install
4) npm run build and verify that building works
5) start up vscode from scratch
6) open folder in vscode
7) build or F5
!) Build step never completes

It's not fully consistent, and once it works, it seems to continue working until I reload.

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.73GB (14.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by StephenWeatherford** [comment]
This is happening most of the time for me right now.  The work-around is to restart the build task.

**Comment by StephenWeatherford** [comment]
"typescript": "^3.1.1",

I removed the globally installed typescript, so it should be using that.  Still repros.

**Comment by StephenWeatherford** [comment]
Okay, actually I have no idea which version is actually being used.  I've added "typescript.tsdk": ".\\node_modules\\typescript\\lib" to settings, but even though I removed this path I get no errors from vscode.  I don't see a notification in the status bar about the typescript version...  How about I supposed to tell?

**Comment by dbaeumer** [comment]
@StephenWeatherford when this happens can you provide the output of the terminal running the build task?

**Comment by StephenWeatherford** [comment]
It seems to have gone away, so I guess it was fixed.  Thanks!

**Comment by StephenWeatherford** [comment]
This is still reproing very consistently the first time I try to F5

**Comment by dbaeumer** [comment]
Can you provide the terminal output when this happens.
