### ISSUE TITLE
Cmd + Enter to commit no longer works on macOS

### ISSUE THREAD

**Issue by Zlass** [Microsoft/vscode#60395]
Issue Type: <b>Bug</b>

1. Type a commit message in the source control tab

2. Use Cmd + Enter hotkey to perform a commit

Nothing happens ☹️

3. Press the Checkmark icon and it commits properly

Not a huge issue but deffintly an annoying bug.

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-04T16:40:40.180Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 3|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|-psn_0_274499|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.1
arepl|alm|1.0.1
vscode-color|ans|0.4.5
swagger-viewer|Arj|2.0.2
vscode-database|baj|1.5.2
vscode-custom-css|be5|3.0.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.60
vscode-svgviewer|css|1.4.6
vscode-eslint|dba|1.6.0
es7-react-js-snippets|dsz|1.8.6
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.4.2
prettier-vscode|esb|1.6.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.4
vscode-mysql|for|0.3.0
vscode-auto-open-markdown-preview|hnw|0.0.4
beautify|Hoo|1.4.4
mysql-syntax|jak|1.3.1
svg|joc|0.1.4
vscode-styled-components|jpo|0.0.22
vscode-github|Kni|0.30.0
MagicPython|mag|1.1.0
sort-typescript-imports|mic|1.4.1
theme-monokai-pro-vscode|mon|1.1.8
python|ms-|2018.8.0
color-highlight|nau|2.3.0
autodocstring|njp|0.2.3
vscode-docker|Pet|0.3.1
material-icon-theme|PKi|3.6.0
vscode-icons|rob|7.27.0
stylelint|shi|0.43.0
guides|spy|0.9.2
autoimport|ste|1.5.3
code-spell-checker|str|1.6.10
language-stylus|sys|1.10.0
html-preview-vscode|tht|0.2.4
wallaby-vscode|Wal|1.0.96
jinja|who|0.0.8

(5 theme extensions excluded)

</details>

**Comment by agurodriguez** [comment]
Hi @Zlass! I'm running the same VS Code and OS version and I'm not being able to reproduce it.

Could try running VS Code with all the extensions disabled?

You can quickly do that by clicking the link shown in the image below:

<img width="812" alt="screen shot 2018-10-09 at 9 09 32 pm" src="https://user-images.githubusercontent.com/13837769/46705863-d4184d80-cc07-11e8-8efa-863291abd211.png">

**Comment by Zlass** [comment]
Yup you're right, my bad. Time to figure out which extension is the culprit.
