### ISSUE TITLE
1.28.0 unable to open terminal

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#60393]
- VSCode Version: 1.28.0
- OS Version: Windows 10

Steps to Reproduce:

1. Install 1.28.0 in user mode
2. Open and launch terminal

Does this issue occur when all extensions are disabled?: Yes

It errors with:

```sh
The terminal process command 'C:\Program Files\Git\bin\bash.exe' failed to launch (exit code: 2)
```

The same goes for `cmd.exe` (the default).

By the way, in Windows, when I try to upgrade from background it fails with 

![image](https://user-images.githubusercontent.com/3254987/46698571-584cdf80-cbcc-11e8-913f-3802d272d5b4.png)
There ARE other instances of VSCode running by other users. But no instance is running for the current user. That's probably a separate bug.

**Comment by unional** [comment]
For the upgrade issue, it is mentioned and tracked in https://github.com/Microsoft/vscode/issues/60375

**Comment by Tyriar** [comment]
Does this path exist `C:\Program Files\Git\bin\bash.exe`? exit code 2 means the path doesn't exist. For cmd.exe what path are you using to test this? Are you on a corporate locked down machine?

**Comment by unional** [comment]
Yes it exists. When downgrade back to 1.27.2, it works fine. 
the same problem when I switch back to `cmd.exe` it's the basic command prompt.
The paths are correct and it is not in a locked down machine.

**Comment by unional** [comment]
This issue still exists in 1.28.2

**Comment by Tyriar** [comment]
Ok, let me know if you see it again. Closing for now.

**Comment by unional** [comment]
The corruption is due to https://github.com/Microsoft/vscode/issues/60375, so will see what happen after that is fixed.

**Comment by unional** [comment]
Said too soon. After I close VSCode and reopen it, the issue still exists. So it is not related to upgrade.

Please reopen.

**Comment by unional** [comment]
This is related to Workspace.

I have an additional setting in the workspace file:

```
{
  "settings": {
    "terminal.integrate.cwd": "..."
   }
}
```

That path is valid when the active project is "project-a" (I have "project-a" and "project-b" in the workspace) but not "project-b".

When the "project-b" is active (i.e. the currently active file is in "project-b"), the said path is invalid and causing the terminal fails to open (code 2).

In 1.27, the terminal opens and default to the root of the active project.
