### ISSUE TITLE
Add more reusable types for CSS Intellisense 

### ISSUE THREAD

**Issue by dstorey** [Microsoft/vscode#604]
There are a lot of parts of CSS that are reused in multiple properties, that get duplicated in the XML file, leading to code bloat and risk of inconsistencies.

The most obvious one are the colour keywords which are repeated 42 times in css-scheme.xml alone (and there are a lot of colours!, and they're included in other files on top), but there are others such as border-style values (that are in column-rule, etc.), timing functions (transitions, animations, etc)

Some things already are reused, such as the length units, and hsla,rgba, etc. Would be nice to expand this.

**Comment by dstorey** [comment]
There is a color restriction but the colours are often repeated inside anyway, so I need to test if these are needed or are just there for legacy reasons.

**Comment by aeschli** [comment]
css-scheme.xml is not part of the runtime. It is a 3rd party file we get from the IE team. We use it to create 'browsers.js' out of it, which is the data that drives attributes and value intellisense for css/less/sass.
'browsers.js' is optimized, colors are stripped out, attributes that are not supported by at least 2 browsers are stripped out (replaced with 'restriction: enum'), descriptions that are used more than once are in a shared description table. 
The script that does that is 'generate_browsers.js'. What ends up in the build and runtime is only browser.js.
Colors and units are managed in '/languageFacts.ts', and only exist there.
So I think we're pretty well optimized, maybe there's some more value sets in browsers that we can take out and share, but I think we're fine.

@dstorey Closing, please comment if you disagree and see more potential for improvement.
