### ISSUE TITLE
Allow background token colors

### ISSUE THREAD

**Issue by Zooce** [Microsoft/vscode#60408]
This is a feature request for allowing color themes to give background colors to tokens. This is possible in Sublime Text as seen in the screenshot below.

_See the background color on the comments._
![background_token_color_sublime_text](https://user-images.githubusercontent.com/5490155/46704758-53def180-cbe1-11e8-8b48-e8c4dbd71187.png)

_*If there is a similar feature request already open, my apologies, I couldn't find one about this._

**Comment by usernamehw** [comment]
Duplicate of #3429

**Comment by Zooce** [comment]
Thanks, @usernamehw - didn't see that one.
