### ISSUE TITLE
URLs with `:` in them are not "clickable" in terminal

### ISSUE THREAD

**Issue by benlesh** [Microsoft/vscode#60401]
Issue Type: <b>Bug</b>

echo any url that has a semicolon in in the path (not the querystring, that appears to work):

```shell
echo https://www.example.com/this:is:a:test?whatever=go
```

Then try CTRL+click on the echo'ed link.

It'll send you to `https://www.example.com/this`, excluding the rest of the URL.

At google we have a lot of debugging URLs with semicolons in them, and they don't work from VS Code terminal.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:11:15.873Z)
OS version: Linux x64 4.17.0-3rodete2-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 2661)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.39GB (4.31GB free)|
|Process Argv|/usr/share/code/code .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
bazel-code|Dev|0.1.9
mustache|daw|1.1.1
tslint|eg2|1.0.39
g3|eva|0.0.8
python|ms-|2018.9.0
vsliveshare|ms-|0.3.735
vscode-icons|rob|7.27.0
vscode-import-cost|wix|2.9.0

(2 theme extensions excluded)

</details>

**Comment by jrkong** [comment]
@Tyriar I was looking into this issue and I believe changing https://github.com/xtermjs/xterm.js/blob/5bc7fc4256edac39eeb340ec21f6ba0c4d877e00/src/addons/webLinks/webLinks.ts#L17 to 
`(\/[\/\w\.\-%~:]*)*` should fix it. Would there be any side effects to me doing so?
