### ISSUE TITLE
Font rendering/scaling issue in Linux, integrated terminal

### ISSUE THREAD

**Issue by maxwellb** [Microsoft/vscode#60409]
- [x] `<!-- Please search existing issues to avoid creating duplicates. --> `
- [x] `<!-- Also please test using the latest insiders build to make sure your issue has not already been fixed: https://code.visualstudio.com/insiders/ -->` 

- VSCode Version: 1.28.0, 1.29.0-insider
- OS Version: Ubuntu 18.04, Xpra 2.1.3 server, Xpra 2.3.4 client

Steps to Reproduce:

1. Install code
2. Connect Xpra (may be reproduced without, but I cannot check)
3. Open code (`export DISPLAY=:100`)
4. Open integrated terminal

Observe incorrect font scaling/rendering in bash on code 1.28.0+. I observed the regression by comparing to another server I had installed code on last week.

Installing 1.27 from deb on the affected server resolved the issue.

![compare](https://user-images.githubusercontent.com/3590441/46705737-e3df6400-cbfe-11e8-951e-25f478c46323.PNG)
![compare2](https://user-images.githubusercontent.com/3590441/46705738-e3df6400-cbfe-11e8-8520-fcb76be052e9.PNG)
![compare3](https://user-images.githubusercontent.com/3590441/46705739-e477fa80-cbfe-11e8-9371-980c9fdcfa66.PNG)
![compare4](https://user-images.githubusercontent.com/3590441/46705740-e477fa80-cbfe-11e8-857b-6a1bf716370a.PNG)
![compare5](https://user-images.githubusercontent.com/3590441/46705742-e477fa80-cbfe-11e8-9d87-9eb8812ff071.PNG)
![compare6](https://user-images.githubusercontent.com/3590441/46705743-e477fa80-cbfe-11e8-9833-432f8626790b.PNG)

- [x] <code></code>
- [x] Does this issue occur when all extensions are disabled?: **(Yes)**~/No~

**Comment by Tyriar** [comment]
It looks like this is probably related to the Ubuntu Mono hack here: https://github.com/Microsoft/vscode/pull/56429

I'll add a fallback just in case the font isn't present.

**Comment by Tyriar** [comment]
Fixed in https://github.com/Microsoft/vscode/commit/dcd3744554fbfa343ca5b858480cfde0e66cae01

@maxwellb if you could verify that works in tomorrow's Insiders build that would be helpful 😃

**Comment by maxwellb** [comment]
The issue appears to be resolved. Thank you!
![screenshot 2018-10-13 at 3 31 53 pm](https://user-images.githubusercontent.com/3590441/46909253-3c637980-cefd-11e8-8616-e2d5b8223aed.png)
