### ISSUE TITLE
version 1.28 wipes out cortex-debug extension

### ISSUE THREAD

**Issue by myxyplyxyt** [Microsoft/vscode#60405]
Issue Type: <b>Bug</b>

Use of cortex-debug extension with arm tools gdb on external embedded system works with VSCode debug front end in version 1.27.2 on Windows, Ubuntu, and OSX.

As soon as version 1.28 is loaded the cortex-debug extension no longer works.

How can I contact person responsible for cortex-debug?

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-04T16:40:40.180Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 1, 0|
|Memory (System)|16.00GB (8.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cortex-debug|mar|0.1.21

</details>

**Comment by mjbvz** [comment]
Please start by filing this issue against that extension: https://github.com/Marus/cortex-debug/issues
