### ISSUE TITLE
VSCode Version 1.28.0 is crashing very often

### ISSUE THREAD

**Issue by caradong** [Microsoft/vscode#60403]
Issue Type: <b>Bug</b>

open VScode, do some work, and it crashes very often.

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.79GB (9.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.5.6
tslint|eg2|1.0.39
prettier-vscode|esb|1.6.1
typescript-hero|rbb|2.3.2

</details>

**Comment by EklipZgit** [comment]
Getting a crash when ctrl+P searching for files (in a large, multi folder workspace). File search seems slower than before 1.28, and now the search crashes and VSCode hangs until the reopen prompt if I ctrl+p and search after it has been open for more than a few minutes.

ver: 1.28.0
Exts:
Azure Repos 1.142.0
Git History 0.4.3
Git Merger 0.4.1
gitignore 0.5.0
GitLens 8.5.6
JSon Schema Validator 0.1.0
Partial Diff 1.4.0
Powershell 1.9.0
XML Format 1.0.0

**Comment by roblourens** [comment]
@caradong can you provide more details? Are you also searching with ctrl+p?

@EklipZgit could you open your own issue, and tell me as many details as possible about what you're seeing?

**Comment by EklipZgit** [comment]
Opened https://github.com/Microsoft/vscode/issues/60672

**Comment by caradong** [comment]
@roblourens it crashed a few times when when ctrl+P searching. It also crashed a few times while editing the files. Extensions: GitLens; TsLint

**Comment by roblourens** [comment]
@lijqh Please open a new issue.

@caradong Can you please try the Insiders build to see if your problem still exists? Fixed an issue with crashing when using ctrl+p.

If not, please provide as many details as possible.

**Comment by haugerbr** [comment]
As of 1.28.2 the Ctrl+P freezing still exists and seems to have started when 1.28 was released. So seems like #60672 did not fix the issue.

**Comment by roblourens** [comment]
@haugerbr could you open a new issue? Please add as many details as possible like how many folders are in your workspace, are they large folders, exactly what you do to see the freeze, etc. Thanks!

I fixed "something" but can believe that some issue still exists. I am closing this issue because it's all tied up in the previous discussion before 1.28.2

**Comment by haugerbr** [comment]
@roblourens #62082 has a dump of the information from report issue in vscode.
