### ISSUE TITLE
PowerShell process

### ISSUE THREAD

**Issue by liwangqian** [Microsoft/vscode#60414]
A lot of PowerShell Process created and do not exit when doing symbol searching.

**Comment by liwangqian** [comment]
It seems the PowerShell process created during debuging, a lot!
![image](https://user-images.githubusercontent.com/19996314/46714278-35cecb00-cc8d-11e8-8474-ea37a7f34470.png)

Vscode 1.28.0(system setup)

**Comment by Tyriar** [comment]
Can you run code --status in a terminal when you're seeing this and paste in the process tree?

**Comment by Tyriar** [comment]
Also include the language of the file(s) and your extension list.
