### ISSUE TITLE
Unexpected layout is displayed

### ISSUE THREAD

**Issue by tetsugi** [Microsoft/vscode#60416]
- VSCode Version: 1.28.0
- OS Version: Windows_NT x64 10.0.16299

The problem is that another layout is displayed frequently like the following gif animation:

![vscode](https://user-images.githubusercontent.com/38849987/46707382-a1586e80-cc74-11e8-9c6b-47794a0a8ad5.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
@bpasero any idea of this issue, it looks like a chromium/rendering issue to me.

**Comment by tetsugi** [comment]
I tried to reproduce this issue with VSCode Exploration Builds 1.28.0(Windows) installed on this computer, but it did not reproduce.
It became difficult to provide more info because I do not have this computer that can reproduce this issue anymore.
