### ISSUE TITLE
Keyboard setting configuration layout issue

### ISSUE THREAD

**Issue by mifas** [Microsoft/vscode#60415]
Issue Type: <b>Bug</b>

In Keyboard Shortcut page, When I search something, the row is not appearing in a proper way

![peek 2018-10-10 09-29](https://user-images.githubusercontent.com/4384874/46708081-8e8f6b00-cc6f-11e8-9c83-a902681208c3.gif)

VS Code version: Code - Insiders 1.29.0-insider (5bd6ebe2dbc4dee510699020a25f70a69784ce8c, 2018-10-09T09:26:47.491Z)
OS version: Linux x64 4.15.0-36-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 2521)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|15.55GB (1.69GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.1
Bookmarks|ale|9.1.0
project-manager|ale|9.0.1
vscode-color|ans|0.4.5
snapshot-tools|asv|0.1.2
htmltagwrap|bra|0.0.7
turbo-console-log|Cha|1.2.10
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.60
vscode-eslint|dba|1.6.0
vscode-quick-select|dba|0.2.7
gitlens|eam|8.5.6
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.39
vsc-material-theme|Equ|2.4.2
prettier-vscode|esb|1.6.1
vscode-todo-plus|fab|4.8.1
auto-rename-tag|for|0.0.15
vscode-favorites|how|1.4.0
sublime-babel-vscode|jos|0.2.10
vscode-styled-components|jpo|0.0.22
expand-region|let|0.1.2
vscode-language-babel|mgm|0.0.20
vscode-wrap-console-log|mid|1.6.2
dotenv|mik|1.0.1
sublime-keybindings|ms-|4.0.0
debugger-for-chrome|msj|4.10.2
snippet-creator|nik|0.0.5
vscode-jest|Ort|2.9.2
vscode-docker|Pet|0.3.1
vscode-versionlens|pfl|0.21.2
material-icon-theme|PKi|3.6.0
vscode-icons|rob|7.27.0
code-settings-sync|Sha|3.1.2
vscode-fileutils|sle|2.11.0
code-spell-checker|str|1.6.10
blueprint|tea|2.2.0
ReactSnippetsStandard|Tim|1.1.0
vscode-status-bar-format-toggle|tom|1.4.0
sort-lines|Tyr|1.7.0
vscode-import-cost|wix|2.9.0
vscode-jumpy|wma|0.3.1

(9 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
I cannot reproduce this. Please try out new insiders and see if it is fixed.
