### ISSUE TITLE
Error dialog cuts off message

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#6041]
- VSCode Version: 1.1
- OS Version: Linux

Steps to Reproduce:

Follow the steps of #5784 I get the following error dialog when launching the debugger (after step 3)
![image](https://cloud.githubusercontent.com/assets/6461412/14954532/5f20d242-1073-11e6-8106-f5a36ee57754.png)

The interesting part of the message is cut off.
-> Make the hover message longer.
-> Put the message to an output as well

**Comment by isidorn** [comment]
This is a native chrome hover which has a size limit on linux. 
Closing as will not fix
