### ISSUE TITLE
VsCode can open ".code-workspace" as plain text

### ISSUE THREAD

**Issue by ljporljp** [Microsoft/vscode#60418]
Now that opening the workspace file just open the saved workspace but not purely open the text file itself, can you lovely guys give one more choice that allowing us choose to do what action for the workspace file?

**Comment by bpasero** [comment]
@ljporljp you can do File >Open to open a workspace file as text. Also, when you have opened a workspace, there is a command to show the workspace file.

**Comment by ljporljp** [comment]
I mean context menu that right clicked "Open with Code" or the drag to open action can give me another choice to open the workspace file as plain text. But thanks for pointing the command way, I really don't know that.
