### ISSUE TITLE
what‘s the difference between user version and system version

### ISSUE THREAD

**Issue by SuperChild191** [Microsoft/vscode#60410]
Issue Type: <b>Feature Request</b>

I want to know the difference between user version and system version. Besides, if I want to download the old version of  VS code of a system version, I can not find the download link. The updates catagory can only download the user version of the old versions of VS code. Where can I find the download link   of the system version of the old VS Code.

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 10.0.17763

**Comment by beastdestroyer** [comment]
The difference between the 2 is that User Install doesn't require any Admin permissions to update, install etc,and is only available for one person (the user who downloaded it) whereas System makes it available to everyone on yoir PC, but DOES require admin permission.

All downloads are here: [https://code.visualstudio.com/#alt-downloads]

**Comment by egamma** [comment]
@beastdestroyer thanks for answering the question.
