### ISSUE TITLE
Not Responding while using Go To File (Ctrl + P)

### ISSUE THREAD

**Issue by fallXone** [Microsoft/vscode#60425]
- VSCode Version: 1.28.0
- OS Version: Windows 10 Pro 10.0.16299 Build 16299

Steps to Reproduce:

1. Have a large workspace / folder opened
2.  Use the Go To File hotkey (Ctrl + P)
3. Type quickly to search for files
4. Repeat until VS Code goes not responding - sometimes this happens quicker than other times

Does this issue occur when all extensions are disabled?: Yes

Attached is a screenshot of what I'm seeing. I've been experiencing this issue for several months now and finally got around to posting about it, as I can't take it anymore. When searching for files, VS Code goes not responding all the time. I believe it's related to typing fast while having a large number of files in my workspace/folder. It occurs with all extensions disabled. VS Code goes not responding for me 10+ times on a daily basis. Sometimes as soon as I reopen after VS Code freezing, it will freeze immediately when I go to search for a file again when I begin to type. It's also important to note that we have a very large project with a ton of files.

![image](https://user-images.githubusercontent.com/5201384/46710285-3592e900-cc15-11e8-8a88-3546c4dde987.png)

**Comment by roblourens** [comment]
I haven't seen this one before, is your computer low-powered or have a single core?

**Comment by fallXone** [comment]
Nope, definitely not. Here are my system specs:
![image](https://user-images.githubusercontent.com/5201384/46731287-487add00-cc58-11e8-93c0-67243b2963ec.png)

**Comment by roblourens** [comment]
So your workspace is very large? Have you ever seen it in a smaller workspace? Does it ever start responding again if you wait?

It's weird that the renderer process would stop responding because the amount of data sent between the renderer and search process is not very large.

Can you 

- Open developer tools to check for errors when this happens
- Open the process explorer to see which processes are using high cpu or memory when this happens?

These are both under the help menu.

**Comment by fallXone** [comment]
Dev tools are showing no errors. The only thing i'm seeing change drastically in the process explorer is two processes. Below is a before and after.

**Before**
![image](https://user-images.githubusercontent.com/5201384/46756699-125c4e00-cc96-11e8-8cf0-6580d085700f.png)

**After**
![image](https://user-images.githubusercontent.com/5201384/46756707-16886b80-cc96-11e8-995b-1c4c1b2451a0.png)

At some point, it stabilizes and everything in the process explorer stops, VS Code never recovers. When the freezing first begins, both of these processes continue to increase in memory until they both stabilize. During this freeze time, both of these processes were consuming 13% CPU each. I am not able to reproduce it in a smaller workspace because the search is so fast.

**Comment by fallXone** [comment]
Attached is a video of it happening. You can see a bunch of new processes appear as soon as the freezing begins, looking at "Microsoft VS Code\resources\app\node_modules.asar.unpacked" and then they disappear right away.
[vscode-issue.zip](https://github.com/Microsoft/vscode/files/2465990/vscode-issue.zip)

**Comment by MikeMatusz** [comment]
I get this too (I'm on the same project) and it only seems to lock up if I start typing immediately after hitting Ctrl+P.  If I wait a second or two before I start typing, it's usually fine.  The window of time is larger if I try to start searching immediately after opening the app.

**Comment by roblourens** [comment]
Do you have `search.quickOpen.includeSymbols` set?

Does your workspace have multiple folders?

**Comment by MikeMatusz** [comment]
I do not have includeSymbols checked, and it does include multiple (7) folders.

**Comment by roblourens** [comment]
Those two processes under searchService that are stuck - that is rg.exe running in one of your workspace folders. Can you check which folder it is and whether it's the same two folders every time, or just a couple random ones? You should see the search folder at the very end of the list of args.

**Comment by fallXone** [comment]
I'm not seeing any specific folder, just a long list of our excludes. Here is the full path:

`0	8	34096	             "c:\Users\name\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe" --files --hidden --case-sensitive -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store -g !**/.awcache -g !**/.tscache -g !**/*.map -g !**/*.properties -g !**/*.sln -g !**/*.vspscc -g !**/*.vssscc -g !**/*.zip -g !**/bin -g !**/build -g !**/build_src -g !**/ci-build -g !**/coverage -g !**/dist -g !**/docs -g !**/help -g !**/helpers -g !**/karma_html -g !**/lib -g !**/node_modules -g !**/node_modules/.*/** -g !**/nws-docs -g !**/obj -g !**/plato-reports -g !**/Properties -g !**/staging -g !**/*.tgz -g !**/test-src -g !**/tests -g !**/Web.Common -g !**/Web.Demo -g !**/Web.TestTools -g !/npm-debug.log.* -g !/test-results.testxml -g !/tscommand*.tmp.txt -g !**/bower_components --no-ignore-parent --follow --no-config --no-ignore-global -- .`

I wasn't able to reproduce it when I undid all of our file excludes. I'm wondering if the glob expressions are causing problems. I tried narrowing it down to just one exclude and wasn't successful.

**Comment by roblourens** [comment]
Right I forgot that the file search rgs all run from each folder on `.`

Do you use text search, do you ever see this there?

Can you try setting `search.followSymlinks` to false to see if that helps?

> I wasn't able to reproduce it when I undid all of our file excludes

That's really interesting but I'm not sure why that would cause issues.

You said you've seen this for several months but did it get any worse after 1.28? Someone mentioned a similar problem in another issue so I wondered whether there was an actual recent regression.

**Comment by fallXone** [comment]
I may have had it freeze on me yesterday during text search, but that was my first time ever seeing that. That has never been a problem for me. It still appears to happen with search.followSymlinks: false. It is definitely not worse since 1.28, it has been bad for me ever since it was first introduced, and I don't believe it's changed since. I know it's weird, but the only time i'm not able to reproduce it is if I remove my "files.exclude" setting. Seems odd that searching over more files would actually make it perform better. I think it's because it then takes longer for results to come back. I searched back over an old conversation of when my co-worker started seeing it and that was on 7/25/18. My guess is I was seeing it about a month prior to that, so my guess is that it was introduced in the June 2018 release, or possibly May 2018. Before this, we had no issues using this feature.

**Comment by fallXone** [comment]
I just noticed this error in the dev tools (I might have missed it earlier because it appears as a warning). This gets spammed to the console everytime I do Ctrl + P, as well as every time I type to search. It seems like it spams to the console when I stop typing and it begins to retrieve results.
![image](https://user-images.githubusercontent.com/5201384/46774544-f75aff80-ccd0-11e8-8735-16643e1f2abd.png)

**Comment by roblourens** [comment]
@joaomoreno (sorry I'm guessing randomly) do you recognize the above IPC error or know what that implies?

**Comment by joaomoreno** [comment]
I guess that means the shared process isn't running or isn't serving at the socket.

**Comment by roblourens** [comment]
Is anything else broken in vscode when you see those warnings? Can you install extensions?

**Comment by roblourens** [comment]
That's good because that will be the default in the future but I'm still stumped. Do the IPC warnings go away too?

I tried different variations of searching in a workspace with lots of large folders but I can't repro anything like this.

**Comment by fallXone** [comment]
For some reason i'm not seeing that error at all anymore (even with that setting off), so i'm pretty confident it's unrelated. I removed this setting and was able to get it to break right away with no mention of that error in the console.

**Comment by roblourens** [comment]
I've gotten a few issues this week that sound very similar to this, and I can actually repro this issue. But only on 1.28, I can't repro on any earlier releases. But you say that it's happened for months. So I'm still stumped :)

**Comment by roblourens** [comment]
My repro steps are

- Open a workspace with like 15 folders
- Open quick open, type several characters
- See the window hang

It doesn't repro if I only type a few characters or type slowly, which makes me think it's related to cancelling the search.

**Comment by roblourens** [comment]
I am fixing this or a related issue in #60672, there will be a fix in tomorrow's Insiders build. Please try it out and let me know if it helps.

My theory is that there is an older underlying issue that isn't fixed yet, it just got easier to hit in 1.28. So I'm very curious whether it helps you.

**Comment by MikeMatusz** [comment]
I'm not sure I'll be able to test on this build, I'm seeing other issues which are making Search and Go to File unusable. 

I'll create separate issues, but Search keeps erroring out with "cannot read property 'fileEncoding' of undefined", and Go to File is displaying seven results for each file (one for each workspace folder) and usually the file I'm actually looking for isn't among them (the result per folder seems to be a recurring issue with Insiders builds).  

I can still try and retest if you want, but since Go to File is misbehaving, I'm not sure if it would be entirely valid.

**Comment by roblourens** [comment]
It sounds like you might have `"searchRipgrep.enable"` set (I can see issues with that setting on) but can you test without that setting?

**Comment by MikeMatusz** [comment]
Yes, I did still have that enabled from your earlier recommendation.  Turning it off did indeed resolve those other issues.  I'm not able to reproduce the original issue here anymore with the latest build.

**Comment by roblourens** [comment]
Thanks. @fallXone would appreciate if you can also try out the Insiders build to see if it fixes your issue.
