### ISSUE TITLE
Chinese character transform Hexadecimal code

### ISSUE THREAD

**Issue by SheffieldLee** [Microsoft/vscode#60428]
- VSCode Version: 1.28.0
- OS Version: Windows10 1803

Steps to Reproduce:

1. when you git log has Chinese character，and you enter ‘ git log --oneline ' 
2. you will see Hexadecimal code but not Chinese character

![image](https://user-images.githubusercontent.com/33490770/46711453-f600e700-cc7e-11e8-9a67-5725c4c6e435.png)

The VSCode Version 1.27.2 dose not has this issue. How to deal with it？

Does this issue occur when all extensions are disabled?: Yes

**Comment by DemoHu** [comment]
我也遇到了同样的问题

**Comment by SheffieldLee** [comment]
@DemoHu 我知道怎么解决了，在环境变量里添加LESSCHARSET  utf-8，就跟下图一样
![image](https://user-images.githubusercontent.com/33490770/46794727-09917800-cd7b-11e8-8774-02ff19fc30d9.png)
重启电脑就能解决问题了。

I know how to deal with this problem，add LESSCHARSET=utf-8 to the env.  and reboot your computer.

**Comment by SheffieldLee** [comment]
@Tyriar No，I use CMD

**Comment by Tyriar** [comment]
This doesn't appear to be a regression, so closing in favor of https://github.com/Microsoft/vscode/issues/45693
