### ISSUE TITLE
not repsonsive extension manager

### ISSUE THREAD

**Issue by vizisens** [Microsoft/vscode#60427]
- Extension Name: configuration-editing
- Extension Version: 1.0.0
- OS Version: Darwin x64 17.7.0
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:```json 
{
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 37,
		"activateCallTime": 4,
		"activateResolvedTime": 0,
		"activationEvent": "onLanguage:json"
	}
}
```

**Comment by egamma** [comment]
Please see https://github.com/Microsoft/vscode/issues/60318
