### ISSUE TITLE
Angular imports use absolute path

### ISSUE THREAD

**Issue by Hypenate** [Microsoft/vscode#60438]
Issue Type: <b>Bug</b>

Since the last update most of the imports are in the absolute path instead of the relative path
Where it used to be ../somePath it's now src/app/somePath.

![image](https://user-images.githubusercontent.com/7478681/46716052-bfb56e80-cc62-11e8-8503-d9b347e4ee2c.png)

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (6.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.1
vscode-css-formatter|aes|1.0.1
bracket-pair-colorizer|Coe|1.0.60
vscode-simpler-icons|dav|1.6.5
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.39
Angular-BeastCode|Mik|6.2.32
csharp|ms-|1.16.2
debugger-for-chrome|msj|4.10.2
material-icon-theme|PKi|3.6.0
csharp2ts|raf|0.0.22
bootstrap4-vscode|the|4.3.0

</details>

**Comment by Hypenate** [comment]
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ],
    "module": "es2015",
    "baseUrl": "./",
    //DevExpress Reporting
    "paths": {
      "jszip": [
        "../node_modules/jszip/dist/jszip.min.js"
      ],
      "globalize": [
        "../node_modules/globalize/dist/globalize"
      ],
      "globalize/*": [
        "../node_modules/globalize/dist/globalize/*"
      ],
      "cldr": [
        "../node_modules/cldrjs/dist/cldr"
      ],
      "cldr/*": [
        "../node_modules/cldrjs/dist/cldr/*"
      ]
    }
  }
}
```

**Comment by ezequielzacca** [comment]
im having the same issue, have you find a workaround?

**Comment by mjbvz** [comment]
@Hypenate Can you try setting: `"typescript.preferences.importModuleSpecifier": "relative"`. We should choose the shortest path by default but that logic may have changed recently. Setting `relative` should force VS Code to always use relative imports

**Comment by Hypenate** [comment]
@mjbvz It works again!
Thank you.
