### ISSUE TITLE
Python Extension debug print with AttributeError("'NoneType' object has no attribute 'write'",) 

### ISSUE THREAD

**Issue by ojnc** [Microsoft/vscode#60436]
In 1 PC Windows 10 Home Edition debug print works fine
Version: 1.28.0 (system setup)
Commit: 431ef9da3cf88a7e164f9d33bf62695e07c6c2a9
Date: 2018-10-05T14:58:53.203Z
Electron: 2.0.9 Chrome: 61.0.3163.100
Node.js: 8.9.3 V8: 6.1.534.41
Architecture: x64

In 2nd Windows 10 Professional debug print crashes
Version: 1.28.0 (system setup) 
Commit: 431ef9da3cf88a7e164f9d33bf62695e07c6c2a9 
Date: 2018-10-05T14:58:53.203Z 
Electron: 2.0.9 Chrome: 61.0.3163.100 
Node.js: 8.9.3 V8: 6.1.534.41 
Architecture: x64

### Very Easy to reproduce In debug console type print("jnc")
**print("jnc") AttributeError("'NoneType' object has no attribute 'write'",) 
It happens on my Windows 10 Professional latest updated VSCODE**

Others too equally impacted; please see 
https://stackoverflow.com/questions/52462326/vs-code-python-debugger-error-with-print-statements/52462487

**Comment by wuxin1030** [comment]
Yes i have the same error.

**Comment by ojnc** [comment]
Office PC (Windows 10 Home Edition) worked fine automagically after 1.28.1 was installed

Home PC (Windows 10 Professional ) with latest Anaconda did not work
UNTIL I read https://github.com/Microsoft/vscode-python/issues/2410

Had to change settings.json to avoid 
a) pythonW
b) and getting stuck on activate base on powershell

Though a happy ending I can foresee a future of unstable releases
for a wonderful VSCODE and even better Python Extension
