### ISSUE TITLE
No longer runs Python scripts

### ISSUE THREAD

**Issue by PCJimmmy** [Microsoft/vscode#60434]
Issue Type: <b>Bug</b>

For the third time in last two months VS code suddenly stops running Python.  The only solution seems to be a fresh install of WIndows.  Removing VS Code and reinstalling changes nothing.

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz (12 x 3400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.91GB (51.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
anaconda-extension-pack|ms-|1.0.0
python|ms-|2018.9.0
team|ms-|1.136.0
vscode-yaml|red|0.0.17

</details>

**Comment by egamma** [comment]
Please report the issue against the python extension.
