### ISSUE TITLE
tsc build task failed when using only nvm.

### ISSUE THREAD

**Issue by RedTailBullet** [Microsoft/vscode#60433]
- VSCode Version: 1.27.2
- OS Version: 4.18.12-arch1-1-ARCH

Steps to Reproduce:

1. Uninstall all node installation except for the nvm one.
2. Create an .ts file and try to run tsc task.

Does this issue occur when all extensions are disabled?: No

**However, while I manually disabled all extensions in vscode, the error happened again...**

The error message is: 

```
> Executing task: /home/.../node_modules/.bin/tsc -p /home/.../tsconfig.json <

/usr/bin/env: ‘node’: No such file or directory
The terminal process terminated with exit code: 127
```

**Comment by mjbvz** [comment]
Can you successfully run the same command on the command line: `./.bin/tsc -p /home/...`

**Comment by RedTailBullet** [comment]
Yes I do. That's why I am so confused and that's why I think it's a VSCode issue rather than a Typescript issue.

**Comment by RedTailBullet** [comment]
> Can you successfully run the same command on the command line: `./.bin/tsc -p /home/...`

Besides, when I am checking the /usr/bin/env, the path does contains this `/home/scott/.nvm/versions/node/v8.12.0/bin` as the first path value. And this file also contains NVM_DIR.

**Comment by RedTailBullet** [comment]
Some further investigation on this issue indicates that this might be related to my app launcher rofi. When running code using the terminal, the issue disappeared. I have filed an issue for rofi and will be reporting back if they have anything related to this.

**Comment by RedTailBullet** [comment]
Issue closed for this is not a VS Code issue.
