### ISSUE TITLE
webpack-dev-server will crash when resizing terminal size

### ISSUE THREAD

**Issue by genesis-scott** [Microsoft/vscode#60431]
It seems vscode will send KILL signal when resizing.

- VSCode Version: 1.27.2
- OS Version: win 10

Steps to Reproduce:
1. ctrl + shift + ` open terminal
2.  start webpack-dev-server
3. resize the terminal

Does this issue occur when all extensions are disabled?: No

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
