### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'children' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#60447]
Issue Id: <b>cf80a418-c78f-3c36-7023-5c21aa841f8a</b><br /><br />*Versions* <br />- 2291080075f17a27a8cd709def0a2c9298a4155c<br />-  431ef9da3cf88a7e164f9d33bf62695e07c6c2a9<br />-  5ba5f14c954682df46f04a541f0b272166605366<br />-  85d970acdee48f6dcecf909a0faeb3c6882217a9<br />-  c432054ae59c91fab2fc11511ce6d2cb4d84dc52<br />-  fe8d9d2470ddffb9dc2da604b23f5bd8a185cd66<br />-  caaa5369cb4d22b7481e6ff97252cf92937709eb<br />-  2d676e6dfdb99bd3e079ac3f4e9833656fc1b607<br />-  83d5a29433d7f576b59db8019575a0c9dc78a967<br />-  99b5434b0a90a024caab1cb35a1f7ca06708fefc<br />-  60db21f08b81f03c15bb5c9395755ad3620a62bd<br />-  79f79a2c971d6eab36b92d78505402b42ffcae93<br />-  b4d09d27509f2c023f63d4315aa966a5ec7581e9<br />*Stack* <br />TypeError: Cannot read property 'children' of undefined<br />    at DomRenderer._setCellUnderline (\node_modules.asar\vscode-xterm\lib\renderer\dom\DomRenderer.js:280:45)<br />    at DomRenderer._onLinkHover (\node_modules.asar\vscode-xterm\lib\renderer\dom\DomRenderer.js:273:14)<br />    at Linkifier.<anonymous> (\node_modules.asar\vscode-xterm\lib\renderer\dom\DomRenderer.js:65:79)<br />    at Linkifier.EventEmitter.emit (\node_modules.asar\vscode-xterm\lib\common\EventEmitter.js:70:20)<br />    at MouseZone.hoverCallback (\node_modules.asar\vscode-xterm\lib\Linkifier.js:182:19)<br />    at MouseZoneManager._onHover (\node_modules.asar\vscode-xterm\lib\ui\MouseZoneManager.js:106:18)<br />    at MouseZoneManager._onMouseMove (\node_modules.asar\vscode-xterm\lib\ui\MouseZoneManager.js:84:18)<br />    at HTMLDivElement._super.MouseZoneManager._this._mouseMoveListener (\node_modules.asar\vscode-xterm\lib\ui\MouseZoneManager.js:30:64)<br />

**Comment by Tyriar** [comment]
https://github.com/xtermjs/xterm.js/issues/1747
