### ISSUE TITLE
Debug: Set Variable Request lost the variable name info

### ISSUE THREAD

**Issue by testforstephen** [Microsoft/vscode#60444]
Below is the env info:
Version: 1.28.0 (system setup)
Commit: 431ef9da3cf88a7e164f9d33bf62695e07c6c2a9
Date: 2018-10-05T14:58:53.203Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

In the variable view, try to set a new value to a variable. 
![image](https://user-images.githubusercontent.com/14052197/46717537-e2637980-cc9a-11e8-809c-69a33f5145c9.png)
The DA sent an empty name request to Java Debugger. 
`{"command":"setVariable","arguments":{"variablesReference":5,"name":"","value":"test"},"type":"request","seq":20}`

This issue appears in the latest vscode and insider version.

**Comment by isidorn** [comment]
@testforstephen thanks for filling this issue, this is a clear regression from our debug refactoring.
Setting candidate lable to discuss if this should be a part of the recovery build. I think not since not a large number of users are affected.

**Comment by alexg1980** [comment]
The behavior is still not as expected. Now it is possible to change a variable's value but only to the same data type as the original value:
a = 1 change to a = 2 -> success
a = 1 change to a = test -> pre-1.28.1 behavior

**Comment by alexg1980** [comment]
The behavior is slightly off. Before 1.28.0 we had the following:
a = None -> click on the var to change its value -> input _test_ -> success
Now we have:
a = None -> click on the var to change its value -> input _test_ -> no effect
We have to explicitly input the quotes : _'test'_, in order for the value to be changed.

**Comment by isidorn** [comment]
@alexg1980 that sounds like an unrelated issue. Can you please cretae a new issue please. Also what debug adapter are you using, this issue seems to be coming from an extension
