### ISSUE TITLE
net::ERR_TIMED_OUT

### ISSUE THREAD

**Issue by Yjq14114** [Microsoft/vscode#60440]
Issue Type: <b>Bug</b>

net::ERR_TIMED_OUT  i can not update

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (6.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|9.0.1
vscode-svgviewer|css|1.4.6
vscode-eslint|dba|1.6.0
xml|Dot|2.3.2
gitlens|eam|8.5.6
prettier-vscode|esb|1.6.1
vue-format|feb|0.1.2
git-project-manager|fel|1.7.1
vscode-attrs-sorter|mrm|2.1.0
cpptools|ms-|0.19.0
vetur|oct|0.13.0
platformio-ide|pla|1.4.0
partial-diff|ryu|1.4.0
vim|vsc|0.16.9
gitblame|wad|2.4.4

(1 theme extensions excluded)

</details>

**Comment by Yjq14114** [comment]
![image](https://user-images.githubusercontent.com/15209776/46776234-4b9bc900-cd3d-11e8-9d9a-200eaa8be185.png)

**Comment by Yjq14114** [comment]
No use any proxy, my edge and microsoft store is that's it  ,but my chrome is normal 
os version is win10 1809
**it's store:**
![image](https://user-images.githubusercontent.com/15209776/46795895-da303a80-cd7d-11e8-9f5d-33c28ee0cd4e.png)
it's edge and chrome
![image](https://user-images.githubusercontent.com/15209776/46796099-5aef3680-cd7e-11e8-916e-f8180e1df1d1.png)
![image](https://user-images.githubusercontent.com/15209776/46796128-75291480-cd7e-11e8-9bfb-70d129d71a6b.png)

**Comment by Yjq14114** [comment]
I suspect that it has something to do with the system version.After updating, that's all.

**Comment by joaomoreno** [comment]
You have an issue with Windows. Please contact Windows support instead.
