### ISSUE TITLE
Selection > Select All is not working anymore

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#60443]
Looks like a regression from the change to use a role in the menu.

**Steps:**
* be on macOS
* open an editor
* select Selection > Select All

=> 🐛 nothing happens

/cc @rebornix @alexandrudima

**Comment by sbatten** [comment]
reverting bab47f0ffde4692b5a738c915bd823ef7ebc8d39 for now. will investigate if we can add it back with some changes to how select all is handled
