### ISSUE TITLE
 Cannot read property 'threads' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#60448]
Issue Id: <b>347e0160-ce4c-7836-aa34-03222a48e8bd</b><br /><br />*Versions* <br />- 1.28.0<br />-  99b5434b0a90a024caab1cb35a1f7ca06708fefc<br />-  caaa5369cb4d22b7481e6ff97252cf92937709eb<br />-  2d676e6dfdb99bd3e079ac3f4e9833656fc1b607<br />-  85d970acdee48f6dcecf909a0faeb3c6882217a9<br />-  c432054ae59c91fab2fc11511ce6d2cb4d84dc52<br />-  60db21f08b81f03c15bb5c9395755ad3620a62bd<br />-  0bcd086e536f55b4bf608b64f7f8882e61d957ba<br />-  b4d09d27509f2c023f63d4315aa966a5ec7581e9<br />-  83d5a29433d7f576b59db8019575a0c9dc78a967<br />-  2291080075f17a27a8cd709def0a2c9298a4155c<br />-  5a736c2e4904ed114fae2d5941508505f53afc66<br />*Stack* <br />TypeError: Cannot read property 'threads' of undefined<br />[/vs/workbench/parts/debug/electron-browser/debugSession.ts#546:18 (fetchThreads)](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/workbench/parts/debug/electron-browser/debugSession.ts#L546:18 (fetchThreads))<br />[/vs/workbench/parts/debug/electron-browser/debugSession.ts#582:21 (onComplete)](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/workbench/parts/debug/electron-browser/debugSession.ts#L582:21 (onComplete))<br />[/vs/base/common/winjs.base.js#1191:0 (_notify)](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/base/common/winjs.base.js#L1191:0 (_notify))<br />[/vs/base/common/winjs.base.js#916:0 (enter)](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/base/common/winjs.base.js#L916:0 (enter))<br />[/vs/base/common/winjs.base.js#1089:0 (_run)](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/base/common/winjs.base.js#L1089:0 (_run))<br />[/vs/base/common/winjs.base.js#1062:0 (_error)](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/base/common/winjs.base.js#L1062:0 (_error))<br />[/vs/base/common/winjs.base.js#758:0 (onError)](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/base/common/winjs.base.js#L758:0 (onError))<br />[/vs/base/common/winjs.base.js#1457:0 (then)](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/base/common/winjs.base.js#L1457:0 (then))<br />[/vs/base/common/winjs.base.js#762:0 (enter)](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/base/common/winjs.base.js#L762:0 (enter))<br />[/vs/base/common/winjs.base.js#1089:0 (_run)](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/base/common/winjs.base.js#L1089:0 (_run))<br />[/vs/base/common/winjs.base.js#1057:0 (complete)](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/base/common/winjs.base.js#L1057:0 (complete))<br />[/vs/base/common/winjs.base.js#1844:0 (argDone)](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/base/common/winjs.base.js#L1844:0 (argDone))<br />[/vs/base/common/winjs.base.js#1860:0 (onError)](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/base/common/winjs.base.js#L1860:0 (onError))<br />[/vs/base/common/winjs.base.js#1230:0](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/base/common/winjs.base.js#L1230:0)<br />

**Comment by AnanyaJha** [comment]
Still seeing this issue when launching `Apex Replay Debugger`- a Canceled pop up is displayed at the end of the session with `Cannot read property 'threads' of undefined.` This was tested today on Insiders Version 1.29.0-insider (1.29.0-insider) 4d9f1d23a556dccd2c0fd5203923a24b21e41209. Please let us know when the fix for this will be released, thanks!

**Comment by isidorn** [comment]
@AnanyaJha the fix is already present in vscode insiders.
If you still see this with latest vscode insiders, can you please
F1 > developer tools > look at the console and paste the error stack trace here

Thanks

**Comment by AnanyaJha** [comment]
Hello- we are no longer seeing the `Cannot read property 'threads' of undefined` error when ending a debug session, but the `Canceled` pop up is still being displayed. The only thing I see in the console at the time of the event is:

`notificationsAlerts.ts:40 Canceled
t.onDidNotificationChange @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
e.fire @ event.ts:145
t.notify @ notifications.ts:113
t.error @ notificationService.ts:48
(anonymous) @ debugSession.ts:590`

**Comment by isidorn** [comment]
@AnanyaJha that is an unrelated error to this one. Please file a new issue for this with nice reproducable steps.
