### ISSUE TITLE
 Cannot read property 'message' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#60458]
Issue Id: <b>79bf1bbb-c999-0dee-c637-8ed9f055dccb</b><br /><br />*Versions* <br />- 1.28.0<br />*Stack* <br />TypeError: Cannot read property 'message' of null<br />[/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#1329:31 (onError)](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L1329:31 (onError))<br />[/vs/base/common/winjs.base.js#1230:0 (_notify)](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/base/common/winjs.base.js#L1230:0 (_notify))<br />[/vs/base/common/winjs.base.js#916:0 (enter)](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/base/common/winjs.base.js#L916:0 (enter))<br />[/vs/base/common/winjs.base.js#1089:0 (_run)](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/base/common/winjs.base.js#L1089:0 (_run))<br />[/vs/base/common/winjs.base.js#1062:0 (_error)](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/base/common/winjs.base.js#L1062:0 (_error))<br />[/vs/base/common/winjs.base.js#758:0 (onError)](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/base/common/winjs.base.js#L758:0 (onError))<br />[/vs/base/common/winjs.base.js#1230:0 (_notify)](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/base/common/winjs.base.js#L1230:0 (_notify))<br />[/vs/base/common/winjs.base.js#916:0 (enter)](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/base/common/winjs.base.js#L916:0 (enter))<br />[/vs/base/common/winjs.base.js#1089:0 (_run)](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/base/common/winjs.base.js#L1089:0 (_run))<br />[/vs/base/common/winjs.base.js#1062:0 (_actualErr)](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/base/common/winjs.base.js#L1062:0 (_actualErr))<br />[/vs/workbench/services/extensions/node/lazyPromise.ts#72:8 (resolveErr)](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/workbench/services/extensions/node/lazyPromise.ts#L72:8 (resolveErr))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#422:15 (_receiveReplyErr)](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L422:15 (_receiveReplyErr))<br />[/vs/workbench/services/extensions/node/rpcProtocol.ts#323:9 (score)](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L323:9 (score))<br />[/vs/base/parts/quickopen/common/quickOpenScorer.ts#434:27](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/base/parts/quickopen/common/quickOpenScorer.ts#L434:27)<br />

**Comment by dbaeumer** [comment]
Fixed.
