### ISSUE TITLE
Open file dialog dont appear after the disconnected network 

### ISSUE THREAD

**Issue by edsondiasalves** [Microsoft/vscode#6045]
- VSCode Version: 1.0.0
- OS Version: Windows 7 - Enterprise

Steps to Reproduce:

1. Open a file on a network directory using the open file dialog.
2. Disconnect from the network
3. Try access the open file dialog again

In my case this action spent a lot of time, after I disconnect the network

**Comment by bpasero** [comment]
@edsondiasalves that seems like standard OS behavior, not much we can control.

**Comment by edsondiasalves** [comment]
Ok, nervermind and thank you for the feedback.
