### ISSUE TITLE
Settings Sync extension startup too slow

### ISSUE THREAD

**Issue by kirit0s** [Microsoft/vscode#60464]
- Extension Name: code-settings-sync
- Extension Version: 3.1.2
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:
```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 7502,
		"activateCallTime": 1,
		"activateResolvedTime": 7525,
		"activationEvent": "*"
	}
}
```

**Comment by egamma** [comment]
Closing please see https://github.com/Microsoft/vscode/issues/60318
