### ISSUE TITLE
Different README.md for Marketplace

### ISSUE THREAD

**Issue by muuvmuuv** [Microsoft/vscode#60466]
I recently created my own VS Code Extensions and made a – imho – greate README.md, then I noticed that in the VS Code Marketplace some things are not making so much sense display e.g.: menu with a download button, badges, install on VS Code Marketplace button. 

It would be pretty great to have a secondary README.md, maybe in `.vscode` or `README-MARKETPLACE.md` where we could optionally put information to the extension. There we could also point better to VS Code specify things like the extension options.

and another thing is that the GitHub flavoured icons e.g. `:heart:`:heart: are not rendering as emojis

**Comment by egamma** [comment]
Can you show examples of information that does not make sense when shown in the market place?

**Comment by muuvmuuv** [comment]
@egamma have a look at my extension: https://github.com/muuvmuuv/vscode-sundial

1. The badges at the top
2. In the menu: Download, License
3. Installation section (because it is clear how to install an extension when its displayed in the VS Code Extension manager)

Some of them may differ from extension to extension, but I think it would be pretty helpful – for users as well – to have a different README especially for the Marketplace.

**Comment by egamma** [comment]
@muuvmuuv thanks for following up. 

The recommendation is to optimize the Readme.md for when it is shown in the market place.
For additional developer related information you can create additional markdown files that link from the Readme.md.
