### ISSUE TITLE
The Extensions are taking longer time to load

### ISSUE THREAD

**Issue by AshwinKheta** [Microsoft/vscode#60463]
- Extension Name: search-rg
- Extension Version: 1.0.0
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:
```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 3064,
		"activateCallTime": 0,
		"activateResolvedTime": 0,
		"activationEvent": "*"
	}
}
```

**Comment by egamma** [comment]
Please see https://github.com/Microsoft/vscode/issues/60318
