### ISSUE TITLE
 Cannot read property 'command' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#60461]
Issue Id: <b>86079940-8581-1f76-a886-392212711eda</b><br /><br />*Versions* <br />- 1.28.0<br />-  60db21f08b81f03c15bb5c9395755ad3620a62bd<br />-  c432054ae59c91fab2fc11511ce6d2cb4d84dc52<br />*Stack* <br />TypeError: Cannot read property 'command' of null<br />[/vs/workbench/parts/tasks/node/processRunnerDetector.ts#173:80 (detect)](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/workbench/parts/tasks/node/processRunnerDetector.ts#L173:80 (detect))<br />[/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#1590:127 (computeLegacyConfiguration)](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L1590:127 (computeLegacyConfiguration))<br />[/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#1519:10 (computeWorkspaceFolderTasks)](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L1519:10 (computeWorkspaceFolderTasks))<br />[/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#1503:23 (computeWorkspaceTasks)](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L1503:23 (computeWorkspaceTasks))<br />[/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#1485:37 (updateWorkspaceTasks)](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L1485:37 (updateWorkspaceTasks))<br />[/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#531:8 (call)](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L531:8 (call))<br />[/vs/base/common/event.ts#140:15 (fire)](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/base/common/event.ts#L140:15 (fire))<br />[/vs/workbench/services/configuration/node/configurationService.ts#672:34 (triggerConfigurationChange)](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/workbench/services/configuration/node/configurationService.ts#L672:34 (triggerConfigurationChange))<br />[/vs/workbench/services/configuration/node/configurationService.ts#569:10 (onComplete)](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/workbench/services/configuration/node/configurationService.ts#L569:10 (onComplete))<br />[/vs/base/common/winjs.base.js#1191:0 (_notify)](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/base/common/winjs.base.js#L1191:0 (_notify))<br />[/vs/base/common/winjs.base.js#867:0 (enter)](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/base/common/winjs.base.js#L867:0 (enter))<br />[/vs/base/common/winjs.base.js#1089:0 (_run)](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/base/common/winjs.base.js#L1089:0 (_run))<br />[/vs/base/common/winjs.base.js#1057:0](https://github.com/microsoft/vscode/blob/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/src/vs/base/common/winjs.base.js#L1057:0)<br />    at l (out/vs/workbench/workbench.main.<br />

**Comment by dbaeumer** [comment]
Fixed.
