### ISSUE TITLE
Extensions seem really slow .

### ISSUE THREAD

**Issue by mjarkk** [Microsoft/vscode#60465]
Issue Type: <b>Bug</b>

Sinds the last 1.28.0 update Vscode seems not to get data from a lot of extensions or it takes really long to get the data.  
I mean with this that when i edit a ts file Ts lint takes a minimum of 3 seconds to find errors if it even finds it.  
This also effect a lot of other extensions (maybe all).  

I also noticed that my CPU usage is around 50-60% constantly. I have to notice that i have a under clocked cpu but this is still way to much it's normally around 20% CPU usage max.   

I also shows that new warning around every 2 minute or so it usually appends when i switch from file to file (`Extension Host unresponsive`)

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-04T16:41:10.439Z)
OS version: Linux x64 4.18.11-200.fc28.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|15.52GB (3.89GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
laravel-goto-view|cod|1.2.1
es7-react-js-snippets|dsz|1.8.6
tslint|eg2|1.0.39
comment-anchors|Exo|1.6.0
php-intellisense|fel|2.3.5
file-icons|fil|1.0.16
discord-vscode|icr|2.10.1
code-beautifier|mic|2.1.0
Angular-BeastCode|Mik|6.2.32
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.8
Go|ms-|0.6.90
vsliveshare|ms-|0.3.735
laravel-blade|one|1.18.0
laravel5-snippets|one|1.5.0
vscode-docker|Pet|0.3.1
material-icon-theme|PKi|3.6.0
vscode-yaml|red|0.0.17
vscode-workspace-switcher|sad|1.9.0
language-stylus|sys|1.10.0
vscode-import-cost|wix|2.9.0

(11 theme extensions excluded)

</details>

**Comment by egamma** [comment]
Please provide a CPU profile when this happens as described in this guide https://github.com/Microsoft/vscode/wiki/Performance-Issues. It also includes other information for how to narrow this down.

**Comment by mjarkk** [comment]
![screenshot from 2018-10-10 09-30-07](https://user-images.githubusercontent.com/15320763/46721052-70773a00-cc72-11e8-82d5-871977e5b5b7.png)
Here is a screenshot of my CPU usage i hope that i can give you some more detailed information later today i have still work to do

**Comment by egamma** [comment]
Since this is a performance issue, please also add the information that included when you report a performance issue. In this case more information will be included.

- narrow down whether this is caused by an extension, it very likely is given the information above. So when this happens check the process explorer help>process explorer.
- if it is an extension, you can either selectively enable/disable extensions or much preferred you create a CPU profile, which is described in the wiki page I´ve included above. 

From the traces it looks like you are doing PHP work when this happens?

**Comment by mjarkk** [comment]
I'm working here on a angular project (lots of typescript files).  
The project with lots of typescript are also where i notice the most lag.  

I have also worked on some Golang files today and it seems like that extensions don't crash there but the Golang extension is still really slow when code is saved.  

I'll add some technical details later today.

**Comment by mjarkk** [comment]
Ow sorry for this stupid question.  
After some digging i found that one extension ([Comment Anchors](https://marketplace.visualstudio.com/items?itemName=ExodiusStudios.comment-anchors)) scans all files in my work space.  
this is oke when vscode doesn't kill all extensions after 10s of no response but because this extension takes more than 10s to scan all my files vscode gives that error and vscode starts behaving really wired.  

Because my Golang work space has way less files maybe like 100-1000x less files then my angular work space it didn't error  

Still thanks for your help @egamma  
I'll make an issue on there [extension git repo](https://github.com/ExodiusStudios/vscode-comment-anchors)

**Comment by egamma** [comment]
@mjarkk thanks for tracking this down. Actually, we do not terminate extensions after 10s of running, exception when the user selects `Restart Extension Host`. So the extension will continue to consume a lot of CPU.
