### ISSUE TITLE
Autocompletion improvements. Shorter first. Case matching priority. 

### ISSUE THREAD

**Issue by VladislavKostin** [Microsoft/vscode#60479]
### Shorter First

If I type "EM" I get suggestions: 

1. EntityManagerExtensions
2. EntityManager

A definitively better way would be to suggest in the opposite order here. Why? Because in the case above if I need the "EntityManager" I can't get to it by typing another letter, I have to move down with an arrow or type in the whole word "EManager" before it prioritizes "EntityManager" over "EntityManagerExtensions".

And if the shorter matching word is prioritized in the suggestions, we will be getting this:

1. EntityManager
2. EntityManagerExtensions

And this means that we can go **immediately** to what we need in any case. "EM" gives EntityManager. "EME" gives EntityManagerExtensions. So this is in my opinion always the preferred way to order the suggestion, shorter first.

### Case Matching Priority
If I type "VI" (with capital i) I get very unpredictable results:

1. ADBannerView
2. NetworkView
3. SceneView
4. VectorInt

Logically what should come first is VectorInt otherwise I wouldn't type "VI" if I would need views I would type "Vi" (with lowercase i) and I should get this:

1. SceneView
2. NetworkView
3. ADBannerView
4. VectorInt

Why? Because logically case matching "Vi" appears first in "SceneView" (characters 6 and 7), then in NetworkView (characters 8 and 9), then "ADBannerView" and then not case matching "VectorInt"  But instead I'm getting this again:

1. ADBannerView
2. NetworkView
3. SceneView
4. VectorInt

But the main point is case matching. If I want "NetworkView" I go "NV". If I want "VectorInt" I should be able to just type "VI". So for "VI" this should be the order:

1. VectorInt
2. SceneView
3. NetworkView
4. ADBannerView

Thank you. Please let me know what you think. I've been sitting on this suggestion for years hoping that someone else will take it to the team, but here I am finally posting. Wasn't that hard :)

One last thing: I just noticed that suggestions, after moving away from a word and then coming back and retyping one letter, are different then if I wouldn't move or would retype two letters. Same word "VId" but different suggestions. Slight inconsistency there.

**Comment by egamma** [comment]
The sort order of recommendations is controlled by the extension that provides completions.

For what language should the above recommendations apply?

**Comment by VladislavKostin** [comment]
I would apply it to other languages too, although I personally don't use them.

**Comment by egamma** [comment]
Then can you please report the issue against the C# extension, this extension defines the sort order for c#.
