### ISSUE TITLE
Clone in VS Code from AzureDevops fails for project names containing spaces

### ISSUE THREAD

**Issue by PeterWone** [Microsoft/vscode#60472]
Issue Type: <b>Bug</b>

Create a repo with a name that contains one or more spaces. Put something in it eg a readme.md and then attempt to clone it via VS Code.

VS Code fails to URL encode the URL, and fails to quote the folder name that it creates. 

I copied the generated git command and did those things to it and then it worked as expected.

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz (4 x 3293)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (1.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
aurelia|Aur|1.0.3
xml|Dot|2.3.2
gitlens|eam|8.5.6
vscode-test-explorer|hbe|2.0.9
reg|ion|0.0.2
mssql|ms-|1.4.0
csharp|ms-|1.16.2
PowerShell|ms-|1.9.0
vsliveshare|ms-|0.3.735
team|ms-|1.136.0

</details>

**Comment by PeterWone** [comment]
The reason I removed the Windows from the bug title is I suspect the problem will take much the same form with the same solution on all platforms.

**Comment by Glober777** [comment]
Are there any news on this? I am hitting this issue quite often
