### ISSUE TITLE
Keep history independent of splits

### ISSUE THREAD

**Issue by jhaberstro** [Microsoft/vscode#6047]
- VSCode Version: Version 1.0.0 (1.0.0) fa6d0f03813dfb9df4589c30121e9fcffa8a8ec8
- OS Version: Mac OS X 10.11.4

If I split my editor and then navigate through history, navigation will linearize my history such that I cannot step back in history in my in-focus editor split without inadvertently affecting my out-of-focus editor.

For example, if I have editor splits 1 and 2 and my navigation history looks like this (with time moving from left to right):
```
Split 1: File A              --> File B
Split 2: File X  --> File Y            --> File Z
```
If my in-focus editor is split 2 and I want to navigate back in history to File X, I cannot do so without also causing Split 1 revert back to File A, which is very undesirable.

**Comment by bpasero** [comment]
@jhaberstro I assume that this would be solved if you had a way to navigate in the history "per split" (or editor group as we name it)?

**Comment by jhaberstro** [comment]
Yes, if I'm understanding you correctly :). When I navigate history, I want the history kept separate for every split and to thus only affect the editor split I'm currently typing in.

And to clarify, what I call "editor split" is basically a single view into a source file; these splits are created by clicking the UI button in the top right corner whose hover text says "Split Editor". I'm not sure they're the same as what you're referring to as "editor groups" as they're not grouping anything. What precisely is an editor group?

**Comment by bpasero** [comment]
An editor group is the thing that opens when you split, it has a stack on its own (in the future with the work of tabs). You can navigate between tabs in that group.

To be clear, we will still have a linear history of any editor open in the past but on top of that you can navigate between tabs per group that you opened.

**Comment by jhaberstro** [comment]
Glad to hear the functionality will change :). Thanks!
