### ISSUE TITLE
[loc]Request to add Slovenian (sl) language to VS Code project in Transifex

### ISSUE THREAD

**Issue by juozhe** [Microsoft/vscode#60476]
We expect at least three language contributors sign up and product team sign off before adding new language to Transifex. Please vote by adding your Transifex account name here in this issue (request).
How to request guide: https://github.com/Microsoft/Localization/wiki/How-to-request-a-new-UI-language-for-VS-Code-project

**Comment by juozhe** [comment]
I'm joining the translation team for Slovenian language, my Transifex user name is juozhe.

**Comment by ciril-fabcic** [comment]
I'm joining the translation team for Slovenian language, my Transifex user name is ciril.fabcic.

**Comment by capobandaf** [comment]
I'm joining the translation team for Slovenian language, my Transifex user name is capobandaf.

**Comment by juozhe** [comment]
I have some experience with localization, e.g. I localized browser extension panlatin (for chrome and firefox) into Russian, French and German.

**Comment by juozhe** [comment]
The user profiles at transifex are

https://www.transifex.com/user/profile/juozhe/
https://www.transifex.com/user/profile/ciril.fabcic/
https://www.transifex.com/user/profile/capobandaf/

**Comment by danyeh** [comment]
@shawndon , could you please triage the request? Thanks!

**Comment by shawndon** [comment]
Hi Folks,

Thanks for using the Transifex platform. however, as of January 1, 2019, Microsoft has discontinued the use and now has migrated to the Microsoft  Localization Community Platform (MLCP).

Please see the following Wiki page for more information

How to request guide: https://github.com/Microsoft/Localization/wiki/How-to-request-a-new-UI-language-for-VS-Code-project
