### ISSUE TITLE
Terminal window

### ISSUE THREAD

**Issue by dreamzzzz** [Microsoft/vscode#60471]
Issue Type: <b>Feature Request</b>

It would be greate if the terminal window could launch bash instead of powershell

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 10.0.17134

**Comment by stevenhay** [comment]
I believe this is already a feature. The settings allows you to determine which terminal you wish to open.

![image](https://user-images.githubusercontent.com/26744309/46728509-e97a8f80-cc7a-11e8-9852-ede9c1e336f2.png)

**Comment by Tyriar** [comment]
It is, but you want to use the `terminal.integrated.shell.windows` setting. 

You can use this command (ctrl+shift+p) to help configure it for you:

![image](https://user-images.githubusercontent.com/2193314/46771822-25791900-ccaa-11e8-939b-67bfa7d320df.png)
![image](https://user-images.githubusercontent.com/2193314/46771830-2f028100-ccaa-11e8-9fdd-bce158ba83ec.png)
