### ISSUE TITLE
custom snippet [json] Invalid characters in string

### ISSUE THREAD

**Issue by pixieaka** [Microsoft/vscode#60477]
Issue Type: <b>Bug</b>

Here before $2 I entered tab for indentation to fast snippet writing it show me error:
{ [json] Invalid characters in string. Control characters must be escaped. }
we can escape this error for snippets only for fast writing, or would be better for add ability to write snippets like sublime text in free way it will be great and so much better actually.

	"Print to console": {
		"prefix": "log",
		"body": [
			"console.log('$1');",
			"	$2"
		],
		"description": "Log output to console"
	}

VS Code version: Code - Exploration 1.29.0-exploration (878fda8c5e688a5f01fe16c586ba51c28da325a4, 2018-10-10T05:47:41.620Z)
OS version: Windows_NT x64 10.0.17763

**Comment by pixieaka** [comment]
Can we replace current snippet & find multi line from JSON to just text like sublime text and vscode generate in background from user snippet input like here for example:
https://snippet-generator.app/

**Comment by jrieken** [comment]
We have chosen JSON for snippets and have currently no plans to change that. Tab characters must be enter in this form `\t`.
