### ISSUE TITLE
Black blocks on editor everywhere

### ISSUE THREAD

**Issue by EWhite613** [Microsoft/vscode#6048]
- VSCode Version: 1.0.0
- OS Version: Mac 

Steps to Reproduce: No clue (randomly happens)

I get issues like this all the time with vscode. I have no idea what causes it
<img width="1219" alt="screen shot 2016-05-02 at 5 30 10 pm" src="https://cloud.githubusercontent.com/assets/9057680/14968683/15054922-108c-11e6-90da-39cc2bab9851.png">

To fix them I can sometimes click where they are. But more appear ( cut off one head and two more take its place)

**Comment by joaomoreno** [comment]
Do you maybe have an Nvidia GPU? electron/electron#4380

**Comment by EWhite613** [comment]
@joaomoreno Nope. AMD

**Comment by joaomoreno** [comment]
@bpasero Have you seen this?

**Comment by EWhite613** [comment]
I've never seen it in my other electron apps. Only vscode

**Comment by bpasero** [comment]
Wonder if newer Electron fixes it. @EWhite613 
You can give it a try from our insiders release today: http://code.visualstudio.com/Download#insiders

**Comment by EWhite613** [comment]
@bpasero I used the insiders for two days and didn't get the problem. But then again I have no idea how to reproduce it

**Comment by bpasero** [comment]
Ok lets assume it got fixed and reopen when it happens again.
