### ISSUE TITLE
Jumping between functions

### ISSUE THREAD

**Issue by Karlito88** [Microsoft/vscode#60497]
I would love to see a implementation of jumping between functions if you have more functions in one file that you can jump between them with hotkeys. Its like the "@"-symbol jumping but only with functions.

Example:
```
function 1 {}; // hotkey + '+' jumps to function 2 and hotkey + '-' jumps to function 3
function 2 {}; // hotkey + '+' jumps to function 3 and hotkey + '-' jumps to function 1
function 3 {}; // hotkey + '+' jumps to function 1 and hotkey + '-' jumps to function 2
```

**Comment by Karlito88** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Jump to function beginning (#57102)](https://www.github.com/Microsoft/vscode/issues/57102)

This is a other featureRequest

**Comment by egamma** [comment]
Navigating to functions is supported by the Go to Symbol in File command.

Please file a separate feature request to use key bindings to jump to a function in a particular sequence.
