### ISSUE TITLE
Need doulble click for termian under view tab

### ISSUE THREAD

**Issue by LHLK** [Microsoft/vscode#60490]
Version Info:
Version: 1.28.0 (user setup)
Commit: 431ef9da3cf88a7e164f9d33bf62695e07c6c2a9
Date: 2018-10-05T14:58:53.203Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Everytime I click the terminal under the 'view', I'll have to click twice.  Please take a look.  Thanks...

**Comment by Tyriar** [comment]
Are you trying to hide the termianl?
