### ISSUE TITLE
Add a Ctrl-Shift-P command or menu entry for opening the changelog

### ISSUE THREAD

**Issue by costincaraivan** [Microsoft/vscode#60493]
Seeing the latest changelog is quite nice but unfortunately after you close the tab, it's gone. There's no way that I can find to re-open it in VS Code.

So I propose that a command or a menu entry are added to "Open the latest changelog". Ideally both 😉

**Comment by nilllzz** [comment]
You can open the changelog by clicking Help > Release Notes

**Comment by costincaraivan** [comment]
Oh, I completely missed that. It should suffice, thanks! 👍
