### ISSUE TITLE
Problem always block

### ISSUE THREAD

**Issue by gladenko** [Microsoft/vscode#60492]
- Extension Name: git
- Extension Version: 1.0.0
- OS Version: Darwin x64 18.0.0
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:

**Comment by joaomoreno** [comment]
This issue was closed because it doesn't meet our standards of a properly filled issue. Please read our guide about [Submitting Bugs and Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).
