### ISSUE TITLE
Cyrptic JSON error in our sources

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#60491]
![screenshot from 2018-10-10 11-37-53](https://user-images.githubusercontent.com/22350/46727549-1af65980-cc81-11e8-9c3f-ba8d7f2eff75.png)

**Comment by aeschli** [comment]
The hover shows both an error (`[ts] Cannot write...) as well as the information hover of the object under the cursor (`JSON schema...')

I assume this is about the error.

**Comment by mjbvz** [comment]
Let me know if you still see this
