### ISSUE TITLE
[css] Support auto-complete of gradient function parameters like currently do for rgb/hsl

### ISSUE THREAD

**Issue by dstorey** [Microsoft/vscode#605]
The colour functions in CSS currently prefill the parameters and allow you to tab through the values. Similarly it would be nice to support that for the 4 gradient functions, especially as the syntax is some times hard to remember (not helped by the fact it has changed so many times). Currently it just supplies empty (). 

The colour functions are set up in languagefacts, while the gradients are just standard property values in the XML file.

**Comment by dstorey** [comment]
…this is complicated by the fact that while all values are required in RGB()/HSLA(), in gradients, some are optional, and there can be multiple colour stops added.

**Comment by aeschli** [comment]
+1 for adding the gradient functions. It should be easy to add following the approach we currently have. Check out colorFunctions in /src/vs/languages/css/common/services/intelliSense.ts as well as
/src/vs/languages/sass/common/services/intelliSense.ts
