### ISSUE TITLE
Tab space setting of some Php files become 8 spaces after some time.

### ISSUE THREAD

**Issue by guneyozsan** [Microsoft/vscode#60502]
Issue Type: <b>Bug</b>

I have a project with 10-15 php files around 50 lines. All files start with 4 space tab. But after some time some files become 8-space tab when opened and never go back to 4-space. They are very basic php scripts with some SQL queries. All files are variations of the same script (various get queries for a database), some stay at 4-tab, some convert to 8-tab. I couldn't find a pattern.

The only way to convert them back to 4 space tab is to copy the content, delete the file, create a new file and paste the content.

This bug blocks the workflow pretty badly.

Here is a sample code that works as 4-space for some time, then become 8-space:

```
<?php
namespace SomeNamespace;

require_once "config.php";
require_once "utility.php";

$room_id_parameter = 'room_id';

if (!isset($_GET[$room_id_parameter])) {
    http_response_code(400);
    die_with_message($room_id_parameter ." is required but was not set.");
}

$surround_image_path = joinPaths(
    CLIENT_FILES_PATH,
    SURROUND_IMAGE_FOLDER
);

$room_id = $_GET[$room_id_parameter];
validate_database_id($room_id_parameter, $room_id);

$query = '  SELECT      `room_view_id`,
                        `rv`.`room_id`,
                        CONCAT(\'' .$surround_image_path .'\' , \'/\',`surround_image_file_name`)
                    AS  `surround_image_path`
            FROM        `building` AS `b`
            RIGHT JOIN  `floor` AS `f`
                    ON  `b`.`building_id` = `f`.`building_id`
            RIGHT JOIN  `room` AS `r`
                    ON  `f`.`floor_id` = `r`.`floor_id`
            RIGHT JOIN  `room_view` AS `rv`
                    ON  `r`.`room_id` = `rv`.`room_id`
            WHERE       `b`.`building_id` = ' .BUILDING_ID .' '
                 .'AND  `r`.`room_id` = ' .$room_id .' '
            .';';
echo_query_result($database, $query);
?>
```
 

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz (8 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (8.35GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|0.8.8
dart-code|Dar|2.19.0
flutter|Dar|2.19.0
php-debug|fel|1.12.6

</details>

**Comment by roblourens** [comment]
Do you have any relevant settings like `editor.tabSize` set?

Do you have any extensions like EditorConfig that change file formats? You could try starting with `--disable-extensions` to see

**Comment by guneyozsan** [comment]
I use default settings (all settings untouched from install). I had only 4 extensions (Flutter, Dart, PHP Debug and Php Intellisense). It is the same after disabling all extensions.

Turning off `Editor:Detect Indentation` result in 4-spaces, and turning it on again sets it to 8-spaces. Here is a gif while switching indetect indentation:
![vs-bug](https://user-images.githubusercontent.com/19275187/46768709-eec6f100-ccf1-11e8-9dc5-834ad65db4db.gif)

**Comment by roblourens** [comment]
Oh I think it's just that "detect indentation" is detecting the wrong indentation because of that file formatting. It's not very smart, it just looks at where lines begin. If it's getting it wrong for your files, I recommend just disabling it.

**Comment by guneyozsan** [comment]
I see. It is still surprising that it picks 8 where all spaces are powers of 4 (i.e. 4, 12, 16, 20, 24). Don't know how it works but Largest Common Denominator with some frequency weight function may help.
