### ISSUE TITLE
could binary view be added? 

### ISSUE THREAD

**Issue by smmif** [Microsoft/vscode#60506]
Binary, being the base of an executable, or even more, an operating system, should be view-able. Its a very important aspect of a good text editor. Maybe we all have our best choice of an text/binary editor in our minds, such as UltraEdit and so on. But the thing is, while enjoying the greatness of U-E, you will find your self paying a price that's way higher them acceptable. Well, because company must make money right? But, one day, you will find your self looking at your empty wallet or bank card and go thinking :"well well I'm darn poor, can't afford sky-high prices, lets go open-sorce."With that thought in mind, you will go searching for text editors, and after finding an app with a  perfect looking UI, "said so" powerful powers, and a big co. called "Microsoft" behind it, you will think you have found the best choice. But, sad thing, our beloved friends in git hub and the guys sitting in their nice comfy chair in Seattle aren't in a good mood to make their product binary-able. right, guys ? I don't think adding some more features in an text editor, especially an  open sorce app would  be very hard, right? so come on, just some  binary, features to let us not facing a blank screen every time I click on a file made with ones and zeros. maybe you will find your self facing the same frustration, so, could you please just add some binary? Thanks!

**Comment by egamma** [comment]
Our users use this nice hex editor extension for this purpose
https://marketplace.visualstudio.com/items?itemName=slevesque.vscode-hexdump

There is an existing feature request to support that you can define the default editor for particular file types.
