### ISSUE TITLE
Need full file path of file in title bar

### ISSUE THREAD

**Issue by ShujaathKhan** [Microsoft/vscode#60508]
Issue Type: <b>Feature Request</b>

Hi there,
Full path of file in title bar would really helps to diff. b/w the same files names when working upon.

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 10.0.15063

**Comment by egamma** [comment]
This is configurable, pls see the setting ```
 "window.title": "${dirty}${activeEditorShort}${separator}${rootName}${separator}${appName}"
```

// CC @sbatten did we change the default rendering, I´m seeing more feature requests for this, e.g. #60445
