### ISSUE TITLE
configuration-editing

### ISSUE THREAD

**Issue by yadianfdez07** [Microsoft/vscode#60505]
- Extension Name: configuration-editing
- Extension Version: 1.0.0
- OS Version: Windows_NT x64 10.0.16299
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:

```json 
{
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 70,
		"activateCallTime": 6,
		"activateResolvedTime": 0,
		"activationEvent": "onLanguage:jsonc"
	}
}
```

**Comment by egamma** [comment]
Please see #60318, closing.
