### ISSUE TITLE
React  / JSX lost autocomplete

### ISSUE THREAD

**Issue by yuritoledo** [Microsoft/vscode#60513]
- VSCode Version:
- OS Version: Linux mint 18
Version: 1.28.0
Commit: 431ef9da3cf88a7e164f9d33bf62695e07c6c2a9
Date: 2018-10-05T14:52:58.945Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Steps to Reproduce:

1. Inside a JSX file (react render) create a button component and try ctrl space inside it. Not showing the onClick, onLeave, etc
2. Inside a react class component, when Ctrl space, Is not showing the lifecycle methods, and another options that appears on 1.28
I've tried with Javascript, Rectjavascript and JSX syntax, same problem
![image](https://user-images.githubusercontent.com/18474538/46739992-24c78f00-cc78-11e8-916d-75c16a1451af.png)

But for vanillaJS, the intelisense still works
![image](https://user-images.githubusercontent.com/18474538/46740283-d070df00-cc78-11e8-9fbf-a2d21728cddd.png)

Does this issue occur when all extensions are disabled?: Yes/No 
YES :/

**Comment by jmsstudio** [comment]
I have the same problem. After the last update it stopped working.

**Comment by danfsd** [comment]
Same here. Language is set to `Javascript React` and still not autocompleting/listing JSX attributes as it was before.

**Comment by mjbvz** [comment]
Please check the TypeScript Server trace:

1. Set `"typescript.tsserver.trace": "verbose"`
1. Reproduce the problem
1. Open the output panel and view the `TypeScript` section

Are there any errors or stack traces printed near the end?

**Comment by danfsd** [comment]
Unfortunately I did saw a stack trace printed, but decided to clear it in order to see if it was still happening, but it turns out that it isn't.

No stack traces or errors are being logged on Typescript, however the issues still remains.

Let's hope that the OP is getting something in the logs.

**Comment by yuritoledo** [comment]
For me, it automagically back to normal 

Sorry for dont help @danfsd

**Comment by danfsd** [comment]
No problem @yuritoledo, it's back to normal for me as well. I think it went back after the `1.28.1` update. Try updating to that version @jmsstudio.

I think the issue can be closed @mjbvz

**Comment by jmsstudio** [comment]
The problem still occurs on my VS Code...
I updated my version but it didn't change anything regarding this issue

**Comment by yuritoledo** [comment]
@jmsstudio it works with normal JSX button / input too?

**Comment by jmsstudio** [comment]
I disabled all the extensions and tried again, it worked now
Sorry for the inconvenient, it was some extension trouble here

Now the only problem that is still occurring is related to import not being placed in the file header with the imports, but it is another issue...

**Comment by yuritoledo** [comment]
@jmsstudio great!
