### ISSUE TITLE
Add option to change the status bar color or follow theme color

### ISSUE THREAD

**Issue by murdocdv** [Microsoft/vscode#60516]
Just started using Visual Studio Code but really dislike the brightly colored status bar.

I'd like the ability to have the status bar match the styling of the theme or have it's own colors.

I know this is like a Microsoft app wide design, and I hate it in Word, Excel, etc.

**Comment by usernamehw** [comment]
```json
"workbench.colorCustomizations": {
    "statusBar.background": "#ffffff",
},
```

**Comment by murdocdv** [comment]
thanks @usernamehw 

DIdn't find the closed issues (was only searching for open) vscodebot echoed and just missed Color Customizations in Settings/Preferences
