### ISSUE TITLE
Special characters in file path don't turn into clickable links in terminal

### ISSUE THREAD

**Issue by markgoho** [Microsoft/vscode#60519]
- VSCode Version: 1.29 nightly
- OS Version: Windows 10

Steps to Reproduce:

1. Get any file path printed out in terminal (using Bash currently).
2. Ctrl+Click on a file path with no special characters, the file opens immediately.
3. Hover over a link with a special character (`+` specifically) and no option is given to ctrl+click

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
https://github.com/xtermjs/xterm.js/issues/583
