### ISSUE TITLE
Add support for BigInt literals in javascript code validation

### ISSUE THREAD

**Issue by droland1** [Microsoft/vscode#60517]
Chrome now supports the type BigInt for javascript code. This includes support for BigInt literals:

var n = 13135151n;

Visual Studio tags these literals as syntax errors. Coders can avoid these errors by instead using:

var n = BigInt("1313515");

It would be great if Visual Studio supported the literal notation.

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/Microsoft/TypeScript/issues/15096
