### ISSUE TITLE
[?] How open preview file saved focus on the explorer?

### ISSUE THREAD

**Issue by ProSerg** [Microsoft/vscode#60518]
Hello,

Could you tell me how to open a file in the same way as with a single click on a file when the preview mode is on?
It is convenient for me to see a large number of configs in the preview mode.
However, if you open the file through the keyboard, the focus changes to editing. Then in order to open the next file through explorer I need to return the focus back.

I want to view files without losing focus in explorer.
 
Thanks!

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/28710
