### ISSUE TITLE
CSS inside JavaScript not colorizing or giving suggestions

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#6051]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Open a JavaScript file with embedded CSS

Colorization is different inside the defined CSS portion, no suggestions are shown, and the color preview for coloring elements is not shown.

Example:
```javascript
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 */

import React, {
  AppRegistry,
  Component,
  StyleSheet,
  Text,
  View
} from 'react-native';

class ReactNativeProject extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.android.js
        </Text>
        <Text style={styles.instructions}>
          Shake or press menu button for dev menu
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('ReactNativeProject', () => ReactNativeProject);

```

**Comment by joaomoreno** [comment]
I do not see any embedded CSS in your snippet. I do see JavaScript objects that build up a style sheet though... I don't understand what kind of colorisation you'd expect other than the plain JavaScript.

**Comment by dbaeumer** [comment]
@aeschli assigning to you since this is a grammar thing. However I think we should close this one since css inside JS is to my knowledge not valid.

**Comment by aeschli** [comment]
Th coloring of the provided sample looks all fine to me. Closing.
@vsccarl Scott, if I overlooked something, please reopen with more detailed information.
