### ISSUE TITLE
Terminal initial state is broken after 1.28.0 update

### ISSUE THREAD

**Issue by gauravmahto** [Microsoft/vscode#60527]
- VSCode Version: 1.28.0 (user setup)
- OS Version: Win10(October update) Pro x64

After I updated my VSCode to v1.28.0, whenever I open a new terminal, the cursor position is not visible and the view port is always scrolled to the botton. When pressing any keystorke the characters are placed somewhere in the window(not at the correct position). After pressing the cariage return key, the curson position and view port will be set correctly.

Steps to Reproduce:

1. Open the code
2. Open new terminal

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/57803
