### ISSUE TITLE
Missing Menus

### ISSUE THREAD

**Issue by OdarGM** [Microsoft/vscode#60529]
After i update Visual Studio Code to version 1.2.8 the menu bar went missing
![http://media.odar.xyz/o5b57Qw4oa.png](http://media.odar.xyz/o5b57Qw4oa.png)

### This one^^^

Here it's Screenshot about how mine looks

![http://media.odar.xyz/F3a94av9b6.png](http://media.odar.xyz/F3a94av9b6.png)

### As you can see it's missing 

I tried re-insalling the editor few times but it didn't work

## Also the activity bar is missing and i dont know how to bring it back

 

- VSCode Version:  1.2.8
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Update to  version 1.2.8
2. Open Folder
3. It happend

Does this issue occur when all extensions are disabled?: Yes/No

Yes

**Comment by egamma** [comment]
What is your Menu bar visibility setting? 
![image](https://user-images.githubusercontent.com/172399/46750972-9116b280-ccb9-11e8-802b-9b1aec5c280b.png)

**Comment by OdarGM** [comment]
Oh it was hidden i fixed that

Thanks

but how do i fix the acticty bar

![http://media.odar.xyz/10u841F2k1.png](http://media.odar.xyz/10u841F2k1.png)


This^^^

**Comment by OdarGM** [comment]
its missing too

**Comment by OdarGM** [comment]
Never mind fixed it thanks for your help <3

Have a nice day!

**Comment by creal1976** [comment]
Stop emailing me

Sent from my Verizon Wireless 4G LTE DROID


Odar <notifications@github.com> wrote:


After i update Visual Studio Code to version 1.2.8 the menu bar went missing
[http://media.odar.xyz/o5b57Qw4oa.png]<https://camo.githubusercontent.com/5accf6ec718ea9527d194de6e1c06091ca0df6fc/687474703a2f2f6d656469612e6f6461722e78797a2f6f356235375177346f612e706e67>

This one^^^

Here it's Screenshot about how mine looks

[http://media.odar.xyz/F3a94av9b6.png]<https://camo.githubusercontent.com/e623ebd6128a11e7ae0904347d97dd810040fc4b/687474703a2f2f6d656469612e6f6461722e78797a2f463361393461763962362e706e67>

As you can see it's missing

I tried re-insalling the editor few times but it didn't work

Also the activity bar is missing and i dont know how to bring it back

  *   VSCode Version: 1.2.8
  *   OS Version: Windows 10 Pro

Steps to Reproduce:

  1.  Update to version 1.2.8
  2.  Open Folder
  3.  It happend

Does this issue occur when all extensions are disabled?: Yes/No

Yes

**Comment by OdarGM** [comment]
??? i didnt email you anything

**Comment by OdarGM** [comment]
@creal1976 it's from github because you are subscirbe to this thread 
They gave you link that will stop this notifications
