### ISSUE TITLE
Markdown preview urlencode link get arguments

### ISSUE THREAD

**Issue by corretge** [Microsoft/vscode#60525]
Markdown preview urlencode link get arguments then broken links when pasting in a rich text document.

- VSCode Version:  Version 1.28.0  431ef9da3cf88a7e164f9d33bf62695e07c6c2a9 2018-10-04T16:33:34.831Z
- OS Version: macOS Mojave 10.14 (18A391)

Steps to Reproduce:

1. Create a Markdown document with a link with parameters, i.e.: 
``` 
[Test](https://foo.com/bar?foo=1&bar=2)
```
2. Copy the preview link
3. Paste in a rich text document (in example mac Notes)
4. Follow the link, is broken.

If you follow the link from the preview, it works, but if you follow the link from the rich text you get

```
https://foo.com/bar?foo%3D1%26bar%3D2
``` 

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
I'm not able to reproduce this. How are you copying the link? In the markdown preview or in the editor?

**Comment by corretge** [comment]
Hi @mjbvz, I'm copying from the Preview pane.

**Comment by corretge** [comment]
Here a screenshot with the link urlencoded:

![image](https://user-images.githubusercontent.com/228097/46786648-cd87f400-cd35-11e8-9b36-cc03a9d0f78d.png)

Lots of thanks

**Comment by mjbvz** [comment]
How are you copying that link?

**Comment by corretge** [comment]
I'm copying the link in the preview pane selecting the text with the mouse and pressing Command & C keys simultaneously.

Today I installed [Markdown Preview Enhanced](https://github.com/shd101wyy/vscode-markdown-preview-enhanced) and then, works fine.

**Comment by mjbvz** [comment]
Notes for repo: I can't figure out how to copy the link from the preview hover but on macos you can just drag the link to textedit
