### ISSUE TITLE
How to hit debug break point for AspNet C# console app.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#6052]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows10

Steps to Reproduce:
1.  Create aspnet C# console project using yeoman. 
2. Open project folder in VSCode.
3. Set proper .net environment and configuration for debugging.
4. Update launch.json with properties:
              "stopAtEntry": true.
               "program": "${workspaceRoot}/bin/Debug/dnx451/win7-x64/TestCSharpWithVSCode.exe",
5. Set "debugType": "portable" in project.json.
6. Build project and set the brake point at entry point under program.cs (main function).
7. Now start debugging and verify app behavior.

Actual:
1. Debug break point is not hitting.
2. Should stop at entry point as stopAtEntry set to true.

Question: Am I missing something here? What are the settings I need to add to hit debug break point? 
I am following instructions from https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger.md

**Comment by weinand** [comment]
@v-pavanp C# debugging is a separate extension that is not part of VS Code core. I've moved this issue over to omnisharp-vscode.

**Comment by weinand** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#270
