### ISSUE TITLE
Is it possible to overwrite default sequence in integrated-terminal?

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#60524]
Having this in `Keybindings`:
```json
{
    "key": "ctrl+shift+c",
    "command": "workbench.action.terminal.sendSequence",
    "args": {
        "text": "\u0003Y\u000D"
    },
    "when": "terminalFocus && !terminalTextSelected"
}
```

The above works (kills process with confirmation on windows using <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>C</kbd> 2x), but it doesn't work for <kbd>Ctrl</kbd>+<kbd>c</kbd>:
```json
{
    "key": "ctrl+c",
    "command": "workbench.action.terminal.sendSequence",
    "args": {
        "text": "\u0003Y\u000D"
    },
    "when": "terminalFocus && !terminalTextSelected"
}

```
This one is sending default sequence and ignores user defined.

---

Version: 1.29.0-insider (user setup) Commit: cc5e2b41c3add18a31e87f84b5d6162566a38d6e Date: 2018-10-10T05:19:52.883Z

**Comment by Tyriar** [comment]
Good catch, this is happening because `sendSequence` is not in the default for `terminal.integrated.commandsToSkipShell`
