### ISSUE TITLE
Prompt powerhell and CMD hidden hidden wsl

### ISSUE THREAD

**Issue by 910321906** [Microsoft/vscode#60523]
O prompt do Powershell e do CMD desaparece depois de instalar WSl.

**Comment by egamma** [comment]
Translation: 
The Powershell and CMD prompt disappears after installing WSl.

Can you add more information about the prompot no longer appears.

**Comment by jiakme** [comment]
vscode: latest version
os: win10 latest version
input; win10 default
description: After I opened the terminal in vscode, the first line that you can write commands will become missing after you just had wrote something, such as "cd". And after you type "Enter", start a new line, it will become normal again.
the picture blow shows the issue.
![vscodeterminalissue](https://user-images.githubusercontent.com/8815138/46849965-701ea080-ce24-11e8-9b58-b967068ee303.PNG)
Thank you.

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/57803

**Comment by 910321906** [comment]
Muito agradecido pela vossa resposta, instantânea.
O problema é esse, não se via o prompt do cmd nem do powershell quando abria o terminal.
Eu ativei o WSL e pensei que fosse ele a causar esta problema porque o prompt do bash aparece bem.
Sim resolve-se digitando cls ou cd depois o prompt já aparece normalmente.

Mais uma vez muito agradecido pelo vosso feedback.

**Comment by Tyriar** [comment]
@910321906 yes, that's captured in #57803. See that issue for more details on the bug.
