### ISSUE TITLE
Gutter indicator colors for TFVC (similar to Git)

### ISSUE THREAD

**Issue by Da13Harris** [Microsoft/vscode#60530]
Add gutter indicator colors, like those linked below for Git, when using TFVC as a source control provider.

[https://code.visualstudio.com/Docs/editor/versioncontrol#_gutter-indicators](https://code.visualstudio.com/Docs/editor/versioncontrol#_gutter-indicators)

Visual Studio does it, so I know it's possible. Maybe ask the folks across the hall? ;-)

**Comment by creal1976** [comment]
Stop emailing me

Sent from my Verizon Wireless 4G LTE DROID


Dale Harris <notifications@github.com> wrote:


Add gutter indicator colors, like those linked below for Git, when using TFVC as a source control provider.

https://code.visualstudio.com/Docs/editor/versioncontrol#_gutter-indicators

Visual Studio does it, so I know it's possible. Maybe ask the folks across the hall? ;-)
