### ISSUE TITLE
Editor hover can overflow to top of screen

### ISSUE THREAD

**Issue by gggustafson** [microsoft/vscode#60534]
I am using flutter/dart in VS Code on Windows 7 SP1

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.8.2, on Microsoft Windows [Version 6.1.7601], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[√] VS Code, 64-bit edition (version 1.28.0)
[√] Connected devices (1 available)

• No issues found!
```

When I hover over a recognized object, a tooltip popup appears. A problem is that if the object over which I hover is close to the top of the screen, the tooltip appears too far up; its top contents are hidden; and I have to reposition the object lower on the screen.

The first image displays the tooltip positioning problem. I have hovered over **Column** (line 78) where **Column** is near the top of the screen.

![tooltip_too_high](https://user-images.githubusercontent.com/13719145/46751681-d965ae80-cc80-11e8-996b-01aae1a801b6.png)

The second image displays the tooltip when **Column** has been scrolled downward towards the center of the screen.

![tooltip_ok](https://user-images.githubusercontent.com/13719145/46751698-e4b8da00-cc80-11e8-92d3-b7bad99fe94a.png)

It appears that tooltips require 9 lines. So through simple computations, the tooltip could be placed so that all 9 lines of the tooltip appear near the object it is discussing without clipping.

**Comment by gggustafson** [comment]
Since I am using VS Code 1.28, the vscodebot once again provides worthless information. The suggested issue has **absolutely nothing to do with the issue** I raise!!

**Comment by egamma** [comment]
The bot can be understood since this issue is about the flutter extension, please file the issue against this repository.

**Comment by DanTup** [comment]
@egamma I'm the author of the extension and advised @gggustafson to post here. I don't know how the extension can control this (I actually raised a similar bug years ago -> https://github.com/Microsoft/vscode/issues/10051).

If you believe I can fix this, please give me a pointer.

**Comment by egamma** [comment]
@DanTup I´m deeply sorry you are absolutely right.

**Comment by gggustafson** [comment]
This issue is not a duplicate of #57088. That issue was concerned with the **size** of the popup. This issue regards the **positioning** of the popup. This issue is the same as #10051. But that was reported on Aug 2, 2016 by the extension author. **It has not been fixed!!!**

**Comment by joaomoreno** [comment]
@gggustafson Thanks for the heads up.
