### ISSUE TITLE
The regex /.*/ cannot match anything in Editor while /.+/ is ok

### ISSUE THREAD

**Issue by gjy1992** [Microsoft/vscode#6053]
- VSCode Version: 1.0.0
- OS Version: Windows 10

Steps to Reproduce:

1. open a text file
2. search .* with regex on
![qq 20160503113354](https://cloud.githubusercontent.com/assets/5539385/14974106/225f3776-1123-11e6-8039-1f120588bfc4.png)
![qq 20160503113500](https://cloud.githubusercontent.com/assets/5539385/14974107/2261eb4c-1123-11e6-8317-758b2688ddb4.png)

**Comment by gjy1992** [comment]
It seems that * is not work correctly when X* is the beginning of the regex.
![qq 1](https://cloud.githubusercontent.com/assets/5539385/14974158/ada232c0-1123-11e6-9a0c-cbd16d755874.png)
![qq 2](https://cloud.githubusercontent.com/assets/5539385/14974159/adadc914-1123-11e6-80e4-2957d7995d3a.png)

**Comment by alexandrudima** [comment]
The code that tries to protect against non-advancing regexes needs to be revisited.
