### ISSUE TITLE
Should custom menus have non-transparent background by default?

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#60543]
```json
"window.titleBarStyle": "custom"
```
If a theme doesn't specify **Menu Bar Colors** it gets some default values. But if the backup color have opacity then all custom menus are transparent:
![screenshot 58](https://user-images.githubusercontent.com/9638156/46758063-84ec1e80-ccd4-11e8-9708-5f0ae3dfd2e4.png)

Hate to bring it, but I forget every single time the setting name. It doesn't reflect what the setting does. At least add `menu` or `context` keywords to description.

**Comment by sbatten** [comment]
@usernamehw what theme is shown here? If I create a new theme without a menu background color specified, the default is not transparent.

**Comment by usernamehw** [comment]
Well, it defaults to dropdown background - and it **can** be transparent:
```typescript
export const selectBackground = registerColor('dropdown.background', { dark: '#3C3C3C', light: Color.white, hc: Color.black }, nls.localize('dropdownBackground', "Dropdown background."));
// ...
export const menuBackground = registerColor('menu.background', { dark: selectBackground, light: selectBackground, hc: selectBackground }, nls.localize('menuBackground', "Background color of menu items."));
```

You can try using `"dropdown.background": "#ff000020",` on `Solarized Light` theme.

**Comment by sbatten** [comment]
@usernamehw right, it uses dropdown as this is sensibly a similar style of UI, but dropdown also does not default to transparent. You can either override the theme that is using a transparent background for dropdown in your settings.json:
```
    "workbench.colorCustomizations": {
        "menu.background": "#ff0000"
    }
```
or report an issue with the theme
