### ISSUE TITLE
Push in Git's API

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#60547]
Right now we can do pull but not push with Git's API https://github.com/Microsoft/vscode/blob/0f02aa065e280d84c8ea17397faf4b397f8919db/extensions/git/src/api/git.d.ts . We are looking into allowing users to create pull request from the extension https://github.com/Microsoft/vscode-pull-request-github/pull/554 but without this API, we can only execute git command ourselves.

Not sure about the cost of adding this API, the shape of `push` in my mind can be like `push(remoteName: string, upstreamBranch: string, setUpstream: boolean)`.

**Comment by joaomoreno** [comment]
Fixed by https://github.com/Microsoft/vscode/pull/61448
