### ISSUE TITLE
Theme Disappearing/Deleted After Update

### ISSUE THREAD

**Issue by umbraesoulsbane** [Microsoft/vscode#60546]
I have a custom theme in the extensions folder. After updating this folder is always deleted. I assume this is because I didn't get this theme from the store and created and placed it myself. I really didn't want to go through the hassle of getting my personal theme in the store, but I also don't want to have to re-copy the thing over after every update. 

Is there a way to avoid my theme from getting delete every update? Is there a better place to put my personal theme than the extension folder?

**Comment by sandy081** [comment]
@umbraesoulsbane What do you mean by updating? Updating VS Code or updating the them extension? If it is updating the extension, how are you updating it?

**Comment by umbraesoulsbane** [comment]
Updating vs code. The theme is custom so it only updates when I open files and change them. :)

**Comment by aeschli** [comment]
The updater will remove the VSCode instllation including the built-in extensions. Don't put anything in there.
Instead use the extensions location in your user folder (e.g. `C:\Users\youruser\.vscode\extensions`)
