### ISSUE TITLE
Support PCRE2 regex searches

### ISSUE THREAD

**Issue by dwelle** [Microsoft/vscode#60553]
Since rigrep supports opt-in to PCRE2 [since August](https://github.com/BurntSushi/ripgrep/pull/1017), can VSCode support it, also?

If perf is a concern we could opt-in to PCRE2 (via `--pcre2` flag) only if the user uses PCRE2 syntax (such as lookbehind etc.).

Related: https://github.com/Microsoft/vscode/issues/50872

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/60218
