### ISSUE TITLE
Bug: file save but restored to a previous state (git enable)

### ISSUE THREAD

**Issue by Gettyk** [Microsoft/vscode#60550]
I made changed to a  file and save it, use git to stage the change and closed VS Code. When I reopen Vs Code, and modified another file and I open a new window. Usually the new window opens with a untitlled file but that time one  of my file where there (the one mentionned earlier). I close the window, it asked me to save the change. I didn't made change to the file and it appears as the last save but I press by error  yes (save the change). VS code freezed for 30 sec, the new window closed and my file appear in the first window but in a earlier version (of more than 24h ago )

(I could get the lastest version of my file in thanks to my last stage)

CPUs | Intel(R) Core(TM) i7-2760QM CPU @ 2.40GHz (8 x 2395)
-- | --
GPU Status | 2d_canvas: enabledchecker_imaging: disabled_offflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwarerasterization: unavailable_softwarevideo_decode: enabledvideo_encode: enabledwebgl: enabledwebgl2: enabled
Memory (System) | 7.90GB (2.07GB free)
Process Argv |  
Screen Reader | no
VM | 0%

Extension | Author (truncated) | Version
-- | -- | --
Bookmarks | ale | 9.1.0
project-manager | ale | 9.0.1
transformer | dak | 1.6.0
auto-close-tag | for | 0.5.6
macros | ged | 1.2.1
gc-excelviewer | Gra | 2.1.26
vscode-opn | lfu | 1.1.2
python | ms- | 2018.9.0
debugger-for-chrome | msj | 4.10.2
vscode-fileutils | sle | 2.11.0
vscode-autohotkey | sle | 0.2.2

**Comment by Tyriar** [comment]
It's not super clear what's happening, the hot exit feature may be behaving as expected. Can you please read https://code.visualstudio.com/docs/editor/codebasics#_hot-exit and clarify the expected behavior vs actual?

**Comment by Gettyk** [comment]
I have `hot exit` activated but that's not what is happening here.   

Step 1) I edited a file (file.html), saved it, staged it to git and then I close VS Code.   
Step 2) Sometimes later I reopened VS Code. While I was editing another file, I opened a new VS Code window by mistake. In this new windows I didn't have an "untitled file" (as usual) but "file.html" in its latest version. When I closed this new VS Code window, a pop up asked me if I wanted to save the changes (i don't know what changes because file.html was its latest version). I pressed yes by mistake. The new VS Code windows froze for 30 sec, I waited and then it closed itself. So I was back in the "first" VS Code window. There, I had  "file.html" but in an earlier version (more than 24h ago - so VS Code lost all the edits that I saved in step 1)

**Comment by Tyriar** [comment]
@Gettyk if you staged the file to git you should still have that copy unless you told git to clear the staged files? Also did some other source change the file between then and now? 

I can't reproduce the problem locally by doing the following:

1. Create a new folder and open VS Code in it
2. `git init` in the folder
3. Create a file.html, add content
4. `git add .`
5. Close the window
6. Open the window

**Comment by Gettyk** [comment]
Thanks for your time @Tyriar.  Yes I was able to get my file back, thanks to git. I don't really understand what happened. I just posted it here in case someone already had something similar.

**Comment by Tyriar** [comment]
@Gettyk good to hear, let us know if you see something like this happen again.
