### ISSUE TITLE
I would really like to see problems / output / debug / terminal window side by side located and integrated in visual studio.

### ISSUE THREAD

**Issue by saostad** [Microsoft/vscode#60555]
_Originally posted by @Tyriar in https://github.com/Microsoft/vscode/issues/41656#issuecomment-358006989_

please refer to this issue :
https://github.com/Microsoft/vscode/issues/41656

I think it's really useful feature.
Please let me know if it's already exist or open it .
Thanks

**Comment by isidorn** [comment]
This will come in the near future with the grid layout of the workbench. You can checkout our open feature requests for workbench-layout

**Comment by saostad** [comment]
thanks, looking forward to use it!
