### ISSUE TITLE
Missing all important commit characters for intellisense/suggestions in TypeScript (space, dot, colon, semicolon) and no setting for it

### ISSUE THREAD

**Issue by frevds** [Microsoft/vscode#60552]
Please provide a setting or simply add all characters to the commit list. 
It is super cumbersome to press Enter or Tab all the time while writing, to invoke the autocompletion, one of the biggest issues for people coming from visual studio, and so simple a feature to add. Thanks.

**Comment by mjbvz** [comment]
Please provide example code that shows where commit characters do not work

**Comment by frevds** [comment]
Are they supposed to work? They do not, did not ever, nowhere, not just a particular piece of code. 
If I type Foo, the suggestions open automatically (good), a match is highlighted (fantastic), and then I have to stop typing, press Enter or Tab to commit. If I fail to do so, e.g. by typing a dot (assuming that it will commit the highlighted word) to access a member of an object, then I end up with a partial identifier, have to delete that character and press Ctrl+Space again, followed by Enter or Tab. This is highly annoying. I can make a video of this.

**Comment by mjbvz** [comment]
Yes please upload a short video or gif of this. I haven't seen anything like what you describe

**Comment by frevds** [comment]
Strange, it does work, you're right, at least in the simple .ts file I made for the demo video. 
Apparently the issue only appears with more complex code (i.e. all my code). 
I'll try to create a standalone code file for reproducing the issue (as a video won't help), but tomorrow (late here), since I'm not allowed to hand out the code of my current project where I've got this issue.

**Comment by frevds** [comment]
I just installed the newest VSC update to 1.28.0 with TypeScript 3.1.1. 
**The issue seems gone! Apparently somebody fixed it already. 👍** 

Prior to this I had TypeScript 3.0.3 active, not sure which VSC version (not too old). 
I made a video of the **old behavior**: 

![vsc-commit-suggestions-issue](https://user-images.githubusercontent.com/5341447/46776125-83d5e400-cd0a-11e8-9af5-9fad332718e6.gif)
