### ISSUE TITLE
Ctrl + S no longer properly commits Git Message

### ISSUE THREAD

**Issue by DrewImm** [Microsoft/vscode#60554]
Ctrl+S no longer commits Git message

- VSCode Version: Latest (tested on in-siders as well)
- OS Version: Windows 10

Steps to Reproduce:

1. Initialize git repository and open in VS Code
2. Change a file and write a commit message
3. Press Ctrl + S while focused on the Commit Message field.  Previously, this would have saved the commit changes.  Now, it just saves the file.  

Does this issue occur when all extensions are disabled?
Yes

**Comment by DrewImm** [comment]
bot improperly labeled as Insiders label (I mentioned that I tested it on Insiders as per Contributing guidelines)

**Comment by joaomoreno** [comment]
Sorry about that. The keybinding is now configurable via the `scm.acceptInput` command, you can set it back to Ctrl S in your Keyboard Preferences.

**Comment by Sata51** [comment]
If you put this in the Keyboard Preferences you can no longer save a file in another panel.

Is it possible to assign a command contextually to avoid this side-effect ?

**Comment by DrewImm** [comment]
Updated "key" value to "ctrl+s" for Windows, but confirmed working and thank you very much!
