### ISSUE TITLE
Integrated terminal: Cycle only unique commands

### ISSUE THREAD

**Issue by Splike** [Microsoft/vscode#60558]
When cycling previously run commands with the up-arrow, it can look something like this
(read from bottom to top)
```
$ ls
$ java main.
$ javac main.java
$ java main
$ javac main.java
$ java main
$ javac main.java
$ java main
```
But I want an option to remove duplicate commands, when cycling through them, so it would look like this
(read from bottom to top)
```
$ ls
$ javac main.java
$ java main
```

**Comment by Tyriar** [comment]
This is up to how the shell manages history, we can't control this at all unfortunately.
