### ISSUE TITLE
Not getting any response while running DNX command multiple times.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#6055]
- VSCode Version: 1.1.0-alpha
- OS Version: windows10

Steps to Reproduce:
1. Create Aspnet C# console app using yeoman.
2. Set proper dotnet environment and verify response using dnx restore and dnx run.
3. Launch VSCode and open project folder.
4. Configure launch.json, task.json.
5. Perform DNX restore and DNX run command and verify response.
6, Now update project.json and add "debugType": "portable" under compilationOptions.
7. Build project and verify if any error message or warning is showing up.
8. Now try to perform "DNX restore" and "DNX: run command" operation from command palette and verify app behavior.

Actual: DNX command is responding very first time only and for further dnx execution there is no response.
Expected: User should get proper response when executing DNX command from command palette.

Note: Each time user needs to reload window or restart app to get DNX response.

![dnxissuenew](https://cloud.githubusercontent.com/assets/17735796/14974661/9e5a0a30-10ac-11e6-958e-bf95d4f551e3.gif)

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#271
