### ISSUE TITLE
Long JS strings are not formatted

### ISSUE THREAD

**Issue by maxwelljordanwhite** [Microsoft/vscode#60563]
- VSCode Version: 1.28.0 (1.28.0)
- OS Version: maxOS Mojava 10.14.1 Beta 

Steps to Reproduce:

1. Add a long string in a JS file, such as the following

`new Chunk("lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum. lorem ipsum."),`

<img width="2140" alt="screen shot 2018-10-10 at 5 25 41 pm" src="https://user-images.githubusercontent.com/7244793/46766978-8d7f2d80-ccb1-11e8-89a5-0db7ed919b6b.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
What is the expected behavior?

**Comment by maxjwhite** [comment]
Hi. Shouldn't it be styled, with any theme? I've tried several themes and they all do this, where the string isn't affected (the text is plain white). However, it works with shorter strings. 

Is this normal behavior? I didn't see why the syntax wouldn't be affected for larger text, like my example.

**Comment by mjbvz** [comment]
Ok, I can't repo this even making the string longer:

![screen shot 2018-10-12 at 11 46 06 am](https://user-images.githubusercontent.com/12821956/46888124-7016a480-ce14-11e8-9c49-4c52ac82e385.png)

Is that string part of a larger program? Please exact repo steps for this

**Comment by maxjwhite** [comment]
That is strange. No, it does this with only that text and in a program with it. Here's an example with more text, and less text. The one with less text seems to work, but more than that, it doesn't:

<img width="2229" alt="screen shot 2018-10-12 at 4 46 24 pm" src="https://user-images.githubusercontent.com/7244793/46893301-73268a80-ce3e-11e8-8bbf-23c34c7bbeec.png">

**Comment by creal1976** [comment]
I will file charges of harrasment if u don't stop emailing me

Sent from my Verizon Wireless 4G LTE DROID


Matt Bierner <notifications@github.com> wrote:


Ok, I can't repo this even making the string longer:

[screen shot 2018-10-12 at 11 46 06 am]<https://user-images.githubusercontent.com/12821956/46888124-7016a480-ce14-11e8-9c49-4c52ac82e385.png>

Is that string part of a larger program? Please exact repo steps for this

**Comment by maxwelljordanwhite** [comment]
@alexandrudima Hi, I don't believe so. It looks like it isn't working at even 1,066 characters

<img width="774" alt="screen shot 2018-10-17 at 7 15 51 am" src="https://user-images.githubusercontent.com/7244793/47082728-99507f80-d1dc-11e8-95c1-df70e962d291.png">

**Comment by alexandrudima** [comment]
@maxwelljordanwhite I cannot reproduce

I have created a new `.js` file with your content. I am trying on a VS Code installation without any settings and without any extensions:

![image](https://user-images.githubusercontent.com/5047891/47348338-8e509000-d6b1-11e8-8434-8f7e4fec6294.png)

Does this reproduce for you when disabling all extensions?

**Comment by maxwelljordanwhite** [comment]
@alexandrudima Hi, disabling all of my themes and extensions seemed to fix it. I'll report back once I discover which caused the issue. Thanks!

**Comment by alexandrudima** [comment]
I think it would be best to reach out to the extension author directly.
