### ISSUE TITLE
"Extension host is unresponsive" every few minutes

### ISSUE THREAD

**Issue by nategreen** [Microsoft/vscode#60561]
Issue Type: <b>Feature Request</b>

I don't actually care when the extension host goes responsive or unresponsive. **Please let me turn that obnoxious notification toast off**.

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 10.0.16299

**Comment by egamma** [comment]
Please see #60318
