### ISSUE TITLE
Strict null checking VS Code

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#60565]
Tracks engineering work to enable `strictNullChecks` in the VS Code code base.

## Problem
A steady number of issues are reported each month that are caused by null reference exceptions. Most of these are just simple programming errors, such as forgetting to initialize a value or not realizing that a function may return `undefined`.

## Proposal
To address this class of errors, I propose that we move to enable `strictNullChecks` in the main VS Code codebase. We have already successfully enabled `strictNullChecks` for our build scripts and for our built-in extensions, and I believe that these changes have been highly beneficial in catching common errors and enforcing better programming practices.

Today, building VS Code with `strictNullChecks` produces thousands of errors. Addressing these in a single pass is both impractical and would risk major regressions. I therefore propose we turn on `strictNullChecks` in our code base incrementally, opting in individual files until eventually `strictNullChecks` is enabled for the entire codebase.

## Implementation
To accomplish this, a new tsconfig called `tsconfig.strictNullChecks.json` will be introduced. This tsconfig will only be used for error checking. It will use `include` and `files` to compile only files that should be strict null checked. 

We will build `tsconfig.strictNullChecks.json` as part of our normal build process. A `strictNullChecks` failure  in `tsconfig.strictNullChecks.json` should cause the entire VS Code build to fail. This should prevent us from regressing `strictNullChecks` changes that have already been added

## How to help
This will be an long term engineer effort. The good news is that I believe we can do this incrementally and that each incremental change will improve the codebase in its own right.

Here's what's needed to make this work:

**For regular development**
Make sure your changes do not break the `tsconfig.strictNullChecks.json` build. You can check this manually by running: `yarn strict-null-check`

This script s part of our build pipelines. It is not run as part of `yarn compile` or `yarn watch` for performance reasons (doing so would essentially have us building the VS Code codebase twice) 

**Add a new file to be strict null checked**
1.  Add the file in the `files` section of `src/tsconfig.strictNullChecks.json`

    ```json
	"files": [
		"./vs/base/common/iterator.ts"
	]
    ```

    Keep in mind that this will also strict null check all files that the added file imports. Therefore it's best to start with files that either have very few imports or that only import files that are strict null checked.

2. Run `yarn strict-null-check` or `yarn strict-null-check -- --watch`

3. Fix all null check related errors. In general, this should involve:

    - Annotate nullable types and fix type errors
    - Use the `!` not null operator to tell TypeScript that a value cannot be null. Only use this if you are certain that a value absolutely cannot be `null` or `undefined` (i.e. you already checked this in code)
    - Add conditionals to handle null. Only change the actual logic if you believe that strict null checks has revealed a real programming error that must be handled.

4. Make sure you have not broken the normal VS Code build.

5. Check in your changes

**Comment by roblourens** [comment]
Will I see errors inline from this? Basically can VS Code check two overlapping tsconfig projects at the same time?

**Comment by mjbvz** [comment]
No, unfortunately that's not possible using multiple tsconfigs . I'll bring this up to the TS team to see if there is a better approach

**Comment by Tyriar** [comment]
@mjbvz I add xterm.js' strict null check project [as a pretest script](https://github.com/xtermjs/xterm.js/blob/58003d4e2985ee94f1f3aef209c554940bd517f0/package.json#L53), I assume most people run this before committing to that should help keep the build green.

**Comment by mjbvz** [comment]
@Tyriar Yes that's a good idea. At some point running the check may become quite slow but we can worry about that when we hit it

**Comment by mjbvz** [comment]
Status:

* Checked in `src/tsconfig.strictNullChecks.json` and opted in a few files
* Added a `yarn strict-null-check` script to builds this project.
* Run this script in the precommit checks
* Run this script in our Azure pipelines builds

**Comment by mjbvz** [comment]
Here's a list of files that have zero imports. These are a good starting point if you are looking to help out with conversion:

- [ ] `./vs/base/browser/history.ts`
- [ ] `./vs/base/browser/iframe.ts`
- [ ] `./vs/base/browser/ui/scrollbar/scrollbarState.ts`
- [ ] `./vs/base/common/collections.ts`
- [ ] `./vs/base/common/diff/diffChange.ts`
- [ ] `./vs/base/common/hash.ts`
- [ ] `./vs/base/common/json.ts`
- [ ] `./vs/base/common/jsonSchema.ts`
- [ ] `./vs/base/node/flow.ts`
- [ ] `./vs/base/node/ports.ts`
- [ ] `./vs/base/node/stream.ts`
- [ ] `./vs/base/parts/contextmenu/common/contextmenu.ts`
- [ ] `./vs/base/worker/workerMain.ts`
- [ ] `./vs/editor/common/core/position.ts`
- [ ] `./vs/editor/common/core/rgba.ts`
- [ ] `./vs/editor/common/core/token.ts`
- [ ] `./vs/editor/common/core/uint.ts`
- [ ] `./vs/editor/common/model/pieceTreeTextBuffer/rbTreeBase.ts`
- [ ] `./vs/editor/common/view/overviewZoneManager.ts`
- [ ] `./vs/editor/common/viewLayout/whitespaceComputer.ts`
- [ ] `./vs/editor/contrib/folding/foldingRanges.ts`
- [ ] `./vs/editor/contrib/indentation/indentUtils.ts`
- [ ] `./vs/editor/standalone/common/monarch/monarchCommon.ts`
- [ ] `./vs/editor/standalone/common/monarch/monarchTypes.ts`
- [ ] `./vs/nls.mock.ts`
- [ ] `./vs/platform/extensions/common/extensionHost.ts`
- [ ] `./vs/platform/extensions/common/extensions.ts`
- [ ] `./vs/platform/files/node/files.ts`
- [ ] `./vs/platform/instantiation/common/descriptors.ts`
- [ ] `./vs/workbench/common/extensionHostProtocol.ts`
- [ ] `./vs/workbench/parts/logs/common/logConstants.ts`
- [ ] `./vs/workbench/services/extensions/node/proxyIdentifier.ts`
- [ ] `./vs/workbench/test/electron-browser/api/mock.ts`

**Comment by roblourens** [comment]
If it ends up taking more than a few seconds to run, I would move it out of the precommit hook to `scripts/test` or something

**Comment by roblourens** [comment]
What if we have a simple extension that runs the script and shows errors inline?

Or like a clone of the TS extension that basically runs a second tsserver instance for the tsconfig

**Comment by mjbvz** [comment]
Yes I just used a script to opt a bunch of files in to strict null checks (a2738f73e556ae2a26eebc05deae0075c94d0e9a) so I guess it's already time to worry :) I'll move the check to run in the test scripts instead

Extension is an interesting idea. I think we could also use a task and a problem matcher

**Comment by joaomoreno** [comment]
Love this. Yeah, I was coming in saying I am worried about the pre-commit check. Tests is fine, we are always watching the build.

**Comment by alexandrudima** [comment]
:-1: on running the compiler every time I invoke `scripts/test.sh`. I run the tests very often, it is part of the way I develop, and the extra slowness brought in is noticeable.

**Comment by mjbvz** [comment]
One common cause of strict typing errors in our code is nulling out properties in `dispose` implementations. To fix this, we can:

* Mark these properties as nullable. This usually introduces a strict check error where ever else we try to use the property. These errors are correct but fixing them is not straightforward.

* Decide that trying to use an object after it is disposed is undefined behavior and should possible throw reference errors. If we go this route, I propose we explicitly annotate why nulling out is ok:

    ```js
	dispose(): void {
		super.dispose();
		this.el = null!; // StrictNullOverride: nulling out ok in dispose
	}
    ```

    This would let us revisit these decisions later if we want too. As part of this work, we could also add `assert(!this.isDisposed)` at the top of every public method that could trigger these type of reference errors

Thoughts?

**Comment by joaomoreno** [comment]
Another alternative is not to null non-nullable properties. Garbage collection should collect everything correctly if the last top level reference is indeed released.

**Comment by alexandrudima** [comment]
@mjbvz I think the tool that lists files has some sort of issue, because it doesn't list the tree as a candidate for strict null checking. The tree sits at `vs/base/parts/tree` and is (indirectly) blocking the completion of the `/editor/` folder.

**Comment by mjbvz** [comment]
@alexandrudima This is because `tree.ts` has a cycle. I'll update the script to handle that

Yes eventually we will need the test files to be covered too. How do we feel about trying to get more community participation for the test files at least?

**Comment by JoshuaKGoldberg** [comment]
I'm writing a project to add missing type annotations, `!` markers, etc. using static analysis. @roblourens - you mentioned this likely isn't appropriate for non-test source code, as some of it needs to be refactored, but might be fine for `src/**/*.test.ts`.

@mjbvz / etc. - would you accept a PR that adds `| null`, `| undefined`, and `!`s where needed in test files to get them added to `tsconfig.strictNullChecks.json`? Any particular restrictions?

**Comment by mjbvz** [comment]
@JoshuaKGoldberg Yes definitely, so long as the fixes and suppressions make sense.

I just opened #65233 to try to get community help strict null checking our test files. Do you want to try using the tool on a few of the eligible test file and we can see how it works?

**Comment by mjbvz** [comment]
Now that we're strict null checked much of the codebase, here's a complete list of the remaining unchecked files. Please quickly look over this to see which areas you own

Most of these files blocked from being fully checked by their dependencies, so keep using [this list](https://github.com/Microsoft/vscode/issues/60565#issuecomment-428777490) to see what files we can enable strict null checking for. However you can do work to fix strict null errors within these individual files and just not add them the `tsconfig.strictNullChecks.json` until their dependencies are also checked.

**Updated: February 19, 2019**

- [ ] `"./vs/editor/contrib/goToDefinition/goToDefinitionCommands.ts"`
- [ ] `"./vs/editor/contrib/goToDefinition/goToDefinitionMouse.ts"`
- [ ] `"./vs/editor/contrib/referenceSearch/referencesController.ts"`
- [ ] `"./vs/editor/contrib/referenceSearch/referenceSearch.ts"`
- [ ] `"./vs/editor/editor.all.ts"`
- [ ] `"./vs/editor/editor.main.ts"`
- [ ] `"./vs/editor/standalone/browser/referenceSearch/standaloneReferenceSearch.ts"`
- [ ] `"./vs/platform/backup/test/electron-main/backupMainService.test.ts"`
- [ ] `"./vs/platform/extensionManagement/test/electron-browser/extensionEnablementService.test.ts"`
- [ ] `"./vs/platform/extensionManagement/test/node/extensionGalleryService.test.ts"`
- [ ] `"./vs/platform/state/test/node/state.test.ts"`
- [ ] `"./vs/platform/storage/test/node/storageService.test.ts"`
- [ ] `"./vs/platform/telemetry/test/electron-browser/commonProperties.test.ts"`
- [ ] `"./vs/platform/theme/test/electron-browser/colorRegistry.releaseTest.ts"`
- [ ] `"./vs/platform/workspaces/test/electron-main/workspacesMainService.test.ts"`
- [ ] `"./vs/workbench/api/browser/viewsExtensionPoint.ts"`
- [ ] `"./vs/workbench/api/electron-browser/extensionHost.contribution.ts"`
- [ ] `"./vs/workbench/api/electron-browser/mainThreadComments.ts"`
- [ ] `"./vs/workbench/api/electron-browser/mainThreadDocuments.ts"`
- [ ] `"./vs/workbench/api/electron-browser/mainThreadDocumentsAndEditors.ts"`
- [ ] `"./vs/workbench/api/electron-browser/mainThreadEditors.ts"`
- [ ] `"./vs/workbench/api/electron-browser/mainThreadExtensionService.ts"`
- [ ] `"./vs/workbench/api/electron-browser/mainThreadHeapService.ts"`
- [ ] `"./vs/workbench/api/electron-browser/mainThreadLanguageFeatures.ts"`
- [ ] `"./vs/workbench/api/electron-browser/mainThreadSaveParticipant.ts"`
- [ ] `"./vs/workbench/api/electron-browser/mainThreadTask.ts"`
- [ ] `"./vs/workbench/api/electron-browser/mainThreadWebview.ts"`
- [ ] `"./vs/workbench/api/node/apiCommands.ts"`
- [ ] `"./vs/workbench/api/node/extHost.api.impl.ts"`
- [ ] `"./vs/workbench/api/node/extHostApiCommands.ts"`
- [ ] `"./vs/workbench/api/node/extHostCommands.ts"`
- [ ] `"./vs/workbench/api/node/extHostComments.ts"`
- [ ] `"./vs/workbench/api/node/extHostDebugService.ts"`
- [ ] `"./vs/workbench/api/node/extHostDiagnostics.ts"`
- [ ] `"./vs/workbench/api/node/extHostDocumentContentProviders.ts"`
- [ ] `"./vs/workbench/api/node/extHostDocuments.ts"`
- [ ] `"./vs/workbench/api/node/extHostDocumentsAndEditors.ts"`
- [ ] `"./vs/workbench/api/node/extHostDocumentSaveParticipant.ts"`
- [ ] `"./vs/workbench/api/node/extHostExtensionService.ts"`
- [ ] `"./vs/workbench/api/node/extHostFileSystem.ts"`
- [ ] `"./vs/workbench/api/node/extHostFileSystemEventService.ts"`
- [ ] `"./vs/workbench/api/node/extHostLanguageFeatures.ts"`
- [ ] `"./vs/workbench/api/node/extHostLanguages.ts"`
- [ ] `"./vs/workbench/api/node/extHostProgress.ts"`
- [ ] `"./vs/workbench/api/node/extHostQuickOpen.ts"`
- [ ] `"./vs/workbench/api/node/extHostSCM.ts"`
- [ ] `"./vs/workbench/api/node/extHostStatusBar.ts"`
- [ ] `"./vs/workbench/api/node/extHostTask.ts"`
- [ ] `"./vs/workbench/api/node/extHostTerminalService.ts"`
- [ ] `"./vs/workbench/api/node/extHostTextEditor.ts"`
- [ ] `"./vs/workbench/api/node/extHostTextEditors.ts"`
- [ ] `"./vs/workbench/api/node/extHostTreeViews.ts"`
- [ ] `"./vs/workbench/api/node/extHostTypeConverters.ts"`
- [ ] `"./vs/workbench/api/node/extHostWebview.ts"`
- [ ] `"./vs/workbench/browser/actions/listCommands.ts"`
- [ ] `"./vs/workbench/browser/dnd.ts"`
- [ ] `"./vs/workbench/browser/labels.ts"`
- [ ] `"./vs/workbench/browser/layout.ts"`
- [ ] `"./vs/workbench/browser/parts/activitybar/activitybarActions.ts"`
- [ ] `"./vs/workbench/browser/parts/activitybar/activitybarPart.ts"`
- [ ] `"./vs/workbench/browser/parts/compositeBar.ts"`
- [ ] `"./vs/workbench/browser/parts/compositeBarActions.ts"`
- [ ] `"./vs/workbench/browser/parts/editor/breadcrumbsControl.ts"`
- [ ] `"./vs/workbench/browser/parts/editor/breadcrumbsPicker.ts"`
- [ ] `"./vs/workbench/browser/parts/editor/editor.contribution.ts"`
- [ ] `"./vs/workbench/browser/parts/editor/editorActions.ts"`
- [ ] `"./vs/workbench/browser/parts/editor/editorCommands.ts"`
- [ ] `"./vs/workbench/browser/parts/editor/editorDropTarget.ts"`
- [ ] `"./vs/workbench/browser/parts/editor/editorGroupView.ts"`
- [ ] `"./vs/workbench/browser/parts/editor/editorPart.ts"`
- [ ] `"./vs/workbench/browser/parts/editor/editorStatus.ts"`
- [ ] `"./vs/workbench/browser/parts/editor/noTabsTitleControl.ts"`
- [ ] `"./vs/workbench/browser/parts/editor/tabsTitleControl.ts"`
- [ ] `"./vs/workbench/browser/parts/editor/textDiffEditor.ts"`
- [ ] `"./vs/workbench/browser/parts/editor/textResourceEditor.ts"`
- [ ] `"./vs/workbench/browser/parts/editor/titleControl.ts"`
- [ ] `"./vs/workbench/browser/parts/panel/panelActions.ts"`
- [ ] `"./vs/workbench/browser/parts/panel/panelPart.ts"`
- [ ] `"./vs/workbench/browser/parts/titlebar/menubarControl.ts"`
- [ ] `"./vs/workbench/browser/parts/titlebar/titlebarPart.ts"`
- [ ] `"./vs/workbench/browser/parts/views/customView.ts"`
- [ ] `"./vs/workbench/common/editor/diffEditorInput.ts"`
- [ ] `"./vs/workbench/common/editor/resourceEditorInput.ts"`
- [ ] `"./vs/workbench/common/editor/resourceEditorModel.ts"`
- [ ] `"./vs/workbench/common/editor/textDiffEditorModel.ts"`
- [ ] `"./vs/workbench/common/editor/textEditorModel.ts"`
- [ ] `"./vs/workbench/common/editor/untitledEditorInput.ts"`
- [ ] `"./vs/workbench/common/editor/untitledEditorModel.ts"`
- [ ] `"./vs/workbench/contrib/backup/common/backup.contribution.ts"`
- [ ] `"./vs/workbench/contrib/backup/common/backupModelTracker.ts"`
- [ ] `"./vs/workbench/contrib/codeEditor/electron-browser/codeEditor.contribution.ts"`
- [ ] `"./vs/workbench/contrib/codeEditor/electron-browser/workbenchReferenceSearch.ts"`
- [ ] `"./vs/workbench/contrib/codeinset/electron-browser/codeInset.contribution.ts"`
- [ ] `"./vs/workbench/contrib/codeinset/electron-browser/codeInsetWidget.ts"`
- [ ] `"./vs/workbench/contrib/comments/electron-browser/commentNode.ts"`
- [ ] `"./vs/workbench/contrib/comments/electron-browser/comments.contribution.ts"`
- [ ] `"./vs/workbench/contrib/comments/electron-browser/commentsEditorContribution.ts"`
- [ ] `"./vs/workbench/contrib/comments/electron-browser/commentsPanel.ts"`
- [ ] `"./vs/workbench/contrib/comments/electron-browser/commentsTreeViewer.ts"`
- [ ] `"./vs/workbench/contrib/comments/electron-browser/commentThreadWidget.ts"`
- [ ] `"./vs/workbench/contrib/debug/browser/baseDebugView.ts"`
- [ ] `"./vs/workbench/contrib/debug/browser/breakpointsView.ts"`
- [ ] `"./vs/workbench/contrib/debug/browser/debugActions.ts"`
- [ ] `"./vs/workbench/contrib/debug/browser/debugCommands.ts"`
- [ ] `"./vs/workbench/contrib/debug/browser/debugEditorActions.ts"`
- [ ] `"./vs/workbench/contrib/debug/browser/debugEditorModelManager.ts"`
- [ ] `"./vs/workbench/contrib/debug/browser/debugQuickOpen.ts"`
- [ ] `"./vs/workbench/contrib/debug/browser/debugToolbar.ts"`
- [ ] `"./vs/workbench/contrib/debug/browser/debugViewlet.ts"`
- [ ] `"./vs/workbench/contrib/debug/browser/loadedScriptsView.ts"`
- [ ] `"./vs/workbench/contrib/debug/common/debugModel.ts"`
- [ ] `"./vs/workbench/contrib/debug/common/replModel.ts"`
- [ ] `"./vs/workbench/contrib/debug/electron-browser/breakpointWidget.ts"`
- [ ] `"./vs/workbench/contrib/debug/electron-browser/callStackView.ts"`
- [ ] `"./vs/workbench/contrib/debug/electron-browser/debug.contribution.ts"`
- [ ] `"./vs/workbench/contrib/debug/electron-browser/debugConfigurationManager.ts"`
- [ ] `"./vs/workbench/contrib/debug/electron-browser/debugEditorContribution.ts"`
- [ ] `"./vs/workbench/contrib/debug/electron-browser/debugHover.ts"`
- [ ] `"./vs/workbench/contrib/debug/electron-browser/debugService.ts"`
- [ ] `"./vs/workbench/contrib/debug/electron-browser/debugSession.ts"`
- [ ] `"./vs/workbench/contrib/debug/electron-browser/electronDebugActions.ts"`
- [ ] `"./vs/workbench/contrib/debug/electron-browser/repl.ts"`
- [ ] `"./vs/workbench/contrib/debug/electron-browser/terminalSupport.ts"`
- [ ] `"./vs/workbench/contrib/debug/electron-browser/variablesView.ts"`
- [ ] `"./vs/workbench/contrib/debug/electron-browser/watchExpressionsView.ts"`
- [ ] `"./vs/workbench/contrib/debug/node/debugger.ts"`
- [ ] `"./vs/workbench/contrib/debug/node/terminals.ts"`
- [ ] `"./vs/workbench/contrib/debug/test/browser/baseDebugView.test.ts"`
- [ ] `"./vs/workbench/contrib/debug/test/browser/debugANSIHandling.test.ts"`
- [ ] `"./vs/workbench/contrib/debug/test/browser/linkDetector.test.ts"`
- [ ] `"./vs/workbench/contrib/debug/test/common/debugViewModel.test.ts"`
- [ ] `"./vs/workbench/contrib/debug/test/electron-browser/debugModel.test.ts"`
- [ ] `"./vs/workbench/contrib/debug/test/node/debugger.test.ts"`
- [ ] `"./vs/workbench/contrib/experiments/test/electron-browser/experimentalPrompts.test.ts"`
- [ ] `"./vs/workbench/contrib/experiments/test/electron-browser/experimentService.test.ts"`
- [ ] `"./vs/workbench/contrib/extensions/electron-browser/extensionEditor.ts"`
- [ ] `"./vs/workbench/contrib/extensions/electron-browser/extensionProfileService.ts"`
- [ ] `"./vs/workbench/contrib/extensions/electron-browser/extensions.contribution.ts"`
- [ ] `"./vs/workbench/contrib/extensions/electron-browser/extensionsAutoProfiler.ts"`
- [ ] `"./vs/workbench/contrib/extensions/electron-browser/extensionsViewlet.ts"`
- [ ] `"./vs/workbench/contrib/extensions/electron-browser/extensionsViews.ts"`
- [ ] `"./vs/workbench/contrib/extensions/electron-browser/runtimeExtensionsEditor.ts"`
- [ ] `"./vs/workbench/contrib/extensions/test/electron-browser/extensionsActions.test.ts"`
- [ ] `"./vs/workbench/contrib/extensions/test/electron-browser/extensionsTipsService.test.ts"`
- [ ] `"./vs/workbench/contrib/extensions/test/electron-browser/extensionsViews.test.ts"`
- [ ] `"./vs/workbench/contrib/extensions/test/electron-browser/extensionsWorkbenchService.test.ts"`
- [ ] `"./vs/workbench/contrib/files/browser/editors/binaryFileEditor.ts"`
- [ ] `"./vs/workbench/contrib/files/browser/editors/fileEditorTracker.ts"`
- [ ] `"./vs/workbench/contrib/files/browser/editors/textFileEditor.ts"`
- [ ] `"./vs/workbench/contrib/files/common/dirtyFilesTracker.ts"`
- [ ] `"./vs/workbench/contrib/files/common/editors/fileEditorInput.ts"`
- [ ] `"./vs/workbench/contrib/files/electron-browser/explorerViewlet.ts"`
- [ ] `"./vs/workbench/contrib/files/electron-browser/fileActions.contribution.ts"`
- [ ] `"./vs/workbench/contrib/files/electron-browser/fileActions.ts"`
- [ ] `"./vs/workbench/contrib/files/electron-browser/fileCommands.ts"`
- [ ] `"./vs/workbench/contrib/files/electron-browser/files.contribution.ts"`
- [ ] `"./vs/workbench/contrib/files/electron-browser/saveErrorHandler.ts"`
- [ ] `"./vs/workbench/contrib/files/electron-browser/views/emptyView.ts"`
- [ ] `"./vs/workbench/contrib/files/electron-browser/views/explorerView.ts"`
- [ ] `"./vs/workbench/contrib/files/electron-browser/views/explorerViewer.ts"`
- [ ] `"./vs/workbench/contrib/files/electron-browser/views/openEditorsView.ts"`
- [ ] `"./vs/workbench/contrib/files/test/browser/fileEditorInput.test.ts"`
- [ ] `"./vs/workbench/contrib/files/test/browser/fileEditorTracker.test.ts"`
- [ ] `"./vs/workbench/contrib/files/test/electron-browser/explorerModel.test.ts"`
- [ ] `"./vs/workbench/contrib/files/test/electron-browser/fileActions.test.ts"`
- [ ] `"./vs/workbench/contrib/html/common/htmlInput.ts"`
- [ ] `"./vs/workbench/contrib/html/electron-browser/html.contribution.ts"`
- [ ] `"./vs/workbench/contrib/html/electron-browser/htmlPreviewPart.ts"`
- [ ] `"./vs/workbench/contrib/markers/electron-browser/markers.contribution.ts"`
- [ ] `"./vs/workbench/contrib/markers/electron-browser/markersPanel.ts"`
- [ ] `"./vs/workbench/contrib/markers/electron-browser/markersTreeViewer.ts"`
- [ ] `"./vs/workbench/contrib/outline/browser/outline.contribution.ts"`
- [ ] `"./vs/workbench/contrib/output/browser/logViewer.ts"`
- [ ] `"./vs/workbench/contrib/output/browser/outputActions.ts"`
- [ ] `"./vs/workbench/contrib/output/browser/outputPanel.ts"`
- [ ] `"./vs/workbench/contrib/output/electron-browser/output.contribution.ts"`
- [ ] `"./vs/workbench/contrib/output/electron-browser/outputServices.ts"`
- [ ] `"./vs/workbench/contrib/output/test/outputLinkProvider.test.ts"`
- [ ] `"./vs/workbench/contrib/performance/electron-browser/performance.contribution.ts"`
- [ ] `"./vs/workbench/contrib/performance/electron-browser/perfviewEditor.ts"`
- [ ] `"./vs/workbench/contrib/performance/electron-browser/startupProfiler.ts"`
- [ ] `"./vs/workbench/contrib/preferences/browser/keybindingsEditor.ts"`
- [ ] `"./vs/workbench/contrib/preferences/browser/keybindingsEditorContribution.ts"`
- [ ] `"./vs/workbench/contrib/preferences/browser/keybindingWidgets.ts"`
- [ ] `"./vs/workbench/contrib/preferences/browser/preferencesActions.ts"`
- [ ] `"./vs/workbench/contrib/preferences/browser/preferencesEditor.ts"`
- [ ] `"./vs/workbench/contrib/preferences/browser/preferencesRenderers.ts"`
- [ ] `"./vs/workbench/contrib/preferences/browser/preferencesWidgets.ts"`
- [ ] `"./vs/workbench/contrib/preferences/browser/settingsLayout.ts"`
- [ ] `"./vs/workbench/contrib/preferences/browser/settingsTree.ts"`
- [ ] `"./vs/workbench/contrib/preferences/browser/settingsTreeModels.ts"`
- [ ] `"./vs/workbench/contrib/preferences/browser/tocTree.ts"`
- [ ] `"./vs/workbench/contrib/preferences/common/preferences.ts"`
- [ ] `"./vs/workbench/contrib/preferences/common/preferencesContribution.ts"`
- [ ] `"./vs/workbench/contrib/preferences/electron-browser/preferences.contribution.ts"`
- [ ] `"./vs/workbench/contrib/preferences/electron-browser/preferencesSearch.ts"`
- [ ] `"./vs/workbench/contrib/preferences/electron-browser/settingsEditor2.ts"`
- [ ] `"./vs/workbench/contrib/preferences/test/browser/keybindingsEditorContribution.test.ts"`
- [ ] `"./vs/workbench/contrib/preferences/test/browser/settingsTreeModels.test.ts"`
- [ ] `"./vs/workbench/contrib/scm/electron-browser/scm.contribution.ts"`
- [ ] `"./vs/workbench/contrib/scm/electron-browser/scmViewlet.ts"`
- [ ] `"./vs/workbench/contrib/search/browser/search.contribution.ts"`
- [ ] `"./vs/workbench/contrib/search/browser/searchActions.ts"`
- [ ] `"./vs/workbench/contrib/search/browser/searchResultsView.ts"`
- [ ] `"./vs/workbench/contrib/search/browser/searchView.ts"`
- [ ] `"./vs/workbench/contrib/search/browser/searchWidget.ts"`
- [ ] `"./vs/workbench/contrib/search/test/browser/searchActions.test.ts"`
- [ ] `"./vs/workbench/contrib/search/test/browser/searchViewlet.test.ts"`
- [ ] `"./vs/workbench/contrib/search/test/common/queryBuilder.test.ts"`
- [ ] `"./vs/workbench/contrib/tasks/electron-browser/task.contribution.ts"`
- [ ] `"./vs/workbench/contrib/terminal/electron-browser/terminal.contribution.ts"`
- [ ] `"./vs/workbench/contrib/terminal/electron-browser/terminalPanel.ts"`
- [ ] `"./vs/workbench/contrib/terminal/electron-browser/terminalService.ts"`
- [ ] `"./vs/workbench/contrib/update/electron-browser/releaseNotesEditor.ts"`
- [ ] `"./vs/workbench/contrib/update/electron-browser/update.contribution.ts"`
- [ ] `"./vs/workbench/contrib/update/electron-browser/update.ts"`
- [ ] `"./vs/workbench/contrib/watermark/electron-browser/watermark.ts"`
- [ ] `"./vs/workbench/contrib/webview/electron-browser/baseWebviewEditor.ts"`
- [ ] `"./vs/workbench/contrib/webview/electron-browser/webview.contribution.ts"`
- [ ] `"./vs/workbench/contrib/webview/electron-browser/webviewCommands.ts"`
- [ ] `"./vs/workbench/contrib/webview/electron-browser/webviewEditor.ts"`
- [ ] `"./vs/workbench/contrib/webview/electron-browser/webviewEditorInput.ts"`
- [ ] `"./vs/workbench/contrib/webview/electron-browser/webviewEditorInputFactory.ts"`
- [ ] `"./vs/workbench/contrib/webview/electron-browser/webviewEditorService.ts"`
- [ ] `"./vs/workbench/contrib/webview/electron-browser/webviewElement.ts"`
- [ ] `"./vs/workbench/contrib/webview/electron-browser/webviewFindWidget.ts"`
- [ ] `"./vs/workbench/electron-browser/main.contribution.ts"`
- [ ] `"./vs/workbench/electron-browser/main.ts"`
- [ ] `"./vs/workbench/electron-browser/workbench.ts"`
- [ ] `"./vs/workbench/test/browser/part.test.ts"`
- [ ] `"./vs/workbench/test/browser/parts/editor/baseEditor.test.ts"`
- [ ] `"./vs/workbench/test/browser/parts/editor/breadcrumbModel.test.ts"`
- [ ] `"./vs/workbench/test/browser/parts/editor/rangeDecorations.test.ts"`
- [ ] `"./vs/workbench/test/browser/parts/views/views.test.ts"`
- [ ] `"./vs/workbench/test/browser/quickopen.test.ts"`
- [ ] `"./vs/workbench/test/common/editor/dataUriEditorInput.test.ts"`
- [ ] `"./vs/workbench/test/common/editor/editor.test.ts"`
- [ ] `"./vs/workbench/test/common/editor/editorDiffModel.test.ts"`
- [ ] `"./vs/workbench/test/common/editor/editorGroups.test.ts"`
- [ ] `"./vs/workbench/test/common/editor/editorInput.test.ts"`
- [ ] `"./vs/workbench/test/common/editor/editorModel.test.ts"`
- [ ] `"./vs/workbench/test/common/editor/resourceEditorInput.test.ts"`
- [ ] `"./vs/workbench/test/common/editor/untitledEditor.test.ts"`
- [ ] `"./vs/workbench/test/common/memento.test.ts"`
- [ ] `"./vs/workbench/test/electron-browser/api/extHostApiCommands.test.ts"`
- [ ] `"./vs/workbench/test/electron-browser/api/extHostCommands.test.ts"`
- [ ] `"./vs/workbench/test/electron-browser/api/extHostDiagnostics.test.ts"`
- [ ] `"./vs/workbench/test/electron-browser/api/extHostDocumentsAndEditors.test.ts"`
- [ ] `"./vs/workbench/test/electron-browser/api/extHostDocumentSaveParticipant.test.ts"`
- [ ] `"./vs/workbench/test/electron-browser/api/extHostFileSystemEventService.test.ts"`
- [ ] `"./vs/workbench/test/electron-browser/api/extHostLanguageFeatures.test.ts"`
- [ ] `"./vs/workbench/test/electron-browser/api/extHostSearch.test.ts"`
- [ ] `"./vs/workbench/test/electron-browser/api/extHostTextEditor.test.ts"`
- [ ] `"./vs/workbench/test/electron-browser/api/extHostTextEditors.test.ts"`
- [ ] `"./vs/workbench/test/electron-browser/api/extHostTreeViews.test.ts"`
- [ ] `"./vs/workbench/test/electron-browser/api/extHostTypeConverter.test.ts"`
- [ ] `"./vs/workbench/test/electron-browser/api/extHostWebview.test.ts"`
- [ ] `"./vs/workbench/test/electron-browser/api/mainThreadConfiguration.test.ts"`
- [ ] `"./vs/workbench/test/electron-browser/api/mainThreadDocuments.test.ts"`
- [ ] `"./vs/workbench/test/electron-browser/api/mainThreadDocumentsAndEditors.test.ts"`
- [ ] `"./vs/workbench/test/electron-browser/api/mainThreadEditors.test.ts"`
- [ ] `"./vs/workbench/test/electron-browser/api/mainThreadSaveParticipant.test.ts"`
- [ ] `"./vs/workbench/test/electron-browser/quickopen.perf.integrationTest.ts"`
- [ ] `"./vs/workbench/test/electron-browser/textsearch.perf.integrationTest.ts"`
- [ ] `"./vs/workbench/test/workbenchTestServices.ts"`
- [ ] `"./vs/workbench/workbench.main.ts"`

**Comment by bpasero** [comment]
Done with `vs/workbench/(common|browser|electron-browser)/**`

**Comment by mjbvz** [comment]
![](https://media.giphy.com/media/SjInxhAJTzU7S/giphy.gif)

Just 325 strict null errors left in just a handful of files. Owners of these files should have an issue open. Please take a look so that we can enable strict null in our normal build

**Comment by extmchristensen** [comment]
@mjbvz It could be very interesting if you publicized some behind-the-scenes data for this effort, such as roughly how many bugs was found in the codebase as a result of this and how much effort it took ?

**Comment by mjbvz** [comment]
Zero. I can't think of a single instance where we knew of a bug and strict null checking fixed it.

But that's not why this work is valuable. By better specifying our code's behavior with strict null checks, we (mostly) eliminated an entire class of future potential bugs, both in existing our code and in our future written code, enabling us to work more safely and quickly going forward.

So: 0 known bugs fixed. ∞ potential bugs prevented

**Comment by rudi-c** [comment]
@mjbvz Amazing effort! Do you think you might write a blog post about the process at some point? I'm sure lots of people would be interested.

**Comment by mjbvz** [comment]
[Blog post](https://code.visualstudio.com/blogs/2019/05/23/strict-null)
