### ISSUE TITLE
Provide list of scopes available to themes

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#6056]
See http://stackoverflow.com/questions/36940822/complete-list-of-theme-elements-to-colorize

It would be handy to have a list on the website of available scopes. This list could be extracted from the .tmLanguage files for each language programmatically.

**Comment by aeschli** [comment]
I replied on stackoverflow and added a section Q&A in the themes documentation page.
IMO the best advice about what scopes to use is to follow the text mate specs. Avoid language specific rules and don't make any assumptions on the grammars we use, as they can be replaced by extensions.
