### ISSUE TITLE
uninstall000.exe频繁弹窗

### ISSUE THREAD

**Issue by MOLLMY** [Microsoft/vscode#60578]
VS code经常弹出一个错误窗口显示C:\Program Files\Microsoft VS Code\unins000.exe 尝试在目标目录创建文件时出错：拒绝访问。这个exe不是卸载用的吗，我没有卸载，只是正常使用，点击“中止”、“重试”、“忽略”中的任一个都不能阻止它频繁弹这个窗口

**Comment by egamma** [comment]
Translation: 

>VS code often pops up an error window showing C:\Program Files\Microsoft VS Code\unins000.exe An error occurred while trying to create a file in the target directory: access denied. This exe is not uninstalled, I did not uninstall, just normal use, click on "Abort", "Retry", "Ignore" can not prevent it from playing this window frequently

**Comment by joaomoreno** [comment]
@MOLLMY Please fully reinstall VS Code, as it seems something broke along the way.
