### ISSUE TITLE
vscode terminal  bug with Chinese keyboard

### ISSUE THREAD

**Issue by NateLing** [microsoft/vscode#60576]
- VSCode Version: 1.28
- OS Version: macos 10.14

vscode terminal is not friendly when use chinese keyboard.

1. input word throw by wubixing.
2. press ctrl+v when you are inputing chinese word.
3. press space key
 
look this video
[https://youtu.be/yzf_J0ZPInA](url)

**Comment by lwshang** [comment]
I ran into the same buggy behavior of integrated terminal. This issue was labeled with `upstream` by @Tyriar . So what upstream dependency cause this problem?

**Comment by Tyriar** [comment]
@lwshang https://github.com/xtermjs/xterm.js, you should be able to repro IME-related issues on xterm.js' demo

**Comment by lwshang** [comment]
> @lwshang https://github.com/xtermjs/xterm.js, you should be able to repro IME-related issues on xterm.js' demo

Thanks. Will check there.

**Comment by Tyriar** [comment]
Please create any issues you have with IME input in the upstream repo https://github.com/xtermjs/xterm.js, include version/OS information and detailed repro steps (I'm not familiar with that IME).
