### ISSUE TITLE
Focus previous editor after closing active editor

### ISSUE THREAD

**Issue by rmccue** [Microsoft/vscode#60574]
Currently, when closing the active editor (<kbd>⌘+W</kbd>), the previous recently used editor is focussed next. For users who do not want to use MRU functionality, it would be useful to be able to focus the previous (indexed) editor instead.

e.g:
1. Open files `a`, `b`, `c`, `d` (`d` is now focussed)
2. Focus file `b`
3. Close file `b`
4. Observe `d` is now focussed, rather than `a`

VS Code allows overriding MRU functionality by rebinding the tabbing shortcuts, e.g. <kbd>⌃+Tab</kbd> from `workbench.action.openNextRecentlyUsedEditorInGroup` to `workbench.action.nextEditor`, but no such distinction appears to exist for `workbench.action.closeActiveEditor`. Additionally, you can't rebind the close button in the UI, so this would likely need a preference.

(Sorry if this has been filed previously, was unable to find while searching!)

**Comment by rmccue** [comment]
Can you clarify which issue this was a duplicate of? As mentioned, I could not find one, so I’m likely looking for the wrong thing:)

**Comment by rmccue** [comment]
@egamma @bpasero Hi, sorry to ping again! Can you please let me know what the duplicate issue is, as I am unable to find it? :)

**Comment by bpasero** [comment]
@rmccue https://github.com/Microsoft/vscode/issues/57554

**Comment by rmccue** [comment]
Aha, thanks very much!
