### ISSUE TITLE
Error with RN 0.57

### ISSUE THREAD

**Issue by super918180** [Microsoft/vscode#60586]
![image](https://user-images.githubusercontent.com/20025505/46778413-2069a780-cd46-11e8-9b36-291b7a8caed9.png)

**Comment by egamma** [comment]
What is the problem, can you describe what is incorrect on the screenshot?

**Comment by mjbvz** [comment]
I believe you are running into this TypeScript issue: https://github.com/Microsoft/TypeScript/issues/27421
