### ISSUE TITLE
Mac / Window: Title Bar Style - setting does not work

### ISSUE THREAD

**Issue by WebVeteran** [Microsoft/vscode#60587]
Issue Type: <b>Bug</b>

The setting "Window: Native Tabs" when enabled makes Code use the native _window title bar_, even though "Window: Title Bar Style" is set to 'custom' (not native).

I have restarted several times while toggling to test.

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-04T16:40:40.180Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 3400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-close-tag|for|0.5.6
coldfusion|ili|1.0.1
sftp|lix|1.5.13

(2 theme extensions excluded)

</details>

**Comment by WebVeteran** [comment]
Not full screen. Just a regular window. Also this is probably Mac only.

See attached. This is after the setting change and restart. Based on the settings shown, I should have the custom VSC title bar - not the native title bar.

![image](https://user-images.githubusercontent.com/40175/46779642-b53cb880-cce6-11e8-97b5-bc27e6ad4bf8.png)

**Comment by ctsstc** [comment]
Mine has no title bar at all when it's set to custom
![image](https://user-images.githubusercontent.com/416814/46854480-c99bb680-cdb5-11e8-9202-f63528edbffa.png)

**Comment by sbatten** [comment]
@WebVeteran Native tabs are currently by design incompatible with the custom title bar style. The second line of the native tabs setting description calls this out.
