### ISSUE TITLE
Integrated terminal doesn't show the path when it starts

### ISSUE THREAD

**Issue by tonijarjour** [Microsoft/vscode#60580]
Without doing anything the terminal starts like this:
![image](https://user-images.githubusercontent.com/39845673/46776820-558ce000-ccdb-11e8-881e-ecc04689c76f.png)

Scroll up to the top shows this:
![image](https://user-images.githubusercontent.com/39845673/46776853-6e959100-ccdb-11e8-86d9-093e6cdfcee9.png)

Type something:
![image](https://user-images.githubusercontent.com/39845673/46776869-81a86100-ccdb-11e8-912d-cbe79b6f0e31.png)

Press Enter:
![image](https://user-images.githubusercontent.com/39845673/46776900-97b62180-ccdb-11e8-9346-87eac9444016.png)

I want to note that this issue is not present when the terminal is on the right and not the bottom.

**Comment by SimonLoir** [comment]
I have experienced this issue too but with the terminal on the right. It happened after the last Windows 10 update (1809) but I'm not sure it's related.

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/57803
