### ISSUE TITLE
'Workbench › Editor: Show Tabs' changed to false itself

### ISSUE THREAD

**Issue by liubiantao** [Microsoft/vscode#60583]
- VSCode Version: Version 1.28.0 (1.28.0)
- OS Version: macOS 10.13.6 (17G65)

Steps to Reproduce:

1. Coding several weeks
2. Shut Down computer
3. Starting up, open VSCode
4. `Workbench › Editor: Show Tabs` automatic change from `true` to `false` in `USER SETTING`

Last year, this happened more than 10 times, including my Windows PC, Mac mini, MacBook Pro.
And it's not only me, I found many users same as me, they did nothing, but show tabs changed!

> @RMacfarlane I finally found it's my user setting incorrect, i set
workbench.editor.showTabs=false
which cause it, It's ok now. but i don't remember when did i set it ....
https://github.com/Microsoft/vscode/issues/51649#issuecomment-397529971

https://github.com/Microsoft/vscode/issues/42179#issuecomment-360675176
https://github.com/Microsoft/vscode/issues/40440#issuecomment-352672249

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by liubiantao** [comment]
@bpasero I guess you are right, but let me coding without any extension for weeks, it's terrible.
How can I  know which extension did that?  Is there any way I can debug?

**Comment by sandy081** [comment]
Try opening VS Code on extension installation folder and do a search on `showTabs` in the extensions code and see if any extension is updating the setting?

**Comment by alekseyt** [comment]
Can this be reopened?

I encountered the same issue twice already and i think i know thy this happens, this is not an extension i believe: key binding for `Toggle Tab Visibility` is set to `Ctrl+Super+W`. Normal (at least for me) shortcut to close file is `Ctrl+W`, i guess it's possible to unintentionally press Super key sometimes and toggle this option on.

Maybe default shortcut for `Toggle Tab Visibility` can be reconsidered. When this happens it's very hard to understand what happened and how to fix it.

**Comment by sandy081** [comment]
@alekseyt Please file separate a new issue/request for changing the default shortcut
