### ISSUE TITLE
windows x64 1.28.0.exe;git show chinese fault

### ISSUE THREAD

**Issue by mazhan465** [Microsoft/vscode#60581]
Issue Type: <b>Bug</b>

1.update to 1.28.0 x64
2.input git log show chinese commit log and resuluit is like "<E4><BF><AE><E6><94><B9><E6><96><87><E6><9C><AC><E6><96><87><E6><A1><A3>"

even I try to fix it for input "git config --global i18n.commitencoding utf-8 
git config --global i18n.logoutputencoding gbk".
It no more change .And when I reinstall 1.27.2 x64 and inuput "git config --global i18n.commitencoding utf-8 
git config --global i18n.logoutputencoding gbk",everything is normal.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|3.93GB (1.04GB free)|
|Process Argv|D:\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
node-module-intellisense|lei|1.5.0
vscode-language-pack-zh-hans|MS-|1.28.2
python|ms-|2018.9.0
cpptools|ms-|0.19.0
Go|ms-|0.6.91
markdown-all-in-one|yzh|1.6.2

</details>

**Comment by gimlyon** [comment]
![image](https://user-images.githubusercontent.com/20081668/46856263-7e76b780-ce38-11e8-8d56-cf4db21c0286.png)
Then I use this command: `export LESSCHARSET=utf-8`. 
![image](https://user-images.githubusercontent.com/20081668/46856353-cb5a8e00-ce38-11e8-9799-bfb5585682e5.png)
The commit log is normal now! But when I restart the vscode, the problem happen again~~

**Comment by tonny-zhang** [comment]
@gimlyon 
This can help you, https://github.com/Microsoft/vscode/issues/60717

**Comment by huleiEthan** [comment]
> @gimlyon @mazhan465
> This can help you, #60717

It's work!! Thank you!
