### ISSUE TITLE
Cannot keybind "workbench.action.files.newFile"

### ISSUE THREAD

**Issue by oodboo** [Microsoft/vscode#6059]
- VSCode Version: Version 1.0.0
- OS Version: Windows 10

Steps to Reproduce:

1. Create keybinding snippet:
   {
        "key": "ctrl+alt+n",     "command": "workbench.action.files.newFile",
                                    "when": ""
    }
2. When keys ("ctrl+alt+n) are pressed while in Explorer message pop ups:
"No handler found for the command "workbench.action.files.newFile", An extension may be missing active event."

I have checked VSCode base and I can see the code for :** workbench.action.files.newFile**

[fileActions.ts](https://github.com/Microsoft/vscode/blob/3ac0ead70531884389000844bb505c56a193d48e/src/vs/workbench/parts/files/browser/fileActions.ts)
Line 472: NewFileAction 

What am I missing? Do I need to restrict with when, but never the less, error says it is not finding handler at all...

**Comment by bpasero** [comment]
You can give it a try from our insiders release today: http://code.visualstudio.com/Download#insiders

**Comment by oodboo** [comment]
Thank you it is working in  1.1.0-insider
