### ISSUE TITLE
[Interaction]when i search someting the expand disabled!

### ISSUE THREAD

**Issue by Lanseria** [Microsoft/vscode#60599]
When I try to search, I encounter this problem and end the search. The file can't view the folded content normally. Only when I restart the `vscode`, the problem is solved.
![image](https://user-images.githubusercontent.com/14802764/46785750-523e3680-cd65-11e8-9f9f-ddbadd46d1ab.png)
normally as follow:
![image](https://user-images.githubusercontent.com/14802764/46785870-ac3efc00-cd65-11e8-8d4d-96c65fcb34d9.png)
global:
![image](https://user-images.githubusercontent.com/14802764/46785948-f0ca9780-cd65-11e8-98f7-bedf1c90d5b1.png)

版本: 1.28.0 (user setup)
提交: 431ef9da3cf88a7e164f9d33bf62695e07c6c2a9
日期: 2018-10-05T14:58:53.203Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
架构: x64

**Comment by aeschli** [comment]
@Lanseria Sorry, I don't understand what the issue is.
Can you give a small code example and detailed steps to show the problem.

When navigating through the search results, and a search match is in a folded region, we always expand the region.

**Comment by Lanseria** [comment]
@aeschli I am not sure how this bug will happen, but I did encounter it, but I can't reproduce the bug.
