### ISSUE TITLE
Please add support form Haml/Slim. Most of the new frameworks use these languages instead of html

### ISSUE THREAD

**Issue by sibinx7** [Microsoft/vscode#606]
There are lots of frameworks uses haml/slim as template languages. Haml and Slim save lots of time. So please add support for haml and slim in visual studio code.

**Comment by berwyn** [comment]
Wouldn't this belong in an extension? A basic language extension could be made from https://github.com/handcrafted/handcrafted-haml-textmate-bundle and further enhanced from there.

**Comment by egamma** [comment]
Agreed this support should be provided by an extension and not the VS Code core.
