### ISSUE TITLE
When implements interface in typescript adds import before element

### ISSUE THREAD

**Issue by inferius** [Microsoft/vscode#60606]
Hi, implements interface in typescript auto adds import with absolute path before element of class.

- VSCode Version: 1.28.0
- OS Version: Windows 10

Steps to Reproduce:
![ezgif-1-cab6cff57ba4](https://user-images.githubusercontent.com/7590016/46789397-99fc9800-cd3c-11e8-9b20-f0271207a971.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Please try upgrading your workspace to use `typescript@next` by following [these instructions](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions). Do you still see this error after upgrading?

**Comment by inferius** [comment]
Yes, i still see this error after upgrading.

**Comment by mjbvz** [comment]
Thanks for testing. Can you please share your tsconfig and a basic description of your project structure

**Comment by DanTup** [comment]
@mjbvz I see this too. I've pushed a branch with a repro here:

https://github.com/Dart-Code/Dart-Code/tree/vscode-60606-repro

Clone the `vscode-60606-repro` branch, open `src/pub/pub_task_provider.ts` and then use the quick-fix to implement the interface. I changed it to `typescript@latest` and see the same issue.

<img width="564" alt="screen shot 2018-10-23 at 9 57 51 am" src="https://user-images.githubusercontent.com/1078012/47349141-db7d3380-d6aa-11e8-8739-bde7cc05df9f.png">
<img width="1155" alt="screen shot 2018-10-23 at 9 57 56 am" src="https://user-images.githubusercontent.com/1078012/47349142-db7d3380-d6aa-11e8-81bc-36d74bd481de.png">
<img width="235" alt="screen shot 2018-10-23 at 10 03 01 am" src="https://user-images.githubusercontent.com/1078012/47349144-db7d3380-d6aa-11e8-9d7e-60eeed844f70.png">

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#28165
