### ISSUE TITLE
Display X number of preceeding and following lines in search results

### ISSUE THREAD

**Issue by janez-svetin** [Microsoft/vscode#60608]
Hi! Currently, in search results (either in sidebar or panel) you can see only the line that contains the search keyword. 

<img width="1605" alt="screen shot 2018-10-11 at 10 05 38" src="https://user-images.githubusercontent.com/7753805/46789658-4474bb00-cd3d-11e8-9c4b-ef7a0b08fa9d.png">

A cool feature to have would be to view additional lines in search results that come before and after that line. So, if you would have a setting to view additional 1 line, each search result would display 3 lines (one more before search result, one more after). In that way you can easily have more context when searching and find exact match faster. Sublime IDE have this and I find it very useful and missing it in vscode.

<img width="1605" alt="screen shot 2018-10-11 at 10 05 38" src="https://i.stack.imgur.com/VAlkA.jpg">

Alternative to setting how many lines you would want to see is that vscode handles that automatically (as is the case with Sublime, see above).

 Thanks!

**Comment by roblourens** [comment]
I have https://github.com/Microsoft/vscode/issues/59458 to support this internally, I think I won't try to support it in the search view but enable extensions to show search results somewhere else.
