### ISSUE TITLE
Xamarin IOS info.plist Device Orientation Changes After Save

### ISSUE THREAD

**Issue by MonkeyLucas** [Microsoft/vscode#60604]
- VSCode Version:  15.8.7 15.8.6
- OS Version:

Every time I go in to Info.plist in order to lock the app to Portrait orientation and save, my changes aren't saved.
For more detail you can access [https://stackoverflow.com/questions/52747057/windows-vs-xamarin-ios-info-plist-device-orientation-changes-after-save](url)
This issue appears on VS for Window 15.8.7 and 15.8.6 . And VS for mac works fine.

**Comment by egamma** [comment]
There is no such version of Visual Studio Code. You must report your issue against the wrong repository, sorry.

**Comment by ferdgonz** [comment]
Its actually Windows VS 15.8.1 2017
