### ISSUE TITLE
[loc][Query][VSCode] Ampersand position

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#6060]
Hi, we have a question from a translator. Could you help please?

Source:
&amp;&amp;Reopen Closed File

File Name:
src\vs\workbench\electron-main\menus.nls.resx

Resource ID:
".resx", 0; "miReopenClosedFile"

Query:
Please confirm the two ampersands in the source string should be inserted in the source as is.	inho.chung	4/27/2016 1:27:00 PM

**Comment by bpasero** [comment]
@mkyjakova nls.localize({ key: 'miReopenClosedFile', comment: ['**&& denotes a mnemonic**'] }, "&&Reopen Closed File")

**Comment by mkyjakova** [comment]
Thanks!
