### ISSUE TITLE
Quick file view is broken for python files (Intellisense for Python)

### ISSUE THREAD

**Issue by arvindkumarc** [Microsoft/vscode#60609]
- VSCode Version: 1.28.0 (1.28.0) - 2018-10-04T16:33:34.831Z
- OS Version: MacOS High Sierra 10.13.6

Steps to Reproduce:
1. Open any python file where Intellisense for python is enabled. 
2. cmd+p is mapped to something else and not quick file view

Does this issue occur when all extensions are disabled?: No

**Comment by egamma** [comment]
From the description it is not clear whether this is Python specific issue. 
When I type CMD+P in a Python file then Quick Open is shown as expected. 
Please provide more details with screenshot what you problem is.
Please review whether you have changed the key binding for CMD+P.
