### ISSUE TITLE
Global search doesn't work properly

### ISSUE THREAD

**Issue by Mi-lex** [Microsoft/vscode#60601]
- VSCode Version: 1.28.0
- OS Version: Windows 10 (x64)

Steps to Reproduce:

1. Press Ctrl+Shift + F
2. Type a string
3. Search

Searching doesn't seem to find all occurrences, especially when files are deep in folders, even if files were _recently opened_.

When I _disable all extensions_, it doesn't work, either.
I don't have errors in devTools window.

I reinstalled VsCode. Didn't help.

Another editor is able to perform global search. It takes some time, but still.

**Comment by Mi-lex** [comment]
Here is the output ![log](https://user-images.githubusercontent.com/30773104/46789302-c7e5da80-cd44-11e8-82aa-3ac1686652d2.png).

**Comment by roblourens** [comment]
Can you see the wiki section on missing search results and let me know whether that helps? https://github.com/Microsoft/vscode/wiki/Search-Issues

**Comment by Mi-lex** [comment]
The search works when I stop using **Exclude Settings and Ignore files**, although I deleted every pattern in excluded files list.
![doesn't work when I use the option](https://user-images.githubusercontent.com/30773104/46878965-6f4e3480-ce4d-11e8-8281-5b6e70b1d9b4.png)

Well, I got results I needed, so thank you.

**Comment by roblourens** [comment]
Are they covered by a gitignore file?

**Comment by Mi-lex** [comment]
Right. I completely forgot that I had default one. Of course the file included _vendor_ folder whose files I needed to be in results. 
I turned of **Search: Use Ignore Files** and everything worked. Thank you again)
