### ISSUE TITLE
Workbench(terminal etc.) - Position

### ISSUE THREAD

**Issue by septoun** [Microsoft/vscode#60619]
Hi,
The little **sign** in **workbench** which allowed you to switch the **workbench**(terminal, problems, output, debug)position is not there anymore.

Problem: 
Trying to change the workbench position doesn't work, since the setting can't be saved and do not change afterwards.
 **user settings > workbench > Panel: default location > bottom/right**

-- I am student from Germany and English is not my primary language, still i hope there is a solution to the problem since i couldn't find one by myself.

**Comment by isidorn** [comment]
As designed, dup of https://github.com/Microsoft/vscode/issues/60548

@bpasero this is already the second guy complaing about this in insiders
I think from stable I might get a shitstorm. We should consider bringing it back
