### ISSUE TITLE
Markdown syntax highlighting can't handle C# using statement in fenced code block

### ISSUE THREAD

**Issue by kolletzki** [Microsoft/vscode#60610]
Issue Type: <b>Bug</b>

The [C# using statement] isn't highlighted correctly in a [fenced code block] with C# syntax highlighting in a markdown file.

Steps to reproduce:

1. Create a new file
2. Select markdown language (Ctrl-K M -> "Markdown" -> return)
3. Create a [fenced code block] with C# highlighting and a using statement in it (see below)
4. -> Highlighting until the first semicolon is incorrect

Example file content to reproduce:

    ```csharp
    using (var x = new X())
    {
        var y = "test";
        var z = "test";
    }
    ```

Result:

![image](https://user-images.githubusercontent.com/1665745/46790560-8999ec80-cd3f-11e8-94d7-ed9f55863386.png)

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz (6 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|16.00GB (3.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.3.2
compareit|in4|0.0.2
eml|lei|0.3.1
Go|ms-|0.6.91
PowerShell|ms-|1.9.0
vscode-hexdump|sle|1.7.0
markdown-pdf|yza|1.2.0

</details>

[C# using statement]: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement
[fenced code block]: https://github.github.com/gfm/#code-fence

**Comment by mjbvz** [comment]
Same behavior in regular c# files: 

<img width="416" alt="screen shot 2018-10-11 at 4 46 34 pm" src="https://user-images.githubusercontent.com/12821956/46839917-3c387200-cd75-11e8-8924-7c6a754cd5d8.png">

**Comment by aeschli** [comment]
The problem is with the C# grammar. when seeing `using`, it seems to assume that what follows is a using static directive.

**Comment by aeschli** [comment]
This issue was moved to dotnet/csharp-tmLanguage#140
