### ISSUE TITLE
Can't copy value from the Debugger Variables list (Go/Delve)

### ISSUE THREAD

**Issue by altimac** [Microsoft/vscode#60618]
<img width="445" alt="screen shot 2018-10-11 at 11 26 17" src="https://user-images.githubusercontent.com/778986/46794627-89521f00-cd48-11e8-94e9-76f1c2cd3925.png">
Issue Type: <b>Bug</b>

I'm using the Go delve debugger (remote mode) inside VSCode and right clicking any of the local variables in the debugger (displaying the correct variable values!) only displays a *disabled* contextual menu where I can't copy (or set) value.

Copying a variable value from the debugger is pretty basic debugging workflow.

Thanks

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:04:11.329Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|32.00GB (0.50GB free)|
|Process Argv|/private/var/folders/18/6dc39z5x1jjc_9qnltvmtm4r0000gn/T/AppTranslocation/457D544F-36C3-45A2-800E-298DB26F3262/d/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
Go|ms-|0.6.91
vscode-docker|Pet|0.3.1
xcode-keybindings|ste|1.0.0

</details>

**Comment by isidorn** [comment]
Please file this agains the go and delve debugger and tell them they have to support `evaluateName` property for this actions to be enabled
