### ISSUE TITLE
Extension Host is unresponsive

### ISSUE THREAD

**Issue by ipapoutsidis** [Microsoft/vscode#60620]
Dear community,
I am sharing with you the issue "Extension Host is unresponsive"  that I have with my Vscode editor.
The extension that was causing this problem was " Bracket Pair Colorizer",
so I follow the steps in https://code.visualstudio.com/updates/v1_28#_extension-host-unresponsive" and I just Uninstall the extension and the problem was solved.
I hope it was helpful.

**Comment by egamma** [comment]
Thank you for your report. This warning has caused confusion and we will correct it, pls see #60318
