### ISSUE TITLE
Blank screen after recent update (when launching from existing shortcut)

### ISSUE THREAD

**Issue by JakeSidSmith** [Microsoft/vscode#60621]
Solved ourselves, but worth reporting...

After a recent update one of my colleagues VSCode opened to a completely blank screen when launching from the dock icon (Mac).

<img width="617" alt="screen shot 2018-10-11 at 10 33 36" src="https://user-images.githubusercontent.com/5850625/46795813-ffec1e00-cd42-11e8-84fd-112e340b3d79.png">

Could not get to settings, access the dev tools, etc. It was as if electron had not initialized.

Fortunately after some time we realized that launching VSCode from Applications worked fine.

**FIX:** We fixed this by removing the existing dock icon, and dragging the app from Applications into the dock again.

Maybe this is just an OSX issue, but in case it could be fixed here I thought it'd be worth mentioning.

Interestingly only one of my colleagues has had this issue, even though there are many of us using the same OS and VSCode.

- VSCode Version: 1.28.1
- OS Version: Mac OSX High Sierra 10.13.4

Steps to Reproduce (theoretically):

1. Install older VSCode version
2. Drag app into dock
3. Update VSCode
4. Try to launch from dock icon

Does this issue occur when all extensions are disabled?: Yes/No

I imagine this would work (though we didn't get a chance to test it before we fixed the issue) as it'd be referencing the binary rather than a shortcut.

**Comment by joaomoreno** [comment]
@JakeSidSmith Was it reproducible? If you would quit Code in that state and run it again from the dock, the same would happen? Only after deleting the dock shortcut and recreating it, did it open, is that correct?

**Comment by JakeSidSmith** [comment]
@joaomoreno that's correct.

**Comment by joaomoreno** [comment]
@bpasero This seems independent from update, maybe related to workbench startup/themes.

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by JakeSidSmith** [comment]
@bpasero we've unfortunately already removed the icon (though it could be in my colleagues trash, I'll have a look).

Though I think running code from the terminal will work as expected, and we could not open the developer tools when it was in the blank state.

Will get back to you shortly.

**Comment by JakeSidSmith** [comment]
It seems the shortcut from the dock is gone forever. Not sure how we could reproduce now.

**Comment by bpasero** [comment]
Ok.
