### ISSUE TITLE
Per-user background update fails on a RDP server

### ISSUE THREAD

**Issue by anttiah** [Microsoft/vscode#60625]
VSCode Version:
> Version: 1.27.2 (user setup)
> Commit: f46c4c469d6e6d8c46f268d1553c5dc4b475840f
> Date: 2018-09-12T16:17:45.060Z
> Electron: 2.0.7
> Chrome: 61.0.3163.100
> Node.js: 8.9.3
> V8: 6.1.534.41
> Architecture: x64

Relevant settings.json entries:
`"update.enableWindowsBackgroundUpdates": true`

OS Version:
> Windows Server 2012 R2
> Remote Desktop Session Host role
> No per-system installed VS Code present (user installs only)

Steps to Reproduce:
1. Log on to a RDS server using account with administrative access.
2. Try to update your per-user installed VS Code using background updater.
3. Make sure no UAC elevation prompts are shown.

Expected result:
VS Code updates itself

Actual, incorrect result:
Update fails with error
```
---------------------------
VS Code
---------------------------
There was an error while attempting to kill any running Code.exe processes:

Failed to open process: Access is denied.


Please verify there are no VS Code processes still executing.
---------------------------
Retry   Cancel   
---------------------------
```
and

```
---------------------------
VS Code
---------------------------
Failed to install VS Code update.

Updates may fail due to anti-virus software and/or runaway processes. Please try restarting your machine before attempting to update again.

If update fails repeatedly, please attach the following log file to a new issue on GitHub:

C:\Users\<myusername>\AppData\Local\Temp\7\vscode-inno-updater-1539252851.log
---------------------------
OK   
---------------------------
```
The log file shows that updater tried to kill code.exe processes started by other users that are currently logged on the server.

Does this issue occur when all extensions are disabled?: Yes

Workaround
--
Update succeeded after disabling background updates:
`"update.enableWindowsBackgroundUpdates": false`

**Comment by joaomoreno** [comment]
I'd say that's a pretty good workaround for RDP environments: disable background updates.
