### ISSUE TITLE
UpdateService is unable to disable

### ISSUE THREAD

**Issue by fzzr-** [Microsoft/vscode#60627]
- VSCode Version: 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, x64)
- OS Version: macOS 10.12.6 (16G1036)

Steps to Reproduce:

1. turn off following settings:
  - `update.enableWindowsBackgroundUpdates`
  - `extensions.autoCheckUpdates`
  - `extensions.autoUpdate`
  - `telemetry.enableTelemetry`
  - `telemetry.enableCrashReporter`
2. reboot Vscode
3. ![screen shot 2018-10-11 at 13 31 46](https://user-images.githubusercontent.com/888526/46798631-2ae26c00-cd5b-11e8-9a3e-8d7dc190d186.png)

Does this issue occur when all extensions are disabled?: __Yes__

![screen shot 2018-10-11 at 13 48 17](https://user-images.githubusercontent.com/888526/46799124-97119f80-cd5c-11e8-97ac-d31afe35172b.png)

**Expected behaviour:**

When all `autoUpdate`-options are disabled, no-one process is expected to produce requests to the update-server for any purposes.

**Comment by fzzr-** [comment]
@vscodebot you are made mistake. There is no needed tag `extensions`.

**Comment by joaomoreno** [comment]
The setting you're looking for is `update.channel = none`

**Comment by fzzr-** [comment]
So I cannot disable __auto__-updates and __auto__-check-updates without disabling possibility of checking updates manually (File menu / Check Updates)?

And I found related [issue (#12817)](https://github.com/Microsoft/vscode/issues/12817) and it's not a problem - it's "as designed".

Why this is designed so uncomfortably? Is there a technical reason for this?
Will full manual updates (without auto) be implemented in future versions?

Cause now I have two options:
- enable auto-updates (by default)
- disable updates completely:
  - auto-check-updates
  - auto-updates
  - __check updates manually__
  - __manual updates__

**Comment by joaomoreno** [comment]
You're right, I've reopened the original issue.
