### ISSUE TITLE
Unable to use vim-way navigation when focusing to Problems

### ISSUE THREAD

**Issue by bunadmitrii** [Microsoft/vscode#60629]
In earlier versions (1.25.x) I used to navigate through `Problems` panel using vim's `jk` buttons, b ut currently it is not possible since the text is being appeared inside the filter input.

- VSCode Version: 1.28.0
- OS Version: Ubuntu 18.04
- VsCodeVIM: 0.16.9

Steps to Reproduce:

1. Open problems panel
2. Try to navigate using vim's binding

The screenshot:

![problems](https://user-images.githubusercontent.com/32439381/46801167-8f54f980-cd62-11e8-885b-e34877176051.png)

I would propose to be able to type into the filter input when it's focused on.

**Comment by sandy081** [comment]
I do not think if we ever officially supported vim commands inside a view.
