### ISSUE TITLE
rg (ripgrep) continues to hog disk after search stopped

### ISSUE THREAD

**Issue by cpboyd** [Microsoft/vscode#60639]
- VSCode Version: 1.28.0
- OS Version: Linux (Ubuntu 18.04)
- Commit: 431ef9da3cf88a7e164f9d33bf62695e07c6c2a9
- Date: 2018-10-05T14:52:58.945Z
- Electron: 2.0.9
- Chrome: 61.0.3163.100
- Node.js: 8.9.3
- V8: 6.1.534.41
- Architecture: x64

Steps to Reproduce:

1. Start search on a large nesting of folders (e.g. a Yocto project)
2. Stop search.
3. Observe that multiple rg processes are still present, reading from the disk.

This issue causes a huge slowdown on systems with traditional hard drives.

Not sure if this also impacts other OSes.

Does this issue occur when all extensions are disabled?: **Yes**

Edit: rg processes are stopped whenever VS Code is closed.

**Comment by roblourens** [comment]
I can't repro this. Do some of the processes go away immediately when search is cancelled, and some stick around?

**Comment by cpboyd** [comment]
Perhaps?  I hadn't entirely paid attention.

I do know there were multiple `rg` processes still cranking through several MB/s.

As I mentioned, they almost always go away immediately after closing the VS code window (though I did notice a process stick around for another minute in one instance).

It's on a Yocto project, so one search I was filtering for bitbake files with "*.bb".  (which is also what caused me to notice it... because `rg` was basically causing the Yocto builds to slow down immensely whenever it needed to do any sort of I/O operation)

In a test just now, there was only **one** `rg` process spawned when I did a search for "test" (without any file modifiers).  When I clicked the stop button, it kept reading at a rate of 1 to 3 MB/s.  I then started a search for "test" (with "*.bb" files specified) and it launched a second `rg` process.  Neither process seemed like they were going to stop until I closed the VS code window.

**Comment by roblourens** [comment]
I see. Thought you were talking about file search. Could you try setting `"searchRipgrep.enable": true`, reload the window, and see if they are stopped properly when search is cancelled then?

**Comment by cpboyd** [comment]
The processes spawned from searching (with that flag enabled) seem to stop properly, but there is an rg process that seems permanently present (started when launching VS Code).

**Comment by roblourens** [comment]
I pushed a change into Insiders which fixes some related issues that have been reported... would appreciate if you try that tomorrow (without the above setting) and let me know whether it helps.

**Comment by cpboyd** [comment]
@roblourens My issue seems to be resolved as well with the current Insiders build.

**Comment by roblourens** [comment]
Excellent, thanks
