### ISSUE TITLE
Cursor and focus gone after toggling the side bar.

### ISSUE THREAD

**Issue by Jasper76** [Microsoft/vscode#6063]
- VSCode Version: 1.0.0
- OS Version: OSX 10.11.3

Steps to Reproduce:

1. Open a file and place the cursor somewhere.
2. Hide side bar (CMD-B). Cursor remains at position --> OK
3. Show side bar again. Cursor is gone and the focus is set on the Working Files panel of the side bar. --> Not OK

**Comment by bpasero** [comment]
@Jasper76 hard to argue, when you bring in the sidebar we move focus to it because your intent seems to be to work with the sidebar. I could equally argue why focus should stay in the editor?

**Comment by Jasper76** [comment]
@bpasero I understand. Personally I often hide the sidebar so I have more space for the code. Then I can toggle the sidebar to check for info like debugging info. I understand it's by design so feel free to close the issue.

**Comment by bpasero** [comment]
👍
