### ISSUE TITLE
Git: Prevent running git operations during sync

### ISSUE THREAD

**Issue by mehdhi** [microsoft/vscode#60630]
While syncing git commits in a branch let it be feature1, before sync completes in feature1 branch, if i switched to another branch (dev), the changes in feature1 gets automatically merged into dev. I thinks its pulling the origin/feature1 in to the dev after switching. This occured to me several times while git busy animation is on. Please fix this soon, I had to reset the HEAD of the branch each time. 

OS: Windows 10
VSCode: 1.28.0 (User Setup)

**Comment by iolpltuisciaoln** [comment]
still actual 
Version: 1.63.0
Commit: 7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e
Date: 2021-12-07T05:16:45.441Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.15.6-200.fc35.x86_64

**Comment by romg974** [comment]
Any updates on this ? I'm having this issue pretty often, I think because auto fetch is enabled.

**Comment by lszomoru** [comment]
This has been addressed as part of https://github.com/microsoft/vscode/issues/169293 and will be included in `1.75`.
