### ISSUE TITLE
Feature request: explorer view listing installed packages

### ISSUE THREAD

**Issue by patrys** [Microsoft/vscode#60635]
Unlike JavaScript, most other languages do not install libraries/packages/modules inside the project directory. It would be nice to allow language servers to register per-language library folders and have them displayed as treeviews either in a separate explorer pane or under the explorer.

**Comment by isidorn** [comment]
Search for file-explorer and feature-request label for similar feature-request to upvote them

**Comment by patrys** [comment]
@isidorn Mind if I ask which issue is the original report? I did search for this feature request before reporting as I hoped I'd just 👍 an already popular one.

**Comment by isidorn** [comment]
@patrys I do not know the actuall issue number due to the large number of issues but you can find it if you go through all the issues with the tag I mentioned in my previous comment

**Comment by patrys** [comment]
@isidorn I went through the entire list, there's only [39 matching issues](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afile-explorer+label%3Afeature-request). I am genuinely interested in upvoting the correct issue.

**Comment by isidorn** [comment]
@patrys got it. Though we would not tackle it that way, we try to keep vscode minimalstic and this feels to me like something each extensino should done seperatly
