### ISSUE TITLE
Open folder in a new window.

### ISSUE THREAD

**Issue by ColinTree** [microsoft/vscode#60637]
Hi there, can a option added into the right click menu that allow user to open the selected folder in a new vscode window?

**Comment by egamma** [comment]
Not clear what you mean by the right click menu. It is already possible to open a new window from the Recent menu when you CMD/CTRL click the entry. Please give it a try.

**Comment by ColinTree** [comment]
Oops, sorry I was talking about the right click menu inside vscode, like this:
![image](https://user-images.githubusercontent.com/22613139/46812802-137da000-cda8-11e8-9819-eacfc673f9ae.png)
Currently we just got:
* new file
* new folder
* open in explorer
* open in shell / cmd

And I recommend to add a new option that allow user to `open in new window`

**Comment by egamma** [comment]
Currently there is an extension that does this: https://marketplace.visualstudio.com/items?itemName=chrisdias.vscode-opennewinstance

**Comment by ColinTree** [comment]
Thanks for that.
