### ISSUE TITLE
Extensions and IntelliSense not working

### ISSUE THREAD

**Issue by GranFariduz** [Microsoft/vscode#60636]
Issue Type: <b>Bug</b>

Just after the latest upgrade, while I started up my React project there was a popup saying 'Extension host has become unresponsive'. After some time, there was another popup which read 'Extension host has become responsive' along with another popup informing me of the updating of one of my extensions. None of the extensions or IntelliSense seems to work for me. 

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.89GB (0.82GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
django-html|bib|1.2.0
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.60
dart-code|Dar|2.19.0
flutter|Dar|2.19.0
vscode-babel-coloring|dza|0.0.4
vscode-npm-script|eg2|0.3.5
vscode-great-icons|emm|2.1.44
vsc-material-theme|Equ|2.4.2
git-project-manager|fel|1.7.1
php-debug|fel|1.12.6
php-intellisense|fel|2.3.5
php-pack|fel|1.0.2
gc-excelviewer|Gra|2.1.26
py-paste-indent|hye|0.0.2
vscode-cdnjs|Jak|0.14.3
indent-rainbow|ode|7.2.4
material-icon-theme|PKi|3.6.0
heroku-command|pko|0.0.8
polacode|pnp|0.2.2
live-sass|rit|3.0.0
LiveServer|rit|5.1.1
sass-indented|rob|1.4.9
vscode-paste-and-indent|Rub|0.0.8
quokka-vscode|Wal|1.0.153
html-css-class-completion|Zig|1.17.1

(2 theme extensions excluded)

</details>

**Comment by egamma** [comment]
pls see #60318
