### ISSUE TITLE
Two jsdoc comment blocks in a row are merged into one

### ISSUE THREAD

**Issue by JobLeonard** [Microsoft/vscode#60638]
Version: 1.28.0
Commit: 431ef9da3cf88a7e164f9d33bf62695e07c6c2a9
Date: 2018-10-05T14:52:58.945Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
OS: Linux

Steps to Reproduce:
![image](https://user-images.githubusercontent.com/259840/46807208-af3beb80-cd69-11e8-928b-21e131636ec9.png)
```js
/**
 * Comment one
 */

/**
 * Comment two
 */

function foo () {}
```

Expected behaviour: nothing, since there is a space between the function and the doc comment. 

Actual behaviour: `"Comment one Comment two"`

PS: Perhaps the jsdoc spec actually actually allows for this and I am not aware of it, but I can't find proof of that if that is the case.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This has been marked as wont-fix upstream: https://github.com/Microsoft/TypeScript/issues/15106
