### ISSUE TITLE
Reduce movement in common editor actions

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#60649]
Example of switching from `.txt` file to `.md`:

![editor-icons](https://user-images.githubusercontent.com/9638156/46816330-6abe4900-cd85-11e8-96ec-8343ddbca8a5.gif)

**Comment by usernamehw** [comment]
So, you don't see the problem here?

**Comment by usernamehw** [comment]
@egamma, I mean since they have that icon in common it would be nice to rerender just 1 icon:

| Before  | After |
| ------------- | ------------- |
| ![editor-icons](https://user-images.githubusercontent.com/9638156/46816330-6abe4900-cd85-11e8-96ec-8343ddbca8a5.gif)  | ![ezgif com-video-to-gif](https://user-images.githubusercontent.com/9638156/46887186-a3355400-ce65-11e8-9251-94cf994afd9d.gif)  |

**Comment by egamma** [comment]
//CC @misolori

**Comment by misolori** [comment]
I think we can re-open and track. I agree that common controls/buttons should not move/jump where possible.

**Comment by usernamehw** [comment]
I don't think this issue is actionable.
