### ISSUE TITLE
Provide install number and update numbers separately

### ISSUE THREAD

**Issue by apupier** [Microsoft/vscode#60645]
On VS Code Marketplace the number of "installs" is in fact the number of installations + updates.
it would be nice to provide the numbers of installation and updates separately. The advantages will be to better compare popularity of plugins between each other (a plugin releasing twice more often will have an higher number currently even if there is the same number of users)
it will allow to have a better insight on how many people are still using the extensions.

**Comment by egamma** [comment]
I´ve forwarded this to the Marketplace team. I´m closing the issue since it is nothing the VS Code team can act on, but the issue can still be used to communicate between you and the market place team.

**Comment by viradhamMS** [comment]
Thanks Erich. We (marketplace) are working on this. Expect to get this enabled sooner.
