### ISSUE TITLE
Rename widget broken

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#6064]
Try to rename something, it seems like the rename keyboard input is ignored. Thus it is impossible to rename something.

I see this on os x

Assiging to @alexandrudima since I know you refactored the editor common which affects content widgets

**Comment by alexandrudima** [comment]
Sorry about that, there was an issue with the context menu service not calling `onHide` that was leading to editors to believe they were focused after a context menu was shown. The `Enter` was going to the wrong editor.
