### ISSUE TITLE
Is it possible to update README page screenshot?

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#60647]
It just looks n-years old, the image quality is not too great ... also the editor appearance now much better:
* File explorer(and tab) have icons
* File explorer decorations (ignored, modified, untracked..., errors, warnings)
* Custom title bar
* Better file explorer icons (add file, folder, refresh, collapse all)
* `Dark+` workbench and syntax colors changed
* Dimming of unused symbols
* Different scm icon (previous was git icon), vscode supports not only git
* Extensions can contribute views to activity bar

Probably more ... and that's just using the same code text and opened viewlet.

**Comment by puneet97** [comment]
Latest image from the [VS Code Home Page](https://code.visualstudio.com/):

![](https://user-images.githubusercontent.com/15259105/47539033-f1c60200-d8eb-11e8-8826-7e5d216ec23d.png)
How's this? 
If it is acceptable, I can open a pull request to update the screenshot.

**Comment by gregvanl** [comment]
@puneet97 That image is out of date as well :-) so that plan won't work.

**Comment by puneet97** [comment]
I think a GIF would be best and I've found a few online that fit but I'm hesitant to post all of them here so as to not result in inadvertent spam.
@gregvanl Do you have an updated image / should I post the alternatives I found?
