### ISSUE TITLE
Move last modified markdown list line up/down causes wrong modification indicator

### ISSUE THREAD

**Issue by MuseBoy** [microsoft/vscode#60644]
Issue Type: <b>Bug</b>

* Open a **git traced** markdown file
* Modify **markdown list** lines or add new markdown list lines. =>There are change indicators in these lines
* Place cursor on the **last** line in some continuous,**marked** as modified,markdown list lines (Which means that line may not be the real last modified markdown list line), then use `alt+uparrow/downarrow` to move the line up/down. =>the modification indicator of line x is gone. And this step is repeatable.
* Disableing all extensions does't fix the bug.

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:52:58.945Z)
OS version: Linux x64 4.15.0-36-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 1697)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|5.72GB (1.54GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
output-colorizer|IBM|0.1.2
gitignore|cod|0.5.0
bracket-pair-colorizer|Coe|1.0.60
transformer|dak|1.6.0
vscode-markdownlint|Dav|0.20.0
vscode-eslint|dba|1.6.0
xml|Dot|2.3.2
translation|dus|0.0.4
gitlens|eam|8.5.6
vscode-highlight|fab|1.2.10
gitlab-workflow|fat|1.2.0
code-runner|for|0.9.4
vscode-power-mode|hoo|2.2.0
latex-workshop|Jam|5.11.1
select-highlight-minimap|mde|0.0.8
markdown-shortcuts|mdi|0.8.1
metago|met|2.10.0
vscode-language-pack-zh-hans|MS-|1.28.2
python|ms-|2018.9.0
cpptools|ms-|0.19.0
java|red|0.32.0
partial-diff|ryu|1.4.0
code-settings-sync|Sha|3.1.2
vscode-leetcode|she|0.8.0
vscode-fileutils|sle|2.11.0
markdown-all-in-one|yzh|1.6.2

</details>

**Comment by joaomoreno** [comment]
I can't repro this, closing it.

**Comment by MuseBoy** [comment]
I can still reproduce this with latest vscode. Try this:
- create a new git repo
- create a new markdown file a.md, add a few new line and commit, the file a.md should be like
  ```md
  
  
  
  
  ```
- put `- 1` in 1st line, put `- 2` in 2nd line, u can see the blue lines to the left of these two lines, the file a.md should be like
  ```md
  - 1
  - 2
  
  
  ```
- use `alt + uparrow` to swrap these two lines, the file a.md should be like
  ```md
  - 2
  - 1
  
  
  ```
- but now these is a blue line to the left of only the 1st line, the 2nd line is not considered as modified.

**Comment by joaomoreno** [comment]
Oh yeah, I can definitely repro that, great steps thanks!
