### ISSUE TITLE
Enabling ripgrep causes file picker to generate paths with a leading dot breaking sidebar reveal

### ISSUE THREAD

**Issue by elprans** [Microsoft/vscode#60643]
- VSCode Version: 1.28.0
- OS Version: Gentoo Linux

Steps to Reproduce:

1. Press `Ctrl+P` to open the file picker, look for a file.
![file-picker](https://user-images.githubusercontent.com/347119/46812636-1e521980-cd43-11e8-96a5-357d5ae71a08.png)

2. Select a file.

3. File is opened with path containing a dot: `folder/./path/to/file`, and sidebar reveal does not work.
![breadcrumbs](https://user-images.githubusercontent.com/347119/46812650-2611be00-cd43-11e8-8f0d-184b3a7cb656.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@elprans how do you open that folder, is it a symlink or path containing a "."?

**Comment by elprans** [comment]
@bpasero It's a regular folder, and a part of a workspace:

```json
{
	"folders": [
		{
			"path": "/home/elvis/dev/magic/asyncpg"
		}
	]
}
```

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by elprans** [comment]
@bpasero I cannot reproduce on the insiders build. On 1.28.0 this seems to be caused by `    "searchRipgrep.enable": true`

**Comment by roblourens** [comment]
Can you check whether this still happens in Insiders? I think it should be fixed.

**Comment by elprans** [comment]
@roblourens Yes, it seems to be fixed in the latest insiders build.

**Comment by roblourens** [comment]
Great, thanks for checking.
