### ISSUE TITLE
The editor doesn´t work

### ISSUE THREAD

**Issue by intelcapo** [Microsoft/vscode#60654]
Hi everyone.

In this moment I try to open a file and when the editor try to open it sudenly 
report a problem and it's close.

This is cause whit this setup VSCodeUserSetup-x64-1.28.0.exe.

Thank you.

**Comment by egamma** [comment]
Based on this information we are not able to reproduce the issue, please provide detailed steps for how we can reproduce this problem, provide as many details about the platform, when this happened, the context you are in when this happens.

**Comment by intelcapo** [comment]
Hi Erick thanks for you response.

The issue is presenting when I try to open a file whatever, when the editor try to open a file shows a Dialog that says "VSCode doesn't work Do you want close the program?".

I don´t know if I need a new update of the aplication, I tried to download the lastest version published on the web site and install again, but the trouble persist.

The last update that VSCode Installed on my computer   was September 2018 (Version 1.28.1)

The configuration of mi computer desktop is:

SO: Windows 10 Pro 64 Bits.
Processor: Intel(R) CORE TM i5-6400 CPU @ 2.20 GHz
Memory RAM: 8GB.

Thak you for you attention.

**Comment by intelcapo** [comment]
This is the information that event viewer give me:

Depósito con errores 2026610655722909328, tipo 4
Nombre de evento: APPCRASH
Respuesta: No disponible
Identificador de archivo CAB: 1373054949871256182

Firma del problema:
P1: Code.exe
P2: 1.28.1.0
P3: 5b9797c2
P4: SHELL32.dll
P5: 10.0.14393.2068
P6: 5a7e6fba
P7: c000001d
P8: 00000000000677e7
P9: 
P10: 

Archivos adjuntos:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER36F5.tmp.WERInternalMetadata.xml
\\?\C:\Windows\Temp\WER42BD.tmp.csv
\\?\C:\Windows\Temp\WER42FC.tmp.txt
\\?\C:\Users\WforeroB\AppData\Local\Temp\WER431B.tmp.appcompat.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4AEC.tmp.dmp
\\?\C:\Users\WforeroB\AppData\Local\Temp\WER4FCF.tmp.WERDataCollectionFailure.txt

Es posible que estos archivos estén disponibles aquí:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Code.exe_3e948398528ad02947e031d587fb315dad18f861_e13b10ec_cab_1dc46c8c

Símbolo de análisis: 
Nueva búsqueda de una solución: 0
Identificador de informe: 2fc3871d-b315-4967-bd3d-6a0773e176a8
Estado del informe: 9
Depósito con algoritmo hash: 597db30e6b2155e07c1ff7a76862ae90

**Comment by intelcapo** [comment]
Windows no puede tener acceso al archivo  por alguna de las siguientes razones: Hay un problema con la conexión de red, con el disco donde se almacena este archivo o con los controladores de almacenamiento instalados en este equipo; o bien no se encuentra el disco. Windows cerró el programa Visual Studio Code por este error.

Programa: Visual Studio Code
Archivo: 

El valor del error se muestra en la sección Datos adicionales.
Acción del usuario
1. Abra el archivo de nuevo. Podría ser solo un problema temporal que se corrige al ejecutar el programa de nuevo.
2. Si todavía no se puede tener acceso al archivo y 
	- Está en la red, el administrador de red debe comprobar que no exista ningún problema con la red y que es posible ponerse en contacto con el servidor.
	- Está en un disco extraíble, como un disquete o un CD-ROM, compruebe que el disco esté insertado en el equipo.
3. Compruebe y repare el sistema de archivos ejecutando CHKDSK. Para ejecutar CHKDSK, haga clic en Inicio y después en Ejecutar; escriba CMD y después haga clic en Aceptar. En el símbolo del sistema, escriba CHKDSK /F y después presione Entrar.
4. Si el problema continúa, restaure el archivo a partir de una copia de seguridad.
5. Compruebe si se pueden abrir otros archivos en el mismo disco. Si no se pueden abrir, el disco podría estar dañado. Si se trata de un disco duro, póngase en contacto con el administrador o con el fabricante del hardware del equipo para obtener ayuda adicional.

Datos adicionales
Valor del error:00000000
Tipo de disco: 0

**Comment by egamma** [comment]
Translation

Windows can not access the file for any of the following reasons: There is a problem with the network connection, with the disk where this file is stored, or with the storage drivers installed on this computer; or the disc is not found. Windows closed the Visual Studio Code program for this error.

Program: Visual Studio Code
Archive:

The value of the error is shown in the Additional data section.
User action
1. Open the file again. It could be just a temporary problem that is fixed when you run the program again.
2. If the file can not yet be accessed and
- It is in the network, the network administrator must check that there is no problem with the network and that it is possible to contact the server.
- It is on a removable disk, such as a floppy disk or a CD-ROM, check that the disk is inserted in the computer.
3. Check and repair the file system by running CHKDSK. To run CHKDSK, click Start and then Run; type CMD and then click OK. At the command prompt, type CHKDSK / F and then press Enter.
4. If the problem continues, restore the file from a backup.
5. Check if other files can be opened on the same disk. If they can not be opened, the disk may be damaged. If it is a hard drive, contact the administrator or the computer hardware manufacturer for additional help.

Additional data
Value of the error: 00000000
Disk type: 0
