### ISSUE TITLE
addSelectionToNextFindMatch should infer match whole word

### ISSUE THREAD

**Issue by safield** [Microsoft/vscode#60650]
**EDIT: This has been addressed already in Insiders edition. Can be CLOSED**

This is basically a "please mirror a behaviour from Sublime" feature request. 

The behaviour is such that, the way in which I select a word, will determine whether match whole word is used in subsequent caret additions.

In Sublime:

If I **place the caret at the beginning of a word** (without the word selected) and hit ctrl+d, it will select the word, and all subsequent ctrl+d, will add carets at other instances of the whole word.

eg.

```
foo // ctrl+d hit here with caret at front of word
foobar // next ctrl+d skips here
foo // next ctrl+d caret added here
_foo // next ctrl+d skips here
foo // next ctrl+d caret added here
```

Alternatively, if I select the initial word by means other that "ctrl+d at the front", such as ctrl+shift+right or shift+right, or mouse selection, match whole word setting will not be implicitly inferred.

eg.

```
foo // select this by normal selection (not ctrl+d)
foobar // next ctrl+d addedhere on "foo"
foo // next ctrl+d added here on "foo"
_foo // next ctrl+d added here on "foo"
foo // next ctrl+d added here on "foo"
```

This implicit behaviour is quite beneficial. Multi-caret editing is at the heart of the proficiency of editors like Sublime, Atom, and VSCode, and should be as streamlined as possibly.

**Comment by egamma** [comment]
@safield since it has been addressed in the insiders version, is it OK to close the issue?

**Comment by safield** [comment]
Yes.
