### ISSUE TITLE
Variable substitution does not work on windows

### ISSUE THREAD

**Issue by jwmurray** [Microsoft/vscode#60652]
- VSCode Version: 1.28.0-insider
- OS Version: Windows 10

Steps to Reproduce:

Should this work the same on Windows?

I have the following task:

```
{
            "label": "test"
            ,"type": "shell"
            ,"options": {
                "env": {
                    "message": "hello"
                }
            }
            
            ,"windows": {
                
                "command": "echo $message"
            }
            ,"group": {
                "kind": "build",
                "isDefault": true
            }
            ,"presentation": {
                "panel": "new",
            }
}
```

and get the following output:

```
> Executing task: echo $message; echo ${message} <


Press any key to close the terminal.
```

Not sure why $message is not expanded to the environment variable that is being set.  I get the same result when the code tries to echo ${message}.

I have also tried this putting the options section inside the windows section, getting the same result.  I have tried this on OSX and it works fine.  I believe this should work on windows in the same way.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by dbaeumer** [comment]
Which shell are you using under Windows. The command `echo $message` works under OSX since $message is the shell way to access a variable. Under Windows this depens on the shell you are using (PowerShell versus cmd.exe).

**Comment by dbaeumer** [comment]
In PowerShell this should be `echo $env:message`

**Comment by jwmurray** [comment]
I am working in powershell.

That solved the problem!  Thank you!
