### ISSUE TITLE
Breadcrumbs dropdown picker is small

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#60665]
![image](https://user-images.githubusercontent.com/323878/46821905-ddf09c80-cd3e-11e8-91fa-d9828a4c35c1.png)

- Invoke breadcrumbs dropdown in a file with 3 classes e.g. SearchService.ts
- It is sized to show 3 classes
- Type to find some method. It stays uncomfortably small. By design or bug?

**Comment by jrieken** [comment]
it's kind of by design, the height adjusts with the number of elements and find box but I see how this case could benefit from some tweaking

**Comment by roblourens** [comment]
Once I search, there are many elements and it would be nicer to be able to browse them and see more than one at a time.

**Comment by jrieken** [comment]
The *new* breadcrumbs experience doesn't show the input box anymore making this obsolete.
