### ISSUE TITLE
runtime arguments are interpreted by "Electron Helper" as files

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#6066]
- VSCode Version: alpha

I tried to add a runtime argument '--debug-brk' when VS Code launches node-debug by setting the `runtimeArgs` attribute in package.json. This half-works: node seems to be launched in debug-brk mode and I can attach to it with VS Code. But then an exception occurs because node tries to execute the '--debug-brk' as a file:

![2016-05-03 17-09-24](https://cloud.githubusercontent.com/assets/1898161/14987933/eac372bc-1151-11e6-8c2b-7377597f79af.png)

Could it be that the '--debug-brk' option is passed twice or in the wrong position? IIRC you are using Alex's script to reroute stdin/stdout through some named pipe. Could that be the problem?

**Comment by isidorn** [comment]
@weinand I would close this as will not fix unless you are getting hit by this?
