### ISSUE TITLE
New `window.openFilesInNewWindow` option: `onlyIfOutsideOpenFolders`

### ISSUE THREAD

**Issue by drujd** [microsoft/vscode#60663]
I am submitting this as a feature request, but I could have sworn that older versions of Code behaved the way I want.

None of the current options for "Open Files In New Window" setting seems to do what I want and what I would consider a reasonable default:

If I open a file in Code, it should reuse a window *if and only if* the file's folder (or its parent) is opened in an existing window (and it should be opened in *that* window, obviously). If the folder is not opened, new window should be created. Could this be added as a new option? Or possibly the 'default' option could be altered to behave this way: I cannot imagine many cases where you would **not** want the file to open in the window which has the folder opened. Currently 'default'/'on' unfortunately always open a new window.

I can also imagine a 'prefer-reuse' variant, which will reuse (besides corresponding folder windows) also a "folderless" window, if such a window exists, and create a new window *if and only if* all open windows have folders (not containing the file) opened.

This functionality would really help in using Code as both an universal text editor AND an IDE at the same time.

**Comment by drujd** [comment]
Yup, I could have sworn that this is how Code behaved in the past.

**Comment by drujd** [comment]
Windows 10 x64

With "window.openFilesInNewWindow": "on" or "default" (which is **NOT** the default):
I have dir "C:\a\" opened in a vscode window and call 'Code.exe C:\a\file' - file is opened in a new window.

With "window.openFilesInNewWindow": "off" (which is the default):
I have opened dir "C:\a\" in a vscode window and also an 'others'/"purple status bar" window with various files outside the folder. *However*, the "C:\a\" window has been used more recently. When I "call 'Code.exe C:\c\file' - file is opened in the "C:\a\b" window.

So neither of the options does what I want (and what I feel is the most reasonable "default" behaviour).

Again, I *think* Code behaved differently before, but I am not 100% sure. Having the possibility to confine opened folders' files to one window (which is what only the "off" value currently does) while opening other files in a different window (either a single universal 'others'/"purple status bar" one or always a new one) would really help in using Code as both an IDE and a universal text editor.

**Comment by bpasero** [comment]
> With "window.openFilesInNewWindow": "on" or "default" (which is NOT the default):
I have dir "C:\a" opened in a vscode window and call 'Code.exe C:\a\file' - file is opened in a new window.

That works as expected and as described by the settings description.

> With "window.openFilesInNewWindow": "off" (which is the default):
I have opened dir "C:\a" in a vscode window and also an 'others'/"purple status bar" window with various files outside the folder. However, the "C:\a" window has been used more recently. When I "call 'Code.exe C:\c\file' - file is opened in the "C:\a\b" window.

I cannot reproduce that.

> Again, I think Code behaved differently before

Hard to say without being able to reproduce.

**Comment by drujd** [comment]
**Every** option works as described by the settings description, that is why I have submitted this as a feature request. Definitely not as expected, though, none of the current options makes sense for a user using Code as a text editor (opening files from a file manager) and an IDE at the same time.

As for the "off" option, how can you not reproduce that? That also works as described by the description. Windows, default VS code user dir installation, no changed settings:

- run 'code whatever_folder' (opens a window with the folder opened)
- run 'code' (opens a window without a folder opened)
- click on the window with whatever_folder opened (marking it as the least recently used)
- run 'code any_file_outside_whatever_folder'

The file opens in the window with the folder opened.

**Comment by drujd** [comment]
Maybe the most intuitive way to implement this would be a new option, e.g. **window.isolateOpenedFolderWindows**:

If "on", then regardless of "window.openFilesInNewWindow":"off" or --reuse-window, windows with folder(s) opened are *never* used to open files outside the window's folder(s). With "window.openFilesInNewWindow":"off" or --reuse-window, a single "universal"/"no folder" window may be created if it is not open already.

**Comment by jsmith-sapient** [comment]
It's happening on macOS High Sierra (10.13.6) too with VS Code 1.28.1

**Comment by gjsjohnmurray** [comment]
Followers of this may like to upvote #149775 to try and get it the 20 it needs to progress beyond Backlog Candidate.
