### ISSUE TITLE
Debug: always use scheme when creating uris

### ISSUE THREAD

**Issue by rodrigovaras** [Microsoft/vscode#60667]
Steps to Reproduce:

1. Register a provider debug tracker using something like:
```
vscode.debug.registerDebugConfigurationProvider('*', this);
public provideDebugAdapterTracker(session: vscode.DebugSession, folder: vscode.WorkspaceFolder | undefined, debugConfig: vscode.DebugConfiguration, token?: vscode.CancellationToken): vscode.IDebugAdapterTracker {
        return new MyTracker();
    }
class  MyTracker implements vscode.IDebugAdapterTracker {
    public toDebugAdapter(message: any): void {

    }
}
```

2. Run latest insider 
3. Debug a node app
4. Press restart

Result: restart never completed

**Comment by isidorn** [comment]
@rodrigovaras thanks for creating an issue. 
I followed your steps and I can not reproduce this with the latest vscode insiders.

Let me know if you are doing something differently than me. If yes then please create a GitHub repository with the extension for which you can reproduce this
![adaptertracker](https://user-images.githubusercontent.com/1926584/46864371-7c056500-ce1a-11e8-933e-b945e8b376f3.gif)

**Comment by rodrigovaras** [comment]
You are right the latest insiders did fix the issue, but i found another related to IDebugAdapterTracker interface. Same steps as before (register a mock implementation with 'fromDebugAdapter' method. 
1 )Have a node app with a line like this 'console.log('foo').
2) Step into
vscode display this:
[UriError]: Scheme is missing: {scheme: "", authority: "", path: "<node_internals>/bootstrap_node.js", query: "", fragment: ""}
![image](https://user-images.githubusercontent.com/4292977/46877240-3d10e880-cdf5-11e8-9197-da0387e1e13b.png)
