### ISSUE TITLE
VSCode doesn't find app.ts if it isn't in project root

### ISSUE THREAD

**Issue by mathewmeconry** [Microsoft/vscode#6067]
**TypeScript Version:** 

1.8.10

**VSCode Version:**
1.0.0

**OS**
Linux 4.4.8-300.fc23.x86_64
Fedora 23
Gnome 3.18.2

**Project structure**

├── dist
│   ├── app.js
│   ├── app.js.map
│   ├── other code
├── node_modules
├── npm-shrinkwrap.json
├── package.json
├── readme.md
├── src
│   ├── app.ts
│   ├── other code
├── tsconfig.json
├── tsd.json
├── tslint.json
└── typings
    ├── main.d.ts

**tsconfig.json**
```json
{
  "compilerOptions": {
    "noImplicitAny": false,
    "removeComments": true,
    "preserveConstEnums": true,
    "sourceMap": true,
    "sourceRoot": "./src",
    "module": "commonjs",
    "target": "es5",
    "outDir": "dist"
  },
  "filesGlob": [
    "src/**/*.ts",
    "src/app.ts"
  ],
  "exclude": [
    "node_modules",
    "dist",
    "doc",
    "Gruntfile.js"
  ]
}
```

**Expected behavior:**
vscode should look for the app.ts in the sourceRoot
And "activate" intelisense
 
**Actual behavior:** 
vscode doesn't find the app.ts and because of this intelisense doesn't work

**Edit**
added the intelisense part to the behavior describtion

**Comment by joaomoreno** [comment]
I assume you are talking about debugging?

**Comment by mathewmeconry** [comment]
Sorry I forgot the important part :)
I'm talking about Intelisense. This isn't working with this configuration. I've always to open the src folder to get Intelisense working

**Comment by joaomoreno** [comment]
So... what do you mean by *vscode doesn't find the app.ts*? Where exactly, in Code, do you expected to see `app.ts` and does not appear?

**Comment by mathewmeconry** [comment]
If I understand the editor correct. It search the app.ts file to get all the reference paths that intelisense and typings works.

**Comment by joaomoreno** [comment]
So... it's when you do Reference Search? Or when you use Intellisense in some other module? Are your sources open, so we could clone them?

**Comment by mathewmeconry** [comment]
"find all references" and code completion in all modules even in app.ts doesn't work.

No sorry

**Comment by dbaeumer** [comment]
@mathewmeconry are you able to share your project. Looking at you folder layout it should work. 

Please be aware that VSCode has no support for filesGlob in tsconfig.json. However in your setup VS Code considers all ts files below the directory containing the tsconfig.json file as part of the project.

**Comment by mathewmeconry** [comment]
@dbaeumer I shared already a part of the project tree at the issue description. Is this enough or do you need more? Unfortunately the code is not opensource.

The strange thing is, that it worked with VSCode before version 1 with this configuration. Do I need to change something with the update to version 1?
I didn't found anything in the release description

**Comment by dbaeumer** [comment]
@mathewmeconry as said from looking at the description of the issue I think things should work. However it looks like the don't. What exactly do you mean by
>I've always to open the src folder to get Intelisense working

Since you can't share out project could you please do the following:

- open workspace preferences
- add the following setting
```
 "typescript.tsserver.trace": "messages"
```
- open the output window and switch to the typescript channel
- do what causes the problem to appear
- attach the trace to this issue

**Comment by mathewmeconry** [comment]
@dbaeumer As you see in the folder tree we've a folder called "src" where all the source files are located. The compiled .js files are located after compiling in "dist" folder.

Project root
├── dist
├── src
│   ├── .ts source files



So the problem is now the following:
When I open the project root in VSCode I'm not able to use function like "Find all References" and code completion.
![notworking](https://cloud.githubusercontent.com/assets/4057473/15150687/8bee7f2a-16ce-11e6-8098-b98c8a2c67ba.png)

But when I open the src folder as root for VSCode all those function are working as expected
![working](https://cloud.githubusercontent.com/assets/4057473/15150683/8857a72e-16ce-11e6-8f6d-12e099bfda19.png)


Additionally you see that I don't have the channel typescript... I added the setting you wished to my workspace preferences.

**Comment by dbaeumer** [comment]
@mathewmeconry thanks for the additional info. However I have no idea right now what causes this behavior since your tsconfig.json is correctly located in root.

Could you please enable the tracing I suggested in https://github.com/Microsoft/vscode/issues/6067#issuecomment-218152606 and attach the trace. This would help me to understand why the TS language server doesn't provide results.

**Comment by mathewmeconry** [comment]
@dbaeumer I enabled it but as you can see I can't select the typescript channel in the output console. Am I at the right place?

This is my settings.json in the .vscode folder in the root of the project (path: /)

```json
{
    "editor.formatOnType": true,
    
    "files.exclude": {
        "dist/**": true,
        ".idea/**" : true,
        "**/.git": true,
        "**/.DS_Store": true
    },
    
    "typescript.useCodeSnippetsOnMethodSuggest": false,
     "typescript.tsserver.trace": "messages",
    "tslint.enable": true,
    "tslint.configFile": "tslint.json"
}
```

**Comment by mathewmeconry** [comment]
@dbaeumer After updateing vscode to the latest version in the mosquito Fedora repo, it does work.
Here the dnf entry of vscode.
```
Available Packages
Name        : vscode
Arch        : x86_64
Epoch       : 0
Version     : 1.1.0
Release     : 1.fc23
Size        : 4.0 M
Repo        : mosquito-vscode
Summary     : Visual Studio Code - An open source code editor
URL         : https://github.com/Microsoft/vscode
License     : MIT
Description :  VS Code is a new type of tool that combines the simplicity of a code editor
            :  with what developers need for their core edit-build-debug cycle. Code provides
            :  comprehensive editing and debugging support, an extensibility model, and
            :  lightweight integration with existing tools.

```

The bug seems to be fixed now with version 1.1.0 of VSCode.

Thanks for your support :)

**Comment by dbaeumer** [comment]
@mathewmeconry great to hear that 1.1.0 resolved the issue. You didn't see any trace since that feature got added for 1.1.0 :-).

**Comment by mathewmeconry** [comment]
@dbaeumer I found the issue which mentioned a nearly same behaivior: [VSCode 5521](https://github.com/Microsoft/vscode/issues/5521)
