### ISSUE TITLE
Cannot show .js outline after opening long simple .js file

### ISSUE THREAD

**Issue by capobandaf** [Microsoft/vscode#60677]
Issue Type: <b>Performance Issue</b>

Open VS Code. Open workspace "lib-translit". If there are any open files, close all the files and restart Code.

Open file TranslitTable.js. Show outline pane and wait for symbols to show.
Open file dict_en.js. Wait for symbol (there is only one) to show. (This is
an encoded CMUDICT-based dictionary, about 10000 lines long)
Open file Translitor.js. 

Notice: the processor usage is high. Usually, after few minutes it shows "No symbols found in document 'Translitor.js'". It seems to be a bit random. Only once it happened to me that the symbols were shown, but the symbols for the next .js file were not shown, see next paragraph.

If it shows the symbols, open the file DomAnnotator.js or yet another .js file. This last file doesn't show any symbols.

Note: If dict_en.js is not opened, the symbols for all the files are shown quickly.

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (4.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    68	  8168	code main
    0	    47	  1656	   shared-process
    0	   119	  7836	   gpu-process
    0	    67	  8236	   window (Issue Reporter)
    0	    88	 11804	   window (Translitor.js - lib-translit (Workspace) - Visual Studio Code)
    0	    20	  3960	     watcherService
    0	    61	  8716	     extensionHost
   27	   653	 10436	       electron_node tsserver.js 
    0	    58	  2028	         electron_node typingsInstaller.js typesMap.js 
    0	    11	  9340	     electron-crash-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Translitor.js - lib-translit (Workspace) - Visual Studio Code)
|    Folder (translit): 7 files
|      File types: js(6) css(1)
|      Conf files:;
```

</details>
Extensions: none

**Comment by capobandaf** [comment]
[60677-outline-afler-long.zip](https://github.com/Microsoft/vscode/files/2470505/60677-outline-afler-long.zip)

**Comment by juozhe** [comment]
Ups, I reported the problem while my son was logged in into github.

**Comment by juozhe** [comment]
![1-after-opening-long-file](https://user-images.githubusercontent.com/4638123/46831862-de238300-cda4-11e8-8fb5-626ce78bb9dc.PNG)
![2-after-opening-third-file](https://user-images.githubusercontent.com/4638123/46831875-e2e83700-cda4-11e8-95c1-f46277b5c41f.PNG)

**Comment by mjbvz** [comment]
Thanks for the example code. I've opened https://github.com/Microsoft/TypeScript/issues/27960 to track the root cause of this issue upstream
