### ISSUE TITLE
 Unused blank space on top of terminal while having only 1 terminal panel

### ISSUE THREAD

**Issue by juanhuerta** [Microsoft/vscode#60675]
- VSCode Version: 1.28
- OS Version: Mac osx 10.14 Mojave

Steps to Reproduce:

1. Open integrated terminal
2. Unused blank space on top of terminal while having only 1 terminal panel

Does this issue occur when all extensions are disabled?: Yes

An unused space appears on top of the integrated terminal window, and I can't resize or avoid it, but when I split the terminal in two terminals the space disappears. It appears no matter if I'm using vertical pane or horizontal terminal pane.

![image](https://user-images.githubusercontent.com/7265780/46829143-9bd95200-cd62-11e8-83e9-2de1cabd9e23.png)

![image](https://user-images.githubusercontent.com/7265780/46829351-2752e300-cd63-11e8-8f52-d528205eb2f1.png)

**Comment by Tyriar** [comment]
I can't seem to repro this, does it happen consistently? Also does it happen when you switch to bash?

```
"terminal.integrated.shell.osx": "/bin/bash:
```
