### ISSUE TITLE
September Recover 1.28.1 Endgame 

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#60671]
- [x] Bump up the version in package.json @kieferrm
- [x] Build stable for all platforms for https://github.com/Microsoft/vscode/commit/3368db6750222d319c851f6d90eb619d886e08f5 @kieferrm
- [x] Verify all issues #60444 #59328 #60318 #59876 **team**
- [x] Smoke Test
   - [x] Windows
   - [x] Mac @kieferrm 
   - [x] Linux
- [x] Make rpm signing request @Tyriar 
- [x] Sanity check of installable bits
  - [x] Windows 64
    - [x] signed installer
    - [x] user installer
    - [x] zip
  - [x] Windows 32
    - [x] signed installer
    - [x] user installer
    - [x] zip
  - [x] OS X @kieferrm 
  - [x] Linux
    - [x] deb package 64-bit
    - [x] deb package 32-bit
    - [x] rpm package 64-bit
    - [x] rpm package 32-bit
    - [x] archive 64-bit
    - [x] archive 32-bit
- [x] Update release notes with milestone link and DownloadVersion @gregvanl
- [x] Add a git tag to `HEAD` of `release/<x.y>` in format `x.y.z` @mjbvz
- [x] Publish website @gregvanl
- [x] Publish to stable @mjbvz
- [ ] Publish deb and rpms to repositories manually @Tyriar

**Comment by mjbvz** [comment]
1.28.1 shipped

**Comment by tomburgin** [comment]
Not that it affects me but the last item on the list isn't ticked, just checking it's been done

**Comment by avsanin8** [comment]
bow to the gods of IntelliSense
