### ISSUE TITLE
Not Working on Windows 10

### ISSUE THREAD

**Issue by Peter57** [Microsoft/vscode#60681]
- Extension Name: debug-auto-launch
- Extension Version: 1.0.0
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:

```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 10,
		"activateCallTime": 6,
		"activateResolvedTime": 0,
		"activationEvent": "*"
	}
}
```

**Comment by isidorn** [comment]
Fixed in latest, we no longer show this notification
