### ISSUE TITLE
outputChannel.show changes the terminal, but not the tab.

### ISSUE THREAD

**Issue by rosanch** [Microsoft/vscode#60689]
When I use 
ext.outputChannel.append("something");
ext.outputChannel.show();

the terminal shows the output log, but it never changes to that output channel on the tab.  For example:
If I'm in the git output channel, and output something to the docker channel and show. It will show my output but the tab will still say that I'm in the git output channel, even tho I'm seeing something from the docker channel.

**Comment by sandy081** [comment]
![kapture 2018-10-16 at 11 00 08](https://user-images.githubusercontent.com/10746682/47004862-c0527700-d132-11e8-8b71-4aff1d782efa.gif)


@rosanch It works for me. Is it possible to provide a sample of your test case?

**Comment by rosanch** [comment]
Sorry I don’t know what happened. It’s now working for me as well. Maybe there was something messed up with my environment at that moment.

Thanks,
Rodrigo Mendoza
