### ISSUE TITLE
Not Woprking on windows 10

### ISSUE THREAD

**Issue by Peter57** [Microsoft/vscode#60683]
- Extension Name: git
- Extension Version: 1.0.0
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:
```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 164,
		"activateCallTime": 13,
		"activateResolvedTime": 2749,
		"activationEvent": "*"
	}
}
```

**Comment by egamma** [comment]
Please see #60318
