### ISSUE TITLE
Rename command available not available in the Open Editors view

### ISSUE THREAD

**Issue by RokuKent** [Microsoft/vscode#60690]
Issue Type: <b>Bug</b>

I think I was sure it was there, but it's no longer there, control click on files in the browser view.

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:07:48.477Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
go-outliner|766|0.1.20
vscode-languagetool|ada|3.8.0
vscode-languagetool-en|ada|3.8.0
code-gnu-global|aus|0.2.2
vscode-django|bat|0.17.0
django-html|bib|1.2.0
brightscript|cel|1.2.1
bracket-pair-colorizer|Coe|1.0.60
dart-code|Dar|2.19.0
flutter|Dar|2.19.0
vscode-markdownlint|Dav|0.20.0
docs-markdown|doc|0.1.5
jupyter|don|1.1.4
python-extension-pack|don|1.4.0
xml|Dot|2.3.2
gitlens|eam|8.5.6
vs-code-xml-format|fab|0.1.5
code-runner|for|0.9.4
gc-excelviewer|Gra|2.1.26
MagicPython|mag|1.1.0
rainbow-csv|mec|0.6.0
vscode-clang|mit|0.2.2
roku-deploy-vscode|mjm|0.0.4
python|ms-|2018.9.0
cpptools|ms-|0.19.0
Go|ms-|0.6.91
vsliveshare|ms-|0.3.790
go-doc|msy|0.1.1
quicktype|qui|12.0.46
code-spell-checker|str|1.6.10
python|tht|0.2.3
vscodeintellicode|Vis|1.0.4
jinja|who|0.0.8
vscode-ide-brightscript|wil|1.3.5

</details>

**Comment by RokuKent** [comment]
![screen shot 2018-10-11 at 3 00 20 pm](https://user-images.githubusercontent.com/38437554/46836470-69c9ef00-cd66-11e8-8a90-1edfed7ee7f5.jpg)

**Comment by RokuKent** [comment]
Oh, now I see, rename is not in the group section, only in the flle browser section, this is a subtle UI issue, one would think that you could rename files in the group section as you can save and revert. Is it possible to make rename also part of the group file options (Open Editors)? It would be easier than to chase down the file in the browser.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/52713
