### ISSUE TITLE
Outline padding

### ISSUE THREAD

**Issue by pixieaka** [Microsoft/vscode#60694]
Issue Type: <b>Bug</b>

![capture](https://user-images.githubusercontent.com/17777237/46836621-90157c00-cdb2-11e8-93e6-fc4817969112.gif)

VS Code version: Code - Exploration 1.29.0-exploration (d27719015aae32e9cec06eaac23d7a9c2272ca46, 2018-10-11T08:30:13.517Z)
OS version: Windows_NT x64 10.0.17763

**Comment by jrieken** [comment]
Hm, I cannot reproduce. Please try with latest insiders and report back

**Comment by pixieaka** [comment]
Same problem @jrieken at resolution 1366 * 768 when i resize the outline panel the problem gone but when i restart vscode the problem return and i have to resize the panel again.

**Comment by jrieken** [comment]
True, it's the very first layout that's causes problems. Thanks for clarifying.
