### ISSUE TITLE
Unable to read long message in debug console.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#6069]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows10

Steps to Reproduce:
1. Launch app and open folder which contains Aspnet console app.
2. Configure for debugging.
3. Start debugging  and verify debug console window.
Actual: Long message is truncated and user unable to read complete message from debug console.
Expected: Message should not be truncated and wrap properly. or Mouse hove should show message contents.

The program 'c:\src\TestCSharpProj\TestCSharpWithVSCode/bin/Debug/dnx451/win7-x64/TestCSharpWithVSCode.exe' has exited with code -1 (0xffffffff).

![image](https://cloud.githubusercontent.com/assets/17735796/14988198/b72f099c-1107-11e6-94a6-0da5d8887268.png)

**Comment by isidorn** [comment]
Dup of #6044
