### ISSUE TITLE
"The JSON Language Server crashed 5 times in the last 3 minutes"

### ISSUE THREAD

**Issue by RonaldAi** [Microsoft/vscode#60705]
- Extension Name: json-language-features
- Extension Version: 1.0.0
- OS Version: Windows_NT x64 10.0.18258
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:
```json 
{
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 164,
		"activateCallTime": 25,
		"activateResolvedTime": 0,
		"activationEvent": "onLanguage:jsonc"
	}
}
```

**Comment by egamma** [comment]
Pls see #60318
