### ISSUE TITLE
System internal message should not be displayed on debug console.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#6070]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows10
-Project Type: Aspnet console app

I observer when I am terminating debug session by clicking on stop button from debug-actions-widget then debug console is displaying some system internal message which is irrelevant to the user.

![errormsgdebugconsole](https://cloud.githubusercontent.com/assets/17735796/14989604/80226cc2-110d-11e6-9538-d02235203cdc.gif)

**Comment by weinand** [comment]
@v-pavanp This is a problem of the C# extension. Please file bug against them.
