### ISSUE TITLE
JSON snippets are not offered until new line entered

### ISSUE THREAD

**Issue by joechung-msft** [microsoft/vscode#60704]
- VSCode Version: 1.28.1 and later
- OS Version: Windows

Steps to Reproduce:

1. Create a JSON snippet.
2. Try to use the JSON snippet on a JSON object literal without entering a new line.

![image](https://user-images.githubusercontent.com/26208574/46840473-0b0d7100-cd78-11e8-93fd-f0eef9897b5e.png)

Note that if you press Enter to split the JSON object into multiple lines, VSCode will present the snippet as an option:

![image](https://user-images.githubusercontent.com/26208574/46840485-18c2f680-cd78-11e8-9494-7587a518d371.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
> Create a JSON snippet.

what is the file name you are using?

**Comment by joechung-msft** [comment]
`json.json` for the snippet file (default name suggested by Code).  The file being edited is `Untitled-1.json`.

In the Visual Studio extension, the snippet filename is `logicapps.snippets.json`.

**Comment by jrieken** [comment]
> The file being edited is Untitled-1.json.
 
That's not a file name we support, it must be the name of a language, like `ison.json` or `javascript.json`. For global snippets, use `SomeName.code-snippets`

**Comment by joechung-msft** [comment]
Why was this closed?

You misunderstood:  the JSON file I was editing was called "Untitled-1.json," not that it actually matters.  I also reproduced the issue in a file called `ison.json` and `javascript.json`.

The snippet filename was called `json.json`.

**Comment by josephwallertheceo** [comment]
I am the master and I'm not bound by any of you so you better get me paid now

**Comment by josephwallertheceo** [comment]
Because if I'm not you all will be not bound by any computer company that I pen or have a controlling interest in think that leaves one

**Comment by josephwallertheceo** [comment]
And this is to be packet money I need a jet, personal aid, C.C. passport, diplomat papers, medical pass for the cannabis that I carry

**Comment by josephwallertheceo** [comment]
The new line was release two minutes ago

**Comment by josephwallertheceo** [comment]
Thanks everyone that hasn't stuck in my back this and for the ones that have try harder

**Comment by jrieken** [comment]
>Create a JSON snippet.

What does this mean? Please update your steps. To create a new snippet go via "F1 > Configure Snippets"

**Comment by joechung-msft** [comment]
1. Preferences: Configure User Snippets
2. Select json.
3. Uncomment the example snippet (lines 7-14).
4. Save the snippet.
5. Open a JSON file (any filename).
6. Type `{}`
7. Move the cursor between the braces.
8. Press Ctrl-Space:  only "$schema" is listed as a suggestion.
9. Press Enter.
10. Press Ctrl-Space:  "$schema" and the "log" snippet are listed as suggestions.

Expected
The "log" snippet should have been listed in step 8.

**Comment by jrieken** [comment]
Really - That is your issue? How would I know those 10 steps from just the 2 [steps above](
https://github.com/Microsoft/vscode/issues/60704#issue-369351554)? I am under impression that you to create a new snippet file and don't get help on authoring a snippet. Sorry, but I am not clairvoyant.

**Comment by jrieken** [comment]
Snippet completion has the challenge that it doesn't know where snippets should be inserted. It's not like C# or TypeScript where `.` or word-starts are good anchors from which to compute snippets. The challenge is to find a balance between proposing snippets and not being overly noisy, e.g. not always propose snippets. 

Our logic walks the current line prefix to find reasonable anchors and returns snippets that match/overlap with that anchor. Only when no anchor is found all snippets are shown. I can see if that logic can be tweaked but there is potential for snippet spam

**Comment by joechung-msft** [comment]
Check your attitude.

**Comment by joechung-msft** [comment]
Any news on this?  Also, can you reopen this since it is not resolved?  Thanks.
