### ISSUE TITLE
File Icons aren't associating properly in explorer

### ISSUE THREAD

**Issue by RyannnnnnR** [Microsoft/vscode#60716]
Issue Type: <b>Bug</b>

Im pretty sure the application updated from inside VS Code and this caused all the files to have the default association icon.

I then downloaded the latest version of VS Code from the site, reinstalled and caused most files to associate expect for my php files.

I installed the latest insider version and couldn't seem to recreate this bug - however, with this being said, the insider version I installed was completely clean meaning there were no pre-existing settings installed on my PC for the insiders version of VS Code - something which isn't the case for the stable build as I update whenever prompted.

It seems as if my php files are associated to a different version of VS Code?

![bug](https://user-images.githubusercontent.com/26314009/46844075-38fac000-ce21-11e8-9f2f-ba12e704a8e3.gif)

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600 Six-Core Processor             (12 x 3194)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.95GB (4.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.60
EditorConfig|Edi|0.12.4
prettier-vscode|esb|1.6.1
php-intellisense|fel|2.3.5
dotenv|mik|1.0.1
python|ms-|2018.9.0
csharp|ms-|1.16.2
debugger-for-chrome|msj|4.10.2
laravel5-snippets|one|1.5.0

(2 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
@RyannnnnnR it seems that for some file types the icon shows up and for others it does not?

**Comment by RyannnnnnR** [comment]
@bpasero  That's correct and from what I can see it only appears to be with my php files.

**Comment by bpasero** [comment]
i do not think this is a vscode issue, but windows issue. i suggest you file a bug against windoofs.

**Comment by misolori** [comment]
@RyannnnnnR you may have multiple versions of vs code installed, the newer versions include the black background when you navigate to the "Open with..." submenu:
![image](https://user-images.githubusercontent.com/35271042/46877840-a34a3b00-cdf6-11e8-8918-b4839163448a.png)

I'd double check that you don't have multiple versions, and if not then try re-installing vs code and see if that helps. I've found that a fresh install fixes the issue on windows for me.

**Comment by RyannnnnnR** [comment]
@misolori 

I specified the path to the Code executable and furthermore, all other file associations got associated no problems.

I ended up fixing it by deleting all registry associations for php files and then reinstalled VS Code to rebuild the keys.

So I think it was a Windows bug like @bpasero  suggested

🤷‍♂️
