### ISSUE TITLE
CTRL + R is broken recently

### ISSUE THREAD

**Issue by dbroytman** [Microsoft/vscode#60711]
Issue Type: Bug

Previously, pressing "ctrl + r" opened the recent folders/workspaces popup. Since my latest update, I see "(Ctrl + R) was pressed. Waiting for second key of chord..."

Also, I see that the shortcut is still registered in to "Open Recent" in shortcuts.

VS Code version: Code - Insiders 1.29.0-insider (f151c46b1783cf4f9a4ca934a85f78846f08688e, 2018-10-11T05:19:51.895Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1505M v6 @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.86GB (21.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.6.0
gitlens|eam|8.5.6
vscode-npm-script|eg2|0.3.5
minify|Hoo|0.3.0
debugger-for-chrome|msj|4.10.2
java|red|0.32.0
partial-diff|ryu|1.4.0
addDocComments|ste|0.0.8
vscode-java-debug|vsc|0.14.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.10.0
vscode-maven|vsc|0.11.0

</details>

**Comment by egamma** [comment]
You must have recently installed the `vscode-npm-script` extension. It adds some chording short cuts that start with `CTRL-R`. This is the a terrible mistake by the extension author (me... but it was the first extension I wrote). The fix is to remove the keybindings added by `vscode-npm-script` or uninstall the extension.
