### ISSUE TITLE
Sell extension on VS Marketplace

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#6071]
I'm not sure this is the best place for the question, but I'm wondering who I could talk to about selling an extension on the VS Marketplace for VS Code. Is this possible? Contacts / pointers would be helpful, thanks!

**Comment by joaomoreno** [comment]
Unfortunately this is not supported as all Code extensions are meant to be free. You can always implement that functionality within the extension itself although you'd be handling all the payments and distribution yourself.

cc @chrisdias
