### ISSUE TITLE
Integrated terminal git bash character error.

### ISSUE THREAD

**Issue by AnuyMik** [Microsoft/vscode#60710]
- VSCode Version: 1.28.1
- OS Version: Windows 10 (10.0.17134)

Korean font is broken in the integrated terminal (git bash).

VSCode version 1.27.2 hasn't the problem.

Show below image. left 1.28.1, right 1.27.2
![vscode_terminal](https://user-images.githubusercontent.com/10217225/46842282-c7fade80-ce07-11e8-9c9b-5d7870f4a428.PNG)

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/60717
