### ISSUE TITLE
Extensions pack tab does not show extention dependencies

### ISSUE THREAD

**Issue by paulvi** [Microsoft/vscode#60718]
Extensions pack tab does not show extention's subdependencies (but in Dependencies )

- VSCode Version: 1.28.1
- OS Version: Windows

Steps to Reproduce:

1. Search for "Java IDE Pack" on marketplace
2. On Extensions pack tab "Debugger for Java" should have shown dependency

![image](https://user-images.githubusercontent.com/1614482/46845226-18c10600-ce0d-11e8-8f65-763b875a7804.png)

subdependency are seen for extention 

![image](https://user-images.githubusercontent.com/1614482/46845176-e6170d80-ce0c-11e8-83bf-4da8f106ebcf.png)

ref https://github.com/Microsoft/vscode/issues/59548

**Comment by sandy081** [comment]
Since this is an extension pack tab it shows only extension packs tree not dependencies tree.

**Comment by sandy081** [comment]
Wont it be confusing if the extension pack tree also has deps has children? How does the user know if an entry is a dependency or extension pack element?

**Comment by paulvi** [comment]
Impossible to continue this thread as now https://github.com/Microsoft/vscode/issues/61430

**Comment by paulvi** [comment]
OK, #61430 was only for one extension.

This is feature request that in the tab dependencies should be in form of tree to show subdependency.

Should I create new issues to show it as feature request?

**Comment by sandy081** [comment]
> in the tab dependencies should be in form of tree to show subdependency.

Dependencies tab already shows sub dependencies. Am I missing something here?

**Comment by paulvi** [comment]
for extension dependencies,  
but not for extension pack dependencies.

Extension pack dependencies' subdependencies are not shown.

**Comment by sandy081** [comment]
@paulvi What do you mean by extension pack dependencies? If an extension pack has dependencies it should be shown in dependencies tab. If it is a extensions (defined using `extensionPack`) those will be shown under extension pack tab.

**Comment by paulvi** [comment]
Well, for dependencies as usual and for extensions (defined using `extensionPack`) 
it would be consistent if VSCode will show subdependencies within any tab.

**Comment by sandy081** [comment]
I see your point, but not sure how the tree looks like in the case where an extension has packed extensions and also dependencies. 

I also think that this cannot get implemented unless it is highly requested. If you are passionate about we are always happy to take a PR.

**Comment by paulvi** [comment]
Just see screenshots above.
In case of [Microsoft Java Extension Pack](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack) within SVCode it should have 2 tabs named "Dependencies" and "Extension Pack" all showing related dependencies.

And this issue is about that in "Extension Pack" it also should be shown as tree.
So actually the same code should handle that as for "Dependencies" tab.

**Comment by sandy081** [comment]
@paulvi Java Extension Pack does not have dependencies. So it does not makes sense to show Dependencies tab.

In fact it is a tree and none of the children are extension packs hence they do no have children.

As I said, I think you are asking for a tree that shows all extensions gets installed when installing the extension? This should be a new tab IMO.

**Comment by paulvi** [comment]
> a tree that shows all extensions gets installed when installing the extension

yes, and it was so when Extension Packs had only dependencies.
Now when any Extension Pack has some dependencies defined in `extensionPack` they are shown as list, not as tree.

If it is clear this way, let's close this issue and open new.
This one got too long.

**Comment by paulvi** [comment]
https://github.com/Microsoft/vscode-java-pack/blob/master/package.json#L84

**Comment by sandy081** [comment]
Hmm that's not good. An extension pack should be just a simple extension that has a pack of extensions to install. Having additional functionalities and especially dependencies is mis-leading. Please file issue against java pack extension to make it correct.

**Comment by paulvi** [comment]
Yes, it is confusing me and would confuse many about what Extension Pack is.
Before it was just a way to install several extensions quick.

`extensionsPack` entry made if clearer, yet possibility to mix ideas, made it no so strict.
