### ISSUE TITLE
edit in all lines prompt: "The number of cursors has been limited to 10000."

### ISSUE THREAD

**Issue by phaibin** [Microsoft/vscode#60713]
VSCode version 1.28.1
OSX 10.14

It's strange I can't find any solution about this situation. 
Is this a limit from VSCode or just a bug?

**Comment by egamma** [comment]
Sorry this as designed and you cannot have more than 10000 cursors.

**Comment by mrtristan** [comment]
https://github.com/Microsoft/vscode/issues/28121

@egamma @alexandrudima any reason this can't be a setting that we can override? this is breaking some workflows that i've been using vscode for now that i've jumped up a few versions. my laptop has 64gb of ram and such so resource constraints shouldn't be a problem.

**Comment by phaibin** [comment]
@mrtristan Agree. I have to return to Sublime Text to edit this kind of big files.
