### ISSUE TITLE
Can't Update

### ISSUE THREAD

**Issue by reserveword** [Microsoft/vscode#60727]
- VSCode Version:1.14.2
- OS Version:Windows 10 x64 10.0.17134

Steps to Reproduce:

1.Open VSCode
2.Click the gear icon at bottom left
3.Where should have updates says “更新不可用”(I believe that "Update not avalible" is it's corresponding phrase in English)
4.Keep it open for a while, and it would not detect any updates either

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Please download VS Code again and reinstall it.
