### ISSUE TITLE
When launching `code` in git-bash, the integrated git-bash terminal won't clear history output properly

### ISSUE THREAD

**Issue by kidlj** [Microsoft/vscode#60720]
- VSCode Version: 1.28.1
- OS Version: Windows 10 1809, 17763.55

Steps to Reproduce:

1. launch code in git-bash: `code`
2. open integrated terminal(git-bash configured)
3. make some output in the terminal: `ls`
4. try to clean the history output of the opened terminal: hit `ctrl + L` or `clear`
5. The history outputs remain

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
See https://github.com/xtermjs/xterm.js/issues/106#issuecomment-393947437
