### ISSUE TITLE
Markdown preview not coloring code blocks

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#6073]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Preview a markdown file that includes a JavaScript code block

 
![mdpreviewcolor](https://cloud.githubusercontent.com/assets/12900364/14997947/1b4b8e04-1136-11e6-936d-a1650dbf92e4.PNG)

It should be colored the same as live:
![mdpreviewcolorlive](https://cloud.githubusercontent.com/assets/12900364/14997975/45c8a428-1136-11e6-8282-fdb32c67021b.PNG)

**Comment by joaomoreno** [comment]
Does it work with `javascript` instead of `js`?

@bpasero, is it worth it to configure this alias?

**Comment by vsccarl** [comment]
@joaomoreno It is not being colored using either `javascript` or `js`

**Comment by PandaFang** [comment]
Same bug with java and c#
