### ISSUE TITLE
issues got when turn on vscode and shows popup on bottom of editor continuously

### ISSUE THREAD

**Issue by sufiiiyan** [Microsoft/vscode#60734]
- Extension Name: configuration-editing
- Extension Version: 1.0.0
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:
```json 
{
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 723,
		"activateCallTime": 1,
		"activateResolvedTime": 0,
		"activationEvent": "onLanguage:jsonc"
	}
}
```

**Comment by egamma** [comment]
Please see #60318
