### ISSUE TITLE
No response when clicking "Add Configuration..." consecutively in Debug dropdown list

### ISSUE THREAD

**Issue by GraceDong** [Microsoft/vscode#60738]
- VSCode Version: 1.28.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Install cpptools extension
2. Create a C++ app
3. Open the app with VSCode
4. F5, select "C++ (GDB/LLDB)" as following picture:
5. Click "Debug" on left menu and select "Add Configuration..." as following picture:
![image](https://user-images.githubusercontent.com/20184778/46851505-4a949580-ce2a-11e8-9f66-9620d1c456ae.png)
6. Select "C/C++: (gdb) Attach" in editor and save this change
7. Click "Add Configuration..." again (note: Don't click on the "Add Configuration..." in the editor.)

Excepted behavior:

The editor should display the message shown below:
![image](https://user-images.githubusercontent.com/20184778/46851045-be35a300-ce28-11e8-95ef-475c08278d11.png)

Actual behavior:

There is no respond.
Clicking on the "Add Configuration..." in the editor will not repro this issue.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by isidorn** [comment]
This works for me. Can you reproduce with latest vscode insiders https://code.visualstudio.com/insiders/
Are you doing something differently than me?
![addconfiguration](https://user-images.githubusercontent.com/1926584/46863715-642ce180-ce18-11e8-8028-3b05248de24e.gif)
