### ISSUE TITLE
Auto Formatted Documents 

### ISSUE THREAD

**Issue by vssadineni** [Microsoft/vscode#60735]
Issue Type: <b>Bug Report | Problem with Auto Formatting</b>

Whenever we hit Ctrl+s button the cursor goes down to the last line of the page, which is very confusing. Just imagine document has about an average 5000 or 6000 lines of code and working on line 500 or 1000 and save the file and you see that the cursor goes to the last line in the document and scrolling all the way up is tedious. Please find a solution for this problem.

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:15:15.139Z)
OS version: Windows_NT ia32 10.0.14393

**Comment by egamma** [comment]
This is caused by an extension that doesn´t implement format properly.

**Comment by vssadineni** [comment]
Thank you Erich.
