### ISSUE TITLE
Problems view filter: Extend capabilities

### ISSUE THREAD

**Issue by Aukstkalnis** [microsoft/vscode#60736]
Extend problem view filter capabilities:
    - Enable to exclude errors, warnings, info messages by writing !error, !warning, !info,
    - Enable to exclude or show only specific messages by writing <!>error/<!>warning/<!>info**:**<Message patern that starts with defined text or has defined text in the message>
    - Enable to stack filter options. If we want to exclude info messages, warnings that have text, for example,  directive and errors that start with, for example, undefined, then we could write like this: !info, !warnings:directive, !error:^undefined
    - Add possibility to mix show only message and exclude messages. Example: info, !info:[cSpell checker]. In this example only info messages are shown that do not starts with [cSpell checker].

**Comment by sandy081** [comment]
this requirement `Enable to exclude errors, warnings, info messages by writing !error, !warning, !info` is covered by #47354 and the rest I do not see any requests.
