### ISSUE TITLE
shift + alt+ f , code formatting  shortcut  broken

### ISSUE THREAD

**Issue by leedonhyun** [Microsoft/vscode#6074]
- VSCode Version: 

Version 1.1.0-insider
Commit 1f0657703be5609d70088b0385bc27db8cc03a41
Date 2016-05-03T07:20:40.394Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0
 
- OS Version:
windows 10

Steps to Reproduce:

1.  Add test.html file
2. Input `<html></html>` tag in  test.html file.
3. shift+ alt+ f , code formatting  shortcut  is broken.
4. After shortcut(shift+ alt+ f ) key down, added `<html> `tag repeatedly

**Comment by alexandrudima** [comment]
@leedonhyun I cannot reproduce. Is it possible you have installed extensions that interfere with or that overwrite the HTML formatting?

![6074](https://cloud.githubusercontent.com/assets/5047891/15083758/593f7c2a-13cf-11e6-8167-88880b8c7246.gif)

**Comment by leedonhyun** [comment]
![animation](https://cloud.githubusercontent.com/assets/8449892/15096362/7d08312c-152f-11e6-880e-2936a474a98c.gif)

My vscode installed extensions are in the list of captured images below.

<img width="245" alt="capture" src="https://cloud.githubusercontent.com/assets/8449892/15096365/92a30e9e-152f-11e6-904b-1f26f9690525.PNG">

**Comment by Alexisvt** [comment]
Hi! Im having the same error, every time that I format the code with the shorcut or the option menu it's repeating the last tag! 
This is the version that I have:

![image](https://cloud.githubusercontent.com/assets/7120647/15132746/04a9b8a4-161a-11e6-9117-1480024758c5.png)

And this is the error:

![error](https://cloud.githubusercontent.com/assets/7120647/15132801/544f83ac-161a-11e6-81c7-85b909c79588.gif)

As you can see is always repeating the last element line

**Comment by Alexisvt** [comment]
I didn't have this error before, this came out on this new version!
