### ISSUE TITLE
Type colon will trigger snippet

### ISSUE THREAD

**Issue by xiaoyongdong** [Microsoft/vscode#60746]
Issue Type: <b>Bug</b>

1. Type colon
2. Snippet will show
![image](https://user-images.githubusercontent.com/3884211/46854716-5d13cc80-ce34-11e8-86ff-59ced99fbdb4.png)

VS Code version: Code - Insiders 1.29.0-insider (931c22033db3cc8d5dff265889307ed4076ac2d3, 2018-10-12T05:17:15.739Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (9.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.60
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.4
path-autocomplete|ion|1.12.0
c-cpp-flylint|jbe|1.2.0
hex-fmt|ker|1.0.0
cortex-debug|mar|0.1.21
python|ms-|2018.9.0
cpptools|ms-|0.19.1-insiders
PowerShell|ms-|1.9.0
veriloghdl|msh|0.3.4
vscode-icons|rob|7.27.0
code-settings-sync|Sha|3.1.2
vscode-hexdump|sle|1.7.0
vscodeintellicode|Vis|1.0.4

(1 theme extensions excluded)

</details>

**Comment by egamma** [comment]
@jrieken I suspect that the C++ extension defines ':' as a trigger character?

**Comment by xiaoyongdong** [comment]
@egamma 1.28 work fine.

**Comment by jrieken** [comment]
This is a regression from fixing #60247 - I will revisit that fix...

**Comment by Raydir** [comment]
My problem of #60759 is solved with the latest fix - Thanx for that  @jrieken
