### ISSUE TITLE
Angular Generate Component

### ISSUE THREAD

**Issue by ewwwgiddings** [Microsoft/vscode#60744]
Issue Type: <b>Bug</b>

When I generate a component for Angular 6 it causes errors in my app module. This only happens on the latest update.

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:13:53.910Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.93GB (0.70GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.1.0
copy-relative-path|ale|0.0.2
vscode-angular2-files|ale|1.6.2
ng-template|Ang|0.1.10
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.60
tslint|eg2|1.0.40
prettier-vscode|esb|1.6.1
vue-snippets|hol|0.1.9
csharpextensions|jch|1.3.0
vscode-nuget-package-manager|jmr|1.1.6
Angular2|joh|6.3.0
csharpfixformat|Leo|0.0.75
Arduino|moo|0.0.4
cpptools|ms-|0.19.0
csharp|ms-|1.16.2
debugger-for-chrome|msj|4.10.2
vetur|oct|0.13.0
Angular2|pav|0.0.1
material-icon-theme|PKi|3.6.0
typescript-hero|rbb|3.0.0
vue-vscode-extensionpack|sdr|0.1.3
vue-vscode-snippets|sdr|1.3.0
vscode-status-bar-format-toggle|tom|1.4.0
vscode-arduino|vsc|0.2.21
vuetify-vscode|vue|0.2.0
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.7.1

(2 theme extensions excluded)

</details>

**Comment by egamma** [comment]
Please provide more information with steps for how to reproduce this problem.
