### ISSUE TITLE
VSCode should respect the Metered Connection flag on Windows, and not download updates

### ISSUE THREAD

**Issue by Jawz84** [Microsoft/vscode#60741]
## general info
 
I've only found #27758 to be slightly related, that's more of a feature request, while I consider this to be a bug, where a MS product, on a MS platform does not respect the 'metered connection' setting.

On VSCode Insiders - I've skipped this check, because it makes no sense in the context of this issue.

- VSCode Version:
Version: 1.28.0 (user setup)
Commit: 431ef9da3cf88a7e164f9d33bf62695e07c6c2a9
Date: 2018-10-05T14:58:53.203Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
- OS Version:
1083 build 17134.285
## Steps to Reproduce:
1. Have a version of VSCode installed that's one or more updates behind. 
1. Set update settings to default. (automatically update)
1. disconnect from any wired network
1. connect to a wireless network, and flag it as 'Metered Connection'

Does this issue occur when all extensions are disabled?: Yes/No
Yes

## Actual behaviour 

VSCode detects a newer version is avaliable, and starts downloading it, even while on a metered connection.

## Expected behaviour

VSCode detects that i'm on a metered connection and only indicates that an update is available, but does not automatically download it.

## Remarks

I love VSCode, and I would love it more if it also respected my wallet :-)
Work-around: disable updates by unchecking 'windows background update' and set updates to 'none'.

**Comment by Jawz84** [comment]
Thank you @vscodebot, but since #8540 is already closed, I would like to leave this issue open. The only way I can work with VSCode now, while on a metered connection, is by disabling alle update-settings.

**Comment by egamma** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/8540

**Comment by Jawz84** [comment]
Thank you @egemma, please help me understand why this is not considered a bug - I noticed you added the feature label. Thanks!

**Comment by Jawz84** [comment]
I've found this documentation by Microsoft on detecting metered connections from javascript: https://msdn.microsoft.com/en-us/library/hh750310
And I think the place where a change would have to be made in
vscode/src/vs/platform/update/electron-main/updateService.win32.ts
Am I on the right track with this? If so - i'm willing to consider proposing a pr. Will wait for guidance.

**Comment by Jawz84** [comment]
I'm abandoning this idea, various reasons.
