### ISSUE TITLE
markdown.styles preview does not work url containing @ character

### ISSUE THREAD

**Issue by mromanch** [Microsoft/vscode#60742]
Issue Type: <b>Bug</b>

Stylesheets specified with HTTPS URL in the `markdown.styles` preference are not used when veiwing Markdown preview.

Various bugs marked as closed (#45260) point to the [Markdown and Visual Studio Code, Using your own CSS](https://code.visualstudio.com/Docs/languages/markdown#_using-your-own-css), which states:
> You can also use your own CSS in the Markdown preview with the `"markdown.styles": [] setting.` This lists **URLs for style sheets to load in the Markdown preview.** These **stylesheets can** either **be https urls**, or relative paths to local files in the current workspace.

However, this isn't working:

```
"markdown.styles": [
        "https://raw.githubusercontent.com/highlightjs/highlight.js/master/src/styles/tomorrow-night-blue.css"
]
```

The same CSS file works fine if I copy it to a local file with a workspace-relative path:

```
"markdown.styles": [
        ".vscode/tomorrow-night-blue.css"
]
```

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:13:53.910Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (7 x 3408)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|20.00GB (7.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
swagger-viewer|Arj|2.0.2
markdown-preview-github-styles|bie|0.1.3
xml|Dot|2.3.2
autorest|ms-|2.0.1
azure-account|ms-|0.4.3
csharp|ms-|1.16.2
PowerShell|ms-|1.9.0
azurerm-vscode-tools|msa|0.4.2
code-spell-checker|str|1.6.10
markdown-pdf|yza|1.2.0

</details>

**Comment by ccb012100** [comment]
Have you tried it with a URL that isn't under the `https://raw.githubusercontent.com`  domain?

Those don't work because GitHub responds with `X-Frame-Options: deny`: [Custom markdown styles not working?](https://github.com/Microsoft/vscode/issues/8287#issuecomment-230021773)

**Comment by mromanch** [comment]
@ccb012100 I have tried this using jsDelivr (`https://cdn.jsdelivr.net/gh/highlightjs/highlight.js@6747ca77b6ec3fea25f7265fa1f295719f619542/src/styles/tomorrow-night-blue.css`).  In the debugger, I do not even see the network load.  However, if I load the URL in the browser and look at the debugger there, I do not see any `X-Frame-Options` header, so as far as I can tell, the new URL does not have the problem you are referencing.

**Comment by mromanch** [comment]
@mjbvz This is not a duplicate of any of the bugs mentioned by @vscodebot.  With the new URL, it is not a duplicate of the one @ccb012100 mentioned.

**Comment by mjbvz** [comment]
Oo, new issue. Bad encoding of `@`: 

`https://cdn.jsdelivr.net/gh/highlightjs/highlight.js%406747ca77b6ec3fea25f7265fa1f295719f619542/src/styles/tomorrow-night-blue.css`

**Comment by rebornix** [comment]
I found 

```
"markdown.styles": [
        "https://raw.githubusercontent.com/highlightjs/highlight.js/master/src/styles/tomorrow-night-blue.css"
]
```

is still not working.

**Comment by mjbvz** [comment]
@rebornix `"https://raw.githubusercontent.com` prevents loading  content in an iframe like the markdown preview. Can you try `https://cdn.jsdelivr.net/gh/highlightjs/highlight.js@6747ca77b6ec3fea25f7265fa1f295719f619542/src/styles/tomorrow-night-blue.css`

**Comment by rebornix** [comment]
@mjbvz it works as expected.
