### ISSUE TITLE
Unable to use Terminal: Select Default Shell function while argument are present

### ISSUE THREAD

**Issue by grekkster** [Microsoft/vscode#60757]
- VSCode Version:
Version: 1.28.1 (user setup)
Commit: 3368db6750222d319c851f6d90eb619d886e08f5
Date: 2018-10-11T18:13:53.910Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

- OS Version:
Windows 10 64b

Steps to Reproduce:
1. I was using the official guide to use different integrated shell - Cmder in my case:
https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration

2. Set terminal shell arguments (to run custom shell for example - for me Cmder):
```
"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",
"terminal.integrated.shellArgs.windows": [
        "/k", "c:\\Tools\\cmder\\bin\\vscode.bat"
    ],
```
3. Use **Terminal: Select Default Shell** function and set **different shell then shell arguments are intended for**, arguments are used for all choices, which breaks creating integrated terminal **Toggle Integrated Terminal** function.

I would like to have a possibility to select different default shells or set multiple shells to switch between them. When I add the Cmder for example according to the guide mentioned before, it works until i swap default shell when i want to create different integrated terminal - it uses same args and fails.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
Right now you do this using an extension: https://marketplace.visualstudio.com/items?itemName=Tyriar.shell-launcher

I'm hesitant to clear the args when the shell switches because it could accidentally erase someone's config.

**Comment by grekkster** [comment]
> 
> 
> Right now you do this using an extension: https://marketplace.visualstudio.com/items?itemName=Tyriar.shell-launcher
> 
> I'm hesitant to clear the args when the shell switches because it could accidentally erase someone's config.

I am using shell launcher but this doesn't allow me to open Cmder shell window with it's shortcut, because it is not set as a default shell. I need to discard previus shell and then open Cmder shell window via command `Shell Launcher: Launch` and then select Cmder which is slow and i need to repeat everytime i start VSCode. Maybe there is some way to use just standard shortcut for opening Cmder terminal immediatelly but i don't know it and i think i could mess up selecting or switching to different shells.
