### ISSUE TITLE
"Add Function Breakpoint" is not available in Breakpoint window

### ISSUE THREAD

**Issue by GraceDong** [Microsoft/vscode#60756]
- VSCode Version: 1.28.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Install cpptools extension
2. Create a C++ app
3. Open this app in VSCode
4. Check "Add Function Breakpoint" in Breakpoints window, it is not available as following:
![disabled](https://user-images.githubusercontent.com/20184778/46859141-7c642700-ce3f-11e8-811b-c6e2d50963c6.PNG)
This issue can not repro on Windows 10.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by isidorn** [comment]
Can you reproduce this issue with vscode insiders?
https://code.visualstudio.com/insiders/

Asking since I can not
