### ISSUE TITLE
ошибка возврата истории HTML

### ISSUE THREAD

**Issue by haiflive** [Microsoft/vscode#60750]
Issue Type: <b>Bug</b>

при редактировании HTML стирается история возврата при автодополнеии тегов
пример пишем код пишем тег <a>
он автоматически дополняется <a></a>
пишем код дальше
возвращаемся при помощи команды Ctrl+Z
отменяем возврат при помощи команды Ctrl+Shift+Z
история возвращается до момента автодополнения и вставляется автодополнение <a></a>, всё дальше вернуть изменения с помощью Ctrl+Shif+Z не получается, из-за того что автодополнение внесло изменение в код

VS Code version: Code - Insiders 1.29.0-insider (f151c46b1783cf4f9a4ca934a85f78846f08688e, 2018-10-11T05:19:51.895Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz (8 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (1.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
php-debug|fel|1.12.6
php-intellisense|fel|2.3.5
smarty|imp|0.3.0
graphql-for-vscode|kum|1.12.1
vscode-language-pack-ru|MS-|1.28.2

</details>

**Comment by egamma** [comment]
Translation:

>when editing HTML, the return history is erased with auto-tagging
example write code write tag
it is automatically completed
write the code further
return with the command Ctrl + Z
cancel the return using the command Ctrl + Shift + Z
the history returns to the moment of auto-completion and auto-completion is inserted, it is impossible to return the changes further using Ctrl + Shif + Z, due to the fact that auto-completion made a change in the code

**Comment by aeschli** [comment]
duplicate of #34484
