### ISSUE TITLE
Vscode automatically opens a large number of windows powershell in the background

### ISSUE THREAD

**Issue by JiangPF92** [Microsoft/vscode#60752]
- VSCode Version: 1.28.0
- OS Version:windows7

Steps to Reproduce:

1. Open vscode and Windows Task Manager.
2. After a while, a large number of windows powershell processes appear in Windows Task Manager.
3. Close vscode, all windows powershell was closed.

Does this issue occur when all extensions are disabled?: No

**Comment by egamma** [comment]
This looks like the same issue as described here #60585

Which extensions do you have installed?

Can you include the output of `code --status` when this happens

**Comment by egamma** [comment]
duplicate of #60585
