### ISSUE TITLE
Setup appears to be blocking itself - window appearing with bizarre message

### ISSUE THREAD

**Issue by fractos** [Microsoft/vscode#60758]
About showed:

Version: 1.27.2 (user setup)
Commit: f46c4c469d6e6d8c46f268d1553c5dc4b475840f
Date: 2018-09-12T16:17:45.060Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

But I appeared to be on this:

Windows 10 Professional 64-bit

Steps to Reproduce:

1. Using VSCode completely normally, there appears to be an update available
2. Window pops up saying:
![image](https://user-images.githubusercontent.com/657772/46859541-e7910780-ce05-11e8-82de-3405db646a90.png)

Does this issue occur when all extensions are disabled?: Yes/No
When I shut down to restart VSCode with the --disable-extensions flag, setup kicked in on another process and updated the editor version to 1.28.0

**Comment by joaomoreno** [comment]
Please restart your machine and try to update once again.
