### ISSUE TITLE
IntelliSense often changes suggestions without user action

### ISSUE THREAD

**Issue by MickaelSylvestre** [Microsoft/vscode#60753]
I have often wrong code completion like this example :
![2018-10-12](https://user-images.githubusercontent.com/7061061/46856978-1e681d00-ce08-11e8-9ec6-63d40ffa2e25.gif)

I start type my method name with "addCs" and if I press Enter, the method "addConfProperty" is selected instead of "addCustomStyle"
If I dont press Enter, I see autocompletion switch for some ms as you can see in the example above

- VSCode Version: 1.28.1 (user setup)
 Commit: 3368db6750222d319c851f6d90eb619d886e08f5
Date: 2018-10-11T18:13:53.910Z
- Electron: 2.0.9
- Node.js: 8.9.3
- V8: 6.1.534.41
- Architecture: x64
- OS Version: Windows 10 (17134.286)
- Typescript : 3.0.3

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
Yeah, I have seen this as well at time. Tho unsure what this is...

**Comment by jrieken** [comment]
@MickaelSylvestre Do you have repro steps for this (from the gif it seems so)? While I see this from time to time I don't really know yet how to reproduce this. It would be awesome if you can share a sample with me.

**Comment by jrieken** [comment]
Understood, I can also only see this in the vscode repo, not in my toy projects. I was hope it's easy for you to repro... I'll what I can do, must be that we don't cancel a re-filter request after typing the next character...

**Comment by jrieken** [comment]
So, I can repro well enough... This seems to happen in the widget itself cc @ramya-rao-a @joaomoreno 

![oct-16-2018 12-35-48](https://user-images.githubusercontent.com/1794099/47010711-17127d80-d140-11e8-9194-013b5637b516.gif)

**Comment by jrieken** [comment]
This is coming from the suggest details that resolve async and that reveal an old item. It misses a cancel call and it misses to reset the focused element. I will pushed changes accordingly.
