### ISSUE TITLE
Current Debian build fails on Ubuntu

### ISSUE THREAD

**Issue by beruic** [Microsoft/vscode#60764]
- VSCode Version: 1.28.1-1539281690
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Upgrade or install `code` from the repository (`deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main`)

Result:
Here is the output from apt:
```
$ sudo apt install code
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  code
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/44.1 MB of archives.
After this operation, 196 MB of additional disk space will be used.
(Reading database ... 226790 files and directories currently installed.)
Preparing to unpack .../code_1.28.1-1539281690_amd64.deb ...
Unpacking code (1.28.1-1539281690) ...
dpkg: error processing archive /var/cache/apt/archives/code_1.28.1-1539281690_amd64.deb (--unpack):
 unable to open '/usr/share/code/code.dpkg-new': Operation not permitted
Errors were encountered while processing:
 /var/cache/apt/archives/code_1.28.1-1539281690_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
I have tried uninstalling code, and reinstalling, but the `/usr/share/code/` never seems to be deleted.

Does this issue occur when all extensions are disabled?: N/A, but yes

**Comment by beruic** [comment]
Found the error. The operation is blocked by Sophos antivirus somehow. Stopping the antivirus service fixed the error.

**Comment by beruic** [comment]
I find this one so edge case, that unless it uncovers other issues, it should be closed. You have my blessing in closing this issue, but I will not do it myself, in case there is something you want to investigate.

**Comment by Tyriar** [comment]
Thanks for letting us know, will see if anyone else reports 🙂
