### ISSUE TITLE
Peek Definition to Find all References closes peek window

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#6076]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Right click a variable > Peek Definition
2. Right click the same variable > Find all References

This closes the peek window and does not open the Find all References window. The reverse (Find all references to Peek Definition) also closes the window.

**Comment by jrieken** [comment]
That's the designed behaviour cos we want to reduce clutter by not allowing to many nested editors. That's why one nested editor closes the other one.

fyi @stevencl
