### ISSUE TITLE
Using vscode to install some plug-ins takes up a lot of memory and a cup

### ISSUE THREAD

**Issue by baobz** [Microsoft/vscode#60761]
🚨 The issue tracker is not for questions 🚨

Using vscode to install some plug-ins takes up a lot of memory and a cup.
There are times when the cup is 100% occupied and the machine crashes

**Comment by egamma** [comment]
Please provide more information about the particular setup. Which extensions do you have installed when your machine consumes a lot of **cpu** and memory.
