### ISSUE TITLE
can't run active file

### ISSUE THREAD

**Issue by RottenPi** [Microsoft/vscode#60768]
- VSCode Version: 1.28.1
- OS Version:  win10 1803

Steps to Reproduce:

1. I open a html file and click "Run Active File",
2. the editor alerts that "Cannot read property 'indexOf' of undefined" and nothing happened,
3. while in the last version it would open the html file in the browser correctly.
4. and I have uninstall vscode and delete the dir '.vscode/' and 'appdata/roaming/code/", then reinstall vscode, but it still not works.

Does this issue occur when all extensions are disabled?: Yes

**Comment by egamma** [comment]
VS Code provides no command ´Run Active File´ so this must come from an extension. Try to find out which extension is causing this and then file an issue against this extension.

**Comment by RottenPi** [comment]
> VS Code provides no command ´Run Active File´ so this must come from an extension. Try to find out which extension is causing this and then file an issue against this extension.
in menu "terminal" - Run Active File, and there is a native command "workbench.action.terminal.runActiveFile"

**Comment by RottenPi** [comment]
> VS Code provides no command ´Run Active File´ so this must come from an extension. Try to find out which extension is causing this and then file an issue against this extension.

in menu "terminal" - Run Active File, and there is a native command "workbench.action.terminal.runActiveFile"

**Comment by RottenPi** [comment]
I'm sure about that, and I back to 1.27.2, it works perfectly, no error occurred, it must be a bug in 1.28 version.

**Comment by egamma** [comment]
Sorry about that. Reopening the issue.

**Comment by Tyriar** [comment]
Hmm, the action just doesn't seem to work for me anymore.

/cc @alexr00

**Comment by Tyriar** [comment]
@RottenPi could you mouse over the file tab for the HTML file and take a screenshot of the tooltip?

**Comment by Tyriar** [comment]
Ping @RottenPi

**Comment by mjhutton** [comment]
I was having the same problem, and (thanks to info in this issue) was able to add a space to my path as a workaround. Not sure about @RottenPi, but fixing the path issue with "Run Active File" would definitely be helpful to me.

**Comment by Tyriar** [comment]
I'm going to assume this is fixed in https://github.com/Microsoft/vscode/commit/08cefacac57a9b5da8e53548c9fd36260f7256fc
