### ISSUE TITLE
Allow re-indexing of files to clear stale search results

### ISSUE THREAD

**Issue by costincaraivan** [Microsoft/vscode#60760]
I've renamed a top-level folder (don't remember if I did it within VS Code or outside of it, I'm not sure it matters much).

Unfortunately now when I search for files, I get both the results in the old folder (which fail to open, obviously, and they're removed from the search results, afterwards, through the popup) and the ones in the new folder.

Is there some way to manually trigger re-indexing of files so that the search results are up-to-date? It's kind of annoying when you have tens or hundreds of files moved around.

**Comment by roblourens** [comment]
Could those renamed files still be open in an editor tab in the background?

**Comment by costincaraivan** [comment]
Nope, they aren't. This happens even after restarting VS Code, I don't know if it makes any difference.

**Comment by roblourens** [comment]
Are those in the "recently opened" section? In the light gray text on the right sie

**Comment by costincaraivan** [comment]
I'm not sure. If I search for "yml" with Ctrl-P, the first line does say "recently opened". Does this mean that everything present there has been recently opened? If so, I guess they were all "recently opened".

**Comment by roblourens** [comment]
Yeah once a file is opened, it's unfortunately not removed from that list when deleted. You can clear the whole recently opened list by running "Clear Editor History".

I think https://github.com/Microsoft/vscode/issues/27317 covers this
