### ISSUE TITLE
Cursor jumps around with auto-save enabled

### ISSUE THREAD

**Issue by rojepp** [Microsoft/vscode#60762]
- VSCode Version: 1.28.1
- OS Version: Win10

Steps to Reproduce:

1. Enable auto-save with a delay of 50 ms
2. Type something reasonably fast:
![jumpy](https://user-images.githubusercontent.com/445888/46863098-c84ea600-ce16-11e8-95e1-7887f33166b9.gif)

When auto-save kicks in in the middle of typing, the cursor goes back to where it was presumably before that 50ms delay, and I continue typing there. Turning auto-save off fixes the problem. Setting a delay of 500ms also fixes the problem, but I could probably manage to repeat the problem given enough time. ;) 
At 50ms it happens constantly.

**Comment by egamma** [comment]
This is typically caused by an extension that doesn´t implement the format API properly.
Can you reproduce this when you have all extensions disabled?

**Comment by egamma** [comment]
This is good to know, thanks. We still need to know whether the issue can be reproduced when all extensions are disabled.
