### ISSUE TITLE
Remove floating debug controls

### ISSUE THREAD

**Issue by fordp2002** [Microsoft/vscode#60770]
I love code but am not a fan of the floating debug control. I hate that I have to press "play" in the debug pane and then press "play" on in the floating control.

I think the controls should be in the debug tab and there should be only one play button!

![code_issue](https://user-images.githubusercontent.com/3258482/46865302-f4692780-ce14-11e8-9c6d-db1dc1972bd0.png)

The large drop down that always says "Python" in my case could be moved in to the "cog" menu as I would think people are not changing that option much so do not need it wasting screen real estate all the time?

I hope this has not already been suggested there are a lot of issues on here and I did look!

Thanks.

**Comment by isidorn** [comment]
Try `"debug.toolBarLocation": "docked"`
Or `"debug.toolBarLocation": "hidden"`

**Comment by fordp2002** [comment]
Thanks for your help. That works pretty much as I wanted.
Great!
