### ISSUE TITLE
Investigate using Electron's `resolveProxy` API in order to better handle requests behind proxies

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#60773]
https://github.com/electron/electron/blob/master/docs/api/session.md#sesresolveproxyurl-callback

Also: https://github.com/felicienfrancois/node-electron-proxy-agent

From @chrmarti:

> Seems reasonably simple. Maybe we can just adapt that for the extension host. We might need a cache to ensure good performance, but that shouldn’t be too hard either.

**Comment by chrmarti** [comment]
Related links:
- Lack of proxy support in Node.js: https://github.com/nodejs/node/issues/15620
- Modifying `https.globalAgent` doesn't work: https://github.com/nodejs/node/issues/9057
- There are `http-proxy-agent`, `https-proxy-agent`, `socks-proxy-agent` and `pac-proxy-agent` node modules, but none for reading the OS' proxy configuration.

**Comment by joaomoreno** [comment]
@chrmarti As promised: https://github.com/joaomoreno/proxy-containers

**Comment by chrmarti** [comment]
Also: https://github.com/joaomoreno/proxy-tests

**Comment by shana** [comment]
We've been having some problems with authentication on the GitHub Pull Requests extension, and I've tracked it down to commit https://github.com/Microsoft/vscode/commit/cc60804a167723aad315142fcfc58da81aaccfe3. The following code:

```
const get = https.request('https://vscode-auth.github.com', res => {
    vscode.window.showInformationMessage(${res.statusCode});
});
get.on('error', err => {
    vscode.window.showInformationMessage(${err});
});
get.end();
```

fails with

```
Error: write EPROTO 140735921918912:error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error:../../vendor/node/deps/openssl/openssl/ssl/s23_clnt.c:802:
```

This has been repro'd on multiple machines running macOS Sierra and Mojave. I have no proxy configuration on my machines. If I set `"http.systemProxy": "off"`, requests work just fine. 

/cc @rebornix

**Comment by chrmarti** [comment]
@shana Could you start with `code-insiders --log=trace` and check what `ProxyResolver#resolveProxy` entry you get in the Log (Extension Host) channel in the Output panel? (You can search with Ctrl + F / Cmd + F in there.)

**Comment by chrmarti** [comment]
@shana Can reproduce now. Looking into it.

**Comment by chrmarti** [comment]
Disabling the setting by default for tomorrow's Insiders build.

**Comment by shana** [comment]
@chrmarti Sorry, I've been traveling and couldn't follow up on this. Yay for repro, thanks for looking into it!

**Comment by chrmarti** [comment]
Tracking the bug as #64133.

**Comment by dwaq** [comment]
I came from the [1.3.0 release page for the network proxy support](https://code.visualstudio.com/updates/v1_30#_network-proxy-support-for-extensions). I just wanted to let that you know that setting `Http: Proxy Support` to `override` **solved** a [longstanding issue where I couldn't install an extension that downloaded extra software from behind a proxy](https://community.particle.io/t/issue-could-not-download-gcc-arm-from-behind-proxy/44363/10). Thank you for this fix.

**Comment by chrmarti** [comment]
@dwaq Great! The goal is to make `override` the default. I have made it the default in the insiders releases (again) and will let that go into the next stable release assuming testing looks good.

**Comment by diev** [comment]
Please keep updated every [whitelist domain](https://code.visualstudio.com/docs/setup/network#_common-hostnames) as issued at [#2278](/Microsoft/vscode-docs/issues/2278) in VS Code Docs.

**Comment by SounD120** [comment]
Hey guys, we have some issues with current Proxy Support feature on the Stable VS Code `1.30.2` and the `1.31-insiders` version. We have created an [issue](https://github.com/Microsoft/vscode/issues/66892) could you please take a look?

**Comment by chrmarti** [comment]
Closing as there are no immediate issues reported anymore. Please open new issues if anything comes up.

**Comment by vilic** [comment]
@chrmarti Is the imported proxy (and explicit proxy settings) being applied to remote extensions? I am experiencing issue with remote extensions accidentally using the local proxy settings.

**Comment by chrmarti** [comment]
@vilic You're right, we need to be smarter about when to use the proxy settings from the local side. I'll open an issue.
