### ISSUE TITLE
Can't display chinese language in output window

### ISSUE THREAD

**Issue by smallprogram** [Microsoft/vscode#60775]
Issue Type: <b>Bug</b>

when i restore the asp.net core package, in output window can't display chinese info.

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:13:53.910Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (9.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.3
xml|Dot|2.3.2
vscode-npm-script|eg2|0.3.5
php-debug|fel|1.12.6
php-intellisense|fel|2.3.5
php-pack|fel|1.0.2
Angular2|joh|6.3.0
vscode-sshfs|Kel|1.10.0
vscode-language-pack-zh-hans|MS-|1.28.2
cpptools|ms-|0.19.0
csharp|ms-|1.16.2
team|ms-|1.142.0
debugger-for-chrome|msj|4.10.2
vscode-icons|rob|7.27.0

</details>

![image](https://user-images.githubusercontent.com/6050360/46868028-91e64a80-ce59-11e8-895d-92865285a740.png)

**Comment by isidorn** [comment]
Can you please properly attach a picture.
Do you mean the debug console or the output? Are you sure this is not a duplicate? Please search through duplicates

**Comment by huleiEthan** [comment]
@smallprogram Maybe this one can help you #60717

**Comment by isidorn** [comment]
Answering my questions would also help
