### ISSUE TITLE
不能调试python

### ISSUE THREAD

**Issue by hihimizi** [Microsoft/vscode#60779]
Issue Type: <b>Bug</b>

1.28 vscode 3.7-32 python g更新到1.28 就不能调试python了

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:13:53.910Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz (8 x 2395)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (4.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
GBKtoUTF8|buk|0.0.2
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.60
code-runner|for|0.9.4
vscode-language-pack-zh-hans|MS-|1.28.2
python|ms-|2018.9.0
cpptools|ms-|0.19.0
csharp|ms-|1.16.2
guides|spy|0.9.2

</details>

**Comment by egamma** [comment]
Translation: Can't debug

Please file the issue against the Python extension and provide more information about how to reproduce the problem.

**Comment by creal1976** [comment]
Stop emailing me or I will file charges of harrasment

Sent from my Verizon Wireless 4G LTE DROID


Erich Gamma <notifications@github.com> wrote:


Translation: Can't debug

Please file the issue against the Python extension and provide more information about how to reproduce the problem.

―
