### ISSUE TITLE
Can`t close terminal by Terminal instance

### ISSUE THREAD

**Issue by chnliquan** [Microsoft/vscode#60771]
- VSCode Version: 1.28.0
- OS Version: macos 10.13.3

Steps to Reproduce:

1. i am developing a vscode extension, there is a function that will show text in terminal when i click a button, the terminal text will start a webpack dev server. i want to close the current terminal and create a new ternimal 
2. i can new a Terminal instance when click but this will open a lot of terminals. This is not what I expected
3. when i use vscond api Terminal.dispose() , its not work

```node
const terminal = vscode.window.createTerminal('hippo')
vscode.commands.registerCommand('pages.preview', object => {
    terminal.show()
    terminal.dispose()
    terminal.sendText(object.terminalText)
  })
```

how to deal it or is there an api to close the current terminal?

**Comment by Tyriar** [comment]
You want something more along the lines of this:

```ts
let terminal;
vscode.commands.registerCommand('pages.preview', object => {
    if (terminal) {
        terminal.dispose()
    }
    terminal = vscode.window.createTerminal('hippo')
    terminal.show()
    terminal.sendText(object.terminalText)
  })
```

Also you might want to look at the task APIs as tasks supports reusing the same terminal across multiple processes.

**Comment by chnliquan** [comment]
> You want something more along the lines of this:
> 
> ```ts
> let terminal;
> vscode.commands.registerCommand('pages.preview', object => {
>     if (terminal) {
>         terminal.dispose()
>     }
>     terminal = vscode.window.createTerminal('hippo')
>     terminal.show()
>     terminal.sendText(object.terminalText)
>   })
> ```
> 
> Also you might want to look at the task APIs as tasks supports reusing the same terminal across multiple processes.

It works, thank you
