### ISSUE TITLE
Python Language Server Consuming Large Amounts of Memory

### ISSUE THREAD

**Issue by mhamilto** [Microsoft/vscode#60778]
With the latest VS Code build (1.28.1) I'm finding that the python language server is consuming large amounts of memory. This is with only 12 python files open, none of which are particularly large.

![image](https://user-images.githubusercontent.com/44090354/46868529-89bde900-ce20-11e8-847e-4319616e3613.png)

I noticed that there were supposed to be at least one fix for this in the last week. But it does not seemed to be sorted on my install. 
Python Extension version is 2018.9.0

**Comment by egamma** [comment]
Please file the issue against the Python extension.
