### ISSUE TITLE
+new Date cause highlighting failure

### ISSUE THREAD

**Issue by hezedu** [Microsoft/vscode#60774]
- VSCode Version:1.28
- OS Version:MacOS 10.13.6

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes

**Comment by egamma** [comment]
What language, what code snippet? How can we reproduce?

**Comment by hezedu** [comment]
![image](https://user-images.githubusercontent.com/8508437/46868201-26e94380-ce5a-11e8-8fa3-ec308384b531.png)

**Comment by hezedu** [comment]
test code
```js
let clickedAt = +new Date;
let backup_url = 'some';
setTimeout(() => {
  if (+new Date - clickedAt < 2000) {
    window.location = backup_url;
  }
}, 1500);
var abc = 'abc';
function abc2(){

}
```

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/Microsoft/TypeScript-TmLanguage/issues/673 to track this upstream
