### ISSUE TITLE
Builds failing for arm64 (vscode-ripgrep 0.10.0 doesn't have an arm64 build)?

### ISSUE THREAD

**Issue by headmelted** [Microsoft/vscode#60785]
- VSCode Version: latest
- OS Version: debian stretch

Does this issue occur when all extensions are disabled?: Yes

error /root/build/code/node_modules/vscode-ripgrep: Command failed.
Exit code: 1
Command: node ./lib/postinstall.js
Arguments: 
Directory: /root/build/code/node_modules/vscode-ripgrep
Output:
Downloading ripgrep failed: Error: No asset named ripgrep-0.10.0-linux-arm64.zip found

This seems to be new.  Having looked at the repository it's hitting (https://github.com/roblourens/ripgrep/releases), it appears that 0.9.0 *did* support arm64, but there's no arm64 zip in the releases for 0.10.0, causing the builds to fail for this architecture.

I know arm64 isn't officially supported, but I suspect this is an unintentional omission, so raising here (the ripgrep repo doesn't support the Issues feature or I would raise there).

**Comment by roblourens** [comment]
I missed uploading it, thanks for the reminder!
