### ISSUE TITLE
Erro de tradução

### ISSUE THREAD

**Issue by izacarias** [microsoft/vscode#60783]
Issue Type: <b>Bug</b>

Ao clicar no ícone "Tweetar feedback" uma tela é exibida.
Existem um campo onde devemos digitar a mensagem e um contador de caracteres restantes, logo acima.

A mensagem no contador de caracteres restantes é:
"Diga-no porquê? (XXX caracteres à esquerda)"

A mensagem no contador de caracteres restantes deve ser:
"Diga-no porquê? (XXX caracteres restantes)"

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:09:20.566Z)
OS version: Linux x64 4.15.0-36-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz (4 x 816)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|3.80GB (0.17GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
gnuplot|mam|1.0.4
vscode-language-pack-pt-BR|MS-|1.28.2
python|ms-|2018.9.0
cpptools|ms-|0.19.0
java|red|0.32.0
vscode-java-debug|vsc|0.14.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.10.0
vscode-maven|vsc|0.11.1

(1 theme extensions excluded)

</details>

**Comment by danyeh** [comment]
Thanks @izacarias for your feedback! 
VS Code is a community localization project host in Transifex. Translation are contributed by community. Could you please help to fix in Transifex? See http://aka.ms/vscodeloc to instruction on how to sign up and contribute.
The string is here.
https://www.transifex.com/microsoft-oss/vscode-workbench/translate/#pt_BR/$/111041273?q=translation_text%3A'caracteres+%C3%A0+esquerda'

**Comment by shawndon** [comment]
Assigning to Production for investigation.

**Comment by danyeh** [comment]
Looks good in current version.
![image](https://user-images.githubusercontent.com/19785531/57961910-1bb23680-78c7-11e9-8c67-4af0dfd3091a.png)
