### ISSUE TITLE
Extensions view filter enters double "@" sign in Insiders release

### ISSUE THREAD

**Issue by carlocardella** [Microsoft/vscode#60793]
Issue Type: <b>Bug</b>

In the current Insiders release, type "@" in the extensions view to bring up suggestions, select any entry from the list and hit Tab or Enter: the string is completed with two leading "@@" signs an of course the filter does not display any result. Remove one of the two "@" signs and filters is applied properly. 
Note: this works fine in the latest Stable release

![insiders_extensions_view](https://user-images.githubusercontent.com/5784415/46878449-32a41e00-cdf8-11e8-9127-37026e6198e8.gif)

VS Code version: Code - Insiders 1.29.0-insider (931c22033db3cc8d5dff265889307ed4076ac2d3, 2018-10-12T05:17:15.739Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.86GB (15.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by charlottetan** [comment]
Additionally, trying to type any of the commands doesn't seem to trigger autocomplete anymore.
(dev build on left, stable build on right)

![vscode-extensions-autocomplete](https://user-images.githubusercontent.com/4824630/47271429-26257100-d52e-11e8-8c5d-2c9f615343ea.gif)

**Comment by ramya-rao-a** [comment]
@jrieken This issue got introduced with the commit https://github.com/Microsoft/vscode/commit/d00e5cb041fbbb610851acc572db9969201557bf#diff-6dba103c08842c74d9919a87c5561c11

**Comment by ramya-rao-a** [comment]
This got fixed by https://github.com/Microsoft/vscode/commit/11cb54e1a98bca8bacf003d64a728a0f23ab9c41 as well
