### ISSUE TITLE
Extension view filter missing some suggestions

### ISSUE THREAD

**Issue by carlocardella** [Microsoft/vscode#60791]
Issue Type: <b>Bug</b>

Sidebar extension view filter in the Insiders release does not behave properly:, some entries are not properly suggested. For example, "@inst" should suggest "@installed" and "@sort:installs", it works fine in the latest Code release but the last 3-4 Insiders releases only show the "@sort:" option. 
Note, if I type "@installed" then the extension list is filtered correctly.

![image](https://user-images.githubusercontent.com/5784415/46875510-b65a0c80-cdf0-11e8-9813-c4e53ba79b36.png)

![image](https://user-images.githubusercontent.com/5784415/46875636-0afd8780-cdf1-11e8-8e93-2943f041ac1a.png)

VS Code version: Code - Insiders 1.29.0-insider (931c22033db3cc8d5dff265889307ed4076ac2d3, 2018-10-12T05:17:15.739Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.86GB (15.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by nealot** [comment]
This also affects the settings editor (UI).

**Comment by ramya-rao-a** [comment]
This happens in the new settings editor search as well. Try typing `@i`. In stable 1.28, you will still see 2 results, but in Insiders you see none. cc @roblourens 

@jrieken This issue got introduced with the commit https://github.com/Microsoft/vscode/commit/d00e5cb041fbbb610851acc572db9969201557bf#diff-6dba103c08842c74d9919a87c5561c11

**Comment by jrieken** [comment]
Do these providers use overwriteBefore/After?

**Comment by jrieken** [comment]
Yeah, looks like they do...

<img width="1248" alt="screenshot 2018-10-22 at 18 06 32" src="https://user-images.githubusercontent.com/1794099/47303811-3b30fb80-d625-11e8-853a-ee0e1790fdff.png">

**Comment by jrieken** [comment]
@ramya-rao-a @roblourens Where are those providers implemented?

**Comment by jrieken** [comment]
Nevermind, found it: https://github.com/Microsoft/vscode/blob/121c60f64af7f6b2e4f489a1cf2c0881d2a193dd/src/vs/workbench/parts/codeEditor/electron-browser/suggestEnabledInput.ts#L185
