### ISSUE TITLE
Discarding changes on a file deletes other untracked files

### ISSUE THREAD

**Issue by mdarse** [Microsoft/vscode#60797]
Issue Type: <b>Bug</b>

1. Initialize a git repository and open the folder in VSCode.
2. Create two new files, one named `*.json` and the other `foo.json`.
3. From the Git panel, click on the curvy arrow icon of the `*.json` file to discard changes.

At that point I expect to still have the `foo.json` file in the tree, but it's not there anymore.
From what I saw, VSCode is exec'ing `git clean -n -f -- <path_git_repo>/*.json`. The last argument is treated as a pathspec by Git but doesn't seem to be escaped by VSCode.

```
❯ git --version
git version 2.15.0
```

May be related to https://github.com/Microsoft/vscode/issues/41246

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-04T16:40:40.180Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 5|
|Memory (System)|16.00GB (0.68GB free)|
|Process Argv|-psn_0_13868345|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
EditorConfig|Edi|0.12.4
npm-intellisense|chr|1.3.0
vscode-css-modules|cli|0.2.3
gitignore|cod|0.5.0
vscode-eslint|dba|1.6.0
xml|Dot|2.3.2
gitlens|eam|8.5.6
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.6.1
php-debug|fel|1.12.6
text-transform|flo|0.1.0
flow-for-vscode|flo|0.8.4
vscode-pull-request-github|Git|0.2.0
ansible|haa|0.2.8
vscode-firefox-debug|hbe|1.7.0
vscode-rust|kal|0.4.2
vscode-csscomb|mrm|5.2.2
python|ms-|2018.9.0
cpptools|ms-|0.19.0
vsliveshare|ms-|0.3.790
debugger-for-chrome|msj|4.10.2
vscode-docker|Pet|0.3.1
elm|sbr|0.22.0
code-settings-sync|Sha|3.1.2
sci-sort-import-groups|Sno|2.1.1
ansible-autocomplete|tim|0.0.2
shellcheck|tim|0.6.0
vscode-arduino|vsc|0.2.21
babelrc|wad|1.0.0
vscode-wakatime|Wak|1.2.3
twig|wha|1.0.2
vscode-import-cost|wix|2.9.0

</details>

**Comment by fatcerberus** [comment]
`*` is a legal filename character?  Seems like a huge footgun.

**Comment by mdarse** [comment]
I think only null byte and `/` are illegal file name on posix but may be wrong. I suppose it depends on the filesystem.

In that case I was showing to someone how to avoid globbing issues in a shell script when I noticed that bug.

**Comment by joaomoreno** [comment]
Yeah it definitely feels like you're living on the edge. Since Code simply spawns Git which sometimes runs a shell, there's not much we can do to prevent this. It's also the first time I see someone hitting such an issue, so I'll close it given the workaround: don't created files named like that. Sorry!
