### ISSUE TITLE
Git: Delete Branch command should support multiple choice

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode#60799]
The `Git: Delete Branch` command at the moment supports deleting only one branch at a time.

Most of the time I use this feature is delete all the stale branches I have either from working on old features or the branches that get created when doing PR reviews.

Having a multiple choice for this command would make it easier to clean up the mess :)

**Comment by joaomoreno** [comment]
This might be interesting for you: https://stackoverflow.com/questions/6127328/how-can-i-delete-all-git-branches-which-have-been-merged

**Comment by mitchellirvin** [comment]
I'd like to take a stab! Can somebody add me as the assignee?

**Comment by brute4s99** [comment]
I would like this work on this issue !

**Comment by joaomoreno** [comment]
First come first serve, guys!

**Comment by Ragnoroct** [comment]
@joaomoreno Do you want this to be a new command?

**Comment by joaomoreno** [comment]
Actually, we now have a powerful quick open API which allows for multi-select. I'd just adopt that API in the existing Delete Branch command.

**Comment by joaomoreno** [comment]
Closing as won't do.
