### ISSUE TITLE
Add 'experimentalAsyncFunctions' compiler options to jsconfig.json

### ISSUE THREAD

**Issue by Beingbook** [Microsoft/vscode#608]
Hello.
My codes uses `async` / `await` and `target` option is `ES6`.
VSCode highlights around of `async` / `await` with red underline.
Is there way solve it?

Thank you.

**Comment by tgienger** [comment]
Same. Not only is `async`/`await` underlined, but all `let` and corresponding variables within the same block are also `can't find name ...`

**Comment by vsDizzy** [comment]
async / await is ES7 not ES6 feature. But I agree we need Intelisence on them,

**Comment by Dynalon** [comment]
This is a bug, not a feature request!

I got the same problem: Using the latest TypeScript 1.7.5, target set to `es6` and invoking `tsc` on the commandline yields no compile errors and async/await work fine, latest vscode will under line all async functions red. Highlighting it says that experimentalAsyncFunctions should be enabled in the compiler, although I *do* have this in the `compilerOptions` section of `tsconfig.json` set.

I bet the vscode internal TypeScript compiler is not setting the `--experimentalAsyncFunctions` flag, and thus thinks the code is wrong (although it isn't).

**Comment by Dynalon** [comment]
Correcting my previous comment: My `tsconfig.json` was mislocated and thus not loaded properly. It actually DOES work if you put `"experimentalAsyncFunctions": true` into your `tsconfig.json`. So this can by workaround by having a tsconfig.json with that setting set (which is not a real fix as using a tsconfig.josn is optional for typescript projects).

**Comment by Dynalon** [comment]
With the update to vscode released today and the inclusion of TS 1.7.5, this bug is completely gone; please close and thanks for the fix :beers:

**Comment by Beingbook** [comment]
Thank you!

**Comment by calebboyd** [comment]
I believe this is still an issue. @Dynalon was referencing tsconfig but, the OP is for `async/await` in JS. which is still screaming.  Once this is fixed I can probably _actually_ use vscode! :+1:

**Comment by jrieken** [comment]
That's true. We have advanced the TS version but not yet the language service we use for JavaScript. That will come very soon. Stay tuned.

**Comment by Beingbook** [comment]
as @jrieken  mentioned, other javascript extension supports es7 functions.
@calebboyd temporally, you could fix it change extension `jsx` from `js`
