### ISSUE TITLE
Open native console: Use folder name as title for cmd windows

### ISSUE THREAD

**Issue by jblanchet** [Microsoft/vscode#60806]
Opening a new console window with ctrl-shift-c opens a cmd window titled '\\'. I typically have 5+ VS Code instances open and I love this feature but my taskbar just shows 5+ windows with "\\". It would be great to include the same name as the VS Code instance as the title in order to differentiate them at a glance.

**Comment by Tyriar** [comment]
While we can't have the path show, this is an issue that it says \\. I've fixed it up to leave it the title up to cmd.exe. This is what it should look like after this change:

![image](https://user-images.githubusercontent.com/2193314/47048941-b3dd1700-d150-11e8-876e-59d97ccc8705.png)
