### ISSUE TITLE
Quick open command should allow you select and open multiple files

### ISSUE THREAD

**Issue by fernet87** [Microsoft/vscode#60800]
Issue Type: <b>Feature Request</b>

The quick open command (Ctrl + P) should allow the user select and open multiple files like the eclipse or others editors which have this functionality.
I am working in angular and for example i want to edit the start.component.ts, start.component.html and start.component.scss and it's very annoying for me pres Ctrl + P and type start.component... for each file.
Please do that.

Thank you.

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:13:53.910Z)
OS version: Windows_NT x64 10.0.17134

**Comment by usernamehw** [comment]
Right arrow <kbd>→</kbd> or mouse middle click?

**Comment by fernet87** [comment]
> Right arrow → or mouse middle click?

Ok, i didn´t know that.
It is very unintuitive. I expected that by keeping the shift pressed and the arrow down (or clicking) the filenames will be selected and with enter all the selected ones will open or some behavior like that
