### ISSUE TITLE
[Search by keypress] not always a complete match

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#60804]
Issue Type: <b>Bug</b>

Searching by pressing keys in keybindings GUI is not always matching for correct hotkey name:

Example of searching for arrow right <kbd>→</kbd>
Expected: `RightArrow`
Actual: `right`

![screenshot 62](https://user-images.githubusercontent.com/9638156/46886327-433dae00-ce63-11e8-93fc-36059b19a41d.png)

VS Code version: Code - Insiders 1.29.0-insider (931c22033db3cc8d5dff265889307ed4076ac2d3, 2018-10-12T05:17:15.739Z)
OS version: Windows_NT x64 10.0.17134

**Comment by creal1976** [comment]
Spam quit emailing me

Sent from my Verizon Wireless 4G LTE DROID


Alexander <notifications@github.com> wrote:


Issue Type: Bug

Searching by pressing keys in keybindings GUI is not always matching for correct hotkey name:

Example of searching for arrow right →
Expected: RightArrow
Got: right

[screenshot 62]<https://user-images.githubusercontent.com/9638156/46886327-433dae00-ce63-11e8-93fc-36059b19a41d.png>

VS Code version: Code - Insiders 1.29.0-insider (931c220<https://github.com/Microsoft/vscode/commit/931c22033db3cc8d5dff265889307ed4076ac2d3>, 2018-10-12T05:17:15.739Z)
OS version: Windows_NT x64 10.0.17134

**Comment by creal1976** [comment]
Stop

Sent from my Verizon Wireless 4G LTE DROID


Alexander <notifications@github.com> wrote:


Issue Type: Bug

Searching by pressing keys in keybindings GUI is not always matching for correct hotkey name:

Example of searching for arrow right →
Expected: RightArrow
Got: right

[screenshot 62]<https://user-images.githubusercontent.com/9638156/46886327-433dae00-ce63-11e8-93fc-36059b19a41d.png>

VS Code version: Code - Insiders 1.29.0-insider (931c220<https://github.com/Microsoft/vscode/commit/931c22033db3cc8d5dff265889307ed4076ac2d3>, 2018-10-12T05:17:15.739Z)
OS version: Windows_NT x64 10.0.17134

**Comment by usernamehw** [comment]
Actually, even a perfect match is not good enough:
![screenshot 64](https://user-images.githubusercontent.com/9638156/46903549-57bf8c00-cedf-11e8-9411-6840e36356b1.png)

Is it possible to search only by `Keybinding` column? Quotes seems to work fine:
![screenshot 66](https://user-images.githubusercontent.com/9638156/46903602-08c62680-cee0-11e8-8da5-9cdd1abb211b.png)
