### ISSUE TITLE
Cannot Capture File->Save menu option when using a webview

### ISSUE THREAD

**Issue by allenoleksak** [microsoft/vscode#60801]
We have a use case where we have created our own extension to open certain file extensions via a webview.  This basically allows the user to enter meta data stored in json in a more visual way.  One issue we are running into though is since we are using a webview, if the user selects File->Save or any of those save commands, we aren't able to capture that.

We need an event to get fired if the user does that and a WebView is the current active editor.

**Comment by mjbvz** [comment]
@sbatten With your work, won't the save menu item be disabled if there is no active editor?

**Comment by allenoleksak** [comment]
@mjbvz @sbatten 

If the plan is to disable it, that may also work in our case.  At least that way the user isn't confused, thinking they are saving using the file menu.  We can add our own save buttons in the webview in that case.

**Comment by allenoleksak** [comment]
Closed by mistake

**Comment by sbatten** [comment]
@mjbvz yes, we should add that context key to save and save as...

**Comment by bpasero** [comment]
@sbatten sorry but I had to revert this change as it imho breaks our layers. Checking https://github.com/Microsoft/vscode/wiki/Code-Organization#workbench-parts there is:

> think twice before letting a part depend on another part: is that really needed and does it make sense? Can the dependency be avoided by using the workbench extensibility story maybe?

In this case we suddenly make the files contribution depend on the welcome experience. Is that really a good idea? I would prefer a clean solution where e.g. we introduce a new context key that is managed by the workbench and is updated when editors change by asking them if they can be saved or not. This may not exist yet, but we can easily add more methods to editors (or inputs) to support that.

**Comment by sbatten** [comment]
fair enough. I would argue that this isn't a hard dependency in that the removal of the welcome ex does not change its behavior, but I understand the idea. I don't want to be maintaining this list if it grows, either. I did not find a reliable dirtyEditor context key or similar, but we can add one.

**Comment by bpasero** [comment]
> isn't a hard dependency in that the removal of the welcome ex does not change its behavior

How is this not a hard dependency? We will not be able to bundle the file explorer alone without the welcome code unless we remove the import statements.

> I did not find a reliable dirtyEditor context key or similar, but we can add one.

I think [`handleContextKeys`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/workbench.ts#L629) would be a good start to add this. It is the one that already reacts to editors changing. We can look into this when you are here :+1:

**Comment by sbatten** [comment]
> We will not be able to bundle the file explorer alone without the welcome code unless we remove the import statements.

My mistake, forgot I actually used the id variable and not just the string literal.
