### ISSUE TITLE
Git folder shows .VC.db* files as modified

### ISSUE THREAD

**Issue by sumonto** [Microsoft/vscode#6080]
VSCode Version: 1.0
OS Version: OS X Elcapitan
Steps to Reproduce:

Open a git repository
I have configured
$ git config --global core.excludesfile ~/.gitignore_global
and added them to .gitignore_global it does not work

.vscode, and .VC. files are shown as modified,
These files should be auto ignored

(Same as issue https://github.com/Microsoft/vscode/issues/5868)
Had to create this one since I did not get a response on the updates.

**Comment by joaomoreno** [comment]
What does `git status` return on the command line?

**Comment by sumonto** [comment]
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

**Comment by joaomoreno** [comment]
Can you provide a screenshot?

**Comment by sumonto** [comment]
I cannot repro the issue after the latest VS Code updates.
Can you assign this back to me, without closing it?

**Comment by joaomoreno** [comment]
Will just close it. Feel free to reopen if it happens again.
