### ISSUE TITLE
createFileSystemWatcher API not fired when parents renamed

### ISSUE THREAD

**Issue by NTaylorMullen** [microsoft/vscode#60813]
- VSCode Version: 1.28.0
- OS Version: Win10-x64

Steps to Reproduce:

1. Create a file system watcher that monitors adds/removes:
```TypeScript
...
        const watcher = vscode.workspace.createFileSystemWatcher('**/*.csproj*');
        const createRegistration = watcher.onDidCreate(async (uri: vscode.Uri) => {
            console.log('CSProj added: ' + uri.toString());
        });

        const deleteRegistration = watcher.onDidDelete(async (uri: vscode.Uri) => {
            console.log('CSProj removed: ' + uri.toString());
        });
...
```
2. Change the parent folder of a csproj

Expected: remove => create gets called on the watched files
Actual: Nothing fires

#### Additional Notes
Seeing this in practice in the Razor VSCode extension: https://github.com/aspnet/Razor.VSCode/blob/05b60813dd446fc4a21529a3513aeec186886465/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorProjectTracker.ts#L25-L32

**Comment by creal1976** [comment]
Stop emailing me or I will report you for harrasment

Sent from my Verizon Wireless 4G LTE DROID


"N. Taylor Mullen" <notifications@github.com> wrote:


  *   VSCode Version: 1.28.0
  *   OS Version: Win10-x64

Steps to Reproduce:

  1.  Create a file system watcher that monitors adds/removes:

...
        const watcher = vscode.workspace.createFileSystemWatcher('**/*.csproj*');
        const createRegistration = watcher.onDidCreate(async (uri: vscode.Uri) => {
            console.log('CSProj added: ' + uri.toString());
        });

        const deleteRegistration = watcher.onDidDelete(async (uri: vscode.Uri) => {
            console.log('CSProj removed: ' + uri.toString());
        });
...

  1.  Change the parent folder of a csproj

Expected: remove => create gets called on the watched files
Actual: Nothing fires

Additional Notes

Seeing this in practice in the Razor VSCode extension: https://github.com/aspnet/Razor.VSCode/blob/05b60813dd446fc4a21529a3513aeec186886465/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorProjectTracker.ts#L25-L32

**Comment by creal1976** [comment]
Stop emailing me I have unsubscribed and deleted my account and you flood my account with about 50 emails a min..stop this is harrasment

Sent from my Verizon Wireless 4G LTE DROID


"vscodebot[bot]" <notifications@github.com> wrote:


(Experimental duplicate detection)
Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:

  *   Unable to find project.json or *.csproj if there are multiple *.csproj (#60381)<https://www.github.com/Microsoft/vscode/issues/60381>

**Comment by bpasero** [comment]
This is a consequence of us optimizing to only report the folder rename as a change event and not the files within. We might support this scenario with a new file system implementation.

**Comment by NTaylorMullen** [comment]
> This is a consequence of us optimizing to only report the folder rename as a change event and not the files within. We might support this scenario with a new file system implementation.

Interesting choice. Should I change my bits to use the onChange method?

**Comment by bpasero** [comment]
@NTaylorMullen well there is currently no workaround unless you throw in a glob pattern with the name of the folder that was renamed.

**Comment by NTaylorMullen** [comment]
Oh geez that's pretty bad. I guess we'll have to leave the behavior broken for now then. Is there another issue I can watch that tracks the effort to "support this scenario with a new file system implementation"?

**Comment by Timmmm** [comment]
Is this API completely broken then? If I'm writing a C extension (for example) and a user opens `Foo.cpp` which contains `#include "bar/Foo.h"`, I want to add a watch for `Foo.h`... but then if they rename the `bar` directory my extension won't be notified? Is that right?

**Comment by Mrazator** [comment]
This is a pretty big limitation for stateful language servers which cannot track project-wide diagnostics and changes - it's almost 3 years old, anyone using some workarounds (except for custom language client and filewatcher)? 

> @NTaylorMullen well there is currently no workaround unless you throw in a glob pattern with the name of the folder that was renamed.

Theoretically, this could work by throwing in the glob all existing folders, but once there is some folder for example copied (as it was not existing), then the server is unnotified again.

**Comment by sakivns** [comment]
> This is a pretty big limitation for stateful language servers which cannot track project-wide diagnostics and changes - it's almost 3 years old, anyone using some workarounds (except for custom language client and filewatcher)?
> 
> > @NTaylorMullen well there is currently no workaround unless you throw in a glob pattern with the name of the folder that was renamed.
> 
> Theoretically, this could work by throwing in the glob all existing folders, but once there is some folder for example copied (as it was not existing), then the server is unnotified again.

I have used the glob pattern "**/*" which is triggering didChangeWatchedFile for each folder delete or rename(in this case created and deleted). In case of copying a folder, the didChangeWatchedFile event is triggered for folder creation, and for all the nested specific files for which patterns are registered.

**Comment by bmewburn** [comment]
I've found this is a problem when trying to watch file changes in PHP projects when using composer. Composer appears to save files to a temp directory before renaming the dir. This results in a bunch of create events for files that only exist briefly and no events for the rename.

**Comment by Timmmm** [comment]
I still don't understand how we're supposed to use this API at all given this bug.

Suppose I'm writing an LSP for Java. I want to know about all `.java` files in the workspace and receive a notification when any of them is created, modified, renamed or deleted.

It sounds like the only way to do that currently is:

1. Use this API but watch *everything*, and then add custom logic to invalidate folder contents when the folder is deleted/renamed.
2. Just give up on this API and do the watching yourself.

Ironically the [LSP specification recommends using this API](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_didChangeWatchedFiles) because:

> in our experience getting file system watching on disk right is challenging

Well, yeah. Can you really say "use our API - it's hard to get it right", when your API is so fundamentally broken?

**Comment by RobbyCBennett** [comment]
I have this problem with renamed or deleted folders for a language client I'm working on. I didn't find a workaround yet. I tried adding server capabilities for "workspace" and that didn't help.

**Comment by znorman-harris** [comment]
> I have this problem with renamed or deleted folders for a language client I'm working on. I didn't find a workaround yet. I tried adding server capabilities for "workspace" and that didn't help.

I ended up doing two things:

1. You can listen to workspace events in VSCode that let you know this is happening ([here](https://github.com/interactive-data-language/vscode-idl/blob/f3ead73609c8154210919eafd3fbeba2ba25e50b/libs/vscode/client/src/lib/start-language-server.ts#L271-L290) is my example)
2. Send a custom message to the language server that will manually trigger whatever actions need to happen ([here](https://github.com/interactive-data-language/vscode-idl/blob/main/libs/vscode/server/src/lib/events/custom-events/on-folder-delete.ts) is what I did to remove/re-index files)
