### ISSUE TITLE
Tooltips stop working after opening context menu in the editor

### ISSUE THREAD

**Issue by havoron** [Microsoft/vscode#6081]
When pointing to program objects (variables, methods, classes, etc) by mouse, vscode shows tooltip with information about it:

C#

![vscode-csharp-tooltips](https://cloud.githubusercontent.com/assets/18505072/15002747/4e642c5c-11ad-11e6-8f7d-142ce54f9b4f.png)

Golang

![vscode-go-tooltips](https://cloud.githubusercontent.com/assets/18505072/15002751/55a8f254-11ad-11e6-8d25-c8df712bf29a.png)

Or just json file with vscode settings.

But after opening context menu by right mouse button click tooltips stop working.

![vscode-context-menu](https://cloud.githubusercontent.com/assets/18505072/15002774/97defc4a-11ad-11e6-82db-1f4e1bffccfe.png)

Pointing any object doesn't trigger tooltips anymore. It starts working again after restart of vscode.

- VSCode Version: 1.1.0-insider (Commit 1f065770).
- OS Version: Windows 10.0.10586 and Fedora 23.

Steps to Reproduce:

1. Start vscode.
2. Open File -> Preferences -> User Settings (or any Go/C# file).
3. Point to `editor.fontFamily`. It triggers tooltip "Controls the font family".
4. Press right mouse button to open context menu.
5. Point to `editor.fontFamily` again. There's no tooltip.

**Comment by joaomoreno** [comment]
YES! You should get an award for this issue. I've seen the hover stop working several times but never found a way to reproduce it...

**Comment by admmasters** [comment]
I was about to come on to raise this issue. The tooltips stopped working - I had not pinned it down to use of the context menu - some sort of global state issue? This is also happening on OSX 10.11.5 beta.

**Comment by admmasters** [comment]
Its a regression that does not appear to be happening on earlier versions of VSCode - specifically this is not occurring on 1.0.

**Comment by alexandrudima** [comment]
No need to port this change from `release/1.1` to `master` because cb0977bb8d4a592a73654815bf0267f5a139d75f fixed it on master already. I just didn't realize it was a recent regression introduced by the new Electron version update.

**Comment by alexandrudima** [comment]
Steps to verify:
* have a file.ts:
```
interface comeon {
}
```

* hover over comeon
* right click on comeon
* click somewhere else (not on an action)
* hover no longer shows
> This is caused because the contextmenu disables the hover while it is being shown for historic reasons (if the contextmenu is implemented in HTML and not natively)
