### ISSUE TITLE
my vs code  commit suicide !!

### ISSUE THREAD

**Issue by zhangenming** [microsoft/vscode#60817]
Wake up after a sleep.
Boot up computer and found my vscode has been uninstalled

and i Reinstall it
fortunately, all Plug-in, configuration Be retained

No problem now.
Just reporting to you.

 

- VSCode Version:1.28
- OS Version:6.1.7601 Service Pack 1 Build 7601

Does this issue occur when all extensions are disabled?: No

**Comment by zhangenming** [comment]
6.1.7601 Service Pack 1 Build 7601
Suicide version, 1.28

**Comment by cleidigh** [comment]
@zhangenming 
By "unmounted" do you mean that VSC got uninstalled?  No evidence of the program after coming out of sleep?

**Comment by zhangenming** [comment]
https://pic4.zhimg.com/50/v2-b6fbb71c758c3b859de3b074f1a01700_b.jpg

after auto uninstalled  screenshot

**Comment by zhangenming** [comment]
https://pic4.zhimg.com/50/v2-b6fbb71c758c3b859de3b074f1a01700_b.jpg

**Comment by zhangenming** [comment]
https://pic1.zhimg.com/50/v2-4bb4e08d58a735808aae044e96d7cb34_b.jpg

**Comment by egamma** [comment]
@zhangenming I don't have permission to view the attached images.

**Comment by zhangenming** [comment]
http://wx1.sinaimg.cn/mw690/0060lm7Tly1fw6jv9o9ejj30is094n19.jpg
http://wx3.sinaimg.cn/mw690/0060lm7Tly1fw6jv9oe0rj30ce06s400.jpg

**Comment by egamma** [comment]
Cannot act on the issue given the information provided.
