### ISSUE TITLE
Terminal layout changes when open developer tools.

### ISSUE THREAD

**Issue by Anti-Li** [Microsoft/vscode#60819]
Issue Type: <b>Bug</b>

Terminal layout changes when open developer tools.

![animation](https://user-images.githubusercontent.com/28052536/46900744-a8cc8180-ced9-11e8-95e2-c6f7f4348b7b.gif)

![image](https://user-images.githubusercontent.com/28052536/46900746-b1bd5300-ced9-11e8-881b-4f434505a595.png)

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:13:53.910Z)
OS version: Windows_NT x64 10.0.17134

**Comment by Anti-Li** [comment]
Haven't tested when use Powershell or Bash.

**Comment by egamma** [comment]
In the animated GIF I can see that the terminal adjust its layout to the smaller space, which is correct. Do I overlook another problem?

**Comment by fatcerberus** [comment]
@egamma If you take a look at the second screenshot below the GIF, it appears that the terminal doesn't properly resize itself back once it's no longer "squeezed".

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
