### ISSUE TITLE
Improve ui/ux when debugging with multiple configurations

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#60810]
I am often debugging both an extension and attaching to an lsp server and I find the current ui/ux frustrating when constantly switching between them. Having to use the dropdown on the Debug sidebar to switch between running the extension vs attaching to the lsp server is imo less than ideal.

I would love to see something like the following (one or more of them):
1. a way of defining shortcut keys to launch specific configs (ideally per workspace)
1. a way to make a config(s) the default (like tasks) -- so that F5 would ALWAYS run that config, and if there were more than 1 default, it would open a quickpick with the set of defaults (again just like build tasks when you hit Ctrl+Shift+B)
1. in lieu of the default above, another option would be a way to start a launch config without switching the selected launch config -- e.g. I start debugging the extension (so the dropdown is the extension), then I want to attach to the lsp server so I run something like `workbench.action.debug.selectandstart` but it *shouldn't* change the selection. So that when I stop debugging and I hit F5 again, it runs the extension rather than attaching to a not running lsp server.
1. Coupled with the one above, would be nice to be able to have F5, if the debugger wasn't paused (BP or otherwise), open a quickpick of launch configs (not by default, but something that can be made to happen via custom shortcut configuration)

Thoughts?

**Comment by fabiospampinato** [comment]
More state in general about debugging should be exposed (https://github.com/Microsoft/vscode/issues/30810), and more APIs for interacting with it should be made available.

AFAIK right now the only way of switching debugger when compound debugging are:
- Putting the toolbar in the sidebar and using the dropdown:
  - It looks totally out of place
  - The sidebar becomes ginormous
  - If one wants to have another activity bar view active one has to switch to the "debug" view first and then back again
- Having a floating toolbar:
  - Good look debugging and searching at the same time or just having that thing out of the way

With proper APIs for this one should be able to switch to a particular debugger with a shortcut, display all the available debuggers in a quickpick etc.

**Comment by isidorn** [comment]
Thanks for the suggestions
1. We could add some command to launch the first, second, third ... launch configuraition without default keybindings. Than a user can define the keybindings on his own
2. Not a big fan of having the default and also the drop down, to me it feels like they could be contradicting each other
3. We could introduce some command which simply launches and does not select. Or something in that order

Let's keep this open for now to gather more user feedback before jumping on it.

fyi @weinand

**Comment by isidorn** [comment]
@eamodio if you are still passionate about this we could meet and discuss potential ides on how to tackle it.

**Comment by eamodio** [comment]
@isidorn sure - would definitely like to talk about it

**Comment by isidorn** [comment]
Let's talk some time next week, just ping me on slack. Thanks :)

**Comment by tao-cumplido** [comment]
I find the toolbar takes too much horizontal space in docked mode.

![grafik](https://user-images.githubusercontent.com/6384563/69346448-10273a00-0c73-11ea-9921-e93790ff05aa.png)

The DEBUG label could be removed maybe, or make the toolbar two lines.

**Comment by isidorn** [comment]
@eamodio did this experience improve with the current focus stack frame improvements?
If not I would suggest that you schedule a short meeting with Rob since he is taking over Debug UI.

For now closing this issue, and the best step forward would be to schedule a meeting with Rob I think, and then you two can create a new up to date issue.

Sorry for note being more responsive on this one

**Comment by eamodio** [comment]
I honestly haven't debugged a scenario like this in a long time. So I'm not sure if it's better or not. If/when I do that again we can revisit
