### ISSUE TITLE
Unexpected macro syntax error when macro is in an expression

### ISSUE THREAD

**Issue by xisui-MSFT** [Microsoft/vscode#60812]
Issue Type: <b>Bug</b>

Example:
#ifdef TEST
int func(int a,
#else
int func2(int a,
#endif
int b);

Error: #else and #endif are red since it thinks there are syntax errors.
Expected: parse correctly.

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.92GB (39.86GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by mjbvz** [comment]
Nevermind on that `caused-by-extension`, this is a  grammar issue. 

We pull in our c/c++ grammar from [here](https://github.com/atom/language-c/issues). Please file this issue upstream
