### ISSUE TITLE
Add SpeedyCGI syntax support (map speedy to perl)

### ISSUE THREAD

**Issue by demasu** [Microsoft/vscode#60816]
Issue Type: <b>Feature Request</b>

Hey,

Since [SpeedyCGI](http://www.daemoninc.com/SpeedyCGI/) is a decently used caching utility for Perl scripts running on a web server, I would like to have Visual Studio Code set the correct syntax when opening Perl scripts using SpeedyCGI.

Currently, this can be arranged if the file in question has a file extension that is specific to SpeedyCGI files, but if that's not the case, it loads up as plain text.

With Perl scripts that use SpeedyCGI, the shebang line contains the word "speedy" in it. An example from SpeedyCGI's website is:

`#!/usr/bin/speedy
`

However, I know that some companies/organizations/people renamed the binary, or set up a global symlink with a different name, so it would be nice if the check for it would accept something in front of the word speedy. An example of this would be:

`#!/usr/bin/{company}-speedy
`

I found in a [StackOverflow question](https://stackoverflow.com/questions/42498117/vscode-syntax-highlighting-for-custom-shebang) that there's a `firstLine` option in the languages configuration point. However, that point does not seem to be user-editable (at least not in a way that doesn't have the possibility of being overwritten on an update).

Thanks!

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:07:48.477Z)
OS version: Darwin x64 17.7.0

**Comment by egamma** [comment]
This cannot be achived by the end user, but it can be achieved by an extension for the speedy syntax.
