### ISSUE TITLE
Request to join the Microsoft account system can be synchronized to set up and expand

### ISSUE THREAD

**Issue by PanXinYi** [Microsoft/vscode#60824]
Issue Type: <b>Feature Request</b>

I am a developer, every time I install VSCODE on another computer, I need to change a lot of settings and install a lot of expansion, it is more trouble! Request support for Microsoft account login function, synchronize a lot of expansion and settings! Or can support Configuration and extended export, the same experience on the new computer import! VSCODE will be more user-friendly! VSCODE is really easy to use, hope that development will be more and more great!

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 10.0.17763

**Comment by egamma** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/2743
