### ISSUE TITLE
Intellisense and AutoComplete

### ISSUE THREAD

**Issue by Ammat-ALLAH** [Microsoft/vscode#60828]
Issue Type: <b>Bug</b>

Auto fix and Ctrl+. and Ctrl + space is not getting me any suggestion for the import statment for example I typed ICollection to declare a variable and as previously behaviour we type CTRL + . this Auto imports the name space of the collevtion generics , but the actual behaviour was "nothing Suggested"

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (4.08GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
csharpextensions|jch|1.3.0
csharp|ms-|1.15.2
f12-open-file|rex|0.3.1

</details>

**Comment by ctretyak** [comment]
+1

**Comment by egamma** [comment]
What programming language are using when this happens. If it is c# then please file the issue against the c# extension.
