### ISSUE TITLE
When I run the extension, the developer tool pops up and triggers an error

### ISSUE THREAD

**Issue by Anti-Li** [Microsoft/vscode#60820]
Issue Type: <b>Bug</b>

When I run the extension, the developer tool pops up and triggers an error -- it will fire indefinitely after closing until the extended development host is closed.

![image](https://user-images.githubusercontent.com/28052536/46900831-b2ef7f80-cedb-11e8-8a2a-8e267a12543f.png)

[-1539401634965.log](https://github.com/Microsoft/vscode/files/2475038/-1539401634965.log)

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:13:53.910Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.92GB (0.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
csp|Ant|0.0.2
c-cpp-compile-run|dan|0.2.7
githistory|don|0.4.3
tslint|eg2|1.0.40
output-colorizer|IBM|0.1.2
vscode-regexp-preivew|le0|0.0.3
node-module-intellisense|lei|1.5.0
vscode-language-pack-zh-hans|MS-|1.28.2
python|ms-|2018.9.0
cpptools|ms-|0.19.0
csharp|ms-|1.16.2
Go|ms-|0.6.91
notepadplusplus-keybindings|ms-|1.0.2
debugger-for-chrome|msj|4.10.2
vscode-icons|rob|7.27.0
vscodeintellicode|Vis|1.0.4
vscode-todo-highlight|way|1.0.4
markdown-all-in-one|yzh|1.6.2

</details>

**Comment by egamma** [comment]
Can you reproduce this when you have all extension disabled?

Please include the full stack traces. The screenshot does not show the full stack trace and it is therefore not possible to analyze what triggered the exception.

**Comment by Anti-Li** [comment]
> Can you reproduce this when you have all extension disabled?

No, it happen when I debugging my extension.
**BUT IT ONLY HAPPEN in [vscode 1.28.1](https://code.visualstudio.com/updates/v1_28)**

**Comment by Anti-Li** [comment]
Is it similar with a "solved problem" Microsoft/vscode#59114?

**Comment by sanboxrunner** [comment]
Hi, I am also getting this issue in a similar setup to the above (Extension Host, 1.28.2 now tho). A bit more specifically for me, this only triggers when I drag the terminal horizontal size bar down below vscode's lowest boundary. It then reproduces continuously until I shut down the extension host. I don't get that error outside using the extension host, while dragging the terminal in the same manner.

**Comment by Tyriar** [comment]
This was fixed in 1.29 https://github.com/Microsoft/vscode/issues/59114

**Comment by Anti-Li** [comment]
I have also discovered this. Thank you.
