### ISSUE TITLE
Please provide a "Delete Record" button when the path of recent project does not exist.

### ISSUE THREAD

**Issue by andylizf** [microsoft/vscode#60821]
please provide a "Delete Record" button when the "Path does not exist" dialog box pops up in the "Recent" tab of the initial welcome screen

**Comment by prabhu43** [comment]
@Anti-Li Currently when the path does not exists for the recent folder uri, it gets deleted from vscode state. It will not be shown again.

What is actually expected?

**Comment by Anti-Li** [comment]
It doesn't like what you said.

![animation](https://user-images.githubusercontent.com/28052536/47262097-675b5800-d511-11e8-9373-ecc7e425e619.gif)

**Comment by Anti-Li** [comment]
VS Code version: Code - Insiders 1.29.0-insider (45d5d153bbebed743b77e426615aade34971eb46, 2018-10-19T06:58:45.940Z)
OS version: Windows_NT x64 10.0.17134

**Comment by lramos15** [comment]
The open recent list should now be better linked to the getting started screen. So feel free to delete and clear issues there

**Comment by lramos15** [comment]
To verify ensure deleting something from the open recent menu also deletes it from the walkthrough
