### ISSUE TITLE
Make Ctrl-Tab activate last tab on pressing Tab, instead of on releasing Ctrl

### ISSUE THREAD

**Issue by ZYinMD** [Microsoft/vscode#60822]
By default, when using `Ctrl-Tab` to switch tabs, the new tab is activated when `Ctrl` is released.

I'd like to have Sublime Text's way, where the new tab is activated immediately when `Tab` is pressed, then you can keep tabbing to keep switching (without releasing `Ctrl`). 

Sublime Text doesn't show a dropdown, but in VSCode I don't mind whether there's a dropdown or not, as long as the switching is immediate.

This setting is especially good when you only tab once, because for the same cost, the user feels much faster.

#20295 mentions keybindings like this:
```
[
    { "key": "ctrl+tab",         "command": "workbench.action.nextEditor" },
    { "key": "ctrl+shift+tab",   "command": "workbench.action.previousEditor"}
]
```
This isn't the solution, because it changes the order of switching. I like the default behavior (switch to last opened), not the browser behavior (switch to tab on the right).

**Comment by fatcerberus** [comment]
I'm going to agree with this, in editors that support this I'll often find myself using Ctrl+Tab to quickly switch between two tabs when comparing them or e.g. typing something into one file while using another as reference (I greatly dislike split-screen) as I can momentarily pull the other file forward without committing to a distracting focus switch.

**Comment by fatcerberus** [comment]
I don’t think this is a duplicate - that other issue is about Quick Open (i.e. previewing files that are not opened), this is about Ctrl+Tabbing between already-opened files.

**Comment by ZYinMD** [comment]
@bpasero I think you believe it's a duplicate because you're thinking about implementing these two feature requests in the same way, however I believe this one is easier than #8939. We could have something like `workbench.action.recentlyUsedEditor`
