### ISSUE TITLE
Ignore dirs from `Go to symbol in workspace`

### ISSUE THREAD

**Issue by garyking** [Microsoft/vscode#60826]
Please make it possible to ignore directories in `Go to symbol in workspace`. At the moment, results are returned from the `client/node_modules` dir and subdirs, when I use the command in a file in the `client` dir.

I searched for an existing solution to this, but I was unable to find one.

I also have a `jsconfig.json` file at the project root dir (which also contains another `package.json` and `node_modules`; not sure if I need another one in `client` too), with the following:

```json
{
  "exclude": [
    "**/node_modules"
  ]
}
```

**Comment by mjbvz** [comment]
I can't repo this in a simple project. Can you please try opening one of the files under `client/node_modules` that is returned in the search results and then running the `TypeScript: Go to project configuration` command from the command palette. Does this open a jsconfig?

**Comment by garyking** [comment]
Weird, I can't reproduce this too, now. Feel free to close this issue if necessary. Otherwise, I'll report back if it happens again, with repro steps.

**Comment by mjbvz** [comment]
Ok, let me know if you see this again
