### ISSUE TITLE
Open corresponding markdown file when click its link in preview mode

### ISSUE THREAD

**Issue by changkun** [Microsoft/vscode#60836]
## Motivation

1.28 introduces a feature that allows markdown preview mode opens a markdown link directly in preview mode.

However, there are few constraints:

1. There is no navigation if a user performs multiple clicks, it is not possible getting back to an intermediate state.
2. It is impossible to open multiple markdown preview window panel simultaneously.

## Feature request

1. If a user only opens single markdown preview window, directly navigates clickstream
2. If a user opens two window panel side by side, the source on the left and preview on the right， open the corresponding source file on the left and preview it on the right, vice versa.
3. If a user clicks a markdown link on the left (source), open a **new** preview window on the right.

**Comment by changkun** [comment]
@vscodebot

No, the feature request is not duplicated with any others.

**Comment by mjbvz** [comment]
Having a single markdown preview is by-design, see: https://code.visualstudio.com/Docs/languages/markdown#_dynamic-previews-and-preview-locking

You can lock the preview to a single file to allow multiple previews to be open in the same editor group

**Comment by changkun** [comment]
@mjbvz 

Please carefully read the motivations above.

This is not a requirement regarding locking the preview, besides it remains a single window of preview mode and no navigations when clicking a link in the preview window.

**Comment by changkun** [comment]
@mjbvz  ping

**Comment by changkun** [comment]
@mjbvz ping

**Comment by changkun** [comment]
@mjbvz ping
