### ISSUE TITLE
Better IntelliSense for TypeScript/JavaScript

### ISSUE THREAD

**Issue by donaldpipowitch** [Microsoft/vscode#6083]
- VSCode Version: 1.0.0
- OS Version: OS X 10.11.4

I think IntelliSense could show more documentation than it currently does. Take the following example (concrete feature requests are marked with a leading "❤️"):

```typescript
/**
 * Add numbers!
 * @param a First number.
 * @param b Second number.
 */
function add(a: number, b: number): number {
  return a + b;
}

/**
 * This is a.
 */
const a = 1;

const c = add(a, 2);

/**
 * This is some object.
 */
interface SomeObject {
  /**
   * This is foo.
   */
  foo: string;
  /**
   * This is bar.
   */
  bar: string;
}

/*
 * This is an instance of some object.
 */
const someObject: SomeObject = {
  /**
   * Test.
   */
  foo: 'foo',
  bar: 'bar'
};

const foo2 = someObject.foo;
```

And now let us step through each statement and look if it could be improved.

**1. Function signature**

```typescript
function add(a: number, b: number): number {
```

- Hovering over `add` shows `Add numbers!`. 
- Hovering over `a` shows `First number.`.
- Hovering over `b` shows `Second number.`.

Great. Everything works 👍 

**2. Function body**

```typescript
  return a + b;
```

- Hovering over `a` shows `First number.`.
- Hovering over `b` shows `Second number.`.

Great. Everything works 👍 

**3. Variable declaration**

```typescript
const a = 1;
```

- Hovering over `a` shows `This is a.`.

Great. Everything works 👍 

**4. Function call**

```typescript
const c = add(a, 2);
```

- Hovering over `c` shows nothing.
  - This is expected. We have no description like for `const a`.
  - ❓ However... it doesn't seem we can document return values from a function call properly. Adding `* @return This is the sum.` to the `function add` documentation shows the return annotation as part of the description. But it would be nice, if hovering over `c` would show `This is the sum.` instead.
  - If we'd add a description to `const c` like we did for `const a` (e.g. `This is c.`) _and_ we add a proper `@return` annotation to `function add` it would be nice if IntelliSense would show _both_ description when hovering over `c`: `This is c.` and `This is the sum.` (maybe with a small visual delimiter between both descriptions.).
- Hovering over `add` shows `Add numbers!`.
- Hovering over `a` shows `This is a.`.
  - It would be nice, if it would also show `First number.`.
- Hovering over `2` shows nothing.
  - It would be nice, if it would show `Second number.`.

❤️  **Request 1**: It would be nice to show `@return` annotations correctly in IntelliSense.
❤️  **Request 2**: It would be nice to _additionally_ show `@param` and `@return` annotations alongside with descriptions of variable declarations or _at least_  as a fallback, if a variable has no _own_ description.

**5. Interface**

```typescript
interface SomeObject {
```

- Hovering over `SomeObject` shows `This is some object.`.

Great. Everything works 👍 

**6. Property in interface**

```typescript
  foo: string;
```

- Hovering over `foo` shows `This is foo.`.

Great. Everything works 👍 

**7. Object with interface**

```typescript
const someObject: SomeObject = {
```

- Hovering over `someObject` shows nothing.
  - I'd expect to see `This is an instance of some object.`.
- Hovering over `SomeObject` shows `This is some object.`.

❤️  **Request 3**: It would be nice to show the description of an object using an interface.

**8. Properties of an object with interface**

```typescript
  foo: 'foo',
  bar: 'bar'
```

- Hovering over `foo` shows `Test.`.
  - It could also show `This is foo.`.
- Hovering over `bar` shows nothing.
  - It could at least show `This is bar.`.

❤️  **Request 4**: It would be nice to _additionally_ show property descriptions from an interface _and_ descriptions of properties in a concrete object or _at least_  as a fallback, if the property of an object has no _own_ description.

**9. Using properties of an object with interface**

```typescript
const foo2 = someObject.foo;
```

- Hovering over `foo` shows `This is foo.`.
  - It could also show `Test.`. (💡 This was very surprising for me that IntelliSense used `This is foo.` instead of `Test.` here. However... best thing would be to show both.)
- Hovering over `foo2` shows nothing.
  - It looks like the the type is correctly inferred and it would be nice if the descriptions could be reused here, too. (E.g. `Test.` and `This is foo.`)
- Hovering over `someObject` shows nothing.
  - It should show `This is an instance of some object.` (and could additionally show `This is some object.`).

❤️  **Request 5**: When using properties of an object which are documented in the object itself _and_ in the interface it would be nice if the description from the object declaration could be shown (because it is probably more custom to the current use case) _or_ show both descriptions.
❤️  **Request 6**: When types can be inferred it would be nice to infer descriptions, too.

**Comment by rozzzly** [comment]
I'd like to see the hover tooltip get a bit of a makeover. I've been playing around with the extension api, but hover providers are pretty limited. It would be awesome if you could pass html, not just a `MarkedString`. I'm imagining hovering over a function and seeing a table of its params like you would see in online documentation, that be great. But at the very least.. recognise some more of the jsdoc tags. Anything besides `@param` and `@returns` are not picked up and just jumble up into a single line.

![fail](http://i.imgur.com/7AE5kMr.jpg)

Here are a few more things on my wishlist: `@see` autocompletion and click-to-follow keep jsdocs on imports, optionally allow for seperate descriptions on a constructor and a class definition
<sub><kbd>foo.ts</kbd></sub>
```typescript
/**
 * some text
 * @class Derp
 */
export class Derp {
    /**
     * builds a new Derp
     * @constructor
     * @param {string} name - the name of the person
     */
    constructor(name: string) {
        this.name = name;
    }
}
```
<sub><kbd>bar.ts</kbd></sub>
```typescript
import { Derp } from './foo.ts';
     //   ^   hovering shows "some text"

const foobar = new Derp('rozzzly');
                //   ^    hovering shows "builds a new Derp"

if (foobar instanceof Derp) {
                  //   ^   hovering shows "some text"
    // ...
}
```

**Comment by dbaeumer** [comment]
@donaldpipowitch @rozzzly thanks a lot for all the suggestions. I will move the issue to the TS team since VSCode leverage the tsserver to provide TS/JS smartness.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#8525
