### ISSUE TITLE
Language doesn't change after reload.

### ISSUE THREAD

**Issue by zwuis** [Microsoft/vscode#60834]
Issue Type: <b>Bug</b>

Steps to Reproduce:
1. Go to Extension Marketplace.
2. Install  Chinese (Simplified) Language Pack for Visual Studio Code .
3. Click "Reload to Activate".
4. VSCode still display English.
5. Close VSCode, and open it again. It display Chinese.

(should use Chinese language pack in Windows first)
Sry for my bad English.

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:15:15.139Z)
OS version: Windows_NT ia32 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G2020 @ 2.90GHz (2 x 2893)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.41GB (1.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.60
vsc-material-theme|Equ|2.4.2
code-runner|for|0.9.4
vscode-language-pack-zh-hans|MS-|1.28.2
cpptools|ms-|0.19.0
debugger-for-edge|msj|1.0.6
color-highlight|nau|2.3.0
indent-rainbow|ode|7.2.4
vscode-icons|rob|7.27.0
trailing-spaces|sha|0.2.11

(2 theme extensions excluded)

</details>

**Comment by jeangovil** [comment]
@zwuis Just press `Ctrl+Shift+P`, then type `Configure Display Language`. It will open the file `locale.json`. All you need is to change `locale` value to `zh-cn`.

**Comment by jeangovil** [comment]
@zwuis You need to reload the vscode after installing any extension. So this extension you've installed gets the locale from `locale.json` config file(You can access it with command: `Configure Display Language`). After the first time you reload the vscode, extension gets activated. Then it's able to change `locale.json`. When you change that file, you need to reload the vscode again. So this is not a bug. You can install the extension, then change the locale value in `locale.json` by yourself and then reload the vscode.

**Comment by dbaeumer** [comment]
@jeangovil thanks for the clarification which is correct.

@sandy081 could we display a different label in this case to make it more clear. If not feel free to close.

**Comment by sandy081** [comment]
I think Reload action does not makes sense for Localisation extensions. Hence removed it. 

I think if an action is needed then it should activate the language and restart VS Code.

**Comment by sandy081** [comment]
@ramya-rao-a Not sure if `Reload to Activate` is right word even for other extensions because an extension can be not activated even after reload as the activation happens through some events.

**Comment by dbaeumer** [comment]
@sandy081 thanks!

**Comment by ramya-rao-a** [comment]
@sandy081 #60053 is tracking the need to change the `Reload to Deactivate` text.

Going by the same arguments there, we can also change `Reload to Activate` to `Reload to finish install`.
Thoughts?
