### ISSUE TITLE
can't start vscode x64 version in win7 x64, but x86 can.

### ISSUE THREAD

**Issue by vimtt** [Microsoft/vscode#60832]
Issue Type: <b>Bug</b>

just start vscode by double click the Code.exe.

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-04T16:47:36.731Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3 CPU       M 380  @ 2.53GHz (4 x 2527)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.87GB (0.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eclipse-keybindings|alp|0.9.8
vscode-eslint|dba|1.6.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
svn-scm|joh|1.43.0
vscode-language-pack-zh-hans|MS-|1.28.2
debugger-for-chrome|msj|4.10.2
vscode-docker|Pet|0.3.1
LiveServer|rit|5.1.1

</details>

**Comment by Tyriar** [comment]
You're not meant to be able to start the 64 bit version on 32 bit Windows.

**Comment by vimtt** [comment]
I mean that it can't start the 64 bit version of vscode on 64 bit Windows 7, but the 32 bit version of vscode can start on 64 bit Windows 7.

**Comment by vimtt** [comment]
The version of x64 windows 7  is recognized as Windows_NT ia32 6.1.7601 but x64 windows 10 Windows_NT x64 10.0.17134, but I don't know why.

**Comment by Tyriar** [comment]
Try running `code --verbose` on the 64-bit version  and see what the output is.

**Comment by vimtt** [comment]
I just ran `code --verbose`, but nothing happened.I think the code recognizes the windows as x86 arch, so nothing to start. And I noticed that sombody else also encounterd similar situations.
![image](https://user-images.githubusercontent.com/3397136/47164239-3d940c80-d32a-11e8-91b0-d8d73cbc8260.png)

**Comment by vimtt** [comment]
when I use the depends.exe to display the dependences of Code.exe, just show the error info below:
![image](https://user-images.githubusercontent.com/3397136/47264298-9e982c00-d546-11e8-845d-68621bb0fc36.png)
