### ISSUE TITLE
auto save conflict with windows 10 onedrive auto save

### ISSUE THREAD

**Issue by cloudeal** [Microsoft/vscode#60830]
Issue Type: <b>Bug</b>

I put my project in "Onedrive/My Document" folder,and i enable onedrive auto save;Also,I enable vscode auto save my project,so sometime vscode popup an error of auto save failed(I think the reason is onedrive lock the file.)

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:13:53.910Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (2.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-css-formatter|aes|1.0.1
Bookmarks|ale|9.1.0
expressjs|ama|2.0.0
vscode-eslint|dba|1.6.0
gitlens|eam|8.5.6
node-module-intellisense|lei|1.5.0
vscode-jade-snippets|mrm|1.0.1
vscode-pugbeautify|mrm|1.0.2
vscode-language-pack-zh-hans|MS-|1.28.2
python|ms-|2018.9.0
Go|ms-|0.6.91
debugger-for-chrome|msj|4.10.2
vetur|oct|0.13.0
LiveServer|rit|5.1.1
code-settings-sync|Sha|3.1.2

(2 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
This sounds like an issue you should report to OneDrive.
