### ISSUE TITLE
WChar support in terminal when edingting

### ISSUE THREAD

**Issue by liwangqian** [Microsoft/vscode#60838]
When editing widechar in the terminal, delete or navigate a character needs to type keyboard twice, this is not user friendly. For example：
![terminal](https://user-images.githubusercontent.com/19996314/46905452-92004c00-cf26-11e8-876a-723865df4dc2.gif)

**Comment by liwangqian** [comment]
While using the original terminal dose not has this problem.
![terminal1](https://user-images.githubusercontent.com/19996314/46905522-82cdce00-cf27-11e8-97a1-07755260e6ab.gif)

**Comment by Anti-Li** [comment]
I test in Windows and found that this problem only exists in **(MinGW)bash**, and doesn't exist in Powershell or cmd.

**Comment by tonny-zhang** [comment]
@liwangqian 
This can help you https://github.com/Microsoft/vscode/issues/60717

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
