### ISSUE TITLE
terminal: when started, initially invisible user/pc name and the path we are in

### ISSUE THREAD

**Issue by pgrycz** [Microsoft/vscode#60839]
- VSCode Version:  official 1.28.1 (user setup)
- OS Version: Windows 10 64bit home

Steps to Reproduce:

1. changed terminal.integrated.shell.windows from git bash to windows powershell (everything ok after this switch)
2. changed terminal.integrated.shell.windows from windows powershell to windows bash (issue, failed like bash.exe file doesn't exist)
3. changed terminal.integrated.shell.windows from failed windows bash to windows cmd (issue occures at this point even after vscode restart)
3. changed terminal.integrated.shell.windows from issued windows cmd to windows powershell (issue occures at this point even after vscode restart)
4. changed terminal.integrated.shell.windows from issued windows powershell to git bash (everything ok after this switch as initially it worked)

Does this issue occur when all extensions are disabled?: Yes

**Comment by KaneGreen** [comment]
I met the same problem, even I never changed `terminal.integrated.shell.windows` -- I always use PowerShell.
I need to type something to show the prompt (like `PS C:\working_dir\>`)

![Screenshot](https://user-images.githubusercontent.com/20700283/46913624-75feb800-cfc3-11e8-97c5-5795d0657965.png)

```
Version: 1.28.1 (user setup)
Commit: 3368db6750222d319c851f6d90eb619d886e08f5
Date: 2018-10-11T18:13:53.910Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

**Comment by TheGrimSilence** [comment]
Same here it's pretty frustrating.

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/57803
