### ISSUE TITLE
VS Code is freezes when typing code

### ISSUE THREAD

**Issue by infinity7592** [Microsoft/vscode#60846]
Issue Type: <b>Bug</b>

This software is constantly freezing.
What a hell !
Nobody is testing the app before release ????

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.87GB (4.55GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|60%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.12
beautify|Hoo|1.4.4
python|ms-|2018.7.1
cpptools|ms-|0.19.0
debugger-for-chrome|msj|4.10.2

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
@infinity7592 please update to 1.28 and see if it's still a problem, you're on a 3 month old build.
