### ISSUE TITLE
Terminal: A right click paste what you have in your clipboard.

### ISSUE THREAD

**Issue by christalk** [Microsoft/vscode#60843]
- VSCode Version: 1.28.1
- OS Version: Windows10   1809   64 bits

Steps to Reproduce:
Terminal : 
A right click sticks what you have in your clipboard.

Does this issue occur when all extensions are disabled?: Yes

**Comment by usernamehw** [comment]
Settings => `"terminal.integrated.rightClickBehavior": "default",`

**Comment by christalk** [comment]
It works _how it is expected to work_ with the "default" value.
"Show the context Menu"
Thank you.

**Comment by Tyriar** [comment]
@christalk it was designed to work the same as conhost which is also the way other popular terminals work like cmder.
