### ISSUE TITLE
Typescript class field types don't have the 'type' class

### ISSUE THREAD

**Issue by Aarilight** [Microsoft/vscode#6084]
- VSCode Version: 1.0.0
- OS Version: Windows 10

Steps to Reproduce:

1. ![](http://puu.sh/oFFik/dfd047fab7.png)
2. ![](http://puu.sh/oFFwh/edc55d6ba5.png)

The typescript syntax server doesn't give class field types the `type` class, and the colon and type are not split apart as they are for other types. Because of this, there is not currently a way to style them with other types.

(For reference, this is the scope that I'm using to colour the other locations of types: `type.cover, type.name - variable, type.operator - variable, type.square, type.support`)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#160
