### ISSUE TITLE
Extension

### ISSUE THREAD

**Issue by haniraza18** [Microsoft/vscode#60842]
Issue Type: <b>Bug</b>

I cannot add any extensions into my visual code. i want to add bootstrap3 extension in my visual code. 

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:13:53.910Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|3.92GB (1.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

</details>Extensions: none

**Comment by egamma** [comment]
Do you get any error message? 
I suspect you are behind a proxy, please see https://code.visualstudio.com/docs/setup/network#_proxy-server-support
