### ISSUE TITLE
Scrolling with middle mouse + trackpoint is extremely difficult

### ISSUE THREAD

**Issue by bliden** [microsoft/vscode#60841]
- VSCode Version: 1.28.1
- OS Version: Windows 7 Ultimate 64 bit
- Computer: Thinkpad W520
- Synaptics Driver: 16.2.19.14

Steps to Reproduce:

1. Create or open text file long enough to require a vertical scrollbar
2. Using a trackpoint, hover the cursor over the text, hold the middle mouse button, and direct the trackpoint down.

Does this issue occur when all extensions are disabled?: Yes

-----

I first noticed this issue when installing VS Code on my Windows 7 machine. It has not been an issue on the same machine using the linux build.

Scrolling works as expected in other programs like Firefox, terminals, etc. When scrolling using the trackpoint (pointing stick) and middle mouse button in VS Code, the document will move jerkily the first second, and then stop scrolling. The document may scroll a few pixels a second, it is very difficult to move. 

Bumping "editor.mouseWheelScrollSensitivity" to 50 (or greater) does give some movement. I tried some of the solutions for scrolling with a Dell Precision touchpad (window.smoothScrollingWorkaround, and changing window size), but they had no effect.

I've noted others reporting similar behavior [here](https://github.com/Microsoft/vscode/issues/15211#issuecomment-399334329) and [here](https://github.com/Microsoft/vscode/issues/15211#issuecomment-401422331).

Additionally, scrolling using two fingers on the touchpad works completely fine.

Please let me know if I can submit a performance profile or otherwise. VS Code has given me so much, I'm happy to help in any way I can.

**Comment by alexandrudima** [comment]
I don't think there is anything we can do on our side. We react to `mousewheel` events as they come in. We've added the `editor.mouseWheelScrollSensitivity` which helps in speeding or slowing things down, but there is nothing we can do if we are not receiving those events or if they are arriving in some weird way.

AFAIK, trackpads / trackpoints generate mouse wheel events. Sometimes, I have heard that the drivers might generate different events based on the current focused window (i.e. they might send different events to different applications).

My only recommendation is to try to reproduce this issue in Chrome. The same source code (for handling mousewheel events) runs at https://microsoft.github.io/monaco-editor/ . If you can reproduce there, perhaps you can search for or create a new issue against Chromium, especially if things work as expected in other browsers. But, it might turn out to be a driver issue...

**Comment by bliden** [comment]
Right, i understand. I haven't had a similar issue with Chrome, although I do see some other related issues on the Chromium issue tracker. 

VS Code was previously working fine on the same machine with Windows 10. Perhaps there was a new driver version issued through Windows Update that's not on the manufacturer site.

Thanks for the reply, I'll try and do some more investigating.

**Comment by bluppfisk** [comment]
This is actually a regression I noticed since I updated today from 1.28 to 1.32. It seems like some programs (VS Code included) keep receiving scroll events even after the user has let go of either middle button or the touchstick. The lag is the document still responding to those events.

But it should be noted that this behaviour did not exist in 1.28.

**Comment by bluppfisk** [comment]
I want to add that I have alleviated the issue by going into my Thinkpad Touchpad's Advanced options and switching from "Traditional" (i.e. smooth) scrolling to "Standard" scrolling. It doesn't seem to scroll quite as satisfyingly as before, but at least the strange lag is gone.
