### ISSUE TITLE
When hitting f2 key it doesn't replace the word in the comments

### ISSUE THREAD

**Issue by tifDev** [Microsoft/vscode#60849]
- VSCode Version: 1.27.2
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1.Hit f2
2.Write the new name
3.Hit enter

And will see that it doesn't replace in the comments.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by egamma** [comment]
The rename is a semantic rename and it there fore only renames symbol references and not the matches in comments.
