### ISSUE TITLE
Launch VSCode via PYTHONBREAKPOINT and Python 3.7's breakpoint() function.

### ISSUE THREAD

**Issue by mingwandroid** [Microsoft/vscode#60853]
In my workflow I am used to inserting `import pdb; pdb.set_trace()` to break into a fairly minimal CLI debugger. How awesome would it be instead if I could launch into VSCode with as much debugging context available as possible?

I think it would be very nice indeed.

CC @zooba.

**Comment by isidorn** [comment]
Thanks for the suggestion, however this is not on our current road map and will not be tackled in the forceable future.

**Comment by mingwandroid** [comment]
This is disappointing. For my workflow (and I suspect many others') this would be a killer feature (next to being able to launch code with a filename to open from the command-line), suggestion to fix that:

```
cat /usr/local/bin/code
#!/usr/bin/env bash

# open /Applications/Visual\ Studio\ Code.app $*
/Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron $*
```
