### ISSUE TITLE
Repl: reveal on error or reduce minimal height

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#6085]
My use case is to run tests within VS Code and be notified when tests break. For this I have the repl always visible below the editor. I find the minimal height of the repl to be quite large, it could be smaller, maybe small enough that I only see 1 line of output (= the test result).

Alternatively it would be cool if the repl would only show if my test run failed. In other words, if the process spawned exits with non zero exit code, reveal the repl (provided as option).

![image](https://cloud.githubusercontent.com/assets/900690/15007154/ef624386-11d6-11e6-972a-965b439d4c26.png)

**Comment by bpasero** [comment]
Or maybe we have a configuration in launch.json that forces the repl to show up when you run? I am fine to  close it manually afterwards.

**Comment by isidorn** [comment]
For this issue I reduced the minimal height.

For showing the repl when there are errors I will look into by addressing #5870
Configuration to force replShow will look into by addressin #5889
