### ISSUE TITLE
VSCode is not saving any file nor exiting IDE after updated to v1.28.1

### ISSUE THREAD

**Issue by Coffeer** [Microsoft/vscode#60859]
After accepting suggested update to version 1.28.1, VSCode is no longer saving any files. However, changes are shown on filles untill  IDE is restarted.

VSCode is no longer closing down / Exiting either using the close icon, or by exit option from the menu. The only way to exit VSCode is killing it's process through Windows Task manager.

Uninstalling, Reinstalling or Downgrading to the previous version didn't solve the problem.

**Comment by egamma** [comment]
Can you illustrate the problem you are having with screen shots or provide more details.

>However, changes are shown on filles untill IDE is restarted.

Can you please elaborate where changes are shown?
