### ISSUE TITLE
Autocomplete is autocompleting base64 gibberish

### ISSUE THREAD

**Issue by DrJosh9000** [Microsoft/vscode#60857]
Issue Type: <b>Bug</b>
![screenshot 2018-10-14 at 10 11 14](https://user-images.githubusercontent.com/2398124/46910932-0f18d900-cf9a-11e8-8c3b-84dfd4b4e676.png)

No idea how to reproduce, it just started doing it this morning.
This is a very simple Go program for App Engine and using Protobufs.

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:09:20.566Z)
OS version: Linux x64 4.14.67-07156-gc116f2c8c400

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|06/8e (4 x 1607)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|1, 0, 0|
|Memory (System)|4.84GB (3.48GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
Go|ms-|0.6.91
vscode-proto3|zxh|0.2.1

(2 theme extensions excluded)

</details>

**Comment by egamma** [comment]
This doesn´t look like a VS Code issue.
