### ISSUE TITLE
Terminal has weird letter spacing

### ISSUE THREAD

**Issue by levistep32** [Microsoft/vscode#60855]
Issue Type: <b>Bug</b>

Open VS Code and look at terminal. The letter spacing is too wide.

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:52:58.945Z)
OS version: Linux x64 3.18.0-18125-ge005298cc868

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU  N3160  @ 1.60GHz (4 x 2332)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 3, 2|
|Memory (System)|3.80GB (0.42GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|2.19.0
flutter|Dar|2.19.0
pubspec-assist|jer|0.3.0

</details>

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/35681

We recommend using a monospace font

**Comment by levistep32** [comment]
Changed terminal font, works perfectly. Thanks!
