### ISSUE TITLE
Powershell integrated terminal disaply issue

### ISSUE THREAD

**Issue by kzhui125** [Microsoft/vscode#60866]
Issue Type: <b>Bug</b>

here is windows powershell:
![image](https://user-images.githubusercontent.com/11925432/46912585-08935d00-cfac-11e8-9c9a-857f3f2cefe4.png)

here is VSCode integrated terminal:
![image](https://user-images.githubusercontent.com/11925432/46912590-22cd3b00-cfac-11e8-9c00-98a25f7cb972.png)

here is test.ps1:
[test.ps1.zip](https://github.com/Microsoft/vscode/files/2476089/test.ps1.zip)

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:13:53.910Z)
OS version: Windows_NT x64 10.0.17134

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
