### ISSUE TITLE
Hash mismatch while checking updates

### ISSUE THREAD

**Issue by asiaon123** [Microsoft/vscode#60861]
Issue Type: <b>Bug</b>

Checkou for updates

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3610QM CPU @ 2.30GHz (8 x 2295)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (10.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.20.0
vscode-docker|Pet|0.3.1
vscode-icons|rob|7.27.0

</details>

**Comment by egamma** [comment]
Please provide more information about the issue and provide steps for how to reproduce this issue.

**Comment by asiaon123** [comment]
It's be highly possible that the isp hajacking the request, which caused the downloaded file to be tampered.

**Comment by egamma** [comment]
Closing for now

**Comment by brunolcarlos** [comment]
This update is 404 error
