### ISSUE TITLE
mac - workspace history lost when showing app windows

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#6086]
One of the mission control features in the mac is to rearrange the desktop to only show windows from a certain app. This work with VS Code but until recently I would also see a list of recently opened workspaces at the bottom of the desktop. That allows rapid switching between workspaces and is now gone...

**Comment by bpasero** [comment]
Could be the electron update...

**Comment by bpasero** [comment]
@jrieken do you get the list of workspaces when you right click on the icon in the dock?

**Comment by jrieken** [comment]
nope

**Comment by jrieken** [comment]
computer crashed, restarted, and now they are back. wtf
