### ISSUE TITLE
Debug adapter process has terminated unexpectedly (read error)

### ISSUE THREAD

**Issue by richarddaniel34** [Microsoft/vscode#60864]
Issue Type: <b>Bug</b>

Issue Type: Bug

i can not debug python on vs code
this is msg : Debug adapter process has terminated unexpectedly
thanks for help

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:13:53.910Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU  N2830  @ 2.16GHz (2 x 2167)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.89GB (1.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-es|MS-|1.28.2
python|ms-|2018.9.0

</details>

**Comment by egamma** [comment]
Please file the issue with steps for how to reproduce the issue in the Python extension repository.
