### ISSUE TITLE
Allow html/markdown in displaymessages

### ISSUE THREAD

**Issue by eByte23** [Microsoft/vscode#6087]
Allowing html/markdown in window.show*Message() would be nice.
e.g.

```
vscode.window.showInformationMessage('<strong>Woohoo</strong><i>it</i><p>worked</p>");
```

**Comment by 4mitch** [comment]
Just found some solution here https://github.com/Microsoft/vscode/issues/20595#issuecomment-281099832

**Comment by mjbvz** [comment]
As @4mitch notes, we support some basic formatting like bold or italic in the messages but not html or markdown. I believe this is by design as notifications are limited to a single line
