### ISSUE TITLE
The image of the window appears distorted with last version of VSCode

### ISSUE THREAD

**Issue by JavierFuentes** [microsoft/vscode#60873]
- VSCode Version: 1.28.1
- OS Version: Hackintosh OSX Yosemite 10.10.5

Steps to Reproduce:

1. A clean install of VSCode
2. Open any file with some text and image is distorted in VSCode window

Does this issue occur when all extensions are disabled?: NO

#### Problem
Hi, I just installed the latest stable version of __Visual Studio Code 1.28.1__ completely clean on my __Hackintosh with OSX Yosemite 10.10.5__ and __GeForce GT 230 graphics card__ and the image of the window appears distorted as shown in the attached image.

![system_info](https://user-images.githubusercontent.com/5801847/46914504-04147780-cf9f-11e8-8575-c1cbd55c1c8a.png)

![vs_code_render_chunks](https://user-images.githubusercontent.com/5801847/46914507-0d9ddf80-cf9f-11e8-804d-29f7e883df51.png)

In the past something similar happened to me with Chrome 55 and the technical team told me that the temporary solution could be to disable the __hardware acceleration__ of the rendering through one of the Chrome settings until they solve the problem as it seems that they have already do.

_Is there a similar option in Visual Studio Code to solve this problem?_

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/45498d93166483c2eff886e28f8dab915ae382fc/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/code-exploration_1.28.0-1538127308_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/VSCodeUserSetup-x64-1.28.0-exploration.exe)

**Comment by bpasero** [comment]
@JavierFuentes does it reproduce when you run "code --disable-gpu"?

**Comment by JavierFuentes** [comment]
@bpasero this works OK... but is there any Preference I can switch to make this option permanent?

It is very annoying to launch VS Code from Terminal instead of OS X Docking bar.

Thanks in advance.

**Comment by bpasero** [comment]
@JavierFuentes are you on macOS hardware? Because you said "Hackintosh with OSX Yosemite 10.10.5"

**Comment by JavierFuentes** [comment]
@bpasero no, my hardware is macOS compatible with a __GeForce GT 230 graphics card__ but recently I've been reading about the same issue with original macOS hardware and with some Virtual Machines environments running Windows and Linux, so I think a permanent Preference could be interesting.

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)
