### ISSUE TITLE
Upgrading to the lastest version failed...

### ISSUE THREAD

**Issue by Maledong** [Microsoft/vscode#60876]
VS Code Version：
![error1](https://user-images.githubusercontent.com/40081831/46915503-07c7ee80-cfdf-11e8-814d-5b6401a1ca06.PNG)

OS Version：

![error](https://user-images.githubusercontent.com/40081831/46915518-5b3a3c80-cfdf-11e8-8715-ffb6ecd8494b.PNG)
Windows 10 Professional, with 17134.345 (x86)

Steps to rep：

1）Click the most left corner icon to upgrade my vs.
2）Then an 'Update VS' occurs.
3）After 5~6 seconds, it pops up the error below:

![error](https://user-images.githubusercontent.com/40081831/46915500-01397700-cfdf-11e8-94e4-50ce66dbd7c3.PNG)——The file is in use by another process……

![ierror](https://user-images.githubusercontent.com/40081831/46915534-989eca00-cfdf-11e8-9464-6cb343c6a6e5.PNG)

**Comment by Maledong** [comment]
PS：I've downloaded the System version and it should be the latest one, but why should I still accept the upgrade? And what's the MOST diff between 'User Version' and 'System Version'?

I've also attached the logs for you :)
[ErrorLog.zip](https://github.com/Microsoft/vscode/files/2476286/ErrorLog.zip)

**Comment by joaomoreno** [comment]
Yes, I suggest you switch to the system setup. The big difference is that it will install Code for all users in your system.
