### ISSUE TITLE
editor.acceptSuggestionOnEnter: "off" not working in debugging console

### ISSUE THREAD

**Issue by maple3142** [microsoft/vscode#60877]
Issue Type: <b>Bug</b>

`editor.acceptSuggestionOnEnter: "off"` doesn't work when I type in debugging console.
It still insert `FileList` when I type `files` and hit `enter`.
Video: https://streamable.com/r7zcc

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:15:15.139Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.96GB (8.37GB free)|
|Process Argv|ffmpeg.js.wasm\|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
markdown-checkbox|bie|0.1.1
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
gitignore|cod|0.5.0
vscode-svgviewer|css|1.4.7
vscode-markdownlint|Dav|0.20.0
vscode-eslint|dba|1.6.0
xml|Dot|2.3.2
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.40
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.6.1
vsc-travis-ci-status|fel|1.1.0
code-runner|for|0.9.4
terminal|for|0.0.10
vscode-yarn|gam|1.6.0
vscode-pull-request-github|Git|0.2.1
webpack-snippets|gog|0.0.4
vue-snippets|hol|0.1.9
minify|Hoo|0.3.0
webpack|jer|2.1.0
nearley|kar|1.0.3
vscode-fix-checksums|leh|1.1.0
g-translate|map|0.0.2
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.8
vscode-attrs-sorter|mrm|2.1.0
vscode-jade-snippets|mrm|1.0.1
vscode-language-pack-zh-hant|MS-|1.28.2
python|ms-|2018.9.0
cpptools|ms-|0.19.0
debugger-for-chrome|msj|4.10.2
vetur|oct|0.13.0
material-icon-theme|PKi|3.6.0
polacode|pnp|0.2.2
vscode-graphql|Pri|0.1.5
ejs-language-support|Qas|0.0.1
vscode-yaml|red|0.0.17
LiveServer|rit|5.1.1
background|sha|1.1.19
code-settings-sync|Sha|3.1.2
language-stylus|sys|1.10.0
nativescript-xml-snippets|tsv|1.0.7
quokka-vscode|Wal|1.0.153
swig|zhu|0.0.5
vscode-open-in-github|ziy|1.3.6

</details>

**Comment by isidorn** [comment]
I acknowledge the limiation.
The issue here is that we manually set acceptSuggestionOnEnter: "smart" for the debug console so that when the user inputs the whole match and presses enter it would get immediatly evaluated.

Leaving this open as a feature request.

**Comment by sebnapi** [comment]
### THIS IS SO ANNOYING!

**Comment by johan-boule** [comment]
On a side note, i find the mere existence of the 'enter' shortcut for autocompletion to be a misfeature. There's 'tab' for that. I suppose removing the shortcut altogether is the "solution".

**Comment by Moeyoo** [comment]
This problem is very annoying. I have to press "**space backspace enter**" to skip autocomplete instead of just an "enter" to execute a single command. It makes debug console almost unusable. Please fix this bug.

**Comment by andrewlstewart** [comment]
This is an incredibly frustrating feature of an otherwise great IDE.

**Comment by ivanhernandez13** [comment]
Is this FR still a possibility? From the duped [issue above](https://github.com/microsoft/vscode/issues/97439#issuecomment-626627117) looks like there was an intention to reopen this bug.

**Comment by isidorn** [comment]
Yes, we can reopen. And we might weclome PRs that tackle this.

**Comment by damdaepark** [comment]
Is it fixed now?

**Comment by damdaepark** [comment]
Is it fixed now? It's really annoying.

**Comment by fmhsu** [comment]
Might be a little help until this gets closed: If you change the When Expression of the Keyboards shortcut "Debug:Stop" to "inDebugMode && !inDebugRepl" you can Esc + Enter

> This problem is very annoying. I have to press "**space backspace enter**" to skip autocomplete instead of just an "enter" to execute a single command. It makes debug console almost unusable. Please fix this bug.

**Comment by kyle-mallah** [comment]
This is the most annoying thing. there is editor.acceptSuggestionOnEnter, but no terminal.acceptSuggestionOnEnter or related

**Comment by joshenders** [comment]
Also experiencing this issue. This is quote problematic as others have mentioned because debugging now involves cancelling the autosuggestion before interacting. It's a very frustrating experience.

**Comment by bersbersbers** [comment]
Related: #108439

**Comment by ell1e** [comment]
There is `debug.console.historySuggestions` but for me it doesn't work: https://github.com/microsoft/vscode/issues/110838

Also, as I explained here I think not only are **working** options needed for all these enter-autocompletes scenarios but also the default should be changed throughout the IDE: https://github.com/microsoft/vscode/issues/108536 (to have enter auto-completing default to *off* everywhere, both editor and terminal)

I think the whole situation around auto-complete settings needs an entire rethink. I spend an entire day trying to turn everything off because it's spread out over multiple settings (and I still use auto complete *all the time*, just without the very bad enter-autocompletes shortcut which is an absolute nightmare in languages without line terminators like Python) and it's *still* not fully off due to e.g. this bug/ticket here and maybe me missing more related settings. This should not be my first IDE experience. It is way too hard to get a sane configuration, the defaults need to be better.

**Comment by gabrielhuang** [comment]
please fix!!!

**Comment by isidorn** [comment]
This is fixed now.
Apart from that we introduced `debug.console.acceptSuggestionOnEnter` to control this behaviour.
