### ISSUE TITLE
Add License Badge

### ISSUE THREAD

**Issue by gr8shivam** [Microsoft/vscode#60872]
Add a license badge in README.md

**Comment by egamma** [comment]
We want to keep the number of badges to a reasonable level and a license badge adds minimal value, since the license is easily accessible in the `License.md` file.

Please provide a separate PR that aligns the color of the gitter badge.

**Comment by gr8shivam** [comment]
Hi @egamma, thanks for replying. Opened issue #60902 and PR #60903 for Gitter Badge color.
