### ISSUE TITLE
Search results with regular expression are incorrect

### ISSUE THREAD

**Issue by ToMakeSense** [Microsoft/vscode#60871]
- VSCode Version:1.28.0
- OS Version:windows 7

Steps to Reproduce:

**Searched file example**
```html
target="psplayer">Introduction</a>
target="psplayer">Introduction</a>
target="psplayer">Explore
                                                        the Course Objectives</a>
target="psplayer">Explore
                                                        Functional Groups</a>
target="psplayer">Explore
                                                        the VM and Networking Configuration</a>
target="psplayer">Building
                                                        Your Lab Environment</a>
target="psplayer">What
                                                        This Module Covered</a>

target="psplayer">Install and Configure Domain Controllers</a>
target="psplayer">Introduction</a>
target="psplayer">Explore
                                                        Active Directory Components</a>
target="psplayer">Explore
                                                        Active Directory Components: Domains</a>
target="psplayer">Explore
                                                        Active Directory Components: Forests</a>
target="psplayer">Explore
                                                        Active Directory Components: Sites</a>
```
1. search with: `target="psplayer">[\s\S]{1,}?</a>` only 4 records matched, that is to say, The situation of line breaking cannot be handled well.
![image](https://user-images.githubusercontent.com/6244148/46914283-ffff4e80-cfcc-11e8-9b22-36cb3fe48ed7.png)

2. However the same case works well under sublime, 13 matches are captured
![image](https://user-images.githubusercontent.com/6244148/46914296-35a43780-cfcd-11e8-9065-8b00fd845d6b.png)

**Comment by roblourens** [comment]
Search only operates in multiline mode if the query includes a \n. Only if it does, then \s will match newlines.

**Comment by ToMakeSense** [comment]
@roblourens So, is it possible to handle this case in vscode?

**Comment by ToMakeSense** [comment]
#313 
[proposal-regexp-lookbehind](https://github.com/tc39/proposal-regexp-lookbehind)

**Comment by Simran-B** [comment]
From vscode 1.29 release notes:
> VS Code now supports multiline search! Same as in the editor, a regex search executes in multiline mode only if it contains a \n literal. [...]
> This feature is possible thanks to the work done in the ripgrep tool to implement multiline search. [...]
> It is also now possible to use backreferences and lookahead assertions in regex searches, by setting "search.usePCRE2": true. [...]
> If you are still missing lookbehind assertions, don't worry! That feature is just recently supported by JavaScript and should come to VS Code in a later Electron shell update.

The problem still is that you need a literal `\n` in the search expression to trigger it. A workaround that seems to work in case of `[\S\s]` is to use `[\S\s\n]` instead. Not sure about other situations. It would be helpful if you could use the [flags supported Rust's regex implementation](https://docs.rs/regex/1.0.6/regex/#grouping-and-flags) via ripgrep, e.g. `(?s)...` to let `.` match new lines too etc. However, as long as two regex engines are used (JavaScript to search open files) with different supported features this won't really work.
