### ISSUE TITLE
Focus moves to editor after debug sessions terminates

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#6088]
Steps to Reproduce:

1. open repl
2. run tests in selfhost

=> after tests are finished, focus moves to the editor
=> focus should stay in the repl

**Comment by isidorn** [comment]
It's the focus police 👮
Makes perfect sense -> may to investigate

**Comment by isidorn** [comment]
Ok, we were always setting focus to editor on debug session end. I am not a big fan of this auto focus change, so I removed that. That covers this case
