### ISSUE TITLE
copy/paste/cut not working

### ISSUE THREAD

**Issue by chandu1263** [Microsoft/vscode#60889]
Issue Type: <b>Bug</b>

i downloaded some extensions and copy/paste/cut are not working. I don't know which other shortcuts may not work too

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:09:20.566Z)
OS version: Linux x64 4.15.0-36-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2928)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 6, 6|
|Memory (System)|7.66GB (2.11GB free)|
|Process Argv|code.py|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
code-gnu-global|aus|0.2.2
bracket-pair-colorizer|Coe|1.0.60
vscode-eslint|dba|1.6.0
githistory|don|0.4.3
xml|Dot|2.3.2
gitlens|eam|8.5.6
vscode-html-css|ecm|0.2.0
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.40
vscode-npm-script|eg2|0.3.5
vscode-great-icons|emm|2.1.44
vsc-material-theme|Equ|2.4.2
prettier-vscode|esb|1.6.1
php-debug|fel|1.12.6
php-intellisense|fel|2.3.5
latex-workshop|Jam|5.12.2
vscode-clang|mit|0.2.3
mssql|ms-|1.4.0
python|ms-|2018.9.0
cpptools|ms-|0.19.0
csharp|ms-|1.16.2
PowerShell|ms-|1.9.0
vsliveshare|ms-|0.3.790
material-icon-theme|PKi|3.6.0
java|red|0.32.0
vscode-yaml|red|0.0.17
vscode-icons|rob|7.27.0
python|tht|0.2.3
vscode-java-debug|vsc|0.14.0
vscode-java-test|vsc|0.10.0
vscode-maven|vsc|0.11.1
vim|vsc|0.16.9
vscode-react-native|vsm|0.6.18
JavaScriptSnippets|xab|1.7.1
html-css-class-completion|Zig|1.17.1

</details>

**Comment by chandu1263** [comment]
These are the extensions i downloaded. I don't know what is wrong with
them. Ctrl+C/P/X are not working.
I am new to VSC. So please help me.

**Comment by egamma** [comment]
Can you reproduce this when all the extensions are disabled? See our issue reporting guidelines for how to do this https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions.

**Comment by chandu1263** [comment]
Yes it is working after disabling all the extensions.

**Comment by egamma** [comment]
Then you need to narrow down which extension is causing the problem and file the issue against this extension. There is nothing we can do from the VS Code side, sorry.
