### ISSUE TITLE
Replace deprecated dependency gulp-util 

### ISSUE THREAD

**Issue by prog1dev** [microsoft/vscode#60884]
[`gulp-util`](https://www.npmjs.com/package/gulp-util) has been deprecated. Continuing to use this dependency may prevent the use of vscode with version 4 of Gulp.

The [README.md](https://github.com/gulpjs/gulp-util) lists alternatives for all the components so a simple replacement should be enough.

See:
- https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
- https://github.com/gulpjs/gulp-util/issues/143

**Comment by prog1dev** [comment]
@egamma How does issue is a duplicate of pull request?

**Comment by egamma** [comment]
@prog1dev sorry reopening.
