### ISSUE TITLE
Ctrl+f does not focus settings search bar when it is open (in some situations)

### ISSUE THREAD

**Issue by thernstig** [Microsoft/vscode#60899]
- VSCode Version: 1.28.1 (system setup)
- OS Version: Windows 10 Pro, 1803 (17134.286)

Steps to Reproduce:

1. Open settings
2. Focus the Side Bar
3. Press ctrl+f to search.

This does not focus the settings search bar. It opens the normal search box. However, if you instead have the settings focused, it does focus the settings search bar.

I am _assuming_ this is a bug but I am not sure.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Not sure what you mean,

> It opens the normal search box.

I see ctrl+f have no effect when the side bar is focused which is what I would expect. Do you have some other keybinding defined?

**Comment by thernstig** [comment]
@roblourens I do not have any extra keybinding defined than the defaults for this. I tested it on another machine and it behaved the same there.

I think one reason might be that I have set `"workbench.settings.editor": "json"`

If you try it with that, you might see what I mean. Still, in if the settings.editor is set to 'ui' even in that case I would have thought ctrl+f would move focus to the ui search field.

**Comment by roblourens** [comment]
I see what you're talking about now. But, I think the settings-specific keybindings should only take effect if focus is inside the settings editor. Is that an issue for you?

**Comment by thernstig** [comment]
@roblourens It is not a huge problem of course. I just though that since it does open the normal search, the same reasoning could maybe be applied to that part. Why does it open normal search at all then? Anyhow, not a huge deal but I found it ambigous.
