### ISSUE TITLE
Cannot debug generated vscode extension code

### ISSUE THREAD

**Issue by gayanper** [Microsoft/vscode#60896]
Steps to Reproduce:

1. Create TypeScript extension following the guide https://code.visualstudio.com/docs/extensions/example-hello-world
2. Debug the extension by adding a break point into extension.ts
3. The debug point is not hit.

**Comment by isidorn** [comment]
Thanks for the steps, however it does not preorduce for me.
Can you reproduce with latest vscode insiders https://code.visualstudio.com/insiders/

**Comment by gayanper** [comment]
I tried with insider as well, but still the same, here is a screenshot
![image](https://user-images.githubusercontent.com/7471994/46952469-8c327400-d0a8-11e8-9eb7-7edaed142023.png)

**Comment by gayanper** [comment]
The generated launch.json

```json
{
	"version": "0.2.0",
    "configurations": [
        {
            "name": "Extension",
            "type": "extensionHost",
            "request": "launch",
            "runtimeExecutable": "${execPath}",
            "args": [
                "--extensionDevelopmentPath=${workspaceFolder}"
            ],
            "outFiles": [
                "${workspaceFolder}/out/**/*.js"
            ],
            "preLaunchTask": "npm: watch"
        },
        {
            "name": "Extension Tests",
            "type": "extensionHost",
            "request": "launch",
            "runtimeExecutable": "${execPath}",
            "args": [
                "--extensionDevelopmentPath=${workspaceFolder}",
                "--extensionTestsPath=${workspaceFolder}/out/test"
            ],
            "outFiles": [
                "${workspaceFolder}/out/test/**/*.js"
            ],
            "preLaunchTask": "npm: watch"
        }
    ]
}
```

**Comment by isidorn** [comment]
That is all fine, does it still say it is unverified if you actually activate your extension by running the hello world command in then newly started window

**Comment by gayanper** [comment]
No, invoking the command doesn't work either 😢

**Comment by isidorn** [comment]
Can you please attach a gif showing what you are doing? Thanks
When you invoke the command do you actually see the command being executed? Is there a notification being shown?

**Comment by gayanper** [comment]
Seems like there was a issue with the generated txconfig.json. after copying a txconfig.json from the official vscode example the debug started to work. So i'm closing this issue since there is no issue with vscode.
