### ISSUE TITLE
closePanel command ignored when problems filter text box focused.

### ISSUE THREAD

**Issue by safield** [Microsoft/vscode#60897]
Version: 1.29.0-insider
Commit: f151c46b1783cf4f9a4ca934a85f78846f08688e
Date: 2018-10-11T05:12:53.188Z
Electron: 2.0.11
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Running on Linux Mint 19

Observed Behaviour:
With the problems panel open, and focus applied to the filter text box (ctrl+f default), hitting the mapped keyboard shortcut for _workbench.action.closePanel_, does not close the panel.

Expected Behaviour:
Regardless of where focus is in the panel _workbench.action.closePanel_ should always close it.

**Comment by sandy081** [comment]
@safield I assigned `cmd+j` keybinding to `Close Panel` command and it works even when the focus is in filter text box. Can you please let me know what keybinding are you using?

**Comment by safield** [comment]
I am using shift+esc. I can confirm that other bindings do work to close the panel.

**Comment by sandy081** [comment]
@safield I rebound cmd+j to close panel command.

So you say only `shift+esc` keybinding does not work and other keybindings work for close panel? Can you please see if there are other commands bound to `shift+esc`?

**Comment by safield** [comment]
shift+escape is not mapped to anything else in my user settings.

shift+escape is mapped to quite a few other commands in default settings.

None of those commands stand out as overriding closePanel.

**Comment by sandy081** [comment]
@safield Thanks for confirmation. I could reproduce it. 

Fixed.
