### ISSUE TITLE
Suggestion: Create git branch action in checkout dropdown after typing in new branch name

### ISSUE THREAD

**Issue by lannonbr** [Microsoft/vscode#60895]
When you open the git checkout dropdown and search for a branch that doesn't exist, there is a "Create new branch" and then you have to type the name in again.

I propose an action in the dropdown that if a branch doesn't exist so if I search for "feature/my-new-branch", there will be an item that has the following action:

```
Create "feature/my-new-branch" branch.
```

and when you select it, it would generate the new branch and checkout into it.

**Comment by ParkourKarthik** [comment]
I'd like to pick this up.

**Comment by laphets** [comment]
I suppose that we can't get input from `showQuickPick`. Really tough, do you have an idea? @ParkourKarthik

**Comment by ParkourKarthik** [comment]
@laphets You're right. After going through the flow, I also feel the same.
But, I guess there is a possibility to achieve this with the help of `createQuickPick()`. There we have `value` property under `QuickPick` which posses the filter text.
With that said, we need a proper way of handling the select events of the `QuickPick`. Then, of course, we could pass on the newly typed branch name to the `branch command` by adding an optional param.

**Comment by ParkourKarthik** [comment]
@joaomoreno Could you help us a little?

**Comment by nikhilpsathyanathan** [comment]
createQuickPick()

**Comment by danielcompton** [comment]
I wonder if it would make sense to copy the search term into the next input which asks for the new branch name. Then you can hit 'Enter' to accept the branch name, or type something different if it's not what you want.

Currently it is like this:

<img width="609" alt="screenshot of code 22-11-18 11-59-44 am" src="https://user-images.githubusercontent.com/811954/48872649-eca69500-ee4e-11e8-8ab0-3473b9fcdd1a.png">

<img width="603" alt="screenshot of code 22-11-18 12-00-21 pm" src="https://user-images.githubusercontent.com/811954/48872655-efa18580-ee4e-11e8-997e-379352394d5c.png">

But if you copied the first value into the second, you would see this after you select the "Create new branch" option:

<img width="606" alt="screenshot of code 22-11-18 12-06-57 pm" src="https://user-images.githubusercontent.com/811954/48872693-2a0b2280-ee4f-11e8-9499-139ea7edd3b2.png">

**Comment by segevfiner** [comment]
@danielcompton That's also a possibility, and what https://github.com/Microsoft/vscode/pull/63451 actually does when the branch name fails the validation regex from the config. But when it doesn't, it just goes ahead and creates the branch. See the PR description and other comments in this issue.
