### ISSUE TITLE
Errors Compiling from Source on Arch Linux

### ISSUE THREAD

**Issue by fusion809** [Microsoft/vscode#6089]
Hi,

I have been using [this](https://aur.archlinux.org/packages/visual-studio-code-oss) PKGBUILD for building VScode on Arch Linux but whenever it gets to the stage of running `gulp vscode-linux-x64` it returns this error message:

```bash
[21:45:49] Starting 'optimize-vscode'...

<--- Last few GCs --->

122514 ms: Mark-sweep 1086.3 (1434.3) -> 1086.3 (1434.3) MB, 1281.1 / 0 ms [allocation failure] [GC in old space requested].
123780 ms: Mark-sweep 1086.3 (1434.3) -> 1086.3 (1434.3) MB, 1265.8 / 0 ms [allocation failure] [GC in old space requested].
125094 ms: Mark-sweep 1086.3 (1434.3) -> 1086.3 (1434.3) MB, 1314.7 / 0 ms [last resort gc].
126388 ms: Mark-sweep 1086.3 (1434.3) -> 1086.3 (1434.3) MB, 1293.1 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x13bd75fc9fa9 <JS Object>
1: addMapping(aka SourceMapGenerator_addMapping) [/home/fusion809/AUR/visual-studio-code-oss/src/vscode-1.0.0/node_modules/concat-with-sourcemaps/node_modules/source-map/lib/source-map-generator.js:~94] [pc=0x16def244cf1a] (this=0x1638bb806d99 <a SourceMapGenerator with map 0x32765b3f7f41>,aArgs=0x326def047751 <an Object with map 0x1662ab3f8ca9>)
2: /* anonymous */(aka /* anonymous */) ...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
/home/fusion809/AUR/visual-studio-code-oss/PKGBUILD: line 41: 8995 Aborted (core dumped) gulp vscode-linux-${_vscode_arch}
==> ERROR: A failure occurred in build().
Aborting...
```

Changing `gulp vscode-linux-x64` to `gulp vscode-linux-x64 --max_new_space_size=2000000` (in accordance with [this](http://stackoverflow.com/a/26094800/1876983) answer at StackOverflow) makes no difference to this error. Likewise changing `gulp vscode-linux-x64` to `gulp vscode-linux-x64 --max_new_space_size=16000000` makes no difference. So I suspect there is a deeper issue here. 

Thanks for your time,
Brenton

**Comment by bpasero** [comment]
Interestingly I have seen this too on Windows when I try to build VS Code locally. 

@fusion809 what node.js version are you running with?

**Comment by fusion809** [comment]
6.0.0. I should have said I found a solution (see the comments on https://aur.archlinux.org/packages/visual-studio-code-oss/). Namely (changing `gulp vscode-linux-x64` to):

```bash
node --max_old_space_size=2000000 /usr/bin/gulp vscode-linux-x64
```

where the `2000000` can of course be adjusted to how much memory (RAM) you're willing to allocate to this process and `vscode-linux-x64` should be adjusted to match your platform.
