### ISSUE TITLE
Intellisense not working on user custom snippet since vscode 1.2.6 version

### ISSUE THREAD

**Issue by leozhao0709** [Microsoft/vscode#60909]
I defined some snippet with $1, $2, but find since 1.2.6 version, if I trigger my snippet and before finish editing my snippet, there's no intellisense. See the following gif. I append 2 gif which is 1.2.8 vs 1.2.5.

version 1.2.8:

![vscode1 2 8](https://user-images.githubusercontent.com/10889192/46921797-a25f0800-cfb4-11e8-95c3-79c703e37fa0.gif)

version 1.2.5:

![vscode1 2 5](https://user-images.githubusercontent.com/10889192/46921808-b99df580-cfb4-11e8-9e8c-cc09758f3992.gif)

**Comment by leozhao0709** [comment]
This is on mac.

**Comment by jrieken** [comment]
Have this setting: `"editor.suggest.snippetsPreventQuickSuggestions": false`
