### ISSUE TITLE
Markdown previewing a link to a URL containing round brackets (like MS Technet URLs) fails

### ISSUE THREAD

**Issue by corneliu-p1** [Microsoft/vscode#6090]
- VSCode Version:1.0.0
- OS Version: Windows 10 Pro Insider - Build 14328

Steps to Reproduce:

1. In an md file use markdown notation: \[text]\(url) to create a link like 
[SQL Server](https://msdn.microsoft.com/library/mt590198(v=sql.1).aspx)
2. Open md file in page preview mode
3. The link appears broken

**Comment by bpasero** [comment]
This is a bug in our markdown library (marked).

**Comment by bpasero** [comment]
Fixed with our new markdown extension.
