### ISSUE TITLE
Git fails to checkout remote branch with the same name as a local branch

### ISSUE THREAD

**Issue by simpert** [microsoft/vscode#60904]
- VSCode Version: 1.29.0-insider (user setup)
- OS Version: Windows 10 10.0.17134

**more details - entire help entry**
Version: 1.29.0-insider (user setup)
Commit: 931c22033db3cc8d5dff265889307ed4076ac2d3
Date: 2018-10-12T05:17:15.739Z
Electron: 2.0.11
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Steps to Reproduce:

1. open *vscode* with a git controlled folder.
2. from any branch select the scm icon in status bar to checkout a different branch and select origin/master in the command pallette popup while on say develop

Does this issue occur when all extensions are disabled?: Yes/No
Yes

*this is the error I recieve*
![image](https://user-images.githubusercontent.com/2422222/46920227-4e4e2680-cfa8-11e8-92e7-789379560ece.png)

**Here is the git log**
```
> git checkout -q --track origin/master
fatal: A branch named 'master' already exists.
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse develop
> git rev-parse --symbolic-full-name develop@{u}
> git rev-list --left-right develop...refs/remotes/origin/develop
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
```  

I normally do not use the insiders build but I installed it to test this out.

There may be a issue with my git for windows configuration and not vscode.
I recently updated my git for windows install and this problem started after the update.

If I simply execute `git checkout master` then the checkout works as expected it seems the problem only happens when using vscode scm features.

**Comment by jacobherrington** [comment]
Working on this -- PR inbound. :octocat:

**Comment by joaomoreno** [comment]
Issue happens because Code tries to checkout `origin/master`. We should check whether there's a local branch which already has `origin/master` as an upstream and just checkout that branch instead.

**Comment by simpert** [comment]
is there an update on this. my entire office that uses vscode can no longer use built-in git scm if they have updated to latest.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by joaomoreno** [comment]
@skprabhanjan Feel free to just jump on any `help wanted` issue.

**Comment by DavidGerva** [comment]
@joaomoreno I would like to start help with some issue. I found this one but I also see that the PR for the issue #61149 should fix also this but there are conflicts to be solved before merge.

If I'm right, can I do something to help with these issue? I see these issue blocked since a few months...
