### ISSUE TITLE
reviewboard support for review tool

### ISSUE THREAD

**Issue by twk-b** [Microsoft/vscode#60908]
Issue Type: <b>Feature Request</b>

New extension to integrate reviewboard, with the ability to:
* list current review requests
*  submit post request
* update existing review
* patch review to current directroy

https://www.reviewboard.org/

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:07:48.477Z)
OS version: Darwin x64 17.7.0

**Comment by egamma** [comment]
Have you looked at this extension https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github?

Independent of this, such feature should not be provide by the VS Code core but be provide as an extension. I therefore close this issue.
