### ISSUE TITLE
complete functions with their parameter signature for fat arrow functions

### ISSUE THREAD

**Issue by takahser** [microsoft/vscode#60901]
Currently, the settings `useCodeSnippetsOnMethodSuggest`, `javascript.suggest.completeFunctionCalls` and `typescript.suggest.completeFunctionCalls` can be used to complete functions with their parameter signature, when using intellisense.

Unfortunately, this only works for the basic es5 function syntax. It would be nice, if it worked for the es6 fat arrow function syntax as well.

```
// ES5 (settings work)
var multiplyES5 = function(x, y) {
  return x * y;
};

// ES6 (settings don't work)
const multiplyES6 = (x, y) => { return x * y };
```

**Comment by mjbvz** [comment]
As of VS Code 1.31, neither of those cases trigger `javascript.suggest.completeFunctionCalls`. This will however:

```js
function fun(x, y) {
    return x * y;
};
```

All three should work

**Comment by mjbvz** [comment]
Closing this in favor of https://github.com/microsoft/TypeScript/issues/25207

It's not possible for us to fix this reliably on the VS Code side. We really need TS to bring support for this
