### ISSUE TITLE
terminal issue

### ISSUE THREAD

**Issue by BeemenSameh** [Microsoft/vscode#60913]
- VSCode Version: 1.28.1
- OS Version: windows 10 education build 17763.55

when i open terminal "cmd or powershell" and write any thing, it write not in same end line

![image](https://user-images.githubusercontent.com/41084077/46923600-213a5c00-d01a-11e8-8de8-390dbc48b27b.png)

![image](https://user-images.githubusercontent.com/41084077/46923605-37481c80-d01a-11e8-9d1c-0dad737a1b17.png)

Does this issue occur when all extensions are disabled: Yes

**Comment by pyyzcwg2833** [comment]
Yes!!!I have encountered this problem.

VSCode Version: 1.28.1
OS Version: Deepin 15.7
![_ _20181015093059](https://user-images.githubusercontent.com/24390069/46925171-13f29100-d05d-11e8-8686-cfe1d4b973ad.png)

### How to reproduce this problem
1. open terminal in vscode
2. wait about 7 seconds

**Comment by oswee** [comment]
The same there. Latest VS Code and latest Windows. Not sure what invoked this. Almost sure that it happend right after update. Also, when starting terminal, there are no any output (like current directory) and when start to type command it appears somewhere in the middle of the screen. When resizing terminal, everything (in terminal) are glitching.
![vs code glitch](https://user-images.githubusercontent.com/20469200/46940739-1e6b5580-d072-11e8-99fa-390639205181.gif)

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/57803
