### ISSUE TITLE
Using launch.json to do simple tasks (without debug)

### ISSUE THREAD

**Issue by MLefebvreICO** [Microsoft/vscode#6091]
Hi there,
I'm currently looking for a way to remove the `--debug-brk` parameter passed in scripts in `launch.json` as we currently use `launch.json` to execute some gulp tasks instead of real debugging.

We are trying to achieve a VS-like build menu.

Here is our `launch.json` : 

    {
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Build Dev",
			"type": "node",
			"request": "launch",
			"program": "${workspaceRoot}/.vscode/launch_build.js",
			"stopOnEntry": false,
			"args": [],
			"cwd": "${workspaceRoot}",
			"runtimeExecutable": null,
			"runtimeArgs": [
			],
			"env": {
				"NODE_ENV": "development"
			},
			"externalConsole": false,
			"sourceMaps": false,
			"outDir": null
		},
		{
			"name": "Build Release",
			"type": "node",
			"request": "launch",
			"program": "${workspaceRoot}/.vscode/launch_build.js",
			"stopOnEntry": false,
			"args": [],
			"cwd": "${workspaceRoot}",
			"runtimeExecutable": null,
			"runtimeArgs": [
			],
			"env": {
				"NODE_ENV": "production"
			},
			"externalConsole": false,
			"sourceMaps": false,
			"outDir": null
		},
		{
			"name": "------------------",
		},
		{
			"name": "Clean Dev",
			"type": "node",
			"request": "launch",
			"program": "${workspaceRoot}/.vscode/launch_clean.js",
			"stopOnEntry": false,
			"args": [],
			"cwd": "${workspaceRoot}",
			"runtimeExecutable": null,
			"runtimeArgs": [
			],
			"env": {
				"NODE_ENV": "development"
			},
			"externalConsole": false,
			"sourceMaps": false,
			"outDir": null
		},
		{
			"name": "Clean Release",
			"type": "node",
			"request": "launch",
			"program": "${workspaceRoot}/.vscode/launch_clean.js",
			"stopOnEntry": false,
			"args": [],
			"cwd": "${workspaceRoot}",
			"runtimeExecutable": null,
			"runtimeArgs": [
			],
			"env": {
				"NODE_ENV": "production"
			},
			"externalConsole": false,
			"sourceMaps": false,
			"outDir": null
		},
		{
			"name": "------------------",
		},
                {
                        "name": "Tests",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/.vscode/launch_build.js",
            "stopOnEntry": false,
            "args": [],
            "cwd": "${workspaceRoot}",
            "runtimeExecutable": null,
            "runtimeArgs": [
			],
            "env": {
                "NODE_ENV": "test"
            },
            "externalConsole": false,
            "sourceMaps": false,
            "outDir": null
        }
	]
    }

This currently works, but with the `--debug-brk` option passed, it takes some time to fire up the gulp task.

We are launching gulp tasks with `child_process`'s `exec` in a small nodeJS script.

**Comment by bpasero** [comment]
@isidorn is it possible to configure a launch configuration that does not start debug?

**Comment by isidorn** [comment]
@MLefebvreICO @bpasero yes, this should be possible. Please use the debug: start without debugging action. 
![screen shot 2016-05-06 at 09 22 45](https://cloud.githubusercontent.com/assets/1926584/15066777/1f7dd49a-136c-11e6-984c-e5e20401dcc1.png)
