### ISSUE TITLE
Linux code will not start under headless vanilla X11

### ISSUE THREAD

**Issue by gnbond** [Microsoft/vscode#60915]
- VSCode Version: $ code --version
1.27.2
f46c4c469d6e6d8c46f268d1553c5dc4b475840f
x64

- OS Version: Red Hat Enterprise Linux Server release 7.3 (Maipo)

Steps to Reproduce:

1. slogin to RHEL host, set DISPLAY environment variable pointing to mobaXterm server on Windows host.  This X server has it's own integrated window manager.
2. Note that xterm and other "raw" X11 apps work fine.
3. run "code --verbose"

```
[main 11:26:34] Resolving machine identifier...
[main 11:26:34] Resolved machine identifier: 2224e9b825fd9e11bdab87672d9f6cc2278c1cf137ff0d4fa5a7ef84650999e7
[main 11:26:34] update#setState idle
xdg-settings: unknown desktop environment
[main 11:26:34] windowsManager#open
$ 
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/3451

**Comment by gnbond** [comment]
Tyriar,

I do not think this the same issue #3451 .  I've tried the worklarounds there (editing BIG-REQUESTS from libxcb.so.1.... yuk) and get the same response as above:

[main 16:11:31] Resolving machine identifier...
[main 16:11:31] Resolved machine identifier: 2224e9b825fd9e11bdab87672d9f6cc2278c1cf137ff0d4fa5a7ef84650999e7
[main 16:11:31] update#setState idle
xdg-settings: unknown desktop environment
[main 16:11:31] windowsManager#open
