### ISSUE TITLE
HTMLCanvasElement intellisense typo "fillStlye"

### ISSUE THREAD

**Issue by trixrabbit** [Microsoft/vscode#60911]
- VSCode Version: 1.28.1
- OS Version: Windows 10

Steps to Reproduce:

1. Createa a JS file. Create a HTMLCanvasElement : HTMLCanvasElement c = new HTMLCanvasElement();
2. Type : c.fill
3. Suggestions will be c.fillRect and c.fillStlye instead of c.fillStyle

**Comment by emtei** [comment]
I tried to reproduce that on Win10, VSCode 1.28.1 but I failed.

@trixrabbit do you use any additional extensions for intellisense?
I checked TypeScript source code, `fillStyle` is defined [here](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L2898) but spelling is correct.

FYI: @mjbvz

**Comment by mjbvz** [comment]
What framework or library are you using?

**Comment by trixrabbit** [comment]
I wasn't using any library. The problem was actually with the canvas
context => canvas.getContext('2d') but it seems fix now.
