### ISSUE TITLE
Support path alias Rename import path

### ISSUE THREAD

**Issue by rohmanhm** [Microsoft/vscode#60918]
With vscode `1.28` now we have `Rename import path`,
But it doesn't work with path aliases.

I tried to rename path with path alias like below
```ts
import('~/containers/DashboardPage')
```
But it's not allowed me to rename. Only shows some tooltip `An error occured while resolving rename location`

But when I changed to
```ts
import('./containers/DashboardPage')
```
It works well.

Here is my `tsconfig.json` for path settings.
```
"paths": {
  "~/*": ["*"]
}
```

Can you make it works with path aliases as well?

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/Microsoft/TypeScript/issues/27959 to track this upstream
