### ISSUE TITLE
Shift cursor focus back to first group after second is closed without saving

### ISSUE THREAD

**Issue by garyking** [Microsoft/vscode#60925]
- VSCode Version: Version 1.28.1 (1.28.1)
- OS Version: macOS 10.13.6 (17G65)

Steps to Reproduce:

1. Open two groups. In the second one, type something, then close it, then choose `Don't save`.
2. Cursor will not be moved back to the first group. Whereas if you close the second group when its only file has no text, then the cursor moves back to the first group, as it probably should.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Good catch 👍
