### ISSUE TITLE
Add a button of "Stop Code run" on the OUTPUT panel

### ISSUE THREAD

**Issue by laphets** [Microsoft/vscode#60934]
Just like this, sometimes I want to stop some running code, but I had to right click and press "Stop code run" on the right menu (may be hard for some users to find this). But why not just add some button on the top panel, so that I can directly click it. (Just like "Clear Output")

<img width="794" alt="feature" src="https://user-images.githubusercontent.com/12796233/46932648-47e0ad00-d083-11e8-83f1-186eb179c4a5.png">

**Comment by dbaeumer** [comment]
This is possible with the new task system (version 2.0.0) that executes in the terminal. A task can be stop by pressing the garbage bin button there.

We don't have any plans to back port this to the old task runner executing in the Output panel.
