### ISSUE TITLE
View: visibility states are redundant

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#60935]
![image](https://user-images.githubusercontent.com/900690/46933590-f4f00100-d054-11e8-92c7-4ccc4b67def9.png)

@sandy081 please check the local storage usages in [`saveVisibilityStates`](https://github.com/Microsoft/vscode/blob/d68c05c3d93c11d0995888b9d4e68207825819af/src/vs/workbench/browser/parts/views/views.ts#L448) and [`saveViewsStates`](https://github.com/Microsoft/vscode/blob/d68c05c3d93c11d0995888b9d4e68207825819af/src/vs/workbench/browser/parts/views/views.ts#L437)

**Comment by bpasero** [comment]
@sandy081 when fixing it would be great if you could remove the duplicate keys from the object so that we do not migrate these duplicate keys to the new sqlite3 backend.

**Comment by sandy081** [comment]
Sure
