### ISSUE TITLE
command 'PowerShell.RunSelection' not found

### ISSUE THREAD

**Issue by tgburgin** [Microsoft/vscode#60936]
Issue Type: <b>Bug</b>

1. Open VS Code
2. Open .ps1 file
3. Select all code
4. F8

This just returns the "command 'PowerShell.RunSelection' not found" error. I'm sure this used to work.

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:13:53.910Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.96GB (6.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-open-in-sourcetree|mor|0.6.0
mssql|ms-|1.4.0
python|ms-|2018.9.0
csharp|ms-|1.16.2
powershell|ms-|1.9.0

</details>

**Comment by egamma** [comment]
This command is contributed by the powershell extension, please file the issue against this extension.
