### ISSUE TITLE
Move core services from main back into shell

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#6093]
It is bad that we only have it outside shell because we need to initialize it, instead we should load the config and pass it into the shell and construct the config service in there how it used to be.

**Comment by bpasero** [comment]
@joaomoreno cc

**Comment by joaomoreno** [comment]
Another idea would be to make the `get` return a `Promise`. This, to me, would be much cleaner.

**Comment by bpasero** [comment]
So you say making it possible to set a `Promise<IService>` into the collection that gets resolved?

**Comment by jrieken** [comment]
> Another idea would be to make the get return a Promise. This, to me, would be much cleaner.

unsure what that means?

**Comment by joaomoreno** [comment]
Nah. Make the `get` method of the configuration service be async.

**Comment by jrieken** [comment]
You mean this [`get`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/configuration/common/configuration.ts#L20)-method? We only recently made it sync ;-)

**Comment by bpasero** [comment]
Closing (clean up), no plans to work on this.
