### ISSUE TITLE
lose response when terminal print large string

### ISSUE THREAD

**Issue by zjjott** [Microsoft/vscode#60943]
- VSCode Version: 1.18.1
- OS Version:macOS 10.14

Steps to Reproduce:

1. `code --disable-extensions ` open a window
2. using terminal,and just print large string, I have try lua and python script,they all can reproduce

just one line
```python
print("asdqweasd"*10000)
```
Does this issue occur when all extensions are disabled?: Yes/No
Yes

few char will speed up,about 30000 chars,there need 5 seconds to response

**Comment by Tyriar** [comment]
You're on a very old version of vscode, please update before creating issues.

**Comment by zjjott** [comment]
@Tyriar sorry,just typo,it is 1.28.1
