### ISSUE TITLE
Python extension issues about print "\t" after upgrading to version 1.28.1 (1.28.1)

### ISSUE THREAD

**Issue by yinyihui1995** [Microsoft/vscode#60946]
Issue Type: <b>Bug</b>

After upgrading to version 1.28.1 (1.28.1), the number of printed spaces using "\t" when using python expansion has changed from 4 to 8.

code:
```
print("Python")
print("\tPython")
print("Language:\nPython\nC\nJavaScript")
print("Language:\n\tPython\n\tC\n\tJavaScript")
```
<img width="382" alt="2018-10-15 17 01 28" src="https://user-images.githubusercontent.com/32058165/46940718-fb559b80-d09b-11e8-8e97-45e8fcced5c8.png">

display:
```
Python
        Python
Language:
Python
C
JavaScript
Language:
        Python
        C
        JavaScript
```
<img width="132" alt="2018-10-15 16 59 15" src="https://user-images.githubusercontent.com/32058165/46940626-bf223b00-d09b-11e8-945e-1ad3fc3d50d8.png">

Python version: Python 3.7.0
VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:07:48.477Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.28.2
python|ms-|2018.9.0

</details>

**Comment by egamma** [comment]
Please file the issue against the Python extension.
