### ISSUE TITLE
python version problem

### ISSUE THREAD

**Issue by Jasonsupreme** [Microsoft/vscode#60944]
Issue Type: <b>Bug</b>

my preversion is python 3.6.4,then i uninstall it, and install the python 3.7,then, ,the version information is correct in shell,  but it still shows Python 3.6.4 32-bit in the blue color task area(the lower left quarter of the window)

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:13:53.910Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3598)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.94GB (3.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
terminal|for|0.0.10
vscode-language-pack-zh-hans|MS-|1.28.2
python|ms-|2018.9.0
vscode-icons|rob|7.27.0
vim|vsc|0.16.10

</details>

**Comment by egamma** [comment]
Please report the issue against the Python extension.
