### ISSUE TITLE
Should stop sending global settings and keybindings via IPC

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#6094]
Instead we should have a way to instantiate these settings on the renderer side (including watching).

**Comment by bpasero** [comment]
@joaomoreno cc

**Comment by joaomoreno** [comment]
I created the `NodeConfigurationService` which should serve as a stepping stone for this. Any environment with node access should be able to instantiate one of these guys, which listens on changes to the global settings. We then can compose it with another guy which listens on changes to the local workspace settings. Reusability is key here.

**Comment by joaomoreno** [comment]
![louis](https://m.popkey.co/a16137/Y9qx3.gif?c=popkey&p=usa_network&i=suits-ent&l=search&f=.gif)

**Comment by bpasero** [comment]
Louis <3
