### ISSUE TITLE
shift+alt+f 会让没有内容的script标签不断的添加新的空行

### ISSUE THREAD

**Issue by ccfto** [Microsoft/vscode#60942]
Issue Type: <b>Bug</b>

shift+alt+f  会让  
<script type="text/javascript">
 </script> 
</body>
</html>
不断的新增空行

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (3.10GB free)|
|Process Argv|E:\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
solidity-extended|bea|3.0.2
cocos-creator|Chu|0.0.1
cocos-debug|chu|0.0.1
solidity-solhint|idr|1.1.4
solidity|Jua|0.0.46
vscode-language-pack-zh-hans|MS-|1.27.2
mssql|ms-|1.4.0
debugger-for-chrome|msj|4.10.2
bootstrap-3-snippets|wcw|0.1.0

</details>

**Comment by egamma** [comment]
Translation:
Will let the label without content continue to add new blank lines


Constantly adding blank lines

Please provide more detailed steps for how to reproduce the problem. See our issue reporting guidelines  https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions
