### ISSUE TITLE
Allow open different workspaces in different windows simultaneously.

### ISSUE THREAD

**Issue by TheTechOddBug** [Microsoft/vscode#60952]
As title indicate, if you are working in different scenarios, different applications or different configuration sets, it is useful to have the ability of open two different VSCode windows, each one with a different workspace with the setup you need for each case.

**Comment by bpasero** [comment]
Just append the workspace file names to the command line (or even folder names):

`code-insiders ~/Documents/playground.code-workspace ~/Development/vscode.code-workspace`
