### ISSUE TITLE
Can task script support get current line number?

### ISSUE THREAD

**Issue by morland96** [Microsoft/vscode#60950]
Hi, I think let task script know current line number just like it already know current file name would be a nice idea.
Like if I want to open a file in vim, I can do this now.
 {
            "label": "open in vim",
            "type": "shell",
            "command": "vim ${file}",
            "problemMatcher":[]
 }
But it missed file line number info which might helpful for me. Can we have this feature? Or it's there anything I missed to reach this aim.

**Comment by dbaeumer** [comment]
`${lineNumber}` should actually do the trick.
