### ISSUE TITLE
IntelliSense not working when using absolute import paths

### ISSUE THREAD

**Issue by gyosifov** [Microsoft/vscode#60956]
> Version: 1.28.1 (user setup)
> Commit: 3368db6750222d319c851f6d90eb619d886e08f5
> Date: 2018-10-11T18:13:53.910Z
> Electron: 2.0.9
> Chrome: 61.0.3163.100
> Node.js: 8.9.3
> V8: 6.1.534.41
> Architecture: x64

The issue is the same as the one described [here](https://github.com/Microsoft/vscode/issues/19342). 
The workaround in the comments does not seem to work. 
The project is created using [create-react-app](https://github.com/facebook/create-react-app). jsconfig.json is in the same folder as package.json (moving it in the /src directory did not help).

I also have .env file that looks like this:
`NODE_PATH=src`
as suggested [here](https://medium.com/@ktruong008/absolute-imports-with-create-react-app-4338fbca7e3d).

I have tried most of the examples for jsconfig.json  found [here](https://code.visualstudio.com/Docs/languages/javascript#_writing-jsconfigjson).

Does this issue occur when all extensions are disabled?: Yes

Thank you for your time and efforts!

**Comment by mjbvz** [comment]
Please share an example import and your current jsconfig.

**Comment by gyosifov** [comment]
Sure, 

Currently the jsconfig.json is:

```
{
    "compilerOptions": {
        "target": "ES6"
    }
}
```
But I have also tried:
```
{
    "compilerOptions": {
        "target": "ES6"
    },
    "include": [
        "src/**/*"
    ]
}
```
and 
```
{
    "compilerOptions": {
        "module": "es6"
    }
}
```
,
```
{
    "compilerOptions": {
        "module": "system"
    }
}
```

Steps to Reproduce:

1. As an example I use my `actionTypes.js` which has redux action type constants like this:
```
export const START_THING = 'START_THING';
export const START_THING_DONE = 'START_THING_DONE';
```

2. Then when I import them with relative path like this the IntelliSense is working like so:
![2b5dd844-e2e4-11e6-9155-c7cff4b27847](https://user-images.githubusercontent.com/2285468/46998672-eb859800-d12b-11e8-918e-98b035a642b6.png)

3. But if I use absolute import (which is always better choice than relative) then IntelliSense does not pick up constants from actionTypes.js file like so:
![775c87d6-e2e4-11e6-97ee-77b82e4278bd](https://user-images.githubusercontent.com/2285468/46998687-f93b1d80-d12b-11e8-8be5-7c2fb003e1d2.png)

**Also there is no autocomplete when writing the import path.**

**Comment by mjbvz** [comment]
You need to set the `baseUrl`:

```
{
    "compilerOptions": {
        "target": "ES6",
        "baseUrl": "./src"
    }
}
```
