### ISSUE TITLE
Don't show current active editors file in the go to file window (cmd+p)

### ISSUE THREAD

**Issue by LukeDefeo** [Microsoft/vscode#60954]
Im used to using cmd+p to navigate around my workspace. Often I'm bouncing between 2 files. In Intellij for example the similar command (cmd+e)  excludes the currently edited file from the list and the list and the top item is the last edited file.

This allows for a nice workflow improvement where you can just quickly do cmd+p > enter to go the previous file.

Seems like a small change and I guess this could be hidden behind an option for people who like it the current way but I'm pretty sure most intellij converts will appreciate this.

**Comment by bpasero** [comment]
We support this scenario in a nicer way, if you configure this in keybindings:

```json
{ "key": "ctrl+q", "command": "workbench.action.openPreviousEditorFromHistory" },
{ "key": "ctrl+q", "command": "workbench.action.quickOpenNavigateNext", "when": "inQuickOpen" }
```

You can jump between files easily and do not even need a second keyboard invocation. Just release and you are done. Pressing Q multiple times in this case will allow you to select other files. All in all this works like Alt+Tab to switch applications.
