### ISSUE TITLE
Try to put the "debug" toolbar in a place not hiding something else

### ISSUE THREAD

**Issue by apupier** [Microsoft/vscode#60967]
By default, the debug bar is placed in the middle of the screen. It is hiding editor names as soon as there are more than 2 editors opened (depends on screen size)

![image](https://user-images.githubusercontent.com/1105127/46952745-0c96ac00-d08c-11e8-8c4d-ab8e4d336615.png)

even if there are some places on the right. So would be best to place it by default at the top right before the menu toolbar buttons like that:
![image](https://user-images.githubusercontent.com/1105127/46952781-2f28c500-d08c-11e8-9ae0-693716e02b93.png)

or just after the last tab opened (but as soon as another tab will open it will be problematic):
![image](https://user-images.githubusercontent.com/1105127/46952802-3fd93b00-d08c-11e8-838a-ec9f73908f43.png)

or at the top right just below button bars:
![image](https://user-images.githubusercontent.com/1105127/46952827-51bade00-d08c-11e8-863b-b08031975d0c.png)

**Comment by isidorn** [comment]
You can drag it to many of those locations, including your last picture.
Apart from that try using the `debug.toolBarLocation` setting

**Comment by apupier** [comment]
I know that I can drag it to many locations but it is adding one more action to users although the software can be more user friendly and place it in a place they won't have to take an extra action.
What I reported is that the default location used can be largely improved.

**Comment by isidorn** [comment]
Thanks for feedback, but that is user preference. Everyone can change the location, and changing the default might make some people unhappy becuase they got used to the location, becuase they have tabs disabled, it makes it harder to spot and so on...
Thus I will not make this change.

**Comment by apupier** [comment]
> but that is user preference

I don't think that it is user preference, but a usability problem.

> because they have tabs disabled, it makes it harder to spot and so on...

I don't understand which disabled tabs you are talking about.

Anyway, i'm fine if you judge that the usability improvement is not worthy the cost to implement it and the change of the user habits. (I guess one day I will get used to also and stop swearing searching for my editor tab ^^)

**Comment by isidorn** [comment]
You can hide tabs via
`workbench.editor.showTabs: false`

You should just change the position once and it should be preserved across all your workspaces. If that is not the case than it is clearly a bug we should fix.
