### ISSUE TITLE
unresponsive host

### ISSUE THREAD

**Issue by iremuznbz** [Microsoft/vscode#60969]
- Extension Name: debug-auto-launch
- Extension Version: 1.0.0
- OS Version: Linux x64 4.15.0-36-generic
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:

**Comment by iremuznbz** [comment]
```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 1743,
		"activateCallTime": 1,
		"activateResolvedTime": 0,
		"activationEvent": "*"
	}
}
```

**Comment by isidorn** [comment]
This is fixed in latest vscode, we no longer show the notification. Closing
