### ISSUE TITLE
Update: often hits ERR_NETWORK_IO_SUSPENDED

### ISSUE THREAD

**Issue by elieobeid7** [Microsoft/vscode#60966]
I'm using windows 10, vscode 64 bit latest update. I keep getting this notification, I have no idea if it's a bug or not, just letting you know

![capture](https://user-images.githubusercontent.com/660142/46952519-c0e80080-d093-11e8-8e7d-9526bf51ad44.PNG)

**Comment by joaomoreno** [comment]
Are you behind a proxy?

**Comment by joaomoreno** [comment]
Really not sure what this is. Found this related link: https://bugs.chromium.org/p/chromium/issues/detail?id=82407

**Comment by carlocardella** [comment]
I just encountered this error combined with net::ERR_NETWORK_CHANGED: this happened right after I resumed from sleep my laptop at work (I set it to sleep last night at home, of course connected to a different wireless 

![image](https://user-images.githubusercontent.com/5784415/47017523-540e4e00-d107-11e8-925c-2e2660b1bcc0.png)

**Comment by alexweininger** [comment]
The error message 

`net::ERR_NETWORK_IO_SUSPENDED`

`Source: Update Service`

Appears on launch.

![image](https://user-images.githubusercontent.com/12476526/47042258-ab301500-d13f-11e8-810d-86b651021cb1.png)

**Comment by neilsustc** [comment]
Also seeing this for many times, exactly the same error message. No proxy/VPN etc.

One suspicious reason is I usually make my laptop sleep (`win+x`>shut down or sign out>sleep) before I leave. Then when I am back, it is very likely to see this error.

**Comment by vitaminj** [comment]
This error message always happens for me, one notification in every open VSC window, when I wake my work laptop up from sleep. All 1.28.x releases.

**Comment by wolf99** [comment]
I'm seeing this. With 1.28.2 on Windows 10 1809
Maybe related, I'm also seeing the error in #7570, cannot start VS Code without internet connection.

**Comment by bogdan-calapod** [comment]
Also seeing this, Windows 10 1809. What I noticed is that it also shows up when switching workspaces (Ctrl + R)

**Comment by justClouds** [comment]
I experience the "net::ERR_NETWORK_CHANGED - Source: Update Service" issue in VS Code 1.28.2 on Windows 10 1809.
This is not when waking up from sleep, but spontaneous (at least no apparent reason).

**Comment by LordHog** [comment]
I am also seeing this message recently.  I am not sure it is related to the recent VSC update or cpptools update.  I am seeing it both on CentOS and Windows 10 machines.  Behind company fireware, but proxy settings are configured and never had an issue until today.

**Comment by gguidotti** [comment]
I'm having the same issue with my work laptop.
I suspend it every afternoon and once I come back to the office I see the net::ERR_ENTWORK_CHANGED coming up.

**Comment by samiggapps** [comment]
+1

**Comment by bodeC** [comment]
+1

**Comment by Gliptal** [comment]
Same here, no Proxies or VPN. Windows 10 1803 (17134.376). I also mainly hibernate my system.

**Comment by subarugt** [comment]
Happened 1st time to me this morning... also on resume.

Closed VS Code. Disconnected my internet connection. Opened Command Promt. Typed in **ipconfig /flushdns**. Reconnected to internet. Open VS Code. Problem gone.

Hope that also works for others..

**Comment by alexandrudima** [comment]
@joaomoreno I also hit this. The steps are:
- let Windows PC hibernate
- wake up PC
- open a new window or open a folder in the existing window

I don't mind that checking for updates is somehow broken after the resume, but the notifications showing so often are annoying.

![image](https://user-images.githubusercontent.com/5047891/48800211-6c2a4c00-ed09-11e8-92bf-09120760658f.png)

**Comment by JoshuaKGoldberg** [comment]
Copying discussion from #62824:

You know, looking through `src/vs/workbench/parts/update/electron-browser/update.ts`, it looks like this code is made to also handle the case of the user manually requesting an update. In that case, a lack of internet _would_ be an error case.

Maybe the update code paths should keep track (pass through) how the request to update was originated? If it originated from a user action, failures are errors; if not, they should be silent logs.

**Comment by robinlarondelle** [comment]
Getting this error as well, running Windows 1809, Visual Studio Code wont open up w/o internet connection as well... I think this is related

**Comment by elieobeid7** [comment]
@joaomoreno  I just want to say that I received the same problem right now and I have the latest version, no updates available, version 1.29.1.

I don't know if you pushed the update to users or not

https://github.com/Microsoft/vscode/commit/1567e662ccfe9a8e034e6eecb1ac68d5fc754805

 But in case you did update VSCode, then the issue is still not fixed.

**Comment by elieobeid7** [comment]
@usernamehw  Ah thanks for the info!

**Comment by roblourens** [comment]
I see this on Mac:

- Go offline
- Click "Check for updates"
- In devtools:

```
  ERR context is not defined: ReferenceError: context is not defined
    at t.onError (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:347:147)
    at e.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:123:532)
    at AutoUpdater.r (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:129:235)
    at emitTwo (events.js:126:13)
    at AutoUpdater.emit (events.js:214:7)
```

**Comment by roblourens** [comment]
I'll call this verified because I haven't seen random update service errors when offline recently, and code review makes sense. I'll open a new issue for the Mac failure.
