### ISSUE TITLE
SHIFT+ENTER should start a new line and not break the previous

### ISSUE THREAD

**Issue by darijanrijan** [Microsoft/vscode#60964]
I looked for it, but could not find it.

How to reproduce:
* Put cursor in the middle of some text (or at the beginning of a line that has text for that matter)
* Hit SHIFT + ENTER
* **IS**: it breaks the line and moves everything after the cursor to the new line
* **SHOULD**: start a new clean line and do not change the content of the previous line (everything stays up)

This works in Eclipse and IntelliJ and it's super useful.

**Comment by darijanrijan** [comment]
Thanks.

**Comment by isidorn** [comment]
You can customize this in Keyboard shorcuts. Just change it to shit + enter :)

![screen shot 2018-10-15 at 14 53 33](https://user-images.githubusercontent.com/1926584/46952076-1fa87c80-d08a-11e8-9dcf-cf805ae1e7c0.png)

**Comment by darijanrijan** [comment]
Thanks @isidorn !
