### ISSUE TITLE
yarn watch hangs

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#60968]
Running yarn watch on my Windows 10 box often hangs and does not continue:

![image](https://user-images.githubusercontent.com/900690/46953206-7d8a9380-d08d-11e8-9ee2-1be18ece0514.png)

/cc @Microsoft/vscode if someone else saw this too

**Comment by roblourens** [comment]
I saw this error this morning which is new? But just saw it once

```
[09:41:19] Starting 'watch-client'...
TypeError: Class constructor ReportFunc cannot be invoked without 'new'
    at tsb.create.err (/Users/roblou/code/vscode/build/lib/compilation.js:46:57)
    at printDiagnostic (/Users/roblou/code/vscode/node_modules/gulp-tsb/lib/builder.js:45:9)
    at /Users/roblou/code/vscode/node_modules/gulp-tsb/lib/builder.js:218:75
    at Array.forEach (<anonymous>)
    at /Users/roblou/code/vscode/node_modules/gulp-tsb/lib/builder.js:218:45
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
[09:42:46] [monaco.d.ts] Starting monaco.d.ts generation
[09:42:52] [monaco.d.ts] Finished monaco.d.ts generation
```

**Comment by joaomoreno** [comment]
@bpasero Make sure this isn't the usual command prompt waiting for an `Enter` press

**Comment by bpasero** [comment]
I tried many times and got the same result always. Now at home I cannot reproduce...

**Comment by beastdestroyer** [comment]
I got it hanging when I was working on a pull request; I spammed enter a lot and didn't do anything, I had to wait ~5mins for it to continue.

Happens on both Insiders and Exploration, using Windows 10 1803 17134.345 and this process uses roughly 1.5GB+ of RAM. 

I doubt I'm supposed to post here but I experienced this

**Comment by bpasero** [comment]
For me I think it did not continue even after 5 minutes.

**Comment by dbaeumer** [comment]
It doesn't hang for me.

**Comment by bpasero** [comment]
Reproducible for me hangs with high CPU: ![grid-tw](https://user-images.githubusercontent.com/900690/47003201-04437d00-d12f-11e8-8667-08dbb8a2c056.gif)

**Comment by jrieken** [comment]
Looks like the max_old_size argument is accepted for you. The memory doesn't go over 1GB in your gif and I am pretty sure you are now in infinite allocation-gc-cycles. Is that a very new or old version of node?

**Comment by bpasero** [comment]
@jrieken true story, I accidentally installed a 32bit node.js version it seems. This is what we currently need:

![image](https://user-images.githubusercontent.com/900690/47005160-77e78900-d133-11e8-966b-6fe55e3c1477.png)
