### ISSUE TITLE
Clean up BaseRequestService and the one in workbench 

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#6096]
Try to reuse the NodeRequestService as much as possible.

Try to remove the request service that leaves in the workbench.

**Comment by joaomoreno** [comment]
I've created the `NodeRequestService` as a stepping stone for this. It contains much of what the `RequestService` in the `workbench` world has.

We should create a `XHRRequestService` that does requests over XHR and then compose that with the `NodeRequestService` to use within the workbench.

**Comment by joaomoreno** [comment]
Everything is super clean now! 🎆
