### ISSUE TITLE
Font renders weird

### ISSUE THREAD

**Issue by crewone** [Microsoft/vscode#60965]
Issue Type: <b>Bug</b>

After updating to the latest insiders release, this is how the font (blackfont) looks:

![image](https://user-images.githubusercontent.com/2951144/46950399-ddc90780-d084-11e8-9399-c95601d28101.png)

VS Code version: Code - Insiders 1.29.0-insider (628740747496bc1f36c83d70f208b7fd85afc86b, 2018-10-15T05:17:12.673Z)
OS version: Windows_NT ia32 10.0.18252

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590S CPU @ 3.00GHz (4 x 2993)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (7.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
gitkit|alb|0.1.1
Bookmarks|ale|9.1.0
vscode-database|baj|1.5.2
vscode-intelephense-client|bme|0.8.8
gitignore|cod|0.5.0
bracket-pair-colorizer|Coe|1.0.60
vscode-eslint|dba|1.6.0
xml|Dot|2.3.2
gitlens|eam|8.5.6
php-debug|fel|1.12.6
auto-rename-tag|for|0.0.15
mediawiki|jak|2.1.0
php-cs-fixer|jun|0.1.85
vscode-scss|mrm|0.6.2
cpptools|ms-|0.19.0
debugger-for-chrome|msj|4.10.2
php-docblocker|nei|1.6.0
vscode-icons|rob|7.27.0
Align|ste|0.2.0
html-css-class-completion|Zig|1.17.1

(1 theme extensions excluded)

</details>

**Comment by scottymcraig** [comment]
I cannot get this to reproduce in this build.  What theme are you using?

**Comment by crewone** [comment]
Visual studio dark

**Comment by Tyriar** [comment]
Can you share your settings.json file?

**Comment by crewone** [comment]
This is still not fixed. I reduced it to this settings.json:

`
{
    "editor.fontFamily": "source code pro",
    "editor.fontSize": 15
}
`
