### ISSUE TITLE
Allow to use window.withProgress with buttons when shown as notification

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode#60979]
Copied from original issue here by @chrisdias https://github.com/Microsoft/vscode-azureappservice/issues/645

> every time i get this message i want to open the output window:
> 
> ![image](https://user-images.githubusercontent.com/1487073/46909084-c56cb780-cee1-11e8-82f3-38179619e3ec.png)
> 
> it would be nice to have a button on this that would open it.  i think other prompts do this...

The deploy output is way too detailed to put in a notification, but we also don't want to pop up the output channel every time. The notification was a good middle ground, but ideally we would be able to add a "View Output" button.

**Comment by bpasero** [comment]
This is all supported from the workbench but not supported in our extensions API.

/cc @jrieken

**Comment by kizivat** [comment]
So is this not possible? You suggest a link to output in progress notification in your guidelines here: https://code.visualstudio.com/api/references/extension-guidelines#progress-notification

I was hoping to implement the notification same way as shown there.
