### ISSUE TITLE
Arrow left in problems view crashes

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#60972]
Running from master

**Comment by oriash93** [comment]
I am running from master.
I get error notifications when I press ⬅️ on the problems pane.

When the tree is expanded:
![capture1](https://user-images.githubusercontent.com/14019835/47375832-d5fb0a00-d6f9-11e8-9946-4ae7f451f8f0.PNG)

When the tree is collapsed:
![capture2](https://user-images.githubusercontent.com/14019835/47375843-db585480-d6f9-11e8-8629-905b958aa2e8.PNG)
