### ISSUE TITLE
debug adapter telemetry doesn't honour opt-in/out flag

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#6097]
The debug layer offers telemetry services to it's adapters but that code path doesn't honour the user setting to opt out of telemetry.

**Comment by bpasero** [comment]
@isidorn @weinand fyi

**Comment by weinand** [comment]
@isidorn I assume we are using the telemetry API. Is this correct?

@jriekenI I don't think that every client of the telemetry API should have to honor the opt-out setting themself. This would be too error prone. Isn't there a central place in the telemetry API implentation that does this?

**Comment by jrieken** [comment]
@weinand Today there is not such API... The value is stored in the config. I like the idea of API and I will add `ITelemetryService#isOptOut` for that

**Comment by isidorn** [comment]
@jrieken :+1: once we have isOptOut I can use that flag to not send telemetry

**Comment by jrieken** [comment]
@isidorn Done. Note that you must re-read this flag each time you log since it might change during the lifetime of a session

**Comment by weinand** [comment]
@jrieken why is the `this.telemetryService.isOptedIn` check not done inside the `this.telemetryAdapter.log`?
Moving the responsibility of this check to the client looks error prone to me:

```
if (this.telemetryAdapter && this.telemetryService.isOptedIn) {
	this.telemetryAdapter.log(event.body.output, event.body.data);
}
```
What is the use case where a `telemetryAdapter.log()` would not be guarded by a `telemetryService.isOptedIn`?

**Comment by jrieken** [comment]
> Moving the responsibility of this check to the client looks error prone to me:

Yes and when using the actual service it's good, but in the debug error telemetry case the service isn't used but just the shared node lib - which doesn't know about configuration

**Comment by weinand** [comment]
@isidorn is there a way to use the telemetry service instead of the the shared node lib?

**Comment by isidorn** [comment]
@weinand no, we were both discussing this with Sofian far back. Here's the pr https://github.com/Microsoft/vscode/pull/3054 and I forwarded you a mail thread where we were discussing this with Sofian
