### ISSUE TITLE
Pressing Alt to move a line up/down in Fullscreen also pops the menu

### ISSUE THREAD

**Issue by cossio** [Microsoft/vscode#60975]
Pressing Alt to move a line up/down in Fullscreen also pops the menu. This is annoying because it moves the screen up/down erratically. There is a conflict with these keyboard shortcuts here.

**Comment by cossio** [comment]
@rebornix @egamma  The tag editor-autoindent doesn't seem to be correct.

**Comment by rebornix** [comment]
@sbatten I remember the menu can tell whether it's alt or alt+keys ?

**Comment by sbatten** [comment]
@cossio I am unable to reproduce this issue. Do you have specific steps. Here are mine.
1. Open VS Code
2. Ensure menu visibility is set to toggle or default
3. enter fullscreen by hitting F11
4. Open a file
5. Use Alt+Up/Down to move a line.

Expected+Actual => line moves, menu stays hidden

**Comment by cossio** [comment]
Maybe this got fixed in a recent release. I cannot repro any more.
