### ISSUE TITLE
Zooming in or out is affecting custom title bar too.

### ISSUE THREAD

**Issue by Guema** [Microsoft/vscode#60974]
- VSCode Version: 1.28.1
- OS Version: Windows 7 x64

Steps to Reproduce:

1. Zoom in or out
=> Problem : the title bar is affected.

Does this issue occur when all extensions are disabled?: Yes

It's probably not exactly a bug as i suppose it's the default behavior of Chromium zoom.
Perhaps it is working as intended, but, it's making custom title bar design inconsistent with other Windows app, and also with native title-bar mode, maybe on Linux and MacOS too.

In the other hand it certainly can be useful to zoom title-bar from an accessibility perspective. However , maybe it could be more consistent to make the zoom of the title bar managed by the OS accessibility options.

![zoomproblem](https://user-images.githubusercontent.com/8943532/46959014-58048680-d09b-11e8-840b-3808e19e2bdb.gif)

**Comment by sbatten** [comment]
@Guema this is the intended behavior. the menu bar should be zoomable for accessibility reasons and so we zoom the titlebar. similar to scaling windows in the system display options. if you, however, do not use the menu bar and don't want it to zoom the titlebar, you can set `window.menuBarVisibility` to `hidden` and the title bar will not zoom with the rest of the UI.
