### ISSUE TITLE
Using VSCode as an advertising platform

### ISSUE THREAD

**Issue by agoldis** [Microsoft/vscode#60989]
Today I launched VSCode (which I enjoy and like a lot) and saw this small thingy:
<img width="619" alt="screen shot 2018-10-15 at 10 25 34 am" src="https://user-images.githubusercontent.com/1637928/46967245-d560d480-d064-11e8-94ee-9ae2bc367452.png">

It is very exciting to see that Microsoft uses the power and popularity of this great product to advertise its cloud commercial solution. It makes sense - there're so many developers using VSCode and it's possible to reach so many of them just by embedding advertisement within the editor 💪🏻

I would like to check the possibility of advertising other, non-Microsoft products within VSCode - should I submit a PR for that and / or where can I find information about how other companies can promote their commercial products using VSCode "open source" platform?

**Comment by agoldis** [comment]
@David-Else I have seen that while using their stable `1.28.1` version:
<img width="291" alt="screen shot 2018-10-15 at 1 50 44 pm" src="https://user-images.githubusercontent.com/1637928/46977582-6645a900-d081-11e8-86db-f07dcedb8172.png">

**Comment by dmarkhas** [comment]
Real men use vim.

**Comment by agoldis** [comment]
@burtek I am not 100% sure, I didn't debug it. Based on list of my extensions, it is unlikely...

But even if it's a part of an extension - it is unethical and improper for Microsoft to use VSCode extensions and / or code editor for promoting their commercial products.

The only case I would somehow consider it ok is showing the popup **after** I installed a dedicated Azure extension (and it wasn't the case).

For reference - the list of installed extensions: 
- npm (eg2.vscode-npm-script)
- GitLens (eamodio.gitlens)
- ESLint (dbaeumer.vscode-eslint)
- DotENV (mikestead.dotenv)
- Docker (peterjausovec.vscode-docker)
- Color Highlight (naumovs.color-highlight)

P.S.
Here's the irony... Last week I was attending Node + JS Interactive conference. Among the keynote speakers was Chris Dias (@chrisdias) 👋🏻 - the same guy that's assigned to this issue.

https://events.linuxfoundation.org/events/node-js-interactive-2018/agenda/schedule/

The highlight of his talk:
> Microsoft’s history with Open Source Software actually began long ago, but recent projects like Visual Studio Code and TypeScript are some of the most popular, most active, and most “open”. What do these projects do differently, and what can we all learn from them?

Chris made a point by demonstrating how Microsoft changed, showcasing the significant shift in attitude and company's contributions to the open source (and JS) ecosystem. 👍🏻

It would be nice to keep VSCode **most "open"**

**Comment by chrisdias** [comment]
@agoldis 

I also made a point in that talk that we sometimes make mistakes :)

We recently did a quick experiment with a small set of users to understand how effective different variations in wording were in the extension recommendation prompts.

It turns out the different phrases didn't make a difference, but some of the terms did, causing negative reactions. Not what we wanted so we quickly turned these experiments off yesterday. You won't see these again.

Lesson learned, thanks for submitting the issue, and sorry for the inconvenience.

**Comment by David-Else** [comment]
@agoldis Seems like the phrases that caused "negative reactions" included **advertisements for  Microsoft products**?

Your explanation does not address the fact you were experimenting in turning VS Code into an advertising platform, it is exactly this kind of thing that people most fear about Microsoft. This is much more than just an issue of "inconvenience.", this is an issue of trust in a company with a history of being an enemy of open source.
