### ISSUE TITLE
debug convert paths utilities  make the debug adapter to exit

### ISSUE THREAD

**Issue by rodrigovaras** [Microsoft/vscode#60998]
This scenario is happening when interaction between live share and the new tracking debug adapter API.

When live share start sharing we flow all of the events back into our host adapter process that will interact with our agent. One particular case is the stopped event where our live share host treat it in a special way by requesting more info into the 'real' debug adapter (threads/scopes/variables..etc..) before notifying our joined sessions. When stepping really fast in a node js app it happen that request were made into the adapter when the state is running and so sometimes the scope request will fail.

The problem being reported is in the following vscode source file:
src\vs\workbench\parts\debug\common\debugUtils.ts

function convertPaths(msg: DebugProtocol.ProtocolMessage, fixSourcePaths: (toDA: boolean, source: DebugProtocol.Source | undefined) => void): void {
....
		case 'response':
			const response = <DebugProtocol.Response>msg;
			if (response.success) { **<==== without this line the debug adapter exit**
				switch (response.command) {

Note: 
Processing a response and some expected contents will fail for other scenarios too.
The ask is to add this extra line check, that immediately fix our live share issue we were seeing when quickly stepping.

**Comment by weinand** [comment]
@rodrigovaras great catch, thx!
