### ISSUE TITLE
Issues with VS Code, OmniSharp, and the node_modules folder.

### ISSUE THREAD

**Issue by bobwinners** [Microsoft/vscode#60997]
Version VS Code 1.28.1

I currently have a project that is a .NET Core MVC/Angular project.  Since the last update, I have been experiencing weird behavior with OmniSharp.  If I open the project without the node_module folder everything is fine and I have no namespace errors with OmniSharp.  Then, I run npm install to download the packages and everything is still ok.  Now if I restart VS Code, after OmniSharp starts up, I get a bunch of errors “Type or namespace name xxx does not exist in the namespace project_namespace.”  I am able to compile and run the project just fine.  I have tried to edit my .omnisharp.json file to include exclude node_modules directory but that does not work.  All intellisense in my project’s namespace fails, however, it works with all other namespaces (System, Microsoft.AspNetCore, etc).  If I remove the node_module folder and restart VS Code, OmniSharp works again.  

Steps to reproduce.
1.	Open project folder in VS Code without the node_modules directory.
2.	Run npm install to download modules
3.	Reopen VS Code.

Thanks for your help,
Bob

**Comment by bobwinners** [comment]
As a follow up I was able to replicate this behavior on another system.

**Comment by bobwinners** [comment]
I only have one Extension installed and it is the C# extension.  I guess I will have to stop using VS Code as it is too unstable for writing production code.  Microsoft needs to start supporting their open-source products better.

**Comment by isidorn** [comment]
Pleae file this issue against the C# extension here
https://github.com/OmniSharp/omnisharp-vscode
thank you
