### ISSUE TITLE
ext install: auto go away while focus out from one window to another

### ISSUE THREAD

**Issue by mumairali** [Microsoft/vscode#610]
I think Ctrl+Shift+P dialog should persist until unless I select option by hit enter key or click on cross* icon or press Esc key to close this dialog. 

Unfortunately when my mouse focus out from code window to other or click somewhere else. Package control dialog disappear and then need to start search again!.

**Comment by joaomoreno** [comment]
Unfortunately, as designed, until we do a new UI for this. #448
