### ISSUE TITLE
Azure Repos extension, automatically acquire PAT

### ISSUE THREAD

**Issue by jacwil** [Microsoft/vscode#61002]
Issue Type: <b>Bug</b>

The experience behind "Authenticate and get access token automatically (new experience)" of the "team signin" command (Azure Repos extension) was not fool-proof.

While the text does say I must press the Enter key to continue and Esc to cancel, I only read as far as "...copy this code... paste it in aka.ms/devicelogin" and proceeded to do just that. Clicking out of the command effectively cancels the action. I copied and pasted the code into my browser 3 times before carefully reading the text.

This issue is in regards to wording of the text. It should read in order of action: "Copy the code and press the Enter key. You will be taken to aka.ms/devicelogin where you will paste the code and sign in."

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17763

<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
swagger-viewer|Arj|2.0.2
python|ms-|2018.7.1
autorest|ms-|2.0.1
Go|ms-|0.6.91
PowerShell|ms-|1.9.0
team|ms-|1.142.0
vscode-apielements|vnc|0.6.7

</details>

**Comment by chrmarti** [comment]
This issue was moved to Microsoft/azure-repos-vscode#446
