### ISSUE TITLE
Repainting issues in Output and Debug Console  after upgrade to 1.28.1 

### ISSUE THREAD

**Issue by thered121** [Microsoft/vscode#61001]
Issue Type: <b>Bug</b>

1) Launch VSCode
2) Activate Output window
3) Part of the File Explorer shows up in the Output

1) Launch VSCode
2) Activate the Debug Console
3) Input area shows blinking cursor and menu bar

Note: Can reproduce with all extensions disabled.  

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:13:53.910Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (6.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
cucumberautocomplete|ale|2.12.1
cform|aws|0.0.15
vagrant|bbe|0.5.0
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.6.0
xml|Dot|2.3.2
gitlens|eam|8.5.6
tslint|eg2|1.0.40
vscode-npm-script|eg2|0.3.5
git-project-manager|fel|1.7.1
code-runner|for|0.9.4
rest-client|hum|0.20.2
Ionide-FAKE|Ion|1.2.3
Ionide-Paket|Ion|1.12.0
svn-scm|joh|1.43.0
docomment|k--|0.1.2
msr-vscode-p|lov|0.0.5
mssql|ms-|1.4.0
python|ms-|2018.9.0
azurecli|ms-|0.4.2
cpptools|ms-|0.19.0
csharp|ms-|1.16.2
Go|ms-|0.6.91
PowerShell|ms-|1.9.0
vsliveshare|ms-|0.3.790
azurerm-vscode-tools|msa|0.4.2
debugger-for-chrome|msj|4.10.2
chef|Pen|0.7.0
vscode-docker|Pet|0.3.1
vscode-boot-dev-pack|Piv|0.0.8
vscode-boot-properties|Piv|0.1.4
vscode-bosh|Piv|1.0.0
vscode-manifest-yaml|Piv|1.0.0
vscode-spring-boot|Piv|1.0.0
ruby|reb|0.20.0
java|red|0.32.0
vscode-yaml|red|0.0.17
vscode-icons|rob|7.27.0
yo|sam|0.9.3
elm|sbr|0.22.0
vscode-java-debug|vsc|0.14.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.10.0
vscode-maven|vsc|0.11.1
vscode-spring-boot-dashboard|vsc|0.1.2
vscode-spring-initializr|vsc|0.4.0

</details>

![explorerwindowinoutput](https://user-images.githubusercontent.com/19173414/46975785-9139f800-d095-11e8-92f7-bce9b8807237.jpg)

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/59682
