### ISSUE TITLE
it's very very very slow!

### ISSUE THREAD

**Issue by choreno** [Microsoft/vscode#61004]
Issue Type: <b>Bug</b>

[10372:1015/170007.627:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:13:53.910Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.39GB (8.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by choreno** [comment]
it works fine until ver 1.25. But it getting slower from 1.26. still it has not been resolved with 1.28 ??

**Comment by lijqh** [comment]
I think I encountered the same situation. Since updated to 1.28.1, VSCode eats my memory!
Open the Resource Moniter I found a lot of "powershell.exe" processes. 


Version: 1.28.1 (system setup)
Commit: 3368db6750222d319c851f6d90eb619d886e08f5
Date: 2018-10-11T18:13:53.910Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by jrieken** [comment]
@lijqh what you are seeing is https://github.com/Microsoft/vscode/issues/60585.

**Comment by jrieken** [comment]
@choreno Please follow this and paste the perf numbers: https://github.com/Microsoft/vscode/wiki/Performance-Issues#read-the-startup-timers

**Comment by choreno** [comment]
Here is the result.

Startup Performance Measurement
OS: win32(6.1.7601)
CPUs: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz(8 x 2712)
Memory(System): 15.39 GB(8.88GB free)
Memory(Process): 197.36 MB working set(197.36MB peak, 184.57MB private, 29.60MB shared)
VM(likelyhood): 0% 
Initial Startup: true 
Has 0 other windows
Screen Reader Active: false 
Empty Workspace: true 


Raw Startup Timers (CSV)
Name	Start
main:started 	1539695421157 
main:appReady 	1539695421231 
main:loadWindow 	1539695421517 
renderer/started 	1539695441741 
willShowPartsSplash 	1539695441750 
willAccessLocalStorage 	1539695441750 
didAccessLocalStorage 	1539695441750 
didShowPartsSplash 	1539695441903 
willLoadWorkbenchMain 	1539695441914 
didLoadWorkbenchMain 	1539695442372 
main/startup 	1539695442372 
willStartWorkbench 	1539695442399 
willLoadExtensions 	1539695442402 
LifecyclePhase/Restoring 	1539695442406 
willRestoreEditors 	1539695442453 
willRestoreViewlet 	1539695442453 
didRestoreViewlet 	1539695442459 
didRestoreEditors 	1539695443766 
LifecyclePhase/Running 	1539695443766 
didStartWorkbench 	1539695443770 
extensionHostReady 	1539695443838 
didLoadExtensions 	1539695443838 
LifecyclePhase/Eventually 	1539695444800 

INFO standard startup Object
