### ISSUE TITLE
VScode freezes upon trying to move a file

### ISSUE THREAD

**Issue by michaelsharpe** [Microsoft/vscode#61008]
- VSCode Version: 1.28
- OS Version: OSX 10.12.6

Steps to Reproduce:

1. Try to move a file or a folder
2. My whole session in VSCode freezes.  I can to things from the dropdown menus, but I can't click anything and the keyboard shortcuts all stop working.  This has arisen since I upgraded to 1.28 just a few hours ago.  It also appears that the same bug on my end is happening in VSCode Insiders.

Any thoughts or ideas? 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by burtek** [comment]
I have similar issue, although it freezes just by trying to use auto-complete in TS file.

**Comment by michaelsharpe** [comment]
Apparently I also can't move tabs around.  Same behavior results.  My ability to type or click things with the mouse breaks.  I can access dropdown menus, and even select options in them...

**Comment by burtek** [comment]
I just traced it down to `ms-vscode.typescript-javascript-grammar` extension, disabling of which solved the issue. Do you have that installed and does disabling it help?

**Comment by michaelsharpe** [comment]
@burtek Even restarting the program with extensions disabled doesn't fix it for me. Not sure what it might be.   I don't think I have any typescript extensions installed either.

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!
