### ISSUE TITLE
Show error returned from 'callstack' request prominently in CALL STACK view

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#6100]
This is related to #5348.

When requesting a backtrace in recent versions of node (v6 and some v5 versions of node that are used in electron), in some situations node runs into an "Internal error: illegal access". Currently node-debug silently ignores this error and returns an empty call stack (which is not very helpful).

Strangely enough fixes node-debug's code injection this problem (but we do not yet understand why).

However there are situations in which code injection doesn't work reliably, e.g. when attaching to an already running node process. To give better feedback to the user in this situation we will have to show the error prominently in the CALL STACK view. (This will help in the 'pause' execution case as well, where the call stack is not available but the CALL STACK view doesn't explain why).

**Comment by isidorn** [comment]
So you propose that we show an error in the call stack view if the call stack request fails?
Or what would be the mechanism for the debug adapter to send the error message which should be displayed in the callstack view?

**Comment by weinand** [comment]
Yes, we show the error message from the request in the view (probably wrapped because the view is narrow).

**Comment by weinand** [comment]
@isidorn for now I'm returning the error as a dummy stack with one element:

![2016-05-09 12-59-23](https://cloud.githubusercontent.com/assets/1898161/15111222/ee01cd1e-15e5-11e6-9fd7-1b67717da633.png)

Please let me know if I can remove this workaround.

**Comment by weinand** [comment]
@isidorn error shows up nicely but stopped reason is missing; see https://github.com/Microsoft/vscode/issues/6214
