### ISSUE TITLE
VS Code crashed, file content is lost.

### ISSUE THREAD

**Issue by alex2k8** [Microsoft/vscode#61007]
- VSCode Version: 1.28.0
- OS Version: Microsoft Windows [Version 10.0.17134.345]

1. Worked on some .html (with a lot of javascript in it)
2. Suddenly VS Code crashed.
3. Once VS Code restarted, the .html file was empty. It's content completely gone.

I checked C:\Users\sasha\AppData\Roaming\Code\Backups, nothing useful here.

**Comment by alex2k8** [comment]
Luckily, the code was cached in Chrome Dev Tools, so I copied it back. But now an interesting situation. I open that file in VS Code, and it shows again as empty. I initially thought that it was deleted again, but no, the file on disk has content, only in VS Code it shows as empty.

Here is my experiment:
1. cmd
2. echo b.html
Prints: "test"

Notice: the b.html is the name of the originally lost file.

3. code b.html
It opens, but content of the b.html file is shown as empty in VS Code. 
4. echo b.html
Prints: "test"
5. echo "Foo" > c.html
6. In same VS Code instance I open that new "c.html", and I see "Foo".
7. Just let's make sure 100% "cmd" and VS Code work with same directory.
8. echo "Bar" > c.html
9. In VS Code I see "Bar"

Notes:
1. I did not try to save "b.html" from VS Code yet. I afraid, that if I do this, the bug will gone. While I can reproduce it, better to leave things as is. So if I can send any details, let me know.

2. I can close/open VS Code, bug remains.

3. It's obvious to ask a question: "Initially, after VS Code crash, may be the b.html was not removed, but just was not shown in VS Code"? Answer is no, after crash it was indeed removed on disk (I opened file using other editor, and it was empty).

**Comment by bpasero** [comment]
@alex2k8 was the file dirty when it crashed or not?
