### ISSUE TITLE
Text drag & drop no longer works for CRLF or LF character

### ISSUE THREAD

**Issue by devuxer** [microsoft/vscode#61012]
- VSCode Version: 1.28.1
- OS Version: Windows 10 (10.0.17134 Build 17134)

**Steps to Reproduce**

1. Select a block of code, including the blank line above.

    ![selection](https://user-images.githubusercontent.com/1298521/46986162-bc771400-d0a2-11e8-8de9-8166e154eaf1.png)

2. Move the cursor to the beginning of the blank line.

    ![cursor over symbol](https://user-images.githubusercontent.com/1298521/46986163-bed96e00-d0a2-11e8-9988-4103c03a221e.png)

3. Attempt to drag the selected text.

Does this issue occur when all extensions are disabled?: Yes

**Actual behavior**

Text is deselected.

**Expected behavior**

Text is dragged.

**Comment by rebornix** [comment]
This one is a really good catch but it's a good challenge to the current architecture. When an empty line is selected, to make sure that users can see the line is being selected, we render a thin selection in the empty line with some round corners. When users mouse click on it, our hit test doesn't take this empty selection into account so it thinks users are clicking on the empty area.

Considering the difficulty to make this work and the fact users can select non-empty lines to drag and drop, I'm going to give this a won't-fix. It doesn't mean that we are never going to fix this issue but if our architecture allows (as it keeps involving), we will make it happy.
