### ISSUE TITLE
git bash chinese encoding wrong!!

### ISSUE THREAD

**Issue by hooozen** [Microsoft/vscode#61013]
Issue Type: <b>Bug</b>

git bash chinese encoding wrong!!

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:13:53.910Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|7.89GB (3.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-faker|dee|1.3.0
smarty|imp|0.3.0
code-beautifier|mic|2.1.0
dotenv|mik|1.0.1
vetur|oct|0.13.0
vscode-icons|rob|7.27.0
gitconfig|sid|2.0.0
vim|vsc|0.16.10

</details>

**Comment by huleiEthan** [comment]
@hooozen Maybe this one can help you #60717
