### ISSUE TITLE
Open file via URL creates a "ghost" file in the "working files" section

### ISSUE THREAD

**Issue by Janne252** [Microsoft/vscode#6101]
I'm using HoverProvider to provide links to the source file of a Lua function.

The URL is constructed like this:
```typescript
var url = "file:" + userFunction.sourceFile;
```
(using `file:\\` doesn't seem to work, it triggers the error "file not found" - looks like the `\\` is automatically added after the `file:` protocol?)

The field sourceFile is for example `e:\coh2_mods\ccm\scar\ccm_extensions.scar` (a string value, an absolute path to a physical file)

Clicking this link works and the file is opened. However once the file is edited, which triggers adding the file to the "Working files" list, a ghost file is added to the list instead:
![Ghost file](http://i.imgur.com/pmRO1MB.png)
This file can be edited and the changes seem to save on save as well as long as this file is selected.

Attempting to click this ghost file causes and error (re-select or select after selecting another file):
![Error](http://i.imgur.com/Ay45Bve.png)

Opening the previously clicked file via the workspace explorer and after editing it it is added to the "Workspace files" list:
![Actual file](http://i.imgur.com/BD42WFz.png)
This file behaves correctly. 

Closing the "ghost file" causes the "1 unsaved" notifier to remain. 

**How to test/reproduce?**
1. Prepare a way of clicking a markdown-formatted link in vscode (I used HoverProvider for this) that points to a physical file on your computer
2. Click it. The file should load. Edit it. A ghost file should appear as explained above.

**Note**
The ghost file only started to appear after 1.0.0 update.

**Comment by bpasero** [comment]
@Janne252 does it reproduce in our latest insider build? 
We are releasing preview releases of the next stable VS Code version for everyone to try and give feedback. These preview releases are not 100% tested and might be unstable but contain our latest features and bugfixes. You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by Janne252** [comment]
@bpasero Unfortunately it still is:
![Ghost file](http://i.imgur.com/w42of9u.png)

**Comment by bpasero** [comment]
@Janne252 can you somehow attach the full file URI here that you use in the hover?

**Comment by Janne252** [comment]
@bpasero 
I captured this with a breakpoint + "Copy Value" via Debug->Variables
```typescript
"CCM_HealthMonitorInit(Void)\r\n * [e:\coh2_mods\ccm_v2\scar\ccm_healthMonitor.scar, line 134](file:e:\coh2_mods\ccm_v2\scar\ccm_healthMonitor.scar#L134)"
```
The full file URI is in this case `file:e:\coh2_mods\ccm_v2\scar\ccm_healthMonitor.scar#L134`

**Comment by bpasero** [comment]
@Janne252 hm, would you be able to provide a sample extension that I could run to reproduce this? I believe it has something to do with how the URI is created and flowing through the system. Thanks!

**Comment by Janne252** [comment]
@bpasero [https://github.com/Janne252/vscode-uri-test](https://github.com/Janne252/vscode-uri-test)

**Comment by bpasero** [comment]
Thanks!!

**Comment by bpasero** [comment]
@Janne252 there is some weird URI escaping happening, but I am able to fix this issue by changing the customHoverProvider.ts to create the file URI as follows:

```typescript
/*---------------------------------------------------------
 * Copyright (C) Janne Varjo. All rights reserved.
 * Licensed under the MIT License. See LICENSE.txt in the project root for license information.
 *--------------------------------------------------------*/

'use strict';

import * as vscode from 'vscode';
import {HoverProvider, Hover, TextDocument, Position, CancellationToken, Uri} from 'vscode';
import {Directory, Path} from './helpers';

export class CustomHoverProvider implements HoverProvider
{
    
    public provideHover(document:TextDocument, position:Position, token:CancellationToken)
    {
        var files:string[] = Directory.GetFiles(vscode.workspace.rootPath);
        
        var word = document.getText(document.getWordRangeAtPosition(position));
        var hoverMessage = `'${word}' doesn't match a filename in the current workspace. You should probably create ${word}.txt`;
        
        for(var file of files)
        {
            var fileName = Path.GetFileNameWithoutExtension(file);
            var uri = Uri.file(file);

            if (fileName == word)
            {
                hoverMessage = `'${word}' matches the file [${file}](${uri.toString()}) in the workspace.`;
                break;
            }
        }
        
        return new Hover(hoverMessage);
    }
}
```

**Comment by Janne252** [comment]
@bpasero Thanks for figuring it out. Certainly does make sense to use a service to construct the URI rather than prepend the protocol.

**Comment by bpasero** [comment]
@jrieken maybe you could answer the question in https://github.com/Microsoft/vscode/issues/6101#issuecomment-218148979

**Comment by jrieken** [comment]
@Janne252 `Uri.file` always assumes to argument is a file path - that means url-specific characters like `#` and `?` will be encoded. To add query parameters and a fragment you should use `Uri.parse`
