### ISSUE TITLE
Cmd+Shift+E does not open explorer

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#61010]
Issue Type: <b>Bug</b>

- Latest insider
- `code-insiders --disable-extensions --user-data-dir ./foo`
- Cmd+Shift+E do not open explorer (Cmd+Shift+F for search and Cmd+Shift+X for extensions) work though
- No error in dev console
- No other bindings for Cmd+Shift+E

![image](https://user-images.githubusercontent.com/4033249/46982759-76b24f80-d092-11e8-9f41-684b65872e0d.png)

VS Code version: Code - Insiders 1.29.0-insider (628740747496bc1f36c83d70f208b7fd85afc86b, 2018-10-15T05:11:18.840Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-emoji|bie|0.0.7
markdown-preview-github-styles|bie|0.1.3
vscode-eslint|dba|1.6.0
remotehub|eam|0.2.0
tslint|eg2|1.0.40
vsc-material-theme|Equ|2.4.2
prettier-vscode|esb|1.6.1
beautify|Hoo|1.4.4
theme-monokai-pro-vscode|mon|1.1.8
vscode-language-pack-ja|MS-|1.28.2
python|ms-|2018.9.0
debugger-for-chrome|msj|4.10.2
vetur|oct|0.13.0
webview-lsp-inspector|oct|0.0.1
polacode|pnp|0.2.2
vscode-csstree|sme|0.7.0
language-stylus|sys|1.10.0
vim|vsc|0.16.10

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
@octref Are you able to reproduce it when running from sources?

**Comment by sandy081** [comment]
Can you please keep a breakpoint at the following line and see what command is getting executed?

https://github.com/Microsoft/vscode/blob/125260e63f179a87cfa1f8228cff9d6afc435c99/src/vs/platform/keybinding/common/abstractKeybindingService.ts#L189

**Comment by octref** [comment]
I'm working on my home laptop, and it doesn't have this bug...And in Friday I just formatted my work laptop's disk because Mojave can't boot...

**Comment by sandy081** [comment]
Oh ok. I cannot reproduce this hence asking your help to understand what's happening. 

Can I close this issue until you can reproduce and provide the requested info?

**Comment by octref** [comment]
Yes let's do that. Thanks.
