### ISSUE TITLE
Git color coding missing in Explorer view

### ISSUE THREAD

**Issue by xoxota99** [Microsoft/vscode#61017]
Issue Type: <b>Bug</b>

I seem to be experiencing #46888 again as of today. Git color coding has disappeared from the Explorer view, and changes are no longer visible in the margin / gutter of the Editor view.

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:07:48.477Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (5.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.9.0
cpptools|ms-|0.19.0
platformio-ide|pla|1.4.0

</details>

**Comment by jrieken** [comment]
> and changes are no longer visible in the margin / gutter of the Editor view.

Looks like all of git is dead. @xoxota99 please provide more insight here as you seems to be the only one having this issue. How about trying with insiders and how about attaching some git logs

**Comment by joaomoreno** [comment]
@xoxota99 Do you see changes in the SCM view?

**Comment by joaomoreno** [comment]
Related https://github.com/Microsoft/vscode/issues/60010

**Comment by xoxota99** [comment]
Yes, changes are showing up in SCM view just fine. Other than the Explorer view color coding and gutter change indicators, git integration in general seems to be working fine.

**Comment by xoxota99** [comment]
I'm fine resolving this as a dupe of #60010 if you like.
