### ISSUE TITLE
On Linux and Mac OS, Debugger Terminal should respect "Primary Display" setting

### ISSUE THREAD

**Issue by 9527KGG** [microsoft/vscode#61023]
Ubuntu 18 LTS + xfce.

Repro:
I've 2 display. I set display 1 as the "Primary Display". (Setting->Display)
Start vscode and move it to display 2.
Start to debug c++ hello word.

Observed:
The "Debugger Terminal" always start in the same display as vs code. That's display 2.

Expected:
The "debugger Terminal" should start in "Primary Display", which is display 1.

Comments:
What I request is the exact same behavior of Visual Studio on Windows. Because of missing feature, every time I restart debug, I've to drag  "Debugger Terminal" to another display. So they won't overlap, which is very very boring .

Thanks.

**Comment by isidorn** [comment]
@9527KGG I feel like you are using the external terminal. What is your launch.json? Can you paste a picture

@bpasero do we already have some umbrella issues for multiple display and where to open windows?

**Comment by 9527KGG** [comment]
Yes. I'm using the external terminal. The .json file is the default one.

Because of missing feature, every time I restart debug, I've to drag "Debugger Terminal" to another display, which is very very boring .

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "1.cpp",
            "type": "cppdbg",
            "request": "launch",
            "program": "/home/xxx/ttt/a.out",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}

**Comment by 9527KGG** [comment]
BTW, both 
Ubuntu 18 LTS + gnome
Ubuntu 18 LTS + xfce
has the issue.

I bet other OS has this issue too

**Comment by isidorn** [comment]
This is about on what monitor the native terminal opens the new terminal
forwarding to @weinand and @Tyriar

**Comment by weinand** [comment]
@pieandcakes is the `"externalConsole": true` option based on VS Code's `runInTerminalRequest` or is the C++ debugger rolling its own ext terminal?

**Comment by pieandcakes** [comment]
@weinand The RunInTerminal change is in [0.19.1-insiders2](https://github.com/Microsoft/vscode-cpptools/releases/tag/0.19.1-insiders2). Prior to that, it is launched by calling `gnome-terminal` or `xTerm` to start. We don't specify anything special for display setting so it is whatever the terminal defaults are.

**Comment by 9527KGG** [comment]
Since VS code is my most favorable editor, I just tried on Mac. The issue still repro. So pls fix it.

**Comment by 9527KGG** [comment]
I see. Thanks, anyway.
