### ISSUE TITLE
Publisher name should not be part of extension name.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#6102]
test : https://github.com/Microsoft/vscode/issues/6099 
- VSCode Version: 1.1.0-alpha
- OS Version: Windows10

Steps to Reproduce:
1. Launch command prompt and execute command :
 code-alpha --list-extensions or code-alpha --install-extension "cpptools"

Actual: Publisher name is preceded with the extension name and without this user can't install or uninstall extension from command prompt.
Expected: Publisher name should not be required to install and uninstall extension and it should work same like how it is working from command palette : ext install Go

Example: To install CPP extension we need to provide command like:
**code-alpha --install-extension "ms-vscode.cpptools"**
But from command palette we can install with : **ext install cpptools**

![image](https://cloud.githubusercontent.com/assets/17735796/15022445/8bdaf1be-11e0-11e6-9ff7-354135633655.png)

**Comment by joaomoreno** [comment]
The publisher is part of the id, it is required to uniquely identify the extension.
