### ISSUE TITLE
lose response when terminal print large string

### ISSUE THREAD

**Issue by zjjott** [microsoft/vscode#61026]
VSCode Version: 1.28.2
OS Version:macOS 10.14
Shell: zsh or bash can all reproduce
Steps to Reproduce:

1. `code --disable-extensions` open a window
2. using terminal,and just print large string, I have try lua and python script,they all can reproduce
just one line python code:
```
print("asdqweasd"*10000)
```
Does this issue occur when all extensions are disabled?: Yes/No
Yes

few char will speed up,about 30000 chars,there need 5 seconds to response.

I just open a issue yesterday #60943 ,and typo VSCode version,but your developer close the issue.

I just upgrade VSCode to 1.28.2,but it's still slow

**Comment by Tyriar** [comment]
Works fine for me under macOS 10.13, even with `*1000000`. Can you share your settings file?

**Comment by Tyriar** [comment]
Cannot repro, very fast over here. If you have terminal slowness you can try change rendererType to dom.
