### ISSUE TITLE
loading document symbols for '....py'

### ISSUE THREAD

**Issue by Jerry1106** [Microsoft/vscode#61022]
Issue Type: <b>Bug</b>

My Visual Studio IntelliCode seems to be not working. 
there used to be an outline and recommendation in my code context. But now when I open a python, the outline will show that "loading document symbols for '....py". 

I wonder if there is anyways to figure it out? Thanks a lot!

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:07:48.477Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 6|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
al-code-outline|and|0.0.9
vscode-django|bat|0.17.0
jupyter|don|1.1.4
vscode-great-icons|emm|2.1.44
vimL|fal|0.0.3
vscode-test-explorer|hbe|2.0.9
nbpreviewer|jit|1.0.0
vscode-python-test-adapter|lit|0.1.4
MagicPython|mag|1.1.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2018.9.0
azure-account|ms-|0.4.3
vscode-yaml|red|0.0.17
altitude-script-language|uca|0.0.3
vscodeintellicode|Vis|1.0.5
vim|vsc|0.16.10
jinja|who|0.0.8

</details>

**Comment by mjbvz** [comment]
Please file this issue against the python extension
