### ISSUE TITLE
Windows: Deep nested files, long path; VS Code can not find files

### ISSUE THREAD

**Issue by FrimJo** [Microsoft/vscode#61034]
VS Code on Windows can not find deep nested files using ctrl + P nor find deep nested code using Search tool. Can open deep nested files manually using VS Code Explorer, but do not get TSLint, IntelliSense nor Prettier auto fix support. All works fine on Mac.

- VSCode Version: 1.29.0-Insider
- OS Version: Windows 10 

Steps to Reproduce:
1. Open a project with the following file structure
```js
frontend/src/scenes/Counseling/scenes/CounselingDefault/components/CounselingSceneController/components/CounselingSession/components/Consulting/components/AdvicePackagesContainer/components/AdvicePackage/components/ProductProposalsContainer/components/AdviceActionBase/components/AdviceActionManagementOptions/components/FundDepotManagementOptions/components/OwnManagement/OwnManagement.tsx 
```
2. Using ctrl + P, serach for `OwnManagement`

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
I'm not aware of any reason that deeply nested files wouldn't show up in search. Are you sure it isn't covered by a `files.exclude` or `search.exclude` pattern, or .gitignore file? I don't even consider that file to be that "deeply nested", a couple dozen folders is nothing 😁

**Comment by FrimJo** [comment]
Thank you for you answer @roblourens. Yes I'm sure, it is not related to `files.exclude`, `search.exclude` or any similar. It works on all OSX machines running this project put not for any one using Windows on the team.

**Comment by roblourens** [comment]
Any chance this project can be shared? 
Or can you share the logs by doing the following?

- Run the command "Set log level" and change it to "Trace"
- Run the search again
- Show the search-related messages in the "Log (Window)" output panel

![image](https://user-images.githubusercontent.com/323878/35987940-02aae15a-0cb2-11e8-83f1-d95c5dc3881b.png)
