### ISSUE TITLE
can not configure git

### ISSUE THREAD

**Issue by guotielong** [Microsoft/vscode#61032]
Issue Type: <b>Bug</b>

when i use vscode opened jupyterlab project  that show a tab git not found .next i was use file ->setting  setting the git path  ,and then tip me "edit in setting.json",and next ...

at last nothing was run .so what happen?what is the next should do ?

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (9.73GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
anaconda-extension-pack|ms-|1.0.1
python|ms-|2018.9.0
vscode-yaml|red|0.0.17

</details>

**Comment by joaomoreno** [comment]
What value did you set `git.path` to?
