### ISSUE TITLE
Storage: avoid duplicate entries in currentOrPreviouslyRunExperiments

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#61039]
As discussed, please avoid duplicate keys in this storage entry. Also, add some code to remove the existing duplicates from the object we already have.

![image](https://user-images.githubusercontent.com/900690/47014759-7a55dd00-d14b-11e8-9b18-08e201820154.png)

**Comment by ramya-rao-a** [comment]
Fixed with 
https://github.com/Microsoft/vscode/commit/c1af5ff797c5e3ef195d8f060c59cf9a1b7e2b2a
