### ISSUE TITLE
ctrl+y and redo function not work

### ISSUE THREAD

**Issue by RONAKDHOLARIYA** [Microsoft/vscode#61035]
when undo something in my code and I suddenly press ctrl+y never redo my code and when I go at edit and redo should be enable if this is not working so it give as disable why should make it enable.
Because of it I changed two keyboard of my Lappy who is responsible for it.

**Comment by rebornix** [comment]
@RONAKDHOLARIYA could you please give detailed reproduce steps for what's happening?
