### ISSUE TITLE
ctrl + / in html file displays {% comment %} ... {% endcomment %}

### ISSUE THREAD

**Issue by qdirks** [Microsoft/vscode#61030]
Issue Type: <b>Bug</b>

Open an html file and use ctrl + / to comment something. It doesn't put &lt;!-- --&gt; like it's supposed to for html files.

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:13:53.910Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (8 x 3411)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (9.67GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
vscode-color|ans|0.4.5
django-html|bib|1.2.0
django-snippets|bib|1.1.0
jshint|dba|0.10.20
tslint|eg2|1.0.40
python|ms-|2018.9.0
cpptools|ms-|0.19.0
csharp|ms-|1.16.2
vsliveshare|ms-|0.3.790
debugger-for-chrome|msj|4.10.2
java|red|0.32.0
vscode-icons|rob|7.27.0
vscode-java-debug|vsc|0.14.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.10.0
vscode-maven|vsc|0.11.1

</details>

**Comment by qdirks** [comment]
Well, now it's working again. I think, since I turn my machine off every night, the reboot helped it to work properly today, but yesterday I did not try a reboot; I only tried closing and reopening the program, but the problem remained.

I have encountered this before where the shortcut works fine for awhile, and then stops working, and then seems okay after some time (perhaps after a reboot, or after an update).

**Comment by aeschli** [comment]
Nothing has changes in that area. Closing, please reopen if you see this again.

**Comment by qdirks** [comment]
@aeschli

Yeah, it's happening again. I can believe that there are no changes in that area. This has been an issue for me in previous versions I think. Sometimes it works fine, and sometimes it doesn't.

I guess I'm leaving my computer (and vscode) on for several hours at a time without usage. Could that cause the bug to manifest? At least, I only seem to notice an issue after it has been running for a long time.

I can confirm that closing and re-opening the program does not fix the problem. I will try a reboot really quick and see if the problem is gone.

![bad html comments](https://user-images.githubusercontent.com/26916078/47208821-75b04500-d354-11e8-9d31-2381e366ae7d.PNG)
