### ISSUE TITLE
Alt+S C no longer opens Tortoise SVN Commit

### ISSUE THREAD

**Issue by rottndandie** [Microsoft/vscode#61038]
Issue Type: <b>Bug</b>

Before the most recent update, Alt+S C reliably opened the Tortoise SVN commit dialog. Now, it duplicates the current line, even though it's defined in the key bindings JSON file. When I tried to define a different key sequence to open that dialog, such as Alt+S Q, I get the message that Alt+S Q is not defined, even though it's plainly visible in my custom keybindings.

To reproduce:
install the Tortoise SVN extension
Press Alt+s followed by c
Expected: Tortoise SVN commit dialog opens
Actual: The line the cursor is on is duplicated

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:13:53.910Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3450 CPU @ 3.10GHz (4 x 3109)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (9.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
better-phpunit|cal|1.1.0
bracket-pair-colorizer|Coe|1.0.60
vscode-faker|dee|1.3.0
tortoise-svn|fan|0.1.1
php-debug|fel|1.12.6
php-intellisense|fel|2.3.5
php-pack|fel|1.0.2
php-docblocker|nei|1.6.0
laravel-blade|one|1.18.0
vscode-php-getters-setters|php|1.2.3
vscode-icons|rob|7.27.0

(1 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
mnemonics aren't ignored properly now with the new menu. if you don't use menu mnemonics, you can work around this by disabling them with `window.enableMenuBarMnemonics` => `false`
