### ISSUE TITLE
TypeScript syntax highlighting breaks on "<{}>"

### ISSUE THREAD

**Issue by danvk** [Microsoft/vscode#6104]
- VSCode Version: Version 1.0.0 (1.0.0) 2016-04-13T10:59:46.727Z
- OS Version: Mac OS X 10.11.4 (15E65)

The syntax highlighting in vscode gets confused by `<{}>` in a type declaration in a TSX file:

```ts
let root: React.ReactElement<{}>;
// syntax highlighting is broken for the rest of the file
```

For example, OK:

![screen shot 2016-05-04 at 2 00 37 pm](https://cloud.githubusercontent.com/assets/98301/15023947/bade108e-1200-11e6-92e6-ed1540242e7e.png)

and broken (look at `let` and `if`):

![screen shot 2016-05-04 at 2 00 18 pm](https://cloud.githubusercontent.com/assets/98301/15023952/bdf5bda8-1200-11e6-9f54-9fa4a3062d6f.png)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#161
