### ISSUE TITLE
Search: Cannot read property 'fileEncoding' of undefined

### ISSUE THREAD

**Issue by MikeMatusz** [Microsoft/vscode#61042]
Issue Type: <b>Bug</b>

When running any search query in my multi-folder workspace, results start to display, but then disappear and an error appears around the search input:
'Cannot read property 'fileEncoding' of undefined'

I have made no changes to any files in my workspace since it was working in the prior Insiders build, and started getting this error immediately after updating this morning.

VS Code version: Code - Insiders 1.29.0-insider (a0b91c2c5dff3ad25aab867f4692d08c700d5c10, 2018-10-16T07:33:17.566Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|31.85GB (6.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.10
jshint|dba|0.10.20
tslint|eg2|1.0.40
vscode-guid|hea|1.4.0
Angular2|joh|6.3.0
csharp|ms-|1.16.2
vsliveshare|ms-|0.3.790
debugger-for-chrome|msj|4.10.2
angular2-inline|nat|0.0.17
vscode-subword-navigation|ow|1.2.0
typescript-hero|rbb|3.0.0

</details>

**Comment by MikeMatusz** [comment]
I had `searchRipgrep.enable` set to true because of #60425.  I'm not able to reproduce this in the latest build with that setting turned off, nor with `search.runInExtensionHost` turned on (which replaces the previous, deprecated setting), so this can probably be closed.

**Comment by jkdmyrs** [comment]
On the latest insider build, this issue is still happening with searchRipgrep both enabled and disabled.

**Comment by roblourens** [comment]
Can you tell me if this is still happening in the latest? Think I might have fixed it.

If so, do you see a full stack in the developer tools?

**Comment by jkdmyrs** [comment]
@roblourens looks to be working on 1.29.0-insider

**Comment by roblourens** [comment]
Thanks
