### ISSUE TITLE
Crash at launch when no network

### ISSUE THREAD

**Issue by jtsom** [Microsoft/vscode#61044]
- VSCode Version: 1.29.0 Insider
- OS Version: Windows 10

Steps to Reproduce:

1. Attempt to launch VS Code when no network is available.

```
$ code-insiders .
dns.js:246
    this._handle = new ChannelWrap();
                   ^

Error: EFILE
    at new Resolver (dns.js:246:20)
    at dns.js:377:25
    at dns.js:431:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at net.js:45:13
    at net.js:1730:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at internal/child_process.js:6:13
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by jtsom** [comment]
This may be a duplicate (to https://github.com/Microsoft/vscode/issues/7570) However, that was reported several months ago, and marked "resolved" 15 days ago. It is not resolved, as it is happening, rendering VS Code unusable.

**Comment by sfeek** [comment]
I have the EXACT same issue. Please open this case again!

**Comment by Digized** [comment]
Pretty sure this might be a problem with electron https://github.com/electron/electron/issues/6437
We should keep an eye on that

**Comment by gustavosatheler** [comment]
Why this topic was closed if the error is still happening, if it was said as "resolved"?

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/7570

**Comment by hossmf** [comment]
Which company in the world launch a program that doesn't launch. Funny Microsoft! 😂
