### ISSUE TITLE
workbench.action.navigateToLastEditLocation

### ISSUE THREAD

**Issue by bthodla** [Microsoft/vscode#61045]
Issue Type: <b>Bug</b>

Found this as a new feature in Release Notes and tried to look for it in Settings but can't find it

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:13:53.910Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz (2 x 2294)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|8.00GB (2.70GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.1.0
systemd-unit-file|coo|1.0.0
vscode-github|Kni|0.30.0
MagicPython|mag|1.1.0
vscode-kanban|mkl|1.23.0
python|ms-|2018.9.0
partial-diff|ryu|1.4.0
code-settings-sync|Sha|3.1.2
sort-lines|Tyr|1.7.0
vim|vsc|0.16.10

(2 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
This is a command you can configure as keybinding in the keybindings editor. You can also invoke it from the command palette.
