### ISSUE TITLE
Launching from command line opens two windows

### ISSUE THREAD

**Issue by jtsom** [Microsoft/vscode#61048]
Issue Type: <b>Bug</b>

Opening VS Code from the command line, and specifying the current folder (code-insiders .) causes Code to open with the specified directory opened in two windows.

VS Code version: Code - Insiders 1.29.0-insider (628740747496bc1f36c83d70f208b7fd85afc86b, 2018-10-15T05:17:41.965Z)
OS version: Windows_NT x64 10.0.17763

<details>
Steps to reproduce:
Launch VS Code and open a folder. Close VS Code. From a command line, navigate to the folder that was opened and launch VS Code with `code-insiders .`

VS Code will launch with both the window that was opened, and a second (smaller) window to the same folder.

<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (2 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|12.00GB (4.94GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.10
path-intellisense|chr|1.4.2
githistory|don|0.4.3
tslint|eg2|1.0.40
auto-rename-tag|for|0.0.15
toggler|hid|0.0.3
output-colorizer|IBM|0.1.2
Angular2|joh|6.3.0
json-to-ts|Mar|1.5.5
markdown-shortcuts|mdi|0.8.1
code-beautifier|mic|2.1.0
prettify-json|moh|0.0.3
csharp|ms-|1.17.0
debugger-for-chrome|msj|4.10.2
material-icon-theme|PKi|3.6.0
polacode|pnp|0.2.2
open-in-browser|tec|2.0.0

(3 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
You might be seeing the hot exit feature? https://code.visualstudio.com/docs/editor/codebasics#_hot-exit

Could you provide more details about the windows if not?

**Comment by xtofl** [comment]
I see this too.  Today the number grew from 2 to 3 :).  I am using version 1.27.2, though.  My `files.hotExit` setting is at `onExit`, `window.restoreWindows` is at `one`.

What info do you need on the opened windows?
