### ISSUE TITLE
1.28 spams notifications for being offline

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#61054]
Is it possible to remove notifications from `Source: Update Service` every time you open vscode or switch workspaces or reload window while being offline?

`net::ERR_NAME_NOT_RESOLVED` or `net::ERR_INTERNET_DISCONNECTED`

Version: 1.28.1 (user setup)
OS: Win10 x64

**Comment by maryam-a** [comment]
I've also gotten this error, but while actually being connected to the internet.

Version: 1.28.2 (system setup)
OS: Win10 x64
