### ISSUE TITLE
Import feature partially broken

### ISSUE THREAD

**Issue by Kallikrein** [Microsoft/vscode#61059]
- VSCode Version: 1.28.1 (user setup)
- OS Version: Windows 10 Enterprise 1607

Steps to Reproduce:

1. Create a .ts or .tsx file
2. Start typing a variable name: Auto import suggestions appear so the feature is available (same with Trigger Suggest command, import show in the list)
![workingimport](https://user-images.githubusercontent.com/6169839/47029144-17743e00-d16b-11e8-9c97-8da3d5b27db0.PNG)

3. Try to have code action suggestion import with shortcut: "no code action available"
![notworkingimport](https://user-images.githubusercontent.com/6169839/47029150-1cd18880-d16b-11e8-8935-a025a959c26f.PNG)

Does this issue occur when all extensions are disabled?: Yes

**Comment by burtek** [comment]
I had similar issue with this version, but what happened to me was that vscode half-froze. No keyboard shortcuts were working, as well as auto-completion, auto-import and several other features (see #61008). I traced it down to `ms-vscode.typescript-javascript-grammar` extension, disabling of which solved the issues. Do you have that installed and if so, does disabling it help?

**Comment by Kallikrein** [comment]
A colleague of mine helped me notice ctrl + space is now how to access import suggestions, sorry for the irrelevant issue, closing.
