### ISSUE TITLE
Decreasing window zoom level affect cursor visibility

### ISSUE THREAD

**Issue by dariuszsobkowicz** [microsoft/vscode#61057]
- VSCode Version: 1.28.1 (1.28.1)
- OS Version: macOS Mojave (10.14)

Steps to Reproduce:

1. Zoom Out to -1 or less
![kapture 2018-10-16 at 17 28 19](https://user-images.githubusercontent.com/14201464/47029022-d419cf80-d16a-11e8-9b21-cb25ccd8c55d.gif)

Does this issue occur when all extensions are disabled?: Yes/No
YES

**Comment by alexandrudima** [comment]
The recommendation is to not use `workbench.zoomLevel < 0`, but to tweak the font size instead.
