### ISSUE TITLE
Ability to insert snippets into input fields

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#61058]
```json
{
    "key": "ctrl+shift+alt+u",
    "command": "editor.action.insertSnippet",
    "args": {
        "snippet": "💄"
    },
},
```
I want to use it for scm inputbox (or find widget).

**Comment by joaomoreno** [comment]
@jrieken This seems to be like a snippet feature, as there's a lot of input fields across the workbench.

**Comment by jrieken** [comment]
Your instance of the editor must add the snippet controller (editor contribution) for that.

**Comment by jrieken** [comment]
Simply add the `SnippetController` here (https://github.com/Microsoft/vscode/blob/4d9f1d23a556dccd2c0fd5203923a24b21e41209/src/vs/editor/browser/widget/codeEditorWidget.ts#L68) and feel another round of ping pong if anything is still unclear

**Comment by joaomoreno** [comment]
@jrieken We do not use the monaco editor for SCM. I was force to drop that years ago because our API made the editor show up in unwanted places. It's just an input box.

**Comment by jrieken** [comment]
>  I was forced to drop that years ago because our API made the editor show up in unwanted places.

Well, things are better now. The extension view and preferences editor can do it, so could you

**Comment by usernamehw** [comment]
This is actually working now for `scm` input so I'm closing this.
