### ISSUE TITLE
The --wait switch no longer works

### ISSUE THREAD

**Issue by thomaslevesque** [Microsoft/vscode#61065]
I've been using VSCode as my Git editor for a while, with the following value for `core.editor`:

```
'C:\Program Files (x86)\Microsoft VS Code\Code.exe' --wait
```

It was working fine, but now Git keeps waiting after I closed the editor tab, so I suspect the process Git is waiting for is still running when it should stop.

(Using VSCode 1.28.1)

**Comment by rafalborczuch** [comment]
As a workaround you can add `-n` switch to force opening a new VS Code window.

**Comment by joaomoreno** [comment]
@bpasero I actually just saw this happen live when @rebornix was showing me a feature.

**Comment by bpasero** [comment]
@joaomoreno @thomaslevesque are you running this from the integrated terminal?

**Comment by thomaslevesque** [comment]
@bpasero no, running from an independent terminal

**Comment by thomaslevesque** [comment]
@bpasero in your scenario, it's a new instance of VSCode, and closing the tab closes VSCode, so it works. In my scenario I already have a VSCode instance running. The new tab is created in the existing window, so closing it doesn't close the window.

**Comment by bpasero** [comment]
@thomaslevesque I understand, but I cannot reproduce that either.

**Comment by joaomoreno** [comment]
@bpasero It was integrated terminal 👍

**Comment by bpasero** [comment]
@joaomoreno I cannot reproduce. 

**LOOK HERE: Everyone, what is your exact windows version?**

Adding @Tyriar for the integrated terminal.

**Comment by bpasero** [comment]
@joaomoreno @thomaslevesque wait, you are not using the actual code.exe in program files to do this right? That will not work, you must be using our "code" global command.

**Comment by thomaslevesque** [comment]
> Everyone, what is your exact windows version?

Windows 10 64bit v1803

> Does it reproduce without configuring any settings?

What kind of settings do you mean? The Git editor settings are as described in the first message (I think this setup was done by the Git for Windows installer)

> That will not work, you must be using our "code" global command.

Ah, that works! Thanks!

**Comment by joaomoreno** [comment]
> wait, you are not using the actual code.exe in program files to do this right? That will not work, you must be using our "code" global command.

The machine where I saw it happening was the demo booth machine, which wasn't set up by me. It was also a shiny new windows, with pretty much nothing installed but (1) Code and (2) Git. Afaik, Git can automatically configure Code as the default editor. It is possible that they are doing the wrong thing and using `code.exe` as the editor value. I can't check any more, since I'm not with the machine anymore...

If this is true, we might wanna follow up with the Git for Windows guys and get them to do the right thing.

**Comment by rebornix** [comment]
Some interesting workaround mentioned in https://github.com/Microsoft/vscode/issues/60192#issuecomment-429298203

**Comment by joaomoreno** [comment]
@bpasero That is exactly the problem. There's already an issue in the Git package: https://github.com/git-for-windows/git/issues/1875
