### ISSUE TITLE
externalConsole: true does not open terminal, just hangs

### ISSUE THREAD

**Issue by arve0** [Microsoft/vscode#6107]
- VSCode Version: 1.0.0
- OS Version: osx 10.11.4

Steps to Reproduce:

1. Create launch.json

  ```json
  {
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch",
			"type": "node",
			"request": "launch",
			"program": "${workspaceRoot}/dist/index.js",
			"stopOnEntry": false,
			"args": [],
			"cwd": "${workspaceRoot}/dist/",
			"preLaunchTask": null,
			"runtimeExecutable": null,
			"runtimeArgs": [
				"--nolazy"
			],
			"env": {
				"NODE_ENV": "development"
			},
			"externalConsole": true,
			"sourceMaps": false,
			"outDir": null
		},
		{
			"name": "Attach",
			"type": "node",
			"request": "attach",
			"port": 5858,
			"address": "localhost",
			"restart": false,
			"sourceMaps": false,
			"outDir": null,
			"localRoot": "${workspaceRoot}",
			"remoteRoot": null
		}
	]
  }
  ```

2. Press F5.

**What happens**: Debug-bar shows. If one goes to debug view, a small dot moves left to right, above *VARIABLES*.

**Expected**: A terminal should open.

If I change `externalConsole` to `false`, I can debug as normal *inside* vscode, but without any stdin.

**Comment by weinand** [comment]
@arve0 does it make a difference if you open the Terminal application first and then try to launch the debugging session?

**Comment by arve0** [comment]
No, it's the same with Terminal open or closed.

**Comment by weinand** [comment]
@arve0 if the Terminal application is not running, does VS Code make the Terminal application start when launching a debug session?

**Comment by arve0** [comment]
Not at the PC now, I'll have to check that later today.

**Comment by arve0** [comment]
> if the Terminal application is not running, does VS Code make the Terminal application start

No.

I've created a screen cast: https://youtu.be/xpZOi9hqT4M

Should also mention that I have a case *sensitive* file system. (You may notice that I'm using typescript 1.9.0-dev, ref #5161.)

**Comment by weinand** [comment]
@arve0 mentioning the case sensitive file system might have helped to find the problem: the node-debug extension references an AppleScript helper through a path with the wrong character case.

Could you please change the name of the Apple Script helper from `TerminalHelper.scpt` to `terminalHelper.scpt`. You can find the helper inside the VS Code application bundle:

`/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/extensions/node-debug/out/node/TerminalHelper.scpt`

**Comment by arve0** [comment]
Sweet! That worked 🎉 Thanks.
