### ISSUE TITLE
Allow debug session to exclude all other files except the current file

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#61079]
I'm in a scenario where I find neither of the debug options could help me efficiently stop on the line that I care about:

- Let's say, I'm rendering a component that's backed by some data object for 100 times.
- An exception is thrown in the component rendering logic. Stack trace points to a line in my component rendering code.
- I want to break on that single line when the exception is thrown.

My current options are all cumbersome:

- Breakpoint on that line: It'll be hit 100 times.
- Conditional breakpoints: I would need to know the reason for the exception to be thrown (something I don't know at the point of debugging), and guard against that in my condition.
- Break uncaught/all exception: I might hit 100 exceptions, while I only care about one of them. The exception might be caught by a node module and re-thrown, so I end up in a file I'm totally not interested in.

I think either of these two things would help me a lot:

- Allow me to exclude all other files, except the file I'm working on. So even if my line gets an exception thrown that's 100-levels down in the call stack, I can stay at the top level.
- Allow me to add "Exception Break Point", so that when an exception happens, it stops on the line that I care about, for example

```js
if (fun1(obj1) && fun2(obj2) && obc3.foo !== null) { // The line I'm interested in

}
```

The exception might be thrown inside executing `fun2(obj2)`, but I want to debug on the line where I can see obj1/obj2/obj3.
If this is inside a gulp task, the exception would be caught and re-thrown from files under `node_modules/gulp`, but none of the info in the `node_modules/gulp` folder would be useful for my debugging.

**Comment by octref** [comment]
After checking with @roblourens, this seems to be an issue where `skipFiles` don't work as expected:

- An error is thrown in a `gulp.task` callback function
- Gulp would catch this error and re-throw another one
- `skipFiles` has `node_modules/**/*` and `<node_internals>/**/*`
- When I start a debugging section with `All Exceptions` checked, I expect to hit the exception
- Observe: No exception hit.

https://github.com/octref/gulp-debug

**Comment by roblourens** [comment]
I filed https://github.com/Microsoft/vscode-node-debug2/issues/212, I don't know whether this is resolved by that issue or whether this is still an independent feature request?

**Comment by octref** [comment]
I guess what I want (exception breakpoints) are only possible in a time-traveling debugger.

I would still suggest making `node_modules/**/*` and `<node_internals>/**/*` the default for node launch config, though.
