### ISSUE TITLE
Downloading ubuntu repository index fails

### ISSUE THREAD

**Issue by jovere** [Microsoft/vscode#61075]
This isn't a vscode issue per se, but an MS server issue with getting the package.  When trying to download the following file needed for the package manager (http://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages.bz2) it freezes at a partial download and doesn't complete.  I've tried downloading manually as well as through the package manager, with no luck.

**Comment by Tyriar** [comment]
Are you still having this issue? There haven't been any other reports so it could have been a temporal issue.

**Comment by jovere** [comment]
Unfortunately, I am.  It makes no sense to me as to why it's happening.  It's only this repository.  It's as if there's a cache somewhere between my machine and the server that only has 99% of the file.  This is from a windows PC:
```
$ curl http://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages.bz2 -o Packages.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 98 72672   98 71397    0     0    630      0  0:01:55  0:01:53  0:00:02     0
```

And this is from the linux PC:
```
$ wget http://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages.bz2
--2018-10-23 07:29:13--  http://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages.bz2
Resolving packages.microsoft.com (packages.microsoft.com)... 40.76.35.62
Connecting to packages.microsoft.com (packages.microsoft.com)|40.76.35.62|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 72672 (71K) [application/octet-stream]
Saving to: ‘Packages.bz2’

Packages.bz2         99%[==================> ]  70.45K  --.-KB/s    eta 2s     
```

**Comment by jovere** [comment]
On a whim, I just changed it to HTTPS rather than HTTP.  That appears to be working.

**Comment by Tyriar** [comment]
Thanks, I let the repo admins know about this. Glad it's working for you!
