### ISSUE TITLE
Macbook with Touchbar Fn shortcuts malfunctioning

### ISSUE THREAD

**Issue by CrispinLin** [Microsoft/vscode#61078]
Issue Type: <b>Bug</b>

Since a recent update (sorry didn't notice which one), all F1-F12 shortcuts on the touchbar are not recognized correctly. Any key pressed with the Fn key are ignored. 
For example:
Pressing Cmd+F2 only performs F2, and Cmd+F3 only F3. 
This happens only when using the Fn keys on the touchbar. When using an external keyboard everything works fine.

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:07:48.477Z)
OS version: macOS high sierra 10.13.6

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.29GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
matlab|Gim|0.9.0
TabOut|alb|0.1.6
Bookmarks|ale|9.1.0
vscode-codetags|cg-|0.1.0
gitignore|cod|0.5.0
code-runner|for|0.9.4
easy-icons|jam|0.3.1
select-highlight-minimap|mde|0.0.8
python|ms-|2018.9.0
cpptools|ms-|0.19.0
code-settings-sync|Sha|3.1.2
codelf|unb|10.7.0
vscode-lldb|vad|1.0.0
vim|vsc|0.16.10

(2 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
I suggest to file a bug against Apple.
