### ISSUE TITLE
UI is slow when writing complex regexp for long files

### ISSUE THREAD

**Issue by digeff** [microsoft/vscode#61076]
- VSCode Version: 1.28.1
- OS Version: Windows 10 RS4

Steps to Reproduce:

1. Open a very long file
2. Start writing a regexp to replace in a single file. The regexp should be complex and have a lot of matches all over the file.

Does this issue occur when all extensions are disabled?:
It happens with extensions disabled, but it's not as bad (It's still bad though)

**Comment by rebornix** [comment]
We run the search in main thread and a slow search can slow down the whole UI, the solution can be either disable auto search https://github.com/microsoft/vscode/issues/60977 or thinking about how to move it off main thread (then fix https://github.com/microsoft/vscode/issues/30874 completely). Track this issue in the two detailed one.
