### ISSUE TITLE
Restart to update always fail

### ISSUE THREAD

**Issue by alencar** [Microsoft/vscode#61085]
We have written the needed data into your clipboard because 
Issue Type: <b>Bug</b>

1. Uninstall VS Code "standard"
2. Install VS Code "user setup"
3. Wait for an update
4. Click on the update link and chose "Restart to Update"
5. The update will fail

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|15.90GB (2.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|mau|1.3.7
vscode-azureterraform|ms-|0.2.2
vscode-kubernetes-tools|ms-|0.1.14
mssql|ms-|1.4.0
python|ms-|2018.9.0
azure-account|ms-|0.4.3
cpptools|ms-|0.19.0
Go|ms-|0.6.91
PowerShell|ms-|1.9.0
vscode-docker|Pet|0.3.1
vscode-yaml|red|0.0.17
vscode-fileutils|sle|2.11.0
vscode-ansible|vsc|0.5.1

</details>
it was too large to send. Please paste.

**Comment by joaomoreno** [comment]
How does the update fail? Is there a log file, do you have a screenshot?

**Comment by alencar** [comment]
The problem is related to this:
![image](https://user-images.githubusercontent.com/1740176/47733510-99fa0480-dc25-11e8-8066-30815a6d5ed2.png)

%AppData%\Local\Programs\Microsoft VS Code\Code.exe is somehow protected, as it is always open by SYSTEM. Even with admin rights, it is not possible to delete it. Same for the installer, it will fail because it will not be able to rename the current file.

Looking through Process Explorer, it is always open by System

![image](https://user-images.githubusercontent.com/1740176/47733971-a3d03780-dc26-11e8-8538-c1bb9f86d011.png)

It is not possible to close that file handler

![image](https://user-images.githubusercontent.com/1740176/47734251-3cff4e00-dc27-11e8-9d1f-4aa2797fe371.png)
