### ISSUE TITLE
is there a setting to enable the search results to display line numbers in the list?

### ISSUE THREAD

**Issue by 10manjunath** [Microsoft/vscode#61083]
Issue Type: <b>Feature Request</b>

In the codebase, after searching for a specific phrase, it displays the result with a list of files and every line has the highlighted search phrase. I would also like to see the line numbers to the left.  

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:13:53.910Z)
OS version: Windows_NT x64 10.0.14393

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/39219
