### ISSUE TITLE
ZH-TW | VS Code 1.0 Unable to Work with English Command Correctly

### ISSUE THREAD

**Issue by terrysheng** [Microsoft/vscode#6108]
![screen](https://cloud.githubusercontent.com/assets/18434825/15028289/f336ac88-11fc-11e6-9af1-e93075cfc5ee.png)
Steps to Reproduce:

1. execute "code . --locale=zh-tw" in command prompt to launch VS Code 1.0 with Chinese Taiwan UI.
2. press "F1" to show command palette and try to input ">configure".
3. input Chinese Traditional chars ">設定" instead.
(please refer to my screenshot attached)

result:
No result for searching keywords started from "configure", but searching "設定" worked.

expectation:
"Commands" in command palette should not be localized.

In addition, the issue here is not about the “searchable”. It is how the user input command.
For example, if a user wants to switch to a git branch, he inputs >git: branch in EN locale of VSCode. (and “git branch” in command prompt)
But in zh-tw locale, “>git: branch” command doesn’t work, and user have to input “>git: 分支” instead.
I believe most of the local developers won't use IME to input Chinese characters for command input.

So, I suggest we can support the command in both English and localized string (e.g. Chinese Traditional)
Thanks.
Terry

**Comment by Treri** [comment]
please see #4679

**Comment by bpasero** [comment]
You can give it a try from our insiders release today: http://code.visualstudio.com/Download#insiders
