### ISSUE TITLE
Search keeps old results when updated in the middle of another search

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#61081]
Issue Type: <b>Bug</b>

* Open [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped). You need a large directory that takes time to search.
* Ctrl-shift-f to open search.
* Search for `"lib": [`. There will be a lot of results that start filling in.
* Quickly type `x` and hit enter, so you're searching for `"lib": [x`. There ought to be no results, but there are -- when I tried it there were still 3165 results (though in another test there were 1117, since it's timing based) -- all of them were just `"lib": [`, meaning that some old search results weren't removed when the search changed.

Note I'm running this on Linux and on DefinitelyTyped vscode runs out of file watchers, though I don't think that should affect this case.

VS Code version: Code - Insiders 1.29.0-insider (f151c46b1783cf4f9a4ca934a85f78846f08688e, 2018-10-11T05:12:53.188Z)
OS version: Linux x64 4.13.0-43-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 3237)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 12, 7|
|Memory (System)|7.63GB (0.68GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by roblourens** [comment]
Great catch!
