### ISSUE TITLE
After installation 1.28.1, my debug extension does not show the entire call stack.

### ISSUE THREAD

**Issue by killerall** [Microsoft/vscode#61088]
Issue Type: <b>Bug</b>

After installation 1.28.1, updated from version 1.27.2, my debug extension does not show the entire "call stack".

Previous behavior (1.27.2):
The stack was fully displayed:
![image](https://user-images.githubusercontent.com/4764609/47049584-1d225180-d174-11e8-894c-caf089b2e96f.png)

New behavior (1.28.1):
If the source code is not found in the folder (s) the stack item is not displayed:
![image](https://user-images.githubusercontent.com/4764609/47049751-9cb02080-d174-11e8-87f3-51b75d12050c.png)

My debug extension sends the following json response to the StackTrace request:

```
{  
  "seq":19,
  "success":true,
  "message":null,
  "request_seq":9,
  "command":"stackTrace",
  "body":{  
    "stackFrames":[  
      {  
        "id":1001,
        "source":{  
          "name":"test.tlpp",
          "path":"c:\\vscode\\tlpp-unit-test\\test\\test.tlpp",
          "sourceReference":0
        },
        "line":10,
        "column":0,
        "name":"U_MYFINAL"
      },
      {  
        "id":1002,
        "source":{  
          "name":"APLIB190.PRW",
          "path":"APLIB190.PRW",
          "sourceReference":0
        },
        "line":164,
        "column":0,
        "name":"EXECBLOCK"
      },
      {  
        "id":1003,
        "source":{  
          "name":"MSFINAL.PRW",
          "path":"MSFINAL.PRW",
          "sourceReference":0
        },
        "line":64,
        "column":0,
        "name":"FINAL"
      },
      {  
        "id":1004,
        "source":{  
          "name":"FWAPP.PRW",
          "path":"FWAPP.PRW",
          "sourceReference":0
        },
        "line":600,
        "column":0,
        "name":"{ || PSWWPCOMMIT())}"
      },
      {  
        "id":1005,
        "source":{  
          "name":"FWAPP.PRW",
          "path":"FWAPP.PRW",
          "sourceReference":0
        },
        "line":714,
        "column":0,
        "name":"{ || EVAL(BCLOSE)}"
      },
      {  
        "id":1006,
        "source":{  
          "name":"FWAPP.PRW",
          "path":"FWAPP.PRW",
          "sourceReference":0
        },
        "line":714,
        "column":0,
        "name":"ACTIVATE"
      },
      {  
        "id":1007,
        "source":{  
          "name":"APLIB000.PRW",
          "path":"APLIB000.PRW",
          "sourceReference":0
        },
        "line":123,
        "column":0,
        "name":"SIGAFAT"
      }
    ]
  },
  "type":"response"
}

```
Has something changed that I need to implement in my extension?

PSC
I tested the insiders and behavior continues the same as 1.28.1.

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:13:53.910Z)
OS version: Windows_NT x64 10.0.15063

<details>

<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.87GB (8.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|0.12.0
tslint|eg2|1.0.40
advpl-vscode|Kil|0.10.12
cmake-tools-helper|mad|0.2.1
Angular-BeastCode|Mik|6.2.32
cpptools|ms-|0.19.0
debugger-for-chrome|msj|4.10.2
vscode-coverage-gutters|rya|2.2.0
cmake|twx|0.0.17
cmake-tools|vec|1.1.2

</details>

**Comment by isidorn** [comment]
@killerall thanks for reporting this issue. Does your extension [`supportsDelayedStackTraceLoading`](https://github.com/Microsoft/vscode/blob/c762e7868a24d3e6cc0e1eb6a6eaa1bd9ec61786/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L1190). If you return [`totalFrames`](https://github.com/Microsoft/vscode/blob/c762e7868a24d3e6cc0e1eb6a6eaa1bd9ec61786/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L744) as part of the `StackTraceResponse` does that make a difference?

@killerall For the future since you are an extension author it would be great if you could be using Insider - that way we would be able to find issue like this sooner.

fyi @weinand

**Comment by killerall** [comment]
@isidorn thanks for the answer.

I just implemented and tested the totalFrames in response. There was no difference.

I usually use the Insider, but I'm not programming in ADPVL so often. I'll ask some user keys to use the Insider as well. Thank you.

**Comment by killerall** [comment]
> Thanks. Does your extension [`supportsDelayedStackTraceLoading`](https://github.com/Microsoft/vscode/blob/c762e7868a24d3e6cc0e1eb6a6eaa1bd9ec61786/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L1190).
> Does changing that capability make a difference?

No.
But I found what changed.
https://github.com/Microsoft/vscode/commit/f8a736c017d00bd2b1719297fa9960070ad13275#diff-05910b80b38cefe548a9d4f9c9d6c78e

In the latest version of Uri.ts, it throws exceptions if it can not find the file.

The getCallStackImpl method of the debugModel.ts class stops adding the elements in the stack if any exceptions are thrown.

```

	private getCallStackImpl(startFrame: number, levels: number): TPromise<IStackFrame[]> {
		return this.session.stackTrace(this.threadId, startFrame, levels).then(response => {
			if (!response || !response.body) {
				return [];
			}


			if (this.stoppedDetails) {
				this.stoppedDetails.totalFrames = response.body.totalFrames;
			}


			return response.body.stackFrames.map((rsf, index) => {
				const source = this.session.getSource(rsf.source);


				return new StackFrame(this, rsf.id, source, rsf.name, rsf.presentationHint, new Range(
					rsf.line,
					rsf.column,
					rsf.endLine,
					rsf.endColumn
				), startFrame + index);
			});
		}, (err: Error) => {
			if (this.stoppedDetails) {
				this.stoppedDetails.framesErrorMessage = err.message;
			}


			return [];
		});
	}

```

**Comment by isidorn** [comment]
@killerall great find!
@weinand can you maybe look into this since you are already in URI land?
I would assume here is the issue https://github.com/Microsoft/vscode/blob/d08e54002bf38b0f584ec39a16af92fe923538cb/src/vs/workbench/parts/debug/common/debugSource.ts#L55

**Comment by weinand** [comment]
The new URI.parse behaviour in VS Code 1.28.1 results in an exception if the "path" attribute of a "Source" is not absolute.

I've added a workaround to restore the previous behaviour.

However, returning relative paths in a "Source" object and having a "sourceReference" with value 0 at the same time does not make any sense. 

@killerall here is the explanation:
- VS Code can only match absolute "Source.path" values against workspace files. Relative paths are not supported because VS Code has no notion of a "current directory" against the relative path can be applied.
- a relative "Source.path" can only be provided (e.g. for display purposes) if it is accompanied by a "Source.sourceReference" > 0. In this case VS Code uses the "sourceReference" to retrieve the contents of the source from the debug adapter.

So all but the first "Source" objects in the json response from above are incorrect because they have relative paths and a "sourceReference" of 0.

**Comment by killerall** [comment]
@weinand Thanks for the answer.
 I did not understand the sourceReference correctly.
In the following stack example:

function1 - Source1
function2 - Source2
function3 - Source1

Let's assume that the Source2 source file is not in the workspace. Should I return a SourceResponse with blank content?

If this is the correct behavior, I will change my extension.

**Comment by weinand** [comment]
This is a correct source object because "path" is absolute:
```js
        "source":{  
          "name":"test.tlpp",
          "path":"c:\\vscode\\tlpp-unit-test\\test\\test.tlpp",
          "sourceReference":0
        },
```

This source object is incorrect because "path" is relative:
```js
        "source":{  
          "name":"APLIB190.PRW",
          "path":"APLIB190.PRW",
          "sourceReference":0
        },
 ```

Just make "path" absolute by adding the containing folder to the path.
This applies to both files in the workspace and files outside of it.

So something like this:
```js
        "source":{  
          "name":"APLIB190.PRW",
          "path":"c:\\vscode\\tlpp-unit-test\\test\\APLIB190.PRW",
          "sourceReference":0
        },
 ```

**Comment by killerall** [comment]
@weinand Thank you very much for the quick reply.

The problem is the source code APLIB190, for example, is not available in the workspace, and DA does not know it either (similar to a dynamic library that does not have the source code).

If I could understand. I should send sourceReference (in APLIB090), and when DA receives the request, I return the content as: "source code is not available".

This is correct?

**Comment by weinand** [comment]
@killerall yes, your approach is basically correct.

But please consider this: even if the source is not available in your workspace (or outside), there is probably a binary file (e.g. a dynamic library) somewhere in the filesystem. And this file has a path. In this case I recommend to return that path. VS Code will automatically show  an error if it cannot show the contents of the file in an editor.

**Comment by killerall** [comment]
Understood.
Thank you very much for your attention.
I will change as soon as possible.

**Comment by weinand** [comment]
@killerall it would be great if you could verify that your (unmodified) debug extension works in the latest Insiders.

**Comment by killerall** [comment]
@weinand 
I tested it and it worked perfectly. 

Thanks a lot.

**Comment by weinand** [comment]
Great, I'll add a verified label.
