### ISSUE TITLE
VS Code not shutting down nodejs server

### ISSUE THREAD

**Issue by DanHibbert** [Microsoft/vscode#61082]
Issue Type: <b>Performance Issue</b>

Create asp.net core web api with create-react-app  client side app
launch.json configured to run compound task 1)launching the back end and 2)opening Chrome 

I've noticed that when I stop debugging (both tasks) and start again when I check Task Manager, VS Code still has child Node.js Server-side javascript process running.  These processes don't take any CPU but still use ~500mb Memory.  This causes the memory usage of VS Code to ramp up - so over the course of a working day, I have to stop and start VS Code multiple times or my machine slows down significantly

VS Code version: Code - Insiders 1.29.0-insider (a0b91c2c5dff3ad25aab867f4692d08c700d5c10, 2018-10-16T07:33:17.566Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.83GB (8.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    92	 12052	code-insiders main
    0	   205	  3484	   gpu-process
    0	    24	 11904	   utility
    0	   191	 13328	   window (MainModule.cs - FundManager - Visual Studio Code - Insiders)
    0	    40	 18976	     searchService
    0	    15	 19436	     watcherService 
    0	    12	 24808	       console-window-host (Windows internal process)
    0	   108	 19732	     extensionHost
    0	     9	 11840	       cmd /s /c "C:\Users\dhibbert\.vscode-insiders\extensions\ms-vscode.csharp-1.16.2\.omnisharp\1.32.5\OmniSharp.exe -s c:\Dev\repos\FundManager\FundManager.sln --hostPID 19732 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4"
    0	   293	 10496	         C:\Users\dhibbert\.vscode-insiders\extensions\ms-vscode.csharp-1.16.2\.omnisharp\1.32.5\OmniSharp.exe  -s c:\Dev\repos\FundManager\FundManager.sln --hostPID 19732 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4
    0	    12	 10776	         console-window-host (Windows internal process)
   18	    25	 23404	       C:\WINDOWS\System32\wbem\WMIC.exe process get CommandLine,CreationDate,ParentProcessId,ProcessId
    0	    12	  2144	         console-window-host (Windows internal process)
    0	    15	 24244	     electron-crash-reporter
    0	    70	 18792	   shared-process
    1	    74	 25352	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (MainModule.cs - FundManager - Visual Studio Code - Insiders)
|    Folder (FundManager): 1709 files
|      File types: cs(377) js(215) dll(177) variables(155) overrides(147)
|                  css(130) cache(73) json(70) pdb(56) less(48)
|      Conf files: csproj(12) package.json(2) gulp.js(2) sln(1) launch.json(1)
|                  settings.json(1) tasks.json(1) jsconfig.json(1)
|                  webpack.config.js(1)
|      Launch Configs: coreclr(4) chrome edge;
```

</details>
<details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
sort-imports|ama|6.0.0
vscode-eslint|dba|1.6.1
es7-react-js-snippets|dsz|1.8.7
gitlens|eam|8.5.6
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.4.2
vscode-nuget-package-manager|jmr|1.1.6
dotnet-core-commands|mat|1.0.6
mssql|ms-|1.4.0
azure-account|ms-|0.4.3
csharp|ms-|1.16.2
team|ms-|1.142.0
debugger-for-chrome|msj|4.10.2
debugger-for-edge|msj|1.0.6
material-icon-theme|PKi|3.6.0
vscode-icons|rob|7.27.0

(2 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
