### ISSUE TITLE
Source control icon is blinking every few seconds

### ISSUE THREAD

**Issue by ryanmortier** [Microsoft/vscode#61080]
![image](https://user-images.githubusercontent.com/2053960/47043898-d07f4c00-d15c-11e8-9364-382e6d42dd09.png)

- VSCode Version: 1.28.1
- OS Version: macOS 10.14 Mojave

Steps to Reproduce:

1. Open a folder with initialized git repository

Does this issue occur when all extensions are disabled?: Yes

There was a similar issue back in February: #43234

This bug appears to have resurfaced.

**Comment by joaomoreno** [comment]
If you run with `code --verbose`, do you see file change events from within that repo which might explain the constant refreshing?

**Comment by ryanmortier** [comment]
I can't seem to replicate the issue anymore. Nothing has changed but for some reason it isn't doing it anymore.

Closing for now I guess.
