### ISSUE TITLE
Extensions: Review public gallery API access

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#61095]
From @damccorm

> @joaomoreno this generally looks fine to me, a couple thoughts though.
> 
> 1. We use queryParams to encode variables into the url instead of passing them in the request as data. Not sure if the API is ok accepting them both ways or not, but the recommended way for [all of these REST API's](https://docs.microsoft.com/en-us/rest/api/vsts/?view=vsts-rest-4.1) is through the url. So with your parameters our requests end up looking like: {base_url}/_apis/public/gallery/extensionQuery?pagenumber={pagenumber}&pageSize={pageSize}&flags.a={flags.a}&flags.b={flags.b}&etc...
> 2. Similarly, we encode the extensionId as a [route value](https://github.com/Microsoft/azure-devops-node-api/blob/8b877def56f58a581edb29debd8c7c6f4b37d481/api/GalleryApi.ts#L1635), which means it gets placed in the url like: {base_url}/_apis/public/gallery/extensionQuery/**{extensionId}**?{queryValues}. Again, not really sure whether the API can accept it the way you're sending it/will support that going forward, but that is at least how we do it and our code is generated directly from the REST endpoint.

From https://github.com/Microsoft/vscode-vsce/issues/297

**Comment by sandy081** [comment]
Closing for the same reason as https://github.com/Microsoft/vscode-vsce/issues/297#issuecomment-489092844
