### ISSUE TITLE
[bug?] "window.titleBarStyle": "custom" broke color theme?

### ISSUE THREAD

**Issue by V0idk** [Microsoft/vscode#61105]
- VSCode Version: since code_1.28.0-1538751525_amd64.deb
- OS Version: ubuntu

Steps to Reproduce:
1.  "window.titleBarStyle": "native" 

![2018-10-17 10-24-15](https://user-images.githubusercontent.com/17514799/47058263-eccfc700-d1f6-11e8-97c9-b12ae152cacd.png)

2. "window.titleBarStyle": "custom"

![2018-10-17 10-24-45](https://user-images.githubusercontent.com/17514799/47058262-eccfc700-d1f6-11e8-862c-5a1844fbe8cd.png)

**Comment by Tyriar** [comment]
What theme are you using?

**Comment by V0idk** [comment]
@Tyriar Cobalt2 Theme Official

**Comment by sbatten** [comment]
@V0idk the theme needs to add a color for menu background. You can add your own override in settings like so:

```
    "workbench.colorCustomizations": {
        "[Cobalt2]": {
            "menu.background": "#ff0000"
        }
    }
```
