### ISSUE TITLE
Add api command so that extensions can lazily resolve code lenses

### ISSUE THREAD

**Issue by daytonellwanger** [microsoft/vscode#61100]
VSCode Version: 1.29.0-insider (10/16 build)
OS Version: Win10

The following single-file extension will reproduce this issue:
```
'use strict';

import * as vscode from 'vscode';

export async function activate(context: vscode.ExtensionContext) {
    let documentUri = 'C:/Program Files/Microsoft VS Code Insiders/resources/app/extensions/node_modules/typescript/lib/lib.dom.d.ts';
    await vscode.workspace.openTextDocument(documentUri);
    await vscode.commands.executeCommand<vscode.CodeLens[]>('vscode.executeCodeLensProvider', vscode.Uri.file(documentUri), Number.MAX_VALUE);
}

export function deactivate() {}
```

Open a file in VS Code with this extension installed. No language services will work (hover, find all refs, go to definition, ...). All will result in "infinite" loading (they do eventually come back online once `executeCodeLensProvider` returns, but this can take ~10 minutes).

This is clearly because of the `Number.MAX_VALUE` argument. If this is set to 10, e.g., things behave fine. My concern is that this is a regression - the current version of stable doesn't have this issue - and I'd like to have all code lenses for the document resolved.

**Comment by daytonellwanger** [comment]
Note: this happens with no other extensions installed.

There's also another concern here that extensions can lock up the core experience.

**Comment by daytonellwanger** [comment]
@jrieken

**Comment by mjbvz** [comment]
Yes that file has like 10,000 symbols so even if we're resolving them relatively quickly it's still going to be slow

What are does your extension need all the resolved code lenses for?

**Comment by daytonellwanger** [comment]
The extension is Live Share. To remote Code Lenses to guests, we ask the host machine for all the Code Lenses a document has. 

As for this being a regression, the line
```
await vscode.commands.executeCommand<vscode.CodeLens[]>('vscode.executeCodeLensProvider', vscode.Uri.file(documentUri), Number.MAX_VALUE);
```
in the above sample extension returns in ~1s on Stable (1.26.1 anyway). On Insiders, it's ~10 minutes.

**Comment by daytonellwanger** [comment]
@mjbvz have you decided to not treat this as a regression? i.e. should this be closed as expected behavior? If so, how do you propose to resolve Code Lenses for a document with a large number of Code Lenses? As per [this discussion](https://github.com/Microsoft/vscode/issues/44846), I didn't think there was any other way.

**Comment by mjbvz** [comment]
@daytonellwanger Eagerly resolving all codes lenses seems wrong, even if it doesn't take 10 minutes. @jrieken Is there some way that liveshare could these resolve code lenses lazily, like we do in `CodeLensProvider`?

Will take a look at why it takes so long in November

**Comment by jrieken** [comment]
> @jrieken Is there some way that liveshare could these resolve code lenses lazily, like we do in CodeLensProvider?

We currently don't expose the resolve functions as commands but instead we allow to resolve N (defined by an arg) eagerly

**Comment by mjbvz** [comment]
Closing as we haven't seen much demand for such an api
