### ISSUE TITLE
closePanel fails when viewing terminal

### ISSUE THREAD

**Issue by safield** [Microsoft/vscode#61108]
Version: 1.29.0-insider
Commit: f151c46b1783cf4f9a4ca934a85f78846f08688e
Date: 2018-10-11T05:12:53.188Z
Electron: 2.0.11
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

OS: Linux Mint 19

When I have the panel open, and the current panel view is set to terminal, executing the command _closePanel_ fails for certain key bindings.

For example I have _closePanel_ mapped to "escape" key.

In this case, hitting escape will close the panel when in _Problems_, _Output_, and _Debug_ view, but fails when in terminal view.

ctrl+j for _closePanel_ also succeeds for _Problems_, _Output_, and _Debug_ view, but fails when in terminal view.

But, ctrl+shift+q for example always succeeds even when the panel view is currently terminal.

It seems like the terminal is eating keyboard shortcuts.

**Comment by usernamehw** [comment]
Settings:
```diff
"terminal.integrated.commandsToSkipShell": [
+    "workbench.action.closePanel",
```

Should probably be there by default.

**Comment by Tyriar** [comment]
It's not the default because then you wouldn't be able to use vim ☹️
