### ISSUE TITLE
Default text color for non-current tabs in light themes does not pass the color contrast ratio check.

### ISSUE THREAD

**Issue by infinnie** [Microsoft/vscode#61106]
![image](https://user-images.githubusercontent.com/8168391/47058409-85fedd80-d1f7-11e8-8769-4dfca139cbd9.png)
Text color on tabs that are not the current tab have a contrast ratio of only 2.70:1 against its background in light themes such as Visual Studio Light. The corresponding color in the dark theme does pass the check.

Considering that those tabs are clickable, they should not be considered “inactive” items.

**Comment by misolori** [comment]
Fixed via https://github.com/Microsoft/vscode/commit/29733d7aaa7b9c4c25765b46f2fdcc3bec1054df
