### ISSUE TITLE
multiple auto-update windows opened, leading to corrupted install

### ISSUE THREAD

**Issue by tvald** [Microsoft/vscode#61101]
- VSCode Version: not sure, can't launch VSCode anymore
- OS Version: Windows 10

Steps to Reproduce:
1. Install VSCode with user installer.
2. Close multiple VSCode editors in quick succession.

Observed Behavior:
1. Two setup / update dialogs pop up
-- The first window said something like "close all VSCode windows and then click retry".
-- The second window hung when I alt-tabbed to it ("application is not responding"), then crashed after a few minutes.
2. I clicked "retry" on the first window. It showed the same message again after a moment.
3. I clicked "cancel" on the first window. It disappeared.
4. I try to launch VSCode from the Start Menu, and a message pops up saying the shortcut target is missing. As best as I can tell, VSCode is no longer installed on my system.

Does this issue occur when all extensions are disabled?: can't launch VSCode anymore

**Comment by joaomoreno** [comment]
This is pretty strange. If you see it happen again, please take a screenshot, I'd love to see it.

For now, fully reinstall VS Code.
