### ISSUE TITLE
Update fails: Code.exe The process cannot access the file because it is being used by another process.

### ISSUE THREAD

**Issue by brandstaetter** [Microsoft/vscode#61118]
Issue Type: <b>Bug</b>

Wait for auto-update or trigger the update manually.
Update fails to open the file handle on Code.exe, even though it is not running.
LockHunter shows "System" as locking the file.

Also, updating from the installer only works if I try it after a reboot without opening vscode before.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.79GB (7.73GB free)|
|Process Argv|C:\Users\hbrandstaetter\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>
[vscode-inno-updater-1539757127.log](https://github.com/Microsoft/vscode/files/2486089/vscode-inno-updater-1539757127.log)

Extension|Author (truncated)|Version
---|---|---
auto-build|mar|0.1.0
cpptools|ms-|0.19.0
platformio-ide|pla|1.4.0

</details>

**Comment by stewest** [comment]
Same here on MacOs 10.13.6 (17G2307) Code Version 1.27.2 (1.27.2)

**Comment by wijkjh** [comment]
It also fails on 1.28.0 (user setup), Windows 10 version 1803.
[vscode-inno-updater-1540287295.log](https://github.com/Microsoft/vscode/files/2505532/vscode-inno-updater-1540287295.log)

**Comment by stewest** [comment]
I removed and re-installed Version 1.28.2 (1.28.2) for MacOs (High sierra) and it works now, without continuously trying to update.
