### ISSUE TITLE
Please add the file/folder cut command to the context menu and the releated shortcut.

### ISSUE THREAD

**Issue by metasong** [Microsoft/vscode#61110]
vscode is a code editor, and cut/paste should be in Explorer View, and it is not related to any extensions, it is basic file operation...

without this command the file management functionality is not complete!

since the file/folder drag drop function is available, why this command is not available!

it's really strange this feature request is closed #57616. please value the voice from vscode fans!

**Comment by metasong** [comment]
no reponse??

**Comment by isidorn** [comment]
We will discuss this in this week's ux meeting and we will let you know what we decide.
In the menatime install the extension which adds it

**Comment by metasong** [comment]
ok, thanks! for my conern, this should not be put in any extension. this is a feature to make vscode a true files edit

**Comment by isidorn** [comment]
You can try this out from tomorrow's vscode insiders
