### ISSUE TITLE
open file map erroer!!!

### ISSUE THREAD

**Issue by WuG978** [Microsoft/vscode#61116]
![tim 20181017145700](https://user-images.githubusercontent.com/38772075/47067926-73979a80-d21d-11e8-828f-cf6a778c50b3.png)
![tim 20181017145700](https://user-images.githubusercontent.com/38772075/47067845-316e5900-d21d-11e8-9c90-a42914ad51e4.png)
Issue Type: <b>Bug</b>

After debuging my code, this words"open file map error" will display on the Debug console .How to deal with this problem?

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:13:53.910Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (2.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.28.2
python|ms-|2018.9.0

</details>

**Comment by WuG978** [comment]
> 使用英语要好得多。

I change the default language,but this problem still exist.   So bad, this problem drive me crazy.
![544e674efd9911e086c6b0d9cdc79ae](https://user-images.githubusercontent.com/38772075/47066614-3e894900-d219-11e8-8102-50b647729448.png)

**Comment by successgdc** [comment]
I mean your problem description in your screenshot.

**Comment by WuG978** [comment]
> I mean your problem description in your screenshot.
![image](https://user-images.githubusercontent.com/38772075/47067952-8b6f1e80-d21d-11e8-89ff-00f81cd6cf08.png)

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-python/
