### ISSUE TITLE
How to deal with this problem about"open file map error！" 

### ISSUE THREAD

**Issue by WuG978** [Microsoft/vscode#61114]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on [
![544e674efd9911e086c6b0d9cdc79ae](https://user-images.githubusercontent.com/38772075/47064791-62499080-d213-11e8-9730-8e0c6692d741.png)
](https://stackoverflow.com/questions/tagged/visual-studio-code.[](url))

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/61116
