### ISSUE TITLE
JavaScript Intellisense shows TypeScript keywords

### ISSUE THREAD

**Issue by CarterLi** [Microsoft/vscode#61115]
Issue Type: <b>Bug</b>

1. open a js file
2. type `im`

The typescript keyword `implements` shows before `import`

Expected behavior: don't show typescript keywords in javascript file

![image](https://user-images.githubusercontent.com/6134068/47065821-ddf90c80-d216-11e8-8782-36d6ac1b52d4.png)

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:07:48.477Z)
OS version: Darwin x64 18.0.0

Does this issue occur when all extensions are disabled?: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.26GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
indent4to2|Com|0.1.2
vscode-todo|Mat|0.8.0
ejs-language-support|Qas|0.0.1
html-css-class-completion|Zig|1.17.1
html-snippets|abu|0.2.1
vscode-caniuse|aga|0.5.0
color-info|bie|0.5.0
open-html-in-browser|cod|0.1.21
gitignore|cod|0.5.0
dart-code|Dar|2.19.0
vscode-markdownlint|Dav|0.20.0
vscode-eslint|dba|1.6.1
vscode-dash|dee|2.0.0
githistory|don|0.4.3
gitlens|eam|8.5.6
vscode-npm-script|eg2|0.3.5
vimL|fal|0.0.3
php-debug|fel|1.12.6
php-intellisense|fel|2.3.5
php-pack|fel|1.0.2
vscode-nginx-conf-hint|han|0.1.0
angular-bootstrap|her|4.0.9
beautify|Hoo|1.4.4
icon-fonts|idl|2.1.2
gitlab-mr|jas|1.4.1
vscode-map-preview|jum|0.4.2
codeacejumper|luc|1.1.8
rainbow-csv|mec|0.7.1
vscode-stylefmt|mrm|2.5.0
vscode-language-pack-zh-hans|MS-|1.28.2
python|ms-|2018.9.0
cpptools|ms-|0.19.0
csharp|ms-|1.16.2
Go|ms-|0.6.91
mono-debug|ms-|0.15.8
vetur|oct|0.13.0
vscode-icons|rob|7.27.0
sass-indented|rob|1.4.9
rust|rus|0.4.10
vscode-nginx|sha|0.5.0
gitconfig|sid|2.0.0
vscode-csstree|sme|0.7.0
cmake|twx|0.0.17
cmake-tools|vec|1.1.2
highlight-matching-tag|vin|0.6.1
vscode-todo-highlight|way|1.0.4
swig-tpl|zha|0.0.6
swig|zhu|0.0.5

(3 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/Microsoft/TypeScript/issues/27955 to track this upstream
