### ISSUE TITLE
[Suggestion] User should get a message if there is no extension installed for VSCode.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#6111]
Testing : https://github.com/Microsoft/vscode/issues/6099
- VSCode Version: 1.1.0-alpha
- OS Version: Windows10\Linux\MAC

When there is no extension installed for VSCode then it should display some friendly message like " There is no extension installed for VScode". Right now "code --list-extensions" is not displaying  any message on command prompt.

**Comment by joaomoreno** [comment]
As designed. Usually, cli tools work this way.
