### ISSUE TITLE
Option to enable/disable auto closing GUI tabs

### ISSUE THREAD

**Issue by beastdestroyer** [Microsoft/vscode#61113]
Issue Type: Feature Request

VSCode 1.29-insiders and Exploration 
Windows 10 1803 17134.345

1. Open Settings GUI
2. Notice on tab, it opens with italics, meaning clicking on a different file will close it and open the file instead. 
3. Open Keyboard shortcuts GUI, notice it doesn't have italics, meaning opening another file won't close it.

Note: 2. occurs with Extension previews too. 

It would be nice if they could stay open until the user actually closes it, or perhaps it could be dependant on an option such as `workbench.keepTabsOpen` or something, where `true` means all GUIs such as setting will open as a tab that can't close until the x is pressed, or `false`, where all GUIs will close when clicking a new file too.

**Comment by nealot** [comment]
See https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode.

**Comment by beastdestroyer** [comment]
Oh thx, just what I was looking for.
