### ISSUE TITLE
python code hints won't show sometimes

### ISSUE THREAD

**Issue by yangbocheng** [Microsoft/vscode#61117]
Issue Type: <b>Bug</b>

python 3.6
create file below:
-project
---directory1
------a1.py
---directory2
------a2.py
where in a2.py ,write a function of a1,then run a2.py ,,,,it can run correctly
but!!!!
int a2,i can never see the code hints of function a1,.

otherwise, vscode have ofen lost code hints when i write python. In order to get code hints, I have to restart vscode, sometimes vscode can rework correctly.
that's why???

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:13:53.910Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|15.88GB (8.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.17.0
jupyter|don|1.1.4
vscode-language-pack-zh-hans|MS-|1.28.2
python|ms-|2018.9.0
cpptools|ms-|0.19.0
csharp|ms-|1.16.2
vscode-icons|rob|7.27.0
jinja|who|0.0.8

</details>

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-python/
