### ISSUE TITLE
Using native Windows OpenSSH client rather than Putty?

### ISSUE THREAD

**Issue by xfudox** [Microsoft/vscode#61120]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/visual-studio-code.
Already done [here](https://stackoverflow.com/questions/52801135/using-vs-code-with-native-windows-openssh-client)

I'm trying to move from Putty/Pagent/Plink to Windows native OpenSSH client, but i'm struggling.

I've already enabled the OpenSSH agent service to start automatically, added my ssh key with the ssh-add command, but any time i try to write to origin (e.g.: push) i got a popup with

> Git: FATAL ERROR: Disconnected: No supported authentication methods available (server sent: public key)

Trying to push from command line give also

> Please make sure you have the correct access rights and the repository exists.

I'm sure the ssh key and the acces rights are correcty set since I menaged to  configure TortoiseGit to use Windows native OpenSSH client and I can do any operation without error.

The only difference is that in TortoiseGit I can choose the ssh manager, opposite to VSCode

**Comment by joaomoreno** [comment]
This sounds like a configuration issue independent of VS Code. Asking in SO is the right thing to do.
