### ISSUE TITLE
Toggle Menu bar gives no effect

### ISSUE THREAD

**Issue by kaytrance** [Microsoft/vscode#61128]
If I toggle "Toggle Menu bar" option from View->Appearance menu I expect top menu bar to disappear (or to be visible by hitting Alt key) but despite me selecting this option from menu bar or from command palette menu bar remains visible all time.

Take a look at gif below. There I tried to select that option couple of times, then tried to hit alt to see if menu bar will react, then tried to use command palette to use the same option.

![gif](https://i.imgur.com/EwJLMrZ.gif)

Any guess why this happens?

**Comment by sbatten** [comment]
@kaytrance can you please open your settings file and navigate to `window.menuBarVisibility` and see if the setting is affected by your actions?
