### ISSUE TITLE
RAM consumption

### ISSUE THREAD

**Issue by LeoDupont** [Microsoft/vscode#61127]
Issue Type: <b>Performance Issue</b>

I open VS Code on an Angular project.

If the opened tab is not related to the project (let's say it's the User Preferences tab), the RAM stays around 400 MB, without doing anything, with all extensions disabled.

As soon as I switch to a TypeScript file, the RAM peaks over 1.8 GB...

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:13:53.910Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7560U CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|15.89GB (8.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   128	 10984	code main
    0	   243	  6036	   window (saisie-list.component.ts - ghs-apps - Visual Studio Code)
    0	    58	  2872	     extensionHost
    0	   493	 14224	       electron_node tsserver.js 
    0	    57	 17964	         electron_node typingsInstaller.js typesMap.js 
    0	    38	 15080	       "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=2872
    0	    14	 12152	     watcherService 
    0	    10	 15096	       console-window-host (Windows internal process)
    0	    13	 13008	     electron-crash-reporter
    0	     6	 17136	     winpty-process
    0	    67	   576	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     9	  8424	       console-window-host (Windows internal process)
    0	    70	 19508	   window (Rapporteur du problème)
    0	    64	 19732	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (saisie-list.component.ts - ghs-apps - Visual Studio Code)
|    Folder (ghs-apps): 2199 files
|      File types: xml(449) png(430) class(253) dex(253) json(201) ts(145)
|                  java(115) jar(54) scss(51) js(35)
|      Conf files: package.json(10) tslint.json(3) tsconfig.json(2) gulp.js(1)
|                  launch.json(1) webpack.config.js(1) settings.json(1)
|      Launch Configs: chrome(2);
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-fr|MS-|1.28.2

</details>

**Comment by Tyriar** [comment]
You can see details on your memory usage in your report:

<img width="846" alt="screen shot 2018-10-22 at 8 27 28 pm" src="https://user-images.githubusercontent.com/2193314/47333753-f0b97a00-d638-11e8-9c77-5962b3efcc61.png">

The major culprits are 550mb for TypeScript support, 38 for json support, 67 is powershell.exe, 243 for the window. These are pretty typical numbers. When you hit almost 2gb you could run `code --status` to see what processes are causing the problems as that does seem high.
