### ISSUE TITLE
launch.json autocompletion in configurations.compounds.configurations doesn't update until the file is saved

### ISSUE THREAD

**Issue by nixxquality** [microsoft/vscode#61122]
Issue Type: <b>Bug</b>

Open a launch.json that you have, add a compounds field if you don't have one already.
Look at the autocompletion in configurations.compounds.configurations.
Change the name of one of your configurations without changing the file, then look at the autocompletion. It hasn't changed.
Save the file and you'll note the autocompletion options have changed.

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:07:48.477Z)
OS version: Darwin x64 17.7.0

**Comment by isidorn** [comment]
Agree with that, however this is the current limitation of how we designed the feature. Assigning to backlog.
