### ISSUE TITLE
Antimaware service triggers every time I search in quick open

### ISSUE THREAD

**Issue by sstoychev** [Microsoft/vscode#61130]
- VSCode Version:
Version: 1.29.0-insider (user setup)
Commit: 799bc78af597769a5dd5a6b002359ddae412b1be
Date: 2018-10-17T05:19:06.776Z
Electron: 2.0.11
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
- OS Version:
Windows 10

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes

I had problems with opening the files from the quick open (ctrl+P/F1) which were discussed/fixed in issue #60163 . Few days ago I just cleared my  "Search history", "Search results", ''Editor history" (again ctrl+P/F1), which solved the problem with opening blank files from quick launch. Now every time I try to search file in the quick open Antimaware service kicks in and I have to wait it to finish. When I search the recently opened files are shown immediately.

With the stable version I don't have any problems. I have the same extensions and folders opened there.

**Comment by roblourens** [comment]
This is Windows Defender right, or do you have another antimalware service installed?

I see this sometimes too, from what I understand there's really nothing we can do about it. I don't know why you would see this with insiders but not stable.

I'll leave this open for now, please let me know if you see any changes...

**Comment by sstoychev** [comment]
Yes, this is Windows Defender.
I've been using Insiders for quite some time - an year or so and didn't have any significant problems.

I've noticed the same thing happens (Antimaware kicks in) when I try 'grep -r' from LSW ( the ubuntu shell in WIndows 10), so I guess it is because some process tried to read too many files in too short period. 

This happened after I deleted the history, so I guess I've deleted the index file/db and I guess vscode is trying to create the index again, which means reading all the files in all my opened projects/folders. 

For some reason it can't save the index and is trying to read all the files every time, which causes the triggering of Antimaware.

So first - how can I wipe the current index and recreate it? And verify it is OK?

Another thing which I noticed -  because of #60163 I opened C:\Users\<user>\AppData\Roaming\Code - Insiders\Local Storage\file__0.localstorage and I see a lot of records like:

storage://workspace/c%3A/Users/.....

'c%3A' should be 'c:'?
which I think is also problem in #60163

**Comment by roblourens** [comment]
There is no index, it always reads all files, which is why I don't know why it wouldn't be a problem in stable.

And that URI is correct, special characters like : have to be escaped

**Comment by sstoychev** [comment]
Ok, I copied rg.exe from the stable version and now everything is fine

`
PS C:\Users\abe\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin> .\rg.exe -V
ripgrep 0.9.0
PS C:\Users\abe\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin> .\rg_old.exe -V
ripgrep 0.10.0
PS C:\Users\abe\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin> dir


    Directory: C:\Users\abe\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----    17.10.2018 г.      0:30        3506944 rg.exe
-a----    18.10.2018 г.      5:23        4141320 rg_old.exe
`

rg_old.exe is the file which was in the folder, rg.exe I the one from the stable version. So I guess Windows Defender doesn't like 0.10.0 version

**Comment by sstoychev** [comment]
Yes, it does.

Version: 1.29.0-insider (user setup)
Commit: 9e83209ed59a22df3d593735d04cc963396bb89e
Date: 2018-10-18T05:17:36.900Z
Electron: 2.0.11
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Currently both exes are in the same folder as I showed above, but I believe there is no way that rg_old.exe is used.

**Comment by roblourens** [comment]
Text search might not work though...

Do you have any "search" related settings?

Windows Defender might have scanned enough to decide that it likes that particular binary for some reason?

**Comment by sstoychev** [comment]
Actually it is working with both versions.
The only "search" setting is "search.location": "sidebar", which I believe is irrelevant.

I don't know how Windows Defender works, but I don't think the number of scans affect it. 
Windows Defender for sure hasn't scanned the file in the stable's location enough times, because I use the stable version quite rarely and mainly open it just to manually sync my settings and extensions with the Insiders. I keep the stable "just in case".
Another option would be if Windows Defender scanned the 0.9 version enough times when it was in Insiders and "liked" it, but it would mean I should have felt the slow searches before - something I never had problems with.

P.S. this gave me the idea to manually run a scan while Insiders is running and I'm searching for a file, because I'm sure the Defender would scan the running processes and their files and I hope it would keep the result for the scanned files. And it worked! Now I'm using the 0.10 version and I'm able to search for files as fast as before.

Thank you for your help!

**Comment by roblourens** [comment]
That's very interesting... so you...

- Ran insiders with the normal version of rg
- Started a search (?) text search or file search?
- While it was running, started a manual scan from Defender (just by clicking "scan now" on the Virus scan page?)
- And now Defender doesn't slow down searching?

**Comment by sstoychev** [comment]
Yes
file search
Yes
Yes

**Comment by sstoychev** [comment]
I'm still having this problem and after the update on the stable it happens there too.
At the moment I can't do anything to avoid it - no manual scans or whatever.
I tried to find what triggers the Defender but I can't find anything.

I think the option left is to reinstall. How to completely uninstall, because when I do it the normal way most of the settings/extensions are kept. What folders I have to delete in order to completely remove vscode and do fresh install?

**Comment by roblourens** [comment]
Seems that there is a new issue in 1.29, tracking this in https://github.com/Microsoft/vscode/issues/63070

**Comment by kelvinlow** [comment]
I facing this issue on 1.29.1 too. Is there any solution since this issue was closed?

**Comment by sstoychev** [comment]
My temporary solution is replacing rg.exe with version 0.9 (https://github.com/BurntSushi/ripgrep/releases/tag/0.9.0) every time I do an update.
This way text search is not working, but ….
