### ISSUE TITLE
Save find and replace regex

### ISSUE THREAD

**Issue by anishmittal2020** [Microsoft/vscode#61131]
I use some sets of find and replace more often while editing markdown files. Can I save those pair as a script file or as a shortcut that gets executed whenever I invoke the shortcut or the script file?

**Comment by Tyriar** [comment]
alt+up can navigate the history if you have find focused.

**Comment by honzajde** [comment]
I many times using Search functionality in combination with regexp to do various code transformations. 

For example here is how I replace all markdown links in format [http://example.com]() to a 'tag' format <http://example.com>.

![image](https://user-images.githubusercontent.com/3186360/77419431-723aac00-6dd9-11ea-9f02-c61fa65230fc.png)

Another even more frequent example is transforming JSON file to a typescript mock object. 
Regexp is trivial but it's kind of tedious to fill the fields in the UI it again and again.

Alt+up only iterates over values in one field. And it also contains history of all imperfect tries in that field.

I want to encourage others to vote if you think as me that this would be really huge boost for productivity and opening new possibilities.
