### ISSUE TITLE
Unresponsive in cshtml/mustache/svg (possibly more)

### ISSUE THREAD

**Issue by thany** [Microsoft/vscode#61138]
Issue Type: <b>Bug</b>

1. Open a ASP.Net MVC project
2. Start editing a cshtml file

At some arbitrary point, the editor will stop accepting input. Any character typed will NOT show up. It's still possible to delete/backspace characters, as well as moving the cursor. VS Code is still completely responsive. Editing any other file still works fine.

Sometimes characters typed in, or pasted in, will show up after a delay of some minutes, but most of the type the delay feels so long that I decide the editor is broken and I end up just restarting the application.

Sometimes after a long delay the editor *does* resume accepting input, and any characters typed/pasted in during the freeze are lost in oblivion. This is brilliant when you're one of those people that looks at the keyboard while typing. So apart from an inconvenience, this is also a form a data loss.

During this problem, VS Code also manages to utilize 15-25% of my entire CPU - which is a hyperthreaded hexacore. How much processing power does an editor really need? ¯\\\_(ツ)_/¯

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:13:53.910Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.74GB (18.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
Bookmarks|ale|9.1.0
html-class-suggestions|And|1.0.7
color-info|bie|0.5.0
vscode-eslint|dba|1.6.1
vscode-babel-coloring|dza|0.0.4
EditorConfig|Edi|0.12.5
file-icons|fil|1.0.16
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
duplicate|gee|1.0.1
svgeditor|hen|2.7.0
beautify|Hoo|1.4.6
docthis|joe|0.7.1
vscode-duplicate|mrm|1.2.1
code-settings-sync|Sha|3.2.0

</details>

**Comment by thany** [comment]
It's not a performance issue. The editor is **frozen**, not slow.

**Comment by thany** [comment]
The same thing is now happening in mustache template files!!

Why is this happening???

**Comment by thany** [comment]
Happens in svg as well btw.

**Comment by thany** [comment]
Do you need more information? If so, please specify.

**Comment by thany** [comment]
Happens in a JSON file too. All I have to do is type a `<`.

**Comment by infctr** [comment]
@thany thanks for pinpointing the extension causing this behavior, it was driving me crazy for a while

**Comment by Tyriar** [comment]
Thanks for letting us know (and sorry about the delay, was on leave). We're in the process of improving how we surface extensions that take too much CPU so hopefully this won't need to go through us next time.

**Comment by thany** [comment]
Well there we go: the problem has resurfaced. It's still happening with said extension disabled.

I'm not yet sure what I have to do to make this happen. For now, all I can say it's happening in CSHTML (razor template) files.

**Comment by Tyriar** [comment]
@thany does it happen when you disable _all_ extensions? (relaunch using `code --disable-extensions`)

**Comment by thany** [comment]
I don't know. I tried. But it's just very hard to reproduce, even with extensions enabled.
Last time it happened, I had a few empty lines in between a bunch of code that is indented. On the empty lines, I indented a few steps and then place my caret on the next empty line. The indentation was cleared (as per "Trim Auto Whitespace" being ticked) and the editor stopped responding to keystrokes in the exact same way.

Later, I could no longer reproduce it on demand. It seems to be a matter of luck (or bad luck for that matter) for now.

**Comment by Tyriar** [comment]
These sorts of issues are typically related to extensions, we've actually improved detecting these issues a lot and will point out the problem extension in the latest version that we just released, so hopefully you'll get a notification and VS Code will tell you which extension is the problem when you upgrade to 1.30

https://code.visualstudio.com/updates/v1_30#_unresponsive-extension-host
