### ISSUE TITLE
Bracket auto-complete in markdown

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#6113]
- VSCode Version:1.1.0-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Open a markdown file and add a code block.
2. Type a function, string, etc that has an opening bracket or string

Regardless of the language specified for the code block, bracket completion is not supported.

**Comment by bpasero** [comment]
Verified that this still does not work with the new markdown extension.

**Comment by rebornix** [comment]
Fixed via https://github.com/kieferrm/vscode-markdown/commit/81f52f5ebfa0ebf84529c4538985c17bc58f735d

**Comment by bpasero** [comment]
@rebornix cool! would it not make more sense to push your changes directly to master given that we pushed vscode-markdown into VSCode?

**Comment by rebornix** [comment]
I'll send out my PR real quick (I'd like to have the push privilege after my onboard).
