### ISSUE TITLE
Missing ampersands in new "custom" title bar

### ISSUE THREAD

**Issue by joshuacc** [Microsoft/vscode#61139]
- VSCode Version: 1.28.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create a folder containing an ampersand. i.e. "Notes & Todos"
2. Open this folder in VS Code
3. Go to File > Open Recent, and you will see that the folder is listed, but missing the ampersand.

Does this issue occur when all extensions are disabled?: Yes

This only occurs when the new title bar setting is set to "custom." When set to "native" the ampersand appears as expected.

**Comment by joshuacc** [comment]
This is a separate issue than the one linked by @vscodebot above.

**Comment by joeyfoo** [comment]
I'm able to replicate this. 

I'm planning to try to fix this and to submit a fix as a PR, but this will be my first contribution to a project of this size.
