### ISSUE TITLE
Notifications balloon cut-off at top when no new notifications

### ISSUE THREAD

**Issue by tmknight** [Microsoft/vscode#61135]
Issue Type: <b>Bug</b>

When there are no new notifications, the notifications balloon is cut-off at the top.

VS Code version: Code - Insiders 1.29.0-insider (799bc78af597769a5dd5a6b002359ddae412b1be, 2018-10-17T05:19:06.776Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (22.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.60
compulim-vscode-closetag|Com|1.2.0
vbscript|Dar|1.0.4
xml|Dot|2.3.2
php-debug|fel|1.12.6
php-intellisense|fel|2.3.5
auto-close-tag|for|0.5.6
code-runner|for|0.9.4
phpcs|ika|1.0.5
vscode-apache|mrm|1.1.1
mssql|ms-|1.4.0
python|ms-|2018.9.0
cpptools|ms-|0.19.0
csharp|ms-|1.16.2
PowerShell|ms-|1.9.0
team|ms-|1.142.0
htmlescape-vscode-extension|ray|0.0.4
vscode-yaml|red|0.0.17
code-settings-sync|Sha|3.2.0
vscode-preview-server|yui|1.1.1

(1 theme extensions excluded)

</details>

![2018-10-17 08_01_50-window](https://user-images.githubusercontent.com/548588/47084971-2b5b8680-d1e3-11e8-8b10-508cd3ebe419.png)

**Comment by bpasero** [comment]
@tmknight is that on a normal sized window?

**Comment by bpasero** [comment]
I cannot reproduce:

![image](https://user-images.githubusercontent.com/900690/47353497-babdd980-d6bc-11e8-82d6-b313411343a0.png)

@tmknight does this reproduce all the time?

**Comment by tmknight** [comment]
It appears to have been resolved in a subsequent insiders update.

Currently on:
Version: 1.29.0-insider (system setup)
Commit: d1f5894892e3719846bbd4bd0dd75f117f211ab5
Date: 2018-10-23T05:20:39.912Z
Electron: 2.0.11
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Closing as resolved
