### ISSUE TITLE
onDidChangeWorkspaceFolders dont emit when i change dir or file

### ISSUE THREAD

**Issue by chnliquan** [Microsoft/vscode#61137]
- VSCode Version: 1.28.0
- OS Version: macos 10.3.3

Steps to Reproduce:

1. I am binding an onDidChangeWorkspaceFolders event to vscode in extention.js
2. when i create a dir or a file in extention mode, the callback not emit

```js
vscode.workspace.onDidChangeWorkspaceFolders(() => {
    console.log(1231231) // not console
    pageProvider.refresh()
})
```

**Comment by bpasero** [comment]
This event is triggered when changing folders in a multi root workspace, so it will not fire when you open a single folder or create folders. There is other API to listen to file changes: `createFileSystemWatcher`
