### ISSUE TITLE
Show Function List(Symbols List) in tree explorer viewlet

### ISSUE THREAD

**Issue by xiagw** [Microsoft/vscode#61143]
Many modern editors have an import feature: function list. It is very useful to view the outline of the c/c++ file.
Although vscode can view the symbols list via Ctrl-Shift-O, but many programmers prefer function list, I think.

So, I expect vscode can implement function list via the extension.

Thanks.

**Comment by usernamehw** [comment]
Like this? https://code.visualstudio.com/updates/v1_25#_outline-view

**Comment by Tyriar** [comment]
We already have this functionality, use https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools for C++ support (and report at https://github.com/Microsoft/vscode-cpptools if you have problems)
