### ISSUE TITLE
macOS custom file icons reset not auto triggered.

### ISSUE THREAD

**Issue by orhaneee** [Microsoft/vscode#61142]
- VSCode Version: 1.28.1
- OS Version: macOS Mojave 10.14.1 Beta (18B45d)

### Description:
New update brings custom font icons in OS explorers in Windows and macOS. But, after updating and restarting, the icons DID not replace with the new ones.
So, I cleared icon cache with
```sh
sudo rm -rfv /Library/Caches/com.apple.iconservices.store; sudo find /private/var/folders/ \( -name com.apple.dock.iconcache -or -name com.apple.iconservices \) -exec rm -rfv {} \; ; sleep 3;sudo touch /Applications/* ; killall Dock; killall Finder
```  

### Does this issue occur when all extensions are disabled?
Yes

**Comment by bpasero** [comment]
Great, I did the same once, seems to work fine.
