### ISSUE TITLE
Run Build Task not running on Linux

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#6114]
- VSCode Version: 1.1.0-alpha
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Run Build Task (Ctrl+Shift+B or run from F1 menu)

The tasks window opens but the errors are not showing up.

**Comment by dbaeumer** [comment]
@vsccarl can you please provide the workspace showing this behavior. An easy explanation is that there might not be any problem matchers configured.

**Comment by vsccarl** [comment]
I was working with the [smoke test repo](https://github.com/Microsoft/vscode-smoketest-express) but I'm not able to repro on the latest build. I'll reopen if any other builds repro.
