### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by 0888946595** [Microsoft/vscode#61144]
Issue Type: <b>Bug</b>

i can't set name file HTML is "index.html". I just set "index.htm"

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:13:53.910Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.88GB (0.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-django|bat|0.17.0
flask-snippets|cst|0.1.0
jupyter|don|1.1.4
python-extension-pack|don|1.4.0
tslint|eg2|1.0.40
MagicPython|mag|1.1.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2018.9.0
team|ms-|1.142.0
vscode-yaml|red|0.0.17
vscode-icons|rob|7.27.0
vscodeintellicode|Vis|1.0.5
jinja|who|0.0.8

(1 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
@0888946595 Please provide more details what the problem is (more steps, screenshots) and what should be improved in VSCode.
