### ISSUE TITLE
Ability to perfect size views by double clicking on sash

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#61148]
The same way it works for vertical sashes (sidebar, panel) and grid editors. 
It would be nice for it to behave the same for horizontal views such as `outline`:

| Before  | After |
| ------------- | ------------- |
| ![before](https://user-images.githubusercontent.com/9638156/47095141-4fe04e80-d235-11e8-9d06-ae3e6d39e66a.png)  | ![after](https://user-images.githubusercontent.com/9638156/47095170-625a8800-d235-11e8-8878-5ce9995ebaf7.png) |

Maybe a duplicate of #50853, I'm not sure.

**Comment by joaomoreno** [comment]
This is implemented in the splitview, but needs adoption from splitview users. So if you want you can file specific issues to the specific areas in which this should work.
