### ISSUE TITLE
Menu stays open in this case

### ISSUE THREAD

**Issue by krousseeuw** [Microsoft/vscode#61145]
Issue Type: <b>Bug</b>

I discovered a small bug in Visual Studio Code. When you follow the steps described below the right click menu will remain open and cannot be closed anymore. I could only get it fixed by restarting VS-code.

Steps to reproduce:
1. Split your editor (in my case I split to the right)
2. Right click on the top bar to open a menu
3. In the explorer in Open Editors you close all editors tied to the one you right-clicked

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:15:15.139Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2694)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|7.90GB (0.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.10
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.60
gitlens|eam|8.5.6
vscode-html-css|ecm|0.2.0
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.40
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.6.1
angular-essentials|joh|0.4.0
Angular2|joh|6.3.0
csharp|ms-|1.16.2
debugger-for-chrome|msj|4.10.2
angular2-inline|nat|0.0.17
material-icon-theme|PKi|3.6.0

(1 theme extensions excluded)

</details>

**Comment by ganeshkbhat** [comment]
The custom menu bar does not allow a right click on the editor or the terminal window. The context menu closes if you try to open.

**Comment by ganeshkbhat** [comment]
@sbatten I cannot give you a print screen. The max I can do is record a screen video and submit the issue. When you right click on the editor or terminal for context menu using the custom menu setting, the menu opens and closes immediately. I am on Ubuntu 18.04.1 LTS

**Comment by sbatten** [comment]
@ganeshkbhat This is a separate issue that has seen a few fixes over time even very recently. Please try the latest insiders to confirm the issue persists and create a separate issue if so.

**Comment by ganeshkbhat** [comment]
@sbatten Ok. I did not know that. How do I get to the latest insiders section? Have to agree I am clueless here.

**Comment by sbatten** [comment]
@ganeshkbhat https://code.visualstudio.com/insiders/

**Comment by ganeshkbhat** [comment]
@sbatten Issue of right click context menu still closes with the custom menu setting; even in the insider version. Can you point me to this issue # ?

**Comment by sbatten** [comment]
@ganeshkbhat #61154

**Comment by ganeshkbhat** [comment]
@sbatten Thanks for your time.

**Comment by sbatten** [comment]
@krousseeuw I can no longer reproduce this issue, can you verify?

**Comment by bpasero** [comment]
@sbatten the menu remains open for me even when editors close, though I can still close it afterwards:

![before](https://user-images.githubusercontent.com/900690/52109760-dd865500-25fe-11e9-8c6e-58e20db55371.gif)

**Comment by bpasero** [comment]
Actually now that I think about it, the menu should close when I click on the action in the "Open Editors" view, reopening, but not critical imho.

**Comment by sbatten** [comment]
This will likely just be fixed by https://github.com/Microsoft/vscode/pull/64099 when I get that in.
