### ISSUE TITLE
Conexão em banco de dados por odbc

### ISSUE THREAD

**Issue by johnnyvaz1** [Microsoft/vscode#61147]
Trabalho muito com banco de dados Firebird, e gostaria que tivesse como executar um script sql direto pelo vs code, no caso, sugiro que a conexão seja por ODBC, porque daí poderia ser usado em outras formas de acesso.
não achei em nenhuma extensão o acesso a ODBC.

obrigado

**Comment by Tyriar** [comment]
This seems like something that an extension would drive
