### ISSUE TITLE
JSON snippets are not offered until new line entered

### ISSUE THREAD

**Issue by joechung-msft** [Microsoft/vscode#61146]
- VSCode Version: 1.28.1
- OS Version: Windows

Steps to Reproduce:

1. Create a JSON snippet.
2. Try to use the JSON snippet on a JSON object literal without entering a new line.

![image](https://user-images.githubusercontent.com/26208574/46840473-0b0d7100-cd78-11e8-93fd-f0eef9897b5e.png)

Note that if you press Enter to split the JSON object into multiple lines, VSCode will present the snippet as an option:

![image](https://user-images.githubusercontent.com/26208574/46840485-18c2f680-cd78-11e8-9494-7587a518d371.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by joechung-msft** [comment]
@jrieken, you misunderstood:  the JSON file I was editing was called `Untitled-1.json`, not that it actually matters.  I also reproduced the issue in a file called `ison.json` and `javascript.json`.

The snippet filename was called `json.json`.

Also, note that the snippet works if you enter a new line so I don't think the name of the snippet file is what is causing the issue.

**Comment by josephwallertheceo** [comment]
All I know I better get paid or all you are fired 
I just don't understand is if one of you hadn't been I would have some lawyer up my zoo but don't pay the boss for 25 years 28 years no problem you all getting your last paycheck if mine is not put into my bank soon

**Comment by josephwallertheceo** [comment]
One million a month x 12 x 25 = 300 million today

**Comment by josephwallertheceo** [comment]
Well guess I can pay my bills now
![15397888463411537643582](https://user-images.githubusercontent.com/43848445/47096450-129fa080-d1e4-11e8-8b6c-380dd32f32ed.jpg)

**Comment by josephwallertheceo** [comment]
So when will get the wire
And the sir plus on the futures of mine that you all sold

**Comment by josephwallertheceo** [comment]
I am the master and I'm bound by no one and that include all of you if I'm not paid today you all will not need to return to work ever again

**Comment by jrieken** [comment]
> Also, note that the snippet works if you enter a new line so I don't think the name of the snippet file is what is causing the issue.

No, what you are seeing the default json suggestion and *not* the snippet suggestion. The file *must* end in JSON and it *must* be in the right folder.

**Comment by jrieken** [comment]
> Create a JSON snippet.

What does this mean? Please update your steps. To create a new snippet go via "F1 > Configure Snippets"

**Comment by jrieken** [comment]
closing as dupe, lets continue the discussion in #60704
