### ISSUE TITLE
Buttons/Menus blinking

### ISSUE THREAD

**Issue by beckerzito** [Microsoft/vscode#61157]
- VSCode Version: 1.28.1
- OS Version: Windows 7 Professional x64

Steps to Reproduce:

1. Install VSCode.
2. On Settings page, move mouse across the entire application.

PS: It happens with any color theme and both titleBar configuration (custom or native). 
When in custom titleBar, the minimize/maximize/close buttons are buggy and change their colors while mouse cursor moves over the app. 

PS2: I already uninstalled everything, deleted all folders from Visual Studio Code and installed a new instance.

You can find gifs showing the issue. 
Menu Item on Settings page:
![menu](https://user-images.githubusercontent.com/26304432/47105224-b6577380-d219-11e8-9962-53ea67431b8e.gif)

With custom titleBar, minimize/maximize/close buttons:
![buttons](https://user-images.githubusercontent.com/26304432/47105549-abe9a980-d21a-11e8-84b1-5ec928c6a37a.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Weird glitch. Seen this before @sbatten?

**Comment by beckerzito** [comment]
Any update on this?

**Comment by roblourens** [comment]
I have no idea - could you try downloading our Insiders build to see whether it happens there too? But this is probably just a chromium glitch that we'll need an electron update for...

https://code.visualstudio.com/insiders

**Comment by beckerzito** [comment]
@roblourens With some deepier search, I've found an issue about glitching on VS Code. In that situation the guy used the --disable-gpu command. For my luck it solved my problem too. 

I already know there's lots of issues about this and it has some complexities, however I'd like to reinforce that disabling the gpu over settings configuration would be a nice feature, once when I use the windows shortcuts and context menu I cannot put the command --disable-gpu and then the glitch happens again.

Thanks and best regards.

**Comment by roblourens** [comment]
Could you try in this build using Electron 3? https://az764295.vo.msecnd.net/exploration/a19e0f85ac7167f27716b3cbbb07a6164f47684e/VSCode-win32-x64-1.29.0-exploration.zip
