### ISSUE TITLE
The files.insertFinalNewline setting doesn't work in the 1.1.0-insiders build

### ISSUE THREAD

**Issue by gwynjudd** [Microsoft/vscode#6115]
- VSCode Version: 1.1.0-insiders
- OS Version: Windows 8

Steps to Reproduce:

1. Add the user setting: "files.insertFinalNewline": true,
2. Edit a file and save

I expect that a newline is added at the end of the file. It is in the 1.0 release, but it is not in the 1.1.0-insiders build.

**Comment by bpasero** [comment]
@gwynjudd this setting is coming from an extension? which one?

**Comment by gwynjudd** [comment]
@bpasero sorry please close this, I'd forgotten to install the final-newline extension in the insiders build
