### ISSUE TITLE
Some tooltips are too small to read on high-DPI displays

### ISSUE THREAD

**Issue by kennykerr** [microsoft/vscode#61153]
Issue Type: <b>Bug</b>

Hover mouse over file tab and try to read the full path in the tooltip. 

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:13:53.910Z)
OS version: Windows_NT x64 10.0.18261

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 3492)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (10.18GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-pull-request-github|Git|0.2.1
cpptools|ms-|0.19.0

</details>

![image](https://user-images.githubusercontent.com/9845234/47102343-5351e680-d1f1-11e8-99f1-97020fac66a7.png)

**Comment by Tyriar** [comment]
Could you try using this exploration build that uses Electron 3 to see if this is fixed? https://az764295.vo.msecnd.net/exploration/d2bb6005911d54dae39d56d26b1d1f80e758d96e/VSCode-win32-x64-1.29.0-exploration.zip

**Comment by kennykerr** [comment]
I gave it a try, but the results are the same.

**Comment by PaluMacil** [comment]
On the Surface Book I still have these very tiny tooltips too. About says I'm on Electron 3.1.3 and VS Code 1.32.1. While I appreciate the duplicate bot, it is certainly painful to have to lean way in to see tooltips.

**Comment by danwhitston** [comment]
And here's a screenshot from a Dell XPS13 9370 running VSCode 1.33.1 on Win 10, set to 200% UI scale in desktop display settings. Same issue. Gives me actual headaches trying to read the path. The software I'm working on has hundreds of files with the same name so I'm checking it all the time.
![image](https://user-images.githubusercontent.com/8845838/57388091-6d640e00-71af-11e9-94c8-0581839dbf9a.png)

**Comment by nitrousdigital** [comment]
Same:
![image](https://user-images.githubusercontent.com/506984/59770575-4dc40900-9276-11e9-9f18-18dfeaefce1c.png)


HP ZBook
VS Code 1.35.1
Electron 3.1.8
