### ISSUE TITLE
Enter if (condition) {} press Enter to edit the condition without keyword prompt

### ISSUE THREAD

**Issue by Despoinis** [Microsoft/vscode#61159]
Enter if (condition) {} press Enter to edit the condition without keyword prompt

JavaScript
version 1.28.1 (system setup)

**Comment by isidorn** [comment]
Sounds like snippets..

**Comment by Despoinis** [comment]
> 
> 
> @Despoinis Please add actionable information

Gif screenshot:
https://ipfs.infura.io/ipfs/QmacLWZwWWSzgQ62Su4m1dVhphVgdSjg86FhJ4PGWGzWoc

**Comment by jrieken** [comment]
Use this setting `"editor.suggest.snippetsPreventQuickSuggestions": false`
