### ISSUE TITLE
Right click menu in explorer disappears after click

### ISSUE THREAD

**Issue by Yanpas** [Microsoft/vscode#61154]
Issue Type: <b>Bug</b>

I'm using custom titleBarStyle on linux. Here is what's going on:
![peek 2018-10-17 20-13](https://user-images.githubusercontent.com/7345761/47104182-832cd880-d249-11e8-9962-abbb538c8feb.gif)

If I click on a file located in the middle of explorer then right click menu disappears immeditely. Holding right mouse button and moving it to the left allows to open menu

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:09:20.566Z)
OS version: Linux x64 4.15.0-36-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3731)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.35GB (12.72GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.2
blamer-vs|bea|0.4.0
path-intellisense|chr|1.4.2
vscode-dash|dee|2.0.0
githistory|don|0.4.3
xml|Dot|2.3.2
gitlens|eam|8.5.6
file-icons|fil|1.0.16
code-runner|for|0.9.4
perl-outline|hit|0.0.4
svn-scm|joh|1.44.1
language-haskell|jus|2.5.0
favorites|kdc|2.0.0
sftp|lix|1.6.3
bash-ide-vscode|mad|1.3.3
vscode-todo-parser|min|1.9.1
vscode-language-pack-ru|MS-|1.28.2
python|ms-|2018.9.0
cpptools|ms-|0.19.0
gradle-language|nac|0.2.3
vscode-subword-navigation|ow|1.2.0
java|red|0.32.0
vscode-yaml|red|0.0.17
vscode-sort-json|ric|1.13.0
vscode-lua|tri|0.12.4
cmake|twx|0.0.17
cmake-tools|vec|1.1.2
vscode-java-debug|vsc|0.14.0
vscode-maven|vsc|0.11.1
debug|web|0.22.0
clang-format|xav|1.6.2
vscode-proto3|zxh|0.2.1

(2 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
@joaomoreno didn't this get fixed before 1.28? :(

**Comment by joaomoreno** [comment]
Funny. It repros in the Explorer, but it doesn't repro in the Open Editors view nor in the editor itself. 🤔

**Comment by TheAifam5** [comment]
After setting `titleBarStyle` to `native` issue is gone. Please just move the context menu 2px to right :@

**Comment by ganeshkbhat** [comment]
I am also facing the same issue of the custom right click context menu closing immediately. Whenever you right click on the editor or the terminal it immediately closes. I was on Ubuntu 18.04 V and Node 10.x. I upgraded Ubuntu 18.04.1v with latest updates and installed node 11.x. Now the issue is not happening in normal scenarios. `Now the right click context menu closes immediately only in the last line of the text of the editor when a file is open`. It, possibly, could not be Node upgrade that made the issue at major places go away but could be my OS upgrade.

**Comment by joaomoreno** [comment]
@ganeshkbhat What is your VS Code version?
