### ISSUE TITLE
wrong order of next/prev buttons at touchbar

### ISSUE THREAD

**Issue by Eugene-Musika** [Microsoft/vscode#61150]
- VSCode Version: 1.28.1
- OS Version: macOS Mojave 10.14

Steps to Reproduce:

1. Open VS Code
2. Configure display language in locale.json to "ru"
3. Install Russian language pack
4. Few times open/close VS Code via CMD+Q

Related to #35906

**Comment by Tyriar** [comment]
Reopened original
