### ISSUE TITLE
Globbing files and variable substitution in tasks.json

### ISSUE THREAD

**Issue by pablox-cl** [microsoft/vscode#61158]
I have a simple task for running a `rake task`:
```json
            {
                "label": "rake test",
                "type": "shell",
                "options": {
                    "env": {
                        "TEST": "${relativeFile}"
                    }
                },
                "command": "rake",
                "args": [
                    "test"
                ],
                "group": {
                    "kind": "test",
                    "isDefault": true
                },
            }
```

The problem is that the task (since `${relativeFile}`) can run on every file and I would like it to run only on `test/*_test.rb` files. I have read the documentation, checked the schema files, and it doesn't seem possible to run some globbing or pattern matching.

**Comment by dbaeumer** [comment]
Just to clarify. You want the task to be a noop if relative file doesn't matche `test/*_test.rb`

**Comment by pablox-cl** [comment]
I don't understand exactly what do you mean by noop (sorry :frowning_face:), but I meant that the taks as it is, could be run on every file (even on `tasks.json`). I rather simply expect that the test don't run.

**Comment by dbaeumer** [comment]
Tasks never run by themselves, they need to be triggered by the user. If I understand you correctly if the task above is trigger by a user on a file not matching `test/*_test.rb` the task should actually do nothing (noop === no operation).

**Comment by pablox-cl** [comment]
Yes, that's it.
