### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by 24Beast** [Microsoft/vscode#61152]
Issue Type: <b>Feature Request</b>

I am having trouble executing my code because, there is some problem with the include files.I am getting the following error-

#include errors detected.Please update your include file.

How am I supposed to update these files. 
I am a beginner in coding so I have literally no idea.
Kindly Help!

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:13:53.910Z)
OS version: Windows_NT x64 10.0.16299

**Comment by michaelscof** [comment]
Hi! This maybe because you have not updated the compiler path. Have a look into it!
This might  help https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/MinGW.md
