### ISSUE TITLE
Trying to save file

### ISSUE THREAD

**Issue by gvanderest** [Microsoft/vscode#61160]
Issue Type: <b>Bug</b>

* Create untitled file
* Added a json blob to it to try to set up tsconfig.json structure
* Open save dialog window, which has `webpack.config.json` pre-selected
* Change selection to parent folder of `webpack.config.json` which is called `src`
* Type `tsconfig.json` into save box
* Click save

Shown error that webpack.config.js is a file and not a directory.. but I'm tryring to save to the folder above it.  Somehow it's not selecting the folder or changing the path away from the webpack.config.js file.

VS Code version: Code - Insiders 1.29.0-insider (799bc78af597769a5dd5a6b002359ddae412b1be, 2018-10-17T05:12:39.408Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
ion-format-support|Avi|1.0.2
vscode-eslint|dba|1.6.1
java-debug|DSn|0.0.2
gc-excelviewer|Gra|2.1.26
todo-tree|Gru|0.0.92
rainbow-csv|mec|0.7.1
mssql|ms-|1.4.0
python|ms-|2018.9.0
sublime-keybindings|ms-|4.0.0
gradle-language|nac|0.2.3
indent-rainbow|ode|7.2.4
java|red|0.32.0
missinglineendoffile|ric|0.3.1
vscode-java-debug|vsc|0.14.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.10.0
vscode-maven|vsc|0.11.1
vim|vsc|0.16.10
vscode-todo-highlight|way|1.0.4
plsql-language|xyz|1.5.0

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
@gvanderest this sounds more like an OS issue to me. Can you do a screen cast how this behaves? I also do not understand how `webpack.config.json` is already preselected for you.

**Comment by gvanderest** [comment]
I'll try to get more info if this happens again.  It also might have been caused by another bug (as I reported two additional ones), forcing the saving to lock to a specific path.  I'll close for now until I can reliably reproduce with video/steps.

It hasn't happened again in a while.
