### ISSUE TITLE
vscode cant open when pc not connected to wifi

### ISSUE THREAD

**Issue by fecundlabs** [Microsoft/vscode#61165]
We have written the needed data into your clipboard because it was too large to send. Please paste.

1 disconect your computer from wifi and disable functionality that allows it to automtically connect
2 shut down your pc
3 turn it onand make sure its not connected to wifi
4 try and open vs code, it does not even load. this has been happening since the week began and is very frustrating as i donot always have internet

**Comment by nancym** [comment]
This is a huge problem for me too. The bot will probably soon close this issue and point you to Issue #7570 where you can read that the "exploration build" fixes this: https://github.com/Microsoft/vscode/issues/7570#issuecomment-423196532

Please someone post how to get the latest exploration build. There are links in #7570 to random exploration builds, but what if I want the latest? Also please post a link to info that tells more about the exploration build, e.g., is it something that someone who is wary of alpha and beta software should use?

Thank you from ℵ who is wary of alpha and beta releases

**Comment by rcwei44** [comment]
I also encountering this problem, and it seen there are many people is encountering this question, I hope they can notice this bug soon

**Comment by Berrysoft** [comment]
If you run `code` in command line with no Internet, you will get the following message:
```
dns.js:246
    this._handle = new ChannelWrap();
                   ^

Error: EFILE
    at new Resolver (dns.js:246:20)
    at dns.js:377:25
    at dns.js:431:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at net.js:45:13
    at net.js:1730:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at internal/child_process.js:6:13
```
I hope this will help.

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/7570
