### ISSUE TITLE
Live server not installing

### ISSUE THREAD

**Issue by prajjvalt** [Microsoft/vscode#61167]
We have written the needed data into your clipboard because it was too large to send. Plea
Issue Type: <b>Performance Issue</b>

from last 3 days i am trying to install live server extension but its not installing,it just stucks on installing window and never actually installs,i also tried installing other extension like python but its also not installing

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3217U CPU @ 1.80GHz (4 x 1796)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.89GB (1.40GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe --open-url -- vscode:extension/ritwickdey.LiveServer|
|Screen Reader|no|
|VM|67%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	    78	  1732	code main
    3	   474	  4812	   window (undefined)
    2	    63	  5924	   window (Issue Reporter)
    0	   159	  8632	   window (Extension: Live Server - Visual Studio Code)
    0	    51	  4964	     extensionHost
    0	     9	  6404	     electron-crash-reporter
    4	    41	  9788	   gpu-process
    0	    80	 10148	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
Extensions: none
se paste.

**Comment by sandy081** [comment]
@prajjvalt Can you please update to latest stable version and see if you still have the issue?

Also do following steps before trying it

- Enable log level to trace using `Set Log Level` Command
- Open Shared Process logs using `Open Logs` command

Try to reproduce now and let us know what you see in logs.
