### ISSUE TITLE
OSX <fstream> cannot be found in default CPP Include Path /usr/include

### ISSUE THREAD

**Issue by SamuelHenderson** [Microsoft/vscode#6116]
- VSCode Version: 1.0.0
- OS Version: OSX 10.11.4

Steps to Reproduce:

1. Setup a C++ project in VS Code
2. `include <fstream>` in source

I see a green wavy line under `include <fstream>` with a lightbulb. When I click the lightbulb the c_cpp_properties.json file is opened.  I see that /usr/include is listed as the include path.  I can see that <fstream> is in this path (actually it's in /usr/include/c++/4.2.1/ ... but other C++ headers in the same folder seem to work ok... like <sstream> and <map>)

What am I doing wrong?

**Comment by bpasero** [comment]
We are very sorry to hear you are having issues with VS Code. Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. Most extensions are on GitHub as well so it should be easy to file it against the extension.

Thanks for your feedback!
