### ISSUE TITLE
Pasting text from clipboard freezes vscode

### ISSUE THREAD

**Issue by janfokke** [microsoft/vscode#61161]
Main log
[2018-10-17 20:09:09.731] [main] [error] [VS Code]: detected unresponsive

OS: Manjaro
Clipboard from: LevelEditor.bin.x86_64 (Linux HPL Editor Suite for Amnesia 1.3 and later.)
https://wiki.frictionalgames.com/hpl2/tools/start

Other text editors have a slight delay, but vscode freezes immediately

**Comment by rebornix** [comment]
@janfokke what does the content in the clipboard look like? Without more information I don't have a way to reproduce this issue. Thanks!

**Comment by janfokke** [comment]
It is plain text copied from a textbox

**Comment by rebornix** [comment]
Could you for example provide the content? Does it happen every time?

**Comment by janfokke** [comment]
the LevelEditor.bin.x86_64 seems to use SDL2 for setting the clipboard

you can reproduce the occurrence by running the following code

```
#include <stdio.h>
#include <SDL2/SDL.h>

int main(int argc,char **argv) {
    if(SDL_Init(SDL_INIT_VIDEO)){
        printf("%s",SDL_GetError());
    }

    if(SDL_SetClipboardText("Test")){
        printf("%s",SDL_GetError());
    }
    printf("%s", "clipboard set");

    getchar();
}
```

**Comment by rebornix** [comment]
This is an known issue when the clipboard is large and pasting from it might crash the window.
