### ISSUE TITLE
Debug Console for Node 10 and Sailsjs outputs different than Node version < 8

### ISSUE THREAD

**Issue by L1qu1d1c3** [Microsoft/vscode#61174]
VSC version: 1.28.0
Platform: Windows 10
NodeJS version: 10.8.0
SailsJS version: 0.12

Hello,

When I installed NodeJS 10, all of the sudden I noticed that the output in the Debug Console wasn't the same as before. When I was in an older version, the output used to be like this:
![image](https://user-images.githubusercontent.com/7668505/47086374-92942d80-d219-11e8-8aea-42c97a8217a4.png)

After putting it on 10, the output all of the sudden came out to this:
![image](https://user-images.githubusercontent.com/7668505/47086200-25809800-d219-11e8-8e9c-f5cc24d8fbf5.png)

I think the main issue is that VSC only outputs things that are on "debug" level of logging, and not other levels - something I don't want, i'd like it to output everything.

Steps to Reproduce:

1. Install NodeJS >=10
2. Install SailsJS
3. Create an example app
4. Debug the app with basic node debug config (node app.js)

**Comment by roblourens** [comment]
Could you set `"trace": true`, run the app in node 10, and upload the log here?

**Comment by L1qu1d1c3** [comment]
I've attached it - its 21mb...
[debugadapter.txt](https://github.com/Microsoft/vscode/files/2494901/debugadapter.txt)

**Comment by roblourens** [comment]
Is it possible that you need to set something to enable the verbose logging? vscode isn't doing any filtering. The only log messages it got from node are the ones it displays.

**Comment by L1qu1d1c3** [comment]
Hello,

I've attached a GIF where you can see how it behaves with different nodejs versions. I have NVM to switch node versions. In the first go, I switched to version 4.2.0 - you can see that it outputs stuff perfectly, even the native visual studio verbose that I enabled earlier.

After that, I switched back to 10 and you can see how it doesn't output any more logs - even the Visual Studio "trace".

![vsdebug](https://user-images.githubusercontent.com/7668505/47282873-1c107a80-d5e1-11e8-8f27-f11292bfb2cf.gif)

Regards,

**Comment by L1qu1d1c3** [comment]
Hello,

I've attached a Gif where you can see the behaviour between different nodejs versions (4.7.0 & 10.8.0. You can see how even the logging of vsc's "trace" disappears when using node 10.

![vsdebug](https://user-images.githubusercontent.com/7668505/47284183-b7581e80-d5e6-11e8-8688-e040b4785077.gif)

Regards,

**Comment by L1qu1d1c3** [comment]
> Is it possible that you need to set something to enable the verbose logging? vscode isn't doing any filtering. The only log messages it got from node are the ones it displays.

Hello,

I've attached a gif where you can see Visual Studio Code's different output when using different versions of nodejs (4.7.0 & 10.8.0). Even the "trace" log comes out different.

![vsdebug](https://user-images.githubusercontent.com/7668505/47284280-15850180-d5e7-11e8-8ed0-42561c206e8f.gif)

Regards,

**Comment by roblourens** [comment]
Oh, I see. Most likely the other logs are being read from the node process's stdout, but they aren't going through the debug connection. There are a few reasons why that can happen, some logging libraries write directly to stdout.

Try adding `"outputCapture": "std"` to your launch config, that should make it work the same in node 10.

**Comment by L1qu1d1c3** [comment]
> Oh, I see. Most likely the other logs are being read from the node process's stdout, but they aren't going through the debug connection. There are a few reasons why that can happen, some logging libraries write directly to stdout.
> 
> Try adding `"outputCapture": "std"` to your launch config, that should make it work the same in node 10.

That worked!! Thanks so much.

**Comment by L1qu1d1c3** [comment]
@roblourens  has this changed in recent releases? outputCapture is no longer working :/

**Comment by roblourens** [comment]
Nothing has changed that I know of on our end.

**Comment by L1qu1d1c3** [comment]
My apologies, as of sails 1.0, the output logging has been reduced to a minimum unless configured otherwise.
