### ISSUE TITLE
Integrated Terminal does not display prompt when started

### ISSUE THREAD

**Issue by DSakura1987** [Microsoft/vscode#61172]
- VSCode Version: 1.28.1, 1.29.0-insider
- OS Version: Windows 10 Enterprise Version 1809

Steps to Reproduce:

1. Open Visual Studio Code
2. Click the status icon on bottom left, and switch to TERMINAL tab.

Does this issue occur when all extensions are disabled?: Yes

Expected result: 
Terminal (PowerShell) is started and I can see the prompt and cursor.

Result: 
Terminal started, however ...
1. Scrolled down to bottom
2. When scrolled up to top, the prompt and cursor are not shown.

Actually it is ready for input, but it is confusing because I have got no cursor or prompt.

Image:
![image](https://user-images.githubusercontent.com/4421906/47115954-74c8c780-d21d-11e8-859d-32bab21f0408.png)
![image](https://user-images.githubusercontent.com/4421906/47116108-e3a62080-d21d-11e8-86ec-8934bda5b0ef.png)

**Comment by ghiscoding** [comment]
most probably related to #57803 which is because of Win10 build 1809, a fix is in the upstream but might take few weeks for us to get.

**Comment by DSakura1987** [comment]
Thanks @ghiscoding . Glad to know the fix is on its way. Now I simply hope November comes sooner 😄 
Feel free to close the issue.
