### ISSUE TITLE
Intellisense autocomplete: user snippets sometimes don't show up

### ISSUE THREAD

**Issue by dancherb** [Microsoft/vscode#61176]
- VSCode Version: 1.28.1
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Use tab for accepting suggestions: "editor.acceptSuggestionOnEnter": "off",
2. Set up some javascript snippets.
3. Start typing them in different contexts. Here, I've created one "bw". It shows up in some contexts:
![](https://i.imgur.com/fRX4Fol.png)

And not in others - this is a line above, in the style object of a component in exactly the same way:
![](https://i.imgur.com/ir10Z3m.png)

Does this issue occur when all extensions are disabled? Yes - this is with all installed extensions disabled.

**Comment by mjbvz** [comment]
Can you please share the code in your screenshot as text? I want to see the context of two locations may be different and cannot tell this from the screenshots

**Comment by dancherb** [comment]
Sure, here's a simplified version @mjbvz 

Here, the outer div has a bunch of suggestions (none of which are the snippet), while the inner one starts with the snippet. It seems to be the fact that the style object in the outer div spreads onto two lines that is causing this, though I've had similar issues in other contexts.

```
class Screen extends Component {
    render() {
        return(
            <div center style={{width: "100%", height: theme.headerHeight, justifyContent: "space-between", alignItems: "flex-start"}}>
                <div style={{alignItems: "flex-start", marginLeft: theme.margin}}/>
            </div>
        )
    }
}
```

**Comment by jrieken** [comment]
@dancherb this is fixed in insiders: https://code.visualstudio.com/insiders/
