### ISSUE TITLE
Allow extension to use onCreate activation event

### ISSUE THREAD

**Issue by launay12u** [Microsoft/vscode#61173]
Hello,

Im looking to create extension who proposes to make a `git add` when a user create a file in git repo, but unfortunately when i check the activation event I don't see an event when a file is created.

I hope my request is not too stupid and you can answer it quickly.

Thanks in advance ;)

**Comment by jrieken** [comment]
There is a command (@bpasero will know which) which is being used to create a new file. You could use the `onCommand`-activator.

**Comment by bpasero** [comment]
@launay12u create how?

**Comment by alexandrudima** [comment]
@launay12u For cases where you don't find a good activation event, you can activate on `*`. If we receive multiple requests / find multiple use cases for a certain activation event, we will consider to add it.
