### ISSUE TITLE
Alway warn "You seem to have git 1.9.4 installed. Code works best with git >=2.0.0."

### ISSUE THREAD

**Issue by MichaelHuyPhan** [Microsoft/vscode#6117]
- VSCode Version:
![image](https://cloud.githubusercontent.com/assets/19192116/15035812/dc4da9fe-12b0-11e6-85b2-0a5448f4e411.png)

- OS Version:
![image](https://cloud.githubusercontent.com/assets/19192116/15035835/3c84b43e-12b1-11e6-9cd8-3dfd8b97bbf5.png)

-Git version: 
![image](https://cloud.githubusercontent.com/assets/19192116/15035845/5e4869da-12b1-11e6-80ee-e82fb80162f1.png)

Steps to Reproduce: 
Just open VS Code and it warn!!
![image](https://cloud.githubusercontent.com/assets/19192116/15035847/6f892c66-12b1-11e6-8688-c1d64a8d1cc1.png)

**Comment by stevenbrix** [comment]
I've noticed this as well. Not sure how it tries to detect what version of GIT I have installed, but I did not install Git to the default location (I chose c:\dev\git) so I don't know if that has something to do with it or not

**Comment by joaomoreno** [comment]
Please either uninstall the old git, put the latest git ahead in your `PATH` variable or simply tell Code where your latest git is installed via the `git.path` configuration setting.
