### ISSUE TITLE
autofetch causes ssh-askpass to popup

### ISSUE THREAD

**Issue by leonyu** [Microsoft/vscode#6118]
- VSCode Version: 1.0
- OS Version: Ubuntu

Steps to Reproduce:

1. install any of the `ssh-askpass` packages
2. have a git repo with passphrased ssh key
3. open VSCode
4. observe that ssh-askpass would popup

This is probably expected given the autofetch setting is the default. I am not sure how to solve it. 

Maybe auto-disable autofetch when one of the following is true
* askpass is installed
* git repo is detected to have a password

**Comment by rolandog** [comment]
I'm using Lubuntu 16.04.

VS Code first asked me to have ssh-askpass installed (can't remember what the prompt exactly said, but I'm having a very similar issue... even if my user settings declare that autofech is disabled)

The current issues I have are:
* I'm having a really long wait time for each commit
* I have to type in my passphrase for pulling
* I have to type in my passphrase, again, for pushing

Are these issues related to OP's? Or should I create a different issue?

**Comment by joaomoreno** [comment]
Either disable auto fetch using the configuration setting, use SSH for authentication or properly configure [a credential manager](https://help.github.com/articles/caching-your-github-password-in-git/#platform-all).
