### ISSUE TITLE
change how file explorer displays directories that only have one subdirectory

### ISSUE THREAD

**Issue by tylerthehaas** [Microsoft/vscode#61181]
Intellij has a feature with its file explorer that combines the name of directories that only have one subdirectory as shown below. This is very common in java projects and would be nice to have vscode behave the same way.

![image](https://user-images.githubusercontent.com/11150235/47121158-d180ae00-d22e-11e8-968f-a6d63ce65d9c.png)

**Comment by tylerthehaas** [comment]
Which issue is this a duplicate of? I tried to search issues and couldn’t find any similar issues. Also the original issue wasn’t linked to this issue.

**Comment by isidorn** [comment]
Search for issue tagged with explorer and feature-request. Thanks

**Comment by tylerthehaas** [comment]
I have searched that way. This is the closest issue I found but it is still a different issue. https://github.com/Microsoft/vscode/issues/6328
