### ISSUE TITLE
On Windows, if go.toolsGopath is set, 2 tools fail to install

### ISSUE THREAD

**Issue by EximChua** [Microsoft/vscode#61180]
- VSCode Version: 1.28.1
- OS Version: Windows 2008 R2 SP1

Installing 2 tools at D:\Development\Go\Tools\bin
  gorename
  godef

Installing golang.org/x/tools/cmd/gorename FAILED
Installing github.com/rogpeppe/godef FAILED

2 tools failed to install.

gorename:
Error: Command failed: C:\Go\bin\go.exe get -u -v golang.org/x/tools/cmd/gorename
Fetching https://golang.org/x/tools/cmd/gorename?go-get=1
Parsing meta tags from https://golang.org/x/tools/cmd/gorename?go-get=1 (status code 200)
get "golang.org/x/tools/cmd/gorename": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/cmd/gorename?go-get=1
get "golang.org/x/tools/cmd/gorename": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
golang.org/x/tools (download)
package golang.org/x/tools/cmd/gorename: cannot find package "golang.org/x/tools/cmd/gorename" in any of:
	C:\Go\src\golang.org\x\tools\cmd\gorename (from $GOROOT)
	D:\Development\Go\Tools\src\golang.org\x\tools\cmd\gorename (from $GOPATH)
Fetching https://golang.org/x/tools/cmd/gorename?go-get=1
Parsing meta tags from https://golang.org/x/tools/cmd/gorename?go-get=1 (status code 200)
get "golang.org/x/tools/cmd/gorename": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/cmd/gorename?go-get=1
get "golang.org/x/tools/cmd/gorename": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
golang.org/x/tools (download)
package golang.org/x/tools/cmd/gorename: cannot find package "golang.org/x/tools/cmd/gorename" in any of:
	C:\Go\src\golang.org\x\tools\cmd\gorename (from $GOROOT)
	D:\Development\Go\Tools\src\golang.org\x\tools\cmd\gorename (from $GOPATH)

godef:
Error: Command failed: C:\Go\bin\go.exe get -u -v github.com/rogpeppe/godef
github.com/rogpeppe/godef (download)
# github.com/rogpeppe/godef
runtime.main_main·f: function main is undeclared in the main package
github.com/rogpeppe/godef (download)
# github.com/rogpeppe/godef
runtime.main_main·f: function main is undeclared in the main package

Steps to Reproduce:

1. Set go.toolsGopath in User Settings (not Workspace settings) to a new location.
2. Install Go Tools to go.toolsGopath using Command Palette, "Go: Install/Update Tools" and install all tools.
3. All tools but 2 succeed. Retry step 2, but choose only gorename and godef.

Does this issue occur when all extensions are disabled?: This question does not apply, because if all extensions are disabled, Go cannot be used in VS Code.

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-go
