### ISSUE TITLE
Weird window issue

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#61195]
I have seen this a couple times. This time, the sidebar was hidden, and I pressed cmd+shift+d to show it. Then the workbench shifted left, leaving a blank space on thr right.

??

![image](https://user-images.githubusercontent.com/323878/47129909-2252cf80-d24c-11e8-888a-849320dc4b08.png)

The workbench is on the left and fully functional. No unusual errors in the dev tools. The Elements tool doesn't really show any reason for the workbench to be shifted over.

If I open the command palette, the window goes back to normal. Then I toggle the sidebar and it happens again. It only happens if the panel is open.

Here's a video of what I'm seeing... I'm just showing/hiding the sidebar and command palette and seeing the workbench slide around.

[Oct-17-2018 20-39-31.mp4.zip](https://github.com/Microsoft/vscode/files/2490094/Oct-17-2018.20-39-31.mp4.zip)

Let me know if you can think of anything else for me to debug? I can repro it consistently in one window and I'll leave it in that state as long as I can. Was Electron updated recently?

**Comment by bpasero** [comment]
@jrieken a regression from https://github.com/Microsoft/vscode/commit/9ac1a920081ef247f14d275cad010ac7cfc47cdd#diff-f04feb719eaac89f352441a4c6424777 it seems

**Comment by jrieken** [comment]
@roblourens Do you have repro steps for this?

**Comment by jrieken** [comment]
I have restored the old code, it doesn't use RAF because that just executes the trasher at the end of the current JS time slice. We kinda want RAF in next JS time slice which I mimicked with the good old `setTimeout`...

**Comment by alexr00** [comment]
@jrieken, how should this be verified?

**Comment by roblourens** [comment]
I didn't have a consistent repro, but I'll call it verified based on code review, and I haven't seen it lately.
