### ISSUE TITLE
After set "window.zoomLevel": -1 or -2. the character on editor is blurred.

### ISSUE THREAD

**Issue by MichaelHuyPhan** [Microsoft/vscode#6119]
- VSCode Version:1.0.0
- OS Version:Win 10 Pro

Steps to Reproduce:

1. Add setting to user setting.json "window.zoomLevel": -1,
2. Go to editor and all code is blurred. When scroll sometime it clear back then go blur again. Ref this:
![bug blurred](https://cloud.githubusercontent.com/assets/19192116/15036130/0d8c3ec8-12b5-11e6-9025-e0d88193906f.gif)

**Comment by bpasero** [comment]
Related:

https://github.com/Microsoft/vscode/issues/5411
https://github.com/Microsoft/vscode/issues/1896
https://github.com/Microsoft/vscode/issues/1334
https://github.com/Microsoft/vscode/issues/254
https://github.com/Microsoft/vscode/issues/959
