### ISSUE TITLE
Search results are not filtered

### ISSUE THREAD

**Issue by snovey** [Microsoft/vscode#61196]
- VSCode Version: 1.28.2
- OS Version: Mac OS 10.13.6

Steps to Reproduce:

1. Search some keyword
2. The search results contain files under the `node_modules` folder

![image](https://user-images.githubusercontent.com/15171147/47130901-6a1a3b00-d2ce-11e8-97ff-a97e3c598704.png)

Does this issue occur when all extensions are disabled?: Yes
(The background image is because the vscode file was modified)

**Comment by snovey** [comment]
I have never opened these files, they are always closed.

**Comment by roblourens** [comment]
Your screenshot shows that you've toggled off the "Use excludes" button (on the right side of the "files to exclude" box). If you click that, the exclude patterns will be used.

**Comment by snovey** [comment]
I apologize for my own mistakes
