### ISSUE TITLE
SFTP UPLOAD ERROR

### ISSUE THREAD

**Issue by swarmchen** [Microsoft/vscode#61191]
Issue Type: <b>Bug</b>

Can't set modified time to the file because Permission denied.This will cause "Sync" command to transfer unnecessary files.(this error will only show once) when local -> remote 

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (2.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
stylus|Ala|0.0.4
cssrem|cip|0.0.7
vscode-eslint|dba|1.6.1
vue-snippets|hol|0.1.9
beautify|Hoo|1.4.6
sftp|lix|1.6.3
dotenv|mik|1.0.1
vscode-apache|mrm|1.1.1
vscode-language-pack-zh-hans|MS-|1.28.2
mssql|ms-|1.4.0
python|ms-|2018.9.0
Go|ms-|0.6.92
sublime-keybindings|ms-|4.0.0
go-doc|msy|0.1.1
php-docblocker|nei|1.6.0
vetur|oct|0.13.0
vscode-icons|rob|7.27.0
vue-vscode-snippets|sdr|1.3.0
markdown-preview-enhanced|shd|0.3.8
python|tht|0.2.3
codelf|unb|10.7.0

(7 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
I don't think we support setting the modified time of a file?
