### ISSUE TITLE
Removing a keyboard shortcut is not feasible when multiple are in place

### ISSUE THREAD

**Issue by Ciantic** [Microsoft/vscode#612]
I want to remove a one keyboard shortcut from a tab key, and not touch the others. Specifically:

Original:
```
{ "key": "tab",                   "command": "editor.emmet.action.expandAbbreviation",
                                     "when": "editorTextFocus && !editorHasSelection && !editorHasMultipleSelections && !editorTabMovesFocus" }
```

There is no way to remove *only* above tab command. I tried to do it like the FAQ says, and added this:

```
	// Remove emmet from tab key
	{ "key": "tab",             "when": "editorTextFocus && !editorHasSelection && !editorHasMultipleSelections && !editorTabMovesFocus" },
	
```

But it removes *all* tab commands, including normal tab.

**Comment by Ciantic** [comment]
My suggestion how to implement this in VS Code:

If the original is this:

```
{ "key": "tab",                   "command": "editor.emmet.action.expandAbbreviation",
                                     "when": "editorTextFocus && !editorHasSelection && !editorHasMultipleSelections && !editorTabMovesFocus" }
```

Then removing a specific command from a key should require defining the "removeKey" and "command":

```
{ "removeKey": "tab", "command": "editor.emmet.action.expandAbbreviation" }
```
This would remove only the emmet from tab, other tab commands would remain unaltered.

This would be backwards compatible, since the old syntax of removing keys (defining the key empty) could be preserved.

----

Here is a hackish workaround for my *specific problem* emmet being in wrong key, until the keyboard shortcut overwriting feature is fixed:

See this file for reference: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/emmet/node/emmet.contribution.ts

Open up `Microsoft VS Code\resources\app\out\vs\workbench\workbench.main.js` 

Search for a string `ExpandAbbreviationAction.ID` and after that you should see the keybinding, then just replace `primary:a.KeyCode.Tab` with `primary:a.KeyCode.Unknown`.

**Comment by alexandrudima** [comment]
I like your suggestion, you want in a way to remove a specific rule in the array and you identify it via `key+command` in a way.

**Comment by alexandrudima** [comment]
fyi @egamma 
One idea I had was to copy-paste the rule and prefix the command with a minus:
```
{ "key": "tab",                   "command": "-editor.emmet.action.expandAbbreviation",
                                     "when": "editorTextFocus && !editorHasSelection && !editorHasMultipleSelections && !editorTabMovesFocus" }
```

**Comment by Ciantic** [comment]
@alexandrudima Isn't the "unneccessary" in there? 

```
{ "key": "tab", "command": "-editor.emmet.action.expandAbbreviation"}
```

Would be sufficient I think.

**Comment by alexandrudima** [comment]
For verifications. Ways to remove the emmet for example:

```
    // { "key": "tab", "command": "-editor.emmet.action.expandAbbreviation", "when": "editorTextFocus && !editorHasSelection && !editorHasMultipleSelections && !editorTabMovesFocus && config.emmet.triggerExpansionOnTab" }
    // { "key": "tab", "command": "-editor.emmet.action.expandAbbreviation" }
    // { "command": "-editor.emmet.action.expandAbbreviation" }
```

**Comment by jrieken** [comment]
```
    {
        "command": "-acceptSelectedSuggestion"
    }
```

I cannot undo the `.` keybinding we have for accepting a selected suggestion, neither with `-workbench.action.files.openFileFolder` and `Cmd+O`

**Comment by alexandrudima** [comment]
Nice catch! That's because the rule for `acceptSelectedSuggestion` uses the `^`:

```
{ "key": ".",                     "command": "^acceptSelectedSuggestion",
                                     "when": "editorTextFocus && suggestWidgetVisible && suggestionSupportsAcceptOnKey && editorLangId == 'typescript'" },
```

**Comment by KingGeneral** [comment]
help, not working when key is doubled, even when using  '-' or '^' in keybindings.json
`{ "key": "ctrl+left","command": "-cursorWordStartLeft"}`

want to remove this
```
{ "key": "ctrl+left",             "command": "cursorWordStartLeft",
                                     "when": "editorTextFocus" },
{ "key": "ctrl+shift+left",       "command": "cursorWordStartLeftSelect",
                                     "when": "editorTextFocus" },
```
