### ISSUE TITLE
command for view layouts ?

### ISSUE THREAD

**Issue by SheepDomination** [Microsoft/vscode#61201]
Where can I find the command for any of the *view* options; ie, `single column editor layout` ?

**Comment by SheepDomination** [comment]
These suggestions are not the answer to my question.

**Comment by Tyriar** [comment]
![image](https://user-images.githubusercontent.com/2193314/47327708-35d2b180-d623-11e8-8a56-23bc3408728d.png)

**Comment by SheepDomination** [comment]
![singlelayout_command](https://user-images.githubusercontent.com/6827459/47329189-c4562b80-d641-11e8-86f7-26053b7ff028.png)
If I exclude the `>` I still don't get the command for single column editor; as your command palette displays ?

**Comment by SheepDomination** [comment]
@Tyriar how are you typing `layout` cause as mentioned, I don't see what you see ?

**Comment by Tyriar** [comment]
@SheepDomination inside the keybindings editor, `ctrl+k, ctrl+s`
