### ISSUE TITLE
How to support experimentalObjectRestSpread ？

### ISSUE THREAD

**Issue by simonguo** [Microsoft/vscode#6120]
How to support experimentalObjectRestSpread ？

![Uploading BB243355-83CD-4B3B-BD11-360F311D10F3.png…]()

**Comment by bpasero** [comment]
@simonguo can you clarify? does this come from an extension?

**Comment by simonguo** [comment]
ESLint config 

```{
    "env": {
        "browser": true,
        "es6": true
    },
    "parserOptions": {
        "ecmaVersion": 6,
        "sourceType": "module",
        "ecmaFeatures": {
            "jsx": true,
            "experimentalObjectRestSpread":true
        }
    }
   ...
}
```

**Comment by bpasero** [comment]
@egamma @dbaeumer please chime in for ESLint.

**Comment by hiyangguo** [comment]
![qq 20160506164140](https://cloud.githubusercontent.com/assets/15609339/15068374/73a9a7e6-13a9-11e6-932a-edfbdefed36b.jpg)

**Comment by dbaeumer** [comment]
@egamma can you please answer. I know you wrote something up on how to support this.

**Comment by egamma** [comment]
@simonguo @hiyangguo voila the link to the [JavaScript doc](https://code.visualstudio.com/docs/languages/javascript#_disable-syntax-validation-when-using-non-es6-constructs)

**Comment by egamma** [comment]
Closing this issue since adding support for Object Rest Spread is already tracked in the TypeScript repository.
