### ISSUE TITLE
Can not switch to view other files when debug pause

### ISSUE THREAD

**Issue by xiaoyongdong** [Microsoft/vscode#61202]
Issue Type: <b>Bug</b>

I use the extension 'Cortex-Debug" to debug my project.  I found when i clicked Pause, I can not switch to view other files, it will go back automatically.  But when i clicked Continue to continue run, then I can switch.
This issue was found in insider 1.29, work fine in 1.28.
I upload a Gif to show this issue:
 
![1](https://user-images.githubusercontent.com/3884211/47132929-1f51f080-d2d9-11e8-92dc-5fd2ae10d2e5.gif)

VS Code version: Code - Insiders 1.29.0-insider (799bc78af597769a5dd5a6b002359ddae412b1be, 2018-10-17T05:19:06.776Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|3.91GB (0.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
cortex-debug|mar|0.1.21
cpptools|ms-|0.19.0
vscode-icons|rob|7.27.0

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
I can not reproduce this with node debugger.
Can you reproduce if you disable all extensions and try to debug a simple javascript file
```
console.log('hello')
```
Does the behavior happen if you open any other file, not just launch.json
This seems like a Cortex-Debug issues, but let's first wait for you to investigate more

**Comment by xiaoyongdong** [comment]
@isidorn I try to debug a python file, and no problem.
not just launch.json, same as any other file.
But the same extensions 1.28 can work fine.  So i think 1.29 maybe change something to cause it.

**Comment by isidorn** [comment]
So please fiel this issue against the extensoin, since when you debug python there is no problem. Thank you
