### ISSUE TITLE
Maximized - Tooltip on mouse hover moves the window down and right 1 pixel

### ISSUE THREAD

**Issue by sondresj** [microsoft/vscode#61205]
Reproduced in versions 1.28.1, 1.28.2 and 1.29.0 (insider build)

- VSCode Version: 1.28.1
- OS Version: Windows 10 (winver reports version 1607 (OS-build 14393.2189)

Steps to Reproduce:

1. Maximize VSCode window
2. Open Explorer (Ctrl+Shift+E)
3. Hover over a file
4. When the tooltip appears, the VSCode window also **moves 1** (or maybe 2) **pixels down and right**

Does this issue occur when all extensions are disabled?: **Yes**

Workaround: 
* Don't maximize VSCode

Maybe relevant:
* This issue occurs on my HP ZBook Studio G3, but **not** on my Dell XPS 15 (with Windows 10 Version 1803) (Both latpops have the same resolution).
* This issue goes away when there's a Windows noitification in the bottom right corner, or when the notifications are shown
* This issue also goes away when I try to record a video of it using Snagit... So I can't provide a video capture.

EDIT: It also occurs when hovering any menuitem, or anything that shows a tooltip (except in the editor)

**Comment by MatthewClair** [comment]
I am also experiencing this issue.  I also see it happening in Slack.  It seems to occur when displaying a Windows tooltip/menu but not one that is part of the application (ex: right clicking the menu bar causes the shift but the editor does not)

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/45498d93166483c2eff886e28f8dab915ae382fc/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/code-exploration_1.28.0-1538127308_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/VSCodeUserSetup-x64-1.28.0-exploration.exe)

**Comment by sondresj** [comment]
Hi @bpasero, 
I followed your link and installed and tested the exploration build for windows (see screenshot), and the answer is unfortunately **yes**, the issue is reproduced.

![image](https://user-images.githubusercontent.com/44254105/47339517-c056f780-d69b-11e8-9254-fc3c7f5efd33.png)

**Comment by DeltaRazero** [comment]
Experiencing this on the workstation I use at work as well. Though it's worth nothing that my desktop at home does not suffer from this.
Using Windows 10 Enterprise.
![image](https://user-images.githubusercontent.com/26445643/53561492-58378700-3b4f-11e9-9d9b-f62d165dca3c.png)

**Comment by DeltaRazero** [comment]
I tried and set the compability mode of VSCode to Windows 7 and that seems to get rid of it, interesting.

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)

**Comment by DeltaRazero** [comment]
Hi bpasero, I think that seems to fix it for me. That newer version of Electron also seems to fix another issue I had, namely that the VSCode window had a single black 1px high line at the bottom.
