### ISSUE TITLE
Create new file/folder fires on cmd + tab 

### ISSUE THREAD

**Issue by 19shubham11** [Microsoft/vscode#61200]
- VSCode Version: 1.28.0
- OS Version: MacOS Mojave 10.4

While creating a new file or folder , switching windows (cmd + tab) fires `NewFolderAction` if anything is typed in the placeholder. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Native explorer behaves the same: exmaple mac finder
