### ISSUE TITLE
Add yarn as valid task type

### ISSUE THREAD

**Issue by Ermish** [Microsoft/vscode#61203]
Hey, vscode team!

1) It would be awesome to be able to use `yarn` as a vscode task type.
2) Should have a `yarn` option in the default task options for the command palette `Task: Configure Task option

I didn't see any other open issues directly related to this, so feel free to close if there's a duplicate I missed.

**Comment by dbaeumer** [comment]
@egamma assigning to you since yarn should be 99% compatible with npm for which we have task auto detection support.

**Comment by egamma** [comment]
@Ermish ping?

**Comment by Ermish** [comment]
Oh nice! I didn’t have this option. I’ll take a look when I get back from my trip.

**Comment by egamma** [comment]
@Ermish since I haven't heard from you I assume things are fine and I'm closing the issue.

**Comment by arcanis** [comment]
@egamma would it be possible to define custom package managers? For example when developing, would it be possible to set it to `./vendors/yarn-1.13.0.js`, or does this settings affect more than just the binary being used?
