### ISSUE TITLE
all version after 1.25.1 can't launch at my win7 os

### ISSUE THREAD

**Issue by stone-wind** [Microsoft/vscode#61209]
- VSCode Version:1.26.1  1.27.2 1.28.2
- OS Version:windows 7

Steps to Reproduce:

1. run vscode and no ui appear

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
What happens when you run `code --verbose` from a terminal?

**Comment by myron-randall** [comment]
I have the same problem. When I type 
C:\>code --verbose
C:\>
If just returns and prints nothing.

**Comment by myron-randall** [comment]
Error happens with latest release 1.28.2. Also had the issue with version 1.26.1. My working version is 1.24.0.
Operating System=Windows 7
OS Service Pack=Service Pack 1
BIOS Date=09/16/14
[PROCESSOR]
Processor=Intel64 Family 6 Model 60 Stepping 3
Processor Mhz=2594 Mhz
Processor Vendor=GenuineIntel
[MEMORY]
Installed Memory=8069.91015625 Mb
Available Memory=3875.43359375 Mb
Percent Memory Free=48.02325576%
PageFile Parameters=0

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by myron-randall** [comment]
Same result:
C:\Program Files\Microsoft VS Code Insiders>"Code - Insiders" --version
C:\Program Files\Microsoft VS Code Insiders>"Code - Insiders" --verbose
C:\Program Files\Microsoft VS Code Insiders>

**Comment by myron-randall** [comment]
I usually use the 64 bit, but I tried with both 64 and 32 bit and neither works.

**Comment by bpasero** [comment]
Weird, @joaomoreno maybe any clues?

**Comment by joaomoreno** [comment]
@myron-randall Can you maybe check the system's Event Log, maybe there are some errors there?

**Comment by stone-wind** [comment]
I have try the 1.29.0 version, still can not launch. the system's event log as below, event ID is 7036:
日志名称:          System
来源:            Service Control Manager
日期:            2018/11/14 10:07:05
事件 ID:         7036
任务类别:          无
级别:            信息
关键字:           经典
用户:            暂缺
计算机:          LOCAL
描述:
Windows Error Reporting Service 服务处于 正在运行 状态。
事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Service Control Manager" Guid="{555908d1-a6d7-4695-8e1e-26931d2012f4}" EventSourceName="Service Control Manager" />
    <EventID Qualifiers="16384">7036</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8080000000000000</Keywords>
    <TimeCreated SystemTime="2018-11-14T02:07:05.287153500Z" />
    <EventRecordID>79581</EventRecordID>
    <Correlation />
    <Execution ProcessID="672" ThreadID="54280" />
    <Channel>System</Channel>
    <Computer>LOCAL</Computer>
    <Security />
  </System>
  <EventData>
    <Data Name="param1">Windows Error Reporting Service</Data>
    <Data Name="param2">正在运行</Data>
    <Binary>5700650072005300760063002F0034000000</Binary>
  </EventData>
</Event>

**Comment by stone-wind** [comment]
> 
> 
> I have the same problem. When I type
> C:>code --verbose
> C:>
> If just returns and prints nothing.

i clear this problem by this way(https://blog.csdn.net/CODES001/article/details/79784481):
at cmd run:
netsh winsock reset
