### ISSUE TITLE
[loc][Query][DevDiv] Please clarify "code"

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#6121]
Hi, we have a question about the English source. Please see below.

Source:
Click go to code
It is recommended not to run Code as 'root'.
Navigate to the code for the topmost method from the stack trace in my code.

File Name (respectively):
localize\ENU\Microsoft.VisualStudio.ApplicationInsights.dll
src\vs\workbench\electron-browser\shell.nls.resx
localize\ENU\Microsoft.VisualStudio.ApplicationInsights.dll

Resource ID (respectively):
0; "ClickGoToCode"
".resx", 0; "runningAsRoot"
0; "CodeLensGotoMyCodeHyperlinkTooltip"

Query:
Does code mean a concrete conception (which should be localized as 代码), or a code editor (which should be left as it is)? Please confirm. Thanks.	" by="CnE_zh-CN_translator

**Comment by bpasero** [comment]
@mkyjakova this does not seem to be in our code (ApplicationInsights.dll), why is it being picked up?

**Comment by jrieken** [comment]
wrong repo? we don't ship those dll-files

**Comment by mkyjakova** [comment]
Sorry, this went to the wrong database.

**Comment by mkyjakova** [comment]
Hi, I've modified the bug (deleted the .dll files) Can you please have a look at the one that remains?  Thanks!

**Comment by jrieken** [comment]
still wrong repo @mkyjakova ?
