### ISSUE TITLE
TypeScript: Property does not exist warning

### ISSUE THREAD

**Issue by screendriver** [Microsoft/vscode#61218]
- VSCode Version: 1.28.2
- OS Version: macOS Mojave

Steps to Reproduce:

1. write a type declaration that add properties to the `window` object in the file `./typings/dom/index.d.ts`

```ts
declare global {
  interface Window {
    foo: string;
  }
}
```

2. Add the `typings` directory to your `tsconfig.json` as compiler flag

```ts
"typeRoots": ["./typings", "./node_modules/@types"]
```

3. try to access the `foo` property

```ts
const bar = window.foo;
```

4. run `tsc` from your command line: everything works
5. look at Visual Studio Code and you see

<img width="480" alt="screen shot 2018-10-18 at 10 31 41" src="https://user-images.githubusercontent.com/149248/47141468-0b01f980-d2c1-11e8-8fe3-23151cceb3bd.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
You don't want `typeRoots` here. Please confirm that `dom/index.d.ts` is part of the tsconfig project by opening that file and running `TypeScript: go to project configuration`. This should open your tsconfig. 

If it does not, make sure that file is included

**Comment by screendriver** [comment]
I opened the file `./typings/dom/index.d.ts` in Visual Studio Code, pressed `Cmd + Shift + P` and entered `TypeScript: go to project configuration`. It directly jumped to my `tsconfig.json` that is located in my the project root.

But now I get the error `[ts] Augmentations for the global scope can only be directly nested in external modules or ambient module declarations.` 🤔 This was not the case before and I didn't change anything 😳 

My workaround is now to change `./typings/dom/index.d.ts` to

```ts
declare module 'dom' {
  global {
    interface Window {
      foo: string;
    }
  }
}
```

Then everything works. But I don't fully 100% understand why I have to do this? I read the [article in the docs](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#global-augmentation) but it doesn't explain how to do that with a `*.d.ts` file. Instead it explains how to do that from inside a module directly.

When I change `./typings/dom/index.d.ts` to

```ts
interface Window {
  foo: string;
}
```

It works as well. But what is then the purpose of `global`?

**Comment by mjbvz** [comment]
Not sure about that one. Try asking this on stackoverflow or over on the typescript repo

Closing since it sounds like the issue has been resolved
