### ISSUE TITLE
TypeScript syntax colouring incomplete

### ISSUE THREAD

**Issue by jpike88** [Microsoft/vscode#61215]
- VSCode Version: 1.28.1
- OS Version: macOS Mojave

Steps to Reproduce:

![screen shot 2018-10-18 at 3 01 25 pm](https://user-images.githubusercontent.com/9585787/47139740-bffadd00-d2e6-11e8-9fb1-93cb35bb4f75.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by SimonLoir** [comment]
This issue also occurs on Windows 7 with version 1.28.2 but it doesn't by using the [online version of monaco](https://microsoft.github.io/monaco-editor/)  : 
![2](https://user-images.githubusercontent.com/17649337/47145441-0d1c8600-d2ca-11e8-987e-59ebd2aceec9.PNG)

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript-TmLanguage/issues/675 to track upstream

**Comment by octref** [comment]
![image](https://user-images.githubusercontent.com/4033249/47875475-e2efbb80-ddd3-11e8-81fd-dec4653eb4ce.png)
