### ISSUE TITLE
Can't debug with child_process 

### ISSUE THREAD

**Issue by Trucc** [Microsoft/vscode#61226]
HI,

I don't have the same behavior when running script with child process fork over terminal and over VSCode.

example : 

main.js
```
...
// Mise en place des workers
const { fork } = require('child_process');
const forked = fork('./workers/modbusConnector.worker');
forked.send({ hello: 'world' });
forked.on('message', (msg) => {
  console.log('Message from child', msg);
});
...
module.exports = app;
```

./workers/modbusConnector.worker.js

```
process.on('message', (msg) => {
    console.log('Message from parent:', msg);
  });
  
  let counter = 0;
  
  setInterval(() => {
    process.send({ counter: counter++ });
  }, 1000);
```
Output from terminal - no debug mode : 

```
Message from parent: { hello: 'world' }
Message from child { counter: 0 }
Message from child { counter: 1 }
Message from child { counter: 2 }
Message from child { counter: 3 }
Message from child { counter: 4 }
```

From VS code - DEBUG mode : 

`Error: write EPIPE`

**Comment by weinand** [comment]
How does you debug config look like?
If you want to debug the child processes you'll have to add `"autoAttachChildProcesses": true` to it.
Please see https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_automatically-attach-debugger-to-nodejs-subprocesses

**Comment by Trucc** [comment]
Here you have my configuration : 
```
{
            "type": "node",
            "request": "launch",
            "name": "Lancer le programme",
            "program": "${workspaceFolder}\\bin\\www",
            "stopOnEntry": false,
            "autoAttachChildProcesses": true,
            "args": [
                
            ],
            "env": {
                "NODE_ENV": "development",
                "PORT" : 4000
            }
        }
```

Here is my error stack : 
```
 Debugger listening on ws://127.0.0.1:30581/5cc5ea0e-0132-49e9-aa19-79dacbda1495
Starting inspector on 127.0.0.1:30581 failed: address already in use
Debugger attached.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at _errnoException (util.js:992:11)
    at ChildProcess.target._send (internal/child_process.js:702:20)
    at ChildProcess.target.send (internal/child_process.js:586:19)
    at Object.<anonymous> (d:\repositories\hweb_server\app.js:112:8)
```

**Comment by weinand** [comment]
Are you using the node.js "cluster" module?

If not, please make sure that the child-process use different debug ports.
The error you are seeing indicates that a child process uses the same debug port as its parent.

If you are just "forking" or "spawning" child process, they automatically inherit the arguments passed to the parent. This includes the debug port.
 
For details see here: https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_automatically-attach-debugger-to-nodejs-subprocesses

When using node's "cluster" module the problem should not occur.

**Comment by Trucc** [comment]
I'm using the child-process. So how can i change debug port of these processes and make them debuggable by VSCode ?
