### ISSUE TITLE
Support custom linkify rules

### ISSUE THREAD

**Issue by ashi009** [Microsoft/vscode#61223]
VSCode currently linkify URLs in the source code, and one can follow the link with <kbk>Option</kbd> + Click.  It would be nice to support custom linkify rules in the workspace config, eg:

- follow `#123` to open an issue/pr
- follow `t/123` to open a ticket in a corp network

**Comment by alexandrudima** [comment]
This is doable from an extension. We have link provider API so any extension can mark any region of code as a link and open a custom URL when the link is clicked.
