### ISSUE TITLE
the window is no longer responding

### ISSUE THREAD

**Issue by ParkJongdoo** [Microsoft/vscode#61224]
- VSCode Version: latest version
- OS Version: Windows7

sometime I open editor it showing "The Window is not Longer responding" and error message.
also I try to quick open it showing the error message.

Does this issue occur when all extensions are disabled?: No

**Comment by ParkJongdoo** [comment]
I can't upload the profile... bcz of security policy in company...

**Comment by Tyriar** [comment]
If you launch using `code --verbose` in cmd.exe does it return anything interesting when the crash happens?

**Comment by ParkJongdoo** [comment]
I don't know but this message is different from other messages.

[7868:1025/083020.600:INFO:CONSOLE(1409)] "%cDEBUG", source: file:///D:/#.Secure
 Work Folder/9__UTILITY/VSCode-win32-ia32-1.28.1/resources/app/out/vs/workbench/
workbench.main.js (1409)

----------------------------------------------------------------------------------------------------------
[7868:1025/082937.764:INFO:CONSOLE(282)] "%c[Extension Host] %cactivating extens
ion %c(at Object.activate (C:\Users\LGRnD\.vscode\extensions\ms-vscode.cpptools-
0.19.0\out\src\LanguageServer\extension.js:41:13))", source: file:///D:/#.Secure
 Work Folder/9__UTILITY/VSCode-win32-ia32-1.28.1/resources/app/out/vs/workbench/
workbench.main.js (282)
[7868:1025/082937.779:INFO:CONSOLE(282)] "%c[Extension Host] %cstarting language
 server %c(at realActivation (C:\Users\LGRnD\.vscode\extensions\ms-vscode.cpptoo
ls-0.19.0\out\src\LanguageServer\extension.js:93:13))", source: file:///D:/#.Sec
ure Work Folder/9__UTILITY/VSCode-win32-ia32-1.28.1/resources/app/out/vs/workben
ch/workbench.main.js (282)
[7868:1025/082940.303:INFO:CONSOLE(1408)] "%cTRACE", source: file:///D:/#.Secure
 Work Folder/9__UTILITY/VSCode-win32-ia32-1.28.1/resources/app/out/vs/workbench/
workbench.main.js (1408)
[7868:1025/082947.078:INFO:CONSOLE(1408)] "%cTRACE", source: file:///D:/#.Secure
 Work Folder/9__UTILITY/VSCode-win32-ia32-1.28.1/resources/app/out/vs/workbench/
workbench.main.js (1408)
[7868:1025/082947.088:INFO:CONSOLE(1408)] "%cTRACE", source: file:///D:/#.Secure
 Work Folder/9__UTILITY/VSCode-win32-ia32-1.28.1/resources/app/out/vs/workbench/
workbench.main.js (1408)
[7868:1025/083015.776:INFO:CONSOLE(1408)] "%cTRACE", source: file:///D:/#.Secure
 Work Folder/9__UTILITY/VSCode-win32-ia32-1.28.1/resources/app/out/vs/workbench/
workbench.main.js (1408)
[7868:1025/083020.600:INFO:CONSOLE(1409)] "%cDEBUG", source: file:///D:/#.Secure
 Work Folder/9__UTILITY/VSCode-win32-ia32-1.28.1/resources/app/out/vs/workbench/
workbench.main.js (1409)
[7868:1025/083021.364:INFO:CONSOLE(1408)] "%cTRACE", source: file:///D:/#.Secure
 Work Folder/9__UTILITY/VSCode-win32-ia32-1.28.1/resources/app/out/vs/workbench/
workbench.main.js (1408)
[7868:1025/083021.603:INFO:CONSOLE(1408)] "%cTRACE", source: file:///D:/#.Secure
 Work Folder/9__UTILITY/VSCode-win32-ia32-1.28.1/resources/app/out/vs/workbench/
workbench.main.js (1408)
[7868:1025/083021.968:INFO:CONSOLE(1408)] "%cTRACE", source: file:///D:/#.Secure
 Work Folder/9__UTILITY/VSCode-win32-ia32-1.28.1/resources/app/out/vs/workbench/
workbench.main.js (1408)
[7868:1025/083021.978:INFO:CONSOLE(1408)] "%cTRACE", source: file:///D:/#.Secure
 Work Folder/9__UTILITY/VSCode-win32-ia32-1.28.1/resources/app/out/vs/workbench/
workbench.main.js (1408)
[7868:1025/083021.979:INFO:CONSOLE(1408)] "%cTRACE", source: file:///D:/#.Secure
 Work Folder/9__UTILITY/VSCode-win32-ia32-1.28.1/resources/app/out/vs/workbench/
workbench.main.js (1408)
[7868:1025/083021.980:INFO:CONSOLE(1408)] "%cTRACE", source: file:///D:/#.Secure
 Work Folder/9__UTILITY/VSCode-win32-ia32-1.28.1/resources/app/out/vs/workbench/
workbench.main.js (1408)

**Comment by mjmaldonado** [comment]
I'm having this same problem.

Here is the output of `code --verbose` from cmd.exe:

![image](https://user-images.githubusercontent.com/8247508/48517794-1a775280-e82d-11e8-9c40-dd1d3fa25d7a.png)

which subsequently opens a new VS Code session.

Visual Studio Code version:

`1.29.0
5f24c93878bd4bc645a4a17c620e2487b11005f9
ia32`

Windows 7 OS

**Comment by mjmaldonado** [comment]
This is a subsequent event:

![image](https://user-images.githubusercontent.com/8247508/48560752-2b1edb80-e8b4-11e8-971b-123880913c46.png)

which was showing when unlocked my computer today.

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!
