### ISSUE TITLE
Unable to Save html files in VISCode when the default program is Chrome

### ISSUE THREAD

**Issue by sanncode** [Microsoft/vscode#61228]
I was constantly getting this error when editing and saving html files - "Failed to save : A system error occurred (EBUSY: resource busy or locked"

- VSCode Version: 1.28.2
- OS Version: Windows 7 Enterprise
- Does this issue occur when all extensions are disabled?: Yes/No

Steps to Reproduce:

1. Open html file
2. Make changes to the code
3. Click File, Save..
4. See the error and unable to save file unless I use Save As.... to save it under a new name
5. The problem recurs even when I try to save the newly named file

The work-around I discovered was to switch the default program that opens html files from Chrome to Internet Explorer and now I'm able to save with no problems.

I'm creating this as a new issue because even though I discovered a work-around, there is obviously still a bug that prevents VSCode from successfully saving html files when the default is set to Chrome.

This is my first time submitting an issue using Github so hopefully I've explained enough above and the team at VISCode can solve this problem in the future.

Thanks

**Comment by sanncode** [comment]
An update to this error is that today I am still having the same problem saving files, even though my default program for opening html files is still Internet Explorer.   Basically my work-around has not been working today!

**Comment by bpasero** [comment]
This sounds like a configuration problem on the system and nothing we can do about.
