### ISSUE TITLE
Git: Showing old commit count

### ISSUE THREAD

**Issue by creator1134** [Microsoft/vscode#61225]
Issue Type: <b>Bug</b>

Its showing old commit counts even after git push using the UI. It gets pushed to the server but after some time the count reappears.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.87GB (7.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.2
numbered-bookmarks|ale|0.12.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.60
vscode-eslint|dba|1.6.1
gitlens|eam|8.5.6
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.40
react-native-react-redux|EQu|1.9.1
prettier-vscode|esb|1.6.1
auto-close-tag|for|0.5.6
beautify|Hoo|1.4.6
node-module-intellisense|lei|1.5.0
angular1-code-snippets-johnpapastyle|lpe|0.1.0
gitignore|mic|1.0.1
vsliveshare|ms-|0.3.834
debugger-for-chrome|msj|4.10.2
LiveServer|rit|5.1.1
code-settings-sync|Sha|3.2.0
better-align|wwm|1.1.6
ReactSnippets|xab|2.2.1
html-css-class-completion|Zig|1.17.1

(7 theme extensions excluded)

</details>

**Comment by creator1134** [comment]
![vscode](https://user-images.githubusercontent.com/15572280/47288286-192e7d80-d613-11e8-80b4-af45de951e94.JPG)

Attached screenshot, the problem with "synchronize Change".

The count appears back when switching between projects or branches.

**Comment by creator1134** [comment]
![screenshot](https://user-images.githubusercontent.com/15572280/47288286-192e7d80-d613-11e8-80b4-af45de951e94.JPG)

Attached screenshot, the problem with "synchronize Change".

The count appears back when switching between projects or branches.

**Comment by joaomoreno** [comment]
What does `git status` return?

**Comment by joaomoreno** [comment]
So.. git is reporting the same as VS Code:

```
On branch <dev>
Your branch is ahead of 'origin/dev' by 17 commits.
  (use "git push" to publish your local commits)
```

**Comment by creator1134** [comment]
when I do the git push. The counter resets back to zero. But after some time, it reset back to some number i.e., it shows n no. of the commit in the status again like 
```
On branch <dev>
Your branch is ahead of 'origin/dev' by 17 commits.
  (use "git push" to publish your local commits)
```

**Comment by creator1134** [comment]
so, the problem is related to git, not vscode?

Because I am facing this issue in more than one project in vscode.

**Comment by joaomoreno** [comment]
It might be related to another piece of software which is messing with your repositories. Can you reproduce when running with `code --disable-extensions`?

**Comment by creator1134** [comment]
Its working fine with extensions disabled, I guess some extension have the issue. Thanks you for looking into the matter.
