### ISSUE TITLE
[loc][Query][DevDiv] Please clarify "Contribute"

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#6122]
Hi, we have a query about the English source. Can you please help us clarify?

Source:
Contributes textmate color themes.

File Name:
src\vs\workbench\services\themes\electron-browser\themeService.nls.resx

Resource ID:
".resx", 0; "vscode.extension.contributes.themes"

Query:
Could you give more information here? It's hard to get the exact meaning of "Contribute". Thanks." by="CnE_zh-CN_translator_29

**Comment by aeschli** [comment]
This is used in the context of our extension APIs. Extensions can add a new theme to VSCode. They 'contribute' a new theme to VSCode. To do so the extension needs a special entry in their package.json file under key 'contribute/themes' 
The translated label is the description of that key. 
There are many other similar contribution points.
nls.localize('vscode.extension.contributes.languages', 'Contributes language declarations.'),
nls.localize('vscode.extension.contributes.snippets', 'Contributes TextMate snippets.'),
nls.localize('vscode.extension.contributes.grammars', 'Contributes textmate tokenizers.'),
...
