### ISSUE TITLE
Fold All Regions feature doesn't work

### ISSUE THREAD

**Issue by suadev** [Microsoft/vscode#61220]
- VSCode Version: 1.28.2
- OS Version: Windows

"Fold All Regions" feature doesn't work neither by ctrl+k, ctrl+8 nor by F1 menu.

**Comment by aeschli** [comment]
Please add a code sample. I tried with the folloing sample and it worked
foo.ts
```ts
//#region
Test
//#endregion
//#region
Test2
//#endregion
```
- ctrl + k / ctrl + 8: folds all regions
- ctrl + k / ctrl + 9: unfolds all regions

**Comment by suadev** [comment]
@aeschli sorry, i should have specified the language.

It looks,  it's ok for .ts file. 

But for .cs file, it doesn't work.

```
public class foo
{
    #region newregion
    int i = 0;
    #endregion
}

**Comment by aeschli** [comment]
Do you use an extension for c# ?

Out of the box you get indentation based folding with region markers sand your example works the same way as my example.
But maybe an extension adds language specific folding and doesn't mark the regions correctly.

**Comment by suadev** [comment]
Yes, i use c# extension that powered by omnisharp.  My whole extension list; 

![image](https://user-images.githubusercontent.com/5918811/47366723-f372a880-d6e6-11e8-8f90-2ada70fe5605.png)

**Comment by aeschli** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#2621
