### ISSUE TITLE
[loc][Query][DevDiv] Typo in Source "run"

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#6123]
Hi, we found a possible typo in source. Can you please have a look?

Source:
Customizes which terminal to on Linux.

File Name:
src\vs\workbench\parts\execution\electron-browser\terminal.contribution.nls.resx

Resource ID:
".resx", 0; "terminal.external.linuxExec"

Query:
It looks like the verb "run" is missing from the source. Please check and confirm.

**Comment by Tyriar** [comment]
Already fixed on master

**Comment by mkyjakova** [comment]
Excellent! Thank you.
