### ISSUE TITLE
Jumping to the bottom on formatting after update to 1.28

### ISSUE THREAD

**Issue by goriunov** [Microsoft/vscode#61231]
- VSCode Version: 1.28
- OS Version: Linux, Mac IS

Steps to Reproduce:

1. Create long file with js code for example (with wrong formatting)
2. Then select everything with ctrl + a 
3. Then format file with alt+shilt+f (or depending on the system) you will be moved to the bottom of the file (it is very annoying)

Previous version did not have this issue (i kind of got used to this so needed to roll back my vscode version)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Same issue as #60339

**Comment by jrieken** [comment]
This is the design as of fixing #48051

**Comment by alexandrudima** [comment]
@goriunov You can execute Shift+Alt+F without selecting the entire file and it still works.
