### ISSUE TITLE
auto hints is not available under the scope of cycle statement in python file

### ISSUE THREAD

**Issue by imshi** [Microsoft/vscode#61233]
VSCode Version: 1.28.2
OS Version: Windows 10 
Python Version：3.6.5
 Q&A： 
         auto hints is not available under the scope of cycle statement, such as for or while...etc, in python file,
         but if i print something with auto hints outside these scope, then it will work fine

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-python/
