### ISSUE TITLE
Phantom artifact on screen in editor below html text

### ISSUE THREAD

**Issue by MilosStanic** [Microsoft/vscode#61232]
- VSCode Version: 1.28.2
- OS Version: Windows 10

A strange artifact, in fact a part like a screenshot of the upper left portion of VSCode, appears below the end of a HTML file opened in editor. For some reason, only in opened HTML files. Not other files. 

![screenshot_120](https://user-images.githubusercontent.com/3983854/47150999-bb2f2c80-d2d8-11e8-8c25-7e69e0b710a4.png)

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/45498d93166483c2eff886e28f8dab915ae382fc/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/code-exploration_1.28.0-1538127308_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/VSCodeUserSetup-x64-1.28.0-exploration.exe)
