### ISSUE TITLE
Windows installer deletes project files

### ISSUE THREAD

**Issue by mpaland** [Microsoft/vscode#61234]
- VSCode Version: 1.28.2
- OS Version: Windows 10 Pro 1803 64bit

Steps to Reproduce:

1. VScode is installed at `D:/VS Code`
2. My project folder in inside: `D:/VS Code/projects`  <<< perhaps that's bad?
3. Notification on available update (from 1.27.1)
4. Update started but stops with error.
5. Manually download latest VScode 1.28.2 64 bit for Windows
6. Install to `D:/VS Code`

Nearly all files ending on .json, .js and .ts are deleted below `D:/VS Code/projects`.
Strange is that files in deeper level subdirs remain: `D:\VS Code\projects\test\src\applet\image` still has all files.
The whole folder remains, but most top project folders are empty and have no files anymore.

**CAUTION: THIS BUG CAUSED A FILE LOSS OFF FEW FILES WHICH WERE UNCOMMITTED WHILE UPDATING.**

Does anyone else observed this?

**Comment by joaomoreno** [comment]
> My project folder in inside: D:/VS Code/projects <<< perhaps that's bad?

Yes! That's very bad! Don't place your files inside VS Code's installation folder.
