### ISSUE TITLE
Middle mouse button scrolling breaks when click+holding on a image within release notes. 

### ISSUE THREAD

**Issue by Steve-Fry** [Microsoft/vscode#61238]
Issue Type: <b>Bug</b>

1. Open VSCode
2. Open release notes (Control+Shift+P --> Release Notes) 
3. **Click and hold middle mouse button** while mouse is over an image. 

Expected behavior: 
 - Screen will scroll according to offset of mouse postion from inital mousedown position. 

Actual behavior: 
 - No scrolling occurs. 
 - All mousewheel based scrolling is not possible from this time on. This is only returned to normal functionality after switching tabs/reloading editor. 

GIF Example
![repro1](https://user-images.githubusercontent.com/29991066/47156235-8d4ce680-d2de-11e8-9b98-eca931ce552d.gif)
Events:
- Left Click - Clear existing selected text
- Middle Mouse Click on text
- Middle Mouse Click on image
- Middle mouse Click+Hold on text
- Middle mouse Click+Hold on image

VS Code version: Code - Insiders 1.29.0-insider (9e83209ed59a22df3d593735d04cc963396bb89e, 2018-10-18T05:17:36.900Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz (6 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (8.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.9.0

</details>

Edit: Added explanation of steps on gif

**Comment by Steve-Fry** [comment]
IMO not related to 
#6302
#16514
#40985

**Comment by T3sT3ro** [comment]
Also what can be seen on this gif is another bug(I don't believe that it's intended behaviour): scrolling the release notes with MMB held selects the text. Same effect as holding LMB over text and scroling with keyboard arrow keys. When VS Code doesn't have focus, selection still appears and MMB scrolling doesn't work. - Windows, idk about other OSes.

**Comment by rrmistry** [comment]
I do not notice this issue anymore with January 2019 (version 1.31) release.

Version: 1.31.1 (system setup)
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:20:54.427Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by mjbvz** [comment]
@Steve-Fry Can you please verify this too?

It may have been fixed when we updated to electron 3

**Comment by Steve-Fry** [comment]
Confirmed fixed in latest version of stable.

Many thanks for the feedback + fix.
