### ISSUE TITLE
Explorer not showing the file tree correctly when scroll

### ISSUE THREAD

**Issue by tonny008** [Microsoft/vscode#61230]
Issue Type: <b>Bug</b>

Explorer not showing the file tree correctly when scroll if the tree is big

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|16.00GB (0.29GB free)|
|Process Argv|-psn_0_1823165|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
ng-template|Ang|0.1.10
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.60
vscode-svgviewer|css|1.4.7
xml|Dot|2.3.2
gitlens|eam|8.5.6
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.40
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.6.1
auto-rename-tag|for|0.0.15
code-runner|for|0.9.4
kotlin|fwc|0.1.8
vscode-lombok|Gab|0.9.6
rest-client|hum|0.20.2
jdl|jhi|1.4.1
Angular2|joh|6.3.0
python|ms-|2018.9.0
Go|ms-|0.6.92
vsliveshare|ms-|0.3.834
debugger-for-chrome|msj|4.10.2
vscode-docker|Pet|0.3.1
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.0.0
vscode-manifest-yaml|Piv|1.0.0
vscode-spring-boot|Piv|1.0.0
material-icon-theme|PKi|3.6.0
quicktype|qui|12.0.46
java|red|0.32.0
LiveServer|rit|5.1.1
vscode-java-debug|vsc|0.14.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.10.0
vscode-maven|vsc|0.11.1
vscode-spring-boot-dashboard|vsc|0.1.2
vscode-spring-initializr|vsc|0.4.0

</details>

**Comment by Tyriar** [comment]
Can you provide a screenshot?

**Comment by tonny008** [comment]
It looks like two layers overlapped and have different scroll speed.
i have seen it many times when node_module expanded. however, I cannot reproduce now
I will take screenshot next time.

**Comment by joaomoreno** [comment]
OK, we'll be waiting.
