### ISSUE TITLE
Format on save doesn't work 

### ISSUE THREAD

**Issue by matepek** [Microsoft/vscode#61237]
Issue Type: <b>Bug</b>

Probably since the last update the vscode doesn't reformat my ts code.
- Yes it is set in workspace config (and user config too).

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.5.6
vsc-material-theme|Equ|2.4.2
vscode-npm|fkn|3.3.0
todo-tree|Gru|0.0.92
vscode-test-explorer|hbe|2.0.9
python|ms-|2018.9.0
cpptools|ms-|0.19.0
vscode-gn|npc|1.0.0
python|tht|0.2.3
cmake|twx|0.0.17
vscode-lldb|vad|1.0.0
clang-format|xav|1.6.2

</details>

**Comment by matepek** [comment]
Actually it seems it only has a problem with one of my files. I will try to create an example later.

**Comment by mjbvz** [comment]
Closing as needs more info. Please follow [this guide](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions) on what to include in issue reports
