### ISSUE TITLE
Breakpoints move up 10 lines when debugging jest tests

### ISSUE THREAD

**Issue by makr28** [Microsoft/vscode#61235]
Issue Type: <b>Bug</b>

I am working on a Node.js project with Jest unit tests. I am using the launch configuration i've pasted below to run the jest tests. If I put a break point on line 280, when I run the debugger the break point is now on line 270. 

This did not happen on the older version of VS Code I had on my previous laptop (a Lenovo Thinkpad w541) And began only once I got a new laptop (Dell precision 5530) and installed the current version of VS Code. 

My Launch Configuration
{
      "type": "node",
      "request": "launch",
      "name": "Jest Tests (Windows)",
      "program": "${workspaceRoot}\\node_modules\\jest\\bin\\jest.js",
      "args": ["-i"],
      "internalConsoleOptions": "openOnSessionStart",
      "outFiles": ["${workspaceRoot}/dist/**/*"]
    }  

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:13:53.910Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.74GB (17.88GB free)|
|Process Argv|--folder-uri file:///c%3A/dev/HTML5/media-viewer-js|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by roblourens** [comment]
This is being discussed in https://github.com/facebook/create-react-app/issues/5319
