### ISSUE TITLE
[oc][Query][DevDiv] Please clarify "Debug"

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#6124]
Hi, we have a question from our translator and I was hoping you could help.

Source:
Debug Call Stack
Debug Watch Expressions

File Name:
src\vs\workbench\parts\debug\browser\debugViews.nls.resx

Resource ID:
".resx", 0; "callStackAriaLabel"
".resx", 0; "watchAriaTreeLabel"

Query:
Please clarify if "Debug" is noun here, or a verb. Thanks.  	Zinacle	4/27/2016 12:17:02 PM

**Comment by isidorn** [comment]
Debug is a noun here, I have added comments for the translators.

**Comment by mkyjakova** [comment]
Fantastic, thank you!
