### ISSUE TITLE
Version 1.28.2 is still slow !

### ISSUE THREAD

**Issue by choreno** [Microsoft/vscode#61245]
I've installed the latest version. 1.28.2.
But it's still slow.  I've rollback again to 1.25. 

Please check my previous issue,  "it's very very very slow! #61004"

Thanks. 

 

- VSCode Version: 1.28.2
- OS Version: win7 x64

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jrieken** [comment]
@choreno Please try to understand what a duplicate is
