### ISSUE TITLE
Blank space opening new terminal

### ISSUE THREAD

**Issue by IAmHopp** [Microsoft/vscode#61249]
Issue Type: <b>Bug</b>

So... This is a bit of a weird issue, so I waited a few builds to see if how permanent it was and it's not going away, so here I am.

Here's what's happening: Whenever I open a new terminal, the line that used to display the path is just blank. The cursor is dislocated to the right, so the space to display the path is allocated, it just doesn't show anything. If I start typing, the text shows up correctly, but anything before it is blank.

Here's what I see right after opening a new terminal:

![image](https://user-images.githubusercontent.com/8302437/47170009-63de8b80-d2db-11e8-9c4e-ed0561f0a119.png)

Here's what it looks like after typing a new command:

![image](https://user-images.githubusercontent.com/8302437/47170049-7953b580-d2db-11e8-85cd-b9f41712daba.png)

Here is what I see scrolling up [notice the scrollbar]:

![image](https://user-images.githubusercontent.com/8302437/47170107-9b4d3800-d2db-11e8-88dc-218a9fc711a8.png)
![image](https://user-images.githubusercontent.com/8302437/47170120-a56f3680-d2db-11e8-8e73-23e499f6e0f1.png)

If I select the area where the path should be, copy the contents and paste it into the editor, it's all just blank spaces. I have no idea what this is. Not critical, of course, but it's certainly unusual.

VS Code version: Code - Insiders 1.29.0-insider (9e83209ed59a22df3d593735d04cc963396bb89e, 2018-10-18T05:17:36.900Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (7.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.5.6
mssql|ms-|1.4.0
vsliveshare|ms-|0.3.834
team|ms-|1.142.0
vscode-docker|Pet|0.3.1
java|red|0.32.0
vscode-java-debug|vsc|0.14.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.10.0
vscode-maven|vsc|0.11.1
html-css-class-completion|Zig|1.17.1

</details>

**Comment by IAmHopp** [comment]
I'm not on a Windows Insider build.

**Comment by michael-hawker** [comment]
@IAmHopp the bug was originally filed for Windows Insiders, but now that is the official release, where the same bug is still present.  There sounds like there's a fix coming upstream for it though.

**Comment by criduvero** [comment]
Close this issue please. Now We know there are other open, and the problem is with Windows  RS5 1809

**Comment by IAmHopp** [comment]
Oh, right. Forgot these could be closed by the submitter.
