### ISSUE TITLE
cant open vscode without network

### ISSUE THREAD

**Issue by God1W** [Microsoft/vscode#61242]
Issue Type: <b>Bug</b>

I just cant open vscode without network
my system is win10 pro

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.92GB (5.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
latex-workshop|Jam|5.13.0
python|ms-|2018.9.0
cpptools|ms-|0.19.0
markdown-all-in-one|yzh|1.6.2

</details>

**Comment by Tyriar** [comment]
What happens when you try? Could you run code --verbose and see what the output is?

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/7570
