### ISSUE TITLE
Sidebar not restoreing the correct width

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#61255]
Issue Type: <b>Bug</b>

Up to a few days ago the Sidebar always have the outermost one's width. Some recent commits changed the behavior so the restored sidebar is always narrower:

![image](https://user-images.githubusercontent.com/4033249/47172650-eefe5800-d2c0-11e8-9e9d-f03acee0149d.png)

VS Code version: Code - Insiders 1.29.0-insider (9e83209ed59a22df3d593735d04cc963396bb89e, 2018-10-18T05:11:43.632Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 3, 3|
|Memory (System)|16.00GB (0.23GB free)|
|Process Argv|-psn_0_8566827|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.1.3
tslint|eg2|1.0.40
vsc-material-theme|Equ|2.4.2
prettier-vscode|esb|1.6.1
theme-monokai-pro-vscode|mon|1.1.8
vscode-language-pack-de|MS-|1.28.2
vscode-language-pack-ja|MS-|1.28.2
Go|ms-|0.6.92
debugger-for-chrome|msj|4.10.2
vetur|oct|0.13.0
polacode|pnp|0.2.2
shader|sle|1.1.4
language-stylus|sys|1.10.0
vim|vsc|0.16.10

(2 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
@bpasero Somehow related to html caching?

**Comment by octref** [comment]
Not really sure what's the cause, but this issue is a bit annoying. Hope it can be fixed for October.

**Comment by bpasero** [comment]
@octref @sandy081 what's the issue here?

**Comment by bpasero** [comment]
@octref @sandy081 what's the issue here?

**Comment by bpasero** [comment]
@octref can you explain with different words and steps to reproduce what the issue is here?

**Comment by bpasero** [comment]
@octref @sandy081 I am not sure I understand the issue, what is it?

**Comment by sandy081** [comment]
If I understand correctly, @octref says the side bar width is restored with different width after reload than of the first window

**Comment by NavyAdmiral** [comment]
@bpasero If you modify the sidebar width, the changes made aren't persistent. To clarify, open vscode, change the sidebar width, open new vscode, take a look at the sidebar and notice that it is back to the unmodified width.

**Comment by octref** [comment]
I cannot find a consistent repro case, but once in a while when I open a new VS Code window, the sidebar would be in the narrower state.

**Comment by bpasero** [comment]
@NavyAdmiral I cannot reproduce

@octref steps please

**Comment by octref** [comment]
@bpasero I can't find a reliable repro, but can you try this?

- Continue to open new windows
- For each window, run `Open Recent` and pick one of the old project that was opened

Also, any info I can get for you when I'm running into this issue?

**Comment by octref** [comment]
![repro](https://user-images.githubusercontent.com/4033249/47310349-acec5380-d5eb-11e8-9e7b-b4192f27520e.gif)

**Comment by bpasero** [comment]
@octref we store the size of the sidebar with a delay of 800ms so you might be able to hit this when you open new windows fast enough. I do not think this would happen for normal users.

**Comment by Tyriar** [comment]
I looked into this and it seems to be related to newly opened windows saving the initial state into `storage://global/workbench.sidebar.width` before the restore happens. Here's the repro:

1. Close all VS Code windows and open a new one with a folder opened
2. Resize the width to around 300-400
3. Open devtools and verify that `storage://global/workbench.sidebar.width` is 300-400
4. Open a new window, keep devtools visible in the background
5. Open a folder in the new window, at this point `storage://global/workbench.sidebar.width` will flash and update to 170 incorrectly

**Comment by bpasero** [comment]
Probably a regression from https://github.com/Microsoft/vscode/commit/6187c6672710fcc03b4450ebc136155253cea0f4, which I just reverted.
