### ISSUE TITLE
Outline double-click usability issues

### ISSUE THREAD

**Issue by mgood** [Microsoft/vscode#61252]
Issue Type: <b>Bug</b>

Clicking on an entry in the outline causes the view to scroll to center that entry. This makes it difficult to double-click and jump to an item since the view moves between clicks.

So, to go to an entry you have to:

1) single-click on the item
2) move your mouse to the new location after it scrolls
3) double-click to jump

I think the intended behavior is to scroll to make the current item visible when moving through the source file. Scrolling after clicking on an item in the view is unnecessary since it's inherently visible in that case.

Ideally the view should only scroll if the new highlight is not already visible, but if that's difficult it might also make sense to just avoid scrolling when triggered by a click in the outline view.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 17.7.0

**Comment by jrieken** [comment]
The problem is that the tree has no function like `revealInCenterIfOutsideViewport` and therefore we always reveal in the center (middle).

**Comment by joaomoreno** [comment]
@jrieken You can use `getRelativeTop` to figure out if an item is visible. Then, you can use `reveal` to reveal it wherever.
