### ISSUE TITLE
Unsplit editor window

### ISSUE THREAD

**Issue by henrychoi** [Microsoft/vscode#61251]
I searched for 'unspilt' and found 'split' https://github.com/Microsoft/vscode/issues/36700

I love the split feature; that's how I get 3 or more panes easily.  But cleaning up the mess is a bit more difficult, because I usually open yet other files in the newly created split window.  Un-splitting, then, is actually about merging all the files in a editor pane to an adjacent pane.  Picking which pane to move the editor windows over is not an obvious choice,  but I would be happy with VSC making that choice for me--all for. the convenience of many mouse movements.

**Comment by usernamehw** [comment]
`View: Join Editor Group with Next Group` **`workbench.action.joinTwoGroups`**
`View: Join All Editor Groups` **`workbench.action.joinAllGroups`**
