### ISSUE TITLE
Can't get out of vim insert mode

### ISSUE THREAD

**Issue by gvanderest** [Microsoft/vscode#61257]
Issue Type: <b>Bug</b>

Sometimes I'll be in the middle of editing, and hit ESC to get out of insert mode.

This results in an error `Activating extension 'vscodevim.vim' failed: Cannot read property 'document' of undefined.`

It doesn't happen all the time, so I don't know the exact cause.

```
Activating extension `vscodevim.vim` failed:  Cannot read property 'document' of undefined (at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:312:325)
```

VS Code version: Code - Insiders 1.29.0-insider (9e83209ed59a22df3d593735d04cc963396bb89e, 2018-10-18T05:11:43.632Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 6, 7|
|Memory (System)|16.00GB (0.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
ion-format-support|Avi|1.0.2
vscode-eslint|dba|1.6.1
java-debug|DSn|0.0.2
tslint|eg2|1.0.40
gc-excelviewer|Gra|2.1.26
todo-tree|Gru|0.0.92
rainbow-csv|mec|0.7.1
mssql|ms-|1.4.0
python|ms-|2018.9.0
sublime-keybindings|ms-|4.0.0
gradle-language|nac|0.2.3
indent-rainbow|ode|7.2.4
java|red|0.32.0
missinglineendoffile|ric|0.3.1
vscode-java-debug|vsc|0.14.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.10.0
vscode-maven|vsc|0.11.1
vim|vsc|0.16.10
vscode-todo-highlight|way|1.0.4
plsql-language|xyz|1.5.0

(1 theme extensions excluded)

</details>

**Comment by bradens** [comment]
I think this is fixed by https://github.com/VSCodeVim/Vim/pull/3146
