### ISSUE TITLE
[loc][Query][DevDiv] Please clarify "Find telemetry for this"

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#6125]
Hi, we have a query about the English source. Can you please advise?

Source:
Find telemetry for this

File Name:
localize\ENU\Microsoft.VisualStudio.ApplicationInsights.dll

Resource ID:
0; "RelatedItemsInlineText"

query:
Please clarify what this string will be followed by. Thanks.	Zinacle	4/27/2016 2:56:27 PM

**Comment by bpasero** [comment]
@mkyjakova this does not seem to be in our workspace?

**Comment by jrieken** [comment]
we don't ship: Microsoft.VisualStudio.ApplicationInsights.dll
