### ISSUE TITLE
Information displayed twice in log/Terminal

### ISSUE THREAD

**Issue by kgoderis** [Microsoft/vscode#61266]
Issue Type: <b>Bug</b>

I can not reproduce the problem, it just happned after an upgrade of azure tools. See screenshot. ILogger.LogInformation() output is displayed in blue and in white, whereas the other information dumped by the azure func host is only displayed once. 

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/5459062/47182185-20107400-d325-11e8-80d7-d597fab65509.png">

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-04T16:40:40.180Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|-psn_0_131104|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
azure-storage-explorer|for|0.1.2
AzureFunctionsSnippets|hha|0.1.0
vscode-github|Kni|0.30.0
vscode-azureappservice|ms-|0.9.1
vscode-azurefunctions|ms-|0.11.0
vscode-azurestorage|ms-|0.4.2
vscode-azureterraform|ms-|0.2.2
vscode-cosmosdb|ms-|0.8.0
vscode-kubernetes-tools|ms-|0.1.14
mssql|ms-|1.4.0
python|ms-|2018.9.0
vscode-ai|ms-|0.3.1
azure-account|ms-|0.4.3
azurecli|ms-|0.4.2
csharp|ms-|1.16.2
PowerShell|ms-|1.9.0
vscode-azureextensionpack|ms-|0.0.9
team|ms-|1.142.0
azurerm-vscode-tools|msa|0.4.2
azure-hdinsight|msh|0.0.17
openhab|ope|0.4.0
vscode-docker|Pet|0.3.1
typescript-hero|rbb|3.0.0
java|red|0.32.0
vscode-yaml|red|0.0.17
arm-snippets|sam|1.3.7
usql-vscode-ext|usq|0.2.14
application-insights|Vis|0.4.2
azure-iot-edge|vsc|1.5.0
azure-iot-toolkit|vsc|1.5.0
vscode-java-debug|vsc|0.14.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.10.0
vscode-maven|vsc|0.11.1

</details>

**Comment by Tyriar** [comment]
This is likely an issue with the program you're running within the terminal. If you see it again you can enable escape sequence logging and see what is getting sent to VS Code https://github.com/Microsoft/vscode/wiki/Terminal-Issues#enabling-escape-sequence-logging
