### ISSUE TITLE
Explorer rename text field screen cheese

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#61269]
Notice the left border:

<img width="415" alt="screenshot 2018-10-18 at 13 59 17" src="https://user-images.githubusercontent.com/22350/47183910-131c6200-d2de-11e8-89d3-b23c5d0e49c7.png">

**Comment by isidorn** [comment]
@garymathews can you please look into this, it is caused by your PR. Let me know if you do not have time and I can fix / potential revert the PR.
