### ISSUE TITLE
Empty folder with parent .git folder resulting in high cpu use on Mac

### ISSUE THREAD

**Issue by xsstomy** [Microsoft/vscode#6126]
- VSCode Version:1.0.0
- OS Version:10.11.4

Steps to Reproduce:

1. using vscode to open an empty folder 
2. creating a file ,eg:index.html
3.  to write something 

![1](https://cloud.githubusercontent.com/assets/8943787/15039952/5aafe1b8-12e3-11e6-8edc-ec36162c356a.png)

sorry for my poor english

**Comment by bpasero** [comment]
The 99+ over git is very suspicious so I assume the folder is not empty. @xsstomy is there a parent .git repository maybe that is very large? Can you send me the `ps aux | grep` of the process that is high?

**Comment by xsstomy** [comment]
@bpasero yes,you are right, there is a parent .git repository.

the follow?


xiashishi       79779 102.1  3.8  4796332 322824   ??  R    11:09PM   0:26.77 /Applications/Visual Studio Code.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper --type=renderer --no-sandbox --lang=en-US --node-integration=true --enable-delegated-renderer --num-raster-threads=2 --gpu-rasterization-msaa-sample-count=8 --content-image-texture-target=3553 --video-image-texture-target=3553 --channel=4687.21.1463192446
xiashishi       79823   0.0  0.0  2423376    240 s000  R+   11:10PM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn 79779

sorry, I don't know much   about   `ps aus | grep`.

**Comment by bpasero** [comment]
@xsstomy does it reproduce if you disable the git integration in settings?

`git.enabled: false`

**Comment by xsstomy** [comment]
@bpasero it doesn't reproduce after that  i set  `git.enabled: false`

**Comment by xsstomy** [comment]
thanks

**Comment by joaomoreno** [comment]
How many changes do you have in your git repository?

**Comment by xsstomy** [comment]
@joaomoreno 
There are many files，I do not know the specific number
![2](https://cloud.githubusercontent.com/assets/8943787/15527960/f9884fc6-2271-11e6-8f2b-3cf71ec48ed9.png)


all files in the picture

**Comment by joaomoreno** [comment]
Open a Terminal on your empty folder. Run `git status | wc -l`, which will tell you approximately how many changes there are in your git repository.

**Comment by xsstomy** [comment]
@joaomoreno 5998
![3](https://cloud.githubusercontent.com/assets/8943787/15575995/311f9ab8-2388-11e6-8567-2a260343194d.png)
sorry for that i do not answer timely

**Comment by joaomoreno** [comment]
Why are you working on a repository that has 5998 pending changes? You must either commit them more often or work outside of a git repository.
