### ISSUE TITLE
Add default integrated terminal cwd when no workspace is open

### ISSUE THREAD

**Issue by dfoverdx** [microsoft/vscode#61264]
Currently `terminal.integrated.cwd`, if specified, *always* opens new terminals to that the specified path.  I would like a setting that opens to the specified path *only if* no workspace is open.

When I start a new project, I open vscode, press <kbd>ctrl</kbd>+<kbd>\`</kbd>, `cd /e/src`, create a new folder for my project, open that folder in vscode, and create a new workspace there.  When I don't have a workspace open, I never open a terminal to anywhere but `/e/src`, and when I do have a workspace open, I always want to open terminals at `${workspaceFolder}`.  AFAIK, currently there is no way to distinguish between these two cases with the current settings behavior.  I also thought to change my `.bashrc` to set the default working directory, but the script runs after the working dir is set by vscode.

**Comment by Tyriar** [comment]
No plans to add this due to how niche it is. You can probably set this up though using `$TERM_PROGRAM` to detect a VS Code terminal and have a whitelist of paths or something.
