### ISSUE TITLE
macOS: Unable to update VSCode via update service.

### ISSUE THREAD

**Issue by dlo83** [Microsoft/vscode#61265]
- VSCode Version: 1.28.1 
- OS Version: macOS 10.13.6

Steps to Reproduce:

1. Launch VSCode
2. Check for updates
3. Observe the following toast:
<img width="386" alt="screen shot 2018-10-18 at 1 23 53 pm" src="https://user-images.githubusercontent.com/1965272/47182125-85d70e80-d2d9-11e8-830b-fe629c704a42.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Can you fully close Code and then run with `code --verbose` and attempt to get an update? There should be some error output in the terminal.

**Comment by dlo83** [comment]
Hi @joaomoreno , sure:

```
main 1:47:38 PM] windowsService#getRecentlyOpened 1
[82057:1023/134738.178840:INFO:CONSOLE(1408)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1408)
[main 1:47:38 PM] update#setState downloading
[main 1:47:38 PM] UpdateService error: Could not create temporary directory: Permission denied
[main 1:47:38 PM] update#setState idle
[82057:1023/134738.871132:INFO:CONSOLE(1408)] "%cTRACE", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (1408)
```

That was the only error that came up in the logs.

**Comment by aldeed** [comment]
Same issue since updating to 1.28.0. It looks similar to https://github.com/Microsoft/vscode/issues/7426#issuecomment-277737150 but the fixes there don't work. It would be helpful if the error message stated where it's trying to create a temp dir so that we can fix permissions.

**Comment by dlo83** [comment]
@aldeed -- that's exactly how I got here.  Came from that ticket, tried to apply the fixes recommended, no luck.

**Comment by joaomoreno** [comment]
Does your user have permissions to write to `$TMPDIR`?

**Comment by aldeed** [comment]
$TMPDIR
```
drwx------  142 eric  staff  4544 Oct 25 09:37 /var/folders/6t/9gklckns55q55y2w1vzjv2qh0000gn/T/
```

~/Library/Caches/com.microsoft.VSCode.ShipIt
```
drwxr--r--  2 root  staff  64 Jul 17 14:52 /Users/eric/Library/Caches/com.microsoft.VSCode.ShipIt
```

And `touch $TMPDIR/test` works as my user.

**Comment by aldeed** [comment]
Oh, thanks @joaomoreno that made the problem clear. I have now resolved this. The problem is that the fix in https://github.com/Microsoft/vscode/issues/7426#issuecomment-277737150 is:

```
sudo chown $USER ~/Library/Caches/com.microsoft.VSCode.ShipIt/*
```

But that didn't work for me. I needed to do:

```
sudo chown $USER ~/Library/Caches/com.microsoft.VSCode.ShipIt
```

No `/*` at the end

**Comment by joaomoreno** [comment]
Excellent, great to know. I've updated the comment.

**Comment by dlo83** [comment]
That fixed it for me as well. Thanks!

**Comment by JediYozh** [comment]
@aldeed Thanks, for me too!
