### ISSUE TITLE
When renaming a file, rename it using git if in a repository

### ISSUE THREAD

**Issue by stereokai** [Microsoft/vscode#6127]
- VSCode Version: 1.0.0
- OS Version: OS X El Capitan

Steps to Reproduce:
1. Rename a file via the sidebar

Expected result:
- Git registers the rename (ie. when using `git mv`)

Actual result:
- Git doesn't recognize the operation as a rename, but rather thinks the file with the old name was deleted, and the renamed file appears untracked.

**Comment by bpasero** [comment]
@stereokai not if you stage the change though, right?

**Comment by stereokai** [comment]
@bpasero Well, if you `git mv` any file, it gets staged consequently. Is that what you mean?

This behavior is present in WebStorm by default, for example.

**Comment by bpasero** [comment]
@stereokai yeah so git typically is smart enough to detect a rename even if you do it from the file system as soon as you stage the change. Otherwise any 3rd party tool that is not aware of git would not cause a git mv in the end.

**Comment by stereokai** [comment]
@bpasero Well, as I described, unfortunately with VSCode git doesn't recognize a rename

**Comment by bpasero** [comment]
@stereokai makes sense, I think this only happens though if the 2 files have so many changes that git does not recognize they are the same.

**Comment by stereokai** [comment]
No changes, only rename

Try for yourself :)

**Comment by barrymay** [comment]
+1 on this - would be really helpful!

**Comment by lironess** [comment]
Is someone working on it ?

**Comment by sharwell** [comment]
I am strongly opposed to the IDE making any implicit changes to the staging area of my git repositories (i.e. the index). I frequently use it as a scratchpad that I compare against, and when an IDE makes changes to it in the background I have lost work, incorrectly committed files, and/or been unable to correctly review my local progress. Three operations in an IDE which I expect to be able to complete without affecting the staging area of a Git repository are:

1. Deleting a file in the Explorer view (or equivalent in other IDEs)
2. Renaming a file in the Explorer view
3. Adding a file in the Explorer view

**Comment by rodison** [comment]
The same problem to me. VSCode version: 1.11.2. Windows 10

**Comment by radziksh** [comment]
I have the same problem. VSCode version: 1.11.2. Windows 10

**Comment by radziksh** [comment]
@stereokai @rodison @lironess I had the same problem until I realized that the git does not erase the history of the changes anyway, no matter that the file is shown as deleted and created again. [The history of changes will not be lost](http://stackoverflow.com/questions/7938582/how-does-git-detect-similar-files-for-its-rename-detection). So there is no more problem for me.

**Comment by stereokai** [comment]
@radziksh Thanks for that link. It actually makes it clear the `git mv` does nothing special, and it's all in the hands of Git to be aware of file renames. Thanks!
