### ISSUE TITLE
provide suggestions on what to exclude when vscode requests to exclude some code

### ISSUE THREAD

**Issue by capaj** [Microsoft/vscode#61270]
I just spent considerable amount of time using vscode on our project without a ts language server help. Why?
It started showing me the prompt to exclude folders-like in this closed issue:
https://github.com/Microsoft/vscode/issues/9594

I tried excluding node_modules and since it's a monorepo, I tried to explicitly exclude all of them by listing every single one. Didn't help.

So thankfully some people in the thread suggested that I should just exclude my build folders. I reluctantly tried it, but since any activity in the thread is locked-even emojis, I didn't know if it would work or not.
It did in the end, but it would be great if vscode could provide some information about what it considers too big code file/folder. Like what is too big? 1MB? 2MB? 5MB? Ideally it could provide a list of suggestions -maybe like all the files/folder crossing the limit.

That would be great, thanks!

**Comment by mjbvz** [comment]
Can you please share more information about your project structure?

- Typescript or javascript?
- Did you have a jsconfig or tsconfig to start with?
- Approximate size of your build folders, both number of files and file size?

Automatically figuring out when a bad folder is included in a project is hard, and if we knew this we wouldn't probably try including them in the first place. Maybe show a list of all included files instead?
