### ISSUE TITLE
New linux nvidia 410.66 drivers cause flickering on Linux VSCode

### ISSUE THREAD

**Issue by masonk** [Microsoft/vscode#61271]
This might be a completely upstream issue to this project, but this bug might be a useful reference for those with a similar issue, or for collecting workarounds.

- VSCode Version: 1.28.1
- OS Version: Ubuntu 18.04 LTS
- Geforce 2080Ti

Upgrading to the the recently-released nvidia driver [410.66](https://www.nvidia.com/download/driverResults.aspx/138959/) produces severe flickering in embedded terminal windows.

410.57 was even worse, though, and caused frequent input lag and stuttering in VSCode (and Chrome as well - so it's probably Chromium).

Interestingly,  --disable-gpu doesn't seem to prevent the .66 flickering or the .57 stuttering.

For those coming here with a similar issue, 410.48 is still the best driver for my particular system, and you might have better luck with it too.

If any vscode dev wants to tackle this flickering issue, which is kind of a whackamole issue that's come up before with other linux nvidia driver releases, I am happy to try building a patched version from source & testing it on my system.

**Comment by Tyriar** [comment]
This should hopefully get fixed when we move to Electron 3 https://github.com/Microsoft/vscode/issues/52629. You can use this as a workaround in the meantime:

```
"terminal.integrated.rendererType": "dom"
```
