### ISSUE TITLE
Build: Fresh vscode repository clone fails building vscode-sqlite3

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#61274]
Issue Type: <b>Bug</b>

- A gyp build error started several days ago
- I can/could build checkouts before October 15 (right before work was done on vscode-sqlite3
- After yarn cache clean and git -gc failed to fix, tried fresh repository clone
- Same build  error building 
- I have made no changes to any of the tool dependencies, Node, Python, VS Community, yarn et cetera
- I am thinking there is possibly some dependency change I have not picked up?  Seems odd since a fresh repository has the same error

- Searched issues and found nothing relevant

- I can successfully build before the first commit below which was a commit adding logging for
   vscode-sqlite3 - @bpasero  any ideas?

October 15 fails
git checkout  2dcc9b085c5288e92fcc862f71f2dff4b03b4bc1 -b insiders-1.28.1-addlogging

October 15 works
git checkout  55b9f52f93c14f9ee17bc4cdf60c352322b88bfc -b grav

From the the log, the  following option for gyp is suspicious since I have VS Community 2017
if that's what it's referring to?
```
gyp info spawn args   'msvs_version=2015',
```

I don't know the build tools sufficiently to debug myself...

```TXT
Microsoft Windows [Version 10.0.17134.345]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Dev\VSC Dev\vc2\vscode>git clean -xfd
Removing node_modules/

C:\Dev\VSC Dev\vc2\vscode>git clean -xfd

C:\Dev\VSC Dev\vc2\vscode>yarn
yarn install v1.10.1
$ node build/npm/preinstall.js
[1/4] Resolving packages...
[2/4] Fetching packages...
info vscode-fsevents@0.3.9: The platform "win32" is incompatible with this module.
info "vscode-fsevents@0.3.9" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > gulp-tsb@2.0.5" has incorrect peer dependency "typescript@^2.0.10".
[4/4] Building fresh packages...
[8/16] ⠠ vscode-nsfw
[6/16] ⠠ node-pty
[7/16] ⠠ spdlog
[10/16] ⠐ vscode-sqlite3
error C:\Dev\VSC Dev\vc2\vscode\node_modules\vscode-sqlite3: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: C:\Dev\VSC Dev\vc2\vscode\node_modules\vscode-sqlite3
Output:
C:\Dev\VSC Dev\vc2\vscode\node_modules\vscode-sqlite3>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.12.0 | win32 | x64
gyp info spawn C:\ProgramData\Miniconda2\python.EXE
gyp info spawn args [ 'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Dev\\VSC Dev\\vc2\\vscode\\node_modules\\vscode-sqlite3\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Christopher\\.node-gyp\\iojs-2.0.11\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Christopher\\.node-gyp\\iojs-2.0.11',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Christopher\\.node-gyp\\iojs-2.0.11\\<(target_arch)\\iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Dev\\VSC Dev\\vc2\\vscode\\node_modules\\vscode-sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Dev\\VSC Dev\\vc2\\vscode\\node_modules\\vscode-sqlite3\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(67,5): error MSB8020: The build tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, please install v140 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then
selecting "Retarget solution". [C:\Dev\VSC Dev\vc2\vscode\node_modules\vscode-sqlite3\build\deps\action_before_build.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Dev\VSC Dev\vc2\vscode\node_modules\vscode-sqlite3
gyp ERR! node -v v8.12.0

```

VS Code version: Code - Insiders 1.29.0-insider (9e83209ed59a22df3d593735d04cc963396bb89e, 2018-10-18T05:17:36.900Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.87GB (20.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-snippet-pack|aka|0.1.5
Bookmarks|ale|9.1.0
pascal|ale|6.4.0
git-easy|bib|1.9.1
bracket-pair-colorizer|Coe|1.0.60
vscode-eslint|dba|1.6.1
gitlens|eam|8.5.6
tslint|eg2|1.0.40
git-project-manager|fel|1.7.1
file-icons|fil|1.0.16
vscode-npm|fkn|3.3.0
code-runner|for|0.9.4
macros|ged|1.2.1
innosetup|idl|1.2.0
csharpfixformat|Leo|0.0.76
start-git-bash|McC|1.2.1
python|ms-|2018.9.1
csharp|ms-|1.16.2
debugger-for-chrome|msj|4.10.2
vscode-icons|rob|7.27.0
git-add-remote|sam|0.0.2
code-settings-sync|Sha|3.2.0
vscode-hexdump|sle|1.7.0
gitblame|wad|2.4.4
JavaScriptSnippets|xab|1.7.1

(1 theme extensions excluded)

</details>

Build output:

```TXT
Microsoft Windows [Version 10.0.17134.345]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Dev\VSC Dev\vc2\vscode>git clean -xfd
Removing node_modules/

C:\Dev\VSC Dev\vc2\vscode>git clean -xfd

C:\Dev\VSC Dev\vc2\vscode>yarn
yarn install v1.10.1
$ node build/npm/preinstall.js
[1/4] Resolving packages...
[2/4] Fetching packages...
info vscode-fsevents@0.3.9: The platform "win32" is incompatible with this module.
info "vscode-fsevents@0.3.9" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > gulp-tsb@2.0.5" has incorrect peer dependency "typescript@^2.0.10".
[4/4] Building fresh packages...
[8/16] ⠠ vscode-nsfw
[6/16] ⠠ node-pty
[7/16] ⠠ spdlog
[10/16] ⠐ vscode-sqlite3
error C:\Dev\VSC Dev\vc2\vscode\node_modules\vscode-sqlite3: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: C:\Dev\VSC Dev\vc2\vscode\node_modules\vscode-sqlite3
Output:
C:\Dev\VSC Dev\vc2\vscode\node_modules\vscode-sqlite3>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.12.0 | win32 | x64
gyp info spawn C:\ProgramData\Miniconda2\python.EXE
gyp info spawn args [ 'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Dev\\VSC Dev\\vc2\\vscode\\node_modules\\vscode-sqlite3\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Christopher\\.node-gyp\\iojs-2.0.11\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Christopher\\.node-gyp\\iojs-2.0.11',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Christopher\\.node-gyp\\iojs-2.0.11\\<(target_arch)\\iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Dev\\VSC Dev\\vc2\\vscode\\node_modules\\vscode-sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Dev\\VSC Dev\\vc2\\vscode\\node_modules\\vscode-sqlite3\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(67,5): error MSB8020: The build tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, please install v140 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then
selecting "Retarget solution". [C:\Dev\VSC Dev\vc2\vscode\node_modules\vscode-sqlite3\build\deps\action_before_build.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Dev\VSC Dev\vc2\vscode\node_modules\vscode-sqlite3
gyp ERR! node -v v8.12.0

```

**Comment by bpasero** [comment]
@aeschli can you fill in the details what you did to get the 2015 build tools? We should then maybe also update https://github.com/Microsoft/vscode/wiki/How-to-Contribute

**Comment by aeschli** [comment]
I fixed it by installing the VS2015 build tools http://download.microsoft.com/download/5/F/7/5F7ACAEB-8363-451F-9425-68A90F98B238/visualcppbuildtools_full.exe (check the window 8 sdk)

That said it would be nicer if all that is needed are the [windows-build-tools](https://www.npmjs.com/package/windows-build-tools), like we had it before.
I just read that there's an setting on the build tools to install the 2015 compiler:
`yarn global add windows-build-tools --vs2015`

@cleidigh can you try that out? I'll try it out on Monday.

**Comment by cleidigh** [comment]
@aeschli 
@bpasero 
Thanks guys, I'm back up and building ( which is good considering how behind I am my October IssueAssignments ;-)

That said, I still had to wrestle a bit to get things building.  Short explanation: yarn solution failed.
I got an npm solution working.  I will clarify this weekend after a few more tests.

**Comment by GongT** [comment]
I used `yarn global add windows-build-tools`, and everything works well.    
**Today**, after I run `git clean -x`, `yarn install` cannot success again.    
It says `vscode-sqlite3` won't build, because `python` not able to run.

My python is installed by `windows-build-tools`, so it's not in PATH.     
After add `c:\user\me\.windows-build-tools\python27`, install success.

**Comment by GongT** [comment]
I used `yarn global add windows-build-tools`, and everything works well.    
**Today**, after I run `git clean -x`, `yarn install` cannot success again.    
It says `vscode-sqlite3` won't build, because `python` not able to run.

My python is installed by `windows-build-tools`, so it's not in PATH.     
After add `c:\user\me\.windows-build-tools\python27`, install success.

**Comment by GongT** [comment]
I used `yarn global add windows-build-tools`, and everything works well.    
**Today**, after I run `git clean -x`, `yarn install` cannot success again.    
It says `vscode-sqlite3` won't build, because `python` not able to run.

My python is installed by `windows-build-tools`, so it's not in PATH.     
After add `c:\user\me\.windows-build-tools\python27`, install success.

**Comment by bpasero** [comment]
I think @joaomoreno hit this too

**Comment by bpasero** [comment]
@cleidigh can you maybe see if https://github.com/nodejs/node-gyp/issues/633 helps for you?

**Comment by joaomoreno** [comment]
@bpasero My issue was on macOS, bad Python installation. A re installation of Python with Homebrew fixed it.

**Comment by cleidigh** [comment]
I think Python was tissue for @GongT , required pass environment variable.

My issue is that no variation on a yarn -based install works.  Installing with npm succeeds.
I'm still experimenting trying to find a conflict perhaps with the VS community 2017

**Comment by cleidigh** [comment]
@bpasero 
I tried to get back to the point where I had the Windows-build-tools disabled or uninstalled.  This would get me back to where I was with only VS 2017 commandline tools which was my original installation, working up to the point of your tweaks on vscode-sqlite3.  

Now I can still successfully compile when I don't think I should.  I investigated and it turns out I already have GYP_MSVS_VERSION=2015 set.  I think this happened when I successfully installed the tools with
npm install --global windows-build-tools --vs2015

See what I found in the tool repository:
![image](https://user-images.githubusercontent.com/25272315/47328217-3c225700-d63e-11e8-928d-07134113453a.png)


I'm guessing that I am only able to build because the VS 2017 tools are still installed and I found references that Microsoft now has  BOTH 2015 and 2017 build tools together.  Right now I'm in the position where things are working at the moment but I think I have installs that did not complete what were partially removed so now I don't know what's making things work.

I don't want to go down a rabbit hole, but I don't think my installation prior was out of the ordinary so still think at a minimum we may need some adjustment to the notes as you said.  I'm thinking I will have to completely uninstall VS to reproduce the steps.  

Do you want me to try to do that?

**Comment by bpasero** [comment]
I updated https://github.com/Microsoft/vscode/wiki/How-to-Contribute to indicate that you need to install [`windows-build-tools`](https://github.com/felixrieseberg/windows-build-tools) with the `--vs2015` option. Since `sqlite3` is explicitly asking for `VS2015`, I do not think we should encourage people to build with the 2017 version. Besides, this is not working currently anyways with `node-gyp` (see [here](https://github.com/nodejs/node-gyp/pull/1549)).

**Comment by cleidigh** [comment]
@bpasero 
sounds good
I will post issue on the Windows-build-tools rep to see if they have any responses on the install failure
using yarn.  I think that scenario come up for others.

**Comment by avannaldas** [comment]
@bpasero I've added setup troubleshooting section in my forked version of [How-to-Contribute.md](https://github.com/avannaldas/vscode-wiki/blob/master/How-to-Contribute.md#troubleshooting-steps). Lists solutions to issues I bumped into while setting up vscode for the first time. Please let me know if it helps to update __How-to-Contribute.md__, I'll raise a PR.
