### ISSUE TITLE
comparing tool gives wrong result for large files

### ISSUE THREAD

**Issue by zchrissirhcz** [microsoft/vscode#61289]
- VSCode Version: 1.28.1
- OS Version: Windows 10

Steps to Reproduce:

1. Prepare one text file, say 14741KB large. Name it as "log1.txt". Each line of log1.txt may be like this:
```
	i=1, 0.000000*1.000000+0.000000=0.000000
```

2. Copy log1.txt to log2.txt, and change some lines of log2.txt to be diffirent than log1.txt's;

3. Putting log1.txt and log2.txt under same directory, say "log_cmp";

4. Using VSCode open "log_cmp" folder, and compare these two files

Does this issue occur when all extensions are disabled?: Didn't try that

Screenshot:
![image](https://user-images.githubusercontent.com/3831847/47201490-a58b3700-d3ac-11e8-921c-e2a28e0d0d3a.png)

![image](https://user-images.githubusercontent.com/3831847/47201534-c8b5e680-d3ac-11e8-886b-124929dceab0.png)

**Note**
If I decrease the compared files to only contain 5000 lines, the comparing tool works correctly.

**Comment by alexandrudima** [comment]
The diffing algorithm is implemented to be time sensitive. If computing the diff takes longer than 5 seconds, then the returned result is a valid diff, but is not very precise.
