### ISSUE TITLE
Code folding: I cannot collapse functions, or other code blocks.

### ISSUE THREAD

**Issue by brunoscopelliti** [Microsoft/vscode#61284]
- VSCode Version: 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850) I can replicate the issue with insiders too.
- OS Version: macOS High Sierra

Steps to Reproduce:

1. Open a JavaScript file.
2. Try to collapse some function.

Expected: The block of code is collapsed to one line.

Actual: The block remains uncollapsed.

![bug](https://user-images.githubusercontent.com/3489757/47198877-009e3900-d36f-11e8-9b29-5d9bb44eb82b.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
In the status bar, it says `initializing js/ts language features`. If you wait until this is completed, can you collapse the blocks?

**Comment by brunoscopelliti** [comment]
I cannot reproduce the issue anymore.
This is strange, because a couple of days ago it was very easy to reproduce, with any javascript file.

> In the status bar, it says initializing js/ts language features.

Yep, I noticed that as well. The problem was that it displayed that message indefinitely.
I had reproduced the same problem also with vscode insiders, that I had just installed.

**Comment by mjbvz** [comment]
Ok, let me know if you see this again. Closing for now.

It it does happen again, please check the TypeScript Server trace:

1. Set `"typescript.tsserver.trace": "verbose"`
1. Reproduce the problem
1. Open the output panel and view the `TypeScript` section

Look to see if there any errors or stack traces printed in the trace
