### ISSUE TITLE
Redo is not focusing active cursor

### ISSUE THREAD

**Issue by workspace-mayur** [Microsoft/vscode#61283]
Issue Type: <b>Bug</b>

If I try to redo something in code then it doesn't scroll up to undoed line.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (1.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.0.22
php-debug|fel|1.12.6
php-pack|fel|1.0.2
beautify|Hoo|1.4.6
theme-monokai-pro-vscode|mon|1.1.8
vscode-apache|mrm|1.1.1
vsnotes|pat|0.6.0
format-html-in-php|rif|1.3.8
code-settings-sync|Sha|3.2.0

(1 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment]
@workspace-mayur  I cannot reproduce:

Here I am typing a character, then running undo and then running redo.

![kapture 2018-10-23 at 15 39 35](https://user-images.githubusercontent.com/5047891/47364552-e4392e00-d6d9-11e8-949c-bc2bee8db628.gif)

**Comment by workspace-mayur** [comment]
Hello There, Sorry I didn't noticed your request for more information.

I'm facing this issue in Windows 10 OS (pro). My colleague is using mac and it works in his system but it doesn't work in my system.

**Comment by workspace-mayur** [comment]
Alright, somehow it's working now. Maybe they fixed this issue in the latest update or some extension might be causing this issue.
