### ISSUE TITLE
go.gopath is set in settings.json but $GOPATH is not defined in the terminal

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/vscode#61287]
I have this in `.vscode/settings.json`:

```json
{
   "go.gopath":"/Users/oleg/codes/huru"
}
```

and after I reopen vscode, I open a new terminal but $GOPATH is not defined in the terminal. I was hoping that vscode would pick up the env var from settings.json and it would be set in the terminal, something like this:

```
export GOPATH="muhSettingsJSONValue:$GOPATH"
```

**Comment by ORESoftware** [comment]
I tried this too:

```json
{
    "go.gopath": "/Users/oleg/codes/huru",
    "terminal.integrated.env.linux": {
        "GOPATH": "${go.gopath}"
    }
}
```

still didn't work, fml

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/46696
