### ISSUE TITLE
Cannot carry out secondary development

### ISSUE THREAD

**Issue by chnliquan** [Microsoft/vscode#61281]
- VSCode Version: 1.28.0
- OS Version: macos 10.3.3

I want to add some new features to the existing view outline, such as deleting a function, whether it can be redeveloped on the current basis, if there is no secondary development, if there is an api, an abstract syntax tree can be generated based on the current file.

![image](https://user-images.githubusercontent.com/34906299/47195509-cf356580-d38e-11e8-8f11-102a3cffb54f.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
Sorry, but I don't understand this
