### ISSUE TITLE
"files to include" for named workspace folder doesn't work with slashes in name

### ISSUE THREAD

**Issue by MarekLew** [microsoft/vscode#61297]
Issue Type: <b>Bug</b>

Where I use option `find in folder` in multi root project, path to folder started with folders. Path with worksace folder name(not path to this folder)  then when I  named folder(not path) `serwer/proj1` then search not find: 
`No folder in workspace with name: serwer `
because this path not exist. **You mixed path and name of folders.**

Please add `${workspaceFolder:folder}` opction in `file to include` input.

Example (file to include):
 ./`${workspaceFolder:serwer/proj1}`

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz (4 x 3293)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.68GB (2.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by MarekLew** [comment]
Note: when I write "folder name" then I think "workspace folder name" ex. {..."name":"folder/name" ...}

**Comment by axetroy** [comment]
same issue
In fact my workspace name is like this
![2019-02-09 23 41 59](https://user-images.githubusercontent.com/9758711/52522745-5737d600-2cc4-11e9-9f02-eb05c00ae8ee.png)
In order to better distinguish the project, I used the extension to rename the workspace, and the name of the file directory has not changed.
