### ISSUE TITLE
Copy and paste vertically

### ISSUE THREAD

**Issue by azbo** [microsoft/vscode#61295]
- VSCode Version:1.28.2

Steps to Reproduce:

1.copy
![image](https://user-images.githubusercontent.com/5110699/47201786-a2dd1180-d3ad-11e8-9671-2744b4d5ea26.png)

2.Paste
The first：
![image](https://user-images.githubusercontent.com/5110699/47201845-d750cd80-d3ad-11e8-9b8f-f9282c29d945.png)
Single cursor
![image](https://user-images.githubusercontent.com/5110699/47201869-f3546f00-d3ad-11e8-8fb4-5a4173cccbc5.png)

The Second：
![image](https://user-images.githubusercontent.com/5110699/47201889-fea79a80-d3ad-11e8-9bf7-15aa7911b01d.png)
Multiple cursors
![image](https://user-images.githubusercontent.com/5110699/47201909-0ff0a700-d3ae-11e8-93c7-179fff6b9136.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexandrudima** [comment]
Let's track in #80624
