### ISSUE TITLE
Custom title bar moves by one pixel if 2nd screen (extended) is off

### ISSUE THREAD

**Issue by alexhmm** [microsoft/vscode#61290]
- VSCode Version: 1.28.2 (user setup)
- OS Version: Windows 10 Pro

Version: 1.28.2 (user setup)
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:23:51.859Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
Theme: Dark+ (default)

Steps to Reproduce:

1. Have 2 screens with extended view
2. Turn off the 2nd screen
3. While switching between tabs in vscode, custom title bar stutters for 1 pixel every time
4. If the 2nd screen is on, its not moving

Using the native bar style there is no movement having only the 1st screen enabled.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
@alexhmm can you verify with the latest insiders?

**Comment by alexhmm** [comment]
@sbatten It's still a thing with insiders v 1.31.0.

It only appears in full screen window mode. Having it "minimized" and pulling the window to fullscreen the 1 pixel movement isn't happening.

**Comment by sbatten** [comment]
@alexhmm can you clarify what you mean by having the second screen off? also, if you could provide a gif of your experience, that would be awesome.

**Comment by alexhmm** [comment]
@sbatten

My computer has two monitors connected:
1st via HDMI (Dell),
2nd via DVI (Ilyama)

The strange thing is, the problem doesnt get recorded with VLC player, so i recorded two smartphone videos:
https://streamable.com/fokkv (Fullscreen, problem occurs, vscode moves for 1 pixel after every click)
https://streamable.com/v644i (Small, problem doesnt occur)

If i have turned off the 2nd monitor the problem occurs in vscode. For sure its not a monitor problem, because i had the problem with two different monitors before. 

It only affects vscode in custom bar style mode. I dont have similar problems with other software.

Hopefully this helps.

**Comment by sbatten** [comment]
@alexhmm is your 2nd monitor still detected by Windows. (i.e. Can you still move windows to that screen?)

**Comment by alexhmm** [comment]
@sbatten Nope.

At "Multiple Displays / Monitors" I have the option "only show on 1" enabled (I dont know the correct english notation - german windows version).
The problem only occurs with "only show on 1". If I change it to "expand" the problem doesn't occur.
