### ISSUE TITLE
Phantom build error when dbset name changed

### ISSUE THREAD

**Issue by yogiderek** [Microsoft/vscode#6129]
- VSCode Version:1.1.0-insider
- OS Version: 10.0.10586

Steps to Reproduce:

1. In my DbContext derived class, I replaced,
 	```public virtual DbSet<NewsItem> NewsItem { get; set; }``` by
 	```public virtual DbSet<NewsItem> NewsItems { get; set; }``` 

2. In HomeController.cs I replaced
```
	    public IActionResult Index()
		{
			return View(_db.NewsItem);
		}
```
by
```
		public IActionResult Index()
		{
			return View(_db.NewsItems);
		}
```
3  Save all files and click debug to build and run. The following error is detected during preLaunchTask 'build'

'xxxxxContext' does not contain a definition for 'NewsItems' and no extension method .......

4  Close down and reopen project
5  Click debug and application builds and runs ok. Error??? is no longer detected by vscode

**Comment by bpasero** [comment]
I am very sorry to hear you are having issues with VS Code. Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
