### ISSUE TITLE
Not autocomplete (even Ctrl+Space) with cordova/ionic project?

### ISSUE THREAD

**Issue by nampdn** [Microsoft/vscode#613]
I'm trying to use VS Code with IONIC project, it doesn't hint me any function inside angular component like controller, factory, etc... I think the IDE is not index the javascript file when I open the folder. Some global variable is not recognized inside angular controller/factory as well.

**Comment by egamma** [comment]
You need to add .d.ts files. See this blog post http://blogs.msdn.com/b/vscode/archive/2015/06/05/mobile-hybrid-apps-with-vs-code-and-ionic.aspx

**Comment by nampdn** [comment]
I added the .d.ts file. But some global variable in javascript still unknow between js files.
For example:
In app.js:
```javascript
    var jc = {a: "value"}
```

In controller.js:
```javascript
    console.log(jc.a); //This will ignore the variable jc
```
