### ISSUE TITLE
Double click slowly in the file list to rename the file

### ISSUE THREAD

**Issue by YamiOdymel** [microsoft/vscode#61300]
The idea of this feature is to able to rename a file when you **double click slowly** the file in the file list.

![image](https://user-images.githubusercontent.com/7308718/47207067-decba300-d3bc-11e8-8604-7c87ea080c56.png)

This has been implemented in the Windows Explorer. If you double click a file slowly, you can rename the file instead of `Right click > Rename` or press `F2`.

![image](https://user-images.githubusercontent.com/7308718/47207172-218d7b00-d3bd-11e8-89a8-77d6054138a8.png)

---

![image](https://user-images.githubusercontent.com/7308718/47207691-75e52a80-d3be-11e8-89a5-c6fb995a38b2.png)

**Comment by isidorn** [comment]
Thanks for the suggestion. However this is very windows specific behavior thus we are worried about adding it to our cross platform explorer
Leaving this open as a feature request

**Comment by YamiOdymel** [comment]
A _very windows specific behavior_ (or user experience) ? 

You can rename the file by clicking the file name in macOS with the Finder (but I forget if it's a _single click and wait_ or _double click slowly_), it's kinda the same idea.

**Comment by isidorn** [comment]
I can not get Finder to rename a file by double click / for both slow and fast. It renames on enter

**Comment by Karlito88** [comment]
Click on a file and push F2 is the better way for renaming. So you don't open a file by mistake (click to fast)

**Comment by PizzaPartyInc** [comment]
As a person who switched from VS 2017 to VS Code - I'm really missing this feature. 
I think it would be great to have an option to enable it in VS Code and have it in disabled state by default, if there is a concern that the functionality itself might be confusing for people who are not used to it.

**Comment by Karlito88** [comment]
Think the problem stays with the simple renaming per double click and F2 - imports are not changing.
