### ISSUE TITLE
No warning on reformattting tool failing to reformat the document

### ISSUE THREAD

**Issue by mrkafk** [Microsoft/vscode#61308]
- VSCode Version: 1.28.2
- OS Version: Debian 9.5 amd64

Steps to Reproduce:

1. Install current Python extension (Oct 2018)
2. Create virtualenv with Python 3.6, enable it in workspace root
3. Install "black" formatter for Python, enable it in settings
3. Open python program written in Python 2 dialect
4. Right-click, select "Format Document"

Actual result:

Nothing happens.

Expected result: 

Get warning that formatter cannot format this file.

Root cause:

```
(ve) user@host ~/projects/shed_utils % black /home/user/projects/shed_utils/shed_utils/logins_to_ans_hosts.py
error: cannot format /home/user/projects/shed_utils/shed_utils/logins_to_ans_hosts.py: cannot use --safe with this file; failed to parse source file with Python 3.6's builtin AST. Re-run with --fast or stop using deprecated Python 2 syntax. AST error message: Missing parentheses in call to 'print'. Did you mean print('Ctrl-C pressed. Aborting.')? (<unknown>, line 93)
All done! 💥 💔 💥
1 file failed to reformat.
```

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-python/
