### ISSUE TITLE
Texteditor Mode versus IDE (optional master workdir)

### ISSUE THREAD

**Issue by flddr** [Microsoft/vscode#61301]
Hi,

sorry, i did not found anything in issues because i do not know the correct wording.

#### My problem

**VS Code** is my main _IDE_, _editor_, _daily-helper_ and i am working mostly in one workspace for longer time. **But**, if i closed _VS Code_ and do not work on a project **and then open a single file** like `somewhat.txt` via explorer-context-menu `Open with Code`, then **this resets my workdir**. I must _choose_ **open folder** every time after that.

I do not like this, i just want to open _some_ files without affecting my main workdir.

Lastly it's the same to _quick open_ a project just to test somewhat. When i close this project and restart _VS Code_, i want to restart in my **master workdir**.

I would like to have a `setting` for this or any option to prefer this dir if VS Code starts "emtpy" and _if set master workdir_ it should stay (if VS Code is closed and i just open something that has no `.vscode` folder). The `.vscode` folder project can be active as long i do not _close_ it. But _after close_ **and restart / start** i want to start in my _master workdir_

Thanks for reading 😊

**Comment by Tyriar** [comment]
You should be able to accomplish this with the existing settings. Check out this one in particular:

![image](https://user-images.githubusercontent.com/2193314/47324214-cd300880-d613-11e8-9fcf-fc82cda23a05.png)

**Comment by flddr** [comment]
@Tyriar 

This is **`not`** what i have issued 😕 

If you do this:

1) Set those settings
2) Load your workspace
3) work in your workspace
4) **close** VS Code

**_... do other things_**

5) watch a file with context menu `Open with Code` (or open temporarily a _folder_ in VS Code)

#### **`from now on there is no workspace anymore`**.

**_Neither_** in this new opened window nor in **closed VS Code**.

Thats why i have requested a **master workdir**: **_if set_** it will be reopened as long it isn't closed via **VS Code menu** close project/folder _whatever in correct translation_ or maybe **_close master_**...

I reload my workdir since initial realease of VS Code daily 😖 (On those days were i close VS Code because work is done this day)

**Comment by flddr** [comment]
> Thanks for creating this issue! We figured it's covering the same as another one we already have.

?

**Comment by flddr** [comment]
@bpasero please can you give me the duplicate? Thanks.
