### ISSUE TITLE
display wrong

### ISSUE THREAD

**Issue by jokervTv** [Microsoft/vscode#61307]
Issue Type: <b>Bug</b>

hello,

I'm new here. There is something wrong. And closing all extensions is not help it.

![image](https://user-images.githubusercontent.com/29646575/47214158-aa151700-d3cf-11e8-9cb8-6ce452aa770f.png)

thanks.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (10.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
simple-timer|bur|1.0.1
bracket-pair-colorizer|Coe|1.0.60
vscode-markdownlint|Dav|0.20.0
code-runner|for|0.9.4
fortran|Gim|0.2.0
matlab|Gim|0.9.0
beautify|Hoo|1.4.6
latex-workshop|Jam|5.13.0
vscode-language-pack-zh-hans|MS-|1.28.2
python|ms-|2018.9.1
cpptools|ms-|0.19.0
zoombar-vscode|wra|1.1.0
ncl|yue|1.3.0

</details>

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/59682
