### ISSUE TITLE
Not opening 

### ISSUE THREAD

**Issue by Harshsngh07** [Microsoft/vscode#61302]
We have written the needed data into your 
Issue Type: <b>Bug</b>

My vscode doesn't open when I'm offline but it starts to open when I'm online
please guys fix this.I'm also attaching the error it shows while running it via cmd.

dns.js:246
    this._handle = new ChannelWrap();
                   ^

Error: EFILE
    at new Resolver (dns.js:246:20)
    at dns.js:377:25
    at dns.js:431:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at net.js:45:13
    at net.js:1730:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at internal/child_process.js:6:13

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3217U CPU @ 1.80GHz (4 x 1796)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.89GB (1.16GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
code-gnu-global|aus|0.2.2
bracket-pair-colorizer|Coe|1.0.60
angular2-snippets|dan|1.0.20
vscode-html-css|ecm|0.2.0
vscode-great-icons|emm|2.1.44
vsc-material-theme|Equ|2.4.2
Angular-BeastCode|Mik|7.0.2
python|ms-|2018.9.1
cpptools|ms-|0.19.1-insiders2
debugger-for-chrome|msj|4.10.2
material-icon-theme|PKi|3.6.0
LiveServer|rit|5.1.1
vscode-icons|rob|7.27.0
quokka-vscode|Wal|1.0.156
html-css-class-completion|Zig|1.17.1

(1 theme extensions excluded)

</details>
clipboard because it was too large to send. Please paste.

**Comment by Harshsngh07** [comment]
PLease give me a fix.I'm fed up with this issue.

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/7570
