### ISSUE TITLE
TreeItem should support highlights

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#61313]
It would be nice if the tree view supports some kind of highlights in its label. This would be helpful when showing search-result-like things. Maybe something like this

```
export class TreeItem {

  label?: string;

  // start, end tuples
  labelHighlights?:[number,number][]
}
```

or something more elaborated that allows to reference a theme color or allows to express the highlighting style (background color or bold text etc)

**Comment by sandy081** [comment]
@jrieken How about

```typescript
export class TreeItem {

  label?: string || {label: string, highlights?:[number,number][]};

}
```

This will avoid providing highlights without giving label.

**Comment by alexr00** [comment]
This is already done now!
