### ISSUE TITLE
C# not coloring syntax

### ISSUE THREAD

**Issue by Zalatos** [Microsoft/vscode#6131]
- VSCode Version:1.0.0
- OS Version: windows 10

Steps to Reproduce:

I've had Visual studio code installed since open beta. got several updates as time went along
1. Opened a csharp file and there was an update since i hadn't used VSCode in a few weeks. updated because the update notes said something C# now supported.
2. text appears plain as if a txt file.
3. installed C# extension through ext install then selected the first C# that popped up (C# for visual studio code (powered by omnisharp) )
4. text still white

**Comment by bpasero** [comment]
@Zalatos can you check if you have errors for extensions reported (bottom left corner in the status bar) and can you check bottom right in the languages indicator if C# shows up for the file you open? can you attach a screenshot?

**Comment by jrieken** [comment]
@Zalatos ping

**Comment by Zalatos** [comment]
Ah sorry about that.

finally got round to it today.

Thanks for the info on the information buzzer on the bottom left.

I had assumed the extension was already installed since i couldnt find any progress bar and such.

Left it open to run the installation and it installed successfully. it seems I finished making my edits and opened a new window with a new file or gave up and went to normal VS before I let it finish installing.



Does the installation stop if other VSCode windows are open but the one that initiated the install is closed?

**Comment by jrieken** [comment]
> Does the installation stop if other VSCode windows are open but the one that initiated the install is closed?

Should continue, but @joaomoreno knows for sure

**Comment by joaomoreno** [comment]
It doesn't no.

**Comment by Zalatos** [comment]
@joaomoreno thanks for the update
