### ISSUE TITLE
Tree view should support a default message 

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#61312]
It would be nice if the tree view API supports some kind of placeholder text. Already, today the container shows a message while the extension is loading/activating and I would like to piggy back on that. Something like this

```ts
export interface TreeView<T> extends Disposable {
  message?: string | MarkdownString
}
```

**Comment by sandy081** [comment]
@jrieken I suppose this is not initial message and is shown whenever the tree is empty?

**Comment by jrieken** [comment]
Yeah, it's the empty message and it should help to explain how to populate the tree

**Comment by sandy081** [comment]
@jrieken Any scenarios for setting a markdown as message?

**Comment by sandy081** [comment]
@jrieken Any scenarios for setting a markdown as message?

**Comment by eamodio** [comment]
This is what one of the empty states looks like in the upcoming GitLens 9:

![image](https://user-images.githubusercontent.com/641685/48567504-2ade0a80-e8cb-11e8-9540-53903b01930a.png)

Although I will I will probably stick with what I am currently doing for now -- since they are currently click-able

**Comment by sandy081** [comment]
@eamodio Supporting markdown in the message will allow you to provide links.. Will this help you in moving to messages?

**Comment by sandy081** [comment]
@jrieken Tree view supports now showing a message. Added the api to proposed section.

**Comment by eamodio** [comment]
@sandy081 yeah I think links could definitely work. Thanks!

**Comment by sandy081** [comment]
@jrieken Would like to promote to public API if there are no concerns?

**Comment by jrieken** [comment]
Yeah, go for it

**Comment by sandy081** [comment]
Reverted to proposed due to the UX issues markdown string brings in

**Comment by sandy081** [comment]
I kinda see the issues Markdown string can bring in to our UI. Extensions could abuse the tree view by making it a markdown view with links, lists, table etc., Main reason to allow markdown string is to support some simple links to populate the view. We cannot tradeoff this with the feature set the Markdown string brings into the Tree view. 

I would rather do what @bpasero does in the notifications API for supporting links in the message. I can introduce the empty view button concept in future if needed.

**Comment by jrieken** [comment]
Just to clarify this: we don't support tables.

**Comment by bpasero** [comment]
+1 for only allowing links in the message, but nothing else, same as what notifications do today.

**Comment by jrieken** [comment]
-1 I think that's too restrictive. We should just allow plain text then and have support for those monster buttons the explorer adds. Tho, again I see great value in supporting markdown and we do support them in many places already. We can tweak the feature set (maybe no bold, italics, and tables) but markdown with just links is not markdown and it will need a new type in the API to express that.

**Comment by bpasero** [comment]
Having just text and support for the button is perfectly fine for me, I prefer that over text with links but I am not sure that helps GitLens for example.

**Comment by jrieken** [comment]
question remains: how do I build a ref-search history with that?

**Comment by bpasero** [comment]
The button has to be a control that you can click to expand to previous searches I guess, similar to this control:

![image](https://user-images.githubusercontent.com/900690/49220297-23902400-f3d6-11e8-8c76-5bf35f7d0513.png)

**Comment by sandy081** [comment]
Closing this as we decided to go for proposed only in this milestone.
