### ISSUE TITLE
JS inetellisense doesn't work for prototype extensions for js-native-types

### ISSUE THREAD

**Issue by Yegorich555** [Microsoft/vscode#61315]
- VSCode Version: 1.28.2
- OS Version: Window 10 x64
- All extensions disabled

Steps to Reproduce:
```
 Array.prototype.test = function() {
    return 'ok';
}

var arr = [];
arr.te - I want to see function 'test' in intellisense
```
![image](https://user-images.githubusercontent.com/25006810/47218661-35cd7a00-d3b5-11e8-81cc-97439c61747f.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#28064
