### ISSUE TITLE
Native support for Vue files

### ISSUE THREAD

**Issue by ffxsam** [Microsoft/vscode#61318]
I know that support for .vue files is possible via the Vetur extension, but I (as well as many others) have been struggling with some of Vetur's [performance issues](https://github.com/vuejs/vetur/issues/784) lately. As someone who works in Vue daily, it's incredibly frustrating, and I think it would be ideal for VS Code to have native Vue support. 

It's my impression that the VSC team leaves it to third party developers to provide support for a file type when it's sort of "fringe." I think Vue is mainstream enough to warrant serious consideration for native support. This way, we would all benefit from more dedicated support when bugs arise.

**Comment by octoxan** [comment]
Would be nice, some other editors support it out of the box.

**Comment by ffxsam** [comment]
Just as a point of comparison, there are other, less popular formats natively supported by VS Code, such as Handlebars. Handlebars has 13.8k stars, whereas Vue has 117k stars.

**Comment by Tyriar** [comment]
Vetur is actually maintained by someone from the vscode team, so integrating it would be integrating Vetur which I'm not really a fan of (the vscode core should remain slim). I recommend creating an issue over on Vetur instead.

**Comment by octref** [comment]
This is probably related to TSServer. I don't have much time to dive into the perf issues, but planning to look into https://github.com/vuejs/vetur/issues/682 with @mjbvz so if a specific version of Vetur isn't causing problem for you, you can always locally install a TypeScript dependency and let Vetur use it.

**Comment by ffxsam** [comment]
Interesting, I didn't know you were part of the official VS Code team. Is there any way MS would allocate more folks to Vetur to help out, since you're pressed for time?
