### ISSUE TITLE
ALT Keyboard Shortcut no longer working

### ISSUE THREAD

**Issue by Sell24** [Microsoft/vscode#61328]
- VSCode Version: 1.28.1
- OS Version: Windows 10

I just updated to v1.28.1 last night and in previous versions of VS Code I had **ALT+F S** mapped to **"workbench.action.files.saveAll"**

In this version when I try and use that particular shortcut, it saves only the file in focus not any of the others  that needs saving.

If I change the keyboard shortcut to **CTRL+F S**, it works.

**Comment by sbatten** [comment]
`Alt+F S` is actually the mnemonic for `Save`. This behavior was broken before and is fixed so the behavior you are seeing is by design. If you wish to disable mnemonics so that you can specify your original shortcut, you may with `window.enableMenuBarMnemonics` => `false`

**Comment by sbatten** [comment]
@Sell24 Realized this was actually a regression and have fixed the issue

**Comment by Sell24** [comment]
I followed your instructions before and it works fine for what I need. So I appreciate the time to answer and to fix.
