### ISSUE TITLE
Extensions hang after long-running, can't read process tree

### ISSUE THREAD

**Issue by jphenow** [Microsoft/vscode#61324]
Issue Type: <b>Bug</b>

Had a twitter thread with Erich Gamma here: https://twitter.com/jphenow/status/1050780454822006785

My main workflow involves having 1-4 Code workspaces open. I'm relatively light on extensions I think - usually use typescript stuff, C#, some react tools, Spotify plugin (Not listed below because I _just_ tried disabling a moment ago [`shyykoserhiy.vscode-spotify`]).

After running things for a few days (sometimes less), the extensions clearly start giving out - "Loading" for intellisense, bottom bar starts losing statuses. At this point I try to view the process tree to no avail, and run `code --status` (this also hangs).

I can kill most `Code Helper`s but some just never close. I recently noticed, also, that there's ~75 `ps` processes running which seems awfully suspicious. `ps -A` also hangs. 

My difficulty with reproducing is mostly that it's over the course of a few days that it gives out. But once it gives out, my only resolution has been a hard restart because the hanging processes prevent a restart.

Any insight or next steps would be greatly appreciated!

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|-psn_0_489575112|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.1.0
vscode-mjml|att|1.5.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
ssh|chr|0.0.4
vscode-eslint|dba|1.6.1
gitlens|eam|8.5.6
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.40
vscode-great-icons|emm|2.1.44
testcafe-snippets|hdo|1.0.57
beautify|Hoo|1.4.6
csharpextensions|jch|1.3.0
docomment|k--|0.1.2
copy-github-url|mat|0.2.0
cpptools|ms-|0.19.0
csharp|ms-|1.16.2
mono-debug|ms-|0.15.8
PowerShell|ms-|1.9.0
vsliveshare|ms-|0.3.834
vscode-docker|Pet|0.3.1
gitlink|qez|0.4.5
testcafe-test-runner|rom|1.4.3
ayu|tea|0.16.0

(6 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment]
I think there are two issues here, one regarding leaking `ps` processes and one (not clear at this point) regarding slowdown of extensions

---

Regarding the leaking `ps` processes, I think both `code --status` and the process tree end up invoking `ps`. I really don't know why those would hang. Perhaps we should spawn `ps` and kill the process after a few seconds if no output is received? @bpasero 

---

Regarding the slowdown in IntelliSense, this is something difficult to track down without reproducible steps. What programming language are you using when the slowdown occurs? Is it C# or JavaScript? When you notice the slowdown, you can open Running Extensions `F1 > Developer: Show Running Extensions`. This should help in narrowing down which extensions are executing while the slowdown occurs. Can you attempt disabling non-mission-critical extensions for a while to see if perhaps one of those is generating the slow-down?

If you identify some reproducible steps, you can profile the extension host and identify which of the extensions is consuming a lot of CPU by following this guide [here](https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions)
