### ISSUE TITLE
be able to disable the 'This may be converted to an async function' tooltip

### ISSUE THREAD

**Issue by AlexGalays** [Microsoft/vscode#61326]
Can we have an option to specifically disable this "hint"? Not everyone find the async function style superior. I'm never going to use this refactoring so it just hinders the readability of my files compared to previous versions of vscode.

![image](https://user-images.githubusercontent.com/1375586/47225273-f6eff200-d3bd-11e8-8cf3-70e3bb373532.png)

**Comment by mjbvz** [comment]
Set `"javascript.suggestionActions.enabled": false` or `"typescript.suggestionActions.enabled": false` to disable these

**Comment by arenddeboer** [comment]
I also favour promises and simply disabling all suggestions feels rather heavy handed.

**Comment by AlexGalays** [comment]
yes, the granularity is too coarse here.

**Comment by joshburgess** [comment]
Many people don't find async/await to be superior in any way. This should be configurable on its own.

**Comment by trusktr** [comment]
Async is superior (IMO). :) But still, for a function that manually returns a promise but never uses the `await` keyword anywhere in it's body, this tip is pointless.

**Comment by andrewtw** [comment]
Totally agree with @trusktr.


Disable the `suggestionActions` is not the right way for us, since this option controls all diagnostics of JS/TS.

**Comment by AlexGalays** [comment]
> Async is superior (IMO). :)
> 
> But still, for a function that manually returns a promise but never uses the `await` keyword anywhere in it's body, this tip is pointless. There's absolutely no reason to convert a non-`await`-using function into an `async` function. This tip should only appear (as an error) if we try to use `await` in a non-`async` function.

Let's not make it a discussion about which style is superior; I just wanted to illustrate that not everyone like the async style more than the explicit Promise style with a personal example.
vscode should be and remain completely unbiased regarding coding practices.
