### ISSUE TITLE
Debug Toolbar Placement should be allowed to be moved to any edge.

### ISSUE THREAD

**Issue by palodequeso** [microsoft/vscode#61336]
Currently, when running the debugger, you are limited to placing the debug toolbar to the two top "UI rows", basically on top of your tabs or, your code, or your sidebar, but always on the top of the UI. I would simply like to be able to move this to the bottom where my debug console and terminal are, so that way I can make the toolbar cover less critical portions of the UI.

**Comment by isidorn** [comment]
Sorry accidentely closed it

**Comment by palodequeso** [comment]
No worries mate!

**Comment by ronnyek** [comment]
I vote having a REAL toolbar where you wouldn't necessarily NEED to move it around because it wouldnt be in the same space as document tabs etc.

**Comment by AlexanderHurst** [comment]
Just want to add my opinion and recommendation.
I code on a portrait mode monitor, so horizontal elements that are locked to the same level as other horizontal elements are a huge bummer. 
My horizontal space is already limited. Locking it to the tabs section is even worse as it only takes opening four tabs before it starts to cover up tabs at which point I have to move the toolbar two or three times to jump back and forth between tabs using the GUI. 
Docking the toolbar means i have to change my side panel to interface with it, and this takes up nearly 1/4 of my coding screen if I want to see the all the buttons on the debug bar.

If it were free floating it would feel infinitely better, if I want to drag it down (even if i want to drag it over other less essential UI) I want to drag it down. I want to put it where I want it. If we could opt to align the buttons vertically it would be even better for me. 
Finally adding these buttons in one four locations indicated with white boxes in the attached picture would be ideal for me.

Just please put it somewhere that doen't require an open sidebar or covering my tabs / find replace UI. 

![image](https://user-images.githubusercontent.com/31860982/58986971-84951c00-87ac-11e9-87d3-dab159512bba.png)

**Comment by siran** [comment]
@AlexanderHurst's screen is super high, but definitely agree with his tool bar location at the left or in the menu bar. Not in console/terminal bar as it would require to open the side/bottom bar, that is not always required. 
![image](https://user-images.githubusercontent.com/180129/61174044-0ecd5e80-a569-11e9-99ef-98010e5b2d14.png)

**Comment by ronnyek** [comment]
Why cant this just be a toolbar like every other ide?! I just dont get it. "It's not an ide... its an editor"

An editor with debug capabilities, which makes it.... an ide?

**Comment by jjssoftware** [comment]
> Why cant this just be a toolbar like every other ide?! I just dont get it. "It's not an ide... its an editor"
> 
> An editor with debug capabilities, which makes it.... an ide?

If the definition of an IDE is a software tool where you can both edit code and compile code then vscode is an IDE. We can do both of these things in vscode. You might have to install a plugin to compile code in vscode but having done that, code compilation is as much done in vscode as code compilation is done in Visual Studio where code compilation isn't actually performed by devenv.exe but is done by msbuild.exe.

Therefore it follows that both vscode and Visual Studio are both IDEs or they're both not IDEs. You can't have it both ways.

People who attempt to argue that vscode is not an IDE do it for strategic reasons.
