### ISSUE TITLE
Editor not working!

### ISSUE THREAD

**Issue by seemsindie** [Microsoft/vscode#6133]
- VSCode Version: 1.0.0
- OS Version: Linux 4.5.1-1-ARCH x86_64

Steps to Reproduce:

1. Open editor (i think this happened with latest update)

Well i just opened the editor and got blank screen. With this message in the console:
![image](https://cloud.githubusercontent.com/assets/1268576/15046659/37c42684-12e1-11e6-8424-e0501ec579af.png)

**Comment by bpasero** [comment]
@seemsindie weird, I have seen this error before but only if you try to start a second instance after deleting the folder from which the first instance started. Does it work after a reboot? Does it work from the insiders build?

We are releasing preview releases of the next stable VS Code version for everyone to try and give feedback. These preview releases are not 100% tested and might be unstable but contain our latest features and bugfixes. You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by seemsindie** [comment]
@bpasero Yes, now that you say it, i deleted the folder which was the first instance, and then i started the second one and it didn't work. But now it's working after reboot. Weird :)

**Comment by bpasero** [comment]
Ok this is https://github.com/Microsoft/vscode/issues/2259
