### ISSUE TITLE
User install nag won't stop nagging!

### ISSUE THREAD

**Issue by cosmoKenney** [Microsoft/vscode#61339]
How do I disable the nag for the "User Install"? I would install it, but the user installer doesn't automatically uninstall the system install. And I really don't want to loose my settings.

**Comment by usernamehw** [comment]
It probably shouldn't delete your settings after uninstalling system version... At least I didn't lose anything.

Windows uninstaller even gives this notification:
![screenshot 80](https://user-images.githubusercontent.com/9638156/47233740-56f59100-d3dc-11e8-85c2-8f8f249cadac.png)

**Comment by Tyriar** [comment]
Yes your settings/extensions should remain.

**Comment by cosmoKenney** [comment]
Why close this? My question wasn't answered. How do I disabe the nag?
