### ISSUE TITLE
Empty 'cancelled' notification pops up after every python `start without debbugging` run

### ISSUE THREAD

**Issue by gerazenobi** [Microsoft/vscode#61331]
Issue Type: <b>Bug</b>

When running a python file by selecting the option `Start without debugging`, after the script (any script, this happens on each run) is done, an empty notification pops up without any message just the word and icon for 'cancelled'.

<img width="285" alt="screen shot 2018-10-19 at 17 12 08" src="https://user-images.githubusercontent.com/7520283/47227005-24d73580-d3c2-11e8-9545-ce6cd8990a21.png">

<img width="489" alt="screen shot 2018-10-19 at 17 10 06" src="https://user-images.githubusercontent.com/7520283/47226965-06713a00-d3c2-11e8-987f-edca232b547a.png">

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (6.99GB free)|
|Process Argv|-psn_0_1483114|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.9.1

</details>

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-python/
