### ISSUE TITLE
Customizing Dark+ Default Theme Doesn't Work

### ISSUE THREAD

**Issue by mikernet** [Microsoft/vscode#61337]
The following `settings.json` contents intended to customize only the Dark+ theme, as per the documentation [here](https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme), does not work:

    {
        "workbench.colorCustomizations": {
            "[Dark+ (default dark)]": {          
                "editor.background": "#FF0000FF"
            }
        }
    }

This works but affects all themes:

    {
        "workbench.colorCustomizations": {
                "editor.background": "#FF0000FF"
        }
    }

Furthermore, using `editor.tokenColorCustomizations` results in an unknown configuration setting and no intellisense is provided to fill out the token color options as the documentation above suggests it should:

![image](https://user-images.githubusercontent.com/1700111/47232672-4e7e6580-d39e-11e8-8afd-eb2e7c43b2cb.png)

 

- VSCode Version: 1.14.2
- OS Version: Windows 10 1803

Does this issue occur when all extensions are disabled?: Yes

**Comment by usernamehw** [comment]
> VSCode Version: 1.14.2 (June 2017)

That's kind of old version you have there.

**Comment by mikernet** [comment]
Hmmm...it literally just updated itself so I'm not sure why that would be...let me look into it.

**Comment by mikernet** [comment]
Okay, looks like some kind of bug was preventing it from actually ever updating itself when it said it was updating on restart...weird. All fixed now, thanks haha :)
