### ISSUE TITLE
Command-P searching delays

### ISSUE THREAD

**Issue by acdha** [microsoft/vscode#61344]
Issue Type: <b>Bug</b>

I find myself frequently hitting this cycle now, which I don't recall happening much previously:

1. Command-P to search for a file
2. Type the filename
3. Hit enter

There's a race condition here where that either works as expected or stays in the current file because the results hadn't loaded yet and so enter just closed the dialog. It feels like that should be blocked until the file listing actually loads.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz (8 x 3500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.75GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
makeRunner|ale|0.1.1
vscode-django|bat|0.17.0
better-toml|bun|0.3.2
language-prometheus|caa|0.1.2
systemd-unit-file|coo|1.0.0
gitlab-ci-validator|cst|1.0.0
vscode-eslint|dba|1.6.1
xml|Dot|2.3.2
EditorConfig|Edi|0.12.5
prettier-vscode|esb|1.6.1
todo-tree|Gru|0.0.92
vscode-cfn-lint|kdd|0.2.4
restructuredtext|lex|79.0.0
dotenv|mik|1.0.1
vscode-apache|mrm|1.1.1
language-gettext|mro|0.1.1
python|ms-|2018.9.1
cpptools|ms-|0.19.0
vscode-docker|Pet|0.3.1
java|red|0.32.0
rust|rus|0.4.10
crates|ser|0.3.3
vscode-nginx|sha|0.5.0
stylelint|shi|0.44.0
rewrap|stk|1.9.1
vcl|tho|0.1.2
html-preview-vscode|tht|0.2.4
shellcheck|tim|0.6.0
vscode-java-debug|vsc|0.14.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.10.0
vscode-maven|vsc|0.11.1
vscode-ansible|vsc|0.5.1

</details>

**Comment by bpasero** [comment]
I cannot reproduce this neither with the old nor the new implementation. Does this still happen?
