### ISSUE TITLE
If I could able to scold project for supported languages it will be too good. 

### ISSUE THREAD

**Issue by venkatmca008** [Microsoft/vscode#6134]
If I could able to scold project for supported languages it will be too good. instant of going outside .Thanks a lot for Vs code very useful and simple

**Comment by bpasero** [comment]
@venkatmca008 are you talking about code folding?

**Comment by aeschli** [comment]
@venkatmca008 Can you clarify what you mean by 'scold'?

Closing for now, feel free to reopen once clarified.
