### ISSUE TITLE
Windows installer

### ISSUE THREAD

**Issue by Const-me** [Microsoft/vscode#61343]
You should consider adjusting the installer so it creates compressed folder when installing on NTFS-formatted partition, on Windows.

Take a look at the screenshot (version 1.28.2 x64), that's 40% improvement:
![vscode-disk-size](https://user-images.githubusercontent.com/925112/47236035-26612780-d3db-11e8-8cc9-cac536e0144b.png)

From Inno Setup you’re using, simplest method is probably running [compact.exe](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/compact) from %windir%\system32, after the directory is created but while it’s still empty.

**Comment by joaomoreno** [comment]
In today's world, 100-ish MB is nothing. We will very likely not do this.
