### ISSUE TITLE
ctrl + / in html file displays {% comment %} ... {% endcomment %}

### ISSUE THREAD

**Issue by qdirks** [Microsoft/vscode#61348]
Issue Type: <b>Bug</b>

This comment was copied from issue #61030.

@aeschli

Yeah, it's happening again. I can believe that there are no changes in that area. This has been an issue for me in previous versions I think. Sometimes it works fine, and sometimes it doesn't.

I guess I'm leaving my computer (and vscode) on for several hours at a time without usage. Could that cause the bug to manifest?

I can confirm that closing and re-opening the program does not fix the problem. I will try a reboot really quick and see if the problem is gone.

![](https://user-images.githubusercontent.com/26916078/47208821-75b04500-d354-11e8-9d31-2381e366ae7d.PNG)

The bug is still present after rebooting. As of right now, I'm not sure what I'm doing to cause the bug to manifest, or what causes the bug to disappear.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (8 x 3411)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (10.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
vscode-color|ans|0.4.5
django-html|bib|1.2.0
django-snippets|bib|1.1.0
jshint|dba|0.10.20
tslint|eg2|1.0.40
python|ms-|2018.9.1
cpptools|ms-|0.19.0
csharp|ms-|1.16.2
vsliveshare|ms-|0.3.834
debugger-for-chrome|msj|4.10.2
java|red|0.32.0
vscode-icons|rob|7.27.0
vscode-java-debug|vsc|0.14.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.10.0
vscode-maven|vsc|0.11.1

</details>

**Comment by qdirks** [comment]
It's the next day now, my computer was off all night, and I'm still seeing the incorrect behavior exhibited.

**Comment by collinsnji** [comment]
@qdirks hi, out of curiosity, did you ever change your key bindings at some point? I can't reproduce this behaviour

**Comment by qdirks** [comment]
Not to my knowledge. Ctrl + / is the default binding for comment shortcut, right? That's what it is for me.

It was working correctly for me just a moment ago, but I was able to trigger the bug just now.

Can you please try to:
step 1: open vscode
step 2: open an html file or untitled file with html language
step 3: test if the comment shortcut is working, if it is
step 4: leave the tab open in vscode, and close vscode
step 5: re-open vscode. your tab is probably still there
step 6: test if the comment shortcut is not working now for the html

or basically:
step 1: test html comment shortcut
step 2: close and reopen
step 3: test html comment shortcut

This seems to trigger it for me. I was thinking, maybe it happens if I try to comment something before vscode is done loading up completely; you might see if that can trigger it. I would test it myself, but I can't right now, since it is currently in the triggered state for me, and I don't know how to un-trigger it.

**Comment by aeschli** [comment]
@qdirks I tried your steps and don't see the problem. This is my sample code:
```html
<html>
<script>

   console.log("Hello")

</script>
</html>
```

I set the cursor at the beginning of the 'console.log' line and press 'Ctrl + /'.

**Comment by qdirks** [comment]
After vscode does those little updates, it starts working again.

I also tested to see if it matters about vscode still loading up, and no it doesn't. The comment shortcut always fails after closing and reopening vscode for me, no matter how long you wait for vscode to be done loading, but -- so far as I'm aware -- it only happens in html files. After it has failed, it does not work again until something happens, like an update, or you uninstall it and reinstall it. Rebooting does nothing.

**Comment by aeschli** [comment]
Thanks for the video. The problem is that your editor language is 'Django Template' (as seen in the status bar). You have to file an issue against the extension that provides the Django Template language to configure embedded languages like HTML does.

**Comment by qdirks** [comment]
Okay. And when you uninstall and reinstall, it plainly says that extensions are not removed. I don't remember ever installing the django extension, but I can believe that I did at some point. Disabling that fixed the issue for me. Thanks so much. I'll see if I can file a bug for that extension.

**Comment by aeschli** [comment]
which django extension was it? We should file an issue against it.

**Comment by qdirks** [comment]
https://github.com/iambibhas/vscode-django-template

or if you type in "django template" when searching the extension marketplace inside vscode. It's the one by bibhasdn, v.1.2.0

I would have filed an issue with it but I don't see how to do it. And I was looking at it... that actually might be intended for it to markup the comments that way. Look at this image:


![](https://raw.githubusercontent.com/iambibhas/vscode-django-template/master/example.png)

Very similar markup. This picture is on the extension page. Perhaps I was not cognizant of why I was installing the extension in the first place so long ago.
