### ISSUE TITLE
Can't move window from space right after the last menu item

### ISSUE THREAD

**Issue by jongio** [Microsoft/vscode#61340]
Issue Type: <b>Bug</b>

When window not fully maximized, I can't click and drag the space right after the last menu item to move the window.

This space right here:

![image](https://user-images.githubusercontent.com/2163001/47234286-2edd4200-d38a-11e8-8ff3-69085a85fe15.png)

In between Selection and the file name.  I can't move the window using that space.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|23.94GB (5.18GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/jon/Dropbox/code/GitHub/jongio/iotedgedev|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
vscode-hexo|cod|1.0.1
vscode-gist|dba|1.0.0
gitlens|eam|8.5.6
vs-code-xml-format|fab|0.1.5
code-runner|for|0.9.4
docker-explorer|for|0.1.6
terminal|for|0.0.10
vscode-pull-request-github|Git|0.2.1
Python-autopep8|him|1.0.2
github-pr|jas|1.0.0
csharpfixformat|Leo|0.0.76
code-coverage|mar|0.0.2
dotenv|mik|1.0.1
vscode-azurefunctions|ms-|0.11.0
python|ms-|2018.9.1
azure-account|ms-|0.4.3
cpptools|ms-|0.19.0
csharp|ms-|1.16.2
PowerShell|ms-|1.9.0
vscode-docker|Pet|0.3.1
vscode-coverage-gutters|rya|2.2.0
code-settings-sync|Sha|3.2.0
code-spell-checker|str|1.6.10
python|tht|0.2.3
terminal-tabs|Tyr|0.2.0
azure-iot-edge|vsc|1.5.0
azure-iot-toolkit|vsc|1.5.0
vscode-arduino|vsc|0.2.22

</details>

**Comment by sbatten** [comment]
@jongio this has to do with the fact that your window is very small and the menu is being collapsed but still occupying that space. You can still drag with the title I believe, but thanks for pointing this out.

**Comment by sbatten** [comment]
sorry @jongio I fixed this issue under a duplicate :( #64741

we know in our hearts you pointed it out first ❤️

**Comment by jongio** [comment]
All good! Glad it is fixed
