### ISSUE TITLE
Conditional bp intellisense isn't in the column context

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#61357]
Have some code:

```ts
let x: string[] = [];
x.map(y => y.charAt(0))
```

- Set an inline bp inside the callback on `charAt`
- In the expression input box, type `y`. The y var inside the callback isn't in the suggest list 🐛 
- Type `x`, see it in suggestions ✔️

**Comment by isidorn** [comment]
Yeah, breakpoint widget has limited intellisense support which is visible in this corner case
If you would like to experiment and try to tune it here's a code pointer https://github.com/Microsoft/vscode/blob/4d9f1d23a556dccd2c0fd5203923a24b21e41209/src/vs/workbench/parts/debug/electron-browser/breakpointWidget.ts#L220
