### ISSUE TITLE
Allow choosing which local to use in the application.

### ISSUE THREAD

**Issue by Mparaiso** [Microsoft/vscode#6135]
- VSCode Version: 1.0.0
- OS Version: Windows 8.1

Please allow choosing which local to use in the application. It's stupid that it is sometimes difficult to follow tutorials on the net that depends on english when the interface is not in English, furthermore, several translations make no sense. I'm ready to contribute though, if you are interested.

**Comment by Citizen01** [comment]
Do you mean this ?
https://code.visualstudio.com/docs/customization/locales
