### ISSUE TITLE
Add shortcut to delete to EOL in integrated terminal

### ISSUE THREAD

**Issue by janosh** [Microsoft/vscode#61354]
`cmd+backspace` does not delete to end of line in integrated terminal. There appears to be no way to set a shortcut for that.

**Comment by Tyriar** [comment]
You can do this now by adding this keybinding:

```json
{ "key": "cmd+backspace",
  "command": "workbench.action.terminal.sendSequence",
  "args": { "text": "\u0015" } }
```

I like the idea of making this a default though 👍

**Comment by janosh** [comment]
> I like the idea of making this a default though 👍

@Tyriar Me too!

**Comment by janosh** [comment]
Adding this to `keybindings.json` is not working for me.
```json
{
    "key": "cmd+backspace",
    "command": "workbench.action.terminal.sendSequence",
    "args": { "text": "\u0015" }
}
```
I'm using `zsh` in case that matters.

**Comment by janosh** [comment]
@Tyriar Could you please reopen this issue?

**Comment by Tyriar** [comment]
@janosh I notice zsh clears the entire line instead of to beginning, are you aware of a keystroke that clears to beginning only?

Are you on v1.28 as sendSequence will only work there.

**Comment by Tyriar** [comment]
@janosh hmm, well that's exactly what the keybinding is meant to do `\u0015` is just another way of saying `0x15`.

**Comment by janosh** [comment]
FWIW, there seems to be a general problem with sending sequences via keybindings for me. I just tried the example under [Send text from a keybinding](https://code.visualstudio.com/docs/editor/integrated-terminal#_send-text-from-a-keybinding):
```
{
  "key": "ctrl+u",
  "command": "workbench.action.terminal.sendSequence",
  "args": { "text": "\u001b[1;5D\u007f" }
}
```
which supposedly binds `ctrl+u` to jump over the word to the left of the cursor (ctrl+left arrow) and press backspace. However, for me it doesn't change the default behavior of `ctrl+u`, i.e. deleting the entire line (even after restarting VS Code).

**Comment by Tyriar** [comment]
@janbaltus I think this is because the sendSequence command wasn't whitelisted to always skip the shell until the upcoming 1.29, it should work then. In the meantime you can add the command manually to `terminal.integrated.commandsToSkipShell`

**Comment by janosh** [comment]
Perfect! Now it works!
