### ISSUE TITLE
Breadcrumbs symbol tree items with twisties are misaligned

### ISSUE THREAD

**Issue by ryanclarke** [Microsoft/vscode#61365]
![image](https://user-images.githubusercontent.com/2686469/47249847-ec961e00-d3e6-11e8-9467-91e10b58d685.png)

Version: 1.29.0-insider (user setup)
Commit: 45d5d153bbebed743b77e426615aade34971eb46
Date: 2018-10-19T06:58:45.940Z
Electron: 2.0.11
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Steps to Reproduce:
1. Turn on breadcrumbs
2. Open the last breadcrumb item's treeview with the ellipsis to see the file's symbols.
3. The rows of items with twisties are not left aligned correctly like they are in 1.28. The same issue exists in all file types I've checked: ts, js, and json. The directory/file treeviews on directory/file breadcrumbs are still aligned correctly.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
<img width="402" alt="screenshot 2018-10-22 at 14 12 47" src="https://user-images.githubusercontent.com/1794099/47291655-bfbf5200-d604-11e8-953d-f889a08dc9c1.png">

Looks good to me

**Comment by ryanclarke** [comment]
Weird. I'm still seeing it on the latest insiders but not on 1.28.

**Comment by ryanclarke** [comment]
I no longer see this behavior in 1.29. Closing.
![image](https://user-images.githubusercontent.com/2686469/48372753-8cb13100-e68d-11e8-8098-4ca41189c328.png)
