### ISSUE TITLE
FileWatcher EventEmitter warning

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#61362]
Open a workspace with more than 11 folders, see this warning.

```
[IPC Library: File Watcher (nsfw)] (node:75333) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added. Use emitter.setMaxListeners() to increase limit
```

I just fixed the same for search. It's not a problem but doesn't look good.

**Comment by Tyriar** [comment]
@roblourens OS?

**Comment by roblourens** [comment]
Mac

**Comment by Tyriar** [comment]
Upstream: https://github.com/Axosoft/nsfw

**Comment by gigouni** [comment]
Hi @Tyriar 

The upstream issue comment (https://github.com/Axosoft/nsfw/issues/89#issuecomment-606948385) seems they won't provide any fix. Do you know how to increase this value within VS Code?

Thanks

**Comment by Tyriar** [comment]
I'm not sure know where the listeners are getting registered. I don't think our built-in event emitter will trigger that which is why I thought it was in nsfw. Relevant code: https://github.com/microsoft/vscode/tree/master/src/vs/platform/files/node/watcher/nsfw
