### ISSUE TITLE
It will hang if I open the second 'Code' project in the second window

### ISSUE THREAD

**Issue by frankzhang718** [Microsoft/vscode#61360]
- VSCode Version: from 1.28.1, also crashed in 1.28.2
- OS Version: MS Windows 7 64-bit with SP1 (built 6.1.7601)

Steps to Reproduce:
1. open one code window (= instance), open one project.
2. open another code window (my way is to right-click code icon on the bottom bar). It could hang
3. try to open another project, it will hang

Does this issue occur when all extensions are disabled?: Yes. 
No matter all extensions are disabled or not.

**Comment by frankzhang718** [comment]
It was ok in version 1.26 and before. It can support 2 or more Code window and open quickly. It was useful while studying or check another project.
By the way, I feel the new version (1.28.x) become a little slow.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
