### ISSUE TITLE
关于自动提示问题

### ISSUE THREAD

**Issue by swat521** [Microsoft/vscode#61367]
Issue Type: <b>Bug</b>

正常使用的情况下,然后把电脑休眠,在打开,自动提示就没了,必须重启客户端才能恢复

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:13:53.910Z)
OS version: Windows_NT x64 10.0.17134

**Comment by Tyriar** [comment]
Little help @octref 😅

**Comment by octref** [comment]
@Tyriar He was saying when laptop goes to sleep mode and wake up again, IntelliSense is gone. He has to restart VS Code to get it.

@swat521 在 issue 中請使用英文，并提供 bug 相關的信息 (使用的編程語言)。謝謝。
