### ISSUE TITLE
Local variable completion fails after auto parameter completion in Java method call

### ISSUE THREAD

**Issue by safield** [Microsoft/vscode#61364]
Version: 1.29.0-insider
Commit: 9e83209ed59a22df3d593735d04cc963396bb89e
Date: 2018-10-18T05:14:11.586Z
Electron: 2.0.11
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Java Language Support by Red Hat version 0.32.0

Linux Mint 19

When I am typing out a java method which takes parameters, and then auto completion presents me with to option to complete the method, I select this option. Subsequently, the auto completion also fills in the parameter name for the method call. When I delete this parameter, and start typing the name of a local/member variable, there is no completion suggestions for this variable.

Observe the following code:

```
public class VscodeTest {

    int blah;

    public VscodeTest() {
    }
    public void someMethod(int bar){
    }
    public void test() {
        int backet;

        someMethod();
    }
}
```

**Scenario 1:**
-In the test() method, I start typing out "some" and the select the completion suggestion _someMethod(int bar)_.
-someMethod gets completed to _someMethod(bar);_
-I then delete _bar_ and start typing either _backet_ or _blah_
-no completion suggestion appears.

**Scenario 2:**
-In the test() method I manually type out _someMethod();_
-I place the caret in the method call brackets and start typing either _backet_ or _blah_
-in both cases, autocomplete suggestions pop up for the variables.

**Comment by Tyriar** [comment]
https://github.com/redhat-developer/vscode-java
