### ISSUE TITLE
Open browser failed

### ISSUE THREAD

**Issue by wangquanqing** [Microsoft/vscode#61374]
Issue Type: <b>Bug</b>

Open browser failed!! Please check if you have installed the browser  correctly!
1.28.2

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX-7500 Radeon R7, 10 Compute Cores 4C+6G   (4 x 2096)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|6.93GB (1.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.28.2
python|ms-|2018.9.1
view-in-browser|qin|0.0.5
open-in-browser|tec|2.0.0

</details>

**Comment by Tyriar** [comment]
What did you do that made it say this?
