### ISSUE TITLE
Allow to open 2 files side by side from the command line

### ISSUE THREAD

**Issue by jabbalaci** [microsoft/vscode#61373]
I want to open 2 files side by side, from the command line. I want to use vertical alignment. In vim it's "`vim -O file1 file2`" ("`-o`" will do horizontal split). Is it possible in VS Code?

Motivation: I have a project where my modules have unit tests. It would be great if I could see a module and its unit test next to each other. Thus I could verify easily if everything is tested or should I add more tests.

**Comment by jtencer** [comment]
I have an additional usecase for this capability.  I have a script which generates a large number of image pairs.  I would like to conveniently open pairs of them side-by-side for visual comparison.  For external reasons, the pairs are not named such that they are alphabetically adjacent (or even in the same folder), so it is extremely cumbersome to select these pairs through the gui.  It would be exceedingly easy to do this if there were a CLI option for opening multiple files side-by-side.

**Comment by pippaine** [comment]
I have yet another use-case: I am managing my projects in a note-taking app like Obsidian, and I'd like to use plugin functionality there to execute a command which will directly open the editor in the workspace configuration I typically use to reduce friction in my workflow

**Comment by xavdid** [comment]
I'd love this because I have a workflow that involves generating 3 new files every day. Each day, I have to open them each in vscode and then arrange them manually. It's not a lot of work, but it adds up. 

It would be super convenient to be able to do something like:

```
code --left file-a.txt --right file-b.txt --right file-c.txt
```

And have it just jump into the shape I want.
