### ISSUE TITLE
Emmet for CSS files not working

### ISSUE THREAD

**Issue by Fuego710** [Microsoft/vscode#61375]
Emmet works fine for HTML files but I can't seem to get any suggestions for any CSS/SASS/SCSS files to work. I don't see any suggestions in the popup box and pressing tab after typing p20-10 just adds an actual tab.

Here are the user settings I have:

`
"window.zoomLevel": 1,
"emmet.triggerExpansionOnTab": true,
"emmet.showSuggestionsAsSnippets": true,
"editor.snippetSuggestions": "top",
"emmet.syntaxProfiles": {
    "html": {
        "filters": "bem"
    },
    "html.autoClosingTags": true,
},
`

![emmet](https://user-images.githubusercontent.com/32409846/47254741-21918780-d45e-11e8-8f38-675c4dda0660.jpg)

**Comment by ramya-rao-a** [comment]
Emmet in css files is for the css property value pairs for which you should be typing inside a css rule. In your examples that is not the case.

Try typing `p20-10` inside a rule
```
.foo {
   p20-10
}
```

**Comment by Fuego710** [comment]
The biggest of brain farts, sorry to waste your time!
