### ISSUE TITLE
VSCode now appears as penguin icon on Chromebook

### ISSUE THREAD

**Issue by DavidMorton** [Microsoft/vscode#61377]
Issue Type: <b>Bug</b>

Using Crostini, installed VSCode. I pinned VSCode to the shelf, and when I run it, a new icon appears with a penguin in it. This didn't happen with the previous version of VSCode. 

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:20:56.183Z)
OS version: Linux x64 4.14.65-05969-g6f2926628697

![image](https://user-images.githubusercontent.com/2237045/47255146-00b33d00-d432-11e8-8d3e-afcd2abaee94.png)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|06/8e (4 x 1607)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|0, 0, 0|
|Memory (System)|4.84GB (3.95GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|100%|

</details>Extensions: none

**Comment by Tyriar** [comment]
Is this penguin icon some generic icon for ChromeOS? 😕

**Comment by DavidMorton** [comment]
I believe so... The following Reddit thread shows people having a similar issue after the last VSCode update (and also has a link to the corresponding ChromeOS bug report, to cover all the bases). I'm not sure if something changed with the WMClass or something, but it seems to be affecting multiple people when running VSCode via Crostini on Chromebooks. Prior to the most recent update, this was not an issue.

**Comment by Tyriar** [comment]
Looks like it's fixed on their side https://bugs.chromium.org/p/chromium/issues/detail?id=893690

**Comment by sarbbottam** [comment]
Looks like it is yet not resolved. I just installed VSCode in Pixelbook running 70.0.3538.76 and experiencing the same issue.
