### ISSUE TITLE
tsserver crashes when using ts code with dynamic import

### ISSUE THREAD

**Issue by MirKml** [Microsoft/vscode#61376]
- VSCode Version: 1.28.2 with Typescript 3.1.3
- OS Version: Windows 10

Steps to Reproduce:

1. extract attached zip into folder, load into vs code
2. npm install
3. Go to main.tsx above ReactDOM.Render try to type e.g. ```var test: Test```

tsserver for intellisense crashes with the

```
[Error  - 12:34:19 PM] 'getCodeFixes' request failed with error.
Error processing request. Debug Failure.
Error: Debug Failure.
    at Object.assertDefined (e:\vscode\resources\app\extensions\node_modules\typescript\lib\tsserver.js:1446:24)
    at getDefaultExportInfoWorker (e:\vscode\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108210:80)
    at getDefaultLikeExportInfo (e:\vscode\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108191:24)
    at e:\vscode\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108174:35
    at e:\vscode\resources\app\extensions\node_modules\typescript\lib\tsserver.js:108318:21```
```

I found that problem is with the js-xlsx/* files. I added path for these into tsconfig.json and jsconfig.json  into exlude section, but vscode still crashes.

[vscode-crash.zip](https://github.com/Microsoft/vscode/files/2498078/vscode-crash.zip)

**Comment by mjbvz** [comment]
Thanks. This is already tracked upstream by https://github.com/Microsoft/TypeScript/issues/27878
