### ISSUE TITLE
Terminal Chinese display problem when execute git log

### ISSUE THREAD

**Issue by JiangPF92** [Microsoft/vscode#61372]
- VSCode Version: 1.28.2
- OS Version: windows7 64

Steps to Reproduce:

1. Git commit with chinese;
2. Execute git log command in ternimal of vscode;

PS D:\sources\pycodes> git log
commit 834b6ec7dcc2fb18b0e8e1193157d0f88bdbc2e6 (HEAD -> master)
Author: Your Name <you@example.com>
Date:   Sat Oct 20 17:24:26 2018 +0800

    <E5><88><A0><E9><99><A4>ipan_lodas

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/60717
