### ISSUE TITLE
Settings tabs are jumpy between selection

### ISSUE THREAD

**Issue by c5inco** [Microsoft/vscode#61370]
Issue Type: <b>Bug</b>

With at least one folder loaded in Code:

1. Go to Code > Preferences > Settings
2. Click on either "User Settings" or "Workspace Settings"

Notice tab spacing is jumpy when changing active selection.  It should NOT be as jumpy.  I believe it's caused by the text being bolded on active selection.

<i>Desired</i>

![Not jumpy tabs](https://i.imgur.com/ZmmBOpk.gif)

<i>Actual</i>

![Jumpy tabs](https://imgur.com/2KDWhzS.gif)

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (0.30GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by c5inco** [comment]
Here's the fix #61371

**Comment by roblourens** [comment]
I'm not sure about this change, I think the bold is necessary to make the selected tab noticeable. Some themes hide the underline on the selected item, and in some themes, the color difference is not really noticeable. So I would worry that this would make it impossible to tell which tab is selected. I also don't really have an issue with the slight shifting, I've never noticed it before now.

**Comment by misolori** [comment]
We should try to remove this shift as it's not really smooth. In our other tabs (panels, settings json) we don't use alternate font-weights for active/inactive, so I think we should keep them consistent and the same.

Alternatively, if we really want to make the states look different we could adjust the opacity (just like the other tabs) as long as they pass the color contrast ratio:
![ezgif com-gif-maker 14](https://user-images.githubusercontent.com/35271042/47307885-01400500-d5e5-11e8-8c94-1d64acff421a.gif)

**Comment by c5inco** [comment]
I agree that it's not smooth.  It's also not consistent with the other tabs in the product.  

There is a hack that can remove the shifting (discussed [here](https://stackoverflow.com/questions/556153/inline-elements-shifting-when-made-bold-on-hover) with this [JSFiddle](http://jsfiddle.net/85LbG/)), however I think that might be overdoing it to achieve this effect.

I would add the opacity change as well to help reinforce the two states.

**Comment by roblourens** [comment]
Should I just borrow the inactive color from the panel tabs, at least for the builtin themes? Or if I should use opacity, can you tell me what color/opacity to use? Looking through some popular ones, I don't think this change would be a problem for that many other themes really...

Also for folder settings, the folder name and string "Folder Settings" are currently distinguished by size and color, so we might still need 3 colors.

**Comment by roblourens** [comment]
Actually the current panel tab colors in Monokai don't meet the contrast requirement: 
![image](https://user-images.githubusercontent.com/323878/47321378-876e4280-d609-11e8-8514-a28080329a20.png)

![image](https://user-images.githubusercontent.com/323878/47321399-8f2de700-d609-11e8-880f-6df09c1f6854.png)

**Comment by misolori** [comment]
We only need to meet the color contrast on the themes we own, which is light/dark/hc. Here's the contrast on the inactive text:

|Dark|Light|
|---|---|
|![image](https://user-images.githubusercontent.com/35271042/47332461-3de71d00-d634-11e8-9ef0-8fce541910a2.png)|![image](https://user-images.githubusercontent.com/35271042/47332484-51928380-d634-11e8-8972-13c0ae9de747.png)|

Here's the colors and opacity for the active/inactive panels:

https://github.com/Microsoft/vscode/blob/d1f5894892e3719846bbd4bd0dd75f117f211ab5/src/vs/workbench/common/theme.ts#L214-L224

For the folder settings, you can change the opacity to `.90` (which passes) and will end up looking like this:
![image](https://user-images.githubusercontent.com/35271042/47332945-fc577180-d635-11e8-8afc-e6f5380c1603.png)
