### ISSUE TITLE
There is a problem with the Korean on the terminal (git bash).

### ISSUE THREAD

**Issue by mulder21c** [Microsoft/vscode#61380]
- VSCode Version: 1.28.2
- OS Version: Windows 10 Pro

Steps to Reproduce:

1.Open git bash as Terminal Integrated Shell 
2.Print git log, or write korean on vim editor in bash

![vscode](https://user-images.githubusercontent.com/14821565/47255677-d1dbac00-d4af-11e8-9068-c7890906004a.jpg)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/60717
