### ISSUE TITLE
Source code manager doesn't update its contents when a file saves

### ISSUE THREAD

**Issue by LambdaAlpha** [microsoft/vscode#61386]
Issue Type: <b>Bug</b>

action => is the source code manager update its contents
* modify and save the **first** file A => **yes**
* modify and save file B => **no**
* modify and save file A again => **yes**, so **B** is traced correctly now
* modify and save file C => no
* modify and save file B again => yes, so C is traced correctly now
* ...
* modify and save file which is not traced by the source code manager => no
* modify and save file which is traced by the source code manager => yes, and all modified files are traced correctly now

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:20:56.183Z)
OS version: Linux x64 4.15.0-36-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 1661)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|5.72GB (1.39GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
output-colorizer|IBM|0.1.2
gitignore|cod|0.5.0
bracket-pair-colorizer|Coe|1.0.60
transformer|dak|1.6.0
vscode-markdownlint|Dav|0.20.0
vscode-eslint|dba|1.6.1
xml|Dot|2.3.2
translation|dus|0.0.4
gitlens|eam|8.5.6
vscode-highlight|fab|1.3.0
gitlab-workflow|fat|1.2.0
code-runner|for|0.9.4
latex-workshop|Jam|5.13.0
align-by-regex|jan|1.0.1
select-highlight-minimap|mde|0.0.8
markdown-shortcuts|mdi|0.8.1
metago|met|2.11.0
vscode-language-pack-zh-hans|MS-|1.28.2
python|ms-|2018.9.1
cpptools|ms-|0.19.0
java|red|0.32.0
vscode-yaml|red|0.0.17
partial-diff|ryu|1.4.0
code-settings-sync|Sha|3.2.0
vscode-leetcode|she|0.8.0
vscode-fileutils|sle|2.11.0
markdown-all-in-one|yzh|1.6.2

</details>

**Comment by MuseBoy** [comment]
ps:if a file which isn't git traced is modified and saved, the source code manager will update its contents.

**Comment by joaomoreno** [comment]
@MuseBoy Does this reproduce with `--disable-extensions`?

Do you wait at least 10 seconds before assuming the SCM view does not show events?

Can you show me a screen recording?

Is there any correlations between actions working/not working and file names, paths?

If you run with `code --verbose`, does Code report file events?

**Comment by MuseBoy** [comment]
@joaomoreno I reproduce this and found the pattern I found was totally wrong. When the file name contains non-english character, the file is not traced by  the source code manager correctly. That's it. Disableing all extensions does't help.

**Comment by joaomoreno** [comment]
Can you give me an example of a file name which causes this issue?

**Comment by MuseBoy** [comment]
@joaomoreno 中文名.md
