### ISSUE TITLE
I can not open vscode without network

### ISSUE THREAD

**Issue by God1W** [Microsoft/vscode#61381]
I just can not open vscode without network
my system is win10 pro
VS Code version: Code 1.28.2 (7f3ce96, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17763

--------------------------------------------------------------------------------------------------------------
when I run code --verbose in cmd  with network, the vscode will be opened
but without network , the output as following:
PS C:\Windows\system32> code --verbase
dns.js:246
this._handle = new ChannelWrap();
^
Error: EFILE
at new Resolver (dns.js:246:20)
at dns.js:377:25
at dns.js:431:3
at NativeModule.compile (bootstrap_node.js:606:7)
at NativeModule.require (bootstrap_node.js:550:18)
at net.js:45:13
at net.js:1730:3
at NativeModule.compile (bootstrap_node.js:606:7)
at NativeModule.require (bootstrap_node.js:550:18)
at internal/child_process.js:6:13

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/7570
