### ISSUE TITLE
Broken `cmd+alt+t` detection

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#61389]
- VSCode Version: v1.28.2
- OS Version: macOS 10.13.5

Steps to Reproduce:

1. Install [Terminals Manager](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-terminals)
2. Do a `cmd+alt+t`
3. Nothing happens because VSC is waiting for the second chorded shortcut, _unless_ it's executed while the "Keyboard Shortcuts" is in focus 🤷‍♂️ 

<img width="1014" alt="screen shot 2018-10-20 at 17 13 17" src="https://user-images.githubusercontent.com/1812093/47257250-cecec480-d48b-11e8-96db-97358c21b0cc.png">

<img width="864" alt="screen shot 2018-10-20 at 17 09 37" src="https://user-images.githubusercontent.com/1812093/47257249-ce362e00-d48b-11e8-9f14-f1587a3d4745.png">

**Comment by fabiospampinato** [comment]
It looks like my extension's code isn't executed at all if I have the focus on a regular editor. If instead I'm viewing the Keyboard Shortcuts or the custom Settings UI it works 🤷‍♂️

**Comment by ChristianAlexander** [comment]
It's possible that the shortcuts / settings UIs don't satisfy the `editorTextFocus` condition, which makes the press of ⌥⌘T unambiguous while they are open.

**Comment by Tyriar** [comment]
This is by design as the settings UI isn't an editor.

**Comment by fabiospampinato** [comment]
Right, I didn't realize I had 2 chorded shortcuts defined starting with `cmd+alt+t`. The margin inside chorded shortcuts is almost not existent, perhaps it should be increased to avoid confusion.
