### ISSUE TITLE
Emmet input checkbox & input radio

### ISSUE THREAD

**Issue by jluisgarcia** [Microsoft/vscode#61382]
For html input checkbox, Emmet currently outputs:
`<input type="checkbox" name="" id="">`
Is it possible to add the attribute "value"? This attribute is always used. The new output would be this:
`<input type="checkbox" name="" id="" value="">`
The same could be applied for input radio:
 `<input type="radio" name="" id="">`
Thanks

**Comment by ramya-rao-a** [comment]
The snippets come from https://github.com/emmetio/snippets/blob/master/html.json. You can create an issue or submit a PR in that repository, after which I can look into pulling those changes into VS Code.

You can also override the snippets by creating your own [custom snippets](https://code.visualstudio.com/docs/editor/emmet#_using-custom-emmet-snippets)
