### ISSUE TITLE
Cannot change tab spacing

### ISSUE THREAD

**Issue by GregoryLundberg** [Microsoft/vscode#61384]
Issue Type: <b>Bug</b>

I am side-by-side viewing the changes made to a file. The person who did the work tends to mess up the indentation by mixing spaces and tabs. This is easy to spot if you change the Spaces:4 (our default) to something large. But you can't because you're viewing in read-only mode. This is a good check for when you want to change the tabs to spaces, but it's a dumb check if I want to change the number of spaces for a tab without replacement.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17763

**Comment by alexandrudima** [comment]
@GregoryLundberg Sorry I don't exactly understand the issue. The diff editor will out-of-the-box ignore trim whitespace. But you can press a button and have it not ignore them. I personally also enable to render whitespace:

![kapture 2018-10-23 at 12 35 38](https://user-images.githubusercontent.com/5047891/47354888-2fdede00-d6c0-11e8-8400-c3306b8b2625.gif)

**Comment by GregoryLundberg** [comment]
At the bottom is the option to change the spacing. If the editor is in read/write mode, you can change the display rendering from, say 4 spaces per tab to 8, or event 24, which makes it much simpler to find spots where a new member has used tabs where spaces should appear. Yes, I know about the display option you're showing. It's too hard to see those little grayed-out dots. Maybe I'd use it if they were not so invisible when enabled, or maybe it's just that my eyes are half a century older. They're not the issue. The issue is I want to display tabs at 24 columns and it won't let me change it in a read-only mode. I'm not changing the file, so why does it care?

**Comment by alexandrudima** [comment]
@GregoryLundberg The color of the rendered whitespace can be customized. e.g.

```
"workbench.colorCustomizations": {
  "editorWhitespace.foreground": "#ff0000"
}
```

![image](https://user-images.githubusercontent.com/5047891/47414024-3d53a100-d770-11e8-8758-eef7b64d0258.png)

I am not sure I understand what you mean by "The issue is I want to display tabs at 24 columns and it won't let me change it in a read-only mode". I can configure the setting `"editor.tabSize": 24` and this is respected in all the editors.

**Comment by GregoryLundberg** [comment]
I like VS Code but don't like the "we have so many options you'll never learn them all" so I tend to ignore them and go with what I see on screen. On screen is a button at the bottom which I can press to change the tab spacing. I press it, it says I can't change the tab size on read-only documents.

For what I need I've given up on VS Code. I can find the mistakes using `git diff` to find the changed code, and fiddling with my terminal's tab spacing to see the tab/space mistakes in incoming code.

**Comment by alexandrudima** [comment]
@GregoryLundberg 

Do you mean this menu?
![image](https://user-images.githubusercontent.com/5047891/47447532-0906d180-d7be-11e8-9a23-773439b98416.png)

That menu has actions split in two groups. The first group is labeled "change view". When you click on one of those actions you can change how large a tab size is rendered.

The second group is labeled "convert file". If you choose on of those actions you must have opened an editable file. A file that is staged in git's index and presented in a diff editor with the label (Working Tree) is not editable, i.e. you are comparing HEAD with index so neither resource is editable. Typing is also not possible in this situation.

I am happy you managed to find a workaround using `git diff`. In our project (vscode) we use a precommit hook that ensures no commits are done with wrong indentation.

Good luck!
