### ISSUE TITLE
Hang when debugging Python library.

### ISSUE THREAD

**Issue by HaloGithub** [Microsoft/vscode#61388]
- VSCode Version: 1.28.2 (1.28.2)
- OS Version: MacOS Mojave 10.14 (18A391)

Hi All, today I want to debugging one python library call `molecule` but failed. Hanging in debug mode without `step in`, `step out`, `continue` etc.

Here is my lauch.json:

```
        {
            "name": "Python: Molecule Test",
            "type": "python",
            "request": "launch",
            "pythonPath": "~/Working/VirtualEnv/python2/bin/python",
            "program": "~/Working/VirtualEnv/python2/bin/molecule",
            "args": [
                "destroy"
            ],
            "console": "integratedTerminal"
        }
```

Here is my screenshot of VSCode:

![image](https://user-images.githubusercontent.com/28960001/47257017-f9844180-d4ba-11e8-8ee5-047080fbb151.png)

Is anyone have same issue with me?

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode-python/

**Comment by HaloGithub** [comment]
Okay thank you! @Tyriar
