### ISSUE TITLE
help me image appear at editor

### ISSUE THREAD

**Issue by apt425410** [Microsoft/vscode#61392]
![image](https://user-images.githubusercontent.com/27874509/47257585-081e2900-d4ba-11e8-908e-53e1fdf41e11.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/59682

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/45498d93166483c2eff886e28f8dab915ae382fc/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/code-exploration_1.28.0-1538127308_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/VSCodeUserSetup-x64-1.28.0-exploration.exe)
