### ISSUE TITLE
JavaScript IntelliSense missing on recreated file

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#6139]
- VSCode Version:1.1.0-alpha, 1.0-stable
- OS Version:Windows 10, OS X, Ubuntu 14.04

Steps to Reproduce:

1. Create an empty folder and create a new file, app.js
2. Type console. - you get IntelliSense for Console methods.
3. Delete app.js and recreate it.
4. Type console. - no IntelliSense

Need to restart VS Code for IntelliSense to be active again for app.js.
Another workaround is to change the language (ex. C) then change back to JavaScript manually.

**Comment by bpasero** [comment]
Unsure who to ping, @jrieken @dbaeumer @egamma fyi, should this be always filed against TypeScript?

**Comment by jrieken** [comment]
I'd say TypeScript. Looks like thy miss a file event

**Comment by dbaeumer** [comment]
@gregvanl can not reproduce an code-alpha which contains a new version of the tsserver (in comparison of 1.0).

**Comment by dbaeumer** [comment]
@gregvanl can you give it another test with latest.

**Comment by gregvanl** [comment]
Still repros on latest code-alpha on Windows 10.

**Comment by dbaeumer** [comment]
Still not for me :-(. Do you have additional steps info ?

![bug](https://cloud.githubusercontent.com/assets/1931590/15148090/fac2af76-16c3-11e6-96d1-e38d83250024.gif)

**Comment by gregvanl** [comment]
![missingintellisense](https://cloud.githubusercontent.com/assets/12818376/15156143/7f7d70f4-169a-11e6-8e43-c665c3670759.gif)
Here's a repro on another machine Windows 7.

**Comment by gregvanl** [comment]
The .gif above was done with 1.1 stable but it also repros with latest code-alpha

**Comment by dbaeumer** [comment]
@gregvanl what does the code assist show when you press ctrl+space

And I would like to ask you to enable TS trace. Add the following workspace setting
```json
"typescript.tsserver.trace": "messages"
```
open the output window and switch to the TypeScript channel and attach the provided log.

**Comment by gregvanl** [comment]
Here's the log from the output window TypeScript channel:
Sending request: open (45). Response expected: no. Current queue length: 0
Sending request: geterr (46). Response expected: no. Current queue length: 0
Event received: semanticDiag (0).
Sending request: projectInfo (47). Response expected: yes. Current queue length: 0
Response received: projectInfo (47). Request took 0 ms. Success: true 
Sending request: change (48). Response expected: no. Current queue length: 0
Sending request: completions (49). Response expected: yes. Current queue length: 0
Response received: completions (49). Request took 3 ms. Success: false . Message: Error processing request. Cannot read property 'lineCount' of undefined
Sending request: geterr (50). Response expected: no. Current queue length: 0
Sending request: change (51). Response expected: no. Current queue length: 0
Event received: semanticDiag (0).
Sending request: geterr (52). Response expected: no. Current queue length: 0
Event received: semanticDiag (0).
Sending request: change (53). Response expected: no. Current queue length: 0
Sending request: geterr (54). Response expected: no. Current queue length: 0
Event received: semanticDiag (0).
Sending request: change (55). Response expected: no. Current queue length: 0
Sending request: geterr (56). Response expected: no. Current queue length: 0
Event received: semanticDiag (0).
Sending request: change (57). Response expected: no. Current queue length: 0
Sending request: geterr (58). Response expected: no. Current queue length: 0
Event received: semanticDiag (0).
Sending request: change (59). Response expected: no. Current queue length: 0
Sending request: geterr (60). Response expected: no. Current queue length: 0
Event received: semanticDiag (0).
Sending request: change (61). Response expected: no. Current queue length: 0
Sending request: geterr (62). Response expected: no. Current queue length: 0
Event received: semanticDiag (0).
Sending request: change (63). Response expected: no. Current queue length: 0
Sending request: geterr (64). Response expected: no. Current queue length: 0
Sending request: change (65). Response expected: no. Current queue length: 0
Event received: semanticDiag (0).
Sending request: geterr (66). Response expected: no. Current queue length: 0
Event received: semanticDiag (0).
Sending request: change (67). Response expected: no. Current queue length: 0
Sending request: completions (68). Response expected: yes. Current queue length: 0
Response received: completions (68). Request took 15 ms. Success: false . Message: Error processing request. Cannot read property 'lineCount' of undefined
Sending request: geterr (69). Response expected: no. Current queue length: 0
Event received: semanticDiag (0).

**Comment by gregvanl** [comment]
Code Assist (ctrl+space) just shows:
```
[abc] console
```

**Comment by dbaeumer** [comment]
@gregvanl do you by any change have a tsdk setting which points to a different tsserver. The problem is an exception in the tsserver in your case which I don't get.

**Comment by gregvanl** [comment]
Not that I know of.  I've seen this on several different machines including CDias' OS X machine. I'll see how widespread the repro is on the team here in Redmond.

**Comment by gregvanl** [comment]
Can you see if anyone else in Zurich can repro the issue?  It's a simple repro.

I think the issue is worth investigating since it could happen when a newbie is trying out VS Code or JavaScript or Node.js for the first time.  They create a simple "Hello World" app and then decide to start over recreating the empty file.

**Comment by gregvanl** [comment]
Just repro'd on Wade's OS X machine as well.

**Comment by dbaeumer** [comment]
OK. We have a trace and @gregvanl can easily repro. I will forward to the TS team then. The are in Redmond as well and can easily drop by. The issue is like the trace shows in the tsserver (might be timing related).

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#8587
