### ISSUE TITLE
Some Default VSCode Settings GUI Descriptions not using MarkdownText for code

### ISSUE THREAD

**Issue by beastdestroyer** [Microsoft/vscode#61396]
Issue Type: Bug

- VSCode Version: 1.29.0-exploration and insiders
- OS Version: Windows 10 1803 17134.345

Steps to Reproduce:

1. Open Settings GUI
2. Search carefully and look for backticks ` ` ` in descriptiosn which don't change into markdown.

I have left out extensions obviously as it's based on the authors to fix it.

Locations:
1. CSS > Lint: **Font Face Properties** | `@font-face` rule must define `src` and `font-family` properties
2. CSS › Lint: **Important** | Avoid using `!important`. It is an indication that the specificity of the entire CSS has gotten out of control and needs to be refactored.

@roblourens 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
Thanks, we had to find these one by one and missed a couple...
