### ISSUE TITLE
Custom workspace shell settings not working anymore in 1.29 Insider

### ISSUE THREAD

**Issue by J0F3** [Microsoft/vscode#61394]
Issue Type: <b>Bug</b>

"terminal.integrated.shell.windows" setting defined in .vscode\settings.json is not working anymore in version 1.29 Insider. It works still on the stable verison (1.28.2),

Expected result:
* When opening the first time a folder with a settings.json in it in which the "terminal.integrated.shell.windows" is set to something different than in the user settings, VS Code ask me if I want to allow to launch the shell.
* After that, every time when the folder is opened, the workspace defined shell (e.g. bash) is used for the integrated terminal instead of the default PowerShell.

Actual result with 1.29 Insider (also with all extensions disabled):
* When the folder is opened the first time the question to allow the custom shell is not displayed.
* When the folder is opened the "terminal.integrated.shell.windows", from .vscode\settings.json in that folder, just get silently ignored and the default shell is used instead.
* If I add "terminal.integrated.isWorkspaceShellAllowed = true" for the corresponding workspace manually through the Dev Tools it works again after closing and re-opening the folder.

VS Code version: Code - Insiders 1.29.0-insider (45d5d153bbebed743b77e426615aade34971eb46, 2018-10-19T06:58:45.940Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz (4 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (9.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by Tyriar** [comment]
This was caused by strict null checks in here ignoring fallbackValues of `undefined` ff13b502778296c9124b2926a1b7a35ab9c3d3fe:

@mjbvz the changes to `getInteger` and `getBoolean` are not safe.

<img width="1397" alt="screen shot 2018-10-25 at 2 56 58 pm" src="https://user-images.githubusercontent.com/2193314/47532810-3e66fa00-d866-11e8-8fd7-a4ae29afd841.png">

Changing it to this fixes it for the terminal case but I'm not confident that it fixes other cases:

```
getBoolean(key: string, fallbackValue?: boolean | undefined): boolean | undefined {
```

**Comment by Tyriar** [comment]
@mjbvz I pushed 60cbd1fd0b56fa8ad7dc4e0187a9036fcc4545c1, compile and `yarn strict-null-check` passes. Please give it a review.
