### ISSUE TITLE
VS Code uninstalled itself

### ISSUE THREAD

**Issue by willharrison** [Microsoft/vscode#61390]
Last night I installed an update to VS Code and after the update was installed I was no longer able to access VS Code because it seems to have been uninstalled. I installed the update last night and went to sleep. When I woke up VS Code was gone. I do not know if it was gone before I went to sleep or not.

The `C:\Program Files\Microsoft VS Code` directory has all folders in it but they are all empty other than the root folder and tools.

In the root folder I have the following files:

```
unins000.dat
unins000.exe
unins000.msg
```

and in the tools folder:

```
inno_updater.exe
vcruntime140.dll
```

- VSCode Version: Unsure. I think it was the version right before the latest.
- OS Version: Windows 10 Pro 1803

Steps to Reproduce:

1. Open VSCode
2. When asked to install update accept
3. Install update
4. Close laptop
5. Wake laptop
6. VSCode deleted

Does this issue occur when all extensions are disabled?: N/A

**Comment by joaomoreno** [comment]
That's not great. We are currently tracking update issues in #47841. It seems that you might've hit one. Can you see if you find an update log in `%TMP%`?
