### ISSUE TITLE
Unable to close an opened file.

### ISSUE THREAD

**Issue by Cvelth** [Microsoft/vscode#61395]
- VSCode Version: 1.28.1
- OS Version: Windows 10 (1803) Build: 17134.345 

Steps to Reproduce:
1. Mount NFS file system and open file using VSCode.
2. Close VSCode.
3. Unmount NFS.
4. Open VSCode again. File cannot be closed.

After an attempt to close (or activate) the file, VSCode freezes and 
![image](https://user-images.githubusercontent.com/18015148/47258619-81138580-d4a6-11e8-9665-ff9b009d455b.png)
message appears shortly after.

Address of the file (if it matters): \\192.168.43.86\shared\data.txt

Does this issue occur when all extensions are disabled?: Yes, it does.

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by Cvelth** [comment]
> Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!
[vscode_logs.zip](https://github.com/Microsoft/vscode/files/2503239/vscode_logs.zip)

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/45498d93166483c2eff886e28f8dab915ae382fc/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/code-exploration_1.28.0-1538127308_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/VSCodeUserSetup-x64-1.28.0-exploration.exe)

**Comment by Cvelth** [comment]
I'm unable to reproduce the issue anew as I don't have access to said network anymore.

**Comment by Cvelth** [comment]
No, I mean, I don't have access to the network causing the issue, so I cannot reproduce it in new copy of VScode, but the issue with my copy is still remain (I cannot close the file).
