### ISSUE TITLE
File watcher exclude doesn't work

### ISSUE THREAD

**Issue by Honzys** [Microsoft/vscode#61393]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Have a directory containing a lots of files/directories named "data"
2. Add a folder with sources, etc. and also containing the "data" folder to workspace.
3. Set user settings:
```
"files.watcherExclude": {
	"**/data/**": true,
	"**/shared/**": true,
	"**/.git/objects/**": true,
	"**/.git/subtree-cache/**": true,
	"**/node_modules/**": true
},
"files.exclude": {
	"**/.git": true,
	"**/.svn": true,
	"**/.hg": true,
	"**/CVS": true,
	"**/.DS_Store": true,
	"**/data": true,
	"**/shared": true,
},
"search.exclude": {
	"**/node_modules": true,
	"**/bower_components": true,
	"**/data": true,
	"**/shared": true,
},"
```
3. Use `htop` to watch `watcherService` cpu usage and see that CPU usage is constant 20% (and also `ntfs-3g` driver consumes 60% CPU because of the files are on the ntfs filesystem - Due to dual boot with windows).
5. Remove that folder from workspace, restart vs and check htop again, see that there's no cpu usage.
6. Add folder to workspace, restart and see the CPU usage again.

I guess the `files.watcherExclude` doesn't work properly, because the watcher is consuming so much CPU usage when the folder with huge amount of files is in the workspace.

Did someone solved this issue? Or can someone take a look at that?
Is there a log for watcherService to dig deep into it?

Thank you very much !

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:20:56.183Z)
OS version: Linux x64 4.15.0-36-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz (8 x 2759)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|7.25GB (0.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
laravel-blade-spacer|aus|1.0.2
vscode-intelephense-client|bme|0.8.8
path-intellisense|chr|1.4.2
laravel-goto-view|cod|1.2.3
bracket-pair-colorizer|Coe|1.0.60
vscode-html-css|ecm|0.2.0
vsc-material-theme|Equ|2.4.2
php-debug|fel|1.12.6
php-intellisense|fel|2.3.5
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
referenceshelper|gay|0.2.3
vscode-gutter-preview|kis|0.16.1
sftp|lix|1.7.0
dotenv|mik|1.0.1
python|ms-|2018.9.1
azure-account|ms-|0.4.3
cpptools|ms-|0.19.0
sublime-keybindings|ms-|4.0.0
laravel-blade|one|1.18.0
laravel5-snippets|one|1.5.0
material-icon-theme|PKi|3.6.0
rewrap|stk|1.9.1
highlight-matching-tag|vin|0.6.2
markdown-all-in-one|yzh|1.6.2
html-css-class-completion|Zig|1.17.1

(3 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/3998
