### ISSUE TITLE
Variables view in debugger got stale

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#614]
Did the smoke test and debugged through some express code. The variables view in the debugger got stale. Couldn't close/open nodes in the tree. Variables didn't update. 

Couldn't reproduce a second time but showed to @weinand

**Comment by isidorn** [comment]
Did you see something in the console?

**Comment by dbaeumer** [comment]
Haven't checked. Sorry.

**Comment by isidorn** [comment]
If you see it again please check the console - there might have been duplicate ids in the tree and the tree usualy complains about this.

**Comment by isidorn** [comment]
Please reopen if you see it again with data from the console output.

**Comment by dbaeumer** [comment]
Nothing to verify since it doesn't reproduce and nothing got committed.
