### ISSUE TITLE
Automatic update breaks the application on OSX El Capitan

### ISSUE THREAD

**Issue by mariosangiorgio** [microsoft/vscode#61416]
I'm seeing the same symptoms described in #47941, but that issue has been closed and I cannot comment on there.

- VSCode Version: latest, but I've observed this issue for a few months now
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. install VScode
2. wait for an automatic update to happen
3. try to launch VScode again

Does this issue occur when all extensions are disabled?: Yes

It appears that automatic update breaks the Electron framework distributed with the app
```
~ code
dyld: Library not loaded: @rpath/libnode.dylib
  Referenced from: /Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
  Reason: image not found
/usr/local/bin/code: line 10: 66649 Trace/BPT trap: 5       ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"
```

Re-installing VScode fixes the issue, but it's quite annoying

**Comment by joaomoreno** [comment]
So... reinstalling the issue fixed it... but only until the next update?

Where do you usually place VS Code's app bundle?

**Comment by mariosangiorgio** [comment]
Yes, exactly. My app bundle is in `/Applications`, it should be a standard location

**Comment by joaomoreno** [comment]
@bpasero Have you seen this?

**Comment by bpasero** [comment]
@joaomoreno nope, first time

**Comment by joaomoreno** [comment]
I am clueless on this one. Can you reproduce it on other machines?

**Comment by mariosangiorgio** [comment]
Unfortunately this is the only machine I have available. #47941 suggests it happened also for at least someone else.

It also seems an Electron issue more than a Visual Studio Code specific issue. Have a look at this issue in the Atom repository https://github.com/atom/atom/issues/3093#issuecomment-327482918

At the moment I'm afraid there isn't much I can do, but I'll report back what happens the next time vscode tried to update itself.
