### ISSUE TITLE
Search in folder when Cmd/Ctrl+Shift+F is invoked on a folder in sidebar 

### ISSUE THREAD

**Issue by borekb** [Microsoft/vscode#61410]
When I press Cmd/Ctrl+Shift+F and a focus is currently on some folder in the Explorer sidebar, it would be nice to automatically scope the search to that folder. It's currently achievable by putting this to `keybindings.json`:

```
    {
        "key": "cmd+shift+f",
        "command": "filesExplorer.findInFolder",
        "when": "explorerViewletVisible && filesExplorerFocus"
    },
```

but I think it would be a nice little improvement to do that automatically.

**Comment by roblourens** [comment]
I think cmd+shift+f should just focus the viewlet in that case. Imagine if you press cmd+shift+e, then cmd+shift+f - you would be stuck searching in a folder, unless you grab the mouse to move the focus off a folder.

But, I would take a PR that adds this keybinding for cmd+alt+f (or something else reasonable) and something reasonable for windows.

**Comment by skprabhanjan** [comment]
@roblourens , can i work on this ?
If yes then some starter points would be helpful :)

**Comment by roblourens** [comment]
There is already a PR in progress, see just above your comment.
