### ISSUE TITLE
Accepting suggestions with semicolon is way too eager

### ISSUE THREAD

**Issue by Zarel** [Microsoft/vscode#61413]
Issue Type: <b>Bug</b>

I just typed:

```js
this.started = true
```

and pressed semicolon, and this autocompleted to:

```js
this.started = turnTicksLeft;
```

This is clearly massively undesirable.

The behavior is somewhat inconsistent; here it is happening:

![image](https://user-images.githubusercontent.com/551184/47261075-43563300-d48d-11e8-9ea4-bf5fe39ebda7.png)

And here it is, working just fine:

![image](https://user-images.githubusercontent.com/551184/47261071-389b9e00-d48d-11e8-8514-e0e7fa9fec24.png)

After screwing around, I couldn't get it to happen again. But I've definitely been pretty frustrated by semicolon completions so far.

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:07:48.477Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz (8 x 3700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|-psn_0_57358|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-pull-request-github|Git|0.2.1
sublime-commands|Zar|0.1.0

</details>

**Comment by Zarel** [comment]
https://github.com/Zarel/Pokemon-Showdown/blob/master/room-battle.js

is the file I was working on, in case it's useful.

**Comment by Zarel** [comment]
I just typed `this.checkActive(` and it autocompleted to `this.this.checkActive()`

Clearly there's something wrong with autocompletions.

**Comment by mjbvz** [comment]
You can disable semi-colon accept by setting: `"editor.acceptSuggestionOnCommitCharacter": false`

The part with `true` not showing up and `this.this.checkActive` sounds like #59848. If you have reliable repo steps please let me know
