### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by jacobweber** [Microsoft/vscode#61411]
Issue Type: <b>Performance Issue</b>

While editing in VSCode, I'm experiencing moments of very slow performance, which affect the whole machine — CPU usage goes up to 100%. After a few minutes it will usually go back to normal.

I'm running with all extensions disabled. I'm usually editing ReactJS projects when this happens, and running the create-react-app development server in the background.

I have a tsserver log and process sample from Activity Monitor, but I'd prefer not to post them here. Is there a way to submit them privately?

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

![screen shot 2018-10-20 at 2 00 40 pm](https://user-images.githubusercontent.com/542988/47260531-3a0b9d00-d472-11e8-8037-c4f2e93f9717.png)

**Comment by jacobweber** [comment]
@mjbvz Thanks -- I emailed them, since they were from an older session.

**Comment by pqvst** [comment]
I'm having a similar issue. Randomly my vscode started consuming 100% CPU. When I checked the process explorer, tsserver is consuming 100% CPU. Also, autocomplete has stopped working in my JavaScript project :/

**Comment by sheetalkamat** [comment]
Is it possible to try out drop from https://github.com/Microsoft/TypeScript/pull/28209 to see if that helps.

**Comment by jacobweber** [comment]
I have my `typescript.tsdk` pointing to a local build of that branch. I'll run with it for a few days and let you know how it performs.

**Comment by jonknowles** [comment]
Has anyone found a workaround for this issue?

**Comment by mjbvz** [comment]
@jacobweber Did you get a chance to test this?

**Comment by jacobweber** [comment]
So I've been running it for a couple weeks with this branch. I'd say the change (which seems to affect mostly the .cache files inside node_modules) feels like an improvement.

I'm still seeing high CPU usage in some cases from Code Helper, so I don't feel very confident about this. But it's been hard for me to narrow down the cause.

**Comment by sheetalkamat** [comment]
@jacobweber may be sharing tsserver log from when you see high usage can help us identify if there is any issue we can handle. 
You can upload logs using 
1. With "typescript.tsserver.log": "verbose" enabled
2. Restart vscode or vscode insiders
3. Reproduce the problem
4. Run ```code --upload-logs``` on the command line (or ```code-insiders --upload-logs``` if using vscode insiders) and follow instructions
5. Share the log file ID

**Comment by jacobweber** [comment]
Yep, will do if it happens again.

**Comment by daviesdoclc** [comment]
I'm seeing this same problem.  tsserver is running at 100% and I'm not even using TypeScript in my project.

**Comment by sheetalkamat** [comment]
@daviesdoclc Your logs show that you are using typescript@3.1.4 and not typescript@next. You need to set the vscode to use [typescript@next ](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Nightly%20Builds.md#visual-studio-code).

**Comment by daviesdoclc** [comment]
@sheetalkamat my project is not using typescript.  Is this something vscode is including?  If so, how do I change to @next ?

**Comment by sheetalkamat** [comment]
vscode uses typescript to power user experience of javascript. You can follow steps in https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Nightly%20Builds.md#visual-studio-code to install typescript@next and that link also has information on how to change vscode to use typescript nightly drop.

**Comment by jacobweber** [comment]
I'm okay with closing this -- overall I'm noticing far fewer slowdowns with the TS branch. I'll submit another issue if I see them again.

**Comment by jacobweber** [comment]
Seeing more of these issues -- I opened #65229.
