### ISSUE TITLE
Window snap does not reopen Code at the same size

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#6141]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows 10 (1440p resolution)

Steps to Reproduce:

1. Drag the Code window to snap left or right
2. Close and reopen Code

When snapped left, it reopens slightly smaller with extra space to the bottom and left and moves slightly right. When snapped right, it reopens slightly smaller with space left at the bottom and right sides.

**Comment by bpasero** [comment]
Not reproducible for me on my Windows 10.

**Comment by vsccarl** [comment]
Heres a gif. I can reproduce on 1080p and 1440p resolutions.

![snapresize](https://cloud.githubusercontent.com/assets/12900364/15080823/b8e86dae-1374-11e6-84c5-8d7006d3d970.gif)

**Comment by bpasero** [comment]
If in doubt, blame it on some Windows 10 version you are using ;)

**Comment by bpasero** [comment]
Bug clean up: please report back if this still reproduces.
