### ISSUE TITLE
Vs code file is not getting updated when i commit from git bash

### ISSUE THREAD

**Issue by gpamitranjit** [Microsoft/vscode#61428]
Issue Type: <b>Bug</b>

Vs code file is not getting updated when i commit from git bash...it is still showing that changes are not commited!!

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:15:15.139Z)
OS version: Windows_NT ia32 6.2.9200

**Comment by joaomoreno** [comment]
@gpamitranjit Does VS Code react to file events, otherwise? Eg. if you create a file in your workspace, outside of VS Code, does it show up in the explorer?
