### ISSUE TITLE
I want an account to retain the previously installed plug-in.

### ISSUE THREAD

**Issue by xwLyc** [Microsoft/vscode#61424]
I want an account to retain the previously installed plug-in.
So you do not need to change the computer to find plug-ins installed.

**Comment by scottymcraig** [comment]
I think he's talking about being able to sync extensions across computers so you have the same setup on each computer.  If so, this extension already exists:  [Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync)
