### ISSUE TITLE
Zen mode for terminal

### ISSUE THREAD

**Issue by loftusa** [Microsoft/vscode#61421]
Hey, it'd be cool to have a full-screen Zen mode terminal, much like the editor. 

Currently, the best I can figure out how to do is this, but it'd be cool to just be able to make the terminal completely full screen:

![full-screen-terminal](https://user-images.githubusercontent.com/12386450/47262352-b32be400-d4b4-11e8-8695-731e4c09e6b4.png)

**Comment by ddruker** [comment]
@loftusa This is an awesome idea. 

@Tyriar Is help wanted for this? Do you foresee any problems or gotchas?

**Comment by Tyriar** [comment]
No plans to add something like this anytime soon, however it may happen for free if terminals can be pulled out of the panel (see https://github.com/Microsoft/vscode/issues/10546)
