### ISSUE TITLE
white font suddenly become black

### ISSUE THREAD

**Issue by beanywang** [Microsoft/vscode#61427]
[Issue](url) Type: <b>Bug</b>
![untitled](https://user-images.githubusercontent.com/26607019/47264082-8bcf2880-d541-11e8-979c-8c3829927259.png)

all system level text color become black instead of white, e.g. in side bar, notification popup, menu bar and so on. since the theme is unchanged as default dark+, I cannot see the texts on the whole UI except the code (the fonts of codes are normal)

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (11.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
hive-sql|jos|0.0.4
python|ms-|2018.9.1

</details>

**Comment by Tyriar** [comment]
@beanywang doe the problem go away if you switch themes?

**Comment by beanywang** [comment]
@Tyriar Tried that for so many times. never work. black text are fixed and unchangeable. black text with white theme and black text with dark theme and black text with, well, any themes.
Actually, the software used to be normal on my machine, until I reseted the whole windows 10 first and then refresh the whole windows 10 secondly.
black text issue happens when I reinstall a fresh VS Code on my fresh os.
why me......

**Comment by bpasero** [comment]
We fixed this meanwhile. You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by beanywang** [comment]
@bpasero Thanks for your jobs! How soon will this fix packed into the stable build? is there a schedule? don't really want to install an extra preview build. I may just wait for an stable update.

**Comment by bpasero** [comment]
@beanywang in about 2 weeks

**Comment by beanywang** [comment]
@bpasero Nice.
