### ISSUE TITLE
Java cannot find symbol bug

### ISSUE THREAD

**Issue by alexandrugris** [Microsoft/vscode#61435]
Issue Type: <b>Bug</b>

I see a lot of cannot find symbol messages in the problems window although the application compiles, go to definition work and everything seems to run ok.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2720QM CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.36GB free)|
|Process Argv|-psn_0_45067|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
java-debug|DSn|0.0.2
python-docs|Muk|0.8.3
vscode-tomcat|ada|0.10.1
vscode-database|baj|1.5.2
vscode-markdownlint|Dav|0.20.0
xml|Dot|2.3.2
tslint|eg2|1.0.40
javac-linter|fau|1.3.1
clangcomplete|kub|1.0.1
python|ms-|2018.9.1
csharp|ms-|1.16.2
debugger-for-chrome|msj|4.10.2
vscode-docker|Pet|0.3.1
java|red|0.32.0
vscode-java-debug|vsc|0.14.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.10.0
vscode-maven|vsc|0.11.1
jinja|who|0.0.8
wilderminds-aspnetcore-snippets|wil|0.2.1

(1 theme extensions excluded)

</details>

**Comment by alexandrugris** [comment]
![image](https://user-images.githubusercontent.com/528256/47269022-c85e4c80-d560-11e8-9e87-6c20e81b407e.png)

**Comment by Tyriar** [comment]
https://github.com/redhat-developer/vscode-java
