### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by aviboot92** [Microsoft/vscode#61434]
Issue Type: <b>Bug</b>

My terminal doesn't display anything

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|15.92GB (8.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-babel-coloring|dza|0.0.4
beautify|Hoo|1.4.6
mssql|ms-|1.4.0
vsliveshare|ms-|0.3.834
open-in-browser|tec|2.0.0
lorem-ipsum|Tyr|1.2.0

</details>

**Comment by Tyriar** [comment]
What happens when you open the terminal? Can you post a screenshot?

Also could you settings.json file?

**Comment by onlineservices283418** [comment]
The same issue on Windows. It looks like this:
![terminal-bug](https://user-images.githubusercontent.com/29972256/47302052-2d7d7500-d629-11e8-99b7-84fd52a857e6.png)

**Comment by Aqours** [comment]
Same issue with 1.28.2
![qq 20181028140609](https://user-images.githubusercontent.com/8586286/47612726-49ff2e80-dabb-11e8-95c3-40df7743786f.png)

The path info does not show. It works fine when I input anything then press enter.

**Comment by romanoledergerber** [comment]
Same Issue Version 1.28.2

**Comment by onlineservices283418** [comment]
Guys please fix it. This issue is not a show stopper, but it's very annoying.
