### ISSUE TITLE
Updating workspace "files.exclude" does not seem to fully refresh views 

### ISSUE THREAD

**Issue by shoffmeister** [Microsoft/vscode#61437]
vscode allows excluding artefacts from a workspace using  the files.exclude setting, e.g.

		"files.exclude": {
			"somedir*": true
		}

When this setting is made, "somedir*" does in fact disappear from the list tree view that represents the workspace.

What does not happen, though is that "emphasized items" are not recomputed, that maven projects are not rescanned etc. After a restart of the IDE, the state of those views correctly reflects the exclusion intent.

Steps to reproduce (sort of):
* have directories with plenty of Java projects / maven inside a workspace
* have one of these Java projects presents issues (triggering emphasis)
* files.exclude -> the directory

//exp: directory dynamically disappears from view, emphasis disappears, maven project disappears from "Maven Projects" (Java extension)

//act: directory dynamically disappears from view

**Comment by isidorn** [comment]
Please file against the java extension that they should respec the files.exclude setting

**Comment by isidorn** [comment]
And what does exactly need to be fixed in the file explorer. Sorry that is not very clear for me from your initial comment

**Comment by shoffmeister** [comment]
Let me clarify: 
* update files.exclude
//exp: file-explorer dynamically updates itself
//act: file-explorer stays as it is

Cannot tell whether the Settings change is not broadcasted, or not reacted upon.

/// restart VS code
// expected view rendered
