### ISSUE TITLE
Crash when reordering file tabs

### ISSUE THREAD

**Issue by dbuksbaum** [Microsoft/vscode#61433]
Issue Type: <b>Bug</b>

If I drag reorder a tab, Code reports that the window has crashed and reopens

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz (8 x 3498)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.94GB (14.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (58)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
project-manager|ale|9.0.1
package-to-readme|ant|0.0.3
cform|aws|0.0.15
vscode-icontheme-nomo-dark|be5|1.3.6
vscode-node-readme|ben|3.0.2
file-templates|brp|1.2.0
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
gitignore|cod|0.5.0
vscode-markdownlint|Dav|0.20.0
vscode-eslint|dba|1.6.1
vscode-npm-source|dku|1.0.0
githistory|don|0.4.3
xml|Dot|0.2.0
xml|Dot|2.3.2
vscode-pandoc|Dou|0.0.8
vscode-generate-getter-setter|DSK|0.5.0
vscode-npm-script|eg2|0.3.5
vscode-great-icons|emm|2.1.44
terraform-autocomplete|erd|0.0.8
prettier-vscode|esb|1.6.1
git-project-manager|fel|1.7.1
vscode-npm|fkn|3.3.0
flow-for-vscode|flo|0.8.4
code-runner|for|0.9.4
beautify|Hoo|1.4.6
CreateModule|Hoo|0.0.5
rest-client|hum|0.20.2
open-folder-in-new-instance|jma|0.0.1
docthis|joe|0.7.1
docomment|k--|0.1.2
codeshell|Kip|0.2.2
terraform|mau|1.3.7
terraform-snippets|min|2.1.0
vscode-exec-node|mir|0.5.0
prettify-json|moh|0.0.3
mssql|ms-|1.4.0
python|ms-|2018.9.1
cpptools|ms-|0.19.0
csharp|ms-|1.16.2
Go|luk|0.6.78
node-debug2|ms-|1.29.0
PowerShell|ms-|1.9.0
vs-keybindings|ms-|0.2.0
debugger-for-chrome|msj|4.10.2
node-modules-resolve|nau|1.0.2
vscode-docker|Pet|0.3.1
vscode-versionlens|pfl|0.22.0
material-icon-theme|PKi|3.6.0
view-in-browser|qin|0.0.5
vscode-yaml|red|0.0.17
vscode-icons|rob|7.27.0
yo|sam|0.9.3
code-settings-sync|Sha|3.2.0
gitconfig|sid|2.0.0
tmlanguage|Tog|0.9.0
vscode-react-native|vsm|0.6.18

(3 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by dbuksbaum** [comment]
Hello Benjamin,

I have the DMP and log files. I have attached the log files. Do you want
the DMP as well?

Regards
David

**Comment by bpasero** [comment]
@dbuksbaum let's start with the log files. Also: 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
