### ISSUE TITLE
Extension Pack dependencies are not shown at all

### ISSUE THREAD

**Issue by paulvi** [Microsoft/vscode#61430]
Extention Pack dependencies are not shown at all in VSCode 1.28 and VSCode for Insiders

- VSCode Version: VSCode 1.28 and VSCode for Insiders
- OS Version: Windows 

Steps to Reproduce:

1. Open Extension view
2. see any extension details

**Comment by sandy081** [comment]
@paulvi Sorry what's the issue with continuing in discussion in #60718?

**Comment by paulvi** [comment]
This issue is that current VSCode versions do not show at all dependencies for extensions packs, as there is no such tab any more.

#60718 is/was issues/feature request that in that tab dependencies should be in form of tree to show subdependency.

**Comment by paulvi** [comment]
OK, the problem is not for VSCode but only for one extensions, so this is duplicate of https://github.com/Microsoft/vscode/issues/59684
