### ISSUE TITLE
Nothing's Happening

### ISSUE THREAD

**Issue by OlohimeAnnie** [Microsoft/vscode#6143]
- VSCode Version: 1.0.0
- OS Version: OS X Yosemite 10.10.5

<img width="806" alt="screen shot 2016-05-05 at 21 21 37" src="https://cloud.githubusercontent.com/assets/19213420/15056214/6051fd20-1308-11e6-91f1-4170440dd914.png">

So... nothing's happening. I downloaded the VSCode package and the icon showed up on my desktop. I double clicked and I guess it unarchived...? I moved the Visual Studio Code.app to my Applications folder. Basically, I did everything as I was supposed to. Whenever I try to open it though, the menu bar flickers to 'Code' but then it's back to Finder.  Saw this on the console. What's wrong? And what do I do? Heeelp.

**Comment by bpasero** [comment]
Weird. Can we try to launch it from the console to see if there are issues. cd into the application bundle into `Contents/MacOS` and then run `./Electron` and send the output here.

Also, are you maybe running as root user?

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
