### ISSUE TITLE
Create menu to work with git branches like in WebStorm

### ISSUE THREAD

**Issue by budarin** [Microsoft/vscode#61440]
To work with branches in VS Code like to be typewriter - every time you should to type git commands
You have the branch name place at the status bar - please use it for menu for branch manipulation like it has been done in WebStorm

**Comment by joaomoreno** [comment]
What actions around branches do you need/want?

**Comment by budarin** [comment]
Here is how WebStorm's git menu looks like

<img width="725" alt="default" src="https://user-images.githubusercontent.com/8055157/47313173-edc58600-d646-11e8-837f-5413c61613e4.png">

**Comment by joaomoreno** [comment]
Right, we also have quite a few commands for managing branches in VS Code:

![image](https://user-images.githubusercontent.com/22350/47319612-fba5e780-d603-11e8-8768-43c65aa4aa5b.png)

Please let me know if there's a specific command you're missing.

**Comment by budarin** [comment]
it is not usefull - it make me a lot of typing instead of running a command on dedicated branch

**Comment by budarin** [comment]
- checkout
- rename 
- delete
- merge into current

**Comment by joaomoreno** [comment]
We already support all those commands. We support keybinding customization to make you avoid the typing. We have some UI to reach them easily. There's not much more to do here.

**Comment by budarin** [comment]
these commands make me type ">git:<command>" while you have an interface element which does nothing but only opens command line. 
Using local menu on it is more UI/UX friendly than opening command line and typing a command

**Comment by joaomoreno** [comment]
You can configure keybindings to access those commands better.

You can also contribute an extension which simply adds those commands to any contributable menu in the UI.

**Comment by budarin** [comment]
of cause I can, but it takes me time to find accesible keybindings and then try to remember them from anothe tens of keybindings.

Good IDE gives functionality fo free and immediately and doesnt make a user to dance with configurations and memoisation those params

**Comment by budarin** [comment]
and here is another problem - with delete command I can operate only with local branches while in WebStorm I can point on any brunch in list and delete it with one click

So, using command line is not a panacea and should not be used everywhere - do use right UI pattern for every user's case

**Comment by joaomoreno** [comment]
> Good IDE gives functionality fo free and immediately and doesnt make a user to dance with configurations and memoisation those params

Actually, sorry for picking on this, but VS Code aims to be an editor first and an IDE second. We tend to have a strong preference towards being lightweight vs. having all the features in your face.

> I can operate only with local branches while in WebStorm I can point on any branch in the branches list and delete it with one click

Good point. That we lack.

> So, using command line is not a panacea and should not be used everywhere - do use right UI pattern for every user's case

I did not suggest to use the command line at all. This is why we already have commands in problems.

Thanks for understanding.
