### ISSUE TITLE
Support history of previous clipboard values 

### ISSUE THREAD

**Issue by ccirello** [Microsoft/vscode#6144]
- VSCode Version: 1.0.0
- OS Version: OS X 10.11.4

Steps to Reproduce:
1. type cmd+K cmd+v
2. it does not open an option like the below

![image](https://cloud.githubusercontent.com/assets/138827/15057022/2bf3ac80-12eb-11e6-88b2-5e5f479abe3f.png)

**Comment by DavidBabel** [comment]
+1

**Comment by roblav96** [comment]
@ccirello was this ever implemented by any chance? :X

**Comment by peabnuts123** [comment]
Why is this closed?

**Comment by mertdeg2** [comment]
+1 to @peabnuts123 

This sounds useful.

**Comment by peabnuts123** [comment]
Irrespective of the fact it seems like a nice feature to have. I am generally just confused as to why this issue was abruptly closed with no discussion

**Comment by DavidBabel** [comment]
On Mac OS "Alfred" is a good alternative. But native vscode muli clipboard is still a must have
