### ISSUE TITLE
Detect Indentation setting removes single space on indent

### ISSUE THREAD

**Issue by kwaschny** [microsoft/vscode#61442]
- VSCode Version: 1.28.2
- core setting, not extension related

![demo](https://user-images.githubusercontent.com/35005943/47269864-c649bd00-d563-11e8-9b6f-e8185e20313a.gif)

**Settings**
`Detect Indentation`: true
`Tab Size`: 4

**Description**
Indenting lines that contain a single space (within the indentation whitespaces) will remove the space, i.e. consider the space as part of an indent level.

**Background**
When minifying HTML output by removing all newlines, a single space is used to separate multiline attributes. Identing present code removes all spaces and breaks it as demonstrated in the above gif.

**Proposal**
Unless `Tab Size` is set to 1, a single space (within tabs) should not be considered as indentation level and stay untouched while the `Detect Indentation` mode is enabled.

**Comment by rebornix** [comment]
It's controlled by `editor.autoIndent`, which attempts to align the indentation when you do `Tab`. You can turn this option off if it doesn't work as needed.

**Comment by kwaschny** [comment]
@rebornix Did you test your proposal? Because `"editor.autoIndent": false` doesn't change the behavior.

**Comment by rebornix** [comment]
@kwaschny good catch ;) It should work with `"editor.autoIndent": false `.
