### ISSUE TITLE
Hold cmd & Q to quit on MacOS

### ISSUE THREAD

**Issue by bestvow** [Microsoft/vscode#61455]
just like chrome
![screen recording 2018-10-22 at 11 16 54](https://user-images.githubusercontent.com/24888709/47276774-37cd4e00-d5ec-11e8-9589-cf3ab542490d.gif)

**Comment by bestvow** [comment]
Only to prevent users misoperation caused close the editor.
Then close the issue please.

**Comment by weinand** [comment]
Since VS Code has hot-exit I do not see a strong need for this...
