### ISSUE TITLE
Horizontal Scroll stopped working @ version 1.28

### ISSUE THREAD

**Issue by vixson** [Microsoft/vscode#61450]
Issue Type: <b>Bug</b>

After an update to version 1.28, the horizontal scroll just stopped functioning normally

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.98GB (2.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
shaderlabvscodefree|aml|1.1.3
clipboard-history|Anj|1.0.7
cdn-list|Ary|1.0.0
color-info|bie|0.5.0
goto-documentation|cxf|0.0.1
jshint|dba|0.10.20
unity3d-pack|dim|1.0.0
line-counter|dol|0.5.2
es7-react-js-snippets|dsz|1.8.7
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.4.2
git-project-manager|fel|1.7.1
auto-rename-tag|for|0.0.15
markdown-preview-bitbucket|hbr|1.0.0
beautify|Hoo|1.4.6
minify|Hoo|0.3.0
jquery-snippets|Hri|1.0.0
vscode-postfix-ts|ipa|1.8.0
vscode-angular2-emmet|jak|2.0.3
fontawesome-autocomplete|Jan|0.1.7
docthis|joe|0.7.1
docomment|k--|0.1.2
unity-code-snippets|kle|1.2.2
csharpfixformat|Leo|0.0.76
vscode-html-format|moh|0.0.3
mssql|ms-|1.4.0
csharp|ms-|1.16.2
vs-keybindings|ms-|0.2.0
vscode-code-outline|pat|0.2.1
linesinfostatusbar|pet|0.0.3
material-icon-theme|PKi|3.6.0
esdoc-mdn|sam|0.6.0
bracket-jumper|sas|1.1.8
shader|sle|1.1.4
unity-tools|Tob|1.0.5
selectline-statusbar|tom|0.0.2
unity-debug|Uni|2.6.6
vscode-react-native|vsm|0.6.18
unity-snippets|Ycl|0.1.2
tslint-snippets|zuo|1.1.0

(2 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Do you mean inside the editor? How are you scrolling exactly?

**Comment by vixson** [comment]
> Do you mean inside the editor? How are you scrolling exactly?

Both inside the editor and the sidebar. Am still yet to discover more places that were affected.

**Comment by vixson** [comment]
It works for some time then stops.

**Comment by SanwariyaAmit** [comment]
Are you using a mouse (a Logitech one) or touchpad?

**Comment by vixson** [comment]
Please label this issue as a **Bug** on version 1.28.
Because I just downgraded back to version 1.27 and its working perfectly (scrolling horizontally).

**Comment by chsu2** [comment]
Hey! I noticed a horizontal scrolling error as well while splitting the editor. 

When splitting right, the horizontal scrolling of the new screen doesn't work. When you continue to split, the old screens scroll, but the new one loses the scrolling feature. 

So my initial screen (1) scrolls perfectly fine. Split the screens and make a new screen (2), the scrolling on 2 doesn't work. Open a third (3), the scrolling on 2 and 1 are okay. Close all the tabs in 2, the scrolling in 3 and 1 work. 

I'm using a touchpad for the scrolling 

let me know if you need any other details! And hopefully this makes sense

**Comment by joaomoreno** [comment]
@alexandrudima Funny how the user reports issues on both the tree and the editor. Any scrollbar changes largely?

**Comment by alexandrudima** [comment]
@joaomoreno Not that I am aware of, I am looking at https://github.com/Microsoft/vscode/commits/master/src/vs/base/browser/ui/scrollbar. Before October (and strict null checks), there is a change in July and another one in March... 

I cannot reproduce the issue, but the reports come in that it reproduces with the touchpad for `1.28.2` and not for `1.27`. That last change from July was already included in `1.27`. Perhaps an electron update?
