### ISSUE TITLE
Inconsistent Peek Definition behavior 

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#6145]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Highlight or put the cursor on a variable
2. Right click > Peek Definition
3. Right click again > Peek Definition

This will close the just opened Peek window. If you use the keybinding instead (Alt + F12) to open, pressing it again does nothing. It should be consistent one way or the other.

**Comment by jrieken** [comment]
The behaviour is consistent wrt to the editor selection. What happens to @vsccarl is that when doing a right click you likely change the editor position.

**Comment by vsccarl** [comment]
It closes even when clicking the same spot. Here's an example:
![peekexample](https://cloud.githubusercontent.com/assets/12900364/15081029/9802c0ca-1375-11e6-8dea-f77566087b2c.gif)

When it re-opens at the end, I press Alt+F12 a few times but it does not close.

**Comment by jrieken** [comment]
>  press Alt+F12 a few times but it does not close.

if you focus the outer editor, it does

**Comment by vsccarl** [comment]
That makes sense then.
