### ISSUE TITLE
Icons are back in the suggest widget used in Settings and Extensions search

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#61459]
Issue Type: <b>Bug</b>

In the September release, we updated the suggest widget to respect the `no-icons` class. See https://github.com/Microsoft/vscode/commit/ab002ec2eb105583d59144ff40692328dc0cb83d#diff-b1e324b56791c91ba94b301f2d739ea9

The recent  changes in the suggest widget for #44860 has caused a regression and brought the icons back when `no-icons` class is set on the widget.

VS Code version: Code - Insiders 1.29.0-insider (45d5d153bbebed743b77e426615aade34971eb46, 2018-10-19T06:50:39.461Z)
OS version: Darwin x64 15.6.0

**Comment by alexr00** [comment]
I still see icons in the Setting suggest widget:
![image](https://user-images.githubusercontent.com/38270282/47918437-ea36c800-deac-11e8-86cd-ce1751a49b0d.png)

**Comment by ramya-rao-a** [comment]
@alexr00 I meant the settings search 

<img width="646" alt="screen shot 2018-11-02 at 10 15 38 am" src="https://user-images.githubusercontent.com/16890566/47930130-44716200-de88-11e8-9fc2-f358dca22a9a.png">
