### ISSUE TITLE
Add option to change left margin in the tree of File Explorer

### ISSUE THREAD

**Issue by Lovecircle** [Microsoft/vscode#61462]
Please add option to the settings which would increase this margin, because it is very very hard to see which files are in which folder:

![redact](https://user-images.githubusercontent.com/6691153/47278191-9d5f1180-d5cf-11e8-8570-57e6c844cba2.png)

**Comment by isidorn** [comment]
https://github.com/Microsoft/vscode/issues/35447

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/35447
