### ISSUE TITLE
hope

### ISSUE THREAD

**Issue by hyl24lee** [Microsoft/vscode#61460]
![sublime3](https://user-images.githubusercontent.com/26035031/47277721-73b8e100-d5f5-11e8-90a5-9e5c4fd112a7.gif)
![vscode](https://user-images.githubusercontent.com/26035031/47277723-73b8e100-d5f5-11e8-9df3-3646fc7e0d83.gif)

**Comment by dseight** [comment]
Looks like an issue with font, not editor. Try to set the same font as on first picture.

**Comment by kumarharsh** [comment]
You're not using a monospace font in the vscode editor, that's why your brackets are not aligning.
