### ISSUE TITLE
Quick open should not leak keyup into the editor after close

### ISSUE THREAD

**Issue by vsccarl** [microsoft/vscode#6146]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows 10

Steps to Reproduce:
1. Click on a variable
2. F1 > Peek Definition

It looks like it brings up the peek window and also performs the go to definition command.

![peekcommandwindow](https://cloud.githubusercontent.com/assets/12900364/15059195/ba5029d8-12d5-11e6-80c0-9df18522752a.gif)

**Comment by bpasero** [comment]
Might be because quick open focusses the editor when it closes...

**Comment by jrieken** [comment]
@bpasero Is there anything special wrt <kbd>Enter</kbd>? When the command is invoked from the F1 palette the tree in the peek widget immediately receives an `onEnter` event which makes it jump to the declaration. Now I wonder where that event comes from

**Comment by bpasero** [comment]
Maybe F1 triggers the command onKeyDown and thus onKeyUp might go to the editor. Though if that is true I wonder why you do not end up with a newline in the editor for any other command?

**Comment by jrieken** [comment]
fixed by ce3fb81
