### ISSUE TITLE
VSCode not launching when FONTCONFIG_FILE env variable is set

### ISSUE THREAD

**Issue by 4O4** [Microsoft/vscode#61465]
- VSCode Version:
1.28.2
7f3ce96ff4729c91352ae6def877e59c561f4850
x64
- OS Version: Manjaro Linux KDE x64, kernel 4.19.0-1

Steps to Reproduce:

1. Set the FONTCONFIG_FILE to any value (it can be empty, it can point to existing or non-existing file - the result is the same) and run vscode: `env FONTCONFIG_FILE="" code --verbose`
2. VScode window does not appear and application exits. The output is:
```
[20538:1022/082947.661071:ERROR:sandbox_linux.cc(344)] InitializeSandbox() called with multiple threads in process gpu-process.
[main 8:29:47 AM] Starting VS Code
[main 8:29:47 AM] from: /opt/visual-studio-code/resources/app
[main 8:29:47 AM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  add: false,
  a: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  'open-url': false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': true,
  disableExtensions: true,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  issue: false,
  'skip-getting-started': false,
  'skip-release-notes': false,
  'sticky-quickopen': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'skip-add-to-recently-opened': false,
  status: false,
  s: false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  trace: false }
[main 8:29:47 AM] Resolving machine identifier...
[main 8:29:47 AM] Resolved machine identifier: <CUT>
[main 8:29:47 AM] update#setState idle
xdg-mime: application argument missing
Try 'xdg-mime --help' for more information.
[main 8:29:48 AM] windowsManager#open
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
How did you install vscode?

**Comment by 4O4** [comment]
I've installed it from AUR package `visual-studio-code-bin`. You can see the PKGBUILD here: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=visual-studio-code-bin
This is basically an automated installation script which downloads the official Linux build and unpacks it to the filesystem.

**Comment by Tyriar** [comment]
This issue originates from electron, you can check if it repros on the latest release and create an issue here if you want https://github.com/electron/electron
