### ISSUE TITLE
Please, add short key to fold/unfold everything in the selected text.

### ISSUE THREAD

**Issue by Lovecircle** [Microsoft/vscode#61463]
Let's say I carefully organized my code for folding and then folded all of it by clicking Ctrl K Ctrl 0. Now, if I want to focus my work only on some function - I have to unfold every level inside my function by hand instead of just selecting folded block and unfolding all code inside the selection - clicking by a short key.

It is very inconvenient, given that aforementioned function usually has 6 or more level of folding - because every "if", "foreach" and so on statement is automatically folded if properly formatted.

**Comment by aeschli** [comment]
Did you try `Unfold Recursively`?
- set the cursor on function which is folded or has folded blocks
- invoke `Unfold Recursively`

**Comment by Lovecircle** [comment]
Thank you! This is exactly what I needed.
