### ISSUE TITLE
Inline diff view removed lines (red) are smaller font than changed (green) lines.

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#6147]
- VSCode Version:1.1.0-alpha
- OS Version:Windows10, OS X

Steps to Reproduce:

1. Set "diffEditor.renderSideBySide": false
2. Look at a git diff.

The red removed lines are smaller (Segoe WPC, SegUI 13px) while the changed lines (green) match the rest of the editor font and size.

This is poor for looking at inline diffs since the changed characters are no longer directly lined up above and below each other.

Does not repro on 1.0-stable

**Comment by gregvanl** [comment]
Does not repro on latest insiders so this is a recent regression.

**Comment by alexandrudima** [comment]
@gregvanl Thank you for spotting this!
