### ISSUE TITLE
Makefile: != operator not recognized by syntax highlighting

### ISSUE THREAD

**Issue by burianvlastimil** [Microsoft/vscode#61475]
- VSCode Version:
```
Version: 1.28.2
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:20:56.183Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```
- OS Version:

Linux Mint 19 Cinnamon
 ```
$ uname -s; uname -m; uname -r
Linux
x86_64
4.15.0-36-generic
```
Steps to Reproduce:

1. Open a Makefile
2. Type:
```
variable_name != value_assigned_by_shell__some_command
```

Does this issue occur when all extensions are disabled?: Yes

Note:
- this operator (!=) is available in both GNU and BSD make

I attach a sample:

![vscode != operator not recognized by syntax highlighting ](https://i.imgur.com/Cqz3Aka.png)

**Comment by aeschli** [comment]
This issue was moved to fadeevab/make.tmbundle#2
