### ISSUE TITLE
Search > Files to Include/exclude: Path suggestions

### ISSUE THREAD

**Issue by flpwgr** [Microsoft/vscode#61487]
Hello all!

I was wondering if it is possible to add the possibility to suggest completions for the directories in the file to include/exclude box... 

e.g:

If I start typing `src-js/` I can hit ctrl+space it should suggestions to autocomplete directory name assuming `.` as the root of the project.. something like the following screenshot below

![screenshot 2018-10-22 at 14 27 47](https://user-images.githubusercontent.com/1329042/47292262-b800ad00-d606-11e8-9329-4e779c0be4d2.png)

**Comment by mjbvz** [comment]
This is already supported. What is your project structure? Do you have a jsconfig.json?

**Comment by flpwgr** [comment]
Oh, just saw that in the options... I don't use any `jsconfig.json` only tsconfig, but I guess this should not affect that.
