### ISSUE TITLE
Replace All across multiple files overwrites all targeted files with the same code

### ISSUE THREAD

**Issue by Flimetta** [Microsoft/vscode#61488]
Version: 1.28.1 (user setup)
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
Windows: 10

Steps to Reproduce:

1. Use the find & replace tool to find a term found in multiple files 
2. Enter your term in the "Replace" field
3. Press the "Replace All" icon

**Issue**: the code from one of the target files is copied and overwritten into all the other files.
So if the find & replace tool lists:
```
style1.scss
style2.scss
style3.scss
```
... and I press "Replace All", the code from `style1.scss` will be overwritten into` style2.scss` and `style3.scss`.

**Comment by roblourens** [comment]
Can you give a more specific example? I haven't seen this before and I'm not sure exactly what you mean when you say "the code from style1.scss will be overwritten into ..."
