### ISSUE TITLE
Allow terminal view to take the whole width (under sidebar and content)

### ISSUE THREAD

**Issue by edimitchel** [Microsoft/vscode#61481]
I'm working on a vertical screen in order to getting terminal in the bottom (with a height of 2/5 of the screen height).
I set the side bar on the right, it's great, I love it, but I would like to get my terminal under it..

**Currently I have this :** 

![image](https://user-images.githubusercontent.com/2922851/47290511-2aba5a00-d600-11e8-893c-0312a7a1eac6.png)

**And I would like to have this:**

![image](https://user-images.githubusercontent.com/2922851/47290583-7836c700-d600-11e8-8f3e-de926766ac40.png)

**Is this already possible ? Otherwise, can this feature be created ?**

**Comment by j0hnm4r5** [comment]
I think this is a duplicate of #42149, but this issue has a much better description.
