### ISSUE TITLE
Intellisense crashing/not working correctly

### ISSUE THREAD

**Issue by TincanPipPip** [Microsoft/vscode#61480]
- VSCode Version: 1.28.2
- OS Version: Win 10 x64

Cannot nail down steps to reproduce, but since recent updates, I've noticed that intellisense will stop suggesting anything when typing on various filetypes (e.g. JS, SASS, twig/html). Restarting VSCode will fix the issue, but until that's done no suggestions will be presented when writing any code.

**Comment by mjbvz** [comment]
Does this reproduce with all extensions disabled?
