### ISSUE TITLE
bug appears when open a special file

### ISSUE THREAD

**Issue by thinkermao** [Microsoft/vscode#6148]
- VSCode Version: 1.0.0
- OS Version: Windows 10 

![image](https://cloud.githubusercontent.com/assets/7908062/15062435/a1899e0a-1372-11e6-8787-1aed1201c3ab.png)

![image](https://cloud.githubusercontent.com/assets/7908062/15062449/bee89b04-1372-11e6-9358-606023d9b96f.png)

Steps to Reproduce:

1. Create a file that contains spaces, such as "reproduce bug.md".
2. In the context menu, select "Edit with code".
3. Now, you will find the filename is divided into two parts -- (reproduce, bug.md), and displays two files in splitted screen 

But, code will open file normally if I just double-click file instead of select from context menu.

**Comment by joaomoreno** [comment]
Fixed since.
