### ISSUE TITLE
Allow retrying failed task detection

### ISSUE THREAD

**Issue by the-ress** [Microsoft/vscode#61499]
It would be nice to have a command to retry failed task detection.

This happens often:
1. Gulp task detection fails
2. I fix the issue (usually by running `npm install`)
3. Now I have to reload window to retry

**Comment by dbaeumer** [comment]
Actually the gulp task detection should handle this and re-compute the tasks on changes to the `node_modules` folder.

**Comment by dbaeumer** [comment]
@alexr00 that would expose you to the task API client side. The code is here: https://github.com/Microsoft/vscode/blob/master/extensions/gulp/src/main.ts#L6

**Comment by dbaeumer** [comment]
@alexr00 we might want to consider merging this in in November to not invalidate testing.

**Comment by roblourens** [comment]
How should this work?

- I open a folder with a gulpfile and no node_modules
- Tasks aren't detected
- I run `npm install`
- "Run Task" -> Still no tasks found

**Comment by alexr00** [comment]
@roblourens, I can't reproduce this. Things I've tried:
- delete node_modules folder -> no gulp tasks, npm install -> gulp tasks
- remove npm scripts from package.json -> only task is now npm install, run npm install -> gulp tasks
- remove package.json -> no tasks found, add package.json and npm install -> gulp tasks
Was your package.json missing a dependency on gulp maybe?

**Comment by roblourens** [comment]
So this worked as expected in another repo I tried, but I am trying in this random repo where it didn't work: https://github.com/Microsoft/vscode-edge-debug

![image](https://user-images.githubusercontent.com/323878/49605053-5ee5a200-f944-11e8-925b-17390a123f95.png)

**Comment by roblourens** [comment]
vscode-edge-debug has native dependencies and `npm install` took a long time. Maybe task detection was triggered too early before gulp was actually installed. I don't know what the file watcher is looking for exactly.

**Comment by alexr00** [comment]
Hm, we just watch for changes to the node_modules folder. I'll look at that repo and see what's going on. Thank you!

**Comment by alexr00** [comment]
This appears to be a problem with tasks 0.1.0. I updated the tasks.json in vscode-edge-debug to use 2.0.0 and detection of gulp tasks after `npm install` worked. Since 0.1.0 is deprecated the solution is to move to 2.0.0 :)

    {
        "version": "2.0.0",
        "tasks": [
        {
                "label": "Watch",
                "type": "gulp",
                "task": "watch",
                "group": "build",
                "isBackground": true,
                "problemMatcher": [
                    "$tsc"
                ]
            },
            {
                "label": "Watch-Build-Test",
                "type": "gulp",
                "task": "watch-build-test",
                "isBackground": true,
                "group": "test"
            }
        ]
    }
