### ISSUE TITLE
[Bug] Javascript reformat auto remove semicolon?

### ISSUE THREAD

**Issue by nampdn** [Microsoft/vscode#615]
When I reformat code in VS Code, all of my statements, functions automatically remove the semicolon, then the IDE notify me to add it again. Is this a bug?

**Comment by jrieken** [comment]
You can configure for JavaScript whether missing semicolons are allowed or not.

**Comment by nampdn** [comment]
I didn't find any options to set it.

`"javascript.validate.lint.missingSemicolon": "ignore"` This is for validate, not for reformat code option.

Could you please show me how to configure it?

**Comment by nampdn** [comment]
Why this issue was closed why it has not been solved?

**Comment by jrieken** [comment]
This issue was closed because I assumed you talk about the lint rule. That is because the formatter should not insert `;` ever. Please provide *detailed* steps that allow me to reproduce this

**Comment by nampdn** [comment]
1. Open VS Code.
2. Open my project folder.
3. Open my .js file.
4. Press `Shift + Alt + F`, then VS Code automatically format the code. Only one issue is all of my statements that already has `;` before was removed. I don't want the IDE remove my semicolon in each statement by formatting the code.

**Comment by jrieken** [comment]
@nampdn Please provide a sample of your code

**Comment by nampdn** [comment]
Before:
`console.log("Hello");`
After reformat:
`console.log("Hello")`

**Comment by jrieken** [comment]
Sorry, but that are just not sufficient steps: 
![format](https://cloud.githubusercontent.com/assets/1794099/11419197/09c58bcc-9426-11e5-9460-780f3163877b.gif)

**Comment by nampdn** [comment]
How about this, I have no idea why?
![issue](https://cloud.githubusercontent.com/assets/15364911/11419436/ce95c84e-9459-11e5-9ac7-66dac1db9b1d.gif)

**Comment by nampdn** [comment]
Sorry, I got the solution, It is because this extension : https://marketplace.visualstudio.com/items/chenxsan.vscode-standard-format
I try to remove every plugin and retry.
Thanks for your support!

**Comment by felipequiroz** [comment]
I had the same problem and uninstall the extension: solved.
A rule of "JavaScript Standard Style" indicates "No semicolons": http://standardjs.com

**Comment by dadvir** [comment]
I'm amazed!!! This happened to me and my whole code became a mess!!! This plugin ruined my life!

**Comment by SiriusGuo** [comment]
OMG! I have uninstall vscode because of it! I thought vscode did it so sad...my fault!
