### ISSUE TITLE
Translation of `Change All Occurrences` to Chinese not correct

### ISSUE THREAD

**Issue by innerlee** [Microsoft/vscode#6150]
- VSCode Version: 1.1.0-insider
- OS Version: win 10

`Occurrences` => `事件` is wrong. It means `event, incident` in Chinese.
`出现` or `地方` or something else might be appropriate.

![bug](https://cloud.githubusercontent.com/assets/9464825/15063928/0c000a54-1381-11e6-8592-6969d7a71a28.PNG)

**Comment by johnliu2016** [comment]
@lukaschal please sent suggested translation to review

[findController.nls.resx.lcl](https://monacotools.visualstudio.com/DefaultCollection/Monaco/_git/MonacoLocalization?path=%2FLocalize%2Fchs%2Fvscode%2Fsrc%2Fvs%2Feditor%2Fcontrib%2Ffind%2Fcommon%2FfindController.nls.resx.lcl&version=GBmaster&_a=contents)

      <Item ItemId=";changeAll.label" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[Change All Occurrences]]></Val>
          <Tgt Cat="Text" Stat="Loc" Appr="PreApproved" Orig="New">
            <Val><![CDATA[更改所有事件]]></Val>
          </Tgt>
        </Str>
        <Disp Icon="Str" />
        <Modified By="ICizkova" DateTime="2016-03-10T16:02:41Z" />
      </Item>

**Comment by lukaschal** [comment]
Waiting for linguistic input.

**Comment by lukaschal** [comment]
New translation implemented.

File: src\vs\editor\contrib\find\common\findController.nls.resx
ID: ".resx", 0; "changeAll.label"
SRC: Change All Occurrences
TGT: 更改所有匹配项
