### ISSUE TITLE
terminal doesn't show path when open

### ISSUE THREAD

**Issue by cl1107** [Microsoft/vscode#61502]
- VSCode Version:1.28.2
- OS Version:win10 1809 17763.55

Steps to Reproduce:

1.when i open the vscode then press ctrl+` to open terminal ; the terminal show like this picture.there is no path but i can type sth.
![image](https://user-images.githubusercontent.com/21985353/47299960-f79eb780-d64d-11e8-9028-f5ce89f2eaa8.png)
![image](https://user-images.githubusercontent.com/21985353/47299986-05ecd380-d64e-11e8-969e-af069cb04750.png)
2.when i press enter it can show normal
![image](https://user-images.githubusercontent.com/21985353/47300160-68de6a80-d64e-11e8-9da0-c8dd86b8872f.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/57803
