### ISSUE TITLE
Tabs list on several rows

### ISSUE THREAD

**Issue by ThomasPerraudin** [Microsoft/vscode#61508]
We need to work with several files at the same time, dispersed in several folders of the projects.
That makes a lot of open tabs but all in only one row. That's pretty annoying to have to scroll left and right. Considering the size of each project the Explorer is not of a great help.
It would be very helpful to be able to display open tabs on several rows.

**Comment by usernamehw** [comment]
`"workbench.editor.tabSizing": "shrink",` - not what you asking for, but still...

**Comment by ThomasPerraudin** [comment]
@usernamehw still helpful ... thank you

**Comment by ThomasPerraudin** [comment]
Yes I think this issue is crucial. How to work efficiently if you can’t access tour files easily ?

**Comment by dpope-atlassian** [comment]
Also considered previously with more votes there: https://github.com/Microsoft/vscode/issues/32836

There's at least some level of interest here.
