### ISSUE TITLE
Slow and Ugly font in Ubuntu 18.10

### ISSUE THREAD

**Issue by sbahmani** [Microsoft/vscode#61506]
After upgrade to Ubuntu 18.10, vscode run very slowly and default font is not look like 18.04.

**Comment by Tyriar** [comment]
Please see https://github.com/Microsoft/vscode/wiki/Performance-Issues for creating actionable performance issues

**Comment by shino47** [comment]
I recently upgraded to Ubuntu 18.10 and had the same issues. The solutions are the following:

**For the slow startup**
If you installed Code from Ubuntu Software Center, uninstall it and install the deb package from the Code website. The one in the Software Center is a snap package and there are many performance issues reported on snaps.

**For the ugly font**
The default value for editor font family is `'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'`. It seems that Droid Sans Mono has been removed in this version of Ubuntu, but Droid Sans Fallback is still present. You can change this value to:
```'Droid Sans Fallback', 'monospace', monospace```

or in my case, switch to DejaVu Sans Mono: 
```'DejaVu Sans Mono','monospace', monospace```

**Comment by joaomoreno** [comment]
Snap issues: https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Asnap
