### ISSUE TITLE
Regression: problem matcher in extension not showing up 

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#61513]
Issue Type: <b>Bug</b>

I have a [problem matcher extension](https://marketplace.visualstudio.com/items?itemName=eamodio.tsl-problem-matcher) in the marketplace that contributes 4 matchers: `$ts-webpack`, `$tslint-webpack`, `$ts-webpack-watch`, and `$tslint-webpack-watch`. All of which are available for use in vscode 1.28.2, but not in 1.29. In 1.29 `$ts-webpack-watch` and `$tslint-webpack-watch` are missing, and I see the following in the `tasks` output channel:

```
Error: Invalid problemMatcher reference: $ts-webpack-watch

Error: Invalid problemMatcher reference: $tslint-webpack-watch

Error: the description can't be converted into a problem matcher:
{
    "base": "$ts-webpack-watch",
    "applyTo": "closedDocuments",
    "fileLocation": "absolute"
}

Error: the description can't be converted into a problem matcher:
{
    "base": "$tslint-webpack-watch",
    "applyTo": "closedDocuments",
    "fileLocation": [
        "relative",
        "${workspaceFolder}/../codestream-lsp-agent/"
    ]
}

Error: Invalid problemMatcher reference: $ts-webpack-watch

Error: Invalid problemMatcher reference: $tslint-webpack-watch
```

This *might* be related to this: https://github.com/Microsoft/vscode/issues/56721

FYI the code for the extension is here: https://github.com/eamodio/vscode-tsl-problem-matcher

/cc @dbaeumer 

VS Code version: Code - Insiders 1.29.0-insider (4d9f1d23a556dccd2c0fd5203923a24b21e41209, 2018-10-22T05:18:34.128Z)
OS version: Windows_NT x64 10.0.18262

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (18.32GB free)|
|Process Argv|C:\Users\Eric\code\codestream\vscode-codestream\codestream.code-workspace|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by dbaeumer** [comment]
@eamodio thanks for catching this.

@alexr00 we broke this when adding the strict null support :-(. See change set for the fix.

**Comment by dbaeumer** [comment]
https://github.com/Microsoft/vscode/commit/935d366c6e2ea72cf6701b37501c7c235d3ef92f
