### ISSUE TITLE
"Split Terminal" in workspace is opening incorrect directory

### ISSUE THREAD

**Issue by martellaj** [Microsoft/vscode#61515]
Issue Type: <b>Bug</b>

1. Be in a workspace with 2+ directories.
2. Open terminal.
3. Click "Split Terminal".
4. Choose a directory.

Expected: Directory I chose is opened in a split terminal.
Actual: Directory I didn't choose is opened in a split terminal.

![wrong terminal](https://user-images.githubusercontent.com/1019478/47307355-b07bdc80-d5e3-11e8-8cc9-9dae2b0123a6.gif)

VS Code version: Code - Insiders 1.29.0-insider (4d9f1d23a556dccd2c0fd5203923a24b21e41209, 2018-10-22T05:18:34.128Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.79GB (16.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
snapshot-tools|asv|0.2.2
bracket-pair-colorizer|Coe|1.0.60
gitlens|eam|8.5.6
tslint|eg2|1.0.40
prettier-vscode|esb|1.6.1
sort-typescript-imports|mic|1.4.1
csharp|ms-|1.16.2
debugger-for-chrome|msj|4.10.2
polacode|pnp|0.2.2
vscode-icons|rob|7.27.0
partial-diff|ryu|1.4.0
vscode-todo-highlight|way|1.0.4

(2 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
@alexr00 do we not suppress the multi-root choose dialog based on the new setting?

**Comment by alexr00** [comment]
Thank you for catching!

**Comment by nahuelhds** [comment]
Just for you to know.
The "new terminal" button works correctly now. That's fixed.
But if I try to open a new pane with the "Split terminal" command keeps happening what is reported in here.

**Comment by alexr00** [comment]
Yes, once @Tyriar has taken a look at #61584(which fixes this) I will merge it in.

**Comment by martellaj** [comment]
@alexr00 @Tyriar This regressed even more now. Doing split terminal doesn't even give the option of what directory to open. It just opens a second terminal of the same project. Is this expected? Prior to the original change, clicking "split terminal" gave me an option - which seems like the best UX to me.
