### ISSUE TITLE
Find in files

### ISSUE THREAD

**Issue by richardlhughes** [Microsoft/vscode#61516]
Issue Type: <b>Bug</b>

FIND: ">\n\s\s\s\s\s\s (using regex)
FILE TO INCLUDE: *.sqlproj

Literal '\n' currently not support.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (3.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.3
xml|Dot|2.3.2
gitlens|eam|8.5.6
mssql|ms-|1.4.0
cpptools|ms-|0.19.0
csharp|ms-|1.16.2
PowerShell|ms-|1.9.0
team|ms-|1.142.0
gitflow|vec|1.2.1

</details>

**Comment by roblourens** [comment]
Implemented for October in #13155

**Comment by Silent47** [comment]
> Implemented for October in #13155

I love Insiders edition!
It works well!
