### ISSUE TITLE
The border of scroll bar is ugly, and unclear under high dpi

### ISSUE THREAD

**Issue by be5invis** [Microsoft/vscode#6151]
![image](https://cloud.githubusercontent.com/assets/240091/15066070/a6545b02-1398-11e6-94b0-72c40e430135.png)![image](https://cloud.githubusercontent.com/assets/240091/15066084/c53dbf36-1398-11e6-93e1-4885e92937df.png)

**Comment by alexandrudima** [comment]
@be5invis I'm not sure if I'm just used to it, but to me it is not obvious what is ugly about it :). Is it the color or the fact that it exists?

It is also not really a border, it is a 1px width line drawn inside a canvas element and I'm thinking Chromium is not doing such a good job in scaling canvas elements when the OS zoom level is different than 100%.

**Comment by be5invis** [comment]
@alexandrudima Chromium does scale canvases, but this scaling is not like scaling other elements, it will cause the contents blur.
Many programmers around me, including me, prefer that removing this border will make the UI look better.

**Comment by carlosdwilson** [comment]
I can confirm this bug is present in VSC Version 1.1.1-insider.

I have a 15.4 inch display with a resolution of 2880 x 1800. As mentioned, all decorations (cursor position, selection highlights, etc.) in the overview ruler are blurry. VSC renders everything else crisp and perfect. Thanks.

**Comment by alexandrudima** [comment]
Thanks to http://stackoverflow.com/a/15666143 that shows nicely how to avoid having the browser scale up the canvas (render the canvas at the final pixel resolution), here is a before & after with `"window.zoomLevel": 5`


## BEFORE
![image](https://cloud.githubusercontent.com/assets/5047891/15475687/91cfaa9e-210b-11e6-83eb-e8f7df28fd89.png)

## AFTER
![image](https://cloud.githubusercontent.com/assets/5047891/15475719/bad8b39a-210b-11e6-87da-ecf40d876da5.png)
