### ISSUE TITLE
Crash after create a new file

### ISSUE THREAD

**Issue by markuspxpx** [Microsoft/vscode#61514]
Issue Type: <b>Bug</b>

Sometimes when I create a new file inside some folder of project, the VS Code simply freezes, then I change the tab ( the filed open ) to another and VS backs to normal, but when I click on tab of this new blank file to write the code, it simply freezes again and then crash.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (1.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
expressjs|ama|2.0.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.6.1
EditorConfig|Edi|0.12.5
vscode-npm-script|eg2|0.3.5
code-runner|for|0.9.4
search-node-modules|jas|1.3.0
node-module-intellisense|lei|1.5.0
mssql|ms-|1.4.0
vscode-docker|Pet|0.3.1
gitblame|wad|2.5.0
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.7.1

</details>

**Comment by weinand** [comment]
It is possible that this issue is caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces.
