### ISSUE TITLE
async await color highlighting not matching

### ISSUE THREAD

**Issue by EddyVinck** [Microsoft/vscode#61511]
![image](https://user-images.githubusercontent.com/23434753/47305257-31a99280-d629-11e8-9041-1fae9c712415.png)

- VSCode Version: 1.28.1
- OS Version: Ubuntu 18.04

Does this issue occur when all extensions are disabled?: Yes
![image](https://user-images.githubusercontent.com/23434753/47305435-b8f70600-d629-11e8-9eeb-bba591cbd843.png)

**Comment by vigzmv** [comment]
This is related to theme being used and not a bug in VSCode.

**Comment by EddyVinck** [comment]
Installing the following extension fixed it. https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar
