### ISSUE TITLE
Cannot disable unknown suggestion popup

### ISSUE THREAD

**Issue by erindotio** [Microsoft/vscode#61529]
Issue Type: <b>Bug</b>

Steps:

- Create a javascript file meant to contain styles for a React Native component.
- Add example code:
```
const styles = StyleSheet.create({
  style: {
    display: 'flex',
  },
});
```
- put cursor on the coma after 'flex'
- delete comma, then retype the comma

Result:
- This popup appears:
![screen recording 2018-10-22 at 12 52 pm](https://user-images.githubusercontent.com/1291167/47319813-a7a7fc80-d61d-11e8-8319-6fab488726a5.gif)
- The popup changes to the second one in the above gif after hitting the Enter key

Expected:
A way to disable this popup.

I have tried disabling all extensions, disabling all custom user settings, and adding back in these settings:
```
  "editor.quickSuggestions": {
    "other": false,
    "comments": false,
    "strings": false
  },
  "javascript.suggestionActions.enabled": false,
  "javascript.suggest.autoImports": false,
  "typescript.suggest.autoImports": false,
  "typescript.suggest.completeFunctionCalls": false,
  "typescript.suggest.enabled": false,
  "typescript.suggest.paths": false,
  "javascript.suggest.paths": false,
  "typescript.suggestionActions.enabled": false,
  "typescript.validate.enable": false,
  "javascript.validate.enable": false,
  "editor.wordBasedSuggestions": false,
  "editor.suggestOnTriggerCharacters": false,
  "editor.parameterHints.enabled": false,
```
...none of which seem to disable this popup.

I would love to understand how to disable this as it's quite frustrating to have to escape out of it after every line ending with a comma. I think it's maybe it's typescript validation thing? I'm not entirely sure.

Thanks

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|16.00GB (0.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by burtek** [comment]
Doesn't <kbd>Esc</kbd> work for hiding popup? Works for me

**Comment by mjbvz** [comment]
The `,` triggering this popup should be fixed in the latest VS Code builds. If you do trigger the parameter hints popup (which will still happen when you write out ` StyleSheet.create(`), you can hide it by pressing `esc` as @burtek suggests
