### ISSUE TITLE
Quick open can have duplicate entries with different path casing

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#6152]
I am getting duplicate `debugViews.ts` in recently opened. Both point to the same file, however they seem to have a different editors associated with them - eg selections are different.
Not sure how I got in this state, but I this is the first time I get duplicate entires. So my suspicion is that at a point of time the workbench created an additional editor for a file that was already open

![screen shot 2016-05-06 at 09 29 50](https://cloud.githubusercontent.com/assets/1926584/15066920/217ed0e0-136d-11e6-8f8d-490d2051f5dd.png)

**Comment by bpasero** [comment]
@isidorn could be the same file with different casing because you sometimes seem to vary with your workspace path.

**Comment by bpasero** [comment]
Just Cmd+K W the one file to get rid and File -> Open Recent -> Clear Items to get rid of all your duplicate workspace paths with different casing.

**Comment by bpasero** [comment]
With the update to Electron 1.2.6, `fs.realPath` now returns the right casing so this issue should not happen anymore.

**Comment by isidorn** [comment]
Hoooooray for `fs.realPath`

**Comment by bpasero** [comment]
This landed.

**Comment by bpasero** [comment]
Reopening because it looks like node.js 6.4.0 will revert the nice fs.realpath to go back to the previous JS implementation and behaviour.

**Comment by bpasero** [comment]
Merging into https://github.com/Microsoft/vscode/issues/12448
