### ISSUE TITLE
SOURCE CONTROL: No source control providers registered

### ISSUE THREAD

**Issue by tornPiece** [Microsoft/vscode#61522]
Hello,

i struggle to get ms code (1.28.2) working with git (2.19.1.windows.1) on windows 10 Pro (1803). As of now i only get  _'SOURCE CONTROL: No source control providers registered'_ in the source control view.
There are many threads about other users having the same problem, but the solutions mentioned there didn't help in my case. 

First try:
- I installed git from _https://git-scm.com/download/win_ 
- I added _C:\Git\cmd_ to the windows path manually (As the git install didn't)
- git is working fine with _git --version_ on cmd. 
- I restarted windows
- I installed MS Code from https://code.visualstudio.com/download
- Started ms code and I get _'SOURCE CONTROL: No source control providers registered'_ 

Second try:
- I added the git.exe path manually to the ms code user settings
```
{
    "git.path": "C:\\Git\\cmd\\git.exe",
    "git.enabled": true
}
```
- Closed ms code, restarted the system
- Started ms code again and still _'SOURCE CONTROL: No source control providers registered'_ 

I also checked process.env.Path in the dev tools of ms code
Result: `...pData\Roaming\Composer\vendor\bin;C:\Git\cmd;C:\Users\Lorem Ipsum\AppData\Local\Programs\Microsoft VS Code\bin"`

I have no more ideas. 

Please help. 

![clipboard01](https://user-images.githubusercontent.com/31355249/47320202-08046180-d651-11e8-9f2a-c4865222a180.jpg)

![clipboard02](https://user-images.githubusercontent.com/31355249/47313817-3463b200-d640-11e8-84c8-5b66d75cc3b5.jpg)

**Comment by joaomoreno** [comment]
Can you show me the output from `Git: Show Git Output`?

**Comment by tornPiece** [comment]
I read the suggested Ticket and checked the status of the build in git extension. It's not disabled.
Also I checked the extension logs that does not mention the git extension at all. 
![clipboard01](https://user-images.githubusercontent.com/31355249/47319974-63821f80-d650-11e8-8cfe-3885453ec55c.jpg)

**Comment by joaomoreno** [comment]
Have you tried opening a folder which is a git repository?

**Comment by tornPiece** [comment]
Ok, i opened a folder in the explorer view that was already under git control and magically ;) the source control view came to live. Conclusion: Git war setup correctly all along, i just could verify.

Suggestion: Please add a hint in the ui that content in the source control view is only available if your already open a folder that is under source control.
Follow up questions: But then how do i add a folder (like a new project) to source control out of vs code? And is it possible to push my commits directly to my online repository out of vscode?

Explanation: So the source of my confusion setting up vscode with git was, that i tried to set everything up, then test it and then starting my coding (in opening a folder). 
But this is not the workflow you assume the new user would take...

My problem is solved. Thank you.

**Comment by joaomoreno** [comment]
Funny you just hit this. Another user just did, we should probably improve the experience here. You can follow this issue: https://github.com/Microsoft/vscode/issues/61491

**Comment by rdavid4** [comment]
SOLVE------------------------------------
The only thing you have to do to solve the problem is open de appdata folder: 

1. win+r  write
2. %appdata%  ENTER
3. delete code folder.
4. Start VS code again, it is restarted.
Now you can see the git icon available.
