### ISSUE TITLE
Renaming a styled component does not always work from JSX

### ISSUE THREAD

**Issue by dontsave** [Microsoft/vscode#61527]
- VSCode Version: latest
- OS Version: Windows 10

Renaming a styled component from the JSX does not rename the styled component at its declaration.

Steps to Reproduce:

test.tsx:
```
import styled from 'styled-components';
import * as React from 'react';

const Test = styled.div` <---- renaming Test here successfully renames test below
`;

export const Testing:React.SFC = p => {
	return (
		<div>
			<Test>hi there</Test> <----- renaming Test here does not rename test above
		</div>
	);
};

```

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#28065
