### ISSUE TITLE
page up / down in terminal

### ISSUE THREAD

**Issue by tap52384** [Microsoft/vscode#61521]
Issue Type: <b>Bug</b>

When I use "vi" in the terminal within VS Code on macOS, holding Fn and pressing the up or down arrow keys doesn't seem to page up or page down like it should.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
dotenv|mik|1.0.1
csharp|ms-|1.16.2
vscode-docker|Pet|0.3.1

</details>

**Comment by Tyriar** [comment]
cmd+fn+down/up will scroll page, page up/down are bound to scroll the scrollback buffer.
