### ISSUE TITLE
onDidCloseTextDocument emitting events with wrong text documents

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#61528]
- VSCode Version: 1.29 Insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Clone https://github.com/Microsoft/vscode-extension-samples/tree/master/contentprovider-sample
2. Make following changes to https://github.com/Microsoft/vscode-extension-samples/blob/master/contentprovider-sample/src/provider.ts#L18-L23

```diff
--- a/contentprovider-sample/src/provider.ts
+++ b/contentprovider-sample/src/provider.ts
@@ -13,17 +13,24 @@ export default class Provider implements vscode.TextDocumentContentProvider, vsc
        private _onDidChange = new vscode.EventEmitter<vscode.Uri>();
        private _documents = new Map<string, ReferencesDocument>();
        private _editorDecoration = vscode.window.createTextEditorDecorationType({ textDecoration: 'underline' });
-       private _subscriptions: vscode.Disposable;
+       private _subscriptions: vscode.Disposable[];

        constructor() {

                // Listen to the `closeTextDocument`-event which means we must
                // clear the corresponding model object - `ReferencesDocument`
-               this._subscriptions = vscode.workspace.onDidCloseTextDocument(doc => this._documents.delete(doc.uri.toString()));
+               this._subscriptions = [];
+               this._subscriptions.push(vscode.workspace.onDidCloseTextDocument(doc => {
+                       console.log(close, doc.uri.toString());
+                       this._documents.delete(doc.uri.toString())
+               }));
+               this._subscriptions.push(vscode.workspace.onDidOpenTextDocument(doc => {
+                       console.log('open', doc.uri.toString());
+               }));
        }

        dispose() {
-               this._subscriptions.dispose();
+               this._subscriptions.forEach(dispose => dispose.dispose());
                this._documents.clear();
                this._editorDecoration.dispose();
                this._onDidChange.dispose();
```

3. Launch the extension and open a single TypeScript file, run Show All References command.
4. The events we get are like

```
open references:References.locations
close references:References.locations
open references:References.locations
```

5. If we now close the editor for `references.locations`, we didn't receive any textDocumentClose event.

This is probably a duplicate of https://github.com/Microsoft/vscode/issues/30820.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by rebornix** [comment]
The jsDoc is also recommending to use `TextEditor` event for listening to visible editor being closed 

https://github.com/Microsoft/vscode/blob/1ed819905e084d040da47f7494e84707ef131eb6/src/vs/vscode.d.ts#L7371-L7373

but there is no such event for this purpose. The closest event is `onDidChangeVisibleTextEditors` but if an editor becomes a hidden tab first and being closed, we will not receive the event at the right time.


---
The thing I'm trying to archive here is being notified when an in-memory document is being closed, @bpasero can you help point out which API I should use?

**Comment by jrieken** [comment]
> The thing I'm trying to archive here is being notified when an in-memory document is being closed,

The event is the `onDidCloseTextDocument`-event but it is not in your control when that actually happens. The workbench decides and for virtual documents the rules is implemented here: https://github.com/Microsoft/vscode/blob/df69b899dc0e543589adc02013ac5795d81cd70f/src/vs/workbench/api/electron-browser/mainThreadDocuments.ts#L21

So, after 3mins or when 80MB storage for documents are exceeded we start to clean-up. Before that documents are kept.

**Comment by jrieken** [comment]
What you might want is this: https://github.com/Microsoft/vscode/issues/15178
