### ISSUE TITLE
 n.onOptionChange is not a function

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#61523]
Issue Id: <b>21a76b38-f45e-ac02-c6f3-5a99b42dea21</b><br /><br />*Versions* <br />- 1.29.0-insider (10/17/2018 5:16:50 AM)<br />-  27ee5c295c66653a9ecee858efbb1394d9044ef2<br />*Stack* <br />TypeError: n.onOptionChange is not a function<br />[/vs/workbench/parts/search/browser/patternInputWidget.ts#221:8 (call)](https://github.com/microsoft/vscode/blob/799bc78af597769a5dd5a6b002359ddae412b1be/src/vs/workbench/parts/search/browser/patternInputWidget.ts#L221:8 (call))<br />[/vs/base/common/event.ts#145:15 (fire)](https://github.com/microsoft/vscode/blob/799bc78af597769a5dd5a6b002359ddae412b1be/src/vs/base/common/event.ts#L145:15 (fire))<br />[/vs/base/browser/ui/checkbox/checkbox.ts#105:18 (listener)](https://github.com/microsoft/vscode/blob/799bc78af597769a5dd5a6b002359ddae412b1be/src/vs/base/browser/ui/checkbox/checkbox.ts#L105:18 (listener))<br />[/vs/base/browser/ui/widget.ts#14:102](https://github.com/microsoft/vscode/blob/799bc78af597769a5dd5a6b002359ddae412b1be/src/vs/base/browser/ui/widget.ts#L14:102)<br />

**Comment by roblourens** [comment]
Fixed in #61350
