### ISSUE TITLE
super/meta + delete/backspace cannot be recognized

### ISSUE THREAD

**Issue by praenubilus** [Microsoft/vscode#61520]
- VSCode Version: 1.28.2
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Open VSCode Keyboard Setting 
2. Set keyboard shortcuts

On my ubuntu system, I used to bind delete word left/right with super+backspace/delete. No it suddenly stopped working. And I'm trying to reset it in keyboard settings but the vscode can not recognize that keyboard combination.

**Comment by Tyriar** [comment]
What command are you trying to use? Could you share the exact keybinding entry from your keybindings.json file?

**Comment by praenubilus** [comment]
Any update?

**Comment by alexandrudima** [comment]
@praenubilus Does VS Code receive this key combination? If we are not receiving the key combination, it is very likely that you have updated your OS, or installed something on your OS that is eating up those keybindings. Do these keybindings work for you in other applications?

![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

**Comment by praenubilus** [comment]
> @praenubilus Does VS Code receive this key combination? If we are not receiving the key combination, it is very likely that you have updated your OS, or installed something on your OS that is eating up those keybindings. Do these keybindings work for you in other applications?
> 
Yes. I think you are right. I use AutoKey for customized shortcut based on window class filter. For some reason, the window class filter is not working, I guess it's a bug for updated AutoKey version. The input combination has been intercepted by autokey.
