### ISSUE TITLE
"Source" line in a notification can get truncated down to "Sour..."

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/vscode#61538]
The "Source:" section of a notification is can get heavily truncated, to the point that it says "Sour.." which at that point is obstructing what the text is representing.

![image](https://user-images.githubusercontent.com/54418/47325618-91983d00-d619-11e8-9f36-4cd580baed5d.png)

Not sure if there is much to do here, but it is a slight usability issue as I was demoing this feature to a PM and they asked "what's sour?"

Version: 1.29.0-insider (user setup)
Commit: 4d9f1d23a556dccd2c0fd5203923a24b21e41209
Date: 2018-10-22T05:18:34.128Z
Electron: 2.0.11
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
- OS Version: Windows 10

Steps to Reproduce:

1. Have PowerShell set as your terminal
1. Create a conda environment
1. Launch the Python extension for VS Code
1. Open a fresh terminal which will trigger the notification

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
I opened https://github.com/Microsoft/vscode/issues/65218 to provide a possible solution to this issue.
