### ISSUE TITLE
Very slow tokenization in very long lines

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#61533]
I have a minified js file with long lines that takes an extremely long time to tokenize. I know that we expect long lines to be slow but a profile shows many individual lines taking 5-10s which seems excessive. Maybe there's something in this file that hits a bad case in the grammar. If this is expected, maybe we should set a time limit for tokenization per document, because this causes my CPU to spin for minutes. (Discussed with @rebornix offline.)

I can't share the file publicly so come to me if you want to see it.

**Comment by mjbvz** [comment]
@roblourens Do you still see this issue?

**Comment by roblourens** [comment]
I can't remember what file it was 😁
