### ISSUE TITLE
Change of Dismiss action button position in Search panel

### ISSUE THREAD

**Issue by IllusionMH** [Microsoft/vscode#61532]
- VSCode Version: 1.29-insider
- OS Version: Windows 10 Version 1809 (OS Build 18262.1000)

Steps to Reproduce:

1. Activate Find in files and search for something that will return results
2. Hover over different result lines
3. Both Badge and Action button (Dismiss) are on the left (aligned to the end of result text)

I'm expecting that Dismiss action will have fixed horizontal position (on the right side) that will allow me to easily dismiss several results entries. With current position at the end of result text I have to constantly move mouse to hit Dismiss button.

In stable version both count badge (for file) and Dismiss action were aligned at the right side of the viewlet which was convenient. At this moment it is hard to filter out result entries because texts have different length and button shifts for each line.

I've found #46604 which says that button should always stay on the right side, however this isn't case in v1.28.2 independently from viewlet width (both badge and actions are on the right side).

Does this issue occur when all extensions are disabled?: Yes

<details>
<summary>Screenshot</summary>
<div>

![image](https://user-images.githubusercontent.com/1312662/47322168-ad263680-d65f-11e8-94be-bba3573b46e6.png)

</div>
</details>

**Comment by Tyriar** [comment]
I guess this only applies to the search _panel_?

**Comment by IllusionMH** [comment]
Yes, I observe issue in Search panel.

**Comment by IllusionMH** [comment]
Yes, that match what I see, but makes it harder to use Dismiss action with mouse.

For badge with results count - it is good position, since it is visible without hover.
On the other hands actions are only visible on hover, when background can clearly indicate what line will be dismissed. Previously (September and numerous builds before) I was able to put mouse over X and just click (even without looking) several times to remove unnecessary lines. Now it takes more time/attention to do it with mouse, and if next line after dismissed has longer text - it is easy to open file instead of dismissing it.

Open editors view (Close editor button), Source control (action buttons for files), Extensions (Manage button)  - have static position of actions that are not changed with sidebar width.

My cases are 23" monitor with 1920x1080 and Surface Pro 3. Never had problems when action were on the right side. Users with 4k 30+"  will have to snipe for X too.

**Comment by roblourens** [comment]
>  Previously (September and numerous builds before) I was able to put mouse over X and just click (even without looking) several times to remove unnecessary lines. 

Yes it was broken for a few months, but this was the behavior from before it was broken 😁 

I see your point but I will leave this open to think about it

**Comment by IllusionMH** [comment]
@robertohuertasm thanks!

**Comment by AlexTelon** [comment]
Putting the dismiss button to the right would also make it less likley that someone presses it by accident which I just did. 

The middle of a search result might be just above/below the end of another so that clicking just a bit above/below where you intended could lead you to remove the other search result.

**Comment by lijuenc** [comment]
Issue 1) The dismiss buttons are too close to the actual text of the search result making it very easy to accidentally dismiss something.

Issue 2) The dismiss buttons are invisible until hover/focus. So if you had your focus on another panel or another window and then click on a search result to focus it, it's too easy to click on an invisible button and accidentally dismiss a search result because of issue 1.

**Comment by roblourens** [comment]
Trying to decide whether we should just always right align... but it seems weird to me to have the X really far away from the row content in some cases. Anyway, if someone wants to add a setting to configure this, I would take that PR.
