### ISSUE TITLE
Error message when i use a valid regex

### ISSUE THREAD

**Issue by gtzinos** [Microsoft/vscode#61537]
I execute this command in the search tab, as a regex command:

- ^((?!test).)*$

Is a regular expression to match a line that doesn't contain a word.

But it returns me an error message

![screenshot from 2018-10-23 02-32-26](https://user-images.githubusercontent.com/11459192/47325336-ea90c100-d66b-11e8-8694-0303e5966d38.png)

**Comment by roblourens** [comment]
If a regex matches an empty string, then we reject it because it can lead to an infinite loop. Try + instead of *?

**Comment by gtzinos** [comment]
I tried it. Now I get another error message.

![screenshot from 2018-10-23 13-57-32](https://user-images.githubusercontent.com/11459192/47356070-ba790a80-d6cb-11e8-9a3d-72437df89d60.png)

**Comment by roblourens** [comment]
I also forgot to mention, lookback only works in Insiders (and the next stable release). It can be enabled by setting `search.usePCRE2`.

**Comment by gtzinos** [comment]
I also forgot to mention that I work in code insiders.
