### ISSUE TITLE
App Colors not displaying properly

### ISSUE THREAD

**Issue by bradotron** [Microsoft/vscode#61545]
![capture1](https://user-images.githubusercontent.com/43523833/47327124-8d781980-d631-11e8-837b-5c4431aabd46.PNG)
![capture2](https://user-images.githubusercontent.com/43523833/47327125-8d781980-d631-11e8-8ef3-c28999411bb7.PNG)

Issue Type: <b>Bug</b>

There's no steps really - I install VS Code on my laptop and the colors of the text and accents in the app do not display properly. I've tried reinstalling a couple times and resetting a variety of color theme related settings in windows. I've tried multiple font issues I found through google. Looking for tips on some other routes to fix this. I will post a couple screenshots for reference.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (4.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
open-in-browser|tec|2.0.0

</details>

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/60298
