### ISSUE TITLE
Launch debug session from extension

### ISSUE THREAD

**Issue by TomSputz** [Microsoft/vscode#61544]
It would be great if extensions could be allowed to launch debug sessions, passing their own configuration. This would allow extensions made for automation to jump straight into debugging, and allow extensions to take advantage of files like `package.json` when launching the debugger

## Example use

I've found vscode's launch configurations frustratingly static for a long time, and I'm looking at what would be needed to make an extension that would:

Allow a javascript function to be defined that:

- Is passed all variables launch configurations can take advantage of
- Returns a launch configuration object to be run

`launch.json` would probably look something like

```js
{
  "configurations": [{
    "type": "dynamic",
    "name": "Launch File",
    "function": "({ file }) => ({\
      type: file.split('.').slice(-1)[0] === 'py'\
        ? "python"\
        : "node",\
      request: "launch",\
      program: file\
    })"
  }]
}
```

**Comment by isidorn** [comment]
This is actually supported, please check out our debug api
https://github.com/Microsoft/vscode/blob/121c60f64af7f6b2e4f489a1cf2c0881d2a193dd/src/vs/vscode.d.ts#L8350
