### ISSUE TITLE
When editing css / scss, an option to not inserting blank line within braces.

### ISSUE THREAD

**Issue by terrylks** [microsoft/vscode#61549]
When editing css / scss file, assume we have this:

```
.container{}
```

If the cursor is now within the braces and we insert a new line by pressing `Enter`, it becomes this:

```
.container{
  
}
```

However, what I need is an option that it become this (without the blank line) if I press `shift + Enter`:

```
.container{
}
```

This option helps a lot when I added a new nested child class and migrating css properties from parent down to child by swapping the line using `Option + Up / Down` without removing the blank line that vsc added automatically when I insert a new line within the braces in the child class.

I think it could be used not only in css/scss but all file format indeed.

**Comment by terrylks** [comment]
any updates about it?

**Comment by rebornix** [comment]
This can be done by setting `editor.autoIndent` to `keep` for css language.
