### ISSUE TITLE
Fix strict null errors in 'vs/workbench/api/node/extHostTypes.ts'

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#61543]
Part of #60565

Tracks strict null checking `vs/workbench/api/node/extHostTypes.ts`. Adding multiple owners with rough breakdown (feel free to reassign):

- @jrieken - `TextEdit`, `WorkspaceEdit`, `CodeLens`, `SymbolInformation`, `Hover`
- @isidorn - Debug apis
- @dbaeumer - Task apis
- @alexandrudima - `Position`

**Steps**

1. Add `vs/workbench/api/node/extHostTypes.ts` to the `files` section of `src/tsconfig.strictNullChecks.json` 
1. Run `yarn strict-null-check -- --watch`
1. Fix errors errors in your api area and verify normal build still works

**Comment by weinand** [comment]
fixed debug issue in extHostTypes.ts with https://github.com/Microsoft/vscode/commit/115ea4afe3dd13e739db169d992715c4221721da

**Comment by dbaeumer** [comment]
@jrieken while doing this for Tasks I noticed that some of the API definitions are not correct since they didn't correctly specify `| undefined`. What is our advice in this matter. Adding this to the vscode.d.ts API is strictly speaking breaking.

**Comment by jrieken** [comment]
Yeah, we have been doing these kind of breakages... Just be aware we usually declare optional properties like so `foo?: boolean` instead of `foo: boolean | undefined`. The `| undefined ` we use for return values and parameters that cannot be made optional

**Comment by dbaeumer** [comment]
@jrieken. Thanks. Then I will change the API file as well.

**Comment by dbaeumer** [comment]
Done for tasks.
