### ISSUE TITLE
Very Slow After Long Time Used on Highend computer

### ISSUE THREAD

**Issue by KiyeopYang** [Microsoft/vscode#61551]
Issue Type: <b>Bug</b>

In fact, this happen in my highend computer and laptop.
maybe this happens in other computers.
after using vs code long time (maybe 20~40 hours ? including power saving mode of computer), it become very slow. very.. (very many lags)
after restart Vs code, the problem solved.
but I don't want it happen.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (3.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
snapshot-tools|asv|0.2.2
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.6.1
es7-react-js-snippets|dsz|1.8.7
vscode-wasm|dts|1.2.1
gc-excelviewer|Gra|2.1.26
r|Iku|1.0.0
graphql-for-vscode|kum|1.12.1
vscode-language-pack-ko|MS-|1.28.2
python|ms-|2018.9.1
polacode|pnp|0.2.2
rust|rus|0.4.10

</details>

**Comment by Tyriar** [comment]
Please see https://github.com/Microsoft/vscode/wiki/Performance-Issues for creating actionable performance problem issues.
