### ISSUE TITLE
WSL TERMINAL

### ISSUE THREAD

**Issue by juanpablomarin** [Microsoft/vscode#61553]
Issue Type: <b>Bug</b>

I literally cannot see WSL show any type of prompt, just a blank screen.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:12.403Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.86GB (3.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|40%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-mysql|for|0.3.0
mysql-syntax|jak|1.3.1
python|ms-|2018.9.1
cpptools|ms-|0.19.0
java|red|0.32.0
vscode-java-debug|vsc|0.14.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.10.0
vscode-maven|vsc|0.11.1

</details>

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/57803
