### ISSUE TITLE
Editing around codelens results in garbled codelens position

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#6155]
Extension: CodeMetrics

![codelens](https://cloud.githubusercontent.com/assets/5047891/15067893/dec60988-1373-11e6-80e3-4b838ab6863d.gif)

**Comment by ramya-rao-a** [comment]
@alexandrudima I can't repro this, maybe it got fixed somehow in the past 7 months?

**Comment by alexandrudima** [comment]
:+1: This got somehow fixed in the meantime.
