### ISSUE TITLE
Why is there an extra machineid file needed?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#61562]
It looks like we create a top level `machineid` file ([here](https://github.com/Microsoft/vscode/blob/d1f5894892e3719846bbd4bd0dd75f117f211ab5/src/vs/platform/extensionManagement/node/extensionGalleryService.ts#L815)). We already have a machineid in `storage.json` (as `telemetry.machineId`), can we not use that and get rid of this one?

**Comment by sandy081** [comment]
I do not know about this `machineid` file. @joaomoreno can we use it?

**Comment by bpasero** [comment]
@joaomoreno yeah I remember

**Comment by sandy081** [comment]
@bpasero Can this be closed?

**Comment by bpasero** [comment]
Yeah though at some point we should revisit the stuff we store in the user data directory. The name `machineid` is bad because the term is overloaded.
