### ISSUE TITLE
Emmet keybind not working

### ISSUE THREAD

**Issue by mu60** [Microsoft/vscode#61568]
- VSCode Version: 1.28.1
- OS Version: Windows10

{
  "key": "ctrl+e",
  "command": "editor.emmet.action.expandAbbreviation",
  "when": "config.emmet.triggerExpansionOnTab && editorTextFocus && !editorReadonly && !editorTabMovesFocus"
}

Ctrl + E not working

**Comment by ramya-rao-a** [comment]
Remove the `config.emmet.triggerExpansionOnTab` in the `when` clause
