### ISSUE TITLE
Slow startup on Ubuntu 18.10

### ISSUE THREAD

**Issue by ayush987goyal** [Microsoft/vscode#61565]
Issue Type: <b>Performance Issue</b>

1. Open a terminal and navigate to a director
2. Open VSCode using `code .`

VSCode takes a lot of time to launch.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:20:56.183Z)
OS version: Linux x64 4.18.0-10-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|7.63GB (0.82GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   133	 19286	code main
    0	    39	 19288	   zygote
    0	   203	 19654	     zygote
    0	     0	 19684	       /bin/bash
    0	   102	 19693	       extensionHost
    0	    63	 19699	       watcherService
    0	    63	 19747	       searchService
    0	   102	 19704	     zygote
    0	   102	 19984	     zygote
    0	   133	 19644	   gpu-process
    0	     0	 20008	   /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 20009	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (boot_sect_simple.asm - os - Visual Studio Code)
|    Folder (os): 3 files
|      File types: asm(1) gitignore(1) bin(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
ng-template|Ang|0.1.10
bracket-pair-colorizer|Coe|1.0.60
dart-code|Dar|2.19.0
flutter|Dar|2.19.0
vscode-eslint|dba|1.6.1
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.40
prettier-vscode|esb|1.6.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vscode-pull-request-github|Git|0.2.1
Angular2|joh|6.3.0
Angular-BeastCode|Mik|7.0.4
dotenv|mik|1.0.1
python|ms-|2018.9.1
cpptools|ms-|0.19.0
Go|ms-|0.6.93
debugger-for-chrome|msj|4.10.2
vetur|oct|0.13.0
vscode-graphql|Pri|0.1.5
vscode-icons|rob|7.27.0
sass-indented|rob|1.4.9
code-settings-sync|Sha|3.2.0
JavaScriptSnippets|xab|1.7.1

(1 theme extensions excluded)

</details>

**Comment by ayush987goyal** [comment]
This is in particular to the snap packaged vscode.

**Comment by scruti** [comment]
Had the same issue. The launch time of the snap became unbearably slow.

**Comment by jkehler** [comment]
I experienced the same issue on Ubuntu 18.10. i installed VSCode via the Ubuntu Software center which is a snap package. It would take ~15 seconds to launch every single time. So I uninstalled the snap package and installed it via the .deb download link instead and it starts up almost immediately.

**Comment by andreujuanc** [comment]
Did exactly what @jkehler said, and got opened immediately.  :( 
I heard lot's of these issues with snaps in several apps, like Gnome Calculator :rofl:

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/61613

**Comment by FThompson** [comment]
In Ubuntu 18.10 I experienced VSCode taking ~15s to load installed with the .deb download link. Additionally, my extensions panel would not load, instead hanging with the loading bar animating forever and a loading clock icon over the extensions icon.

Running VSCode with `--disable-gpu` fixed both the slow loading and the extensions panel not loading for me. My system is a laptop with an i7-4700mq and Nvidia GT 755m running the default nouveau drivers, which seem to be a possible source of the problem.
