### ISSUE TITLE
Many *.sock files in my Code home directory

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#61561]
It does not seem right that these files are staying around, shouldn't they be deleted once I close Code?

![image](https://user-images.githubusercontent.com/900690/47337920-39ebe700-d696-11e8-9d1a-3b70e54db548.png)

**Comment by joaomoreno** [comment]
Nice version history!

**Comment by atitoa93** [comment]
I'd like to work on this!. Will start investigating to know from where this issue comes, but meanwhile, insights will be appreciated.

**Comment by bpasero** [comment]
> We just have to delete the file when the shared process stops serving.

@joaomoreno so how are we doing it for the main file then, are we really deleting the file manually or is it cleaned up when the process exists?

**Comment by joaomoreno** [comment]
> @joaomoreno so how are we doing it for the main file then, are we really deleting the file manually or is it cleaned up when the process exists?

Having a quick peek at the code, I could not find any point in which we delete it on shutdown 🤷‍♂️

**Comment by bpasero** [comment]
@joaomoreno I guess what we would want is to mark these files for deletion only when the main process goes down.

**Comment by joaomoreno** [comment]
We can actually just delete them on the shutdown sequence of the shared process.

**Comment by bpasero** [comment]
@joaomoreno yeah, thats a good start. But we will still see sock files around once the process crashes. Though I guess these files would get cleaned up on the next successful start/quit sequence.

**Comment by ColorlessHuman** [comment]
I would like to understand and work on this issue. Any kind of insight will be highly appreciated.

**Comment by atitoa93** [comment]
@joaomoreno @bpasero, Can you point me to file names that I should start from? I spent time trying to find where the main thread gets deleted/cleaned but with no luck. Thanks.

**Comment by joaomoreno** [comment]
Sorry guys, removing the `help wanted` label, I'll just get it done next week.

**Comment by joaomoreno** [comment]
Got it done now! 😆
