### ISSUE TITLE
ES6 basic syntax is not recognized

### ISSUE THREAD

**Issue by chjish28461** [Microsoft/vscode#61563]
更新后解构赋值、无状态组件、jsx的大括号缩进都没有了，什么鬼

**Comment by weinand** [comment]
Please use English for reporting issues and follow our issue reporting guideline:
https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#reporting-issues.

Translation:
ES6 basic syntax is not recognized

After the update, the destructor assignment, the stateless component, and the jsx braces are indented. What the hell?

**Comment by mjbvz** [comment]
Closing as we need more information to investigate this
