### ISSUE TITLE
I can not disable automatic updates

### ISSUE THREAD

**Issue by mu60** [Microsoft/vscode#61567]
- VSCode Version: 1.27.2
- OS Version: Windows10

I have disabled automatic updating, but it will be updated without permission when I reboot.
自動アップデートを無効化しているのですが、再起動すると勝手にアップデートされてしまいます。

[Settings]
Update: Channel → none
Update: Enable Windows Background Updates → none

**Comment by joaomoreno** [comment]
Are you sure? Setting update channel to none should completely disable updates after you restart Code.
