### ISSUE TITLE
syntax highlight of shorthand async functions in object literals

### ISSUE THREAD

**Issue by hasyee** [Microsoft/vscode#6156]
- VSCode Version: 1.0.0
- OS Version: Win 10

Steps to Reproduce:

1. Type this `.js` or `.ts` snippet:
```javascript
const o = {
	async f() {
		
	}
};
```
VSCode won't highlight `async` keyword without `function`.
However it works fine:
```javascript
class A {
	async f() {
		
	}
}
```

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#163
