### ISSUE TITLE
Make TreeItemHighlights API public

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#61579]
Ref https://github.com/Microsoft/vscode/issues/61313

This is the API that allows extension authors to highlight the labels

**Comment by jrieken** [comment]
Well, there is no extra loop enforcement rule but lets make sure our excitement about this doesn't make use push something we haven't thought enough about

**Comment by alexr00** [comment]
The references view has used this API for a long time. To verify, read the inline documentation for the API and make sure it makes sense: https://github.com/Microsoft/vscode/blob/01bbb81052086edf3398e599f218e189c44b0658/src/vs/vscode.d.ts#L8958-L8958
