### ISSUE TITLE
Add an option to default to zen mode

### ISSUE THREAD

**Issue by brainlessdeveloper** [Microsoft/vscode#61572]
The first thing I do when opening a project is switch to zen mode. It's great when vscode opens a project it already knows and automatically switches to zen mode if that was its last state.

It would be great if there were an option to use zen mode by default on _all_ projects, new or known.

Something like:

```json
{
  "window.defaultToZenMode": true,
}
```

I've been searching for issues about this topic (or already-implemented features) and I haven't found one. Thank you for the awesome editor!

**Comment by isidorn** [comment]
Please use 	
`"zenMode.restore": true`

We will not add a setting to open new projects in zen mode, that is out of scope for now.

**Comment by brainlessdeveloper** [comment]
@isidorn That's a pity! I already use `"zenMode.restore": true`. Thanks for the quick answer anyway.
