### ISSUE TITLE
feature issue: saving Find/Replace options

### ISSUE THREAD

**Issue by hasyee** [Microsoft/vscode#6158]
VSCode should save the **Find** / **Replace** options like: `Match case` and `Whole word`.
This would allow to using them after restart.
It could be an user option below search settings.

**Comment by ryanwinchester** [comment]
also does the multiple selections need to use the find settings or can it have it's own, set in settings.json or somewhere?

**Comment by rebornix** [comment]
We'll start with the persistence with three search options  Match Case, Match Word and Regex first. The goal is aligning with current Search Viewlet.

As we discussed in https://github.com/Microsoft/vscode/issues/11574#issuecomment-245623366 , we are going to persist user preference in following way

* anytime a find widget toggle is changed, I will persist it (last one wins)
* when the workbench starts up, I will read the persisted values and start with those by default.

In addition to that, the setting persistence is workspace-based. Workspaces won't share the data. Let's start with it first and see if it's necessary to add a new setting which defines the default toggle setting for Find Widget.

**Comment by leocaseiro** [comment]
Hi @rebornix. I was wondering which version of VSCode persists it?

Any way to use the Nightly version or I need to wait for `1.12.1` be updated?

Thanks

**Comment by ownagedj** [comment]
Is it intended that vscode only remembers the search settings for directory where these have been set?

If I start vscode e.g. with: code example-dir
and I check case sensitive search I will remember these settings, after I closed and reopened the editor.

But if start vscode in an other directory the settings are gone. Is this how it should work?

As far as I know there is no global setting to define the default one or am I missing something?
