### ISSUE TITLE
After a long time running, the cpu up to 50%, and the interface was stuck.

### ISSUE THREAD

**Issue by muyu66** [Microsoft/vscode#61580]
- OS Version: windows 10
VERSION: 1.28.2 (system setup)
SUBMIT: 7f3ce96ff4729c91352ae6def877e59c561f4850
DATE: 2018-10-17T00:23:51.859Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
x64

I didn’t have this exception before, the latest ones have appeared.

Restart the system for a few hours or after a dozen hours, it will appear.

What should I provide debugging data for you to test and analyze?

SETP:
1. code in VSCODE
2. switch to other VistualDesktop(Win10 Feature), use other application (such as Chrome)
3. switch back.
4. as long as I click on VSCODE for editing code, it will Stuck.
5. wait 30 seconds (maybe), It becomes normal.
4,5,4,5,4,5,4,5.....loop.

Does this issue occur when all extensions are disabled?: No

![image](https://user-images.githubusercontent.com/20837526/47346934-c7542900-d6e0-11e8-9ce9-5dd9ef06c6dc.png)

**Comment by muyu66** [comment]
I just restarted, when there is a problem, I will cut off a video for your reference.

**Comment by isidorn** [comment]
Please follow this on how to file a proper performance issue https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by muyu66** [comment]
I followed the help documentation above to confirm that it should be an extension, specifically which extension, I will give feedback to the corresponding developer.
