### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by thomassen88** [Microsoft/vscode#61586]
Everytime i open VScode the "release notes" opens. There is no option to turn it off.

- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:48.528Z)
- OS Version: Windows_NT ia32 10.0.17134
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
xml|Dot|1.9.2
vsc-material-theme|Equ|1.3.0
beautify|Hoo|1.3.0
minify|Hoo|0.3.0
vscode-browser-sync|jas|1.3.1
font-awesome-codes-css|med|0.1.1
font-awesome-codes-html|med|0.0.7
Angular-BeastCode|Mik|6.1.5
vetur|oct|0.12.4
material-icon-theme|PKi|3.2.2
iis-express|war|1.1.0
bootstrap-3-snippets|wcw|0.1.0
livereload|zee|0.1.1

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Open visual studio code

**Comment by mjbvz** [comment]
Closing as we have not heard back if this is still occurring in newer VS Code versions

**Comment by DonGlover** [comment]
It happens to me with 1.28.2

**Comment by thomassen88** [comment]
Sorry for the late reply. I have upgraded to 1.28.2. As Don Glover says, it still happens. Now it only occure sometimes, not everytime as before. Its very random and i cant put my finger on why it happens or if it happens when i open certain files or projects, its just so damn random :p Its not a big problem, but its kind of annoying.
