### ISSUE TITLE
Readonly message in not fully visible

### ISSUE THREAD

**Issue by zqlu** [Microsoft/vscode#61585]
When I try to edit in an readOnly editor, I got a message "Cannot edit in a read-only editor", But when the editor is on the top of browser window, the message is not visible/outside of the window, see below:

![image](https://user-images.githubusercontent.com/1142242/47349409-28323000-d6e6-11e8-894d-8d6316a39dd3.png)

**Comment by weinand** [comment]
What product are you talking about?

**Comment by zqlu** [comment]
> What product are you talking about?

Monaco Editor

**Comment by weinand** [comment]
Then please file issue against Monaco Editor: https://github.com/Microsoft/monaco-editor
