### ISSUE TITLE
"enablePreview" setting is not discoverable

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#61582]
Some users don't like the fact that editors are reused if they are not "pinned" (e.g. #61569).
I know how to pin an editor by double-clicking but I had a hard time to find the corresponding setting `enablePreview` because "preview" isn't something I can relate to "pinning".

IMO "enablePreview" is a less-than-ideal name (but it is probably too late to change this).
I suggest to at least mention the concept "pinned" in the description of `enablePreview`.

If I search for "pinned" in settings I find only this (which appears to be completely bogus):
![2018-10-23_10-56-20](https://user-images.githubusercontent.com/1898161/47348712-5d248f80-d6b2-11e8-8735-a7cce17cf4bd.png)
 
/cc @roblourens

**Comment by RonnieLyu** [comment]
Thank you very much.!!!!!

**Comment by bpasero** [comment]
PR welcome

**Comment by karanisverma** [comment]
@bpasero  I would like to pick this up!
To my understanding the description need to be changed for better explanation.  Please let me know If I am getting it wrong.

**Comment by bpasero** [comment]
@karanisverma yeah thats about right, thanks

**Comment by bpasero** [comment]
@karanisverma yeah thats good. Also maybe fix that typo: `Controls whether opened editors show as preview.` (shows => show)

**Comment by karanisverma** [comment]
Hey @bpasero Thanks a lot! 
i will do this changes and create a PR.
As it's my first contribution to this project. is there any documentation i need to refer(some sort of style guild?)
