### ISSUE TITLE
Please add 'Open keybindings.json' to the secondary actions

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#61587]
Now these are not well connected, I suggest to add "Open keybindings.json" to the context menu.
This way it would also be aligned with the settings and settings.json relationship
fyi @alexandrudima 

![screen shot 2018-10-23 at 11 23 20](https://user-images.githubusercontent.com/1926584/47350411-205a9780-d6b6-11e8-93f1-9a384a1a20ba.png)

**Comment by sandy081** [comment]
@isidorn There is a primary file icon to show the `keybindings.json` file. Looks like this icon is not good enough to represent the action.


@misolori Can you please help me in getting two icons that does

1. Open Keybindings.json file from Keybindings editor 
2. Open Keybindings editor from Keybindings.json file

**Comment by alexandrudima** [comment]
I have also suffered from the missing link, it took me a few minutes to find the file on disk and then it turns out I found the wrong `keybindings.json` from the buit version of Code-OSS and not from the dev version of Code-OSS...

**Comment by sandy081** [comment]
Thanks @misolori  for suggestions.

After today's stand up I had to revert back my changes and show the link back in the editor 😞 

I will close this for now and use it in future if needed.

**Comment by sandy081** [comment]
I see #61590 is being discussed for similar topic. We can continue discussion there.
