### ISSUE TITLE
Multi-target debug fails to start in integratedTerminal if there is any Node Debug Consoles left open

### ISSUE THREAD

**Issue by 4ndv** [microsoft/vscode#61598]
Issue Type: <b>Bug</b>

1. Run non-multitarget debug
2. Stop it
3. Don't close remain Node Debug Console (-s)
4. Run multi-target
5. vscode will try to run all of the targets in the same terminal, trying to paste all of the commands into it

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 6|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv|-psn_0_1466726|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-ru|MS-|1.28.2
vscode-eslint|dba|1.6.1
dotenv|mik|1.0.1
vscode-elixir|mjm|1.1.0
Go|ms-|0.6.93

</details>

**Comment by weinand** [comment]
How do your launch configs look like, e.g. the one for non-multitarget debug and for multi-target debug.

**Comment by 4ndv** [comment]
My config:

```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Repl",
      "program": "${workspaceFolder}/lib/repl.js",
      "envFile": "${workspaceFolder}/.env",
      "console": "integratedTerminal",
      "runtimeArgs": ["--experimental-repl-await"]
    },
    {
      "type": "node",
      "request": "launch",
      "name": "API",
      "program": "${workspaceFolder}/apps/api/server.js",
      "envFile": "${workspaceFolder}/.env",
      "console": "integratedTerminal"
    },
    {
      "type": "node",
      "request": "launch",
      "name": "Worker",
      "program": "${workspaceFolder}/apps/worker/worker.js",
      "envFile": "${workspaceFolder}/.env",
      "console": "integratedTerminal"
    },
    {
      "type": "node",
      "request": "launch",
      "name": "Admin",
      "program": "${workspaceFolder}/apps/admin/server.js",
      "envFile": "${workspaceFolder}/.env",
      "console": "integratedTerminal"
    }
  ],
  "compounds": [
    {
      "name": "Everything",
      "configurations": ["API", "Worker", "Admin", "Repl"]
    }
  ]
}
```

Actually, it fails even if I just run multi-target debug twice, without closing terminals

**Comment by 4ndv** [comment]
1. Run multi-target debug once
2. Stop all the processes
3. Keep "Node Debug Console" terminals open
4. Run it again

**Comment by connor4312** [comment]
/duplicate https://github.com/microsoft/vscode/issues/71850

(and just fixed)
