### ISSUE TITLE
Debug fails to start with zsh and long commands

### ISSUE THREAD

**Issue by 4ndv** [microsoft/vscode#61594]
Issue Type: <b>Bug</b>

1. Have envFile with some long strings / a lot of variables
2. zsh that starts not very fast
3. zsh waits until i press Return to launch a command

Setting shell environment to `/bin/bash` fixes an issue, but i have to manually open zsh inside integrated terminal

Here is the output from integrated terminal that appears when i'm starting a debug session:

```cd /Users/lynx/projects/a/backend ; env "VERY_LONG_SECRET_KEY=loremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsum%▲ backend at dev ✖ cd /Users/lynx/projects/a/backend ; env "VERY_LONG_SECRET_KEY=loremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsumdolorsitalmetloremipsum```

Looks like it's not full command that should be there (it cuts on env variable, but there is not "node" run at all)

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 6, 11|
|Memory (System)|8.00GB (0.07GB free)|
|Process Argv|-psn_0_1466726|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-ru|MS-|1.28.2
vscode-eslint|dba|1.6.1
vscode-elixir|mjm|1.1.0
Go|ms-|0.6.93

</details>

**Comment by tom-thorne** [comment]
This issue is still occurring in VS Code 1.43.2
Here's an example `launch.json` 

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${workspaceFolder}/index.js",
            "env": {
                "TEST_ARG": "hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-hi-END"
            },
            "console": "internalConsole"
        }
    ]
}
```

**Comment by weinand** [comment]
@tom-thorne I cannot reproduce the problem with `"console": "internalConsole"`.
But I see it with `"console": "integratedTerminal"` and `"console": "externalTerminal"`.

On what platform are you seeing this?

**Comment by Tyriar** [comment]
Duplicate https://github.com/microsoft/vscode/issues/59135?

**Comment by weinand** [comment]
/duplicate #59135

@Tyriar yes, thanks.
