### ISSUE TITLE
Search didn't work and display error "Unknown encoding: utf8bom"

### ISSUE THREAD

**Issue by harimambura** [Microsoft/vscode#61593]
- VSCode Version: 1.29.0-insider (system setup)
Commit: d1f5894892e3719846bbd4bd0dd75f117f211ab5
Date: 2018-10-23T05:20:39.912Z
Electron: 2.0.11
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
- OS Version: Windows 10

Steps to Reproduce:

1. Open Settings->Text Editor->Files and set Encoding to 'utf8bom'
2. Open search panel and try to search something

Expected result: search is performed, search results are displayed
Actual result: no search results are displayed, Error message "Unknown encoding: utf8bom" displayed under the search input

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/3999607/47355134-3f165980-d6c9-11e8-99ea-8fa132a04b17.png)

**Comment by chabbothehutt** [comment]
Same here using:

Version: 1.29.0-insider (user setup)
Commit: 4d9f1d23a556dccd2c0fd5203923a24b21e41209
Datum: 2018-10-22T05:18:34.128Z
Electron: 2.0.11
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architektur: x64

OS: Win10 Ent - 1709 x64

For chcp "windows1252"
