### ISSUE TITLE
A11y_PowerShellEditorServices_Editor_Keyboard: Loss of Focus occurred after "BreakPoints" control.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#61595]
**Environment Details:**
VSCode Version : 1.25.0
OS Version : Win10

**Additional Details:**
Keyboard,MAS2.4.3,MAS2.4.7

**Repro Steps:**
1.Launch Visual Studio code desktop application.
2.Navigate to "Plain Text" of "StatusBar"->Enter "PowerShell" in "Select Language Mode"combobox->Write the PowerShell Code in plain editor->Save the editor.
3.Apply debugging and navigate to "Variables,Watch,Call Stack,Breakpoints"options.
4.Here observed that after Breakpoint control loss of keyboard focus occurred

**Actual:**
When the keyboard focus is on the Breakpoint control and user clicked the tab key then loss of focus is occurred.

**Expected:**
While navigating through the keyboard keys then keyboard focused should be visible on the each actionable controls.
Here after breakpoint control keyboard focus should be visible on the "Untitled-2.ps1" editor.

**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
https://microsoft.sharepoint.com/teams/msenable/mas/pages/fixit-details.aspx?fixitid=108

**User Impact:**
User will not able to know where the keyboard focus is after clicking on Breakpoint control.

**MAS Reference:**
MAS2.4.7-https://microsoft.sharepoint.com/%3Aw%3A/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc=%7B3b98b04f-4fab-4d3e-81af-a0906a34849c%7D
MAS2.4.3-https://microsoft.sharepoint.com/%3Aw%3A/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc=%7B0de7fbe1-ad7e-48e5-bcbb-8d986691e2b9%7D

**Attachment For Reference:**
[[Accessibility]A11y_PowerShellEditorServices_Editor_Keyboard.pptx](https://github.com/Microsoft/vscode/files/2505749/Accessibility.A11y_PowerShellEditorServices_Editor_Keyboard.pptx)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/61595

**Comment by isidorn** [comment]
This is fixed in latest vscode insiders, please try with that one
