### ISSUE TITLE
Setting for revealing the debug console

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#6159]
- [x] any platform - **@sandy081**

We have introduced a setting `internalConsoleOptions` in `launch.json` to change the behavior of automatic revealing of the debug console. Verify this setting is easy to find, use and works as expected.

**Comment by mattflix** [comment]
Could you at least mention what setting will restore the old 1.0.0 behavior (which seemed to be to reveal upon launch)?

The new `internalConsoleOptions` setting, nor its possible values, seem to be documented by the intellisense in the launch.json file.  (In fact, the intellisense within launch.json seems to be pretty messed up and incomplete in version 1.1.0, versus what is was in 1.0.0.)

**Comment by isidorn** [comment]
Hi @mattflix thanks for constantly providing useful feedback. However this is not documented because it is in the may - release which means it will be made public early June (yeah the naming is a bit confusing). Thus you should get nice inteli-sense and be able to configure debug console behavior with the next vscode release 1.2.
If you want to get this behavior before I think we will anounce our alpha channel soon, so stay tuned for that.

**Comment by mattflix** [comment]
Okay thanks, will look forward to that.

Am I crazy, or did the debug console reveal behavior change between 1.0.0 and 1.1.0?  (I swear I didn't have to constantly manually bring back the console on every launch, and now I do.)

Btw, I would love the ability to simply hit the Escape key to _toggle_ the console shown/hidden state (like it works in Chorme DevTools).  I tried, but could not make a VS Code key mapping do this for me.

**Comment by isidorn** [comment]
Yeah it changed, let me search for the issue... Here it is https://github.com/Microsoft/vscode/issues/4045
Yeah I also wanted that esc behavior and was fighting for it, but we have too many things binded to esc at the moment. So what works for me is esc when console has focus - closes it
And ctrl + J always toggles it - which is what I use in the end for my day to day development

**Comment by sandy081** [comment]
Tested.
