### ISSUE TITLE
Tasks should have an option to clear the terminal before executing

### ISSUE THREAD

**Issue by alexr00** [Microsoft/vscode#61592]
This clear option can be added into the exiting `"presentation"` task property and would be called `"clear"`:

    	{
			"label": "ExampleTask",
			"type": "shell",
			"command": "echo hello",
			"presentation": {
				"echo": true,
				"reveal": "always",
				"focus": false,
				"panel": "shared",
				"showReuseMessage": true,
				"clear": false
			}	
		}

Added to `TaskPresentationOptions`:

	/**
	 * Controls how the task is presented in the UI.
	 */
	export interface TaskPresentationOptions {
            ….
		/**
		 * Controls whether the terminal is cleared before executing the task.
		 */
		clear?: boolean;
	}

**Comment by roblourens** [comment]
This doesn't work for me:

``` 
{
    "label": "My Task",
    "type": "shell",
    "command": "echo Hello",
    "problemMatcher": [],
    "presentation": {
        "clear": true
    }
}
```

I run it multiple times and see all the output, the terminal is never cleared.

**Comment by alexr00** [comment]
Turns out that if the only presentation option set is clear, this doesn't work. Thanks for finding!
