### ISSUE TITLE
A11y_PowerShellEditorServices_Editor_Keyboard: ToolTip is not appeared on the keyboard focused

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#61591]
**Environment Details:**
VSCode Version : 1.25.0
OS Version : Win10

**Additional Details:**
keyboard,MAS2.1.1

**Repro Steps:**
1.Launch Visual Studio code desktop application.
2.Navigate to "Plain Text" of "StatusBar"->Enter "PowerShell" in "Select Language Mode"combobox->Write the PowerShell Code in plain editor->Save the editor.
3.Apply debugging and navigate to "Variables,Watch,Call Stack,Breakpoints"options.
4.Observed that tooltip is not appeared on keyboard fcoused.

**Actual:**
When the keyboard focused is appeared on the "Variables,Watch,Call Stack,Breakpoints"options  then tooltip is not display on the focused.

**Expected:**
On the keyboard focused tooltip should appeared.
Such as when keyboard fcoused is on "Add Expression,Collapse All,Remove All expressions" then tooltip should appeared on it.

**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
https://microsoft.sharepoint.com/teams/msenable/mas/pages/fixit-details.aspx?fixitid=91

**User Impact:**
User will not able to know the tooltip data on the control which provide the extra information related to controls.

**MAS Reference:**
MAS2.1.1-https://microsoft.sharepoint.com/%3Aw%3A/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc=%7B8492c4eb-c179-40ae-8777-cd044ed725a2%7D

**Attachment For Reference:**
[[Accessibility]A11y_PowerShellEditorServices_Editor_Keyboard.pptx](https://github.com/Microsoft/vscode/files/2505723/Accessibility.A11y_PowerShellEditorServices_Editor_Keyboard.pptx)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Also test on latest vscode
