### ISSUE TITLE
A11y_PowerShellEditorServices_Editor_Screenreader: NVDA is not reading placeholder value such as "Expression To Watch" text field.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#61597]
Environment Details:
VSCode Version : 1.25.0
OS Version : Win10

**Additional Details:**
NVDA,MAS1.3.1

**Repro Steps:**
1.Launch Visual Studio code desktop application.
2.Navigate to "Plain Text" of "StatusBar"->Enter "PowerShell" in "Select Language Mode"combobox->Write the PowerShell Code in plain editor->Save the editor.
3.Write powershell code and save the editor.
4.Use F9 to apply breakpoint and press F5 to start debugging.
5.Navigate to "Variables" option and click on "Add Expression" button.
6.Observed that screenreader is not reading placeholder value such as "Expression To Watch" text field.

**Actual:**
Issue1:NVDA is not reading the placeholder value such as "Expression To Watch".
Issue2:NVDA is not reading "Expression To Watch" is a "Editable" text field where user can enter the value.

**Expected:**
Issue1:NVDA should read the placeholder value such as "Expression To Watch".
Issue2:NVDA should read the "Expression To Watch" as a "Editable" text field where user can enter the value.

**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
https://microsoft.sharepoint.com/teams/msenable/mas/Pages/browse-fixes.aspx

**User Impact:**
If the screenreader is not mentioning it as editable text then user will not understand the use of the control.

**MAS Reference:**
MAS1.3.1-https://microsoft.sharepoint.com/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc=%7B54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4%7D

**Attachment For Reference:**
[[Accessibility]A11y_PowerShellEditorServices_Editor_Screenreader.pptx](https://github.com/Microsoft/vscode/files/2505781/Accessibility.A11y_PowerShellEditorServices_Editor_Screenreader.pptx)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
https://github.com/Microsoft/vscode/issues/51494
