### ISSUE TITLE
Unnecessery save changes dialog when deleting a file

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#616]
1. DIsable auto save
2. modify a file - do not save
3. delete that file
4. I first get a dialog if I am sure I want to delete, I say yes, then I get a dialog wheter I want to save changes to my file. 

I would not expect the second dialog since I just choose to delete that file

**Comment by bpasero** [comment]
Not showing the dialog would mean data loss. To be consistent we always ask. I am quite sure other editors work like this too.
