### ISSUE TITLE
Debug: on stop the current line is not read out

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [microsoft/vscode#61608]
**Environment Details:**
VSCode Version : 1.25.0
OS Version : Win10

**Additional Details:**
NVDA,MAS1.3.1

**Repro Steps:**
1.Launch Visual Studio code desktop application.
2.Navigate to "Plain Text" of "StatusBar"->Enter "PowerShell" in "Select Language Mode"combobox->Write the PowerShell Code in plain editor->Save the editor.
3.Write powershell code in the editor screen
4.Apply the breakpoint in editor using F9
5.Press F5 to start debugging.
6.Press F11 to stepinto the code of editor.
7.Observed that when the user press F11 to step into then nvda is not reading data.

**Actual:**
When user uses F11 to step into code then nvda is reading it as "Debugging Paused,reason step untitled-2.ps1 7"
eg if Invoke-Retestmethode is selected then nvda is reading it as "Debugging Paused,reason step untitled-2.ps1 7" but not reading text i.e "Invoke-Retestmethode "

**Expected:**
When user uses F11 to step into code then nvda should read the selected data text.

**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
https://microsoft.sharepoint.com/teams/msenable/mas/Pages/browse-fixes.aspx

**User Impact:**
If the nvda is not announcing the selected data then user will not understand on which function the keyboard focus stepinto. 

**MAS Reference:**
MAS1.3.1-https://microsoft.sharepoint.com/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc=%7B54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4%7D

**Attachment For Reference:**
[[Accessibility]A11y_PowerShellEditorServices_Editor_Screenreader.pptx](https://github.com/Microsoft/vscode/files/2505926/Accessibility.A11y_PowerShellEditorServices_Editor_Screenreader.pptx)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Works fine in latest

**Comment by isidorn** [comment]
Currently when the debugger stops we only read out that it stop on a line number something .
Assigning to may to fix then.

**Comment by isidorn** [comment]
Adding bug so we verify.
Verifier: make sure that when you are debugging and you step or the program stops that we read out the content on the stopped line

fyi @neurrone for possible feedback
