### ISSUE TITLE
A11y_PowerShellEditorServices_Editor_Screenreader: NVDA is reading three times "Added Breakpoint" and "Removed Breakpoint".

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#61607]
**Environment Details:**
VSCode Version : 1.25.0
OS Version : Win10

**Additional Details:**
NVDA,MAS1.3.1

**Repro Steps:**
1.Launch Visual Studio code desktop application.
2.Navigate to "Plain Text" of "StatusBar"->Enter "PowerShell" in "Select Language Mode"combobox->Write the PowerShell Code in plain editor->Save the editor.
3.Write powershell code in the editor screen
4.Start screenreader as nvda.
5.Apply breakpoint using F9 to any line of code.
6.Press F5 to start debugging.
7.Observed that nvda is reading three times "Added Breakpoint" and "Removed Breakpoint".

**Actual:**
After applying\removing break point nvda is reading it three times.

**Expected:**
After applying\removing break point nvda should read it only once not thrice. 

**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
https://microsoft.sharepoint.com/teams/msenable/mas/Pages/browse-fixes.aspx

**User Impact:**
If the nvda is announcing three times then it will confused the user.

**MAS Reference:**
MAS1.3.1-https://microsoft.sharepoint.com/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc=%7B54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4%7D

**Attachment For Reference:**
[[Accessibility]A11y_PowerShellEditorServices_Editor_Screenreader.pptx](https://github.com/Microsoft/vscode/files/2505912/Accessibility.A11y_PowerShellEditorServices_Editor_Screenreader.pptx)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Try with latest vscode version if you still see it please let me know and I will reopen
