### ISSUE TITLE
window.title error - ${folderName} == ${rootName}

### ISSUE THREAD

**Issue by alexmironof** [Microsoft/vscode#61612]
- VSCode Version: 1.29.0-insider
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. Add this line `"window.title": "${dirty}${folderName}/${activeEditorShort}${separator}${rootName}"` in `settings.json`
2. Open project from here: `anything/myProject`
3. Open file from here `anything/myProject/myFolder/myOtherFolder/myFile.txt`

ER: `●myOtherFolder/myFile.txt - myProject`
AR: `●myProject/myFile.txt - myProject`

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Works as designed: `${folderName}`: name of the workspace folder the file is contained in (e.g. myFolder).

**Comment by alexmironof** [comment]
@bpasero then comment for `window.title` is messed up. If I open workspace in `myProject` folder then `${folderName}` would never be `myFolder`, it is always top level folder eg. `myProject`

**Comment by bpasero** [comment]
@alexmironof a workspace folder is always the "thing" you open as workspace.
