### ISSUE TITLE
terminal integrado (PowerShell) 

### ISSUE THREAD

**Issue by luca0898** [Microsoft/vscode#61618]
Issue Type: <b>Bug</b>

**Por algum motivo quando executo o terminal integrado (PowerShell) o ponteiro não se exibe, sendo assim preciso acertar "Ctrl+C" para estourar erro e ele aparecer ...**

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (6.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
jslint|ajh|1.2.1
emulate|Die|0.0.7
beautify|Hoo|1.4.6
Angular-BeastCode|Mik|7.0.4
vscode-language-pack-pt-BR|MS-|1.28.2
debugger-for-chrome|msj|4.10.2
material-icon-theme|PKi|3.6.0

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/57803
