### ISSUE TITLE
Very slow start with snap package

### ISSUE THREAD

**Issue by nickyspag** [Microsoft/vscode#61613]
Issue Type: <b>Performance Issue</b>

Since upgrade to Ubuntu 18.10 - perhaps related - vscode takes over a minute to start up , maxing out CPU and sending load average soaring. Once system recovers vscode seems normal. However attempting to open a file from command line with command `code <filename>` returns immediately but takes similar amount of time - up to a minute - before file appears in the editor, though not with same high CPU symptom. 

An `strace -p` to the code process while it's starting up shows lots of lseek/reads  (I'm not sure how to interpret that info to be more helpful) - I presume it's reading through some massive amount of files/data or something?

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:20:56.183Z)
OS version: Linux x64 4.15.0-36-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz (4 x 1197)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|2, 2, 2|
|Memory (System)|7.72GB (0.39GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	   166	 31313	code main
    0	    40	 31315	   zygote
    0	   119	 31499	     shared-process
   27	   308	 32303	     window (Welcome - mp (Workspace) - Visual Studio Code)
    2	   158	 32326	       extensionHost
    0	     8	 32331	       /bin/bash
    0	    63	 32333	       watcherService
    2	   103	 32509	     window (Issue Reporter)
    0	     0	 32626	   /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 32627	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Welcome - mp (Workspace) - Visual Studio Code)
|    Folder (gtfe): more than 34258 files
|      File types: png(6182) jpg(4463) py(4080) js(3310) pyc(3056) sql(1670)
|                  pdf(1546) htm(1340) html(1045) ini(481)
|      Conf files: package.json(43) grunt.js(24) gulp.js(7) makefile(6)
|                  launch.json(1) settings.json(1) tslint.json(1)
|      Launch Configs: python(5)
|    Folder (mp): 5300 files
|      File types: py(1689) pyc(1681) h(184) txt(111) so(74) whl(23) exe(20)
|                  rst(18) json(17) conf(12)
|      Conf files: settings.json(1);
```

</details>
Extensions disabled

**Comment by nickyspag** [comment]
[b076-main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/2506148/b076-main.cpuprofile.txt)

**Comment by nickyspag** [comment]
A further observation: opening a file from the quick file picker (ctrl + p) opens quickly, as does opening file from traditional file open dialog (ctrl + o).

**Comment by nickyspag** [comment]
I noticed vscode was installed as a `snap` not a traditional `.deb` package, so I removed the snap and installed from downloaded .deb:

`sudo snap remove vscode`
`sudo dpkg -i code_1.28.2-1539735992_amd64.deb`

and now vscode is behaving normally!

**Comment by jrieken** [comment]
> I noticed vscode was installed as a snap not a traditional .deb package, 

@Tyriar you talked about this once, right?

**Comment by jrieken** [comment]
<img width="1005" alt="screenshot 2018-10-23 at 15 57 05" src="https://user-images.githubusercontent.com/1794099/47365684-5f034880-d6dc-11e8-9c5a-74d8813efa2c.png">


So, there is a v e r y long time in which nothing JavaScript'ish happens. This is mostly likely a delayed app read event. @nickyspag Do you still have the snap install? Can copy/paste what's being printed when calling "F1 > Startup Performance"?

**Comment by nickyspag** [comment]
@jrieken I uninstalled the snap, so that I could get some work done :-) but can easily reinstall it... BUT there is no visible window during the long startup for me to press F1 in ... is there another way (like with command line params) that I can get more useful info for you?

There is a warning when installing the vscode snap about it being a "classic" snap and one has to add the --classic option to get it to install - I know precious little about snaps but maybe something to do with it?

**Comment by jrieken** [comment]
> BUT there is no visible window during the long startup for me to press F1 in ... is there another way

Does it not finish? Eventually, when a window is being shown F1 should be functional...

> I know precious little about snaps but maybe something to do with it?

I know less but yeah sounds like this is a snap issue.

**Comment by nickyspag** [comment]
Sorry I thought you meant wHILE it was opening.

Here's what's in the Startup Performance console after starting the snap version:

![image](https://user-images.githubusercontent.com/144062/47369072-2f0b7380-d6e3-11e8-809f-d7be67752534.png)
[-1540305625449.log](https://github.com/Microsoft/vscode/files/2506599/-1540305625449.log)

**Comment by jrieken** [comment]
This is maybe the same as or very much related to #22087

**Comment by zerkz** [comment]
I am having the same experience after upgrading to cosmic (ubuntu 18.10), using the snap version. Going to install the deb binary and see how that works out!

-v output
```
1.28.2
7f3ce96ff4729c91352ae6def877e59c561f4850
x64
```
Startup Performance:
![image](https://user-images.githubusercontent.com/1448099/47499563-df819080-d825-11e8-825a-de598f27170a.png)

![image](https://user-images.githubusercontent.com/1448099/47499650-1788d380-d826-11e8-9f35-6052c444f7ba.png)

**Comment by jrieken** [comment]
@Tyriar slow, snap, rings a bell?

**Comment by zixia** [comment]
I have the same problem after I upgraded to Ubuntu 18.10 with snap version of vscode.

**Comment by joaomoreno** [comment]
I've gotten a very promising update on a snapd fix:

- Cold start launch time was reduced from ~1min 37secs to ~23secs
- Hot start lunch time was reduced from 1min 32secs to ~5secs

This was done on the same machine running 18.10 with those latest changes. I was told the changes are not out yet, but coming soon.

**Comment by jrieken** [comment]
Much better but still slow. Having 23secs for the first startup isn't something I would endure, esp. not as an Insiders user. Do they have plans to make this fast?

**Comment by scruti** [comment]
I believe this has been recently fixed. Start time has turned almost instant.

**Comment by flexiondotorg** [comment]
@Tyriar This can be closed.
