### ISSUE TITLE
Terminal invisible have to press enter twice

### ISSUE THREAD

**Issue by mxschmitt** [Microsoft/vscode#61614]
Issue Type: <b>Bug</b>

Hello,

In one of the latest insider releases, there is a bug that I have to press twice enter before the real terminal output will appear.
It will occur, once I will open a new terminal:
![image](https://user-images.githubusercontent.com/17984549/47362005-af29dd00-d6d3-11e8-9a59-626114f8a0db.png)

VS Code version: Code - Insiders 1.29.0-insider (d1f5894892e3719846bbd4bd0dd75f117f211ab5, 2018-10-23T05:20:39.912Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (9.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|40%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.6.1
githistory|don|0.4.3
xml|Dot|2.3.2
shell-format|fox|1.1.3
vscode-github|Kni|0.30.0
sftp|lix|1.7.0
python|ms-|2018.9.1
Go|ms-|0.6.93
vscode-docker|Pet|0.3.1
code-settings-sync|Sha|3.2.0
vscodeintellicode|Vis|1.0.5
jinja|who|0.0.8
vscode-import-cost|wix|2.9.0

</details>

**Comment by romanoledergerber** [comment]
Same Issue Version 1.28.2
