### ISSUE TITLE
Debug Powershell in Insiders Build

### ISSUE THREAD

**Issue by timchap** [Microsoft/vscode#61619]
Issue Type: <b>Bug</b>

When I try to debug powershell code in the Insiders build (latest) I get the error "Cannot read property 'OnError' of undefined".  Debugging works fine on the non-insiders build.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.79GB (36.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
PowerShell|ms-|1.9.0

</details>

**Comment by weinand** [comment]
You are not using the latest Insiders (which has version 1.29.0-insider and is from 2018-10-23T05:06:01.229Z).

Please try the latest Insiders and report back if you still see this issue.

**Comment by timchap** [comment]
I reported the bug from the xcopy version (non-insiders where it was working).  I can submit the bug from the version w/ the bug if you’d like.  Here is my insiders version:

[cid:image001.png@01D46AB8.BE154A20]

**Comment by weinand** [comment]
@timchap I cannot see the Insiders version because your screenshot did not make it into this issue.
