### ISSUE TITLE
[Feature request] Option to highlight changed lines against a specified branch, rather than against head

### ISSUE THREAD

**Issue by lolmaus** [Microsoft/vscode#61610]
Hi!

VS Code highlights changed lines against head branch, just like any other IDE does. This means that you can see only uncommitted edits.

I am typically working on a feature for several days. At the end of every day I need to commit my work in order to report my progress and back it up.

After I commit, I no longer see edits that I'm introducing with the given feature.

**I want changed lines to stay highlighted even after I commit**. This could be achieved by letting users select a branch to compare against (head by default).

As a workaround, I'm using [GitLens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens) feature `Compare Ancestry with Working Tree` against the dev branch. This works, but it is a very elaborate action, and it shows results in a separate window. I want changes to be highlighted inline as I work on files.

Thank you for your attention. :bow:

**Comment by oriash93** [comment]
Might be related to #36893

**Comment by lolmaus** [comment]
Closing in favor of #36893. Thank you, @oriash93.
