### ISSUE TITLE
Shortcut for select_word

### ISSUE THREAD

**Issue by lubrogit** [Microsoft/vscode#61628]
Hi,
I would welcome expandWordSelection equivalent to mouse doubleclick or similar to ctrl+J in UltraEdit. This command is more frequent than expandLineSelection (ctrl+I) that can be achieved with twice Expand Select (shift+alt+rightArrow).
This is a suggestion for pure cosmetics but may help many.
Regards
lubrogit

**Comment by alexandrudima** [comment]
Did you try <kbd>Ctrl</kbd>+<kbd>D</kbd> ?
