### ISSUE TITLE
Ctrl-P finder does not find all files with the same name in the workspace

### ISSUE THREAD

**Issue by cdunford** [Microsoft/vscode#61627]
Issue Type: <b>Bug</b>

I do not know specifically what causes this issue to occur, but I work in multiple different single folder workspaces which exhibit the problem. Within my workspace, I have several files with identical names, but at different locations (typically different depths); when I Ctrl-P to find a file and I type one of these names, I only get a subset of the files listed and not all of them.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|15.68GB (8.21GB free)|
|Process Argv|--folder-uri file:///c%3A/Code/xpression-vista-addon|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by roblourens** [comment]
First can you check the wiki page to see whether any tips there are relevant? https://github.com/Microsoft/vscode/wiki/Search-Issues#missing-search-results

**Comment by cdunford** [comment]
I've checked the wiki and don't believe any of those factors are effecting this. The workspace in question has no .gitignore file; search.exclude looks like:

![image](https://user-images.githubusercontent.com/1405868/47432254-bef50000-d76b-11e8-9ac0-93f6ee003407.png)

files.exclude is still the default:

![image](https://user-images.githubusercontent.com/1405868/47432274-cd431c00-d76b-11e8-9b24-206413ef40a3.png)

The file in question is UTF-8:

![image](https://user-images.githubusercontent.com/1405868/47432415-15fad500-d76c-11e8-8868-f3af21242012.png)

And file line endings are CRLF:

![image](https://user-images.githubusercontent.com/1405868/47432456-2b6fff00-d76c-11e8-8dc4-377d77db7d59.png)


Let me know what else you might need.

**Comment by roblourens** [comment]
Can you find other files next to that missing file or under VCAgent?

**Comment by cdunford** [comment]
Actually, no I can't. Including things with unique names in the workspace.

**Comment by roblourens** [comment]
Could there be a .gitignore file somewhere else in the folder structure? You can turn off `search.useIgnoreFiles` to make sure.

Another way to debug this is to rule out exclude patterns and ignore files entirely by doing a text search and toggling off the  "Use Exclude Settings and Ignore Files" button (bottom right)

![image](https://user-images.githubusercontent.com/323878/37785522-9b4d3162-2db7-11e8-9011-5ca513e789b9.png)

**Comment by cdunford** [comment]
Yeah I missed an ignore file in a subfolder 😞
