### ISSUE TITLE
Git Extension Sidebar: Resource Blocking

### ISSUE THREAD

**Issue by jundialwan** [Microsoft/vscode#6162]
- VSCode Version: 1.0.0
- OS Version: Windows 10 Pro

Hi,

I want to post an issues about git extension performance.
I suspect git extension in the sidebar is blocking the memory that VS Code using. I experience some lag when I try to type my code.

This is occur when git refresh it status because it become laggy when loading icon appear on git sidebar, after I edit some of my code.

This is not always happening when I edit my code but very often.

Thank you

**Comment by joaomoreno** [comment]
Do you have many active changes?

**Comment by jundialwan** [comment]
Yes.
At least 5 files with active change.

**Comment by jundialwan** [comment]
I have no problem when opening folder or crashed.
It just feels lag on typing when there are some change not committed, like something blocking the cursor.

**Comment by joaomoreno** [comment]
@jundialwan Can you try the latest [insider release](https://code.visualstudio.com/insiders) and see whether you still see this issue?

**Comment by joaomoreno** [comment]
@jundialwan Ping
