### ISSUE TITLE
Use File Icon for suggestions doesn't work in .jsx file imports

### ISSUE THREAD

**Issue by Astrantia** [Microsoft/vscode#61625]
Create a .jsx file, and write import {asd} from '../'.
No icons are shown for files. 
I reported this in #44860 but it was closed without a response.

**Comment by mjbvz** [comment]
@jrieken This is just based on the label, correct? 

TS intentionally does not insert file extensions in paths (since you would not want to be importing a `.ts` path in the compiled javascript)

**Comment by jrieken** [comment]
It's label and/or detail, whatever matches best: https://github.com/Microsoft/vscode/blob/9742f05593cd36a28284eaf8ed8c95edc34a7d56/src/vs/editor/contrib/suggest/suggestWidget.ts#L169-L170

I agree that the label should be without suffix but I think the detail is a good place for it

**Comment by isidorn** [comment]
Works great now

![screenshot 2018-12-04 at 17 19 33](https://user-images.githubusercontent.com/1926584/49456140-ca1a6180-f7e8-11e8-8d11-0f7f80adddca.png)
