### ISSUE TITLE
Build: Loading "node-pty" failed after cross-compiling to arm64

### ISSUE THREAD

**Issue by 435vic** [Microsoft/vscode#61623]
I am trying to build 1.28.2 for ARM64 on Travis CI.
The build passes, but the installation is not working. A blank screen launches, and the console says that "loading 'node-pty' failed".
![image](https://user-images.githubusercontent.com/13788817/47368750-cb178980-d6a7-11e8-8a2c-0031146199c1.png)

Steps to Reproduce:

1. Go to my [test repository](https://github.com/435vic/vscode-arm64).
2. Download, install and run 1.28.2 from the releases section.

The build logs are in the [Travis CI page](https://travis-ci.com/435vic/vscode-arm64).

The output of `code-oss --verbose` is [here](https://pastebin.com/2GUp7VUm).
All I do on the repository is update yarn to 1.10.1, set `npm_config_arch=arm64`, git clone the repo, and run the arm64 build targets.

**Comment by stripedpajamas** [comment]
cc: @headmelted @ava1ar from https://github.com/Microsoft/vscode/pull/52119

**Comment by 435vic** [comment]
I checked the paths to the "missing" files and it turns out they weren't missing at all:
![image](https://user-images.githubusercontent.com/13788817/47766209-2ee71700-dc93-11e8-8a93-914786187210.png)
![image](https://user-images.githubusercontent.com/13788817/47766249-648c0000-dc93-11e8-9c63-bd0dd32dc24d.png)
However, I can see with `file` that the files are not arm64 compatible:
``` 
➜ file pty.node 
pty.node: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=5eda743055b93473214eedeb4b4c7faea6952838, not stripped
```
Why is this happenning? Shouldn't all packages be built to arm64 if `npm_config_arch` is set to arm64?

**Comment by Tyriar** [comment]
This is where node-pty is built https://github.com/Microsoft/node-pty/blob/912bed984164b85a9531eb83d66b4c7343d44da6/scripts/install.js#L7

Maybe something needs to be passed through to it?

**Comment by 435vic** [comment]
Actually, *all* of the dependencies in `resources/app/node_modules.asar.unpacked` are 64 bit, maybe we are missing a flag or something?

**Comment by headmelted** [comment]
Just for the sake of completeness, it might be worth also setting
npm_config_target_arch (depending on how your setting up your environment).

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/6442
