### ISSUE TITLE
Git preserves commit message even after deleting & reloading

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#61629]
Issue Type: <b>Bug</b>

This happens to all projects on my machine.

![git](https://user-images.githubusercontent.com/4033249/47371738-2db75800-d69d-11e8-94e4-27b54704841c.gif)

VS Code version: Code - Insiders 1.29.0-insider (d1f5894892e3719846bbd4bd0dd75f117f211ab5, 2018-10-23T05:11:31.086Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.70GB free)|
|Process Argv|-psn_0_2155022|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.1.3
tslint|eg2|1.0.40
vsc-material-theme|Equ|2.4.2
prettier-vscode|esb|1.6.1
vscode-pull-request-github|Git|0.2.1
theme-monokai-pro-vscode|mon|1.1.8
vscode-language-pack-de|MS-|1.28.2
Go|ms-|0.6.93
debugger-for-chrome|msj|4.10.2
vetur|oct|0.13.0
polacode|pnp|0.2.2
shader|sle|1.1.4
language-stylus|sys|1.10.0
vim|vsc|0.16.11

(2 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Oh wow, show me in person!

**Comment by joaomoreno** [comment]
This was a configured git commit message template. 😆
