### ISSUE TITLE
Git edit tracking not working

### ISSUE THREAD

**Issue by balmungsama** [Microsoft/vscode#61633]
```
Windows 10, build 1803
Surface Book 2, 15 inch
Version: 1.28.2 (system setup)
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:23:51.859Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

I'm editting my Matlab script in VS Code, and previously all of the git change tracking issues worked perfectly. But now my changed are not being tracked in-line, nor do they show up in the source control panel. 

I know this is a VS Code issue because my git manager of choice, Fork, is able to track changes I make perfectly.

![image](https://user-images.githubusercontent.com/10139189/47373794-89440e80-d6ba-11e8-8be7-e8f882d62d99.png)

**Comment by joaomoreno** [comment]
What does `Git: Show Git Output` show?

**Comment by balmungsama** [comment]
> What does `Git: Show Git Output` show?

Nothing comes up.

I just noticed that most of my extensions also don't seem to be loading, despite being listed as Enabled. I should have plenty visible in the status bar, but only Kite seems to actually be on.

**Comment by balmungsama** [comment]
I fixed it. I just had to disable all extensions, reload, and then re-enable them. 

Not sure why this happened, but everything seems good now.

**Comment by joaomoreno** [comment]
cc @alexandrudima
