### ISSUE TITLE
Context for "Log Storage" string, please

### ISSUE THREAD

**Issue by aldonetti** [Microsoft/vscode#61632]
Hi, as part of the localization process, the translators have encountered the string "Log Storage" string and are wondering what's the exact context, please. 
this is the source file https://github.com/Microsoft/vscode/blob/master/src/vs/platform/storage/node/storageService.ts

Is it a setting or else? Where is it used?
Does it prompt to specify a path? or a boolean to enable a logging service? is it the main VSCode logging service or other?

thanks!!

**Comment by bpasero** [comment]
I renamed the action to "Log Storage Database Contents" and added a comment: A developer only action to log the contents of the storage for the current window.
