### ISSUE TITLE
Show loading indicator while js/ts language features are first being initialized

### ISSUE THREAD

**Issue by axetroy** [Microsoft/vscode#61636]
Issue Type: <b>Bug</b>

I open a small ts project. just 2 ts files.

and language server always in initialization

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|8.00GB (0.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-auto-schema|axe|0.1.0
vscode-gpm|axe|1.0.0
vscode-markdown-script|axe|0.0.1
vscode-npm-import-package-version|axe|0.1.8
indented-block-highlighting|byi|1.0.7
bracket-pair-colorizer-2|Coe|0.0.22
vscode-svgviewer|css|1.4.7
vscode-eslint|dba|1.6.1
githistory|don|0.4.3
gitlens|eam|8.5.6
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.40
vsc-material-theme|Equ|2.4.2
php-intellisense|fel|2.3.5
terminal|for|0.0.10
vscode-nginx-conf-hint|han|0.1.0
vue-snippets|hol|0.1.9
vscode-color-exchange|Iro|1.1.0
vscode-hacker-typer|jev|0.1.1
intellij-idea-keybindings|k--|0.2.27
vscode-colorize|kam|0.7.2
git-indicators|lam|2.1.1
vscode-clang|mit|0.2.3
vscode-language-pack-zh-hans|MS-|1.28.2
python|ms-|2018.9.1
cpptools|ms-|0.19.0
Go|ms-|0.6.93
gremlins|nho|0.7.0
vetur|oct|0.13.0
indent-rainbow|ode|7.2.4
vscode-docker|Pet|0.3.1
material-icon-theme|PKi|3.6.0
nginx-formatter|ray|0.0.4
postcss|ric|2.0.0
px-to-rem|sai|1.2.7
code-settings-sync|Sha|3.2.0
vscode-nginx|sha|0.5.0
trailing-spaces|sha|0.2.11
markdown-preview-enhanced|shd|0.3.8
gitconfig|sid|2.0.0
code-spell-checker|str|1.6.10
open-in-browser|tec|2.0.0
vscode-todo-highlight|way|1.0.4
json-helper|zho|1.3.2

</details>

**Comment by axetroy** [comment]
@weinand 
I have disabled all extensions and restart again. It works now.

But the strange thing is that I will have this problem after I enable some extensions.

I can not get any useful information from dev tool

**Comment by williansabiao** [comment]
Guys, I don't know if it's relevant, but I used to have the same problem, and it occurs because of my `jsconfig.json`. After I changed one rule, it works.

Moreover, this problem started after my last vscode update, some days ago.

The rule was from `"RootDuck/**/*": ["duck/**/*"]` to `"RootDuck/*": ["duck/*"]` inside of `compilerOptions.paths`.

I hope it helps; maybe some extension is using a rule like that in your case @axetroy.

**Comment by weinand** [comment]
@axetroy what extension introduces the slowness?

**Comment by DanZeuss** [comment]
Same here @bluppfisk ... I've got the same error, however, I don't know how to contribute in terms of what information would be needed to diagnose this bug.
