### ISSUE TITLE
Ability to move custom views across containers

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#61630]
Extensions contributing view containers and views are providing a feature allowing users to choose the view container into a contributed view can be shown. Under the hood extensions register multiple same views with different ids for each location and use the when context to define the visibility. This is cumbersome from an implementation perspective also causing issue like https://github.com/Microsoft/vscode/issues/57422

Cleaner way is to VS Code OOB provides support to move contributed views across view containers

**Comment by eamodio** [comment]
@alexr00 Should this be closed now that views can be moved by the user?

**Comment by sandy081** [comment]
True, this can be closed.
