### ISSUE TITLE
Copy JSON object from debugger to memory (i.e. Webstorm copy)

### ISSUE THREAD

**Issue by rossvz** [Microsoft/vscode#61631]
Webstorm's debugger has an amazing option to copy a JSON value to clipboard. Especially useful to avoid writing unnecessary `console.log` statements and trying to copy a stringified output.

Essentially, in the debugger area, you could right-click and "copy JSON" which copies the entire object. There seems to be a "Copy Value" option right now but it literally just copies the string of 
`myVariable: [object]` which is really useless.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/27950
