### ISSUE TITLE
Network usage with disabled Telemetry and extensions

### ISSUE THREAD

**Issue by crash5** [Microsoft/vscode#61646]
Issue Type: <b>Bug</b>

When start VSCode with disabled telemetry and extensions it is try to connect to these hosts:
1. dc.services.visualstudio.com:443
1. az764295.vo.msecnd.net:443

How to stop VSCode to connnect to anywhere?

Steps to Reproduce:
1. start with `code  --disable-extensions`

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz (4 x 1995)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (12.74GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled

**Comment by crash5** [comment]
My settings to disable the network connections:
```
    "extensions.autoCheckUpdates": false,
    "extensions.autoUpdate": false,
    "extensions.showRecommendationsOnlyOnDemand": true,

    "workbench.settings.enableNaturalLanguageSearch": false,
    "workbench.enableExperiments": false,

    "telemetry.enableCrashReporter": false,
    "telemetry.enableTelemetry": false,

    "update.channel": "none",
    "update.showReleaseNotes": false,

    "npm.fetchOnlinePackageInfo": false,
    "git.autofetch": false,
    "update.enableWindowsBackgroundUpdates": false,
```

**Comment by ramya-rao-a** [comment]
Thanks for reporting this @crash5!

As per [IP address used by AppInsights](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-ip-addresses), `dc.services.visualstudio.com:443` is used by the applicationInsights sdk.

If you have telemetry disabled, then the sdk shouldnt have been initialized at all. I will look into it.

`az764295.vo.msecnd.net:443` points to the cdn for a blob storage and is used in 3 scenarios:
- To get list of malicious extensions that shouldnt be loaded
- To get data for the extension recommendations of the kind "This extension is popular among the users of this workspace"
- To get list of some UI experiments that we run from time to time. 

Based on your settings, you have disabled the second and third feature. I'll have to check if the malicious extension check is being made when no extensions are loaded.

**Comment by joaomoreno** [comment]
@ramya-rao-a I see two PRs were merged, should this issue be closed?

**Comment by ramya-rao-a** [comment]
Yes, I was waiting for a Insiders build with the fix before closing this.

@crash5 With the latest [Insiders](https://code.visualstudio.com/insiders), when you run `code-insiders --disable-extensions --disable-telemetry` along with all the settings you have already set to [disable network connections](url
https://github.com/Microsoft/vscode/issues/61646#issuecomment-432811668), you should no longer be  seeing any outgoing network connections.

Can you please give the insiders a try?

**Comment by crash5** [comment]
Sorry for the late reply. Thank you for your work @ramya-rao-a .

<details>
<summary>Tested with 1.29.1</summary>

```
Version: 1.29.1 (user setup)
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

</details>


- With `--disable-extensions --disable-telemetry` it looks fine.
- With the settings above and without the `--disable-telemetry` option still try to connect to dc.services.visualstudio.com:443.

If I'm right:
1. I can't disable telemetry only from settings I have to use the `--disable-telemetry` argument to start the vscode?
1. It's not possible to disable the malicious extensions check from settings. It works only with `--disable-extensions` option on start?


Ps: The `code -h` command output does not contains the `--disable-telemetry` option.

**Comment by ramya-rao-a** [comment]
> I can't disable telemetry only from settings I have to use the --disable-telemetry argument to start the vscode

Yes. This is true. I have logged #63404 to track this. Please subscribe to that issue

> It's not possible to disable the malicious extensions check from settings. It works only with --disable-extensions option on start

Yes, we don't want to have a setting to disable the check as you can understand this is an important check to make if you are using extensions from the marketplace.

> The code -h command output does not contains the --disable-telemetry option.

@joaomoreno Any idea why this is so?

**Comment by ramya-rao-a** [comment]
Thanks @joaomoreno 
I have updated 
https://github.com/Microsoft/vscode/issues/63404 with the your note
