### ISSUE TITLE
file.x (deleted from disk)

### ISSUE THREAD

**Issue by lallousx86** [Microsoft/vscode#61645]
- VSCode Version: latest
- OS Version: n/a

Steps to Reproduce:

1. Open a Python file that exists on disk
2. Delete the file from disk (externally, from the command prompt)
3. VS Code changes the open file's tab title to: file.x (deleted from disk)
4. Re-save that deleted file to re-create it
5. VS Code still says: file.x (deleted from disk) although the file now exists

Suggestion:
- Update the title accordingly when the (previously deleted) file is re-saved

**Comment by bpasero** [comment]
@lallousx86 how do you save the file back, by saving in the editor?

**Comment by lallousx86** [comment]
@bpasero yes, correct, by pressing Ctrl+S. I realize that this might be a duplicate of #33193

**Comment by bpasero** [comment]
@lallousx86 it would be easy to validate that, just run "code --verbose" and follow the steps. You should see file events printed to the developer console (Help > Toggle Developer Tools).

**Comment by bpasero** [comment]
@lallousx86 actually this is weird, I just verified that the "deleted from disk" label should go away as soon as you save successfully even when file events do not work. did you verify that the file shows up on disk?
