### ISSUE TITLE
Light bulb icon doesn't appear in editor when there are fixes available

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#61642]
Someone reported to me that lightbulbs have stopped showing in the editor, and sure enough I can repro.

A few months ago:

![screen shot 2018-10-23 at 6 34 17 pm](https://user-images.githubusercontent.com/1078012/47379293-63d2f700-d6f2-11e8-8b0b-813345a70e66.png)

Now:

<img width="468" alt="screen shot 2018-10-23 at 6 34 10 pm" src="https://user-images.githubusercontent.com/1078012/47379299-67ff1480-d6f2-11e8-8a12-c91482a437e2.png">

Note: I have *not* set the `editor.lightbulb.enabled` setting - it's still true.

I've searched around but can't find any mention of this being deliberate (though also surprisingly, I can't see many others complaining it's disappeared either).

Is this a bug?

**Comment by RandalSchwartz** [comment]
We should point out that the lightbulb *never* shows up now, and the only way to get that pop-up menu is to invoke the refactor command (command-dot on a Mac, for example).

**Comment by DanTup** [comment]
Current stable. Seems like I do see them for TS too, it may be only for Dart they're missing for. Are there any restrictions on what type of code actions will cause lightbulbs to show now? If not, is there somewhere useful I can put a breakpoint and try to debug?

**Comment by jrieken** [comment]
> Are there any restrictions on what type of code actions will cause lightbulbs to show now? 

It does depend on the type of the code action and should be quick fixes and refactoring. I don't think anything as changed for 1.28 here but @mjbvz will know for use

**Comment by DanTup** [comment]
It's possible it's been like this longer than 1.28, neither of us are sure when we last saw them. It may all be working as intended from Code's side, but it'd be good to know the intention so I can ensure Dart is consistent with other languages.

**Comment by DanTup** [comment]
(also: I don't think this needs-more-info, at least not from me :-))

**Comment by jrieken** [comment]
> (also: I don't think this needs-more-info, at least not from me :-))

I still don't what code action kinds you send? And actually still don't know what chance you expect from us?

**Comment by DanTup** [comment]
> I still don't what code action kinds you send?

The ones in the screenshots at the top are refactors (`CodeActionKind.Refactor`).

> And actually still don't know what chance you expect from us?

Not a change, but I'd like to know what the requirements are for showing the light bulb. I thought that any code action would cause the lightbulb (it seems like it used to, but doesn't now). What's the expected behaviour? Is it only QuickFixes that cause the lightbulb? Anything with a diagnostic? Anything except Refactor?

If it's expected behaviour, that's fine - it was just a surprise and I don't know if it's intended or a bug.

**Comment by jrieken** [comment]
my knowledge is that refactorings and quick fixes trigger the lights but source code actions don't. leaving it up to @mjbvz

**Comment by DanTup** [comment]
I saw in in TypeScript so I presume it's only Dart, but I'd need to do more testing. I'm about to leave the house for a few days, but can do more when I get back. I believe the fixes in the screenshot at the top came from one of these:

https://github.com/Dart-Code/Dart-Code/blob/master/src/providers/assist_code_action_provider.ts#L31-L33
https://github.com/Dart-Code/Dart-Code/blob/master/src/providers/refactor_code_action_provider.ts#L43

They're using `CodeAction.Refactor` and `CodeAction.Refactor.append('foo')`. Could it be the append?

**Comment by DanTup** [comment]
@mjbvz 

> Refactors should definitely trigger the lightbulb

This appears to not be the case:

```new CodeAction("refactor", CodeActionKind.Refactor),`

![screen shot 2018-11-05 at 12 03 14 pm](https://user-images.githubusercontent.com/1078012/47997210-f7dd8f00-e0f2-11e8-8408-8a0e60c0f9b7.png)

```new CodeAction("quifix", CodeActionKind.QuickFix),```

![screen shot 2018-11-05 at 12 03 38 pm](https://user-images.githubusercontent.com/1078012/47997198-edbb9080-e0f2-11e8-8840-a51340fea67e.png)

The lightbulb is appearing for quick fixes, but not for my refactors (it doesn't matter whether they're `CodeActionKind.Refactor` or `CodeActionKind.Refactor.append('foo')`, neither show the lightbulb).

**Comment by mjbvz** [comment]
Actually this appears intentional: https://github.com/Microsoft/vscode/commit/ab77235bfb26c3d368c32ba2b22c79eea3e34cca#diff-6a16a6b99ba0b3c9bf8054cbff4e0bc1

This was originally done because we were concerned about showing the light bulb too often while moving through a file. We can try relaxing this for November and see if people dislike the behavior

**Comment by DanTup** [comment]
@mjbvz thanks! If you were used to clicking the lightbulb to get the refactors, it vanishing just makes it seem like they've disappeared. I understand having the lightbulb "everywhere" seems a bit noisy, but if there are options available I think it's reasonable.

If you do decide to revert this, I think it's definitely worth calling out in the release notes (apologies if you did last time, I didn't see it and I do generally read them all!).
