### ISSUE TITLE
Monaco.d.ts generation needs improvements

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#61657]
For one, it's incredibly annoying when jumping between branches. It seems that I **always** have to restart gulp when switching branches due to `monaco.d.ts` (and now `standaloneEnums.ts` too). We can surely do better here.

Also, `monaco.d.ts` generation is hardly the most important thing in our build, why are its messages in ALL CAPS? Lets just make them play nicely with all our other messages.

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/22350/47396494-e4d4c300-d6df-11e8-9ff4-d75a26fb11ab.png">

On top of all of this, can we perhaps find another way to do this that doesn't involve committing computed changes? It seems to me that this would be much better implemented using a continuous build check.

**Comment by alexandrudima** [comment]
I can build a version checking mechanism into the `monaco.d.ts` generation (in `monaco.d.ts.recipe`) to make the error message more clear.

**Comment by alexandrudima** [comment]
Here are the improvements I pushed today:
- introduced a version number in `monaco.d.ts.recipe`. If the in-memory gulp watch loads with a different tooling version number, an error message is displayed inviting you to restart gulp watch.
- reduced the output generated by the `monaco.d.ts` generation both in the happy and in the error case
- changed the way `.ts` files are read to keep less initial state, i.e. be more tolerant to edits done to `monaco.d.ts.recipe`.
- changed the error message color to yellow to indicate that this is not a critical error.

If you have further ideas how to completely avoid the need for `monaco.d.ts` or how to do tree shaking / ship the standalone editor, please feel free to share them with me / Peng.

**Comment by joaomoreno** [comment]
@alexandrudima Thanks for writing this up! cc @Microsoft/vscode

**Comment by joaomoreno** [comment]
In my mind, the question is really about why is `monaco.d.ts` checked in? I know you have answered this to me, and I'm always forgetting... Is it because there are tools which fetch it directly from our GH repo or because you want people to be aware when they are changing editor API by having a modification marked in Git?

**Comment by alexandrudima** [comment]
Because it is part of the compilation and for example [here](https://github.com/Microsoft/vscode/blob/9b2b174cec7f65c1a80ef2abd177e2ece5ab9320/src/vs/editor/common/standalone/standaloneBase.ts#L28) the type `monaco` is used to ensure that we are really implementing and shipping what we are declaring we are shipping.

We use the same principle with the `vscode` API, we want that the implementation of the API is implementing the API and not something else.

**Comment by joaomoreno** [comment]
It seems to me, as @jrieken has pointed out before, that we got it right with `vscode.d.ts`. If it's being used as part of the compilation, we should probably be authoring it manually instead of generating and checking it into source.

In any case, good job, it seems pretty stable and quite fast now! 👏
