### ISSUE TITLE
VS Code Insiders breaks Go to Definition with multiple results

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#61654]
- VSCode Version: 1.29.0-insiders
- OS Version: Windows 

Steps to Reproduce:

1. Use Go to Definition such that it gives multiple results. Using the C/C++ extension with multiple .cpp files with code such as "void func(){}" should repro the issue.

Does this issue occur when all extensions are disabled?: I don't know. It doesn't appear to be a bug with our extension.

Bug: The dialog box that shows the multiple results doesn't appear and it just goes directly to one of the results. The bug doesn't repro with Peek Definition or with the Non-Insiders VS Code, so it appears to be a regression. I've verified that our extension is returning the multiple results via the LSP.

**Comment by jrieken** [comment]
I cannot reproduce with Insiders or with latest from master and a simple sample. Please update your steps

**Comment by jrieken** [comment]
Not for me. The behaviour of stable and latest from master is the same... Please try with latest, latest insiders. There have been some uri which we reverted early this week which might have something todo with it... 

![oct-25-2018 09-50-37](https://user-images.githubusercontent.com/1794099/47484210-7442b900-d83b-11e8-9d54-8627765443c0.gif)

**Comment by sean-mcmanus** [comment]
I figured out why you are not reproing it -- close files Source1.cpp and Source2.cpp, i.e. the files with the definitions. I've also reproed the bug on Mac (i.e. 3 different machines).

**Comment by jrieken** [comment]
![oct-25-2018 09-50-37](https://user-images.githubusercontent.com/1794099/47614389-9177c180-da9f-11e8-9707-baf085e00d30.gif)

I still not reproduce, please keep distilling those steps

**Comment by sean-mcmanus** [comment]
Some one appears to have fixed the bug -- I had commit 4a29bd3731e40c07622bae0e9b0ac3b422b5672a which reproed the bug and then updated to the latest commit 97ad72a02c351d6cde0fd32b41d9700a43e5964a and the bug was fixed. So I'm closing this.
