### ISSUE TITLE
No cursor in the integrated terminal

### ISSUE THREAD

**Issue by usmanibnesadiq** [Microsoft/vscode#61666]
Issue Type: <b>Bug</b>

On windows 10 October update, both VS Code stable and Insider dont show mouse cursor at all when you open the terminal (no matter if its cmd or powershell or bash). If you just start typing any command, the text appears randomly 3-4 lines below, where the cursor should be. However, if you just press enter at least once in ther terminal then the cursor does show up but still dosnt blink.

VS Code version: Code - Insiders 1.29.0-insider (d1f5894892e3719846bbd4bd0dd75f117f211ab5, 2018-10-23T05:20:39.912Z)
OS version: Windows_NT x64 10.0.17763

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/57803
