### ISSUE TITLE
VS Code hogs up the CPU almost all the time after update

### ISSUE THREAD

**Issue by ftrofin** [Microsoft/vscode#61665]
Issue Type: <b>Bug</b>

I've been very happy with VS Code until recently when it updated to the latest version. It was nimble and fast, it just worked. Now it's slow and it hogs up my computer's CPU (constant CPU utilization 25-50% all the time VS Code is running). The extension that's using the CPU is the CPP extension which I've been using before with no issues.
The processes that show almost constant CPU usage are: "Code Helper" and "Microsoft.VSCode.CPP.Extension.darwin".
I also noticed that the Cmd+P (open file) is very slow, it can take up to a minute to find a file, before it was finding it in seconds.
Search in files is also much slower than before. I frequently abandon searches because they don't complete in a minute or more.
Overall, this is a huge performance regression. If we can't make VS Code as fast as it was before (for C++ development) it looses all its appeal over its older brother Visual Studio :-)

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 17.7.0 (Mac OS 10.13.6)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|40, 17, 9|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gtest-adapter|Dav|1.4.0
bazel-code|Dev|0.1.9
python|ms-|2018.9.1
cpptools|ms-|0.19.0
perforce|sle|3.1.0

</details>

**Comment by ftrofin** [comment]
I tried taking a sample of the Code Helper while it was chewing 20% of my CPU but unfortunately the symbols are not available, see attached. Please let me know if i can provide any other useful info for debugging this.

[Sample of Code Helper.txt](https://github.com/Microsoft/vscode/files/2509052/Sample.of.Code.Helper.txt)

**Comment by weinand** [comment]
file this against C++ extension
