### ISSUE TITLE
.NET Dictionary data structure won't let me access the last element!

### ISSUE THREAD

**Issue by Braineeee** [Microsoft/vscode#61668]
Issue Type: <b>Bug</b>
My project uses a string as a key to a .NET dictionary. When I fill out the dictionary with appropriate string keys and gameobject values (I am using Unity3d), and then try to access the very last element of the dictionary, I get a null ref. The last element is NOT accessible. 

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2397)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.43GB (2.81GB free)|
|Process Argv|C:\Users\Jakeeee Snakeeee\Documents\PROJECTS\MouseFlightTutorial\Assets\Scripts\AgentControl.cs|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.9.1
csharp|ms-|1.16.2
java|red|0.33.0
unity-debug|Uni|2.6.6
vscode-java-debug|vsc|0.14.0
vscode-maven|vsc|0.11.1

</details>

**Comment by weinand** [comment]
This is not an issue with VS Code but with your program or the extensions you are using.
