### ISSUE TITLE
Drag and drop to import files in JS!

### ISSUE THREAD

**Issue by techsin** [Microsoft/vscode#61667]
I should be able to drag the file from sidebar maybe hold a key while dragging it and drop it into my current file and it'd automatically insert `import` or `require` statement in Javascript.

Bonus it adds the import statement where I'm hovering the mouse.

**Comment by techsin** [comment]
I checked they are talking opening a file by drag and drop not importing it.

**Comment by byronmejia** [comment]
Does intellisense not solve this issue? Doesn't seem overly difficult to implement, but I would like to know how it would add developer experience, outside of what vscode already provides?

Would this be more suitable as an extension, possibly?

**Comment by techsin** [comment]
@byronmejia when i've to type `require("./../../../../../components/chat/utilities/websocket/receiver/index");` I often make a mistake, and no intellisense can't tell which file i'm looking for unless i type very specifically, as typing index.js doesn't really tell it which index.

as for votes it can't get votes if it's closed in few hours.

**Comment by mjbvz** [comment]
Already tracked by #5240

**Comment by techsin** [comment]
Thank you. This is awesome. You always give a good thoughtful and authoritative reply.
