### ISSUE TITLE
Search is including files outside of the project 

### ISSUE THREAD

**Issue by jpierson** [Microsoft/vscode#6166]
- VSCode Version: 1.0.0
- OS Version: Windows 10

Steps to Reproduce:

1. Ctrl+Shit+f
2. Search for the word "skip", at least that's what I used.

Expected results: The results would only show from the project content
Actual results: Results are being returned for file matches in the Visual Studio Code folder under Program Files.

![image](https://cloud.githubusercontent.com/assets/1467146/15077103/e3f3a274-137a-11e6-9f56-c5640a4c313a.png)

My settings.json file looks like this.

```json
// Place your settings in this file to overwrite default and user settings.
{
    "search.exclude": {
        "**/.git": true,
        "**/node_modules": true,
        "**/tmp": true,
        "**/bin": true,
        "**/doc": true
    },
    "files.exclude": {
        "**/.git": true,         // this is a default value
        "**/.DS_Store": true,    // this is a default value
        // alternative version
        "node_modules": true,   // this excludes the folder 
                                // only from the root of
                                // your workspace 
        "typings": true,
        "bin": true,
        "tmp": true,
        "doc": true
    }
}
```

**Comment by bpasero** [comment]
Somehow you managed to open this file and as such it will show up in the search results. Just open it and press Ctrl+K W to close it for good.

**Comment by atilkan** [comment]
@bpasero That is not a solution. Your answer doesn't even solve anything. Try to understand the problem.
