### ISSUE TITLE
Cursor is lost when toggling Centered Layout

### ISSUE THREAD

**Issue by itsmysterybox** [Microsoft/vscode#61673]
- VSCode Version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
- OS Version: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Open a file
2. Go to View > Toggle Centered Layout

<b>Problem</b>
Whenever I enter or exit the Centered Layout, the cursor disappears and I'm unable to write. I have to click the screen to get the focus.

<b>Expected behavior</b>
The cursor should remain in place and be usable without clicking the screen.

Does this issue occur when all extensions are disabled?: Yes

Does this issue occur with latest VSCode insiders?: Yes

**Comment by isidorn** [comment]
To verify make sure that toggling centered view on / off the focus is set to the editor

**Comment by itsmysterybox** [comment]
Working in latest VSCode Insiders. Thanks!

**Comment by isidorn** [comment]
Thank you for trying it out, adding verified label
