### ISSUE TITLE
Textbox for commit message not visible

### ISSUE THREAD

**Issue by lafe** [Microsoft/vscode#61676]
- VS Code Version:
  - Version: 1.29.0-insider (system setup)
  - Commit: 43823dae97f07760958ffbb5e16c7f219307159c
  - Date: 2018-10-24T05:21:57.644Z
  -Architecture: x64
- OS Version: Windows 7 and Windows 2008 R2

1. Open VS Code
2. Navigate to Source Control Pane
3. The text box for the commit messages is not visible:
  ![image](https://user-images.githubusercontent.com/4070008/47412015-c36ce900-d76a-11e8-8f1d-1350ed482040.png)

Does this issue occur when all extensions are disabled?: Yes (tested with the `--disable-extensions` command line flag; only tested on the Windows 2008 R2 installation)

The issue occurs on two different computers: on my dev environment on a Windows Server 2008 R2 and on my Notebook with Windows 7 as well.

A seemingly related issue was occuring for the past few days, as the text box was sometimes only partly visible. However, I was not able to recreate the issue without the extensions being deactivated as it occured infrequently, so I have not created an issue.

**Comment by andremacola** [comment]
Yes. I can confirm this. OSX Mojave

**Comment by jrieken** [comment]
@joaomoreno I have reverted https://github.com/Microsoft/vscode/commit/217e29ad9c825f8f901e219cf71d22e0dc6f0afe

**Comment by lafe** [comment]
After I applied the new update, the textbox is back again. Thank you for the quick solution!
I am just unsure, if I should close the issue now or if you need it open for some kind of follow-up tasks...

**Comment by joaomoreno** [comment]
Fixed by https://github.com/Microsoft/vscode/commit/e3375691ee2d64e44922ae515d0d799489ce9dc2
