### ISSUE TITLE
Misleading dialog text: "Build errors have been detected during preLaunchTask..."

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#61678]
I see this dialog when trying to run my VS Code extension:

<img width="657" alt="screen shot 2018-10-24 at 8 26 16 am" src="https://user-images.githubusercontent.com/1078012/47413577-8999e380-d766-11e8-9e65-717bce9a4124.png">

However there were actually no errors generated during the running of `npm`. If I click `Show Problems`, I see this:

<img width="435" alt="screen shot 2018-10-24 at 8 26 23 am" src="https://user-images.githubusercontent.com/1078012/47413579-8999e380-d766-11e8-88fd-d2ff575a3ac8.png">

These errors are all Dart errors. They all existed before (and are unrelated to) `npm: watch`.

It would be great if it only looked at the npm errors, though if that's not possible, I think the dialog should be reworded to just say there are build errors to avoid suggesting that there are npm errors (slightly related is #51341, which was a request to make handling of this more general for other extensions).

**Comment by isidorn** [comment]
@DanTup thanks for the feedback after a lengthy discussion with @weinand and a couple of tries of adding heuristics we decided to change the text.
I have created this issue to track the actual problem https://github.com/Microsoft/vscode/issues/61693
