### ISSUE TITLE
Re-toggle panel upon debug/code run exit

### ISSUE THREAD

**Issue by piotr-rarus** [Microsoft/vscode#61675]
Dear developers, contributors, users

I like to work on vertical screen with hidden output panel.
Once I run/debug code it pops up automatically.
When the run/debug process is finished, it stays shown, and I have to hide it (CTRL + J) each time.
It would be nice to have some configurable option, that would check my appearance preferences, and re-apply them, upon such process' completion.

Kind regards,
Piotr Rarus

**Comment by isidorn** [comment]
Please use this `debug.internalConsoleOptions`
More than that is currently out of scope and not on our plan
