### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by JayeshMidasBlue** [Microsoft/vscode#61672]
Issue Type: <b>Bug</b>

It is not able to save the file and showing "(EIO: i/o error, ftruncate) " and asking to retry 
![vs_error](https://user-images.githubusercontent.com/33346250/47426256-5711da00-d7aa-11e8-9643-eec81641cdd1.jpg)

also it is getting crash and showing popup with "The window has crashed  ,we are sorry for inconvenience !You can reopen the window to continue where you left off." and it is happening again and again

![vs_crashed](https://user-images.githubusercontent.com/33346250/47410803-93cada80-d784-11e8-9dd9-bc649978b66c.jpg)

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|7.80GB (4.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
es7-react-js-snippets|dsz|1.8.7
auto-close-tag|for|0.5.6
AngularMaterial|har|6.1.0
openchrome|hua|0.0.3
Angular-BeastCode|Mik|7.0.5
debugger-for-chrome|msj|4.10.2
html5-boilerplate|sid|1.0.3

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
@JayeshMidasBlue is that some special filesystem you are on?

**Comment by JayeshMidasBlue** [comment]
No. It is windows 7 OS.By the way I got the problem that was because of  my drive which was locked somehow and that is why VSCode was giving me that I/O error accessing files on that drive.But again I have doubt about the second issue of getting it crashed and reopening the error popup,its somehow confusing what to do in that situations .
