### ISSUE TITLE
Git commit message textarea missing

### ISSUE THREAD

**Issue by bm-stschneider** [Microsoft/vscode#61679]
Issue Type: <b>Bug</b>

It seems that currently the textare above the changes/staged changes is missing where multiline commit messages where available.
And yes I verified this without extensions.
![image](https://user-images.githubusercontent.com/30625381/47414399-282b4200-d771-11e8-8491-a5f2de0214ae.png)

VS Code version: Code - Insiders 1.29.0-insider (43823dae97f07760958ffbb5e16c7f219307159c, 2018-10-24T05:11:32.976Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
twigcs|cer|0.4.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.60
vscode-svgviewer|css|1.4.7
vscode-eslint|dba|1.6.1
gitlens|eam|8.5.6
toggle-excluded-files|eam|1.6.0
tslint|eg2|1.0.40
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.4.2
prettier-vscode|esb|1.6.1
php-debug|fel|1.12.6
php-intellisense|fel|2.3.5
vscode-pull-request-github|Git|0.2.1
beautify|Hoo|1.4.6
phpcs|ika|1.0.5
smarty|imp|0.3.0
docthis|joe|0.7.1
puppet-vscode|jpo|0.12.0
php-cs-fixer|jun|0.1.85
vscode-gutter-preview|kis|0.16.2
php-symbols|lin|2.1.0
twig-language-2|mbl|0.3.1
php-namespace-resolver|Meh|1.1.0
vscode-scss|mrm|0.6.2
debugger-for-chrome|msj|4.10.2
vscode-ts-uml|myx|0.0.1
color-highlight|nau|2.3.0
vetur|oct|0.13.0
vscode-jest|Ort|2.9.2
vscode-docker|Pet|0.3.1
vscode-versionlens|pfl|0.22.0
errorlens|Phi|1.0.0
material-icon-theme|PKi|3.6.0
ruby|reb|0.20.0
vscode-yaml|red|0.0.17
code-settings-sync|Sha|3.2.0
stylelint|shi|0.44.0
autoimport|ste|1.5.3
easy-snippet-maker|tar|0.0.6
Snippet|vsc|0.3.0
vim|vsc|0.16.11
quokka-vscode|Wal|1.0.156
vscode-import-cost|wix|2.9.0
sort-js-object-keys|zen|1.0.1

(1 theme extensions excluded)

</details>

**Comment by lafe** [comment]
Seems to be the same as #61676
