### ISSUE TITLE
Markdown code blocks in JSDoc result in being prefixed with ` * ` in hover popups when inspected

### ISSUE THREAD

**Issue by KrofDrakula** [Microsoft/vscode#61680]
Possibly related issue: #43783

This issue relates to the indentation and content of code blocks in JSDoc comments using Markdown formatting for code blocks in the body of a description for any type, interface or function.

Version: 1.28.2 (user setup)
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:23:51.859Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Steps to Reproduce:

1. Write the following annotation in a TypeScript file:

```ts
/**
 * This function just works.
 * 
 * Example:
 * 
 * ```js
 * myFn('hello');
 * ```
 */
type Fn = (arg: any) => void;
```

2. Hover over the `Fn` type name to get the JSDoc hover popup:

![image](https://user-images.githubusercontent.com/112161/47414408-ccf55180-d768-11e8-8564-4d31c503829e.png)

3. Notice that the code block is prefixed with `  * ` for every line of code.

Per JSDoc, all the lines should have the indentation and `* ` stripped from content before passing it to the Markdown processor. This would align the tool with all other documentation tools and would avoid showing the `*` characters preceding every JSDoc code block line.

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by mjbvz** [comment]
Thanks. Already tracked upstream by https://github.com/Microsoft/TypeScript/issues/23517
