### ISSUE TITLE
Vscode keeps crashing

### ISSUE THREAD

**Issue by ClaudioPerroni** [Microsoft/vscode#61685]
- VSCode Version: 1.28.2
- OS Version:  Windows 10 pro v.1709

Steps to Reproduce:

1. Open multiple files (at least 5) by dragging them in the window

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@ClaudioPerroni is the window already crashing when you reorder tabs within or only when you drop into Code? Are you logged in as different user compared to who runs Code?

**Comment by ClaudioPerroni** [comment]
> 
> 
> @ClaudioPerroni is the window already crashing when you reorder tabs within or only when you drop into Code? Are you logged in as different user compared to who runs Code?

They get loaded up (i can see them in the tabs), however when i try to edit them vscode suddenly crashes.  I'm the only user logged in.

**Comment by bpasero** [comment]
@ClaudioPerroni are there other ways to reproduce? E.g. can you open multiple files from "File > open" and try then?

**Comment by ClaudioPerroni** [comment]
> 
> 
> @ClaudioPerroni are there other ways to reproduce? E.g. can you open multiple files from "File > open" and try then?

With file>open works fine, it's just dragging that gives me problems

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
