### ISSUE TITLE
debug fail with golang

### ISSUE THREAD

**Issue by michael1589** [Microsoft/vscode#61686]
![image](https://user-images.githubusercontent.com/9250127/47418489-c8eb2300-d7ac-11e8-80a5-c7dc0978f9a5.png)
![image](https://user-images.githubusercontent.com/9250127/47418538-e0c2a700-d7ac-11e8-885e-dc3f8c34716c.png)
![image](https://user-images.githubusercontent.com/9250127/47418584-fdf77580-d7ac-11e8-871a-f3bfb7b6f7ff.png)
![image](https://user-images.githubusercontent.com/9250127/47418646-21222500-d7ad-11e8-9bef-10d719803d77.png)
My windows is Win10.
Can't debug the unit test, I'm sure I can do it some days before.  It's ok when I click "run test" in vscode, but failed when click debug test. Is it a vscode bug?

**Comment by michael1589** [comment]
Can't debug the unit test, I'm sure I can do it some days before. Is it a vscode bug?

**Comment by weinand** [comment]
file this against the go extension.
