### ISSUE TITLE
Need a shortcut key binging of outline to toggle expanding or folding

### ISSUE THREAD

**Issue by kelein** [microsoft/vscode#61689]
It's necessary for me using a shortcut to toggle the outline view.  I think it well be better if it has a key binging to expand the outline when you want to look the code symbol,  and also can folding it when needed.

By the way, why the outline view can not be maximize in the side bar when in expanding state ?

**Comment by jrieken** [comment]
>  for me using a shortcut to toggle the outline view.

Toggle what? Its visibility or its expansion state?

**Comment by Keleir** [comment]
I think toggle expansion state is the first priority. You know use a shortcut is much convenient than moving your mouse to expand it.

**Comment by jrieken** [comment]
@sandy081 Is there maybe something for this already? I know there `<someTreeView>.focus` is there the same of collapse/expand?

**Comment by sandy081** [comment]
There is no collapse/expand of view actions.
