### ISSUE TITLE
Debug is not precise when checking errors after running preLaunchTask

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#61693]
Refs: https://github.com/Microsoft/vscode/issues/61678

1. Use the VSCode sample ts-extension
2. Make an unrelated error in some .json file, for example `package.json`
3. Start debugging -> notice how debugging complains that an error was found in the `preLaunchTask`, even though the error is completely unrelated

For this to work properly we would need some correlation between errors and markers, since what I do from the `debugService` is ask for markers after a `preLaunchTask` run and if there are some markers I show the prompt. And this can be very imprecise as shown in the example above.

@alexr00 @dbaeumer @sandy081 is there any way the marker service would have more information and that it would at least know that some task is responsible for generating those marks. Every marker has an 'owner' could this be used?

fyi @weinand @dantup

**Comment by dbaeumer** [comment]
This needs https://github.com/Microsoft/vscode/issues/31968 because everything else will be guessing and might be equally wrong.

**Comment by isidorn** [comment]
I see you already moved that to october, but the october one year ago 😁

**Comment by dbaeumer** [comment]
Agree. Never got enough traction. PR welcome :-)

**Comment by DanTup** [comment]
(If this is going to get some attention, it'd be really nice if it wasn't specific to preLaunchTasks... It's strange that with/without a preLaunchTask behaves differently given that some project types don't have them but still generate diagnostics in the background https://github.com/Microsoft/vscode/issues/51341)
