### ISSUE TITLE
Git plugin comment input miss

### ISSUE THREAD

**Issue by StArRy5211** [Microsoft/vscode#61695]
Issue Type: <b>Bug</b>

Open the VS Code insiders  
Switch to git tab

VS Code version: Code - Insiders 1.29.0-insider (43823dae97f07760958ffbb5e16c7f219307159c, 2018-10-24T05:11:32.976Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|38, 17, 10|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|-psn_0_9263317|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
project-manager|ale|9.0.1
eggjs|ati|0.3.1
vscode-database|baj|1.5.2
npm-intellisense|chr|1.3.0
gitignore|cod|0.5.0
vscode-eslint|dba|1.6.1
vscode-dash|dee|2.0.0
wpy-beautify|doi|2.0.10
githistory|don|0.4.3
gitlens|eam|8.5.6
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.40
vscode-npm-script|eg2|0.3.5
git-project-manager|fel|1.7.1
tars|fid|0.0.1
beautify|Hoo|1.4.7
solidity|Jua|0.0.46
vscode-cosmosdb|ms-|0.8.0
azure-account|ms-|0.4.3
cpptools|ms-|0.19.0
Go|ms-|0.6.93
vetur|oct|0.13.0
vscode-docker|Pet|0.3.1
jenkinsfile-support|sec|0.1.0
code-settings-sync|Sha|3.2.0
code-spell-checker|str|1.6.10
ayu|tea|0.16.0
wepy-snippets|wle|1.5.14
JavaScriptSnippets|xab|1.7.1

(3 theme extensions excluded)

</details>

**Comment by gangachris** [comment]
Is this related to https://github.com/Microsoft/vscode/issues/61676?

**Comment by StArRy5211** [comment]
Resolved with new version.
