### ISSUE TITLE
[Accessibility]A11y_PowershellEditorServices_Installation_Screenreader:Narrator reads the Tab item control type as Button for the "Details,Contributions,Changelog,Dependencies".

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#61696]
Environment Details:
****VSCode Version : 1.25.1
OS Version : Win10
MAS1.3.1
**Repro Steps:**
1.Launch Visual Studio code desktop application.
2.Navigate to "Extension" button of "ActivityBar"->Enter "PowerShell" in "Search Extension" text field and click on "Install" button.
3.Navigate through keyboard such as "Tab" key.
4.Observed that what narrator reads for the Tab item.

**Actual:**
Narrator reads the tab item as button for "Details,Contributions,Changelog,Dependencies".
Same issue is observed in NVDA also.
**Expected:**
Narrator should read the control type as Tab item for "Details,Contributions,Changelog,Dependencies".

**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
[https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx](url)

**User Impact:**
User will not able to know the correct control type.

**MAS Reference:**
MAS1.3.1
[https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}](url)

Does this issue occur when all extensions are disabled?: Yes
**Attachment for Reference:**
[2726864_A11y_PowershellEditorServices_Installation_Screenreader.pptx](https://github.com/Microsoft/vscode/files/2510053/2726864_A11y_PowershellEditorServices_Installation_Screenreader.pptx)

**Comment by isidorn** [comment]
Narrator is not supported
