### ISSUE TITLE
Cannot figure out how to close error window when jumping between errors

### ISSUE THREAD

**Issue by dakom** [Microsoft/vscode#61692]
This looks like a duplicate of https://github.com/Microsoft/vscode/issues/28380 however setting `editor.parameterHints.enabled` to `false` has no effect

- VSCode Version: 1.28.2
- OS Version: OSX 10.13.5

Steps to Reproduce:

1. Create an error
2. Jump to it with f8
3. Error window pops up
4. Can't figure out how to close it (other than leaving and coming back)

See here:

<img width="487" alt="screen shot 2018-10-24 at 12 40 53" src="https://user-images.githubusercontent.com/6406986/47421869-2621ad00-d78a-11e8-96fa-4182a77d3efd.png">

Does this issue occur when all extensions are disabled?: Yes/No

Yes

**Comment by skylize** [comment]
You can use <kbd>Shift</kbd>-<kbd>Esc</kbd> to hide tooltips on the fly from your keyboard.

**Comment by dakom** [comment]
Yup - that did it! Thanks :D

**Comment by dakom** [comment]
Followup question - is there a way to have the tooltips _not_ show up when navigating between errors?
