### ISSUE TITLE
Executing a built in command does not wait for it to be executed

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#617]
The use case is to call the `workbench.action.closeAllEditors` function and then assert that the number of visible editors is 0. Currently when doing the check after calling the function, `window.visibleTextEditors` is still 1.

I think this is a timing issue where executing a built in command does not wait for any changes to be propagated to the PH side.

Test case showing the issue (commented out atm): https://github.com/Microsoft/vscode/blob/master/extensions/vscode-api-tests/src/commands.test.ts#L19

**Comment by jrieken** [comment]
The problem in your case is that editors sync on their own cadence. See [doUpdateMappings](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/common/mainThreadEditors.ts#L336) which is called after a timeout. 

You should write you test using the `onDidActiveTextEditorChange` event, that's the only sync mechanism we publicly have.

The command execution should wait: see `invokeHandler`

**Comment by bpasero** [comment]
It actually does not wait but it seems to be a problem on the main side too. I created a PR and added Alex on it.

**Comment by jrieken** [comment]
We actually fixed that now

**Comment by bpasero** [comment]
@jrieken there is a test `commands.test.ts` which asserts this behavior and still fails. The test is checked in but disabled. 

```typescript
test('calling command completes with the extension host updated properly', () => {
	return workspace.openTextDocument(join(workspace.rootPath, './far.js')).then(doc => {
		return window.showTextDocument(doc).then(editor => {
			assert.equal(window.visibleTextEditors.length, 1);
			return commands.executeCommand('workbench.action.closeAllEditors').then(() => {
				assert.equal(window.visibleTextEditors.length, 0);
			});
		});
	});
});
```

When the command has executed, the visibleTextEditors is still 0. When I open `CloseAllEditorsAction` in `triggerEditorActions.ts` I can make the following change to assert that indeed the promise is waiting until the editors are 0:

```typescript
public run(): Promise {
	return this.editorService.closeEditors().then(() => {
		console.log(this.editorService.getVisibleEditors().length);
		
		return true;
	});
}
```

**Comment by jrieken** [comment]
Again, that's unrelated to commands. The editor manager doesn't execute sync with the command happening but batches editor/doc changes for performance reasons

**Comment by jrieken** [comment]
see how this is invoked: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/common/mainThreadEditors.ts#L337

**Comment by bpasero** [comment]
If we sell commands as a way to do more things from extensions, I think we need a way for the extension writer to synchronize on the result of invoking an action. How would an extension otherwise make sure that after invoking a command the state on the PH is in sync? E.g. I want to close all editors and then open another editor, wouldn't that collide?

**Comment by jrieken** [comment]
And you have found the only place in which we do that. 

Everyone is invited to fix the problem we that we have with editors, the active editor, visible editors etc. For instance, the complexity comes from the workbench API not being aware of embedded editors, from `EDITOR_INPUT_CHANGED` being fired on focus lost/gain etc, from us treating the combination of one editor and one model as editor in the API etc, etc.

**Comment by bpasero** [comment]
I am not sure how that is related to synchronizing UI state over to the PH side. I think you solved these problems because eventually the visible-editors number goes down to 0 when I invoke the "Close all Editors" action. Doing **anything** on the main side can eventually result in state being synchronized to the plugin host side from **any** action an extension invokes.

**Comment by spoeken** [comment]
Have you come any further with this?
