### ISSUE TITLE
[Accessiblity]A11y_PowershellEditorServices_Installation_Keyboard:Keyboard focus does not go to the content under the Tab item when after enter on any tab item.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#61707]
**Environment Details:**
VSCode Version : 1.25.1
OS Version : Win10
MAS2.4.3
**Repro Steps:**
1.Launch Visual Studio code desktop application.
2.Navigate to "Extension" button of "ActivityBar"->Enter "PowerShell" in "Search Extension" text field and click on "Install" button.
3.Navigate through keyboard such as "Tab" key or arrow keys to the Tab items "Details,Contributions,Changelof,Dependencies".
4.Observed that whether keyboard focus goes to the contents after select the tab item.

**Actual:**
Keyboard focus goes ilogical after any tab selected.After selecting any tab ex:Details,the keyboard focus does not go to the content written under the tab.

**Expected:**
Keyboard focus should go to contents written under the selected  tab after selecting any partiular tab.
**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx

**User Impact:**
User unable to get the content logically.

**MAS Reference:**
MAS2.4.3
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={0de7fbe1-ad7e-48e5-bcbb-8d986691e2b9}

Does this issue occur when all extensions are disabled?: Yes
**Attachment for Reference**
[2726905_A11y_PowershellEditorServices_Installation_Keyboard.pptx](https://github.com/Microsoft/vscode/files/2510345/2726905_A11y_PowershellEditorServices_Installation_Keyboard.pptx)

**Comment by isidorn** [comment]
Shuold be fxied in latest, try with latest vscode
