### ISSUE TITLE
Clickable multiline urls in terminal has been regressed?

### ISSUE THREAD

**Issue by raldred** [microsoft/vscode#61708]
Issue Type: <b>Bug</b>

Urls are converted to clickable links in the terminal, I'm sure it was working fine until 1.28.2.
I know there's an issue when a window is resized but this is a fresh window that has not been resized.

https://www.dropbox.com/s/uk4b38a8xwr3iq5/Screenshot%202018-10-24%2012.50.59.png?dl=0

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.70GB free)|
|Process Argv|-psn_0_6911639|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|9.0.1
vscode-color|ans|0.4.5
htmltagwrap|bra|0.0.7
better-toml|bun|0.3.2
solargraph|cas|0.17.6
vscode-quick-select|dba|0.2.7
gitlens|eam|8.5.6
rspec-snippets|kar|0.0.3
dotenv|mik|1.0.1
vscode-scss|mrm|0.7.0
python|ms-|2018.9.1
azure-account|ms-|0.4.3
Go|ms-|0.6.93
vsliveshare|ms-|0.3.869
debugger-for-chrome|msj|4.10.2
rails-run-spec-vscode|nok|0.1.2
vscode-docker|Pet|0.3.1
heroku-command|pko|0.0.8
vscode-css-peek|pra|2.1.0
ruby|reb|0.20.0
sass-indented|rob|1.4.9
Align|ste|0.2.0
vscode-import-cost|wix|2.9.0

</details>

**Comment by Tyriar** [comment]
It looks like you have increased the horizontal size of the window? If that is the case this is expected. Can you provide some complete repro sets that I could try?

**Comment by jerch** [comment]
@Tyriar, @raldred  Horizontally enlarging will break the current linkifier match as it inserts spaces. This is unlikely to be fixable until we got reflow support in the terminal.

**Comment by raldred** [comment]
@jerch @Tyriar 
I have made a screen cap, it's definitely not working with a fresh window, I am not resizing anything.
https://www.dropbox.com/s/5iw6ry8h4f00qon/terminal-clickable-links.mov?dl=0

**Comment by jerch** [comment]
@raldred Thx, I can repro it with lines in the viewport when the terminal was bigger before.

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/xtermjs/xterm.js/issues/2115

**Comment by Tyriar** [comment]
Seems fixed
