### ISSUE TITLE
All breakpoints are unverified

### ISSUE THREAD

**Issue by ghirlekar** [Microsoft/vscode#61711]
- VSCode Version: 1.28
- Node Version: 10.12
- OS Version: Windows 10 1803
- Using Typescript: No
- Using Webpack: No

Launch configuration
```JSON
{
  "type": "node",
  "request": "launch",
  "name": "Launch Program",
  "useWSL": true,
  "program": "${workspaceFolder}\\index.js"
}
```

Steps to Reproduce:

1. Add breakpoint which appears as a red filled circle
2. Launch with above configuration
3. Breakpoint turns to gray outline with hover of 'Unverified breakpoint'
4. Insert `debugger;` statement in code
5. File opens with subtitle 'read-only core module' in the titlebar
6. Add breakpoint to this read-only file. This breakpoint works as expected
7. Remove `debugger;` statement in editable source file
8. Add functioning breakpoints in the read-only file as required. They all work perfectly.

Line of Examination:

1. Disabling sourceMaps in the launch configuration didn't work
2. `"localRoot": "${workspaceFolder}"` and `"remoteRoot": "C:\\Users\\user\\folder"` did nothing. Code still opens in separate read-only file
3. Opening entire folder in Ubuntu and running launch as-is works perfectly. No issue with breakpoints at all.

I have been struggling with this issue since at least July 2018 without finding a working solution. I would be very grateful for help, since I have to go back to inserting console.log statements all over my code.

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
@ghirlekar what do you mean by "Opening entire folder in Ubuntu"? 
What do you open if breakpoints don't work?

**Comment by roblourens** [comment]
> File opens with subtitle 'read-only core module' in the titlebar

If you hover the title of the readonly file, you should be able to see the full path. How is that path different from the real path of the file? That should give us a hint...

**Comment by roblourens** [comment]
> File opens with subtitle 'read-only core module' in the titlebar

If you hover the title of the readonly file, you should be able to see the full path. How is that path different from the real path of the file? That should give us a hint...

**Comment by ghirlekar** [comment]
It doesn't show a full path; only the filename (index.js in this case).
I also tried on the latest Insiders edition 1.29; it has the same issue.

**Comment by roblourens** [comment]
Can you set `"trace": true`, run it again, and upload the log file here? That should have the info we need.

**Comment by ghirlekar** [comment]
[debugadapter.txt](https://github.com/Microsoft/vscode/files/2513653/debugadapter.txt)

Due to a conference, I will not have access to this desktop until Sunday morning. Until then, I can reply to comments but not run any launches. Sorry for the inconvenience.

**Comment by jeremychone** [comment]
NodeJS: 10.12
VSCode: 1.28.2


I think I have the exact same issue, which started to appear with 10.12 (node 10.11 and before works as expected). Node 11 has the same issue. 

Thinks works if I run and debug on Mac, but since node.js 10.12, if I debug from mac to a local docker image (alpine/node 10.12) It seems that node.js 10.12, on linux at least, emit the wrapped js file on debug, which seems to cause confusion for VSCode. 

- Best case scenario, vscode can recover and find the breakpoint and allows you to step through the emitted file (read-only file). Usually that happen when you put breakpoint on the .js file. Inconvenient, but still workable. 

- Worst case,  is that if we use some map file (i.e. TypeScript source files), then, nothing get found and cannot set breakpoints on source files. 

I rolled back to 10.11 and all work as expected. I think nodejs changed something but I looked at their issues and nobody seems to be mentioning anything about this. 

I was hoping that node 11 was going to roll back whatever they did in 10.12, but it does not seems to be the case. 

Here is the file I have to debug when running node.js 10.12
![image](https://user-images.githubusercontent.com/74671/47526226-f9d26300-d853-11e8-9b96-a749583c06bd.png)

With node.js 10.11, I just debug the start.js

I have a little code sample which reproduces this problem by just chaning the docker image from node 10.11 to node 10.12. I can put it online if there are some interest. 


This is a big deal for us, I am not sure it is a VSCode issue, but feel free to let us know if there is anything we can do to help VSCode or Node team to get to the bottom of it.

**Comment by roblourens** [comment]
@ghirlekar Does it work if you have your repo under a path that doesn't have a space in the path? Possibly this is from Node's change to use file:/// URIs instead of paths, and we might not decodeURI at the right time.

@jeremychone Do you have a space or any special characters in your project's path? If not, please upload a log too.

**Comment by ghirlekar** [comment]
@roblourens I will be able to check in about 36 hours and get back to you then.

**Comment by jeremychone** [comment]
@roblourens So, no special character or space (beside '-'). Also, in my little experiment, I do not have any symlink as well. 

 So, in my case, when no map file, I can debug but in this read only mode where the first line (function.... ) is "added" (probably from JS runtime). Not sure who removes it in normal debug (vscode or nodejs debug interface). 

Ok, I will read how to make the log upload it.

**Comment by ghirlekar** [comment]
@roblourens, removing spaces from the file path solves the original issue, but raises a slightly different one.

If I open the source index.js, attach breakpoints and launch, the breakpoints work correctly.
However, the breakpoints trigger into a new index.js which is a read-only core module that seemingly wraps my original index.js in an IIFE.

![image](https://user-images.githubusercontent.com/4235940/47611751-bc5b1900-da91-11e8-98a0-2599af5aba53.png)

So for every breakpoint, I have to inspect, close the read-only module, attach breakpoints in the source index.js, etc. all while constantly closing the read-only index.js that keeps opening.

If I remember, debugging used to trip breakpoints in the source file itself, right? I don't recall having to keep closing read-only modules in the past.

**Comment by roblourens** [comment]
Can you provide a new log after you work around the space issue? I will fix the space issue for october.

**Comment by ghirlekar** [comment]
Here you go.
[debugadapter.txt](https://github.com/Microsoft/vscode/files/2524528/debugadapter.txt)

**Comment by roblourens** [comment]
Ok there seems to be a separate issue with WSL separate from the space issue, I'll have to try it out.

**Comment by jeremychone** [comment]
@roblourens So, I had exactly the same "read-only core module" problem as @ghirlekar (I never had special/space char in my paths). 

For me, it occurs when I run node.js 10.12 and above in a docker image (all works fine with node.js 10.11 on docker, or even node.js 10.12 when running server on local osx). 

I created a minimalistic repo which reproduces the issue: https://github.com/jeremychone/node-vscode-debug-issue (see readme to reproduce the issue)

I tried to put the trace:true, but did not see any output file generated. I might be missing something obvious. 

The real problem with the "read-only core module" is that it seems to be the beginning of more serious confusion when we use .map file (.e.g., typescript source file) where none of the breakpoints on .ts files are recognized anymore (if need be, I can create another simple repo to show this case)

**Comment by roblourens** [comment]
Thanks for the repro case, I can repro this issue, fix inbound.

**Comment by roblourens** [comment]
I opened https://github.com/Microsoft/vscode/issues/62354 because the "readonly module" issue is technically separate from the "space in path" issue

**Comment by roblourens** [comment]
I've pushed a couple fixes for these two issues, I'd appreciate if everyone can try using the next Insiders build! (released a couple hours after this post)

**Comment by ghirlekar** [comment]
@roblourens, I just tried with v1.29.1. 
Your fix worked perfectly when I launched from VSCode, but if I have my server running with nodemon and try to attach to that from VSCode, then it shows unverified breakpoint again.

I've attached the trace file.
[debugadapter.txt](https://github.com/Microsoft/vscode/files/2622917/debugadapter.txt)

**Comment by ghirlekar** [comment]
For an attach configuration, it tells me `Property useWSL is not allowed`. The docs you linked also use it only with a launch configuration.

**Comment by roblourens** [comment]
In that case I think you need to fill in remoteRoot/localRoot manually.

Example:

```
"localRoot": "${workspaceFolder}",
"remoteRoot": "/mnt/c/<path>"
```

**Comment by ghirlekar** [comment]
That didn't seem to do anything. Breakpoints are still a hollow gray and say 'unverified' on hover.

**Comment by roblourens** [comment]
You probably need to fix those paths. But please open a new issue. Also you can use `.scripts` to see how the paths are being resolved.

**Comment by ghirlekar** [comment]
I will open a new issue as you recommend.

BTW, I didn't understand exactly what you meant by needing to fix those paths. I used these in the attach configuration
```
"localRoot": "${workspaceFolder}",
"remoteRoot": "/mnt/c/Users/admin/Documents/GitRepositories/erp/graphql_server"
```

Also, I assume you mean [tasks](https://code.visualstudio.com/docs/editor/tasks). Regrettably, I have zero experience in using those.

**Comment by roblourens** [comment]
If `graphql_server` is the folder you have open in vscode, then that looks right. But I can help you troubleshoot some more if you open a new issue with a log.

I meant, enter `.scripts` in the debug console, and it will print the scripts in their original and resolved forms.

Alternatively, if it's possible to use a "launch" type config with "useWSL", it may "just work".
