### ISSUE TITLE
Syntax giving error when we dont export the object.

### ISSUE THREAD

**Issue by frkn-aydn** [Microsoft/vscode#61718]
- VSCode Version: 1.28.2
- OS Version: OSX 10.14

Steps to Reproduce:
I was using i18n-node module in my node.js project. But in this module, we cant use "module.exports" to export javascript object. I dont want to see any error in this files but its giving me error.

1.  create a .js file. 
2. write a object without module.exports or anything else.

Does this issue occur when all extensions are disabled?: yes

Error image : https://prnt.sc/l9w9zc

**Comment by mjbvz** [comment]
That's not a valid JS file. The `{}` is interpreted as a code block, not an object. Either use a json file or add an export or similar to make the code valid
