### ISSUE TITLE
[scss] support `speak`

### ISSUE THREAD

**Issue by qkdreyer** [Microsoft/vscode#61719]
- VSCode Version: 1.29.0-insider (8aef44b6426b37ccb22026f56f52f42d136f4a0a) 2018-10-24T09:53:55.963Z
- OS Version: macOS 10.14.1 (18B45d)

Steps to Reproduce:

1. Use `speak` attribute in scss file
2. Problems : `[scss.lint.unknownProperties] Unknown property: 'speak' [unknownProperties]`

![image](https://user-images.githubusercontent.com/717869/47432870-896a0a00-d79f-11e8-95ca-c5d52a786318.png)
![image](https://user-images.githubusercontent.com/717869/47432882-8e2ebe00-d79f-11e8-9d6a-8bbf39a34a2a.png)

Duplicate (closed) issue : #43022
Ressources :
- https://github.com/stylelint/stylelint/issues/3285#issuecomment-385459809
- https://github.com/mdn/data/issues/218
- https://github.com/Microsoft/vscode-css-languageservice/blob/master/src/data/browsers.ts
- https://github.com/mdn/data/blob/master/css/properties.json

Does this issue occur when all extensions are disabled? : Yes

**Comment by octref** [comment]
![image](https://user-images.githubusercontent.com/4033249/47448086-02536c80-d774-11e8-94b7-707905194d79.png)

If mdn/data takes it, we'll get it. If not, then no.
