### ISSUE TITLE
JAVA syntax highlighting breaks for type names ending with 'class'

### ISSUE THREAD

**Issue by Zenoo** [Microsoft/vscode#61727]
Issue Type: <b>Bug</b>

1. Have a Java class with a name ending with 'class'
2. Try to reference this class elsewhere like `ZoneSuperclass zone = null;`

![vsc_color_highlighting_error](https://user-images.githubusercontent.com/7151485/47436739-5af02d00-d7a7-11e8-9494-21d4e98b8cb6.gif)

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|23.89GB (12.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
vscode-eslint|dba|1.6.1
jquerysnippets|don|0.0.1
gitlens|eam|8.5.6
EditorConfig|Edi|0.12.5
apacheconf-snippets|eim|1.1.9
php-debug|fel|1.12.6
php-intellisense|fel|2.3.5
php-pack|fel|1.0.2
smarty|imp|0.3.0
Sbt|itr|0.1.7
Scala|itr|0.1.7
easy-less|mrc|1.4.5
vscode-apache|mrm|1.1.1
vscode-less|mrm|0.6.3
es6-css-minify|olb|2.1.0
java|red|0.33.0
LiveServer|rit|5.1.1
ftp-kr|rua|1.3.16
javascript-typescript|sou|0.0.7
vscode-java-debug|vsc|0.14.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.10.0
vscode-maven|vsc|0.11.1
vscode-playframework-syntax|lan|0.0.1
html-css-class-completion|Zig|1.17.1

</details>

**Comment by alexr00** [comment]
@Zenoo, I can't reproduce this. I tried with:
VS Code version: Code 1.28.2 (7f3ce96, 2018-10-17T00:23:51.859Z)
VS Code version: 1.29.0-insider (4a29bd373)
And built out of master from 3dd2b19b2ab73

This is my test code:
![image](https://user-images.githubusercontent.com/38270282/47487903-a5bf8280-d843-11e8-95fa-68080f0856ee.png)

Can you provide more details for me to reproduce with?

**Comment by alexr00** [comment]
@Zenoo, I see it now, thank you for catching. This also repros in Atom, which is where we're getting the language grammar from.

**Comment by alexr00** [comment]
This issue was moved to atom/language-java#167
