### ISSUE TITLE
Installation fails on Ubuntu Server

### ISSUE THREAD

**Issue by Stephanevg** [Microsoft/vscode#61721]
- VSCode Version:
Latest one from the download page

- OS Version:
Ubuntu Server
![image](https://user-images.githubusercontent.com/6302961/47432751-3abc7000-d79f-11e8-8e4e-e9cf135177e3.png)

Steps to Reproduce:

I actually followed the steps from here --> https://code.visualstudio.com/docs/setup/linux

1. Download DEB package from https://code.visualstudio.com/Download 
2 Executed: ``` sudo dpkg -i <file>.deb``` (This one throws already errors)
3  Then ```sudo apt-get install -f # Install dependencies```

(Triend the above in Bash and in PowerShell, and through the GUI (Double click on the .Deb file.)

This is the output I have :

![image](https://user-images.githubusercontent.com/6302961/47432941-aacaf600-d79f-11e8-8e16-08bc89786277.png)

Using the ```sudo apt-get install -f```to install the dependencies results in the following:

![image](https://user-images.githubusercontent.com/6302961/47432994-c504d400-d79f-11e8-8fd5-47ed0bab1b9f.png)

Of course, If I select Y, it removes the tool, which is not what we want of course.

Ps: I am really a linux noob and just followed the few steps from the documentation, so I might be doing something ```really``` stupid or missing something obvious or so. If so, please excuse me in advance.

Also, I was a bit surprised (Disapointed?) that it was directly available using ```sudo apt-get install code```

Cheers

**Comment by Tyriar** [comment]
I believe running the `sudo apt-get install -f` on the setup page should install code and the deps: https://code.visualstudio.com/docs/setup/linux#_debian-and-ubuntu-based-distributions

The issue is that dpkg only installs the single package and not the dependencies, you need to invoke apt-get to install the deps.

> Also, I was a bit surprised (Disapointed?) that it was directly available using sudo apt-get install code

We install the repo and key when you install the deb package, like several other programs. This is to try help keep you updated.

**Comment by Stephanevg** [comment]
Hi @Tyriar You probably didn't read the screen shot of my second prompt well enough.
This is exactly what I did, and that  didn't fixed my problem.
Could you please re-open the ticket? This problem is not resolved.

**Comment by Tyriar** [comment]
@Stephanevg yes I didn't 😅, if the repo is installed does installing it through there work? `sudo apt install code`

**Comment by Stephanevg** [comment]
I actually did that before as well:
(I followed the steps from here -> https://code.visualstudio.com/docs/setup/linux#_debian-and-ubuntu-based-distributions ) 

1.  I used the following code: ```bash
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
```

2. Then I used the following code: ```bash
sudo apt-get install apt-transport-https
sudo apt-get update
sudo apt-get install code
```

Here are is a screen shot of the results:

![image](https://user-images.githubusercontent.com/6302961/47459081-85f47400-d7db-11e8-8cf7-a04996d0781b.png)

**Comment by Stephanevg** [comment]
Also @Tyriar  The label 'install update' that is set on this ticket, is probably wrong, as I never isntalled vscode before on this linux machine before. This is just a fresh installation that refuses to get installed.

It would be great to have this one fixed, as it is blocking me to debug some urgent failing pester tests.

**Comment by Stephanevg** [comment]
Hi @Tyriar 
Can you tell me what more info you need to work on this one? I don,t really see how more detailed I could get. (Or perhaps the label is wrong?)

**Comment by Stephanevg** [comment]
@tyriar / @weinand it would be nice that this one doesn't fall into oblivion, as this one is really blocking me.

 i don't know what more information i can provide to help u guys with this one.

**Comment by Stephanevg** [comment]
@Tyriar / @weinand Is anyone looking at this?

**Comment by tylerl0706** [comment]
@Stephanevg can you share your PATH?

```
$env:PATH
```

on my mac, code is installed in `/usr/local/bin/code` I would think that this would be added to the PATH but I'm curious

**Comment by Stephanevg** [comment]
Thanks for looking into this @tylerl0706  👍 !

This is what I have in my PATH

![image](https://user-images.githubusercontent.com/6302961/47739249-46170c00-dc75-11e8-930d-d92bdb000e89.png)

I also tried to update apt list, but got the following message
![image](https://user-images.githubusercontent.com/6302961/47739357-7eb6e580-dc75-11e8-9cb3-50d5faa22c02.png)

It seems like I do have an issue with the filetype of that microsoft document.

**Comment by tylerl0706** [comment]
That's odd... but also, can you supply the result of:

```
$env:PATH
```

I don't see it in your screenshots

**Comment by Tyriar** [comment]
It looks like that error is related to the .gpg file having bad contents: https://github.com/Debian/apt/blob/a18f38976d3544477f7450aa4265397db9b62cc6/cmdline/apt-key.in#L335

I just removed the key and repo on my computer and went through all the steps again and it worked fine. Could your internet connection somehow be manipulating the bits or something coming from https://packages.microsoft.com/keys/microsoft.asc ? Maybe try download it through another means and installing it?

**Comment by tylerl0706** [comment]
Another option is to try to install using snap:

https://snapcraft.io/vscode

**Comment by Stephanevg** [comment]
Hi, thanks for you attempts guys. I got help on twitter, and I was actually missing data in apt list.
It was basically containing only 3 lines.
After adding a bunch of them, I was able to download that missing pakage that we see in my very first screen shot (libg.conf2-4). Once I had that one on my machine, I could finally install vscode. :)

Cheers
