### ISSUE TITLE
terminal.integrated.shellArgs doesn't seem to run script

### ISSUE THREAD

**Issue by sambhare** [Microsoft/vscode#61725]
Issue Type: <b>Bug</b>

Steps to reproduce on Linux
1. Disable all extensions and reload
2. Create a Python virtualenv
```cd ~ && python3 -m venv test_venv```
3. Open a folder and add the following to workspace settings (Linux)
```json
    "terminal.integrated.shellArgs.linux": [
        "--rcfile",
        "/home/username/test_venv/bin/activate"
    ],
```
4. Open a terminal window using `Ctrl+~`
5. Expect to see prompt with test_venv activated but don't. 
6. (On Windows, you can replace `"--rcfile etc."` with `"/k C:/Users/username/test_venv/Scripts/activate.bat"` and reproduce the same bug.) 

Same steps above work properly in the current release 1.28.2 but not in latest insiders. 

VS Code version: Code - Insiders 1.29.0-insider (8aef44b6426b37ccb22026f56f52f42d136f4a0a, 2018-10-24T10:02:35.591Z)
OS version: Linux x64 4.15.0-38-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2175)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 1|
|Memory (System)|7.71GB (1.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
Bookmarks|ale|9.1.0
project-manager|ale|9.0.1
better-toml|bun|0.3.2
gitignore|cod|0.5.0
vscode-markdownlint|Dav|0.20.0
vscode-eslint|dba|1.6.1
githistory|don|0.4.3
gitlens|eam|8.5.6
matlab|Gim|0.9.0
vscode-firefox-debug|hbe|1.7.1
nim|kos|0.6.1
python|ms-|2018.9.1
cpptools|ms-|0.19.1-insiders
debugger-for-chrome|msj|4.10.2
autodocstring|njp|0.2.3
vscode-icons|rob|7.27.0
rust|rus|0.4.10
vc6-keybindings|sam|0.2.0
org-mode|too|0.5.0
vscode-lua|tri|0.12.4
cmake|twx|0.0.17
vscode-lldb|vad|1.0.0
gitflow|vec|1.2.1
markdown-all-in-one|yzh|1.6.3
vscode-proto3|zxh|0.2.1

</details>

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/61394
