### ISSUE TITLE
Intellisense problems when project on network drive

### ISSUE THREAD

**Issue by getglad** [Microsoft/vscode#6172]
- VSCode Version: 1.0.0
- OS Version: Win 7

When using a file on a Windows network drive, a lot of the Intellisense features are not working. Where I am at least feeling the most pain points is in using import/export ES6 statements, such that I am not able to see the components of my imported class. Peek/Find All References/Go to Definition, etc will not work.

On a desktop, this is fine. I remember Atom had this problem early on as well. A few are still open: https://github.com/atom/atom/issues/1766

Steps to Reproduce:

1. Put files on network drive
2. Try to use ES6 import/export statements; Peek feature; 'Go to Definition' feature

**Comment by dbaeumer** [comment]
I will move this to the TS team which provide the tsserver.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#8524
