### ISSUE TITLE
'Alt+Click' doesn't activate multi-cursor

### ISSUE THREAD

**Issue by Michel73** [Microsoft/vscode#61729]
As described in the documentation (https://code.visualstudio.com/docs/editor/codebasics) the multi-cursor should be activated by the combination of ==> `Alt+Click` 
If I modify the setting `editor.multiCursorModifier` to `crtlCmd` it works with combination of ==> `Ctrl+Click`
In my memory, that worked in earlier versions. And on Windows it still works.

- VSCode Version: 1.28.2, 1.29.0-insider
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Open an editable file
2. Press anywhere in the file ==>  `Alt+Click`

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
I think your operating system is eating up alt+click (IIRC to move windows around). I think that is why we have introduced the setting in the first place... so you can choose whichever one works on your OS...

Are you able to use the gesture alt+click in any other software on the same machine?

**Comment by Michel73** [comment]
You are right. Using another `mouse-button-modifier`-key solved the Problem.
