### ISSUE TITLE
Code needs internet to launch

### ISSUE THREAD

**Issue by shanthosh2910** [Microsoft/vscode#61731]
![annotation](https://user-images.githubusercontent.com/22300553/47440479-e24f9780-d7cb-11e8-9d90-bb28463f811f.png)
 

- VSCode Version: 1.28.2
- OS Version: windows 1809 (Os build 17763.55)

Steps to Reproduce:

1. Launching code with no internet connection gives the `Error:EFILE`
2. With internet connection it is launching fine. After launch code is working even without internet connection.

Does this issue occur when all extensions are disabled?: Yes

**Comment by DarthSpock** [comment]
I don't experience this issue using Insiders 1.29 on a Win 7 VM. Might be a bug with 1809.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/61662
