### ISSUE TITLE
Allow opening multiple views side by side/at the same time

### ISSUE THREAD

**Issue by Meai1** [Microsoft/vscode#61736]
I see no reason why I should be forced to choose between Debug view and Explorer view and this doesnt stop there, I would like to keep the search view open too. Why should I be forced to click between search and explorer constantly? Many IDEs choose to have search results at the bottom pane for that very reason, this restriction in VSCode seems arbitrary.
I'm aware that Visual Studio by default hides the file explorer during debugging sessions, probably because in c++ and in most versions of c# you shouldnt or couldnt edit any code at runtime anyway and the whole process of debugging was so heavyweight.
However with many non-c++ project types and usecases like javascript or dart I can start a new debugging session in under a second. That means the process of clicking between the file explorer view and the debug view is now a serious annoyance. 
In my opinion project files are naturally closely related to the problem that I'm debugging, I need to inspect and open them all the time while I'm debugging an issue I have. I have a widescreen monitor, it is no problem for me to keep the debug view open at all times next to the explorer.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/50853
