### ISSUE TITLE
Ignore "./" prefix on file names in QuickOpen

### ISSUE THREAD

**Issue by DeegC** [microsoft/vscode#61735]
In my Rails app, when running RSpec tests, I get something like the following on an error:

```
Failed examples:

rspec ./spec/requests/account_spec.rb:961 # create an account
```

To open the error I copy/paste the filename into QuickOpen.  It works great if I don't copy the "./" prefix (QuickOpen correctly interprets the ":961" which is awesome!) but doesn't find the file if the prefix is included.  It would be nice if Code ignored the "./" or interpreted that as the project root.

**Comment by roblourens** [comment]
I don't want to just ignore it, but also we don't have a way to search from the project root with `./`-like semantics right now. Also we would have to think about how it should work for multiroot, whether we should use the same semantics as "files to include" in the search viewlet or not. In the search viewlet, `./` in multiroot expects the configured name of the folder, but `./` in a single folder scenario is a normal relative path inside that folder.

**Comment by DeegC** [comment]
Ok, understood.  I'll see if I can write my own extension.  Thanks for the update!
