### ISSUE TITLE
Allow Silent updates. Do not display any notifications.

### ISSUE THREAD

**Issue by AdamHess** [Microsoft/vscode#61730]
Many developers are bombarded by the number of updates required for each piece of software and operating system. (most annoying of all is Visual Studio 2017 constant yellow box)  

One installation of Visual Studio code can have 2-3 dozen extensions installed to work with multiple languages simultaneously and each time there is an update we get an annoying notification. 

My proposal: 

Allow application wide disabling of notifications for all extensions. Upgrade them silently, but keep a record or show when they were updated. Or offer a "recently updated extensions" page so that developers can figure out what might have broken if it was an update. 

Concomitantly, you can add more fine level detail to allow disabling notifications for a specific extension should the blanket disabling not be desired.

**Comment by sandy081** [comment]
@AdamHess There is an option to auto update extensions which is enabled by default. Is this enabled for you and so what kind of notifications you are seeing?
