### ISSUE TITLE
Improve Explorer Navigation

### ISSUE THREAD

**Issue by dvitry** [Microsoft/vscode#61737]
As has been said in other requests, I find navigating folders in the Explorer pane difficult when there are a large number of files.  My suggestion is a quick toggle that hides all files so you're left seeing only the folder tree.  Then you can get where you're going quickly and show files again.  To make this quick there needs to be a hotkey that toggles this when the mouse is over the Explorer pane, like Alt or Alt-Shift.  With the hotkey pressed, all files are hidden.  Release the hotkey and files are show again.

**Comment by ackvf** [comment]
Can we have the duplicated issue reference here?

**Comment by isidorn** [comment]
Search for issue tagged with file-explorer and feature-request author Tyriar and you will find it
