### ISSUE TITLE
CustomViews should not wait for all extensions to activate before displaying

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode#61732]
I initially brought this up [here](https://github.com/Microsoft/vscode/issues/59645#issuecomment-431881009), but creating a separate issue to track.

When you have multiple extensions installed, the custom views are not shown until _all_ extensions get activated, rather than staggering it so that each one shows up when it's ready individually.

Here is the behavior I see with 5 Azure extensions installed:
![timing2](https://user-images.githubusercontent.com/11282622/47303347-84a72980-d5d8-11e8-8a75-16264b9ee565.gif)

The views all showed up at the exact same time after about 20 seconds. However, each individual extension had an activation time that was much shorter (2-4 seconds):
![screen shot 2018-10-22 at 8 56 50 am](https://user-images.githubusercontent.com/11282622/47303493-e071b280-d5d8-11e8-9572-f51805453905.png)

**Comment by jrieken** [comment]
@chrmarti don't all those extensions depends on your auth extension/lib? could that be the culprit?

**Comment by EricJizbaMSFT** [comment]
@jrieken I did some further testing on this. I created a [very simple extension](https://github.com/EricJizbaMSFT/hellowworldtree) that just has a tree. First I added the delay to the 'activate' method and I couldn't reproduce this bug. However, then I moved the delay outside the activate method (see [this commit](https://github.com/EricJizbaMSFT/hellowworldtree/commit/5a8562ea2a968441e8eb223db3796c2d64a962ef)) and it was reproducing. This is further evidence that we need to try web pack, but still wondering if this is something you can fix.

Gif:
![timing3](https://user-images.githubusercontent.com/11282622/47449968-d5558880-d778-11e8-816c-3a5b5fc8cfb1.gif)

Final activation times:
![screen shot 2018-10-24 at 10 37 12 am](https://user-images.githubusercontent.com/11282622/47449979-dc7c9680-d778-11e8-9b83-5b035067e9e0.png)

**Comment by EricJizbaMSFT** [comment]
Sure but why does it go through all 4 busy loops before a single tree is displayed?

**Comment by eamodio** [comment]
I believe because of the fun of single threaded javascript and that all extension run in the same sandbox 😄

**Comment by EricJizbaMSFT** [comment]
Yeah I have no idea how the extension sandbox works or how you're loading extensions :) If there's nothing you can (reasonably) do than I'll go ahead and close the issue.

**Comment by chrmarti** [comment]
I had two cases where I saw a profile like this, but it no longer reproduces:

![image](https://user-images.githubusercontent.com/9205389/47918341-9b892e00-deac-11e8-98c8-bda02933f14f.png)

**Comment by chrmarti** [comment]
Continuing here: https://github.com/Microsoft/vscode-azure-account/issues/87.
