### ISSUE TITLE
Consider searching with JS regexes in unicode mode

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#61746]
JS regexes now support a `u` flag which changes their semantics regarding unicode characters in some ways and enables some new features.

Examples:

```
/𝌆{2}/u.test('𝌆𝌆') => true
/𝌆{2}/.test('𝌆𝌆') => false

/\p{Sm}/u.test('+') => true
/\p{Sm}/.test('+') => false
```

Example in vscode:
- Have `𝌆𝌆` in editor
- Search `𝌆{2}`
- No match
- Searching `𝌆𝌆` does match

Not sure how many users are affected by this but it's worth investigating.

Also, this support seems half-baked in Node 8 but works more in Node 10, so maybe we wait for an electron update.

More info: https://mathiasbynens.be/notes/es6-unicode-regex

**Comment by roblourens** [comment]
@rebornix now that we are using Node 10, I suggest we do this for the editor. Any reason not to?

**Comment by rebornix** [comment]
@roblourens I'm not aware of any reason why we don't want to do that. If I understand correctly, we only need to add `u` flag to the regex search, right?

**Comment by roblourens** [comment]
Yes. I suggest we move it to August to give plenty of time. This goes with https://github.com/microsoft/vscode/issues/62416 too.
