### ISSUE TITLE
Editor tabs sometimes getting duplicated after saving

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#61749]
Issue Type: <b>Bug</b>

I'm seeing some strange behavior that just started with today's insiders build. I haven't pinpointed exactly what is going on, but sometimes when saving a file the save seems to "fail" or at least the post-save formatting (I use the Prettier extension) failed to format the file. But I did notice when this happens there is another editor tab opened (I didn't open it) where the save and the formatting did succeed. And its like that first editor (the one I opened and was editing) is now dead -- the breadcrumbs won't update, edits don't trigger the dirty indicator (though they do on the other editor).

Its like there is some uri issue.

/cc @bpasero 

VS Code version: Code - Insiders 1.29.0-insider (8aef44b6426b37ccb22026f56f52f42d136f4a0a, 2018-10-24T10:07:06.221Z)
OS version: Windows_NT x64 10.0.18262

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (13.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by eamodio** [comment]
I'm also seeing duplicate entries in the quick file open menu too.

**Comment by eamodio** [comment]
Here is a video of part of it
![editors](https://user-images.githubusercontent.com/641685/47456097-95ef6200-d7a1-11e8-8603-f0398a833111.gif)

**Comment by bpasero** [comment]
@eamodio can you "Copy Path" of the two tabs to see if there is any difference. Also, can you check local storage again in the history entries of quick open to see if there are any differences.

This could be another hickup from @jrieken change where we just went back to the previous form of URI but some insiders still have the other form.

**Comment by jrieken** [comment]
> This could be another hickup from @jrieken change where we just went back to the previous form of URI but some insiders still have the other form.

Yeah, possible but we also changed the `$mid` property back so persisted uris should be revived in their compatible form...

**Comment by eamodio** [comment]
@bpasero Using "Copy Path" I see the exact same string for both tabs and it looks perfectly valid.

Here is my storage for that file:
```
[  
	{  
	   "resourceJSON":{  
		  "$mid":1,
		  "fsPath":"c:\\Users\\Eric\\code\\codestream\\codestream-lsp-agent\\src\\managers\\streamsManager.ts",
		  "external":"file:///c%3A/Users/Eric/code/codestream/codestream-lsp-agent/src/managers/streamsManager.ts",
		  "path":"/c:/Users/Eric/code/codestream/codestream-lsp-agent/src/managers/streamsManager.ts",
		  "scheme":"file"
	   }
	},
	{  
	   "resourceJSON":{  
		  "$mid":1,
		  "fsPath":"c:\\Users\\Eric\\code\\codestream\\codestream-lsp-agent\\src\\managers\\streamsManager.ts",
		  "external":"file:///c:/Users/Eric/code/codestream/codestream-lsp-agent/src/managers/streamsManager.ts",
		  "path":"/c:/Users/Eric/code/codestream/codestream-lsp-agent/src/managers/streamsManager.ts",
		  "scheme":"file"
	   }
	},
...
```

**Comment by jrieken** [comment]
>  exact same string

nope - look at the `file:///c%3A/` and `file:///c:`... interesting, must be an uri which we hand during a small window of breakage...

**Comment by jrieken** [comment]
@bpasero it should only affect windows and insiders but we can do another `$mid` change if that helps...

**Comment by bpasero** [comment]
@jrieken I think its fine, let's not introduce workarounds for this as it only impacts a small number of people and I think we are aware of that kind of issues by now.

@eamodio clearing the editor history once more should fix it.

**Comment by eamodio** [comment]
@jrieken using **Copy Path** in the UI, gave me the same exact string
