### ISSUE TITLE
vscode python program output is not expected

### ISSUE THREAD

**Issue by CHENGWEI001** [Microsoft/vscode#6174]
- VSCode Version:1.00
- OS Version:Windowns7 64bt

Steps to Reproduce:

1. in below file , executing test.py in
[testpy.zip](https://github.com/Microsoft/vscode/files/252680/testpy.zip)
2. assuming there is a line change between "hello"s, for example , if I run in command window, or other python IDE, I would see output like this :
![expected_output](https://cloud.githubusercontent.com/assets/13721617/15079955/6d4e1578-1370-11e6-8d2b-aec1272d8df9.PNG)

However , if I run this test.py in vscode python , I can't see empty lines between "hello"s , wondering any thing I missing in the setting file?

Best Regards
Jack

**Comment by bpasero** [comment]
I am very sorry to hear you are having issues with VS Code. Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
