### ISSUE TITLE
Remove inline git revert confirmation alert not fixed (Issue #43625)

### ISSUE THREAD

**Issue by luiscla27** [Microsoft/vscode#61740]
- VSCode Version: 1.28.2
- OS Version: Windows 8.1 Enterprise

Steps to Reproduce:

1. Just tried to revert a change
2. As you can see it seams like the released version doesn't have the changes made for the fix of issue [#43625](https://github.com/Microsoft/vscode/issues/43625)

![vscode-43625](https://user-images.githubusercontent.com/29953012/47449570-916a7f80-d788-11e8-890c-3eac1773329d.gif)

**Comment by joaomoreno** [comment]
That message was removed last June: https://github.com/Microsoft/vscode/commit/04aba36883f250725a40499e8e45e67f88439fdb#diff-344b8481439db2d9949984cbd9332879

That message can't even be found in our sources any longer. Please confirm that you are indeed on 1.28.2

**Comment by luiscla27** [comment]
i know it was removed! this is the message ghost coming back from the death... D: 

do you think the issue can be related to some kind of weird cache?
![vscode-issue61740](https://user-images.githubusercontent.com/29953012/47470685-6f92ec00-d7cc-11e8-9915-71ceb2f85469.gif)

**Comment by joaomoreno** [comment]
Oh wow... no idea actually. Could be. Does it repro if you fully reinstall VS Code?

**Comment by luiscla27** [comment]
**Solved**! reinstalling vscode did not helped, 

The issue was caused due to another extension... ([svn-scm)](https://github.com/JohnstonCode/svn-scm), you may see the command message [here](https://github.com/JohnstonCode/svn-scm/blob/98bce430090e01b6e501242218d47f15656671f4/src/commands/command.ts#L441).
![image](https://user-images.githubusercontent.com/29953012/47511392-b968ea00-d83f-11e8-935d-24632c4a43e9.png)


I've already reported this as an issue to the extension author. i thought this should've been prevented by launching vscode with `code --disable-extensions`.
