### ISSUE TITLE
Text dissapears when writing a command for the first time on a new terminal

### ISSUE THREAD

**Issue by animeshj9** [Microsoft/vscode#61753]
Issue Type: <b>Bug</b>

1. Open a new terminal 
2. Write something
3. All text dissapearse (except the command)

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.79GB (21.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-azurefunctions|ms-|0.12.0
azure-account|ms-|0.4.3
csharp|ms-|1.16.2

</details>

![vscode bug](https://user-images.githubusercontent.com/6694373/47458955-c3331480-d78f-11e8-8a88-3adb51ac2b27.png)

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/57803
