### ISSUE TITLE
Emmet abbreviation breaks after paste

### ISSUE THREAD

**Issue by jhildenbiddle** [Microsoft/vscode#61751]
- VSCode Version: 1.28.2
- OS Version: macOS 10.13.6

Steps to Reproduce:

1. Begin typing an Emmet abbreviation
2. Append to an abbreviation using the paste commend (e.g. `div.` + paste `foo` = `div.foo`)

At this point, VSCode no longer sees `div.foo` as an Emmet abbreviation (no tab completion available). Emmet functionality can be restored by adding any character, but this feels unnecessary. Ideally, Emmet would continue to recognize an abbreviation after using the paste command to append to a string.

Does this issue occur when all extensions are disabled?: Yes

**Comment by ramya-rao-a** [comment]
Emmet has been implemented using the auto-completion feature.
Auto-completion is triggered when typing and not pasting.

To get around this you can manually trigger the auto-completion feature by pressing `Ctrl+Space` after pasting the text. Or if you want to always have the tab key trigger emmet, then set `emmet.triggerExpansionOnTab` to `true`

**Comment by jhildenbiddle** [comment]
Sounds good. Thanks, @ramya-rao-a!
