### ISSUE TITLE
Can not open URL in MarkupContent in CompletionItem's documentation

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#61754]
I was playing with the idea of providing links to MDN for each CSS property.

Currently clicking the URL does not open the webpage:

![image](https://user-images.githubusercontent.com/4033249/47459979-510fff00-d792-11e8-8039-08a00388e506.png)

**Comment by jrieken** [comment]
> Currently clicking the URL does not open the webpage:

and? what does it do?

**Comment by octref** [comment]
I don't know what changed, but this does not repro in latest version any more.
