### ISSUE TITLE
The embedded terminal slows down over time

### ISSUE THREAD

**Issue by graph** [Microsoft/vscode#61759]
Windows:

Version: 1.28.2 (system setup)
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:23:51.859Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

linux (Ubuntu):
Version: 1.28.2
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:20:56.183Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

So far I experienced this on windows & linux. More significantly on windows.

Steps to Reproduce:

1. just use the terminal throughout the day
2. eventually typing becomes laggy and the only fix is to restart vs code

Does this issue occur when all extensions are disabled?: I haven't tried but no new extensions since the last update.

I stopped debugging my app and terminal resumed speed. Maybe it's my app lol. My app uses 100% CPU, and vs terminal is significantly effected, other apps I use. I tried running my app outside of vs code and vs code terminal became laggy instantly. Other apps are not so laggy while my app I'm building is running. Sometimes each keystroke takes more than a second.

Scrolling on linux is slow for some reason regardless of my app running or not. Restarting doesn't help. On linux it doesn't get super laggy like it does on windows.

When doing `man rsync` or anything scrolling is very slow. I'm pretty certain there is an issue with the terminal now being too slow.

**Comment by dhensen** [comment]
(this is a "me-too" bump)

Me and two other colleagues experience the same thing since a few days also (we keep vscode up to date). I personally experience on both my work laptop (ubuntu 18.04) and personal laptop (arch linux):

```
Version: 1.28.2
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:20:56.183Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

Colleague 1: uses ubuntu 18.04 (updates regularly, but have to verify version)
Colelague 2: uses Windows 7 (updates regularly, but have to verify version)

**Comment by Tyriar** [comment]
What's in your settings.json? Have you you tried changing the rendererType setting?

**Comment by graph** [comment]
```
{
    "files.autoSave": "onFocusChange",
    "files.eol": "\n",
    "C_Cpp.errorSquiggles": "Disabled",
    "keyboard.dispatch": "keyCode",
    "editor.rulers": [
        80,
        100,
        120
    ],
    "editor.smoothScrolling": true,
    "editor.minimap.enabled": false,
    "editor.minimap.maxColumn": 80,
    "window.titleBarStyle": "custom",
    "window.restoreWindows": "none",
    "editor.folding": false,
    "window.zoomLevel": -1,
    "window.menuBarVisibility": "default",
    "workbench.activityBar.visible": true,
    "C_Cpp.commentContinuationPatterns": [
    ],
    "breadcrumbs.enabled": true,
    "workbench.iconTheme": "file-icons",
    "editor.fontWeight": "bold",
    "editor.quickSuggestions": {
        "other": true,
        "comments": true,
        "strings": true
    },
    "typescript.tsc.autoDetect": "off",
    "npm.autoDetect": "off",
    "jake.autoDetect": "off",
    "gulp.autoDetect": "off",
    "grunt.autoDetect": "off",
    "cmake.configureOnOpen": false,
    "extensions.ignoreRecommendations": true
}
```

that's on my linux machine.

**Comment by graph** [comment]
This is just a duplicate of https://github.com/Microsoft/vscode/issues/56517 changing the rendertype canvas/dom for me it's both slow.
