### ISSUE TITLE
Opening files from multiple zip files where filenames are the same doesn't open multiple file tabs in VSCode

### ISSUE THREAD

**Issue by ryan-roberts** [microsoft/vscode#61764]
Issue Type: <b>Bug</b>

1) CMD instance
CMD>md 1\ZippedFolder
CMD>md 2\ZippedFolder
CMD>echo Foo > 1\ZippedFolder\ZippedFile.log
CMD>echo Bar > 2\ZippedFolder\ZippedFile.log
2) In Windows Explorer, right click each folder "ZippedFolder" and send to "Compressed Folder" to create two zip files, both named ZippedFolder.zip.
3) Open 1\ZippedFolder.zip and open ZippedFile.log within it in VSCode
4) Open 1\ZippedFolder.zip and open ZippedFile.log within it in VSCode

Expected: Two files in VSCode, both named ZippedFile.log.
Actual: Last file opened wins, only one ZippedFile.log opened.

In my work environment it's common to have large build logs zipped up with each build so I frequently come across files like Logs.zip which have log files within them from common build components. In many cases I want to see these files side by side and I can do this with notepad++ but not VSCode which handles large files really well.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz (12 x 3298)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.91GB (35.29GB free)|
|Process Argv|\\gssuper03\v410\_Checkpoints\5390091\history.log --max-memory=10240|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by bpasero** [comment]
@ryan-roberts we do not support to open files within zip archives so I am not sure what you are trying to do?

**Comment by ryan-roberts** [comment]
Sorry, my steps #3 and #4 are a bit ambiguous. Where I say "Open *\ZippedFolder.zip and open ZippedFile.log within it in VSCode" I mean double-click the zip in a Windows Explorer view to get a new Windows Explorer view of the zip's contents and then open ZippedFile.log within that window. Assuming file mapping of .log to VSCode that file open should open the file in VSCode.

The issue here is the implicit extraction that Windows Explorer performs when you open a file from a .zip file window creates that file at a path like: _C:\Users\rroberts\AppData\Local\Temp\Temp1_ZippedFolder.zip\ZippedFolder\ZippedFile.log_
- **With VSCode**, opening a second file with the same name from a different .zip file (but same .zip file name) winds up creating a temporary file at the same path and VSCode doesn't open the file again as it sees a file already open at that path.
- **With Notepad++** the same scenarios works because it sees two distinct paths for the files--
C:\Users\rroberts\AppData\Local\Temp\Temp**1**_ZippedFolder.zip\ZippedFolder\ZippedFile.log
 C:\Users\rroberts\AppData\Local\Temp\Temp**2**_ZippedFolder.zip\ZippedFolder\ZippedFile.log

**Comment by bpasero** [comment]
@ryan-roberts so when you open 2 files at once, both are extracted to the same paths, isn't that an issue you should report to them?

**Comment by ryan-roberts** [comment]
No, it appears the bug is with VSCode as the files are extracted to different paths.
VSCode appears to not use the entire filepath when opening files via code.exe parameters when opened via Explorer.exe.

If the repro is performed with [Process Monitor ](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) running you will see activity like the following:

1. Double-click ZippedFile.log  in the first ZippedFolder.zip Explorer window
2. ProcessMonitor> Explorer.exe CreateFile C:\Users\rroberts\AppData\Local\Temp\Temp1_ZippedFolder.zip\ZippedFolder\ZippedFile.log
3. ProcessMonitor> _Explorer then WriteFile/.../CloseFile on the same file path to finish it up_
4. ProcessMonitor> Explorer.exe ProcessCreate: Command line: **"C:\Program Files\Microsoft VS Code\Code.exe" "C:\Users\rroberts\AppData\Local\Temp\Temp1_ZippedFolder.zip\ZippedFolder\ZippedFile.log"**

5. Double-click ZippedFile.log in the second ZippedFolder.zip Explorer window
6. ProcessMonitor> Explorer.exe CreateFile C:\Users\rroberts\AppData\Local\Temp\Temp2_ZippedFolder.zip\ZippedFolder\ZippedFile.log
7. ProcessMonitor> _Explorer then WriteFile/.../CloseFile on the same file path a few more time to tend to that file also_
8. ProcessMonitor> Explorer.exe ProcessCreate: PID: 20560, Command line: **"C:\Program Files\Microsoft VS Code\Code.exe" "C:\Users\rroberts\AppData\Local\Temp\Temp2_ZippedFolder.zip\ZippedFolder\ZippedFile.log"**

The two bolded paths passed to code.exe above are different.

However, if I run the following from a simple command prompt later the issue no longer repros:
CMD> C:\Program Files\Microsoft VS Code\Code.exe" "C:\Users\rroberts\AppData\Local\Temp\Temp1_ZippedFolder.zip\ZippedFolder\ZippedFile.log"
CMD> C:\Program Files\Microsoft VS Code\Code.exe" "C:\Users\rroberts\AppData\Local\Temp\Temp2_ZippedFolder.zip\ZippedFolder\ZippedFile.log"

So it seems to be something about how code.exe handles the file open from Explorer.exe versus other opens like those from the command prompt.
