### ISSUE TITLE
Go to/Peek Definition and Find all References in CSS

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#6176]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Open a css file
2. Right click to show context menu

Shows grayed out Go to Definition, Peek Definition and Find all References:

![contextmenucss](https://cloud.githubusercontent.com/assets/12900364/15085620/3201b1ee-1390-11e6-8af7-2a7c0829d675.PNG)

Other file types that do not support them, they are not included in the right click context menu. Are they included here for some other reason?

**Comment by aeschli** [comment]
With the recent changes of support for css variables, the menus make sense again and we show them everywhere.
