### ISSUE TITLE
There is a problem with the interaction logic of the button on the lower left corner.

### ISSUE THREAD

**Issue by nantianliao** [Microsoft/vscode#61766]
- VSCode Version:1.28.2
- OS Version:Windows 10 Home 1803

I think its interaction logic should be like the Windows menu button.

Steps to Reproduce:
1.Open your VSCode ;
2.Repeat click gear button, It does not rotate alternately like opening / closing.
3.Sometimes you can offset a little bit and you'll find that the menu's position has changed, not fixed.

**Comment by weinand** [comment]
What gear on the lower right corner are you talking about?
Please provide a screenshot.

**Comment by nantianliao** [comment]
> What gear on the lower right corner are you talking about?
> Please provide a screenshot.

@weinand 
1). I mean the button in the yellow circle.

![_20181025145249](https://user-images.githubusercontent.com/11886245/47481951-c4377500-d867-11e8-94fe-4a76f6bdb53b.png)

2).If the button is clicked at different locations within the clickable range of the button, the position of the menu will change rather than be fixed to a certain location.

![_20181025145527](https://user-images.githubusercontent.com/11886245/47482030-fea11200-d867-11e8-8ddb-5b2e79afddea.png)
![_20181025145445](https://user-images.githubusercontent.com/11886245/47482035-02349900-d868-11e8-98ae-f03674089908.png)

**Comment by weinand** [comment]
I don't consider this a problem that need fixing.

**Comment by nantianliao** [comment]
I mean this button should be like any other button's interaction logic: the menu switches between open and close when clicked repeatedly.

If this interaction logic reaches your expectations, please ignore what I have said. Thank you.

**Comment by weinand** [comment]
Yes, you are right:
clicking the gear once opens the menu, but clicking the gear again does not close it.

**Comment by bpasero** [comment]
Imho not a big deal. On macOS the menu closes though when clicked again.
