### ISSUE TITLE
Provide go to definition and peek for Classic ASP includes.

### ISSUE THREAD

**Issue by pr3sidentspence** [microsoft/vscode#61767]
Go to definitions, peeks, and documentLinks don't work on URIs in Classic ASP includes, like
`<!--#include virtual="/includes/master/meta.htm" -->`
perhaps because they are inside comments,  but that's just a guess.

It would be great to be able to enable this. I did find #49933 which seems like a similar request. @mjbvz [suggested ](https://github.com/Microsoft/vscode/issues/49933#issuecomment-389320458)an extension could be developed to do this. I'm not experienced enough to get from A->B on my own, but I'd be happy to work on this if someone could point me farther in the right direction.

(In a perfect world, the includes would open inline with the parent document, so that things like indenting, tag and bracket matching, and beautifiers would work.)

**Comment by weinand** [comment]
Please file this feature against the extension that provides ASP support.

**Comment by pr3sidentspence** [comment]
Which extension of the many? Is there an official one?

**Comment by weinand** [comment]
You did not provide any information what extensions you are using, so I cannot help.

**Comment by weinand** [comment]
Yes, the feature "Look in HTML comments for URIs to attempt to document link." makes sense.
