### ISSUE TITLE
files keep randomly disappearing

### ISSUE THREAD

**Issue by r3wt** [Microsoft/vscode#61761]
Issue Type: <b>Bug</b>

not sure if its vscode or git, but every so often files come up missing. its happened about 5 times thus far, and i can't pinpoint the cause. 

my git workflow is:

```
git commit -am <MY COMMIT MESSAGE> && git push && git checkout master && git pull && git merge <MY BRANCH> && git push && git checkout <MY BRANCH>
```
I run this command when i am deploying code for a feature branch, so that i can quickly merge to master and trigger a deploy then switch back to my working branch.

occassionally files will be missing after this, and i have to perform a `git stash`, at which time the files are restored. its so bizarre, but i can't tell if its bad behavior from vscode, the shell, or a problem with my git workflow.

so far the files that have come up missing:

- react-date-picker from my node modules, entire directory was gone.
- src/components/RedactedComponentName.js
- src/lib/tools.js
- package.json
- scripts/build.js

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (10.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
twigcs|cer|0.4.2
php-debug|fel|1.12.6
php-intellisense|fel|2.3.5
php-pack|fel|1.0.2

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Well, please do some testing and make sure it's VS Code. If it happens to be, let me know. If it's not, please reach out to the git project.

**Comment by r3wt** [comment]
@joaomoreno it is not my job to test your project. you get paid for this, i don't. perhaps you people should fix your crap
