### ISSUE TITLE
lag while new update

### ISSUE THREAD

**Issue by imshivamchauhan** [Microsoft/vscode#61779]
Issue Type: <b>Bug</b>

IDE starts to lag or hang whenever there is a new update arrives in the background or any notification arrives. 

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 6.3.9600

**Comment by Migggz** [comment]
The same problem

**Comment by joaomoreno** [comment]
OK let me know.

**Comment by imshivamchauhan** [comment]
![process-explorer](https://user-images.githubusercontent.com/33184564/47702997-bc4f4a80-dc44-11e8-9073-0c83f8efeea8.png)

again its happening,lagging every-time switching tab or opening new file., see attached snapshot of process explorer.

**Comment by joaomoreno** [comment]
Can you perhaps do the following when it happens again:

1. Run `Developer: Toggle Developer Tools`
2. Switch to the `Performance` tab
3. Run a performance recording for ~10 seconds without touching anything

Send me that recording. Thanks!
