### ISSUE TITLE
Once start debugging failed, it cannot start again 

### ISSUE THREAD

**Issue by saurabhnachankar** [Microsoft/vscode#61770]
Issue Type: <b>Bug</b>

Sometimes i write some wrong code, when start debugging it shows "Process exiting with code: -1". After that, i can't start debugging.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2105 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.89GB (1.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.1.0
githistory|don|0.4.3
gitlens|eam|8.5.6
git-project-manager|fel|1.7.1
csharp|ms-|1.16.2
vsliveshare|ms-|0.3.834
vscode-icons|rob|7.27.0

</details>

**Comment by saurabhnachankar** [comment]
I figured it out. Microsoft liveshare extension is causing the problem.

After uninstalling it perfectly worked with me!

Happy coding!

**Comment by isidorn** [comment]
Feel free to file an issue to the live share extension here https://github.com/MicrosoftDocs/live-share
