### ISSUE TITLE
"Go to file…" does not work on remote filesystems like fuse+sshfs

### ISSUE THREAD

**Issue by emmby** [Microsoft/vscode#6177]
- VSCode Version: 1.0.0
- OS Version: OS X 10.11.4

Steps to Reproduce:

1. Use OSXFuse + sshfs to mount a remote directory
2. open the directory in Code
3. type cmd-P and type a file name

The command window will indicate it's working for a few seconds, but nothing will happen.

**Comment by bpasero** [comment]
@emmby something in the developer console?

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Comment by emmby** [comment]
Hi @bpasero, can you clarify your question?  I'm not sure what you're asking regarding the developer console.

**Comment by bpasero** [comment]
@emmby Help > Toggle Developer Tools > Console is what I was referring to.

**Comment by emmby** [comment]
It appears that my initial report was incorrect – if you wait long enough, eventually there is eventually a response.  In my case it takes about two minutes.  You can see the video here: http://cl.ly/0w200J3t1R1q  You can also see the console in the video, there are no messages.

I'm guessing the issue is that the index is not working, or else there is no index.  In the video you can see I searched for the same term twice, and the second time took just as long as the first.  It doesn't matter whether the directory containing the file is open in the explorer on the left.

**Comment by bpasero** [comment]
Yeah, see also https://github.com/Microsoft/vscode/issues/55 as related.

**Comment by emmby** [comment]
Yes, you're right, looks like they're all related.
