### ISSUE TITLE
Update fails in this version

### ISSUE THREAD

**Issue by modul8com** [Microsoft/vscode#61774]
Issue Type: <b>Bug</b>

Using the Insiders version, it seems to fail to update... the download works, but restarting Code to start the installation fails with an error.

VS Code version: Code - Insiders 1.29.0-insider (8aef44b6426b37ccb22026f56f52f42d136f4a0a, 2018-10-24T10:07:06.221Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (1.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.10
xml|Dot|2.3.2
gitlens|eam|8.5.6
tslint|eg2|1.0.40
Angular2|joh|6.3.0
Angular-BeastCode|Mik|7.0.6
csharp|ms-|1.16.2
vsliveshare|ms-|0.3.869
debugger-for-chrome|msj|4.10.2
quicktype|qui|12.0.46
vscode-icons|rob|7.27.0
ngx-translate-zombies|sev|0.0.1

</details>

**Comment by modul8com** [comment]
The error you get =
Unhandled exception at 0x010603CE in inno_updater.exe: 0xC000001D: Illegal Instruction. occurred

**Comment by joaomoreno** [comment]
Interesting. You can get around it by disabling background updates: `"update.enableWindowsBackgroundUpdates": false`

Also, do you have a screenshot of the error?
