### ISSUE TITLE
The window size is adjusted when the menu item is expanded, and the menu item is beating

### ISSUE THREAD

**Issue by freezestudio** [Microsoft/vscode#61785]
windows 7 vscode 1.28.x

1.打开vscode窗口
2.展开任意菜单项，例如：帮助
3.保存菜单的打开状态，缩小窗口
4.此时将鼠标移到菜单栏
5.菜单项会反复跳动

1. Open the vscode window
2. Expand any menu item, for example: help
3. Keep the menu's open state, reduce the window, and at least zoom out to the menu that pops up in the overlay.
4. Move your mouse over the menu bar, near the program icon location.
5. Menu items will repeatedly beat

**Comment by sbatten** [comment]
this should be fixed as a result of the menu now correctly closing on window resize
