### ISSUE TITLE
Required extensions in workspace settings

### ISSUE THREAD

**Issue by skolmer** [Microsoft/vscode#6178]
I would like to have a required extensions section in settings.json of my workspace. These extensions should be automatically installed when a project is opened the first time or a warning message should be shown that required extensions are missing. 
At the moment I need to instruct my team to install specific extensions to work on a shared project. It would be nice to automate this process.

**Comment by patsissons** [comment]
This is a fantastic idea. Ensuring a consistent workspace across developers would help with code (style, linting, UX) consistency.

**Comment by spywhere** [comment]
I think this issue is kind of a dup of #5559.

**Comment by skolmer** [comment]
Thanks for digging this up.  #5559 describes it pretty good. Please close this issue.
