### ISSUE TITLE
Unable to install goformat extension in vscode

### ISSUE THREAD

**Issue by rajender-ufo** [Microsoft/vscode#61788]
vscode: 1.28.2 
linux: fedora26
Unable to install goformat extension
Failed with the following error:

Tried both:
1. go get winterdrache.de/goformat/goformat
 and 
2. go get github.com/mbenkmann/goformat/goformat

# winterdrache.de/goformat/printer
../../winterdrache.de/goformat/printer/nodes.go:1580: s.Assign undefined (type *ast.TypeSpec has no field or method Assign)

**Comment by weinand** [comment]
Are the projects you mention actually VS Code extensions?
If yes, how did you try to install them? 
Please provide better steps for what you did.

In addition you said "Failed with the following error:" but there is no error.
Please provide this info.

**Comment by weinand** [comment]
file this against go extension
