### ISSUE TITLE
[Accessibility]A11y_PowershellEditorServices_Installation_Screenreader:NVDA reads the Tab item control type as Button for the "Details,Contributions,Changelog,Dependencies".

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#61784]
**Environment Details:**
VSCode Version : 1.25.1
OS Version : Win10,NVDA[2018.2]
MAS1.3.1
**Repro Steps:**
1.Launch Visual Studio code desktop application.
2.Navigate to "Extension" button of "ActivityBar"->Enter "PowerShell" in "Search Extension" text field and click on "Install" button.
3.Navigate through keyboard such as "Tab" key.
4.Observed that what NVDA reads for the Tab item.

**Actual:**
NVDA reads the tab item as button for "Details,Contributions,Changelog,Dependencies".

**Expected:**
NVDA should read the control type as Tab item for "Details,Contributions,Changelog,Dependencies".

**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
[https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx](url)

**User Impact:**
User will not able to know the correct control type.

**MAS Reference:**
MAS1.3.1
[https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}](url)

Does this issue occur when all extensions are disabled?: Yes
**Attachment for Reference:**
![a11y_powershelleditorservices_installation_screenreader](https://user-images.githubusercontent.com/39204909/47491185-f2b55000-d867-11e8-9a9c-b2ae3baef907.png)

**Comment by isidorn** [comment]
Should be fixed in latest vscode
