### ISSUE TITLE
The code hint suddenly disappeared.of frequent occurrence!!!!

### ISSUE THREAD

**Issue by ivedk123** [Microsoft/vscode#61782]
Issue Type: <b>Bug</b>

经常用着用着就没代码提示了，每次都要重启一次才恢复。
The code hint suddenly disappeared.of frequent occurrence!Every time you need to restart the software, It will return to normal.
VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (1.83GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.40
vscode-language-pack-zh-hans|MS-|1.28.2

</details>

**Comment by weinand** [comment]
I don't understand what you mean.
Please provide steps and/or screenshots.
