### ISSUE TITLE
Explore update to Electron 4

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#61787]
**VSCode Exploration Builds with Electron 4.0.x:**
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/code-exploration_1.31.0-1544686921_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCodeUserSetup-x64-1.31.0-exploration.exe)

**Comment by bpasero** [comment]
@Tyriar for some bizarre reason, `vscode-nsfw` fails to load for me even though I can compile it. This is on Windows 10:

![image](https://user-images.githubusercontent.com/900690/47504478-9c96db80-d86c-11e8-83b1-77b7092a1ab5.png)

**Comment by Astrantia** [comment]
When will be Electron 3 pushed to insiders and Electron 4 pushes to exploration?

**Comment by bpasero** [comment]
@Astrantia current idea is January 2019.

**Comment by bpasero** [comment]
I think it was there.

**Comment by bpasero** [comment]
@Tyriar this is when running out of sources, so ASAR is not involved. And I just checked, the `nsfw.node` file is there.

**Comment by bpasero** [comment]
@Tyriar looks like this might be caused by nsfw setting this in `binding.gyp`:

`"win_delay_load_hook": "false"`

See https://github.com/electron/electron/issues/15436#issuecomment-434232193

However I am still struggling to load the module even after making this change: https://github.com/Axosoft/nsfw/compare/master...Microsoft:electron-4.0.x

**Comment by bpasero** [comment]
I published vscode-nsfw@1.1.2 which should take care of this.

**Comment by dalDevelo** [comment]
@bpasero I've used the provided link to download the electron 4 build for macOS. Immediately after install, running 'process.versions.electron' in dev tools reports that v4.0.0 beta.7 is being used, however as soon as the application updates, the electron version number is rolled back to v3.0.9. Is this supposed to be the case, or is there something at your end that needs to be changed so that this build looks in a different location for electron 4 related updates?

**Comment by bpasero** [comment]
@dalDevelo yeah as long as exploration builds are not yet on Electron 4, you will have to configure `update.channel: none` in settings to prevent updates.

At this time I would stay away from using the Electron 4.0.x builds for any serious work.

**Comment by Zehua-Chen** [comment]
I tried to load [microsoft.github.io](https://microsoft.github.io/monaco-editor/) using the just-released electron 4 beta 8 on macOS Mojave, and I do not think font rendering is improved at all.

# VS Code
<img width="584" alt="code" src="https://user-images.githubusercontent.com/31496190/49325601-001ac580-f50b-11e8-9040-ebca61f3ddec.png">

# Electron 4 Beta 8
<img width="696" alt="electron 4 beta 8" src="https://user-images.githubusercontent.com/31496190/49325603-08730080-f50b-11e8-995a-314de0d29b93.png">

Safari, on the other hand, looks normal.
<img width="697" alt="safari" src="https://user-images.githubusercontent.com/31496190/49325617-44a66100-f50b-11e8-83fc-ad59a31cb290.png">

**Comment by bpasero** [comment]
Now that insiders got Electron 3 I will make the exploration builds consume Electron 4.

**Comment by dalDevelo** [comment]
@bpasero what is the situation with the exploration builds if there are multiple stable Electron releases available? Electron 5 beta 1 was published yesterday. Assuming stable Electron 5 is released in the coming weeks, will VScode exploration jump to this version for exploration, or will the Electron 4 exploration continue to be worked on until it reaches insiders / main release, thus delaying Electron 5 adoption?

**Comment by bpasero** [comment]
@dalDevelo exploration will always be 1 version after the current version we have in insiders and only move on to the next once we increment the version in insiders.

**Comment by auchenberg** [comment]
@bpasero What's the platform consequences of upgrading to Electron 4.0? We'd loose Linux 32bit?

**Comment by bpasero** [comment]
@auchenberg yes likely

**Comment by maciejw** [comment]
I'm curious, what happened that this item is deferred in iteration plan? is there a technical issue of lack of time? or its because of electron 5 on a horizon?

**Comment by bpasero** [comment]
@maciejw as long as there are open electron adoption blockers (see [query](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aelectron-blocker)) it is unlikely we can ship with Electron 4.x.

**Comment by gulshan** [comment]
Is it possible to skip 4 and update to Electron 5? The only v4 adoption blocking issue is said to be fixed in v5- https://github.com/electron/electron/issues/16925

**Comment by bpasero** [comment]
We will try to get a release out with Electron 4 and at the same time start to look into adopting Electron 5. It is unlikely we would just skip one version given all the work that is involved.

**Comment by iansan5653** [comment]
Is a user version of the exploration build for Windows available? I'd like to try it but don't have admin rights on this machine.

**Comment by danilaml** [comment]
It looks like there are no blockers now and it's been in "Explore" state for quite some time. Is there any reason left why it's still Deferred?

**Comment by bpasero** [comment]
@danilaml this will land in insiders during June. We felt the current iteration was too short to push this already. If there are new blockers found, it may delay further though.

**Comment by maciejw** [comment]
is exploration build up to date with insiders and only difference is electron? if so, then maybe we have some issues, I'm using exploration build with electron 4.2 and extensions host crashes regularly during startup, sometimes while using editor.

**Comment by bpasero** [comment]
@maciejw which version are you on (check the commit hash from the about dialog). If it is latest then I would be happy for some reproducible steps how to get to these crashes if possible.

**Comment by maciejw** [comment]
@bpasero it was on 291cc2dd4, I'll let you know if this is still the issue I've just installed a2873dc8b. I wondered, was it an extensions fault maybe? I synced my settings including all extensions. when this crash will happen, callstack and details from dev console will be enough to help diagnose it? this issue happens randomly I did not find any particular pattern what causes it.

**Comment by bpasero** [comment]
@maciejw yeah we can revisit this once you can still reproduce, looks like you were on quite an old version of the exploration branch.

**Comment by maciejw** [comment]
@bpasero just after update to 3ac052e the error appeared, below is a console log

```
[Extension Host] debugger listening on port 39926
workbench.main.js:3311 Extension Host
workbench.main.js:3311 Debugger attached.
workbench.main.js:3183 Extension host terminated unexpectedly. Code:  3221225477  Signal:  null
_onExtensionHostCrashed @ workbench.main.js:3183
workbench.main.js:2380 Extension host terminated unexpectedly.
onDidNotificationChange @ workbench.main.js:2380

```

after window refresh works fine.

**Comment by bpasero** [comment]
@maciejw and you are not seeing this in our insiders build? Does it reproduce when you run with `--disable-extensions`?

**Comment by bpasero** [comment]
Pushed to master via https://github.com/microsoft/vscode/commit/73643c60a644145c6a57b61787efd6a62e153cfa. Will be out in insiders end of week when we released stable.

**Comment by maciejw** [comment]
@bpasero I have not tried this switch since this error happens randomly. I run the same extensions on stable and insider and I have not noticed , we will see if this error persists on master.

**Comment by albertosantini** [comment]
In Electron v4 be aware also to [Issue 683994: context.drawImage() slows down massively when drawing a few large images](https://bugs.chromium.org/p/chromium/issues/detail?id=683994#c35), a regression in the Canvas API.

Just my two cents. Thanks for the effort.

**Comment by bpasero** [comment]
^ @Tyriar

**Comment by Tyriar** [comment]
@albertosantini thanks for the info

**Comment by albertosantini** [comment]
@Tyriar Credits to [Hyper Blog](https://hyper.is/blog) - Hyper 3 announce, I suppose you know. ;)

> Electron V3

> Hyper 3 bumps the underlying Electron from V1 to V3. We also tested V4, but a regression in the Canvas API forced us to stay on V3. The upgrade brings in newer versions of V8 and Node.js, and their corresponding bug fixes.
