### ISSUE TITLE
electron-proxy-agent: [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#61796]
@chrmarti saw this when running VSCode with Electron 3.0.x. I think your newly introduced dependency either uses the deprecated buffer constructor or depends on some very old libraries. Are we still on track for this milestone to come up with a fork?

**Comment by chrmarti** [comment]
The fork is there. I need to allocate some time to it.

**Comment by chrmarti** [comment]
/duplicate

Fixed with #60773.
