### ISSUE TITLE
Themes: Create a filter or view specifically for theme extensions

### ISSUE THREAD

**Issue by CJPrindle** [Microsoft/vscode#61798]
When searching through my extension list I regard the theme entries as noise most of the time. It would be nice to have a way to view extensions minus the themes or, conversely, view just the themes alone. 

Perhaps a new option on the Extensions popup would be the easiest way.

**Comment by ramya-rao-a** [comment]
To view just the installed themes you can use `@installed @category:themes`. You can use different categories this way. Type `@category` in the search box in the extension view to see other categories.

https://github.com/Microsoft/vscode/issues/49374 is tracking the feature of having exclusion filters for your scenario of seeing non theme extensions.
