### ISSUE TITLE
Directly navigate to a symbol within a file

### ISSUE THREAD

**Issue by guywald1** [Microsoft/vscode#61799]
**Issue type**: Feature Request

---

Currently, to navigate to a symbol inside a source file, the user must first navigate to the file and use the quickpick with the symbol prefixed with a `#`. i.e. to get to the function `hello` inside `lib.js`, the user must open `lib.js` and then they can type `#hello` in the quickpick.

My suggestion: add the ability to navigate directly to the symbol by typing `lib#hello` in the quickpick. Possibly by adding `#<symbol>` to a search query, the symbol should be searched within the top match. Filenames can have hashes so any matching files should ideally have precedence in the options.

WDYT?

**Comment by mjbvz** [comment]
Does [workspace symbol search](https://code.visualstudio.com/docs/editor/editingevolved#_open-symbol-by-name) do what you want?

**Comment by jrieken** [comment]
> Yes, but what I'm suggesting is a file-specific symbol search

We call that quick outline, the prefix is `@` and we have that already built into the tools.
