### ISSUE TITLE
Rename Symbol not translated

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#6180]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Change language to non-english
2. Right click > observe Rename Symbol is not translated
3. F1 palette 'Rename Symbol' is also not translated 

Looks like a regression as it is translated in 1.1.0 insiders.

**Comment by Ikuyadeu** [comment]
cff665d rename from `rename2` to `rename`.
But  /in18n/ file is still rename2.
 (ex. `vscode/i18n/rus/src/vs/editor/contrib/rename/browser/rename2.i18n.json`)

**Comment by jrieken** [comment]
you are testing this too early
