### ISSUE TITLE
Terminal divider doesn't respect the project I select when opening a new one

### ISSUE THREAD

**Issue by nahuelhds** [Microsoft/vscode#61801]
Issue Type: <b>Bug</b>

Having two folders in the workspace: A and B.

The terminal opens in A project folder by default, when adding a new terminal pane to the right and I select B, the pane opens on project A folder.

VS Code version: Code - Insiders 1.29.0-insider (4a29bd3731e40c07622bae0e9b0ac3b422b5672a, 2018-10-25T05:40:46.260Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 3|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv|-psn_0_491640|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (58)</summary>

Extension|Author (truncated)|Version
---|---|---
output-colorizer|IBM|0.1.2
project-manager|ale|9.0.1
vscode-color|ans|0.4.5
vscode-intelephense-client|bme|0.8.8
vscode-standardjs|che|1.2.3
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
laravel-blade|cjh|1.1.2
bracket-pair-colorizer|Coe|1.0.60
vscode-svgviewer|css|1.4.7
vscode-markdownlint|Dav|0.20.0
vscode-eslint|dba|1.6.1
githistory|don|0.4.3
es7-react-js-snippets|dsz|1.8.7
vscode-babel-coloring|dza|0.0.4
gitlens|eam|8.5.6
vscode-phpmd|eco|1.1.0
EditorConfig|Edi|0.12.5
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.6.1
php-debug|fel|1.12.6
flow-for-vscode|flo|0.8.4
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.4
smarty|imp|0.3.0
docthis|joe|0.7.1
php-cs-fixer|jun|0.1.85
dotenv|mik|1.0.1
vscode-apache|mrm|1.1.1
vscode-scss|mrm|0.6.2
vscode-language-pack-es|MS-|1.29.0
python|ms-|2018.9.1
atom-keybindings|ms-|3.0.4
node-debug2|ms-|1.29.2
debugger-for-chrome|msj|4.10.2
php-docblocker|nei|1.6.0
vetur|oct|0.13.0
laravel5-snippets|one|1.5.0
vuehelper|oys|0.1.0
vscode-php-getters-setters|php|1.2.3
ejs-language-support|Qas|0.0.1
laravel-helpers|raf|0.2.2
sass-indented|rob|1.4.9
laravel-artisan|rya|0.0.22
vscode-sass-format|sas|1.1.6
code-settings-sync|Sha|3.2.0
vscode-nginx|sha|0.5.0
autoimport|ste|1.5.3
Align|ste|0.2.0
vsfire|tob|1.3.2
hosts|tom|1.1.1
sort-lines|Tyr|1.7.0
cordova-tools|vsm|1.4.0
vscode-react-native|vsm|0.6.18
vscode-todo-highlight|way|1.0.4
twig|wha|1.0.2
vscode-import-cost|wix|2.9.0

</details>

**Comment by nahuelhds** [comment]
The duplicate detection is wrong. This is not related with that issue nor the ones that it mentions.

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/61515

**Comment by nahuelhds** [comment]
@Tyriar this keeps happening.

The "new terminal" button works correctly now. That's fixed.
But if I try to open a new pane with the "Divide terminal" command keeps happening what I reported here.

**Comment by Tyriar** [comment]
See https://github.com/Microsoft/vscode/issues/61515, the fix is coming in v1.29
