### ISSUE TITLE
The variables reference in WSL

### ISSUE THREAD

**Issue by OhYee** [Microsoft/vscode#61807]
When I use `"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\bash.exe"`, and run the task:
```json
{
            "label": "test",
            "type": "shell",
            "command": "echo \"${file}\"",
            "presentation": {
                "reveal": "always",
                "echo": false
            },
            "problemMatcher": []
        },
```

It will output the path under Windows(like `c:\Users\xxx\a.cpp`), I think it would be better to use the WSL path(like `/mnt/c/Users/xxx/a.cpp`).

Maybe nobody will use windows path in bash.

It is also good to set the new variables reference like `${wslFile}`, `${wslFolder}`

----
Also, the Java and Python extensions, can not work better when using the WSL environment.
eg: I cannot use the code auto-complate.

**Comment by Tyriar** [comment]
We just announced remote development with VS Code, check out the blog post for details https://code.visualstudio.com/blogs/2019/05/02/remote-development
