### ISSUE TITLE
Latest insider shows duplicate files in quick open

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#61805]
- VSCode Version: Version: 1.29.0-insider (4a29bd3731e40c07622bae0e9b0ac3b422b5672a) (x64)
- OS Version: Windows 10 x64 / (October 2018 update)

Steps to Reproduce:

1. press ctrl + p to show quick open panel

Does this issue occur when all extensions are disabled?: Yes

Here is a screenshot of the quickopen panel:

![image](https://user-images.githubusercontent.com/199648/47511531-b3442f00-d87a-11e8-810a-186ff73a1220.png)

**Comment by chrmarti** [comment]
@roblourens Any idea? Nothing changed on the UI side from what I know.

**Comment by roblourens** [comment]
@bpasero? These are in the Recently Opened list which doesn't touch search.

**Comment by bpasero** [comment]
@warpdesign you will have to "Clear Editor History" and then its fine. We had a URI migration hickup.
