### ISSUE TITLE
Issue with the terminal directory label

### ISSUE THREAD

**Issue by rohanvtk** [Microsoft/vscode#61803]
Issue Type: <b>Bug</b>

The directory shows up and dissappers randomly while working on the terminal inside VS Code. Please fix this issue, it's really annoying.
To produce this issue on your system open terminal inside of VS Code and there you won't see the directory labelled until you press enter or it might even show up but then disappear after any command you type in and press enter.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (4.18GB free)|
|Process Argv|C:\Users\rohan\Desktop\Golo.go|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
php-debug|fel|1.12.6
php-intellisense|fel|2.3.5
php-pack|fel|1.0.2
python|ms-|2018.9.1
cpptools|ms-|0.19.0
Go|ms-|0.6.93

</details>

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/57803
