### ISSUE TITLE
Windows: terminal scrolls to the bottom when opened

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#61806]
- VSCode Version: Version: 1.29.0-insider (user setup) (4a29bd3731e40c07622bae0e9b0ac3b422b5672a)
- OS Version: Windows 10 (October 2018 update)

Steps to Reproduce:

1. Open a new terminal

Notice how the scrollbar is positionned at the bottom, and the blinking cursor isn't visible. Also, see what happens when I start typing:

![vscodeterminal](https://user-images.githubusercontent.com/199648/47512450-86911700-d87c-11e8-9a62-effabc5c9da8.gif)

Does this issue occur when all extensions are disabled?: Yes

**note** There is no such problems with the cmd.exe prompt.

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/57803
