### ISSUE TITLE
Failure to move file to trash

### ISSUE THREAD

**Issue by atombender** [Microsoft/vscode#61810]
- VSCode Version: 1.28.2
- OS Version: macOS 10.14 

Steps to Reproduce:

1. Delete file in the Explorer

Dialog box says it can't be moved to the trash. No explanation given. Nothing in the devtools console.

![screen shot 2018-10-25 at 11 58 28](https://user-images.githubusercontent.com/50314/47514183-bffe5e00-d84d-11e8-88c2-69c6b8236324.jpg)

Does this issue occur when all extensions are disabled?: Yes

**Comment by atombender** [comment]
Different issue.

**Comment by isidorn** [comment]
@atombender so you would expect the error message to be shown in the dialog somewhere? Wouldn't it make it too crowded?
Or you would just like to see it in the debug console, which does not really make sense from the user standpoint?

@bpasero I see that we deliberelty not show the message [here](https://github.com/Microsoft/vscode/blob/5d68db08cda5accef740c69541178911b865d069/src/vs/workbench/parts/files/electron-browser/fileActions.ts#L671) when the trash is used. I guess the original decision was to not make the dialog overcrowded?

**Comment by bpasero** [comment]
@isidorn we are literally not getting any error from Electron when calling `shell.moveItemToTrash()`, check their docs: https://github.com/electron/electron/blob/2-0-x/docs/api/shell.md#shellmoveitemtotrashfullpath

**Comment by isidorn** [comment]
@bpasero thanks for the nice pointer.
Thus we can not do anything here
@atombender if you would like this please first file a feature request against electron that they return an message when a move to trash fails

**Comment by atombender** [comment]
Also, how do we find the cause of Electron's refusal to move files to trash, given that no error is emitted anywhere? This used to work for me. Deleting in Finder works fine. Permissions are correct.

**Comment by hanandjun** [comment]
@atombender I also encountered the same problem, but my environment is as follows:

![20181104210309](https://user-images.githubusercontent.com/17228526/47964461-74ca2380-e075-11e8-8e83-0bfde26535e8.png)
