### ISSUE TITLE
Duplicate entries in the Window menu on macOS

### ISSUE THREAD

**Issue by komealy** [Microsoft/vscode#61812]
Issue Type: <b>Bug</b>

I am using native tabs and noticed that there are two "New Tab" entries, as well as all the other tab/window options being duplicated.

This is not the case when the following line in my `settings.json` is commented out.

```
  // "window.nativeTabs": true,
```

Screenshot of issue when `nativeTabs` is true:

![image](https://user-images.githubusercontent.com/3846175/47517677-d3093200-d83d-11e8-8b03-2e5431da89ff.png)

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
chef|Pen|0.7.0
unique-lines|bib|1.0.0
pgformatter|bra|1.5.1
shell-format|fox|1.1.3
gc-excelviewer|Gra|2.1.26
python|ms-|2018.9.1
vscode-docker|Pet|0.3.1
simple-ruby-erb|vor|0.2.1
HCL|who|0.0.5
change-case|wma|1.0.0
markdown-all-in-one|yzh|1.6.2

</details>

**Comment by agurodriguez** [comment]
It was addressed on https://github.com/Microsoft/vscode/pull/59793. 

I think it will be available in November's release

**Comment by komealy** [comment]
Cool, I'll verify when that comes out. Thanks!

**Comment by komealy** [comment]
This issue duplicates #57421
