### ISSUE TITLE
limited number of supported linux terminals 

### ISSUE THREAD

**Issue by YousefSaber** [Microsoft/vscode#61817]
VSCode only supports very limited number of terminals ( GNOME and another one which I don't remember ) 
I use elementary OS which doesn't support GNOME terminal it's a shame that VSCode can't run on my linux distro and most linux distro 

please address this issue in the future or design your own terminal for VSCode for linux find a solution to this problem

**Comment by weinand** [comment]
VS Code has a built-in integrated terminal.
Where are you using an external terminal?

**Comment by YousefSaber** [comment]
@weinand well in C++ files the integrated terminal doesn't work I'm using VSCode on elementary OS 

![image](https://user-images.githubusercontent.com/33742499/47543666-aa3b7800-d8e3-11e8-9daf-fce2f1ed5d56.png)


![image](https://user-images.githubusercontent.com/33742499/47543683-c3dcbf80-d8e3-11e8-91ce-7fe3067f9aee.png)

I'll file this issue in C++ extensions but it's something to notice

**Comment by weinand** [comment]
This is an issue with the C++ extension, not with VS Code.
