### ISSUE TITLE
Debbuger Run to Line

### ISSUE THREAD

**Issue by vanossj** [Microsoft/vscode#61814]
# Overview:
When debugging, right click a line (in the gutter, maybe editor too), select a menu option "Run to Line"

## Behaviour:
Effectively creates a temporary breakpoint at the line and continues the debug program. The next time the debugger pauses, the created temporary breakpoint is removed (maybe its at that point, maybe it hit another breakpoint first)

**Comment by isidorn** [comment]
Already exists

<img width="458" alt="screen shot 2018-10-26 at 09 53 08" src="https://user-images.githubusercontent.com/1926584/47552420-f5b24e00-d904-11e8-9b61-e97d029b11e9.png">
