### ISSUE TITLE
Problemas de busca em arquivos .less

### ISSUE THREAD

**Issue by claudio-webcis** [Microsoft/vscode#61813]
As vezes ao buscar uma classe ele não encontra o código em arquivos .less.

Ex. Usando a busca geral Ctrl + Shift + F e digitando  ".content" que é uma classe de .less o visual studio acha a classe no arquivo .css mas não acha no arquivo em .less que está na mesma pasta do projeto.

**Comment by weinand** [comment]
Please use English for reporting issues and follow our issue reporting guideline:
https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#reporting-issues.
