### ISSUE TITLE
Add docs for running extension tests on Azure Pipelines

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode#61818]
[We](https://github.com/Microsoft/vscode-azurefunctions) are planning to move over from travis ci to Azure Pipelines, but the existing docs only have instructions for travis ci:
https://code.visualstudio.com/docs/extensions/testing-extensions#_running-tests-automatically-on-travis-ci-build-machines

Can you add an example file for Azure Pipelines? Will the same 'xvfb' stuff work? Currently using the "Hosted Ubuntu 1604" pool, but open to suggestions.

**Comment by bpasero** [comment]
@EricJizbaMSFT can you open this here: https://github.com/Microsoft/vscode-docs
