### ISSUE TITLE
onDidChangeActiveTextEditor getting fired with "plaintext" document when opening new file

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#61825]
Steps to Reproduce:

1. In a repo with 3 markdown files.
2. Make sure all files are closed and then restart vscode
3. Open the first markdown file and open the preview to the side
4. With the markdown editor focused,  click on one of the other markdown files in the explorer

**Bug**
Markdown preview does not update to show the preview of the new document.

The root cause is that `onDidChangeActiveTextEditor` is fired with a `editor.document.languageId` that is set to `plaintext` instead of `markdown`

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Could be a timing promise conversion issue. Not sure who the right owner is here but I'm did some initial investigation. Here's what I believe is going wrong:

1. Starting in `ModelServiceImpl.createModel`
1. This method calls `setMode` which  invokes `.then` on the `mode` promise. This block is not evaluated yet.
1. We next continue on with `createModel` which calls into `MainThreadDocumentsAndEditors`. This code sends the document delta to the extesion host with the incorrect `plaintext` document mode.
1. At some later point, the `.then` block from `setMode` is then evaluated and we update the document to have the correct `markdown` mode

**Comment by rebornix** [comment]
This is not good. Every time when a file is opened, we will warm up the tokens first before displaying, which is a sync task. So what happens now is 

* Tokenize up to 50ms with plaintext
* Language update kicks in
* All tokens are thrown away

**Comment by bpasero** [comment]
Yeah could be likely a Promise/TPromise conversion regression.

**Comment by alexandrudima** [comment]
Definitely caused by the asynchronous `then`, thank you for the analysis @mjbvz. Since I converted the `IModeService` to use native promises, I will look into addressing the issue.
