### ISSUE TITLE
Cannot delete node_modules/@types

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#61829]
Windows 10

I've seen a few times over the past few days that something is locking `node_modules/@types` so I cannot delete node_modules. It may only have happened on the Electron 3 build as I've been dogfooding that.

**Comment by Tyriar** [comment]
This is still an issue, every time I want to start fresh on a workspace I'm forced to reload the window.

**Comment by konpikwastaken** [comment]
+1

**Comment by mjbvz** [comment]
I confirmed that TS server is locking this file. Tracked upstream by https://github.com/Microsoft/TypeScript/issues/29407

I've marked it as a priority to be fixed on the TS time
