### ISSUE TITLE
Folder to terminal mapping

### ISSUE THREAD

**Issue by Punith13** [Microsoft/vscode#61826]
I would like to have the folder to terminal mapping as it would help in switching across projects/folder easily inside a workspace. It is quite cumbersome to switch between open tabs or use split terminal feature. The feature should work in a way as such, clicking on the parent folder or the folder from which the terminal was invoked within the explorer menu , it toggles the corresponding terminal.

**Comment by Tyriar** [comment]
Unfortunately this sort of thing is quite difficult to achieve as vscode has no idea what is actually running inside the terminal, and the only way to change the cwd is to send "cd blah" (which could be sent to some program running within the shell).
