### ISSUE TITLE
Purpose of shortcut Ctrl+Shift+L

### ISSUE THREAD

**Issue by ryangugcloudca** [Microsoft/vscode#61822]
Issue Type: <b>Bug</b>

In the Interactive Editor Play Ground the shortcut  Ctrl+Shift+L has two different purposes: Delete a line and Create cursors on all occurrences of a string. 

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.6.1
vscode-npm-script|eg2|0.3.5
beautify|Hoo|1.4.7
python|ms-|2018.9.1
csharp|ms-|1.16.2
vs-keybindings|ms-|0.2.0
debugger-for-chrome|msj|4.10.2
vscode-docker|Pet|0.3.1

</details>

**Comment by alexandrudima** [comment]
That is not the case with the default settings, so I believe this might be some sort of conflict introduced by the `vs-keybindings` extension.

**Comment by ryangugcloudca** [comment]
Thank you Alex. 
It is from the document "Editor Play Ground" link in VSCode Welcome page. You may find it in first and last lines in the following screenshot.

![image](https://user-images.githubusercontent.com/29901320/47679067-adf82480-db99-11e8-9d83-a83b36a9b029.png)

**Comment by rebornix** [comment]
In the playground, we use display keybindings which are taking effect, but not necessarily the builtin one. If you have Visual Studio Keymap installed, Ctrl+Shift+L will be used to delete the entire line as that's a VS keybinding. That's why you see that in the playground.
