### ISSUE TITLE
Autocomplete is helpful while entering path of files

### ISSUE THREAD

**Issue by greybax** [Microsoft/vscode#6183]
- VSCode Version: 1.0.0
- OS Version: Windows 10

Steps to Reproduce:
1. Start to enter path of files. f.e `"import {Data} from "../../"`
2. Couldn't recognize which files/folders contains in this path.

Expected:
Would be helpful to show in dropdown all files/folders which contains in current matched directory

**Comment by greybax** [comment]
Now we have [Path Intellisense](https://marketplace.visualstudio.com/items?itemName=christian-kohler.path-intellisense) plugin for that. But I'm still not sure that this job is for plugin.

**Comment by mjbvz** [comment]
This feature was added in VSCode 1.8 for both paths and module names. If you notice any issues with it in the latest release, please open a new issue
