### ISSUE TITLE
Quick opening a file with specific line/character numbers doesn't trim trailing whitespace

### ISSUE THREAD

**Issue by varkor** [Microsoft/vscode#61831]
Steps to reproduce:
1. Press ⌘P (or equivalent) to open the quick open panel.
2. Type a file name _with a line (and optionally column)_.
![image](https://user-images.githubusercontent.com/3943692/47535590-169e8300-d8b4-11e8-8894-3959c4486b36.png)
3. Press space.
There will be no results.
![image](https://user-images.githubusercontent.com/3943692/47535599-1d2cfa80-d8b4-11e8-80c3-3e5b3e431951.png)
Note that leading spaces are trimmed:
![image](https://user-images.githubusercontent.com/3943692/47535604-228a4500-d8b4-11e8-8aa8-dcb3151db69b.png)
Additionally, without the line number, trailing spaces are also trimmed:
![image](https://user-images.githubusercontent.com/3943692/47535610-27e78f80-d8b4-11e8-8227-948147264ea9.png)

I often accidentally copy trailing whitespace and it would be much more convenient if the whitespace was trimmed (it would be more consistent too).

**Comment by WaleedAshraf** [comment]
Hi,
I'm working on the fix for this issue. Will open PR in a few days.

**Comment by chrmarti** [comment]
Unfortunately this caused #62131. Reverting the change since we are short on time for release testing. An updated PR would be welcome. /fyi @WaleedAshraf

**Comment by WaleedAshraf** [comment]
Ops! Sorry.
I didn't know we have "view" keyword. Will open a PR with the updated fix.

**Comment by chrmarti** [comment]
@WaleedAshraf No worries. There are several of these shortcuts (`term`, `task`, and a few more).

**Comment by WaleedAshraf** [comment]
Got it. Will open new PR by this weekend. 👍

**Comment by varkor** [comment]
This was [fixed in October](https://github.com/Microsoft/vscode/pull/62019) and was tagged in 1.33.0, but doesn't yet appear in the release version of VSC. When will this be available?

**Comment by chrmarti** [comment]
@varkor We reverted the change (see discussion above).

**Comment by varkor** [comment]
Oh, I see: I didn't notice that the reversion hadn't been followed up on. @WaleedAshraf: are you still planning to open a follow up, or do you not think you have time to?
