### ISSUE TITLE
"Activating extensions" loops forever and VS Code becomes very slow

### ISSUE THREAD

**Issue by masvl** [Microsoft/vscode#61846]
- VSCode Version: 1.29.0-insider 5d68db08cda5accef740c69541178911b865d069 x64
- OS Version: Ubuntu 18.04.1 LTS

Steps to Reproduce:

1. Open VS Code
2. "Activating extensions" text never finishes and the whole app works very slowly

All extensions seemingly load correctly even though the it says it's still activating.

Does this issue occur when all extensions are disabled?: Yes

**Comment by masvl** [comment]
Does not happen with latest stable 1.28.2 7f3ce96ff4729c91352ae6def877e59c561f4850 x64 . Same extensions and settings.json used.

**Comment by alexandrudima** [comment]
This is a new kind of message which I am not aware of. It came in via https://github.com/Microsoft/vscode/commit/7656226f7a3b155b47a7b981a98d76b88f43ef22

@jrieken forwarding to you, maybe you can share in the standup what the message is for.

**Comment by jrieken** [comment]
It is not a pop up but just a status bar message. I will push a change that hides it after some timeout (5seconds?) but I think the promise should eventually resolve and not hang forever.

**Comment by masvl** [comment]
> 
> 
> @masvl when does this happen? what extensions do you have installed? can you run 'F1 > Show Running Extensions' and share with us what it prints? Also, what does 'Output > Log (Extension Host)' contain?

Immediately on start-up. It doesn't seem like the message is the only thing looping because htop is showing CPU usage around 10%-20% for vs code process (no files opened).
[extension_host.log](https://github.com/Microsoft/vscode/files/2525861/extension_host.log)

![vscode_extensions](https://user-images.githubusercontent.com/44491822/47659688-282aa800-db9e-11e8-94a7-ee941ca8efd1.png)

**Comment by alexandrudima** [comment]
@masvl I suspect the CPU usage to be caused by one of the following extension:

* `Zignd.html-css-class-completion`
* `chenxsan.vscode-standardjs`
* `christian-kohler.path-intellisense`
* `CoenraadS.bracket-pair-colorizer`
* `oderwat.indent-rainbow`
* `pranaygp.vscode-css-peek`
* `streetsidesoftware.code-spell-checker`

You can try disabling some of these until you find the culprit or you can follow the steps [here](https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions) to identify it.

**Comment by masvl** [comment]
> 
> 
> @masvl I suspect the CPU usage to be caused by one of the following extension:
> 
>     * `Zignd.html-css-class-completion`
> 
>     * `chenxsan.vscode-standardjs`
> 
>     * `christian-kohler.path-intellisense`
> 
>     * `CoenraadS.bracket-pair-colorizer`
> 
>     * `oderwat.indent-rainbow`
> 
>     * `pranaygp.vscode-css-peek`
> 
>     * `streetsidesoftware.code-spell-checker`
> 
> 
> You can try disabling some of these until you find the culprit or you can follow the steps [here](https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions) to identify it.

While a badly behaving extension could be the culprit in some cases, this was happening even when starting VS Code with --disable-extensions (as mentioned in the initial post). However, I just launched the latest insiders version and the problem is not active anymore. I don't know if it was fixed in the code or if something else fixed it but this issue can now be closed.

Thank  you for everyone that tried to help!
