### ISSUE TITLE
Support regex group when searching or replaceing

### ISSUE THREAD

**Issue by Silent47** [Microsoft/vscode#61841]
Tip: **"Backreferences are not supported"** in the side search bar

```version
Version: 1.29.0-insider (user setup)
Commit: 4a29bd3731e40c07622bae0e9b0ac3b422b5672a
Date: 2018-10-25T05:48:41.485Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

Regex requirement just like:
`(?P<name>...)...(?P=name)`
`(...)...\id`
`(?!...)`

**Comment by roblourens** [comment]
We don't support named capture groups, but you can use simple backreferences and lookbehind in Insiders if you set `search.usePCRE2`

**Comment by konradw86** [comment]
niedz., 28.10.2018, 19:14 użytkownik Rob Lourens <notifications@github.com>
napisał:

**Comment by weikinhuang** [comment]
@roblourens Negative lookbehind doesn't seem to be working with that flag:

![screen shot 2018-10-30 at 4 44 32 pm](https://user-images.githubusercontent.com/794658/47749257-2840ab80-dc63-11e8-91d1-24654757a18d.png)

According to https://www.pcre.org/current/doc/html/pcre2syntax.html#SEC19, that is the correct syntax for a PCRE2 lookbehind regex

**Comment by roblourens** [comment]
I meant lookahead - you can only use PCRE2 features which are currently supported in JS too. Lookahead but not lookbehind.

**Comment by weikinhuang** [comment]
Looks like lookbehind was shipped in chrome 62, which version of chromium is vscode shipping?

**Comment by weikinhuang** [comment]
Nevermind, I see this tracking issue https://github.com/Microsoft/vscode/issues/52629
