### ISSUE TITLE
Same shortcut key for save and not save.

### ISSUE THREAD

**Issue by chy9002** [Microsoft/vscode#6184]
- VSCode Version: 1.0.0
- OS Version: Windows 10 10586.218

Steps to Reproduce:
1. Create new file
2. Type anything
3. Close visual studio code or file. Below alert will display:
   ![vsc](https://cloud.githubusercontent.com/assets/7344772/15090192/1fee2f80-1450-11e6-8f0d-e38529fc8924.png)

Either save or not save, the shortcut key are same. I don't think it's a good idea.

**Comment by dbaeumer** [comment]
@bpasero I move that back to you. The strings need to have comments about the acceleration keys to use. There is little I can do from a localization point of view. Or am I missing something?

**Comment by bpasero** [comment]
@dbaeumer but I do that: https://github.com/Microsoft/vscode/blob/ben/stacks/src/vs/workbench/parts/files/electron-browser/textFileServices.ts#L186

**Comment by dbaeumer** [comment]
Assigning to @johnliu2016 then

@bpasero thanks for clarification. For the future: translation bugs can be directly assigned to @johnliu2016.

**Comment by johnliu2016** [comment]
@lukaschal Duplicate shortcut keys in [textFileServices.nls.resx.lcl](https://monacotools.visualstudio.com/DefaultCollection/Monaco/_git/MonacoLocalization#path=%2FLocalize%2Fchs%2Fvscode%2Fsrc%2Fvs%2Fworkbench%2Fparts%2Ffiles%2Felectron-browser%2FtextFileServices.nls.resx.lcl&version=GBmaster&_a=contents)

   <Item ItemId=";dontSave" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[Do&amp;&amp;n't Save]]></Val>
          <Tgt Cat="Text" Stat="Loc" Appr="PreApproved" Orig="New">
            <Val><![CDATA[不保存(&amp;&amp;S)]]></Val>
          </Tgt>
        </Str>
        <Disp Icon="Str" />
        <Modified By="ICizkova" DateTime="2016-03-10T16:02:41Z" />
        <Cmts>
          <Cmt Name="Dev"><![CDATA[&amp;&amp; denotes a mnemonic]]></Cmt>
        </Cmts>
      </Item>
      <Item ItemId=";save" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[&amp;&amp;Save]]></Val>
          <Tgt Cat="Text" Stat="Loc" Appr="PreApproved" Orig="New">
            <Val><![CDATA[保存(&amp;&amp;S)]]></Val>
          </Tgt>
        </Str>
        <Disp Icon="Str" />
        <Modified By="ICizkova" DateTime="2016-03-10T16:02:41Z" />
        <Cmts>
          <Cmt Name="Dev"><![CDATA[&amp;&amp; denotes a mnemonic]]></Cmt>
        </Cmts>
      </Item>

**Comment by lukaschal** [comment]
Shortcut moved to "N" according to source.

File: src\vs\workbench\parts\files\electron-browser\textFileServices.nls.resx
ID: src\vs\workbench\parts\files\electron-browser\textFileServices.nls.resx
SRC: Do&amp;&amp;n't Save
TGT: 不保存(&amp;&amp;N)

**Comment by joaomoreno** [comment]
@lukaschal @dbaeumer This is *not* fixed in `master` for either Chinese languages:

- https://github.com/Microsoft/vscode/blob/panel/i18n/cht/src/vs/workbench/parts/files/electron-browser/textFileServices.i18n.json#L12
- https://github.com/Microsoft/vscode/blob/panel/i18n/chs/src/vs/workbench/parts/files/electron-browser/textFileServices.i18n.json#L12

**Comment by dbaeumer** [comment]
@joaomoreno we first need to pull in new translations. May be we don't have them yet. Will keep an eye on it.

**Comment by lukaschal** [comment]
Looks like this change was checked-in to GIT at 5/9/2016

https://monacotools.visualstudio.com/DefaultCollection/Monaco/_git/MonacoLocalization/commit/c53e88fa997dae1d86e1ea4821da136a656e6ead?_a=summary

**Comment by bpasero** [comment]
Is this good?

**Comment by chy9002** [comment]
yes
