### ISSUE TITLE
disable git inline annotations on hover

### ISSUE THREAD

**Issue by monkeydri** [Microsoft/vscode#61845]
I would like to know if it is possible to remove the annotations which appear as comments while hovering on each line :

![screenshot from 2018-10-26 08-48-50](https://user-images.githubusercontent.com/18724661/47549357-14601700-d8fc-11e8-8f89-26a45f716494.png)

Did not have them before last update (vscode 1.28.2).

Could not find a setting for it and googling lead me to settings for gitlens extension which I do not have.

**Comment by weinand** [comment]
What git extensions are you using?

**Comment by monkeydri** [comment]
Arf my bad, disabling [Git History Diff](https://github.com/huizhougit/githd) did the trick.

The command relative to those annotations is `GitHD: View Line History`.
