### ISSUE TITLE
Allow to remap "Open to Side" from quick open

### ISSUE THREAD

**Issue by nwaywood** [microsoft/vscode#61843]
- VSCode Version: 1.28.2
- OS Version: macOS 10.13.4

Steps to Reproduce:

1. Open `Keyboard Shortcuts`
2. Use `Record Keys` to filter list by `ctrl + enter` mappings

Does this issue occur when all extensions are disabled?: Yes

I have managed to figure out that pressing `ctrl + enter` while a file is highlighted in the quick open list opens the highlighted file in a split. I want to remap this functionality to `ctrl + v`, but I don't know the command because as you can see from the screenshot below it doesn't show up as a command.

![image](https://user-images.githubusercontent.com/3773641/47547533-8dce2880-d941-11e8-98a8-f1ae4576bb2f.png)

Note that I have also double checked that none of the commands listed above are the correct one by trying 

```
{
       "key": "ctrl+v",
       "command": "<COMMAND>",
       "when": "inQuickOpen"
}
```

where <COMMAND> is one of the commands from the image above.

**Comment by weinand** [comment]
What you call "opens the highlighted file in a split" is named in VS Code "... open to the side"

**Comment by nwaywood** [comment]
@weinand looks like I didn't explain myself very well, I am submitting a bug, not asking a question.

- When you press `ctrl + enter` in the quickopen list the selected file opens in a split
- Therefore a keybinding must exist to make this happen
- The bug is that this keybinding does not show up in the keybindings list

If this is not a bug and for some reason the keybinding is not supposed to show up in the "Keyboard Shortcuts" list, could you please tell me the actual name of the command so I can create my own keybinding? e.g. something like `workbench.action.openQuickOpenSelectionInSplit`.

I tried searching for "...open to the side" like you suggested but that doesn't reveal the keybinding either (as you can see below)

![image](https://user-images.githubusercontent.com/3773641/47611698-9730cf80-dabe-11e8-9959-00151646b9c5.png)

**Comment by quentm74** [comment]
+1

**Comment by prog666** [comment]
I have same problem, did you find any solution to this?
