### ISSUE TITLE
Option to change color for matching tag and searched word

### ISSUE THREAD

**Issue by Anum1212** [Microsoft/vscode#61844]
the current matching tag color is too dull. plz add the option to set a custom color for matching tag and searched word

**Comment by roblourens** [comment]
To customize the matching tag color, set

```json
"workbench.colorCustomizations": {
    "editor.wordHighlightBackground": "#ff0000"
}
```

Not sure what you are referring to by "searched word" exactly but `"editor.findMatchBackground": "#ff0000"` might help, also see the other find-related color tokens.
