### ISSUE TITLE
When you copy a line without any selection the \n should not be copied

### ISSUE THREAD

**Issue by ddehghan** [microsoft/vscode#61840]
- VSCode Version: 1.28.2
- OS Version: OSX 10.13.6

related bug: https://github.com/Microsoft/vscode/issues/40695

Steps to Reproduce:

1. In the editor put cursor on a line and hit CTRL+C.
2. Now go the place you want paste the content and position the cursor in for example in the middle of two parenthesis.
3. Hit CRTL+V. You would expect the content to be pasted in between your two parenthesis. But it will create a new line on top of where you position the cursor and paste the line there. 

This is the default behavior of IntelliJ and PyCharm and it is really convenient. Copying one line of text generally means only the content of that line no the \n at the end.

Does this issue occur when all extensions are disabled?: Yes. same result without any extensions.

**Comment by alexandrudima** [comment]
Not all editors behave the same in this case. I think perhaps an option could be introduced to tweak the behaviour.

**Comment by yubaoquan** [comment]
@alexdima Any progress on this? I would like an option to disable adding new line on paste. It takes a lot of time to remove the new line after paste.

**Comment by dinko-pehar** [comment]
@yubaoquan Can my [answer](https://stackoverflow.com/a/53795818/9871463) on stack help ?

**Comment by yubaoquan** [comment]
> @yubaoquan Can my [answer](https://stackoverflow.com/a/53795818/9871463) on stack help ?

I've read this answer, but I dont want to remember a new key combination. What's more, it will import more key presses since I copy line a lot during coding. 

Thanks.

**Comment by gkarapeev** [comment]
I am pretty sure that in the past, when I copied a line without selection, then pasted that, then a new line **would** get pasted, but **below** the pasted line. Now for some reason the new line appears above and that's really weird.

E.g.:

1. Copy a line without selection using Cmd + C
2. Place cursor here:

```
111
222 <CURSOR>
333
```

3. Hit Cmd + V

**Expected result:**
```
111
222
<COPIED LINE>
333
```

**Actual result:**
```
111
<COPIED LINE> <--- Why here?!
222
333
```

**Comment by gkarapeev** [comment]
Hi and thank you. Before I vote, can I see a final confirmation of what I'm voting for?

- Am I voting for the pasted content going on the line above my cursor?
- Am I voting for the pasted content going where my cursor currently is?
