### ISSUE TITLE
VSCode bash terminal text turns invisible

### ISSUE THREAD

**Issue by Stylian** [Microsoft/vscode#61858]
On VS Code's bash windows if I run a command that returns a long response like "git log" and interrupt it with double tapping ctrl + C then everything I type is invisible. Bash works as I can type "clear" and get a response for any command but I cannot see my text.

I am currently forced to delete the terminal and insert another one. 

- VSCode Version: 1.28.2
- OS Version: Windows Enterprise 10.0.16299

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
