### ISSUE TITLE
Settings: Filtering for Java settings is not possible

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#61864]
I wanted to change a Java setting. In the settings editor I wanted to filer for 'java'. Since the filter matches for prefixes the settings shows me also JavaScript settings.

**Comment by roblourens** [comment]
A couple things that help:

- Search "java" then click the right extension in the TOC
- Search "java.", then the java settings are on top (the JS settings are still returned by bing, but they appear at the bottom of the list)

Can you think of anything else that would help?
