### ISSUE TITLE
Square brackets can't be typed in round brackets

### ISSUE THREAD

**Issue by splitbrain** [Microsoft/vscode#61868]
- VSCode Version: 1.27.2
- OS Version: ArchLinux

Steps to Reproduce:

1. Create a new text file name `test.txt`
2. Try to type `test([test])`
3. You'll notice that the cursor immediately jumps before the `(` when you try to type the `[`

Does this issue occur when all extensions are disabled?: Yes

I also tried to disable "Auto Closing Brackets" but the behavior stays the same. This is a fresh install with no extensions or additional configurations.

**Comment by weinand** [comment]
I cannot reproduce this:

![screen recording 2018-10-26 at 15 30 55 2018-10-26 15_50_53](https://user-images.githubusercontent.com/1898161/47570701-17c4c400-d937-11e8-8f95-bf24513ce91a.gif)

Are you sure that this occurs even if you have extensions disabled?

**Comment by splitbrain** [comment]
I started it with `code --disable-extensions`. And indeed no extensions are loaded:

![peek 2018-10-26 16-27](https://user-images.githubusercontent.com/86426/47572842-35e0f300-d93c-11e8-9dbd-532a906c5950.gif)

I'm using a German keyboard layout. Maybe that's important? A square bracket is a somewhat awkward `ALT GR-8` combo.

**Comment by splitbrain** [comment]
I just noticed: the cursor jumps back when I press ALT-GR (even before I press the 8 for the bracket).

So my initial description was wrong. Whenever I press ALT-GR my cursor jumps one back, no matter what chars I typed before. Basically ALT-GR behaves like a cursor left key.

**Comment by weinand** [comment]
I'm using a German keyboard too :-)
