### ISSUE TITLE
Not able to find special characters like \n, \r, \t

### ISSUE THREAD

**Issue by nitinbansal1989** [Microsoft/vscode#6186]
- VSCode Version: 1.0.0
- OS Version: Mac OS 10.11.4

Steps to Reproduce:

1. Enter some text in editor with tabs and new lines.
2. Open the find box and check the regular expression button.
3. Type "\n" in the search field.

**Comment by alexandrudima** [comment]
`\t` can be searched for when enabling the regular expression. Let's track the multiline find in #313
