### ISSUE TITLE
SCSS syntax highlightning

### ISSUE THREAD

**Issue by dnemoga** [Microsoft/vscode#61869]
Issue Type: <b>Bug</b>

Can you improve SCSS syntax highlightning? I frequently use nested rules such as
```
grid: {
  auto: {
    rows: auto;
    columns: auto;
  }
}
```
and them look pretty odd. I tried to switch between different color themes, and SCSS is shown badly with any of them.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2794)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.95GB (19.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.10
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.40

</details>

**Comment by usernamehw** [comment]
It doesn't look like a valid scss

```
Error: Invalid CSS after "": expected 1 selector or at-rule, was "grid: {"
        on line 1 of stdin
>> grid: {
   ^
```

**Comment by dnemoga** [comment]
@alexr00, looks like built-in SCSS extension has no support for some modern properties.

![vscode-scss-highlightning](https://user-images.githubusercontent.com/695040/47714281-223bd200-dc45-11e8-8be7-b4596b3e2e65.png)

**Comment by alexr00** [comment]
This issue was moved to atom/language-sass#262
