### ISSUE TITLE
VS Code task terminal is revealed on error despite isBackground=true, presentation.reveal=false, and a defined problemMatcher

### ISSUE THREAD

**Issue by segevfiner** [Microsoft/vscode#61861]
- VSCode Version: 1.28.2
- OS Version: Windows 10.0.17134.345 x64

I encountered this while working on https://github.com/Microsoft/vscode-go. See its [tasks.json](https://github.com/Microsoft/vscode-go/blob/0f873208ce2e2010568581d335574397be631f2e/.vscode/tasks.json).

Steps to Reproduce:
1. Launch a task that is: `isBackground=true`, `presentation.reveal=false`, and has a background problem matcher.
2. Launch the task.
3. Change anything in a way that causes an error to be printed.
4. The tasks terminal shows up.

Does this issue occur when all extensions are disabled?: Yes

**Comment by dbaeumer** [comment]
The correct setting must be `presentation.reveal: "never"`. `false` is not a valid value and should have add a green squiggle in the editor.

Please ping if this doesn't fix your issue.

**Comment by segevfiner** [comment]
@dbaeumer It's not set to false, it's set to `silent`, it's just an error on my part in the issue description.

`silent` is described as only showing the terminal if there is an error executing the task and there is no problem matcher (Described in the auto completion, which I think completes from a JSON schema?). But that's not the behavior I'm seeing. If it's the intended behavior, than that text should be updated to reflect that, otherwise that might be a bug in the implementation of `silent`.

**Comment by alexr00** [comment]
Duplicate of #41671
