### ISSUE TITLE
Drag and Drop text (still) copies it instead of moving

### ISSUE THREAD

**Issue by Elkfoot2** [microsoft/vscode#61867]
I know this is a duplicate of #35453 and #54500, but those were closed and locked because it was considered fixed. I would like to report that the issue still happens.

- VSCode Version: 1.28.2 and 1.29.0-insiders
- OS Version:  Windows 10

Steps to Reproduce:

1. Ctrl F (or Ctrl H as Swazimodo shows in #63139)
2. Esc
3. Select some text
4. Drag it

A work around is to tap the Ctrl key before dragging.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Elkfoot2** [comment]
Any progress on this? It often causes me to accidentally duplicate lines of code which often causes problems that are hard to find. I imagine many other users are similarly afflicted by this bug.

**Comment by Hectate** [comment]
I was about to report this bug also. I had searched also and seen the linked (and closed) bug reports but was still seeing issues in the current version. I was also able to narrow it down to my use of CTRL+F to find just prior to dragging text.
I'll add that if I press and release CTRL before the drag, the behavior is correct. It definitely seems that the Find (and/or Replace) pop-up window is preventing the CTRL state from being cleared when dragging text. Pressing and releasing it gives the window an opportunity to correct this.

**Comment by s-ansa** [comment]
I'm having the same issue. 
- VSCode Version: 1.44.0
- OS Version: Ubuntu 18.04.4 LTS 64-bit

**Comment by Elkfoot2** [comment]
It appears to be fixed in 1.48.0. I can no longer recreate it.

**Comment by rebornix** [comment]
Closing as @Elkfoot2 is not seeing this anymore.
