### ISSUE TITLE
Search never ends

### ISSUE THREAD

**Issue by alexdevero** [Microsoft/vscode#61860]
Issue Type: <b>Bug</b>

Search never ends when I try to search in all files. It is also not possible to cancel search. The only solution is re-open VS Code.

Steps:
1. Open search panel
2. Search for anything

Screen:
![search bug](https://user-images.githubusercontent.com/4237724/47558373-403ac700-d913-11e8-9c63-053e72a316de.PNG)

VS Code version: Code - Insiders 1.29.0-insider (5d68db08cda5accef740c69541178911b865d069, 2018-10-26T05:19:44.837Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (8.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.2
vscode-color|ans|0.4.5
color-info|bie|0.5.0
bracket-pair-colorizer|Coe|1.0.60
vscode-svgviewer|css|1.4.7
EditorConfig|Edi|0.12.5
auto-close-tag|for|0.5.6
vscode-styled-components|jpo|0.0.23
wordcounter|kir|1.4.0
contextualduplicate|laf|0.2.0
vscode-language-babel|mgm|0.0.21
postcss-language|mhm|2.1.0
dotenv|mik|1.0.1
vscode-csscomb|mrm|5.2.2
vscode-duplicate|mrm|1.2.1
material-icon-theme|PKi|3.6.0
vscode-icons|rob|7.27.0
stylelint|shi|0.44.0
code-spell-checker|str|1.6.10
code-spell-checker-czech|str|0.1.0
change-case|wma|1.0.0
dictionary-completion|yzh|0.7.0

(1 theme extensions excluded)

</details>

**Comment by zplan** [comment]
Same issue here. Please fix.

**Comment by masvl** [comment]
Same here

**Comment by massimonewsuk** [comment]
I'm experiencing the same issue too

**Comment by sadesyllas** [comment]
I did this **only** with the **Insiders** build.

A **very(!!)** bad bash one liner fix (worth of getting slapped for :smile: ), yet that worked for me, until this is properly fixed:

```shell
pushd /usr/share/code-insiders/resources/app/out/vs/workbench && \
  sudo cp workbench.main.js workbench.main.js2 && \
  sudo sed -i -E 's|throw new Error\("A Match can only be built from a single search result"\);|{if(Array.isArray(t.ranges)){t.ranges=t.ranges[0]\}if(Array.isArray(t.preview.matches)){t.preview.matches=t.preview.matches[0]\}/*throw new Error("A Match can only be built from a single search result");*/\}|' workbench.main.js && \
  popd
```

Oh you will also get a `Your Code - Insiders installation appears to be corrupt. Please reinstall.` message on startup but that's expected.

**Comment by alexdevero** [comment]
Great work guys! Search in the latest update seems to be working properly.

Version: 1.29.0-insider (system setup)
Commit: 4a29bd3731e40c07622bae0e9b0ac3b422b5672a
Date: 2018-10-25T05:48:41.485Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
