### ISSUE TITLE
follow import link detection breaking

### ISSUE THREAD

**Issue by Guema** [Microsoft/vscode#61866]
Follow link (Ctrl + click) layout and link destination itself sometimes break up when changing imports.

![2018-10-26 12_04_25-admin_users js - sim2b-editor - visual studio code administrator](https://user-images.githubusercontent.com/8943532/47560481-9d854700-d918-11e8-8c4c-f7702d7bbbe3.png)
![2018-10-26 11_59_34-greenshot](https://user-images.githubusercontent.com/8943532/47560484-9fe7a100-d918-11e8-9344-96c032ceec59.png)
![2018-10-26 11_59_07-greenshot](https://user-images.githubusercontent.com/8943532/47560488-a1b16480-d918-11e8-933b-790b01c05a4f.png)

As you can see, colors for unused imports are also broken.

- VSCode Version: 1.28.2
- OS Version: win 7 x64

Steps to Reproduce:

i was not able to exactly reproduce reliably, it's quite random but i can precise some informations.
- coding a Meteor 1.8 app
- using blaze
- importing meteor packages/templates/node_modules/html files

=> the layout sometimes break when removing/changing imports, but it's quite random

Does this issue occur when all extensions are disabled?: Yes, but reloading the window correct the issue temporary.

ill add a ts server log when it occur again

**Comment by mjbvz** [comment]
Please let share the TS Server log if you are able to reproduce this

**Comment by Guema** [comment]
Thank you for your attention about this.
I didn't forget this issue because I was not able to reproduce it until now.
Seems it is really specific and multi-factorial.
Ill keep an eye on it and give you the log as early as it append again.

**Comment by Guema** [comment]
Was able to reproduce it

![image](https://user-images.githubusercontent.com/8943532/47801962-93f04a80-dd2f-11e8-884f-103587c70b58.png)

Here is the svn log. As you will see, one of the errors seams to get TsServer unable to work and will still enforcing until reload.

[See PasteBin link for logs](https://pastebin.com/raw/26dABQ9F)

**Comment by mjbvz** [comment]
Thanks. Based on the callstack this looks like https://github.com/Microsoft/TypeScript/issues/27880

Can you please try upgrading your workspace to use `typescript@next` by following [these instructions](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions) to see if that resolves the issue

**Comment by Guema** [comment]
Since i passed to TS dev version, i could not reproduce it. Even if i have got some unrelated other little bugs about how Vscode and TS 3.2 interact (as Vscode is designed around 3.1.6)

Ill wait for @andy-ms linked bug to be fixed then i will close it.

Thanks for your attention
