### ISSUE TITLE
Integrated Terminal hangs on VS Code launch if previously open

### ISSUE THREAD

**Issue by ThomasMichon** [Microsoft/vscode#61873]
If the VS Code terminal is left open when VS Code is closed, the next time VS Code is opened the terminal will fail to reach an interactive state, and must be restarted to proceed.

- VSCode Version: 1.28.2 (system setup)
- OS Version: Windows 10 Enterprise 1809 17763.55

Steps to Reproduce:

1. With CS Code open, launch the integrated Powershell terminal. Once it loads, make sure it remains open and docked.
2. Close VS Code
3. Launch VS Code again.
4. The terminal should still be open, but it will fail to load fully and will not reach an interactive state.
5. Shut down the terminal.
6. Re-open the terminal pane.
7. A new terminal will launch, and this time will reach an interactive state.

![10 26 vs code terminal hang on first load](https://user-images.githubusercontent.com/6828233/47570838-f985a680-d8eb-11e8-91d1-08691658df66.gif)

This appears to be a recent regression. The build from about two weeks ago (public release track) did not have this issue.

Does this issue occur when all extensions are disabled?: Yes

**Comment by VaibhavAcharya** [comment]
I reproduced the steps just as said but everything is working fine on my machine. Try on another machine.

**Comment by ThomasMichon** [comment]
@VaibhavAcharya I was able to make it work on another machine. However, removing all PowerShell extensions from my profile and loading without VS Code extensions still does not make it work on my impacted machine. Any ideas why it would reliably fail-and-then-work on each fresh VS Code window load?

**Comment by VaibhavAcharya** [comment]
@ThomasMichon Can you give list of extensions you are using and more detail about your workspace?

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/57803
