### ISSUE TITLE
Code 1.28 won't start with CentOS 7 [linux]

### ISSUE THREAD

**Issue by ewantowie** [microsoft/vscode#61876]
- VSCode Version: 1.28.2
- OS Version: CentOS 7  (3.10.0-514.6.1.el7.x86_64)

Steps to Reproduce:

1. Try to start code at terminal
2. Get following error message:
./VSCode-linux-x64_1.28.2/code: symbol lookup error: ./VSCode-linux-x64_1.28.2/code: undefined symbol: gtk_widget_get_scale_factor

Can run 1.25.1 no problem, but tried both 1.27 and 1.28 and I get the above error. Can't seem to see any missing dependencies, so a bit lost as to how to resolve this locally.

Checking ldd for code, I get:
	linux-vdso.so.1 =>  (0x00007ffc9374e000)
	libnode.so => /remote/gb12tcad3/ewan-nis/Apps/VSCode-linux-x64_1.28.2/libnode.so (0x00002ab32d6e2000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00002ab32e9b7000)
	libgtk-3.so.0 => /lib64/libgtk-3.so.0 (0x00002ab32ebd3000)
	libgdk-3.so.0 => /lib64/libgdk-3.so.0 (0x00002ab32f2b0000)
	libpangocairo-1.0.so.0 => /lib64/libpangocairo-1.0.so.0 (0x00002ab32f537000)
	libpango-1.0.so.0 => /lib64/libpango-1.0.so.0 (0x00002ab32f744000)
	libatk-1.0.so.0 => /lib64/libatk-1.0.so.0 (0x00002ab32f98e000)
	libcairo.so.2 => /lib64/libcairo.so.2 (0x00002ab32fbb1000)
	libgdk_pixbuf-2.0.so.0 => /lib64/libgdk_pixbuf-2.0.so.0 (0x00002ab32fed4000)
	libgio-2.0.so.0 => /lib64/libgio-2.0.so.0 (0x00002ab3300f7000)
	libgobject-2.0.so.0 => /lib64/libgobject-2.0.so.0 (0x00002ab33048b000)
	libdbus-1.so.3 => /lib64/libdbus-1.so.3 (0x00002ab3306db000)
	libX11-xcb.so.1 => /lib64/libX11-xcb.so.1 (0x00002ab330923000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00002ab330b25000)
	libXi.so.6 => /lib64/libXi.so.6 (0x00002ab330d46000)
	libXcursor.so.1 => /lib64/libXcursor.so.1 (0x00002ab330f56000)
	libXdamage.so.1 => /lib64/libXdamage.so.1 (0x00002ab331161000)
	libXrandr.so.2 => /lib64/libXrandr.so.2 (0x00002ab331364000)
	libXcomposite.so.1 => /lib64/libXcomposite.so.1 (0x00002ab33156e000)
	libXext.so.6 => /lib64/libXext.so.6 (0x00002ab331771000)
	libXfixes.so.3 => /lib64/libXfixes.so.3 (0x00002ab331983000)
	libXrender.so.1 => /lib64/libXrender.so.1 (0x00002ab331b89000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00002ab331d93000)
	libXtst.so.6 => /lib64/libXtst.so.6 (0x00002ab3320d1000)
	libXss.so.1 => /lib64/libXss.so.1 (0x00002ab3322d7000)
	libgconf-2.so.4 => /lib64/libgconf-2.so.4 (0x00002ab3324db000)
	libgmodule-2.0.so.0 => /lib64/libgmodule-2.0.so.0 (0x00002ab33270c000)
	libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00002ab332910000)
	libnss3.so => /lib64/libnss3.so (0x00002ab332c22000)
	libnssutil3.so => /lib64/libnssutil3.so (0x00002ab332f4c000)
	libsmime3.so => /lib64/libsmime3.so (0x00002ab333179000)
	libnspr4.so => /lib64/libnspr4.so (0x00002ab3333a0000)
	libffmpeg.so => /remote/gb12tcad3/ewan-nis/Apps/VSCode-linux-x64_1.28.2/libffmpeg.so (0x00002ab3335de000)
	libasound.so.2 => /lib64/libasound.so.2 (0x00002ab3337c1000)
	libcups.so.2 => /lib64/libcups.so.2 (0x00002ab333aaa000)
	librt.so.1 => /lib64/librt.so.1 (0x00002ab333d13000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00002ab333f1b000)
	libfontconfig.so.1 => /lib64/libfontconfig.so.1 (0x00002ab33411f000)
	libexpat.so.1 => /lib64/libexpat.so.1 (0x00002ab33435b000)
	libstdc++.so.6 => /depot/gcc-5.2.0/lib64/libstdc++.so.6 (0x00002ab334585000)
	libm.so.6 => /lib64/libm.so.6 (0x00002ab3348ff000)
	libgcc_s.so.1 => /depot/gcc-5.2.0/lib64/libgcc_s.so.1 (0x00002ab334c01000)
	libc.so.6 => /lib64/libc.so.6 (0x00002ab334e17000)
	/lib64/ld-linux-x86-64.so.2 (0x00002ab32d4be000)
	libcairo-gobject.so.2 => /lib64/libcairo-gobject.so.2 (0x00002ab3351da000)
	libatk-bridge-2.0.so.0 => /lib64/libatk-bridge-2.0.so.0 (0x00002ab3353e3000)
	libpangoft2-1.0.so.0 => /lib64/libpangoft2-1.0.so.0 (0x00002ab33560e000)
	libXinerama.so.1 => /lib64/libXinerama.so.1 (0x00002ab335823000)
	libgthread-2.0.so.0 => /lib64/libgthread-2.0.so.0 (0x00002ab335a26000)
	libharfbuzz.so.0 => /lib64/libharfbuzz.so.0 (0x00002ab335c28000)
	libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00002ab335e7b000)
	libpixman-1.so.0 => /lib64/libpixman-1.so.0 (0x00002ab336121000)
	libEGL.so.1 => /lib64/libEGL.so.1 (0x00002ab3363ce000)
	libpng15.so.15 => /lib64/libpng15.so.15 (0x00002ab3365ed000)
	libxcb-shm.so.0 => /lib64/libxcb-shm.so.0 (0x00002ab336818000)
	libxcb-render.so.0 => /lib64/libxcb-render.so.0 (0x00002ab336a1b000)
	libz.so.1 => /lib64/libz.so.1 (0x00002ab336c25000)
	libGL.so.1 => /lib64/libGL.so.1 (0x00002ab336e3b000)
	libffi.so.6 => /lib64/libffi.so.6 (0x00002ab3370a6000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00002ab3372ae000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00002ab33750f000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00002ab337736000)
	libmount.so.1 => /lib64/libmount.so.1 (0x00002ab337950000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00002ab337b8f000)
	libdbus-glib-1.so.2 => /lib64/libdbus-glib-1.so.2 (0x00002ab337d93000)
	libplc4.so => /lib64/libplc4.so (0x00002ab337fbb000)
	libplds4.so => /lib64/libplds4.so (0x00002ab3381c0000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00002ab3383c4000)
	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00002ab338610000)
	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00002ab3388f3000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00002ab338b25000)
	libssl.so.10 => /lib64/libssl.so.10 (0x00002ab338d29000)
	libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00002ab338f9b000)
	libavahi-common.so.3 => /lib64/libavahi-common.so.3 (0x00002ab3393fc000)
	libavahi-client.so.3 => /lib64/libavahi-client.so.3 (0x00002ab339609000)
	libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00002ab33981a000)
	libatspi.so.0 => /lib64/libatspi.so.0 (0x00002ab339a51000)
	libgraphite2.so.3 => /lib64/libgraphite2.so.3 (0x00002ab339c78000)
	libxcb-dri2.so.0 => /lib64/libxcb-dri2.so.0 (0x00002ab339e94000)
	libxcb-xfixes.so.0 => /lib64/libxcb-xfixes.so.0 (0x00002ab33a099000)
	libxcb-shape.so.0 => /lib64/libxcb-shape.so.0 (0x00002ab33a2a0000)
	libgbm.so.1 => /lib64/libgbm.so.1 (0x00002ab33a4a4000)
	libglapi.so.0 => /lib64/libglapi.so.0 (0x00002ab33a6ab000)
	libdrm.so.2 => /lib64/libdrm.so.2 (0x00002ab33a8d5000)
	libxcb-glx.so.0 => /lib64/libxcb-glx.so.0 (0x00002ab33aae1000)
	libXxf86vm.so.1 => /lib64/libXxf86vm.so.1 (0x00002ab33acfb000)
	libblkid.so.1 => /lib64/libblkid.so.1 (0x00002ab33af01000)
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00002ab33b13d000)
	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00002ab33b342000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00002ab33b551000)
	libfreebl3.so => /lib64/libfreebl3.so (0x00002ab33b755000)

Does this issue occur when all extensions are disabled?: Yes

**Comment by ewantowie** [comment]
Ok, just checked 1.26.1 and it also has this issue. 

So, there is some dependency change between 1.25 and 1.26 which must be causing this issue.

**Comment by ewantowie** [comment]
Reading through the release notes, I spotted in 1.26 (July release) that:
"In this release, we updated from Electron 1.7.12 to 2.0.5. This brings in a Chromium update from version 58 to 61 and Node.js from 7.9 to 8.9."

I am guessing that something in here is likely to have caused the issue, any ideas on how to resolve?

**Comment by ewantowie** [comment]
This has been a while, is there anyone looking into this issue?

**Comment by ewantowie** [comment]
Perhaps there is something I can test to verify?

**Comment by Tyriar** [comment]
Looks like this is related to the move to GTK3 as I think we (Chromium) actually depends on 3.10 and CentOS ships with 3.8. I'm not sure you can update gtk3 independently just for VS Code?

**Comment by ewantowie** [comment]
Ok, thanks for the update. Just looking into whether we can install GTK3 locally and set LD_LIBRARY_PATH just for VS Code. At first attempt, the rpm for libgtk3 doesn't let us relocate on install. Let me try a few things and I will update when I have some more info.

Due to our development environment, we have to stay within preset images for our linux installs to ensure proper compatibility of everything we develop. It's a pita, and it often throws up issues like I am encountering here.

Checking the 'base' repo for CentOS7 and libgtk3 is currently at revision 3.22, so this may be an issue for people/systems like we have and not an issue with CentOS7 compatibility.

**Comment by qwertie** [comment]
I can't run VSCode in CentOS 7.2, but the error message is different:

    $ /usr/share/code/code
    [19252:0104/153150.614949:FATAL:nss_util.cc(632)] NSS_VersionCheck("3.26") failed. NSS >= 3.26 is required. Please upgrade to the latest NSS, and if you still get this error, contact your distribution maintainer.
    Aborted (core dumped)

Rumor has it that I'm [not supposed to even attempt to upgrade NSS](https://centos.org/forums/viewtopic.php?t=57349).

I saw a suggestion elsewhere to try [VS Code version 1.25](https://code.visualstudio.com/updates/v1_25). After removing the current version with `sudo yum remove code`, the version 1.25 started okay :+1:

**Comment by ewantowie** [comment]
Just to update this issue, it is most definitely not possible to 'install' gtk3 to a different location.

As mentioned above, version 1.25 is pretty stable for us and works.
