### ISSUE TITLE
Unable to search for ^.*(regex).*$ in full text search until file is opened

### ISSUE THREAD

**Issue by MichaelHuyPhan** [Microsoft/vscode#6187]
- VSCode Version: 1.0.0
- OS Version: Win 10 Pro

Steps to Reproduce:
1. close all file are opened in vsc editor
2. close vscode than open it again
3. search for `^.*(regex).*$`
4. no results
5. open an editor that contains `regex`
6. run search again

=> now you find results

**Comment by bpasero** [comment]
I can reproduce.

**Comment by bpasero** [comment]
Looks like in https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/search/node/textSearch.ts#L116 we are getting the new line characters (CR, LF, Bell (?)) and this causes the pattern to not execute because it is not going multiline.

**Comment by bpasero** [comment]
@sandy081 since you are in this area currently, I think this is related to the issues you were talking about where fulltext search is not consistent with editor search.

**Comment by bpasero** [comment]
I cannot reproduce this anymore.
