### ISSUE TITLE
Save All isn't working with custom key bindings

### ISSUE THREAD

**Issue by gordingin** [Microsoft/vscode#61872]
Issue Type: <b>Bug</b>

This was working, not it isn't. I change my binding to use ALT-F ALT-S to save all my files. Pressing that now ONLY saves the current tab I am on.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz (8 x 2794)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|31.91GB (17.08GB free)|
|Process Argv|--folder-uri file:///c%3A/git/MSI.VisaProgram.WebSite/VisaProgram.WebSite/src|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|1.6.1
debugger-for-chrome|msj|4.10.2
autoimport|ste|1.5.3

(1 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
#61038

**Comment by gordingin** [comment]
Why was this closed? #58773 is not my issue.

**Comment by sbatten** [comment]
#61038 seems to be the same issue.

**Comment by gordingin** [comment]
can this be REOPENED. This have nothing to do with SVN. I am trying to save ALL my edited files with ALT+F and ATL+S.

**Comment by gordingin** [comment]
I can confirm this does work in version in version 1.24.0 but 1.28.2 is doesn't.

**Comment by sbatten** [comment]
@gordingin The issue you are experiencing is keybindings conflicting with mnemonics which is the same issue as #61038 … The issue has been fixed in insiders but has not yet been released in stable.
