### ISSUE TITLE
Better project title display

### ISSUE THREAD

**Issue by aakrem** [Microsoft/vscode#61874]
In MacOS and in full screen, the project title is not clear enough, and when we click on different sections (search, debug..) the title is not shown. In case many windows are open finding the one we look for is painful especially if other sections are selected.

I think a better ui will be a good benefit from a user perspective.

<img width="416" alt="screen shot 2018-10-26 at 15 46 13" src="https://user-images.githubusercontent.com/6608260/47572072-632ca180-d93a-11e8-9d36-a9fe1b8dc19c.png">

**Comment by usernamehw** [comment]
It actually shows project title when only 1 folder opened & hidden `openEditors` and `outline`:
![screenshot 90](https://user-images.githubusercontent.com/9638156/47603431-8a47a980-d9f4-11e8-812c-24fdae9869bc.png)

It seems like an improvement if it was shown even with visible `openEditors` and `outline`.

Only that doesn't solve the issue that you want to show it in other sidebar views.

**Comment by isidorn** [comment]
@usernamehw thanks for the pointer, and yes I agree this should be solved using an extension.
