### ISSUE TITLE
Ending double quotes, brackets, etc. should be replaced if typed

### ISSUE THREAD

**Issue by moseleyi** [microsoft/vscode#61878]
Let's say I start typing this line of code:

`$array["`

VSCode will automatically add:

`$array[""]`

now, sometimes it's okay but if I have a lot of code to write after this I still need to press the arrow to the right twice. 

Instead if I type the endings by myself I am left with

`$array[""]"]`

I would like to be able to configure it so that it can be recognised that I closed the tags myself, is it possible?

**Comment by alexandrudima** [comment]
This works fine for me:
![auto-closing](https://user-images.githubusercontent.com/5047891/61864570-f139b680-aed1-11e9-8e1a-8600db6458c8.gif)

**Comment by moseleyi** [comment]
Hmm true now this doesn't appear to be a problem but I swear it used to be :D
