### ISSUE TITLE
Search across project seems to hang and prevents integrated terminal from being used

### ISSUE THREAD

**Issue by johnpapa** [Microsoft/vscode#61875]
Issue Type: <b>Bug</b>

Open a project, CMD+SHIFT+F to search, enter some text

See the attached GIF for details

VS Code version: Code - Insiders 1.29.0-insider (5d68db08cda5accef740c69541178911b865d069, 2018-10-26T05:12:19.765Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz (16 x 3200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|32.00GB (0.24GB free)|
|Process Argv|-psn_0_3797919|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.10
markdown-preview-github-styles|bie|0.1.3
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.20.0
vscode-eslint|dba|1.6.1
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.40
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.6.1
vscode-pull-request-github|Git|0.2.1
Angular1|joh|0.2.0
angular-essentials|joh|0.4.0
Angular2|joh|6.3.0
dotenv|mik|1.0.1
vscode-azureappservice|ms-|0.9.1
vscode-azurefunctions|ms-|0.12.0
vscode-cosmosdb|ms-|0.8.0
azure-account|ms-|0.4.3
azurecli|ms-|0.4.2
vsliveshare|ms-|0.3.869
vsliveshare-audio|ms-|0.1.39
vsliveshare-pack|ms-|0.2.0
debugger-for-chrome|msj|4.10.2
angular2-inline|nat|0.0.17
vetur|oct|0.13.0
vscode-docker|Pet|0.3.1
material-icon-theme|PKi|3.6.0
polacode|pnp|0.2.2
vue-vscode-snippets|sdr|1.3.0
code-settings-sync|Sha|3.2.0

(1 theme extensions excluded)

</details>

![2018-10-26_10-15-16](https://user-images.githubusercontent.com/1202528/47572217-74f55100-d908-11e8-9677-74b2d217a461.gif)

**Comment by roblourens** [comment]
Do you see the same error as in https://github.com/Microsoft/vscode/issues/61860?

**Comment by roblourens** [comment]
We rolled back the previous insiders update, could you check whether this still happens?

**Comment by johnpapa** [comment]
it is NOT happening now. I updated , for the second time, just now. So it looks like i now have your latest.

you can see the version i had in the details above (when the error occurred)
