### ISSUE TITLE
VSCode freezing after certain of time.

### ISSUE THREAD

**Issue by overflowz** [Microsoft/vscode#61871]
Issue Type: <b>Bug</b>

No idea actually how to reproduce it. I'm not turning my computer off and leaving VSCode open there. After few days (even two) it started freezing randomly and I have to restart it to make it work without freezing. I can say, nothing critical here but definitely requires some attention. This started happening after I updated to latest version (major release).

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.95GB (15.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
better-toml|bun|0.3.2
vscode-eslint|dba|1.6.1
gitlens|eam|8.5.6
vscode-npm-script|eg2|0.3.5
vscode-mysql|for|0.3.0
gc-excelviewer|Gra|2.1.26
sftp|lix|1.7.1
code-beautifier|mic|2.1.0
vscode-cosmosdb|ms-|0.8.0
python|ms-|2018.9.1
azure-account|ms-|0.4.3
debugger-for-chrome|msj|4.10.2
vscode-docker|Pet|0.3.1
rust|rus|0.4.10
code-settings-sync|Sha|3.2.0
vscode-lldb|vad|1.0.0
vscode-react-native|vsm|0.6.18
vscode-wakatime|Wak|1.2.3
html-css-class-completion|Zig|1.17.1

</details>

**Comment by overflowz** [comment]
EDIT: to be more exact, it is freezing for like 3-5 seconds and then continues to work, but after first freezing, it repeats in every ~10 seconds or so.

**Comment by ByteArts** [comment]
I started having this problem recently too and the Python linter would just constantly be busy. I discovered that if I turned off 'Autosave', the problem went away.

**Comment by kieferrm** [comment]
@overflowz can you confirm that it's the Python extension in your case as well?

**Comment by overflowz** [comment]
@kieferrm well, I wrote all the extensions I have currently so yeah, I do have but I'm not using python tho ;d

**Comment by lordgreg** [comment]
I have exactly the same issue!

I'm developing Flutter app and it starts freezing after approx 1 hour of usage. When it does start, it continues every 10 seconds or so. I have to reopen VSCode, which means my debugging sessions (Android Emulator) is now disconnected and I have to reconnect vscode to emulator to continue work.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz (8 x 3399)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (3.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.2.0
dart-code|Dar|2.20.0
flutter|Dar|2.20.0
vscode-eslint|dba|1.7.0
githistory|don|0.4.3
tslint|eg2|1.0.40
vsc-material-theme|Equ|2.5.1
prettier-vscode|esb|1.7.1
Angular2|joh|7.0.1
prettify-json|moh|0.0.3
vsliveshare|ms-|0.3.925
quicktype|qui|12.0.46
subtle-brackets|raf|3.0.0
code-settings-sync|Sha|3.2.0
ayu|tea|0.16.0

(2 theme extensions excluded)

</details>

**Comment by overflowz** [comment]
Another thing I noticed is, I'm using only 3 instances of VSCode, but in process list it shows as:
![image](https://user-images.githubusercontent.com/7758774/48315294-b9ae0700-e5ed-11e8-9921-c967f772f6ce.png)

**Comment by jrieken** [comment]
Pretty sure this is https://github.com/Microsoft/vscode/issues/62829. Should be fixed with insiders...

**Comment by overflowz** [comment]
as I said, it's not an easy reproduceable for me, since it takes few days for this result and sorry, I can't use insiders build because I'm on stable one currently.

**Comment by jrieken** [comment]
> since it takes few days for this result and sorry,

That sounds like #62829. We will release stable (1.29) tonight if everything goes as planned. Optimistically closing as dupe

**Comment by overflowz** [comment]
@jrieken I'm not sure if that is duplicate, since you mentioned that only one of your vscode is being freezing, but for me -- all the instances are freezing randomly.
