### ISSUE TITLE
Test: notifications with buttons hide after a timeout

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#61885]
https://github.com/Microsoft/vscode/issues/51013

Complexity: 3

- [x] anyOS @kieferrm 
- [x] anyOS @stevencl 

Notifications that include buttons will now hide after a certain timeout. Previously we would never hide notifications with buttons. There are some exceptions:
* if the notification has severity of error and buttons, we keep showing it
* some selected notifications (like extension recommendations or telemetry opt out) never hide

**Verify:**
* notifications with buttons hide after a timeout unless the severity is error (you can use the notification tester extension: https://marketplace.visualstudio.com/items?itemName=svipben.notification-tester)
* built in notifications like the telemetry opt out or extension recommendation do not hide ever (verify from a fresh user data dir for example)
* if the window is not focused, we keep all notifications with buttons around assuming that the user is not paying attention. verify this by triggering notifications (e.g. from the extension) and moving focus to another window

**Comment by adsingh14** [comment]
@bpasero I've started working on it to hide it after **n** seconds.
