### ISSUE TITLE
Debugger not working as expected

### ISSUE THREAD

**Issue by vekannan** [Microsoft/vscode#61881]
Hi 

I am trying to implement the debugger for my application. The configuration is simple. I am using react. The chrome browser launched with my application but the debugger never comes to the javascript code. If i refresh the page then the debugger comes to that location but i couldn't see any value for the variables it come accross
```
{
"version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceFolder}/src"
        }
    ]
}
```

**Comment by roblourens** [comment]
> If i refresh the page then the debugger comes to that location

Can you set `"trace": true`, run this again (including the refresh) and upload the log?

We try to break on breakpoints in global code, but there are some cases where it won't work, I'm curious which case you are hitting.

> but i couldn't see any value for the variables it come accross

If your code is being transpiled, it may rename variables. We can only show the variables that are in the runtime, not their original names.
