### ISSUE TITLE
Windows explorer Icons

### ISSUE THREAD

**Issue by JuanMejiaVelez** [Microsoft/vscode#61884]
Issue Type: <b>Feature Request</b>

Opening files with Code is wonderful. it is quick and easy, and makes user want to open meny file types with Code. But by doing so, all different file types get the same icon in Windows Explorer, which makes very hard to tell them appart. in a folder where .cs files and .csproj for instance live, all the files have the same icon (the icon of code) this is messy, it should retain the default icon given by visual studio if Code is not going to provide a personalized one, it should have the same icons as visual studio, they are from the same organization.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17763

**Comment by misolori** [comment]
@JuanMejiaVelez can you provide a screenshot as an example?

**Comment by JuanMejiaVelez** [comment]
![snip_20181108104130](https://user-images.githubusercontent.com/13546698/48219992-eb4f7580-e342-11e8-940e-5db23522ae2c.png)

@misolori attaching a screenshot of WIndows Explorer. in here you can can see that the .XAML file has the VS Code file type icon. I had All file types (cs, xml, appxmanifest, csproj, etc) all with the same icon. that creates a messy experience. Visual Studio assigns a different icon to each different file type it supports. I wish Visual Studio Code would do the same, it can simply be associated with VSCode, but keep the Icon in a similar way Visual Studio does.

**Comment by misolori** [comment]
We recently introduced [file icons per file type](https://code.visualstudio.com/updates/v1_28#_file-icons-per-file-type) that will allow you to see different file icons, however we have only added a small list of icons and are updating that list when we see the need for it. Will keep this request in mind.

**Comment by JuanMejiaVelez** [comment]
That's great, although the note of "For small icon sizes, we decided to preserve the VS Code logo as the icon" sort of kills the whole thing for me, as I don't set the views in Source code folders to "Huge Icons" they are always in detail view showing only 16 pixel icons.
