### ISSUE TITLE
I am unable to press "Shift+Alt+A" to toggle a block comment

### ISSUE THREAD

**Issue by swinster** [Microsoft/vscode#6188]
- VSCode Version:1.0.0.
- OS Version:Win 10 Pro build 14322

Steps to Reproduce:
1. Highlight a block of text
2. Press `Shift+Alt+A`. Nothing happens. (however, via the `Ctrl+P` menu and select togel clock comment, as is OK)
3. In the Keybinding,json Shot cuts file, I see:

```
{ "key": "shift+alt+a",           "command": "editor.action.blockComment",
                                     "when": "editorTextFocus" },
```

And nothing is overridden in my user settings.

**Comment by alexandrudima** [comment]
@swinster It might be that you have installed some other Windows software that "steals" `Shift+Alt+A`. What appears in the input box when you go through the Define Keybinding widget:

![shift-alt-a](https://cloud.githubusercontent.com/assets/5047891/15105984/5ba9618a-15c6-11e6-9132-de3472569af6.gif)
