### ISSUE TITLE
Test: highlight modified tabs

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#61883]
https://github.com/Microsoft/vscode/issues/26284

Complexity: 2

- [x] anyOS @roblourens 
- [x] anyOS @weinand  (macOS)

A new setting `workbench.editor.highlightModifiedTabs` allows to draw a (themable: `tab.activeModifiedBorder` etc. ) border to the top of tabs whenever they are dirty.

**Verify:**
* no border is drawn unless `workbench.editor.highlightModifiedTabs` is true
* when enabled a border is showing on top of the tab until you save
* even if the theme (or your settings) configure to draw a top border for a tab (via `tab.activeBorderTop`), the modified border will win

**Note:** the border will not show if auto save is enabled after 1s delay.

**Comment by Studio384** [comment]
In today's Insider release (10-29), when enabling or disabling this setting without restarting Visual Studio, the editor will duplicate the tab when editing it.

**Comment by roblourens** [comment]
I don't see that @Studio384, maybe it was already fixed, if not, please open an issue with details.
