### ISSUE TITLE
Image Update is broked

### ISSUE THREAD

**Issue by macOneOone** [Microsoft/vscode#61889]
- VSCode Version:
- OS Version: macOS Mojave

Steps to Reproduce:

1. Open a visual Studio Code
<img width="408" alt="captura de ecra 2018-10-13 as 13 54 24" src="https://user-images.githubusercontent.com/16170629/47579211-3df06100-d943-11e8-9190-d343a2790e52.png">

2. Search for update Vscode button
3. Wait to change the icon and you will see the image below

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
I can't repro that. Does it happen and look the same every time?

**Comment by roblourens** [comment]
And what theme are you using?

**Comment by macOneOone** [comment]
I'm using One Dark Pro

> I can't repro that. Does it happen and look the same every time?

yes it looks the same every time it happen

**Comment by macOneOone** [comment]
> And what theme are you using?

One Dark Pro
