### ISSUE TITLE
Test: simple fullscreen support

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#61880]
https://github.com/Microsoft/vscode/issues/26445

Complexity: 2

- [x] macOS @isidorn 
- [x] macOS @RMacfarlane 

A new setting `window.nativeFullscreen` can now be set to `false` to disable the native macOS fullscreen support and use a custom one instead. The custom one should still do the same thing (bring the window into fullscreen), but will not create a separate space on the desktop (macOS Space).

**Verify:**
* with this setting configured to `false`, everything works as it does with normal fullscreen
* however you cannot bring the menu to fullscreen by using the window controls top right
* you are not getting a separate macOS space created
* entering and leaving fullscreen works without issues
* fullscreen is also restart after a restart if you configure `window.restoreFullscreen`

**Comment by a-eid** [comment]
switching back from fullscreen and the control buttons are gone 

![screen shot 2018-10-29 at 9 06 37 pm 1](https://user-images.githubusercontent.com/19273413/47673900-9ed79d80-dbbe-11e8-92a1-a0313d4ebefe.png)

**Comment by bpasero** [comment]
@a-eid are you using any custom settings, I cannot reproduce that. How did you enter fullscreen?

> also you have to use keyboard shortcuts to switch back from fullscreen.
Or the menu, but yeah the window buttons do not toggle fullscreen because native fullscreen gets disabled with that setting.

**Comment by a-eid** [comment]
I use `command-option` + `f` to toggle fullscreen. 
I don't use any custom settings that might affect that, I will check again.

**Comment by bpasero** [comment]
@a-eid that sounds like the keybinding for switching to native full screen no? Can you try `Ctrl+Cmd+F` instead?

**Comment by isidorn** [comment]
Works nicely, I will actually use this setting in my daily selfhosting

**Comment by a-eid** [comment]
@bpasero  yes I meant `Ctrl + Cmd + F` sorry..

**Comment by a-eid** [comment]
@bpasero yes the new update fixed the issue I had, thank you.
