### ISSUE TITLE
emmet.triggerExpansionOnTab php variables to html tags

### ISSUE THREAD

**Issue by ChazyTheBest** [Microsoft/vscode#6189]
- VSCode Version: 1.1.0-insider
- OS Version: Manjaro 15.12 x64

Steps to Reproduce:

1. Create a variable in php called `$variable`.
2. Then press tab and it'll be replaced by `<1variable></1variable>`.

I don't know if it's a bug but it's not what I was expecting.

**Comment by egamma** [comment]
Emmet is enabled by default in PHP files. You can disable emmet abbreviation expansion on TAB using the following setting: 
```json 
	"emmet.triggerExpansionOnTab": false
```

**Comment by ramya-rao-a** [comment]
@ChazyTheBest 

With the new Emmet improvements in VS Code 1.15, this is no longer a problem

Tab will no longer trigger Emmet, instead Emmet abbreviations will show up in suggestion/auto-completion list.

Please read more on what else is new at [Emmet 2.0](https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0)
