### ISSUE TITLE
workbench.action.terminal.runSelectedText issue with IPython

### ISSUE THREAD

**Issue by louisabraham** [microsoft/vscode#61892]
- VSCode Version: 1.28.2
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. Open an ipython console
2. Select some code block with multiple indented lines
3. Use workbench.action.terminal.runSelectedText

Example:

```python
def f(x):
    x *= 2
    return x
```

Result:

```
In [4]: def f(x):
   ...:         x *= 2
   ...:             return x
  File "<ipython-input-4-110910b1aeaa>", line 3
    return x
    ^
IndentationError: unexpected indent
```

Explanation:

IPython automatically indents when you type return. However, when pasting the whole code block or each line it doesn't. The problem probably comes from the fact than vscode simulates a return key instead of a simple newline when sending the line.

**Comment by louisabraham** [comment]
Another issue arises when trying to execute multiple lines with the same indentation

```python
import math
import os
```
Only the first line is sent.

**Comment by louisabraham** [comment]
@weinand This issue is NOT caused by an extension. I could reproduce with `code --disable-extensions`.

**Comment by JiuShiNewBee** [comment]
Same problem with me, I have to copy and paste manually.

**Comment by Tyriar** [comment]
I believe this is an issue with ipython as it only affects it.

**Comment by louisabraham** [comment]
I would like to reopen this issue.

In vim, the slime plugin has a variable `slime_python_ipython`. If it is set and the current language is python, then it wraps the text with `%cpaste`.
This should be implemented in vscode as well.

**Comment by cbrnr** [comment]
Although this is not caused by the Python extension, maybe the suggested change (using `%cpaste`) should be implemented in the extension - someone already created an issue: https://github.com/Microsoft/vscode-python/issues/2837
