### ISSUE TITLE
Go to Implementation misses implementations in different folders

### ISSUE THREAD

**Issue by jchurch33** [Microsoft/vscode#61890]
I'm working with a large Typescript codebase, and I have noticed this consistent problem with the "go to implementation" command.

When I invoke this command on a class in /workspace_root/a/b/c/parent.ts I can get results for other classes in the same directory, (/workspace_root/a/b/c/child1.ts), but I have other implementing classes in another directory (/workspace_root/a/b/d/child2.ts) that do not appear in the results.

This is puzzling because other commands like "go to definition" or "find all references" don't seem to have this problem.

This seems fixable.

**Comment by mjbvz** [comment]
Are these files all part of the same tsconfig?

Please provide a small example project or  example code that shows how to reproduce

**Comment by jchurch33** [comment]
To the first question: no, it appears they do have distinct tsconfig files. 
Do you still need an example?

**Comment by mjbvz** [comment]
This will only work if they are in the same project. Are you using project references here?
