### ISSUE TITLE
net::ERR_PROXY_CONNECTION_FAILED even though I do not use any proxy and it was working perfectly!

### ISSUE THREAD

**Issue by MohammadJodeh** [Microsoft/vscode#61891]
Version: 1.28.2
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:20:56.183Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

- OS Version: Ubuntu 16.04

Steps to Reproduce:
It keeps saying "net::ERR_PROXY_CONNECTION_FAILED" even though I do not use any proxy !!
I uninstalled completely and removing all the settings and reinstalled it and it is still the same !
the settings file:

{
    "editor.fontSize": 16,
    "editor.formatOnPaste": true,
    "editor.formatOnType": true,
    "http.proxyStrictSSL": false,
    "markdown.preview.fontSize": 16,
    "terminal.integrated.fontSize": 16
}

Does this issue occur when all extensions are disabled?: Yes/No
No

Checked the network tab:
ERR net::ERR_PROXY_CONNECTION_FAILED: {1}
az764295.vo.msecnd.net/experiments/vscode-experiments.json Failed to load resource: net::ERR_PROXY_CONNECTION_FAILED
marketplace.visualstudio.com/_apis/public/gallery/extensionquery Failed to load resource: net::ERR_PROXY_CONNECTION_FAILED
workbench.main.js:sourcemap:5575 Error querying extensions gallery Error
    at XMLHttpRequest.t.xhrRequest.i.TPromise.o.onerror (workbench.main.js:sourcemap:5520)
s @ workbench.main.js:sourcemap:5575
workbench.main.js:sourcemap:2374 net::ERR_PROXY_CONNECTION_FAILED

**Comment by joaomoreno** [comment]
Do you have a `HTTP_PROXY` environment variable set?
