### ISSUE TITLE
titlebar menu items truncated for smaller window size

### ISSUE THREAD

**Issue by zsloane** [Microsoft/vscode#61896]
Issue Type: <b>Bug</b>

When the width goes below the minimum needed to show the (full menu + title + window buttons) the menu is just truncated with no indication (i.e. ellipsis)

![image](https://user-images.githubusercontent.com/10229009/47587744-ea294c00-d931-11e8-8218-22bdf806f660.png)

![image](https://user-images.githubusercontent.com/10229009/47587779-0331fd00-d932-11e8-9081-830aa90d749d.png)

Also, probably related to this... the area of the titlebar exposed by the truncation of the menu is not available as a window drag target
![image](https://user-images.githubusercontent.com/10229009/47587916-70459280-d932-11e8-9a79-5f7c4c61abae.png)

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 6.1.7601

**Comment by sbatten** [comment]
part of #57756
