### ISSUE TITLE
Cannot debug extensions if offline

### ISSUE THREAD

**Issue by aaronpowell** [Microsoft/vscode#619]
If my wifi is offline or my laptop is in flight mode I am unable to launch the VSCode debugger for debugging extensions.

## Steps to repo

1. Clone a repository with an extension (or `yo code`)
2. Restore npm packages
3. Open extension in VS Code
4. Press `F5`

When doing so the following error is displayed:

![vscode-error](https://cloud.githubusercontent.com/assets/434140/11396522/27d92b88-93c6-11e5-85a1-49f039dac7f6.PNG)

I've reproduced it on my machine while network disconnected and while in flight mode. Once wifi connectivity is reestablished it works just fine, I didn't close/open VS Code in between.

## System info

* Windows 10 (latest updates via fast ring)
* VS Code 0.10.1
* Node.js 4.0.0
* npm 3.4.1

**Comment by isidorn** [comment]
@aaronpowell awesome bug description :+1: 
@weinand I believe you already looked into not able to debug while offline, thus assigning to you

**Comment by weinand** [comment]
@aaronpowell you are running into this node.js on Windows bug: node-inspector/node-inspector#645

**Comment by weinand** [comment]
and the problem with the unreadable error message has been fixed for the December release.

**Comment by weinand** [comment]
fixed by PR https://github.com/Microsoft/vscode-node-debug/pull/31
