### ISSUE TITLE
Recommended extensions disappear after installing a couple

### ISSUE THREAD

**Issue by amitkan** [Microsoft/vscode#61904]
Issue Type: <b>Bug</b>

Install a copule recommended extensions - click 'reload'. Once VS Code reloads, I no longer see recommendations

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (17.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.16.2
debugger-for-chrome|msj|4.10.2

</details>

**Comment by weinand** [comment]
Did you install the recommended extensions?

**Comment by amitkan** [comment]
Not all. I got around 7 to 8 recommendations on the first install. I only installed a couple of them. Rest disappeared after the refresh.

**Comment by kieferrm** [comment]
Do you have any recommended extensions, i.e. is the list empty, or did it change? We cycle the recommended extensions, so you'll see different ones over time.

**Comment by amitkan** [comment]
The list is empty

[cid:image003.jpg@01D47500.A94F8E00]

**Comment by ramya-rao-a** [comment]
@amitkan 
- Can you share your settings?
- What do you see when you search for `@recommended` in the extensions view's search box?

**Comment by amitkan** [comment]
Which setting are you looking for in particular? Note that I have not changed any settings myself.

@recommended shows me just one recommendation "Azure Repos 1.144.1"

**Comment by ramya-rao-a** [comment]
> Which setting are you looking for in particular? Note that I have not changed any settings myself.

If you havent changed any, then that is ok.

Some recommendations are based on the project you are working on, they may not appear when you dont have that project open in VS Code.

> I got around 7 to 8 recommendations on the first install.

Do you mean the first time you installed VS Code on your machine?
