### ISSUE TITLE
Losing intellisense abilities

### ISSUE THREAD

**Issue by mahorad** [Microsoft/vscode#61903]
Issue Type: <b>Bug</b>

After a few hours (sometimes minutes) of working with vscode, it suddenly loses all of its intellisense abilites. So the cmd+space only shows 'Loading...' from then on.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 5|
|Memory (System)|16.00GB (3.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (74)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.3.1
jest-snippets|and|1.6.1
vscode-styled-jsx|bla|1.0.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
bracket-pair-colorizer|Coe|1.0.60
vscode-markdownlint|Dav|0.20.0
vscode-eslint|dba|1.6.1
xml|Dot|2.3.2
es7-react-js-snippets|dsz|1.8.7
gitlens|eam|8.5.6
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.40
vscode-npm-script|eg2|0.3.5
vscode-great-icons|emm|2.1.44
prettier-vscode|esb|1.6.1
git-project-manager|fel|1.7.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vscode-indent-on-paste|gaz|2.2.1
vscode-nginx-conf-hint|han|0.1.0
beautify|Hoo|1.4.7
rest-client|hum|0.20.2
kubernetes-snippets|ipe|0.1.9
open-file-from-path|jac|1.2.5
nginx-log-highlighter|jak|1.1.0
plantuml|jeb|2.9.8
docthis|joe|0.7.1
solidity|Jua|0.0.46
node-module-intellisense|lei|1.5.0
MagicPython|mag|1.1.0
vscode-mocha-sidebar|mat|0.20.18
dotenv|mik|1.0.1
vscode-kubernetes-tools|ms-|0.1.14
python|ms-|2018.9.1
debugger-for-chrome|msj|4.10.2
autodocstring|njp|0.2.3
vscode-extension-auto-import|Nuc|1.4.3
prettier-standard-vscode|num|0.3.0
vscode-docker|Pet|0.3.1
serverless-vscode-snippets|raf|0.0.4
nginx-formatter|ray|0.0.4
java|red|0.33.0
vscode-yaml|red|0.0.17
vscode-icons|rob|7.27.0
vscode-javascript-booster|sbu|0.10.2
bash-beautify|sha|0.1.1
code-settings-sync|Sha|3.2.0
vscode-nginx|sha|0.5.0
markdown-preview-enhanced|shd|0.3.8
indenticator|Sir|0.6.0
js-jsx-snippets|sky|0.3.0
javascript-typescript|sou|0.0.7
autoimport|ste|1.5.3
code-spell-checker|str|1.6.10
ayu|tea|0.16.0
python|tht|0.2.3
react-redux-es6-snippets|tim|2.1.0
python-extended-snippets|tus|0.0.1
vscodeintellicode|Vis|1.0.5
colonize|vms|2.2.2
vscode-java-debug|vsc|0.14.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.10.0
vscode-maven|vsc|0.11.1
vscode-react-native|vsm|0.6.18
vscode-todo-highlight|way|1.0.4
theme-code-os|wil|0.10.0
vscode-import-cost|wix|2.9.0
JavaScriptSnippets|xab|1.7.1
city-lights-icon-vsc|Yum|1.1.3
markdown-all-in-one|yzh|1.6.2
html-css-class-completion|Zig|1.17.1

(4 theme extensions excluded)

</details>

**Comment by weinand** [comment]
It is possible that this issue is caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.
