### ISSUE TITLE
Visual Studio Code crashes if big file's contrent is copied

### ISSUE THREAD

**Issue by Andrey-Anatolyevich** [microsoft/vscode#61911]
- VSCode Version: 1.28.2
- OS Version: Windows 10 Pro (up to date); i7-3770 processor; 16GB of RAM

Steps to Reproduce:
1. Obtain or create big .csv file Size: 79.6MB 13522 lines of content.
2. Open VS Code
3. Drag&Drop the .csv file into VS Code window
4. Select all file's content with Ctrl+A
5. Copy all the content with Ctrl+C

Does this issue occur when all extensions are disabled?: **Yes** (Checked)

VS Code version screen:
![image](https://user-images.githubusercontent.com/9977125/47595676-50b06900-d936-11e8-8d6c-031141b10327.png)

**Comment by rebornix** [comment]
let's track it in https://github.com/microsoft/vscode/issues/61911
