### ISSUE TITLE
Find widget history lost from untitled file when the file is saved

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#61918]
- Open new untitled file with some text
- Write complicated regex in find widget
- Save the file
- Open find widget, see that the find history is gone

But you can open a new untitled file to see the history. It seems like all untitled editors share find history and all real file editors share find history? Why are they separate?

**Comment by sandy081** [comment]
Assigning to November for investigation

**Comment by sandy081** [comment]
History is per find widget and not sure how find widget is created for these editors. Hence forwarding to editor land.

**Comment by rebornix** [comment]
Interesting idea but we are not going to implement in the near term.
