### ISSUE TITLE
Debug console line rendering problem, long line of dots disappears

### ISSUE THREAD

**Issue by ManfredSteiner** [Microsoft/vscode#61924]
Issue Type: <b>Bug</b>

This effect is observed on the result of the `console.log` statement in a remote system
(Debugging session ist started with launch.json/attach).

When printing a long line of identical characters, a line break is done automatically depending on width of  window. This is working proper, except the line is starting with spaces and continues with dots (`"     ......."`). In this case the output disappears if width is too small, and it reapperars if the window is enlarged.

This image shows as it should be. The line with dots is visible:
![nobug](https://user-images.githubusercontent.com/23413293/47600044-25bc2880-d9bb-11e8-88c5-90ed3bc03ce8.png)

The next image shows the bug. The width is reduced, the line with `A` breaks automatically, the line with `.` disappears. If the dot line has no leading spaces, it is visible:
![bug](https://user-images.githubusercontent.com/23413293/47600051-48e6d800-d9bb-11e8-9e16-a28cbd1105c9.png)

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:20:56.183Z)
OS version: Linux x64 4.15.0-36-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2028)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|11.43GB (0.99GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|1.4.7
vscode-eslint|dba|1.6.1
tslint|eg2|1.0.40
vscode-great-icons|emm|2.1.44
c-cpp-flylint|jbe|1.2.0
cpplint|min|0.1.3
vscode-remote-workspace|mkl|0.36.5
cpptools|ms-|0.19.0
remote-vscode|raf|1.1.0
markdown-pdf|yza|1.2.0

</details>

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/11462
Also this happens because of our wrapping heuristics, which might go away once we start using the new tree with dynamic heights
