### ISSUE TITLE
Improve OutputChannel API (discovery, appending, etc)

### ISSUE THREAD

**Issue by guardrex** [Microsoft/vscode#6192]
- VSCode Version: 1.1.0-insider
- OS Version: Win10

I understand how to create and use a new `OutputChannel` ...

``` typescript
var tasksOutputChannel = new OutputChannel;
tasksOutputChannel.addOutputChannel('Status Bar Tasks');
```

... but since my extension is working with tasks, it would be better if I could get a ref to the existing `Tasks` output channel and write my messages there.

I don't see a method for this. Is there any way to get such a reference to an existing output channel?

**Comment by jrieken** [comment]
You cannot do that today. 

> but since my extension is working with tasks, it would be better if I could get a ref to the existing Tasks output channel and write my messages there.

Can provide a little more details about that use-case? I'd like to understand the requirements such that we can discuss this request.

**Comment by GuardRex** [comment]
I'm the author of https://marketplace.visualstudio.com/items?itemName=GuardRex.status-bar-tasks

It would make sense for the output generated from the tasks fired off by the extension to appear in the existing Tasks output pane. As it stands, I had to create my own pane, which I called 'Status Bar Tasks.' Users now have two panes for basically the same ouput: If they execute a task using the command palette, the output goes to 'Tasks;' and if they execute a task from my extension, it goes to the pane that I setup.

**Comment by jrieken** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
