### ISSUE TITLE
Test: workspace storage using SQLite as backend

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#61928]
https://github.com/Microsoft/vscode/issues/58957

Complexity: 5

- [x] macOS @Tyriar 
- [x] Linux @alexr00 
- [x] Windows @joaomoreno 

In this milestone I changed the backend for workspace storage (any user of `IStorageService` with `StorageScope.WORKSPACE`) from `window.localStorage` to a SQLite DB on disk (`%APPDATA%/Code Insiders/User/workspaceStorage/<workspace ID>/storage.db`). Upon first opening of a window, data will be migrated exactly once into the new backend.

Even though there is a new backend, data will still be written to both the DB and `window.localStorage` for a couple of milestones until we are confident with the solution. Any state in the `StorageScope.GLOBAL` will end up in `window.localStorage` as before (we will switch to SQLite for global scope in the next milestone).

The easiest to test this is by running Code Stable on a user data dir (using `--user-data-dir`) and then opening Code Insiders on that same directory. Alternatively you can delete the folder `User/workspaceStorage` in our user home directory. This is the place where the SQLite DBs are stored.

Some **things** that we store in workspace storage that we can be used to check on:
* list of recently opened files in quick open
* list of opened editors and grid layout
* last active output channel
* sidebar hidden/visible
* [and more...](https://github.com/Microsoft/vscode/blob/a3549d44d2b657d54fac9a74bd73cca0a68ce6f6/src/vs/workbench/electron-browser/main.ts#L326)

**Note:** if you do not shutdown VSCode normally, some data might not get persisted. The reason is simply that some data is only persisted when the window closes and not periodically. That behaviour was there before with the old backend already.

**Note:** You can use https://sqlitebrowser.org/ to read the DB with an external tool if needed.

**Things to watch out for**
* there is no suspicious output in devtools that connections or operations fail (if the connection to the DB fails for some reason, this error should be printed. in fatal error cases we will fallback to an empty DB or  to an in-memory DB which is also logged as error)
* in no case we fail to render the workbench, even if the DB is corrupt or the connection cannot be made. we always fall back to a solution that allows the user to use the workbench (even though workspace state might be gone)

**Verify:**
* you can monitor all storage activity by running with `--logStorage`
* you can print the contents of workspace storage with the "Log Storage" action from the command palette (note that global storage will be empty as it is not used yet). the location of the DB is also printed
* data that was there before in `window.localStorage` is migrated to the SQLite DB and not lost. test this
  * from a single-folder workspace
  * from a multi-root workspace
  * from an empty window (yes, empty windows also have workspace storage associated)
* reloading the window or restarting will store data into the DB and restore properly when the workbench has loaded again
* entering a multi-root workspace from an empty window (just "Save Workspace As...") or single folder (just add another folder to the explorer) or workspace (just "Save Workspace As...") works and the workspace storage is persisted for that workspace (e.g. restores after window reload). Since this will enter a workspace without window reload, we migrate the workspace storage file behind the scene.
* try to crash the Code process to get the SQLite DB into a broken state if possible. Data might get lost but the DB itself should never get corrupted. If it does, we create it from scratch and store the corrupt DB next to `storage.db` with a `.corrupt` suffix but we always recover from that and never fail to startup at least. currently we are not creating backups of databases to restore, but this is an idea for the future.
* verify we start even if a corrupt DB is present (you can turn a DB corrupt by changing its contents with a normal text editor)

**Comment by bpasero** [comment]
@Tyriar I moved you off Linux to macOS because @alexr00 is using a Windows machine.

**Comment by alexr00** [comment]
@bpasero, I'm not seeing the sidebar get restored to debug on Linux. If I have it open to debug, close code, then open code-insiders, then it just gets opened to explorer. However, this appears to be the way it's supposed to work.

**Comment by bpasero** [comment]
@alexr00 I think what you are seeing is that we never restore the last used viewlet unless you do a window reload, so unless you saw other things not restoring properly I think that behaviour can be explained.

Good catch with `SQLITE_NOTADB`, can you file an issue on that one? I should probably check for more error cases like that.
