### ISSUE TITLE
remote debugging (launch / attach), console.log works but stdout is suppressed

### ISSUE THREAD

**Issue by ManfredSteiner** [Microsoft/vscode#61922]
Issue Type: <b>Bug</b>

I have a typescript remote platform project, using visual studio code (V1.28.2) as IDE. Node.js is started on platform, using the command `node --inspect=0.0.0.0:9229 --inspect-brk=0.0.0.0:9229 ...` there. 

In visual studio code the `launch.json` file defines an attach request:

    {
        "version": "0.2.0",
        "configurations": [
             {
                "type": "node",
                "request": "attach",
                "name": "Launch on RPI",
                "sourceMaps": true,
                "smartStep": true,
                "stopOnEntry": false,
                "port": 9229,
                "address": "192.168.1.2",
                "restart": false,
                "localRoot": "${workspaceRoot}/",
                "remoteRoot": "/home/pi/remoteproject/"
           }
        ]
    }

Everything is working fine (starting, debugging, ...). But there is one issue I cannot understand.

A call of `console.log('Hello');` is written in the Debug console window of code.  
A call of `process.stdout.write('Hello\n');` is suppressed there.

If the program is started inside a shell on the remote platform, both statements are printed out.

What is the reason for this different behavior?  
How I can redirect stdout to to visual studio code Debug console (or terminal) window?

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:20:56.183Z)
OS version: Linux x64 4.15.0-36-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2004)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|11.43GB (0.78GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|1.4.7
vscode-eslint|dba|1.6.1
tslint|eg2|1.0.40
vscode-great-icons|emm|2.1.44
c-cpp-flylint|jbe|1.2.0
cpplint|min|0.1.3
vscode-remote-workspace|mkl|0.36.5
cpptools|ms-|0.19.0
remote-vscode|raf|1.1.0
markdown-pdf|yza|1.2.0

</details>

**Comment by weinand** [comment]
"stdout" and "stderr" are connected to the terminal where node.js is started.
"log" is connected to the debug connection and shows up in VS Code's debug console.

It might be possible to redirect "stdout" and "stderr" to the debug connection by adding a `""outputCapture": "console"` to your launch config.

**Comment by ManfredSteiner** [comment]
The attribute `outputCapture` is working for `"request":"launch"` configuration. It is not allowed (and not working) for `"request":"attach"` configuration (see question),

**Comment by roblourens** [comment]
`process.stdout.write('Hello\n');` writes directly to the stdout stream, and can't be captured by the debugger. `outputCapture` can't be used for "attach" because the debugger doesn't have access to the process' stdout. So we can't help with that case unforunately.

**Comment by ManfredSteiner** [comment]
Capturing of stdout and stderr would be essential for debugging on remote platforms. I hope that someone will offer an extension, which is able to attach also to stdout and stderr on the target platform. At the moment I have written an debug log handler which collects messages and uses `console.log` to print them out. Not perfect but it works as work-arround and I can see the complete output as long as  I use the logger.

**Comment by weinand** [comment]
I don't think that an extension can solve this issue because launch a runtime/debugger remotely is not under the control of VS Code so there is no way capture stdout/stderr.

But IMO this is not a real problem. I think there are three scenarios:
- the remote runtime is launched manually in a remote shell: then stdout/stderr is available in the remote shell.
- the remote runtime is launched programmatically. In this case stdout/stderr is typically redirected into a log file, which itself is available for inspection.
- the remote runtime/program has wired up stderr/stdout with the logging mechanism available via the debug connection. This is the approach you are using and it seems to work fine.

**Comment by ManfredSteiner** [comment]
I disagree @weinand's summary, an extension could solve this issue, when another ssh connection is automatically established if starting a  remote debugging session. This session could redirect outputs.
I know this kind of debugging from remote-platform debugging with Netbeans and Java. The java code is compiled on fast work system, then the java classes are transferred via ssh to the remote system and started there. Output is automatically relocated via ssh back to the work system. Perfect solution, very comfortable and efficient to work.

All other solutions (you point it out) are less or more a work around. At the moment you have to login on  the remote system (inefficient) or to use a logger which is using  `console.log` all the time (that's the way I am doing at the moment).

**Comment by weinand** [comment]
@ManfredSteiner your solution is just an elaborate form of my first scenario.

Yes, you can add an extension on top of the remote shell/SSH that redirects stderr and stdout to the debug console. But there is no big advantage in doing so because the debug console is rather limited in comparison to the integrated terminal and SSH.
