### ISSUE TITLE
Disable "Clear all notifications" if no notifications is available

### ISSUE THREAD

**Issue by SamueleDassatti** [microsoft/vscode#61934]
- VSCode Version: 1.29.0-insiders
- OS Version: Windows 10 Pro (1809)

Steps to Reproduce:

1. Open the notification panel in the lower-right corner
2. Clear all notifcations, if there is any
3. "Clear all notifcations" is not hidden if no notification is present

This issue occurs even when all extensions are disabled.

**Comment by Anakha77** [comment]
Wouldn't be better to disable the button instead of making it disappear ?

With notifications :
![image](https://user-images.githubusercontent.com/11684508/47617541-77060e00-dac8-11e8-8270-885a15929332.png)

Without :
![image](https://user-images.githubusercontent.com/11684508/47617531-56d64f00-dac8-11e8-89ee-88f9e402da5b.png)

**Comment by SamueleDassatti** [comment]
I agree, it would be much more consistent.

**Comment by bpasero** [comment]
Sorry, I am not convinced we should do that. I feel like it is very convinient to allow to close the notifications center always from the same action even if there are no notifications.

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/pull/82171

**Comment by bpasero** [comment]
Verify: the "Clear Notifications" button is disabled in the notifications center when there are no notifications and enabled when there are.

**Comment by Tyriar** [comment]
The button is disabled but it still lights up a little when clicking the disabled button.

**Comment by bpasero** [comment]
I do not reproduce that if we had this issue, it would surface for every disabled action item. Can you report this as new issue after checking that it reproduces elsewhere?
