### ISSUE TITLE
vscode c file outline not working

### ISSUE THREAD

**Issue by noullove** [Microsoft/vscode#61933]
Version: 1.28.2 (user setup)
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:23:51.859Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

- VSCode Version: 1.28.2 
- OS Version: Windows 10 Home

Steps to Reproduce:

1. open c sample file
![vscode outline](https://user-images.githubusercontent.com/2210413/47602244-19fe4f80-da17-11e8-9edf-015b48a6b9c9.png)

2. outline view function list not showing (loading symbols...)

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
file against C/C++ extension

**Comment by noullove** [comment]
Opening a file with the folder open will work properly.
However, it does not work if you open the file only.

**Comment by weinand** [comment]
Yes, most likely the C/C++ extension can't find the necessary project information if only a single file and not the project folder was opened.
