### ISSUE TITLE
Question: Is there a way to hide the .vscode folder?

### ISSUE THREAD

**Issue by animanoir** [Microsoft/vscode#6193]
- VSCode Version: 1.0
- OS Version: Windows 10

Steps to Reproduce:

1. Create a new project.
2. Wait until the folder appears.

So yeah, it is only that. I find it a bit annoying. But I know it might be useful.

**Comment by bpasero** [comment]
http://stackoverflow.com/questions/30140112/how-do-i-hide-certain-files-from-the-sidebar-in-visual-studio-code/30142299#30142299
