### ISSUE TITLE
VSCode opens a lot of tscancellation files in workspace editor

### ISSUE THREAD

**Issue by antony-chopin** [Microsoft/vscode#61935]
Issue Type: <b>Bug</b>

I did not do something special, just worked with Typescript-React project with up to 2 terminal sessions (WDS and NodeJS server) and 2-10 files opened in editor (each of 10-100 lines of code, `.sass`, `.ts`, `.tsx`). In one moment (approximately after 2 hours of work, but sometimes it can take longer) autocomplete in `*.ts`/`*.tsx` files stops working (shows "Loading..." instead of autocomplete list). After that I'm reloading the VSCode after 1-2 minutes a lot of `tscancellation` files (about 50) with empty content are appearing in my workspace editor, and also the "VSCode stopped working" Ubuntu error screen is showing.

The tscancellation files have this relative path and format:
`/tmp/vscode-typescript/tscancellation-{some hex}.tmp{some decimal}`

During all of this action, nothing unusual happens with the system - no lags, CPU overloads, etc.

This bug is rare, and it starts happening since 1.28.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:20:56.183Z)
OS version: Linux x64 4.15.0-38-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 x 3273)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|7.74GB (2.16GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
svg|joc|0.1.4
sass-indented|rob|1.4.9

</details>

**Comment by mjbvz** [comment]
The cancellation files are just a symptom of the `Loading...`. They are expected

Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?
