### ISSUE TITLE
VS Code & VS Code Insiders fails to start without Internet Acces

### ISSUE THREAD

**Issue by aindriu80** [Microsoft/vscode#61931]
- VSCode Version: 1.28
- OS Version: Windows 10 Pro with latest updates

Steps to Reproduce:

1. No Internet connect
2. Launch either VS Code or VS Code insiders

I have read several threads on this issue but none offer a resolution and they are a few years old.  Without an Internet connection VS Code will not launch.  However Visual Studio 2017 will launch.  What is the solution ? 

Internet != Electricity;

**Comment by aindriu80** [comment]
I'm sorry Bot but that's not an answer, its a circular.  Duplicate on each one.

**Comment by alessiot89** [comment]
I got the same issue. And this is a BIG issue. This is unacceptable for a software like this, and no, I am not in Lemongrab mode. I don't thing we need a scientific paper to explain why such software need to offline.

Please, fix this.
