### ISSUE TITLE
Bug: Font error when i change font size to 14

### ISSUE THREAD

**Issue by giangm9** [Microsoft/vscode#6194]
- VSCode Version: 1.0.0
- OS Version: Ubuntu 16.04

Steps to Reproduce:
1. Install Droid Sans Mono font
2. Open workspace preference
3. put these setting in the file
   "editor.fontFamily": "Droid Sans Mono",
   "editor.fontSize": 14
4. this happen

![image](https://cloud.githubusercontent.com/assets/10234339/15096217/f4bb9ea4-1519-11e6-823e-c2472ff7696c.png)

VSCode works fine with other font size but 14

**Comment by alexandrudima** [comment]
I can reproduce this funny looking behaviour in both Firefox and Chromium on Ubuntu 16.04.

I think there is something funny about the font. If you wish to pursue this issue further, I recommend opening issues against Chromium at https://bugs.chromium.org/p/chromium/issues/list

repro:
http://codepen.io/anon/pen/GWoLGL
