### ISSUE TITLE
Extremly blurry text

### ISSUE THREAD

**Issue by belst** [microsoft/vscode#61940]
- VSCode Version: 1.29.0-insiders
- OS Version: Win 10 (also happens on Linux (Arch))
- GPU-Driver: Nvidia 416.34

Steps to Reproduce:

1. Open File
2. Move mouse

Does this issue occur when all extensions are disabled?: Yes

I know this is fixable with `--disable-gpu` but I do need gpu support for plugins which use webgl.

Does not only happen on Windows. I also noticed this on Linux.

![](https://i.imgur.com/fSoOHyF.png)

References: #44168 #1896

Other than disabling GPU (which I can't) I have not found a fix yet. I had this issue for quite a while now (at least half a year).

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/45498d93166483c2eff886e28f8dab915ae382fc/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/code-exploration_1.28.0-1538127308_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/VSCodeUserSetup-x64-1.28.0-exploration.exe)

**Comment by belst** [comment]
Thanks. it still happens with the exploration build:

![](https://i.imgur.com/fImCT8x.png)

**Comment by samrose3** [comment]
@bpasero using the Exploration build fixed this issue for me 👍

Issue: blurry text


* VSCode Version: 1.29.1
* OS Version: macOS Mojave 10.14.1
* GPU: Intel HD Graphics 630 & Radeon Pro 555

VS Code 1.29.1 does work on my work Macbook Pro (same OS version) but with a Radeon Pro 560 🤷‍♂️
