### ISSUE TITLE
Folding in XML files doesn't work properly

### ISSUE THREAD

**Issue by smarts** [Microsoft/vscode#6195]
I'm not sure if it's relevant, but apparently this happens in Atom too atom/atom#3442

- VSCode Version: 1.0.0 (Commit fa6d0f0)
- OS Version: Windows 8 Pro

Steps to Reproduce:

 - create a new file 
 - select XML language mode
 - use this text:
```xml
<foo>
	<bar>
		<baz/>
	<baz>
		blah blah blah
	</baz>
	</bar>
</foo>
```
 - try to fold the `<bar>` element on line 2

user settings (minus `git.path`, because I _hope_ that doesn't affect code folding):
```json
// Place your settings in this file to overwrite the default settings
{
    "editor.tabSize": 2,
    "editor.insertSpaces": false,
    "files.eol": "\n",
    "files.trimTrailingWhitespace": true,
    "files.autoSave": "afterDelay",
    "files.autoSaveDelay": 60000
}
```

**Comment by aeschli** [comment]
What you see is what's expected. The currently implemented folding strategy is based purely on the indentation of lines. A folding region starts when a line has a smaller indent than one or more following lines, and ends when there is a line with the same or smaller indent.

To be more smart and to, for example, understand tags, we will have to go one step further and introduce language agnostic folding regions. We have issue #3422 for this.
