### ISSUE TITLE
Create the SplashScreen in Visual Studio Code

### ISSUE THREAD

**Issue by Dob6458** [Microsoft/vscode#61958]
Hello everyone,
In Visual Studio Code, I think it's possible to create the **SplashScreen**.
While the loading, the **VSC icon** is show to center of this application.
After, he can show the code editor, the menus, the navbars...

Thanks.

![untitled](https://user-images.githubusercontent.com/35851048/47608312-db26c480-da2b-11e8-89a2-3e1def90209f.png)

**Comment by belst** [comment]
why? vscode starts almost instantly. no need for a splash screen.

**Comment by Dob6458** [comment]
@belst You know, Today, while a loading, he have no icons to center of this program.

**Comment by weinand** [comment]
as already observed by @belst: one goal of VS Code is to start instantly. To show a splash screen would mean that we'd have given up on that goal.
