### ISSUE TITLE
Window closes when I place a large amount of text in the clipboard

### ISSUE THREAD

**Issue by ananaszjoe** [Microsoft/vscode#61968]
![image](https://user-images.githubusercontent.com/6877691/47610212-07543c80-da50-11e8-944f-7377646c7a11.png)

Issue Type: <b>Bug</b>

I'm switching from Sublime Text and evaluating how Visual Code compares. Dealing with unreasonably large text files is something most of text editors struggle with, but VS Code seems to do worse than just struggle. I made a .sql file with a million lines, weighing about 70 MB. Opening the file in VSC is okay, but noticeably slower than a regular file. However, when I hit CMD+A and CMD+C to copy the whole content, the app seems to crash and a standard windows error window pops up, saying "The window has crashed" with options to "Reopen" and "close".

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz (8 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.76GB (2.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.6.1
php-debug|fel|1.12.6
php-intellisense|fel|2.3.5
php-pack|fel|1.0.2
file-icons|fil|1.0.16
vs-color-picker|lih|0.7.0
vscode-scss|mrm|0.6.2
sublime-keybindings|ms-|4.0.0
vscode-css-peek|pra|2.1.0
magento-snippets|raf|0.1.3

</details>

**Comment by rebornix** [comment]
@ananaszjoe it's very likely we run into OOM on v8, can you help try `code --max-memory=4096` (first close all vscode instances) and see if it helps?
