### ISSUE TITLE
If all problems are warnings, use yellow instead of red

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/vscode#61960]
See this screenshot:

<img width="938" alt="screenshot 2018-10-27 13 26 26" src="https://user-images.githubusercontent.com/11139560/47609007-0689bf00-d9ec-11e8-94b5-6085a9be81bb.png">

In the problems tab, we see a red warning sign, but all the problems are warnings, not errors, so the icon should be yellow instead of red, to let us know that the only problems are warnings not errors.

In other words, there is an icon with 2 problems, that should be yellow not red in this case.

**Comment by sandy081** [comment]
It's the badge whose colour is themable. It means your current colour theme is colouring it red. Colour of the badge is nothing to do with the type.
