### ISSUE TITLE
Support adding grammars at runtime

### ISSUE THREAD

**Issue by michaelgmcd** [microsoft/vscode#61962]
Hello!

I'm the author of [vscode-language-babel](https://github.com/michaelgmcd/vscode-language-babel) and I'd love to be able to support [configurable tagged template literal grammar extensions](https://github.com/gandm/language-babel#javascript-tagged-template-literal-grammar-extensions). In order to do this, I'd need to be able to add grammars based on the users configuration instead of in the `contributes.grammars` field.

I've noticed the [vscode-textmate](https://github.com/Microsoft/vscode-textmate) library used within vscode has the methods I would need but they don't seem to be public. Would a feature like this be possible to expose to extension authors?

**Comment by michaelgmcd** [comment]
@alexr00 would it be possible to get an update on this issue?

**Comment by jquense** [comment]
would love to see some movement or workaround for this

**Comment by cdaringe** [comment]
Ah man @vscodetriage-bot! This is a pretty advanced feature. The average user will have a hard time foreseeing the benefits such a feature could offer. 

I'm talking to a bot. 🤦

**Comment by jquense** [comment]
yeah that sucks. we have to round up 20 votes from vscode grammar extension devs...
