### ISSUE TITLE
Regression: Custom view item tooltips don't show up

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#61970]
Issue Type: <b>Bug</b>

Tooltips on custom view items almost never show up anymore.

They still work fine in 1.28.2.
/cc @sandy081 

VS Code version: Code - Insiders 1.29.0-insider (4a29bd3731e40c07622bae0e9b0ac3b422b5672a, 2018-10-25T05:48:41.485Z)
OS version: Windows_NT x64 10.0.18267

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (17.09GB free)|
|Process Argv|c:\Users\Eric\code\vscode-gitlens|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by eamodio** [comment]
Some more details on this -- it looks like the tooltips DO show up when you hover over the empty area of an item, but don't show up when hovering over the text or icon.

Also semi-related -- while the tooltip of "inline" commands on a tree item do show up, when you hold `alt` to show the alternate command the tooltip doesn't show up

**Comment by sandy081** [comment]
@eamodio Other issue is not related and is not a regression. Can you please file a separate issue?

**Comment by eamodio** [comment]
@sandy081 done: https://github.com/Microsoft/vscode/issues/62064
