### ISSUE TITLE
Git removes all files from tracking

### ISSUE THREAD

**Issue by Shein** [Microsoft/vscode#61979]
Issue Type: <b>Bug</b>

Since last update VS Code (that we just love) periodically removes all files from tracking on git (as if the command git rm * was executed). Even after re-adding these files this continues to happen every few minutes making working with source control impossible on this project

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.60
Bookmarks|ale|9.1.0
copy-relative-path|ale|0.0.2
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.6.1
githistory|don|0.4.3
prettier-vscode|esb|1.6.1
intellij-idea-keybindings|k--|0.2.28
python|ms-|2018.9.1
debugger-for-chrome|msj|4.10.2
vetur|oct|0.13.0
LiveServer|rit|5.1.1
vue-vscode-extensionpack|sdr|0.1.3
vue-vscode-snippets|sdr|1.3.0
vscode-status-bar-format-toggle|tom|1.4.0
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.7.1

(1 theme extensions excluded)

</details>

**Comment by weinand** [comment]
It is possible that this issue is caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by Shein** [comment]
Thanks for super quick reply - yep looks like an extension issue. Will look deeper and file against the extension repo. Thanks!
