### ISSUE TITLE
Mouse clicks when I release the button in Context Menu

### ISSUE THREAD

**Issue by TheAifam5** [Microsoft/vscode#61982]
Version: 1.28.2
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:20:56.183Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
OS: ArchLinux
Window Manager: GNOME 3.30

**Expected behavior**
I right click (mousedown), the context menu appears, nothing happens when I release the button. To click an item in the context menu, I click it normally with the right mouse button.

**Actual behavior**
I right click (mousedown), the context menu appears, when I release the mouse button (mouseup), the item under the cursor is clicked.
The issue does not occurs when the Program runs in Full-Screen mode, because Context-Menus are placed only on top and bottom of the cursor.

I tried different WM (Gnome based), Themes, Cursors and still the same issue.

Atom Editor (context menu is created with 1px padding on the left):
![atom](https://user-images.githubusercontent.com/2192274/47616749-48386980-dac1-11e8-9f22-8a56384b8992.png)

VSCode Editor (cursor is inside the Context Menu):
![vscode](https://user-images.githubusercontent.com/2192274/47616757-51c1d180-dac1-11e8-90f0-b91c901d821d.png)

**Comment by sbatten** [comment]
the behavior of clicking on mouseup is as designed, however the issue you are experiencing is not, and I will direct you to that issue. #61154

**Comment by TheAifam5** [comment]
@sbatten that's really similar issue.
