### ISSUE TITLE
Setting to enable variable completion in string literals.

### ISSUE THREAD

**Issue by safield** [Microsoft/vscode#61984]
This issue is closely related to #61985 , but I believe should be addressed independently.

I would like to see a configurable setting to enable variable completion in string literals.

I can imagine many people not desiring this, so default could sensibly be false.

I commonly refer to variables in literals when doing log writes.

This behaviour would also be congruent with Vim and Sublime, so it would be familiar for many developers.

**Comment by ZenoArrow** [comment]
I understand the request, but isn't it not generally recommended to put implementation details in comments? Doesn't it just increase the general maintenance burden in code, when compared to comments that describe the general behaviour (and leave out implementation details).

**Comment by safield** [comment]
> I understand the request, but isn't it not generally recommended to put implementation details in comments? Doesn't it just increase the general maintenance burden in code, when compared to comments that describe the general behaviour (and leave out implementation details).

I think this is an ideological question that is objectively outside the scope of this particular discussion.

**Comment by ZenoArrow** [comment]
Sure, it's an ideological point, but generally it helps to keep the core of the editor focused on "best practices" and allow for custom workflows via extensions.

Every feature, no matter how small, adds to the maintenance burden. With this request in particular I can foresee a number of follow up requests. For example, "Refactoring variable names should update variable names in comments too", which would mean that comments would need to be parsed as code just to support a niche workflow.

I'd suggest you'd be better off putting together a VSCode extension for this type of functionality.

**Comment by safield** [comment]
You have swayed me. Removed the "comments" portion of the request.

**Comment by jrieken** [comment]
> I understand the request, but isn't it not generally

Sorry, but I don't understand the request. What is this for? In what language? What variables? Can you provide a sample?

**Comment by ZenoArrow** [comment]
> 
> 
> > I understand the request, but isn't it not generally
> 
> Sorry, but I don't understand the request. What is this for? In what language? What variables? Can you provide a sample?

You're replying to the wrong person. I didn't raise the request.

In any case, what the requester is asking is for code elements to be included in whatever autocomplete mechanisms that VSCode has when writing text. Think of it like spelling corrections when writing Word documents, the "words" that are names of code elements appear in the dictionary of valid names, which also allows them to be autocompleted. It doesn't have to be tied to a single language, unless it's a necessity to only have this behaviour for variable names.

I'd suggest directing further questions at safield.

**Comment by jrieken** [comment]
> In any case, what the requester is asking is for code elements to be included in whatever autocomplete mechanisms that VSCode has when writing text.

VS Code is just the messenger - it doesn't compute completion but makes requests to extensions and renders results from extensions. It does offer word-based completions which are enabled *everywhere* via this setting `"editor.wordBasedSuggestions": true`. For everything else please get in touch with the extensions directly.
