### ISSUE TITLE
Error Run 'Debug: Download .NETCore Debugger' in the Command Palette or open a .NET project directory to download the .NETCore Debugger

### ISSUE THREAD

**Issue by vaishnav4226** [Microsoft/vscode#6198]
- VSCode Version: 1.0.0
- OS Version: 10.11.4

Steps to Reproduce:

1. Using dotnet new to create a simple HelloWorld.cs program. 
2. dotnet restore and dotnet run to check if the program can run without an errors (optional)
3. Put a breakpoint and hit cmd + f5. 

After following the steps above, I get the error: 
Error Run 'Debug: Download .NETCore Debugger' in the Command Palette or open a .NET project directory to download the .NETCore Debugger

$ dotnet --version
.NET Command Line Tools (1.0.0-beta-001598)

Product Information:
 Version:     1.0.0-beta-001598
 Commit Sha:  7582649f88

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 Runtime Id:  osx.10.11-x64

Strange part is I already have the .NETCore Debugger installed. It keeps asking me to open project.json
Is there any other information that I could share here to help you guys figure this out? This is the first issue I am opening. Thanks.

**Comment by GuardRex** [comment]
@vaishnav4226 That's an ancient version of `dotnet cli`. Get the SDK installer (2nd column) from the cli repo at https://github.com/dotnet/cli/tree/rel/1.0.0. It might not solve your prob with debugging, but it certainly is a suspect.

**Comment by bpasero** [comment]
I am very sorry to hear you are having issues with VS Code. Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Comment by vaishnav4226** [comment]
@GuardRex Thanks for the reply. I tried installing the latest SDK from the link you posted. After installing it, I still see the same version. Do I need to uninstall it first and reinstall it? Thanks

**Comment by GuardRex** [comment]
@vaishnav4226 Ah ... you may have run into this problem ... https://github.com/dotnet/cli/issues/2948

Do what I did: Uninstall any `dotnet cli`'s you see in `Programs & Features`, clean out any lingering registry keys (I think they're at: `HKLM > Software > Microsoft > dotnet`), clean up any lingering SDK's (should be found at `c:\Program Files\dotnet\sdk`. Probably a good idea to nuke the package caches: `nuget locals all -clear` or find and delete them at `C:\Users\<USER>\.nuget\packages`. Check the system PATH and make sure there aren't any lingering paths (I found one just yesterday to a DNX location! I haven't had DNX on this PC for quite a while. Restart your PC. Install the latest SDK.

**Comment by vaishnav4226** [comment]
@GuardRex Thanks for the reply. You guys are the best. Would appreciate instructions to do the exact same steps on Mac OSX. Trying to find a good way to remove and reinstall dotnet for a while now. Haven't found anything useful yet 😢

**Comment by GuardRex** [comment]
@vaishnav4226 Sure thing. Ah! I'm all Windows here. There are plenty of Mac :cat:'s around tho, so I'm sure someone will jump in. Otherwise, ask for help on JabbR, and there might be a Mac pro there. https://jabbr.net/#/rooms/AspNetCore

**Comment by jasonmm** [comment]
@vaishnav4226 [these uninstall/re-install steps](https://www.microsoft.com/net/core#macosx) worked for me.

**Comment by CarlosTorrecillas** [comment]
@vaishnav4226 the official steps (including running the sh script) did the trick for me as well. Thanks @jasonmm
