### ISSUE TITLE
Clear Console doesn't work and output is sometimes missing

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#61986]
Debug `console.log('hi')`

- Get console output
- Click Clear Console
- Nothing happens

Sometimes, I start debugging and get no console output at all

**Comment by thpeder** [comment]
I have a similar experience with the insider c72cb129f2a0b8117c9b01f3767026041d7d1d31.
After I change the field name and tries to debug again then it doesn't update the messages in the output panel (see the timestamps for each line) and only when I click clear then it shows some of the messages:
![insiderdebugoutputclear](https://user-images.githubusercontent.com/24276180/48425815-dec58580-e765-11e8-8e04-e4893b55c4f8.gif)

**Comment by isidorn** [comment]
@roblourens oups this somehow feel through my fingers, sorry about that. Can you still reproduce with the latest insiders? Becuase I can not following your steps
@thpeder that issue I probably introduced yesterday. Can you try to reproduce with running a simple node program
`console.log('hello')`
Or any reproducable steps would be really helpful for me. Thanks

**Comment by roblourens** [comment]
I don't think I've seen it lately.

**Comment by isidorn** [comment]
@roblourens got it. So your issue is probably fixed
Let's wait for @thpeder for a potential reproducable sample

**Comment by thpeder** [comment]
@isidorn It seems like the logic for when it shows the output messages has changed.
We are sending messages to the debug output panel before replying to the Launch request and if the response to the Launch request is not a success then it doesn't show them.
I have changed the Mock-Debug-Adapter project to reproduce the problem, see here [thpeder/vscode-mock-debug](https://github.com/thpeder/vscode-mock-debug).

**Comment by isidorn** [comment]
@thpeder thanks for the nice repro steps, the fix should be ini tomorrows vscode insiders.
Please try it out and let us know if this fixes the issue for you.

**Comment by isidorn** [comment]
@StanislawStempin hi, currently the recvoery build 1.29.2 is not planned.
However if we decide to do this we can include this fix.

My suggestion is to either tell your developers to use vscode insiders
Or to do a recovery release of your extension which fixes this in the following way:
send messages to the output channel while a debug session is not fully initialised, reveal the output channel and hide it appropriatly

Kind regards
