### ISSUE TITLE
Multi cursor completion while subset of cursors are in string literals.

### ISSUE THREAD

**Issue by safield** [Microsoft/vscode#61985]
This issue is closely related to #61984  , but I believe should be addressed independently.

**Current Behaviour:**
When multiple cursors are currently being used to edit text, completion suggestions only display if the location of the first initial cursor was not in a string literal.

**Desired Behaviour:**
If multiple cursors are being used to edit text, if at least one of the cursors is not located in a string literal, completion suggestions should be used.

Observe my favourite snippet:

System.out.println("$1 = "+$1);

I use this to quickly print out values of variables.

When used, the two $1 are replaced with two instances of cursors, but when I begin to type no completion is present, because the first cursor is in a string literal.

This behaviour could be implemented as a configurable setting potentially.

**Comment by alexandrudima** [comment]
AFAIK suggestions currently use the primary cursor as the context for the suggestion. That would be the cursor next to which suggestions are rendered.

I guess in this case the primary cursor is the one inside the string, and it is used as the position which is sent to language servers. I don't think there is a lot to do here except perhaps send N completion requests and show all the suggestions returned. But that would be a performance hit...

**Comment by jrieken** [comment]
Yeah, the design is that the primary cursor counts
