### ISSUE TITLE
Intellisense is not woking 

### ISSUE THREAD

**Issue by BhagathB** [Microsoft/vscode#61988]
after a few minutes the Intellisense stops working, even after restarting the visual studio code

**Comment by gocs** [comment]
needs more info

**Comment by tiancihe** [comment]
Having the same issue here.

**Comment by Lakston** [comment]
I don't know if I should create a new Issue or if I should piggy back on this one and add some infos so here we go:

Intellisense is not working in an Angular V7 project, the only intellisense I get is for selenium (ex: I'll add `HttpClient` and the auto import only proposes the selenium one)

I have no intellisense on any Angular module (ex: typing `HttpClientMod...` does not yield any options)

How to reproduce: simple `ng new myapp` with the latest cli version (7.0.3) and try adding any core module or use autoimport in a service using the httpclien.

Intellisense works when I do an `implements` and will show lifecycles, same for adding a lifecycle method in the component.

My typescript version is `3.1.3` on both my project and vscode.

**Comment by mjbvz** [comment]
@Lakston Create a new issue. 

@BhagathB Please follow [this guide](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions) to submit a proper issue report. This should include:

- What are you trying to do?
- What went wrong?
- Steps to reproduce the problem
