### ISSUE TITLE
White bars unreadable text after wake from suspend on Linux

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#61987]
Issue Type: <b>Bug</b>

1. Open terminal in VSCode (CTRL + `)
1. Puts system to RAM sleep.
1. Wake system up.
1. Notice VSCode windows as well as terminal has white bar making  text unreadable.

This happens all the time and easy to reproduce on my Linux system. I am using Kubuntu 18.04LTS with the NVidia driver.

The vertical bar inside the terminal will not go away, I am forced to close the terminal and open new one. The other bar clear up by resizing the window panes.

- KDE Plasama: v5.12.6
- KDE Framework: v5.44.0
- QT: v5.9.5
- NVidia Driver: v390.77 (Later recommended by Kubuntu for GeForce GT 430)

VS Code version: Code - Insiders 1.29.0-insider (5d68db08cda5accef740c69541178911b865d069, 2018-10-26T05:13:31.757Z)
OS version: Linux x64 4.15.0-38-generic

![image](https://user-images.githubusercontent.com/439226/47619571-93994a80-dab6-11e8-898d-5a529934a3f6.png)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Phenom(tm) II X4 940 Processor (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|15.66GB (5.86GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
dep|car|0.1.0
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.21.0
vscode-eslint|dba|1.6.1
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.40
markdown-toc|jof|1.4.0
solidity|Jua|0.0.46
sort-typescript-imports|mic|1.4.1
Angular-BeastCode|Mik|7.0.9
cpptools|ms-|0.19.1-insiders3
debugger-for-chrome|msj|4.10.2
angular2-inline|nat|0.0.17
java|red|0.33.0
language-stylus|sys|1.10.0
sort-lines|Tyr|1.7.0
vscode-java-debug|vsc|0.14.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.10.0
vscode-maven|vsc|0.11.1
better-align|wwm|1.1.6

(2 theme extensions excluded)

</details>

**Comment by rajinder-yadav** [comment]
This happens with NVidia video cards only, I got a new ATI Radeon card and this problem doesn't exist for this card.

**Comment by Tyriar** [comment]
This is a Chromium problem (Electron uses Chromium).
