### ISSUE TITLE
Racourcci "ouvrir avec vs code" ouvre une ancienne version

### ISSUE THREAD

**Issue by deado800** [Microsoft/vscode#61980]
Issue Type: <b>Bug</b>

Quand j'utilise le raoucrci "ouvrir avec vs code" quand je clique avec bouton droit sur un dossier (sous windows) la version de vs code qui s'ouvre est la 1.26, alors que la version installée est la 1.28.2 ! et à chaque fois VS code essaye de lancer la mise à jour pour passer a la 1.28.2 alors que je l'utilise déjà ...

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (3.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
gitlens|eam|8.5.6
RunOnSave|eme|0.0.18
beautify|Hoo|1.4.7
minify|Hoo|0.3.0
vscode-favorites|how|1.4.0
latex-workshop|Jam|5.13.0
restructuredtext|lex|79.0.0
vscode-apache|mrm|1.1.1
vscode-language-pack-fr|MS-|1.28.2
mssql|ms-|1.4.0
python|ms-|2018.9.1
team|ms-|1.142.0
LiveServer|rit|5.1.1
vscode-table-formatter|shu|1.2.1
vba|spe|1.2.0
html-preview-vscode|tht|0.2.4

</details>

**Comment by deado800** [comment]
Hi there,
I'm sorry for the inconvenience, my English skills is weak. And as I'm using fresh version of VS code I wrote it on French.
by the way, your translation is exactly what I would have wrote in English.

**Comment by joaomoreno** [comment]
You must have both versions installed on your machine. Please find them and uninstall them all. Then, download Code again and install the latest.
