### ISSUE TITLE
Python: Add 'params' to 'function' tooltips

### ISSUE THREAD

**Issue by C-PyLx** [Microsoft/vscode#61996]
Issue Type: <b>Feature Request</b>
![issue_li](https://user-images.githubusercontent.com/40021473/47622030-2668d200-db15-11e8-817b-0678624355b5.jpg)

Hi, very thanks for this application and we like it.
We wants from you to add (function parameters) into (functions) tooltip.

This property helps us to find the parameters in our pro programs.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

**Comment by mjbvz** [comment]
File this against the python extension

**Comment by C-PyLx** [comment]
I Titled the python language. I don't know exactly where to put this feature.
Show me python's extension issue link, thanks.

**Comment by mjbvz** [comment]
https://github.com/Microsoft/vscode-python
