### ISSUE TITLE
Misaligned 'new folder' input box

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#61991]
![image](https://user-images.githubusercontent.com/323878/47620219-06012f00-daa5-11e8-8478-2c05229b969d.png)

- Disable folder icons
- Add new folder in file explorer, at the top level of the file tree
- The left border of the input box is missing. It's easier to see if you add an error.

@isidorn do you own this now?

**Comment by isidorn** [comment]
Dup of #61991

**Comment by roblourens** [comment]
That is this issue

**Comment by isidorn** [comment]
sorry. Dup of #61269
