### ISSUE TITLE
Output for IntelliSense 

### ISSUE THREAD

**Issue by sleemer** [Microsoft/vscode#6199]
- VSCode Version: 1.1.0-insider (1.1.0-insider)
- OS Version: OS X 10.11.4 

Steps to Reproduce:
1. If there is an error within IntelliSense internals than there is no way to make anything of this issue.
2. It would be great if IntelliSense uses Output to writes logs.

**Comment by mjbvz** [comment]
This is language/extension specific. TypeScript and Html and CSS for example already provide this functionality for debugging intellisense issues
