### ISSUE TITLE
Add 'globalSearchFocus' context for keyboard shortcuts

### ISSUE THREAD

**Issue by nikitavoloboev** [Microsoft/vscode#61990]
I often make whole codebase searches with cmd+shift+f and I really wish I could press down arrow to instantly jump to the results of my search query. However that seems impossible to do and I couldn't figure out how I could bind down arrow to jump to results from my search query. Currently pressing down arrow does nothing for me in this context.

There is `Search: Focus List` command available and I wish I could bind it to down arrow when I am making a global search query. However there is no such context available so I could not make this hotkey. Perhaps I am mistaken and it is possible to add this hotkey somehow.

I would really appreciate having the ability to change what down arrow key does when making global searches.

Thank you.

**Comment by roblourens** [comment]
You should be able to do this with `cmd/ctrl+down`. `down` there is for navigating history. The command being invoked there is `search.focus.nextInputBox` if you want to customize it.
