### ISSUE TITLE
Go to definition and navigate back puts cursor in wrong spot

### ISSUE THREAD

**Issue by dlclark** [Microsoft/vscode#62]
Use Go To Definition (F12) on a function call to jump to its definition.  Then immediately use "Back" (Ctrl-minus).  Your cursor will not be back to where it was when you hit F12.  Sometimes it's just off a character, other times it's several lines away.

It seems to be more consistently reproducible when jumping between files and jumping to a file that's not already in the "Working Files" area.  Even jumping within a file by repeatedly doing F12, Ctrl-minus will eventually jump to the wrong spot.

This was happening while using the Go plugin with v0.10.1 on Mac OS X 10.10.5

**Comment by bpasero** [comment]
@dlclark the issue is that the action does not add an entry to our history stack. entries are currently only set when you set the cursor +/-5 lines from the last location.

Imho the Editor should provide the history feature and not the workbench from the outside listening to events and then deciding how to navigate.

**Comment by alexandrudima** [comment]
Indeed, we need a HistoryService or NavigationService that each interested party can participate in (e.g. the find widget, the go to definition contrib)

**Comment by Tyriar** [comment]
I use back/forward pretty heavily and find the 5 line rule frustrating. It would help me a lot if it was smarter and/or configurable when cursor points are added to the history stack. Examples:

- Go to definition should always add a history point, regardless of the relative position of the definition
- Clicking should always add a history point
- Holding down should not trigger a new history point for every line, there should be one at the start and one at the end, where the poiint at the end is based on either the cursor stopping for a period of time or another action being performed.

This is probably possible to implement what I want via an extension but forward/back is already integrated into the core editor.

**Comment by alexandrudima** [comment]
> This is probably possible to implement what I want via an extension but forward/back is already integrated into the core editor.

Not in the editor core:
```
{ "key": "alt+left",              "command": "workbench.action.navigateBack" },
```

**Comment by roblourens** [comment]
Same as #11727 right? Looks like it was fixed over there.
