### ISSUE TITLE
aria-posinset wrong for custom menu

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#62007]
**Environment Details:**
VSCode Version : 1.28.2
OS Version : Win10

Additional Details:
MAS1.3.1,NVDA

**Repro Steps:**
1.Launch Visual Studio code desktop application.
2.Navigate to "Plain Text" of "StatusBar"->Enter "PowerShell" in "Select Language Mode"combobox->Write the PowerShell Code in plain editor->Save the editor.
3.Write powershell code and save the editor.
4.Start screenreader as NVDA
5.Navigate to "More Actions" button and expand it.
6. Observed that screen reader is not reading the correct ordering of selected item.

**Actual:**
When the screen reader focus is on the second item then nvda is reading it as "Close All 1of1"

**Expected:**
When the screen reader focus is on the second item then nvda should read it as "Close All 2of2"

**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
https://microsoft.sharepoint.com/teams/msenable/mas/Pages/browse-fixes.aspx

**User Impact:**
If the screen reader is not reading the order correct then user will not understand what number of item get selected by the user also expanded button contains how many number of items.

**MAS Reference:**
MAS1.3.1-https://microsoft.sharepoint.com/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc=%7B54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4%7D

Attachment For References:
![image](https://user-images.githubusercontent.com/39204909/47633104-bab55200-db72-11e8-93d0-c3c5aa7b27dc.png)

Do this issue occur when all extensions are disable?: Yes

**Comment by isidorn** [comment]
Seems like the `posinset` property is off in the custom menu
forwarding to @sbatten let me know if you need help here, but I would just check the https://www.w3.org/TR/wai-aria-1.1/#aria-posinset
