### ISSUE TITLE
Permissions issue with Angular CLI for Mac.

### ISSUE THREAD

**Issue by robertbglaser** [Microsoft/vscode#62001]
This issue is similar to issue #58881 but that issue is for Windows and this issue that I am reporting is for a mac.
 

- VSCode Version: 1.28.2
- OS Version: Mac Mojave 10.14

Steps to Reproduce:

1. Use the Angular CLI to create a new project
2. Navigate to the project src -> app directory.
3. Edit any file and then save the file.
4. See the following message:
    Failed to save 'XXXXX.ts': Insufficient permissions. Select 'Retry as Admin' to retry as administrator.
Select Retry as Admin to save the file.

Yes, I followed your instructions on how to update the path for VS Code but that did not help.  Spent hours on a Sunday trying to fix this issue.

*** Did the same thing with Create-React-app without any issue.

**Comment by bpasero** [comment]
This sounds like a configuration issue with your OS.
