### ISSUE TITLE
Any methods to support locating search results quickly?

### ISSUE THREAD

**Issue by ChenghaoZHU** [Microsoft/vscode#62006]
Take an example, I have one piece of text containing 50 occurrences of world 'hello'. Are there any method to locate the 15th 'hello' directly. Now I just keep pressing next button repeatedly.

**Comment by weinand** [comment]
If you search via the search viewlet, all occurrences are listed and you can directly go to individual matches:

![2018-10-29_12-13-11](https://user-images.githubusercontent.com/1898161/47646434-31068400-db74-11e8-804d-9aa60ba78c9e.png)

**Comment by ChenghaoZHU** [comment]
@weinand Thanks. But I thought it could be something like 'hello:20' to finish the job.
