### ISSUE TITLE
Predominant axis scrolling

### ISSUE THREAD

**Issue by gubikmic** [microsoft/vscode#62003]
It would be nice if there was an option to scroll only the predominant axis.
This is a standard feature of NSScrollView on macOS.
UX-wise you usually scroll vertically but of course on a trackpad deltaX will not be exactly zero, so it happens quite easily that the leftmost characters get clipped.

With predominant axis scrolling only the bigger delta gets applied, and mostly vertical scrolling is strictly just vertical without any stray x-position change.

**Comment by cleidigh** [comment]
@gubikmic 
Just to clarify some more:

The idea is essentially have a mood where dragging a finger when this mode is on would ignore "finger wander" and only react to the main access let's see vertical.  Specifically, even if you moved your finger
diagonally at 45 degrees, only the vertical component would be relevant and cause only vertical scrolling.
(same idea for horizontal if that is the primary access)

Is the above correct?

**Comment by gubikmic** [comment]
Correct, it's for ignoring "finger wander" as you say. But 45 degrees is the edge case.
This would be one setting only.

Examples:
If user scrolls mostly up but also left by a little bit → results in scrolling just up
If user scrolls mostly to the right but also up by a little bit → results in scrolling just right

If you're on a Mac with trackpad you can try by opening a large page in Safari or just zooming in a lot on this one. It's the default setting. You scroll vertically and even though there's always a small sideways scroll when using a trackpad, it's being ignored.
I think it's a good default setting for anything centered around text (as opposed to maps or graphics).
