### ISSUE TITLE
Esc in custom menu moves focus to window

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [Microsoft/vscode#62008]
**Environment Details:**
VSCode Version : 1.28.2
OS Version : Win10

Additional Details:
MAS1.3.1,NVDA

**Repro Steps:**
1.Launch Visual Studio code desktop application.
2.Navigate to "Plain Text" of "StatusBar"->Enter "PowerShell" in "Select Language Mode"combobox->Write the PowerShell Code in plain editor->Save the editor.
3.Write powershell code and save the editor.
4.Using keyboard navigate to "More Actions" button expand it by clicking on enter key
5. Observed that after pressing esc key then keyboard focus moves to "File" button.

**Actual:**
After pressing esc key then keyboard focus is moving on "File" button.

**Expected:**
After pressing esc key the keyboard focus should remains on the same button i.e on "More Actions" button it should not move to "File" button.

**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
https://microsoft.sharepoint.com/teams/msenable/mas/Pages/browse-fixes.aspx

**User Impact:**
After pressing esc key if the focus is not remains on the same control then user have to navigate all the control to reach at "More Actions" button.

**MAS Reference:**
MAS2.1.1:https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={8492c4eb-c179-40ae-8777-cd044ed725a2}

**Attachment For References:**
[A11y_PowerShellEditorServices_Editor_Keyboard.pptx](https://github.com/Microsoft/vscode/files/2524144/A11y_PowerShellEditorServices_Editor_Keyboard.pptx)

Do this issue occur when all extensions are disable?: Yes

**Comment by isidorn** [comment]
This one is about esc moving focus to the main window, it should stay on the element that had the focus before the custom menu opened imho. Forwarding to @sbatten
