### ISSUE TITLE
Optional parameters cause Intelisense to fail to index an object in some cases.

### ISSUE THREAD

**Issue by DrAwesome4333** [Microsoft/vscode#62013]
Issue Type: <b>Bug</b>

Full Description: I have defined an object in JavaScript embeded in a HTML document. In this object I have defined two functions. the first just returns a value based on some input, the second has 2 parameters, one of which is optional and has the defualt value set to the return value of the first function. This causes Intelisense to be unable to define any property of the parent object outside of the object, displaying the parent object as "var SomeObject: any" when hovered over any instance of the name.

Steps to Reproduce:
1. Create an HTML document with a html, body, and script tag nested within each other (Ensure VS Code knows this is an HTML document).
```HTML
<html>
    <body>
        <script>
         
        </script>
    </body>
</html>
```
2. Create an Object that has 2 properties that are simple functions that work independently of each other.
```HTML
<html>
    <body>
        <script>
            var SomeObject = {
                SomeFunction:function(SomeInput){
                    return SomeInput*2;
                },
                SomeOtherFunction:function(SomeOtherInput,SomeMoreInput){
                    return SomeOtherInput * SomeMoreInput;
                }
            };
        </script>
    </body>
</html>
```
3. Notice how Intelisense works properly for the object when typing its name giving helpful assistance when referencing the functions within the object.
![screenshot 43](https://user-images.githubusercontent.com/22409322/47634709-10a8dc00-db18-11e8-87d7-8576729bbfbc.png)
![screenshot 45](https://user-images.githubusercontent.com/22409322/47634728-26b69c80-db18-11e8-8991-eeb80baf53df.png)

4.  Change the second function to have an optional parameter that calls the other function.
```HTML
<html>
    <body>
        <script>
            var SomeObject = {
                SomeFunction:function(SomeInput){
                    return SomeInput*2;
                },
                SomeOtherFunction:function(SomeOtherInput,SomeOptionalInput=SomeObject.SomeFunction(2)){
                    return SomeOtherInput * SomeOptionalInput;
                }
            };
        </script>
    </body>
</html>
```
5. Notice how Intelisense no longer gives suggestions or help past the typing of the object name. Also notice how hovering over the object name now displays "var Objectname: any" instead of showing the properties inside brackets.
![screenshot 46](https://user-images.githubusercontent.com/22409322/47634767-43eb6b00-db18-11e8-93c5-35a5ffbe828f.png)
![screenshot 44](https://user-images.githubusercontent.com/22409322/47634784-51a0f080-db18-11e8-8843-3b8e6e981f42.png)

What I would expect:
I would expect that Intelisense would still provide information about the object, and when displaying the parameters of SomeOtherFunction, simply display the second parameter as either type any or the return type (in this case number) of the referenced function. This issue renders Intelisense much less useful when referencing these objects as it will only suggest the name of the object and then suggest a random list of properties (many of which will not relate to the parent object).

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.96GB (6.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
debugger-for-chrome|msj|4.10.2

</details>

**Comment by aeschli** [comment]
Probably needs to be forwarded to the typescript team.

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/28210 to track this upstream
