### ISSUE TITLE
Rename directory does not auto update imported path

### ISSUE THREAD

**Issue by sevenryze** [Microsoft/vscode#62018]
Issue Type: <b>Bug</b>

```ts
/folder/test.ts:
export function test(){}

index.ts:
import { test } from "./folder/test"
```

Then, hit f2 to rename `folder` to `folder-1` should update the imported path in index.ts automatically, which sadly not.

I find some issues in typescript repo said this feature already has been supported, so i think this is a bug.

P.S. Typescript version: latest typescript@next. 

VS Code version: Code - Insiders 1.29.0-insider (4626bc0e1b679d555dd6f034ece35ffc394b3bb7, 2018-10-29T06:18:55.850Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.86GB (4.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details>Extensions: none

**Comment by mjbvz** [comment]
Do you have a tsconfig in the workspace?

**Comment by sevenryze** [comment]
Yes, below is my tsconfig content:
```ts
{
  "compilerOptions": {
    "module": "esnext",
    "moduleResolution": "node",
    "target": "esnext",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "sourceMap": true,
    "removeComments": true,
    "strict": true,
    "alwaysStrict": true
  }
}
```

**Comment by sevenryze** [comment]
So, any update here? do you need more information to diagnose?
