### ISSUE TITLE
Formatting selection - something is wrong with key pattern

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/vscode#62012]
I see this in Preferences => keyboard shortcuts:

<img width="1264" alt="screenshot 2018-10-29 00 08 54" src="https://user-images.githubusercontent.com/11139560/47634481-ed2d6380-db0e-11e8-80ac-2c57fee4434b.png">

What exactly is:

`
cmd+K+cmd+F
`

I am confused. Seems buggy docs?

**Comment by weinand** [comment]
this is a "chord", first press cmd-k then cmd-f
