### ISSUE TITLE
Slows down on opening large Repos

### ISSUE THREAD

**Issue by SarathSantoshDamaraju** [Microsoft/vscode#62010]
Issue Type: <b>Performance Issue</b>

 VS code lags and slowing down system after opening any larger repos.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   16	   115	  2023	code main
    0	    66	  2024	   gpu-process
    0	   246	  2025	   window (package.json — boilerplate)
    0	     0	  2252	     /bin/bash -l
    0	    98	  2304	     extensionHost
    0	    49	  2492	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=2304
    0	    49	  2509	       electron_node server.js 
    0	    49	  2530	       /Users/sarathd/.vscode/extensions/ms-vsliveshare.vsliveshare-0.3.869/dotnet_modules/vsls-agent --autoexit --pipe 349cf620e95948b0ad98f5ffd8fbcca3 --service https://insiders.liveshare.vsengsaas.visualstudio.com/
    0	    49	  2321	     watcherService
    0	    49	  2493	     searchService
    0	    82	  2489	   shared-process
    0	    82	  2544	   window (Issue Reporter)
    0	     0	  2546	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (package.json — boilerplate)
|    Folder (boilerplate): 498 files
|      File types: h(210) pak(162) plist(16) png(16) js(15) modulemap(9)
|                  dylib(6) bin(6) json(5) placeholder(4)
|      Conf files: package.json(2) grunt.js(1);
```

</details>
<details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
css-minify|Die|0.1.10
minify|Hoo|0.3.0
Bookmarks|ale|9.1.0
gitlens|eam|8.5.6
prettier-vscode|esb|1.6.1
vscode-semistandard-format|hom|0.0.9
beautify|Hoo|1.4.7
python|ms-|2018.9.1
vsliveshare|ms-|0.3.869
vscode-css-peek|pra|2.1.0
vscode-icons|rob|7.27.0
stylelint|shi|0.44.0

</details>

**Comment by weinand** [comment]
It is possible that this issue is caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by SarathSantoshDamaraju** [comment]
Yes it is working after disabling the plugins, I just use 10 plugins and i need a few of them while working and disabling them is a little annoying. So, I will dig a little deeper and find which plugin is causing and raise a PR in the respective repo. But i feel, VS code should handle it nevertheless or show a notification about slow plugin (maybe)
