### ISSUE TITLE
How to cancel multi-cursor using keyboard shortcut?

### ISSUE THREAD

**Issue by thu-jw** [Microsoft/vscode#62039]
When I'm writing ```\begin{}\end{}``` in LaTeX, the multi-cursor function is invoked automatically. I want to cancel multi-cursor using keyboard shortcut, could anyone tell me the method?

Best Regard,
Williams

**Comment by alexandrudima** [comment]
You can press Escape to leave multicursor mode or remove the snippet or simply not use the snippet that brings you to multicursor mode.
