### ISSUE TITLE
files.associations stop accepting wildcard

### ISSUE THREAD

**Issue by FernandoMiguel** [Microsoft/vscode#62030]
Issue Type: <b>Bug</b>
Until today, using a files.associations with a wildcard, would include all files covered by it.
After updating to todays latest nightly release, that seems to fail.

    "files.associations": {
        "Dockerfile-*": "dockerfile",
        "*.yml.*": "yaml",
        "*.tpl": "shellscript",
    },

For example, a file called `Dockerfile-nginx` will be open as Plain Text

VS Code version: Code - Insiders 1.29.0-insider (4626bc0e1b679d555dd6f034ece35ffc394b3bb7, 2018-10-29T06:11:45.152Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.40GB free)|
|Process Argv|-psn_0_1524084|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
spellright|ban|3.0.6
vscode-icontheme-nomo-dark|be5|1.3.6
gitlens|eam|8.5.6
mdhelper|jos|0.0.11
terraform|mau|1.3.7
prettify-json|moh|0.0.3
vscode-docker|Pet|0.3.1
material-icon-theme|PKi|3.6.0
vscode-icons|rob|7.27.0
vscode-nginx|sha|0.5.0
sort-lines|Tyr|1.7.0

</details>

**Comment by kernhanda** [comment]
@alexandrudima I can still repro this issue with the latest code-insiders release.

Version: 1.29.0-insider
Commit: 97ad72a02c351d6cde0fd32b41d9700a43e5964a
Date: 2018-10-31T06:13:36.475Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
