### ISSUE TITLE
search count badge jumps

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#62031]
* have a search result
* resize the sidebar
* 🐛 the count badge jumps at one point

![oct-29-2018 12-11-08](https://user-images.githubusercontent.com/1794099/47646337-eb49bb80-db73-11e8-952c-5ac349d1d84d.gif)

**Comment by roblourens** [comment]
This is by design, because it doesn't look good when the view is very wide, like in the panel, and the numbers are on the right side far from the content. Problems does the same. The threshold could be tweaked maybe? Why does it look like a bug to you?

**Comment by jrieken** [comment]
> Why does it look like a bug to you?

Because it looks like screen cheese. It also messes with usability and readability - glancing over groups or selecting inline actions is really hard when things are at varying positions. It is also super inconsistent with the SCM viewlet, its own title buttons, with explorer decorations etc etc

**Comment by roblourens** [comment]
I will change the "wide" threshold from 600 to 1000.

Or, I can change it to always align left when in the panel and always right when in the sidebar. But I wanted to avoid that because either one can be narrow or wide and the view shouldn't have to know where it is.
