### ISSUE TITLE
VSCode does not terminate Node JS on close

### ISSUE THREAD

**Issue by neilyoung** [Microsoft/vscode#62040]
- VSCode Version: 1.28.2
- OS Version: macOS Mojave

Steps to Reproduce:

1. Launch debugger for Node JS app
2. Close Code
3. Reopen Code
4. Restart debugging node js
5. You'll find the server port already allocated, since the old instance is still running

Does this issue occur when all extensions are disabled?: don't know.

**Comment by isidorn** [comment]
Thanks for nice steps, however this is fixed in latest vscode insiders (I pushed a fix around 2 weeks ago).
Can you please try with vscode inisders and let us know if you still see it https://code.visualstudio.com/insiders/

**Comment by neilyoung** [comment]
Confirmed. Gone with October update of "ordinary" Code :) Thanks

**Comment by isidorn** [comment]
Thanks
