### ISSUE TITLE
Terminal returns exit code zero on non-Windows even if execution was interrupted

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#62043]
See #58828 for more discussion.

If a process is sent SIGTERM for example then what should the exit code from the terminal be?

**Comment by jerch** [comment]
@alexr00 Maybe go with typical shell semantics on POSIX systems? For more info see this thread & answer https://unix.stackexchange.com/a/99143

**Comment by Tyriar** [comment]
@alexr00 I think we were just talking in another issue about changing onExit to give tasks undefined, closing in favor of that.
