### ISSUE TITLE
Integrated Terminal closes immediately upon opening

### ISSUE THREAD

**Issue by tsengsational** [Microsoft/vscode#62041]
Issue Type: <b>Bug</b>

When integrated terminal is open, it immediately closes.

1. Open VSCode
2. Select "View" > "Terminal"

No errors logged in Developer Tools console.

See screen recording for behavior:
https://drive.google.com/open?id=1uBa3EJlcLTFpySKyhDysMLjcih8KOO8G

VS Code version: Code - Insiders 1.29.0-insider (4626bc0e1b679d555dd6f034ece35ffc394b3bb7, 2018-10-29T06:11:45.152Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by Tyriar** [comment]
Is this a personal machine or managed by your org? Also what's `$SHELL` set to and what's in your settings.json file?

**Comment by caiceA** [comment]
> https://drive.google.com/open?id=1uBa3EJlcLTFpySKyhDysMLjcih8KOO8G

@tsengsational  did you solve it ? i am having the same issue

**Comment by Tyriar** [comment]
@caiceA please answer the questions above, your `$SHELL` is probably bad.

**Comment by caiceA** [comment]
> @caiceA please answer the questions above, your `$SHELL` is probably bad.

@Tyriar i changed my Shell to this and its working fine now



<img width="644" alt="screenshot 2018-12-27 at 12 57 42" src="https://user-images.githubusercontent.com/16766231/50479475-1c5d3580-09d7-11e9-8d84-bbdf2eabf1f4.png">

**Comment by caiceA** [comment]
@Tyriar what i should do now ? to change the setting?

**Comment by Tyriar** [comment]
@caiceA just changing the setting will work, having SHELL as a bad value is unrelated to VS Code, likely due to your enterprise setup or shell startup scripts.

**Comment by caiceA** [comment]
this is the ouput of echo $SHELL
/bin/bash

**Comment by Tyriar** [comment]
Can you run `/bin/bash` in the default mac terminal?
