### ISSUE TITLE
After executing the npm install command and in an open project, the editor loads the processor 100%

### ISSUE THREAD

**Issue by hazratgs** [microsoft/vscode#62042]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. npm i
2. show monitoring cpu

Does this issue occur when all extensions are disabled?: Yes/No

https://www.youtube.com/watch?v=8K6jh8Jz7vA&feature=youtu.be

recorded a video where you can see how it happens, the problem is in installing dependencies of the application, and so the editor reacts to any application when installing dependencies

MacOS Seirra
node 10.12
npm 6.4.1

**Comment by weinand** [comment]
How should we reproduce this?
Please follow our issue reporting guideline:
https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#reporting-issues.

**Comment by kieferrm** [comment]
@hazratgs thanks for creating the video. Can you please run `code -status` when the CPU usage is high? Thanks!

**Comment by hazratgs** [comment]
> @hazratgs thanks for creating the video. Can you please run `code -status` when the CPU usage is high? Thanks!

nothing
https://www.youtube.com/watch?v=ktW68Xu7nwM&feature=youtu.be

**Comment by hazratgs** [comment]
Dear developers, you know the reason for this behavior? It seems to me that this is not about the editor, but rather a npm bug.

**Comment by chrmarti** [comment]
@hazratgs Which version of VS Code is this? `--status` needs to dashes: `code --status`.

**Comment by hazratgs** [comment]
> code --status

version 1.29.0 (1.29.0)
5f24c93878bd4bc645a4a17c620e2487b11005f9

command code --status not work!

**Comment by chrmarti** [comment]
Closing as obsolete. This should work in the latest release, let me know if it does not.
