### ISSUE TITLE
Different color scheme for references modal

### ISSUE THREAD

**Issue by ashutoshraina** [Microsoft/vscode#6204]
- VSCode Version: Version 1.0.0 (1.0.0)
- OS Version: Mac OSX EL Capitan

When clicking on references the modal has a different theme from the one which  I selected in VS code.

Steps to Reproduce:
1. Change the theme to something other than the default.
2. Click on References and the modal has a different color scheme.

**Comment by bpasero** [comment]
@ashutoshraina can you attach a screen shot?

**Comment by ashutoshraina** [comment]
![vscode modal - color scheme issue](https://cloud.githubusercontent.com/assets/1003532/15105218/77c14466-15dd-11e6-8905-914c289d2bfc.png)


The two color schemes are different. If there is a setting which allows the user to set the scheme for the modal as well, the that should be ok as well.

**Comment by jrieken** [comment]
I believe that's a UX decision.

**Comment by bgashler1** [comment]
@ashutoshraina, are you referring to the dark-blue background color and the light blue outline colors of the modal?

**Comment by ashutoshraina** [comment]
Yes, that is the issue. I was hoping for the modal to pick up the same scheme. The change in background colour is jarring.

**Comment by stevencl** [comment]
We intentionally designed the peek window to have a different background to the main editor. That way people can easily distinguish it from the editor when they are scrolling through the file.

In earlier designs we investigated what the experience would be like if the background to the peek window wasthe same as the background of the editor. What we found was that when the peek window was scrolled out of view, perhaps when somebody needs to scroll to the bottom of a file to browse some code, it was more difficult to get back to the peek window by quickly scrolling back through the file as it is not so easy to identify the peek window when it has the same background as the rest of the editor.

**Comment by bgashler1** [comment]
@ashutoshraina, it seems your frustration is not that the background color is different but that it's always blue no matter what theme you are using.  For example, if you were to be using a warmer theme where no blues are used, then the blueish peek window (as it is currently) would stand out too much from the rest of theme.  Is that correct?

**Comment by ashutoshraina** [comment]
@bgashler1 yes, that is correct.
As long as there is way for us to configure what theme the modal should have we should be OK.

**Comment by isidorn** [comment]
Not sure if this is themeable, assigning to @bpasero and @aeschli to groom this

**Comment by aeschli** [comment]
Yes, the peek view is now fully themable:
See https://code.visualstudio.com/docs/getstarted/theme-color-reference#_peek-view-colors
