### ISSUE TITLE
October Endgame

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#62045]
- *October/29* Code freeze for the endgame
- *November/2* [Endgame done](https://github.com/Microsoft/vscode/wiki/Development-Process#inside-an-iteration)

> **Note:** The `Insiders` build needs to be in the wild for 24 hours before we can enter the last phase of the endgame.

##### Monday
- [x] Run [OSS tool](https://github.com/Microsoft/vscode-distro/blob/master/distro-tools/README.md) **endgame master**
  - *The LCA review of the ThirdPartyNotices.txt files is not needed anymore*
- [x] Code freeze at 5pm PT
- [x] Ensure we have a green build on all platforms at 5pm PT
- [x] All test items contain sufficiently comprehensive test descriptions by 6pm PT
- [x] Update your availability for testing here - https://vscode-tools.azurewebsites.net/

##### Tuesday
- [x] Test plan items assigned (using https://vscode-tools.azurewebsites.net/)
  - Run the tool multiple times to balance load if test items come in later and assignments are already made
- [x] All closed feature-requests either have a verification-needed or on-testplan tag
- [x] Test build starts at 7am CET
- [x] Test plan ready by 8am CET
- [x] Testing
- [x] [Verification needed](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+-label%3Averified+is%3Aclosed+label%3Averification-needed)

##### Wednesday
- [x] Testing
- [x] Remind team members to assign issues that they intend to fix to the current milestone
- [x] Fixing (self-assigned, milestone assigned)
- [x] [Verification (pls update the milestone in the query)](https://github.com/Microsoft/vscode/issues?utf8=✓&q=is%3Aissue+label%3Abug+-label%3Averified+-label%3Aon-testplan+is%3Aclosed+-label%3Aerror-telemetry+-label%3Aduplicate+-label%3A*duplicate+-label%3Ainvalid+-label%3Aas-designed+milestone%3A%22October+2018%22+)

##### Thursday
- [x] Fixing (scrutiny sets in - major bugs only - to be discussed in stand-up meeting, labeled as `candidate`)
- [x] [Verification](https://github.com/Microsoft/vscode/issues?utf8=✓&q=is%3Aissue+label%3Abug+-label%3Averified+-label%3Aon-testplan+is%3Aclosed+-label%3Aerror-telemetry+-label%3Aduplicate+-label%3A*duplicate+-label%3Ainvalid+-label%3Aas-designed+milestone%3A%22October+2018%22+)
- [x] Check new OSS usage is entered into the [OSS registry](https://ossmsft.visualstudio.com/_apps/hub/ms.vss-oss-web.hub-oss) **owner**

##### Friday
- [x] Pause scheduled `insider` builds **endgame master**
- Satellite modules/npm packages ready, version updated, smoke tested
  - [x] vscode **@bpasero**
  - [x] yo generator **@aeschli**
  - [x] vsce **@joaomoreno**
  - [x] node debug **@weinand**
  - [x] node debug2 **@roblourens**
  - [x] node debugadapter node **@weinand**
  - [x] debug adapter protocol **@weinand**
- [ ] All issues [verified](https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Abug+-label%3Averified+-label%3Aon-testplan+is%3Aclosed+-label%3Aerror-telemetry+-label%3Aduplicate+-label%3A*duplicate+-label%3Ainvalid+-label%3Aas-designed+milestone%3A%22October+2018%22+)
- [x] Fixing (only critical bugs - no string changes)
- [x] [Smoketest](https://github.com/Microsoft/vscode/wiki/Smoke-Test)
  - [x] Windows - @alexr00 
  - [x] OS X - @weinand 
  - [x] Linux - @joaomoreno 
- [ ] All release notes updated
  - release notes are collected in a file named *`Month_Year.md`* in this [repo directory](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/)
  - [x] @aeschli
  - [x] @alexandrudima
  - [x] @alexr00
  - [x] @bpasero
  - [x] @chrmarti
  - [x] @dbaeumer
  - [x] @egamma
  - [x] @isidorn
  - [x] @joaomoreno
  - [x] @jrieken
  - [x] @kieferrm
  - [x] @mjbvz
  - [x] @octref
  - [x] @ramya-rao-a
  - [x] @rebornix 
  - [x] @rmacfarlane
  - [x] @roblourens
  - [x] @sandy081
  - [ ] @sbatten
  - [x] @tyriar
  - [x] @weinand
- [ ] Acknowledge pull requests in release notes. We acknowledge PRs from outside the team. Use the [thankyou](https://vscode-tools.azurewebsites.net/#acknowledgePRs) tool to generate the initial contents of the section. **owner**
  - [x] vscode **endgame master**
  - [x] vscode-node-debug **@weinand**
  - [x] vscode-node-debug2 **@roblourens**
  - [x] vscode-debugadapter-node **@weinand**
  - [x] debug-adapter-protocol **@weinand**
  - [x] vscode-languageserver-node **@dbaeumer**
  - [x] language-server-protocol **@dbaeumer**
  - [x] vscode-textmate **@alexandrudima**
  - [x] vscode-loader **@alexandrudima**
  - [x] vscode-generator-code **@aeschli**
  - [x] vscode-vsce **@joaomoreno**
  - [ ] vscode-docs **@gregvanl**
  - [x] vscode-css-languageservice **@alexr00**
  - [x] vscode-json-languageservice **@alexr00**
  - [x] vscode-html-languageservice **@alexr00**
  - [x] jsonc-parser **@aeschli**
  - [x] vscode-jscs **@chrisdias**
  - [x] vscode-tslint **@egamma**
  - [x] vscode-eslint **@dbaeumer**
  - [x] vscode-jshint **@rmacfarlane**
  - [ ] vscode-recipes **@auchenberg**
  - [x] localization **@danyeh**
  - [x] vscode-github-issues-prs **@chrmarti**
  - [x] inno-updater **@joaomoreno**
- [ ] Add notable fixes to the release notes **all**
- When done fixing/verifying and there are changes since last build at the end of day PT
  - [ ] Trigger new insider build and publish it manually **endgame master**
- [x] Let Daniel Ye know that the release branch `release/<x.y>` got created and that translation should be pulled from there and that the pull request has to be created against that branch **endgame master**

##### Friday/Monday
- [x] Branch code to `release/<x.y> **endgame master**
- [x] Bump up the version in package.json - **endgame master**
- [x] Announce master is open for business **endgame master**
- [x] Polish release notes **redmond**

##### Monday - Wednesday
- [ ] [Smoketest](https://github.com/Microsoft/vscode/wiki/Smoke-Test)
  - [x] Windows - @alexr00 
  - [x] OS X - @sandy081 
  - [x] Linux - @joaomoreno 
- [x] Polish release notes **redmond**
- [x] Cherry-pick hand-picked and reviewed changes to `release/<x.y>` **endgame master**
- [x] Build `Insider` from `release/<x.y>` **endgame master**
- [x] Manually release `Insider` **endgame master**
- [x] Build stable for all platforms as new candidate issues come in **endgame master**
- [x] Documentation updated
  - [ ] @aeschli
  - [ ] @alexandrudima
  - [x] @alexr00
  - [ ] @bpasero
  - [ ] @chrmarti
  - [x] @dbaeumer
  - [x] @egamma
  - [ ] @isidorn
  - [x] @joaomoreno
  - [ ] @jrieken
  - [x] @kieferrm
  - [ ] @mjbvz
  - [x] @octref
  - [x] @ramya-rao-a
  - [x] @rebornix 
  - [ ] @rmacfarlane
  - [x] @roblourens
  - [ ] @sandy081
  - [ ] @sbatten
  - [x] @tyriar
  - [x] @weinand

> **Note:** The `Insiders` build needs to be in the wild for 24 hours before we can enter the last phase of the endgame.

##### Tentatively: Monday Nov 12th
- [x] Build stable for all platforms **endgame master**
- [x] Make [rpm signing request](https://github.com/Microsoft/vscode-distro/blob/master/linux-repo/README.md) **@rmacfarlane**
- [x] Sanity check of installable bits
  - [ ] Windows
    - [x] signed installer 32-bit **owner**
    - [x] signed installer 64-bit **owner**
    - [x] signed user installer 32-bit **owner**
    - [x] signed user installer 64-bit **owner**
    - [x] zip 32-bit **owner**
    - [x] zip 64-bit **owner**
  - [x] OS X - **owner**
  - [x] Linux
    - [x] deb package 32-bit **owner**
    - [x] deb package 64-bit **owner**
    - [x] rpm package 64-bit **owner**
    - [x] rpm package 32-bit **owner**
    - [x] archives **owner**
- [x] Publish website **@gregvanl**
- [ ] Publish to stable **endgame master**
- [x] Add a git tag to `HEAD` of `release/<x.y>` in format `x.y.z` (for vscode.d.ts download)  **endgame master**
- [ ] Publish deb and rpms to repositories manually **@rmacfarlane**
- [x] Enable scheduled `insider` builds **endgame master**
- [x] Twitter announcement **@auchenberg**

**Comment by WizardCM** [comment]
Things have been pretty quiet here - what's the latest?

**Comment by anthcool** [comment]
> Things have been pretty quiet here - what's the latest?

My guess is they abandoned us for:  [https://www.pass.org/summit/2018/Live.aspx](url) to support their Azure Data Studio home-skillets.

**Comment by chrmarti** [comment]
> Things have been pretty quiet here - what's the latest?

We will hold back a release if we need additional time to squash an important bug. This is such a case. Stay tuned.

**Comment by connorshea** [comment]
Thanks for all your work ❤️
