### ISSUE TITLE
editor.wordBasedSuggestions completes in string literals

### ISSUE THREAD

**Issue by safield** [Microsoft/vscode#62047]
VSCode, in the absence of any installed extensions, offers word based suggestions out of the box. I would like a setting to enable word suggestions to work when typing in a string literal.

A setting like "editor.WordBasedSuggestionsInStringLiteral" or whatever is most sensible.

This behaviour is independent of any extension language support. It works with a base install of vscode.

Observe the following example. The behaviour was tested in a base install of vscode, in a Java , c#, and c++ source file.

int foo = 0;
fo // type fo and completion suggestion for foo is suggested.
"fo" // type "fo" and no completion suggestion is added.

Word based suggestions in string literals is the default behaviour in editors like Vim and Sublime.

**Comment by jrieken** [comment]
@safield did you try `"editor.wordBasedSuggestions": true` and/or `"editor.quickSuggestions": {
    "other": true,
    "comments": false,
    "strings": true
  },?

**Comment by safield** [comment]
"editor.quickSuggestions": { "other": true, "comments": false, "strings": true }

is the exact settings I was looking for.  Thanks.

Close issue.
