### ISSUE TITLE
Make us able to create sidebar extensions, with their own icon

### ISSUE THREAD

**Issue by GabrielBB** [Microsoft/vscode#62051]
I would like to make an extension and have its own icon in the left sidebar. Just like this:

![image](https://user-images.githubusercontent.com/8752823/47660006-863e9780-db6c-11e8-8596-54acb0e16042.png)

I want to do some type of search, similar to the extension search.

**Comment by kieferrm** [comment]
This already exists: 
https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesviewscontainers
