### ISSUE TITLE
node typescript build task not found with multiroot workspace

### ISSUE THREAD

**Issue by cazfletch** [Microsoft/vscode#62055]
When you have a multiroot workspace with a typescript and javascript project and try and debug the typescript project the build step fails.

- VSCode Version: 1.28.2
- OS Version: Mac OS

Steps to Reproduce:

1. Have a workspace with a typescript project and javascript project
2. open a typescript file and press f5 to debug
3. an error will pop up saying that the prelaunch task `tsc: build - tsconfig.json` can't be found

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
I can't repo this is a simple workspace with the following launch and tasks.json:

![Screen Shot 2019-04-12 at 3 02 19 PM](https://user-images.githubusercontent.com/12821956/56068518-ff553400-5d33-11e9-9a43-109a2bcb96ff.png)

If you still see this, please share your `launch.json` and `tasks.json` (or even better, a small example workspace)
