### ISSUE TITLE
option to enable saving documents in .txt format by default

### ISSUE THREAD

**Issue by dadapotok** [Microsoft/vscode#62054]
option to enable saving documents in .txt format by default

will be handy for those who writes .txt notes and opens them using text editors on other devices

**Comment by mstenemo** [comment]
> @dadapotok
> When you create a new file it gets labeled Untitled-x where X is the number of the untitled file incremented for each new file. The default is "Plaintext" as shown in the status bar. If you use
> the command "Save File" you will see the extension defaults to ".txt" but without having to change anything. If you use the command "Change Language Mode" while viewing a currently untitled/undefined language, when you go to save the file the appropriate extension will be set in the Save File dialog.

How does the extension change this setting? I am using https://github.com/Ikuyadeu/vscode-R, which currently isn't changing this setting (reported this in https://github.com/Ikuyadeu/vscode-R/issues/95), but I also would like to change the default save as (exist old open issue about this: https://github.com/Microsoft/vscode/issues/28425#issuecomment-443145502)
