### ISSUE TITLE
Result number reset.

### ISSUE THREAD

**Issue by JoseluGallardo** [Microsoft/vscode#62050]
Issue Type: <b>Bug</b>

Hi there guys!

I've realised that the results number is getting reset when change tabs.

**Steps to reproduce:**
-Open document 1.
-Search (Ctrl+F) for a result. It'll show the number of the results. IE: 1/7.
-Go for the next result -> 2/7.
-Change tab to document 2.
-Go back to document 1: The selection won't have changed, but the number will be 1/7 again.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

**Comment by rebornix** [comment]
We don't store the state of the result per document in an editor at this moment.
