### ISSUE TITLE
Git Source Control Explorer: commit message input jumps under the toolbar and gets partially covered

### ISSUE THREAD

**Issue by juristr** [microsoft/vscode#62061]
- VSCode Version: 1.29.0-Insider
- OS Version: MacOS 10.13.6

Steps to Reproduce:

![vscode-git-bug](https://user-images.githubusercontent.com/542458/47662954-3b3c7880-db9c-11e8-85c8-737d4676678d.gif)

The gif shows the behavior. Basically when clicking the item in the "Changes" list, the input box for the git commit message jumps up and gets covered. I wasn't able to properly reproduce this consistently as when closing/reopening VSCode it disappeared. Just wanted to log it here as from now and then this strange behavior pops up.

Does this issue occur when all extensions are disabled?: (Hard to say as restarting VSCode makes it disappear as well)

**Comment by joaomoreno** [comment]
Yup I also saw this and was unable to repro, but I'm sure we can find a way into it

**Comment by juristr** [comment]
@joaomoreno I think we can close this. It didn't happen again on my installation, so I assume it's resolved by now 🙂
