### ISSUE TITLE
Test: Hide SCM commit input box

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#62068]
Related to #51808

- [x] anyOS @RMacfarlane 
- [x] anyOS @isidorn 

Complexity: 2

When authoring an extension which contributes an SCM Provider, one can now hide the SourceControlInputBox from the UI using the `visible` property: https://github.com/Microsoft/vscode/blob/1d55212ec0ff49c9274da54fb775d13126dba5cf/src/vs/vscode.proposed.d.ts#L780

**Comment by isidorn** [comment]
@ThomasNolte this are test plan items which are tested internally by vscode team members. If you would like to contribute look for issues with good-first-issue and help-wanted
