### ISSUE TITLE
Test: Problems panel

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#62063]
Related to #59976

- [x] macOS: @sandy081 
- [x] linux @sbatten 
- [x] windows @alexr00 

Complexity: 4

The Problems panel was heavily refactored to adopt the new [`ObjectTree`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/tree/objectTree.ts). Please completely test the problems panel

- Make sure problems are shown correctly without missing. 
- Make sure the badge shows correct number of problems
- If auto reveal is enabled `problems.autoReveal`, Switching between files should reveal the problems for the current active file.
- Test filtering by typing and also test files exclude filter (`files.exclude`)
- Test Keyboard Navigation: Navigating problems using keyboard (up and down arrows) should select the problem and also reveals it in the file by opening it.
- Test Mouse handling: Expanding and Collapsing, Selection, Double click, Opening file to the right (cmd+click).
- Test scrolling with mouse and also with keyboard.
- Test actions: Light bulb, Collapse All, context menu actions.
- Test accessibility using Voice over / NVDA in Mac / Windows.

You can use following sample to generate problems when active editor is changed

```typescript
const diagnosticsCollection = vscode.languages.createDiagnosticCollection('test');
vscode.window.onDidChangeActiveTextEditor(e => {
    if (e && e.document) {
        const diagnostics: vscode.Diagnostic[] = [];
        const diagnostic = new vscode.Diagnostic(new vscode.Range(new vscode.Position(10, 1), new vscode.Position(10, 10)), `This is an error`, vscode.DiagnosticSeverity.Error);
        diagnostic.source = 'test';
        diagnostic.code = 1234;
        diagnostics.push(diagnostic);
        diagnosticsCollection.set(e.document.uri, diagnostics);
    }
});
```

**Comment by alexr00** [comment]
@joaomoreno, with `problems.autoReveal` should the problems pane show? I'm seeing the badge pop up on PROBLEMS when I switch files, but the problems pane isn't getting switched to.

**Comment by sandy081** [comment]
@alexr00 With auto reveal works only when problems panel is open... just like auto reveal in explorer.
