### ISSUE TITLE
Test: Expose Change resources in git extension API

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#62067]
Related to #60048

- [ ] anyOS @chrmarti 
- [x] anyOS @sbatten 

Complexity: 2

When authoring an extension, one can reach onto the Git extension's API: https://github.com/Microsoft/vscode/blob/master/extensions/git/README.md#api

When there is an open repository, you should be able to reach out to it and get a list of [`Change`](https://github.com/Microsoft/vscode/blob/1d55212ec0ff49c9274da54fb775d13126dba5cf/extensions/git/src/api/git.d.ts#L80:L91) instances when accessing the `mergeChanges`, `indexChanges` and `workingTreeChanges` properties on the Repository.

**Comment by chrmarti** [comment]
Seen all except `INDEX_COPIED`, `IGNORED`, `ADDED_BY_US`, `ADDED_BY_THEM` and `BOTH_DELETED`. Not sure how to get these (if at all) with Git.
