### ISSUE TITLE
PHP validator is picking excluded files/folders

### ISSUE THREAD

**Issue by Mangatt** [Microsoft/vscode#62070]
Even when I have configured ```files.exclude``` properly, PHP validator is still validating them. This pretty much kills usefulness of this feature, because some folders in my workspace contains large number of old, invalid files. And it's almost impossible to find single error among 100+ others.

Oh, and startup performance is in this case really bad as well, since every file is validated on start.

- VSCode Version: 1.28.2
- OS Version: Win 10

**Comment by roblourens** [comment]
Is that from an extension? If so please file an issue on that extension's repo.

**Comment by konradw86** [comment]
Gdzie są te pliki do usunięcia..n

pon., 29.10.2018, 18:33 użytkownik Mangatt <notifications@github.com>
napisał:

**Comment by Mangatt** [comment]
@roblourens I'm sorry, which extension is that? I'm not sure where to file this.

**Comment by Mangatt** [comment]
@konradw86 They are inside workspace folder and can't be moved away.

**Comment by roblourens** [comment]
I was just wondering whether you are using the simple builtin php validation or using an extension for this.

If you are using the builtin validation, you should only see errors when you open the file. It won't crawl your workspace to find files. Is that not what you see?

**Comment by Mangatt** [comment]
@roblourens Yes, built-in validation. There are errors piling up after start-up in unopened files even with `code --disable-extensions`. Apparently VS Code is crawling these files and validating them.

**Comment by Mangatt** [comment]
Ok, there is culprit: https://github.com/felixfbecker/vscode-php-intellisense. This was crawling excluded files, you were right @roblourens . Thanks for your help!
