### ISSUE TITLE
Error every time that a file is searched

### ISSUE THREAD

**Issue by rolurq** [Microsoft/vscode#62071]
```
spawn /usr/share/code/resources/app/extensions/search-rg/node\_modules/vscode-ripgrep/bin/rg ENOENT
```

- VSCode Version: 1.28.2
- OS Version:  Linux 4.18.0-2-amd64 #1 SMP Debian 4.18.10-2 (2018-10-07) x86_64 GNU/Linux

Steps to Reproduce:

1. Open a workspace
2. Use the `Ctrl+P` command to open a file

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Do you have `"searchRipgrep.enable"` set? Do you know why you set it? Does it work if you unset it?

**Comment by rolurq** [comment]
![screenshot 2018-10-29 13 57 01](https://user-images.githubusercontent.com/13684824/47670004-8e093680-db82-11e8-84b4-7aae3709411c.png)
I had it enabled, nevertheless, I disabled it and reload, the problem persists.

**Comment by rolurq** [comment]
The binary in the error exists and it works, I tried it manually from the terminal.

**Comment by roblourens** [comment]
It looks like it's still enabled in the "User" scope. Also make sure you reload after unchecking it. Do you remember why you turned it on in the first place?

"search.useRipgrep" should be turned ON, while "searchRipgrep.enable" should be turned OFF.

Sorry for the confusing naming, it's going away soon 😁

**Comment by roblourens** [comment]
No worries, let me know if you have issues again
