### ISSUE TITLE
git détection

### ISSUE THREAD

**Issue by REQJ** [Microsoft/vscode#62075]
Issue Type: <b>Bug</b>

Git include documents and files to ignored like ".gitignore"... and more
the Git repository in 'C: ...' has too many active changes, only a subset of Git features will be enabled.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.92GB (2.82GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
twig-language-2|mbl|0.3.1
vscode-language-pack-fr|MS-|1.27.2
csharp|ms-|1.16.2
vetur|oct|0.13.0
laravel-blade|one|1.18.0
laravel-artisan|rya|0.0.23
highlight-matching-tag|vin|0.7.1

</details>

**Comment by joaomoreno** [comment]
I don't understand your first issue, can you elaborate?

For the too many changes issue: Run `git rev-parse --show-toplevel` to find out where your git repository root is. If that should not be a git repository, then delete the `.git` folder contained within it.

**Comment by REQJ** [comment]
despite the presence of the gitignore, vscode still includes 'forbidden' files like vendor, node modules, etc ...
Before it worked properly and suddenly it does not work properly (as explained above). All my projects are not concerned.

The command git rev-parse --show-toplevel, show me the path of projects (C:/laragon/www/myProject)

**Comment by joaomoreno** [comment]
> despite the presence of the gitignore, vscode still includes 'forbidden' files like vendor, node modules, etc ...
Before it worked properly and suddenly it does not work properly (as explained above). All my projects are not concerned.

Can you show me a screenshot?

**Comment by REQJ** [comment]
![vs-git-problem](https://user-images.githubusercontent.com/16952934/47811365-e3417580-dd45-11e8-96b5-1a808b44568f.PNG)

**Comment by joaomoreno** [comment]
Can you show me the full exact contents of the `.gitignore` file? Note that you must commit the changes to `.gitignore` for it to work.

**Comment by REQJ** [comment]
Mhhh, the .gitignore file changed the content alone… I've restaured the old content and it's work, but why this content have changed alone .. ? Thanks joaomoreno

**Comment by joaomoreno** [comment]
No clue :thinking: 

Glad to know you're OK now.
