### ISSUE TITLE
Icon-Theme bugged in "Open ..." commands?

### ISSUE THREAD

**Issue by LucaZulberti** [Microsoft/vscode#62078]
Issue Type: <b>Bug</b>

When I click on File>Open File... (or similar) the window opened has a very ugly aspect..
![Image](https://image.ibb.co/eyyx3A/Schermata-da-2018-10-29-20-01-51.png)

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:20:56.183Z)
OS version: Linux x64 4.18.0-10-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 1458)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|4, 4, 4|
|Memory (System)|7.70GB (0.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.5.6
tslint|eg2|1.0.40
fontawesome-autocomplete|Jan|0.1.7
dotenv|mik|1.0.1
python|ms-|2018.9.1
cpptools|ms-|0.19.0
debugger-for-chrome|msj|4.10.2
vscode-docker|Pet|0.3.1

</details>

**Comment by Tyriar** [comment]
It looks like this is related to your display manager, not VS Code.
