### ISSUE TITLE
C# intellisense doesn't show return type

### ISSUE THREAD

**Issue by jchannon** [Microsoft/vscode#6207]
- VSCode Version: 1.0.0
- OS Version: OSX El Capitan

Steps to Reproduce:

1. Using intellisense in C# the output shows the methods available but it does not show the return type of that method.  I think this has been in Omnisharp from day 1 so would be nice to get this in.
2. More info here :  https://twitter.com/jchannon/status/728502404346462208

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#287
