### ISSUE TITLE
TS: no compile error in this case

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#62080]
* open `src/vs/base/node/storage.ts` and go to the `close()` method
* replace the last line of that method with:

```typescript
return always(this.flushDelayer.trigger(() => this.flushPending()), () => this.storage.close());
```
* compile

=> I would expect a compile error because `always` is declared as: `always<T>(promise: Thenable<T>, callback: () => void): Promise<T>` and `this.storage.close()` does not return `void` but `Promise<void>`.

This confused me quite a lot because originally I thought always would also `then` on that promise, but it does not.

**Comment by mjbvz** [comment]
This is by-design, see https://github.com/Microsoft/TypeScript/issues/9603 and linked issues

Currently seems to be tracked here: https://github.com/Microsoft/TypeScript/issues/8584

**Comment by bpasero** [comment]
I commented why I think this is a bug: https://github.com/Microsoft/TypeScript/issues/8584#issuecomment-434180138
