### ISSUE TITLE
Terminal freezes and goes black

### ISSUE THREAD

**Issue by sulavaaa** [Microsoft/vscode#62081]
Issue Type: <b>Bug</b>

Open vscode
Open terminal
Do some stufff 
Now terminal freezes and goes black. VSCode too crashes but recovers. 
Terminal goes black. 

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz (8 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (3.11GB free)|
|Process Argv|C:\Users\somedude\Desktop\SomeoCode-G\SomeApp-G|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.16.2
laravel-blade|one|1.18.0

</details>

**Comment by jrieken** [comment]
> VSCode too crashes but recovers.

@sulavaaa Can you clarify this? Does the render need a reload? Do things freeze for a (long?) moment?

**Comment by Tyriar** [comment]
We need more information in order to be able to repro/action.
