### ISSUE TITLE
PauseRequest not being received by the debugAdapter

### ISSUE THREAD

**Issue by pieandcakes** [Microsoft/vscode#62085]
Issue Type: <b>Bug</b>

In 1.28.2, I'm unable to receive the pauseRequest in the debugAdapter which is causing me to be unable to pauseDebugging.

I've debugged it to the point where i notice that VS Code is not sending the request to the debugAdapter.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (4.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.19.0

</details>

**Comment by pieandcakes** [comment]
I have verified this with both the C# and the C++ extension

**Comment by isidorn** [comment]
@pieandcakes good catch, thanks for reporting it.
It would be great if you self hosted on vscode insiders so we try to catch issues like this earlier.

**Comment by pieandcakes** [comment]
@isidorn I do try and use insiders, but I find I'm mostly using VS since our code is not C++.

**Comment by pieandcakes** [comment]
@weinand I can test it as soon as the build is out.

**Comment by weinand** [comment]
yes, and a new Insiders build appears every weekday.

**Comment by pieandcakes** [comment]
It works again.

Build:
Visual Studio Code - Insiders
Version: 1.29.0-insider (user setup)
Commit: d7ac6e838f51a03f7d417b4758f5fb075878d615
Date: 2018-11-01T06:20:59.729Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by isidorn** [comment]
Thanks for letting us know, adding verified label
