### ISSUE TITLE
Find and Replace key binding no longer working

### ISSUE THREAD

**Issue by dalanskis** [Microsoft/vscode#62084]
- VSCode Version:
1.28.2.
- OS Version:
macOS High Sierra 

I've noticed since last week I lost the find and replace functionality I had been using nearly everyday since using VSCode. Now I can't be totally sure, but i'm pretty certain that the combination was cmd+opt+F to bring up the Find and Replace bars in whatever current window you were working in. Now hitting the combination does nothing.

Steps to Reproduce:

1. Find a word or number that's repeated in your document. 
2. Double click, cmd+option+'F'. (Should open the Find and Replace window in your current document)

Does this issue occur when all extensions are disabled?: Yes

**Comment by kieferrm** [comment]
@dalanskis, the default keybinding is still there. You can verify with **Preferences: Open Default Keyboard Shortcuts File** from the Command Palette.
```json
{ "key": "alt+cmd+f",             "command": "editor.action.startFindReplaceAction" },
```

Please make sure that you don't have any conflicting keybindings, maybe introduced through an extensions. Go to **Preferences: Open Keyboard Shortcuts** from the Command Palette, hit the keyboard icon on the right of the search input box, type <kbd>Alt</kbd>+<kbd>Cmd</kbd>+<kbd>f</kbd> and it should only show the default binding.

**Comment by dalanskis** [comment]
@kieferrm, When I go to Keyboard Shortcuts and record my keybinding of Alt+Cmd+F, it records it as if I typed 'alt+cmd+' everytime. I know that my 'F' key works fine, so i'm not sure why it's not registering it when enter there. I do see some duplicates of some keybindings already in there like 'Replace' and 'Save all', which may or may not be related. Attaching a screenshot of duplicates:

![screen shot 2018-10-30 at 8 31 44 am](https://user-images.githubusercontent.com/10092006/47718242-4b953780-dc1e-11e8-8cea-3433fa8b3ff6.png)
