### ISSUE TITLE
Test JSON warning in status bar when schema can not be resolved

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#62087]
Tests #60219

- [x] any os @weinand (macOS)
- [x] any os @sandy081 

Complexity: 2

- open a JSON file and associate a schema
- go offline, or change the schema to an unresolvable location
- instead of an error/warning there's now a warning symbol in the status line. Clicking on the icon tries to reload.

**Comment by xxyy** [comment]
Generally, I'd love to, but I really can't get this done by tomorrow, sorry!

**Comment by octref** [comment]
OK, I'll push fixes.
