### ISSUE TITLE
Maximize panel causes left panel to shrink

### ISSUE THREAD

**Issue by calvn** [microsoft/vscode#62083]
Issue Type: <b>Bug</b>

Toggling "Maximize Panel Size" when  the panel is positioned to the right causes the left panel (e.g. Explorer) to shrink. This means that every time I toggle the panel expansion on and then off, I need to resize the left view (by double clicking on the divider between the explorer view and the editor view to auto-adjust). 

It looks like the behavior that is happening is that the expansion is causing the explorer and editor views to re-adjust when the right panel expands to the left. I can potentially see two solutions to this:

1) Change the behavior such that the expanded panel "covers" the editor view, and does not adjust/shrink the explorer view unless the expanded panel view goes beyond it. This makes sense if expanding the panel is assumed to be a temporary state (e.g. used for running tests or some other one-off commands where obstructing editor view is okay, and expected that panel size will be adjusted back). This seems to the behavior when expanding the panel whenever it's positioned at the bottom.

2) Shrink the explorer and editor view, but keep track of the original position, such that toggling the expanded panel size off restores the all the views to their original position. 

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 18.0.0

**Comment by kieferrm** [comment]
![yjgbai2vmg](https://user-images.githubusercontent.com/4674940/47682110-a54b2280-db88-11e8-8336-8fadcf691983.gif)

**Comment by AHKol** [comment]
I'm fairly new to VSCode, I duplicated the bug and am interested in giving a shot solving.

**Comment by isidorn** [comment]
@AHKol thanks for your intreset, however for helping it is best to search for issues with label `help-wanted` or `good-first-issue`

**Comment by jasonvarga** [comment]
I believe this is fixed since they made "maximize" take up the entire editor area (without your code "peeking" through anymore)

**Comment by isidorn** [comment]
Yes, this should be fixed now. Thus closing. @jasonvarga thanks for commenting
