### ISSUE TITLE
VSCode refuses to enter full screen mode on macOS mojave

### ISSUE THREAD

**Issue by samuela** [Microsoft/vscode#62095]
- VSCode Version: Version 1.29.0-insider (1.29.0-insider) 4626bc0e1b679d555dd6f034ece35ffc394b3bb7
- OS Version: macOS 10.14

I just upgraded to the latest Insiders version and I can no longer enter "full screen" mode. The rightmost green button used to transition the window to run as its own "workspace" in macOS. Now it just resizes the window in the same workspace to occupy all of the screen. It's also not possible to drag the window into the workspace bar on the top.

See https://imgur.com/a/KHeBTNx.

Steps to Reproduce:

1. Open VSCode.
2. Attempt to enter full screen mode.

Does this issue occur when all extensions are disabled?: Yes

**Comment by tjmlandi** [comment]
Also currently having the same issue with macOS 10.13.6 running the latest VSCode Insiders version.

**Comment by bpasero** [comment]
@samuela @tjmlandi can you check if you maybe have native fullscreen mode disabled:

![image](https://user-images.githubusercontent.com/900690/47707192-7df96180-dc2b-11e8-9027-386722675204.png)

**Comment by sdiprizio** [comment]
If you set _Window: Title Bar Style_ to native it works again as intended, but you loose the custom title bar...

**Comment by bpasero** [comment]
@tjmlandi @sdiprizio can you send me a screenshot of how the title buttons look like for you? do you see a green + for the fullscreen button instead of the fullscreen button?

**Comment by sdiprizio** [comment]
> I can reproduce, it seems related to the window.zoomLevel setting. It does not seem to reproduce when that is set to `1` (which I am using).

@bpasero you're right.

My window.zoomLevel was 0. I set it to 1, with window.titleBarStyle = custom. Boom fullscreen button back to normal behaviour (true macOS native fullscreen).
It still works even if I change zoom back to normal with View > Appearance > Reset Zoom.

Thanks :)

**Comment by bpasero** [comment]
I will push a fix promptly and release a new insiders version. This should take around 1 hour.

**Comment by samuela** [comment]
@bpasero Huge props! Just restarted and it seems to be back to normal now. I just want to say your responsiveness is truly appreciated!
