### ISSUE TITLE
Test: Workbench navigation

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#62097]
Refs: https://github.com/Microsoft/vscode/pull/59270 and https://github.com/Microsoft/vscode/issues/44625.

- [x] anyOS @misolori  
- [x] anyOS @Tyriar 

Complexity: 1

4 commands are added:

- `workbench.action.previousPanelView`
- `workbench.action.previousSidebarView`
- `workbench.action.nextPanelView`
- `workbench.action.nextSidebarView`

2 context keys are added too:

- `sidebarFocus`
- `panelFocus`

Known limitation: Git Viewlet unfocusable when uninitialized, https://github.com/Microsoft/vscode/issues/61534.

- Test the commands work as expected
- Test the context key work as expected (standalone, or in combination such as `"sidebarFocus && activeViewlet == 'workbench.view.explorer'"`)

**Comment by Tyriar** [comment]
@isidorn please review the command names (related https://github.com/Microsoft/vscode/issues/62218)

**Comment by isidorn** [comment]
@Tyriar @octref created this one regarding naming https://github.com/Microsoft/vscode/issues/62270
