### ISSUE TITLE
Regression: composite launch configs don't work

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#62091]
Composite launch configs don't work in latest source.

Only a single debug session shows up.  
If sessions are started manually one after another, they show up fine.

**Comment by isidorn** [comment]
This works fine for me in the latest insiders
Is there something special about your launch configuration setup? Here's the one I was using

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}/hey.js"
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program2",
            "program": "${workspaceFolder}/hey.js"
        }
    ],
    "compounds": [
        {
            "name": "Compound",
            "configurations": ["Launch Program", "Launch Program2"]
        }
    ]
}
```

![screenshot 2018-10-30 at 16 33 34](https://user-images.githubusercontent.com/1926584/47730079-b025b600-dc61-11e8-8fc2-96a917cf5f75.png)

**Comment by weinand** [comment]
here is the multiroot-workspace:
[loadedScripts.zip](https://github.com/Microsoft/vscode/files/2530453/loadedScripts.zip)

Just open scripts.code-workspace and run the "Compound (test)" launch config.

**Comment by isidorn** [comment]
This seems to work for me with latest insiders
We can do a screen sharing session tomorrow morning so I investigate what is wrong on your machine

![screenshot 2018-10-30 at 20 08 50](https://user-images.githubusercontent.com/1926584/47743574-a57a1980-dc7f-11e8-9695-bd9cbad12a92.png)

**Comment by weinand** [comment]
Behaviour in stable:
[stable.mov.zip](https://github.com/Microsoft/vscode/files/2534086/stable.mov.zip)

Behaviour in today's insiders and node2 (v8.9.4):
[Insiders.mov.zip](https://github.com/Microsoft/vscode/files/2534082/Insiders.mov.zip)

Additional issue: clearing the console doesn't work.
