### ISSUE TITLE
Add-Type does not work like PowerShell_ISE in VSCode Debugger

### ISSUE THREAD

**Issue by wesselsr** [Microsoft/vscode#62094]
Issue Type: <b>Bug</b>

When I try to to load a .NET Framework assembly, assign the type to a parameter, and return it to the caller from a function: VSCode does not return the correct type information, while Powershell_ISE does. 

Example: 
``` [Powershell]
function Get-MyType($dllPath)
{
$type = Add-Type -Path $dllPath -PassThru
# make sure the type was loaded
[MyType.From.Dll] | gm | out-string | write-Host;

return [MyType.From.Dll]
}

# in my min repo repro, I use 1 dll that has at least 1 other dll that it references locally (both built for .netframework ).
$myType = Get-MyType -dllPath <PATH>
$myType  | gm | out-string | write-host; # Same as before 'System.RuntimeType'

$myType::MyFunction()  #works in ISE not in CODE; code complians about loading the dependency dll
```

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1660 v3 @ 3.00GHz (16 x 2993)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (18.68GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
githistory|don|0.4.3
xml|Dot|2.3.2
LogFileHighlighter|emi|2.4.2
format-php|Kas|1.1.2
devinsights|Mic|0.9.7
mssql|ms-|1.4.0
csharp|ms-|1.16.2
PowerShell|ms-|1.9.0
team|ms-|1.142.0
vscode-docker|Pet|0.3.1

</details>

**Comment by joaomoreno** [comment]
Please file this in the appropriate extension repository: csharp.
