### ISSUE TITLE
Show x more Stack Frames text runs into origin text

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#62090]
Testing #61809

![image](https://user-images.githubusercontent.com/323878/47680741-f822db00-db84-11e8-81c3-cc45f0c0d834.png)

Could we do anything to separate the "Show x More Stack Frames" from the "read-only core module..." text? Reading it all together, it only makes sense to me as a DA developer. Even just a `: ` would help

**Comment by isidorn** [comment]
@roblourens yes @weinand suggested we use the `:`. We can try that, sure

**Comment by isidorn** [comment]
I liked that the wording to be consistent with Load More Stack Frames. Though I guess that is not necessery

We could do the following if the origin is there we say
`Show n More [ORIGIN]` in this example `Show 4 more read only core module(skipped by skipFiles)`
If the origin is not there we just say
`Show n More Stack Frames`

**Comment by isidorn** [comment]
@roblourens I like that idea, let's try it out
