### ISSUE TITLE
Quickly-typed rename errors

### ISSUE THREAD

**Issue by andy-ms** [microsoft/vscode#62099]
Issue Type: <b>Bug</b>

* Type:
```ts
function f() {}

f();
```

* Put your cursor to the right of `f`.
* *Quickly* hit `F2`, then `r`, then enter.

Expected: renames `f` to `r`. The behavior should be identical no matter how fast I type.
Actual:
```ts
function for (let index = 0; index < array.length; index++) {
    const element = array[index];
    
}() {}

f();
```

VS Code version: Code - Insiders 1.29.0-insider (4626bc0e1b679d555dd6f034ece35ffc394b3bb7, 2018-10-29T06:12:36.265Z)
OS version: Linux x64 4.13.0-43-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2878)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|7.63GB (0.42GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by jrieken** [comment]
tricky - we are calling `prepareRename` in order to show the input box and that depends on the timing of the extension host and tsserver
