### ISSUE TITLE
Unable to create new folder in root while too many folder exists

### ISSUE THREAD

**Issue by vikyd** [Microsoft/vscode#62109]
Unable to create new folder in root while too many folder exists.

How can I create a new folder in the root of the workspace?

![2](https://user-images.githubusercontent.com/2208880/47689970-1d930180-dbe4-11e8-8cce-380afa556843.png)

**Comment by joaomoreno** [comment]
Focus one of the folders and press <kbd>Escape</kbd> to unselect it.

**Comment by vikyd** [comment]
> Focus one of the folders and press Escape to unselect it.

Yes! It works! 

But after focus one of the folders, you should press <kbd>Escape</kbd> `2 times` to unselect it.
