### ISSUE TITLE
Blue highlight over WSL Terminal

### ISSUE THREAD

**Issue by jarbus** [Microsoft/vscode#62101]
Issue Type: <b>Performance Issue</b>

All text in my WSL shell in VSCode is highlighted in blue, and changing LS_COLORS did nothing.
![image](https://user-images.githubusercontent.com/42819002/47687225-9b8be400-dbb5-11e8-8be9-1f45a6e931c6.png)
This is my first time submitting an issue to GitHub and I'm not sure how to reliably reproduce the bug, as all I do is open a WSL Terminal.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.18247

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (8.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|2.5.1
nbpreviewer|jit|1.0.0
mips|kda|0.0.2
python|ms-|2018.9.2
cpptools|ms-|0.19.0
material-icon-theme|PKi|3.6.0
pdf|tom|0.3.0

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
This is probably happening because you changed the theme colors of cmd.exe

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693

**Comment by jarbus** [comment]
Thank you very much for looking into this. As far as I know, I recently wiped my computer and don't believe I've made any changes to the theme of cmd.exe since.
