### ISSUE TITLE
Tree twisty not alligned under Linux

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#6210]
- VSCode Version: 1.1.0
- OS Version: Linux

See screen shot:

![capture](https://cloud.githubusercontent.com/assets/1931590/15114724/94e707c4-15fb-11e6-9e80-750e4218b69a.png)

**Comment by dbaeumer** [comment]
@isidorn not sure if you or @joaomoreno

**Comment by isidorn** [comment]
That is me, dup of #195
It should only happen on the last added watch expression

**Comment by dbaeumer** [comment]
I am also seeing this in the VARIABLES pane

![capture](https://cloud.githubusercontent.com/assets/1931590/15114933/a63c7df0-15fc-11e6-8e56-95db5450362a.png)

**Comment by isidorn** [comment]
@dbaeumer Then it is a different issue. In the explorer are the twisties aligned?

**Comment by isidorn** [comment]
It seems to be 1px lower than it should on linux. I also see it for the explorer - though it is less visible

**Comment by isidorn** [comment]
@bpasero why don't we add a win / mac / linux css class top level, similar to what we do with `vs-dark`. That way I could style this twistie differently for linux (move it on 1px up)

**Comment by isidorn** [comment]
![screen shot 2016-05-25 at 12 42 53](https://cloud.githubusercontent.com/assets/1926584/15537633/eca98c4c-2277-11e6-94f3-075d2bc64442.png)

It seems aligned now to me, but the right border seems to be thicker -> postponing to June

**Comment by isidorn** [comment]
This is fixed with the new svg we are usign for the twisty
