### ISSUE TITLE
Collapsing if/else block in PowerShell PSM1 filehides the next else condition line

### ISSUE THREAD

**Issue by alongafni** [Microsoft/vscode#62100]
We have written the needed data into your clipboard because it was
Issue Type: <b>Bug</b>

1. Create a new file test.psm1 and paste this inside:
if (a -eq b) {
    do #1
} elseif (a -gt b) {
    do #2
} else {
    do #3
}

2. collapse line #1

Expected: Only line #2 is hidden
Actual: Lines #2 and #3 are hidden

This happens in PSM1 files but not in PS1 files BTW.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.92GB (39.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.21.0
vscode-eslint|dba|1.6.1
tslint|eg2|1.0.40
vscode-npm-script|eg2|0.3.5
json-tools|eri|1.0.2
beautify|Hoo|1.4.7
rest-client|hum|0.20.2
Go|ms-|0.6.93
PowerShell|ms-|1.9.0
debugger-for-chrome|msj|4.10.2
vscode-docker|Pet|0.3.1
markdown-preview-enhanced|shd|0.3.8
vscode-todo-highlight|way|1.0.4

</details>
 too large to send. Please paste.

**Comment by aeschli** [comment]
Please file this against the Powershell extension that you use...
Maybe this one? https://github.com/PowerShell/vscode-powershell

**Comment by alongafni** [comment]
Thanks @aeschli , opened a ticket to the extension:

https://github.com/PowerShell/vscode-powershell/issues/1598
