### ISSUE TITLE
Test multiline search

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#62102]
Test #13155

Complexity: 3

- [x] Mac @misolori  
- [x] Windows @gregvanl 
- [x] Linux @rebornix 

Test that multiline search works and works the same as in the editor. A regex search executes in multiline mode if it has a `\n`. `\s` will match a newline only if there is a `\n` literal somewhere in the regex.

The search view should show the first line, and highlight the correct full range in the editor when clicked.

**Comment by rebornix** [comment]
> Test that multiline search works and works the same as in the editor

Searching for LF and CRLF returns different results, is this expected? In the editor we will normalize the line breaks.

**Comment by roblourens** [comment]
There is also https://github.com/Microsoft/vscode/issues/36309#issuecomment-433579519, so besides that, they should be the same
