### ISSUE TITLE
Test: Review VS Code API Key Topics

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#62106]
Refs: https://github.com/Microsoft/vscode-docs/issues/1949

Complexity: 2

- [x] anyOS: @joaomoreno 
- [x] anyOS: @kieferrm 
- [x] anyOS: @sandy081 

I wrote a lot of content for the new Extension API doc. As I'm not the owner of some of the areas, I hope owners of these areas could do fact-checking and polishing of the docs I've written.

The Key Topics include:

- https://vscode-ext-docs.azurewebsites.net/api
- https://vscode-ext-docs.azurewebsites.net/api/extension-capabilities/overview
- https://vscode-ext-docs.azurewebsites.net/api/extension-capabilities/theming
- https://vscode-ext-docs.azurewebsites.net/api/extension-capabilities/extending-workbench
- https://vscode-ext-docs.azurewebsites.net/api/extension-guides/overview

These topics are key topics in the new Extension API because they provide high-level overview for different areas in VS Code API. They should guide people to more detailed resources on each topics.

Please review for:

- Any factual error?
- Any wording that might convey misunderstanding on certain topics?
- Anything that's important but left out?
- Navigation / Organization: Imagine yourself as a beginner/intermediate/advanced extension author. Can you easily locate what you are looking for in this APi doc structure?

For small issues, feel free to commit directly. Changes go to the `ext-docs` branch of vscode-docs: https://github.com/Microsoft/vscode-docs/tree/ext-docs.

**Comment by joaomoreno** [comment]
@octref I can't find the sources for https://vscode-ext-docs.azurewebsites.net/api in the Microsoft/vscode-docs@ext-docs branch

**Comment by octref** [comment]
@joaomoreno That's correct, that file is still in `vscode-website` private repo.
