### ISSUE TITLE
integrated terminal not updating characters what I typped but can still exec them

### ISSUE THREAD

**Issue by CreeperLKF** [Microsoft/vscode#62118]
Issue Type: <b>Bug</b>

1. Open a integrated terminal by "open in terminal"(**wsl**)
2. Use integrated terminal to compile some small cpp files and exec the result
3. Terminal stops updating characters but still exec that I typped
![x1](https://user-images.githubusercontent.com/28673129/47698733-6af68980-dc4b-11e8-9697-7be54e34fc7a.png)
it can still exec what I typped

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.18267

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6498DU CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|7.89GB (3.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
GBKtoUTF8|buk|0.0.2
graphviz-preview|EFa|1.3.0
python|ms-|2018.9.2
cpptools|ms-|0.19.0
vscode-paste-image|mus|1.0.2
glassit|s-n|0.1.3
markdown-preview-enhanced|shd|0.3.10
codelf|unb|10.8.0
markdown-all-in-one|yzh|1.7.0

</details>

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
