### ISSUE TITLE
[Settings] files.exclude option has no effect in workspace settings or folder settings

### ISSUE THREAD

**Issue by bin-zhao** [Microsoft/vscode#62116]
- VSCode Version: 1.28.1
- OS Version: Win10 Home

Steps to Reproduce:

My **User Settings** has a default *files.exclude* option, I want to cover this option in my workspace/folder, but it is no use. example:
**User Settings**
```json
"files.exclude": {
    "**/*.pyc": true,
    "**/*.o": true,
    "**/*.obj": true,
}
```

**Folder Settings**
```json
"files.exclude": {
    "**/*.pyc": true,
    "**/*.obj": true,
}
```
**I want remove** "**/*.o" **in my workspace/folder.**

Does this issue occur when all extensions are disabled?: Have not test.

**Comment by roblourens** [comment]
It should hide those files in the file explorer. Is that what you are expecting to see?

**Comment by bin-zhao** [comment]
> It should hide those files in the file explorer. Is that what you are expecting to see?

I want show *.o file when I use the settings below.

**Comment by roblourens** [comment]
Sorry, I don't understand. Before you said

> I want remove "**/*.o" in my workspace/folder.

Now you said you want to show them?

**Comment by bin-zhao** [comment]
Yes.

**Comment by roblourens** [comment]
Which one? You want to show them or hide them? I don't quite understand the problem.

**Comment by bin-zhao** [comment]
Ok. my *user default settings* is:
```json
"files.exclude": {
    "**/*.pyc": true,
    "**/*.o": true,
    "**/*.obj": true,
}
```
I want to exclude *.o file by default, so *.o is here. now I have a workspace which need to include *.o file(**show** *.o file), so I added a new setting to my *workspace settings*:
```json
"files.exclude": {
    "**/*.pyc": true,
    "**/*.obj": true,
}
```
This setting **removed** *.o, which would **show** *.o file in workspace, I think it would be work, but no effect.
Is this explanation clear?

**Comment by roblourens** [comment]
Oh, now I understand. You need to override individual keys by adding something like this: `"**/*.o": true`. That should give the result you expect.
