### ISSUE TITLE
扩展全部卡死,状态栏一直提示Activating Extensions...

### ISSUE THREAD

**Issue by oneness0** [Microsoft/vscode#62113]
Issue Type: <b>Bug</b>

只要vscode运行一段时间就会出现,稳定版也有这样的问题

VS Code version: Code - Insiders 1.29.0-insider (4626bc0e1b679d555dd6f034ece35ffc394b3bb7, 2018-10-29T06:18:55.850Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.97GB (10.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.2
html-snippets|abu|0.2.1
Bookmarks|ale|9.1.0
iview-snippets|bos|0.2.1
wechat-snippet|Cha|0.4.10
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.21.0
jquerysnippets|don|0.0.1
gitlens|eam|8.5.6
vscode-great-icons|emm|2.1.44
vsc-material-theme|Equ|2.5.1
file-icons|fil|1.0.16
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.5
vue-snippets|hol|0.1.9
beautify|Hoo|1.4.7
output-colorizer|IBM|0.1.2
easy-icons|jam|0.3.1
vscode-gutter-preview|kis|0.16.3
vscode-simple-icons|Lau|1.8.7
sftp|lix|1.7.2
easy-less|mrc|1.4.5
vscode-autoprefixer|mrm|2.1.2
vscode-language-pack-zh-hans|MS-|1.29.0
PowerShell|ms-|1.9.0
debugger-for-chrome|msj|4.10.2
vetur|oct|0.13.0
open-html-in-browser|pea|0.0.3
material-icon-theme|PKi|3.6.0
minapp-vscode|qiu|1.9.0
live-sass|rit|3.0.0
LiveServer|rit|5.1.1
vscode-icons|rob|7.27.0
sass-indented|rob|1.4.9
code-settings-sync|Sha|3.2.0
guides|spy|0.9.2
code-spell-checker|str|1.6.10
ayu|tea|0.16.0
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.9.0
JavaScriptSnippets|xab|1.7.1
markdown-all-in-one|yzh|1.7.0

(9 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
Translation: Status bar keeps displaying "Activating Extensions ..." after using VSCode Insiders or Stable for a while.

**Comment by jrieken** [comment]
This is fixed (the message will disappear after max 5 sec) in latest insiders.
