### ISSUE TITLE
Closing an unsaved file window is not showing the confirmation

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#6211]
- VSCode Version: 1.1
- OS Version: Windows 8

**Steps to Reproduce:**

1. Open VS Code for any project
2. Create a new file
3. Write some text and close the window (Use either Ctrl + w or 'x' button)

**Expected**
- A confirmation dialog asking to save or cancel

**Actual**
- Window closes and file remains under working directory as is

[screencast.zip](https://github.com/Microsoft/vscode/files/255079/screencast.zip)

**Comment by isidorn** [comment]
@sandy081 please also try with VSCode 1.0 so we see if it is a regression

**Comment by aeschli** [comment]
Closing, all fine.
The confirmation dialog only needs to appear with closing VS code, not just the editor.
