### ISSUE TITLE
problems view should only collpase/expand when clicking twisty

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#62127]
```ts
export function activate(context: any) {
  for (let co in document) {
    consle.log();
  }
}
```
* have  the above snippet twice
* click on an error in the problems view
* because it has related diagnostic info the node collapses/expands which is rather weird

![oct-30-2018 10-47-04](https://user-images.githubusercontent.com/1794099/47709773-59a08380-dc31-11e8-9c4d-17e52efa34ff.gif)

**Comment by sandy081** [comment]
@joaomoreno How can we support this in new tree? In the old tree we have the following api in the controller

```ts
protected shouldToggleExpansion(element: ITreeItem, event: IMouseEvent, origin: string): boolean {
		
	}
```

**Comment by sandy081** [comment]
@joaomoreno I see there is an option `expandOnlyOnTwistieClick`, but this applies for all. For above case, I would be able to control it per row. Especially for custom views I do not know upfront.

**Comment by joaomoreno** [comment]
Pushed `expandOnlyOnTwistieClick` as a function of `T => boolean`, which should help you.
