### ISSUE TITLE
Phpstorm like local variable declaration with annotation ( * @var ) support 

### ISSUE THREAD

**Issue by praad** [Microsoft/vscode#62123]
It would be nice to use local variables declaration possibilities for code completion like in Phpstorm or in Cakephp. It can be very useful for example editing views files.

**Comment by kieferrm** [comment]
@praad I'm guessing you use an extension when you develop PHP. Can you please file the issue against the PHP extension that you use? Thanks!

**Comment by praad** [comment]
No it is not related to extensions I would like to use normal inline variable annotations like this without any extension
`/** @var Stock $a */`
