### ISSUE TITLE
Using React in Visual Studio Code: IntelliSense

### ISSUE THREAD

**Issue by mnp3** [Microsoft/vscode#62126]
- VSCode Version: 1.28.2
- OS Version: Mac OS El Capitan 10.11.5

Steps to Reproduce:

1. https://code.visualstudio.com/docs/nodejs/reactjs-tutorial#_intellisense
2. The example code does not seem to generate a jsconfig.json file and hence intellisense for REACts types and methods does not work.
3. Solution: create a jsconfig.json file and add the content:

{
    "compilerOptions": {
        ...
    },
    "typeAcquisition": {
        "include": [
            "node"
        ]
    }
}

4. Intellisense works as described in the tutorial.

**Comment by mjbvz** [comment]
A jsconfig should not be necessary. Will investigate to see why automatic types acquisition did not download the react typings here. They should be downloaded when we see `import * as React from 'react'`

**Comment by mjbvz** [comment]
I can't repo this for a simple npm project:

```bash
mkdir test
cd test
npm init -y
npm i react
echo "import * as React from 'react'; " > index.js
```

I suspect [automatic typing acquisition](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_typings-and-automatic-type-acquisition) failed for you originally. You can manually install the react typings by running: `npm install @types/react`

Let me know if you still hit this error and have repo steps
