### ISSUE TITLE
VS Code insider expending on new virutal desktop macOS

### ISSUE THREAD

**Issue by AlexTeixeira** [Microsoft/vscode#62120]
- VSCode Version: 1.29.0-insider - 2018-10-30T06:06:04.104Z
- OS Version: macOS Mojave 10.14

Steps to Reproduce:

Since last update, can't open VS Code in virtual desktop when I click on expending button.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@AlexTeixeira we fixed this meanwhile, please update to latest.
