### ISSUE TITLE
Python linter too slow

### ISSUE THREAD

**Issue by superlevure** [Microsoft/vscode#62139]
- VSCode Version: 1.28.2
- OS Version: CentOS 7

Prerequisites:
- linter is on
- linter is pylint 

Steps to Reproduce:

1. Write a python file of ~600 lines
2. Save

What happens: 
- Linting report (using pylint) occurs after 5 seconds or so
- This causes the (default) timeout of format on save to be triggered

Note that: 
- Using pylint from the command line on the same file takes less than 500ms 
- Results is slightly better with pep8 but still > 750ms

Does this issue occur when all extensions are disabled?: Yes (all extensions disabled but python)

**Comment by kieferrm** [comment]
@superlevure thanks for reporting this. Can you pls file the issue against the Python extension? Thanks a ton.
