### ISSUE TITLE
High CPU occupied When the day is around 18 o'clock

### ISSUE THREAD

**Issue by zmicx** [microsoft/vscode#62132]
- VSCode Version:1.28.2
- OS Version: win10

When the day is around 18 o'clock, vscode isn't response all operations and high cpu occuiped with a number of proccess

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kieferrm** [comment]
@zmicx can you please follow https://github.com/Microsoft/vscode/wiki/Performance-Issues next time is 18 o'clock? Thanks!

**Comment by zmicx** [comment]
![image](https://user-images.githubusercontent.com/26269444/47987936-caf1a200-e11b-11e8-8810-446345e0f620.png)
Today I encounter the issue again at 16:30, proccesses snapshot as the picture above, 
![image](https://user-images.githubusercontent.com/26269444/47988147-66831280-e11c-11e8-9baf-80e757e45f93.png)
this picture' shown is all extensions I using 

I hope it helps. Thanks a lot

**Comment by zmicx** [comment]
![image](https://user-images.githubusercontent.com/26269444/47988480-46a01e80-e11d-11e8-9d5b-36a5fcb5a9a9.png)
It's My work pc information

**Comment by chrmarti** [comment]
Is this still an issue?
