### ISSUE TITLE
Explorer: does not reveal file in node_modules

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#62136]
Steps to Reproduce:

1. open `\node_modules\vscode-nsfw\binding.gyp`
2. collapse all in the explorer
3. reload window

=> explorer does not reveal file. works fine when refreshing the explorer

**Comment by isidorn** [comment]
Works for me. Can you repro with latest insiders, if yes what are you doing differently than me?

![reloadandreveal](https://user-images.githubusercontent.com/1926584/47817698-a3cf5500-dd56-11e8-9c3a-6074af54cec8.gif)
