### ISSUE TITLE
regression - `view` quick open broken 

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#62131]
trying to verify https://github.com/Microsoft/vscode/issues/58555

* hit F1
* select all and type `view `
* 🐛 instead of viewlet, panels et a I see file resuts

<img width="677" alt="screenshot 2018-10-30 at 10 58 52" src="https://user-images.githubusercontent.com/1794099/47710382-f44d9200-dc32-11e8-846e-1dcdb15e8a43.png">

**Comment by bpasero** [comment]
@chrmarti https://github.com/Microsoft/vscode/commit/3f7e8b4d3d2d6b44685f7c4ac918ad8dd5ab3c53 ?
