### ISSUE TITLE
SyntaxError throw when start debug with breakpoint

### ISSUE THREAD

**Issue by odelvalle** [Microsoft/vscode#62134]
Issue Type: <b>Bug</b>

I catch this error when I run debugger with breakpoint on node project. Without breakpoint, no error is throw.

Debugger listening on ws://127.0.0.1:14690/07669240-9e68-41ad-988f-c51c75780904

> Error processing "setBreakpoints": SyntaxError: Invalid regular expression: /(?<=^|file:\\\/\\\/\\\/)([a-zA-Z]):/: Invalid group at Object.pathToRegex (c:\Users\{user}\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\ms-vscode.node-debug2\node_modules\vscode-chrome-debug-core\out\src\utils.js:465:23) at NodeDebugAdapter.<anonymous> 

VS Code version: Code - Insiders 1.29.0-insider (d8c42ed0045d290adb1783ac3e9c113bfc357def, 2018-10-30T06:19:51.721Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (9.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by pkeuter** [comment]
I have the same issue, but with the latest stable (1.28.2). I'm on Windows, and I suppose this has something to do with the node-debug2 adapter.

```
Error processing "setBreakpoints": SyntaxError: Invalid regular expression: /(?<=^|file:\\\/\\\/\\\/)([a-zA-Z]):/: Invalid group
    at Object.pathToRegex (C:\Users\{user}\.vscode\extensions\ms-vscode.node-debug2-1.29.3\node_modules\vscode-chrome-debug-core\out\src\utils.js:465:23)
    at NodeDebugAdapter.<anonymous> (C:\Users\{user}\.vscode\extensions\ms-vscode.node-debug2-1.29.3\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:1353:44)
    at Generator.next (<anonymous>)
    at C:\Users\{user}\.vscode\extensions\ms-vscode.node-debug2-1.29.3\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:10:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\{user}\.vscode\extensions\ms-vscode.node-debug2-1.29.3\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:6:12)
    at NodeDebugAdapter.addBreakpoints (C:\Users\{user}\.vscode\extensions\ms-vscode.node-debug2-1.29.3\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:1339:16)
    at NodeDebugAdapter.<anonymous> (C:\Users\{user}\.vscode\extensions\ms-vscode.node-debug2-1.29.3\out\src\nodeDebugAdapter.js:613:62)
    at Generator.next (<anonymous>)
    at C:\Users\{user}\.vscode\extensions\ms-vscode.node-debug2-1.29.3\out\src\nodeDebugAdapter.js:10:71
```

```
Version: 1.28.2 (system setup)
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:23:51.859Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

**Comment by imarem** [comment]
same here

**Comment by mariuszr** [comment]
I'm getting the same error on macOS Mojave (10.14) for VS Code Insiders (1.29.0-insider - 2b06dd1ca31e407abed24f65e1804ae86180401d - 2018-10-30T11:00:25.541Z).

**Comment by vgrafe** [comment]
Same problem here - I submitted (and closed) a duplicate issue (https://github.com/Microsoft/vscode/issues/62156)

**Comment by ethanx94** [comment]
Also having this issue on stable
VSCode: 1.28.2
Chrome: 61.0.3163.100
Node.js: 8.9.3

Are we sure this isn't related to Debugger for Chrome?
That extension is at version 4.10.2

**Comment by ethanx94** [comment]
Is there any way to downgrade this? I bumped down all the way back to debugger-for-chrome-4.9.1 but no luck. Since this is part of vscode-chrome-debug-core, I'm not sure how to force that package down.

**Comment by BenoitClaveau** [comment]
same here

**Comment by vgrafe** [comment]
I installed vs-code 1.28.2 (stable version), and this issue happens as well.

**Comment by odelvalle** [comment]
Check for updates: https://dev.azure.com/vscode/VSCode/_build/results?buildId=9741&view=results

**Comment by vgrafe** [comment]
the last update didn't fix the bug for me.
