### ISSUE TITLE
Extension install should stay when focus lost for bad internet connections

### ISSUE THREAD

**Issue by arliang** [Microsoft/vscode#6213]
- VSCode Version: 1.1.0-insider (1.1.0-insider)
- OS Version: It may happen on all OS, not clear

Steps to Reproduce:

1. press **cmd(ctrl) - shift - p**
2. enter *install ext rainbow*
3. blur from Quick Command Action then it disappears and stops searching.

**Comment by isidorn** [comment]
@arliang can you please provide a screenshot, or even better a gif?

For me it works fine 

<img width="610" alt="screen shot 2016-05-09 at 21 44 43" src="https://cloud.githubusercontent.com/assets/1926584/15125843/48a49dfc-162f-11e6-8686-31d1f773f94c.png">

**Comment by arliang** [comment]
Oh, I'm sorry that I forgot providing the screenshot.
For some WE-CAN'T-SAY-REASONS :smirk: , it's hard to connect to the Internet under the protect of GFW :disappointed: .
![cl8n2mgt 9lrtkr3 fdw j](https://cloud.githubusercontent.com/assets/1703022/15134935/3d2d28ee-16a3-11e6-933c-ddb464a03886.png)

So, this feature is not required outside the GFW :sad:

**Comment by isidorn** [comment]
What is GFW? Do you have an internet connection while you are trying the ext install command?
The ext install command will fetch the list of extensions from a server, thus you must have an internet connection while doing this

**Comment by arliang** [comment]
Well, GFW is an invisible wall between Internet and China LAN. It makes connections -- from the Mainland to Outland -- slow or fail. That's why there is a [cnpm](https://github.com/cnpm/cnpm) -- a mirror for npm which organized by Taobao.
I should not have talked about this.

At last, it may be better if the **Quick Command Action** keeps there when losing focus for those people whose internet connections are not good enough. Isn't it?

**Comment by isidorn** [comment]
Thanks for more info, assigning to Joao

**Comment by arliang** [comment]
Many thanks for the response :smile:

**Comment by joaomoreno** [comment]
Merging with #637
