### ISSUE TITLE
branch change on disk not synced in VSC

### ISSUE THREAD

**Issue by bbaassssiiee** [Microsoft/vscode#62130]
Issue Type: <b>Bug</b>

- Open a project with Code.
- Switch to a branch with Code.
- Switch to another branch in iTerm
- Code does not show the right branch in the left-bottom bar.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 18.0.0

**Comment by joaomoreno** [comment]
Does the branch update as soon as you focus the VS Code window?

Do other events work? If you create a file (`touch file`) does the file explorer show it?

**Comment by bbaassssiiee** [comment]
does not help if the focus is on:
- VS Code window
- Exporer
- Source control

Nor by opening a file, editing the new file, etc.


touch a file works.

**Comment by joaomoreno** [comment]
That's odd. If you run `Git: Show Git Output`, do you see any commands being run when you switch the branch and focus VS Code?

**Comment by bbaassssiiee** [comment]
To be clear, the files in the Explorer are updated when I checkout another branch, but the current branch name is not updated in the lower-left part of the status bar.

Output of what you asked for:

```
Looking for git in: /usr/local/bin/git
Using git 2.19.1 from /usr/local/bin/git
> git rev-parse --show-toplevel
> git config --get commit.template
Open repository: /Users/bas/code/helloworld
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse develop
> git rev-parse --symbolic-full-name develop@{u}
fatal: no upstream configured for branch 'develop'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git check-ignore -z --stdin
```

**Comment by joaomoreno** [comment]
Is `develop` the wrong branch, in that example?

**Comment by bbaassssiiee** [comment]
The Git output only shows what happens using VSC. If I switch branches from a shell there is no new output. (don't worry about the line about no upstream)

**Comment by joaomoreno** [comment]
> If I switch branches from a shell there is no new output.

Even if you focus VS Code? Even after 10 seconds? Hm...

**Comment by bbaassssiiee** [comment]
[vsc.mov.zip](https://github.com/Microsoft/vscode/files/2538664/vsc.mov.zip)

**Comment by joaomoreno** [comment]
Awesome, thanks for the screen recording, much easier to understand!

Anything special about the workspace path? What does `cwd` return? What about `git rev-parse --show-toplevel`?

PS: Gotta love that <kbd>Cmd Shift 5</kbd>, right?!

**Comment by bbaassssiiee** [comment]
```
demo:helloworld bas$ pwd
/Users/bas/code/helloworld
demo:helloworld bas$ git status
On branch perl
Your branch is up to date with 'origin/perl'.

nothing to commit, working tree clean
demo:helloworld bas$ git rev-parse --show-toplevel
/Users/bas/code/helloworld
demo:helloworld bas$
```

**Comment by joaomoreno** [comment]
Maybe... does it repro with `--disable-extensions`?

**Comment by bbaassssiiee** [comment]
Makes no difference.

**Comment by joaomoreno** [comment]
Does it repro on the [insider release](https://code.visualstudio.com/insiders)?

**Comment by bbaassssiiee** [comment]
No it does not reproduce with the [insiders release](url
https://code.visualstudio.com/insiders).

**Comment by joaomoreno** [comment]
Alright, how about if you run stable with `--user-data-dir FOLDERNAME` in order to run a fresh copy of Code?

**Comment by bbaassssiiee** [comment]
No with a fresh `--user-data-dir` it does not reproduce. I figure it is not a bug then...

**Comment by joaomoreno** [comment]
How about on another workspace?

**Comment by bbaassssiiee** [comment]
What can I delete from `~/Library/Application Support/Code/` to get back on track?

**Comment by bbaassssiiee** [comment]
Yes it does.

**Comment by bpasero** [comment]
@joaomoreno to be clear, we are seeing the file event coming in (because the explorer updates), but your call to get the branch name returns the wrong result?

**Comment by bbaassssiiee** [comment]
the label of the ui below the navigator, it does not update to the checked out branch

**Comment by joaomoreno** [comment]
@bpasero Exactly. And a new user data dir fixes it. :thinking:

**Comment by bpasero** [comment]
I do not see how the user data dir could have an impact on that since I do not know what code path this call takes.

**Comment by joaomoreno** [comment]
None at all, related to the user data dir. :thinking: 

@bbaassssiiee Is there anything else in the status bar which fails to update, as far as you can tell?

Can you also show us you full user settings? Maybe reset them to nothing and see if the issue still occurs?

**Comment by bbaassssiiee** [comment]
OK to close.
