### ISSUE TITLE
Add ability to highlight files in tree view sidebar

### ISSUE THREAD

**Issue by elitistsnob** [microsoft/vscode#62144]
Offer users the ability to highlight files in the sidebar tree view. Similar to the feature shown in the attached screenshot. 

![screen shot 2018-10-30 at 9 41 41 am](https://user-images.githubusercontent.com/538261/47722126-0bd34d80-dc28-11e8-9e0e-1a1dcbc8dc33.png)

**Comment by isidorn** [comment]
https://github.com/microsoft/vscode/issues/62104
