### ISSUE TITLE
The editor ignores tabSize in markdown files

### ISSUE THREAD

**Issue by in-in** [microsoft/vscode#62143]
- VSCode Version: **1.28.2** (**1.29.0-insider**)
- OS Version: _Linux Mint 19 Cinnamon_

Steps to Reproduce:

1. Create a markdown file with this content:
```markdown
<!-- test.md -->
- item1
  - item2
```
It works as expected `tabSize` _space: 2_
![18103001](https://user-images.githubusercontent.com/8797432/47721280-d26b0400-dc60-11e8-8293-88828841eeee.png)

2. Add one more nested item and reopen this file:
```markdown
<!-- test1.md -->
- item1
  - item2
    - item3
```
`tabSize` change to _space: 4_
![18103002](https://user-images.githubusercontent.com/8797432/47721565-6fc63800-dc61-11e8-993b-71cfa4e07231.png)

Does this issue occur when all extensions are disabled?: Yes

My `settings.json`
```json
{
    "editor.tabSize": 2,
    "editor.renderWhitespace": "all"
}
```

**Comment by kieferrm** [comment]
Confirmed. When you change the setting when the editor is open, the editor picks up the settings change. When you open an editor, after the setting is changed, the editor uses the default rather than the actual setting.

**Comment by in-in** [comment]
What settings did you mean? I did not touch the settings, they change themselves. That is why I opened this issue.
