### ISSUE TITLE
Warning does not provide reasonable information

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#62147]
Testing #62087

- Configure an invalid schema URL for a json file

```
"json.schemas": [
		{
			"fileMatch": [
				"vscode/sample.json"
			],
			"url": "https://path/to/schema.json",
		},
	]
```

- Open sample.json and see warning icon in the status bar
- Hover on the warning icon

![image](https://user-images.githubusercontent.com/10746682/47722629-1f47de00-dc53-11e8-9e81-e3426a3df92c.png)

**Comment by aeschli** [comment]
FYI @xxyy... We tested your PR in this weeks test pass. Of course, fixes are welcome, as always. I'm out the coming month, but @octref can help getting them pushed.

**Comment by octref** [comment]
Let's track this in #62149.
