### ISSUE TITLE
Markdown data URLs are now broken

### ISSUE THREAD

**Issue by brunnerh** [Microsoft/vscode#62142]
Issue Type: <b>Bug</b>

I frequently use base 64 encoding to embed images directly in a markdown document, this worked until some previous version. Now the links are broken because the constructed URL is prefixed with `vscode-resource:`; i assume for relative link resolution, as the prefix points to the current directory.

So you get rendered HTML like this:

```html
<img src="src="vscode-resource:/i:/Documents/Tasks/data:image/png;base64,iVBORw0KGgoAAAAN..."/>
```

When it should be:

```html
<img src="data:image/png;base64,iVBORw0KGgoAAAAN..."/>
```

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (1.02GB free)|
|Process Argv|--disableExtensions|
|Screen Reader|yes|
|VM|0%|

</details>Extensions disabled

**Comment by Dob6458** [comment]
Have you added this code in your file ?
```html
  <meta charset="utf-8" />
```

**Comment by brunnerh** [comment]
No, i have not, just regular markdown along the lines of:

```markdown
![pic](data:image/png;base64,...)
```

This new mechanism also messes with some extensions, e.g. https://github.com/neilsustc/vscode-markdown/issues/296

**Comment by Dob6458** [comment]
Try to show the image with `https://` but not `data:image/<code>`
