### ISSUE TITLE
Warning icon flickers while changing the json schema setting

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#62146]
Testing #62087

- Configure an invalid schema URL for a json file

```
"json.schemas": [
		{
			"fileMatch": [
				"vscode/sample.json"
			],
			"url": "https://path/to/schema.json",
		},
	]
```

- Open sample.json and see warning icon in the status bar
- Open settings which will remove the warning.
- Now change the file name to `sampl.json`
- Warning is not shown - good
- Change the file name back to `sample.json` and save
- 🐛 Warning icon appears for a moment

**Comment by aeschli** [comment]
FYI @xxyy... We tested your PR in this weeks test pass. Of course, fixes are welcome, as always. I'm out the coming month, but @octref can help getting them pushed.
