### ISSUE TITLE
Git: Provide better filter on git checkout quick open

### ISSUE THREAD

**Issue by budarin** [microsoft/vscode#62140]
We use lerna for publishing our components to registry.
Every publish it creates a tag for every component.
When we try to find a branch from command line we should scroll huge amount of time through tag list to find a branch.

**Comment by kieferrm** [comment]
@budarin I'm not sure I understand the issue you report. Can you please add a gif recording to this issue?

**Comment by budarin** [comment]
I'm sorry - I cannot create gif but I have an image

<img width="819" alt="default" src="https://user-images.githubusercontent.com/8055157/47767484-e0faff00-dce4-11e8-9cd3-996b9a79f5ad.png">

**Comment by cnelson9** [comment]
You can just change the Checkout Type to "remote" in the git settings.

![image](https://user-images.githubusercontent.com/28309447/48161218-a45c7400-e29f-11e8-801a-cb16b788850a.png)

**Comment by budarin** [comment]
but I need to view local branches !
It doesn't solve the problem (

**Comment by budarin** [comment]
I want to discover what branches are - I don't know their names

**Comment by ADIX7** [comment]
The "remote" options shows local branches too. It ignores only tags.
