### ISSUE TITLE
window.nativeFullscreen name and description

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#62145]
Refs: #61880

1. `window.nativeFullscreen` I would prefer `window.nativeFullScreen`, because Full Screen is two words in our appereance menu. There is already an option `zenMode.fullScreen`. I understand there is already a badly named `window.restoreFullscreen`. But I would prefer correct casing over consistency here.
2. The description is `Prefer native full-screen. Disable this option to prevent macOS from creating a new space when going full-screen.`
I would prefer the following 

`Controls if native full-screen should be used on macOS. Disable this option to prevent macOS from creating a new space when going full-screen.`
In the future if this affects behavior on other OSs we can tune the descipriont

**Comment by arthurdenner** [comment]
Hi @isidorn. I see that you assigned this to a member, but can I tackle this one?
