### ISSUE TITLE
Warning icon disappears even the URL is invalid

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#62148]
Testing #62087

- Configure an invalid schema URL for a json file

```
"json.schemas": [
		{
			"fileMatch": [
				"vscode/sample.json"
			],
			"url": "https://path/to/schema.json",
		},
	]
```

- Open sample.json and see warning icon in the status bar
- Click on the warning icon and it disappears even though URL is not resolved.

**Comment by aeschli** [comment]
FYI @xxyy... We tested your PR in this weeks test pass. Of course, fixes are welcome, as always. I'm out the coming month, but @octref can help getting them pushed.

**Comment by octref** [comment]
Probably as-designed. When a user provides an invalid URL, retry once. If it fails, don't enable JSON Schema for that file.
