### ISSUE TITLE
'Run to Cursor' option not offered on sources that were loaded readonly

### ISSUE THREAD

**Issue by gjsjohnmurray** [Microsoft/vscode#62141]
- VSCode Version: 1.28.2 (user setup)
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Debug something
2. Use 'Pause' (F6) to suspend execution in a read-only core module. In my case (debugging my debugger extension) Pause happened in async_hooks.js in the emitHookFactory function.
3. Right-click a few lines further on in this source, and observe that the context menu doesn't offer 'Run to Cursor'

This seems to be the source line that's explicitly requiring a writeable editor in order to offer 'Run to Cursor':

https://github.com/Microsoft/vscode/blob/2b06dd1ca31e407abed24f65e1804ae86180401d/src/vs/workbench/parts/debug/browser/debugEditorActions.ts#L106

Why is it not possible to offer 'Run to Cursor' within a readonly source?

**Comment by isidorn** [comment]
@gjsjohnmurray Good point. And thanks for providing a code pointer.
