### ISSUE TITLE
Intellisense no longer working? How to re-enable?

### ISSUE THREAD

**Issue by MrSkinny** [Microsoft/vscode#6215]
- VSCode Version: 1.0.0
- OS Version: 10.11.4

I'm not sure exactly when this was disabled, but I used to get the Intellisense inline suggests without any special configuration.  i.e. I'm in a single javascript file, I declare a function that has an unused locally scoped variable, and Intellisense underlines it.  

This no longer happens and I'm not seeing an obvious way to reenable this?  If I used globals that weren't defined, it also used to prompt to allow downloading of the typings file (e.g. for node), but that's also stopped.

**Comment by dbaeumer** [comment]
@MrSkinny we move to a unified JavaScript / TypeScript language service to better support JS. However this requires some more configuration which is documented here: https://code.visualstudio.com/docs/languages/javascript 

We are also working on bringing back the prompting to download typings files.

Regarding the underlines unused: yes the new language service warns about unused locales. This can be disabled in a jsocnfig.json file.

**Comment by MrSkinny** [comment]
I'm either doing something wrong or there are a lot of missing intellisense markers that used to come up. From that link you provided, it doesn't appear any setup is *necessary*, only recommended.  I tried adding the sample `jsconfig.json` that just sets an ES6 target and excludes `node_modules`, but I'm not getting things like `$` being undefined even if there's no jquery project / global var declared, etc.

**Comment by MrSkinny** [comment]
For example:

<img width="415" alt="screen shot 2016-05-11 at 10 51 16 pm" src="https://cloud.githubusercontent.com/assets/3757471/15205316/f5882114-17ca-11e6-95f1-f05ae6f1a935.png">

**Comment by dbaeumer** [comment]
@MrSkinny now I see. This is a know issue with the new JS language server and is tracked in this TS issue: https://github.com/Microsoft/TypeScript/issues/6802.

**Comment by MrSkinny** [comment]
OK good to know it's being worked on! Thanks.
