### ISSUE TITLE
Problems shown in Problems pane for files in excluded folders

### ISSUE THREAD

**Issue by alexr00** [Microsoft/vscode#62151]
In user settings:

    "files.exclude": {
		"**/.git": true,
		"**/.svn": true,
		"**/.hg": true,
		"**/CVS": true,
		"**/.DS_Store": true,
	}

Make a javascript file in the .git folder of a workspace. Write some javascript and introduce a problem.

Expected: The problem doesn't show up in the Problems pane.

Actual: The problem is in the problems pane even though the .git folder is excluded.

Version 1.29.0-insiders commit 2b06dd1ca31 on Windows.

Found while testing: #62063

**Comment by sandy081** [comment]
@alexr00 Did you enable exclude option in filter box?

![image](https://user-images.githubusercontent.com/10746682/47725714-55885c00-dc59-11e8-88b3-592451b0e367.png)

**Comment by alexr00** [comment]
Works great with that. Thanks!
