### ISSUE TITLE
Remove --logStorage argv

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#62152]
Testing #61928

The `--logStorage` argument seems a bit weird and too specific. I know it's just a dev option, but this is exactly why we have log levels. Those `info` log statements should just be `trace` log statements and checking for storage logs should just be `--log trace` and filtering down on storage service messages.

Doing so even helps us in debugging issues which might not seem storage related, but by using `--log trace` we would see storage service messages in the log.

**Comment by bpasero** [comment]
I love it ❤️

**Comment by joaomoreno** [comment]
No! I love you! :couple:
