### ISSUE TITLE
Problems stay in problems pane if I delete the file they are from

### ISSUE THREAD

**Issue by alexr00** [Microsoft/vscode#62154]
Create a file in an workspace.
Introduce some problems and save the file.
See the problems in the Problems pane.
From the filesystem, delete the new file.
The problems won't go away without reloading the window.

version 1.29.0-insiders
commit 2b06dd1ca
Windows

Found while testing #62063

**Comment by sandy081** [comment]
@alexr00 Is it a typescript file?

**Comment by sbatten** [comment]
@sandy081 same behavior for me with markdown file

**Comment by sandy081** [comment]
Assigning to @mjbvz as I suppose markdown diagnostics are not cleared in this case.

**Comment by alexr00** [comment]
@sandy081, this is happening to me with _all_ file types I've tried so far (js and ts). There's one more step that I missed. Before you delete the file, you need to close it.

**Comment by mjbvz** [comment]
@sandy081 Our built-in markdown support does not provide any diagnostics so this is likely coming from an extension

**Comment by sandy081** [comment]
@sbatten Can you check which extension is providing these errors?

**Comment by sbatten** [comment]
@sandy081 I was using my own test extension locally

**Comment by sandy081** [comment]
Ok, it explains. VS Code does not remove the markers automatically when file is closed or deleted. It is responsibility of the owner of the markers to clean up. So closing this as designed.

**Comment by alexr00** [comment]
@sandy081, what about the ts and js errors? I had not installed any marketplace extension to provide those problems.

**Comment by sandy081** [comment]
Regarding TS and JS, Errors should be cleared when files are deleted. But not when files are closed. Please correct me @mjbvz if I am wrong.
