### ISSUE TITLE
Specificity not very clear what it means

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#62155]
Refs: #62048

Notice in the screenshot that specificity is being rendered and me as a user can be puzzled by this. I have no clue what this means, I can not google specificity. Due to that I propose the following:
1. Rename "Specificity" to "CSS Specificity"
2. If you can render links in the hover, consider linking to https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity The "CSS Specificty" would link to it.

![screenshot 2018-10-30 at 15 17 25](https://user-images.githubusercontent.com/1926584/47724519-253fbe00-dc57-11e8-99e3-c5872488b56d.png)

**Comment by octref** [comment]
@tlent fixed this with `Selector Specificity`, which I think is pretty good too.
