### ISSUE TITLE
Extension details do not load

### ISSUE THREAD

**Issue by Kuuak** [Microsoft/vscode#62150]
Issue Type: <b>Bug</b>

When select an extension in the Marketplace, the details of the extenstion do not show and the loader keeps running indefinitely.

I can however install and remove by the command line `code --install-extension`

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz (4 x 3300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.5
twig-language|mbl|0.2.9
vscode-scss|mrm|0.6.2
vetur|oct|0.13.0
vscode-docker|Pet|0.3.1
sass-indented|rob|1.4.9
wordpress-toolbox|wor|1.2.0

(1 theme extensions excluded)

</details>

**Comment by kieferrm** [comment]
@Kuuak, it seems you can access the market place and search for extensions? You can't however open the details page. Is this the same for all extensions or only specific ones? If the latter, those are fine on https://marketplace.visualstudio.com?

**Comment by Kuuak** [comment]
Hello @kieferrm, thanks for your answer.
Indeed I can search in the marketplace and the results show up correctly. I get the same results from searching inside VSCode or on the marketplace website.

Sorry for not being enough descriptive on my bug report. As an image can be way more explicit than some text, find a short screen-cast of the bug through that link https://drive.google.com/open?id=1o-cASslETYQ6xmDhHryM8MX9W6qqWcVa

Thanks

**Comment by kieferrm** [comment]
@Kuuak are sitting behind a proxy server?

**Comment by sandy081** [comment]
@Kuuak Can you please do following steps

- Open Dev tools using command `Developer: Toggle Developer Tools` in Command pallette
- Please check if there are any errors in the console
- Can you also check network tab and see if the requests to market place are returning back?
