### ISSUE TITLE
DebugConfigurationProvider is not recognized on linux

### ISSUE THREAD

**Issue by miniwolf** [Microsoft/vscode#62165]
- VSCode Version: 1.26.1
- OS Version: Ubunut 18.04.1

A user has reported that the the launch configuration for the debugger is not appearing in the list. 
The typescript implementation is using the DebugConfigurationProvider to provide the resulting configuration file content. https://github.com/Unity-Technologies/vscode-unity-debug/blob/master/typescript/attach.ts#L41

This works well on Windows and OSX. Is there any additional steps that I can take to verify or resolve the problem?

**Comment by isidorn** [comment]
Please investigate deeper on the extensinos side before filling issues here.
So first, make sure the user can reproduce wit hthe latest insider version.
If he can, than please investigate on your extension side by putting breakpoints and providing more useful information. 

Thanks
