### ISSUE TITLE
Errors and warnings not updated after changing language mode

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#6216]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows 10

Related: #5193 

Steps to Reproduce:

1. Open a JavaScript file, mine by default had no errors.
2. On the bottom toolbar click JavaScript to change language mode
3. Select CSS
4. Observe that the error count has changed
5. Change language mode back to JavaScript

Errors are not removed until the file is removed from working files or restarting Code.

**Comment by jrieken** [comment]
maybe @aeschli

**Comment by dbaeumer** [comment]
@aeschli the stale markers are CSS markers. However there is not easy fix here since we can't in general remove markers on mode change (for example spelling problems stay valid). I will keep the issue for now and will consider this when working on an improved marker story.

**Comment by dbaeumer** [comment]
A new marker story will be implemented in June.

**Comment by dbaeumer** [comment]
This will be addressed in CSS. The agreed story is to remove markers when a file closes for single file marker generation.
