### ISSUE TITLE
CSS quick fix should suggest to use validProperties settings

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#62160]
Refs: https://github.com/Microsoft/vscode/issues/62049

Have the following css:
```css
nav > a:hover::before {
	isidor: 5;
}
```
Notice the warning and the quick fixes. I would expect the quick fix to offer to add "isidor" to the "validProperties" setting. That way we would make this setting more discoverable

![screenshot 2018-10-30 at 15 55 09](https://user-images.githubusercontent.com/1926584/47727180-3b03b200-dc5c-11e8-9f83-142fc6cf394c.png)

**Comment by octref** [comment]
We don't suggest them in IntelliSense either. I think a more sensible approach would be allow https://github.com/Microsoft/vscode/issues/2784 for HTML / CSS. This allows people to add their own definitions to the collections of HTML/CSS tags/properties we source from MDN. We can then update all language features to base off that collection.

That setting is meant as a quick-dirty way to shut up the linter. I don't hope we base all CSS language features from one small setting.

**Comment by isidorn** [comment]
Ok makes sense, thanks for the explanation.
