### ISSUE TITLE
Split Cwd descriptions

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#62175]
Testing #62096

Two suggestions:
- Use 'folder' not 'cwd' in the descriptions of the setting and its values.
- Change the settings description to something simpler, e.g.: Controls in which folder a split terminal starts in.

**Comment by octref** [comment]
I agree with both points. Re the first one, @chrmarti what do you think of my suggestion at https://github.com/Microsoft/vscode/issues/62180?

- `terminal.integrated.splitWorkingDirectory`
  - `inherit`
  - `initial`
  - `workspaceRoot`

**Comment by Tyriar** [comment]
The reason it's cwd is because it aligns with the already established setting "terminal.integrated.cwd"

**Comment by octref** [comment]
`"terminal.integrated.cwd"` What's the use case for that? I can only think it's useful when I'm opening empty workspace, and I hope it does fallback to workspace root when I'm not opening empty workspace.

**Comment by chrmarti** [comment]
The descriptions would still benefit from using 'folder' instead of 'cwd'.

**Comment by alexr00** [comment]
Change the descriptions to use folder instead of cwd seems reasonable. It would allow people who aren't familiar with 'cwd' to avoid having to look it up.

**Comment by alexr00** [comment]
I ended up using 'working directory' instead of folder since it aligns with the initialism 'cwd' and is more accurate than 'folder'
