### ISSUE TITLE
Brief fullscreen toggle when changing monitor configuration with simple fullscreen

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#62177]
Testing https://github.com/Microsoft/vscode/issues/61880

1. Set `window.nativeFullscreen` to false
2. Toggle in and out of fullscreen, ending on fullscreen
3. Change monitor configuration. I have two external monitors, I unplugged one

After the configuration change, VSCode toggles in and out of fullscreen:
![fullscreen_flicker](https://user-images.githubusercontent.com/3672607/47735524-eba48e00-dc29-11e8-9e11-189cc58142d4.gif)

VS Code version: Code - Insiders 1.29.0-insider (2b06dd1ca31e407abed24f65e1804ae86180401d, 2018-10-30T11:06:08.867Z)
OS version: Darwin x64 18.0.0

**Comment by bpasero** [comment]
Thanks for uncovering this 👍

**Comment by ignu** [comment]
@bpasero yeah, something i uncovered was that if i switched monitors or resolutions vscode would still be "fullscreen" but the resolution would be wrong.

**Comment by ignu** [comment]
(ugh. i just realized... my flicker's not nearly that bad but i just realized i have all my animations/transitions in macOS either sped up or completely off)

**Comment by bpasero** [comment]
Will check today if there is any other solution, otherwise we have to report to Electron and track as upstream.

**Comment by bpasero** [comment]
Closing as upstream reported.
