### ISSUE TITLE
can not access to marketplace

### ISSUE THREAD

**Issue by Mohamad-Amin-Ataee** [Microsoft/vscode#62174]
i remove my vscode and install the last version .i'm in ubuntu 18.04 and my ip is from iran. What should i do : 
We cannot connect to the Extensions Marketplace at this time, please try again later

**Comment by kieferrm** [comment]
@Mohamad-Amin-Ataee, is the marketplace available when you try to access it through a browser: https://marketplace.visualstudio.com ?

**Comment by Mohamad-Amin-Ataee** [comment]
> @Mohamad-Amin-Ataee, is the marketplace available when you try to access it through a browser: https://marketplace.visualstudio.com ?

Yes it's available ..

**Comment by sandy081** [comment]
@Mohamad-Amin-Ataee Can you please show a screen shot of what you are seeing in Extensions view?

Also open Dev tools using `Development: Toggle Developer Tools` command in Command Pallette and check if there are any errors in console or network tab?

**Comment by Mohamad-Amin-Ataee** [comment]
I have switched to Microsoft Windows and my problem solved .. Thanks

**Comment by keelung-yang** [comment]
ME TOO, On last KDE Neon running Ubuntu 18.04

**Comment by SrikalyanBurra** [comment]
Same issue... please reopen

**Comment by ToniApps** [comment]
Me too, i add a screenshot of the error

![captura de pantalla 2018-12-05 a las 15 47 13](https://user-images.githubusercontent.com/16474660/49521182-280c7f00-f8a5-11e8-980a-3d737edf4e97.png)
