### ISSUE TITLE
multiline search results different on Windows and Ubuntu

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#62187]
Re #62102 

* Search `.*\n\t` on Ubuntu in VSCode repo

![image](https://user-images.githubusercontent.com/876920/47742987-219e3e00-dc3b-11e8-8d93-4fc23e02f37e.png)

* Search `.*\n\t` on Windows 10 in VSCode repo

![image](https://user-images.githubusercontent.com/876920/47743010-32e74a80-dc3b-11e8-993a-467ce09ec7e9.png)

**Comment by roblourens** [comment]
`\r\n` :( https://github.com/Microsoft/vscode/issues/36309#issuecomment-433579519
