### ISSUE TITLE
multiline search result view duplicates

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#62186]
Re #62102 

System: Ubuntu 18.04

* Open VSCode repo
* Search `;\n\t*` with regex mode
* The result view shows duplicated content

![image](https://user-images.githubusercontent.com/876920/47742883-dc7a0c00-dc3a-11e8-83c0-28e6411c899c.png)

In image above, the search found `'use strict';` correctly but the result view is displaying `'use strict'use strict'use strict';`

**Comment by roblourens** [comment]
Also this (@gregvanl) now I can repro

![image](https://user-images.githubusercontent.com/323878/47749770-118e5a80-dc4b-11e8-899d-c39c9ce3211d.png)

**Comment by roblourens** [comment]
There are at least a couple different issues but it's too hard to pick them apart so I'm calling this the master issue of these weird search results.
