### ISSUE TITLE
Git output doesn't contain sanity checking errors anymore

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#6218]
- VSCode Version: 1.1, latest from HEAD
- OS Version: Linux Elementary OS

I want to commit, error dialag says there has been an issue, please check output, but no message in output.
![image](https://cloud.githubusercontent.com/assets/6461412/15127197/d86b4584-1635-11e6-8389-b0fef7d3b392.png)

**Comment by isidorn** [comment]
Dup of #5838
