### ISSUE TITLE
Golden ratio for pane

### ISSUE THREAD

**Issue by iamkabirmalik** [Microsoft/vscode#62189]
Provide a feature to automatically resize active pane. So that when someone click on pane it will take more screen area than others pane. This feature already available in many editors. Here is atom preview

![golden ratio](https://user-images.githubusercontent.com/31293295/47743159-6a3e1180-dca4-11e8-826f-15db12030873.gif)

Here is another Example 

![golden ratio 2](https://user-images.githubusercontent.com/31293295/47743234-99ed1980-dca4-11e8-8c11-91d773f2c9ea.gif)

**Comment by bpasero** [comment]
This can be done via commands and grid layout, see https://code.visualstudio.com/updates/v1_25#_new-layouteditorgroups-command
