### ISSUE TITLE
full screen

### ISSUE THREAD

**Issue by uwbwsvd** [Microsoft/vscode#62194]
Issue Type: <b>Bug</b>

After full srceen, there is no way back.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:12.403Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.89GB (7.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.6.1
vscode-language-pack-de|MS-|1.28.2
cpptools|ms-|0.19.0
csharp|ms-|1.16.2
vba|spe|1.2.0
html-preview-vscode|tht|0.2.4

</details>

**Comment by uwbwsvd** [comment]
Press F11. I see now chance to get back to then normal screen. Do I move to upper border of the screen, the curser change to hand. I can grasp something an I get picture of a file (like to move it)

**Comment by kieferrm** [comment]
@uwbwsvd correct, use <kbd>F11</kbd> to toggle in or out of full-screen mode, you can also go through the command palette.

**Comment by uwbwsvd** [comment]
Hadn't in mind that "Umschalten"(German) means toggle  in **or** out.
