### ISSUE TITLE
Loaded scripts in command pallete does not show parent resources

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#62190]
Refs: #62093

Since we now show parent resources in the loaded scripst view I would expect that we also show parent resources in the loaded scripts in the command palette.

**Comment by roblourens** [comment]
@isidorn what do you mean "in command palette"?

**Comment by weinand** [comment]
@isidorn do you mean the quick pick base loaded scripts?

**Comment by isidorn** [comment]
Yes I mean the quick pick, sorry for the wrong wording.
