### ISSUE TITLE
Loaded scripts in command pallete are not rendering file icons

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#62191]
Refs: #62093

Notice how when you open quick open to navigate to a file the icon is being nicely rendered.
This is not the case when I am navigating through loaded scripts in the command pallete and I would expect that the experience is the same.

**Comment by weinand** [comment]
@isidorn I think you mean "quick pick" when you say "command palette".

Since the "quick pick" based loaded scripts will go away as soon as the loaded scripts view supports filtering, I will not add any new features.
