### ISSUE TITLE
Feedback on extension docs overview

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#62197]
Testing https://github.com/Microsoft/vscode/issues/62107

Under "What Can Extensions Do?", I think it would be better to not include the note about being unable to access DOM API. This makes an assumption about the readers knowledge. Since this is an overview, I think this technical detail can be left out. If it is included, then I think there should be another explanatory sentence about VSCode running on electron, or a link to docs on the architecture.

The bullet points here might also be confusing, I would use generic language instead of `Tree View` and `StatusBar`, something like "Adding new UI components or views".

The section under "Building Extensions" restates what's in the table of contents. Instead of using the same section headers, this might be better structured as a list of tools/resources that have a brief explanation of what they are and potentially a link to more, like:

- Hello Code
- Yeoman Code Generator
- Extension Samples
- vsce
- References

**Comment by RMacfarlane** [comment]
I think it might also be useful to have an architecture diagram on the overview page. I actually quite like this about the existing extension overview page: https://code.visualstudio.com/docs/extensions/overview

**Comment by octref** [comment]
> I think it might also be useful to have an architecture diagram

I can update the illustration. But I think it should exist in the Extension Capabilities Overview page.

For the DOM part, I agree it's a bit intimidating for an Overview. I can put it to Extension Capabilities Overview too.

> The bullet points here might also be confusing, I would use generic language instead of Tree View and StatusBar, something like "Adding new UI components or views".

Sure. Good point.

> Hello Code
Yeoman Code Generator
Extension Samples
vsce
References

The problem is vsce and Yeoman Code Generator are too detailed that I don't think they should end up in this listing, though.

**Comment by octref** [comment]
> The bullet points here might also be confusing, I would use generic language instead of Tree View and StatusBar, something like "Adding new UI components or views".

Made it `Add customized components & views to the Workbench UI`.

> If it is included, then I think there should be another explanatory sentence about VSCode running on electron, or a link to docs on the architecture.

What we end up with:

> VS Code is an Electron based app, so its UI is built using HTML, CSS and JavaScript using the usual browser DOM API. However, VS Code does not provide DOM access to extension authors in order to ensure its responsiveness and performance. Instead, an extensive Extension API is exposed in order to customize the editor. Here are some examples of what you can achieve using this API, each with link to a more detailed topic:
