### ISSUE TITLE
Better syntax highlighting for Shell scripts

### ISSUE THREAD

**Issue by scriptum** [Microsoft/vscode#62193]
Following example will not be highlighted in VSC:

```sh
find /home -name filename -type f
```

Vim:
![image](https://user-images.githubusercontent.com/695971/47745380-90f44c00-dc94-11e8-9ba1-7c22369b6339.png)

Atom:

![image](https://user-images.githubusercontent.com/695971/47745417-a9646680-dc94-11e8-8733-6dd9d88f171b.png)

Visual Studio Code:

![image](https://user-images.githubusercontent.com/695971/47745437-b7b28280-dc94-11e8-9d35-4d2659ce11cc.png)

**Comment by octref** [comment]
Which page?

**Comment by alexr00** [comment]
This issue was moved to atom/language-shellscript#135

**Comment by alexr00** [comment]
I moved the issue to owners of the text mate grammar. Looks like there are still occasional changes to the repository is still being maintained.
