### ISSUE TITLE
Quick Open hover shows 'null'

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#62207]
- VSCode Version: 1.29 Insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Bring up Quick Open (workbench.action.quickOpen)
2. Hover over a list item

You see a hover (don't see this in 1.28) with the text 'null'.

![image](https://user-images.githubusercontent.com/12818376/47752462-c0ce3000-dc51-11e8-963c-d6679e9e694f.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by gregvanl** [comment]
Also repro's in the Command Palette

![image](https://user-images.githubusercontent.com/12818376/47752672-5ec1fa80-dc52-11e8-994f-ce5842951251.png)

**Comment by bpasero** [comment]
@isidorn maybe a change in `IconLabel`? Also ping @jrieken

**Comment by jrieken** [comment]
maybe a strict null issue? the highlight label can optional (`undefined`) take a title attribute and I can image that this has become `null` somewhere down the path

**Comment by gpoussel** [comment]
This is due to 318250ae1230966df2c15e0af23688f4dfa646a6 I guess.

**Comment by isidorn** [comment]
@gpoussel thanks for the PR, assigned it to @sandy081 to review since it is his commit

**Comment by isidorn** [comment]
I verified that the PR does indeed fix the issue. Once @sandy081 gives the thumbs up, we can merge it in
