### ISSUE TITLE
Cmd + Hover disappears once mouse moves, cannot scroll inside it

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#62208]
1.28. If Cmd + Hover shows a hover with overflow, I cannot go into the hover and scroll. Whenever my mouse leaves highlighted word, the Cmd Hover disappears. This is inconsistent with plain Hover.

![cmd-hover](https://user-images.githubusercontent.com/4033249/47752653-4a7dfd80-dc52-11e8-8d8f-7cf68f72a992.gif)

**Comment by jrieken** [comment]
@alexandrudima is that something that has changed with the recent'ish hover tweaks?

**Comment by alexandrudima** [comment]
@jrieken I think this is specific to cmd+hover i.e. `GotoDefinitionWithMouseEditorContribution`. That thing is actively adding/removing a hover message decoration that contains the text of the jump target. I guess it is removing the hover message decoration even when the mouse moves over the hover itself.

**Comment by roblourens** [comment]
This still goes away when I try to mouseover

**Comment by jrieken** [comment]
@roblourens proof it
![dec-06-2018 09-15-33](https://user-images.githubusercontent.com/1794099/49570647-841fe380-f937-11e8-9146-06028ace331d.gif)

**Comment by roblourens** [comment]
![dec-06-2018 11-46-44](https://user-images.githubusercontent.com/323878/49608104-aec86700-f94c-11e8-81bf-661aff254e33.gif)

Am I doing something wrong? Just holding cmd and moving the mouse around.

**Comment by jrieken** [comment]
I will investigate in December. It works for me but my link-modifier-key is `Alt` so that might make a difference
