### ISSUE TITLE
'Run to Cursor' breakpoint no longer gets removed

### ISSUE THREAD

**Issue by gjsjohnmurray** [Microsoft/vscode#62202]
Issue Type: <b>Bug</b>

Using Insider 1.29 to verify the fix for #62141 I discovered that the temporary breakpoint added when I use 'Run to Cursor' from the context menu no longer gets removed when execution reaches it. 

This feature works correctly in 1.28.2.

VS Code version: Code - Insiders 1.29.0-insider (4b2fac2b6da220f62ff58b2766e4ecc1f561be94, 2018-10-30T16:54:48.685Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A6-3420M APU with Radeon(tm) HD Graphics (4 x 1497)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.47GB (0.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-cos|dou|0.4.0

</details>

**Comment by isidorn** [comment]
Good catch, thanks for reporting it!

**Comment by weinand** [comment]
works fine in latest.
