### ISSUE TITLE
Cannot sign into Azure via azure functions extension

### ISSUE THREAD

**Issue by tpmehta** [Microsoft/vscode#62200]
Issue Type: <b>Bug</b>

I have installed the azure functions extension for VS Code, and prior to creating a new project I am failing to log in.  Repro steps:
1. click on "Sign in to Azure"
2. A toast notification pops up with URL and one time auth code for microsoft.com/devicelogin
3. I log in via hyperlink, successfully using my microsoft.com credentials (I get the following message in browser: "Visual Studio Code
You have signed in to the Visual Studio Code application on your device. You may now close this window."
4. VS Code never refreshes to update with my creds

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (1.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-azurefunctions|ms-|0.12.0
azure-account|ms-|0.4.3

</details>

**Comment by chrmarti** [comment]
@tpmehta Does the status bar keep showing 'Azure: Signing in...' or does that change? Does the console (Help > Toggle Developer Tools) show any errors?

**Comment by bcube** [comment]
I have the same problem. 

OS : masOC Mojave 10.12.1
Default Browser : Chrome 

However, when accessing the url devicelogin with Safari, I can login successfully for my VS Code.

**Comment by chrmarti** [comment]
@bcube Could you try with an incognito window in Chrome?

**Comment by bcube** [comment]
@chrisbenti I tried incognito and it works and i can login in my VS Code. 

I also tried to logout from azure.portal in my **normal** window but it is still not working.

**Comment by chrmarti** [comment]
@bcube You could try deleting the cookies the login page has set. Just start the login and on the first page navigate to the cookies:
![image](https://user-images.githubusercontent.com/9205389/49455902-4496b180-f7e8-11e8-9928-d4f5683afc12.png)

Clicking the cookies text will open a dialog where you can delete them.

**Comment by bcube** [comment]
@chrmarti Thanks! It works now!!
