### ISSUE TITLE
Multiline search results sometimes shows second line

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#62204]
- VSCode Version: 1.29 Insiders
- OS Version: Windows 10

Found while testing https://github.com/Microsoft/vscode/issues/62102

Steps to Reproduce:

1. Try `(---\n# )` in vscode-docs repo

![image](https://user-images.githubusercontent.com/12818376/47751803-ff62eb00-dc4f-11e8-875a-5c97e3adbc2b.png)

If you select the first search result to open in the editor and then the second, the correct first line result is shown.

![image](https://user-images.githubusercontent.com/12818376/47751919-510b7580-dc50-11e8-8742-9211ed5528af.png)

**Comment by roblourens** [comment]
#62186
