### ISSUE TITLE
Shift click multi-selection not as expected in Git viewlet

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#6220]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Make some changes on a few files (more than 5)
2. Change to the Git viewlet
3. Click on a file under changes in the middle (file 3)
4. Hold shift
5. Click on file 5 (should have files 3-5 selected)
4. Keep holding shift, click on file 2.

In file explorer clicking files above or below while holding shift only selects the files above or below the originally clicked file. I would expect the same behavior here.

**Comment by isidorn** [comment]
This is as desgined. The git viewlet is the only viewlet that support multiple selection.
The issue here is that our explorer does not support multi select yet.
