### ISSUE TITLE
Merge conflict marker in `package-lock.json` in hello code sample

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#62209]
Testing https://github.com/Microsoft/vscode/issues/62107

There are some conflict markers in the lock file that got checked in:
https://github.com/Microsoft/vscode-extension-samples/blob/ddf6bc3826d4eefd16605741b0edf64703239625/hellocode-sample/package-lock.json#L49

**Comment by octref** [comment]
Thanks, I do remember I resolved all merge conflicts shown in the Git UI, not sure why there would be some left out.
