### ISSUE TITLE
Multiline search selects one too many characters in the editor

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#62203]
- VSCode Version: 1.29 Insiders
- OS Version: Window 10

Found while testing https://github.com/Microsoft/vscode/issues/62102

Steps to Reproduce:

1. Try search with one character ending the match `(---\n# D)`

Sometimes an extra character is included in the editor selection.

![image](https://user-images.githubusercontent.com/12818376/47751524-3ab0ea00-dc4f-11e8-8321-946b93c2fed4.png)

It happens on the first open of the editor. If you go to another file and then come back the selection is correct.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by gregvanl** [comment]
Not surprisingly, the over selection also affects search and replace removing the extra character.

![image](https://user-images.githubusercontent.com/12818376/47753846-30deb500-dc56-11e8-8891-c0a2c11d3580.png)

**Comment by roblourens** [comment]
#62186
