### ISSUE TITLE
Tree API: When using async `getChildren` of TreeDataProvider, no progress on revealing

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#62214]
Testing #62073

I made the `getChildren` wait 2 seconds before returning:

```ts
		getChildren: (element: { key: string }): Thenable<{ key: string }[]> => {
			return new Promise(resolve => {
				setTimeout(() => {
					resolve(getChildren(element ? element.key : undefined).map(key => getNode(key)))
				}, 2000)
			})
		},
```

The result of using `Reveal` on `aaaaa`: Nothing happens for 10 seconds.

I think we should use the progress API for indication.

**Comment by eamodio** [comment]
I think this is somewhat related to this: https://github.com/Microsoft/vscode/issues/54806

**Comment by eamodio** [comment]
Since #54806 is locked and this is related, and the custom views are using the new tree now -- is this something that should work?

/cc @alexr00

**Comment by alexr00** [comment]
I just tested it, and it appears to work. Are you seeing it work?

**Comment by eamodio** [comment]
I haven't had a chance to try it, sorry.

**Comment by eamodio** [comment]
@alexr00 It doesn't seem to be working for me. If you add a node with the state `TreeItemCollapsibleState.Expanded` with children that take a while the node won't show up in the tree until all the children are loaded.

**Comment by alexr00** [comment]
Discussed with Joao, and we don't have a clear solution for this.
