### ISSUE TITLE
Proposal: Ability to move Debugging bar - or auto-shift for long file location paths

### ISSUE THREAD

**Issue by MarkPieszak** [Microsoft/vscode#6221]
Is it possible to have the `debugging bar`? It's difficult to see the file currently being viewed in when you're stepping through a debug process.

It'd be nice for it to either (self-shift) for long *location paths* or be able to move it someplace yourself. When debugging through large Node applications you can't see exactly what file you're working on, or where it is located. You have to constantly hover over the tab to see it.

Love code otherwise, great job guys :)

**Comment by isidorn** [comment]
Thanks for the suggestions however this is a dupe of #4580

**Comment by MarkPieszak** [comment]
Ahhh I didn't find that one! Apologies.
Hopefully it's on the radar :)
