### ISSUE TITLE
Tree API bug when having highlight [[2, -1]]

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#62211]
Testing #62073

Code:

```ts
		label: <vscode.TreeItemLabel>{ label: key, highlights: key.length > 1 ? [[2, -1]] : void 0},
```

Behavior:

![image](https://user-images.githubusercontent.com/4033249/47753146-cf1d4b80-dc53-11e8-8680-fc038f3d55fa.png)

**Comment by octref** [comment]
Same kind of bug when you have `[[2, 1]]`: 
![image](https://user-images.githubusercontent.com/4033249/47753218-01c74400-dc54-11e8-8c89-baa46a6e55d4.png)

**Comment by alexr00** [comment]
I think the desired behavior here is to have negative numbers count in from the end of the string (ex. 2,-1 would highlight from 2 up to, but not including, the last character in the string).
