### ISSUE TITLE
TreeItem.highlights should have proper documentation

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#62210]
Testing #62073

Without proper documentation, I cannot find what's the numbers that's passed in are used for.

**Comment by octref** [comment]
I think it's better to make it an array like `[{ start: number, end: number }]`.

**Comment by sandy081** [comment]
Added more doc to describe what a range is.

```ts
/**
 * Ranges in the label to highlight. A range is Defined as a tuple of two number where the
 * first is the inclusive start index and the second the exclusive end index
 */
highlights?: [number, number][];
```

This format is used because it is also used in other places in the API.

**Comment by octref** [comment]
> Defined

Can you also fix the casing for that?
