### ISSUE TITLE
Multiline search and replace results line count lost in space

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#62213]
- VSCode Version: 1.29 Insiders
- OS Version: Windows 10

Found while testing https://github.com/Microsoft/vscode/issues/62102

Steps to Reproduce:

1. Try multiline search and replace in vscode-docs repo `(Questions\n\n###)`
2. Drag the search view wide.

The results line count ('+2') are spread out across the blank space.

![image](https://user-images.githubusercontent.com/12818376/47753763-e0ffee00-dc55-11e8-959f-ed27e5afd710.png)

**Comment by roblourens** [comment]
#62186

**Comment by roblourens** [comment]
Actually keeping this open for verification since it's a bit different
