### ISSUE TITLE
Cannot open any hyperlinks in non-administrator mode (Windows)

### ISSUE THREAD

**Issue by JeffreyCA** [Microsoft/vscode#62219]
- VSCode Version: 1.28.2
- OS Version: Windows 10 (1809)

Steps to Reproduce:

1. Install VS Code to `C:\Program Files\Microsoft VS Code`
2. Open as user (not Admin)

All hyperlinks (e.g. Release Notes, Extension pages) do not open the link in the browser. I'm using Google Chrome as my default browser. They open if I run VS Code as Admin.

Does this issue occur when all extensions are disabled?: Yes

**Comment by JeffreyCA** [comment]
Update: I restarted my Chrome browser and seems to be working again. Weird glitch.

**Comment by kieferrm** [comment]
Thanks for reporting this. I'll close this as restarting Chrome fixed your issue.
