### ISSUE TITLE
Inconsistent terminology referring to viewlet in commands

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#62218]
#62097

Looking at the commands list we refer to the viewlet as "viewlet", "sidebar" and "sideBar".

**Comment by isidorn** [comment]
Here's our general principles:
1. Never expose term `viewlet` in the UI
2. Everything under the "view" command is actually a `view`. We just use the term view in general everywhere, which I think is fine

Now taking this into account please let me know where you think we are incosistent and what exact wording would you expect us to change?

Thanks!

**Comment by octref** [comment]
View lost meaning if it's the same as "box". 

> Never expose term viewlet in the UI

You can find a bunch of them as context keys and command names. Should we start deprecate / remove them? For example, `explorerViewletVisible` and `searchViewletVisible`.

**Comment by octref** [comment]
What I want is tracked in https://github.com/Microsoft/vscode-docs/issues/1842, so maybe @Tyriar can clarify what changes he wants.

**Comment by Tyriar** [comment]
I was just bringing attention to the inconsistencies
