### ISSUE TITLE
Keyboard navigation on problems panel breaks if problems are created while navigating

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode#62220]
Testing #62063

Using keyboard to navigate the the problems panel with multiple files having problems, I cannot navigate the files correctly. With the below structure, as I press down through extension.ts errors, everything work as expected. Once I get to the first error in tsconfig.json, it open tsconfig.json to reveal the error as expected but then focus is moved in the problems panel to extensions.ts again.

This is likely due to the way I am generating diagnostics, when a file is focused, it gets a new problem and the others remain; however, this shouldn't break the experience imo.

![image](https://user-images.githubusercontent.com/6561887/47755718-8ae27900-dc5c-11e8-9b4f-a983d2bc403a.png)

**Comment by sandy081** [comment]
Planning to October as this is a regression.

**Comment by sandy081** [comment]
![kapture 2018-11-02 at 9 55 49](https://user-images.githubusercontent.com/10746682/47904541-8a78f680-de85-11e8-9b88-a2edf9204197.gif)

**Comment by sandy081** [comment]
Verified running from Sources
