### ISSUE TITLE
PS Terminal Scroll Bar missing

### ISSUE THREAD

**Issue by timchapman** [microsoft/vscode#62226]
Issue Type: <b>Bug</b>

Can't scroll through results in PS terminal

VS Code version: Code - Insiders 1.29.0-insider (4b2fac2b6da220f62ff58b2766e4ecc1f561be94, 2018-10-30T16:54:48.685Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.79GB (41.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
macros|ged|1.2.1
mssql|ms-|1.4.0
PowerShell|ms-|1.9.0
team|ms-|1.142.0

</details>

**Comment by kieferrm** [comment]
@timchap can you pls attach a gif recording? Thanks!
