### ISSUE TITLE
Middle Click to only Close Current Tab

### ISSUE THREAD

**Issue by KyleMit** [Microsoft/vscode#62229]
Not sure if this is a bug or feature, but when I middle click an open editor tab, Visual Studio Code closes all or some of the tabs to the right.  In most other tab based editors, middle clicking a tab will only close the current tab.  

This might have something to do with "Close To The Right"
<img width="486" alt="Screen Options" src="https://user-images.githubusercontent.com/4307307/47761443-ba11de00-dc8e-11e8-99a6-41ef4c9ee22b.png">

Here's what happens when I middle click a single time on one tab

<img width="486" alt="Screenshare" src="https://user-images.githubusercontent.com/4307307/47761629-8d11fb00-dc8f-11e8-9a39-1777f8a424f0.gif">

Is this the supported behavior?  Is there any way to change in Workbench Settings?

**Comment by bpasero** [comment]
@KyleMit I cannot reproduce, are you using a normal mouse?

![grid-tw](https://user-images.githubusercontent.com/900690/47780650-1828da80-dcfc-11e8-92a3-1f7e9b095eb1.gif)

@isidorn maybe you could also try

**Comment by isidorn** [comment]
Works for me also
@KyleMit can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
