### ISSUE TITLE
нет тегов 

### ISSUE THREAD

**Issue by SergeyUgnat** [Microsoft/vscode#62225]
Issue Type: <b>Bug</b>

нет двух тегов преведу пример align  и bgcolor

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2130 CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.96GB (0.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
browsersync|jer|1.1.1
vscode-language-pack-ru|MS-|1.28.2
debugger-for-chrome|msj|4.10.2
open-html-in-browser|pea|0.0.3
open-in-browser|tec|2.0.0

</details>

**Comment by kieferrm** [comment]
@SergeyUgnat pls provide more details. Thanks!

**Comment by oneslash** [comment]
@SergeyUgnat, пожалуйста используйте английский язык.

**Comment by oneslash** [comment]
@chrmarti, I think we can close the ticket.

**Comment by chrmarti** [comment]
@oneslash Thanks.
