### ISSUE TITLE
Parsing arguments passed to debug providers

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/vscode#62233]
- VSCode Version: 1.25.2
- OS Version: 10.13.5

We can pass custom arguments in our debug providers' configurations, e.g.:

```javascript
args: [`--extensionDevelopmentPath=${rootPath}`]
```

For some reason the following isn't properly parsed:

```javascript
args: [`--extensionDevelopmentPath="${rootPath}"`]
args: [`--extensionDevelopmentPath='${rootPath}'`]
```

Notice that I'm quoting the value of the `extensionDevelopmentPath` option.

Is this documented anywhere? Is this a bug?

**Comment by weinand** [comment]
What do you mean by "the following isn't properly parsed"?
What error are you seeing?

Instead of putting quotes around the rootPath to protect paths with spaces, you can let VS Code do the work:
```

args: [`--extensionDevelopmentPath`, `${rootPath}`]
```
VS Code will quote arguments that contain spaces.

**Comment by fabiospampinato** [comment]
> What do you mean by "the following isn't properly parsed"?

I get this error, basically the quotation marks are preserved and a slash is added at the beginning:

<img width="466" alt="screen shot 2018-10-31 at 13 33 13" src="https://user-images.githubusercontent.com/1812093/47788311-9e035080-dd11-11e8-8cbe-03b8f1915f35.png">

> args: [`--extensionDevelopmentPath`, `${rootPath}`]
> VS Code will quote arguments that contain spaces.

That's exactly what I need, thanks.

Does VS Code quote arguments that are write like this: `--extensionDevelopmentPath=${rootPath}` too?
