### ISSUE TITLE
java开发 缺少快捷键；Java development lacks shortcut keys

### ISSUE THREAD

**Issue by 410919244** [Microsoft/vscode#62235]
在eclipse中鼠标悬浮在类名上 使用ctrl+T可以查看接口的所有实现类，或者所有的继承类。vscode似乎没有这个快捷键。还有鼠标悬浮在方法名上按住ctrl后出现选项可选择跳转到接口定义或者选择跳转到方法的实现。这两个快捷键对开发者来说很重要，但目前我不知道在vsvode中怎么使用这两个功能。如果有这两功能我可能会放弃使用eclipse。

In eclipse, hover over the class name and use Ctrl + T to view all the implementation classes of the interface, or all the inherited classes. Vscode does not seem to have this shortcut. There are also options that appear when the mouse hovers over the method name and holds down Ctrl to choose to jump to the interface definition or to choose to jump to the implementation of the method. These two shortcuts are important to developers, but I don't know how to use them in vsvode at this point. If I have these two functions, I may give up using eclipse.

**Comment by kieferrm** [comment]
@410919244 Please file the issue against https://github.com/redhat-developer/vscode-java/issues. Thanks!
