### ISSUE TITLE
window.showOpenDialog doesn't respect filters option

### ISSUE THREAD

**Issue by testforstephen** [Microsoft/vscode#62237]
Env:
```
Version: 1.29.0-insider (system setup)
Commit: 4b2fac2b6da220f62ff58b2766e4ecc1f561be94
Date: 2018-10-30T16:54:48.685Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
Steps to Reproduce:
```

In Insider version, the API `window.showOpenDialog` doesn't respect the `filters` option.
```
{
  ...,
  filters: { "Source files": ["jar", "zip"] }
}
```
The same code works in the normal vscode 1.28.2.

**Comment by sbatten** [comment]
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/dialogs/electron-browser/dialogService.ts#L276

The code here converts the filters from the extension API into the electron API, but the function is supplied with the electron API format so this is not necessary and is causing the break.

**Comment by isidorn** [comment]
We believe this is a regression, adding candidate label
