### ISSUE TITLE
VS Code unable to find test when running single unit test

### ISSUE THREAD

**Issue by ahyerman** [Microsoft/vscode#62238]
Issue Type: <b>Bug</b>

Python: 3.6.6
Pytest: 3.8.2

When trying to run an individual test, vs code seems to fail with `ERROR: file not found: <file>::<class>::<method>`. It seems VS Coder can find the test since the command to run all tests works, also all tests appear to be discovered when running either all or a single test. However when running a single test I am seeing the above failure. I've tried to enforce the path to ensure the `pytest.ini` and `rootdir` are set correctly and that also fails.

# Repro:
## workspace settings:
           "folders": [
		{
			"path": "C:\\proj"
		}
	],
		"python.unitTest.pyTestArgs": [
			"--show-capture=no",
			"-ra",
			"-Wignore",
		],
		// Whether to enable or disable unit testing using pytest.
		"python.unitTest.unittestEnabled": false,
		"python.unitTest.pyTestEnabled": true,
		"python.unitTest.nosetestsEnabled": false,
## folder structure:
/proj
|___/tests
|______pytest.ini
|______/scenario1
|_________test_1_s1.py
|_________test_2_s1.py
|______/scenario2
|_________test_1_s2.py
|_________test_2_s2.py

It seems this error only appears when trying to run or debug a single unit test, as running all tests seems to succeed.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|47.79GB (29.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.5.6
nbpreviewer|jit|1.0.0
python|ms-|2018.9.2
PowerShell|ms-|1.9.0
team|ms-|1.142.0

</details>

**Comment by ahyerman** [comment]
It seems [Can't run single method or class unit test using PyTest in editor (#58070)](https://www.github.com/Microsoft/vscode/issues/58070) is tangentially related. However the problem here is not that pytest in editor, but rather once triggering a single test through command palette.

**Comment by ahyerman** [comment]
It seems like the problem is coming out of the working directory being incorrect

**Comment by ahyerman** [comment]
Seems this working directory issue can be solved by including multiple paths in the folders option on the workspace. It'd be great if the python.unittest.cwd option could be used for pytest as well!

**Comment by kieferrm** [comment]
@ahyerman can you please file the issue against the Python extension at  https://github.com/Microsoft/vscode-python/issues. Thanks!
