### ISSUE TITLE
High contrast theme adjusts spacing on call stack file names

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#6223]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows 10

Steps to Reproduce:
1. Change theme to High Contrast
2. Debug
3. Hover over call stack items

![highcontrastcallstack](https://cloud.githubusercontent.com/assets/12900364/15131117/165ac2c2-1602-11e6-9089-0fb4b04bf161.gif)

**Comment by bgashler1** [comment]
@vsccarl awh yes.  Thanks for reporting this.  Will get on it.
