### ISSUE TITLE
Undocumented `execPath` placeholder

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#62231]
We have this thing in the launch configuration of extensions: `runtimeExecutable: '${execPath}'`.

The `execPath` placeholder doesn't seem to be documented anywhere.

I assume it points to the current VSC executable, right?

**Comment by weinand** [comment]
yes, correct.
It is an implementation detail of extension debugging.

**Comment by fabiospampinato** [comment]
@weinand I wouldn't call it an implementation detail since all extensions authors are required to create a launch configuration, where `execPath` must be used` in order to debug their extension.

**Comment by rrd108** [comment]
In my case it points to electron instead of vscode executable. There is no information how to change it, or why it is set incorrectly.

**Comment by weinand** [comment]
If you are running out of source, "execPath" will point to electron.
