### ISSUE TITLE
PowerShell integration console / terminal hangs on starting

### ISSUE THREAD

**Issue by skeeler** [Microsoft/vscode#62232]
- VSCode Version: 1.28.2
- OS Version: Windows 10 version 1809 (build 17763.55)

Steps to Reproduce:

1. Start VS Code
2. Open Terminal window
3. See Windows PowerShell / Copyright (C) Microsoft Corporation. All rights reserved.
4. Does not return to "PS C:\Users\<uname>" prompt - hangs

Does this issue occur when all extensions are disabled?: Yes/No
Yes, the same problem occurs when starting VS Code with extensions disabled.
The command window (where VS Code was started from), displays:
```
[main 10:06:34 PM] update#setState idle
[main 10:07:04 PM] update#setState checking for updates
[main 10:07:05 PM] update#setState idle
```
![2018-10-30 22_01_14-extension_ azure account - visual studio code](https://user-images.githubusercontent.com/755941/47761816-63a59f00-dc90-11e8-9332-487c9d8bdbc3.png)

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/57803
