### ISSUE TITLE
Blind snippet insertion

### ISSUE THREAD

**Issue by safield** [microsoft/vscode#62236]
I have a workflow problem with snippets and completions.

I have concluded snippets and suggestions are different, and they should be treated separately. At the least, there should be a setting _blindSnippetCompletion_.

My issue is as follows.

1. I know my user snippets off by heart. I use them often, and deliberately. I don't need to a list to present my snippets to me. I don't need to shop around in a grocery list of snippets (and other suggestions) to find the right one. I just type the string and hit tab.

2. I like my snippets to work reliably 100% of the time. So when I type "msg1" followed by the tab key, I want my message write snippet to be placed 100% of the time. I don't want completion suggestions injected by language support extensions unpredictably interrupting my snippet insertion muscle memory. 

3. I don't want any snippets cluttering up my quick suggestions list. Like I mentioned previously, I already know all my snippets, and in some cases I have to cycle through a couple snippets to get to the desired suggestion. I want the suggestions list exclusively for variable, method, and type completions.....not snippets.

With the current settings available in vscode...

"editor.snippetSuggestions": "bottom" Solves issue 3. but exacerbates issue 2.
"editor.snippetSuggestions": "top" Solves issue 2. but exacerbates issue 3.
"editor.snippetSuggestions": "inline" is worst of both worlds.

Enter _blindSnippetCompletion_.

With this setting enabled, pressing tab (insert snippet), will always prioritise snippet insertion over quick suggestion or intellisense completion. But snippets will never show up in completion suggestions lists.

**Comment by jrieken** [comment]
We can offer these settings: `"editor.tabCompletion": "onlySnippets",    "editor.snippetSuggestions": "none", "editor.quickSuggestions": false,`  With them no snippets will ever show in the suggestion list, suggestions won't show as type (the prefix of a snippet), and pressing Tab after a snippet prefix will expand it.

**Comment by safield** [comment]
I can try those out, but "editor.tabCompletion" : "onlySnippets" sounds like it would disable suggestions tab completion. This would not be desirable.
