### ISSUE TITLE
`debug.startDebugging` doesn't work with named configurations

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#62230]
- VSCode Version: 1.28.2
- OS Version: 10.13.5

Steps to Reproduce:

1. Add a launch configuration with name `Foo`.
2. Execute `vscode.debug.startDebugging ( undefined, 'Foo' );` from an extension.
3. Instead of launching the debugger I get this error `'launch.json' does not exist.`, needless to say that `launch.json` exists and that I can actually start the `Foo` configuration from the debug view.

**Comment by weinand** [comment]
the documentation of startDebugging says it all:
```
		/**
		 * Start debugging by using either a named launch or named compound configuration,
		 * or by directly passing a [DebugConfiguration](#DebugConfiguration).
		 * The named configurations are looked up in '.vscode/launch.json' found in the given folder.
		 * Folder specific variables used in the configuration (e.g. '${workspaceFolder}') are resolved against the given folder.
		 * @param folder The [workspace folder](#WorkspaceFolder) for looking up named configurations and resolving variables or `undefined` for a non-folder setup.
		 * @param nameOrConfiguration Either the name of a debug or compound configuration or a [DebugConfiguration](#DebugConfiguration) object.
		 * @return A thenable that resolves when debugging could be successfully started.
		 */
```
If you pass `undefined` as the folder, the launch config cannot be found.
