### ISSUE TITLE
Project level snippets should not show up when editing the launch.json

### ISSUE THREAD

**Issue by qiulang** [microsoft/vscode#62240]
- VSCode Version: 1.28.2 
- OS Version: macOS 10.14

Project code snippets  should not show up when editing the launch setting, it is quite misleading when they show up.

Steps to Reproduce:

1. use the Preferences: Configure User Snippets command to create a xxx.code-snippets file in the .vscode folder
2. edit the launch setting (`launch.json`), click "add configuration..."  the pop-up show all launch settings and the code snippets I just added.

**Comment by isidorn** [comment]
@jrieken currently I am simply triggering this action from the launch.json
`this.commandService.executeCommand('editor.action.triggerSuggest')`
Is there some way to triggerSuggest and exclude the project level snippets?

**Comment by jrieken** [comment]
Yeah, you can use this: https://github.com/Microsoft/vscode/blob/220bff273eed39013f24b6d26fc17f2a742ce10f/src/vs/editor/contrib/suggest/suggest.ts#L270

**Comment by isidorn** [comment]
It seems like the showSimpleSuggestions requires an array of Suggestions, which I do not have.
If I pass an empty array my suggestions do not show up.

The issue here is that my suggestions are also snippet suggestions and we do not have diferentiator between debug snipets and project level snippets

**Comment by jrieken** [comment]
Well you suggestion come from somewhere, right?

**Comment by isidorn** [comment]
Yeah they come declarativly from package.json, and I feed them into the JSON schema.
To get this nicely flowing through I would have to restructure who is reading the JSON schema and whos is triggering the Add Configuration command, which I do not want to do atm -> backlog.

**Comment by jrieken** [comment]
Well your choice, but I'd say it trival to achieve
