### ISSUE TITLE
formatOnSave not working

### ISSUE THREAD

**Issue by nileshpawar-xento** [Microsoft/vscode#62243]
Issue Type: <b>Bug</b>

I have added following settings
"editor.formatOnPaste": true,
    "editor.formatOnSave": true,
    "files.autoSave": "off"

but formatting code is not working properly. Kindly suggest do I need to make any other settings also?

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.88GB (3.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|9.0.1
npm-intellisense|chr|1.3.0
auto-close-tag|for|0.5.6
vscode-prettier-standard|iSa|0.0.2
vscode-jetbrains-keybindings|isu|0.1.8
vscode-language-babel|mgm|0.0.21
vsliveshare|ms-|0.3.897
prettier-standard-vscode|num|0.3.0
vscode-icons|rob|7.28.0

</details>

**Comment by kieferrm** [comment]
@nileshpawar-xento can you please provide more details. What files are you working on?

**Comment by carlodri** [comment]
same problem here in formatting python files with black. Format document command works but format on save does not. This is my user configuration:

```json
{
    "python.linting.pylintEnabled": false,
    "python.linting.flake8Enabled": true,
    "python.linting.enabled": true,
    "python.condaPath": "C:\\Miniconda3x64\\Scripts",
    "python.pythonPath": "C:\\Miniconda3x64\\envs\\pythr02-env\\python.exe",
    "workbench.iconTheme": "vscode-icons",
    "diffEditor.renderSideBySide": false,
    "autoDocstring.docstringFormat": "google",
    "editor.formatOnSave": true,
    "git.autofetch": true,
    "python.formatting.provider": "black"
}
```

Using VSCode:
```
Version: 1.30.2 (user setup)
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:54:13.295Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134
```

**Comment by rob-miller** [comment]
Issue Type: <b>Bug</b>

Editing a 2200 line python file with autopep8 configured to format on save, the formatting says it is happening in the blue line at the bottom, however (1) issues it should fix remain, and (2) the blue line clears within a second or so - but the Format On Save Timeout is set to 6000 msec

VS Code version: Code 1.32.2 (e64cb27b1a0cbbc3f643c9fc6c7d93d6c6509951, 2019-03-13T01:56:08.693Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|32.00GB (0.25GB free)|
|Process Argv|-psn_0_14818849|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.6
gitlens|eam|9.5.1
vscode-pyvmmonitor|fab|0.0.3
git-project-manager|fel|1.7.1
code-runner|for|0.9.7
vscode-emacs-friendly|lfs|0.8.2
python|ms-|2019.2.5558
python-coding-tools|nil|1.0.2
local-history|xyz|1.7.0


</details>

**Comment by chrmarti** [comment]
Thanks @rob-miller and @carlodri, could you open a new issue for us to track yours separately?

I'm closing this one since we haven't heard back from @nileshpawar-xento. Sorry for the delay.

**Comment by rob-miller** [comment]
Thanks @chrmarti, no worries.  I had the issue after restarting vscode, but a power fail this morning led to a full system restart and now I cannot reproduce.  Job done!  Will open new if I see it again.
