### ISSUE TITLE
Tasks with dollar sign

### ISSUE THREAD

**Issue by omartin2010** [Microsoft/vscode#62241]
Issue Type: <b>Bug</b>

Create a task (in tasks.json):
```
{
            "label": "Remote_PyKill",
            "command":"awk '{print $2}' out.txt | xargs echo",
            "type": "shell"
}
```
the $2 in awk is completely ignored... so unable to parse the output of this file. Was trying in other ways and I'm out of ideas at this point. I'm using bash as the terminal shell in this case, on w10.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (7.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
azure-storage-explorer|for|0.1.2
vscode-azurefunctions|ms-|0.12.0
vscode-cosmosdb|ms-|0.8.0
python|ms-|2018.9.2
vscode-ai|ms-|0.3.1
azure-account|ms-|0.4.3
csharp|ms-|1.16.2
azure-iot-edge|vsc|1.5.0
azure-iot-toolkit|vsc|1.5.0

</details>

**Comment by dbaeumer** [comment]
@alexr00 can you please investigate. I think it might be a problem on how we pass this on to the terminal.

@omartin2010 which bash shell are you using ?

**Comment by alexr00** [comment]
Yes, I will look into this.

**Comment by omartin2010** [comment]
@alexr00 , so I said I'm running 16.04, I made a mistake. I'm running 18.04. Just reinstalled ubuntu on my machine for some reason, not realizing a new install would give me that new version.

**Comment by omartin2010** [comment]
And I've confirmed the issue is there with 16.04 and 18.04.

**Comment by alexr00** [comment]
@omartin2010, what is the output from the task?

**Comment by omartin2010** [comment]
task : 
```
{
            "label":"Test task",
            "type": "shell",
            "isBackground": false,
            "command" : "ssh 192.168.32.51 ps -ef | awk '{print \"test\"$2}'"
}
```
output : 
```
> Executing task: ssh 192.168.32.51 ps -ef | awk '{print "test"$2}' <

test
test
test
test
test
```
so basically the same thing as if I didn't put the $2. With the $2 only, I'd get that : 
```
> Executing task: ssh 192.168.32.51 ps -ef | awk '{print $2}' <

UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 13:53 ?        00:00:06 /sbin/init
root         2     0  0 13:53 ?        00:00:00 [kthreadd]
root         4     2  0 13:53 ?        00:00:00 [kworker/0:0H]
```
which is not what I'm trying to do... (which is to extract token 2).
Does this help?

**Comment by alexr00** [comment]
Yes thanks, I am able to reproduce.

**Comment by alexr00** [comment]
I think this is an issue with bash. I have file out.txt:

    test1 test11
    test2 test22
    test3 test33

From cmd.exe I run ` bash.exe -c "awk '{print $2}' out.txt | xargs echo"`
I expect:
test11 test22 test33
I get:
test1 test11 test2 test22 test3 test33

If you can find a variation of this command that works from cmd then it _should_ work from VS Code (we do have some character escaping issues, so you could always run into one of those, but in that case we'll try to fix it).

**Comment by omartin2010** [comment]
So I'm running this on bash on WSL directly, within bash : 

```
~ vi out.txt
~ awk '{print $2}' out.txt | xargs echo
test11 test22 test33
~
```
Agree, it seems like it's not a bug with vscode, but clearly it's a bug with something. What would that be?

**Comment by alexr00** [comment]
I found a command that should work for you 😊 try escaping your `$`:

    {
        "label": "dollar",
        "command":"awk '{print \\$2}' out.txt | xargs echo",
        "type": "shell"
    }

**Comment by omartin2010** [comment]
LOVE IT! :) thank you!

**Comment by omartin2010** [comment]
and btw this should be documented...

**Comment by alexr00** [comment]
It's a Windows/WSL/bash thing. I'll see if I can track down where in the Windows docs that would go.

**Comment by omartin2010** [comment]
a nice thing - I guess see this as a feature request - would be to have a property of a task that specifies if task X runs on powershell.exe, cmd.exe, ,or bash.exe (which shell it "natively" runs on).

**Comment by alexr00** [comment]
This already exists. In your task:

    "options": {
        "shell": {
            "executable": "bash.exe"
        }
    }

**Comment by omartin2010** [comment]
great! Except when I use it, I get this :
```
> Executing task: sleep 3 <

/bin/bash: sleep 3: No such file or directory
The terminal process terminated with exit code: 127

Terminal will be reused by tasks, press any key to close it.

> Executing task: /bin/sleep 3 <

/bin/bash: /bin/sleep 3: No such file or directory
The terminal process terminated with exit code: 127

Terminal will be reused by tasks, press any key to close it.
```
And for that, my task definition is 

```
 {
            "label": "test-task",
            "type": "shell",
            "isBackground": false,
            "command" : "/bin/sleep 3",
            "options": {
                "shell": {
                    "executable": "bash.exe"
                }                
            }
        }
```
I've tried with 'bash.exe -c' as the shell, also with command = "sleep 3" (which is what you see above in the first output) or this one with 'bin/sleep 3' when I know that's exactly where it is... at least from bash's point of view (once bash is started). It probably works but isn't obvious how... am I missing something here?

**Comment by dbaeumer** [comment]
The options need to be like this:
```
"options": {
    "shell": {
        "executable": "bash.exe",
        "args": ["-c"]
    }
}
```

**Comment by omartin2010** [comment]
that did work, thanks @dbaeumer !
