### ISSUE TITLE
Please just always update in the background

### ISSUE THREAD

**Issue by Plasma** [Microsoft/vscode#62244]
Issue Type: <b>Feature Request</b>

It's great you're shipping so many updates, but each time I open VS Code it nags me if I want to update or not -- just do it and have the next time I open its already updated.

Thank you!

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:57:45.963Z)
OS version: Windows_NT ia32 10.0.17134

**Comment by kieferrm** [comment]
Please use the user installer. 
<img width="325" alt="image" src="https://user-images.githubusercontent.com/4674940/47967826-9c3dd380-e016-11e8-8e0d-1f9e0d148ca9.png">

VS Code will then update in the background and will notify you that's ready to reload.
<img width="50" alt="image" src="https://user-images.githubusercontent.com/4674940/47967838-b8da0b80-e016-11e8-8cc5-74017d4c75dd.png">
