### ISSUE TITLE
I can't compile my code

### ISSUE THREAD

**Issue by Sidious209** [Microsoft/vscode#62254]
Issue Type: <b>Bug</b>

The java.home variable defined in VS Code settings does not point to a JDK

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
java|red|0.33.0
vscode-java-debug|vsc|0.14.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.10.0
vscode-maven|vsc|0.11.1

</details>

![image](https://user-images.githubusercontent.com/44046364/47777754-fd6c5b00-dd27-11e8-81c9-5ac8bd837d94.png)
I have already downloaded Language Support for Java(TM)....
![image](https://user-images.githubusercontent.com/44046364/47777826-2a207280-dd28-11e8-96d7-8ef4d9218c12.png)

**Comment by kieferrm** [comment]
@Sidious209 please file the issue against https://github.com/redhat-developer/vscode-java/issues. Thanks!
