### ISSUE TITLE
PHP files open in 1 column

### ISSUE THREAD

**Issue by MeenaFawzy** [Microsoft/vscode#6225]
- VSCode Version: 1.1.0
- OS Version: Windows 10

Steps to Reproduce:

1. Update VSCode from v1 to v1.1.0
2. Open any PHP file
3. PHP file oepn as a single column in the editor, sceenshot below
https://cloud.githubusercontent.com/assets/89722/15133201/2e04ef38-1661-11e6-8cdb-d8e332e4e7cb.png

**Comment by isidorn** [comment]
What is your editor.wrappingColumn, might you be facing this issue https://github.com/Microsoft/vscode/issues/6219
Does changing your editor.wrappingColumn to -1 solve the issue?
Do you only see this for PHP files or for any file?

**Comment by MeenaFawzy** [comment]
i found out that i already had "editor.wrappingColumn": 1000 in my settings, after removing it the problem solved.
