### ISSUE TITLE
vs code (1.28.2) version is not launching in offline mode 

### ISSUE THREAD

**Issue by amkr2525** [Microsoft/vscode#62250]
- VSCode Version:1.28.2
- OS Version: windows 10 

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alessiot89** [comment]
Can't Microsoft just fix this?
You have a full heap of duplicate issues like this, and the bug is like 2 years old.

**Comment by amkr2525** [comment]
i don't know, why this problem is arising ?But   initially it had worked in offline mode.

**Comment by alessiot89** [comment]
I guess it had to do with the tons of external dependencies..

**Comment by kieferrm** [comment]
This will be fixed as soon as we are on electron 3.0.

**Comment by amkr2525** [comment]
> I guess it had to do with the tons of external dependencies..

which vesion vs code are you using?

**Comment by amkr2525** [comment]
> /duplicate of #

> Thanks for creating this issue! We figured it's covering the same as another one we already have. Thus, we closed this one as a duplicate. You can search for existing issues [here](https://aka.ms/vscodeissuesearch). See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.
> 
> Happy Coding!

Still my problem is not solved.And you are saying this is duplicate but how? Initially it had worked properly but now it did not may be any setting problem may occur because in my laptop this problem occur but  my friend it doesn't.

**Comment by amkr2525** [comment]
> /duplicate of #7570

but how?

**Comment by amkr2525** [comment]
If you know the solution then please tell me but don't say any irrelevant thing.

> /duplicate of #7570

If you know the solution then please tell me but don't say any irrelevant thing.
