### ISSUE TITLE
open preview local image link error ?

### ISSUE THREAD

**Issue by djmisterjon** [Microsoft/vscode#62255]
Hi, when i add comment link to open a reference image with [ctrl+click], i get a error.
![image](https://user-images.githubusercontent.com/24865815/47777898-1810e680-dccc-11e8-8c40-38b819a2084a.png)
here the code 
![image](https://user-images.githubusercontent.com/24865815/47777984-41317700-dccc-11e8-852e-505f0011a014.png)
```javascript
/*#region [rgba(0, 200, 0, 0.04)]
┌------------------------------------------------------------------------------┐
  TEST OPEN PREVIEW IMAGE
  file://data2/Hubs/pinBar/hudsPinBar.png
  
└------------------------------------------------------------------------------┘
*/
```

The behavior i want get when i ctrl+click on the link is to open the image like this.
![image](https://user-images.githubusercontent.com/24865815/47778163-9d949680-dccc-11e8-9bc3-6dbe70fadc04.png)

Is the syntax correct or bug? or is not possible in VsCode ? 
thank a lot for help me understand.

**Comment by kieferrm** [comment]
It seems to me that your Url is missing a third slash. It should be `file://data2/Hubs/pinBar/hudsPinBar.png` since the path should be absolute.

**Comment by djmisterjon** [comment]
ok work, this it just insane in vscode !  if you need build a items DB
![image](https://user-images.githubusercontent.com/24865815/47833147-b43ff980-dd6f-11e8-82fe-b0eaf7fa0e49.png)
