### ISSUE TITLE
Terminal setting splitCwd didn´t expect to get prompted in the sourceInitialCwd case

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#62265]
Testing #62096 on Windows

I have a multi-root workspace setup and set the setting to `sourceInitialCwd`.

![image](https://user-images.githubusercontent.com/172399/47783418-f2eb9a80-dd02-11e8-8862-92b50a414081.png)

I did not expect that I have to select the root in this case, I was assuming it takes cwd of the first terminal that opened.

**Comment by alexr00** [comment]
@egamma, your assumption is correct! I can't reproduce this though. What were you doing before this happened?

**Comment by egamma** [comment]
I can no longer reproduce it, closing.
