### ISSUE TITLE
Allow sort order of code actions from multiple providers to be influenced

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#62267]
I have multiple code action providers and have been unable to sort them as I'd like (eg. one provider is low priority and should always come last).

I found this code:

https://github.com/Microsoft/vscode/blob/243168d450cac7b641ad33a3fc54171aa7c6a83c/src/vs/editor/contrib/quickFix/quickFix.ts#L43

Which suggests that the messages from the associated diagnostics are used - however I tried messing with these and it didn't seem to make any difference (it also seems weird to use the text message of the associated diagnostic which is not visible on the screen to sort with).

Is it possible to add some sort of rank to code actions to allow sorting from multiple providers to be influenced (or at least, the sorting rules documented).

(cc @mjbvz)

**Comment by jrieken** [comment]
> Is it possible to add some sort of rank to code actions to allow sorting from multiple providers to be influenced (or at least, the sorting rules documented).

:-1: for ranks et al. this will just make folks set their ranks to `MAX_VALUE` because you never know what other providers are installed from other extensions... We have to define (or document) the sort order by other means (I think today it is severity of the diagnostics they eventually tackle and label)

**Comment by DanTup** [comment]
> this will just make folks set their ranks to MAX_VALUE because you never know what other providers are installed from other extensions

I'm really not convinced that would happen for a few reasons:

1. Most languages only get fixes from one extension
2. Extension authors probably (hopefully) care more about delivering a good experience that putting their things at top - people will uninstall their extensions if they do stupid things
3. They can still "rig" things if you use the diagnostic message, they just have to be more creative (though FWIW, I couldn't make the sorting work at all - the code looks like it uses the message from the diagnostic - not the severity - which is unintuitive but also didn't seem to work)

That said,. I do agree coordinating ranks across extensions would be tricky. However I think there should be a solution within a single extension - why shouldn't an extension author have control of the order of their own quick fixes relative to each other?

**Comment by jdneo** [comment]
Hi @jrieken 👋 ,

I have the same request - to make result from a provider comes last.

The different part is that, @DanTup's case is one extension having multiple providers, so he can rank the providers by the extension itself. My case is that, the providers come from different extensions. And all the code actions have not set `isPreferred` and `diagnostics`. In that case, the rank of the provider determines the order of the code actions (according to https://github.com/microsoft/vscode/blob/94c9ea46838a9a619aeafb7e8afd1170c967bb55/src/vs/editor/common/modes/languageFeatureRegistry.ts#L166-L178)

I can easily make the results of the provider come first (e.g. postpone the code action provider registration), but so far I didn't find an easy way to make the results come last.
