### ISSUE TITLE
Workbench navigation sidebar should be sideBar or Side Bar in labels

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#62270]
Refs: #62097

Pease change all the names to be `sideBar`so capital B. Since these are two words across our UX. So the command names to be `workbench.action.previousSideBarView` and `workbench.action.nextSideBarView`
The context key to be `sideBarFocus`

Also change the Label to be `Previous Side Bar View` and `Next Side Bar View`

Thanks!

**Comment by isidorn** [comment]
While you are at it you could also change this wronlgy named command
`View: maximize editor group and hide sidebar` to be
`View: maximize editor group and hide side bar `

![screenshot 2018-10-31 at 12 33 28](https://user-images.githubusercontent.com/1926584/47785490-30ebbd00-dd09-11e8-93df-9080e699db23.png)

**Comment by octref** [comment]
Fixed via https://github.com/Microsoft/vscode/commit/fe5db1a8f5a448f5d3c0a1909a1e8f0c56c810ca. Tagged wrong issue though...
