### ISSUE TITLE
editor.tabCompletion breaks tab completion for components in jsx

### ISSUE THREAD

**Issue by alexmccabe** [microsoft/vscode#62279]
`"editor.tabCompletion": "on"` breaks `javascriptreact` tab completion on jsx components

- VSCode Version: 1.28.2
- VSCode Version: 1.29.0-insider
- OS Version: macOS 10.14

Steps to Reproduce:

1. Copy the following settings to settings.json
```
{
  "editor.formatOnSave": true,
  "javascript.format.enable": false,
  "files.associations": {
    "javascript": "javascriptreact"
  },
  "emmet.triggerExpansionOnTab": true,
  "editor.tabCompletion": "on"
}
```

2. Create a two new javascript files
3. Set language to javascript react
4. Import one file into the other, with an import name (e.g. `import SecondFile from './SecondFile';`)
5. Try to create some JSX with tab completion, just inserts space

![output](https://user-images.githubusercontent.com/2529110/47788044-87a4c700-dd08-11e8-8adb-cf37b75cec42.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
The behavior that expands `div` - >`<div></div>` comes from emmet, not from our JavaScript extension. Not sure if it can be configured to expand custom react components as well.

This does work if you use the custom component in a more complex expansion expression:

![Screen Shot 2019-05-17 at 3 53 54 PM](https://user-images.githubusercontent.com/12821956/57960127-ff5ccc80-78bb-11e9-9e89-b30feef3a635.png)

**Comment by octref** [comment]
@jrieken When `editor.tabCompletion` is set to true, emmet doesn't get a chance to expand on tab. Should the "tab to complete" behavior happen only when completion list is open?

**Comment by jrieken** [comment]
> Should the "tab to complete" behavior happen only when completion list is open?

That would be against the design of tab completion. The idea is that can just tab to complete, not interaction with the suggest widget needed. Ultimatively this boils down to a config issue, maybe an emmet issue as this shouldn't register on tab but be always part of completions, esp now that we have tab completions build in

**Comment by octref** [comment]
@alexmccabe As explained above, your config leads to an overloaded meaning of of `tab` in this case. If you set `"editor.tabCompletion": "on"`, I suggest remapping the `Emmet: Expand Abbreviation` command to another shortcut: 

![image](https://user-images.githubusercontent.com/4033249/58114687-27df1200-7bad-11e9-9e57-3096834a2ebe.png)

**Comment by alexmccabe** [comment]
I've used Emmet tab completion for _years_ across multiple editors and not run into the issue before, where custom tab completion would prevent Emmet from doing it's job. I understand the reasoning, and I'm unsure whether it's worth fighting my case on this.

For anyone who runs into this in the future, use this setting:

```
"editor.tabCompletion": "onlySnippets",
```

Allows Emmet to do it's job, and gives you access to your snippets and language features.
