### ISSUE TITLE
GitHub PR: Description "Comment" button is not clickable

### ISSUE THREAD

**Issue by alexr00** [Microsoft/vscode#62275]
![image](https://user-images.githubusercontent.com/38270282/47786293-9c368e80-dd0b-11e8-9e04-a2a667010bc8.png)

Found testing #62184

**Comment by Dob6458** [comment]
Maybe because a malfunctioning of Visual Studio Code.

**Comment by RMacfarlane** [comment]
Fixed by https://github.com/Microsoft/vscode-pull-request-github/commit/c269b46fb391c34310749c58687a6d9f7556a6b1

**Comment by RMacfarlane** [comment]
For verifiers:

Open the description webview and enter some text in the textarea without submitting it. Open a different file and then return to the webview. The text should be shown and all buttons should be enabled.

**Comment by alexr00** [comment]
@RMacfarlane, does this need a new version of the extension?

**Comment by RMacfarlane** [comment]
Yep, sorry, will release a new version of it
