### ISSUE TITLE
Select text => <kbd>Tab</kbd> / <kbd>Shift</kbd>+<kbd>Tab</kbd> ?

### ISSUE THREAD

**Issue by cottrell** [microsoft/vscode#62289]
_Originally posted by @usernamehw in https://github.com/Microsoft/vscode/issues/41262#issuecomment-355884705_

**Comment by cottrell** [comment]
Select indent right is not working again. Has there been a regression? Select shift-indent does work.

**Comment by rebornix** [comment]
Close as lack of enough information here and we can reopen once more info provided.
