### ISSUE TITLE
Syntax highlighting error in typescript after double dot

### ISSUE THREAD

**Issue by Franziskus1988** [Microsoft/vscode#6228]
- VSCode Version: 1.1.0, 1.0.0
- OS Version: Windows 10 x64

Steps to Reproduce:
1. Set color theme to Dark+
2. Type something like: `var testvar = isTrue ? "hello" : "goodbye"`

![error](https://cloud.githubusercontent.com/assets/5774027/15136685/065ffc84-1684-11e6-9a99-66f631dca411.PNG)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#165
