### ISSUE TITLE
Add setting to show inherited Typescript interface properties

### ISSUE THREAD

**Issue by jdforsythe** [microsoft/vscode#62288]
Consider the example:

```ts
export interface BaseEntity {
  id: number;
}

export interface DatedEntity {
  createdAt: number;
  updatedAt: number;
}

export interface SomeEntity extends BaseEntity, DatedEntity {
  prop: string;
}
```

The `SomeEntity` actually looks like:

```ts
interface SomeEntity {
  id: number;
  createdAt: number;
  updatedAt: number;
  prop: string;
}
```

But there doesn't appear to be any way to visualize that. I can CMD+hover over the interfaces it's extending to see their properties, but you can only do that one at a time. 

What would be extremely helpful is if there was either a setting or a shortcut to show the inherited properties of the interface inline. They could be greyed out or otherwise visibly different than the actual properties, perhaps even like the "references" and "implementation" text enhancements where they're clearly not editable but provide extra information about the interface.

It's very difficult to visualize the actual shape of an interface when it is extending other interfaces.

**Comment by jdforsythe** [comment]
Actually it's most closely related to #11526 from my searches, but not quite the same.

**Comment by mjbvz** [comment]
Yes this is the same core request as https://github.com/Microsoft/TypeScript/issues/10752

May be something that an extension could implement

**Comment by mjbvz** [comment]
Closing this as upstream or extension candidate
