### ISSUE TITLE
Provide the option to control brace styles for TypeScript formatting

### ISSUE THREAD

**Issue by tommai78101** [Microsoft/vscode#62287]
I have been searching for similar or exact issues, but I have never seen any issues related to TypeScript formatting. I am guessing this is an upstream issue?

For some unusual issue, TypeScript formatter in Visual Studio Code is overriding the VS Code extension, Beautify, and is formatting JavaScript files, even if the TypeScript formatter is disabled.

I am assuming Visual Studio Code no longer supports formatting JavaScript via VS Code extensions, and now uses only TypeScript formatting for JavaScript.

Because of this, I looked in the Settings to configure TypeScript formatter, and found out the formatter does not support certain brace styles.

Especially, the default TypeScript formatter in Visual Studio Code does not support "Inserting New Lines After and Before Opening and Closing Braces." They are all "Insert Spaces ..."

I would like to request, as is, the default TypeScript formatter in Visual Studio Code to provide options to insert new lines:

- Before Opening Braces
- After Opening Braces
- Before Closing Braces
- After Closing Braces

Just these 4 options. If it's an upstream issue, please let me know how to report a feature request to the TypeScript formatting engine team.

Thanks.

**Comment by mjbvz** [comment]
The first part is incorrect; VS Code still supports formatting JavaScript with extensions. Did you try setting `"javascript.format.enable": false` to disable the built-in formatter?

More advanced formatting options like the ones you propose are best handled by extensions
