### ISSUE TITLE
I can't install myextension.vsix

### ISSUE THREAD

**Issue by Dob6458** [Microsoft/vscode#62297]
Hi everyone,
I want to publish my extension on VSC but I get this : 

![capture](https://user-images.githubusercontent.com/35851048/47803825-a1a7cf00-dd33-11e8-8fe4-9e607cab3994.PNG)

Can you help me please.

**Comment by kieferrm** [comment]
@Dob6458 there is a valid vsix in this directory, correct?

**Comment by Dob6458** [comment]
Sorry, I missed to install vsce
```bat
npm install vsce -g
```
