### ISSUE TITLE
VS Code outputs text when started from cmd.exe on Windows

### ISSUE THREAD

**Issue by jaholme** [Microsoft/vscode#62291]
- VSCode Version: 1.28.2
- OS Version: Windows 10 1809

Steps to Reproduce:
1. Make sure any instances of VS code are closed
2. Run "start foo.cpp" in cmd.exe (or any other file type that vs is registered as the default file handler.)

VS code now outputs "update#setState checking for updates" "[main 3:28:35 AM] update#setState idle" every hour on that console window for as long as it remains open.  

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Yes, this is an Electron limitation and it's why we put a `code.cmd` in the PATH instead.
