### ISSUE TITLE
Markdown preview copy and paste to another application doesn't transfer images.

### ISSUE THREAD

**Issue by psichel** [Microsoft/vscode#62302]
Issue Type: <b>Bug</b>

Show a preview of a markdown file that includes an image.
Select All
Copy
Paste into a new Email message
Observe that images from the markdown preview are not transferred into the Email message.

This same sequence using LightPaper (dedicated markdown editor) works as expected.
I was hoping to replace yet another editor with VS code, but it's not quite there yet.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 5, 4|
|Memory (System)|16.00GB (0.92GB free)|
|Process Argv|-psn_0_6038978|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
dotenv|mik|1.0.1
python|ms-|2018.9.2
debugger-for-chrome|msj|4.10.2
vscode-yaml|red|0.0.17
markdown-preview-enhanced|shd|0.3.11
haml|vay|1.0.1

</details>

**Comment by mjbvz** [comment]
This is an electron/chromium issue. You can verify this by opening a simple html file such as:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <img src='./cat.jpg' width="200">
</body>
</html>
```

under the `file` protocol in chrome, and trying to copy paste the image to another app like Apple Mail. Works in safari but not with Chrome

Please try [filing an issue against chromium](https://www.chromium.org/for-testers/bug-reporting-guidelines) 

Closing as upstream
