### ISSUE TITLE
Release notes will not stay closed

### ISSUE THREAD

**Issue by DonGlover** [Microsoft/vscode#62300]
Issue Type: <b>Bug</b>

Update to 1.28.2
open VS
Close releae notes
close vs
Open Vs Release notes display again.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (7.74GB free)|
|Process Argv|G:\My Drive\Addressable Assets\AddressableAssetsHostingServices.md|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-angular2-files|ale|1.6.2
vscode-instant-markdown|dba|1.4.3
vscode-pandoc|Dou|0.0.8
rest-client|hum|0.20.2
perl-debug|mor|0.4.1
python|ms-|2018.9.2
csharp|ms-|1.17.0
spellchecker|swy|1.2.13
markdown-pdf|yza|1.2.0
markdown-all-in-one|yzh|1.7.0

</details>

**Comment by joaomoreno** [comment]
Does it keep opening, as you restart VS Code?

**Comment by DonGlover** [comment]
Your question is not clear in the context of the repo steps I provided above. What is it that you are actually truing to ask?

**Comment by joaomoreno** [comment]
If you restart VS Code, do the Release Notes appear again?

If you restart again, do they appear once again?

And so on...

**Comment by DonGlover** [comment]
As stated in the repo steps above:
close vs
Open Vs Release notes display again.
What is not clear about that?  How does that not answer your questions?

**Comment by joaomoreno** [comment]
Do other things persist? For instance, if you select the Search view, then shutdown Code and open it again... is the Search view still open?

**Comment by DonGlover** [comment]
Not that I have seen.

**Comment by joaomoreno** [comment]
Can you please check?
