### ISSUE TITLE
Allow multiline search to be enabled without regex

### ISSUE THREAD

**Issue by misolori** [Microsoft/vscode#62304]
Issue Type: <b>Feature Request</b>

Testing #62102

It would be great if when I selected multiline text and triggered `Find in Files` or `cmd+shift+f` that Search would know it was multiline and be enabled without having to use regex. This would be a big time saver.

![image](https://user-images.githubusercontent.com/35271042/47806445-0a248b00-dcf7-11e8-81f3-63c84657b600.png)

VS Code version: Code - Insiders 1.29.0-insider (97ad72a02c351d6cde0fd32b41d9700a43e5964a, 2018-10-31T06:11:22.318Z)
OS version: Darwin x64 18.0.0

**Comment by traviie** [comment]
I think a great example to use as a reference for developing this feature is this extension in Visual Studio: https://marketplace.visualstudio.com/items?itemName=PeterMacej.MultilineSearchandReplace 

You can paste the multi-line text that you wish to search for and it would apply the regex for you.
Also has the ability for multi-line replace.

It's still my go to for multi-line search, however, integrating this functionality into VS Code would be even better.

**Comment by IvanLinos** [comment]
Totally agree, multiline search functionality has a lot of room to improve.
Having a Textarea which will automatically detect jump lines and spaces instead of a textbox is the way to go.

![real-multiline](https://user-images.githubusercontent.com/23552631/48768416-470ded00-ecb9-11e8-870a-3e57a0c80eaa.png)

**Comment by IvanLinos** [comment]
I take this space to make another request, related to multiline search too (but also regular find-in-files) but I think it will also benefit hard search users.
Having a recent locations dropdown for find-in-files box will be really useful, something like this will do the trick:
![findinfiles-recentlocations](https://user-images.githubusercontent.com/23552631/48769247-6c9bf600-ecbb-11e8-80ce-139914fadd2d.png)
