### ISSUE TITLE
Doxygen « file » tag interpreted as a C/C++ preprocessor

### ISSUE THREAD

**Issue by m03d** [Microsoft/vscode#62303]
Issue Type: <b>Bug</b>

1. Create a file (can be either an header or source code)
2. Puts the standard Doxygen comment at the beggining of the file; example:
```
/**
 * @file example.c
 * @author developer
 */
```
3. Check the problem list:
![image](https://user-images.githubusercontent.com/44464701/47806352-d0c13f00-dd39-11e8-92fe-1fd3b1eff96c.png)

VS Code version: Code - OSS 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-14T00:41:55.375Z)
OS version: Linux x64 4.18.16-arch1-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Phenom(tm) II X4 945 Processor (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 1|
|Memory (System)|7.79GB (3.13GB free)|
|Process Argv|/usr/lib/code/code.js --unity-launch|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|0.4.1
discord-vscode|icr|2.10.1
vscode-language-pack-fr|MS-|1.27.2
cpptools|ms-|0.20.0

</details>

**Comment by kieferrm** [comment]
@m03d pls file the issue against the C++ extension at Microsoft/vscode-cpptools. Thanks!
