### ISSUE TITLE
intellisense not working

### ISSUE THREAD

**Issue by mauricio-scardaccione** [Microsoft/vscode#62301]
Issue Type: <b>Bug</b>

After fetching data for better typescript intellisense, autocomplete stop working.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (3.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vscode-eslint|dba|1.6.1
es7-react-js-snippets|dsz|1.8.7
vscode-babel-coloring|dza|0.0.4
auto-close-tag|for|0.5.6
vscode-scss|mrm|0.6.2
vscode-jest|Ort|2.9.2
material-icon-theme|PKi|3.6.0
sass-indented|rob|1.4.9
sort-lines|Tyr|1.7.0
gitblame|wad|2.5.1
full-react-snippets|wal|1.1.2

</details>

**Comment by kieferrm** [comment]
@mauricio-scardaccione pls add concrete steps that help us reproducing the problem.
