### ISSUE TITLE
Tab is rendering in single column

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#62306]
1.28.

The text in question. Just copy paste it into a new editor window. You'll see the tab rendered in single column, when it should be `tabWidth` columns.

```
<span style="color: #000000">	</span>
```

This is likely caused by `editor.useTabStops`. But I can repro no matter it's true or false.

![tab](https://user-images.githubusercontent.com/4033249/47807082-72c03780-dcf8-11e8-87de-62338a24f868.gif)

**Comment by rebornix** [comment]
Root cause: the color decorator

**Comment by rebornix** [comment]
> You'll see the tab rendered in single column, when it should be tabWidth columns.

I found this assumption is actually incorrect and it's how a tab works. You can verify by

* Copy a hard tab
* Create an untitled file
* Type in three spaces
* Paste the hard tab
* You can see the tab is rendered in the width of `tabWidth - 3`
