### ISSUE TITLE
How to use "items" in configuration contribution?

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#62318]
My use case: I would like to have a setting that's an array of strings. `items` seems like the right choice.

Problem 1: There is no documentation on the possible fields of configurations: https://vscode-ext-docs.azurewebsites.net/api/references/contribution-points#contributes.configuration

Problem 2: The description says so:
![image](https://user-images.githubusercontent.com/4033249/47811282-a011e300-dd02-11e8-83e1-33d4eb3cdba0.png)

But this setting does not check against each element of the array:

```json
          "css.lint.validProperties": {
            "type": "array",
            "items": "string",
            "uniqueItems": true,
            "scope": "resource",
            "default": [],
            "description": "%css.lint.validProperties.desc%"
          },
```

I can still have a list of random values and be accepted.

![image](https://user-images.githubusercontent.com/4033249/47811352-c6d01980-dd02-11e8-8014-d781df114e5a.png)

**Comment by sandy081** [comment]
`items` is defined by `json` schema.

**Comment by aeschli** [comment]
See here for more information on JSON schemas: https://json-schema.org/understanding-json-schema/
arrays are documented here: https://json-schema.org/understanding-json-schema/reference/array.html

**Comment by octref** [comment]
Oh well, for some reason I tried `"item": "{ \"type\": \"string\" }"`, but not `"item": { "type": "string" }`...
