### ISSUE TITLE
Files not showing up in sidebar Debian 9

### ISSUE THREAD

**Issue by JacobStewart64** [Microsoft/vscode#62314]
Issue Type: <b>Bug</b>

Running an out of source CMake build in my workspace, sidebar only acknowledges a few changed files. An ls on the build dir shows all the files are there, but the gui doesn't know about them =(

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:20:56.183Z)
OS version: Linux x64 4.9.0-8-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4170 CPU @ 3.70GHz (4 x 3699)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|7.75GB (5.84GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.20.0
cmake-tools|vec|1.1.2

</details>

**Comment by JacobStewart64** [comment]
I run this command 'source run'

the run file contains contents:

#!/usr/bin

rm -rf build
mkdir build
cd build
cmake ..
make
cd ..

**Comment by JacobStewart64** [comment]
I believe this issue started when I installed the latest update during a restart.

**Comment by JacobStewart64** [comment]
Running the `source run` command in twice usually gets my gui updated correctly, not if I wait a long time.

**Comment by dotnetCarpenter** [comment]
@JacobStewart64 Sounds like you're running out of file watchers, especially if you get  `ENOSPC`, which is #45295. Unfortunately, there is nothing you can do if you're using multi-root (#40898), but if not, you can set `"files.useExperimentalFileWatcher": false` and ignore the folders with a lot of files that you don't need to auto watch, with `"files.watcherExclude"`.

If your hardware got a lot of memory, then you can also try to up the inode notifiction setting as described here: https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc.

@bpasero explain the situation the best in [issue 45295](https://github.com/Microsoft/vscode/issues/45295#issuecomment-371749489):

> The file watcher we have needs 1 file handle per file on Linux to support the watching (unfortunately). When the list of file handles exceeds the OS limit, VS Code will still function but some file events will not be recorded and be missing. E.g. if you delete a file in the Linux explorer, you will not see that file go away from the VS Code explorer.

Your current limit can be viewed by running: `cat /proc/sys/fs/inotify/max_user_watches`
Or:
```bash
echo "MAX file watches allowed on system"
cat /proc/sys/fs/inotify/max_user_watches

echo "Current files in project - excluding node_modules"
find . -type f -not -path '**/node_modules/**' | wc -l

echo "Current files in project - including node_modules"
find . -type f | wc -l
```
