### ISSUE TITLE
Do Not Show for overwriting extension message

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#62316]
![image](https://user-images.githubusercontent.com/4033249/47810635-04cc3e00-dd01-11e8-952d-de53c4320f70.png)

I'm in a debug session, so I'm perfectly aware that the extension I'm developing might be overwriting an existing one. I hope I can turn this message off.

**Comment by sandy081** [comment]
@alexandrudima This request looks sense to me. I am planning to add `Do not show again` action to the message and the user can opt in not to show this again.

What's your opinion?

**Comment by siegebell** [comment]
I'm debugging several extensions at once, so I use `--extensions-dir my-exts/` and `--extensionDevelopmentPath=my-exts/foo`. Because `foo` is in `my-exts/`, I get the message *"[my-exts/foo]: Overwriting extension my-exts/foo with my-exts/foo."* This is silly :/

**Comment by alefragnani** [comment]
I'm not sure which issue will remain, but there is an older issue, which is still opened (#26276).

**Comment by connorshea** [comment]
When 'Do Not Show Message' is used, should the message be dismissed just for that specific extension or for all extensions forever?

**Comment by sandy081** [comment]
It will be for all extensions

**Comment by alexandrudima** [comment]
Duplicate of #26276
