### ISSUE TITLE
Expose electron version to extension host process

### ISSUE THREAD

**Issue by salterok** [microsoft/vscode#62315]
As discussed in https://github.com/Microsoft/vscode-languageserver-node/issues/434 extension should be able to read `electron` version, vscode bundled with.

- VSCode Version: 1.29.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Write/generate simple extension 
2. In `activate` hook inspect `process.versions`
```javascript
console.log("process.versions", process.versions);
```
giving this:
![](https://user-images.githubusercontent.com/1340183/47665859-ccb2e700-dbaa-11e8-8070-012a3ffa6aec.png)

Does this issue occur when all extensions are disabled?: N/A

**Comment by mjbvz** [comment]
@jrieken Do you think we'd ever want to expose this to extensions? Shipping binaries in extensions isn't great right now but I don't think giving extensions the electron version is the right fix

**Comment by jrieken** [comment]
Yeah, not sure what the plan actually is but I am also not the biggest fan of this request. Unless there are objections I would fold this in the "support binaries for extensions" request
