### ISSUE TITLE
Provide command to jump back / to diff editor from common editor

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#62319]
1.28.

When I'm reviewing git changes, I sometimes want to quickly go to the editor view.
When I'm in a file, I sometimes want to see all changes in the file.

I hope these are distinct commands that I can bind my shortcut to.

**Comment by octref** [comment]
We have Git: Open File, now we need Git: Open Diff :p

**Comment by joaomoreno** [comment]
It's `Git: Open Changes` :dancer:
