### ISSUE TITLE
Find a file in the file tree quickly

### ISSUE THREAD

**Issue by dorianrod** [Microsoft/vscode#62317]
Hi,

First of all, thank you for this tool, I'm using it on a front-end project (jsx + html + less), and I love it.

**Feature request**
An idea of feature which could be interesting : being able to look for a file in file tree quickly (the tree you can display with CTRL + MAJ + E).

**Why ?**
When you work on a big project, you have a lot of directories and files and you lose a lot of times going through all the tree to open the file. And despite the huge number of files, we often know the names of these files.

**Example of solution**
We could click on a the top of the panel, then it would enable a text area. This search area would filter files and directories by name. Then it's easy to open the file.

Dorian

**Comment by kieferrm** [comment]
@dorianrod have you tried <kbd>Ctrl</kbd>+<kbd>P</kbd>?  Or are you looking for something like #10026?

**Comment by dorianrod** [comment]
Perfect! This is exactly what I was looking for.
Thank you
