### ISSUE TITLE
Remove *.colorDecorators.enabled language specific settings

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#62325]
The language specific color decorator settings (`css.colorDecorators.enable`, `scss.colorDecorators.enable`, `less.colorDecorators.enable`, and `json.colorDecorators.enable`) have been marked as deprecated for at least 7 months. `"editor.colorDecorators"` is now the proper setting

We should remove these deprecated settings

**Comment by octref** [comment]
Note to self: Use "deprecationMessage" to mark deprecated, then remove in Dec.

**Comment by octref** [comment]
Alright, already deprecated. I'll remove it next month.
