### ISSUE TITLE
Lag when scrolling with precision touchpad still si happening

### ISSUE THREAD

**Issue by rulyotano** [Microsoft/vscode#62327]
Just for notifying the following issues are still happening on Windows 10 Pro latest version, but all Issues already reported are locked:

https://github.com/Microsoft/vscode/issues/35191
https://github.com/Microsoft/vscode/issues/40007
https://github.com/Microsoft/vscode/issues/35191

* At the first time VSCode load, it is not happening. It occurs some time later, when load more stuffs, files, consoles, etc.
* When MIN/MAX the window it is fixed.

**Comment by kieferrm** [comment]
This was originally tracked in #13612. What is your precise Windows version?

**Comment by rulyotano** [comment]
I got more info:
Step to reproduce it:
1. Open VsCode, scroll is working fine and smooth.
2. Go to desktop (Gesture three fingers down) 
3. Go to VsCode again, (Gesture three fingers up)
4. Now scroll isn't smooth.
5. To fix it is needed going to small window and then going back to full window.

My particular version of window:
* Window 10 Education, version 1803, Os Version: 17134.345

**Comment by kieferrm** [comment]
@rulyotano What's your VS Code version? Insiders?

**Comment by Leffers90** [comment]
I am also having this issue when 2 finger scrolling on the precision touch pad. I am new to coding and it is unbearable. I don't get this issue in any other program. I have the latest VScode version. I am in a bootcamp course and have asked my instructors who are also unsure. 

I also use a mouse now as I receive 0 lag using the mouse wheel scroll.

**Comment by rulyotano** [comment]
@kieferrm :
* Version: 1.28.2 (system setup)
* Commit: 7f3ce96ff.....
* Date: 2018-10-17T00:23:51.859Z
* Electron: 2.0.9
* Chrome: 61.0.3163.100
* Nodejs: 8.9.3
* V8: 6.1.534.41
* Architecture: x64

Also my pc is a Xiaomi Mi Notebook Pro.

@chrmarti This issue is just for helping you guys to identifying that all the previous issues are not solved at all. Even I give the step to reproduce it. But it seams that it si more important for you to close it as duplicated than to solve it. I know it is dup, it is in the firts post, it is just is still happening.

**Comment by rulyotano** [comment]
@HazemAM It the issue is totally solved after the Windows KB4462933 update!!!

I didn't know what happened. Before I post this issue I checked twice if windows had some updates, but said there were no updates. Now I check for this in particular and wasn't there, so I force the update. So I need to apologize to you guys, and thanks for your time.

**Comment by chrmarti** [comment]
Also see https://github.com/Microsoft/vscode/issues/13612#issuecomment-436208013.
