### ISSUE TITLE
Support for GitHub-Flavoured MarkDown TaskLists

### ISSUE THREAD

**Issue by CarlRevell** [Microsoft/vscode#62326]
Please add support for [GitHub-flavoured MarkDown TaskLists](https://blog.github.com/2014-04-28-task-lists-in-all-markdown-documents/).

Amongst other things, I use VSCode as a simple task todo list while working on a project.

- [ ] Do something
- [ ] Do something else
- [x] Done something.

And whilst I can type these into my MarkDown `ToDo.md` document it would be great if it styled them like a proper todo list in the MarkDown preview.

**Comment by mjbvz** [comment]
See https://marketplace.visualstudio.com/items?itemName=bierner.markdown-checkbox

**Comment by CarlRevell** [comment]
Thank you. This extension seems to do exactly what I wanted. I'm sure I've seen and/or tried this extension before and didn't keep it for some reason but I have no idea why or if I am just imagining that I tried it previously 🤔😂
