### ISSUE TITLE
Integrated terminal resets scroll position to top when emacs is closed

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#62329]
Issue Type: <b>Bug</b>

**steps**
1. In the intergrated terminal.
1. Run a command that generates more than one screen of content: `ls -alF /dev/`
1. Scroll to bottom
1. Now run emacs and then close emacs using ctrl+c ctrl+x

**Bug**
Terminal scroll position reset to top of buffer

VS Code version: Code - Insiders 1.29.0-insider (4b2fac2b6da220f62ff58b2766e4ecc1f561be94, 2018-10-30T16:46:24.907Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|vscode-reference-view/|
|Screen Reader|no|
|VM|22%|

</details>

**Comment by Tyriar** [comment]
Can't repro, will keep an eye out for it though.
