### ISSUE TITLE
MarkedString: Cannot use language `md` or `markdown`

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#62332]
1.28.

If for the hover, you return either of these:

```ts
{
  language: 'markdown' // or 'md',
  value: '[VS Code](https://github.com/microsoft/vscode)'
}
```

It'll not be rendered as markdown. However, if the hover is just a markdown string like `'[VS Code](https://github.com/microsoft/vscode)'`, then it'll be rendered as a link.

**Comment by mjbvz** [comment]
The expectation in this case is that the text is rendered as markdown source:

```md
[VS Code](https://github.com/microsoft/vscode)
``` 

Is that what you see?

**Comment by octref** [comment]
If `{ language: 'javascript', value: 'console.log' }` will be rendered as JS, I would expect ` { language: 'markdown', value: '[foo](link)' }` to render as Markdown, not code literals enclosed in triple backquotes.

**Comment by mjbvz** [comment]
This is how javascript is handled too. `{ language: 'javascript', value: 'console.log' }` is equivalent to 

~~~md
```javascript
console.log
```
~~~

`language` is effectively just a shorthand to treat the content as a markdown code block

**Comment by octref** [comment]
Will remove usage of `MarkedString` then, since it's deprecated. Thanks for answering: https://github.com/Microsoft/vscode-css-languageservice/issues/132
