### ISSUE TITLE
No snippets shown when triggering completions at whitespace on line that already has text

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#62335]
Issue Type: <b>Bug</b>

**steps**
1. For a markdown file with the contents

```md
 
a 
```

1. `ctrl` + `space` trigger intellisense on line 1. See snippets
1. Now move cursor to the whitespace after the `a` on line two: `a |`
1.  `ctrl` + `space` trigger intellisense 

**bug**
No snippets are shown. 

Snippets are shown in this case if you trigger on a word, such as `a b|`

VS Code version: Code - Insiders 1.29.0-insider (97ad72a02c351d6cde0fd32b41d9700a43e5964a, 2018-10-31T06:11:22.318Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|22%|

</details>

**Comment by jrieken** [comment]
Weird, but not a regression...
