### ISSUE TITLE
Suggestions for node_modules automatic imports not shown

### ISSUE THREAD

**Issue by patillades** [Microsoft/vscode#62339]
- VSCode Version: 1.28.2
- OS Version: Ubuntu 18.04.1 64-bit

Steps to Reproduce:

1. Write the first characters of a lodash module, like `templ` for `template`
2. The suggestions box says "No suggestions" instead of the expected `template` module from lodash

![peek 2018-10-31 23-54](https://user-images.githubusercontent.com/8511199/47823988-13e7d600-dd6b-11e8-97aa-72c538728929.gif)

It happens with extensions disabled, with code or code-insiders, and with Typescript 3.1.3 or 3.1.5. As can be seen on the GIF, imports from an own ts module work as expected.

I'm doing it on a very simple project that just contains:

`package.json`
```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "dist/index.js",
  "directories": {
    "test": "test"
  },
  "scripts": {
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@types/lodash": "^4.14.117",
    "typescript": "^3.1.5"
  },
  "dependencies": {
    "lodash": "^4.17.11"
  }
}
```

`tsconfig.json`
```
{
    "compilerOptions": {
        "target": "es6",
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true,
        "outDir": "dist",
        "baseUrl": "."
    },
    "include": [
        "src/**/*.ts"
    ]
}
```

**Comment by kyranet** [comment]
In my case, it looks like it's a problem with module augmentation. A package `a` has an exported member `Foo` (being a class), and when I write `Foo` it shows if I want to import `Foo` from `a`. However, if I do an augmentation, using the following pattern:

```typescript
declare module 'a' {
	export interface Foo {
		prop: string;
	}
}
```

The class Foo will indeed have Foo.prototype.prop, as far as Intellisense and TypeScript tell me, but if I type `Foo` again, it doesn't show unless I comment out the augmentation.

In a real world case, this is happening: ![image](https://vgy.me/Ryvbar.gif)

**Comment by kyranet** [comment]
Similarly, if I have a dep `B` augmenting `A` (which is the case [here](https://github.com/dirigeants/klasa/blob/8496d45db52a01727e5d3fd8b0b81450df77efbf/typings/index.d.ts#L1000-L1257) too), the same problem is caused (I don't get suggestions from `A`, but I get from `B`). Not sure if this is a TypeScript issue, or a Visual Studio Code one, or perhaps, my own code.

**Comment by mjbvz** [comment]
This sounds like it could be https://github.com/Microsoft/TypeScript/issues/30033

Do you reference the normal `lodash` module anywhere in your project? Or only `lodash/add`?
