### ISSUE TITLE
Cannot split complete terminal created by task 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#62331]
Issue Type: <b>Bug</b>

**Steps**
1. With a `tasks.json`:

```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "ExitWithCode",
            "type": "shell",
            "command": "exit 4",
            "presentation": {
                "echo": true,
                "reveal": "silent",
                "focus": false,
                "panel": "shared",
                "showReuseMessage": true,
                "clear": false
            }
        }
    ]
}
```

1. Run the task.
1. This should open  the intergrated terminal with the message `Terminal will be reused by tasks, press any key to close it.` at the bottom
1. Now click on the split terminal button

**Bug**
Button has no effect. No errors in developer console.

You can split the terminal for tasks that are still running. 

VS Code version: Code - Insiders 1.29.0-insider (97ad72a02c351d6cde0fd32b41d9700a43e5964a, 2018-10-31T06:11:22.318Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.30GB free)|
|Process Argv|-psn_0_50495525|
|Screen Reader|no|
|VM|22%|

</details>

**Comment by johanforssell** [comment]
I'm not getting any terminal split since I update to 1.29.1 (Linux).

![no-split-for-me](https://user-images.githubusercontent.com/684381/49221154-9b5f4e00-f3d8-11e8-9679-2bc79481bd0d.gif)

**Comment by Tyriar** [comment]
@johanforssell that's as designed, not sure why you're not getting the message though:

![image](https://user-images.githubusercontent.com/2193314/49243886-4cf38480-f3c3-11e8-8024-d962c31c24e5.png)

**Comment by Tyriar** [comment]
This works now.
