### ISSUE TITLE
Empty problems view

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#62341]
Issue Type: <b>Bug</b>

**Steps**
1. In a workspace with no problems.
1. Open the problems view
1. Enter `%` as the problems view filter text
1. Now introduce an error into a file
1. See the prolem count update
1. Now delete the filter text and press enter again

**Bug**
No problems shown

![screen shot 2018-10-31 at 5 09 38 pm](https://user-images.githubusercontent.com/12821956/47825542-c7cb7000-dd2f-11e8-98b1-f9d071f70795.png)

VS Code version: Code - Insiders 1.29.0-insider (97ad72a02c351d6cde0fd32b41d9700a43e5964a, 2018-10-31T06:11:22.318Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|22%|

</details>

**Comment by sandy081** [comment]
@mjbvz 

- I cannot reproduce it, is it happening for some specific error?
- Do you see any errors in the console?

**Comment by sandy081** [comment]
I can reproduce it now. This looks to me a dup of https://github.com/Microsoft/vscode/issues/62216

**Comment by sandy081** [comment]
After investigating figured out that this is not a dup.
