### ISSUE TITLE
Enable git.promptToSaveFilesBeforeCommit by default

### ISSUE THREAD

**Issue by letmaik** [Microsoft/vscode#62344]
I regularly stumble on this and just discovered that there is an option to enable this warning prompt. Is there any reason not enabling this by default? If it's on by default, then the prompt could have an additional button to make it easy to disable it in case people don't like it.

I found two other cases where people were unaware this option existed:
https://github.com/Microsoft/vscode/issues/60538
https://github.com/Microsoft/vscode/issues/58896

**Comment by joaomoreno** [comment]
That's actually a great question.
