### ISSUE TITLE
vscode don't delete the old file when update extension 

### ISSUE THREAD

**Issue by John0King** [Microsoft/vscode#62347]
- VSCode Version: 1.28.2  System install
- OS Version: win10

Steps to Reproduce:

1. instill   `liveshare`
2. when `liveshare` extension updated, checkout the `%profile%/.vscode/extensions` folder, there multiple  liveshare extension there.

**Comment by sandy081** [comment]
@John0King Restart VS Code and they will be deleted. We clean up older or uninstalled version when VS Code is restarted.

**Comment by John0King** [comment]
@sandy081  as my test, It will do as u say when I uninstall a extension.
but not work as **update** , ~~there's no `.obsolete` file.~~
There no extension update now, I will test again when a extension has an update. 
I fill another issue if it doesn't work as expect.
