### ISSUE TITLE
first scroll doesn't trigger

### ISSUE THREAD

**Issue by graph** [microsoft/vscode#62342]
Version: 1.29.0-insider
Commit: 5d68db08cda5accef740c69541178911b865d069
Date: 2018-10-26T05:13:31.757Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Version: 1.29.0-exploration
Commit: 72250eb188df74b879c6ecef96dbb05a6090499d
Date: 2018-10-25T05:43:44.088Z
Electron: 3.0.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
Architecture: x64

OS: Ubuntu

also the current stable it's reproducible.

Steps to Reproduce:

1. open a file big enough to scroll
2. move mouse out of the vs code
3. move mouse back into vs code
4. move the mouse wheel ever so slighting to do 1 tick

reproducibility: 100% lol

expected result: scroll a bit

actual result: The event gets sent backwards in time which results in [this bug](https://github.com/Microsoft/vscode/issues/28795) ;)

Does this issue occur when all extensions are disabled?: I haven't tried

Terminal also behaves this way.

**Comment by kieferrm** [comment]
@alexandrudima can you pls have a look since @bpasero is out?
