### ISSUE TITLE
Find in terminal clears result highlight if there is only a single result and you press enter again

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#62348]
Issue Type: <b>Bug</b>

**steps**
1. In VS Code source
1. Open a new integrated terminal
1. Run `ls`
1. Search for `OSS` in the terminal
1. Press enter and see one result for `OSSREADME.json`correctly highlighted
1. Now Press enter multiple times

**Bug**
The highlighting of the result is lost

VS Code version: Code - Insiders 1.29.0-insider (97ad72a02c351d6cde0fd32b41d9700a43e5964a, 2018-10-31T06:11:22.318Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|22%|

</details>

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/xtermjs/xterm.js/issues/2456
