### ISSUE TITLE
Support native text control context menu

### ISSUE THREAD

**Issue by manoelcampos** [Microsoft/vscode#6235]
- VSCode Version: 1.1.0
- OS Version: Mac OSX 10.11.4

Steps to Reproduce:
1. Open Visual Studio Code
2. Open any file
3. Right click in any word to show the popup menu
4. The native Mac OSX popup menu is replaced by a particular Visual Studio Code menu

However, the operating system native popup usually provides useful things such as spell check. Visual Studio Code popup menu options would be added to the native Mac OSX popup.
The images below shows the differences between a native Mac OSX application and Visual Studio Code.
- **Mac OSX popup menu in native TextEdit app:**
  ![macos-popup-menu-native-textedit-app](https://cloud.githubusercontent.com/assets/261605/15140797/b153fe5a-1694-11e6-8cb1-e4435d9a7acc.gif)
- **Replaced popup menu in Visual Studio Code:**
  ![macos-popup-menu-visualstudiocode](https://cloud.githubusercontent.com/assets/261605/15140798/b19e513a-1694-11e6-9e34-ef4b20ecff20.gif)

**Comment by isidorn** [comment]
FYI @bpasero

**Comment by alexandrudima** [comment]
@manoelcampos Is this a bad practice on macs? Do all other text areas in all other software on the mac present this exact context menu you show?

**Comment by manoelcampos** [comment]
Sorry for the late reply @alexandrudima . I was on vacation :)
I think so. Apple applications and even third-party Mac apps such as Easy Markdown and Cyberduck have that same context menu, as well as other multi-platform apps such as Skype, FileZilla and GitHub Desktop. However, several other apps have a custom context menu.

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

P.S. If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
