### ISSUE TITLE
Run active file does nothing on windows if file path has space in it

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#62350]
Issue Type: <b>Bug</b>

While testing https://github.com/Microsoft/vscode/issues/60768

**steps**
1. On windows
1. Create an html file called `sp ace.html`
1. Open the file
1. From the terminal menu, select `Run Active file`

**bug**
This command executes `"c:\Users\matb\folder\sp ace.html"` in the terminal. For powershell at least, this does nothing.

If the file does not have a space, then we run  `c:\Users\matb\projects\san\nospace.html` which opens a web browser 

VS Code version: Code - Insiders 1.29.0-insider (97ad72a02c351d6cde0fd32b41d9700a43e5964a, 2018-10-31T06:19:46.141Z)
OS version: Windows_NT x64 10.0.18262

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.98GB (1.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|

</details>

**Comment by Tyriar** [comment]
@tylerleonhardt do you have a suggestion of what should happen for powershell?

**Comment by TylerLeonhardt** [comment]
You'll want the [call operator (`&`)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_operators?view=powershell-6#call-operator-) which should do what you want.

```powershell
& "c:\Users\matb\folder\sp ace.html"
```

**Comment by TylerLeonhardt** [comment]
This issue doesn't just apply to Windows but any OS that uses PowerShell.

**Comment by Tyriar** [comment]
@TylerLeonhardt thanks for the info 👍
