### ISSUE TITLE
backspace键

### ISSUE THREAD

**Issue by lzz1996** [Microsoft/vscode#62360]
Issue Type: <b>Bug</b>

backspace键在VisualStudio Code编辑器里有时不能退格，而在去其他编辑器上正常使用

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (4.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (61)</summary>

Extension|Author (truncated)|Version
---|---|---
code-snippets|119|0.1.11
html-snippets|abu|0.2.1
bs4code|adn|1.5.0
aessoft-class-autocomplete|AES|0.1.0
vscode-javascript-snippet-pack|aka|0.1.5
htmltagwrap|bra|0.0.7
simple-react-snippets|bur|1.2.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.60
vscode-vue-ts-snippet|crp|0.0.3
vscode-eslint|dba|1.6.1
jquerysnippets|don|0.0.1
Vue2|duc|0.1.3
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.40
bootstrap-4-cdn-snippet|eve|1.1.3
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
React-JS-Snippet|Gaj|3.0.54
vscode-atom-javascript-snippet|glu|0.2.1
vue-snippets|hol|0.1.9
beautify|Hoo|1.4.7
angular-snippets|Hri|1.0.2
jquery-snippets|Hri|1.0.0
vetur-wepy|hu2|0.13.6
vue-autoimport|ish|0.0.2
vuejs-peek|ish|0.0.3
Angular2|joh|6.3.0
react-native-snippet|jun|0.5.0
es6-angular-snips|kas|0.0.3
node-module-intellisense|lei|1.5.0
quickstart|lol|0.1.0
amazeui-vscode-snippets|min|0.0.2
HTMLHint|mka|0.5.0
vscode-filesize|mkx|2.1.1
vscode-language-pack-zh-hans|MS-|1.28.2
es6-typescript-import-sorter|nik|1.1.1
vetur|oct|0.13.0
open-html-in-browser|pea|0.0.3
tslint-vue|pro|1.5.6
view-in-browser|qin|0.0.5
LiveServer|rit|5.1.1
vscode-icons|rob|7.28.0
react-native-snippet|san|0.6.0
vue-vscode-snippets|sdr|1.3.0
indenticator|Sir|0.6.0
react-redux-es6-snippets|sle|0.5.3
javascript-typescript|sou|0.0.7
open-in-browser|tec|2.0.0
bootstrap4-vscode|the|4.3.0
es6-string-html|Tob|1.8.3
vue-ls-snippets|van|0.0.5
vscode-angular-support|vis|0.1.4
quokka-vscode|Wal|1.0.156
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.7.1
ReactSnippets|xab|2.2.1
bootstrap-v4-snippets|Zac|0.1.5
html-css-class-completion|Zig|1.17.1
tslint-snippets|zuo|1.1.0

(1 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
@lzz1996 can you follow our wiki of keybindings to troubleshoot and provide more information ? https://github.com/Microsoft/vscode/wiki/Keybinding-Issues
