### ISSUE TITLE
usually stuck when using touchpad

### ISSUE THREAD

**Issue by oi-songer** [Microsoft/vscode#62362]
Issue Type: <b>Performance Issue</b>

While I'm using touchpad to scroll, VS code usually stuck for a little while. It doesn't a big problem, but it does affect the user experience. This issue won't happen if I am using my mouse or touchscreen.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (1.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	    88	 10164	code main
    0	    72	  1320	   shared-process
    0	   235	 10796	   gpu-process
    0	   215	 18612	   window (FileOperation.java - Check with package - Visual Studio Code)
    0	     4	  9604	     winpty-process
    0	    34	  1368	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     6	 12596	       console-window-host (Windows internal process)
    0	    11	 16392	     watcherService 
    0	     4	  9992	       console-window-host (Windows internal process)
    0	     9	 19508	     electron-crash-reporter
    0	    96	 20536	     extensionHost
    0	   465	 13032	       d:\jdk\bin\java --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication -jar C:\Users\alber\.vscode\extensions\redhat.java-0.33.0\server\plugins\org.eclipse.equinox.launcher_1.5.200.v20180922-1751.jar -configuration C:\Users\alber\.vscode\extensions\redhat.java-0.33.0\server\config_win -data c:\Users\alber\AppData\Roaming\Code\User\workspaceStorage\946290bbfafc180a2729dde762391a04\redhat.java\jdt_ws
    0	     4	  1936	         console-window-host (Windows internal process)
    0	    22	 31008	       "D:\Microsoft VS Code\Code.exe" "d:\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=20536
    2	    71	 25520	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (FileOperation.java - Check with package - Visual Studio Code)
|    Folder (Check with package): 13 files
|      File types: java(11) txt(1) json(1)
|      Conf files: settings.json(1);
```

</details>
<details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-latex-renderer|agu|0.0.2
vscode-ghc-mod|hoo|1.2.0
language-haskell|jus|2.5.0
cpptools|ms-|0.20.1
phoityne-vscode|pho|0.0.20
quantum-devkit-vscode|qua|0.3.18102508
java|red|0.33.0
vscode-java-debug|vsc|0.14.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.10.0
vscode-maven|vsc|0.11.1
markdown-all-in-one|yzh|1.7.0

(4 theme extensions excluded)

</details>

**Comment by kieferrm** [comment]
This is fixed in the Windows 10 October 2018 update (also know as RS5).
