### ISSUE TITLE
Shortcut key on diff tool

### ISSUE THREAD

**Issue by fujitatakesh** [Microsoft/vscode#62361]
It will be better key shortcut on diff tool.
1: Jump to differences.
2: Apply changes from left pane(original source).
Thank you.

**Comment by kieferrm** [comment]
1. You navigate between differences with <kbd>F7</kbd> and <kbd>Shift</kbd>+<kbd>F7</kbd>. The corresponding commands are `workbench.action.compareEditor.nextChange` and `workbench.action.compareEditor.previousChange` if you want to change the keybindings.

2. In the keyboard shortcut editor search for "merge". You can bind your own keyboard shortcuts to any of the **Accept** commands.

**Comment by fujitatakesh** [comment]
I confirmed that a keyword "nextChange" is assigned already to alt+F5.
It could be useful for me.
Thank you for replying.
