### ISSUE TITLE
I can't open folder dialog

### ISSUE THREAD

**Issue by DarkTemplar008** [microsoft/vscode#62363]
Issue Type: <b>Bug</b>

1. open app on windows
2. click "Open Folder" button 
3. do nothing

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|23.92GB (20.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kieferrm** [comment]
@DarkTemplar008 can you please attach a screen recording? Are you potentially running in full-screen mode? I wonder if the dialog is behind or off-screen.

**Comment by DarkTemplar008** [comment]
good job, with new editon, it doesn't happen any more
my best editor, not vim
