### ISSUE TITLE
suggestSelection 'recentlyUsedByPrefix' share recentlyUsed in different project

### ISSUE THREAD

**Issue by inu1255** [Microsoft/vscode#62365]
### this is my problem:
the project A
![image](https://user-images.githubusercontent.com/5772409/47841535-ddef3400-ddf4-11e8-8f19-53c44b6d8f24.png)
the project B
![image](https://user-images.githubusercontent.com/5772409/47841498-c3b55600-ddf4-11e8-8067-c69a18023738.png)

### I want :
once `con` -> `console` in project A 
it become `con` -> `console` in project B

**Comment by skprabhanjan** [comment]
@jrieken , can i work on this?
If so some starter pointers would be helpful :)
Thanks

**Comment by jrieken** [comment]
* Check the two usages of [`StorageScope.WORKSPACE`](https://github.com/Microsoft/vscode/blob/33c89529befce0fc18cb1c783f3d991b8b03c3d0/src/vs/editor/contrib/suggest/suggestMemory.ts#L222). They define where data is being read from: global or workspace storage. 
* for the setting "Monkey see, monkey do" is my advice, take this as an example: https://github.com/Microsoft/vscode/blob/33c89529befce0fc18cb1c783f3d991b8b03c3d0/src/vs/editor/common/config/commonEditorConfig.ts#L637

**Comment by skprabhanjan** [comment]
@jrieken , Any updates or reviews on the PR ?
Thanks :)

**Comment by jrieken** [comment]
Sorry, didn't have time yet...

**Comment by jrieken** [comment]
:clap: @skprabhanjan - I have tweaked the name of the setting to `shareSuggestSelections`

**Comment by skprabhanjan** [comment]
> 👏 @skprabhanjan - I have tweaked the name of the setting to `shareSuggestSelections`

@jrieken , Awesome, the new name makes more sense:)
Thanks for the review and merge:)

**Comment by roblourens** [comment]
I can't get this to work.

- Set `editor.suggestSelection` to `recentlyUsedByPrefix`
- Enable `shareSuggestSelections`
- Open folder A, type `con`, select `console`
- Now `con` suggests `console` ✔️ 
- Open folder B, type `con`
- `confirm` is still selected

**Comment by jrieken** [comment]
Yeah, good catch. It seems that @bpasero removed the delayed saving of suggest memories with https://github.com/Microsoft/vscode/commit/6187c6672710fcc03b4450ebc136155253cea0f. It now requires you to close/reload the window (or whenever `onWillSaveState` will happen). Not sure why that change was done. @bpasero Is saving every 3 seconds really to much pressure on sql-lite?

**Comment by bpasero** [comment]
@jrieken see https://github.com/Microsoft/vscode/pull/64496 to restore the previous behavior. I think it would be more efficient if periodic saving would not be needed but rather the storage service calls `onWillSaveState()` also when a new window gets opened (at least for `StorageScope.GLOBAL`). Maybe something for debt week.

**Comment by bpasero** [comment]
Yeah, to be safe against a crash, periodic saving is currently the only option.

**Comment by jrieken** [comment]
There are more things wrong with this feature. I will re-open the issue, remove the setting from the schema, and schedule for next milestone...

@skprabhanjan feel free to give this a second stab. things to look out for:

1. when two windows are open at the same time a synchronisation is needed (`onDidChangeStorage`)
1. there is a flaw in suggest memories is an instance per editor and different editor might override each others data. I have a fix for that, maybe the event from 1. will fix this too
1. when renaming the setting I forgot to rename parts of it

**Comment by jrieken** [comment]
I have pushed my changes here https://github.com/Microsoft/vscode/tree/joh/fixmem. I will finish this in December.

**Comment by jrieken** [comment]
Yeah, you revert 
https://github.com/Microsoft/vscode/commit/0740633118c88555e139624320ffc4825dade527 to get the setting back.

I have pushed my changes and most things should work, except for what's commented out. The challenge is multiple windows being open at the same time. It needs some "leader election". I would propose the following strategy: 

* receiving the event *without* focus => then reset (drop the current data and call update)
* receiving the event *with* focus => then ignore the event
* shorten the debounce delay after which stuff is written to memory

You can use `IWindowService#hasFocus` to know if you have focus, make sure and test well that two or windows don't constantly react and causes the storage change event

**Comment by skprabhanjan** [comment]
@jrieken , Okay I am looking at the "leader election" changes now. `this._register(this._storageService.onDidChangeStorage` will be the event and inside that `if (e.scope === StorageScope.GLOBAL && e.key.indexOf(this._storagePrefix) === 0)` will be the check and inside this if is where the changes you suggested needs to happen rite ?

I figured out how to check for focus , One clarificaiton I will need is 
> drop the current data and call update

Drop the data would be clearing SuggestMemoryService member variables or _storageService ?

**Comment by jrieken** [comment]
> I figured out how to check for focus ,Clarifications that I will be need

Sorry, I now went it pushed the remaining changes. This item is finished now.
