### ISSUE TITLE
Use native Mac OSX spell check

### ISSUE THREAD

**Issue by manoelcampos** [microsoft/vscode#6236]
- VSCode Version: 1.1.0
- OS Version: Mac OSX 10.11.4

Steps to Reproduce:
1. Open Visual Studio Code
2. Open any file that has some spell errors inside its content
3. The app will not highlight spell errors and grammar suggestions
4. It should be highlighted spell errors in red and grammar suggestions in green, that is a native feature of Mac OSX apps

The images below shows the differences between a native Mac OSX application and Visual Studio Code.
- **Mac OSX spell check in native TextEdit app:**
  ![macos-spellcheck-native-textedit-app](https://cloud.githubusercontent.com/assets/261605/15141241/03ff9e00-1697-11e6-800a-329983b949f0.gif)
- **Visual Studio Code does't show spell errors and grammar suggestions:**
  ![macos-spellcheck-doesn-work-visualstudiocode](https://cloud.githubusercontent.com/assets/261605/15141270/2a020bba-1697-11e6-92b9-1fb8b5714f47.gif)

**Comment by Tyriar** [comment]
Related: https://github.com/Microsoft/vscode-spell-check/issues/29#issuecomment-218685569

**Comment by martinkoppel** [comment]
I've moved some the documentation to git using MarkDown language. Having spellcheck working there would be super awesome.

**Comment by sorgel** [comment]
+1.  Atom supports native spell check

**Comment by terryupton** [comment]
Is this on the VS Code roadmap at all? Having come from Sublime Text 3 - I do miss the native spellchecker and the plugins I have tried don't really live up to Sublime Text 3 spell checking facility, as they get confused with comments/strings/copy vs actual code etc.

**Comment by phyllisstein** [comment]
The [SpellRight extension](https://marketplace.visualstudio.com/items?itemName=ban.spellright) integrates with the system dictionary. It's the best workaround I've seen, until the maintainers update the built-in implementation.
