### ISSUE TITLE
Console opens unasked-for

### ISSUE THREAD

**Issue by zivcaspi** [Microsoft/vscode#62368]
Issue Type: <b>Bug</b>

Should I start VSCode to edit a file and there being some totally-unrelated extension issues (such as an extension wanting to deploy some update perhaps?), the console opens up completely unasked-for. Not only am I presented by multiple toasters announcing stuff I don't care about (no dotnet cli on the path -- yes, but I'm editing a text file, so why would I care?), the console itself takes half the screen and constantly interrupts my work.

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:15:15.139Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.91GB (15.37GB free)|
|Process Argv|index.md|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
vscode-markdownlint|Dav|0.21.0
vscode-rust|kal|0.4.2
codeshell|Kip|0.2.2
vscode-antlr4|mik|2.0.4
python|ms-|2018.9.2
cpptools|ms-|0.20.1
csharp|ms-|1.17.0
PowerShell|ms-|1.9.0
java|red|0.33.0
rust|rus|0.4.10
vscode-java-debug|vsc|0.15.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.10.0
vscode-maven|vsc|0.11.1

</details>

**Comment by zivcaspi** [comment]
Issue Type: <b>Bug</b>

Should I start VSCode to edit a file and there being some totally-unrelated extension issues (such as an extension wanting to deploy some update perhaps?), the console opens up completely unasked-for. Not only am I presented by multiple toasters announcing stuff I don't care about (no dotnet cli on the path -- yes, but I'm editing a text file, so why would I care?), the console itself takes half the screen and constantly interrupts my work.

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:15:15.139Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.91GB (15.37GB free)|
|Process Argv|index.md|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
vscode-markdownlint|Dav|0.21.0
vscode-rust|kal|0.4.2
codeshell|Kip|0.2.2
vscode-antlr4|mik|2.0.4
python|ms-|2018.9.2
cpptools|ms-|0.20.1
csharp|ms-|1.17.0
PowerShell|ms-|1.9.0
java|red|0.33.0
rust|rus|0.4.10
vscode-java-debug|vsc|0.15.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.10.0
vscode-maven|vsc|0.11.1


</details>

**Comment by isidorn** [comment]
About notifications file that against extensions please.
As for the console I do not know which console are you talking about? Can you post a screen shot? Are you actually debuging?

**Comment by zivcaspi** [comment]
This one. I’m not debugging anything – just trying to write some docs 😊

[cid:image001.png@01D471DA.D45C6060]

**Comment by isidorn** [comment]
@zivcaspi you did not attach the image, please try again

**Comment by zivcaspi** [comment]
<img width="184" alt="a" src="https://user-images.githubusercontent.com/3773221/47849859-c6578180-dddb-11e8-85b0-64e472d837f8.png">

**Comment by isidorn** [comment]
Some extension seesm to be openeing the problems panel, but forwarding to @sandy081 as he might know more

**Comment by sandy081** [comment]
@zivcaspi Can you please try disabling all extensions and see if the problems panel is getting opened? 

If not, please try to disable each extension and find out which extension is doing this and file an issue against it.
