### ISSUE TITLE
[json] IntelliSense doesn't work for scoped packages in package.json

### ISSUE THREAD

**Issue by Globegitter** [Microsoft/vscode#62377]
- VSCode Version: 1.28.2
- OS Version: elementary OS 5.0 Juno (Ubuntu 18.04)

Steps to Reproduce:

1. Add a package.json file
2.  within `{ "dependencies: { }}` try to add any npm dependency starting with `@`, such as `@babel/core`.

I expected to see autocomplete in the same way as for non-scoped packages like when typing `babel-` and it suggests me the unscoped babel packages.

Does this issue occur when all extensions are disabled?: Yes

I have seen there is https://github.com/Microsoft/vscode/issues/24321 which mentioned it brought in support for `@angular` and `@types` and indeed when I type `@` it immediately suggests these two scopes but I have not been able to get it to suggest any package within the scope, even when i tried to type almost the whole name `@types/moch`. So one the one hand it would be great if that could be fixed and it would also be great if `@babel`, `@nuxtjs`, `@vue` and `@bazel` scopes could be added.

Also not sure if the issue belongs here or in https://github.com/Microsoft/vscode-json-languageservice so please let me know if I should reopen it there (or anywhere else if I missed it)

**Comment by aeschli** [comment]
I still don't know of a search index for all private scopes. We just provide a hard coded list. I added the proposed scoped.

I fixed the query for the scoped package names
