### ISSUE TITLE
ctrl+q can't be configured to not close vscode

### ISSUE THREAD

**Issue by davidnorthetal** [microsoft/vscode#62372]
- VSCode Version: 1.27.2
- OS Version: ArchLinux x64

Steps to Reproduce:

1. unbind/change all Keybindings that involve <Ctrl+q>
2. open Tab: Preferences: Open User Settings
3. press <Ctrl+q>, vscode will exit

Does this issue occur when all extensions are disabled?: **yes**

**Comment by kieferrm** [comment]
<kbd>Ctrl</kbd>+<kbd>Q</kbd> on ArchLinux works system wide and is consumed by the window manager. You need to unbind it there. See https://bbs.archlinux.org/viewtopic.php?id=78712.

**Comment by davidnorthetal** [comment]
@kieferrm I have checked, but I'm using i3-wm and I've made sure that i3 **isn't** configured to consume `Ctrl`+`q`

Other applications like chromium also don't quit on Ctrl+q - applications like Thunderbird or Thunar quit with Ctrl-q but they also show this in the menu bar under `File->Quit` - so it seems very much that this **is** application specific and that vscode does exhibit wrong behavior here.

**Comment by alexandrudima** [comment]
@davidnorthetal I haven't gotten around to install arch linux to try to reproduce. Is this still a problem for you?
