### ISSUE TITLE
Debug Restart option requires a manual focus shift

### ISSUE THREAD

**Issue by gjsjohnmurray** [Microsoft/vscode#62374]
Issue Type: <b>Bug</b>

1. Set up the vscode-mock-debug sample and run it.
2. Begin stepping through readme.md example "code" using Step Over button on debug toolbar.
3. After a step or two, click the Restart button on that toolbar.
4. The debug toolbar disappears. It is necessary to change focus (e.g. click onto body of the open readme.md file, or onto a different application) in order to make debugging start and the debug toolbar reappear.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.15063

Also happens on latest 1.29 Insider.

**Comment by gjsjohnmurray** [comment]
Try setting EMBED_DEBUG_ADAPTER = true and then launching the Extension debug config of vscode-mock-debug per the instructions at https://code.visualstudio.com/docs/extensions/example-debuggers#_alternative-approach-to-develop-a-debug-extension

When I flip EMBED_DEBUG_ADAPTER to false I no longer get the problem.

**Comment by isidorn** [comment]
I do not plan to fix this. Closing
