### ISSUE TITLE
Don't accept suggestion on `.` 

### ISSUE THREAD

**Issue by BairDev** [Microsoft/vscode#6237]
- VSCode Version: 1.1.0
- OS Version: Ubuntu 14.4, 64 bit

Steps to Reproduce:

1. Start a TypeScript file
2. Use methods on any kind of object, in my case lodash, which is imported and available globally as `_`
3. type *_* (or however you object is named), than *.* and if there are any suggestion for completion, the suggestion is accepted.

I'm not sure, whether this is a bug or intended behaviour, but it is annoying, that there are additional keys/inputs, which work like `"editor.acceptSuggestionOnEnter": true`.

**Comment by jrieken** [comment]
A few languages define a rule like so: `"editorTextFocus && suggestWidgetVisible && editorLangId == 'typescript' && suggestionSupportsAcceptOnKey"` which means certain character accept completions *and* insert the character. It's by design but I understand that it's not desirable for everyone

**Comment by jrieken** [comment]
Actually, this can be configured. @BairDev Just add the following to your keybindings configuration and `.` isn't an accept character anymore

```json
{
	"key": ".",
	"command": "",
	"when": "editorTextFocus && suggestWidgetVisible && editorLangId == 'typescript' && suggestionSupportsAcceptOnKey"
}
```

**Comment by jrieken** [comment]
@alexandrudima I would be really cool if we have a _unbind this_-shortcut/command on the LHS keybindings editor such that it generated these kind of configs

**Comment by alexandrudima** [comment]
@jrieken Here is the request: #612

**Comment by BairDev** [comment]
@jrieken It works great, thanks!
