### ISSUE TITLE
Add API that allows webviews to open in background

### ISSUE THREAD

**Issue by akaroml** [microsoft/vscode#62375]
## Symptom
I'm using the `createWebviewPanel()` API to present a web view. I want the new web view to **NOT** take the focus by setting the `preserveFocus` option to `true`.
The documentation stated this:

> @param showOptions Where to show the webview in the editor. If preserveFocus is set, the new webview will not take focus.

VS Code does not seem to respect the option and presents the new webview in the front.

Here's the actual `showOptions` I'm using:
```
    {
      viewColumn: vscode.ViewColumn.One,
      preserveFocus: true
    }
```

## Expected Behavior
VS Code conforms to the contract and show the new webview in the background.

**Comment by akaroml** [comment]
Any updates? @mjbvz

**Comment by mjbvz** [comment]
From your comment it sounds like you are trying to use `preserveFocus`  to open a webview in a background tab. Is that correct?

`createWebviewPanel` always makes the webview visible, `preserveFocus` just controls if it also becomes focused or not (if you replace the already focused editor, the webview will be focused regardless of `preserveFocus`).

**Comment by akaroml** [comment]
> From your comment it sounds like you are trying to use `preserveFocus` to open a webview in a background tab. Is that correct?
> 
> `createWebviewPanel` always makes the webview visible, `preserveFocus` just controls if it also becomes focused or not (if you replace the already focused editor, the webview will be focused regardless of `preserveFocus`).

Yes, open a webview in a background tab is exactly what I wanted to do. Seems like preserveFocus will not help achieve this. Any suggestions on how this can be done?

**Comment by mjbvz** [comment]
This can't be done currently. I've updated the title to reflect the feature request

**Comment by mjbvz** [comment]
Closing due to lack of interest expressed in this over the past few years
