### ISSUE TITLE
Warning is shown after automatically navigating from last merge conflict 

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#62385]
Testing #45853

- Enable `merge-conflict.autoNavigateNextConflict.enabled`
- After merging the last conflict following warning is shown

![image](https://user-images.githubusercontent.com/10746682/47854824-12f28b00-dde3-11e8-9f1b-bbb3b83e29f1.png)

If auto navigation is enabled then I do not think this warning is needed

**Comment by laphets** [comment]
Would like to pick this up
