### ISSUE TITLE
Debugger ignores changes in breakpoints

### ISSUE THREAD

**Issue by zimmelbc** [Microsoft/vscode#62388]
Issue Type: <b>Bug</b>

Running VS Code v1.28.2 executing a React application and debugging Node.js v8.9.3 on Chrome v61.0.3163.100. I set breakpoints and the debugger stops as expected. If I then add/edit/remove breakpoints, the debugger ignores any changes. Stopping and starting the debugger then detects the new breakpoints.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.85GB (6.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
phpserver|bra|2.4.6
githistory|don|0.4.3
gitlens|eam|8.5.6
php-debug|fel|1.12.6
auto-close-tag|for|0.5.6
lambda-snippets|log|0.2.0
aws-cli-configure|mar|0.3.0
python|ms-|2018.9.2
PowerShell|ms-|1.9.0
debugger-for-chrome|msj|4.10.2
debugger-for-edge|msj|1.0.6
php-ci|sma|0.2.10
code-spell-checker|str|1.6.10

</details>

**Comment by roblourens** [comment]
Can you set `"trace": true`, run it again reproing the issue, and upload the log here?
