### ISSUE TITLE
Go To Definition(F12) option need to be enhanced (Even the Definition one is in another page with in the project))like sublime text?i'm facing this issue from long since i install VS code ?Any help on this? 

### ISSUE THREAD

**Issue by vinod-a-ext** [Microsoft/vscode#6238]
- VSCode Version:Latest 1.1.0
- OS Version:windows

Steps to Reproduce:

1. In your controller inject a service/factory for a http call
2. press F12 (go to definition ) to visit the factory which results negative?

**Comment by isidorn** [comment]
Please provide a short code snippet for which this behavior can be reproduced. Or even better create a repository on gitHub which we can clone and see this behavior

**Comment by vinod-a-ext** [comment]
1.factory.js file
`(function() {
'use strict';

    app.factory('Service', function() {
        return{
            Callmefromcontroller : function() {
           return '1';
                }
        }  
});
});
`
2.controller.js

`
 Controller of the App
 
app.controller('Aboutus2Ctrl', function ($scope,Service) {
Service.Callmefromcontroller();

  });`

**Comment by vinod-a-ext** [comment]
when i press F12 on Callmefromcontroller in controller.js I need to go to Callmefromcontroller defintion method which is in factory.js file?Any help on this

**Comment by jrieken** [comment]
@vinod-a-ext I formatted the snippet to your previous comment, hope it's still correct.

**Comment by jrieken** [comment]
and to clarify, you want `go to definition` understand the service injection tricks such that the editor knows that the `Service` argument has been injected and find where it was defined?

**Comment by vinod-a-ext** [comment]
Spot on @jrieken i need same thing which done perfectly in sublime text editor

**Comment by jrieken** [comment]
ok. moving to the TypeScript team which provides the brain the behind JavaScript and TypeScript smartness in VS Code. I know they have been starting some work on support for angular et al

**Comment by jrieken** [comment]
This issue was moved to Microsoft/TypeScript#8547
