### ISSUE TITLE
Why currently I'm able to open only one file per window?

### ISSUE THREAD

**Issue by SuperManEver** [Microsoft/vscode#62393]
With the latest update of VSCode I'm only able to open only one file per window? Why is that? it's not convenient at all

**Comment by kieferrm** [comment]
@SuperManEver can you please provide the exact way you open files? What platform are you on? On what version of VS Code? Thanks!

**Comment by SuperManEver** [comment]
@kieferrm I open files in a usual manner just by click file a project explorer on the left.
Version: 1.28.2
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:20:56.183Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
I use Ubuntu 18.04

**Comment by gpoussel** [comment]
When you single-click a file from Project Explorer, you are in *Preview Mode* ; and you can have only one Preview open at a time.
As soon as you perform a change to a file, you switch to default mode.

You can either:

- Double-click files in the Project Explorer. They will be opened in default mode.
- Look for "Enable Preview from Quick Open" in your User Configuration, and disable it.

**Comment by SuperManEver** [comment]
@gpoussel Yes. I'm aware of this behavior and how to deal with it. I'm not being able to solve my case using your approach

**Comment by SuperManEver** [comment]
@kieferrm @gpoussel I was able to fix my issue by tweaking some option in settings. it's called 'Enable Tabs' or something like that. Thank you for help. This issue might be closed I guess
