### ISSUE TITLE
Parameter suggest popup has extra empty space

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#62399]
```ts
function foo(a, b) {

}

foo()
```

Trigger the parameter helper window, see empty space where doc comment would go:

![image](https://user-images.githubusercontent.com/323878/47868498-88e5fa80-ddc1-11e8-935e-29a8be211ce3.png)

**Comment by YisraelV** [comment]
Going to work on this.

**Comment by YisraelV** [comment]
@ramya-rao-a 

1 [in this code](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/parameterHints/parameterHintsWidget.ts#L409-L431) both signature.documentation and activeParameter.documentation have value of empty string. Isn't this a bug with the language server for not making them null? That is the reason [this check](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/parameterHints/parameterHintsWidget.ts#L422) doesn't prevent the bug. Null value also makes more sense if there is no documentation.

2. Currently we are only checking if the main documentation is truthy Shouldn't we check for the documentation of the active parameter as well? I mean: 
`		dom.toggleClass(this.signature, 'has-docs', !!signature.documentation && !!activeParameter.documentation);`

Thank you very much.
