### ISSUE TITLE
Show panel buttons on headers when split views are collapsed

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#62391]
In the `Open Editors` section, when collapsed the `Save All`, `Close All` buttons get hidden.
In the `Files` section, when collapsed the `New File`, `New Folder`, etc buttons get hidden.

It would be nice if these buttons were still usable when the section is collapsed.

**Comment by isidorn** [comment]
This is true for all split views. And I personally prefer it the way it is now.
Since it is a feature request against split views forwarding to @sandy081

**Comment by sandy081** [comment]
I also prefer the current approach. 

In general header actions depends on the state of the view. When view is collapsed view is hidden and it could be possible that it can be removed from the document for performance reasons. Actions might not behave expected in that case.

Sorry for not considering this.
