### ISSUE TITLE
Duplicate entries in quick open

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode#62395]
- VSCode Version: 1.29-insiders
- OS Version: Windows 10

Not sure what gets you into the state but, I now have duplicate entries in the quick pick recent files list.

![image](https://user-images.githubusercontent.com/6561887/47865221-dc077f80-ddb8-11e8-9a9f-d9d51f6fe59c.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
Now I remember, this issue: https://github.com/Microsoft/vscode/issues/61805

You can clear history to get rid of them, then should be ok.

**Comment by genosonic** [comment]
I'm experiencing this issue as well, along with other weird behaviors.

**Steps to reproduce:**
1. Ctrl + P
2. Many of the files appear twice on the Recent files list

Another issue, that I imagine is related to the first one, occurs:
3. Click to open any file that appears as duplicate
4. Modify it by typing any key

Two strange things occur:
- A duplicate new tab of the same file appears to the right (marked as unsaved but with no modifications)
- If you try to save the original file, it doesn't save even though it gets marked as saved
- But, if you tap on the duplicate tab, you can actually use that tab work on that file and save does work

Clearing the recent opened files history solved the issues for me, as pointed out by @roblourens .

**Comment by roblourens** [comment]
If so, and you are on the latest insiders, that would sound like a different issue. Can you open a new issue with details @genosonic ?

**Comment by DarkLite1** [comment]
Experiencing the exact same two issues as described by @genosonic 
A. Duplicate entries in quick open
B. Duplicate tabs with the same file name, one tab being empty the other not

I cannot consistently reproduce issue B, but it happens quite often and is very confusing. 

```
Version: 1.30.0-insider (user setup)
Commit: c348be666adf9650b1ae1d212f019e6e9f226b7d
Date: 2018-11-21T06:25:32.454Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 6.2.9200
```

**Comment by DarkLite1** [comment]
@roblourens can this issue be reopened please?
