### ISSUE TITLE
VSCode will not start/debug Forked Processes in VMWare

### ISSUE THREAD

**Issue by adam-beck** [Microsoft/vscode#62394]
- VSCode Versions:
  - 1.28.2
  - 1.29.0-insider
- Host OS: Windows 10 Pro
- Guest OS: Ubuntu 18.04
- Node.js Version:
  - 8.12.x
  - 10.13.0
- Virtualization Software: 
   - VMWare Workstation 14.1.3 build-9474260
   - VMWare Workstation 15.0.1 build-10737736

Steps to Reproduce:

1. Create file that creates a cluser of workers. See https://nodejs.org/api/cluster.html#cluster_cluster

```js
// index.js
const cluster = require("cluster");
const http = require("http");
const numCPUs = require("os").cpus().length;

if (cluster.isMaster) {
  console.log(`Master ${process.pid} is running`);

  // Fork workers.
  for (let i = 0; i < numCPUs; i++) {
    cluster.fork();
  }

  cluster.on("exit", (worker, code, signal) => {
    console.log(`worker ${worker.process.pid} died`);
  });
} else {
  // Workers can share any TCP connection
  // In this case it is an HTTP server
  http
    .createServer((req, res) => {
      res.writeHead(200);
      res.end("hello world\n");
    })
    .listen(8000);

  console.log(`Worker ${process.pid} started`);
}
```
2. Create a debug configuration that attaches to child processes

```json
// launch.json
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Cluster",
      "program": "${workspaceFolder}/index.js",
      "autoAttachChildProcesses": true
    }
  ]
}

``` 

3. Run the configuration

4. Output of "Debug Console":
>/home/adam/.nvm/versions/node/v10.13.0/bin/node --inspect-brk=3239 index.js 
>Debugger listening on ws://127.0.0.1:3239/450c0865-2468-4083-b3f8-ee72f8e591ab
>For help, see: https://nodejs.org/en/docs/inspector
>Debugger attached.
>Master 27097 is running

Observe that the child processes do not log their PID

5. Check that the processes actually started with `ps -ef | grep "index\.js"`

![2018-11-01 12_21_52-milksteak - vmware workstation 14 player](https://user-images.githubusercontent.com/6046654/47864762-ce5df400-ddd0-11e8-8245-23313b52dd07.png)

6. Observe there is no option to debug on certain ports
![2018-11-01 12_23_18-milksteak - vmware workstation 14 player](https://user-images.githubusercontent.com/6046654/47864838-ff3e2900-ddd0-11e8-935e-2c419b2049c1.png)

Note: running this script from the command line (i.e. without VSCode) does display the children's PIDs

![2018-11-01 12_27_06-milksteak - vmware workstation 14 player](https://user-images.githubusercontent.com/6046654/47865019-7d9acb00-ddd1-11e8-8b95-79b1214c8164.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
You have tow launch configs. Which one are you using?
What version of node.js are you using?

**Comment by adam-beck** [comment]
I'll update my question but here is the information

I'm using the `"name": "Cluster"` launch configuration.
I'm using Node.js version `10.13.0`

**Comment by weinand** [comment]
Could you please try whether this works with node.js 8.x?, e.g. by adding a `"runtimeVersion": "8.12"` to your launch config if you are using "nvm" or "nvs".

**Comment by adam-beck** [comment]
It does not work with Node.js version `8.12.0` either.

![2018-11-01 16_43_12-milksteak - vmware workstation 14 player](https://user-images.githubusercontent.com/6046654/47878668-40483480-ddf5-11e8-9e90-4569d506f195.png)

**Comment by weinand** [comment]
I've tried to reproduce your problem with your exact code and launch config on Ubuntu 18.04, but it works fine for me:
![cluster](https://user-images.githubusercontent.com/1898161/47881097-77ced500-de25-11e8-803b-2396b25d5826.gif)
 
Please note that VS Code now has a debug console per session (process). That explains why you are not seeing the children's PIDs in one place.

**Comment by adam-beck** [comment]
Do you think this could be because I'm inside of a VM. I'm not too informed on subjects so I wouldn't know how to even begin debugging what would be causing yours to work and not mine. Maybe you're even on a VM? 

I'll ask a co-worker to see if they can get my example up and running on their native machine.

**Comment by weinand** [comment]
I'm on a Parallels-VM on macOS configured to have 4 cores.
That's the reason why I see 4 child processes.

Could you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces.

**Comment by adam-beck** [comment]
> Could you try to run VS Code without extensions? From the command line, execute: code --disable-extensions and try your steps again to see if it reproduces.

This unfortunately didn't help either.

> What do you mean by "VSCode's Config Launcher"?

Sorry I just meant launching the debugger from VSCode. If I run this from a terminal window I see the expected `console.log`s. However, you mentioned I shouldn't expect to see them from within VS Code because "debug console per session (process)".

> Maybe there is already a process listening on that port.

I don't think so because when I launch from a terminal window it works as expected and I can access the URL. I also tried changing to a random port and that didn't help.

> Please restart your linux and try again.

This actually worked! I tried it twice (once before submitting the PR and just now). However, it only started 2 of the expected 3 workers. And, once I killed the debug session it didn't start up a 2nd time. Seems to be a clue though.

**Comment by adam-beck** [comment]
So I'm able to get this working on both my laptop and host computer (which are both Windows10). However, inside Ubuntu VMs on both machines it does not work. The thing is the `else` in the script is never ran so I feel as if the `else` block is not running. However, I do see the PIDs of the children when running `ps -ef | grep "index\.js"`

**Comment by adam-beck** [comment]
Another clue, if I grab the `--inspect-brk=19088` and use chrome manually to inspect (via `localhost:19088`), it is paused on the first line of the script. If I hit run _then_ I can actually see the "hello world" on port 8000. However, still no child processes showing up in the VSCode.

**Comment by adam-beck** [comment]
Only seems to be an issue using VMWare. I installed VirtualBox and created a new machine and the code worked. I created a new machine using the exact same steps with VMWare and it didn't work. You said it was working in Parallels on Mac.

**Comment by adam-beck** [comment]
Changed title of defect to more accurately reflect the situation. If anybody has any ideas on how to debug this I would be willing to give it a look.

**Comment by weinand** [comment]
I do not have access to VM Ware, so I cannot investigate this myself.

**Comment by jakawell** [comment]
I can't attach in a Hyper-V VM either, for what it's worth. I'm sure why this has been labeled "Out of scope"?
