### ISSUE TITLE
Allow scripts in *.code-workspace

### ISSUE THREAD

**Issue by lukepighetti** [Microsoft/vscode#62396]
Hello! I use workspaces to handle monorepos. Works great. We put our build scripts at the repo root and they reach into each folder as needed. I would like to be able to put a script at the top level so we can trigger these scripts from the command palette. In searching for a solution it seems that the scripts need to be placed in `%WORKSPACE_ROOT%/%WORKSPACE_FOLDER%/.vscode/config.json` which means that we need the scripts placed in every individual top level folder in our monorepo.

Perhaps I missed something but this feature request is to allow scripts in *.code-workspace.

Cheers
Luke

**Comment by kieferrm** [comment]
It seems to me that the proper layout in your case would be to move the scripts you have at the root into a dedicated scripts folder and to make that scripts folder part of your workspaces. This way, tasks, etc. can pick up the scripts as expected.

**Comment by lukepighetti** [comment]
Thanks for letting me know and I believe closing this issue is reasonable. Cheers.
