### ISSUE TITLE
Auto-complete of HTML Media Element

### ISSUE THREAD

**Issue by zbandhan** [Microsoft/vscode#624]
Provide "HTML Media Element" intellisense support inside js file.

`<video src=""><\video>`

`document.querrySelector('video').paused;`

"paused" should be auto-complete in JavaScript and inside `<script><\script>`

**Comment by brandonrninefive** [comment]
Hello, I just tested this on Debian 9 64-bit in both scenarios and it seems to be working. Perhaps this feature was added in a commit over the past two years? Screenshots below.

![pause1](https://user-images.githubusercontent.com/6752598/27714387-8efaaa46-5cfe-11e7-82fb-6214fe94dca8.png)

![pause2](https://user-images.githubusercontent.com/6752598/27714443-e59cb696-5cfe-11e7-825e-e800e9748bc6.png)

**Comment by mjbvz** [comment]
Yes this was fixed at some point. If you don't see the property types on your element, try casting it to an `HTMLMediaElement `:

```js
const myElement = /** @type {HTMLMediaElement} */ (document.getElementById('id'))
myElement.pause
```

<img width="894" alt="screen shot 2017-10-11 at 8 52 14 pm" src="https://user-images.githubusercontent.com/12821956/31478576-2924453c-aec6-11e7-9994-1b48143990fd.png">
