### ISSUE TITLE
`workbench.action.showCommands` command should accept a filter term...

### ISSUE THREAD

**Issue by busticated** [Microsoft/vscode#62400]
hi there :wave:

i have an extension with a number of commands. i've created a welcome screen to try and help onboard my users that behaves similarly to VSCode's main welcome screen. on my welcome screen i have a link to "show available commands" which when clicked ultimately runs `executeCommand('workbench.action.showCommands')`

it would be great if there was a way to filter the command palette using a specific prefix - something like: `executeCommand('workbench.action.showCommands', <term-to-filter-on>)`

thanks!

**Comment by busticated** [comment]
perhaps some overlap with 👉 https://github.com/Microsoft/vscode/issues/38841

**Comment by brycefranzen** [comment]
You could always do this:
`{
  "key": "alt+z",
  "command" : "workbench.action.quickOpen", 
   "args"   : ">{type your filter string here}",
   "when"   : "editorTextFocus"
}`

**Comment by busticated** [comment]
@brycefranzen that works well - thanks!

`workbench.action.quickOpen` (or `workbench.action.showCommands`) isn't documented here: https://code.visualstudio.com/api/references/commands which is unfortunate

**Comment by chrmarti** [comment]
Closing, as your request seems to be fulfilled with that. Thanks. (PRs appreciated: https://github.com/Microsoft/vscode-docs/blob/master/api/references/commands.md)
