### ISSUE TITLE
Wrong rpm version

### ISSUE THREAD

**Issue by martinring** [Microsoft/vscode#6240]
- VSCode Version: 1.1.0
- OS Version: Fedora 23

Steps to Reproduce:

1. Download current rpm from https://go.microsoft.com/fwlink/?LinkID=760867
2. Try to install (console or gui doesn't matter)

It will not install if vscode 1.0.0 ist already installed because the rpm for 1.10 is also versioned as 1.0.0. 

Workaround before fixed: uninstall vscode 1.0.0 beforehand or use `rpm --force --install`

**Comment by Tyriar** [comment]
@martinring where are you seeing that 1.1.0 is versioned as 1.0.0? The `Version` property in the spec file should be set correctly:

![image](https://cloud.githubusercontent.com/assets/2193314/15205447/2f66939c-17cc-11e6-9a74-9019e73079f3.png)

**Comment by martinring** [comment]
This is what I get, when I use the above link. I just got the feeling, the error might be on my side. Maybe there is some broken old install.. I check it right now

![screenshot from 2016-05-12 08-30-47](https://cloud.githubusercontent.com/assets/763861/15205993/0c0101f8-181c-11e6-95b3-61d4c1530153.png)

**Comment by Tyriar** [comment]
@martinring there are definitely some weird differences in the screenshots. I have experienced issues before when updating the rpm, restarting fedora always seemed to fix the issue. I assumed it was the GUI updater's fault as cli install always worked.

The revision which is an epoch timestamp for mine is Mon, 09 May 2016 12:47:01 GMT, yours is Wed, 13 Apr 2016 14:17:11 GMT so it's definitely the March release.

I'll close this assuming you were targeting the wrong file somehow, please let me know if you find any other issues with installing though.

**Comment by martinring** [comment]
Hmm... restarting after removing every old version of vscode changed the issue but didn't necessarily improve on it. Still not able to install via GUI. 

![screenshot from 2016-05-12 08-48-13](https://cloud.githubusercontent.com/assets/763861/15206287/50333966-181e-11e6-823f-4415bee0972b.png)

Ok, but this is clearly not an issue with the vscode rpm package, but something is messed up on my system.

Sorry to have bothered you.

**Comment by Tyriar** [comment]
@martinring no worries, as I mentioned I've experienced issues around updating rpms too so ping me if you find anything else.

**Comment by martinring** [comment]
@Tyriar aha... found the issue. The problem was apparently a `code.desktop` file lying around in my `~/.local/applications` folder. I put it there before there was the rpm package. It pointed nowhere but somehow gnome software seems to check that location. After removing the file and restarting gnome, it now displays the same info as on your screenshot. Maybe this info helps others with the same issue after all.
