### ISSUE TITLE
"Update imports" prompt is slow to appear

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#62402]
- Open vscode workspace
- In file explorer, move `src/vs/platform/search/common/replace.ts` from 'common' to the sibling 'test'
- Wait 5s or more
- "Would you like to update imports?" prompt finally appears

**Comment by roblourens** [comment]
- Move it a second time before the prompt appears
- The prompt appears once
- Click "no"
- The prompt appears again immediately

**Comment by mjbvz** [comment]
Duplicate of #65112. Root cause is upstream: https://github.com/Microsoft/TypeScript/issues/29031
