### ISSUE TITLE
The extentions

### ISSUE THREAD

**Issue by TheETK** [Microsoft/vscode#62408]
I have recently gotten visual studio code and I was following a tutorial and then he added an extension that I needed to as well, did I do something wrong or is it the software because I have an internet connection that is stable, but the program is still unable to connect
![screen shot 2018-11-02 at 7 00 58 am](https://user-images.githubusercontent.com/44683175/47876345-2ea27380-de6d-11e8-8ddc-0be555dad117.png)

**Comment by kieferrm** [comment]
@TheETK you can reach the marketplace (https://marketplace.visualstudio.com) in your browser, correct?

**Comment by rikur** [comment]
```$ tracepath marketplace.visualstudio.com
 1:  localhost                                             0.076ms reached
     Resume: pmtu 65535 hops 1 back 1 
```

Seems like I had added a record to /etc/hosts to stop the editor from "calling home". Maybe @TheETK has a similar problem.
