### ISSUE TITLE
Search improperly matches files inside .git

### ISSUE THREAD

**Issue by elprans** [Microsoft/vscode#62409]
- VSCode Version: 1.29.0-insider (4a29bd3731e40c07622bae0e9b0ac3b422b5672a)
- OS Version: Gentoo x64

Steps to Reproduce:

1. Enable git rerere `git config rerere.enabled true`
2. Deal with a merge conflict, git records `preimage`/`postimage` for the merge conflict files. 
3. In VSCode, perform a search, and you'll get results from `.git/rr-cache` even though `.git` should be completely ignored:

![screenshot_20181101_161512](https://user-images.githubusercontent.com/347119/47877570-95cf1200-ddf2-11e8-895f-c2766a1db569.png)

Search log trace:

![screenshot_20181101_161541](https://user-images.githubusercontent.com/347119/47877582-a2ec0100-ddf2-11e8-9c59-a2a1591af2fb.png)

Not that doing the same search with `rg` directly does not seem to reproduce the issue:

![screenshot_20181101_161649](https://user-images.githubusercontent.com/347119/47877640-c151fc80-ddf2-11e8-8d2b-f1a67375fc83.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by elprans** [comment]
Other files like `.git/COMMIT_EDITMSG` are also included in search.

**Comment by kieferrm** [comment]
@elprans what do your **Search: Exclude** and **File: Exclude** settings look like? If non of them contains `**/.git` then we'll search inside the `.git` folder.

**Comment by elprans** [comment]
@kieferrm Both **Search: Exclude** and **File: Exclude** are set to default values:

![screenshot_20181101_221527](https://user-images.githubusercontent.com/347119/47890101-bc597100-de23-11e8-91ce-583045cfd503.png)

**Comment by elprans** [comment]
Also, in an earlier log screenshot you can see that `.git` is included in the `"excludePattern"`.

**Comment by roblourens** [comment]
Yes, the exclude patterns are not respected when searching with a `./` pattern, due to my refactoring this month.
