### ISSUE TITLE
PCRE2 search does not support \u{0061} in regex 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#62416]
Issue Type: <b>Bug</b>

Testing #61744

**Repo**
1. Enable pcre2 search
1. Open search and enable regular expression search
1. Search for `\u{0061}` (`a`)

**Bug**
No search results. 

If you disable pcre2 search and search then you get the expected results. `\x{0061}` does work with PCRE2 

VS Code version: Code - Insiders 1.29.0-insider (d7ac6e838f51a03f7d417b4758f5fb075878d615, 2018-11-01T06:11:43.390Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|-psn_0_52474376|
|Screen Reader|no|
|VM|22%|

</details>

**Comment by roblourens** [comment]
I remap `\u1234` to `\x1234` but not `\u{1234}` because it isn't supported by JS correctly yet.

```
> /\u{0061}?/.test(Array(62).join('u'))
true
```

**Comment by roblourens** [comment]
Also see https://github.com/Microsoft/vscode/issues/61746

**Comment by roblourens** [comment]
Now this is blocked on https://github.com/microsoft/vscode/issues/61746

**Comment by roblourens** [comment]
Requires https://github.com/microsoft/vscode/issues/61746
