### ISSUE TITLE
Cannot clear "top" debug console

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#62417]
VS Code Insiders

- run cluster sample
- terminate all processes
- clear console

Observe: nothing happens

- switch to another debug console
- clear console

Observe: console is cleared

**Comment by isidorn** [comment]
@weinand good catch, thanks! I have verified this works now with the cluster example from [here](https://github.com/Microsoft/vscode/issues/40123#issue-281453170)

**Comment by weinand** [comment]
works fine now.
