### ISSUE TITLE
Indicate VSCode Version on download page.

### ISSUE THREAD

**Issue by martinring** [Microsoft/vscode#6241]
Currently there is no way to find out, which version is offered for download on the website. It would be great if the download page would indicate that in some way (or at lease the downloaded file would have the version in its name). Especially since versions seem out of sync quite regularly for a short period after release, which is annoying because the only way of finding out is to download and install.

**Comment by waderyan** [comment]
Good suggestion. Added to vscode-website backlog.

**Comment by waderyan** [comment]
Closed and tracked in vscode-website backlog.
