### ISSUE TITLE
Splitting the terminal doesn't open a quickpick anymore

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#62410]
Issue Type: <b>Bug</b>

Clicking on the "Split Terminal" button used to show a quickpick when in a multi-root workspace, but now it seems to just duplicate the current terminal.

Is that intentional? I personally preferred it the other way if so 😉 

/cc @Tyriar 

VS Code version: Code - Insiders 1.29.0-insider (d7ac6e838f51a03f7d417b4758f5fb075878d615, 2018-11-01T06:20:59.729Z)
OS version: Windows_NT x64 10.0.18267

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (19.69GB free)|
|Process Argv|C:\Users\Eric\code\codestream\vscode-codestream\codestream.code-workspace|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by kieferrm** [comment]
@eamodio you can control this now with `terminal.integrated.splitCwd`.

**Comment by eamodio** [comment]
@kieferrm Thanks -- it would be a great enhancement to provide an `alt` command for that button to switch between the split and split with picker.
