### ISSUE TITLE
Clicking on a "..." menu again after opening doesn't close the menu

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#62413]
Issue Type: <b>Bug</b>

Prior to the new menu work (which I **love** btw), if you clicked on the "..." icon again after opening the menu it would close it. That doesn't work anymore, the menu just stays visible.

/cc @sbatten 

VS Code version: Code - Insiders 1.29.0-insider (d7ac6e838f51a03f7d417b4758f5fb075878d615, 2018-11-01T06:20:59.729Z)
OS version: Windows_NT x64 10.0.18267

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (19.76GB free)|
|Process Argv|C:\Users\Eric\code\codestream\vscode-codestream\codestream.code-workspace|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by joaomoreno** [comment]
Let's add it!

**Comment by sbatten** [comment]
code changes in PR. moving to December to merge in debt week.
