### ISSUE TITLE
Start without debugger doesn't start without debugger

### ISSUE THREAD

**Issue by rchiodo** [Microsoft/vscode#62422]
Issue Type: <b>Bug</b>

Create an extension
Build the extension
Start debugger without debugging

Expected:
Another copy of VS code starts without starting the debugger

Actual:
Another copy of VS code starts and the debugger is attached.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 3492)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (2.90GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.12.5
react-javascript-to-typescript-transform-vscode|moh|1.10.0
vscode-language-pack-ja|MS-|1.28.2
python|ms-|2018.9.2
azure-account|ms-|0.4.3
cpptools|ms-|0.20.1
debugger-for-chrome|msj|4.10.2
typescript-hero|rbb|3.0.0

</details>

**Comment by isidorn** [comment]
Starting without debugging is only supported if the extension supports it.
@rchiodo I can not reproduce what you are saying. Can you reproduce with latest vscode insiders https://code.visualstudio.com/insiders/
Though it is expected that the debugger is attached, it is just not expected that you can hit breakpoints and stop. What exactly are you seeing?
