### ISSUE TITLE
Notifications: custom context menu stealing focus causes issues

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#62425]
From verifying #57997

- On Linux for custom dropdown
- Click a notification to activate it and show buttons
- Tab to gear icon
- Space to show it
- Esc to hide it
- The notification is no longer active and buttons aren't visible
- I can get the focus outline on the notification but space doesn't do anything, I can't get the buttons to show up

![nov-01-2018 17-25-57](https://user-images.githubusercontent.com/323878/47887171-37f2f800-ddfb-11e8-8685-8345a5ce39dc.gif)

**Comment by bpasero** [comment]
This is a consequence of the custom menu taking focus away from the element that has focus. Maybe as a workaround the context menu service should focus back the DOM element it was showing around if the menu is closed without invoking an action.

**Comment by sbatten** [comment]
resolved elsewhere
