### ISSUE TITLE
Very poor marketplace search ordering for "Java Debugger'

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#62426]
Issue Type: <b>Bug</b>

**Repo**
1. In extension view, search for `Java Debugger`

**Bug**
The `debugger for java` extension is not in the first 10 results

![screen shot 2018-11-01 at 6 15 33 pm](https://user-images.githubusercontent.com/12821956/47888551-55779000-de02-11e8-97a4-f1d79f9faad4.png)

VS Code version: Code - Insiders 1.29.0-insider (d7ac6e838f51a03f7d417b4758f5fb075878d615, 2018-11-01T06:11:43.390Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|22%|

</details>

**Comment by joaomoreno** [comment]
cc @viradhamMS @pkuma-msft

**Comment by roblourens** [comment]
Possibly from https://github.com/Microsoft/vscode/pull/62247/files

**Comment by ramya-rao-a** [comment]
Fixed with https://github.com/Microsoft/vscode/pull/62508
