### ISSUE TITLE
In the configuration of the integrated terminal's shell the Linux configuration is applied to osx

### ISSUE THREAD

**Issue by sh-tech** [microsoft/vscode#62439]
- VSCode Version:1.28.2
- OS Version:macOS Mojave version 10.14.1

Steps to Reproduce:

1. Install VSCode by homebrew
2. I tried to change the shell of the integrated terminal from bash to zsh (setting.json)
    Specifically, I changed terminal.integrated.shell.osx.
　` "terminal.integrated.shell.osx" : "/usr/local/bin/zsh" `
3. Somehow it does not work properly
4. I changed the item of Linux this time.
   ` "terminal.integrated.shell.linux" : "/usr/local/bin/zsh" `
5. Although it is macOS, the linux setting was applied. 🤔 

Does this issue occur when all extensions are disabled?:  Yes

**Comment by kieferrm** [comment]
We don't provide a homebrew install. Does the same issue occur for you when you install VS Code directly from https://code.visualstudio.com?
