### ISSUE TITLE
Slow scrolling for binary file opened as text

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#62430]
Issue Type: <b>Bug</b>

**Steps**
1. Open this binary file in VS code: [img.ping.txt](https://github.com/Microsoft/vscode/files/2540746/img.ping.txt)
1. Select that you want to open it as text. It should open as `utf-8`
1. Try scrolling through the file

**Bug**
Notice a lot of scrolling slow down and jitter. [Profile-20181101T184133.json.zip](https://github.com/Microsoft/vscode/files/2540748/Profile-20181101T184133.json.zip)

Seems that `viewLine` is triggering a layout that takes over 150ms while scrolling.

Similar to #47683

VS Code version: Code - Insiders 1.29.0-insider (d7ac6e838f51a03f7d417b4758f5fb075878d615, 2018-11-01T06:11:43.390Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|22%|

</details>

**Comment by alexandrudima** [comment]
I agree this is slow as hell, but there is nothing I can think of to improve things for rendering such a range of characters (invalid ones as well). Most of the time is spent by Chromium doing layout... A possible user workaround is to enable word wrapping to limit the amount of text rendered in the viewport.

**Comment by eamodio** [comment]
@alexdima I no longer see the file above slow with scrolling, but I am seeing really slow jittery scrolling with this json file:
[vscode-debugadapter.zip](https://github.com/microsoft/vscode/files/4028270/vscode-debugadapter.zip)

**Comment by alexdima** [comment]
@eamodio I have looked at your sample file and profiled the scrolling, but there is nothing jumping out. That is a file with very many long lines. In fact, there are long patches of lines with over 10k characters. This is kind of the worst case scenario, given we haven't implemented horizontal virtualization. So even if the viewport only contains 200 characters horizontally, the entire 10k characters are painted, so rendering is a lot slower, especially when scrolling vigorously and all old lines are removed from the viewport and all new lines are inserted. 

I have to be honest and say that I won't do any changes to address these worst-case files... The only changes I could do would be to implement horizontal virtualization, but that only for ASCII lines and monospace fonts, but I don't plan to do that as part of a bug-fix.

All in all, the honest thing is for me to close this issue as I won't do anything to target it.
