### ISSUE TITLE
VScode is Freezing 

### ISSUE THREAD

**Issue by Chandu3245** [Microsoft/vscode#62436]
- Extension Name: all default extensions
- Extension Version: NA
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:
```json 
{
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 37,
		"activateCallTime": 1,
		"activateResolvedTime": 0,
		"activationEvent": "onLanguage:jsonc"
	}
}
```
Initially VScode gets freezed, then a popup promts at left bottom with message "Extension host is now responsive". Dont know why I am experiencing this behaviour recently in VScode, its annoying.

**Comment by graph** [comment]
I'm also experiencing this on both Windows & Linux. I'm editing python & c++ files. I leave the editor open for days btw. But freezing happens throughout sometimes early after restart too. Hard to reproduce, just happens randomly. Been happening everyday. 1 of my cores goes to 100% when it happens, obviously one of the vs code processes.

**Comment by kieferrm** [comment]
@Chandu3245 pls update to the latest version 1.28.2. Also see #60318.

@graph can you please file a separate issue. Please include which processes are running wild. Please use `code --status`. Also, please see https://github.com/Microsoft/vscode/wiki/Performance-Issues.

Thanks!
