### ISSUE TITLE
[html] Cannot get close tag suggestions for HTML after updating to 1.1.0

### ISSUE THREAD

**Issue by ndkcha** [Microsoft/vscode#6243]
- VSCode Version: 1.1.0
- OS Version: OS X 10.11.4

Steps to Reproduce:

1. While editing html code

Before updating visual studio code, whenever I start typing closing tag. I used to get suggestions that result into proper indentation as well. But after updating it, I'm not able to do it.

I'm attaching screen shot

<img width="1280" alt="screen shot 2016-05-10 at 5 20 00 pm" src="https://cloud.githubusercontent.com/assets/8328240/15145522/b85e9b12-16d3-11e6-877d-9618e19da9ef.png">

**Comment by sandy081** [comment]
Verified that intelli-sense shows closing tags and on selection properly indented.

**Comment by ndkcha** [comment]
Is the update released ?
