### ISSUE TITLE
Can't parse C code properly.

### ISSUE THREAD

**Issue by bearuse** [Microsoft/vscode#62437]
Issue Type: <b>Bug</b>

With special character input, it can't parse C codes properly.
Color is not matched with codes and byte code.
For example, it can't parse '\\\"' in below source codes.

if(parm[0] == '\\\"')
				{
					if(parm[size+1] == '\\\"')
					{
						LOG_MESSAGE("Writing data with ASCII codes\n");
						ret = Diag_SetDID(did_no, &parm[1], &err_code, DID_ORIGIN_ETC);
					}
					else
					{
						LOG_MESSAGE("size doen't match\n");
					}
					break;
				}

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2194)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (0.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-great-icons|emm|2.1.44
capl-vector|kma|0.1.1
clangcomplete|kub|1.0.1
vscode-language-pack-ko|MS-|1.28.2
cpptools|ms-|0.20.1
reloaded-cpp|rel|0.1.6
vscode-icons|rob|7.28.0
vscode-hexdump|sle|1.7.0

(13 theme extensions excluded)

</details>

**Comment by bearuse** [comment]
Special character is not input properly.
'\"' -> '\\\"' is right.

**Comment by bearuse** [comment]
I attach a unmatched color in the codes.
![image](https://user-images.githubusercontent.com/5081705/47894480-6da0eb00-dea6-11e8-885c-1fc5f0840820.png)

**Comment by gpoussel** [comment]
This code is wrong, isn't it?
As far as I can tell, single-quotes are used for single-character only. And in your code, you use `'\"'` which is two characters. Backslashes are not escaping anything here.

**Comment by kieferrm** [comment]
This is what I get in the latest insider without any C/C++ extension installed:

<img width="592" alt="image" src="https://user-images.githubusercontent.com/4674940/47967661-b4145800-e014-11e8-94dc-c95411e7dc2a.png">
