### ISSUE TITLE
Add an ability to color code folders in sidebar!

### ISSUE THREAD

**Issue by techsin** [Microsoft/vscode#62432]
It'd make my life easier if I could custom color code the folders and all directories in them. 

So I can easily Tell whether register.js is from backend or frontend directory. 

While reveal in sidebar is very useful. I've to visually trace it back to section of code the file belongs to. 

![new project](https://user-images.githubusercontent.com/4664695/47890561-c8463280-de25-11e8-8ac0-d8c152234ae9.png)

of course highlight would be behind text color

**Comment by techsin** [comment]
+1

**Comment by techsin** [comment]
@isidorn can you link the duplicate issue?

**Comment by techsin** [comment]
I searched and couldn't find anything

**Comment by isidorn** [comment]
Search for issues with tags: file-explorer and feature-request

**Comment by techsin** [comment]
Still didn't find any request that mentioned color coding folders in sidebar... Can you link to duplicate you found?

**Comment by techsin** [comment]
you added duplicate tag, can you also add the link to of what it's duplicate of.

**Comment by techsin** [comment]
Thanks, that says exactly what i wanted.
