### ISSUE TITLE
Allow code and file navigation to always open in a separate editor

### ISSUE THREAD

**Issue by entonio** [Microsoft/vscode#62433]
I've searched for this and to my surprise didn't find it.

When control/cmd-clicking a code element to go to its source, or when clicking a file on the folder pane, sometimes the target file will open in the same editor we're using, rather than in a separate one. I don't like that.
If we're in an editor with unsaved changes, or if we double-click the file on the folder pane,  it will always open in a new editor (or an existing one, if the other file is already open)
But even in other cases it does use a separate editor, I've been unable to determine when.

I would like an option for it always to use a separate editor (a new one, or an existing one if the file is already open). I even think thats should be the default, but I'll happy if there's an option.

**Comment by kieferrm** [comment]
@entonio pls see 
https://github.com/Microsoft/vscode/issues/62433#issuecomment-435580305 above.

**Comment by entonio** [comment]
Thank you for solving the problem I was having.
1. I've looked at the setting. Yes, it is what I was talking about. No, I would never be able to find it, short of reading the description of all settings one by one (which is not something I'd do when a filter is available). Neither the name, nor the default value, nor the first part of the description are in any way adequate, in my opinion. It's very por UX and would constitute a bug in itself, in my opinion.
2.  My 'preview editors' do not show in italic font. That is objectively a bug either with the font or the description.
3. I think waiting a bit before autoclosing issues would be in order. Some of us don't always have immediate access to vscode during weekends.
4. The autoclose message's tone is condescending.

**Comment by entonio** [comment]
To be clear: I've struggled with this problem for months and never suspected there would be a setting already, as I didn't find one the various times I've looked for it. I'm sure I'm not alone in this.
