### ISSUE TITLE
Allow fuzzy result on searching symbol in file 

### ISSUE THREAD

**Issue by eypsum** [microsoft/vscode#62435]
- VSCode Version:
1.28.2
- OS Version:
 Ubuntu Gnome 16.04.5 (x64)

Steps to Reproduce:
I search very often a symbol in current active file using by ctrl+shift+o.
I noticed that takes some inaccurate results than Sublime Text in cases like below.
    **symbols with Under and Upper case naming**
    example 1)
    onSomeHandle()
    onAnotherSomeHandle()
    let search with words such as 'osh' using by ctrl+shift+o
    the result element list are:
    VS Code =>
    onAnotherSomeHandle()
    onSomeHandle()

Sublime Text=>
onSomeHandle()
onAnotherSomeHandle()

what I want is onSomeHandle().

example 2)
setDBook()
setDefineSome(bool)
onStoreDefineAddressBook()
let search with such as 'sdb'
the results :
VS Code =>
onStoreDefineAddressBook()
setDefineSome(bool)
setDBook()
Sublime Text =>
setDBook()
onStoreDefineAddressBook()
setDefineSome(bool)

what I want is setDBook()

On the candidates list, It doesn't focus to the symbol in where the cursor is on editor when search box is invoked by ctrl+shift+o, it always get focus at the top element.
Sublime Text focus to the symbol in which gets the cursor in editor.
In my experience, It gets better convenient in Sublime Text.

I'm new with VS Code, I have used Sublime Text and Eclipse for a few years.
I use always the searching by symbol while work.
I feels a bit more bad than Sublime Text with this feature,
I think this feature should key feature on mention to if not full IDE.

**Comment by eypsum** [comment]
Additionally,  if there are symbols like below,
replaceWaypoints()
requestFromTextSearchResult()
registerService()

If,  search with 'r'
 that candidates ==>
registerService()
replaceWaypoints()
requestFromTextSearchResult()

If, search with 'rw'
    that candidates ==>
     replaceWaypoints()    --> good

now, the problem is following.

if, search with 'rf'
    that candidates ==> there is nothing! what's happen?

**Comment by jrieken** [comment]
This is now actually working. Since a few months outline uses the same fuzzy score algorithm IntelliSense sense does and the samples should you have listed should now work. please file individual issues for cases that don't work well. Happy Coding
