### ISSUE TITLE
Preview Error of Markdown Checklist

### ISSUE THREAD

**Issue by Riajyuu** [Microsoft/vscode#62441]
Issue Type: <b>Bug</b>

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

Just compare these two screenshots:
VSC:
![image](https://user-images.githubusercontent.com/16912240/47896495-beb1de80-dea8-11e8-909b-de8b86bfd77d.png)

GitHub:
![image](https://user-images.githubusercontent.com/16912240/47896506-cb363700-dea8-11e8-9fd6-977e7f7f064a.png)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-6410 APU with AMD Radeon R5 Graphics     (4 x 1996)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|6.97GB (1.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|40%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-auto-open-markdown-preview|hnw|0.0.4
beautify|Hoo|1.4.7
es6-css-minify|olb|2.1.0
material-icon-theme|PKi|3.6.0

</details>

**Comment by mjbvz** [comment]
Our built-in markdown support targets common mark which does not include task lists

Try this extension: https://marketplace.visualstudio.com/items?itemName=bierner.markdown-checkbox
