### ISSUE TITLE
debug: refresh values on doubleclick in the inspection panel and/or increasere responce tollerance of the debugger

### ISSUE THREAD

**Issue by Spown** [Microsoft/vscode#6244]
- VSCode Version: 1.1.0
- OS Version: WIN10 x64
- Node.js 4.4.4

I have a rather complex web-app, heavily reliable on express, mongoose, Q, etc... , thus making input->output chains extremely long from the compiler point of view. so more often than not debugger just gives up on me:
![](https://dl.dropboxusercontent.com/u/105338698/ShareX/2016-05/Code_2016-05-10_13-28-41.png) 

And its not like these values are inaccessible - no, I can view them just fine if add them to the watch (but I have to add the explicit path to the primitive value, since anything object-like won't be expandable and I can't do it for every single piece of data) or I can use the console:
![](https://dl.dropboxusercontent.com/u/105338698/ShareX/2016-05/Code_2016-05-08_06-50-35.png)
The problem is I have to manually do it. Another way is to ``step over`` since it would refresh the watchers, but that's not a solution since data can change in this one step or even the debugger can jump out of the context in question.

And moving forward also leads to an another problem: - stepping/resuming will cause an error message.
![](https://dl.dropboxusercontent.com/u/105338698/ShareX/2016-05/Code_2016-05-09_09-06-04.png)
or sometimes this
![](https://dl.dropboxusercontent.com/u/105338698/ShareX/2016-05/Code_2016-05-09_15-16-06.png)
the funny thing is, I have never experienced an actual decoupling of the debugger from the process - hitting "close" on this message and then repeating the action always resumes the debugging session. The annoying thing is I have to hit "close" twice or even thrice (the message reappears at least once). always. never once. almost every time I ``continue`` or want to ``step into/over`` and I have to do it since this message covers the debugger controls. And I can't use the keyboard enter/esc key - I have to grab the mouse, since the errors aren't modular and do not receive focus.

So, for the fist part (<...> for variable values) - **maybe you could implement refreshing mechanic, on doubleclicking on them?**
And for the second part (error messages) - **some sort of option to control over this mysterious "amount of time" the debugger deems as "reasonable"?**

Steps to Reproduce:
yeah, thats a problem, I can't share my project, and I don't know how to forcefully lag the workflow - I tried to build a test case similar to my project, but it seems it is still "lightweight" enough to not cause the mentioned behavior...

thank you.

**Comment by isidorn** [comment]
Making the node debug timeout configurable makes sense to me. @weinand opinions?

**Comment by Spown** [comment]
>...since this message covers the debugger controls. And I can't use the keyboard enter/esc key - I have to grab the mouse, since the errors aren't modular and do not receive focus.

I've noticed that I'm actually able to close the warnings if I press esc twice. As of now the warnings reappear 4-6 times every time I want to step forward/continue (snowball effect is a factor I guess). And there is a a couple seconds delay between each action which makes my debugging a nightmare... I find it "easier" to debug via ``console.log()`` rather than through interrupting right now.

**Comment by Spown** [comment]
don't want to spoil it, but it seems the 1.2.0 update took care of it all. Haven't seen any warnings and unexpandable <...> variables yet... 

Thank you very much, I feel like flying now :+1:

**Comment by weinand** [comment]
@Spown great to hear!
