### ISSUE TITLE
Integrated Terminal Pane changes shape

### ISSUE THREAD

**Issue by cbluth** [microsoft/vscode#62456]
Version: 1.28.2
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:20:56.183Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Steps to Reproduce:

1. `code ./project-dir`
2. see on monitor vscode launching (integrated terminal not fully drawn to screen yet)
3. use SUPER^Left arrow to "snap" window to left of screen (ubuntu 18.04 feature)
4. integrated terminal finished launching

Does this issue occur when all extensions are disabled?: Yes/No
No, I cannot reproduce.

![image](https://user-images.githubusercontent.com/6709636/47912331-8a362680-de98-11e8-92c8-df62cc5fb8bd.png)

**Comment by cbluth** [comment]
```
cbluth@dl7490:~$ code --list-extensions
DavidAnson.vscode-markdownlint
ms-kubernetes-tools.vscode-kubernetes-tools
ms-python.python
ms-vscode.Go
PeterJausovec.vscode-docker
redhat.vscode-yaml
ziyasal.vscode-open-in-github
cbluth@dl7490:~$ 
```
@kieferrm

**Comment by kieferrm** [comment]
It doesn't seem that any of these extensions is interacting with the terminal size.

**Comment by cbluth** [comment]
@kieferrm @Tyriar 

I can now reliably reproduce it doing these steps:

1. `code ./project-dir`
2. see on screen vscode launching (integrated terminal not fully drawn to screen yet)
3. use SUPER^Left arrow to "snap" window to left of screen (ubuntu 18.04 feature)
4. integrated terminal finished launching

you can see the scroll-bar and the selected text from this screenshot:

![image](https://user-images.githubusercontent.com/6709636/48265691-70af5480-e42d-11e8-83f6-6a93b05fb7b1.png)

**Comment by cbluth** [comment]
it can be fixed by adjusting this panel:

![image](https://user-images.githubusercontent.com/6709636/48266167-de0fb500-e42e-11e8-9f11-dac445315d8d.png)

**Comment by Tyriar** [comment]
I can't reproduce.

> see on monitor vscode launching (integrated terminal not fully drawn to screen yet)

Are you suggesting this is a race condition by quickly snapping the window while the terminal is launching?

**Comment by cbluth** [comment]
> I can't reproduce.
> 
> > see on monitor vscode launching (integrated terminal not fully drawn to screen yet)
> 
> Are you suggesting this is a race condition by quickly snapping the window while the terminal is launching?

No really suggesting that, but i tried it a million times to verify at which point the error would occur.
Originally, the issue seemed to happen randomly when opening a new vscode window, but then I tried to reproduce the issue by doing it fast, and i tried it a little delayed. 

I could only reliably reproduce the issue if the window was still launching.

No, with the build i pasted below, i cannot reproduce the issue at all.

```
Version: 1.29.1
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:07:43.495Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

**Comment by Tyriar** [comment]
I managed to reproduce, likely related to the resize occurring before listeners are installed.

![image](https://user-images.githubusercontent.com/2193314/49468960-177fda00-f7bb-11e8-950a-a40aae44a118.png)

My repro:

1. Open vscode and the terminal
2. Make the window very narrow
3. Close vscode
4. Run `code` and hit super+left while the terminal is blank

**Comment by cbluth** [comment]
> I managed to reproduce, likely related to the resize occurring before listeners are installed.
> 
> ![image](https://user-images.githubusercontent.com/2193314/49468960-177fda00-f7bb-11e8-950a-a40aae44a118.png)
> 
> My repro:
> 
> 1. Open vscode and the terminal
> 2. Make the window very narrow
> 3. Close vscode
> 4. Run `code` and hit super+left while the terminal is blank

sounds about right.

i sometimes swap my vscode window between different sized monitors, not sure if that info is helpful.

**Comment by cbluth** [comment]
> > I can't reproduce.
> > > see on monitor vscode launching (integrated terminal not fully drawn to screen yet)
> > 
> > 
> > Are you suggesting this is a race condition by quickly snapping the window while the terminal is launching?
> 
> No really suggesting that, but i tried it a million times to verify at which point the error would occur.
> Originally, the issue seemed to happen randomly when opening a new vscode window, but then I tried to reproduce the issue by doing it fast, and i tried it a little delayed.
> 
> I could only reliably reproduce the issue if the window was still launching.
> 
> Now, with the build i pasted below, i cannot reproduce the issue at all.
> 
> ```
> Version: 1.29.1
> Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
> Date: 2018-11-15T19:07:43.495Z
> Electron: 2.0.12
> Chrome: 61.0.3163.100
> Node.js: 8.9.3
> V8: 6.1.534.41
> Architecture: x64
> ```

^ i was able to reproduce the error with the build too, this morning.
