### ISSUE TITLE
terminal messy code

### ISSUE THREAD

**Issue by HTw-ss** [Microsoft/vscode#62454]
![image](https://user-images.githubusercontent.com/20150944/47910238-2ed25b80-decd-11e8-928b-2be2329a065e.png)
I use git bash to commit will not cause chinese Character decode problem.
But when I use visual studio code terminal bash to write commit message the problem arises.
The problem arises on the VSC newest version 1.28.2.
And I find that the problem arises in the several recent versions.
Do anyone know why?
Because I did not change any system setting.

**Comment by kieferrm** [comment]
@rebornix do you see the same?

**Comment by rebornix** [comment]
I didn't run into any issue with git commit. But unluckily on Windows, I can't type in the whole Chinese sentence displayed above, it seems the IME handling has some issues with that.

**Comment by HTw-ss** [comment]
This problem arises after I use backspace to delete chinese character.I pressed once the backspace key, the one chinese character successfully deleted as expected, but I have to press the second time to force the cursor go back to the last character.
1.entered '测试测试'
![image](https://user-images.githubusercontent.com/20150944/47981761-18fcaa80-e108-11e8-872f-998a23aee868.png)
2.after I pressed backspace to delete the last character
![image](https://user-images.githubusercontent.com/20150944/47981820-434e6800-e108-11e8-9e58-982e61c5940f.png)
3.I have to press the second time to force the cursor at the right place
![image](https://user-images.githubusercontent.com/20150944/47981826-49444900-e108-11e8-861a-577fc39f0a89.png)
4.used 'git log -1'to log commit message at the ternimal panel
![image](https://user-images.githubusercontent.com/20150944/47982001-fae37a00-e108-11e8-8595-49fcba92e545.png)

5.used git bash here to output the same log
![image](https://user-images.githubusercontent.com/20150944/47981880-89a3c700-e108-11e8-95c7-a49cb84c3a19.png)
![image](https://user-images.githubusercontent.com/20150944/47981958-d8e9f780-e108-11e8-8b4d-70857961a08e.png)

**Comment by jerch** [comment]
Looks like #60717.
