### ISSUE TITLE
Avoid showing another tab automatically when the terminal has the focus

### ISSUE THREAD

**Issue by jjavierdguezas** [Microsoft/vscode#62452]
First thanks for this amazing tool!
Sometimes, I start vscode and start typing in the terminal and it is very annoying that another tab is showed in the middle of what I'm writing (to show me the Output tab  for example).
![vscode](https://user-images.githubusercontent.com/13673443/47908405-70dbad00-de8d-11e8-9f30-352a91dacbba.gif)
Could you please avoid this behavior?
Do not allow another tab to be displayed automatically if the terminal has the focus?
thanks in advance

**Comment by kieferrm** [comment]
This comes from the C# extension. VS Code does not reveal output by itself. Please file the issue against https://github.com/OmniSharp/omnisharp-vscode/issues. Thanks!

**Comment by kieferrm** [comment]
VS Code does not reveal output automatically. Pls file the issue against the C# extension here: https://github.com/OmniSharp/omnisharp-vscode/issues. Thanks!
