### ISSUE TITLE
when open multiple terminals very caton or dead

### ISSUE THREAD

**Issue by dale426** [Microsoft/vscode#62451]
所需的数据太大，无法直接发送。
Issue Type: <b>Bug</b>

1. use ‘ctrl + \’ open  more than three terminal
2. edit some code

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.87GB (8.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|80%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
iview-snippets|bos|0.2.1
bracket-pair-colorizer|Coe|1.0.60
vscode-eslint|dba|1.6.1
vscode-babel-coloring|dza|0.0.4
gitlens|eam|8.5.6
auto-close-tag|for|0.5.6
vue-snippets|hol|0.1.9
autofilename|Jer|0.1.3
vue|liu|0.1.5
jscs-formatter|moo|0.1.1
vscode-language-pack-zh-hans|MS-|1.28.2
debugger-for-chrome|msj|4.10.2
vetur|oct|0.13.0
vscode-icons|rob|7.28.0
px-to-rem|sai|1.2.7
git-merger|sha|0.4.1
background|sha|1.1.19
code-settings-sync|Sha|3.2.0
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details>
我们已经将其写入剪贴板，请粘贴。

**Comment by rebornix** [comment]
@dale426 could you please paste your issue report here in the website?
