### ISSUE TITLE
Proposal: Ability to avoid certain modules/files/folders during debugging process - "smart code stepping"

### ISSUE THREAD

**Issue by MarkPieszak** [Microsoft/vscode#6245]
- VSCode Version: _1.1.0_
- OS Version: OS X

Could it be possible to blacklist certain modules (let's say given libraries within `node_modules` from showing up during the Step Over / In / Out debugging process?

For example, let's say Library -Z- is a common one through out your Node application, but it's very low-level, it would be incredible to have some sort of Flag to say "Skip during debugging process" for the entire (lets say) folder, that way you could continue (F10 etc) and never end up in those files / locations.

Just an idea, I'm not sure how feasible it is.

**Comment by weinand** [comment]
@MarkPieszak VS Code 1.1 supports something like this already: see section "Smart code stepping" in https://code.visualstudio.com/updates#_nodejs-debugging
Currently this only works for a very specific use case, but it should be possible to extend this to your scenario as well.

**Comment by MarkPieszak** [comment]
Thanks @weinand I'm looking at it right now, you guys are one step ahead of me, glad it's at least in the works! :+1: I'll close this out since it's already on your guys radar.

**Comment by weinand** [comment]
@MarkPieszak let's keep this feature request open until your scenario is actually supported...

**Comment by MarkPieszak** [comment]
Sounds good to me, I can keep testing it as features get released as well.

**Comment by weinand** [comment]
@MarkPieszak great! I'll let you know.

**Comment by Spown** [comment]
just to keep things connected:  #3215

**Comment by weinand** [comment]
This feature has been implemented in November 2016.
