### ISSUE TITLE
Intellicode fails completely after hot reboot (python)

### ISSUE THREAD

**Issue by robleolo** [Microsoft/vscode#62450]
1) Have anacondas running
2) Install system VSCODE
3) Install User VSCODE
             --> runs normally for certain number of normal restarts etc (not hot reboot).
4) Run a hot reboot
5) intellicode fails to produce any reference to imported packages or other user-created scripts. Also 'run python file in terminal' functionality fails, although can still obviously run python file by manually inputting the python.exe path and passing the script path as an argument in "" as per normal shell command.

**Comment by kieferrm** [comment]
Please file the issue against the Python extension at 
https://github.com/Microsoft/vscode-python/issues. Thanks!
