### ISSUE TITLE
selecting first option from dropdown when typing a (

### ISSUE THREAD

**Issue by schicks** [Microsoft/vscode#62466]
Issue Type: <b>Bug</b>

Using mocha;
* Create a test file with a top level describe block (describe, context, and it are all in the global namespace)
* create a context within the describe
* when you add the parens after context to call the function, it gets autocorrected to the first symbol in the list.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 7|
|Memory (System)|16.00GB (3.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
haproxy|bma|0.1.1
insert-unicode|bru|0.2.0
vscode-postgres|cko|1.1.4
indent4to2|Com|0.1.2
vscode-eslint|dba|1.6.1
githistory|don|0.4.3
tslint|eg2|1.0.40
prettier-vscode|esb|1.6.1
flow-for-vscode|flo|0.8.4
reasonml|fre|1.0.38
nbpreviewer|jit|1.0.0
vscode-styled-components|jpo|0.0.23
vscode-map-preview|jum|0.4.2
saltstack|kor|0.0.5
graphql-for-vscode|kum|1.12.1
mssql|ms-|1.4.0
python|ms-|2018.9.2
vsliveshare|ms-|0.3.897
debugger-for-chrome|msj|4.10.2
vscode-docker|Pet|0.3.1
material-icon-theme|PKi|3.6.0
ejs-language-support|Qas|0.0.1
scratchpadmd|saa|0.0.4

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
This is by design. Characters like `.` and `(` accept the current suggestion 

Press escape to cancel the suggestion in this case or set `"editor.acceptSuggestionOnCommitCharacter": false` to disable this behavior entirely
