### ISSUE TITLE
Periodically loads the CPU up to 80%. Периодически загружает процессор до 80%.

### ISSUE THREAD

**Issue by andreylc** [Microsoft/vscode#62463]
Issue Type: <b>Bug</b>

When working with css, php files, the editor process consumes up to 80% of CPU power.
При работе с css, php файлами процесс редактора потребляет до 80% мощности процессора.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G2030 @ 3.00GHz (2 x 2993)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (3.32GB free)|
|Process Argv|C:\Users\user\AppData\Local\Temp\scp30258\pride-mebel\wp-content\themes\pride\style.css|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
vsc-material-theme|Equ|2.5.1
php-debug|fel|1.12.6
php-intellisense|fel|2.3.5
php-pack|fel|1.0.2
smarty|imp|0.3.0
vscode-apache|mrm|1.1.1
vscode-scss|mrm|0.6.2
vscode-language-pack-ru|MS-|1.28.2
material-icon-theme|PKi|3.6.0
sass-indented|rob|1.4.9
highlight-matching-tag|vin|0.8.1

(2 theme extensions excluded)

</details>

**Comment by kieferrm** [comment]
@andreylc can you pls follow the steps in https://github.com/Microsoft/vscode/wiki/Performance-Issues to report the performance issue? Thanks!

**Comment by andreylc** [comment]
> @andreylc can you pls follow the steps in https://github.com/Microsoft/vscode/wiki/Performance-Issues to report the performance issue? Thanks!

Thanks. I understand, I'm sorry.
