### ISSUE TITLE
Outline displays wrong hover text for SymbolKind.File

### ISSUE THREAD

**Issue by gjsjohnmurray** [Microsoft/vscode#62460]
Issue Type: <b>Bug</b>

Implement a DocumentSymbolProvider with a simple provideDocumentSymbols method that returns one SymbolInformation entry for each value of the vscode.SymbolKind enumeration, e.g.
```
    public async provideDocumentSymbols(document: vscode.TextDocument, token: vscode.CancellationToken): Promise<vscode.SymbolInformation[]> {
		return new Promise<vscode.SymbolInformation[]>((resolve) => {
			let symbols: vscode.SymbolInformation[] = [];
			// This is just so we can see a samples of all icons
			for (i=0; i<26 ; i++) {
				symbols.push(
					new vscode.SymbolInformation(i.toString(), i, '', new vscode.Location(document.uri, new vscode.Position(i,0)))
				);
			}
			/**/

			resolve(symbols);
		});
	}
```

View the result, and observe how the hover tip for entry 0 (i.e. SymbolKind.File) is "property"

![image](https://user-images.githubusercontent.com/6726799/47913433-f7938880-de93-11e8-83d2-71e754940d42.png)

Indeed, the icon used for 0 is the same as for 6, which is the enumeration value for SymbolKind.Property.

Also, the above screenshot shows that SymbolKind.Null uses the same icon as SymbolKind.Boolean, and Module, Namespace, Package and Object all use the same icon. At least in all of these cases the hover tips allow us to distinguish between them.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.15063

Also occurs in 1.29 Insider.

**Comment by jrieken** [comment]
Yeah, we reuse some icons for different types

**Comment by gjsjohnmurray** [comment]
But for SymbolKind.File why does the hover tip say **'property'** ?

**Comment by jrieken** [comment]
Yeah, that is weird indeed...

**Comment by jrieken** [comment]
This is the problem: https://github.com/Microsoft/vscode/blob/f9f38b2bbf5d5049cad387b97b8fa85e98c6d3c4/src/vs/editor/common/modes.ts#L839
