### ISSUE TITLE
Anaconda custom environment not activating

### ISSUE THREAD

**Issue by tamimmirza** [Microsoft/vscode#62467]
Issue Type: <b>Bug</b>

I created an Anaconda Python 3.7 environment labled "Django" in which I installed django via pip

But when I try to invoke the command "django-admin startproject web_project .".  The terminal states that django is not installed.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (11.04GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.9.2

</details>

**Comment by kieferrm** [comment]
@tamimmirza pls file the issue against the Python extension at https://github.com/Microsoft/vscode-python/issues. Thanks!
