### ISSUE TITLE
Test telemetry

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#6246]
- [x] @seanmcbreen 

Once again telemetry has undergone some refactorings, esp to fix #1000. The appending of events now happens inside the shared process such that DNS issues don't block the main thread anymore. We should **validate** that

* we still send the common properties, like `isNewSession`, `timestamp` etc etc
* we still send the common properties using the same data types, like `timesincesessionstart` is a number, `timestamp` is a string 
* we don't miss events on shutdown
* we still honour the opt out setting

**Comment by jrieken** [comment]
@seanmcbreen fyi master of telemetry data

**Comment by weinand** [comment]
@seanmcbreen Joh mentioned that you've already verified this. If this is correct please set your checkbox and close this item.
