### ISSUE TITLE
Week ranking in extensions viewlet

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#62472]
Issue Type: <b>Bug</b>

Searching for 'azure app service' the extension with that name is place 10:
![image](https://user-images.githubusercontent.com/9205389/47918721-aa241500-dead-11e8-880d-981c4ac40169.png)

VS Code version: Code - Insiders 1.29.0-insider (220bff273eed39013f24b6d26fc17f2a742ce10f, 2018-11-02T06:13:24.258Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (2.00GB free)|
|Process Argv|--user-data-dir /Users/chrmarti/Development/repos/tmp/user2 --extensions-dir /Users/chrmarti/Development/repos/tmp/ext2 --inspect-extensions=22143|
|Screen Reader|no|
|VM|20%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-azurefunctions|ms-|0.12.0
vscode-azurestorage|ms-|0.4.2
vscode-cosmosdb|ms-|0.8.0
mssql|ms-|1.4.0
azure-account|ms-|0.4.3
azurecli|ms-|0.4.2
vscode-node-azure-pack|ms-|0.0.4
azurerm-vscode-tools|msa|0.4.2
vscode-docker|Pet|0.3.1

</details>

**Comment by sandy081** [comment]
cc @viradhamMS @pkuma-msft. Please check it.

**Comment by ashukum-msft** [comment]
Hi @chrmarti, 
We recently did some changes to fix relevance issues and this issue is fixed now.
Please find screenshots below -
![image](https://user-images.githubusercontent.com/56161576/66210463-8679d800-e6d7-11e9-8fd7-b06859c9ccf3.png)

cc @sandy081 @pkuma-msft @kesane-msft

**Comment by chrmarti** [comment]
Looks good, thanks.
