### ISSUE TITLE
[typescript] Hover has not border anymore

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#6247]
- VSCode Version: 1.1 2016-05-09T02:15:45.497Z
- OS Version: Linux Elementary OS

Dark+ theme

- open a TypeScript file, hover over an identifier: Hover lacks a border or a background color.

![image](https://cloud.githubusercontent.com/assets/6461412/15147925/5ab7c318-16c3-11e6-9913-7166dcb35f5b.png)

**Comment by jrieken** [comment]
@bgashler1 was this a UX change?
