### ISSUE TITLE
Clear doesn't work for extension contributed tasks

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#62474]
To reproduce:

package.json
```json
	"scripts": {
		"echo": "node -e console.log('Hello')"
	},
```

tasks.json
```json
		{
			"type": "npm",
			"script": "echo",
			"presentation": {
				"echo": true,
				"reveal": "always",
				"focus": false,
				"panel": "shared",
				"showReuseMessage": true,
				"clear": true
			},
			"problemMatcher": []
		}
```

Observe: terminal is not cleared.

To make this work we need to add the clear here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/tasks/node/taskConfiguration.ts#L750

Sorry for not catching this when reviewing.

**Comment by Areax** [comment]
Fix is in #62495

**Comment by alexr00** [comment]
Reopening until this is merged into release.

**Comment by RMacfarlane** [comment]
Following the steps above, I'm still seeing the task output left in the terminal with the final message "Terminal will be reused by tasks, press any key to close it.". I assume this is what should be cleared.

VSCode version:

Version: 1.29.0-insider
Commit: 5e481940ccf7ed9005dfd810f586c09a49421355
Date: 2018-11-09T14:55:36.370Z
