### ISSUE TITLE
markdown previewer with yaml code block colorizer

### ISSUE THREAD

**Issue by reecebradley** [Microsoft/vscode#62486]
Issue Type: <b>Bug</b>

1. create a markdown file
2. create a yaml code block like this:
```yaml
info:
  name: testname
  long name: testlongname
```
You'll notice the space in the "long name" doesn't colorize correctly in the preview. the inline markdown editor is correctly handling spaces.

![image](https://user-images.githubusercontent.com/1536861/47925558-800e2b00-de8c-11e8-8377-28c3861a9f55.png)

Tried this in vscode insiders as well, same behavior.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.90GB (14.14GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-file-peek|abi|1.0.1
html-snippets|abu|0.2.1
markdown-toc|Ala|1.5.6
markdown-mermaid|bie|1.0.0
vscode-markdownlint|Dav|0.21.0
vscode-new-file|dku|4.0.2
githistory|don|0.4.3
xml|Dot|2.3.2
gitlens|eam|8.5.6
EditorConfig|Edi|0.12.5
LogFileHighlighter|emi|2.4.2
vscode-postman|eri|0.5.2
file-icons|fil|1.0.16
scriptcsRunner|fil|0.1.0
code-runner|for|0.9.5
mdmath|goe|2.3.4
rest-client|hum|0.20.3
ilspy-vscode|ics|0.7.0
Angular2|joh|6.3.0
vscodeilviewer|jos|0.0.1
chat|kar|0.7.3
ecdc|mit|0.12.0
mssql|ms-|1.4.0
azure-account|ms-|0.4.3
csharp|ms-|1.17.0
PowerShell|ms-|1.9.0
vsliveshare|ms-|0.3.897
vsliveshare-audio|ms-|0.1.39
vsliveshare-pack|ms-|0.2.0
vscode-docker|Pet|0.3.1
vscode-yaml|red|0.0.17
vscode-icons|rob|7.28.0
ActiveFileInStatusBar|Ros|1.0.3
markdown-preview-enhanced|shd|0.3.11
vscode-fileutils|sle|2.11.0
vscode-markdown-paste-image|tel|0.9.5
vscode-todo-highlight|way|1.0.4
markdown-all-in-one|yzh|1.7.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Seems fixed in current insiders builds:

![screen shot 2018-11-02 at 11 42 15 am](https://user-images.githubusercontent.com/12821956/47934390-67a20e80-de94-11e8-9e8b-5f8e40487983.png)

**Comment by reecebradley** [comment]
Apologies, left out an important detail. I said it in the title, not the description, the colorizer is not correct in the markdown "Preview". It is correct in the markdown.

**Comment by mjbvz** [comment]
Ok. We use highlight.js in the preview. Can you please file an issue upstream for this: https://github.com/highlightjs/highlight.js
