### ISSUE TITLE
Report Issue does not work on Debian 9.5, KDE Plasma desktop - some extension seems to be the cause

### ISSUE THREAD

**Issue by mrkafk** [Microsoft/vscode#62481]
- VSCode Version: 1.28.2, installed from Apt repos on Debian 9.5 amd64
- OS Version: Debian 9.5 amd64, KDE Plasma desktop

Steps to Reproduce:

1. Ironically, selecting Help | Report Issue results in empty issue report window:

![issue_reporter](https://user-images.githubusercontent.com/593219/47922166-b791cd00-deb6-11e8-8580-ce907018c8f3.png)

Does this issue occur when all extensions are disabled?: **No**

Extension list:
```
AkashGutha.greetings
alanz.vscode-hie-server
alefragnani.Bookmarks
brainfit.vscode-importmagic
BriteSnow.vscode-toggle-quotes
DavidAnson.vscode-markdownlint
donjayamanne.githistory
eamodio.gitlens
formulahendry.code-runner
Gruntfuggly.todo-tree
hoovercj.haskell-linter
humao.rest-client
justusadam.language-haskell
kenhowardpdx.vscode-gist
konstantin.wrapSelection
lukasz-wronski.ftp-sync
mkloubert.vscode-deploy-reloaded
ms-python.python
ms-vscode.cpptools
naturallucky.googlesearch
qezhu.gitlink
qinjia.seti-icons
qinjia.view-in-browser
red-auto.red
ryu1kn.edit-with-shell
Shan.code-settings-sync
shardulm94.trailing-spaces
sidneys1.gitconfig
stkb.rewrap
truman.autocomplate-shell
tushortz.python-extended-snippets
Tyriar.sort-lines
wmaurer.vscode-jumpy
wwm.better-align
Yummygum.city-lights-icon-vsc
yzhang.markdown-all-in-one
```

**Comment by RMacfarlane** [comment]
@mrkafk Can you hit `Ctrl+Shift+I` while focused on the issue reporter window to bring up the dev tools, and see if there is anything in the console?

**Comment by RMacfarlane** [comment]
Actually, nevermind, I have a repro now. Installing `mkloubert.vscode-deploy-reloaded` did it for me.
