### ISSUE TITLE
Latest update (1.1.0) breaks entire UI.

### ISSUE THREAD

**Issue by Peter-LaComb** [Microsoft/vscode#6249]
- VSCode Version: 1.1.0
- OS Version: Windows 8.1

Steps to Reproduce:

1. Alllowed latest version to install
2. Launch VS Code
3. Notice that the entire UI is unusable/black/grey. Only the about box works.

This appears to be a video acceleration issue - moving the window sometimes redraws the UI correctly.

![image](https://cloud.githubusercontent.com/assets/1329239/15150767/8cc36d2a-169c-11e6-96c9-73175194e6e6.png)

**Comment by bpasero** [comment]
@Peter-LaComb is this on a VM?

**Comment by bpasero** [comment]
Also can you try running `code.exe --disable-gpu` from a command prompt from the installation folder of code to see if it makes any difference?

**Comment by Peter-LaComb** [comment]
1) Not on a VM.
2) code.exe --disable-gpu works perfectly. WIsh I had seen that in the docs.

**Comment by bpasero** [comment]
@egamma @gregvanl we should add this to our FAQ when people run into UI issues like this one, do you agree?

**Comment by egamma** [comment]
Agreed filed https://github.com/Microsoft/vscode-docs/issues/300

**Comment by Tyriar** [comment]
@bpasero should `--disable-gpu` be added to `code --help`. FYI I can't seem to find it in `google-chrome --help` or https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md

**Comment by bpasero** [comment]
@Tyriar I think its a hacky workaround for an issue we do not understand, nor do we know the consequences in terms of performance.

**Comment by Peter-LaComb** [comment]
@bpasero - I'm not yet the heaviest VSCode user, but the performance impact appeared minimal. It's more likely an issue with my actual video drivers - Chrome and Slack started breaking in the same way shortly afterward. Makes me kind of sad to see that GPU acceleration is required for such a clean and simple looking UI.

**Comment by Peter-LaComb** [comment]
Can I vote to close this? I'm happy with the FAQ addition and some tweaks to my video driver (I don't recall installing an update or changing settings before this) have resolved the issue, even without the --disable-gpu.
