### ISSUE TITLE
Git clone not in command pallet

### ISSUE THREAD

**Issue by NaemBhuiyan** [Microsoft/vscode#62499]
Issue Type: <b>Bug</b>

I cant clone the git repository 
in the command platte there is no clone option for cloning 

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (3.94GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|1.6.1
beautify|Hoo|1.4.7
cpptools|ms-|0.20.1
debugger-for-chrome|msj|4.10.2
LiveServer|rit|5.1.1
open-in-browser|tec|2.0.0
bootstrap4-vscode|the|4.3.0

</details>

**Comment by cleidigh** [comment]
@NaemBhuiyan 
Running Code 1.28.2 under Windows 10, I am unable to reproduce this.
Under the command pallet, the command "Git: Clone" appears as expected.

Can you provide any more information?
