### ISSUE TITLE
[Extension] Is it possible to stop a TreeItem tied to a workspace resource from getting Emphasized?

### ISSUE THREAD

**Issue by tetchel** [microsoft/vscode#62497]
Sorry if this doesn't belong here, but I already have [a StackOverflow question](https://stackoverflow.com/questions/53094634/stop-treeitem-from-being-emphasized) which no one has helped with. Copied here: 

In my extension, I have a TreeView where the TreeItems have their `resourceUri` set to point to a folder in the workspace. When I have errors/warnings/etc in those folders, the folder gets Emphasized (turns green/red/etc and gets a dot to the right side), as does the TreeItem that matches it.

I don't want this behaviour in my TreeView. Is it possible to disable Emphasizing a TreeItem while still setting the `resourceUri` field?

**Comment by jrieken** [comment]
That's currently not possible

**Comment by tetchel** [comment]
Thanks for the response. Consider this a feature request, then :)

**Comment by sandy081** [comment]
@tetchel When you use a resource then we would like to make sure this resource is displayed same at all places in VS Code. This makes UI good and consistent. 

If you do not want to render them as resources, can't you not use the resource and set label and icon yourself?

Also may I know why do you not want to have resource decorations?

**Comment by tetchel** [comment]
Hey Sandy,

Good questions. I am not rendering them as resources, and am providing my own label and icon as you stated. 

However, this made me question why exactly I was setting the resourceUri in the first place, since this was one of the first things I did when I started my extension work a couple months ago. After doing some digging, I could not come up with any good answer. I'm not sure if I thought it was required to set it, or what, but I know better now.

I am no longer setting resourceUri and my TreeView now looks good. Thanks for prompting me to revisit that assumption.

**Comment by jrieken** [comment]
@sandy081 I think that a fair feature request. There are other place in the UI that show a resource but not the decoration, e.g. editor tabs, debugging, or quick open. This also touches on https://github.com/Microsoft/vscode-references-view/issues/18 which is about showing the folder for a given resource. I think we should come up with an API like so:

```
enum TreeItemLabelRules {
  ShowDirectory,
  ShowDecorations,
  // more?
}
class TreeItem {
  labelRules: TreeItemLabelRules
}
```

**Comment by sandy081** [comment]
@jrieken I did not say it is invalid. I was checking with user the purpose of the request and he can overcome it or not. 

For your request of showing `directory` the right approach would be to

- introduce optional `description` property which behaves like `label`.

Have to think following when a resource URI is passed

- Give control to show description/folder or not?
- Is the default to show the description or not? 

If we do not want to show it by default, we have to introduce the rules as you suggested.

**Comment by sandy081** [comment]
@alexr00 Assigning to you as it is custom views related. Let me know if you need any info here.

**Comment by alexr00** [comment]
Marking as out of scope because, reasonable or not, I don't think we're going to make this change any time soon given the level of interest in it.
