### ISSUE TITLE
Some issues and suggestions for HTML

### ISSUE THREAD

**Issue by mahyar78** [Microsoft/vscode#62493]
Issue Type: <b>Bug</b>

Hi,
First of all let me thank you for your Awesome! IDE.
There are some features I've noticed when coding HTML on VSCode which I really want you to know so you can fix them to have more powerful IDE.
1 - When we edit a starter tag the end tag should edit simultaneously
2 - The tab key does not work sometimes for Emmet styling.(e.g:when you write .some-class and go back through the word to change it into .some-other-class and at the end when you come back to the end of the class defenition and press the tab key it does nothing.
3 - When wotking with many tags you may like to go to the starter tag from its end tag and vice-versa.its better to match the starter tags to end tags with a vertical line.
4 - On duplicating a line of code(I have not tested it on other languages) its indention is gonna loos despite of a setting "automatic format on pate" is On!

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     E7500  @ 2.93GHz (2 x 2933)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|4.00GB (1.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|2.5.1
ftp-sync|luk|0.3.3
HTMLHint|mka|0.5.0

</details>

**Comment by octref** [comment]
1. https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-rename-tag
2. You need to run `Emmet: Expand Abbreviation`. I don't think tab can be configured to work that way.
3. There is no such feature. What happens when they don't have the same indent?
4. That's right. You need to indent it manually. For example:

```html
<div>
</div>
```

If you duplicate the top line, the editor doesn't know what's your intention and can't indent correctly.

```html
<div>
<!-- Do you plan to close the 1st div here? -->
<div>
<!-- Do you plan to close the 2nd div here? -->
</div>
```
