### ISSUE TITLE
Emmet: Support class names like width-1/2

### ISSUE THREAD

**Issue by neeravp** [Microsoft/vscode#62491]
With the advent of utility first css frameworks like tachyon and tailwindcss, class names like `width-1/2` etc are very common now a days.   
Emmet doesn't seem to provide a filter for such names. However **PHPStorm** is already supporting the use of such class names in emmet
```emmet
div.width1/2.relative.p-4
```
expands to
```html
<div class="width-1/2 relative p-4"></div> 
```
in PHPStorm

Support for such class names via emmet is essential so to say in the world of utility first css frameworks.  

Please enable support for such class names via emmet in vscode as well.

**Comment by ramya-rao-a** [comment]
@neeravp We use https://github.com/emmetio/abbreviation to parse the emmet abbreviation. For us to support this case of `div.width1/2`, this module should support it which it doesnt.

Please log a feature request at https://github.com/emmetio/abbreviation for the same.
Once it is implemented there, we can absorb the changes here.

**Comment by neeravp** [comment]
Thanks @ramya-rao-a . I have logged an issue at https://github.com/emmetio/abbreviation/issues/10 as per your suggestion.
