### ISSUE TITLE
Improve error message for failed node debugging when node not installed

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode#62494]
Currently, this is the error when hitting f5 in a node app when you don't have node installed.

![image](https://user-images.githubusercontent.com/1186948/47929849-7d5d0700-de87-11e8-837e-767757755be3.png)

The error isn't very actionable and may not make sense to some people (and there's a typo: "on" should be "in"). I'd like to suggest something like 

>"Cannot find runtime 'node' in PATH. Make sure Node.js is installed correctly." 

and it would be awesome to add a "learn more" on best practices for installing node.

**Comment by roblourens** [comment]
I think "on the path" is correct.

**Comment by fiveisprime** [comment]
Thanks! I've never heard "on the path" before and I trust your experience. Thanks for pointing that out.
