### ISSUE TITLE
Color picker

### ISSUE THREAD

**Issue by Odonno** [Microsoft/vscode#625]
It could be great have a color picker to update color.
For example, when you have a CSS file like this : 

![capture](https://cloud.githubusercontent.com/assets/6053067/11398092/b4613d90-937e-11e5-8abe-1e44cd142265.PNG)

A color picker could be generated when you click on the colored element.

**Comment by wUFr** [comment]
+1 would save me from opening photoshop just to pick color

**Comment by TheColorRed** [comment]
+1 VSC would greatly benefit I think.

**Comment by dstorey** [comment]
F12, which is also based on Monaco and uses TypeScript has a colour picker, colour dropper, and colour palette in the styles panel (at least I think it also uses Monaco for that view)

![screen shot 2016-01-14 at 12 55 01 am](https://cloud.githubusercontent.com/assets/465069/12319821/acb25708-ba59-11e5-8ab2-72123ee19c85.png)

I wonder if this code can be shared?

**Comment by Odonno** [comment]
@dstorey Seems good !

**Comment by egamma** [comment]
@dstorey
>F12, which is also based on Monaco and uses TypeScript has a colour picker

F12 is using the Monaco editor when presenting source code. The DOM explorer from the Screenshot above is implemented in TypeScript but it is in a separate code base, which isn't OSS.

**Comment by mkoske** [comment]
Also, [Brackets](http://brackets.io) has colorpicker, which is nice.

**Comment by colonelchlorine** [comment]
+1 would be nice to have

**Comment by MandarSant** [comment]
@dstorey i think dreamweaver colorpicker is more Userfriendly [#15367](https://github.com/Microsoft/vscode/issues/15367#event-856371619)

**Comment by codeTrainingMine** [comment]
This has been open since 2015? Should be prioritised high as it's very basic functionality.

**Comment by anseki** [comment]
Exactly one year ago, I published [Color Picker extension](https://marketplace.visualstudio.com/items?itemName=anseki.vscode-color), but the installation seems to fail sometimes in some environments.
I'd be glad if you report something to my repository.

**Comment by erichiller** [comment]
If this was something that was available to extension developers, that would be great, then we could add it to other extensions as well.

**Comment by freMea** [comment]
[ColorHelper](https://github.com/facelessuser/ColorHelper) package for Sublime does a great straightforward job to pick/convert color. Other useful feature of this package:

- show all the colors of current file to easy pick an existing color
- allow favorites and palettes management
- picker changes according to rgb or hsl context
- allow saving, accessing, and managing colors in named color palettes all from the tooltip.

I wish to see those features in a color picker for Code.
Set your own color palette for a project would be a nice feature.

**Comment by sidati** [comment]
I suggest some like G-Chrome WebDev Tool Color Picker 😎

**Comment by freMea** [comment]
In the meantime, [Color Picker](https://marketplace.visualstudio.com/items?itemName=anseki.vscode-color) extension does a good job although you can not create your own palette to save the needed colors and easily reuse them.

**Comment by anseki** [comment]
@freMea, The Color Picker extension supports custom color palettes.

**Comment by freMea** [comment]
@anseki my bad. Thanks for the enlightening.

**Comment by ghiscoding** [comment]
This subject of a color picker, seem to have been referenced under a different issue #28587 in the insider June iteration plan

**Comment by lukaszpolowczyk** [comment]
It seems to me that the Brackets INLINE color picker is very good, especially because it is inline and quite comfortable way to call it. 
https://goo.gl/43qpz8

**Comment by michelkaporin** [comment]
@ghiscoding thanks for pointing to a different issue. 

Moving this discussion to #28587. I will keep updated on the progress on the color picker there.
