### ISSUE TITLE
Search pushes CPU usage for Antimalware Service Executable to around 80-90%

### ISSUE THREAD

**Issue by RaviSankarRao** [Microsoft/vscode#62509]
- VSCode Version: 1.28.2
- OS Version: Windows 10.0.17134 

Steps to Reproduce:

1. Click on Search in left nav
2. Enter search text
3. Press 'Enter'

Does this issue occur when all extensions are disabled?: Yes

![cpu hits 100 memory - 2](https://user-images.githubusercontent.com/12565630/47947013-df425e80-ded1-11e8-9652-e428b55a260d.PNG)

**Comment by roblourens** [comment]
Yes thanks
