### ISSUE TITLE
VSCode remote debugging doesn't map to local files properly

### ISSUE THREAD

**Issue by dejangeci** [Microsoft/vscode#62507]
Issue Type: <b>Bug</b>

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:20:56.183Z)
OS version: Linux x64 4.15.0-38-generic

Also reproduced on:
Win7 x64, VSCode 1.28.2, Docker Toolbox
Win10 x64, VSCode 1.28.2, Docker for Windows

[Minimal working example to reproduce](https://github.com/dejangeci/vscode-remote-debug-nodejs-issue)

Steps to Reproduce:

1. Build and run docker container with nodejs app
2. Attach to remote debugger
3. Set breakpoint
4. Trigger breakpoint

Expected: Original local file with breakpoint is shown
Actual: Read-only editor is shown with slightly different source

Does this issue occur when all extensions are disabled?: Yes

Tried using node and nodemon, adding trailing "/" to launch.json, different dirs inside docker. Same result every time.

![screenshot from 2018-11-02 22-12-04-crop](https://user-images.githubusercontent.com/1375514/47942140-30157f80-def1-11e8-99df-c0054cb5d5ce.png)

**Comment by weinand** [comment]
How does your launch.json look like?

**Comment by dejangeci** [comment]
It's included in the example project mentioned in the original post:
https://github.com/dejangeci/vscode-remote-debug-nodejs-issue/blob/master/.vscode/launch.json

**Comment by dejangeci** [comment]
console.log(__filename) reports "/home/node/app/src/index.js"

![image](https://user-images.githubusercontent.com/1375514/48015401-5f163600-e129-11e8-9dc8-389fd736f7b6.png)

**Comment by timothyallan** [comment]
I'm encountering this as well with a similar setup on MacOS after months of flawless debugging ... and it only started with node v10.12. I see you're using node:10.12.0-alpine

If you change your Dockerfile to use node v10.11, does it magically start to work like mine does?

**Comment by dejangeci** [comment]
Fixed in 1.29 with #62354, cannot reproduce anymore.

In 1.28.2, Node >= 10.12 (including 11) issue was reproducible.
