### ISSUE TITLE
Font rendering issues in Ubuntu 18.10

### ISSUE THREAD

**Issue by exah-io** [Microsoft/vscode#62501]
**Version:** 1.28.2 (snap)
**OS:** Ubuntu 18.10 (ubuntu-restricted-extras package is installed)
**Extensions:** solidity, One Monokai Theme
**Does this issue occur when all extensions are disabled?** Yes

**Issue:**
The fonts seem very thin in the code editor in Ubuntu 18.10. Didn't face this issue while in 18.04.
I've been trying to switch to other fonts, but can't seem to get a better result.

![vscode](https://user-images.githubusercontent.com/3874515/47935678-27ae4c00-ded3-11e8-8e71-bb2d3fe192ee.png)

**Comment by graph** [comment]
When I edit my files the text wiggles sometimes. I don't know if it's related to this. I have all my font settings to bold as the non-bold is too thin.

**Comment by pipegreyback** [comment]
I am having the same issue. If you use a bigger font size you kinda get a better result, but comments still looking ugly.
![screenshot from 2018-11-03 19-57-01](https://user-images.githubusercontent.com/13972706/47958097-c5bd1780-dfa2-11e8-8104-e7e06fd2381d.png)

**Comment by kieferrm** [comment]
There are reports about font issues on 18.10 in general. Some claim it only happens when the update to 18.10 and not in a clean install. We'll keep tracking the issue but it's unclear if there's anything we can do.

**Comment by gnarum** [comment]
Thanks for the reply @kieferrm. I did a clean install though.

According to launchpad both Ubuntu 18.04 and 18.10 have the same freetype version (https://launchpad.net/ubuntu/+source/freetype).

I'll see what I can find upstream.

**Comment by lzantal** [comment]
Hi there,

Same issue on Mac Mojave. Thin and blurry font.
Only happened after I updated to the latest version this morning.
I tried every setting available but can't fix it. First I thought it might the antialiasing but doesn't matter what I change it to it stays the same.

**Comment by graph** [comment]
I hear Mojave is having blurry fonts everywhere including xcode. @izantal it will be good if you can compare the same font and size in xcode to see if it's just as blurry.

**Comment by lzantal** [comment]
@graph Xcode looks fine. I wasn't even thinking that might be due to electron so I am going to try some of those overwrites. However my MacBook has retina screen and the fixes out there for monitors without Retina display.

**Comment by kieferrm** [comment]
The Mojave issue is different from the Ubuntu issue. See 
https://code.visualstudio.com/docs/supporting/faq#_blurriness-on-macos-mojave.

**Comment by osamaq** [comment]
On Ubuntu 18.10, uninstalling the snap package and installing the deb package seems to resolve the issue for me.

**Comment by pipegreyback** [comment]
@osamaq Thanks! Your workaround also worked for me.

**Comment by lzantal** [comment]
@kieferrm just tried that and it's still looks the same blurry. Found the same workaround in other places too but it's not working for some reason.

**Comment by lzantal** [comment]
Ok it is all good now thanks @kieferrm I had a hunch and did a full shutdown and once it turned back on now it looks better. Not the same as it was before but I can't complain.

**Comment by ozra** [comment]
I've used atom then and when since at least 2015, and electron has had blurry font rendering since then, all the way using Ubuntu, updating every release. Since VSC is using the same foundation as Atom (?) I assume the same problem holds. I just can't find no way around it. In Howl and Sublime I can use my raster-fonts that are perfectly sculpted for coding without any anti-alias, but also if using anti-aliased vector-based fonts it looks a million times sharper than both VSC and Atom. _It's a real strain on the eyes, akin to a health hazard_ :-(

**Comment by bpasero** [comment]
@exah-io 
We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/45498d93166483c2eff886e28f8dab915ae382fc/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/code-exploration_1.28.0-1538127308_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/VSCodeUserSetup-x64-1.28.0-exploration.exe)
