### ISSUE TITLE
multiple references, same line

### ISSUE THREAD

**Issue by rakkarage** [Microsoft/vscode#6251]
![2016-05-10 1](https://cloud.githubusercontent.com/assets/962340/15151508/62bc19ac-169f-11e6-80c5-b4e704da5161.png)

when multiple references on same line...
idk looks kinda cluttered and does not line up...
i appreciate that it even works at all and remember when it did not.
but if if showed only the number when multiple they would at least line up
but that would look bad and be hard to click
not an issue, a design decision with no better alternative?
(maybe outline color of variable based on how many references it has: 0 no outline, 255+ ref brightest outline, click on variable itself for list)
idk
thanks

**Comment by jrieken** [comment]
> but if if showed only the number when multiple they would at least line up

Hard. what is printed there depends on the extension, it's not always a number but can be any string, see [version lens](https://marketplace.visualstudio.com/items?itemName=pflannery.vscode-versionlens) or [code metrics](https://marketplace.visualstudio.com/items?itemName=kisstkondoros.vscode-codemetrics).

**Comment by jrieken** [comment]
@bgashler1 @stevencl ideas?

**Comment by stevencl** [comment]
My first reaction is that perhaps we shouldn't be showing all these indicators all the time and perhaps we should only make indicators visible for a field that is selected? Consider also the case when there could be more than one indicator for the field (references, change history, etc).

For example, imagine selecting the symbol and seeing something like this:

![image](https://cloud.githubusercontent.com/assets/1704059/15217278/b6a7b472-1852-11e6-9a76-607b3541cd37.png)

**Comment by jrieken** [comment]
unsure how that would word for things that aren't single line/word, like so when showing function metrics:

<img width="291" alt="screen shot 2016-05-12 at 17 53 12" src="https://cloud.githubusercontent.com/assets/1794099/15221130/75cd7122-186a-11e6-9f3f-da00bcab3eb1.png">

**Comment by stevencl** [comment]
There is an extension for VS that shows code metrics like so:

![image](https://cloud.githubusercontent.com/assets/1704059/15222922/c306048c-1869-11e6-98f3-98d97d18b524.png)

**Comment by jrieken** [comment]
And the lens shows because I am in the body of `Start` or always?

**Comment by stevencl** [comment]
Those particular indicators show always because they are on the method signature.

**Comment by jrieken** [comment]
yeah, challenge for us is that extensions are free to put lenses anywhere. most are nice and use method/functions scope but anything is possible - as C# does with lenses on enum elements. Maybe we should talk to them about this...

**Comment by bgashler1** [comment]
I like the overlay or lens instead of putting it in the editor as if it was part of the user's code.  That way we distinguish it from what can be selected or edited (the code) and what is supplemental information.

**Comment by bgashler1** [comment]
Do users need to see these references all the time or just for what's in scope based on their selection?  I think they would only need to see it for what's in scope of where they are, and thus I like what @stevencl suggested about minimizing the clutter of these pieces of information (seems the most scalable).

One thought, is putting this inline annotation necessary?  I know it's not part of the code, but a subconscious part of us might feel anxiety that we may inadvertently select this information because it's inline with the code.  Perhaps a hover event over signatures and variables could show everything with no annotations...
![image](https://cloud.githubusercontent.com/assets/11839736/15256786/f9dbca1c-18f7-11e6-951a-1a138ee0759a.png)

**Comment by jrieken** [comment]
Closing this as-designed as we can't control how many lenses one or many extensions add. It's always up to the user to enable code lenses (`"editor.codeLens": true|false`)

**Comment by stevencl** [comment]
But can you control when a lens is shown? For example, we could consider not showing lenses automatically inside an enum, but only show them for a field that is selected? For example, VS doesn't show lenses inside the enum:

![image](https://cloud.githubusercontent.com/assets/1704059/18878014/02729206-84c7-11e6-8878-5abdc0b9a9cf.png)

**Comment by jrieken** [comment]
That is under the control of the OmniSharp extension - I don't see us expressing that in a generic way

**Comment by stevencl** [comment]
I see, so this bug/suggestion should really go to OmniSharp then?
