### ISSUE TITLE
(css) change device-width tag highlighting color

### ISSUE THREAD

**Issue by Fleta** [microsoft/vscode#62515]
![screenshot](https://i.imgur.com/C7tMdEp.png)

This highlighting color seems like `min-device-width` tag is syntax error.
I think this change in highlighting will help readability.

Thanks.

**Comment by octref** [comment]
@alexr00 This is because we had the wrong CSON -> JSON conversion in grammar. Therefore multiline rules aren't converted correctly. For example:

```
			"match": "(?xi)\n(?<=^|\\s|\\(|\\*/)           # Preceded by whitespace, bracket or comment\n(?:\n  # Standardised features\n  (\n    (?:min-|max-)?            # Range features\n    (?: height\n      | width\n      | aspect-ratio\n      | color\n      | color-index\n      | monochrome\n      | resolution\n    )\n    | grid                    # Discrete features\n    | scan\n    | orientation\n    | display-mode\n  )\n  |\n  # Deprecated features\n  (\n    (?:min-|max-)?            # Deprecated in Media Queries 4\n    device-\n    (?: height\n      | width\n      | aspect-ratio\n    )\n  )\n  |\n  # Vendor extensions\n  (\n    (?:\n      # Spec-compliant syntax\n      [-_]\n      (?: webkit              # Webkit/Blink\n        | apple|khtml         # Webkit aliases\n        | epub                # ePub3\n        | moz                 # Gecko\n        | ms                  # Microsoft\n        | o                   # Presto (pre-Opera 15)\n        | xv|ah|rim|atsc|     # Less common vendors\n          hp|tc|wap|ro\n      )\n      |\n      # Non-standard prefixes\n      (?: mso                 # Microsoft Office\n        | prince              # YesLogic\n      )\n    )\n    -\n    [\\w-]+                   # Feature name\n    (?=                       # Terminates correctly\n      \\s*                    # Possible whitespace\n      (?:                     # Possible injected comment\n        /\\*\n        (?:[^*]|\\*[^/])*\n        \\*/\n      )?\n      \\s*\n      [:)]                    # Ends with a colon or closed bracket\n    )\n  )\n)\n(?=\\s|$|[><:=]|\\)|/\\*)     # Terminates cleanly"
```

Is incorrectly converted from https://github.com/atom/language-css/blob/master/grammars/css.cson#L1202-L1267

Is there anyway to might fix that conversion?

**Comment by alexr00** [comment]
We might be able to come up with a regex replacement to remove those comments in strings, but I'm not even sure if comments are allowed in strings like that in cson (our coffeescript) grammar doesn't think they are allowed). There are legit strings in there like 'include': '#comment-block'. How are those distinguishable from those comments?

**Comment by octref** [comment]
@alexr00 Yeah, I tried it yesterday and there wasn't a straightforward way to convert them programatically.
Also I have no idea how to remove the whitespaces precisely. Some of them might be used for regex and some aren't.

**Comment by octref** [comment]
@alexr00 Sorry for my misunderstanding. After chatting with @mjbvz, I learned that the leading [`x` mode in Ruby regex](https://ruby-doc.org/core-2.4.1/Regexp.html#class-Regexp-label-Free-Spacing+Mode+and+Comments) handles comments and whitespaces. The grammar itself marked the properties as `"name": "invalid.deprecated.media.css"`. So it's a grammar issue.

However, Sublime's guidance states:

![image](https://user-images.githubusercontent.com/4033249/67341951-d6cda400-f4e5-11e9-80a4-7b383628f2c6.png)

I created an upstream issue https://github.com/atom/language-css/issues/163.

**Comment by alexr00** [comment]
I didn't know about the leading x mode, thanks for the info!

**Comment by octref** [comment]
@alexr00 I updated grammar at octref/language-css and you can pull latest grammar form octref/language-css. I also sent an upstream PR, but that's pending review.

**Comment by alexr00** [comment]
Will do for November!

**Comment by aeschli** [comment]
Marking as fixed
