### ISSUE TITLE
VSCode locks .asar files, preventing Electron app release (Duplicate of closed issue https://github.com/Microsoft/vscode/issues/13076)

### ISSUE THREAD

**Issue by drk-mtr** [Microsoft/vscode#62518]
Issue Type: <b>Bug</b>

I am trying to work on an Electron app. As part of the process to create an executable file, the 'Electron Packager' creates .asar files within a 'release' directory under the root of the solution. This gets overwritten when doing a new release.

When I try to do a new release, this `app.asar` file can't be overwritten as it's locked by VS Code (confirmed in Resource Monitor > Application Handles).

I can't work out whether it's VS Code that is doing this or an extension, so if it's an extension apologies for filing this bug report!

I have tried this with extensions switched off (i.e. `code --disable-extensions`) and it does work, however I don't know whether this is conclusive proof it's an extension because the .asar locking happens inconsistently i.e. if I start VS Code with extensions enabled, the error doesn't occur if I try a release immediately.

It appears this has been raised before: https://github.com/Microsoft/vscode/issues/13076

Apparently this is fixed, so maybe I'm wrong about what's going on here. Does anyone know whether there's any way to force VS code to ignore the existence of these files, or troubleshooting I could try to better prove whether it's an extension or not?

I have tried adding this `release` directory to the `files.exclude` list in Workspace Settings and this does seem to help - I've just run the release process 3 times without any file locking. Does anyone know whether this `files.exclude` setting impacts extensions too, as this might help point us in the right direction?

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (9.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
project-manager|ale|9.0.1
vscode-sqlite|ale|0.3.1
ng-template|Ang|0.1.10
jshintrc-generator|ben|1.0.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.7.0
githistory|don|0.4.3
vscode-pandoc|Dou|0.0.8
vscode-npm-script|eg2|0.3.5
git-project-manager|fel|1.7.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
dotnet|for|0.0.4
graphviz-markdown-preview|gee|0.0.7
status-bar-tasks|Gua|0.3.0
rest-client|hum|0.20.3
Ionide-FAKE|Ion|1.2.3
Ionide-fsharp|Ion|3.29.0
Ionide-Paket|Ion|1.12.0
csharpextensions|jch|1.3.0
nuget-reverse-package-search|jes|0.1.68
vscode-redux-devtools|jin|0.0.11
Angular2|joh|6.3.0
vscode-csharp-snippets|jor|0.3.1
csharpfixformat|Leo|0.0.76
expand-region|let|0.1.2
Angular-BeastCode|Mik|7.0.13
theme-monokai-pro-vscode|mon|1.1.8
csharp|ms-|1.17.0
node-debug2|ms-|1.29.5
PowerShell|ms-|1.9.0
debugger-for-chrome|msj|4.10.2
refsharp|mtn|0.9.2
vscode-versionlens|pfl|0.22.0
vscode-yaml|red|0.0.17
live-sass|rit|3.0.0
LiveServer|rit|5.1.1
vscode-icons|rob|7.28.0
sass-indented|rob|1.4.9
aspnet-helper|sch|0.6.4
vscode-table-formatter|shu|1.2.1
autoimport|ste|1.5.3
dot|Ste|0.0.1
vscode-todo-highlight|way|1.0.4

(8 theme extensions excluded)

</details>

**Comment by kieferrm** [comment]
@drk-mtr extensions should conform to the `file.excludes` setting if it makes sense for their use case. Not quite sure how to help you hear. You could test extensions one-by-one but since you have a long list, this is quite a chore.

**Comment by chrmarti** [comment]
@drk-mtr You could:
- Restart VS Code.
- Check that the file is not locked yet.
- Run 'Developer: Show Running Extensions' command.
- Screenshot the list of activated extensions.
- Do something that makes the file become locked.
- Compare the list of now running extensions with the previous.

That might help track the extension causing it down. (Note that just because an extension was already activated when the file was not locked yet doesn't necessarily mean that it didn't cause the lock later on.)
