### ISSUE TITLE
CPU usage up to 90% + 

### ISSUE THREAD

**Issue by ACERY1** [Microsoft/vscode#62511]
here is the snapshot：

<img width="833" alt="image" src="https://user-images.githubusercontent.com/19555547/47947563-e6ad4a80-df59-11e8-900e-bba4fefc704e.png">

**Comment by ACERY1** [comment]
I open a file like '.xxx.js'， and typingsinstaller.js goes to 100% cpu usage.

**Comment by graph** [comment]
`code --status`

```

Version:          Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:20:56.183Z)
OS Version:       Linux x64 4.15.0-36-generic
CPUs:             Intel(R) Core(TM) i7-2760QM CPU @ 2.40GHz (4 x 3189)
Memory (System):  7.68GB (0.14GB free)
Load (avg):       1, 1, 0
VM:               0%
Screen Reader:    no
Process Argv:     --open-url
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    disabled_software
                  rasterization:                disabled_software
                  video_decode:                 unavailable_software
                  video_encode:                 unavailable_software
                  webgl:                        enabled
                  webgl2:                       enabled

CPU %	Mem MB	   PID	Process
    1	    94	  5435	code main
    0	    16	  5439	   zygote
   46	   338	  5629	     window (resolve.py - depender - Visual Studio Code)
    0	    55	  5680	       extensionHost
    0	    47	 12864	         /usr/share/code/code /usr/share/code/resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=5680
    0	    24	  5686	       watcherService
    0	     0	 28711	       /bin/bash
    0	   102	  5641	     shared-process
    0	   212	 29405	     window (csearchd.cpp - csearch - Visual Studio Code)
    0	     0	 29426	       /bin/bash
    0	    94	 29436	       extensionHost
    0	   189	 29477	         /home/blue/.vscode/extensions/ms-vscode.cpptools-0.20.0/bin/Microsoft.VSCode.CPP.Extension.linux
    0	   652	 29442	       watcherService
    0	   149	  5473	   gpu-process

Workspace Stats:
|  Window (csearchd.cpp - csearch - Visual Studio Code)
|  Window (resolve.py - depender - Visual Studio Code)
|    Folder (depender): 4 files
|      File types: py(4)
|      Conf files:
|    Folder (csearch): more than 43700 files
|      File types: hpp(28703) cpp(6137) html(2449) qbk(1015) ipp(530) h(396)
|                  js(390) v2(342) py(288) c(239)
|      Conf files: cmake(54) makefile(32) sln(16) settings.json(1)
|                  launch.json(1) tasks.json(1)
|      Launch Configs: cppdbg(3)

```

vs code froze with high cpu when I ran the command.

**Comment by ACERY1** [comment]
what I did was changing the file’s name，prevent to use ' .xx.js '.

**Comment by kieferrm** [comment]
https://github.com/Microsoft/vscode/issues/62511#issuecomment-435562136 is unrelated to this issue as it shows the renderer process being active.

**Comment by mjbvz** [comment]
@ACERY1  Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by ACERY1** [comment]
> @ACERY1 Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

Sure，I close all of the extensions when I took that snapshot.

**Comment by mjbvz** [comment]
Can you also please try upgrading your workspace to use `typescript@next` by following [these instructions](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions). We've made some fixes upstream for file watching issues that could be causing cpus spikes like that.

If you still see the problem after upgrading, try collecting the TS Server log:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a folder with a `ti-xxx.log` file in it

If you can share that typings installer log file, I can take a look to see what may be going wrong

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this
