### ISSUE TITLE
Emoji completion in markdown

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#62513]
We can offer it behind a setting so people can disable it.

![image](https://user-images.githubusercontent.com/4033249/47948411-0b6bd880-deee-11e8-8070-bcac298babac.png)

I don't know if this should go in markdown core or the markdown emoji extension, though.

Rough implementation is in this branch: https://github.com/Microsoft/vscode/tree/markdown-emoji-completion.

**Comment by mjbvz** [comment]
Try this extension: https://marketplace.visualstudio.com/items?itemName=bierner.emojisense

Not in favor of adding this to core
