### ISSUE TITLE
vscode don't goto source in python code

### ISSUE THREAD

**Issue by lotapp** [Microsoft/vscode#62510]
- VSCode Version:1.28.2
- OS Version:Ubuntu 18.04

eg: goto sendto source
```py
import socket

def main():
    with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as udp_sock:
        udp_sock.sendto("大兄弟，你好啊".encode("utf-8"), ("192.168.36.235", 8080))
    print("over")

if __name__ == '__main__':
    main()
```
not only in this demo，I like to use vscode, but this bug has to switch to other IDEs often.

hope fix the bug，thanks ---from china friend

**Comment by kieferrm** [comment]
@lotapp please file the issue against the Python extension here 
https://github.com/Microsoft/vscode-python/issues. Thanks!
