### ISSUE TITLE
OutputChannel.hide doesn't hide the window(?)

### ISSUE THREAD

**Issue by evmar** [Microsoft/vscode#6252]
- VSCode Version: 1.0.0
- OS Version: Ubuntu Linux

If you put this code in an extension:

``` js
  let proc = child_process.spawn('ls');
  let outputWindow = vscode.window.createOutputChannel('ls');
  outputWindow.clear();
  function onOutput(data) { outputWindow.append(data.toString()); }
  proc.stdout.on('data', onOutput);
  proc.stderr.on('data', onOutput);
  proc.on('exit', code => {
    outputWindow.append('exit');
    outputWindow.hide();  // ***
  });
```

Then you see the "ls" output and the "exit" message, but the call to `hide()` doesn't seem to hide the window.

**Comment by isidorn** [comment]
The problem here is that the append shows the output channel and all these call are async so the hide() actually gets exectued before the append().
@jrieken do we have some recommendation on how to use the API here?

**Comment by jrieken** [comment]
> async so the hide() actually gets exectued before the append().

@isidorn Unsure where that happens? The calls made in `ExtHostOutputService` shouldn't in order despite being async.

**Comment by isidorn** [comment]
@jrieken It might be our output append delayer to prevent spamming the output 
https://github.com/Microsoft/vscode/blob/ben/stacks/src/vs/workbench/parts/output/common/outputEditorInput.ts#L26

So he schedules to append and show output in 300ms, in the meantime the output gets hidden

**Comment by jrieken** [comment]
I'd say so. Either _hide_ goes into the same queue or (better) it set's a flag that append et al don't reveal the view anymore.

**Comment by martine** [comment]
Ah, that delay you linked to explains so much!  I really feel it when running a subprocess that has a lot of output -- vscode looks like it's struggling to keep up because the output is all jerky.  It would be nice if you instead capped the output at something closer to a frame rate (like 30ms ~= 30fps), which is still a huge delay from the computer's perspective.

If there was a way to get an async callback that happens after the append that would be fine too:
```js
outputWindow.append('exit', () => { outputWindow.hide(); });
```

**Comment by jrieken** [comment]
We are trying to hide the fact that stuff runs async (and on another process) so low chances for the callback. It's an implementation detail that we should get right ;-) 

I like the idea of a shorter timeout but we also saw perf issues with tons of output. Isi will know.

**Comment by isidorn** [comment]
@sandy081 do we still use a delayer with the new output rewrite for appending to the model?

**Comment by sandy081** [comment]
@isidorn with new re-write, appending a message will writes into the backup file and also writes into the output model if exists. Append will never show the channel (which I assume also same before). 
So Append and Hide calls will not have race condition.

**Comment by isidorn** [comment]
@evmar this should be fixed in latest vscode inisders, can you please try it there https://code.visualstudio.com/insiders/
