### ISSUE TITLE
Docs for formatOnSave are unclear

### ISSUE THREAD

**Issue by tlent** [Microsoft/vscode#62526]
- VSCode Version: 
Version: 1.29.0-insider
Commit: d43f6cb9947c57a3254b556e69aeacc2b2025184
Date: 2018-11-02T15:56:43.302Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
(Also occurring on my non-insiders 1.28.2 install)

- OS Version: 4.18.16-arch1-1-ARCH

Steps to Reproduce:

1. Set settings.json to: ```
{
    "files.autoSave": "onFocusChange",
    "editor.formatOnSave": true
}``` 
2. Install the prettier extension
3. Open a javascript file and edit it in a way that will change when formatted
4. Switch focus to another window

The file will auto save as expected, but it also formats. Based on the description of the `editor.formatOnSave` setting which says "the file must not be auto-saved" I would expect the file not to be formatted after this save.

The same issue happens when `"files.autoSave": "onWindowChange"` is set. When `"file.autoSave": "afterDelay"` is set it works as expected (saves without format).

I also tested using the Rust (rls) extension to format a Rust file and the same issue occurred.

I prefer to auto save on focus change but I do not want the file formatted unless I manually save. The description of `editor.formatOnSave`  leads me to believe that with these two settings I will get that behavior but I do not. Either the behavior should be changed to only format on a manual save (which I believe is the intended behavior) or the description should be changed to clarify that the file must not be auto saved after delay (if that is actually the intended behavior).

Does this issue occur when all extensions are disabled?: N/A because the issue depends on a formatting extension being installed. It does occur when all extensions other than prettier are disabled.

**Comment by jrieken** [comment]
> The same issue happens when "files.autoSave": "onWindowChange" is set. When "file.autoSave": "afterDelay" is set it works as expected (saves without format).

It works as designed but I agree that the doc is unclear. Format on save will not happen when auto save is configured to happen after a delay but it will happen when focus out happens.
