### ISSUE TITLE
Add project level snippets support for .tsx and .jsx files

### ISSUE THREAD

**Issue by trueshuka** [Microsoft/vscode#62521]
Snippets should show up in .tsx or .jsx files if you have the corresponding language in `scope` field.

Here's my `.code-snippets` file :
`
{
 "isc": {
    "prefix": "isc",
    "body": "import styled from 'styled-component'",
    "description": "Imports styled from styled-components",
    "scope": "javascript, typescript"
  }
}
`

And `isc` isn't showing up
![v](https://user-images.githubusercontent.com/30146228/47955487-ab8f3380-dfba-11e8-8133-9574345f3336.png)

But it does, if I change the extension to .ts
![a](https://user-images.githubusercontent.com/30146228/47955497-d9747800-dfba-11e8-9dd2-96f020057877.png)

**Comment by mjbvz** [comment]
Try using the `javascriptreact` and `typescriptreact` scopes for `jsx` and `tsx` respectively. These are treated as separate languages for legacy reasons
