### ISSUE TITLE
Context menu actions invoke multiple times (7x update message)

### ISSUE THREAD

**Issue by samuela** [Microsoft/vscode#62524]
- VSCode Version: Version 1.29.0-insider (1.29.0-insider) d43f6cb9947c57a3254b556e69aeacc2b2025184
- OS Version: macOS 10.14

Steps to Reproduce:
https://imgur.com/a/ySuCW8g

This seems to go away after reloading the window, but when it happens it is repeatable.

Does this issue occur when all extensions are disabled?: Pretty sure, but can't be certain. Reloads usually make it go away.

**Comment by joaomoreno** [comment]
It is always 7? Do you have other windows open?

**Comment by samuela** [comment]
@joaomoreno Not always, I've found that it varies. I don't think I had any other VSCode windows open at the time.

**Comment by samuela** [comment]
I just came across the same thing in 5f24c93878bd4bc645a4a17c620e2487b11005f9 as well. Although this time I did notice that it happened after the window crashed and I was prompted to "reload" which I did. Perhaps these UI events are still being sent/received by zombie versions of the UI? That would explain why different numbers of repetitions can be observed in different sessions. I have been seeing an alarming number of "this window is not responding. would you like to reload?" dialogs on Insiders in the past week or two.

**Comment by Astrantia** [comment]
I can confirm this is an issue https://github.com/Microsoft/vscode/issues/62820

**Comment by joaomoreno** [comment]
@alexandrudima Any clue? @Astrantia also gets this simply by opening a new window using a keybinding.

**Comment by warrenrumak** [comment]
I'm seeing something very similar, but not in all VS Code instances.

Many dialog boxes will show several times in a row.... even "About".

**Comment by joaomoreno** [comment]
![image](https://user-images.githubusercontent.com/22350/48536085-c3fe2880-e8ad-11e8-8fe1-21f079225271.png)

**Comment by joaomoreno** [comment]
cc @Microsoft/vscode in case someone has any clues

**Comment by sbatten** [comment]
I saw this duplicate behavior one time when working with the PR extension. I thought it was related to the extension so @RMacfarlane and I spent quite a while trying to reproduce it to no avail.

**Comment by Astrantia** [comment]
@sbatten I didn't have PR extension installed when this happened to me.

**Comment by sbatten** [comment]
@Astrantia yes, based on the reports in this thread, the PR extension does not seem to be the culprit but a victim to this issue

**Comment by samuela** [comment]
@bpasero Yes, eg deleting a file confirmation dialog.

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/45498d93166483c2eff886e28f8dab915ae382fc/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/code-exploration_1.28.0-1538127308_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/VSCodeUserSetup-x64-1.28.0-exploration.exe)

**Comment by joaomoreno** [comment]
@samuela ping

**Comment by samuela** [comment]
Hey @joaomoreno, I haven't had a chance to switch to use exploration builds yet. (It's just annoying to re-set up all of my extensions and everything.) But I haven't been seeing this issue recently. That said, I also haven't had any "this window has frozen. would you like to reload?" dialogs recently so it's entirely possible that the bug still exists but is not being triggered as readily.

**Comment by bpasero** [comment]
Any update in todays insider build?

**Comment by samuela** [comment]
@bpasero I'll update and check it out!

**Comment by bpasero** [comment]
Thanks

**Comment by bpasero** [comment]
People that got this, did you see a dialog asking to reload the window because it either has crashed or is unresponsive? Asking because we have a repro here: https://github.com/Microsoft/vscode/issues/65959

**Comment by samuela** [comment]
@bpasero yes, cf some of my previous comments for details
