### ISSUE TITLE
ubuntu vs code can't install anyextension

### ISSUE THREAD

**Issue by zongka** [microsoft/vscode#62520]
the ubuntu version is 16.04
i'm new user of vs code, and i find it difficult to install extensions. 
if i just use the vscode to download the extension, it will happen "failed to download xxx-xxx-xxx"
and i also try to install the extensions manually, it will happen "eacces:permission denied.mkdir"/home/xxx/.vscode/extentions/xxxxx""
btw, i'm confused the relationship between vscode and anaconda, i can open the vscode inside the anaconda

**Comment by kieferrm** [comment]
@zongka did you get VS Code through anaconda or did you install it via a download from code.visualstudio.com? If you got it through anaconda, can you please try to install from our website? Also, what are the permissions on the  directory `/home/xxx/.vscode/extentions/`?

**Comment by zongka** [comment]
> @zongka did you get VS Code through anaconda or did you install it via a download from code.visualstudio.com? If you got it through anaconda, can you please try to install from our website? Also, what are the permissions on the directory `/home/xxx/.vscode/extentions/`?

i already fix the problem,  the main teason is i don't have the permissiton on /home/xxx/.vscode/extentions/, and i just fix it by changing the folder permission to 777
