### ISSUE TITLE
VSCode extension F5 debug behavior is different with the extension is published

### ISSUE THREAD

**Issue by plantain-00** [Microsoft/vscode#62539]
- VSCode Version: 1.28.2 and 1.29.0-insider
- OS Version: 10.12.6 (16G1510)

Steps to Reproduce:

1. Open the VSCode extension project(yarn && yarn build) and press F5 to start: https://github.com/plantain-00/vscode-type-coverage
2. Open a directory: https://github.com/plantain-00/type-coverage
3. After a few seconds, it shows 13 problems
4. Stop debug, open the same directory, install the extension: https://marketplace.visualstudio.com/items?itemName=york-yao.vscode-type-coverage 
5. After a few seconds, it shows 33 problems

Does this issue occur when all extensions are disabled?: Yes and No

![2018-11-04 15 17 25](https://user-images.githubusercontent.com/7639395/47961529-b7750700-e047-11e8-9635-8e8581a5cabf.png)
![2018-11-04 15 18 31](https://user-images.githubusercontent.com/7639395/47961530-b7750700-e047-11e8-9ad3-fd2ca6061073.png)
![2018-11-04 15 28 17](https://user-images.githubusercontent.com/7639395/47961531-b7750700-e047-11e8-9cbf-c95ea1cc745a.png)
![2018-11-04 15 30 02](https://user-images.githubusercontent.com/7639395/47961532-b80d9d80-e047-11e8-93f0-2ee7ba96bfc4.png)

**Comment by weinand** [comment]
What are the differences between 13 and the 33 problems?
Do you see a pattern?

**Comment by plantain-00** [comment]
The 20 new problems have these patterns:
1. for...of
```ts
    for (const node of nodes) { // the nodes is ts.NodeArray<ts.Node>, but the node is any
      handleNode(node, file, sourceFile)
    }
```
2. sourceFile.forEachChild
```ts
      sourceFile.forEachChild(node => { // sourceFile is ts.SourceFile, but the node is any
        handleNode(node, file, sourceFile)
      })
```
3. instanceof
```ts
if (error instanceof Error) {
    console.log(error.message) // error.message should be string, but is any
  }
```
4. Array.map
```ts
rootNames.map((r) => path.resolve(process.cwd(), dirname, r)) // r is any
```
5. Promise
```ts
new Promise<fs.Stats | undefined>((resolve) => { // resolve is any
```
It seems the 20 problems are all typescript related.

Days ago, I checked maybe `process.cwd()` caused this, but they are all `/`.

**Comment by weinand** [comment]
Sorry, but this looks like a problem with your extension.

**Comment by plantain-00** [comment]
Can you provide a link about the difference between F5 debug and run as an extension?

**Comment by weinand** [comment]
The only difference is that with F5 the underlying node.js runtime in in debug mode.

I still do not understand what errors are reported. Please provide at least screenshots of the problems view in the two setups.
