### ISSUE TITLE
macOS Mojave: VSCode keeps adding lots of duplicate icons to the right side of my Dock

### ISSUE THREAD

**Issue by ndbroadbent** [Microsoft/vscode#62536]
- VSCode Version: 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850)
- OS Version: MacOS Mojave (10.14)

I keep right clicking the icons and choosing "Remove from Dock", but they keep coming back at a rate of around 1 per day. It's really, really annoying. Is this something to do with automatic updates?

<img width="242" alt="screen shot 2018-11-04 at 1 58 52 pm" src="https://user-images.githubusercontent.com/139536/47961258-25b2cd00-e03a-11e8-9bea-e188e0aeba54.png">

**Comment by ndbroadbent** [comment]
Ah, MacOS Mojave has started adding "Recent Applications" to the dock. [Here's an article that show how you can turn off that feature.](https://www.tekrevue.com/tip/recent-applications-extra-icons-mojave-dock/)

However, it seems like a useful feature so I want to keep using it, and it would be great if VS Code could do something to prevent the duplicate icons. My hunch is that this is because VS Code has automatic updates, so the application is changing and MacOS sees a new "fingerprint" (maybe a different signature or hash). This is why it's adding a new icon to the recent applications, even though they all point to the same application.

Would it be possible to open a support ticket with Apple to resolve this issue? Or maybe they have some documentation about how this can be prevented. 

Thanks!

**Comment by csantanapr** [comment]
This is very very annoying, have being going crazy the last couple of days.
I cleaned up all icons from Dock, but every time I type `code .` in my terminal it add a new icon up to 3 plus the one that is pinned

![image](https://user-images.githubusercontent.com/1094878/48161634-0a012e00-e2a9-11e8-8b9c-3769fa602fd3.png)
