### ISSUE TITLE
Cannot start  VSCode without network

### ISSUE THREAD

**Issue by JoeZhouYH** [Microsoft/vscode#62535]
Issue Type: <b>Bug</b>

1.disconnect network
2.run "Code" in command line
3.It will show:
dns.js:246
    this._handle = new ChannelWrap();
                   ^

Error: EFILE
    at new Resolver (dns.js:246:20)
    at dns.js:377:25
    at dns.js:431:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at net.js:45:13
    at net.js:1730:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at internal/child_process.js:6:13

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|7.89GB (2.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.28.2

</details>

**Comment by JoeZhouYH** [comment]
似乎没有官方的解决方案，但参考#7570，里面有人给出了一种避免问题的方式：
https://docs.microsoft.com/en-us/previous-versions/tn-archive/cc708322(v=ws.10)

microsoft loopback adapter
就是安装在本机上的一块虚拟网卡，它跟本机上的其它物理网卡、和物理网卡连接的网络是没有关系的，你可以理解成这块网卡上的网线接到了另外一个空白网络。

它的作用仅仅是用来给那些需要本机配置有网络的服务程序调试用，它不能与实体网络进行通信。

举个最简单的例子，你的电脑没有网卡，想给本机安装WINDOWS的DNS服务试着玩，但DNS服务在启动时若检测到本机没有网络会报错停止，这时你安装块loopback adapter网卡就有用了。

**Comment by kieferrm** [comment]
This is fixed in electron 3.0 and we're working on adopting 3.0.

**Comment by JoeZhouYH** [comment]
@kieferrm Thanks.By referring to issue #7570, I have known what's going on about this problem.It will be thankful you fix it.
