### ISSUE TITLE
Missing button images

### ISSUE THREAD

**Issue by jbrook10** [Microsoft/vscode#6253]
- VSCode Version: 1.1.0
- OS Version:  Windows 7

Steps to Reproduce:

1. Open up VSCode
2. Look around and see missing icons on buttons (they work when you click them)
3. Example has missing debugger icons / debug settings / tab close icons
4. This is the first version I have ever installed.

![vscode](https://cloud.githubusercontent.com/assets/19290608/15154687/7d61d580-16a4-11e6-86f0-fdef84c6987c.png)

**Comment by bpasero** [comment]
@jbrook10 does the entry around "missing icons" on http://code.visualstudio.com/Docs/supporting/faq#_windows-faq help?

**Comment by jbrook10** [comment]
@bpasero The FAQ solved the issue for me.  Thanks!
