### ISSUE TITLE
Git - Unable to set a shortcut to stage or revert git change after Show Next Change (when dirtyDiffVisible)

### ISSUE THREAD

**Issue by dhalima3** [microsoft/vscode#62534]
- VSCode Version: 1.28.2
- OS Version: macOS High Sierra 10.13.5

Steps to Reproduce:
1. Assign a shortcut to stage and revert change when dirtyDiffVisible.  Below is what I had in my keybindings.json file.
```javascript
    {
        "key": "alt+cmd+a",
        "command": "git.stageChange",
        "when": "dirtyDiffVisible"
    },
    {
        "key": "alt+cmd+z",
        "command": "git.revertChange",
        "when": "dirtyDiffVisible"
    }
```

2. Load a file with some unstaged changes.  Use command `Show next change` from the command palette to go to next change and bring up dirty diff view.  When evoking the shortcut to either stage or revert the change, the following error message pops up "Git: Cannot read property 'toString' of undefined"

Clicking the buttons manually doesn't produce the issue, but using the keyboard shortcut does.  As you can see from the screenshot, it seems like vscode has correctly mapped the action to the shortcut.

<img width="206" alt="screenshot 2018-11-04 01 19 15" src="https://user-images.githubusercontent.com/546242/47960328-1008bd80-dfd0-11e8-9cc7-6296db574c63.png">

<img width="172" alt="screenshot 2018-11-04 01 22 35" src="https://user-images.githubusercontent.com/546242/47960374-092e7a80-dfd1-11e8-9648-6c8c9715e5ff.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Try using `git.stageSelectedRanges` and `git.revertSelectedRanges` instead.

**Comment by dhalima3** [comment]
Using `git.stageSelectedRanges` and `git. revertSelectedRanges` works when the cursor is on the same line as the change.  However, it seems that invoking the command `workbench.action.editor.nextchange` doesn't move the cursor resulting in the git commands not working.  

Will this be addressed as part of this [issue](https://github.com/Microsoft/vscode/issues/51031) and merge request?

**Comment by bryango** [comment]
As the issue has been dormant for a while, I would like to confirm that this bug is still present:
```
$ pacman -Qo /usr/bin/code 
/usr/bin/code is owned by code 1.75.1-1
```

**Comment by ChristopherBrix** [comment]
With activated Shortcut Troubleshooting, I get "2023-04-26 11:46:22.069 [info] [KeybindingService]: + Invoking command git.stageChange.", but nothing happens. 

This has also been reported on SuperUser: https://superuser.com/questions/1768536/what-is-the-vs-code-keyboard-shortcut-to-accept-a-highlighted-change

```
code -v
1.76.1
5e805b79fcb6ba4c2d23712967df89a089da575b
x64
```

**Comment by lszomoru** [comment]
Apologies for not getting back to you until now. The `git.stageChange` and `git.revertChange` require the necessary context (diff information) to function correctly. This context can only be passed when the commands are invoked through the quick diff editor toolbar, and not through keybindings.

As mentioned in [this comment](https://github.com/microsoft/vscode/issues/62534#issuecomment-437828259), you can use the `git.stageSelectedRanges` and `git.revertSelectedRanges` instead as these commands use the cursor position to determine the diff information.
