### ISSUE TITLE
"invalid columns"  that are valid column and the query works correctly

### ISSUE THREAD

**Issue by ph3ll3r** [Microsoft/vscode#62542]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

The table function Sales.udft_GetCustomerSalesOrders declares aliases
    su.companyname as SupplierCompanyName,
    s.companyname as ShipperCompanyName,
correctly.
The cross apply query projects the 
   , u.SupplierCompanyName
     , u.ShipperCompanyName
as "invalid columns" with red squiggly lines but the query executes correctly.
 

alter FUNCTION Sales.udft_GetCustomerSalesOrders
 (@custid as int)
 returns table
 as
 return
SELECT
    c.companyname, 
    c.contactname, 
    e.FullName,
    su.companyname as SupplierCompanyName,
    s.companyname as ShipperCompanyName,
    o.orderid,
    o.orderdate,
    o.shipcountry as Country  ,
    o.shipregion as Region,
    o.shipcity as City,
    p.productname,
    p.productid,
    od.qty,
    od.unitprice,
    TotalAmmountLineItem = od.qty *  od.unitprice
from Sales.Customers as c
    inner join Sales.Orders as o on c.custid = o.custid
    INNER JOIN Sales.OrderDetails as od on o.orderid=od.orderid
    inner join Hr.Employees as e on e.empid=o.empid
    INNER join Sales.Shippers as s on s.shipperid=o.shipperid
    inner JOIN Production.Products as p on p.productid = od.productid
    inner join Production.Suppliers as su on su.supplierid = p.supplierid 
    where o.custid = @custid

select C.custid
     , u.companyname
     , u.contactname
     , u.FullName
     , u.SupplierCompanyName
     , u.ShipperCompanyName
     , u.orderid
     , u.orderdate
     , u.Country
     , u.Region
     , u.City
     , u.productname
     , u.productid
     , u.qty
     , u.unitprice
     , u.TotalAmmountLineItem
from Sales.Customers                                        as C
    cross apply Sales.udft_GetCustomerSalesOrders(C.custid) as u;

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3410)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.95GB (17.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.60
xml|Dot|2.3.2
gitlens|eam|8.5.6
tslint|eg2|1.0.40
beautify|Hoo|1.4.7
rest-client|hum|0.20.3
ssmskeymap|kev|1.0.0
mssql|ms-|1.4.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2018.9.2
Go|ms-|0.6.93
PowerShell|ms-|1.9.0
vscode-docker|Pet|0.3.1
java|red|0.33.0
vscode-yaml|red|0.1.0
vscode-icons|rob|7.28.0
javascript-typescript|sou|0.0.7
code-spell-checker|str|1.6.10
vscode-java-debug|vsc|0.15.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.10.0
vscode-maven|vsc|0.11.1
JavaScriptSnippets|xab|1.7.1

</details>

**Comment by kieferrm** [comment]
Please file the issue against the SQL extension at 
https://github.com/Microsoft/vscode-mssql/issues. Thanks!
