### ISSUE TITLE
Multiline pasting fails on exactly two lines

### ISSUE THREAD

**Issue by GuiRitter** [microsoft/vscode#62547]
Issue Type: <b>Bug</b>

Hi everyone.

Consider the following piece of text:

```
copy the word "foo" from here ->
foo<- to here
paste 1st here:

paste 2nd here:

paste 3rd here:

```

Copy the `foo` word from arrow to arrow, in order to include the new line character. Place the caret at the end of the line containing `1st`. Place another caret at the end of the line containing `2nd` (default `Alt+click`). Paste. This is the expected result:

```
copy the word "foo" from here ->
foo<- to here
paste 1st here:
foo

paste 2nd here:
foo

paste 3rd here:

```

This is the actual result:

```
copy the word "foo" from here ->
foo<- to here
paste 1st here:

paste 2nd here:foo

paste 3rd here:

```

Only one line receives the paste, without the new line character. The same doesn't happen if there is only 1 caret or more than 2 carets. It also works normally if there's no new line character in the clipboard.

Thanks in advance.

VS Code version: Code - Insiders 1.29.0-insider (9b2a7f4a83ca6a2d495463276a21157f398b41e7, 2018-11-02T13:42:21.142Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.96GB (1.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by rebornix** [comment]
I can't reproduce this any more in latest version. We can reopen when anyone runs into it again.

**Comment by GuiRitter** [comment]
I still can, though. Just downloaded the latest Insiders to confirm.

VS Code version: Code - Insiders 1.37.0-insider (310cb67b0e5df5b0644f42df93ada186130dcd1b, 2019-08-02T11:11:48.598Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 x 3200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.69GB (1.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none
