### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by mrsaadme** [Microsoft/vscode#62541]
Issue Type: <b>Bug</b>

Vscode keeps on crashing after its latest update

VS Code version: Code - Insiders 1.29.0-insider (4b2fac2b6da220f62ff58b2766e4ecc1f561be94, 2018-10-30T16:53:45.728Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.79GB (3.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
(1 theme extensions excluded)

**Comment by kieferrm** [comment]
@mrsaadme can you pls provide more detailed steps? What are you doing when it happens? Does it also happen when you disable all extensions with `code-insiders --disable-extensions`?

**Comment by debabratakarfa** [comment]
> @mrsaadme can you pls provide more detailed steps? What are you doing when it happens? Does it also happen when you disable all extensions with `code-insiders --disable-extensions`?

Not solve

**Comment by chrmarti** [comment]
@debabratakarfa Are you seeing this? What makes it reproduce? With which versions of VS Code does it occur?

**Comment by jrieken** [comment]
closing this as dupe of #62628
