### ISSUE TITLE
create file path bug

### ISSUE THREAD

**Issue by xgqfrms** [Microsoft/vscode#62558]
# vscode can't auto figure out the folder path   & create file path bug

> vscode can't auto figure out the folder path when create a file with folder path?

![image](https://user-images.githubusercontent.com/7291672/47972663-5269f180-e0d9-11e8-85bf-f5a9d954d23f.png)

***
- VSCode Version: 1.5.1
- OS Version: Windows 10 pro x64

![image](https://user-images.githubusercontent.com/7291672/47972743-0ff4e480-e0da-11e8-8dc6-a0b1c0b0170a.png)

Steps to Reproduce:

1. click + `new File` icon
2. create a new file with the folder path

![vscode-bug](https://user-images.githubusercontent.com/7291672/47972776-72e67b80-e0da-11e8-9797-a7827582740f.gif)

Does this issue occur when all extensions are disabled?: No

**Comment by kieferrm** [comment]
Please update to a newer version of VS Code. Thanks!
