### ISSUE TITLE
Error with python. Says 'No module named '"module"'' for every module i try and use

### ISSUE THREAD

**Issue by MoxieMoo** [Microsoft/vscode#62552]
I have been trying to use my modules in python for a day now. so far no success I have tried to restart the app, redownload the module and etc. (basically anything I could find on the internet to fix this problem). if anyone here can help me I would greatly appreciate it. 

from,  MoxieMoo

**Comment by kieferrm** [comment]
Please file the issue against the python extension at 
https://github.com/Microsoft/vscode-python/issues. Thanks!
