### ISSUE TITLE
Annotation 

### ISSUE THREAD

**Issue by mysea** [Microsoft/vscode#62556]
Issue Type: <b>Bug</b>

Before pressing the shortcut key ctrl+/, the JavaScript annotation is //, but now it becomes `<!-- -->`.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

**Comment by kieferrm** [comment]
Please provide steps that allow us to reproduce the problem.

**Comment by alexr00** [comment]
I also can't repro. My steps were:
1. Create a new file with the name testcomment.cshtml
2. Add html tag, head tag and script tag. Add some text in the script tag.
3. Select the text in the script tag. ctrl+/

**Comment by mysea** [comment]
After updating to the latest version, I did the same thing again, but when I pressed `Ctrl+/`, the comment did become `<!-->`.
![image](https://user-images.githubusercontent.com/22957843/48525147-f44dc300-e8bd-11e8-8a34-8da221bdf4d3.png)

**Comment by alexr00** [comment]
Does this reproduce with all extensions disabled? I still can't reproduce it.
