### ISSUE TITLE
Memory and CPU usage is too high

### ISSUE THREAD

**Issue by SendAcacia** [Microsoft/vscode#62559]
Issue Type: <b>Performance Issue</b>

Hello, thank you very much for the convenience brought by our products. Recently, when I was programming, I found that my computer memory usage is as high as 2G to 3G, CPU is up to 80%, and I often restart it. I hope I can solve it. Thanks again.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (1.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    81	 11656	code main
    1	    73	  4620	   window (问题报告程序)
    0	    70	  7176	   shared-process
    0	    84	 13184	   gpu-process
    0	   227	 14308	   window (Entry.php - 无标题 (工作区) - Visual Studio Code)
    0	    40	   588	     searchService
    0	    13	   856	     electron-crash-reporter
    0	   122	 10088	     extensionHost
    0	    83	  8572	       electron_node tsserver.js 
    0	    56	 22272	         electron_node typingsInstaller.js typesMap.js 
    0	    40	  9632	       electron_node server.js 
    0	   356	 14280	       electron_node server.js 
    0	    83	 15444	       "D:\Program\Microsoft VS Code\Code.exe" "d:\Program\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain" --node-ipc --clientProcessId=10088
    0	   187	 17992	       electron_node server.js 
    0	   275	 19468	       php c:\Users\nl\.vscode\extensions\felixfbecker.php-intellisense-2.3.5\vendor\felixfbecker\language-server\bin\php-language-server.php --tcp=127.0.0.1:64355 --memory-limit=4095M
    0	    10	 16852	         console-window-host (Windows internal process)
    0	   343	 21644	       electron_node server.js 
    0	   356	 21760	       electron_node server.js 
    0	    44	 16812	     watcherService
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Entry.php - 无标题 (工作区) - Visual Studio Code)
|    Folder (php): 1 files
|      File types: php(1)
|      Conf files:
|    Folder (py): 16 files
|      File types: py(5) pyc(3) php(3) txt(2) log(1) md(1) html(1)
|      Conf files:
|    Folder (Project): more than 20628 files
|      File types: svn-base(11581) php(3220) html(3182) png(564) dat(360)
|                  md(195) js(168) jpg(150) gitignore(136) css(111)
|      Conf files: makefile(4) launch.json(1) package.json(1)
|      Launch Configs: php(2);
```

</details>
<details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
color-info|bie|0.5.0
vscode-intelephense-client|bme|0.8.8
vscode-great-icons|emm|2.1.44
prettier-vscode|esb|1.6.1
php-debug|fel|1.12.6
php-intellisense|fel|2.3.5
minify|Hoo|0.3.0
vscode-language-pack-zh-hans|MS-|1.28.2
mssql|ms-|1.4.0
php-docblocker|nei|1.6.0
material-icon-theme|PKi|3.6.0
vscode-css-peek|pra|2.1.0
html5-boilerplate|sid|1.0.3
ayu|tea|0.16.0
vscode-todo-highlight|way|1.0.4

(4 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Can you look at the process explorer when vscode is using high cpu, to find out which process is using high cpu? The attached details only shows normal low cpu usage.
