### ISSUE TITLE
Settings UX - JSON input field

### ISSUE THREAD

**Issue by Astrantia** [Microsoft/vscode#62555]
This is a feature request for the settings ui. With it being introduced, we still have to go to the json editor for more complicated settings. What's the harm of having a multiline Monaco json editor in settings gui? 

@roblourens

**Comment by roblourens** [comment]
We considered something like this but I don't like it, I think it would be awkward to have a text editor inside the UI. I think it's better to let a normal json editor be a good editor, and have the UI be a good UI.
