### ISSUE TITLE
opencv can't show function list and funciton document

### ISSUE THREAD

**Issue by yanhaiming56** [Microsoft/vscode#62562]
Issue Type: <b>Bug</b>

when I write python code,calling the opencv function like "cv2.imread",it can't show function list of opencv and under the "cv2" which show the red wave line.In fact, it's no problem and can run normally.
![image](https://user-images.githubusercontent.com/26322264/47974762-02455c00-e0e6-11e8-8349-69eee8347124.png)

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (3.24GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-python-docstring|aza|0.0.5
bat-snippets|bat|0.2.0
python-snippets|cst|0.2.0
c-cpp-project-generator|dan|1.1.1
python-preview|don|0.0.4
code-python-isort|fre|0.0.3
CppSnippets|har|0.0.13
Python-autopep8|him|1.0.2
py-paste-indent|hye|0.0.2
jumpprotobuf|ldc|0.0.3
vscode-language-pack-zh-hans|MS-|1.28.2
anaconda-extension-pack|ms-|1.0.1
python|ms-|2018.9.2
cpptools|ms-|0.20.1
python-docs|Muk|0.8.3
proto|pet|0.0.2
vscode-yaml|red|0.1.0
vscode-icons|rob|7.28.0
python|tht|0.2.3
copy-python-path|yar|1.0.4
vscode-proto3|zxh|0.2.1

</details>

**Comment by kieferrm** [comment]
Please file the issue against the Python extension here. 
https://github.com/Microsoft/vscode-python/issues. Thanks!
