### ISSUE TITLE
Java no longer working

### ISSUE THREAD

**Issue by aparrish22** [Microsoft/vscode#62568]
Issue Type: <b>Bug</b>

I don't know why, but Java stopped working for some reason. I didn't change anything. One day I turn my computer off after successfully running a Java code on VS Code. Then the next day, right after I turn on my pc and open up VS code, I try to run my Java code(s), but VS code returns:
"Error: Could not find or load main class <myjavafilename>"

And don't ask me if I installed anything new or did anything between that night and that morning. Like I said, I turn the pc off, turn it back on the next day and get right back on VS code to this Error after running java. *crying emoji*

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (1.94GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eclipse-keybindings|alp|0.9.8
code-gnu-global|aus|0.2.2
vscode-intelephense-client|bme|0.8.8
c-cpp-compile-run|dan|0.4.3
vscode-eslint|dba|1.7.0
vsc-material-theme|Equ|2.5.1
php-debug|fel|1.12.6
php-intellisense|fel|2.3.5
php-pack|fel|1.0.2
code-runner|for|0.9.5
phpcs|ika|1.0.5
csharpfixformat|Leo|0.0.76
vscode-clang|mit|0.2.3
mssql|ms-|1.4.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2018.9.2
cpptools|ms-|0.20.1
csharp|ms-|1.17.0
material-icon-theme|PKi|3.6.0
java|red|0.33.0
vscode-yaml|red|0.1.0
ayu|tea|0.16.0
vscode-java-debug|vsc|0.15.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.10.0
vscode-maven|vsc|0.11.1
JavaScriptSnippets|xab|1.7.1

(4 theme extensions excluded)

</details>

**Comment by kieferrm** [comment]
Please file the issue against the Java extension at
https://github.com/redhat-developer/vscode-java/issues. Thanks!
