### ISSUE TITLE
when I run {start /max "VSCODE" "H:\Microsoft VS Code\Code.exe"}

### ISSUE THREAD

**Issue by bigmgreen** [Microsoft/vscode#62561]
- VSCode Version: 1.28.2
- OS Version: win10 64

Steps to Reproduce:

1. `start /max "VSCODE" "H:\Microsoft VS Code\Code.exe"` by cmd;
2. when it opened, but cmd not exit;
3. the message:
```
[main 涓婂崍9:59:10] update#setState idle 

[main 涓婂崍9:59:41] update#setState checking for updates 

[main 涓婂崍9:59:41] update#setState idle 
```
4. I clicked the close btn of the cmd, cmd and vsocde exit, was that ok?

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
What is it that you are trying to do?
