### ISSUE TITLE
Javascript does weird formats on save

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#6256]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows 10

Steps to Reproduce:

For my repro I was working on developing an extension generated by Yo.
1. Open extension.js
2. Delete an ending semi-colon somewhere
3. Save

It removes the extra line spacing between the brackets of the deactivate function at the bottom. It also adjusts the function bracket spacing of the function inside disposable.

![saveformatting](https://cloud.githubusercontent.com/assets/12900364/15158198/90843910-16a3-11e6-91ba-4c4db83341d3.gif)

**Comment by jrieken** [comment]
@vsccarl there is no format on save by default. what extensions has you installed?

**Comment by vsccarl** [comment]
Looks like it is a result of the [JS-CSS-HTML formatter extension](https://marketplace.visualstudio.com/items?itemName=lonefy.vscode-JS-CSS-HTML-formatter). It does not repro with extensions removed.
