### ISSUE TITLE
npm publish silently fails on OTP prompt

### ISSUE THREAD

**Issue by bnb** [Microsoft/vscode#62560]
Issue Type: <b>Bug</b>

As an npm user, I've got 2FA for publishes turned on. When I try to run `npm publish` from the Terminal inside of VS Code with the following error:

```
npm ERR! publish Failed PUT 401
npm ERR! code E401
npm ERR! You must provide a one-time pass. Upgrade your client to npm@latest in order to use 2FA. : good-first-issue
```

If I run the same command from my normal terminal application, I am prompted for a one-time password (OTP) that I can find in my authenticator app. It seems that, for whatever reason, VS Code does not play well with npm's implementation of OTPs.

VS Code version: Code - Insiders 1.29.0-insider (d43f6cb9947c57a3254b556e69aeacc2b2025184, 2018-11-02T15:50:03.156Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (8.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.7.0
chat|kar|0.7.3
vscode-codemetrics|kis|1.17.3
vscode-azurefunctions|ms-|0.12.0
azure-account|ms-|0.4.3
vsliveshare|ms-|0.3.897
vsliveshare-audio|ms-|0.1.39
debugger-for-chrome|msj|4.10.2
vscode-for-node-js-development-pack|nod|2.0.1
vscode-docker|Pet|0.3.1
code-settings-sync|Sha|3.2.0
vscode-import-cost|wix|2.9.0

</details>

**Comment by Tyriar** [comment]
The error message tells you what the problem is:

> Upgrade your client to npm@latest in order to use 2FA.
