### ISSUE TITLE
终端编辑多次

### ISSUE THREAD

**Issue by baixinfei** [microsoft/vscode#62578]
没有开启自动保存，但是ctrl+s，终端会编译多次

**Comment by GongT** [comment]
你需要仔细描述问题

**Comment by rebornix** [comment]
@baixinfei please provide detailed reproduce steps.

**Comment by jcs090218** [comment]
I think what he is saying is that the built-in terminal compiles multiple times when saving?

**Comment by rebornix** [comment]
Close as lack of enough information to help troubleshoot. We can reopen whenever we have good reproduce steps.
