### ISSUE TITLE
Wrong highlight when ignoring FOLDER but NOT SOME files

### ISSUE THREAD

**Issue by jpenna** [Microsoft/vscode#62574]
- VSCode Version: 1.28.2
- OS Version: MacOS 10.13.6

Files are wrongly highlighted when using .gitignore with DON'T ignore 

> It worked correctly after closing and reopening Code, but for the second folder it didn't work again, even after reopening. Check below.

`.gitignore`
```.gitignore
# .gitignore
folder/*
!folder/*.track.json
```

<img width="345" alt="screen shot 2018-11-02 at 12 19 35 pm" src="https://user-images.githubusercontent.com/16005946/47893786-d170e700-de99-11e8-8610-5131a401c2b8.png">

Code and Git are tracking correctly.

<img width="339" alt="screen shot 2018-11-02 at 12 20 18 pm" src="https://user-images.githubusercontent.com/16005946/47893787-d170e700-de99-11e8-866b-fab8d85ce650.png">
<img width="340" alt="screen shot 2018-11-02 at 12 20 34 pm" src="https://user-images.githubusercontent.com/16005946/47893789-d2a21400-de99-11e8-8942-400723ed4261.png">

`*.track.json` should be highlighted and tracked. The others not.

**UPDATE (2018-11-05)**

After reopening Code, it showed correctly the `folder` folder. Then I created another folder to check, but this `another` folder didn't work, even after reopening the application.

`.gitignore`
```.gitignore
folder/*
!folder/*.track.json

another/*
!another/*.track
```

with `code --disable-extensions` and another folder
<img width="340" alt="screen shot 2018-11-05 at 3 57 18 pm" src="https://user-images.githubusercontent.com/16005946/47985071-89f58f80-e113-11e8-963a-61795fb3a21c.png">

Steps to reproduce:
 1. Just create a folder, ignore it in .gitignore and "unignore" some files.

**Comment by jrieken** [comment]
please run `git check-ignore` and see what it reports as being ignored (https://git-scm.com/docs/git-check-ignore)

**Comment by jpenna** [comment]
@jrieken I didn't understand what you mean. How do you want me to run this command?

The problem is that Code is not updating correctly the highlights. It shows the lines in gray even if git is tracking them. Check above, git is tracking the `folder/file.track.json`, but Code is showing it in gray, even though Code is also showing a `U` next to the file name, meaning the "letters feature" is tracking correctly. 

By the way, I reopend this sample folder to run the `git check-ignore`, and now all the files are gray.

<img width="585" alt="screen shot 2018-11-06 at 6 17 17 pm" src="https://user-images.githubusercontent.com/16005946/48057936-39a02f80-e1f0-11e8-8077-78b4aa4d9ce7.png">

**Comment by jrieken** [comment]
Open a console for that folder and type `git check-ignore SOME_PATH -v`. That's the command VS Code runs to know if a file is ignored or not. If git things the file isn't ignored, then it's a config or git issue
