### ISSUE TITLE
eslint menu can't scroll to bottom

### ISSUE THREAD

**Issue by Alfred-kai** [Microsoft/vscode#62570]
Issue Type: <b>Bug</b>

I can't scroll to the bottom of the menu when I tried to use eslint fix menu

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|7.89GB (2.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.7.0
vetur|oct|0.13.0
autoimport|ste|1.5.3
addDocComments|ste|0.0.8

</details>

**Comment by sbatten** [comment]
this issue is likely fixed, please re-open if you still encounter the issue.
