### ISSUE TITLE
Option for opening defintion in peek view with Ctrl+click

### ISSUE THREAD

**Issue by AlexGuo1998** [microsoft/vscode#62571]
When we use `Ctrl + mouse click` to jump to definition, `vscode` would open the definition in a new window, which is inconvenient for me.

It would be better if we can choose where to open definition, like in `Visual Studio`. [VS settings here](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-view-and-edit-code-by-using-peek-definition-alt-plus-f12?view=vs-2017#to-change-options-for-peek-definition)

![image](https://user-images.githubusercontent.com/25975864/47980352-39c20180-e102-11e8-800a-294679a1ffe4.png)

**Comment by GustavoASC** [comment]
Nice suggestion.

@jrieken If you agree with this, I'll create a setting so one can choose the 'ctrl+click behavior':
- Go to definition (default)
- Peek definition

**Comment by JacksonKearl** [comment]
Normally, ctrl+click runs `editor.action.revealDefinition` and cmd+ctrl+click opens `editor.action.revealDefinitionAside`. With this setting enabled, they both run `editor.action.PeekDefinition`. I don't think that's expected. Possibly change https://github.com/microsoft/vscode/pull/89884/files#diff-e65fe89b0a38c52267c34d0a2b04a9feR339 to

```ts
new DefinitionAction({ openToSide, openInPeek: openInPeek && !openToSide, .... 
```
?

**Comment by roblourens** [comment]
@JacksonKearl you can reopen verification-found issues

**Comment by GustavoASC** [comment]
@JacksonKearl Uhm, I'll take a look on that. Thanks for your feedback!

**Comment by jrieken** [comment]
@JacksonKearl Please file a bug and don't reopen feature requests

**Comment by jrieken** [comment]
I created https://github.com/microsoft/vscode/issues/91665
