### ISSUE TITLE
C++ code folding does properly handle macros that are not fully indented.

### ISSUE THREAD

**Issue by jhaberstro** [Microsoft/vscode#6258]
- VSCode Version: Version 1.0.0 fa6d0f03813dfb9df4589c30121e9fcffa8a8ec8
- OS Version: OS X 10.11.4

Steps to Reproduce:

1. Create a C++ file
2. Insert the following code and notice how code folding works correctly:
```
if (blah)
{
    // line 1
    // line 2
    // line 3
}
````
3. Add some if-endif macros that are not indented the same as the body of the if statement and notice that only code up to the #if is folded, e.g.:
```
if (blah)
{
    // line 1
#if 1
    // line 2
#endif
    // line 3
}
```

**Comment by aeschli** [comment]
The currently implemented folding strategy is based purely on the indentation of lines. A folding region starts when a line has a smaller indent than one or more following lines, and ends when there is a line with the same or smaller indent.

To be more smart and to, for example, understand C++ blocks, we will have to go one step further and introduce language agnostic folding regions. We have issue #3422 for this.
