### ISSUE TITLE
Add preferences per windows registry

### ISSUE THREAD

**Issue by alexhass** [Microsoft/vscode#62581]
It looks like MS has implemented a way to access the windows registry for electron applications, see https://www.microsoft.com/developerblog/2015/11/09/reading-and-writing-to-the-windows-registry-in-process-from-node-js/.

Enterprise administrators need to be able to pre-configure applications behaviour per machine/per user via Windows registry.

I need to disable automatic update (`update-channel`) per machine as VSCode is installed per machine. GPOs cannot write JSON files.

Please allow setting global preferences via registry.

This is needed at minimum:
```
  "telemetry.enableTelemetry": false,
  "telemetry.enableCrashReporter": false,
  "update.channel": "none",
```

**Comment by alexhass** [comment]
- disable all update menu points in the application

**Comment by sandy081** [comment]
> Please allow setting global preferences via registry.

@alexhass Not sure what exactly you mean by setting global preferences via registry. Can you please explain in more detail about this?

**Comment by alexhass** [comment]
This means per machine gpo or per machine settings. Not per user only. 

It need to work with group policies. Therefore we vannot write to json files as only windows registry is supported by microsoft.

**Comment by sandy081** [comment]
@alexhass Thanks for the details.

> This means per machine gpo or per machine settings. Not per user only.

Go it 👍 


> GPOs cannot write JSON files.
Please allow setting global preferences via registry.

This is still not clear. Are you expecting to have a machine level settings which are not in json files?

**Comment by alexhass** [comment]
Yes, json files cannot written with GPO, so it need to be in the registry.

**Comment by sandy081** [comment]
I see. We have plans for supporting machine specific settings but sorry that we might not implement reading configuration from windows registry. 

So closing this.

**Comment by alexhass** [comment]
How should we set enteeprise settings than?
