### ISSUE TITLE
yarn install failed :vscode-ripgrep: Command failed.

### ISSUE THREAD

**Issue by gooyoy** [Microsoft/vscode#62589]
- VSCode Version:
master 
I use a new floder and run git clone 
- OS Version:
mac os 10.14 Mojave
yarn v1.12.1
node v8.12.0

Steps to Reproduce:

1.
yarn
yarn install v1.12.1
$ node build/npm/preinstall.js
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
info windows-foreground-love@0.1.0: The platform "darwin" is incompatible with this module.
info "windows-foreground-love@0.1.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info windows-mutex@0.2.0: The platform "darwin" is incompatible with this module.
info "windows-mutex@0.2.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info windows-process-tree@0.2.2: The platform "darwin" is incompatible with this module.
info "windows-process-tree@0.2.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[-/14] ⠠ waiting...
[10/14] ⠠ vscode-ripgrep
[-/14] ⠠ waiting...
[11/14] ⠠ oniguruma
error /Users/billlu/work/g6ide/node_modules/vscode-ripgrep: Command failed.
Exit code: 1
Command: node ./lib/postinstall.js
Arguments: 
Directory: /Users/billlu/work/g6ide/node_modules/vscode-ripgrep

BILLLU-MC1:g6ide billlu$ 
2.

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by gooyoy** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [yarn fails to install vscode-ripgrep (#61164)](https://www.github.com/Microsoft/vscode/issues/61164)
> * [Problems while building from source: electron-mksnapshot error (#61575)](https://www.github.com/Microsoft/vscode/issues/61575)

i readed this threads,and run git clean -xfd  it's dosn't work.the issue still exists

**Comment by roblourens** [comment]
Is there an error log in your workspace with details?

**Comment by gooyoy** [comment]
> Is there an error log in your workspace with details?
i run yarn with --verbose
this output is
Downloading ripgrep failed: Error: connect ETIMEDOUT 13.250.94.254:443

i behind firewall but i set proxy as 
yarn config set proxy http://proxyhost:port
yarn config set strict-ssl=false

**Comment by gooyoy** [comment]
> Hm, so this is not the IP of your proxy? `13.250.94.254`
> 
> In theory, the yarn proxy config settings should be applied inside the postinstall task that downloads ripgrep.

yes，13.250.94.254 is not my proxy ip.
my proxy is work fine ,but can not work for download vscode-ripgrep,why?

**Comment by roblourens** [comment]
I don't know. It would be helpful if you can help me debug it by testing whether the HTTP_PROXY env var is set in the postinstall task.
