### ISSUE TITLE
Theme development: default theme switching

### ISSUE THREAD

**Issue by sho-87** [Microsoft/vscode#62582]
- VSCode Version: 1.28.2
- OS Version: Windows 10

Steps to Reproduce:

1a. Set primary VScode theme in `settings.json` using `"workbench.colorTheme": "theme"`.
1b. For the second problem below, change the order of the activity bar icons
2. Create new color theme using Yeoman extension generator
3. In `launch.json` set args to `["--extensionDevelopmentPath=${workspaceFolder}", "--disable-extensions"]`
3. F5 into Extension Development Host (EDH)
4. Preferences > Color Theme > choose new theme currently under development
5. Exit EDH/debugging, quit all instances of VScode
6. Launch Code again

**Problem 1**: Switching into EDH (and switching themes within) caused my regular `settings.json` colorTheme setting to change to the name of the new theme. The new theme obviously can't be found without EDH, so it defaults to another dark theme (Dark+). This is a minor annoyance, but I would have thought that debugging in EDH should not change anything about my regular environment. This results in constantly having to switch back to my main editor theme. Is there a way to have EDH use a blank/different `settings.json` file during debugging so my main one doesn't get altered?

**Problem 2**: If I change the order of my activity bar icons as well during step 1 and go through the steps again, when I re-launch code the icon order resets back to default. For example, I use a number of extensions that add icons to the bar (project manager, gitlens, bookmarks). They typically show up at the bottom of the icon list. I change the order of those icons to something more sensible, but the order is not preserved when switching in and out of EDH. Maybe this has something to do with disabling extensions when entering EDH?

**Comment by kieferrm** [comment]
The issue here is that the user settings are shared between the OSS version of VS Code and the actual installed product. This is convenient in some cases but disturbing in others like the one explained here.

**Comment by sho-87** [comment]
@kieferrm @sandy081 Is this behaviour currently considered a bug or a feature?

obviously the problems I described are fairly trivial but...

when creating themes you have to change the active theme in the EDH as thats the only way to test it. In this situation I feel like the users expectation is that the settings change is isolated to that testing session, and not persisted to their regular `settings.json`. theres no reason to expect otherwise because the theme change is a requirement of testing, not something I actually want to change for myself, so persisting that change is counter to what the user would want or expect

would a sensible middle ground be to use a copy of the users settings when entering EDH, and maybe discard it when going back to the installed environment? That way you get the benefits of using your own settings when testing/debugging, but nothing about your regular environment is changing behind the scenes

**Comment by sandy081** [comment]
I think settings is not the primary issue here.. it is just a detail of you can change a theme.

IMO, Theme updater should be smart to detect that the theme extension is being debugged and when switching to the development theme the change should be done in memory rather than impacting all windows.

Second issue is because of disabling extensions which is resetting the order.
