### ISSUE TITLE
VSC really slow after last update

### ISSUE THREAD

**Issue by clegeard** [Microsoft/vscode#62588]
Issue Type: <b>Bug</b>

After a while working, the application gets stuck, cursor not available, takes seconds to write somehing.  It is definitely not working as it should since I updated on Friday.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6440HQ CPU @ 2.60GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.83GB (18.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
lit-html|bie|1.7.0
beautify|Hoo|1.4.7
Angular-BeastCode|Mik|7.0.14
csharp|ms-|1.17.0
debugger-for-chrome|msj|4.10.2
vscode-extension-auto-import|Nuc|1.4.3
autoimport|ste|1.5.3
es6-string-html|Tob|1.8.3
highlight-matching-tag|vin|0.8.1

</details>

**Comment by smbt** [comment]
I´m having similar issues. I´m also using beautify in some projects. I now disabled it and will see if it will be better.

**Comment by clegeard** [comment]
> 
> 
> Can you try to follow the steps described in here: https://github.com/Microsoft/vscode/wiki/Performance-Issues. This would help us to pin this down further. Thanks!

In my case it seems node.js is consuming the memory...

![capture](https://user-images.githubusercontent.com/30863390/48062306-8a486600-e1b9-11e8-9577-9186ec2f4933.PNG)

**Comment by clegeard** [comment]
Although when I stop serving my project I have still issues. If you see in the shot I sent the file I am editing is consuming 344 MB and it is only 100 lines of code.

**Comment by jrieken** [comment]
While some memory is being consumed it is not so much that it would cause a noticeable slow down or freezes. Please keep an eye open use the CPU profiler when slowness happens: https://github.com/Microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process

**Comment by vitorsemeano** [comment]
Hi, I'm having the same problem reported in this issue. I managed to capture some profiling data while this freezes happened:

[CPU-20181108T095150.zip](https://github.com/Microsoft/vscode/files/2561218/CPU-20181108T095150.zip)

I am also running vscode with these extensions:
annsk.alignment
bladnman.auto-align
bmewburn.vscode-intelephense-client
donjayamanne.githistory
DotJoshJohnson.xml
dracula-theme.theme-dracula
eamodio.gitlens
ecmel.vscode-html-css
ecodes.vscode-phpmd
felixfbecker.php-debug
formulahendry.code-runner
GrapeCity.gc-excelviewer
HookyQR.beautify
kokororin.vscode-phpfmt
marcostazi.VS-code-vagrantfile
mechatroner.rainbow-csv
michelemelluso.code-beautifier
mikestead.dotenv
mkaufman.HTMLHint
mrmlnc.vscode-apache
msjsdiag.debugger-for-chrome
mtxr.sqltools
neilbrayfield.php-docblocker
onecentlin.laravel-blade
onecentlin.laravel5-snippets
robertohuertasm.vscode-icons
spywhere.whiteviz
steve8708.Align
stevejpurves.cucumber
stevencl.addDocComments
tht13.html-preview-vscode
tomoki1207.pdf
TysonAndre.php-phan
vincaslt.highlight-matching-tag
wayou.vscode-todo-highlight
wwm.better-align
xyz.local-history

**Comment by jrieken** [comment]
Thanks @vitorsemeano. This is the same profile as seen in https://github.com/Microsoft/vscode/issues/62693. Must be one of the extensions you have in common with @rtemred. Getting closer...
