### ISSUE TITLE
The window appears distorted

### ISSUE THREAD

**Issue by 0815fox** [Microsoft/vscode#62583]
When I open a certain file in VS Code and move the mouse, scroll, etc, the window becomes distorted. Also context overlays do not work correctly. With other files this issue does not occur.

- Use Help > Report Issue to prefill these.
Side note: VSCode crashed when I invoked Help -> Report Issue.

- VSCode Version: 1.28.2

Happens also with:
1.28.2-1539735992 - visual-studio-code (= ) 
1.28.1-1539281690 - visual-studio-code (= ) 
1.28.0-1538751525 - visual-studio-code (= ) 
1.27.2-1536736588 - visual-studio-code (= ) 
1.27.1-1536226049 - visual-studio-code (= ) 
1.27.0-1536125615 - visual-studio-code (= ) 
1.26.1-1534444688 - visual-studio-code (= ) 
1.26.0-1534177765 - visual-studio-code (= )

Last version without this issue:
1.25.1-1531323788

- OS Version: Debian 9.5

Steps to Reproduce:

1. Open the file EndPoints_Settings.ts
2. Move the mouse, scroll, etc.

Does this issue occur when all extensions are disabled?: Yes, still occurs.

#60873 may be a similar issue, however, I am on linux, not mac and `code --disable-gpu` seems not to help in my case.

![endpoints_settings ts - twms-backend - visual studio code_020](https://user-images.githubusercontent.com/8955528/47995678-6112d180-e0f6-11e8-8294-6b0429b2c0f9.png)
![endpoints_settings ts - twms-backend - visual studio code_019](https://user-images.githubusercontent.com/8955528/47995680-6112d180-e0f6-11e8-8707-b0dd8b3037a2.png)

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/45498d93166483c2eff886e28f8dab915ae382fc/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/code-exploration_1.28.0-1538127308_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/VSCodeUserSetup-x64-1.28.0-exploration.exe)
