### ISSUE TITLE
bogus test: basics (broken DB falls back to in-memory)

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#62587]
this test only works once and then fails until the compiler is restarted...

<img width="949" alt="screenshot 2018-11-05 at 13 06 44" src="https://user-images.githubusercontent.com/1794099/47997325-ba313400-e0fb-11e8-9025-814cabe7ae58.png">

**Comment by bpasero** [comment]
Thanks for catching, pushed a fix.
