### ISSUE TITLE
Remove explorer header

### ISSUE THREAD

**Issue by thany** [microsoft/vscode#62596]
Issue Type: <b>Feature Request</b>

Please remove this header. I know it's the explorer. I can see it by all the files than can be explored/are open. This header is just taking up space for no good reason.

![capture](https://user-images.githubusercontent.com/152227/48003145-e0f86600-e10d-11e8-93f1-3c44d036b496.PNG)
*That there header in red*

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

**Comment by thany** [comment]
> If you want to hide the header you can hide all other non explorer views and the header will automatically go away.

I only have code editors open, and the header still shows. So I guess that's not what you mean by "non explorer views"?

> If there are multiple views we show the header, that is just our design currently, do I do understand your point about saving vertical space

Even if I close everything, that header stays put. What more can I close?...

**Comment by isidorn** [comment]
The header will stay, but you will save some vertical space.

![close](https://user-images.githubusercontent.com/1926584/48008282-a3013f00-e119-11e8-8479-2883276b9cfd.gif)

**Comment by misolori** [comment]
This would cause issues in the case where you have no list headers (as @isidorn shows above) because we also show actions in the header: 

![image](https://user-images.githubusercontent.com/35271042/48010065-bb4d6b80-e0d1-11e8-9daf-a688ec0474c7.png)

Additionally, this would cause inconsistencies with out other views since every view has a header and actions. This would be a 👎 for me.

**Comment by thany** [comment]
@isidorn So hide the whole "open editors" tree. Then I can't know which editor I have open. I don't have tabs.

@misolori For me, the "explorer" header is always empty, apart from the text "explorer" in screaming capitals. For me those buttons sit on the collapsable trees below it...
![capture](https://user-images.githubusercontent.com/152227/48053865-0471ee00-e1ac-11e8-82b8-c2fc1d74dda7.PNG)
So the header is completely useless to me.

Personally I don't care about consistency with other panels. The explorer panel is the one I work with pretty much 99% of the time. I'm not installing extensions all day, I'm actually working with code ;)

**Comment by isidorn** [comment]
@thany I also do not have tabs and do not have open editors. Just try that out, you might like that setup. You will get accustomted to using Quick PIck for navigating between open files.

**Comment by spencermountain** [comment]
i removed this by adding this to my `workbench.main.css` file
```css
.title-label > h2 {
  display:none;
}
```

on a mac that file is at `/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.css
`
cheers

**Comment by thany** [comment]
> @thany I also do not have tabs and do not have open editors. Just try that out, you might like that setup. You will get accustomted to using Quick PIck for navigating between open files.

I don't know that I'll like that. Especially in a project with hundreds and hundres of files.

Why can't we have either:
* No main header, but do have subheaders for each pane
* Main header only for those without the "open editors" pane. 

In other words, why MUST the main header sit there, when it's adding absolutely nothing, and only taking precious vertical screen real estate. When it DOES add functionality, by all means keep it visible. But when it DOESN'T add anything, why not hide it? How hard can it be?

@spencermountain We shouldn't hack into program code like that.

**Comment by colinmegill** [comment]
This should be reopened. The header accomplishes nothing, and editing the CSS causes the error `Installation appears to be corrupt [Unsupported]#`

**Comment by rafaelrenanpacheco** [comment]
I would love an option to hide that `EXPLORER` (useless) label as well. Messing around with the CSS didn't work for me due a computed height value for the explorer:

![image](https://user-images.githubusercontent.com/12160864/77763521-fb402600-7019-11ea-961a-a4b965401222.png)

So, after hiding the explorer label with:

```css
.monaco-workbench .part>.composite.title { display: none; }
```

The engine is still calculating the explorer height size as if the explorer label were still there. At the image above you can see a gap between the statusbar and the `Maven Projects`, even tho maven projects is collapsed.

**Comment by whaaaley** [comment]
Yes please.

**Comment by rchoudhary** [comment]
Hey everyone, just wanted to let you know that you can use @spencermountain's CSS snippet _without_ corrupting your VS Code installation! Simply download the [Customize UI](https://marketplace.visualstudio.com/items?itemName=iocave.customize-ui) extension from the marketplace and add the following to your settings JSON file:

```
    "customizeUI.stylesheet": {
        ".title-label > h2" : "display: none"
    }
```

I have just tried it myself and it works like a charm! :)

For reference, I'm using VS Code version 1.46 on Mac OS Mojave.

**Comment by CodeBrotha** [comment]
Is it possible to remove the "EXPLORER:" text when a folder is open, and only show the folder name there? Prepending the "EXPLORER:" makes it hard to see the folder name at a glance without extending the sidebar into the working space.

**Comment by MichaelScoggins** [comment]
i'm looking for this as well.

**Comment by whaaaley** [comment]
fwiw the monkey patch extension that the customize ui extension uses still "corrupts" your installation in the same way

**Comment by bartekpacia** [comment]
This needs to be reopened, we need this feature.

**Comment by whaaaley** [comment]
Update in 2022.

Use this extension: <https://github.com/be5invis/vscode-custom-css>
Use this CSS:

```css
.title-actions {
  display: none;
}

#be5invis.vscode-custom-css {
  display: none;
}
```

For just the header label and not the actions use `.title-label`

**Comment by SidBlack** [comment]
Hello, I have a question, I do not know why you are asking me with this
problem I do not know programming I do not know what you mean, this is not
my field

niedz., 6 mar 2022 o 23:36 Whaley ***@***.***> napisał(a):

**Comment by whaaaley** [comment]
@SidBlack If this isn't you <https://github.com/SidBlack> this person is using your email for their GitHub account.

**Comment by AuracleTech** [comment]
still there... Its uglyyyyyyyyyyyyyyyyyyyy

maybe they should add "editor" for where the editor is, and "sidebar" for the sidebar, and search because why an icon, and [ . . . ]

**Comment by MohammadLashkari** [comment]
Hi 
First, hide all explorer sections, such as open editors and outline. Once you've done that, you can add the following line to your settings:
``` json
"sideBarTitle.foreground": "#00000000"
```
This adjustment will make the header text transparent for you.

**Comment by pete-willard** [comment]
+1

**Comment by feliperdamaceno** [comment]
Thanks @MohammadLashkari, that worked perfectly!

**Comment by Curcii** [comment]
No official solution yet?

**Comment by uberubert** [comment]
I think the team uses the upvote feature to determine issue importance, so add an upvote to the op.

When the "Explorer" title shows, it adds another row to the top of the explorer folder hierarchy. This seems pointless, since there's plenty space in the title area for the action buttons.

I tried the css trick, which hides the text. Neat. Now the extra height space is even more pointless.

**Comment by whaaaley** [comment]
There is a semi-official solution @Curcii

![image](https://github.com/microsoft/vscode/assets/7419947/4fcc335e-75cd-4365-87b4-374ddd674165)

First if you click these three dots, you can uncheck each icon:
![image](https://github.com/microsoft/vscode/assets/7419947/b4e101db-b8e9-40f1-922c-a93f58001aeb)

Next, in your settings.json add this color customization:
```
  "workbench.colorCustomizations": {
    "sideBarTitle.foreground": "#00000000"
  }
```

**Comment by silverwind** [comment]
All we need is a boolean option that does this:

```css
.sidebar > .title {
  display: none;
}
```

**Comment by AuracleTech** [comment]
Why is this issue closed

**Comment by silverwind** [comment]
For anyone feeling adventurous, I have [this custom CSS](https://github.com/silverwind/tmtheme/blob/1e5c60c13712a009c47c2ac22dc28b00657549eb/custom.css#L48-L71) that gets rid of the explorer header. It has a unresolved issue in that it leaves a tiny bit of empty space below the file list, but that doesn't bother me too much currently.

<img width="252" alt="image" src="https://github.com/microsoft/vscode/assets/115237/cdc384a7-ca10-4106-bff3-0badc1a7a90c">

**Comment by AuracleTech** [comment]
> For anyone feeling adventurous, I have below custom CSS 

I'm pretty sure CSS isn't supported by vscode for years now

**Comment by silverwind** [comment]
> > For anyone feeling adventurous, I have below custom CSS
> 
> I'm pretty sure CSS isn't supported by vscode for years now (Or else this wouldn't be an issue)

It is still possible with certain extensions.

Thought, CSS can only go so far when everything relies on inline styles with`height` and the virtualized file list being non-flexible in terms of CSS. I don't think a clean CSS-only solution is possible, it has to be done on JS level.

**Comment by Curcii** [comment]
Thanks @whaaaley! That looks much cleaner! I hope there will be option to hide the empty space as well.

**Comment by chertik77** [comment]
> Is it possible to remove the "EXPLORER:" text when a folder is open, and only show the folder name there? Prepending the "EXPLORER:" makes it hard to see the folder name at a glance without extending the sidebar into the working space.

Is there any update on this? 🥲

**Comment by dannypernik** [comment]
Used `"sideBarTitle.foreground": "#00000000"` as suggested by @MohammadLashkari and [Apc customize UI extension](https://marketplace.visualstudio.com/items?itemName=drcika.apc-extension) with the following to move the header up and in line with the minimap:

```
"apc.sidebar.titlebar": {
    "height": 30
  },
```

![image](https://github.com/user-attachments/assets/f69cf789-88c2-4d95-bfc1-795b8546dace)
