### ISSUE TITLE
Theme colours are not maintainted with different instances and screen size

### ISSUE THREAD

**Issue by tadywankenobi** [Microsoft/vscode#62597]
Issue Type: <b>Bug</b>

I have Code set to open in full screen view. I use the "Dark+ (default dark)" theme on Windows 10 desktop.

For whatever reason, more often than not, the text appears black on grey. I don't seem to be aboe to find a setting to over-ride this. It's highly annoying and makes using the dark mode hard to work with. Screenshot: https://www.dropbox.com/s/pc28ayxklb4pg7l/vs-dark-bug.jpg?dl=0

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz (4 x 3504)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (7.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
gitlens|eam|8.5.6
php-debug|fel|1.12.6
php-intellisense|fel|2.3.5
php-pack|fel|1.0.2
minify|Hoo|0.3.0
mssql|ms-|1.4.0
cpptools|ms-|0.20.1
team|ms-|1.142.0
LiveServer|rit|5.1.1

</details>

**Comment by tadywankenobi** [comment]
It is not related to the macOS Mojave dark theme issue

**Comment by kieferrm** [comment]
This is the screenshot from the original description:

![image](https://user-images.githubusercontent.com/4674940/48035146-63d1ee80-e117-11e8-862d-8aaa96eb049d.png)

**Comment by kieferrm** [comment]
@tadywankenobi do you have any value specified for `workbench.colorCustomizations` in your settings?

**Comment by tadywankenobi** [comment]
Hi folks, sorry I've not logged a bug like this before. Apologies for not including enough info.

As per the Contribution guidelines:

- I'm on: 
Version: 1.28.2 (user setup)
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:23:51.859Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

- I have the following Extensions enabled:
Azure Repos
C/C++ Intellisense
GitLens
Live Server
minify
PHP Debug
PHP Extension Pack
PHP IntelliSense
SQL Server (mssql)

- Reproducible steps:
 1. Not much to indicate here. I open VS Code and text colours do not correspond to the dark theme and are difficult to read

- Actual v Expected:

Actual:
![image](https://user-images.githubusercontent.com/615588/48073252-a6123300-e1de-11e8-802e-b21aa2e56fe3.png)

Expected:
![image](https://user-images.githubusercontent.com/615588/48073275-b3c7b880-e1de-11e8-9de0-49fafd2426f4.png)
(Extensions text on left nav. Achieved by hovering when taking screenshot)

@kieferrm to answer your questions, my workbench.colorCustomizations settings are 100% empty:

![image](https://user-images.githubusercontent.com/615588/48073480-25076b80-e1df-11e8-9b0a-e1cd3f56e9ab.png)

I have toggled open the Developer Tools and added a color: #fff to the .monaco-shell class, which appears to rectify the issue. I'm not sure if I should add this somewhere else though, so that this class doesn't get over-ridden again later.

- Console error: there are no console errors in the Developer Tools

I have attached my settings.json file here (in txt format).
[settings.txt](https://github.com/Microsoft/vscode/files/2553701/settings.txt)

These are my personal settings:

`{
    "files.associations": {
        "window.newWindowDimensions": "maximized",
        "*.master": "csharp",
        "*.asp": "vb"
    },
    "php.validate.executablePath": "C:\\xampp\\php\\php.exe",
    "breadcrumbs.enabled": false,
    "liveServer.settings.donotShowInfoMsg": true,
    "git.autofetch": true,
    "tfvc.location": "C:\\\\Program Files (x86)\\\\Microsoft Visual Studio 14.0\\\\Common7\\\\IDE\\\\TF.exe",
    "team.showWelcomeMessage": false,
    "workbench.colorTheme": "Visual Studio Dark",
}`

(I don't have too many, but if I can add something to them to fix this, I'd be happy to)

Even accessing the settings panel, I have the same issue. When I hover over the text, they go white. I'm at a loss as to what the issue is or if there's some conflict I'm missing.

![image](https://user-images.githubusercontent.com/615588/48072921-df966e80-e1dd-11e8-87ba-0b65a5f96021.png)

That enough?

**Comment by chrmarti** [comment]
@tadywankenobi You're using the `Dark` theme, does this reproduce also with the `Dark+` theme?

**Comment by tadywankenobi** [comment]
@chrmarti Yes it does. I usually use the Dark+ theme.

**Comment by tadywankenobi** [comment]
I've been playing with adding `"workbench.colorCustomizations": {}` settings but can't find one that adds just a simple white to the .monaco-shell class

**Comment by chrmarti** [comment]
@tadywankenobi Does it reproduce when launching with `code --disable-extension` (or the command `Reload Window with Extensions Disabled` from the command palette)?

**Comment by tadywankenobi** [comment]
@chrmarti It does. Just tested.

**Comment by tadywankenobi** [comment]
I also tested by removing all my user settings (cut the contents) and still the same.

**Comment by tadywankenobi** [comment]
Is there some file I can delete or something?

**Comment by chrmarti** [comment]
Still a puzzle. You could remove local storage from your user data dir and see if that fixes it. That would also remove any other customizations in local storage, but usually isn't too bad. Or you could check what 'colorthemedata' is set to in local storage and delete that (it's just a cache):
![image](https://user-images.githubusercontent.com/9205389/48114942-545ebc80-e261-11e8-882c-24de28345ec1.png)

**Comment by tadywankenobi** [comment]
No joy. Not sure at all what to do. Is deleting all localStorage data risky?

**Comment by chrmarti** [comment]
It shouldn't be risky, extensions might remember some answers you gave by pressing buttons on message boxes, these you will need to provide again. You could start by backing up your user data dir and then delete the local storage (or just rename its subfolder).

**Comment by tadywankenobi** [comment]
Completely emptying the cache did nothing. If you can tell me where the Data directory is, I'll delete remove that and see if it helps.

**Comment by chrmarti** [comment]
It's in `~/Library/Application\ Support/Code`. Try renaming the `Local Storage` folder there.

**Comment by tadywankenobi** [comment]
Sorry, on a PC

**Comment by tadywankenobi** [comment]
@chrmarti Any indication where this is on Windows?

**Comment by chrmarti** [comment]
It's in `AppData\Roaming\Code` of your user directory.

Somehow thought you were on Mac.

**Comment by tadywankenobi** [comment]
No joy. Have uninstalled. Will try a clean install.

**Comment by tadywankenobi** [comment]
Ok, I don't understand this. I've uninstalled all extensions, uninstalled code, deleted the code folder, downloaded latest version, rebooted, installed and still...

![image](https://user-images.githubusercontent.com/615588/48197055-b9470f00-e354-11e8-9534-384536250df1.png)

I'm at a loss.

**Comment by tadywankenobi** [comment]
(You'll notice there are no chrome icons either in the top right, e.g. Close, minimize, hide)

**Comment by tadywankenobi** [comment]
I've gone into the workbench.main.css and added a colour to .monaco-shell and it has fixed the issue. I'm assuming next time I update Code I'll lose this change though...

**Comment by tadywankenobi** [comment]
For the record, it's not perfect... But at least I'm not squinting and looking for black links on dark grey any more. It would appear to me that in the dark theme, there are fallback expectations that are not precise. The cascade does not appear to be correctly picking up the implicit font colour so it looks like it needs to be explicitly declared.

**Comment by tadywankenobi** [comment]
On further investigation, it appears the the dark theme json files are not being loaded. There are no overrides from the base theme kicking in. Can anyone offer any insight as to how to resolve this?

**Comment by chrmarti** [comment]
Reinstalling won't clean your `AppData\Roaming\Code`. You said that using a new user data dir helped. So you could:
- close Code
- rename your `AppData\Roaming\Code` folder
- start Code
- copy your old settings.json from the renamed folder to the newly created `AppData\Roaming\Code` folder

If you could keep a copy of your old `AppData\Roaming\Code`, our experts on this matter might be interested in learning more from it when they are back from vacation.

**Comment by tadywankenobi** [comment]
@chmarti I did all this. When I uninstalled and reinstalled, I renamed the Code folder and immediately after install, it was still the same. I’m at a complete loss.

**Comment by tadywankenobi** [comment]
@chrmarti For info, I manually removed all extensions, removed the app, removed the Roaming > Code folder, rebooted and then reinstalled. I immediately had the same problems. I’ve switched to a light theme so I can work but it’s a pain in the ass.

**Comment by aeschli** [comment]
looks like the css issue we looked at with @bpasero

**Comment by chrmarti** [comment]
@tadywankenobi Could you check if this is fixed in the latest insiders builds: https://code.visualstudio.com/insiders/ ?

**Comment by chrmarti** [comment]
/duplicate #60298

Thanks @tadywankenobi .
