### ISSUE TITLE
Chinese input cannot be displayed in the terminal

### ISSUE THREAD

**Issue by Hideer** [Microsoft/vscode#62598]
- VSCode Version: 
版本: 1.28.2 (system setup)
提交: 7f3ce96ff4729c91352ae6def877e59c561f4850
日期: 2018-10-17T00:23:51.859Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
架构: x64
- OS Version:

Steps to Reproduce:

1. when i use chinese in terminal ,but it show abnormality
2.
![image](https://user-images.githubusercontent.com/31301552/48004014-0061b400-e14b-11e8-9de4-cc339a8fff89.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jerch** [comment]
@Hideer Can you check if #60717 solves it?

**Comment by kieferrm** [comment]
The fix for #60717 is in the latest insider and will be in 1.29 due later this week.

**Comment by Hideer** [comment]
regretful！ when i see #60717 error,and i use configuration.
for example 
```
"terminal.integrated.env.windows": {
    "LANG": "C.UTF-8"
  },
```
but, It didn't solve my problem

**Comment by Hideer** [comment]
oh! ,i set it configuration ,must reload project
now i solve problem 
thanks!

Happy Coding!
