### ISSUE TITLE
Typing brackets while text is selected

### ISSUE THREAD

**Issue by thany** [Microsoft/vscode#62595]
Issue Type: <b>Bug</b>

When text is selected (and, arbitrarily, only then) typing the `{` character actually puts `{` and `}` around the selection.

The expected behaviour is that selected text will always be replaced by what is typed on the keyboard. Please restore this behaviour, because this is what I expect.

The current behaviour takes me off my flow, by inadvertently placing too many brackets.

What I normally do: I want to replace a passage of text by a variable of some sort, so I select that text and literally type: `{` `{` `}` `}` `arrow left` `arrow left` `v` `a` `r`
This turns the selected text into `{{var}}}}`. I never typed four closing brackets, so that's why this behaviour is highly undesirable for me.

I didn't find a way to disable it in the settings. There is also no keyboard mapping for the `{` character, even though there *is* special behaviour associated with it. That seems like a whoopsie... A hardcoded key mapping. It's also not an extension causing the behaviour described, afaik.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.74GB (16.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
Bookmarks|ale|9.1.0
html-class-suggestions|And|1.0.7
color-info|bie|0.5.0
mustache|daw|1.1.1
vscode-eslint|dba|1.7.0
vscode-babel-coloring|dza|0.0.4
EditorConfig|Edi|0.12.5
file-icons|fil|1.0.16
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
duplicate|gee|1.0.1
svgeditor|hen|2.7.0
beautify|Hoo|1.4.7
docthis|joe|0.7.1
vscode-duplicate|mrm|1.2.1
vscode-docker|Pet|0.3.1
code-settings-sync|Sha|3.2.0
rewrap|stk|1.9.1

</details>

**Comment by usernamehw** [comment]
`"editor.autoSurround": "never",` ?

**Comment by kieferrm** [comment]
Pls see 
![image](https://user-images.githubusercontent.com/4674940/48033424-19993f00-e110-11e8-937d-9867017fb6b5.png)

**Comment by thany** [comment]
Works.

Why can I not find this settings when I search for "brackets" in the settings? It looks like it should be able to find it, since brackets in one of the possible options.

The fact that I report this as an issue, should be a telltale sign that the preferences pane might not provide enough hints towards this option, since I did look for it...
