### ISSUE TITLE
Change All Occurrences on folded/collapsed sections

### ISSUE THREAD

**Issue by Xiltch** [Microsoft/vscode#6259]
- VSCode Version: 1.0.0
- OS Version: Windows 7 Enterprise Service Pack 1
Steps to Reproduce:

VB file type

1. Have some of the target items that would be changed in a section folded/collapsed and not visible
2. Select the keyword and trigger 'Change all Occurrences'
3. Make your change
4. Keyword in the folded section is not changed but instead the new keyword is on the topmost line of the folded/collapsed section

**Comment by aeschli** [comment]
@Xiltch Do you have a small code example where I can see this? I just tried some random examples where I renamed some variables that where folded away and didn't see any strange effects.

**Comment by aeschli** [comment]
Closing. Please reopen with an example.
