### ISSUE TITLE
Add option to flatten directory trees that contains only a subfolder

### ISSUE THREAD

**Issue by V-ed** [Microsoft/vscode#62603]
**Issue type** : Feature Request

I propose to add an option to flatten the directory tree when folders contains only a subfolder.

To give an example, GitHub does it like so :
![image](https://user-images.githubusercontent.com/16652915/48006063-f73cfc80-e0e2-11e8-9535-5391a852592b.png)

This feature exists in IntelliJ IDEA too :
![image](https://user-images.githubusercontent.com/16652915/48021311-3b8dc400-e106-11e8-93fd-3345d6c7f2f3.png)

This is not really what I personally find beautiful to look at and moves everything with alot of indentation, making long class names under low level folders harder to read :
![image](https://user-images.githubusercontent.com/16652915/48007621-040f1f80-e0e6-11e8-93a9-a0de4c656d37.png)

This would preferably be under an option, probably disabled by default to not dramatically change how we are used to the tree layout.

---

One thing to keep in mind if this feature gets to be worked on is the way right clicks would interact with "shrunken down folders" :

In IntelliJ IDEA, it acts like a right click on the most low level folder (in the picture of GitHub above, right clicking on _test/java/io/[...]_ would be like right clicking on the final **_vramework_** folder)
- While logical, I sometimes find myself wanting to create a folder in one of the middle level folders, in the same example would in the **_vhoyon_** subfolder (think of when creating the Unit Tests for a new project, creating all the folders is more tedious when you don't have access to the middle level folders directly), and going the route of IntelliJ makes it harder for me for such use case

Therefore, I propose to deal with "shrunken down folders" like IntelliJ does (right clicking means right clicking on the lowest level folder), but having _another_ option to select which folder to put the right click event onto :
![image](https://user-images.githubusercontent.com/16652915/48007376-76cbcb00-e0e5-11e8-9fc6-2b47b368e8a1.png)
, option which would bring up a dropdown of some sort to select which middle level folder would be selected.

I'll be honest, I'm not sure which workflow would be the best in that case for selecting a middle level folder, but having an option similar to this would greatly be appreciated compared to IntelliJ IDEA.

**Comment by V-ed** [comment]
@isidorn I searched for such issue but couldn't find one, possibly I didn't use the right search terms, can I get the issue number so I can go follow it there?

**Comment by isidorn** [comment]
Search for issues tagged with label file-explorer and label feature-request and you will find it sooner or later

**Comment by V-ed** [comment]
Found it here : #41627

@isidorn , it would be great if you linked the issue when you find yourself a duplicate. The same happened over #41627, and it wasn't even a duplicate as further explanations concluded.

It's infuriating when people don't search if similar issues are already opened and I get that, but sometimes we search and don't use the proper terms, leading to thinking it wasn't already asked.

Simply slapping a duplicate label gives me no clue to where to search for such "duplicate" issue.
(oh and I'm not saying that the duplicate label shouldn't be used, but rather that the way of finding the issue would be very appreciated if known - directly linking it even better)
