### ISSUE TITLE
Add horizontal scroll bar for build messages and in debugger windows

### ISSUE THREAD

**Issue by dougbu** [Microsoft/vscode#6260]
- VSCode Version: 1.1.0
- OS Version: Windows 8.1
 - C# extension used in some screen shots below: [`v1.0.5-rc2`](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.0.5-rc2)

##### Steps to Reproduce:
1. Show Errors and Warnings in a project with a few of each.

or

2. Stop at a breakpoint in a project using long-named classes or with a deeply-nested property hierarchy. 

##### Notes
Highlighting on hover only goes so far in a few more places than #5580 covers...

###### Build messages
Note these messages can only be seen in full affter opening the offending file.
![unwrappederrors](https://cloud.githubusercontent.com/assets/6431421/15157544/f99d0ce0-16a0-11e6-8edc-19a2742ea2c6.png)

###### Call stack at breakpoint
This particular view might be improved if the stack showed `{method}, {namespace-qualified class}` or `{class.method}, {namespace}`.
![unwrappedcallstack](https://cloud.githubusercontent.com/assets/6431421/15157553/0354c8d6-16a1-11e6-93e5-9da3a69f4365.png)

###### Deeply nested variables
![unwrappedvariables](https://cloud.githubusercontent.com/assets/6431421/15157557/06ce53ec-16a1-11e6-9ad2-d5f8bd6c529a.png)

**Comment by isidorn** [comment]
Build errors layout we are changing thus forwarding this to @sandy081
Debug horizontal scroll bar is not on the current plan, for inspecting such nested variables you can evaluate them in the repl which should give more space. Though I agree we should think about adding a horizontal scroll bar

**Comment by sandy081** [comment]
I am closing this as duplicates #6679 if this issue is specific to errors and warnings. Otherwise, please reopen this for a particular issue/usecase.

Refer to #6679 for updates on problems panel
