### ISSUE TITLE
Add APIs on vscode.git extension to support rich reviews in collaboration session

### ISSUE THREAD

**Issue by IlyaBiryukov** [Microsoft/vscode#62609]
Issue Type: <b>Feature Request</b>

Hi,

I'm working on supporting rich reviews in live share collaboration session. To support that, we'd need the following APIs:

1. `Repository.getGlobalConfig(key: string): Promise<string>`
1. `Repository.getLog(options?: GitLogOptions): Promise<Commit>`
1. `Repository.diffWorkingDirectoryWith(ref: string): Promise<Change[]>`
1. Add `interface GitLogOptions {	readonly maxEntries?: number; }`
1. Add `readonly authorEmail?: string | undefined;` to `Commit` interface.

I have changes ready and can submit a PR if you accept this feature request.

**Comment by IlyaBiryukov** [comment]
cc @joaomoreno

**Comment by joaomoreno** [comment]
@IlyaBiryukov Sounds good. Some questions:

- Does `getLog` return a single `Commit`?
- Should we overload `diffWith` to return `Change[]` if no path is provided, instead of creating `diffWorkingDirectoryWith`?

**Comment by IlyaBiryukov** [comment]
Good points. `getLog` should return an array, `Commit[]`.
Using `diffWith` with no path is fine too. Though then it would be returning either a string (if called with path) or `Change[]`. If this is OK, then I'm fine with that.

**Comment by IlyaBiryukov** [comment]
Are you fine with me sending out a PR for this bug? I have a fix ready.

**Comment by joaomoreno** [comment]
Sure, send a PR for this feature.

**Comment by joaomoreno** [comment]
@IlyaBiryukov Note that we just entered November endgame, meaning: today is the last day I could merge said PR. Else, we're going to have to merge this in December.

**Comment by IlyaBiryukov** [comment]
I'll try to send it out today. Also December is fine.
