### ISSUE TITLE
Right click menu is incomplete

### ISSUE THREAD

**Issue by GentlemanHu** [Microsoft/vscode#62601]
- VSCode Version:1.28.2
- OS Version:Win10 1809

Recently I found that the right-click menu is incomplete.
I think its because too many menu items cannot be automatically paged.

![no](https://user-images.githubusercontent.com/34559079/48005796-559fc480-e14f-11e8-99e1-80df4cf90e4e.png)

**Comment by sbatten** [comment]
duplicate of https://github.com/Microsoft/vscode/issues/52533
