### ISSUE TITLE
Crash in Code Insiders MacOS on launch

### ISSUE THREAD

**Issue by zackkrida** [Microsoft/vscode#62608]
Latest downloaded insiders build crashes immediately. 

- VSCode Version: 1.29.0-insider
- OS Version: MacOs Mojave 10.14 (18A391)

Steps to Reproduce:

1. Install vscode 1.29.0-insider
2. Attempt to open

Does this issue occur when all extensions are disabled?: Yes

**Comment by zackkrida** [comment]
```bash
❯ ci --disable-extensions --verbose
[55091:1105/144446.881663:WARNING:dns_config_service_posix.cc(156)] dns_config has unhandled options!
[main 2:44:47 PM] Sending env to running instance...
[main 2:44:47 PM] Sent env to running instance. Terminating...
[main 2:44:47 PM] Lifecycle#kill()
```

**Comment by kieferrm** [comment]
@zackkrida pls have a look at #60041.

**Comment by zackkrida** [comment]
@kieferrm #60041 took care of it—thank you.
