### ISSUE TITLE
VSCode autoupdate should not occur over metered connection

### ISSUE THREAD

**Issue by fatherjack** [Microsoft/vscode#62615]
There are similar issues which have been closed with no adequate reason. 
see

https://github.com/Microsoft/vscode/issues/60741
VSCode should respect the Metered Connection flag on Windows, and not download updates #60741

https://github.com/Microsoft/vscode/issues/8540
Respect metered connections on Windows 10 #8540

If this issue has been addressed in an insiders build then please advise and I will gladly test

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. connect via connection that is marked as a metered connection
2. start vscode that is a version or more behind with auto update enabled

Does this issue occur when all extensions are disabled?: Yes/No
yes

as mentioned above there are two other issues linked to this bug that have been closed previously, one by a bot and one with no explanation of why it wasnt at least kept open as a recognised issue with the application. I think we deserve better detail than "I'm abandoning this idea, various reasons.".

**Comment by kieferrm** [comment]
@fatherjack we closed those issues as out-of-scope as we have no plans in the address them in any reasonable timeframe. PRs welcome.
