### ISSUE TITLE
Portrait Mode with Zen Mode

### ISSUE THREAD

**Issue by jpandey2** [Microsoft/vscode#62616]
Issue Type: <b>Bug</b>

Side Bar gets cut off if it is opened in Portrait Mode Zen Mode (for example by pressing Ctrl+Shift+F)

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz (12 x 3398)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.91GB (23.85GB free)|
|Process Argv|C:\P4\jp-Final_TOT\sw\rel\gpu_drv\r415\r415_00\drivers\display\lddm\nvlddmkm|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.20.1

</details>

**Comment by tomkcook** [comment]
I'm not sure it's related, but zen mode does produce fairly perverse results by default when used on a high-aspect-ratio screen that's in portrait orientation (ie with its long axis vertical).  I end up with an editor that's about 40 characters wide.  Perhaps it'd make sense to set a minimum width (in characters) for an editor to span before centering is enabled?

I'd suggest 80 or 100 characters as a sensible minimum.

**Comment by isidorn** [comment]
@jpandey2 Screenshoot needed. Thanks
