### ISSUE TITLE
All suggest icons are small when setting a "big" font

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#62618]
Issue Type: <b>Bug</b>

Icons are way too small now. Is it possible to have them the same size as before?:

| Stable  | Insiders |
| ------------- | ------------- |
| ![before](https://user-images.githubusercontent.com/9638156/47603611-38545300-d9f7-11e8-9b1b-4ea58bde0c1e.png) | ![after](https://user-images.githubusercontent.com/9638156/47603613-4013f780-d9f7-11e8-8e54-b7b175397edd.png) |

```json
"editor.suggestLineHeight": 40,
"editor.suggestFontSize": 20,
```

VS Code version: Code - Insiders 1.29.0-insider (bdfe4fd41f6a5fe538197b3cba937230249a563a, 2018-11-04T13:04:20.759Z)
OS version: Windows_NT x64 10.0.17134

**Comment by jrieken** [comment]
This should be better with "normal" icons but is still a challenge with theme icons. Leaving that to @aeschli

**Comment by aeschli** [comment]
If I remember right, the size of the theme icons would be controlled by the css we generate.
There are no size requirements to the providers of theme icons.

@jrieken Not clear to me what I can/should do here.
