### ISSUE TITLE
Allow to show buttons when showing progress

### ISSUE THREAD

**Issue by jeffreymew** [Microsoft/vscode#62612]
Looking to add a "View Output" button on the Azure App Service Extension progress location but there doesnt seem to be API for having buttons in the Notification window for ProgressLocation.

Example: The "View Output" button in the screenshot below.

![image](https://user-images.githubusercontent.com/43653065/48020314-83065700-e0ea-11e8-84af-8f1248dd05a8.png)

Jeffrey Mew
Program Manager for VS Code

**Comment by eamodio** [comment]
This looks like a duplicate of: https://github.com/Microsoft/vscode/issues/60979
