### ISSUE TITLE
Use a auto-fix will result a new buffer being created

### ISSUE THREAD

**Issue by xbtsw** [Microsoft/vscode#62617]
Issue Type: <b>Bug</b>

Open a TS file with an auto-fix available.
Apply the auto-fix.
Current buffer will be modified, but a new buffer with identical content will be created.

VS Code version: Code - Insiders 1.29.0-insider (bdfe4fd41f6a5fe538197b3cba937230249a563a, 2018-11-04T13:04:20.759Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2123 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.73GB (17.73GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.0.22
EditorConfig|Edi|0.12.5
prettier-vscode|esb|1.6.1
PowerShell|ms-|1.9.0
sort-lines|Tyr|1.7.0
vim|vsc|0.16.12

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
In VS code, click on the file name of each editor and run `copy file path`. Are the two paths exactly the same, including case? Or are they different?

**Comment by xbtsw** [comment]
@mjbvz I checked the two path, they are exactly the same, including case.

**Comment by xbtsw** [comment]
Just to close the loop it now works as expected in
```
Version: 1.29.0-insider (user setup)
Commit: 5f24c93878bd4bc645a4a17c620e2487b11005f9
Date: 2018-11-10T00:34:03.196Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```
