### ISSUE TITLE
Less obnoxious CSS color previews

### ISSUE THREAD

**Issue by 0matgal0** [Microsoft/vscode#62611]
Currently they look like this:
![image](https://user-images.githubusercontent.com/18264503/48020029-3136ee80-e135-11e8-9049-39343da7e318.png)

Here's how they look with a vim plugin (imho better than putting in additional non existing text / graphic into the file view):
![image](https://user-images.githubusercontent.com/18264503/48020151-74915d00-e135-11e8-85d6-0dcbb815f4be.png)

**Comment by usernamehw** [comment]
https://marketplace.visualstudio.com/items?itemName=naumovs.color-highlight

**Comment by 0matgal0** [comment]
This disables them completely, which is not what is shown on the second screenshot.

**Comment by usernamehw** [comment]
Did you install the extension I linked?

**Comment by 0matgal0** [comment]
Ahh, yes, I see now. Would be nice to have this baked in, but that will do. Thanks.
