### ISSUE TITLE
F5 to start debugging not working with Extension debugging

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#6261]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Use yo code to generate a Code extension (Javascript)
2. Open the extension folder
3. Navigate in Explorer to extension.js and open it (you can make changes, but it is not necessary)
4. Press F5

Nothing happens. It works before opening extension.js but after the key just doesn't work to start debugging.

**Comment by isidorn** [comment]
Can not repro on win10 neither on mac.
Are you still seeing this, if yes can you start debugging by clicking on the green play icon?
Can you start debugging if you bind some other keybinding to start debug action?
