### ISSUE TITLE
Freeze / long time to respond

### ISSUE THREAD

**Issue by wasinwill** [Microsoft/vscode#62621]
Issue Type: <b>Bug</b>

Nothing to do in particular to reproduce. VS Code would randomly slow down and freeze for a minute or two when trying to select a word or type code. CPU usage peaks while I only have VS Code, Chrome and XAMPP running.

When VS Code freezes, other programs are fully usable and responsive.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (4 x 3498)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (11.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-close-tag|for|0.5.6
vscode-apache|mrm|1.1.1
mssql|ms-|1.4.0
highlight-matching-tag|vin|0.8.1

</details>

**Comment by wasinwill** [comment]
Issue doesn't seem to reproduce on Insiders and never occurred before the last VS Code update if I remember correctly.

**Comment by wasinwill** [comment]
![capture](https://user-images.githubusercontent.com/44789688/48033027-ad2a3a00-e127-11e8-90f3-69328c55383f.PNG)

Taken right before VS Code crashed

**Comment by kieferrm** [comment]
Here are some tips: https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by wasinwill** [comment]
Thanks. I will report when it happens again.

**Comment by edin-coralic** [comment]
Same problem here. Also my coworker has same issue... Random freezes with CPU rising.

**Comment by edin-coralic** [comment]
> What extensions do you have installed?

```
$ code --list-extensions
cstuder.gitlab-ci-validator
EditorConfig.EditorConfig
hollowtree.vue-snippets
kumar-harsh.graphql-for-vscode
mauve.terraform
mikestead.dotenv
ms-python.python
ms-vscode.Go
tht13.python
xyz.local-history
```

**Comment by wasinwill** [comment]
So I opened the Process Explorer when VS Code started to slow down. All processes are pretty much idle, and peak at 7-8% when I highlight some code. After a while, it started to slow down and as soon as I would select a word or a line, the same process shown in the screenshot below would peak at 30%+ CPU usage.

If I reload VS Code, it goes back to normal so I couldn't test disabling the extensions. I'm now running it with all extensions disabled and will report if it slows down again.

![untitled-1](https://user-images.githubusercontent.com/44789688/48236980-a3f0d580-e392-11e8-8e55-2c46674bc03c.png)

**Comment by rodmax** [comment]
It seems i have the same issue. All working fine first 5-10 minutes but then start freezing

> Are you running webpack or some other build tool when this happens?
@chrmarti  If it helps somehow, I use webpack(angular application on work pc and webpack+typescript react application at home) on both machines i observe exactly the same as described in this report issue
