### ISSUE TITLE
Uri: Support opening internal URIs via 'vscode.open'

### ISSUE THREAD

**Issue by akaroml** [Microsoft/vscode#62629]
Source issue: Microsoft/vscode-java-pack#54

I'm trying to use `vscode.commands.executeCommand('vscode.open', uri)`. This works fine for `https` uris. But it has problem with uris like `vscode:extension/k--kato.intellij-idea-keybindings`. Here’s the error message:

> Unable to open 'k--kato.intellij-idea-keybindings': resource is not available.

I used this to allow users to install an extension without leaving vscode. Is there any alternative or can we whitelist `vscode` resource type?

**Comment by joaomoreno** [comment]
@jrieken Our internal URL handlers return whether they've handled the URI or otherwise. Maybe we can let them have a go and finally let it go to the OS, if none handled it?

**Comment by jrieken** [comment]
Ok, can you then wire them into the `OpenerService`?

**Comment by KamasamaK** [comment]
The use case for opening an extension page is addressed with #58642.
