### ISSUE TITLE
[less] How to eliminate marks of the less term expected？

### ISSUE THREAD

**Issue by anyclub** [Microsoft/vscode#62627]
- VSCode Version: 1.28.2
- OS Version:win10 64

 https://github.com/Microsoft/vscode/issues/43087

`"less.validate": false `dont work

![tim 20181105101710](https://user-images.githubusercontent.com/19922265/47974426-8565b280-e0e4-11e8-8fed-f911239c79cd.png)

**Comment by octref** [comment]
You need to wait for Vetur extension to update its css-language-service dependency.
