### ISSUE TITLE
[Latest alpha] Having to save twice

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#6262]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Open a js or json file
2. Modify something (or just retype something to dirty the file)
3. Save

After saving, the file is still dirty. It looks to be doing some formatting after saving which is dirtying the file again. 

This behavior looks to be introduced in today's alpha only.

**Comment by bpasero** [comment]
![untitled](https://cloud.githubusercontent.com/assets/900690/15170515/c041de84-1746-11e6-928e-0ebfdd9d3320.gif)

Not reproducible for me, this needs more steps or info.

**Comment by vsccarl** [comment]
Looks like it is a result of the [JS-CSS-HTML formatter extension](https://marketplace.visualstudio.com/items?itemName=lonefy.vscode-JS-CSS-HTML-formatter). It does not repro with extensions removed.
