### ISSUE TITLE
Scrollbar in debug hover widget interferes with twisty

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#62631]
Issue Type: <b>Bug</b>

VS Code version: Code - Insiders 1.29.0-insider (bdfe4fd41f6a5fe538197b3cba937230249a563a, 2018-11-04T12:59:18.833Z)
OS version: Darwin x64 15.6.0

<img width="477" alt="screen shot 2018-11-05 at 3 54 36 pm" src="https://user-images.githubusercontent.com/16890566/48040838-722c0480-e12f-11e8-8674-95f9d7e0784c.png">

**Comment by ramya-rao-a** [comment]
Happens in Stable 1.28 as well

**Comment by isidorn** [comment]
https://github.com/Microsoft/vscode/issues/59452
