### ISSUE TITLE
Support IntelliSense suggestions in debug console

### ISSUE THREAD

**Issue by dougbu** [Microsoft/vscode#6263]
- VSCode Version: 1.1.0
- OS Version: Windows 8.1
- C# Extension:  [`v1.0.5-rc2`](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.0.5-rc2)

##### Steps to Reproduce:
1. Open a .NET Core application
2. Configure debugging
3. Set a breakpoint somewhere in the project
4. Start debugging (F5 etc.)
5. Type in debug console entry field

Expected: Prompts for properties of local variables and other suggestions.
Actual: No suggestions.

##### Notes
Relates to OmniSharp/omnisharp-vscode#299

As mentioned in that issue, the ability to expand objects in the debug console output window helps but isn't sufficient. For one thing, method calls aren't supported there.

**Comment by isidorn** [comment]
This is now supported on the vscode side. Once omnisharp-vscode picks up the api it should be fully working
