### ISSUE TITLE
Seti file icon theme - inconsistency with webpack icons

### ISSUE THREAD

**Issue by mmilanovic4** [microsoft/vscode#62636]
- VSCode Version: 1.28.2
- OS Version: Linux Mint 18.3 Sylvia (XFCE DE)

Steps to Reproduce:

1. Open `Settings` menu and set `Seti (Visual Studio Code)` to default file icon theme
2. Create new project with following files:
    - `webpack.common.js`
    - `webpack.config.js`
    - `webpack.dev.js`
    - `webpack.prod.js`

As you can see, `webpack.config.js` have different icon then other webpack files. It might make sense to use same icon for all `webpack.*.js` files.

![screenshot_2018-11-06_06-13-59](https://user-images.githubusercontent.com/24554925/48044596-ff517680-e18c-11e8-8182-55a31d5970b2.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by misolori** [comment]
This appears to have already been fixed by https://github.com/jesseweed/seti-ui/issues/516

<img width="228" alt="image" src="https://user-images.githubusercontent.com/35271042/66421866-86baf180-e9bd-11e9-8f85-def4050fb311.png">
