### ISSUE TITLE
Code hints (IntelliSense) always show loading

### ISSUE THREAD

**Issue by wang1212** [Microsoft/vscode#62633]
Since the update of vscode to 1.27, the code hints have slowed down. The code hint does not appear until the beginning of the previous time, and it is always displayed **'loading'** by pressing **Ctrl + Space**.

I uninstalled the vscode reinstall and still didn't solve it. 

My operating system is **win10(1803)**，the vscode version is **1.28.2**, I am in **China**.

**Comment by chrmarti** [comment]
What programming language is this? Have you installed an extension for that language?

**Comment by wang1212** [comment]
I found this because of the installation of the **vscode-flow-ide** extension.
