### ISSUE TITLE
Search string in folder not work for Chinese string but worked in open files

### ISSUE THREAD

**Issue by xzzh999** [Microsoft/vscode#62640]
Issue Type: <b>Bug</b>

As the title said, follow the steps:

1. prepare two files, a.cpp and b.cpp, both in the same folder, both include the strings "test" and "测试";
2. search "test" string in folder, no matter the two files open or closed, found them ok, worked;
3. only open a.cpp in editor, search "测试", just found one in a.cpp, not correct;
4. close all files in editor, search "测试", nothing found, not correct;

English seems always ok, other language not working.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (2.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.1.0
pascal|ale|6.4.0
project-manager|ale|9.0.1
code-gnu-global|aus|0.2.2
jshint|dba|0.10.20
vscode-eslint|dba|1.7.0
vscode-npm-script|eg2|0.3.5
code-runner|for|0.9.5
terminal|for|0.0.10
CppSnippets|har|0.0.13
output-colorizer|IBM|0.1.2
innosetup|idl|1.2.0
nsis|idl|3.15.0
Lua|key|0.0.9
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-language-pack-zh-hans|MS-|1.28.2
python|ms-|2018.9.2
azure-account|ms-|0.5.0
cpptools|ms-|0.20.1
csharp|ms-|1.17.0
Go|ms-|0.6.93
debugger-for-chrome|msj|4.11.0
makefiles-support-for-vscode|nae|0.0.3
vetur|oct|0.13.0
vscode-docker|Pet|0.3.1
java|red|0.33.0
preview-vscode|sea|1.4.6
code-settings-sync|Sha|3.2.0
vscode-hexdump|sle|1.7.0
easy-snippet-maker|tar|0.0.6
html-preview-vscode|tht|0.2.4
vscode-lua|tri|0.12.4
cmake|twx|0.0.17
vscode-java-debug|vsc|0.15.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.10.0
vscode-maven|vsc|0.11.1
vscode-mermaid-preview|vst|0.10.1
quokka-vscode|Wal|1.0.156
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.9.0
markdown-pdf|yza|1.2.0
markdown-all-in-one|yzh|1.7.0

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
If those files are not encoded in utf8, you will need to set the `files.encoding` to the proper encoding.

**Comment by xzzh999** [comment]
@roblourens 
if it is the ```files.encoding``` problem, why when i opened these files, i can searched them?

**Comment by roblourens** [comment]
When they are opened, they are actually saerched by the editor which can handle other encodings better.

**Comment by xzzh999** [comment]
@roblourens 
In my test case, a.cpp and b.cpp can mixed with ```utf8``` or ```gb2312``` encoding, and my vs code env default files encoding is utf8, open can search, closed can't search. If i search a string in a folder, i just want to search the string in all files no matter which file encoding it use.

**Comment by roblourens** [comment]
I understand the difficulty, but this isn't something that we are able to support right now.
