### ISSUE TITLE
Code indenting alone to save file.

### ISSUE THREAD

**Issue by GuiAlmeida** [Microsoft/vscode#6264]
- VSCode Version: 1.1
- OS Version: Windows 10 

Steps to Reproduce:

1. Open CSS
2. Modify
3. Save

After saving , indents alone, seems to be doing some formatting after is dirtying the file again.

**Comment by aeschli** [comment]
@GuiAlmeida My guess is that you have an extension installed that does something on save. The out-of-the-box VSCode doesn't do anything on save.
Can you reproduce the issue when starting vscode without extensions by using the `--disable-extensions` command line argument?

**Comment by aeschli** [comment]
Need more information. Closing...
