### ISSUE TITLE
Unable to debug with GDB

### ISSUE THREAD

**Issue by Dreace** [Microsoft/vscode#62647]
Issue Type: <b>Bug</b>

Appears when debugging with GDB
ERROR: Unable to start debugging. Unexpected GDB output from command "-exec-run".
There are some codes that have this problem and some have no such problem.
This is my code
```
#include <bits/stdc++.h>
using namespace std;
typedef struct Line {
    double left, right;
    Line(double a, double b) {
        left = a;
        right = b;
    }
} Line;
bool cmp(Line a, Line b) {
    return a.left < b.left;
}
int main() {
    int n, m;
    int cas = 0;
    while (cin >> n >> m) {
        if (n == 0 && m == 0) {
            break;
        }
        cas++;
        int res = 1;
        vector<Line> v;
        for (int i = 0; i < n; i++) {
            int x, y;
            double d;
            cin >> x >> y;
            if (y > m) {
                res = -1;
            } else {
                d = sqrt(m * m - y * y);
                v.push_back(Line(x - d, x + d));
            }
        }
        if (res == -1) {
            cout << "Case " << cas << ": " << res << endl;
            continue;
        }
        sort(v.begin(), v.end(), cmp);
        Line l = v[0];
        for (int i = 1; (unsigned)i < v.size(); i++) {
            if (v[i].left > l.right) {
                l = v[i];
                res++;
            } else {
                l = l.right < v[i].right ? l : v[i];
            }
        }
        cout << "Case " << cas << ": " << res << endl;
    }
    return 0;
}
```

VS Code version: Code - Insiders 1.29.0-insider (bdfe4fd41f6a5fe538197b3cba937230249a563a, 2018-11-04T13:04:20.759Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.92GB (3.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
include-autocomplete|ajs|0.0.4
code-runner|for|0.9.5
vscode-language-pack-zh-hans|MS-|1.29.1
cpptools|ms-|0.20.1
material-icon-theme|PKi|3.6.0
vscode-icons|rob|7.28.0

</details>

**Comment by chrmarti** [comment]
This issue was moved to Microsoft/vscode-cpptools#2778
