### ISSUE TITLE
Bring back window.smoothScrollingWorkaround

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#62644]
Refs: https://github.com/Microsoft/vscode/issues/13612

We have removed window.smoothScrollingWorkaround since the new windows update has the fix for this issue.
However we should give more time for users to update to the new windows and keep this setting for one more milestone.

Commit that needs reverting https://github.com/Microsoft/vscode/commit/d4dbfa3c29909e537646b75e6d166714c5f86052

**Comment by joaomoreno** [comment]
cc @bpasero

**Comment by isidorn** [comment]
Fixed via https://github.com/Microsoft/vscode/pull/62648
