### ISSUE TITLE
Difficult to use

### ISSUE THREAD

**Issue by niaiwomattt** [Microsoft/vscode#62641]
Issue Type: <b>Bug</b>

I am a web programmer, mainly using PHP, golang, js, HTML, but the PHP prompt of vscode is not very useful, golang is not a problem for the time being, JS in HTML files is difficult to use without any grammatical hints and plug-ins available, HTML tags are not displayed in pairs, and will not automatically. Close, hoping to improve.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (2.37GB free)|
|Process Argv|D:\www\mobile_www|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
toml|be5|0.0.3
vscode-intelephense-client|bme|0.8.8
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.60
elasticsearch-snippets|dan|0.1.2
vscode-markdownlint|Dav|0.21.0
jshint|dba|0.10.20
vscode-eslint|dba|1.7.0
gitlens|eam|8.5.6
php-debug|fel|1.12.6
php-intellisense|fel|2.3.5
php-pack|fel|1.0.2
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
align-mode|Gru|0.0.16
bracketselection|guo|1.0.3
beautify|Hoo|1.4.7
docthis|joe|0.7.1
vscode-phpfmt|kok|1.0.30
vscode-filesize|mkx|2.1.1
vscode-language-pack-zh-hans|MS-|1.28.2
python|ms-|2018.9.2
Go|ms-|0.6.93
vscode-auto-scroll|pej|1.0.2
subtle-brackets|raf|3.0.0
phpdoc-comment-vscode-plugin|rex|1.1.0
vscode-icons|rob|7.28.0
markdown-preview-enhanced|shd|0.3.11

</details>

**Comment by chrmarti** [comment]
Thanks for your feedback. Please file individual issues for each change you would like to see included.
