### ISSUE TITLE
Cannot type Ω

### ISSUE THREAD

**Issue by lionelvillard** [microsoft/vscode#62658]
- VSCode Version:  1.28.2
- OS Version: MacOS 10.13.6

Steps to Reproduce:

1. Type right-opt z

Does this issue occur when all extensions are disabled?: Yes

**Comment by lionelvillard** [comment]
right-opt z is assigned to Toggle Word Wrap. I wonder if this is possible to distinguish between left option key vs right option key

**Comment by chrmarti** [comment]
Have you tried unassigning Toggle Word Wrap in the keybinding editor?

**Comment by lionelvillard** [comment]
Yes this works.
