### ISSUE TITLE
HTML syntax highlight breaks with === and < on ng2 attributes

### ISSUE THREAD

**Issue by JulioC** [Microsoft/vscode#6265]
- VSCode Version: 1.1.0

![attributes](https://cloud.githubusercontent.com/assets/387794/15162352/c769ff48-16d8-11e6-9211-82b338d2b034.png)

```html
    Current behaviour:
    <div [class.selected]="i === selected"></div>
    <div [class.tooSmall]="value < threshold"></div>
    <div [class.tooBig]="value > limit"></div>

    Expected (to be like):
    <div *ngIf="i === selected"></div>
    <div *ngIf="value < threshold"></div>
    <div *ngIf="value > limit"></div>
```

I could offer a PR if anyone familiar with the vscode structure give me hints on where I should look for the issue.

**Comment by aeschli** [comment]
dupilcate of #5919

**Comment by JulioC** [comment]
I believe it's related, but not duplicated of https://github.com/Microsoft/vscode/issues/5919

The issue here is about [attribute values](https://www.w3.org/TR/html-markup/syntax.html#syntax-attribute-value).

**Comment by aeschli** [comment]
I tested that your example works with the fix for #5919.

**Comment by aeschli** [comment]
![image](https://cloud.githubusercontent.com/assets/6461412/15194247/47239ad4-17c2-11e6-83ae-79b35dece7bf.png)

**Comment by JulioC** [comment]
That's nice, thanks!
