### ISSUE TITLE
[themes] Color adjustments independent of themes

### ISSUE THREAD

**Issue by myuseringithub** [microsoft/vscode#62656]
Hi, many themes are exactly the same with a slight tweak to the contrast or brightness of colors. These themes are actually duplicates. I suggest adding `Color controls` that could adjust the common aspects of theme color presentation. 

### Color Adjustments settings: 
_Examples of adjustment options to consider:_
1. Contrast
2. Brightness
3. Sepia _- for whatever reason_
4. Grayscale
5. Vividness _- I think it could be adjusted using Contrast and Brightness_

These adjustments could be used:
1. Directly in the theme settings.
2. Externally in the VSCode settings - which is the main benefit of this suggested feature.

# Example of a similar suggested behavior:
_Using Dark Reader Chrome extension:_ Imagine the code text is in the image colors.
![d9nvnfpraz](https://user-images.githubusercontent.com/7758497/48066480-65aeb700-e1d6-11e8-856c-4e850e501940.gif)

# Example of unnecessary duplicate themes: 
- One dark pro - https://marketplace.visualstudio.com/items?itemName=zhuangtongfa.Material-theme
- One dark pro vivid - https://marketplace.visualstudio.com/items?itemName=kkozee.theme-one-dark-vivid

# Why ? 
Currently there is no way to adjust colors without dealing with the theme settings. 
- Color adjustments for themes allows to make them: Dimmed, Vivid, Grayscaled, etc. without dealing with the VSCode Theme API. 
- Dynamic color adjustments for themes depending on the computer screen being used or the brightness it self of the computer screen. This allows the same theme to fit better on different environments or just personal preferences.

Thanks 😍

**Comment by alexanderby** [comment]
Interesting suggestion. Since VS Code is built on Chromium, maybe there is a way to apply the extension to the whole app? Or maybe there is API to show popover and change theme colors dynamically?
