### ISSUE TITLE
Not able to scroll thru open editor tabs

### ISSUE THREAD

**Issue by zehawki** [Microsoft/vscode#62657]
Issue Type: <b>Bug</b>

This is an intermittent problem and I'm not able to find a pattern to reproduce reliably. But it happens often. When I have a bunch of tabs open, there is no way to scroll to the tabs that are outside the viewport. The only way to get to them is to use the overflow button which is supremely cumbersome. Further the last tab will usually have its close button outside the viewport. Clicking on the tab should bring the entire tab into focus, but that also doesnt happen.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (3.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
(1 theme extensions excluded)

**Comment by bpasero** [comment]
@zehawki when the mouse is over the tabs you can scroll left and right by scrolling with the mouse, does that not work?
