### ISSUE TITLE
Merge conflict code lens provider is artificially slow

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#62652]
Use steps in https://github.com/Microsoft/vscode/issue_comments#issuecomment-436213454 and notice how calling code lenses always takes 250ms plus some extra. All code lenses from all providers are awaited before showing them (to prevent flicker) which means this provider artificially slows things down...

**Comment by chrmarti** [comment]
@jrieken The link 404s, is the comment gone?

**Comment by chrmarti** [comment]
I think the delay is there for the decorations. Is the code lens provider called immediately after a document change?

**Comment by jrieken** [comment]
It must most likely this: https://github.com/microsoft/vscode/blob/2c063fa8544a8aac35d2f63ee24eabc7c8747a78/extensions/merge-conflict/src/documentTracker.ts#L66, e.g a delay of 250ms in some cases

**Comment by chrmarti** [comment]
@jrieken Is the code lens provider called immediately after a document change? (Asking to understand if I can just remove delay for the code lenses.)

**Comment by jrieken** [comment]
The code lens controller already debounces its request and therefore provider shouldn't do that
