### ISSUE TITLE
Renaming a file

### ISSUE THREAD

**Issue by tunedin76** [Microsoft/vscode#62661]
Issue Type: <b>Bug</b>

I do not know when the issue begins. However it seems to happen after you open, and change a file you can save it or not.

At that point you can no longer rename the file.  Once that happens, you cannot save any file whether it has been open or not.

It also might be a "time that VS Code has been running"..

If I click and ctrl-drop to copy, I get a file with a .1 in the name... only sometimes I cannot change that name. I am not sure I edited the file previously - either way it is saved and closed.

The problem ends when I restart VSCode

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.96GB (5.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
vscode-intelephense-client|bme|0.8.8
laravel-goto-view|cod|1.2.3
wpy-beautify|doi|2.0.10
vue-inline-template|fai|1.0.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vue-snippets-js-html-pug-razor|heb|0.0.3
vue|jcb|0.1.5
vscode-phpfmt|kok|1.0.30
vs-color-picker|lih|0.7.0
php-namespace-resolver|Meh|1.1.0
code-beautifier|mic|2.1.0
dotenv|mik|1.0.1
vetur|oct|0.13.0
indent-rainbow|ode|7.2.4
mysql-inline-decorator|odu|0.0.5
laravel-blade|one|1.18.0
material-icon-theme|PKi|3.6.0
tslint-vue|pro|1.5.6
format-html-in-php|rif|1.3.8
trailing-spaces|sha|0.2.11
bootstrap4-vscode|the|4.3.0
JavaScriptSnippets|xab|1.7.1

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Can you reproduce with vscode insiders
https://code.visualstudio.com/insiders/

**Comment by tunedin76** [comment]
Yes it happens in isiders

Blessings,
James Bailey
