### ISSUE TITLE
extensionService.activateByEvent should return even if some extension fails activation

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#62660]
1. Have some extension which fails to activate  on event `myevent` and crashes in its activation
2. 	Have the following code in vsocde
```
 this.extensionService.activateByEvent('myevent').then(() => console.log('hi'), err => console.log('err');
```
3. Notice that both code paths are not printed and the `activateByEvent` call does not return

**Comment by alexdima** [comment]
I think this has been fixed in the meantime. Here is what I have tried:
* `package.json`:
```
{
    "publisher": "alex",
    "name": "62660",
    "version": "0.0.0",
    "engines": {
        "vscode": "^1.0.0"
    },
    "activationEvents": [
        "special"
    ],
    "main": "index.js"
}
```
* `index.js`:
```
const vscode = require('vscode');

exports.activate = function (ctx) {
    console.log(`62660 activated!`);
    // throw new Error('an error!');
    return Promise.reject('an error!');
}
```

Then, somewhere in the renderer code:
```
this._extensionService.activateByEvent('special').then(() => console.log('hi'), err => console.log('err'));
```

I have tried both variants, of return a rejected promise and throwing an error. In both cases I see `hi` printed.
