### ISSUE TITLE
App keeps flashing white on the screen

### ISSUE THREAD

**Issue by Krafty-Coder** [Microsoft/vscode#62662]
- Extension Name: configuration-editing
- Extension Version: 1.0.0
- OS Version: Linux x64 4.15.0-36-generic
- VSCode version: 1.28.0

```json 
{
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 254,
		"activateCallTime": 2,
		"activateResolvedTime": 0,
		"activationEvent": "onLanguage:jsonc"
	}
}
```

**Comment by chrmarti** [comment]
/duplicate #60318

Please update to the latest version (1.28.2).
