### ISSUE TITLE
VS Code crashes when previewing large image on Markdown page

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#6267]
- VSCode Version:1.1.0-stable
- OS Version:Windows 7

Steps to Reproduce:
1. create a Markdown page and add the following link:
```
![car](https://static.pexels.com/photos/54278/pexels-photo-54278.jpeg)
```
2. Open Preview, View Source, Open Preview again

Usually crashes VS Code on the second preview.  You might need to try several times.

**Comment by isidorn** [comment]
Add important to raise attention

**Comment by bpasero** [comment]
Likely an out of memory crash because the image is very large and loaded into the renderer process. As it stands currently we cannot prevent the out of memory from happening given the hardcoded memory limit in V8.

**Comment by jrieken** [comment]
It does work with the new, currently in-dev, version markdown extension

**Comment by bpasero** [comment]
Ok lets close this.
