### ISSUE TITLE
I'd like to be able to get the current editor decoration ranges

### ISSUE THREAD

**Issue by PEZ** [Microsoft/vscode#62671]
In my extension for Clojure there is a feature for inline evaluation of code. It looks like so:

![re-eval-wishy](https://user-images.githubusercontent.com/30010/48077007-b4fce380-e1e6-11e8-8f7e-04fed083cc1b.gif)

This is nice, but has a few issues. One is that since I can only set the editor's decoration with an array, it is impossible to keep them at the right place when adding a new evaluation decoration if the document has been edited such that the original ranges are no longer valid. It can get like so:

![re-eval-wishy-2](https://user-images.githubusercontent.com/30010/48078485-d6ab9a00-e1e9-11e8-9f69-120d9b9aedf7.gif)

For this I would need some way to either add and remove decorations or to update them in an intelligent way.

Sometimes you can have quite a lot of evaluations showing, and you don't know which ones are valid. In the first gif aboveI have to re-evaluate them all efter having redefined the `hello` function.

I would want to be able to re-evaluate all currently active evaluations in the editor either dynamically or on command. The problem is that I do not know what the current ranges for them are, so I don't know what to evaluate. But VS Code knows what the ranges are, as evidenced by that my decorations, that I add when evaluating a range, keeps being highlighted correctly even when the document is quite heavily edited.

I am not sure which is the right API, but I would like to be able to tap into this knowledge of Code's and re-evaluate what it is keeping highlighted by certain decoration types.

Please let me know if I can clarify what it is I need some.

**Comment by PEZ** [comment]
Here's a demo of LightTable's inline evaluation display (and as-you-type evaluation, even):

https://www.youtube.com/watch?v=cs3lO4FE3U4

It is stuff that Clojure programmers are spoiled with in other editors. Would be so nice to be able to offer more of that in VS Code.

**Comment by alexandrudima** [comment]
Let's track in #54147
