### ISSUE TITLE
Integrated Terminal Display Problem

### ISSUE THREAD

**Issue by taipeiwu** [Microsoft/vscode#62670]
- VSCode Version: 1.28.2
- OS Version: Windows 10 1809 (OS Build: 17763.55)

Steps to Reproduce:

1. Open Terminal.
2. press any words then the leading path will disappear.
3. When I press "ENTER", it will return to normal.

![001](https://user-images.githubusercontent.com/8307585/48078429-666e3a00-e224-11e8-8be9-26ed76dc1227.jpg)
![002](https://user-images.githubusercontent.com/8307585/48078430-6837fd80-e224-11e8-8f49-2a39ff89503e.jpg)
![003](https://user-images.githubusercontent.com/8307585/48078433-69692a80-e224-11e8-85a9-4adeba79db89.jpg)

Does this issue occur when all extensions are disabled?: Yes

**Comment by luca0898** [comment]
same problem ...

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/57803
