### ISSUE TITLE
Menu bar text doesn't show

### ISSUE THREAD

**Issue by imertz** [Microsoft/vscode#62673]
![screenshot from 2018-11-06 19-18-39](https://user-images.githubusercontent.com/24761980/48081579-0d3ce100-e1f9-11e8-9c7b-9486864dfa5c.png)

Issue Type: <b>Bug</b>

Menu bar text doesn't show, otherwise the menu is actionable.

VS Code version: Code - Insiders 1.29.0-insider (1d0e4299c6ccfe9210252c811b4247cfdc8a6a44, 2018-11-06T10:44:34.297Z)
OS version: Linux x64 4.18.0-10-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|19.31GB (12.89GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.7.0
prettier-vscode|esb|1.6.1
sass-indented|rob|1.4.9
vscode-import-cost|wix|2.9.0
html-css-class-completion|Zig|1.17.1

</details>

**Comment by chrmarti** [comment]
/duplicate #62593

A workaround is to enable custom menus in the settings.
