### ISSUE TITLE
Comments that go past col 1000 don't format as comments

### ISSUE THREAD

**Issue by mcbergsma** [Microsoft/vscode#62676]
I have a long string in a variable and I noticed when I comment it out like this

`// let longstring='....'`

vscode doesn't format it based on my theme. If I cut the comment at col 1000, it is formatted, at 1001, it isn't.

V1.28.1

**Comment by alexandrudima** [comment]
I cannot reproduce. Can you reproduce when you disable all extensions? (perhaps you have installed a custom grammar file for JavaScript?)

![image](https://user-images.githubusercontent.com/5047891/48306839-d9d3bc80-e540-11e8-8efe-55babc5f6b49.png)
