### ISSUE TITLE
Broken syntax highlighting for PHP closures returning references

### ISSUE THREAD

**Issue by alkihis** [Microsoft/vscode#62680]
- VSCode Version: 1.28.2
- OS Version: macOS Mojave 10.14.1

Syntax highlighting for closures (anonymous functions) who returns references is broken.

Steps to Reproduce:

1. Create anonymous function with "&" between "function" keyword and argument list

Does this issue occur when all extensions are disabled?: Yes
<img width="334" alt="capture d ecran 2018-11-06 a 22 30 36" src="https://user-images.githubusercontent.com/32335180/48095110-2f902800-e214-11e8-9e95-2efbd3d11925.png">
<img width="298" alt="capture d ecran 2018-11-06 a 22 35 05" src="https://user-images.githubusercontent.com/32335180/48095133-3d45ad80-e214-11e8-8ffe-04dd8b4a717c.png">

**Comment by alexr00** [comment]
This issue was moved to atom/language-php#343

**Comment by alexr00** [comment]
We pull our PHP grammar from atom/language-php. Since this appears to be an issue with that grammar I've moved the issue to that repo. Thanks for reporting!
