### ISSUE TITLE
Slow color rendering of tree item

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#62681]
Issue Type: <b>Bug</b>

* Open a nodejs repo
* Open `node_modules` folder
* File/Folder grey out after being expanded

![slow-color-rendering](https://user-images.githubusercontent.com/876920/48095346-5ffea480-e1c9-11e8-8b30-3db87e5f280f.gif)

VS Code version: Code - Insiders 1.29.0-insider (1d0e4299c6ccfe9210252c811b4247cfdc8a6a44, 2018-11-06T10:41:32.761Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 3|
|Memory (System)|16.00GB (1.10GB free)|
|Process Argv|-psn_0_8194000|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-emoji|bie|0.0.7
solargraph|cas|0.17.6
npm-intellisense|chr|1.3.0
vscode-svgviewer|css|1.4.7
vscode-markdownlint|Dav|0.21.0
vscode-eslint|dba|1.7.0
gitlens|eam|8.5.6
remotehub|eam|0.2.0
tsl-problem-matcher|eam|0.0.4
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.40
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.5.1
prettier-vscode|esb|1.6.1
vscode-pull-request-github|Git|0.2.3
ocaml|hac|0.6.43
beautify|Hoo|1.4.7
references-plusplus|jri|0.0.5
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.8
vscode-language-pack-zh-hans|MS-|1.29.1
python|ms-|2018.9.2
azure-account|ms-|0.5.0
csharp|ms-|1.17.0
Go|ms-|0.6.93
PowerShell|ms-|1.9.0
wordcount|ms-|0.1.0
vsliveshare|ms-|0.3.897
debugger-for-chrome|msj|4.11.0
debugger-for-ios-web|msj|0.1.2
color-highlight|nau|2.3.0
vetur|oct|0.13.0
vscode-versionlens|pfl|0.22.0
material-icon-theme|PKi|3.6.0
seti-icons|qin|0.1.3
project-snippets|reb|0.5.0
ruby|reb|0.20.0
smartpaste|reb|0.0.3
toggle|reb|0.0.1
sass-indented|rob|1.4.9
rust|rus|0.4.10
vscode-lldb|vad|1.0.0

(10 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
@jrieken Maybe we can preemptively assume files are ignored, if folder is ignored? Maybe we could animate the fade out?
