### ISSUE TITLE
Not possible to close the Extensions: Marketplace window.

### ISSUE THREAD

**Issue by Bartolomeus-649** [Microsoft/vscode#62684]
Issue Type: <b>Bug</b>

1. Press shift+ctrl+x to show the Extensions window
2. now there's no way to close it
   a) ctrl+F4 does not work
   b) alt+space gives the system menu for the main window
   c) pressing ctrl+shift+x again does not close it
   d) Selecting the window in the View-menu does nothing
   e) No close button [x] in the upper right corner
   f)  No documentation available on how to close the Extension window.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:12.403Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (7.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.7.0
xml|Dot|2.3.2
python|ms-|2018.9.2
cpptools|ms-|0.20.1
csharp|ms-|1.17.0
PowerShell|ms-|1.9.0
team|ms-|1.144.1
debugger-for-chrome|msj|4.11.0

</details>

**Comment by usernamehw** [comment]
<kbd>Ctrl</kbd>+<kbd>b</kbd>?
Click on extension icon?

**Comment by Bartolomeus-649** [comment]
First of all, it was not a question, it is impossible to close the "Extensions: Marketplace window". And if you can open a window, then surely it should be able to close it?

Also, wouldn't it be better to make windows behave like windows, so not everyone need to figure out your unique way to close a window?

You do know Microsoft has a huge amount documentation on how to do proper user interfaces, that provide a very good user experience. Are you reading and following following Microsoft's Design Guidelines?
<br />
As an Example, this is what **Microsoft** say about User Interface Principles, and what they **consider** to be the **most important for a good user experience**.
[User Interface Principles](https://docs.microsoft.com/en-us/windows/desktop/appuistart/-user-interface-principles#intuitiveness) [\[https://docs.microsoft.com/en-us/windows/desktop/appuistart/-user-interface-principles#intuitiveness\]](https://docs.microsoft.com/en-us/windows/desktop/appuistart/-user-interface-principles#intuitiveness)
<sup>2018-05-31 - 37 minutes to read</sup>

> <i><b>Intuitiveness</b>
> This is the most important aspect of a great user experience. Intuitive UX lessens the need for explanations. The user just knows what the controls do.
> 
> An important topic in intuitive design is color-coding.  A very good example of recognition of content by colors is Microsoft Office OneNote. The application's tabs can be set to different colors while still looking essentially like a proper part of the overall Windows style design.
> 
> Another important aspect is the text in your applications. Recently, there have been various efforts to simplify the language used for the written instructions in Windows software. The usage of text inside software will be discussed later, but please note the following small but important detail.
> 
> MSN Messenger had a check box in its Options dialog marked "Share webcam capabilities." Developers and tech-friendly people know what that means, but a novice user could possibly think that you could let another user on the other end of your chat use your Web cam, too. In a recent version, they changed it to "My Webcam: Allow others to see that I have a webcam". This is perfect for the target audience that may not have technical knowledge and are used to simple language.
> 
> While simpler language makes it easy to understand, there's also an added advantage. Scientific studies show that our mind works easier with simpler language when trying to understand something new. Often, our brain processes words like 'it,' 'for,' 'that,' and other common words so speedily and effortlessly that more 'bandwidth' is allocated to understanding the words that stand out, like 'Webcam' or 'Others,' in the above example.
> 
> Message Box titles, GroupBox captions, and other such text blocks make it easy for you to convey the function of a group of controls to the end user with just a few words.
> 
> Intuitiveness is also born from familiarity. For example, the placement of the OK and Cancel buttons is so uniform and well placed in our minds that if a dialog holds these buttons in a reverse sequence (Cancel, then OK; instead of OK, then Cancel)—you just might hit Cancel instead. After using a particular standard for doing things—Windows-based applications for example—for more than a year, habits develop. Following industry standards (however unstated they may be) makes your software easier to use.
> 
> In one of the early Windows Vista preview builds, the Minimize, Maximize, and Close buttons of any window became different. In previous versions of Windows (especially when using a single monitor), you develop a habit of moving the cursor in the top-right corner of the screen and clicking. This always resulted in the window closing. Now in this particular build of Windows Vista, there were approximately 8 pixels worth of space between the Close button and the right-most border of the window. The extra space did make it look cool (and was probably necessary for the cool glow animation the button sported), but was irritating because it did not allow users to close open windows as easily. Reconditioning your mind can be tough. Thankfully, in the following build, this issue was addressed. Now, there still is space between the border of the window and the close button, but clicking that space also causes the window to be closed.
> 
> A very important factor of intuitive design is the amount of 'mental bandwidth'—the amount of time it might take our mind to comprehend something—it uses. The lower the 'bandwidth' usage, the better your user experience.
> 
> These are small things that contribute to the "experience" of using a software application. The following examples provide tips on improving your applications with real-world tips and tricks.
> <br />
> <b style="font-size: 120%;">Use Standards</b>
> The established standards of any software environment—whether on the operating system level, brand level, or application level—are very important. Besides the branding, the standards act as a proverbial schema in the user's mind. When the user spends long periods of time working with a software application, he or she will automatically increase productivity because of the growing familiarity.
> 
> Before discussing standards, let's first discuss what exactly these standards are. The standards include everything from the layout of controls in a particular manner on the dialog boxes—like the OK and Cancel buttons, the user interface's shape—rounded-corners of the top of the window as in Windows dialogs, styles of icons, styles of any other graphics, interactive behavior of your application, and the like.
> 
> If your application falls into a specific niche, then it may fare better to follow a different set of standards. For example, if your application supports, application or an add-on for, Office OneNote 2003, it is wise to follow the styles of UI and interactivity standards of Office—and OneNote itself, in particular. This includes using the Office-style command bars instead of the standard toolbars, and other such things— both visual and behavioral. **If your application is to be part of the Microsoft Visual Studio** .NET category, **then you have a separate set of standards.** In fact, for such add-on or support applications, companies such as Microsoft do **release written guidelines**. Also note that sometimes graphics and design concepts are protected intellectual properties. Always check the proper documentation to make sure you have the license to create such designs.
> 
> <b>When applications share the operating system-level or application-level standards, the users feel more at home with the software, which makes it easier to learn and use. This results is a direct boost to productivity. Users want to be able to become productive with new software as quickly as possible.</b></i>

<hr />

**And this is what [Jakob Nielsen](https://en.wikipedia.org/wiki/Jakob_Nielsen_(usability_consultant )** say in his article ["Top 10 Application-Design Mistakes"](https://www.nngroup.com/articles/top-10-application-design-mistakes/) regarding the use of standard GUI controls:

> <i><b>Top 10 Application-Design Mistakes </b>
>   \- 1. Non-Standard GUI Controls
> Jakob's Law is:
> "users spend most of their time on other websites (or applications)", 
> then Jakob's Second Law is even more critical:
> **"Users have several thousand times more experience with standard GUI controls than with any individual new design."**</i>
> <hr />

#### Here are some links to Microsoft's Design Guidelines, among others:
* Docs: User Interface Principles 
https://docs.microsoft.com/en-us/windows/desktop/appuistart/-user-interface-principles#intuitiveness

* MSDN: User Interface Principles
https://msdn.microsoft.com/en-us/library/windows/desktop/dn742491(v=vs.85).aspx

* Docs: Usability in Software Design
https://docs.microsoft.com/en-us/windows/desktop/appuistart/usability-in-software-design

* AskTOG: First Principles of Interaction Design (Revised & Expanded)
https://asktog.com/atc/principles-of-interaction-design/

* Blomberg: A computer users manifesto
https://www.bloomberg.com/news/articles/1998-09-27/a-computer-users-manifesto

* Principle of least astonishment
https://en.wikipedia.org/wiki/Principle_of_least_astonishment
