### ISSUE TITLE
capitilization is not consistent for file paths on windows in setbreakpoints message 

### ISSUE THREAD

**Issue by jacdavis** [Microsoft/vscode#6268]
- VSCode Version:1.1
- OS Version: windows 10

Steps to Reproduce:
1) start a debug session
2) add a bp
3) Breakpoint message will likely contain uppercase drive letter
4) Delete bp
5) Breakpoint message will now contain lowercase drive letter

NOTE: I am working around this in our debug adapter. This causes an issue because we have collections of source files that contain bps in the c++ and c# debug adapters. These keys are not found in this case because of the casing mismatch.

**Comment by isidorn** [comment]
This seems like our internal uri class sometims converts drive letter to uper case and sometimes not.
@jacdavis I am not able to reproduce this though, can you please provide steps with some example file so I can investigate into this further to see when this is happening. When I tried I always got the lowercase driver letter. Thanks!

**Comment by jacdavis** [comment]
1) Install mingw
2) write c++ app for mingw using gcc. Compile with -g
3) Open folder in vscode. you will need a recent build of the c++ extension.\\cpvsbuild\drops\MDDDebugger\CppTools\latest\Extension
4) Start debugging. with a bp set
5) The first bp message will have a lower case c: any second message will have an upper-case driver letter.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/22740
