### ISSUE TITLE
Alert when developing an extension that uses the `vscode.previewHtml` command

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#62685]
Part of #62630

**Feature**
Show an alert when a developer is running an extension that calls the `vscode.previewHtml` command. This should only happen for extensions being run in development mode

The goal is to alert developers to the fact that `vscode.previewHtml` is deprecated and will stop working properly in the future

**Comment by roblourens** [comment]
Side note, the sample previewHtml extension doesn't work anymore.

`Unable to open 'CSS Property Preview': Cannot read property 'document' of undefined.`
