### ISSUE TITLE
Press arrow keys got number pad key instead while using vscode by X11 forwarding

### ISSUE THREAD

**Issue by pengbins** [Microsoft/vscode#62694]
Similar to #33912

- Version: 1.28.2
- Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
- Date: 2018-10-17T00:20:56.183Z
- Electron: 2.0.9
- Chrome: 61.0.3163.100
- Node.js: 8.9.3
- V8: 6.1.534.41
- Architecture: x64
- OS Version: Ubuntu 16.04 ( ssh from windows10)
- X server : Mobaxterm v11.0 Build 3816

Steps to Reproduce:

1. ssh login to Ubuntu 16.04 with X11 forwarding setup
2. start vscode, and press arrow keys ( same as Home, End, Pgup PgDn)

![arrowkey_vscode](https://user-images.githubusercontent.com/1439218/48112958-ab7d8500-e293-11e8-9841-b23b3b6dc9f3.gif)

By press left arrow key, you got number'6'  input repeatedly,  can be stopped by hit Ctrl-C.
By press up arrow key, you got number  '8'  input repeatedly,  can be stopped by hit Ctrl-C.

If open the keyboard shortcut editor, press arrow key you can see number pad key repeatedly pressed.
![keyboard_vscode](https://user-images.githubusercontent.com/1439218/48112930-8c7ef300-e293-11e8-9ece-acf5480a72eb.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by pengbins** [comment]
#24012

**Comment by chrmarti** [comment]
That's supposedly fixed, must be a new/different issue.

**Comment by pengbins** [comment]
Maybe this is a Mobaxterm issue, I can reproduce this issue by xterm too.
