### ISSUE TITLE
can not add breackpoint

### ISSUE THREAD

**Issue by useaname** [Microsoft/vscode#62691]
clicking on the editor margin not add breakpoint

- VSCode Version: 1.28.2 (1.28.2)
- OS Version:macOS  10.13.6 

![1111](https://segmentfault.com/img/bVbjdyP?w=804&h=360)

**Comment by useaname** [comment]
By replacing the configuration(User settings), it is found that it is because of the configuration file, which one is unclear.

**Comment by falsifier** [comment]
Not debug mode

**Comment by useaname** [comment]
solved.
// Controls visibility of the glyph margin
 "editor.glyphMargin": false
