### ISSUE TITLE
Integrated terminal: zsh: execvp(3): failed. No such file or directory

### ISSUE THREAD

**Issue by rogersachan** [Microsoft/vscode#62699]
- VSCode Version: 1.27.2
- OS Version: Manjaro Linux

Steps to Reproduce: exactly the same as #7850 , which was fixed and closed then with the Insider build.

1. Run command from task
2. Receive error

Does this issue occur when all extensions are disabled?: Yes

**Comment by rogersachan** [comment]
I also have zsh/oh-my-zsh installed, which seems to be a recurring theme with issues along this.

**Comment by chrmarti** [comment]
What is your `"terminal.integrated.shell.linux"` setting?

**Comment by mze9412** [comment]
I have the same issue on my aspnetcore/angular web project sinde the update to 1.30.0-insidder
VSCode Version: 1.30.0-insider (1.30.0-insider)
OS Version: Ubuntu 18.10 (Linux 4.18.0-10-generic #11-Ubuntu SMP Thu Oct 11 15:13:55 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux)

**Comment by chrmarti** [comment]
@winzig @mze9412 I have extracted #63104 for the debugging issue in 1.30.0-insiders.

@rogersachan Could you retry with 1.29.0?

**Comment by abdohossam5** [comment]
@chrmarti I am having the same issue with zsg and insiders (1.30.0-insider- 6ef7e81ec086ced5fb20e904ea405075be474023- 2018-11-14T18:08:13.618Z). Tested with code 1.29 and it is working fine.

**Comment by chrmarti** [comment]
The issue in 1.30.0-insider is tracked as #63104. I'll close this one because it was reported against 1.27.2. Let us know if you see it in 1.29.0.
