### ISSUE TITLE
Bad margins in debug call stack

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#627]
The call stack line numbers overlap with the scrollbar. Make sure we get enough right margin/padding in there.

![image](https://cloud.githubusercontent.com/assets/22350/11400299/d2caf858-938c-11e5-837f-5c68364ffc58.png)

**Comment by isidorn** [comment]
Nice catch
Added 0.15 em to the right margin, since we already had a left margin. I like it now

**Comment by joaomoreno** [comment]
You're as fast as :zap: Gordon.

**Comment by joaomoreno** [comment]
Instead of this fix, I suggest you remove that and increase the `right-margin` of the `div.stack-frame` to `1.2em`.

Marking this as verified though.

**Comment by isidorn** [comment]
When making the viewlet horizontally small `file name: line number` get hidden if there is not enough space so I went with `0.8em` since `1.2em` felt like too much
