### ISSUE TITLE
collapse frequently

### ISSUE THREAD

**Issue by Kay1986** [Microsoft/vscode#62708]
When I remove some code. The editor reacts slowly and crashes easily.

**Comment by chrmarti** [comment]
Please follow: https://github.com/Microsoft/vscode/wiki/Performance-Issues

If it's a plain crash, check out: https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues

**Comment by jrieken** [comment]
@Kay1986 what version is this happening this? do have terminals open? do you run some build tool, like webpack-dev-server or such?

**Comment by Kay1986** [comment]
> @Kay1986 what version is this happening this? do have terminals open? do you run some build tool, like webpack-dev-server or such?

Yes, when I crashed, I was using webpack.but it didn’t crash at the beginning,it didn’t become smooth after running for a while.my version is 1.28.2, my colleague also has this problem, using the windows 10 system.

**Comment by Kay1986** [comment]
> Please follow: https://github.com/Microsoft/vscode/wiki/Performance-Issues
> 
> If it's a plain crash, check out: https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues

Ok, I try to do it, but I am afraid I don’t have a lot of time to check it out. I can only submit this question to you first.

**Comment by jrieken** [comment]
@Kay1986 is that webpack in dev/watch mode? Iff so then it might be caused by file watching. There is a setting `files.watcherExclude` with which you can exclude the webpack out/dist folder. Please give that a try. Thanks

**Comment by Kay1986** [comment]
> @Kay1986 is that webpack in dev/watch mode? Iff so then it might be caused by file watching. There is a setting `files.watcherExclude` with which you can exclude the webpack out/dist folder. Please give that a try. Thanks



> @Kay1986 is that webpack in dev/watch mode? Iff so then it might be caused by file watching. There is a setting `files.watcherExclude` with which you can exclude the webpack out/dist folder. Please give that a try. Thanks

Yes, it is this mode, but I have excluded this folder, and I have not packaged my project yet. I found that sometimes I select some code and it will cause slow response, so I think this is because of some plugins and Editor-related compatibility issues, such as the ES-Lint plugin that requires real-time monitoring of code. Thank you for your kind help.

**Comment by jrieken** [comment]
@Kay1986 Thanks. When selection is getting slow this might caused by an extension. Can you share the list of extensions with us, just run `code --list-extensions`. 

Also try to CPU profile this. Hit F1 > Toggle Developer Tools. In the overflow menu select 'More Tools > JavaScript Profiler'. 
* In there select start, 
* try to reproduce the slowdown
* stop it, profiling, save it to a file, and attach the file here. 

Thanks.

<img width="380" alt="screen shot 2017-09-28 at 09 44 31" src="https://user-images.githubusercontent.com/1794099/30954796-d1be9e30-a431-11e7-959e-495d234c37c6.png">
