### ISSUE TITLE
1.28.2 version startup slow 

### ISSUE THREAD

**Issue by TrumanDu** [Microsoft/vscode#62703]
Issue Type: <b>Performance Issue</b>

just startup 

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.10586

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (8.41GB free)|
|Process Argv|--prof-startup|
|Screen Reader|no|
|VM|0%|

</details>

<details>
<summary>Raw Startup Timers (CSV)</summary>

|Name|Start|
|---|---|
main:started |	1541577585698 
main:appReady |	1541577585745 
main:loadWindow |	1541577586073 
renderer/started |	1541577606369 
willShowPartsSplash |	1541577606376 
willAccessLocalStorage |	1541577606376 
didAccessLocalStorage |	1541577606376 
didShowPartsSplash |	1541577606393 
willLoadWorkbenchMain |	1541577606413 
didLoadWorkbenchMain |	1541577606921 
main/startup 	|1541577606921 
willStartWorkbench| 	1541577606942 
willLoadExtensions |	1541577606948 
LifecyclePhase/Restoring |	1541577606974 
willRestoreEditors| 	1541577607055 
didRestoreEditors| 	1541577607055 
willRestoreViewlet| 	1541577607055 
didRestoreViewlet| 	1541577607063 
willRestorePanel |	1541577607063 
didRestorePanel |	1541577607171 
LifecyclePhase/Running| 	1541577607172 
didStartWorkbench |	1541577607184 
extensionHostReady| 	1541577608982 
didLoadExtensions |	1541577608982 
LifecyclePhase/Eventually |	1541577609681 

</details>

**Comment by jrieken** [comment]
@TrumanDu This is fixed in [VS Code Insiders](https://code.visualstudio.com/insiders/).
