### ISSUE TITLE
Multiple Cursor Select and adding an incrementing ID with Emmet

### ISSUE THREAD

**Issue by RamVal** [Microsoft/vscode#62705]
- VSCode Version: 1.28.2
- OS Version: Windows 7 Professional (Newest Updates installed)

When I try to wrap multipe selections with paragraphs while adding an incrementing ID with the abbreviation p#id$ VSCode it doesnt work like in Brackets with Emmet.

In the preview VSCode displays for every paragraph: 
```<p id="id\$">a lot of text</p>```

When I then press Enter VSCode sets the following for every paragraph: 
```<p id="id$">a lot of text</p>```

So it doesn't add the incrementing number instead of the $ like in Brackets. In Brackets the created Wraps would look like this:
```<p id="id1">a lot of text</p>```
```<p id="id2">a lot of text</p>```
```<p id="id3">a lot of text</p>```

When I use the abbreviation by itself to create multiple paragraphs without selecting anything it works like intended. For example with p#id$*3 it creates:
```<p id="id1"></p>```
```<p id="id2"></p>```
```<p id="id3"></p>```

So I tried to use that variation with the number of paragraphs I have selected in Wrap with abbreviation to maybe have a workaround. But then it just creates the same like above just for every paragraph.

Sure it's just a comfort issue, so not that important, but it would be great if that would work too.

Does this issue occur when all extensions are disabled?: Yes

**Comment by ramya-rao-a** [comment]
When using `Wrap with abbreviation` in the multi cursor mode, the same expanded abbreviation gets applied to each cursor.

If you want to use the repeater (*) with numbering ($), then try `Wrap individual lines with Abbreviation`?

![wrap](https://user-images.githubusercontent.com/16890566/48176339-6e7db680-e2c4-11e8-8622-39a99963910b.gif)

**Comment by RamVal** [comment]
That only works when I use lines that are direct neighbours basicly. When I select lines that are apart from each other it doesn't work correctly and still gives each line I select the ID id1.
So for every line it still shows (in preview and after expanding the abbreviation):
```<p id="id1">linex</p>```

**Comment by ramya-rao-a** [comment]
Multi-cursor support for the wrap feature in VS Code assumes that the same abbreviation should be applied on each selection separately. 

To get what you want, we need to treat multiple selections as part of a single abbreviation expansion.

The 2 features are mutually exclusive when using the new emmet modules that we are using in VS Code.
