### ISSUE TITLE
In Linux, cannot use mouse to operate dialog created by API vscode.window.showOpenDialog 

### ISSUE THREAD

**Issue by Eskibear** [Microsoft/vscode#62704]
- VSCode Version: 1.28.2
- OS Version: Ubuntu 18.0.4 , also reported by Fedora 28

Steps to Reproduce:

1. In developing a VSCode extension, register a command to execute the following callback
```ts
await vscode.window.showQuickPick(["Click to showOpenDialog"]);
await vscode.window.showOpenDialog({
  canSelectFiles: false,
  canSelectFolders: true,
  canSelectMany: false
});
```
2. Trigger the command, in the QuickPick, use **MOUSE** to select the item "Click to showOpenDialog"
3. It pops up a dialog, but you are not able to click anything with mouse. But keyboard can work.

I'll paste a GIF later.

**Comment by jrieken** [comment]
can you try to reproduce this with vscode insiders?

**Comment by Eskibear** [comment]
@jrieken Yes, I can reproduce it in 1.29.0-insider

And one thing to mention, it might help to diagnose. If I set a breakpoint at the following line, after the breakpoint is hit, I simply click the continue button, it pops up the dialog and it works well with the mouse.

**Comment by Eskibear** [comment]
See this GIF, I've added captions and key strokes for your imformation. 

![linuxbug](https://user-images.githubusercontent.com/2351748/48126087-43429980-e2bb-11e8-975e-8e0249cc6072.gif)

**Comment by Eskibear** [comment]
In following cases, the dialog works well.

- Pause before `showOpenDialog`
![pause](https://user-images.githubusercontent.com/2351748/48126453-16db4d00-e2bc-11e8-96a8-33dbab90ed60.gif)

- Press "Enter" in the QuickPick box instead of click. 
![enter](https://user-images.githubusercontent.com/2351748/48126611-881b0000-e2bc-11e8-8ed3-1bf20a8f1957.gif)

**Comment by jrieken** [comment]
I can reproduce... This is bizarre..

**Comment by jrieken** [comment]
adding @chrmarti because of the quick pick thing... this smells like an upstream electron issue but it might somehow interact with quick pick...

**Comment by Eskibear** [comment]
Any update on this? Linux users are still suffering from it.

**Comment by chrmarti** [comment]
@Eskibear Do you still see this with the latest Insiders builds? We recently updated Electron which might affect this. /cc @bpasero

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by chrmarti** [comment]
Thanks @Eskibear !
