### ISSUE TITLE
Instantiate native promise instead of WinJS.Promise

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#62716]
This is part of https://github.com/Microsoft/vscode/issues/53526 and points out files in which we call `new WinJS.Promise`. In addition to `join`, `as`, `wrap`, and `wrapError` that's how winjs promises end up in our system and we wanna get rid of them. 

Please migrate to instantiating native promises with taking all care that's needed for this adoption. 

@bpasero 
* [ ] `src/vs/platform/lifecycle/electron-main/lifecycleMain.ts`

**Comment by dbaeumer** [comment]
Started this but need to wait until lower level stuff like `src/vs/workbench/services/files/electron-browser/fileService.ts` is converted.

**Comment by dbaeumer** [comment]
Did:
```
src/vs/base/node/processes.ts
src/vs/workbench/parts/tasks/common/problemMatcher.ts
src/vs/workbench/parts/tasks/common/taskDefinitionRegistry.ts
```

@alexr00 can you do `src/vs/workbench/parts/tasks/electron-browser/terminalTaskSystem.ts` that I don't interfere with work you are doing.

**Comment by roblourens** [comment]
Using `Thenable` helps when the file's dependencies aren't converted. e.g. in cases like

```
public foo(): Thenable<void> {
  return actuallyTPromise().then(() => something)
}
```

As long as you check that the code will be safe when the upstream method switches from TPromise to Promise.

**Comment by jrieken** [comment]
Yes, there are three ways to deal with not-yet-converted dependencies (and I think that 1 and 2 are the best ways to tackle this)

* use `Thenable`
* or use `Promise.resolve`
* use async-await

**Comment by dbaeumer** [comment]
Makes sense. Since the `fileService` is on the list to be converted I will wait. Will ensure I only need to touch once.

**Comment by jrieken** [comment]
ping @bpasero and @Tyriar

**Comment by alexandrudima** [comment]
@bpasero Why the reassign? Are there more files I should look at?

I've done the files under my name.

**Comment by bpasero** [comment]
@alexandrudima sorry I thought people would remove the ones that are done from the summary like Joao did.

**Comment by bpasero** [comment]
Ah whatever, converted the last one :100:

**Comment by jrieken** [comment]
awesome!
