### ISSUE TITLE
mardown-preview-enhanced

### ISSUE THREAD

**Issue by lookaaa** [Microsoft/vscode#62717]
- VSCode Version: <code>Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)</code>
- OS Version: <code>Windows_NT ia32 6.1.7601</code>
- CPUs: <code>Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz (4 x 2494)</code>
- Memory (System): <code>3.78GB (1.47GB free)</code>
- Memory (Process): <code>92.25MB working set (93.86MB peak, 64.97MB private, 24.30MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|3350|
|main|app.isReady => window.loadUrl()|9790|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|23701|
|renderer|require(workbench.main.js)|8872|
|renderer|create extension host => extensions onReady()|23328|
|renderer|restore viewlet|0|
|renderer|restore editor view state|4|
|renderer|overall workbench load|8426|
|main + renderer|start => extensions ready|74000|
|main + renderer|start => workbench ready|54218|

---

Additional Steps to Reproduce (if any):

1.
2.

**Comment by chrmarti** [comment]
You are running an outdated version of VS Code. Please upgrade.
