### ISSUE TITLE
Suggests bug

### ISSUE THREAD

**Issue by tonn2y** [Microsoft/vscode#6272]
- VSCode Version:1.1.0
- OS Version:Window 10 OSX 10.11

Steps to Reproduce:

1. I define properties use 2 underline,like '__events',when i use this property,the Suggests always give me 3 underline property ,like '___events'.
![2](https://cloud.githubusercontent.com/assets/2756249/15167252/f0a8c2dc-1759-11e6-87a3-4df0ea8e004b.png)

**Comment by jrieken** [comment]
That is as designed
