### ISSUE TITLE
Shell Script and Bash Commands Highlight

### ISSUE THREAD

**Issue by agenciah1code** [Microsoft/vscode#62723]
After 5 years using Sublime, I am migrating to VS Code, however I have noticed a big problem in HighLight of Shell (Bash) language, variables are not colored correctly, bash commands, etc. Is there any forecast or any way to fix this?

**Comment by alexr00** [comment]
@agenciah1code, is this what you mean?
![image](https://user-images.githubusercontent.com/38270282/48191428-57cb7400-e345-11e8-85b0-86e721189dd5.png)
Where `file` is not colored?

It looks like this is a problem with the grammar we use from atom/language-shellscript.

**Comment by alexr00** [comment]
This issue was moved to atom/language-shellscript#130

**Comment by alexr00** [comment]
If there is another shell script grammar that will classify variables better then we could look into moving to it 😊
