### ISSUE TITLE
Option to run tasks without problem matchers or tasks.json

### ISSUE THREAD

**Issue by diminutivesloop** [microsoft/vscode#62728]
I frequently use the task runner to execute npm scripts in my projects. However I don't find the problem matcher functionality useful and the prompts to choose a matcher whenever I have a new project without a `tasks.json` file can get annoying. I would appreciate an option to run tasks without having to choose a problem matcher or create a `tasks.json` file.

**Comment by dbaeumer** [comment]
This requires new API to let the npm script detector decide whether VS Code should prompt for a problem matcher. Alternatively we could add a global setting `"tasks.promptForProblemMatcher": "never"`.

**Comment by alexr00** [comment]
I'm a fan of the global setting.

**Comment by alexr00** [comment]
New setting proposal. Can be either a boolean or an array of task types:
`"task.problemMatchers.neverPrompt": ["npm"]`

**Comment by alexr00** [comment]
To verify, try setting `"task.problemMatchers.neverPrompt"` to an array of task types an a boolean and verify that places where you saw the problem matcher prompt no longer show the problem matcher prompt. Good task types to test with are "npm" and "shell".
