### ISSUE TITLE
Git does not track changes

### ISSUE THREAD

**Issue by bibblebabl** [Microsoft/vscode#62726]
Issue Type: <b>Bug</b>

Git stop tracking changes. After I have changed several files, they are not displayed in the menu and the list of changed files. 

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 18.0.0
![2018-11-07 16 54 10](https://user-images.githubusercontent.com/9008978/48135513-33708880-e2ae-11e8-8484-b64c5756a777.png)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
vscode-styled-jsx|bla|1.0.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.60
vscode-eslint|dba|1.7.0
githistory|don|0.4.3
es7-react-js-snippets|dsz|1.9.0
gitlens|eam|8.5.6
vscode-great-icons|emm|2.1.44
vsc-material-theme|Equ|2.5.1
path-autocomplete|ion|1.12.0
vscode-styled-components|jpo|0.0.23
vscode-styled-components-snippets|lXS|1.0.2
vscode-language-babel|mgm|0.0.21
prettify-json|moh|0.0.3
vscode-duplicate|mrm|1.2.1
sass-indented|rob|1.4.9
vscode-input-sequence|tom|0.2.0
vscode-todo-highlight|way|1.0.4

</details>

**Comment by sunwgit** [comment]
I have the same issue since version 28.
<img width="881" alt="vscode_git_bug" src="https://user-images.githubusercontent.com/11364780/48388558-bd987100-e734-11e8-9afd-4d271bf9b1d0.png">

**Comment by joaomoreno** [comment]
@bibblebabl I see a `4` on the SCM view icon... where did you expect the changes to appear?

**Comment by joaomoreno** [comment]
So, Git does track files, but doesn't react to file events?

**Comment by bibblebabl** [comment]
Made a screencapture with this issue
[screencapture.mov.zip](https://github.com/Microsoft/vscode/files/2595101/screencapture.mov.zip)

**Comment by joaomoreno** [comment]
@bibblebabl Excellent, thanks for the video. Can you run the same with `--verbose`? I'm interested in knowing whether Code detects file changes at all.

**Comment by bibblebabl** [comment]
@joaomoreno after I launched  with verbose flag I edited some files – git did not not track any changes
[Uploading vscode_verbose_log.log…]()

**Comment by bibblebabl** [comment]
@joaomoreno I meant git CLI. Never mind

**Comment by joaomoreno** [comment]
Can you check if Code's file explorer tracks file events? If, when deleting a file from the outside, Code removes it from the explorer, for example?

Also, can you show me a video recording with the terminal showing the output of `--verbose`, as you change files?
