### ISSUE TITLE
Terminal does work well my multiprocessing python scripts called by cmd batch scripts

### ISSUE THREAD

**Issue by risaldar** [Microsoft/vscode#62721]
Issue Type: <b>Bug</b>

Terminal does work well my multiprocessing python scripts called by cmd batch scripts.

- start batch script and call python
- from python main starts pool
- each pool worker runs a bash shell and runs a shell script
- one shell script has to call another python script
-- other python main starts another pool
-- other pool worker (file reader) performs some action

> python get's lost somewhere. The same system works when called some native Cmd instead of VsCode Embedded Cmd. 

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.86GB (17.58GB free)|
|Process Argv|C:\Drive_Y\xxx|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.9.2
cpptools|ms-|0.20.1
notepadplusplus-keybindings|ms-|1.0.2

</details>

**Comment by chrmarti** [comment]
I don't understand what "python gets lost somewhere" means. Please clarify.
