### ISSUE TITLE
Can't set VS Code as default for XML files

### ISSUE THREAD

**Issue by derekantrican** [Microsoft/vscode#62732]
Issue Type: <b>Bug</b>

I'm using Windows 10 and I just installed VS Code (I've tried both "User" version and "System" version). I want set it as the default for xml files. But whenever I select it (either by right clicking on a file and "Open With" > "Choose another app") or by Settings > Default Apps > Choose Default Apps by File Type, it doesn't "stick": https://i.imgur.com/wrFG6xo.gifv

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|15.85GB (5.71GB free)|
|Process Argv|C:\Projects\Sigma3D\SigmaNEST3DDevelopment\S3SW\S3SW.csproj|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by chrmarti** [comment]
This appears to be an issue with Windows 10: https://answers.microsoft.com/en-us/windows/forum/all/windows-10-always-open-with-doesnt-work/eea098a9-65e4-444c-acfc-2ea94d3140a8

**Comment by derekantrican** [comment]
I have asked this on StackOverflow but haven't been getting any help: https://stackoverflow.com/questions/53160649/cant-set-vs-code-as-default-for-xml-files

**Comment by chrmarti** [comment]
This looks like an issue with Windows 10, please see: https://answers.microsoft.com/en-us/windows/forum/all/windows-10-always-open-with-doesnt-work/eea098a9-65e4-444c-acfc-2ea94d3140a8
