### ISSUE TITLE
Storage migration is slow and happens on each new window

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#62733]
This one only took 2.8s, but sometimes I get 4s startup times:

![image](https://user-images.githubusercontent.com/4033249/48148947-ce963d80-e26f-11e8-85af-49f447d151d8.png)

- VSCode Version: <code>Code - Insiders 1.29.0-insider  (5438af145cf480ce0162bda0799435684b293ec5, 2018-11-07T00:54:27.213Z)</code>
- OS Version: <code>Darwin x64 17.7.0 </code>
- CPUs: <code>Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)</code>
- Memory(System): <code>16.00 GB(2.71GB free) </code>
- Memory(Process): <code>315.69 MB working set(0.00MB peak, 166.49MB private, 149.20MB shared) </code>
- Load(avg): <code>2, 2, 2 </code>
- VM: <code>0% </code>
- Initial Startup: <code>yes </code>
- Screen Reader: <code>no </code>
- Empty Workspace: <code>yes </code>
- Timings:

| Component | Task | Duration(ms) | Info |
| ---| ---| ---| ---|  
| [main]| start => app.isReady| 70| true|
| [main]| nls:start => nls:end| 1| true|
| [main]| app.isReady => window.loadUrl()| 318| true|
| [main->renderer]| window.loadUrl() => begin to require(workbench.main.js)| 344| NewWindow|
| [renderer]| require(workbench.main.js)| 1257| cached data: NO|
| [renderer]| require workspace storage| 4| |
| [renderer]| require & init workspace storage| 13| |
| [renderer]| register extensions & spawn extension host| 256| |
| [renderer]| restore viewlet| 0| |
| [renderer]| restore panel| 0| |
| [renderer]| restore editors| 268| 1: workbench.editors.untitledEditorInput|
| [renderer]| overall workbench load| 494| |
| [main->renderer]| workbench ready| 2541| |
| [renderer]| extensions registered| 2810| |
 
---

:warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`prof-cda2.extHost.cpuprofile.txt`
-`prof-cda2.main.cpuprofile.txt`
-`prof-cda2.renderer.cpuprofile.txt`

[prof.zip](https://github.com/Microsoft/vscode/files/2558498/prof.zip)

**Comment by octref** [comment]
Further investigation:

- `code-insiders --disable-extensions` starts up fast:
  ![image](https://user-images.githubusercontent.com/4033249/48149184-567c4780-e270-11e8-92b4-8f3d046c1207.png)
- Still extension disabled state, opening new window is slow (Cmd + Shift + N)
  ![image](https://user-images.githubusercontent.com/4033249/48149239-7b70ba80-e270-11e8-8e9b-b9e65a8e433b.png)

So there are 2 problems:

1. Extension can impact startup perf — this is unexpected. I'll try to find which extension is causing this. But extensions shouldn't be able to impact startup.
2. Cmd + Shift + N is slow whether I have extensions enabled or not. This needs investigation.

**Comment by octref** [comment]
More details:

- This happens on Cmd+Shift+N, namely, opening new window with no workspace.
- I see this on @mjbvz and my machine, but not Kai or Rob's machine
- What slows things down seems to be the workspace storage keys migration. By looking at startup timers, these are the deltas these events happen after `didloadworkbenchmain`:

```
willMigrateWorkspaceStorageKeys: 22ms
didMigrateWorkspaceStorageKeys: 3355ms
```

**Comment by octref** [comment]
Me and Kai looked into this. What we found:

- For newly created window, we create a folder like `/Users/pine/Desktop/InsidersData/User/workspaceStorage/1540307933411`
- A `storage.db` file doesn't exist in that folder. So [this check](https://github.com/Microsoft/vscode/blob/83660da7ea9f2b25a676cd1418e897feee7922fb/src/vs/workbench/electron-browser/main.ts#L306) fails.
- VS Code runs the [`parseStorage`](https://github.com/Microsoft/vscode/blob/7f9d70125991c63da8ba964ae5dbcdb1e204ee96/src/vs/platform/storage/common/storageLegacyMigration.ts#L48) function, in attempt to migrate localStorage to SQL for the new workspace. This can take more than 3s. My `storage.length` is around 10k, so [this loop](https://github.com/Microsoft/vscode/blob/7f9d70125991c63da8ba964ae5dbcdb1e204ee96/src/vs/platform/storage/common/storageLegacyMigration.ts#L56) runs 10k times.

**Comment by mjbvz** [comment]
Added small optimization to cut time in half: https://github.com/mjbvz/vscode/commit/aeb7a3c6b08c443db5151a4e07be59496cb9be25

Still slow. We can optimize the loops further (using a trie for example) but we probably want to revisit the core logic

**Comment by roblourens** [comment]
Why does this migration happen every time instead of just once? And why does @octref have more storage keys than the rest of us?

**Comment by kieferrm** [comment]
One idea we discussed here was can we migrate once, then when a new workspace is opened copy the migrated version, and replay potential changes that happened afterwards (for example through an older version of code) be replayed incrementally in the background.

**Comment by octref** [comment]
@roblourens 

> Why does this migration happen every time instead of just once? 

The migration happens every time because we create a folder `<user-data-dir>/User/workspaceSorage/<id>` for each newly opened window.

> And why does @octref have more storage keys than the rest of us?

This is on my personal laptop, where I have accumulated a lot of repos.

**Comment by octref** [comment]
What we used to have: all keys in the same localStorage. Keys start with either `/global` or `/workspace/<id>`.

What we now have: `<user-data-dir>/Users/workspaceStorage/<id>` for each workspace, and a lot of small DB files in each `workspaceStorage/<id>` folder.

What's slow:
```
for (let key in localStorage) { // 10k of them
  if (key.startsWith(workspaceId)...
}
```

A suggested hotfix:

- We do a full migration of localStorage into a single SQLite3 DB file
- For newly created workspace, copy over that SQLite3 DB file (this should be fast)
- After startup, start removing keys from the storage that's neither global nor workspace-specific

@sandy081 One of the reason I have 10k keys is the viewlet keys stored for each workspace:

![image](https://user-images.githubusercontent.com/4033249/48169759-5f3d3f80-e2a9-11e8-9642-8d3fc57d3d05.png)

**Comment by sandy081** [comment]
@octref Yes, these keys are to cache viewlet enablement and since it (custom viewlets) can happen per workspace have to store per workspace. Let me know if I can help here.

**Comment by isidorn** [comment]
Great investigation and great optimizations.

After looking a bit into this miself I just wanted to clarify something:
The migration code only gets triggered the first time you open a workspace. Not more.
However, it gets triggered every time a new no folder purple vscode is open.
Because of this we should not ship without a fix. Most of our users use purple vscode and this can slow down every time they startup vscode on a different file.

I have provided a PR https://github.com/Microsoft/vscode/pull/62775 which solves this by changing our storage to use the legacy chrome storage and by not doing the transition code. More details can be found in the PR.
The benefits of this approach is that it is not so risky, and the downsides are that we postpone the storage transition by one milestone.

This fix would still require testing.

**Comment by isidorn** [comment]
Closed via #62775 for October
@octref can you please take the latest unreleased stable build (I just triggered it) and verify you no longer see this issue on your laptop. Thank you very much

**Comment by octref** [comment]
Much better now. Adding bug label and marking as verified:

![image](https://user-images.githubusercontent.com/4033249/48274405-18119480-e3f8-11e8-901a-d520249cd2e5.png)

**Comment by bpasero** [comment]
Thanks for the investigation guys 🍻, good outcome 👍
