### ISSUE TITLE
Use inactive Terminal cursor when window is inactive

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#62736]
Cursor when terminal is focused: 
![image](https://user-images.githubusercontent.com/323878/48152855-ccd17780-e279-11e8-89b0-84989c6af998.png)

Cursor when editor is focused: 
![image](https://user-images.githubusercontent.com/323878/48152870-d5c24900-e279-11e8-9f6f-6d6a82d9c5cd.png)

But when the terminal is "focused" inside the window but a different app has OS focus, the filled in cursor is still used. If possible we should use the outline "inactive" cursor anytime the terminal doesn't have real keyboard focus.

**Comment by Tyriar** [comment]
I think this is fixed.
