### ISSUE TITLE
Inconsistent TSX indent cursor after end tag

### ISSUE THREAD

**Issue by dennisss** [microsoft/vscode#62748]
- VSCode Version: 1.29.0-insider
- OS Version: macOS 10.13.4

Steps to Reproduce:

1. Write two or more nested elements in TSX 
2. Make sure language mode is on "Typescript React"
3. Create a blank line after the inner end tag
4. Place cursor at very start of that blank line
5. Hit the tab keyboard key

**Observed Behavior:**
<img width="369" alt="screen shot 2018-11-07 at 6 30 19 pm" src="https://user-images.githubusercontent.com/1341104/48168473-56566900-e2bd-11e8-8fcd-89c40825a04b.png">

**Expected Behavior:**
<img width="365" alt="screen shot 2018-11-07 at 6 30 34 pm" src="https://user-images.githubusercontent.com/1341104/48168478-5ce4e080-e2bd-11e8-8e77-e2fdd0c4ea01.png">

Only seems to happen in some spots in the tree. Comparison of behavior in three different locations tested first in TSX, then in an HTML file. HTML mode indents correctly in all three cases. TSX doesn't work in third case:
![kapture 2018-11-07 at 18 28 51](https://user-images.githubusercontent.com/1341104/48168404-12fbfa80-e2bd-11e8-80da-ce910c411b8d.gif)

**Comment by GHTesting174** [comment]
Completely off-topic, but would you mind sharing what extension you're using to show HTML tag breadcrumbs at the top in the `Untitled-2` file? Or is this an Insiders feature? (I'm using the regular build.) Thanks.

**Comment by dennisss** [comment]
@GHTesting174 seems to only be in Insiders right no. No extensions are installed in the video

**Comment by mjbvz** [comment]
Closing due to lack of further user interest expressed in this issue over the past two plus years
