### ISSUE TITLE
Format on Save Using Incorrect Indentation on Multi-line Statements in TypeScript

### ISSUE THREAD

**Issue by berwyn** [microsoft/vscode#62742]
- VSCode Version: 1.28.2
- OS Version: macOS 10.14.1

Steps to Reproduce:
1. Write any number of multi-line statements (examples given below)
2. Ensure `typescript.formatOnSave` is enabled
3. Watch as various continuations are incorrectly out-dented to match their parents

The infuriating part is that the behaviour doesn't seem to be consistent. This doesn't happen when TSServer initially launches and seems to happen at some point _after_ launch, and can sometimes be fixed by reloading the window. As far as I can tell, at some point TSServer will get into a state where it suddenly doesn't like these indentations.

In this case, I'm not using any formatter extensions, the closest I've got in this case is the core TypeScript Language Services, Angular Language Service, and TSLint. With all extensions disabled, the error still occurs and the formatting will be incorrect.

Of note, other rules will continue to work correctly, _just_ continuations will fail. Additionally, it seems to happen more reliably in a Git submodule with its own {tsconfig,tslint}.json defined, even though the two sets of rules are largely the same (and in some cases, the outer Git repo's files are actually just empty extensions of the submodule's).

Does this issue occur when all extensions are disabled?: Yes

Examples:

```ts
// Code as written
const someReallyLongIdentifier
  = someMethodInvocation();

someObservable$.withLatestFrom(
  someOtherObservable$,
  aThirdObservable$
)

someArray.reduce(
  (acc, cur) => // some expression body,
  new Map()
)

// This one is rare and much more inconsistent
someFunc()
  .chain()
  .chainAgain()
  .chainYetAgain()
  // etc

// Gets formatted to
const someReallyLongIdentifier
= someMethodInvocation();


someObservable$.withLatestFrom(
someOtherObservable$,
aThirdObservable$
)

someArray.reduce(
(acc, cur) => // some expression body,
new Map()
)

someFunc()
.chain()
.chainAgain()
.chainYetAgain()
// etc
```

**Comment by berwyn** [comment]
One more step of further weirdness I've discovered. Normally, I run the Angular compiler inside a Docker container with my workspace mounted as a volume. Additionally, the Angular compiler is typically watching for changes and recompiling my app in the background. Today, I was in a workflow where I didn't necessarily need the compiler up and running and so eschewed it and just leaned on the editor to check my files until I was ready to run a compile step.

This is where the next bit of weirdness crops up; As long as the compiler isn't watching and compiling the files in the background, the files in the submodule are being formatted correctly. I'm not sure now whether Docker, Angular CLI, git submodules, or some combination of the above is the primary factor, but the combination of the three seems to be what aggravates the issue the most.

**Comment by mjbvz** [comment]
I cannot repo this. Can you please test in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled.

If you still see the issue:

* Does it happen in all projects you try it in, or only in particular?
* Are the specific steps that trigger this?
