### ISSUE TITLE
PSCustomObject Accelerator Intellisense Formatting

### ISSUE THREAD

**Issue by mpearon** [Microsoft/vscode#62744]
### Details Output
```
### VSCode version: 1.28.2 7f3ce96ff4729c91352ae6def877e59c561f4850 x64

### VSCode extensions:
aaron-bond.better-comments@2.0.2
alexcvzz.vscode-sqlite@0.3.1
Compulim.vscode-clock@0.0.1
DotJoshJohnson.xml@2.3.2
fabiospampinato.vscode-github-notifications-bell@2.1.1
GrapeCity.gc-excelviewer@2.1.26
hoovercj.vscode-power-mode@2.2.0
johnstoncode.svn-scm@1.45.0
le0zh.vscode-regexp-preivew@0.0.3
mkloubert.vscode-remote-workspace@0.36.5
ms-mssql.mssql@1.4.0
ms-vscode.PowerShell@1.9.0
ms-vsliveshare.vsliveshare@0.3.869
ms-vsliveshare.vsliveshare-audio@0.1.39
rafaelmaiolla.remote-vscode@1.1.0
Shan.code-settings-sync@3.2.0
shyykoserhiy.git-autoconfig@0.0.1
WakaTime.vscode-wakatime@1.2.3
xyz.local-history@1.7.0
yzhang.markdown-all-in-one@1.7.0

### PSES version: 1.9.0.0

### PowerShell version:

Name                           Value
----                           -----
PSVersion                      5.1.17134.228
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.228
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description
When using the [PSCustomObject] Accelerator, the initial `[` is not removed.

#### Expected Behaviour
I think that the if an initial `[` is detected, it should be removed.

#### Actual Behaviour
The `[` is duplicated when using Tab and when selecting the autocomplete option.
I've seen that if I type `PSCustomObject`, then hit tab or select the option, the bracket is not added - but I naturally begin typing the actual expression.  Maybe I'm being a bit too picky.

### Attached Files
![pscustomobjectformatting](https://user-images.githubusercontent.com/7157790/47732868-11836000-dc35-11e8-9ddc-f24176d589e2.gif)

**Comment by jrieken** [comment]
This seems to be snippet completion. Is that a default snippet that ships with the extensions?

**Comment by mpearon** [comment]
Sorry @jrieken, I guess I missed this response!
Yes, this is a default.

**Comment by rjmholt** [comment]
@jrieken Is this a problem with the snippet itself? Is there anything the PowerShell extension should change to fix this?

**Comment by rjmholt** [comment]
[Here](https://github.com/PowerShell/vscode-powershell/blob/79848af29ea3707603848a613d1bfac4fa9ec090/snippets/PowerShell.json#L929-L937)'s the snippet itself
