### ISSUE TITLE
tabsize is always 2, setting ingored. applies when using prettier as well

### ISSUE THREAD

**Issue by urbanhop** [microsoft/vscode#62740]
Issue Type: <b>Bug</b>

I configured tabsize wherever i can to 4. i used prettier but even when i disable prettier (and certainly reload) then the setting 

"editor.tabSize": 4

is totally ignored, for all file types.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.70GB (17.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-backtix|adi|1.1.1
Bookmarks|ale|9.0.3
spellright|ban|2.5.32
npm-intellisense|chr|1.3.0
githistory|don|0.4.1
vscode-npm-script|eg2|0.3.5
vscode-highlight|fab|1.2.2
color-scheme-selector|hen|0.2.0
output-colorizer|IBM|0.1.2
Ionide-fsharp|Ion|3.22.2
theme-rusty-icons|ion|0.0.1
vscode-icon-theme|jtl|1.6.2
vscode-position|jtr|1.0.1
favorites|kdc|1.9.1
vscode-typescript-ast-explorer|kri|1.0.0
vscode-simple-icons|Lau|1.8.3
xml-format|mik|1.0.0
csharp|ms-|1.15.2
vetur|oct|0.12.5
vscode-code-outline|pat|0.2.1
vscode-versionlens|pfl|0.21.1
easy-compile|ref|1.1.2
highlight-words|rsb|0.0.7
preact-preact-router-snippets|sar|0.1.2

(21 theme extensions excluded)

</details>

**Comment by urbanhop** [comment]
more information:

when i acreate a new file, then the tabsize setting is correctly applied. but that size sticks to the document. so the **tabsize for a document is freezed at creation time**. weird!!!

history:
no document reacts to changing tab size in settings
all files use tabsize 2

create a new file myfile.ts  WHILE tabsize is 7
formatting in myfile.ts uses tabsize 7
formatting in other files NOT

change tabsize setting to 5
formatting in myfile.ts stil uses tabsize 7
all other files still use tabsize 2

**Comment by christianscheuer** [comment]
Prettier has completely stopped working recently in VSCode. It's like there's a new internal VSCode formatter installed for Javascript which takes precedence, or something is broken entirely. This is a pretty nasty bug since it affects all commits and if we're not careful to manually format exactly like Prettier would've done we're now introducing so much whitespace and formatting noise... Would be nice if there was added some tests for prettier integration so that this does not regress in the future.
