### ISSUE TITLE
Invisible context menu on MacOS

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#62756]
- Just installed MacOS 10.14.1
- Have missing import in file
- Trigger quick fixes with `cmd+.`
- Context menu doesn't appear
- But keyboard input goes to an invisible context menu instead of the editor, eg I can press down, then enter, and autoimport happens

Also, it only happens when vscode is on my second monitor.

I saw this happen a few times randomly, then I came across one error where it happens very regularly. Trying some other similar errors, I can't get it to happen.

I can't get this to happen by right clicking or with shift+f10, just invoking quick fixes... ???

**Comment by mjbvz** [comment]
Adding @bpasero since this sounds electron related

**Comment by roblourens** [comment]
Today I can't repro with the same setup and same place in code. I'll watch out for it.

**Comment by roblourens** [comment]
I have seen this once since last week but still can't repro it enough to debug more.
