### ISSUE TITLE
Folder with git repo on MacOS keeps crashing.

### ISSUE THREAD

**Issue by abetrs** [Microsoft/vscode#62754]
- VSCode Version: 1.28.2
- OS Version: MacOS 10.12

Steps to Reproduce: 
Run a folder with git repository on vscode.

Does this issue occur when all extensions are disabled?: Yes/No
Yes.

**Comment by abetrs** [comment]
Stops if git integration is disabled

**Comment by joaomoreno** [comment]
What do you mean by _crashing_? Can you share a screenshot, or a screen recording?

**Comment by abetrs** [comment]
I get a pop up that says that the editor has crashed and I need to quit and restart it. Then it happens again in the course of the next 10-20 minutes. All the times this has happened has one thing in common: my workspace folder was a git repo. This never happens if I am not in a git repo.

**Comment by joaomoreno** [comment]
Please share a screenshot of that message. Also, try running with `code --disable-extensions` for a while and see if the issue still reproduces.

**Comment by abetrs** [comment]
I fixed it by reinstalling VSCode. Guess it was a just my installation
