### ISSUE TITLE
The minimum size of a terminal should be an option in Settings

### ISSUE THREAD

**Issue by Tumiz** [microsoft/vscode#62759]
[(https://github.com/Microsoft/vscode/issues/45678)]
The related issue was closed, but I think it need more work!
Some terminal can be resized to a small size if they are not important. In some case, showing multiple terminals is just to notify the user whether they are running. Currently the minimum size of terminal is fixed and too large.
I suggest that the minimum size of a terminal should be an option in Settings.

**Comment by Tyriar** [comment]
@Tumiz do you have a better suggestion for the minimum size (currently 250px)? #45678 was purely to prevent a broken layout in the terminal space and having terminals get hidden.

**Comment by Tumiz** [comment]
![image](https://user-images.githubusercontent.com/7362124/49349848-825fe100-f6e7-11e8-8462-5f25ed668ecf.png)

Some terminal is OK as small like this. In this case, I only need a few lines to show a program's status. So partly hidden is also acceptable.  
It will be better if the minimum size can be configured in Settings.
