### ISSUE TITLE
vscode won't start on my Ubuntu, and `$ code --verbose` gives no output

### ISSUE THREAD

**Issue by foodtooth** [Microsoft/vscode#62752]
- OS Version:Ubuntu 16.04.5 LTS x86_64

Does this issue occur when all extensions are disabled?: Yes

I run a ubuntu 16.04 on remote, and access it via vnc server. The vscode just can't start. I've been googling around. Then answers from [Cannot open Visual Studio Code][1] don't work.

    $ code --verbose # this gives no output

    $ bash --debugger -x `which code`
    /usr/bin/code: /usr/share/bashdb/bashdb-main.inc: No such file or directory
    /usr/bin/code: warning: cannot start debugger; debugging mode disabled
    ++ id -u
    + '[' 1000 = 0 ']'
    + '[' '!' -L /usr/bin/code ']'
    + which readlink
    +++ readlink -f /usr/bin/code
    ++ dirname /usr/share/code/bin/code
    + VSCODE_PATH=/usr/share/code/bin/..
    + ELECTRON=/usr/share/code/bin/../code
    + CLI=/usr/share/code/bin/../resources/app/out/cli.js
    + ELECTRON_RUN_AS_NODE=1
    + /usr/share/code/bin/../code /usr/share/code/bin/../resources/app/out/cli.js

    # this command stopped at here. stuck.

And some workaround from [vscode github issue 862][2] do not work. Assign SHELL to whatever it recommend ends up with no luck.

  [1]: https://askubuntu.com/questions/1022923/cannot-open-visual-studio-code
  [2]: https://github.com/Microsoft/vscode/issues/862

**Comment by sitsofe** [comment]
This sounds like issue issue #3451 ...

**Comment by foodtooth** [comment]
> This sounds like issue issue #3451 ...

That workaround gives no difference... I may just upgrade to 18.04 to see whether it has been fixed
