### ISSUE TITLE
VS Code v1.28.2 on 2015 MacBook Pro 15 inch on macOS 10.14.1 High CPU Usage

### ISSUE THREAD

**Issue by JosephTLyons** [Microsoft/vscode#62757]
Issue Type: <b>Performance Issue</b>

I'm not doing anything special, just editing a few C++ files and I noticed my macbook heating up quite a  bit and my battery draining extremely fast.  I then checked the CPU usage and the cores were jumpuing up to 40 and even 50 percent usage (this is a 2.8 gHz quad core i7).

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (1.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   16	   115	  6721	code main
    5	    82	  6722	   gpu-process
    7	   295	  6723	   window (process.cc — CSCI-B 424 Homework 10)
    0	     0	  6729	     /bin/bash -l
    0	    66	  6732	     extensionHost
    0	    33	  6736	       /Users/josephlyons/.vscode/extensions/ms-vscode.cpptools-0.20.1/bin/Microsoft.VSCode.CPP.Extension.darwin
    0	   131	  6755	         /Users/josephlyons/.vscode/extensions/ms-vscode.cpptools-0.20.1/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.darwin 6736 0
    0	    49	  6734	     watcherService
    4	    82	  6756	   shared-process
   38	    82	  6758	   window (Issue Reporter)
    0	     0	  6759	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (process.cc — CSCI-B 424 Homework 10)
|    Folder (CSCI-B 424 Homework 10): 12 files
|      File types: cc(3) o(3) h(2) gitignore(1) pdf(1)
|      Conf files: makefile(1);
```

</details>
<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-open-native-terminal|ale|1.4.0
better-toml|bun|0.3.2
file-icons|fil|1.0.16
vscode-rust|kal|0.4.2
Lisp|mat|0.1.8
cpptools|ms-|0.20.1
rust|rus|0.4.10
pdf|tom|0.3.0
vscode-terminal-here|Tyr|0.1.1
licenser|ymo|1.3.1

</details>

**Comment by JosephTLyons** [comment]
The workspace information may not be correct, while I was in that same exact project, I switched to different files before discovering there was a performance reporting tool inside of VS Code.  Had I of known that previously, I would've not touched the project before reporting.

**Comment by chrmarti** [comment]
Please follow https://github.com/Microsoft/vscode/wiki/Performance-Issues when this happens again.

**Comment by jrieken** [comment]
@JosephTLyons in case this affects the UI process, e.g. the cursor freezes, that please jump straight to this guide: https://github.com/Microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process

**Comment by JosephTLyons** [comment]
@jrieken , I don't think there were any UI issues when I ran into this issue, but I'll keep a look out next time.

**Comment by jrieken** [comment]
closing because no actionable information is present
