### ISSUE TITLE
VScode couldn't run without Internet

### ISSUE THREAD

**Issue by zaylezou** [Microsoft/vscode#62750]
If I have access to Internet, I can run VScode normaly;
but without Internet, it couldn't run.
If I open it with cmd command "code", it will give error information:
-------------------------------------------------
dns.js:246
    this._handle = new ChannelWrap();
                   ^

Error: EFILE
    at new Resolver (dns.js:246:20)
    at dns.js:377:25
    at dns.js:431:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at net.js:45:13
    at net.js:1730:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at internal/child_process.js:6:13
-----------------------------------------------
even if I don't have access to the Internet actually, but I have wlan icon on the task bar, I can run VScode correctly.
The problem appeared yesterday.

**Comment by SimonLoir** [comment]
#59477

**Comment by mjbvz** [comment]
Duplicate of #7570
