### ISSUE TITLE
Default formatter if no formatter is installed.

### ISSUE THREAD

**Issue by Domvel** [Microsoft/vscode#62765]
For some files, there are no formatters. e.g. Unity shaderlab file (*.shader). Whatever ...
`There is no document formatter for 'shaderlab'-files installed`

My feature request is about to enable an option 
"Use default formatter": "The simple default format is used if no specific formatter is installed."

**What does the default formatter?**

- Remove multiple empty lines. Only one empty line between code blocks!
- Remove multiple tabs (spaces) from indent. (use editor settings for tab type) `*`
- [Any other idea?]

`*` For this feature, the formatter needs to know who to set indents. Maybe by an additional option for code blocks like `{}` (most cases) or just count the existing length of spaces between begining of line and number of whitespaces and use this for the level of ident.

Special features:
- Remove multiple spaces. Only one space between words. BUT this feature is only possible if the formatter knows the comment and quote syntax. In most of cases its `//` and `"` or `'`. But this can be additional settings. This should ignore strings (quotes).

Already implemented by other features and does not really need the default formatter:
- Trim trailing whitespaces. (files.trimTrailingWhitespace)
- Trim final new lines (files.trimFinalNewlines)
- Insert final newline (files.insertFinalNewlines)

The formatter steps could looks like (indent example):
1. Remove all spaces from beginning of a line (regex example `^[\s]+`)
2. Add tabs (spaces) at the beginning of the line by level character e.g. `{` (set by user option) reduce level on `}`.

What you think? Is this possible? Or to complex or impossible. Write a formatter extension is required.

Current version of VS Code: 1.28.2 

Tutorial - [Creating a Formatter Extension](https://code.visualstudio.com/blogs/2016/11/15/formatters-best-practices)

I think I going to write my own formatter ... :)

**Comment by Domvel** [comment]
I thinks it's no duplicate. 

I think the default formatter only need some informations about ident formatting.

Options:
* Increase indent level on character: `{` 
* Decrease indent level on character: `{`

**Comment by jrieken** [comment]
You can do this as extension. If you register a formatter for the `*` language it will be used whenever no other, more specific, formatter is registered, e.g the prettier formatter extension. The API should be rich enough to support this scenario. Closing as extension candidate but I can help with more questions.
