### ISSUE TITLE
Scrolling with two-finger touch in jerky.

### ISSUE THREAD

**Issue by coobit** [Microsoft/vscode#62769]
Issue Type: <b>Bug</b>

Open any file in VScode.
Put two fingers on a touchpad.
Move fingers.
Scrolling will not respond at first, but then will jerk screen more than you expect.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.88GB (7.70GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-ru|MS-|1.28.2
python|ms-|2018.9.2

</details>

**Comment by chrmarti** [comment]
Do you have smooth scrolling enabled?
![image](https://user-images.githubusercontent.com/9205389/48191693-0cfe2c00-e346-11e8-91ea-368bdb4be2e6.png)

**Comment by coobit** [comment]
This particular option didn't help, but when looking for 'smooth' I've found out 'Smooth Scrolling Workaround' in the same 'Text Editor' settings page and it worked. :) Thanks for a hint. Guess we can close the issue.

**Comment by isidorn** [comment]
@coobit can you please do me a favor and verify that the same setting also works nicely with vscode insiders https://code.visualstudio.com/insiders/
Thanks a ton!

**Comment by coobit** [comment]
To tell you the truth, It has stopped working on my pc. So there is no need in checking insider's version.
I've checked all 'smooth scrollong' and 'smooth scrolling workaround' checkboxes.

It just stopped working after some time. So .... 


>Четверг,  8 ноября 2018, 16:56 +03:00 от Isidor Nikolic <notifications@github.com>:
>
>@coobit can you please do me a favor and verify that the same setting also works nicely with vscode insiders  https://code.visualstudio.com/insiders/
>Thanks a ton!
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Логвиненко Евгений

**Comment by coobit** [comment]
![image](https://user-images.githubusercontent.com/25038006/48304340-43e06780-e529-11e8-8a03-aa1f6ee0e5d7.png)
Checked all the checkboxes, but still jerking stops for some time only after remaximizing the VSCODE window.

**Comment by isidorn** [comment]
Update to latest windows version please
