### ISSUE TITLE
Provide an editor action to open Settings and Keybindings editor UI from JSON files

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#62768]
There is an editor title action in Keybindings and Settings editor to navigate to respective json files. A similar action would be good and consistent to navigate from json to UI.

**Comment by misolori** [comment]
@sandy081 can you use the same icon as Markdown's "Go to source"?

![image](https://user-images.githubusercontent.com/35271042/48213553-f7333b80-e332-11e8-8be5-54f1b1d0a981.png)

https://github.com/Microsoft/vscode/blob/master/extensions/markdown-language-features/media/ViewSource.svg

**Comment by sandy081** [comment]
@sandy081 I think it is not going to the source/file. Action should navigate user from source to preview (UI)

**Comment by misolori** [comment]
Can you use the same one as @roblourens (the curly brackets)?

![image](https://user-images.githubusercontent.com/35271042/48725238-6be26180-ebe0-11e8-9a1c-cc382cae00e1.png)


**Light**
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/preferences/electron-browser/media/edit-json.svg

**Dark**
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/preferences/electron-browser/media/edit-json-inverse.svg

**Comment by sandy081** [comment]
Here are some icons. 

- Icon to open Settings/Keybindings file
![image](https://user-images.githubusercontent.com/10746682/48765059-ac5de000-ecb1-11e8-857b-24d99ac6767c.png)

- Icon to open Settings/Keybindings UI
![image](https://user-images.githubusercontent.com/10746682/48765146-dca57e80-ecb1-11e8-804a-247c34e2aab6.png)

- Icon to open Settings/Keybindings UI
![image](https://user-images.githubusercontent.com/10746682/48765209-f646c600-ecb1-11e8-8eec-c0ca922f918d.png)

All of them have gear icon overlaid which might help users to know this action is related to preferences (settings/keybindings)

What do you think?

**Comment by misolori** [comment]
I like the gear idea, even though it does mean "Settings" but we use that for configuration in Debug as well. What if did the second option but pinned the gear to the top left corner?

<img width="30%" src="https://user-images.githubusercontent.com/35271042/48793141-e2e42c80-ecaa-11e8-9a8b-1c85c2e5a6cf.png" />

**Comment by sandy081** [comment]
Gear icon on the top left corner is ok for me.

- We can continue using `{ }` icon to take to json editor.
- Use the new `gear` icon to take to the preview.

Can you please provide the icon with gear on top left corner?

**Comment by misolori** [comment]
@sandy081 sent!

**Comment by sandy081** [comment]
Added this action for both Keybindings and Settings files. 

![image](https://user-images.githubusercontent.com/10746682/48912915-2d1a0900-ee77-11e8-9b02-162e1eae5016.png)


![image](https://user-images.githubusercontent.com/10746682/48912902-268b9180-ee77-11e8-9752-30b491e8f5c1.png)


@roblourens FYI
