### ISSUE TITLE
phpcs: Request workspace/configuration failed with message: Unable to locate phpcs. Please add phpcs to your global path or use composer dependency manager to install it in your project locally.

### ISSUE THREAD

**Issue by caocuong2404** [Microsoft/vscode#62764]
Issue Type: <b>Bug</b>

phpcs: Request workspace/configuration failed with message: Unable to locate phpcs. Please add phpcs to your global path or use composer dependency manager to install it in your project locally.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (2.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
vscode-intelephense-client|bme|0.8.8
npm-intellisense|chr|1.3.0
laravel-goto-view|cod|1.2.3
es7-react-js-snippets|dsz|1.9.0
vscode-html-css|ecm|0.2.0
vscode-npm-script|eg2|0.3.5
react-native-react-redux|EQu|1.9.2
php-debug|fel|1.12.6
php-intellisense|fel|2.3.5
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.5
beautify|Hoo|1.4.7
minify|Hoo|0.3.0
phpcs|ika|1.0.5
vscode-gutter-preview|kis|0.16.3
debugger-for-chrome|msj|4.11.0
laravel-blade|one|1.18.0
laravel5-snippets|one|1.5.0
advanced-new-file|pat|1.2.0
material-icon-theme|PKi|3.6.0
vscode-icons|rob|7.28.0
laravel-artisan|rya|0.0.23
open-in-browser|tec|2.0.0
pdf|tom|0.3.0
vscode-react-native|vsm|0.6.18

(3 theme extensions excluded)

</details>

**Comment by chrmarti** [comment]
It appears you need to add the PHP CodeSniffer to your PATH environment variable in order to make the PHPCS extension for VS Code work.
