### ISSUE TITLE
type script files are not opening as default 

### ISSUE THREAD

**Issue by yash59** [Microsoft/vscode#62761]
Issue Type: <b>Bug</b>

when i am setting VS code as default for opening .ts file it's not wokring.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (2.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
java|red|0.33.0
vscode-java-debug|vsc|0.15.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.10.0
vscode-maven|vsc|0.11.1

</details>

**Comment by chrmarti** [comment]
Is this a issue with Windows 10? Please see: https://answers.microsoft.com/en-us/windows/forum/all/windows-10-always-open-with-doesnt-work/eea098a9-65e4-444c-acfc-2ea94d3140a8

**Comment by chrmarti** [comment]
#62732

**Comment by chrmarti** [comment]
#62732
