### ISSUE TITLE
Beta releases

### ISSUE THREAD

**Issue by kaflan** [Microsoft/vscode#6276]
Beta releases are ? Or Studio code will be steadily updated each month?

**Comment by DickvdBrink** [comment]
They do have the insiders build:
https://code.visualstudio.com/Download#insiders

That is the place where you get the new stuff early. The new stuff can be found in the `iteration-plans`: https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=label%3Aiteration-plan+

**Comment by kaflan** [comment]
@DickvdBrink  senk you  I google and search saite not found senk

**Comment by Tyriar** [comment]
Insider's builds which are every week or so are currently available. The nightly builds used by the dev team are also on the way https://github.com/Microsoft/vscode/issues/5453
