### ISSUE TITLE
Lagging too much

### ISSUE THREAD

**Issue by 9i8s** [Microsoft/vscode#62762]
Issue Type: <b>Bug</b>

Why it is lagging too much when i try to take backspace to erase any thing? Please help as soon as possible.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G4400 @ 3.30GHz (2 x 3312)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.91GB (1.53GB free)|
|Process Argv|C:\Users\9i8s\AppData\Local\Temp\scp08577\var\www\html\restaurant\application\config\routes.php|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.7.0
auto-rename-tag|for|0.0.15
code-runner|for|0.9.5
beautify|Hoo|1.4.7
Angular-BeastCode|Mik|7.0.14
notepadplusplus-keybindings|ms-|1.0.2
vscode-css-peek|pra|2.1.0
bootstrap4-vscode|the|4.3.0
highlight-matching-tag|vin|0.8.1

</details>

**Comment by chrmarti** [comment]
Could you attach a recording?

**Comment by 9i8s** [comment]
Sure, i think one of the extensions stop working i'll send you soon on next lagg

**Comment by jrieken** [comment]
Also try to CPU profile this. Hit F1 > Toggle Developer Tools. In the overflow menu select 'More Tools > JavaScript Profiler'. In there select start, let it profile for 30 to 60 seconds, stop it, save it to a file and attach the file here. Thanks.

<img width="380" alt="screen shot 2017-09-28 at 09 44 31" src="https://user-images.githubusercontent.com/1794099/30954796-d1be9e30-a431-11e7-959e-495d234c37c6.png">

**Comment by 9i8s** [comment]
Now, Working fine in 1.29.1 not any lag.
