### ISSUE TITLE
"Unable to load compilation data: No root directory found"

### ISSUE THREAD

**Issue by joelonsql** [Microsoft/vscode#62766]
- VSCode Version: 1.28.2 7f3ce96ff4729c91352ae6def877e59c561f4850
- OS Version: macOS 10.14.1

Steps to Reproduce:

1. Reinstall VS Code, install jaredly.reason-vscode
2. Open up any .ml file

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by chrmarti** [comment]
This issue was moved to jaredly/reason-language-server#177
