### ISSUE TITLE
Editor Flickers inside #region tags on higher resolutions

### ISSUE THREAD

**Issue by ztzven** [Microsoft/vscode#62763]
- VSCode Version: 1.28.2
- OS Version: Ubuntu 18.04.1
- Window Size: Greater than 1080p
- GPU: ATI RX580

Steps to Reproduce:

1. Create a large (full viewport) #if #else #endif region of C / C++ code
2. View a greyed out region of code (excluded region)
3. Only bits of code will appear and the entire window glitches, with sections of the window glitching in and out at random.

Does this issue occur when all extensions are disabled?: Yes, with or without

Below is a screenshot of the issue

![screenshot at 2018-11-08 19-48-09](https://user-images.githubusercontent.com/860865/48182229-51fa8080-e38f-11e8-9874-348ab24be0c3.png)

**Comment by chrmarti** [comment]
Could you attach a recording?

**Comment by alexandrudima** [comment]
This looks incredibly similar to #56732 , so let's track there ...
