### ISSUE TITLE
Add option to convert all tabs to spaces (not only indentation)

### ISSUE THREAD

**Issue by GoTo-Romania** [Microsoft/vscode#6277]
- VSCode Version: 1.0.0
- OS Version: Windows 7

Steps to Reproduce:

1. Create new file.
2. Insert text like:

aaa`<TAB>`bbbb
aaaaaa`<TAB>`bbbb
aaaaaaaa`<TAB>`bbbb

3. Go to File/Preferences/User Settings and add this line "editor.tabSize": 10
4. Check all Bs from step 2 are aligned on the left side. Check As and Bs are separated by one tab and not by spaces.
5. Implement option "Convert Tabs to Spaces" such that after the conversion, the way the text is displayed does not change (take into account that a `<TAB>` has a variable width when it is displayed on the screen). This conversion should work for all tabs in a document, not only for identation.

**Comment by isidorn** [comment]
We already have a convert indentation to spaces, and convert intdentation to tabs actions. You can find them by clicking on the lower right corner tab size, or spaces

Check it out

**Comment by GoTo-Romania** [comment]
"This conversion should work for all tabs in a document, not only for identation."

**Comment by isidorn** [comment]
I have reasoned about why this should not be part of VSCode but an extension here
https://github.com/Microsoft/vscode/pull/7582
