### ISSUE TITLE
Only one class file can be viewed

### ISSUE THREAD

**Issue by iMinusMinus** [Microsoft/vscode#62770]
- VSCode Version: 1.28.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open a (java)class file like 'org.springframework.web.context.support.AnnotationConfigWebApplicationContext', use 'Ctrl' and left click open parent class.
2. Previous class automate closed! And only one class can be viewed.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by chrmarti** [comment]
Try disabling editor preview:
![image](https://user-images.githubusercontent.com/9205389/48191859-8ac23780-e346-11e8-8e65-8f91ac45ef2a.png)
