### ISSUE TITLE
Simple print command not working

### ISSUE THREAD

**Issue by roberti** [Microsoft/vscode#62771]
Issue Type: <b>Bug</b>

the code in file foo.py is:
```
# simple print
print('hell')
```

The result is:
Exception has occurred: AttributeError
'NoneType' object has no attribute 'write'
  File "C:\Projetos\Faculdade\POO\python\datas.py", line 4, in <module>
    print('hell')

It is working perfectly in python console. Does not work in Visual Studio Code.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.86GB (2.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
anaconda-extension-pack|ms-|1.0.1
python|ms-|2018.9.2

</details>

**Comment by chrmarti** [comment]
How do you run the file from VS Code? What is the Python console you mention?

**Comment by roberti** [comment]
It is really that simple as it sounds. But, lets go...

_How do you run the file from VS Code?_ (F5, configured to run in integrated terminal) 
What is the Python console you mention? (VS Code console, type python and voila. From command prompt type python and voila!)

**Comment by roberti** [comment]
Even other simple samples are not running on VS Code like this one.
```
from flask import Flask
app = Flask(__name__)

@app.route("/")
def hello():
    return "Welcome to machine learning model APIs!"

if __name__ == '__main__':
    app.run()
```
The error: 
xception has occurred: AttributeError
'NoneType' object has no attribute 'isatty'
  File "C:\Projetos\Faculdade\POO\python\foo.py", line 9, in <module>
    app.run()

**Comment by chrmarti** [comment]
This issue was moved to Microsoft/vscode-python#3272
