### ISSUE TITLE
VS Code should be able to handle file:// URIs

### ISSUE THREAD

**Issue by perlun** [microsoft/vscode#62777]
- VSCode Version: Version: 1.28.2
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:20:56.183Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
- OS Version: Debian buster/sid

Steps to Reproduce:

1. Ctrl-Click an HTML `file://` URL in `gnome-terminal` like `file:///home/per/git/myproject/build/reports/spotbugs/main.html`
2. A new VSCode window opens, but with an empy `Untitled-1` file instead of the file I tried opening.

No error is shown in the developer console (I verified).

This _seems_ like #25987 have come back, in one form or the other.

For reference, here is the `code.desktop` file:

```ini
$ cat /usr/share/applications/code.desktop
[Desktop Entry]
Name=Visual Studio Code
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=/usr/share/code/code --unity-launch %F
Icon=code
Type=Application
StartupNotify=true
StartupWMClass=Code
Categories=Utility;TextEditor;Development;IDE;
MimeType=text/plain;inode/directory;
Actions=new-empty-window;
Keywords=vscode;

X-Desktop-File-Install-Version=0.23

[Desktop Action new-empty-window]
Name=New Empty Window
Exec=/usr/share/code/code --new-window %F
Icon=code
```

Does this issue occur when all extensions are disabled?: Yes/No

Can't really try. :cry:

**Comment by perlun** [comment]
For the sake of it, I installed `code-insiders` also - it didn't register a handler for `file:///` URLs apparently, so they started opening in Firefox instead. (I uninstalled my regular `code` package.)

Reinstalled code, and now the bug is back again.

**Comment by joaomoreno** [comment]
I don't think Code ever registered a handler for `file://` at all. It does register itself as a handler for `vscode://` uris, though. If this worked before, was it maybe because you edited the `code.desktop` file, or maybe you configured the OS to use Code for `file://` uris?

**Comment by perlun** [comment]
@joaomoreno Hmm, that's interesting. I just tried and the error still persists on my machine. vscode 1.29.1-1542309157.

As noted, when I uninstalled code and reinstalled it, the behavior changed - so I'm fairly certain it has to do with vscode, or some local config causing it to malfunction.

Any idea where I should start digging?

**Comment by joaomoreno** [comment]
This was simply never implemented.

**Comment by perlun** [comment]
Thanks @joaomoreno, it would be great to see this fixed at some point.
