### ISSUE TITLE
No space in the status bar

### ISSUE THREAD

**Issue by timurmamedov** [Microsoft/vscode#62776]
There is virtually no space in the status bar.

I am using a portrait-oriented monitor and using vim plugin. And as a vim user it is so important for me to see what mode I am in or what I am typing after : or /. But since other plugins are using so much space in the status bar I can't even see when I am in INSERT or other modes, or what I am searching because they all sit on top of each other. Other plugins literally block vim from appearing. 

Please allow customizability of the status bar. I can't use vscode until it is possible to do, which is sad because it is such a great editor.

**Comment by usernamehw** [comment]
There is an open issue to hide status bar items: #3874. Is that what you mean?
