### ISSUE TITLE
Retour à la ligne

### ISSUE THREAD

**Issue by Hashdow** [microsoft/vscode#62781]
Issue Type: <b>Feature Request</b>

Bonjour, comment rendre permanent le retour à la ligne svp, vos tutoriels en ligne ne sont pas à jour.

Merci d'avance.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

**Comment by chrmarti** [comment]
/duplicate https://github.com/Microsoft/vscode/issues/12223 if I understand correctly.

**Comment by Hashdow** [comment]
Ok, thank you for your answer, but is incredible, i just want to configure a automatic back to line in the editor. I know with a old version, but with the new one i'm lost, lika ALT + Z but aneble automaticly.
Visual code is great, but why is so complicated to do something so easy anywhere else.

Thank you

**Comment by chrmarti** [comment]
/needsMoreInfo

Could you describe with bullet points what the expected behavior is and then what the actual behavior is?

**Comment by amynbe** [comment]
If you're looking how to make word wrapping default, go to File > Preferences > Settings and search for "editor.wordWrap"

**Comment by chrmarti** [comment]
Closing as obsolete.

**Comment by Hashdow** [comment]
thanks

Le jeu. 24 oct. 2019 à 10:42, Christof Marti <notifications@github.com> a
écrit :
