### ISSUE TITLE
Copy action in debug console is inserting empty lines between each line

### ISSUE THREAD

**Issue by apupier** [Microsoft/vscode#62785]
- VSCode Version: 1.28.2 (user setup)
- OS Version: Windows 10

Steps to Reproduce:

1. right-click in terminal, "Copy all"
2. paste it in notepad for instance
it occurs also when creating a new file in VS Code and pasting in it.

you can se the terminal log without empty lines at the bottom and the pasted content in the editor
![image](https://user-images.githubusercontent.com/1105127/48202746-041d5280-e366-11e8-9755-8798791622ce.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by apupier** [comment]
this is not a duplicated of the mentioned issue

**Comment by leonm1** [comment]
This bug only seems to happen in the Debug Console, not the integrated terminal.

Was not able to reproduce on Arch Linux, but I could repro on Windows 10.
