### ISSUE TITLE
look-around, look-behind... not is not supported in find in files

### ISSUE THREAD

**Issue by ntfshard** [Microsoft/vscode#62782]
Issue Type: <b>Bug</b>

Try to use regexp   foo(?!b)    in search in files. You will get a red square error.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.88GB (16.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.20.1

</details>

**Comment by YisraelV** [comment]
@ntfshard similar question has been asked before  #41493

**Comment by chrmarti** [comment]
/duplicate https://github.com/Microsoft/vscode/issues/41493#issuecomment-357109522
