### ISSUE TITLE
Unwanted autocompletions at the end of sentences

### ISSUE THREAD

**Issue by Timmmm** [Microsoft/vscode#62786]
This has annoyed me for a while. Quite often I write a comment like this:

    // This is a comment.

If you're typing this normally, you get to the full stop (period) at the end, and then depending on which language/extension you are using it will pop up a totally incorrect autocomplete suggestion very quickly, you then press enter, and you end up with

    // This is a comment.alloc

This is a real example using Rust (but this is not unique to Rust):

![image](https://user-images.githubusercontent.com/376842/48203500-92daa100-e35f-11e8-937e-416fb788965e.png)

This is really annoying and I don't know a good way to make it not do that. As a general solution I would say VSCode should:

1. **Measure the time between the autocomplete request and when you press enter.**
2. **If it is less than some threshold (I'd guess around 0.3s) then enter should insert a newline.** After that it should insert the autocomplete suggestion.

I would *not* suggest delaying the actual autocomplete popup because that will make VSCode feel more laggy, and it would make you wait before you can start reading the suggestions.

An alternative (maybe better?) solution would be to provide an option to **never suggest autocompletions in comments** (detected via syntax highlighting). This issue mostly occurs in comments and I doubt people actually use autocomplete in comments much.

**Comment by jrieken** [comment]
It's the extension compute the suggestion. How/when/where suggestions as you are requested can be configured via `editor.quickSuggestions`

**Comment by Timmmm** [comment]
No, sorry I thought I was clear enough but apparently not:

>  this is not unique to Rust

This is a problem with *many* extensions. I don't think it is feasible to fix them all. And also the only way to fix this for non-comment code is to change VSCode itself - it *can't* be fixed in extensions.

`editor.quickSuggestions.comments` is already set to false by default yet I still get suggestions in comments. Is this just a bug?
