### ISSUE TITLE
intellisence for node js modules

### ISSUE THREAD

**Issue by masoud-moghini** [Microsoft/vscode#6278]
- VSCode Version:the latest 
- OS Version:ubunto 16.04

assume that I want to harness 'fs' module features.naturally I have a code like:
`var fs=require('fs');`
then when I want to read a file or define a stream to a file for writing I expect when I type `fs` a variety of different options would be displayed.but it seems modules are unknown for VSCode and ,if  so,this is an extremely significant failure .
please guide me if there is a solution what's that.this case occurs for `child_process` and other modules too.

**Comment by v-pavanp** [comment]
@masoud-moghini : I hope you already installed node module and added reference in your project like below:
![image](https://cloud.githubusercontent.com/assets/17735796/15188558/38b1302c-175b-11e6-9f31-1e5a6ee3cdde.png)

**Comment by dbaeumer** [comment]
Besides using /// references you can define a JS project using a jsconfig.json file and add typings into the project. A doc describing how to do this is available here: https://code.visualstudio.com/docs/languages/javascript
