### ISSUE TITLE
Debugger is not stopping at breakpoints

### ISSUE THREAD

**Issue by arunagirinathan-rajan** [Microsoft/vscode#62780]
- VSCode Version: 1.28.2
- OS Version: OSX 10.14

**Steps to Reproduce:**

I am using custom framework to run spec files(Rspec).

After i marked my breakpoints inside the code, I will start my execution. But the debugger is not stopping at breakpoints. debugger just ignores/skip the breakpoints. Debugger works like runner. directly fly to end.

**Expected:** Debugger should stop at the break point and show all necessary debug information like call stack etc
**Actual:** Debugger is not stoping and there is no visual representation.

**Additional Information:** Find my debug configuration which i gave in **launch.json**.

> {
            "name": "Webframe",
            "type": "Ruby",
            "request": "launch",
            "cwd": "${workspaceRoot}",
            "program": "/Users/arunagirinathanr/.rvm/gems/ruby-2.5.1/bin/webframe",
            "env": {
                "PLAN":"Garden"
            },
            "args": [
                "${file}",
                "spec/abandoned_call_metrics1.rb"
            ]
        }

**Comment by weinand** [comment]
Please file against Ruby extension.
