### ISSUE TITLE
badges on custom activities added to activity bar by extensions

### ISSUE THREAD

**Issue by elf-pavlik** [microsoft/vscode#62783]
Previously mentioned by @eamodio in https://github.com/Microsoft/vscode/issues/43645#issuecomment-378261837 where @sandy081 asked to create separate issues for more specific features.

It would come helpful if extensions which create new activity in activity bar could also display a badge with a count. For example https://github.com/Gruntfuggly/todo-tree/issues/22 has request to show number of TODO/FIXME found in the project.

![badge](https://user-images.githubusercontent.com/22587994/40053697-997c15dc-5842-11e8-87b0-444531094fa1.png)

**Comment by jrieken** [comment]
@elf-pavlik The progress indication will show the a tree view operation is in progress. And since the tree views is the only thing we support here I was assuming that what we have is good enough. What the scenario here? You update something but don't yet update the tree?

**Comment by sandy081** [comment]
@Gruntfuggly Not sure search results is a good example also the existing Search viewlet does not show the count.

**Comment by SergioTx** [comment]
I think it's different from search.

Search is a tab you open to search and close right after that, the information there is no longer needed.

In the Todo case, it's a useful information all the time, same as version control information, even with the tab closed.

**Comment by Gruntfuggly** [comment]
The source control view show a badge with a count of the number of items in the view - I think that's all that users are really asking for - they want to know how many items are in the view without needing to open it.

**Comment by gim-m** [comment]
I would love to get badge support too. For my use case, I have a custom activity bar item that shows the status of remote jobs. I would really like to show an indication that something is running without the user having to expand the view.

It could be handy to have the option for a count badge or a plain "dot" badge in cases where we know something is running, but we might not know the exact count.

Thanks!

**Comment by cnshenj** [comment]
I have another case: a task view using VSCode task API. If the custom activity bar icon can show a number to indicate how many tasks are running (especially long running background tasks), then a user doesn't need to expand the view if they just want to make a sure a task is not running.

**Comment by Gruntfuggly** [comment]
As an alternative to badges in the activity bar, how about allowing badges in the title bar of a view when it is collapsed? That way an icon could be displayed to indicate that something has changed in the view.

**Comment by spmeesseman** [comment]
+1 for this

**Comment by andrewbarnesweb** [comment]
Just installed the todo add on, and it would be awesome to see a count in these things without having to open it.

**Comment by nbransby** [comment]
Could we also consider a badge color properly and support for displaying without a number? I would like to show online/away/offline status in https://teamhub.dev/ as we do in IntelliJ (bottom left on first screenshot)

**Comment by Nemesarial** [comment]
I too am developing a team-centric activity and would be very useful to have some means of indicating there are changes on that activity that a user would want to be notified about.

**Comment by Gruntfuggly** [comment]
There is a new API coming up allowing the title to be changed. Not quite badges, but it will at least allow something to be shown.

**Comment by luisjotapepe** [comment]
+1 for this

**Comment by ErisDS** [comment]
Is there any way to show how many todos there are for a codepath inside the tree?

I have lots of large codebases and monorepos, so it would be great if we could see which packages had the most TODOs.

**Comment by Gruntfuggly** [comment]
Do you mean subtotals for each tree node? If you enable `todo-tree.tree.showCountsInTree` it will show the number of children for each node.

**Comment by ErisDS** [comment]
Oh perfect - I've just been customising all the details - colours, icons and more and somehow totally missed that option.

Thanks 🙏

**Comment by ngarg-panw** [comment]
Going back to the badge problem, i have a scenario in which we scan the repos for issues. It will be good to show the count of issues found on the badge. Any update on this. Last post was Dec'19 so not sure where are things now.

**Comment by ycjcl868** [comment]
+1

**Comment by joelmagner** [comment]
Any updates on this proposed and sought after feature?

**Comment by vincentjocodes** [comment]
Any updates?

**Comment by chsxf** [comment]
Would be perfect for my custom extension. Is this planned at some point?

**Comment by alefragnani** [comment]
I guess not, unfortunately. 

It's been 2 years since the latest update from the team (adding `Backlog` label), with no additional info. 

I would love to have this as well, but decided to use a workaround. Instead of the badge in the Activity Bar, I used the added `Treeview.Title` property, concatenating the number of items I would like to show. It's not the same, but gives the message.

Hope this helps

**Comment by matthewjamesadam** [comment]
Hello @sandy081 @alexr00, I am interested in implementing this, it seems to be a popular request from a number of extension authors.  I've looked into how the activity count code works and am curious what kind of extension API you think might make sense for this:

* An optional event on `TreeDataProvider` and `WebviewViewProvider` that can be used to publish a badge for a tree/webview based views.
* Alternatively, a separate provider that can be registered to provide the badge for the activity ViewContainer as a whole.

And finally, is there any reason you think I shouldn't go ahead attempting to implement this?  Any reasons this wouldn't be a good addition?  Thanks!

**Comment by matthewjamesadam** [comment]
I've made two PRs with example APIs and would appreciate feedback:

1: An event on TreeDataProvider / WebviewViewProvider that allows providing activity information: https://github.com/microsoft/vscode/pull/139225
2: A new interface for providing activity information: https://github.com/microsoft/vscode/pull/139229/files

**Comment by matthewjamesadam** [comment]
I am leaning towards the second proposal (https://github.com/microsoft/vscode/pull/139229).  I have an implementation of this API in another PR here: https://github.com/microsoft/vscode/pull/139539/files.

**Comment by hamirmahal** [comment]
> What I meant the given example is not appealing. A badge being shown means it should be for a prominent reason like SCM outgoing changes. I see how it might be useful in case of Todo.

@sandy081 It would be helpful for our team if we could display a badge on our extension's Activity Bar icon when there is an update to our software available.

@alexr00 What things can we do to help make this functionality available for VSCode extension developers?

**Comment by isidorn** [comment]
@hamirmahal glad to hear you are interested in this API.
We have slowly started to work on this feature with the help of @matthewjamesadam 
For now no further help from the community is required. Thank you for offering though!

**Comment by hamirmahal** [comment]
@isidorn You're welcome! Thank you for the update.

**Comment by usernamehw** [comment]
It would be great to have progress state available; like SCM badge: https://code.visualstudio.com/api/ux-guidelines/views#views-with-progress

**Comment by alexr00** [comment]
@usernamehw we already support showing progress through the `showProgress` function:

https://github.com/microsoft/vscode/blob/d8d25af3ab734ac332f30a8fc5a8dd3d05c21d05/src/vscode-dts/vscode.d.ts#L9491-L9511

in `ProgressOptions`, you can specify a view id:
https://github.com/microsoft/vscode/blob/d8d25af3ab734ac332f30a8fc5a8dd3d05c21d05/src/vscode-dts/vscode.d.ts#L10592-L10600

Does that work for you? We try not to have 2 ways to do the same thing in API, so we wouldn't want to use the badges API to show progress.

**Comment by usernamehw** [comment]
@alexr00 yeah, that's great. I didn't know about that. Maybe the UX guideline should say that other views also support showing progress. Now it's just says:

> You can also [show progress in the Source Control view](https://code.visualstudio.com/api/references/vscode-api#ProgressLocation) if your view is inside of the SCM view container.

**Comment by alexr00** [comment]
Docs update in progress: https://github.com/microsoft/vscode-docs/pull/5316

**Comment by matthewjamesadam** [comment]
Thanks for your help on this @alexr00 !  It's great to see the badge feature available in builds for extension developers to try out.  I've been working against this and it seems to work pretty well.

Do you have an idea what the process and timeline look like for this to evolve from a proposed API to a stable API?  The official documentation here doesn't make this clear: https://code.visualstudio.com/api/advanced-topics/using-proposed-api. 

Should I be soliciting feedback at this point?  I found some (possibly outdated?) documentation here that seems to indicate I should, but it's not clear exactly what I should be doing: https://github.com/Microsoft/vscode/wiki/Extension-API-process#api-proposal-implemented--feedback-requested

Thanks again!

**Comment by alexr00** [comment]
We don't usually have a set timeline for finalizing API. The best way to help us decide to finalize it try the API out and post any feedback you have in this issue. When more extension authors try out the API and provide feedback we gain confidence that the API is well designed and satisfies a real need.
