### ISSUE TITLE
Go lang debugging "Unverified breakpoint" when project path contains symlink [Linux]

### ISSUE THREAD

**Issue by Karm** [Microsoft/vscode#62791]
- VSCode Version: 
```
Version: 1.28.2
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:20:56.183Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```
- OS Version:
```Fedora, 4.13.16-100 x86_64```
- Go extension Version:
```0.7.0```
- Installed Extensions:
```
13xforever.language-x86-64-assembly-2.2.11
flet.vscode-semistandard-1.1.2
ms-vscode.go-0.7.0
peterjausovec.vscode-docker-0.3.1
shakram02.bash-beautify-0.1.1
```
- Go version
```
go version go1.11.2 linux/amd64
```
- Delve version:
```
~/go/bin/dlv version
Delve Debugger
Version: 1.1.0
Build: 4927bc6c7a2045ba52f9f77633c867d39cafbbe5
```

# Steps to Reproduce:

1. Create a similar dir structure, i.e. one dir a an actual dir and the other one is a symlink:
```
karm@local:~/test$ pwd
/home/karm/test
karm@local:~/test$ ls -lahZ
total 28K
drwxrwxr-x.   4 karm karm unconfined_u:object_r:user_home_t:s0     4.0K Nov  8 16:18 .
drwx--x---+ 160 karm karm unconfined_u:object_r:user_home_dir_t:s0  12K Nov  8 16:17 ..
drwxrwxr-x.   2 karm karm unconfined_u:object_r:user_home_t:s0     4.0K Nov  8 16:17 project-1
drwxrwxr-x.   2 karm karm unconfined_u:object_r:user_home_t:s0     4.0K Nov  8 16:17 project-2
lrwxrwxrwx.   1 karm karm unconfined_u:object_r:user_home_t:s0       25 Nov  8 16:18 sym-project-2 -> /home/karm/test/project-2
```
2. Create main.go, identical both in ```project-1``` and in ```sym-project-2``` as:
```
 1 package main
 2 
 3 import (
 4 	"log"
 5 )
 6 
 7 func main() {
 8 	log.Println("Haha")
 9 }
10
```
3. Create identical launch config in both ```project-1/.vscode/launch.json ``` and in ```sym-project-2/.vscode/launch.json ``` as:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${fileDirname}",
            "env": {},
            "args": []
        }
    ]
}
```
3. Open VSCode and Open Folder -> project-1 -> set breakpoint line 8 -> F5 -> execution stops at line 8, *Good, expected*
4. Open Folder -> sym-project-2 -> set breakpoint line 8 -> F5 -> breakpoint goes grey as Unverified for a while and program completes, it did not stop at the breakpoint, *No good, not expected*

The only difference between the projects but for their name is the symlink in the path to the folder.
If any screenshots and/or further debugging comes handy, just drop me a line in a comment. I haven't delved into it yet, I don't know what is causing this behavior.

**Comment by Karm** [comment]
https://github.com/Microsoft/vscode-go/issues/2111

**Comment by cody588** [comment]
Do you know how can I resolve it?Which extension result in this problem?

**Comment by Karm** [comment]
@cody588 Follow [vscode-go/issues/2111](https://github.com/Microsoft/vscode-go/issues/2111).
