### ISSUE TITLE
Searching files list old results unrelated to current parameter

### ISSUE THREAD

**Issue by nyohasstium** [Microsoft/vscode#62793]
Issue Type: <b>Bug</b>

Searching new words accross the whole project keeps matching words used in previous searches

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.59GB free)|
|Process Argv|-psn_0_73746|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|9.1.0
vscode-eslint|dba|1.7.0
vscode-phpmd|eco|1.1.0
php-debug|fel|1.12.6
php-intellisense|fel|2.3.5
phpcs|ika|1.0.5
vscode-docker|Pet|0.3.1
gitblame|wad|2.6.0
JavaScriptSnippets|xab|1.7.1

</details>

**Comment by chrmarti** [comment]
Could you attach a screenshot?

**Comment by roblourens** [comment]
It's not clear exactly what the problem is, a screenshot would help.
