### ISSUE TITLE
Broken internet connection detection

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#62792]
- VSCode Version: v1.28.2
- OS Version: 10.13.5

Steps to Reproduce:

1. Load VSC

I'm using a VPN, I've never seen this before when I wasn't using a VPN.

![internet_connection](https://user-images.githubusercontent.com/1812093/48209851-6c743000-e376-11e8-9604-a6d335c06db7.gif)

**Comment by chrmarti** [comment]
Does this reproduce with all extensions disabled? (`code --disable-extensions`)

**Comment by fabiospampinato** [comment]
Probably, I can't reproduce it anymore. 

I haven't changed my extensions in a while, what changed was: crappy WiFi and a VPN. You can't see this in the gif but I actually tried multiple times and VSCode would always detect that I had no internet connection, even though I was actually able to browse the internet.

Also the detection seemed too fast, maybe the `isOffline` value or whatever was cached for some reason? I don't know.

**Comment by joaomoreno** [comment]
Let me know if you can repro.
