### ISSUE TITLE
VS Code for PowerShell v2

### ISSUE THREAD

**Issue by urbanator84** [Microsoft/vscode#6279]
- VSCode Version: 1.1
- OS Version: Windows Server 2008 R2

Hi,

Is there a support for PowerShell v2 in VSC? What is my concern to use it to develop scripts for SharePoint 2010. 
If not - will it be implemented at some point?

Thanks for answer.

**Comment by isidorn** [comment]
@daviwil can you please answer :)

**Comment by daviwil** [comment]
Hi @urbanator84, we currently don't have plans to support PowerShell v2 in the PowerShell extension for VS Code.  If we receive enough requests for this we may consider it.  I'd recommend filing a request for it over at our GitHub page:

https://github.com/PowerShell/vscode-powershell
