### ISSUE TITLE
Custom domain URLs in JSON include trailing quote

### ISSUE THREAD

**Issue by pvh** [Microsoft/vscode#62800]
- VSCode Version: VSCode Electron 3 exploration
- OS Version: Windows 10

Steps to Reproduce:
1. Register a filesystem with a new protocol
2. Include a link to that filesystem in a JSON document (in my case this document shows the defect):
```
{ 
  "good-url": "http://doc2.json",
  "bad-url": "hypermergefs:/doc2.json",
  "unhighlighted-url": "unregistered:/foo.json"
}
```
3. Note that the "bad-url" highlight includes the trailing quote and the unregistered scheme does not highlight.

I suspect this is a Very Small Bug with a regex somewhere but I haven't been able to find it. If anyone can point me in the right direction I'm happy to fix it.

**Comment by alexr00** [comment]
@pvh, can you outline what you mean by "Register a filesystem with a new protocol"? What you have looks like a registered URI protocol but I can't repro with that.

**Comment by pvh** [comment]
Ah - yes, I found a reproduction with a publicly available filesystem provider. Try installing the SSH FS extension and then look at the above JSON with the extension loaded. You'll see that the SSH extension URL highlight includes both the trailing " and comma. Does that help?

**Comment by alexr00** [comment]
I still can't reproduce this on the insiders build or on stable. Does it reproduce on those for you? Can you add a screen shot of what you're seeing with SSH FS please?

**Comment by pvh** [comment]
Sorry, I should have been more clear that to see the bug with the SSH FS you need an ssh URL. On both the insiders and exploration build I have I see this:

![image](https://user-images.githubusercontent.com/2880/48362258-18a86600-e658-11e8-9f3b-4626f1bc0662.png)

For reference, the Insiders build I'm using is the following:

Version: 1.29.0-insider (user setup)
Commit: 1d0e4299c6ccfe9210252c811b4247cfdc8a6a44
Date: 2018-11-06T10:07:08.614Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by alexr00** [comment]
I can see it repro now. The step I used:

Install SSH FS
Add an arbirary sshfs.configs to settings. I just copied it out of the extension info.
Run the SSH FS: Connect as workspace folder command with your new dummy config
Type up this example:

    {
	    "good-url": "http://doc2.json",
	    "bad-url": "ssh://microsoft.com/doc2.json",
	    "unhighlighted-url": "unregistered://foo.json"
    }


See that the underline for `"bad-url"` extends through the comma.

@jrieken, do you usually look at URI document link provider issues?

**Comment by jrieken** [comment]
Yeah, we have simple (read stupid) link detector when a file system is being registered: https://github.com/Microsoft/vscode/blob/95190ed713a1c0312686a04db5ce8a25db866c27/src/vs/workbench/api/node/extHostFileSystem.ts#L37-L39

**Comment by pvh** [comment]
Aha! Yeah, I suspect you could just throw some quotes into the [^\s] group at the end there but to do it right I guess you'd probably want to handle quote escaping and things like that. I took a quick look at other implementations of provideDocumentLinks elsewhere in the main repo and none of them popped out as having an obviously equivalent regex. Let me know if this is something you could use an external contribution for but I suspect it's probably a quick fix for someone who knows the code well.

**Comment by jrieken** [comment]
> I suspect you could just throw some quotes into the [^\s] group at the end there but to do it right I guess you'd probably

sounds like a winner ;-)

**Comment by jrieken** [comment]
Nah, I did go for the proper fix... It now uses the state machine logic we have for http and file links

**Comment by pvh** [comment]
You, sir, are a gentleman and a scholar. Thanks!
