### ISSUE TITLE
Ctrl + Shift + G not working suddenly

### ISSUE THREAD

**Issue by rhshi** [Microsoft/vscode#62807]
While I was working, all of a sudden, ctrl+shift+G stopped working - when I try to set the key binding in key preferences, i am able to input ctrl and shift, but not G.   Ctrl+shift+E, ctrl+shift+X, etc still work fine.

I have no other SCM extensions

**Comment by chrmarti** [comment]
/needsMoreInfo

Which OS and which version of VS Code are you using and what extensions do you have installed?

Have you tried searching for the keybinding with `"ctrl+shift+g"`?

![image](https://user-images.githubusercontent.com/9205389/48250730-902f8880-e3ff-11e8-8a40-bc702bedfbb4.png)

**Comment by rhshi** [comment]
I am using VSCode 1.28 on Windows. 

List of extensions:
justusadam.language-haskell
ms-python.python
ms-vscode.cpptools
PKief.material-icon-theme
pnp.polacode
rafaelmaiolla.remote-vscode
spywhere.guides
streetsidesoftware.code-spell-checker
Tyriar.shell-launcher
yummygum.city-lights-theme

**Comment by brunholm** [comment]
My whole work has the same issue - some runs totally clean install on a windows 10, some with extensions, like GitLens installed (but with no overrides in keyboard shortcuts).

To note here is the totally clean installs of vscode with no extensions installed. We believe it's a core bug or a windows bug maybe.

**Comment by syaffers** [comment]
I just want to add that I'm facing a similar issue on my computer. Except, for me the keybindings ctrl + shift + alt + (any arrow key) suddenly stopped working and, like @rhshi, I cannot assign the keybinding. I can press ctrl + shift + alt but when pressing the arrow keys, nothing happens. However, doing ctrl + shift + alt + c, for example, works. See https://imgur.com/a/dzIzibx

I'm on Ubuntu 18.04, freshly installed 3-4 days ago, running VSCode 1.29.0 installed via snap. I only have the Python extension (`ms-python.python`) installed.

**Comment by brunholm** [comment]
I just tested and I can rebind the SCM shortcut to something else like ctrl + shift + å, which works perfectly. Perhaps something else is overriding the ctrl + shift + g shortcut somewhere, even on a clean install.
Btw, we use bitbucket with ssh key if it makes any difference.

**Comment by syaffers** [comment]
@alexandrudima According to the photo I posted above (https://imgur.com/a/dzIzibx), you can clearly see that screenkey captured the keypresses but not VSCode. I've even tried changing the settings on GNOME to switch workspaces with the ctrl + shift + alt + down key and it works fine. Must be a VSCode issue on my side.

**Comment by alexandrudima** [comment]
@syaffers It is a bit impolite to take over another person's thread given you might be even on a different OS than the OP (since the OP doesn't even mention). Simply because a keybinding does not work for both of you, it does not mean you have the same issue.

Anyways, @syaffers  have you tried running VS Code from the zip (outside of snap?). Did this keybinding work for you in the past in VS Code? Does this keybinding work for you in other software on that machine?

**Comment by brunholm** [comment]
I found out that it can't be vscode that has the issue. I can't bind ctrl + shift + g in the new keyboard shortcut setting, although I can bind the combination in other apps - they don't react, so something else is hijacking it, be it windows self or some other app we all per chance has installed.

**Comment by brunholm** [comment]
Found the bug - it's Google Drive file stream that hijacks the key combination! Exit the app and vscode etc will work as expected.

**Comment by alexandrudima** [comment]
@rhsi Do you have the same problem with Google Drive ?

**Comment by syaffers** [comment]
@brunholm @alexandrudima Apologies for this, I saw the thread when I was facing the problem and I thought I would echo a my problem rather than create a new one since the situation was very similar. Apologies once again :bowing_man: 

@alexandrudima The keybinding did work for me in the past. I purged the snap and reinstalled using the .deb and it works now.

Apologies once again (again), I should've created a new issue.

**Comment by alexandrudima** [comment]
Thanks @syaffers , I'm happy you managed to resolve the issue.

@rhsi Are you still having issues with Ctrl+Shift+G ?

**Comment by rhshi** [comment]
Yep, this is my problem as well.  When I quit Google File Stream I am able to use Ctrl+Shift+G, but not when it's open.

**Comment by alexandrudima** [comment]
Thank you for confirming.
