### ISSUE TITLE
Debug output panel does output messages.

### ISSUE THREAD

**Issue by thpeder** [Microsoft/vscode#62808]
- VSCode Version: 1.29.0-insider (user setup)
- OS Version: Windows 10 version 1809 (OS build 17763.55)
Commit: bdfe4fd41f6a5fe538197b3cba937230249a563a
Date: 2018-11-04T13:04:20.759Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Steps to Reproduce:

1. Clone, build and run the Mock debug adapter (https://github.com/Microsoft/vscode-mock-debug) 
2. On a new line in the README file enter `log(MyCustomMessage)`
3. Start the debugger(as written in the README file) in the README.md file and step over the Log line. In the debug ourput panel the text `MyCustomMessage` should appear but it doesn't.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
@thpeder this works nicely for me. Please let me know what you are doing differerently than me
fyi @weinand 

![mock](https://user-images.githubusercontent.com/1926584/48255516-32a23880-e40d-11e8-8a5e-4ee71f21fffb.gif)

**Comment by thpeder** [comment]
Thanks for investigating it. I updated to Commit: 9a2d095fd017e9ea129ca6e136e869e49290a4ba and it works for me too.
