### ISSUE TITLE
Cannot read property 'stopTime' of undefined

### ISSUE THREAD

**Issue by wembernard** [Microsoft/vscode#6280]
- VSCode Version: 1.1.0
- OS Version: Mac OS 10.11.4

Steps to Reproduce:

1. `cmd` + `shift` + `P`
2. `> Developer: Startup Performance`
3. `Enter`

=> `[error] Cannot read property 'stopTime' of undefined`

Restarting vscode fixed the problem. I know have a proper message:

`[info] Command 'Developer: Startup Performance' is not enabled in the current context.`

Not sure if it's a one-time bug auto-fixed but that might worth to take a look into it.

**Comment by bpasero** [comment]
When you can provide steps to reproduce, we can reopen.
