### ISSUE TITLE
Add setting for where terminal opens (in workspace)

### ISSUE THREAD

**Issue by martellaj** [Microsoft/vscode#62804]
It's not clear to me what determines what folder gets opened in the integrated terminal when I toggle the terminal (when there are none currently open). Ideally, I'd like a setting similar to `terminal.integrated.splitCwd` that gives me the same options such that I can choose each time.

**Comment by Tyriar** [comment]
Here's what happens:

- Multi-root: Whatever was the last active root (based on files opened), falling back to the first (I think)
- One folder: The folder
- No folders: "home" fallback folder

It seems the only complication is when multi-root happens, but the difference here is that the terminal panel must launch asap without user intervention (we cannot have a picker here) I'm not sure what the options would be and if it's worth adding a new setting for. @martellaj what options were you thinking here?

**Comment by martellaj** [comment]
>  the difference here is that the terminal panel must launch asap without user intervention (we cannot have a picker here)

This makes sense and probably makes it not worth it. I like the control I get when I click the "new terminal" button (when the terminal is already opened) that allows me to choose which folder gets opened up.

When there's no terminal open (in the multi-root case), it's not always the case that the one I want to open is the last one I was working in. Selfishly, this issue doesn't affect me anymore (monorepo woo), so if there's a sample count of 1 asking for the feature it's probably not too important to build. 😊

**Comment by Tyriar** [comment]
> When there's no terminal open (in the multi-root case), it's not always the case that the one I want to open is the last one I was working in.

In that case I would recommend using ctrl+shift+` as you will get the picker then, just not with the general toggle panel commands.
