### ISSUE TITLE
Changes from TextDocumentContentProvider#onDidChange not applied correctly

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#62802]
This is the root cause of https://github.com/OmniSharp/omnisharp-vscode/issues/2641 and probably other issues. 

With https://github.com/Microsoft/vscode/commit/bab31465aeefbe9f4c31f5895b772975478ee2f8 (which happened 4 months ago) we have changes the logic how events from `TextDocumentContentProviders` are applied to editor models. Instead of using `setValue` (which flushed all decorations and flickers the editor) it uses the `computeMoreMinimalEdits` (which we also use for formatting) and `ITextModel#applyModel`. The problem is that subsequent changes aren't waiting for the previous change to be applied nor do they cancel them. This makes us compute the edits against an old, invalid version of the document. 

Applying those edits then messes up the document, sometimes crashing the editor all together. 

There is two fixes: (1) do back to `setValue` (undo https://github.com/Microsoft/vscode/commit/bab31465aeefbe9f4c31f5895b772975478ee2f8) or (2) cancel/ignore a change when another change happens.

**Comment by isidorn** [comment]
This is fixed for the release, clsoing so we get it verified
@jrieken if you would like to re-verify this on master with your different fix please create a new issue. Thanks

Also some verification steps would be great.
