### ISSUE TITLE
New 'when' clause context: activityBarVisible

### ISSUE THREAD

**Issue by LucaMoschella** [Microsoft/vscode#62818]
If I'm not mistaken, in the possible "when" [clause contexts](https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts) it is missing the context: `activityBarVisible`
It's toggle is: `workbench.action.toggleActivityBarVisibility`

It would be useful to implement a shortcut that toggles both the sidebar and activity bar visibility togheter.

**Comment by usernamehw** [comment]
You can use Settings keys in `when`:
```json
"when": "config.workbench.activityBar.visible"
```
Maybe it would be possible to toggle them if there was a way to execute multiple commands: #871. 
Or using an extension: [macros](https://marketplace.visualstudio.com/items?itemName=geddski.macros).

**Comment by LucaMoschella** [comment]
Oh I didn't knew about this! Thank you

Yes, I'm using macros

**Comment by usernamehw** [comment]
> I had to do several bindings because == or || didn't seem to work

Yep, there's no `||` operator yet #22778
