### ISSUE TITLE
Feature Request: Better Git Diff Tools

### ISSUE THREAD

**Issue by ReeseJones** [Microsoft/vscode#62813]
Issue Type: <b>Feature Request</b>

I still open Visual Studio to manage merge conflicts. Would be nice to have obvious out of the box support to get something like with what I am used to in visual studio. 

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

**Comment by beastdestroyer** [comment]
Would the GitLens extension help? https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens

It might not have what you're looking for but  I find it very helpful for Git. Perhaps there may be other extensions too

**Comment by ReeseJones** [comment]
> Would the GitLens extension help? https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens
> 
> It might not have what you're looking for but I find it very helpful for Git. Perhaps there may be other extensions too

I have gitlens installed, and use it occasionally. Its more or less has just taught me to use the command line for branch management, which I am okay with learning and using. However it does not solve for my ideal experience when merging.

I opened this mostly just to provide user feedback (it seems to be the main channel for this), as I like code and think its a good tool and I wanted to share what it would take to get me to leave visual studio behind entirely. Code does a pretty good job of recommending extensions, but I haven't found one that replicates the gui merge experience in visual studio where I can see the two branches side by side, whats been added and removed from both, and below, a window displaying the final changes where I can make adjustments when I cant just take from the source or target, but need to manually combine the two.

I have no proposed solutions for this, just expressing my ideal experience. It could be that someone has made an extension already that replicates this experience, but as a user it does me no good if I do not know it exists.

If I was recommended extensions that replicate the experiences I was familiar with that would get me to my ideal experience.

If it was built into vs code, that would too.
