### ISSUE TITLE
Debian repository Packages / Packages.gz / Packages.bz2 contain extra whitespace

### ISSUE THREAD

**Issue by furlongm** [microsoft/vscode#62811]
The Debian repository Packages{,.gz,.bz2} seem to have an extra line of whitespace that causes parsing issues with python-debian.

This only occurs for 12 of the entries, the other 453 are fine.

To see the 12 with an extra line with whitespace only in the stanza, run:

```
# curl -s http://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages | grep -n -H "^ $"
(standard input):3485:
(standard input):3780:
(standard input):3802:
(standard input):3824:
(standard input):3846:
(standard input):3868:
(standard input):3890:
(standard input):3912:
(standard input):3934:
(standard input):3956:
(standard input):3978:
(standard input):4000:
```

Would it be possible to remove these lines from the Packages files?

**Comment by chrmarti** [comment]
That whitespace is part of the descriptions which is allowed to have whitespace. I don't know what the spec for Packages says, but since other tools appear to tolerate it, should `python-debian` be updated to do the same?

**Comment by furlongm** [comment]
Opened a bug report against python-debian:

   https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=913274

According to the bug report, the spec doesn't seem to allow whitespace, but most tools are tolerant of it, including python-debian generally. Awaiting reply on the bug report.
