### ISSUE TITLE
Pug Highlighting Doesn't Recognize Inline Blocks

### ISSUE THREAD

**Issue by emersonp** [Microsoft/vscode#62817]
- VSCode Version: 1.28.2
- OS Version: Win 10 x64

Steps to Reproduce:

1. Use a pug inline block

``` p: strong```

2. strong is not highlighted as code.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
@emersonp, can you give me an example of an editor or IDE that does this correctly please? I want to make sure I'm reproducing this the right way.

**Comment by lxmfly123** [comment]
@alexr00 WebStorm does this correctly.

**Comment by joexmdq** [comment]
@alexr00  Here is an example of VSCode (1.29.1) vs Sublime Text (3.1.1) and Atom (1.33.0):
![example1](https://user-images.githubusercontent.com/45812155/49972379-37787180-ff10-11e8-8fc6-330d51ddd5f7.png)

**Comment by alexr00** [comment]
@joexmdq, thanks for the example! Looks like this is a problem with the grammar we're using for pug.

**Comment by alexr00** [comment]
This issue was moved to davidrios/pug-tmbundle#26
