### ISSUE TITLE
Parameter suggestion sometimes underlines return type's property with same name

### ISSUE THREAD

**Issue by cxcorp** [Microsoft/vscode#62814]
When using a function which accepts a parameter and returns an object with a property that has the same name as a parameter, the suggestion incorrectly highlights the property instead of the parameter. This bug appears at least when using the JavaScript language mode.

The correct behavior looks like the following:
> ![VS Code correctly underlining the parameter](https://user-images.githubusercontent.com/21111572/48230447-b3cce180-e3b3-11e8-9d62-59c57322e8ad.png)

I tested a few scenarios and the suggestion breaks when the parameter's name and a property in the returned object has the same name, and:
- both the parameter type and property type are guessed by VS Code
    > ![VS Code incorrectly underlining the return type's property](https://user-images.githubusercontent.com/21111572/48228490-fc819c00-e3ad-11e8-8491-1ab18fed4005.png)
- the parameter's type is defined via JSDoc and the return type is guessed
  > ![image](https://user-images.githubusercontent.com/21111572/48228707-a52ffb80-e3ae-11e8-8162-738b2bfbb503.png)
- the parameter's type is guessed and the returned object's property type is either `any`, `object`, `array`, or some specific type union such as `object | null`
    > ![image](https://user-images.githubusercontent.com/21111572/48229454-cabe0480-e3b0-11e8-81d9-1fd6a32d42d1.png)
  - however, this one works correctly when the type is `string`, `number`, `boolean`, `undefined` (possibly others as well)
  - interestingly some type unions such as `string | array` work
- both the parameter type and property type are `any`, `object`, `array`, or some specific type union such as `object | null`
  > ![image](https://user-images.githubusercontent.com/21111572/48229863-f42b6000-e3b1-11e8-874a-7d68bf33acb0.png)

All of these scenarios seem to share the fact that the type gets evaluated to `any`.

The bug also appears in these scenarios when the property's name _ends with_ the parameter's name:
> ![image](https://user-images.githubusercontent.com/21111572/48230215-f17d3a80-e3b2-11e8-85a2-612065b218d7.png)

...but not when the property's name contains a _substring_:
> ![image](https://user-images.githubusercontent.com/21111572/48230397-8122e900-e3b3-11e8-94f6-a33f1337460a.png)

- VSCode Version: 1.28.2, also 1.29.0-insider
- OS Version: Windows 10 Pro (version 1803, build 17134.285)

Steps to Reproduce:

1. Write a function which accepts a parameter and returns an object with a key that has the same name as the parameter
2. Trigger the parameter suggestion by writing the function's name and the opening bracket

Does this issue occur when all extensions are disabled?: Yes

Possibly similar, but not duplicate issues:
#18782, #40080

**Comment by cxcorp** [comment]
Here's a gif of the bug appearing when using a function with more arguments. I think it shows well why the bug causes a bit of confusion.

![video](https://user-images.githubusercontent.com/21111572/48231902-83d40d00-e3b8-11e8-8d3a-4d8fca3d5d48.gif)

**Comment by mjbvz** [comment]
I believe this was fixed by 3e7bb120c786038030de0d284b62a837d204330a

Text source for verification:

```js
function sayHello(name) {
    return { name }
}

sayHello
```
