### ISSUE TITLE
Ruby heredoc in method arguments break braces syntax

### ISSUE THREAD

**Issue by amerov** [Microsoft/vscode#62812]
- VSCode Version: 1.28.2
![screenshot from 2018-11-09 02-15-58](https://user-images.githubusercontent.com/196747/48227871-6bb6ba80-e3c5-11e8-9dd2-ed719ec6c742.png)

**Comment by alexr00** [comment]
After the heredoc starts, shouldn't it all be heredoc until the ending LOG? In this case the closing parenthesis is highlighted correctly.  @rebornix am I understanding this correctly?

**Comment by amerov** [comment]
@alexr00 It is valid ruby code.
Examples:
https://github.com/rails/rails/blob/master/activemodel/lib/active_model/attributes.rb#L35
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/persistence.rb#L659
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/nested_attributes.rb#L370

**Comment by rebornix** [comment]
@alexr00 the heredoc content starts from the line following the heredoc identifier (`LOG` in our case) and we can use the heredoc identifier as a variable in that line, so `log(<<-LOG)` is a valid function call and `<<-LOG` is referring to the content after this line (and also ends with `LOG`). https://docs.ruby-lang.org/en/2.5.0/syntax/literals_rdoc.html

For short, `)` is not part of the multiline string, our grammar is kind of wrong.

**Comment by alexr00** [comment]
Thanks for checking!

**Comment by alexr00** [comment]
This issue was moved to textmate/ruby.tmbundle#124
