### ISSUE TITLE
Freezing most of the time

### ISSUE THREAD

**Issue by C4pt4inM** [Microsoft/vscode#62827]
Issue Type: <b>Performance Issue</b>

It freezes when I keep press a key for more than 1 seconds. It doesnot matter what kind of file it is, whether a project is opened or a single file. every time it does it. some times freezes for long time which triggers prompt to close or wait. Memory is ok, 200+. whenever freezes I checked cpu usage, disk usage, memory , all were fine.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:12.403Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.80GB (0.57GB free)|
|Process Argv|C:\Users\Lenovo\AppData\Local\Temp\fz3temp-2\functions.php|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    50	  5436	code main
    0	   110	  7068	   window (● template-timesheet.php - Visual Studio Code)
    0	    36	 13548	     extensionHost
    0	    15	  7772	       "C:\Program Files (x86)\Microsoft VS Code\Code.exe" "c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain" --node-ipc --clientProcessId=13548
    0	     5	 10328	       "C:\Program Files (x86)\Microsoft VS Code\Code.exe" "c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain" --node-ipc --clientProcessId=13548
    0	    35	 15200	       electron_node tsserver.js 
    0	     7	  5280	         electron_node typingsInstaller.js typesMap.js 
    0	    10	 14416	     electron-crash-reporter
    0	    24	  9472	   shared-process
    1	    57	  9828	   window (Issue Reporter)
    1	    51	 14560	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
Bookmarks|ale|9.2.0
copy-relative-path|ale|0.0.2
htmltagwrap|bra|0.0.7
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.60
xml|Dot|2.3.2
php-debug|fel|1.12.6
vscode-JS-CSS-HTML-formatter|lon|0.2.3
node-debug2|ms-|1.29.5
vetur|oct|0.13.0
laravel-blade|one|1.18.0
vscode-icons|rob|7.28.0
vue-vscode-snippets|sdr|1.3.0
vscode-sql-beautify|sen|0.0.4
vscode-status-bar-format-toggle|tom|1.4.0
highlight-matching-tag|vin|0.8.1
vscode-react-native|vsm|0.6.18
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.7.1
ReactSnippets|xab|2.2.1

(5 theme extensions excluded)

</details>

**Comment by C4pt4inM** [comment]
This is not similar to common freezing problem, this is specifically with input that is a long keypress (even arrow keys)

**Comment by jrieken** [comment]
@C4pt4inM Please try to CPU profile this. Hit F1 > Toggle Developer Tools. In the overflow menu select 'More Tools > JavaScript Profiler'. In there select start, let it profile for 30 to 60 seconds, stop it, save it to a file and attach the file here. Thanks.

<img width="380" alt="screen shot 2017-09-28 at 09 44 31" src="https://user-images.githubusercontent.com/1794099/30954796-d1be9e30-a431-11e7-959e-495d234c37c6.png">
