### ISSUE TITLE
Logo for R language overflows the normal area

### ISSUE THREAD

**Issue by James-Leib** [Microsoft/vscode#62822]
Issue Type: <b>Bug</b>

Logo for R language overflows the normal area.

Don't think I did anything to screw with vs, got some basic prefs and i have .NET and omnisharp.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|8.00GB (0.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.17.0

(2 theme extensions excluded)

</details>

**Comment by alexr00** [comment]
Can you add a screen shot?

**Comment by alexr00** [comment]
Can you add a screen shot?

**Comment by alexr00** [comment]
@James-Leib, this has been already. Try updating to version 1.29.* or Insiders.
