### ISSUE TITLE
Cannot read property 'isFullScreen' of null

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#62833]
Issue Type: <b>Bug</b>

ERR Cannot read property 'isFullScreen' of null: TypeError: Cannot read property 'isFullScreen' of null
    at C.isFullScreen (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:444:954)
    at Screen.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:438:18)
    at emitThree (events.js:141:20)
    at Screen.emit (events.js:217:7)

VS Code version: Code - Insiders 1.29.0-insider (5438af145cf480ce0162bda0799435684b293ec5, 2018-11-07T00:54:27.213Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.89GB free)|
|Process Argv|-psn_0_5215481|
|Screen Reader|no|
|VM|33%|

</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
unique-lines|bib|1.0.0
ssh|chr|0.0.4
vscode-eslint|dba|1.7.0
Spot|der|0.4.0
ghlink|dt|1.0.2
remotehub|eam|0.2.0
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.40
git-project-manager|fel|1.7.1
vscode-pull-request-github|Git|0.2.3
rest-client|hum|0.20.3
solidity|Jua|0.0.46
theme-karyfoundation-themes|kar|18.2.1
graphql-for-vscode|kum|1.12.1
vscode-azureappservice|ms-|0.9.1
vscode-azurefunctions|ms-|0.12.0
vscode-cosmosdb|ms-|0.8.0
azure-account|ms-|0.6.0
azurecli|ms-|0.4.2
github-issues-prs|ms-|0.9.1
vsliveshare|ms-|0.3.925
debugger-for-chrome|msj|4.11.0
vscode-docker|Pet|0.3.1
vscode-versionlens|pfl|0.22.0
vscode-workspacecontains-canary|rob|0.0.2
vscode-open-in-github|sys|1.8.0
ayu|tea|0.16.0
azure-iot-toolkit|vsc|1.6.0

</details>

**Comment by isidorn** [comment]
I could add a null check and simply go over this. However forwarding to @bpasero since this might uncover some flaw in his logic

**Comment by bpasero** [comment]
This was a global listener not being cleaned up when the window closes 👍
