### ISSUE TITLE
Allow "ctrl+<char>" keybindings to be executed from integrated terminal focus.

### ISSUE THREAD

**Issue by dsanz006** [Microsoft/vscode#62831]
I have the keybinding "ctrl+h p" assigned to "workbench.action.togglePanel", and this works fine except when my focus is on the terminal. In this case, it seems to be the terminal who grabs the keys I am pressing, and I would like VS Code to grab them. ¿Is there any setting to allow this? If not, it would be nice to have that option.

By the way, I didn't modify the default contents of "terminal.Integrated.commandsToSkipShell", so "workbench.action.togglePanel" is on it, as it is by default.

**Comment by Tyriar** [comment]
The problem is that chord keybindings don't work when the terminal is focused, this is by design currently.
