### ISSUE TITLE
editor.hover.delay setting is only "activated" when user settings is altered. 

### ISSUE THREAD

**Issue by pietervandereems** [Microsoft/vscode#62835]
Issue Type: <b>Bug</b>

File -> Preferences -> Settings
Search for "hover"
Alter Editor> Hover:Delay to 2001
---
The hover popup delay is now 2001 millis.
Close Visual Studio Code
Start Visual Studio Code
The hover popup delay is now 300 millis.
File -> Preferences -> Settings
 "..." -> settings.json
See that in the settings.json (right side, under USER SETTINGS) the delay is set to 2001: "editor.hover.delay": 2001
Change the 2001 to for example 2000 (so that the settings.json is saved)>
The hover popup delay is now 2000 millis.

Repeat.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:20:56.183Z)
OS version: Linux x64 4.18.0-10-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 3898)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.52GB (4.09GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sequence-diagrams|Ale|0.3.1
vscode-eslint|dba|1.7.0
EditorConfig|Edi|0.12.5
vscode-firefox-debug|hbe|1.7.1
vscode-icons|rob|7.28.0
vscode-scss-formatter|sib|1.0.4

(1 theme extensions excluded)

</details>

**Comment by usernamehw** [comment]
/confirm Win10 1.28.2/1.29.0

It's starting to work again after tab switching.
