### ISSUE TITLE
[ts] Missing syntax highlighting for async arrow functions

### ISSUE THREAD

**Issue by crystalgreen** [Microsoft/vscode#6283]
- VSCode Version: 1.1.0
- OS Version:Win10

Steps to Reproduce:

1. Create .ts file
2. paste `let f = async (x) => {};`

The result should be a blue `async` and a cyan colored `x`. 
When writing `let f2 = async function(x) {};` the async is colored blue.

![async-highlighting](https://cloud.githubusercontent.com/assets/16759855/15180324/217905b2-1781-11e6-9ce0-1121372e2930.png)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#172
