### ISSUE TITLE
unify scrollbar onclick behavior with (most) native apps and change Minimap on click behavior

### ISSUE THREAD

**Issue by yumeyao** [microsoft/vscode#62834]
Expected behavior:
On Windows/most Linux DEs, when you click on the scrollbar:
- If you click on the current section, you can drag it to scroll up/down
- **If you click outside the current section, it scrolls up/down(towards clicked point) _by one page_** (If you hold your mouse, it will scroll in that direction continously)

VSCode scrollbar behavior:
- If you click on the current section, you can drag it to scroll up/down
- **If you click outside the current section, it navigates to that position directly.**

VSCode Minimap behavior
- If you click on the current section, you can drag it to scroll up/down
- **If you click outside the current section, it navigates to the mid point of current position and clicked position directly.**

personally, I want VSCode scrollbar acts like a native apps so that it scrolls by one page, and I want the minimap acts like what scrollbar acts rightnow - navigate to clicked position directly. Of course we can just add configs for such behavior so users can choose what they want.

**Comment by gjsjohnmurray** [comment]
See also #43564
