### ISSUE TITLE
Provide possibility to configure the top displayed label in outline view for Language Servers

### ISSUE THREAD

**Issue by apupier** [Microsoft/vscode#62839]
When there are several language servers contributing an outline for a file. They are both displayed. They are grouped in separate trees. The top level display name seems to use the extension name used.

It would be nice to allow customizing this naming.

for instance, when installing "XML" and "Language Support for Apache Camel", the "Language Support of Apache Camel" naming is used and it is truncated:
![image](https://user-images.githubusercontent.com/1105127/48255144-181b8f80-e40c-11e8-9970-67eec22e4528.png)

for information i tried to ask if it is already possible but got no answer so I guess it is not https://stackoverflow.com/questions/52816836/specify-oultine-title-when-several-language-servers-are-present

**Comment by YisraelV** [comment]
I would like to work on this please.

**Comment by YisraelV** [comment]
@apupier can you give another example of a language that has two outline providers?

**Comment by apupier** [comment]
@YisraelV sorry, I don't know any others

**Comment by jrieken** [comment]
@YisraelV get this extension https://marketplace.visualstudio.com/items?itemName=roblourens.unittest-navigate and open TypeScript test files. That will show this.

**Comment by jrieken** [comment]
Most of the required code is already there but the default label is the extension name. That happens here: 

https://github.com/Microsoft/vscode/blob/e839e4560c19ce53c717d6f3078fd01e35c737a2/src/vs/workbench/api/node/extHostLanguageFeatures.ts#L964

We need some new API that allows to provide a name when calling `registerDocumentSymbolProvider`. We usually do that as extra argument to that call, e.g

`export function registerDocumentSymbolProvider(selector: DocumentSelector, provider: DocumentSymbolProvider, metadata?: XXXX): Disposable;` similar to [`registerCodeActionProvider`](https://github.com/Microsoft/vscode/blob/e839e4560c19ce53c717d6f3078fd01e35c737a2/src/vs/vscode.d.ts#L7619)

**Comment by YisraelV** [comment]
@jrieken thank you very much for the guidance! You've saved me a few hours.

I thought the OP had in mind a way for the user to set the name displayed with no change in the extension code. But what you say - making this part of the api for extensions - makes more sense and is much easier to implement.

**Comment by jrieken** [comment]
👏 @YisraelV

**Comment by YisraelV** [comment]
@jrieken thank you very much for the tips and for taking the time to review and merge it.

**Comment by apupier** [comment]
Can you explain how to use this new configuration?

With my Language Server Extension I'm not calling explicitly the registerDocumentOutline https://github.com/Microsoft/vscode/pull/63150/files#diff-6ed04bc0a0e32b52bb98d493792f857eR976 How should specify the specific name?

**Comment by jrieken** [comment]
this needs LSP support first, cc @dbaeumer

**Comment by dbaeumer** [comment]
Created https://github.com/Microsoft/language-server-protocol/issues/617. A PR to add this to LSP and the node libraries is highly appreciated.

**Comment by YisraelV** [comment]
@jrieken @dbaeumer  I would like to help but could you please explain to me:

1. what has it got to do with the language server protocol? the display name is something the extension (the language client) is supposed to decide and it's not part of the protocol.

2.  just to be sure the node clients you are talking about are actually wrappers around the api found in vscode.d.ts (the vscode namespace) right?

**Comment by jrieken** [comment]
verify by opening the outline and/or breadcrumbs for launch.json, one provider should be called 'Launch Targets'

**Comment by YisraelV** [comment]
@jrieken because this issue is closed I assume the work was finished by someone else? I did not quite understand what happened.
