### ISSUE TITLE
golang environment - panic appears in auto composition

### ISSUE THREAD

**Issue by axamon** [Microsoft/vscode#62847]
Issue Type: <b>Bug</b>

create a Go project
import stat (or any other package)
write stat.
press ctrl+space and instead of the functions to use panic appears.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:20:56.183Z)
OS version: Linux x64 4.18.16-300.fc29.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-6410 APU with AMD Radeon R5 Graphics (4 x 1312)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|1, 1, 0|
|Memory (System)|6.77GB (1.24GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
Go|ms-|0.7.0

</details>

**Comment by chrmarti** [comment]
Could you attach a screenshot or explain what 'panic' is?
