### ISSUE TITLE
State lost sometimes when restarting the OS

### ISSUE THREAD

**Issue by akontsevich** [Microsoft/vscode#62844]
- **VSCode Version:** 1.28.2 (reproducible in all older versions as well)
- **OS Version:** openSUSE Tumbleweed

**Steps to Reproduce:**
VS Code remembers opened folder and recent folders and documents on exit, restores them fine on next start. However it fails to do this on KDE exit/restart. On next DE start VS Code shows welcome screen, does not restore previous folder and opened documents - all is empty and default. Moreover, File->Open Recent menu become empty.

**Does this issue occur when all extensions are disabled?:** Yes

**Comment by chrmarti** [comment]
That's stored in either:
- `$VSCODE_APPDATA/.config`
- `$XDG_CONFIG_HOME/.config`
- or `~/.config`

Can you check which is used and if that is preserved across restarts?

**Comment by akontsevich** [comment]
It is stored in `~/.config/Code/storage.json. However can't reproduce bug for now, though happen very often. May be when 2 instances of vscode running, don't know. Will try with 2 copies later.

**Comment by akontsevich** [comment]
Happen again after PC restart. `~/.config/Code/storage.json` content:

```
...
"windowsState": {
        "openedWindows": [],
        "lastActiveWindow": {
            "backupPath": "~/.config/Code/Backups/1541951491527",
            "uiState": {
                "mode": 1,
                "x": 448,
                "y": 185,
                "width": 1024,
                "height": 768
            }
        }
    }
```
Should be:
```
...
"windowsState": {
        "openedWindows": [],
        "lastActiveWindow": {
            "folderUri": {
                "$mid": 1,
                "fsPath": "~/.../Sources/preview/qml-editor",
                "external": "file:///~/.../Sources/preview/qml-editor",
                "path": "~/.../Sources/preview/qml-editor",
                "scheme": "file"
            },
            "backupPath": "~/.config/Code/Backups/a3e26752567d37177ebfd10be7586b23",
            "uiState": {
                "mode": 1,
                "x": 458,
                "y": 157,
                "width": 1333,
                "height": 828
            }
        }
    },
    "pickerWorkingDir": "~/.../Sources/preview",
    "openedPathsList": {
        "workspaces2": [
            "file:///~/.../Sources/preview/qml-editor"
        ],
        "files2": []
    }
```

**Comment by akontsevich** [comment]
> Does it happen as part of the restart? 

Yes, but not every time.

>Was the right content there after you closed VS Code, but before restarting?

If I just close VS Code content is fine as I mentioned previously.

**Comment by chrmarti** [comment]
So the restart causes it, not VS Code?

**Comment by akontsevich** [comment]
I think VS Code on restart, :) does not exits and save settings properly on restart/shutdown. It loses settings for some reason.

**Comment by akontsevich** [comment]
Still happen very often.

**Comment by alexbuzzbee** [comment]
This happens on Windows as well. When I shut down my Windows box, Windows terminates running applications, including VS Code. Apparently, when it does this, VS Code fails to save state. When it next opens, it is left in the same state it was in the last time it was exited normally.

This might be due to Windows doing the equivalent of SIGKILL or due to a bug in VS Code or Electron. Given that other applications (e.g., Firefox, certain Microsoft applications) save state successfully, along with Windows' "waiting for applications to exit" screen, I suspect the latter, but I obviously can't be certain.

**Comment by bpasero** [comment]
I think the only solution is to store state periodically and not just on shutdown where the OS may decide to just kill the application if it takes long to shutdown.

**Comment by bpasero** [comment]
Merging into https://github.com/Microsoft/vscode/issues/12058
