### ISSUE TITLE
Code Lens get clipped on Mac

### ISSUE THREAD

**Issue by jdneo** [Microsoft/vscode#62842]
- VSCode Version: 1.28.2
- OS Version: macOS High Sierra 10.13.6

Steps to Reproduce:

1. Generate a Code Lens which only has a emoji icon.

![screen shot 2018-08-23 at 08 12 59](https://user-images.githubusercontent.com/976374/44507862-6d1cf480-a6ac-11e8-8035-a8bfabe9d6b6.png)

**Comment by jrieken** [comment]
This is very weird.. We are not setting a width constraint on the elements and it seems that the renderer decided that cut-off looks good. For me it is not that bad so I wonder @jdneo Do you have a special size configure for code lens?

<img width="151" alt="screenshot 2018-11-12 at 10 08 26" src="https://user-images.githubusercontent.com/1794099/48337349-05e75e80-e663-11e8-80b1-a900a9f383c3.png">

**Comment by jrieken** [comment]
I have added some padding to code lenses. let me know if this is still a problem with 1.30-insiders

**Comment by jdneo** [comment]
Thank you @jrieken.
I’m on vacation these days will let you know when I get back

**Comment by jdneo** [comment]
@jrieken The padding works well in 1.30-insiders. Thank you!
