### ISSUE TITLE
Running shows Permission denied

### ISSUE THREAD

**Issue by mudit458** [Microsoft/vscode#62846]
Issue Type: <b>Bug</b>

clicking on Terminal->Run Active File

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:20:56.183Z)
OS version: Linux x64 4.15.0-38-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU        P6100  @ 2.00GHz (2 x 1029)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|5.62GB (0.16GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
xml|Dot|2.3.2
gitlens|eam|8.5.6
vscode-html-css|ecm|0.2.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
MagicPython|mag|1.1.0
vscode-clang|mit|0.2.3
python|ms-|2018.10.0
cpptools|ms-|0.20.1
java|red|0.33.0
python|tht|0.2.3

</details>

**Comment by chrmarti** [comment]
What are the permissions on the file?

**Comment by mudit458** [comment]
I don't know I just installed, wrote and run
[image: Screenshot from 2018-11-10 01-36-36.png]

*Please help me solve this.*

**Comment by mudit458** [comment]
![screenshot from 2018-11-10 01-36-36](https://user-images.githubusercontent.com/40176751/48299273-e4666580-e4f0-11e8-8bad-6e3ad2b335ce.png)

The Screen-Shot with the error

**Comment by chrmarti** [comment]
A `.cpp` file won't run as-is from the terminal. You'll first need to build it. Also make sure you install the C++ extension. Take a look at our documentation: https://code.visualstudio.com/docs/languages/cpp
