### ISSUE TITLE
Packaging resources in an extension.

### ISSUE THREAD

**Issue by mat-mcloughlin** [Microsoft/vscode#6284]
Hey I was hoping to include an executable as part of my VsCode extension but can't see any documentation as to if this is possible.

Is it? and if so do you have some guidance?

Thanks in advance

**Comment by jrieken** [comment]
It should just work, unless you have [`.vscodeignore`](https://github.com/Microsoft/vscode-docs/blob/master/docs/tools/vscecli.md#vscodeignore) rules configured

**Comment by jrieken** [comment]
@mat-mcloughlin did this work in the end?

**Comment by mat-mcloughlin** [comment]
Yes it did. Thanks
