### ISSUE TITLE
Expiclitly hidden viewlet does not dispose views inside

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#62841]
Currently the views only get dispossed when the user explicitly makes them hidden: for example right click on call stack view -> hide

I argue that it might make more sense to always dispose all views as soon as they are no longer visible.
This would have the following benefits:
* We dispose objects more eagirly - since right now the main user action is changing viewlets, hiding sidebar, hiding panel and for all of those we do not do any disposing
* No longer must we write weird code to ignore events if I not visible. [Example](https://github.com/Microsoft/vscode/blob/f9307094ba513aad26e18c22143e180aeb8a947b/src/vs/workbench/parts/debug/electron-browser/callStackView.ts#L157)

The downside is obviously that every time a view gets visible we need to re-create it from scratch.
But in practice I am not sure would this be noticable and is there any other downside?

@joaomoreno @sandy081 @jrieken  let me know what you think. There is probably some reason why we are not doing this already that I might be missing

**Comment by sandy081** [comment]
I think this needs storing the view state for custom views. Have to see if there are any hassles with file explorer... will it be laggy?

**Comment by isidorn** [comment]
I can experiment with the speed and lagginess of the explorer if you think this idea is not too bad.

**Comment by sandy081** [comment]
Why not if it is not laggy.

As said, it needs me to store the custom views state may be just like you do for tree explorer. Probably all tree views (search, problems) needs to do. So, a common util would be good.

**Comment by isidorn** [comment]
Ok, assigning to November than to investigate

**Comment by isidorn** [comment]
Ok, your point makes sense. These actions should be light and preserve view state.

The only case I found when we should dispose but we do not is when the user explicitly hides the whole viewlet.
1. Open explorer
2. Right click in activity bar to hide the explorer
3. Notice that the views are not disposed

@sandy081 would you like me to look into this or will you?

**Comment by sandy081** [comment]
@isidorn This is clearly a bug in my area. I will take a look.

**Comment by isidorn** [comment]
@sandy081 renaming this one than, and assigning to you

**Comment by sandy081** [comment]
With current framework it is not possible to dispose viewlets when hidden. Hence not implementing this.
