### ISSUE TITLE
Markdown double hash (##) search isn't working with match whole word

### ISSUE THREAD

**Issue by diberry** [Microsoft/vscode#62856]
Issue Type: <b>Bug</b>

open markdown page in editor with h2s and h3s
need to search for all h2s, enter 2 hashtags in file's search window
select match whole word to distinguish h2s only , don't want to see h3s
all h3s are selected anyway

surface laptop
version 1.28.2
commit sha 7f3ce96ff
electron 2.0.9
chrome 61.0.3161.100
node.js 8.9.3
v8: 6.1.534.41
arch: x64

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (7.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sidebar|Acr|1.0.1
vscode-markdownlint|Dav|0.21.0
docs-article-templates|doc|0.1.3
docs-authoring-pack|doc|0.1.1
docs-markdown|doc|0.1.5
docs-preview|doc|0.3.16
vscode-docker|Pet|0.3.1
code-spell-checker|str|1.6.10

</details>

**Comment by roblourens** [comment]
I don't think that will work as you expect since # is not a "word character"

**Comment by diberry** [comment]
@roblourens Ok, I didn't know exactly how strick the concept of a word is. Thanks for the suggestion of regex.
