### ISSUE TITLE
Emmet abbreviations for color with opacity values do not work

### ISSUE THREAD

**Issue by StickNitro** [Microsoft/vscode#62855]
Issue Type: <b>Bug</b>

I used to be able to type `c:#0.2` which would expand to `color: rgba(0,0,0,.2)` but this no longer seems to be working

VS Code version: Code - Insiders 1.29.0-insider (5e481940ccf7ed9005dfd810f586c09a49421355, 2018-11-09T14:55:36.370Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.04GB free)|
|Process Argv|-psn_0_3437383|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-angular2-files|ale|1.6.2
sort-imports|ama|6.0.0
ng-template|Ang|0.1.10
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
githistory|don|0.4.3
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.40
vscode-npm-script|eg2|0.3.5
auto-close-tag|for|0.5.6
code-runner|for|0.9.5
vscode-pull-request-github|Git|0.2.3
vscode-gist|ken|1.2.1
git-indicators|lam|2.1.1
code-beautifier|mic|2.1.0
vscode-scss|mrm|0.6.2
debugger-for-chrome|msj|4.11.0
color-highlight|nau|2.3.0
vscode-html-scss|P-d|0.0.42
typescript-hero|rbb|3.0.0
vscode-icons|rob|7.28.0
vsfire|tob|1.3.2

</details>

**Comment by StickNitro** [comment]
Also `bd1:s:#0` used to expand to `border: 1px solid #000`, there are others I am sure

**Comment by ramya-rao-a** [comment]
@swashata You are on 1.30 Insiders which had an issue due to which none of the Emmet features were working. That bug is fixed in the latest Insiders, please give that a try. 

@StickNitro Neither `c:#0.2` nor `bd1:s:#0` was ever supported in VS Code atleast since the last 2 years as far as I know.

`c:#0.2` is a valid abbreviation that is not supported at the moment. This is a bug.
But `bd1:s:#0` doesnt look like a valid abbreviation. I tried it in https://docs.emmet.io/ and didnt get your expected result.

**Comment by ramya-rao-a** [comment]
To add support for abbreviations like `c:#0.2`, the regex used for hex color value in `vscode-emmet-helper` should be updated at https://github.com/Microsoft/vscode-emmet-helper/blob/master/src/emmetHelper.ts#L967-L968

**Comment by swashata** [comment]
@ramya-rao-a Thank you and yes you are absolutely correct. It was indeed a bug for that particular version of insider. Now I have it updated and it's gone. Thank you for your great work, you are awesome!!
