### ISSUE TITLE
Wrong output in Debug output of C/C++

### ISSUE THREAD

**Issue by KingLebron** [Microsoft/vscode#6285]
- VSCode Version: 1.1.0
- OS Version:   OS X Version 10.11.4

Steps to Reproduce:

1. Write the following code
```c
    int array[] = {9, 8, 7, 6, 5, 4, 3};
    int size = sizeof(array)/sizeof(int);
    for (int i = 0; i < size; i++)
    {
        fprintf (stdout, "%d ", array[i]);
        fflush(stdout);
    }
```
2. output should be:

> 9 8 7 6 5 4 3

however the output is
> 8 7 6 5 4 3 

The '9' is lacked.

**Comment by isidorn** [comment]
Sounds like an issue for the c++ extension, I have moved it to their repository https://github.com/Microsoft/vscppsamples/issues/43
