### ISSUE TITLE
Leaner launch.json generation

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#62851]
- [x] Node https://github.com/Microsoft/vscode-node-debug/issues/185
  - [ ] C# https://github.com/OmniSharp/omnisharp-vscode/issues/2673
  - [x] Python https://github.com/Microsoft/vscode-python/issues/3321
  - [x] Java https://github.com/Microsoft/vscode-java-debug/issues/476
  - [ ] C++ https://github.com/Microsoft/vscode-cpptools/issues/2819
  - [x] Chrome https://github.com/Microsoft/vscode-chrome-debug/issues/751
  - [ ] **Help Wanted** Php https://github.com/felixfbecker/vscode-php-debug/issues/318
  - [ ] Go https://github.com/Microsoft/vscode-go/issues/2120
  - [ ] Powershell https://github.com/PowerShell/vscode-powershell/issues/1611
  - [ ] React Native https://github.com/Microsoft/vscode-react-native/issues/830
  - [x] **Help Wanted** Ruby https://github.com/rubyide/vscode-ruby/issues/404 thanks @YisraelV 
  - [x] Docker https://github.com/Microsoft/vscode-docker/issues/612

These are all the extensions from our top 100 which support debugging.

**Comment by isidorn** [comment]
@weinand houghts if node should be simplified, currently it generates the following file

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${file}"
        }
    ]
}
```

imho I like this and would not add any wizard that asks if you would like to launch / attach
I think the bigger issues are other extensions and I would start there

**Comment by isidorn** [comment]
@roblourens chrome currently generates this

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceFolder}"
        },
    ]
}
```

I also like that and I think we should be aligned with what node is doing.
What you profit from using quick pick to ask some questions? Did you notice that users get puzzled by something or that somethins is especially hard to setup? Like source maps for example?

**Comment by roblourens** [comment]
Configuring sourceMapPathOverrides and pathMapping is still an issue, but it's something you have to "discover" by looking at the app during runtime, I wouldn't try to make it easier during launch config creation.

If we want to optimize for few parameters by default, `webRoot` could be removed and defaulted to `workspaceFolder`. I think it helps to have it in the default config so it can be discovered more easily but I don't know how often it has to be changed.

**Comment by isidorn** [comment]
Adding `help wanted` as we need user help currently for ruby and might potentially need it for other extensions. The work needed is updating ruby to user the newest vscode debug configuration api. More details can be found here https://github.com/rubyide/vscode-ruby/issues/404 and the PR should be done against that repository.
There are extensions which are already using latest vscode debug configuration api which can be used as examples, for instance [node debug](https://github.com/Microsoft/vscode-node-debug)

**Comment by YisraelV** [comment]
@isidorn after struggling for some time with escaping the $ symbol in configurationSnippets I found this syntax in the node extension you linked to:

"localRoot": "^\"\\${workspaceFolder}\"",

could you please tell me:
1. is there any documentation on the use of the caret symbol as escape character in snippets (could be I'm missing the obvious)
2. why isn't the syntax provided [here ](https://code.visualstudio.com/docs/editor/userdefinedsnippets)(under Grammar) enough for escaping? it didn't work for me.

Thank you.

**Comment by isidorn** [comment]
@YisraelV here's some snippet documentation https://code.visualstudio.com/docs/editor/userdefinedsnippets
For more details @jrieken  would be better to answer. But I think there are some corner cases with the $ symbol and thus it has to be double escaped. I would just try to copy what nodeDebug does 
https://github.com/Microsoft/vscode-node-debug/blob/660175936b0d83277a1b8b2a8a0f2f868ccd032b/package.json#L169

Hope that helps, and thanks for your contribution

**Comment by isidorn** [comment]
We have provided feedback to most popular extensions, some are already updated and some are planning to update. Since all the work pllaned has been done I am closing this
Some related follow up work https://github.com/Microsoft/vscode/issues/65988
