### ISSUE TITLE
PowerShell command prompt doesn't show until you press some keys

### ISSUE THREAD

**Issue by gbracey** [Microsoft/vscode#62854]
Issue Type: <b>Bug</b>

Launch VS Code with Microsoft Powershell extesnion installed.  Open Terminal window in PowerShell.  Windows Powershell copyright text appears, but not command prompt.  Once I hit a few keys, the prompt shows.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (2 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|8.00GB (5.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|40%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
PowerShell|ms-|1.9.0

</details>

**Comment by leomoty** [comment]
I can also reproduce this on my home computer.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz (8 x 3500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (5.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|0.8.8
vscode-eslint|dba|1.7.0
gitlens|eam|8.5.6
prettier-vscode|esb|1.7.2
dotnet-test-explorer|for|0.5.5
smarty|imp|0.3.0
csharp|ms-|1.17.0
vsliveshare|ms-|0.3.925
vetur|oct|0.13.0
laravel-blade|one|1.18.0
vscode-docker|Pet|0.3.1
vscode-coverage-gutters|rya|2.2.1
code-settings-sync|Sha|3.2.0
markdown-preview-enhanced|shd|0.3.11
twig|wha|1.0.2


</details>

**Comment by adamhewitt627** [comment]
I can also reproduce this, and believe it's related to Windows 17763. It was one of the first things I noticed after updating the OS (without a VSCode update) and just haven't gotten around to logging it.

**Comment by dlucazeau** [comment]
I have also this issue. and lost all my history of commands.
VSCode Insiders 1.30.0 or VSCode 1.29.1
Windows 10 : 10.0.17763.134 (Win10 RS5 [1809] October 2018 Update) [Updated on 11/24/18]

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/57803
