### ISSUE TITLE
vscode.window.showInformationMessage hangs forever after pressing Escape

### ISSUE THREAD

**Issue by ruslan-bikkinin** [Microsoft/vscode#62853]
Issue Type: <b>Bug</b>

## Description

Closing windows created with `vscode.window.showInformationMessage` by pressing Escape button makes function refuse to go to neither onResolved nor onRejected callbacks. However, closing window by clicking on `x` button works as expected.

Simple extension snippet:

```ts
'use strict';
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {

    let disposable = vscode.commands.registerCommand('extension.ShowInformationalMessage', () => {
        // Press Escape after notification is shown
        vscode.window.showInformationMessage('Close me by pressing Escape button').then(() => {
            // Unfortunately, you can't get over here  
            console.log("Okay");
        }, (err) => {
            // And you can't get over here, too
            console.log("Not okay");
            console.log(err);
        });
    });

    context.subscriptions.push(disposable);
}

export function deactivate() {
}
```

## Steps to reproduce
* Clone [this demo project](https://github.com/ruslan-bikkinin/demoInfoMessage) which is simple extension created with yo generator
* Install packages for project
* Open it in VS Code and start `Launch Extension` debug configuration
* In new VS Code window run palette command `Show informational message` - notification window will be opened
* Press Escape

## Expected Behavior
* `Okay` message is logged in `Debug Console` output window in main VS Code instance

## Actual Behavior
* No message is logged in which signalizes that function hangs. 

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.40
cordova-tools|vsm|1.5.1
vscode-react-native|vsm|0.6.18

</details>

**Comment by bpasero** [comment]
@ruslan-bikkinin yes what you describe is the correct behaviour, an notification is only considered to be closed when it is removed from the notification center either by pressing the X from the toast when it appears or by using other actions to clear notifications (there is a command to close all notifications). Pressing ESC will just hide any notification toasts so that you can free up some space but the user still has to deal with the notification later from the notification center. We think this is the better behaviour for you to code against.

Closing as designed, it is unlikely we would change this behaviour.
