### ISSUE TITLE
Constant crashes that require window reloading.

### ISSUE THREAD

**Issue by tot0** [Microsoft/vscode#62858]
Issue Type: <b>Bug</b>

Multiple times every day I come back to VSCode to find it saying the window has stopped responding and needs to be reloaded or waited for. Waiting never works. This is VERY annoying.

VS Code version: Code - Insiders 1.29.0-insider (5438af145cf480ce0162bda0799435684b293ec5, 2018-11-07T01:01:54.305Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (3.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.60
scala|dal|0.0.5
gitlens|eam|8.5.6
nbpreviewer|jit|1.0.0
python|ms-|2018.10.0
cpptools|ms-|0.20.1
csharp|ms-|1.17.0
PowerShell|ms-|1.9.0
code-settings-sync|Sha|3.2.0

</details>

**Comment by chrmarti** [comment]
@tot0 Please update to the latest insiders build (5f24c93878) where we have fixed one source of freezes and let us know if you still see this problem.
