### ISSUE TITLE
File/Folder Picker is too small

### ISSUE THREAD

**Issue by Frogmore42** [Microsoft/vscode#62863]
Issue Type: <b>Bug</b>

1. 32" 4K monitor
2. Display scale set to 175% (also shows up at 150%)
3. Windows 1803

Looks like the open folder dialog is not respecting the scale factor so it shows up too small.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.66GB (11.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.5.6
PowerShell|ms-|1.9.0
gitconfig|sid|2.0.0
markdown-all-in-one|yzh|1.7.0

</details>

**Comment by Frogmore42** [comment]
![image](https://user-images.githubusercontent.com/14101627/48282292-266aab00-e40e-11e8-995e-a32177d5fa70.png)

**Comment by Frogmore42** [comment]
![image](https://user-images.githubusercontent.com/14101627/48282454-924d1380-e40e-11e8-887d-42b1c37f5a3e.png)

**Comment by chrmarti** [comment]
The dialog is from the OS, try increasing the font size there. I doubt we can pass the zoom factor to the dialog.

**Comment by Frogmore42** [comment]
Except that the same dialog on the OS is appropriately sized at the 175% scale factor I have already chosen.  It appears that when called from VSCode the dialog gets displayed at 100% scale, which makes it pretty tiny.

**Comment by Frogmore42** [comment]
Looks like this is what happens when you change scale/zoom on the OS but don't restart the OS.  Some apps don't get the message that the scale has changed until you reboot.  Once I rebooted after having already changed the scale, the window appeared at an appropriate size.
