### ISSUE TITLE
Code formatting shouldn't happen during merge resolutions

### ISSUE THREAD

**Issue by kernhanda** [Microsoft/vscode#62862]
Issue Type: <b>Bug</b>

If you're writing C++ code and have clang-format enabled as well as format on save enabled, the results can be really annoying when dealing with merge conflicts. clang-format will automatically mess with the merge markers, which makes VS Code unable to highlight them. I imagine this isn't a problem unique to C++ or clang-format. 

A simple solution would be to not run code formatting when merge markers are detected.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:12.403Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 3492)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (4.18GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
githistory|don|0.4.3
tslint|eg2|1.0.40
vscode-highlight|fab|1.3.2
vscode-todo-plus|fab|4.9.4
beautify|Hoo|1.4.7
latex-workshop|Jam|5.15.1
vscode-clang|mit|0.2.3
prettify-json|moh|0.0.3
python|ms-|2018.10.0
cpptools|ms-|0.20.1
PowerShell|ms-|1.9.0
vscode-docker|Pet|0.3.1
reloaded-cpp|rel|0.1.6
llvm|RRe|0.0.3
code-spell-checker|str|1.6.10
cmake|twx|0.0.17
gitblame|wad|2.6.0

(2 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
Debatable... In the presence of syntax errors (that's what merger markers usually are) a formatter shouldn't do anything. I'd say that's an issue with that specific formatter. E.g. TypeScript understand merge markers (and treats them like comments) and then not formatter wouldn't be correct

**Comment by jrieken** [comment]
> A simple solution would be to not run code formatting when merge markers are detected.

Marking as out-of-scope as it's not so simple for us. First, you need to teach VS Code what a merge marker is, then you need honour some setting to disable formatters in that case. Then it's actually true that you don't ever want to format when having invalid syntax and that's something only the language brain/formatter knows

**Comment by moander** [comment]
> First, you need to teach VS Code what a merge marker is, then you need honour some setting to disable formatters in that case.

VS code now know that a file is in a merging state. Is it possible to disable formatting during this stage only?

**Comment by Maddimax** [comment]
Can we reopen this issue? Its still a problem in 2024 with c++ code formatting. It regularly makes quite a bit of work when you just save a file during merge issue resolution.
