### ISSUE TITLE
Allow conditional user settings

### ISSUE THREAD

**Issue by remi2j** [microsoft/vscode#62868]
**Problem**
I like the minimap on my external monitor, but it's taking too much space when I'm using my laptop's display.

**Feature request**
Allow us to apply settings conditionally, for example based on the app's window size. It could look somewhat like this:
```javascript
editor.minimap.enabled: false
window.breakpoint: '1000px' // let the user decide what a large window is
window.isLarge: {
  // Apply regular settings here, like:
  editor.minimap.enabled: true
}
```

**Comment by jabacchetta** [comment]
I'd love the ability to have the terminal panel positioned on the bottom when on a laptop, and on the right when on my external monitor.
