### ISSUE TITLE
fold up

### ISSUE THREAD

**Issue by amgalan81mn** [Microsoft/vscode#62867]
Issue Type: <b>Feature Request</b>

ctrl+shift+] unfold row       works fine,                    better than sublime.
ctrl+shift+[     fold row not works fine, you can do better than sublime
intellig Idea does much better, you can find out how they behave

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

**Comment by aeschli** [comment]
@amgalan81mn Please give an example along with describing the expected/improved behaviour.
