### ISSUE TITLE
Editor should be focused immediately after switching working files

### ISSUE THREAD

**Issue by mavsic** [Microsoft/vscode#6286]
- VSCode Version: 1.1.0
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Open several working files
2. Switch current working file by clicking on it in Working Files pane
3. Now the focus is in Explorer view, although user (me) expects it to be in editor instead

One of the consequences of this issue is that it is inconvenient to copy and paste text between working files. User can't press Ctrl+V immediately after switching current file as the editor is not focused.

**Comment by mavsic** [comment]
Oh, I've just found a similar issue: #5105.

**Comment by isidorn** [comment]
We are revisiting working files in the future, also you found a similar issue so closing this one
