### ISSUE TITLE
Files are not reopened on restart

### ISSUE THREAD

**Issue by Mellbourn** [Microsoft/vscode#62874]
- VSCode Version: 1.28.2
- OS Version: macOS Mojave 10.14.1

Steps to Reproduce:

1. start code
2. open a folder
3. open some files in the folder
4. close code
5. start code
6. folder is opened, but previously opened files are not opened

Also, recently run commands have also been forgotten. If I do command-shift-P, it does not show any recent commands.

I've had this problem for maybe a couple of weeks. 
I have checked all the output buffers, but there are no errors logged.
I have tried clearing recently opened files, but that does not help.
Reinstalling code does not help.
Removing all user settings does not help.
I've searched the log files in ~/Library/Application Support/Code for errors, but haven't found anything.

Does this issue occur when all extensions are disabled?: Yes

The problem is not present in the insider's build. So maybe there is something wrong with my global configuration, but what? How do I troubleshoot this?

EDIT:
OK, I managed to repair it.  What helped was completely removing the whole folder `~/Library/Application Support/Code` and reinstalling code. Still have no idea what exactly went wrong.

**Comment by bpasero** [comment]
Yeah, you "fixed" this by removing the DB that contains our UI state. I suspect that the DB was in a broken state. Hard to diagnose after the fact now though. What will help in the future is our intent to move away from this DB to store UI state.

**Comment by Mellbourn** [comment]
I actually have the old folder left (in my Trash). So I could send it to you if you want to analyze it.
