### ISSUE TITLE
Menu items with no group specified are now shown in separate groups

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode#62875]
Issue Type: <b>Bug</b>

**Was this an intentional change?**

For instance, in the Cosmos DB extension (ms-azuretools.vscode-cosmosdb):

Version: 1.28.2 (user setup):
![image](https://user-images.githubusercontent.com/6913354/48294148-68f4ad80-e437-11e8-891b-d82a6574788b.png)

VS Code version: Code - Insiders 1.29.0-insider (5438af145cf480ce0162bda0799435684b293ec5, 2018-11-07T01:01:54.305Z):
![image](https://user-images.githubusercontent.com/6913354/48294157-7316ac00-e437-11e8-8411-e0d03a1db05e.png)

The corresponding view/item/context items look like:
				{
					"command": "cosmosDB.copyConnectionString",
					"when": "view == cosmosDBExplorer && viewItem == cosmosDBGraphAccount"
				},
				{
					"command": "cosmosDB.createGraphDatabase",
					"when": "view == cosmosDBExplorer && viewItem == cosmosDBGraphAccount"
				},

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.73GB (11.55GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/stephwe/Repos/vscode-docker|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.40
vscode-antlr4|mik|2.0.4
vscode-azureappservice|ms-|0.9.1
vscode-azurestorage|ms-|0.4.2
vscode-cosmosdb|ms-|0.8.0
extension-manifest-editor|ms-|0.1.5
azure-account|ms-|0.6.0
csharp|ms-|1.17.0
azurerm-vscode-tools|msa|0.4.2
vscode-docker|Pet|0.3.1

</details>

**Comment by sandy081** [comment]
Caused by https://github.com/Microsoft/vscode/commit/0ce7badda9459ec194893dd58d62d890e8f1a301


Tagging this candidate as it is a regression

**Comment by jrieken** [comment]
@mjbvz please undo that strict null change
