### ISSUE TITLE
how to locate which extension cause high cpu

### ISSUE THREAD

**Issue by waiaan** [Microsoft/vscode#62877]
![image](https://user-images.githubusercontent.com/25977464/48295869-372d2680-e4cb-11e8-8f57-2b35350606f5.png)

thanks

**Comment by chrmarti** [comment]
The `--type` tells you which process you are looking at. Here the second row is the extension host. 12% doesn't sound high. Is there a problem with that?

**Comment by waiaan** [comment]
> The `--type` tells you which process you are looking at. Here the second row is the extension host. 12% doesn't sound high. Is there a problem with that?

thanks, I've found that is because of the Bracket Pair Colorizer 2 extension.
 Is there any way to find out which extension is costing cpu ? or mark the extension that may cause that situation in marketplace?

**Comment by chrmarti** [comment]
You can profile the extension host: https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions
