### ISSUE TITLE
Code formatting, post positioning error

### ISSUE THREAD

**Issue by shenlanchenwei** [Microsoft/vscode#62879]
Issue Type: <b>Bug</b>

If the code in the code is collapsed, then the code is formatted, all the folds will be automatically expanded, resulting in a wrong display position.

Expected results: the collapsed code continues to collapse after formatting

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.87GB (9.17GB free)|
|Process Argv|D:\WorkSpace\Hone.IM.Core\IM.CS\im-client|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-eslint|dba|1.7.0
code-runner|for|0.9.5
dotnet|for|0.0.4
vue-snippets|hol|0.1.9
beautify|Hoo|1.4.7
vscode-tfs|iva|0.7.2
csharpextensions|jch|1.3.0
electron-debug|kod|18.11.0
vscode-csproj|luc|0.7.0
vscode-language-pack-zh-hans|MS-|1.28.2
csharp|ms-|1.17.0
debugger-for-chrome|msj|4.11.0
vetur|oct|0.13.0
vscode-icons|rob|7.28.0
aspnet-helper|sch|0.6.4
vscode-hexdump|sle|1.7.2
JavaScriptSnippets|xab|1.7.1
html-css-class-completion|Zig|1.17.1

</details>

**Comment by aeschli** [comment]
That should only happen if the formatter changes the code in such a a way that there's no longer a folding region.
Here's what I see with the built-in HTML formatter on collapsed code. Formatting does not uncollapse:
![folding-on-format](https://user-images.githubusercontent.com/6461412/50842293-ab1e6a80-1366-11e9-8c96-7a63b6820d65.gif)

Please add a small reproducible code sample and describe the steps. If possible add screenshots/animated gifs as well.

**Comment by aeschli** [comment]
Need reproducible steps...
