### ISSUE TITLE
VSCode disable large folders warning

### ISSUE THREAD

**Issue by gladiator001** [Microsoft/vscode#62871]
The same issue was reported here https://github.com/Microsoft/vscode/issues/31188 and it was closed, locked and limited conversation to collaborators. However, some users are still experiencing the same issue over and over. 

- VSCode Version:
1.28.2 (1.28.2)

- OS Version:
macOS Mojave version 10.14.1

Steps to Reproduce:
1. Open a large workspace project in vscode.
2. The annoying message toast warning notification popup appears.
>To enable project-wide JavaScript/TypeScript language features, exclude large folders with source files that you do not work on.

Does this issue occur when all extensions are disabled?
Yes

**Comment by mjbvz** [comment]
Did you try configuring your jsconfig or tsconfig to exclude large folders, such as `node_modules` and build outputs?
