### ISSUE TITLE
.d.ts files not recognized during compilation if camel-cased

### ISSUE THREAD

**Issue by dartzki** [Microsoft/vscode#6287]
- VSCode Version: 1.1.0
- OS Version: Arch

Steps to Reproduce:
- create a custom .d.ts file to merge an ambient typing interface definiton, e.g.:

```
//in customMatcher.d.ts
declare namespace jasmine {
    interface Matchers {
        toContainNoDialogs(): void;
    }
}
```
- use added method in other file

```
expect($window.history.state).toContainNoDialogs();
```

vs-code will show an error 

> Property 'toContainNoDialogs' does not exist on type 'Matchers'.

however, tsc compiles the code correctly without warnings.

**Comment by dbaeumer** [comment]
@dartzki which version of tsc do you have installed (e.g. tsc --version)

**Comment by dartzki** [comment]
I'm using 1.8.9 from npm and am using the same version by overriding "typescript.tsdk" in my workspace settings.

**Comment by dbaeumer** [comment]
@dartzki strange :-). Could you share your project. Would be easier for me to reproduce.

**Comment by dartzki** [comment]
Sorry, I can't

I'll try to reproduce it in a simple project on github

**Comment by dbaeumer** [comment]
Thanks !

**Comment by dartzki** [comment]
here's the project:
https://github.com/dartzki/typescript-vscode-test

it's nothing functional, but tests (gulp test) should run

**Comment by dbaeumer** [comment]
The problem is that a ts file has always preference over a d.ts file. So you can't have both a customMatchers.ts and a customMatchers.d.ts in your workspace.
