### ISSUE TITLE
Color Scheme and Theme

### ISSUE THREAD

**Issue by bhanuvikram** [Microsoft/vscode#62878]
Issue Type: <b>Feature Request</b>

Hi, 

I am new to coding and I have been using Sublime Text. 

**Color Scheme and Theme are two separate things on Sublime Text.** 

I could not find a way to lighten the borders on VSC. This is possible under Themes in Sublime Text. Could you please add an option to allow users to lighten or darken the areas outside the code editor? 

Thanks, 
Bhanu 

![untitled](https://user-images.githubusercontent.com/5193270/48295952-e8897900-e445-11e8-8986-40e2619eb9c4.png)

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

**Comment by usernamehw** [comment]
Do you mean the same thing as in this issue #25986 (to be able to set light GUI and dark syntax)?

It's already possible to do that only by hand. In Settings:
```json
"workbench.colorCustomizations": {
    "titleBar.activeBackground": "#ffffff",
    "titleBar.activeForeground": "#000000",
    "menu.background": "#ffffff",
    "menu.foreground": "#000000",
    "menubar.selectionBackground":"#00000040",
}
```
