### ISSUE TITLE
[git] File is shown under `Changes` even when all changes have been staged

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode#6288]
- VSCode Version: 1.1.0-inside
- OS Version: Windows 10

Steps to Reproduce:

1. Open a file which has changes
2. Select some lines, and click on `Stage Selected Lines` in the ellipsis menu on top-right.
3. When you've staged all the lines, the file is still there in the **Changes** section.

What Should Happen:
File should be immediately removed from the changes section when all it's changes have been staged.

**Comment by isidorn** [comment]
Do you still see this after 10seconds?
There is a small delay we use for refreshing the git viewlet

**Comment by kumarharsh** [comment]
For me, switching tabs refreshes the list.

**Comment by kumarharsh** [comment]
There is also the subtle *bug* which I encountered today, which triggered me to write this issue: I had not setup the `autocrlf` config for my repo, so even after staging all marked hunk diffs, vscode was not refreshing the `CHanges` section because there would have been `^M` characters in the diff making the file unclean. This is not marked in the diff view, which caused some head-scratching.

**Comment by kumarharsh** [comment]
@isidorn I'm sorry but on further investigation I think this is a false alarm. The files not clearing is definitely being caused by the hidden CRLF characters which are not marked in the vscode diff.

Should I raise a separate bug for that, or can we convert this one to read "vscode doesn't visualize changed newline characters in diffs" or something along those lines?

**Comment by isidorn** [comment]
I believe there is already a feature request for that - please search for it, and if you can not find it please file a new issue - thanks!
