### ISSUE TITLE
reset terminal session

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/vscode#62882]
I can open a new terminal window, but what I want to do is reset the terminal session = close it + open a new session. If I hit the delete/trash button, it just closes it, but I want to reopen it too!

I think the reset command is what I am looking for - 
https://askubuntu.com/questions/19772/how-to-reinitialize-a-terminal-window-instead-of-closing-it-and-starting-a-new-o

but if the reset command can be integrated into the VSCode UI, that would be nice. I think just a refresh icon with a tooltip that says "reset terminal session" or something, would be good.

**Comment by Tyriar** [comment]
You could do a keybinding to send the reset sequence, I don't think that's actually what you want though. I recommend creating a basic extension that just sends the kill and new terminal commands.
