### ISSUE TITLE
startup is very slowly -1.28.2

### ISSUE THREAD

**Issue by happytigeryang** [microsoft/vscode#62887]
code startup or open file   is very slowly (>20s).

Raw Startup Timers (CSV)
Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:5075 Name	Start
main:started 	1541839937908 
main:appReady 	1541839938017 
main:loadWindow 	1541839938363 
renderer/started 	1541839958648 
willShowPartsSplash 	1541839958656 
willAccessLocalStorage 	1541839958656 
didAccessLocalStorage 	1541839958656 
didShowPartsSplash 	1541839958799 
willLoadWorkbenchMain 	1541839958809 
didLoadWorkbenchMain 	1541839959643 
main/startup 	1541839959643 
willStartWorkbench 	1541839959721 
willLoadExtensions 	1541839959725 
LifecyclePhase/Restoring 	1541839959743 
willRestoreEditors 	1541839959798 
didRestoreEditors 	1541839959984 
LifecyclePhase/Running 	1541839959984 
didStartWorkbench 	1541839959993 
extensionHostReady 	1541839961596 
didLoadExtensions 	1541839961596 
LifecyclePhase/Eventually 	1541839962951 

CPUs | Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)
-- | --
GPU Status | 2d_canvas: enabledchecker_imaging: disabled_offflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwarerasterization: enabledvideo_decode: enabledvideo_encode: enabledwebgl: enabledwebgl2: enabled
Memory (System) | 7.91GB (4.98GB free)
Process Argv |  
Screen Reader | no
VM | 0%

CPU %	Mem MB	   PID	Process
    0	   103	  1380	code main
    0	    93	  5776	   shared-process
    0	    23	  6420	   utility
    1	    65	  6504	   window (Issue Reporter)
    2	    92	  8876	   gpu-process
    0	   288	  8912	   window (Settings - Visual Studio Code)
    0	    14	  4964	     electron-crash-reporter
    0	    80	  7420	     extensionHost

Extension | Author (truncated) | Version
-- | -- | --
html-snippets | abu | 0.2.1
npm-intellisense | chr | 1.3.0
vscode-eslint | dba | 1.7.0
xml | Dot | 2.3.2
gitlens | eam | 8.5.6
vscode-html-css | ecm | 0.2.0
tslint | eg2 | 1.0.40
vscode-great-icons | emm | 2.1.44
react-native-react-redux | EQu | 1.9.2
live-html-previewer | hdg | 0.3.0
beautify | Hoo | 1.4.7
rest-client | hum | 0.20.3
easy-icons | jam | 0.3.1
node-module-intellisense | lei | 1.5.0
vscode-scss | mrm | 0.6.2
mssql | ms- | 1.4.0
cpptools | ms- | 0.20.1
csharp | ms- | 1.17.0
node-debug2 | ms- | 1.29.5
vs-keybindings | ms- | 0.2.0
debugger-for-chrome | msj | 4.11.0
vscode-docker | Pet | 0.3.1
vscode-icons | rob | 7.28.0
sass-indented | rob | 1.4.9
vscode-sql-beautify | sen | 0.0.4
react-beautify | tai | 0.3.0
vscode-react-native | vsm | 0.6.18
bootstrap-3-snippets | wcw | 0.1.0
debug | web | 0.22.0

**Comment by dbaeumer** [comment]
I am closing the issue as out of date.
