### ISSUE TITLE
Add the abillity to toggle panel with ui button

### ISSUE THREAD

**Issue by pavanagrawal123** [Microsoft/vscode#62880]
This panel here:
![image](https://user-images.githubusercontent.com/17802917/48296644-fa2b4a80-e45e-11e8-8201-79c83b7fc414.png)
Should be collapsible. Helpful for laptops with smaller screen heights/reading details anywhere, i.e. the new GH pull request extension, readme files, etc.

Currently, I only see maximize and restore. If I drag to the bottom, I have to drag it back up to get it back to the same size.

**Comment by cleidigh** [comment]
@pavanagrawal123 
The command "toggle panel" will hide and show the panel retaining its last size.
You can assign any key to the command.

**Comment by pavanagrawal123** [comment]
Yeah this is what I was looking for, so sorry I missed this. I guess it would be nice to have a button for it in the panel, but that's a really minor issue!

**Comment by cleidigh** [comment]
@chrmarti - excuse my speech recognition, it decided to unassigned you :-(

**Comment by cleidigh** [comment]
@pavanagrawal123 
Changed your title to clarify the request for a button.

**Comment by chrmarti** [comment]
There is also an 'X' button that does that.

**Comment by pavanagrawal123** [comment]
@chrmarti there is no button to restore it to the original size which was my main concern, but I feel like it's kinda nit picky, so I'm fine with this request staying closed.
