### ISSUE TITLE
总是卡住不动，cpu使用率狂飙

### ISSUE THREAD

**Issue by ZiFar** [Microsoft/vscode#62884]
Issue Type: <b>Bug</b>

总是卡住不动，cpu使用率狂飙

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (6.70GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.3.2
sproto-support|ily|0.0.1
vscode-language-pack-zh-hans|MS-|1.28.2
vscode-lua|tri|0.12.4
vim|vsc|0.16.12
vscode-todo-highlight|way|1.0.4

(2 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
Could you please follow steps in https://github.com/Microsoft/vscode/wiki/Performance-Issues to help troubleshoot?
