### ISSUE TITLE
$ in markdown (.md) file changes it to \$

### ISSUE THREAD

**Issue by deadcoder0904** [Microsoft/vscode#62889]
Issue Type: <b>Bug</b>

# Reproduction Steps

1. Create `README.md`
2. Enter `$10` in it & Save file
3. It should change to `\$10`

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz (4 x 2000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (0.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
html-css-class-completion|Zig|1.17.1
alignment|ann|0.3.0
code-gnu-global|aus|0.2.2
aws-amplify-vscode|aws|0.0.4
color-info|bie|0.5.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.60
vscode-eslint|dba|1.7.0
githistory|don|0.4.3
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.40
vsc-material-theme|Equ|2.5.1
prettier-vscode|esb|1.7.1
auto-rename-tag|for|0.0.15
code-runner|for|0.9.5
latex-workshop|Jam|5.15.1
docthis|joe|0.7.1
vscode-styled-components|jpo|0.0.23
vscode-colorize|kam|0.7.2
swift|Kas|0.0.3
graphql-for-vscode|kum|1.12.1
vscode-language-babel|mgm|0.0.21
dotenv|mik|1.0.1
cpptools|ms-|0.20.1
sublime-keybindings|ms-|4.0.0
wordcount|ms-|0.1.0
debugger-for-chrome|msj|4.11.0
tachyons|oct|0.3.0
vscode-jest|Ort|2.9.2
advanced-new-file|pat|1.2.0
vscode-versionlens|pfl|0.22.0
material-icon-theme|PKi|3.6.0
vscode-graphql|Pri|0.1.6
code-settings-sync|Sha|3.2.0
markdown-preview-enhanced|shd|0.3.11
velocity|sod|0.1.0
ayu|tea|0.16.0
highlight-matching-tag|vin|0.8.1
vscode-jss-snippets|vis|0.2.2
vscode-wakatime|Wak|1.2.3

(6 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce with all extensions disabled?

**Comment by deadcoder0904** [comment]
Nope, so I'll close this. Its an issue with some extension I guess.
