### ISSUE TITLE
Cursor does not come into view

### ISSUE THREAD

**Issue by graphicagenda** [Microsoft/vscode#62888]
Issue Type: <b>Bug</b>

When I move the cursor and the window is far off to the right on a long line of code, the window does not show the cursor when I move it left or right or type in a new character.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (3.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-standardjs|che|1.2.3
vscode-eslint|dba|1.7.0
gitlens|eam|8.5.6
tslint|eg2|1.0.40
terminal|for|0.0.10
browsersync|jer|1.1.1
vscode-language-babel|mgm|0.0.21
python|ms-|2018.10.1
js-atom-grammar|ms-|0.1.14
debugger-for-chrome|msj|4.11.0
LiveServer|rit|5.1.1
vscode-icons|rob|7.28.0

(1 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment]
Let's track in #50304
