### ISSUE TITLE
More Robust Metadata for TM Scopes

### ISSUE THREAD

**Issue by paul-lapczynski** [Microsoft/vscode#62897]
Could there be more robust metadata on TM Scopes for typescript types? Specifically to help distinguish classes vs interfaces.

**Use Case**

![image](https://user-images.githubusercontent.com/20756305/48303987-f7246e80-e4df-11e8-85b3-cbff534f11f5.png)

![image](https://user-images.githubusercontent.com/20756305/48304000-2aff9400-e4e0-11e8-8e5d-893a65166d10.png)

There is no way to customize styling differently between these.
When declaring the type there is nothing that distinguishes them. Closest seems to be 
> entity.name.type.ts 

but obviously results in
![image](https://user-images.githubusercontent.com/20756305/48304063-fb9d5700-e4e0-11e8-8643-1093f78c8475.png)

**Comment by mjbvz** [comment]
This information is impossible to determine at the grammar level. You need semantic highlighting: #585
