### ISSUE TITLE
Stylesheets do not apply (have no effect) inside Webviews

### ISSUE THREAD

**Issue by bxantus** [Microsoft/vscode#62892]
- VSCode Version: 1.28.2
- OS Version: windows 10

When using the webview API to display custom html content, linked stylesheets have no effect. I checked, with Developer Tools, that stylesheets are loaded correctly. Also checked that selectors are valid, but the rules still do not participate in the cascade.
The problem can be reproduced with an opensource example extension as well: https://github.com/rebornix/vscode-webview-react (I am building a different extension, but posting this link is much easier, than reproducing in my own environment)

Steps to Reproduce:

1. build the extension (npm run build)
2. start the extension and execute the 'Start React Webview' command
3. Notice, using developer tools, that styles from the loaded main.xyz.css do not apply. In my opinion the logo should have a rotating/looping css animation, also styles for the body element doesn't participate in the cascade, despite having a selector for body.

I think it can be reproduced with any webview content linking a stylesheet with the vscode-resource: protocol (I am doing the same/very similar thing, this exception does with linking stylesheets)

Does this issue occur when all extensions are disabled?: Sorry, haven't checked. I don't know how to start extension debugging, without loading other installed extensions. I also haven't checked with the insiders build.

**Comment by mjbvz** [comment]
From https://github.com/mjbvz/vscode-github-markdown-preview-style/issues/40 seems to be cause by custom `files.associations` such as setting:

```json
"files.associations": {
        "*.css": "scss"
    }
```

**Comment by mjbvz** [comment]
@bxantus Please try the next  VS Code insiders build and let me know if you still see this issue. Using your example extension, In confirmed that setting 

```
"files.associations": {
        "*.css": "scss"
    }
```

broke the css.

**Comment by bxantus** [comment]
Thanks for the reply!

Indeed our extension had these lines in package.json, in the languages section:
```
{
	"id": "css",
	"aliases": [
	      "NNG Style Sheet",
	      "nss"
	],
	"extensions": [
		".css",
		".nss"
	]
}
```

This caused the problem (I don't understand why). We wanted to style nss files as css, for every user of the extension. 
But removing the ".css" extension, the problem is solved, even in the standard release.
By leaving the ".css" extension in place the problem is reproducible with the insider build too.

**Comment by sbatten** [comment]
@mjbvz looks like the language contribution section also messes with this as mentioned by @bxantus

**Comment by mjbvz** [comment]
We should just hardcode the common mime for files like js and css. Our built-in mime determination logic is too editor-y for the webview use case.

Too risky for November. Will fix in December

**Comment by octref** [comment]
@bxantus FYI, you should not do that. The correct way is to register `nss` as a language and ask users to use `files.associations` in their workspace to mark *.css files as nss.
