### ISSUE TITLE
Unable to require ibm_db for building an extension

### ISSUE THREAD

**Issue by vysh1986** [Microsoft/vscode#62890]
Hi, I have been trying to build an extension for VS Code that involves communicating to IBM Db2 database.
I was trying to use [ibm_db ](https://github.com/ibmdb/node-ibm_db) module as the driver module. However in my extension code, when i require in the *ibm_db* module, i get this error
![image](https://user-images.githubusercontent.com/36654528/48300385-61e6a180-e502-11e8-8d8f-8fc3048d6aec.png)
Is this because *ibm_db* is a native module?
I tried electron-rebuild to rebuild ibm_db, and after that, i get a different error, which is:

Activating extension 'vashok.hellodb2' failed: The module '\\?\E:\VSCode_extn\hellodb2\node_modules\ibm_db\build\Release\odbc_bindings.node' was compiled against a different Node.js version using
NODE_MODULE_VERSION 50. This version of Node.js requires NODE_MODULE_VERSION 57. Please try re-compiling or re-installing the module (for instance, using `npm rebuild` or `npm install`)..

Could you please help me here? What am i missing here?

- VSCode Version: 1.28.2
- OS Version: Windows 2008 R2 Standard, 64-bit

Steps to Reproduce:

1. Create a sample extension using yeoman generator as outlined in VS Code documentation
2. npm install ibm_db
3. Put the line 'const ibmdb = require('ibm_db') inside your extension.js file
4. Launch the extension and activate it

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by chrmarti** [comment]
We recommend against using native modules because these will only work on a single platform and only for a particular version of Electron (so you need to recompile when we release VS Code with a newer version of Electron).

There is some documentation on compiling a native module for Electron here: https://electronjs.org/docs/tutorial/using-native-node-modules
