### ISSUE TITLE
Install only supported extensions

### ISSUE THREAD

**Issue by spywhere** [Microsoft/vscode#6289]
## Proposal

**Givens:**
- An extension called "Acme" has released 3 versions, each version has developed on the following VSCode version (just for the example)...
  - Acme v1.0.0 on VSCode v0.10.3
  - Acme v1.7.0 on VSCode v0.10.10
  - Acme v2.0.0 on VSCode v1.1.0
- User is using VSCode v1.0.0

**Events:**
User wants to install Acme extension. User open the command palette and search for Acme extension then click Install.

**Expects:**
VSCode should install Acme v1.7.0 instead of Acme v2.0.0 since the Acme extension's developer might use newer API calls that are not exist in VSCode v1.0.0 which can leads to extension crash.

## Potential Solutions
1. Let VSCode query only compatible version of the extensions upon install, update.
2. Allow developers to specify minimum VSCode version on each extension submission (potentially `packages.json`).

**Comment by spywhere** [comment]
Further more, I'm going to file another issue on VSCE repository to suggest the supports for this idea.

**Comment by joaomoreno** [comment]
Note that Code uses [semver](http://semver.org/).

Each version of your extension can have a version restriction under the `engines` field of `package.json`.

In your example, what is under the `engines` field of `Acme v2.0.0`?

**Comment by spywhere** [comment]
That `Acme` extension is just an example I took to make it easier to understand (it is not a reference to real extension version though).

To put it simply of what I wrote, I wonder how VSCode install the extension which has been written with the latest API (let's say this API came out with VSCode 1.1.0) while the user is using an earlier version of VSCode (let's say this user is using VSCode 1.0.0). Do VSCode 1.0.0 install an extension that compatible with itself (the one that wrote without that new API) or it just install the latest one (the one that wrote with that new API)?

Since the latest extension use a new API, I do not know if VSCode that not have a new API yet would crash or not.

Hope it clear things up for you. But if it is not, feels free to ask more. :)

**Comment by joaomoreno** [comment]
Code installs the latest compatible version. This is achieved with [semver ranges](https://github.com/npm/node-semver), specified in the `engines.vscode` field of the extension's `package.json`.

Let me pick up your example. Imagine the following Acme releases:

| Version | `"engines.vscode"` |
|---------|--------------------|
| 1.0.0 | ^0.10.3 |
| 1.7.0 | ^0.10.10 |
| 2.0.0 | ^1.0.0 |
| 2.1.0 | ^1.1.0 |

Code 0.10.10 will install version 1.7.0. Code 1.0.0 will install 2.0.0. Code 1.4.0 will install 2.1.0.
