### ISSUE TITLE
Font rendering on different monitor [macbook pro]

### ISSUE THREAD

**Issue by ant-ia** [Microsoft/vscode#62899]
I connected an external monitor to my macbook. (HP 24w)

On some editors, including vsc, I can not work on the external monitor because the resolution and font rendering is not perfect.

I have attached the two photos below to show the problem.

Can you advise me something?

Thank you.

<img width="284" alt="macbook_retina" src="https://user-images.githubusercontent.com/4062455/48305039-05947980-e524-11e8-96d0-46e9f45e400a.png">

**Comment by ant-ia** [comment]
@chrmarti see this post 
https://stackoverflow.com/questions/53242367/vs-code-font-rendering-on-macbook-pro-retina-with-external-monitor

**Comment by bpasero** [comment]
@ant-ia is this on macOS Mojave?

**Comment by ant-ia** [comment]
Yep. Mojave. Only on 2560x1440 external monitor

**Comment by bpasero** [comment]
@ant-ia does this help: https://code.visualstudio.com/updates/v1_28#_blurriness-on-macos-mojave
