### ISSUE TITLE
ES6 validator doesn't understand static class methods

### ISSUE THREAD

**Issue by AshleyScirra** [Microsoft/vscode#629]
The following code is valid ES6 code:

```javascript
(function ()
{
	class C {
		static Foo()
		{
			console.log("Foo");
		}
	};
})();
```

(jsconfig.json must specify the "ES6" target to understand the class syntax)

VS code underlines "static" in red and says "Modifiers cannot appear here". This is an incorrect error: it is valid ES6 syntax.

Note VS Code does not mark it as an error if the class is not wrapped in an IIFE, but these are typically used for encapsulation.

**Comment by jrieken** [comment]
This comes from the version of TypeScript we are using behind the scenes. Will be fixed once we use project salsa.

**Comment by castlerek** [comment]
+1 the same

**Comment by ronnieoverby** [comment]
+1.

**Comment by jrieken** [comment]
Yes - that Salsa it is

**Comment by jrieken** [comment]
As we now ship with project Salsa this should work.
