### ISSUE TITLE
Wrapping split points for links

### ISSUE THREAD

**Issue by brianmickel** [Microsoft/vscode#62905]
monaco-editor version: 0.X.Y
Browser (environment): VSCode Version 1.28.2 
OS: MacOS
Steps To Reproduce:
1. create a .md doc in vscode
2. add any character and a space to a line eg. `* `
3. add a link to the same line and it'll push the link to start below it then split at the end of that 'subline'

Notes:
* More cosmetic than anything
* It doesn't create an extraneous newline or anything functionally wrong but it splits the link a wrapped line too late

<img width="904" alt="screen shot 2018-10-22 at 10 04 47 pm" src="https://user-images.githubusercontent.com/22584166/47337198-ce7b2880-d647-11e8-9b04-f87192df43ff.png">

**Comment by john-cj** [comment]
Should be quite easy to fix, I assume. Drives me crazy a lot.
