### ISSUE TITLE
Icons are disappearing in activity bar when applied custom themes

### ISSUE THREAD

**Issue by ahmetzeybek** [Microsoft/vscode#62909]
- VSCode Version: 1.28.2
- OS Version:macOS Mojave 10.14

Does this issue occur when all extensions are disabled?: Yes

![screenshot](https://user-images.githubusercontent.com/30319707/48309265-13c7b180-e587-11e8-968f-a7416da682a8.png)

**Update**: `activityBar.foreground` property in `theme-file.json` is blocking icon visibility

**Comment by chrmarti** [comment]
So is `activityBar.foreground` set to a dark grey or something? Would setting `activityBar.background` (or something similar) to a light color help? Is this an issue with the theme?

**Comment by ahmetzeybek** [comment]
> So is `activityBar.foreground` set to a dark grey or something? Would setting `activityBar.background` (or something similar) to a light color help? Is this an issue with the theme?

Just removed `activityBar.foreground` property from `.json` file, I think icons' foreground color based on theme type (`"type": "dark"`)

**Comment by chrmarti** [comment]
Could you check if this is fixed in the latest insiders builds: https://code.visualstudio.com/insiders/ ?

**Comment by ahmetzeybek** [comment]
I don't know how but icons are working properly now in both versions (insiders and stable)

**Comment by ahmetzeybek** [comment]
Same, not working in Insiders too
![screen shot 2018-11-12 at 12 57 59 pm](https://user-images.githubusercontent.com/30319707/48340057-aeed8380-e67a-11e8-88f8-146ed6868cbc.png)
 too

**Comment by ahmetzeybek** [comment]
> Works for me
> @ahmetzeybek
> 
> 1. What color do you set `activityBar.foreground` to?
> 2. Can you also reproduce with all light and dark themes?
> 3. Can you reproduce if you switch off mac os mojave dark mode?
> 
> ![screenshot 2018-11-12 at 11 23 28](https://user-images.githubusercontent.com/1926584/48341471-67142f80-e66d-11e8-8601-925ffe25a0dd.png)

1. I tried with #FFFFFF but didn't work, then tried other colors but same...
2. It is not about dark or light themes
3. Icons are invisible in these themes both dark & light mojave
Quite Light, Solarized Light, Kimbie Dark, Monokai

**I am using Mojave on VMWare 15.4**

**Comment by isidorn** [comment]
Thanks for providing more details. Dup of https://github.com/Microsoft/vscode/issues/57694
