### ISSUE TITLE
Preserve Current Selection when using snippet with TM_SELECTED_TEXT variable

### ISSUE THREAD

**Issue by markusdd** [microsoft/vscode#62907]
Currently snippets with prefixes set become rather useless when they contain the selected text variable.

I have a snippet like this:
```
  "lint_checking": {
    "prefix": "lin",
    "body": [
      "//lint_checking ${1:RULE_ID} off",
      "$TM_SELECTED_TEXT",
      "//lint_checking ${1:RULE_ID} on"
    ],
    "description": "lint pragmas"
  }
```
What I want is being able to select text, start typing lin (which will of course remove the selection) and then IntelliSense will recommend lin as a completion. When I press enter I want the selection to reappear, surrounded by my snippet.

This behavior is actually standard in other editors and I was kind of surprised to find no useful way to use snippets with a completion prefix when the selction variable is being used.

If this is unwanted by some users this should be made configurable as an option, but as a hardware developer I find myself in the situation quite often where this would be useful, as such 'surrounding pragmas' are pretty common.

Another variant would be to make snippets able to be promoted to commands for the Ctrl+Shift+P command palette, so we don't have to go into the insert snippet sub palette. I do not want to assign dedicated Key Bindings, as it just becomes to much. The prefix 'is the keybinding'.

**Comment by jrieken** [comment]
> Another variant would be to make snippets able to be promoted to commands for the Ctrl+Shift+P command palette, so we don't have to go into the insert snippet sub palette. 

You can achieve this via `F1 > Insert Snippet > <snippet>`

> What I want is being able to select text, start typing lin (which will of course remove the selection) and then IntelliSense will recommend lin as a completion. When I press enter I want the selection to reappear, surrounded by my snippet.

Just to clarify - that is typing "over" a selection with a snippet prefix, then selecting that snippet will resolve the TM_SELECTION variable to the typed-over word? Can you attach a gif from another editing doing this?

**Comment by markusdd** [comment]
> You can achieve this via F1 > Insert Snippet > <snippet>

As I stated, this is going through another palette. E.g. in Sublime Text snippets directly register in the Command Palette (Ctrl+shift+P or F1 in this case). Going in the Insert Snippet submenu each time is tedious.

> Just to clarify - that is typing "over" a selection with a snippet prefix, then selecting that snippet will resolve the TM_SELECTION variable to the typed-over word? Can you attach a gif from another editing doing this?

You do not even have to leave VS Code to demonstrate. Just mark a word or sentence and type ".
It automatically encloses the selection in "", although from the 'classic' semantics you would be overriding the selection. What I'm asking for is making this possible for any type of snippet, not just brackets and " " or ' '

**Comment by jrieken** [comment]
Makes sense.

**Comment by ssscassio** [comment]
Any news about this?

**Comment by NickGist** [comment]
Adding this feature would be very nice.
Using F1 > Insert Snippet > is time consuming.
Opening suggestions list by hotkey is not convenient as you need no scroll it to find the snippet, as you can't 'type-to-find' it.
Setting hotkey directly for every usable snippet? We already have too many. Can we use second keyboard to extend?=))

**Comment by jrieken** [comment]
To verify:

* have a snippet that uses `$SELECTION` or `$TM_SELECTED_TEXT`
* select some text
* type the prefix of above snippet and accept the snippet suggestion
* make sure that the old selection is inserted as as variable value
* test with multiple cursors
* test with multi-line selections
