### ISSUE TITLE
Code inside anchor doesn’t indent

### ISSUE THREAD

**Issue by rsgranne** [Microsoft/vscode#62904]
monaco-editor version: 0.X.Y (latest version with VSC 1.28.0; how do I find this out?)
Browser: latest versions of Firefox, Safari, Chrome
OS: latest versions of Windows & macOS
Steps or JS usage snippet reproducing the issue:

I teach college courses, & the following has been true for all of my students, in both macOS & Windows, using the previous & latest versions of VSCode, with & without extensions.

The following code is valid, according to W3C recommendations:

~~~
<a href="foo.html">
  <h3>Title</h3>
  <p>Lorem ipsum</p>
</a>
~~~

However, VSCode doesn’t correctly indent it upon Save. If the code looks like this:

~~~
  <a href="foo.html">
<h3>Title</h3>
    <p>Lorem ipsum</p>
</a>
~~~

Pressing Save does nothing at all in terms of indenting that chunk of code (it acts like `<pre>` in that regard), while all other code everywhere else correctly indents.

**Comment by rsgranne** [comment]
Nope. This is not at all a duplicate. Completely separate issue.

**Comment by alexr00** [comment]
@rsgranne, in the bottom right, is the Language Mode set to HTML? What happens if run the Format Document command?

**Comment by rsgranne** [comment]
Sorry — been sick.

Yes, the Language Mode is set to HTML.

Running the Format Document command does not change/fix anything. The problem persists.

Everything *else* reformats correctly, but not the problematic code I detailed above.

**Comment by alexr00** [comment]
I'm not seeing this reproduce now. Looks like it has been fixed. @rsgranne, let me know if you're still seeing it.

**Comment by rsgranne** [comment]
I’m running the latest VSCode (1.30.0) & I’m still seeing it using the code example above.
