### ISSUE TITLE
File explorer jumps when focusing via keybinding even if the file was visible

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#62901]
Repro:

1. Open a folder with lots of files
2. Expand some folders so it fills the explorer
3. Click a file
4. Press ctrl+shift+e, even though the file is visible, the explorer will be centered on the file which is disorienting

**Comment by isidorn** [comment]
Yes I also dislike this behavior.
fyi @sandy081 I changed that we no longer pass the scroll top property to the tree (check the commit). Please check if this breaks some other behavior you might be reliying on, but I think this fix is proper as it will reduce overall tree scrolling

**Comment by sandy081** [comment]
@isidorn This is mainly used by File explorer I suppose.

**Comment by isidorn** [comment]
Cool, let's just keep our eyes open for regressions.

**Comment by isidorn** [comment]
Might not be fully fixed for november, will be tackled fully via https://github.com/Microsoft/vscode/issues/63406 in december

**Comment by Tyriar** [comment]
The core issue is fixed but still have some issues which I'll comment over on #63406
