### ISSUE TITLE
Broken fuzzy search highlighting/ranking for trimable strings

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#62918]
- VSCode Version: 1.28.2
- OS Version: macOS 10.13.5

~~Fuzzy~~ messy (https://github.com/Microsoft/vscode/issues/34088) search gives wrong highlights and inconsistent rankings when the quickpick entries start with some whitespace characters.

In the following GIF I'll be making two searches, in the first one the entries start with whitespace characters, in the second one they don't, there are some issues:

1. in the first search the wrong characters are highlighted. Notice also how removing the hyphen in `vscode-todo` causes the highlighted characters to go from `vscode-todo` to `vsc` and `ode-` for the `vscode-todo-plus` entry, this isn't happening if the entries don't start with whitespace characters.

2. In the second search you can see how removing the hyphen from `vscode-todo` leads to different rankings. And that hyphens obviously shouldn't matter since all entries have it in the same exact position.

![kapture 2018-11-11 at 14 24 25](https://user-images.githubusercontent.com/1812093/48313512-f235ec80-e5bd-11e8-95df-4c13f02071af.gif)

IMHO the root cause of this is that for some reason proper fuzzy search is still not available everywhere, instead it looks like there are lots of special cases for supposedly improving the ranking. Shouldn't this be fixed sooner rather than later?

**Comment by bpasero** [comment]
I added your issue to our collection (https://github.com/Microsoft/vscode/issues/27317) since you give a good example but I still mark this as duplicate of https://github.com/Microsoft/vscode/issues/34088

I agree we should look into this, but I do not have time currently.
