### ISSUE TITLE
VS Code in MAC OS Mojave in a VM in Parallel Desktop

### ISSUE THREAD

**Issue by AngelValdes** [Microsoft/vscode#62911]
Issue Type: <b>Bug</b>

Use Parallel Desktop 14 in Mojave to create a VM running Mac OS Mojave. So yes, Mojave running in a VM in Mojave. Everthing works great, but when you open VS Code inside the VM, the screen brakes... You dont get to see portions of the screen. All other apps work fine in the VM.

![image](https://user-images.githubusercontent.com/6753973/48309431-017a5300-e548-11e8-9605-42ab932ee82c.png)

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.83GB free)|
|Process Argv||
|Screen Reader|no|
|VM|33%|

</details><details><summary>Extensions (68)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
project-manager|ale|9.1.0
ng-template|Ang|0.1.10
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
bracket-pair-colorizer-2|Coe|0.0.22
supersharp|cra|0.1.4
angular-schematics|cyr|1.9.0
vscode-eslint|dba|1.7.0
netcore-extension-pack|dog|0.7.2
netcore-snippets|dog|0.2.2
gitlens|eam|8.5.6
EditorConfig|Edi|0.12.5
auto-type|eee|0.1.0
tslint|eg2|1.0.40
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.5.1
prettier-vscode|esb|1.7.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
docker-explorer|for|0.1.6
docker-extension-pack|for|0.0.1
dotnet|for|0.0.4
dotnet-test-explorer|for|0.5.5
json2ts|Gre|0.0.6
beautify|Hoo|1.4.7
search-node-modules|jas|1.3.0
csharpextensions|jch|1.3.0
vscode-nuget-package-manager|jmr|1.1.6
angular-essentials|joh|0.4.0
Angular2|joh|7.0.1
vscode-csharp-snippets|jor|0.3.1
docomment|k--|0.1.2
chat|kar|0.7.4
csharpfixformat|Leo|0.0.76
ts-extension-pack|loi|0.1.0
Angular-BeastCode|Mik|7.0.14
vscode-azureappservice|ms-|0.9.1
vscode-azurefunctions|ms-|0.12.0
vscode-azurestorage|ms-|0.4.2
vscode-cosmosdb|ms-|0.8.0
mssql|ms-|1.4.0
azure-account|ms-|0.6.0
azurecli|ms-|0.4.2
csharp|ms-|1.17.0
vscode-node-azure-pack|ms-|0.0.4
vsliveshare|ms-|0.3.925
vsliveshare-audio|ms-|0.1.39
vsliveshare-pack|ms-|0.2.0
azurerm-vscode-tools|msa|0.4.2
debugger-for-chrome|msj|4.11.0
angular2-inline|nat|0.0.17
vscode-docker|Pet|0.3.1
vscode-gitignore-generator|pio|1.0.1
material-icon-theme|PKi|3.6.0
tsimporter|pmn|1.2.14
polacode|pnp|0.2.2
quicktype|qui|12.0.46
typescript-hero|rbb|3.0.0
aspnet-helper|sch|0.6.4
autoimport|ste|1.5.3
move-ts|str|1.11.3
msbuild-project-tools|tin|0.2.42
nodejs-extension-pack|wad|0.1.9
vscode-import-cost|wix|2.9.0
JavaScriptSnippets|xab|1.7.1
licenser|ymo|1.3.1

(2 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/45498d93166483c2eff886e28f8dab915ae382fc/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/code-exploration_1.28.0-1538127308_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/VSCodeUserSetup-x64-1.28.0-exploration.exe)
