### ISSUE TITLE
Terminal tasks cannot be processed by problemMatcher

### ISSUE THREAD

**Issue by ncannasse** [Microsoft/vscode#62914]
Build tasks are using the builtin terminal, but he problemMatcher is not able to cope with terminal width.

See for instance the following terminal output:

![image](https://user-images.githubusercontent.com/1022912/48312008-9ad95180-e5a8-11e8-9df8-60f203fd46a2.png)

Because the error has more than (terminal width) characters, the problem matcher is only able to process the first line and not the others, resulting in the following cutout error in *Problems*:

![image](https://user-images.githubusercontent.com/1022912/48312017-c0fef180-e5a8-11e8-8c1e-6c0b6f5c7614.png)

It's not practical to have compiler error messages limited by the Terminal Window Width. It's even more problematic since unless you navigate to the Terminal tab it will keep its original 80 width, resulting in even more cutout error messages.

**Comment by chrmarti** [comment]
Which problem matcher are you using? Is this an issue with the Haxe extension?

**Comment by ncannasse** [comment]
Yes this is the problem matcher used:
```
{
	"name": "haxe",
	"regexp": "^(.+):(\\d+): (?:lines \\d+-(\\d+)|character(?:s (\\d+)-| )(\\d+)) : (?:(Warning) : )?(.*)$",
	"file": 1,
	"line": 2,
	"endLine": 3,
	"column": 4,
	"endColumn": 5,
	"severity": 6,
	"message": 7
}
```

(you can see the whole package definition here https://github.com/vshaxe/vshaxe/blob/master/package.json)

The problem is that tasks are using a terminal with a specific width, so errors get newlines inserted (at least on Windows) when the max width is reached.

**Comment by ncannasse** [comment]
Please note that the problem is not specific to Haxe extension. All problemMatchers should be affected the same.

**Comment by dbaeumer** [comment]
Actually this is a dup of https://github.com/Microsoft/vscode/issues/43664. There are only some cases where some of the info on the next line is not covered. For all the details see 43664.
