### ISSUE TITLE
New OS explorer icons not showing up as shown in release notes in FE

### ISSUE THREAD

**Issue by AgentAzure** [Microsoft/vscode#62912]
Issue Type: <b>Bug</b>

So, I don't know If I'm using this wrong, and I'm also an alien to reporting issues here, so please cut me some slack here and tell me if I'm doing something wrong here. Anyway, I updated VS code to latest version, restarted pc, checked the file icons on large / medium image size [file types checked: js, py, rb] and they still showed up as the default vscode file icon. [page with lines on it and vscode logo in corner] I don't know what's gone wrong here, but I still wanna have these new icons.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.87GB (10.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
solargraph|cas|0.17.6
vscode-eslint|dba|1.7.0
python|ms-|2018.10.1
sublime-keybindings|ms-|4.0.0
vsliveshare|ms-|0.3.925
ruby|reb|0.20.0
LiveServer|rit|5.1.1
JavaScriptSnippets|xab|1.7.1

</details>

**Comment by chrmarti** [comment]
Check which file icon theme you have set (Ctrl + Shift + P and search for 'file icon').

**Comment by AgentAzure** [comment]
I'm using Seti Icons

**Comment by chrmarti** [comment]
Could you try the insiders build and see if it is still a problem there? (https://code.visualstudio.com/insiders/) If it is, could you attach a screenshot?

**Comment by AgentAzure** [comment]
I'll check that out.

**Comment by AgentAzure** [comment]
Do I have to uninstall my current installation?

**Comment by chrmarti** [comment]
No, you can install the two side-by-side. Insiders comes with a green icon to distinguish it from the stable release.

**Comment by AgentAzure** [comment]
![image](https://user-images.githubusercontent.com/43924875/48339202-998c4f80-e6a2-11e8-8e82-fe2de6e48ba4.png)
Works in insider's build, thanks for the continued help btw.

**Comment by chrmarti** [comment]
Thanks for confirming!

**Comment by AgentAzure** [comment]
Any way to get it working in stable ver?

**Comment by AgentAzure** [comment]
Is it normal for the small icons to also be type specific? 
![image](https://user-images.githubusercontent.com/43924875/48339668-b37a6200-e6a3-11e8-896b-e6b819ad2412.png)

**Comment by chrmarti** [comment]
We will release a new stable version in the coming days. That will be identical to the current insiders build (plus maybe some bug fixes).

**Comment by AgentAzure** [comment]
ok

**Comment by AgentAzure** [comment]
I am really very sorry for bothering you all with this, may be something to look into though!

**Comment by chrmarti** [comment]
That's expected behavior from what I see then. Thanks.

**Comment by AgentAzure** [comment]
Oh! Thanks for clearing that up!
