### ISSUE TITLE
load time for TypeScript and JavaScript files is too much 

### ISSUE THREAD

**Issue by Oluwasetemi** [Microsoft/vscode#62916]
- Extension Name: typescript-language-features
- Extension Version: 1.0.0
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.28.2

 We have written the needed data into your clipboard. Please paste:
```json 
{
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 757,
		"activateCallTime": 1209,
		"activateResolvedTime": 0,
		"activationEvent": "onLanguage:javascript"
	}
}
```

**Comment by mjbvz** [comment]
What is going wrong? That pasted logs indicate a time of one second

**Comment by Oluwasetemi** [comment]
![image](https://user-images.githubusercontent.com/10030028/48666957-4106e900-eacc-11e8-9a4f-9fda7903d279.png)
This is a shot of my task manager on windows. I can't run 2 instance of vscode.

i am tired of the heavy lag. i used to enjoy vscode but now it very difficult for my to get my job done very easily.

**Comment by mjbvz** [comment]
Please take a look at our [issue reporting guide](https://aka.ms/vscodeissuereporting) and provide the necessary information to investigate this. There's a section on perf issues too: https://github.com/Microsoft/vscode/wiki/Performance-Issues
