### ISSUE TITLE
Copying content when deleting it

### ISSUE THREAD

**Issue by MustafaHi** [Microsoft/vscode#62923]
Issue Type: <b>Bug</b>

code is copying text when deleting it with backspace.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (4 x 3498)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (2.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.60
theme-karyfoundation-themes|kar|18.2.1
LiveServer|rit|5.1.1

(1 theme extensions excluded)

</details>

**Comment by chrmarti** [comment]
/needsMoreInfo

Do you have any customizations with your keybindings? Does it reproduce with the insiders build? (https://code.visualstudio.com/insiders/)

**Comment by MustafaHi** [comment]
Yes, I looked into it and realized its cut not just delete, sorry about that.
