### ISSUE TITLE
macOS: Wrong space focused when having multiple fullscreen windows

### ISSUE THREAD

**Issue by ZachariahRosenberg** [microsoft/vscode#62920]
- VSCode Version: 1.28.2
- OS Version: OSX 10.14.1

Steps to Reproduce:

1. Put VS Code in Full-Screen Mode (cmd+shift+f on mac)
2. Toggle breakpoint in the code
3. Select "Start Debugging"
      2b. Option "Python: Current File (Integrated Terminal)
4. Run Code

Does this issue occur when all extensions are disabled?: **Yes**

The following screen capture shows the switch. This switch is triggered automatically and happens on every break point.

Thanks!

![ezgif-1-b113c371bb7b](https://user-images.githubusercontent.com/6923376/48315793-b80e2000-e5a8-11e8-9a4e-961b8f322ba1.gif)

**Comment by isidorn** [comment]
Yes, this is by design. Every tim the breakpoint is hit we focus the window.
If more users ask for this we could make it configurable.

**Comment by ZachariahRosenberg** [comment]
@isidorn focusing to the vs code window on breakpoint is fine. The issue shown in the GIF is that the focus is taken _off screen_ upon breakpoint.

To clarify, I am currently full screen focused on vs code. I have the debugger running. Break point is hit and my screen switches to my desktop (and away from VS Code).

I see now that my GIF is not clear which way it is shifting. On breakpoint, the screen switches to my desktop, away from VS code. I believe the feature is that it would switch **to** vs code. Is that correct?

**Comment by isidorn** [comment]
@ZachariahRosenberg ok got it. So the issue is that `this.windowService.focusWindow()` seems to focuses the wrong OS X space. Forwarding to @bpasero since this sounds like an Electron issue.

**Comment by bpasero** [comment]
@ZachariahRosenberg how about configuring to use simple fullscreen support that we just added via setting: `window.nativeFullScreen: false`

**Comment by bpasero** [comment]
Actually disregard my last comment, I have seen issues with simple fullscreen that are big enough that I am thinking of removing that feature from VSCode.

**Comment by dmidnight** [comment]
Still seeing this issue as of today
