### ISSUE TITLE
Can we ban the IME when the editor is read only

### ISSUE THREAD

**Issue by jddxf** [microsoft/vscode#62938]
monaco-editor version: 0.14.6
Browser: Chrome
OS: OSX
Steps or JS usage snippet reproducing the issue:
![image](https://user-images.githubusercontent.com/11155177/47206033-403e4280-d3ba-11e8-89a0-ec2690aed35c.png)
It would be nice if IME wouldn't show when the editor is read only.

**Comment by alexandrudima** [comment]
We now mark the editor as read-only on the web (https://github.com/microsoft/vscode/pull/81394).
