### ISSUE TITLE
disable sound error on key shortcut

### ISSUE THREAD

**Issue by andy-dev** [Microsoft/vscode#6293]
- VSCode Version:1.1.0
- OS Version: 10.11.4 

Steps to Reproduce:

1. create new shortcut(make it the same as a previous editor)
  {
        "key": "ctrl+cmd+down",
        "command": "editor.action.moveLinesDownAction",
        "when": "editorTextFocus"
    },
2. IT works but makes sound

I only sounds on down not on up.

Thanks in advance,

A

**Comment by Tyriar** [comment]
@andy-dev this on Windows?

**Comment by andy-dev** [comment]
@tyriar no, mac osx yosemite 10.11.14

**Comment by alexandrudima** [comment]
@andy-dev We don't play any sounds. Maybe the OS is doing this? Does this sound occur when you are in other programs and press the same key combo?

**Comment by alexandrudima** [comment]
Closing after a number of days without a reply.
