### ISSUE TITLE
save as... pop up window

### ISSUE THREAD

**Issue by rezan83** [Microsoft/vscode#62934]
![vscsaveas](https://user-images.githubusercontent.com/12866632/48329958-36230300-e64b-11e8-834e-ff66ce0140b2.png)
Issue Type: <b>Bug</b>

ubuntu.. when making new file and then 'save as' to give it a name and extension, the pop-up window doesn't give save option!! its just a file navigation window

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:20:56.183Z)
OS version: Linux x64 4.15.0-38-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2681)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|2, 2, 2|
|Memory (System)|7.69GB (0.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.60
jshint|dba|0.10.20
vscode-eslint|dba|1.7.0
prettier-vscode|esb|1.7.2
code-runner|for|0.9.5
beautify|Hoo|1.4.7
vscode-language-babel|mgm|0.0.21
python|ms-|2018.10.1
ruby|reb|0.20.0
LiveServer|rit|5.1.1
bootstrap4-vscode|the|4.3.0
JavaScriptSnippets|xab|1.7.1
ReactSnippets|xab|2.2.1
html-css-class-completion|Zig|1.17.1

</details>

**Comment by chrmarti** [comment]
Your 'Save As' dialog shows a transparent titlebar. You can see 'Cancel' and 'Save' buttons top left and right. Could you try a different Ubuntu color theme to see if that affects it? (I'm not sure we have any control over this.)

**Comment by chrmarti** [comment]
No worries. Do you have transparent titlebars in other applications too?

**Comment by rezan83** [comment]
i don't think I've seen it in other applications.. see LibreOffice save as
window in attachments

**Comment by bpasero** [comment]
Looks like nothing that is under our control, closing.
