### ISSUE TITLE
Allow resize explorer pane and terminal pane to arbitrary width

### ISSUE THREAD

**Issue by schrodog** [microsoft/vscode#62931]
When you reduce width of explorer pane to certain minimum, it will collapse and hide the pane. But that minimum width is too large for me, there's a huge gap between filename and edge, wasting a lot of space. I rather prefer to be able to resize to any width without sudden collapse. Same request goes for terminal pane on the right/bottom.

![pane](https://user-images.githubusercontent.com/16360247/48323732-8bb9d880-e668-11e8-8ea3-bb91fb43e708.png)

**Comment by schrodog** [comment]
Any follow up / comment on this request?

**Comment by isidorn** [comment]
Panel can now be resized to max width. Sidebar can not and we will not change that
