### ISSUE TITLE
problemMatcher reports ordering

### ISSUE THREAD

**Issue by ncannasse** [microsoft/vscode#62942]
ATM a problemMatcher will report issues grouped by file, and for each file will sort the issues based on line/column.

However some compilers can report issues in unordered ways, such as:

```
file.c:55: error xxxxx
file.c:33: see definition here
```

In that case, current handling will report something like this in `Problems` tab:

```
(file.c)
    |- see definition here (33)
    |- error xxxx
```

Whereas we would prefer to keep the compiler original order.

Feature request: add the ability for a problemMatcher to set `keepOrder : true` that will:
* keep ordering for errors within the same file
* keep ordering of files (first reported files gets listed first in Problems)

**Comment by ncannasse** [comment]
My implementation suggestion would be to:

a) add a new priority:Int (default 0) to problems view items. sort them by priority first, then current sorting. this should not affect anything

b) enable the problemMatcher to emit "priority", where each problem reported gets assigned a decreasing priority (0, -1, -2 etc.)

**Comment by dbaeumer** [comment]
I am not a fan of given clients such fine controlled ordering since it will lead to an inconsistent user interface. However I can see the need to boost some types of errors like missing dependencies to showup first since fixing other errors makes no sense if for example you are missing a library.

@ncannasse for you specific case you want to emit related information for a diagnostic which is possible in the API but currently not with a problem matcher. We have an item for this: https://github.com/Microsoft/vscode/issues/55253

So I am actually leaning towards closing this as a dup of #55253. Objections?

**Comment by ncannasse** [comment]
@dbaeumer my suggestion is not to given "clients" the ordering control, it's just a flag to tell whereas the compiler output order should be taken into account or not. 

I'm not familiar enough with the differences between diagnostics and problem matcher output to comment on whereas this would be the best solution or would instead introduce some additional issues compared to current workflow. Also, that does not seem to answer the issue if the diagnostics are ordered the same way the reported problems are.

**Comment by dbaeumer** [comment]
The case you are provided are not two distinct errors. It is one error 
`file.c:55: error xxxxx` with a related information about `file.c:33: see definition here`. This is typically the case if for example a var is readonly and someone tries to write it. These kind of related information shoundn't produce its own diagnostic. There should be one saying `file.c:55: error xxxxx` with a child saying `file.c:33: see definition here`. In this case only one error on line 55 would be rendered in the problems view wiht a child node for line 33.

With client I mean users of our API. If we add something we must allow extensions to do the same and then problems generated by extension A are rendered in different order than problems generated by extension B.

**Comment by ncannasse** [comment]
@dbaeumer I agree these are "related errors", but I'm not sure how we could be able to group them using problemMatcher to have it as a child node.

Also, some errors might be unrelated, but the second might be the consequence of the first.
For example:

```
MyClass:55: unknown type Srting for member variable foo
A.hx:66: MyClass has no field foo
```

Using problemMatcher, files will be sorted using alphabetic order, so you will get first the `A.hx` error before the `MyClass.hx`, while we would expect again here to respect the compiler error ordering.

In C that could also be something like this:

```
file.h(55): can't open include file <files.h>
file.c(66): unreferenced identifier open_file
```

Again, the `.c` error would be displayed before the `.h`

**Comment by dbaeumer** [comment]
I see your point but I would find it way more confusing if the problems are not grouped by files. Usually if I look at the problems view and expand a file node I expect to see all errors in that file. With our argument that would not be the case anymore.

**Comment by ncannasse** [comment]
I'm not proposing that they are not grouped by file, I'm proposing that the
files are ordered by output of the compiler, and the errors within the same
file as well. That should already cover most of the cases.

**Comment by ncannasse** [comment]
Up for this discussion

Today I got the following terminal output:
```
src/ui/BaseUI.hx:65: characters 52-54 : Icon should be IconKind
src/ui/BaseUI.hx:65: characters 52-54 : For function argument 'i'
src/ui/BaseUI.hx:65: characters 31-55 : Void should be h2d.Tile
```

Which resulted in the following Problems view:

![image](https://user-images.githubusercontent.com/1022912/64607439-d14e4b80-d3c8-11e9-912a-5ee4787c42e7.png)

As you can see, the error reporting is completely messed up as the result of:
- error line 2 overriding error line 1 and making it disappear (?) because same position
- error line 3 begin reordered in Problems before error line 2

I really wish we had either a programmatic way to create and order Problems on compilation tasks, or some more control on the output (see JSON output suggestion in https://github.com/microsoft/vscode/issues/9635#issuecomment-523377704) and related issue #55253

**Comment by alexr00** [comment]
I think that this would be solved by programatic problem matching: https://github.com/microsoft/vscode/issues/59337
Feel free to ping this issue if that's not the case!
