### ISSUE TITLE
Intellisense tooltips is cut off code area

### ISSUE THREAD

**Issue by Xarkam** [microsoft/vscode#62947]
Hello,
I just noticed that intellisense tooltips are cut off if an error is present on the first line.

In addition, the controls of the window are present in it (see the screenshot)

![image](https://user-images.githubusercontent.com/331816/48348904-f972fe00-e682-11e8-8ce5-3d650be74ec4.png)

If I collapse the first zone, the tooltips show below closing }
![image](https://user-images.githubusercontent.com/331816/48349043-5e2e5880-e683-11e8-9fc2-729449d8efcd.png)

**Comment by misolori** [comment]
@joaomoreno this sounds like a hover bug? who should I assign this to?
