### ISSUE TITLE
Multi-line strings are not handled properly for brace matching and code folding

### ISSUE THREAD

**Issue by adrianth** [Microsoft/vscode#6294]
- VSCode Version: 1.1.0
- OS Version: Win 8.1

Problem: Multi-line strings are not handled properly for brace matching and code folding.

Steps to Reproduce:

1) Open a JavaScript file and  put the following content in it:
```
var obj = {
	property: "line1\
line2\
line3\"
}
```
2) Place the cursor near the opening or closing brace to activate the brace matching.
3) Click the "minus sign" icon to fold the object declaration. Lines two and three of the object declaration remain visible.

**Comment by Tyriar** [comment]
Folding is currently indent-based, the issue tracking folding knowing about languages is https://github.com/Microsoft/vscode/issues/3422, please :+1: the issue to indicate you want it.
