### ISSUE TITLE
Terminal don' show characters at start. 

### ISSUE THREAD

**Issue by daniel-dia** [Microsoft/vscode#62946]
Issue Type: <b>Bug</b>

Just open the terminal A "blank" area is show.  The information is there, but it's not visible. 

Typing "clear" refreshes the terminal and the characters will be visible.

I tried with a fresh install, as the screenshot below

![anotacao](https://user-images.githubusercontent.com/2263037/48348121-84de9600-e667-11e8-9834-5efc59524d5f.png)

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (6.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.17.0

</details>

**Comment by hsulm-traub** [comment]
I have the same problem. When you start terminal panel in maximized mode, the problem is gone.

**Comment by Stefan-jw** [comment]
Me too. Switching to dom render does not help.

**Comment by romanoledergerber** [comment]
Same Issue on Versin 1.29.1

**Comment by Stefan-jw** [comment]
I can confirm, it is a Windows 1809 problem.

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/57803
