### ISSUE TITLE
Allow to set filename but not path when opening with openTextDocument

### ISSUE THREAD

**Issue by FredrikFolkesson** [microsoft/vscode#62940]
Hi!

Is there a possibility to add the wanted filename (not path) when using `openTextDocument`

something like:

```
openTextDocument({ language: 'js', content: script, name: my-app.js });
```

I see that something similar has been referenced here: #12283

What I want is my filename instead of `Untitled-1` but still get the save file dialog when attempting to save.

I could do this:

```
    var setting = Uri.parse("untitled:" + scriptFileName);
    workspace.openTextDocument(setting).then((a) => {
      window.showTextDocument(a, 1, false).then(e => {
        e.edit(edit => {
          edit.insert(new Position(0, 0), scriptContent);
        });
      });
    }, (error) => {
      console.error(error);
      debugger;
    });
```
But then it does not prompt the save file dialog but instead tries to save the file at `/scriptfileName` which is not what I want.

I want an "unsaved" file with a specified filename (but not the path) and content where the user when attempting to save gets the save file dialog (with the specified filename as default, preferably in the open workspace as default)

I hope you understand what I mean

**Comment by bpasero** [comment]
Currently not possible.

/cc @jrieken
