### ISSUE TITLE
Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:22172).

### ISSUE THREAD

**Issue by danielgalleni** [Microsoft/vscode#62944]
- VSCode Version: 1.28.0
- OS Version: macOS Majave 10.14

Steps to Reproduce:

1. Start debugging;
2. Stop or restart debugging.

Does this issue occur when all extensions are disabled?: Yes

I use the following setup:
```js
{
  // Use IntelliSense to learn about possible Node.js debug attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "program": "${workspaceRoot}/src/lib/server.js",
      "outFiles": [
        "${workspaceRoot}/bin/**/*.js"
      ],
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/babel-node",
      "smartStep": true,
      "envFile": "${workspaceRoot}/.env",
      "restart": true,
      "outputCapture": "std"
    },
    {
      "type": "node",
      "request": "attach",
      "name": "Attach to Process",
      "address": "localhost",
      "port": 5858
    },
    {
      "type": "node",
      "request": "launch",
      "name": "Test",
      "program": "${workspaceFolder}/node_modules/mocha/bin/_mocha",
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/babel-node",
      "args": [
        "--timeout",
        "1000000",
        "--bail",
        "${file}"
      ],
      "smartStep": true,
      "restart": false,
      "envFile": "${workspaceFolder}/.env.hmg",
      "outputCapture": "std"
  },
  ]
}
```

I have the problem, only in the "Launch Program". When I debug tests, this problem does not occur.

I already updated vscode, but it did not work. I've also tried some settings available on other similar issues.

Usage node v8.11.1.

**Comment by danielgalleni** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
>     * [Very slow debugger launching, with errors (#36821)](https://www.github.com/Microsoft/vscode/issues/36821)

I checked, but not this problem I have.

**Comment by roblourens** [comment]
Does it happen every time? This implies that there's something else running on that port, or that node failed to start in debug mode.

**Comment by danielgalleni** [comment]
Yes, it happens every time. If I debug, it works.
The problem occurs when I try to restart the debugging or stop.
I always need to wait to give the error message, then yes the previous process kills and starts manually, I can debug again.
It's like trying to start a new process, with the other still running.
<img width="810" alt="image" src="https://user-images.githubusercontent.com/21322510/48366082-ed436c80-e693-11e8-8c24-46133b8b3f98.png">
<img width="815" alt="image" src="https://user-images.githubusercontent.com/21322510/48366242-5aef9880-e694-11e8-8df3-9a2270bc3f68.png">
<img width="814" alt="image" src="https://user-images.githubusercontent.com/21322510/48366142-15cb6680-e694-11e8-8080-eb77115952f2.png">
In the examples above, I just started debugging, and then clicked on the restart button. You already have the error message.

**Comment by roblourens** [comment]
Can you tell me whether this is still an issue in 1.29?

**Comment by danielgalleni** [comment]
It worked perfectly in version 1.29.0.
Thanks for the support.
