### ISSUE TITLE
File emptied/content deleted intermittently on save.

### ISSUE THREAD

**Issue by hanvyj** [Microsoft/vscode#62948]
I've just installed VS Code and I've noticed it intermittently deletes all of a file's content on save. I've seen people have this issue with extensions, but I am running with `code --disable-extensions`:

![savecontentdelete](https://user-images.githubusercontent.com/20140222/48352282-486d6300-e684-11e8-8e90-78d33eb40646.gif)

I can consistently reproduce it by simply 'ctrl-s' a few times. I'm guessing it must be something related to my particular setup though, but as I said, it's just been installed on this machine so everything should be pretty default.

Auto save is off.

Version: 1.28.2 (user setup)
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:23:51.859Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Also noticed, and may be related, getting an ocasional:

> Failed to save 'Alert.ts': A system error occurred (EBUSY: resource busy or locked, open '...\Alert.ts')

Then I can't save because the open (with existing content) file is:

> Failed to save 'Alert.ts': The content on disk is newer. Please compare your version with the one on disk.

On comparing with the version on disk - it's empty!

**Comment by chrmarti** [comment]
Do you have anything running in the background that might access the file? Some build tool maybe? EBUSY indicates that something else is holding on to the file at that moment.

**Comment by hanvyj** [comment]
The test example was in a new "project" (well, a new folder in Documents) with just two files. There are no other build processing or tooling running on it, it's just a folder with a text file in. I've also experienced on random config files I was editing, so I'm pretty sure its not something else holding the file.

It's a new work machine so I'm not sure what they've installed on it, but I doubt there'd be anything holding file handles open for random text files?

Can you think of a suggested test? I'd expect to see similar behaviour in another text editor?

**Comment by chrmarti** [comment]
Looks like https://github.com/Microsoft/vscode/issues/61310. Could retry with the released VS Code 1.29.0?

**Comment by isidorn** [comment]
Yeah closing as duplicate.
@hanvyj if you can repro with latest vscode let us know and I will reopen. Thanks
