### ISSUE TITLE
The terminal process command 'C:\WINDOWS\System32\cmd.exe' failed to launch (exit code: 2)

### ISSUE THREAD

**Issue by SmallLuma** [Microsoft/vscode#62953]
- VSCode Version:
Version: 1.28.2 (system setup)
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:23:51.859Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

- OS Version:10.0.17134.345

Steps to Reproduce:

1. Open VSCode
2. Open a folder
3. Ctrl + Shift + `
4. Error Message:The terminal process command 'C:\WINDOWS\System32\cmd.exe' failed to launch (exit code: 2) 

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Are you on a locked down machine? You should also try the user installer instead of the system installer https://code.visualstudio.com/Download

**Comment by SmallLuma** [comment]
> 
> 
> Are you on a locked down machine? You should also try the user installer instead of the system installer https://code.visualstudio.com/Download

I has installed VSCode with user installer,but terminal not works too.

Message:
The terminal process command 'C:\Windows\System32\cmd.exe' failed to launch (exit code: 2)

**Comment by Tyriar** [comment]
is this a personal machine or managed by your organization?

**Comment by SmallLuma** [comment]
> is this a personal machine or managed by your organization?

Yes,it is my personal machine.

**Comment by SmallLuma** [comment]
> 
> 
> Does it work when you switch to powershell? https://code.visualstudio.com/docs/editor/integrated-terminal#_windows

The terminal process command 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' failed to launch (exit code: 2)

**Comment by Tyriar** [comment]
I'm a bit stumped on this one, hopefully it will be fixed by changing the way we create the process which will likely land in 1.31 https://github.com/Microsoft/vscode/issues/45693

**Comment by SmallLuma** [comment]
Thanks.

**Comment by faridrafati** [comment]
Just remove deleted files from your work space in vs code it works for me

**Comment by faridrafati** [comment]
> Thanks.

Just remove deleted files from your work space in vs code it works for me
