### ISSUE TITLE
Auto closing single quote is wearing out my delete key

### ISSUE THREAD

**Issue by archer884** [Microsoft/vscode#6295]
- VSCode Version: 1.1.0
- OS Version: Windows 7

Steps to Reproduce:
1. Open a rust source file and type `'`
2. Watch the editor add a second `'` even though there is almost zero chance you want one

I really want to turn this off, but I don't want to lose auto brackets. Please tell me there's some way to kill this, or that you'll put one in. :)

**Comment by alexandrudima** [comment]
@archer884 
I agree that the set of auto-closing characters should be configurable, sometime the quotes are annoying me as well.

In the short term, maybe this is a bug in the Rust configuration we ship with? [https://github.com/Microsoft/vscode/blob/master/extensions/rust/rust.configuration.json] - I am sorry I don't know Rust's syntax.

**Comment by zummenix** [comment]
Starting from vscode 1.2.0 "Suppress auto-closing of ' for rust" works. I think the issue can be closed.

**Comment by gitgrimbo** [comment]
Can we have the ability to turn off **all** auto-quote features?
