### ISSUE TITLE
VSCode Hangs, Losing Work. 

### ISSUE THREAD

**Issue by MattGrdinic** [Microsoft/vscode#62955]
Issue Type: <b>Bug</b>

I have a "somewhat" large PHP/HTML project, hundreds of files, etc. When typing in a mixed PHP/HTML document the editor will, very consistently, hang. The entire applicaiton becomes unresponsive until a modal popus up saying I can close the editor, etc. When I do, all work since the last save is gone. So far as I can tell this doesn't happen in "pure" code files, just mixed HTML/PHP ones. Also, the bug reporter URL from VSCode was broken, logging into GitHub first seemed to fix the issue. 

Any questions please let me know!

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|24.00GB (14.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.2.0
vscode-intelephense-client|bme|0.8.8
gitlens|eam|8.5.6
php-debug|fel|1.12.6
vscode-icon-theme|jtl|1.6.5
vscode-icons|rob|7.28.0

(1 theme extensions excluded)

</details>

**Comment by chrmarti** [comment]
Please check https://github.com/Microsoft/vscode/wiki/Performance-Issues. Is this still an issue with the upcoming 1.29 release?

**Comment by rkeithhill** [comment]
I'm seeing the same thing but on 1.29.0.  Although I was seeing this occasionally on 1.28.2 as well.
