### ISSUE TITLE
Sluggish for no apparent reason.

### ISSUE THREAD

**Issue by sburgett** [Microsoft/vscode#62954]
Issue Type: <b>Performance Issue</b>

Everything in Visual Studio Code is sluggish.  Switching editors by clicking a tab takes 1.5 to 2 seconds.  Scrolling is sluggish.  Drag-selecting text lags behind the mouse by 1/2 second, and catches up in slow motion.  Typing lags by 1/2 second, etc.  Other running applications are behaving normally.

To troubleshoot this, I have built a fresh Windows 10 virtual machine.  All VSCode extensions are disabled.  The only applications I am running are a PowerShell window with the node development server, several Edge windows (one with the application I am writting), and VSCode.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (6 x 2794)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.98GB (1.94GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    67	 10300	code main
    1	   181	  2092	   gpu-process
    0	   226	  2872	   window (● bubbleChartD3.js - disruptive (Workspace) - Visual Studio Code)
    0	    68	  7084	     extensionHost
    0	   261	 14400	       electron_node tsserver.js 
    0	    47	  8580	         electron_node typingsInstaller.js typesMap.js 
    0	    42	 10208	     watcherService
    0	    67	  8488	   shared-process
    0	    66	 16212	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● bubbleChartD3.js - disruptive (Workspace) - Visual Studio Code)
|    Folder (disruptive): 161 files
|      File types: js(36) zip(24) css(22) ttf(19) json(13) otf(10) map(4)
|                  png(4) html(4) xlsx(4)
|      Conf files: package.json(1) launch.json(1) tasks.json(1)
|      Launch Configs: chrome(2) firefox(2) edge;
```

</details>
Extensions: none

**Comment by chrmarti** [comment]
Please check if this is still an issue with the upcoming 1.29 release.

**Comment by rightaway** [comment]
Same for me on linux with 1.29 and 1.28 (possibly even a little earlier than that too). Scrolling and moving the mouse cursor and typing are very slow, a very noticeable lag.

**Comment by rightaway** [comment]
The `window` process in Process Explorer shows 20% CPU usage when I'm just scrolling up and down in a normal file. None of the extensions are showing high CPU usage and the issue remains when I disable all extensions.

**Comment by jrieken** [comment]
please follow this guide: https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by sburgett** [comment]
Yes, it is still an issue in 1.29.1.

**More information:**
With all extensions disabled, I slowly scrolled up and down in one file for 20 or 30 seconds, then clicked a tab to switch to a different file.  During this time my fans were going faster and faster, and Windows Task Manager reported that VSCode had "very high" power usage (see screen shot). 

At other times, my fans will spin up as I start using VSCode, but Task Manager reports single-digit CPU percentages for it.  I'm wondering if the GPU (NVIDIA GeForce GT 750M) is heating up and throttling.

<img width="958" alt="screen shot 2018-11-20 at 11 49 22 am 2" src="https://user-images.githubusercontent.com/1622131/48799076-1af36b80-ecbb-11e8-9c6b-a8594e7df636.png">

**Comment by jrieken** [comment]
please follow this guide: https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by sburgett** [comment]
Here is the output from 'code --status' and a CPU profile.  All extensions were disabled, and settings were empty.

[code-status.txt](https://github.com/Microsoft/vscode/files/2605164/code-status.txt)


[CPU-20181121T091242.cpuprofile.txt](https://github.com/Microsoft/vscode/files/2605167/CPU-20181121T091242.cpuprofile.txt)

**Comment by jrieken** [comment]
Hard to make a call here, there is nothing that stands out as single big thing. However, the trace-calls look fishy. On typing [this runs](https://github.com/Microsoft/vscode/blob/6dcade9ed5f05c913abba28d8f4f44cc1cc3655c/src/vs/workbench/services/textfile/common/textFileEditorModel.ts#L499) which also add some trace-logging and those calls take to much time

<img width="815" alt="screenshot 2018-11-22 at 09 11 24" src="https://user-images.githubusercontent.com/1794099/48889637-cecd3600-ee36-11e8-80e8-9cd969d460e2.png">

@sburgett What log level are you running with?

**Comment by sburgett** [comment]
Do you mean in Developer Tools?  I haven't changed anything from the out-of-the-box state.  It appears to be {Info, Warnings, Errors}:

<img width="161" alt="screen shot 2018-11-23 at 9 13 49 am" src="https://user-images.githubusercontent.com/1622131/48954951-6d719980-ef00-11e8-9862-def060ce4f7b.png">

**Comment by jrieken** [comment]
closing because no actionable information is present
