### ISSUE TITLE
`Toggle Tab Visibility` keybind is too similar to `Close File` keybind

### ISSUE THREAD

**Issue by alekseyt** [Microsoft/vscode#62959]
Per comments in #60583 i'm opening another issue. I think this issue type is enhancement, but it looks like a bug, honestly.

Description: https://github.com/Microsoft/vscode/issues/60583#issuecomment-437408352

(Supposedly) Steps to Reproduce:

1. Press `Ctrl+W` to close file
2. Unintentionally press `Super` key too

Actual result 1: tabs in editor disappears
Actual result 2: `workbench.editor.showTabs` is now `false` is `settings.json`

Default keybind for `Close File` - `Ctrl+W` (that's fine), default keybind for `Toggle Tab Visibility` - `Ctrl+Super+W`.

I'm not 100% sure this is the cause for originally reported issue, however i don't know how else `Toggle Tabs Visibility` would "change by itself", but it sure does sometimes. Also, for a person who didn't even know such keybind exists, it's very hard to troubleshoot what happened without googling and finding #60583 or other issue that mentions `workbench.editor.showTabs`, then it's a revelation to find out that this option is indeed set to `false` in settings somehow.

Similar issue: #60140

Does this issue occur when all extensions are disabled?: Potentially.

**Comment by liubiantao** [comment]
Maybe this is the real reason for the bug, even not, I learned a shortcut key to `Toggle Tab Visibility`,
 thank you @alekseyt .

**Comment by bpasero** [comment]
I am not sure why this has a keybinding associated by default, I think we should just remove it.

**Comment by bpasero** [comment]
Given ~3500 users of this command through keybinding I am reluctant to just remove it. Closing as designed. You can always remove a keybinding to not accidentally hit it.

**Comment by plinehan** [comment]
FWIW I fat-fingered this myself yesterday and was mystified for a whole day until I spent 10 minutes digging into the settings.
