### ISSUE TITLE
Search: clear should also clear all the input fields

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#62952]
Also it should be disalbed only if the input fields are empy and the tree is empty.

The clear is clear everything to my mind, so I do not like that we are leaving the input box and filter input untouched.

**Comment by skprabhanjan** [comment]
@roblourens , can i work on this ?

**Comment by roblourens** [comment]
Sure

**Comment by skprabhanjan** [comment]
@roblourens, Some starter points would be really helpful, thanks :)

**Comment by roblourens** [comment]
I guess @aechan got to it first. @aechan this issue was claimed, please leave a note if you are working on an issue, or don't snipe issues that someone else is working on...

**Comment by jrieken** [comment]
Works, but unsure if everyone will be happy with this change in default behaviour...
