### ISSUE TITLE
Please provide a code.ps1 alongside code.cmd and code in bin directory

### ISSUE THREAD

**Issue by marking** [Microsoft/vscode#6296]
- VSCode Version:
Version 1.1.0
Commit c212f0908f3d29933317bbc3233568fbca7944b1
Date 2016-05-09T12:53:58.929Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0

- OS Version: Windows 10 Professional

not so much a bug as a feature request. I'd like to see a code.ps1 along with the code.cmd and code scripts.  Here's a skeleton to get started (blatantly copied from code.cmd and translated):

```powershell
[CmdletBinding()]
    Param
    (
    [parameter(mandatory=$false, position=0, ValueFromRemainingArguments=$true)]$Remaining
    )

Remove-Item env:\VSCODE_DEV
$env:ATOM_SHELL_INTERNAL_RUN_AS_NODE=1
$dp0 = Split-Path -parent $PSCommandPath;
$exePath = [System.Io.Path]::Combine($dp0, "..\code.exe");
Write-Verbose "exePath is $exePath";
$jsPath =  [System.Io.Path]::Combine($dp0, "..\resources\app\out\cli.js");
Write-Verbose "jsPath is $jsPath";
Write-Verbose "remaining is $remaining"
Write-Verbose "command line is [$exePath] [$jsPath] [$remaining]"

&"$exePath" "$jsPath" $remaining

```

**Comment by marking** [comment]
updated powershell example to better handle env changes as well as added some verbose output

**Comment by isidorn** [comment]
Please file this issue in the https://github.com/PowerShell/vscode-powershell
As this is happening in the powershell extension
