### ISSUE TITLE
[macos] "Enable Trash" setting only works if "Confirm Delete" Setting is enabled

### ISSUE THREAD

**Issue by cgoy-nvidia** [Microsoft/vscode#62960]
- VSCode Version: Version 1.28.2 (1.28.2) 7f3ce96ff4729c91352ae6def877e59c561f4850
- OS Version: MacOS Mojave 10.14.1 (18B75)

Steps to Reproduce:

1. Go to settings, make sure `Enable Trash` is checked
2. Also make sure `Confirm Delete` is not checked
3. Use cmd + delete to delete a file in the explorer
4. Notice the dialog with `Delete Permanently` working comes up.
5. Click `Delete Permanently` and notice the file doesn't go to the trash.
6. Go back to settings and check `Confirm Delete` in the `Explorer` section
7. Delete a file
8. Notice the different dialog notifying about sending the file to the trash.

Both of these settings need to be enabled on MacOS to have files go to the trash which seems a bit misleading at best, but I did just lose a day's worth of work because of this.  My `Enable Trash` Setting was enabled, but my file was deleted permanently. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by cgoy-nvidia** [comment]
Related issue: #32078

**Comment by bpasero** [comment]
@cgoy-nvidia I cannot reproduce this with your steps, with `explorer.confirmDelete: false` I am never seeing a dialog popping up when deleting from the explorer via keybindings. That is the expected behaviour, no?

**Comment by cgoy-nvidia** [comment]
Suppose no.  Sorry for the noise.
