### ISSUE TITLE
Consider deprecating the split JSON settings editor

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#62964]
Edit - Since this has so many 👎, I need to be very clear, we will never remove editing settings.json files. This is about the UI in the JSON editor, e.g. the pencil icons, the split view, the search bar, etc.

---

Now that the settings UI is stable, we should consider getting rid of the split JSON settings UI. It would just mean less code to maintain, and new UX feature investment can be focused on the UI.

I think that by default, we would open the default settings and settings.json side by side, and the setting `workbench.settings.openDefaultSettings` would still control whether the default settings editor is opened.

We need a better understanding of how many people are using it over the settings UI.

**Comment by roblourens** [comment]
I need to be clear, we will never remove editing settings.json files. This is about the UI in the JSON editor, e.g. the pencil icons, the split view, the search bar, etc.

**Comment by eamodio** [comment]
While I don't care much about the pencils, I definitely like the split view and filtering. I would still consider that quite a loss

**Comment by roblourens** [comment]
Would the simpler split view (just two editors like keybindings uses) suffice? And you would still get intellisense in settings.json which I find sometimes more useful anyway.

**Comment by martellaj** [comment]
It looks like this has already been implemented in Insiders... First bad move VS Code has made IMO. 🙁

**Comment by roblourens** [comment]
No, I haven't made any change for this.

I think some people are misunderstanding what this change is about. settings.json is not going away, you can even set it as the default if you want.

**Comment by martellaj** [comment]
Got it. Thanks, Rob. The link in the rich settings UI to open in settings.json seems to be gone in the latest build so that's why I assumed. I'll have to hunt it down...

**Comment by roblourens** [comment]
Oh, under the `...` button? Yes that was moved to an editor action button, so now you can get to it with a single click 😄 

![image](https://user-images.githubusercontent.com/323878/48451330-d74eae00-e75e-11e8-8ce0-8478e75a5f33.png)

**Comment by eamodio** [comment]
@roblourens for me I think just a normal split view would suffice. Sometimes I like the search filtering, but I don't think I'd miss it much.

**Comment by carlocardella** [comment]
Personally I don't care too much about the pencil (as long as intellisense will still work) but I do like the search/filtering. For settings I'm not a UI fan, I have set the json view as my default

**Comment by Astrantia** [comment]
@roblourens The new settings UI doesn't provide configuration for more complicated extensions. For example look up latex extension, 40% of the extension settings cant be configured in the new editor.

**Comment by martellaj** [comment]
@carlocardella Thanks for the heads up that there's a setting for settings. 😂 Just switched mine to be JSON by default! 🎉

**Comment by graph** [comment]
When I saw the json settings editor for the first time I thought it was a genius approach.  Especially given that vs code target audience is developers. The pencil button is great, the search is great, comments in the code. It feels so simple and easy. It's easy to find what I'm looking for and edit the settings as needed. The new UI is also simple and easy to use, and is great, but I don't feel it's worth effort to migrate to new UI.

**Comment by carlocardella** [comment]
Exactly my reaction: I did not complain when the Settings UI was proposed (I understand people may have different requirements and taste) but given being a developer tool I had not expected the need for a UI, since the Json split view works very well.

**Comment by JeffreyCA** [comment]
Coming from 1.29 to the Insiders build, it took me way too long to figure out that the `{}` icon was for opening the `settings.json` file. I thought you guys removed the feature or something. My initial instinct was to think that it would be under the `...` button on the tab bar because it had been under the `...` before.

The location of the icon got moved to the same row as the upper tab bar which makes it difficult for users to discover where the new button for accessing the JSON is.

| Before | After |
|---|---|
| <img width="977" alt="screen shot 2018-11-26 at 10 42 12 am" src="https://user-images.githubusercontent.com/9157833/49024724-2ab1fa80-f168-11e8-9292-0e47fc3dd6a2.png"> | <img width="1081" alt="screen shot 2018-11-26 at 10 42 22 am" src="https://user-images.githubusercontent.com/9157833/49024740-2f76ae80-f168-11e8-9dd5-faaa65870756.png"> |

Can we move the `{}` button to where the previous `...` button was: on the same row as *User Settings* and *Workspace Settings*?

**Comment by JeffreyCA** [comment]
@roblourens

**Comment by roblourens** [comment]
This actually makes it more consistent with the rest of vscode, e.g. similar to the button to navigate from a git diff view to the individual file. I understand it might be a road bump for people who have gotten used to the second ... menu but I think it's better long term to be consistent. Also, this puts it a single click away instead of two clicks which was a common complaint.

**Comment by JeffreyCA** [comment]
My suggestion would be sort of a middle ground, so that accessing the JSON is still one click away, but in the previous location. I think it makes more sense to put it on the lower row because it applies only to the Settings view.

There will probably be many reports by users asking where that setting went when 1.30 is released.

**Comment by roblourens** [comment]
Could you open a new issue for that since it's not quite related to removing the UI in the JSON editor?

**Comment by JeffreyCA** [comment]
Sure, created an issue here: https://github.com/Microsoft/vscode/issues/63806

Other than discovering the new button after upgrading I don't think there are major issues with the change.

**Comment by piotr-tobolski** [comment]
Maybe we should consider deprecating the GUI settings editor? The JSON settings editor in a *developer tool* is a brilliant idea I wish more apps would adopt.

I would love an option to disable the GUI settings editor completely to make the VS Code a bit faster and simpler.

**Comment by roblourens** [comment]
If you don't like it, don't use it 😁 See `workbench.settings.editor`

**Comment by MeikTranel** [comment]
@roblourens then why is this issue even discussed if you don't plan to to get of the split view editor, but default to the GUI editor instead?

**Comment by thernstig** [comment]
**Benefits of the JSON editor**
- Easy copy&paste of configuration.
- Quick overview of your personal settings (the defaults one has chose to override).
- Extensions, all of them(?), show the settings as JSON. For example, see here: https://code.visualstudio.com/docs/editor/codebasics. Maintaining images to show of settings is very cumbersome.
- You get green squiggly lines on settings that you have configured but that do not longer exist, which gives a quick visual indication.
- Possibility to configure more complex settings.

**Benefits of the GUI editor**
- You can click stuff.

Feel free to add to the list.

To reiterate: I've already understood this is not about removing the JSON editor. But you are aiming to do "something" and that "something" I do not like whatever it is :)

But I have no idea why the GUI editor is the default. Do Microsoft employees actually prefer that? As coders? Another topic for another day maybe.

**Comment by roblourens** [comment]
I am moving this issue to https://github.com/Microsoft/vscode/issues/64932

@thernstig Those are all good reasons that you may prefer to use JSON and you are still welcome to do so 😁 

But there are many benefits of the GUI editor for new users. Not every vscode user is an experienced coder. Not every coder knows what JSON is. The JSON-based experience is overwhelming to many people who just want to change the font size with a minimal learning curve. When there is a power user option and a friendly option, the friendly option is going to be the default.
