### ISSUE TITLE
Ignore text after linenumber in file explorer

### ISSUE THREAD

**Issue by nicdal** [Microsoft/vscode#62962]
When copying filenames from a backtrace in Ruby you have text added after the line number.
app/controllers/demo/demo_controller.rb:45:in `demo_method'

In many other code editors it is possible to search for
"demo_controller.rb:45:in `demo_method'"
It will find the file demo_controller.rb and open it on line 45.

In vscode you have to remove the extra text until it says
"callback_controller.rb:70:" before it finds the file.

Would it be possible to get same behavior in vscode?

**Comment by roblourens** [comment]
Are you searching in quick open (cmd+p/ctrl+p)?

**Comment by nicdal** [comment]
Yes quick open.

**Comment by roblourens** [comment]
Not likely to happen, our fuzzy search just matches the whole query against the path.
