### ISSUE TITLE
Please make the ... menu in source control scrollable

### ISSUE THREAD

**Issue by Muzical84** [microsoft/vscode#62969]
Basically, I have my entire VS Code UI set super-large--that's one thing I LIKE being able to do and why I quickly swapped to Code from Sublime.  However, I noticed that when I tried to click the ... menu in Source Control, the menu that pops up is not scrollable; the only way to see the entire thing is to shrink my UI, I think past even the default level of smallness.

<img width="953" alt="capture" src="https://user-images.githubusercontent.com/775601/48373819-8a98a380-e688-11e8-8ff6-72ac5c41cb32.PNG">

**Comment by sbatten** [comment]
this is done
