### ISSUE TITLE
Creating debug task dropdown box opens too long

### ISSUE THREAD

**Issue by Yanpas** [Microsoft/vscode#62967]
Issue Type: <b>Bug</b>

Screencast:
![peek 2018-11-12 22-42](https://user-images.githubusercontent.com/7345761/48371225-5b0b8a80-e6cc-11e8-943d-f400cb79d094.gif)

First time (after boot) it takes longer, but it's already long enogh on the screencast

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:20:56.183Z)
OS version: Linux x64 4.18.16-arch1-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 4100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.61GB (0.63GB free)|
|Process Argv|src/extragear/utils/yakuake/ -n|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
yaml|ada|0.0.9
vscode-hie-server|ala|0.0.24
better-toml|bun|0.3.2
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.7.0
vscode-dash|dee|2.0.0
java-decompiler|dgi|0.0.2
xml|Dot|2.3.2
gitlens|eam|8.5.6
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.40
prettier-vscode|esb|1.7.2
file-icons|fil|1.0.16
code-runner|for|0.9.5
godot-tools|gee|0.3.7
todo-tree|Gru|0.0.101
live-html-previewer|hdg|0.3.0
hoogle-vscode|jca|0.0.7
svn-scm|joh|1.45.1
language-haskell|jus|2.5.0
favorites|kdc|2.3.1
Lisp|mat|0.1.8
vscode-todo-parser|min|1.9.1
vscode-clang|mit|0.2.3
vscode-language-pack-ru|MS-|1.28.2
python|ms-|2018.10.1
cpptools|ms-|0.20.1
csharp|ms-|1.17.0
mono-debug|ms-|0.15.8
phoityne-vscode|pho|0.0.20
java|red|0.33.0
rust|rus|0.4.10
vscode-hexdump|sle|1.7.2
vscode-lua|tri|0.12.4
cmake|twx|0.0.17
cmake-tools|vec|1.1.2
vscode-svg-previewer|vit|0.1.2
vscode-java-debug|vsc|0.15.0
debug|web|0.22.0
jinja|who|0.0.8
clang-format|xav|1.6.2

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
All of your debug extensions are being activate, and you have some extension taking a long time to activate. I know the C# extension can be slow to activate. You may want to check which one is being slow and disable it if you aren't using it.

FYI @isidorn
