### ISSUE TITLE
"editor.autoClosingQuotes": "always" does not always apply

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#62968]
Issue Type: <b>Bug</b>

Related to #61070

**Repo**
1. Set `"editor.autoClosingQuotes": "always"`
2. In a js file with cursor at `|`:

```js
abc|
```

3. Type \` (backtick)

**Expected**
Backtick is closed since we have set the mode to `always`

**Actual**
Quote is not closed

VS Code version: code-oss-dev 1.30.0 (Commit unknown, Date unknown)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|25%|

</details>

**Comment by 5tormTrooper** [comment]
I still have this issue. 
Applied the setting, and even tried reloading window with extensions disabled. Tried in both "javascript" and "javascriptreact". 

VS Code: 1.32.3 (1.32.3)
OS: MacOS High Sierra 10.13.6

**Comment by irrationalRock** [comment]
@5tormTrooper I'm wondering if can you try and replicate this issue on VSCode Insiders?

**Comment by 5tormTrooper** [comment]
@irrationalRock It seems to autoclose as expected on Insiders 👍

However, it'd be helpful to have it auto-ident on enter, since template literals allow expressions, such as in use with graphql.

![Screen Recording 2019-04-07 at 12 25 PM](https://user-images.githubusercontent.com/4154407/55682216-bb77be80-5930-11e9-8b1d-c0149b42425b.gif)

VS Code: 1.34.0-insider (1.34.0-insider)
