### ISSUE TITLE
Recommend to disable an extension in .vscode/extensions.json

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#62975]
Issue Type: <b>Bug</b>

**Feature Request**
Allow workspace authors to recommend that an extenion be disabled in the workspace. 

**Example Use Case**
When migrating the VS Code workspace to use the new `typescript-tslint-plugin` extension, we'd like to ensure that users disable the old `eg2.tslint` extension. There does not currently seem to be a clean way of doing that.

It would be nice if we could write:

```json
{	"recommendations": [
		"ms-vscode.vscode-typescript-tslint-plugin",
		"-eg2.tslint"
	]
}
```

or 

```json
{	"recommendations": [
		"ms-vscode.vscode-typescript-tslint-plugin"
	],
	"recommendationToDisable": [
		"eg2.tslint"
	]
}
```

VS Code version: Code - Insiders 1.29.0-insider (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-10T00:26:25.769Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 5|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|--inspect-extensions=19773|
|Screen Reader|no|
|VM|25%|

</details>

**Comment by sandy081** [comment]
@mjbvz What is the intention here? 

Is it to recommend users an extension is replaced by a new extension and replace the old with new extension?

If so, why not rename the existing extension with new?
