### ISSUE TITLE
failed to install all extensions - it  shows a non-stopping progress status

### ISSUE THREAD

**Issue by Yidy** [Microsoft/vscode#62979]
Issue Type: <b>Bug</b>

VS code installed on Windows 8.1. But in is not installing extensions. It shows a contineous installing status. Tried all suggestions from forums with no success.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz (8 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (10.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

</details>Extensions: none

**Comment by sandy081** [comment]
@Yidy Can you please do following steps:

- Set log level to `trace` using `set log level` command from Command Pallette
- Open Shared Process logs in Output panel
- Retry the install operation
- Share us the logs
