### ISSUE TITLE
Debug Configuration drop down blank before creating launch.json

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#6297]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Open a folder with no launch.json config file
2. Switch to the debug viewlet

The drop down used to say "No Configuration" where now it says nothing until you create launch.json.

![noconfignotshowing](https://cloud.githubusercontent.com/assets/12900364/15198132/6002cb2a-178a-11e6-933f-0aed7b6f301b.PNG)

Is this an intended change?

**Comment by isidorn** [comment]
Assiging to @vsccarl to verify
