### ISSUE TITLE
Don't use non-standard MouseWheelEvent in codebase

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#62981]
Issue Type: <b>Bug</b>

**Problem**
The `MouseWheelEvent` dom event type is non-standard and has been deprecated: https://developer.mozilla.org/en-US/docs/Web/API/MouseWheelEvent

We use this type in a few places in the VS Code code base

**Proposed Fix**
See if we can migrate the the standardized `WheelEvent` instead: https://developer.mozilla.org/en-US/docs/Web/API/WheelEvent

VS Code version: code-oss-dev 1.30.0 (Commit unknown, Date unknown)
OS version: Darwin x64 18.2.0

**Comment by roblourens** [comment]
Scrolling felt off in today's insiders, I looked around and found this issue. On my 2015 Macbook Pro, scrolling with the touchpad feels less sensitive than it did before. Let me know how I can help debug.

**Comment by alexandrudima** [comment]
This is a bit tough to debug. What I've done is leave both kind of listeners in and comment/uncomment them and then I put a console.log in the old implementation to check what the previous result was and what the new result was (i.e. compare a before and after for `deltaX`, `deltaY`).

My mac is in for repairs, so I cannot test this anytime soon. I would appreciate if you can debug it a little... see the `mousewheel` event vs the `wheel` event and just do a console.log(JSON.stringify(e))

**Comment by usernamehw** [comment]
Scroll with mouse wheel not looking great either
```json
"editor.mouseWheelScrollSensitivity": 9,
"editor.fontSize": 20,
"editor.lineHeight": 30,
```

stable scrolls **15** lines
insiders scrolls **~38** lines

OS version: Windows_NT x64 10.0.17134

**Comment by alexandrudima** [comment]
We now use a mix to maintain compatibility...
