### ISSUE TITLE
Load more stack frames shown on all threads

### ISSUE THREAD

**Issue by faxue-msft** [Microsoft/vscode#6298]
- VSCode Version: 1.1
- OS Version: Windows 10, Ubuntu 14.04

Steps to Reproduce:

1. Create a multithread application and start debugging
2. Enter break mode, For thread 1: debugger return 20 stack frames and total count of 100. For thread 2: debugger return 3 stack frames and total count of 3.
3. Verify the "Load More Stack Frames" frame is shown for thread1, Verify there is only 3 frames for thread 2
4. Click the "Load More Stack Frames" frame in thread 1

Problem:
Both thread 1 and thread 2 now shows the "Load More Stack Frames" frame, even though thread 2 only has 3 stack frames.

**Comment by faxue-msft** [comment]
![1](https://cloud.githubusercontent.com/assets/5318374/15198680/b135f280-178d-11e6-8e33-dca7c1499ccd.png)
![2](https://cloud.githubusercontent.com/assets/5318374/15198681/b1386416-178d-11e6-9fbe-25959c3d7b91.png)

**Comment by isidorn** [comment]
@faxue-msft The version fo the C++ extension that I have does not support `totalFrames` thus I can not get this behavior. How can I get the newest C++ extension for which I can reproduce this?
I will first verify that the adapter returns a proper `totalFrames` field per each thread.

**Comment by faxue-msft** [comment]
It's not in any of the existing C++ Extension, I was working on supporting more than 20 frames and discovered this bug. I can share with you some private bits if you don't have any other debugger support this already.

**Comment by isidorn** [comment]
Only node debug so far supports this, but it is not multi threaded.
If sharing private bits is complicated I can do some hacking on the vscode side to fake this behavior.

Did you verify on your side that the totalFrames returned by your adapter are correct for each thread respectively?

**Comment by isidorn** [comment]
Setting this to June as we are wrapping up the May milestone and did not have a chance to investigate, let me know if you guys need it before and I will put back to May

**Comment by isidorn** [comment]
Since this is a bit hard to reproduce and not a huge issue I propose to fix this once the C++ extension starts supporting `totalFrames` attribute. Then I can investigate on my machine why this is happening.

**Comment by faxue-msft** [comment]
The latest C++ extension already supports totalFrames attribute.

**Comment by edumunoz** [comment]
I can repro this with some other debug adapter too.

**Comment by weinand** [comment]
@edumunoz @faxue-msft could you please verify that this works now in the insiders? Thanks.

**Comment by faxue-msft** [comment]
I verified in C++ debugger extension that that this bug is fixed today's insider build.
Thanks!

**Comment by weinand** [comment]
@faxue-msft thanks a lot for verifying.
