### ISSUE TITLE
Updata failed

### ISSUE THREAD

**Issue by WXZA** [Microsoft/vscode#62986]
![image](https://user-images.githubusercontent.com/44490742/48388486-77431200-e734-11e8-8109-5123047f80c6.png)
![image](https://user-images.githubusercontent.com/44490742/48388496-80cc7a00-e734-11e8-90d6-086b9e8ff540.png)
![image](https://user-images.githubusercontent.com/44490742/48388515-9477e080-e734-11e8-8a11-1b2b7b0c43c8.png)

How to deal with it?

**Comment by joaomoreno** [comment]
/duplicate #52855

Please fully reinstall VS Code. Sorry for that.
