### ISSUE TITLE
How to define custom search box in treeProvider

### ISSUE THREAD

**Issue by chnliquan** [Microsoft/vscode#62988]
- VSCode Version: 1.28.2
- OS Version: 10.3.3

Steps to Reproduce:

1. I want to add a search box in my view treeProvider like this

![image](https://user-images.githubusercontent.com/34906299/48390019-06ebbf00-e73b-11e8-8765-a949fe18da8f.png)

2. I can`t find an api to do this, please tell me how to create a search box to filter my treeProvider data

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
Duplicate of #50062
