### ISSUE TITLE
Global search and replace with regexp containing newlines does not substitute variables

### ISSUE THREAD

**Issue by aardappel** [Microsoft/vscode#62980]
- VSCode Version: 1.29.0
- OS Version: Linux / Ubuntu

Supposedly this issue was fixed in https://github.com/Microsoft/vscode/issues/9010 (which is now locked), but it is not working for me still.

Steps to Reproduce:

1. Use a global search regexp pattern with group occurrences such as (.*)
2. Refer to them in the pattern with `$1` etc.
3. Notice in the preview (double click on result) it shows `$1`, not the matched substring.

It could well be that it is a preview issue, did not try to actually execute the replacement.
Also my regexp was multi-line, if that matters (matching `\n` in places outside the groups).

**Comment by roblourens** [comment]
Can you share the exact regex search/replace? This works for me

**Comment by aardappel** [comment]
Ah I see you were able to reproduce. Sorry for not giving an example earlier.

**Comment by roblourens** [comment]
Pulling this from the recovery milestone. This is unfortunate but I think it's sort of a niche issue. The fix is in Insiders already if anyone needs this.
