### ISSUE TITLE
Open two projects with 100% CPU usage in the latest version

### ISSUE THREAD

**Issue by songyule** [Microsoft/vscode#62999]
- VSCode Version: 1.29.0
- OS Version: MacOS 10.12.6

Steps to Reproduce:

1.Open two proiects
2.
![image](https://user-images.githubusercontent.com/23656890/48399126-b76aba80-e75d-11e8-8869-905ec4e1c2bf.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by lysigk** [comment]
Same problem here, even when only one project is opened.

- VSCode Version: 1.29.0
- OS: Arch Linux

Additional observations: The CPU usage goes up after a few minutes and stays at 100%. At the same time, several keyboard shortcuts stop working as expected (could be realated to #62994 ). Restarting VSCode helps, but only for a short period of time.

**Comment by joseph1125** [comment]
I experience the same problem here

VSCode Version: 1.29.0
OS: Windows 10 Pro

**Comment by roblourens** [comment]
Can you get the full command line args of those processes using `ps ax` or the vscode Process Explorer?
