### ISSUE TITLE
Markdown relative image in preview not shown

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/vscode#62995]
Steps to Reproduce:

On windows

For a folder structure:
```
images/
    logo.png
docs/
    doc.md
```

With doc.md:
```
![a](../images/logo.png)
```
1. Open doc.md directly (don't open the folders)
2. Open preview

bug
No image shown in preview.

**Comment by mjbvz** [comment]
I can't repo in VS Code insiders:

![screen shot 2018-11-14 at 5 45 58 pm](https://user-images.githubusercontent.com/12821956/48524439-2a933000-e835-11e8-8319-4f5b993bfa2e.png)

Does this repo with extensions disabled?

**Comment by formulahendry** [comment]
Hi @mjbvz , please not open that folder so that you could repro.
![image](https://user-images.githubusercontent.com/1050213/48535509-8ff32980-e8e6-11e8-809f-fd6f1abeea62.png)

**Comment by mjbvz** [comment]
This is intentionally not supported for security reasons. We only support opening files with the current workspace, not in parent directories
