### ISSUE TITLE
Format on save messes up original HTML file format

### ISSUE THREAD

**Issue by micobarac** [Microsoft/vscode#62996]
- VSCode Version:
1.28.2 (1.28.2)

- OS Version:
macOS Mojave 10.14.1
Windows 10 x64

Steps to Reproduce:

1. Create new or edit an existing HTML file with new lines and indenting
2. Save HTML file with Format on Save active
3. Most of the time the VSCode compacts some parent tags into one line tags and messes up the original HTML file format. Some other tags are split over multiple lines. Sometimes, this problem doesn't happen when hitting the save in VSCode.

Example:

Original HTML code:

```html
<div class="navbar-item">
  <div class="control has-icons-right">
    <input class="input is-rounded is-secondary-focus has-text-white is-borderless" type="text" placeholder="Search..."/>
    <span class="icon is-small is-right has-text-white"> 
      <i class="sl sl-icon-magnifier"></i> 
    </span>
  </div>
</div>
```

Messed-up code:

```html
      <div class="navbar-item">
        <div class="control has-icons-right">
          <input
            class="input is-rounded is-secondary-focus has-text-white is-borderless"
            type="text"
            placeholder="Search..."
          />
          <span class="icon is-small is-right has-text-white"> <i class="sl sl-icon-magnifier"></i> </span>
        </div>
      </div>
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by zymr-keshav** [comment]
same issue here

vs code v 1.29.0
macOS v _10.13.6_ High Sierra

 - No HTML formatter extension installed/enabled 

settings 
_Format On Save: Disabled_ 

now when I make any change and save the file (⌘ + s) it changes HTML semantics weirdly and it turned 1 line of HTML into 10 lines and each line have single HTML attribute, [see this image](https://imgur.com/a/DaAEYlj)

**Comment by zymr-keshav** [comment]
I have disabled all extensions and it is working fine but do not know which is the culprit and obviously, we need those extensions for our ease and help.

**Comment by micobarac** [comment]
Actually, **Prettier - Code formatter** extension was the only one active and was causing all the problems. 

Sorry VSCode guys!!!

**Comment by micobarac** [comment]
I have some pretty long HTML tags. Setting `printWidth` to 300 didn't solve the problem :(.

Original:

```html
              <!-- Name -->
              <mat-form-field>
                <input matInput type="text" formControlName="name" required placeholder="{{ 'OpenFunctionTranslation.Name' | translate }}"
                  autocomplete="off" />
              </mat-form-field>
              <small *ngIf="name.touched && !name.value.length" class="mat-warn">
                {{ 'OpenFunctionTranslation.NameRequired' | translate }}
              </small>
              <small *ngIf="name.touched && !name.valid && name.value.length" class="mat-warn">
                {{ 'invalidNameFormat' | translate }}
              </small>
```
Bad Prettier Formatting:

```html
              <!-- Name -->
              <mat-form-field> <input matInput type="text" formControlName="name" required placeholder="{{ 'OpenFunctionTranslation.Name' | translate }}" autocomplete="off" /> </mat-form-field>
              <small *ngIf="name.touched && !name.value.length" class="mat-warn"> {{ 'OpenFunctionTranslation.NameRequired' | translate }} </small> <small *ngIf="name.touched && !name.valid && name.value.length" class="mat-warn"> {{ 'invalidNameFormat' | translate }} </small>
```

**Comment by micobarac** [comment]
Is there an option in the Prettier VSCode settings to disable its bad HTML formatter and let the built-in formatter work? I went through the docs and couldn't find any...

**Comment by micobarac** [comment]
Actually, this is a setting that disabled Prettier formatter for HTML files:

```json
"prettier.disableLanguages": ["html"]
```

**Comment by zymr-keshav** [comment]
I also tried all available options in vs code settings  by keyword "word wrap" and tried various combination but no luck

**Comment by micobarac** [comment]
Use the above setting in VSCode `settings.json` file. It required a restart of VSCode in my case to make it active, I don't know why. This way it reactivates the built-in HTML formatter which works fine enough. I just hope the Prettier formatter will get fixed any time soon.

**Comment by zymr-keshav** [comment]
Yes, you are right. I did the same and add these 2 settings in settings.json

```
"prettier.disableLanguages": [
    "html"
  ],
 "html.format.enable": true,
"html.format.indentInnerHtml": true
```
