### ISSUE TITLE
Terminal is not split

### ISSUE THREAD

**Issue by MVDraurus** [Microsoft/vscode#62991]
Issue Type: <b>Bug</b>

The termonal is not broken, neither with the button and with the kay combination, until the update worked, please check ...

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:42:27.562Z)
OS version: Linux x64 4.9.0-8-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU 3825U @ 1.90GHz (4 x 1900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|3.78GB (1.12GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.2.0
code-gnu-global|aus|0.2.2
doxdocgen|csc|0.4.1
gitlens|eam|8.5.6
vscode-todo-plus|fab|4.10.0
cpptools|ms-|0.20.1
material-icon-theme|PKi|3.6.0

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Can you explain exactly what you do? The "Split Terminal" works for me

**Comment by yagehu** [comment]
Also does not work for me after update. When I click the split terminal icon, the icon registers the click but nothing happens. Shortcut ctrl+\ and command pallete also does nothing.

Version: 1.29.0
Commit: 5f24c93878bd4bc645a4a17c620e2487b11005f9
Date: 2018-11-12T07:42:27.562Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by robclancy** [comment]
I'm on arch linux, doesn't work. Coworker beside me is on mac, works fine.

**Comment by yagehu** [comment]
> I'm on arch linux, doesn't work. Coworker beside me is on mac, works fine.

I'm also on Arch

**Comment by alexr00** [comment]
Have you modified the terminal split setting? In your user settings, What is Terminal>Integrated: Split Cwd set to?

**Comment by sainf** [comment]
After updating to 1.29, in Linux (arch), on: Terminal>Integrated: Split Cwd: default _inherited_ fails to open split terminal, but _initial_ and worksapceRoot work's fine.

**Comment by yagehu** [comment]
> Have you modified the terminal split setting? In your user settings, What is Terminal>Integrated: Split Cwd set to?

Same as @sainf. Using workspaceRoot now. ``inherited`` does not work.

**Comment by nfour** [comment]
Can confirm `inherited` doesn't work on Arch. The other two options do though.

**Comment by alexr00** [comment]
Seems like it might be Arch specific then.

**Comment by MVDraurus** [comment]
I found how to fix it, in the ```Terminal› Integrated: Split Cwd``` settings, I’ve chosen the ```initial``` option instead of ```inherited``` and it worked!

**Comment by robclancy** [comment]
Confirmed works when you change it. But a new issue should be opened about inherited not working? Especially since it's the default.

**Comment by foli** [comment]
It doesn't work on debian(deepin) either, nothing happens when clicked or with the shortcut
also terminal position button is missing
```
Version: 1.29.1
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:07:43.495Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

**Comment by alexr00** [comment]
We should still fix that `inherited` doesn't work for some people using Linux. @foli, what do you have `terminal.integrated.splitCwd` set to?

**Comment by sambrosia** [comment]
On Arch Linux here as well, and terminal splitting does not work with `terminal.integrated.splitCwd` set to `inherit` for me. The workaround suggested by @polderudo in #63170 does not resolve the problem for me.

**Comment by Tyriar** [comment]
This is what is run to get the cwd on Linux currently:

https://github.com/Microsoft/vscode/blob/beb5998ea3d6b4cae43b3a09ecdf11e3bd692667/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L1158-L1165

**Comment by alexr00** [comment]
@sainf, @sambrosia, @yagehu and anyone else who saw `inherited` not work: 

I'm not sure what's going wrong here. Can you:

1. Open a terminal in vscode
2. run `echo $$` in that terminal
3. Run `lsof -p <output from step 2>`
4. There should be a line FD == cwd in there. Can you share that line? I'm guessing there's something about out substring in the snippet @Tyriar posted that doesn't always work.

**Comment by sambrosia** [comment]
Yeah it looks like `lsof` is not a declared dependency in the `visual-studio-code-bin` AUR package.

The `inherit` option works as expected after manually installing `lsof` :+1:

**Comment by Tyriar** [comment]
@dcelasun could you add `lsof` as a dep to your AUR package?

**Comment by dcelasun** [comment]
@Tyriar thanks for the ping, I've updated stable and insiders builds.
