### ISSUE TITLE
osx asks to select python intepreter everytime reopened

### ISSUE THREAD

**Issue by tbbrave** [Microsoft/vscode#62997]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.on macos
2.open python code
![image](https://user-images.githubusercontent.com/9070847/48398752-9b1a4e00-e75c-11e8-82ae-081edde93516.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
Did you select an interpreter? Please file this on the Python extension if it's a bug.
