### ISSUE TITLE
Keybindings Not Working Anymore

### ISSUE THREAD

**Issue by Javid-Izadfar** [Microsoft/vscode#62994]
Issue Type: <b>Bug</b>

I've been using VSCode for quite some times with my own key binding settings. I've updated VSCode recently and these keybindings (like my custom emmet abbrevation) fail.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (8.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.7.0
gitlens|eam|8.5.6
vue-snippets|hol|0.1.9
atom-keybindings|ms-|3.0.4
vetur|oct|0.13.0
vue-vscode-snippets|sdr|1.3.0

(1 theme extensions excluded)

</details>

**Comment by falkheiland** [comment]
keyboard shortcut workbench.action.terminal.clear was unassigned (was CTRL+K) with 1.29

**Comment by roblourens** [comment]
Do they still appear in the keybindings editor?

Can you try upgrading to 1.29?

**Comment by Javid-Izadfar** [comment]
I've Upgraded to 1.29 but still the same. And yes they are in keybindings editor

**Comment by falkheiland** [comment]
other issue

**Comment by roblourens** [comment]
Can you give a specific example of what the keybinding is and what doesn't work?
