### ISSUE TITLE
File Search got stuck with a great number of files

### ISSUE THREAD

**Issue by diegossalmeida** [Microsoft/vscode#63]
File search (CTRL + E) got stuck with a great number of files (around 60k files on 5k folders) when searching for a file by its name. It took too long to find the file and sometimes the search bar suddenly disappeared.

**Comment by AdiOltean** [comment]
I have a similar issue. Search is extremely slow and gets stuck at some point. I have around 33K files, mostly source code. 

A few results are being shown after a while but this is clearly incomplete. 

Sublime Text (or even the "findstr" command) have no trouble grepping though these files in a few seconds. 

I am using a fast SSD as a disk-level storage (Samsung 840 PRO) so disk read performance should be very good both in terms of IOPS and bandwidth.

**Comment by bpasero** [comment]
#55
