### ISSUE TITLE
Git: Support to open file on click, by default

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#63005]

**Comment by joaomoreno** [comment]
There's a new `git.openDiffOnClick` setting which controls this behavior.

Verifier please check that upon toggling that setting, files start opening in the regular editor and a `Open Change` action appears inline, for each.

**Comment by usernamehw** [comment]
Is it possible to add another way of opening?

`"git.openDiffOnClick": true` - <kbd>Alt</kbd> + <kbd>Click</kbd> - to open file
`"git.openDiffOnClick": false` - <kbd>Alt</kbd> + <kbd>Click</kbd> - to open diff

**Comment by joaomoreno** [comment]
@usernamehw Care to file a separate issue?
