### ISSUE TITLE
registerCompletionItemProvider include extra data

### ISSUE THREAD

**Issue by chnliquan** [Microsoft/vscode#63004]
- VSCode Version: 1.29.0
- OS Version: 10.3.3

Steps to Reproduce:

1. when i use `registerCompletionItemProvider` api, the IntelliSense include some extra data like this
![image](https://user-images.githubusercontent.com/34906299/48401021-023b0100-e763-11e8-8fd8-2ca5e329a255.png)

2. i just want my data show 

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
Extensions cannot mute other extensions. The design of the system it to be cooperative and not exclusive.
