### ISSUE TITLE
Symbols not loaded for current project according to tsconfig.json lookup logic (only for first tsconfig.json found in project)

### ISSUE THREAD

**Issue by ashelley** [Microsoft/vscode#6300]
- VSCode Version: 1.10
- OS Version: Windows 10

Symptom: 

VSCode only loads symbols for the first tsconfig.json it finds in the directory tree.  If you try to look up a symbol using Ctrl+T you will only see symbols from the first tsconfig.json in the project.

Expected results: 

When hitting Ctrl+T it should look at the current active file and find the next tsconfig.json up the directory tree and use that to load symbols.  Currently it seems that the syntax checker (compiler) uses the right logic to determine the correct symbols to load but Ctrl+T does not.

Steps to Reproduce:

1. clone this sample repo https://github.com/ashelley/vscode-tsconfig-all-symbols-test.git
2. Navigate to any project that is not the first project in the list (module3/Biz.ts)
3. Notice that symbols are loaded for only the first project:

![image](https://cloud.githubusercontent.com/assets/3195045/15199261/8b188b04-1791-11e6-9bf6-471319d8402c.png)

4. Try to load a symbol from the current project.  Notice how the symbol loads for the syntax checker (compiler) (no errors) but does not load the symbol when hitting ctrl+T

![image](https://cloud.githubusercontent.com/assets/3195045/15199286/c17d4eb4-1791-11e6-86c5-72c6afea9eb7.png)

![image](https://cloud.githubusercontent.com/assets/3195045/15199292/d5a4a9be-1791-11e6-9e70-79363600d24f.png)

**Comment by ashelley** [comment]
Another example of a discrepancy between the symbol lookup and other features of vscode is that peek definition still works (even if the symbol lookup does not)

 
![image](https://cloud.githubusercontent.com/assets/3195045/15199440/f62bf164-1792-11e6-8f53-a40d209837f3.png)

**Comment by dbaeumer** [comment]
Due to a limitation of the tsserver workspace symbols are currently scoped to the project the focused text editor is part of.

I will move this issue to TS since it requires work on the tsserver side.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#8571
