### ISSUE TITLE
Issue reporter: Detect language and suggest automatic translation

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#63006]
The issue reporter could use Bing Translator (or similar) to detect the entered language and suggest a translation if it is not in English.

**Comment by gjsjohnmurray** [comment]
Sort of related to this, do the non-English translations of the Issue Reporter dialog already include text (in the localized language, naturally) asking the user to post in English? If not, perhaps that would be an easy first step towards reducing the number of issues opened in other languages.

**Comment by RMacfarlane** [comment]
@gjsjohnmurray Yes, there's localized text at the top of the Issue Reporter in that case asking for responses in English
