### ISSUE TITLE
Recommended XML extension in VS Code

### ISSUE THREAD

**Issue by fbricon** [microsoft/vscode#63001]
Currently, VS Code recommends to install https://marketplace.visualstudio.com/items?itemName=DotJoshJohnson.xml, when an XML document is opened or when you search for XML, in the extensions view:

<img width="489" alt="screen shot 2018-11-13 at 3 14 08 am" src="https://user-images.githubusercontent.com/148698/48399642-375b3b00-e6f2-11e8-92a8-ec38a7b3c2f1.png">

[`redhat.vscode-xml`](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml) actually has a [**much** larger feature set](https://github.com/redhat-developer/vscode-xml/blob/master/README.md#features) and is actively maintained. 

I wonder which criteria determine how an extension should be the recommended one for a given language. Is it based on max number of installations alone? I remember how, for Java, the recommendation was sort of hard-coded to promote Microsoft's Java Extension pack. 

cc @auchenberg, @egamma, @aeschli, @akaroml, @gorkem, @NikolasKomonen

**Comment by olafurpg** [comment]
Related, the top recommended extension for Scala is "Better Comments" instead of the official Syntax highlighting extension, which is actively maintained and also vendors Scala highlighting on GitHub.com.

![Screenshot 2019-06-19 at 18 32 34](https://user-images.githubusercontent.com/1408093/59783606-c8b21180-92c0-11e9-9f81-352399f92d68.png)

**Comment by angelozerr** [comment]
@auchenberg, @egamma, @aeschli, @akaroml, @gorkem, @mjbvz today Red Hat vscode-xml continues to provide more and more advanced features like XML -> XSD/DTD generator, codelens inside DTD, XSD, entities support, etc and we have a lot of planned features although the XML Tools which is the recommended extension is not active.

As @fbricon asked, could you please explain which criteria determine how an extension should be the recommended one for a given language?

Perhaps the Java requirement is the problem and it's the reason why vscode doesn't recommend Red Hat vscode-xml extension?

Thanks for your answer.

**Comment by chrisdias** [comment]
We try to recommend extensions that will provide the best "out of the box" experience, which is guided by what is popular/highly downloaded/highly ranked in the Marketplace. It looks like the XML tools extension has quite some open issues, but it also looks like the maintainer of the extension has become active again, which is goodness.

And, we can recommend multiple extensions. The challenge with the Redhat extension is that the user gets an error message immediately when trying to view an XML file if they don't have Java installed. Are there ways you can make this experience better? Maybe the prompt is not an error, but instead says some of the features are not available unless you install Java? Can a subset of features be available if the user doesn't want to install Java?

**Comment by bubba** [comment]
Hi, we also recently published [an official Haskell extension](https://marketplace.visualstudio.com/items?itemName=haskell.haskell) under the Haskell organisation, would it be possible to recommend users to this for `.hs` files as well? It requires one of the GHC, Cabal or Stack build tools to be installed but we display messages with links to install them if they are not found. Asides from that there are no other prerequisites.

**Comment by chrisdias** [comment]
@bubba please open a new issue here to track the Haskell extension request.
