### ISSUE TITLE
Problems tab badge/count appears/disappears for no apparent reason

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#63019]
Sometimes I see counts of problems in a badge next to the Problems tab (38 here):

![screen shot 2018-11-13 at 11 42 15 am](https://user-images.githubusercontent.com/1078012/48411368-47e2d400-e739-11e8-8300-6f7c6e793761.png)

Other times, it does not show:

![screen shot 2018-11-13 at 11 41 51 am](https://user-images.githubusercontent.com/1078012/48411381-503b0f00-e739-11e8-9d75-85911f9615d5.png)
![screen shot 2018-11-13 at 11 41 55 am](https://user-images.githubusercontent.com/1078012/48411382-50d3a580-e739-11e8-8749-79848d3e3802.png)

I can't figure out a pattern to it. Usually when it's not there, I `Reload Window` and once the code is re-analyzed, the count comes back.

**Comment by sandy081** [comment]
@DanTup Are there steps to reproduce it? 

When you see it next time, can you please inspect the DOM and see if the badge exists ?

**Comment by DanTup** [comment]
I don't know how to reliably repro it yet, but I've seen it quite a lot today. The badge is in the DOM but appears to have no count and is `display:none`'d:

<img width="1343" alt="screen shot 2018-11-14 at 4 46 19 pm" src="https://user-images.githubusercontent.com/1078012/48497904-f1ef5880-e82c-11e8-9690-a92b729eff1d.png">

There are errors here from both `tslint` (via the new extension) and from my own Dart plugin.

If I type some bad code while it's in this state (to cause a new error to appear), the badge suddenly appears and fixes itself.

**Comment by sandy081** [comment]
I will try to repro from my side. If you could can you please help me in inspecting. 
If possible have a break point at following line and see where is it going wrong

https://github.com/Microsoft/vscode/blob/c8cbfdad24a3d8a481f83b65401fa6fd63b7658b/src/vs/workbench/parts/markers/electron-browser/markers.ts#L64

This code updates the badge.

**Comment by DanTup** [comment]
Seems like that code is not being hit. I seem to be able to repro really easily - if I select the `Output` pane, then run `Reload Window`, then cause an error - then  badge doesn't update. If I've ever shown the `Problems` pane before causing it, then the badge does appear.

Is there anything that might be lazy that doesn't happen until the problems list has been shown?

**Comment by sandy081** [comment]
@DanTup I can reproduce it too. Thanks for the step.

**Comment by sandy081** [comment]
Steps to Verify:

- Open VS Code
- Open any panel other than Problems panel
- Reload VS Code
- Open a file and generate errors

🐛 Badge is not updated in Problems panel.

**Comment by DanTup** [comment]
Fix LGTM, thanks!
