### ISSUE TITLE
Clicking on error message from debug console is not setting up pointer at line number all the time. 

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#6301]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows10

Steps to Reproduce:
1. Launch app and open folder for Basic Node js express project.
2. Start debugging and verify debug console.
3. Click on any error message showing up in the debug console to get exact line number.
4. Navigate to different error message and verify it should set the pointer correctly.

**Actual:** When navigating to different error message and going back and forth from one error message to other then mouse pointer is not setting up all the time.
**Expected:** When user navigate to different error message then mouse pointer should be set all the time at correct location.
![debugconsolepointersetissue1](https://cloud.githubusercontent.com/assets/17735796/15200253/f132a944-1799-11e6-832c-5a026ba6ea87.gif)

**Comment by isidorn** [comment]
No action planned to fix this. Will look into if more users complain.

**Comment by aleksey-bykov** [comment]
+1 complaint

the mother VS supports clicking at  the error messages if they are formatted in a proper manner so that at clicking VS navigates you to a place mentioned in the error

I MISS THIS FEATURE!

**Comment by aleksey-bykov** [comment]
related https://github.com/Microsoft/vscode/issues/6619

**Comment by ashleybrener** [comment]
+1 complaint

**Comment by isidorn** [comment]
Reopening

**Comment by isidorn** [comment]
Fixed by @felixfbecker
