### ISSUE TITLE
1.29.0 "files to exclude" in Search not working

### ISSUE THREAD

**Issue by adzchappers** [Microsoft/vscode#63015]
Just updated to 1.29.0 and the "files to exclude" in the search bar isn't working.

Before the update I could just put in a folder name: ./app and this would exclude the app folder, since the update this isn't working, and is being ignored.

Appears that if I select the "Use Legacy Search" option, then this fixes it. However, this is stated as being legacy/deprecated so would appreciate a better solution.

I am using Mac macOS Mojave 10.14, connecting to a network drive running Linux Ubuntu 16.04

Thanks, Adz

**Comment by roblourens** [comment]
I think `app` should still work (although it will exclude `**/app/**`)

**Comment by adzchappers** [comment]
Hi, yes putting in just `app` works, however, if I want to drill down any further `app/test` then this would stop this from working, and obviously, I want it to trigger from the root of the project folder I'm in, thus the `./`

Thanks for looking at this :-)

**Comment by roblourens** [comment]
`app/test` should also still work (as `**/app/test/**`) if I understand you correctly
