### ISSUE TITLE
Provide file icon for .code-workspace extension.

### ISSUE THREAD

**Issue by Azarien** [Microsoft/vscode#63016]
Given that workspace files work similar to solutions in other IDEs (so that one can click on workspace file or on a desktop link to workspace file in order to open the workspace), those files - with .code-workspace extension - should have some meaningful icon, instead of generic document icon.

**Comment by misolori** [comment]
Thanks for the suggestion, but per https://github.com/Microsoft/vscode/issues/60699#issuecomment-429208011 we're not tracking file icon requests, so will close this.

**Comment by Azarien** [comment]
This is unfortunate, because I'm not asking for some obscure file type, but a file type specific and important for VSCode itself.

**Comment by misolori** [comment]
It's definitely something we originally discussed but didn't have the proper asset/icon for that file type. It also isn't an icon supported in the [Seti icon theme](https://github.com/jesseweed/seti-ui), which is what we're using in these file types.

At the minimum we could at least match the file type used so it doesn't show a text file icon:

<img width="50%" src="https://user-images.githubusercontent.com/35271042/48444921-250ceb80-e74a-11e8-80bf-f6f2a3d85798.png">
