### ISSUE TITLE
Set root namespace of a project

### ISSUE THREAD

**Issue by ruimaciel** [Microsoft/vscode#63018]
When using VS Code 1.28.2 to work on C# projects, apparently the default root namespace adopted by a project is deduced from the project tree structure.  However, some projects happen to have root namespaces that don't match the projec tree.  It would be nice if VS Code enabled developers to specify the root namespace of a project.

Some online comments mention the existence of an option labelled `RootNamespace` supported by csproj files.  However, the contents of that variable have no effect on VS code commands such as "new C# class". 

It would be very helpful if VS Code offered a way to configure the root namespace of a project, or even the default namespace used in specific folders of a project.  Supporting third-party data sources such as the contents of csproj files would be ideal, but being able to specify this sort of option in the contents of .vscode would work as well.

**Comment by roblourens** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#2675
