### ISSUE TITLE
No fallback for css script that fails to load

### ISSUE THREAD

**Issue by sigalvo** [Microsoft/vscode#63012]
\If the scripts are loaded from CDN and it's down, there won't be a fallback to the fallback path from requirejs config.
I see the following comment in the code: “In IE there is no way to know if the CSS file loaded successfully or not.”
This is not accurate. Since we can know whether the CSS was loaded successfully be validating that stylesheet.cssRules.length > 0 in the onload callback.

Thanks,
Violet.

**Comment by alexandrudima** [comment]
@sigalvo Can you please follow the template we have for reporting issues? What is the actual problem here? What steps do you take? What is expected and what actually happens?

**Comment by sigalvo** [comment]
Hi,
The problem:
When CDN is down, Monaco editor css file download fails.

Steps to reproduce:
1. Download editor.main from CDN path: https://applicationanalytics-aimon.azureedge.net/vs/editor/editor.main.js?_b=3f923
2. CDN breaks and no more content can be loaded from the CDN
3. Monaco editor loader tries to load editor.main.css from the editor's base url:https://applicationanalytics-aimon.azureedge.net/vs/editor/editor.main.css?_b=3f923
and since CDN is down, this call fails
4. No style is loaded for the editor

The expected behavior:
 To have an option of a fallback base url so that if the css file download fails, Monaco code will try to load the css from the fallback url

What happens now:
Monaco css files aren't downloaded at all when CDN is down.

Our customers reported this issue a few times.
Let me know is you need more information.

Thanks,
Violet.
