### ISSUE TITLE
Multiple windows message boxes

### ISSUE THREAD

**Issue by baruchiro** [Microsoft/vscode#63023]
Issue Type: <b>Bug</b>

In my PC, I launch 2 instances of VSCode, and each 10 minute, one of the instances get stucked.
If I delete a file from VSCode, or check for update, the Windows MessageBox show some times.

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:47:15.448Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460S CPU @ 2.90GHz (4 x 2893)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (3.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
vbscript-language-server-client|and|1.0.3
code-gnu-global|aus|0.2.2
path-intellisense|chr|1.4.2
asp-classic-with-jscript|dar|1.3.1
vbscript|Dar|1.0.4
vscode-markdownlint|Dav|0.21.0
jshint|dba|0.10.20
vscode-eslint|dba|1.7.0
jupyter|don|1.1.4
xml|Dot|2.3.2
gitlens|eam|8.5.6
prettier-vscode|esb|1.7.2
auto-close-tag|for|0.5.6
code-runner|for|0.9.5
gc-excelviewer|Gra|2.1.26
beautify|Hoo|1.4.7
classic-asp|ili|0.0.4
classic-asp-html|jtj|0.1.0
vbscript|kar|0.5.5
csharpfixformat|Leo|0.0.76
VBScript|lug|0.0.2
Kotlin|mat|1.7.0
rainbow-csv|mec|0.8.0
DocFX|ms-|0.1.3
mssql|ms-|1.4.0
python|ms-|2018.10.1
cpptools|ms-|0.20.1
csharp|ms-|1.17.0
github-issues-prs|ms-|0.9.1
Go|ms-|0.7.0
PowerShell|ms-|1.9.0
typescript-javascript-grammar|ms-|0.0.46
vscode-docker|Pet|0.3.1
ruby|reb|0.20.0
java|red|0.33.0
vscode-icons|rob|7.28.0
vba|spe|1.2.0
vscode-vba-icons|spe|1.0.2
code-spell-checker|str|1.6.10
vscode-java-debug|vsc|0.15.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.10.0
vscode-maven|vsc|0.11.1
vscode-todo-highlight|way|1.0.4
plsql-language|xyz|1.6.2
html-css-class-completion|Zig|1.17.1

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Is that the message box that says "the window is not responding"?

Can you try to take a CPU profile while this happens?

https://github.com/Microsoft/vscode/issues/62970#issuecomment-438164153

**Comment by baruchiro** [comment]
Unfortunately, I no longer have the computer.

**Comment by roblourens** [comment]
Will roll this into https://github.com/Microsoft/vscode/issues/62970, please try to provide more details if you see this again.

**Comment by baruchiro** [comment]
The message box "the window is not responding" is not back, but still, when I delete a file, the delete message box appear multiple times.

**Comment by roblourens** [comment]
What do you mean "the delete message box appear multiple times."?

**Comment by bpasero** [comment]
I believe that issue could be https://github.com/Microsoft/vscode/issues/62524 and unrelated to the notification leak.
