### ISSUE TITLE
Debug: unexpected type

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#63028]
Issue Type: <b>Bug</b>

The type is `node`:
![image](https://user-images.githubusercontent.com/9205389/48417550-50e09f00-e753-11e8-96ef-69c3e745a292.png)

VS Code version: Code - Insiders 1.30.0-insider (c72cb129f2a0b8117c9b01f3767026041d7d1d31, 2018-11-13T06:12:08.651Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|-psn_0_9193668|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
unique-lines|bib|1.0.0
dependency|chr|0.0.1
ssh|chr|0.0.4
vscode-eslint|dba|1.7.0
Spot|der|0.4.0
ghlink|dt|1.0.2
remotehub|eam|0.2.0
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.40
git-project-manager|fel|1.7.1
vscode-pull-request-github|Git|0.2.3
rest-client|hum|0.20.3
solidity|Jua|0.0.46
theme-karyfoundation-themes|kar|18.2.1
graphql-for-vscode|kum|1.12.1
vscode-azureappservice|ms-|0.9.1
vscode-azurefunctions|ms-|0.12.0
vscode-cosmosdb|ms-|0.8.0
azure-account|ms-|0.6.1
azurecli|ms-|0.4.2
github-issues-prs|ms-|0.9.1
vsliveshare|ms-|0.3.953
debugger-for-chrome|msj|4.11.0
vscode-docker|Pet|0.3.1
vscode-versionlens|pfl|0.22.0
vscode-workspacecontains-canary|rob|0.0.2
vscode-open-in-github|sys|1.10.0
ayu|tea|0.16.0
azure-iot-toolkit|vsc|1.6.0

</details>

**Comment by pjninnim** [comment]
The popup error of 'Unexpected Type' has been resolved, but after updating today to the latest version, this error has now changed to show the following error in a warning box (bottom right):

Debug adapter process has terminated unexpectedly (Error: Cannot read property 'type' of undefined
{"seq":1,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"exceptionBreakpointFilters":[{"label":"All Exceptions","filter":"all","default":false},{"label":"Uncaught Exceptions","filter":"uncaught","default":false}],"supportsConfigurationDoneRequest":true,"supportsSetVariable":true,"supportsConditionalBreakpoints":true,"supportsCompletionsRequest":true,"supportsHitConditionalBreakpoints":true,"supportsRestartFrame":true,"supportsExceptionInfoRequest":true,"supportsDelayedStackTraceLoading":true,"supportsValueFormattingOptions":true,"supportsEvaluateForHovers":true,"supportsLoadedSourcesRequest":true,"supportsLogPoints":true,"supportsTerminateRequest":false}}
Error: Cannot read property 'type' of undefined
{"seq":1,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"exceptionBreakpointFilters":[{"label":"All Exceptions","filter":"all","default":false},{"label":"Uncaught Exceptions","filter":"uncaught","default":false}],"supportsConfigurationDoneRequest":true,"supportsSetVariable":true,"supportsConditionalBreakpoints":true,"supportsCompletionsRequest":true,"supportsHitConditionalBreakpoints":true,"supportsRestartFrame":true,"supportsExceptionInfoRequest":true,"supportsDelayedStackTraceLoading":true,"supportsValueFormattingOptions":true,"supportsEvaluateForHovers":true,"supportsLoadedSourcesRequest":true,"supportsLogPoints":true,"supportsTerminateRequest":false}}
    at t.handleData (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:374:256)
    at Socket.<anonymous> (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:373:696)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20))

**Comment by weinand** [comment]
@pjninnim I cannot reproduce. What is your setup?
