### ISSUE TITLE
Search very slow

### ISSUE THREAD

**Issue by scosmaa** [Microsoft/vscode#63029]
Issue Type: <b>Bug</b>

After the last update the search is very slow!

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:47:15.448Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (1.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.7.0
es7-react-js-snippets|dsz|1.9.0
gitlens|eam|8.5.6
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.7.2
webpack|jer|2.1.0
vscode-icons|rob|7.28.0
code-settings-sync|Sha|3.2.0
autoimport|ste|1.5.3
vscode-import-cost|wix|2.9.0
JavaScriptSnippets|xab|1.7.1
local-history|xyz|1.7.0

(2 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Can you explain the issue some more?

What are you searching? Is your workspace large?

**Comment by csavtchenko** [comment]
I have been noticing this as well - using `Ctrl + P` - seems to do a deeper search than a simple file fuzzy search. Perhaps I have a bad cache or something? I googled a bit but couldn't come up with a solution.

This is for C++ files on a fairly large code base.

**Comment by csavtchenko** [comment]
I'll be happy to provide an info you need, except the code base :)

**Comment by roblourens** [comment]
ctrl+p should just be searching files, unless you have `search.quickOpen.includeSymbols` enabled. There is no cache.

**Comment by csavtchenko** [comment]
Okay that's good to know - definitely not enabled - definitely very slow. `FZF` is same speed as before so I'm slightly hesitant that it could be a HW issue.

**Comment by roblourens** [comment]
What is FZF? Can you explain the problem some more? Are you on 1.29? Is it slower than 1.28 or just slow in general?

**Comment by csavtchenko** [comment]
`FZF` is a linux tool for fuzzy search. It's very fast - I use it when I'm using `vim` instead of visual studio code.

Typically, I press `Ctrl + P`, I start typing, files immediately appear as the fuzzy search narrows. However, now I press `Ctrl + P` I start typing - I see a "progress toolbar" then they appear. This seemed to happen on the newest update I got from the Ubuntu PPA (1.28.2). C/C++ module is 0.20.1

**Comment by roblourens** [comment]
1.29 just went out, can you try upgrading to that? I think it should be available for ubuntu now?

**Comment by csavtchenko** [comment]
Thank  you - fixed in 1.29

**Comment by roblourens** [comment]
Great, thanks.

@scosmaa more details would be great

**Comment by scosmaa** [comment]
Sure, I'm searching using the search functionality (the project size is normal, not so big not considering node_modules folder and .history folder plugin).

I do search and it's slower than days ago using 1.28 version.

I'll do more research, I want to test if the antimalware service is responsible

**Comment by scosmaa** [comment]
Probably it was my antimalware service, I no longer have the problem, thank you!
