### ISSUE TITLE
Terminal hangs up for specific set of input/output

### ISSUE THREAD

**Issue by irfaan008** [Microsoft/vscode#63024]
Issue Type: <b>Bug</b>

I am running node js command through terminal which is long enough that it takes two line in my case. After execution my code uploads some file on S3 and prints some log information which is lengthy in nature. Once execution finishes, the terminal gets stuck.
If I try to scroll then I can see scroll indicator moving on right but nothing updates on my terminal.

I am able to replicate it everytime I run command 
`BRAND_UUID='some-long-uuid-fdsfsd-r33243' ENV=dev node scripts/upload_menu_to_s3.js up`

If I maximise the terminal at this stage it throws an error in the bottom right saying "Cannot read property 'children' of undefined"

Screenshot : 
<a href="https://ibb.co/eFzPkL"><img src="https://preview.ibb.co/dhPqQL/Screenshot-2018-11-13-at-6-25-36-PM.png" alt="Screenshot-2018-11-13-at-6-25-36-PM" border="0"></a><br />

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|-psn_0_53261|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
php-project|Fro|2.2.0
JSDocTagComplete|Hoo|0.0.2
format-php|Kas|1.1.2
html-snippets|abu|0.2.1
vscode-angular2-files|ale|1.6.2
swagger-viewer|Arj|2.0.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.21.0
vscode-eslint|dba|1.7.0
githistory|don|0.4.3
gitlens|eam|8.5.6
remotehub|eam|0.2.0
tslint|eg2|1.0.40
vscode-npm-script|eg2|0.3.5
apacheconf-snippets|eim|1.1.9
php-debug|fel|1.12.6
php-intellisense|fel|2.3.9
code-runner|for|0.9.5
gc-excelviewer|Gra|2.1.26
vue-snippets|hol|0.1.9
rest-client|hum|0.20.3
composer-support-client|Hyp|0.19.12
gitlab-mr|jas|1.4.1
search-node-modules|jas|1.3.0
react-vscode-extension-pack|jaw|0.4.0
vue|jcb|0.1.5
webpack|jer|2.1.0
Angular2|joh|7.0.1
vscode-phpfmt|kok|1.0.30
code-beautifier|mic|2.1.0
dotenv|mik|1.0.1
vscode-apache|mrm|1.1.1
vscode-pugbeautify|mrm|1.0.2
vsliveshare|ms-|0.3.925
debugger-for-chrome|msj|4.11.0
vscode-json-editor|nic|0.2.0
vscode-extension-auto-import|Nuc|1.4.3
vetur|oct|0.13.0
vscode-docker|Pet|0.3.1
heroku-command|pko|0.0.8
remote-vscode|raf|1.1.0
ruby|reb|0.20.0
vscode-icons|rob|7.28.0
code-spell-checker|str|1.6.10
vscode-react-native|vsm|0.6.18
gitblame|wad|2.6.0
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.7.1
ReactSnippets|xab|2.2.1

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Does this happen in 1.29?

If so can you open the developer tools to get the full stack of that error?
