### ISSUE TITLE
File explorer keeps on opening

### ISSUE THREAD

**Issue by chadidi** [Microsoft/vscode#63021]
Version: 1.29.0 (user setup)
Commit: 5f24c93878bd4bc645a4a17c620e2487b11005f9
Date: 2018-11-12T07:47:15.448Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Steps to Reproduce:

1. Open a File/Folder or save workspace (Happening on most of the items under file tab).
2. choose a file then it will open and the File explorer opens again (when it shouldn't).

**Comment by chadidi** [comment]
After a restart, the bug is fixed, and also it happened after I created a workspace and adding two folders to it. couldn't reproduce it after restarting.

**Comment by bpasero** [comment]
@chadidi can you record a screencast of this issue, having a hard time to understand it from the description.
