### ISSUE TITLE
Moving tab does not change file

### ISSUE THREAD

**Issue by cartond** [Microsoft/vscode#63032]
Issue Type: <b>Bug</b>

Be in a folder, 
Split your window into 2 panes,
Open two files that are in different locations of the folder,
i.e. /proj/x/foo.rb
and /proj/y/bar.rb
If you open a file in the second pane (/proj/y/bar2.rb) and drag it to the first window pane, it will not change the open file in the file explorer on the rail

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:39:38.932Z)
OS version: Darwin x64 18.0.0

**Comment by roblourens** [comment]
I don't quite understand the problem. Isn't the same file open anyway?

**Comment by cartond** [comment]
No, 
Pane 1:  /proj/x/foo.rb
Pane 2: /proj/y/bar.rb and /proj/y/bar2.rb

When you have the bar2.rb file selected it shows in the finder pane on the left correctly. When you drag it to the first pane, it shows /proj/x/foo.rb in the finder pane, even though bar2.rb is the file open.

I will work on getting a gif or something.

**Comment by cartond** [comment]
Here is a gif: [https://imgur.com/a/pt2G9Zz](https://imgur.com/a/pt2G9Zz)

As you can see, when I drag the file from pane 2 to pane 1, it has the original file from pane 1 selected in the file explorer instead of the file that was just dragged and that is currently active.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/61899
