### ISSUE TITLE
panel position toggle button disappeared after October 2018 1.29 update

### ISSUE THREAD

**Issue by luisaccedo** [Microsoft/vscode#63034]
- VSCode Version: 1.29
- OS Version: macOs 10.13.6

Steps to Reproduce:

1. Open vscode
2. View -> Terminal

Does this issue occur when all extensions are disabled?: Yes

**Comment by andgreendigital** [comment]
The release notes can be quite dense! Is this what you are asking about? https://code.visualstudio.com/updates/v1_29#_panel-position-button-to-context-menu

**Comment by NilsJPWerner** [comment]
Can we get this button back? It was really useful, and the right click is not that intuitive.

**Comment by isidorn** [comment]
As designed, sorry we will not bring it back for now as we plan to do a more flexible grid layout of the workbench. The reasoning why we did this can be found in the release notes
https://code.visualstudio.com/updates/v1_29#_panel-position-button-to-context-menu
