### ISSUE TITLE
Traps malware detection breaks search

### ISSUE THREAD

**Issue by chris-kostiw** [Microsoft/vscode#63036]
Issue Type: <b>Bug</b>

Corporate IT requires Traps to be installed on development workstations, https://www.paloaltonetworks.com/products/secure-the-endpoint/traps

Version 1.29.0 is triggering a malware detection error when we try to search (using the Find panel). This breaks search for us.

I'm reporting this, in case it is a real malware problem and not just a false-positive. Rolling back to 1.28 fixes the problem for us. Disabling extensions does not help.

Prevention ID: cde1473e-cbf0-4387-975b-a9f6a12f0091
User ID:
User Name:
Machine name: 
OS Name: macOS
OS Version: OS X 10.13.4
Traps version: 4.2.0.586
Dump path: N/A
Content Version: 37-5038
verdict: 2
Mode: Terminate
Module name: Local Analysis
Date: 11/13/18, 10:31:50 AM
Source Process ID: 6876
Source Process Name: rg
Source Process Path: /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin
Source Process version: 
Source Process Hash: 
Source Process Command-Line: /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --hidden --heading --line-number --color ansi --colors path:none --colors line:none --colors match:fg:red --colors match:style:nobold --ignore-case -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store -g !**/node_modules -g !**/bower_components --max-filesize 17179869184 --no-ignore-parent --follow --encoding utf8 --fixed-strings --no-config --no-ignore-global --json -- test .

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:39:38.932Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (3.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.10
vscode-standardjs|che|1.2.3
angular-schematics|cyr|1.9.0
githistory|don|0.4.3
gitlens|eam|8.5.6
toggle-excluded-files|eam|1.6.0
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.40
vscode-pull-request-github|Git|0.2.3
prettify-json|moh|0.0.3
vsliveshare|ms-|0.3.953
debugger-for-chrome|msj|4.11.0
vscode-versionlens|pfl|0.22.0
ejs-language-support|Qas|0.0.1
stylelint|shi|0.46.1

</details>

**Comment by roblourens** [comment]
Nothing has changed since 1.28 so that's interesting. Is there some way you can whitelist it locally?

**Comment by roblourens** [comment]
Does it give you any other info about what it thinks it detected?

**Comment by chris-kostiw** [comment]
The only other info Traps provides is
```
Application name: rg
Application publisher: MicrosoftCorporation (UBF8T346G9)
Alert description: Attempted execution of locally-detected malware
```
Unfortunately, I cannot reproduce the error this morning. That may be because I am working on a different network today, or because our IT have changed something in our Traps config overnight - I'll try to confirm that with them.

**Comment by chris-kostiw** [comment]
It looks like Traps updated its whitelist - just had to wait for that to happen. The problem has been resolved on our side, so I'm closing this issue.
