### ISSUE TITLE
Intellisense not working well in a yarn project

### ISSUE THREAD

**Issue by wizard982** [Microsoft/vscode#63030]
- VSCode Version: 1.29.0 (system setup)
- Commit: 5f24c93878bd4bc645a4a17c620e2487b11005f9
- Data: 2018-11-12T07:47:15.448Z
- Electron: 2.0.12
- Chrome: 61.0.3163.100
- Node.js: 8.9.3
- V8: 6.1.534.41
- Architettura: x64
- OS Version: Windows 10

CPUs | Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)
GPU Status | 2d_canvas: enabledchecker_imaging: disabled_offflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwarerasterization: enabledvideo_decode: enabledvideo_encode: enabledwebgl: enabledwebgl2: enabled
Memory (System) | 15.92GB (3.51GB free)
Process Argv |  
Screen Reader | no
VM | 0%

Extension | Author (truncated) | Version
ng-template | Ang | 0.1.10
i18ndiff | Chr | 0.3.2
vs-treeview | DaG | 2.6.0
githistory | don | 0.4.3
tslint | eg2 | 1.0.40
vscode-npm-script | eg2 | 0.3.5
vscode-great-icons | emm | 2.1.44
sass-lint | gle | 1.0.3
svn-scm | joh | 1.45.1
vscode-simple-icons | Lau | 1.8.7
angular-localization-helper | man | 0.2.1
vscode-language-pack-it | MS- | 1.29.2
PowerShell | ms- | 1.9.0
debugger-for-chrome | msj | 4.11.0
material-icon-theme | PKi | 3.6.0
seti-icons | qin | 0.1.3
sass-indented | rob | 1.4.9
autoimport | ste | 1.5.3

I have installed autoimport beacause the intellisense not worked well

I dont' know how to reproduce this bug, i tried to create new yarn project but all seems to work fine, i think that the problem is when an Angular Cli project use yarn.

I dont'have this problem in other workspace and in the workspace that have the problem i can see only the suggestion but when i press enter on my keyboard nothing get imported in file. At same time the editor register one modify action and the crtl+z command take in consideration this action.
For this reason if i try to import one suggested library for ten times and after i try to back before the modificatins i must press ctl+z keys for ten times.

For now i solved this problem deactivating the intellisense support for the specific workspace and installed the autoimport extension (enabled only for the specific workspace).

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Please provide some example code or small example project, along with steps the reproduce the problem
