### ISSUE TITLE
Ability to customize editorHoverWidget.foreground color

### ISSUE THREAD

**Issue by queeniema** [Microsoft/vscode#63039]
Issue Type: <b>Feature Request</b>

There is currently support for `editorHoverWidget.background` and `editorHoverWidget.border`, but no option to edit the foreground color. For one of my dark themes, I would like to change the foreground color to black and the background color to a lighter color (e.g. white), but this isn't possible at the moment. It would be great if this color customization could be supported.

https://code.visualstudio.com/docs/getstarted/theme-color-reference#_editor-widget-colors

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 18.0.0

**Comment by RedBaron97** [comment]
Already implemented this. We are going to make the pull request this week!

**Comment by aeschli** [comment]
Thanks for the PR. Closing this issue and using the PR to track progress.
