### ISSUE TITLE
A new window opened from a localized italian one is not translated

### ISSUE THREAD

**Issue by eddieffe** [Microsoft/vscode#63035]
Issue Type: <b>Bug</b>

installed visual studio code is v1.29.0 in windows 10 64bit.
From a Vscode window with italian language pack installed and showing localized italian menus open a new window from file menu. The new window is not translated and shows english menu.
Right clicking on the visual studio application bar icon and selecting the new window activity does open a new  italian localized menu window

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:47:15.448Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2694)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (3.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|0.8.8
bracket-pair-colorizer|Coe|1.0.60
jshint|dba|0.10.20
gitlens|eam|8.5.6
beautify|Hoo|1.4.7
vscode-language-pack-it|MS-|1.29.2
debugger-for-chrome|msj|4.11.0

</details>

**Comment by chaegumi** [comment]
You can try this website: https://code.visualstudio.com/docs/getstarted/locales.
The same error was found in Simplified Chinese, the setting is "zh-cn", but it didn’t work, when I change to "zh-CN", it works.

**Comment by eddieffe** [comment]
Changing locale from 'it' to 'it-IT' made it work! Thank you chaegumi!
