### ISSUE TITLE
Search inside nested json in Settings GUI

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#63031]
Issue Type: <b>Feature Request</b>

Since **json** input field is not going to be added #62555 at least make it possible to search for all the properties from new Setting GUI. The result should be a link `Edit in settings.json` that scrolls needed property into view.

**Comment by roblourens** [comment]
Do you mean that searching for "foo" should still match values that can't be displayed in the settings UI?

I think this is covered by https://github.com/Microsoft/vscode/issues/56712

**Comment by usernamehw** [comment]
I mean searching for `Default Dark` does nothing. IDK if it's a duplicate of that issue or not
```javascript
{
    "workbench.colorCustomizations": {
        "[Default Dark+]": {
            // ...
        }
    }
}
```

**Comment by roblourens** [comment]
Yes thanks
