### ISSUE TITLE
VS Code integrated terminal disordered $PATH

### ISSUE THREAD

**Issue by janosh** [Microsoft/vscode#63046]
Issue Type: <b>Bug</b>

When I run `echo $PATH` in iTerm (running `zsh`) I get
```
/usr/local/miniconda3/envs/te/bin:/Users/Janosh/.nvm/versions/node/v10.11.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```
whereas VS Code's integrated terminal responds with
```
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/miniconda3/envs/te/bin:/Users/Janosh/.nvm/versions/node/v10.11.0/bin
```
Notice that `/usr/local/miniconda3/envs/te/bin` appears after `/usr/bin`. As a result `python` in VS Code's terminal refers to the macOS system install, i.e. `python --version` gives `Python 2.7.10` while in iTerm the version is `Python 3.6.6`.

Any ideas what could be causing this and how to fix it?

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:39:38.932Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (3.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.7.0
gitlens|eam|8.5.6
prettier-vscode|esb|1.7.2
gc-excelviewer|Gra|2.1.26
vscode-styled-components|jpo|0.0.25
vscode-styled-components-snippets|lXS|1.0.2
markdown-shortcuts|mdi|0.9.0
rainbow-csv|mec|0.8.0
python|ms-|2018.10.1
vsliveshare|ms-|0.3.953
material-icon-theme|PKi|3.6.0
code-settings-sync|Sha|3.2.0
pdf|tom|0.4.1
vscodeintellicode|Vis|1.0.6
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.7.1
markdown-all-in-one|yzh|1.7.0

</details>

**Comment by roblourens** [comment]
Is it different when you start vscode from a terminal?

**Comment by janosh** [comment]
@roblourens Yes, when I start via `code`, `echo $PATH` is the same.

**Comment by janosh** [comment]
@roblourens @Tyriar Let me know if there is any further diagnostics I can help with.

**Comment by Tyriar** [comment]
This happens because vscode launches a login shell to establish a "dev friendly" environment, the terminal then also launches as a login shell which can duplicate these properties. You could try add this setting to see if that helps or otherwise tweak your startup scripts (eg. `~/.bash_profile`):

```json
terminal.integrated.shellArgs.osx: []
```

**Comment by janosh** [comment]
@Tyriar Nice, `terminal.integrated.shellArgs.osx: []` did the trick. Thanks a lot!
