### ISSUE TITLE
Problems tab falsely showing typescript errors

### ISSUE THREAD

**Issue by mcfarljw** [Microsoft/vscode#63041]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
Please give more details about the problem.

**Comment by mcfarljw** [comment]
I guess clicking no thanks opened this issue to the experimental bot things opened the issue? I did not click to submit a new issue.
