### ISSUE TITLE
Add action to move caret by word

### ISSUE THREAD

**Issue by johnmarian** [microsoft/vscode#63045]
Would it be possible to add a keybinding option to move caret by word? i.e. Take the existing `editor.action.moveCarret` bindings and expand them to move by word like the `cursorWord` actions? It would be nice to be able to move selections left/right along a line more than one character at a time.

**Comment by alexandrudima** [comment]
PR welcome

**Comment by whiter001** [comment]
move selections up/down in `editor.action.moveCarret`  would be nice,too
