### ISSUE TITLE
Update fails repeatedly

### ISSUE THREAD

**Issue by KevM** [Microsoft/vscode#63043]
## Version 
```
Version: 1.28.2 (user setup)
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:23:51.859Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

Trying to update VS Code I repeatedly get this dialog. There are no instances running. 

```
If update fails repeatedly, please attach the following log file to a new issue on GitHub:

C:\Users\meeeeee\AppData\Local\Temp\vscode-inno-updater-1542129228.log
```

[vscode-inno-updater-1542129228.log](https://github.com/Microsoft/vscode/files/2577337/vscode-inno-updater-1542129228.log)

**Comment by KevM** [comment]
Hmm I attached the file to the issue but it didn't show up and now the file is gone from my Temp folder.

**Comment by KevM** [comment]
[vscode-inno-updater-1542129228.log](https://github.com/Microsoft/vscode/files/2577361/vscode-inno-updater-1542129228.log)

**Comment by joaomoreno** [comment]
When you say `There are no instances running.`, did you confirm this using the Task Manager?
