### ISSUE TITLE
Search sidebar - misplaced error message

### ISSUE THREAD

**Issue by deader115** [Microsoft/vscode#63049]
Issue Type: <b>Bug</b>

1. Type anything in search text box
2. Type a ```\``` in the files to exclude box (this may work with other invalid characters)

As of latest version, \ cannot be used in exclude which is fine (was excluding a directory with this notation previously). However, when the dangling \ is in the "files to exclude" box, the UI error instead shows for the top textbox. I would expect the error to point to the textbox it actually occurs in.

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:46:32.773Z)
OS version: Windows_NT ia32 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (9.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|9.1.0
npm-intellisense|chr|1.3.0
gitignore|cod|0.5.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.7.0
githistory|don|0.4.3
gitlens|eam|8.5.6
vscode-html-css|ecm|0.2.0
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.40
vscode-npm-script|eg2|0.3.5
Angular2|joh|7.0.1
csharp|ms-|1.17.0
team|ms-|1.144.1
debugger-for-chrome|msj|4.11.0
vscode-icons|rob|7.28.0
code-spell-checker|str|1.6.10
shell-launcher|Tyr|0.2.0

</details>

![image](https://user-images.githubusercontent.com/45014320/48436126-3ef30200-e73b-11e8-94f8-6cd035a48806.png)

**Comment by roblourens** [comment]
Errors usually can't be resolved to a particular input box so we don't try. But this syntax should work.

**Comment by deader115** [comment]
Fair enough, I had a suspicion that behind the scenes this is basically just a single object, making it hard to break apart. Sorry for not understanding that intent. 

On the bright side, glad I could help perhaps spot another issue. I simply took off the / and it met my needs so I just assumed it was a slight syntax cleanup.
