### ISSUE TITLE
Terminal position button disapeard in 1.29

### ISSUE THREAD

**Issue by HotscriptGG** [Microsoft/vscode#63048]
- VSCode Version: 1.29
- OS Version: Linux

Steps to Reproduce:

1.Turn on integrated terminal
2. Try to click terminal position button (bottom/side switcher)

It is not there.

![Image of VS Code terminal](https://i.imgur.com/6iwvfam.jpg)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/63034
