### ISSUE TITLE
Ctrl+P search crashing on 1.29.0

### ISSUE THREAD

**Issue by EklipZgit** [Microsoft/vscode#63047]
Issue Type: <b>Bug</b>

Same as #60672
The issue has been fixed since the original issue linked above was patched, however without adding anything new to my workspaces the issue returned immediately after updating to 1.29.0.

  "search.useLegacySearch": false
  "searchRipgrep.enable": false
  "search.useRipgrep": true

EDITING:
To be totally clear here (since the original issues description talks about a lot of stuff), what I am specifically referencing is the behavior where you press Ctrl+P on a large, multi-folder workspace, start typing, and then sometimes instead of seeing search results, the whole VSCode window freezes up as in the previous tickets screenshot until the hung-reopen prompt pops up and VSCode must be reopened.

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:47:15.448Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.79GB (5.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.3
gitlens|eam|8.5.6
PowerShell|ms-|1.9.0

</details>

**Comment by roblourens** [comment]
I can repro this in 1.29. But somehow I can repro it in 1.28.2? But it seems to be a slightly different set of steps than the original 1.28.2 issue.

**Comment by roblourens** [comment]
I pushed a change which I think will help, would appreciate if you can test this in tomorrow's Insiders.

Probably won't push this to 1.29.1 unless there is another flood of people reporting the same.

**Comment by EklipZgit** [comment]
@roblourens is this still in the insiders build? I can test it. I'm seeing the issue fairly consistently, although it does not appear entirely the same as before. Sometimes I get a 5+ second hang that unhangs, and then other times the hang continues to the reopen prompt.

**Comment by roblourens** [comment]
Yeah it's just in Insiders. Are you saying you're still seeing it in insiders? Or 1.29.1?

**Comment by EklipZgit** [comment]
1.29.1. Trying insiders now

**Comment by EklipZgit** [comment]
Haven't really been able to repro it in either 1.29.1 or Insiders since last comment. Not sure why, I haven't changed anything on my end. I will say, there are a lot more instances of delayed Ctrl+P searches than before though (where the blue loading bar idles across the search box but no search results show up for ~5-8 seconds). I almost never saw this pre-1.29. Sorry I don't have anything more concrete for you

**Comment by roblourens** [comment]
Do you see the Antimalware service acting up when you search? Got https://github.com/Microsoft/vscode/issues/63070 too

**Comment by EklipZgit** [comment]
@roblourens yeah, finally had task manager open when I got one of the initial slowdowns (not hangs), and indeed saw antimalware service executable using 80% CPU. Haven't correlated it to the crashes though as they don't seem to be happening anymore despite me changing nothing...

**Comment by EklipZgit** [comment]
@roblourens last update, when the crash happens (not a slowdown), antimalware service is NOT acting up. The crashes are super rare, this is the first in over a week.

**Comment by roblourens** [comment]
By "crash" you mean "hang", right? I don't have any other ideas unfortunately 🤷‍♂️

**Comment by isidorn** [comment]
Adding verified based on user commenting he is no longer seeing it
