### ISSUE TITLE
Previous run stuck

### ISSUE THREAD

**Issue by marco-ms** [Microsoft/vscode#63059]
Issue Type: <b>Bug</b>

New version stuck after some up time.

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:42:27.562Z)
OS version: Linux x64 4.15.0-38-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2251)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 3, 2|
|Memory (System)|23.29GB (6.52GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.3
project-snippets|reb|0.5.0
code-spell-checker|str|1.6.10
gitblame|wad|2.6.0

</details>

**Comment by roblourens** [comment]
See https://github.com/Microsoft/vscode/issues/62970, it would be great if you can capture a cpu profile.

**Comment by jrieken** [comment]
> New version stuck after some up time.

Is that when focusing back from another window or while typing or else how using the editor?
