### ISSUE TITLE
Opening two projects in two windows results in infinite loop of reloading

### ISSUE THREAD

**Issue by aechan** [Microsoft/vscode#63058]
- VSCode Version: 1.29.0
- OS Version: macOS 10.14

Steps to Reproduce:

1. Open a project in one window with File -> New Window, File -> Open Recent
2. Open a project in another window with the same steps.

Does this issue occur when all extensions are disabled?: NO

One of the projects was an Ionic project and the bug seems to stop when I disable [this](https://marketplace.visualstudio.com/items?itemName=loiane.ionic-extension-pack) extension.

Video of the bug occurring [here](https://drive.google.com/file/d/1-8-ofxc4r1ZCvTaCm81NiRmhwNA9RtzW/view?usp=sharing)

**Comment by roblourens** [comment]
That's strange. It would be great if you can also file this on that extension and maybe they can help us understand why they might be causing the window to reload.
