### ISSUE TITLE
save file shortcuts repeat

### ISSUE THREAD

**Issue by 121468615** [Microsoft/vscode#6305]
- VSCode Version:1.1.0
- OS Version:Windows 10 64Bit

Steps to Reproduce:

1. hot key is same  'S' ,look this image

![qq 20160512093417](https://cloud.githubusercontent.com/assets/6504537/15201576/1bf69380-1825-11e6-86b4-a494e8b41ee4.png)

2.

**Comment by bpasero** [comment]
thanks, this was reported already.
