### ISSUE TITLE
Not getting any import intellisense with JavaScript and Vue single-file-components

### ISSUE THREAD

**Issue by ryancole** [Microsoft/vscode#63053]
Issue Type: <b>Bug</b>

I'm not getting any import file suggestions when importing from within a Vue single-file-component. This is the code that goes inside of a `.vue` file, within the `<script>` block. Importing a file does not seem to trigger or produce the file suggestion drop-down.

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:47:15.448Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700 Eight-Core Processor           (16 x 2994)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.95GB (23.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.7.0
prettier-vscode|esb|1.7.2
vetur|oct|0.13.0
material-icon-theme|PKi|3.6.0

</details>

**Comment by octref** [comment]
Please try https://github.com/octref/veturpack, get a repro case and create an issue in https://github.com/vuejs/vetur.
