### ISSUE TITLE
Passing arguments in from CLI to Code's terminal window

### ISSUE THREAD

**Issue by codiddle** [Microsoft/vscode#63056]
I currently have an automated way to start Visual Studio 2017 and run the debugger.  Now what I'd like to do, is after waiting a variable amount of time, to start Visual Studio Code with command line arguments I can pass into the terminal using the Arguments property on ProcessStartInfo.  For example, the following is my C# code:
```

var pathToBranch = ConfigurationManager.AppSettings["PathToBranch"];
var userName = ConfigurationManager.AppSettings["UserName"];
var vsProcess = Process.Start(new ProcessStartInfo
{
     FileName = @"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\devenv.exe",
     Arguments =  $@"""{pathToBranch}some.sln"" /Run"
});

Thread.Sleep(27000);

var vsCodeProcess = Process.Start(new ProcessStartInfo 
{
     FileName = $@"C:\Users\{userName}\AppData\Local\Programs\Microsoft VS Code\Code.exe",
     Arguments = $@"""{pathToBranch}somePath\"""
});
```
The problem I have is I do not have a way to enter "npm start" into the terminal as a command.

**Comment by codiddle** [comment]
I mean, it would be nice if the command `Arguments =  $@"""{pathToBranch}somePath"" /Run 'npm start' "` was supported here as well.  There maybe a way to pass arguments I'm not aware of, but after the research I did 2 months ago I could not find a clear way of doing this.  If there is a way, I'm open to other routes of obtaining the same result.

**Comment by roblourens** [comment]
Do you want to enter a command in the terminal, or do you want to start the vscode debugger (more equivalent to what I guess VS `/Run` is doing?)

**Comment by codiddle** [comment]
/Run would be awesome, I just assumed it is all CLI behind the scenes.  When I first started to try this out, I was executing the code command, trying to pass the terminal arguments but was unable to get that to work, so instead I changed it to use the Process class, since it's a little cleaner and works without the need to keep a command prompt open.

**Comment by isidorn** [comment]
If you would like to find the duplicate go through our issues tagged with feature-request and debug
