### ISSUE TITLE
Apply `mouseWheelScrollSensitivity` in some other places

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#63051]
Issue Type: <b>Feature Request</b>

Having usual OS sensitivity of scroll 9 lines or `"editor.mouseWheelScrollSensitivity": 9,` it's probably good that `quick pick`, `file explorer` etc. ignore it, but some  custom vscode editors that very similar to ordinary ones, like: `Keybindings GUI`, `Settings GUI`, `Interactive Playground` don't have minimap to drag it easily and they are usually long if not using search.

Would it be possible to use configured sensitivity on them?

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/37727
