### ISSUE TITLE
PSScriptAnalyzer false detection of implicit aliasing

### ISSUE THREAD

**Issue by paulmellors40** [Microsoft/vscode#63054]
Issue Type: <b>Bug</b>

Create an object with a property name that has a space and starts with Location.
Then reference this property. eg
$HREmp.{Location Long Desc}
This will then get incorectly detected as a code problem with the message:
'Location' is implicitly aliasing 'Get-Location' because it is missing the 'Get-' prefix. This can introduce possible problems and make scripts hard to maintain. Please consider changing command to its full name. (PSAvoidUsingCmdletAliases)

Whilst having property names with spaces is not ideal it is sometimes necessary when working with 3rd party data

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.16299

**Comment by roblourens** [comment]
This issue was moved to PowerShell/vscode-powershell#1612
