### ISSUE TITLE
Expose a terminal's creation options as API

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#63052]
Right now when a terminal is created the `onDidOpenTerminal` event fires providing the ref to the `terminal` created.

This information is crucial for the Python Extension when activating the Python Environment in the terminal.

Note: Each workspace folder can have different python environments, hence the workspace folder Uri is necessary when identifying the python environment that needs to be activated.

**Suggestion**: Add `workspaceUr` or `cwd` to the `Terminal` object.

**Comment by Tyriar** [comment]
Well terminals aren't bound to workspaces and we can't expose a dynamic cwd, how about this?

```ts
export interface Terminal {
  readonly initialCwd: string;
}
```

**Comment by DonJayamanne** [comment]
That's perfect, yes I agree with your comment.

**Comment by Tyriar** [comment]
@DonJayamanne if https://github.com/microsoft/vscode/issues/46696 worked in multi-root workspaces would that also fix the problem?

**Comment by DonJayamanne** [comment]
Unfortunately no.

**Comment by Tyriar** [comment]
@DonJayamanne you need to do more than just set the python version on the path, like run some script to set up virtual env or something?

**Comment by DonJayamanne** [comment]
> like run some script to set up virtual env or something?

Yes, thats right.

**Comment by Tyriar** [comment]
Adding to October for discussion, this won't be implemented in October.

**Comment by Tyriar** [comment]
I discussed this at the API meeting today, instead of exposing an `initialCwd` property on Terminal we could make it more generic and just expose the options object used to create the terminal:

```ts
export interface Terminal {
	creationOptions: TerminalOptions | ExtensionTerminalOptions;
}
```

**Comment by Tyriar** [comment]
We should use `Readonly<...>`

**Comment by Tyriar** [comment]
@DonJayamanne I'd like some feedback/validation before promoting this to stable, if the idea is validated then we can look at promoting it to stable for December.

**Comment by DonJayamanne** [comment]
Woo hoo. Perfect. Validated, thanks

**Comment by Tyriar** [comment]
To verify:

1. Create an extension that logs `creationOptions` for each `Terminal` in `vscode.window.terminals` whenever a terminal is created via `onDidOpenTerminal`
2. Create some terminals using normal means, `createTerminal` and another extension and verify `creationOptions` looks correct.

**Comment by connor4312** [comment]
I tried this. I do see the creation options, but the cwd is undefined when creating a terminal via the `+` button, in both single root and multiroot workspaces. I would expect this to be set to the relevant workspace folder.

![](https://memes.peet.io/img/20-01-d4c643bd-b770-444a-8fc5-0779ca9d979d.png)

**Comment by Tyriar** [comment]
@connor4312 are you sure it's not working in multi-root workspaces? It's undefined in single root workspaces for me, which means open the default cwd, but for multi-root it always sets it as a URI? Are you by chance using this command?

<img width="393" alt="Screen Shot 2020-01-30 at 4 57 46 AM" src="https://user-images.githubusercontent.com/2193314/73451697-17c32900-431d-11ea-8172-1014c354d904.png">

It is expected to come through as undefined for that as well.

**Comment by connor4312** [comment]
Okay, if that's expected then I think we're good 🙂

**Comment by Tyriar** [comment]
Thanks, it is an important edge case for extensions to consider, my hope is that it's understood as those terminals were created just like a call to createTerminal when cwd is undefined.
