### ISSUE TITLE
Color completions showing generic icon

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#63062]
Issue Type: <b>Bug</b>

**Repo**
1. In a css file:

```css
.a {
    color: r|
}
```

1. Trigger completions at the `|`

**Bug**
Suggestions for colors like `red` have a generic color icon instead of the actual color:

![screen shot 2018-11-13 at 3 06 40 pm](https://user-images.githubusercontent.com/12821956/48449085-014fa280-e756-11e8-851e-367485189c5a.png)

VS Code version: Code - Insiders 1.30.0-insider (c72cb129f2a0b8117c9b01f3767026041d7d1d31, 2018-11-13T06:12:08.651Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 3|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|22%|

</details>Extensions disabled

**Comment by mjbvz** [comment]
This line is failing:

https://github.com/microsoft/vscode/blob/master/src/vs/editor/contrib/suggest/suggestWidget.ts#L160

`suggestion.documentation` is a markdown string here, not a `string`

**Comment by octref** [comment]
Color codes show up fine for me, named colors don't. I guess it's related to changes in suggest widget.

**Comment by octref** [comment]
![image](https://user-images.githubusercontent.com/4033249/48450111-db2c0180-e759-11e8-83f7-7e7258916be8.png)

**Comment by jrieken** [comment]
This is a regression from us making things more markdown'ish by default...
