### ISSUE TITLE
With two editor groups, open "already-split" things like settings.json or git diffs across the two parent groups

### ISSUE THREAD

**Issue by cd-rum** [Microsoft/vscode#63060]
Instead of further splitting things like `settings.json` into smaller groups when two editor groups are already open like so:

![image](https://user-images.githubusercontent.com/12165422/48447195-5a1f4980-e7ef-11e8-866f-16ff2932a115.png)

How about a setting to "use" the already allocated parent groups to open settings like so:

![image](https://user-images.githubusercontent.com/12165422/48447277-9ce12180-e7ef-11e8-9cd6-332d9313c03b.png)

Same for git diffs and the like.

![image](https://user-images.githubusercontent.com/12165422/48447342-c437ee80-e7ef-11e8-876d-29c53cc626bd.png)

Because confining split views to one group makes it harder to read.

**Comment by roblourens** [comment]
Not sure how well this would work in all grid scenarios

**Comment by sbatten** [comment]
@joaomoreno has this ever been suggested before? I like the idea, but as I understand it, these split views aren't quite the same as our editor groups.

**Comment by joaomoreno** [comment]
The settings editor, the diff editor, the keybindings editor... these are all special editors which require two editors open at once. It's a big investment in making them play nicely with the grid (or whatever layout scheme we have). This will very likely never happen. cc @bpasero @sandy081

**Comment by cd-rum** [comment]
What if it's just in a new window outside the grid?

**Comment by roblourens** [comment]
We don't support multiple windows right now

**Comment by drorata** [comment]
Another possible workaround could be to allow the split group (like setting or git diff) be given a full width horizontal split?
