### ISSUE TITLE
Reload loses unsaved changes

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#63064]
Issue Type: <b>Bug</b>

- Create untitled file and write some code
- Make some edit in an existing file
- Reload
- Both changes are forever gone

Empty settings. The default should be either asking if the unsaved files should be saved, or using hotExit. None of that is happening.

1.28 would restore both file changes.

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:39:38.932Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.65GB free)|
|Process Argv|--extensionDevelopmentPath /Users/octref/Library/Application Support/Code - Insiders/User/workspaceStorage/87133f68688d74b85b46cb331d1a2bda/octref.sfe/ext|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by roblourens** [comment]
I don't repro

**Comment by octref** [comment]
@roblourens Are you on Mojave?

**Comment by roblourens** [comment]
Yes

**Comment by joaomoreno** [comment]
@octref Can you maybe run the investigation over there, since @bpasero and @Tyriar are out?

**Comment by isidorn** [comment]
Maybe related https://github.com/Microsoft/vscode/issues/61310

**Comment by octref** [comment]
This does not repro on my home machine, and I tried it again in work laptop:

- This still repros first time I try this morning
- I copied user data dir to `~/Desktop` and ran `code --user-data-dir=~/Desktop/userdatadir`
- I cannot repro it any more
- I launch Code as usual, using the system data dir. I cannot repro any more

My guess is this is related to the storage migration, so it only happens to people who:

- Was using 1.28
- Upgraded to 1.29 and reopened some of the old workspaces

https://github.com/Microsoft/vscode/issues/63109 might be the same thing as my issue. You open an empty workspace, write some code, reload/quit VS Code, and next time you restart all content is gone.

**Comment by octref** [comment]
I tried many more times, but unable to reproduce it. I'll keep an eye on it if it happens again.

**Comment by bpasero** [comment]
@octref I would be surprised if this is due to the storage migration. even if the editor state is not restored, we always fallback to just opening dirty editors in the active group so that the user is able to see them. I feel like in your case you must have hit an actual bug in hot-exit land that would be great to reproduce.
