### ISSUE TITLE
Cannot (easily) expand last object in debug tip

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#63071]
Mac, Insiders

when hovering over a value in break mode, it is very hard to click on the expando triangle to expand the last item listed because it is mostly covered by the horizontal scrollbar.

![image](https://user-images.githubusercontent.com/1487073/48453324-c22a4d00-e767-11e8-8240-bc44b2725e4b.png)

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/59452

Assigning that to november to try to fix
