### ISSUE TITLE
terminal

### ISSUE THREAD

**Issue by cfkis** [Microsoft/vscode#63074]
Issue Type: <b>Bug</b>

Console content always displays only one row at the bottom, and the information is invisible after the command is executed.

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:47:15.448Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (4.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.2.0
copy-relative-path|ale|0.0.2
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.61
doxdocgen|csc|0.4.1
prettier-vscode|esb|1.7.2
auto-close-tag|for|0.5.6
code-runner|for|0.9.5
terminal|for|0.0.10
vue-snippets|hol|0.1.9
debugger-for-chrome|msj|4.11.0
vetur|oct|0.13.0
sass-indented|rob|1.4.9
vue-vscode-extensionpack|sdr|0.1.3
vue-vscode-snippets|sdr|1.3.0
code-spell-checker|str|1.6.10
vscode-status-bar-format-toggle|tom|1.4.0
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.7.1

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Does it look the same as https://github.com/Microsoft/vscode/issues/57803?
