### ISSUE TITLE
code.cmd should wait for output before terminating

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#6307]
Currently `code.cmd` does not wait for output before terminating like `code.sh`. Atom has the same issue in https://github.com/atom/atom/issues/4178

See https://github.com/Microsoft/vscode/issues/5941#issuecomment-218148072

**Comment by Tyriar** [comment]
Actually this probably won't reproduce once looking at the code

**Comment by joaomoreno** [comment]
Did not understand this. What do you mean by *should wait for output*?

**Comment by Tyriar** [comment]
@joaomoreno ignore this, I opened it based on someone comments but I don't think it's actually a problem.

What I meant what `code.cmd --wait` should wait until the process stops before returning.
