### ISSUE TITLE
Insiders(1.30.0) displays Windows 10 buttons on Linux

### ISSUE THREAD

**Issue by lilianmoraru** [Microsoft/vscode#63081]
- VSCode Version: 1.30.0-insider, commit: c72cb129f2a0b8117c9b01f3767026041d7d1d31
- OS Version: Ubuntu 16.04.5 LTS

Steps to Reproduce:

1. Install VSCode Insiders 1.30.0 on Linux

Does this issue occur when all extensions are disabled?: Yes

Screenshot:
1.30.0 Insiders:
![windowscodeinsiders](https://user-images.githubusercontent.com/621738/48458935-01d94f00-e7d1-11e8-8847-620e95b69cf1.png)

Previous versions:
![codeprevious](https://user-images.githubusercontent.com/621738/48459125-cd19c780-e7d1-11e8-963d-39dcde83d540.png)

**Comment by minghuaw** [comment]
Apparently if you go to settings and change the titleBarStyle back to "native", you will get back the original title bar. However, the forground color will be the same as the background color, making the menu texts invisible

**Comment by sbatten** [comment]
@G-Ray thanks for recalling this issue. I've updated its label to reflect that it is on Linux and help re-surface it. 

@lilianmoraru This is the current default we are trying in insiders. Follow @minghuaw 's instructions to revert to the native menu or even better, open new issues regarding your feedback on the new custom menus :)

**Comment by kasru** [comment]
Try use:
`"window.titleBarStyle": "native"`
