### ISSUE TITLE
Option to copy path with "/" forward slahes?

### ISSUE THREAD

**Issue by oodboo** [Microsoft/vscode#6308]
- VSCode Version: Any
- OS Version: Any

Feature suggestion:
Can we add into the config option where you can choose how path slashes will look like after copying.

Currently:
After Right click on file > Copy Path > Paste :

result will look like "c:\foo\bar\again.html"

It would be nice if we could choose option in config e.g:
workbench.action.copyPath.forwardSlash = true/false;
or 
editor.copyPathForwardSlash  = true/false;

so if editor.copyPathForwardSlash is set to "true" result would look like:
"c:/foo/bar/again.html"

**Comment by Tyriar** [comment]
I don't think we'd want customization on this level as Windows paths use `\`, and Unix-like use `/`. While Windows can use `/` in some programs, the correct way is `\`. Perhaps an extension could do this though?

**Comment by oodboo** [comment]
Default option can be "false", for those who like default it will stay default:

editor.copyPathForwardSlash = false;

And this is only for the Explorer > "Copy Path", there is frequent usage of "/" everywhere in coding, angular especially and it is annoying that after copy path we have to go trough manual replacement process.

**Comment by oodboo** [comment]
Actually just saw the last bit, maybe you are right, maybe Extension is better option so Copy Forward Path can be added. 
Ok... I have to check how to create an extension ...
