### ISSUE TITLE
"New" missing under "File" menu

### ISSUE THREAD

**Issue by klins75** [Microsoft/vscode#63087]
Issue Type: <b>Bug</b>

When I look under "File" on the menu, where you would expect to see the option "New", there is no such option.  So I can't start a new workspace or use a template.

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:46:32.773Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) Dual  CPU  E2160  @ 1.80GHz (2 x 1795)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|3.24GB (1.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
javadebugger|don|0.1.5
vscode-html-css|ecm|0.2.0
python|ms-|2018.10.1
java|red|0.33.0
LiveServer|rit|5.1.1
vscode-java-debug|vsc|0.15.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.10.0
vscode-maven|vsc|0.11.1

</details>

**Comment by sbatten** [comment]
@klins75 While I understand the issue is clearly explained, would you mind providing a screenshot of the entire window so I can try to spot anything off?

**Comment by klins75** [comment]
![vsc_screen_shot](https://user-images.githubusercontent.com/33096277/48504309-5cf45b80-e83c-11e8-9885-2c0d40c97dba.jpg)
Normally, there would be a "New" with a drop down menu.

**Comment by sbatten** [comment]
Ah, unlike Visual Studio and other IDEs, VS Code does not provide templates for new projects out of the box. For this reason, we do not have a `New...` button that would go through such a creation process.

**Comment by klins75** [comment]
I have watched people use the new button on tutorials and remember it working before

**Comment by klins75** [comment]
I think I was confused between VS code and Visual Studio.  Thank you for quick help :)
