### ISSUE TITLE
Cannot read property results of null

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#63088]
1.29 Stable

- Open empty workspace
- Cmd + P
- Type something

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/4033249/48461515-fcf0ad00-e788-11e8-8427-d195fc74cf11.png">

**Comment by chrmarti** [comment]
![image](https://user-images.githubusercontent.com/9205389/48469890-38729200-e7f0-11e8-9373-de0f4f55d529.png)

**Comment by chrmarti** [comment]
@roblourens Looks like a recent change in search. Passing over to you.
