### ISSUE TITLE
Error: The gulp task detection didn't contribute a task for the following configuration

### ISSUE THREAD

**Issue by LoneSimba** [Microsoft/vscode#63093]
- VSCode Version: 1.30 (Nov 14 build)
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Clone https://github.com/LoneSimba/RCSE.git
2. (Optional) Change anything in /public_html/themes/RCS/pages/main_template/*.scss
3. Try running "Terminal->Run Task", it will output "Error: The gulp task detection didn't contribute a task for the following configuration" and the rest of it.

Does this issue occur when all extensions are disabled?: Yes

This does not happen on Windows, but always occur on Ubuntu (at least, never tested on other Linux systems). Is there a way over this trouble, or just work with SCSS on Windows?

**Comment by dbaeumer** [comment]
@LoneSimba the reason for this is that under Ubuntu VS Code can't find the gulp command. Do you may be have it installed globally on Windows but not under Ubuntu ?

**Comment by LoneSimba** [comment]
@dbaeumer sorry for not responding, have been busy a little. Gulp is installed both globally and locally on both Win and Ubuntu

**Comment by LoneSimba** [comment]
Decided to check one more time. Globally it wasn't installed ('cause of this: https://github.com/sass/node-sass/issues/1098), but even after installation haven't any success on finding gulp tasks.BTW, even updated to newest version available of insiders

**Comment by dbaeumer** [comment]
@LoneSimba can you provide me with a GitHub repository that demos this?

**Comment by LoneSimba** [comment]
@dbaeumer It's the same with in first post here.

**Comment by alexr00** [comment]
@LoneSimba, check the output from Gulp Auto Detection (in the output pane it's in the dropdown menu). I found a couple issues in there that were easily fixed. In your repo I had the wrong version of gulp-sass installed and gulp.task only takes two parameters.

**Comment by LoneSimba** [comment]
Actually, even in VSCode Task Guide usage of gulp.task with 3 params present. And this composer was based on that guide (but it looked differently in sept). And this code works just fine on Windows PC. So, it's something with Linux version. BTW, this trouble (gulp autodetection) brings arse-pain to lots of users.
If my gulptask.js is wrong, can you show expacle of improving it?

**Comment by alexr00** [comment]
I'll look into the VSCode Task Guide, thank you for pointing it out! I just went through the issues in the Gulp Auto Detection output to see how I could make it work.
