### ISSUE TITLE
Unable to get exception detail under debug-view container with mouse hover.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#6309]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows10

I tried to debug extension and got exception, when I tried to get exception details I observed that exception string is not showing up completely on mouse hove (under debug-view container).

![image](https://cloud.githubusercontent.com/assets/17735796/15206243/7e0a3732-17d2-11e6-91f7-750d3af363ba.png)

Expected:
![image](https://cloud.githubusercontent.com/assets/17735796/15206425/edbb6e42-17d3-11e6-8ed0-7670debe47fb.png)

**Comment by isidorn** [comment]
As designed, this is native chrome behavior that the hover is clipped.
