### ISSUE TITLE
Running the contributed command:'emmet.expandAbbreviation' failed.

### ISSUE THREAD

**Issue by ALNY-AC** [Microsoft/vscode#63090]
Issue Type: <b>Bug</b>

tab

VS Code version: Code - Insiders 1.30.0-insider (c72cb129f2a0b8117c9b01f3767026041d7d1d31, 2018-11-13T06:19:28.504Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (10.55GB free)|
|Process Argv|F:\river\code\company\runbei\website\website-child-admin|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
vscode-eslint|dba|1.7.0
tortoise-svn|fan|0.1.1
code-runner|for|0.9.5
code-beautifier|mic|2.1.0
dotenv|mik|1.0.1
vscode-language-pack-fr|MS-|1.29.2
vscode-language-pack-zh-hans|MS-|1.29.2
debugger-for-chrome|msj|4.11.0
vetur-e|qia|0.11.7
vscode-icons|rob|7.28.0
markdown-all-in-one|yzh|1.7.0

</details>

**Comment by crewone** [comment]
I get the same

**Comment by dmitrykovaltsov** [comment]
+1

**Comment by alexdevero** [comment]
+1

Version: 1.30.0-insider (system setup)
Commit: 5fc60ec67950234cdf82ea455013617adf00e7b6
Date: 2018-11-14T06:20:26.830Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by krokofant** [comment]
Duplicate #63033

**Comment by pkrawc** [comment]
+ 1

`Running the contributed command:'emmet.expandAbbreviation' failed.`

Version: Version 1.30.0-insider (1.30.0-insider)
System MacOS Mojave v10.14.1

**Comment by ramya-rao-a** [comment]
/duplicate #63033

Thanks for reporting everyone, this is being tracked in #63033
Please subscribe to #63033
