### ISSUE TITLE
Markdown link rendering in hovers isn't html encoding properly

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#63095]
Issue Type: <b>Bug</b>

Markdown links aren't getting properly html encoded anymore.
![image](https://user-images.githubusercontent.com/641685/48464692-5f0fd900-e7ae-11e8-956a-3f34353ce032.png)

It was caused by this commit:
https://github.com/Microsoft/vscode/commit/d4116a8f38b2a4c5b68430bb734359b94d768316

I will be submitting a PR with the fix shortly.

/cc @jrieken 

VS Code version: Code - Insiders 1.30.0-insider (c72cb129f2a0b8117c9b01f3767026041d7d1d31, 2018-11-13T06:19:28.504Z)
OS version: Windows_NT x64 10.0.18277

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (19.86GB free)|
|Process Argv|c:\Users\Eric\code\oss\vscode|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by eamodio** [comment]
@jrieken this should be re-opened until my new PR is merged -- as my first "fix" didn't actually fix it :(

**Comment by jrieken** [comment]
lol - don't blindly merge @eamodio's changes...
