### ISSUE TITLE
1.29.0 is soo slow

### ISSUE THREAD

**Issue by ZSH-HSZ** [Microsoft/vscode#63099]
It takes up a lot of memory, at first i thought my computer was broken

**Comment by Kcko** [comment]
Takes up a lot of memory, my cpu fan is spinning like a *****,  ctrl + p is very slow,

1.29 = real HELL!

**Comment by joseph1125** [comment]
duplicate of #62970

**Comment by roblourens** [comment]
Please provide more details. Is search slow? Do you see lots of rg processes? Is the window hanging? As many details as possible please.

**Comment by PavelFranta** [comment]
since 1.29 everything is horrible... even if I want to run basic commands from terminal (like: ng s ) it sometimes take more than 10s to start compiling ) ... and intellisence ? I literally can't use it :/

**Comment by Kcko** [comment]
> since 1.29 everything is horrible... even if I want to run basic commands from terminal (like: ng s ) it sometimes take more than 10s to start compiling ) ... and intellisence ? I literally can't use it :/

Probably duplicated #63070

We are still waiting for some meaningful answer.

**Comment by roblourens** [comment]
Since I have no details from @ZSH-HSZ, I am closing this issue. Anyone else can open a new issue if you can provide more details.

**Comment by Carduelis** [comment]
I've experienced freezes with AutoImport plugin. It was trying to scan the project. VSCode bottom bar showed the active "Scanning..." process. I assume it was provided by AutoImport plugin.
So, maybe the reason for the bug: something in this plugin is incompatible with the new version.
