### ISSUE TITLE
language aware auto indent

### ISSUE THREAD

**Issue by mityukov** [microsoft/vscode#63097]
Issue Type: <b>Bug</b>

There are couple of examples, one in PHP, another one in JS:
```
// PHP code:

    DB::table('my_table')
        ->select([ 'my_field' ])
        ->where('type', 'plain')
        ->get();***cursor is here***
```

```
// JS code:

    $('.my-button')
        .on('click', () => alert('Clicked');***cursor is here***
```

In both cases, pressing Enter would make new line indented just like the previous one (col 8). However, it should indent to be matching the line where the "flow-style" construction started (col 4).

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:39:38.932Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|4.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|0.8.8
better-phpunit|cal|1.1.1
compulim-vscode-closetag|Com|1.2.0
vscode-eslint|dba|1.7.0
githistory|don|0.4.3
php-debug|fel|1.12.6
smarty|imp|0.3.0
sftp|lix|1.7.4
php-constructor|Meh|0.1.1
dotenv|mik|1.0.1
php-docblocker|nei|1.6.0
vetur|oct|0.13.0
laravel-blade|one|1.18.0
advanced-new-file|pat|1.2.0
vscode-docker|Pet|0.3.1
code-settings-sync|Sha|3.2.0
vscode-fileutils|sle|2.13.3
bootstrap-3-snippets|wcw|0.1.0
twig|wha|1.0.2

</details>

**Comment by aeschli** [comment]
To implement what you suggest, the indent-on-enter feature would need to be syntax aware.
It needs to find out that the current cursor location is at the end of a statement and then use the indent from the beginning of the statement. 

Our indent-on-enter is currently regex based, meaning it has no language syntax understanding.

**Comment by mityukov** [comment]
But it's not only when you press Enter in the marked position. It's the same if you copy paste anything after that flow construction, if you move line (Opt+Up/Down) to the place right after it and etc.

The rule for next line should be like: "find the _beginning_ of the _whole_ previous command (not just the last line), then indent appropriately to that beginning."
