### ISSUE TITLE
Maximized windows didn't fill the screen when Taskbar use small icons

### ISSUE THREAD

**Issue by LeThiHyVong** [Microsoft/vscode#63091]
Issue Type: <b>Bug</b>

When windows task bar uses small icons, the maximized vscode windows doesn't fill the screen, there an extra line between the taskbar and window. You can see the black line from my wallpaper in this capture.
![capture](https://user-images.githubusercontent.com/19317679/48463427-872f2480-e80e-11e8-9ff2-c3f63191c0d0.PNG)
Other apps have no problem (Foxit Reader)
![capture](https://user-images.githubusercontent.com/19317679/48463497-c9586600-e80e-11e8-8fc4-98e6164c6aaa.PNG)
The problem doesn't relate to windows theme, vscode extension or screen resolution.
When windows taskbar use large icons, vscode window perfectly fit.
My screen is DellE2416H.

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:47:15.448Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.92GB (3.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/52265
