### ISSUE TITLE
VS Code Extension API support for vertical rulers

### ISSUE THREAD

**Issue by abhinavk99** [Microsoft/vscode#63098]
It would be great if there was a way to see the editor's vertical rulers in the Extension API, such as with a list of Ruler objects in the TextEditor object. The Ruler object would just store the character number of the ruler and the color of the ruler.

**Comment by rebornix** [comment]
For the column number of rulers, you can access that from user's config.

**Comment by abhinavk99** [comment]
Thanks, I couldn't see how to access user settings from the Extension API but I'll go through it again.

**Comment by rebornix** [comment]
You can use `getConfiguration(section?: string, resource?: Uri | null): WorkspaceConfiguration` and the config name for this one is `editor.rulers`. I'd like to close this one as we have a good solution here.
