### ISSUE TITLE
Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by pjninnim** [Microsoft/vscode#63107]
Issue Type: <b>Bug</b>

Start the debugger and you get a popup error in a warning box. Error Below.

```
Debug adapter process has terminated unexpectedly (Error: Cannot read property 'type' of undefined
{"seq":1,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"exceptionBreakpointFilters":[{"label":"All Exceptions","filter":"all","default":false},{"label":"Uncaught Exceptions","filter":"uncaught","default":false}],"supportsConfigurationDoneRequest":true,"supportsSetVariable":true,"supportsConditionalBreakpoints":true,"supportsCompletionsRequest":true,"supportsHitConditionalBreakpoints":true,"supportsRestartFrame":true,"supportsExceptionInfoRequest":true,"supportsDelayedStackTraceLoading":true,"supportsValueFormattingOptions":true,"supportsEvaluateForHovers":true,"supportsLoadedSourcesRequest":true,"supportsLogPoints":true,"supportsTerminateRequest":false}}
```
```
Error: Cannot read property 'type' of undefined
{"seq":1,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"exceptionBreakpointFilters":[{"label":"All Exceptions","filter":"all","default":false},{"label":"Uncaught Exceptions","filter":"uncaught","default":false}],"supportsConfigurationDoneRequest":true,"supportsSetVariable":true,"supportsConditionalBreakpoints":true,"supportsCompletionsRequest":true,"supportsHitConditionalBreakpoints":true,"supportsRestartFrame":true,"supportsExceptionInfoRequest":true,"supportsDelayedStackTraceLoading":true,"supportsValueFormattingOptions":true,"supportsEvaluateForHovers":true,"supportsLoadedSourcesRequest":true,"supportsLogPoints":true,"supportsTerminateRequest":false}}
at t.handleData (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:374:256)
at Socket. (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:373:696)
at emitOne (events.js:116:13)
at Socket.emit (events.js:211:7)
at addChunk (_stream_readable.js:263:12)
at readableAddChunk (_stream_readable.js:250:11)
at Socket.Readable.push (_stream_readable.js:208:10)
at Pipe.onread (net.js:594:20))
```
VS Code version: Code - Insiders 1.30.0-insider (5fc60ec67950234cdf82ea455013617adf00e7b6, 2018-11-14T06:20:26.830Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-8150 Eight-Core Processor            (8 x 3901)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.90GB (19.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
stylus|Ala|0.0.4
emojisense|bie|0.4.1
bracket-pair-colorizer|Coe|1.0.61
vue-peek|dar|1.0.2
vscode-eslint|dba|1.7.0
gitlens|eam|8.5.6
php-intellisense|fel|2.3.10
auto-close-tag|for|0.5.6
pug2html|gin|0.0.5
gc-excelviewer|Gra|2.1.26
vs-color-picker|lih|0.7.0
rainbow-csv|mec|0.8.0
vscode-apache|mrm|1.1.1
vscode-cosmosdb|ms-|0.9.0
python|ms-|2018.10.1
azure-account|ms-|0.6.1
vsliveshare|ms-|0.3.954
vsliveshare-audio|ms-|0.1.39
debugger-for-chrome|msj|4.11.0
vetur|oct|0.13.0
vscode-versionlens|pfl|0.22.0
pjwd-minify|PJW|0.0.1
vscode-icons|rob|7.28.0
git-add-remote|sam|0.0.2
vscode-import-cost|wix|2.9.0
JavaScriptSnippets|xab|1.7.1
html-css-class-completion|Zig|1.17.1

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Can you share your launch config?

**Comment by pjninnim** [comment]
@roblourens Sure my launch config is below:

`{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Server",
      "program": "${workspaceFolder}/server",
      "cwd": "${workspaceFolder}",
      "env": {
        "NODE_ENV": "development",
        "PJWD_DEV_ENV": "splitServer"
      },
      "skipFiles": [
        "node_modules/**/*.js"
      ]
    },
    {
      "type": "node",
      "request": "launch",
      "name": "Client",
      "program": "${workspaceFolder}/server",
      "cwd": "${workspaceFolder}",
      "env": {
        "NODE_ENV": "development",
        "PJWD_DEV_ENV": "splitClient"
      },
      "sourceMapPathOverrides": {
        "webpack:///src/*": "${workspaceRoot}/src/*"
      },
      "sourceMaps": true,
      "skipFiles": [
        "node_modules/**/*.js"
      ],
      "outFiles": [
        "${workspaceRoot}/dist/*.js"
      ]
    }
  ],
  "compounds": [
    {
      "name": "Server/Client",
      "configurations": ["Server", "Client"]
    }
  ]
}`

**Comment by Jahtila** [comment]
@roblourens FYI I'm also having the same problem.

**Comment by pjninnim** [comment]
@roblourens I've done some more research and found that is it now just the VS Live Share Audio extension that causes the problem. It works with just VS Live Share installed.

**Comment by isidorn** [comment]
Please file it against that extension.
Thanks

**Comment by pjninnim** [comment]
@isidorn thanks, that's now been done https://github.com/MicrosoftDocs/live-share/issues/1294
