### ISSUE TITLE
TypeScript autocompletion unexpectedly prefers hyphens

### ISSUE THREAD

**Issue by saschanaz** [Microsoft/vscode#63100]
- VSCode Version: 1.29.0
- OS Version: Windows 10

Steps to Reproduce:

Try autocompletion with hyphen-containing members. Here, "type" should appear first rather than second.

![image](https://user-images.githubusercontent.com/3396686/48468819-51029c80-e830-11e8-8286-4f9a9357c80b.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Simple repo:

```ts
const a = {
    x: 1,
    'x-y': 2
};

a.|
```

@jrieken Seems like a suggest sort issue. The entries that TS returns have the same sort text in this case

**Comment by jrieken** [comment]
Yeah, that's weird. A 100%-match should bet a prefix match...

**Comment by jrieken** [comment]
This is what happens: 

* `a.|` and suggestion `x`: nothing will be replaced/overwritten, nothing to score against
* `a.|` and suggestion `x-y`: that suggestion has filter text `.x-y` and replaces `.` so we score `.` against `.x-y` which gives good score

Something similar happens with `a.x` and `a._x_` vs `a_.x_` (_foo_ is the scoring range). Not sure what to do here, the rules are that longer scores are better but in this case it's not visible what being scored against...

**Comment by jrieken** [comment]
@mjbvz When having those bracket-member suggestions TypeScript could return a replace-range for *all* completions so that they all replace the leading dot and hence have the same ranking offset. Not sure what else to do there...

**Comment by jrieken** [comment]
👏 thanks @mjbvz
