### ISSUE TITLE
Integrated terminal not starting WSL for new projects

### ISSUE THREAD

**Issue by shatgupt** [Microsoft/vscode#63103]
VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:47:15.448Z)
OS version: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Create a new folder and start VSCode in there using `Open with Code` right click context menu.
2. Set `terminal.integrated.shell.windows` to `C:\\WINDOWS\\System32\\wsl.exe` or in fact any path in Workspace settings.
3. Start the integrated terminal (Ctrl+`).
4. Powershell starts irrespective of the setting above.
![2018-11-14-01-21-27](https://user-images.githubusercontent.com/2388644/48469992-74383800-e7ad-11e8-84cc-a79df9d77844.gif)

Does this issue occur when all extensions are disabled?
Yes

It **does** work properly with existing projects.

**Comment by alexr00** [comment]
I can repro. passing this on to @Tyriar.
@shatgupt, to work around this for now, you can place your setting in the User Settings instead of the Workspace Settings.

**Comment by Tyriar** [comment]
This is a security feature, run this command to get it working:

![image](https://user-images.githubusercontent.com/2193314/49314067-20606b00-f49e-11e8-8e25-d3817a32c505.png)
