### ISSUE TITLE
activeDebugConsole.append() does not work on Version: 1.29.0

### ISSUE THREAD

**Issue by ccc159** [Microsoft/vscode#63114]
Version: 1.29.0 (system setup)
Commit: 5f24c93878bd4bc645a4a17c620e2487b11005f9
Date: 2018-11-12T07:47:15.448Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

After updated to latest version 1.29.0, my plugin which prints output into `DebugConsole` using `activeDebugConsole.append()` function doesnot work anymore.

**Comment by isidorn** [comment]
Probably a duplicate of https://github.com/Microsoft/vscode/issues/61986
@ccc159 can you please try to reproduce with latest vscode insiders https://code.visualstudio.com/insiders/

**Comment by ccc159** [comment]
@isidorn Sorry for late reply.

I tried a simple test on the lastest vscode insiders:

If I want to print something into the debug console, I used to just print like this:
![image](https://user-images.githubusercontent.com/15573101/48698394-40af4080-ebe7-11e8-8901-c30b38d845c9.png)

And it should appear in the debug console as it did in the older versions.
![image](https://user-images.githubusercontent.com/15573101/48698493-866c0900-ebe7-11e8-91c8-dcae7e337c63.png)

**Comment by isidorn** [comment]
Thanks for the clarification. However with the introduction of multi debug consoles we have made the debug console read only while debugging is inactive.
So the debug console can only be appended to if there is an active debug session.

Can you also reproduce this if you are debugging? If yes than this is a bug
If no than this is the limitation of our current design.

**Comment by ccc159** [comment]
Thanks for your answer. I see the reason. It is unfortunately not documented in the vscode reference.

I will switch to `OutputChannel` to print messages.

**Comment by isidorn** [comment]
Created this issue to make it clearer https://github.com/Microsoft/vscode/issues/63489
Yeah using an `OutputChannel` makes more sense for your use case.
Thanks!
