### ISSUE TITLE
Split terminal windows directories

### ISSUE THREAD

**Issue by chrisorrick** [Microsoft/vscode#63111]
Issue Type: <b>Bug</b>

In latest version of VSCode, I can no longer have split terminal windows from different working directories like I could previously. I have a workspace set up with multiple directories but can no longer open terminal in the second directory

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:39:38.932Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

**Comment by roblourens** [comment]
You should be able to configure this with the setting `terminal.integrated.splitCwd`

**Comment by alexr00** [comment]
This is configurable using `terminal.integrated.splitCwd`. The default behavior is what you now see. To be able to select the workspace root, set this new setting to `workspaceRoot`.
