### ISSUE TITLE
C# Code Highlighting & IntelliSense not working

### ISSUE THREAD

**Issue by mt-webdev** [Microsoft/vscode#6311]
- VSCode Version: 1.1.0
- OS Version: Win7 SP1

Steps to Reproduce: Create/Open *.cs file/'s in VS Code

VS Code not highlighting C# anymore and IntelliSense for C# also not working anymore at all.

FIXED: Reinstalled C# Extension for VS Code 2-3 times and works again...

**Comment by isidorn** [comment]
Glad reinstalling the C# extension solved your issue
