### ISSUE TITLE
how can i go to the last edit position, same to issue #20165

### ISSUE THREAD

**Issue by ustccw** [Microsoft/vscode#63110]
what i wanted is just to go to last edit position. 
`alt + left array` or `go back` always goto the latest place. 

examples:
edit A file, browser B file, C file, D file to ensure A place, and now i want to goto A edit place for re-edit.
it there a way to make it?

thanks!

**Comment by DTasev** [comment]
I think the command you are looking for `workbench.action.navigateToLastEditLocation`. Rebind it in the keyboard shortcut settings

**Comment by ustccw** [comment]
@DTasev wow! thanks a lot. it works.
