### ISSUE TITLE
"scroll-snap-align" is not supported

### ISSUE THREAD

**Issue by obendev** [Microsoft/vscode#63116]
It seems like `scroll-snap-align` is not supported (Unknown property)
`scroll-margin` and `scroll-padding` are also missing.

![New model](https://developers.google.com/web/updates/images/2018/07/css-scroll-snap/specification-history.png)

- VSCode Version: 1.29
- OS Version: Winows 10 64 Bit

Steps to Reproduce:

1. Create a scss file
2. Write some code with `scroll-snap-align` property

Does this issue occur when all extensions are disabled?: Yes

**Comment by connorshea** [comment]
@octref it was only added 12 days ago: https://github.com/mdn/data/commit/bf1ac6834a2f2defe9d74d8b0ac226d253f7011d

Probably just need to get Mozilla to release a new version :)

**Comment by octref** [comment]
@wbamberg @chrisdavidmills would appreciate a lot if you can make a release! There hasn't been new releases since 2.0.0 in September.

**Comment by octref** [comment]
@wbamberg No worries. Thanks a lot for publishing. I'll pull it in for next release.
