### ISSUE TITLE
Search can't find pch.h in project

### ISSUE THREAD

**Issue by eypsum** [Microsoft/vscode#63115]
- VSCode Version:  1.28 ~ 1.30.0-insider(Latest)
- OS Version: Ubuntu Gnome 16.04.5
- Project: C/C++ project

Steps to Reproduce:
1. Search files using by Ctrl+P
2. Type pch for keyword
VSCode find files like pch.cpp, pch123.h on top  but not pch.h in the project.
VSCode never find pch.h file. 
I don't specify pattern for that in the Exclude filter of the Setting.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Please see the wiki page for this issue first: https://github.com/Microsoft/vscode/wiki/Search-Issues#missing-search-results let me know whether anything in there helps

**Comment by eypsum** [comment]
I found the cause.  that is my .gitignore contains the pch.h file name.
Please close this issue.
Thanks.
