### ISSUE TITLE
VS Code suddenly no longer available in Ubuntu dock while open

### ISSUE THREAD

**Issue by gert7** [Microsoft/vscode#63117]
Issue Type: <b>Bug</b>

In Ubuntu 18.04 the VS Code icon favorited in the taskbar suddenly "closes" but the window itself is open and perfectly fine. I can only get to it through the Activities gesture.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:20:56.183Z)
OS version: Linux x64 4.18.0-11-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3610QM CPU @ 2.30GHz (8 x 1697)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.68GB (1.06GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.7.0
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
vscode-phpfmt|kok|1.0.30
vscode-apache|mrm|1.1.1

</details>

**Comment by Tyriar** [comment]
What do you mean by "suddenly closes", maybe some expected/actual screenshots would help clarify?

**Comment by gert7** [comment]
Only the instance of the dock icon closes. The actual window and program itself is unaffected. This is probably a GNOME 3 related problem.

**Comment by Tyriar** [comment]
@joaomoreno seen this one before?

**Comment by joaomoreno** [comment]
Not really. @gert7 Can you reproduce on 1.29?
