### ISSUE TITLE
Git: Disable smart commit bessage box

### ISSUE THREAD

**Issue by rogermartensson** [microsoft/vscode#63127]
I don't want to commit all the files if no changes are staged. This was implemented many moons ago. Thank you.

Now whenever I commit and miss staging files I get a warning and to be honest, getting rather annoyed at that warning..

So my request is to be able to disable this messagebox and keep enableSmartCommit set to false.

**Comment by joaomoreno** [comment]
So, in that case you'd like Code to not do anything at all?

**Comment by rogermartensson** [comment]
Yes, exactly. I tend to forget to stage changes quite often and do not want to enable commit all changes. I think that "no action" is the correct way. 

The UI (the V) maybe should greyed out (not clickable).

**Comment by skprabhanjan** [comment]
@joaomoreno , I would like to work on this :)
Any Starter points would be helpful.
Thanks :)

**Comment by joaomoreno** [comment]
You'll want to check in `commands.ts`. Find a nice configuration setting name for skipping the message altogether.

**Comment by herecydev** [comment]
I didn't even see that @skprabhanjan had put in a PR (although I started this a few days ago), I did also add in my PR a "Don't remind me" button so that this behavior can be toggled off permanently from the UI.

I was also going to raise a query about a visual change to the commit tick to clarify why a user can't commit.

**Comment by mIkhail-zaretsky** [comment]
Btw, to keep things simple and do not introduce a new setting maybe it is possible to extend states for existing 'git.enableSmartCommit' setting with something like 'not sure, ask me later', so it will be enum ['true', 'false', 'ask']. Then the same scenario with "Always/Never" choice.
Not sure is it too hard to migrate setting type from boolean to enum...

**Comment by aeschli** [comment]
Verified new setting `git.suggestSmartCommit`
