### ISSUE TITLE
Browserwindows opening as subwindows of vscode

### ISSUE THREAD

**Issue by Konrad97** [Microsoft/vscode#63122]
Issue Type: <b>Bug</b>

-open a link from code in vscode with ctrl+click
-now open your standart browser outside of vscode
-the browser window will appear under the vs code section
-close all browser windows in the vscode section
-now open your standart browser outside of vscode
-the browser window will appear under the standart browser section

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:42:27.562Z)
OS version: Linux x64 4.15.0-39-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2481)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|2, 1, 0|
|Memory (System)|15.40GB (11.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
monokai-charcoal-high-contrast|74t|1.0.4
dart-code|Dar|2.20.0
flutter|Dar|2.20.0
bazel-code|Dev|0.1.9
jupyter|don|1.1.4
vsc-material-theme|Equ|2.5.1
nbpreviewer|jit|1.0.0
python|ms-|2018.10.1
cpptools|ms-|0.20.1
markdown-preview-enhanced|shd|0.3.11
cmake|twx|0.0.17
cmake-tools|vec|1.1.2

(3 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
> -the browser window will appear under the vs code section

I'm not sure what you mean by "the vscode section"
