### ISSUE TITLE
Items in outline view do not follow cursor

### ISSUE THREAD

**Issue by werunom** [Microsoft/vscode#63126]
- VSCode Version: 1.29
- OS Version: Linux Manjaro

**Issue** - 
I use vscode for markdown writing. After the latest update, the headings that come in the outline-view do not follow the cursor position. That is, if I move from heading-1 to heading-2 in the editor, in the outline, the heading-2 is not highlighted. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by tormec** [comment]
Version: 1.29.1
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:07:43.495Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

In my case, this issue still persists with php and javascript files whereas it doesn't happen with python file.

I have only three extensions: PHP Debug, PHP IntelliSense and Python. 
I've tried to disable all of them and reload but nothing change.
