### ISSUE TITLE
Not able to find download location for exported plantUML file

### ISSUE THREAD

**Issue by DBDneelam** [Microsoft/vscode#63120]
- VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|plantuml|jebbs|1.4.2|

---

Steps to Reproduce:

1. Create plant uml file
2.Once done with the sequencing
3.Right  on plantUML file and click on "Export Current Diagram"
4.Diagram will get exported but exported location wont be visible on Output window.

**Comment by roblourens** [comment]
This sounds like an issue with the plantuml extension, please file the issue on their repo
