### ISSUE TITLE
Screen cheese for suggest widget

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#63125]
Have the following code sample 
```javascript
var filewalker = require('filewalker');

filewalker('.').on('file', function (p, s) {
	if (s.
	console.log('file: %s, %d bytes', p, s.size);
}).walk();
```
On s. trigger suggest widget. Press cmd + space again to get the docs one.
Screen cheese
![screenshot 2018-11-14 at 12 57 54](https://user-images.githubusercontent.com/1926584/48481182-ee4bd980-e80c-11e8-9ba4-8355159bff12.png)

**Comment by octref** [comment]
I'm not sure I got the point. Locally I tried installing `filewalker`, and `s` is `any` so it shows word based suggestion, right?

**Comment by octref** [comment]
Giving to @ramya-rao-a, although I cannot repro it.

<img width="696" alt="image" src="https://user-images.githubusercontent.com/4033249/48502231-e59ad980-e7f3-11e8-8715-3eacff095a9c.png">

Just right above, I have the fly-out style completion open:

<img width="710" alt="image" src="https://user-images.githubusercontent.com/4033249/48502246-ee8bab00-e7f3-11e8-9074-9a935a2c8437.png">

**Comment by isidorn** [comment]
I already filled an issue like this couple of years ago I believe
might you maybe remember @joaomoreno

**Comment by jrieken** [comment]
I cannot reproduce anymore.
