### ISSUE TITLE
dotnet exited with error code 2147516546

### ISSUE THREAD

**Issue by wenjianzhang** [Microsoft/vscode#6312]
- VSCode Version:1.1.0
- OS Version: win 7

desc:
Error: Failed to load the dll from [C:\Program Files\dotnet\hostfxr.dll], HRESULT: 0x80070057

dotnet exited with error code 2147516546

**Comment by isidorn** [comment]
This looks like an error with the C# extension, can you please file this bug in this repository
https://github.com/OmniSharp/omnisharp-vscode

**Comment by liyunzhi1993** [comment]
vs 2015
win 7 system

Failed to load the dll from [C:\Program Files\dotnet\hostfxr.dll], HRESULT: 0x80070057
![image](https://cloud.githubusercontent.com/assets/6257587/15992900/4952d78c-310a-11e6-9732-6aa021cf4b3b.png)

how to do it?
THX~

**Comment by isidorn** [comment]
@liyunzhi1993 This looks like an error with the C# extension, can you please file this bug in this repository
https://github.com/OmniSharp/omnisharp-vscode

**Comment by qihaibin** [comment]
---------------------------
Microsoft Visual Studio
---------------------------
尝试运行项目模型服务器进程(1.0.0-preview1-002702)时出现以下错误。



无法启动进程。Failed to load the dll from [C:\Program Files\dotnet\hostfxr.dll], HRESULT: 0x80070057



项目模型服务器进程为 Visual Studio 提供了智能感知、生成和参考信息，不使用该进程将使体验严重受限。请尝试关闭并重新打开 Visual Studio，查看是否解决问题。或者，请检查是否正确安装了 .NET Core SDK。
---------------------------
确定   
---------------------------

**Comment by qihaibin** [comment]
@liyunzhi1993 
I encountered the same problem

**Comment by isidorn** [comment]
@qihaibin This looks like an error with the C# extension, can you please file this bug in this repository
https://github.com/OmniSharp/omnisharp-vscode

**Comment by SmallShrimp** [comment]
修改global.json文件 把core的版本引用改为最新的 然后安装的最新的版本 ，我是这样解决的。
