### ISSUE TITLE
vscode v. 1.29 freezes very often

### ISSUE THREAD

**Issue by mateuszgazdziak** [Microsoft/vscode#63132]
- VSCode Version: 1.29
- OS Version: Windows 10 (1803)

Steps to Reproduce:

1. Do stuff
2. After several minutes vscode freezes.

**Comment by filipesilva** [comment]
I also see this on Windows 10, VS Code v1.29.0. Saw it while editing a powershell script. Window hangs until a prompt comes up asking if I want to reopen it because it stopped responding.

Task manager shows VSCode CPU usage at very high percentages (50%) while it is frozen.

**Comment by fusengine** [comment]
<img width="1277" alt="capture d ecran 2018-11-14 a 15 55 13" src="https://user-images.githubusercontent.com/7295655/48490583-07ad4f80-e826-11e8-984d-a6a74282af21.png">

**Comment by filipesilva** [comment]
This issue seems to be a duplicate of https://github.com/Microsoft/vscode/issues/62970. A suggested workaround is to always clear notifications.

**Comment by fusengine** [comment]
> This issue seems to be a duplicate of #62970. A suggested workaround is to always clear notifications.

haha I know and? I need response to why this freezings my Mac?

**Comment by mateuszgazdziak** [comment]
> This issue seems to be a duplicate of #62970. A suggested workaround is to always clear notifications.

Yes, indeed it look like the same issue. I am sorry, I've missed that one.
