### ISSUE TITLE
Ctrl + Open Recent could open the folder in a new Window

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#6313]
- VSCode Version: 1.1.0
- OS Version: any

I constantly see myself doing the following two actions:

- new window
- then select a recently opened folder.

Would either be cool to have a special menu entry for this, make open recent configurable to create a new window or to support Ctrl + Open Recent which does both (my preferred solution)

**Comment by bpasero** [comment]
@dbaeumer what about we add an action to the "Open Recent" list that does just that or implicitly do it when you Ctrl+click on such an entry?

<img width="657" alt="screen shot 2016-05-12 at 11 06 57" src="https://cloud.githubusercontent.com/assets/900690/15209510/a9f1af6a-1831-11e6-9318-fad3f4646329.png">

**Comment by dbaeumer** [comment]
Sorry, was not precise in the description. I am preferring Ctrl+ click on the entry in the menu. 

Silly question: how do I get the list you show in the screen shot. Never saw that.

**Comment by bpasero** [comment]
@dbaeumer as far as I know there is no way of detecting keyboard modifiers while interacting with the chrome menu.

The quick open for recent files/folders is in `F1 -> File: Open Recent`

**Comment by dbaeumer** [comment]
OK. Ctrl+Click in the open recent list would make my day then.

**Comment by bpasero** [comment]
@dbaeumer I wonder if this rather should be a setting instead. are you always wanting to open the folder in a new window if you pick it from the recent list?

**Comment by dbaeumer** [comment]
Yes, I almost always want to open a new window.

**Comment by bpasero** [comment]
#371
