### ISSUE TITLE
[Java] Syntax highlighting not working on multi-line method declaration

### ISSUE THREAD

**Issue by stanleynguyen** [Microsoft/vscode#63137]
Syntax highlighting doesn't detect language component correctly if a method declaration spans over multiple lines. Here is an example (please only take note of the colors)

Expected:
![capture1](https://user-images.githubusercontent.com/12974927/48491000-925f7000-e861-11e8-9682-3e6142dfdbdf.PNG)

Actual:
![capture](https://user-images.githubusercontent.com/12974927/48491010-968b8d80-e861-11e8-8ab8-5b8dfb92ccf3.PNG)

- VSCode Version: 1.29
- OS Version: Both Windows 10 and MacOS Mojave

Steps to Reproduce:

1. Declare a method with signature that's longer than line width limit
2. Save and wait for the formatter to reformat it to multiple lines

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
This issue was moved to atom/language-java#186

**Comment by alexr00** [comment]
Moved to the owning repository since this is an issue with the text-mate grammar that we consume.
