### ISSUE TITLE
Cannot update with AppLocker

### ISSUE THREAD

**Issue by sterid** [microsoft/vscode#63135]
Issue Type: <b>Bug</b>

Hi, VSCode cannot be updated from menu _Help -> Install update_ with enabled Applocker. The reason is unsigned TMP file "%OSDRIVE%\USERS\%username%\APPDATA\LOCAL\TEMP\IS-BOHH9.TMP\CODESETUP-STABLE-5F24C93878BD4BC645A4A17C620E2487B11005F9.TMP (or similar) was prevented from running." You have to use update service (as google chrome) or evaluate permission before starting update. Because not every one is working with administrator rights. 

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (8.64GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.2.0
githistory|don|0.4.3
xml|Dot|2.3.2
filter-line|eve|1.1.0
cisco|jam|1.2.0
python|ms-|2018.10.1
PowerShell|ms-|1.9.0
vscode-icons|rob|7.28.0
code-settings-sync|Sha|3.2.0
vscode-autohotkey|sle|0.2.2
sort-lines|Tyr|1.7.0

</details>

**Comment by roblourens** [comment]
You may want to try reinstalling to get the user-level setup

**Comment by sterid** [comment]
@roblourens this is just a workaround which won't work in SRP|Applocker environment. In additional Applocker is blocking executing EXE files outside ProgramFiles|ProgramFiles(X64)|Windows directories. That behavior is basic of "Microsoft security concept" - running EXE files only from directories where only Administrator have write permissions.  I just want to say using TMP files without signature isn't good solution for updating process. As I noticed update process contains 2 steps: 

- start _%OSDRIVE%\USERS\%username%\APPDATA\LOCAL\TEMP\VSCODE-UPDATE-SYSTEM-X64\CODESETUP-STABLE-5F24C93878BD4BC645A4A17C620E2487B11005F9.EXE_ with digital signature
- extract to temp file like _%OSDRIVE%\USERS\%username%\APPDATA\LOCAL\TEMP\IS-ANF6V.TMP\CODESETUP-STABLE-5F24C93878BD4BC645A4A17C620E2487B11005F9.TMP_ without digital signature

**Comment by joaomoreno** [comment]
These files now have signatures.
