### ISSUE TITLE
Highlight matches in Settings GUI search

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#63133]
Actual:
![screenshot 103](https://user-images.githubusercontent.com/9638156/48488608-392c1800-e832-11e8-930f-645936592308.png)
Expected:
![screenshot 104](https://user-images.githubusercontent.com/9638156/48488615-3f21f900-e832-11e8-990a-08af97ebeb40.png)

**Comment by beastdestroyer** [comment]
I think a background highlight might also be good here
