### ISSUE TITLE
Search stopped following symlinks

### ISSUE THREAD

**Issue by DavidSvetlik** [Microsoft/vscode#63138]
Issue Type: <b>Bug</b>

Hello,

looks like after last update, search within files stopped following folder symlinks.

Thanks for all your great work, by the way. :-)

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:47:15.448Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
calculate|aca|2.1.0
project-manager|ale|9.1.0
vscode-great-icons|emm|2.1.44
svgeditor|hen|2.7.0
vscode-text-pastry|jkj|1.2.0
sublime-keybindings|ms-|4.0.0
debugger-for-chrome|msj|4.11.0
partial-diff|ryu|1.4.0
language-stylus|sys|1.10.0
prettify-selected-json|vth|1.0.3

(3 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Did you set `search.followSymlinks`?
