### ISSUE TITLE
inbuilt Terminal  doesn't show directory name at startup

### ISSUE THREAD

**Issue by ThayalanGR** [Microsoft/vscode#63130]
whenever I open the terminal, it doesn't show any directory name, 
after start typing the command, it turns visible.
steps to reproduce the problem,
open vs code 
open terminal ( Ctrl + ` )
then - 
(it shows a blank  terminal screen without displaying the current directory path)

then-
try to type some command and execute it (say:-  $  ls )

then the directory path is visible.

Thanks,

Images.

![image](https://user-images.githubusercontent.com/35830033/48488088-f8d69500-e845-11e8-9833-b250d866e385.png)
![image](https://user-images.githubusercontent.com/35830033/48488119-0e4bbf00-e846-11e8-9ceb-7d6d21f63559.png) then the directory label is visible.
![image](https://user-images.githubusercontent.com/35830033/48488159-1dcb0800-e846-11e8-9461-3f5ed53bf932.png)

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/57803
