### ISSUE TITLE
Tree: Support sorting

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#63148]
@jrieken Makes a great point that the tree is the best place for sorting a model since it only needs to sort the visible elements.

**Comment by joaomoreno** [comment]
Done!

**Comment by mjbvz** [comment]
@joaomoreno Steps for verification?

**Comment by joaomoreno** [comment]
Just API verification: https://github.com/Microsoft/vscode/blob/27aed2d87a2a94c2f78d4aa2343cabdfa62cb4d7/src/vs/base/browser/ui/tree/tree.ts#L71
