### ISSUE TITLE
Сдвинулись подсказки синтаксиса

### ISSUE THREAD

**Issue by bossonojka** [Microsoft/vscode#63143]
Issue Type: <b>Bug</b>

При увеличении размера шрифта в параметрах, некорректно отображаются подсказки синтаксиса при вводе (сдвигаются влево и накладываются на иконки).

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:47:15.448Z)
OS version: Windows_NT x64 10.0.17134

**Comment by roblourens** [comment]
> When you increase the font size in the parameters, the syntax hints are displayed incorrectly as you type (shift to the left and overlap the icons).

**Comment by roblourens** [comment]
Can you share a screenshot?

**Comment by jrieken** [comment]
I don't know what this should mean.

**Comment by bossonojka** [comment]
![image](https://user-images.githubusercontent.com/36764653/48589371-e5115880-e943-11e8-92a8-58a125980f09.png)

**Comment by jrieken** [comment]
please share you settings and the icon theme you are using

**Comment by bossonojka** [comment]
Themes: Dark+ (default dark), Seti.
![image](https://user-images.githubusercontent.com/36764653/48631822-1895c680-e9c8-11e8-8a53-326c450b6524.png)
