### ISSUE TITLE
Split Terminal in Workspace no longer shows working directory dropdown

### ISSUE THREAD

**Issue by davidluhr** [Microsoft/vscode#63141]
- VSCode Version: Version 1.29.0 (1.29.0)
- OS Version: masOS Mojave Version 10.14 (18A391)

#### Expected Behavior

In previous versions of VSCode, the Split Terminal function would prompt the user with the "Select current working directory for new terminal" dropdown when creating a split terminal inside of a Workspace.

As of the latest update, this is no longer happening.

#### Steps to Reproduce

1. Open a Workspace project with more than one folder
2. Open a New Terminal
3. Open another terminal with the New Terminal command and select an option from the "Select current working directory for new terminal"
4. Open a Split Terminal and observe that the working directory dropdown does not appear (it automatically creates a new terminal in the same working directory without asking)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
This is configurable using `terminal.integrated.splitCwd`. The default behavior is what you now see. To be able to select the workspace root, set this new setting to `workspaceRoot`. Checkout the release notes for a full description of this new setting 😊

**Comment by davidluhr** [comment]
@alexr00 Thank you so much! I read over the release notes originally, but missed the mention of this new setting. Sorry for the false issue and thanks for an amazing product!
