### ISSUE TITLE
Allow a task to execute an extension command

### ISSUE THREAD

**Issue by GabeDeBacker** [Microsoft/vscode#63153]
Our build environment is quite complex and offers more that just console output. For example, information can be obtained by listening to event tracing providers.

As such, our VSCode extension communicates with an out of process server (using JSON-RPC) to perform the build actions in our environment. The extension exposes commands that users must specifically invoke to perform a build action.

The desire is to integrate with VSCode's task infrastructure and have the task infrastructure execute an exposed extension command rather than an external process.

This way, users can use VSCode's user interface as it is currently designed rather than have to locate our extension's commands.

**Comment by dbaeumer** [comment]
Duplicates https://github.com/Microsoft/vscode/issues/11396
