### ISSUE TITLE
Setting to disable all pop-ups

### ISSUE THREAD

**Issue by daniel-livestories** [Microsoft/vscode#63151]
I've seen many, many issues about disabling pop-ups and invariably the creator is satisfied with only _some_ pop-ups being disabled.  But I really do want _all_ pop-ups disabled.  They are annoying, are never informative for my DX, often creating very frustrating experiences as I begin typing only to have my vision obscured.  I have both the recommended settings (`"editor.quickSuggestions": false,` and `"editor.parameterHints": false,`) and I still received many pop-ups.

A setting to prevent any and all pop-ups would be awesome and solidify the VSCode experience for me.

**Comment by roblourens** [comment]
Which popups are you talking about besides parameterHints and quickSuggestions?

**Comment by daniel-livestories** [comment]
Seems like the `editor.parameterHints` flag has changed to `editor.parameterHints.enabled`.  Setting this flag does seem to have removed most pop-ups.
