### ISSUE TITLE
Copy-pasting plain text from VSCode adds formatting (color etc

### ISSUE THREAD

**Issue by alex-jitbit** [Microsoft/vscode#63154]
- VSCode Version:  1.28.2
- OS Version: Windows 10

Steps to Reproduce:

1. Edit HTML file in VSCode, select some text then paste it into any wysiwyg editor (Gmail message box for example)
2. You will see formatting, like on the screenshot

Does this issue occur when all extensions are disabled?: Yes

See the screenshot. It should be plain text without black background and any colors.

![image](https://user-images.githubusercontent.com/33555768/48501708-7a2e2780-e846-11e8-86b7-b7c50e89b1a4.png)

**Comment by rebornix** [comment]
This feature can be turned off by `editor.copyWithSyntaxHighlighting`
