### ISSUE TITLE
Explore improving UX for Welcome Page

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#63152]
This exploration will aim to modernize the look and feel of the Welcome page while also improving the layout for new and current users. Items we're looking to explore:

- Add "privacy" section to page for better visibility
- Add "recently update" section for app and extension updates
- Add underline for text links on hover (consistency)

## Related issues
- Ability to remove recent item #22489
- Ability to pin projects #63057
- Don't open browser on first launch without user's action #14934
- Revisit "Interface Overview" page #19491

## Current Design

![image](https://user-images.githubusercontent.com/35271042/48791391-7a934c00-eca6-11e8-9cb5-abaa01645d78.png)

## Research
Our research shows that new users install language & keyboard shortcut extensions the most, while current users go to recent projects or open folders. Below is a visualization of the top actions.

### Top actions for new users
![new users](https://user-images.githubusercontent.com/35271042/48498898-12e38980-e7ec-11e8-88f8-8b1c85b3a62b.png)

### Top actions for current users
![current users](https://user-images.githubusercontent.com/35271042/48499353-1cb9bc80-e7ed-11e8-80d7-1a543a88659f.png)

I will be updating this issue with explorations as they're developed.

**Comment by beastdestroyer** [comment]
@misolori from my issue at #56144 there was a comment about pinned projects on the welcome screen too.

And also to keep in line with thw rest of VSCode, the hyperlinks should have an underline on hover

**Comment by misolori** [comment]
@beastdestroyer thanks, I've updated the issue to include those two.

**Comment by gulshan** [comment]
Should welcome page contain a link to command for git cloning a repo? IntelliJ and next Visual studio is showing that in their start/welcome page/view.

**Comment by misolori** [comment]
## Explorations

### Exploration A

- Moves Start and Recents to the right
- Adds option to star/remove recent item
- Adds privacy section for telemetry 
- Condenses help links into buttons

![exploration a](https://user-images.githubusercontent.com/35271042/48587503-34c23680-e8e8-11e8-848a-151ca8af5f50.png)

### Exploration B

- Moves Start and Recents into sidebar
- Adds option to star/remove recent item
- Adds privacy section for telemetry 
- Condenses Customize, Learn, Help into tabbed content
- Adds an "Updates" tab to show app & extension updates

![exploration b](https://user-images.githubusercontent.com/35271042/48587562-7b179580-e8e8-11e8-9eed-ed5891ac3376.png)

### Exploration C

- Makes recents two-columns
- Moves Start to the right side
- Adds option to star/remove recent item
- Adds privacy section for telemetry 
- Condenses help links into buttons
- Condenses help links into buttons

![exploration c](https://user-images.githubusercontent.com/35271042/48588171-d185d380-e8ea-11e8-9929-3e2a3f960754.png)

### Exploration D

- Makes Recents and Start into two-columns
- Moves Customize, Learn, Help into large buttons
- Adds option to star/remove recent item
- Adds privacy section for telemetry 
- Condenses help links into buttons
- Condenses help links into buttons

![exploration d](https://user-images.githubusercontent.com/35271042/48588222-0d209d80-e8eb-11e8-8cbf-030ced7ff41b.png)

**Comment by octref** [comment]
I do think Playground is an important part for people to get familiar with VS Code's editing features and should be a part of the welcome experience.

Being able to try the features right in editor is much better than reading docs in a browser and come back to editor.

**Comment by chrmarti** [comment]
I like the focus of C on 'Recent' folders. Is there a good way to use that space when there are no recent folders yet, like on first startup? E.g., by using a subpage switcher like in B.

**Comment by beastdestroyer** [comment]
I like C and D, perhaps sort the buttons on D by category like C, lower that container down so it's centre with everything else, and center the `Show welcome page on startup` checkbox

**Comment by ergometh** [comment]
Seems like the C is the best option. Focus on "Recents" is the best.

**Comment by misolori** [comment]
@chrmarti that's a good idea. We could move the "Help" content up to the recents location when there are no recents, since the users accessing this view would most likely be new users, and then move it back when there are recents:

![exploration C-1](https://user-images.githubusercontent.com/35271042/48638469-9684ae00-e985-11e8-8307-a20c162ab3f8.png)

**Comment by rebornix** [comment]
I prefer D the most and here are my 2 cents. Before I'm super familiar with shortcuts of Open Recent and Open Folder, I used Welcome Page as my dashboard. I bind F2 to command Open Welcome Page and then everytime I just press F2 and then

* Choose a recently opened folder 
* Or open a new folder

But now I no longer do that as I have to switch from the keyboard to mouse to operate on the welcome page. When I use Open Recent, I only need to press Ctrl+R, type and then pressing Enter, however with welcome page, navigating into those links is painful.

For option D, as we already focus on the Recent Folders, if we can use arrow keys to navigate between all clickable elements, it can be super helpful 
![image](https://user-images.githubusercontent.com/876920/48644076-6bef2100-e996-11e8-9d2d-52945d06ffb8.png)

**Comment by chrmarti** [comment]
@misolori I like that. 👍 

@rebornix I think keyboard-centric navigation is best served by the Open Recent (Ctrl+R) command. We should still think about improving keyboard navigation on the Welcome page, but I wouldn't optimize the design for the keyboard.

**Comment by misolori** [comment]
# Exploration C

Here's an updated exploration for Concept C. In this one I explored ways to make the first day experience (Day 0) focused on getting started. From the research above, it's very important for new users to adjust the editor to fit their workflows (via language support and keyboard shortcuts). Additionally, I wanted to make sure that current users (Day 30) we're able to easily access their recent projects while still providing for a way for those new users to access the first day content.

## Day 0

- Focal point is on getting started (customizing and learning) while also exploring the product
- Added content tabs for app + extension updates, and help content
- Entire layout is reduced for easier click targets

![exploration c 1 4](https://user-images.githubusercontent.com/35271042/48752415-fdcc8780-ec3d-11e8-8335-10a60977f7af.png)

## Day 1

- Moved customize and learn content into tabbed content to reduce visual noise

![exploration c 1 2](https://user-images.githubusercontent.com/35271042/48751984-058b2c80-ec3c-11e8-8929-f9b92eba88b4.png)

## Day 30

- Increased layout for higher density of information
- Recents turns into two columns

![exploration c 1 3](https://user-images.githubusercontent.com/35271042/48751985-058b2c80-ec3c-11e8-979f-4331cfc1a3e0.png)

**Comment by chrmarti** [comment]
I need to warm up to that little page switcher. Isn’t that an indication of us putting too much information on the ‘Welcome’ page?

I like the other ideas.

**Comment by beastdestroyer** [comment]
@chrmarti But can't you also argue that. being a Welcome screen, a lot of features can make it quite appealing, especially to newer users. I would say depending on the content yes there may be too much, but the page switcher with a few buttons isn't at all

**Comment by misolori** [comment]
It's a hard balance to make certain content the focal point for certain users, so that's the main reason for introducing the content tabs/switcher. In our current design, we definitely show a lot of content so I'm trying tidy that up while placing  a bigger emphasis for Recents and Start.

**Comment by misolori** [comment]
After doing a bit of user testing with the various explorations above (thanks to @stevencl), we've found that **Exploration C** has performed the best and we'll be working on incorporating those changes. The actual changes will likely happen in the next iteration or so. I'll keep this issue open as I post higher fidelity mockups. Below are the latest iterations.

## Day 0
![day 0](https://user-images.githubusercontent.com/35271042/49380153-375ac380-f711-11e8-8b8b-11c927a4aca9.png)

## Day 30
![day 30](https://user-images.githubusercontent.com/35271042/49380154-375ac380-f711-11e8-8c65-a838306a570d.png)

**Comment by misolori** [comment]
Below are a couple of the higher fidelity mockups:

## Day 0
![welcome](https://user-images.githubusercontent.com/35271042/49915383-3250ef00-fe4a-11e8-9092-02270e104616.png)

## Day 1
![welcome](https://user-images.githubusercontent.com/35271042/49915402-44cb2880-fe4a-11e8-9d77-7c1731093aff.png)

## Day 30
![welcome](https://user-images.githubusercontent.com/35271042/49915404-45fc5580-fe4a-11e8-918f-473f31dd739a.png)


## Transition (GIF)
![ezgif com-gif-maker 5](https://user-images.githubusercontent.com/35271042/49915373-21a07900-fe4a-11e8-8e8b-7b9f2f86dd89.gif)

**Comment by Astrantia** [comment]
@misolori the folders list looks really empty. can icons be added next to them? if a folder is mainly javascript maybe display javascript icon?

**Comment by misolori** [comment]
@Astrantia the intention is to keep it simple, any icons would add unnecessary visual noise since it would be the same icon (projects can contain multiple file types).

**Comment by dalDevelo** [comment]
It’s a minor complaint, but I think the logo and header text alignment looks terrible in relation to the text below. Maybe the header could be moved up a little further to create more separation from the ‘recents’ section below, or add some background shading to the recents section, such as in exploration B (which I still prefer). It would probably even look a little better if the logo was moved to the right hand side of the text and the header text was aligned to the text left?

Are recent workspaces still identifiable by (workspace) after the title, or will there be other visual indicators of workspaces, such as a different shade of text, perhaps?

**Comment by ghiscoding** [comment]
@misolori 
Just a quick proposition, some user might not understand why their view is changing (or even when it's changing). So perhaps adding a dropdown to choose the view that the user would want might help!? I basically think of exactly how that can be customized in Outlook with Pane View customization. 

I'm also assuming that your "transition GIF" in your previous [post](https://github.com/Microsoft/vscode/issues/63152#issuecomment-446836851) was forced in your code, while you could instead do it with a dropdown. 

If you want to keep it simple, you can also skip the dropdown proposition (it's just a suggestion). Your new approach is nice.

Thanks for making VSCode my Go To Editor for all my coding 😃 

![outlook](https://user-images.githubusercontent.com/643976/50803085-2f191980-12b7-11e9-9a3d-39ce98e02f8c.png)

**Comment by misolori** [comment]
@ghiscoding thanks for the suggestion! Can I ask why you'd want to customize this layout and what  you'd want to do?

Our main reasoning for doing this two-part view was so that we could help optimize the space for two specific types of users without alienating the other. New users need guidance to get started and existing users jump back into their projects a good majority of the time. While I can see how the dropdown would be convenient to customize, it doesn't really fit into the story of optimizing the space for these two users and a dropdown would be a bit overkill for this (IMO). We also definitely prefer a simpler/minimal approach to our UI 😄

**Comment by ghiscoding** [comment]
@misolori the suggestion is basically to address what I wrote in first paragraph of my previous post

> some user might not understand why their view is changing (or even when it's changing)

Basically your implementation changes the layout after a month without advising the user of the change. Some users might not know why or when it changed (I know myself because I read this thread, but apart from that, I probably wouldn't know that the layout changes after a month). A new dropdown would make it more clear and provide possibility to keep 1st layout forever if user wish to. 

Again this is just a suggestion, if you like it then go ahead with it, else I'm totally fine without it.

**Comment by loligans** [comment]
Would it be possible to add a setting to hide the "Show Welcome Page at Startup" checkbox?

**Comment by nealot** [comment]
I'm a fan of the visual studio 2010 start page as it emphasizes the various sections quite nicely:

![image](https://user-images.githubusercontent.com/36805289/50858823-85419780-135f-11e9-8c27-61711c01f669.png)

I have the current welcome screen disabled because the keyboard is much faster. However, if the page featured news/tips using the layout above then I might actually enable it.

I'm not sure if the day 30 thing is going to be more useful than just adding a setting that changes the layout whenever the user wants. Experienced users who prefer minimalism would have already modified the `Workbench: Startup Editor` setting to match their preferences. Instead, I'm in favor of adding these 2 options for the welcome screen:

1. Regular welcome screen
2. Centered welcome screen with only the file creation and recent project list (for the minimalist)

Here's a quick ugly sketch of what that might look like: 

![component 4image](https://user-images.githubusercontent.com/36805289/50858778-6511d880-135f-11e9-97bb-15341ad1b5e7.png)
![component 3](https://user-images.githubusercontent.com/36805289/50858779-6511d880-135f-11e9-800f-25865827e531.png)

**Comment by misolori** [comment]
@loligans I get what you're getting at (you don't want to see the checkbox), but I'm not sure it's worth the investment just to hide a single checkbox.

@nealot thanks for the suggestions. Curious to hear why you would enable the welcome page just for tips? I personally don't think adding "news" to an editor is a great idea as there are so many different mediums for consuming it (it's also an old trend that has phased out).

**Comment by nealot** [comment]
@misolori VSCode has so many great features that sometimes it's difficult to wrap your head around them -- this is especially true for beginners. I don't think most people are devoted enough to go through every single release update (past or future), so displaying tips about unused configuration options now and then might be useful. For instance, a tip like "You can disable _Editor › Minimap: Render Characters_ to render color blocks instead of the actual characters" might benefit someone unfamiliar with that option. Or maybe a featured API reference might inspire someone to create their first extension? Perhaps even some notable keyboard shortcuts could be mentioned? Tiny pieces of information like that could potentially make even the more infrequent users a little more aware of the application's ecosystem.

As for the news, I suppose it's the only other thing I might find useful since I almost exclusively use the keyboard for commands. Aggregating product updates from a bunch of sources ([such as this article]( https://blog.github.com/2019-01-07-create-pull-requests-in-vscode/)) to be displayed on the welcome page seems very strategic to me. But if the concept wasn't popular then it's whatever; I'm not particularly attached to the idea, just personally thought it would be a neat addition.

**Comment by gjsjohnmurray** [comment]
I suggest the "Add workspace folder..." text gets reworded to "Add folder to workspace..." so it matches what appears on the File menu.

And how about adding a link for "Open workspace..." as well? If yes, then I suggest putting it between "Open folder..." and "Add folder to workspace..."

**Comment by alefragnani** [comment]
Hi @misolori ,

I really liked the new mockups, specially the exploration C, but I would like to comment a different area.

Is there any chance (or had any conversation about) allow extensions to _contribute_ to certain sections of the Welcome Page?

I mean, my [Project Manager](https://marketplace.visualstudio.com/items?itemName=alefragnani.project-manager) extension allows the user to define _Favorite Projects_ and would be nice to have this list available right from the start in the Welcome Page. This could appear _near_ the **Recent** section.

There are also some extension that almost makes VS Code a new IDE, like the Java/Python extension. These extensions could add their _new kinds of projects/files_ in the **Start** section.

Even the **Help** section could receive contribution from extension.

The idea is the extension  _contributes / provide additional info_, not _replace_ the VS Code contents. So the users still gets all the current help/features/support from VS Code, and after extending VS Code with new extensions, the start up would also be improved.

Thanks, and congratulations for the explorations 👍

**Comment by kowalski7cc** [comment]
Totally agree with @alefragnani 
Really loving exploration C (maybe logo could be a little bigger) and would be wonderful if extensions could contribute to the page.
An exanple could be a GitHub extension to provide open issues or remote repositories.
Or the SSH remote cold provide some host to connect to, without opening a project.
Hope to see soon the new design! 😁

**Comment by andrewrothman** [comment]
Basing off of: https://user-images.githubusercontent.com/35271042/49915404-45fc5580-fe4a-11e8-918f-473f31dd739a.png

What do you think of moving the "Create file", "Create folder", and "Add folder to workspace" buttons above the recent files/folders list? They could be represented as icons (possibly with titles underneath) stacked horizontally. That way, the "Start" section could be removed, which should provide enough space for the "Customize", "Learn", and "Help" sections to be broken out into vertically stacked sections (removing the need for a page switcher).

Thoughts?

**Comment by Matelasse** [comment]
@misolori What became of this?

**Comment by misolori** [comment]
@Matelasse we've got a direction for the design but this has yet to be added to a milestone. I'm hoping this happens soon though I don't have an ETA.

**Comment by lambainsaan** [comment]
@misolori UX is sorted for this, right? I would love to implement the new designs.

**Comment by roman-petrov** [comment]
This might be a great improvement: being a non-new VS Code user I never need many items on current Welcome screen and use  every day only `Recent` as show on initial design proposal as top 1 action for current users. I suppose there are many VS Code users doing the same.

**Comment by misolori** [comment]
👋  Hey Everyone, it's been a while since we last updated this issue. We've been busy working on a new "Getting Started" experience (https://github.com/microsoft/vscode/issues/111554) and we're ready to revive the welcome page explorations. I'll be posting updates into this issue since they are all related. A few additional items we're exploring:

- Clean up the main sections (Recents, Start, Help) w/ primary actions
- Show content from "Getting Started"
- Show content from extensions for "Getting Started" https://github.com/microsoft/vscode/issues/116414

## Empty folder
![image](https://user-images.githubusercontent.com/35271042/109855087-b8fd6c80-7c0c-11eb-88da-d365cea3d898.png)

## Workspace
![image](https://user-images.githubusercontent.com/35271042/109855206-d9c5c200-7c0c-11eb-89b0-28796fbd2d90.png)

## Workspace + Recents

![image](https://user-images.githubusercontent.com/35271042/109860726-552a7200-7c13-11eb-8d2c-bd37eff921dc.png)

## Workspace + Recents + Getting Started

And after some time that the user has opened multiple projects and installed multiple extensions that contribute to the getting started content

![image](https://user-images.githubusercontent.com/35271042/109862377-37f6a300-7c15-11eb-9791-8e48a9625c0a.png)

**Comment by kolebayev** [comment]
Hi, are there any methods in current extensions api to make custom welcome page (as extension)? I need to show only recents as grid (not list) and button to open folder with project for example

**Comment by digitarald** [comment]
@kolebayev there is #119097, but just for walkthroughs. What kind of projects would you expect to see on the recent list? Feel free to ping me on my profile email for longer input.

**Comment by Inori-Lover** [comment]
simple is better, i choose a

**Comment by misolori** [comment]
Since we already shipped our new welcome page that includes the new [getting started pages](https://code.visualstudio.com/updates/v1_57#_new-getting-started-experience), closing this issue as done 🎉
