### ISSUE TITLE
Explore support for developing on WSL

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#63155]
WSL allows you to run linux program on Windows. We are looking into providing support for working with WSL when Code runs on Windows.  This is related to https://github.com/Microsoft/vscode/issues/29194.

Other related items are:
- https://github.com/Microsoft/vscode/issues/9502
- https://github.com/Microsoft/vscode/issues/13138
- https://github.com/Microsoft/vscode/issues/20220
- https://github.com/Microsoft/vscode/issues/22663
- https://github.com/Microsoft/vscode/issues/28667
- https://github.com/Microsoft/vscode/issues/50795

Here is the query of all open issues labeled with `WSL`: [query](https://github.com/Microsoft/vscode/issues?page=1&q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc+label%3AWSL&utf8=%E2%9C%93)

**Comment by jsynowiec** [comment]
Just a heads-up, for reference, most JetBrains IDEs now support WSL interpreters without the remote-interpreter-over-ssh workaround. It's available in [PyCharm 2018.3](https://www.jetbrains.com/help/pycharm/2018.3/using-wsl-as-a-remote-interpreter.html), [RubyMine 2017.3](https://blog.jetbrains.com/ruby/2017/10/rubymine-2017-3-eap5-wsl-support-improved-parameter-hinting/#bash), [WebStorm 2018.2](https://www.jetbrains.com/webstorm/whatsnew/#v2018-2-nodejs-on-wsl).

**Comment by uishon** [comment]
> Just a heads-up, for reference, most JetBrains IDEs now support WSL interpreters without the remote-interpreter-over-ssh workaround. It's available in [PyCharm 2018.3](https://www.jetbrains.com/help/pycharm/2018.3/using-wsl-as-a-remote-interpreter.html), [RubyMine 2017.3](https://blog.jetbrains.com/ruby/2017/10/rubymine-2017-3-eap5-wsl-support-improved-parameter-hinting/#bash), [WebStorm 2018.2](https://www.jetbrains.com/webstorm/whatsnew/#v2018-2-nodejs-on-wsl).

As for JetBrains IDEs, it's true and nice *but* as for Python (PyCharm), virtualenvs are *not* supported so at least for me, this makes this feature *useless*. Unfortunately.

**Comment by helio-correia** [comment]
Yes, a totally agree with uishon. Vscode is from windows and now the python package too (and the top downloaded package). I think they should focus more on getting the best integration between vscode, python and WSL. 
When I'm doing Django development on windows, I need to use wsl because I got some bugs on translations and channels for example. If I use that, I can't set the python linter for vscode.
The fix I needed to do was have two virtualenvs, one for windows and another to WSL.

**Comment by offero** [comment]
Does debugging through docker work?

**Comment by benc-uk** [comment]
Oh god yes!
I need this. The integration today is really bad, and actually causes a lot of problems. 

Support for WSL git as the main source control, but also critical for language extensions (Node, Dotnet, Python, Go). The lack of support currently means I have to have SDKs for all languages installed under both Windows and WSL

Don't forget tasks and debug also have massive issues with WSL today, with path translations and locating binaries. Trying to get a set of clean launch configs that work on any developers system is impossible

**Comment by samirbr** [comment]
A simple suggestion: the integration should be simple as reference WSL commands and paths using a WSL schema: `wsl://<path>`. 
Example:
```
wsl://usr/bin/python
```

**Comment by offero** [comment]
> A simple suggestion: the integration should be simple as reference WSL commands and paths using a WSL schema: `wsl://<path>`.
> Example:
> 
> ```
> wsl://usr/bin/python
> ```

That seems very useful. One caveat is that people may have multiple WSL environments installed, so there should be a way to set which one should be used.

**Comment by bardware** [comment]
> people may have multiple WSL environments installed

You call `wsl.exe` and get one wsl environment. Every other Linux has to be started by `bash.exe` or something.
https://docs.microsoft.com/en-us/windows/wsl/wsl-config

**Comment by samirbr** [comment]
> > A simple suggestion: the integration should be simple as reference WSL commands and paths using a WSL schema: `wsl://<path>`.
> > Example:
> > ```
> > wsl://usr/bin/python
> > ```
> 
> That seems very useful. One caveat is that people may have multiple WSL environments installed, so there should be a way to set which one should be used.

Maybe use `wsl+<environment>://<path>`.
Example:
```
wsl+ubuntu://usr/bin/python
```

**Comment by benc-uk** [comment]
The `wsl://` schema idea is a neat idea, but I don't know if the integration needs to go deeper? E.g. The major language extensions (Python, Go, Node, C#) need to be aware of WSL too

**Comment by clouds56** [comment]
Also the filenames and project folder would need transform before passing into wsl
e.g. `C:\your\workspace` -> `/mnt/c/your/workspace`
when using `wsl://` schema

**Comment by benc-uk** [comment]
Shame that every month this moves out another month. I wouldn't mind but some news on progress, what is being worked on/investigated would give us WSL users some hope! 😁

**Comment by dscho** [comment]
Have you gentle people seen [this announcement](https://docs.microsoft.com/en-us/windows/wsl/release-notes) about the next Windows feature update and `\\wsl$`? I think this might neatly solve the problem, but of course, I do not have that Windows version yet, so I can't say for sure.

**Comment by kavdev** [comment]
@dscho Thanks for the heads up on that. Pretty cool, but it only enables you to interact with wsl files. There still needs to be more work on having the vscode instance be able to work with linux binaries, unless I'm missing something.

I tried setting ``git.path`` to ``\\wsl$\Ubuntu\usr\bin\git`` (technically ``\\\\wsl$\\Ubuntu\\usr\\bin\\git`` in settings.json) to no avail

**Comment by dscho** [comment]
> I tried setting `git.path` to `\\wsl$\Ubuntu\usr\bin\git`

Why not using `wsl git`?

```
C:\>wsl git version
git version 2.7.4
```

**Comment by kavdev** [comment]
> Why not using wsl git?

@dscho I was just using the git executable as an example. I appreciate the willingness to help, but I want to avoid taking this thread off-topic; see https://github.com/Microsoft/vscode/issues/9502 on why that solution doesn't work

**Comment by Yablon** [comment]
Oh I think the wsl based vscode is really needed. If the wsl python interpreter and remote python interpreter(I don't know if this will be surpported) is surpported in vscode, I will change my IDE from Pycharm to VsCode.

**Comment by kowalski7cc** [comment]
> > > A simple suggestion: the integration should be simple as reference WSL commands and paths using a WSL schema: `wsl://<path>`.
> > > Example:
> > > ```
> > > wsl://usr/bin/python
> > > ```
> > 
> > 
> > That seems very useful. One caveat is that people may have multiple WSL environments installed, so there should be a way to set which one should be used.
> 
> Maybe use `wsl+<environment>://<path>`.
> Example:
> 
> ```
> wsl+ubuntu://usr/bin/python
> ```

I think it would be better a thing like wsl://ubuntu/<path> or wsl-distro://ubuntu/<path> and wsl://<path> referring to default distro

**Comment by Tyriar** [comment]
We just announced remote development with VS Code, check out the blog post for details https://code.visualstudio.com/blogs/2019/05/02/remote-development
