### ISSUE TITLE
Installer should reopen all last opened folders

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#6316]
- VSCode Version: 1.1.0
- OS Version: Windows

Steps to Reproduce:

1. Have more than one workspace folder open
2. Update to a new version

Observe: only on window is reopened. I would expect that all open folders get reopened.

**Comment by dbaeumer** [comment]
@bpasero unsure if this is the installer or the workbench.

**Comment by bpasero** [comment]
It is a setting (window.reopenFolders) which is checked here (https://github.com/Microsoft/vscode/blob/ben/stacks/src/vs/code/electron-main/windows.ts#L846) and if we know that VS Code was restarted because of an update, it should be easy to force reopen of folders from there.

**Comment by bpasero** [comment]
I might be able to just do this by storing a temporary setting before applying the update.

**Comment by bpasero** [comment]
@dbaeumer @jrieken pushed a change to reopen windows when an update is applied. Please let me know from your self host usage if this works on Mac and Windows.

**Comment by dbaeumer** [comment]
Looking forward to it !
