### ISSUE TITLE
Default AND User settings BROKEN for pylint.linting.pylintEnabled

### ISSUE THREAD

**Issue by kinyusui** [Microsoft/vscode#63168]
pylint does not work unless 
    "python.linting.pylintEnabled": true
is in workspace settings.
If this is not included but IS included in "User settings", there will still be no pylint errors shown.

I'm using a simple error like 
print 'hi'
which should through an error asking for parenthesis on python 3.

Since python.linting.pylintEnabled is true by default, this would mean that the default settings aren't working for me either. I MUST specify it specifically in my workspace settings.

**Comment by mjbvz** [comment]
Please file this issue against the python extension

**Comment by kinyusui** [comment]
My bad, will do that.
