### ISSUE TITLE
VS 1.9:  python version still shows 2.7 eventhough the staus bar shows 3.7 

### ISSUE THREAD

**Issue by tomvolek** [Microsoft/vscode#63166]
🚨 The issue tracker is not for questions 🚨

Mac OS: 
VS Code 1.29 . 

VS 1.9:  python code gets executed with  2.7 interpreter even though the status  bar shows selected interpreter is Python 3.7.0 64bit.  

Preferences-> Extensions-> python -> user settings: python configuration:-> PythonPath: "/usr/local/bin/python3"

**Comment by mjbvz** [comment]
Please file this issue against the python extension
