### ISSUE TITLE
Resolve modules imported via `@submodule` notation 

### ISSUE THREAD

**Issue by hexrcs** [Microsoft/vscode#63160]
I am currently working on a javascript project using subdirectory `package.json` files to denote "sub module" names in order to avoid the tedious `../../../../../someFile.js`. Basically we place a `package.json` with contents like below beside the `index.js` inside a sub directory, then we can import from that directory anywhere in the project with the name defined in `package.json`.

Inside `src/foo/bar/components`

```json
{
    "name": "@components"
}
```

Inside `src/baz/qux.js`

```js
import { CoolStuff } from '@components'
// instead of `import { CoolStuff } from './../foo/bar/components'`
```

However, VS Code doesn't seem to resolve the imports done this way, and doesn't offer autocompletion, definition peeking or any handy IDE features.

Support for this feature would be awesome!

**Comment by mjbvz** [comment]
Try creating a [`jsconfig.json`](https://code.visualstudio.com/Docs/languages/javascript#_javascript-projects-jsconfigjson) and configure `paths` to setup the mapping. Something like

```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es2016",
        "baseUrl": ".",
        "paths": {
            "@components": [
                "./src/foo/bar/components"
            ]
        }
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]   
}
```
