### ISSUE TITLE
Flimmer/Blurry text on vertical mouse movement in 1.29 (Windows, disappears with --disable-gpu)

### ISSUE THREAD

**Issue by Centril** [Microsoft/vscode#63164]
- VSCode Version: 1.29.0 (user setup); the problem was introduced a few major versions ago, don't remember exactly when.

![vscode-about](https://user-images.githubusercontent.com/855702/48505097-8c0fca80-e846-11e8-8af7-8532c79903ac.png)

- OS Version:

```
Edition: Windows 10 Pro
Version: 1803
OS Build: 17134.345
```

- Machine details:

CPUs | Intel(R) Core(TM) i7-3610QM CPU @ 2.30GHz (8 x 2295)
-- | --
GPU Status | 2d_canvas: enabledchecker_imaging: disabled_offflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwarerasterization: enabledvideo_decode: enabledvideo_encode: enabledwebgl: enabledwebgl2: enabled
Memory (System) | 15.95GB (6.22GB free)
Process Argv | --disable-extensions
Screen Reader | no
VM | 0%
GPU | NVidia GeForce GTX 660M; NVIDIA GeForce Experience Version 3.15.0.186

Steps to Reproduce:

1. Move the mouse vertically on the sidebar, the settings page, status bar, and sometimes in the text area for files.

Does this issue occur when all extensions are disabled?: Yes; and with an empty `User/settings.json`. Launching with `code --disable-gpu` solves the issue.

Video showing the bug (didn't work to convert to gif...): http://sendvid.com/5bwj2543

**Comment by roblourens** [comment]
Can you download this build to check whether it's fixed with the next version of electron?

https://az764295.vo.msecnd.net/exploration/a19e0f85ac7167f27716b3cbbb07a6164f47684e/VSCode-win32-x64-1.29.0-exploration.zip

**Comment by Centril** [comment]
@roblourens 

Thanks for the quick response. :)

I tested the binary with and without extensions + `settings.json`...
I cannot reproduce the bug with the binary provided in any scenario so the bug seems to be gone.

**Comment by roblourens** [comment]
Alright, sounds like the fix is coming down the pipeline. There are some similar issues.

**Comment by Centril** [comment]
@roblourens I'll continue to use `--disable-gpu` in the interim which has worked thus far so there's no rush, but could you speak a bit about when that is estimated to be?.

**Comment by roblourens** [comment]
I don't know. Not this month.

**Comment by Centril** [comment]
@roblourens Alright; Thanks!
