### ISSUE TITLE
Maximizing VS Code leaves tiny open space at top

### ISSUE THREAD

**Issue by wsuBobby** [Microsoft/vscode#63171]
Issue Type: <b>Bug</b>

Expected:  Maximizing VS Code takes up the entire screen.
Actual:  Maximizing VS Code doesn't take up the entire screen, instead there is a tiny space at the top.

This happens the first time you maximize, doing it a second time is good.  Then retrying it, it's bad, second time it works.  Seems to be in pairs of bad then good.  This happens on several different maximizing actions.  Happens when clicking the maximize icon on the windows header, when dragging the window to the top of the screen to auto-maximze, and also occurs when using the windows+up shortcut.

Screenshot:  https://i.imgur.com/YNdZcoE.png

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:47:15.448Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.34GB (7.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.3.2
gc-excelviewer|Gra|2.1.26
mssql|ms-|1.4.0
csharp|ms-|1.17.0

</details>

**Comment by wsuBobby** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Maximized panel should be fullscreen (#45734)](https://www.github.com/Microsoft/vscode/issues/45734)

**Comment by wsuBobby** [comment]
FYI, I checked #45734 and it's not a dupe of that.  #45734 is about the terminal windows maximization whereas this item is referring to the entire VS Code window.

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/52265
