### ISSUE TITLE
[Insiders] Double menu on Linux

### ISSUE THREAD

**Issue by alekseyt** [Microsoft/vscode#63174]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/993454/48520508-87b0d500-e879-11e8-80b5-3792ae2e16c4.png)

Normal look:

![image](https://user-images.githubusercontent.com/993454/48520565-bf1f8180-e879-11e8-938b-9db438f24408.png)

I know where this is coming from, it's not hard to guess. You should probably check `$XDG_CURRENT_DESKTOP` and compare it with string "GNOME". Reference: https://chromium.googlesource.com/chromium/src/+/master/base/nix/xdg_util.cc#59

Please note that it handles more than one case.

VS Code version: Code - Insiders 1.30.0-insider (6ef7e81ec086ced5fb20e904ea405075be474023, 2018-11-14T18:15:46.706Z)
OS version: Linux x64 4.4.0-112-generic

<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.21.0-insiders
shader|sle|1.1.4
vscode-lua|tri|0.12.4
cmake|twx|0.0.17
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
@alekseyt thanks for the info about XDG_CURRENT_DESKTOP. Unfortunately, I still can't repro your issue with a fresh copy of Ubuntu 16.04 and VS Code 1.30.

You are the second person to see double menus and that person was using MATE. I would like to get to the bottom of this. Do you have any special configuration that might helpful to know.

I do notice with Unity that there are duplicate window controls. 

@joaomoreno perhaps Unity is a DE we should consider more deeply.

**Comment by sbatten** [comment]
got a repro of this issue due to another issue, thus resolving as duplicate https://github.com/Microsoft/vscode/issues/63022

**Comment by joaomoreno** [comment]
@sbatten Unity, once created by Canonical, has been abandoned by it in favor of Gnome 3. Though there are still quite some users on it...

**Comment by sbatten** [comment]
@joaomoreno right, since detection isn't too difficult and we still see users, perhaps we could make some changes too improve that experience. at least for a while.

**Comment by alekseyt** [comment]
@sbatten thank you for your support.

There are no specific steps to reproduce, i just start insiders build which i've got from `http://packages.microsoft.com/repos/vscode stable`, that's it. It starts maximized and produces image as shown on screenshots. All my settings for insiders build, except for keybindings, are also on screenshot.

When it's not maximized, there is still double menu, but 3 buttons instead of 6.

![image](https://user-images.githubusercontent.com/993454/48646965-20b72b80-e9f3-11e8-8548-6af08a6a88de.png)

However native title bar is where vscode really shines:

![image](https://user-images.githubusercontent.com/993454/48647053-74297980-e9f3-11e8-87eb-b272b5a2da14.png)
