### ISSUE TITLE
stop working

### ISSUE THREAD

**Issue by zhaoYun-Long** [Microsoft/vscode#63184]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/visual-studio-code.
I stopped for a moment, and he stopped working

**Comment by roblourens** [comment]
Did vscode hang? If so try downloading Insiders, we fixed an issue there: https://code.visualstudio.com/insiders

Otherwise, provide more details.
