### ISSUE TITLE
Extensions will be unable when I update vscode version

### ISSUE THREAD

**Issue by installBean** [Microsoft/vscode#63182]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.17134
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.1.3
vscode-markdownlint|Dav|0.20.0
jshint|dba|0.10.19
vscode-eslint|dba|1.4.12
xml|Dot|2.3.2
gitlens|eam|8.4.1
beautify|Hoo|1.4.3
vscode-language-pack-zh-hans|MS-|1.23.5
Go|ms-|0.6.91
java|red|0.30.0
vscode-java-debug|vsc|0.12.2
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.8.0
vscode-maven|vsc|0.11.1

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by installBean** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [macOS: Unable to update VSCode via update service. (#61265)](https://www.github.com/Microsoft/vscode/issues/61265)



> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [macOS: Unable to update VSCode via update service. (#61265)](https://www.github.com/Microsoft/vscode/issues/61265)

I also lost the sidebar, but this had to happen

**Comment by roblourens** [comment]
Please provide more details about the problem
