### ISSUE TITLE
Code recognition off

### ISSUE THREAD

**Issue by wasinwill** [Microsoft/vscode#63186]
![capture](https://user-images.githubusercontent.com/44789688/48531210-5fb97580-e869-11e8-96e8-3cf868e3e3ef.PNG)
Issue Type: <b>Bug</b>

Since last update, VS Code seems unable to recognize PHP tags inside script tags (see attached screenshot).
- Reproduces when all extensions are disabled
- Occurs on Insiders only.

VS Code version: Code - Insiders 1.30.0-insider (6ef7e81ec086ced5fb20e904ea405075be474023, 2018-11-14T18:22:35.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (4 x 3498)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (11.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-close-tag|for|0.5.6
vscode-apache|mrm|1.1.1
highlight-matching-tag|vin|0.8.3

</details>

**Comment by roblourens** [comment]
Works in Atom

**Comment by wasinwill** [comment]
Any update on this by any chance?

**Comment by skison** [comment]
I have a similar issue now with stable release 1.30.1 on Windows 10:
![php highlight error](https://user-images.githubusercontent.com/22156854/50299732-5a46e080-0450-11e9-8343-a9f3f927c485.PNG)
Currently have extensions disabled, same thing happens when enabled. I never had this problem with previous VS Code versions, this has only started happening after a new install.

**Comment by wasinwill** [comment]
Yeah, the issue now reproduces on the stable release as well.

**Comment by apkrieg** [comment]
![image](https://user-images.githubusercontent.com/6716740/51452334-b9c23580-1d07-11e9-9791-eca520eb05d1.png)

Having issues with `<script>` tags as well.

**Comment by roblourens** [comment]
I think this was https://github.com/Microsoft/vscode/issues/65649
