### ISSUE TITLE
middle click to close active non tab window when click on name area at top?

### ISSUE THREAD

**Issue by rakkarage** [Microsoft/vscode#63185]
when in tab mode:
- ctwl+w closes windows
- middle click on file name in open section of explorer closes it
- middle-click on file name in tab closes it

when not in tab mode:
- ctwl+w closes windows
- middle click on file name in open section of explorer closes it
- middle click on file name in 'non-tab' **DOES NOT** closes it

thank you?

**Comment by rakkarage** [comment]
thanks. yes this is different.
middle click does not even close tab when tab mode is off
i know technically there is no tab but in reality there is

**Comment by bpasero** [comment]
Good catch, thanks!
