### ISSUE TITLE
Containers headers/libraries

### ISSUE THREAD

**Issue by bhack** [Microsoft/vscode#63183]
I am try to repropose https://github.com/Microsoft/vscode-cpptools/issues/2818 here. 
Is there a plan to parse libraries installed in a container image?
Expecially if the container is running remotely (Kubernetes etc.) so that it will be hard to launch portable vscode inside a volume mounted in the container.

**Comment by roblourens** [comment]
I don't understand what you mean by "parse libraries"

**Comment by bhack** [comment]
@roblourens I.e. in the c++ use case. Suppose that in a Dockerfile I have a entry `RUN apt-get install libfoo-dev`. The headers are in the image/container file-system for Intellisense not on the host.

**Comment by roblourens** [comment]
I think this is covered by some existing feature requests such as https://github.com/Microsoft/vscode/issues/35671
