### ISSUE TITLE
Snap: User fonts are missing

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#63194]
I'm using Fira Code iScript

![image](https://user-images.githubusercontent.com/22350/48535814-cf9d1f80-e8ac-11e8-8f89-9ceff59de43b.png)

**Comment by chrisberry08** [comment]
Also experiencing this issue. I'm using Fira Code. All fonts display fine on non-snap version.

**Comment by joaomoreno** [comment]
@flexiondotorg Any thoughts on this one? I can't actually get the Code-Insiders snap working with any other font than the ugly Courier New. :thinking:

**Comment by flexiondotorg** [comment]
@joaomoreno I can't reproduce this issue. I have installed the Code Insiders snap on a clean Ubuntu 18.10 VM. I've canged tthe Editor: Font Family to this: `'Ubuntu Mono','Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'` and I have the Ubuntu font reflected in my editor.

How did you install the Fira Code font? What directory it is installed in?

**Comment by kingofsystem** [comment]
Still experiencing this issue. I'm using xubuntu and installed Fira Code via standard font viewer in ubuntu. Non-snap edition can use custom font.

**Comment by farzadmf** [comment]
I have the same problem with the terminal font on Ubuntu 18.10; I have installed vscode using the `edge` channel, and I have installed [Menlo for Powerline](https://github.com/abertsch/Menlo-for-Powerline) font, but when I set this:

```
"terminal.integrated.fontFamily": "Menlo for Powerline"
```

I receive an error message like this:
![image](https://user-images.githubusercontent.com/5768792/51147968-482b4880-182a-11e9-8b62-d9393e13b2e9.png)

The reason I know it's not because of the font not being monospace is that I get the error message no matter what I type for the setting.

It may be worth mentioning that if I set the value to `Ubuntu Mono`, the font changes, and I don't see the error message

**Comment by joaomoreno** [comment]
@flexiondotorg Fonts are in `~/.local/share/fonts`.

The default `'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'` also doesn't work for me:

![image](https://user-images.githubusercontent.com/22350/51170066-c8df5880-18ad-11e9-93e2-caf16d179a2a.png)

Compare that with the non-snap version:

![image](https://user-images.githubusercontent.com/22350/51170202-21aef100-18ae-11e9-84b9-d29c8c8c170b.png)

---

The value `'Ubuntu Mono','Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'` actually works, I get the Ubuntu font. :thinking:

**Comment by flexiondotorg** [comment]
@joaomoreno We've been testing this and discovered the following. User installed fonts in `~/.fonts` or `~/.local/share/fonts` are not working with code-insiders snaps when it is installed on Ubuntu 18.10. However,  user installed fonts **are working** with the code-insiders snap on Ubuntu 16.04 LTS and Ubuntu 18.04 LTS. We are investigating further to understand why 18.10 is not working.

We've been using Fira Code and the [Go font](https://go.googlesource.com/image) in our testing.

**Comment by joaomoreno** [comment]
Current workaround: copy fonts to `/usr/share/fonts`

**Comment by joaomoreno** [comment]
Thanks to @flexiondotorg, this is now fixed in `master`! https://github.com/Microsoft/vscode/pull/70884
