### ISSUE TITLE
Sometimes take high cpu  usage and the window is no respone

### ISSUE THREAD

**Issue by ghostHBL** [Microsoft/vscode#63198]
Issue Type: <b>Bug</b>

After I get the last version of VSCode, sometimes it takes high CPU usage even when I didn't do anything in VSCode, and the window will not respond in this case. And this case is often happend when I debug the code. 
![2018-11-15 15-43-11 1](https://user-images.githubusercontent.com/15714810/48538672-09dbe080-e8f0-11e8-9741-ae7f776da3e7.png)
![2018-11-15 15-43-11 2](https://user-images.githubusercontent.com/15714810/48538685-0fd1c180-e8f0-11e8-8666-aa393f3bfe17.png)

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:42:27.562Z)
OS version: Linux x64 4.18.16-041816-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 1601)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|7.66GB (1.61GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
Python-autopep8|him|1.0.2
nbpreviewer|jit|1.0.0
sftp|lix|1.7.5
ftp-sync|luk|0.3.3
vscode-language-pack-zh-hans|MS-|1.29.2
python|ms-|2018.10.1

</details>

**Comment by roblourens** [comment]
Please see the tips in the perf wiki page https://github.com/Microsoft/vscode/wiki/Performance-Issues#the-rendererwindow-process-consumes-a-lot-of-cpu - and if that doesn't help, see the next section to attach a profile of the renderer process.

**Comment by roblourens** [comment]
Please upgrade to 1.29.1 where we fixed an issue like this and let me know whether it still happens.

**Comment by ghostHBL** [comment]
> Please upgrade to 1.29.1 where we fixed an issue like this and let me know whether it still happens.

It work well after I upgrade to 1.29.1，thanks a lot.
