### ISSUE TITLE
No C# Highlight in 1.1.0?

### ISSUE THREAD

**Issue by hszest** [Microsoft/vscode#6319]
- VSCode Version:1.1.0
- OS Version:Windows 7 SP1 x64

Steps to Reproduce:

1. Install & Start VS Code v1.1.0
2. Looking for "C#" in the highlight drop-list
3. NO C# ANYWHERE

**Comment by isidorn** [comment]
C# has moved into an extension, please install the extension https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp

**Comment by hszest** [comment]
The "Ctrl+P" and then "ext install csharp" is not working...

Can't get C# support for something name starting with "Visual Studio" really did amaze me :(

**Comment by isidorn** [comment]
Can you please provide more details as to why "ext install csharp" is not working. Do you get any errors? Are you connected to the internet when doing this? Are you behind a firewall?

**Comment by hszest** [comment]
Internet connection seems fine, and I manually added VSCode to the Windows Firewall approval list.
When I typed "Ctrl+P" then entered "ext install csharp", the progress bar below turns out running, then nothing happened, the C# support did not show up
No errors

**Comment by eByte23** [comment]
This seems to be an issue with the omnisharp ext not working you have to manually install it from latest omnisharp vscode for it to work

**Comment by eByte23** [comment]
@csholmq also had this issue

**Comment by eByte23** [comment]
But we were running on insider 1.1.0

**Comment by csholmq** [comment]
Correct. [Built-in Omnisharp](https://marketplace.visualstudio.com/items?itemName=ms-vscode.omnisharp) extension states 

> Don't install this extension unless you want to try an early version. By default it is already
bundled with VS Code.

Which isn't true anymore. Something has broken.

**Comment by isidorn** [comment]
C# extension is no longer bundled by default with VSCode.
If the C# extension can not be properly installed please file that issue with setup description against 

https://github.com/OmniSharp/omnisharp-vscode/issues
