### ISSUE TITLE
经常卡死退出

### ISSUE THREAD

**Issue by zouhuigang** [Microsoft/vscode#63199]
Issue Type: <b>Bug</b>

版本: 1.29.0 (user setup)
提交: 5f24c93878bd4bc645a4a17c620e2487b11005f9
日期: 2018-11-12T07:47:15.448Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
架构: x64

经常卡死退出

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:47:15.448Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|15.75GB (7.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.29.2
python|ms-|2018.10.1
Go|ms-|0.7.0
vetur|oct|0.13.0

</details>

**Comment by roblourens** [comment]
Please include more details

**Comment by roblourens** [comment]
If vscode is hanging, see https://github.com/Microsoft/vscode/issues/62970
