### ISSUE TITLE
Event 'file changed' triggered when scss/less files are editing (win7)

### ISSUE THREAD

**Issue by fouckybzh** [Microsoft/vscode#632]
To illustrate this issue, I wrote this gulp task that watches for changes on some files with differents extensions :

```javascript
gulp.task('watch', function() {
  var filesToWatch = [
    'src/styles/*.scss',
    'src/styles/*.less',
    'src/styles/*.css'
  ];
  
  function doSomething() {
    console.log("I do something ...");
  }
  
  gulp.watch(filesToWatch, doSomething) ;
});
```

I run the task and open the folder project with vscode (0.10.1).
```
#> code .
#> gulp watch
```
As long as I keep a sass file (.scss) opened in the code viewer, the function `doSomething()` is fired without stop (same bevahior when editing less files).

It's quite annoying.

**Comment by bpasero** [comment]
@fouckybzh weird indeed, VS Code should not touch the file, but maybe someone else is? Can you run "vscode --verbose" and open the console to see what kind of file events VS Code receives? It should look like this:

![image](https://cloud.githubusercontent.com/assets/900690/11406737/2cf5e8c0-93af-11e5-8ed9-e7e372059695.png)

**Comment by fouckybzh** [comment]
Here is the VSCode logs after running it in verbose mode and opening a sass file in the editor :
![capture1](https://cloud.githubusercontent.com/assets/15893458/11420336/b930cc1e-942d-11e5-84af-27875f0a7723.PNG)

At the same time, I started the watch gulp task :
![capture2](https://cloud.githubusercontent.com/assets/15893458/11420374/0163d6d4-942e-11e5-899c-ed393d4bfb56.PNG)

**Comment by bpasero** [comment]
@fouckybzh do you have any extensions installed?

**Comment by fouckybzh** [comment]
No extension has been installed. To be safe, I uninstalled and reinstalled VSCode but I still have the same behavior. I just did a test on another machine with a fresh install of vscode (0.10.2) .... same problem :(

**Comment by bpasero** [comment]
@fouckybzh is this project somewhere on github for me to play with?

**Comment by fouckybzh** [comment]
https://github.com/fouckybzh/test-watch.git

**Comment by bpasero** [comment]
Thanks will have a look!

**Comment by bpasero** [comment]
I cannot reproduce on Windows 8 so far.
