### ISSUE TITLE
Starting a node.js process in debugger takes forever

### ISSUE THREAD

**Issue by patrickjane** [Microsoft/vscode#63204]
- VSCode Version: 1.28.0
- OS Version: macOS 10.13.3

Steps to Reproduce:

1. Open a node.js based project
2. Hit F5 to start the debugger
3. Wait

Sometimes it starts up really quickly, but at random times the debugger will "hang" (the bottom bar is still blue, and the top menu will have the progress bar showing "startup-activity") for around 30s.

This is extremely annoying when you're trying to fix several minor issues, because each time vscode is forcing you to wait around half a minute before starting the debugger.

This issue was first observed some months ago, and it happens to all of my different node.js projects. I am using node.js v8.9.4 currently.

This is how the terminal looks when it hangs:
https://imgur.com/a/DWKR02f

This is how the debugger panel looks like then it hangs:
https://imgur.com/a/pTBp8j2
(note that the pause/step/step into/etc panel is not yet displayed)

My launch config:

		{
			"type": "node",
			"request": "launch",
			"name": "Launch Portal",
			"program": "${workspaceRoot}/source/app.js",
			"args": ["--setup=./setup/setup.xml"],
			"env": {
				"NODE_ENV": "production",
				"DEBUG": "portal:error portal:warn portal:info portal:line portal:debug"
			},
			"sourceMaps": true,
			"console": "integratedTerminal"	
		},

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by roblourens** [comment]
Can you set `"trace": true` and upload the log here?

**Comment by patrickjane** [comment]
Sure, if you can tell me _how exactly_ I do this, I will provide the logs.

**Comment by weinand** [comment]
Add `"trace": true` to your launch config and press F5. On the debug console you will find the location of the log file. Zip it and attach it to this issue.

**Comment by patrickjane** [comment]
Okay actually, upon restarting, my installation was updated to v1.29.0. I have not succeeded in reproducing this issue since. So maybe this bug/behaviour is no longer present in the current version. Once I come across the issue again and manage to catch the logs, I will add them to this issue.

**Comment by weinand** [comment]
Thanks for the update!
