### ISSUE TITLE
Snippet suggestion triggered incorrectly

### ISSUE THREAD

**Issue by 23min** [Microsoft/vscode#6320]
- VSCode Version: Version 1.1.0 (1.1.0)
- OS Version: Mac OS X Yosemite 10.10.5 (14F27)

Steps to Reproduce:

1. Create a user snippet with a prefix "sup" 
(I created mine in ~/Library/Application Support/Code/User/snippets/elixir.json)
2. In a file matching the language, type `S` or `s`, intellisense correctly suggests snippet "sup"
3. When proceeding to type non-matching characters, e.g. `erv` intellisense still suggests snippet "sup"

![screenshot 2016-05-12 13 26 23](https://cloud.githubusercontent.com/assets/1111124/15213139/8d3877be-1845-11e6-97af-a6af439c1a7f.png)

Expected behavior:

When the typed characters no longer match the start of a snippet prefix, the snippet suggestion should not be shown.

**Comment by jrieken** [comment]
@23min Can you share you snippet with us? Trying this with the `class` snippet in JavaScript doesn't allow me to repo

![may-12-2016 17-57-13](https://cloud.githubusercontent.com/assets/1794099/15221275/1bce3ebc-186b-11e6-89f0-b5c3e59bc53f.gif)

**Comment by 23min** [comment]
```
{

	// Place your snippets for Elixir here. Each snippet is defined under a snippet name and has a prefix, body and 
	// description. The prefix is what is used to trigger the snippet and the body will be expanded and inserted. Possible variables are:
	// $1, $2 for tab stops, ${id} and ${id:label} and ${1:label} for variables. Variables with the same id are connected.
	// Example:
	"Print to console": {
		"prefix": "log",
		"body": [
			"console.log('$1');",
			"$2"
		],
		"description": "Log output to console"
	},
	
		"Print to Somethjing": {
		"prefix": "Lassa",
		"body": [
			"console.log('$1');",
			"$2"
		],
		"description": "Log output to console"
	},
	
	"Supervisor Template": {
		"prefix": "sup",
		"body": [
			"defmodule $1.Supervisor do",
				"\tuse Supervisor",
				"",
				"\tdef start_link do",
					"\t\tSupervisor.start_link(__MODULE__, [])",
				"\tend",
				"",
				"\tdef init(_) do",
					"\t\tchildren = [",
						"\t\t\tworker($1.Server, [])",
					"\t\t]",
					"",
					"\t\tsupervise(children, strategy: :one_for_one)",
				"\tend",
				"",
			"end",
			"$2"
		],
		"description": "Creates a skeleton supervisor"
	},
	
	"GenServer Template": {
		"prefix": "gens",
		"body": [
			"defmodule $1 do",
				"\tuse GenServer",
				"", 
				"\tdef start_link do",
					"\t\tGenServer.start_link(__MODULE__, :ok, [name: __MODULE__])",
				"\tend",
		    "",  
			"end",
			"$2"
		],
		"description": "Creates a minimal skeleton genserver"
	}	
}
```

**Comment by jrieken** [comment]
Understood. It is like this because we [compare](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/suggest/browser/completionModel.ts#L124) suggestions against their `label`, `codeSnippet`, and `filterText`. The first and last are clear to me but I don't remember why we filter against the `codeSnippet`...

**Comment by jrieken** [comment]
Reopening and reverting this due to #6620

**Comment by jrieken** [comment]
Now depends on #6620

**Comment by jrieken** [comment]
Sorry, need to revert again due to #8531. There is still something wrong with the `json` language which doesn't allow me to make this change

**Comment by aeschli** [comment]
Thanks @jrieken !

**Comment by fluffynuts** [comment]
This also affects "inbuilt" snippets: when working in Typescript, typing "c" shows the completion for the "class" snippet -- however, finishing out to "const" leaves the "class" snippet still selected, so an <Enter> keypress to move to the next line for a bunch of consts gets me a class snippet.
So this isn't so much a case of "the wrong snippet selected" as "no snippet actually matches the word, but last last matching snippet is still selected".

I stumbled across this report from searching GitHub issues for vscode and snippets -- if this addition should be put somewhere else, please advise.
