### ISSUE TITLE
Saving file might conflict with OneDrive

### ISSUE THREAD

**Issue by viiliainen** [Microsoft/vscode#63201]
Issue Type: <b>Bug</b>

I have some php code done on laptops D: drive (SD card) that is synced with OneDrive for Business. Saving a file makes Onedrive to make a local copy of it with new name. Dunno if this is messed up by OneDrive, Code or both.
Can't have OneDrive active when writing code with Code.

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:47:15.448Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Atom(TM) x5-Z8350  CPU @ 1.44GHz (4 x 1440)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.90GB (0.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.10.1
vscode-ai|ms-|0.3.1
azure-account|ms-|0.6.1

</details>

**Comment by roblourens** [comment]
It sounds like this is a onedrive issue, please report it to them.
