### ISSUE TITLE
Stuck while coding

### ISSUE THREAD

**Issue by tyViroth** [Microsoft/vscode#63219]
Issue Type: <b>Bug</b>

After update this IDE stuck sometime while coding and need to reopen. why?

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:46:32.773Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (4.02GB free)|
|Process Argv|C:\Users\Ty Viroth\Desktop\index.html|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
vscode-spring-boot|ecm|0.0.10
angular-bootstrap|her|4.0.9
ng-bootstrap-snippets|ktr|1.0.0
Kotlin|mat|1.7.0
mssql|ms-|1.4.0
vsliveshare|ms-|0.3.954
vetur|oct|0.13.0
LiveServer|rit|5.1.1
bootstrap4-vscode|the|4.3.0
bootstrap-3-snippets|wcw|0.1.0

</details>

**Comment by roblourens** [comment]
See https://github.com/Microsoft/vscode/issues/62970
