### ISSUE TITLE
Hangs

### ISSUE THREAD

**Issue by YevhenKysilov** [Microsoft/vscode#63214]
After saving files with the "Ctrl+S" key combination, the program hangs. After that, a window appears indicating that the program is not responding and needs to be rebooted.

**Comment by jrieken** [comment]
what version are you using?

**Comment by YevhenKysilov** [comment]
Version: 1.29.0 (user setup)
Fixing: 5f24c93878bd4bc645a4a17c620e2487b11005f9
Date: 2018-11-12T07:47:15.448Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by jrieken** [comment]
oh, this is very likely https://github.com/Microsoft/vscode/issues/62970. please try latest insiders (http://code.visualstudio.com/insiders/) which has a fix for this. we are also planning to release a recovery build (1.29.1) shortly
