### ISSUE TITLE
Wrong file location in problem tab.

### ISSUE THREAD

**Issue by jeffsmith82** [Microsoft/vscode#63211]
- VSCode Version: 1.29.0
- OS Version: Centos 7.5.1804

Steps to Reproduce:

Create a folder with a root make file and individual make files inside folders. I then have a task that calls make -C and then the sub directory that has the makefile in for the lib or app i want to build.

{
            "label": "Make SwCoreLib",
            "type": "shell",
            "command": "source scl_source enable devtoolset-7 && make -C ${workspaceFolder}/libs/SwCoreLib -j 7",
            "problemMatcher": [
                "$gcc"
            ]
        },

I get warning in the code like this.
![image](https://user-images.githubusercontent.com/1884943/48550848-beafd680-e8cb-11e8-8156-eaf3cac3e4b4.png)

But when I click on them the paths are wrong so cant open the files. The root workspaceFolder in this case is /home/build/esp/ and the file i want to open is /home/build/esp/libs/SwCoreLib/bzip2-1.0.3/bzlib.c

![image](https://user-images.githubusercontent.com/1884943/48550896-dbe4a500-e8cb-11e8-826e-8cf9dbb7211e.png)

Does this issue occur when all extensions are disabled?: I get errors so cant reproduce with extensions disabled.

**Comment by roblourens** [comment]
Is this a problem with the cpp extension, or is the `gcc` problem matcher built in?

**Comment by alexr00** [comment]
@jeffsmith82, what are the errors you get when you disable extensions? Also, do you have repo I can clone to reproduce this?

**Comment by jeffsmith82** [comment]
@alexr00 https://github.com/jeffsmith82/vscodeBug there is a simple example here setup with a task called build that should throw a warning of unused variable.

when you go into the Problems tab it has the wrong path so cant click on it.

There is no error if i disable the extensions as i don't think the ProblemMatcher for $gcc will work.

to run it again delete the main file and run the task again.

**Comment by alexr00** [comment]
In your example, your task would need to work like this:

    {
            "label": "build",
            "type": "shell",
            "command": "make -C helloWorld",
            "problemMatcher": [
                {
                "base":"$gcc",
                "fileLocation": ["relative", "${workspaceFolder}/helloWorld"]
                }
            ]
    }

There's also this issue, which seems relevant: https://github.com/Microsoft/vscode-cpptools/issues/2266

We're thinking about adding a way for tasks to do additional processing on output beyond what a problem matcher can do which would also help this.
