### ISSUE TITLE
Breadcrumb missing on first restored document when reopening a workspace using a FileSystemProvider

### ISSUE THREAD

**Issue by gjsjohnmurray** [Microsoft/vscode#63216]
- VSCode Version: 1.29.0
- OS Version: Windows 10 x64

I saw the same symptoms when using either 'Remote Workspace' or 'Remote FS', but not with a workspace that uses the local filesystem. So I think FileSystemProvider is significant. By testing with two different ones I think I have increased the probability that the issue lies within vscode rather than the extensions.

Steps to Reproduce:

1. Install an extension that implements FileSystemProvider
2. Configure a workspace that connect to a remote directory (I tested with both SFTP and FTP protocols).
3. Open two files from the remote directory (I used simple .txt files).
4. Make sure breadcrumb is turned on and is displayed for both files as you switch between the tabs.
5. Close the workspace.
6. Reopen the workspace. The remote connection is correctly re-established, and the two files are re-opened, but there is no breadcrumb on the current tab. This is the bug.
7. Switch to the other tab and see the breadcrumb appear correctly. Switch back to the first tab and its breadcrumb is also shown as expected.

**Comment by jrieken** [comment]
> I saw the same symptoms when using either 'Remote Workspace' or 'Remote FS', but not with a workspace that uses the local filesystem.

Yeah, that's a challenge. When we restore the editor and its breadcrumbs the file system provider is likely not yet known - which means we don't understand that uri... Later when the file system is registered again we should listen to the event which will cause flicker...

**Comment by jrieken** [comment]
it will now update as soon as the provider is registered again

**Comment by gjsjohnmurray** [comment]
Almost working. The breadcrumb now appears when the workspace is reopened, but the tabs don't repaint properly:
![image](https://user-images.githubusercontent.com/6726799/48702725-8a992600-ebe9-11e8-9eaf-79742ec3bb5a.png)

When I click on the almost-visible tab:
![image](https://user-images.githubusercontent.com/6726799/48702840-e368be80-ebe9-11e8-999b-73c531f75d25.png)

It gets sorted out:
![image](https://user-images.githubusercontent.com/6726799/48702877-fd0a0600-ebe9-11e8-8cab-a610f6f647a8.png)

**Comment by jrieken** [comment]
Never push without testing... you got me.

**Comment by gjsjohnmurray** [comment]
Confirmed resolved in latest Insiders. Thanks.
