### ISSUE TITLE
Option to side-by-side debug console and terminal

### ISSUE THREAD

**Issue by OysteinAmundsen** [Microsoft/vscode#63210]
First of, thanks for a fantastically flexible, smart, durable, minimalistic editor. I have actually replaced my IntelliJ IDE with VSCode completely and I'm very happy. 

I'm often running server-client architecture. Debugging is therefore in two separate processes, one outputs to Debug Console, the other to terminal. It would be great if I could drag either "Terminal" tab or "Debug Console" tab out and dock side-by-side with the other, in order to get the full overview of logging from both worlds.

**Comment by isidorn** [comment]
If you would like to find the duplicate search for issues with label "workbench-layou" and "feature-request"
