### ISSUE TITLE
Way to jump back to previous file/line after Ctrl+clicking function call

### ISSUE THREAD

**Issue by amitagrawal11** [Microsoft/vscode#63222]
There should be back and forward button should be given once user gets navigated to different files. Such as if I find function definition which is written inside another file and I gets navigated to another file on click of function definition but I can not go back to see from which file/function did i reach to this file.

Means to say as browser have back and forth functionality we should have the same functionality implemented with vscode so that user can go back to the file from which he has come.

**Comment by roblourens** [comment]
See #61103
