### ISSUE TITLE
Launching vscode opens multiple workspaces

### ISSUE THREAD

**Issue by tmds** [Microsoft/vscode#63220]
When I launch `code-insiders .` to open vscode for the working directory in a terminal, two windows are opened. One window is for the working directory, another window has a 'workspace' I was working in earlier.

I expect only one window to be opened for the working directory. It's not clear why vscode also opens another workspace.

- VSCode Version:
code-insiders --version
1.23.0-insider
b845ce918f2689344795e845ae6ef691916c3079
x64
- OS Version: Fedora 28

Steps to Reproduce:

1. execute `code-insiders .` in a terminal

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
You can customize this behavior with the setting `window.restoreWindows`

**Comment by tmds** [comment]
> You can customize this behavior with the setting window.restoreWindows

When I set restoreWindows to `none`, it still opens up two windows.
One Window still had an unsaved file, so maybe that has something to do with it.

I don't expect to see this other Window, so perhaps the default behavior is not intuitive.

Because the windows have unrelated things loaded in them, I thought of this as separate instances of code, so my initial response of `Exit`ing one, resulted into closing the one I wanted to have too (since they are both windows of the same application).

**Comment by roblourens** [comment]
> One Window still had an unsaved file, so maybe that has something to do with it.

That's correct, otherwise you would have no way to get that file back. You can customize this with `files.hotExit`

**Comment by tmds** [comment]
@roblourens the default behavior is not intuitive to me. Do you think it makes sense to most users?

**Comment by roblourens** [comment]
Regarding hot exit? I think so. If someone leaves an unsaved file open, they are probably in the middle of something, and we don't want them to think the changes were lost.

**Comment by tmds** [comment]
Regarding multiple windows opening when launching vscode with a folder argument.

**Comment by roblourens** [comment]
That only happened because the other window had unsaved changes though, right?

**Comment by tmds** [comment]
Yes, that could be. Adding additional windows on the next vscode launch for dealing with unsaved changes is very intrusive to me.
Suggesting some alternatives:
Show unsaved changes in the opened window for files in opened workspace folders.
Add a way to get a list of files that were never saved and open them on-demand.

**Comment by roblourens** [comment]
It's been discussed, there may be an open feature request. But in any case, it's configurable to your preference.
