### ISSUE TITLE
[Integrated Terminal] Next/Prev panel not switching

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#63223]
Using kind of similar code to suggested in release notes:
```json
{
    "key": "ctrl+]",
    "command": "workbench.action.nextPanelView",
    "when": "panelFocus"
},
{
    "key": "ctrl+[",
    "command": "workbench.action.previousPanelView",
    "when": "panelFocus"
}
```
Not working until added to `terminal.integrated.commandsToSkipShell`. Should they be there by default?

**Comment by octref** [comment]
I think the principle is navigation commands should always be skipped. @alexr00 can you add these two commands and `workbench.action.[previous|next]SideBarView` to the skip commands?

**Comment by octref** [comment]
Also opened https://github.com/Microsoft/vscode/issues/63271...
