### ISSUE TITLE
Spawning a new terminal (powershell) results in a blank window with unexpected behavior

### ISSUE THREAD

**Issue by saifali96** [Microsoft/vscode#63229]
Starting today after I updated my Windows 10 from 1803 to 1809, if I spawn/start a new terminal or add a new terminal, I see only a blank window/prompt. Please refer to the following pictures.
[imgur 1](https://imgur.com/a/BbjjM5Y)
[imgur 2](https://imgur.com/a/lT1PzPk)
[imgur 3](https://imgur.com/a/9Di7jNG)
[imgur 4](https://imgur.com/a/t90O5Ua)

Additionally `Ctrl + L` is also resulting in strange/unexpected behavior. It does clear the screen/terminal but after you start writing again, it retains the previous output. please refer to this image below:
[imgur 5](https://imgur.com/a/QPy2a0N)

- VSCode Version: 1.29.0
- OS Version: Windows 10, 1809 (Version 10.0.17763.134)

Steps to Reproduce:

1. Press `Ctrl + ' ` to open the Terminal.

Does this issue occur when all extensions are disabled?: Yes

**Comment by saifali96** [comment]
Removed and reinstalled the latest VSCode, the issue still persists.

**Comment by roblourens** [comment]
#57803
