### ISSUE TITLE
[CSS] url() in variables, and targeting by ctrl + lclick in imported file

### ISSUE THREAD

**Issue by Mlocik97-issues** [microsoft/vscode#63225]
Issue Type: <b>Bug</b>

When I use something like:

```
.container {
    background-image: var(--noise);
};

/* a lot of code */

:root {
    --noise: url(data:image/png;base64, ........ ==);
};
```

I can click on var(--noise), and it show me data:img URI code. But if I use import, and I write 
```
.container {
    background-image: var(--noise);
};
```
in imported file... it doesn't show me code, also I can't click on it by ctrl + lclick to open file, where is --noise defined.

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:47:15.448Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (9.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by octref** [comment]
Depends on #28459.

**Comment by aeschli** [comment]
duo of #28459.
