### ISSUE TITLE
vscode struggles to auto-import lodash

### ISSUE THREAD

**Issue by tnrich** [Microsoft/vscode#63239]
Hey there, does anyone know why vscode struggles to auto-import lodash modules?

![image](https://user-images.githubusercontent.com/2730609/48579653-f3bf2780-e8d1-11e8-9d58-affcb2887e4e.png)

Here I'm looking for lodash's array.compact method, but while recompose has an auto-import suggested, lodash's auto-import doesn't seem to want to show up:

I've opened this same issue on lodash's repo and @jdalton wasn't sure why lodash's auto-import isn't working in vscode. 

https://github.com/lodash/lodash/issues/4062

Thanks!

**Comment by tnrich** [comment]
@vscodebot thanks but I don't think either of those issues are the same as mine.

**Comment by joseph1125** [comment]
Is this project a typescript project or JavaScript project?

**Comment by tnrich** [comment]
Java script

**Comment by joseph1125** [comment]
Have you tried reinstalling lodash?

Thomas Rich <notifications@github.com> 於 2018年11月16日 週五 08:15寫道：

**Comment by nhardy** [comment]
I also experience this with TypeScript projects.

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/29039 to track this upstream
