### ISSUE TITLE
Arduino Board Configuration Issue

### ISSUE THREAD

**Issue by cemoke** [Microsoft/vscode#63236]
Issue Type: <b>Bug</b>

I installed VSCode in my Macbook Pro running macOS Mojave (10.14) also installed the Arduino extension. 

I have also installed Arduino IDE 1.6.2 since previous releases than  version 1.7 are recomended for the extension. 

However when i try to install package by using Board Manager from Command Palette. After the installation is done nothing changes and Vscode acts like i did not install the package. ( I can still see the install button and nothing is written like installed) Also when i search for the boards only AVR boards seems available to upload the code.

I will be glad if any help is provided. 

Thank you

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:39:38.932Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (0.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-dash|dee|2.0.0
python|ms-|2018.10.1
cpptools|ms-|0.20.1
vscode-arduino|vsc|0.2.22

</details>

**Comment by sean-mcmanus** [comment]
Another user at https://github.com/Microsoft/vscode-cpptools/issues/2833 reported that install button wasn't working.

**Comment by roblourens** [comment]
Are you talking about the extension, or some package from the extension?

**Comment by sandy081** [comment]
@cemoke Can you please let us know what extension are you installing? It will be helpful if you show some screenshots or a gif.

Thanks

**Comment by cemoke** [comment]
@sean-mcmanus  actually i believe this is not the case. Since the install button working and also it installs the package. However the issue is after installing, it does not recognize the downloaded package i believe.

@roblourens i successfully downloaded and installed Arduino extension everything seems fine. However, when i try to use Arduino extension's Board Manager to install Arduino SAM Boards package (or any other package than AVR ) i can not install it. 

@sandy081 Arduino extension is installed without any problem but i have problems with board packages. I believe necessary ss will be as follows:


<img width="500" alt="screen shot 2018-11-17 at 15 10 02" src="https://user-images.githubusercontent.com/40527576/48660920-f9a43c80-ea7a-11e8-8272-96dd369d912d.png">

<img width="515" alt="screen shot 2018-11-17 at 15 10 19" src="https://user-images.githubusercontent.com/40527576/48660922-fe68f080-ea7a-11e8-9c2f-f467e009fb42.png">
 and finally the output message i got from the vscode when i try to install SAM board package.
<img width="1019" alt="screen shot 2018-11-17 at 15 10 36" src="https://user-images.githubusercontent.com/40527576/48660925-09238580-ea7b-11e8-9eeb-138760cdfaed.png">

**Comment by sean-mcmanus** [comment]
Can you file an issue at https://github.com/Microsoft/vscode-arduino/issues ? This sounds like an Arduino extension issue.

**Comment by sandy081** [comment]
Please file an issue against arduino extension - https://github.com/Microsoft/vscode-arduino/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
