### ISSUE TITLE
SQL highlighting inside single-line comment

### ISSUE THREAD

**Issue by moseleyi** [Microsoft/vscode#63235]
I don't have any highlighting extensions installed. Reformatted my laptop recently and only installed few extensions (Git, SSH, Trailing Spaces, Apache Conf, and Egoist One)

- VSCode Version: 1.29.0
- OS Version: Windows 10 Home

Steps to Reproduce:

1. Open new file, save it as *.sql
2. Type comment that includes some of the words used in SQL for example:

# One thing to remember is that

That's what it looks like
![vscode_issue](https://user-images.githubusercontent.com/16131590/48576104-a9de3d80-e8e1-11e8-9016-cff7cf8e3d21.jpg)

That's what it looks like if I use multi-line comment
![vscode_issue2](https://user-images.githubusercontent.com/16131590/48576164-cbd7c000-e8e1-11e8-9c51-a0ee1ed92309.jpg)

**Comment by mkenigs** [comment]
Looks like the issue is you're expecting MySQL highlighting instead of SQL highlighting - installing the package MySQL Syntax should resolve it.

**Comment by roblourens** [comment]
Thanks @mkenigs
