### ISSUE TITLE
Output panel contains scrollbar remnant even when empty

### ISSUE THREAD

**Issue by beastdestroyer** [Microsoft/vscode#63234]
- VSCode Version: 1.29.0-exploration
- OS Version: Windows 10 1803 17134.407

Steps to Reproduce:

1. Open panel
2. Switch to Output if not already
3. Look at panel's Right hand side and see scrollbar remnant

![image](https://user-images.githubusercontent.com/30497573/48575934-1d487500-e90b-11e8-9e41-4cc7408d1131.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Pretty sure this is by design, empty editors have a scrollbar too even when not scrollable.

**Comment by beastdestroyer** [comment]
But the Output panel is non-editable? And all the other panels have like this overlay scrollbar in a sense. Switch to terminal, and press enter a bunch of times to scroll, you'll see the scrollbar is different. I saw this with the Problems panel too

**Comment by sandy081** [comment]
I know this is an implementation detail but Output panel uses the Editor underneath hence it is shown. @alexandrudima Is there a way to not to show the scroll bar in such cases?

**Comment by alexandrudima** [comment]
That is not the scrollbar, but the overview ruler. There is an option to not draw that border called `overviewRulerBorder`.

**Comment by sandy081** [comment]
As @alexandrudima said this is a overview ruler and output panel is an editor behind and may be some extension authors or users might be depending on it, I am not going to change it.
