### ISSUE TITLE
comment

### ISSUE THREAD

**Issue by kennychen0606** [Microsoft/vscode#63230]
Issue Type: <b>Bug</b>

in django html comment key set (ctrl + / ) sometimes use <-- --> sometimes use {% comment %}{% endcomment%} how can i setup what i need

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:47:15.448Z)
OS version: Windows_NT x64 10.0.17134

**Comment by aeschli** [comment]
Do you use https://github.com/iambibhas/vscode-django-template?

**Comment by kennychen0606** [comment]
I have solved the problem.Thank you.
