### ISSUE TITLE
Selection prompt to extract method not worked

### ISSUE THREAD

**Issue by lishali12345** [Microsoft/vscode#6323]
- VSCode Version:Version 1.1.0 (1.1.0)
- OS Version: Mac OS X EI Capitan

Steps to Reproduce:

1. Selection some lines code inside a method, will not show the prompt which will contains two menu item, just like "Extract Method" and "Use explicit type", which can be found in [the release notes of v0.7.0](https://code.visualstudio.com/updates/v0_7_0#_c35)
2. I just can not do this, and I google a lot for this, then I got nothing, so I'm here.

**Comment by isidorn** [comment]
Do you have the C# extension installed? If yes and you still see the issue please file an issue against the C# extension here https://github.com/OmniSharp/omnisharp-vscode

You can get the extension here https://marketplace.visualstudio.com/items/ms-vscode.csharp
