### ISSUE TITLE
Windows is Not Responding since upgrade

### ISSUE THREAD

**Issue by ssandler** [Microsoft/vscode#63233]
Issue Type: <b>Bug</b>

Ever since the latest upgrade, I get "The Window is No Longer Responding" several times per day. I had not seen this popup before this release, and haven't changed my extensions recently.

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:39:38.932Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (1.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.2.0
prettier-vscode|esb|1.7.2
smarty|imp|0.3.0
trailingwhitespacehighlighter|paj|0.0.2
vscode-hack|pra|1.1.0
save-and-run|wk-|0.0.21

(1 theme extensions excluded)

</details>

**Comment by juncgu** [comment]
Same issue on MacOS since 1.29.0
![window](https://user-images.githubusercontent.com/6314092/48579899-b36ca300-e8eb-11e8-92c9-5a08f1865010.png)

**Comment by sean-mcmanus** [comment]
I got it too on Windows (1.29). I wasn't doing anything in particular (debugging C++ code).

![image](https://user-images.githubusercontent.com/19859882/48588325-802a1400-e8eb-11e8-910a-e9e8ffdb49e0.png)

**Comment by roblourens** [comment]
Try 1.29.1, we fixed an issue like this.
