### ISSUE TITLE
Add Configuration not working

### ISSUE THREAD

**Issue by boogermanus** [Microsoft/vscode#63242]
Issue Type: <b>Bug</b>

When  open certain large AngularJS projects that use typescript the Add Confirugation option on the Debug view does not work. It is missing the splitter, and clicking on it does nothing.

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:47:15.448Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (5.41GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
hg|mrc|1.2.3
mssql|ms-|1.4.0
python|ms-|2018.10.1
csharp|ms-|1.17.0
PowerShell|ms-|1.9.0
debugger-for-chrome|msj|4.11.1

</details>

**Comment by isidorn** [comment]
Can you reproduce the issue with vscode insiders https://code.visualstudio.com/insiders/
If yes, can you please share your launch.json file for wich the Add Configuration option does not work
Thanks
