### ISSUE TITLE
Preselected item in completition dropdown is not properly focused on initial show

### ISSUE THREAD

**Issue by SirIntruder** [Microsoft/vscode#63245]
Issue Type: <b>Bug</b>

Currently, completition providers can set "preselect: bool?" for completition items, and if an item has a preselected flag set it gets displayed to the user as default completition in the dropdown.

BUG is: dropdown selects preselected item properly, but scroll on the dropdown doesn't go to match that, and stays on the top of the list. That would be behaviour if there was no preselect item present.

Bug is reproduced every time I open completition dropdown with ctrl+space.

In the GIF example I provided, you can see that Dictionary<T, V>() was properly seleted in the list, but I had to press down key on the keyboard to see that.

Completition here is provided by c# ext, but it looks like a pure editor issue.

![preselectbug](https://user-images.githubusercontent.com/5102661/48584650-93100900-e92a-11e8-9684-dc2c7f8a635d.gif)

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:47:15.448Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (10.94GB free)|
|Process Argv|C:\Git\misacar\ageOfCastles|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
shaderlabvscodefree|aml|1.1.3
vscode-icontheme-nomo-dark|be5|1.3.6
gitlens|eam|8.5.6
docomment|k--|0.1.2
csharpfixformat|Leo|0.0.76
unity-snippets-modified|lio|0.4.0
csharp|ms-|1.17.1
vscode-icons|rob|7.28.0
shader|sle|1.1.4
unity-debug|Uni|2.6.6

(1 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
Yeah, it probably misses a call to reveal...

**Comment by jrieken** [comment]
@joaomoreno I do call reveal (now with `0`, before (clamped `1`) but it still doesn't reveal anything. Debugging into this does show that the list as a height et al. This is where stuff happens: https://github.com/Microsoft/vscode/blob/66b963d0cd39378d92c1b220f38d169eb0efd577/src/vs/editor/contrib/suggest/suggestWidget.ts#L779

**Comment by joaomoreno** [comment]
@jrieken Maybe we debug it together?

**Comment by joaomoreno** [comment]
This is now fixed!
