### ISSUE TITLE
Can't start debugging after windows update

### ISSUE THREAD

**Issue by rosanch** [Microsoft/vscode#63240]
Issue Type: <b>Bug</b>

I got a windows update. After this I wasn't able to debug my code. It never lunches the program.

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:47:15.448Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.73GB (17.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
gitlens|eam|8.5.6
tslint|eg2|1.0.40
vscode-pull-request-github|Git|0.2.3
python|ms-|2018.10.1
azure-account|ms-|0.6.1
vscode-docker|Pet|0.3.1
vscode-yaml|red|0.1.0
vscodeintellicode|Vis|1.0.6

</details>

**Comment by roblourens** [comment]
Please include as many details as possible

**Comment by isidorn** [comment]
Also can you reproduce with vscode insiders https://code.visualstudio.com/insiders/

**Comment by rosanch** [comment]
I was able to fix this by removing everything from VS code and reinstalling the software
