### ISSUE TITLE
Do Not Show Again for "Cannot update on a read-only volume"

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#63247]
Can we have a "Do not show again" for this one?

~~This even happens for portable mode.~~

![image](https://user-images.githubusercontent.com/4033249/48585122-849cff80-e8e0-11e8-85cb-cc44da779a64.png)

Repro:

- Download Code to desktop on macOS
- Run it

**Comment by joaomoreno** [comment]
Actually I prefer if we don't have such an action. This is pretty important and clicking that action would potentially put the user in a situation in which he wouldn't get any updates nor be notified by it.

**Comment by octref** [comment]
My use case is usually when I'm testing, I would need to download a 1.30-stable-prerelease. I used to be able to run it directly by putting it to desktop, but now I have to replace my VS Code stable in `/Applications` just for testing, and download stable again once I'm done.

**Comment by joaomoreno** [comment]
But when testing it's actually good that the update can't run at all, keeping that version. You can just ignore the error message when testing, right?

**Comment by octref** [comment]
That's why I was asking "Do Not Show Again" 😜. But if it has to be un-ignorable that's fine too.
