### ISSUE TITLE
If you cancel open file or folder dialog, it opens again

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode#63241]
Issue Type: <b>Bug</b>

1) File->Open Folder...
2) click Cancel
!) The open folder dialog closes and then opens up again
3) click Cancel
4) this time it stays closed

VS Code version: Code - Insiders 1.29.0-insider (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-10T00:34:03.196Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.73GB (19.27GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/stephwe/Repos/AzureACR/vscode-docker|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.40
vscode-antlr4|mik|2.0.4
vscode-azureappservice|ms-|0.9.1
vscode-azurestorage|ms-|0.4.2
vscode-cosmosdb|ms-|0.9.0
extension-manifest-editor|ms-|0.1.5
azure-account|ms-|0.6.1
csharp|ms-|1.17.1
azurerm-vscode-tools|msa|0.4.2
vscode-docker|Pet|0.3.1

</details>

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/62524
