### ISSUE TITLE
A11y_ViennaVsCodeExtension_ExplorerTAB_Usability: Instruction not provided for right click menu in toolbar section for screen reader users.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#63255]
“Check out Keros! - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

Environment Details:
Application Name: ViennaVsCodeExtension
Application Version: 1.28.0
Operating System: Windows10
Url:  https://marketplace.visualstudio.com/items?itemName=ms-toolsai.vscode-ai#overview

Repro Steps:
1) Launch VisualStudio Code.
2) Start Narrator
3) Navigate to Explorer Tab hit Space bar key-> Navigate to toolbar section-->Right click on any toolbar.

Actual
In the Toolbar section, when we right click on any toolbar new menu get opend. but there is no any screen reader user instruction available for this right click menu feature.

This is common across application

Expected
There should be instruction available before entering into the Toolbar section for this "Right click" menu feature.

User Impact
Screen reader user will not be able to understand about this feature.

**Comment by greazer** [comment]
Looks like I forgot to add the video the accessibility people made: [704283_A11y_ViennaVsCodeExtension_ExplorerTAB_Usability(1).zip](https://github.com/Microsoft/vscode/files/2591162/704283_A11y_ViennaVsCodeExtension_ExplorerTAB_Usability.1.zip)

**Comment by roblourens** [comment]
Sorry for the slow response but I don't understand 100%, is the problem that the screenreader doesn't read the commands inside the context menu?
