### ISSUE TITLE
Multi ports for remote debug 

### ISSUE THREAD

**Issue by yafacex** [Microsoft/vscode#63269]
my servers has many processes,Can I remote debug each process in one vscode instance? 
each process launch  "--inspect" with diffrent ports, and vscode debug them at the same time?

**Comment by weinand** [comment]
Yes, you can debug any number of processes within one VS Code.
Either create multiple launch configs (for different debug ports).
Or use the "autoAttachChildProcesses" feature of VS Code's node.js debugging:
https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_automatically-attach-debugger-to-nodejs-subprocesses

**Comment by yafacex** [comment]
It works fine.Thank you so mush!
