### ISSUE TITLE
ripgrep triggers Windows Defender even if not doing any search

### ISSUE THREAD

**Issue by yhvicey** [Microsoft/vscode#63267]
- VSCode Version: 1.29.1
- OS Version: Windows 10 1809

Steps to Reproduce:

1. Open VSCode
2. You will see rg.exe takes ~10% CPU Usage (Intel E5-1630 v4) per instance:
![image](https://user-images.githubusercontent.com/8000820/48596029-27fa1d00-e992-11e8-904b-8075568bfad2.png)
![image](https://user-images.githubusercontent.com/8000820/48596033-2d576780-e992-11e8-88fd-26028f2d062b.png)

Does this issue occur when all extensions are disabled?: Not sure, occurs randomly and might not be able to repro

P.S.: From procexp it seems summoned by `searchService`:
![image](https://user-images.githubusercontent.com/8000820/48596077-6099f680-e992-11e8-895a-aaf58a45b123.png)

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/63070
