### ISSUE TITLE
Can't open file from keyboard.

### ISSUE THREAD

**Issue by lborgman** [Microsoft/vscode#63260]
Issue Type: <b>Bug</b>

Please see here: 
https://stackoverflow.com/questions/53325051/open-a-file-in-vscode-from-keyboard

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:47:15.448Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU N4200 @ 1.10GHz (4 x 1094)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.84GB (0.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.7.0
beautify|Hoo|1.4.7
vim|vsc|0.16.12

</details>

**Comment by roblourens** [comment]
It sounds like you're using the native file open dialog, which we don't control. Does quick open (ctrl+p) fit your needs?

**Comment by lborgman** [comment]
Thanks, but it doesn't because vscodevim takes that combination, I think.

I have set the option

    "vim.useCtrlKeys": false

but Vim still takes it. (Which looks like a bug in vscodevim to me.)

**Comment by lborgman** [comment]
@roblourens
That the Ctrl+O dialog can't be used entirely from the keyboard is of course a bug in Windows 10. Could you please further this?

**Comment by roblourens** [comment]
If vscodevim prevents you from using ctrl+p you can change the keybinding or file an issue on that extension. I can't help with the windows dialog though.

**Comment by lborgman** [comment]
Thanks, but I know if course I can change the key binding. However it doesn't help at all with this issue.

I have no idea where to report the issue (and getting support). That is why I tried here. If you know someone who might know this, then please forward it.

I think closing the issue just because you can't fix it is not productive. (Microsoft is very much involved here.)

**Comment by roblourens** [comment]
It really seems like an issue with this extension, so please file the issue there: https://marketplace.visualstudio.com/items?itemName=vscodevim.vim

**Comment by lborgman** [comment]
Thanks. There are actually two issues. One with the extension. And one with this new file open dialog in Windows 10.

I just had not had time to file the first issue. The second one is really impossible to file without better contacts. (Since no one really knows how to handle big volumes of bug reports.)
