### ISSUE TITLE
Workbench docking button disappeared

### ISSUE THREAD

**Issue by bigopon** [Microsoft/vscode#63263]
At the moment, this is how my workbench looks like
![image](https://user-images.githubusercontent.com/9994529/48592312-e5d5d900-e99b-11e8-9ce0-4321e9112b35.png)

It happened after an upgrade, awhile ago and I thought it was specific to insiders, but just yesterday, my normal vscode just got the same issue after an upgrade,

Does this issue occur when all extensions are disabled?: YES

**Comment by roblourens** [comment]
What is the issue exactly?

**Comment by bigopon** [comment]
There used to be a button to dock the workbench either on the right, or at the bottom. You can see from the image that it's gone

**Comment by roblourens** [comment]
I think you are looking for this: https://code.visualstudio.com/updates/v1_29#_panel-position-button-to-context-menu

**Comment by bigopon** [comment]
Awesome ... I missed that. Thanks
