### ISSUE TITLE
Update Issue

### ISSUE THREAD

**Issue by SambaiahY** [Microsoft/vscode#63262]
Issue Type: <b>Bug</b>

Hi Team,
It is showing that, there is an update, when I click on update it is not updating.

again it is showing update notification.

Thanks,
Sambaiah Y

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2370M CPU @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.90GB (1.54GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-github|Kni|0.30.0
debugger-for-chrome|msj|4.11.1
ionic2|Tha|3.0.2

</details>

**Comment by roblourens** [comment]
It looks like you are on a very old version! Can you tell us exactly what happens when you click on update? You can also just try reinstalling...
