### ISSUE TITLE
Snow in terminal from resume after suspend (Linux Mint / Nvidia graphics)

### ISSUE THREAD

**Issue by garrickevans-ca** [Microsoft/vscode#63265]
Issue Type: <b>Bug</b>

System: Ryzen 5 2600, Nvidia GTX 670, 16 GB RAM, MSI TOMAHAWK B450
Kernal: 4.15.0-39-generic
Nvidia Driver: 415.13
Linux Mint 19 TARA
VS CODE Ver: 1.28.2

Every time system Suspend and resume, snow appears in VS CODE terminal.

* If you close the terminal and reopen in VS Code. It's still there.
* If you have 2 terminals. It's still there.
* Only way to get ride of it is end the terminal session (garbage can) and start a fresh session.
* Does not effect regular system terminal or Atom.io terminal.

* Replicated problem: Installed another fresh version with Linux Mint / Nvidia & VS code. Problem still persisted.

[Picture of snow in terminal](https://imgur.com/MB9skX6)

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:20:56.183Z)
OS version: Linux x64 4.15.0-39-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor (12 x 3202)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|15.68GB (6.88GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
laravel-blade|cjh|1.1.2
vue-peek|dar|1.0.2
vscode-eslint|dba|1.7.0
EditorConfig|Edi|0.12.5
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.7.2
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vue-snippets|hol|0.1.9
beautify|Hoo|1.4.7
vscode-attrs-sorter|mrm|2.1.0
mssql|ms-|1.4.0
vuejs-extension-pack|mub|1.1.3
printcode|nob|3.0.0
vetur|oct|0.13.0
laravel-blade|one|1.18.0
advanced-new-file|pat|1.2.0
code-settings-sync|Sha|3.2.0
vscode-status-bar-format-toggle|tom|1.4.0
JavaScriptSnippets|xab|1.7.1

(1 theme extensions excluded)

</details>

**Comment by dakota-hawkins** [comment]
I have the same issue, also running Linux Mint 19.

**Comment by Tyriar** [comment]
This is caused by Chromium

**Comment by garrickevans-ca** [comment]
> This is caused by Chromium

If you are referring to the browser. No Chrome/Chromium browser is installed.
(Even if it was, that should not effect VS Code)

This problem is even repeatable on:
GeForce GTX 750
Intel(R) Pentium(R) CPU G3258 @ 3.20GHz
4.15.0-20-generic
nvidia-driver-390
Linux Mint 19

(This system is INTEL & a different Nvidia make model Card) -> Same result.
![screenshot from 2018-12-01 09-42-17](https://user-images.githubusercontent.com/29846759/49329571-0c287680-f54f-11e8-8aa9-e60507eab479.png)

VS Code:
Version: 1.29.1
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:07:43.495Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by Tyriar** [comment]
VS Code uses Electron which is built on Chromium, this is a bug with Chromium not retaining the canvas texture after sleep.

**Comment by garrickevans-ca** [comment]
I appreciate the clarification.
Thank you.
