### ISSUE TITLE
aspnetcorerazor  format error

### ISSUE THREAD

**Issue by niltor** [Microsoft/vscode#63276]
Issue Type: <b>Bug</b>

Open a .cshtml, just like _Layout.cshtml,and you'll see:

![image](https://user-images.githubusercontent.com/8222201/48603523-ab773680-e9b1-11e8-9d1a-62b042b75903.png)

I had tried reinstall vscode,but can't solve problem.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (6.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.21.0
vscode-language-pack-zh-hans|MS-|1.29.2
csharp|ms-|1.17.1

</details>

**Comment by alexr00** [comment]
Does this reproduce with the three extensions you have disabled?

**Comment by niltor** [comment]
@alexr00  not disabled.
Infact ,csharp extension is necessary  for  razor language,when i just install this extension without other extensions, it is the same problem.

**Comment by alexr00** [comment]
Looks like this is an issue with the csharp extension then!

**Comment by alexr00** [comment]
The extensions readme should tell you some way to report issues to them since they're the ones who will need to fix it.
