### ISSUE TITLE
C/C++ highlight error

### ISSUE THREAD

**Issue by ZCShou** [Microsoft/vscode#63273]
Issue Type: <b>Bug</b>

#define IS_UPGRADE_ADDR(addr)					(/*((addr) >= UPGRADE_BASE_ADDR) && */(addr) < UPGRADE_BASE_ADDR + UPGRADE_SPACE_SIZE)

The code after the comments will not be highlighted. such as above

VS Code version: Code - Insiders 1.30.0-insider (df8ea54c5397e67b3e47df15a355bd04345c6934, 2018-11-15T06:21:02.187Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.83GB (2.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|9.1.0
xml|Dot|2.3.2
gitlens|eam|8.5.6
reg|ion|0.0.2
cpptools|ms-|0.21.0-insiders
java|red|0.33.0
vscode-icons|rob|7.28.0
vscode-java-debug|vsc|0.15.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.10.0
vscode-maven|vsc|0.11.1

</details>

**Comment by alexr00** [comment]
This issue was moved to atom/language-c#307
