### ISSUE TITLE
Wrong block lighting

### ISSUE THREAD

**Issue by coaperator** [Microsoft/vscode#63274]
- VSCode Version: 1.29.1
- OS Version: Win 10 October Update

**Correctly**
![img1](https://user-images.githubusercontent.com/6645911/48601832-380a0080-e982-11e8-9309-a209bf3e3087.png)

**Wrong**
![img2](https://user-images.githubusercontent.com/6645911/48601840-3d674b00-e982-11e8-93fd-b28260d505b4.png)

**Comment by alexr00** [comment]
What extensions do you have installed? Does this reproduce if you uninstall all of them?
