### ISSUE TITLE
Getting exception "This socket has been ended by the other party" wen debuggin extension.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#6327]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows10

I am not certain if this is the real issue with product or not. But thought to give heads up if something we need to handle at API level.

Steps to Reproduce:
1. Generate VSCode extension project  using Yeoman
2. Open VS code and open generated folder.
3. Start debugging by following instruction mentioned at  https://code.visualstudio.com/docs/extensions/example-hello-world
4. Verify debug point hit under extension project once you try to add hello world extension.
5. Try to execute "extension install command" from command palette in newly launched instance of VSCOde and then clean all the text using backspace key.
Actual: Getting exception: ""This socket has been ended by the other party""
Expected: There should not be any exception triggered when you perform common operations on newly launched VSCode instance.
![extensiondebuggingissue](https://cloud.githubusercontent.com/assets/17735796/15222549/1e4741fc-1825-11e6-88c3-fc2de86b2e5b.gif)

**Comment by isidorn** [comment]
Asigning to may to try to reporduce

**Comment by isidorn** [comment]
Can not reproduce neither on win10 neither on mac.
