### ISSUE TITLE
Non-legacy search seems to always use git ignore

### ISSUE THREAD

**Issue by Srekel** [Microsoft/vscode#63277]
Issue Type: <b>Bug</b>

We have a project structure that looks like this:

```
\gameengine
     \.git
     \<various_engine_folders>
     \actualgame
            \.git
            \<more folders>
```

I have a workspace set up for this. In it I use

    "search.useIgnoreFiles": false,

because otherwise the "actualgame" folder won't be searched - it's speciified in the gameengine's git ignore.

But now I started up VS Code after updating to the latest version and now search (find-in-files) would not find anything in the game folder, unless I opened a file that had the search term in it.

Use Global Ignore Files is false.

When I enabled "Use Legacy Search", the search started working again. It says it supports more text encodings, but we use UTF-8 with \n line endings throughout.

Are there any other settings I may have missed?

**Info from VS Code:**

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (18.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
vsctoix|a-b|1.1.1
better-comments|aar|2.0.3
overtype|ada|0.2.0
Bookmarks|ale|9.2.0
markdown-emoji|bie|0.0.7
markdown-preview-github-styles|bie|0.1.4
bracket-pair-colorizer|Coe|1.0.61
smoothscroll|cya|1.0.4
vscode-markdownlint|Dav|0.21.0
githistory|don|0.4.3
EditorConfig|Edi|0.12.5
LogFileHighlighter|emi|2.4.2
asciidecorator|hel|0.2.0
beautify|Hoo|1.4.7
contextualduplicate|laf|0.2.0
MagicPython|mag|1.1.0
python|ms-|2018.10.1
cpptools|ms-|0.20.1
indent-rainbow|ode|7.2.4
material-icon-theme|PKi|3.6.0
subtle-brackets|raf|3.0.0
snake-trail|ric|0.6.0
code-settings-sync|Sha|3.2.0
trailing-spaces|sha|0.2.11
markdown-preview-enhanced|shd|0.3.11
indenticator|Sir|0.6.0
vscode-fileutils|sle|2.13.3
shader|sle|1.1.4
vscode-hexdump|sle|1.7.2
user-extensions|srf|1.0.1
code-spell-checker|str|1.6.10
ninja|sur|0.0.1
python|tht|0.2.3
sort-lines|Tyr|1.7.0
markdown-all-in-one|yzh|1.7.0

(2 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/63128
