### ISSUE TITLE
Snippets, shortcuts and extension sometimes suddenly stop working

### ISSUE THREAD

**Issue by Mestika** [Microsoft/vscode#63282]
VSCode Version: Code 1.29.0 (2018-11-15T18:59:37.244Z)
OS Version: MacOS X 10.14.1 (18B75)

| Extension | Version |
| --- | --- |
| All Autocomplete | 0.0.17 |
| Auto Close Tag | 0.5.6 |
| Auto Rename Tag | 0.0.15 |
| Beautify | 1.4.7 |
| Bookmarks | 9.2.0 |
| ES5 to ES6 | 1.0.2 |
| ESLint | 1.7.0 |
| File Utils | 2.13.3 |
| GitLens | 8.5.6 |
| Handlebars | 0.4.1 |
| JavaScript (ES6) code snippets | 1.7.1 |
| Laravel Artisan | 0.0.23 |
| Log Wrapper | 1.0.2 |
| Markdown All in One | 1.7.0 |
| Partial Diff | 1.4.0 |
| PHP Extension pack | 1.0.2 |
| PHP IntelliSense | 2.3.10 |
| vscode-icons | 7.28.0 |

- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Happens randomly (seemingly) / can't deliberately recreate
2. ?

Sometimes when working all my snippets, shortcuts and extensions (such as bookmarks, log wrapper, etc.) seemingly out of nowhere stops to work.

I've a `console.log` snippet for JavaScript, triggered with keys `cl` but nothing happens. The same for all snippets. 
The `Intellisense` also stops to work.

The only way I know to "fix" it is by restarting the editor and then it works again for unknown period of time. It can be fine for days or it can "stop" working after 10 minutes.

Don't know if I'm accidentally hitting some weird key-combination but looking into settings and shortcuts hasn't given me any clue so far.
It almost feels like the editor is not in `focus` or something.

**Comment by jrieken** [comment]
Please try again with 1.29.1 which we released yesterday. It fixes a freeze that happens while working with VS Code.

**Comment by Mestika** [comment]
I updated to 1.29.1 and after 1 hour it happened again :-(

**Comment by jrieken** [comment]
Ok please try without extensions, it might be that one extension is "stuck" and thereby blocks all other extensions from computing suggestion. The command is `code --disable-extensions`. You can also use Insiders (http://code.visualstudio.com/insiders/) which has now better logging for things extensions are doing.

**Comment by mkallies** [comment]
This happens to me as well.  I noticed we have a couple of extensions in common.  I checked out the Auto Rename Tag repo and found this https://github.com/formulahendry/vscode-auto-rename-tag/issues/70.  I'm going to uninstall and see how it goes!

**Comment by tylerstephens814** [comment]
I have this problems too. Right after I updated, all my snippets from other extension stopped working. Specifically I use Django Snippets for Django template files, and after the update the snippets don't work, but the syntax highlighting still does.

**Comment by Mestika** [comment]
@mkallies did it solve anything to disable the auto-rename extension?
I've actually not have experienced this issue for a couple of days now but this is normal behaviour, sometimes there can goes days between.

**Comment by jrieken** [comment]
closing because this issue is without actionable information
