### ISSUE TITLE
File saving problem

### ISSUE THREAD

**Issue by mysmlz** [Microsoft/vscode#63286]
Issue Type: <b>Bug</b>

After modifying the file, the tab does not prompt "small dot" to save, nor does it prompt to save after closing. It can only be saved manually "ctrl + s". After reopening, it is still the modified state, not the original state.

====

VS Code version: Code - Insiders 1.30.0-insider (24b0f75b1e33b88f30f2ed9d5b17ca60062c270b, 2018-11-16T06:20:02.054Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.94GB (1.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-github|Kni|0.30.0
vscode-language-pack-zh-hans|MS-|1.29.2

</details>

**Comment by bpasero** [comment]
@mysmlz could it be that you have auto save enabled?
