### ISSUE TITLE
Terminal on right side

### ISSUE THREAD

**Issue by jackoliver** [Microsoft/vscode#63289]
Issue Type: <b>Bug</b>

The ability to move the Terminal panel to the right side is no-longer working, either through config or through UI button (which is now missing).

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-caniuse|aka|0.5.3
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.7.0
vscode-great-icons|emm|2.1.44
vsc-material-theme|Equ|2.5.1
prettier-vscode|esb|1.7.2
git-project-manager|fel|1.7.1
icon-fonts|idl|2.1.4
vscode-placeholder-images|Jak|0.1.0
vscode-circleci|jva|0.5.0
vscode-codemetrics|kis|1.17.3
vscode-duplicate|mrm|1.2.1
python|ms-|2018.10.1
atom-keybindings|ms-|3.0.4
cpptools|ms-|0.20.1
debugger-for-chrome|msj|4.11.1
react-proptypes-intellisense|OfH|1.0.3
code-stats-vscode|riu|1.0.12
code-settings-sync|Sha|3.2.0
vscode-spotify|shy|3.0.4
vscode-react-native|vsm|0.6.18
quokka-vscode|Wal|1.0.165
vscode-import-cost|wix|2.9.0
html-css-class-completion|Zig|1.17.1

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Read the release notes please.

**Comment by sterproton** [comment]
same bug here
![snipaste_2018-11-23_15-48-35](https://user-images.githubusercontent.com/28805644/48932516-6023d180-ef37-11e8-9f15-d128e7de5836.png)

**Comment by sterproton** [comment]
the button that move the terminal panel to right  is disapear

**Comment by jackoliver** [comment]
Right click! :)
*Jack Oliver*
