### ISSUE TITLE
无法保存

### ISSUE THREAD

**Issue by mysmlz** [Microsoft/vscode#63281]
Issue Type: <b>Bug</b>

修改文件之后,页签上未提示"小圆点"保存,关闭之后也不提示保存,只能手动"ctrl+s"保存,再次打开之后还是修改后的状态,而不是原状态

VS Code version: Code - Insiders 1.30.0-insider (24b0f75b1e33b88f30f2ed9d5b17ca60062c270b, 2018-11-16T06:20:02.054Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.94GB (2.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-github|Kni|0.30.0
vscode-language-pack-zh-hans|MS-|1.29.2

</details>

**Comment by alexr00** [comment]
Please use English for reporting issues and follow our issue reporting guideline:
https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#reporting-issues.

**Comment by mysmlz** [comment]
!!!
