### ISSUE TITLE
After fresh update, "Open Recent..." quits Code

### ISSUE THREAD

**Issue by dmke** [microsoft/vscode#63287]
- VSCode Version: 1.29.1 (but behaviour is present for a while)
- OS Version: Debian 9.6, Gnome 3.22.2

Steps to Reproduce:

1. Install and open version *n*-1 of VSCode.
2. Open VSCode
3. Upgrade to version *n* (I'm using `apt` here in a seperate terminal window)
4. Open a recent file/workspace (<kbd>Ctrl+r</kbd>)
5. Upon selecting a recent item, the VSCode window disappears and its processes exit.

Does this issue occur when all extensions are disabled?: Yes

---

Code autostarts when I log into my desktop. I am also in the habit of running system updates first thing after logging in (which occasionally brings in a new Code version; I don't have logic in place to parse `apt` output to trigger a restart of Code).

While working on the previous project, everything works fine, but when I need to switch workspaces the application just quits.

This behaviour does not hinder me to work (I can just reopen the application), but it is still annoying.

**Comment by chrmarti** [comment]
So this is specifically with Linux when you upgrade while a window is still open?

@joaomoreno For ideas on where to start looking.

**Comment by dmke** [comment]
Sorry, I don't have a Windows or macOS to test this on.

**Comment by joaomoreno** [comment]
Unfortunately, we cannot prevent apt from updating while Code is running. You should remember to shut Code down before attempting to update. Sad... but that's all we can do for now. :cry: cc @Tyriar
