### ISSUE TITLE
Multiline regex with capture group substitutes $1 literally until Replace Preview is opened

### ISSUE THREAD

**Issue by Simran-B** [Microsoft/vscode#63297]
**Version:** 1.30.0-insider (but also seen in released 1.29.0)
Commit: 24b0f75b1e33b88f30f2ed9d5b17ca60062c270b
Date: 2018-11-16T06:20:02.054Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Steps to Reproduce:**

1. Create a folder `multiline-capture`
2. Create a file `test.md` inside the folder with the following content:

       Use a loop to iterate over an array and
       print something.

3. Open the folder in vscode
4. Open Search panel, enable regex option and use: `(array).+\n` and `$1`
5. Hit return or Refresh. The preview in the search panel shows:
    > a loop over an <del>array and</del>$1
6. Click on it to open the _Replace Preview_.
    It confirms that the match will be replaced by a literal `$1`
7. Close the _Replace Preview_. In this moment, the preview in the search panel changes to:
   > a loop over an <del>array and</del>array
8. Click on it again to open the full preview and see it confirmed that it will replace it by the capture group value `array` now.
9. Refresh the search. It goes back to `$1` 
10. If you use _Replace All_, the result is as shown in the preview, so the match is either replaced by `$1` or `array` depending on what it showed before you replaced all occurrences.
11. Remove `\n` from the expression and refresh search: The issue does not occur, the preview shows `array` as substitute value immediately.

![image](https://user-images.githubusercontent.com/7819991/48619598-4f0a1c00-e99d-11e8-983a-6fc03efb6b84.png)
![image](https://user-images.githubusercontent.com/7819991/48619653-72cd6200-e99d-11e8-967b-f231dd2c6ad5.png)

**Expected behavior:**
I expect it to replace the match with the content of the capture group (which is `array`) all the time.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Can you check whether this works in the latest insiders? It sounds the same as #62980 and this scenario works for me now.

**Comment by Simran-B** [comment]
The problem still occurs in

Version: 1.30.0-insider
Commit: 0d3a14402d88f0f555ab3250c3ffd4c45a251665
Date: 2018-11-22T06:17:03.696Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134

**Comment by roblourens** [comment]
I see it now. Windows only.

**Comment by NilsEnevoldsen** [comment]
This is happening for me on macOS, @roblourens.

**Comment by roblourens** [comment]
In the latest Insiders build? Mac will also fail on 1.29

**Comment by NilsEnevoldsen** [comment]
Sorry, on 1.29.1. Carry on.

**Comment by roblourens** [comment]
This fails with CRLF line endings, you can use `\r\n` in your pattern instead to work around it.

**Comment by Simran-B** [comment]
It's only half a work around: I tried `(array).+\r\n` and the result list shows the expected captured value, but if you open the preview and close it, the match in the result list disappears.

Version: 1.30.0-insider
Commit: d3bb20c3fd1f23c369b80dca2ed25d54efd664e2
Date: 2018-11-27T08:27:31.447Z

**Comment by Simran-B** [comment]
Confirmed to be working. I assume the original issue is considered a bug that needs fixing still?

**Comment by roblourens** [comment]
Yep
