### ISSUE TITLE
Perf problems aftermath

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#63290]
We have shipped two not-so-good performance issues this month and we should make sure to not repeat that. This is a collection of ideas and changes:

* I have pushed https://github.com/Microsoft/vscode/commit/d7f82c11d667d0c86e8d6965c9474d34d111d7ad which is a telemetry event that tells us that a user got a hang or crash. @bpasero might know if we are already sending this somewhere else but I didn't find anything. Anyways, it shouldn't stop there but we should regularly look at those events and monitor them for a trend.
* https://github.com/Microsoft/vscode/commit/b548ced43cb1c9f86f3a013e20ccd8613fbd4138 is a change that logs warnings when an event emitter has a suspicious amount of listeners. While developing and while using insiders we should never seem them
* similar to the automatic extension host profiling (https://github.com/Microsoft/vscode/issues/60332) we should invest if we can automatically profile the renderer as soon as it appear as unresponsive. That would help us nail down these issues faster

**Comment by egamma** [comment]
closing as obsolete.
