### ISSUE TITLE
PI when scrolling in terminal

### ISSUE THREAD

**Issue by oppoi1** [Microsoft/vscode#63292]
Issue Type: <b>Performance Issue</b>

VS Code starts to lag if I scroll, type or get a new notification in the integrated terminal

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:11:49.509Z)
OS version: Windows_NT ia32 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|7.91GB (3.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	   153	 11252	code main
    1	    61	  8140	   window (Issue Reporter)
    0	    52	 13484	   shared-process
    0	   158	 14308	   window (show.ejs - TMSTest - Visual Studio Code)
    0	    13	   900	     watcherService 
    0	     6	  7772	       
    0	    32	  3788	     extensionHost
    0	    21	  9744	       "C:\Users\admin\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\admin\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain" --node-ipc --clientProcessId=3788
    0	    20	 14076	       "C:\Users\admin\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\admin\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=3788
    0	    22	 15484	       electron_node server.js 
    0	    27	 15764	       "C:\Users\admin\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\admin\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain" --node-ipc --clientProcessId=3788
    0	     6	  8496	     winpty-process
    0	     8	 15340	       
    0	     4	 15840	       
    0	     8	 10776	         
    0	    11	 15824	     electron-crash-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (show.ejs - TMSTest - Visual Studio Code)
|    Folder (TMSTest): 91 files
|      File types: js(19) ejs(17) png(11) log(6) csv(5) toc(4) css(3) json(3)
|                  exe(3) DBF(2)
|      Conf files: package.json(1) settings.json(1);
```

</details>
<details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|9.1.0
copy-relative-path|ale|0.0.2
bracket-pair-colorizer|Coe|1.0.61
githistory|don|0.4.3
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
rainbow-csv|mec|0.8.0
dotenv|mik|1.0.1
python|ms-|2018.10.1
debugger-for-chrome|msj|4.11.1
color-highlight|nau|2.3.0
vscode-css-peek|pra|2.1.0
addDocComments|ste|0.0.8
vscode-wakatime|Wak|1.2.3

(1 theme extensions excluded)

</details>

**Comment by oppoi1** [comment]
I just noticed I also get lags if I start to scroll in my files in general.

**Comment by alexandrudima** [comment]
@oppoi1 Can you please follow [these steps](https://github.com/Microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process) and create a CPU profile of you scrolling in an editor.

**Comment by oppoi1** [comment]
Hopefully this helps

[CPU-20181203T103243.zip](https://github.com/Microsoft/vscode/files/2638841/CPU-20181203T103243.zip)

**Comment by rebornix** [comment]
The cpu log shows terminal is doing heavy computation

![image](https://user-images.githubusercontent.com/876920/49397520-b4297580-f6f0-11e8-9519-8d553cd1418c.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/56517
