### ISSUE TITLE
Simple Full Screen on macOS acts up

### ISSUE THREAD

**Issue by alesok** [Microsoft/vscode#63291]
Issue Type: <b>Bug</b>

There are some problems with mouse in the new Native Full Screen: Explorer panel can't be resized using mouse. Actually it would be nice to have horizontal scrolling in the Explorer panel. 

Thanks

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.33GB free)|
|Process Argv|-psn_0_1253682|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
vscode-eslint|dba|1.7.0
githistory|don|0.4.3
latex-workshop|Jam|5.16.0
vscode-sshfs|Kel|1.11.2
linter-gfortran|krv|2.0.1
mssql|ms-|1.4.0
python|ms-|2018.10.1
java|red|0.33.0
vscode-java-debug|vsc|0.15.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.10.0
vscode-maven|vsc|0.11.1

</details>

**Comment by bpasero** [comment]
I also see crazy behaviour, e.g. the mouse behaves weird, it does not change when hovering over the divider to resize the explorer. Is that what you see too?

Given this I think we need to disable this feature until the issues are addressed.

**Comment by ignu** [comment]
Yeah, it seems like VS Code doesn't recognize (some|all) hover events after going Simple Fullscreen. GitLens' modal also stops working for me.

**Comment by bpasero** [comment]
Ok thanks for confirming.

**Comment by bpasero** [comment]
@ignu now I cannot reproduce anymore, do you have steps? does it reproduce always? I tried with Code stable and insiders via the keybinding `Cmd+Ctrl+F`...

**Comment by ignu** [comment]
I still see it on my Insiders... `dcc243c9920f0077e87e4a7befbc67c713a1709b / Version 1.30.0-insider ` if I got into Simple FullScreen hover no longer registers... even if I then exit Fullscreen.

`Reload Window` while non-fullscreen will restore hover functionality.

**Comment by bpasero** [comment]
@ignu can you please try to reproduce with our stable release (1.29.1), I am trying to understand if this is a regression or not.

**Comment by bpasero** [comment]
Nevermind, now I was able to reproduce also with stable. This is odd :-/, if I cannot fix it I will see to disable this functionality again, too bad.

**Comment by bpasero** [comment]
@ignu I might have found a workaround: does it reproduce if you disable our custom titlebar? Just configure `"window.titleBarStyle": "native"`.

It is possible that simple fullscreen and custom title are not supposed to work. If that is true we can simply disable the custom title when in simple fullscreen mode.

**Comment by ignu** [comment]
@bpasero yeah, that fixes the issue for me!

(Although simple fullscreen, custom titles and hover do work together if i do a `Reload Window` after i transition into Simple Fullscreen... so I think it's something that happens during the transition in and out of Simple Fullscreen..)

**Comment by bpasero** [comment]
Ok, I think we can keep simple fullscreen thereby but I will have to disable the custom title 🙌
