### ISSUE TITLE
Extension wishlist/idea contribution

### ISSUE THREAD

**Issue by zewa666** [microsoft/vscode#63298]
It would be great if we could contribute ideas, in a way of wishlist, somewhere officially, so that extension developers can see what the community is looking for.

As an example I've worked today with glob patterns and it pretty much drove me nuts having to build a minimal node app just for the sake of creating the proper pattern. A simple small extension could be helpful here where you could select a base folder, paste your glob pattern, hit enter and see a list of hits.

Now of course one can always do it by oneself but I expect there are a lot of users overwhelmed with the extension API or the whole process of creating one. On the other hand there might be people looking for cool ideas to build their next VSCode extension for.

The marketplace might be a fit for this (submit your extension idea) or maybe directly from within VSCode Menu->Help->Submit Extension idea

**Comment by usernamehw** [comment]
Doesn't look like it's going to happen anytime soon. Maybe someone wants to create a repo for this? 
@zewa666 @frobinsonj @gins3000 @madarsbiss @SimonSiefke @connorshea @sovgut @yume-chan

**Comment by zewa666** [comment]
While a repo is a start, I think this really stands and falls with its visibility, so the Marketplace would still be the best place to add the "submit idea" feature

**Comment by usernamehw** [comment]
While it's true that it would be better to have a button on the marketplace and the officially supported repository, but issues can be safely ignored up to 1000 upvotes. And this particular one looks like something the community can do on its own.

AFAIK new features almost never added to the Marketplace (even as small as adding button or link).

**Comment by zewa666** [comment]
yeah I thought so. So what would be with the following idea:

* Create an official repository from microsoft/vscode team called something like `extension-requests`
* Create an issue template, which already has the predefined parts in there like describe what it does, how it should work, attach some image links ... bla bla bla
* Directly in VSCode, add a button to the Help menu saying `Request extension`
* Add a visible link in the Extensions panel
* When either of the links is clicked, it send the user to a new issue creation on Github in the preferred browser. E.g. for this repo it would be `https://github.com/Microsoft/vscode/issues/new/choose`

I guess most of the times users are in VSCode, find an interesting issue and wonder whether there is an extension available. I guess lots of them would then naturally switch to the Extension pane and search for something. If nothing is found, that link could be the logical next step as its visible and part of your search workflow.

**Comment by usernamehw** [comment]
@egamma @kieferrm Any thoughts?

**Comment by egamma** [comment]
The suggestion assumes that users distinguish between:
- requesting a feature in VS Code
- requesting an extension that implements a feature. 

This is not what I'm observing, users just file feature requests against VS Code. The VS Code team then triages these issues and labels them with `extension-candidate`.

What we could do is to promote the query for [extension candidates](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aclosed+label%3A%2Aextension-candidate) more so that 'people looking for cool ideas to build their next VSCode extension for' can find them.

**Comment by usernamehw** [comment]
1. It's not clear which extensions already implemented
1. Issues are locked, so no upvotes, no comments, no users reading closed issues
1. There's no area/technology tags on `extension-candidate` issue

**Comment by egamma** [comment]
@usernamehw one approach to overcome the limitations you mention is to copy the `extension-candidate` issues into a community maintained repository. 

>It's not clear which extensions are already implemented

If the team member closing the issue knows that there is an existing extension, then we try to point users to it. However, in general we cannot afford to add more load on the development team to manage `extension-candidate` issues. The development team is really busy managing issues affecting VS Code. See the October iteration plan https://github.com/microsoft/vscode/issues/82194, for example. I hope you understand this.

If the you are creating an extension-candidate repository, then please let us know and we will add it to our documentation where it is appropriate.

**Comment by egamma** [comment]
@Tyriar correct, we had some activity on this page after we launched extensions, but it is no longer managed and therefore has no value. I've removed it.

**Comment by usernamehw** [comment]
Since nobody else wants it I can try to create such a repo. Do you have any thoughts/ideas for it? Maybe piece of content for the README file. My English is not great.

**Comment by egamma** [comment]
Closing - no action planned from the VS Code team.
