### ISSUE TITLE
Ubuntu glitching lines on render

### ISSUE THREAD

**Issue by aleksey-pastuhov** [Microsoft/vscode#6329]
- Device: Lenovo Yoga 500
- OS Version: Ubuntu 16.04 x64
- Processor: Intel® Core™ i5-6200U CPU @ 2.30GHz × 4 
- Graphics: Intel® HD Graphics 520 (Skylake GT2) 
- VSCode Info:
    - Version 1.0.0
    - Commit fa6d0f03813dfb9df4589c30121e9fcffa8a8ec8
    - Date 2016-04-13T14:21:33.326Z
    - Shell 0.35.6
    - Renderer 45.0.2454.85
    - Node 4.1.1

Steps to Reproduce:

Just write the code and some time that bug will appear... Sorry for that not informative issue description, but only way to reproduce is to write code or sometimes open and close menus. I thinks it is some problems with graphics and rendering.

But that annoying error occurred too often, so I can't use VSCode for development.

P.S.: There is no errors in the developer console.

![screenshot](https://cloud.githubusercontent.com/assets/11784219/15226103/06a6989e-188a-11e6-98a7-9697ad82cf7f.png)

**Comment by alexandrudima** [comment]
@aleksey-pastuhov That looks like a Chromium or graphics drivers bug... Does this happen if you run VS Code with `code --disable-gpu` ?

**Comment by aleksey-pastuhov** [comment]
Yes, and even more often than usual

**Comment by Tyriar** [comment]
@aleksey-pastuhov are you running Ubuntu through a VM and do you see this when browsing Chrome?

**Comment by aleksey-pastuhov** [comment]
@Tyriar No, I have Ubuntu installed on my notebook as primary OS. By default I use Firefox, and I do not see such problems there. But I will check the bug in chrome.

**Comment by alexandrudima** [comment]
@aleksey-pastuhov You could also try upgrading to vscode 1.1 which includes a new Chromium version (49 instead of 45!), maybe it got fixed in the meantime in Chromium

**Comment by alexandrudima** [comment]
@aleksey-pastuhov Are things better with vscode 1.3.0 which just got released? If not, we can file a bug against Chromium

**Comment by aleksey-pastuhov** [comment]
@alexandrudima Sorry, I can't confirm that issue was fixed, because I've switched back to Windows 10, and here everything works well. 👍

**Comment by alexandrudima** [comment]
Given there's no action on our side from this issue and you're no longer suffering from it, I'm opting to close this issue and we can reopen if it ever comes up again.
