### ISSUE TITLE
Retry as administrator - Retry with sudo

### ISSUE THREAD

**Issue by scriptcoded** [Microsoft/vscode#63295]
Issue Type: <b>Bug</b>

When editing a file that can't be saved without elevation, a notification pops up, prompting to try and save as administrator. On Linux, perhaps this should say "Retry with sudo"

![screenshot](https://user-images.githubusercontent.com/6452991/48618811-c8ecd600-e99a-11e8-88ef-92bbb827048e.png)

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:42:27.562Z)
OS version: Linux x64 4.15.0-39-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 3495)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 1|
|Memory (System)|15.42GB (4.51GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by bpasero** [comment]
Up for grab. Should it be "Retry as Sudo" maybe?

**Comment by scriptcoded** [comment]
@bpasero Seems fair!
