### ISSUE TITLE
No apparent way to get column for a visible editor

### ISSUE THREAD

**Issue by bbenoist** [Microsoft/vscode#6330]
As of VSCode API Version: 0.11.0, it seems to be impossible to get column of the active editor from a TypeScript extension.

This is quite strange considering typings for `vscode.window.showTextDocument()`:

```typescript
/**
 * Show the given document in a text editor. A [column](#ViewColumn) can be provided
 * to control where the editor is being shown. Might change the [active editor](#window.activeTextEditor).
 *
 * @param document A text document to be shown.
 * @param column A view column in which the editor should be shown. The default is the [one](#ViewColumn.One), other values
 * are adjusted to be __Min(column, columnCount + 1)__.
 * @return A promise that resolves to an [editor](#TextEditor).
 */
export function showTextDocument(document: TextDocument, column?: ViewColumn): Thenable<TextEditor>;
```

Could you please add a `viewColumn` property to the `TextEditor` interface?

See https://github.com/bbenoist/vscode-togglehs/issues/2 for the initial reasons of my request

**Comment by bbenoist** [comment]
Temporary trick in case others are suffering from the same issue:

```typescript
function getTextEditorViewColumn(textEditor:any) : number {
  return textEditor._viewColumn;
}
```

**Comment by jrieken** [comment]
It does exist as ['TextEditor.viewColumn'](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L772)

@bbenoist Aure you sure you are using a recent version of vscode.d.ts?
