### ISSUE TITLE
Can't click and drag to select text in the Debugger "Watch" pane

### ISSUE THREAD

**Issue by iansan5653** [Microsoft/vscode#63302]
**System:**
Version: 1.29.0 (user setup)
Commit: 5f24c93878bd4bc645a4a17c620e2487b11005f9
Date: 2018-11-12T07:47:15.448Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Steps to Reproduce:
1. Start a debugging session (I used Python but that shouldn't matter)
2. In the "Watch" panel on the sidebar, click "+"
3. Type anything
4. Try to select text using the mouse (ie, click and drag)
5. Instead of text being selected, the whole expression is dragged

Note that <kbd>shift</kbd> + <kbd>arrow keys</kbd> does work to select text.

**Comment by isidorn** [comment]
@iansan5653 good catch, thanks for reporting

**Comment by iansan5653** [comment]
@roblourens this issue was for the input box - it is definitely fixed in the latest preview.
