### ISSUE TITLE
./ doesn't work in "files to exclude"

### ISSUE THREAD

**Issue by borekb** [Microsoft/vscode#63303]
- VSCode Version: 1.29.1
- OS Version: macOS Mojave

Previously, including `./somedir` and excluding `./somedir/subdirectory` would find all matches everywhere in `somedir` except `subdirectory`. In 1.29, I also get results from the subdirectory.

There have been quite a few [search-related changes](https://code.visualstudio.com/updates/v1_29#_search) in 1.29, is this one of them? I have to say that I found the previous behavior more intuitive.

(I'm able to replicate in 1.30 insiders.)

**Comment by roblourens** [comment]
I don't think that's related, can you file a separate issue for `@sandy081`? Thanks

**Comment by borekb** [comment]
Done: https://github.com/Microsoft/vscode/issues/63522.
