### ISSUE TITLE
Error on searching string every time

### ISSUE THREAD

**Issue by CharlesWuQiushi** [Microsoft/vscode#63305]
Issue Type: <b>Bug</b>

When I search for a string, the alert showed"spawn D:\Microsoft VS Code\Code\resources\app\node_modules.asar\unpacked\vscode-ripgrep\bin\rg.exe ENOENT", I installed VS Code again, it still has got this error, and I have to look for the string by myself.
Please fix this bug as soon as possible, THANK YOU VERY MUCH! 

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.73GB (3.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
vscode-language-pack-zh-hans|MS-|1.29.2
python|ms-|2018.10.1
debugger-for-chrome|msj|4.11.1

</details>

**Comment by roblourens** [comment]
Can you check whether `D:\Microsoft VS Code\Code\resources\app\node_modules.asar\unpacked\vscode-ripgrep\bin\rg.exe` exists?

Is it possible that you have a folder in your workspace that doesn't exist?

**Comment by CharlesWuQiushi** [comment]
I checked, this file exists. I haven't found a folder which doesn't exist in my workspace. That's really confusing!

**Comment by CharlesWuQiushi** [comment]
And I tried to open the workspace again, changed the target string & file, no effect.

**Comment by roblourens** [comment]
If you paste that into a command prompt, does it work? (It should just print out the `USAGE` help text)

**Comment by roblourens** [comment]
If you paste that into a command prompt, does it work?

**Comment by ghena** [comment]
Hi, same problem, affected after last update.
spawn sC:\Program Files\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe 

How to fix it ?

**Comment by CharlesWuQiushi** [comment]
I don't know! I haven't changed any inside settings, but I can't search for a string. Until now.

**Comment by charlieflowers** [comment]
Closed because it needs more info? Well, here's more -- it is happening to me too.
