### ISSUE TITLE
Need highlighting to the symbol there gets cursor

### ISSUE THREAD

**Issue by eypsume** [Microsoft/vscode#63306]
When Quick Open for Find in A File get invoked using by Ctlr+Shift+O , In my opinion, when the highlighting point to the symbol which owns the cursor in the editor that is more useful. So I move easily the cursor to a symbol nearby using by Up or Down arrow key.

Most some tool such as Sublime Text or Eclipse do that.

my environment is 
Code Insiders latest
Primary tool is c/c++
OS is Ubuntu Gnome 16.04

**Comment by roblourens** [comment]
I don't think I understand. When you focus a symbol, the editor should scroll to that symbol. Is that not what you see?

**Comment by eypsume** [comment]
My point is that the focus always place on top instead of the  current symbol of the editor on start up.
The editor scrolls good whenever the  focus moves. That is not problem. I hope you understand what I mean. 
Thanks.

**Comment by bpasero** [comment]
@eypsume sorry I do not understand what you mean, maybe draw a picture of what you mean to illustrate your idea?

**Comment by eypsum** [comment]
![quicksymbol_need_hilight_current_symbol_on_editor_1](https://user-images.githubusercontent.com/20113770/49290646-d651a680-f4ea-11e8-94b9-24f105d84045.png)

**Comment by eypsum** [comment]
> @eypsume sorry I do not understand what you mean, maybe draw a picture of what you mean to illustrate your idea?
![quicksymbol_need_hilight_current_symbol_on_editor_1](https://user-images.githubusercontent.com/20113770/49290671-f1bcb180-f4ea-11e8-8b7c-457bd15a808f.png)
