### ISSUE TITLE
Standard ML support in VSC

### ISSUE THREAD

**Issue by Azambadar** [Microsoft/vscode#63304]
There is Standard ML extention in marketplace but no support and documentation are available how to configure sml/nj in VSC , this feature must be improved and worked on.

**Comment by alexr00** [comment]
Can you link to the market place extension? It seems like this documentation request should be touted to them.

**Comment by Azambadar** [comment]
I'm talking about this one 

https://marketplace.visualstudio.com/items?itemName=freebroccolo.sml

**Comment by Azambadar** [comment]
I managed to solve this myself without any help.
