### ISSUE TITLE
Powershell session terminated when I run "git checkout branch-name"

### ISSUE THREAD

**Issue by liweizhi** [Microsoft/vscode#63308]
- VSCode Version: 1.29.1
- OS Version: Win10 1809

Steps to Reproduce:
1. install PowerShell extension 1.9.0
1. create a powershell file in a git directory
2. if current branch is master, I run the following script with press F8:
  cmd /c "git status"
  cmd /c "git stash"
  cmd /c "git checkout rc"
3. the session will be terminated

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexr00** [comment]
Is this an issue you are having with the Powershell extension?
