### ISSUE TITLE
Make settings.json more accessible 

### ISSUE THREAD

**Issue by Ragnoroct** [Microsoft/vscode#63317]
Currently, if I want to quickly get to settings.json I press ctr+, but then I have to press the dot menu to switch to settings.json. I'm sure that there is probably a setting to default to settings.json but I think it still would be better to give "Open settings.json" it's own button.

Current:
![image](https://user-images.githubusercontent.com/19155205/48632467-92a55b80-e986-11e8-8d1e-bbb2c90011f8.png)

My poor man's paint mockup:
![untitled](https://user-images.githubusercontent.com/19155205/48632594-ee6fe480-e986-11e8-8936-e3574bd52e08.png)

**Comment by usernamehw** [comment]
There is an icon `{}` in insiders version. Should be out in the next release `1.30`.
