### ISSUE TITLE
Restoring fullscreen appearance will not work and destroy windows positioning

### ISSUE THREAD

**Issue by Sgt-Nukem** [Microsoft/vscode#63313]
Quitting VS Code while in fullscreen appearance and later re-opening of VS Code will not just
 - NOT open in fullscreen appearance again, but also
 - destroy window positioning (and size) information, so it gets a default size and is floating somewhere on the desktop.

(Size/positioning information will get remembered for regular windowed mode.)

- VSCode Version: 1.29.0 (user setup)
- OS Version: Windows 10 1809 (October 2018 Update)

Steps to Reproduce:

1. View -> Appearance -> Toggle Fullscreen
2. File -> Exit
3. reopen VS Code

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Set `"window.restoreFullscreen": true`
