### ISSUE TITLE
1px gap between scrollbars

### ISSUE THREAD

**Issue by Swazimodo** [microsoft/vscode#63315]
Issue Type: <b>Bug</b>

This is not a big issue but it just looks a little sloppy. In between the file preview bar and the scroll bar there is a 1px gap and you can see text from long lines that go off the page show through.

![image](https://user-images.githubusercontent.com/10536879/48631581-160d7f80-e97c-11e8-9d71-2751b7f3a80c.png)

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:47:15.448Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.79GB (16.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|8.5.6
vscode-

**Comment by roblourens** [comment]
Have you zoomed at all?

**Comment by Swazimodo** [comment]
I am at a -1 window zoom in vscode. The OS is not applying an extra zoom.

**Comment by alexandrudima** [comment]
The gap is caused by zooming.
