### ISSUE TITLE
unins000.dat is becoming bigger and bigger everytime after auto update

### ISSUE THREAD

**Issue by wangwenx190** [microsoft/vscode#63316]
Issue Type: <b>Bug</b>

unins000.dat is becoming bigger and bigger everytime after VSC updates. If using preview version of VSC, it will eventually larger than 100MB after many times of updating.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (11.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details>

**Comment by joaomoreno** [comment]
Any chance you can send it to me at joao moreno at _mycompany_ com?

**Comment by wangwenx190** [comment]
Sorry that I have deleted it already, but it's easy to reproduce, just install an old version of VSC, then install a newer version, repeat these steps, and the "unins000.dat" will become much bigger than it was when first installed. If you have patience and repeat these steps for many many times, it will certainly larger than 100MB. When I deleted it, it was already 130MB.
