### ISSUE TITLE
Code UI is slow

### ISSUE THREAD

**Issue by sarunask** [Microsoft/vscode#63311]
Issue Type: <b>Performance Issue</b>

UI is slow while using

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.43GB free)|
|Process Argv|-psn_0_57358|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   11	   147	   278	code main
    0	   131	   356	   gpu-process
    0	   147	   411	   shared-process
  100	   983	  4017	   window (aws-terraform)
   31	   328	  4018	     extensionHost
    0	    66	  4019	     watcherService
    0	    49	  4020	     searchService
    0	    98	  4617	   window (Issue Reporter)
    0	     0	  4619	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (aws-terraform)
|    Folder (aws-terraform): more than 22820 files
|      File types: tf(15174) tfvars(1007) md(809) mk(630) xml(514) yml(432)
|                  json(430) py(383) hcl(334) yaml(273)
|      Conf files: makefile(1259) package.json(65);
```

</details>
<details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
systemd-unit-file|coo|1.0.2
vscode-markdownlint|Dav|0.21.0
githistory|don|0.4.3
gitlens|eam|8.5.6
vscode-html-css|ecm|0.2.0
git-project-manager|fel|1.7.1
terminal|for|0.0.10
shell-format|fox|1.1.3
terraform|mau|1.3.7
rainbow-csv|mec|0.8.0
mssql|ms-|1.4.0
python|ms-|2018.10.1
cpptools|ms-|0.20.1
Go|ms-|0.7.0
vscode-docker|Pet|0.3.1
quicktype|qui|12.0.46
vscode-icons|rob|7.28.0
rust|rus|0.4.10
crates|ser|0.3.5
vim|vsc|0.16.12
HCL|who|0.0.5
html-css-class-completion|Zig|1.17.1

</details>

**Comment by alexr00** [comment]
Does this occur when you disable extensions? What were you doing when you saw that the UI was slow?
