### ISSUE TITLE
Code scroll doesn't match coding area when at the bottom

### ISSUE THREAD

**Issue by JasonSPriorityDispatch** [Microsoft/vscode#63323]
Issue Type: <b>Bug</b>

Using the mini code scrolling on the right before the scroll bar matches with the code at the top but when you get to the bottom it stops matching up.

![error](https://user-images.githubusercontent.com/45105668/48638134-f5015a80-e98c-11e8-8302-0e71c2c7d781.png)

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.10
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
jshint|dba|0.10.20
vscode-eslint|dba|1.7.0
xml|Dot|2.3.2
vscode-html-css|ecm|0.2.0
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.40
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.7.2
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
beautify|Hoo|1.4.7
vscode-angular2-emmet|jak|2.0.3
angular-essentials|joh|0.4.0
Angular2|joh|7.0.1
pwa-tools|joh|0.1.0
easy-less|mrc|1.4.5
python|ms-|2018.10.1
team|ms-|1.144.1
debugger-for-chrome|msj|4.11.1
angular2-inline|nat|0.0.17
vetur|oct|0.13.0
indent-rainbow|ode|7.2.4
vscode-docker|Pet|0.3.1
material-icon-theme|PKi|3.6.0
vue-vscode-snippets|sdr|1.3.0
gitblame|wad|2.6.1

(2 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment]
@JasonSPriorityDispatch Do you have any steps to reproduce? I cannot reproduce this.

![image](https://user-images.githubusercontent.com/5047891/48651805-d6d34300-e9fc-11e8-9ff1-d69f172c3ce4.png)
