### ISSUE TITLE
No Call Stack hover message mismatched

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#6332]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Start debugging a JS project
2. Pause after it is running
3. Hover over the message in the call stack

![callstackmismatch](https://cloud.githubusercontent.com/assets/12900364/15229851/a3719e00-1847-11e6-96ae-aac30ce88fbb.png)

**Comment by isidorn** [comment]
Yes, this is as designed. Do you find it confuzing?
Why would you expect to see the same message on hover. We tried to show the meta-info on hover, because the actual error is sometimes not as clear as in this case
