### ISSUE TITLE
Cannot reliably edit text in VS Code

### ISSUE THREAD

**Issue by clayms** [Microsoft/vscode#63327]
[CPU-20181117T172158.zip](https://github.com/Microsoft/vscode/files/2592316/CPU-20181117T172158.zip)

Issue Type: <b>Bugs</b>

The last few updates have rendered VS Code nearly unusable.  It cannot handle the most basic text editing of small files smoothly and reliably.  VS Code constantly freezes when I scroll, or select text.  Around half the time there is a several second delay when I type new text or when I paste text into the editor. 

What is going on?  Is there anything I can do to remedy this?

When I first started using VS Code it was extremely responsive and a joy to use.  Now it causes nothing but frustration, even when trying to complete the most basic tasks of a simple text editor.  My system has not changed at all over this time period.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (8.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by rebornix** [comment]
@clayms can you follow https://github.com/Microsoft/vscode/wiki/Performance-Issues to provide more information? Right now the info from `code -s` seems good.

**Comment by dubbha** [comment]
@rebornix , while @clayms is preparing his profile, would you like to take a look at mine?
I am struggling the same way @clayms does for some time now, and having the same emotions, remembering the time when vscode was fast.

[CPU-20181117T020301.zip](https://github.com/Microsoft/vscode/files/2591286/CPU-20181117T020301.zip)

**Comment by rebornix** [comment]
@dubbha sure, thanks for your help!

**Comment by rebornix** [comment]
@dubbha I found that the issue you ran into is the same as https://github.com/Microsoft/vscode/issues/62970, which is already fixed in 1.29.1, update VSCode can fix it ;)

**Comment by clayms** [comment]
@rebornix  CPU profile attached to OP.  There were a few stutters during the recording of this profile but not as bad as it can get.  If it starts getting really bad again, I will try and remember to start recording a CPU profile and then attach it to this post.

**Comment by clayms** [comment]
@rebornix  I followed the instructions here: 
https://github.com/Microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process

I did not see an option to profile the extension host or rendering process separately.

**Comment by rebornix** [comment]
@clayms sorry that's my mistake, your profile is good, I somehow loaded the wrong one.

**Comment by rebornix** [comment]
The log is pretty helpful, we see frequent mousedown event and then repainting without any break/idle.

![image](https://user-images.githubusercontent.com/876920/48727180-5708cc80-ebe6-11e8-8ee1-3e23abb9ab4f.png)

![image](https://user-images.githubusercontent.com/876920/48727189-64be5200-ebe6-11e8-95be-b26792866f74.png)

@clayms did you happen to select text in the editor?

**Comment by jackwakefield** [comment]
I'm running into the same issue with any sized file within a large project (~5000 files, mostly a few thousand lines each, but one exception with a generated ~100,000 line Go file) and all extensions disabled.

```
Version:          Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:07:43.495Z)
OS Version:       Linux x64 4.19.2-arch1-1-ARCH
CPUs:             Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2400)
Memory (System):  15.53GB (3.00GB free)
Load (avg):       1, 1, 1
VM:               36%
Screen Reader:    no
Process Argv:     --verbose
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    disabled_software
                  rasterization:                disabled_software
                  video_decode:                 unavailable_software
                  video_encode:                 unavailable_software
                  webgl:                        enabled
                  webgl2:                       enabled

CPU %	Mem MB	   PID	Process
    0	   175	 12591	code main
    0	    32	 12593	   zygote
    0	   111	 12770	     shared-process
    0	    79	 12623	   gpu-process
Workspace Stats:
|  Window (client.go - syrinx-gateway - Visual Studio Code)
|    Folder (syrinx-gateway): 14169 files
|      File types: go(6969) sql(3925) json(766) proto(286) textproto(222)
|                  md(190) s(71) feature(65) yml(59) gitignore(58)
|      Conf files: makefile(102) settings.json(1)
```
[vscode-typing-and-freezing.cpuprofile.zip](https://github.com/Microsoft/vscode/files/2596677/vscode-typing-and-freezing.cpuprofile.zip)

**Comment by rebornix** [comment]
It spent quite a lot of time dealing with IPC. @jackwakefield do you mind running `code --logExtensionHostCommunication` when you run into that issue and then open "Developer Tools" and share the log in the console with us?

**Comment by jackwakefield** [comment]
@rebornix I've since realised it's only happening when editing new files in the workspace, the logs also helped trigger my memory as rather importantly there's ~4000 untracked files in the git repository.

```
[Ext → Win][4945170][len: 641561]  492 - receiveRequest MainThreadDecorations.$onDidChange( 1 (4074) [{…}, {…}, ...]
... 2 second freeze
extensionService.ts:1092 [Win → Ext][2797639][len:     5]  492 - ack undefined
extensionService.ts:1092 [Win → Ext][2797644][len:     5]  492 - reply: undefined
```

**Comment by clayms** [comment]
@rebornix   Yes, I did select text.  Selecting text and scrolling with the mouse wheel are two of the things that seem to cause slow-downs and momentary freezes the most.   However, simply moving the cursor with keyboard or mouse along with inputting text also cause problems.

**Comment by rebornix** [comment]
@JacksonKearl it looks like we are sending git file decorations to the core which takes that much of time, @joaomoreno can you help take a look?

**Comment by rebornix** [comment]
@clayms now I'm thinking whether it's a chromium rendering issue. It would be great if you can do the following when it slows down siganificantly.

* Open Developer Tools
* Open Performance Tab
* Record by click the left most round button 

![image](https://user-images.githubusercontent.com/876920/48794000-90583f80-ecad-11e8-9099-e04eb2941e24.png)

* Scroll or type in the editor
* Stop the recording and save the profile

![image](https://user-images.githubusercontent.com/876920/48794051-b087fe80-ecad-11e8-8272-f9610335bb37.png)
* Share the profile with us

With the profile, we can better know what kind of tasks Chromium is running. The cpu profile only tells us about it's browser work.

**Comment by clayms** [comment]
Has this been resolved with 
https://code.visualstudio.com/docs/setup/windows#_scrolling-is-laggy-and-not-smooth
?

**Comment by jrieken** [comment]
Yes, this has been resolved.
