### ISSUE TITLE
API to retrieve vscode.DebugSession

### ISSUE THREAD

**Issue by quoctruong** [microsoft/vscode#63324]
I am writing a debugger for vscode that launches `vscode.DebugSession` underneath (through `startDebugging` API). However, there does not seem to be any API in `vscode.debug` for retrieving and/or terminating a `vscode.DebugSession` that is running in the background and not the current `activeDebugSession`. Is there any way to achieve this or any plan to add this feature?

**Comment by weinand** [comment]
You can track debug sessions by registering for `onDidStartDebugSession` and `onDidTerminateDebugSession`.
And you can terminate the active debug session via the `workbench.action.debug.stop` command (which doesn't help if you want to stop a session that is not active).

As a workaround for the missing "StopSession" API, you could send a [DAP Terminate request]( https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Disconnect) via the with `DebugSession.customRequest`.

**Comment by quoctruong** [comment]
@weinand Thank you for the detailed response. I was able to keep track of the `debugSession` and terminates it with `customRequest`.

One problem, however, that I am trying to address is to terminate the `debugSession` properly when user closes vscode. When vscode is closing, I make a call to `customRequest` but get back an error saying `no debug adapter`. Do you know how I can properly terminate a `debugSession` that I started through `vscode.debug.startDebugging` when user closes vscode?

**Comment by weinand** [comment]
@quoctruong when a user closes VS Code, debug sessions still running should be terminated automatically by VS Code.
