### ISSUE TITLE
Open Help on keys alt+shift

### ISSUE THREAD

**Issue by ekam230** [Microsoft/vscode#63325]
Issue Type: <b>Bug</b>

i change language on keys alt+shift. in visual code studio when i press this keys. Open Help. In keybinding i don't find this keys 

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:07:43.495Z)
OS version: Linux x64 4.15.0-39-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (8 x 3456)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|14.64GB (2.65GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.2
vscode-eslint|dba|1.7.0
vscode-faker|dee|1.3.0
gitlens|eam|8.5.6
tslint|eg2|1.0.40
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
ftp-simple|hum|0.6.8
vscode-gist|ken|1.2.1
php-symbols|lin|2.1.0
Angular-BeastCode|Mik|7.0.15
vscode-exec-node|mir|0.5.0
vscode-language-pack-ru|MS-|1.29.2
python|ms-|2018.10.1
LiveServer|rit|5.2.0
code-settings-sync|Sha|3.2.0
ayu|tea|0.17.0
vscode-todo-highlight|way|1.0.4

(2 theme extensions excluded)

</details>

**Comment by cleidigh** [comment]
@ekam230 
Can you provide some more information:
- What is your goal?  
- Are you trying to set a key binding for language mode?
- Is there particular command you do not see in the key bindings?

**Comment by sbatten** [comment]
@ekam230  can you verify 2 things?
1) Are you using the custom menubar? Please report the value of "window.titleBarStyle" in you settings.
2) Please report the value of "window.menuBarVisibiliby" in your settings.

I am currently not able to reproduce this with any configuration, but more information can help narrow it down. Thanks.

**Comment by ekam230** [comment]
Yes problem with window.titleBarStyle = custom. When i set "native"  - problem disappears.

I found another solution to the problem. I have a Russian language pack installed(ms-ceintl.vscode-language-pack-ru). When window.titleBarStyle = custom. I delete the Russian plugin. The problem also disappears. 

I will use in native mode. 

p.s. window.menuBarVisibiliby = default

**Comment by sbatten** [comment]
@ekam230 I want to re-open this as this is a valid bug against the custom menu. It is likely due to a bug in mnemonics with the Russian language pack. Can you try setting `window.enableMenuBarMnemonics` to false with the custom title bar enabled and see if this reproduces?

**Comment by ekam230** [comment]
i set window.enableMenuBarMnemonics=false and problem also disappears.
