### ISSUE TITLE
"Content on disk is newer" warnings while saving Go files

### ISSUE THREAD

**Issue by bportnoy** [Microsoft/vscode#63335]
- VSCode Version: 1.29.1 (1.29.1)
- OS Version: MacOS Mojave 10.14.1 (18B75)

Steps to Reproduce:

1. Save .go file.
2. Presented with "content on disk is newer" warning and resolution diff.

I've been using VSCode with Go for over a year and have never had this problem before the past few weeks (but don't know if it's correlated with a new VSCode version). It doesn't seem to be a `gofmt` issue; the changes in the diff are exactly the changes that I intend to save, and the issue occurs with extensions disabled.

Does this issue occur when all extensions are disabled?: Yes

Thanks for your help; please let me know if I can provide additional information.

**Comment by roblourens** [comment]
Does this only happen with .go files? Does it happen every time?

**Comment by roblourens** [comment]
Is it possible that you have some build task or extension that's touching those files in the background?

**Comment by jamietre** [comment]
This happens to me with typescript files too, with nothing running in the background.

I've also in the past tried to use a run-code-on-save process which also results in this happening, so I disabled it, but it still happens sometimes.

For me the general behavior of vscode is problematic. Even if it was working as expected, I should be able to run processes in the background that touches files after vscode saves them without vscode getting confused. It should just reload it, or notify that it's been changed and offer to reload (like sublime text). At a minimum, this should be an option that users can choose - either automatically reload, don't reload but let me know it's out of date. The merge behaviour is basically never what I'd want, and it's the only option we seem to have right now.

**Comment by roblourens** [comment]
@jamietre this should only happen when there is a conflict between the two versions, so we would have to lose some changes, which is not good to do automatically or by default.

**Comment by jamietre** [comment]
> @jamietre this should only happen when there is a conflict between the two versions, so we would have to lose some changes, which is not good to do automatically or by default.

This doesn't make sense to me.

The only circumstance in which you would want to address a "conflict" is when a file has been edited by two independent processes since a single source of truth has been last updated.

That is never the case in a single-user environment: I save a file in vscode. Something else edits it a few seconds later and saves it to disk. Those are sequential actions, both in a single-user environment. There's not a question of what the source of truth is. VS Code should not try to "merge" a change made outside of its environment, unless I had *unsaved* work in an editor. The single source of truth is the file system; there was never a conflict.

In any event there are so many prior issues about this, it should be clear that a lot of people would like a way to turn off this "feature" even if you don't agree with it.

**Comment by jamietre** [comment]
Hmm... I think it's probably the 2nd one? Maybe this is an issue of the editor actually being dirty because another "save" event took place before the externally-triggered update had finished. Let me see if I can repro with more specific scenarios.

**Comment by bportnoy** [comment]
Hi – to address the questions:

1) This does not happen every time; there doesn't seem to be a pattern as to when it does and doesn't happen.
2) I've been primarily working in Go, and have not observed it in other files. That does not necessarily mean it's isolated to Go files, however, as there has been far less opportunity for other file types.
3) There's nothing new or changed that would touch those files; I can try seeing if this happens with our file watcher disabled.

All that said, it's curious to me that the changes are exactly what I'm trying to save, rather than an actual difference as if it were edited by another process. Perhaps it's being saved twice in some way?

**Comment by bpasero** [comment]
@bportnoy if any external tool changes the `mtime` (modification time) of the file to a newer value of what VSCode knows you will get this error popping up. There is https://github.com/Microsoft/vscode/issues/919 which suggests to use content hashing, which would be nice but non-trivial to implement. 

If you can find out which external tool changes the `mtime`, that should help.

**Comment by bportnoy** [comment]
Thanks, I'll look into this (apologies for the slow response, was sick and then the holiday happened).

**Comment by bpasero** [comment]
Ok
