### ISSUE TITLE
Format on Save is mangling my code

### ISSUE THREAD

**Issue by johnjutsu** [Microsoft/vscode#63339]
Issue Type: <b>Bug</b>

It is hard to reliably reproduce, but seems to maybe be related to saving the file while a mouse-over pop-up is present on the screen.  This is a big problem because it is difficult to recover from since the file saves immediately after the mangling.

1. Write some code that needs to be formatted
1. Hover the mouse over some other object to present pop-up info for the object.
1. Press and hold Ctl
1. Press S

Expected result: Existing code is formatted.
Actual result: Random code from elsewhere in my sources is inserted into/overwrites the real code.

This is C++ software on version 1.29.0.

I have not noticed the problem until a day or two ago (11/13/18 or 11/14/18), and it may have correlated with updating VS Code.  I have rebooted since seeing the problem the first time, and still see it.

OS is Ubuntu 14.04.

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:42:27.562Z)
OS version: Linux x64 4.4.0-139-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz (8 x 2352)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|15.65GB (11.75GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.3
vsc-material-theme|Equ|2.5.1
python|ms-|2018.10.1
cpptools|ms-|0.20.1
java|red|0.33.0
vscode-java-debug|vsc|0.15.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.10.0
vscode-maven|vsc|0.11.1
vscode-proto3|zxh|0.2.1

</details>

**Comment by cleidigh** [comment]
@johnjutsu 
Have you tried or encountered a similar problem with other languages?  
Have you disabled all other extensions?

**Comment by johnjutsu** [comment]
I don't typically use VS Code with any other languages, unfortunately.

I've just now disabled all extensions except for cpptools. Will see how it behaves.

**Comment by johnjutsu** [comment]
I did have it happen to me earlier, and it didn't necessarily seem tied to the editor-hover, but my mouse position did seem to possibly affect which code was randomly inserted (the code was from the same file).

**Comment by johnjutsu** [comment]
Here is an example of one occurrence:

	delete curMsg;
	delete curlrecvbuf;
+	delete curMsg;
+	delete curlrecvbuf;
	delete curlsendbuf;

Note that lines 3 and 4 are duplicate of 1 and 2, and added by the code formatting.  This was also far away from where i was actually editing (this code is near the bottom of the file in a class destructor).  Further up, other mangling happened, but I didn't recognize that it did soon enough to learn more about it.  Only found this when reviewing git diffs when my build failed.

Looking closer at the mangling in another spot, it removed two lines that were near-ish to my changes, but not actually lines that I made changes to.

Frustrating, because now I have to roll back to last known git state and redo my latest changes.

This was with all extensions disabled except for cpptools.

**Comment by johnjutsu** [comment]
Dug up some more info.

On 10/23 I updated VS Code: code:amd64 (1.27.2-1536736588, 1.28.2-1539735992)

Didn't see any issues with that update.

On 11/13 I updated again: code:amd64 (1.28.2-1539735992, 1.29.0-1542008808)

This seems to be the culprit update.

Not sure how to see my Extension update history?

**Comment by roblourens** [comment]
Please file this on the cpp extension's repo.
