### ISSUE TITLE
Support process environment per opened window

### ISSUE THREAD

**Issue by swernli** [Microsoft/vscode#6333]
- VSCode Version: 1.1.0 (c212f0908f3d29933317bbc3233568fbca7944b1)
- OS Version: Windows 10 TP5

When the first instance of VSCode opens, it inherits the environment from whatever context it was opened from.  Any subsequent instances do not inherit their environment, instead copying the one loaded by the first instance.  So if the first instance is launched from explorer against a random file, while the second one is launched from a cmd window that has GO and GIT configured in the path, the second one will insist that GO and GIT are missing from the environment.  Reversing the order fixes the issue.

Even though inheriting environment from other open instances may provide some speed boost for opening, each new instance should inherit its environment from the context it was launched in order to preserve expected behavior for users.

Quick repro (using golang extension from https://marketplace.visualstudio.com/items?itemName=lukehoban.Go):
1. Unset GOPATH environment variable in shell.
2. Launch vscode, observe the yellow warning in the lower right indicating that GOPATH is not set.
3. Set the GOPATH environment variable correctly.
4. Navigate to a new folder and launch vscode again

Expected:
GOPATH should be loaded.

Actual:
GOPATH is still not detected because environment is inherited from first instance.

**Comment by joaomoreno** [comment]
The thing is... there is a main process which spawns the renderer processes. There are no multiple instances but always one. When you try launching a second one, it simply communicates to the first, which launches a new renderer. Very hard to control the environment of that new renderer process, not even sure whether we can do it. @bpasero ?

**Comment by bpasero** [comment]
We would probably have to copy the contents of the environment from the second launch into the process object for the new window that opens. However the more we move processes into the shared process, this environment would get lost. But it should work for the extension host and processes we fork from the renderer in general.

**Comment by joaomoreno** [comment]
Just not sure if electron's api allows us to specify a different env for each renderer, upon creation.

**Comment by swernli** [comment]
I ran into another issue with this behavior: if the first instance of code was launched elevated (say, from an elevated cmd), non-elevated instances will silently fail to start.  This makes the system-wide contextual menu "Open with Code" fail, in addition to any launches from non-elevated prompts to silently fail.

I'm sure there are benefits to this single process model where new instances are really just children of the first, but as someone who develops on several different projects simultaneously (c# tests that need to run as admin, multiple go projects with different GOPATH requirements, powershell scripts that need to access remote machines), this behavior really hampers my use.  I'm really loving vscode, and I want to use it for <i>everything</i>, and this issue makes that much harder.

Maybe a stopgap would be providing a setting that could disable this and allow each instance to be an entirely new process?  It could be off by default, and someone like me with more advanced scenarios could enable it so that I can get a fresh environment in each instance.

**Comment by mosajjal** [comment]
I've mentioned something similar in #48. Python programmers tend to use `venv` on a daily-basis. Not having a new env for each window sucks

**Comment by a2un** [comment]
Hey is this issue fixable??

**Comment by bpasero** [comment]
@swernli @mosajjal @a2un is this still an issue? I can run a second instance from the command line with different environment variables and they are picked up in that second window. Works for me on Windows and macOS at least. 

We do send the full process environment over from the second instance that is launching and merge that into the environment that we have on the main side.

**Comment by mosajjal** [comment]
@bpasero I just tested it and it's no longer an issue on Arch Linux.

One thing I've changed since commenting on this issue is running the code binary i
`/usr/share/code/bin/code`
instead of 
`/usr/share/code/code`

**Comment by bpasero** [comment]
Ok I think this is fixed meanwhile.
