### ISSUE TITLE
emmet in jsx is doing to much

### ISSUE THREAD

**Issue by axe-z** [Microsoft/vscode#63332]
It's either It works or I have to deactivated it. 
it great in jsx to create html stuff, yet abbreviation are showing on EVERY thing I write. 
![capture d ecran le 2018-11-16 a 15 58 15](https://user-images.githubusercontent.com/27289270/48646957-6efb0900-e9b8-11e8-8589-b5418dc73788.png)

not sure if I did something wrong... but it's a visual mess 
![capture d ecran le 2018-11-16 a 16 01 19](https://user-images.githubusercontent.com/27289270/48647080-de70f880-e9b8-11e8-8c2f-f869282a86a4.png)

**Comment by ramya-rao-a** [comment]
Unfortunately, there is no good way currently for emmet to know which parts of the jsx file is js, and which part is html.

I would suggest to set `emmet.showExpandedAbbreviation` to `inMarkupAndStylesheetFilesOnly` when you are doing purely js work. This will disable emmet completions in jsx files while still retaining it for html and css files. When you want to use emmet in jsx file, change the same setting back to `always`

**Comment by ramya-rao-a** [comment]
We will be using #51537 to track the need to better differentiate js and html when providing emmet suggestions
