### ISSUE TITLE
A .vscode folder with a settings.json file is created under my current working directory

### ISSUE THREAD

**Issue by ataner** [Microsoft/vscode#63331]
Issue Type: <b>Bug</b>

When I try to edit settings.json file from the Settings menu, a new .vscode/settings.json file is created under whatever working directory I have open. 

Steps to Reproduce: 
1. File > Open , Open Workspace or Open Recent 
2. Code > Preferences > Settings 
3. Click "edit settings.json" 

Expected results: settings.json  opens on editor, and edits to it are saved to the directory where VSCode is installed (or to the user's home dir if that's the case)
Actual results: a new directory called .vscode with a settings.json file is added to your current working folder 

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|-psn_0_2023918|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by roblourens** [comment]
This will happen if you have "Workspace Settings" selected. The purpose of that feature is to edit settings that just affect the current workspace. If you select "User Settings" it will save elsewhere in a global file like you expect.
