### ISSUE TITLE
All keybindings are changed since last update. Seems all shortcut keys are replaced with each other.

### ISSUE THREAD

**Issue by iyashpal** [Microsoft/vscode#63342]
- VSCode Version: 1.29.1
- OS Version: Windows 10 Pro 64bit

Steps to Reproduce:

1. Since the update of version 1.29.1 all shortcut keys are replaced with each other. I always use the default shortcut keys defined in VS code. Not any editor's (atom, sublime etc.) keybindings are imported. There is no user defined shortcut keys there.

 * `ctrl+,` is running command of `ctrl+p`
![image](https://user-images.githubusercontent.com/19922707/48656896-24799b00-ea51-11e8-904f-a9d2129a86c6.png)

 * `ctrl+b` does nothing.
![image](https://user-images.githubusercontent.com/19922707/48656906-3f4c0f80-ea51-11e8-8c88-defa6e9ad27c.png)

 * `ctrl+d` is **coping the line below** instead of **Add selection to next Find match**.
![image](https://user-images.githubusercontent.com/19922707/48656913-512db280-ea51-11e8-8cc9-c4c8e1960ec0.png)

 * `Shift+Alt+↓/↑` is performing action of **Multi-Cursor Editing** instead of **Copy line up/down**.
![image](https://user-images.githubusercontent.com/19922707/48656936-71f60800-ea51-11e8-8133-c89c32e24c11.png)
![image](https://user-images.githubusercontent.com/19922707/48656954-9c47c580-ea51-11e8-8236-f7476e80529b.png)

 There maybe other shortcut keys behaving like this. All shortcut keys were working fine in 1.29.0 version.

Does this issue occur when all extensions are disabled?:
-> **Yes**

**Comment by roblourens** [comment]
Have you installed any keybinding extensions?

**Comment by iyashpal** [comment]
@roblourens I haven't installed any keybinding extensions. I am using all VS Code's default shortcut keys.

Thanks!

**Comment by alexandrudima** [comment]
@iyashpal 

1. Open your `keybindings.json` and comment it out
2. Disable all extensions 
3. Change keyboard layout to English/US

If you do all of the above, are the keyboard shortcuts back to normal?

**Comment by alexandrudima** [comment]
Well, it is very likely you have installed an extension that tweaks your keybindings. On each extension, there is a contributes section. There you can see what the contributions are and identify extensions that tweak keybindings:

e.g.

<image src="https://user-images.githubusercontent.com/5047891/48703343-a43f6b00-ebf3-11e8-9958-bdce7796343c.png" width="250" />

**Comment by iyashpal** [comment]
Sure, Thanks for the guidance.
