### ISSUE TITLE
Suddenly tab would jump from editor to buttons in sidebar (jump widgets)

### ISSUE THREAD

**Issue by ozra** [Microsoft/vscode#63340]
- VSCode Version: 1.29.1
- OS Version: Ubuntu 18.10

Steps to Reproduce:

Sorry — I have _no_ idea, but think it's better I report than not: I was in the right-most editor pane, and suddenly I just noticed the cursor disappearing when I hit tab to indent, after some moronity, I saw the cursor jumped to the first icon in the Activity Bar, and jumping to the next on further tabs, while jumping back to the editor, to the editor on the left, and so on, with shift+tab. So I could still type, and indent using space. But tab just saw the editors as another stop in widget jumping.

Restarted VSC and then all was back to normal.

Does this issue occur when all extensions are disabled?: Yes/No

Don't know how to reproduce it, reports so potentially helpful info is not just /dev/nil'ed.

**Comment by usernamehw** [comment]
You probably accidentally pressed <kbd>Ctrl</kbd>+<kbd>M</kbd>. That toggles moving focus around by pressing <kbd>Tab</kbd>. You can unbind it.

```json
{
    "key": "ctrl+m",
    "command": "-editor.action.toggleTabFocusMode"
},
```

**Comment by roblourens** [comment]
When in that mode there will be an indicator in the status bar. You can press ctrl+m a second time to get out of it. Let me know if this wasn't what happened.

**Comment by ozra** [comment]
Ah, you figured it out, just did it by mistake now and saw the pattern xD I have ctrl+m for goto-matching-pair in other editors. Case closed. Sorry to waste your time
