### ISSUE TITLE
Preview cannot show when in global replace

### ISSUE THREAD

**Issue by joseph1125** [Microsoft/vscode#63347]
- VSCode Version: 1.29.1
- OS Version: Mac OS 10.14.1
- Special config used:
```
"search.usePCRE2": true,
"search.showLineNumbers": true
```

Steps to Reproduce:

1. Do a global replace with some files in the result
2. Preview on some files cannot show up, shows popup
```
Unable to open '67.md ↔ 67.md (Replace Preview)': ModelService: Cannot add model because it already exists!.
```
3. Redo the global replace can somehow solve this problem

Does this issue occur when all extensions are disabled?: Yes

**Comment by joseph1125** [comment]
They are all markdowns, and I find that it is easier to trigger if you
replace one of the search results when the preview is opened, and then open
another preview.

Rob Lourens <notifications@github.com> 於 2018年11月26日 週一 11:22寫道：

**Comment by roblourens** [comment]
I still can't repro. Any idea @sandy081?

**Comment by sandy081** [comment]
No idea. @joseph1125 May I know if there are any files open already while you are doing this operation? And is there any information in the console that can help us in investigation - Use the command `Developer: Toggle Developer Tools` to open the console

**Comment by joseph1125** [comment]
I will try to reproduce the issue again, please hold

Sandeep Somavarapu <notifications@github.com> 於 2018年11月28日 週三 17:52寫道：

**Comment by sandy081** [comment]
Sure

**Comment by joseph1125** [comment]
weird, after working 2382 markdowns, it still does not show any errors, I will close it for now and start another issue if this happens again.

**Comment by tschaub** [comment]
@joseph1125 @sandy081 @roblourens - I opened #64103 with steps that reproduce the issue for me.  Hope that makes it easier for others to reproduce the same.
