### ISSUE TITLE
Add default key to launch developer tool under keybinding.json.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#6334]
I thought to raise this as a feature request but after looking at the keybindings.json, looks like  it is provided for configuration.
**workbench.action.toggleDevTools**

it would be great if we can enable default setting to launch developer tool under keybindings.json.
If someone doesn't like the default key combination they can change it, but generally developers try to launch developer tool by pressing F12 or Ctrl +F12 or something like that (though it is not Browser).

**Comment by bpasero** [comment]
But why would we do that for the built product and our users? This is not something a user should typically do. And when you run out of the source code, we do assign a default keybinding. @v-pavanp please clarify and I suggest to close this one.

**Comment by bpasero** [comment]
Not planning.
