### ISSUE TITLE
code.cmd call doubles ^ in passed arguments

### ISSUE THREAD

**Issue by msftrncs** [Microsoft/vscode#63348]
- VSCode Version: 1.29.1 & Insiders 1.30
- OS Version: Win 10 1809

Steps to Reproduce:

Attempt to call up VS code via the 'code.cmd' file, that applications such as GitHub Desktop utilize to service functionality of 'open in external editor'.
(starting from my home directory, either in CMD or in PWSH)
```batchfile
".\appdata\local\programs\Microsoft VS Code Insiders\bin\code-insiders.cmd" "%%testing^carrots.txt"
```
VS Code opens a file called "%testing^^carrots.txt".  That's not what was requested, as I gave it two '%' and only 1 '^'.

if the code.CMD file is altered, and the 'CALL' removed, everything is fine.
```batchfile
"%~dp0..\Code - Insiders.exe" "%~dp0..\resources\app\out\cli.js" %*
```
instead of 
```batchfile
call "%~dp0..\Code - Insiders.exe" "%~dp0..\resources\app\out\cli.js" %*
```

Does this issue occur when all extensions are disabled?: not tried

**Comment by msftrncs** [comment]
For a confirmation, ATOM does not use CALL, https://github.com/atom/atom/blob/master/resources/win/atom.cmd

IMHO I think it is in error that CALL is escaping a quoted argument, but the help for CALL does state 'Calls one batch file from another.'

**Comment by msftrncs** [comment]
@aeschli, I think you just commited a fix for this.

**Comment by aeschli** [comment]
Oh, great :-)

@joaomoreno FYI I removed the call: https://github.com/Microsoft/vscode/commit/0dc03a8281e736dd801de7485cf74495175120e2
The problem is that with `call`, all that's behind `call` is first evaluated, in particular `%*` is expanded.
If any of the expanded arguments contains a `%` this will be evaluated again. That mean is the user provided arguments (e.g. the file paths) contain any sequence like `%1` they will be replaced

**Comment by joaomoreno** [comment]
@aeschli That `call` has been there for ages. It was also introduced for a reason, we just don't know which. Just keep this change in mind if something breaks in the near future.

**Comment by msftrncs** [comment]
#3055 is the issue marked as to when it was 'call' was originally added.  I didn't see any specific reasons there for the addition.  Atom's similar script has never had 'call'.
