### ISSUE TITLE
我的屏幕设置的很暗，但我找不到一个好的明亮的字体。我看不清代码文字。

### ISSUE THREAD

**Issue by tankfly2014** [Microsoft/vscode#63344]
我的屏幕设置的很暗，但我找不到一个好的明亮的字体。我看不清代码文字。

**Comment by joseph1125** [comment]
This issue is not relevant to this program, please dont use this as message thread.

PS I suggest using Kira Code as coding font

**Comment by roblourens** [comment]
Not clear what the issue is, please include more details
