### ISSUE TITLE
光标与连接下划线闪动

### ISSUE THREAD

**Issue by zghnzch** [Microsoft/vscode#63346]
Issue Type: <b>Bug</b>

复制链接到编辑器中 光标在最后的未知 或者下面的空白行中 连接的下划线连接与下划线 交互闪动 有时候下划线会多出三四条

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3398)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.94GB (2.98GB free)|
|Process Argv|E:\LogMessage\16\15567-ReceiveAndSend.log|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
xml2json|bui|1.1.1
vscode-standard-format|che|0.0.12
xml|Dot|2.3.2
LogFileHighlighter|emi|2.4.2
json-tools|eri|1.0.2
vscode-html-format|moh|0.0.3
prettify-json|moh|0.0.3
vscode-language-pack-zh-hans|MS-|1.29.2
quicktype|qui|12.0.46
vscode-icons|rob|7.28.0

</details>

**Comment by roblourens** [comment]
> Copy the link to the editor. The cursor is in the last unknown or the blank line below. The underline connection and the underline are connected. The flashing occurs. Sometimes the underline will be three or four more.

Sorry I don't understand, can you explain some more or share a screenshot/gif/
