### ISSUE TITLE
Add a setting to always show sidebar even when opening empty window

### ISSUE THREAD

**Issue by jamesdlow** [microsoft/vscode#63354]
It would be great if we had an option to always show the sidebar on startup, even if opening with just one file. Have a consistent user interface, rather than one that moves around depending on the number of files open is important to some of us.

**Comment by roblourens** [comment]
Sort of related to https://github.com/Microsoft/vscode/issues/3742

**Comment by kanlukasz** [comment]
I always want to keep open sidebar too, but everytime:
- if i open vs code with fresh session ( `-N i mean` ) ➡️ sidebar is close  
- if i open file with right click ( `edit with VSCode` ) ➡️ sidebar is close
- if i open new window ( `File > New Window` ) ➡️ sidebar is close

Of course, pressing `Ctrl + B` is not a big deal, but if I have to do it every day several times, it is very frustrating 😞 

---

I think that the option satisfying everyone would be something like:
- `"workbench.startupSidebar"`

with the following options:

- [ ] always _(sidebar will always be open each time on startup)_
- [ ] never _(never show sidebar on startup)_
- [ ] one _(remember state from previous session)_

**Comment by khadden-compline** [comment]
Adding my vote for this.
