### ISSUE TITLE
[BUG]cant editor list cursor(key bind)

### ISSUE THREAD

**Issue by Knoooooooow** [Microsoft/vscode#63351]
Issue Type: <b>Bug</b>

list cursor:
default :up left right down
but i want set : ctrl + i=up(cursor up)
ctrl + k=down(cursor down)

bug:i cant set

i need quick selection  and  i don't want to move my right hand to the arrow keys
hope  solve it :)

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (10.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-html-css|ecm|0.2.0
Angular-BeastCode|Mik|7.0.15
vscode-scss|mrm|0.6.2
vscode-language-pack-zh-hans|MS-|1.29.2
debugger-for-chrome|msj|4.11.1
sass-indented|rob|1.4.9
open-in-browser|tec|2.0.0
highlight-matching-tag|vin|0.8.4
JavaScriptSnippets|xab|1.7.1
sublime-commands|Zar|0.1.0
html-css-class-completion|Zig|1.17.1

</details>

**Comment by Knoooooooow** [comment]
sofa :)

**Comment by roblourens** [comment]
Can you explain some more what you're trying to do?
