### ISSUE TITLE
Auto copy code when CTRL+S?

### ISSUE THREAD

**Issue by fantasyKing** [Microsoft/vscode#6335]
- VSCode Version:latest
- OS Version:win7

Steps to Reproduce:

1. It automatically copy my code of .js file when I press Ctrl+s。

**Comment by alexandrudima** [comment]
@fantasyKing Do you have any extensions installed? Does this reproduce when closing all instances of VSCode and launching it from the command line with `code --disable-extensions` ? Did you customize any keybindings via `File > Preferences > Keyboard Shortcuts` ?

**Comment by n0652640** [comment]
I also had this issue - it seemed to be caused by this extension https://github.com/HookyQR/
It worked in previous version of VSCode, but became broken when updating to v 1.1.0.

**Comment by sajjadafzal** [comment]
I am also facing the same issue in version 1.1.0. Ctrl + s duplicates the code in a file. The issue fixes when I revert back to the earlier version i-e 10.10.

**Comment by fantasyKing** [comment]
I have solved it by updating all of extensions. @sajjadafzal @n0652640

**Comment by alexandrudima** [comment]
In the meantime we have also fixed the bug on our side (#6281) and it went out with VSCode 1.1.1.
