### ISSUE TITLE
Auto indent / indentation of question mark (?) in format document in jsx is incorrect and never indented

### ISSUE THREAD

**Issue by joshunger** [Microsoft/vscode#63355]
Issue Type: <b>Bug</b>

1. Paste the following text -

```
import React from 'react';

export default () => (
  <div>
    <div>something</div>
    ?
  </div>
);
```

2. Format Document (⇧⌥F)

ACTUAL:
![image](https://user-images.githubusercontent.com/2301847/48661687-48c67f00-ea33-11e8-8688-9e8c757a3b3e.png)

EXPECTING: What is the correct behavior? Perhaps prettier.io?
![image](https://user-images.githubusercontent.com/2301847/48661696-6b589800-ea33-11e8-9fc5-623a04141df1.png)

VS Code version: Code - Insiders 1.30.0-insider (df8ea54c5397e67b3e47df15a355bd04345c6934, 2018-11-15T06:13:38.891Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.7.0
xml|Dot|2.3.2
EditorConfig|Edi|0.12.5
prettier-vscode|esb|1.7.2
flow-for-vscode|flo|0.8.5
python|ms-|2018.10.1
vscode-jest|Ort|2.9.2
vscode-docker|Pet|0.3.1
java|red|0.34.0
sass-indented|rob|1.4.9
vscode-fileutils|sle|2.13.3
code-spell-checker|str|1.6.10
sort-lines|Tyr|1.7.0
vscode-java-debug|vsc|0.15.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.10.0
vscode-maven|vsc|0.11.1

</details>

**Comment by joshunger** [comment]
By design?

**Comment by roblourens** [comment]
Is that valid jsx?

**Comment by roblourens** [comment]
I didn't know if the ? has special meaning in jsx. I actually can't repro this, the ? stays in the same place for me. Is one of your extensions doing the formatting here?

**Comment by joshunger** [comment]
Maybe eslint formatting took over. Let me verify.

**Comment by joshunger** [comment]
@roblourens odd, if I disable extensions and select Format Document it formats it this way

```
import React from 'react';

export default () => (
    <div>
        <div>something</div>
        ?
  </div>
);
```

**Comment by joshunger** [comment]
@roblourens I can't reproduce it on b1d9b0982e78e51167a671908c39e058b343f21f 2018-11-28T06:06:14.411Z. Maybe something was fixed?
