### ISSUE TITLE
Follow VS2019’s icon change

### ISSUE THREAD

**Issue by be5invis** [Microsoft/vscode#63352]
![image](https://user-images.githubusercontent.com/240091/48659460-9d4a1880-ea8c-11e8-8333-ae64b0735699.png)

Ref: https://blogs.msdn.microsoft.com/visualstudio/2018/11/12/a-preview-of-ux-and-ui-changes-in-visual-studio-2019/

**Comment by skyel1u** [comment]
The unification of icons will make the whole Visual Studio ecology more coordinated. Hope to follow the Visual Studio 2019 icon's change.

**Comment by chrisdias** [comment]
this is being tracked in https://github.com/Microsoft/vscode/issues/71827
