### ISSUE TITLE
Update problem

### ISSUE THREAD

**Issue by blueberrycodegithub** [Microsoft/vscode#63350]
My VS Code can't update after restarting the programm.
This is the error message I get:

![vscode_update_error](https://user-images.githubusercontent.com/34658874/48659123-a915ea80-ea4c-11e8-91bd-4b961449af03.PNG)

It says I should upload a .log file:

[vscode-inno-updater-1542443308.log](https://github.com/Microsoft/vscode/files/2591612/vscode-inno-updater-1542443308.log)

Please write me back ASAP; email address is at my profile.

 
Thank you

**Comment by roblourens** [comment]
> Die Datei oder das Verzeichnis ist beschädigt und nicht lesbar.

**Comment by joaomoreno** [comment]
@blueberrycodegithub Can you fully reinstall VS Code?

**Comment by blueberrycodegithub** [comment]
Maybe it could be some extentions installed in VS Code, don't know

**Comment by dibyendumajumdar** [comment]
BTW Uninstall says some files could not be removed, and any attempt to install fails saying that Code.exe is in use. Even after reboots.

**Comment by dibyendumajumdar** [comment]
Okay - as I mentioned I uninstalled all extensions. I had C++, Java and Python extensions installed. As a test I just uninstalled VS Code and it was successful. So @blueberrycodegithub you are right - it is one of those extensions that is causing an issue. Maybe it is running in the background?

**Comment by blueberrycodegithub** [comment]
@dibyendumajumdar  It might be the local PHP server or HTTP server extension, is that possible?

**Comment by joaomoreno** [comment]
@dibyendumajumdar You have #47841

@blueberrycodegithub Can you fully reinstall VS Code?
