### ISSUE TITLE
Run Task in activated terminal

### ISSUE THREAD

**Issue by hanct** [Microsoft/vscode#63356]
VS Code : v1.25.1
Window OS: Win 10

I would like to suggest able to provide a new value for the task's  presentation.panel to support running task in the existing selected terminal. 
My reason for this is because I wanted to run 1 task in a left side of a split terminal, and another task in the right side of a split terminal. So that i can monitor the the 2 tasks status at the same time. 
Current I can't really achieve this effect. 

So to achieve this, I could only think of make the left side of the split terminal active before running the task 1. Then active the right side of the split terminal before running the task 2. But to do that, VS Code should provide this feature of able to run a task in an existing active terminal, instead of auto creating a new terminal

**Comment by dbaeumer** [comment]
Duplicates https://github.com/Microsoft/vscode/issues/47265.

Running a task in the active terminal is very hard to achieve since it is hard to determine if a terminal is idle or not. Strictly speaking it is impossible to do this reliable. So it will always be some guessing.
