### ISSUE TITLE
[BUG] Jerky screen transition when sidebar is closed

### ISSUE THREAD

**Issue by ford04** [Microsoft/vscode#63353]
- VSCode Version: 1.29.1
- OS Version: Win 10

Steps to Reproduce:

1. Set (user) settings.json to the following:
```
{
    "breadcrumbs.enabled": true,
    "workbench.sideBar.location": "right",
}
```
2. Open any file in an editor. Example `test.ts`:
```
class MyClass {

    constructor(private myProp: string) {

    }

    myMethod() {
        console.log("test");
    }

    myMethod2() {
        console.log("test");
    }

    myMethod3() {
        console.log("test");
    }

}
```
3. Toggle (open and close) the sidebar <kbd>ctrl</kbd>+ <kbd>B</kbd>.

You notice a bad looking jerky movement / motion juddering of the text for a short period of time after the sidebar closes (don't know if thats the correct word for the behavior in english). I think, it has to do with the setting `"breadcrumbs.enabled": true` that takes some screen space in the editor and not optimal render timings of the editor view. It gets more apparant, if you have the sidebar on the right side with ` "workbench.sideBar.location": "right"`.

Does this issue occur when all extensions are disabled?: Yes/No
yes

**Comment by bpasero** [comment]
@ford04 video?

**Comment by ford04** [comment]
Hey @bpasero ,
recorded a short clip showing that behavior. In the video it shows this jerky transition only on every second close of the sidebar, but in fact appeared every time (recording related).

PS: had to make a zipped .flv out of that. Converting the scene with my favorite gif tool somehow could no capture the movement, so I used OBS, made a .flv and zipped it due to github file extension restrictions.

[jerky_screen_trans.zip](https://github.com/Microsoft/vscode/files/2609848/jerky_screen_trans.zip)

**Comment by bpasero** [comment]
Does it reproduce when running `code --disable-gpu`?

**Comment by ford04** [comment]
nope, unfortunately it does not go away with `--disable-gpu` (maybe a tiny little bit better, the jerks came every second to third close of the sidebar, when I toggle it multiple times). But still not satisfying.

Kind of interesting: I was sure, that there were no problems with prior versions of VS Code, so I tried them out. Up until version `1.28.2`, everything works ok (gpu enabled).  Starting with `1.29`, it gets jerky.

**Comment by bpasero** [comment]
@ford04 does it not reproduce when breadcrumbs are disabled?

**Comment by bpasero** [comment]
Adding @jrieken based on https://github.com/Microsoft/vscode/issues/63353#issuecomment-441357899. Video to watch: https://github.com/Microsoft/vscode/issues/63353#issuecomment-441165178

**Comment by jrieken** [comment]
Sorry, the video does work for me. Please try to CPU profile this:  Hit F1 > Toggle Developer Tools. In the overflow menu select 'More Tools > JavaScript Profiler'. In there select start, let it profile for 30 to 60 seconds, stop it, save it to a file and attach the file here. Thanks.

<img width="380" alt="screen shot 2017-09-28 at 09 44 31" src="https://user-images.githubusercontent.com/1794099/30954796-d1be9e30-a431-11e7-959e-495d234c37c6.png">

**Comment by ford04** [comment]
Here it is:
[CPU-20181127T105100.zip](https://github.com/Microsoft/vscode/files/2619276/CPU-20181127T105100.zip)

**Comment by jrieken** [comment]
Sorry, but the profile didn't show any load. Can you profile while you toggle the sidebar?

<img width="1026" alt="screenshot 2018-11-27 at 11 20 46" src="https://user-images.githubusercontent.com/1794099/49075142-82b73280-f236-11e8-9a4b-c2f2e0d4b62b.png">

**Comment by ford04** [comment]
sure. 30 seconds of toggle action incoming 👌:

[CPU-20181127T140612.zip](https://github.com/Microsoft/vscode/files/2620043/CPU-20181127T140612.zip)

**Comment by jrieken** [comment]
No breadcrumbs in this profile, just normal sidebar hide/show logic. @ford04 Why do you say this depends on the breadcrumb? What is it that you observe?

<img width="1116" alt="screenshot 2018-11-27 at 15 40 59" src="https://user-images.githubusercontent.com/1794099/49089020-e7848400-f25a-11e8-8d9b-31710c427484.png">

<img width="827" alt="screenshot 2018-11-27 at 15 41 17" src="https://user-images.githubusercontent.com/1794099/49089026-e9e6de00-f25a-11e8-802c-4773465e166e.png">

**Comment by bpasero** [comment]
@jrieken according to the author, there is some noticable flicker when showing/hiding the sidebar if breadcrumbs are enabled in the editor.

@ford04 can you maybe record a screencast as gif and attach it here?

**Comment by ford04** [comment]
@jrieken hmm thats strange. I'm quite sure, I did not touch the breadcrumbs settings in any way when I did the profiling. It was (and is) on the whole time. Unfortunately, I am not very well versed with this profiler at all.

Video is nothing special,  e.g. every vlc player can open it. Here is another recording as .mp4, h264 codec:
[jerky_screen_trans2.zip](https://github.com/Microsoft/vscode/files/2620591/jerky_screen_trans2.zip)

**Comment by jrieken** [comment]
Ok, thanks @ford04. I think I have understood your issue. The breadcrumbs seems to be positioned somewhere wrong for a short time. You could make this visible using the Timeline-tab in dev tools. This only happens when using workbench-tabs. 

<img width="723" alt="screenshot 2018-11-27 at 17 08 57" src="https://user-images.githubusercontent.com/1794099/49094730-2fa9a380-f267-11e8-8e71-99bff9d67b43.png">

Question is why does this layout happen? @bpasero Is there anything special in the tabs-title-case? Do we move things around?

**Comment by bpasero** [comment]
@jrieken lets look at it in the office. the tabs are a bit special with layouting due to the custom scrollbar that is used in the parent container.

**Comment by bpasero** [comment]
Same cause as https://github.com/Microsoft/vscode/issues/63764
