### ISSUE TITLE
Add a hotkey to pin a tab in place (so new files don't overwrite open file)

### ISSUE THREAD

**Issue by nikitavoloboev** [Microsoft/vscode#63359]
You can double click on a file name in VS Code to stick the tab in place. So pressing here two times:

![2018-11-17 at 18 36](https://user-images.githubusercontent.com/6391776/48663945-b4423800-ea97-11e8-943d-98b5ebad6ed2.png)

Will pin the tab in place:

![2018-11-17 at 18 36](https://user-images.githubusercontent.com/6391776/48663947-c2905400-ea97-11e8-91e7-4a5361278d7c.png)

And new files searched will open in new tabs as well as `go to definition`.

I searched VS Code and I can't find a hotkey to do this action from keyboard. There seems to be none.

Can you please add this hotkey? I am aware of `"workbench.editor.enablePreview": false` setting that will open ALL files in new tabs however that is not whaI what I want. I want a hotkey to make the tab `stick in place` like you can already do from your keyboard.

Thank you.

**Comment by usernamehw** [comment]
<kbd>Ctrl</kbd>+<kbd>S</kbd> ?

**Comment by nikitavoloboev** [comment]
CMD + S on macOS. But thank you. This works.

**Comment by nikitavoloboev** [comment]
@usernamehw Is it possible to unpin the tab back? Say I saved the file and want to have the file not be pinned again?

**Comment by usernamehw** [comment]
Don't think so. 
Maybe you can do it somehow using multiple commands with extension https://marketplace.visualstudio.com/items?itemName=geddski.macros
