### ISSUE TITLE
Search include and files exclude not working.

### ISSUE THREAD

**Issue by mwoskowicz** [Microsoft/vscode#63363]
It seems like `search.include` and `files.exclude` are not working properly. My settings from the `settings.json`:
```
{
              "search.exclude": {
			"**/.git": true,
			"**/node_modules": true,
			"**/bower_components": true,
			"**/tmp": true,
			"**/packs": true,
			"**/log": true,
			"log": true
		},
		"files.exclude": {
			"**/.git": true,
			"**/.svn": true,
			"**/.hg": true,
			"**/CVS": true,
			"**/.DS_Store": true,
	               "**/public": true,
			".vscode": true
		},
}
```
Unfortunately I receive records from `public` folder, when I use the text-search feature.
![image](https://user-images.githubusercontent.com/23441349/48665679-4441ab00-eab3-11e8-99f3-2e903e7206df.png)

Edit: nevermind. The button was turned off 🤦‍♂️ 
![image](https://user-images.githubusercontent.com/23441349/48665745-4f490b00-eab4-11e8-9f2c-6a85e2339512.png)

**Comment by roblourens** [comment]
Thanks for following up!
