### ISSUE TITLE
Deleting large folders causes VSCode to hang.

### ISSUE THREAD

**Issue by MicahZoltu** [microsoft/vscode#63368]
This is a dupe of #56690, I'm not sure why it was locked as there were active comments saying that it had not been fixed yet.  I just ran into this problem again in the following version:
```
Version: 1.29.0 (user setup)
Commit: 5f24c93878bd4bc645a4a17c620e2487b11005f9
Date: 2018-11-12T07:47:15.448Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

Issue occurs when deleting a very large `node_modules` folder (because Node dependency management is a horrible abomination).

**Comment by MicahZoltu** [comment]
Hehe, apparently the bot isn't smart enough to notice that this is expressly a duplicate of #56690.  ;)

**Comment by bpasero** [comment]
@MicahZoltu on which OS are you (you pasted some output and it does not include this info, maybe you can let me know from where you copied it so that we can add it there)

**Comment by MicahZoltu** [comment]
VS Code -> Help -> About -> Ctrl C (or the copy button)

```
Edition: Windows 10 Pro
Version: 1803
OS build: 17134.407
```

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by tboby** [comment]
I can confirm this happens to me too. I routinely delete a large npm install folder and it hangs for maybe 30 seconds while deleting. It's clearly synchronous as UI elements do not react to hover nor click.

> Version: 1.31.1 (user setup)
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:20:54.427Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

I have the VSCode repo set up so if there's anything you'd like me to check against Code - OSS?
