### ISSUE TITLE
Shift+Tab does not work for moving back to a previous snippet placeholder

### ISSUE THREAD

**Issue by joepie91** [Microsoft/vscode#63365]
Issue Type: <b>Bug</b>

Steps to reproduce:

1. Use a snippet with multiple placeholders
2. Tab from the first to the second placeholder
3. Try to tab back to the first placeholder using Shift+Tab

__Expected result:__ Moves back focus to the first placeholder.
__Actual result:__ Outdents the line.

__Attempted workarounds:__

- Tried adding `!inSnippetMode` to the `outdent` keybinding to keep it from firing, as a user keybinding. Removed the original default keybinding without that specifier.
- Tried restarting.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:07:43.495Z)
OS version: Linux x64 4.14.79

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-6300 Six-Core Processor (6 x 3474)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|23.50GB (1.94GB free)|
|Process Argv|--skip-getting-started|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by joepie91** [comment]
This is not a duplicate of the bot-suggested issue.

**Comment by jrieken** [comment]
works for me. please share the snippet in question

**Comment by jrieken** [comment]
$0 is the final placeholder and cannot be used like that

**Comment by joepie91** [comment]
I'm not really sure why the issue got closed in this, well, rather rude fashion.

The issue is reproducible for this snippet as well, for example:

```js
	"Router Module": {
		"scope": "javascript,jsx",
		"prefix": "router",
		"body": "module.exports = function({${1:db}}) {\n    let router = require(\"express-promise-router\")();\n\n    ${0:router.}\n\n    return router;\n}"
	},
```

... where I can't jump back from `$2` to `$1` either, so evidently the problem doesn't lie with `$0`.

Not that that should matter, either, since the [VS Code documentation](https://code.visualstudio.com/docs/editor/userdefinedsnippets) states:

> The snippet syntax follows the TextMate snippet syntax with the exceptions of 'interpolated shell code' and the use of `\u`; both are not supported.

... and the [linked documentation](https://macromates.com/manual/en/snippets) states:

> Often though we want to fill in text in several places in the snippet. Multiple tab stops can be provided by inserting $1-$n. The caret will start at $1, then when pressing tab it will move to $2 and $3 on next tab etc. until there are no more tab stops. If you do not explicitly set $0, the caret will be at the end of the snippet.

... which is precisely how at the very least the "Export Module" snippet provided above works, and the page makes no mention of any limitations with regards to moving back to previous placeholders, nor anything specific to `$0`. No such limitations are mentioned on the VS Code documentation page, either.

So, as far as I can tell, I am using snippets correctly, and the inability to move back to previous placeholders is either a logic bug (should work but doesn't), or a documentation bug (shouldn't work, but isn't documented as such).

Therefore I also don't really understand what you mean with "can't be used like that". Can't be used like *what*?
