### ISSUE TITLE
Javascript Code Format Indentation not always correct

### ISSUE THREAD

**Issue by zevero** [Microsoft/vscode#6336]
- VSCode Version: 1.1.0
- OS Version: Debian Stretch

There is a glitch of the (otherwise very perfect) Javascript Code Format:

Steps to Reproduce:
0. (Set "editor.tabSize": 2 for using 2 spaces as indentation)
1. save this as a .js file
```
    var series = [{
      name: 'One',
      data: []
    }, {
        name: 'Two',
        data: []
      }, {
        name: 'Three',
        data: []
      }
    ];
```

2. Press Ctrl+Shift+i to format code 
3. The Object named One will not get indented correctly.
4. Indent it manually, so it is aligned with Two and Three.
5. Press Ctrl+Shift+i
6. Object One is misaligned again.

It does not understand how to format an object in this way (used in highcharts for example)
It works however if the first '{' is written in an extra line (which I do not like).

I may sound picky, but this is the first code formatter, that I actually use extensively and so I really care! It formats nicely without interfering too much!
Thank you!

**Comment by dbaeumer** [comment]
Moving to TS since we format JS using the TS formatter.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#8641
