### ISSUE TITLE
Remove element from tree view

### ISSUE THREAD

**Issue by Gruntfuggly** [Microsoft/vscode#63362]
I really like the new List References view, but as it's another view which (like the search view) provides buttons to remove elements, it strikes me that this would be a nice feature to allow in custom tree views too.

**Comment by jrieken** [comment]
>  it strikes me that this would be a nice feature to allow in custom tree views too.

It is implemented as custom tree view: https://github.com/Microsoft/vscode-references-view/blob/master/src/extension.ts#L338
