### ISSUE TITLE
Python Interpreter not changing!

### ISSUE THREAD

**Issue by Farhan1998** [Microsoft/vscode#63379]
Issue Type: <b>Bug</b>

When am working in a workspace, even if I change the interpreter, its not changing. Its working when am out of a workspace. Please solve it as soon as possible.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.18277

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (2.75GB free)|
|Process Argv|C:\Users\farha\Desktop\Ruuh_Voice_Bot.code-workspace|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
python-preview|don|0.0.4
code-runner|for|0.9.5
python|ms-|2018.10.1
material-icon-theme|PKi|3.6.0

</details>

**Comment by roblourens** [comment]
Please file this on the Python extension with more details

**Comment by Farhan1998** [comment]
Not an extension

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by roblourens** [comment]
vscode doesn't have an option to pick a python interpreter built in. You are probably using the python extension. If not, please give more details.

**Comment by Farhan1998** [comment]
Oh..okay, then the extension name is Python....coz the problem is in 'Python Interpreter'

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
