### ISSUE TITLE
VS Code Node.js error

### ISSUE THREAD

**Issue by Blaze2658** [Microsoft/vscode#63371]
- Visual Studio Version: 15.8.7
- OS: Windows 10

I am trying to make a node.js application for a discord bot in Visual Studio. Weather or not this is a good idea aside, I get this error in the debugger anytime I try to run the code: "The program 'app.js' has exited with code -1 (0xffffffff)" I have googled this but can not find what this means.  If this is the wrong place to post this, please let me know. I am kind of new to this, so thanks in advance.

**Comment by weinand** [comment]
This repository is for "Visual Studio **Code**" not "Visual Studio".
