### ISSUE TITLE
items in 'open recent' sub menu are missing ampersand '&'

### ISSUE THREAD

**Issue by msftrncs** [Microsoft/vscode#63372]
- VSCode Version: 1.29.1 & Insiders 1.30.0
- OS Version: Win 10 1809

Steps to Reproduce:

1. Locate a file (or folder) where the file path will contain an ampersand `&`, and open it in VS Code.  Then close it. (closing is optional though)
2. Look for this item in the 'Open Recent' sub menu of the 'File' menu.  The `&` character will be missing.

![image](https://user-images.githubusercontent.com/26179051/48668614-7ce38380-eab7-11e8-825e-92856e55f12d.png)

In this image, I am showing the editor 'hello && there.txt' open, and the bottom is part of the 'Open Recent' menu with the last line showing the same file without the '&&'.  Also, the first folder shown, is missing a '&', as it should have read '...\&%^ Test Repo\...'

This is a well known issue with Windows Applications.  I write a bug report for almost every application I use, for this very issue, as I almost always have a use to open a file that possesses a `&` in the path.  The `&` character is used by the normal Windows menu system to designate the access key.  Normally, to include an actual `&` in the menu, you would use double `&`, but if you open a file in Code with two `&` in a row they are both removed.  Most all application programmers forget to escape the `&` out of the file names/paths before they put them in menu's (or sometimes from other user input locations in other kinds of applications as well).  For instance, even WordPad in Win 10 1809, and Word 2016 fail to show the `&` in the tool tip in the recent menu.  However, here, I am not sure what is going on.

This might be similar to issue #61139.

**Comment by sbatten** [comment]
@msftrncs_ thanks for reporting and the information. Same underlying issue as #61139 so resolving as duplicate
