### ISSUE TITLE
[HTML, Emmet] link:manifest

### ISSUE THREAD

**Issue by Mlocik97-issues** [Microsoft/vscode#63384]
please, add to emmet "link:manifest" -> `<link rel="manifest" href="manifest.json">`

**Comment by ramya-rao-a** [comment]
You can submit a PR for the same at https://github.com/emmetio/snippets/blob/master/html.json

Once the change is in there, we can absorb it here

**Comment by irrationalRock** [comment]
Hi, I was doing some digging around and I found that `html.json` already has it:

https://github.com/emmetio/snippets/blob/9515e86def0f237602bf20e3e757d3361a06f2cc/html.json#L22

But even when I type `link:manifest`, it doesn't want to work.

I think this problem might have something to do with https://github.com/emmetio/html-snippets-resolver.

**Comment by Mlocik97-issues** [comment]
yes, I commited that https://github.com/emmetio/snippets/commit/c656181a295fa1124de8b752a2e7ae5d868921af

**Comment by irrationalRock** [comment]
@Mlocik97-issues thanks for that, I didn't notice that.

**Comment by Mlocik97-issues** [comment]
@ramya-rao-a Can You add these changes to VSCode?

**Comment by octref** [comment]
@Mlocik97-issues Hi I'm maintaining emmet now. I'll try to upgrade in December and ship it for January build.

**Comment by ramya-rao-a** [comment]
@octref The vscode-emmet-helper is updated to absorb this change. Only thing left is to publish a new version for it and use it in VS Code

**Comment by octref** [comment]
Fixed. But the other suggestion doesn't look right:

@ramya-rao-a Should this completion be provided? (Maybe we can rank it lower).

![image](https://user-images.githubusercontent.com/4033249/51272771-e11fa800-197f-11e9-94f2-9fec07f7dada.png)

**Comment by ramya-rao-a** [comment]
@octref That seems to be showing up regardless of what we type

![image](https://user-images.githubusercontent.com/16890566/51290942-3d072280-19ba-11e9-85ed-5dcc2d9ff1ab.png)

We should track that as a separate bug. And try not to show it at all.
