### ISSUE TITLE
Improve Translations of VSCode

### ISSUE THREAD

**Issue by Gillespie59** [Microsoft/vscode#63383]
- VSCode Version: 1.22.2
- OS Version: Mac OSX

Steps to Reproduce:
I do not know if this is the right behavior, but let's go create this issue anyway. Because it was strange to me. 
When I want to extract a code into a function/method or constant for example (check the screenshot below), the text is translated in french except the technical words (function, method, constant, ...)

Is it normal ?

Does this issue occur when all extensions are disabled?: Yes/No

<img width="676" alt="capture d ecran 2018-11-08 a 11 13 44" src="https://user-images.githubusercontent.com/555768/48672990-2751ba00-eb3d-11e8-9c08-6cab46149f48.png">

**Comment by roblourens** [comment]
I don't know whether that's correct or not, but if you're interested in contributing better translations, please see this page: https://github.com/Microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project

**Comment by Gillespie59** [comment]
Why have you closed this issue if you are not sure ?

**Comment by roblourens** [comment]
Our translations come from the community, I don't speak French 😁 See my link for more details if you want to suggest a different translation
