### ISSUE TITLE
VS code freezing

### ISSUE THREAD

**Issue by teokitan** [Microsoft/vscode#63389]
Issue Type: <b>Bug</b>

VS code often completely freezes and I have to close it forcely when it does

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:34:20.517Z)
OS version: Linux x64 4.10.0-38-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2367M CPU @ 1.40GHz (4 x 1400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 2, 2|
|Memory (System)|3.74GB (0.11GB free)|
|Process Argv|/usr/share/code/code --unity-launch /home/teo/Documents/Programiranje/Python/PersonalAssistant/main.py|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.10.1

</details>

**Comment by roblourens** [comment]
1.26.1 is a very old version. Can you try upgrading to the latest release to see if it's still an issue?

**Comment by AibiTi** [comment]
This problem still occurs in v1.28.2.

**Comment by Joelande94** [comment]
In v1.29.0 too (at least on my mac), and it freezes on my ubuntu machine as well. While I'm not sure which version of Code it has it should be the latest version available for ubuntu, since I installed it yesterday.

**Comment by johnmarkwayve** [comment]
This has been happening to me recently too for the last few days. I wouldn't be surprised if it was because of the 1.29.0 update. Worked perfectly for months before that.

Ubuntu 16.04
Version: 1.29.0
Commit: 5f24c93878bd4bc645a4a17c620e2487b11005f9
Date: 2018-11-12T07:42:27.562Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by domino14** [comment]
Same here. The newest version has been freezing. Sometimes a window pops up in front telling me that the window has stopped responding, and if I want to close it or restart it or wait. This hasn't happened in any prior versions that I know of.

**Comment by roblourens** [comment]
We fixed a hanging issue in 1.29.1, please upgrade to that version.

**Comment by roblourens** [comment]
@teokitan let me know if this still happens in the latest. Others, open new issues if it happens in the latest.
