### ISSUE TITLE
yaml file does not colorise

### ISSUE THREAD

**Issue by Noiknez** [Microsoft/vscode#63382]
When I open a specific yaml file (the longest that I have) in visual studio code, the color syntax for this file bug completely, this is really annoying because its harder to read in it (comment, line, ...)

![image](https://user-images.githubusercontent.com/20723083/48671447-abe60d80-eb28-11e8-9fce-05f7b7e1f8ac.png)

- VSCode Version: Windows 10 x64, v17134.407
- OS Version: 1.29.1

Steps to Reproduce:

1. Open the file in VS code
Yaml file link : https://pastebin.com/3QiMYN7J

Does this issue occur when all extensions are disabled?: Yes

**Comment by Noiknez** [comment]
Its not the same issue

**Comment by roblourens** [comment]
Can you share that file?

**Comment by Noiknez** [comment]
[Tesseract_Guilde.zip](https://github.com/Microsoft/vscode/files/2593046/Tesseract_Guilde.zip)

**Comment by dpoetzschke** [comment]
I ran into the same error when configuring .circleci/config.yaml

The problem seems to be a missing closing quote, which in my case in not true but falsely recognized as such. 
When checking Noiknez file i get the same issue that can also be fixed by adding a false double-quote.

A smaller version of my file is this, which can be fixed by adding a second double-quote in line 27
```version: 2

jobs:
  dockerize:
    working_directory: ~/project

    docker:
      - image: google/cloud-sdk

    steps:
        - checkout

        - run:
        name: 'Build and push docker image'
        command: |
          docker run \
                --rm \
                -w /app \
                -v $(pwd):/app \
                -v ${HOME}:/config \
                -v /var/run/docker.sock:/var/run/docker.sock \
                google/cloud-sdk \
                sh -c "\
                  command1 && \
                  command2 && \
                  command3
                "
        - run:
        name: 'test'
        command: |
          ....
          ....```

**Comment by Noiknez** [comment]
I have more information, but I don't know if it is related

![image](https://user-images.githubusercontent.com/20723083/48971373-cd5b6380-f018-11e8-9c0d-e0811817883c.png)

![image](https://user-images.githubusercontent.com/20723083/48971377-e3692400-f018-11e8-94aa-b4a3d805909e.png)

![image](https://user-images.githubusercontent.com/20723083/48971380-eebc4f80-f018-11e8-9041-8eb5f825c7ef.png)

**Comment by alexr00** [comment]
This issue was moved to textmate/yaml.tmbundle#30

**Comment by alexr00** [comment]
I moved the issue to the owners of that grammar. Thank you for filing the issue!
