### ISSUE TITLE
File Icon themes: Some icon themes misalign the directory structure in the sidebar

### ISSUE THREAD

**Issue by amithm7** [Microsoft/vscode#63380]
Issue Type: <b>Bug</b>

Steps to Reproduce: Open File > Preferences > Select theme "Minimal (vs code)" theme

Here in the gif below, only "Seti" Theme aligns the directory structure properly, while the other two shift the the icons to right. Hence, due to misalignment, "app.html" and "login.html" appear to be inside "public/" directory while they are files under "app/" directory. 
![bug3](https://user-images.githubusercontent.com/7036770/48670862-38062e00-eb45-11e8-8886-3460b685a6b9.gif)

#17777 could solve this too

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:07:43.495Z)
OS version: Linux x64 4.9.0-8-amd64

**Comment by roblourens** [comment]
This is by design, you simply need to use folder icons if you want them to be aligned that way.

**Comment by amithm7** [comment]
@roblourens I'm sorry but i don't understand, the problem appears when the folders have icons. What does it mean when you say i have to use "folder icons"?

**Comment by gjsjohnmurray** [comment]
Discussion on #28974 may be relevant. And #61808 is another case where Seti vs Minimal makes a significant difference.

**Comment by roblourens** [comment]
This is correct, see that the text of app.html vs "js" shows that "js" is indented more. The arrow off to the left might make it confusing but this is as designed.

**Comment by amithm7** [comment]
@roblourens yes, i see that; so the indentations are based on text of files but not considering the space occupied by arrow is what i see as a problem.

Here, in the picture below ( No icon theme ), you can see that it seems like "js" folder (incuding it's arrow) is aligned with "app.html". The fact that by design "app.html" file's text is also aligned with "public" folder's text is less obvious visually.
![2018-11-20_11-43](https://user-images.githubusercontent.com/7036770/48754924-83414d80-ecb9-11e8-9557-adf7fc88a3e4.png)

**Comment by roblourens** [comment]
I understand, but it's not likely to change
