### ISSUE TITLE
Can I just use Tab?

### ISSUE THREAD

**Issue by zhy1378de** [Microsoft/vscode#63381]
Issue Type: <b>Bug</b>

Hi dear developers,

I know you want to suggest us using double blanks instead of one Tab in Angular, SASS, TypeScript and so on.

But I just want to use Tab.

Can you please stop replace Tab to blanks when I elect that my primary indent button is Tab?

Please be nice to tab guys, it's really much more simple and beautiful.

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:39:38.932Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.33GB free)|
|Process Argv|-psn_0_6780535|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
html-css-class-completion|Zig|1.17.1
vscode-css-formatter|aes|1.0.1
code-gnu-global|aus|0.2.2
language-kuka-krl|d4n|1.5.1
app-migrator|deb|0.0.6
vscode-html-css|ecm|0.2.0
smarty|imp|0.3.0
Angular2|joh|7.0.1
vscode-clang|mit|0.2.3
vscode-language-pack-de|MS-|1.29.2
cpptools|ms-|0.20.1
csharp|ms-|1.17.1
Go|ms-|0.7.0
md2pdf|qin|0.0.1
java|red|0.34.0
sass-indented|rob|1.4.9
stylelint|shi|0.46.1
pdf|tom|0.4.1
vscode-java-debug|vsc|0.15.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.10.0
vscode-maven|vsc|0.11.1

</details>

**Comment by roblourens** [comment]
You can use the `editor.insertSpaces` setting
