### ISSUE TITLE
Cross-platform UWP Edge Shell and Chakra Core

### ISSUE THREAD

**Issue by ab35** [Microsoft/vscode#63387]
Hi,

Why isn't VSCode based on UWP Edge Shell and ChakraCore instead of Chromium and V8 (Electron)?

Why isn't Edge Shell programmatically available in a cross-platform way, the same manner as chromium is with Puppeteer, for building desktop applications with a nodejs backend ?

**Comment by roblourens** [comment]
Electron lets us keep a single code base across platforms. We do have this issue to release in the windows store. 

> Why isn't Edge Shell programmatically available in a cross-platform way

This one is above my pay grade 😁 I think it's not likely that Edge will be made cross platform.

**Comment by ab35** [comment]
So windows platform is not really universal ? It is a platform that locks in developers and reduce their market and audience ?

**Comment by ab35** [comment]
The goal is not publish in the windows store (at least not the first goal). The goal is to be able to build cross-platform applications using the tools that are present in the windows platform. The best cross-platform stack being the webstack.

**Comment by ab35** [comment]
If even microsoft guys do not believe in their own product, it is no wonder that such question is above their pay grade...

**Comment by ab35** [comment]
> I think it's not likely that Edge will be made cross platform.

On October 5, 2017, Microsoft announced a preview of Microsoft Edge for Android and iOS.[8] ([Wikipedia](https://en.wikipedia.org/wiki/Microsoft_Edge))

**Comment by roblourens** [comment]
The issue I meant to link is https://github.com/Microsoft/vscode/issues/10759

@chrisdias anything else to say about UWP/the windows platform?

**Comment by ab35** [comment]
One hopes that one didn't sound rough or personal: kindly excuse if that sounded like that. 

Daily user of VSCode and Windows platform here.

It is just a bit frustrating to not have cross-platform tools to work with and to have to download chromium everytime when Edge could have the same functionality out of the box on Windows for desktop applications built upon the webstack.

I think OS manufacturers could do better and even have a common standard browser shell for application development: one application built on any OS upon the webstack should work on any other OS out of the box... Total interoperability: that ... would be :cool:
