### ISSUE TITLE
hard to read menu bar on linux

### ISSUE THREAD

**Issue by Bandito11** [Microsoft/vscode#63385]
Issue Type: <b>Bug</b>

Hopefully this is not an issue repeat but after the update the menu dark and really hard to see.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:07:43.495Z)
OS version: Linux x64 4.18.0-11-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|7.63GB (4.68GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.40
prettier-vscode|esb|1.7.2
auto-rename-tag|for|0.0.15
Angular2|joh|7.0.1
code-beautifier|mic|2.1.0
autoimport|ste|1.5.3

</details>

**Comment by Mlocik97-issues** [comment]
/duplicate #62593 related to https://github.com/electron/electron/issues/15194

**Comment by rifat-H** [comment]
Go to Settings>type "window.titleBarStyle" > select "custom" and restart..
