### ISSUE TITLE
Staging chunk in file discards previous staged chunks

### ISSUE THREAD

**Issue by jakub-gonet** [Microsoft/vscode#63386]
Issue Type: <b>Bug</b>

1. click green/blue/red block on line and stage it by `+` sign
2. click other line block to stage it
3. first staged chunk is discarded

VS Code version: Code - OSS 1.30.0 (610918d48f581d2644745fa51c63515046df9ae9, 2018-11-18T15:05:55.294Z)
OS version: Linux x64 4.9.135-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz (4 x 3441)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 7, 8|
|Memory (System)|7.71GB (1.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by joaomoreno** [comment]
Can you show me a screen recording of the issue?

**Comment by jakub-gonet** [comment]
Sure:

**Comment by jakub-gonet** [comment]
Sure:
https://youtu.be/2VJan4dRdFM

As you may see, I started with clean document, but VSC showed that one line was modified (was modified earlier, as it took me 2 attemps to record this, but I removed modifications by using git). Aside from that non existent modif, VSC is clearly swapping between two staged versions. One line was added to staging and then the second should be added, but it swapped the staged versions.

**Comment by joaomoreno** [comment]
> I started with clean document, but VSC showed that one line was modified

OK that is weird. That sounds like it's the actual issue, not your original description.

So, does VS Code not react to git repo events?

**Comment by jakub-gonet** [comment]
Hard to tell actually, because commits are updated. I'll check if reopening a file forces VSCode to record all new operations on repo.

I'm kinda suprised that nobody earlier spotted this issue, staging different things directly from VS seems to be quite popular workflow.

**Comment by joaomoreno** [comment]
> I'm kinda suprised that nobody earlier spotted this issue, staging different things directly from VS seems to be quite popular workflow.

I can't reproduce it, I bet most people can't.

> Yup, reloading the file fixes this.

You mean, closing and opening it?

---

Then, how _easy_ is it for you to hit the issue?

**Comment by jakub-gonet** [comment]
Yep, reopening fixes that visual bug.

As it's happening to every file in every repo, quite easy.

I'll try deleting all local files and unistalling VS Code, maybe it won't occur in clean install.

**Comment by joaomoreno** [comment]
If you want to simulate a clean install simply run with `code --user-data-dir DIR` and pick a new folder for the user data dir.

**Comment by jakub-gonet** [comment]
Nope, switching folders and even reinstalling didn't help at all.
