### ISSUE TITLE
workspace.asRelativePath doesn't return the relative path when the folder matches the workspace folder

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#63391]
Issue Type: <b>Bug</b>

Now this *may* not be a bug as the docs say:
> When there are no [workspace folders](#workspace.workspaceFolders) or when the path is not contained in them, the input is returned.

And technically the workspace folder itself isn't contained within itself, but I would have still expected it to convert the path to a relative path -- similar to Node's `path.relative` function

```ts
import * as vscode from 'vscode';

export async function activate(context: vscode.ExtensionContext) {
    if (vscode.workspace.workspaceFolders) {
        const path = vscode.workspace.asRelativePath(vscode.workspace.workspaceFolders[0].uri);
        // path will equal vscode.workspace.workspaceFolders[0].uri.fsPath, rather than '' or something like that
        path;
    }
}
```

/cc @jrieken 

VS Code version: Code - Insiders 1.30.0-insider (24b0f75b1e33b88f30f2ed9d5b17ca60062c270b, 2018-11-16T06:20:02.054Z)
OS version: Windows_NT x64 10.0.18282

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (16.45GB free)|
|Process Argv|c:\Users\Eric\code\vscode-gitlens|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by jrieken** [comment]
>  but I would have still expected it to convert the path to a relative path

It's always the relative to the workspace itself, so what's the relative path of a path itself?

**Comment by eamodio** [comment]
`.` or just `/`?

**Comment by jrieken** [comment]
Not a fan, the point of this function is to help with display labels and having just `.` or `/` isn't helpful IMO. What is your scenario?

**Comment by jrieken** [comment]
> The Live Share api uses this call internally to convert uris from host to guest and guest to host.

What? That sounds so wrong

**Comment by eamodio** [comment]
Why? It's part of their conversion, since the guest uris are all relative rather than absolute they use that api as the first part of converting it.
