### ISSUE TITLE
Add Files include include

### ISSUE THREAD

**Issue by Jackie-Yang** [Microsoft/vscode#63399]
Issue Type: <b>Feature Request</b>

Now we can use "files exclude", but some projects have too much files to exclude, can we use "files include" to add the files/folders we need?

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.16299

**Comment by cleidigh** [comment]
@Lennon925 
Not at this point.  The team will have to track and compare the various feature requests.
I would give a thumbs-up to the original issue from @Jackie-Yang , the number of up votes
drives a lot of the process.

**Comment by roblourens** [comment]
This is not likely to happen. Too complicated to think about how the 'excludes' and the 'includes' interact, for example.
