### ISSUE TITLE
No event prompts when selecting elements using Queryselector

### ISSUE THREAD

**Issue by ScrLiberty** [Microsoft/vscode#63395]
title: 使用 querySelector 选择元素时没有事件提示

在 javascript 中使用 querySelector 或者 querySelectorAll 选择元素不会有事件提示，类似于：onkeyup, onmousedown, onclick 等 提示。希望能修复此问题。

Using Queryselector or Queryselectorall selection elements in JavaScript does not have event hints, similar to: onkeyup, onmousedown, onclick, and so on. Hopefully, you can fix this problem.
--From Microsoft Translator--

**Comment by mjbvz** [comment]
Please provide some example code

**Comment by ScrLiberty** [comment]
> 请提供一些示例代码

![obox](https://user-images.githubusercontent.com/40620264/48744010-8845d300-eca0-11e8-975c-275fdf726955.png)
![oboxs](https://user-images.githubusercontent.com/40620264/48744014-8b40c380-eca0-11e8-9ac1-2e9847998081.png)
![oboxid](https://user-images.githubusercontent.com/40620264/48744103-d4911300-eca0-11e8-9087-e5854b993988.png)

-------------------------------------------------------------------------
Similar to the code on the image, use document.querySelector('#box'); or document.querySelectorAll('.box'); there is no code hint for on event when the selector is used.

The on event code hint appears when you select an element using document.getElementById('box');
-------------------------------------------------------------------------
--From Google Translate

If you can't view the image, please see the sample code below

- <body>
-     <div id="box" class="boxs"></div>
-     <div class="boxs"></div>
-     <div class="boxs"></div>
-     <div class="boxs"></div>
- </body>
- <script>
-     let oBox = document.querySelector('#box');
-     let oBoxs = document.querySelectorAll('.box');
-     let oBoxID = document.getElementById('box');
- 
-     oBoxID.on
- </script>

**Comment by mjbvz** [comment]
VS Code can not safely assume that you selector will return a specific dom node type. Try something like:

```js
const box = /** @type {HTMLDivElement} */ (document.querySelector('box'));
```
