### ISSUE TITLE
Python Shift+Enter with Code Cells not running line

### ISSUE THREAD

**Issue by milewsmr** [Microsoft/vscode#63393]
Default keybindings
{
        "key": "shift+enter",
        "command": "python.execSelectionInTerminal",
        "when": "editorFocus && !findInputFocussed && !python.datascience.hascodecells && !replaceInputFocussed && editorLangId == 'python'"
    },
    {
        "key": "shift+enter",
        "command": "python.datascience.runcurrentcelladvance",
        "when": "editorFocus && python.datascience.featureenabled && python.datascience.hascodecells"
    }

Believe the issue is with the !python.datascience.hascodecells, if there is a code cell anywhere in the file the run selection/line is not functioning. 

Work around is to map python.datascience.runcurrentcelladvace to a different binding (shift+alt+enter), and remove the !python.datascience.hascodecells from "when" for python.execSelectionInTerminal

Its would be useful to have by default ability to run lines or cells as commanded.

**Comment by roblourens** [comment]
Please file this on the Python extension's repo
