### ISSUE TITLE
Format selection Ctrl K Ctrl F doesn't work anymore

### ISSUE THREAD

**Issue by albu77** [Microsoft/vscode#63392]
Issue Type: <b>Bug</b>

Select a portion of code
Type Ctrl K CtrlF 
The Search text box show up but no format of the selection
And there is no conflict whown for this combination

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:11:49.509Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz (4 x 2294)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|5.98GB (1.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-snippet-pack|aka|0.1.5
project-manager|ale|9.1.0
vscode-custom-css|be5|3.0.1
css-compressor|bes|0.0.2
path-intellisense|chr|1.4.2
open-html-in-browser|cod|0.1.21
vscode-instant-markdown|dba|1.4.3
vscode-great-icons|emm|2.1.44
json-tools|eri|1.0.2
vscode-todo-plus|fab|4.10.0
beautify|Hoo|1.4.7
ftp-simple|hum|0.6.8
typings-autoinstaller|jvi|1.2.0
gitignore|mic|1.0.1
vscode-language-pack-fr|MS-|1.29.2
debugger-for-chrome|msj|4.11.1
live-server-preview|neg|0.1.2
flowmaker|spe|1.2.0

(2 theme extensions excluded)

</details>

**Comment by albu77** [comment]
I've just tried with all extensions disabled: IT IS DOING SAME THING
For the fie format, .js, .html json anyone I tried.
Something strange is also that context Menu is not showing the key shortCut although the setting show good record of the key binding, as shown on images attached
![bug1](https://user-images.githubusercontent.com/624802/48696695-f035e400-ebe2-11e8-9f36-70ae4be372c6.png)
![bug2](https://user-images.githubusercontent.com/624802/48696699-f330d480-ebe2-11e8-8f25-8d74e24709e7.png)

**Comment by alexandrudima** [comment]
@albu77 Most likely, there is another keybinding for `Ctrl+K Ctrl+F` that overrides this one.

Can you please confirm that your `keybindings.json` is empty and that searching for "Ctrl+K Ctrl+F" only shows Format Selection:

![image](https://user-images.githubusercontent.com/5047891/48768016-593b5b80-ecb8-11e8-85a2-cdaa557aa84a.png)

**Comment by albu77** [comment]
**Ok, my bad...... I'm sorry** 
I made an error in my keybindings.json: I forgot to add  "when": "terminalFocus" in the binding of the clear terminal when I added it.
Now with this correction Everything is Ok (shortkey and contextMenu)
```
{
   "key": "ctrl+k",
    "command": "workbench.action.terminal.clear",
    "when": "terminalFocus"
   }
```
