### ISSUE TITLE
Maintain File Permissions when Copying Directories/Files on Linux and MacOS

### ISSUE THREAD

**Issue by caleblloyd** [Microsoft/vscode#634]
When copying a directory or file in the file tree on Linux and MacOS, all of the file permissions in the destination file/directory get reset to 644.

VS Code should maintain file permissions.

**Comment by bpasero** [comment]
@joaomoreno I am quite sure this code [1] is still from you from the old days ;). Maybe you could have a look and also apply it to the pipeFs() method where no mode is set. 

[1] https://github.com/Microsoft/vscode/blob/master/src/vs/base/node/extfs.ts#L107

**Comment by joaomoreno** [comment]
@bpasero the `& 511` is mine: it just truncates the permissions but doesn't set them to 644. Something else is doing that.
