### ISSUE TITLE
lanuch.json format happen to some errors

### ISSUE THREAD

**Issue by zsirfs** [Microsoft/vscode#63409]
- VSCode Version: newest version
- OS Version: OSX newest version

Steps to Reproduce:

1. create new debug configation

Does this issue occur when all extensions are disabled?: No

![image](https://user-images.githubusercontent.com/22249411/48692455-170b0f00-ec11-11e8-9453-bd140273f75b.png)

**Comment by weinand** [comment]
What exactly is the problem?

**Comment by zsirfs** [comment]
This is a luanch.json formatted question
