### ISSUE TITLE
Explorer: reveal should not always be in center

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#63406]
It looks like a change was pushed to no longer reveal files in the center (https://github.com/Microsoft/vscode/commit/76ee724e18353c93b2cc8eca92de5edd848b05ff and https://github.com/Microsoft/vscode/commit/b4c6906b62e3199eee87c17649979939a4e43323). I find this change breaks my usual workflow where upon navigation in files, I nicely see all files around the one that is active to jump to a related file. This workflow is broken if the file is at the bottom of the list (which it is most of the times if the tree is large).

If there is any interest in changing this behaviour (that we always had btw), it should be a setting but I would leave the default as it is today.

**Comment by bpasero** [comment]
@isidorn @joaomoreno maybe that would be something to try out: if the first resource gets revealed (on startup) or any other resource that is not in viewport, reveal it centered, otherwise reveal it without scrolling.

Just checked with Eclipse and they seem to do just that:

![before](https://user-images.githubusercontent.com/900690/48717790-61dd5480-ec1a-11e8-89b0-1771a940f47a.gif)

**Comment by bpasero** [comment]
Nevertheless, I got so used to the fact that the explorer would always center around the currently active file because that gives me super easy access to any file that is near by. I think this functionality would be lost either way so I would wish for a setting.

**Comment by isidorn** [comment]
Yes, we should add a setting - I plan to extend explorer.autoReveal to also take a string
Default I will do the reveal in center if outside viewport

**Comment by bpasero** [comment]
@isidorn sounds good. I still think the default behaviour should be to reveal in center if outside viewport though.

**Comment by jrieken** [comment]
@isidorn this was a bad change and completely ruined the way how it work with the explorer. I don't auto reveal, but manually, and I do that to see the file and its context. The latter isn't possible anymore.

**Comment by isidorn** [comment]
For now will go back to the old behavior by reverting via 722b04f340.
Pushing this issue to december since than I plan to adopt the explorer to the new tree. And than I can look into optimising the reveal behavior and to make it configurable as we discussed
@jrieken I have triggered new insiders builds and do not plan to release them. You can download one if this is blocking you from working.

**Comment by Tyriar** [comment]
Just did verification for https://github.com/Microsoft/vscode/issues/62901

My only problem with ctrl+shift+e now is that it should still be centered when the file was outside of the viewport imo. To clarify I use `"explorer.autoReveal": false` and a keybinding for `workbench.files.action.showActiveFileInExplorer`.

> maybe that would be something to try out: if the first resource gets revealed (on startup) or any other resource that is not in viewport, reveal it centered, otherwise reveal it without scrolling.

That's what I want 👍

**Comment by isidorn** [comment]
Got it, thanks @Tyriar 
We'll look into this next milestone

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/23902
