### ISSUE TITLE
OCaml syntax highlighting problem

### ISSUE THREAD

**Issue by hbbio** [Microsoft/vscode#6340]
- VSCode Version: 1.1.0
- OS Version: OSX 10.10

Steps to Reproduce:

1. OCaml comments are nested, i.e.
```ocaml
(* this (* and *) that *) 
```
is a proper comment, but highlighting ends the comment at first occurrence of closing pattern.

**Comment by aeschli** [comment]
Are you using an extension for the OCaml support? Please file the issue against the provider of the extension.
