### ISSUE TITLE
Search based on folder name for (__init__.py/index.ts/etc) 

### ISSUE THREAD

**Issue by seanbudd** [Microsoft/vscode#63403]
When searching for a file, files with the name \_\_init__.py/index.ts/etc return a large amount of results for large projects. If possible, it would be nice to be able to search for the package/module name and the index/init file is returned. 

**Example:** If I have the following module "project/lib/foo/\_\_init__.py" I would like "\_\_init__.py" to show as a result when searching "foo" (and/or "project/lib/foo")

**Note:** I'm happy to give a crack at the PR for this, given that vscode team think it's an appropriate addition

**Comment by roblourens** [comment]
Not clear exactly what you want. If you type "foo" in file search (cmd/ctrl+p) it should return files in a folder "foo"

**Comment by seanbudd** [comment]
Oops, so it does. I guess I was just receiving other files as a priority with names similar to "foo" rather than "foo/index.ts" or they hadn't been indexed yet.
