### ISSUE TITLE
How to customize the color of the terminal command and how to customize the text

### ISSUE THREAD

**Issue by zhaipanyu** [Microsoft/vscode#63401]
https://s1.ax1x.com/2018/11/19/FSIW5j.png

I try to use  "terminal.foreground":  to settings color. 
but all fonts have changed.

**Comment by roblourens** [comment]
The setting controls the default text color but for an effect like that, you have to configure your shell. I suggest searching "customize prompt" with the name of your shell, e.g. "bash"
