### ISSUE TITLE
[Feature request] vscode for browser

### ISSUE THREAD

**Issue by wzxinchen** [Microsoft/vscode#63408]
I need a WebIDE. I wrote it myself. Later I found that vscode is actually a WEBIDE, but the bottom layer is nodejs, but if I transfer the underlying part of nodejs to the server, this should work. of. Although it doesn't seem to be a complete IDE, the features I want are all there. So I hope to have a browser version of vscode. At first I thought it might be difficult, but after I tried to modify it, I succeeded. Although the function is not comparable to the real vscode, at least I can write typescript, html, css. I can also load plugins. So I hope to have a browser version of the official version of vscode.

**Comment by AibiTi** [comment]
very funny

**Comment by wzxinchen** [comment]
I am trying to modify it again, because the previous changes are too thorough and almost impossible to upgrade.

**Comment by Lachlantula** [comment]
Have you tried [StackBlitz](https://stackblitz.com/) or [CodeSandbox](https://codesandbox.io/) (the latter has the option in Preferences under Experiments)?

**Comment by wzxinchen** [comment]
> Have you tried [StackBlitz](https://stackblitz.com/) or [CodeSandbox](https://codesandbox.io/) (the latter has the option in Preferences under Experiments)?

I tried, third-party editors too, include them, if they allows me to load the specified project and embed they into my own website, this is fine, but they don't seem to do it.
