### ISSUE TITLE
Analyse extensions and find bad usages of vscode

### ISSUE THREAD

**Issue by alexandrudima** [microsoft/vscode#63418]
Just by accident, I observed the Powershell extension was using `vscode` as a regular dependency instead of as a dev dependency. By moving `vscode` to a dev dependency, they [have reduced their install size from 62.1 MB to 12.9 MB](https://github.com/PowerShell/vscode-powershell/pull/1608#issuecomment-439710479)

I suggest we do the following:
1. Scan for existing extensions in the marketplace and create issues/PRs
2. Add a lint check in the `extension-editing` extension that is bundled with VS Code.

**Comment by alexandrudima** [comment]
@bpasero Sorry, I have no idea

**Comment by egamma** [comment]
>By moving vscode to a dev dependency

This has been done and vsce is now checking whether vscode is dependency or a devDependency, closing.
