### ISSUE TITLE
When the `text` in StoppedEvent is null or an empty string, the UI is not refreshed.

### ISSUE THREAD

**Issue by actboy168** [Microsoft/vscode#63416]
Issue Type: <b>Bug</b>

https://github.com/Microsoft/vscode-debugadapter-node/blob/master/debugProtocol.json#L169-L172

The UI will continue to display the last value.

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:46:32.773Z)
OS version: Windows_NT ia32 10.0.17134

**Comment by weinand** [comment]
Please provide steps for how to reproduce.

**Comment by actboy168** [comment]
1. DA send 
```json
{"seq":1,"body":{"threadId":1,"reason":"exception","text":"This is a text."},"event":"stopped","type":"event"}
```
2. You can see "This is a text." on the UI.
3. continue
4. DA send 
```json
{"seq":2,"body":{"threadId":1,"reason":"breakpoint"},"event":"stopped","type":"event"}
```
5. You can still see "This is a text." on the UI.

**Comment by weinand** [comment]
@isidorn a "continue" must clear all state of a previous stopped event.

**Comment by isidorn** [comment]
@actboy168 thanks for the repro steps. Please try out tomorrow's insiders and let me know if the issue is fixed for you

**Comment by actboy168** [comment]
It has been fixed. But now when there is no text, the UI will display 'undefined', I think it would be better not to display it.

**Comment by isidorn** [comment]
@actboy168 thanks for letting us know. Please try it out in tomorrows insiders and let us know if the issue is fixed.
