### ISSUE TITLE
move function in Explorer like Package Explorer in Eclipse

### ISSUE THREAD

**Issue by LOGANLEEE** [Microsoft/vscode#63419]
![screen shot 2018-11-19 at 17 44 31](https://user-images.githubusercontent.com/26853553/48695541-c6041680-ec22-11e8-94c2-2298bd4e078a.png)

when i tried to dev spring boot app with vscode.

searching package is very difficult cuz i can't slide explorer view to right.

which mean is i have to expand that view like underneath 
![screen shot 2018-11-19 at 17 45 50](https://user-images.githubusercontent.com/26853553/48695632-f6e44b80-ec22-11e8-969e-d02f82d8eb39.png)

which mean is this way is not efficient at all.

is there any solution for it?

Thank you.

**Comment by isidorn** [comment]
Set this in your settings
`workbench.tree.horizontalScrolling: true`
It has performance degredations fyi
