### ISSUE TITLE
Chrome Debugger doesn't hit typescript in angular project

### ISSUE THREAD

**Issue by blfuentes** [Microsoft/vscode#63417]
- VSCode Version: 1.29.1
- OS Version: Windows 10 Enterprise 1809
- Debugger for Chrome extension 4.11.1
- Chrome 72.0.3610.2
- Angular 7.0.6
- Typescript 3.1.6
- Node 11.2.0

Steps to Reproduce:

1. Create new Angular project ' ng new my-app'
2. Start VS Code 'code .'
3. Set some breakpoints, for example in app.component.ts
4. Create launch debug setting

        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:4200",
            "webRoot": "${workspaceFolder}"

        }
5. Start the App 'ng serve'
6. Start the debug launcher
7. Breakpoints are not hit unless you set a breakpoint directly in the inspect code from Chrome under 'Sources->webpack://->.->src->app->app.ocmponent.ts->
8. Refresh and the breakpoint is hit by chrome and VS code

Does this issue occur when all extensions are disabled?: Debugger for Chrome is needed.
![vs_code_breakpoint_error](https://user-images.githubusercontent.com/5121778/48695287-122d6780-ebdf-11e8-8700-80e901a36124.png)

**Comment by blfuentes** [comment]
I found this issue

[https://github.com/Microsoft/vscode/issues/46905](url)

And modified the launch.json settings so the webroot looks like '"webRoot": "${workspaceFolder}/my-app"'

It seems that way the breakpoints are hit. I will test with a bigger project where the src folder structure is quite different.

**Comment by roblourens** [comment]
This seems to work for me with a fresh ng project. Let me know if there's still an issue and we can collect some more info.
