### ISSUE TITLE
The type of the variable in an or expression is incorrect

### ISSUE THREAD

**Issue by HankXu** [Microsoft/vscode#63422]
Issue Type: <b>Bug</b>

Steps: 
- Create a ts file;
- Add example code: 
```typescript
class Demo {
    test(param: string = 'param') {
        const variable: number = 0;
        if (param !== 'test1' || param !== 'test2') return;

        if (variable !== 0 || variable !== 12) return;
    }
}
```
- Put cursor on the "param" (or "variable") after "|| "

Result:

 - the popup appears, and the type of "param" (or "variable") is "test1"(or "0")

![image](https://raw.githubusercontent.com/HankXu/TryOnce/master/showBug.gif)

Expected:

the type of "param" (or "variable") is "string"(or "number")

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.96GB (1.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>
<summary>Extensions: none</summary>

**Comment by roblourens** [comment]
I think this is correct. The second part of the `||` after `!== 0` will only be evaluated when that check doesn't pass, when `variable === 0`

**Comment by mjbvz** [comment]
Yes it seems like the type narrowing is correct here
