### ISSUE TITLE
Bad whitespace wrap in git commit box

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#6342]
1. Git commit box - notice that the word wrapping is broken
2. I think somebody changed the white-space property

![screen shot 2016-05-13 at 12 25 08](https://cloud.githubusercontent.com/assets/1926584/15245272/ca817b96-1905-11e6-8cbf-5b466744f982.png)

**Comment by joaomoreno** [comment]
Nah, this is just the place holder text. It doesn't repro once you start typing. Someone files this one every 3 months.
