### ISSUE TITLE
REPL: reveal auto-expanded objects

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#6343]
- VSCode Version: alpha

Steps to Reproduce:
- start debugging
- fill the debug console so that a new entered expression appears at the bottom of the REPL
- type 'process'

Observe:
process is auto expanded but not revealed. This will make the user try to expand the object which in fact will make it collapse.

I suggest to reveal the auto expanded object at the top of the debug console.

**Comment by isidorn** [comment]
May to investigate
