### ISSUE TITLE
adopt new DAP attribute "runInTerminal.shellProcessId"

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#63434]
adopt the new DAP attribute "runInTerminal.shellProcessId" in VS Code.

Corresponding DAP feature request: https://github.com/Microsoft/debug-adapter-protocol/issues/12

**Comment by gjsjohnmurray** [comment]
Using today's Insiders I confirmed that I get the new shellProcessId attribute. But I also found that the first RunInTerminalRequest that was issued after startup consistently gave a RunInTerminalResponse with "success":false and "message":"terminal shell timeout". Perhaps my environment (Windows 10 x64, and debugging an extension) is too slow, but maybe the 1-second timeout hardcoded as part of https://github.com/Microsoft/vscode/commit/e40df5770d55ba93b1e1f7524ae27d9e70a9dc11 needs to be longer.

**Comment by weinand** [comment]
Thanks for letting me know. I'll increase the timeout. Coming from macOS I was obviously too optimistic in my guess...

**Comment by weinand** [comment]
Increased timeout to 5 secs.

**Comment by gjsjohnmurray** [comment]
That's resolved it for me. Thanks.

**Comment by weinand** [comment]
@gjsjohnmurray thanks for verifying. Added verified label.
