### ISSUE TITLE
Terminal at start visual issue

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#63435]
When terminal is opened on vscode start:
![image](https://user-images.githubusercontent.com/736697/48717069-7c272a80-ec3a-11e8-85a8-fc7a7e06eefe.png)

if I type something:
![image](https://user-images.githubusercontent.com/736697/48717124-9bbe5300-ec3a-11e8-87d4-54b63689ea69.png)

After I press enter:
![image](https://user-images.githubusercontent.com/736697/48717152-a547bb00-ec3a-11e8-8148-0c70f92de06a.png)

Also when new terminal is opened, the cursor is not on the command line:

![image](https://user-images.githubusercontent.com/736697/48717229-c9a39780-ec3a-11e8-85fe-db241cd6950e.png)

VSCode version 1.29, Window 10 (exact version is on the screen)

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/43169
