### ISSUE TITLE
Window freeze

### ISSUE THREAD

**Issue by StepanViliura** [Microsoft/vscode#63432]
Issue Type: <b>Bug</b>

Visual Studio Code stop working every few minutes with pop up that window does not respond. Should all time reopen the app

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:47:15.448Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4610M CPU @ 3.00GHz (4 x 2993)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (1.87GB free)|
|Process Argv|--folder-uri file:///d%3A/Projects/ATS|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
QML|bbe|1.0.0
jshint|dba|0.10.20
vscode-eslint|dba|1.7.0
compareit|in4|0.0.2
vscode-clang|mit|0.2.3
python|ms-|2018.10.1
cpptools|ms-|0.20.1
tcrunner|van|0.0.1

</details>

**Comment by StepanViliura** [comment]
Have reproduced in different devices

**Comment by monkeygroover** [comment]
I'm seeing something that sounds similar, Ubuntu18.04

Version: 1.29.1
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:07:43.495Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by lwxbr** [comment]
Same issue here, It freezes when I use **PHP XDebug extension**.

**Comment by roblourens** [comment]
@StepanViliura we fixed an issue related to this in 1.29.1, please upgrade to that. @monkeygroover please open a new issue but it sounds like maybe it's just slow because your CPU is busy. @lwxbr also please open a new issue with as many details as possible.

**Comment by lwxbr** [comment]
@roblourens, thanks for feedback. I will keep watching the problem, it's intermittent. When I achieve to reproduce the problem with clarity, I create a issue to show more details. Is there VSCode a way to watch in logs fatal errors like these?
