### ISSUE TITLE
Process explorer not working

### ISSUE THREAD

**Issue by lgraubner** [Microsoft/vscode#63437]
Issue Type: <b>Bug</b>

The process explorer is empty. `code --status` also doesn't show any running processes.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 18, 13|
|Memory (System)|16.00GB (1.81GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
html-css-class-completion|Zig|1.17.1
vscode-intelephense-client|bme|0.8.8
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.7.0
vscode-phpmd|eco|1.1.0
EditorConfig|Edi|0.12.5
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.7.2
flow-for-vscode|flo|0.8.5
vscode-styled-components|jpo|0.0.25
vscode-colorize|kam|0.8.1
node-module-intellisense|lei|1.5.0
vscode-language-babel|mgm|0.0.21
vscode-language-pack-de|MS-|1.29.2
code-settings-sync|Sha|3.2.0
glean|wix|4.2.3
vscode-import-cost|wix|2.9.0

(1 theme extensions excluded)

</details>

**Comment by RMacfarlane** [comment]
@lgraubner So `code --status` prints version and workspace information, but not process information? Or does it print nothing at all?

**Comment by RMacfarlane** [comment]
What's the output of running `/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command= | grep Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron`?

**Comment by lgraubner** [comment]
```
$ /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command= | grep Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron
 6763     1   2,8  0,6 /Applications/Visual Studio Code.app/Contents/MacOS/Electron .
 7181  6220   0,0  0,0 grep Applications/Visual Studio Code.app/Contents/MacOS/Electron
```

**Comment by weinand** [comment]
verified with German locale.
