### ISSUE TITLE
how to support smarty syntax???

### ISSUE THREAD

**Issue by sdhexu** [Microsoft/vscode#63430]
HTML CODE:
```code=html
{%foreach $users %}
{%if $users eq 'Admin'%}
<div> some text....</div>
{%else%}
<span> some text...</span>
<%/if%}
```
HOW TO SUPPORT {%.....%} ？？？

**Comment by oneslash** [comment]
Hi, you have another issue created with the same topic, please close one of them.


https://github.com/Microsoft/vscode/issues/63429

**Comment by oneslash** [comment]
I have found this extension, https://marketplace.visualstudio.com/items?itemName=imperez.smarty#overview please try it
