### ISSUE TITLE
Not Launching

### ISSUE THREAD

**Issue by VarunSaiTeja** [Microsoft/vscode#63439]
- VSCode Version:1.29.1 (User SetUp)
- OS Version: Windows 1809

Steps to Reproduce:
 typed code in cmd
gives following output without launching

am Command Prompt Microsoft Windows [Version 10.0.17763.134] (c) 2018 Microsoft Corporation. All rights reserved. 
C:\Users\Varun>code 
dns.js:246
           this._handle = new ChannelWrap(); 

Error: EFILE
at new Resolver (dns.js:246:20)
at dns.js:377:25
at dns.js:431:3
at NativeModule.compile (bootstrap_node.js:606:7)
at NativeModule.require (bootstrap_node.js:550:18)
at net.js:45:13 at net.js:1730:3
at NativeModule.compile (bootstrap_node.js:606:7)
at NativeModule.require (bootstrap_node.js:550:18)
at internal/child_process.js:6:13 
C:\Users\Varun>

**Comment by roblourens** [comment]
Can you try `code --verbose`?

**Comment by VarunSaiTeja** [comment]
I tried 
code .
from then its launching perfectly without any problem from desktop shortcut too

**Comment by VarunSaiTeja** [comment]
Yeah
After running 
code .
No problem with vs code
Launching directly from desktop shortcut.

Whenever I face this problem I am doing this thing, helping me alot

Don't know why it's not launching directly from desktop shortcut sometimes

**Comment by roblourens** [comment]
I don't really understand the problem, can you explain it some more? What happens when you try to use the desktop shortcut?

**Comment by VarunSaiTeja** [comment]
VSCode does not launch
just mouse cursor rotates in busy style few milli seconds

**Comment by roblourens** [comment]
Can you try reinstalling?
