### ISSUE TITLE
Go to definition not working

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#63448]
Issue Type: <b>Bug</b>

**repo**
1. Try running `go to definition` in a js/ts file

**Bug**
Nothing happens. The command may also not show up in the command palette 

VS Code version: Code - Insiders 1.30.0-insider (24b0f75b1e33b88f30f2ed9d5b17ca60062c270b, 2018-11-16T06:22:01.663Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.27GB free)|
|Process Argv|-psn_0_12327873|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by mjbvz** [comment]
@jrieken Reopening to track changing the fix in ebe9ea85a0a0bb087dccc98949542605dfc51f6f to use a better id

**Comment by mjbvz** [comment]
Note that my comment on the commit is has a copy paste error; both commands were registered with the id `editor.action.goToDeclaration`. I introduced `editor.action.goToRealDeclaration` as a temporary workaround

**Comment by jrieken** [comment]
Thanks @mjbvz. It's tricky because the go-to-definition command uses a bogus id to begin with...

**Comment by burakcan** [comment]
This is happening on latest non-insiders version, too. 
Version 1.29.1 (1.29.1), MacOs
