### ISSUE TITLE
Can't code fold const

### ISSUE THREAD

**Issue by corysimmons** [Microsoft/vscode#63446]
I can fold everything within a const, but not the const itself...

![image](https://user-images.githubusercontent.com/224636/48725098-1e262300-ebf9-11e8-8b9b-bb9fa2dd5c39.png)

![image](https://user-images.githubusercontent.com/224636/48725118-2c743f00-ebf9-11e8-8e63-7225ac6d3c54.png)

**Comment by mjbvz** [comment]
Tracked by https://github.com/Microsoft/TypeScript/issues/23382
