### ISSUE TITLE
Do Not Reopen Window still reopens windows

### ISSUE THREAD

**Issue by fulldecent** [Microsoft/vscode#63447]
Issue Type: <b>Bug</b>

TEST CASE:

1. Set preference "Restore windows" to "none"
1. Command line `code somefolder`
2. Start editing `afile` and save
3. Close the window
4. Command line `code somefolder` 

EXPECTED: 

No editors are open

ACTUAL:

Editor for `afile` is open

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv|team.pacificmedicaltraining.com|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by roblourens** [comment]
That controls which windows are reopened, not which editors are reopened. If an editor was open before, it gets restored when the same folder is opened.

**Comment by fulldecent** [comment]
I believe the expected behavior is well described in the issue.
