### ISSUE TITLE
Syntax highlight color of function without parameters

### ISSUE THREAD

**Issue by mlostekk** [Microsoft/vscode#63443]
- VSCode Version: Version 1.29.1 (1.29.1)
- OS Version: Mac OS 10.14.1 (18B75)

Steps to Reproduce:

1. Simply paste the code given below
2. Observe the different behavior of the syntax coloring
3. I would expect the color of `trackError` function to be the same as the other functions inside that object

![bildschirmfoto 2018-11-19 um 17 19 20](https://user-images.githubusercontent.com/10534316/48720193-7ec85680-ec1f-11e8-8fb6-3e66f303ded8.jpg)

```
/*******************************************************************************
 * Tracker endpoint implementation for Mixpanel
 */
export const MixpanelEndpoint: EndpointInterface = {

  /*******************************************************************************
   */
  identifyUser: (userId: string) => {
  },

  /*******************************************************************************
   */
  setUserProperties: (property: string, value: string, once: boolean) => {
  },

  /*******************************************************************************
   */
  incrementCounter: (property: string, value: number) => {
  },

  /*******************************************************************************
   */
  trackEvent: (event: EventType, payload: EventData) => {
  },

  /*******************************************************************************
   */
  trackError: (/* error: ErrorType, data: ErrorData */) => { },
};

```

Does this issue occur when all extensions are disabled?: Yes/No

**How to fix this?**

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/Microsoft/TypeScript-TmLanguage/issues/686 to track this issue upstream
