### ISSUE TITLE
Console doesn't spawn when debugging

### ISSUE THREAD

**Issue by dbrocher** [Microsoft/vscode#63450]
Issue Type: <b>Bug</b>

Any debugging.  No console spawns while debugging.  I saw a comment on github stating: "You are probably missing a component called lldb-launcher" but there is no indications on how to fix.  My launch.json looks like this:

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [

        {
            "name": "(lldb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/test",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "lldb"
        }
    ]
}

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|-psn_0_2187798|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
cpptools|ms-|0.20.1
html5-boilerplate|sid|1.0.3

</details>

**Comment by Blurbs** [comment]
I'm having same issue. Just getting the progress indicator under green arrow and nothing happens. Stop button on debug doesn't work either, and debug console still says "please start a debug session to evaluate". Debugging doesn't work on any of my projects all of a sudden.
launch.json:

{
    // Use IntelliSense to find out which attributes exist for C# debugging
    // Use hover for the description of the existing attributes
    // For further information visit https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch PAS API (.NET Core)",
            "type": "coreclr",
            "request": "launch",
            "program": "${workspaceFolder}/pas-api/bin/Debug/netcoreapp2.1/PAS.API.dll",
            "args": [],
            "cwd": "${workspaceFolder}/pas-api",
            "stopAtEntry": false,
            "internalConsoleOptions": "openOnSessionStart",
            "launchBrowser": {
                "enabled": false,
                "args": "${auto-detect-url}",
                "windows": {
                    "command": "cmd.exe",
                    "args": "/C start ${auto-detect-url}"
                },
                "osx": {
                    "command": "open"
                },
                "linux": {
                    "command": "xdg-open"
                }
            },
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development",
                "ASPNETCORE_URLS": "http://localhost:80;https://localhost:443"
            }
        }
    ]
}

VS Code version: 1.29.1
Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.403\

**Comment by Blurbs** [comment]
@dbrocher Just resolved this for myself. Turns out my C# extension was bugged and I had to reinstall it. Hope that helps.

**Comment by roblourens** [comment]
@dbrocher it looks like you're trying to debug with the cpp extension. Please file this issue on their github repo.
