### ISSUE TITLE
Please return the Toggle Panel Position icon to the visible terminal menu.

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#63459]
Came in through code.visualstudio.com doc feedback release notes verbatim:

"Please return the Toggle Panel Position icon to the visible terminal menu.  It was one of the most useful one-click configuration options around.  Frankly, Id take it over split screen; moreover, Ive never felt the terminal menu lacked space for icons."

**Comment by ahouse101** [comment]
I can't understand why this change was made in the first place. I frequently change the panel location, as the best place for it depends on the aspect ratio of the VSCode window + the arrangement of editor tabs/splits, which changes as I move the window around and work on code. Removing the button has created a constant pain point when using VSCode. I used that button more than any other button in the bottom panel.

**Comment by SharakPL** [comment]
I also change my terminal placement all the time. Different workspaces require different settings. Sometimes I have VSCode on right half of the screen with terminal on the bottom, but when I work with few other applications at the same time I like to have VSCode on the bottom with terminal on the right. 

**Please bring back the Toggle Panel Position icon**

I'm sure a lot of users would like that too, but they're currently more occupied with constant Extension Host chrashing 😞

**Comment by ytimenkov** [comment]
Another use-case is different displays. One can think about external/internal with very different aspect ratio, where one is wide so it makes sense to have terminal on the right and another is more square-ish where having terminal on the side leaves no space for editor.

**Comment by isidorn** [comment]
Dup of #63034
Please assign a keybinding to it and change it all the time quickly and conventietly
Here's a gif of me doing it

![keybinding](https://user-images.githubusercontent.com/1926584/48764387-cbf40900-ecaf-11e8-9d30-de5f8380aa28.gif)

**Comment by igoticecream** [comment]
Why we can't have nice things? bring back the button please
