### ISSUE TITLE
terminal.integrated.scrollback unlimited history

### ISSUE THREAD

**Issue by flddr** [Microsoft/vscode#63452]
#14320 is locked

Please, why is that limited to 1000 Lines? 😕 

I tried `terminal.integrated.scrollback` `-1`, `0` and above - not possible?

**Comment by Tyriar** [comment]
We do not support "unlimited" history, you can set scrollback beyond 1000, pick a large number that works for you (note the terminal will eagerly allocate memory for the buffer's scrollback).
