### ISSUE TITLE
Fix strict null errors in 'vs/workbench/parts/tasks/'

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#63453]
Part of #60565

I see a few strict null eligible files under `vs/workbench/parts/tasks/`:

- [x] `"vs/workbench/parts/tasks/electron-browser/jsonSchema_v1.ts"`
- [x] `"vs/workbench/parts/tasks/electron-browser/jsonSchema_v2.ts"`
- [x] `"vs/workbench/parts/tasks/electron-browser/terminalTaskSystem.ts"`
- [x] `"vs/workbench/parts/tasks/node/processTaskSystem.ts"`
- [x] `"vs/workbench/parts/tasks/node/taskConfiguration.ts"`

**Steps**

1. Add file  to the `files` section of `src/tsconfig.strictNullChecks.json` 
1. Run `yarn strict-null-check -- --watch`
1. Fix strict null check compiler errors
1. Verify normal build still works

**Comment by mjbvz** [comment]
Removing @aeschli  and assigning to @dbaeumer and @alexr00 since the jsonSchema files are owned by tasks, not by our json support

**Comment by alexr00** [comment]
Thank you, I'll take this one.
