### ISSUE TITLE
Use the web packed version of vscode-emmet-helper

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode#63463]
Once https://github.com/Microsoft/vscode-emmet-helper/issues/27 is completed, use the web packed version of vscode-emmet-helper in the Emmet extension.

This can help us in avoiding the case where we have to exclude vscode-emmet-helper from the bundling done to the Emmet extension.

Note: If we plan to remove the lazy loading of vscode-emmet-helper, check the start up times before making the call

**Comment by rzhao271** [comment]
Closing this issue because it might already have been handled by https://github.com/microsoft/vscode-emmet-helper/commit/47be7ee4fbb4bdee05a39606c892601e050119eb

**Comment by aeschli** [comment]
@rzhao271 I just stumbled over this as emmet is one of the extensions with the most files. It is webpacked, but excludes `vscode-emmet-helper`.

I gave it a quick try and removed `vscode-emmet-helper` from the exclusion list: https://github.com/microsoft/vscode/blob/ea006a72c031bb1009f567dabfa678f19a82c7b2/extensions/emmet/extension.webpack.config.js#L23
and this works. I don't know the history and don't know emmet very well, but going through the code I couldn't figure out whats the reason for the exclusion. Also for the web version we don't have that.

I made a build and tested it a bit and don't see any problems.

I suggest we give it a try? We can test it in more depth next week.

**Comment by aeschli** [comment]
see https://github.com/microsoft/vscode/pull/109257

**Comment by rzhao271** [comment]
So you're saying that Emmet extension is currently, webpacked but not the vscode-emmet-helper dependency?
Maybe it's a relic from back when expand-full.js had to be under UMD for some reason.

I'm not very familiar with webpack though, adding @rebornix to the PR for a second look

**Comment by rzhao271** [comment]
\closedWith 2f22788

**Comment by aeschli** [comment]
Verified that there's no `extensions/emmet/node_modules` in 
Version: 1.51.0-insider
Commit: 2ee8b8c645ec8ab54304bacae7aa979c1d9c647a
Date: 2020-10-29T05:47:02.014Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.3.0-64-generic
