### ISSUE TITLE
`vsce publish` doesn't fully support semver...

### ISSUE THREAD

**Issue by busticated** [Microsoft/vscode#63461]
hi there :wave:

i just tried to publish my extension for the first time and ran into the following:

```
Error: The version string '1.0.0-alpha.4' doesn't conform to the requirements for a version. It must be one to four numbers in the range 0 to 2147483647, with each number seperated by a period. It must contain at least one non-zero number.
```

which is odd since i was under the impression that vscode extensions used semver.

from the docs:

> You can also specify a complete SemVer compatible version on the command line

([source](https://code.visualstudio.com/docs/extensions/publish-extension#_autoincrementing-the-extension-version))

using [node-semver](https://github.com/npm/node-semver), i'm able to verify my version string is valid:

```javascript
semver = require('semver');
semver.valid('1.0.0-alpha.4') // = '1.0.0-alpha.4'
semver.valid('1.0.0.4') // = null (iow, invalid)
semver.valid('1') // = null (iow, invalid)
```

([spec](https://semver.org/#spec-item-9))

here's the command i ran:

`vsce publish 1.0.0-alpha.4`

vsce version: 1.53.0
OS Version: macOS v10.13.6 (high sierra)

**Comment by busticated** [comment]
ah, this looks related 👉 https://github.com/Microsoft/vscode-vsce/issues/148

**Comment by roblourens** [comment]
Yes that's the issue tracking this
