### ISSUE TITLE
Why there is no default csharp

### ISSUE THREAD

**Issue by liuww111** [Microsoft/vscode#6346]
I found csharp USES vs code is not the default, need to install the extension, very inconvenient.
Suggestions and any other language in vscode internal integration

**Comment by chrisdias** [comment]
Hi @liuww111, 

VS Code is written in TypeScript/JavaScript/HTML so "out of the box" we only include deep support for these languages. For any other language you must install and extension to get the support. We do this to allow languages to ship on their own schedule and to keep the core VS Code editor download as small as possible.

We are constantly trying to improve the experience for how you discover and install extensions into VS Code (see [here](https://code.visualstudio.com/updates/vFebruary#_workbench) and [here](https://code.visualstudio.com/updates/vMarch#_workbench)), so hopefully you will find this less inconvenient over time. For now, please see the [C# documentation](https://code.visualstudio.com/Docs/languages/csharp) on how to install the extension and what types of projects are supported.  

Thank you,
Chris
