### ISSUE TITLE
slow start

### ISSUE THREAD

**Issue by jixuni** [Microsoft/vscode#63472]
- VSCode Version: <code>Code 1.29.0  (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:42:27.562Z)</code>
- OS Version: <code>Linux x64 4.18.0-11-generic </code>
- CPUs: <code>Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4000)</code>
- Memory(System): <code>15.60 GB(9.55GB free) </code>
- Memory(Process): <code>217.17 MB working set(236.45MB peak, 129.63MB private, 87.55MB shared) </code>
- Load(avg): <code>1, 1, 1 </code>
- VM: <code>0% </code>
- Initial Startup: <code>yes </code>
- Screen Reader: <code>no </code>
- Empty Workspace: <code>no </code>
- Timings:

| Component | Task | Duration(ms) | Info |
| ---| ---| ---| ---|  
| [main]| start => app.isReady| 13855| true|
| [main]| nls:start => nls:end| 0| true|
| [main]| app.isReady => window.loadUrl()| 222| true|
| [main->renderer]| window.loadUrl() => begin to require(workbench.main.js)| 197| NewWindow|
| [renderer]| require(workbench.main.js)| 729| cached data: NO|
| [renderer]| require workspace storage| 2| |
| [renderer]| require & init workspace storage| 10| |
| [renderer]| register extensions & spawn extension host| 142| |
| [renderer]| restore viewlet| 22| workbench.view.explorer|
| [renderer]| restore panel| 0| |
| [renderer]| restore editors| 0| 1: workbench.editors.welcomePageInput|
| [renderer]| overall workbench load| 115| |
| [main->renderer]| workbench ready| 15147| |
| [renderer]| extensions registered| 15364| |
 
---

:warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`prof-20fe.main.cpuprofile.txt`

**Comment by cleidigh** [comment]
@jixuni 
Can download and check the latest revision 1.29.1
Not necessarily a definitive solution, but it is best to make sure you are using and testing with the latest bug fixes.

**Comment by jixuni** [comment]
Thank you, that fix the problem. It went from 5 second load time from my SSD to nearly instant.I had originally installed 1.29 from the software center. I remove it and downloaded the latest .deb off the website.

**Comment by cleidigh** [comment]
@jixuni 
Excellent !
