### ISSUE TITLE
The "Ctrl+P" and then "ext install csharp" is not working...

### ISSUE THREAD

**Issue by liuww111** [Microsoft/vscode#6347]
- VSCode Version:1.1.0
- OS Version:windows7

Steps to Reproduce:

1. install code
2. run "ext install csharp" 
3.The progress bar is not installed
4.Long time no response, I do not know whether the installation is successful
5.Can update next time try to integrate csharp？？？？？？？

**Comment by isidorn** [comment]
This is because the installation takes quite some time and there is no progress.

**Comment by joaomoreno** [comment]
Some people seem to not be able to install this one... strange.

**Comment by joaomoreno** [comment]
@liuww111 Is this still an issue for you? I'll reopen if so.
