### ISSUE TITLE
Git bash not working well

### ISSUE THREAD

**Issue by aimergenge** [Microsoft/vscode#63479]
I use git bash as my integrated terminal in vscode, but it sometimes doesn't work well. But when I use a git bash as a external shell, it works normally.

What it looks like now:
![image](https://user-images.githubusercontent.com/13799160/48759462-1a200100-ecde-11e8-8b52-72bbb2c71fe9.png)
What it should look like:
![image](https://user-images.githubusercontent.com/13799160/48759467-1f7d4b80-ecde-11e8-93d8-d6d1608cb64b.png)

However, I can scroll to top by hand to see the green "DONE" label...
It seems like there is always a extra blank line which push the log info up a little...

Certainly, when I use wsl or powershell as my integrated terminal, this works well:
![image](https://user-images.githubusercontent.com/13799160/48759734-088b2900-ecdf-11e8-911f-20b6e9816cc5.png)

- VSCode Version:1.29.1
- OS Version:Windows10 1803 17134.407

Steps to Reproduce:

1. use git bash as integrated terminal
2. have @vue/cli installed
3. run `npm run serve` or `yarn serve`

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
