### ISSUE TITLE
code can not start in ubuntu 14.04/16.04 via vnc

### ISSUE THREAD

**Issue by AnboSkyWalker** [Microsoft/vscode#63474]
bash -x /usr/share/code/bin/code
++ id -u
+ '[' 1001 = 0 ']'
+ '[' '!' -L /usr/share/code/bin/code ']'
++ dirname /usr/share/code/bin/code
+ VSCODE_PATH=/usr/share/code/bin/..
+ ELECTRON=/usr/share/code/bin/../code
+ CLI=/usr/share/code/bin/../resources/app/out/cli.js
+ ELECTRON_RUN_AS_NODE=1
+ /usr/share/code/bin/../code /usr/share/code/bin/../resources/app/out/cli.js

it stop at cli.js and has no response

**Comment by cleidigh** [comment]
@AnboSkyWalker 
Can you provide more information:
- code version, extensions, more clarity on the situation causing the problem
- the built-in issue reporter will gather the information for you

**Comment by AnboSkyWalker** [comment]
@cleidigh 
I tried both 1.28 and 1.29.1.
Both code and code --verbose gives no output
I downloaded the deb package from https://code.visualstudio.com/Download
I don't know how to use code built-in issue reporter to gather the information when code can not start.

Any log or other informations can I collected manually?
