### ISSUE TITLE
Search input hides away behind search title

### ISSUE THREAD

**Issue by umnovI** [Microsoft/vscode#63488]
Issue Type: <b>Bug</b>

1. open worksapse
2. use global search
3. select found file
Input will be behind search title
![screenshot_1](https://user-images.githubusercontent.com/30232564/48766789-4596f180-ecc6-11e8-910c-9423b219d970.jpg)

After I turned off extensions and did the same steps search input is just disappeared.
![screenshot_2](https://user-images.githubusercontent.com/30232564/48766701-16808000-ecc6-11e8-864d-16db1ff787b4.jpg)

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:07:43.495Z)
OS version: Linux x64 4.4.0-139-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 2777)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|7.70GB (0.55GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-apache|mrm|1.1.1
vscode-language-pack-ru|MS-|1.29.2
sublime-keybindings|ms-|4.0.0
vscode-icons|rob|7.28.0
code-settings-sync|Sha|3.2.0
markdown-all-in-one|yzh|1.7.0

</details>

**Comment by roblourens** [comment]
I've never seen that before. Does that happen every time? Are there results? Can you show a screenshot of the whole window?

**Comment by umnovI** [comment]
>Does that happen every time?

Yes

I've changed locale to eng and I cannot repro it, but if locale in rus it happens all the time

<details> <summary>RU:</summary>

 ![screenshot at 2018-11-21 10 27 25](https://user-images.githubusercontent.com/30232564/48825327-1ccf3480-ed78-11e8-9f44-8762e00dcbbb.png)
![screenshot at 2018-11-21 10 17 12](https://user-images.githubusercontent.com/30232564/48825328-1ccf3480-ed78-11e8-8a0c-89a3f9ff0fa5.png)

</details>

<details> <summary>EN:</summary>

![screenshot at 2018-11-21 10 30 35](https://user-images.githubusercontent.com/30232564/48825479-8b13f700-ed78-11e8-9544-ee8a8a86080d.png)

</details>
