### ISSUE TITLE
activeDebugConsole is a no-op when debugging is not active

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#63489]
`vscode.debug.activeDebugConsole.append('hello')`
Is a no-op if debugging is not active. It only appends output is there is a debug session.

This comes from the fact that we are now supporting multiple debug consoles.

A user actually hit this, but it seems he was misusing this and was happy to switch to the output channel - which imho is the right thing to do.
https://github.com/Microsoft/vscode/issues/63114

We should at least change documentation to make it clearer to the user.

**Comment by weinand** [comment]
I've added the sentence "If no debug session is active, all output sent to the debug console is lost." to the `activeDebugConsole` comment in vscode.d.ts.
