### ISSUE TITLE
Дико логает

### ISSUE THREAD

**Issue by lovik1468** [Microsoft/vscode#63484]
Issue Type: <b>Bug</b>

http://joxi.ru/vAWzMoVi1xojx2 Невозможно долго грузится 
Тем самым пока не загрузится не возможно работать. Все тормазит и лагает. 
Это после последнего обновления 

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz (8 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|7.87GB (1.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
pug|ama|1.0.1
cypress-snippets|and|1.2.0
ACF-Snippet|ant|1.9.0
vscode-intelephense-client|bme|0.8.8
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
woocommerce|cla|1.0.0
wpcs-whitelist-flags|cla|1.0.0
vscode-eslint|dba|1.7.0
jquerysnippets|don|0.0.1
es7-react-js-snippets|dsz|1.9.0
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.40
prettier-vscode|esb|1.7.2
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vue-snippets-js-html-pug-razor|heb|0.0.3
vue-snippets|hol|0.1.9
rest-client|hum|0.20.3
phpcs|ika|1.0.5
webpack|jer|2.1.0
wordpress-vscode-extensionpack|jpa|1.2.0
react-native-snippet|jun|0.5.0
vscode-gist|ken|1.2.1
vscode-language-pack-ru|MS-|1.29.2
PowerShell|ms-|1.9.0
debugger-for-chrome|msj|4.11.1
php-docblocker|nei|1.6.0
vetur|oct|0.13.0
live-sass|rit|3.0.0
LiveServer|rit|5.2.0
vscode-icons|rob|7.28.0
sass-indented|rob|1.4.9
ftp-kr|rua|1.3.16
vue-vscode-snippets|sdr|1.3.0
code-settings-sync|Sha|3.2.0
indenticator|Sir|0.6.0
js-jsx-snippets|sky|0.3.0
code-spell-checker|str|1.6.10
wordpress-snippet|tun|1.1.5
indent-one-space|use|0.2.3
bootstrap-3-snippets|wcw|0.1.0
vscode-import-cost|wix|2.9.0
wordpress-toolbox|wor|1.2.0
JavaScriptSnippets|xab|1.7.1
ReactSnippets|xab|2.2.1
html-css-class-completion|Zig|1.17.1

</details>

**Comment by lovik1468** [comment]
http://joxi.ru/vAWzMoVi1xojx2 Impossible to load for a long time
Thereby until it is loaded it is not possible to work. All the brakes and lags.
This is after the last update.

**Comment by alexr00** [comment]
Does this issue still occur when you disable all extensions?

**Comment by lovik1468** [comment]
No, when this process goes up to 100% everything works fine. But it is long and you have to wait a very long time * (

**Comment by lovik1468** [comment]
When this problem is resolved with the editor it’s impossible to work

**Comment by lovik1468** [comment]
Thanks found the problem on their own helped to disable the plugin. And everything works fine as before.

**Comment by alexr00** [comment]
Do you know which extension it was?

**Comment by lovik1468** [comment]
http://joxi.ru/p27a1ygUodw36r
It helped exactly until I started working with the SVG code, and here I’m going to insert the same problem and think about it for 30-60 seconds minimum. does not respond to pressing the tab and do not respond plugins such as KR-FTP ...

**Comment by lovik1468** [comment]
I’m probably going to try to roll back to a later version. Since I cannot continue to work on this one.
