### ISSUE TITLE
[regex] Invalid regular expression: (?<=)

### ISSUE THREAD

**Issue by ztytotoro** [Microsoft/vscode#63482]
Issue Type: <b>Bug</b>

Invalid group (?<=)  when search

VS Code version: Code - Insiders 1.30.0-insider (d37f7c158322b3b66e61721f196e7fa56c2c9ab0, 2018-11-20T06:19:01.190Z)
OS version: Windows_NT x64 10.0.18282

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz (8 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (3.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.10
gitignore|cod|0.6.0
gitlens|eam|8.5.6
tslint|eg2|1.0.40
beautify|Hoo|1.4.7
Ionide-fsharp|Ion|3.30.0
chat|kar|0.8.0
vscode-language-pack-zh-hans|MS-|1.29.2
vscode-kubernetes-tools|ms-|0.1.14
anaconda-extension-pack|ms-|1.0.1
python|ms-|2018.10.1
cpptools|ms-|0.20.1
csharp|ms-|1.17.1
Go|ms-|0.7.0
PowerShell|ms-|1.9.0
vs-keybindings|ms-|0.2.0
vsliveshare|ms-|0.3.954
vsliveshare-audio|ms-|0.1.39
vsliveshare-pack|ms-|0.2.2
debugger-for-chrome|msj|4.11.1
vetur|oct|0.13.0
vscode-docker|Pet|0.3.1
material-icon-theme|PKi|3.6.0
tslint-vue|pro|1.5.6
vscode-yaml|red|0.1.0
vscodeintellicode|Vis|1.0.6

(1 theme extensions excluded)

</details>

**Comment by alexr00** [comment]
Can you give an example of what you're using to search and what kind of output you're seeing?

**Comment by ztytotoro** [comment]
@alexr00 like: /(?<=})\n(?=[f|/]) and as expected it will match code like:
```js
function a() {
}//Insert lines below
function b() {
}
```
![wxworkcapture_15427056661553](https://user-images.githubusercontent.com/8148113/48764291-42adf800-ecea-11e8-8637-260f1af76725.png)

**Comment by IllusionMH** [comment]
Lookbehind isn't supported by VS Code until update to Electron v3.

From latest release notes:
> While PCRE2 supports many other features, we only support regex expressions that are still valid in JavaScript, because open editors are still searched using the editor's JavaScript-based search.
>
> If you are still missing lookbehind assertions, don't worry! That feature is just recently supported by JavaScript and should come to VS Code in a later Electron shell update.

**Comment by ztytotoro** [comment]
@IllusionMH thanks

**Comment by d4nyll** [comment]
**Feedback**: the help text in the settings tab suggests that lookbehinds are supported. I'd suggest it is rephrased to avoid such confusions until it is implemented.

![screenshot from 2018-12-04 14-54-18](https://user-images.githubusercontent.com/9997953/49450276-959caa80-f7d4-11e8-9166-bb13a45fb70f.png)

**Comment by roblourens** [comment]
Thanks @d4nyll, I meant lookahead. Fixed.
