### ISSUE TITLE
1

### ISSUE THREAD

**Issue by lalwaysy** [Microsoft/vscode#63485]
Issue Type: <b>Feature Request</b>

2

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:47:15.448Z)
OS version: Windows_NT x64 10.0.14393

**Comment by thecakeisalie25** [comment]
3

**Comment by alexr00** [comment]
There doesn't appear to be an issue here.
