### ISSUE TITLE
High CPU load on macOS Mojave

### ISSUE THREAD

**Issue by pelegb** [Microsoft/vscode#63481]
- VSCode Version: 1.29.1
- OS Version: 10.14.1

Steps to Reproduce:

1. Open VSCode
2. Open JS file

There seems to be bash process which VSCode is starting in endlessly with one of the following commands:
* bash /usr/local/Cellar/pyenv/1.2.8/libexec/pyenv-which npm
* bash /usr/local/Cellar/nodenv/1.1.2/libexec/nodenv-which npm
To clarify the process ends and then a new one runs with one of these commands.

Does this issue occur when all extensions are disabled?: Yes
Tried both code --disable-extensions and uninstalling all extensions and issue still occurs.
Reproduces in insiders build as well.

Thanks for your assistance.

**Comment by pelegb** [comment]
@alexr00 @roblourens  I don't think so as I'm on macOS Mojave and not Windows.

**Comment by ergenekonyigit** [comment]
same issue here.

- VSCode Version: 1.29.1
-  OS Version: 10.14.1

**Comment by alexr00** [comment]
Ah sorry about that! I should have paid better attention.

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!

**Comment by pelegb** [comment]
System Information:

CPUs | Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)
-- | --
GPU Status | 2d_canvas: enabledchecker_imaging: disabled_offflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: enabledrasterization: enabledvideo_decode: enabledvideo_encode: enabledwebgl: enabledwebgl2: enabled
Load (avg) | 4, 5, 5
Memory (System) | 16.00GB (1.79GB free)
Process Argv |  
Screen Reader | no
VM | 0%


Running processes:
CPU %	Mem MB	   PID	Process
   13	    82	  3596	code main
    2	    82	  3597	   gpu-process
    0	   229	  3598	   window (CompetitorDetails.js — studio-app)
    0	     0	  3882	     /bin/bash -l
    0	    82	  3891	     extensionHost
    0	   229	  4106	       electron_node tsserver.js 
    0	    82	  4159	         electron_node typingsInstaller.js typesMap.js 
    1	     0	  4222	           bash /usr/local/Cellar/pyenv/1.2.8/libexec/pyenv-exec npm install --ignore-scripts types-registry@latest
    0	     0	  6357	             bash /usr/local/Cellar/pyenv/1.2.8/libexec/pyenv-which npm
   87	     0	  6358	               bash /usr/local/Cellar/pyenv/1.2.8/libexec/pyenv-which npm
    0	    49	  5050	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=3891
    0	    49	  4034	     watcherService
    0	    82	  3907	   shared-process
    0	    66	  6326	   window (Issue Reporter)
    0	     0	  6359	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=

Workspace Metadata:
|  Window (CompetitorDetails.js — studio-app)
|    Folder (studio-app): 98 files
|      File types: js(56) svg(7) json(6) ttf(6) png(5) map(4) ico(2) html(2)
|                  css(2) production(1)
|      Conf files: jsconfig.json(1) package.json(1)
			

Extensions: none


I think I followed all the reporting guidelines.

**Comment by andrewtw** [comment]
This might not be the problem of VS code itself.

Here is my resource consumption (VS Code 1.29.1, 2 workspaces, per workspace opens 10 TS files with avg. 400 lines each) 

![image](https://user-images.githubusercontent.com/12085701/48788559-0ac4a600-ed26-11e8-9c3b-51cec9a11084.png)


Machine,

![image](https://user-images.githubusercontent.com/12085701/48788731-63943e80-ed26-11e8-854c-89b77bb52eec.png)

**Comment by pelegb** [comment]
@bpasero I have no extensions installed and I've run code --disable-extensions as well. It reproduces in both cases.

**Comment by bpasero** [comment]
@pelegb any clue what this is `/usr/local/Cellar/pyenv/1.2.8/libexec/pyenv-which npm` ?

**Comment by pelegb** [comment]
This is tool to manage python versions:
https://github.com/pyenv/pyenv

**Comment by bpasero** [comment]
@pelegb is it possible that something triggers this when you open VSCode? Is it only in Python workspaces?

**Comment by pelegb** [comment]
As you can see I'm actually opening a JS file. What triggers it is "electron_node typingsInstaller.js typesMap.js" which is trying to find npm in order to install the types-registry@latest package.
How does VSCode find my node environment? Is there something environment variable or other way to configure this? Has this changed in the latest version as I've been using pyenv to manage my environment for several  years now.

**Comment by bpasero** [comment]
Seems to be triggered by TypeScript language service then.

**Comment by pelegb** [comment]
@mjbvz Any directions on how to check what is not configured in the node environment.

Thanks

**Comment by mjbvz** [comment]
@pelegb You can set `typescript.npm` to point to your npm install location as described here: https://code.visualstudio.com/Docs/languages/javascript#_fixing-npm-not-installed-warning-for-automatic-type-acquisition

**Comment by pelegb** [comment]
@mjbvz Thanks for the pointer. Solved.
