### ISSUE TITLE
Integrated terminal gitbash chinese input bug?

### ISSUE THREAD

**Issue by dtboy1995** [microsoft/vscode#63483]
- VSCode Version: 1.29.1
- OS Version: Window10

**after input Chinese terminal does not echo, but can enter**

### problem of repetition
<img width="788" alt="screen shot" src="https://wenan-public.oss-cn-beijing.aliyuncs.com/art.gif">

**Comment by dtboy1995** [comment]
any help？

**Comment by yutent** [comment]
same bug here. And works welll before.

**Comment by yutent** [comment]
It works now.
I remove this config  `// "terminal.integrated.setLocaleVariables": false,` in `settings.json`. I don't know how it was set, I nerver did before.

**Comment by dtboy1995** [comment]
@yutent , it can't works....
