### ISSUE TITLE
HTML in Problems view?

### ISSUE THREAD

**Issue by ncannasse** [Microsoft/vscode#63496]
When capturing compiler output with problemMatcher, some parts are not showing in Problems view, for instance in the message `Array<String> should be Array<Int>` , it will only display `Array should be Array`. It seems some kind of HTML escaping is missing between problemMatcher and Problems view.

A screenshot showing the issue. Tooltip correctly show the full error message:

![](https://i.imgur.com/YSla0ia.png)

**Comment by Gama11** [comment]
Note that this also reproduces with problems from diagnostics:

```ts
import * as vscode from "vscode";

export function activate(context: vscode.ExtensionContext) {
	var diagnostics = vscode.languages.createDiagnosticCollection("foo");
	vscode.window.onDidChangeActiveTextEditor(editor => {
		if (editor != null) {
			var diagnostic = new vscode.Diagnostic(new vscode.Range(0, 0, 1, 0), "Array<Int> should be Array<String>");
			diagnostics.set(editor.document.uri, [diagnostic]);
		}
	});
}
```

![](https://i.imgur.com/6YhLspO.png)
