### ISSUE TITLE
Exclamation mark doesn't work in warnings pane

### ISSUE THREAD

**Issue by Yanpas** [Microsoft/vscode#63490]
- VSCode Version: 1.29.2
- OS Version: linux

Steps to Reproduce:

1. open some .cpp files with errors
2. enter `!**/*.cpp` or `!*.cpp` as suggested in hover
3. errors from these files are still there

My use case:
I use gitlens extension. It downloads older versions of files to /tmp/ and of course they produce a lot of errors and warnings.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexr00** [comment]
Are you saying errors/warnings are in older versions of files that gitlens is downloading? Or the errors/warnings are occuring in the file that you edited with `!`?

**Comment by alexr00** [comment]
Also, can you provide an example small cpp file that will have these errors?

**Comment by Yanpas** [comment]
Sorry, let me clarify.
vscode has **warnings and errors** pane, it groups all errors from the project. And there is an input bar that lets you exclude some files. Here I want to exclude all ts files, but it doesn't work:
![image](https://user-images.githubusercontent.com/7345761/48779105-e77b0600-ece7-11e8-88ae-280f1c024e74.png)

**Comment by sandy081** [comment]
This seems to be a regression from new tree adoption. It's because tree is marking the parent node as visible always.
