### ISSUE TITLE
Freeze on Windows 10

### ISSUE THREAD

**Issue by arjaneising** [Microsoft/vscode#63493]
(I see similar, recent issues posted about crashes on windows, so please ignore/close if this bug report is redundant :-) )

When using the latest 1.29.1, interacting with the application quickly starts to spike CPU and then causes Windows to hang, resulting in a forced reboot. Interactions I tried that ultimately caused this are: typing code in an existing file, unfolding a folder in the folder tree, jumping to a file by typing the start of the file name. The application is usable for a short while, with high CPU before the system/OS becomes unresponsive.

I was able to disable the extensions manually, within the application. With disabled extensions the issue remains.

I guess this is not a lot of information, but please feel free to ask certain details.

Thanks in advance for looking into this :-)

- VSCode Version: 1.29.1
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. open VSCode, last opened folder opens automatically
2. interact with the code base, eg:
2a. type code in a file
2b. unfold a folded folder
2c. goto a file with Ctrl+P
2d. possibly other interactions too
3. continue to do this for a brief period, CPU spikes and within 1 minute OS hangs

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Can you start a profile recording then reproduce? ctrl + shift + P -> Toggle Developer Tools -> Performance -> Record. 
In task manager, can you see if CPU is spiking on a process?

**Comment by arjaneising** [comment]
After filing the issue, my colleagues and I found out the virus scanner active on the systems is interfering with pretty much anything related to the file system in VSCode. Unfortunately, this did not show up clearly in the task manager. I'll close this issue.

My apologies for the confusion, and thanks for getting back to me! :-)
