### ISSUE TITLE
Expose a "Always on Visible Workspace" setting

### ISSUE THREAD

**Issue by aplatypus** [microsoft/vscode#63492]
Issue Type: <b>Bug</b>

On graphical Ubuntu Linux the windowing option in the control menu there is an option for: "Always On Visible Workspace" (being an Desktop workspace, not a VSCode workspace).  That means my vscode window is visible in every ddesktop.

Selecting that option works for a little while, say 30 min or so.  It always seems to be reset or cleared.  When it does reset; the VSCode window can vanish from the current desktop and is only to be found on the desktop it thinks of a 'home'(??).

It is very annoying and irksome when the editor you rely on  just vanishes like that.  I used to think that code had crashed.  Not so.

In contrast many other windows have "Always on Visible Workspace" file browser, terminal, some browswer windows.  These work as expected.  And from memory when I used Atom, it was also well behaved.

How is  VSCode dropping the ball?

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:07:43.495Z)
OS version: Linux x64 4.18.0-11-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Phenom(tm) II X4 965 Processor (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.63GB (0.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
code-runner|for|0.9.5
kotlin|fwc|0.1.9
crystal|g3o|0.1.9
ruby-linter|hoo|1.0.0
bash-ide-vscode|mad|1.3.3
Kotlin|mat|1.7.0
ruby|reb|0.20.0
RustyCode|sav|0.19.1
markdown-preview-enhanced|shd|0.3.11
code-spell-checker|str|1.6.10

</details>

**Comment by sbatten** [comment]
@aplatypus could you provide your current setting for `window.titleBarStyle`?

**Comment by aplatypus** [comment]
native

**Comment by sbatten** [comment]
@joaomoreno @Tyriar Either of you seen this behavior as frequent Linux users. Doesn't appear to be menu related.

**Comment by aplatypus** [comment]
I see it on two Ubuntu 18.10, Cinnamon desktop, LightDM  and 18.04 prior to that and with Gnome.

**Comment by joaomoreno** [comment]
Unfortunately I'm not using Gnome desktop anymore, so I haven't seen this. Sounds like a general Linux os integration issue.

**Comment by aplatypus** [comment]
A wee update per most recent release I installed yesterday: 

```
Version: 1.30.0
Commit: c6e592b2b5770e40a98cb9c2715a8ef89aec3d74
Date: 2018-12-11T22:21:33.585Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.18.0-12-generic
```

Seems 1.30 has bone "_borderless_" -- Quite nice  It has not fixed this issue.  

It has made it harder to reproduce because the DisplayManager or  X-windows system drop-down menu is not longer available on the frame, only Minimise, Expand and Close remain.

The rest of the standard menu selections are (gratefully) available Right-Click on the task-bar VS Code icon.

## suggestions

1. provide the missing standard window options as a menu/icon near the "minimise / full screen / close" icons.
2. Consider adding some support  or API so people can manipulate the frame/window on the desktop.
    * VS Code clearly lives by extensions/ plugins.
    * I personally think it would be handy  to have ways to use these settings from add-on extensions, etc.
3. Add these windowing commands to one of the VS Code top level menus -- `View` menu sounds a likely candidate.

When i was no longer able to use "show on all desktops" I checked View and Hel first, then File, etc.

**Comment by joaomoreno** [comment]
cc @bpasero @Tyriar for Electron consulting

**Comment by joaomoreno** [comment]
@aplatypus Can you still repro this?

**Comment by aplatypus** [comment]
@joaomoreno -- Yes this problem is consistient.  If anything, it is becoming more frequent.  My current version is: 

```
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:40.634Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.0.7-050007-generic
```

Actually it happened just now.  All I was doing was switching back to Code to check the version.  May be it has something to do with a window frame refresh???

**Comment by joaomoreno** [comment]
@bpasero Moving this to you. We probably should use the Electron's API for this: https://electronjs.org/docs/api/browser-window#winsetvisibleonallworkspacesvisible-options

**Comment by aplatypus** [comment]
@bpasero -- The "Always on Visibls Workspace" button is a Dispaly Manger fixture.  This isn't an option, it is normally always present.  Unless it has been turned-off or disabled.


At least please please apply an accurate title, such as this one.

**VS Code must NOT change the "Always on Visible Workspace" window manager setting on Linux**

![image](https://user-images.githubusercontent.com/67028/67535098-dbc86880-f71c-11e9-80c5-64bd7c2fc5d0.png)

There is little advantage to re-implementing an existing working feature.

**Comment by aplatypus** [comment]
This is an error in my opinion.  It breaks existing Windowing functionality on the Window manager / Display Manager.

**Comment by oscx** [comment]
The break with intended Window Manager behavior forces me to stick with one of the old IDE versions and really disturbs the user experience. Can't be managed by Gnome as workaround if this setting is overwritten - which is non-recommended GUI practice. Is there an alternative way to a feature request in terms of "revert" or just disable the unintended setting?
