### ISSUE TITLE
Consider adding example how to get javascript intellisense working in global context in ES5 projects

### ISSUE THREAD

**Issue by realmerx** [Microsoft/vscode#63494]
When working with ES5 project and using external library that has type definitions using module syntax to get intellisense working in global context (without import that would fail in ES5)  you can create your own global.d.ts (name does not matter really) file in project directory with following (example for axios library):

    import { AxiosStatic } from "axios";

    declare global {
        const axios: AxiosStatic;
    }

It brings axios type into global context and you get intellisense without having to do:

import axios from 'axios' 

in javascript file where you want intellisense for axios.

**Comment by roblourens** [comment]
Sorry I don't understand what your question/issue is

**Comment by mjbvz** [comment]
Defining global variables for js type checking is covered here: https://code.visualstudio.com/Docs/languages/javascript#_global-variables-and-type-checking

The specifics vary depending on what library you are using

**Comment by realmerx** [comment]
Added github link and info to original comment how to reproduce this. I agree this is library specific but there is a common pattern of getting things into global context (in my example I use Vue and Axios  - the technique to get them global is exactly the same and would work for any type definition normally requiring import in actual javascript file.
