### ISSUE TITLE
Wrong colors in d.ts after `::`

### ISSUE THREAD

**Issue by niieani** [Microsoft/vscode#635]
This content doesn't get parsed correctly for coloring:
```typescript
export declare const localhostAliases: {
    'localhost': boolean;
    '127.0.0.1': boolean;
    '::1': boolean;
};
```
![screen shot 2015-11-25 at 17 43 39](https://cloud.githubusercontent.com/assets/563469/11403242/1f32ab28-939c-11e5-9a68-09766bafbac6.png)

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#15
