### ISSUE TITLE
After the last update, the system began to slow down.

### ISSUE THREAD

**Issue by lovik1468** [Microsoft/vscode#63503]
http://joxi.ru/GrqjKkVHQlDJRm This happens very slowly and does not work. FTP does not connect half of the plug-ins because of this does not work until this download is completed

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz (8 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|7.87GB (1.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    83	 10740	code main
    0	    78	  2776	   window (Средство создания отчетов о неполадках)
    0	   139	 11032	   gpu-process
    0	    83	 12208	   shared-process
    0	   266	 15760	   window (common.js - v-myza - Visual Studio Code)
    0	    14	   644	     watcherService 
    0	    10	  8268	       console-window-host (Windows internal process)
   13	   933	  8720	     extensionHost
    0	    39	  1376	       electron_node eslintServer.js 
    0	    73	  3060	       electron_node server.js 
    0	    57	  4108	       electron_node server.js 
    0	   103	  5420	       electron_node tsserver.js 
    0	    59	  4848	         electron_node typingsInstaller.js typesMap.js 
    0	    33	  6120	       electron_node server.js 
    0	    33	  6268	       electron_node tslintServer.js 
    0	   147	  8904	       D:/xamp/php/php.exe c:\Users\lovik\.vscode\extensions\felixfbecker.php-intellisense-2.3.10\vendor\felixfbecker\language-server\bin\php-language-server.php --tcp=127.0.0.1:50785 --memory-limit=4095M
    0	    10	 13660	         console-window-host (Windows internal process)
    0	    35	 15544	     searchService
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (common.js - v-myza - Visual Studio Code)
|    Folder (v-myza): 8231 files
|      File types: php(1746) svg(1332) png(1243) jpg(1029) css(847) js(625)
|                  gif(481) less(426) mo(141) po(102)
|      Conf files: makefile(1);
```

</details>
<details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
pug|ama|1.0.1
cypress-snippets|and|1.2.0
ACF-Snippet|ant|1.9.0
vscode-intelephense-client|bme|0.8.8
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
woocommerce|cla|1.0.0
wpcs-whitelist-flags|cla|1.0.0
vscode-eslint|dba|1.7.0
jquerysnippets|don|0.0.1
es7-react-js-snippets|dsz|1.9.0
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.40
prettier-vscode|esb|1.7.2
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vue-snippets-js-html-pug-razor|heb|0.0.3
vue-snippets|hol|0.1.9
rest-client|hum|0.20.3
phpcs|ika|1.0.5
webpack|jer|2.1.0
wordpress-vscode-extensionpack|jpa|1.2.0
react-native-snippet|jun|0.5.0
vscode-gist|ken|1.2.1
vscode-language-pack-ru|MS-|1.29.2
PowerShell|ms-|1.9.0
debugger-for-chrome|msj|4.11.1
php-docblocker|nei|1.6.0
vetur|oct|0.13.0
live-sass|rit|3.0.0
LiveServer|rit|5.2.0
vscode-icons|rob|7.28.0
sass-indented|rob|1.4.9
ftp-kr|rua|1.3.16
vue-vscode-snippets|sdr|1.3.0
code-settings-sync|Sha|3.2.0
indenticator|Sir|0.6.0
js-jsx-snippets|sky|0.3.0
code-spell-checker|str|1.6.10
wordpress-snippet|tun|1.1.5
bootstrap-3-snippets|wcw|0.1.0
vscode-import-cost|wix|2.9.0
wordpress-toolbox|wor|1.2.0
JavaScriptSnippets|xab|1.7.1
ReactSnippets|xab|2.2.1
html-css-class-completion|Zig|1.17.1

</details>

**Comment by alexr00** [comment]
Can you open task manager and see if there is a process spiking CPU?

**Comment by lovik1468** [comment]
http://joxi.ru/KAxBXqgCMGDGDm

**Comment by lovik1468** [comment]
http://joxi.ru/Q2Kz4oji46Qpam

**Comment by lovik1468** [comment]
Sorry, accidentally closed commit

**Comment by alexr00** [comment]
It looks like you have task manager sorted by memory. Can you sort by CPU? We have an known issue where Windows Defender is spiking CPU usage so I want to see if you have an executable belonging to that using lots of CPU.

**Comment by lovik1468** [comment]
Thanks found the problem on their own helped to disable the plugin. And everything works fine as before.
