### ISSUE TITLE
Bring back Toggle Panel Position icon

### ISSUE THREAD

**Issue by igoticecream** [Microsoft/vscode#63501]

**Comment by jahshuah** [comment]
Ditto. Especially for terminal windows. Seriously. Or at least give an option to keep it for those who like having it. I often switch between dual 27" monitors and using my laptop screen. Based on screen real estate, I switch from either docking the terminal on the right side (for large monitors) or on the bottom (for laptop screen).

Shouldn't be a "one size, fits all" design decision.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/63459
