### ISSUE TITLE
javascript selected words highlight bug ?

### ISSUE THREAD

**Issue by alexhmelnoy** [microsoft/vscode#63500]
- VSCode Version: 1.29
- OS Version: windows 10

Hi to all,
in javascript and typescript files we have strange bug with incorrect highlighting selected and matched words. After selection we can see right color about 1 second, after this highlight colors will change to default. Issue doesn't reproduce with other file extensions, like c++, json, etc.

Steps to Reproduce:

1.  set next options:
"editor.selectionHighlightBorder": "#ff0000",
"editorOverviewRuler.selectionHighlightForeground":"#ff0000",
2. reload vs code to apply these options
3.  open javascript or typescript file and select any word

![main js - client - visual studio code 2018-11-20 15 02 36](https://user-images.githubusercontent.com/4902870/48772492-9c57f780-ecd5-11e8-81e7-fba07aaad238.jpg)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
@rebornix Can you please take a look or assign to the right owner. I don't think this is a javascript specific issue. Two problems here:

1. I think selection highlight in the overview ruler is a language has symbol occurrences highlighting (like js does). Not 100% sure about this however

1. For the missing borders, the borders are there but they are under the symbol match highlighting background. This results in them seeming very faint.

**Comment by rebornix** [comment]
It's an known issue with our word/symbol/selection highlight.
