### ISSUE TITLE
TS intellisense Array.findIndex error: 'findIndex' does not exist on type 'IExampleObj[]'. [2339]

### ISSUE THREAD

**Issue by danm** [Microsoft/vscode#63502]
Unable to use findIndex array method in typescript without a intellisense error. Code compiles and runs without issue.

- VSCode Version: 1.29.1 & 1.30.0-insider
- OS Version: 10.13.6 (17G3025)

Steps to Reproduce:

1. Launch
2. Create a typescript file
3. Run the below code
4. The method `findIndex` on an array, will throw a TS error:

```
[ts] Property 'findIndex' does not exist on type 'IDropdownValue[]'. [2339]
```

```ts
interface IProps {
  data: IDropdownValue[];
}

interface IDropdownValue {
  label: string;
}

const testFunction = (props: IProps) => {
  const index = props.data.findIndex((row: IDropdownValue) => {
    if (row.label === 'Daniel') return true;
    return false;
  });
  return index;
};

testFunction({
  data: [
    {
      label: 'this is a label',
    },
    {
      label: 'Daniel',
    },
  ],
});

```

Does this issue occur when all extensions are disabled?: Yes

<img width="789" alt="screen shot 2018-11-20 at 12 19 15" src="https://user-images.githubusercontent.com/6394846/48773179-88ed6200-ecbe-11e8-8881-eb8171f95089.png">

**Comment by mjbvz** [comment]
In your `tsconfig`, what is the `target` and `lib` setting? I believe these apis require a lib of es2016 or higher.

**Comment by danm** [comment]
yeah, my b, I didn't realise that method was ES6. cheers.
