### ISSUE TITLE
Electron async dialog blocks use of mouse

### ISSUE THREAD

**Issue by huanhexiao** [microsoft/vscode#63505]
Issue Type: <b>Bug</b>

i use code under Xubuntu(not Ubuntu).
When i open some folds listed within code, whose directories do not exsit(may  have been moved before), code got stuck

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:07:43.495Z)
OS version: Linux x64 4.15.0-39-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz (4 x 2552)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|7.74GB (5.63GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
beautify|Hoo|1.4.7
vscode-language-pack-zh-hans|MS-|1.29.2
python|ms-|2018.10.1
cpptools|ms-|0.20.1
vscode-code-outline|pat|0.2.1
vscode-icons|rob|7.28.0
cmake|twx|0.0.17
cmake-tools|vec|1.1.2

</details>

**Comment by isidorn** [comment]
Can you reproduce this with vscode insiders https://code.visualstudio.com/insiders/
If yes, than please file this issue with useful reproducable steps and some information which we could actually use to fix this

**Comment by huanhexiao** [comment]
i'm sorry, the insider version does not have such problem.
it exsits in the default version(?), whose home page has a menu "Recent", if I click "More" and choose some folds which have been moved, code stuck. 
But insider's "More" doesn't contain the moved folds, remove them automaticlly? so i can not reproduce this

**Comment by huanhexiao** [comment]
By the way, what are differences between default version and insider version?

**Comment by isidorn** [comment]
Insider version has newer version of source code.
This seems to be tied to the menus, forwarding to @sbatten 
Though I would close since can not be reproduced with insiders

**Comment by huanhexiao** [comment]
Thank you.
Code is great, hope better.
best wishes.

**Comment by sbatten** [comment]
@isidorn I can reproduce this regardless of the menus. Steps to reproduce on Ubuntu 16.04
1. Launch VS Code / Insiders
2. Open any folder (e.g. folder1)
3. Open any other folder (e.g. folder2)
4. Delete the first folder (e.g. folder1)
5. F1 to open command palette
6. Execute Open recent...
7. **Use the mouse** to select the deleted folder (e.g. folder1)

**Comment by isidorn** [comment]
I can reproduce this, it seems like the Electron dialog blocks the whole application.
Please note to reprocude you have to use the mouse

The dialog service is called from here https://github.com/Microsoft/vscode/blob/23e1fb8d6fc6bef3cb0cf57e66a4be3ae5c70444/src/vs/code/electron-main/windows.ts#L881

Last change there is to use the async version of electron api. Thus forwarding to @bpasero 
This feels like an electron issue to me.

**Comment by huanhexiao** [comment]
Do you mean pressing enter could get rid of the sticking？
I am sorry，when this issue occurs，everything is freezing.
i have to enter into tty1 to “killall code” , to retrieve it
