### ISSUE TITLE
Bash progress-bar malformed

### ISSUE THREAD

**Issue by Gurran** [Microsoft/vscode#63504]
- VSCode Version:
Version: 1.30.0-insider (user setup)
- OS Version:
Windows 10 Pro
Steps to Reproduce:

1.  Launch bash in the integrated terminal
2.  Run [sudo] npm install -g @angular/cli

Does this issue occur when all extensions are disabled?: Yes
![bashrogressbars](https://user-images.githubusercontent.com/42462633/48780369-0a9eb900-ecda-11e8-8df0-a9f96874cc3b.PNG)

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
