### ISSUE TITLE
Find/Replace Doesn't appear to be working

### ISSUE THREAD

**Issue by barry292** [Microsoft/vscode#63506]
Issue Type: <b>Bug</b>

Using the Find and Replace functionality doesn't appear to work. It correctly highlights all of the instances that should be replaced but doesn't actually replace them. 

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3096)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.85GB (24.11GB free)|
|Process Argv|C:\Users\Barry.Wilcox\OneDrive - Tribridge Holdings LLC\Documents\PODS\BRD\CR101 - Marketo Integration\Temporary Marketo Scripts\P_LB_Marketo book integration.js|
|Screen Reader|no|
|VM|44%|

</details>Extensions: none

**Comment by alexr00** [comment]
Is this find and replace in the search view or in the editor?

**Comment by barry292** [comment]
Hey Alex, appears to be in the editor.

Also, I closed and reopened and it appears that it is working correctly in
the reopened session. I'll see if I can replicate

**Comment by alexandrudima** [comment]
@barry292 Did you attempt to edit in a read only editor perhaps ?

**Comment by barry292** [comment]
It definitely wasn't that. I am working on the same file in two different
windows, is it possible that was preventing find and replace?

**Comment by alexandrudima** [comment]
No. Sometimes, when using git and clicking on an added file that has been staged, the file is opened from the index in a read-only editor.

Any way, if that was not it, then please let us know if you find reproducible steps.
