### ISSUE TITLE
Can’t open vscode

### ISSUE THREAD

**Issue by ilove3q** [Microsoft/vscode#63516]
VS Code version: 1.29.1 and 1.26
Os: win 10 1809
Hello,
This morning, when I open vscode for working but vscode can’t open laungch. I open task manager, and don’t see it run. I reinstalled vscode 1.29 and its run. 
But, afternoon, the issue appears. I try to reinstall 1.29 or 1.26, its don’t works.

**Comment by ilove3q** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Replace All doesn’t work in large files (#52813)](https://www.github.com/Microsoft/vscode/issues/52813)

It's not like isssue

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/45498d93166483c2eff886e28f8dab915ae382fc/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/code-exploration_1.28.0-1538127308_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/VSCodeUserSetup-x64-1.28.0-exploration.exe)
