### ISSUE TITLE
Can't launch go debugger on MacOS

### ISSUE THREAD

**Issue by Enmk** [Microsoft/vscode#63515]
Issue Type: <b>Bug</b>

Can't start debugging golang application on MacOS , same launch.json works on Linux though...
VS Code displays non-informative message: `Failed to continue: Check the debug console for details.`, while debug console is empty and there is nothing to look at.

Adding tracing to launch.json doesn't help:
```
"trace": true
```

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
go-outliner|766|0.1.20
better-comments|aar|2.0.3
gitlens|eam|8.5.6
goto-last-edit-location|kri|0.2.1
dotenv|mik|1.0.1
mssql|ms-|1.4.0
Go|ms-|0.7.0
vscode-docker|Pet|0.3.1
subtle-brackets|raf|3.0.0
rust|rus|0.4.10
vscode-todo-highlight|way|1.0.4
vscode-proto3|zxh|0.2.2

</details>
<details><summary>Versions of delve and go</summary>

```
$ which dlv
/Users/enmk/go/bin/dlv

$ dlv version
Delve Debugger
Version: 1.1.0
Build: $Id: 1990ba12450cab9425a2ae62e6ab988725023d5c $

$ which go
/usr/local/bin/go

$ go version
go version go1.10.3 darwin/amd64
```
</details>

<details><summary>launch.json</summary>

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${workspaceFolder}/cmd/main.go",
            "env": {},
            "args": [],
            "trace": true
        }
    ]
}
```
</details>

**Comment by ramya-rao-a** [comment]
@Enmk The issue with the console not showing any errors is being tracked in https://github.com/Microsoft/vscode-go/issues/2118

Can you try the latest [Insiders](https://code.visualstudio.com/insiders) which has the fix for this so that you can see the errors?

Once you see the errors, please log an issue in the vscode-go repo at https://github.com/Microsoft/vscode-go

**Comment by edlevin6612** [comment]
Had a similar issue, downloaded/launched Insiders and was able to see the error in the debug console (underlying  cause was my code couldn't compile to start -- facepalm). Glad there is a workaround until the error output is fixed.
