### ISSUE TITLE
Support to pass multiple activation events to "extensionService.activateByEvent"

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#63510]
In order to avoid promise chains like this https://github.com/Microsoft/vscode/blob/b134a61eb2f1557dd5a20068084a4e71ea9344f4/src/vs/workbench/parts/debug/electron-browser/debugConfigurationManager.ts#L418-L420

it would be helpful if multiple activation events could be passed to `extensionService.activateByEvent`

https://github.com/Microsoft/vscode/blob/b134a61eb2f1557dd5a20068084a4e71ea9344f4/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L224

**Comment by alexandrudima** [comment]
IMHO that should not be a chain, since you don't want sequential execution. I think you should do:

```
return Promise.all([
  this.extensionService.activateByEvent(`${activationEvent}:${debugType}`),
  this.extensionService.activateByEvent(activationEvent),
  this.extensionService.activateByEvent('onDebug')
]);
```

**Comment by weinand** [comment]
`extensionService.activateByEvent` returns a Thenable which is incompatible with Promise.all.

But IMHO using independent Promises on the client side looks a bit like overkill to me...
