### ISSUE TITLE
Html format not working as expected

### ISSUE THREAD

**Issue by fractionalJoe** [Microsoft/vscode#63512]
Issue Type: <b>Bug</b>

Create a link or script tage that exceeds 120 characters and Alt+Shift+f.

Expected: Line length does not exceed 120 characters.

Actual: Line length exceeds 120.

Using default settings with wrapAttributes=auto and wrapLineLength=120.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.41GB (17.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.3.2
docomment|k--|0.1.2
csharp|ms-|1.17.1

</details>

**Comment by alexr00** [comment]
wrapAttributes only controls line wrap for tag attributes. Can you provide a concrete example of a line that this happens with?
