### ISSUE TITLE
Default Zoom Out and Go Back keybindings cause "one way" zoom

### ISSUE THREAD

**Issue by el2iot2** [Microsoft/vscode#63513]
Issue Type: <b>Bug</b>

On a smaller laptop (no keypad and using touchpad), I used the `ctrl+=` keybinding to zoom in. This worked as expected (as it has many times before). Then I zoomed in "too far". When I attempted to correct it with `ctrl+-`, the editor flipped to another open document. Soon I was so zoomed in I couldn't navigate to the keybindings or settings to rectify. After a bit of reading, I realized i needed to [edit my settings file](https://code.visualstudio.com/docs/getstarted/settings#_settings-file-locations) manually. I edited `"window.zoomLevel": 9` to `"window.zoomLevel": 0` and was back in business.

Then I looked into my keybinding (as I remember this all working before). I see the following:

![image](https://user-images.githubusercontent.com/28941195/48785585-dd321b00-ec99-11e8-95ff-50a1d7bf9d4f.png)

Note that the ambiguous bindings both somehow have the source of "Default". I am not sure exactly when this happened, and I am sure that if i had a keypad (there is a alternate binding for it) it wouldn't have forced me to load up settings.json in notepad. But that was the adventure of the morning!

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (10.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|3.0.6
language-hugo-vscode|bud|0.11.0
better-toml|bun|0.3.2
EditorConfig|Edi|0.12.5
Ionide-Paket|Ion|1.12.0
docomment|k--|0.1.2
csharp|ms-|1.17.1
PowerShell|ms-|1.9.0
vs-keybindings|ms-|0.2.0
debugger-for-chrome|msj|4.11.1
vscode-docker|Pet|0.3.1
sass-indented|rob|1.4.9

</details>

**Comment by usernamehw** [comment]
I don't see this command being default mapping. It's added by extension `vs-keybindings`.

---

Partly related ~~ there is a command to reset zoom (can also be invoked from command palette)

**Comment by usernamehw** [comment]
Issue about keybindings not showing different source from extensions: #37034

**Comment by el2iot2** [comment]
The "Go Back" navigation binding was indeed [contributed by vs-keybindings](https://github.com/Microsoft/vscode-vs-keybindings/blob/master/package.json#L128-L131), so the ambiguous binding label #37034 masked that original source. Thanks for the detective work, @usernamehw! I will take it up with the extension folks.
