### ISSUE TITLE
Cannot read property 'type' of undefined when restart a debug session with DebugAdapterTracker hookup

### ISSUE THREAD

**Issue by rodrigovaras** [Microsoft/vscode#63529]
This only happen when liveshare is installed and we register our 'generic' adapter tracker to 'spy' messages. It will happen during restart only, normal debugging works fine.

i found the offending code and it seems to be on 'extHostDebugService.ts'.
BTW, the marketplace liveshare extension is broken against the latest debug API, we a private VSIX with those fixes if necessary to repro the issue, i suspect it will happen for other extension that use the new tracking API's

public $startDASession(debugAdapterHandle: number, sessionDto: IDebugSessionDto): Thenable {
const mythis = this;

	const session = this.getSession(sessionDto); <=== this return 'undefined'
	return this.getAdapterDescriptor(this.getAdapterProviderByType(session.type), session).then(x => {

**Comment by weinand** [comment]
@rodrigovaras how is the marketplace LS extension broken against the latest debug API?
I've tried to fix the latest reported breakage last week.

**Comment by rodrigovaras** [comment]
I check the latest proposed API and found some breaks in the consumption of the tracker API. I just fix all of them and everything works fine except the 'restart'. Maybe you are referring to another debug API we were using. The point is that i'm not sure you will be able to see this problem when using the marketplace vsix. Also be aware that we require 'isInternal' == true to use the tracker API. I think it will be easier to try with a simple tracking class that pretty much do nothing.
