### ISSUE TITLE
when clause for editor/context menu contribution point is too difficult to use

### ISSUE THREAD

**Issue by GabeDeBacker** [microsoft/vscode#63520]
- VSCode Version: 1.29.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create an extension that has a contribution point for menus/editor/context
2. Create a when clause like "when" : "resourceLangId == c"
3. Open a .c file, then open
4. Right-click on the "main editor"  
5. Note that the command shows up fine.
6. Click on an output window with no output in it
7. Notice the languagre ID doesn't change
8. Right click in the output window
9. Notice the context menu options appear

This same thing happens in any "editor" that is hosted in VSCode. And it doesn't seem to matter what "when" clause values you use. I've pretty much tried them all.

What I'm really looking for is the ability to add context menu items using "when" clauses in the "editor" instance where a user would be editing source code for the c/cpp languages. This would naturally exclude editor instances in the "output", "debug", etc.

Thus far, I have not been able to find a good way to achieve this.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
You can use the key called `editorLangId`. It will be defined inside code editors (when focus is in the code editor) and will have the string identifier of the language, e.g. for C/C++ that would be `c` and `cpp`.

Since keybindings can be tested easier (without needing to write an extension), here is an example that works for me:

```
{
	"key": "ctrl+r",
	"command": "actions.find",
	"when": "editorLangId=='cpp'"
}
```
