### ISSUE TITLE
Java Language Support crash

### ISSUE THREAD

**Issue by MiciMacii** [Microsoft/vscode#63527]
Issue Type: <b>Bug</b>

Every time I open VS code, after about 5 minutes of use, the Java Language Support crashes and displays this message: "the language support for java server crashes 5 times in the last 3 minutes. the server will not be restarted."
So in order to use the Java Language Support I have to restart VS code every 5 minutes.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|5.90GB (2.95GB free)|
|Process Argv|C:\Users\Mici Maci\Google Drive\Uni\semester 4\Data Structures\lab9\AVLDriver.java|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.10.1
cpptools|ms-|0.20.1
java|red|0.34.0
vscode-java-debug|vsc|0.15.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.10.0
vscode-maven|vsc|0.11.1

</details>

**Comment by alexr00** [comment]
Does this reproduce if you disable all extensions?

**Comment by MiciMacii** [comment]
No, since the Java Support extension is the one crashing.
When I disable every extension except the Java Support extension, it still does it.
When I enable the Debugger for Java as well and try to use it, same thing happens with that. It works for 5 minutes and then the Debugger crashes as well (displaying this message: "Debug adapter process has terminated unexpectedly (read ECONNRESET)").

**Comment by alexr00** [comment]
It looks like the issue is with the extension then. The Language Support for Java(TM) by Red Hat, has this link in their extension details for issues: https://github.com/redhat-developer/vscode-java/issues. It also looks like they might have a bug for it already: https://github.com/redhat-developer/vscode-java/issues/305
