### ISSUE TITLE
Second bar won't display find

### ISSUE THREAD

**Issue by grayback6192** [Microsoft/vscode#63528]
Issue Type: <b>Bug</b>

1. Open second tab
2. Find won't work

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (7.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.3.0
vscode-intelephense-client|bme|0.8.8
gitlens|eam|8.5.6
php-debug|fel|1.12.6
gc-excelviewer|Gra|2.1.26
ftp-simple|hum|0.6.8
sshextension|kon|0.4.0
dotenv|mik|1.0.1
vscode-apache|mrm|1.1.1
debugger-for-chrome|msj|4.11.1
laravel-blade|one|1.18.0
vscode-icons|rob|7.28.0
glassit|s-n|0.1.3

</details>

**Comment by alexandrudima** [comment]
I cannot reproduce. I can open two tabs and have the Find widget working in both of them:

![image](https://user-images.githubusercontent.com/5047891/48942328-4bd3da80-ef1f-11e8-8220-d04bf380f3ea.png)
