### ISSUE TITLE
"paused on exception" but exception is not shown

### ISSUE THREAD

**Issue by Spongman** [Microsoft/vscode#63523]
Issue Type: <b>Bug</b>

i have a simple program that makes async http calls. when an exception is thrown due in the http library, vscode shows that the main thread is "paused on exception" in the callstack, however no exception is shown in the locals view. and entering `$exception` in the watch window just shows 'Evaluation failed'.

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3403)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (2.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
jsrefactor|cms|2.15.1
xml|Dot|2.3.2
gitlens|eam|8.5.6
tslint|eg2|1.0.40
dotnet|for|0.0.4
macros|ged|1.2.1
beautify|Hoo|1.4.7
junos|jam|1.2.0
hg|mrc|1.2.3
mssql|ms-|1.4.0
csharp|ms-|1.17.1
typescript-javascript-grammar|ms-|0.0.47
debugger-for-chrome|msj|4.11.1
live-server-preview|neg|0.1.2
typescript-hero|rbb|3.0.0
java|red|0.34.0
shader|sle|1.1.4
vscode-java-debug|vsc|0.15.0
vscode-java-pack|vsc|0.4.0
vscode-java-test|vsc|0.10.0
vscode-maven|vsc|0.11.1
FilterText|yhi|0.0.11
vscode-preview-server|yui|1.2.0

</details>

**Comment by weinand** [comment]
What debugger are you using?

**Comment by Spongman** [comment]
regular VS managed (non-compatibility)

**Comment by Spongman** [comment]
it's using the `coreclr` debugger.

**Comment by weinand** [comment]
Please file issue against C# extension.
