### ISSUE TITLE
Output Pane Won't Auto Scroll

### ISSUE THREAD

**Issue by pltrant** [Microsoft/vscode#63525]
Version: 1.29.1 (user setup)
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
Windows 10 Pro

When the Output pane receives focus, it stops auto scrolling.  The Scroll Lock is not enabled.

Steps to Reproduce:

1.  Click anywhere in the Output pane.
2.  Wait for new text to be submitted to the Output pane.
3.  It should scroll with the new text, but doesn't.

**Comment by sandy081** [comment]
This is because of the feature - https://github.com/Microsoft/vscode/issues/49110

@isidorn Assigning to you as you introduced this feature. Let me know if I can help you further.

**Comment by isidorn** [comment]
No immediate plans to look into this
Leaving open as feature request and a PR which neatly fixes would be appreicated

**Comment by pltrant** [comment]
How is this not a bug?  It will auto scroll, until the pane gets focus, then stops regardless of the Scroll Lock setting.

**Comment by YisraelV** [comment]
@isidorn what is exactly the feature request? some people want the output to stop when clicked, some want it not to stop. How do you reconcile it?

**Comment by isidorn** [comment]
The output should behave like this:
1. When it is locked: it should never auto scroll
2. When it is not locked: it should auto scroll whenever there is new output

Stoping when clicked is somewhat of a smart scroll, which for some reason we dropped in the output and introduced this toggle.
So the click and what is revelaed should not have influence on whether to auto scroll or not, only the state of the toggle.

**Comment by YisraelV** [comment]
I don't quite understand. The bug as described in the original post:
_1. Click anywhere in the Output pane.
2. Wait for new text to be submitted to the Output pane.
3. It should scroll with the new text, but doesn't._

However this is exactly the behavior that was requested in #49110

@pltrant maybe you could clarify this to me? It sounds like what you describe as bug was requested by users. 

Maybe you mean that clicking the output should change the state of the scroll-lock? but then would moving to the end resume it as was originally intended? because I would imagine if the lock is set it shouldn't resume until it's unset regardless of the cursor position.

**Comment by pltrant** [comment]
Yes, I think you described it well, @YisraelV.  I think having the "Smart Scroll" and "Scroll Lock" is fine, but they should work together and not independent of each other (since they essentially do the same thing - just through different activations).  Meaning if a user clicks anywhere, which then disables the scroll (due to the Smart Scroll), it should do so by enabling the Scroll Lock.  That makes it obvious to the end user what is happening and how to resume scrolling (by simply clicking the Scroll Lock button to toggle it off).  It's also fine if moving to the end auto disables the Scroll Lock lock too (due to the Smart Scroll logic).  I don't think they have to be mutually exclusive, but as is, it does cause confusion.  This isn't a made up scenario - an end user ran into this issue and asked me about it.  They couldn't figure out how to re-enable scrolling since the Scroll Lock was already disabled.

**Comment by YisraelV** [comment]
Thanks for clarifying! I will look into this.

**Comment by sandy081** [comment]
To Verify:

- Scroll lock is enabled when you click in the output panel (except in the last line)
- Scroll lock gets disabled when you click in the last line
