### ISSUE TITLE
Markdown transition to Common Mark breaks YAML front matter

### ISSUE THREAD

**Issue by cdbattags** [Microsoft/vscode#63526]
- VSCode Version: 1.29.1
- OS Version: macOS 10.13.6

Steps to Reproduce:

1. add 3 dashes to start of `.md` file
2. add yaml content
3. add another 3 dashes

The `markdown.previewFrontMatter` does nothing now and the syntax highlighting is all messed up.

**Comment by cdbattags** [comment]
Whoops. Looks like whatever landed in the last version doesn't like:

```yaml
thing: ?
```

A question mark in the last yaml "item" breaks the syntax highlighting.

**Comment by cdbattags** [comment]
Either way the preview of the "front matter" still looks way off.

![image](https://user-images.githubusercontent.com/4399055/48799780-08d2f680-ecd6-11e8-9ab5-7a3d933ca2de.png)

**Comment by Novakeys** [comment]
We know that I do not have any privacy

**Comment by mjbvz** [comment]
```md
---
thing: ?
---
```

is not valid yaml.

Everything works for me if I have:

```md
---
thing: q?
---
```

This is on insiders with all extensions disabled

**Comment by mjbvz** [comment]
I don't understand. Does it work in insiders?

**Comment by cdbattags** [comment]
Unsure what you mean by "insiders" but the syntax highlighting changed on a recent release of VS Code. No idea how to pinpoint which release but definitely within the last month.

Looks to be a non-issue though since question mark is not allowed in general by the YAML spec. So we can go ahead and close this issue methinks.

Just interesting is all.
