### ISSUE TITLE
Ctrl C in integrated terminal

### ISSUE THREAD

**Issue by dlshcbmuipmam** [Microsoft/vscode#63536]
It is a common practice to escape the command in any terminal by Ctrl + C. I know there are a few threads discussing this issue already. However, I found that the solution provided by parkovski (https://github.com/Microsoft/vscode/issues/9347) can fix this problem, simply replace winpty-agent.exe. It would be great if the vscode can include this fix officially.

**Comment by Tyriar** [comment]
Please don't create duplicate issues, there is even a recent update on the issue you linked from.
