### ISSUE TITLE
"emmet.exlcudeLanguages": [] raises "Unknown configuration setting" warning

### ISSUE THREAD

**Issue by jeffschwartz** [Microsoft/vscode#63538]
Issue Type: <b>Bug</b>

Add "emmet.excludeLanguages": [] to User Settings

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     P7550  @ 2.26GHz (2 x 2260)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: unavailable_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Load (avg)|2, 2, 2|
|Memory (System)|2.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.1.4
vscode-eslint|dba|1.7.0
code-beautifier|mic|2.1.0
debugger-for-chrome|msj|4.11.1
material-icon-theme|PKi|3.6.0
open-in-browser|tec|2.0.0
es6-string-html|Tob|1.8.3
lorem-ipsum|Tyr|1.2.0
append-comma|vco|0.0.1
highlight-matching-tag|vin|0.8.4
colonize|vms|2.2.2
vim|vsc|0.16.12

(5 theme extensions excluded)

</details>

**Comment by ramya-rao-a** [comment]
Please share the warning you are seeing.
