### ISSUE TITLE
"Never show this again on" notification disables ability to change largeFileOptimization

### ISSUE THREAD

**Issue by dpb06** [microsoft/vscode#63533]
Issue Type: <b>Bug</b>

This is related to large files tokenization

I started facing this After the fix made in https://github.com/Microsoft/vscode/issues/44206.

If the user clicks "never show this again" when they are informed certain features have been turned off, the user can never have the notification show again via changing settings.
Additionally, all of the settings related to large files are now ignored ('editor.largeFileOptimizations'), as vscode checks to see if the notification was dismissed and returns if it is, then checks settings if it isnt dismissed. 
This means if the user wants to have the notification not display due to not needing it for most files, but be able to force optimizations on later for a particular file, it is now not possible to do so.

Version: 1.29.1
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Steps to Reproduce
---------------------
1) Open large file (vscode definition of large file)
2) Click "Never show this again" on disabled tokenization notification
3) Attempt to word wrap large file (disabled due to disabled tokenization)
4) Open Settings
5) Change User setting 'editor.largeFileOptimizations' to true
6) Attempt to word wrap large file (still disabled)

**Comment by alexandrudima** [comment]
`editor.largeFileOptimizations` is `true` by default. It must be changed to `false` in order to get wrapping working in large files.
