### ISSUE TITLE
Lack of Errors

### ISSUE THREAD

**Issue by TR45HM4N1721** [Microsoft/vscode#63532]
Issue Type: <b>Bug</b>

With the base WPILib Java suite (Java extension and WPILib library), errors d not appear, regardless of what is actually written. I typed, to test this, simply the phrase

this is an error

By all accounts, some error message should appear, or at least be visible in a debug - no such luck.

Extension version: 2019.0.0-alpha-4
VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|5.89GB (2.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by alexr00** [comment]
Is this an issue with a Java extension? In the bottom right corner, do you have the file language set to java?
