### ISSUE TITLE
CLI script not executed in WSL in Windows 1809

### ISSUE THREAD

**Issue by weikinhuang** [Microsoft/vscode#63539]
- VSCode Version: 1.29.1 user setup
- OS Version: Windows 10 x64 1809 build

Steps to Reproduce:

1. Open WSL
2. run `code .` or any flags with `code`

Does this issue occur when all extensions are disabled?: Yes

When I run `code .` it will always run in the foreground.

When I try to run `code --list-extensions`, it exits with a error code of `0` and has no output.

I added `set -x` to the code batch entrypoint and ran `code -v`

```bash
code -v
+ NAME=Code
++++ realpath '/mnt/c/Users/me/AppData/Local/Programs/Microsoft VS Code/bin/code'
+++ dirname '/mnt/c/Users/me/AppData/Local/Programs/Microsoft VS Code/bin/code'
++ dirname '/mnt/c/Users/me/AppData/Local/Programs/Microsoft VS Code/bin'
+ VSCODE_PATH='/mnt/c/Users/me/AppData/Local/Programs/Microsoft VS Code'
+ ELECTRON='/mnt/c/Users/me/AppData/Local/Programs/Microsoft VS Code/Code.exe'
+ grep -q Microsoft /proc/version
+ '[' -x /bin/wslpath ']'
+ export WSLENV=ELECTRON_RUN_AS_NODE/w:DOCKER_MACHINE_NAME:DOCKER_TLS_VERIFY:DOCKER_HOST:DOCKER_CERT_PATH/p
+ WSLENV=ELECTRON_RUN_AS_NODE/w:DOCKER_MACHINE_NAME:DOCKER_TLS_VERIFY:DOCKER_HOST:DOCKER_CERT_PATH/p
++ wslpath -m '/mnt/c/Users/me/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js'
+ CLI='C:/Users/me/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js'
+ ELECTRON_RUN_AS_NODE=1
+ '/mnt/c/Users/me/AppData/Local/Programs/Microsoft VS Code/Code.exe' 'C:/Users/me/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js' -v
+ exit 0
```

This was definitely working before the 1809 update.

Edit: This is the windows version of vscode, **not** the linux version. I am trying to launch the windows build via wsl, which was working consistently before the 1809 build of windows 10.

**Comment by bpasero** [comment]
@weikinhuang what does "Vscode always launches in the foreground" mean? If you run "code --verbose" the process will remain and show output.

**Comment by weikinhuang** [comment]
There seems to be several issues here.

1. When launching `code .` it will hold the console prompt until I close VSCode (like running a long running cli foreground process command).
1. The other problem is that none of the cli commands output anything in the WSL terminal where it did before the windows 10 1809 update. In the output above, you can see that I tried to output the version, but there was no output before the `exit 0` happened.

**Comment by bpasero** [comment]
@weikinhuang yeah all of that sounds like our code-cli.cmd is not being executed, rather our code.exe which does not support everything.

@joaomoreno @Tyriar does this ring a bell?

**Comment by weikinhuang** [comment]
here's my output of:
```bash
which code
/mnt/c/Users/me/AppData/Local/Programs/Microsoft VS Code/bin/code
```

It's definitely running the shell script entrypoint

**Comment by bpasero** [comment]
@weikinhuang does `code --help` work?

**Comment by weikinhuang** [comment]
@bpasero no, running `code --help` just exits with no error and no output.

**Comment by Tyriar** [comment]
I can't reproduce on Windows 1809 (18282.1000) and VS Code 1.29.1

**Comment by weikinhuang** [comment]
@Tyriar I'm willing to provide any additional details you might need

**Comment by weikinhuang** [comment]
ping @Tyriar?

**Comment by Tyriar** [comment]
Unless you have more info that would help reproduce I'm guessing this must be related to the Windows 1809 as I can't repro on a slightly later version.

**Comment by weikinhuang** [comment]
What other information would you need?

**Comment by Tyriar** [comment]
@weikinhuang let us know if it still happens when you update Windows 10 to align with my version (18282.1000)

**Comment by weikinhuang** [comment]
will do

**Comment by weikinhuang** [comment]
This issue is still reproducible on Windows 10 181213.2133 (Insiders Fast Ring) was unable to get into the Skip Ahead version group.

**Comment by weikinhuang** [comment]
@Tyriar Seems there might be some weird issue with the shell or something with the stdout buffer in the current version of wsl or ELECTRON_RUN_AS_NODE.

I ran `vscode --version` in the `Ubuntu` app shell and got this output with weird spacing:

```bash
$ code --version
1.30.1
      dea8705087adb1b5e5ae1d9123278e178656186a
                                              x64
```

Then I tried again with a cat to buffer the output, and it printed out fine:

```bash
$ code --version | cat
1.30.1
dea8705087adb1b5e5ae1d9123278e178656186a
x64
```

In the case where I opened the issue, I was running the shell via SSH and using a local ssh terminal emulator (`SecureCrt`):

```bash
$ code --version
--- NO OUTPUT ---
```

However if I use `cat` as I did above, it works just fine:

```bash
code --version | cat -           
1.30.1
dea8705087adb1b5e5ae1d9123278e178656186a
x64
```

This also solves the issue where I don't regain control of the terminal when I run `code .`, if I pipe it through `code . | cat -`, it works perfectly like it used to.

**Comment by Tyriar** [comment]
@weikinhuang if you suspect it's related to the WSL shell itself you could follow this up with the console team: https://github.com/Microsoft/console
