### ISSUE TITLE
vscode never gets focus when started from cmd line with 'code'.

### ISSUE THREAD

**Issue by rg-3** [microsoft/vscode#63530]
- VSCode Version: 1.29.1

- OS Version: Mac OS 10.14

Steps to Reproduce:

1. start either terminal.app or iterm2.
2. run 'code .'
3. give vscode focus, type cmd + p
4. notice that cmd + p is sent to iTerm2 and not vs code. 
all key strokes are also sent to iTerm2 instead of vscode.
when i try to give vscode focus by selecting it with my mouse, the app with focus in the title bar is always Terminal.app/iTerm.app
5. appears as though vscode never gets focus

Does this issue occur when all extensions are disabled?: Yes

**Comment by r-obert** [comment]
is there a work around for this issue? i can't use vs code anymore :(

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)
