### ISSUE TITLE
debugging 'eval' not working on latest version

### ISSUE THREAD

**Issue by sharang1** [Microsoft/vscode#6354]
- VSCode Version: 1.1.0
- OS Version:windows 10 enterprise

Steps to Reproduce:

1.  executed code using eval(__code, _this);  like below. if __code is having break point inside it then visual studio code is not able to show code and locate break point. Before installing latest updates it was working fine.

setTimeout( function()
	{
		try
		{
			eval(__code, _this);
		}
		catch(eee)
		{
            
		}
	}, 12);

**Comment by weinand** [comment]
@sharang1 since you are passing two arguments to eval, what 'eval' are you using? What is '__code'? I assume it is a string of with some JavaScript code. How do you set a breakpoint in that code?

Without this information I cannot investigate this. Thanks.

**Comment by weinand** [comment]
@sharang1 could you please answer my questions from above.

**Comment by weinand** [comment]
@sharang1 closing.
