### ISSUE TITLE
[Suggestion] Smooth Cursor Animation in Overview Ruler

### ISSUE THREAD

**Issue by JeffreyCA** [microsoft/vscode#63540]
With the smooth typing animation implemented in #20310, I want to suggest adding a similar animation for the cursor in the overview ruler. Notice the cursor in the text area is smooth, but the cursor in the overview ruler is not.

![untitled](https://user-images.githubusercontent.com/9157833/48813840-7f87e800-ed06-11e8-9996-dc6dda51bb33.gif)

**Comment by Ahsome** [comment]
Has any progress been made to this?
