### ISSUE TITLE
Support a view for 'git difftool --dir-diff' 

### ISSUE THREAD

**Issue by zlatko-michailov** [microsoft/vscode#63548]
Thanks for supporting a view for the plain 'git difftool' command where each file is sent individually. I don't use it though, because I don't want to go through many files that I'm not interested in until I get to the file I want to examine. And f I miss it, I have to start all over again. I can't imagine how the plain 'difftool' experience is useful to anybody.

What I always do is open the whole commit using 'git difftool --dir-diff', which prepares two folders (left and right) with all the changed files. Then, I go back and forth with the files I'm interested in. See how bc4 (BeyondCompare does it it). There are plenty of public images available through the search engines.

What is needed is a 'directory tree diff' view, where double-clicking on a file opens _a new tab_ with the 'file diff' view that already exists.

**Comment by DCdeBrabander** [comment]
we need this!
Currently want to view the differences between 2 versions (tags) in repository, and I rather want VSCode to be the difftool then anything else (since Im using vscode for most development currently anyways) but it doesnt play nice..

**Comment by samdenty** [comment]
There's https://marketplace.visualstudio.com/items?itemName=letmaik.git-tree-compare, which pretty much accomplishes what you want

**Comment by zlatko-michailov** [comment]
Let me reiterate. The experience is not diffing folders interactively from within vscode. The experience is `git difftool --dir-diff` from the shell.

Therefore, the referenced extension doesn't help at all.

Vscode has already done the heavy lifting of visualizing the diffs for a particular file. All that needs to be done is to use the "left" and the "right" for that existing view.

Please fix your bot that closes issues to factor in the amount of work needed. This does look like a low hanging fruit to me.

**Comment by alfaproject** [comment]
Also not sure why this is closed <.<

**Comment by colin314** [comment]
Still a problem, this should not be closed.

**Comment by afaucon** [comment]
I don't know if this feature is included in this issue: The possibility to compare 2 diverging branches within a 3 panel view, with the common ancestor in the middle, still with `git difftool -t vscode ref1 ref2 --dir-diff`.
