### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by NekronBrony** [Microsoft/vscode#63544]
Issue Type: <b>Bug</b>

the powershell isent working at all and the extenchens arnt effective

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|19.98GB (15.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.7.0
vscode-npm-script|eg2|0.3.5
powershellprotools|iro|0.1.4
search-node-modules|jas|1.3.0
vscode-exec-node|mir|0.5.0
PowerShell|ms-|1.9.0
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.7.1

</details>

**Comment by junjie-lean** [comment]
i meet this situation too, In my MacBookPro.

**Comment by cleidigh** [comment]
@NekronBrony 
I have a powershell open on Windows ten/1.29.1
Can you provide more information perhaps a screenshot like below to show what you're seeing
You also mentioned extensions.  Is that separate issue? How do you see that connected to the power shell issue?
You should also include information on any extensions.

![image](https://user-images.githubusercontent.com/25272315/48821756-92abaf80-ed28-11e8-9d40-4ba4a5f74adc.png)

**Comment by Tyriar** [comment]
@junjie-lean looks like that's related to your launch scripts.

**Comment by Tyriar** [comment]
Closing since OP hasn't responded
