### ISSUE TITLE
Menu: border falls out of window for top level menu

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#63546]
Looks a bit weird:

![image](https://user-images.githubusercontent.com/900690/48822321-ed5efe80-ed5c-11e8-8c81-c81f5ed8b711.png)

**Comment by sbatten** [comment]
On windows? I cannot repro
![image](https://user-images.githubusercontent.com/6561887/48863756-5192ba00-ed7f-11e8-80ee-1fa27d989f4a.png)

**Comment by bpasero** [comment]
@sbatten yeah, it was through a VM though, so feel free to close if you cannot reproduce on a normal Windows box.
