### ISSUE TITLE
Native dialog locks KDE

### ISSUE THREAD

**Issue by ngollan** [microsoft/vscode#63555]
Issue Type: <b>Bug</b>

Working on the wrong branch and then trying to change branches on a dirty repo via the bottom right UI element triggers a modal dialog telling the user to clear changes before switching branches.

That's OK, but once the dialog is open, it cannot be clicked and locks up the entire KDE window manager so windows can no longer be moved, and even other applications on the same screen (but on other desktops) cannot be interacted with any more.

Killing the `code` process via SIGTERM "unlocks".

This is on Ubuntu 18.04.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:07:43.495Z)
OS version: Linux x64 4.15.0-39-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3314)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.68GB (0.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.3.2
gitlens|eam|8.5.6
beautify|Hoo|1.4.7
ctags-support|jay|1.0.19
rails-fast-nav|jem|1.2.0
haml|kar|1.1.0
auto-comment-blocks|kev|1.0.1
csharp|ms-|1.17.1
prettier-vscode-with-tabs|pas|1.1.0
ruby|reb|0.20.0

</details>

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/45498d93166483c2eff886e28f8dab915ae382fc/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/code-exploration_1.28.0-1538127308_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/VSCodeUserSetup-x64-1.28.0-exploration.exe)

**Comment by ngollan** [comment]
I tried that exploration build (Linux), and the problem is the same. As soon as the dialogue pops up, most interaction with the desktop environment is locked out and I need to kill the `code-exploration` process.

**Comment by ngollan** [comment]
Running Code with `--log debug --verbose` produces this when the dialogue pops up (I left the update messages in there for good measure, but the first two lines seem to be the only relevant ones):

```
[main 08:52:21] windowsService#showMessageBox 1
Gtk-Message: 08:52:21.073: GtkDialog mapped without a transient parent. This is discouraged.
[main 08:52:30] update#checkForUpdates, state =  idle
[main 08:52:30] update#setState checking for updates
[main 08:52:30] RequestService#request https://update.code.visualstudio.com/api/update/linux-x64/stable/bc24f98b5f70467bc689abf41cc5550ca637088e
[main 08:52:30] telemetry/update:notAvailable { explicit: false }
[main 08:52:30] update#setState idle
[main 08:52:31] menubarService#updateMenubar 1
Terminated
```

**Comment by bpasero** [comment]
Does it reproduce when you run "code --disable-gpu"?

**Comment by ngollan** [comment]
Yes, same result. I don't think it's a rendering problem (for one I can still switch between virtual desktops with animations and all, and if I have a console open and selected I can use that), just that dialogue is somehow "too modal".

**Comment by bpasero** [comment]
@ngollan does it happen with any dialog, even the one to confirm when closing a dirty editor?

**Comment by ngollan** [comment]
This is the only one I've had the issue with so far, the dirty editor warning doesn't do it. I won't be able to do more checking until Monday, but I'm curious if that has the same GTK warning.

**Comment by ngollan** [comment]
FWIW, the dirty editor dialogue triggers the same GTK warning.

**Comment by bpasero** [comment]
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to the code. As such, I will go ahead and close it. If you can identify the component that is causing the issue, please report it upstream:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.
