### ISSUE TITLE
Diff sometimes uses different tabWidths for removed lines

### ISSUE THREAD

**Issue by kumarharsh** [microsoft/vscode#63553]
- VSCode Version: 1.29.1
- OS Version: Windows 10

Steps to Reproduce:

1. Make changes in a file tracked by git.
2. Go to the git tab and click on the file in the changes tab.
3. Sometimes, the whitespace of the line removed (`-`) and the line added (`+`) don't align. The removed line is always the one with the incorrect spacing. 
4. This won't happen everytime. To increase your chances of seeing it, keep unselecting the file, and then reselecting it to see the changes. I think sometimes vscode doesn't get a chance to apply the correct whitespace to the removed lines view.

Example:
![image](https://user-images.githubusercontent.com/760112/48828335-7a25ae80-ed95-11e8-8278-483216be14d0.png)

Does this issue occur when all extensions are disabled?: **No** (most probably)

**Comment by kumarharsh** [comment]
Maybe it's caused by the gitlens extension, as I couldn't reproduce it in 5-10 tries with extensions disabled.

**Comment by kumarharsh** [comment]
While reproducing this issue, I observed that when I click on a file in the git view, the removed sections (in red) are painted first (with a tab-size of 2), and then the added sections (in green) are painted, and then the tab size is changed to whatever is in the .editorconfig (4 in my case). In between these two paints, it's possible that gitlens is trying to show the annotations, and that is somehow messing with vscode editor, leaving the removed sections with the original tab-size and thus not aligning with the added sections.

**Comment by alexandrudima** [comment]
Interesting issue, this could technically happen if indentation detection is on, and the "original" is guessed with a tab width of 2, while the "modified" is guessed with a tab width of 4. I agree this results in a confusing presentation.

**Comment by alexandrudima** [comment]
Steps to reproduce: Open two files for (inline diff) comparison and only after the diff is rendered, change the tab size from the status bar. This will impact the modified file, and does not re-render the original deleted lines with the new tab size...
