### ISSUE TITLE
Search with files to include

### ISSUE THREAD

**Issue by flyingfish2016** [Microsoft/vscode#63550]
Somehow I could not search with "files to include" options set. I used to set "files to include" as **\*.ts, as I just want to search ts file. Today I could not make it at all. I have to clear the value in "files to include" to make a search. Otherwise no value returns.

VS code version: 1.29.1

![image](https://user-images.githubusercontent.com/6909659/48826090-646bb580-eda4-11e8-9a0f-696d16207c65.png)

![image](https://user-images.githubusercontent.com/6909659/48826131-7cdbd000-eda4-11e8-83ff-4319ebdb20a8.png)

![image](https://user-images.githubusercontent.com/6909659/48826154-8f560980-eda4-11e8-829b-34f56726a96d.png)

**Comment by roblourens** [comment]
It should work with a forward slash.
