### ISSUE TITLE
VSCode terminating without any error or warning when launching with keyboard shortcut key.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#6355]
- VSCode Version:1.1.0-alpha
- OS Version: Windows10

Steps to Reproduce:
1. Launch VS code 
2. Open keybinding.json to add keyboard shortcut to launch developer tool as below:
    {"key": "CTRL+F12",
    "command": "workbench.action.toggleDevTools",
    "when": "editorTextFocus"
    }
3. Try to launch developer tool by pressing CTRL+F12.
4. Repeat step 3 multiple times and verify app behavior.

Actual: Developer tool launching successfully but with few quick user's action to launch developer tool VScode is closing without any error or warning.
Expected: Application should not be closed.
![keybindingissuewithdevtool](https://cloud.githubusercontent.com/assets/17735796/15261395/150ac4f0-1911-11e6-8de3-0429cc6a3d26.gif)

Tried on MAC and getting below warning message:

<img width="457" alt="keybindingkeyboardshortcut" src="https://cloud.githubusercontent.com/assets/17735796/15262710/e4af76d6-1918-11e6-8f9e-265566af6a84.png">

**Comment by isidorn** [comment]
Can not repro on my mac

**Comment by bpasero** [comment]
Known electron issue.

**Comment by v-pavanp** [comment]
@bpasero : To track this issue, can we link this to original issue?

**Comment by bpasero** [comment]
https://github.com/electron/electron/issues/4261
