### ISSUE TITLE
No menubar under Ubuntu 18.10

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#63559]
After upgrading Ubuntu 18.04 to 18.10 VS Code 1.29.1 has no menu bar and it shows up as "Visual Studio Code - URL Handler" in the Ubuntu desktop menu bar:

![2018-11-21_10-29-55](https://user-images.githubusercontent.com/1898161/48832266-0c6b8980-ed79-11e8-95f4-af47645a7e51.png)

Clicking in the empty space where VS Code's menu bar used to be, drop down menu appear.

**Comment by sant123** [comment]
I have Ubuntu 18.04 and the URL Handler appears in the title.

![image](https://user-images.githubusercontent.com/7959437/48930703-51e69e80-eec0-11e8-8ef7-0595fab97b30.png)

Should I ignore it? 

Version: 1.29.1
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:07:43.495Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
