### ISSUE TITLE
Rechercher absent de la barre latérale

### ISSUE THREAD

**Issue by maduv** [Microsoft/vscode#63560]
Issue Type: <b>Bug</b>

Bonjour,

Je n'arrive plus à avoir le bouton rechercher dans la barre latéral. Il s'affiche dans le panneau et c'est vraiment pas pratique.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (7.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
apex|Joh|0.0.2
vscode-language-pack-fr|MS-|1.29.2
python|ms-|2018.10.1
salesforcedx-vscode|sal|44.8.0
salesforcedx-vscode-apex|sal|44.8.0
salesforcedx-vscode-apex-debugger|sal|44.8.0
salesforcedx-vscode-apex-replay-debugger|sal|44.8.0
salesforcedx-vscode-core|sal|44.8.0
salesforcedx-vscode-lightning|sal|44.8.0
salesforcedx-vscode-visualforce|sal|44.8.0

</details>

**Comment by alexr00** [comment]
Please use English for reporting issues and follow our issue reporting guideline:
https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#reporting-issues.

If you're talking about the button for moving the panel from the bottom to the side, it is now in a context menu and you can still use keybindings. https://github.com/Microsoft/vscode/issues/63459#issuecomment-440205435
