### ISSUE TITLE
Copy Paste are not working in IDE when memory usage is more

### ISSUE THREAD

**Issue by maibono** [Microsoft/vscode#63561]
- VSCode Version:
- OS Version:
Ubuntu 18.04.1 LTS
VS Code: ds
Version: 1.28.2
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:20:56.183Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Steps to Reproduce:

1. Run multiple servers in VS Code
2. Try copy and paste

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by rebornix** [comment]
@maibono can you elaborate more on what's not working? Does it not work at all? Or it doesn't work when the content in the clipboard is large?
