### ISSUE TITLE
Option to hide the status bar

### ISSUE THREAD

**Issue by kendaleiv** [Microsoft/vscode#6356]
For those wishing to further minimize distractions and/or maximize screen space, an option to hide the status bar (the blue bar at the bottom) might be nice.

**Comment by isidorn** [comment]
@bpasero

**Comment by emag50** [comment]
Enter Ctrl + P for the control panel, search for statusbar and set a keybinding to toggle the blue guy. 
![d](https://cloud.githubusercontent.com/assets/13910185/22320754/f790f338-e343-11e6-8ee0-2cde531ac9c8.JPG)
