### ISSUE TITLE
Verify commitHashes used for built-in extensions

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#63564]
Follow up from #62060

The following oss components need to be verified if the correct commitHash / version is used:
- [x] https://github.com/chriskempson/tomorrow-theme 0e0d35ac303f99b8aa182091ebeaee81cf2183a0
- [x] https://github.com/Colorsublime/Colorsublime-Themes d7401929c97c5fe78319b424f575ddce3f05da81
- [x] https://github.com/DefinitelyTyped/DefinitelyTyped 69e3ac6bec3008271f76bbfa7cf69aa9198c4ff0

I believe I did the correct thing but maybe you could check with @aeschli once he is back or try to do some more investigation.
DefinetelyType I think people just copy paste from them and they do not have a version so I took the latest commit I belive

For colorSurblime-themes I also took the latest commit which I am not sure is correct. And same for tomorrow-theme - though for that one it should be good since the latest commmit is 3 years old.

In case some of these need changing, make sure to do a full text search since for some we depend in multiple places.
Thanks a lot

**Comment by alexr00** [comment]
I've spent a couple hours looking through and trying to check the commit hashes, but I can't determine if they're correct. Assigning to @aeschli for when he gets back.

**Comment by isidorn** [comment]
Thanks for looking into this.
it is fine for @aeschli to look deeper into this once he is back as it is not urgent

**Comment by aeschli** [comment]
The theme files were copied from Colorsublime/Colorsublime-Themes some time back in 2014.
In the meantime they have been converted to JSON and modified by us.

@isidorn How important is it that we reference the actual commit of the file we took? We don't have that commit right now, but could figure it out by comparing contents.

**Comment by isidorn** [comment]
@aeschli well it is imporant that we have some reference to the version we took. Either by the commit hash or the version number.
If no license changed between commit hashes and there is no potential security vunerability than I guess it is fine to take an approxiamte commit hash

**Comment by aeschli** [comment]
Updated commit hash for Colorsublime/Colorsublime-Themes to a commit that matches the contents of the themes that we originally copied in 2015,

DefinitelyTyped looks fine to me

The https://github.com/chriskempson/tomorrow-theme registration comes from the markdown extension. @mjbvz Can you verify it is still valid and correct?

**Comment by mjbvz** [comment]
I actually don't think we need to list this for the markdown extension. We use highlight.js which includes a theme called tomorrow theme, but nowhere to my knowledge do we use this repository.
