### ISSUE TITLE
Collapse parent folder action

### ISSUE THREAD

**Issue by bestwestern** [microsoft/vscode#63568]
Is it possible to add a collapse folder in the bottom of the list of files...

Typical use case is when wanting to close the node_modules folder:
So a collapse-above-folder on the red arrow would be awesome

![image](https://user-images.githubusercontent.com/3617433/48837653-2f506a80-ed86-11e8-961a-2552ae271d4b.png)

**Comment by bestwestern** [comment]
Sorry. 
I meant 'above folder' not parent...

**Comment by bpofficial** [comment]
This would be really useful for things like previewing a package's export definitions and having the entire module tree open. The real struggle is scrolling to the top to close the parent with a touchpad.

**Comment by isidorn** [comment]
You can left arrow, space. Since left arrow should navigate to parent and space should collapse it
