### ISSUE TITLE
Adopt new tree for custom views

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#63566]
Adopt new tree for custom views

**Comment by smarter** [comment]
Hi! Is there an ETA for this issue being implemented ?

**Comment by sandy081** [comment]
Most probably next milestone.

**Comment by alexr00** [comment]
New tree in custom view is merged. It is still missing the auto expand initial tree node state, but we wanted to started getting coverage on insiders!

**Comment by eamodio** [comment]
@alexr00 How should we best report issues with this change? Or should we hold off until it is more complete?

**Comment by alexr00** [comment]
Please do report issues as soon as you find them! Opening new issue is the best way. If you could reference this issue or @ mention me that will help me see the issues quickly.
