### ISSUE TITLE
Terminal view changes when typing anything

### ISSUE THREAD

**Issue by SamiBenChaabane** [Microsoft/vscode#63579]
Issue Type: <b>Bug</b>

While using the cmd terminal, As soon as i hit any the view of the terminal changes like it pressed Tab multiple times by itself

VS Code version: Code - Insiders 1.30.0-insider (c348be666adf9650b1ae1d212f019e6e9f226b7d, 2018-11-21T06:25:32.454Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (13.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.21.0-insiders

</details>

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/57803
