### ISSUE TITLE
immediate AppCrash after opening code.exe

### ISSUE THREAD

**Issue by FlorianW16** [Microsoft/vscode#63570]
Issue Type: <b>Bug</b>

completely deinstalled, Code-Folders in AppData/Roaming deleted, current 32bit version for W7 re-installed "for all users" - no startup - immediate crash

![grafik](https://user-images.githubusercontent.com/45231585/48839046-7e989a00-ed8a-11e8-944a-a46f7475c783.png)

Attach Debugger VS2010:

![grafik](https://user-images.githubusercontent.com/45231585/48839105-a687fd80-ed8a-11e8-9007-8a2beb308a3c.png)

Breakpoint!?

![grafik](https://user-images.githubusercontent.com/45231585/48839131-bbfd2780-ed8a-11e8-9e2f-b5f3701ed444.png)

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:11:49.509Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1240 v5 @ 3.50GHz (8 x 3504)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|3.00GB (0.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|

</details>Extensions: none

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by FlorianW16** [comment]
Also crashes with the insider build:

![grafik](https://user-images.githubusercontent.com/45231585/48931041-955b0000-eef4-11e8-9d81-6630ed8773a3.png)

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/45498d93166483c2eff886e28f8dab915ae382fc/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/code-exploration_1.28.0-1538127308_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/VSCodeUserSetup-x64-1.28.0-exploration.exe)
