### ISSUE TITLE
Source control performance downgrade

### ISSUE THREAD

**Issue by almost92** [Microsoft/vscode#63574]
Issue Type: <b>Performance Issue</b>

major performance downgrade when opening source control (take 8-10 seconds to load)
also, major lag when viewing the diffs of files.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17763

<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-kubernetes-tools|ms-|0.1.14
python|ms-|2018.10.1
vscode-docker|Pet|0.4.0
vscode-yaml|red|0.1.0

</details>

**Comment by joaomoreno** [comment]
Can you reproduce with `code --disable-extensions`?

**Comment by almost92** [comment]
no, couldn't reproduce it, any idea which extension might be causing that?

**Comment by joaomoreno** [comment]
Disable them one by one until you find the culprit. Let me know if you find it!
