### ISSUE TITLE
X-fowarded window can't be moved on screen for code-insiders

### ISSUE THREAD

**Issue by xavor92** [Microsoft/vscode#63576]
- VSCode Version: 1.29.1
- VSCode-Insiders Version: 1.30.0-insider
- OS Version:  Ubuntu 16.04 LTS in a Virtualbox VM / Win10 as Host / Cygwin-X 1.20.0.1

I can't move a x-forwarded Window on my Setup when starting the current insider build. The "normal" build still works.

I've updated today from an ~1-2 month old version, since then I can't 'grab' the title bar of the code-insiders window. Insiders had a frame similar to the normal version next to it before I updated.

I can still click the buttons (expand, close, minimize), but I can't move the window nor can I resize it by dragging the corners.

![image](https://user-images.githubusercontent.com/7982749/48841347-742dce80-ed91-11e8-8016-3bb6e5bec9d1.png)

**Comment by sbatten** [comment]
@xavor92 With the insiders version we have been trying out the custom title bar on Linux. This eliminates the standard window chrome and we use our own custom implementation. Unfortunately, this does not play nice with x-forwarded windows and is a limitation on electron it seems.

Probably the best solution would be to set `window.titleBarStyle` back to `native` when X-forwarding. Another option might be to have your X Server let windows provide the window management. I believe you will get 2 sets of min, max, close buttons, but if you like the custom menu bar it is an okay workaround.
