### ISSUE TITLE
Add differing numbers to multiline editing

### ISSUE THREAD

**Issue by Not-Super-Nova** [microsoft/vscode#63571]
Pretty much, I thought it might be nice to add the ability to put a character (such as $ for emmet) so that while you are editing multiple lines using the multicursor function you can input different numbers for each line instead of writing the lines all with the same number then modifying it later.

**Comment by mattwoodnyc** [comment]
I'd love to contribute to this. Where do I start?

**Comment by tghelere** [comment]
Hey guys!
What about this feature?
