### ISSUE TITLE
Python and TSLint linters not working

### ISSUE THREAD

**Issue by MrGrimpy** [Microsoft/vscode#63587]
Nothing is highlighted in both languages and nothing appears under the "Problems" and "Output" tabs.
Developer tools shows nothing under «Console».
In python files, if I run F1 > Python: Run Linting nothing happens.
In typescript files, if I run TSLint: Show Output, I only see "Linter is running.".

Both linters used to work correctly then suddently stopped a few weeks ago.

I should add that pylint works correctly when used from CLI.

Please help

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

**Comment by MrGrimpy** [comment]
No, both linters are working as intended in the latest build.

Thank you and have a nice day :)
