### ISSUE TITLE
Unable to fold block comments

### ISSUE THREAD

**Issue by realjay007** [Microsoft/vscode#63584]
- VSCode Version: 1.29.1
- OS Version: Windows 10 1703

Steps to Reproduce:

1. Open a file with code in it.
2. Comment a section using block comments
3. The commented section cannot be folded. The plus [+] icon no longer shows in the gutter region.

Does this issue occur when all extensions are disabled?: Yes

I believe this is a recent bug (or feature) because I have always been able to fold block commented code.

**Comment by aeschli** [comment]
@realjay007 For what language? Can you add a small sample code?
