### ISSUE TITLE
MacOS - Links in terminal require Alt-Click

### ISSUE THREAD

**Issue by CodingGreen** [Microsoft/vscode#63583]
Issue Type: <b>Bug</b>

When file links are displayed in the terminal on MacOS the popup still reads "Alt-click to follow link"
<img width="256" alt="screen shot 2018-11-21 at 14 39 20" src="https://user-images.githubusercontent.com/17253156/48848504-f622f500-ed9b-11e8-9fd3-9f3d935b6d45.png">
Using option-click works but also actives box selection in the terminal which is confusing...

May be similar to issue #39918

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS version: Darwin x64 17.7.0

<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.7.0
gitlens|eam|8.5.6
prettier-vscode|esb|1.7.2
vsliveshare|ms-|0.3.954
vscode-docker|Pet|0.3.1
vscode-icons|rob|7.28.0
code-spell-checker|str|1.6.10

</details>

**Comment by Tyriar** [comment]
It should only be alt if you have modified `multiCursorModifier`, this is by design.
