### ISSUE TITLE
Git Operations are extremely hard and slow

### ISSUE THREAD

**Issue by venudaroju** [Microsoft/vscode#63582]

**Comment by venudaroju** [comment]
Any git operation runs slow and very hard to perform unless you know all GIT commands. It would be very nice if we have a UI that performs basic to all operations supported by GIT.

**Comment by joaomoreno** [comment]
What's an example of a slow git operation? Is the operation faster when executing it in the command line?

---

Also, do not ignore our issue template, please provide as much info as you can.

![screenshot from 2018-11-22 11-31-51](https://user-images.githubusercontent.com/22350/48897401-48baea80-ee4a-11e8-97ed-fbb3029c273d.png)

**Comment by venudaroju** [comment]
Simple example is getting latest commit from remote repo. I command line behaves the same.. command line responds very slow, for example when I say ‘git branch’ it takes little time to respond..

**Comment by joaomoreno** [comment]
If the command line is very slow, that's the problem, since VS Code simply spawns `git.exe`. I suggest you look into why git is slow in your machine.
