### ISSUE TITLE
auto complete needs restarting

### ISSUE THREAD

**Issue by aamirafridi** [Microsoft/vscode#63580]
Issue Type: <b>Bug</b>

I use vscode on daily basis. It works fine. All though its really annoying when auto complete in javascript stops working or keeps ages to load. I restart vscode and it starts working just fine. I have to restart after every 3-5 hours.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.75GB free)|
|Process Argv|-psn_0_147492|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
html-css-class-completion|Zig|1.17.1
jest-snippets|and|1.6.1
npm-intellisense|chr|1.3.0
vscode-svgviewer|css|1.4.7
vscode-eslint|dba|1.7.0
react-redux-react-router-snippets|dis|0.4.29
eslint-disable-snippets|drK|1.1.5
prettier-vscode|esb|1.7.2
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
dotenv|mik|1.0.1
vscode-duplicate|mrm|1.2.1
sublime-keybindings|ms-|4.0.0
vscode-docker|Pet|0.4.0
vscode-icons|rob|7.28.0
sass-indented|rob|1.4.9
vscode-react-native|vsm|0.6.18
gitblame|wad|2.6.1

(1 theme extensions excluded)

</details>

**Comment by deanolium** [comment]
This is also happening for me. Intellisense in general seems to just stop pretty often since at least the last update.

VS Code Version: 1.29.1
Windows 10

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by aamirafridi** [comment]
Yes. I am on latest version. It happens even without any plugin.

**Comment by mjbvz** [comment]
In a JavaScript or TypeScript file, run the the `Select typescript version` command. What is the exact  version that is currently selected?

**Comment by aamirafridi** [comment]
@mjbvz I get this
![image](https://user-images.githubusercontent.com/55896/49150345-700b2f00-f304-11e8-8f47-e85750b32e56.png)

**Comment by mjbvz** [comment]
You are not on the latest insiders build. Please test using it: https://code.visualstudio.com/insiders/

**Comment by aamirafridi** [comment]
I am not using the insiders build. The bug is on default build. But command not found on insiders build
![image](https://user-images.githubusercontent.com/55896/49237971-5d255700-f3f7-11e8-9f7f-6ff552c9e42f.png)

**Comment by mjbvz** [comment]
The command only shows up when you have a js or ts file open

**Comment by aamirafridi** [comment]
I am not sure why it matters. I am not using this build. How is this relevant?

**Comment by mjbvz** [comment]
The insiders build has the lastest fixes. Your issue may have already been fixed so you should test using it

**Comment by aamirafridi** [comment]
Ok I will move to insiders build
