### ISSUE TITLE
Add a command to open Quick Pick for picking debug target

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#63595]
When I'm pressing F5, now it runs the active debug target. But to change the debug target, I need to use mouse clicks.

I would prefer if I can bind Shift+F5 to a command like `launch` in quick pick. Similar to `task` or `view`, it'll display the list of debug targets. Then I can type to filter it down. After successful launch, it should switch the active debug target to the chosen one.

**Comment by isidorn** [comment]
There is select and start debugging, you can assign a custom keybinding to it
![screenshot 2018-11-21 at 17 50 10](https://user-images.githubusercontent.com/1926584/48856139-f03a0d80-edb5-11e8-9e48-995d075ddbcf.png)

**Comment by octref** [comment]
Hmm I did try to find it but couldn't...Thanks!

**Comment by isidorn** [comment]
Welcome
