### ISSUE TITLE
Allow decorations to contain multiple lines of text

### ISSUE THREAD

**Issue by smarter** [microsoft/vscode#63600]
Using [ThemableDecorationAttachmentRenderOptions#contentText](https://code.visualstudio.com/docs/extensionAPI/vscode-api#ThemableDecorationAttachmentRenderOptions) it's possible to specify a string to be displayed at a specific position in the source code. However, newlines in this string are ignored.

This limitation makes some features hard to implement, e.g. for Scala 3 we've developed a vscode extension which contains a [worksheet mode](http://dotty.epfl.ch/docs/usage/worksheet-mode.html) that runs every line of code in the current buffer and displays the corresponding output on the right side of the screen. This is done using decorations, but when the output spans multiple lines we're forced to add new empty lines in the user code to properly display it, this is hacky and fragile.

Another usecase for newlines in decorations is displaying compiler-generated code: for example, a user might want to see what code a macro generates, and this code may span multiple lines.

**Comment by smarter** [comment]
Instead of extending the decoration API to support newlines in contentText (which seems hard given how it's implemented), I wonder if we could instead introduce a new API to insert "virtual" lines in the editor, where the content of a virtual line is set using the API and otherwise is read-only, in effect this would be similar to code lenses, except code lenses are also restricted to a single line and are styled in a peculiar way. Does that seem reasonable ?

**Comment by alexandrudima** [comment]
Let's track in #3220
