### ISSUE TITLE
VSCode debugger front end is not showing the source correctly when sourceReference is not 0

### ISSUE THREAD

**Issue by dibyendumajumdar** [Microsoft/vscode#6360]
- VSCode Version: 1.1.0
- OS Version: Windows 10

Steps to Reproduce:

1. As the debugger steps through code the backend returns a sourceReference != 0
2. When the debugger front end sends a source request with the sourceReference to the backend, the backend returns the source code
3. The first time this works fine.
4. But next time even if the source has changed, VSCode displays the same source as before.

Example of sequence:

{"type":"request","seq":116,"command":"source","arguments":{"sourceReference":-1124546559}}
{"type":"response","seq":141,"command":"source","request_seq":116,"success":true,"body":{"content":"local t: table = {}; t=function() end"}}

{"type":"request","seq":227,"command":"source","arguments":{"sourceReference":-1115920383}}
{"type":"response","seq":273,"command":"source","request_seq":227,"success":true,"body":{"content":"local t: table = {}; local f=function() t = 1 end; f()"}} 

In the above sequence VSCode keeps showing the first source, although the second request has a different sourceReference and a different source.

**Comment by dibyendumajumdar** [comment]
My analysis is that somehow the front-end is assuming that for a given stack frame the source reference is going to be the same across multiple calls to the backend. In my implementation this is not true - so therefore the front-end is displaying the wrong source I believe. This seems like 'undocumented' behaviour?

**Comment by isidorn** [comment]
> the source reference is going to be the same across multiple calls to the backend
What exactly do you mean by multiple calls to the backend?

VSCode frontend supports displaying multiple different source files with a reference (just checkout node debugging and click deep down in the call stack).

When you expect VSCode to show your new source - what is the exact situation? User clicked on that source in call stack?

Is there some way I can reproduce this behavior on my machine?

**Comment by dibyendumajumdar** [comment]
@isidorn Many thanks for looking into this. I have attached a  minimum sample program - and the log output from a debug session. You can install the Ravi Debugger extension from the marketplace and try to step through the sample program. Will run on Windows 10 64-bit only.

You can see from attached log (line 490, line 551, line 663) as the code steps through the script - the stack trace returned by the backend indicates that the source is to be retrieved via the sourceReference. However the front end never sends a source request.

By front end I mean VSCode. By backend I mean my debug executable.

Log file:
[out1.txt](https://github.com/Microsoft/vscode/files/266921/out1.txt)

Sample script - please remove .txt extension:
[simple-debug-test.lua.txt](https://github.com/Microsoft/vscode/files/266924/simple-debug-test.lua.txt)

Sample launch file - please remove .txt extension:
[launch.json.txt](https://github.com/Microsoft/vscode/files/266925/launch.json.txt)

**Comment by dibyendumajumdar** [comment]
btw if you have a /temp folder on the drive then the log file named out1.txt will be generated by the backend.

**Comment by dibyendumajumdar** [comment]
I have been trying to work out the cause here. I am finding that the source is correctly displayed if the Source.name is uniquely set. So it appears that VSCode is somehow associating the source with a name, and not calling the backend if it thinks that the source is already available by name? This seems to me a) undocumented behaviour, b) not as per spec because if sourceReference is set then shouldn't the backend be always called to retrieve the source?

**Comment by dibyendumajumdar** [comment]
I have implemented the fix that the name for each dynamically generated source includes the pointer address of the source - making each name unique. This appears to work with the example script supplied above. I have also updated the package.

It would be great if you can confirm the semantics of the sourceReference feature. 

Does sourceReference have to be unique within a session?
Does the source name have to be unique within a session?

**Comment by isidorn** [comment]
If `sourceReference > 0` then it has to be unique within a session.
`sourceName` should not have to be unqiue within a session. However I looked now in the code and there seems to be a limitation that you hit in how we are doing caching of these sources. So in practice it should be unique until we fix this issue.

**Comment by dibyendumajumdar** [comment]
OK thank you for confirming. Requiring source reference to be unique is also a limitation in my view as languages like Lua can have hundreds of dynamically generated functions each with their own source snippet. Can it not be more granular like maintaining unique source reference for a given stack instantiation?

Alternative could sourceReference be a string? Reason for asking all this is that in Lua the VM gives me access to the source. So I simply need to pass a reference that I can decode back. Right now I am passing the stack depth but as per your note that will not work as it will not be unique. If source reference is a string I can encode more information.‎ I could encode stack depth plus the address of the source.
From: Isidor Nikolic
Sent: Thursday, 19 May 2016 8:47 AM
To: Microsoft/vscode
Reply To: Microsoft/vscode
Cc: Dibyendu Majumdar; Author
Subject: Re: [Microsoft/vscode] VSCode debugger front end is not showing the source correctly when sourceReference is not 0 (#6360)



If sourceReference > 0 then it has to be unique within a session.
sourceName should not have to be unqiue within a session. However I looked now in the code and there seems to be a limitation that you hit in how we are doing caching of these sources. So in practice it should be unique until we fix this issue.

**Comment by isidorn** [comment]
The reason for the uniquness is that we somehow need to identify them on the VSCode side. Unique per stack frame instantitation makes sense, however this would require us to drop our source cache per each step - so we would have to first experiment with how this behaves in practice.
Making it a string also makes sense, however that would change our protocol and break other debug adapters.
Adding @weinand to get his opinion on the matter

**Comment by dibyendumajumdar** [comment]
@isidorn @weinand  Hi - I have been able to fix the source display on my implementation by following means: I set sourceReference to the pointer address of the source string, and store a list of sourceReference to stack depth mapping in the debugger. So when the front-end sends a Source request I lookup the stack depth using the sourceReference.

I only need to know the stack depth to locate the source - as the source is available in the Lua VM. But since stack depth is not unique - my original solution of passing this as sourceReference would not work. 

Is it possible to do following:

a) Add a stack frameId to the Source request - can the front end supply this?
b) Ensure that sourceReference is sized such that it can hold pointer values (as integers). This seems to work but I am not sure what the 'number' JSON value can hold and whether it is large enough to hold a pointer value.

The stack frameId is all I need to return the source. But this may not be true for other debug adapters of course.

**Comment by weinand** [comment]
@dibyendumajumdar source references are only valid for a single session (the life time of a debug adapter). So VS Code will not persist source references across sessions. This makes it very simple for a debug adapter to manage source references: just use a counter and increment the counter if you need a new source reference. Internal to the debug adapter you can just use the Handles class available through the vscode-debugadapter module. For every source that VS Code should stream from the debug adapter to VS Code create a new entry in Handles and return the handle as a source reference. If VS Code should show the same source sometime later, just make sure to return the same handle. If you need to return a new source to VS Code, create a new handle.
Alternatively to the Handles class you could return the address of a source (converted to an integer) as  the source reference as long this address does not change for the lifetime of the debug adapter. I prefer the use of the Handles because the integers returned as source references are easier to follow than arbitrary 64 bit addresses.
