### ISSUE TITLE
Source control revert dialog appears more than once

### ISSUE THREAD

**Issue by thuy-n-lu** [Microsoft/vscode#63608]
Issue Type: <b>Bug</b>

When reverting changes in the source control panel, the dialog for if I want to delete/revert my changes pops up more than once even after my selection

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:47:15.448Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.89GB (5.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.40
theme-monokai-pro-vscode|mon|1.1.9
vim|vsc|0.16.12

</details>

**Comment by alexr00** [comment]
Possibly related to #62524?

**Comment by bpasero** [comment]
@thuy-n-lu are other actions causing this too, e.g. deleting a file pops up multiple dialogs to confirm?
