### ISSUE TITLE
"Cannot read property 'getItem' of undefined"

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#63606]
Issue Type: <b>Bug</b>

- In Insiders
- Change the theme
- See exception in devtools

The id of this tree is 'npm'

```
e.getItem (treeModel.ts:1429)
e.refresh (treeModel.ts:980)
e.refresh (treeImpl.ts:162)
(anonymous) (customView.ts:503)
t.doRefresh (customView.ts:503)
(anonymous) (customView.ts:233)
e.fire (event.ts:212)
e.applyTheme (workbenchThemeService.ts:352)
(anonymous) (workbenchThemeService.ts:297)
g (winjs.base.js:1191)
enter (winjs.base.js:867)
_run (winjs.base.js:1089)
_completed (winjs.base.js:1057)
_tickCallback (internal/process/next_tick.js:188)
Promise resolved (async)
enter (winjs.base.js:762)
_run (winjs.base.js:1089)
_setCompleteValue (winjs.base.js:1073)
g (winjs.base.js:1191)
enter (winjs.base.js:867)
_run (winjs.base.js:1089)
_completed (winjs.base.js:1057)
g (winjs.base.js:1191)
enter (winjs.base.js:867)
_run (winjs.base.js:1089)
_completed (winjs.base.js:1057)
(anonymous) (fileService.ts:248)
emitNone (events.js:111)
emit (events.js:208)
endReadableNT (_stream_readable.js:1056)
_combinedTickCallback (internal/process/next_tick.js:138)
_tickCallback (internal/process/next_tick.js:180)
```

VS Code version: Code - Insiders 1.30.0-insider (c348be666adf9650b1ae1d212f019e6e9f226b7d, 2018-11-21T06:24:03.519Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (1.47GB free)|
|Process Argv|-psn_0_8824938|
|Screen Reader|no|
|VM|25%|

</details><details><summary>Extensions (69)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
disableligatures|Coe|0.0.8
duplicate|alq|0.0.2
mock-debug|and|0.27.0
gulpsymbols|apa|0.1.1
emojisense|bie|0.4.1
lit-html|bie|1.10.1
better-toml|bun|0.3.2
genderdecoder|chr|0.0.4
quills|chr|1.0.1
vscode-opennewinstance|chr|0.0.4
npm-intellisense|chr|1.3.0
vscode-svgviewer|css|1.4.7
dart-code|Dar|2.20.0
gitlens|eam|8.5.6
tslint|eg2|1.0.40
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.5.1
php-debug|fel|1.12.6
vsc-travis-ci-status|fel|1.1.0
vscode-flatland-icon-theme|geb|0.0.6
vscode-pull-request-github-insiders|Git|0.324.0
beautify|Hoo|1.4.7
vscode-dimmer|hoo|2.1.0
vscode-ghc-mod|hoo|1.2.0
vscode-styled-components|jpo|0.0.25
center-editor-window|kai|2.1.1
theme-karyfoundation-themes|kar|18.2.1
vscode-typescript-ast-explorer|kri|1.0.0
Lisp|mat|0.1.8
rainbow-csv|mec|0.8.0
theme-monokai-pro-vscode|mon|1.1.9
vscode-cosmosdb|ms-|0.9.0
vscode-language-pack-zh-hans|MS-|1.29.2
python|ms-|2018.10.1
azure-account|ms-|0.7.0
azurecli|ms-|0.4.2
csharp|ms-|1.17.1
Go|ms-|0.7.0
team|ms-|1.144.1
debugger-for-chrome|msj|4.11.1
live-server-preview|neg|0.1.2
incrementor|nms|0.1.0
vetur|oct|0.13.0
vscode-docker|Pet|0.4.0
seti-icons|qin|0.1.3
java|red|0.34.0
vscode-sort-json|ric|1.13.0
sass-indented|rob|1.4.9
npm-link-status|rob|0.0.3
searchdocs|rob|0.0.3
unittest-navigate|rob|0.0.2
vscode-nand2tetris-hdl|rob|0.1.1
vscode-stocks|rob|0.1.1
vscode-workspacecontains-canary|rob|0.0.2
rust|rus|0.4.10
annotator|ryu|0.11.0
yo|sam|0.9.3
elm|sbr|0.23.0
kustovscode|sea|0.0.4
vscode-hexdump|sle|1.7.2
vscode-open-in-github|sys|1.10.0
ayu|tea|0.17.0
html-preview-vscode|tht|0.2.4
selectline-statusbar|tom|0.0.2
es-quotes|vil|0.2.6
vscode-react-native|vsm|0.6.18
vscode-jumpy|wma|0.3.1
wandbox-vscode|wra|2.2.3

(28 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Since the id of the tree is `npm` which sounds like a custom tree, I'll move this to @sandy081.
