### ISSUE TITLE
Terminal Process Failed To Launch When Working in a Deleted Directory

### ISSUE THREAD

**Issue by runewake2** [Microsoft/vscode#63604]
- VSCode Version: 1.28.2
- OS Version: Debian Linux

Some version control systems use specific directory structures to to manage changes. Perforce, TFS and Subversion are all potential examples here. In these examples a use case involves opening a copy of Visual Studio Code to work in that directory, making and committing the change and then deleting the local change.

In my use case, after deleting the local change, I would like to open a terminal to 1) create a new change 2) navigate to the new change 3) use `code -r /my/new/directory` to open the new change in a visual studio code window. This is currently not possible in the integrated terminal. When you attempt to open the integrated terminal from a deleted directory the command fails with the error `The terminal process command failed to launch (exit code: 1)`. This error effectively prevents using an integrated terminal once the directory your Visual Studio Code instance is opened to is deleted. I would like some sort of fallback behavior added to help ensure a shell is provided in this failure case. 

#### Steps to Reproduce:

1. `mkdir ~/testing`
2. `code -r ~/testing`
3. `ctrl` + `shift` + `p` -> "New Integrated Terminal" (works correctly)
4. `rm -rf ~/testing`
5. `ctrl` + `shift` + `p` -> "New Integrated Terminal" (The terminal process command failed to launch)

**Comment by Tyriar** [comment]
> This error effectively prevents using an integrated terminal once the directory your Visual Studio Code instance is opened to is deleted.

This is by design, I imagine other parts of the editor will also break. Some things you can consider:

- Make an extension to create a terminal where you want to
- Set `terminal.integrated.cwd`
