### ISSUE TITLE
More actions (...) button on custom views doesn't work anymore

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#63601]
Issue Type: <b>Bug</b>

Clicking on the `...` icon doesn't do anything anymore. I believe this started in today's insiders version (or very recently).

Even affects the `Outline` view

VS Code version: Code - Insiders 1.30.0-insider (c348be666adf9650b1ae1d212f019e6e9f226b7d, 2018-11-21T06:25:32.454Z)
OS version: Windows_NT x64 10.0.18282

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (15.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by joaomoreno** [comment]
Yeah, fixed yesterday, today's insiders is good! :+1: 

Thanks for keeping an eye out, @eamodio!

**Comment by joaomoreno** [comment]
Yeah, fixed yesterday, today's insiders is good! :+1: 

Thanks for keeping an eye out, @eamodio!
