### ISSUE TITLE
VS Code always give error on autoupdate

### ISSUE THREAD

**Issue by IPv6** [Microsoft/vscode#63619]
Every time i close VS Code it flashes error about "Cant update". Every time. It`s even hillarious ))
- VSCode Version: 
Version: 1.28.2 (user setup)
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:23:51.859Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

- OS Version: Win10

---------------------------
VS Code
---------------------------
Failed to install VS Code update.
Updates may fail due to anti-virus software and/or runaway processes. Please try restarting your machine before attempting to update again.
If update fails repeatedly, please attach the following log file to a new issue on GitHub:
C:\Users\wpadmin\AppData\Local\Temp\vscode-inno-updater-1542867591.log

[vscode-inno-updater-1542867591.log](https://github.com/Microsoft/vscode/files/2606789/vscode-inno-updater-1542867591.log)

**Comment by joaomoreno** [comment]
Please disable automatic background updates: `update.enableWindowsBackgroundUpdates = false`
