### ISSUE TITLE
Add CompletionItemKind/SymbolKind and icons for C++ things like typedef/alias and function declarations

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#63617]
We would like 

CompletionItemKind.TypeAlias and SymbolKind.TypeAlias  (there is no good icon choice currently, we might use "interface" but that might be confusing)
SymbolKind.FunctionDeclaration and SymbolKind.OperatorDeclaration (we currently just use the function or operator icon)

I think that would involve an LSP change.

With icons similar to what Visual Studio C++ has.
![image](https://user-images.githubusercontent.com/19859882/48880473-7f025680-edc5-11e8-8b8a-c4bd4f517b31.png)
![image](https://user-images.githubusercontent.com/19859882/48880491-917c9000-edc5-11e8-9b35-3e19842aaeb8.png)

As a workaround for SymbolKind we are adding extra text to the symbol name, like (declaration): https://github.com/Microsoft/vscode-cpptools/issues/2851 .

Also, CompletionItemKind and SymbolKind for PrivateField, ProtectedField, PrivateMethod, ProtectedMethod would be nice to have, but lower priority:
![image](https://user-images.githubusercontent.com/19859882/48880760-b3c2dd80-edc6-11e8-838f-37d0f4a0c167.png)

Also, unions would be nice to have, but lower priority (we plan to use the Struct icon for that).
![image](https://user-images.githubusercontent.com/19859882/48880516-b96bf380-edc5-11e8-8723-1d6266671b4e.png)

Also, there is a CompletionItemKind.Reference which we're using for a file symbolic link, but we'd like a CompletionItemKind.FolderReference for folder symbolic links, but that is also lower pri (we just use the Folder type like TypeScript does).

**Comment by jrieken** [comment]
This dupes #23927 and https://github.com/Microsoft/vscode/issues/2628. For individual kind requests, file individual request please. Also list languages that support this, e.g a good list of languages that support alias, as we don't wanna end up with an enumeration of all possible kinds
