### ISSUE TITLE
markdown outline support more than 10 items

### ISSUE THREAD

**Issue by nik-shornikov** [Microsoft/vscode#63611]
- VSCode Version: 1.29.1 bc24f98b5f70467bc689abf41cc5550ca637088e x64
- OS Version:   System Version:	macOS 10.13.6 (17G3025)

Steps to Reproduce:

1. start a markdown file
2. add the following content
```
# 1
## 1
### 1
#### 1
#### 2
#### 3
#### 4
#### 5
#### 6
#### 7
#### 8
#### 9
#### 10
#### 11
```
3. check the outline to find item 6 appearing as item 1, etc; fun puzzle to reverse engineer without looking at code; happens at any level of outline with >10 items

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Your outline view is set to `sort by type`. Change it to: `sort by position` by clicking on the `...` in the bar

<img width="313" alt="screen shot 2018-11-26 at 6 05 46 pm" src="https://user-images.githubusercontent.com/12821956/49053671-ee04f400-f1a5-11e8-9150-4044ffbb0d0b.png">

**Comment by nik-shornikov** [comment]
Awesome... thanks for fixing my immediate problem. Is this by design or still a (lesser) bug?

**Comment by mjbvz** [comment]
@jrieken This is for sorting the outline view by `type`

**Comment by nik-shornikov** [comment]
Fellas, I’m just seeing if you could tell me the logic. I’d expect that an h3 is the same type as the h3 following it. Surely, I’m missing something. What am I missing?

Say you’re sorting objects on a “column”
which isn’t defined for any of them. What’s less desirable or expected: a random sort or a positional sort following some inexplicable algorithm?
