### ISSUE TITLE
Copying and pasting long strings into command line fails

### ISSUE THREAD

**Issue by klick-barakgall** [Microsoft/vscode#63613]
Issue Type: <b>Bug</b>

Not sure if maybe this is unsupported? I feel there is good support for the Terminal in general including copy and paste support.

However today I noticed that some of my strings refused to copy into the terminal and the only difference I can find is that these strings are longer then the ones that work.

The string in question is of length 1587 and fails to paste (right-click, ctrl+v, double right-click > paste... all do nothing, terminal behaves as if no action taken).

So I set about testing this real quick.

The following is a list of lengths I tried and whether the paste action worked in the terminal. Each of the strings are constructed of "1234567890" repeated/truncated however many times are necessary.

100: Paste worked
500: Paste worked
1000: Paste worked
2000: Paste does not work
1500: Paste worked
1750: Paste does not work
1580: Paste does not work
1550: Paste worked
1570: Paste does not work
1560: Paste worked
1565: Paste worked
1568: Paste worked
1569: Paste does not work

It seem like if the length of the string is 1569 characters long or longer it fails to paste. I also tried to copy a string of length 1569 to notepad first and then to the terminal from there (to strip out any strangeness/alternative data-types, etc).

This happens with extensions disabled as well.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.63GB (18.27GB free)|
|Process Argv|C:\_projs\OverKlock\CM|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
calculate|aca|2.1.0
vscode-diff|fab|1.3.6
code-beautifier|mic|2.1.0
csharp|ms-|1.17.1

</details>

**Comment by klick-barakgall** [comment]
Also, minor additional mention: All of these strings appear to work in the regular windows command line outside of VS Code.

Please let me know if I can provide any additional details to get this resolved.

**Comment by Tyriar** [comment]
Looks like the same root cause as https://github.com/Microsoft/vscode/issues/38137
