### ISSUE TITLE
Segmentation fault on Fedora 28.

### ISSUE THREAD

**Issue by c-edw** [Microsoft/vscode#63610]
I'm currently experiencing a similar problem to #60128 on Fedora 28, version `1.26.1` of VSCode. 
```
/usr/bin/code: line 35: 12852 Segmentation fault      (core dumped) ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"
```

**Comment by oneslash** [comment]
@c-edw, could you try to install latest version, it might have the fix.

**Comment by c-edw** [comment]
Strangely, the package wouldn't update. I was only able to obtain the latest version by removing and reinstalling `code`. I assumed that `dnf update` would always go and get the version I was supposed to have.

`1.29.1` works and resolves this issue. Thanks for your help :+1:
