### ISSUE TITLE
Collapse all in Explorer change to expand all if collapsed

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#6361]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows 10

Would it be possible to change the function of collapse all to expand all if all explorer items are already collapsed? Just a feature I thought could be useful.

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
