### ISSUE TITLE
VS Code startup time is very slow

### ISSUE THREAD

**Issue by vy74u745** [Microsoft/vscode#63622]
Issue Type: <b>Bug</b>

Start the VS Code

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500T CPU @ 2.70GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (3.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by octref** [comment]
Please follow https://github.com/Microsoft/vscode/wiki/Performance-Issues for reporting perf issues.

It would be helpful if you can do both:

- F1 -> Startup Performance -> Paste results here
- Run `code --prof-startup` and upload the startup profiles here
