### ISSUE TITLE
Git: Add setting to disable automatic refresh

### ISSUE THREAD

**Issue by chongchai** [microsoft/vscode#63625]
I find when I open file in the vscode in the explore viewlet, the git.exe will run in the background cause a little high CPU usage. From the git output, it seems that command 'git show' and 'git check-ignore -z --stdin' is running. But I don't want it run automatically.  

 Can I stop git auto-runnig in the background and set it to run when I switch to git viewlet? Thanks in advance.

**Comment by joaomoreno** [comment]
That would break editor gutter decorations, the git status bar item, etc. It sounds like a pretty bad idea. We could instead give you a setting which would disable automatic refreshing all the time, that would mean you'd have to run `Git: Refresh` when you wanted to see the latest changes, or press the Refresh icon at the top of the SCM viewlet.

**Comment by chongchai** [comment]
@joaomoreno The "git.autorefresh" setting is good for me. Thanks.

**Comment by skprabhanjan** [comment]
@joaomoreno , There is already a setting called [autorefresh](https://github.com/Microsoft/vscode/blob/master/extensions/git/package.json#L1014), Please confirm if we can use this itself in https://github.com/Microsoft/vscode/blob/master/extensions/git/src/autofetch.ts.

@YisraelV , If you want to go ahead then here is what you should do.
Use the above setting [here](https://github.com/Microsoft/vscode/blob/master/extensions/git/src/autofetch.ts#L114).

PS : This is how you use a setting ( https://github.com/Microsoft/vscode/blob/master/extensions/git/src/autofetch.ts#L74)

PPS : I have a PR ready if you have changed your mind , so let me know :)

**Comment by YisraelV** [comment]
@skprabhanjan no problem go ahead :)

**Comment by joaomoreno** [comment]
This is done: `git.autorefresh`.
