### ISSUE TITLE
editor.insertSpaces setting ignored based on status bar setting

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#6362]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Open settings
2. Add "editor.insertSpaces": false
3. Open a file and press tab

Spaces are still being inserted if your status bar setting is set to spaces.

**Comment by SamVerschueren** [comment]
When I add `editor.insertSpaces: false`, it actually updates my status bar setting and uses tabs instead.

**Comment by isidorn** [comment]
Dup of #5276
