### ISSUE TITLE
custom menu removes native titlebar

### ISSUE THREAD

**Issue by mleduque** [Microsoft/vscode#63629]
Issue Type: <b>Bug</b>

Wehn I launch code, there is a tip which says "If you experience hard to read text in the menu bar, we recommend trying out the custom title bar."

I tried it and indeed this make the menu better. But it removes the native window manager titlebar which is undesirable.
This conflates the menu and the titlebar which are two really different things. The titlebar shouldn't be hidden as it has its own purpose.
At the moment, I'm left to use the inferior native menu because I can't set the config switch.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:07:43.495Z)
OS version: Linux x64 4.15.0-1026-oem

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|15.39GB (5.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|9.1.0
quitcontrol-vscode|art|3.0.0
better-toml|bun|0.3.2
whitespace-plus|dav|0.0.5
gitlens|eam|8.5.6
EditorConfig|Edi|0.12.5
githd|hui|2.1.0
rpm-spec|Lau|0.2.2
vscode-duplicate|mrm|1.2.1
indent-rainbow|ode|7.2.4
vscode-subword-navigation|ow|1.2.0
vscode-docker|Pet|0.4.0
rust|rus|0.4.10
whitespace|san|0.0.5
crates|ser|0.3.5
code-settings-sync|Sha|3.2.0
local-history|xyz|1.7.0
plsql-language|xyz|1.6.2
markdown-all-in-one|yzh|1.7.0

</details>

**Comment by sbatten** [comment]
@mleduque I agree that the naming of the setting is a bit confusing, but the custom menu bar and title bar are conflated as one contains the other in the custom implementation. Thanks for the feedback
