### ISSUE TITLE
Open New window - opens twice

### ISSUE THREAD

**Issue by kenduraghav** [Microsoft/vscode#63628]
Issue Type: <b>Bug</b>

When selecting "New Window" from file menu, it opens the window twice, after the recent update version 1.2.91

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.10240

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz (4 x 3492)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|7.92GB (3.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
sublime-babel-vscode|jos|0.2.10
debugger-for-chrome|msj|4.11.1
comment-ts|sal|0.8.0

</details>

**Comment by tejaskale** [comment]
Trying to open a file with `Ctrl + O` produces the same behavior.
```
Version: 1.29.0
Commit: 5f24c93878bd4bc645a4a17c620e2487b11005f9
Date: 2018-11-12T07:42:27.562Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

**Comment by alexr00** [comment]
Possibly related to #62524?

**Comment by bpasero** [comment]
@kenduraghav does it reproduce if you disable the custom menu via `window.titleBarStyle: native`?

**Comment by kenduraghav** [comment]
I haven't checked that option yet. I'll check it up tomorrow. 

Also I have seen  another issue. When we select  "Help" menu and select "About" option, it displays version info . When click "Okay" button, it's appears again. If you click again the OK button , then it disappears.

**Comment by bpasero** [comment]
@kenduraghav yeah please check

**Comment by kenduraghav** [comment]
It didn't reproduced after disabling the  "window.titleBarStyle".  

I have also checked "Help"> "About menu", and it is working fine now, version info dialog disappears for the first time itself.

**Comment by kenduraghav** [comment]
Sure I will install and try to reproduce the issue.

**Comment by bpasero** [comment]
Thanks

**Comment by kenduraghav** [comment]
@bpasero 

I have installed the VS - Code insider and tried recreating the issue and it seems to be working fine. 

Thanks
Raghav.
