### ISSUE TITLE
"Accept all Current/Incoming" does not work when selecting multiple files (in Source Control Tab)

### ISSUE THREAD

**Issue by daffodil2021** [microsoft/vscode#63621]
- VSCode Version: 1.29.1
- OS Version: Windows 10 / Ubuntu 16.04

Steps to Reproduce:
1. git rebase a repo
2. select more than one file with conflicts
3. right click selected files and do "Accept all Incoming" or "Accept all Current"
4. I would assume that this affects all selected files, not just one

Does this issue occur when all extensions are disabled?: Yes

**Comment by unional** [comment]
I have 50+ files in merge conflicts. Missing this is a big deal. 😛

**Comment by StephenKoller** [comment]
Seeing the same issue.

Similar / related:
1. git rebase repo
2. right click file with conflicts _without_ left-click / opening file in editor pane
3. click "Accept all Incoming" / "Accept all Current"
4. no changes are accepted, file in list remains unchanged.

**Comment by FanrayMedia** [comment]
Same here, I have 60+ files, this fix would be greatly appreciate it!

**Comment by jimthedev** [comment]
Even if you couldn't do it all at once it would be helpful to have these options:
"Accept all current and Save"
"Accept all incoming and Save"

Right now you have to do them one at a time and save them in the file pane too.

**Comment by chrmarti** [comment]
Git might help (see all top rated answer): https://stackoverflow.com/questions/10697463/resolve-git-merge-conflicts-in-favor-of-their-changes-during-a-pull

**Comment by EmandM** [comment]
It would be nice to do this from the ui though, as that would allow bulk merging of most files, and then manual handling of the rest.

It's also nice to resolve merge conflicts following the usual workflow, rather than having to use a different workflow for specific edge cases

**Comment by brcrista** [comment]
@chrmarti in this case, that Git command is not quite what I was looking for.  I wanted to manually merge a few files and then accept the rest.

I thought I could highlight a group under **Merge changes** and click **Accept All Incoming,** since this is how **Stage Changes** and **Unstage Changes** work.  But **Accept All ...** only seems to apply for one file at at time (that is, the first one you clicked on).

![image](https://user-images.githubusercontent.com/33549821/56664248-cc853700-6675-11e9-95bd-760d83effc0b.png)

**Comment by t0lkman** [comment]
I have `Accept incoming changes` but it looks like it does `Accept current changes`

Can somebody clarify which of them for the changes made locally?

**Comment by danielo515** [comment]
It not only not affects many files when you have them selected... You also have to left click on the new file you want to affect and then right click. So, for example if you have file-A selected by clicking on it with the left mouse button and then you directly right click on file-B the action you perform will still affect file-A

**Comment by Webunity** [comment]
Correct, this is annoying; in addition you have to SAVE the file after choosing accept all incoming.

So current workflow with merge conflicts; every file has to be selected by left-clicking, then right-clicking, choosing 'accept incoming' for example. You have to SAVE the file before you can "+" it.

Suggested workflow;
Select multiple files, right-click; accept incoming
Should do just that, save the files and add them to the staged changes

**Comment by chrmarti** [comment]
Fixed for July. Note that you still need to save, but can enable Auto Save to avoid that.

**Comment by Webunity** [comment]
Thnx @chrmarti :-)
