### ISSUE TITLE
Data tree exploded when expanding grandchild

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#63627]
Checkout branch https://github.com/Microsoft/vscode/tree/isidorn/debugTrees

1. Have the following watch expression `console`
2. Have the following program
`console.log('hey')`
3. Debug, expand console, first level all is good, second level tree explodes

**Comment by joaomoreno** [comment]
Repros in 8.9.1.

**Comment by joaomoreno** [comment]
Fixed!
