### ISSUE TITLE
Shortcut help overlay + popularity

### ISSUE THREAD

**Issue by mtrelis** [Microsoft/vscode#63634]
Issue Type: <b>Feature Request</b>

Suggestions :
* Holding eg CTRL down for x seconds shows a keyboard overlay with all binded combinations highlighted, if user hovers a key, show what it does

**Comment by sandy081** [comment]
@mtrelis Keybindings Editor has this feature.
- Open Keybindings Editor
- Enter into recording mode by pressing the `Record Keys` action in the input box
- Now press `Ctrl`
- It shows all keybindings 

Please check out this feature.
