### ISSUE TITLE
Alternate data streams are removed by saving

### ISSUE THREAD

**Issue by NotepadPlusUser** [Microsoft/vscode#6363]
- VSCode Version:1.1.0
- OS Windows Pro 10.0.10586.318 V1511 

Steps to Reproduce:
1. Open with VSCode a text file that has one or more alternate data stream files.
2. Make some small change in the text.
3. Save the file.
4. The ADS files have been removed.

I'm sure that there is a setting that will prevent VSCode removing ADS files when saving — they are, after all, a Windows special.  If not, could you please regard it as a bug and add such an option.

**Comment by bpasero** [comment]
@NotepadPlusUser I would expect this issue to be there in standalone node.js already, if you could try out a `fs.writeFile()` to reproduce the issue you should report it to them.

**Comment by NotepadPlusUser** [comment]
Thanks, bpasero, for looking at this issue and adding the 'bug' stamp to it.  I have to apologise, however, that I don't understand what your reply means.
1.  Is your reply directed to me, or to the developers of VSCode?
2. If the reply is to me, and is asking me to do something:
(a) What does 'standalone node.js' mean?  (I have a rather basic knowledgeof JScript.)
(b) What is a 'fs.writefile()'?
(c) Who is 'them?
(d) What more information is needed?  My 'steps to reproduce' seem a complete description of the issue and how to reproduce it.

**Comment by bpasero** [comment]
@NotepadPlusUser node.js is the framework we use for writing to files so it would be interesting if this bug is a bug in node.js (https://nodejs.org/en/). By writing a small script like the following we could see if the issue is node.js related or not (using fs.writeFileSync from https://nodejs.org/docs/v5.10.0/api/fs.html#fs_fs_writefilesync_file_data_options):

```
var fs = require("fs");

fs. writeFileSync(filepath, "data");
```

Where filepath is the path to the file with data streams.

**Comment by NotepadPlusUser** [comment]
Apologies bpasero, I'm completely out of my depth here.

I tried running the two lines as a bare .js file, but I get the error: Line 1, Char 1, Object expected.  I tried running it another environment with the same result,  By the way, in line 2, I had substituted filepath with the full path of the target file:
"D:\\DataForVallaHome\\Scripts\\WSCLibrary\\TestADSFiles.txt"

I tried instead to post you a TXT file that has two ADS TXT files attached, but of course the transfer to your servers removed them (I tested that by previewing and re-downloading).  

Then I tried zipping the file first, but that also removed the ADS files..  

So I'll have to leave it to the developers to sort out the origin of the problem and the fix.  It's a serious matter for windows users, because you often want to put file metadata in an ADS file.

**Comment by bpasero** [comment]
@NotepadPlusUser can you maybe explain how one gets a file with data streams on Windows? Then I can try to reproduce in node.js.

**Comment by NotepadPlusUser** [comment]
[Next morning]  Sure.  Using good old DOS is the most direct way.  The following 5 lines of DOS code will: 
1.  Create a file called "MainFile.txt" in the current directory
2.  Create two attached ADS files, "FirstADSFile.txt" and "SecondADSFile.txt"
3.  List the current directory — the /r switch is what displays the otherwise hidden ADS files.
 - - - - - - - -
Echo "This is the main file" > MainFile.txt
Echo "Some content for the first ADS file" > MainFile.txt:FirstADSFile.txt
Echo "Some content for the second ADS file" > MainFile.txt:SecondADSFile.txt
Dir /r
Pause
 - - - - - - - -
So to reproduce the problem:
1. Run these five lines from a DOS batch file or in a DOS window (preferably working within a directory with few files in it), and you will see the two attached ADS files listed on separate lines under MainFile.txt.
2. Then open MainFile.txt with VSCode, make a small change to the text, and save it.
3. Then run just the last two lines of the DOS code above, and the Dir /r command will now show that the two ADS files have been removed. I want to prevent that removal.

**Comment by NotepadPlusUser** [comment]
Thanks very much, bpasero, for handling this issue and confirming it.  I'll keep a watch on the updates as they come out, and report back.

**Comment by bpasero** [comment]
Thanks I am able to reproduce with just node.js so this is indeed an upstream issue it seems.

**Comment by f0zi** [comment]
All right, as @seishun mentioned:

> To preserve data in alternate streams, consider using the 'r+' flag and ftruncate instead

**Comment by seishun** [comment]
VS Code already uses this logic for hidden files thanks to https://github.com/Microsoft/vscode/pull/31733. So it just needs to be applied to all existing files.
