### ISSUE TITLE
VSCode built from source is unresponsive after 10s

### ISSUE THREAD

**Issue by maelvalais** [Microsoft/vscode#63632]
- VSCode Version: master (0d3a14402d88f0f555ab3250c3ffd4c45a251665) 1.16.0-19592-g0d3a14402d
- OS Version: Ubuntu 18.04

For some reason, after building vscode from source, `./scripts/code.sh` is usable for approx. 10s; after that, the window freezes. Same issue with `--disable-extensions` and even when disabling builtin extensions with `--builtin`. 

Steps to Reproduce:

1. clone vscode repo
2. `nvm use`
2. `yarn`
3. `yarn compile`
4. `./scripts/code.sh`

![peek 2018-11-21 12-22](https://user-images.githubusercontent.com/2195781/48899101-e0223c80-ee4e-11e8-93d2-c6d609b81b7e.gif)

**Comment by maelvalais** [comment]
I tried using `./scripts/code-cli.sh`... And it works without getting stuck after 10s! :-)
For some reason, `./scripts/code.sh` gets stuck

**Comment by bpasero** [comment]
@maelvalais does it reproduce if you try the same thing from the `electron-3.0.x` branch? Make sure to `git clean -xfd` before trying.
