### ISSUE TITLE
Project menu item - Copy path for Windows Subsystem for Linux (WSL) - Windows

### ISSUE THREAD

**Issue by efortes** [Microsoft/vscode#63633]
I often use the vscode WSL terminal to navigate to a file by right clicking a file in VS code and hitting the `Copy path` options. This will deliver me a windows path (  `C:\Users\`. ).
As i'm using WSL I want the possibility to copy an Unix path. The path would then be: `/c/Users`.

**Comment by alexandrudima** [comment]
You can write an extension to do this. An example is https://github.com/alexandrudima/vscode-copy-relative-path

**Comment by victor-ruben** [comment]
This extension does that: https://github.com/CoenraadS/Copy-WSL-Path
