### ISSUE TITLE
VSCode spawns a dontet process which locks dotnet obj folder

### ISSUE THREAD

**Issue by ivaylo5ev** [Microsoft/vscode#63649]
- VSCode Version: 
    1.29.1
- OS Version: 
    Windows 7 Professional
    Windows 8.1 Home

Steps to Reproduce:

1. Open a VSCode workspace or a folder with dotnet projects/solutions
2. At some point a child dotnet process is being spawned (process explorer would show it under some of the VSCode's sub-processes)
3. Some of the project's obj directory remains locked. This results in the following issues:
    - manual package updates, for instance when using paket would fail (ex. `paket update` / `paket install` )
    - manual `dotnet restore` calls would fail
4. Killing the dotnet process would resolve the issue -- the above commands would then run successfully, but the dotnet process is being immediatelly restarted and would cause the lock again after some time

Does this issue occur when all extensions are disabled?: No

It is inthuitive to believe this is caused by an extension that supports dotnet development, but I have quite a few of them installed -- OmniSharp, Ionide-FSharp and so on. Is there a way to determine which one of them is calling the misbehaving dotnet process, so at least the issue would be directed at the extension developer?

**Comment by alexandrudima** [comment]
@alexr00 @ivaylo5ev  This should be moved to https://github.com/OmniSharp/omnisharp-vscode

**Comment by alexr00** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#2701
