### ISSUE TITLE
Debug adapter process has terminated unexpectedly (read error)

### ISSUE THREAD

**Issue by ruslan-bikkinin** [Microsoft/vscode#63640]
Issue Type: <b>Bug</b>

Hi guys, [vscode-react-native](https://github.com/Microsoft/vscode-react-native) extension team is here. We noticed that since 1.29 new UI change was introduced: now debugging toolbar is shown immediately after user clicks on play button. Recently, in 1.28 toolbar has been shown only when debugger is attached (in our case we are making some preparation steps in the middle like building and running react native app). So, now in some cases when user clicks "stop" just after clicking "Play" button, error is shown: `Debug adapter process has terminated unexpectedly (read error)`
To demonstrate the problem I made two gifs: the first one shows how it worked in 1.28, the second - in 1.29.

**1.28**
![1 28](https://user-images.githubusercontent.com/30265843/48901213-c04a4300-ee65-11e8-9b45-5c9e32cd56f5.gif)

**1.29**
![1 29](https://user-images.githubusercontent.com/30265843/48901206-baecf880-ee65-11e8-8dc0-2e93343a634e.gif)

We are facing the problem on Mac, on Linux all work without any issues.

I suspected vscode-node-debug2 because we use node debug adapter from the builtin node-debug2 extension under the hood, but after lowering version to the one was used in 1.28 problem was still persisted.

Do you have any clues what could cause this?
Please let me know if you need any additional info from our side.

## Technical information

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|8.00GB (0.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-react-native|vsm|0.6.18

</details>

**Comment by isidorn** [comment]
@ruslan-bikkinin we are now showing the debug toolbar while a session is initalising becuase this gives users the option to terminate debugging before. More details here https://github.com/Microsoft/vscode/issues/62346

So the difference here is that you are now able to more easily stop the debug adapter while it is initialising.
In 1.28 you could still call F1 > stop to the same effect.

The actual issue here is that the debug adapter stops unexcepctedly if it is stopped while not fully initialised. And that I leave up to @weinand

**Comment by ruslan-bikkinin** [comment]
@weinand no

**Comment by weinand** [comment]
Pressing the Stop button while the debug session is starting, terminates the debug adapter (which is expected).
So the issue is that the UI shows an "unexpected termination" error despite the fact that the termination **is expected** and not a problem, right?

**Comment by ruslan-bikkinin** [comment]
@weinand yes, you are right.

**Comment by weinand** [comment]
Ok, we will have to fix the issue that error message arriving from the DA after the DA has been stopped should be ignored.

**Comment by weinand** [comment]
@ruslan-bikkinin I've released a fix for this. Please try in the latest if running out of source or use the next Insiders.

**Comment by ruslan-bikkinin** [comment]
@weinand thanks for the update! How frequent Insiders is built? I mean, when a new build including the fix will be released?

**Comment by weinand** [comment]
Insiders is built every weekday (Mon-Fri). But when preparing a Stable release (like this week), there are no Insiders releases for a few days. Expect the next Insiders on Thursday.

**Comment by ruslan-bikkinin** [comment]
@weinand just checked on VS Code 1.30.1 - seems to be the issue is gone. Thanks!
