### ISSUE TITLE
Search Issue With Turkish Character

### ISSUE THREAD

**Issue by muratersin** [Microsoft/vscode#63643]
This issue is exists from very long time.
When I search with '**i**' and without case sensitive, VS Code can't find words whic contain capital letter(**İ**).

Searched word: **'İptal'**
Search query: **'iptal'**
Match Case: **Disable**
result = nothing

- VSCode Version: 1.29.1
- OS Version: Windows 10 Home

**Comment by roblourens** [comment]
Hm, do other editors handle this properly? I guess you would have to put vscode in a Turkish mode so that `i` will match `İ` as uppercase

**Comment by Rasit-Vatan** [comment]
> This issue is being closed to keep the number of issues in our inbox on a manageable level, we are closing issues that are not going to be addressed in the foreseeable future: We look at the number of votes the issue has received and the number of duplicate issues filed. More details [here](https://aka.ms/vscode-out-of-scope). If you disagree and feel that this issue is crucial: We are happy to listen and to reconsider.
> 
> If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.
> 
> Thanks for your understanding and happy coding!

This issue IS crucial. Slows down development A LOT

![Image](https://github.com/user-attachments/assets/2a77cd9e-9340-4757-b4db-1273d7e6738d)

**Comment by ChrisIdema** [comment]
You can use regex: `[iİ]ptal`

<img width="524" height="249" alt="Image" src="https://github.com/user-attachments/assets/4c4faa6c-3ee4-42db-aa33-9d8ea3c070a6" />
