### ISSUE TITLE
Failed to continue: Check the debug console for details.

### ISSUE THREAD

**Issue by MichaelYgZhang** [Microsoft/vscode#63641]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. 
![image](https://user-images.githubusercontent.com/7804046/48901409-61e68a00-ee90-11e8-9626-001c9aac63f8.png)

2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by weinand** [comment]
Please file against Go extension.
