### ISSUE TITLE
Support for Waf build system

### ISSUE THREAD

**Issue by preechaim** [Microsoft/vscode#63652]
Can we get an officially support for waf build system?
Currently it's difficult to configure the IDE to work with existing projects that use the waf build tools for the code auto-completion and debugging to work correctly.
Is it possible to make the IDE to parse the waf configuration file and auto-configure itself to the build environment?

**Comment by weinand** [comment]
VS Code does not provide any built-in functionality for build systems.
So this feature sounds like an excellent opportunity for an extension.
