### ISSUE TITLE
Portable mode: Presence of data folder prevents --user-data-dir command-line override

### ISSUE THREAD

**Issue by myfonj** [microsoft/vscode#63657]
- VSCode Version: 1.29.1 bc24f98b5f70467bc689abf41cc5550ca637088e
- OS Version: Windows 10 (1709)

Steps to Reproduce:
1. Have content of `VSCode-...-.zip` unpacked into say `C:\apps\VSCode`
2. Create `C:\apps\VSCode\data` folder ([docs](https://code.visualstudio.com/docs/editor/portable))
3. Invoke `C:\apps\VSCode\bin\code.cmd --user-data-dir C:\other-data-dir`
 (aside: no [command-line](https://code.visualstudio.com/docs/editor/command-line) argument apparently works on C:\apps\VSCode\Code.exe  (#57185))

Expected outcome:
`C:\other-data-dir` folder is created and populated with default profile (or used if existed already).

Actual outcome:
`C:\apps\VSCode\data\user-data` folder is created and populated, rendering command-line switch ineffective.

4. delete `C:\apps\VSCode\data` folder
5. Repeat step 3.

Actual outcome is now correct.

**Comment by joaomoreno** [comment]
Yeah, the `user-data-dir` command line flag is ignored in portable mode. What is the actual use case for it?

**Comment by myfonj** [comment]
> What is the actual use case for it?

## Testing.
`code.cmd --user-data-dir C:\throwaway-vanilla-profile --extensions-dir C:\throwaway-no-extensions` should ensure you run clean slate vanilla VSC without need to wipe your settings, move any folder etc, resulting in better and more reliable bugreports. Perhaps.

## Consistency. 
It is [documented ](https://code.visualstudio.com/docs/editor/command-line#_advanced-cli-options) to do something, not documented not to do that in certain circumstances, so one could expect it to work all the time.  Command line arguments generally serve such purpose.

**Comment by joaomoreno** [comment]
> It is documented to do something, not documented not to do that in certain circumstances, so one could expect it to work all the time. Command line arguments generally serve such purpose.

Well, you could apply the same argument about portable: it is documented to do something, not documented not to do that in certain circumstances (when using `--user-data-dir`). It comes down to: what has priority?

I think you are right, though, in that a command line flag should have priority.

**Comment by myfonj** [comment]
BTW, I think that until this issue is resolved it would be worth mentioning this peculiarity in the aforementioned [documentation](https://code.visualstudio.com/docs/editor/command-line#_advanced-cli-options) page to prevent possible frustration of fellow portable mode users.

I. e. current
> `--user-data-dir <dir>` | Specifies the directory that user data is kept in, (...).

Amend like
> `--user-data-dir <dir>` | **Unless using [portable mode](https://code.visualstudio.com/docs/editor/portable)**, specifies the directory that user data is kept in, (...).
