### ISSUE TITLE
ctrl + backquote(`) is not working in Windows 10 (JP) with US-keyboard

### ISSUE THREAD

**Issue by yamavol** [Microsoft/vscode#63659]
Issue Type: <b>Bug</b>

Steps to reproduce:

1. Setup Windows10 (1803) in Japanese language (or whatever non-US language?)
2. Open Windows10 preference > "Time and Language" > "Region & Language" > Options for display language
3. Change keyboard layout from JP(106/109) to US(101/102) , reboot
3. Open VSCode, press Ctrl + `
4. The terminal won't showup

## Additional Information
- When I press the "`" key, the vscode detects as "oem_3".
- When I press the "ctrl + `" key, the vscode detects as "ctrl + unknown".
- "ctrl + shift + `" works and the new terminal opens. Only toggle terminal does not work.

At first I noticed that my laptop (Thinkpad T480s, Win10/JP + US keyboard) cannot open the terminal with default key bindings. To investigate the problem,  I also tested with a USB-keyboard (US layout) and the situation did not changed. Furthermore, I tested the USB-keyboard with another Win10 desktop machine, and the problem was reproduced. 

I feel this is a bug, but if someone knows how to avoid this, it would be helpful. 

[KeyMappings.txt](https://github.com/Microsoft/vscode/files/2608747/KeyMappings.txt)

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (8.70GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by alexandrudima** [comment]
Can you please hover over the keybinding when you press <kbd>Ctrl</kbd>+<kbd>`</kbd> and take a screenshot:

![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

**Comment by alexandrudima** [comment]
@yamavol Thank you for the screenshots and explanations. This indicates to me that the OS is reserving <kbd>Ctrl</kbd>+<kbd>`</kbd> for some IME purposes (when having the Japanese keyboard layout installed perhaps?).

I don't think there is anything we can do on our side (VS Code) in this case. Perhaps there are some Windows options that can be tweaked to free up/change that keybinding to something else...
