### ISSUE TITLE
JSON: Intellisense appears and disappears every keystroke

### ISSUE THREAD

**Issue by thany** [Microsoft/vscode#63654]
Issue Type: <b>Bug</b>

This bug occurs when in JSON, while typing a key. On every keystroke, the intellisense menu appears and disappears with the suggestion to quote the key. So this feature only works when typing keys that consist of an uneven number of characters, since intellisense disappears at every even character.

I've made a recording:
[intellisense in json.zip](https://github.com/Microsoft/vscode/files/2608629/intellisense.in.json.zip)

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.74GB (17.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
Bookmarks|ale|9.3.0
html-class-suggestions|And|1.0.7
color-info|bie|0.5.0
mustache|daw|1.1.1
vscode-eslint|dba|1.7.0
vscode-babel-coloring|dza|0.0.4
EditorConfig|Edi|0.12.5
file-icons|fil|1.0.16
auto-close-tag|for|0.5.6
duplicate|gee|1.0.1
beautify|Hoo|1.4.7
docthis|joe|0.7.1
vscode-duplicate|mrm|1.2.1
vscode-docker|Pet|0.4.0
vscode-sort-json|ric|1.13.0
code-settings-sync|Sha|3.2.0
rewrap|stk|1.9.1
vscode-svg-previewer|vit|0.2.0

</details>

**Comment by alexr00** [comment]
@mjbvz, should general intellisense issues go to you? Feel free to re-assign to me if not!

**Comment by thany** [comment]
Yep, it sure does.

**Comment by aeschli** [comment]
That's the expected behaviour of quick suggest: code completions are automatically shown when typing at the end of a word. You cam configure/disable this in the settings.

**Comment by thany** [comment]
No it can't be. Please reopen.
Intelligence flickers on and off while typing. How is that expected? If this is really meant to be, please reopen still, because it's undesirable. It also only happens in JSON and (so far) not in any other languages, so that all on its own makes it a bug.
