### ISSUE TITLE
VS Code does not launch after update 1.29.1 when offline.

### ISSUE THREAD

**Issue by rishabh-327** [Microsoft/vscode#63658]
Issue Type: <b>Bug</b>

1. Disconnect internet.
2. Launch VS Code

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (4.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by myfonj** [comment]
Tracked in #7570 / electron/electron#6437

Btw on machine with older Windows version (1709) it is still possible to start VSC while offline.

**Comment by JaWiD2** [comment]
Too many people faced with this issue on windows 10 (1809) and the only thing that they do is close issue!
obviously there is two way: fall backwards or migrating to Mac/Linux 👎🏻👎🏻👎🏻

**Comment by myfonj** [comment]
From the main issue(s) tags it appears to be fixed in Electron 3; I've [asked for estimate](https://github.com/Microsoft/vscode/issues/59634#issuecomment-432942761) when it will come into stable branch in another dupe but got no response.
Overall it seems strange: bug in Electron core that exhibits itself only on certain Windows versions, or other yet undiscovered circumstances.  Strange that the main Electron bug is still "open" ATM.

**Comment by bpasero** [comment]
Q1 2019.

**Comment by lubrogit** [comment]
How can you close the issue if it is still unsolved? Code still does not run without Internet on Win10-1809.

**Comment by Karthik-Sharavana** [comment]
vs code opens only when it is connected to internet, if i try to open offline it is not opening.
And even when i try to troubleshoot the app from settings , vs code opens only if internet is connected when i click "Test the program" , in offline after i click "Test the program" the app doesnt open

my windows 10 os v:1809
vs code v:1.25

please help me,
thank you..
