### ISSUE TITLE
Suggestion: command to reset workspace

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/vscode#63668]
When I move between tasks in a given project, I often perform the following commands to achieve the effect of resetting the workspace (as if I had just opened it for the first time):

- `workbench.files.action.collapseExplorerFolders` (then manually expand the root folder)
- `workbench.action.closeAllEditors`

I would like to suggest a new command that performs both of these (and any others), to allow this goal to be achieved in a single command.

I suppose this would also be possible if VS Code allowed commands to be composed, i.e. macros?

**Comment by bpasero** [comment]
@OliverJAsh I think there are extensions to do this (run a list of commands as one command), have you tried?

**Comment by OliverJAsh** [comment]
Using https://github.com/geddski/macros, this almost does the trick:

``` json
{
  "macros": {
    "resetWorkspace": [
      "workbench.action.closeAllEditors",
      "workbench.files.action.collapseExplorerFolders"
    ]
  }
}
```

However, AFAIK there is no command which performs `workbench.files.action.collapseExplorerFolders` **then** manually expands the root folder (which is what VS Code does when you initially open a workspace).

**Comment by OliverJAsh** [comment]
I created the following keyboard shortcut which works well enough:

```json
  {
    "key": "cmd+alt+r",
    "command": "runCommands",
    "args": {
      "commands": [
        "workbench.action.closeAllEditors",
        "workbench.files.action.collapseExplorerFolders",
        "workbench.action.terminal.killAll",
        "workbench.action.reloadWindow"
      ]
    }
  }
```
