### ISSUE TITLE
Unable to setup Powerline font on Ubunu 18.04 and Zsh

### ISSUE THREAD

**Issue by GaurangTandon** [Microsoft/vscode#63665]
VSCode 1.29.1 

This is how my terminal looks:

![image](https://user-images.githubusercontent.com/6308683/48918921-b3554000-eeb5-11e8-9497-9df3d4817d9c.png)

and this is how the vscode terminal looks:

![image](https://user-images.githubusercontent.com/6308683/48918932-c7993d00-eeb5-11e8-8d61-b5195157337e.png)

I have looked at all of the following links and none of them work for me. 

- tried all different font names listed on https://github.com/powerline/fonts. Using any font name mentioned gives the error "only supports monospace fonts."
- looked at this [widely referred comment](https://github.com/Microsoft/vscode/issues/15119#issuecomment-259248159). Unfortuntely setting my Ubuntu terminal preferences to use "PowerlineSymbols,Medium" messes it up, so I use Monospace Regular. I am assuming issue's specific to mac.
- also tried [this font](https://github.com/Microsoft/vscode-docs/issues/675#issuecomment-378946509), same monospace warning.
- also these blogs - [dev.to](https://dev.to/mattstratton/making-powerline-work-in-visual-studio-code-terminal-1m7) and [urbandiscourse](http://www.urbandiscourse.com/2017/02/11/configure-visual-studio-code-integrated-terminal-oh-my-zsh/) and [medium](https://medium.com/@hippojs.guo/vs-code-fix-fonts-in-terminal-761cc821ef41)
- related [so question](https://stackoverflow.com/questions/41574169/how-do-i-use-the-meslo-font-for-visual-studio-code/41959837)

I have also tried changing `"terminal.integrated.shell.linux": "/bin/zsh",` to `"usr/bin/zsh"` with no luck.

Please suggest alternative solution. Thanks.

**Comment by ChipTechno** [comment]
Open setting menu and find "Terminal>Integrated:Font Family", set the font "DejaVu Sans Mono for Powerline" .
You can get the font from https://github.com/powerline/fonts
or the packet "ttf-dejavu-sans-mono-powerline"

**Comment by Tyriar** [comment]
![image](https://user-images.githubusercontent.com/2193314/49312325-aed1ee00-f498-11e8-8cd7-cbd698273011.png)

This means that the font is not being picked up correctly, so something is wrong with the fontFamily setting.
