### ISSUE TITLE
Inconsistent scroll (main editor/integrated terminal)

### ISSUE THREAD

**Issue by JCKodel** [Microsoft/vscode#63669]
Issue Type: <b>Bug</b>

Apart from VSCode not complying with Windows WheelScroll setting (mine is 3, VSCode scrolls 4.1 on main editor) (there is another bug opened for both these bugs), there is a third bug related to Integrated Terminal:

This is my screen, without any scroll:

![image](https://user-images.githubusercontent.com/379339/48923799-c6a5e280-ee98-11e8-9be8-972e46d6cc3c.png)

This is the same screen, with 1 click of the mouse wheel:

![image](https://user-images.githubusercontent.com/379339/48923815-efc67300-ee98-11e8-9348-939e8f76e05c.png)

The main editor scrolled 4 lines (and a bit more) - ok, there are issues open for that.
The terminal has scrolled 1 entire screen!
This is where terminal should scroll (considering the two bugs above (not comply with Windows settings + top margin being cut)):

![image](https://user-images.githubusercontent.com/379339/48923841-24d2c580-ee99-11e8-8a11-c5fc65500355.png)

It seems VSCode is scrolling a fixed amount of lines, because with terminal window shorter, the first line after the scroll remains the same:

No scroll:
![image](https://user-images.githubusercontent.com/379339/48923878-85fa9900-ee99-11e8-897a-c299edf8af7a.png)

1 scroll using mouse wheel:

![image](https://user-images.githubusercontent.com/379339/48923884-9874d280-ee99-11e8-9e33-f0de906db1cc.png)

P.S.: My monitors are 4K (3840 x 2160 pixels) scalled to 200% (so they are 1920 x 1080 without DirectText/GDI/WPF horrible font rendering =P). Mentioning that because there is a LOT of softwares that don't work well in this configuration (not sure if is the issue here, since Electron is fine with that).

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.96GB (19.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-svgviewer|css|1.4.7
tslint|eg2|1.0.40
vscode-npm-script|eg2|0.3.5
path-autocomplete|ion|1.13.0
debugger-for-chrome|msj|4.11.1
vetur|oct|0.13.0
material-icon-theme|PKi|3.6.1
autoimport|ste|1.5.3
language-stylus|sys|1.10.0
stylus-supremacy|thi|2.12.7
highlight-matching-tag|vin|0.8.4

</details>

**Comment by Tyriar** [comment]
Moved to https://github.com/xtermjs/xterm.js/issues/1805
