### ISSUE TITLE
inno_updater.exe -System Error

### ISSUE THREAD

**Issue by NaumanMoazzam** [Microsoft/vscode#63666]
- VSCode Version: 1.28.2
- OS Version: Windows 8.1
- Issue: BUG

Steps to Reproduce:

1. When quitting VSCode

Does this issue occur when all extensions are disabled?: Yes/No : YES

![capture](https://user-images.githubusercontent.com/30693949/48918233-1abac200-eead-11e8-85c5-cc729684682a.PNG)

This issue was already reported, but it was closed [#57028]. Picture attached.

![capture123](https://user-images.githubusercontent.com/30693949/48918324-8bfa7500-eead-11e8-94b9-13b688b042ba.PNG)

**Comment by joaomoreno** [comment]
This is very odd. I suggest disabling windows background updates with the `update.enableWindowsBackgroundUpdates` setting.

**Comment by NaumanMoazzam** [comment]
When i close my VS Code it shows my this error every time, as you suggested to disable update. I have done that too. It still produced that error. 
Plus I have tried disabling all the extensions i am using, and tried without opening any project in VS Code, just welcome page.

Now what more info you needs? @joaomoreno

**Comment by joaomoreno** [comment]
I am 100% sure that if you set `update.enableWindowsBackgroundUpdates` to `false`, and restart Code, it's impossible for you to get that error. This will not disable updates, it will disable background updates... you will still get updates, but not in the background. And they will not use `inno_updater`. So, please retry setting that to false and restarting VS Code.

**Comment by NaumanMoazzam** [comment]
This didn't worked @joaomoreno .
Screenshot attached to show you that Windows Background updates are off.
![capture](https://user-images.githubusercontent.com/30693949/49280913-1c881500-f4ad-11e8-92a2-ce05f2fea7f6.PNG)

**Comment by joaomoreno** [comment]
After you disable window background updates, can you restart your machine before attempting to get a new update?

**Comment by NaumanMoazzam** [comment]
Okay, i did restarted the machine but i was still getting this error. I update my machine uninstall some background services. And now it is not showing. It's resolved. Thanks.
