### ISSUE TITLE
The window is no longer responding

### ISSUE THREAD

**Issue by arsari** [Microsoft/vscode#63660]
- VSCode Version: 1.29 (user setup)
- OS Version: Windows 10

Steps to Reproduce:

1. The error shows up when trying to open a workplace with various projects on it. I tested with some extensions disable and get the same error.
2. VS Code opens without errors if no workplace or folder is selected. If one folder is selected open without errors. If after this I try to open to folders I get the Error again.
3. I have the same VS Code version and same extensions in my mac (high sierra 10.3.6) and don't get the error.

Does this issue occur when all extensions are disabled?: Yes/No
If all the extensions are disbale the error doesn't show. I start to eneble each extension and found that the extension CSS Peek cause VS Code to crash.

**Comment by alexr00** [comment]
Can you open this issue with CSS Peek? If enabling CSS Peek is causing VS Code to crash then the issue is with that extension 😊

**Comment by arsari** [comment]
Hello @alexr00

Yes, I open an Issue ticket in CSS Peek.  I added the reason of my error here for reference to others in the community.
