### ISSUE TITLE
Do not show (hide) default workspace settings pane (when editing settings.json)

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#63661]
When I open `vscode/settings.json` it shows split panel:

![image](https://user-images.githubusercontent.com/736697/48915574-f8bb4280-eea0-11e8-8a39-80c13c84fd36.png)

it is not very convenient if the pane is narrow already, and I don't see the ability to hide this `Default Workspace Settings` part, which not need in most of the cases.

**Comment by sandy081** [comment]
There is a setting `workbench.settings.openDefaultSettings` to disable this. Please use it.

**Comment by whitecolor** [comment]
Nice thanks.
