### ISSUE TITLE
Feature Request - A rich layout and options for SCM penel similar to Github Desktop.

### ISSUE THREAD

**Issue by iyashpal** [Microsoft/vscode#63678]
My colleagues including me do's 70% of all git operations on a separate desktop app [Github Desktop](https://desktop.github.com/) and cli. VSCode has a inbuilt SCM tool that is a benifit for us. But we are missing some functionalities from Github Desktop. Like 
1. **Commit Title**, **Commit Description** or put a button to commit instead of shortcut key **Ctrl+Enter**.
2. A **Push** button.
3. **Commit History**.

**Github Desktop** Commit Tab
![changes](https://user-images.githubusercontent.com/19922707/48930704-550d7900-ef18-11e8-88d1-a9ac5063eedd.png)

**Github Desktop** History Tab
![history](https://user-images.githubusercontent.com/19922707/48930711-59399680-ef18-11e8-99dd-21664043cfa5.png)

Is it possible to have above functionality into the **SCM panel** ?
![vscode scm layout](https://user-images.githubusercontent.com/19922707/48930831-014f5f80-ef19-11e8-8a62-85cd6ae3458b.png)

Thank you for your consideration

**Comment by joaomoreno** [comment]
1. Commit title and description are already supported: just press <kbd>Enter</kbd>
2. Fair enough, though we do support keybindings to actions, you can already today have a key which simply pushes. You can also contribute an extension which adds a `Push` command to the Git repo's inline menu. There's is also already a `Commit` button, above the input box.
3. #68
