### ISSUE TITLE
files.exclude does not support ./foldername

### ISSUE THREAD

**Issue by epDHowwD** [Microsoft/vscode#63679]
It is [documented](https://code.visualstudio.com/docs/editor/codebasics#_advanced-search-options) that files.exclude should support to match first level elements only by filtering for patterns starting with `./`. But it does not work at all. 
Excluding `foldername` works instead, like `./foldername` should work, matching objects on top level only, but not objects deeper in the tree. To get this, `**/foldername` has to be used.

Please align both files.exclude and search panel behavior wrt. pattern matching with each other in case you want to share documentation for them. Alternatively, please split documentation to indicate different behavior.

- VSCode Version: 1.28.2
- OS Version: Ubuntu 16.04.5

**Comment by roblourens** [comment]
#63303
