### ISSUE TITLE
please read my content 

### ISSUE THREAD

**Issue by sylviatanggit** [Microsoft/vscode#63674]
Issue Type: <b>Bug</b>

when i changed my code and already saved it. after a day ,vscode  opened an old version of my page autoly ,and i pressed ctrl + v ,my page back to the old version......why would it happen....

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:47:15.448Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|5.90GB (2.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|2.5.1
vscode-icons|rob|7.28.0

</details>

**Comment by bpasero** [comment]
@sylviatanggit it is possible that the file was changed on disk outside of VSCode?
