### ISSUE TITLE
After Visual studio upgrade and relaunch, icon in Dock becomes tiny

### ISSUE THREAD

**Issue by sameeragrawal** [Microsoft/vscode#63681]
Issue Type: <b>Bug</b>

After Visual studio upgrade and relaunch, icon in Dock becomes tiny

have to reboot Dock process to get the icon back to normal

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (0.48GB free)|
|Process Argv|-psn_0_327760|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode/issues/63068

**Comment by bpasero** [comment]
@sameeragrawal can you show a screenshot?
