### ISSUE TITLE
Delete / Move modal UI

### ISSUE THREAD

**Issue by DorianMaliszewski** [Microsoft/vscode#63689]
Hi evereyone,

I doesn't find an issue related that but on my ubuntu 18.04 LTS i took the .deb package on the official website and i have a trouble when i try to move / delete a file i join a screencshot of the modal displayed/

![exemple_error1](https://user-images.githubusercontent.com/24531136/48949374-0f60a880-ef38-11e8-9caa-b1d5ab111356.png)
![exemple_error2](https://user-images.githubusercontent.com/24531136/48949375-0f60a880-ef38-11e8-8eb0-0a3d4253ad75.png)

Sometimes options aren't display at all (fortunately i know vscode :smile: ).

If someone have a solution for that

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by DorianMaliszewski** [comment]
No problem in VS Code Insiders
