### ISSUE TITLE
Search input box is 2 row high

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#63685]
Issue Type: <b>Bug</b>

The Search input box is 2 rows high. I have been using search, no particular steps...

![image](https://user-images.githubusercontent.com/5047891/48941624-96078c80-ef1c-11e8-82aa-ea328efc5948.png)

VS Code version: Code - Insiders 1.30.0-insider (8b86554f3af4b47bb14dd519b89c780d6da5fca7, 2018-11-23T06:17:27.340Z)
OS version: Windows_NT ia32 10.0.17134

**Comment by usernamehw** [comment]
Isn't it new feature: after pressing <kbd>Shift</kbd>+<kbd>Enter</kbd> for easier newlines searching?

**Comment by alexandrudima** [comment]
But shouldn't it shrink back to 1 row when the text does not contain a `\n` ?

**Comment by roblourens** [comment]
That's weird. I don't see that happening. It's always like that, or did it just show up at some point?

**Comment by alexandrudima** [comment]
I cannot reproduce when I try. I will keep an eye out and if I see it again I'll update the issue.

**Comment by roblourens** [comment]
The sizing is done just by measuring the text in a `.mirror` div next to the textarea. Would help if you can poke around there in the DOM to see if anything looks obviously out of place.

**Comment by alexandrudima** [comment]
And now I have steps :) :

* type a long string to get two rows
* resize the viewlet to make space on a single row for the long string
* the input does not go back to 1 row

![63685](https://user-images.githubusercontent.com/5047891/49074135-5c909300-f234-11e8-89b9-91baba0be0de.gif)

**Comment by roblourens** [comment]
Oh, good catch
