### ISSUE TITLE
"Go to file..." (Ctrl+P) could support paths starting with `./`

### ISSUE THREAD

**Issue by janpio** [microsoft/vscode#63687]
Currently you can not find files if you input for example `./fastlane/spec/fixtures/fastfiles/FastfileGrouped` to find the file that is in `fastlane/spec/fixtures/fastfiles/FastfileGrouped`. But it is quite common in ruby code to refer to files in this way, also `rspec` outputs the path of failing test files in this way.

It would be great if `./` could just be stripped out when looking for files in the "Go to file..." dialog.

**Comment by chrmarti** [comment]
We'd have to decide between this and #46242.

**Comment by janpio** [comment]
Can't the search do both?

(Although I personally always thought of this to be a project/workspace search, not relative to the current file...)
