### ISSUE TITLE
Turn on terminal TypedArray-based buffer by default

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#63688]
```ts
"terminal.integrated.experimentalBufferImpl": "TypedArray"
```

Testing should focus on resizing the terminal as well as inputting emoji, CJK and "high plane chars" (those with a char code above 65535).

**Comment by Tyriar** [comment]
@nojvek glad to hear you've been testing it out! Much more in the works 😃

This particular one was pretty much all @jerch 💪 https://github.com/xtermjs/xterm.js/issues/791

**Comment by jerch** [comment]
Thx @nojvek! We still have a few more perf gems to come with the next releases, stay tuned :smiley_cat: 

And thx for testing, we need every helping hand to cover the edge cases, esp. for those bigger changes.

**Comment by nojvek** [comment]
Btw I used vscode terminal extensively to test v2 of matrix-rain. 

You can try it at `npm install -g matrix-rain; matrix-rain`

Vscode terminal is the fastest out of iTerm and macOS default. 

So looking forward to a super fast terminal (hopefully standalone someday).

**Comment by Tyriar** [comment]
@nojvek nice! https://github.com/xtermjs/xterm.js/pull/1790 will make it even better when that eventually goes in

**Comment by Tyriar** [comment]
I removed the JsArray completely as TypedArray is very stable at this point.
