### ISSUE TITLE
After project close , vscode won't terminate the Language Server

### ISSUE THREAD

**Issue by netroby** [Microsoft/vscode#63680]
I open three project,(one php, one golang, one java)
After close php project, the vscode won't terminate the php language server .
![qq 20181123155748](https://user-images.githubusercontent.com/278153/48932882-fdcbd080-ef38-11e8-9d4e-2b4f6ab562e6.png)
![qq 20181123155844](https://user-images.githubusercontent.com/278153/48932883-fe646700-ef38-11e8-9317-d8d9c0b7d7f0.png)

You can see my pictures. No php project, but the php language server still exists.

**Comment by roblourens** [comment]
Please file this on the PHP extension you are using

**Comment by netroby** [comment]
https://github.com/felixfbecker/php-language-server
php language server

**Comment by netroby** [comment]
![qq 20181127103955](https://user-images.githubusercontent.com/278153/49055020-20a7fe80-f231-11e8-9e72-e28007feb5ca.png)
