### ISSUE TITLE
Terminal Exit Code 1067 @Windows10

### ISSUE THREAD

**Issue by lcardosobr** [Microsoft/vscode#63696]
Issue Type: <b>Bug</b>

1. Opening terminal with `Ctrl + '` or by menu `Terminal > New Terminal`;
2. The terminal closes with `The terminal process terminated with exit code: 1067` message.

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (8.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-generate-getter-setter|DSK|0.5.0
tslint|eg2|1.0.40
code-runner|for|0.9.5
svgeditor|hen|2.7.0
csharpextensions|jch|1.3.0
docthis|joe|0.7.1
csharpfixformat|Leo|0.0.76
Angular-BeastCode|Mik|7.0.16
csharp|ms-|1.17.1
debugger-for-chrome|msj|4.11.1
material-icon-theme|PKi|3.6.1
bootstrap4-vscode|the|5.0.0

</details>

![windows10-vscode-exitcode1067](https://user-images.githubusercontent.com/33897034/48944443-d3b0e900-ef0d-11e8-9db8-931589f6e2dd.png)

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
