### ISSUE TITLE
markdown files preview does not save scroll position

### ISSUE THREAD

**Issue by AbdullahWali** [microsoft/vscode#63690]
Issue Type: <b>Bug</b>

1. Open markdown file preview
2. scroll down
3. switch tabs and then come back to the markdown tab
=> Scroll position is reset to top

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (7.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
rdetools|Blo|0.1.10
sftp|lix|1.7.7
python|ms-|2018.10.1
cpptools|ms-|0.20.1

</details>

**Comment by skprabhanjan** [comment]
@mjbvz , looking into this :)

**Comment by skprabhanjan** [comment]
@AbdullahWali and @mjbvz , It seems to be retain the scroll position when i am trying.
I am not able to reproduce this bug.
Could you please help me more with this ?

**Comment by Robhox** [comment]
I could reproduce the bug with any md file (on macOS and windows). The scroll position is not saved for the **Mardown Preview** (which you can get by pressing ⇧⌘V or Ctrl+Shift+V in a md file).
I'm looking at this issue right now to fix it

**Comment by skprabhanjan** [comment]
@Robhox , Thanks for the update.
Are you looking into this or should I continue solving this ?

**Comment by Robhox** [comment]
@skprabhanjan I would love to solve it if it's ok for you

**Comment by skprabhanjan** [comment]
@Robhox , sure go ahead , seems like your first contribution , so will leave this to you :)

**Comment by Robhox** [comment]
@skprabhanjan Did you had any ideas how to fix this issue? I'm struggling to find where the position is saved when you switch tabs.

**Comment by skprabhanjan** [comment]
@Robhox , Need to check it , Will get back to you after checking it :)

**Comment by warpdesign** [comment]
Also, the markdown preview seems to be reloaded/regenerated once the user switches back to a preview tab, so during ~800ms there's a blank area which I find quite annoying too.

**Comment by krupenja** [comment]
Reproducible on 1.38.1, sample file inside ZIP: 
[Untitled-1.md.zip](https://github.com/microsoft/vscode/files/3611452/Untitled-1.md.zip)

**Comment by murphyke** [comment]
This is another variation of the same situation: if you open a side-by-side preview, then open another tab in the preview sub-window, then switch back to the preview tab, the scroll position in the preview will have been lost.

**Comment by thadras** [comment]
Want to report that this issue seems to reproduce for the case of using the following experimental setting as found via issue #84520:
```json
"workbench.experimental.editorAssociations": [
    {
        "viewType": "vscode.markdown.preview.editor",
        "filenamePattern": "*.md"
    }
]
```

Whereby, I find it convenient to be able to open `md` files within the `preview` context.  However, it appears that doing so somehow interferes with the applications scroll state when switching between tabs.  As such, the file's preview tab will lose its scroll position when navigating away from and returning to the `md` file.  

Note, I have built the VSCode application from the latest git, and out-of-box the issue does not reproduce without the experimental setting.  Hence, it seems that using preview viewtype as default for md files contributes to the loss of scroll position when switching between tasks.

Given the `help wanted` label, I am reviewing the `vscode` in hopes of gaining a better understanding of the internals, but the learning curve will take some effort to surmount.

**Comment by devuxer** [comment]
I've had this problem with VSCode as long as I can remember. I just installed version 1.44.0 on my Thinkpad, and it's still definitely happening. As I read through the release notes, I like to try out the new features as I read. With a document this long, it definitely causes some frustration having to keep finding my place again after each try. Hoping someone can figure out what's causing this 🙏

**Comment by coffee-sgr** [comment]
The extension descriptions page (extension sidebar -> click on any extension that has a long description) seems to have a similar issue. The page seems to reload when switching to another tab and switching back, resetting the scroll position.

![Screenshot_2020-04-18_22-22-03](https://user-images.githubusercontent.com/29776557/79640245-1a6a4780-81c3-11ea-81fc-08ab31a72d5e.png)

**Comment by gjsjohnmurray** [comment]
See also #27498

**Comment by leosdad** [comment]
This is very annoying and distracting especially when there is a new VS Code release which are very long. Please take a look at it whenever possible.

**Comment by DavidMGini** [comment]
Ping
This is still annoying
